Doc: IGLib EXTENDED: AForge.Vision.Motion.BlobCountingObjectsProcessing Class Reference
AForge.Vision.Motion.BlobCountingObjectsProcessing Class Reference
Motion processing algorithm, which counts separate moving objects and highlights them.
Public Member Functions
BlobCountingObjectsProcessing ()
Initializes a new instance of the BlobCountingObjectsProcessing class.
BlobCountingObjectsProcessing (bool highlightMotionRegions)
Initializes a new instance of the BlobCountingObjectsProcessing class.
BlobCountingObjectsProcessing (int minWidth, int minHeight)
Initializes a new instance of the BlobCountingObjectsProcessing class.
BlobCountingObjectsProcessing (int minWidth, int minHeight, Color highlightColor)
Initializes a new instance of the BlobCountingObjectsProcessing class.
BlobCountingObjectsProcessing (int minWidth, int minHeight, bool highlightMotionRegions)
Initializes a new instance of the BlobCountingObjectsProcessing class.
unsafe void ProcessFrame (UnmanagedImage videoFrame, UnmanagedImage motionFrame)
Process video and motion frames doing further post processing after performed motion detection.
void Reset ()
Reset internal state of motion processing algorithm.
Properties
bool HighlightMotionRegions [get, set]
Highlight motion regions or not.
Color HighlightColor [get, set]
Color used to highlight motion regions.
int MinObjectsWidth [get, set]
Minimum width of acceptable object.
int MinObjectsHeight [get, set]
Minimum height of acceptable object.
int ObjectsCount [get]
Number of detected objects.
Rectangle[] ObjectRectangles [get]
Rectangles of moving objects.
Private Attributes
BlobCounter blobCounter = new BlobCounter()
Color highlightColor = Color.Red
bool highlightMotionRegions = true
Detailed Description
Motion processing algorithm, which counts separate moving objects and highlights them.
The aim of this motion processing algorithm is to count separate objects in the motion frame, which is provided by motion detection algorithm. In the case if HighlightMotionRegions property is set to true, found objects are also highlighted on the original video frame. The algorithm counts and highlights only those objects, which size satisfies MinObjectsWidth and MinObjectsHeight properties.
<note>The motion processing algorithm is supposed to be used only with motion detection algorithms, which are based on finding difference with background frame (see SimpleBackgroundModelingDetector and CustomFrameDifferenceDetector as simple implementations) and allow extract moving objects clearly.</note>
Sample usage:
// create instance of motion detection algorithm
IMotionDetector motionDetector = new ... ;
// create instance of motion processing algorithm
BlobCountingObjectsProcessing motionProcessing = new BlobCountingObjectsProcessing();
// create motion detector
MotionDetector detector = new MotionDetector(motionDetector, motionProcessing);
// continuously feed video frames to motion detector
while (...)
{
    // process new video frame and check motion level
    if ( detector.ProcessFrame( videoFrame ) > 0.02 )
    {
        // check number of detected objects
        if ( motionProcessing.ObjectsCount > 1 )
        {
            // ...
        }
    }
}
See also
MotionDetector, IMotionDetector
Constructor & Destructor Documentation
BlobCountingObjectsProcessing() [1/5]
AForge.Vision.Motion.BlobCountingObjectsProcessing.BlobCountingObjectsProcessing () inline
Initializes a new instance of the BlobCountingObjectsProcessing class.
BlobCountingObjectsProcessing() [2/5]
AForge.Vision.Motion.BlobCountingObjectsProcessing.BlobCountingObjectsProcessing (bool highlightMotionRegions) inline
Initializes a new instance of the BlobCountingObjectsProcessing class.
Parameters
highlightMotionRegions Highlight motion regions or not (see HighlightMotionRegions property).
BlobCountingObjectsProcessing() [3/5]
AForge.Vision.Motion.BlobCountingObjectsProcessing.BlobCountingObjectsProcessing (int minWidth, int minHeight) inline
Initializes a new instance of the BlobCountingObjectsProcessing class.
Parameters
minWidth Minimum width of acceptable object (see MinObjectsWidth property).
minHeight Minimum height of acceptable object (see MinObjectsHeight property).
BlobCountingObjectsProcessing() [4/5]
AForge.Vision.Motion.BlobCountingObjectsProcessing.BlobCountingObjectsProcessing (int minWidth, int minHeight, Color highlightColor) inline
Initializes a new instance of the BlobCountingObjectsProcessing class.
Parameters
minWidth Minimum width of acceptable object (see MinObjectsWidth property).
minHeight Minimum height of acceptable object (see MinObjectsHeight property).
highlightColor Color used to highlight motion regions.
References AForge.Vision.Motion.BlobCountingObjectsProcessing.blobCounter, AForge.Imaging.BlobCounterBase.FilterBlobs, AForge.Vision.Motion.BlobCountingObjectsProcessing.highlightColor, AForge.Imaging.BlobCounterBase.MinHeight, and AForge.Imaging.BlobCounterBase.MinWidth.
BlobCountingObjectsProcessing() [5/5]
AForge.Vision.Motion.BlobCountingObjectsProcessing.BlobCountingObjectsProcessing (int minWidth, int minHeight, bool highlightMotionRegions) inline
Initializes a new instance of the BlobCountingObjectsProcessing class.
Parameters
minWidth Minimum width of acceptable object (see MinObjectsWidth property).
minHeight Minimum height of acceptable object (see MinObjectsHeight property).
highlightMotionRegions Highlight motion regions or not (see HighlightMotionRegions property).
References AForge.Vision.Motion.BlobCountingObjectsProcessing.highlightMotionRegions.
Member Function Documentation
ProcessFrame()
unsafe void AForge.Vision.Motion.BlobCountingObjectsProcessing.ProcessFrame (UnmanagedImage videoFrame, UnmanagedImage motionFrame) inline
Process video and motion frames doing further post processing after performed motion detection.
Parameters
videoFrame Original video frame.
motionFrame Motion frame provided by motion detection algorithm (see IMotionDetector).
Processes provided motion frame and counts number of separate objects, which size satisfies MinObjectsWidth and MinObjectsHeight properties. In the case if HighlightMotionRegions property is set to true, the found object are also highlighted on the original video frame.
Exceptions
InvalidImagePropertiesException Motion frame is not 8 bpp image, but it must be so.
UnsupportedImageFormatException Video frame must be 8 bpp grayscale image or 24/32 bpp color image.
Implements AForge.Vision.Motion.IMotionProcessing.
References AForge.Vision.Motion.BlobCountingObjectsProcessing.blobCounter, AForge.Imaging.BlobCounterBase.GetObjectsRectangles(), AForge.Imaging.UnmanagedImage.Height, AForge.Vision.Motion.BlobCountingObjectsProcessing.highlightColor, AForge.Vision.Motion.BlobCountingObjectsProcessing.highlightMotionRegions, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.BlobCounterBase.ProcessImage(), AForge.Math.Geometry.Rectangle, AForge.Imaging.Drawing.Rectangle(), and AForge.Imaging.UnmanagedImage.Width.
Reset()
void AForge.Vision.Motion.BlobCountingObjectsProcessing.Reset () inline
Reset internal state of motion processing algorithm.
The method allows to reset internal state of motion processing algorithm and prepare it for processing of next video stream or to restart the algorithm.
Implements AForge.Vision.Motion.IMotionProcessing.
Member Data Documentation
blobCounter
BlobCounter AForge.Vision.Motion.BlobCountingObjectsProcessing.blobCounter = new BlobCounter() private
Referenced by AForge.Vision.Motion.BlobCountingObjectsProcessing.BlobCountingObjectsProcessing(), and AForge.Vision.Motion.BlobCountingObjectsProcessing.ProcessFrame().
highlightColor
Color AForge.Vision.Motion.BlobCountingObjectsProcessing.highlightColor = Color.Red private
Referenced by AForge.Vision.Motion.BlobCountingObjectsProcessing.BlobCountingObjectsProcessing(), and AForge.Vision.Motion.BlobCountingObjectsProcessing.ProcessFrame().
highlightMotionRegions
bool AForge.Vision.Motion.BlobCountingObjectsProcessing.highlightMotionRegions = true private
Referenced by AForge.Vision.Motion.BlobCountingObjectsProcessing.BlobCountingObjectsProcessing(), and AForge.Vision.Motion.BlobCountingObjectsProcessing.ProcessFrame().
Property Documentation
HighlightMotionRegions
bool AForge.Vision.Motion.BlobCountingObjectsProcessing.HighlightMotionRegions get set
Highlight motion regions or not.
The property specifies if detected moving objects should be highlighted with rectangle or not.
Default value is set to true.
<note>Turning the value on leads to additional processing time of video frame.</note>
HighlightColor
Color AForge.Vision.Motion.BlobCountingObjectsProcessing.HighlightColor get set
Color used to highlight motion regions.
Default value is set to red color.
MinObjectsWidth
int AForge.Vision.Motion.BlobCountingObjectsProcessing.MinObjectsWidth get set
Minimum width of acceptable object.
The property sets minimum width of an object to count and highlight. If objects have smaller width, they are not counted and are not highlighted.
Default value is set to 10.
MinObjectsHeight
int AForge.Vision.Motion.BlobCountingObjectsProcessing.MinObjectsHeight get set
Minimum height of acceptable object.
The property sets minimum height of an object to count and highlight. If objects have smaller height, they are not counted and are not highlighted.
Default value is set to 10.
ObjectsCount
int AForge.Vision.Motion.BlobCountingObjectsProcessing.ObjectsCount get
Number of detected objects.
The property provides number of moving objects detected by the last call of ProcessFrame method.
Referenced by MotionDetectorSample.MainForm.videoSourcePlayer_NewFrame().
ObjectRectangles
Rectangle [] AForge.Vision.Motion.BlobCountingObjectsProcessing.ObjectRectangles get
Rectangles of moving objects.
The property provides array of moving objects' rectangles detected by the last call of ProcessFrame method.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Vision/Motion/BlobCountingObjectsProcessing.cs