Doc: IGLib EXTENDED: AForge.Imaging.Filters.BaseInPlacePartialFilter Class Reference
AForge.Imaging.Filters.BaseInPlacePartialFilter Class Reference abstract
Base class for filters, which may be applied directly to the source image or its part.
Public Member Functions
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
abstract unsafe void ProcessFilter (UnmanagedImage image, Rectangle rect)
Process the filter on the specified image.
Properties
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Member Functions
void CheckSourceFormat (PixelFormat pixelFormat)
Detailed Description
Base class for filters, which may be applied directly to the source image or its part.
The abstract class is the base class for all filters, which can be applied to an image producing new image as a result of image processing or applied directly to the source image (or its part) without changing its size and pixel format.
Member Function Documentation
Apply() [1/4]
Bitmap AForge.Imaging.Filters.BaseInPlacePartialFilter.Apply (Bitmap image) inline
Apply filter to an image.
Parameters
image Source image to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The method keeps the source image unchanged and returns the result of image processing filter as new image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.Filters.BaseInPlacePartialFilter.Apply(), IPPrototyperSample.CoinsFinder.Process(), and AForge.Imaging.Filters.FillHoles.ProcessFilter().
Apply() [2/4]
Bitmap AForge.Imaging.Filters.BaseInPlacePartialFilter.Apply (BitmapData imageData) inline
Apply filter to an image.
Parameters
imageData Source image to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The filter accepts bitmap data as input and returns the result of image processing filter as new image. The source image data are kept unchanged.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.BaseInPlacePartialFilter.CheckSourceFormat(), AForge.SystemTools.CopyUnmanagedMemory(), AForge.Imaging.Image.CreateGrayscaleImage(), AForge.Imaging.Filters.BaseInPlacePartialFilter.ProcessFilter(), and AForge.Math.Geometry.Rectangle.
Apply() [3/4]
UnmanagedImage AForge.Imaging.Filters.BaseInPlacePartialFilter.Apply (UnmanagedImage image) inline
Apply filter to an image in unmanaged memory.
Parameters
image Source image in unmanaged memory to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The method keeps the source image unchanged and returns the result of image processing filter as new image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.BaseInPlacePartialFilter.Apply(), AForge.Imaging.Filters.BaseInPlacePartialFilter.CheckSourceFormat(), AForge.Imaging.UnmanagedImage.Create(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.PixelFormat, and AForge.Imaging.UnmanagedImage.Width.
Apply() [4/4]
void AForge.Imaging.Filters.BaseInPlacePartialFilter.Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage) inline
Apply filter to an image in unmanaged memory.
Parameters
sourceImage Source image in unmanaged memory to apply filter to.
destinationImage Destination image in unmanaged memory to put result into.
The method keeps the source image unchanged and puts result of image processing into destination image.
<note>The destination image must have the same width and height as source image. Also destination image must have pixel format, which is expected by particular filter (see FormatTranslations property for information about pixel format conversions).</note>
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
InvalidImagePropertiesException Incorrect destination pixel format.
InvalidImagePropertiesException Destination image has wrong width and/or height.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.BaseInPlacePartialFilter.CheckSourceFormat(), AForge.SystemTools.CopyUnmanagedMemory(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.Filters.BaseInPlacePartialFilter.ProcessFilter(), AForge.Math.Geometry.Rectangle, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
ApplyInPlace() [1/6]
void AForge.Imaging.Filters.BaseInPlacePartialFilter.ApplyInPlace (Bitmap image) inline
Apply filter to an image.
Parameters
image Image to apply filter to.
The method applies the filter directly to the provided source image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlaceFilter.
References AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.Filters.BaseInPlacePartialFilter.ApplyInPlace(), AForge.Imaging.Filters.ContrastStretch.ProcessFilter(), AForge.Imaging.Filters.SaturationCorrection.ProcessFilter(), AForge.Imaging.Filters.BrightnessCorrection.ProcessFilter(), AForge.Imaging.Filters.ContrastCorrection.ProcessFilter(), AForge.Imaging.Filters.SISThreshold.ProcessFilter(), AForge.Imaging.Filters.OtsuThreshold.ProcessFilter(), and ShapeChecker.MainForm.ProcessImage().
ApplyInPlace() [2/6]
void AForge.Imaging.Filters.BaseInPlacePartialFilter.ApplyInPlace (BitmapData imageData) inline
Apply filter to an image.
Parameters
imageData Image data to apply filter to.
The method applies the filter directly to the provided source image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlaceFilter.
References AForge.Imaging.Filters.BaseInPlacePartialFilter.CheckSourceFormat(), AForge.Imaging.Filters.BaseInPlacePartialFilter.ProcessFilter(), and AForge.Math.Geometry.Rectangle.
ApplyInPlace() [3/6]
void AForge.Imaging.Filters.BaseInPlacePartialFilter.ApplyInPlace (UnmanagedImage image) inline
Apply filter to an unmanaged image.
Parameters
image Unmanaged image to apply filter to.
The method applies the filter directly to the provided source unmanaged image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlaceFilter.
References AForge.Imaging.Filters.BaseInPlacePartialFilter.CheckSourceFormat(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.Filters.BaseInPlacePartialFilter.ProcessFilter(), AForge.Math.Geometry.Rectangle, and AForge.Imaging.UnmanagedImage.Width.
ApplyInPlace() [4/6]
void AForge.Imaging.Filters.BaseInPlacePartialFilter.ApplyInPlace (Bitmap image, Rectangle rect) inline
Apply filter to an image or its part.
Parameters
image Image to apply filter to.
rect Image rectangle for processing by the filter.
The method applies the filter directly to the provided source image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlacePartialFilter.
References AForge.Imaging.Filters.BaseInPlacePartialFilter.ApplyInPlace(), and AForge.Math.Geometry.Rectangle.
ApplyInPlace() [5/6]
void AForge.Imaging.Filters.BaseInPlacePartialFilter.ApplyInPlace (BitmapData imageData, Rectangle rect) inline
Apply filter to an image or its part.
Parameters
imageData Image data to apply filter to.
rect Image rectangle for processing by the filter.
The method applies the filter directly to the provided source image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlacePartialFilter.
References AForge.Imaging.Filters.BaseInPlacePartialFilter.ApplyInPlace().
ApplyInPlace() [6/6]
void AForge.Imaging.Filters.BaseInPlacePartialFilter.ApplyInPlace (UnmanagedImage image, Rectangle rect) inline
Apply filter to an unmanaged image or its part.
Parameters
image Unmanaged image to apply filter to.
rect Image rectangle for processing by the filter.
The method applies the filter directly to the provided source image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlacePartialFilter.
References AForge.Imaging.Filters.BaseInPlacePartialFilter.CheckSourceFormat(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.Filters.BaseInPlacePartialFilter.ProcessFilter(), AForge.Math.Geometry.Rectangle, and AForge.Imaging.UnmanagedImage.Width.
ProcessFilter()
abstract unsafe void AForge.Imaging.Filters.BaseInPlacePartialFilter.ProcessFilter (UnmanagedImage image, Rectangle rect) protected pure virtual
Process the filter on the specified image.
Parameters
image Source image data.
rect Image rectangle for processing by the filter.
Implemented in AForge.Imaging.Filters.IterativeThreshold, AForge.Imaging.Filters.OtsuThreshold, AForge.Imaging.Filters.MaskedFilter, AForge.Imaging.Filters.ChannelFiltering, AForge.Imaging.Filters.LevelsLinear, AForge.Imaging.Filters.LevelsLinear16bpp, AForge.Imaging.Filters.HSLFiltering, AForge.Imaging.Filters.SISThreshold, AForge.Imaging.Filters.ColorRemapping, AForge.Imaging.Filters.Texturer, AForge.Imaging.Filters.YCbCrFiltering, AForge.Imaging.Filters.ReplaceChannel, AForge.Imaging.Filters.YCbCrReplaceChannel, AForge.Imaging.Filters.ApplyMask, AForge.Imaging.Filters.PointedColorFloodFill, AForge.Imaging.Filters.ColorFiltering, AForge.Imaging.Filters.YCbCrLinear, AForge.Imaging.Filters.PointedMeanFloodFill, AForge.Imaging.Filters.SimplePosterization, AForge.Imaging.Filters.EuclideanColorFiltering, AForge.Imaging.Filters.Pixellate, AForge.Imaging.Filters.HSLLinear, AForge.Imaging.Filters.ContrastCorrection, AForge.Imaging.Filters.ErrorDiffusionDithering, AForge.Imaging.Filters.BrightnessCorrection, AForge.Imaging.Filters.SaturationCorrection, AForge.Imaging.Filters.VerticalRunLengthSmoothing, AForge.Imaging.Filters.HorizontalRunLengthSmoothing, AForge.Imaging.Filters.OrderedDithering, AForge.Imaging.Filters.GammaCorrection, AForge.Imaging.Filters.Threshold, AForge.Imaging.Filters.ThresholdWithCarry, AForge.Imaging.Filters.AdditiveNoise, AForge.Imaging.Filters.Sepia, AForge.Imaging.Filters.SaltAndPepperNoise, AForge.Imaging.Filters.Mirror, AForge.Imaging.Filters.HueModifier, AForge.Imaging.Filters.ContrastStretch, AForge.Imaging.Filters.HistogramEqualization, AForge.Imaging.Filters.Invert, and AForge.Imaging.Filters.RotateChannels.
Referenced by AForge.Imaging.Filters.BaseInPlacePartialFilter.Apply(), and AForge.Imaging.Filters.BaseInPlacePartialFilter.ApplyInPlace().
CheckSourceFormat()
void AForge.Imaging.Filters.BaseInPlacePartialFilter.CheckSourceFormat (PixelFormat pixelFormat) inline private
References AForge.Imaging.Filters.BaseInPlacePartialFilter.FormatTranslations.
Referenced by AForge.Imaging.Filters.BaseInPlacePartialFilter.Apply(), and AForge.Imaging.Filters.BaseInPlacePartialFilter.ApplyInPlace().
Property Documentation
FormatTranslations
abstract Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.BaseInPlacePartialFilter.FormatTranslations get
Format translations dictionary.
The dictionary defines, which pixel formats are supported for source images and which pixel format will be used for resulting image.
See IFilterInformation.FormatTranslations for more information.
Referenced by AForge.Imaging.Filters.BaseInPlacePartialFilter.CheckSourceFormat().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Base classes/BaseInPlacePartialFilter.cs