Doc: IGLib EXTENDED: NUnit.Framework.Assertions.NullableTypesTests Class Reference
NUnit.Framework.Assertions.NullableTypesTests Class Reference
Classes
struct MyStruct
Public Member Functions
void CanTestForNull ()
void CanCompareNullableInts ()
void CanCompareNullableDoubles ()
void CanTestForNaN ()
void CanCompareNullableDecimals ()
void CanCompareWithTolerance ()
void CanCompareNullableEnums ()
void CanCompareNullableMixedNumerics ()
void CanCompareNullableStructs ()
Private Types
enum Colors { Colors.Red, Colors.Blue, Colors.Green }
Member Enumeration Documentation
Colors
enum NUnit.Framework.Assertions.NullableTypesTests.Colors strong private
Enumerator
Red
Blue
Green
Member Function Documentation
CanTestForNull()
void NUnit.Framework.Assertions.NullableTypesTests.CanTestForNull () inline
References NUnit.Framework.Assert.IsNotNull(), NUnit.Framework.Assert.IsNull(), NUnit.Framework.Is.Not, NUnit.Framework.Is.Null, and NUnit.Framework.Assert.That().
CanCompareNullableInts()
void NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableInts () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.GreaterThan(), NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
CanCompareNullableDoubles()
void NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableDoubles () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.GreaterThan(), NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
CanTestForNaN()
void NUnit.Framework.Assertions.NullableTypesTests.CanTestForNaN () inline
References NUnit.Framework.Assert.IsNaN(), NUnit.Framework.Is.NaN, and NUnit.Framework.Assert.That().
CanCompareNullableDecimals()
void NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableDecimals () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.GreaterThan(), NUnit.Framework.Is.GreaterThanOrEqualTo(), and NUnit.Framework.Assert.That().
CanCompareWithTolerance()
void NUnit.Framework.Assertions.NullableTypesTests.CanCompareWithTolerance () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
CanCompareNullableEnums()
void NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableEnums () inline
References NUnit.Framework.Assert.AreEqual().
CanCompareNullableMixedNumerics()
void NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableMixedNumerics () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.GreaterThan(), and NUnit.Framework.Assert.That().
CanCompareNullableStructs()
void NUnit.Framework.Assertions.NullableTypesTests.CanCompareNullableStructs () inline
References NUnit.Framework.Assert.AreEqual().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/NullableTypesTests.cs