Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGEBRD Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGEBRD Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGEBRD (DGEBD2 dgebd2, DGEMM dgemm, DLABRD dlabrd, XERBLA xerbla, ILAENV ilaenv)
DGEBRD ()
void Run (int M, int N, ref double[] A, int offset_a, int LDA, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] TAUQ, int offset_tauq, ref double[] TAUP, int offset_taup, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
DGEBD2 _dgebd2
DGEMM _dgemm
DLABRD _dlabrd
XERBLA _xerbla
ILAENV _ilaenv
Static Private Attributes
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGEBRD reduces a general real M-by-N matrix A to upper or lower bidiagonal form B by an orthogonal transformation: Q**T * A * P = B.
If m .GE. n, B is upper bidiagonal; if m .LT. n, B is lower bidiagonal.
/summary>
Constructor & Destructor Documentation
DGEBRD() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGEBRD.DGEBRD (DGEBD2 dgebd2, DGEMM dgemm, DLABRD dlabrd, XERBLA xerbla, ILAENV ilaenv) inline
DGEBRD() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGEBRD.DGEBRD () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGEBRD.Run (int M, int N, ref double[] A, int offset_a, int LDA, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] TAUQ, int offset_tauq, ref double[] TAUP, int offset_taup, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DGEBRD reduces a general real M-by-N matrix A to upper or lower bidiagonal form B by an orthogonal transformation: Q**T * A * P = B.
If m .GE. n, B is upper bidiagonal; if m .LT. n, B is lower bidiagonal.
/summary>
Parameters
M (input) INTEGER The number of rows in the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns in the matrix A. N .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the M-by-N general matrix to be reduced. On exit, if m .GE. n, the diagonal and the first superdiagonal are overwritten with the upper bidiagonal matrix B; the elements below the diagonal, with the array TAUQ, represent the orthogonal matrix Q as a product of elementary reflectors, and the elements above the first superdiagonal, with the array TAUP, represent the orthogonal matrix P as a product of elementary reflectors; if m .LT. n, the diagonal and the first subdiagonal are overwritten with the lower bidiagonal matrix B; the elements below the first subdiagonal, with the array TAUQ, represent the orthogonal matrix Q as a product of elementary reflectors, and the elements above the diagonal, with the array TAUP, represent the orthogonal matrix P as a product of elementary reflectors. See Further Details. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
D (output) DOUBLE PRECISION array, dimension (min(M,N)) The diagonal elements of the bidiagonal matrix B: D(i) = A(i,i). /param>
Parameters
E (output) DOUBLE PRECISION array, dimension (min(M,N)-1) The off-diagonal elements of the bidiagonal matrix B: if m .GE. n, E(i) = A(i,i+1) for i = 1,2,...,n-1; if m .LT. n, E(i) = A(i+1,i) for i = 1,2,...,m-1. /param>
Parameters
TAUQ (output) DOUBLE PRECISION array dimension (min(M,N)) The scalar factors of the elementary reflectors which represent the orthogonal matrix Q. See Further Details. /param>
Parameters
TAUP (output) DOUBLE PRECISION array, dimension (min(M,N)) The scalar factors of the elementary reflectors which represent the orthogonal matrix P. See Further Details. /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The length of the array WORK. LWORK .GE. max(1,M,N). For optimum performance LWORK .GE. (M+N)*NB, where NB is the optimal blocksize.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value. /param>
References DotNumerics.LinearAlgebra.CSLapack.DGEBRD.ONE, DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBD2.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLABRD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELSD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run().
Member Data Documentation
_dgebd2
DGEBD2 DotNumerics.LinearAlgebra.CSLapack.DGEBRD._dgebd2 private
_dgemm
DGEMM DotNumerics.LinearAlgebra.CSLapack.DGEBRD._dgemm private
_dlabrd
DLABRD DotNumerics.LinearAlgebra.CSLapack.DGEBRD._dlabrd private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGEBRD._xerbla private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DGEBRD._ilaenv private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGEBRD.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEBRD.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgebrd.cs