Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGEBAK Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGEBAK Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGEBAK (LSAME lsame, DSCAL dscal, DSWAP dswap, XERBLA xerbla)
DGEBAK ()
void Run (string JOB, string SIDE, int N, int ILO, int IHI, double[] SCALE, int offset_scale, int M, ref double[] V, int offset_v, int LDV, ref int INFO)
Private Attributes
LSAME _lsame
DSCAL _dscal
DSWAP _dswap
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGEBAK forms the right or left eigenvectors of a real general matrix by backward transformation on the computed eigenvectors of the balanced matrix output by DGEBAL.
/summary>
Constructor & Destructor Documentation
DGEBAK() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGEBAK.DGEBAK (LSAME lsame, DSCAL dscal, DSWAP dswap, XERBLA xerbla) inline
DGEBAK() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGEBAK.DGEBAK () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGEBAK.Run (string JOB, string SIDE, int N, int ILO, int IHI, double[] SCALE, int offset_scale, int M, ref double[] V, int offset_v, int LDV, ref int INFO) inline
Purpose
DGEBAK forms the right or left eigenvectors of a real general matrix by backward transformation on the computed eigenvectors of the balanced matrix output by DGEBAL.
/summary>
Parameters
JOB (input) CHARACTER*1 Specifies the type of backward transformation required: = 'N', do nothing, return immediately; = 'P', do backward transformation for permutation only; = 'S', do backward transformation for scaling only; = 'B', do backward transformations for both permutation and scaling. JOB must be the same as the argument JOB supplied to DGEBAL. /param>
Parameters
SIDE (input) CHARACTER*1 = 'R': V contains right eigenvectors; = 'L': V contains left eigenvectors. /param>
Parameters
N (input) INTEGER The number of rows of the matrix V. N .GE. 0. /param>
Parameters
ILO (input) INTEGER /param>
Parameters
IHI (input) INTEGER The integers ILO and IHI determined by DGEBAL. 1 .LE. ILO .LE. IHI .LE. N, if N .GT. 0; ILO=1 and IHI=0, if N=0. /param>
Parameters
SCALE (input) DOUBLE PRECISION array, dimension (N) Details of the permutation and scaling factors, as returned by DGEBAL. /param>
Parameters
M (input) INTEGER The number of columns of the matrix V. M .GE. 0. /param>
Parameters
V (input/output) DOUBLE PRECISION array, dimension (LDV,M) On entry, the matrix of right or left eigenvectors to be transformed, as returned by DHSEIN or DTREVC. On exit, V is overwritten by the transformed eigenvectors. /param>
Parameters
LDV (input) INTEGER The leading dimension of the array V. LDV .GE. max(1,N). /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value. /param>
References DotNumerics.LinearAlgebra.CSLapack.DGEBAK.ONE, DotNumerics.LinearAlgebra.CSLapack.DSWAP.Run(), DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), and DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DGEBAK._lsame private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DGEBAK._dscal private
_dswap
DSWAP DotNumerics.LinearAlgebra.CSLapack.DGEBAK._dswap private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGEBAK._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGEBAK.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEBAK.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgebak.cs