Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGEBD2 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGEBD2 Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGEBD2 (DLARF dlarf, DLARFG dlarfg, XERBLA xerbla)
DGEBD2 ()
void Run (int M, int N, ref double[] A, int offset_a, int LDA, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] TAUQ, int offset_tauq, ref double[] TAUP, int offset_taup, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
DLARF _dlarf
DLARFG _dlarfg
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGEBD2 reduces a real general m by n matrix A to upper or lower bidiagonal form B by an orthogonal transformation: Q' * A * P = B.
If m .GE. n, B is upper bidiagonal; if m .LT. n, B is lower bidiagonal.
/summary>
Constructor & Destructor Documentation
DGEBD2() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGEBD2.DGEBD2 (DLARF dlarf, DLARFG dlarfg, XERBLA xerbla) inline
DGEBD2() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGEBD2.DGEBD2 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGEBD2.Run (int M, int N, ref double[] A, int offset_a, int LDA, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] TAUQ, int offset_tauq, ref double[] TAUP, int offset_taup, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
DGEBD2 reduces a real general m by n matrix A to upper or lower bidiagonal form B by an orthogonal transformation: Q' * A * P = B.
If m .GE. n, B is upper bidiagonal; if m .LT. n, B is lower bidiagonal.
/summary>
Parameters
M (input) INTEGER The number of rows in the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns in the matrix A. N .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the m by n general matrix to be reduced. On exit, if m .GE. n, the diagonal and the first superdiagonal are overwritten with the upper bidiagonal matrix B; the elements below the diagonal, with the array TAUQ, represent the orthogonal matrix Q as a product of elementary reflectors, and the elements above the first superdiagonal, with the array TAUP, represent the orthogonal matrix P as a product of elementary reflectors; if m .LT. n, the diagonal and the first subdiagonal are overwritten with the lower bidiagonal matrix B; the elements below the first subdiagonal, with the array TAUQ, represent the orthogonal matrix Q as a product of elementary reflectors, and the elements above the diagonal, with the array TAUP, represent the orthogonal matrix P as a product of elementary reflectors. See Further Details. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
D (output) DOUBLE PRECISION array, dimension (min(M,N)) The diagonal elements of the bidiagonal matrix B: D(i) = A(i,i). /param>
Parameters
E (output) DOUBLE PRECISION array, dimension (min(M,N)-1) The off-diagonal elements of the bidiagonal matrix B: if m .GE. n, E(i) = A(i,i+1) for i = 1,2,...,n-1; if m .LT. n, E(i) = A(i+1,i) for i = 1,2,...,m-1. /param>
Parameters
TAUQ (output) DOUBLE PRECISION array dimension (min(M,N)) The scalar factors of the elementary reflectors which represent the orthogonal matrix Q. See Further Details. /param>
Parameters
TAUP (output) DOUBLE PRECISION array, dimension (min(M,N)) The scalar factors of the elementary reflectors which represent the orthogonal matrix P. See Further Details. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (max(M,N)) /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. /param>
References DotNumerics.LinearAlgebra.CSLapack.DGEBD2.ONE, DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGEBD2.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEBRD.Run().
Member Data Documentation
_dlarf
DLARF DotNumerics.LinearAlgebra.CSLapack.DGEBD2._dlarf private
_dlarfg
DLARFG DotNumerics.LinearAlgebra.CSLapack.DGEBD2._dlarfg private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGEBD2._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DGEBD2.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEBD2.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGEBD2.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEBD2.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgebd2.cs