Doc: IGLib EXTENDED: NUnit.Engine.Agents.RemoteTestAgent Class Reference
NUnit.Engine.Agents.RemoteTestAgent Class Reference
RemoteTestAgent represents a remote agent executing in another process and communicating with NUnit by TCP. Although it is similar to a TestServer, it does not publish a Uri at which clients may connect to it. Rather, it reports back to the sponsoring TestAgency upon startup so that the agency may in turn provide it to clients for use.
Public Member Functions
RemoteTestAgent (Guid agentId, ITestAgency agency, IServiceLocator services)
Construct a RemoteTestAgent
override ITestEngineRunner CreateRunner (TestPackage package)
Creates a test runner
override bool Start ()
Starts the agent, performing any required initialization
override void Stop ()
Stops the agent, releasing any resources
void WaitForStop ()
TestEngineResult Explore (TestFilter filter)
Explore a loaded TestPackage and return information about the tests found.
TestEngineResult Load ()
Load a TestPackage for possible execution
void Unload ()
Unload any loaded TestPackage. If none is loaded, the call is ignored.
TestEngineResult Reload ()
Reload the loaded test package.
int CountTestCases (TestFilter filter)
Count the test cases that would be run under the specified filter.
TestEngineResult Run (ITestEventListener listener, TestFilter filter)
Run the tests in the loaded TestPackage and return a test result. The tests are run synchronously and the listener interface is notified as it progresses.
AsyncTestEngineResult RunAsync (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the loaded TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses.
void StartRun (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the loaded TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses.
void StopRun (bool force)
Cancel the ongoing test run. If no test is running, the call is ignored.
Public Member Functions inherited from NUnit.Engine.Agents.TestAgent
TestAgent (Guid agentId, ITestAgency agency, IServiceLocator services)
Initializes a new instance of the TestAgent class.
void Dispose ()
override object InitializeLifetimeService ()
Overridden to cause object to live indefinitely
Properties
int ProcessId [get]
Properties inherited from NUnit.Engine.Agents.TestAgent
IServiceLocator Services [get]
The services available to the agent
ITestAgency Agency [get]
Gets a reference to the TestAgency with which this agent is associated. Returns null if the agent is not connected to an agency.
Guid Id [get]
Gets a Guid that uniquely identifies this agent.
Properties inherited from NUnit.Engine.ITestAgent
ITestAgency Agency [get]
Gets the agency with which this agent is associated.
Guid Id [get]
Gets a Guid that uniquely identifies this agent.
Private Attributes
ITestEngineRunner _runner
TestPackage _package
ManualResetEvent stopSignal = new ManualResetEvent(false)
Static Private Attributes
static Logger log = InternalTrace.GetLogger(typeof(RemoteTestAgent))
Additional Inherited Members
Protected Member Functions inherited from NUnit.Engine.Agents.TestAgent
virtual void Dispose (bool disposing)
Dispose is overridden to stop the agent
Detailed Description
RemoteTestAgent represents a remote agent executing in another process and communicating with NUnit by TCP. Although it is similar to a TestServer, it does not publish a Uri at which clients may connect to it. Rather, it reports back to the sponsoring TestAgency upon startup so that the agency may in turn provide it to clients for use.
Constructor & Destructor Documentation
RemoteTestAgent()
NUnit.Engine.Agents.RemoteTestAgent.RemoteTestAgent (Guid agentId, ITestAgency agency, IServiceLocator services) inline
Construct a RemoteTestAgent
Member Function Documentation
CreateRunner()
override ITestEngineRunner NUnit.Engine.Agents.RemoteTestAgent.CreateRunner (TestPackage package) inline virtual
Creates a test runner
Implements NUnit.Engine.Agents.TestAgent.
References NUnit.Engine.Agents.RemoteTestAgent._package.
Start()
override bool NUnit.Engine.Agents.RemoteTestAgent.Start () inline virtual
Starts the agent, performing any required initialization
Returns
true if the agent was started successfully.
Implements NUnit.Engine.Agents.TestAgent.
References NUnit.Engine.Agents.TestAgent.Agency, NUnit.Engine.Agents.RemoteTestAgent.log, and NUnit.Engine.ITestAgency.Register().
Referenced by NUnit.Agent.NUnitTestAgent.Main().
Stop()
override void NUnit.Engine.Agents.RemoteTestAgent.Stop () inline virtual
Stops the agent, releasing any resources
Implements NUnit.Engine.Agents.TestAgent.
References NUnit.Engine.Agents.RemoteTestAgent.log, and NUnit.Engine.Agents.RemoteTestAgent.stopSignal.
WaitForStop()
void NUnit.Engine.Agents.RemoteTestAgent.WaitForStop () inline
References NUnit.Engine.Agents.RemoteTestAgent.stopSignal.
Referenced by NUnit.Agent.NUnitTestAgent.Main().
Explore()
TestEngineResult NUnit.Engine.Agents.RemoteTestAgent.Explore (TestFilter filter) inline
Explore a loaded TestPackage and return information about the tests found.
Parameters
filter Criteria used to filter the search results
Returns
A TestEngineResult.
Implements NUnit.Engine.ITestEngineRunner.
References NUnit.Engine.Agents.RemoteTestAgent._runner, and NUnit.Engine.ITestEngineRunner.Explore().
Load()
TestEngineResult NUnit.Engine.Agents.RemoteTestAgent.Load () inline
Load a TestPackage for possible execution
Returns
A TestEngineResult.
Implements NUnit.Engine.ITestEngineRunner.
References NUnit.Engine.Agents.RemoteTestAgent._package, NUnit.Engine.Agents.RemoteTestAgent._runner, NUnit.Engine.IServiceLocator.GetService(), NUnit.Engine.ITestEngineRunner.Load(), and NUnit.Engine.Agents.TestAgent.Services.
Unload()
void NUnit.Engine.Agents.RemoteTestAgent.Unload () inline
Unload any loaded TestPackage. If none is loaded, the call is ignored.
Implements NUnit.Engine.ITestEngineRunner.
References NUnit.Engine.Agents.RemoteTestAgent._runner, and NUnit.Engine.ITestEngineRunner.Unload().
Reload()
TestEngineResult NUnit.Engine.Agents.RemoteTestAgent.Reload () inline
Reload the loaded test package.
Returns
A TestEngineResult.
Exceptions
InvalidOperationException If no package is loaded.
Implements NUnit.Engine.ITestEngineRunner.
References NUnit.Engine.Agents.RemoteTestAgent._runner, and NUnit.Engine.ITestEngineRunner.Reload().
CountTestCases()
int NUnit.Engine.Agents.RemoteTestAgent.CountTestCases (TestFilter filter) inline
Count the test cases that would be run under the specified filter.
Parameters
filter A TestFilter
Returns
The count of test cases
Implements NUnit.Engine.ITestEngineRunner.
References NUnit.Engine.Agents.RemoteTestAgent._runner, and NUnit.Engine.ITestEngineRunner.CountTestCases().
Run()
TestEngineResult NUnit.Engine.Agents.RemoteTestAgent.Run (ITestEventListener listener, TestFilter filter) inline
Run the tests in the loaded TestPackage and return a test result. The tests are run synchronously and the listener interface is notified as it progresses.
Parameters
listener An ITestEventHandler to receive events
filter A TestFilter used to select tests
Returns
A TestEngineResult giving the result of the test execution
Implements NUnit.Engine.ITestEngineRunner.
References NUnit.Engine.Agents.RemoteTestAgent._runner, and NUnit.Engine.ITestEngineRunner.Run().
RunAsync()
AsyncTestEngineResult NUnit.Engine.Agents.RemoteTestAgent.RunAsync (ITestEventListener listener, TestFilter filter) inline
Start a run of the tests in the loaded TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses.
Parameters
listener An ITestEventHandler to receive events
filter A TestFilter used to select tests
Returns
A AsyncTestEngineResult that will provide the result of the test execution
Implements NUnit.Engine.ITestEngineRunner.
References NUnit.Engine.Agents.RemoteTestAgent._runner, and NUnit.Engine.ITestEngineRunner.RunAsync().
Referenced by NUnit.Engine.Agents.RemoteTestAgent.StartRun().
StartRun()
void NUnit.Engine.Agents.RemoteTestAgent.StartRun (ITestEventListener listener, TestFilter filter) inline
Start a run of the tests in the loaded TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses.
Parameters
listener An ITestEventHandler to receive events
filter A TestFilter used to select tests
Implements NUnit.Engine.ITestEngineRunner.
References NUnit.Engine.Agents.RemoteTestAgent.RunAsync().
StopRun()
void NUnit.Engine.Agents.RemoteTestAgent.StopRun (bool force) inline
Cancel the ongoing test run. If no test is running, the call is ignored.
Parameters
force If true, cancel any ongoing test threads, otherwise wait for them to complete.
Implements NUnit.Engine.ITestEngineRunner.
References NUnit.Engine.Agents.RemoteTestAgent._runner, and NUnit.Engine.ITestEngineRunner.StopRun().
Member Data Documentation
log
Logger NUnit.Engine.Agents.RemoteTestAgent.log = InternalTrace.GetLogger(typeof(RemoteTestAgent)) static private
Referenced by NUnit.Engine.Agents.RemoteTestAgent.Start(), and NUnit.Engine.Agents.RemoteTestAgent.Stop().
_runner
ITestEngineRunner NUnit.Engine.Agents.RemoteTestAgent._runner private
Referenced by NUnit.Engine.Agents.RemoteTestAgent.CountTestCases(), NUnit.Engine.Agents.RemoteTestAgent.Explore(), NUnit.Engine.Agents.RemoteTestAgent.Load(), NUnit.Engine.Agents.RemoteTestAgent.Reload(), NUnit.Engine.Agents.RemoteTestAgent.Run(), NUnit.Engine.Agents.RemoteTestAgent.RunAsync(), NUnit.Engine.Agents.RemoteTestAgent.StopRun(), and NUnit.Engine.Agents.RemoteTestAgent.Unload().
_package
TestPackage NUnit.Engine.Agents.RemoteTestAgent._package private
Referenced by NUnit.Engine.Agents.RemoteTestAgent.CreateRunner(), and NUnit.Engine.Agents.RemoteTestAgent.Load().
stopSignal
ManualResetEvent NUnit.Engine.Agents.RemoteTestAgent.stopSignal = new ManualResetEvent(false) private
Referenced by NUnit.Engine.Agents.RemoteTestAgent.Stop(), and NUnit.Engine.Agents.RemoteTestAgent.WaitForStop().
Property Documentation
ProcessId
int NUnit.Engine.Agents.RemoteTestAgent.ProcessId get
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Agents/RemoteTestAgent.cs