Doc: IGLib EXTENDED: IG.Num.TestAlglibOld2008 Class Reference
IG.Num.TestAlglibOld2008 Class Reference
Test class for the old version of AlgLib algorithms that were not under GPL.
Public Member Functions
void TestLbfgsAlglibOld ()
Test method for the old version of AlgLib algorithms that were not under GPL.
void TestLbfgsAlglibOld (int dim)
Test method for the old version of AlgLib algorithms that were not under GPL.
Additional Inherited Members
Protected Attributes inherited from IG.Num.TestAlgLibBase2008
int _outputLevel = DefaultOutputLevel
Static Protected Attributes inherited from IG.Num.TestAlgLibBase2008
static int _defaultOutputLevel = 1
Properties inherited from IG.Num.TestAlgLibBase2008
static int DefaultOutputLevel [get, set]
int OutputLevel [get, set]
Detailed Description
Test class for the old version of AlgLib algorithms that were not under GPL.
$A Igor Apr08;
Member Function Documentation
TestLbfgsAlglibOld() [1/2]
void IG.Num.TestAlglibOld2008.TestLbfgsAlglibOld () inline
Test method for the old version of AlgLib algorithms that were not under GPL.
References IG.Num.IScalarFunctionUntransformed.Gradient(), IG.Num.m, AlgLib.lbfgs.minlbfgs(), AlgLib.lbfgs.minlbfgsiteration(), IG.Num.ScalarFunctionUntransformedBase.NumericalGradientForwardPlain(), IG.Num.TestAlgLibBase2008.OutputLevel, IG.Num.M.sqr(), and IG.Num.IScalarFunctionUntransformed.Value().
Referenced by IG.Script.Script_Numeric.TestOptAlglib().
TestLbfgsAlglibOld() [2/2]
void IG.Num.TestAlglibOld2008.TestLbfgsAlglibOld (int dim) inline
Test method for the old version of AlgLib algorithms that were not under GPL.
Parameters
dim Dimension of parameter space.
The generalized Rosenbrock function is minimized.
Function has global minimum at {1, 1, 1, ...}, but can have several local minima for dimensions greater than 3.
For dimensions up to 7, eventual non-global local minima can be at {-1, 1, 1, ...}.
References IG.Num.IScalarFunctionUntransformed.Gradient(), IG.Num.m, AlgLib.lbfgs.minlbfgs(), AlgLib.lbfgs.minlbfgsiteration(), IG.Num.TestAlgLibBase2008.OutputLevel, IG.Num.IVector< T >.SetConstant(), IG.Num.IVector< T >.ToString(), and IG.Num.IScalarFunctionUntransformed.Value().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/opt/alglib/Alglib_Old_UniMb/AlgLib2008/TestOptAlglib2008.cs