Doc: IGLib EXTENDED: TestGui.localhost.Service Class Reference
TestGui.localhost.Service Class Reference
Public Member Functions
Service ()
string PosljiPaket (string paketXml)
void PosljiPaketAsync (string paketXml)
void PosljiPaketAsync (string paketXml, object userState)
string PaketStatus (int paketId)
void PaketStatusAsync (int paketId)
void PaketStatusAsync (int paketId, object userState)
byte[] PaketShema ()
void PaketShemaAsync ()
void PaketShemaAsync (object userState)
byte[] PaketStatusShema ()
void PaketStatusShemaAsync ()
void PaketStatusShemaAsync (object userState)
System.Data.DataSet PaketTipZalogaVrednosti ()
void PaketTipZalogaVrednostiAsync ()
void PaketTipZalogaVrednostiAsync (object userState)
System.Data.DataSet PaketStatusZalogaVrednosti ()
System.Data.DataSet PodrocjaZalogaVrednosti ()
void PaketStatusZalogaVrednostiAsync ()
void PaketStatusZalogaVrednostiAsync (object userState)
new void CancelAsync (object userState)
Properties
new string Url [get, set]
new bool UseDefaultCredentials [get, set]
Events
PosljiPaketCompletedEventHandler PosljiPaketCompleted
PaketStatusCompletedEventHandler PaketStatusCompleted
PaketShemaCompletedEventHandler PaketShemaCompleted
PaketStatusShemaCompletedEventHandler PaketStatusShemaCompleted
PaketTipZalogaVrednostiCompletedEventHandler PaketTipZalogaVrednostiCompleted
PaketStatusZalogaVrednostiCompletedEventHandler PaketStatusZalogaVrednostiCompleted
Private Member Functions
void OnPosljiPaketOperationCompleted (object arg)
void OnPaketStatusOperationCompleted (object arg)
void OnPaketShemaOperationCompleted (object arg)
void OnPaketStatusShemaOperationCompleted (object arg)
void OnPaketTipZalogaVrednostiOperationCompleted (object arg)
void OnPaketStatusZalogaVrednostiOperationCompleted (object arg)
bool IsLocalFileSystemWebService (string url)
Private Attributes
System.Threading.SendOrPostCallback PosljiPaketOperationCompleted
System.Threading.SendOrPostCallback PaketStatusOperationCompleted
System.Threading.SendOrPostCallback PaketShemaOperationCompleted
System.Threading.SendOrPostCallback PaketStatusShemaOperationCompleted
System.Threading.SendOrPostCallback PaketTipZalogaVrednostiOperationCompleted
System.Threading.SendOrPostCallback PaketStatusZalogaVrednostiOperationCompleted
bool useDefaultCredentialsSetExplicitly
Detailed Description
Constructor & Destructor Documentation
Service()
TestGui.localhost.Service.Service () inline
References TestGui.localhost.Service.IsLocalFileSystemWebService(), TestGui.localhost.Service.Url, and TestGui.localhost.Service.UseDefaultCredentials.
Member Function Documentation
PosljiPaket()
string TestGui.localhost.Service.PosljiPaket (string paketXml) inline
PosljiPaketAsync() [1/2]
void TestGui.localhost.Service.PosljiPaketAsync (string paketXml) inline
PosljiPaketAsync() [2/2]
void TestGui.localhost.Service.PosljiPaketAsync (string paketXml, object userState) inline
References TestGui.localhost.Service.OnPosljiPaketOperationCompleted(), and TestGui.localhost.Service.PosljiPaketOperationCompleted.
OnPosljiPaketOperationCompleted()
void TestGui.localhost.Service.OnPosljiPaketOperationCompleted (object arg) inline private
References TestGui.localhost.Service.PosljiPaketCompleted.
Referenced by TestGui.localhost.Service.PosljiPaketAsync().
PaketStatus()
string TestGui.localhost.Service.PaketStatus (int paketId) inline
PaketStatusAsync() [1/2]
void TestGui.localhost.Service.PaketStatusAsync (int paketId) inline
PaketStatusAsync() [2/2]
void TestGui.localhost.Service.PaketStatusAsync (int paketId, object userState) inline
References TestGui.localhost.Service.OnPaketStatusOperationCompleted(), and TestGui.localhost.Service.PaketStatusOperationCompleted.
OnPaketStatusOperationCompleted()
void TestGui.localhost.Service.OnPaketStatusOperationCompleted (object arg) inline private
References TestGui.localhost.Service.PaketStatusCompleted.
Referenced by TestGui.localhost.Service.PaketStatusAsync().
PaketShema()
byte [] TestGui.localhost.Service.PaketShema () inline
PaketShemaAsync() [1/2]
void TestGui.localhost.Service.PaketShemaAsync () inline
PaketShemaAsync() [2/2]
void TestGui.localhost.Service.PaketShemaAsync (object userState) inline
References TestGui.localhost.Service.OnPaketShemaOperationCompleted(), and TestGui.localhost.Service.PaketShemaOperationCompleted.
OnPaketShemaOperationCompleted()
void TestGui.localhost.Service.OnPaketShemaOperationCompleted (object arg) inline private
References TestGui.localhost.Service.PaketShemaCompleted.
Referenced by TestGui.localhost.Service.PaketShemaAsync().
PaketStatusShema()
byte [] TestGui.localhost.Service.PaketStatusShema () inline
PaketStatusShemaAsync() [1/2]
void TestGui.localhost.Service.PaketStatusShemaAsync () inline
PaketStatusShemaAsync() [2/2]
void TestGui.localhost.Service.PaketStatusShemaAsync (object userState) inline
References TestGui.localhost.Service.OnPaketStatusShemaOperationCompleted(), and TestGui.localhost.Service.PaketStatusShemaOperationCompleted.
OnPaketStatusShemaOperationCompleted()
void TestGui.localhost.Service.OnPaketStatusShemaOperationCompleted (object arg) inline private
References TestGui.localhost.Service.PaketStatusShemaCompleted.
Referenced by TestGui.localhost.Service.PaketStatusShemaAsync().
PaketTipZalogaVrednosti()
System.Data.DataSet TestGui.localhost.Service.PaketTipZalogaVrednosti () inline
PaketTipZalogaVrednostiAsync() [1/2]
void TestGui.localhost.Service.PaketTipZalogaVrednostiAsync () inline
PaketTipZalogaVrednostiAsync() [2/2]
void TestGui.localhost.Service.PaketTipZalogaVrednostiAsync (object userState) inline
References TestGui.localhost.Service.OnPaketTipZalogaVrednostiOperationCompleted(), and TestGui.localhost.Service.PaketTipZalogaVrednostiOperationCompleted.
OnPaketTipZalogaVrednostiOperationCompleted()
void TestGui.localhost.Service.OnPaketTipZalogaVrednostiOperationCompleted (object arg) inline private
References TestGui.localhost.Service.PaketTipZalogaVrednostiCompleted.
Referenced by TestGui.localhost.Service.PaketTipZalogaVrednostiAsync().
PaketStatusZalogaVrednosti()
System.Data.DataSet TestGui.localhost.Service.PaketStatusZalogaVrednosti () inline
PodrocjaZalogaVrednosti()
System.Data.DataSet TestGui.localhost.Service.PodrocjaZalogaVrednosti () inline
PaketStatusZalogaVrednostiAsync() [1/2]
void TestGui.localhost.Service.PaketStatusZalogaVrednostiAsync () inline
PaketStatusZalogaVrednostiAsync() [2/2]
void TestGui.localhost.Service.PaketStatusZalogaVrednostiAsync (object userState) inline
References TestGui.localhost.Service.OnPaketStatusZalogaVrednostiOperationCompleted(), and TestGui.localhost.Service.PaketStatusZalogaVrednostiOperationCompleted.
OnPaketStatusZalogaVrednostiOperationCompleted()
void TestGui.localhost.Service.OnPaketStatusZalogaVrednostiOperationCompleted (object arg) inline private
References TestGui.localhost.Service.PaketStatusZalogaVrednostiCompleted.
Referenced by TestGui.localhost.Service.PaketStatusZalogaVrednostiAsync().
CancelAsync()
new void TestGui.localhost.Service.CancelAsync (object userState) inline
IsLocalFileSystemWebService()
bool TestGui.localhost.Service.IsLocalFileSystemWebService (string url) inline private
Referenced by TestGui.localhost.Service.Service().
Member Data Documentation
PosljiPaketOperationCompleted
System.Threading.SendOrPostCallback TestGui.localhost.Service.PosljiPaketOperationCompleted private
Referenced by TestGui.localhost.Service.PosljiPaketAsync().
PaketStatusOperationCompleted
System.Threading.SendOrPostCallback TestGui.localhost.Service.PaketStatusOperationCompleted private
Referenced by TestGui.localhost.Service.PaketStatusAsync().
PaketShemaOperationCompleted
System.Threading.SendOrPostCallback TestGui.localhost.Service.PaketShemaOperationCompleted private
Referenced by TestGui.localhost.Service.PaketShemaAsync().
PaketStatusShemaOperationCompleted
System.Threading.SendOrPostCallback TestGui.localhost.Service.PaketStatusShemaOperationCompleted private
Referenced by TestGui.localhost.Service.PaketStatusShemaAsync().
PaketTipZalogaVrednostiOperationCompleted
System.Threading.SendOrPostCallback TestGui.localhost.Service.PaketTipZalogaVrednostiOperationCompleted private
Referenced by TestGui.localhost.Service.PaketTipZalogaVrednostiAsync().
PaketStatusZalogaVrednostiOperationCompleted
System.Threading.SendOrPostCallback TestGui.localhost.Service.PaketStatusZalogaVrednostiOperationCompleted private
Referenced by TestGui.localhost.Service.PaketStatusZalogaVrednostiAsync().
useDefaultCredentialsSetExplicitly
bool TestGui.localhost.Service.useDefaultCredentialsSetExplicitly private
Property Documentation
Url
new string TestGui.localhost.Service.Url get set
Referenced by TestGui.Form1.btnGetPaketShema_Click(), TestGui.Form1.btnGetPaketStatusShema_Click(), TestGui.Form1.btnPaketStatusZV_Click(), TestGui.Form1.btnPaketTipZV_Click(), TestGui.Form1.btnPodrocjaZV_Click(), TestGui.Form1.button6_Click(), TestGui.Form1.PosljiPaket(), and TestGui.localhost.Service.Service().
UseDefaultCredentials
new bool TestGui.localhost.Service.UseDefaultCredentials get set
Referenced by TestGui.localhost.Service.Service().
Event Documentation
PosljiPaketCompleted
PosljiPaketCompletedEventHandler TestGui.localhost.Service.PosljiPaketCompleted
Referenced by TestGui.localhost.Service.OnPosljiPaketOperationCompleted().
PaketStatusCompleted
PaketStatusCompletedEventHandler TestGui.localhost.Service.PaketStatusCompleted
Referenced by TestGui.localhost.Service.OnPaketStatusOperationCompleted().
PaketShemaCompleted
PaketShemaCompletedEventHandler TestGui.localhost.Service.PaketShemaCompleted
Referenced by TestGui.localhost.Service.OnPaketShemaOperationCompleted().
PaketStatusShemaCompleted
PaketStatusShemaCompletedEventHandler TestGui.localhost.Service.PaketStatusShemaCompleted
Referenced by TestGui.localhost.Service.OnPaketStatusShemaOperationCompleted().
PaketTipZalogaVrednostiCompleted
PaketTipZalogaVrednostiCompletedEventHandler TestGui.localhost.Service.PaketTipZalogaVrednostiCompleted
Referenced by TestGui.localhost.Service.OnPaketTipZalogaVrednostiOperationCompleted().
PaketStatusZalogaVrednostiCompleted
PaketStatusZalogaVrednostiCompletedEventHandler TestGui.localhost.Service.PaketStatusZalogaVrednostiCompleted
Referenced by TestGui.localhost.Service.OnPaketStatusZalogaVrednostiOperationCompleted().
The documentation for this class was generated from the following file:
igtest/tmp_prem/prefa/95_Test/TestUtils/TestGui/Web References/localhost/Reference.cs