Doc: IGLib EXTENDED: alglib.hqrnd Class Reference
alglib.hqrnd Class Reference
Classes
class hqrndstate
Static Public Member Functions
static void hqrndrandomize (hqrndstate state)
static void hqrndseed (int s1, int s2, hqrndstate state)
static double hqrnduniformr (hqrndstate state)
static int hqrnduniformi (hqrndstate state, int n)
static double hqrndnormal (hqrndstate state)
static void hqrndunit2 (hqrndstate state, ref double x, ref double y)
static void hqrndnormal2 (hqrndstate state, ref double x1, ref double x2)
static double hqrndexponential (hqrndstate state, double lambdav)
static double hqrnddiscrete (hqrndstate state, double[] x, int n)
static double hqrndcontinuous (hqrndstate state, double[] x, int n)
static void hqrndrandomize (hqrndstate state)
static void hqrndseed (int s1, int s2, hqrndstate state)
static double hqrnduniformr (hqrndstate state)
static int hqrnduniformi (hqrndstate state, int n)
static double hqrndnormal (hqrndstate state)
static void hqrndunit2 (hqrndstate state, ref double x, ref double y)
static void hqrndnormal2 (hqrndstate state, ref double x1, ref double x2)
static double hqrndexponential (hqrndstate state, double lambdav)
static double hqrnddiscrete (hqrndstate state, double[] x, int n)
static double hqrndcontinuous (hqrndstate state, double[] x, int n)
Static Public Attributes
const int hqrndmax = 2147483563
const int hqrndm1 = 2147483563
const int hqrndm2 = 2147483399
const int hqrndmagic = 1634357784
Static Private Member Functions
static int hqrndintegerbase (hqrndstate state)
static int hqrndintegerbase (hqrndstate state)
Member Function Documentation
hqrndrandomize() [1/2]
static void alglib.hqrnd.hqrndrandomize (hqrndstate state) inline static
References alglib.hqrnd.hqrndm1, alglib.hqrnd.hqrndm2, alglib.hqrnd.hqrndseed(), and alglib.math.randominteger().
Referenced by alglib.testhqrndunit.hqrndcontinuoustest(), alglib.hqrndrandomize(), and alglib.testhqrndunit.testhqrnd().
hqrndseed() [1/2]
static void alglib.hqrnd.hqrndseed (int s1, int s2, hqrndstate state) inline static
References alglib.hqrnd.hqrndm1, alglib.hqrnd.hqrndm2, alglib.hqrnd.hqrndmagic, alglib.hqrnd.hqrndmax, alglib.hqrnd.hqrndstate.magicv, alglib.hqrnd.hqrndstate.s1, alglib.hqrnd.hqrndstate.s2, and alglib.hqrnd.hqrndstate.v.
Referenced by alglib.testhqrndunit.hqrnddiscretetest(), alglib.hqrnd.hqrndrandomize(), alglib.hqrndseed(), and alglib.testhqrndunit.testhqrnd().
hqrnduniformr() [1/2]
static double alglib.hqrnd.hqrnduniformr (hqrndstate state) inline static
References alglib.hqrnd.hqrndintegerbase(), and alglib.hqrnd.hqrndstate.v.
Referenced by alglib.hqrnd.hqrndcontinuous(), alglib.hqrnd.hqrndexponential(), alglib.hqrnd.hqrndnormal2(), alglib.hqrnduniformr(), and alglib.testhqrndunit.testhqrnd().
hqrnduniformi() [1/2]
static int alglib.hqrnd.hqrnduniformi (hqrndstate state, int n) inline static
References alglib.ap.assert().
Referenced by alglib.hqrnd.hqrndcontinuous(), alglib.hqrnd.hqrnddiscrete(), alglib.hqrnduniformi(), alglib.hqrnd.hqrnduniformi(), and alglib.testhqrndunit.testhqrnd().
hqrndnormal() [1/2]
static double alglib.hqrnd.hqrndnormal (hqrndstate state) inline static
Referenced by alglib.hqrndnormal().
hqrndunit2() [1/2]
static void alglib.hqrnd.hqrndunit2 (hqrndstate state, ref double x, ref double y) inline static
Referenced by alglib.hqrndunit2(), and alglib.testhqrndunit.testhqrnd().
hqrndnormal2() [1/2]
static void alglib.hqrnd.hqrndnormal2 (hqrndstate state, ref double x1, ref double x2) inline static
Referenced by alglib.hqrnd.hqrndnormal(), alglib.hqrndnormal2(), alglib.hqrnd.hqrndunit2(), and alglib.testhqrndunit.testhqrnd().
hqrndexponential() [1/2]
static double alglib.hqrnd.hqrndexponential (hqrndstate state, double lambdav) inline static
Referenced by alglib.hqrndexponential(), and alglib.testhqrndunit.testhqrnd().
hqrnddiscrete() [1/2]
static double alglib.hqrnd.hqrnddiscrete (hqrndstate state, double[] x, int n) inline static
Referenced by alglib.hqrnddiscrete(), and alglib.testhqrndunit.hqrnddiscretetest().
hqrndcontinuous() [1/2]
static double alglib.hqrnd.hqrndcontinuous (hqrndstate state, double[] x, int n) inline static
Referenced by alglib.hqrndcontinuous(), and alglib.testhqrndunit.hqrndcontinuoustest().
hqrndintegerbase() [1/2]
static int alglib.hqrnd.hqrndintegerbase (hqrndstate state) inline static private
Referenced by alglib.hqrnd.hqrnduniformi(), and alglib.hqrnd.hqrnduniformr().
hqrndrandomize() [2/2]
static void alglib.hqrnd.hqrndrandomize (hqrndstate state) inline static
References alglib.hqrnd.hqrndm1, alglib.hqrnd.hqrndm2, alglib.hqrnd.hqrndseed(), and alglib.math.randominteger().
hqrndseed() [2/2]
static void alglib.hqrnd.hqrndseed (int s1, int s2, hqrndstate state) inline static
References alglib.hqrnd.hqrndm1, alglib.hqrnd.hqrndm2, and alglib.hqrnd.hqrndmagic.
hqrnduniformr() [2/2]
static double alglib.hqrnd.hqrnduniformr (hqrndstate state) inline static
References alglib.hqrnd.hqrndintegerbase(), and alglib.hqrnd.hqrndmax.
hqrnduniformi() [2/2]
static int alglib.hqrnd.hqrnduniformi (hqrndstate state, int n) inline static
References alglib.ap.assert(), alglib.hqrnd.hqrndintegerbase(), alglib.hqrnd.hqrndmax, and alglib.hqrnd.hqrnduniformi().
hqrndnormal() [2/2]
static double alglib.hqrnd.hqrndnormal (hqrndstate state) inline static
References alglib.hqrnd.hqrndnormal2().
hqrndunit2() [2/2]
static void alglib.hqrnd.hqrndunit2 (hqrndstate state, ref double x, ref double y) inline static
References alglib.hqrnd.hqrndnormal2(), and alglib.math.sqr().
hqrndnormal2() [2/2]
static void alglib.hqrnd.hqrndnormal2 (hqrndstate state, ref double x1, ref double x2) inline static
References alglib.hqrnd.hqrnduniformr(), and alglib.math.sqr().
hqrndexponential() [2/2]
static double alglib.hqrnd.hqrndexponential (hqrndstate state, double lambdav) inline static
References alglib.ap.assert(), and alglib.hqrnd.hqrnduniformr().
hqrnddiscrete() [2/2]
static double alglib.hqrnd.hqrnddiscrete (hqrndstate state, double[] x, int n) inline static
References alglib.ap.assert(), and alglib.hqrnd.hqrnduniformi().
hqrndcontinuous() [2/2]
static double alglib.hqrnd.hqrndcontinuous (hqrndstate state, double[] x, int n) inline static
References alglib.ap.assert(), alglib.hqrnd.hqrnduniformi(), and alglib.hqrnd.hqrnduniformr().
hqrndintegerbase() [2/2]
static int alglib.hqrnd.hqrndintegerbase (hqrndstate state) inline static private
References alglib.ap.assert(), and alglib.hqrnd.hqrndmagic.
Member Data Documentation
hqrndmax
const int alglib.hqrnd.hqrndmax = 2147483563 static
Referenced by alglib.hqrnd.hqrndseed(), alglib.hqrnd.hqrnduniformi(), and alglib.hqrnd.hqrnduniformr().
hqrndm1
const int alglib.hqrnd.hqrndm1 = 2147483563 static
Referenced by alglib.hqrnd.hqrndrandomize(), and alglib.hqrnd.hqrndseed().
hqrndm2
const int alglib.hqrnd.hqrndm2 = 2147483399 static
Referenced by alglib.hqrnd.hqrndrandomize(), and alglib.hqrnd.hqrndseed().
hqrndmagic
const int alglib.hqrnd.hqrndmagic = 1634357784 static
Referenced by alglib.hqrnd.hqrndintegerbase(), and alglib.hqrnd.hqrndseed().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/alglibmisc.cs