Doc: IGLib EXTENDED: NUnit.Framework.Attributes.Tests.CommandWrapperTests Class Reference
NUnit.Framework.Attributes.Tests.CommandWrapperTests Class Reference
Classes
class ExpectedExceptionAttribute
Extremely simple ExpectedException implementation for use in the test
Public Member Functions
void CorrectExceptionThrown ()
void ThrowsCorrectException ()
void NoExceptionThrown ()
void ThrowsNoException ()
void WrongExceptionThrown ()
void ThrowsWrongException ()
Member Function Documentation
CorrectExceptionThrown()
void NUnit.Framework.Attributes.Tests.CommandWrapperTests.CorrectExceptionThrown () inline
References NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestBuilder.RunTestCase(), NUnit.Framework.Interfaces.ResultState.Success, and NUnit.Framework.Assert.That().
ThrowsCorrectException()
void NUnit.Framework.Attributes.Tests.CommandWrapperTests.ThrowsCorrectException () inline
NoExceptionThrown()
void NUnit.Framework.Attributes.Tests.CommandWrapperTests.NoExceptionThrown () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.Failure, NUnit.TestUtilities.TestBuilder.RunTestCase(), and NUnit.Framework.Assert.That().
ThrowsNoException()
void NUnit.Framework.Attributes.Tests.CommandWrapperTests.ThrowsNoException () inline
WrongExceptionThrown()
void NUnit.Framework.Attributes.Tests.CommandWrapperTests.WrongExceptionThrown () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.Failure, NUnit.TestUtilities.TestBuilder.RunTestCase(), and NUnit.Framework.Assert.That().
ThrowsWrongException()
void NUnit.Framework.Attributes.Tests.CommandWrapperTests.ThrowsWrongException () inline
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/CommandWrapperTests.cs