Doc: IGLib EXTENDED: AForge.Imaging.Formats.IImageDecoder Interface Reference
AForge.Imaging.Formats.IImageDecoder Interface Reference
Image decoder interface, which specifies set of methods, which should be implemented by image decoders for different file formats.
Public Member Functions
Bitmap DecodeSingleFrame (Stream stream)
Decode first frame of image from the specified stream.
int Open (Stream stream)
Open specified stream.
Bitmap DecodeFrame (int frameIndex, out ImageInfo imageInfo)
Decode specified frame.
void Close ()
Close decoding of previously opened stream.
Detailed Description
Image decoder interface, which specifies set of methods, which should be implemented by image decoders for different file formats.
The interface specifies set of methods, which are suitable not only for simple one-frame image formats. The interface also defines methods to work with image formats designed to store multiple frames and image formats which provide different type of image description (like acquisition parameters, etc).
Member Function Documentation
DecodeSingleFrame()
Bitmap AForge.Imaging.Formats.IImageDecoder.DecodeSingleFrame (Stream stream)
Decode first frame of image from the specified stream.
Parameters
stream Source stream, which contains encoded image.
Returns
Returns decoded image frame.
For one-frame image formats the method is supposed to decode single available frame. For multi-frame image formats the first frame should be decoded.
Implementations of this method may throw System.FormatException exception to report about unrecognized image format, System.ArgumentException exception to report about incorrectly formatted image or NotSupportedException exception to report if certain formats are not supported.
Implemented in AForge.Imaging.Formats.FITSCodec, and AForge.Imaging.Formats.PNMCodec.
Open()
int AForge.Imaging.Formats.IImageDecoder.Open (Stream stream)
Open specified stream.
Parameters
stream Stream to open.
Returns
Returns number of images found in the specified stream.
Implementation of this method is supposed to read image's header, checking for correct image format and reading its atributes.
Implementations of this method may throw System.FormatException exception to report about unrecognized image format, System.ArgumentException exception to report about incorrectly formatted image or NotSupportedException exception to report if certain formats are not supported.
Implemented in AForge.Imaging.Formats.FITSCodec, and AForge.Imaging.Formats.PNMCodec.
Referenced by AForge.Imaging.Formats.ImageDecoder.DecodeFromFile().
DecodeFrame()
Bitmap AForge.Imaging.Formats.IImageDecoder.DecodeFrame (int frameIndex, out ImageInfo imageInfo)
Decode specified frame.
Parameters
frameIndex Image frame to decode.
imageInfo Receives information about decoded frame.
Returns
Returns decoded frame.
Implementations of this method may throw System.NullReferenceException exception in the case if no image stream was opened previously, System.ArgumentOutOfRangeException in the case if stream does not contain frame with specified index or System.ArgumentException exception to report about incorrectly formatted image.
Implemented in AForge.Imaging.Formats.FITSCodec, and AForge.Imaging.Formats.PNMCodec.
Referenced by AForge.Imaging.Formats.ImageDecoder.DecodeFromFile().
Close()
void AForge.Imaging.Formats.IImageDecoder.Close ()
Close decoding of previously opened stream.
Implementations of this method don't close stream itself, but just close decoding cleaning all associated data with it.
Implemented in AForge.Imaging.Formats.FITSCodec, and AForge.Imaging.Formats.PNMCodec.
Referenced by AForge.Imaging.Formats.ImageDecoder.DecodeFromFile().
The documentation for this interface was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging.Formats/IImageDecoder.cs