Doc: IGLib EXTENDED: AForge.Vision.Motion.MotionDetector Class Reference
AForge.Vision.Motion.MotionDetector Class Reference
Motion detection wrapper class, which performs motion detection and processing.
Public Member Functions
MotionDetector (IMotionDetector detector)
Initializes a new instance of the MotionDetector class.
MotionDetector (IMotionDetector detector, IMotionProcessing processor)
Initializes a new instance of the MotionDetector class.
float ProcessFrame (Bitmap videoFrame)
Process new video frame.
float ProcessFrame (BitmapData videoFrame)
Process new video frame.
float ProcessFrame (UnmanagedImage videoFrame)
Process new video frame.
void Reset ()
Reset motion detector to initial state.
Properties
IMotionDetector MotionDetectionAlgorithm [get, set]
Motion detection algorithm to apply to each video frame.
IMotionProcessing MotionProcessingAlgorithm [get, set]
Motion processing algorithm to apply to each video frame after motion detection is done.
Rectangle[] MotionZones [get, set]
Set of zones to detect motion in.
Private Member Functions
unsafe void CreateMotionZonesFrame ()
Private Attributes
IMotionDetector detector
IMotionProcessing processor
Rectangle[] motionZones = null
UnmanagedImage zonesFrame
int videoWidth
int videoHeight
object sync = new object()
Detailed Description
Motion detection wrapper class, which performs motion detection and processing.
The class serves as a wrapper class for motion detection and motion processing algorithms, allowing to call them with single call. Unlike motion detection and motion processing interfaces, the class also provides additional methods for convenience, so the algorithms could be applied not only to AForge.Imaging.UnmanagedImage, but to .NET's Bitmap class as well.
In addition to wrapping of motion detection and processing algorthms, the class provides some additional functionality. Using MotionZones property it is possible to specify set of rectangular zones to observe - only motion in these zones is counted and post procesed.
Sample usage:
// create motion detector
MotionDetector detector = new MotionDetector(
    new SimpleBackgroundModelingDetector( ),
    new MotionAreaHighlighting( ) );
// continuously feed video frames to motion detector
while (...)
{
    // process new video frame and check motion level
    if ( detector.ProcessFrame( videoFrame ) > 0.02 )
    {
        // ring alarm or do somethng else
    }
}
Constructor & Destructor Documentation
MotionDetector() [1/2]
AForge.Vision.Motion.MotionDetector.MotionDetector (IMotionDetector detector) inline
Initializes a new instance of the MotionDetector class.
Parameters
detector Motion detection algorithm to apply to each video frame.
MotionDetector() [2/2]
AForge.Vision.Motion.MotionDetector.MotionDetector (IMotionDetector detector, IMotionProcessing processor) inline
Initializes a new instance of the MotionDetector class.
Parameters
detector Motion detection algorithm to apply to each video frame.
processor Motion processing algorithm to apply to each video frame after motion detection is done.
References AForge.Vision.Motion.MotionDetector.detector, and AForge.Vision.Motion.MotionDetector.processor.
Member Function Documentation
ProcessFrame() [1/3]
float AForge.Vision.Motion.MotionDetector.ProcessFrame (Bitmap videoFrame) inline
Process new video frame.
Parameters
videoFrame Video frame to process (detect motion in).
Returns
Returns amount of motion, which is provided IMotionDetector.MotionLevel property of the motion detection algorithm in use.
See ProcessFrame(UnmanagedImage) for additional details.
References AForge.Math.Geometry.Rectangle.
Referenced by AForge.Vision.Motion.MotionDetector.ProcessFrame(), and MotionDetectorSample.MainForm.videoSourcePlayer_NewFrame().
ProcessFrame() [2/3]
float AForge.Vision.Motion.MotionDetector.ProcessFrame (BitmapData videoFrame) inline
Process new video frame.
Parameters
videoFrame Video frame to process (detect motion in).
Returns
Returns amount of motion, which is provided IMotionDetector.MotionLevel property of the motion detection algorithm in use.
See ProcessFrame(UnmanagedImage) for additional details.
References AForge.Vision.Motion.MotionDetector.ProcessFrame().
ProcessFrame() [3/3]
float AForge.Vision.Motion.MotionDetector.ProcessFrame (UnmanagedImage videoFrame) inline
Process new video frame.
Parameters
videoFrame Video frame to process (detect motion in).
Returns
Returns amount of motion, which is provided IMotionDetector.MotionLevel property of the motion detection algorithm in use.
The method first of all applies motion detection algorithm to the specified video frame to calculate motion level and motion frame. After this it applies motion processing algorithm (if it was set) to do further post processing, like highlighting motion areas, counting moving objects, etc.
<note>In the case if MotionZones property is set, this method will perform motion filtering right after motion algorithm is done and before passing motion frame to motion processing algorithm. The method does filtering right on the motion frame, which is produced by motion detection algorithm. At the same time the method recalculates motion level and returns new value, which takes motion zones into account (but the new value is not set back to motion detection algorithm' IMotionDetector.MotionLevel property). </note>
References AForge.Vision.Motion.MotionDetector.CreateMotionZonesFrame(), AForge.Vision.Motion.MotionDetector.detector, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Vision.Motion.IMotionDetector.MotionFrame, AForge.Vision.Motion.IMotionDetector.MotionLevel, AForge.Vision.Motion.MotionDetector.motionZones, AForge.Vision.Motion.IMotionProcessing.ProcessFrame(), AForge.Vision.Motion.IMotionDetector.ProcessFrame(), AForge.Vision.Motion.MotionDetector.processor, AForge.Imaging.UnmanagedImage.Stride, AForge.Vision.Motion.MotionDetector.sync, AForge.Vision.Motion.MotionDetector.videoHeight, AForge.Vision.Motion.MotionDetector.videoWidth, AForge.Imaging.UnmanagedImage.Width, and AForge.Vision.Motion.MotionDetector.zonesFrame.
Reset()
void AForge.Vision.Motion.MotionDetector.Reset () inline
Reset motion detector to initial state.
The method resets motion detection and motion processing algotithms by calling their IMotionDetector.Reset and IMotionProcessing.Reset methods.
References AForge.Vision.Motion.MotionDetector.detector, AForge.Imaging.UnmanagedImage.Dispose(), AForge.Vision.Motion.MotionDetector.processor, AForge.Vision.Motion.IMotionProcessing.Reset(), AForge.Vision.Motion.IMotionDetector.Reset(), AForge.Vision.Motion.MotionDetector.sync, AForge.Vision.Motion.MotionDetector.videoHeight, AForge.Vision.Motion.MotionDetector.videoWidth, and AForge.Vision.Motion.MotionDetector.zonesFrame.
Referenced by MotionDetectorSample.MainForm.CloseVideoSource().
CreateMotionZonesFrame()
unsafe void AForge.Vision.Motion.MotionDetector.CreateMotionZonesFrame () inline private
References AForge.Imaging.UnmanagedImage.Create(), AForge.Imaging.UnmanagedImage.Dispose(), AForge.Imaging.UnmanagedImage.ImageData, AForge.Vision.Motion.MotionDetector.motionZones, AForge.Math.Geometry.Rectangle, AForge.SystemTools.SetUnmanagedMemory(), AForge.Imaging.UnmanagedImage.Stride, AForge.Vision.Motion.MotionDetector.sync, AForge.Vision.Motion.MotionDetector.videoHeight, AForge.Vision.Motion.MotionDetector.videoWidth, and AForge.Vision.Motion.MotionDetector.zonesFrame.
Referenced by AForge.Vision.Motion.MotionDetector.ProcessFrame().
Member Data Documentation
detector
IMotionDetector AForge.Vision.Motion.MotionDetector.detector private
Referenced by AForge.Vision.Motion.MotionDetector.MotionDetector(), AForge.Vision.Motion.MotionDetector.ProcessFrame(), and AForge.Vision.Motion.MotionDetector.Reset().
processor
IMotionProcessing AForge.Vision.Motion.MotionDetector.processor private
Referenced by AForge.Vision.Motion.MotionDetector.MotionDetector(), AForge.Vision.Motion.MotionDetector.ProcessFrame(), and AForge.Vision.Motion.MotionDetector.Reset().
motionZones
Rectangle [] AForge.Vision.Motion.MotionDetector.motionZones = null private
Referenced by AForge.Vision.Motion.MotionDetector.CreateMotionZonesFrame(), and AForge.Vision.Motion.MotionDetector.ProcessFrame().
zonesFrame
UnmanagedImage AForge.Vision.Motion.MotionDetector.zonesFrame private
Referenced by AForge.Vision.Motion.MotionDetector.CreateMotionZonesFrame(), AForge.Vision.Motion.MotionDetector.ProcessFrame(), and AForge.Vision.Motion.MotionDetector.Reset().
videoWidth
int AForge.Vision.Motion.MotionDetector.videoWidth private
Referenced by AForge.Vision.Motion.MotionDetector.CreateMotionZonesFrame(), AForge.Vision.Motion.MotionDetector.ProcessFrame(), and AForge.Vision.Motion.MotionDetector.Reset().
videoHeight
int AForge.Vision.Motion.MotionDetector.videoHeight private
Referenced by AForge.Vision.Motion.MotionDetector.CreateMotionZonesFrame(), AForge.Vision.Motion.MotionDetector.ProcessFrame(), and AForge.Vision.Motion.MotionDetector.Reset().
sync
object AForge.Vision.Motion.MotionDetector.sync = new object() private
Referenced by AForge.Vision.Motion.MotionDetector.CreateMotionZonesFrame(), AForge.Vision.Motion.MotionDetector.ProcessFrame(), and AForge.Vision.Motion.MotionDetector.Reset().
Property Documentation
MotionDetectionAlgorithm
IMotionDetector AForge.Vision.Motion.MotionDetector.MotionDetectionAlgorithm get set
Motion detection algorithm to apply to each video frame.
The property sets motion detection algorithm, which is used by ProcessFrame(UnmanagedImage) method in order to calculate motion level and motion frame.
Referenced by MotionDetectorSample.MainForm.SetMotionDetectionAlgorithm().
MotionProcessingAlgorithm
IMotionProcessing AForge.Vision.Motion.MotionDetector.MotionProcessingAlgorithm get set
Motion processing algorithm to apply to each video frame after motion detection is done.
The property sets motion processing algorithm, which is used by ProcessFrame(UnmanagedImage) method after motion detection in order to do further post processing of motion frames. The aim of further post processing depends on actual implementation of the specified motion processing algorithm - it can be highlighting of motion area, objects counting, etc.
Referenced by MotionDetectorSample.MainForm.SetMotionDetectionAlgorithm(), MotionDetectorSample.MainForm.SetMotionProcessingAlgorithm(), and MotionDetectorSample.MainForm.videoSourcePlayer_NewFrame().
MotionZones
Rectangle [] AForge.Vision.Motion.MotionDetector.MotionZones get set
Set of zones to detect motion in.
The property keeps array of rectangular zones, which are observed for motion detection. Motion outside of these zones is ignored.
In the case if this property is set, the ProcessFrame(UnmanagedImage) method will filter out all motion witch was detected by motion detection algorithm, but is not located in the specified zones.
Referenced by MotionDetectorSample.MainForm.defineMotionregionsToolStripMenuItem_Click().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Vision/Motion/MotionDetector.cs