Doc: IGLib EXTENDED: IG.Forms.VectorFunctionPlotter1dForm Class Reference
IG.Forms.VectorFunctionPlotter1dForm Class Reference
Public Member Functions
VectorFunctionPlotter1dForm ()
VectorFunctionPlotter1dForm ()
VectorFunctionPlotter1dForm ()
VectorFunctionPlotter1dForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
VectorFunctionPlotter1d MainControl [get]
Private Member Functions
void neuralParametricTest1_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void neuralParametricTest1_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void neuralParametricTest1_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void neuralParametricTest1_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
IG.Forms.VectorFunctionPlotter1d neuralParametricTest1
Constructor & Destructor Documentation
VectorFunctionPlotter1dForm() [1/4]
IG.Forms.VectorFunctionPlotter1dForm.VectorFunctionPlotter1dForm () inline
References IG.Forms.VectorFunctionPlotter1dForm.InitializeComponent().
VectorFunctionPlotter1dForm() [2/4]
IG.Forms.VectorFunctionPlotter1dForm.VectorFunctionPlotter1dForm () inline
References IG.Forms.VectorFunctionPlotter1dForm.InitializeComponent().
VectorFunctionPlotter1dForm() [3/4]
IG.Forms.VectorFunctionPlotter1dForm.VectorFunctionPlotter1dForm () inline
References IG.Forms.VectorFunctionPlotter1dForm.InitializeComponent().
VectorFunctionPlotter1dForm() [4/4]
IG.Forms.VectorFunctionPlotter1dForm.VectorFunctionPlotter1dForm () inline
References IG.Forms.VectorFunctionPlotter1dForm.InitializeComponent().
Member Function Documentation
neuralParametricTest1_Load() [1/4]
void IG.Forms.VectorFunctionPlotter1dForm.neuralParametricTest1_Load (object sender, EventArgs e) inline private
Referenced by IG.Forms.VectorFunctionPlotter1dForm.InitializeComponent().
Dispose() [1/4]
override void IG.Forms.VectorFunctionPlotter1dForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.VectorFunctionPlotter1dForm.components.
InitializeComponent() [1/4]
void IG.Forms.VectorFunctionPlotter1dForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.VectorFunctionPlotter1d.Function, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Forms.VectorFunctionPlotter1dForm.neuralParametricTest1, and IG.Forms.VectorFunctionPlotter1dForm.neuralParametricTest1_Load().
Referenced by IG.Forms.VectorFunctionPlotter1dForm.VectorFunctionPlotter1dForm().
neuralParametricTest1_Load() [2/4]
void IG.Forms.VectorFunctionPlotter1dForm.neuralParametricTest1_Load (object sender, EventArgs e) inline private
Dispose() [2/4]
override void IG.Forms.VectorFunctionPlotter1dForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.VectorFunctionPlotter1dForm.components.
InitializeComponent() [2/4]
void IG.Forms.VectorFunctionPlotter1dForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.VectorFunctionPlotter1d.Function, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Forms.VectorFunctionPlotter1dForm.neuralParametricTest1, and IG.Forms.VectorFunctionPlotter1dForm.neuralParametricTest1_Load().
neuralParametricTest1_Load() [3/4]
void IG.Forms.VectorFunctionPlotter1dForm.neuralParametricTest1_Load (object sender, EventArgs e) inline private
Dispose() [3/4]
override void IG.Forms.VectorFunctionPlotter1dForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.VectorFunctionPlotter1dForm.components.
InitializeComponent() [3/4]
void IG.Forms.VectorFunctionPlotter1dForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.VectorFunctionPlotter1d.Function, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Forms.VectorFunctionPlotter1dForm.neuralParametricTest1, and IG.Forms.VectorFunctionPlotter1dForm.neuralParametricTest1_Load().
neuralParametricTest1_Load() [4/4]
void IG.Forms.VectorFunctionPlotter1dForm.neuralParametricTest1_Load (object sender, EventArgs e) inline private
Dispose() [4/4]
override void IG.Forms.VectorFunctionPlotter1dForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.VectorFunctionPlotter1dForm.components.
InitializeComponent() [4/4]
void IG.Forms.VectorFunctionPlotter1dForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.VectorFunctionPlotter1d.Function, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Forms.VectorFunctionPlotter1dForm.neuralParametricTest1, and IG.Forms.VectorFunctionPlotter1dForm.neuralParametricTest1_Load().
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.VectorFunctionPlotter1dForm.components = null private
Required designer variable.
Referenced by IG.Forms.VectorFunctionPlotter1dForm.Dispose().
neuralParametricTest1
IG Forms VectorFunctionPlotter1d IG.Forms.VectorFunctionPlotter1dForm.neuralParametricTest1 private
Referenced by IG.Forms.VectorFunctionPlotter1dForm.InitializeComponent().
Property Documentation
MainControl
VectorFunctionPlotter1d IG.Forms.VectorFunctionPlotter1dForm.MainControl get
Referenced by IG.Forms.VectorFunctionScriptControl.btnPlot1d_Click(), and IG.Forms.ScalarFunctionScriptControl.btnPlot1d_Click().
The documentation for this class was generated from the following files:
iglib/extensions/iglibext/Forms/Numeric/FromNeural/VectorFunctionPlotter1dForm.cs
iglib/extensions/iglibext/Forms/Numeric/FromNeural/VectorFunctionPlotter1dForm.Designer.cs