Doc: IGLib EXTENDED: IG.Forms.ImageViewerControl Class Reference
IG.Forms.ImageViewerControl Class Reference
Public Member Functions
ImageViewerControl ()
void ShowViewedItem ()
Shows / plays the viewed contents.
void Clear ()
Clears the viewer and eventually releases any resources used.
bool IsEligibleForViewing (string fileLocation)
Rerurns a flag indicating whether the file (or web resource) at the specified location is eligible for vieiwnig in the current viewer or not.
bool IsEligibleForViewing (Stream stream)
Returnns a flag indicating whether the specified stream is eligible for vieiwnig or not.
void BrowseFile ()
Opens a browser to select the file shown.
ImageViewerControl ()
void ShowViewedItem ()
Shows / plays the viewed contents.
void Clear ()
Clears the viewer and eventually releases any resources used.
bool IsEligibleForViewing (string fileLocation)
Rerurns a flag indicating whether the file (or web resource) at the specified location is eligible for vieiwnig in the current viewer or not.
bool IsEligibleForViewing (Stream stream)
Returnns a flag indicating whether the specified stream is eligible for vieiwnig or not.
void BrowseFile ()
Opens a browser to select the file shown.
ImageViewerControl ()
void ShowViewedItem ()
Shows / plays the viewed contents.
void Clear ()
Clears the viewer and eventually releases any resources used.
bool IsEligibleForViewing (string fileLocation)
Rerurns a flag indicating whether the file (or web resource) at the specified location is eligible for vieiwnig in the current viewer or not.
bool IsEligibleForViewing (Stream stream)
Returnns a flag indicating whether the specified stream is eligible for vieiwnig or not.
void BrowseFile ()
Opens a browser to select the file shown.
Static Public Member Functions
static bool IsValidHttpUrl (string uriNamme)
Chechks whether the specified URI is a valid HTTP URL.
static Image GetImageFromUrl (string url)
Gets an image from the specified URL.
static bool IsValidHttpUrl (string uriNamme)
Chechks whether the specified URI is a valid HTTP URL.
static Image GetImageFromUrl (string url)
Gets an image from the specified URL.
static bool IsValidHttpUrl (string uriNamme)
Chechks whether the specified URI is a valid HTTP URL.
static Image GetImageFromUrl (string url)
Gets an image from the specified URL.
Protected Member Functions
void UpdateControlsVisible ()
Updates dependencies on IsControlsVisible.
void UpdateBrowsable ()
Updates dependencies on IsBrowsable.
void UpdateDragAndDrop ()
Updates dependencies on IsDragAndDrop.
override void Dispose (bool disposing)
Clean up any resources being used.
void UpdateControlsVisible ()
Updates dependencies on IsControlsVisible.
void UpdateBrowsable ()
Updates dependencies on IsBrowsable.
void UpdateDragAndDrop ()
Updates dependencies on IsDragAndDrop.
override void Dispose (bool disposing)
Clean up any resources being used.
void UpdateControlsVisible ()
Updates dependencies on IsControlsVisible.
void UpdateBrowsable ()
Updates dependencies on IsBrowsable.
void UpdateDragAndDrop ()
Updates dependencies on IsDragAndDrop.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
List< PictureBoxSizeMode > _availableSizeModes = Util.GetEnumValues<PictureBoxSizeMode>()
string _viewedFile
Stream _stream
bool _isShownImmediately = true
bool _canViewFiles = true
bool _canViewUrls = true
bool _canViewStreams = true
Whether the current viewer can read streams.
bool _isBrowsable = true
bool _isDragAndDrop = true
Properties
PictureBoxSizeMode SizeMode [get, set]
Enumeraton of type PictureBoxSizeMode that specifies how the image is sized and positioned witin the PictureBox control.
string ViewedFile [get, set]
Gets or sets path to the file or URL of the file that is currently being viewed.
Stream ViewedStream [get, set]
Gets or sets the stream containing the file that is currently being viewed.
bool IsShownImmediately [get, set]
Flag that specifies whether content is shown immediately after the viewed object is set.
bool CanViewFiles [get, set]
Whether the current viewer can view files from the file system.
bool CanViewUrls [get, set]
Whether the current viewer can view web resources (files on the internet).
bool CanViewStreams [get, set]
bool IsControlsVisible [get, set]
Gets / sets a flag that specified whether the viewer's controls are visible or not.
bool IsBrowsable [get, set]
Gets or sets the flag specifying whether one can browse for the file to be opened (e.g. by using the file selection dialog).
bool IsDragAndDrop [get, set]
Whether the viewer provides drag & drop capability.
Properties inherited from IG.Forms.IFileViewer
string ViewedFile [get, set]
Gets or sets path to the file or URL of the file that is currently being viewed.
Stream ViewedStream [get, set]
Gets or sets the stream containing the file that is currently being viewed.
bool IsShownImmediately [get, set]
Flag that specifies whether content is shown / played immediately after the viewed object is set.
bool CanViewFiles [get, set]
Whether the current viewer can view files from the file system.
bool CanViewUrls [get, set]
Whether the current viewer can view web resources (files on the internet).
bool CanViewStreams [get, set]
Whether the current viewer can read streams.
bool IsControlsVisible [get, set]
Gets / sets a flag that specified whether the viewer's controls are visible or not.
bool IsBrowsable [get, set]
Gets or sets the flag specifying whether one can browse for the file to be opened (e.g. by using the file selection dialog).
bool IsDragAndDrop [get, set]
Whether the viewer provides drag & drop capability.
Private Member Functions
void fileSelector1_FileSelected (object sender, EventArgs e)
Triggered when file is selected by the embedded file selector control.
void pictureBox1_DragDrop (object sender, DragEventArgs e)
void pictureBox1_DragEnter (object sender, DragEventArgs e)
void comboSizeMode_SelectedIndexChanged (object sender, EventArgs e)
void menuShowControls_Click (object sender, EventArgs e)
void menuClearHistory_Click (object sender, EventArgs e)
void comboSizeMode_Click (object sender, EventArgs e)
void menuDragDrop_Click (object sender, EventArgs e)
void menuBrowse_Click (object sender, EventArgs e)
void showControlsToolStripMenuItem_Click (object sender, EventArgs e)
void ImageViewerControl_Load (object sender, EventArgs e)
Handles the load event of the current control.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void fileSelector1_FileSelected (object sender, EventArgs e)
Triggered when file is selected by the embedded file selector control.
void pictureBox1_DragDrop (object sender, DragEventArgs e)
void pictureBox1_DragEnter (object sender, DragEventArgs e)
void comboSizeMode_SelectedIndexChanged (object sender, EventArgs e)
void menuShowControls_Click (object sender, EventArgs e)
void menuClearHistory_Click (object sender, EventArgs e)
void comboSizeMode_Click (object sender, EventArgs e)
void menuDragDrop_Click (object sender, EventArgs e)
void menuBrowse_Click (object sender, EventArgs e)
void showControlsToolStripMenuItem_Click (object sender, EventArgs e)
void ImageViewerControl_Load (object sender, EventArgs e)
Handles the load event of the current control.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void fileSelector1_FileSelected (object sender, EventArgs e)
Triggered when file is selected by the embedded file selector control.
void pictureBox1_DragDrop (object sender, DragEventArgs e)
void pictureBox1_DragEnter (object sender, DragEventArgs e)
void comboSizeMode_SelectedIndexChanged (object sender, EventArgs e)
void menuShowControls_Click (object sender, EventArgs e)
void menuClearHistory_Click (object sender, EventArgs e)
void comboSizeMode_Click (object sender, EventArgs e)
void menuDragDrop_Click (object sender, EventArgs e)
void menuBrowse_Click (object sender, EventArgs e)
void showControlsToolStripMenuItem_Click (object sender, EventArgs e)
void ImageViewerControl_Load (object sender, EventArgs e)
Handles the load event of the current control.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
PictureBoxSizeMode _sizeMode = PictureBoxSizeMode.CenterImage
bool _closeStreamAfterUse = false
bool _isControlsVisible = true
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.PictureBox pictureBox1
IG.Forms.FileSelector fileSelector1
System.Windows.Forms.Panel pnlOptions
System.Windows.Forms.Label lblSzeMode
System.Windows.Forms.ComboBox comboSizeMode
System.Windows.Forms.Panel pnlPicture
System.Windows.Forms.ContextMenuStrip contextMenuMain
System.Windows.Forms.Panel pnlOuter
System.Windows.Forms.Panel pnlControls
System.Windows.Forms.ToolStripMenuItem menuClearHistory
System.Windows.Forms.ToolStripMenuItem menuOptions
System.Windows.Forms.ToolStripMenuItem menuDragDrop
System.Windows.Forms.ToolStripMenuItem menuBrowse
System.Windows.Forms.ToolStripMenuItem menuShowControls
Constructor & Destructor Documentation
ImageViewerControl() [1/3]
IG.Forms.ImageViewerControl.ImageViewerControl () inline
References IG.Forms.ImageViewerControl._availableSizeModes, IG.Forms.ImageViewerControl.comboSizeMode, IG.Forms.ImageViewerControl.InitializeComponent(), and IG.Forms.ImageViewerControl.SizeMode.
ImageViewerControl() [2/3]
IG.Forms.ImageViewerControl.ImageViewerControl () inline
References IG.Forms.ImageViewerControl._availableSizeModes, IG.Forms.ImageViewerControl.comboSizeMode, IG.Forms.ImageViewerControl.InitializeComponent(), and IG.Forms.ImageViewerControl.SizeMode.
ImageViewerControl() [3/3]
IG.Forms.ImageViewerControl.ImageViewerControl () inline
References IG.Forms.ImageViewerControl._availableSizeModes, IG.Forms.ImageViewerControl.comboSizeMode, IG.Forms.ImageViewerControl.InitializeComponent(), and IG.Forms.ImageViewerControl.SizeMode.
Member Function Documentation
IsValidHttpUrl() [1/3]
static bool IG.Forms.ImageViewerControl.IsValidHttpUrl (string uriNamme) inline static
Chechks whether the specified URI is a valid HTTP URL.
Parameters
uriNamme URL to be tested.
Returns
True iif the specified string is a valid HTTP URL, false otherwise.
Referenced by IG.Forms.ImageViewerControl.IsEligibleForViewing(), and IG.Forms.ImageViewerControl.ShowViewedItem().
GetImageFromUrl() [1/3]
static Image IG.Forms.ImageViewerControl.GetImageFromUrl (string url) inline static
Gets an image from the specified URL.
Parameters
url URL of the image.
Returns
Image object (of class Image) obtained from the specified URL.
Referenced by IG.Forms.ImageViewerControl.IsEligibleForViewing(), and IG.Forms.ImageViewerControl.ShowViewedItem().
ShowViewedItem() [1/3]
void IG.Forms.ImageViewerControl.ShowViewedItem () inline
Shows / plays the viewed contents.
Can have the role of refresh when IsShownImmediately is true, or is used to actually show the contents after assigning it.
Implements IG.Forms.IFileViewer.
References IG.Forms.ImageViewerControl._viewedFile, IG.Forms.ImageViewerControl.CanViewFiles, IG.Forms.ImageViewerControl.CanViewUrls, IG.Forms.ImageViewerControl.GetImageFromUrl(), IG.Forms.ImageViewerControl.IsValidHttpUrl(), IG.Forms.ImageViewerControl.pictureBox1, IG.Forms.ImageViewerControl.ViewedFile, and IG.Forms.ImageViewerControl.ViewedStream.
Clear() [1/3]
void IG.Forms.ImageViewerControl.Clear () inline
Clears the viewer and eventually releases any resources used.
Implements IG.Forms.IFileViewer.
References IG.Forms.ImageViewerControl.pictureBox1, IG.Forms.ImageViewerControl.ViewedFile, and IG.Forms.ImageViewerControl.ViewedStream.
IsEligibleForViewing() [1/6]
bool IG.Forms.ImageViewerControl.IsEligibleForViewing (string fileLocation) inline
Rerurns a flag indicating whether the file (or web resource) at the specified location is eligible for vieiwnig in the current viewer or not.
Parameters
fileLocation Path to the file on a file system, or file URL.
Returns
True if the file can be viewed in the current viewer, false otherwise.
Implements IG.Forms.IFileViewer.
References IG.Forms.ImageViewerControl.CanViewFiles, IG.Forms.ImageViewerControl.CanViewUrls, IG.Forms.ImageViewerControl.GetImageFromUrl(), and IG.Forms.ImageViewerControl.IsValidHttpUrl().
IsEligibleForViewing() [2/6]
bool IG.Forms.ImageViewerControl.IsEligibleForViewing (Stream stream) inline
Returnns a flag indicating whether the specified stream is eligible for vieiwnig or not.
Parameters
stream Path to the file on a file system, or file URL.
Returns
True if the stream can be viewed in the current viewer, false otherwise.
Implements IG.Forms.IFileViewer.
UpdateControlsVisible() [1/3]
void IG.Forms.ImageViewerControl.UpdateControlsVisible () inline protected
Updates dependencies on IsControlsVisible.
References IG.Forms.ImageViewerControl.IsControlsVisible, IG.Forms.ImageViewerControl.menuShowControls, and IG.Forms.ImageViewerControl.pnlControls.
Referenced by IG.Forms.ImageViewerControl.ImageViewerControl_Load().
BrowseFile() [1/3]
void IG.Forms.ImageViewerControl.BrowseFile () inline
Opens a browser to select the file shown.
Available only when IsBrowsable property is true.
Implements IG.Forms.IFileViewer.
References IG.Forms.FileSelector.BrowseFile(), IG.Forms.ImageViewerControl.fileSelector1, and IG.Forms.ImageViewerControl.IsBrowsable.
UpdateBrowsable() [1/3]
void IG.Forms.ImageViewerControl.UpdateBrowsable () inline protected
Updates dependencies on IsBrowsable.
References IG.Forms.ImageViewerControl.fileSelector1, IG.Forms.ImageViewerControl.IsBrowsable, IG.Forms.FileSelector.IsBrowsable, and IG.Forms.ImageViewerControl.menuBrowse.
Referenced by IG.Forms.ImageViewerControl.ImageViewerControl_Load().
UpdateDragAndDrop() [1/3]
void IG.Forms.ImageViewerControl.UpdateDragAndDrop () inline protected
Updates dependencies on IsDragAndDrop.
References IG.Forms.ImageViewerControl.fileSelector1, IG.Forms.ImageViewerControl.IsDragAndDrop, IG.Forms.FileSelector.IsDragAndDrop, and IG.Forms.ImageViewerControl.menuDragDrop.
Referenced by IG.Forms.ImageViewerControl.ImageViewerControl_Load().
fileSelector1_FileSelected() [1/3]
void IG.Forms.ImageViewerControl.fileSelector1_FileSelected (object sender, EventArgs e) inline private
Triggered when file is selected by the embedded file selector control.
References IG.Forms.FileSelector.FilePath, IG.Forms.ImageViewerControl.fileSelector1, and IG.Forms.ImageViewerControl.ViewedFile.
Referenced by IG.Forms.ImageViewerControl.InitializeComponent().
pictureBox1_DragDrop() [1/3]
void IG.Forms.ImageViewerControl.pictureBox1_DragDrop (object sender, DragEventArgs e) inline private
References IG.Forms.ImageViewerControl.IsDragAndDrop, and IG.Forms.ImageViewerControl.ViewedFile.
Referenced by IG.Forms.ImageViewerControl.InitializeComponent().
pictureBox1_DragEnter() [1/3]
void IG.Forms.ImageViewerControl.pictureBox1_DragEnter (object sender, DragEventArgs e) inline private
References IG.Forms.ImageViewerControl.IsDragAndDrop.
Referenced by IG.Forms.ImageViewerControl.InitializeComponent().
comboSizeMode_SelectedIndexChanged() [1/3]
void IG.Forms.ImageViewerControl.comboSizeMode_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Forms.ImageViewerControl.comboSizeMode, and IG.Forms.ImageViewerControl.SizeMode.
Referenced by IG.Forms.ImageViewerControl.InitializeComponent().
menuShowControls_Click() [1/3]
void IG.Forms.ImageViewerControl.menuShowControls_Click (object sender, EventArgs e) inline private
References IG.Forms.ImageViewerControl.IsControlsVisible.
menuClearHistory_Click() [1/3]
void IG.Forms.ImageViewerControl.menuClearHistory_Click (object sender, EventArgs e) inline private
References IG.Forms.FileSelector.ClearHistory(), and IG.Forms.ImageViewerControl.fileSelector1.
Referenced by IG.Forms.ImageViewerControl.InitializeComponent().
comboSizeMode_Click() [1/3]
void IG.Forms.ImageViewerControl.comboSizeMode_Click (object sender, EventArgs e) inline private
References IG.Forms.ImageViewerControl.comboSizeMode.
Referenced by IG.Forms.ImageViewerControl.InitializeComponent().
menuDragDrop_Click() [1/3]
void IG.Forms.ImageViewerControl.menuDragDrop_Click (object sender, EventArgs e) inline private
References IG.Forms.ImageViewerControl.IsDragAndDrop.
Referenced by IG.Forms.ImageViewerControl.InitializeComponent().
menuBrowse_Click() [1/3]
void IG.Forms.ImageViewerControl.menuBrowse_Click (object sender, EventArgs e) inline private
References IG.Forms.ImageViewerControl.IsBrowsable.
Referenced by IG.Forms.ImageViewerControl.InitializeComponent().
showControlsToolStripMenuItem_Click() [1/3]
void IG.Forms.ImageViewerControl.showControlsToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.ImageViewerControl.IsControlsVisible.
Referenced by IG.Forms.ImageViewerControl.InitializeComponent().
ImageViewerControl_Load() [1/3]
void IG.Forms.ImageViewerControl.ImageViewerControl_Load (object sender, EventArgs e) inline private
Handles the load event of the current control.
References IG.Forms.ImageViewerControl.pictureBox1, IG.Forms.ImageViewerControl.SizeMode, IG.Forms.ImageViewerControl.UpdateBrowsable(), IG.Forms.ImageViewerControl.UpdateControlsVisible(), and IG.Forms.ImageViewerControl.UpdateDragAndDrop().
Referenced by IG.Forms.ImageViewerControl.InitializeComponent().
Dispose() [1/3]
override void IG.Forms.ImageViewerControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ImageViewerControl.components.
InitializeComponent() [1/3]
void IG.Forms.ImageViewerControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.ImageViewerControl.comboSizeMode, IG.Forms.ImageViewerControl.comboSizeMode_Click(), IG.Forms.ImageViewerControl.comboSizeMode_SelectedIndexChanged(), IG.Forms.ImageViewerControl.components, IG.Forms.ImageViewerControl.contextMenuMain, IG.Forms.FileSelector.FilePath, IG.Forms.FileSelector.FileSelected, IG.Forms.ImageViewerControl.fileSelector1, IG.Forms.ImageViewerControl.fileSelector1_FileSelected(), IG.Forms.ImageViewerControl.ImageViewerControl_Load(), IG.Forms.FileSelector.IsBrowsable, IG.Forms.FileSelector.IsDragAndDrop, IG.Forms.ImageViewerControl.lblSzeMode, IG.Forms.ImageViewerControl.menuBrowse, IG.Forms.ImageViewerControl.menuBrowse_Click(), IG.Forms.ImageViewerControl.menuClearHistory, IG.Forms.ImageViewerControl.menuClearHistory_Click(), IG.Forms.ImageViewerControl.menuDragDrop, IG.Forms.ImageViewerControl.menuDragDrop_Click(), IG.Forms.ImageViewerControl.menuOptions, IG.Forms.ImageViewerControl.menuShowControls, IG.Forms.ImageViewerControl.pictureBox1, IG.Forms.ImageViewerControl.pictureBox1_DragDrop(), IG.Forms.ImageViewerControl.pictureBox1_DragEnter(), IG.Forms.ImageViewerControl.pnlControls, IG.Forms.ImageViewerControl.pnlOptions, IG.Forms.ImageViewerControl.pnlOuter, IG.Forms.ImageViewerControl.pnlPicture, and IG.Forms.ImageViewerControl.showControlsToolStripMenuItem_Click().
Referenced by IG.Forms.ImageViewerControl.ImageViewerControl().
IsValidHttpUrl() [2/3]
static bool IG.Forms.ImageViewerControl.IsValidHttpUrl (string uriNamme) inline static
Chechks whether the specified URI is a valid HTTP URL.
Parameters
uriNamme URL to be tested.
Returns
True iif the specified string is a valid HTTP URL, false otherwise.
GetImageFromUrl() [2/3]
static Image IG.Forms.ImageViewerControl.GetImageFromUrl (string url) inline static
Gets an image from the specified URL.
Parameters
url URL of the image.
Returns
Image object (of class Image) obtained from the specified URL.
ShowViewedItem() [2/3]
void IG.Forms.ImageViewerControl.ShowViewedItem () inline
Shows / plays the viewed contents.
Can have the role of refresh when IsShownImmediately is true, or is used to actually show the contents after assigning it.
Implements IG.Forms.IFileViewer.
References IG.Forms.ImageViewerControl._viewedFile, IG.Forms.ImageViewerControl.CanViewFiles, IG.Forms.ImageViewerControl.CanViewUrls, IG.Forms.ImageViewerControl.GetImageFromUrl(), IG.Forms.ImageViewerControl.IsValidHttpUrl(), IG.Forms.ImageViewerControl.pictureBox1, IG.Forms.ImageViewerControl.ViewedFile, and IG.Forms.ImageViewerControl.ViewedStream.
Clear() [2/3]
void IG.Forms.ImageViewerControl.Clear () inline
Clears the viewer and eventually releases any resources used.
Implements IG.Forms.IFileViewer.
References IG.Forms.ImageViewerControl.pictureBox1, IG.Forms.ImageViewerControl.ViewedFile, and IG.Forms.ImageViewerControl.ViewedStream.
IsEligibleForViewing() [3/6]
bool IG.Forms.ImageViewerControl.IsEligibleForViewing (string fileLocation) inline
Rerurns a flag indicating whether the file (or web resource) at the specified location is eligible for vieiwnig in the current viewer or not.
Parameters
fileLocation Path to the file on a file system, or file URL.
Returns
True if the file can be viewed in the current viewer, false otherwise.
Implements IG.Forms.IFileViewer.
References IG.Forms.ImageViewerControl.CanViewFiles, IG.Forms.ImageViewerControl.CanViewUrls, IG.Forms.ImageViewerControl.GetImageFromUrl(), and IG.Forms.ImageViewerControl.IsValidHttpUrl().
IsEligibleForViewing() [4/6]
bool IG.Forms.ImageViewerControl.IsEligibleForViewing (Stream stream) inline
Returnns a flag indicating whether the specified stream is eligible for vieiwnig or not.
Parameters
stream Path to the file on a file system, or file URL.
Returns
True if the stream can be viewed in the current viewer, false otherwise.
Implements IG.Forms.IFileViewer.
UpdateControlsVisible() [2/3]
void IG.Forms.ImageViewerControl.UpdateControlsVisible () inline protected
Updates dependencies on IsControlsVisible.
References IG.Forms.ImageViewerControl.IsControlsVisible, IG.Forms.ImageViewerControl.menuShowControls, and IG.Forms.ImageViewerControl.pnlControls.
BrowseFile() [2/3]
void IG.Forms.ImageViewerControl.BrowseFile () inline
Opens a browser to select the file shown.
Available only when IsBrowsable property is true.
Implements IG.Forms.IFileViewer.
References IG.Forms.FileSelector.BrowseFile(), IG.Forms.ImageViewerControl.fileSelector1, and IG.Forms.ImageViewerControl.IsBrowsable.
UpdateBrowsable() [2/3]
void IG.Forms.ImageViewerControl.UpdateBrowsable () inline protected
Updates dependencies on IsBrowsable.
References IG.Forms.ImageViewerControl.fileSelector1, IG.Forms.ImageViewerControl.IsBrowsable, IG.Forms.FileSelector.IsBrowsable, and IG.Forms.ImageViewerControl.menuBrowse.
UpdateDragAndDrop() [2/3]
void IG.Forms.ImageViewerControl.UpdateDragAndDrop () inline protected
Updates dependencies on IsDragAndDrop.
References IG.Forms.ImageViewerControl.fileSelector1, IG.Forms.ImageViewerControl.IsDragAndDrop, IG.Forms.FileSelector.IsDragAndDrop, and IG.Forms.ImageViewerControl.menuDragDrop.
fileSelector1_FileSelected() [2/3]
void IG.Forms.ImageViewerControl.fileSelector1_FileSelected (object sender, EventArgs e) inline private
Triggered when file is selected by the embedded file selector control.
References IG.Forms.FileSelector.FilePath, IG.Forms.ImageViewerControl.fileSelector1, and IG.Forms.ImageViewerControl.ViewedFile.
pictureBox1_DragDrop() [2/3]
void IG.Forms.ImageViewerControl.pictureBox1_DragDrop (object sender, DragEventArgs e) inline private
References IG.Forms.ImageViewerControl.IsDragAndDrop, and IG.Forms.ImageViewerControl.ViewedFile.
pictureBox1_DragEnter() [2/3]
void IG.Forms.ImageViewerControl.pictureBox1_DragEnter (object sender, DragEventArgs e) inline private
References IG.Forms.ImageViewerControl.IsDragAndDrop.
comboSizeMode_SelectedIndexChanged() [2/3]
void IG.Forms.ImageViewerControl.comboSizeMode_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Forms.ImageViewerControl.comboSizeMode, and IG.Forms.ImageViewerControl.SizeMode.
menuShowControls_Click() [2/3]
void IG.Forms.ImageViewerControl.menuShowControls_Click (object sender, EventArgs e) inline private
References IG.Forms.ImageViewerControl.IsControlsVisible.
menuClearHistory_Click() [2/3]
void IG.Forms.ImageViewerControl.menuClearHistory_Click (object sender, EventArgs e) inline private
References IG.Forms.FileSelector.ClearHistory(), and IG.Forms.ImageViewerControl.fileSelector1.
comboSizeMode_Click() [2/3]
void IG.Forms.ImageViewerControl.comboSizeMode_Click (object sender, EventArgs e) inline private
References IG.Forms.ImageViewerControl.comboSizeMode.
menuDragDrop_Click() [2/3]
void IG.Forms.ImageViewerControl.menuDragDrop_Click (object sender, EventArgs e) inline private
References IG.Forms.ImageViewerControl.IsDragAndDrop.
menuBrowse_Click() [2/3]
void IG.Forms.ImageViewerControl.menuBrowse_Click (object sender, EventArgs e) inline private
References IG.Forms.ImageViewerControl.IsBrowsable.
showControlsToolStripMenuItem_Click() [2/3]
void IG.Forms.ImageViewerControl.showControlsToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.ImageViewerControl.IsControlsVisible.
ImageViewerControl_Load() [2/3]
void IG.Forms.ImageViewerControl.ImageViewerControl_Load (object sender, EventArgs e) inline private
Handles the load event of the current control.
References IG.Forms.ImageViewerControl.pictureBox1, IG.Forms.ImageViewerControl.SizeMode, IG.Forms.ImageViewerControl.UpdateBrowsable(), IG.Forms.ImageViewerControl.UpdateControlsVisible(), and IG.Forms.ImageViewerControl.UpdateDragAndDrop().
Dispose() [2/3]
override void IG.Forms.ImageViewerControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ImageViewerControl.components.
InitializeComponent() [2/3]
void IG.Forms.ImageViewerControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.ImageViewerControl.comboSizeMode, IG.Forms.ImageViewerControl.comboSizeMode_Click(), IG.Forms.ImageViewerControl.comboSizeMode_SelectedIndexChanged(), IG.Forms.ImageViewerControl.components, IG.Forms.ImageViewerControl.contextMenuMain, IG.Forms.FileSelector.FilePath, IG.Forms.FileSelector.FileSelected, IG.Forms.ImageViewerControl.fileSelector1, IG.Forms.ImageViewerControl.fileSelector1_FileSelected(), IG.Forms.ImageViewerControl.ImageViewerControl_Load(), IG.Forms.FileSelector.IsBrowsable, IG.Forms.FileSelector.IsDragAndDrop, IG.Forms.ImageViewerControl.lblSzeMode, IG.Forms.ImageViewerControl.menuBrowse, IG.Forms.ImageViewerControl.menuBrowse_Click(), IG.Forms.ImageViewerControl.menuClearHistory, IG.Forms.ImageViewerControl.menuClearHistory_Click(), IG.Forms.ImageViewerControl.menuDragDrop, IG.Forms.ImageViewerControl.menuDragDrop_Click(), IG.Forms.ImageViewerControl.menuOptions, IG.Forms.ImageViewerControl.menuShowControls, IG.Forms.ImageViewerControl.pictureBox1, IG.Forms.ImageViewerControl.pictureBox1_DragDrop(), IG.Forms.ImageViewerControl.pictureBox1_DragEnter(), IG.Forms.ImageViewerControl.pnlControls, IG.Forms.ImageViewerControl.pnlOptions, IG.Forms.ImageViewerControl.pnlOuter, IG.Forms.ImageViewerControl.pnlPicture, and IG.Forms.ImageViewerControl.showControlsToolStripMenuItem_Click().
IsValidHttpUrl() [3/3]
static bool IG.Forms.ImageViewerControl.IsValidHttpUrl (string uriNamme) inline static
Chechks whether the specified URI is a valid HTTP URL.
Parameters
uriNamme URL to be tested.
Returns
True iif the specified string is a valid HTTP URL, false otherwise.
GetImageFromUrl() [3/3]
static Image IG.Forms.ImageViewerControl.GetImageFromUrl (string url) inline static
Gets an image from the specified URL.
Parameters
url URL of the image.
Returns
Image object (of class Image) obtained from the specified URL.
ShowViewedItem() [3/3]
void IG.Forms.ImageViewerControl.ShowViewedItem () inline
Shows / plays the viewed contents.
Can have the role of refresh when IsShownImmediately is true, or is used to actually show the contents after assigning it.
Implements IG.Forms.IFileViewer.
References IG.Forms.ImageViewerControl._viewedFile, IG.Forms.ImageViewerControl.CanViewFiles, IG.Forms.ImageViewerControl.CanViewUrls, IG.Forms.ImageViewerControl.GetImageFromUrl(), IG.Forms.ImageViewerControl.IsValidHttpUrl(), IG.Forms.ImageViewerControl.pictureBox1, IG.Forms.ImageViewerControl.ViewedFile, and IG.Forms.ImageViewerControl.ViewedStream.
Clear() [3/3]
void IG.Forms.ImageViewerControl.Clear () inline
Clears the viewer and eventually releases any resources used.
Implements IG.Forms.IFileViewer.
References IG.Forms.ImageViewerControl.pictureBox1, IG.Forms.ImageViewerControl.ViewedFile, and IG.Forms.ImageViewerControl.ViewedStream.
IsEligibleForViewing() [5/6]
bool IG.Forms.ImageViewerControl.IsEligibleForViewing (string fileLocation) inline
Rerurns a flag indicating whether the file (or web resource) at the specified location is eligible for vieiwnig in the current viewer or not.
Parameters
fileLocation Path to the file on a file system, or file URL.
Returns
True if the file can be viewed in the current viewer, false otherwise.
Implements IG.Forms.IFileViewer.
References IG.Forms.ImageViewerControl.CanViewFiles, IG.Forms.ImageViewerControl.CanViewUrls, IG.Forms.ImageViewerControl.GetImageFromUrl(), and IG.Forms.ImageViewerControl.IsValidHttpUrl().
IsEligibleForViewing() [6/6]
bool IG.Forms.ImageViewerControl.IsEligibleForViewing (Stream stream) inline
Returnns a flag indicating whether the specified stream is eligible for vieiwnig or not.
Parameters
stream Path to the file on a file system, or file URL.
Returns
True if the stream can be viewed in the current viewer, false otherwise.
Implements IG.Forms.IFileViewer.
UpdateControlsVisible() [3/3]
void IG.Forms.ImageViewerControl.UpdateControlsVisible () inline protected
Updates dependencies on IsControlsVisible.
References IG.Forms.ImageViewerControl.IsControlsVisible, IG.Forms.ImageViewerControl.menuShowControls, and IG.Forms.ImageViewerControl.pnlControls.
BrowseFile() [3/3]
void IG.Forms.ImageViewerControl.BrowseFile () inline
Opens a browser to select the file shown.
Available only when IsBrowsable property is true.
Implements IG.Forms.IFileViewer.
References IG.Forms.FileSelector.BrowseFile(), IG.Forms.ImageViewerControl.fileSelector1, and IG.Forms.ImageViewerControl.IsBrowsable.
UpdateBrowsable() [3/3]
void IG.Forms.ImageViewerControl.UpdateBrowsable () inline protected
Updates dependencies on IsBrowsable.
References IG.Forms.ImageViewerControl.fileSelector1, IG.Forms.ImageViewerControl.IsBrowsable, IG.Forms.FileSelector.IsBrowsable, and IG.Forms.ImageViewerControl.menuBrowse.
UpdateDragAndDrop() [3/3]
void IG.Forms.ImageViewerControl.UpdateDragAndDrop () inline protected
Updates dependencies on IsDragAndDrop.
References IG.Forms.ImageViewerControl.fileSelector1, IG.Forms.ImageViewerControl.IsDragAndDrop, IG.Forms.FileSelector.IsDragAndDrop, and IG.Forms.ImageViewerControl.menuDragDrop.
fileSelector1_FileSelected() [3/3]
void IG.Forms.ImageViewerControl.fileSelector1_FileSelected (object sender, EventArgs e) inline private
Triggered when file is selected by the embedded file selector control.
References IG.Forms.FileSelector.FilePath, IG.Forms.ImageViewerControl.fileSelector1, and IG.Forms.ImageViewerControl.ViewedFile.
pictureBox1_DragDrop() [3/3]
void IG.Forms.ImageViewerControl.pictureBox1_DragDrop (object sender, DragEventArgs e) inline private
References IG.Forms.ImageViewerControl.IsDragAndDrop, and IG.Forms.ImageViewerControl.ViewedFile.
pictureBox1_DragEnter() [3/3]
void IG.Forms.ImageViewerControl.pictureBox1_DragEnter (object sender, DragEventArgs e) inline private
References IG.Forms.ImageViewerControl.IsDragAndDrop.
comboSizeMode_SelectedIndexChanged() [3/3]
void IG.Forms.ImageViewerControl.comboSizeMode_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Forms.ImageViewerControl.comboSizeMode, and IG.Forms.ImageViewerControl.SizeMode.
menuShowControls_Click() [3/3]
void IG.Forms.ImageViewerControl.menuShowControls_Click (object sender, EventArgs e) inline private
References IG.Forms.ImageViewerControl.IsControlsVisible.
menuClearHistory_Click() [3/3]
void IG.Forms.ImageViewerControl.menuClearHistory_Click (object sender, EventArgs e) inline private
References IG.Forms.FileSelector.ClearHistory(), and IG.Forms.ImageViewerControl.fileSelector1.
comboSizeMode_Click() [3/3]
void IG.Forms.ImageViewerControl.comboSizeMode_Click (object sender, EventArgs e) inline private
References IG.Forms.ImageViewerControl.comboSizeMode.
menuDragDrop_Click() [3/3]
void IG.Forms.ImageViewerControl.menuDragDrop_Click (object sender, EventArgs e) inline private
References IG.Forms.ImageViewerControl.IsDragAndDrop.
menuBrowse_Click() [3/3]
void IG.Forms.ImageViewerControl.menuBrowse_Click (object sender, EventArgs e) inline private
References IG.Forms.ImageViewerControl.IsBrowsable.
showControlsToolStripMenuItem_Click() [3/3]
void IG.Forms.ImageViewerControl.showControlsToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.ImageViewerControl.IsControlsVisible.
ImageViewerControl_Load() [3/3]
void IG.Forms.ImageViewerControl.ImageViewerControl_Load (object sender, EventArgs e) inline private
Handles the load event of the current control.
References IG.Forms.ImageViewerControl.pictureBox1, IG.Forms.ImageViewerControl.SizeMode, IG.Forms.ImageViewerControl.UpdateBrowsable(), IG.Forms.ImageViewerControl.UpdateControlsVisible(), and IG.Forms.ImageViewerControl.UpdateDragAndDrop().
Dispose() [3/3]
override void IG.Forms.ImageViewerControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ImageViewerControl.components.
InitializeComponent() [3/3]
void IG.Forms.ImageViewerControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.ImageViewerControl.comboSizeMode, IG.Forms.ImageViewerControl.comboSizeMode_Click(), IG.Forms.ImageViewerControl.comboSizeMode_SelectedIndexChanged(), IG.Forms.ImageViewerControl.components, IG.Forms.ImageViewerControl.contextMenuMain, IG.Forms.FileSelector.FilePath, IG.Forms.FileSelector.FileSelected, IG.Forms.ImageViewerControl.fileSelector1, IG.Forms.ImageViewerControl.fileSelector1_FileSelected(), IG.Forms.ImageViewerControl.ImageViewerControl_Load(), IG.Forms.FileSelector.IsBrowsable, IG.Forms.FileSelector.IsDragAndDrop, IG.Forms.ImageViewerControl.lblSzeMode, IG.Forms.ImageViewerControl.menuBrowse, IG.Forms.ImageViewerControl.menuBrowse_Click(), IG.Forms.ImageViewerControl.menuClearHistory, IG.Forms.ImageViewerControl.menuClearHistory_Click(), IG.Forms.ImageViewerControl.menuDragDrop, IG.Forms.ImageViewerControl.menuDragDrop_Click(), IG.Forms.ImageViewerControl.menuOptions, IG.Forms.ImageViewerControl.menuShowControls, IG.Forms.ImageViewerControl.pictureBox1, IG.Forms.ImageViewerControl.pictureBox1_DragDrop(), IG.Forms.ImageViewerControl.pictureBox1_DragEnter(), IG.Forms.ImageViewerControl.pnlControls, IG.Forms.ImageViewerControl.pnlOptions, IG.Forms.ImageViewerControl.pnlOuter, IG.Forms.ImageViewerControl.pnlPicture, and IG.Forms.ImageViewerControl.showControlsToolStripMenuItem_Click().
Member Data Documentation
_availableSizeModes
List< PictureBoxSizeMode > IG.Forms.ImageViewerControl._availableSizeModes = Util.GetEnumValues<PictureBoxSizeMode>() protected
Referenced by IG.Forms.ImageViewerControl.ImageViewerControl().
_sizeMode
PictureBoxSizeMode IG.Forms.ImageViewerControl._sizeMode = PictureBoxSizeMode.CenterImage private
_viewedFile
string IG.Forms.ImageViewerControl._viewedFile protected
Referenced by IG.Forms.ImageViewerControl.ShowViewedItem().
_closeStreamAfterUse
bool IG.Forms.ImageViewerControl._closeStreamAfterUse = false private
_stream
Stream IG.Forms.ImageViewerControl._stream protected
_isShownImmediately
bool IG.Forms.ImageViewerControl._isShownImmediately = true protected
_canViewFiles
bool IG.Forms.ImageViewerControl._canViewFiles = true protected
_canViewUrls
bool IG.Forms.ImageViewerControl._canViewUrls = true protected
_canViewStreams
bool IG.Forms.ImageViewerControl._canViewStreams = true protected
Whether the current viewer can read streams.
_isControlsVisible
bool IG.Forms.ImageViewerControl._isControlsVisible = true private
_isBrowsable
bool IG.Forms.ImageViewerControl._isBrowsable = true protected
_isDragAndDrop
bool IG.Forms.ImageViewerControl._isDragAndDrop = true protected
components
System ComponentModel IContainer IG.Forms.ImageViewerControl.components = null private
Required designer variable.
Referenced by IG.Forms.ImageViewerControl.Dispose(), and IG.Forms.ImageViewerControl.InitializeComponent().
pictureBox1
System Windows Forms PictureBox IG.Forms.ImageViewerControl.pictureBox1 private
Referenced by IG.Forms.ImageViewerControl.Clear(), IG.Forms.ImageViewerControl.ImageViewerControl_Load(), IG.Forms.ImageViewerControl.InitializeComponent(), and IG.Forms.ImageViewerControl.ShowViewedItem().
fileSelector1
IG Forms FileSelector IG.Forms.ImageViewerControl.fileSelector1 private
Referenced by IG.Forms.ImageViewerControl.BrowseFile(), IG.Forms.ImageViewerControl.fileSelector1_FileSelected(), IG.Forms.ImageViewerControl.InitializeComponent(), IG.Forms.ImageViewerControl.menuClearHistory_Click(), IG.Forms.ImageViewerControl.UpdateBrowsable(), and IG.Forms.ImageViewerControl.UpdateDragAndDrop().
pnlOptions
System Windows Forms Panel IG.Forms.ImageViewerControl.pnlOptions private
Referenced by IG.Forms.ImageViewerControl.InitializeComponent().
lblSzeMode
System Windows Forms Label IG.Forms.ImageViewerControl.lblSzeMode private
Referenced by IG.Forms.ImageViewerControl.InitializeComponent().
comboSizeMode
System Windows Forms ComboBox IG.Forms.ImageViewerControl.comboSizeMode private
Referenced by IG.Forms.ImageViewerControl.comboSizeMode_Click(), IG.Forms.ImageViewerControl.comboSizeMode_SelectedIndexChanged(), IG.Forms.ImageViewerControl.ImageViewerControl(), and IG.Forms.ImageViewerControl.InitializeComponent().
pnlPicture
System Windows Forms Panel IG.Forms.ImageViewerControl.pnlPicture private
Referenced by IG.Forms.ImageViewerControl.InitializeComponent().
contextMenuMain
System Windows Forms ContextMenuStrip IG.Forms.ImageViewerControl.contextMenuMain private
Referenced by IG.Forms.ImageViewerControl.InitializeComponent().
pnlOuter
System Windows Forms Panel IG.Forms.ImageViewerControl.pnlOuter private
Referenced by IG.Forms.ImageViewerControl.InitializeComponent().
pnlControls
System Windows Forms Panel IG.Forms.ImageViewerControl.pnlControls private
Referenced by IG.Forms.ImageViewerControl.InitializeComponent(), and IG.Forms.ImageViewerControl.UpdateControlsVisible().
menuClearHistory
System Windows Forms ToolStripMenuItem IG.Forms.ImageViewerControl.menuClearHistory private
Referenced by IG.Forms.ImageViewerControl.InitializeComponent().
menuOptions
System Windows Forms ToolStripMenuItem IG.Forms.ImageViewerControl.menuOptions private
Referenced by IG.Forms.ImageViewerControl.InitializeComponent().
menuDragDrop
System Windows Forms ToolStripMenuItem IG.Forms.ImageViewerControl.menuDragDrop private
Referenced by IG.Forms.ImageViewerControl.InitializeComponent(), and IG.Forms.ImageViewerControl.UpdateDragAndDrop().
menuBrowse
System Windows Forms ToolStripMenuItem IG.Forms.ImageViewerControl.menuBrowse private
Referenced by IG.Forms.ImageViewerControl.InitializeComponent(), and IG.Forms.ImageViewerControl.UpdateBrowsable().
menuShowControls
System Windows Forms ToolStripMenuItem IG.Forms.ImageViewerControl.menuShowControls private
Referenced by IG.Forms.ImageViewerControl.InitializeComponent(), and IG.Forms.ImageViewerControl.UpdateControlsVisible().
Property Documentation
SizeMode
PictureBoxSizeMode IG.Forms.ImageViewerControl.SizeMode get set
Enumeraton of type PictureBoxSizeMode that specifies how the image is sized and positioned witin the PictureBox control.
Referenced by IG.Forms.ImageViewerControl.comboSizeMode_SelectedIndexChanged(), IG.Forms.ImageViewerControl.ImageViewerControl(), IG.Forms.ImageViewerControl.ImageViewerControl_Load(), and IG.Forms.ResourceViewerControl.InitializeComponent().
ViewedFile
string IG.Forms.ImageViewerControl.ViewedFile get set
Gets or sets path to the file or URL of the file that is currently being viewed.
Whether it is actually shown depends on the IsShownImmediately flag).
Referenced by IG.Forms.ImageViewerControl.Clear(), IG.Forms.ImageViewerControl.fileSelector1_FileSelected(), IG.Forms.ResourceViewerControl.InitializeComponent(), IG.Forms.ImageViewerControl.pictureBox1_DragDrop(), and IG.Forms.ImageViewerControl.ShowViewedItem().
ViewedStream
Stream IG.Forms.ImageViewerControl.ViewedStream get set
Gets or sets the stream containing the file that is currently being viewed.
Whether it is actually shown depends on the IsShownImmediately flag).
Referenced by IG.Forms.ImageViewerControl.Clear(), IG.Forms.ResourceViewerControl.InitializeComponent(), and IG.Forms.ImageViewerControl.ShowViewedItem().
IsShownImmediately
bool IG.Forms.ImageViewerControl.IsShownImmediately get set
Flag that specifies whether content is shown immediately after the viewed object is set.
If set to true and the viewer does not at all have such capability, this should NOT throw an exception (thus, user should check success by verifying if flag changed).
Referenced by IG.Forms.ResourceViewerControl.InitializeComponent().
CanViewFiles
bool IG.Forms.ImageViewerControl.CanViewFiles get set
Whether the current viewer can view files from the file system.
Referenced by IG.Forms.ResourceViewerControl.InitializeComponent(), IG.Forms.ImageViewerControl.IsEligibleForViewing(), and IG.Forms.ImageViewerControl.ShowViewedItem().
CanViewUrls
bool IG.Forms.ImageViewerControl.CanViewUrls get set
Whether the current viewer can view web resources (files on the internet).
Referenced by IG.Forms.ResourceViewerControl.InitializeComponent(), IG.Forms.ImageViewerControl.IsEligibleForViewing(), and IG.Forms.ImageViewerControl.ShowViewedItem().
CanViewStreams
bool IG.Forms.ImageViewerControl.CanViewStreams get set
Referenced by IG.Forms.ResourceViewerControl.InitializeComponent().
IsControlsVisible
bool IG.Forms.ImageViewerControl.IsControlsVisible get set
Gets / sets a flag that specified whether the viewer's controls are visible or not.
Setting should have immediate effect and make controls visible / invisible.
This is important because viewers must be able to be used embedded in other controls, where all behavior is handled by those controls and viewer just provides the viewing area.
Referenced by IG.Forms.ResourceViewerControl.InitializeComponent(), IG.Forms.ImageViewerControl.menuShowControls_Click(), IG.Forms.ImageViewerControl.showControlsToolStripMenuItem_Click(), and IG.Forms.ImageViewerControl.UpdateControlsVisible().
IsBrowsable
bool IG.Forms.ImageViewerControl.IsBrowsable get set
Gets or sets the flag specifying whether one can browse for the file to be opened (e.g. by using the file selection dialog).
If the viewer does not at all have browser capability then setting to true should not throw an exception (therefore, the user should verify by getter if setting actually worked).
Setter can be used to disable drag & drop (e.g. for security, or when used as embedded control and drag & drop would be disturbing). If the viewer does not at all have drag & drop capability, setting this flag to true should NOT throw an exception (thus, user should check if it was successful).
Referenced by IG.Forms.ImageViewerControl.BrowseFile(), IG.Forms.ResourceViewerControl.InitializeComponent(), IG.Forms.ImageViewerControl.menuBrowse_Click(), and IG.Forms.ImageViewerControl.UpdateBrowsable().
IsDragAndDrop
bool IG.Forms.ImageViewerControl.IsDragAndDrop get set
Whether the viewer provides drag & drop capability.
If the viewer does not at all have browser capability then setting to true should not throw an exception (therefore, the user should verify by getter if setting actually worked).
Setter can be used to disable drag & drop (e.g. for security, or when used as embedded control and drag & drop would be disturbing). If the viewer does not at all have drag & drop capability, setting this flag to true should NOT throw an exception (thus, user should check if it was successful).
Referenced by IG.Forms.ResourceViewerControl.InitializeComponent(), IG.Forms.ImageViewerControl.menuDragDrop_Click(), IG.Forms.ImageViewerControl.pictureBox1_DragDrop(), IG.Forms.ImageViewerControl.pictureBox1_DragEnter(), and IG.Forms.ImageViewerControl.UpdateDragAndDrop().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/Viewers/ImageViewerControl.cs
iglib/igforms/Utilities/Viewers/ImageViewerControl.Designer.cs