Doc: IGLib EXTENDED: NUnit.Framework.Constraints.MsgUtilTests Class Reference
NUnit.Framework.Constraints.MsgUtilTests Class Reference
Summary description for MsgUtilTests.
Static Public Member Functions
static void FormatValue_IntegerIsWrittenAsIs ()
static void FormatValue_StringIsWrittenWithQuotes ()
static void FormatValue_FloatIsWrittenWithTrailingF ()
static void FormatValue_FloatIsWrittenToNineDigits ()
static void FormatValue_DoubleIsWrittenWithTrailingD ()
static void FormatValue_DoubleIsWrittenToSeventeenDigits ()
static void FormatValue_DecimalIsWrittenWithTrailingM ()
static void FormatValue_DecimalIsWrittenToTwentyNineDigits ()
static void FormatValue_DateTimeTest ()
static void EscapeControlCharsTest (string input, string expected)
static void EscapeNullCharInString ()
static void TestClipString (string input, int max, int start, string result)
static void ClipExpectedAndActual_StringsFitInLine ()
static void ClipExpectedAndActual_StringTailsFitInLine ()
static void ClipExpectedAndActual_StringsDoNotFitInLine ()
Static Private Attributes
const string s52 = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
Detailed Description
Summary description for MsgUtilTests.
Member Function Documentation
FormatValue_IntegerIsWrittenAsIs()
static void NUnit.Framework.Constraints.MsgUtilTests.FormatValue_IntegerIsWrittenAsIs () inline static
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
FormatValue_StringIsWrittenWithQuotes()
static void NUnit.Framework.Constraints.MsgUtilTests.FormatValue_StringIsWrittenWithQuotes () inline static
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
FormatValue_FloatIsWrittenWithTrailingF()
static void NUnit.Framework.Constraints.MsgUtilTests.FormatValue_FloatIsWrittenWithTrailingF () inline static
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
FormatValue_FloatIsWrittenToNineDigits()
static void NUnit.Framework.Constraints.MsgUtilTests.FormatValue_FloatIsWrittenToNineDigits () inline static
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
FormatValue_DoubleIsWrittenWithTrailingD()
static void NUnit.Framework.Constraints.MsgUtilTests.FormatValue_DoubleIsWrittenWithTrailingD () inline static
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
FormatValue_DoubleIsWrittenToSeventeenDigits()
static void NUnit.Framework.Constraints.MsgUtilTests.FormatValue_DoubleIsWrittenToSeventeenDigits () inline static
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
FormatValue_DecimalIsWrittenWithTrailingM()
static void NUnit.Framework.Constraints.MsgUtilTests.FormatValue_DecimalIsWrittenWithTrailingM () inline static
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
FormatValue_DecimalIsWrittenToTwentyNineDigits()
static void NUnit.Framework.Constraints.MsgUtilTests.FormatValue_DecimalIsWrittenToTwentyNineDigits () inline static
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
FormatValue_DateTimeTest()
static void NUnit.Framework.Constraints.MsgUtilTests.FormatValue_DateTimeTest () inline static
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
EscapeControlCharsTest()
static void NUnit.Framework.Constraints.MsgUtilTests.EscapeControlCharsTest (string input, string expected) inline static
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
EscapeNullCharInString()
static void NUnit.Framework.Constraints.MsgUtilTests.EscapeNullCharInString () inline static
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
TestClipString()
static void NUnit.Framework.Constraints.MsgUtilTests.TestClipString (string input, int max, int start, string result) inline static
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
ClipExpectedAndActual_StringsFitInLine()
static void NUnit.Framework.Constraints.MsgUtilTests.ClipExpectedAndActual_StringsFitInLine () inline static
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Constraints.MsgUtilTests.s52, and NUnit.Framework.Assert.That().
ClipExpectedAndActual_StringTailsFitInLine()
static void NUnit.Framework.Constraints.MsgUtilTests.ClipExpectedAndActual_StringTailsFitInLine () inline static
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Constraints.MsgUtilTests.s52, and NUnit.Framework.Assert.That().
ClipExpectedAndActual_StringsDoNotFitInLine()
static void NUnit.Framework.Constraints.MsgUtilTests.ClipExpectedAndActual_StringsDoNotFitInLine () inline static
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Constraints.MsgUtilTests.s52, and NUnit.Framework.Assert.That().
Member Data Documentation
s52
const string NUnit.Framework.Constraints.MsgUtilTests.s52 = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" static private
Referenced by NUnit.Framework.Constraints.MsgUtilTests.ClipExpectedAndActual_StringsDoNotFitInLine(), NUnit.Framework.Constraints.MsgUtilTests.ClipExpectedAndActual_StringsFitInLine(), and NUnit.Framework.Constraints.MsgUtilTests.ClipExpectedAndActual_StringTailsFitInLine().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/MsgUtilTests.cs