Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLARFG Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLARFG Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLARFG (DLAMCH dlamch, DLAPY2 dlapy2, DNRM2 dnrm2, DSCAL dscal)
DLARFG ()
void Run (int N, ref double ALPHA, ref double[] X, int offset_x, int INCX, ref double TAU)
Private Attributes
DLAMCH _dlamch
DLAPY2 _dlapy2
DNRM2 _dnrm2
DSCAL _dscal
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLARFG generates a real elementary reflector H of order n, such that
H * (alpha) = (beta), H' * H = I. (x) (0)
where alpha and beta are scalars, and x is an (n-1)-element real vector. H is represented in the form
H = I - tau * (1) * (1 v') , (v)
where tau is a real scalar and v is a real (n-1)-element vector.
If the elements of x are all zero, then tau = 0 and H is taken to be the unit matrix.
Otherwise 1 .LE. tau .LE. 2.
/summary>
Constructor & Destructor Documentation
DLARFG() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLARFG.DLARFG (DLAMCH dlamch, DLAPY2 dlapy2, DNRM2 dnrm2, DSCAL dscal) inline
DLARFG() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLARFG.DLARFG () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run (int N, ref double ALPHA, ref double[] X, int offset_x, int INCX, ref double TAU) inline
Purpose
DLARFG generates a real elementary reflector H of order n, such that
H * (alpha) = (beta), H' * H = I. (x) (0)
where alpha and beta are scalars, and x is an (n-1)-element real vector. H is represented in the form
H = I - tau * (1) * (1 v') , (v)
where tau is a real scalar and v is a real (n-1)-element vector.
If the elements of x are all zero, then tau = 0 and H is taken to be the unit matrix.
Otherwise 1 .LE. tau .LE. 2.
/summary>
Parameters
N (input) INTEGER The order of the elementary reflector. /param>
Parameters
ALPHA (input/output) DOUBLE PRECISION On entry, the value alpha. On exit, it is overwritten with the value beta. /param>
Parameters
X (input/output) DOUBLE PRECISION array, dimension (1+(N-2)*abs(INCX)) On entry, the vector x. On exit, it is overwritten with the vector v. /param>
Parameters
INCX (input) INTEGER The increment between elements of X. INCX .GT. 0. /param>
Parameters
TAU (output) DOUBLE PRECISION The value tau. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLARFG.ONE, DotNumerics.LinearAlgebra.CSLapack.DNRM2.Run(), DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAPY2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.FortranLibrary.FortranLib.Sign(), and DotNumerics.LinearAlgebra.CSLapack.DLARFG.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGELQ2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGERQ2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLATRZ.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAPLL.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEHD2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQPF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQP2.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYTD2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBD2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAHR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAEXC.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQPS.Run(), DotNumerics.LinearAlgebra.CSLapack.DLATRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLABRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAHQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR5.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR2.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAQR3.Run().
Member Data Documentation
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLARFG._dlamch private
_dlapy2
DLAPY2 DotNumerics.LinearAlgebra.CSLapack.DLARFG._dlapy2 private
_dnrm2
DNRM2 DotNumerics.LinearAlgebra.CSLapack.DLARFG._dnrm2 private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DLARFG._dscal private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLARFG.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLARFG.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlarfg.cs