Doc: IGLib EXTENDED: NUnit.Framework.Constraints.NumericsTests Class Reference
NUnit.Framework.Constraints.NumericsTests Class Reference
Public Member Functions
void SetUp ()
void CanMatchWithoutToleranceMode (object value)
void CanMatchDecimalWithoutToleranceMode ()
void CanMatchIntegralsWithPercentage (object value)
void CanMatchDecimalWithPercentage ()
void FailsOnIntegralsOutsideOfPercentage (object value)
void FailsOnDecimalBelowPercentage ()
void FailsOnDecimalAbovePercentage ()
Private Attributes
Tolerance tenPercent
Tolerance zeroTolerance
Member Function Documentation
SetUp()
void NUnit.Framework.Constraints.NumericsTests.SetUp () inline
References NUnit.Framework.Constraints.Tolerance.Exact, NUnit.Framework.Constraints.Tolerance.Percent, NUnit.Framework.Constraints.NumericsTests.tenPercent, and NUnit.Framework.Constraints.NumericsTests.zeroTolerance.
CanMatchWithoutToleranceMode()
void NUnit.Framework.Constraints.NumericsTests.CanMatchWithoutToleranceMode (object value) inline
References NUnit.Framework.Constraints.Numerics.AreEqual(), NUnit.Framework.Assert.IsTrue(), and NUnit.Framework.Constraints.NumericsTests.zeroTolerance.
CanMatchDecimalWithoutToleranceMode()
void NUnit.Framework.Constraints.NumericsTests.CanMatchDecimalWithoutToleranceMode () inline
References NUnit.Framework.Constraints.Numerics.AreEqual(), NUnit.Framework.Assert.IsTrue(), and NUnit.Framework.Constraints.NumericsTests.zeroTolerance.
CanMatchIntegralsWithPercentage()
void NUnit.Framework.Constraints.NumericsTests.CanMatchIntegralsWithPercentage (object value) inline
References NUnit.Framework.Constraints.Numerics.AreEqual(), NUnit.Framework.Assert.IsTrue(), and NUnit.Framework.Constraints.NumericsTests.tenPercent.
CanMatchDecimalWithPercentage()
void NUnit.Framework.Constraints.NumericsTests.CanMatchDecimalWithPercentage () inline
References NUnit.Framework.Constraints.Numerics.AreEqual(), NUnit.Framework.Assert.IsTrue(), and NUnit.Framework.Constraints.NumericsTests.tenPercent.
FailsOnIntegralsOutsideOfPercentage()
void NUnit.Framework.Constraints.NumericsTests.FailsOnIntegralsOutsideOfPercentage (object value) inline
References NUnit.Framework.Constraints.Numerics.AreEqual(), NUnit.Framework.Assert.IsTrue(), NUnit.Framework.Constraints.NumericsTests.tenPercent, and NUnit.Framework.Assert.Throws().
FailsOnDecimalBelowPercentage()
void NUnit.Framework.Constraints.NumericsTests.FailsOnDecimalBelowPercentage () inline
References NUnit.Framework.Constraints.Numerics.AreEqual(), NUnit.Framework.Assert.IsTrue(), NUnit.Framework.Constraints.NumericsTests.tenPercent, and NUnit.Framework.Assert.Throws().
FailsOnDecimalAbovePercentage()
void NUnit.Framework.Constraints.NumericsTests.FailsOnDecimalAbovePercentage () inline
References NUnit.Framework.Constraints.Numerics.AreEqual(), NUnit.Framework.Assert.IsTrue(), NUnit.Framework.Constraints.NumericsTests.tenPercent, and NUnit.Framework.Assert.Throws().
Member Data Documentation
tenPercent
Tolerance NUnit.Framework.Constraints.NumericsTests.tenPercent private
Referenced by NUnit.Framework.Constraints.NumericsTests.CanMatchDecimalWithPercentage(), NUnit.Framework.Constraints.NumericsTests.CanMatchIntegralsWithPercentage(), NUnit.Framework.Constraints.NumericsTests.FailsOnDecimalAbovePercentage(), NUnit.Framework.Constraints.NumericsTests.FailsOnDecimalBelowPercentage(), NUnit.Framework.Constraints.NumericsTests.FailsOnIntegralsOutsideOfPercentage(), and NUnit.Framework.Constraints.NumericsTests.SetUp().
zeroTolerance
Tolerance NUnit.Framework.Constraints.NumericsTests.zeroTolerance private
Referenced by NUnit.Framework.Constraints.NumericsTests.CanMatchDecimalWithoutToleranceMode(), NUnit.Framework.Constraints.NumericsTests.CanMatchWithoutToleranceMode(), and NUnit.Framework.Constraints.NumericsTests.SetUp().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/NumericsTest.cs