Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGERQF Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGERQF Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGERQF (DGERQ2 dgerq2, DLARFB dlarfb, DLARFT dlarft, XERBLA xerbla, ILAENV ilaenv)
DGERQF ()
void Run (int M, int N, ref double[] A, int offset_a, int LDA, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
DGERQ2 _dgerq2
DLARFB _dlarfb
DLARFT _dlarft
XERBLA _xerbla
ILAENV _ilaenv
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGERQF computes an RQ factorization of a real M-by-N matrix A: A = R * Q.
/summary>
Constructor & Destructor Documentation
DGERQF() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGERQF.DGERQF (DGERQ2 dgerq2, DLARFB dlarfb, DLARFT dlarft, XERBLA xerbla, ILAENV ilaenv) inline
DGERQF() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGERQF.DGERQF () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGERQF.Run (int M, int N, ref double[] A, int offset_a, int LDA, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DGERQF computes an RQ factorization of a real M-by-N matrix A: A = R * Q.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the M-by-N matrix A. On exit, if m .LE. n, the upper triangle of the subarray A(1:m,n-m+1:n) contains the M-by-M upper triangular matrix R; if m .GE. n, the elements on and above the (m-n)-th subdiagonal contain the M-by-N upper trapezoidal matrix R; the remaining elements, with the array TAU, represent the orthogonal matrix Q as a product of min(m,n) elementary reflectors (see Further Details). /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
TAU (output) DOUBLE PRECISION array, dimension (min(M,N)) The scalar factors of the elementary reflectors (see Further Details). /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. max(1,M). For optimum performance LWORK .GE. M*NB, where NB is the optimal blocksize.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DGERQ2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFT.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLARFB.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGGRQF.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGGQRF.Run().
Member Data Documentation
_dgerq2
DGERQ2 DotNumerics.LinearAlgebra.CSLapack.DGERQF._dgerq2 private
_dlarfb
DLARFB DotNumerics.LinearAlgebra.CSLapack.DGERQF._dlarfb private
_dlarft
DLARFT DotNumerics.LinearAlgebra.CSLapack.DGERQF._dlarft private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGERQF._xerbla private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DGERQF._ilaenv private
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgerqf.cs