Doc: IGLib EXTENDED: IG.Forms.InputOutputDataDefinitionForm Class Reference
IG.Forms.InputOutputDataDefinitionForm Class Reference
Public Member Functions
InputOutputDataDefinitionForm ()
InputOutputDataDefinitionForm ()
InputOutputDataDefinitionForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
InputOutputDataDefinitionControl MainControl [get]
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
IG.Forms.InputOutputDataDefinitionControl inputOutputDataDefinitionCntrol1
Constructor & Destructor Documentation
InputOutputDataDefinitionForm() [1/3]
IG.Forms.InputOutputDataDefinitionForm.InputOutputDataDefinitionForm () inline
References IG.Forms.InputOutputDataDefinitionForm.InitializeComponent(), IG.Forms.InputOutputDataDefinitionControl.InputDataControl, IG.Forms.InpuOrOutputtDataDefinitionControl.IsInputData, IG.Forms.InputOutputDataDefinitionForm.MainControl, and IG.Forms.InputOutputDataDefinitionControl.OutputDataControl.
InputOutputDataDefinitionForm() [2/3]
IG.Forms.InputOutputDataDefinitionForm.InputOutputDataDefinitionForm () inline
References IG.Forms.InputOutputDataDefinitionForm.InitializeComponent(), IG.Forms.InputOutputDataDefinitionControl.InputDataControl, IG.Forms.InpuOrOutputtDataDefinitionControl.IsInputData, IG.Forms.InputOutputDataDefinitionForm.MainControl, and IG.Forms.InputOutputDataDefinitionControl.OutputDataControl.
InputOutputDataDefinitionForm() [3/3]
IG.Forms.InputOutputDataDefinitionForm.InputOutputDataDefinitionForm () inline
References IG.Forms.InputOutputDataDefinitionForm.InitializeComponent(), IG.Forms.InputOutputDataDefinitionControl.InputDataControl, IG.Forms.InpuOrOutputtDataDefinitionControl.IsInputData, IG.Forms.InputOutputDataDefinitionForm.MainControl, and IG.Forms.InputOutputDataDefinitionControl.OutputDataControl.
Member Function Documentation
Dispose() [1/3]
override void IG.Forms.InputOutputDataDefinitionForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.InputOutputDataDefinitionForm.components.
InitializeComponent() [1/3]
void IG.Forms.InputOutputDataDefinitionForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.InputOutputDataDefinitionForm.inputOutputDataDefinitionCntrol1.
Referenced by IG.Forms.InputOutputDataDefinitionForm.InputOutputDataDefinitionForm().
Dispose() [2/3]
override void IG.Forms.InputOutputDataDefinitionForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.InputOutputDataDefinitionForm.components.
InitializeComponent() [2/3]
void IG.Forms.InputOutputDataDefinitionForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.InputOutputDataDefinitionForm.inputOutputDataDefinitionCntrol1.
Dispose() [3/3]
override void IG.Forms.InputOutputDataDefinitionForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.InputOutputDataDefinitionForm.components.
InitializeComponent() [3/3]
void IG.Forms.InputOutputDataDefinitionForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.InputOutputDataDefinitionForm.inputOutputDataDefinitionCntrol1.
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.InputOutputDataDefinitionForm.components = null private
Required designer variable.
Referenced by IG.Forms.InputOutputDataDefinitionForm.Dispose().
inputOutputDataDefinitionCntrol1
IG Forms InputOutputDataDefinitionControl IG.Forms.InputOutputDataDefinitionForm.inputOutputDataDefinitionCntrol1 private
Referenced by IG.Forms.InputOutputDataDefinitionForm.InitializeComponent().
Property Documentation
MainControl
InputOutputDataDefinitionControl IG.Forms.InputOutputDataDefinitionForm.MainControl get
Referenced by IG.Forms.InputOutputDataDefinitionForm.InputOutputDataDefinitionForm().
The documentation for this class was generated from the following files:
iglib/extensions/iglibext/Forms/Numeric/FromNeural/Basic/InputOutputDataDefinitionForm.cs
iglib/extensions/iglibext/Forms/Numeric/FromNeural/Basic/InputOutputDataDefinitionForm.Designer.cs