Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DSYTD2 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DSYTD2 Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DSYTD2 (DAXPY daxpy, DLARFG dlarfg, DSYMV dsymv, DSYR2 dsyr2, XERBLA xerbla, LSAME lsame, DDOT ddot)
DSYTD2 ()
void Run (string UPLO, int N, ref double[] A, int offset_a, int LDA, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] TAU, int offset_tau, ref int INFO)
Private Attributes
DAXPY _daxpy
DLARFG _dlarfg
DSYMV _dsymv
DSYR2 _dsyr2
XERBLA _xerbla
LSAME _lsame
DDOT _ddot
Static Private Attributes
const double ONE = 1.0E0
const double ZERO = 0.0E0
const double HALF = 1.0E0 / 2.0E0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DSYTD2 reduces a real symmetric matrix A to symmetric tridiagonal form T by an orthogonal similarity transformation: Q' * A * Q = T.
/summary>
Constructor & Destructor Documentation
DSYTD2() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DSYTD2.DSYTD2 (DAXPY daxpy, DLARFG dlarfg, DSYMV dsymv, DSYR2 dsyr2, XERBLA xerbla, LSAME lsame, DDOT ddot) inline
DSYTD2() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DSYTD2.DSYTD2 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DSYTD2.Run (string UPLO, int N, ref double[] A, int offset_a, int LDA, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] TAU, int offset_tau, ref int INFO) inline
Purpose
DSYTD2 reduces a real symmetric matrix A to symmetric tridiagonal form T by an orthogonal similarity transformation: Q' * A * Q = T.
/summary>
Parameters
UPLO (input) CHARACTER*1 Specifies whether the upper or lower triangular part of the symmetric matrix A is stored: = 'U': Upper triangular = 'L': Lower triangular /param>
Parameters
N (input) INTEGER The order of the matrix A. N .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the symmetric matrix A. If UPLO = 'U', the leading n-by-n upper triangular part of A contains the upper triangular part of the matrix A, and the strictly lower triangular part of A is not referenced. If UPLO = 'L', the leading n-by-n lower triangular part of A contains the lower triangular part of the matrix A, and the strictly upper triangular part of A is not referenced. On exit, if UPLO = 'U', the diagonal and first superdiagonal of A are overwritten by the corresponding elements of the tridiagonal matrix T, and the elements above the first superdiagonal, with the array TAU, represent the orthogonal matrix Q as a product of elementary reflectors; if UPLO = 'L', the diagonal and first subdiagonal of A are over- written by the corresponding elements of the tridiagonal matrix T, and the elements below the first subdiagonal, with the array TAU, represent the orthogonal matrix Q as a product of elementary reflectors. See Further Details. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,N). /param>
Parameters
D (output) DOUBLE PRECISION array, dimension (N) The diagonal elements of the tridiagonal matrix T: D(i) = A(i,i). /param>
Parameters
E (output) DOUBLE PRECISION array, dimension (N-1) The off-diagonal elements of the tridiagonal matrix T: E(i) = A(i,i+1) if UPLO = 'U', E(i) = A(i+1,i) if UPLO = 'L'. /param>
Parameters
TAU (output) DOUBLE PRECISION array, dimension (N-1) The scalar factors of the elementary reflectors (see Further Details). /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value. /param>
References DotNumerics.LinearAlgebra.CSLapack.DSYTD2.HALF, DotNumerics.LinearAlgebra.CSLapack.DSYTD2.ONE, DotNumerics.LinearAlgebra.CSLapack.DDOT.Run(), DotNumerics.LinearAlgebra.CSLapack.DAXPY.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYMV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DSYTD2.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYTRD.Run().
Member Data Documentation
_daxpy
DAXPY DotNumerics.LinearAlgebra.CSLapack.DSYTD2._daxpy private
_dlarfg
DLARFG DotNumerics.LinearAlgebra.CSLapack.DSYTD2._dlarfg private
_dsymv
DSYMV DotNumerics.LinearAlgebra.CSLapack.DSYTD2._dsymv private
_dsyr2
DSYR2 DotNumerics.LinearAlgebra.CSLapack.DSYTD2._dsyr2 private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DSYTD2._xerbla private
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DSYTD2._lsame private
_ddot
DDOT DotNumerics.LinearAlgebra.CSLapack.DSYTD2._ddot private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DSYTD2.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYTD2.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DSYTD2.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYTD2.Run().
HALF
const double DotNumerics.LinearAlgebra.CSLapack.DSYTD2.HALF = 1.0E0 / 2.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYTD2.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dsytd2.cs