Doc: IGLib EXTENDED: NUnit.Framework.Constraints.EqualityAdapter Class Reference
NUnit.Framework.Constraints.EqualityAdapter Class Reference abstract
EqualityAdapter class handles all equality comparisons that use an IEqualityComparer, IEqualityComparer<T> or a ComparisonAdapter.
Classes
class ComparerAdapter
EqualityAdapter that wraps an IComparer.
class ComparerAdapter
EqualityAdapter that wraps an IComparer.
class ComparisonAdapter
class EqualityComparerAdapter
class EqualityComparerAdapter
class GenericEqualityAdapter
Public Member Functions
abstract bool AreEqual (object x, object y)
Compares two objects, returning true if they are equal
virtual bool CanCompare (object x, object y)
Returns true if the two objects can be compared by this adapter. The base adapter cannot handle IEnumerables except for strings.
Static Public Member Functions
static EqualityAdapter For (IComparer comparer)
Returns an EqualityAdapter that wraps an IComparer.
static EqualityAdapter For (IEqualityComparer comparer)
Returns an EqualityAdapter that wraps an IEqualityComparer.
static EqualityAdapter For< T > (IEqualityComparer< T > comparer)
Returns an EqualityAdapter that wraps an IEqualityComparer<T>.
static EqualityAdapter For< T > (IComparer< T > comparer)
Returns an EqualityAdapter that wraps an IComparer<T>.
static EqualityAdapter For< T > (Comparison< T > comparer)
Returns an EqualityAdapter that wraps a Comparison<T>.
Detailed Description
EqualityAdapter class handles all equality comparisons that use an IEqualityComparer, IEqualityComparer<T> or a ComparisonAdapter.
Member Function Documentation
AreEqual()
abstract bool NUnit.Framework.Constraints.EqualityAdapter.AreEqual (object x, object y) pure virtual
Compares two objects, returning true if they are equal
Implemented in NUnit.Framework.Constraints.EqualityAdapter.ComparisonAdapter< T >, NUnit.Framework.Constraints.EqualityAdapter.ComparerAdapter< T >, NUnit.Framework.Constraints.EqualityAdapter.EqualityComparerAdapter< T >, NUnit.Framework.Constraints.EqualityAdapter.EqualityComparerAdapter< T >, and NUnit.Framework.Constraints.EqualityAdapter.ComparerAdapter< T >.
CanCompare()
virtual bool NUnit.Framework.Constraints.EqualityAdapter.CanCompare (object x, object y) inline virtual
Returns true if the two objects can be compared by this adapter. The base adapter cannot handle IEnumerables except for strings.
Reimplemented in NUnit.Framework.Constraints.EqualityAdapter.GenericEqualityAdapter< T >.
Referenced by NUnit.Framework.Constraints.NUnitEqualityComparer.GetExternalComparer().
For() [1/2]
static EqualityAdapter NUnit.Framework.Constraints.EqualityAdapter.For (IComparer comparer) inline static
Returns an EqualityAdapter that wraps an IComparer.
Referenced by NUnit.Framework.Constraints.CollectionItemsEqualConstraint.Using(), NUnit.Framework.Constraints.EqualConstraint.Using(), NUnit.Framework.Constraints.CollectionItemsEqualConstraint.Using< T >(), and NUnit.Framework.Constraints.EqualConstraint.Using< T >().
For() [2/2]
static EqualityAdapter NUnit.Framework.Constraints.EqualityAdapter.For (IEqualityComparer comparer) inline static
Returns an EqualityAdapter that wraps an IEqualityComparer.
For< T >() [1/3]
static EqualityAdapter NUnit.Framework.Constraints.EqualityAdapter.For< T > (IEqualityComparer< T > comparer) inline static
Returns an EqualityAdapter that wraps an IEqualityComparer<T>.
For< T >() [2/3]
static EqualityAdapter NUnit.Framework.Constraints.EqualityAdapter.For< T > (IComparer< T > comparer) inline static
Returns an EqualityAdapter that wraps an IComparer<T>.
For< T >() [3/3]
static EqualityAdapter NUnit.Framework.Constraints.EqualityAdapter.For< T > (Comparison< T > comparer) inline static
Returns an EqualityAdapter that wraps a Comparison<T>.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Constraints/EqualityAdapter.cs