Doc: IGLib EXTENDED: AForge.Fuzzy.LinguisticVariable Class Reference
AForge.Fuzzy.LinguisticVariable Class Reference
The class represents a linguistic variable.
Public Member Functions
LinguisticVariable (string name, float start, float end)
Initializes a new instance of the LinguisticVariable class.
void AddLabel (FuzzySet label)
Adds a linguistic label to the variable.
void ClearLabels ()
Removes all the linguistic labels of the linguistic variable.
FuzzySet GetLabel (string labelName)
Returns an existing label from the linguistic variable.
float GetLabelMembership (string labelName, float value)
Calculate the membership of a given value to a given label. Used to evaluate linguistics clauses like "X IS A", where X is a value and A is a linguistic label.
Properties
float NumericInput [get, set]
Numerical value of the input of this linguistic variable.
string Name [get]
Name of the linguistic variable.
float Start [get]
Left limit of the valid variable range.
float End [get]
Right limit of the valid variable range.
Private Attributes
string name
float start
float end
Dictionary< string, FuzzySet > labels
float numericInput
Detailed Description
The class represents a linguistic variable.
Linguistic variables are variables that store linguistic values (labels). Fuzzy Inference Systems (FIS) use a set of linguistic variables, called the FIS database, to execute fuzzy computation (computing with words). A linguistic variable has a name and is composed by a set of FuzzySet called its linguistic labels. When declaring fuzzy statements in a FIS, a linguistic variable can be only assigned or compared to one of its labels.
Let us consider, for example, a linguistic variable temperature. In a given application, temperature can be cold, cool, warm or hot. Those will be the variable's linguistic labels, each one a fuzzy set with its own membership function. Ideally, the labels will represent concepts related to the variable's meaning. Futhermore, fuzzy statements like "temperature is warm" or "temperature is not cold" can be used to build a Fuzzy Inference Systems.
Sample usage:
// create a linguistic variable to represent temperature
LinguisticVariable lvTemperature = new LinguisticVariable("Temperature", 0, 80);
// create the linguistic labels (fuzzy sets) that compose the temperature
TrapezoidalFunction function1 = new TrapezoidalFunction(10, 15, TrapezoidalFunction.EdgeType.Right);
FuzzySet fsCold = new FuzzySet("Cold", function1);
TrapezoidalFunction function2 = new TrapezoidalFunction(10, 15, 20, 25);
FuzzySet fsCool = new FuzzySet("Cool", function2);
TrapezoidalFunction function3 = new TrapezoidalFunction(20, 25, 30, 35);
FuzzySet fsWarm = new FuzzySet("Warm", function3);
TrapezoidalFunction function4 = new TrapezoidalFunction(30, 35, TrapezoidalFunction.EdgeType.Left);
FuzzySet fsHot  = new FuzzySet("Hot" , function4);
// adding labels to the variable
lvTemperature.AddLabel(fsCold);
lvTemperature.AddLabel(fsCool);
lvTemperature.AddLabel(fsWarm);
lvTemperature.AddLabel(fsHot);
// showing the shape of the linguistic variable - the shape of its labels memberships from start to end
Console.WriteLine("Cold; Cool; Warm; Hot");
for (float x = 0; x < 80; x += 0.2)
{
    float y1 = lvTemperature.GetLabelMembership( "Cold", x );
    float y2 = lvTemperature.GetLabelMembership( "Cool", x );
    float y3 = lvTemperature.GetLabelMembership( "Warm", x );
    float y4 = lvTemperature.GetLabelMembership( "Hot" , x );
    Console.WriteLine( String.Format( "{0:N}; {1:N}; {2:N}; {3:N}", y1, y2, y3, y4 ) );
}
Constructor & Destructor Documentation
LinguisticVariable()
AForge.Fuzzy.LinguisticVariable.LinguisticVariable (string name, float start, float end) inline
Initializes a new instance of the LinguisticVariable class.
Parameters
name Name of the linguistic variable.
Parameters
start Left limit of the valid variable range.
Parameters
end Right limit of the valid variable range.
References AForge.Fuzzy.LinguisticVariable.end, AForge.Fuzzy.LinguisticVariable.name, and AForge.Fuzzy.LinguisticVariable.start.
Member Function Documentation
AddLabel()
void AForge.Fuzzy.LinguisticVariable.AddLabel (FuzzySet label) inline
Adds a linguistic label to the variable.
Parameters
label A FuzzySet that will be a linguistic label of the linguistic variable.
Linguistic labels are fuzzy sets (FuzzySet). Each label of the variable must have a unique name. The range of the label (left and right limits) cannot be greater than the linguistic variable range (start/end).
Exceptions
NullReferenceException The fuzzy set was not initialized.
ArgumentException The linguistic label name already exists in the linguistic variable.
ArgumentException The left limit of the fuzzy set can not be lower than the linguistic variable's starting point.
ArgumentException "The right limit of the fuzzy set can not be greater than the linguistic variable's ending point."
References AForge.Fuzzy.FuzzySet.LeftLimit, AForge.Fuzzy.FuzzySet.Name, and AForge.Fuzzy.FuzzySet.RightLimit.
Referenced by FuzzyAGV.MainForm.InitFuzzyEngine(), and FuzzySetSample.Sample.runLingVarTestButton_Click().
ClearLabels()
void AForge.Fuzzy.LinguisticVariable.ClearLabels () inline
Removes all the linguistic labels of the linguistic variable.
GetLabel()
FuzzySet AForge.Fuzzy.LinguisticVariable.GetLabel (string labelName) inline
Returns an existing label from the linguistic variable.
Parameters
labelName Name of the label to retrieve.
Returns
Reference to named label (FuzzySet).
Exceptions
KeyNotFoundException The label indicated was not found in the linguistic variable.
References AForge.Fuzzy.LinguisticVariable.labels.
Referenced by AForge.Fuzzy.Clause.Clause(), and AForge.Fuzzy.Rule.ParseRule().
GetLabelMembership()
float AForge.Fuzzy.LinguisticVariable.GetLabelMembership (string labelName, float value) inline
Calculate the membership of a given value to a given label. Used to evaluate linguistics clauses like "X IS A", where X is a value and A is a linguistic label.
Parameters
labelName Label (fuzzy set) to evaluate value's membership.
value Value which label's membership will to be calculated.
Returns
Degree of membership [0..1] of the value to the label (fuzzy set).
Exceptions
KeyNotFoundException The label indicated in labelName was not found in the linguistic variable.
References AForge.Fuzzy.FuzzySet.GetMembership(), and AForge.Fuzzy.LinguisticVariable.labels.
Referenced by AForge.Fuzzy.CentroidDefuzzifier.Defuzzify(), and FuzzySetSample.Sample.runLingVarTestButton_Click().
Member Data Documentation
name
string AForge.Fuzzy.LinguisticVariable.name private
Referenced by AForge.Fuzzy.LinguisticVariable.LinguisticVariable().
start
float AForge.Fuzzy.LinguisticVariable.start private
Referenced by AForge.Fuzzy.LinguisticVariable.LinguisticVariable().
end
float AForge.Fuzzy.LinguisticVariable.end private
Referenced by AForge.Fuzzy.LinguisticVariable.LinguisticVariable().
labels
Dictionary<string, FuzzySet> AForge.Fuzzy.LinguisticVariable.labels private
Referenced by AForge.Fuzzy.LinguisticVariable.GetLabel(), and AForge.Fuzzy.LinguisticVariable.GetLabelMembership().
numericInput
float AForge.Fuzzy.LinguisticVariable.numericInput private
Property Documentation
NumericInput
float AForge.Fuzzy.LinguisticVariable.NumericInput get set
Numerical value of the input of this linguistic variable.
Referenced by AForge.Fuzzy.Clause.Evaluate(), and AForge.Fuzzy.InferenceSystem.SetInput().
Name
string AForge.Fuzzy.LinguisticVariable.Name get
Name of the linguistic variable.
Referenced by AForge.Fuzzy.Database.AddVariable(), AForge.Fuzzy.InferenceSystem.ExecuteInference(), AForge.Fuzzy.Rule.ParseRule(), and AForge.Fuzzy.Clause.ToString().
Start
float AForge.Fuzzy.LinguisticVariable.Start get
Left limit of the valid variable range.
Referenced by AForge.Fuzzy.CentroidDefuzzifier.Defuzzify().
End
float AForge.Fuzzy.LinguisticVariable.End get
Right limit of the valid variable range.
Referenced by AForge.Fuzzy.CentroidDefuzzifier.Defuzzify().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Fuzzy/LinguisticVariable.cs