Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DTRMM Class Reference
DotNumerics.LinearAlgebra.CSLapack.DTRMM Class Reference
Public Member Functions
DTRMM (LSAME lsame, XERBLA xerbla)
DTRMM ()
void Run (string SIDE, string UPLO, string TRANSA, string DIAG, int M, int N, double ALPHA, double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB)
Private Attributes
LSAME _lsame
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
Purpose
DTRMM performs one of the matrix-matrix operations
B := alpha*op(A)*B, or B := alpha*B*op(A),
where alpha is a scalar, B is an m by n matrix, A is a unit, or non-unit, upper or lower triangular matrix and op(A) is one of
op(A) = A or op(A) = A'.
Parameters
SIDE - CHARACTER*1. On entry, SIDE specifies whether op(A) multiplies B from the left or right as follows:
SIDE = 'L' or 'l' B := alpha*op(A)*B.
SIDE = 'R' or 'r' B := alpha*B*op(A).
Unchanged on exit.
UPLO - CHARACTER*1. On entry, UPLO specifies whether the matrix A is an upper or lower triangular matrix as follows:
UPLO = 'U' or 'u' A is an upper triangular matrix.
UPLO = 'L' or 'l' A is a lower triangular matrix.
Unchanged on exit.
TRANSA - CHARACTER*1. On entry, TRANSA specifies the form of op(A) to be used in the matrix multiplication as follows:
TRANSA = 'N' or 'n' op(A) = A.
TRANSA = 'T' or 't' op(A) = A'.
TRANSA = 'C' or 'c' op(A) = A'.
Unchanged on exit.
DIAG - CHARACTER*1. On entry, DIAG specifies whether or not A is unit triangular as follows:
DIAG = 'U' or 'u' A is assumed to be unit triangular.
DIAG = 'N' or 'n' A is not assumed to be unit triangular.
Unchanged on exit.
M - INTEGER. On entry, M specifies the number of rows of B. M must be at least zero. Unchanged on exit.
N - INTEGER. On entry, N specifies the number of columns of B. N must be at least zero. Unchanged on exit.
ALPHA - DOUBLE PRECISION. On entry, ALPHA specifies the scalar alpha. When alpha is zero then A is not referenced and B need not be set before entry. Unchanged on exit.
A - DOUBLE PRECISION array of DIMENSION (LDA, k), where k is m when SIDE = 'L' or 'l' and is n when SIDE = 'R' or 'r'. Before entry with UPLO = 'U' or 'u', the leading k by k upper triangular part of the array A must contain the upper triangular matrix and the strictly lower triangular part of A is not referenced. Before entry with UPLO = 'L' or 'l', the leading k by k lower triangular part of the array A must contain the lower triangular matrix and the strictly upper triangular part of A is not referenced. Note that when DIAG = 'U' or 'u', the diagonal elements of A are not referenced either, but are assumed to be unity. Unchanged on exit.
LDA - INTEGER. On entry, LDA specifies the first dimension of A as declared in the calling (sub) program. When SIDE = 'L' or 'l' then LDA must be at least max(1, m), when SIDE = 'R' or 'r' then LDA must be at least max(1, n). Unchanged on exit.
B - DOUBLE PRECISION array of DIMENSION (LDB, n). Before entry, the leading m by n part of the array B must contain the matrix B, and on exit is overwritten by the transformed matrix.
LDB - INTEGER. On entry, LDB specifies the first dimension of B as declared in the calling (sub) program. LDB must be at least max(1, m). Unchanged on exit. /summary>
Constructor & Destructor Documentation
DTRMM() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DTRMM.DTRMM (LSAME lsame, XERBLA xerbla) inline
DTRMM() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DTRMM.DTRMM () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DTRMM.Run (string SIDE, string UPLO, string TRANSA, string DIAG, int M, int N, double ALPHA, double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB) inline
Purpose
DTRMM performs one of the matrix-matrix operations
B := alpha*op(A)*B, or B := alpha*B*op(A),
where alpha is a scalar, B is an m by n matrix, A is a unit, or non-unit, upper or lower triangular matrix and op(A) is one of
op(A) = A or op(A) = A'.
Parameters
SIDE - CHARACTER*1. On entry, SIDE specifies whether op(A) multiplies B from the left or right as follows:
SIDE = 'L' or 'l' B := alpha*op(A)*B.
SIDE = 'R' or 'r' B := alpha*B*op(A).
Unchanged on exit.
UPLO - CHARACTER*1. On entry, UPLO specifies whether the matrix A is an upper or lower triangular matrix as follows:
UPLO = 'U' or 'u' A is an upper triangular matrix.
UPLO = 'L' or 'l' A is a lower triangular matrix.
Unchanged on exit.
TRANSA - CHARACTER*1. On entry, TRANSA specifies the form of op(A) to be used in the matrix multiplication as follows:
TRANSA = 'N' or 'n' op(A) = A.
TRANSA = 'T' or 't' op(A) = A'.
TRANSA = 'C' or 'c' op(A) = A'.
Unchanged on exit.
DIAG - CHARACTER*1. On entry, DIAG specifies whether or not A is unit triangular as follows:
DIAG = 'U' or 'u' A is assumed to be unit triangular.
DIAG = 'N' or 'n' A is not assumed to be unit triangular.
Unchanged on exit.
M - INTEGER. On entry, M specifies the number of rows of B. M must be at least zero. Unchanged on exit.
N - INTEGER. On entry, N specifies the number of columns of B. N must be at least zero. Unchanged on exit.
ALPHA - DOUBLE PRECISION. On entry, ALPHA specifies the scalar alpha. When alpha is zero then A is not referenced and B need not be set before entry. Unchanged on exit.
A - DOUBLE PRECISION array of DIMENSION (LDA, k), where k is m when SIDE = 'L' or 'l' and is n when SIDE = 'R' or 'r'. Before entry with UPLO = 'U' or 'u', the leading k by k upper triangular part of the array A must contain the upper triangular matrix and the strictly lower triangular part of A is not referenced. Before entry with UPLO = 'L' or 'l', the leading k by k lower triangular part of the array A must contain the lower triangular matrix and the strictly upper triangular part of A is not referenced. Note that when DIAG = 'U' or 'u', the diagonal elements of A are not referenced either, but are assumed to be unity. Unchanged on exit.
LDA - INTEGER. On entry, LDA specifies the first dimension of A as declared in the calling (sub) program. When SIDE = 'L' or 'l' then LDA must be at least max(1, m), when SIDE = 'R' or 'r' then LDA must be at least max(1, n). Unchanged on exit.
B - DOUBLE PRECISION array of DIMENSION (LDB, n). Before entry, the leading m by n part of the array B must contain the matrix B, and on exit is overwritten by the transformed matrix.
LDB - INTEGER. On entry, LDB specifies the first dimension of B as declared in the calling (sub) program. LDB must be at least max(1, m). Unchanged on exit. /summary>
Parameters
SIDE
CHARACTER*1. On entry, SIDE specifies whether op(A) multiplies B from the left or right as follows:
SIDE = 'L' or 'l' B := alpha*op(A)*B.
SIDE = 'R' or 'r' B := alpha*B*op(A).
Unchanged on exit. /param>
Parameters
UPLO
CHARACTER*1. On entry, UPLO specifies whether the matrix A is an upper or lower triangular matrix as follows:
UPLO = 'U' or 'u' A is an upper triangular matrix.
UPLO = 'L' or 'l' A is a lower triangular matrix.
Unchanged on exit. /param>
Parameters
TRANSA
CHARACTER*1. On entry, TRANSA specifies the form of op(A) to be used in the matrix multiplication as follows:
TRANSA = 'N' or 'n' op(A) = A.
TRANSA = 'T' or 't' op(A) = A'.
TRANSA = 'C' or 'c' op(A) = A'.
Unchanged on exit. /param>
Parameters
DIAG
CHARACTER*1. On entry, DIAG specifies whether or not A is unit triangular as follows:
DIAG = 'U' or 'u' A is assumed to be unit triangular.
DIAG = 'N' or 'n' A is not assumed to be unit triangular.
Unchanged on exit. /param>
Parameters
M
INTEGER. On entry, M specifies the number of rows of B. M must be at least zero. Unchanged on exit. /param>
Parameters
N
INTEGER. On entry, N specifies the number of columns of B. N must be at least zero. Unchanged on exit. /param>
Parameters
ALPHA
DOUBLE PRECISION. On entry, ALPHA specifies the scalar alpha. When alpha is zero then A is not referenced and B need not be set before entry. Unchanged on exit. /param>
Parameters
A
DOUBLE PRECISION array of DIMENSION (LDA, k), where k is m when SIDE = 'L' or 'l' and is n when SIDE = 'R' or 'r'. Before entry with UPLO = 'U' or 'u', the leading k by k upper triangular part of the array A must contain the upper triangular matrix and the strictly lower triangular part of A is not referenced. Before entry with UPLO = 'L' or 'l', the leading k by k lower triangular part of the array A must contain the lower triangular matrix and the strictly upper triangular part of A is not referenced. Note that when DIAG = 'U' or 'u', the diagonal elements of A are not referenced either, but are assumed to be unity. Unchanged on exit. /param>
Parameters
LDA
INTEGER. On entry, LDA specifies the first dimension of A as declared in the calling (sub) program. When SIDE = 'L' or 'l' then LDA must be at least max(1, m), when SIDE = 'R' or 'r' then LDA must be at least max(1, n). Unchanged on exit. /param>
Parameters
B := alpha*op(A)*B, or B := alpha*B*op(A), /param>
Parameters
LDB
INTEGER. On entry, LDB specifies the first dimension of B as declared in the calling (sub) program. LDB must be at least max(1, m). Unchanged on exit.
/param>
References DotNumerics.LinearAlgebra.CSLapack.DTRMM.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), and DotNumerics.LinearAlgebra.CSLapack.DTRMM.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTRTRI.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAHR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFB.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEHRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARZB.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAQR5.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DTRMM._lsame private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DTRMM._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DTRMM.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTRMM.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DTRMM.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTRMM.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dtrmm.cs