Doc: IGLib EXTENDED: alglib.testconvunit Class Reference
alglib.testconvunit Class Reference
Static Public Member Functions
static bool testconv (bool silent)
static bool testconv (bool silent)
static bool _pexec_testconv (bool silent)
Static Private Member Functions
static void refconvc1d (complex[] a, int m, complex[] b, int n, ref complex[] r)
static void refconvc1dcircular (complex[] a, int m, complex[] b, int n, ref complex[] r)
static void refconvr1d (double[] a, int m, double[] b, int n, ref double[] r)
static void refconvr1dcircular (double[] a, int m, double[] b, int n, ref double[] r)
static void refconvc1d (complex[] a, int m, complex[] b, int n, ref complex[] r)
static void refconvc1dcircular (complex[] a, int m, complex[] b, int n, ref complex[] r)
static void refconvr1d (double[] a, int m, double[] b, int n, ref double[] r)
static void refconvr1dcircular (double[] a, int m, double[] b, int n, ref double[] r)
Member Function Documentation
testconv() [1/2]
static bool alglib.testconvunit.testconv (bool silent) inline static
References alglib.math.abscomplex(), alglib.ap.assert(), alglib.conv.convc1d(), alglib.conv.convc1dcircular(), alglib.conv.convc1dcircularinv(), alglib.conv.convc1dinv(), alglib.conv.convc1dx(), alglib.conv.convr1d(), alglib.conv.convr1dcircular(), alglib.conv.convr1dcircularinv(), alglib.conv.convr1dinv(), alglib.conv.convr1dx(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.testconvunit.refconvc1d(), alglib.testconvunit.refconvc1dcircular(), alglib.testconvunit.refconvr1d(), alglib.testconvunit.refconvr1dcircular(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.testconvunit._pexec_testconv(), and _Test.Main().
refconvc1d() [1/2]
static void alglib.testconvunit.refconvc1d (complex[] a, int m, complex[] b, int n, ref complex[] r) inline static private
Referenced by alglib.testconvunit.refconvc1dcircular(), and alglib.testconvunit.testconv().
refconvc1dcircular() [1/2]
static void alglib.testconvunit.refconvc1dcircular (complex[] a, int m, complex[] b, int n, ref complex[] r) inline static private
References alglib.testconvunit.refconvc1d().
Referenced by alglib.testconvunit.testconv().
refconvr1d() [1/2]
static void alglib.testconvunit.refconvr1d (double[] a, int m, double[] b, int n, ref double[] r) inline static private
Referenced by alglib.testconvunit.refconvr1dcircular(), and alglib.testconvunit.testconv().
refconvr1dcircular() [1/2]
static void alglib.testconvunit.refconvr1dcircular (double[] a, int m, double[] b, int n, ref double[] r) inline static private
References alglib.testconvunit.refconvr1d().
Referenced by alglib.testconvunit.testconv().
testconv() [2/2]
static bool alglib.testconvunit.testconv (bool silent) inline static
References alglib.math.abscomplex(), alglib.ap.assert(), alglib.conv.convc1d(), alglib.conv.convc1dcircular(), alglib.conv.convc1dcircularinv(), alglib.conv.convc1dinv(), alglib.conv.convc1dx(), alglib.conv.convr1d(), alglib.conv.convr1dcircular(), alglib.conv.convr1dcircularinv(), alglib.conv.convr1dinv(), alglib.conv.convr1dx(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.testconvunit.refconvc1d(), alglib.testconvunit.refconvc1dcircular(), alglib.testconvunit.refconvr1d(), alglib.testconvunit.refconvr1dcircular(), alglib.complex.x, and alglib.complex.y.
_pexec_testconv()
static bool alglib.testconvunit._pexec_testconv (bool silent) inline static
References alglib.testconvunit.testconv().
Referenced by _Test.Main().
refconvc1d() [2/2]
static void alglib.testconvunit.refconvc1d (complex[] a, int m, complex[] b, int n, ref complex[] r) inline static private
refconvc1dcircular() [2/2]
static void alglib.testconvunit.refconvc1dcircular (complex[] a, int m, complex[] b, int n, ref complex[] r) inline static private
References alglib.testconvunit.refconvc1d().
refconvr1d() [2/2]
static void alglib.testconvunit.refconvr1d (double[] a, int m, double[] b, int n, ref double[] r) inline static private
refconvr1dcircular() [2/2]
static void alglib.testconvunit.refconvr1dcircular (double[] a, int m, double[] b, int n, ref double[] r) inline static private
References alglib.testconvunit.refconvr1d().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs