Doc: IGLib EXTENDED: NUnit.Framework.Constraints.FloatingPointNumericsTests Class Reference
NUnit.Framework.Constraints.FloatingPointNumericsTests Class Reference
Public Member Functions
void FloatEqualityWithUlps ()
Tests the floating point value comparison helper
void DoubleEqualityWithUlps ()
Tests the double precision floating point value comparison helper
void MirroredIntegerReinterpretation ()
Tests the integer reinterpretation functions
void MirroredLongReinterpretation ()
Tests the long reinterpretation functions
void MirroredFloatReinterpretation ()
Tests the floating point reinterpretation functions
void MirroredDoubleReinterpretation ()
Tests the double prevision floating point reinterpretation functions
Member Function Documentation
FloatEqualityWithUlps()
void NUnit.Framework.Constraints.FloatingPointNumericsTests.FloatEqualityWithUlps () inline
Tests the floating point value comparison helper
References NUnit.Framework.Constraints.FloatingPointNumerics.AreAlmostEqualUlps(), NUnit.Framework.Assert.IsFalse(), and NUnit.Framework.Assert.IsTrue().
DoubleEqualityWithUlps()
void NUnit.Framework.Constraints.FloatingPointNumericsTests.DoubleEqualityWithUlps () inline
Tests the double precision floating point value comparison helper
References NUnit.Framework.Constraints.FloatingPointNumerics.AreAlmostEqualUlps(), NUnit.Framework.Assert.IsFalse(), and NUnit.Framework.Assert.IsTrue().
MirroredIntegerReinterpretation()
void NUnit.Framework.Constraints.FloatingPointNumericsTests.MirroredIntegerReinterpretation () inline
Tests the integer reinterpretation functions
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.FloatingPointNumerics.ReinterpretAsFloat(), and NUnit.Framework.Constraints.FloatingPointNumerics.ReinterpretAsInt().
MirroredLongReinterpretation()
void NUnit.Framework.Constraints.FloatingPointNumericsTests.MirroredLongReinterpretation () inline
Tests the long reinterpretation functions
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.FloatingPointNumerics.ReinterpretAsDouble(), and NUnit.Framework.Constraints.FloatingPointNumerics.ReinterpretAsLong().
MirroredFloatReinterpretation()
void NUnit.Framework.Constraints.FloatingPointNumericsTests.MirroredFloatReinterpretation () inline
Tests the floating point reinterpretation functions
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.FloatingPointNumerics.ReinterpretAsFloat(), and NUnit.Framework.Constraints.FloatingPointNumerics.ReinterpretAsInt().
MirroredDoubleReinterpretation()
void NUnit.Framework.Constraints.FloatingPointNumericsTests.MirroredDoubleReinterpretation () inline
Tests the double prevision floating point reinterpretation functions
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.FloatingPointNumerics.ReinterpretAsDouble(), and NUnit.Framework.Constraints.FloatingPointNumerics.ReinterpretAsLong().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/FloatingPointNumericsTest.cs