Doc: IGLib EXTENDED: NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests Class Reference
NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests Class Reference
Classes
class NullListener
Public Member Functions
void CreateDriver ()
void Load_ReturnsNonRunnableSuite ()
void Explore_ReturnsNonRunnableSuite ()
void CountTestCases_ReturnsZero ()
void Run_ReturnsNonRunnableSuite ()
Static Private Member Functions
static string GetSkipReason (XmlNode result)
Private Attributes
IFrameworkDriver _driver
Static Private Attributes
const string BAD_FILE = "junk.dll"
const string REASON = "Assembly could not be found"
Member Function Documentation
CreateDriver()
void NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.CreateDriver () inline
References NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests._driver, NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.BAD_FILE, NUnit.Engine.Extensibility.IFrameworkDriver.ID, and NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.REASON.
Load_ReturnsNonRunnableSuite()
void NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Load_ReturnsNonRunnableSuite () inline
References NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests._driver, NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.BAD_FILE, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.GetSkipReason(), NUnit.Engine.Extensibility.IFrameworkDriver.Load(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.REASON, and NUnit.Framework.Assert.That().
Explore_ReturnsNonRunnableSuite()
void NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Explore_ReturnsNonRunnableSuite () inline
References NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests._driver, NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.BAD_FILE, NUnit.Engine.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Extensibility.IFrameworkDriver.Explore(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.GetSkipReason(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.REASON, NUnit.Engine.TestFilter.Text, and NUnit.Framework.Assert.That().
CountTestCases_ReturnsZero()
void NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.CountTestCases_ReturnsZero () inline
References NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests._driver, NUnit.Engine.Extensibility.IFrameworkDriver.CountTestCases(), NUnit.Engine.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Engine.TestFilter.Text, and NUnit.Framework.Assert.That().
Run_ReturnsNonRunnableSuite()
void NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Run_ReturnsNonRunnableSuite () inline
References NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests._driver, NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.BAD_FILE, NUnit.Engine.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.GetSkipReason(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.REASON, NUnit.Engine.Extensibility.IFrameworkDriver.Run(), NUnit.Engine.TestFilter.Text, and NUnit.Framework.Assert.That().
GetSkipReason()
static string NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.GetSkipReason (XmlNode result) inline static private
References NUnit.Framework.Internal.PropertyNames.SkipReason.
Referenced by NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Explore_ReturnsNonRunnableSuite(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Load_ReturnsNonRunnableSuite(), and NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Run_ReturnsNonRunnableSuite().
Member Data Documentation
BAD_FILE
const string NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.BAD_FILE = "junk.dll" static private
Referenced by NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.CreateDriver(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Explore_ReturnsNonRunnableSuite(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Load_ReturnsNonRunnableSuite(), and NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Run_ReturnsNonRunnableSuite().
REASON
const string NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.REASON = "Assembly could not be found" static private
Referenced by NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.CreateDriver(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Explore_ReturnsNonRunnableSuite(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Load_ReturnsNonRunnableSuite(), and NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Run_ReturnsNonRunnableSuite().
_driver
IFrameworkDriver NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests._driver private
Referenced by NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.CountTestCases_ReturnsZero(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.CreateDriver(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Explore_ReturnsNonRunnableSuite(), NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Load_ReturnsNonRunnableSuite(), and NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Run_ReturnsNonRunnableSuite().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Drivers/NotRunnableFrameworkDriverTests.cs