Doc: IGLib EXTENDED: IG.Forms.VectorFunctionPlotter2d Class Reference
IG.Forms.VectorFunctionPlotter2d Class Reference
Form for simple parametric tests (variation of selected parameter) performed on ANN models.
Public Member Functions
VectorFunctionPlotter2d ()
virtual double CalculateOutput (IVector parameters, int whichOutput)
Calculates the specified output value of the vector function at the specified parameters.
void ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void PlotParametricTest1d ()
plots the selected outpt dependend on the selected parameter.
virtual void ApplySurfacePlotSettingsDefault (VtkSurfacePlotBase plot)
Applies default settings to surface plots.
virtual void ApplySurfacePlottterSettingsDefault (VtkPlotter plotter, int whichInput1, int whichInput2, int whichOutput)
Applies default settings to plotter used to render 3D graphs.
void PlotParametricTest ()
plots the selected outpt dependend on the selected parameter.
VectorFunctionPlotter2d ()
virtual double CalculateOutput (IVector parameters, int whichOutput)
Calculates the specified output value of the vector function at the specified parameters.
void ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void PlotParametricTest1d ()
plots the selected outpt dependend on the selected parameter.
virtual void ApplySurfacePlotSettingsDefault (VtkSurfacePlotBase plot)
Applies default settings to surface plots.
virtual void ApplySurfacePlottterSettingsDefault (VtkPlotter plotter, int whichInput1, int whichInput2, int whichOutput)
Applies default settings to plotter used to render 3D graphs.
void PlotParametricTest ()
plots the selected outpt dependend on the selected parameter.
VectorFunctionPlotter2d ()
virtual double CalculateOutput (IVector parameters, int whichOutput)
Calculates the specified output value of the vector function at the specified parameters.
void ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void PlotParametricTest1d ()
plots the selected outpt dependend on the selected parameter.
virtual void ApplySurfacePlotSettingsDefault (VtkSurfacePlotBase plot)
Applies default settings to surface plots.
virtual void ApplySurfacePlottterSettingsDefault (VtkPlotter plotter, int whichInput1, int whichInput2, int whichOutput)
Applies default settings to plotter used to render 3D graphs.
void PlotParametricTest ()
plots the selected outpt dependend on the selected parameter.
VectorFunctionPlotter2d ()
virtual double CalculateOutput (IVector parameters, int whichOutput)
Calculates the specified output value of the vector function at the specified parameters.
void ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void PlotParametricTest1d ()
plots the selected outpt dependend on the selected parameter.
virtual void ApplySurfacePlotSettingsDefault (VtkSurfacePlotBase plot)
Applies default settings to surface plots.
virtual void ApplySurfacePlottterSettingsDefault (VtkPlotter plotter, int whichInput1, int whichInput2, int whichOutput)
Applies default settings to plotter used to render 3D graphs.
void PlotParametricTest ()
plots the selected outpt dependend on the selected parameter.
Static Public Attributes
static string SelectedParametersIntroStr = "Selected input parameters: "
Protected Member Functions
void UpdateSeclectedParametersDependencies ()
override void Dispose (bool disposing)
Clean up any resources being used.
void UpdateSeclectedParametersDependencies ()
override void Dispose (bool disposing)
Clean up any resources being used.
void UpdateSeclectedParametersDependencies ()
override void Dispose (bool disposing)
Clean up any resources being used.
void UpdateSeclectedParametersDependencies ()
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
int _selectedParameterId1 = 0
int _selectedParameterId2 = 0
int _selectedOutputId = 0
int _numPoints1 = 80
int _numPoints2 = 80
ColorScale SurfaceColorScale
BoundingBox3d OriginalBounds
Properties
IReporter Reporter [get]
Reorter used for launching info, warning and error reports.
InputOutputDataDefiniton NeuralDataDefinition [get, set]
Data about input and output quantities of the manipulated functions or response.
IScalarFunction ScalarFunction [set]
IVectorFunction Function [get, set]
int NumInputParameters [get]
Gets number of input parameters.
int NumOutputValues [get]
Gets number of output values.
IVector ParameterValues [get]
Vector of current values of input parameters as defined by the DadaGridView.
double[] MinValues [get]
Minimal values of parameters.
double[] MaxValues [get]
Maximal values of parameters.
int SelectedParameterId1 [get, protected set]
Sequential number of the selected first parameter as specified by the user.
double SelectedParameterMin1 [get]
Minimal value of the selected first parameter.
double SelectedParameterMax1 [get]
Maximal value of the selected first parameter as specified by the user.
int SelectedParameterId2 [get, protected set]
Sequential number of the selected second parameter as specified by the user.
double SelectedParameterMin2 [get]
Minimal value of the selected second parameter.
double SelectedParameterMax2 [get]
Maximal value of the selected second parameter as specified by the user.
int SelectedOutputId [get, protected set]
int NumPlotPoints1 [get, set]
Number of plotting points in the 1st direction.
int NumPlotPoints2 [get, set]
Number of plotting points in the 2nd direction.
string SelectedParameterLabelText [get]
Gets axis label text for the currently selected parameter.
string SelectedOutputLabelText [get]
Gets axis label text for the currently selected output value.
PlotterZedGraph Plotterzedgraph [get]
Plotter that is used for plotting the graphs.
bool PlotImmediately [get, set]
If true then graph is pletted immediately when any parameter changes that affects it appearance.
bool PlotImmediately2dAlso [get, set]
bool PlotImmediatelyOnNumPointsValueChanged [get, set]
Private Member Functions
void neuralInputSelector1_SelectedParameterIdChanged (object sender, IndexChangeEventArgs e)
Executes when ID of the selected first input parameter changes; Plots the parametric test.
void neuralInputSelector1_SelectedParameterMinChanged (object sender, ValueChangeEventArgs e)
Executes when minimal value of the selected first parameter changes by user interaction; Plots the parametric test.
void neuralInputSelector1_SelectedParameterMaxChanged (object sender, ValueChangeEventArgs e)
Executes when maximal value of the selected first parameter changes by user interaction; Plots the parametric test.
void neuralInputSelector2_SelectedParameterIdChanged (object sender, IndexChangeEventArgs e)
Executes when ID of the selected second input parameter changes; Plots the parametric test.
void neuralInputSelector2_SelectedParameterMinChanged (object sender, ValueChangeEventArgs e)
Executes when minimal value of the selected second parameter changes by user interaction; Plots the parametric test.
void neuralInputSelector2_SelectedParameterMaxChanged (object sender, ValueChangeEventArgs e)
Executes when maximal value of the selected second parameter changes by user interaction; Plots the parametric test.
void neuralOutputValueSelector1_SelectedOutputIdChanged (object sender, IndexChangeEventArgs e)
Executes when ID of the selected output value changes; Plots the parametric test.
void chkPlotImmediately_CheckedChanged (object sender, EventArgs e)
void numNumPlotPoints1_Validated (object sender, EventArgs e)
void numNumPlotPoints1_ValueChanged (object sender, EventArgs e)
void numNumPlotPoints2_Validated (object sender, EventArgs e)
void numNumPlotPoints2_ValueChanged (object sender, EventArgs e)
void btnParmTestStart_Click (object sender, EventArgs e)
Plots the parametric test.
void btnIdentifyThread_Click (object sender, EventArgs e)
void btnCheck_Click (object sender, EventArgs e)
void btnTestFunction_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void btnParmTestStart_Click (object sender, EventArgs e)
Plots the parametric test.
void neuralInputSelector1_SelectedParameterIdChanged (int oldId, int newId)
Executes when ID of the selected first input parameter changes; Plots the parametric test.
void neuralInputSelector1_SelectedParameterMinChanged (double oldValue, double newValue)
Executes when minimal value of the selected first parameter changes by user interaction; Plots the parametric test.
void neuralInputSelector1_SelectedParameterMaxChanged (double oldValue, double newValue)
Executes when maximal value of the selected first parameter changes by user interaction; Plots the parametric test.
void neuralInputSelector2_SelectedParameterIdChanged (int oldId, int newId)
Executes when ID of the selected second input parameter changes; Plots the parametric test.
void neuralInputSelector2_SelectedParameterMinChanged (double oldValue, double newValue)
Executes when minimal value of the selected second parameter changes by user interaction; Plots the parametric test.
void neuralInputSelector2_SelectedParameterMaxChanged (double oldValue, double newValue)
Executes when maximal value of the selected second parameter changes by user interaction; Plots the parametric test.
void neuralOutputValueSelector1_SelectedOutputIdChanged (int oldId, int newId)
Executes when ID of the selected output value changes; Plots the parametric test.
void chkPlotImmediately_CheckedChanged (object sender, EventArgs e)
void btnIdentifyThread_Click (object sender, EventArgs e)
void btnCheck_Click (object sender, EventArgs e)
void btnTestFunction_Click (object sender, EventArgs e)
void numNumPlotPoints1_Validated (object sender, EventArgs e)
void numNumPlotPoints1_ValueChanged (object sender, EventArgs e)
void numNumPlotPoints2_Validated (object sender, EventArgs e)
void numNumPlotPoints2_ValueChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void neuralInputSelector1_SelectedParameterIdChanged (object sender, IndexChangeEventArgs e)
Executes when ID of the selected first input parameter changes; Plots the parametric test.
void neuralInputSelector1_SelectedParameterMinChanged (object sender, ValueChangeEventArgs e)
Executes when minimal value of the selected first parameter changes by user interaction; Plots the parametric test.
void neuralInputSelector1_SelectedParameterMaxChanged (object sender, ValueChangeEventArgs e)
Executes when maximal value of the selected first parameter changes by user interaction; Plots the parametric test.
void neuralInputSelector2_SelectedParameterIdChanged (object sender, IndexChangeEventArgs e)
Executes when ID of the selected second input parameter changes; Plots the parametric test.
void neuralInputSelector2_SelectedParameterMinChanged (object sender, ValueChangeEventArgs e)
Executes when minimal value of the selected second parameter changes by user interaction; Plots the parametric test.
void neuralInputSelector2_SelectedParameterMaxChanged (object sender, ValueChangeEventArgs e)
Executes when maximal value of the selected second parameter changes by user interaction; Plots the parametric test.
void neuralOutputValueSelector1_SelectedOutputIdChanged (object sender, IndexChangeEventArgs e)
Executes when ID of the selected output value changes; Plots the parametric test.
void chkPlotImmediately_CheckedChanged (object sender, EventArgs e)
void numNumPlotPoints1_Validated (object sender, EventArgs e)
void numNumPlotPoints1_ValueChanged (object sender, EventArgs e)
void numNumPlotPoints2_Validated (object sender, EventArgs e)
void numNumPlotPoints2_ValueChanged (object sender, EventArgs e)
void btnParmTestStart_Click (object sender, EventArgs e)
Plots the parametric test.
void btnIdentifyThread_Click (object sender, EventArgs e)
void btnCheck_Click (object sender, EventArgs e)
void btnTestFunction_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void neuralInputSelector1_SelectedParameterIdChanged (object sender, IndexChangeEventArgs e)
Executes when ID of the selected first input parameter changes; Plots the parametric test.
void neuralInputSelector1_SelectedParameterMinChanged (object sender, ValueChangeEventArgs e)
Executes when minimal value of the selected first parameter changes by user interaction; Plots the parametric test.
void neuralInputSelector1_SelectedParameterMaxChanged (object sender, ValueChangeEventArgs e)
Executes when maximal value of the selected first parameter changes by user interaction; Plots the parametric test.
void neuralInputSelector2_SelectedParameterIdChanged (object sender, IndexChangeEventArgs e)
Executes when ID of the selected second input parameter changes; Plots the parametric test.
void neuralInputSelector2_SelectedParameterMinChanged (object sender, ValueChangeEventArgs e)
Executes when minimal value of the selected second parameter changes by user interaction; Plots the parametric test.
void neuralInputSelector2_SelectedParameterMaxChanged (object sender, ValueChangeEventArgs e)
Executes when maximal value of the selected second parameter changes by user interaction; Plots the parametric test.
void neuralOutputValueSelector1_SelectedOutputIdChanged (object sender, IndexChangeEventArgs e)
Executes when ID of the selected output value changes; Plots the parametric test.
void chkPlotImmediately_CheckedChanged (object sender, EventArgs e)
void numNumPlotPoints1_Validated (object sender, EventArgs e)
void numNumPlotPoints1_ValueChanged (object sender, EventArgs e)
void numNumPlotPoints2_Validated (object sender, EventArgs e)
void numNumPlotPoints2_ValueChanged (object sender, EventArgs e)
void btnParmTestStart_Click (object sender, EventArgs e)
Plots the parametric test.
void btnIdentifyThread_Click (object sender, EventArgs e)
void btnCheck_Click (object sender, EventArgs e)
void btnTestFunction_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
InputOutputDataDefiniton _neuralDataDefinition
IScalarFunction _scalarFunction
IVectorFunction _function
PlotterZedGraph _plotterZedgraph
bool _plotImmediately = false
bool _plotImmediately2dAlso = false
bool _plotImmediatelyOnNumPointsValueChanged = true
System.ComponentModel.IContainer components = null
Required designer variable.
InputParametersControl neuralInputControl1
System.Windows.Forms.Panel pnlGraph
System.Windows.Forms.NumericUpDown numNumPlotPoints1
System.Windows.Forms.Label lblNumPoints
ZedGraph.ZedGraphControl ParmTestFGraph
System.Windows.Forms.Button btnParamTestStart
IG.Forms.OutputValueSelector neuralOutputValueSelector1
IG.Forms.InputParameterSelectorMinMax neuralInputSelector1
System.Windows.Forms.Label lblTitleParametric2d
IG.Forms.InputParameterSelectorMinMax neuralInputSelector2
System.Windows.Forms.NumericUpDown numNumPlotPoints2
System.Windows.Forms.Label lblNumPointsCross
System.Windows.Forms.Label lblSelectedParameters
System.Windows.Forms.CheckBox chkScaled
IG.Forms.IndicatorLight indicatorLight1
System.Windows.Forms.CheckBox chkPlotImmediately
System.Windows.Forms.Button btnIdentifyThread
System.Windows.Forms.Button btnCheck
System.Windows.Forms.Button btnTestFunction
NeuralInputControl neuralInputControl1
IG.Forms.NeuralOutputValueSelector neuralOutputValueSelector1
IG.Forms.NeuralInputParameterSelectorMinMax neuralInputSelector1
IG.Forms.NeuralInputParameterSelectorMinMax neuralInputSelector2
Detailed Description
Form for simple parametric tests (variation of selected parameter) performed on ANN models.
$A Igor Jun13;
Constructor & Destructor Documentation
VectorFunctionPlotter2d() [1/4]
IG.Forms.VectorFunctionPlotter2d.VectorFunctionPlotter2d () inline
References IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately, IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2, IG.Forms.VectorFunctionPlotter2d.NumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.NumPlotPoints2, and IG.Forms.VectorFunctionPlotter2d.PlotImmediately.
VectorFunctionPlotter2d() [2/4]
IG.Forms.VectorFunctionPlotter2d.VectorFunctionPlotter2d () inline
References IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately, IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2, IG.Forms.VectorFunctionPlotter2d.NumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.NumPlotPoints2, and IG.Forms.VectorFunctionPlotter2d.PlotImmediately.
VectorFunctionPlotter2d() [3/4]
IG.Forms.VectorFunctionPlotter2d.VectorFunctionPlotter2d () inline
References IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately, IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2, IG.Forms.VectorFunctionPlotter2d.NumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.NumPlotPoints2, and IG.Forms.VectorFunctionPlotter2d.PlotImmediately.
VectorFunctionPlotter2d() [4/4]
IG.Forms.VectorFunctionPlotter2d.VectorFunctionPlotter2d () inline
References IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately, IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2, IG.Forms.VectorFunctionPlotter2d.NumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.NumPlotPoints2, and IG.Forms.VectorFunctionPlotter2d.PlotImmediately.
Member Function Documentation
CalculateOutput() [1/4]
virtual double IG.Forms.VectorFunctionPlotter2d.CalculateOutput (IVector parameters, int whichOutput) inline virtual
Calculates the specified output value of the vector function at the specified parameters.
Parameters
parameters Parameter values.
whichOutput Specifies which output value (which element of the vector function) should be calculated.
Returns
The calculated vector function component.
References IG.Forms.VectorFunctionPlotter2d._scalarFunction, IG.Forms.VectorFunctionPlotter2d.Function, IG.Forms.VectorFunctionPlotter2d.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Num.IVectorFunction.Value().
Referenced by IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
UpdateSeclectedParametersDependencies() [1/4]
void IG.Forms.VectorFunctionPlotter2d.UpdateSeclectedParametersDependencies () inline protected
References IG.Forms.VectorFunctionPlotter2d.lblSelectedParameters, IG.Forms.VectorFunctionPlotter2d.SelectedParameterId1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterId2, and IG.Forms.VectorFunctionPlotter2d.SelectedParametersIntroStr.
Referenced by IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterIdChanged(), and IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterIdChanged().
ApplyPlotterSettingsDefault() [1/4]
void IG.Forms.VectorFunctionPlotter2d.ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Num.InputOutputDataDefiniton.InputElementList, IG.Gr.PlotterZedGraph.IsShowPointValues, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Forms.VectorFunctionPlotter2d.SelectedOutputLabelText, IG.Forms.VectorFunctionPlotter2d.SelectedParameterLabelText, IG.Gr.PlotterZedGraph.XAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabel.
Referenced by IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
ApplyPlotCurveSettingsDefault() [1/4]
void IG.Forms.VectorFunctionPlotter2d.ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LineWidth, IG.Gr.PlotZedgraphCurve.PointBorderColor, IG.Gr.PlotZedgraphCurve.PointFillColor, and IG.Gr.PlotZedgraphCurve.PointsVisible.
Referenced by IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
PlotParametricTest1d() [1/4]
void IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d () inline
plots the selected outpt dependend on the selected parameter.
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Forms.VectorFunctionPlotter2d.ApplyPlotCurveSettingsDefault(), IG.Forms.VectorFunctionPlotter2d.ApplyPlotterSettingsDefault(), IG.Forms.VectorFunctionPlotter2d.CalculateOutput(), IG.Num.VectorBase.CopyPlain(), IG.Forms.VectorFunctionPlotter2d.NumInputParameters, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.NumOutputValues, IG.Forms.VectorFunctionPlotter2d.ParameterValues, IG.Forms.VectorFunctionPlotter2d.Plotterzedgraph, IG.Gr.PlotterZedGraph.RemoveAllPlotObjects(), IG.Gr.PlotterZedGraph.ResetView(), IG.Forms.VectorFunctionPlotter2d.SelectedOutputId, IG.Forms.VectorFunctionPlotter2d.SelectedParameterId1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMax1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMin1, and IG.Gr.PlotterZedGraph.Update().
Referenced by IG.Forms.VectorFunctionPlotter2d.btnParmTestStart_Click(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMinChanged(), and IG.Forms.VectorFunctionPlotter2d.neuralOutputValueSelector1_SelectedOutputIdChanged().
ApplySurfacePlotSettingsDefault() [1/4]
virtual void IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlotSettingsDefault (VtkSurfacePlotBase plot) inline virtual
Applies default settings to surface plots.
Parameters
plot Surface plot to which settings are applied.
References IG.Gr3d.VtkSurfacePlotBase.LineColor, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, IG.Forms.VectorFunctionPlotter2d.SurfaceColorScale, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
Referenced by IG.Forms.VectorFunctionPlotter2d.PlotParametricTest().
ApplySurfacePlottterSettingsDefault() [1/4]
virtual void IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlottterSettingsDefault (VtkPlotter plotter, int whichInput1, int whichInput2, int whichOutput) inline virtual
Applies default settings to plotter used to render 3D graphs.
Parameters
plotter 3D Plotter to which settings are applied.
References IG.Gr3d.VtkPlotter.BackGround, IG.Forms.VectorFunctionPlotter2d.chkScaled, IG.Gr3d.VtkDecorationHandler.CubeAxesFlyMode, IG.Gr3d.VtkDecorationHandler.CubeAxesXLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesYLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesZLabel, IG.Gr3d.VtkPlotter.DecorationHandler, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Gr3d.VtkDecorationHandler.LookUpTableColorScale, IG.Gr3d.VtkDecorationHandler.LookUpTableMaxRange, IG.Gr3d.VtkDecorationHandler.LookUpTableMinRange, IG.Num.BoundingBox3d.MaxZ, IG.Num.BoundingBox3d.MinZ, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Forms.VectorFunctionPlotter2d.OriginalBounds, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Gr3d.VtkDecorationHandler.ScalarBarNumberOfLabels, IG.Gr3d.VtkDecorationHandler.ScalarBarTitle, IG.Gr3d.VtkDecorationHandler.ShowCubeAxes, IG.Gr3d.VtkDecorationHandler.ShowScalarBar, IG.Forms.VectorFunctionPlotter2d.SurfaceColorScale, IG.Gr3d.VtkPlotter.WindowSizeX, and IG.Gr3d.VtkPlotter.WindowSizeY.
Referenced by IG.Forms.VectorFunctionPlotter2d.PlotParametricTest().
PlotParametricTest() [1/4]
void IG.Forms.VectorFunctionPlotter2d.PlotParametricTest () inline
plots the selected outpt dependend on the selected parameter.
References IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlotSettingsDefault(), IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlottterSettingsDefault(), IG.Forms.IndicatorLight.BlinkError(), IG.Forms.VectorFunctionPlotter2d.CalculateOutput(), IG.Forms.VectorFunctionPlotter2d.chkScaled, IG.Gr3d.VtkSurfacePlot.ClearSurfaceDefinition(), IG.Num.VectorBase.CopyPlain(), IG.Gr3d.VtkSurfacePlot.Create(), IG.Forms.VectorFunctionPlotter2d.Function, IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Num.BoundingBoxBase.Map(), IG.Num.BoundingBoxBase.Max, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Num.BoundingBoxBase.Min, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Forms.VectorFunctionPlotter2d.NumInputParameters, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2, IG.Forms.VectorFunctionPlotter2d.OriginalBounds, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Forms.VectorFunctionPlotter2d.ParameterValues, IG.Forms.VectorFunctionPlotter2d.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Gr3d.VtkPlotter.ResetCamera(), IG.Forms.VectorFunctionPlotter2d.SelectedOutputId, IG.Forms.VectorFunctionPlotter2d.SelectedParameterId1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterId2, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMax1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMax2, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMin1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMin2, IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetOff(), IG.Forms.IndicatorLight.SetOk(), IG.Gr3d.VtkPlotBase.ShowPlot(), IG.Num.BoundingBoxBase.ToString(), IG.Num.BoundingBox3d.Update(), and IG.Num.Vector3d.Vec.
Referenced by IG.Forms.VectorFunctionPlotter2d.btnParmTestStart_Click(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMinChanged(), and IG.Forms.VectorFunctionPlotter2d.neuralOutputValueSelector1_SelectedOutputIdChanged().
neuralInputSelector1_SelectedParameterIdChanged() [1/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterIdChanged (object sender, IndexChangeEventArgs e) inline private
Executes when ID of the selected first input parameter changes; Plots the parametric test.
Parameters
sender Control that generated the event.
e Event arguments that contain the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2, IG.Forms.VectorFunctionPlotter2d.NumInputParameters, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d(), IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, IG.Forms.InputParameterSelectorMinMax.SetSelectedParameterId(), and IG.Forms.VectorFunctionPlotter2d.UpdateSeclectedParametersDependencies().
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
neuralInputSelector1_SelectedParameterMinChanged() [1/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMinChanged (object sender, ValueChangeEventArgs e) inline private
Executes when minimal value of the selected first parameter changes by user interaction; Plots the parametric test.
Parameters
sender Control that generated the event.
e Event arguments that contain the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
neuralInputSelector1_SelectedParameterMaxChanged() [1/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMaxChanged (object sender, ValueChangeEventArgs e) inline private
Executes when maximal value of the selected first parameter changes by user interaction; Plots the parametric test.
Parameters
sender Control that generated the event.
e Event arguments that contain the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
neuralInputSelector2_SelectedParameterIdChanged() [1/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterIdChanged (object sender, IndexChangeEventArgs e) inline private
Executes when ID of the selected second input parameter changes; Plots the parametric test.
Parameters
sender Control that generated the event.
e Event arguments that contain the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d(), IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, IG.Forms.InputParameterSelectorMinMax.SetSelectedParameterId(), and IG.Forms.VectorFunctionPlotter2d.UpdateSeclectedParametersDependencies().
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
neuralInputSelector2_SelectedParameterMinChanged() [1/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMinChanged (object sender, ValueChangeEventArgs e) inline private
Executes when minimal value of the selected second parameter changes by user interaction; Plots the parametric test.
Parameters
sender Object that raised the event.
e Event arguments containing the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
neuralInputSelector2_SelectedParameterMaxChanged() [1/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMaxChanged (object sender, ValueChangeEventArgs e) inline private
Executes when maximal value of the selected second parameter changes by user interaction; Plots the parametric test.
Parameters
sender Object that raised the event.
e Event arguments containing the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
neuralOutputValueSelector1_SelectedOutputIdChanged() [1/4]
void IG.Forms.VectorFunctionPlotter2d.neuralOutputValueSelector1_SelectedOutputIdChanged (object sender, IndexChangeEventArgs e) inline private
Executes when ID of the selected output value changes; Plots the parametric test.
Parameters
sender Object that raised the event.
e Event arguments containing the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
chkPlotImmediately_CheckedChanged() [1/4]
void IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately, and IG.Forms.VectorFunctionPlotter2d.PlotImmediately.
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
numNumPlotPoints1_Validated() [1/4]
void IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, and IG.Forms.VectorFunctionPlotter2d.NumPlotPoints1.
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
numNumPlotPoints1_ValueChanged() [1/4]
void IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.NumPlotPoints1, and IG.Forms.VectorFunctionPlotter2d.PlotImmediatelyOnNumPointsValueChanged.
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
numNumPlotPoints2_Validated() [1/4]
void IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2, and IG.Forms.VectorFunctionPlotter2d.NumPlotPoints2.
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
numNumPlotPoints2_ValueChanged() [1/4]
void IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2, IG.Forms.VectorFunctionPlotter2d.NumPlotPoints2, and IG.Forms.VectorFunctionPlotter2d.PlotImmediatelyOnNumPointsValueChanged.
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
btnParmTestStart_Click() [1/4]
void IG.Forms.VectorFunctionPlotter2d.btnParmTestStart_Click (object sender, EventArgs e) inline private
Plots the parametric test.
References IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
btnIdentifyThread_Click() [1/4]
void IG.Forms.VectorFunctionPlotter2d.btnIdentifyThread_Click (object sender, EventArgs e) inline private
References IG.Forms.UtilForms.IdentifyCurrentThread().
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
btnCheck_Click() [1/4]
void IG.Forms.VectorFunctionPlotter2d.btnCheck_Click (object sender, EventArgs e) inline private
References IG.Forms.FadingMessage.Launch(), IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, and IG.Num.InputOutputDataDefiniton.ToString().
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
btnTestFunction_Click() [1/4]
void IG.Forms.VectorFunctionPlotter2d.btnTestFunction_Click (object sender, EventArgs e) inline private
References IG.Num.InputOutputDataDefiniton.CreateDefault(), IG.Forms.VectorFunctionPlotter2d.Function, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Num.IVectorFunction.NumParameters, and IG.Num.IVectorFunction.NumValues.
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
Dispose() [1/4]
override void IG.Forms.VectorFunctionPlotter2d.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.VectorFunctionPlotter2d.components.
InitializeComponent() [1/4]
void IG.Forms.VectorFunctionPlotter2d.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.VectorFunctionPlotter2d.btnCheck, IG.Forms.VectorFunctionPlotter2d.btnCheck_Click(), IG.Forms.VectorFunctionPlotter2d.btnIdentifyThread, IG.Forms.VectorFunctionPlotter2d.btnIdentifyThread_Click(), IG.Forms.VectorFunctionPlotter2d.btnParamTestStart, IG.Forms.VectorFunctionPlotter2d.btnParmTestStart_Click(), IG.Forms.VectorFunctionPlotter2d.btnTestFunction, IG.Forms.VectorFunctionPlotter2d.btnTestFunction_Click(), IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately, IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately_CheckedChanged(), IG.Forms.VectorFunctionPlotter2d.chkScaled, IG.Forms.IndicatorLight.ColorLabel, IG.Forms.VectorFunctionPlotter2d.components, IG.Forms.OutputValueSelector.DataDefinition, IG.Forms.InputParameterSelectorMinMax.DataDefinition, IG.Forms.InputParametersControl.DataDefinition, IG.Forms.IndicatorLight.FlowDirection, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLight.LabelFont, IG.Forms.IndicatorLight.LabelText, IG.Forms.VectorFunctionPlotter2d.lblNumPoints, IG.Forms.VectorFunctionPlotter2d.lblNumPointsCross, IG.Forms.VectorFunctionPlotter2d.lblSelectedParameters, IG.Forms.VectorFunctionPlotter2d.lblTitleParametric2d, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.VectorFunctionPlotter2d.neuralInputControl1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter2d.neuralOutputValueSelector1, IG.Forms.VectorFunctionPlotter2d.neuralOutputValueSelector1_SelectedOutputIdChanged(), IG.Forms.OutputValueSelector.NumInputParameters, IG.Forms.InputParameterSelectorMinMax.NumInputParameters, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_Validated(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_ValueChanged(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_Validated(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_ValueChanged(), IG.Forms.OutputValueSelector.NumOutputValues, IG.Forms.InputParameterSelectorMinMax.NumOutputValues, IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.VectorFunctionPlotter2d.ParmTestFGraph, IG.Forms.VectorFunctionPlotter2d.pnlGraph, IG.Forms.OutputValueSelector.SelectedOutputIdChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterIdChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMaxChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMinChanged, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, and IG.Forms.InputParameterSelectorMinMax.TitleParameterSelection.
Referenced by IG.Forms.VectorFunctionPlotter2d.VectorFunctionPlotter2d().
CalculateOutput() [2/4]
virtual double IG.Forms.VectorFunctionPlotter2d.CalculateOutput (IVector parameters, int whichOutput) inline virtual
Calculates the specified output value of the vector function at the specified parameters.
Parameters
parameters Parameter values.
whichOutput Specifies which output value (which element of the vector function) should be calculated.
Returns
The calculated vector function component.
References IG.Forms.VectorFunctionPlotter2d._scalarFunction, IG.Forms.VectorFunctionPlotter2d.Function, IG.Forms.VectorFunctionPlotter2d.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Num.IVectorFunction.Value().
UpdateSeclectedParametersDependencies() [2/4]
void IG.Forms.VectorFunctionPlotter2d.UpdateSeclectedParametersDependencies () inline protected
References IG.Forms.VectorFunctionPlotter2d.lblSelectedParameters, IG.Forms.VectorFunctionPlotter2d.SelectedParameterId1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterId2, and IG.Forms.VectorFunctionPlotter2d.SelectedParametersIntroStr.
ApplyPlotterSettingsDefault() [2/4]
void IG.Forms.VectorFunctionPlotter2d.ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Num.InputOutputDataDefiniton.InputElementList, IG.Gr.PlotterZedGraph.IsShowPointValues, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Forms.VectorFunctionPlotter2d.SelectedOutputLabelText, IG.Forms.VectorFunctionPlotter2d.SelectedParameterLabelText, IG.Gr.PlotterZedGraph.XAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabel.
ApplyPlotCurveSettingsDefault() [2/4]
void IG.Forms.VectorFunctionPlotter2d.ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LineWidth, IG.Gr.PlotZedgraphCurve.PointBorderColor, IG.Gr.PlotZedgraphCurve.PointFillColor, and IG.Gr.PlotZedgraphCurve.PointsVisible.
PlotParametricTest1d() [2/4]
void IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d () inline
plots the selected outpt dependend on the selected parameter.
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Forms.VectorFunctionPlotter2d.ApplyPlotCurveSettingsDefault(), IG.Forms.VectorFunctionPlotter2d.ApplyPlotterSettingsDefault(), IG.Forms.VectorFunctionPlotter2d.CalculateOutput(), IG.Num.VectorBase.CopyPlain(), IG.Forms.VectorFunctionPlotter2d.NumInputParameters, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.NumOutputValues, IG.Forms.VectorFunctionPlotter2d.ParameterValues, IG.Forms.VectorFunctionPlotter2d.Plotterzedgraph, IG.Gr.PlotterZedGraph.RemoveAllPlotObjects(), IG.Gr.PlotterZedGraph.ResetView(), IG.Forms.VectorFunctionPlotter2d.SelectedOutputId, IG.Forms.VectorFunctionPlotter2d.SelectedParameterId1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMax1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMin1, and IG.Gr.PlotterZedGraph.Update().
ApplySurfacePlotSettingsDefault() [2/4]
virtual void IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlotSettingsDefault (VtkSurfacePlotBase plot) inline virtual
Applies default settings to surface plots.
Parameters
plot Surface plot to which settings are applied.
References IG.Gr3d.VtkSurfacePlotBase.LineColor, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, IG.Forms.VectorFunctionPlotter2d.SurfaceColorScale, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
ApplySurfacePlottterSettingsDefault() [2/4]
virtual void IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlottterSettingsDefault (VtkPlotter plotter, int whichInput1, int whichInput2, int whichOutput) inline virtual
Applies default settings to plotter used to render 3D graphs.
Parameters
plotter 3D Plotter to which settings are applied.
References IG.Gr3d.VtkPlotter.BackGround, IG.Forms.VectorFunctionPlotter2d.chkScaled, IG.Gr3d.VtkDecorationHandler.CubeAxesFlyMode, IG.Gr3d.VtkDecorationHandler.CubeAxesXLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesYLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesZLabel, IG.Gr3d.VtkPlotter.DecorationHandler, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Gr3d.VtkDecorationHandler.LookUpTableColorScale, IG.Gr3d.VtkDecorationHandler.LookUpTableMaxRange, IG.Gr3d.VtkDecorationHandler.LookUpTableMinRange, IG.Num.BoundingBox3d.MaxZ, IG.Num.BoundingBox3d.MinZ, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Forms.VectorFunctionPlotter2d.OriginalBounds, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Gr3d.VtkDecorationHandler.ScalarBarNumberOfLabels, IG.Gr3d.VtkDecorationHandler.ScalarBarTitle, IG.Gr3d.VtkDecorationHandler.ShowCubeAxes, IG.Gr3d.VtkDecorationHandler.ShowScalarBar, IG.Forms.VectorFunctionPlotter2d.SurfaceColorScale, IG.Gr3d.VtkPlotter.WindowSizeX, and IG.Gr3d.VtkPlotter.WindowSizeY.
PlotParametricTest() [2/4]
void IG.Forms.VectorFunctionPlotter2d.PlotParametricTest () inline
plots the selected outpt dependend on the selected parameter.
References IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlotSettingsDefault(), IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlottterSettingsDefault(), IG.Forms.IndicatorLight.Blink(), IG.Forms.IndicatorLight.BlinkError(), IG.Forms.VectorFunctionPlotter2d.CalculateOutput(), IG.Forms.VectorFunctionPlotter2d.chkScaled, IG.Gr3d.VtkSurfacePlot.ClearSurfaceDefinition(), IG.Num.VectorBase.CopyPlain(), IG.Gr3d.VtkSurfacePlot.Create(), IG.Forms.VectorFunctionPlotter2d.Function, IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Num.BoundingBoxBase.Map(), IG.Num.BoundingBoxBase.Max, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Num.BoundingBoxBase.Min, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Forms.VectorFunctionPlotter2d.NumInputParameters, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2, IG.Forms.VectorFunctionPlotter2d.OriginalBounds, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Forms.VectorFunctionPlotter2d.ParameterValues, IG.Forms.VectorFunctionPlotter2d.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Gr3d.VtkPlotter.ResetCamera(), IG.Forms.VectorFunctionPlotter2d.SelectedOutputId, IG.Forms.VectorFunctionPlotter2d.SelectedParameterId1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterId2, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMax1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMax2, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMin1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMin2, IG.Forms.IndicatorLight.SetError(), IG.Forms.IndicatorLight.SetOff(), IG.Forms.IndicatorLight.SetOk(), IG.Gr3d.VtkPlotBase.ShowPlot(), IG.Num.BoundingBoxBase.ToString(), IG.Num.BoundingBox3d.Update(), and IG.Num.Vector3d.Vec.
btnParmTestStart_Click() [2/4]
void IG.Forms.VectorFunctionPlotter2d.btnParmTestStart_Click (object sender, EventArgs e) inline private
Plots the parametric test.
References IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
neuralInputSelector1_SelectedParameterIdChanged() [2/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterIdChanged (int oldId, int newId) inline private
Executes when ID of the selected first input parameter changes; Plots the parametric test.
Parameters
oldId Old ID of the selected output value (after change).
newId New ID of the selected output value (after changed).
References IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2, IG.Forms.VectorFunctionPlotter2d.NumInputParameters, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d(), IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, IG.Forms.InputParameterSelectorMinMax.SetSelectedParameterId(), and IG.Forms.VectorFunctionPlotter2d.UpdateSeclectedParametersDependencies().
neuralInputSelector1_SelectedParameterMinChanged() [2/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMinChanged (double oldValue, double newValue) inline private
Executes when minimal value of the selected first parameter changes by user interaction; Plots the parametric test.
Parameters
oldValue Old value.
newValue New value.
References IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
neuralInputSelector1_SelectedParameterMaxChanged() [2/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMaxChanged (double oldValue, double newValue) inline private
Executes when maximal value of the selected first parameter changes by user interaction; Plots the parametric test.
Parameters
oldValue Old value.
newValue New value.
References IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
neuralInputSelector2_SelectedParameterIdChanged() [2/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterIdChanged (int oldId, int newId) inline private
Executes when ID of the selected second input parameter changes; Plots the parametric test.
Parameters
oldId Old ID of the selected output value (after change).
newId New ID of the selected output value (after changed).
References IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d(), IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, IG.Forms.InputParameterSelectorMinMax.SetSelectedParameterId(), and IG.Forms.VectorFunctionPlotter2d.UpdateSeclectedParametersDependencies().
neuralInputSelector2_SelectedParameterMinChanged() [2/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMinChanged (double oldValue, double newValue) inline private
Executes when minimal value of the selected second parameter changes by user interaction; Plots the parametric test.
Parameters
oldValue Old value.
newValue New value.
References IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
neuralInputSelector2_SelectedParameterMaxChanged() [2/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMaxChanged (double oldValue, double newValue) inline private
Executes when maximal value of the selected second parameter changes by user interaction; Plots the parametric test.
Parameters
oldValue Old value.
newValue New value.
References IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
neuralOutputValueSelector1_SelectedOutputIdChanged() [2/4]
void IG.Forms.VectorFunctionPlotter2d.neuralOutputValueSelector1_SelectedOutputIdChanged (int oldId, int newId) inline private
Executes when ID of the selected output value changes; Plots the parametric test.
Parameters
oldId Old ID of the selected output value (after change).
newId New ID of the selected output value (after changed).
References IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
chkPlotImmediately_CheckedChanged() [2/4]
void IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately, and IG.Forms.VectorFunctionPlotter2d.PlotImmediately.
btnIdentifyThread_Click() [2/4]
void IG.Forms.VectorFunctionPlotter2d.btnIdentifyThread_Click (object sender, EventArgs e) inline private
References IG.Forms.UtilForms.IdentifyCurrentThread().
btnCheck_Click() [2/4]
void IG.Forms.VectorFunctionPlotter2d.btnCheck_Click (object sender, EventArgs e) inline private
References IG.Forms.FadingMessage.Launch(), IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, and IG.Num.InputOutputDataDefiniton.ToString().
btnTestFunction_Click() [2/4]
void IG.Forms.VectorFunctionPlotter2d.btnTestFunction_Click (object sender, EventArgs e) inline private
References IG.Num.InputOutputDataDefiniton.CreateDefault(), IG.Forms.VectorFunctionPlotter2d.Function, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Num.IVectorFunction.NumParameters, and IG.Num.IVectorFunction.NumValues.
numNumPlotPoints1_Validated() [2/4]
void IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, and IG.Forms.VectorFunctionPlotter2d.NumPlotPoints1.
numNumPlotPoints1_ValueChanged() [2/4]
void IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.NumPlotPoints1, and IG.Forms.VectorFunctionPlotter2d.PlotImmediatelyOnNumPointsValueChanged.
numNumPlotPoints2_Validated() [2/4]
void IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2, and IG.Forms.VectorFunctionPlotter2d.NumPlotPoints2.
numNumPlotPoints2_ValueChanged() [2/4]
void IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2, IG.Forms.VectorFunctionPlotter2d.NumPlotPoints2, and IG.Forms.VectorFunctionPlotter2d.PlotImmediatelyOnNumPointsValueChanged.
Dispose() [2/4]
override void IG.Forms.VectorFunctionPlotter2d.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.VectorFunctionPlotter2d.components.
InitializeComponent() [2/4]
void IG.Forms.VectorFunctionPlotter2d.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.VectorFunctionPlotter2d.btnCheck, IG.Forms.VectorFunctionPlotter2d.btnCheck_Click(), IG.Forms.VectorFunctionPlotter2d.btnIdentifyThread, IG.Forms.VectorFunctionPlotter2d.btnIdentifyThread_Click(), IG.Forms.VectorFunctionPlotter2d.btnParamTestStart, IG.Forms.VectorFunctionPlotter2d.btnParmTestStart_Click(), IG.Forms.VectorFunctionPlotter2d.btnTestFunction, IG.Forms.VectorFunctionPlotter2d.btnTestFunction_Click(), IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately, IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately_CheckedChanged(), IG.Forms.VectorFunctionPlotter2d.chkScaled, IG.Forms.IndicatorLight.ColorLabel, IG.Forms.VectorFunctionPlotter2d.components, IG.Forms.IndicatorLight.FlowDirection, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLight.LabelFont, IG.Forms.IndicatorLight.LabelText, IG.Forms.VectorFunctionPlotter2d.lblNumPoints, IG.Forms.VectorFunctionPlotter2d.lblNumPointsCross, IG.Forms.VectorFunctionPlotter2d.lblSelectedParameters, IG.Forms.VectorFunctionPlotter2d.lblTitleParametric2d, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.VectorFunctionPlotter2d.neuralInputControl1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter2d.neuralOutputValueSelector1, IG.Forms.VectorFunctionPlotter2d.neuralOutputValueSelector1_SelectedOutputIdChanged(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_Validated(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_ValueChanged(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_Validated(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_ValueChanged(), IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.VectorFunctionPlotter2d.ParmTestFGraph, IG.Forms.VectorFunctionPlotter2d.pnlGraph, IG.Forms.OutputValueSelector.SelectedOutputIdChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterIdChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMaxChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMinChanged, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, and IG.Forms.InputParameterSelectorMinMax.TitleParameterSelection.
CalculateOutput() [3/4]
virtual double IG.Forms.VectorFunctionPlotter2d.CalculateOutput (IVector parameters, int whichOutput) inline virtual
Calculates the specified output value of the vector function at the specified parameters.
Parameters
parameters Parameter values.
whichOutput Specifies which output value (which element of the vector function) should be calculated.
Returns
The calculated vector function component.
References IG.Forms.VectorFunctionPlotter2d._scalarFunction, IG.Forms.VectorFunctionPlotter2d.Function, IG.Forms.VectorFunctionPlotter2d.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Num.IVectorFunction.Value().
UpdateSeclectedParametersDependencies() [3/4]
void IG.Forms.VectorFunctionPlotter2d.UpdateSeclectedParametersDependencies () inline protected
References IG.Forms.VectorFunctionPlotter2d.lblSelectedParameters, IG.Forms.VectorFunctionPlotter2d.SelectedParameterId1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterId2, and IG.Forms.VectorFunctionPlotter2d.SelectedParametersIntroStr.
ApplyPlotterSettingsDefault() [3/4]
void IG.Forms.VectorFunctionPlotter2d.ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Num.InputOutputDataDefiniton.InputElementList, IG.Gr.PlotterZedGraph.IsShowPointValues, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Forms.VectorFunctionPlotter2d.SelectedOutputLabelText, IG.Forms.VectorFunctionPlotter2d.SelectedParameterLabelText, IG.Gr.PlotterZedGraph.XAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabel.
ApplyPlotCurveSettingsDefault() [3/4]
void IG.Forms.VectorFunctionPlotter2d.ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LineWidth, IG.Gr.PlotZedgraphCurve.PointBorderColor, IG.Gr.PlotZedgraphCurve.PointFillColor, and IG.Gr.PlotZedgraphCurve.PointsVisible.
PlotParametricTest1d() [3/4]
void IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d () inline
plots the selected outpt dependend on the selected parameter.
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Forms.VectorFunctionPlotter2d.ApplyPlotCurveSettingsDefault(), IG.Forms.VectorFunctionPlotter2d.ApplyPlotterSettingsDefault(), IG.Forms.VectorFunctionPlotter2d.CalculateOutput(), IG.Num.VectorBase.CopyPlain(), IG.Forms.VectorFunctionPlotter2d.NumInputParameters, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.NumOutputValues, IG.Forms.VectorFunctionPlotter2d.ParameterValues, IG.Forms.VectorFunctionPlotter2d.Plotterzedgraph, IG.Gr.PlotterZedGraph.RemoveAllPlotObjects(), IG.Gr.PlotterZedGraph.ResetView(), IG.Forms.VectorFunctionPlotter2d.SelectedOutputId, IG.Forms.VectorFunctionPlotter2d.SelectedParameterId1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMax1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMin1, and IG.Gr.PlotterZedGraph.Update().
ApplySurfacePlotSettingsDefault() [3/4]
virtual void IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlotSettingsDefault (VtkSurfacePlotBase plot) inline virtual
Applies default settings to surface plots.
Parameters
plot Surface plot to which settings are applied.
References IG.Gr3d.VtkSurfacePlotBase.LineColor, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, IG.Forms.VectorFunctionPlotter2d.SurfaceColorScale, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
ApplySurfacePlottterSettingsDefault() [3/4]
virtual void IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlottterSettingsDefault (VtkPlotter plotter, int whichInput1, int whichInput2, int whichOutput) inline virtual
Applies default settings to plotter used to render 3D graphs.
Parameters
plotter 3D Plotter to which settings are applied.
References IG.Gr3d.VtkPlotter.BackGround, IG.Forms.VectorFunctionPlotter2d.chkScaled, IG.Gr3d.VtkDecorationHandler.CubeAxesFlyMode, IG.Gr3d.VtkDecorationHandler.CubeAxesXLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesYLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesZLabel, IG.Gr3d.VtkPlotter.DecorationHandler, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Gr3d.VtkDecorationHandler.LookUpTableColorScale, IG.Gr3d.VtkDecorationHandler.LookUpTableMaxRange, IG.Gr3d.VtkDecorationHandler.LookUpTableMinRange, IG.Num.BoundingBox3d.MaxZ, IG.Num.BoundingBox3d.MinZ, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Forms.VectorFunctionPlotter2d.OriginalBounds, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Gr3d.VtkDecorationHandler.ScalarBarNumberOfLabels, IG.Gr3d.VtkDecorationHandler.ScalarBarTitle, IG.Gr3d.VtkDecorationHandler.ShowCubeAxes, IG.Gr3d.VtkDecorationHandler.ShowScalarBar, IG.Forms.VectorFunctionPlotter2d.SurfaceColorScale, IG.Gr3d.VtkPlotter.WindowSizeX, and IG.Gr3d.VtkPlotter.WindowSizeY.
PlotParametricTest() [3/4]
void IG.Forms.VectorFunctionPlotter2d.PlotParametricTest () inline
plots the selected outpt dependend on the selected parameter.
References IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlotSettingsDefault(), IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlottterSettingsDefault(), IG.Forms.IndicatorLight.BlinkError(), IG.Forms.VectorFunctionPlotter2d.CalculateOutput(), IG.Forms.VectorFunctionPlotter2d.chkScaled, IG.Gr3d.VtkSurfacePlot.ClearSurfaceDefinition(), IG.Num.VectorBase.CopyPlain(), IG.Gr3d.VtkSurfacePlot.Create(), IG.Forms.VectorFunctionPlotter2d.Function, IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Num.BoundingBoxBase.Map(), IG.Num.BoundingBoxBase.Max, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Num.BoundingBoxBase.Min, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Forms.VectorFunctionPlotter2d.NumInputParameters, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2, IG.Forms.VectorFunctionPlotter2d.OriginalBounds, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Forms.VectorFunctionPlotter2d.ParameterValues, IG.Forms.VectorFunctionPlotter2d.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Gr3d.VtkPlotter.ResetCamera(), IG.Forms.VectorFunctionPlotter2d.SelectedOutputId, IG.Forms.VectorFunctionPlotter2d.SelectedParameterId1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterId2, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMax1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMax2, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMin1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMin2, IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetOff(), IG.Forms.IndicatorLight.SetOk(), IG.Gr3d.VtkPlotBase.ShowPlot(), IG.Num.BoundingBoxBase.ToString(), IG.Num.BoundingBox3d.Update(), and IG.Num.Vector3d.Vec.
neuralInputSelector1_SelectedParameterIdChanged() [3/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterIdChanged (object sender, IndexChangeEventArgs e) inline private
Executes when ID of the selected first input parameter changes; Plots the parametric test.
Parameters
sender Control that generated the event.
e Event arguments that contain the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2, IG.Forms.VectorFunctionPlotter2d.NumInputParameters, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d(), IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, IG.Forms.InputParameterSelectorMinMax.SetSelectedParameterId(), and IG.Forms.VectorFunctionPlotter2d.UpdateSeclectedParametersDependencies().
neuralInputSelector1_SelectedParameterMinChanged() [3/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMinChanged (object sender, ValueChangeEventArgs e) inline private
Executes when minimal value of the selected first parameter changes by user interaction; Plots the parametric test.
Parameters
sender Control that generated the event.
e Event arguments that contain the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
neuralInputSelector1_SelectedParameterMaxChanged() [3/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMaxChanged (object sender, ValueChangeEventArgs e) inline private
Executes when maximal value of the selected first parameter changes by user interaction; Plots the parametric test.
Parameters
sender Control that generated the event.
e Event arguments that contain the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
neuralInputSelector2_SelectedParameterIdChanged() [3/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterIdChanged (object sender, IndexChangeEventArgs e) inline private
Executes when ID of the selected second input parameter changes; Plots the parametric test.
Parameters
sender Control that generated the event.
e Event arguments that contain the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d(), IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, IG.Forms.InputParameterSelectorMinMax.SetSelectedParameterId(), and IG.Forms.VectorFunctionPlotter2d.UpdateSeclectedParametersDependencies().
neuralInputSelector2_SelectedParameterMinChanged() [3/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMinChanged (object sender, ValueChangeEventArgs e) inline private
Executes when minimal value of the selected second parameter changes by user interaction; Plots the parametric test.
Parameters
sender Object that raised the event.
e Event arguments containing the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
neuralInputSelector2_SelectedParameterMaxChanged() [3/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMaxChanged (object sender, ValueChangeEventArgs e) inline private
Executes when maximal value of the selected second parameter changes by user interaction; Plots the parametric test.
Parameters
sender Object that raised the event.
e Event arguments containing the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
neuralOutputValueSelector1_SelectedOutputIdChanged() [3/4]
void IG.Forms.VectorFunctionPlotter2d.neuralOutputValueSelector1_SelectedOutputIdChanged (object sender, IndexChangeEventArgs e) inline private
Executes when ID of the selected output value changes; Plots the parametric test.
Parameters
sender Object that raised the event.
e Event arguments containing the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
chkPlotImmediately_CheckedChanged() [3/4]
void IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately, and IG.Forms.VectorFunctionPlotter2d.PlotImmediately.
numNumPlotPoints1_Validated() [3/4]
void IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, and IG.Forms.VectorFunctionPlotter2d.NumPlotPoints1.
numNumPlotPoints1_ValueChanged() [3/4]
void IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.NumPlotPoints1, and IG.Forms.VectorFunctionPlotter2d.PlotImmediatelyOnNumPointsValueChanged.
numNumPlotPoints2_Validated() [3/4]
void IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2, and IG.Forms.VectorFunctionPlotter2d.NumPlotPoints2.
numNumPlotPoints2_ValueChanged() [3/4]
void IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2, IG.Forms.VectorFunctionPlotter2d.NumPlotPoints2, and IG.Forms.VectorFunctionPlotter2d.PlotImmediatelyOnNumPointsValueChanged.
btnParmTestStart_Click() [3/4]
void IG.Forms.VectorFunctionPlotter2d.btnParmTestStart_Click (object sender, EventArgs e) inline private
Plots the parametric test.
References IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
btnIdentifyThread_Click() [3/4]
void IG.Forms.VectorFunctionPlotter2d.btnIdentifyThread_Click (object sender, EventArgs e) inline private
References IG.Forms.UtilForms.IdentifyCurrentThread().
btnCheck_Click() [3/4]
void IG.Forms.VectorFunctionPlotter2d.btnCheck_Click (object sender, EventArgs e) inline private
References IG.Forms.FadingMessage.Launch(), IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, and IG.Num.InputOutputDataDefiniton.ToString().
btnTestFunction_Click() [3/4]
void IG.Forms.VectorFunctionPlotter2d.btnTestFunction_Click (object sender, EventArgs e) inline private
References IG.Num.InputOutputDataDefiniton.CreateDefault(), IG.Forms.VectorFunctionPlotter2d.Function, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Num.IVectorFunction.NumParameters, and IG.Num.IVectorFunction.NumValues.
Dispose() [3/4]
override void IG.Forms.VectorFunctionPlotter2d.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.VectorFunctionPlotter2d.components.
InitializeComponent() [3/4]
void IG.Forms.VectorFunctionPlotter2d.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.VectorFunctionPlotter2d.btnCheck, IG.Forms.VectorFunctionPlotter2d.btnCheck_Click(), IG.Forms.VectorFunctionPlotter2d.btnIdentifyThread, IG.Forms.VectorFunctionPlotter2d.btnIdentifyThread_Click(), IG.Forms.VectorFunctionPlotter2d.btnParamTestStart, IG.Forms.VectorFunctionPlotter2d.btnParmTestStart_Click(), IG.Forms.VectorFunctionPlotter2d.btnTestFunction, IG.Forms.VectorFunctionPlotter2d.btnTestFunction_Click(), IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately, IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately_CheckedChanged(), IG.Forms.VectorFunctionPlotter2d.chkScaled, IG.Forms.IndicatorLight.ColorLabel, IG.Forms.VectorFunctionPlotter2d.components, IG.Forms.OutputValueSelector.DataDefinition, IG.Forms.InputParameterSelectorMinMax.DataDefinition, IG.Forms.InputParametersControl.DataDefinition, IG.Forms.IndicatorLight.FlowDirection, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLight.LabelFont, IG.Forms.IndicatorLight.LabelText, IG.Forms.VectorFunctionPlotter2d.lblNumPoints, IG.Forms.VectorFunctionPlotter2d.lblNumPointsCross, IG.Forms.VectorFunctionPlotter2d.lblSelectedParameters, IG.Forms.VectorFunctionPlotter2d.lblTitleParametric2d, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.VectorFunctionPlotter2d.neuralInputControl1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter2d.neuralOutputValueSelector1, IG.Forms.VectorFunctionPlotter2d.neuralOutputValueSelector1_SelectedOutputIdChanged(), IG.Forms.OutputValueSelector.NumInputParameters, IG.Forms.InputParameterSelectorMinMax.NumInputParameters, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_Validated(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_ValueChanged(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_Validated(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_ValueChanged(), IG.Forms.OutputValueSelector.NumOutputValues, IG.Forms.InputParameterSelectorMinMax.NumOutputValues, IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.VectorFunctionPlotter2d.ParmTestFGraph, IG.Forms.VectorFunctionPlotter2d.pnlGraph, IG.Forms.OutputValueSelector.SelectedOutputIdChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterIdChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMaxChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMinChanged, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, and IG.Forms.InputParameterSelectorMinMax.TitleParameterSelection.
CalculateOutput() [4/4]
virtual double IG.Forms.VectorFunctionPlotter2d.CalculateOutput (IVector parameters, int whichOutput) inline virtual
Calculates the specified output value of the vector function at the specified parameters.
Parameters
parameters Parameter values.
whichOutput Specifies which output value (which element of the vector function) should be calculated.
Returns
The calculated vector function component.
References IG.Forms.VectorFunctionPlotter2d._scalarFunction, IG.Forms.VectorFunctionPlotter2d.Function, IG.Forms.VectorFunctionPlotter2d.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Num.IVectorFunction.Value().
UpdateSeclectedParametersDependencies() [4/4]
void IG.Forms.VectorFunctionPlotter2d.UpdateSeclectedParametersDependencies () inline protected
References IG.Forms.VectorFunctionPlotter2d.lblSelectedParameters, IG.Forms.VectorFunctionPlotter2d.SelectedParameterId1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterId2, and IG.Forms.VectorFunctionPlotter2d.SelectedParametersIntroStr.
ApplyPlotterSettingsDefault() [4/4]
void IG.Forms.VectorFunctionPlotter2d.ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Num.InputOutputDataDefiniton.InputElementList, IG.Gr.PlotterZedGraph.IsShowPointValues, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Forms.VectorFunctionPlotter2d.SelectedOutputLabelText, IG.Forms.VectorFunctionPlotter2d.SelectedParameterLabelText, IG.Gr.PlotterZedGraph.XAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabel.
ApplyPlotCurveSettingsDefault() [4/4]
void IG.Forms.VectorFunctionPlotter2d.ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LineWidth, IG.Gr.PlotZedgraphCurve.PointBorderColor, IG.Gr.PlotZedgraphCurve.PointFillColor, and IG.Gr.PlotZedgraphCurve.PointsVisible.
PlotParametricTest1d() [4/4]
void IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d () inline
plots the selected outpt dependend on the selected parameter.
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Forms.VectorFunctionPlotter2d.ApplyPlotCurveSettingsDefault(), IG.Forms.VectorFunctionPlotter2d.ApplyPlotterSettingsDefault(), IG.Forms.VectorFunctionPlotter2d.CalculateOutput(), IG.Num.VectorBase.CopyPlain(), IG.Forms.VectorFunctionPlotter2d.NumInputParameters, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.NumOutputValues, IG.Forms.VectorFunctionPlotter2d.ParameterValues, IG.Forms.VectorFunctionPlotter2d.Plotterzedgraph, IG.Gr.PlotterZedGraph.RemoveAllPlotObjects(), IG.Gr.PlotterZedGraph.ResetView(), IG.Forms.VectorFunctionPlotter2d.SelectedOutputId, IG.Forms.VectorFunctionPlotter2d.SelectedParameterId1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMax1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMin1, and IG.Gr.PlotterZedGraph.Update().
ApplySurfacePlotSettingsDefault() [4/4]
virtual void IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlotSettingsDefault (VtkSurfacePlotBase plot) inline virtual
Applies default settings to surface plots.
Parameters
plot Surface plot to which settings are applied.
References IG.Gr3d.VtkSurfacePlotBase.LineColor, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, IG.Forms.VectorFunctionPlotter2d.SurfaceColorScale, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
ApplySurfacePlottterSettingsDefault() [4/4]
virtual void IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlottterSettingsDefault (VtkPlotter plotter, int whichInput1, int whichInput2, int whichOutput) inline virtual
Applies default settings to plotter used to render 3D graphs.
Parameters
plotter 3D Plotter to which settings are applied.
References IG.Gr3d.VtkPlotter.BackGround, IG.Forms.VectorFunctionPlotter2d.chkScaled, IG.Gr3d.VtkDecorationHandler.CubeAxesFlyMode, IG.Gr3d.VtkDecorationHandler.CubeAxesXLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesYLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesZLabel, IG.Gr3d.VtkPlotter.DecorationHandler, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Gr3d.VtkDecorationHandler.LookUpTableColorScale, IG.Gr3d.VtkDecorationHandler.LookUpTableMaxRange, IG.Gr3d.VtkDecorationHandler.LookUpTableMinRange, IG.Num.BoundingBox3d.MaxZ, IG.Num.BoundingBox3d.MinZ, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Forms.VectorFunctionPlotter2d.OriginalBounds, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Gr3d.VtkDecorationHandler.ScalarBarNumberOfLabels, IG.Gr3d.VtkDecorationHandler.ScalarBarTitle, IG.Gr3d.VtkDecorationHandler.ShowCubeAxes, IG.Gr3d.VtkDecorationHandler.ShowScalarBar, IG.Forms.VectorFunctionPlotter2d.SurfaceColorScale, IG.Gr3d.VtkPlotter.WindowSizeX, and IG.Gr3d.VtkPlotter.WindowSizeY.
PlotParametricTest() [4/4]
void IG.Forms.VectorFunctionPlotter2d.PlotParametricTest () inline
plots the selected outpt dependend on the selected parameter.
References IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlotSettingsDefault(), IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlottterSettingsDefault(), IG.Forms.IndicatorLight.BlinkError(), IG.Forms.VectorFunctionPlotter2d.CalculateOutput(), IG.Forms.VectorFunctionPlotter2d.chkScaled, IG.Gr3d.VtkSurfacePlot.ClearSurfaceDefinition(), IG.Num.VectorBase.CopyPlain(), IG.Gr3d.VtkSurfacePlot.Create(), IG.Forms.VectorFunctionPlotter2d.Function, IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Num.BoundingBoxBase.Map(), IG.Num.BoundingBoxBase.Max, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Num.BoundingBoxBase.Min, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Forms.VectorFunctionPlotter2d.NumInputParameters, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2, IG.Forms.VectorFunctionPlotter2d.OriginalBounds, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Forms.VectorFunctionPlotter2d.ParameterValues, IG.Forms.VectorFunctionPlotter2d.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Gr3d.VtkPlotter.ResetCamera(), IG.Forms.VectorFunctionPlotter2d.SelectedOutputId, IG.Forms.VectorFunctionPlotter2d.SelectedParameterId1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterId2, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMax1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMax2, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMin1, IG.Forms.VectorFunctionPlotter2d.SelectedParameterMin2, IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetOff(), IG.Forms.IndicatorLight.SetOk(), IG.Gr3d.VtkPlotBase.ShowPlot(), IG.Num.BoundingBoxBase.ToString(), IG.Num.BoundingBox3d.Update(), and IG.Num.Vector3d.Vec.
neuralInputSelector1_SelectedParameterIdChanged() [4/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterIdChanged (object sender, IndexChangeEventArgs e) inline private
Executes when ID of the selected first input parameter changes; Plots the parametric test.
Parameters
sender Control that generated the event.
e Event arguments that contain the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2, IG.Forms.VectorFunctionPlotter2d.NumInputParameters, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d(), IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, IG.Forms.InputParameterSelectorMinMax.SetSelectedParameterId(), and IG.Forms.VectorFunctionPlotter2d.UpdateSeclectedParametersDependencies().
neuralInputSelector1_SelectedParameterMinChanged() [4/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMinChanged (object sender, ValueChangeEventArgs e) inline private
Executes when minimal value of the selected first parameter changes by user interaction; Plots the parametric test.
Parameters
sender Control that generated the event.
e Event arguments that contain the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
neuralInputSelector1_SelectedParameterMaxChanged() [4/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMaxChanged (object sender, ValueChangeEventArgs e) inline private
Executes when maximal value of the selected first parameter changes by user interaction; Plots the parametric test.
Parameters
sender Control that generated the event.
e Event arguments that contain the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
neuralInputSelector2_SelectedParameterIdChanged() [4/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterIdChanged (object sender, IndexChangeEventArgs e) inline private
Executes when ID of the selected second input parameter changes; Plots the parametric test.
Parameters
sender Control that generated the event.
e Event arguments that contain the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d(), IG.Forms.InputParameterSelectorMinMax.SelectedParameterId, IG.Forms.InputParameterSelectorMinMax.SetSelectedParameterId(), and IG.Forms.VectorFunctionPlotter2d.UpdateSeclectedParametersDependencies().
neuralInputSelector2_SelectedParameterMinChanged() [4/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMinChanged (object sender, ValueChangeEventArgs e) inline private
Executes when minimal value of the selected second parameter changes by user interaction; Plots the parametric test.
Parameters
sender Object that raised the event.
e Event arguments containing the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
neuralInputSelector2_SelectedParameterMaxChanged() [4/4]
void IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMaxChanged (object sender, ValueChangeEventArgs e) inline private
Executes when maximal value of the selected second parameter changes by user interaction; Plots the parametric test.
Parameters
sender Object that raised the event.
e Event arguments containing the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
neuralOutputValueSelector1_SelectedOutputIdChanged() [4/4]
void IG.Forms.VectorFunctionPlotter2d.neuralOutputValueSelector1_SelectedOutputIdChanged (object sender, IndexChangeEventArgs e) inline private
Executes when ID of the selected output value changes; Plots the parametric test.
Parameters
sender Object that raised the event.
e Event arguments containing the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.VectorFunctionPlotter2d.PlotImmediately, IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso, IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
chkPlotImmediately_CheckedChanged() [4/4]
void IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately, and IG.Forms.VectorFunctionPlotter2d.PlotImmediately.
numNumPlotPoints1_Validated() [4/4]
void IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, and IG.Forms.VectorFunctionPlotter2d.NumPlotPoints1.
numNumPlotPoints1_ValueChanged() [4/4]
void IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.NumPlotPoints1, and IG.Forms.VectorFunctionPlotter2d.PlotImmediatelyOnNumPointsValueChanged.
numNumPlotPoints2_Validated() [4/4]
void IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2, and IG.Forms.VectorFunctionPlotter2d.NumPlotPoints2.
numNumPlotPoints2_ValueChanged() [4/4]
void IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2, IG.Forms.VectorFunctionPlotter2d.NumPlotPoints2, and IG.Forms.VectorFunctionPlotter2d.PlotImmediatelyOnNumPointsValueChanged.
btnParmTestStart_Click() [4/4]
void IG.Forms.VectorFunctionPlotter2d.btnParmTestStart_Click (object sender, EventArgs e) inline private
Plots the parametric test.
References IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
btnIdentifyThread_Click() [4/4]
void IG.Forms.VectorFunctionPlotter2d.btnIdentifyThread_Click (object sender, EventArgs e) inline private
References IG.Forms.UtilForms.IdentifyCurrentThread().
btnCheck_Click() [4/4]
void IG.Forms.VectorFunctionPlotter2d.btnCheck_Click (object sender, EventArgs e) inline private
References IG.Forms.FadingMessage.Launch(), IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, and IG.Num.InputOutputDataDefiniton.ToString().
btnTestFunction_Click() [4/4]
void IG.Forms.VectorFunctionPlotter2d.btnTestFunction_Click (object sender, EventArgs e) inline private
References IG.Num.InputOutputDataDefiniton.CreateDefault(), IG.Forms.VectorFunctionPlotter2d.Function, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Num.IVectorFunction.NumParameters, and IG.Num.IVectorFunction.NumValues.
Dispose() [4/4]
override void IG.Forms.VectorFunctionPlotter2d.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.VectorFunctionPlotter2d.components.
InitializeComponent() [4/4]
void IG.Forms.VectorFunctionPlotter2d.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.VectorFunctionPlotter2d.btnCheck, IG.Forms.VectorFunctionPlotter2d.btnCheck_Click(), IG.Forms.VectorFunctionPlotter2d.btnIdentifyThread, IG.Forms.VectorFunctionPlotter2d.btnIdentifyThread_Click(), IG.Forms.VectorFunctionPlotter2d.btnParamTestStart, IG.Forms.VectorFunctionPlotter2d.btnParmTestStart_Click(), IG.Forms.VectorFunctionPlotter2d.btnTestFunction, IG.Forms.VectorFunctionPlotter2d.btnTestFunction_Click(), IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately, IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately_CheckedChanged(), IG.Forms.VectorFunctionPlotter2d.chkScaled, IG.Forms.IndicatorLight.ColorLabel, IG.Forms.VectorFunctionPlotter2d.components, IG.Forms.OutputValueSelector.DataDefinition, IG.Forms.InputParameterSelectorMinMax.DataDefinition, IG.Forms.InputParametersControl.DataDefinition, IG.Forms.IndicatorLight.FlowDirection, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.VectorFunctionPlotter2d.indicatorLight1, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLight.LabelFont, IG.Forms.IndicatorLight.LabelText, IG.Forms.VectorFunctionPlotter2d.lblNumPoints, IG.Forms.VectorFunctionPlotter2d.lblNumPointsCross, IG.Forms.VectorFunctionPlotter2d.lblSelectedParameters, IG.Forms.VectorFunctionPlotter2d.lblTitleParametric2d, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.VectorFunctionPlotter2d.neuralInputControl1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2, IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter2d.neuralOutputValueSelector1, IG.Forms.VectorFunctionPlotter2d.neuralOutputValueSelector1_SelectedOutputIdChanged(), IG.Forms.OutputValueSelector.NumInputParameters, IG.Forms.InputParameterSelectorMinMax.NumInputParameters, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_Validated(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_ValueChanged(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2, IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_Validated(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_ValueChanged(), IG.Forms.OutputValueSelector.NumOutputValues, IG.Forms.InputParameterSelectorMinMax.NumOutputValues, IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.VectorFunctionPlotter2d.ParmTestFGraph, IG.Forms.VectorFunctionPlotter2d.pnlGraph, IG.Forms.OutputValueSelector.SelectedOutputIdChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterIdChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMaxChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMinChanged, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, and IG.Forms.InputParameterSelectorMinMax.TitleParameterSelection.
Member Data Documentation
_neuralDataDefinition
InputOutputDataDefiniton IG.Forms.VectorFunctionPlotter2d._neuralDataDefinition private
_scalarFunction
IScalarFunction IG.Forms.VectorFunctionPlotter2d._scalarFunction private
Referenced by IG.Forms.VectorFunctionPlotter2d.CalculateOutput().
_function
IVectorFunction IG.Forms.VectorFunctionPlotter2d._function private
_selectedParameterId1
int IG.Forms.VectorFunctionPlotter2d._selectedParameterId1 = 0 protected
_selectedParameterId2
int IG.Forms.VectorFunctionPlotter2d._selectedParameterId2 = 0 protected
SelectedParametersIntroStr
static string IG.Forms.VectorFunctionPlotter2d.SelectedParametersIntroStr = "Selected input parameters: " static
Referenced by IG.Forms.VectorFunctionPlotter2d.UpdateSeclectedParametersDependencies().
_selectedOutputId
int IG.Forms.VectorFunctionPlotter2d._selectedOutputId = 0 protected
_numPoints1
int IG.Forms.VectorFunctionPlotter2d._numPoints1 = 80 protected
_numPoints2
int IG.Forms.VectorFunctionPlotter2d._numPoints2 = 80 protected
_plotterZedgraph
PlotterZedGraph IG.Forms.VectorFunctionPlotter2d._plotterZedgraph private
_plotImmediately
bool IG.Forms.VectorFunctionPlotter2d._plotImmediately = false private
_plotImmediately2dAlso
bool IG.Forms.VectorFunctionPlotter2d._plotImmediately2dAlso = false private
_plotImmediatelyOnNumPointsValueChanged
bool IG.Forms.VectorFunctionPlotter2d._plotImmediatelyOnNumPointsValueChanged = true private
SurfaceColorScale
ColorScale IG.Forms.VectorFunctionPlotter2d.SurfaceColorScale protected
Referenced by IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlotSettingsDefault(), and IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlottterSettingsDefault().
OriginalBounds
BoundingBox3d IG.Forms.VectorFunctionPlotter2d.OriginalBounds protected
Referenced by IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlottterSettingsDefault(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest().
components
System ComponentModel IContainer IG.Forms.VectorFunctionPlotter2d.components = null private
Required designer variable.
Referenced by IG.Forms.VectorFunctionPlotter2d.Dispose(), and IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
neuralInputControl1 [1/2]
InputParametersControl IG.Forms.VectorFunctionPlotter2d.neuralInputControl1 private
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
pnlGraph
System Windows Forms Panel IG.Forms.VectorFunctionPlotter2d.pnlGraph private
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
numNumPlotPoints1
System Windows Forms NumericUpDown IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1 private
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_Validated(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_ValueChanged(), IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d(), and IG.Forms.VectorFunctionPlotter2d.VectorFunctionPlotter2d().
lblNumPoints
System Windows Forms Label IG.Forms.VectorFunctionPlotter2d.lblNumPoints private
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
ParmTestFGraph
ZedGraph ZedGraphControl IG.Forms.VectorFunctionPlotter2d.ParmTestFGraph private
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
btnParamTestStart
System Windows Forms Button IG.Forms.VectorFunctionPlotter2d.btnParamTestStart private
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
neuralOutputValueSelector1 [1/2]
IG Forms OutputValueSelector IG.Forms.VectorFunctionPlotter2d.neuralOutputValueSelector1 private
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
neuralInputSelector1 [1/2]
IG Forms InputParameterSelectorMinMax IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1 private
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterIdChanged(), and IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterIdChanged().
lblTitleParametric2d
System Windows Forms Label IG.Forms.VectorFunctionPlotter2d.lblTitleParametric2d private
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
neuralInputSelector2 [1/2]
IG Forms InputParameterSelectorMinMax IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2 private
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterIdChanged(), and IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterIdChanged().
numNumPlotPoints2
System Windows Forms NumericUpDown IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2 private
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_Validated(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_ValueChanged(), IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.VectorFunctionPlotter2d().
lblNumPointsCross
System Windows Forms Label IG.Forms.VectorFunctionPlotter2d.lblNumPointsCross private
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
lblSelectedParameters
System Windows Forms Label IG.Forms.VectorFunctionPlotter2d.lblSelectedParameters private
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), and IG.Forms.VectorFunctionPlotter2d.UpdateSeclectedParametersDependencies().
chkScaled
System Windows Forms CheckBox IG.Forms.VectorFunctionPlotter2d.chkScaled private
Referenced by IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlottterSettingsDefault(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest().
indicatorLight1
IG Forms IndicatorLight IG.Forms.VectorFunctionPlotter2d.indicatorLight1 private
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter2d.neuralOutputValueSelector1_SelectedOutputIdChanged(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest().
chkPlotImmediately
System Windows Forms CheckBox IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately private
Referenced by IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately_CheckedChanged(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), and IG.Forms.VectorFunctionPlotter2d.VectorFunctionPlotter2d().
btnIdentifyThread
System Windows Forms Button IG.Forms.VectorFunctionPlotter2d.btnIdentifyThread private
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
btnCheck
System Windows Forms Button IG.Forms.VectorFunctionPlotter2d.btnCheck private
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
btnTestFunction
System Windows Forms Button IG.Forms.VectorFunctionPlotter2d.btnTestFunction private
Referenced by IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
neuralInputControl1 [2/2]
NeuralInputControl IG.Forms.VectorFunctionPlotter2d.neuralInputControl1 private
neuralOutputValueSelector1 [2/2]
IG.Forms.NeuralOutputValueSelector IG.Forms.VectorFunctionPlotter2d.neuralOutputValueSelector1 private
neuralInputSelector1 [2/2]
IG.Forms.NeuralInputParameterSelectorMinMax IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1 private
neuralInputSelector2 [2/2]
IG.Forms.NeuralInputParameterSelectorMinMax IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2 private
Property Documentation
Reporter
IReporter IG.Forms.VectorFunctionPlotter2d.Reporter get private
Reorter used for launching info, warning and error reports.
Referenced by IG.Forms.VectorFunctionPlotter2d.CalculateOutput(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest().
NeuralDataDefinition
InputOutputDataDefiniton IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition get set
Data about input and output quantities of the manipulated functions or response.
Referenced by IG.Forms.VectorFunctionPlotter2d.ApplyPlotterSettingsDefault(), IG.Forms.VectorFunctionPlotter2d.ApplySurfacePlottterSettingsDefault(), IG.Forms.VectorFunctionPlotter2d.btnCheck_Click(), IG.Forms.VectorFunctionScriptControl.btnPlot2d_Click(), IG.Forms.ScalarFunctionScriptControl.btnPlot2d_Click(), IG.Forms.VectorFunctionPlotter2d.btnTestFunction_Click(), IG.Forms.VectorFunctionPlotter2dForm.InitializeComponent(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest().
ScalarFunction
IScalarFunction IG.Forms.VectorFunctionPlotter2d.ScalarFunction set
Referenced by IG.Forms.ScalarFunctionScriptControl.btnPlot2d_Click().
Function
IVectorFunction IG.Forms.VectorFunctionPlotter2d.Function get set
Referenced by IG.Forms.VectorFunctionScriptControl.btnPlot2d_Click(), IG.Forms.VectorFunctionPlotter2d.btnTestFunction_Click(), IG.Forms.VectorFunctionPlotter2d.CalculateOutput(), IG.Forms.VectorFunctionPlotter2dForm.InitializeComponent(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest().
NumInputParameters
int IG.Forms.VectorFunctionPlotter2d.NumInputParameters get
Gets number of input parameters.
Referenced by IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
NumOutputValues
int IG.Forms.VectorFunctionPlotter2d.NumOutputValues get
Gets number of output values.
Referenced by IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
ParameterValues
IVector IG.Forms.VectorFunctionPlotter2d.ParameterValues get
Vector of current values of input parameters as defined by the DadaGridView.
Referenced by IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
MinValues
double [] IG.Forms.VectorFunctionPlotter2d.MinValues get
Minimal values of parameters.
MaxValues
double [] IG.Forms.VectorFunctionPlotter2d.MaxValues get
Maximal values of parameters.
SelectedParameterId1
int IG.Forms.VectorFunctionPlotter2d.SelectedParameterId1 get protected set
Sequential number of the selected first parameter as specified by the user.
Referenced by IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d(), and IG.Forms.VectorFunctionPlotter2d.UpdateSeclectedParametersDependencies().
SelectedParameterMin1
double IG.Forms.VectorFunctionPlotter2d.SelectedParameterMin1 get
Minimal value of the selected first parameter.
Referenced by IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
SelectedParameterMax1
double IG.Forms.VectorFunctionPlotter2d.SelectedParameterMax1 get
Maximal value of the selected first parameter as specified by the user.
Referenced by IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
SelectedParameterId2
int IG.Forms.VectorFunctionPlotter2d.SelectedParameterId2 get protected set
Sequential number of the selected second parameter as specified by the user.
Referenced by IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.UpdateSeclectedParametersDependencies().
SelectedParameterMin2
double IG.Forms.VectorFunctionPlotter2d.SelectedParameterMin2 get
Minimal value of the selected second parameter.
Referenced by IG.Forms.VectorFunctionPlotter2d.PlotParametricTest().
SelectedParameterMax2
double IG.Forms.VectorFunctionPlotter2d.SelectedParameterMax2 get
Maximal value of the selected second parameter as specified by the user.
Referenced by IG.Forms.VectorFunctionPlotter2d.PlotParametricTest().
SelectedOutputId
int IG.Forms.VectorFunctionPlotter2d.SelectedOutputId get protected set
Referenced by IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
NumPlotPoints1
int IG.Forms.VectorFunctionPlotter2d.NumPlotPoints1 get set
Number of plotting points in the 1st direction.
Referenced by IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_Validated(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_ValueChanged(), and IG.Forms.VectorFunctionPlotter2d.VectorFunctionPlotter2d().
NumPlotPoints2
int IG.Forms.VectorFunctionPlotter2d.NumPlotPoints2 get set
Number of plotting points in the 2nd direction.
Referenced by IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_Validated(), IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_ValueChanged(), and IG.Forms.VectorFunctionPlotter2d.VectorFunctionPlotter2d().
SelectedParameterLabelText
string IG.Forms.VectorFunctionPlotter2d.SelectedParameterLabelText get
Gets axis label text for the currently selected parameter.
Referenced by IG.Forms.VectorFunctionPlotter2d.ApplyPlotterSettingsDefault().
SelectedOutputLabelText
string IG.Forms.VectorFunctionPlotter2d.SelectedOutputLabelText get
Gets axis label text for the currently selected output value.
Referenced by IG.Forms.VectorFunctionPlotter2d.ApplyPlotterSettingsDefault().
Plotterzedgraph
PlotterZedGraph IG.Forms.VectorFunctionPlotter2d.Plotterzedgraph get
Plotter that is used for plotting the graphs.
Referenced by IG.Forms.VectorFunctionPlotter2d.PlotParametricTest1d().
PlotImmediately
bool IG.Forms.VectorFunctionPlotter2d.PlotImmediately get set
If true then graph is pletted immediately when any parameter changes that affects it appearance.
Referenced by IG.Forms.VectorFunctionPlotter2d.chkPlotImmediately_CheckedChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter2d.neuralOutputValueSelector1_SelectedOutputIdChanged(), and IG.Forms.VectorFunctionPlotter2d.VectorFunctionPlotter2d().
PlotImmediately2dAlso
bool IG.Forms.VectorFunctionPlotter2d.PlotImmediately2dAlso get set
Referenced by IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMinChanged(), and IG.Forms.VectorFunctionPlotter2d.neuralOutputValueSelector1_SelectedOutputIdChanged().
PlotImmediatelyOnNumPointsValueChanged
bool IG.Forms.VectorFunctionPlotter2d.PlotImmediatelyOnNumPointsValueChanged get set
Referenced by IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints1_ValueChanged(), and IG.Forms.VectorFunctionPlotter2d.numNumPlotPoints2_ValueChanged().
The documentation for this class was generated from the following files:
iglib/extensions/iglibext/Forms/Numeric/FromNeural/VectorFunctionPlotter2d.cs
iglib/extensions/iglibext/Forms/Numeric/FromNeural/VectorFunctionPlotter2d.Designer.cs