Doc: IGLib EXTENDED: NUnit.ConsoleRunner.Tests.CommandLineTests Class Reference
NUnit.ConsoleRunner.Tests.CommandLineTests Class Reference
Classes
class DefaultOptionsProviderStub
Public Member Functions
void NoInputFiles ()
void CanRecognizeBooleanOptions (string propertyName, string pattern)
void CanRecognizeStringOptions (string propertyName, string pattern, string[] goodValues, string[] badValues)
void CanRegognizeInProcessOption ()
void CanRecognizeLowerCaseOptionValues (string propertyName, string optionName, string[] canonicalValues)
void CanRecognizeIntOptions (string propertyName, string pattern)
void MissingValuesAreReported (string option)
void AssemblyName ()
void AssemblyAloneIsValid ()
void InvalidOption ()
void InvalidCommandLineParms ()
void TimeoutIsMinusOneIfNoOptionIsProvided ()
void TimeoutThrowsExceptionIfOptionHasNoValue ()
void TimeoutParsesIntValueCorrectly ()
void TimeoutCausesErrorIfValueIsNotInteger ()
void ResultOptionWithFilePath ()
void ResultOptionWithFilePathAndFormat ()
void ResultOptionWithFilePathAndTransform ()
void FileNameWithoutResultOptionLooksLikeParameter ()
void ResultOptionWithoutFileNameIsInvalid ()
void ResultOptionMayBeRepeated ()
void DefaultResultSpecification ()
void NoResultSuppressesDefaultResultSpecification ()
void NoResultSuppressesAllResultSpecifications ()
void ExploreOptionWithoutPath ()
void ExploreOptionWithFilePath ()
void ExploreOptionWithFilePathAndFormat ()
void ExploreOptionWithFilePathAndTransform ()
void ExploreOptionWithFilePathUsingEqualSign ()
void ShouldSetTeamCityFlagAccordingToArgsAndDefauls (bool hasTeamcityInCmd, bool? defaultTeamcity, bool expectedTeamCity)
Static Private Member Functions
static FieldInfo GetFieldInfo (string fieldName)
static PropertyInfo GetPropertyInfo (string propertyName)
Member Function Documentation
NoInputFiles()
void NUnit.ConsoleRunner.Tests.CommandLineTests.NoInputFiles () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.CommandLineOptions.InputFiles, NUnit.Framework.Assert.True(), and NUnit.Common.CommandLineOptions.Validate().
CanRecognizeBooleanOptions()
void NUnit.ConsoleRunner.Tests.CommandLineTests.CanRecognizeBooleanOptions (string propertyName, string pattern) inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.ConsoleRunner.Tests.CommandLineTests.GetPropertyInfo().
CanRecognizeStringOptions()
void NUnit.ConsoleRunner.Tests.CommandLineTests.CanRecognizeStringOptions (string propertyName, string pattern, string[] goodValues, string[] badValues) inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Assert.False(), NUnit.ConsoleRunner.Tests.CommandLineTests.GetPropertyInfo(), NUnit.Framework.Assert.True(), and NUnit.Common.CommandLineOptions.Validate().
CanRegognizeInProcessOption()
void NUnit.ConsoleRunner.Tests.CommandLineTests.CanRegognizeInProcessOption () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.ConsoleOptions.ProcessModel, NUnit.Framework.Assert.True(), and NUnit.Common.CommandLineOptions.Validate().
CanRecognizeLowerCaseOptionValues()
void NUnit.ConsoleRunner.Tests.CommandLineTests.CanRecognizeLowerCaseOptionValues (string propertyName, string optionName, string[] canonicalValues) inline
References NUnit.Framework.Assert.AreEqual(), NUnit.ConsoleRunner.Tests.CommandLineTests.GetPropertyInfo(), NUnit.Framework.Assert.True(), and NUnit.Common.CommandLineOptions.Validate().
CanRecognizeIntOptions()
void NUnit.ConsoleRunner.Tests.CommandLineTests.CanRecognizeIntOptions (string propertyName, string pattern) inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.ConsoleRunner.Tests.CommandLineTests.GetPropertyInfo().
MissingValuesAreReported()
void NUnit.ConsoleRunner.Tests.CommandLineTests.MissingValuesAreReported (string option) inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.CommandLineOptions.ErrorMessages, NUnit.Framework.Assert.False(), and NUnit.Common.CommandLineOptions.Validate().
AssemblyName()
void NUnit.ConsoleRunner.Tests.CommandLineTests.AssemblyName () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.CommandLineOptions.InputFiles, NUnit.Framework.Assert.True(), and NUnit.Common.CommandLineOptions.Validate().
AssemblyAloneIsValid()
void NUnit.ConsoleRunner.Tests.CommandLineTests.AssemblyAloneIsValid () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.CommandLineOptions.ErrorMessages, NUnit.Framework.Assert.True(), and NUnit.Common.CommandLineOptions.Validate().
InvalidOption()
void NUnit.ConsoleRunner.Tests.CommandLineTests.InvalidOption () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.CommandLineOptions.ErrorMessages, NUnit.Framework.Assert.False(), and NUnit.Common.CommandLineOptions.Validate().
InvalidCommandLineParms()
void NUnit.ConsoleRunner.Tests.CommandLineTests.InvalidCommandLineParms () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.CommandLineOptions.ErrorMessages, NUnit.Framework.Assert.False(), and NUnit.Common.CommandLineOptions.Validate().
TimeoutIsMinusOneIfNoOptionIsProvided()
void NUnit.ConsoleRunner.Tests.CommandLineTests.TimeoutIsMinusOneIfNoOptionIsProvided () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.CommandLineOptions.DefaultTimeout, NUnit.Framework.Assert.True(), and NUnit.Common.CommandLineOptions.Validate().
TimeoutThrowsExceptionIfOptionHasNoValue()
void NUnit.ConsoleRunner.Tests.CommandLineTests.TimeoutThrowsExceptionIfOptionHasNoValue () inline
References NUnit.Framework.Assert.Throws().
TimeoutParsesIntValueCorrectly()
void NUnit.ConsoleRunner.Tests.CommandLineTests.TimeoutParsesIntValueCorrectly () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.CommandLineOptions.DefaultTimeout, NUnit.Framework.Assert.True(), and NUnit.Common.CommandLineOptions.Validate().
TimeoutCausesErrorIfValueIsNotInteger()
void NUnit.ConsoleRunner.Tests.CommandLineTests.TimeoutCausesErrorIfValueIsNotInteger () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.CommandLineOptions.DefaultTimeout, NUnit.Framework.Assert.False(), and NUnit.Common.CommandLineOptions.Validate().
ResultOptionWithFilePath()
void NUnit.ConsoleRunner.Tests.CommandLineTests.ResultOptionWithFilePath () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.OutputSpecification.Format, NUnit.Common.CommandLineOptions.InputFiles, NUnit.Framework.Assert.Null(), NUnit.Common.OutputSpecification.OutputPath, NUnit.Common.CommandLineOptions.ResultOutputSpecifications, NUnit.Common.OutputSpecification.Transform, NUnit.Framework.Assert.True(), and NUnit.Common.CommandLineOptions.Validate().
ResultOptionWithFilePathAndFormat()
void NUnit.ConsoleRunner.Tests.CommandLineTests.ResultOptionWithFilePathAndFormat () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.OutputSpecification.Format, NUnit.Common.CommandLineOptions.InputFiles, NUnit.Framework.Assert.Null(), NUnit.Common.OutputSpecification.OutputPath, NUnit.Common.CommandLineOptions.ResultOutputSpecifications, NUnit.Common.OutputSpecification.Transform, NUnit.Framework.Assert.True(), and NUnit.Common.CommandLineOptions.Validate().
ResultOptionWithFilePathAndTransform()
void NUnit.ConsoleRunner.Tests.CommandLineTests.ResultOptionWithFilePathAndTransform () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.OutputSpecification.Format, NUnit.Common.CommandLineOptions.InputFiles, NUnit.Common.OutputSpecification.OutputPath, NUnit.Common.CommandLineOptions.ResultOutputSpecifications, NUnit.Common.OutputSpecification.Transform, NUnit.Framework.Assert.True(), and NUnit.Common.CommandLineOptions.Validate().
FileNameWithoutResultOptionLooksLikeParameter()
void NUnit.ConsoleRunner.Tests.CommandLineTests.FileNameWithoutResultOptionLooksLikeParameter () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.CommandLineOptions.ErrorMessages, NUnit.Common.CommandLineOptions.InputFiles, NUnit.Framework.Assert.True(), and NUnit.Common.CommandLineOptions.Validate().
ResultOptionWithoutFileNameIsInvalid()
void NUnit.ConsoleRunner.Tests.CommandLineTests.ResultOptionWithoutFileNameIsInvalid () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.CommandLineOptions.ErrorMessages, NUnit.Framework.Assert.False(), and NUnit.Common.CommandLineOptions.Validate().
ResultOptionMayBeRepeated()
void NUnit.ConsoleRunner.Tests.CommandLineTests.ResultOptionMayBeRepeated () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Assert.Null(), NUnit.Common.CommandLineOptions.ResultOutputSpecifications, NUnit.Framework.Assert.True(), and NUnit.Common.CommandLineOptions.Validate().
DefaultResultSpecification()
void NUnit.ConsoleRunner.Tests.CommandLineTests.DefaultResultSpecification () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.Null().
NoResultSuppressesDefaultResultSpecification()
void NUnit.ConsoleRunner.Tests.CommandLineTests.NoResultSuppressesDefaultResultSpecification () inline
References NUnit.Framework.Assert.AreEqual().
NoResultSuppressesAllResultSpecifications()
void NUnit.ConsoleRunner.Tests.CommandLineTests.NoResultSuppressesAllResultSpecifications () inline
References NUnit.Framework.Assert.AreEqual().
ExploreOptionWithoutPath()
void NUnit.ConsoleRunner.Tests.CommandLineTests.ExploreOptionWithoutPath () inline
References NUnit.Common.CommandLineOptions.Explore, NUnit.Framework.Assert.True(), and NUnit.Common.CommandLineOptions.Validate().
ExploreOptionWithFilePath()
void NUnit.ConsoleRunner.Tests.CommandLineTests.ExploreOptionWithFilePath () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.CommandLineOptions.Explore, NUnit.Common.CommandLineOptions.ExploreOutputSpecifications, NUnit.Common.OutputSpecification.Format, NUnit.Common.CommandLineOptions.InputFiles, NUnit.Framework.Assert.Null(), NUnit.Common.OutputSpecification.OutputPath, NUnit.Common.OutputSpecification.Transform, NUnit.Framework.Assert.True(), and NUnit.Common.CommandLineOptions.Validate().
ExploreOptionWithFilePathAndFormat()
void NUnit.ConsoleRunner.Tests.CommandLineTests.ExploreOptionWithFilePathAndFormat () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.CommandLineOptions.Explore, NUnit.Common.CommandLineOptions.ExploreOutputSpecifications, NUnit.Common.OutputSpecification.Format, NUnit.Common.CommandLineOptions.InputFiles, NUnit.Framework.Assert.Null(), NUnit.Common.OutputSpecification.OutputPath, NUnit.Common.OutputSpecification.Transform, NUnit.Framework.Assert.True(), and NUnit.Common.CommandLineOptions.Validate().
ExploreOptionWithFilePathAndTransform()
void NUnit.ConsoleRunner.Tests.CommandLineTests.ExploreOptionWithFilePathAndTransform () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.CommandLineOptions.Explore, NUnit.Common.CommandLineOptions.ExploreOutputSpecifications, NUnit.Common.OutputSpecification.Format, NUnit.Common.CommandLineOptions.InputFiles, NUnit.Common.OutputSpecification.OutputPath, NUnit.Common.OutputSpecification.Transform, NUnit.Framework.Assert.True(), and NUnit.Common.CommandLineOptions.Validate().
ExploreOptionWithFilePathUsingEqualSign()
void NUnit.ConsoleRunner.Tests.CommandLineTests.ExploreOptionWithFilePathUsingEqualSign () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.CommandLineOptions.Explore, NUnit.Common.CommandLineOptions.ExploreOutputSpecifications, NUnit.Common.CommandLineOptions.InputFiles, NUnit.Framework.Assert.True(), and NUnit.Common.CommandLineOptions.Validate().
ShouldSetTeamCityFlagAccordingToArgsAndDefauls()
void NUnit.ConsoleRunner.Tests.CommandLineTests.ShouldSetTeamCityFlagAccordingToArgsAndDefauls (bool hasTeamcityInCmd, bool? defaultTeamcity, bool expectedTeamCity) inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Common.CommandLineOptions.TeamCity.
GetFieldInfo()
static FieldInfo NUnit.ConsoleRunner.Tests.CommandLineTests.GetFieldInfo (string fieldName) inline static private
References NUnit.Framework.Assert.IsNotNull().
GetPropertyInfo()
static PropertyInfo NUnit.ConsoleRunner.Tests.CommandLineTests.GetPropertyInfo (string propertyName) inline static private
References NUnit.Framework.Assert.IsNotNull().
Referenced by NUnit.ConsoleRunner.Tests.CommandLineTests.CanRecognizeBooleanOptions(), NUnit.ConsoleRunner.Tests.CommandLineTests.CanRecognizeIntOptions(), NUnit.ConsoleRunner.Tests.CommandLineTests.CanRecognizeLowerCaseOptionValues(), and NUnit.ConsoleRunner.Tests.CommandLineTests.CanRecognizeStringOptions().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitConsole/nunit3-console.tests/CommandLineTests.cs