Doc: IGLib EXTENDED: CShell.Framework.Results.SaveDocumentResult Class Reference
CShell.Framework.Results.SaveDocumentResult Class Reference
Public Member Functions
SaveDocumentResult (IDocument document)
SaveDocumentResult (IDocument document, string newFile)
override void Execute (ActionExecutionContext context)
Private Attributes
IDocument document
string newFile
Additional Inherited Members
Protected Member Functions inherited from CShell.Framework.Results.ResultBase
virtual void OnCompleted (Exception exception)
virtual void OnCompleted (Exception exception, bool wasCancelled)
Events inherited from CShell.Framework.Results.ResultBase
EventHandler< ResultCompletionEventArgs > Completed
Constructor & Destructor Documentation
SaveDocumentResult() [1/2]
CShell.Framework.Results.SaveDocumentResult.SaveDocumentResult (IDocument document) inline
References CShell.Framework.Results.SaveDocumentResult.document.
SaveDocumentResult() [2/2]
CShell.Framework.Results.SaveDocumentResult.SaveDocumentResult (IDocument document, string newFile) inline
References CShell.Framework.Results.SaveDocumentResult.newFile.
Member Function Documentation
Execute()
override void CShell.Framework.Results.SaveDocumentResult.Execute (ActionExecutionContext context) inline virtual
Implements CShell.Framework.Results.ResultBase.
References CShell.Framework.Results.SaveDocumentResult.document, CShell.Framework.IDocument.IsDirty, CShell.Framework.Results.SaveDocumentResult.newFile, CShell.Framework.Results.ResultBase.OnCompleted(), CShell.Framework.IDocument.Save(), and CShell.Framework.IDocument.SaveAs().
Member Data Documentation
document
IDocument CShell.Framework.Results.SaveDocumentResult.document private
Referenced by CShell.Framework.Results.SaveDocumentResult.Execute(), and CShell.Framework.Results.SaveDocumentResult.SaveDocumentResult().
newFile
string CShell.Framework.Results.SaveDocumentResult.newFile private
Referenced by CShell.Framework.Results.SaveDocumentResult.Execute(), and CShell.Framework.Results.SaveDocumentResult.SaveDocumentResult().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore/Framework/Results/SaveDocumentResult.cs