Doc: IGLib EXTENDED: AForge.Math.Geometry.Tests.ShapeOptimizerTestBase Class Reference
AForge.Math.Geometry.Tests.ShapeOptimizerTestBase Class Reference
Static Public Member Functions
static void TestOptimizer (int[] coordinates, int[] expectedCoordinates, IShapeOptimizer optimizer)
Member Function Documentation
TestOptimizer()
static void AForge.Math.Geometry.Tests.ShapeOptimizerTestBase.TestOptimizer (int[] coordinates, int[] expectedCoordinates, IShapeOptimizer optimizer) inline static
References AForge.Math.Geometry.IShapeOptimizer.OptimizeShape().
Referenced by AForge.Math.Geometry.Tests.ClosePointsMergingOptimizerTest.OptimizationTest(), AForge.Math.Geometry.Tests.FlatAnglesOptimizerTest.OptimizationTest(), and AForge.Math.Geometry.Tests.LineStraighteningOptimizerTest.OptimizationTest().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Unit Tests/AForge.Math.Tests/Geometry/ShapeOptimizerTestBase.cs