Doc: IGLib EXTENDED: IG.Forms.Test.ColorConverterForm Class Reference
IG.Forms.Test.ColorConverterForm Class Reference
Public Member Functions
ColorConverterForm ()
ColorConverterForm ()
Static Public Member Functions
static void Main0 ()
static void Main0 ()
Private Member Functions
void parseRGB ()
void tbRed_TextChanged (object sender, EventArgs e)
void tbGreen_TextChanged (object sender, EventArgs e)
void tbBlue_TextChanged (object sender, EventArgs e)
void Form1_Paint (object sender, PaintEventArgs e)
void InitializeComponent ()
void parseRGB ()
void tbRed_TextChanged (object sender, EventArgs e)
void tbGreen_TextChanged (object sender, EventArgs e)
void tbBlue_TextChanged (object sender, EventArgs e)
void Form1_Paint (object sender, PaintEventArgs e)
void InitializeComponent ()
Private Attributes
Color theColor
System.Windows.Forms.TextBox tbRed
System.Windows.Forms.TextBox tbGreen
System.Windows.Forms.Label label1
System.Windows.Forms.Label label2
System.Windows.Forms.Label label3
System.Windows.Forms.TextBox tbBlue
System.Windows.Forms.TextBox tbHue
System.Windows.Forms.TextBox tbSat
System.Windows.Forms.Label label4
System.Windows.Forms.Label label5
System.Windows.Forms.Label label6
System.Windows.Forms.TextBox tbBright
Constructor & Destructor Documentation
ColorConverterForm() [1/2]
IG.Forms.Test.ColorConverterForm.ColorConverterForm () inline
References IG.Forms.Test.ColorConverterForm.InitializeComponent(), IG.Forms.Test.ColorConverterForm.tbBlue, IG.Forms.Test.ColorConverterForm.tbGreen, and IG.Forms.Test.ColorConverterForm.tbRed.
Referenced by IG.Forms.Test.ColorConverterForm.Main0().
ColorConverterForm() [2/2]
IG.Forms.Test.ColorConverterForm.ColorConverterForm () inline
References IG.Forms.Test.ColorConverterForm.InitializeComponent(), IG.Forms.Test.ColorConverterForm.tbBlue, IG.Forms.Test.ColorConverterForm.tbGreen, and IG.Forms.Test.ColorConverterForm.tbRed.
Member Function Documentation
Main0() [1/2]
static void IG.Forms.Test.ColorConverterForm.Main0 () inline static
References IG.Forms.Test.ColorConverterForm.ColorConverterForm().
Referenced by IG.Forms.Test.IgFormsQickTests.Main().
parseRGB() [1/2]
void IG.Forms.Test.ColorConverterForm.parseRGB () inline private
References IG.Forms.Test.ColorConverterForm.tbBlue, IG.Forms.Test.ColorConverterForm.tbBright, IG.Forms.Test.ColorConverterForm.tbGreen, IG.Forms.Test.ColorConverterForm.tbHue, IG.Forms.Test.ColorConverterForm.tbRed, IG.Forms.Test.ColorConverterForm.tbSat, and IG.Forms.Test.ColorConverterForm.theColor.
Referenced by IG.Forms.Test.ColorConverterForm.tbBlue_TextChanged(), IG.Forms.Test.ColorConverterForm.tbGreen_TextChanged(), and IG.Forms.Test.ColorConverterForm.tbRed_TextChanged().
tbRed_TextChanged() [1/2]
void IG.Forms.Test.ColorConverterForm.tbRed_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.Test.ColorConverterForm.parseRGB().
Referenced by IG.Forms.Test.ColorConverterForm.InitializeComponent().
tbGreen_TextChanged() [1/2]
void IG.Forms.Test.ColorConverterForm.tbGreen_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.Test.ColorConverterForm.parseRGB().
Referenced by IG.Forms.Test.ColorConverterForm.InitializeComponent().
tbBlue_TextChanged() [1/2]
void IG.Forms.Test.ColorConverterForm.tbBlue_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.Test.ColorConverterForm.parseRGB().
Referenced by IG.Forms.Test.ColorConverterForm.InitializeComponent().
Form1_Paint() [1/2]
void IG.Forms.Test.ColorConverterForm.Form1_Paint (object sender, PaintEventArgs e) inline private
References IG.Forms.Test.ColorConverterForm.theColor.
Referenced by IG.Forms.Test.ColorConverterForm.InitializeComponent().
InitializeComponent() [1/2]
void IG.Forms.Test.ColorConverterForm.InitializeComponent () inline private
References IG.Forms.Test.ColorConverterForm.Form1_Paint(), IG.Forms.Test.ColorConverterForm.label1, IG.Forms.Test.ColorConverterForm.label2, IG.Forms.Test.ColorConverterForm.label3, IG.Forms.Test.ColorConverterForm.label4, IG.Forms.Test.ColorConverterForm.label5, IG.Forms.Test.ColorConverterForm.label6, IG.Forms.Test.ColorConverterForm.tbBlue, IG.Forms.Test.ColorConverterForm.tbBlue_TextChanged(), IG.Forms.Test.ColorConverterForm.tbBright, IG.Forms.Test.ColorConverterForm.tbGreen, IG.Forms.Test.ColorConverterForm.tbGreen_TextChanged(), IG.Forms.Test.ColorConverterForm.tbHue, IG.Forms.Test.ColorConverterForm.tbRed, IG.Forms.Test.ColorConverterForm.tbRed_TextChanged(), and IG.Forms.Test.ColorConverterForm.tbSat.
Referenced by IG.Forms.Test.ColorConverterForm.ColorConverterForm().
Main0() [2/2]
static void IG.Forms.Test.ColorConverterForm.Main0 () inline static
References IG.Forms.Test.ColorConverterForm.ColorConverterForm().
parseRGB() [2/2]
void IG.Forms.Test.ColorConverterForm.parseRGB () inline private
References IG.Forms.Test.ColorConverterForm.tbBlue, IG.Forms.Test.ColorConverterForm.tbBright, IG.Forms.Test.ColorConverterForm.tbGreen, IG.Forms.Test.ColorConverterForm.tbHue, IG.Forms.Test.ColorConverterForm.tbRed, IG.Forms.Test.ColorConverterForm.tbSat, and IG.Forms.Test.ColorConverterForm.theColor.
tbRed_TextChanged() [2/2]
void IG.Forms.Test.ColorConverterForm.tbRed_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.Test.ColorConverterForm.parseRGB().
tbGreen_TextChanged() [2/2]
void IG.Forms.Test.ColorConverterForm.tbGreen_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.Test.ColorConverterForm.parseRGB().
tbBlue_TextChanged() [2/2]
void IG.Forms.Test.ColorConverterForm.tbBlue_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.Test.ColorConverterForm.parseRGB().
Form1_Paint() [2/2]
void IG.Forms.Test.ColorConverterForm.Form1_Paint (object sender, PaintEventArgs e) inline private
References IG.Forms.Test.ColorConverterForm.theColor.
InitializeComponent() [2/2]
void IG.Forms.Test.ColorConverterForm.InitializeComponent () inline private
References IG.Forms.Test.ColorConverterForm.Form1_Paint(), IG.Forms.Test.ColorConverterForm.label1, IG.Forms.Test.ColorConverterForm.label2, IG.Forms.Test.ColorConverterForm.label3, IG.Forms.Test.ColorConverterForm.label4, IG.Forms.Test.ColorConverterForm.label5, IG.Forms.Test.ColorConverterForm.label6, IG.Forms.Test.ColorConverterForm.tbBlue, IG.Forms.Test.ColorConverterForm.tbBlue_TextChanged(), IG.Forms.Test.ColorConverterForm.tbBright, IG.Forms.Test.ColorConverterForm.tbGreen, IG.Forms.Test.ColorConverterForm.tbGreen_TextChanged(), IG.Forms.Test.ColorConverterForm.tbHue, IG.Forms.Test.ColorConverterForm.tbRed, IG.Forms.Test.ColorConverterForm.tbRed_TextChanged(), and IG.Forms.Test.ColorConverterForm.tbSat.
Member Data Documentation
theColor
Color IG.Forms.Test.ColorConverterForm.theColor private
Referenced by IG.Forms.Test.ColorConverterForm.Form1_Paint(), and IG.Forms.Test.ColorConverterForm.parseRGB().
tbRed
System Windows Forms TextBox IG.Forms.Test.ColorConverterForm.tbRed private
Referenced by IG.Forms.Test.ColorConverterForm.ColorConverterForm(), IG.Forms.Test.ColorConverterForm.InitializeComponent(), and IG.Forms.Test.ColorConverterForm.parseRGB().
tbGreen
System Windows Forms TextBox IG.Forms.Test.ColorConverterForm.tbGreen private
Referenced by IG.Forms.Test.ColorConverterForm.ColorConverterForm(), IG.Forms.Test.ColorConverterForm.InitializeComponent(), and IG.Forms.Test.ColorConverterForm.parseRGB().
label1
System Windows Forms Label IG.Forms.Test.ColorConverterForm.label1 private
Referenced by IG.Forms.Test.ColorConverterForm.InitializeComponent().
label2
System Windows Forms Label IG.Forms.Test.ColorConverterForm.label2 private
Referenced by IG.Forms.Test.ColorConverterForm.InitializeComponent().
label3
System Windows Forms Label IG.Forms.Test.ColorConverterForm.label3 private
Referenced by IG.Forms.Test.ColorConverterForm.InitializeComponent().
tbBlue
System Windows Forms TextBox IG.Forms.Test.ColorConverterForm.tbBlue private
Referenced by IG.Forms.Test.ColorConverterForm.ColorConverterForm(), IG.Forms.Test.ColorConverterForm.InitializeComponent(), and IG.Forms.Test.ColorConverterForm.parseRGB().
tbHue
System Windows Forms TextBox IG.Forms.Test.ColorConverterForm.tbHue private
Referenced by IG.Forms.Test.ColorConverterForm.InitializeComponent(), and IG.Forms.Test.ColorConverterForm.parseRGB().
tbSat
System Windows Forms TextBox IG.Forms.Test.ColorConverterForm.tbSat private
Referenced by IG.Forms.Test.ColorConverterForm.InitializeComponent(), and IG.Forms.Test.ColorConverterForm.parseRGB().
label4
System Windows Forms Label IG.Forms.Test.ColorConverterForm.label4 private
Referenced by IG.Forms.Test.ColorConverterForm.InitializeComponent().
label5
System Windows Forms Label IG.Forms.Test.ColorConverterForm.label5 private
Referenced by IG.Forms.Test.ColorConverterForm.InitializeComponent().
label6
System Windows Forms Label IG.Forms.Test.ColorConverterForm.label6 private
Referenced by IG.Forms.Test.ColorConverterForm.InitializeComponent().
tbBright
System Windows Forms TextBox IG.Forms.Test.ColorConverterForm.tbBright private
Referenced by IG.Forms.Test.ColorConverterForm.InitializeComponent(), and IG.Forms.Test.ColorConverterForm.parseRGB().
The documentation for this class was generated from the following files:
iglib/igforms/Basic/igform_quick_tests.cs
igtest/iglib_forms_quick/testforms/ColorConverter.cs