Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DSCAL Class Reference
DotNumerics.LinearAlgebra.CSLapack.DSCAL Class Reference
Public Member Functions
DSCAL ()
void Run (int N, double DA, ref double[] DX, int offset_dx, int INCX)
Detailed Description
Purpose
scales a vector by a constant. uses unrolled loops for increment equal to one. jack dongarra, linpack, 3/11/78. modified 3/93 to return if incx .le. 0. modified 12/3/93, array(1) declarations changed to array(*) /summary>
Constructor & Destructor Documentation
DSCAL()
DotNumerics.LinearAlgebra.CSLapack.DSCAL.DSCAL () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run (int N, double DA, ref double[] DX, int offset_dx, int INCX) inline
Purpose
scales a vector by a constant. uses unrolled loops for increment equal to one. jack dongarra, linpack, 3/11/78. modified 3/93 to return if incx .le. 0. modified 12/3/93, array(1) declarations changed to array(*) /summary>
References DotNumerics.FortranLibrary.FortranLib.Mod().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DRSCL.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRTI2.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGL2.Run(), DotNumerics.LinearAlgebra.CSLapack.DORG2L.Run(), DotNumerics.LinearAlgebra.CSLapack.DORG2R.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBAK.Run(), DotNumerics.LinearAlgebra.CSLapack.DGBTF2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGETF2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run(), DotNumerics.LinearAlgebra.CSLapack.DGBTRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBAL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAHR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DSBEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLATRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLABRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLATRS.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED8.Run(), DotNumerics.LinearAlgebra.CSLapack.DTREVC.Run(), DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DSBEVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYEVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALS0.Run(), and DotNumerics.LinearAlgebra.CSLapack.DTGSJA.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dscal.cs