Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLASDA Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLASDA Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLASDA (DCOPY dcopy, DLASD6 dlasd6, DLASDQ dlasdq, DLASDT dlasdt, DLASET dlaset, XERBLA xerbla)
DLASDA ()
void Run (int ICOMPQ, int SMLSIZ, int N, int SQRE, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] U, int offset_u, int LDU, ref double[] VT, int offset_vt, ref int[] K, int offset_k, ref double[] DIFL, int offset_difl, ref double[] DIFR, int offset_difr, ref double[] Z, int offset_z, ref double[] POLES, int offset_poles, ref int[] GIVPTR, int offset_givptr, ref int[] GIVCOL, int offset_givcol, int LDGCOL, ref int[] PERM, int offset_perm, ref double[] GIVNUM, int offset_givnum, ref double[] C, int offset_c, ref double[] S, int offset_s, ref double[] WORK, int offset_work, ref int[] IWORK, int offset_iwork, ref int INFO)
Private Attributes
DCOPY _dcopy
DLASD6 _dlasd6
DLASDQ _dlasdq
DLASDT _dlasdt
DLASET _dlaset
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
Using a divide and conquer approach, DLASDA computes the singular value decomposition (SVD) of a real upper bidiagonal N-by-M matrix B with diagonal D and offdiagonal E, where M = N + SQRE. The algorithm computes the singular values in the SVD B = U * S * VT. The orthogonal matrices U and VT are optionally computed in compact form.
A related subroutine, DLASD0, computes the singular values and the singular vectors in explicit form.
/summary>
Constructor & Destructor Documentation
DLASDA() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLASDA.DLASDA (DCOPY dcopy, DLASD6 dlasd6, DLASDQ dlasdq, DLASDT dlasdt, DLASET dlaset, XERBLA xerbla) inline
DLASDA() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLASDA.DLASDA () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLASDA.Run (int ICOMPQ, int SMLSIZ, int N, int SQRE, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] U, int offset_u, int LDU, ref double[] VT, int offset_vt, ref int[] K, int offset_k, ref double[] DIFL, int offset_difl, ref double[] DIFR, int offset_difr, ref double[] Z, int offset_z, ref double[] POLES, int offset_poles, ref int[] GIVPTR, int offset_givptr, ref int[] GIVCOL, int offset_givcol, int LDGCOL, ref int[] PERM, int offset_perm, ref double[] GIVNUM, int offset_givnum, ref double[] C, int offset_c, ref double[] S, int offset_s, ref double[] WORK, int offset_work, ref int[] IWORK, int offset_iwork, ref int INFO) inline
Purpose
Using a divide and conquer approach, DLASDA computes the singular value decomposition (SVD) of a real upper bidiagonal N-by-M matrix B with diagonal D and offdiagonal E, where M = N + SQRE. The algorithm computes the singular values in the SVD B = U * S * VT. The orthogonal matrices U and VT are optionally computed in compact form.
A related subroutine, DLASD0, computes the singular values and the singular vectors in explicit form.
/summary>
Parameters
ICOMPQ (input) INTEGER Specifies whether singular vectors are to be computed in compact form, as follows = 0: Compute singular values only. = 1: Compute singular vectors of upper bidiagonal matrix in compact form. /param>
Parameters
SMLSIZ (input) INTEGER The maximum size of the subproblems at the bottom of the computation tree. /param>
Parameters
N (input) INTEGER The row dimension of the upper bidiagonal matrix. This is also the dimension of the main diagonal array D. /param>
Parameters
SQRE (input) INTEGER Specifies the column dimension of the bidiagonal matrix. = 0: The bidiagonal matrix has column dimension M = N; = 1: The bidiagonal matrix has column dimension M = N + 1. /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension (N) On entry D contains the main diagonal of the bidiagonal matrix. On exit D, if INFO = 0, contains its singular values. /param>
Parameters
E (input) DOUBLE PRECISION array, dimension (M-1) Contains the subdiagonal entries of the bidiagonal matrix. On exit, E has been destroyed. /param>
Parameters
U (output) DOUBLE PRECISION array, dimension (LDU, SMLSIZ) if ICOMPQ = 1, and not referenced if ICOMPQ = 0. If ICOMPQ = 1, on exit, U contains the left singular vector matrices of all subproblems at the bottom level. /param>
Parameters
LDU (input) INTEGER, LDU = .GT. N. The leading dimension of arrays U, VT, DIFL, DIFR, POLES, GIVNUM, and Z. /param>
Parameters
VT (output) DOUBLE PRECISION array, dimension (LDU, SMLSIZ+1) if ICOMPQ = 1, and not referenced if ICOMPQ = 0. If ICOMPQ = 1, on exit, VT' contains the right singular vector matrices of all subproblems at the bottom level. /param>
Parameters
K (output) INTEGER array, dimension (N) if ICOMPQ = 1 and dimension 1 if ICOMPQ = 0. If ICOMPQ = 1, on exit, K(I) is the dimension of the I-th secular equation on the computation tree. /param>
Parameters
DIFL (output) DOUBLE PRECISION array, dimension (LDU, NLVL), where NLVL = floor(log_2 (N/SMLSIZ))). /param>
Parameters
DIFR (output) DOUBLE PRECISION array, dimension (LDU, 2 * NLVL) if ICOMPQ = 1 and dimension (N) if ICOMPQ = 0. If ICOMPQ = 1, on exit, DIFL(1:N, I) and DIFR(1:N, 2 * I - 1) record distances between singular values on the I-th level and singular values on the (I -1)-th level, and DIFR(1:N, 2 * I) contains the normalizing factors for the right singular vector matrix. See DLASD8 for details. /param>
Parameters
Z (output) DOUBLE PRECISION array, dimension (LDU, NLVL) if ICOMPQ = 1 and dimension (N) if ICOMPQ = 0. The first K elements of Z(1, I) contain the components of the deflation-adjusted updating row vector for subproblems on the I-th level. /param>
Parameters
POLES (output) DOUBLE PRECISION array, dimension (LDU, 2 * NLVL) if ICOMPQ = 1, and not referenced if ICOMPQ = 0. If ICOMPQ = 1, on exit, POLES(1, 2*I - 1) and POLES(1, 2*I) contain the new and old singular values involved in the secular equations on the I-th level. /param>
Parameters
GIVPTR (output) INTEGER array, dimension (N) if ICOMPQ = 1, and not referenced if ICOMPQ = 0. If ICOMPQ = 1, on exit, GIVPTR(I) records the number of Givens rotations performed on the I-th problem on the computation tree. /param>
Parameters
GIVCOL (output) INTEGER array, dimension (LDGCOL, 2 * NLVL) if ICOMPQ = 1, and not referenced if ICOMPQ = 0. If ICOMPQ = 1, on exit, for each I, GIVCOL(1, 2 I - 1) and GIVCOL(1, 2 *I) record the locations of Givens rotations performed on the I-th level on the computation tree. /param>
Parameters
LDGCOL (input) INTEGER, LDGCOL = .GT. N. The leading dimension of arrays GIVCOL and PERM. /param>
Parameters
PERM (output) INTEGER array, dimension (LDGCOL, NLVL) if ICOMPQ = 1, and not referenced if ICOMPQ = 0. If ICOMPQ = 1, on exit, PERM(1, I) records permutations done on the I-th level of the computation tree. /param>
Parameters
GIVNUM (output) DOUBLE PRECISION array, dimension (LDU, 2 * NLVL) if ICOMPQ = 1, and not referenced if ICOMPQ = 0. If ICOMPQ = 1, on exit, for each I, GIVNUM(1, 2 *I - 1) and GIVNUM(1, 2 *I) record the C- and S- values of Givens rotations performed on the I-th level on the computation tree. /param>
Parameters
C (output) DOUBLE PRECISION array, dimension (N) if ICOMPQ = 1, and dimension 1 if ICOMPQ = 0. If ICOMPQ = 1 and the I-th subproblem is not square, on exit, C(I) contains the C-value of a Givens rotation related to the right null space of the I-th subproblem. /param>
Parameters
S (output) DOUBLE PRECISION array, dimension (N) if ICOMPQ = 1, and dimension 1 if ICOMPQ = 0. If ICOMPQ = 1 and the I-th subproblem is not square, on exit, S(I) contains the S-value of a Givens rotation related to the right null space of the I-th subproblem. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (6 * N + (SMLSIZ + 1)(SMLSIZ + 1)). /param>
Parameters
IWORK (workspace) INTEGER array. Dimension must be at least (7 * N). /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. .GT. 0: if INFO = 1, an singular value did not converge /param>
References DotNumerics.LinearAlgebra.CSLapack.DLASDA.ONE, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASDT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASET.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASDQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD6.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLASDA.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLALSD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DBDSDC.Run().
Member Data Documentation
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLASDA._dcopy private
_dlasd6
DLASD6 DotNumerics.LinearAlgebra.CSLapack.DLASDA._dlasd6 private
_dlasdq
DLASDQ DotNumerics.LinearAlgebra.CSLapack.DLASDA._dlasdq private
_dlasdt
DLASDT DotNumerics.LinearAlgebra.CSLapack.DLASDA._dlasdt private
_dlaset
DLASET DotNumerics.LinearAlgebra.CSLapack.DLASDA._dlaset private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLASDA._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLASDA.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASDA.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLASDA.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASDA.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlasda.cs