Doc: IGLib EXTENDED: NUnit.Framework.Syntax.SyntaxTest Class Reference
NUnit.Framework.Syntax.SyntaxTest Class Reference
Inherited by NUnit.Framework.Syntax.AfterTest_AndOperator, NUnit.Framework.Syntax.AfterTest_PropertyTest, NUnit.Framework.Syntax.AfterTest_SimpleConstraint, NUnit.Framework.Syntax.AllTest, NUnit.Framework.Syntax.AndIsEvaluatedBeforeFollowingOr, NUnit.Framework.Syntax.AndIsEvaluatedBeforePrecedingOr, NUnit.Framework.Syntax.AndOperatorOverride, NUnit.Framework.Syntax.AndTest, NUnit.Framework.Syntax.AndTest_ThreeAndsWithNot, NUnit.Framework.Syntax.AssignableFromTest, NUnit.Framework.Syntax.AssignableFromTest_Generic, NUnit.Framework.Syntax.AssignableToTest, NUnit.Framework.Syntax.AssignableToTest_Generic, NUnit.Framework.Syntax.AtLeastTest, NUnit.Framework.Syntax.AtMostTest, NUnit.Framework.Syntax.AttributeTest, NUnit.Framework.Syntax.AttributeTest_Generic, NUnit.Framework.Syntax.AttributeTestWithFollowingConstraint, NUnit.Framework.Syntax.BinarySerializableTest, NUnit.Framework.Syntax.CollectionContainsTest, NUnit.Framework.Syntax.CollectionEquivalentTest, NUnit.Framework.Syntax.CollectionOrderedByTest, NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer, NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer_Descending, NUnit.Framework.Syntax.CollectionOrderedByTest_Descending, NUnit.Framework.Syntax.CollectionOrderedTest, NUnit.Framework.Syntax.CollectionOrderedTest_Comparer, NUnit.Framework.Syntax.CollectionOrderedTest_Comparer_Descending, NUnit.Framework.Syntax.CollectionOrderedTest_Descending, NUnit.Framework.Syntax.CollectionSubsetTest, NUnit.Framework.Syntax.ContainsTest, NUnit.Framework.Syntax.ContainsTest_IgnoreCase, NUnit.Framework.Syntax.CountTest, NUnit.Framework.Syntax.EndsWithTest, NUnit.Framework.Syntax.EndsWithTest_IgnoreCase, NUnit.Framework.Syntax.EqualToTest, NUnit.Framework.Syntax.EqualToTest_IgnoreCase, NUnit.Framework.Syntax.EqualToTest_WithinTolerance, NUnit.Framework.Syntax.ExactTypeTest, NUnit.Framework.Syntax.ExactTypeTest_Generic, NUnit.Framework.Syntax.FalseTest, NUnit.Framework.Syntax.GreaterThanOrEqualTest, NUnit.Framework.Syntax.GreaterThanTest, NUnit.Framework.Syntax.InstanceOfTest, NUnit.Framework.Syntax.InstanceOfTest_Generic, NUnit.Framework.Syntax.LengthTest, NUnit.Framework.Syntax.LessThanOrEqualTest, NUnit.Framework.Syntax.LessThanTest, NUnit.Framework.Syntax.MessageTest, NUnit.Framework.Syntax.NaNTest, NUnit.Framework.Syntax.NegativeTest, NUnit.Framework.Syntax.NoneTest, NUnit.Framework.Syntax.NotOperatorOverride, NUnit.Framework.Syntax.NotSamePathOrUnderTest_IgnoreCase, NUnit.Framework.Syntax.NotSamePathOrUnderTest_RespectCase, NUnit.Framework.Syntax.NotSamePathTest_IgnoreCase, NUnit.Framework.Syntax.NotSamePathTest_RespectCase, NUnit.Framework.Syntax.NotTest, NUnit.Framework.Syntax.NotTest_Cascaded, NUnit.Framework.Syntax.NullTest, NUnit.Framework.Syntax.OrOperatorOverride, NUnit.Framework.Syntax.OrTest, NUnit.Framework.Syntax.OrTest_ThreeOrs, NUnit.Framework.Syntax.PositiveTest, NUnit.Framework.Syntax.PropertyExistsTest, NUnit.Framework.Syntax.PropertyExistsTest_AndFollows, NUnit.Framework.Syntax.PropertyTest_ConstraintFollows, NUnit.Framework.Syntax.PropertyTest_NotFollows, NUnit.Framework.Syntax.RegexTest, NUnit.Framework.Syntax.RegexTest_IgnoreCase, NUnit.Framework.Syntax.SamePathOrUnderTest, NUnit.Framework.Syntax.SamePathOrUnderTest_IgnoreCase, NUnit.Framework.Syntax.SamePathOrUnderTest_RespectCase, NUnit.Framework.Syntax.SamePathTest, NUnit.Framework.Syntax.SamePathTest_IgnoreCase, NUnit.Framework.Syntax.SamePathTest_RespectCase, NUnit.Framework.Syntax.SomeTest, NUnit.Framework.Syntax.SomeTest_BeforeBinaryOperators, NUnit.Framework.Syntax.SomeTest_NestedSome, NUnit.Framework.Syntax.SomeTest_UseOfAndSome, NUnit.Framework.Syntax.StartsWithTest, NUnit.Framework.Syntax.StartsWithTest_IgnoreCase, NUnit.Framework.Syntax.TextStartsWithTest, NUnit.Framework.Syntax.TrueTest, NUnit.Framework.Syntax.UniqueTest, and NUnit.Framework.Syntax.XmlSerializableTest.
Public Member Functions
void SupportedByStaticSyntax ()
void SupportedByConstraintBuilder ()
void SupportedByInheritedSyntax ()
Protected Member Functions
AssertionHelper Helper ()
ConstraintExpression Builder ()
Protected Attributes
string parseTree
IResolveConstraint staticSyntax
IResolveConstraint inheritedSyntax
IResolveConstraint builderSyntax
Member Function Documentation
Helper()
AssertionHelper NUnit.Framework.Syntax.SyntaxTest.Helper () inline protected
Referenced by NUnit.Framework.Syntax.GreaterThanTest.SetUp(), NUnit.Framework.Syntax.ContainsTest.SetUp(), NUnit.Framework.Syntax.NullTest.SetUp(), NUnit.Framework.Syntax.PropertyExistsTest.SetUp(), NUnit.Framework.Syntax.EqualToTest.SetUp(), NUnit.Framework.Syntax.ExactTypeTest.SetUp(), NUnit.Framework.Syntax.NotOperatorOverride.SetUp(), NUnit.Framework.Syntax.NotTest.SetUp(), NUnit.Framework.Syntax.BinarySerializableTest.SetUp(), NUnit.Framework.Syntax.SamePathTest.SetUp(), NUnit.Framework.Syntax.UniqueTest.SetUp(), NUnit.Framework.Syntax.AfterTest_SimpleConstraint.SetUp(), NUnit.Framework.Syntax.GreaterThanOrEqualTest.SetUp(), NUnit.Framework.Syntax.ContainsTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.TrueTest.SetUp(), NUnit.Framework.Syntax.EqualToTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.AndOperatorOverride.SetUp(), NUnit.Framework.Syntax.NotTest_Cascaded.SetUp(), NUnit.Framework.Syntax.PropertyExistsTest_AndFollows.SetUp(), NUnit.Framework.Syntax.InstanceOfTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest.SetUp(), NUnit.Framework.Syntax.AfterTest_PropertyTest.SetUp(), NUnit.Framework.Syntax.XmlSerializableTest.SetUp(), NUnit.Framework.Syntax.SamePathTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.StartsWithTest.SetUp(), NUnit.Framework.Syntax.AtLeastTest.SetUp(), NUnit.Framework.Syntax.FalseTest.SetUp(), NUnit.Framework.Syntax.EqualToTest_WithinTolerance.SetUp(), NUnit.Framework.Syntax.OrOperatorOverride.SetUp(), NUnit.Framework.Syntax.PropertyTest_ConstraintFollows.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Descending.SetUp(), NUnit.Framework.Syntax.AssignableFromTest.SetUp(), NUnit.Framework.Syntax.AfterTest_AndOperator.SetUp(), NUnit.Framework.Syntax.AllTest.SetUp(), NUnit.Framework.Syntax.NotSamePathTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.PositiveTest.SetUp(), NUnit.Framework.Syntax.TextStartsWithTest.SetUp(), NUnit.Framework.Syntax.LessThanTest.SetUp(), NUnit.Framework.Syntax.PropertyTest_NotFollows.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer.SetUp(), NUnit.Framework.Syntax.AssignableToTest.SetUp(), NUnit.Framework.Syntax.SomeTest.SetUp(), NUnit.Framework.Syntax.SamePathTest_RespectCase.SetUp(), NUnit.Framework.Syntax.NegativeTest.SetUp(), NUnit.Framework.Syntax.LessThanOrEqualTest.SetUp(), NUnit.Framework.Syntax.StartsWithTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.LengthTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer_Descending.SetUp(), NUnit.Framework.Syntax.SomeTest_BeforeBinaryOperators.SetUp(), NUnit.Framework.Syntax.AttributeTest.SetUp(), NUnit.Framework.Syntax.NaNTest.SetUp(), NUnit.Framework.Syntax.EndsWithTest.SetUp(), NUnit.Framework.Syntax.AtMostTest.SetUp(), NUnit.Framework.Syntax.NotSamePathTest_RespectCase.SetUp(), NUnit.Framework.Syntax.CountTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest.SetUp(), NUnit.Framework.Syntax.SomeTest_NestedSome.SetUp(), NUnit.Framework.Syntax.AttributeTestWithFollowingConstraint.SetUp(), NUnit.Framework.Syntax.EndsWithTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.MessageTest.SetUp(), NUnit.Framework.Syntax.SamePathOrUnderTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Descending.SetUp(), NUnit.Framework.Syntax.SomeTest_UseOfAndSome.SetUp(), NUnit.Framework.Syntax.ExactTypeTest_Generic.SetUp(), NUnit.Framework.Syntax.RegexTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer.SetUp(), NUnit.Framework.Syntax.SamePathOrUnderTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.NoneTest.SetUp(), NUnit.Framework.Syntax.InstanceOfTest_Generic.SetUp(), NUnit.Framework.Syntax.RegexTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer_Descending.SetUp(), NUnit.Framework.Syntax.NotSamePathOrUnderTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.AndTest.SetUp(), NUnit.Framework.Syntax.AssignableFromTest_Generic.SetUp(), NUnit.Framework.Syntax.CollectionContainsTest.SetUp(), NUnit.Framework.Syntax.AndTest_ThreeAndsWithNot.SetUp(), NUnit.Framework.Syntax.SamePathOrUnderTest_RespectCase.SetUp(), NUnit.Framework.Syntax.AssignableToTest_Generic.SetUp(), NUnit.Framework.Syntax.CollectionSubsetTest.SetUp(), NUnit.Framework.Syntax.OrTest.SetUp(), NUnit.Framework.Syntax.NotSamePathOrUnderTest_RespectCase.SetUp(), NUnit.Framework.Syntax.AttributeTest_Generic.SetUp(), NUnit.Framework.Syntax.CollectionEquivalentTest.SetUp(), NUnit.Framework.Syntax.OrTest_ThreeOrs.SetUp(), NUnit.Framework.Syntax.AndIsEvaluatedBeforeFollowingOr.SetUp(), and NUnit.Framework.Syntax.AndIsEvaluatedBeforePrecedingOr.SetUp().
Builder()
ConstraintExpression NUnit.Framework.Syntax.SyntaxTest.Builder () inline protected
Referenced by NUnit.Framework.Syntax.GreaterThanTest.SetUp(), NUnit.Framework.Syntax.ContainsTest.SetUp(), NUnit.Framework.Syntax.NullTest.SetUp(), NUnit.Framework.Syntax.PropertyExistsTest.SetUp(), NUnit.Framework.Syntax.EqualToTest.SetUp(), NUnit.Framework.Syntax.ExactTypeTest.SetUp(), NUnit.Framework.Syntax.NotOperatorOverride.SetUp(), NUnit.Framework.Syntax.NotTest.SetUp(), NUnit.Framework.Syntax.BinarySerializableTest.SetUp(), NUnit.Framework.Syntax.SamePathTest.SetUp(), NUnit.Framework.Syntax.UniqueTest.SetUp(), NUnit.Framework.Syntax.AfterTest_SimpleConstraint.SetUp(), NUnit.Framework.Syntax.GreaterThanOrEqualTest.SetUp(), NUnit.Framework.Syntax.ContainsTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.TrueTest.SetUp(), NUnit.Framework.Syntax.EqualToTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.AndOperatorOverride.SetUp(), NUnit.Framework.Syntax.NotTest_Cascaded.SetUp(), NUnit.Framework.Syntax.PropertyExistsTest_AndFollows.SetUp(), NUnit.Framework.Syntax.InstanceOfTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest.SetUp(), NUnit.Framework.Syntax.AfterTest_PropertyTest.SetUp(), NUnit.Framework.Syntax.XmlSerializableTest.SetUp(), NUnit.Framework.Syntax.SamePathTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.StartsWithTest.SetUp(), NUnit.Framework.Syntax.AtLeastTest.SetUp(), NUnit.Framework.Syntax.FalseTest.SetUp(), NUnit.Framework.Syntax.EqualToTest_WithinTolerance.SetUp(), NUnit.Framework.Syntax.OrOperatorOverride.SetUp(), NUnit.Framework.Syntax.PropertyTest_ConstraintFollows.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Descending.SetUp(), NUnit.Framework.Syntax.AssignableFromTest.SetUp(), NUnit.Framework.Syntax.AfterTest_AndOperator.SetUp(), NUnit.Framework.Syntax.AllTest.SetUp(), NUnit.Framework.Syntax.NotSamePathTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.PositiveTest.SetUp(), NUnit.Framework.Syntax.TextStartsWithTest.SetUp(), NUnit.Framework.Syntax.LessThanTest.SetUp(), NUnit.Framework.Syntax.PropertyTest_NotFollows.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer.SetUp(), NUnit.Framework.Syntax.AssignableToTest.SetUp(), NUnit.Framework.Syntax.SomeTest.SetUp(), NUnit.Framework.Syntax.SamePathTest_RespectCase.SetUp(), NUnit.Framework.Syntax.NegativeTest.SetUp(), NUnit.Framework.Syntax.LessThanOrEqualTest.SetUp(), NUnit.Framework.Syntax.StartsWithTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.LengthTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer_Descending.SetUp(), NUnit.Framework.Syntax.SomeTest_BeforeBinaryOperators.SetUp(), NUnit.Framework.Syntax.AttributeTest.SetUp(), NUnit.Framework.Syntax.NaNTest.SetUp(), NUnit.Framework.Syntax.EndsWithTest.SetUp(), NUnit.Framework.Syntax.AtMostTest.SetUp(), NUnit.Framework.Syntax.NotSamePathTest_RespectCase.SetUp(), NUnit.Framework.Syntax.CountTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest.SetUp(), NUnit.Framework.Syntax.SomeTest_NestedSome.SetUp(), NUnit.Framework.Syntax.AttributeTestWithFollowingConstraint.SetUp(), NUnit.Framework.Syntax.EndsWithTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.MessageTest.SetUp(), NUnit.Framework.Syntax.SamePathOrUnderTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Descending.SetUp(), NUnit.Framework.Syntax.SomeTest_UseOfAndSome.SetUp(), NUnit.Framework.Syntax.ExactTypeTest_Generic.SetUp(), NUnit.Framework.Syntax.RegexTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer.SetUp(), NUnit.Framework.Syntax.SamePathOrUnderTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.NoneTest.SetUp(), NUnit.Framework.Syntax.InstanceOfTest_Generic.SetUp(), NUnit.Framework.Syntax.RegexTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer_Descending.SetUp(), NUnit.Framework.Syntax.NotSamePathOrUnderTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.AndTest.SetUp(), NUnit.Framework.Syntax.AssignableFromTest_Generic.SetUp(), NUnit.Framework.Syntax.CollectionContainsTest.SetUp(), NUnit.Framework.Syntax.AndTest_ThreeAndsWithNot.SetUp(), NUnit.Framework.Syntax.SamePathOrUnderTest_RespectCase.SetUp(), NUnit.Framework.Syntax.AssignableToTest_Generic.SetUp(), NUnit.Framework.Syntax.CollectionSubsetTest.SetUp(), NUnit.Framework.Syntax.OrTest.SetUp(), NUnit.Framework.Syntax.NotSamePathOrUnderTest_RespectCase.SetUp(), NUnit.Framework.Syntax.AttributeTest_Generic.SetUp(), NUnit.Framework.Syntax.CollectionEquivalentTest.SetUp(), NUnit.Framework.Syntax.OrTest_ThreeOrs.SetUp(), NUnit.Framework.Syntax.AndIsEvaluatedBeforeFollowingOr.SetUp(), and NUnit.Framework.Syntax.AndIsEvaluatedBeforePrecedingOr.SetUp().
SupportedByStaticSyntax()
void NUnit.Framework.Syntax.SyntaxTest.SupportedByStaticSyntax () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Constraints.EqualConstraint.NoClip, NUnit.Framework.Syntax.SyntaxTest.parseTree, NUnit.Framework.Constraints.IResolveConstraint.Resolve(), NUnit.Framework.Syntax.SyntaxTest.staticSyntax, and NUnit.Framework.Assert.That().
SupportedByConstraintBuilder()
void NUnit.Framework.Syntax.SyntaxTest.SupportedByConstraintBuilder () inline
References NUnit.Framework.Syntax.SyntaxTest.builderSyntax, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Constraints.EqualConstraint.NoClip, NUnit.Framework.Syntax.SyntaxTest.parseTree, NUnit.Framework.Constraints.IResolveConstraint.Resolve(), and NUnit.Framework.Assert.That().
SupportedByInheritedSyntax()
void NUnit.Framework.Syntax.SyntaxTest.SupportedByInheritedSyntax () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Syntax.SyntaxTest.inheritedSyntax, NUnit.Framework.Constraints.EqualConstraint.NoClip, NUnit.Framework.Syntax.SyntaxTest.parseTree, NUnit.Framework.Constraints.IResolveConstraint.Resolve(), and NUnit.Framework.Assert.That().
Member Data Documentation
parseTree
string NUnit.Framework.Syntax.SyntaxTest.parseTree protected
Referenced by NUnit.Framework.Syntax.GreaterThanTest.SetUp(), NUnit.Framework.Syntax.ContainsTest.SetUp(), NUnit.Framework.Syntax.NullTest.SetUp(), NUnit.Framework.Syntax.PropertyExistsTest.SetUp(), NUnit.Framework.Syntax.EqualToTest.SetUp(), NUnit.Framework.Syntax.ExactTypeTest.SetUp(), NUnit.Framework.Syntax.NotOperatorOverride.SetUp(), NUnit.Framework.Syntax.NotTest.SetUp(), NUnit.Framework.Syntax.BinarySerializableTest.SetUp(), NUnit.Framework.Syntax.SamePathTest.SetUp(), NUnit.Framework.Syntax.UniqueTest.SetUp(), NUnit.Framework.Syntax.AfterTest_SimpleConstraint.SetUp(), NUnit.Framework.Syntax.GreaterThanOrEqualTest.SetUp(), NUnit.Framework.Syntax.ContainsTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.TrueTest.SetUp(), NUnit.Framework.Syntax.EqualToTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.AndOperatorOverride.SetUp(), NUnit.Framework.Syntax.NotTest_Cascaded.SetUp(), NUnit.Framework.Syntax.PropertyExistsTest_AndFollows.SetUp(), NUnit.Framework.Syntax.InstanceOfTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest.SetUp(), NUnit.Framework.Syntax.AfterTest_PropertyTest.SetUp(), NUnit.Framework.Syntax.XmlSerializableTest.SetUp(), NUnit.Framework.Syntax.SamePathTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.StartsWithTest.SetUp(), NUnit.Framework.Syntax.AtLeastTest.SetUp(), NUnit.Framework.Syntax.FalseTest.SetUp(), NUnit.Framework.Syntax.EqualToTest_WithinTolerance.SetUp(), NUnit.Framework.Syntax.OrOperatorOverride.SetUp(), NUnit.Framework.Syntax.PropertyTest_ConstraintFollows.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Descending.SetUp(), NUnit.Framework.Syntax.AssignableFromTest.SetUp(), NUnit.Framework.Syntax.AfterTest_AndOperator.SetUp(), NUnit.Framework.Syntax.AllTest.SetUp(), NUnit.Framework.Syntax.NotSamePathTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.PositiveTest.SetUp(), NUnit.Framework.Syntax.TextStartsWithTest.SetUp(), NUnit.Framework.Syntax.LessThanTest.SetUp(), NUnit.Framework.Syntax.PropertyTest_NotFollows.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer.SetUp(), NUnit.Framework.Syntax.AssignableToTest.SetUp(), NUnit.Framework.Syntax.SomeTest.SetUp(), NUnit.Framework.Syntax.SamePathTest_RespectCase.SetUp(), NUnit.Framework.Syntax.NegativeTest.SetUp(), NUnit.Framework.Syntax.LessThanOrEqualTest.SetUp(), NUnit.Framework.Syntax.StartsWithTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.LengthTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer_Descending.SetUp(), NUnit.Framework.Syntax.SomeTest_BeforeBinaryOperators.SetUp(), NUnit.Framework.Syntax.AttributeTest.SetUp(), NUnit.Framework.Syntax.NaNTest.SetUp(), NUnit.Framework.Syntax.EndsWithTest.SetUp(), NUnit.Framework.Syntax.AtMostTest.SetUp(), NUnit.Framework.Syntax.NotSamePathTest_RespectCase.SetUp(), NUnit.Framework.Syntax.CountTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest.SetUp(), NUnit.Framework.Syntax.SomeTest_NestedSome.SetUp(), NUnit.Framework.Syntax.AttributeTestWithFollowingConstraint.SetUp(), NUnit.Framework.Syntax.EndsWithTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.MessageTest.SetUp(), NUnit.Framework.Syntax.SamePathOrUnderTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Descending.SetUp(), NUnit.Framework.Syntax.SomeTest_UseOfAndSome.SetUp(), NUnit.Framework.Syntax.ExactTypeTest_Generic.SetUp(), NUnit.Framework.Syntax.RegexTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer.SetUp(), NUnit.Framework.Syntax.SamePathOrUnderTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.NoneTest.SetUp(), NUnit.Framework.Syntax.InstanceOfTest_Generic.SetUp(), NUnit.Framework.Syntax.RegexTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer_Descending.SetUp(), NUnit.Framework.Syntax.NotSamePathOrUnderTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.AndTest.SetUp(), NUnit.Framework.Syntax.AssignableFromTest_Generic.SetUp(), NUnit.Framework.Syntax.CollectionContainsTest.SetUp(), NUnit.Framework.Syntax.AndTest_ThreeAndsWithNot.SetUp(), NUnit.Framework.Syntax.SamePathOrUnderTest_RespectCase.SetUp(), NUnit.Framework.Syntax.AssignableToTest_Generic.SetUp(), NUnit.Framework.Syntax.CollectionSubsetTest.SetUp(), NUnit.Framework.Syntax.NotSamePathOrUnderTest_RespectCase.SetUp(), NUnit.Framework.Syntax.OrTest.SetUp(), NUnit.Framework.Syntax.AttributeTest_Generic.SetUp(), NUnit.Framework.Syntax.CollectionEquivalentTest.SetUp(), NUnit.Framework.Syntax.OrTest_ThreeOrs.SetUp(), NUnit.Framework.Syntax.AndIsEvaluatedBeforeFollowingOr.SetUp(), NUnit.Framework.Syntax.AndIsEvaluatedBeforePrecedingOr.SetUp(), NUnit.Framework.Syntax.SyntaxTest.SupportedByConstraintBuilder(), NUnit.Framework.Syntax.SyntaxTest.SupportedByInheritedSyntax(), and NUnit.Framework.Syntax.SyntaxTest.SupportedByStaticSyntax().
staticSyntax
IResolveConstraint NUnit.Framework.Syntax.SyntaxTest.staticSyntax protected
Referenced by NUnit.Framework.Syntax.GreaterThanTest.SetUp(), NUnit.Framework.Syntax.ContainsTest.SetUp(), NUnit.Framework.Syntax.NullTest.SetUp(), NUnit.Framework.Syntax.PropertyExistsTest.SetUp(), NUnit.Framework.Syntax.EqualToTest.SetUp(), NUnit.Framework.Syntax.ExactTypeTest.SetUp(), NUnit.Framework.Syntax.NotOperatorOverride.SetUp(), NUnit.Framework.Syntax.NotTest.SetUp(), NUnit.Framework.Syntax.BinarySerializableTest.SetUp(), NUnit.Framework.Syntax.SamePathTest.SetUp(), NUnit.Framework.Syntax.UniqueTest.SetUp(), NUnit.Framework.Syntax.AfterTest_SimpleConstraint.SetUp(), NUnit.Framework.Syntax.GreaterThanOrEqualTest.SetUp(), NUnit.Framework.Syntax.ContainsTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.TrueTest.SetUp(), NUnit.Framework.Syntax.EqualToTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.AndOperatorOverride.SetUp(), NUnit.Framework.Syntax.NotTest_Cascaded.SetUp(), NUnit.Framework.Syntax.PropertyExistsTest_AndFollows.SetUp(), NUnit.Framework.Syntax.InstanceOfTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest.SetUp(), NUnit.Framework.Syntax.AfterTest_PropertyTest.SetUp(), NUnit.Framework.Syntax.XmlSerializableTest.SetUp(), NUnit.Framework.Syntax.SamePathTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.StartsWithTest.SetUp(), NUnit.Framework.Syntax.AtLeastTest.SetUp(), NUnit.Framework.Syntax.FalseTest.SetUp(), NUnit.Framework.Syntax.EqualToTest_WithinTolerance.SetUp(), NUnit.Framework.Syntax.OrOperatorOverride.SetUp(), NUnit.Framework.Syntax.PropertyTest_ConstraintFollows.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Descending.SetUp(), NUnit.Framework.Syntax.AssignableFromTest.SetUp(), NUnit.Framework.Syntax.AfterTest_AndOperator.SetUp(), NUnit.Framework.Syntax.AllTest.SetUp(), NUnit.Framework.Syntax.NotSamePathTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.PositiveTest.SetUp(), NUnit.Framework.Syntax.TextStartsWithTest.SetUp(), NUnit.Framework.Syntax.LessThanTest.SetUp(), NUnit.Framework.Syntax.PropertyTest_NotFollows.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer.SetUp(), NUnit.Framework.Syntax.AssignableToTest.SetUp(), NUnit.Framework.Syntax.SomeTest.SetUp(), NUnit.Framework.Syntax.SamePathTest_RespectCase.SetUp(), NUnit.Framework.Syntax.NegativeTest.SetUp(), NUnit.Framework.Syntax.LessThanOrEqualTest.SetUp(), NUnit.Framework.Syntax.StartsWithTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.LengthTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer_Descending.SetUp(), NUnit.Framework.Syntax.SomeTest_BeforeBinaryOperators.SetUp(), NUnit.Framework.Syntax.AttributeTest.SetUp(), NUnit.Framework.Syntax.NaNTest.SetUp(), NUnit.Framework.Syntax.EndsWithTest.SetUp(), NUnit.Framework.Syntax.AtMostTest.SetUp(), NUnit.Framework.Syntax.NotSamePathTest_RespectCase.SetUp(), NUnit.Framework.Syntax.CountTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest.SetUp(), NUnit.Framework.Syntax.SomeTest_NestedSome.SetUp(), NUnit.Framework.Syntax.AttributeTestWithFollowingConstraint.SetUp(), NUnit.Framework.Syntax.EndsWithTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.MessageTest.SetUp(), NUnit.Framework.Syntax.SamePathOrUnderTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Descending.SetUp(), NUnit.Framework.Syntax.SomeTest_UseOfAndSome.SetUp(), NUnit.Framework.Syntax.ExactTypeTest_Generic.SetUp(), NUnit.Framework.Syntax.RegexTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer.SetUp(), NUnit.Framework.Syntax.SamePathOrUnderTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.NoneTest.SetUp(), NUnit.Framework.Syntax.InstanceOfTest_Generic.SetUp(), NUnit.Framework.Syntax.RegexTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer_Descending.SetUp(), NUnit.Framework.Syntax.NotSamePathOrUnderTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.AndTest.SetUp(), NUnit.Framework.Syntax.AssignableFromTest_Generic.SetUp(), NUnit.Framework.Syntax.CollectionContainsTest.SetUp(), NUnit.Framework.Syntax.SamePathOrUnderTest_RespectCase.SetUp(), NUnit.Framework.Syntax.AndTest_ThreeAndsWithNot.SetUp(), NUnit.Framework.Syntax.AssignableToTest_Generic.SetUp(), NUnit.Framework.Syntax.CollectionSubsetTest.SetUp(), NUnit.Framework.Syntax.OrTest.SetUp(), NUnit.Framework.Syntax.NotSamePathOrUnderTest_RespectCase.SetUp(), NUnit.Framework.Syntax.AttributeTest_Generic.SetUp(), NUnit.Framework.Syntax.CollectionEquivalentTest.SetUp(), NUnit.Framework.Syntax.OrTest_ThreeOrs.SetUp(), NUnit.Framework.Syntax.AndIsEvaluatedBeforeFollowingOr.SetUp(), NUnit.Framework.Syntax.AndIsEvaluatedBeforePrecedingOr.SetUp(), and NUnit.Framework.Syntax.SyntaxTest.SupportedByStaticSyntax().
inheritedSyntax
IResolveConstraint NUnit.Framework.Syntax.SyntaxTest.inheritedSyntax protected
Referenced by NUnit.Framework.Syntax.GreaterThanTest.SetUp(), NUnit.Framework.Syntax.ContainsTest.SetUp(), NUnit.Framework.Syntax.NullTest.SetUp(), NUnit.Framework.Syntax.PropertyExistsTest.SetUp(), NUnit.Framework.Syntax.EqualToTest.SetUp(), NUnit.Framework.Syntax.ExactTypeTest.SetUp(), NUnit.Framework.Syntax.NotOperatorOverride.SetUp(), NUnit.Framework.Syntax.NotTest.SetUp(), NUnit.Framework.Syntax.BinarySerializableTest.SetUp(), NUnit.Framework.Syntax.SamePathTest.SetUp(), NUnit.Framework.Syntax.UniqueTest.SetUp(), NUnit.Framework.Syntax.AfterTest_SimpleConstraint.SetUp(), NUnit.Framework.Syntax.GreaterThanOrEqualTest.SetUp(), NUnit.Framework.Syntax.ContainsTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.TrueTest.SetUp(), NUnit.Framework.Syntax.EqualToTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.AndOperatorOverride.SetUp(), NUnit.Framework.Syntax.NotTest_Cascaded.SetUp(), NUnit.Framework.Syntax.PropertyExistsTest_AndFollows.SetUp(), NUnit.Framework.Syntax.InstanceOfTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest.SetUp(), NUnit.Framework.Syntax.AfterTest_PropertyTest.SetUp(), NUnit.Framework.Syntax.XmlSerializableTest.SetUp(), NUnit.Framework.Syntax.SamePathTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.StartsWithTest.SetUp(), NUnit.Framework.Syntax.AtLeastTest.SetUp(), NUnit.Framework.Syntax.FalseTest.SetUp(), NUnit.Framework.Syntax.EqualToTest_WithinTolerance.SetUp(), NUnit.Framework.Syntax.OrOperatorOverride.SetUp(), NUnit.Framework.Syntax.PropertyTest_ConstraintFollows.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Descending.SetUp(), NUnit.Framework.Syntax.AssignableFromTest.SetUp(), NUnit.Framework.Syntax.AfterTest_AndOperator.SetUp(), NUnit.Framework.Syntax.AllTest.SetUp(), NUnit.Framework.Syntax.NotSamePathTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.PositiveTest.SetUp(), NUnit.Framework.Syntax.TextStartsWithTest.SetUp(), NUnit.Framework.Syntax.LessThanTest.SetUp(), NUnit.Framework.Syntax.PropertyTest_NotFollows.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer.SetUp(), NUnit.Framework.Syntax.AssignableToTest.SetUp(), NUnit.Framework.Syntax.SomeTest.SetUp(), NUnit.Framework.Syntax.SamePathTest_RespectCase.SetUp(), NUnit.Framework.Syntax.NegativeTest.SetUp(), NUnit.Framework.Syntax.LessThanOrEqualTest.SetUp(), NUnit.Framework.Syntax.StartsWithTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.LengthTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer_Descending.SetUp(), NUnit.Framework.Syntax.SomeTest_BeforeBinaryOperators.SetUp(), NUnit.Framework.Syntax.AttributeTest.SetUp(), NUnit.Framework.Syntax.NaNTest.SetUp(), NUnit.Framework.Syntax.EndsWithTest.SetUp(), NUnit.Framework.Syntax.AtMostTest.SetUp(), NUnit.Framework.Syntax.NotSamePathTest_RespectCase.SetUp(), NUnit.Framework.Syntax.CountTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest.SetUp(), NUnit.Framework.Syntax.SomeTest_NestedSome.SetUp(), NUnit.Framework.Syntax.AttributeTestWithFollowingConstraint.SetUp(), NUnit.Framework.Syntax.EndsWithTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.MessageTest.SetUp(), NUnit.Framework.Syntax.SamePathOrUnderTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Descending.SetUp(), NUnit.Framework.Syntax.SomeTest_UseOfAndSome.SetUp(), NUnit.Framework.Syntax.ExactTypeTest_Generic.SetUp(), NUnit.Framework.Syntax.RegexTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer.SetUp(), NUnit.Framework.Syntax.SamePathOrUnderTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.NoneTest.SetUp(), NUnit.Framework.Syntax.InstanceOfTest_Generic.SetUp(), NUnit.Framework.Syntax.RegexTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer_Descending.SetUp(), NUnit.Framework.Syntax.NotSamePathOrUnderTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.AndTest.SetUp(), NUnit.Framework.Syntax.AssignableFromTest_Generic.SetUp(), NUnit.Framework.Syntax.CollectionContainsTest.SetUp(), NUnit.Framework.Syntax.SamePathOrUnderTest_RespectCase.SetUp(), NUnit.Framework.Syntax.AndTest_ThreeAndsWithNot.SetUp(), NUnit.Framework.Syntax.AssignableToTest_Generic.SetUp(), NUnit.Framework.Syntax.CollectionSubsetTest.SetUp(), NUnit.Framework.Syntax.OrTest.SetUp(), NUnit.Framework.Syntax.NotSamePathOrUnderTest_RespectCase.SetUp(), NUnit.Framework.Syntax.AttributeTest_Generic.SetUp(), NUnit.Framework.Syntax.CollectionEquivalentTest.SetUp(), NUnit.Framework.Syntax.OrTest_ThreeOrs.SetUp(), NUnit.Framework.Syntax.AndIsEvaluatedBeforeFollowingOr.SetUp(), NUnit.Framework.Syntax.AndIsEvaluatedBeforePrecedingOr.SetUp(), and NUnit.Framework.Syntax.SyntaxTest.SupportedByInheritedSyntax().
builderSyntax
IResolveConstraint NUnit.Framework.Syntax.SyntaxTest.builderSyntax protected
Referenced by NUnit.Framework.Syntax.GreaterThanTest.SetUp(), NUnit.Framework.Syntax.ContainsTest.SetUp(), NUnit.Framework.Syntax.NullTest.SetUp(), NUnit.Framework.Syntax.PropertyExistsTest.SetUp(), NUnit.Framework.Syntax.EqualToTest.SetUp(), NUnit.Framework.Syntax.ExactTypeTest.SetUp(), NUnit.Framework.Syntax.NotOperatorOverride.SetUp(), NUnit.Framework.Syntax.NotTest.SetUp(), NUnit.Framework.Syntax.BinarySerializableTest.SetUp(), NUnit.Framework.Syntax.SamePathTest.SetUp(), NUnit.Framework.Syntax.UniqueTest.SetUp(), NUnit.Framework.Syntax.AfterTest_SimpleConstraint.SetUp(), NUnit.Framework.Syntax.GreaterThanOrEqualTest.SetUp(), NUnit.Framework.Syntax.ContainsTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.TrueTest.SetUp(), NUnit.Framework.Syntax.EqualToTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.AndOperatorOverride.SetUp(), NUnit.Framework.Syntax.NotTest_Cascaded.SetUp(), NUnit.Framework.Syntax.PropertyExistsTest_AndFollows.SetUp(), NUnit.Framework.Syntax.InstanceOfTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest.SetUp(), NUnit.Framework.Syntax.AfterTest_PropertyTest.SetUp(), NUnit.Framework.Syntax.XmlSerializableTest.SetUp(), NUnit.Framework.Syntax.SamePathTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.StartsWithTest.SetUp(), NUnit.Framework.Syntax.AtLeastTest.SetUp(), NUnit.Framework.Syntax.FalseTest.SetUp(), NUnit.Framework.Syntax.EqualToTest_WithinTolerance.SetUp(), NUnit.Framework.Syntax.OrOperatorOverride.SetUp(), NUnit.Framework.Syntax.PropertyTest_ConstraintFollows.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Descending.SetUp(), NUnit.Framework.Syntax.AssignableFromTest.SetUp(), NUnit.Framework.Syntax.AfterTest_AndOperator.SetUp(), NUnit.Framework.Syntax.AllTest.SetUp(), NUnit.Framework.Syntax.NotSamePathTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.PositiveTest.SetUp(), NUnit.Framework.Syntax.TextStartsWithTest.SetUp(), NUnit.Framework.Syntax.LessThanTest.SetUp(), NUnit.Framework.Syntax.PropertyTest_NotFollows.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer.SetUp(), NUnit.Framework.Syntax.AssignableToTest.SetUp(), NUnit.Framework.Syntax.SomeTest.SetUp(), NUnit.Framework.Syntax.SamePathTest_RespectCase.SetUp(), NUnit.Framework.Syntax.NegativeTest.SetUp(), NUnit.Framework.Syntax.LessThanOrEqualTest.SetUp(), NUnit.Framework.Syntax.StartsWithTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.LengthTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer_Descending.SetUp(), NUnit.Framework.Syntax.SomeTest_BeforeBinaryOperators.SetUp(), NUnit.Framework.Syntax.AttributeTest.SetUp(), NUnit.Framework.Syntax.NaNTest.SetUp(), NUnit.Framework.Syntax.EndsWithTest.SetUp(), NUnit.Framework.Syntax.AtMostTest.SetUp(), NUnit.Framework.Syntax.NotSamePathTest_RespectCase.SetUp(), NUnit.Framework.Syntax.CountTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest.SetUp(), NUnit.Framework.Syntax.SomeTest_NestedSome.SetUp(), NUnit.Framework.Syntax.AttributeTestWithFollowingConstraint.SetUp(), NUnit.Framework.Syntax.EndsWithTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.MessageTest.SetUp(), NUnit.Framework.Syntax.SamePathOrUnderTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Descending.SetUp(), NUnit.Framework.Syntax.SomeTest_UseOfAndSome.SetUp(), NUnit.Framework.Syntax.ExactTypeTest_Generic.SetUp(), NUnit.Framework.Syntax.RegexTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer.SetUp(), NUnit.Framework.Syntax.SamePathOrUnderTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.NoneTest.SetUp(), NUnit.Framework.Syntax.InstanceOfTest_Generic.SetUp(), NUnit.Framework.Syntax.RegexTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer_Descending.SetUp(), NUnit.Framework.Syntax.NotSamePathOrUnderTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.AndTest.SetUp(), NUnit.Framework.Syntax.AssignableFromTest_Generic.SetUp(), NUnit.Framework.Syntax.CollectionContainsTest.SetUp(), NUnit.Framework.Syntax.SamePathOrUnderTest_RespectCase.SetUp(), NUnit.Framework.Syntax.AndTest_ThreeAndsWithNot.SetUp(), NUnit.Framework.Syntax.AssignableToTest_Generic.SetUp(), NUnit.Framework.Syntax.CollectionSubsetTest.SetUp(), NUnit.Framework.Syntax.OrTest.SetUp(), NUnit.Framework.Syntax.NotSamePathOrUnderTest_RespectCase.SetUp(), NUnit.Framework.Syntax.AttributeTest_Generic.SetUp(), NUnit.Framework.Syntax.CollectionEquivalentTest.SetUp(), NUnit.Framework.Syntax.OrTest_ThreeOrs.SetUp(), NUnit.Framework.Syntax.AndIsEvaluatedBeforeFollowingOr.SetUp(), NUnit.Framework.Syntax.AndIsEvaluatedBeforePrecedingOr.SetUp(), and NUnit.Framework.Syntax.SyntaxTest.SupportedByConstraintBuilder().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Syntax/SyntaxTest.cs