Doc: IGLib EXTENDED: IG.Neural.Forms.NeuralControl2D Class Reference
IG.Neural.Forms.NeuralControl2D Class Reference
A 2D neural network approximation demo control.
Public Member Functions
NeuralControl2D ()
void PreparePlotter2D ()
void DecorHandler ()
Initialize decoration handler.
void GenerateDefaultPoints2D ()
Generates the set of default points according to settings.
void DefaultGraph2D ()
Generates plot from default points according to settings.
void RemoveDefaultActors ()
void GenerateTrainingPoints2D ()
Generates the set of training points according to settings.
void TrainingPointsGraph ()
Generates plot from training points according to settings.
void RemoveTrainingPointsActors ()
void ApproximationGraph ()
Generates plot from approximated points according to settings.
void RemoveApproximationActors ()
void ApproximationContourGraph ()
Generates conture plot from approximated points according to settings.
void RemoveApproximationContureActors ()
void DefaultContourGraph ()
Generates conture plot from default points according to settings.
void RemoveDefaultContureActors ()
void SclarBar2D (double minRange, double maxRange, ColorScale Color)
Scalar bar initialization.
void Bounds2D ()
void ResetAll2D ()
Invalidates training results AND training data, and makes corresponding changes in GUI (e.g. disables certain buttons, etc.).
void ResetResults2D ()
Invalidates the training results and makes corresponding changes in GUI to reflect this.
void PrepareApproximationPolts ()
Prepare approximation plots.
void PrepareDefaultPlotsWithoutShow ()
void PrepareDefaultPlots ()
Prepare default plots of.
void ResetTooltipProperties ()
NeuralControl2D ()
void PreparePlotter2D ()
void DecorHandler ()
Initialize decoration handler.
void GenerateDefaultPoints2D ()
Generates the set of default points according to settings.
void DefaultGraph2D ()
Generates plot from default points according to settings.
void RemoveDefaultActors ()
void GenerateTrainingPoints2D ()
Generates the set of training points according to settings.
void TrainingPointsGraph ()
Generates plot from training points according to settings.
void RemoveTrainingPointsActors ()
void ApproximationGraph ()
Generates plot from approximated points according to settings.
void RemoveApprovimationActors ()
void ApproximationContourGraph ()
Generates conture plot from approximated points according to settings.
void RemoveApprovimationContureActors ()
void DefaultContourGraph ()
Generates conture plot from default points according to settings.
void RemoveDefaultContureActors ()
void SclarBar2D (double minRange, double maxRange, ColorScale Color)
Scalar bar initialization.
void Bounds2D ()
void ResetAll2D ()
Reset all to default.
void PrepareApproximationPolts ()
Prepare approximation plots.
void PrepareDefaultPlotsWithoutShow ()
void PrepareDefaultPlots ()
Prepare default plots of.
NeuralControl2D ()
void PreparePlotter2D ()
void DecorHandler ()
Initialize decoration handler.
void GenerateDefaultPoints2D ()
Generates the set of default points according to settings.
void DefaultGraph2D ()
Generates plot from default points according to settings.
void RemoveDefaultActors ()
void GenerateTrainingPoints2D ()
Generates the set of training points according to settings.
void TrainingPointsGraph ()
Generates plot from training points according to settings.
void RemoveTrainingPointsActors ()
void ApproximationGraph ()
Generates plot from approximated points according to settings.
void RemoveApproximationActors ()
void ApproximationContourGraph ()
Generates conture plot from approximated points according to settings.
void RemoveApproximationContureActors ()
void DefaultContourGraph ()
Generates conture plot from default points according to settings.
void RemoveDefaultContureActors ()
void SclarBar2D (double minRange, double maxRange, ColorScale Color)
Scalar bar initialization.
void Bounds2D ()
void ResetAll2D ()
Invalidates training results AND training data, and makes corresponding changes in GUI (e.g. disables certain buttons, etc.).
void ResetResults2D ()
Invalidates the training results and makes corresponding changes in GUI to reflect this.
void PrepareApproximationPolts ()
Prepare approximation plots.
void PrepareDefaultPlotsWithoutShow ()
void PrepareDefaultPlots ()
Prepare default plots of.
NeuralControl2D ()
void PreparePlotter2D ()
void DecorHandler ()
Initialize decoration handler.
void GenerateDefaultPoints2D ()
Generates the set of default points according to settings.
void DefaultGraph2D ()
Generates plot from default points according to settings.
void RemoveDefaultActors ()
void GenerateTrainingPoints2D ()
Generates the set of training points according to settings.
void TrainingPointsGraph ()
Generates plot from training points according to settings.
void RemoveTrainingPointsActors ()
void ApproximationGraph ()
Generates plot from approximated points according to settings.
void RemoveApproximationActors ()
void ApproximationContourGraph ()
Generates conture plot from approximated points according to settings.
void RemoveApproximationContureActors ()
void DefaultContourGraph ()
Generates conture plot from default points according to settings.
void RemoveDefaultContureActors ()
void SclarBar2D (double minRange, double maxRange, ColorScale Color)
Scalar bar initialization.
void Bounds2D ()
void ResetAll2D ()
Invalidates training results AND training data, and makes corresponding changes in GUI (e.g. disables certain buttons, etc.).
void ResetResults2D ()
Invalidates the training results and makes corresponding changes in GUI to reflect this.
void PrepareApproximationPolts ()
Prepare approximation plots.
void PrepareDefaultPlotsWithoutShow ()
void PrepareDefaultPlots ()
Prepare default plots of.
NeuralControl2D ()
void PreparePlotter2D ()
void DecorHandler ()
Initialize decoration handler.
void GenerateDefaultPoints2D ()
Generates the set of default points according to settings.
void DefaultGraph2D ()
Generates plot from default points according to settings.
void RemoveDefaultActors ()
void GenerateTrainingPoints2D ()
Generates the set of training points according to settings.
void TrainingPointsGraph ()
Generates plot from training points according to settings.
void RemoveTrainingPointsActors ()
void ApproximationGraph ()
Generates plot from approximated points according to settings.
void RemoveApproximationActors ()
void ApproximationContourGraph ()
Generates conture plot from approximated points according to settings.
void RemoveApproximationContureActors ()
void DefaultContourGraph ()
Generates conture plot from default points according to settings.
void RemoveDefaultContureActors ()
void SclarBar2D (double minRange, double maxRange, ColorScale Color)
Scalar bar initialization.
void Bounds2D ()
void ResetAll2D ()
Invalidates training results AND training data, and makes corresponding changes in GUI (e.g. disables certain buttons, etc.).
void ResetResults2D ()
Invalidates the training results and makes corresponding changes in GUI to reflect this.
void PrepareApproximationPolts ()
Prepare approximation plots.
void PrepareDefaultPlotsWithoutShow ()
void PrepareDefaultPlots ()
Prepare default plots of.
void ResetTooltipProperties ()
Static Public Member Functions
static ColorScale CreateGreenRedYellow (double minValue, double maxValue)
static ColorScale CreateGreenRedYellow (double minValue, double maxValue)
static ColorScale CreateGreenRedYellow (double minValue, double maxValue)
static ColorScale CreateGreenRedYellow (double minValue, double maxValue)
static ColorScale CreateGreenRedYellow (double minValue, double maxValue)
Public Attributes
System.ComponentModel.BackgroundWorker backgroundWorker2D
Protected Member Functions
void SetNetworkParameters (INeuralApproximator neural)
Prepares network parameters.
void Approximator_BundleCompleted (object obj, EventArgs args)
Event handler that is executed when a new bundle of training epochs completes.
void Aproximator_TrainingCompleted (object obj, EventArgs args)
Event handler that is executed when a new bundle of training epochs completes.
INeuralApproximator TrainNetwork (SampledDataSet trainingData, SampledDataSet verificationData)
Performs training of neural network.
void ShowPlot ()
Shows the plot.
override void Dispose (bool disposing)
Clean up any resources being used.
void ShowPlot ()
Shows the plot.
override void Dispose (bool disposing)
Clean up any resources being used.
void SetNetworkParameters (INeuralApproximator neural)
Prepares network parameters.
void Approximator_BundleCompleted (object obj, EventArgs args)
Event handler that is executed when a new bundle of training epochs completes.
void Aproximator_TrainingCompleted (object obj, EventArgs args)
Event handler that is executed when a new bundle of training epochs completes.
INeuralApproximator TrainNetwork (SampledDataSet trainingData, SampledDataSet verificationData)
Performs training of neural network.
void ShowPlot ()
Shows the plot.
override void Dispose (bool disposing)
Clean up any resources being used.
void SetNetworkParameters (INeuralApproximator neural)
Prepares network parameters.
void Approximator_BundleCompleted (object obj, EventArgs args)
Event handler that is executed when a new bundle of training epochs completes.
void Aproximator_TrainingCompleted (object obj, EventArgs args)
Event handler that is executed when a new bundle of training epochs completes.
INeuralApproximator TrainNetwork (SampledDataSet trainingData, SampledDataSet verificationData)
Performs training of neural network.
void ShowPlot ()
Shows the plot.
override void Dispose (bool disposing)
Clean up any resources being used.
void SetNetworkParameters (INeuralApproximator neural)
Prepares network parameters.
void Approximator_BundleCompleted (object obj, EventArgs args)
Event handler that is executed when a new bundle of training epochs completes.
void Aproximator_TrainingCompleted (object obj, EventArgs args)
Event handler that is executed when a new bundle of training epochs completes.
INeuralApproximator TrainNetwork (SampledDataSet trainingData, SampledDataSet verificationData)
Performs training of neural network.
void ShowPlot ()
Shows the plot.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
INeuralApproximator _neuralApproximator
int _displayTimeMs = 2000
int _delayTimeMs = 2000
Properties
int OutputLevel [get, set]
Level of output to console.
virtual INeuralApproximator NeuralApproximator [get, set]
Neural approximator.
bool BreakTraining [get, set]
BoundingBox3d ScaledBounds [get]
Color ToolTipBackground [get, set]
Tooltip's foreground color.
Color ToolTipForeground [get, set]
Tooltip's background color.
bool IsToolTipActive [get, set]
Whether the tooltip is active and is being displayed for controls or not.
int ToolTipDisplayTimeMs [get, set]
int ToolTipDelayTimeMs [get, set]
Properties inherited from IG.Neural.INeuralApproximatorContainer
INeuralApproximator NeuralApproximator [get, set]
Gets or sets th the neural approximator for the containing class.
Private Member Functions
void LoadForm (object sender, EventArgs e)
void InitializeApproximator2D ()
Clean and initialize the approximator.
void InitializeTrainingData2D ()
Clean and initialize the training data set.
void InitializeVerificationData2D ()
Clean and initialize the verification data set.
void InitializeDefaultData2D ()
Clean and initialize the default data set.
void WriteErrors2D ()
Write training and verification errors in text box.
void ClearErrorGraph2D ()
Clear Graph with error convergence for 2 dimension.
void btReset2D_Click (object sender, EventArgs e)
Reset button.
void btStart2D_Click (object sender, EventArgs e)
Start training button.
void btnShowApprox_Click (object sender, EventArgs e)
void btStop2D_Click (object sender, EventArgs e)
Stop training button.
void TrainNetworkThread2D ()
void btnGenerateOptData2D_Click (object sender, EventArgs e)
Generate training data button.
void btnShowDefault_Click (object sender, EventArgs e)
Show default graph button.
void rbMaxTrainError2D_CheckedChanged (object sender, EventArgs e)
Enable Maximum training error convergence to be written on graph.
void rbRmsTrainError2D_CheckedChanged (object sender, EventArgs e)
Enable Rms training error convergence to be written on graph.
void rbMaxVerError2D_CheckedChanged (object sender, EventArgs e)
Enable Maximum verification error convergence to be written on graph.
void rbRmsVerError2D_CheckedChanged (object sender, EventArgs e)
Enable Rms verification error convergence to be written on graph.
void cbSelfMade2D_CheckedChanged (object sender, EventArgs e)
Enable posibility to self made the equation.
void cbTrainingPoints2D_CheckedChanged (object sender, EventArgs e)
Enable training points on graph.
void cbDefaultSurface2D_CheckedChanged (object sender, EventArgs e)
Enable surface for default function on graph.
void cbDefaultGreed2D_CheckedChanged (object sender, EventArgs e)
Enable greed for default function on graph.
void cbApproximationSurface2D_CheckedChanged (object sender, EventArgs e)
Enable surface for approximation function on graph.
void cbApproximationGreed2D_CheckedChanged (object sender, EventArgs e)
Enable greed for approximation function on graph.
void cbContourDefault2D_CheckedChanged (object sender, EventArgs e)
Enable conture for default function on graph.
void cbContourApproximation2D_CheckedChanged (object sender, EventArgs e)
Enable conture for approximation function on graph.
void cbRandomData2D_CheckedChanged (object sender, EventArgs e)
Enable random training points.
void cbScaleTo_CheckedChanged (object sender, EventArgs e)
Enable scaling to range 1.
void trackbDefaultGraph2D_Scroll (object sender, EventArgs e)
Opacity for visualization of default function.
void trackbApproxGraph2D_Scroll (object sender, EventArgs e)
Opacity for visualization of approximation function.
void trackbContourGraph2D_Scroll (object sender, EventArgs e)
Opacity for visualization of contures.
void cbEquation2D_SelectedIndexChanged (object sender, EventArgs e)
Select equation from the list.
void tbSelfMadeEquation2D_TextChanged (object sender, EventArgs e)
void numSamplesX2D_ValueChanged (object sender, EventArgs e)
Number of training samples on X axe.
void numSamplesY2D_ValueChanged (object sender, EventArgs e)
Number of training samples on Y axe.
void numLowXLimit2D_ValueChanged (object sender, EventArgs e)
Lower limit for x-axes on the graph.
void numHighXLimit2D_ValueChanged (object sender, EventArgs e)
Higher limit for x-axes on the graph.
void numHighYLimit2D_ValueChanged (object sender, EventArgs e)
Higher limit for y-axes on the graph.
void numLowYLimit2D_ValueChanged (object sender, EventArgs e)
Lower limit for y-axes on the graph.
void numMaxEpoch2D_ValueChanged (object sender, EventArgs e)
Maximum number of epochs.
void numEpochBundle2D_ValueChanged (object sender, EventArgs e)
Number of epochs in bundle.
void numRMS2D_ValueChanged (object sender, EventArgs e)
Rms error limit.
void numLearningRate2D_ValueChanged (object sender, EventArgs e)
Learning rate.
void numMomentum2D_ValueChanged (object sender, EventArgs e)
Momentum.
void numHiddenNeuron2D_ValueChanged (object sender, EventArgs e)
Number of neurons in first hidden layer.
void numHiddenNeuronL22D_ValueChanged (object sender, EventArgs e)
Number of neurons in second hidden layer.
void numInputSafety2D_ValueChanged (object sender, EventArgs e)
Input safety factor.
void numOutputSafety2D_ValueChanged (object sender, EventArgs e)
Output safety factor.
void backgroundWorker2D_DoWork (object sender, DoWorkEventArgs e)
void backgroundWorker2D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
void menuTooltipEnabled_CheckedChanged (object sender, EventArgs e)
void resetToolStripMenuItem_Click (object sender, EventArgs e)
void menuTooltipBackground_Click (object sender, EventArgs e)
void menuTooltipForeground_Click (object sender, EventArgs e)
void menuTooltipDisplayTimeValue_Validated (object sender, EventArgs e)
void menuTooltipDelayValue_Validated (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void LoadForm (object sender, EventArgs e)
void InitializeApproximator2D ()
Clean and initialize the approximator.
void InitializeTrainingData2D ()
Clean and initialize the training data set.
void InitializeVerificationData2D ()
Clean and initialize the verification data set.
void InitializeDefaultData2D ()
Clean and initialize the default data set.
void WriteErrors2D ()
Write training and verification errors in text box.
void ClearErrorGraph2D ()
Clear Graph with error convergence for 2 dimension.
void btReset2D_Click (object sender, EventArgs e)
Reset button.
void btStart2D_Click (object sender, EventArgs e)
Start training button.
void btnShowApprox_Click (object sender, EventArgs e)
void btStop2D_Click (object sender, EventArgs e)
Stop training button.
void TrainNetworkThread2D ()
void btnGenerateOptData2D_Click (object sender, EventArgs e)
Generate training data button.
void btnShowDefault_Click (object sender, EventArgs e)
Show default graph button.
void rbMaxTrainError2D_CheckedChanged (object sender, EventArgs e)
Enable Maximum training error convergence to be written on graph.
void rbRmsTrainError2D_CheckedChanged (object sender, EventArgs e)
Enable Rms training error convergence to be written on graph.
void rbMaxVerError2D_CheckedChanged (object sender, EventArgs e)
Enable Maximum verification error convergence to be written on graph.
void rbRmsVerError2D_CheckedChanged (object sender, EventArgs e)
Enable Rms verification error convergence to be written on graph.
void cbSelfMade2D_CheckedChanged (object sender, EventArgs e)
Enable posibility to self made the equation.
void cbTrainingPoints2D_CheckedChanged (object sender, EventArgs e)
Enable training points on graph.
void cbDefaultSurface2D_CheckedChanged (object sender, EventArgs e)
Enable surface for default function on graph.
void cbDefaultGreed2D_CheckedChanged (object sender, EventArgs e)
Enable greed for default function on graph.
void cbApproximationSurface2D_CheckedChanged (object sender, EventArgs e)
Enable surface for approximation function on graph.
void cbApproximationGreed2D_CheckedChanged (object sender, EventArgs e)
Enable greed for approximation function on graph.
void cbContourDefault2D_CheckedChanged (object sender, EventArgs e)
Enable conture for default function on graph.
void cbContourApproximation2D_CheckedChanged (object sender, EventArgs e)
Enable conture for approximation function on graph.
void cbRandomData2D_CheckedChanged (object sender, EventArgs e)
Enable random training points.
void cbScaleTo_CheckedChanged (object sender, EventArgs e)
Enable scaling to range 1.
void trackbDefaultGraph2D_Scroll (object sender, EventArgs e)
Opacity for visualization of default function.
void trackbApproxGraph2D_Scroll (object sender, EventArgs e)
Opacity for visualization of approximation function.
void trackbContourGraph2D_Scroll (object sender, EventArgs e)
Opacity for visualization of contures.
void cbEquation2D_SelectedIndexChanged (object sender, EventArgs e)
Select equation from the list.
void tbSelfMadeEquation2D_TextChanged (object sender, EventArgs e)
void numSamplesX2D_ValueChanged (object sender, EventArgs e)
Number of training samples on X axe.
void numSamplesY2D_ValueChanged (object sender, EventArgs e)
Number of training samples on Y axe.
void numLowXLimit2D_ValueChanged (object sender, EventArgs e)
Lower limit for x-axes on the graph.
void numHighXLimit2D_ValueChanged (object sender, EventArgs e)
Higher limit for x-axes on the graph.
void numHighYLimit2D_ValueChanged (object sender, EventArgs e)
Higher limit for y-axes on the graph.
void numLowYLimit2D_ValueChanged (object sender, EventArgs e)
Lower limit for y-axes on the graph.
void numMaxEpoch2D_ValueChanged (object sender, EventArgs e)
Maximum number of epochs.
void numEpochBundle2D_ValueChanged (object sender, EventArgs e)
Number of epochs in bundle.
void numRMS2D_ValueChanged (object sender, EventArgs e)
Rms error limit.
void numLearningRate2D_ValueChanged (object sender, EventArgs e)
Learning rate.
void numMomentum2D_ValueChanged (object sender, EventArgs e)
Momentum.
void numHiddenNeuron2D_ValueChanged (object sender, EventArgs e)
Number of neurons in first hidden layer.
void numHiddenNeuronL22D_ValueChanged (object sender, EventArgs e)
Number of neurons in second hidden layer.
void numInputSafety2D_ValueChanged (object sender, EventArgs e)
Input safety factor.
void numOutputSafety2D_ValueChanged (object sender, EventArgs e)
Output safety factor.
void backgroundWorker2D_DoWork (object sender, DoWorkEventArgs e)
void backgroundWorker2D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void LoadForm (object sender, EventArgs e)
void InitializeApproximator2D ()
Clean and initialize the approximator.
void InitializeTrainingData2D ()
Clean and initialize the training data set.
void InitializeVerificationData2D ()
Clean and initialize the verification data set.
void InitializeDefaultData2D ()
Clean and initialize the default data set.
void WriteErrors2D ()
Write training and verification errors in text box.
void ClearErrorGraph2D ()
Clear Graph with error convergence for 2 dimension.
void btReset2D_Click (object sender, EventArgs e)
Reset button.
void btStart2D_Click (object sender, EventArgs e)
Start training button.
void btnShowApprox_Click (object sender, EventArgs e)
void btStop2D_Click (object sender, EventArgs e)
Stop training button.
void TrainNetworkThread2D ()
void btnGenerateOptData2D_Click (object sender, EventArgs e)
Generate training data button.
void btnShowDefault_Click (object sender, EventArgs e)
Show default graph button.
void rbMaxTrainError2D_CheckedChanged (object sender, EventArgs e)
Enable Maximum training error convergence to be written on graph.
void rbRmsTrainError2D_CheckedChanged (object sender, EventArgs e)
Enable Rms training error convergence to be written on graph.
void rbMaxVerError2D_CheckedChanged (object sender, EventArgs e)
Enable Maximum verification error convergence to be written on graph.
void rbRmsVerError2D_CheckedChanged (object sender, EventArgs e)
Enable Rms verification error convergence to be written on graph.
void cbSelfMade2D_CheckedChanged (object sender, EventArgs e)
Enable posibility to self made the equation.
void cbTrainingPoints2D_CheckedChanged (object sender, EventArgs e)
Enable training points on graph.
void cbDefaultSurface2D_CheckedChanged (object sender, EventArgs e)
Enable surface for default function on graph.
void cbDefaultGreed2D_CheckedChanged (object sender, EventArgs e)
Enable greed for default function on graph.
void cbApproximationSurface2D_CheckedChanged (object sender, EventArgs e)
Enable surface for approximation function on graph.
void cbApproximationGreed2D_CheckedChanged (object sender, EventArgs e)
Enable greed for approximation function on graph.
void cbContourDefault2D_CheckedChanged (object sender, EventArgs e)
Enable conture for default function on graph.
void cbContourApproximation2D_CheckedChanged (object sender, EventArgs e)
Enable conture for approximation function on graph.
void cbRandomData2D_CheckedChanged (object sender, EventArgs e)
Enable random training points.
void cbScaleTo_CheckedChanged (object sender, EventArgs e)
Enable scaling to range 1.
void trackbDefaultGraph2D_Scroll (object sender, EventArgs e)
Opacity for visualization of default function.
void trackbApproxGraph2D_Scroll (object sender, EventArgs e)
Opacity for visualization of approximation function.
void trackbContourGraph2D_Scroll (object sender, EventArgs e)
Opacity for visualization of contures.
void cbEquation2D_SelectedIndexChanged (object sender, EventArgs e)
Select equation from the list.
void tbSelfMadeEquation2D_TextChanged (object sender, EventArgs e)
void numSamplesX2D_ValueChanged (object sender, EventArgs e)
Number of training samples on X axe.
void numSamplesY2D_ValueChanged (object sender, EventArgs e)
Number of training samples on Y axe.
void numLowXLimit2D_ValueChanged (object sender, EventArgs e)
Lower limit for x-axes on the graph.
void numHighXLimit2D_ValueChanged (object sender, EventArgs e)
Higher limit for x-axes on the graph.
void numHighYLimit2D_ValueChanged (object sender, EventArgs e)
Higher limit for y-axes on the graph.
void numLowYLimit2D_ValueChanged (object sender, EventArgs e)
Lower limit for y-axes on the graph.
void numMaxEpoch2D_ValueChanged (object sender, EventArgs e)
Maximum number of epochs.
void numEpochBundle2D_ValueChanged (object sender, EventArgs e)
Number of epochs in bundle.
void numRMS2D_ValueChanged (object sender, EventArgs e)
Rms error limit.
void numLearningRate2D_ValueChanged (object sender, EventArgs e)
Learning rate.
void numMomentum2D_ValueChanged (object sender, EventArgs e)
Momentum.
void numHiddenNeuron2D_ValueChanged (object sender, EventArgs e)
Number of neurons in first hidden layer.
void numHiddenNeuronL22D_ValueChanged (object sender, EventArgs e)
Number of neurons in second hidden layer.
void numInputSafety2D_ValueChanged (object sender, EventArgs e)
Input safety factor.
void numOutputSafety2D_ValueChanged (object sender, EventArgs e)
Output safety factor.
void backgroundWorker2D_DoWork (object sender, DoWorkEventArgs e)
void backgroundWorker2D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void LoadForm (object sender, EventArgs e)
void InitializeApproximator2D ()
Clean and initialize the approximator.
void InitializeTrainingData2D ()
Clean and initialize the training data set.
void InitializeVerificationData2D ()
Clean and initialize the verification data set.
void InitializeDefaultData2D ()
Clean and initialize the default data set.
void WriteErrors2D ()
Write training and verification errors in text box.
void ClearErrorGraph2D ()
Clear Graph with error convergence for 2 dimension.
void btReset2D_Click (object sender, EventArgs e)
Reset button.
void btStart2D_Click (object sender, EventArgs e)
Start training button.
void btnShowApprox_Click (object sender, EventArgs e)
void btStop2D_Click (object sender, EventArgs e)
Stop training button.
void TrainNetworkThread2D ()
void btnGenerateOptData2D_Click (object sender, EventArgs e)
Generate training data button.
void btnShowDefault_Click (object sender, EventArgs e)
Show default graph button.
void rbMaxTrainError2D_CheckedChanged (object sender, EventArgs e)
Enable Maximum training error convergence to be written on graph.
void rbRmsTrainError2D_CheckedChanged (object sender, EventArgs e)
Enable Rms training error convergence to be written on graph.
void rbMaxVerError2D_CheckedChanged (object sender, EventArgs e)
Enable Maximum verification error convergence to be written on graph.
void rbRmsVerError2D_CheckedChanged (object sender, EventArgs e)
Enable Rms verification error convergence to be written on graph.
void cbSelfMade2D_CheckedChanged (object sender, EventArgs e)
Enable posibility to self made the equation.
void cbTrainingPoints2D_CheckedChanged (object sender, EventArgs e)
Enable training points on graph.
void cbDefaultSurface2D_CheckedChanged (object sender, EventArgs e)
Enable surface for default function on graph.
void cbDefaultGreed2D_CheckedChanged (object sender, EventArgs e)
Enable greed for default function on graph.
void cbApproximationSurface2D_CheckedChanged (object sender, EventArgs e)
Enable surface for approximation function on graph.
void cbApproximationGreed2D_CheckedChanged (object sender, EventArgs e)
Enable greed for approximation function on graph.
void cbContourDefault2D_CheckedChanged (object sender, EventArgs e)
Enable conture for default function on graph.
void cbContourApproximation2D_CheckedChanged (object sender, EventArgs e)
Enable conture for approximation function on graph.
void cbRandomData2D_CheckedChanged (object sender, EventArgs e)
Enable random training points.
void cbScaleTo_CheckedChanged (object sender, EventArgs e)
Enable scaling to range 1.
void trackbDefaultGraph2D_Scroll (object sender, EventArgs e)
Opacity for visualization of default function.
void trackbApproxGraph2D_Scroll (object sender, EventArgs e)
Opacity for visualization of approximation function.
void trackbContourGraph2D_Scroll (object sender, EventArgs e)
Opacity for visualization of contures.
void cbEquation2D_SelectedIndexChanged (object sender, EventArgs e)
Select equation from the list.
void tbSelfMadeEquation2D_TextChanged (object sender, EventArgs e)
void numSamplesX2D_ValueChanged (object sender, EventArgs e)
Number of training samples on X axe.
void numSamplesY2D_ValueChanged (object sender, EventArgs e)
Number of training samples on Y axe.
void numLowXLimit2D_ValueChanged (object sender, EventArgs e)
Lower limit for x-axes on the graph.
void numHighXLimit2D_ValueChanged (object sender, EventArgs e)
Higher limit for x-axes on the graph.
void numHighYLimit2D_ValueChanged (object sender, EventArgs e)
Higher limit for y-axes on the graph.
void numLowYLimit2D_ValueChanged (object sender, EventArgs e)
Lower limit for y-axes on the graph.
void numMaxEpoch2D_ValueChanged (object sender, EventArgs e)
Maximum number of epochs.
void numEpochBundle2D_ValueChanged (object sender, EventArgs e)
Number of epochs in bundle.
void numRMS2D_ValueChanged (object sender, EventArgs e)
Rms error limit.
void numLearningRate2D_ValueChanged (object sender, EventArgs e)
Learning rate.
void numMomentum2D_ValueChanged (object sender, EventArgs e)
Momentum.
void numHiddenNeuron2D_ValueChanged (object sender, EventArgs e)
Number of neurons in first hidden layer.
void numHiddenNeuronL22D_ValueChanged (object sender, EventArgs e)
Number of neurons in second hidden layer.
void numInputSafety2D_ValueChanged (object sender, EventArgs e)
Input safety factor.
void numOutputSafety2D_ValueChanged (object sender, EventArgs e)
Output safety factor.
void backgroundWorker2D_DoWork (object sender, DoWorkEventArgs e)
void backgroundWorker2D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void LoadForm (object sender, EventArgs e)
void InitializeApproximator2D ()
Clean and initialize the approximator.
void InitializeTrainingData2D ()
Clean and initialize the training data set.
void InitializeVerificationData2D ()
Clean and initialize the verification data set.
void InitializeDefaultData2D ()
Clean and initialize the default data set.
void WriteErrors2D ()
Write training and verification errors in text box.
void ClearErrorGraph2D ()
Clear Graph with error convergence for 2 dimension.
void btReset2D_Click (object sender, EventArgs e)
Reset button.
void btStart2D_Click (object sender, EventArgs e)
Start training button.
void btnShowApprox_Click (object sender, EventArgs e)
void btStop2D_Click (object sender, EventArgs e)
Stop training button.
void TrainNetworkThread2D ()
void btnGenerateOptData2D_Click (object sender, EventArgs e)
Generate training data button.
void btnShowDefault_Click (object sender, EventArgs e)
Show default graph button.
void rbMaxTrainError2D_CheckedChanged (object sender, EventArgs e)
Enable Maximum training error convergence to be written on graph.
void rbRmsTrainError2D_CheckedChanged (object sender, EventArgs e)
Enable Rms training error convergence to be written on graph.
void rbMaxVerError2D_CheckedChanged (object sender, EventArgs e)
Enable Maximum verification error convergence to be written on graph.
void rbRmsVerError2D_CheckedChanged (object sender, EventArgs e)
Enable Rms verification error convergence to be written on graph.
void cbSelfMade2D_CheckedChanged (object sender, EventArgs e)
Enable posibility to self made the equation.
void cbTrainingPoints2D_CheckedChanged (object sender, EventArgs e)
Enable training points on graph.
void cbDefaultSurface2D_CheckedChanged (object sender, EventArgs e)
Enable surface for default function on graph.
void cbDefaultGreed2D_CheckedChanged (object sender, EventArgs e)
Enable greed for default function on graph.
void cbApproximationSurface2D_CheckedChanged (object sender, EventArgs e)
Enable surface for approximation function on graph.
void cbApproximationGreed2D_CheckedChanged (object sender, EventArgs e)
Enable greed for approximation function on graph.
void cbContourDefault2D_CheckedChanged (object sender, EventArgs e)
Enable conture for default function on graph.
void cbContourApproximation2D_CheckedChanged (object sender, EventArgs e)
Enable conture for approximation function on graph.
void cbRandomData2D_CheckedChanged (object sender, EventArgs e)
Enable random training points.
void cbScaleTo_CheckedChanged (object sender, EventArgs e)
Enable scaling to range 1.
void trackbDefaultGraph2D_Scroll (object sender, EventArgs e)
Opacity for visualization of default function.
void trackbApproxGraph2D_Scroll (object sender, EventArgs e)
Opacity for visualization of approximation function.
void trackbContourGraph2D_Scroll (object sender, EventArgs e)
Opacity for visualization of contures.
void cbEquation2D_SelectedIndexChanged (object sender, EventArgs e)
Select equation from the list.
void tbSelfMadeEquation2D_TextChanged (object sender, EventArgs e)
void numSamplesX2D_ValueChanged (object sender, EventArgs e)
Number of training samples on X axe.
void numSamplesY2D_ValueChanged (object sender, EventArgs e)
Number of training samples on Y axe.
void numLowXLimit2D_ValueChanged (object sender, EventArgs e)
Lower limit for x-axes on the graph.
void numHighXLimit2D_ValueChanged (object sender, EventArgs e)
Higher limit for x-axes on the graph.
void numHighYLimit2D_ValueChanged (object sender, EventArgs e)
Higher limit for y-axes on the graph.
void numLowYLimit2D_ValueChanged (object sender, EventArgs e)
Lower limit for y-axes on the graph.
void numMaxEpoch2D_ValueChanged (object sender, EventArgs e)
Maximum number of epochs.
void numEpochBundle2D_ValueChanged (object sender, EventArgs e)
Number of epochs in bundle.
void numRMS2D_ValueChanged (object sender, EventArgs e)
Rms error limit.
void numLearningRate2D_ValueChanged (object sender, EventArgs e)
Learning rate.
void numMomentum2D_ValueChanged (object sender, EventArgs e)
Momentum.
void numHiddenNeuron2D_ValueChanged (object sender, EventArgs e)
Number of neurons in first hidden layer.
void numHiddenNeuronL22D_ValueChanged (object sender, EventArgs e)
Number of neurons in second hidden layer.
void numInputSafety2D_ValueChanged (object sender, EventArgs e)
Input safety factor.
void numOutputSafety2D_ValueChanged (object sender, EventArgs e)
Output safety factor.
void backgroundWorker2D_DoWork (object sender, DoWorkEventArgs e)
void backgroundWorker2D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
void menuTooltipEnabled_CheckedChanged (object sender, EventArgs e)
void resetToolStripMenuItem_Click (object sender, EventArgs e)
void menuTooltipBackground_Click (object sender, EventArgs e)
void menuTooltipForeground_Click (object sender, EventArgs e)
void menuTooltipDisplayTimeValue_Validated (object sender, EventArgs e)
void menuTooltipDelayValue_Validated (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
int _outputLevel = 0
GraphPane pane2DError
Error graph.
SampledDataSet trainingData2D = null
Training data set.
SampledDataSet verificationData2D = null
Verification data set.
SampledDataSet defaultFunctionData2D = null
Default data set.
int hiddenNeuronL12D = 5
int hiddenNeuronL22D = 0
int maxEpoch2D = 5000
int epochInBundle2D = 500
double rmsError2D = 0.001
double learningRate2D = 0.3
double momentum2D = 0.6
int samplesX2D = 5
int samplesY2D = 5
double lowHorizontalLimit2D = -1.0
double highHorizontalLimit2D = 1.0
double lowVerticalLimit2D = -1.0
double highVerticalLimit2D = 1.0
double lowVerificationHorizontalLimit2D = -5.0
double highVerificationHorizontalLimit2D = 5.0
double inputSafetyFactor2D = 1.3
double outputSafetyFactor2D = 1.3
string equation2D = "x*x + y*y"
string[] variableNames2D = { "x", "y" }
bool maxTrainErrorEnabled2D = true
bool rmsTrainErrorEnabled2D = false
bool maxVerErrorEnabled2D = false
bool rmsVerErrorEnabled2D = false
bool defaultSurfaceonGraph = false
bool defaultGreedonGraph = true
bool trainingPointsonGraph = true
bool approximationSurfaceonGraph = true
bool approximationGreedonGraph = false
bool contureDefaultonGraph = false
bool contureApproximationonGraph = false
bool stopTraining2D = false
bool stopTraining1D = false
double opacityDefaultGraph2D = 0.5
double opacityApproxGraph2D = 0.7
double opacityContourGraph2D = 1.0
int numAllXPoints2D = 100
int numAllYPoints2D = 100
LineItem errorConvergenceFunction2D
VtkPlotter plotter2D
Plotter.
Func2dFromScalarFunction iFunctionDefault2D
Scalar function that is approximated.
IScalarFunction scalarFunctionDefault2D
Scalar function that is approximated.
StructuredMesh2d3d Default2DMesh
Maeh of default points used for plotting.
VtkSurfacePlot plotDefault2D
Plot from default points.
VtkContourPlot plotApproximationConture2D
Conture Plot from approximated points.
IScalarFunction scalarFunctionTraining2D
Scalar function that is approximated.
StructuredMesh2d3d TrainingPointsMesh2D
Maeh of training points used for plotting.
VtkSurfacePlot plotTrainingPoints2D
Plot from training points.
Func2dFromApproximator iFunctionApproximator2D
Scalar function that is approximated.
ExampleValueFunctionDiff3D iFunctionDifference2D
Scalar function that is a difference default and approximated function.
VtkSurfacePlot plotApproximation2D
Plot from approximated points.
VtkContourPlot plotDefaultConture2D
Conture Plot from default points.
BoundingBox2d paramBounds2D
Bounding box for function limits. </summary
bool _breakTraining = false
BoundingBox3d _scaledBounds
Color _toolTipBackground = Color.LightBlue
Color _toolTipForeground = Color.Black
bool _isTooltipActive = true
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.TrackBar trackbContourGraph2D
System.Windows.Forms.Label label37
System.Windows.Forms.CheckBox cbContourDefault2D
System.Windows.Forms.CheckBox cbContourApproximation2D
System.Windows.Forms.CheckBox cbTrainingPoints2D
System.Windows.Forms.Label label36
System.Windows.Forms.CheckBox cbApproximationGreed2D
System.Windows.Forms.CheckBox cbApproximationSurface2D
System.Windows.Forms.Label label34
System.Windows.Forms.TrackBar trackbApproxGraph2D
System.Windows.Forms.CheckBox cbDefaultGreed2D
System.Windows.Forms.TrackBar trackbDefaultGraph2D
System.Windows.Forms.CheckBox cbDefaultSurface2D
System.Windows.Forms.Label label35
System.Windows.Forms.NumericUpDown numHighXLimit2D
System.Windows.Forms.Label label30
System.Windows.Forms.NumericUpDown numHighYLimit2D
System.Windows.Forms.NumericUpDown numLowYLimit2D
System.Windows.Forms.NumericUpDown numLowXLimit2D
System.Windows.Forms.Label label31
System.Windows.Forms.Label label32
System.Windows.Forms.Label label33
System.Windows.Forms.TextBox tbEquationError2D
System.Windows.Forms.RadioButton rbRmsTrainError2D
System.Windows.Forms.RadioButton rbMaxTrainError2D
System.Windows.Forms.RadioButton rbRmsVerError2D
System.Windows.Forms.RadioButton rbMaxVerError2D
System.Windows.Forms.TextBox tbRmsTrainError2D
System.Windows.Forms.Label label26
System.Windows.Forms.Label label27
System.Windows.Forms.TextBox tbMaxTrainError2D
System.Windows.Forms.TextBox tbRmsVerError2D
System.Windows.Forms.TextBox tbMaxVerError2D
System.Windows.Forms.Label label28
System.Windows.Forms.Label label29
ZedGraph.ZedGraphControl errorConvergence2D
System.Windows.Forms.NumericUpDown numHiddenNeuronL22D
System.Windows.Forms.NumericUpDown numHiddenNeuron2D
System.Windows.Forms.Button btLoadANN2D
System.Windows.Forms.Button btSaveANN2D
System.Windows.Forms.Button btReset2D
System.Windows.Forms.Button btStart2D
System.Windows.Forms.NumericUpDown numOutputSafety2D
System.Windows.Forms.Label label17
System.Windows.Forms.NumericUpDown numInputSafety2D
System.Windows.Forms.Label label18
System.Windows.Forms.Label label20
System.Windows.Forms.NumericUpDown numMomentum2D
System.Windows.Forms.NumericUpDown numLearningRate2D
System.Windows.Forms.NumericUpDown numRMS2D
System.Windows.Forms.NumericUpDown numEpochBundle2D
System.Windows.Forms.NumericUpDown numMaxEpoch2D
System.Windows.Forms.Label label21
System.Windows.Forms.Label label22
System.Windows.Forms.Label label23
System.Windows.Forms.Label label24
System.Windows.Forms.Label label25
System.Windows.Forms.CheckBox cbRandomData2D
System.Windows.Forms.Button btnGenerateOptData2D
System.Windows.Forms.NumericUpDown numSamplesX2D
System.Windows.Forms.Label label14
System.Windows.Forms.ComboBox cbEquation2D
System.Windows.Forms.TextBox tbSelfMadeEquation2D
System.Windows.Forms.Label label3
System.Windows.Forms.CheckBox cbSelfMade2D
System.Windows.Forms.Button btLoad2D
System.Windows.Forms.GroupBox groupBox3
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.NumericUpDown numSamplesY2D
System.Windows.Forms.Label label10
System.Windows.Forms.GroupBox groupBox4
System.Windows.Forms.Button btStop2D
System.Windows.Forms.GroupBox groupBox8
System.Windows.Forms.CheckBox cbScaleTo
System.Windows.Forms.Button btnShowDefault
System.Windows.Forms.Button btnShowApprox
System.Windows.Forms.ProgressBar progressBar1
System.Windows.Forms.ToolTip toolTip1
System.Windows.Forms.ContextMenuStrip contextMenuStrip1
System.Windows.Forms.ToolStripMenuItem menuTooltips
System.Windows.Forms.ToolStripMenuItem menuTooltipEnabled
System.Windows.Forms.ToolStripMenuItem menuTooltipColor
System.Windows.Forms.ToolStripMenuItem menuTooltipBackground
System.Windows.Forms.ToolStripMenuItem menuTooltipForeground
System.Windows.Forms.ColorDialog colorDialog1
System.Windows.Forms.ToolTip toolTip2
System.Windows.Forms.ToolStripMenuItem resetToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem menuDelayTime
System.Windows.Forms.ToolStripMenuItem menuDisplayTime
System.Windows.Forms.ToolStripTextBox menuTooltipDelayValue
System.Windows.Forms.ToolStripTextBox menuTooltipDisplayTimeValue
NeuralNetworks network2D
ANN.
Detailed Description
A 2D neural network approximation demo control.
$A Tadej xx; Igor Feb13;
Constructor & Destructor Documentation
NeuralControl2D() [1/5]
IG.Neural.Forms.NeuralControl2D.NeuralControl2D () inline
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.highHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.highVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.InitializeComponent(), IG.Neural.Forms.NeuralControl2D.IsToolTipActive, IG.Neural.Forms.NeuralControl2D.lowHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.lowVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.menuTooltipColor, IG.Neural.Forms.NeuralControl2D.menuTooltipDelayValue, IG.Neural.Forms.NeuralControl2D.menuTooltipDisplayTimeValue, IG.Neural.Forms.NeuralControl2D.numHighXLimit2D, IG.Neural.Forms.NeuralControl2D.numHighYLimit2D, IG.Neural.Forms.NeuralControl2D.numLowXLimit2D, IG.Neural.Forms.NeuralControl2D.numLowYLimit2D, IG.Neural.Forms.NeuralControl2D.toolTip1, IG.Neural.Forms.NeuralControl2D.ToolTipBackground, IG.Neural.Forms.NeuralControl2D.ToolTipDelayTimeMs, IG.Neural.Forms.NeuralControl2D.ToolTipDisplayTimeMs, and IG.Neural.Forms.NeuralControl2D.ToolTipForeground.
NeuralControl2D() [2/5]
IG.Neural.Forms.NeuralControl2D.NeuralControl2D () inline
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.highHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.highVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.InitializeComponent(), IG.Neural.Forms.NeuralControl2D.lowHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.lowVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.numHighXLimit2D, IG.Neural.Forms.NeuralControl2D.numHighYLimit2D, IG.Neural.Forms.NeuralControl2D.numLowXLimit2D, and IG.Neural.Forms.NeuralControl2D.numLowYLimit2D.
NeuralControl2D() [3/5]
IG.Neural.Forms.NeuralControl2D.NeuralControl2D () inline
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.highHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.highVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.InitializeComponent(), IG.Neural.Forms.NeuralControl2D.lowHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.lowVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.numHighXLimit2D, IG.Neural.Forms.NeuralControl2D.numHighYLimit2D, IG.Neural.Forms.NeuralControl2D.numLowXLimit2D, and IG.Neural.Forms.NeuralControl2D.numLowYLimit2D.
NeuralControl2D() [4/5]
IG.Neural.Forms.NeuralControl2D.NeuralControl2D () inline
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.highHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.highVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.InitializeComponent(), IG.Neural.Forms.NeuralControl2D.lowHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.lowVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.numHighXLimit2D, IG.Neural.Forms.NeuralControl2D.numHighYLimit2D, IG.Neural.Forms.NeuralControl2D.numLowXLimit2D, and IG.Neural.Forms.NeuralControl2D.numLowYLimit2D.
NeuralControl2D() [5/5]
IG.Neural.Forms.NeuralControl2D.NeuralControl2D () inline
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.highHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.highVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.InitializeComponent(), IG.Neural.Forms.NeuralControl2D.IsToolTipActive, IG.Neural.Forms.NeuralControl2D.lowHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.lowVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.menuTooltipColor, IG.Neural.Forms.NeuralControl2D.menuTooltipDelayValue, IG.Neural.Forms.NeuralControl2D.menuTooltipDisplayTimeValue, IG.Neural.Forms.NeuralControl2D.numHighXLimit2D, IG.Neural.Forms.NeuralControl2D.numHighYLimit2D, IG.Neural.Forms.NeuralControl2D.numLowXLimit2D, IG.Neural.Forms.NeuralControl2D.numLowYLimit2D, IG.Neural.Forms.NeuralControl2D.toolTip1, IG.Neural.Forms.NeuralControl2D.ToolTipBackground, IG.Neural.Forms.NeuralControl2D.ToolTipDelayTimeMs, IG.Neural.Forms.NeuralControl2D.ToolTipDisplayTimeMs, and IG.Neural.Forms.NeuralControl2D.ToolTipForeground.
Member Function Documentation
LoadForm() [1/5]
void IG.Neural.Forms.NeuralControl2D.LoadForm (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.errorConvergence2D, and IG.Neural.Forms.NeuralControl2D.pane2DError.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
CreateGreenRedYellow() [1/5]
static ColorScale IG.Neural.Forms.NeuralControl2D.CreateGreenRedYellow (double minValue, double maxValue) inline static
Referenced by IG.Neural.Forms.NeuralControl2D.ApproximationGraph().
InitializeApproximator2D() [1/5]
void IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D () inline private
Clean and initialize the approximator.
References IG.Neural.Forms.NeuralControl2D.Approximator_BundleCompleted(), IG.Neural.Forms.NeuralControl2D.Aproximator_TrainingCompleted(), IG.Num.INeuralApproximator.BundleCompleted, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Num.INeuralApproximator.OutputLevel, IG.Neural.Forms.NeuralControl2D.OutputLevel, and IG.Num.INeuralApproximator.TrainingCompleted.
Referenced by IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.ResetAll2D(), IG.Neural.Forms.NeuralControl2D.ResetResults2D(), and IG.Neural.Forms.NeuralControl2D.TrainNetwork().
InitializeTrainingData2D() [1/5]
void IG.Neural.Forms.NeuralControl2D.InitializeTrainingData2D () inline private
Clean and initialize the training data set.
References IG.Neural.Forms.NeuralControl2D.trainingData2D.
Referenced by IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
InitializeVerificationData2D() [1/5]
void IG.Neural.Forms.NeuralControl2D.InitializeVerificationData2D () inline private
Clean and initialize the verification data set.
References IG.Neural.Forms.NeuralControl2D.verificationData2D.
Referenced by IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
InitializeDefaultData2D() [1/5]
void IG.Neural.Forms.NeuralControl2D.InitializeDefaultData2D () inline private
Clean and initialize the default data set.
References IG.Neural.Forms.NeuralControl2D.defaultFunctionData2D.
Referenced by IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
WriteErrors2D() [1/5]
void IG.Neural.Forms.NeuralControl2D.WriteErrors2D () inline private
Write training and verification errors in text box.
References IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Num.INeuralApproximator.ConvergenceErrorsTrainingMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsTrainingRmsList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationRmsList, IG.Neural.Forms.NeuralControl2D.epochInBundle2D, IG.Neural.Forms.NeuralControl2D.errorConvergence2D, IG.Neural.Forms.NeuralControl2D.errorConvergenceFunction2D, IG.Num.INeuralApproximator.GetErrorsTrainingMax(), IG.Num.INeuralApproximator.GetErrorsTrainingRms(), IG.Num.INeuralApproximator.GetErrorsVerificationMax(), IG.Num.INeuralApproximator.GetErrorsVerificationRms(), IG.Neural.Forms.NeuralControl2D.maxTrainErrorEnabled2D, IG.Neural.Forms.NeuralControl2D.maxVerErrorEnabled2D, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.pane2DError, IG.Neural.Forms.NeuralControl2D.rmsTrainErrorEnabled2D, IG.Neural.Forms.NeuralControl2D.rmsVerErrorEnabled2D, IG.Neural.Forms.NeuralControl2D.tbMaxTrainError2D, IG.Neural.Forms.NeuralControl2D.tbMaxVerError2D, IG.Neural.Forms.NeuralControl2D.tbRmsTrainError2D, and IG.Neural.Forms.NeuralControl2D.tbRmsVerError2D.
Referenced by IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralControl2D.rbMaxTrainError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.rbMaxVerError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.rbRmsTrainError2D_CheckedChanged(), and IG.Neural.Forms.NeuralControl2D.rbRmsVerError2D_CheckedChanged().
ClearErrorGraph2D() [1/5]
void IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D () inline private
Clear Graph with error convergence for 2 dimension.
References IG.Neural.Forms.NeuralControl2D.errorConvergence2D, IG.Neural.Forms.NeuralControl2D.errorConvergenceFunction2D, IG.Neural.Forms.NeuralControl2D.tbMaxTrainError2D, IG.Neural.Forms.NeuralControl2D.tbMaxVerError2D, IG.Neural.Forms.NeuralControl2D.tbRmsTrainError2D, and IG.Neural.Forms.NeuralControl2D.tbRmsVerError2D.
Referenced by IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.ResetAll2D(), IG.Neural.Forms.NeuralControl2D.ResetResults2D(), and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
PreparePlotter2D() [1/5]
void IG.Neural.Forms.NeuralControl2D.PreparePlotter2D () inline
References IG.Neural.Forms.NeuralControl2D.plotter2D.
Referenced by IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), IG.Neural.Forms.NeuralControl2D.btnShowApprox_Click(), IG.Neural.Forms.NeuralControl2D.btnShowDefault_Click(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.ResetAll2D(), and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
DecorHandler() [1/5]
void IG.Neural.Forms.NeuralControl2D.DecorHandler () inline
Initialize decoration handler.
References IG.Gr3d.VtkPlotter.BackGround, IG.Gr3d.VtkDecorationHandler.CubeAxesFlyMode, IG.Gr3d.VtkDecorationHandler.CubeAxesXLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesYLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesZLabel, IG.Gr3d.VtkPlotter.DecorationHandler, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkPlotter.WindowSizeX, and IG.Gr3d.VtkPlotter.WindowSizeY.
Referenced by IG.Neural.Forms.NeuralControl2D.ShowPlot().
GenerateDefaultPoints2D() [1/5]
void IG.Neural.Forms.NeuralControl2D.GenerateDefaultPoints2D () inline
Generates the set of default points according to settings.
References IG.Num.Func2dFromScalarScript.CreateScalarFunction(), IG.Neural.Forms.NeuralControl2D.Default2DMesh, IG.Neural.Forms.NeuralControl2D.equation2D, IG.Num.StructuredMesh2d3d.GenerateCoordinates(), IG.Neural.Forms.NeuralControl2D.iFunctionDefault2D, IG.Num.BoundingBox2d.MaxX, IG.Num.BoundingBox2d.MaxY, IG.Num.BoundingBox2d.MinX, IG.Num.BoundingBox2d.MinY, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.scalarFunctionDefault2D, IG.Neural.Forms.NeuralControl2D.tbEquationError2D, IG.Num.IScalarFunctionUntransformed.Value(), and IG.Neural.Forms.NeuralControl2D.variableNames2D.
Referenced by IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click().
DefaultGraph2D() [1/5]
void IG.Neural.Forms.NeuralControl2D.DefaultGraph2D () inline
Generates plot from default points according to settings.
References IG.Neural.Forms.NeuralControl2D.contureApproximationonGraph, IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph, IG.Gr3d.VtkSurfacePlot.Create(), IG.Neural.Forms.NeuralControl2D.Default2DMesh, IG.Neural.Forms.NeuralControl2D.defaultGreedonGraph, IG.Neural.Forms.NeuralControl2D.defaultSurfaceonGraph, IG.Gr3d.VtkSurfacePlotBase.LineColor, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Neural.Forms.NeuralControl2D.opacityDefaultGraph2D, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D, IG.Neural.Forms.NeuralControl2D.plotDefault2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
Referenced by IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts(), and IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlotsWithoutShow().
RemoveDefaultActors() [1/5]
void IG.Neural.Forms.NeuralControl2D.RemoveDefaultActors () inline
References IG.Neural.Forms.NeuralControl2D.plotDefault2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
Referenced by IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
GenerateTrainingPoints2D() [1/5]
void IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D () inline
Generates the set of training points according to settings.
References IG.Num.SampledDataSet.AddElement(), IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.cbRandomData2D, IG.Num.Func2dFromScalarScript.CreateScalarFunction(), IG.Neural.Forms.NeuralControl2D.equation2D, IG.Num.StructuredMesh2d3d.GenerateCoordinates(), IG.Num.BoundingBoxBase.GetRandomPoint(), IG.Num.BoundingBox2d.MaxX, IG.Num.BoundingBox2d.MaxY, IG.Num.BoundingBox2d.MinX, IG.Num.BoundingBox2d.MinY, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.samplesX2D, IG.Neural.Forms.NeuralControl2D.samplesY2D, IG.Neural.Forms.NeuralControl2D.scalarFunctionTraining2D, IG.Neural.Forms.NeuralControl2D.trainingData2D, IG.Neural.Forms.NeuralControl2D.TrainingPointsMesh2D, IG.Num.IScalarFunctionUntransformed.Value(), and IG.Neural.Forms.NeuralControl2D.variableNames2D.
Referenced by IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click().
TrainingPointsGraph() [1/5]
void IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph () inline
Generates plot from training points according to settings.
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Neural.Forms.NeuralControl2D.plotTrainingPoints2D, IG.Gr3d.VtkSurfacePlotBase.PointColor, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible, IG.Neural.Forms.NeuralControl2D.TrainingPointsMesh2D, and IG.Neural.Forms.NeuralControl2D.trainingPointsonGraph.
Referenced by IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts(), and IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlotsWithoutShow().
RemoveTrainingPointsActors() [1/5]
void IG.Neural.Forms.NeuralControl2D.RemoveTrainingPointsActors () inline
References IG.Neural.Forms.NeuralControl2D.plotTrainingPoints2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
Referenced by IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), IG.Neural.Forms.NeuralControl2D.ResetAll2D(), and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
ApproximationGraph() [1/5]
void IG.Neural.Forms.NeuralControl2D.ApproximationGraph () inline
Generates plot from approximated points according to settings.
References IG.Neural.Forms.NeuralControl2D.approximationGreedonGraph, IG.Neural.Forms.NeuralControl2D.approximationSurfaceonGraph, IG.Gr3d.VtkSurfacePlot.Create(), IG.Neural.Forms.NeuralControl2D.CreateGreenRedYellow(), IG.Neural.Forms.NeuralControl2D.iFunctionApproximator2D, IG.Neural.Forms.NeuralControl2D.iFunctionDefault2D, IG.Neural.Forms.NeuralControl2D.iFunctionDifference2D, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LineColorScale, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Neural.Forms.NeuralControl2D.opacityApproxGraph2D, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotApproximation2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Neural.Forms.NeuralControl2D.SclarBar2D(), IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible, and IG.Gr3d.VtkSurfacePlot.ValueFunctionOfCoordinates.
Referenced by IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts().
RemoveApproximationActors() [1/4]
void IG.Neural.Forms.NeuralControl2D.RemoveApproximationActors () inline
References IG.Neural.Forms.NeuralControl2D.plotApproximation2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
Referenced by IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), IG.Neural.Forms.NeuralControl2D.ResetAll2D(), and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
ApproximationContourGraph() [1/5]
void IG.Neural.Forms.NeuralControl2D.ApproximationContourGraph () inline
Generates conture plot from approximated points according to settings.
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Lib.ColorScaleBase.CreateRainbow(), IG.Neural.Forms.NeuralControl2D.iFunctionApproximator2D, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Gr3d.VtkContourPlot.NumContours, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Neural.Forms.NeuralControl2D.opacityContourGraph2D, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
Referenced by IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts().
RemoveApproximationContureActors() [1/4]
void IG.Neural.Forms.NeuralControl2D.RemoveApproximationContureActors () inline
References IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
Referenced by IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), IG.Neural.Forms.NeuralControl2D.ResetAll2D(), and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
DefaultContourGraph() [1/5]
void IG.Neural.Forms.NeuralControl2D.DefaultContourGraph () inline
Generates conture plot from default points according to settings.
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Lib.ColorScaleBase.CreateRainbow(), IG.Neural.Forms.NeuralControl2D.iFunctionDefault2D, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Gr3d.VtkContourPlot.NumContours, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Neural.Forms.NeuralControl2D.opacityContourGraph2D, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotDefaultConture2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
Referenced by IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts(), and IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlotsWithoutShow().
RemoveDefaultContureActors() [1/5]
void IG.Neural.Forms.NeuralControl2D.RemoveDefaultContureActors () inline
References IG.Neural.Forms.NeuralControl2D.plotDefaultConture2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
SclarBar2D() [1/5]
void IG.Neural.Forms.NeuralControl2D.SclarBar2D (double minRange, double maxRange, ColorScale Color) inline
Scalar bar initialization.
References IG.Gr3d.VtkPlotter.DecorationHandler, IG.Gr3d.VtkDecorationHandler.LookUpTableColorScale, IG.Gr3d.VtkDecorationHandler.LookUpTableMaxRange, IG.Gr3d.VtkDecorationHandler.LookUpTableMinRange, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkDecorationHandler.ScalarBarNumberOfLabels, IG.Gr3d.VtkDecorationHandler.ScalarBarTitle, and IG.Gr3d.VtkDecorationHandler.ShowScalarBar.
Referenced by IG.Neural.Forms.NeuralControl2D.ApproximationGraph().
Bounds2D() [1/5]
void IG.Neural.Forms.NeuralControl2D.Bounds2D () inline
References IG.Neural.Forms.NeuralControl2D.highHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.highVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.lowHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.lowVerticalLimit2D, and IG.Neural.Forms.NeuralControl2D.paramBounds2D.
Referenced by IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D(), IG.Neural.Forms.NeuralControl2D.NeuralControl2D(), IG.Neural.Forms.NeuralControl2D.numHighXLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHighYLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numLowXLimit2D_ValueChanged(), and IG.Neural.Forms.NeuralControl2D.numLowYLimit2D_ValueChanged().
ResetAll2D() [1/5]
void IG.Neural.Forms.NeuralControl2D.ResetAll2D () inline
Invalidates training results AND training data, and makes corresponding changes in GUI (e.g. disables certain buttons, etc.).
References IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Neural.Forms.NeuralControl2D.InitializeDefaultData2D(), IG.Neural.Forms.NeuralControl2D.InitializeTrainingData2D(), IG.Neural.Forms.NeuralControl2D.InitializeVerificationData2D(), IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), IG.Neural.Forms.NeuralControl2D.progressBar1, IG.Neural.Forms.NeuralControl2D.RemoveApproximationActors(), IG.Neural.Forms.NeuralControl2D.RemoveApproximationContureActors(), IG.Neural.Forms.NeuralControl2D.RemoveDefaultActors(), and IG.Neural.Forms.NeuralControl2D.RemoveTrainingPointsActors().
Referenced by IG.Neural.Forms.NeuralControl2D.btReset2D_Click(), IG.Neural.Forms.NeuralControl2D.cbEquation2D_SelectedIndexChanged(), IG.Neural.Forms.NeuralControl2D.cbRandomData2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbScaleTo_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.numHighXLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHighYLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numLowXLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numLowYLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numSamplesX2D_ValueChanged(), and IG.Neural.Forms.NeuralControl2D.numSamplesY2D_ValueChanged().
ResetResults2D() [1/4]
void IG.Neural.Forms.NeuralControl2D.ResetResults2D () inline
Invalidates the training results and makes corresponding changes in GUI to reflect this.
References IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), IG.Neural.Forms.NeuralControl2D.progressBar1, IG.Neural.Forms.NeuralControl2D.RemoveApproximationActors(), IG.Neural.Forms.NeuralControl2D.RemoveApproximationContureActors(), and IG.Neural.Forms.NeuralControl2D.RemoveTrainingPointsActors().
Referenced by IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numInputSafety2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numLearningRate2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numMomentum2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numOutputSafety2D_ValueChanged(), and IG.Neural.Forms.NeuralControl2D.numRMS2D_ValueChanged().
btReset2D_Click() [1/5]
void IG.Neural.Forms.NeuralControl2D.btReset2D_Click (object sender, EventArgs e) inline private
Reset button.
References IG.Neural.Forms.NeuralControl2D.ResetAll2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
SetNetworkParameters() [1/4]
void IG.Neural.Forms.NeuralControl2D.SetNetworkParameters (INeuralApproximator neural) inline protected
Prepares network parameters.
Referenced by IG.Neural.Forms.NeuralControl2D.btStart2D_Click().
btStart2D_Click() [1/5]
void IG.Neural.Forms.NeuralControl2D.btStart2D_Click (object sender, EventArgs e) inline private
Start training button.
References IG.Num.SampledDataSet.AddElement(), IG.Neural.Forms.NeuralControl2D.btLoadANN2D, IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D, IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btReset2D, IG.Neural.Forms.NeuralControl2D.btSaveANN2D, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.btStop2D, IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Num.SampledDataSet.InputLength, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Num.SampledDataSet.OutputLength, IG.Neural.Forms.NeuralControl2D.plotApproximation2D, IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D, IG.Neural.Forms.NeuralControl2D.plotDefault2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), IG.Neural.Forms.NeuralControl2D.progressBar1, IG.Gr3d.VtkPlotter.RemovePlotObject(), IG.Neural.Forms.NeuralControl2D.SetNetworkParameters(), IG.Neural.Forms.NeuralControl2D.trainingData2D, IG.Neural.Forms.NeuralControl2D.TrainNetworkThread2D(), and IG.Neural.Forms.NeuralControl2D.verificationData2D.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
btnShowApprox_Click() [1/5]
void IG.Neural.Forms.NeuralControl2D.btnShowApprox_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts(), IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), and IG.Neural.Forms.NeuralControl2D.ShowPlot().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
PrepareApproximationPolts() [1/5]
void IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts () inline
Prepare approximation plots.
References IG.Neural.Forms.NeuralControl2D.ApproximationContourGraph(), IG.Neural.Forms.NeuralControl2D.ApproximationGraph(), IG.Neural.Forms.NeuralControl2D.contureApproximationonGraph, IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph, IG.Neural.Forms.NeuralControl2D.DefaultContourGraph(), IG.Neural.Forms.NeuralControl2D.DefaultGraph2D(), and IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph().
Referenced by IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted(), and IG.Neural.Forms.NeuralControl2D.btnShowApprox_Click().
btStop2D_Click() [1/5]
void IG.Neural.Forms.NeuralControl2D.btStop2D_Click (object sender, EventArgs e) inline private
Stop training button.
References IG.Num.INeuralApproximator.BreakTraining, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, and IG.Neural.Forms.NeuralControl2D.stopTraining2D.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
TrainNetworkThread2D() [1/5]
void IG.Neural.Forms.NeuralControl2D.TrainNetworkThread2D () inline private
References IG.Neural.Forms.NeuralControl2D.backgroundWorker2D.
Referenced by IG.Neural.Forms.NeuralControl2D.btStart2D_Click().
btnGenerateOptData2D_Click() [1/5]
void IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click (object sender, EventArgs e) inline private
Generate training data button.
References IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.GenerateDefaultPoints2D(), IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D(), IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Neural.Forms.NeuralControl2D.InitializeDefaultData2D(), IG.Neural.Forms.NeuralControl2D.InitializeTrainingData2D(), IG.Neural.Forms.NeuralControl2D.InitializeVerificationData2D(), IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlotsWithoutShow(), IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), IG.Neural.Forms.NeuralControl2D.progressBar1, IG.Neural.Forms.NeuralControl2D.RemoveApproximationActors(), IG.Neural.Forms.NeuralControl2D.RemoveApproximationContureActors(), IG.Neural.Forms.NeuralControl2D.RemoveDefaultActors(), and IG.Neural.Forms.NeuralControl2D.RemoveTrainingPointsActors().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
btnShowDefault_Click() [1/5]
void IG.Neural.Forms.NeuralControl2D.btnShowDefault_Click (object sender, EventArgs e) inline private
Show default graph button.
References IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlots(), and IG.Neural.Forms.NeuralControl2D.PreparePlotter2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
PrepareDefaultPlotsWithoutShow() [1/5]
void IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlotsWithoutShow () inline
References IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph, IG.Neural.Forms.NeuralControl2D.DefaultContourGraph(), IG.Neural.Forms.NeuralControl2D.DefaultGraph2D(), and IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph().
Referenced by IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), and IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlots().
PrepareDefaultPlots() [1/5]
void IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlots () inline
Prepare default plots of.
References IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlotsWithoutShow(), and IG.Neural.Forms.NeuralControl2D.ShowPlot().
Referenced by IG.Neural.Forms.NeuralControl2D.btnShowDefault_Click().
rbMaxTrainError2D_CheckedChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.rbMaxTrainError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum training error convergence to be written on graph.
References IG.Neural.Forms.NeuralControl2D.maxTrainErrorEnabled2D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
rbRmsTrainError2D_CheckedChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.rbRmsTrainError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms training error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.rmsTrainErrorEnabled2D, and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
rbMaxVerError2D_CheckedChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.rbMaxVerError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum verification error convergence to be written on graph.
References IG.Neural.Forms.NeuralControl2D.maxVerErrorEnabled2D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
rbRmsVerError2D_CheckedChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.rbRmsVerError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms verification error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.rmsVerErrorEnabled2D, and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
cbSelfMade2D_CheckedChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.cbSelfMade2D_CheckedChanged (object sender, EventArgs e) inline private
Enable posibility to self made the equation.
References IG.Neural.Forms.NeuralControl2D.cbEquation2D, IG.Neural.Forms.NeuralControl2D.cbSelfMade2D, and IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
cbTrainingPoints2D_CheckedChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D_CheckedChanged (object sender, EventArgs e) inline private
Enable training points on graph.
References IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D, and IG.Neural.Forms.NeuralControl2D.trainingPointsonGraph.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
cbDefaultSurface2D_CheckedChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D_CheckedChanged (object sender, EventArgs e) inline private
Enable surface for default function on graph.
References IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D, and IG.Neural.Forms.NeuralControl2D.defaultSurfaceonGraph.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
cbDefaultGreed2D_CheckedChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D_CheckedChanged (object sender, EventArgs e) inline private
Enable greed for default function on graph.
References IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D, and IG.Neural.Forms.NeuralControl2D.defaultGreedonGraph.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
cbApproximationSurface2D_CheckedChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D_CheckedChanged (object sender, EventArgs e) inline private
Enable surface for approximation function on graph.
References IG.Neural.Forms.NeuralControl2D.approximationSurfaceonGraph, and IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
cbApproximationGreed2D_CheckedChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D_CheckedChanged (object sender, EventArgs e) inline private
Enable greed for approximation function on graph.
References IG.Neural.Forms.NeuralControl2D.approximationGreedonGraph, and IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
cbContourDefault2D_CheckedChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.cbContourDefault2D_CheckedChanged (object sender, EventArgs e) inline private
Enable conture for default function on graph.
References IG.Neural.Forms.NeuralControl2D.cbContourDefault2D, and IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
cbContourApproximation2D_CheckedChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D_CheckedChanged (object sender, EventArgs e) inline private
Enable conture for approximation function on graph.
References IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D, and IG.Neural.Forms.NeuralControl2D.contureApproximationonGraph.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
cbRandomData2D_CheckedChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.cbRandomData2D_CheckedChanged (object sender, EventArgs e) inline private
Enable random training points.
References IG.Neural.Forms.NeuralControl2D.ResetAll2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
cbScaleTo_CheckedChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.cbScaleTo_CheckedChanged (object sender, EventArgs e) inline private
Enable scaling to range 1.
References IG.Neural.Forms.NeuralControl2D.ResetAll2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
trackbDefaultGraph2D_Scroll() [1/5]
void IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D_Scroll (object sender, EventArgs e) inline private
Opacity for visualization of default function.
References IG.Neural.Forms.NeuralControl2D.opacityDefaultGraph2D, and IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
trackbApproxGraph2D_Scroll() [1/5]
void IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D_Scroll (object sender, EventArgs e) inline private
Opacity for visualization of approximation function.
References IG.Neural.Forms.NeuralControl2D.opacityApproxGraph2D, and IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
trackbContourGraph2D_Scroll() [1/5]
void IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D_Scroll (object sender, EventArgs e) inline private
Opacity for visualization of contures.
References IG.Neural.Forms.NeuralControl2D.opacityContourGraph2D, and IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
cbEquation2D_SelectedIndexChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.cbEquation2D_SelectedIndexChanged (object sender, EventArgs e) inline private
Select equation from the list.
References IG.Neural.Forms.NeuralControl2D.cbEquation2D, IG.Neural.Forms.NeuralControl2D.equation2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
tbSelfMadeEquation2D_TextChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D_TextChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.equation2D, and IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numSamplesX2D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.numSamplesX2D_ValueChanged (object sender, EventArgs e) inline private
Number of training samples on X axe.
References IG.Neural.Forms.NeuralControl2D.numSamplesX2D, IG.Neural.Forms.NeuralControl2D.ResetAll2D(), and IG.Neural.Forms.NeuralControl2D.samplesX2D.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numSamplesY2D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.numSamplesY2D_ValueChanged (object sender, EventArgs e) inline private
Number of training samples on Y axe.
References IG.Neural.Forms.NeuralControl2D.numSamplesY2D, IG.Neural.Forms.NeuralControl2D.ResetAll2D(), and IG.Neural.Forms.NeuralControl2D.samplesY2D.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numLowXLimit2D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.numLowXLimit2D_ValueChanged (object sender, EventArgs e) inline private
Lower limit for x-axes on the graph.
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.lowHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.numLowXLimit2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numHighXLimit2D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.numHighXLimit2D_ValueChanged (object sender, EventArgs e) inline private
Higher limit for x-axes on the graph.
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.highHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.numHighXLimit2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numHighYLimit2D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.numHighYLimit2D_ValueChanged (object sender, EventArgs e) inline private
Higher limit for y-axes on the graph.
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.highVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.numHighYLimit2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numLowYLimit2D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.numLowYLimit2D_ValueChanged (object sender, EventArgs e) inline private
Lower limit for y-axes on the graph.
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.lowVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.numLowYLimit2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numMaxEpoch2D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D_ValueChanged (object sender, EventArgs e) inline private
Maximum number of epochs.
References IG.Neural.Forms.NeuralControl2D.maxEpoch2D, IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numEpochBundle2D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.numEpochBundle2D_ValueChanged (object sender, EventArgs e) inline private
Number of epochs in bundle.
References IG.Neural.Forms.NeuralControl2D.epochInBundle2D, and IG.Neural.Forms.NeuralControl2D.numEpochBundle2D.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numRMS2D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.numRMS2D_ValueChanged (object sender, EventArgs e) inline private
Rms error limit.
References IG.Neural.Forms.NeuralControl2D.numRMS2D, IG.Neural.Forms.NeuralControl2D.ResetResults2D(), and IG.Neural.Forms.NeuralControl2D.rmsError2D.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numLearningRate2D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.numLearningRate2D_ValueChanged (object sender, EventArgs e) inline private
Learning rate.
References IG.Neural.Forms.NeuralControl2D.learningRate2D, IG.Neural.Forms.NeuralControl2D.numLearningRate2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numMomentum2D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.numMomentum2D_ValueChanged (object sender, EventArgs e) inline private
Momentum.
References IG.Neural.Forms.NeuralControl2D.momentum2D, IG.Neural.Forms.NeuralControl2D.numMomentum2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numHiddenNeuron2D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in first hidden layer.
References IG.Neural.Forms.NeuralControl2D.hiddenNeuronL12D, IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numHiddenNeuronL22D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in second hidden layer.
References IG.Neural.Forms.NeuralControl2D.hiddenNeuronL22D, IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numInputSafety2D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.numInputSafety2D_ValueChanged (object sender, EventArgs e) inline private
Input safety factor.
References IG.Neural.Forms.NeuralControl2D.inputSafetyFactor2D, IG.Neural.Forms.NeuralControl2D.numInputSafety2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numOutputSafety2D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralControl2D.numOutputSafety2D_ValueChanged (object sender, EventArgs e) inline private
Output safety factor.
References IG.Neural.Forms.NeuralControl2D.numOutputSafety2D, IG.Neural.Forms.NeuralControl2D.outputSafetyFactor2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
Approximator_BundleCompleted() [1/4]
void IG.Neural.Forms.NeuralControl2D.Approximator_BundleCompleted (object obj, EventArgs args) inline protected
Event handler that is executed when a new bundle of training epochs completes.
Updates progress bar.
References IG.Num.INeuralApproximator.EpochCount, IG.Num.INeuralApproximator.MaxEpochs, IG.Num.INeuralApproximator.OutputLevel, and IG.Neural.Forms.NeuralControl2D.progressBar1.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D().
Aproximator_TrainingCompleted() [1/4]
void IG.Neural.Forms.NeuralControl2D.Aproximator_TrainingCompleted (object obj, EventArgs args) inline protected
Event handler that is executed when a new bundle of training epochs completes.
References IG.Num.INeuralApproximator.EpochCount, IG.Num.INeuralApproximator.MaxEpochs, IG.Num.INeuralApproximator.OutputLevel, and IG.Neural.Forms.NeuralControl2D.progressBar1.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D().
TrainNetwork() [1/4]
INeuralApproximator IG.Neural.Forms.NeuralControl2D.TrainNetwork (SampledDataSet trainingData, SampledDataSet verificationData) inline protected
Performs training of neural network.
Parameters
trainingData Training data.
verificationData Verification data.
Returns
References IG.Neural.Forms.NeuralControl2D.epochInBundle2D, IG.Num.NeuralApproximatorBase.EpochsInBundle, IG.Neural.Forms.NeuralControl2D.hiddenNeuronL12D, IG.Neural.Forms.NeuralControl2D.hiddenNeuronL22D, IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Num.NeuralApproximatorBase.InputBoundsSafetyFactor, IG.Num.SampledDataSet.InputLength, IG.Num.NeuralApproximatorBase.InputLength, IG.Num.NeuralApproximatorBase.InputNeuronsRange, IG.Neural.Forms.NeuralControl2D.inputSafetyFactor2D, IG.Num.NeuralApproximatorBase.LearningRate, IG.Neural.Forms.NeuralControl2D.learningRate2D, IG.Num.SampledDataSet.Length, IG.Num.VectorApproximatorBase.Lock, IG.Neural.Forms.NeuralControl2D.maxEpoch2D, IG.Num.NeuralApproximatorBase.MaxEpochs, IG.Num.NeuralApproximatorBase.Momentum, IG.Neural.Forms.NeuralControl2D.momentum2D, IG.Num.NeuralApproximatorBase.MultipleNetworks, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Num.NeuralApproximatorBase.OutputBoundsSafetyFactor, IG.Num.SampledDataSet.OutputLength, IG.Num.NeuralApproximatorBase.OutputLength, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Num.NeuralApproximatorBase.OutputLevel, IG.Num.NeuralApproximatorBase.OutputNeuronsRange, IG.Neural.Forms.NeuralControl2D.outputSafetyFactor2D, IG.Num.IBoundingBox.Reset(), IG.Neural.Forms.NeuralControl2D.rmsError2D, IG.Num.NeuralApproximatorBase.SaveConvergenceRms, IG.Num.NeuralApproximatorBase.SetHiddenLayers(), IG.Num.NeuralApproximatorBase.SetTrainingAndVerificationData(), IG.Num.NeuralApproximatorBase.SigmoidAlphaValue, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.StopWatch1.Time, IG.Num.NeuralApproximatorBase.ToleranceRms, IG.Num.NeuralApproximatorBase.ToString(), IG.Num.NeuralApproximatorBase.TrainingData, IG.Num.NeuralApproximatorBase.TrainNetwork(), and IG.Num.IBoundingBox.UpdateAll().
Referenced by IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_DoWork().
backgroundWorker2D_DoWork() [1/5]
void IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_DoWork (object sender, DoWorkEventArgs e) inline private
References IG.Num.INeuralApproximator.BreakTraining, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Neural.Forms.NeuralControl2D.stopTraining2D, IG.Neural.Forms.NeuralControl2D.trainingData2D, IG.Neural.Forms.NeuralControl2D.TrainNetwork(), and IG.Neural.Forms.NeuralControl2D.verificationData2D.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
backgroundWorker2D_RunWorkerCompleted() [1/5]
void IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.btLoadANN2D, IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D, IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btReset2D, IG.Neural.Forms.NeuralControl2D.btSaveANN2D, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.btStop2D, IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts(), IG.Neural.Forms.NeuralControl2D.ShowPlot(), and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
ShowPlot() [1/5]
void IG.Neural.Forms.NeuralControl2D.ShowPlot () inline protected
Shows the plot.
References IG.Gr3d.VtkPlotter.BoundsScaled, IG.Neural.Forms.NeuralControl2D.cbScaleTo, IG.Neural.Forms.NeuralControl2D.DecorHandler(), IG.Gr3d.VtkPlotter.IsScaled, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Num.BoundingBoxBase.Reset(), IG.Gr3d.VtkPlotter.ResetCamera(), IG.Neural.Forms.NeuralControl2D.ScaledBounds, IG.Gr3d.VtkPlotter.ShowPlot(), and IG.Num.BoundingBox3d.Update().
Referenced by IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralControl2D.btnShowApprox_Click(), and IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlots().
ResetTooltipProperties() [1/2]
void IG.Neural.Forms.NeuralControl2D.ResetTooltipProperties () inline
References IG.Neural.Forms.NeuralControl2D.toolTip1, and IG.Neural.Forms.NeuralControl2D.toolTip2.
Referenced by IG.Neural.Forms.NeuralControl2D.resetToolStripMenuItem_Click().
menuTooltipEnabled_CheckedChanged() [1/2]
void IG.Neural.Forms.NeuralControl2D.menuTooltipEnabled_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.IsToolTipActive, and IG.Neural.Forms.NeuralControl2D.menuTooltipEnabled.
resetToolStripMenuItem_Click() [1/2]
void IG.Neural.Forms.NeuralControl2D.resetToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.ResetTooltipProperties().
menuTooltipBackground_Click() [1/2]
void IG.Neural.Forms.NeuralControl2D.menuTooltipBackground_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.colorDialog1, and IG.Neural.Forms.NeuralControl2D.ToolTipBackground.
menuTooltipForeground_Click() [1/2]
void IG.Neural.Forms.NeuralControl2D.menuTooltipForeground_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.colorDialog1, and IG.Neural.Forms.NeuralControl2D.ToolTipForeground.
menuTooltipDisplayTimeValue_Validated() [1/2]
void IG.Neural.Forms.NeuralControl2D.menuTooltipDisplayTimeValue_Validated (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.menuTooltipDisplayTimeValue.
menuTooltipDelayValue_Validated() [1/2]
void IG.Neural.Forms.NeuralControl2D.menuTooltipDelayValue_Validated (object sender, EventArgs e) inline private
Dispose() [1/5]
override void IG.Neural.Forms.NeuralControl2D.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralControl2D.components.
InitializeComponent() [1/5]
void IG.Neural.Forms.NeuralControl2D.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralControl2D.backgroundWorker2D, IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_DoWork(), IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralControl2D.btLoad2D, IG.Neural.Forms.NeuralControl2D.btLoadANN2D, IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D, IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowApprox_Click(), IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btnShowDefault_Click(), IG.Neural.Forms.NeuralControl2D.btReset2D, IG.Neural.Forms.NeuralControl2D.btReset2D_Click(), IG.Neural.Forms.NeuralControl2D.btSaveANN2D, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.btStop2D, IG.Neural.Forms.NeuralControl2D.btStop2D_Click(), IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D, IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D, IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D, IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbContourDefault2D, IG.Neural.Forms.NeuralControl2D.cbContourDefault2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D, IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D, IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbEquation2D, IG.Neural.Forms.NeuralControl2D.cbEquation2D_SelectedIndexChanged(), IG.Neural.Forms.NeuralControl2D.cbRandomData2D, IG.Neural.Forms.NeuralControl2D.cbRandomData2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbScaleTo, IG.Neural.Forms.NeuralControl2D.cbScaleTo_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbSelfMade2D, IG.Neural.Forms.NeuralControl2D.cbSelfMade2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D, IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.colorDialog1, IG.Neural.Forms.NeuralControl2D.components, IG.Neural.Forms.NeuralControl2D.contextMenuStrip1, IG.Neural.Forms.NeuralControl2D.errorConvergence2D, IG.Neural.Forms.NeuralControl2D.groupBox1, IG.Neural.Forms.NeuralControl2D.groupBox2, IG.Neural.Forms.NeuralControl2D.groupBox3, IG.Neural.Forms.NeuralControl2D.groupBox4, IG.Neural.Forms.NeuralControl2D.groupBox8, IG.Neural.Forms.NeuralControl2D.label10, IG.Neural.Forms.NeuralControl2D.label14, IG.Neural.Forms.NeuralControl2D.label17, IG.Neural.Forms.NeuralControl2D.label18, IG.Neural.Forms.NeuralControl2D.label20, IG.Neural.Forms.NeuralControl2D.label21, IG.Neural.Forms.NeuralControl2D.label22, IG.Neural.Forms.NeuralControl2D.label23, IG.Neural.Forms.NeuralControl2D.label24, IG.Neural.Forms.NeuralControl2D.label25, IG.Neural.Forms.NeuralControl2D.label26, IG.Neural.Forms.NeuralControl2D.label27, IG.Neural.Forms.NeuralControl2D.label28, IG.Neural.Forms.NeuralControl2D.label29, IG.Neural.Forms.NeuralControl2D.label3, IG.Neural.Forms.NeuralControl2D.label30, IG.Neural.Forms.NeuralControl2D.label31, IG.Neural.Forms.NeuralControl2D.label32, IG.Neural.Forms.NeuralControl2D.label33, IG.Neural.Forms.NeuralControl2D.label34, IG.Neural.Forms.NeuralControl2D.label35, IG.Neural.Forms.NeuralControl2D.label36, IG.Neural.Forms.NeuralControl2D.label37, IG.Neural.Forms.NeuralControl2D.menuDelayTime, IG.Neural.Forms.NeuralControl2D.menuDisplayTime, IG.Neural.Forms.NeuralControl2D.menuTooltipBackground, IG.Neural.Forms.NeuralControl2D.menuTooltipColor, IG.Neural.Forms.NeuralControl2D.menuTooltipDelayValue, IG.Neural.Forms.NeuralControl2D.menuTooltipDisplayTimeValue, IG.Neural.Forms.NeuralControl2D.menuTooltipEnabled, IG.Neural.Forms.NeuralControl2D.menuTooltipForeground, IG.Neural.Forms.NeuralControl2D.menuTooltips, IG.Neural.Forms.NeuralControl2D.numEpochBundle2D, IG.Neural.Forms.NeuralControl2D.numEpochBundle2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D, IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D, IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHighXLimit2D, IG.Neural.Forms.NeuralControl2D.numHighXLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHighYLimit2D, IG.Neural.Forms.NeuralControl2D.numHighYLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numInputSafety2D, IG.Neural.Forms.NeuralControl2D.numInputSafety2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numLearningRate2D, IG.Neural.Forms.NeuralControl2D.numLearningRate2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numLowXLimit2D, IG.Neural.Forms.NeuralControl2D.numLowXLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numLowYLimit2D, IG.Neural.Forms.NeuralControl2D.numLowYLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D, IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numMomentum2D, IG.Neural.Forms.NeuralControl2D.numMomentum2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numOutputSafety2D, IG.Neural.Forms.NeuralControl2D.numOutputSafety2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numRMS2D, IG.Neural.Forms.NeuralControl2D.numRMS2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numSamplesX2D, IG.Neural.Forms.NeuralControl2D.numSamplesX2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numSamplesY2D, IG.Neural.Forms.NeuralControl2D.numSamplesY2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.progressBar1, IG.Neural.Forms.NeuralControl2D.rbMaxTrainError2D, IG.Neural.Forms.NeuralControl2D.rbMaxTrainError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.rbMaxVerError2D, IG.Neural.Forms.NeuralControl2D.rbMaxVerError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.rbRmsTrainError2D, IG.Neural.Forms.NeuralControl2D.rbRmsTrainError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.rbRmsVerError2D, IG.Neural.Forms.NeuralControl2D.rbRmsVerError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.resetToolStripMenuItem, IG.Neural.Forms.NeuralControl2D.tbEquationError2D, IG.Neural.Forms.NeuralControl2D.tbMaxTrainError2D, IG.Neural.Forms.NeuralControl2D.tbMaxVerError2D, IG.Neural.Forms.NeuralControl2D.tbRmsTrainError2D, IG.Neural.Forms.NeuralControl2D.tbRmsVerError2D, IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D, IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D_TextChanged(), IG.Neural.Forms.NeuralControl2D.toolTip1, IG.Neural.Forms.NeuralControl2D.toolTip2, IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D, IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D_Scroll(), IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D, IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D_Scroll(), IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D, and IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D_Scroll().
Referenced by IG.Neural.Forms.NeuralControl2D.NeuralControl2D().
LoadForm() [2/5]
void IG.Neural.Forms.NeuralControl2D.LoadForm (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.errorConvergence2D, and IG.Neural.Forms.NeuralControl2D.pane2DError.
CreateGreenRedYellow() [2/5]
static ColorScale IG.Neural.Forms.NeuralControl2D.CreateGreenRedYellow (double minValue, double maxValue) inline static
InitializeApproximator2D() [2/5]
void IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D () inline private
Clean and initialize the approximator.
References IG.Neural.Forms.NeuralControl2D.NeuralApproximator.
InitializeTrainingData2D() [2/5]
void IG.Neural.Forms.NeuralControl2D.InitializeTrainingData2D () inline private
Clean and initialize the training data set.
References IG.Neural.Forms.NeuralControl2D.trainingData2D.
InitializeVerificationData2D() [2/5]
void IG.Neural.Forms.NeuralControl2D.InitializeVerificationData2D () inline private
Clean and initialize the verification data set.
References IG.Neural.Forms.NeuralControl2D.verificationData2D.
InitializeDefaultData2D() [2/5]
void IG.Neural.Forms.NeuralControl2D.InitializeDefaultData2D () inline private
Clean and initialize the default data set.
References IG.Neural.Forms.NeuralControl2D.defaultFunctionData2D.
WriteErrors2D() [2/5]
void IG.Neural.Forms.NeuralControl2D.WriteErrors2D () inline private
Write training and verification errors in text box.
References IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Num.INeuralApproximator.ConvergenceErrorsTrainingMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsTrainingRmsList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationRmsList, IG.Neural.Forms.NeuralControl2D.epochInBundle2D, IG.Neural.Forms.NeuralControl2D.errorConvergence2D, IG.Neural.Forms.NeuralControl2D.errorConvergenceFunction2D, IG.Num.INeuralApproximator.GetErrorsTrainingMax(), IG.Num.INeuralApproximator.GetErrorsTrainingRms(), IG.Num.INeuralApproximator.GetErrorsVerificationMax(), IG.Num.INeuralApproximator.GetErrorsVerificationRms(), IG.Neural.Forms.NeuralControl2D.maxTrainErrorEnabled2D, IG.Neural.Forms.NeuralControl2D.maxVerErrorEnabled2D, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.pane2DError, IG.Neural.Forms.NeuralControl2D.rmsTrainErrorEnabled2D, IG.Neural.Forms.NeuralControl2D.rmsVerErrorEnabled2D, IG.Neural.Forms.NeuralControl2D.tbMaxTrainError2D, IG.Neural.Forms.NeuralControl2D.tbMaxVerError2D, IG.Neural.Forms.NeuralControl2D.tbRmsTrainError2D, and IG.Neural.Forms.NeuralControl2D.tbRmsVerError2D.
ClearErrorGraph2D() [2/5]
void IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D () inline private
Clear Graph with error convergence for 2 dimension.
References IG.Neural.Forms.NeuralControl2D.errorConvergence2D, IG.Neural.Forms.NeuralControl2D.errorConvergenceFunction2D, IG.Neural.Forms.NeuralControl2D.tbMaxTrainError2D, IG.Neural.Forms.NeuralControl2D.tbMaxVerError2D, IG.Neural.Forms.NeuralControl2D.tbRmsTrainError2D, and IG.Neural.Forms.NeuralControl2D.tbRmsVerError2D.
PreparePlotter2D() [2/5]
void IG.Neural.Forms.NeuralControl2D.PreparePlotter2D () inline
References IG.Neural.Forms.NeuralControl2D.plotter2D.
DecorHandler() [2/5]
void IG.Neural.Forms.NeuralControl2D.DecorHandler () inline
Initialize decoration handler.
References IG.Gr3d.VtkPlotter.BackGround, IG.Gr3d.VtkDecorationHandler.CubeAxesFlyMode, IG.Gr3d.VtkDecorationHandler.CubeAxesXLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesYLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesZLabel, IG.Gr3d.VtkPlotter.DecorationHandler, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkPlotter.WindowSizeX, and IG.Gr3d.VtkPlotter.WindowSizeY.
GenerateDefaultPoints2D() [2/5]
void IG.Neural.Forms.NeuralControl2D.GenerateDefaultPoints2D () inline
Generates the set of default points according to settings.
References IG.Num.Func2dFromScalarScript.CreateScalarFunction(), IG.Neural.Forms.NeuralControl2D.Default2DMesh, IG.Neural.Forms.NeuralControl2D.equation2D, IG.Num.StructuredMesh2d3d.GenerateCoordinates(), IG.Neural.Forms.NeuralControl2D.iFunctionDefault2D, IG.Num.BoundingBox2d.MaxX, IG.Num.BoundingBox2d.MaxY, IG.Num.BoundingBox2d.MinX, IG.Num.BoundingBox2d.MinY, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.scalarFunctionDefault2D, IG.Neural.Forms.NeuralControl2D.tbEquationError2D, IG.Num.IScalarFunctionUntransformed.Value(), and IG.Neural.Forms.NeuralControl2D.variableNames2D.
DefaultGraph2D() [2/5]
void IG.Neural.Forms.NeuralControl2D.DefaultGraph2D () inline
Generates plot from default points according to settings.
References IG.Neural.Forms.NeuralControl2D.contureApproximationonGraph, IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph, IG.Gr3d.VtkSurfacePlot.Create(), IG.Neural.Forms.NeuralControl2D.Default2DMesh, IG.Neural.Forms.NeuralControl2D.defaultGreedonGraph, IG.Neural.Forms.NeuralControl2D.defaultSurfaceonGraph, IG.Gr3d.VtkSurfacePlotBase.LineColor, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Neural.Forms.NeuralControl2D.opacityDefaultGraph2D, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D, IG.Neural.Forms.NeuralControl2D.plotDefault2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
RemoveDefaultActors() [2/5]
void IG.Neural.Forms.NeuralControl2D.RemoveDefaultActors () inline
References IG.Neural.Forms.NeuralControl2D.plotDefault2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
GenerateTrainingPoints2D() [2/5]
void IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D () inline
Generates the set of training points according to settings.
References IG.Num.SampledDataSet.AddElement(), IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.cbRandomData2D, IG.Num.Func2dFromScalarScript.CreateScalarFunction(), IG.Neural.Forms.NeuralControl2D.equation2D, IG.Num.StructuredMesh2d3d.GenerateCoordinates(), IG.Num.BoundingBoxBase.GetRandomPoint(), IG.Num.BoundingBox2d.MaxX, IG.Num.BoundingBox2d.MaxY, IG.Num.BoundingBox2d.MinX, IG.Num.BoundingBox2d.MinY, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.samplesX2D, IG.Neural.Forms.NeuralControl2D.samplesY2D, IG.Neural.Forms.NeuralControl2D.scalarFunctionTraining2D, IG.Neural.Forms.NeuralControl2D.trainingData2D, IG.Neural.Forms.NeuralControl2D.TrainingPointsMesh2D, IG.Num.IScalarFunctionUntransformed.Value(), and IG.Neural.Forms.NeuralControl2D.variableNames2D.
TrainingPointsGraph() [2/5]
void IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph () inline
Generates plot from training points according to settings.
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Neural.Forms.NeuralControl2D.plotTrainingPoints2D, IG.Gr3d.VtkSurfacePlotBase.PointColor, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible, IG.Neural.Forms.NeuralControl2D.TrainingPointsMesh2D, and IG.Neural.Forms.NeuralControl2D.trainingPointsonGraph.
RemoveTrainingPointsActors() [2/5]
void IG.Neural.Forms.NeuralControl2D.RemoveTrainingPointsActors () inline
References IG.Neural.Forms.NeuralControl2D.plotTrainingPoints2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
ApproximationGraph() [2/5]
void IG.Neural.Forms.NeuralControl2D.ApproximationGraph () inline
Generates plot from approximated points according to settings.
References IG.Neural.Forms.NeuralControl2D.approximationGreedonGraph, IG.Neural.Forms.NeuralControl2D.approximationSurfaceonGraph, IG.Gr3d.VtkSurfacePlot.Create(), IG.Neural.Forms.NeuralControl2D.CreateGreenRedYellow(), IG.Neural.Forms.NeuralControl2D.iFunctionApproximator2D, IG.Neural.Forms.NeuralControl2D.iFunctionDefault2D, IG.Neural.Forms.NeuralControl2D.iFunctionDifference2D, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LineColorScale, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Neural.Forms.NeuralControl2D.opacityApproxGraph2D, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotApproximation2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Neural.Forms.NeuralControl2D.SclarBar2D(), IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible, and IG.Gr3d.VtkSurfacePlot.ValueFunctionOfCoordinates.
RemoveApprovimationActors()
void IG.Neural.Forms.NeuralControl2D.RemoveApprovimationActors () inline
References IG.Neural.Forms.NeuralControl2D.plotApproximation2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
Referenced by IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
ApproximationContourGraph() [2/5]
void IG.Neural.Forms.NeuralControl2D.ApproximationContourGraph () inline
Generates conture plot from approximated points according to settings.
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Lib.ColorScaleBase.CreateRainbow(), IG.Neural.Forms.NeuralControl2D.iFunctionApproximator2D, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Gr3d.VtkContourPlot.NumContours, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Neural.Forms.NeuralControl2D.opacityContourGraph2D, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
RemoveApprovimationContureActors()
void IG.Neural.Forms.NeuralControl2D.RemoveApprovimationContureActors () inline
References IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
Referenced by IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
DefaultContourGraph() [2/5]
void IG.Neural.Forms.NeuralControl2D.DefaultContourGraph () inline
Generates conture plot from default points according to settings.
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Lib.ColorScaleBase.CreateRainbow(), IG.Neural.Forms.NeuralControl2D.iFunctionDefault2D, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Gr3d.VtkContourPlot.NumContours, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Neural.Forms.NeuralControl2D.opacityContourGraph2D, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotDefaultConture2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
RemoveDefaultContureActors() [2/5]
void IG.Neural.Forms.NeuralControl2D.RemoveDefaultContureActors () inline
References IG.Neural.Forms.NeuralControl2D.plotDefaultConture2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
SclarBar2D() [2/5]
void IG.Neural.Forms.NeuralControl2D.SclarBar2D (double minRange, double maxRange, ColorScale Color) inline
Scalar bar initialization.
References IG.Gr3d.VtkPlotter.DecorationHandler, IG.Gr3d.VtkDecorationHandler.LookUpTableColorScale, IG.Gr3d.VtkDecorationHandler.LookUpTableMaxRange, IG.Gr3d.VtkDecorationHandler.LookUpTableMinRange, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkDecorationHandler.ScalarBarNumberOfLabels, IG.Gr3d.VtkDecorationHandler.ScalarBarTitle, and IG.Gr3d.VtkDecorationHandler.ShowScalarBar.
Bounds2D() [2/5]
void IG.Neural.Forms.NeuralControl2D.Bounds2D () inline
References IG.Neural.Forms.NeuralControl2D.highHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.highVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.lowHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.lowVerticalLimit2D, and IG.Neural.Forms.NeuralControl2D.paramBounds2D.
ResetAll2D() [2/5]
void IG.Neural.Forms.NeuralControl2D.ResetAll2D () inline
Reset all to default.
References IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Neural.Forms.NeuralControl2D.InitializeDefaultData2D(), IG.Neural.Forms.NeuralControl2D.InitializeTrainingData2D(), IG.Neural.Forms.NeuralControl2D.InitializeVerificationData2D(), IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), IG.Neural.Forms.NeuralControl2D.RemoveApprovimationActors(), IG.Neural.Forms.NeuralControl2D.RemoveApprovimationContureActors(), IG.Neural.Forms.NeuralControl2D.RemoveDefaultActors(), and IG.Neural.Forms.NeuralControl2D.RemoveTrainingPointsActors().
btReset2D_Click() [2/5]
void IG.Neural.Forms.NeuralControl2D.btReset2D_Click (object sender, EventArgs e) inline private
Reset button.
References IG.Neural.Forms.NeuralControl2D.ResetAll2D().
btStart2D_Click() [2/5]
void IG.Neural.Forms.NeuralControl2D.btStart2D_Click (object sender, EventArgs e) inline private
Start training button.
References IG.Num.SampledDataSet.AddElement(), IG.Neural.Forms.NeuralControl2D.btLoadANN2D, IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D, IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btReset2D, IG.Neural.Forms.NeuralControl2D.btSaveANN2D, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.btStop2D, IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.NeuralNetworks.EpochBundle, IG.Neural.Forms.NeuralControl2D.epochInBundle2D, IG.Neural.NeuralNetworks.HiddenNeuron1L, IG.Neural.NeuralNetworks.HiddenNeuron2L, IG.Neural.Forms.NeuralControl2D.hiddenNeuronL12D, IG.Neural.Forms.NeuralControl2D.hiddenNeuronL22D, IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Num.SampledDataSet.InputLength, IG.Neural.NeuralNetworks.InputSafetyFactor, IG.Neural.Forms.NeuralControl2D.inputSafetyFactor2D, IG.Neural.NeuralNetworks.LearningRate, IG.Neural.Forms.NeuralControl2D.learningRate2D, IG.Neural.NeuralNetworks.MaxEpoch, IG.Neural.Forms.NeuralControl2D.maxEpoch2D, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Neural.NeuralNetworks.Momentum, IG.Neural.Forms.NeuralControl2D.momentum2D, IG.Neural.Forms.NeuralControl2D.network2D, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Num.SampledDataSet.OutputLength, IG.Neural.NeuralNetworks.OutputSafetyFactor, IG.Neural.Forms.NeuralControl2D.outputSafetyFactor2D, IG.Neural.Forms.NeuralControl2D.plotApproximation2D, IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D, IG.Neural.Forms.NeuralControl2D.plotDefault2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), IG.Gr3d.VtkPlotter.RemovePlotObject(), IG.Neural.NeuralNetworks.RMS, IG.Neural.Forms.NeuralControl2D.rmsError2D, IG.Neural.Forms.NeuralControl2D.trainingData2D, IG.Neural.Forms.NeuralControl2D.TrainNetworkThread2D(), and IG.Neural.Forms.NeuralControl2D.verificationData2D.
btnShowApprox_Click() [2/5]
void IG.Neural.Forms.NeuralControl2D.btnShowApprox_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts(), IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), and IG.Neural.Forms.NeuralControl2D.ShowPlot().
PrepareApproximationPolts() [2/5]
void IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts () inline
Prepare approximation plots.
References IG.Neural.Forms.NeuralControl2D.ApproximationContourGraph(), IG.Neural.Forms.NeuralControl2D.ApproximationGraph(), IG.Neural.Forms.NeuralControl2D.contureApproximationonGraph, IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph, IG.Neural.Forms.NeuralControl2D.DefaultContourGraph(), IG.Neural.Forms.NeuralControl2D.DefaultGraph2D(), and IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph().
btStop2D_Click() [2/5]
void IG.Neural.Forms.NeuralControl2D.btStop2D_Click (object sender, EventArgs e) inline private
Stop training button.
References IG.Neural.NeuralNetworks.BreakTraining, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.network2D, and IG.Neural.Forms.NeuralControl2D.stopTraining2D.
TrainNetworkThread2D() [2/5]
void IG.Neural.Forms.NeuralControl2D.TrainNetworkThread2D () inline private
References IG.Neural.Forms.NeuralControl2D.backgroundWorker2D.
btnGenerateOptData2D_Click() [2/5]
void IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click (object sender, EventArgs e) inline private
Generate training data button.
References IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.GenerateDefaultPoints2D(), IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D(), IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Neural.Forms.NeuralControl2D.InitializeDefaultData2D(), IG.Neural.Forms.NeuralControl2D.InitializeTrainingData2D(), IG.Neural.Forms.NeuralControl2D.InitializeVerificationData2D(), IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlotsWithoutShow(), IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), IG.Neural.Forms.NeuralControl2D.RemoveApprovimationActors(), IG.Neural.Forms.NeuralControl2D.RemoveApprovimationContureActors(), IG.Neural.Forms.NeuralControl2D.RemoveDefaultActors(), and IG.Neural.Forms.NeuralControl2D.RemoveTrainingPointsActors().
btnShowDefault_Click() [2/5]
void IG.Neural.Forms.NeuralControl2D.btnShowDefault_Click (object sender, EventArgs e) inline private
Show default graph button.
References IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlots(), and IG.Neural.Forms.NeuralControl2D.PreparePlotter2D().
PrepareDefaultPlotsWithoutShow() [2/5]
void IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlotsWithoutShow () inline
References IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph, IG.Neural.Forms.NeuralControl2D.DefaultContourGraph(), IG.Neural.Forms.NeuralControl2D.DefaultGraph2D(), and IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph().
PrepareDefaultPlots() [2/5]
void IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlots () inline
Prepare default plots of.
References IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlotsWithoutShow(), and IG.Neural.Forms.NeuralControl2D.ShowPlot().
rbMaxTrainError2D_CheckedChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.rbMaxTrainError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum training error convergence to be written on graph.
References IG.Neural.Forms.NeuralControl2D.maxTrainErrorEnabled2D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
rbRmsTrainError2D_CheckedChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.rbRmsTrainError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms training error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.rmsTrainErrorEnabled2D, and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
rbMaxVerError2D_CheckedChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.rbMaxVerError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum verification error convergence to be written on graph.
References IG.Neural.Forms.NeuralControl2D.maxVerErrorEnabled2D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
rbRmsVerError2D_CheckedChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.rbRmsVerError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms verification error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.rmsVerErrorEnabled2D, and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
cbSelfMade2D_CheckedChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.cbSelfMade2D_CheckedChanged (object sender, EventArgs e) inline private
Enable posibility to self made the equation.
References IG.Neural.Forms.NeuralControl2D.cbEquation2D, IG.Neural.Forms.NeuralControl2D.cbSelfMade2D, and IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D.
cbTrainingPoints2D_CheckedChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D_CheckedChanged (object sender, EventArgs e) inline private
Enable training points on graph.
References IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D, and IG.Neural.Forms.NeuralControl2D.trainingPointsonGraph.
cbDefaultSurface2D_CheckedChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D_CheckedChanged (object sender, EventArgs e) inline private
Enable surface for default function on graph.
References IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D, and IG.Neural.Forms.NeuralControl2D.defaultSurfaceonGraph.
cbDefaultGreed2D_CheckedChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D_CheckedChanged (object sender, EventArgs e) inline private
Enable greed for default function on graph.
References IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D, and IG.Neural.Forms.NeuralControl2D.defaultGreedonGraph.
cbApproximationSurface2D_CheckedChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D_CheckedChanged (object sender, EventArgs e) inline private
Enable surface for approximation function on graph.
References IG.Neural.Forms.NeuralControl2D.approximationSurfaceonGraph, and IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D.
cbApproximationGreed2D_CheckedChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D_CheckedChanged (object sender, EventArgs e) inline private
Enable greed for approximation function on graph.
References IG.Neural.Forms.NeuralControl2D.approximationGreedonGraph, and IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D.
cbContourDefault2D_CheckedChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.cbContourDefault2D_CheckedChanged (object sender, EventArgs e) inline private
Enable conture for default function on graph.
References IG.Neural.Forms.NeuralControl2D.cbContourDefault2D, and IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph.
cbContourApproximation2D_CheckedChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D_CheckedChanged (object sender, EventArgs e) inline private
Enable conture for approximation function on graph.
References IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D, and IG.Neural.Forms.NeuralControl2D.contureApproximationonGraph.
cbRandomData2D_CheckedChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.cbRandomData2D_CheckedChanged (object sender, EventArgs e) inline private
Enable random training points.
References IG.Neural.Forms.NeuralControl2D.ResetAll2D().
cbScaleTo_CheckedChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.cbScaleTo_CheckedChanged (object sender, EventArgs e) inline private
Enable scaling to range 1.
References IG.Neural.Forms.NeuralControl2D.ResetAll2D().
trackbDefaultGraph2D_Scroll() [2/5]
void IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D_Scroll (object sender, EventArgs e) inline private
Opacity for visualization of default function.
References IG.Neural.Forms.NeuralControl2D.opacityDefaultGraph2D, and IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D.
trackbApproxGraph2D_Scroll() [2/5]
void IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D_Scroll (object sender, EventArgs e) inline private
Opacity for visualization of approximation function.
References IG.Neural.Forms.NeuralControl2D.opacityApproxGraph2D, and IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D.
trackbContourGraph2D_Scroll() [2/5]
void IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D_Scroll (object sender, EventArgs e) inline private
Opacity for visualization of contures.
References IG.Neural.Forms.NeuralControl2D.opacityContourGraph2D, and IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D.
cbEquation2D_SelectedIndexChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.cbEquation2D_SelectedIndexChanged (object sender, EventArgs e) inline private
Select equation from the list.
References IG.Neural.Forms.NeuralControl2D.cbEquation2D, IG.Neural.Forms.NeuralControl2D.equation2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
tbSelfMadeEquation2D_TextChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D_TextChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.equation2D, and IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D.
numSamplesX2D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.numSamplesX2D_ValueChanged (object sender, EventArgs e) inline private
Number of training samples on X axe.
References IG.Neural.Forms.NeuralControl2D.numSamplesX2D, and IG.Neural.Forms.NeuralControl2D.samplesX2D.
numSamplesY2D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.numSamplesY2D_ValueChanged (object sender, EventArgs e) inline private
Number of training samples on Y axe.
References IG.Neural.Forms.NeuralControl2D.numSamplesY2D, and IG.Neural.Forms.NeuralControl2D.samplesY2D.
numLowXLimit2D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.numLowXLimit2D_ValueChanged (object sender, EventArgs e) inline private
Lower limit for x-axes on the graph.
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.lowHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.numLowXLimit2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
numHighXLimit2D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.numHighXLimit2D_ValueChanged (object sender, EventArgs e) inline private
Higher limit for x-axes on the graph.
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.highHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.numHighXLimit2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
numHighYLimit2D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.numHighYLimit2D_ValueChanged (object sender, EventArgs e) inline private
Higher limit for y-axes on the graph.
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.highVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.numHighYLimit2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
numLowYLimit2D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.numLowYLimit2D_ValueChanged (object sender, EventArgs e) inline private
Lower limit for y-axes on the graph.
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.lowVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.numLowYLimit2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
numMaxEpoch2D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D_ValueChanged (object sender, EventArgs e) inline private
Maximum number of epochs.
References IG.Neural.Forms.NeuralControl2D.maxEpoch2D, and IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D.
numEpochBundle2D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.numEpochBundle2D_ValueChanged (object sender, EventArgs e) inline private
Number of epochs in bundle.
References IG.Neural.Forms.NeuralControl2D.epochInBundle2D, and IG.Neural.Forms.NeuralControl2D.numEpochBundle2D.
numRMS2D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.numRMS2D_ValueChanged (object sender, EventArgs e) inline private
Rms error limit.
References IG.Neural.Forms.NeuralControl2D.numRMS2D, and IG.Neural.Forms.NeuralControl2D.rmsError2D.
numLearningRate2D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.numLearningRate2D_ValueChanged (object sender, EventArgs e) inline private
Learning rate.
References IG.Neural.Forms.NeuralControl2D.learningRate2D, and IG.Neural.Forms.NeuralControl2D.numLearningRate2D.
numMomentum2D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.numMomentum2D_ValueChanged (object sender, EventArgs e) inline private
Momentum.
References IG.Neural.Forms.NeuralControl2D.momentum2D, and IG.Neural.Forms.NeuralControl2D.numMomentum2D.
numHiddenNeuron2D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in first hidden layer.
References IG.Neural.Forms.NeuralControl2D.hiddenNeuronL12D, and IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D.
numHiddenNeuronL22D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in second hidden layer.
References IG.Neural.Forms.NeuralControl2D.hiddenNeuronL22D, and IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D.
numInputSafety2D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.numInputSafety2D_ValueChanged (object sender, EventArgs e) inline private
Input safety factor.
References IG.Neural.Forms.NeuralControl2D.inputSafetyFactor2D, and IG.Neural.Forms.NeuralControl2D.numInputSafety2D.
numOutputSafety2D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralControl2D.numOutputSafety2D_ValueChanged (object sender, EventArgs e) inline private
Output safety factor.
References IG.Neural.Forms.NeuralControl2D.numOutputSafety2D, and IG.Neural.Forms.NeuralControl2D.outputSafetyFactor2D.
backgroundWorker2D_DoWork() [2/5]
void IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_DoWork (object sender, DoWorkEventArgs e) inline private
References IG.Neural.NeuralNetworks.BreakTraining, IG.Neural.Forms.NeuralControl2D.network2D, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Neural.Forms.NeuralControl2D.stopTraining2D, IG.Neural.Forms.NeuralControl2D.trainingData2D, IG.Neural.NeuralNetworks.TrainNetwork(), and IG.Neural.Forms.NeuralControl2D.verificationData2D.
backgroundWorker2D_RunWorkerCompleted() [2/5]
void IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.btLoadANN2D, IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D, IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btReset2D, IG.Neural.Forms.NeuralControl2D.btSaveANN2D, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.btStop2D, IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts(), IG.Neural.Forms.NeuralControl2D.ShowPlot(), and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
ShowPlot() [2/5]
void IG.Neural.Forms.NeuralControl2D.ShowPlot () inline protected
Shows the plot.
References IG.Gr3d.VtkPlotter.BoundsScaled, IG.Neural.Forms.NeuralControl2D.cbScaleTo, IG.Neural.Forms.NeuralControl2D.DecorHandler(), IG.Gr3d.VtkPlotter.IsScaled, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Num.BoundingBoxBase.Reset(), IG.Gr3d.VtkPlotter.ResetCamera(), IG.Neural.Forms.NeuralControl2D.ScaledBounds, IG.Gr3d.VtkPlotter.ShowPlot(), and IG.Num.BoundingBox3d.Update().
Dispose() [2/5]
override void IG.Neural.Forms.NeuralControl2D.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralControl2D.components.
InitializeComponent() [2/5]
void IG.Neural.Forms.NeuralControl2D.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralControl2D.backgroundWorker2D, IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_DoWork(), IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralControl2D.btLoad2D, IG.Neural.Forms.NeuralControl2D.btLoadANN2D, IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D, IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowApprox_Click(), IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btnShowDefault_Click(), IG.Neural.Forms.NeuralControl2D.btReset2D, IG.Neural.Forms.NeuralControl2D.btReset2D_Click(), IG.Neural.Forms.NeuralControl2D.btSaveANN2D, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.btStop2D, IG.Neural.Forms.NeuralControl2D.btStop2D_Click(), IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D, IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D, IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D, IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbContourDefault2D, IG.Neural.Forms.NeuralControl2D.cbContourDefault2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D, IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D, IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbEquation2D, IG.Neural.Forms.NeuralControl2D.cbEquation2D_SelectedIndexChanged(), IG.Neural.Forms.NeuralControl2D.cbRandomData2D, IG.Neural.Forms.NeuralControl2D.cbRandomData2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbScaleTo, IG.Neural.Forms.NeuralControl2D.cbScaleTo_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbSelfMade2D, IG.Neural.Forms.NeuralControl2D.cbSelfMade2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D, IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.errorConvergence2D, IG.Neural.Forms.NeuralControl2D.groupBox1, IG.Neural.Forms.NeuralControl2D.groupBox2, IG.Neural.Forms.NeuralControl2D.groupBox3, IG.Neural.Forms.NeuralControl2D.groupBox4, IG.Neural.Forms.NeuralControl2D.groupBox8, IG.Neural.Forms.NeuralControl2D.label10, IG.Neural.Forms.NeuralControl2D.label14, IG.Neural.Forms.NeuralControl2D.label17, IG.Neural.Forms.NeuralControl2D.label18, IG.Neural.Forms.NeuralControl2D.label20, IG.Neural.Forms.NeuralControl2D.label21, IG.Neural.Forms.NeuralControl2D.label22, IG.Neural.Forms.NeuralControl2D.label23, IG.Neural.Forms.NeuralControl2D.label24, IG.Neural.Forms.NeuralControl2D.label25, IG.Neural.Forms.NeuralControl2D.label26, IG.Neural.Forms.NeuralControl2D.label27, IG.Neural.Forms.NeuralControl2D.label28, IG.Neural.Forms.NeuralControl2D.label29, IG.Neural.Forms.NeuralControl2D.label3, IG.Neural.Forms.NeuralControl2D.label30, IG.Neural.Forms.NeuralControl2D.label31, IG.Neural.Forms.NeuralControl2D.label32, IG.Neural.Forms.NeuralControl2D.label33, IG.Neural.Forms.NeuralControl2D.label34, IG.Neural.Forms.NeuralControl2D.label35, IG.Neural.Forms.NeuralControl2D.label36, IG.Neural.Forms.NeuralControl2D.label37, IG.Neural.Forms.NeuralControl2D.LoadForm(), IG.Neural.Forms.NeuralControl2D.numEpochBundle2D, IG.Neural.Forms.NeuralControl2D.numEpochBundle2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D, IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D, IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHighXLimit2D, IG.Neural.Forms.NeuralControl2D.numHighXLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHighYLimit2D, IG.Neural.Forms.NeuralControl2D.numHighYLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numInputSafety2D, IG.Neural.Forms.NeuralControl2D.numInputSafety2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numLearningRate2D, IG.Neural.Forms.NeuralControl2D.numLearningRate2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numLowXLimit2D, IG.Neural.Forms.NeuralControl2D.numLowXLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numLowYLimit2D, IG.Neural.Forms.NeuralControl2D.numLowYLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D, IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numMomentum2D, IG.Neural.Forms.NeuralControl2D.numMomentum2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numOutputSafety2D, IG.Neural.Forms.NeuralControl2D.numOutputSafety2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numRMS2D, IG.Neural.Forms.NeuralControl2D.numRMS2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numSamplesX2D, IG.Neural.Forms.NeuralControl2D.numSamplesX2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numSamplesY2D, IG.Neural.Forms.NeuralControl2D.numSamplesY2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.rbMaxTrainError2D, IG.Neural.Forms.NeuralControl2D.rbMaxTrainError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.rbMaxVerError2D, IG.Neural.Forms.NeuralControl2D.rbMaxVerError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.rbRmsTrainError2D, IG.Neural.Forms.NeuralControl2D.rbRmsTrainError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.rbRmsVerError2D, IG.Neural.Forms.NeuralControl2D.rbRmsVerError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.tbEquationError2D, IG.Neural.Forms.NeuralControl2D.tbMaxTrainError2D, IG.Neural.Forms.NeuralControl2D.tbMaxVerError2D, IG.Neural.Forms.NeuralControl2D.tbRmsTrainError2D, IG.Neural.Forms.NeuralControl2D.tbRmsVerError2D, IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D, IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D_TextChanged(), IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D, IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D_Scroll(), IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D, IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D_Scroll(), IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D, and IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D_Scroll().
LoadForm() [3/5]
void IG.Neural.Forms.NeuralControl2D.LoadForm (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.errorConvergence2D, and IG.Neural.Forms.NeuralControl2D.pane2DError.
CreateGreenRedYellow() [3/5]
static ColorScale IG.Neural.Forms.NeuralControl2D.CreateGreenRedYellow (double minValue, double maxValue) inline static
InitializeApproximator2D() [3/5]
void IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D () inline private
Clean and initialize the approximator.
References IG.Neural.Forms.NeuralControl2D.Approximator_BundleCompleted(), IG.Neural.Forms.NeuralControl2D.Aproximator_TrainingCompleted(), IG.Num.INeuralApproximator.BundleCompleted, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Num.INeuralApproximator.OutputLevel, IG.Neural.Forms.NeuralControl2D.OutputLevel, and IG.Num.INeuralApproximator.TrainingCompleted.
InitializeTrainingData2D() [3/5]
void IG.Neural.Forms.NeuralControl2D.InitializeTrainingData2D () inline private
Clean and initialize the training data set.
References IG.Neural.Forms.NeuralControl2D.trainingData2D.
InitializeVerificationData2D() [3/5]
void IG.Neural.Forms.NeuralControl2D.InitializeVerificationData2D () inline private
Clean and initialize the verification data set.
References IG.Neural.Forms.NeuralControl2D.verificationData2D.
InitializeDefaultData2D() [3/5]
void IG.Neural.Forms.NeuralControl2D.InitializeDefaultData2D () inline private
Clean and initialize the default data set.
References IG.Neural.Forms.NeuralControl2D.defaultFunctionData2D.
WriteErrors2D() [3/5]
void IG.Neural.Forms.NeuralControl2D.WriteErrors2D () inline private
Write training and verification errors in text box.
References IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Num.INeuralApproximator.ConvergenceErrorsTrainingMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsTrainingRmsList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationRmsList, IG.Neural.Forms.NeuralControl2D.epochInBundle2D, IG.Neural.Forms.NeuralControl2D.errorConvergence2D, IG.Neural.Forms.NeuralControl2D.errorConvergenceFunction2D, IG.Num.INeuralApproximator.GetErrorsTrainingMax(), IG.Num.INeuralApproximator.GetErrorsTrainingRms(), IG.Num.INeuralApproximator.GetErrorsVerificationMax(), IG.Num.INeuralApproximator.GetErrorsVerificationRms(), IG.Neural.Forms.NeuralControl2D.maxTrainErrorEnabled2D, IG.Neural.Forms.NeuralControl2D.maxVerErrorEnabled2D, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.pane2DError, IG.Neural.Forms.NeuralControl2D.rmsTrainErrorEnabled2D, IG.Neural.Forms.NeuralControl2D.rmsVerErrorEnabled2D, IG.Neural.Forms.NeuralControl2D.tbMaxTrainError2D, IG.Neural.Forms.NeuralControl2D.tbMaxVerError2D, IG.Neural.Forms.NeuralControl2D.tbRmsTrainError2D, and IG.Neural.Forms.NeuralControl2D.tbRmsVerError2D.
ClearErrorGraph2D() [3/5]
void IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D () inline private
Clear Graph with error convergence for 2 dimension.
References IG.Neural.Forms.NeuralControl2D.errorConvergence2D, IG.Neural.Forms.NeuralControl2D.errorConvergenceFunction2D, IG.Neural.Forms.NeuralControl2D.tbMaxTrainError2D, IG.Neural.Forms.NeuralControl2D.tbMaxVerError2D, IG.Neural.Forms.NeuralControl2D.tbRmsTrainError2D, and IG.Neural.Forms.NeuralControl2D.tbRmsVerError2D.
PreparePlotter2D() [3/5]
void IG.Neural.Forms.NeuralControl2D.PreparePlotter2D () inline
References IG.Neural.Forms.NeuralControl2D.plotter2D.
DecorHandler() [3/5]
void IG.Neural.Forms.NeuralControl2D.DecorHandler () inline
Initialize decoration handler.
References IG.Gr3d.VtkPlotter.BackGround, IG.Gr3d.VtkDecorationHandler.CubeAxesFlyMode, IG.Gr3d.VtkDecorationHandler.CubeAxesXLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesYLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesZLabel, IG.Gr3d.VtkPlotter.DecorationHandler, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkPlotter.WindowSizeX, and IG.Gr3d.VtkPlotter.WindowSizeY.
GenerateDefaultPoints2D() [3/5]
void IG.Neural.Forms.NeuralControl2D.GenerateDefaultPoints2D () inline
Generates the set of default points according to settings.
References IG.Num.Func2dFromScalarScript.CreateScalarFunction(), IG.Neural.Forms.NeuralControl2D.Default2DMesh, IG.Neural.Forms.NeuralControl2D.equation2D, IG.Num.StructuredMesh2d3d.GenerateCoordinates(), IG.Neural.Forms.NeuralControl2D.iFunctionDefault2D, IG.Num.BoundingBox2d.MaxX, IG.Num.BoundingBox2d.MaxY, IG.Num.BoundingBox2d.MinX, IG.Num.BoundingBox2d.MinY, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.scalarFunctionDefault2D, IG.Neural.Forms.NeuralControl2D.tbEquationError2D, IG.Num.IScalarFunctionUntransformed.Value(), and IG.Neural.Forms.NeuralControl2D.variableNames2D.
DefaultGraph2D() [3/5]
void IG.Neural.Forms.NeuralControl2D.DefaultGraph2D () inline
Generates plot from default points according to settings.
References IG.Neural.Forms.NeuralControl2D.contureApproximationonGraph, IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph, IG.Gr3d.VtkSurfacePlot.Create(), IG.Neural.Forms.NeuralControl2D.Default2DMesh, IG.Neural.Forms.NeuralControl2D.defaultGreedonGraph, IG.Neural.Forms.NeuralControl2D.defaultSurfaceonGraph, IG.Gr3d.VtkSurfacePlotBase.LineColor, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Neural.Forms.NeuralControl2D.opacityDefaultGraph2D, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D, IG.Neural.Forms.NeuralControl2D.plotDefault2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
RemoveDefaultActors() [3/5]
void IG.Neural.Forms.NeuralControl2D.RemoveDefaultActors () inline
References IG.Neural.Forms.NeuralControl2D.plotDefault2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
GenerateTrainingPoints2D() [3/5]
void IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D () inline
Generates the set of training points according to settings.
References IG.Num.SampledDataSet.AddElement(), IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.cbRandomData2D, IG.Num.Func2dFromScalarScript.CreateScalarFunction(), IG.Neural.Forms.NeuralControl2D.equation2D, IG.Num.StructuredMesh2d3d.GenerateCoordinates(), IG.Num.BoundingBoxBase.GetRandomPoint(), IG.Num.BoundingBox2d.MaxX, IG.Num.BoundingBox2d.MaxY, IG.Num.BoundingBox2d.MinX, IG.Num.BoundingBox2d.MinY, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.samplesX2D, IG.Neural.Forms.NeuralControl2D.samplesY2D, IG.Neural.Forms.NeuralControl2D.scalarFunctionTraining2D, IG.Neural.Forms.NeuralControl2D.trainingData2D, IG.Neural.Forms.NeuralControl2D.TrainingPointsMesh2D, IG.Num.IScalarFunctionUntransformed.Value(), and IG.Neural.Forms.NeuralControl2D.variableNames2D.
TrainingPointsGraph() [3/5]
void IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph () inline
Generates plot from training points according to settings.
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Neural.Forms.NeuralControl2D.plotTrainingPoints2D, IG.Gr3d.VtkSurfacePlotBase.PointColor, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible, IG.Neural.Forms.NeuralControl2D.TrainingPointsMesh2D, and IG.Neural.Forms.NeuralControl2D.trainingPointsonGraph.
RemoveTrainingPointsActors() [3/5]
void IG.Neural.Forms.NeuralControl2D.RemoveTrainingPointsActors () inline
References IG.Neural.Forms.NeuralControl2D.plotTrainingPoints2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
ApproximationGraph() [3/5]
void IG.Neural.Forms.NeuralControl2D.ApproximationGraph () inline
Generates plot from approximated points according to settings.
References IG.Neural.Forms.NeuralControl2D.approximationGreedonGraph, IG.Neural.Forms.NeuralControl2D.approximationSurfaceonGraph, IG.Gr3d.VtkSurfacePlot.Create(), IG.Neural.Forms.NeuralControl2D.CreateGreenRedYellow(), IG.Neural.Forms.NeuralControl2D.iFunctionApproximator2D, IG.Neural.Forms.NeuralControl2D.iFunctionDefault2D, IG.Neural.Forms.NeuralControl2D.iFunctionDifference2D, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LineColorScale, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Neural.Forms.NeuralControl2D.opacityApproxGraph2D, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotApproximation2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Neural.Forms.NeuralControl2D.SclarBar2D(), IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible, and IG.Gr3d.VtkSurfacePlot.ValueFunctionOfCoordinates.
RemoveApproximationActors() [2/4]
void IG.Neural.Forms.NeuralControl2D.RemoveApproximationActors () inline
References IG.Neural.Forms.NeuralControl2D.plotApproximation2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
ApproximationContourGraph() [3/5]
void IG.Neural.Forms.NeuralControl2D.ApproximationContourGraph () inline
Generates conture plot from approximated points according to settings.
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Lib.ColorScaleBase.CreateRainbow(), IG.Neural.Forms.NeuralControl2D.iFunctionApproximator2D, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Gr3d.VtkContourPlot.NumContours, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Neural.Forms.NeuralControl2D.opacityContourGraph2D, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
RemoveApproximationContureActors() [2/4]
void IG.Neural.Forms.NeuralControl2D.RemoveApproximationContureActors () inline
References IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
DefaultContourGraph() [3/5]
void IG.Neural.Forms.NeuralControl2D.DefaultContourGraph () inline
Generates conture plot from default points according to settings.
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Lib.ColorScaleBase.CreateRainbow(), IG.Neural.Forms.NeuralControl2D.iFunctionDefault2D, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Gr3d.VtkContourPlot.NumContours, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Neural.Forms.NeuralControl2D.opacityContourGraph2D, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotDefaultConture2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
RemoveDefaultContureActors() [3/5]
void IG.Neural.Forms.NeuralControl2D.RemoveDefaultContureActors () inline
References IG.Neural.Forms.NeuralControl2D.plotDefaultConture2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
SclarBar2D() [3/5]
void IG.Neural.Forms.NeuralControl2D.SclarBar2D (double minRange, double maxRange, ColorScale Color) inline
Scalar bar initialization.
References IG.Gr3d.VtkPlotter.DecorationHandler, IG.Gr3d.VtkDecorationHandler.LookUpTableColorScale, IG.Gr3d.VtkDecorationHandler.LookUpTableMaxRange, IG.Gr3d.VtkDecorationHandler.LookUpTableMinRange, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkDecorationHandler.ScalarBarNumberOfLabels, IG.Gr3d.VtkDecorationHandler.ScalarBarTitle, and IG.Gr3d.VtkDecorationHandler.ShowScalarBar.
Bounds2D() [3/5]
void IG.Neural.Forms.NeuralControl2D.Bounds2D () inline
References IG.Neural.Forms.NeuralControl2D.highHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.highVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.lowHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.lowVerticalLimit2D, and IG.Neural.Forms.NeuralControl2D.paramBounds2D.
ResetAll2D() [3/5]
void IG.Neural.Forms.NeuralControl2D.ResetAll2D () inline
Invalidates training results AND training data, and makes corresponding changes in GUI (e.g. disables certain buttons, etc.).
References IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Neural.Forms.NeuralControl2D.InitializeDefaultData2D(), IG.Neural.Forms.NeuralControl2D.InitializeTrainingData2D(), IG.Neural.Forms.NeuralControl2D.InitializeVerificationData2D(), IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), IG.Neural.Forms.NeuralControl2D.progressBar1, IG.Neural.Forms.NeuralControl2D.RemoveApproximationActors(), IG.Neural.Forms.NeuralControl2D.RemoveApproximationContureActors(), IG.Neural.Forms.NeuralControl2D.RemoveDefaultActors(), and IG.Neural.Forms.NeuralControl2D.RemoveTrainingPointsActors().
ResetResults2D() [2/4]
void IG.Neural.Forms.NeuralControl2D.ResetResults2D () inline
Invalidates the training results and makes corresponding changes in GUI to reflect this.
References IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), IG.Neural.Forms.NeuralControl2D.progressBar1, IG.Neural.Forms.NeuralControl2D.RemoveApproximationActors(), IG.Neural.Forms.NeuralControl2D.RemoveApproximationContureActors(), and IG.Neural.Forms.NeuralControl2D.RemoveTrainingPointsActors().
btReset2D_Click() [3/5]
void IG.Neural.Forms.NeuralControl2D.btReset2D_Click (object sender, EventArgs e) inline private
Reset button.
References IG.Neural.Forms.NeuralControl2D.ResetAll2D().
SetNetworkParameters() [2/4]
void IG.Neural.Forms.NeuralControl2D.SetNetworkParameters (INeuralApproximator neural) inline protected
Prepares network parameters.
btStart2D_Click() [3/5]
void IG.Neural.Forms.NeuralControl2D.btStart2D_Click (object sender, EventArgs e) inline private
Start training button.
References IG.Num.SampledDataSet.AddElement(), IG.Neural.Forms.NeuralControl2D.btLoadANN2D, IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D, IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btReset2D, IG.Neural.Forms.NeuralControl2D.btSaveANN2D, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.btStop2D, IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Num.SampledDataSet.InputLength, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Num.SampledDataSet.OutputLength, IG.Neural.Forms.NeuralControl2D.plotApproximation2D, IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D, IG.Neural.Forms.NeuralControl2D.plotDefault2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), IG.Neural.Forms.NeuralControl2D.progressBar1, IG.Gr3d.VtkPlotter.RemovePlotObject(), IG.Neural.Forms.NeuralControl2D.SetNetworkParameters(), IG.Neural.Forms.NeuralControl2D.trainingData2D, IG.Neural.Forms.NeuralControl2D.TrainNetworkThread2D(), and IG.Neural.Forms.NeuralControl2D.verificationData2D.
btnShowApprox_Click() [3/5]
void IG.Neural.Forms.NeuralControl2D.btnShowApprox_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts(), IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), and IG.Neural.Forms.NeuralControl2D.ShowPlot().
PrepareApproximationPolts() [3/5]
void IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts () inline
Prepare approximation plots.
References IG.Neural.Forms.NeuralControl2D.ApproximationContourGraph(), IG.Neural.Forms.NeuralControl2D.ApproximationGraph(), IG.Neural.Forms.NeuralControl2D.contureApproximationonGraph, IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph, IG.Neural.Forms.NeuralControl2D.DefaultContourGraph(), IG.Neural.Forms.NeuralControl2D.DefaultGraph2D(), and IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph().
btStop2D_Click() [3/5]
void IG.Neural.Forms.NeuralControl2D.btStop2D_Click (object sender, EventArgs e) inline private
Stop training button.
References IG.Num.INeuralApproximator.BreakTraining, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, and IG.Neural.Forms.NeuralControl2D.stopTraining2D.
TrainNetworkThread2D() [3/5]
void IG.Neural.Forms.NeuralControl2D.TrainNetworkThread2D () inline private
References IG.Neural.Forms.NeuralControl2D.backgroundWorker2D.
btnGenerateOptData2D_Click() [3/5]
void IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click (object sender, EventArgs e) inline private
Generate training data button.
References IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.GenerateDefaultPoints2D(), IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D(), IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Neural.Forms.NeuralControl2D.InitializeDefaultData2D(), IG.Neural.Forms.NeuralControl2D.InitializeTrainingData2D(), IG.Neural.Forms.NeuralControl2D.InitializeVerificationData2D(), IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlotsWithoutShow(), IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), IG.Neural.Forms.NeuralControl2D.progressBar1, IG.Neural.Forms.NeuralControl2D.RemoveApproximationActors(), IG.Neural.Forms.NeuralControl2D.RemoveApproximationContureActors(), IG.Neural.Forms.NeuralControl2D.RemoveDefaultActors(), and IG.Neural.Forms.NeuralControl2D.RemoveTrainingPointsActors().
btnShowDefault_Click() [3/5]
void IG.Neural.Forms.NeuralControl2D.btnShowDefault_Click (object sender, EventArgs e) inline private
Show default graph button.
References IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlots(), and IG.Neural.Forms.NeuralControl2D.PreparePlotter2D().
PrepareDefaultPlotsWithoutShow() [3/5]
void IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlotsWithoutShow () inline
References IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph, IG.Neural.Forms.NeuralControl2D.DefaultContourGraph(), IG.Neural.Forms.NeuralControl2D.DefaultGraph2D(), and IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph().
PrepareDefaultPlots() [3/5]
void IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlots () inline
Prepare default plots of.
References IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlotsWithoutShow(), and IG.Neural.Forms.NeuralControl2D.ShowPlot().
rbMaxTrainError2D_CheckedChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.rbMaxTrainError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum training error convergence to be written on graph.
References IG.Neural.Forms.NeuralControl2D.maxTrainErrorEnabled2D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
rbRmsTrainError2D_CheckedChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.rbRmsTrainError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms training error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.rmsTrainErrorEnabled2D, and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
rbMaxVerError2D_CheckedChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.rbMaxVerError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum verification error convergence to be written on graph.
References IG.Neural.Forms.NeuralControl2D.maxVerErrorEnabled2D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
rbRmsVerError2D_CheckedChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.rbRmsVerError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms verification error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.rmsVerErrorEnabled2D, and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
cbSelfMade2D_CheckedChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.cbSelfMade2D_CheckedChanged (object sender, EventArgs e) inline private
Enable posibility to self made the equation.
References IG.Neural.Forms.NeuralControl2D.cbEquation2D, IG.Neural.Forms.NeuralControl2D.cbSelfMade2D, and IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D.
cbTrainingPoints2D_CheckedChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D_CheckedChanged (object sender, EventArgs e) inline private
Enable training points on graph.
References IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D, and IG.Neural.Forms.NeuralControl2D.trainingPointsonGraph.
cbDefaultSurface2D_CheckedChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D_CheckedChanged (object sender, EventArgs e) inline private
Enable surface for default function on graph.
References IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D, and IG.Neural.Forms.NeuralControl2D.defaultSurfaceonGraph.
cbDefaultGreed2D_CheckedChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D_CheckedChanged (object sender, EventArgs e) inline private
Enable greed for default function on graph.
References IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D, and IG.Neural.Forms.NeuralControl2D.defaultGreedonGraph.
cbApproximationSurface2D_CheckedChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D_CheckedChanged (object sender, EventArgs e) inline private
Enable surface for approximation function on graph.
References IG.Neural.Forms.NeuralControl2D.approximationSurfaceonGraph, and IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D.
cbApproximationGreed2D_CheckedChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D_CheckedChanged (object sender, EventArgs e) inline private
Enable greed for approximation function on graph.
References IG.Neural.Forms.NeuralControl2D.approximationGreedonGraph, and IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D.
cbContourDefault2D_CheckedChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.cbContourDefault2D_CheckedChanged (object sender, EventArgs e) inline private
Enable conture for default function on graph.
References IG.Neural.Forms.NeuralControl2D.cbContourDefault2D, and IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph.
cbContourApproximation2D_CheckedChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D_CheckedChanged (object sender, EventArgs e) inline private
Enable conture for approximation function on graph.
References IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D, and IG.Neural.Forms.NeuralControl2D.contureApproximationonGraph.
cbRandomData2D_CheckedChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.cbRandomData2D_CheckedChanged (object sender, EventArgs e) inline private
Enable random training points.
References IG.Neural.Forms.NeuralControl2D.ResetAll2D().
cbScaleTo_CheckedChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.cbScaleTo_CheckedChanged (object sender, EventArgs e) inline private
Enable scaling to range 1.
References IG.Neural.Forms.NeuralControl2D.ResetAll2D().
trackbDefaultGraph2D_Scroll() [3/5]
void IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D_Scroll (object sender, EventArgs e) inline private
Opacity for visualization of default function.
References IG.Neural.Forms.NeuralControl2D.opacityDefaultGraph2D, and IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D.
trackbApproxGraph2D_Scroll() [3/5]
void IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D_Scroll (object sender, EventArgs e) inline private
Opacity for visualization of approximation function.
References IG.Neural.Forms.NeuralControl2D.opacityApproxGraph2D, and IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D.
trackbContourGraph2D_Scroll() [3/5]
void IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D_Scroll (object sender, EventArgs e) inline private
Opacity for visualization of contures.
References IG.Neural.Forms.NeuralControl2D.opacityContourGraph2D, and IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D.
cbEquation2D_SelectedIndexChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.cbEquation2D_SelectedIndexChanged (object sender, EventArgs e) inline private
Select equation from the list.
References IG.Neural.Forms.NeuralControl2D.cbEquation2D, IG.Neural.Forms.NeuralControl2D.equation2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
tbSelfMadeEquation2D_TextChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D_TextChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.equation2D, and IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D.
numSamplesX2D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.numSamplesX2D_ValueChanged (object sender, EventArgs e) inline private
Number of training samples on X axe.
References IG.Neural.Forms.NeuralControl2D.numSamplesX2D, IG.Neural.Forms.NeuralControl2D.ResetAll2D(), and IG.Neural.Forms.NeuralControl2D.samplesX2D.
numSamplesY2D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.numSamplesY2D_ValueChanged (object sender, EventArgs e) inline private
Number of training samples on Y axe.
References IG.Neural.Forms.NeuralControl2D.numSamplesY2D, IG.Neural.Forms.NeuralControl2D.ResetAll2D(), and IG.Neural.Forms.NeuralControl2D.samplesY2D.
numLowXLimit2D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.numLowXLimit2D_ValueChanged (object sender, EventArgs e) inline private
Lower limit for x-axes on the graph.
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.lowHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.numLowXLimit2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
numHighXLimit2D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.numHighXLimit2D_ValueChanged (object sender, EventArgs e) inline private
Higher limit for x-axes on the graph.
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.highHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.numHighXLimit2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
numHighYLimit2D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.numHighYLimit2D_ValueChanged (object sender, EventArgs e) inline private
Higher limit for y-axes on the graph.
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.highVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.numHighYLimit2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
numLowYLimit2D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.numLowYLimit2D_ValueChanged (object sender, EventArgs e) inline private
Lower limit for y-axes on the graph.
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.lowVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.numLowYLimit2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
numMaxEpoch2D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D_ValueChanged (object sender, EventArgs e) inline private
Maximum number of epochs.
References IG.Neural.Forms.NeuralControl2D.maxEpoch2D, IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
numEpochBundle2D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.numEpochBundle2D_ValueChanged (object sender, EventArgs e) inline private
Number of epochs in bundle.
References IG.Neural.Forms.NeuralControl2D.epochInBundle2D, and IG.Neural.Forms.NeuralControl2D.numEpochBundle2D.
numRMS2D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.numRMS2D_ValueChanged (object sender, EventArgs e) inline private
Rms error limit.
References IG.Neural.Forms.NeuralControl2D.numRMS2D, IG.Neural.Forms.NeuralControl2D.ResetResults2D(), and IG.Neural.Forms.NeuralControl2D.rmsError2D.
numLearningRate2D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.numLearningRate2D_ValueChanged (object sender, EventArgs e) inline private
Learning rate.
References IG.Neural.Forms.NeuralControl2D.learningRate2D, IG.Neural.Forms.NeuralControl2D.numLearningRate2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
numMomentum2D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.numMomentum2D_ValueChanged (object sender, EventArgs e) inline private
Momentum.
References IG.Neural.Forms.NeuralControl2D.momentum2D, IG.Neural.Forms.NeuralControl2D.numMomentum2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
numHiddenNeuron2D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in first hidden layer.
References IG.Neural.Forms.NeuralControl2D.hiddenNeuronL12D, IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
numHiddenNeuronL22D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in second hidden layer.
References IG.Neural.Forms.NeuralControl2D.hiddenNeuronL22D, IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
numInputSafety2D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.numInputSafety2D_ValueChanged (object sender, EventArgs e) inline private
Input safety factor.
References IG.Neural.Forms.NeuralControl2D.inputSafetyFactor2D, IG.Neural.Forms.NeuralControl2D.numInputSafety2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
numOutputSafety2D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralControl2D.numOutputSafety2D_ValueChanged (object sender, EventArgs e) inline private
Output safety factor.
References IG.Neural.Forms.NeuralControl2D.numOutputSafety2D, IG.Neural.Forms.NeuralControl2D.outputSafetyFactor2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
Approximator_BundleCompleted() [2/4]
void IG.Neural.Forms.NeuralControl2D.Approximator_BundleCompleted (object obj, EventArgs args) inline protected
Event handler that is executed when a new bundle of training epochs completes.
Updates progress bar.
References IG.Num.INeuralApproximator.EpochCount, IG.Num.INeuralApproximator.MaxEpochs, IG.Num.INeuralApproximator.OutputLevel, and IG.Neural.Forms.NeuralControl2D.progressBar1.
Aproximator_TrainingCompleted() [2/4]
void IG.Neural.Forms.NeuralControl2D.Aproximator_TrainingCompleted (object obj, EventArgs args) inline protected
Event handler that is executed when a new bundle of training epochs completes.
References IG.Num.INeuralApproximator.EpochCount, IG.Num.INeuralApproximator.MaxEpochs, IG.Num.INeuralApproximator.OutputLevel, and IG.Neural.Forms.NeuralControl2D.progressBar1.
TrainNetwork() [2/4]
INeuralApproximator IG.Neural.Forms.NeuralControl2D.TrainNetwork (SampledDataSet trainingData, SampledDataSet verificationData) inline protected
Performs training of neural network.
Parameters
trainingData Training data.
verificationData Verification data.
Returns
References IG.Neural.Forms.NeuralControl2D.epochInBundle2D, IG.Num.NeuralApproximatorBase.EpochsInBundle, IG.Neural.Forms.NeuralControl2D.hiddenNeuronL12D, IG.Neural.Forms.NeuralControl2D.hiddenNeuronL22D, IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Num.NeuralApproximatorBase.InputBoundsSafetyFactor, IG.Num.SampledDataSet.InputLength, IG.Num.NeuralApproximatorBase.InputLength, IG.Num.NeuralApproximatorBase.InputNeuronsRange, IG.Neural.Forms.NeuralControl2D.inputSafetyFactor2D, IG.Num.NeuralApproximatorBase.LearningRate, IG.Neural.Forms.NeuralControl2D.learningRate2D, IG.Num.SampledDataSet.Length, IG.Num.VectorApproximatorBase.Lock, IG.Neural.Forms.NeuralControl2D.maxEpoch2D, IG.Num.NeuralApproximatorBase.MaxEpochs, IG.Num.NeuralApproximatorBase.Momentum, IG.Neural.Forms.NeuralControl2D.momentum2D, IG.Num.NeuralApproximatorBase.MultipleNetworks, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Num.NeuralApproximatorBase.OutputBoundsSafetyFactor, IG.Num.SampledDataSet.OutputLength, IG.Num.NeuralApproximatorBase.OutputLength, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Num.NeuralApproximatorBase.OutputLevel, IG.Num.NeuralApproximatorBase.OutputNeuronsRange, IG.Neural.Forms.NeuralControl2D.outputSafetyFactor2D, IG.Num.IBoundingBox.Reset(), IG.Neural.Forms.NeuralControl2D.rmsError2D, IG.Num.NeuralApproximatorBase.SaveConvergenceRms, IG.Num.NeuralApproximatorBase.SetHiddenLayers(), IG.Num.NeuralApproximatorBase.SetTrainingAndVerificationData(), IG.Num.NeuralApproximatorBase.SigmoidAlphaValue, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.StopWatch1.Time, IG.Num.NeuralApproximatorBase.ToleranceRms, IG.Num.NeuralApproximatorBase.ToString(), IG.Num.NeuralApproximatorBase.TrainingData, IG.Num.NeuralApproximatorBase.TrainNetwork(), and IG.Num.IBoundingBox.UpdateAll().
backgroundWorker2D_DoWork() [3/5]
void IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_DoWork (object sender, DoWorkEventArgs e) inline private
References IG.Num.INeuralApproximator.BreakTraining, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Neural.Forms.NeuralControl2D.stopTraining2D, IG.Neural.Forms.NeuralControl2D.trainingData2D, IG.Neural.Forms.NeuralControl2D.TrainNetwork(), and IG.Neural.Forms.NeuralControl2D.verificationData2D.
backgroundWorker2D_RunWorkerCompleted() [3/5]
void IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.btLoadANN2D, IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D, IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btReset2D, IG.Neural.Forms.NeuralControl2D.btSaveANN2D, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.btStop2D, IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts(), IG.Neural.Forms.NeuralControl2D.ShowPlot(), and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
ShowPlot() [3/5]
void IG.Neural.Forms.NeuralControl2D.ShowPlot () inline protected
Shows the plot.
References IG.Gr3d.VtkPlotter.BoundsScaled, IG.Neural.Forms.NeuralControl2D.cbScaleTo, IG.Neural.Forms.NeuralControl2D.DecorHandler(), IG.Gr3d.VtkPlotter.IsScaled, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Num.BoundingBoxBase.Reset(), IG.Gr3d.VtkPlotter.ResetCamera(), IG.Neural.Forms.NeuralControl2D.ScaledBounds, IG.Gr3d.VtkPlotter.ShowPlot(), and IG.Num.BoundingBox3d.Update().
Dispose() [3/5]
override void IG.Neural.Forms.NeuralControl2D.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralControl2D.components.
InitializeComponent() [3/5]
void IG.Neural.Forms.NeuralControl2D.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralControl2D.backgroundWorker2D, IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_DoWork(), IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralControl2D.btLoad2D, IG.Neural.Forms.NeuralControl2D.btLoadANN2D, IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D, IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowApprox_Click(), IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btnShowDefault_Click(), IG.Neural.Forms.NeuralControl2D.btReset2D, IG.Neural.Forms.NeuralControl2D.btReset2D_Click(), IG.Neural.Forms.NeuralControl2D.btSaveANN2D, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.btStop2D, IG.Neural.Forms.NeuralControl2D.btStop2D_Click(), IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D, IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D, IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D, IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbContourDefault2D, IG.Neural.Forms.NeuralControl2D.cbContourDefault2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D, IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D, IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbEquation2D, IG.Neural.Forms.NeuralControl2D.cbEquation2D_SelectedIndexChanged(), IG.Neural.Forms.NeuralControl2D.cbRandomData2D, IG.Neural.Forms.NeuralControl2D.cbRandomData2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbScaleTo, IG.Neural.Forms.NeuralControl2D.cbScaleTo_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbSelfMade2D, IG.Neural.Forms.NeuralControl2D.cbSelfMade2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D, IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.components, IG.Neural.Forms.NeuralControl2D.errorConvergence2D, IG.Neural.Forms.NeuralControl2D.groupBox1, IG.Neural.Forms.NeuralControl2D.groupBox2, IG.Neural.Forms.NeuralControl2D.groupBox3, IG.Neural.Forms.NeuralControl2D.groupBox4, IG.Neural.Forms.NeuralControl2D.groupBox8, IG.Neural.Forms.NeuralControl2D.label10, IG.Neural.Forms.NeuralControl2D.label14, IG.Neural.Forms.NeuralControl2D.label17, IG.Neural.Forms.NeuralControl2D.label18, IG.Neural.Forms.NeuralControl2D.label20, IG.Neural.Forms.NeuralControl2D.label21, IG.Neural.Forms.NeuralControl2D.label22, IG.Neural.Forms.NeuralControl2D.label23, IG.Neural.Forms.NeuralControl2D.label24, IG.Neural.Forms.NeuralControl2D.label25, IG.Neural.Forms.NeuralControl2D.label26, IG.Neural.Forms.NeuralControl2D.label27, IG.Neural.Forms.NeuralControl2D.label28, IG.Neural.Forms.NeuralControl2D.label29, IG.Neural.Forms.NeuralControl2D.label3, IG.Neural.Forms.NeuralControl2D.label30, IG.Neural.Forms.NeuralControl2D.label31, IG.Neural.Forms.NeuralControl2D.label32, IG.Neural.Forms.NeuralControl2D.label33, IG.Neural.Forms.NeuralControl2D.label34, IG.Neural.Forms.NeuralControl2D.label35, IG.Neural.Forms.NeuralControl2D.label36, IG.Neural.Forms.NeuralControl2D.label37, IG.Neural.Forms.NeuralControl2D.LoadForm(), IG.Neural.Forms.NeuralControl2D.numEpochBundle2D, IG.Neural.Forms.NeuralControl2D.numEpochBundle2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D, IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D, IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHighXLimit2D, IG.Neural.Forms.NeuralControl2D.numHighXLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHighYLimit2D, IG.Neural.Forms.NeuralControl2D.numHighYLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numInputSafety2D, IG.Neural.Forms.NeuralControl2D.numInputSafety2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numLearningRate2D, IG.Neural.Forms.NeuralControl2D.numLearningRate2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numLowXLimit2D, IG.Neural.Forms.NeuralControl2D.numLowXLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numLowYLimit2D, IG.Neural.Forms.NeuralControl2D.numLowYLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D, IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numMomentum2D, IG.Neural.Forms.NeuralControl2D.numMomentum2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numOutputSafety2D, IG.Neural.Forms.NeuralControl2D.numOutputSafety2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numRMS2D, IG.Neural.Forms.NeuralControl2D.numRMS2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numSamplesX2D, IG.Neural.Forms.NeuralControl2D.numSamplesX2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numSamplesY2D, IG.Neural.Forms.NeuralControl2D.numSamplesY2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.progressBar1, IG.Neural.Forms.NeuralControl2D.rbMaxTrainError2D, IG.Neural.Forms.NeuralControl2D.rbMaxTrainError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.rbMaxVerError2D, IG.Neural.Forms.NeuralControl2D.rbMaxVerError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.rbRmsTrainError2D, IG.Neural.Forms.NeuralControl2D.rbRmsTrainError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.rbRmsVerError2D, IG.Neural.Forms.NeuralControl2D.rbRmsVerError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.tbEquationError2D, IG.Neural.Forms.NeuralControl2D.tbMaxTrainError2D, IG.Neural.Forms.NeuralControl2D.tbMaxVerError2D, IG.Neural.Forms.NeuralControl2D.tbRmsTrainError2D, IG.Neural.Forms.NeuralControl2D.tbRmsVerError2D, IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D, IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D_TextChanged(), IG.Neural.Forms.NeuralControl2D.toolTip1, IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D, IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D_Scroll(), IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D, IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D_Scroll(), IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D, and IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D_Scroll().
LoadForm() [4/5]
void IG.Neural.Forms.NeuralControl2D.LoadForm (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.errorConvergence2D, and IG.Neural.Forms.NeuralControl2D.pane2DError.
CreateGreenRedYellow() [4/5]
static ColorScale IG.Neural.Forms.NeuralControl2D.CreateGreenRedYellow (double minValue, double maxValue) inline static
InitializeApproximator2D() [4/5]
void IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D () inline private
Clean and initialize the approximator.
References IG.Neural.Forms.NeuralControl2D.Approximator_BundleCompleted(), IG.Neural.Forms.NeuralControl2D.Aproximator_TrainingCompleted(), IG.Num.INeuralApproximator.BundleCompleted, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Num.INeuralApproximator.OutputLevel, IG.Neural.Forms.NeuralControl2D.OutputLevel, and IG.Num.INeuralApproximator.TrainingCompleted.
InitializeTrainingData2D() [4/5]
void IG.Neural.Forms.NeuralControl2D.InitializeTrainingData2D () inline private
Clean and initialize the training data set.
References IG.Neural.Forms.NeuralControl2D.trainingData2D.
InitializeVerificationData2D() [4/5]
void IG.Neural.Forms.NeuralControl2D.InitializeVerificationData2D () inline private
Clean and initialize the verification data set.
References IG.Neural.Forms.NeuralControl2D.verificationData2D.
InitializeDefaultData2D() [4/5]
void IG.Neural.Forms.NeuralControl2D.InitializeDefaultData2D () inline private
Clean and initialize the default data set.
References IG.Neural.Forms.NeuralControl2D.defaultFunctionData2D.
WriteErrors2D() [4/5]
void IG.Neural.Forms.NeuralControl2D.WriteErrors2D () inline private
Write training and verification errors in text box.
References IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Num.INeuralApproximator.ConvergenceErrorsTrainingMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsTrainingRmsList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationRmsList, IG.Neural.Forms.NeuralControl2D.epochInBundle2D, IG.Neural.Forms.NeuralControl2D.errorConvergence2D, IG.Neural.Forms.NeuralControl2D.errorConvergenceFunction2D, IG.Num.INeuralApproximator.GetErrorsTrainingMax(), IG.Num.INeuralApproximator.GetErrorsTrainingRms(), IG.Num.INeuralApproximator.GetErrorsVerificationMax(), IG.Num.INeuralApproximator.GetErrorsVerificationRms(), IG.Neural.Forms.NeuralControl2D.maxTrainErrorEnabled2D, IG.Neural.Forms.NeuralControl2D.maxVerErrorEnabled2D, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.pane2DError, IG.Neural.Forms.NeuralControl2D.rmsTrainErrorEnabled2D, IG.Neural.Forms.NeuralControl2D.rmsVerErrorEnabled2D, IG.Neural.Forms.NeuralControl2D.tbMaxTrainError2D, IG.Neural.Forms.NeuralControl2D.tbMaxVerError2D, IG.Neural.Forms.NeuralControl2D.tbRmsTrainError2D, and IG.Neural.Forms.NeuralControl2D.tbRmsVerError2D.
ClearErrorGraph2D() [4/5]
void IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D () inline private
Clear Graph with error convergence for 2 dimension.
References IG.Neural.Forms.NeuralControl2D.errorConvergence2D, IG.Neural.Forms.NeuralControl2D.errorConvergenceFunction2D, IG.Neural.Forms.NeuralControl2D.tbMaxTrainError2D, IG.Neural.Forms.NeuralControl2D.tbMaxVerError2D, IG.Neural.Forms.NeuralControl2D.tbRmsTrainError2D, and IG.Neural.Forms.NeuralControl2D.tbRmsVerError2D.
PreparePlotter2D() [4/5]
void IG.Neural.Forms.NeuralControl2D.PreparePlotter2D () inline
References IG.Neural.Forms.NeuralControl2D.plotter2D.
DecorHandler() [4/5]
void IG.Neural.Forms.NeuralControl2D.DecorHandler () inline
Initialize decoration handler.
References IG.Gr3d.VtkPlotter.BackGround, IG.Gr3d.VtkDecorationHandler.CubeAxesFlyMode, IG.Gr3d.VtkDecorationHandler.CubeAxesXLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesYLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesZLabel, IG.Gr3d.VtkPlotter.DecorationHandler, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkPlotter.WindowSizeX, and IG.Gr3d.VtkPlotter.WindowSizeY.
GenerateDefaultPoints2D() [4/5]
void IG.Neural.Forms.NeuralControl2D.GenerateDefaultPoints2D () inline
Generates the set of default points according to settings.
References IG.Num.Func2dFromScalarScript.CreateScalarFunction(), IG.Neural.Forms.NeuralControl2D.Default2DMesh, IG.Neural.Forms.NeuralControl2D.equation2D, IG.Num.StructuredMesh2d3d.GenerateCoordinates(), IG.Neural.Forms.NeuralControl2D.iFunctionDefault2D, IG.Num.BoundingBox2d.MaxX, IG.Num.BoundingBox2d.MaxY, IG.Num.BoundingBox2d.MinX, IG.Num.BoundingBox2d.MinY, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.scalarFunctionDefault2D, IG.Neural.Forms.NeuralControl2D.tbEquationError2D, IG.Num.IScalarFunctionUntransformed.Value(), and IG.Neural.Forms.NeuralControl2D.variableNames2D.
DefaultGraph2D() [4/5]
void IG.Neural.Forms.NeuralControl2D.DefaultGraph2D () inline
Generates plot from default points according to settings.
References IG.Neural.Forms.NeuralControl2D.contureApproximationonGraph, IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph, IG.Gr3d.VtkSurfacePlot.Create(), IG.Neural.Forms.NeuralControl2D.Default2DMesh, IG.Neural.Forms.NeuralControl2D.defaultGreedonGraph, IG.Neural.Forms.NeuralControl2D.defaultSurfaceonGraph, IG.Gr3d.VtkSurfacePlotBase.LineColor, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Neural.Forms.NeuralControl2D.opacityDefaultGraph2D, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D, IG.Neural.Forms.NeuralControl2D.plotDefault2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
RemoveDefaultActors() [4/5]
void IG.Neural.Forms.NeuralControl2D.RemoveDefaultActors () inline
References IG.Neural.Forms.NeuralControl2D.plotDefault2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
GenerateTrainingPoints2D() [4/5]
void IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D () inline
Generates the set of training points according to settings.
References IG.Num.SampledDataSet.AddElement(), IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.cbRandomData2D, IG.Num.Func2dFromScalarScript.CreateScalarFunction(), IG.Neural.Forms.NeuralControl2D.equation2D, IG.Num.StructuredMesh2d3d.GenerateCoordinates(), IG.Num.BoundingBoxBase.GetRandomPoint(), IG.Num.BoundingBox2d.MaxX, IG.Num.BoundingBox2d.MaxY, IG.Num.BoundingBox2d.MinX, IG.Num.BoundingBox2d.MinY, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.samplesX2D, IG.Neural.Forms.NeuralControl2D.samplesY2D, IG.Neural.Forms.NeuralControl2D.scalarFunctionTraining2D, IG.Neural.Forms.NeuralControl2D.trainingData2D, IG.Neural.Forms.NeuralControl2D.TrainingPointsMesh2D, IG.Num.IScalarFunctionUntransformed.Value(), and IG.Neural.Forms.NeuralControl2D.variableNames2D.
TrainingPointsGraph() [4/5]
void IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph () inline
Generates plot from training points according to settings.
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Neural.Forms.NeuralControl2D.plotTrainingPoints2D, IG.Gr3d.VtkSurfacePlotBase.PointColor, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible, IG.Neural.Forms.NeuralControl2D.TrainingPointsMesh2D, and IG.Neural.Forms.NeuralControl2D.trainingPointsonGraph.
RemoveTrainingPointsActors() [4/5]
void IG.Neural.Forms.NeuralControl2D.RemoveTrainingPointsActors () inline
References IG.Neural.Forms.NeuralControl2D.plotTrainingPoints2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
ApproximationGraph() [4/5]
void IG.Neural.Forms.NeuralControl2D.ApproximationGraph () inline
Generates plot from approximated points according to settings.
References IG.Neural.Forms.NeuralControl2D.approximationGreedonGraph, IG.Neural.Forms.NeuralControl2D.approximationSurfaceonGraph, IG.Gr3d.VtkSurfacePlot.Create(), IG.Neural.Forms.NeuralControl2D.CreateGreenRedYellow(), IG.Neural.Forms.NeuralControl2D.iFunctionApproximator2D, IG.Neural.Forms.NeuralControl2D.iFunctionDefault2D, IG.Neural.Forms.NeuralControl2D.iFunctionDifference2D, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LineColorScale, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Neural.Forms.NeuralControl2D.opacityApproxGraph2D, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotApproximation2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Neural.Forms.NeuralControl2D.SclarBar2D(), IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible, and IG.Gr3d.VtkSurfacePlot.ValueFunctionOfCoordinates.
RemoveApproximationActors() [3/4]
void IG.Neural.Forms.NeuralControl2D.RemoveApproximationActors () inline
References IG.Neural.Forms.NeuralControl2D.plotApproximation2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
ApproximationContourGraph() [4/5]
void IG.Neural.Forms.NeuralControl2D.ApproximationContourGraph () inline
Generates conture plot from approximated points according to settings.
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Lib.ColorScaleBase.CreateRainbow(), IG.Neural.Forms.NeuralControl2D.iFunctionApproximator2D, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Gr3d.VtkContourPlot.NumContours, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Neural.Forms.NeuralControl2D.opacityContourGraph2D, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
RemoveApproximationContureActors() [3/4]
void IG.Neural.Forms.NeuralControl2D.RemoveApproximationContureActors () inline
References IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
DefaultContourGraph() [4/5]
void IG.Neural.Forms.NeuralControl2D.DefaultContourGraph () inline
Generates conture plot from default points according to settings.
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Lib.ColorScaleBase.CreateRainbow(), IG.Neural.Forms.NeuralControl2D.iFunctionDefault2D, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Gr3d.VtkContourPlot.NumContours, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Neural.Forms.NeuralControl2D.opacityContourGraph2D, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotDefaultConture2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
RemoveDefaultContureActors() [4/5]
void IG.Neural.Forms.NeuralControl2D.RemoveDefaultContureActors () inline
References IG.Neural.Forms.NeuralControl2D.plotDefaultConture2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
SclarBar2D() [4/5]
void IG.Neural.Forms.NeuralControl2D.SclarBar2D (double minRange, double maxRange, ColorScale Color) inline
Scalar bar initialization.
References IG.Gr3d.VtkPlotter.DecorationHandler, IG.Gr3d.VtkDecorationHandler.LookUpTableColorScale, IG.Gr3d.VtkDecorationHandler.LookUpTableMaxRange, IG.Gr3d.VtkDecorationHandler.LookUpTableMinRange, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkDecorationHandler.ScalarBarNumberOfLabels, IG.Gr3d.VtkDecorationHandler.ScalarBarTitle, and IG.Gr3d.VtkDecorationHandler.ShowScalarBar.
Bounds2D() [4/5]
void IG.Neural.Forms.NeuralControl2D.Bounds2D () inline
References IG.Neural.Forms.NeuralControl2D.highHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.highVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.lowHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.lowVerticalLimit2D, and IG.Neural.Forms.NeuralControl2D.paramBounds2D.
ResetAll2D() [4/5]
void IG.Neural.Forms.NeuralControl2D.ResetAll2D () inline
Invalidates training results AND training data, and makes corresponding changes in GUI (e.g. disables certain buttons, etc.).
References IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Neural.Forms.NeuralControl2D.InitializeDefaultData2D(), IG.Neural.Forms.NeuralControl2D.InitializeTrainingData2D(), IG.Neural.Forms.NeuralControl2D.InitializeVerificationData2D(), IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), IG.Neural.Forms.NeuralControl2D.progressBar1, IG.Neural.Forms.NeuralControl2D.RemoveApproximationActors(), IG.Neural.Forms.NeuralControl2D.RemoveApproximationContureActors(), IG.Neural.Forms.NeuralControl2D.RemoveDefaultActors(), and IG.Neural.Forms.NeuralControl2D.RemoveTrainingPointsActors().
ResetResults2D() [3/4]
void IG.Neural.Forms.NeuralControl2D.ResetResults2D () inline
Invalidates the training results and makes corresponding changes in GUI to reflect this.
References IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), IG.Neural.Forms.NeuralControl2D.progressBar1, IG.Neural.Forms.NeuralControl2D.RemoveApproximationActors(), IG.Neural.Forms.NeuralControl2D.RemoveApproximationContureActors(), and IG.Neural.Forms.NeuralControl2D.RemoveTrainingPointsActors().
btReset2D_Click() [4/5]
void IG.Neural.Forms.NeuralControl2D.btReset2D_Click (object sender, EventArgs e) inline private
Reset button.
References IG.Neural.Forms.NeuralControl2D.ResetAll2D().
SetNetworkParameters() [3/4]
void IG.Neural.Forms.NeuralControl2D.SetNetworkParameters (INeuralApproximator neural) inline protected
Prepares network parameters.
btStart2D_Click() [4/5]
void IG.Neural.Forms.NeuralControl2D.btStart2D_Click (object sender, EventArgs e) inline private
Start training button.
References IG.Num.SampledDataSet.AddElement(), IG.Neural.Forms.NeuralControl2D.btLoadANN2D, IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D, IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btReset2D, IG.Neural.Forms.NeuralControl2D.btSaveANN2D, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.btStop2D, IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Num.SampledDataSet.InputLength, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Num.SampledDataSet.OutputLength, IG.Neural.Forms.NeuralControl2D.plotApproximation2D, IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D, IG.Neural.Forms.NeuralControl2D.plotDefault2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), IG.Neural.Forms.NeuralControl2D.progressBar1, IG.Gr3d.VtkPlotter.RemovePlotObject(), IG.Neural.Forms.NeuralControl2D.SetNetworkParameters(), IG.Neural.Forms.NeuralControl2D.trainingData2D, IG.Neural.Forms.NeuralControl2D.TrainNetworkThread2D(), and IG.Neural.Forms.NeuralControl2D.verificationData2D.
btnShowApprox_Click() [4/5]
void IG.Neural.Forms.NeuralControl2D.btnShowApprox_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts(), IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), and IG.Neural.Forms.NeuralControl2D.ShowPlot().
PrepareApproximationPolts() [4/5]
void IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts () inline
Prepare approximation plots.
References IG.Neural.Forms.NeuralControl2D.ApproximationContourGraph(), IG.Neural.Forms.NeuralControl2D.ApproximationGraph(), IG.Neural.Forms.NeuralControl2D.contureApproximationonGraph, IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph, IG.Neural.Forms.NeuralControl2D.DefaultContourGraph(), IG.Neural.Forms.NeuralControl2D.DefaultGraph2D(), and IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph().
btStop2D_Click() [4/5]
void IG.Neural.Forms.NeuralControl2D.btStop2D_Click (object sender, EventArgs e) inline private
Stop training button.
References IG.Num.INeuralApproximator.BreakTraining, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, and IG.Neural.Forms.NeuralControl2D.stopTraining2D.
TrainNetworkThread2D() [4/5]
void IG.Neural.Forms.NeuralControl2D.TrainNetworkThread2D () inline private
References IG.Neural.Forms.NeuralControl2D.backgroundWorker2D.
btnGenerateOptData2D_Click() [4/5]
void IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click (object sender, EventArgs e) inline private
Generate training data button.
References IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.GenerateDefaultPoints2D(), IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D(), IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Neural.Forms.NeuralControl2D.InitializeDefaultData2D(), IG.Neural.Forms.NeuralControl2D.InitializeTrainingData2D(), IG.Neural.Forms.NeuralControl2D.InitializeVerificationData2D(), IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlotsWithoutShow(), IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), IG.Neural.Forms.NeuralControl2D.progressBar1, IG.Neural.Forms.NeuralControl2D.RemoveApproximationActors(), IG.Neural.Forms.NeuralControl2D.RemoveApproximationContureActors(), IG.Neural.Forms.NeuralControl2D.RemoveDefaultActors(), and IG.Neural.Forms.NeuralControl2D.RemoveTrainingPointsActors().
btnShowDefault_Click() [4/5]
void IG.Neural.Forms.NeuralControl2D.btnShowDefault_Click (object sender, EventArgs e) inline private
Show default graph button.
References IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlots(), and IG.Neural.Forms.NeuralControl2D.PreparePlotter2D().
PrepareDefaultPlotsWithoutShow() [4/5]
void IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlotsWithoutShow () inline
References IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph, IG.Neural.Forms.NeuralControl2D.DefaultContourGraph(), IG.Neural.Forms.NeuralControl2D.DefaultGraph2D(), and IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph().
PrepareDefaultPlots() [4/5]
void IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlots () inline
Prepare default plots of.
References IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlotsWithoutShow(), and IG.Neural.Forms.NeuralControl2D.ShowPlot().
rbMaxTrainError2D_CheckedChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.rbMaxTrainError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum training error convergence to be written on graph.
References IG.Neural.Forms.NeuralControl2D.maxTrainErrorEnabled2D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
rbRmsTrainError2D_CheckedChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.rbRmsTrainError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms training error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.rmsTrainErrorEnabled2D, and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
rbMaxVerError2D_CheckedChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.rbMaxVerError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum verification error convergence to be written on graph.
References IG.Neural.Forms.NeuralControl2D.maxVerErrorEnabled2D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
rbRmsVerError2D_CheckedChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.rbRmsVerError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms verification error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.rmsVerErrorEnabled2D, and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
cbSelfMade2D_CheckedChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.cbSelfMade2D_CheckedChanged (object sender, EventArgs e) inline private
Enable posibility to self made the equation.
References IG.Neural.Forms.NeuralControl2D.cbEquation2D, IG.Neural.Forms.NeuralControl2D.cbSelfMade2D, and IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D.
cbTrainingPoints2D_CheckedChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D_CheckedChanged (object sender, EventArgs e) inline private
Enable training points on graph.
References IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D, and IG.Neural.Forms.NeuralControl2D.trainingPointsonGraph.
cbDefaultSurface2D_CheckedChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D_CheckedChanged (object sender, EventArgs e) inline private
Enable surface for default function on graph.
References IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D, and IG.Neural.Forms.NeuralControl2D.defaultSurfaceonGraph.
cbDefaultGreed2D_CheckedChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D_CheckedChanged (object sender, EventArgs e) inline private
Enable greed for default function on graph.
References IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D, and IG.Neural.Forms.NeuralControl2D.defaultGreedonGraph.
cbApproximationSurface2D_CheckedChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D_CheckedChanged (object sender, EventArgs e) inline private
Enable surface for approximation function on graph.
References IG.Neural.Forms.NeuralControl2D.approximationSurfaceonGraph, and IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D.
cbApproximationGreed2D_CheckedChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D_CheckedChanged (object sender, EventArgs e) inline private
Enable greed for approximation function on graph.
References IG.Neural.Forms.NeuralControl2D.approximationGreedonGraph, and IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D.
cbContourDefault2D_CheckedChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.cbContourDefault2D_CheckedChanged (object sender, EventArgs e) inline private
Enable conture for default function on graph.
References IG.Neural.Forms.NeuralControl2D.cbContourDefault2D, and IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph.
cbContourApproximation2D_CheckedChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D_CheckedChanged (object sender, EventArgs e) inline private
Enable conture for approximation function on graph.
References IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D, and IG.Neural.Forms.NeuralControl2D.contureApproximationonGraph.
cbRandomData2D_CheckedChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.cbRandomData2D_CheckedChanged (object sender, EventArgs e) inline private
Enable random training points.
References IG.Neural.Forms.NeuralControl2D.ResetAll2D().
cbScaleTo_CheckedChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.cbScaleTo_CheckedChanged (object sender, EventArgs e) inline private
Enable scaling to range 1.
References IG.Neural.Forms.NeuralControl2D.ResetAll2D().
trackbDefaultGraph2D_Scroll() [4/5]
void IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D_Scroll (object sender, EventArgs e) inline private
Opacity for visualization of default function.
References IG.Neural.Forms.NeuralControl2D.opacityDefaultGraph2D, and IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D.
trackbApproxGraph2D_Scroll() [4/5]
void IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D_Scroll (object sender, EventArgs e) inline private
Opacity for visualization of approximation function.
References IG.Neural.Forms.NeuralControl2D.opacityApproxGraph2D, and IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D.
trackbContourGraph2D_Scroll() [4/5]
void IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D_Scroll (object sender, EventArgs e) inline private
Opacity for visualization of contures.
References IG.Neural.Forms.NeuralControl2D.opacityContourGraph2D, and IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D.
cbEquation2D_SelectedIndexChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.cbEquation2D_SelectedIndexChanged (object sender, EventArgs e) inline private
Select equation from the list.
References IG.Neural.Forms.NeuralControl2D.cbEquation2D, IG.Neural.Forms.NeuralControl2D.equation2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
tbSelfMadeEquation2D_TextChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D_TextChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.equation2D, and IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D.
numSamplesX2D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.numSamplesX2D_ValueChanged (object sender, EventArgs e) inline private
Number of training samples on X axe.
References IG.Neural.Forms.NeuralControl2D.numSamplesX2D, IG.Neural.Forms.NeuralControl2D.ResetAll2D(), and IG.Neural.Forms.NeuralControl2D.samplesX2D.
numSamplesY2D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.numSamplesY2D_ValueChanged (object sender, EventArgs e) inline private
Number of training samples on Y axe.
References IG.Neural.Forms.NeuralControl2D.numSamplesY2D, IG.Neural.Forms.NeuralControl2D.ResetAll2D(), and IG.Neural.Forms.NeuralControl2D.samplesY2D.
numLowXLimit2D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.numLowXLimit2D_ValueChanged (object sender, EventArgs e) inline private
Lower limit for x-axes on the graph.
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.lowHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.numLowXLimit2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
numHighXLimit2D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.numHighXLimit2D_ValueChanged (object sender, EventArgs e) inline private
Higher limit for x-axes on the graph.
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.highHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.numHighXLimit2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
numHighYLimit2D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.numHighYLimit2D_ValueChanged (object sender, EventArgs e) inline private
Higher limit for y-axes on the graph.
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.highVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.numHighYLimit2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
numLowYLimit2D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.numLowYLimit2D_ValueChanged (object sender, EventArgs e) inline private
Lower limit for y-axes on the graph.
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.lowVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.numLowYLimit2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
numMaxEpoch2D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D_ValueChanged (object sender, EventArgs e) inline private
Maximum number of epochs.
References IG.Neural.Forms.NeuralControl2D.maxEpoch2D, IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
numEpochBundle2D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.numEpochBundle2D_ValueChanged (object sender, EventArgs e) inline private
Number of epochs in bundle.
References IG.Neural.Forms.NeuralControl2D.epochInBundle2D, and IG.Neural.Forms.NeuralControl2D.numEpochBundle2D.
numRMS2D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.numRMS2D_ValueChanged (object sender, EventArgs e) inline private
Rms error limit.
References IG.Neural.Forms.NeuralControl2D.numRMS2D, IG.Neural.Forms.NeuralControl2D.ResetResults2D(), and IG.Neural.Forms.NeuralControl2D.rmsError2D.
numLearningRate2D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.numLearningRate2D_ValueChanged (object sender, EventArgs e) inline private
Learning rate.
References IG.Neural.Forms.NeuralControl2D.learningRate2D, IG.Neural.Forms.NeuralControl2D.numLearningRate2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
numMomentum2D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.numMomentum2D_ValueChanged (object sender, EventArgs e) inline private
Momentum.
References IG.Neural.Forms.NeuralControl2D.momentum2D, IG.Neural.Forms.NeuralControl2D.numMomentum2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
numHiddenNeuron2D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in first hidden layer.
References IG.Neural.Forms.NeuralControl2D.hiddenNeuronL12D, IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
numHiddenNeuronL22D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in second hidden layer.
References IG.Neural.Forms.NeuralControl2D.hiddenNeuronL22D, IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
numInputSafety2D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.numInputSafety2D_ValueChanged (object sender, EventArgs e) inline private
Input safety factor.
References IG.Neural.Forms.NeuralControl2D.inputSafetyFactor2D, IG.Neural.Forms.NeuralControl2D.numInputSafety2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
numOutputSafety2D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralControl2D.numOutputSafety2D_ValueChanged (object sender, EventArgs e) inline private
Output safety factor.
References IG.Neural.Forms.NeuralControl2D.numOutputSafety2D, IG.Neural.Forms.NeuralControl2D.outputSafetyFactor2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
Approximator_BundleCompleted() [3/4]
void IG.Neural.Forms.NeuralControl2D.Approximator_BundleCompleted (object obj, EventArgs args) inline protected
Event handler that is executed when a new bundle of training epochs completes.
Updates progress bar.
References IG.Num.INeuralApproximator.EpochCount, IG.Num.INeuralApproximator.MaxEpochs, IG.Num.INeuralApproximator.OutputLevel, and IG.Neural.Forms.NeuralControl2D.progressBar1.
Aproximator_TrainingCompleted() [3/4]
void IG.Neural.Forms.NeuralControl2D.Aproximator_TrainingCompleted (object obj, EventArgs args) inline protected
Event handler that is executed when a new bundle of training epochs completes.
References IG.Num.INeuralApproximator.EpochCount, IG.Num.INeuralApproximator.MaxEpochs, IG.Num.INeuralApproximator.OutputLevel, and IG.Neural.Forms.NeuralControl2D.progressBar1.
TrainNetwork() [3/4]
INeuralApproximator IG.Neural.Forms.NeuralControl2D.TrainNetwork (SampledDataSet trainingData, SampledDataSet verificationData) inline protected
Performs training of neural network.
Parameters
trainingData Training data.
verificationData Verification data.
Returns
References IG.Neural.Forms.NeuralControl2D.epochInBundle2D, IG.Num.NeuralApproximatorBase.EpochsInBundle, IG.Neural.Forms.NeuralControl2D.hiddenNeuronL12D, IG.Neural.Forms.NeuralControl2D.hiddenNeuronL22D, IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Num.NeuralApproximatorBase.InputBoundsSafetyFactor, IG.Num.SampledDataSet.InputLength, IG.Num.NeuralApproximatorBase.InputLength, IG.Num.NeuralApproximatorBase.InputNeuronsRange, IG.Neural.Forms.NeuralControl2D.inputSafetyFactor2D, IG.Num.NeuralApproximatorBase.LearningRate, IG.Neural.Forms.NeuralControl2D.learningRate2D, IG.Num.SampledDataSet.Length, IG.Num.VectorApproximatorBase.Lock, IG.Neural.Forms.NeuralControl2D.maxEpoch2D, IG.Num.NeuralApproximatorBase.MaxEpochs, IG.Num.NeuralApproximatorBase.Momentum, IG.Neural.Forms.NeuralControl2D.momentum2D, IG.Num.NeuralApproximatorBase.MultipleNetworks, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Num.NeuralApproximatorBase.OutputBoundsSafetyFactor, IG.Num.SampledDataSet.OutputLength, IG.Num.NeuralApproximatorBase.OutputLength, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Num.NeuralApproximatorBase.OutputLevel, IG.Num.NeuralApproximatorBase.OutputNeuronsRange, IG.Neural.Forms.NeuralControl2D.outputSafetyFactor2D, IG.Num.IBoundingBox.Reset(), IG.Neural.Forms.NeuralControl2D.rmsError2D, IG.Num.NeuralApproximatorBase.SaveConvergenceRms, IG.Num.NeuralApproximatorBase.SetHiddenLayers(), IG.Num.NeuralApproximatorBase.SetTrainingAndVerificationData(), IG.Num.NeuralApproximatorBase.SigmoidAlphaValue, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.StopWatch1.Time, IG.Num.NeuralApproximatorBase.ToleranceRms, IG.Num.NeuralApproximatorBase.ToString(), IG.Num.NeuralApproximatorBase.TrainingData, IG.Num.NeuralApproximatorBase.TrainNetwork(), and IG.Num.IBoundingBox.UpdateAll().
backgroundWorker2D_DoWork() [4/5]
void IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_DoWork (object sender, DoWorkEventArgs e) inline private
References IG.Num.INeuralApproximator.BreakTraining, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Neural.Forms.NeuralControl2D.stopTraining2D, IG.Neural.Forms.NeuralControl2D.trainingData2D, IG.Neural.Forms.NeuralControl2D.TrainNetwork(), and IG.Neural.Forms.NeuralControl2D.verificationData2D.
backgroundWorker2D_RunWorkerCompleted() [4/5]
void IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.btLoadANN2D, IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D, IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btReset2D, IG.Neural.Forms.NeuralControl2D.btSaveANN2D, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.btStop2D, IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts(), IG.Neural.Forms.NeuralControl2D.ShowPlot(), and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
ShowPlot() [4/5]
void IG.Neural.Forms.NeuralControl2D.ShowPlot () inline protected
Shows the plot.
References IG.Gr3d.VtkPlotter.BoundsScaled, IG.Neural.Forms.NeuralControl2D.cbScaleTo, IG.Neural.Forms.NeuralControl2D.DecorHandler(), IG.Gr3d.VtkPlotter.IsScaled, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Num.BoundingBoxBase.Reset(), IG.Gr3d.VtkPlotter.ResetCamera(), IG.Neural.Forms.NeuralControl2D.ScaledBounds, IG.Gr3d.VtkPlotter.ShowPlot(), and IG.Num.BoundingBox3d.Update().
Dispose() [4/5]
override void IG.Neural.Forms.NeuralControl2D.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralControl2D.components.
InitializeComponent() [4/5]
void IG.Neural.Forms.NeuralControl2D.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralControl2D.backgroundWorker2D, IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_DoWork(), IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralControl2D.btLoad2D, IG.Neural.Forms.NeuralControl2D.btLoadANN2D, IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D, IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowApprox_Click(), IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btnShowDefault_Click(), IG.Neural.Forms.NeuralControl2D.btReset2D, IG.Neural.Forms.NeuralControl2D.btReset2D_Click(), IG.Neural.Forms.NeuralControl2D.btSaveANN2D, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.btStop2D, IG.Neural.Forms.NeuralControl2D.btStop2D_Click(), IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D, IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D, IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D, IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbContourDefault2D, IG.Neural.Forms.NeuralControl2D.cbContourDefault2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D, IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D, IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbEquation2D, IG.Neural.Forms.NeuralControl2D.cbEquation2D_SelectedIndexChanged(), IG.Neural.Forms.NeuralControl2D.cbRandomData2D, IG.Neural.Forms.NeuralControl2D.cbRandomData2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbScaleTo, IG.Neural.Forms.NeuralControl2D.cbScaleTo_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbSelfMade2D, IG.Neural.Forms.NeuralControl2D.cbSelfMade2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D, IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.colorDialog1, IG.Neural.Forms.NeuralControl2D.components, IG.Neural.Forms.NeuralControl2D.contextMenuStrip1, IG.Neural.Forms.NeuralControl2D.errorConvergence2D, IG.Neural.Forms.NeuralControl2D.groupBox1, IG.Neural.Forms.NeuralControl2D.groupBox2, IG.Neural.Forms.NeuralControl2D.groupBox3, IG.Neural.Forms.NeuralControl2D.groupBox4, IG.Neural.Forms.NeuralControl2D.groupBox8, IG.Neural.Forms.NeuralControl2D.label10, IG.Neural.Forms.NeuralControl2D.label14, IG.Neural.Forms.NeuralControl2D.label17, IG.Neural.Forms.NeuralControl2D.label18, IG.Neural.Forms.NeuralControl2D.label20, IG.Neural.Forms.NeuralControl2D.label21, IG.Neural.Forms.NeuralControl2D.label22, IG.Neural.Forms.NeuralControl2D.label23, IG.Neural.Forms.NeuralControl2D.label24, IG.Neural.Forms.NeuralControl2D.label25, IG.Neural.Forms.NeuralControl2D.label26, IG.Neural.Forms.NeuralControl2D.label27, IG.Neural.Forms.NeuralControl2D.label28, IG.Neural.Forms.NeuralControl2D.label29, IG.Neural.Forms.NeuralControl2D.label3, IG.Neural.Forms.NeuralControl2D.label30, IG.Neural.Forms.NeuralControl2D.label31, IG.Neural.Forms.NeuralControl2D.label32, IG.Neural.Forms.NeuralControl2D.label33, IG.Neural.Forms.NeuralControl2D.label34, IG.Neural.Forms.NeuralControl2D.label35, IG.Neural.Forms.NeuralControl2D.label36, IG.Neural.Forms.NeuralControl2D.label37, IG.Neural.Forms.NeuralControl2D.menuTooltipBackground, IG.Neural.Forms.NeuralControl2D.menuTooltipColor, IG.Neural.Forms.NeuralControl2D.menuTooltipEnabled, IG.Neural.Forms.NeuralControl2D.menuTooltipForeground, IG.Neural.Forms.NeuralControl2D.menuTooltips, IG.Neural.Forms.NeuralControl2D.numEpochBundle2D, IG.Neural.Forms.NeuralControl2D.numEpochBundle2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D, IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D, IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHighXLimit2D, IG.Neural.Forms.NeuralControl2D.numHighXLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHighYLimit2D, IG.Neural.Forms.NeuralControl2D.numHighYLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numInputSafety2D, IG.Neural.Forms.NeuralControl2D.numInputSafety2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numLearningRate2D, IG.Neural.Forms.NeuralControl2D.numLearningRate2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numLowXLimit2D, IG.Neural.Forms.NeuralControl2D.numLowXLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numLowYLimit2D, IG.Neural.Forms.NeuralControl2D.numLowYLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D, IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numMomentum2D, IG.Neural.Forms.NeuralControl2D.numMomentum2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numOutputSafety2D, IG.Neural.Forms.NeuralControl2D.numOutputSafety2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numRMS2D, IG.Neural.Forms.NeuralControl2D.numRMS2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numSamplesX2D, IG.Neural.Forms.NeuralControl2D.numSamplesX2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numSamplesY2D, IG.Neural.Forms.NeuralControl2D.numSamplesY2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.progressBar1, IG.Neural.Forms.NeuralControl2D.rbMaxTrainError2D, IG.Neural.Forms.NeuralControl2D.rbMaxTrainError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.rbMaxVerError2D, IG.Neural.Forms.NeuralControl2D.rbMaxVerError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.rbRmsTrainError2D, IG.Neural.Forms.NeuralControl2D.rbRmsTrainError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.rbRmsVerError2D, IG.Neural.Forms.NeuralControl2D.rbRmsVerError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.tbEquationError2D, IG.Neural.Forms.NeuralControl2D.tbMaxTrainError2D, IG.Neural.Forms.NeuralControl2D.tbMaxVerError2D, IG.Neural.Forms.NeuralControl2D.tbRmsTrainError2D, IG.Neural.Forms.NeuralControl2D.tbRmsVerError2D, IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D, IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D_TextChanged(), IG.Neural.Forms.NeuralControl2D.toolTip1, IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D, IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D_Scroll(), IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D, IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D_Scroll(), IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D, and IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D_Scroll().
LoadForm() [5/5]
void IG.Neural.Forms.NeuralControl2D.LoadForm (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.errorConvergence2D, and IG.Neural.Forms.NeuralControl2D.pane2DError.
CreateGreenRedYellow() [5/5]
static ColorScale IG.Neural.Forms.NeuralControl2D.CreateGreenRedYellow (double minValue, double maxValue) inline static
InitializeApproximator2D() [5/5]
void IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D () inline private
Clean and initialize the approximator.
References IG.Neural.Forms.NeuralControl2D.Approximator_BundleCompleted(), IG.Neural.Forms.NeuralControl2D.Aproximator_TrainingCompleted(), IG.Num.INeuralApproximator.BundleCompleted, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Num.INeuralApproximator.OutputLevel, IG.Neural.Forms.NeuralControl2D.OutputLevel, and IG.Num.INeuralApproximator.TrainingCompleted.
InitializeTrainingData2D() [5/5]
void IG.Neural.Forms.NeuralControl2D.InitializeTrainingData2D () inline private
Clean and initialize the training data set.
References IG.Neural.Forms.NeuralControl2D.trainingData2D.
InitializeVerificationData2D() [5/5]
void IG.Neural.Forms.NeuralControl2D.InitializeVerificationData2D () inline private
Clean and initialize the verification data set.
References IG.Neural.Forms.NeuralControl2D.verificationData2D.
InitializeDefaultData2D() [5/5]
void IG.Neural.Forms.NeuralControl2D.InitializeDefaultData2D () inline private
Clean and initialize the default data set.
References IG.Neural.Forms.NeuralControl2D.defaultFunctionData2D.
WriteErrors2D() [5/5]
void IG.Neural.Forms.NeuralControl2D.WriteErrors2D () inline private
Write training and verification errors in text box.
References IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Num.INeuralApproximator.ConvergenceErrorsTrainingMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsTrainingRmsList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationRmsList, IG.Neural.Forms.NeuralControl2D.epochInBundle2D, IG.Neural.Forms.NeuralControl2D.errorConvergence2D, IG.Neural.Forms.NeuralControl2D.errorConvergenceFunction2D, IG.Num.INeuralApproximator.GetErrorsTrainingMax(), IG.Num.INeuralApproximator.GetErrorsTrainingRms(), IG.Num.INeuralApproximator.GetErrorsVerificationMax(), IG.Num.INeuralApproximator.GetErrorsVerificationRms(), IG.Neural.Forms.NeuralControl2D.maxTrainErrorEnabled2D, IG.Neural.Forms.NeuralControl2D.maxVerErrorEnabled2D, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.pane2DError, IG.Neural.Forms.NeuralControl2D.rmsTrainErrorEnabled2D, IG.Neural.Forms.NeuralControl2D.rmsVerErrorEnabled2D, IG.Neural.Forms.NeuralControl2D.tbMaxTrainError2D, IG.Neural.Forms.NeuralControl2D.tbMaxVerError2D, IG.Neural.Forms.NeuralControl2D.tbRmsTrainError2D, and IG.Neural.Forms.NeuralControl2D.tbRmsVerError2D.
ClearErrorGraph2D() [5/5]
void IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D () inline private
Clear Graph with error convergence for 2 dimension.
References IG.Neural.Forms.NeuralControl2D.errorConvergence2D, IG.Neural.Forms.NeuralControl2D.errorConvergenceFunction2D, IG.Neural.Forms.NeuralControl2D.tbMaxTrainError2D, IG.Neural.Forms.NeuralControl2D.tbMaxVerError2D, IG.Neural.Forms.NeuralControl2D.tbRmsTrainError2D, and IG.Neural.Forms.NeuralControl2D.tbRmsVerError2D.
PreparePlotter2D() [5/5]
void IG.Neural.Forms.NeuralControl2D.PreparePlotter2D () inline
References IG.Neural.Forms.NeuralControl2D.plotter2D.
DecorHandler() [5/5]
void IG.Neural.Forms.NeuralControl2D.DecorHandler () inline
Initialize decoration handler.
References IG.Gr3d.VtkPlotter.BackGround, IG.Gr3d.VtkDecorationHandler.CubeAxesFlyMode, IG.Gr3d.VtkDecorationHandler.CubeAxesXLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesYLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesZLabel, IG.Gr3d.VtkPlotter.DecorationHandler, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkPlotter.WindowSizeX, and IG.Gr3d.VtkPlotter.WindowSizeY.
GenerateDefaultPoints2D() [5/5]
void IG.Neural.Forms.NeuralControl2D.GenerateDefaultPoints2D () inline
Generates the set of default points according to settings.
References IG.Num.Func2dFromScalarScript.CreateScalarFunction(), IG.Neural.Forms.NeuralControl2D.Default2DMesh, IG.Neural.Forms.NeuralControl2D.equation2D, IG.Num.StructuredMesh2d3d.GenerateCoordinates(), IG.Neural.Forms.NeuralControl2D.iFunctionDefault2D, IG.Num.BoundingBox2d.MaxX, IG.Num.BoundingBox2d.MaxY, IG.Num.BoundingBox2d.MinX, IG.Num.BoundingBox2d.MinY, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.scalarFunctionDefault2D, IG.Neural.Forms.NeuralControl2D.tbEquationError2D, IG.Num.IScalarFunctionUntransformed.Value(), and IG.Neural.Forms.NeuralControl2D.variableNames2D.
DefaultGraph2D() [5/5]
void IG.Neural.Forms.NeuralControl2D.DefaultGraph2D () inline
Generates plot from default points according to settings.
References IG.Neural.Forms.NeuralControl2D.contureApproximationonGraph, IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph, IG.Gr3d.VtkSurfacePlot.Create(), IG.Neural.Forms.NeuralControl2D.Default2DMesh, IG.Neural.Forms.NeuralControl2D.defaultGreedonGraph, IG.Neural.Forms.NeuralControl2D.defaultSurfaceonGraph, IG.Gr3d.VtkSurfacePlotBase.LineColor, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Neural.Forms.NeuralControl2D.opacityDefaultGraph2D, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D, IG.Neural.Forms.NeuralControl2D.plotDefault2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
RemoveDefaultActors() [5/5]
void IG.Neural.Forms.NeuralControl2D.RemoveDefaultActors () inline
References IG.Neural.Forms.NeuralControl2D.plotDefault2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
GenerateTrainingPoints2D() [5/5]
void IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D () inline
Generates the set of training points according to settings.
References IG.Num.SampledDataSet.AddElement(), IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.cbRandomData2D, IG.Num.Func2dFromScalarScript.CreateScalarFunction(), IG.Neural.Forms.NeuralControl2D.equation2D, IG.Num.StructuredMesh2d3d.GenerateCoordinates(), IG.Num.BoundingBoxBase.GetRandomPoint(), IG.Num.BoundingBox2d.MaxX, IG.Num.BoundingBox2d.MaxY, IG.Num.BoundingBox2d.MinX, IG.Num.BoundingBox2d.MinY, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.samplesX2D, IG.Neural.Forms.NeuralControl2D.samplesY2D, IG.Neural.Forms.NeuralControl2D.scalarFunctionTraining2D, IG.Neural.Forms.NeuralControl2D.trainingData2D, IG.Neural.Forms.NeuralControl2D.TrainingPointsMesh2D, IG.Num.IScalarFunctionUntransformed.Value(), and IG.Neural.Forms.NeuralControl2D.variableNames2D.
TrainingPointsGraph() [5/5]
void IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph () inline
Generates plot from training points according to settings.
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Neural.Forms.NeuralControl2D.plotTrainingPoints2D, IG.Gr3d.VtkSurfacePlotBase.PointColor, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible, IG.Neural.Forms.NeuralControl2D.TrainingPointsMesh2D, and IG.Neural.Forms.NeuralControl2D.trainingPointsonGraph.
RemoveTrainingPointsActors() [5/5]
void IG.Neural.Forms.NeuralControl2D.RemoveTrainingPointsActors () inline
References IG.Neural.Forms.NeuralControl2D.plotTrainingPoints2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
ApproximationGraph() [5/5]
void IG.Neural.Forms.NeuralControl2D.ApproximationGraph () inline
Generates plot from approximated points according to settings.
References IG.Neural.Forms.NeuralControl2D.approximationGreedonGraph, IG.Neural.Forms.NeuralControl2D.approximationSurfaceonGraph, IG.Gr3d.VtkSurfacePlot.Create(), IG.Neural.Forms.NeuralControl2D.CreateGreenRedYellow(), IG.Neural.Forms.NeuralControl2D.iFunctionApproximator2D, IG.Neural.Forms.NeuralControl2D.iFunctionDefault2D, IG.Neural.Forms.NeuralControl2D.iFunctionDifference2D, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LineColorScale, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Neural.Forms.NeuralControl2D.opacityApproxGraph2D, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotApproximation2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Neural.Forms.NeuralControl2D.SclarBar2D(), IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible, and IG.Gr3d.VtkSurfacePlot.ValueFunctionOfCoordinates.
RemoveApproximationActors() [4/4]
void IG.Neural.Forms.NeuralControl2D.RemoveApproximationActors () inline
References IG.Neural.Forms.NeuralControl2D.plotApproximation2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
ApproximationContourGraph() [5/5]
void IG.Neural.Forms.NeuralControl2D.ApproximationContourGraph () inline
Generates conture plot from approximated points according to settings.
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Lib.ColorScaleBase.CreateRainbow(), IG.Neural.Forms.NeuralControl2D.iFunctionApproximator2D, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Gr3d.VtkContourPlot.NumContours, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Neural.Forms.NeuralControl2D.opacityContourGraph2D, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
RemoveApproximationContureActors() [4/4]
void IG.Neural.Forms.NeuralControl2D.RemoveApproximationContureActors () inline
References IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
DefaultContourGraph() [5/5]
void IG.Neural.Forms.NeuralControl2D.DefaultContourGraph () inline
Generates conture plot from default points according to settings.
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Lib.ColorScaleBase.CreateRainbow(), IG.Neural.Forms.NeuralControl2D.iFunctionDefault2D, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Gr3d.VtkContourPlot.NumContours, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Neural.Forms.NeuralControl2D.opacityContourGraph2D, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralControl2D.paramBounds2D, IG.Neural.Forms.NeuralControl2D.plotDefaultConture2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
RemoveDefaultContureActors() [5/5]
void IG.Neural.Forms.NeuralControl2D.RemoveDefaultContureActors () inline
References IG.Neural.Forms.NeuralControl2D.plotDefaultConture2D, and IG.Gr3d.VtkPlotBase.RemoveActors().
SclarBar2D() [5/5]
void IG.Neural.Forms.NeuralControl2D.SclarBar2D (double minRange, double maxRange, ColorScale Color) inline
Scalar bar initialization.
References IG.Gr3d.VtkPlotter.DecorationHandler, IG.Gr3d.VtkDecorationHandler.LookUpTableColorScale, IG.Gr3d.VtkDecorationHandler.LookUpTableMaxRange, IG.Gr3d.VtkDecorationHandler.LookUpTableMinRange, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Gr3d.VtkDecorationHandler.ScalarBarNumberOfLabels, IG.Gr3d.VtkDecorationHandler.ScalarBarTitle, and IG.Gr3d.VtkDecorationHandler.ShowScalarBar.
Bounds2D() [5/5]
void IG.Neural.Forms.NeuralControl2D.Bounds2D () inline
References IG.Neural.Forms.NeuralControl2D.highHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.highVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.lowHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.lowVerticalLimit2D, and IG.Neural.Forms.NeuralControl2D.paramBounds2D.
ResetAll2D() [5/5]
void IG.Neural.Forms.NeuralControl2D.ResetAll2D () inline
Invalidates training results AND training data, and makes corresponding changes in GUI (e.g. disables certain buttons, etc.).
References IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Neural.Forms.NeuralControl2D.InitializeDefaultData2D(), IG.Neural.Forms.NeuralControl2D.InitializeTrainingData2D(), IG.Neural.Forms.NeuralControl2D.InitializeVerificationData2D(), IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), IG.Neural.Forms.NeuralControl2D.progressBar1, IG.Neural.Forms.NeuralControl2D.RemoveApproximationActors(), IG.Neural.Forms.NeuralControl2D.RemoveApproximationContureActors(), IG.Neural.Forms.NeuralControl2D.RemoveDefaultActors(), and IG.Neural.Forms.NeuralControl2D.RemoveTrainingPointsActors().
ResetResults2D() [4/4]
void IG.Neural.Forms.NeuralControl2D.ResetResults2D () inline
Invalidates the training results and makes corresponding changes in GUI to reflect this.
References IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), IG.Neural.Forms.NeuralControl2D.progressBar1, IG.Neural.Forms.NeuralControl2D.RemoveApproximationActors(), IG.Neural.Forms.NeuralControl2D.RemoveApproximationContureActors(), and IG.Neural.Forms.NeuralControl2D.RemoveTrainingPointsActors().
btReset2D_Click() [5/5]
void IG.Neural.Forms.NeuralControl2D.btReset2D_Click (object sender, EventArgs e) inline private
Reset button.
References IG.Neural.Forms.NeuralControl2D.ResetAll2D().
SetNetworkParameters() [4/4]
void IG.Neural.Forms.NeuralControl2D.SetNetworkParameters (INeuralApproximator neural) inline protected
Prepares network parameters.
btStart2D_Click() [5/5]
void IG.Neural.Forms.NeuralControl2D.btStart2D_Click (object sender, EventArgs e) inline private
Start training button.
References IG.Num.SampledDataSet.AddElement(), IG.Neural.Forms.NeuralControl2D.btLoadANN2D, IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D, IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btReset2D, IG.Neural.Forms.NeuralControl2D.btSaveANN2D, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.btStop2D, IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Num.SampledDataSet.InputLength, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.numAllXPoints2D, IG.Neural.Forms.NeuralControl2D.numAllYPoints2D, IG.Num.SampledDataSet.OutputLength, IG.Neural.Forms.NeuralControl2D.plotApproximation2D, IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D, IG.Neural.Forms.NeuralControl2D.plotDefault2D, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), IG.Neural.Forms.NeuralControl2D.progressBar1, IG.Gr3d.VtkPlotter.RemovePlotObject(), IG.Neural.Forms.NeuralControl2D.SetNetworkParameters(), IG.Neural.Forms.NeuralControl2D.trainingData2D, IG.Neural.Forms.NeuralControl2D.TrainNetworkThread2D(), and IG.Neural.Forms.NeuralControl2D.verificationData2D.
btnShowApprox_Click() [5/5]
void IG.Neural.Forms.NeuralControl2D.btnShowApprox_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts(), IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), and IG.Neural.Forms.NeuralControl2D.ShowPlot().
PrepareApproximationPolts() [5/5]
void IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts () inline
Prepare approximation plots.
References IG.Neural.Forms.NeuralControl2D.ApproximationContourGraph(), IG.Neural.Forms.NeuralControl2D.ApproximationGraph(), IG.Neural.Forms.NeuralControl2D.contureApproximationonGraph, IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph, IG.Neural.Forms.NeuralControl2D.DefaultContourGraph(), IG.Neural.Forms.NeuralControl2D.DefaultGraph2D(), and IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph().
btStop2D_Click() [5/5]
void IG.Neural.Forms.NeuralControl2D.btStop2D_Click (object sender, EventArgs e) inline private
Stop training button.
References IG.Num.INeuralApproximator.BreakTraining, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, and IG.Neural.Forms.NeuralControl2D.stopTraining2D.
TrainNetworkThread2D() [5/5]
void IG.Neural.Forms.NeuralControl2D.TrainNetworkThread2D () inline private
References IG.Neural.Forms.NeuralControl2D.backgroundWorker2D.
btnGenerateOptData2D_Click() [5/5]
void IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click (object sender, EventArgs e) inline private
Generate training data button.
References IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.GenerateDefaultPoints2D(), IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D(), IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Neural.Forms.NeuralControl2D.InitializeDefaultData2D(), IG.Neural.Forms.NeuralControl2D.InitializeTrainingData2D(), IG.Neural.Forms.NeuralControl2D.InitializeVerificationData2D(), IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlotsWithoutShow(), IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), IG.Neural.Forms.NeuralControl2D.progressBar1, IG.Neural.Forms.NeuralControl2D.RemoveApproximationActors(), IG.Neural.Forms.NeuralControl2D.RemoveApproximationContureActors(), IG.Neural.Forms.NeuralControl2D.RemoveDefaultActors(), and IG.Neural.Forms.NeuralControl2D.RemoveTrainingPointsActors().
btnShowDefault_Click() [5/5]
void IG.Neural.Forms.NeuralControl2D.btnShowDefault_Click (object sender, EventArgs e) inline private
Show default graph button.
References IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlots(), and IG.Neural.Forms.NeuralControl2D.PreparePlotter2D().
PrepareDefaultPlotsWithoutShow() [5/5]
void IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlotsWithoutShow () inline
References IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph, IG.Neural.Forms.NeuralControl2D.DefaultContourGraph(), IG.Neural.Forms.NeuralControl2D.DefaultGraph2D(), and IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph().
PrepareDefaultPlots() [5/5]
void IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlots () inline
Prepare default plots of.
References IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlotsWithoutShow(), and IG.Neural.Forms.NeuralControl2D.ShowPlot().
rbMaxTrainError2D_CheckedChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.rbMaxTrainError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum training error convergence to be written on graph.
References IG.Neural.Forms.NeuralControl2D.maxTrainErrorEnabled2D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
rbRmsTrainError2D_CheckedChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.rbRmsTrainError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms training error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.rmsTrainErrorEnabled2D, and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
rbMaxVerError2D_CheckedChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.rbMaxVerError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum verification error convergence to be written on graph.
References IG.Neural.Forms.NeuralControl2D.maxVerErrorEnabled2D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
rbRmsVerError2D_CheckedChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.rbRmsVerError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms verification error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Forms.NeuralControl2D.rmsVerErrorEnabled2D, and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
cbSelfMade2D_CheckedChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.cbSelfMade2D_CheckedChanged (object sender, EventArgs e) inline private
Enable posibility to self made the equation.
References IG.Neural.Forms.NeuralControl2D.cbEquation2D, IG.Neural.Forms.NeuralControl2D.cbSelfMade2D, and IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D.
cbTrainingPoints2D_CheckedChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D_CheckedChanged (object sender, EventArgs e) inline private
Enable training points on graph.
References IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D, and IG.Neural.Forms.NeuralControl2D.trainingPointsonGraph.
cbDefaultSurface2D_CheckedChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D_CheckedChanged (object sender, EventArgs e) inline private
Enable surface for default function on graph.
References IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D, and IG.Neural.Forms.NeuralControl2D.defaultSurfaceonGraph.
cbDefaultGreed2D_CheckedChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D_CheckedChanged (object sender, EventArgs e) inline private
Enable greed for default function on graph.
References IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D, and IG.Neural.Forms.NeuralControl2D.defaultGreedonGraph.
cbApproximationSurface2D_CheckedChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D_CheckedChanged (object sender, EventArgs e) inline private
Enable surface for approximation function on graph.
References IG.Neural.Forms.NeuralControl2D.approximationSurfaceonGraph, and IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D.
cbApproximationGreed2D_CheckedChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D_CheckedChanged (object sender, EventArgs e) inline private
Enable greed for approximation function on graph.
References IG.Neural.Forms.NeuralControl2D.approximationGreedonGraph, and IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D.
cbContourDefault2D_CheckedChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.cbContourDefault2D_CheckedChanged (object sender, EventArgs e) inline private
Enable conture for default function on graph.
References IG.Neural.Forms.NeuralControl2D.cbContourDefault2D, and IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph.
cbContourApproximation2D_CheckedChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D_CheckedChanged (object sender, EventArgs e) inline private
Enable conture for approximation function on graph.
References IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D, and IG.Neural.Forms.NeuralControl2D.contureApproximationonGraph.
cbRandomData2D_CheckedChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.cbRandomData2D_CheckedChanged (object sender, EventArgs e) inline private
Enable random training points.
References IG.Neural.Forms.NeuralControl2D.ResetAll2D().
cbScaleTo_CheckedChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.cbScaleTo_CheckedChanged (object sender, EventArgs e) inline private
Enable scaling to range 1.
References IG.Neural.Forms.NeuralControl2D.ResetAll2D().
trackbDefaultGraph2D_Scroll() [5/5]
void IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D_Scroll (object sender, EventArgs e) inline private
Opacity for visualization of default function.
References IG.Neural.Forms.NeuralControl2D.opacityDefaultGraph2D, and IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D.
trackbApproxGraph2D_Scroll() [5/5]
void IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D_Scroll (object sender, EventArgs e) inline private
Opacity for visualization of approximation function.
References IG.Neural.Forms.NeuralControl2D.opacityApproxGraph2D, and IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D.
trackbContourGraph2D_Scroll() [5/5]
void IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D_Scroll (object sender, EventArgs e) inline private
Opacity for visualization of contures.
References IG.Neural.Forms.NeuralControl2D.opacityContourGraph2D, and IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D.
cbEquation2D_SelectedIndexChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.cbEquation2D_SelectedIndexChanged (object sender, EventArgs e) inline private
Select equation from the list.
References IG.Neural.Forms.NeuralControl2D.cbEquation2D, IG.Neural.Forms.NeuralControl2D.equation2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
tbSelfMadeEquation2D_TextChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D_TextChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.equation2D, and IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D.
numSamplesX2D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.numSamplesX2D_ValueChanged (object sender, EventArgs e) inline private
Number of training samples on X axe.
References IG.Neural.Forms.NeuralControl2D.numSamplesX2D, IG.Neural.Forms.NeuralControl2D.ResetAll2D(), and IG.Neural.Forms.NeuralControl2D.samplesX2D.
numSamplesY2D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.numSamplesY2D_ValueChanged (object sender, EventArgs e) inline private
Number of training samples on Y axe.
References IG.Neural.Forms.NeuralControl2D.numSamplesY2D, IG.Neural.Forms.NeuralControl2D.ResetAll2D(), and IG.Neural.Forms.NeuralControl2D.samplesY2D.
numLowXLimit2D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.numLowXLimit2D_ValueChanged (object sender, EventArgs e) inline private
Lower limit for x-axes on the graph.
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.lowHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.numLowXLimit2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
numHighXLimit2D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.numHighXLimit2D_ValueChanged (object sender, EventArgs e) inline private
Higher limit for x-axes on the graph.
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.highHorizontalLimit2D, IG.Neural.Forms.NeuralControl2D.numHighXLimit2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
numHighYLimit2D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.numHighYLimit2D_ValueChanged (object sender, EventArgs e) inline private
Higher limit for y-axes on the graph.
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.highVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.numHighYLimit2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
numLowYLimit2D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.numLowYLimit2D_ValueChanged (object sender, EventArgs e) inline private
Lower limit for y-axes on the graph.
References IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.lowVerticalLimit2D, IG.Neural.Forms.NeuralControl2D.numLowYLimit2D, and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
numMaxEpoch2D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D_ValueChanged (object sender, EventArgs e) inline private
Maximum number of epochs.
References IG.Neural.Forms.NeuralControl2D.maxEpoch2D, IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
numEpochBundle2D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.numEpochBundle2D_ValueChanged (object sender, EventArgs e) inline private
Number of epochs in bundle.
References IG.Neural.Forms.NeuralControl2D.epochInBundle2D, and IG.Neural.Forms.NeuralControl2D.numEpochBundle2D.
numRMS2D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.numRMS2D_ValueChanged (object sender, EventArgs e) inline private
Rms error limit.
References IG.Neural.Forms.NeuralControl2D.numRMS2D, IG.Neural.Forms.NeuralControl2D.ResetResults2D(), and IG.Neural.Forms.NeuralControl2D.rmsError2D.
numLearningRate2D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.numLearningRate2D_ValueChanged (object sender, EventArgs e) inline private
Learning rate.
References IG.Neural.Forms.NeuralControl2D.learningRate2D, IG.Neural.Forms.NeuralControl2D.numLearningRate2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
numMomentum2D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.numMomentum2D_ValueChanged (object sender, EventArgs e) inline private
Momentum.
References IG.Neural.Forms.NeuralControl2D.momentum2D, IG.Neural.Forms.NeuralControl2D.numMomentum2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
numHiddenNeuron2D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in first hidden layer.
References IG.Neural.Forms.NeuralControl2D.hiddenNeuronL12D, IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
numHiddenNeuronL22D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in second hidden layer.
References IG.Neural.Forms.NeuralControl2D.hiddenNeuronL22D, IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
numInputSafety2D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.numInputSafety2D_ValueChanged (object sender, EventArgs e) inline private
Input safety factor.
References IG.Neural.Forms.NeuralControl2D.inputSafetyFactor2D, IG.Neural.Forms.NeuralControl2D.numInputSafety2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
numOutputSafety2D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralControl2D.numOutputSafety2D_ValueChanged (object sender, EventArgs e) inline private
Output safety factor.
References IG.Neural.Forms.NeuralControl2D.numOutputSafety2D, IG.Neural.Forms.NeuralControl2D.outputSafetyFactor2D, and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
Approximator_BundleCompleted() [4/4]
void IG.Neural.Forms.NeuralControl2D.Approximator_BundleCompleted (object obj, EventArgs args) inline protected
Event handler that is executed when a new bundle of training epochs completes.
Updates progress bar.
References IG.Num.INeuralApproximator.EpochCount, IG.Num.INeuralApproximator.MaxEpochs, IG.Num.INeuralApproximator.OutputLevel, and IG.Neural.Forms.NeuralControl2D.progressBar1.
Aproximator_TrainingCompleted() [4/4]
void IG.Neural.Forms.NeuralControl2D.Aproximator_TrainingCompleted (object obj, EventArgs args) inline protected
Event handler that is executed when a new bundle of training epochs completes.
References IG.Num.INeuralApproximator.EpochCount, IG.Num.INeuralApproximator.MaxEpochs, IG.Num.INeuralApproximator.OutputLevel, and IG.Neural.Forms.NeuralControl2D.progressBar1.
TrainNetwork() [4/4]
INeuralApproximator IG.Neural.Forms.NeuralControl2D.TrainNetwork (SampledDataSet trainingData, SampledDataSet verificationData) inline protected
Performs training of neural network.
Parameters
trainingData Training data.
verificationData Verification data.
Returns
References IG.Neural.Forms.NeuralControl2D.epochInBundle2D, IG.Num.NeuralApproximatorBase.EpochsInBundle, IG.Neural.Forms.NeuralControl2D.hiddenNeuronL12D, IG.Neural.Forms.NeuralControl2D.hiddenNeuronL22D, IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Num.NeuralApproximatorBase.InputBoundsSafetyFactor, IG.Num.SampledDataSet.InputLength, IG.Num.NeuralApproximatorBase.InputLength, IG.Num.NeuralApproximatorBase.InputNeuronsRange, IG.Neural.Forms.NeuralControl2D.inputSafetyFactor2D, IG.Num.NeuralApproximatorBase.LearningRate, IG.Neural.Forms.NeuralControl2D.learningRate2D, IG.Num.SampledDataSet.Length, IG.Num.VectorApproximatorBase.Lock, IG.Neural.Forms.NeuralControl2D.maxEpoch2D, IG.Num.NeuralApproximatorBase.MaxEpochs, IG.Num.NeuralApproximatorBase.Momentum, IG.Neural.Forms.NeuralControl2D.momentum2D, IG.Num.NeuralApproximatorBase.MultipleNetworks, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Num.NeuralApproximatorBase.OutputBoundsSafetyFactor, IG.Num.SampledDataSet.OutputLength, IG.Num.NeuralApproximatorBase.OutputLength, IG.Neural.Forms.NeuralControl2D.OutputLevel, IG.Num.NeuralApproximatorBase.OutputLevel, IG.Num.NeuralApproximatorBase.OutputNeuronsRange, IG.Neural.Forms.NeuralControl2D.outputSafetyFactor2D, IG.Num.IBoundingBox.Reset(), IG.Neural.Forms.NeuralControl2D.rmsError2D, IG.Num.NeuralApproximatorBase.SaveConvergenceRms, IG.Num.NeuralApproximatorBase.SetHiddenLayers(), IG.Num.NeuralApproximatorBase.SetTrainingAndVerificationData(), IG.Num.NeuralApproximatorBase.SigmoidAlphaValue, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.StopWatch1.Time, IG.Num.NeuralApproximatorBase.ToleranceRms, IG.Num.NeuralApproximatorBase.ToString(), IG.Num.NeuralApproximatorBase.TrainingData, IG.Num.NeuralApproximatorBase.TrainNetwork(), and IG.Num.IBoundingBox.UpdateAll().
backgroundWorker2D_DoWork() [5/5]
void IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_DoWork (object sender, DoWorkEventArgs e) inline private
References IG.Num.INeuralApproximator.BreakTraining, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Neural.Forms.NeuralControl2D.stopTraining2D, IG.Neural.Forms.NeuralControl2D.trainingData2D, IG.Neural.Forms.NeuralControl2D.TrainNetwork(), and IG.Neural.Forms.NeuralControl2D.verificationData2D.
backgroundWorker2D_RunWorkerCompleted() [5/5]
void IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.btLoadANN2D, IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D, IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btReset2D, IG.Neural.Forms.NeuralControl2D.btSaveANN2D, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.btStop2D, IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts(), IG.Neural.Forms.NeuralControl2D.ShowPlot(), and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
ShowPlot() [5/5]
void IG.Neural.Forms.NeuralControl2D.ShowPlot () inline protected
Shows the plot.
References IG.Gr3d.VtkPlotter.BoundsScaled, IG.Neural.Forms.NeuralControl2D.cbScaleTo, IG.Neural.Forms.NeuralControl2D.DecorHandler(), IG.Gr3d.VtkPlotter.IsScaled, IG.Neural.Forms.NeuralControl2D.plotter2D, IG.Num.BoundingBoxBase.Reset(), IG.Gr3d.VtkPlotter.ResetCamera(), IG.Neural.Forms.NeuralControl2D.ScaledBounds, IG.Gr3d.VtkPlotter.ShowPlot(), and IG.Num.BoundingBox3d.Update().
ResetTooltipProperties() [2/2]
void IG.Neural.Forms.NeuralControl2D.ResetTooltipProperties () inline
References IG.Neural.Forms.NeuralControl2D.toolTip1, and IG.Neural.Forms.NeuralControl2D.toolTip2.
menuTooltipEnabled_CheckedChanged() [2/2]
void IG.Neural.Forms.NeuralControl2D.menuTooltipEnabled_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.IsToolTipActive, and IG.Neural.Forms.NeuralControl2D.menuTooltipEnabled.
resetToolStripMenuItem_Click() [2/2]
void IG.Neural.Forms.NeuralControl2D.resetToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.ResetTooltipProperties().
menuTooltipBackground_Click() [2/2]
void IG.Neural.Forms.NeuralControl2D.menuTooltipBackground_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.colorDialog1, and IG.Neural.Forms.NeuralControl2D.ToolTipBackground.
menuTooltipForeground_Click() [2/2]
void IG.Neural.Forms.NeuralControl2D.menuTooltipForeground_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.colorDialog1, and IG.Neural.Forms.NeuralControl2D.ToolTipForeground.
menuTooltipDisplayTimeValue_Validated() [2/2]
void IG.Neural.Forms.NeuralControl2D.menuTooltipDisplayTimeValue_Validated (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralControl2D.menuTooltipDisplayTimeValue.
menuTooltipDelayValue_Validated() [2/2]
void IG.Neural.Forms.NeuralControl2D.menuTooltipDelayValue_Validated (object sender, EventArgs e) inline private
Dispose() [5/5]
override void IG.Neural.Forms.NeuralControl2D.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralControl2D.components.
InitializeComponent() [5/5]
void IG.Neural.Forms.NeuralControl2D.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralControl2D.backgroundWorker2D, IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_DoWork(), IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralControl2D.btLoad2D, IG.Neural.Forms.NeuralControl2D.btLoadANN2D, IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D, IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), IG.Neural.Forms.NeuralControl2D.btnShowApprox, IG.Neural.Forms.NeuralControl2D.btnShowApprox_Click(), IG.Neural.Forms.NeuralControl2D.btnShowDefault, IG.Neural.Forms.NeuralControl2D.btnShowDefault_Click(), IG.Neural.Forms.NeuralControl2D.btReset2D, IG.Neural.Forms.NeuralControl2D.btReset2D_Click(), IG.Neural.Forms.NeuralControl2D.btSaveANN2D, IG.Neural.Forms.NeuralControl2D.btStart2D, IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.btStop2D, IG.Neural.Forms.NeuralControl2D.btStop2D_Click(), IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D, IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D, IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D, IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbContourDefault2D, IG.Neural.Forms.NeuralControl2D.cbContourDefault2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D, IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D, IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbEquation2D, IG.Neural.Forms.NeuralControl2D.cbEquation2D_SelectedIndexChanged(), IG.Neural.Forms.NeuralControl2D.cbRandomData2D, IG.Neural.Forms.NeuralControl2D.cbRandomData2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbScaleTo, IG.Neural.Forms.NeuralControl2D.cbScaleTo_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbSelfMade2D, IG.Neural.Forms.NeuralControl2D.cbSelfMade2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D, IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.colorDialog1, IG.Neural.Forms.NeuralControl2D.components, IG.Neural.Forms.NeuralControl2D.contextMenuStrip1, IG.Neural.Forms.NeuralControl2D.errorConvergence2D, IG.Neural.Forms.NeuralControl2D.groupBox1, IG.Neural.Forms.NeuralControl2D.groupBox2, IG.Neural.Forms.NeuralControl2D.groupBox3, IG.Neural.Forms.NeuralControl2D.groupBox4, IG.Neural.Forms.NeuralControl2D.groupBox8, IG.Neural.Forms.NeuralControl2D.label10, IG.Neural.Forms.NeuralControl2D.label14, IG.Neural.Forms.NeuralControl2D.label17, IG.Neural.Forms.NeuralControl2D.label18, IG.Neural.Forms.NeuralControl2D.label20, IG.Neural.Forms.NeuralControl2D.label21, IG.Neural.Forms.NeuralControl2D.label22, IG.Neural.Forms.NeuralControl2D.label23, IG.Neural.Forms.NeuralControl2D.label24, IG.Neural.Forms.NeuralControl2D.label25, IG.Neural.Forms.NeuralControl2D.label26, IG.Neural.Forms.NeuralControl2D.label27, IG.Neural.Forms.NeuralControl2D.label28, IG.Neural.Forms.NeuralControl2D.label29, IG.Neural.Forms.NeuralControl2D.label3, IG.Neural.Forms.NeuralControl2D.label30, IG.Neural.Forms.NeuralControl2D.label31, IG.Neural.Forms.NeuralControl2D.label32, IG.Neural.Forms.NeuralControl2D.label33, IG.Neural.Forms.NeuralControl2D.label34, IG.Neural.Forms.NeuralControl2D.label35, IG.Neural.Forms.NeuralControl2D.label36, IG.Neural.Forms.NeuralControl2D.label37, IG.Neural.Forms.NeuralControl2D.menuDelayTime, IG.Neural.Forms.NeuralControl2D.menuDisplayTime, IG.Neural.Forms.NeuralControl2D.menuTooltipBackground, IG.Neural.Forms.NeuralControl2D.menuTooltipColor, IG.Neural.Forms.NeuralControl2D.menuTooltipDelayValue, IG.Neural.Forms.NeuralControl2D.menuTooltipDisplayTimeValue, IG.Neural.Forms.NeuralControl2D.menuTooltipEnabled, IG.Neural.Forms.NeuralControl2D.menuTooltipForeground, IG.Neural.Forms.NeuralControl2D.menuTooltips, IG.Neural.Forms.NeuralControl2D.numEpochBundle2D, IG.Neural.Forms.NeuralControl2D.numEpochBundle2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D, IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D, IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHighXLimit2D, IG.Neural.Forms.NeuralControl2D.numHighXLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numHighYLimit2D, IG.Neural.Forms.NeuralControl2D.numHighYLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numInputSafety2D, IG.Neural.Forms.NeuralControl2D.numInputSafety2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numLearningRate2D, IG.Neural.Forms.NeuralControl2D.numLearningRate2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numLowXLimit2D, IG.Neural.Forms.NeuralControl2D.numLowXLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numLowYLimit2D, IG.Neural.Forms.NeuralControl2D.numLowYLimit2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D, IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numMomentum2D, IG.Neural.Forms.NeuralControl2D.numMomentum2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numOutputSafety2D, IG.Neural.Forms.NeuralControl2D.numOutputSafety2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numRMS2D, IG.Neural.Forms.NeuralControl2D.numRMS2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numSamplesX2D, IG.Neural.Forms.NeuralControl2D.numSamplesX2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.numSamplesY2D, IG.Neural.Forms.NeuralControl2D.numSamplesY2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.progressBar1, IG.Neural.Forms.NeuralControl2D.rbMaxTrainError2D, IG.Neural.Forms.NeuralControl2D.rbMaxTrainError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.rbMaxVerError2D, IG.Neural.Forms.NeuralControl2D.rbMaxVerError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.rbRmsTrainError2D, IG.Neural.Forms.NeuralControl2D.rbRmsTrainError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.rbRmsVerError2D, IG.Neural.Forms.NeuralControl2D.rbRmsVerError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.resetToolStripMenuItem, IG.Neural.Forms.NeuralControl2D.tbEquationError2D, IG.Neural.Forms.NeuralControl2D.tbMaxTrainError2D, IG.Neural.Forms.NeuralControl2D.tbMaxVerError2D, IG.Neural.Forms.NeuralControl2D.tbRmsTrainError2D, IG.Neural.Forms.NeuralControl2D.tbRmsVerError2D, IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D, IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D_TextChanged(), IG.Neural.Forms.NeuralControl2D.toolTip1, IG.Neural.Forms.NeuralControl2D.toolTip2, IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D, IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D_Scroll(), IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D, IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D_Scroll(), IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D, and IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D_Scroll().
Member Data Documentation
_outputLevel
int IG.Neural.Forms.NeuralControl2D._outputLevel = 0 private
pane2DError
GraphPane IG.Neural.Forms.NeuralControl2D.pane2DError private
Error graph.
Referenced by IG.Neural.Forms.NeuralControl2D.LoadForm(), and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
_neuralApproximator
INeuralApproximator IG.Neural.Forms.NeuralControl2D._neuralApproximator protected
trainingData2D
SampledDataSet IG.Neural.Forms.NeuralControl2D.trainingData2D = null private
Training data set.
Referenced by IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_DoWork(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D(), and IG.Neural.Forms.NeuralControl2D.InitializeTrainingData2D().
verificationData2D
SampledDataSet IG.Neural.Forms.NeuralControl2D.verificationData2D = null private
Verification data set.
Referenced by IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_DoWork(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), and IG.Neural.Forms.NeuralControl2D.InitializeVerificationData2D().
defaultFunctionData2D
SampledDataSet IG.Neural.Forms.NeuralControl2D.defaultFunctionData2D = null private
Default data set.
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeDefaultData2D().
hiddenNeuronL12D
int IG.Neural.Forms.NeuralControl2D.hiddenNeuronL12D = 5 private
Referenced by IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D_ValueChanged(), and IG.Neural.Forms.NeuralControl2D.TrainNetwork().
hiddenNeuronL22D
int IG.Neural.Forms.NeuralControl2D.hiddenNeuronL22D = 0 private
Referenced by IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D_ValueChanged(), and IG.Neural.Forms.NeuralControl2D.TrainNetwork().
maxEpoch2D
int IG.Neural.Forms.NeuralControl2D.maxEpoch2D = 5000 private
Referenced by IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D_ValueChanged(), and IG.Neural.Forms.NeuralControl2D.TrainNetwork().
epochInBundle2D
int IG.Neural.Forms.NeuralControl2D.epochInBundle2D = 500 private
Referenced by IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.numEpochBundle2D_ValueChanged(), IG.Neural.Forms.NeuralControl2D.TrainNetwork(), and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
rmsError2D
double IG.Neural.Forms.NeuralControl2D.rmsError2D = 0.001 private
Referenced by IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.numRMS2D_ValueChanged(), and IG.Neural.Forms.NeuralControl2D.TrainNetwork().
learningRate2D
double IG.Neural.Forms.NeuralControl2D.learningRate2D = 0.3 private
Referenced by IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.numLearningRate2D_ValueChanged(), and IG.Neural.Forms.NeuralControl2D.TrainNetwork().
momentum2D
double IG.Neural.Forms.NeuralControl2D.momentum2D = 0.6 private
Referenced by IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.numMomentum2D_ValueChanged(), and IG.Neural.Forms.NeuralControl2D.TrainNetwork().
samplesX2D
int IG.Neural.Forms.NeuralControl2D.samplesX2D = 5 private
Referenced by IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D(), and IG.Neural.Forms.NeuralControl2D.numSamplesX2D_ValueChanged().
samplesY2D
int IG.Neural.Forms.NeuralControl2D.samplesY2D = 5 private
Referenced by IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D(), and IG.Neural.Forms.NeuralControl2D.numSamplesY2D_ValueChanged().
lowHorizontalLimit2D
double IG.Neural.Forms.NeuralControl2D.lowHorizontalLimit2D = -1.0 private
Referenced by IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.NeuralControl2D(), and IG.Neural.Forms.NeuralControl2D.numLowXLimit2D_ValueChanged().
highHorizontalLimit2D
double IG.Neural.Forms.NeuralControl2D.highHorizontalLimit2D = 1.0 private
Referenced by IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.NeuralControl2D(), and IG.Neural.Forms.NeuralControl2D.numHighXLimit2D_ValueChanged().
lowVerticalLimit2D
double IG.Neural.Forms.NeuralControl2D.lowVerticalLimit2D = -1.0 private
Referenced by IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.NeuralControl2D(), and IG.Neural.Forms.NeuralControl2D.numLowYLimit2D_ValueChanged().
highVerticalLimit2D
double IG.Neural.Forms.NeuralControl2D.highVerticalLimit2D = 1.0 private
Referenced by IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.NeuralControl2D(), and IG.Neural.Forms.NeuralControl2D.numHighYLimit2D_ValueChanged().
lowVerificationHorizontalLimit2D
double IG.Neural.Forms.NeuralControl2D.lowVerificationHorizontalLimit2D = -5.0 private
highVerificationHorizontalLimit2D
double IG.Neural.Forms.NeuralControl2D.highVerificationHorizontalLimit2D = 5.0 private
inputSafetyFactor2D
double IG.Neural.Forms.NeuralControl2D.inputSafetyFactor2D = 1.3 private
Referenced by IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.numInputSafety2D_ValueChanged(), and IG.Neural.Forms.NeuralControl2D.TrainNetwork().
outputSafetyFactor2D
double IG.Neural.Forms.NeuralControl2D.outputSafetyFactor2D = 1.3 private
Referenced by IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.numOutputSafety2D_ValueChanged(), and IG.Neural.Forms.NeuralControl2D.TrainNetwork().
equation2D
string IG.Neural.Forms.NeuralControl2D.equation2D = "x*x + y*y" private
Referenced by IG.Neural.Forms.NeuralControl2D.cbEquation2D_SelectedIndexChanged(), IG.Neural.Forms.NeuralControl2D.GenerateDefaultPoints2D(), IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D(), and IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D_TextChanged().
variableNames2D
string [] IG.Neural.Forms.NeuralControl2D.variableNames2D = { "x", "y" } private
Referenced by IG.Neural.Forms.NeuralControl2D.GenerateDefaultPoints2D(), and IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D().
maxTrainErrorEnabled2D
bool IG.Neural.Forms.NeuralControl2D.maxTrainErrorEnabled2D = true private
Referenced by IG.Neural.Forms.NeuralControl2D.rbMaxTrainError2D_CheckedChanged(), and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
rmsTrainErrorEnabled2D
bool IG.Neural.Forms.NeuralControl2D.rmsTrainErrorEnabled2D = false private
Referenced by IG.Neural.Forms.NeuralControl2D.rbRmsTrainError2D_CheckedChanged(), and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
maxVerErrorEnabled2D
bool IG.Neural.Forms.NeuralControl2D.maxVerErrorEnabled2D = false private
Referenced by IG.Neural.Forms.NeuralControl2D.rbMaxVerError2D_CheckedChanged(), and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
rmsVerErrorEnabled2D
bool IG.Neural.Forms.NeuralControl2D.rmsVerErrorEnabled2D = false private
Referenced by IG.Neural.Forms.NeuralControl2D.rbRmsVerError2D_CheckedChanged(), and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
defaultSurfaceonGraph
bool IG.Neural.Forms.NeuralControl2D.defaultSurfaceonGraph = false private
Referenced by IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D_CheckedChanged(), and IG.Neural.Forms.NeuralControl2D.DefaultGraph2D().
defaultGreedonGraph
bool IG.Neural.Forms.NeuralControl2D.defaultGreedonGraph = true private
Referenced by IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D_CheckedChanged(), and IG.Neural.Forms.NeuralControl2D.DefaultGraph2D().
trainingPointsonGraph
bool IG.Neural.Forms.NeuralControl2D.trainingPointsonGraph = true private
Referenced by IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D_CheckedChanged(), and IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph().
approximationSurfaceonGraph
bool IG.Neural.Forms.NeuralControl2D.approximationSurfaceonGraph = true private
Referenced by IG.Neural.Forms.NeuralControl2D.ApproximationGraph(), and IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D_CheckedChanged().
approximationGreedonGraph
bool IG.Neural.Forms.NeuralControl2D.approximationGreedonGraph = false private
Referenced by IG.Neural.Forms.NeuralControl2D.ApproximationGraph(), and IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D_CheckedChanged().
contureDefaultonGraph
bool IG.Neural.Forms.NeuralControl2D.contureDefaultonGraph = false private
Referenced by IG.Neural.Forms.NeuralControl2D.cbContourDefault2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.DefaultGraph2D(), IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts(), and IG.Neural.Forms.NeuralControl2D.PrepareDefaultPlotsWithoutShow().
contureApproximationonGraph
bool IG.Neural.Forms.NeuralControl2D.contureApproximationonGraph = false private
Referenced by IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.DefaultGraph2D(), and IG.Neural.Forms.NeuralControl2D.PrepareApproximationPolts().
stopTraining2D
bool IG.Neural.Forms.NeuralControl2D.stopTraining2D = false private
Referenced by IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_DoWork(), and IG.Neural.Forms.NeuralControl2D.btStop2D_Click().
stopTraining1D
bool IG.Neural.Forms.NeuralControl2D.stopTraining1D = false private
opacityDefaultGraph2D
double IG.Neural.Forms.NeuralControl2D.opacityDefaultGraph2D = 0.5 private
Referenced by IG.Neural.Forms.NeuralControl2D.DefaultGraph2D(), and IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D_Scroll().
opacityApproxGraph2D
double IG.Neural.Forms.NeuralControl2D.opacityApproxGraph2D = 0.7 private
Referenced by IG.Neural.Forms.NeuralControl2D.ApproximationGraph(), and IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D_Scroll().
opacityContourGraph2D
double IG.Neural.Forms.NeuralControl2D.opacityContourGraph2D = 1.0 private
Referenced by IG.Neural.Forms.NeuralControl2D.ApproximationContourGraph(), IG.Neural.Forms.NeuralControl2D.DefaultContourGraph(), and IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D_Scroll().
numAllXPoints2D
int IG.Neural.Forms.NeuralControl2D.numAllXPoints2D = 100 private
Referenced by IG.Neural.Forms.NeuralControl2D.ApproximationContourGraph(), IG.Neural.Forms.NeuralControl2D.ApproximationGraph(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.DefaultContourGraph(), and IG.Neural.Forms.NeuralControl2D.GenerateDefaultPoints2D().
numAllYPoints2D
int IG.Neural.Forms.NeuralControl2D.numAllYPoints2D = 100 private
Referenced by IG.Neural.Forms.NeuralControl2D.ApproximationContourGraph(), IG.Neural.Forms.NeuralControl2D.ApproximationGraph(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.DefaultContourGraph(), and IG.Neural.Forms.NeuralControl2D.GenerateDefaultPoints2D().
errorConvergenceFunction2D
LineItem IG.Neural.Forms.NeuralControl2D.errorConvergenceFunction2D private
Referenced by IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
plotter2D
VtkPlotter IG.Neural.Forms.NeuralControl2D.plotter2D private
Plotter.
Referenced by IG.Neural.Forms.NeuralControl2D.ApproximationContourGraph(), IG.Neural.Forms.NeuralControl2D.ApproximationGraph(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.DecorHandler(), IG.Neural.Forms.NeuralControl2D.DefaultContourGraph(), IG.Neural.Forms.NeuralControl2D.DefaultGraph2D(), IG.Neural.Forms.NeuralControl2D.PreparePlotter2D(), IG.Neural.Forms.NeuralControl2D.SclarBar2D(), IG.Neural.Forms.NeuralControl2D.ShowPlot(), and IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph().
iFunctionDefault2D
Func2dFromScalarFunction IG.Neural.Forms.NeuralControl2D.iFunctionDefault2D private
Scalar function that is approximated.
Referenced by IG.Neural.Forms.NeuralControl2D.ApproximationGraph(), IG.Neural.Forms.NeuralControl2D.DefaultContourGraph(), and IG.Neural.Forms.NeuralControl2D.GenerateDefaultPoints2D().
scalarFunctionDefault2D
IScalarFunction IG.Neural.Forms.NeuralControl2D.scalarFunctionDefault2D private
Scalar function that is approximated.
Referenced by IG.Neural.Forms.NeuralControl2D.GenerateDefaultPoints2D().
Default2DMesh
StructuredMesh2d3d IG.Neural.Forms.NeuralControl2D.Default2DMesh private
Maeh of default points used for plotting.
Referenced by IG.Neural.Forms.NeuralControl2D.DefaultGraph2D(), and IG.Neural.Forms.NeuralControl2D.GenerateDefaultPoints2D().
plotDefault2D
VtkSurfacePlot IG.Neural.Forms.NeuralControl2D.plotDefault2D private
Plot from default points.
Referenced by IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.DefaultGraph2D(), and IG.Neural.Forms.NeuralControl2D.RemoveDefaultActors().
plotApproximationConture2D
VtkContourPlot IG.Neural.Forms.NeuralControl2D.plotApproximationConture2D private
Conture Plot from approximated points.
Referenced by IG.Neural.Forms.NeuralControl2D.ApproximationContourGraph(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.DefaultGraph2D(), IG.Neural.Forms.NeuralControl2D.RemoveApprovimationContureActors(), and IG.Neural.Forms.NeuralControl2D.RemoveApproximationContureActors().
scalarFunctionTraining2D
IScalarFunction IG.Neural.Forms.NeuralControl2D.scalarFunctionTraining2D private
Scalar function that is approximated.
Referenced by IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D().
TrainingPointsMesh2D
StructuredMesh2d3d IG.Neural.Forms.NeuralControl2D.TrainingPointsMesh2D private
Maeh of training points used for plotting.
Referenced by IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D(), and IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph().
plotTrainingPoints2D
VtkSurfacePlot IG.Neural.Forms.NeuralControl2D.plotTrainingPoints2D private
Plot from training points.
Referenced by IG.Neural.Forms.NeuralControl2D.RemoveTrainingPointsActors(), and IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph().
iFunctionApproximator2D
Func2dFromApproximator IG.Neural.Forms.NeuralControl2D.iFunctionApproximator2D private
Scalar function that is approximated.
Referenced by IG.Neural.Forms.NeuralControl2D.ApproximationContourGraph(), and IG.Neural.Forms.NeuralControl2D.ApproximationGraph().
iFunctionDifference2D
ExampleValueFunctionDiff3D IG.Neural.Forms.NeuralControl2D.iFunctionDifference2D private
Scalar function that is a difference default and approximated function.
Referenced by IG.Neural.Forms.NeuralControl2D.ApproximationGraph().
plotApproximation2D
VtkSurfacePlot IG.Neural.Forms.NeuralControl2D.plotApproximation2D private
Plot from approximated points.
Referenced by IG.Neural.Forms.NeuralControl2D.ApproximationGraph(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.RemoveApprovimationActors(), and IG.Neural.Forms.NeuralControl2D.RemoveApproximationActors().
plotDefaultConture2D
VtkContourPlot IG.Neural.Forms.NeuralControl2D.plotDefaultConture2D private
Conture Plot from default points.
Referenced by IG.Neural.Forms.NeuralControl2D.DefaultContourGraph(), and IG.Neural.Forms.NeuralControl2D.RemoveDefaultContureActors().
paramBounds2D
BoundingBox2d IG.Neural.Forms.NeuralControl2D.paramBounds2D private
Bounding box for function limits. </summary
Referenced by IG.Neural.Forms.NeuralControl2D.ApproximationContourGraph(), IG.Neural.Forms.NeuralControl2D.ApproximationGraph(), IG.Neural.Forms.NeuralControl2D.Bounds2D(), IG.Neural.Forms.NeuralControl2D.DefaultContourGraph(), IG.Neural.Forms.NeuralControl2D.DefaultGraph2D(), IG.Neural.Forms.NeuralControl2D.GenerateDefaultPoints2D(), IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D(), and IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph().
_breakTraining
bool IG.Neural.Forms.NeuralControl2D._breakTraining = false private
_scaledBounds
BoundingBox3d IG.Neural.Forms.NeuralControl2D._scaledBounds private
_toolTipBackground
Color IG.Neural.Forms.NeuralControl2D._toolTipBackground = Color.LightBlue private
_toolTipForeground
Color IG.Neural.Forms.NeuralControl2D._toolTipForeground = Color.Black private
_isTooltipActive
bool IG.Neural.Forms.NeuralControl2D._isTooltipActive = true private
_displayTimeMs
int IG.Neural.Forms.NeuralControl2D._displayTimeMs = 2000 protected
_delayTimeMs
int IG.Neural.Forms.NeuralControl2D._delayTimeMs = 2000 protected
components
System ComponentModel IContainer IG.Neural.Forms.NeuralControl2D.components = null private
Required designer variable.
Referenced by IG.Neural.Forms.NeuralControl2D.Dispose(), and IG.Neural.Forms.NeuralControl2D.InitializeComponent().
trackbContourGraph2D
System Windows Forms TrackBar IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.trackbContourGraph2D_Scroll().
label37
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label37 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
cbContourDefault2D
System Windows Forms CheckBox IG.Neural.Forms.NeuralControl2D.cbContourDefault2D private
Referenced by IG.Neural.Forms.NeuralControl2D.cbContourDefault2D_CheckedChanged(), and IG.Neural.Forms.NeuralControl2D.InitializeComponent().
cbContourApproximation2D
System Windows Forms CheckBox IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D private
Referenced by IG.Neural.Forms.NeuralControl2D.cbContourApproximation2D_CheckedChanged(), and IG.Neural.Forms.NeuralControl2D.InitializeComponent().
cbTrainingPoints2D
System Windows Forms CheckBox IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D private
Referenced by IG.Neural.Forms.NeuralControl2D.cbTrainingPoints2D_CheckedChanged(), and IG.Neural.Forms.NeuralControl2D.InitializeComponent().
label36
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label36 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
cbApproximationGreed2D
System Windows Forms CheckBox IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D private
Referenced by IG.Neural.Forms.NeuralControl2D.cbApproximationGreed2D_CheckedChanged(), and IG.Neural.Forms.NeuralControl2D.InitializeComponent().
cbApproximationSurface2D
System Windows Forms CheckBox IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D private
Referenced by IG.Neural.Forms.NeuralControl2D.cbApproximationSurface2D_CheckedChanged(), and IG.Neural.Forms.NeuralControl2D.InitializeComponent().
label34
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label34 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
trackbApproxGraph2D
System Windows Forms TrackBar IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.trackbApproxGraph2D_Scroll().
cbDefaultGreed2D
System Windows Forms CheckBox IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D private
Referenced by IG.Neural.Forms.NeuralControl2D.cbDefaultGreed2D_CheckedChanged(), and IG.Neural.Forms.NeuralControl2D.InitializeComponent().
trackbDefaultGraph2D
System Windows Forms TrackBar IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.trackbDefaultGraph2D_Scroll().
cbDefaultSurface2D
System Windows Forms CheckBox IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D private
Referenced by IG.Neural.Forms.NeuralControl2D.cbDefaultSurface2D_CheckedChanged(), and IG.Neural.Forms.NeuralControl2D.InitializeComponent().
label35
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label35 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numHighXLimit2D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralControl2D.numHighXLimit2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), IG.Neural.Forms.NeuralControl2D.NeuralControl2D(), and IG.Neural.Forms.NeuralControl2D.numHighXLimit2D_ValueChanged().
label30
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label30 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numHighYLimit2D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralControl2D.numHighYLimit2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), IG.Neural.Forms.NeuralControl2D.NeuralControl2D(), and IG.Neural.Forms.NeuralControl2D.numHighYLimit2D_ValueChanged().
numLowYLimit2D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralControl2D.numLowYLimit2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), IG.Neural.Forms.NeuralControl2D.NeuralControl2D(), and IG.Neural.Forms.NeuralControl2D.numLowYLimit2D_ValueChanged().
numLowXLimit2D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralControl2D.numLowXLimit2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), IG.Neural.Forms.NeuralControl2D.NeuralControl2D(), and IG.Neural.Forms.NeuralControl2D.numLowXLimit2D_ValueChanged().
label31
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label31 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
label32
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label32 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
label33
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label33 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
tbEquationError2D
System Windows Forms TextBox IG.Neural.Forms.NeuralControl2D.tbEquationError2D private
Referenced by IG.Neural.Forms.NeuralControl2D.GenerateDefaultPoints2D(), and IG.Neural.Forms.NeuralControl2D.InitializeComponent().
rbRmsTrainError2D
System Windows Forms RadioButton IG.Neural.Forms.NeuralControl2D.rbRmsTrainError2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
rbMaxTrainError2D
System Windows Forms RadioButton IG.Neural.Forms.NeuralControl2D.rbMaxTrainError2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
rbRmsVerError2D
System Windows Forms RadioButton IG.Neural.Forms.NeuralControl2D.rbRmsVerError2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
rbMaxVerError2D
System Windows Forms RadioButton IG.Neural.Forms.NeuralControl2D.rbMaxVerError2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
tbRmsTrainError2D
System Windows Forms TextBox IG.Neural.Forms.NeuralControl2D.tbRmsTrainError2D private
Referenced by IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
label26
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label26 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
label27
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label27 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
tbMaxTrainError2D
System Windows Forms TextBox IG.Neural.Forms.NeuralControl2D.tbMaxTrainError2D private
Referenced by IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
tbRmsVerError2D
System Windows Forms TextBox IG.Neural.Forms.NeuralControl2D.tbRmsVerError2D private
Referenced by IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
tbMaxVerError2D
System Windows Forms TextBox IG.Neural.Forms.NeuralControl2D.tbMaxVerError2D private
Referenced by IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
label28
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label28 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
label29
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label29 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
errorConvergence2D
ZedGraph ZedGraphControl IG.Neural.Forms.NeuralControl2D.errorConvergence2D private
Referenced by IG.Neural.Forms.NeuralControl2D.ClearErrorGraph2D(), IG.Neural.Forms.NeuralControl2D.InitializeComponent(), IG.Neural.Forms.NeuralControl2D.LoadForm(), and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
numHiddenNeuronL22D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.numHiddenNeuronL22D_ValueChanged().
numHiddenNeuron2D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.numHiddenNeuron2D_ValueChanged().
btLoadANN2D
System Windows Forms Button IG.Neural.Forms.NeuralControl2D.btLoadANN2D private
Referenced by IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), and IG.Neural.Forms.NeuralControl2D.InitializeComponent().
btSaveANN2D
System Windows Forms Button IG.Neural.Forms.NeuralControl2D.btSaveANN2D private
Referenced by IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), and IG.Neural.Forms.NeuralControl2D.InitializeComponent().
btReset2D
System Windows Forms Button IG.Neural.Forms.NeuralControl2D.btReset2D private
Referenced by IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), and IG.Neural.Forms.NeuralControl2D.InitializeComponent().
btStart2D
System Windows Forms Button IG.Neural.Forms.NeuralControl2D.btStart2D private
Referenced by IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
numOutputSafety2D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralControl2D.numOutputSafety2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.numOutputSafety2D_ValueChanged().
label17
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label17 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numInputSafety2D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralControl2D.numInputSafety2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.numInputSafety2D_ValueChanged().
label18
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label18 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
label20
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label20 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numMomentum2D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralControl2D.numMomentum2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.numMomentum2D_ValueChanged().
numLearningRate2D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralControl2D.numLearningRate2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.numLearningRate2D_ValueChanged().
numRMS2D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralControl2D.numRMS2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.numRMS2D_ValueChanged().
numEpochBundle2D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralControl2D.numEpochBundle2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.numEpochBundle2D_ValueChanged().
numMaxEpoch2D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.numMaxEpoch2D_ValueChanged().
label21
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label21 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
label22
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label22 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
label23
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label23 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
label24
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label24 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
label25
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label25 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
cbRandomData2D
System Windows Forms CheckBox IG.Neural.Forms.NeuralControl2D.cbRandomData2D private
Referenced by IG.Neural.Forms.NeuralControl2D.GenerateTrainingPoints2D(), and IG.Neural.Forms.NeuralControl2D.InitializeComponent().
btnGenerateOptData2D
System Windows Forms Button IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D private
Referenced by IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), and IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numSamplesX2D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralControl2D.numSamplesX2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.numSamplesX2D_ValueChanged().
label14
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label14 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
cbEquation2D
System Windows Forms ComboBox IG.Neural.Forms.NeuralControl2D.cbEquation2D private
Referenced by IG.Neural.Forms.NeuralControl2D.cbEquation2D_SelectedIndexChanged(), IG.Neural.Forms.NeuralControl2D.cbSelfMade2D_CheckedChanged(), and IG.Neural.Forms.NeuralControl2D.InitializeComponent().
tbSelfMadeEquation2D
System Windows Forms TextBox IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D private
Referenced by IG.Neural.Forms.NeuralControl2D.cbSelfMade2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.tbSelfMadeEquation2D_TextChanged().
label3
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label3 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
cbSelfMade2D
System Windows Forms CheckBox IG.Neural.Forms.NeuralControl2D.cbSelfMade2D private
Referenced by IG.Neural.Forms.NeuralControl2D.cbSelfMade2D_CheckedChanged(), and IG.Neural.Forms.NeuralControl2D.InitializeComponent().
btLoad2D
System Windows Forms Button IG.Neural.Forms.NeuralControl2D.btLoad2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
groupBox3
System Windows Forms GroupBox IG.Neural.Forms.NeuralControl2D.groupBox3 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
groupBox1
System Windows Forms GroupBox IG.Neural.Forms.NeuralControl2D.groupBox1 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
groupBox2
System Windows Forms GroupBox IG.Neural.Forms.NeuralControl2D.groupBox2 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
numSamplesY2D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralControl2D.numSamplesY2D private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.numSamplesY2D_ValueChanged().
label10
System Windows Forms Label IG.Neural.Forms.NeuralControl2D.label10 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
groupBox4
System Windows Forms GroupBox IG.Neural.Forms.NeuralControl2D.groupBox4 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
btStop2D
System Windows Forms Button IG.Neural.Forms.NeuralControl2D.btStop2D private
Referenced by IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), and IG.Neural.Forms.NeuralControl2D.InitializeComponent().
groupBox8
System Windows Forms GroupBox IG.Neural.Forms.NeuralControl2D.groupBox8 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
backgroundWorker2D
System ComponentModel BackgroundWorker IG.Neural.Forms.NeuralControl2D.backgroundWorker2D
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.TrainNetworkThread2D().
cbScaleTo
System Windows Forms CheckBox IG.Neural.Forms.NeuralControl2D.cbScaleTo private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.ShowPlot().
btnShowDefault
System Windows Forms Button IG.Neural.Forms.NeuralControl2D.btnShowDefault private
Referenced by IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.btStop2D_Click(), IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.ResetAll2D().
btnShowApprox
System Windows Forms Button IG.Neural.Forms.NeuralControl2D.btnShowApprox private
Referenced by IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.InitializeComponent(), IG.Neural.Forms.NeuralControl2D.ResetAll2D(), and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
progressBar1
System Windows Forms ProgressBar IG.Neural.Forms.NeuralControl2D.progressBar1 private
Referenced by IG.Neural.Forms.NeuralControl2D.Approximator_BundleCompleted(), IG.Neural.Forms.NeuralControl2D.Aproximator_TrainingCompleted(), IG.Neural.Forms.NeuralControl2D.btnGenerateOptData2D_Click(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.InitializeComponent(), IG.Neural.Forms.NeuralControl2D.ResetAll2D(), and IG.Neural.Forms.NeuralControl2D.ResetResults2D().
toolTip1
System Windows Forms ToolTip IG.Neural.Forms.NeuralControl2D.toolTip1 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), IG.Neural.Forms.NeuralControl2D.NeuralControl2D(), and IG.Neural.Forms.NeuralControl2D.ResetTooltipProperties().
contextMenuStrip1
System Windows Forms ContextMenuStrip IG.Neural.Forms.NeuralControl2D.contextMenuStrip1 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
menuTooltips
System Windows Forms ToolStripMenuItem IG.Neural.Forms.NeuralControl2D.menuTooltips private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
menuTooltipEnabled
System Windows Forms ToolStripMenuItem IG.Neural.Forms.NeuralControl2D.menuTooltipEnabled private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.menuTooltipEnabled_CheckedChanged().
menuTooltipColor
System Windows Forms ToolStripMenuItem IG.Neural.Forms.NeuralControl2D.menuTooltipColor private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.NeuralControl2D().
menuTooltipBackground
System Windows Forms ToolStripMenuItem IG.Neural.Forms.NeuralControl2D.menuTooltipBackground private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
menuTooltipForeground
System Windows Forms ToolStripMenuItem IG.Neural.Forms.NeuralControl2D.menuTooltipForeground private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
colorDialog1
System Windows Forms ColorDialog IG.Neural.Forms.NeuralControl2D.colorDialog1 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), IG.Neural.Forms.NeuralControl2D.menuTooltipBackground_Click(), and IG.Neural.Forms.NeuralControl2D.menuTooltipForeground_Click().
toolTip2
System Windows Forms ToolTip IG.Neural.Forms.NeuralControl2D.toolTip2 private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.ResetTooltipProperties().
resetToolStripMenuItem
System Windows Forms ToolStripMenuItem IG.Neural.Forms.NeuralControl2D.resetToolStripMenuItem private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
menuDelayTime
System Windows Forms ToolStripMenuItem IG.Neural.Forms.NeuralControl2D.menuDelayTime private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
menuDisplayTime
System Windows Forms ToolStripMenuItem IG.Neural.Forms.NeuralControl2D.menuDisplayTime private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent().
menuTooltipDelayValue
System Windows Forms ToolStripTextBox IG.Neural.Forms.NeuralControl2D.menuTooltipDelayValue private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), and IG.Neural.Forms.NeuralControl2D.NeuralControl2D().
menuTooltipDisplayTimeValue
System Windows Forms ToolStripTextBox IG.Neural.Forms.NeuralControl2D.menuTooltipDisplayTimeValue private
Referenced by IG.Neural.Forms.NeuralControl2D.InitializeComponent(), IG.Neural.Forms.NeuralControl2D.menuTooltipDisplayTimeValue_Validated(), and IG.Neural.Forms.NeuralControl2D.NeuralControl2D().
network2D
NeuralNetworks IG.Neural.Forms.NeuralControl2D.network2D private
ANN.
Referenced by IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_DoWork(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), and IG.Neural.Forms.NeuralControl2D.btStop2D_Click().
Property Documentation
OutputLevel
int IG.Neural.Forms.NeuralControl2D.OutputLevel get set
Level of output to console.
Referenced by IG.Neural.Forms.NeuralControl2D.ApproximationContourGraph(), IG.Neural.Forms.NeuralControl2D.ApproximationGraph(), IG.Neural.Forms.NeuralControl2D.DefaultContourGraph(), IG.Neural.Forms.NeuralControl2D.DefaultGraph2D(), IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Neural.Forms.NeuralControl2D.TrainingPointsGraph(), and IG.Neural.Forms.NeuralControl2D.TrainNetwork().
NeuralApproximator
INeuralApproximator IG.Neural.Forms.NeuralControl2D.NeuralApproximator get set
Neural approximator.
Referenced by IG.Neural.Forms.NeuralControl2D.ApproximationGraph(), IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_DoWork(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Forms.NeuralControl2D.btStop2D_Click(), IG.Neural.Forms.NeuralControl2D.InitializeApproximator2D(), IG.Neural.Applications.NeuralApp2D.InitializeComponent(), IG.Neural.Forms.NeuralControl2D.rbMaxTrainError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.rbMaxVerError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.rbRmsTrainError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.rbRmsVerError2D_CheckedChanged(), IG.Neural.Forms.NeuralControl2D.TrainNetwork(), and IG.Neural.Forms.NeuralControl2D.WriteErrors2D().
BreakTraining
bool IG.Neural.Forms.NeuralControl2D.BreakTraining get set
Referenced by IG.Neural.Applications.NeuralApp2D.InitializeComponent().
ScaledBounds
BoundingBox3d IG.Neural.Forms.NeuralControl2D.ScaledBounds get protected
Referenced by IG.Neural.Forms.NeuralControl2D.ShowPlot().
ToolTipBackground
Color IG.Neural.Forms.NeuralControl2D.ToolTipBackground get set
Tooltip's foreground color.
Referenced by IG.Neural.Forms.NeuralControl2D.menuTooltipBackground_Click(), and IG.Neural.Forms.NeuralControl2D.NeuralControl2D().
ToolTipForeground
Color IG.Neural.Forms.NeuralControl2D.ToolTipForeground get set
Tooltip's background color.
Referenced by IG.Neural.Forms.NeuralControl2D.menuTooltipForeground_Click(), and IG.Neural.Forms.NeuralControl2D.NeuralControl2D().
IsToolTipActive
bool IG.Neural.Forms.NeuralControl2D.IsToolTipActive get set
Whether the tooltip is active and is being displayed for controls or not.
Referenced by IG.Neural.Forms.NeuralControl2D.menuTooltipEnabled_CheckedChanged(), and IG.Neural.Forms.NeuralControl2D.NeuralControl2D().
ToolTipDisplayTimeMs
int IG.Neural.Forms.NeuralControl2D.ToolTipDisplayTimeMs get set
Referenced by IG.Neural.Forms.NeuralControl2D.NeuralControl2D().
ToolTipDelayTimeMs
int IG.Neural.Forms.NeuralControl2D.ToolTipDelayTimeMs get set
Referenced by IG.Neural.Forms.NeuralControl2D.NeuralControl2D().
The documentation for this class was generated from the following files:
shelldev/lib/extended/LibNeuralExtForms/FormsExperimental/NeuralForms/NeuralControl2D.cs
shelldev/lib/extended/LibNeuralExtForms/FormsExperimental/NeuralForms/NeuralControl2D.Designer.cs