Doc: IGLib EXTENDED: NUnit.Framework.Internal.TestFixtureTests Class Reference
NUnit.Framework.Internal.TestFixtureTests Class Reference
Tests of the NUnitTestFixture class
Classes
class FixtureIsNotNullForTests
class FixtureNotNullTestAttribute
Public Member Functions
void ConstructFromType ()
void ConstructFromNestedType ()
void ConstructFromDoublyNestedType ()
void ConstructFromTypeWithoutTestFixtureAttributeContainingTest ()
void ConstructFromTypeWithoutTestFixtureAttributeContainingTestCase ()
void ConstructFromTypeWithoutTestFixtureAttributeContainingTestCaseSource ()
void ConstructFromTypeWithoutTestFixtureAttributeContainingTheory ()
void CannotRunConstructorWithArgsNotSupplied ()
void CanRunConstructorWithArgsSupplied ()
void BadConstructorRunsWithSetUpError ()
void CanRunMultipleSetUp ()
void CanRunMultipleTearDown ()
void FixtureUsingIgnoreAttributeIsIgnored ()
void FixtureUsingIgnorePropertyIsIgnored ()
void FixtureUsingIgnoreReasonPropertyIsIgnored ()
void CanRunFixtureDerivedFromAbstractTestFixture ()
void CanRunFixtureDerivedFromAbstractDerivedTestFixture ()
void FixtureInheritingTwoTestFixtureAttributesIsLoadedOnlyOnce ()
void CanRunMultipleTestFixtureSetUp ()
void CanRunMultipleTestFixtureTearDown ()
void CanRunTestFixtureWithNoTests ()
void ConstructFromStaticTypeWithoutTestFixtureAttribute ()
void CanRunStaticFixture ()
void CanRunGenericFixtureWithProperArgsProvided ()
void CannotRunGenericFixtureWithNoArgsProvided ()
void CannotRunGenericFixtureDerivedFromAbstractFixtureWithNoArgsProvided ()
void CanRunGenericFixtureDerivedFromAbstractFixtureWithArgsProvided ()
void CannotRunPrivateSetUp ()
void CanRunProtectedSetUp ()
void CanRunStaticSetUp ()
Determines whether this instance [can run static set up].
void CannotRunSetupWithReturnValue ()
void CannotRunSetupWithParameters ()
void CannotRunPrivateTearDown ()
void CanRunProtectedTearDown ()
void CanRunStaticTearDown ()
void CannotRunTearDownWithReturnValue ()
void CannotRunTearDownWithParameters ()
void CannotRunPrivateFixtureSetUp ()
void CanRunProtectedFixtureSetUp ()
void CanRunStaticFixtureSetUp ()
void CannotRunFixtureSetupWithReturnValue ()
void CannotRunFixtureSetupWithParameters ()
void CannotRunPrivateFixtureTearDown ()
void CanRunProtectedFixtureTearDown ()
void CanRunStaticFixtureTearDown ()
void CannotRunFixtureTearDownWithReturnValue ()
void CannotRunFixtureTearDownWithParameters ()
Static Private Member Functions
static void CanConstructFrom (Type fixtureType)
static void CanConstructFrom (Type fixtureType, string expectedName)
static Type GetTestDataType (string typeName)
Static Private Attributes
static string dataAssembly = "nunit.testdata"
Detailed Description
Tests of the NUnitTestFixture class
Member Function Documentation
CanConstructFrom() [1/2]
static void NUnit.Framework.Internal.TestFixtureTests.CanConstructFrom (Type fixtureType) inline static private
Referenced by NUnit.Framework.Internal.TestFixtureTests.ConstructFromDoublyNestedType(), NUnit.Framework.Internal.TestFixtureTests.ConstructFromNestedType(), NUnit.Framework.Internal.TestFixtureTests.ConstructFromStaticTypeWithoutTestFixtureAttribute(), NUnit.Framework.Internal.TestFixtureTests.ConstructFromType(), NUnit.Framework.Internal.TestFixtureTests.ConstructFromTypeWithoutTestFixtureAttributeContainingTest(), NUnit.Framework.Internal.TestFixtureTests.ConstructFromTypeWithoutTestFixtureAttributeContainingTestCase(), NUnit.Framework.Internal.TestFixtureTests.ConstructFromTypeWithoutTestFixtureAttributeContainingTestCaseSource(), and NUnit.Framework.Internal.TestFixtureTests.ConstructFromTypeWithoutTestFixtureAttributeContainingTheory().
CanConstructFrom() [2/2]
static void NUnit.Framework.Internal.TestFixtureTests.CanConstructFrom (Type fixtureType, string expectedName) inline static private
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.Test.FullName, NUnit.TestUtilities.TestBuilder.MakeFixture(), and NUnit.Framework.Internal.Test.Name.
GetTestDataType()
static Type NUnit.Framework.Internal.TestFixtureTests.GetTestDataType (string typeName) inline static private
References NUnit.Framework.Internal.TestFixtureTests.dataAssembly.
ConstructFromType()
void NUnit.Framework.Internal.TestFixtureTests.ConstructFromType () inline
References NUnit.Framework.Internal.TestFixtureTests.CanConstructFrom().
ConstructFromNestedType()
void NUnit.Framework.Internal.TestFixtureTests.ConstructFromNestedType () inline
References NUnit.Framework.Internal.TestFixtureTests.CanConstructFrom().
ConstructFromDoublyNestedType()
void NUnit.Framework.Internal.TestFixtureTests.ConstructFromDoublyNestedType () inline
References NUnit.Framework.Internal.TestFixtureTests.CanConstructFrom().
ConstructFromTypeWithoutTestFixtureAttributeContainingTest()
void NUnit.Framework.Internal.TestFixtureTests.ConstructFromTypeWithoutTestFixtureAttributeContainingTest () inline
References NUnit.Framework.Internal.TestFixtureTests.CanConstructFrom().
ConstructFromTypeWithoutTestFixtureAttributeContainingTestCase()
void NUnit.Framework.Internal.TestFixtureTests.ConstructFromTypeWithoutTestFixtureAttributeContainingTestCase () inline
References NUnit.Framework.Internal.TestFixtureTests.CanConstructFrom().
ConstructFromTypeWithoutTestFixtureAttributeContainingTestCaseSource()
void NUnit.Framework.Internal.TestFixtureTests.ConstructFromTypeWithoutTestFixtureAttributeContainingTestCaseSource () inline
References NUnit.Framework.Internal.TestFixtureTests.CanConstructFrom().
ConstructFromTypeWithoutTestFixtureAttributeContainingTheory()
void NUnit.Framework.Internal.TestFixtureTests.ConstructFromTypeWithoutTestFixtureAttributeContainingTheory () inline
References NUnit.Framework.Internal.TestFixtureTests.CanConstructFrom().
CannotRunConstructorWithArgsNotSupplied()
void NUnit.Framework.Internal.TestFixtureTests.CannotRunConstructorWithArgsNotSupplied () inline
References NUnit.TestUtilities.TestAssert.IsNotRunnable().
CanRunConstructorWithArgsSupplied()
void NUnit.Framework.Internal.TestFixtureTests.CanRunConstructorWithArgsSupplied () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
BadConstructorRunsWithSetUpError()
void NUnit.Framework.Internal.TestFixtureTests.BadConstructorRunsWithSetUpError () inline
References NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.Framework.Interfaces.ResultState.SetUpError, and NUnit.Framework.Assert.That().
CanRunMultipleSetUp()
void NUnit.Framework.Internal.TestFixtureTests.CanRunMultipleSetUp () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
CanRunMultipleTearDown()
void NUnit.Framework.Internal.TestFixtureTests.CanRunMultipleTearDown () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
FixtureUsingIgnoreAttributeIsIgnored()
void NUnit.Framework.Internal.TestFixtureTests.FixtureUsingIgnoreAttributeIsIgnored () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeFixture(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, and NUnit.Framework.Internal.PropertyNames.SkipReason.
FixtureUsingIgnorePropertyIsIgnored()
void NUnit.Framework.Internal.TestFixtureTests.FixtureUsingIgnorePropertyIsIgnored () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeFixture(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, and NUnit.Framework.Internal.PropertyNames.SkipReason.
FixtureUsingIgnoreReasonPropertyIsIgnored()
void NUnit.Framework.Internal.TestFixtureTests.FixtureUsingIgnoreReasonPropertyIsIgnored () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeFixture(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, and NUnit.Framework.Internal.PropertyNames.SkipReason.
CanRunFixtureDerivedFromAbstractTestFixture()
void NUnit.Framework.Internal.TestFixtureTests.CanRunFixtureDerivedFromAbstractTestFixture () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
CanRunFixtureDerivedFromAbstractDerivedTestFixture()
void NUnit.Framework.Internal.TestFixtureTests.CanRunFixtureDerivedFromAbstractDerivedTestFixture () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
FixtureInheritingTwoTestFixtureAttributesIsLoadedOnlyOnce()
void NUnit.Framework.Internal.TestFixtureTests.FixtureInheritingTwoTestFixtureAttributesIsLoadedOnlyOnce () inline
References NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestBuilder.MakeFixture(), NUnit.Framework.Internal.TestSuite.Tests, NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
CanRunMultipleTestFixtureSetUp()
void NUnit.Framework.Internal.TestFixtureTests.CanRunMultipleTestFixtureSetUp () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
CanRunMultipleTestFixtureTearDown()
void NUnit.Framework.Internal.TestFixtureTests.CanRunMultipleTestFixtureTearDown () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
CanRunTestFixtureWithNoTests()
void NUnit.Framework.Internal.TestFixtureTests.CanRunTestFixtureWithNoTests () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
ConstructFromStaticTypeWithoutTestFixtureAttribute()
void NUnit.Framework.Internal.TestFixtureTests.ConstructFromStaticTypeWithoutTestFixtureAttribute () inline
References NUnit.Framework.Internal.TestFixtureTests.CanConstructFrom().
CanRunStaticFixture()
void NUnit.Framework.Internal.TestFixtureTests.CanRunStaticFixture () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
CanRunGenericFixtureWithProperArgsProvided()
void NUnit.Framework.Internal.TestFixtureTests.CanRunGenericFixtureWithProperArgsProvided () inline
References NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestBuilder.MakeFixture(), NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Internal.TestSuite.Tests, and NUnit.Framework.Assert.That().
CannotRunGenericFixtureWithNoArgsProvided()
void NUnit.Framework.Internal.TestFixtureTests.CannotRunGenericFixtureWithNoArgsProvided () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeFixture(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Internal.PropertyNames.SkipReason, NUnit.Framework.Does.StartWith(), NUnit.Framework.Internal.TestSuite.Tests, and NUnit.Framework.Assert.That().
CannotRunGenericFixtureDerivedFromAbstractFixtureWithNoArgsProvided()
void NUnit.Framework.Internal.TestFixtureTests.CannotRunGenericFixtureDerivedFromAbstractFixtureWithNoArgsProvided () inline
References NUnit.TestUtilities.TestAssert.IsNotRunnable(), NUnit.TestUtilities.TestBuilder.MakeFixture(), and NUnit.Framework.Internal.TestSuite.Tests.
CanRunGenericFixtureDerivedFromAbstractFixtureWithArgsProvided()
void NUnit.Framework.Internal.TestFixtureTests.CanRunGenericFixtureDerivedFromAbstractFixtureWithArgsProvided () inline
References NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestBuilder.MakeFixture(), NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Internal.TestSuite.Tests, and NUnit.Framework.Assert.That().
CannotRunPrivateSetUp()
void NUnit.Framework.Internal.TestFixtureTests.CannotRunPrivateSetUp () inline
References NUnit.TestUtilities.TestAssert.IsNotRunnable().
CanRunProtectedSetUp()
void NUnit.Framework.Internal.TestFixtureTests.CanRunProtectedSetUp () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
CanRunStaticSetUp()
void NUnit.Framework.Internal.TestFixtureTests.CanRunStaticSetUp () inline
Determines whether this instance [can run static set up].
References NUnit.TestUtilities.TestAssert.IsRunnable().
CannotRunSetupWithReturnValue()
void NUnit.Framework.Internal.TestFixtureTests.CannotRunSetupWithReturnValue () inline
References NUnit.TestUtilities.TestAssert.IsNotRunnable().
CannotRunSetupWithParameters()
void NUnit.Framework.Internal.TestFixtureTests.CannotRunSetupWithParameters () inline
References NUnit.TestUtilities.TestAssert.IsNotRunnable().
CannotRunPrivateTearDown()
void NUnit.Framework.Internal.TestFixtureTests.CannotRunPrivateTearDown () inline
References NUnit.TestUtilities.TestAssert.IsNotRunnable().
CanRunProtectedTearDown()
void NUnit.Framework.Internal.TestFixtureTests.CanRunProtectedTearDown () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
CanRunStaticTearDown()
void NUnit.Framework.Internal.TestFixtureTests.CanRunStaticTearDown () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
CannotRunTearDownWithReturnValue()
void NUnit.Framework.Internal.TestFixtureTests.CannotRunTearDownWithReturnValue () inline
References NUnit.TestUtilities.TestAssert.IsNotRunnable().
CannotRunTearDownWithParameters()
void NUnit.Framework.Internal.TestFixtureTests.CannotRunTearDownWithParameters () inline
References NUnit.TestUtilities.TestAssert.IsNotRunnable().
CannotRunPrivateFixtureSetUp()
void NUnit.Framework.Internal.TestFixtureTests.CannotRunPrivateFixtureSetUp () inline
References NUnit.TestUtilities.TestAssert.IsNotRunnable().
CanRunProtectedFixtureSetUp()
void NUnit.Framework.Internal.TestFixtureTests.CanRunProtectedFixtureSetUp () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
CanRunStaticFixtureSetUp()
void NUnit.Framework.Internal.TestFixtureTests.CanRunStaticFixtureSetUp () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
CannotRunFixtureSetupWithReturnValue()
void NUnit.Framework.Internal.TestFixtureTests.CannotRunFixtureSetupWithReturnValue () inline
References NUnit.TestUtilities.TestAssert.IsNotRunnable().
CannotRunFixtureSetupWithParameters()
void NUnit.Framework.Internal.TestFixtureTests.CannotRunFixtureSetupWithParameters () inline
References NUnit.TestUtilities.TestAssert.IsNotRunnable().
CannotRunPrivateFixtureTearDown()
void NUnit.Framework.Internal.TestFixtureTests.CannotRunPrivateFixtureTearDown () inline
References NUnit.TestUtilities.TestAssert.IsNotRunnable().
CanRunProtectedFixtureTearDown()
void NUnit.Framework.Internal.TestFixtureTests.CanRunProtectedFixtureTearDown () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
CanRunStaticFixtureTearDown()
void NUnit.Framework.Internal.TestFixtureTests.CanRunStaticFixtureTearDown () inline
References NUnit.TestUtilities.TestAssert.IsRunnable().
CannotRunFixtureTearDownWithReturnValue()
void NUnit.Framework.Internal.TestFixtureTests.CannotRunFixtureTearDownWithReturnValue () inline
References NUnit.TestUtilities.TestAssert.IsNotRunnable().
CannotRunFixtureTearDownWithParameters()
void NUnit.Framework.Internal.TestFixtureTests.CannotRunFixtureTearDownWithParameters () inline
References NUnit.TestUtilities.TestAssert.IsNotRunnable().
Member Data Documentation
dataAssembly
string NUnit.Framework.Internal.TestFixtureTests.dataAssembly = "nunit.testdata" static private
Referenced by NUnit.Framework.Internal.TestFixtureTests.GetTestDataType().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/TestFixtureTests.cs