Doc: IGLib EXTENDED: NeuronDotNet.Core.SOM.NeighborhoodFunctions.GaussianFunction Class Reference
NeuronDotNet.Core.SOM.NeighborhoodFunctions.GaussianFunction Class Reference
Gaussian Neighborhood Function. It is a continuous bell shaped curve centered at winner neuron.
Public Member Functions
GaussianFunction (int learningRadius)
Creates a new Gaussian Neighborhood Function
GaussianFunction (SerializationInfo info, StreamingContext context)
Deserialization Constructor
void GetObjectData (SerializationInfo info, StreamingContext context)
Populates the serialization info with the data needed to serialize the neighborhood function
void EvaluateNeighborhood (KohonenLayer layer, int currentIteration, int trainingEpochs)
Determines the neighborhood of every neuron in the given Kohonen layer with respect to winner neuron using Gaussian function
Properties
double Sigma [get]
Gets the initial value of sigma
Private Attributes
readonly double sigma = 0d
Detailed Description
Gaussian Neighborhood Function. It is a continuous bell shaped curve centered at winner neuron.
Constructor & Destructor Documentation
GaussianFunction() [1/2]
NeuronDotNet.Core.SOM.NeighborhoodFunctions.GaussianFunction.GaussianFunction (int learningRadius) inline
Creates a new Gaussian Neighborhood Function
Parameters
learningRadius Initial Learning Radius
GaussianFunction() [2/2]
NeuronDotNet.Core.SOM.NeighborhoodFunctions.GaussianFunction.GaussianFunction (SerializationInfo info, StreamingContext context) inline
Deserialization Constructor
Parameters
info Serialization information to deserialize and obtain the data
context Serialization context to use
Exceptions
ArgumentNullException If info is null
References NeuronDotNet.Core.Helper.ValidateNotNull().
Member Function Documentation
GetObjectData()
void NeuronDotNet.Core.SOM.NeighborhoodFunctions.GaussianFunction.GetObjectData (SerializationInfo info, StreamingContext context) inline
Populates the serialization info with the data needed to serialize the neighborhood function
Parameters
info The serialization info to populate the data with
context The serialization context to use
Exceptions
ArgumentNullException If info is null
References NeuronDotNet.Core.SOM.NeighborhoodFunctions.GaussianFunction.sigma, and NeuronDotNet.Core.Helper.ValidateNotNull().
EvaluateNeighborhood()
void NeuronDotNet.Core.SOM.NeighborhoodFunctions.GaussianFunction.EvaluateNeighborhood (KohonenLayer layer, int currentIteration, int trainingEpochs) inline
Determines the neighborhood of every neuron in the given Kohonen layer with respect to winner neuron using Gaussian function
Parameters
layer The Kohonen Layer containing neurons
currentIteration Current training iteration
trainingEpochs Total number of training epochs
Exceptions
ArgumentNullException If layer is null
ArgumentException If trainingEpochs is zero or negative
ArgumentOutOfRangeException If currentIteration is negative or, if it is not less than trainingEpochs
Implements NeuronDotNet.Core.SOM.INeighborhoodFunction.
References NeuronDotNet.Core.SOM.PositionNeuron.Coordinate, NeuronDotNet.Core.SOM.NeighborhoodFunctions.GaussianFunction.sigma, NeuronDotNet.Core.SOM.KohonenLayer.Size, NeuronDotNet.Core.Helper.ValidateNotNull(), NeuronDotNet.Core.Helper.ValidatePositive(), and NeuronDotNet.Core.SOM.KohonenLayer.Winner.
Member Data Documentation
sigma
readonly double NeuronDotNet.Core.SOM.NeighborhoodFunctions.GaussianFunction.sigma = 0d private
Referenced by NeuronDotNet.Core.SOM.NeighborhoodFunctions.GaussianFunction.EvaluateNeighborhood(), and NeuronDotNet.Core.SOM.NeighborhoodFunctions.GaussianFunction.GetObjectData().
Property Documentation
Sigma
double NeuronDotNet.Core.SOM.NeighborhoodFunctions.GaussianFunction.Sigma get
Gets the initial value of sigma
Initial value of sigma
The documentation for this class was generated from the following file:
shelldev/lib/externalextended/NeuronDotNetGPL/source/Core/SOM/NeighborhoodFunctions/GaussianFunction.cs