Doc: IGLib EXTENDED: IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase Class Reference
IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase Class Reference
A template class for physical models. Each child should define its own plottable curves).
Public Member Functions
PlotZedgraphCurve NewCurveFromPlottableData (PlotterZedGraph plotter, int x, int y)
Creates a new PlotZedgraphCurve object from the available plottable data.
void LoadPlottableDataToCurve (PlotZedgraphCurve curve, int x, int y)
Copies the calculated data to the existing PlotZedgraphCurve object. Enough space must be available on the curve object's list.
Protected Attributes
string _title
Properties
string Title [get, set]
The plottable model's name. Also used as a plot title.
List< double[]> PlottableData [get, set]
The main solution array, which is used by the plotter.
Private Attributes
List< double[]> _plottableData
Detailed Description
A template class for physical models. Each child should define its own plottable curves).
Member Function Documentation
NewCurveFromPlottableData()
PlotZedgraphCurve IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase.NewCurveFromPlottableData (PlotterZedGraph plotter, int x, int y) inline
Creates a new PlotZedgraphCurve object from the available plottable data.
Parameters
plotter The PlotHQ's plotter to which the new curve should belong.
x Which sublist (index) on the source list (plottable data) represents the x-axis data.
y Which sublist (index) on the source list (plottable data) represents the y-axis data.
Returns
A PlotZedGraphCurve object filled with values.
References IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase._plottableData, and IG.Gr.PlotZedgraphCurve.AddPoint().
Referenced by IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.A_vs_T(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.ResonanceCurve(), IG.MPetekLib.Application.Scripts.LinearOscillator._14PhaseShiftPlot.Run(), IG.MPetekLib.Application.Scripts.NonlinearOscillator._15SolutionPlot.Run(), IG.MPetekLib.Application.Scripts.NonlinearOscNondim._16SolutionPlot.Run(), IG.MPetekLib.Application.Scripts.MagOscHardSpring._23SingleResCurveManyPhases.Run(), IG.MPetekLib.Application.Scripts.NonlinearOscillator._19SingleResonancePlot.Run(), IG.MPetekLib.Application.Scripts.NonlinearOscillator._22SingleResCurveManyPhases.Run(), IG.Script._18ChaoticPlot.Run(), IG.MPetekLib.Application.Scripts.NonlinearOscillator._21MultipleResCurvesPlot.Run(), IG.Script._25KickedRotator.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._08SteadyStateAmplitude.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._12MultipleResCurvesPlot.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._13SolutionAndDrivingFunctionPlot.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._09SingleResonanceCurvePlot.Run(), IG.MPetekLib.Application.Scripts.MagOscHardSpring._24MultiResCurvesPlotPhaseScan.Run(), IG.MPetekLib.Application.Scripts.NonlinearOscNondim._20MultipleResCurvesPlot.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._10MultipleResCurvesPlotObsolete.Run(), IG.Script.DemoResonanceCurvePlot.Run(), IG.Script.DemoResonanceCurvePlotExt.Run(), IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.MolecularCatenary.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.V_vs_T(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.V_vs_X(), and IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.X_vs_T().
LoadPlottableDataToCurve()
void IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase.LoadPlottableDataToCurve (PlotZedgraphCurve curve, int x, int y) inline
Copies the calculated data to the existing PlotZedgraphCurve object. Enough space must be available on the curve object's list.
Parameters
curve The PlotZedgraphCurve object that the data will be copied to.
x Which sublist (index) on the source list (plottable data) represents the x-axis data.
y Which sublist (index) on the source list (plottable data) represents the y-axis data.
References IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase._plottableData, IG.Gr.PlotZedgraphCurve.AddPoint(), and IG.Gr.PlotZedgraphCurve.ClearPoints().
Referenced by IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.Run(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.MolecularCatenary.SimulatedAnnealing().
Member Data Documentation
_title
string IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase._title protected
Referenced by IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.DrivenHarmonicOscillator().
_plottableData
List<double[]> IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase._plottableData private
Referenced by IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase.LoadPlottableDataToCurve(), and IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase.NewCurveFromPlottableData().
Property Documentation
Title
string IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase.Title get set
The plottable model's name. Also used as a plot title.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenNonlinearOscillator.DrivenNonlinearOscillator(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenNonlinOscNondim.DrivenNonlinOscNondim(), and IG.MPetekLib.Algorithms.PlottableModels.Oscillators.MagneticOscHardSpring.MagneticOscHardSpring().
PlottableData
List<double[]> IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase.PlottableData get set
The main solution array, which is used by the plotter.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.CalcAnalyticalAmplitudeVsDrivingFrequnecy(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.CalcAnalyticalResonantAmplitudeVsResonantDrivingFrequency(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.CalcSteadyStateAmplitudeVsDrivingFrequency(), IG.MPetekLib.Algorithms.PlottableModels.PlottableODEModelBase.CalculateErrors(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.CalculateExactErrors(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.FindAnalyticallyPhaseVsDrivingFrequency(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.LoadDrivingFunctionInSolution(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.MolecularCatenary.MolecularCatenary(), IG.MPetekLib.Algorithms.PlottableModels.PlottableODEModelBase.PostProcessErrors(), IG.MPetekLib.Algorithms.PlottableModels.KickedRotator.Solve(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.SolveAnalytically(), IG.MPetekLib.Algorithms.PlottableModels.PlottableODEModelBase.SolveNumerically(), IG.MPetekLib.Algorithms.PlottableModels.KickedRotator.TakeAStep(), and IG.MPetekLib.Algorithms.PlottableModels.PlottableODEModelBase.VerifyErrorsValidity().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/Guest_Marko_Petek_Lib/algorithms/PlottableModels/00PlottableModelBase.cs