Doc: IGLib EXTENDED: NUnit.Framework.Internal.RuntimeFramework Class Reference
NUnit.Framework.Internal.RuntimeFramework Class Reference
RuntimeFramework represents a particular version of a common language runtime implementation.
Public Member Functions
RuntimeFramework (RuntimeType runtime, Version version)
Construct from a runtime type and version. If the version has two parts, it is taken as a framework version. If it has three or more, it is taken as a CLR version. In either case, the other version is deduced based on the runtime type and provided version.
override string ToString ()
Overridden to return the short name of the framework
bool Supports (RuntimeFramework target)
Returns true if the current framework matches the one supplied as an argument. Two frameworks match if their runtime types are the same or either one is RuntimeType.Any and all specified version components are equal. Negative (i.e. unspecified) version components are ignored.
Static Public Member Functions
static RuntimeFramework Parse (string s)
Parses a string representing a RuntimeFramework. The string may be just a RuntimeType name or just a Version or a hyphenated RuntimeType-Version or a Version prefixed by 'versionString'.
Static Public Attributes
static readonly Version DefaultVersion = new Version(0,0)
DefaultVersion is an empty Version, used to indicate that NUnit should select the CLR version to use for the test.
Properties
static RuntimeFramework??? CurrentFramework [get]
Static method to return a RuntimeFramework object for the framework that is currently in use.
RuntimeType Runtime [get, private set]
The type of this runtime framework
Version FrameworkVersion [get, private set]
The framework version for this runtime framework
Version ClrVersion [get, private set]
The CLR version for this runtime framework
bool AllowAnyVersion [get]
Return true if any CLR version may be used in matching this RuntimeFramework object.
string DisplayName [get, private set]
Returns the Display name for this framework
Private Member Functions
void InitFromFrameworkVersion (Version version)
void InitFromClrVersion (Version version)
Static Private Member Functions
static void ThrowInvalidFrameworkVersion (Version version)
static bool IsRuntimeTypeName (string name)
static string GetDefaultDisplayName (RuntimeType runtime, Version version)
static bool VersionsMatch (Version v1, Version v2)
Static Private Attributes
static RuntimeFramework currentFramework
Detailed Description
RuntimeFramework represents a particular version of a common language runtime implementation.
Constructor & Destructor Documentation
RuntimeFramework()
NUnit.Framework.Internal.RuntimeFramework.RuntimeFramework (RuntimeType runtime, Version version) inline
Construct from a runtime type and version. If the version has two parts, it is taken as a framework version. If it has three or more, it is taken as a CLR version. In either case, the other version is deduced based on the runtime type and provided version.
Parameters
runtime The runtime type of the framework
version The version of the framework
References NUnit.Framework.Internal.RuntimeFramework.DisplayName, NUnit.Framework.Internal.RuntimeFramework.GetDefaultDisplayName(), NUnit.Framework.Internal.RuntimeFramework.InitFromClrVersion(), NUnit.Framework.Internal.RuntimeFramework.InitFromFrameworkVersion(), and NUnit.Framework.Internal.RuntimeFramework.Runtime.
Referenced by NUnit.Framework.Internal.RuntimeFramework.Parse().
Member Function Documentation
InitFromFrameworkVersion()
void NUnit.Framework.Internal.RuntimeFramework.InitFromFrameworkVersion (Version version) inline private
References NUnit.Framework.Internal.RuntimeFramework.ClrVersion, NUnit.Framework.Internal.RuntimeFramework.FrameworkVersion, NUnit.Framework.Internal.RuntimeFramework.Runtime, and NUnit.Framework.Internal.RuntimeFramework.ThrowInvalidFrameworkVersion().
Referenced by NUnit.Framework.Internal.RuntimeFramework.RuntimeFramework().
ThrowInvalidFrameworkVersion()
static void NUnit.Framework.Internal.RuntimeFramework.ThrowInvalidFrameworkVersion (Version version) inline static private
Referenced by NUnit.Framework.Internal.RuntimeFramework.InitFromFrameworkVersion().
InitFromClrVersion()
void NUnit.Framework.Internal.RuntimeFramework.InitFromClrVersion (Version version) inline private
References NUnit.Framework.Internal.RuntimeFramework.ClrVersion, NUnit.Framework.Internal.RuntimeFramework.FrameworkVersion, and NUnit.Framework.Internal.RuntimeFramework.Runtime.
Referenced by NUnit.Framework.Internal.RuntimeFramework.RuntimeFramework().
Parse()
static RuntimeFramework NUnit.Framework.Internal.RuntimeFramework.Parse (string s) inline static
Parses a string representing a RuntimeFramework. The string may be just a RuntimeType name or just a Version or a hyphenated RuntimeType-Version or a Version prefixed by 'versionString'.
Parameters
s
Returns
References NUnit.Framework.Internal.RuntimeFramework.DefaultVersion, NUnit.Framework.Internal.RuntimeFramework.IsRuntimeTypeName(), and NUnit.Framework.Internal.RuntimeFramework.RuntimeFramework().
Referenced by NUnit.Engine.Tests.RuntimeFrameworkTests.CanParseRuntimeFramework(), and NUnit.Framework.Internal.RuntimeFrameworkTests.CanParseRuntimeFramework().
ToString()
override string NUnit.Framework.Internal.RuntimeFramework.ToString () inline
Overridden to return the short name of the framework
Returns
References NUnit.Framework.Internal.RuntimeFramework.AllowAnyVersion, NUnit.Framework.Internal.RuntimeFramework.FrameworkVersion, and NUnit.Framework.Internal.RuntimeFramework.Runtime.
Referenced by NUnit.Engine.Tests.RuntimeFrameworkTests.CanDisplayFrameworkAsString(), and NUnit.Framework.Internal.RuntimeFrameworkTests.CanDisplayFrameworkAsString().
Supports()
bool NUnit.Framework.Internal.RuntimeFramework.Supports (RuntimeFramework target) inline
Returns true if the current framework matches the one supplied as an argument. Two frameworks match if their runtime types are the same or either one is RuntimeType.Any and all specified version components are equal. Negative (i.e. unspecified) version components are ignored.
Parameters
target The RuntimeFramework to be matched.
Returns
True on match, otherwise false
References NUnit.Framework.Internal.RuntimeFramework.AllowAnyVersion, NUnit.Framework.Internal.RuntimeFramework.ClrVersion, NUnit.Framework.Internal.RuntimeFramework.FrameworkVersion, NUnit.Framework.Internal.RuntimeFramework.Runtime, and NUnit.Framework.Internal.RuntimeFramework.VersionsMatch().
Referenced by NUnit.Engine.Tests.RuntimeFrameworkTests.CanListAvailableFrameworks(), NUnit.Engine.Tests.RuntimeFrameworkTests.CanMatchRuntimes(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanMatchRuntimes(), and NUnit.Framework.Internal.PlatformHelper.IsRuntimeSupported().
IsRuntimeTypeName()
static bool NUnit.Framework.Internal.RuntimeFramework.IsRuntimeTypeName (string name) inline static private
References NUnit.Framework.Internal.TypeHelper.GetEnumNames().
Referenced by NUnit.Framework.Internal.RuntimeFramework.Parse().
GetDefaultDisplayName()
static string NUnit.Framework.Internal.RuntimeFramework.GetDefaultDisplayName (RuntimeType runtime, Version version) inline static private
References NUnit.Framework.Internal.RuntimeFramework.DefaultVersion.
Referenced by NUnit.Framework.Internal.RuntimeFramework.RuntimeFramework().
VersionsMatch()
static bool NUnit.Framework.Internal.RuntimeFramework.VersionsMatch (Version v1, Version v2) inline static private
Referenced by NUnit.Framework.Internal.RuntimeFramework.Supports().
Member Data Documentation
DefaultVersion
readonly Version NUnit.Framework.Internal.RuntimeFramework.DefaultVersion = new Version(0,0) static
DefaultVersion is an empty Version, used to indicate that NUnit should select the CLR version to use for the test.
Referenced by NUnit.Framework.Internal.RuntimeFramework.GetDefaultDisplayName(), NUnit.Framework.Internal.PlatformHelper.IsRuntimeSupported(), and NUnit.Framework.Internal.RuntimeFramework.Parse().
currentFramework
RuntimeFramework NUnit.Framework.Internal.RuntimeFramework.currentFramework static private
Property Documentation
CurrentFramework
RuntimeFramework??? NUnit.Framework.Internal.RuntimeFramework.CurrentFramework static get
Static method to return a RuntimeFramework object for the framework that is currently in use.
Referenced by NUnit.Engine.Tests.RuntimeFrameworkTests.CanGetCurrentFramework(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanGetCurrentFramework(), NUnit.Engine.Tests.RuntimeFrameworkTests.CanListAvailableFrameworks(), NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms(), NUnit.Engine.Tests.RuntimeFrameworkTests.CurrentFrameworkHasBuildSpecified(), NUnit.Framework.Internal.RuntimeFrameworkTests.CurrentFrameworkHasBuildSpecified(), NUnit.Engine.Tests.RuntimeFrameworkTests.CurrentFrameworkMustBeAvailable(), and NUnit.Framework.Internal.PlatformHelper.PlatformHelper().
Runtime
RuntimeType NUnit.Framework.Internal.RuntimeFramework.Runtime get private set
The type of this runtime framework
Referenced by NUnit.Engine.Tests.RuntimeFrameworkTests.CanCreateUsingClrVersion(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanCreateUsingClrVersion(), NUnit.Engine.Tests.RuntimeFrameworkTests.CanCreateUsingFrameworkVersion(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanCreateUsingFrameworkVersion(), NUnit.Engine.Tests.RuntimeFrameworkTests.CanGetCurrentFramework(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanGetCurrentFramework(), NUnit.Engine.Tests.RuntimeFrameworkTests.CanParseRuntimeFramework(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanParseRuntimeFramework(), NUnit.Framework.Internal.RuntimeFramework.InitFromClrVersion(), NUnit.Framework.Internal.RuntimeFramework.InitFromFrameworkVersion(), NUnit.Framework.Internal.RuntimeFramework.RuntimeFramework(), NUnit.Framework.Internal.RuntimeFramework.Supports(), and NUnit.Framework.Internal.RuntimeFramework.ToString().
FrameworkVersion
Version NUnit.Framework.Internal.RuntimeFramework.FrameworkVersion get private set
The framework version for this runtime framework
Referenced by NUnit.Engine.Tests.RuntimeFrameworkTests.CanCreateUsingClrVersion(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanCreateUsingClrVersion(), NUnit.Engine.Tests.RuntimeFrameworkTests.CanCreateUsingFrameworkVersion(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanCreateUsingFrameworkVersion(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanGetCurrentFramework(), NUnit.Framework.Internal.RuntimeFramework.InitFromClrVersion(), NUnit.Framework.Internal.RuntimeFramework.InitFromFrameworkVersion(), NUnit.Framework.Internal.RuntimeFramework.Supports(), and NUnit.Framework.Internal.RuntimeFramework.ToString().
ClrVersion
Version NUnit.Framework.Internal.RuntimeFramework.ClrVersion get private set
The CLR version for this runtime framework
Referenced by NUnit.Engine.Tests.RuntimeFrameworkTests.CanCreateUsingClrVersion(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanCreateUsingClrVersion(), NUnit.Engine.Tests.RuntimeFrameworkTests.CanCreateUsingFrameworkVersion(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanCreateUsingFrameworkVersion(), NUnit.Engine.Tests.RuntimeFrameworkTests.CanGetCurrentFramework(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanGetCurrentFramework(), NUnit.Engine.Tests.RuntimeFrameworkTests.CanParseRuntimeFramework(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanParseRuntimeFramework(), NUnit.Engine.Tests.RuntimeFrameworkTests.CurrentFrameworkHasBuildSpecified(), NUnit.Framework.Internal.RuntimeFrameworkTests.CurrentFrameworkHasBuildSpecified(), NUnit.Framework.Internal.RuntimeFramework.InitFromClrVersion(), NUnit.Framework.Internal.RuntimeFramework.InitFromFrameworkVersion(), and NUnit.Framework.Internal.RuntimeFramework.Supports().
AllowAnyVersion
bool NUnit.Framework.Internal.RuntimeFramework.AllowAnyVersion get
Return true if any CLR version may be used in matching this RuntimeFramework object.
Referenced by NUnit.Framework.Internal.RuntimeFramework.Supports(), and NUnit.Framework.Internal.RuntimeFramework.ToString().
DisplayName
string NUnit.Framework.Internal.RuntimeFramework.DisplayName get private set
Returns the Display name for this framework
Referenced by NUnit.Engine.Tests.RuntimeFrameworkTests.CanDisplayFrameworkAsString(), NUnit.Framework.Internal.RuntimeFrameworkTests.CanDisplayFrameworkAsString(), NUnit.Engine.Tests.RuntimeFrameworkTests.CanListAvailableFrameworks(), and NUnit.Framework.Internal.RuntimeFramework.RuntimeFramework().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/RuntimeFramework.cs