Doc: IGLib EXTENDED: alglib.mannwhitneyu Class Reference
alglib.mannwhitneyu Class Reference
Static Public Member Functions
static void mannwhitneyutest (double[] x, int n, double[] y, int m, ref double bothtails, ref double lefttail, ref double righttail)
static void mannwhitneyutest (double[] x, int n, double[] y, int m, ref double bothtails, ref double lefttail, ref double righttail)
Static Private Member Functions
static void ucheb (double x, double c, ref double tj, ref double tj1, ref double r)
static double uninterpolate (double p1, double p2, double p3, int n)
static double usigma000 (int n1, int n2)
static double usigma075 (int n1, int n2)
static double usigma150 (int n1, int n2)
static double usigma225 (int n1, int n2)
static double usigma300 (int n1, int n2)
static double usigma333 (int n1, int n2)
static double usigma367 (int n1, int n2)
static double usigma400 (int n1, int n2)
static double utbln5n5 (double s)
static double utbln5n6 (double s)
static double utbln5n7 (double s)
static double utbln5n8 (double s)
static double utbln5n9 (double s)
static double utbln5n10 (double s)
static double utbln5n11 (double s)
static double utbln5n12 (double s)
static double utbln5n13 (double s)
static double utbln5n14 (double s)
static double utbln5n15 (double s)
static double utbln5n16 (double s)
static double utbln5n17 (double s)
static double utbln5n18 (double s)
static double utbln5n19 (double s)
static double utbln5n20 (double s)
static double utbln5n21 (double s)
static double utbln5n22 (double s)
static double utbln5n23 (double s)
static double utbln5n24 (double s)
static double utbln5n25 (double s)
static double utbln5n26 (double s)
static double utbln5n27 (double s)
static double utbln5n28 (double s)
static double utbln5n29 (double s)
static double utbln5n30 (double s)
static double utbln5n100 (double s)
static double utbln6n6 (double s)
static double utbln6n7 (double s)
static double utbln6n8 (double s)
static double utbln6n9 (double s)
static double utbln6n10 (double s)
static double utbln6n11 (double s)
static double utbln6n12 (double s)
static double utbln6n13 (double s)
static double utbln6n14 (double s)
static double utbln6n15 (double s)
static double utbln6n30 (double s)
static double utbln6n100 (double s)
static double utbln7n7 (double s)
static double utbln7n8 (double s)
static double utbln7n9 (double s)
static double utbln7n10 (double s)
static double utbln7n11 (double s)
static double utbln7n12 (double s)
static double utbln7n13 (double s)
static double utbln7n14 (double s)
static double utbln7n15 (double s)
static double utbln7n30 (double s)
static double utbln7n100 (double s)
static double utbln8n8 (double s)
static double utbln8n9 (double s)
static double utbln8n10 (double s)
static double utbln8n11 (double s)
static double utbln8n12 (double s)
static double utbln8n13 (double s)
static double utbln8n14 (double s)
static double utbln8n15 (double s)
static double utbln8n30 (double s)
static double utbln8n100 (double s)
static double utbln9n9 (double s)
static double utbln9n10 (double s)
static double utbln9n11 (double s)
static double utbln9n12 (double s)
static double utbln9n13 (double s)
static double utbln9n14 (double s)
static double utbln9n15 (double s)
static double utbln9n30 (double s)
static double utbln9n100 (double s)
static double utbln10n10 (double s)
static double utbln10n11 (double s)
static double utbln10n12 (double s)
static double utbln10n13 (double s)
static double utbln10n14 (double s)
static double utbln10n15 (double s)
static double utbln10n30 (double s)
static double utbln10n100 (double s)
static double utbln11n11 (double s)
static double utbln11n12 (double s)
static double utbln11n13 (double s)
static double utbln11n14 (double s)
static double utbln11n15 (double s)
static double utbln11n30 (double s)
static double utbln11n100 (double s)
static double utbln12n12 (double s)
static double utbln12n13 (double s)
static double utbln12n14 (double s)
static double utbln12n15 (double s)
static double utbln12n30 (double s)
static double utbln12n100 (double s)
static double utbln13n13 (double s)
static double utbln13n14 (double s)
static double utbln13n15 (double s)
static double utbln13n30 (double s)
static double utbln13n100 (double s)
static double utbln14n14 (double s)
static double utbln14n15 (double s)
static double utbln14n30 (double s)
static double utbln14n100 (double s)
static double usigma (double s, int n1, int n2)
static void ucheb (double x, double c, ref double tj, ref double tj1, ref double r)
static double uninterpolate (double p1, double p2, double p3, int n)
static double usigma000 (int n1, int n2)
static double usigma075 (int n1, int n2)
static double usigma150 (int n1, int n2)
static double usigma225 (int n1, int n2)
static double usigma300 (int n1, int n2)
static double usigma333 (int n1, int n2)
static double usigma367 (int n1, int n2)
static double usigma400 (int n1, int n2)
static double utbln5n5 (double s)
static double utbln5n6 (double s)
static double utbln5n7 (double s)
static double utbln5n8 (double s)
static double utbln5n9 (double s)
static double utbln5n10 (double s)
static double utbln5n11 (double s)
static double utbln5n12 (double s)
static double utbln5n13 (double s)
static double utbln5n14 (double s)
static double utbln5n15 (double s)
static double utbln5n16 (double s)
static double utbln5n17 (double s)
static double utbln5n18 (double s)
static double utbln5n19 (double s)
static double utbln5n20 (double s)
static double utbln5n21 (double s)
static double utbln5n22 (double s)
static double utbln5n23 (double s)
static double utbln5n24 (double s)
static double utbln5n25 (double s)
static double utbln5n26 (double s)
static double utbln5n27 (double s)
static double utbln5n28 (double s)
static double utbln5n29 (double s)
static double utbln5n30 (double s)
static double utbln5n100 (double s)
static double utbln6n6 (double s)
static double utbln6n7 (double s)
static double utbln6n8 (double s)
static double utbln6n9 (double s)
static double utbln6n10 (double s)
static double utbln6n11 (double s)
static double utbln6n12 (double s)
static double utbln6n13 (double s)
static double utbln6n14 (double s)
static double utbln6n15 (double s)
static double utbln6n30 (double s)
static double utbln6n100 (double s)
static double utbln7n7 (double s)
static double utbln7n8 (double s)
static double utbln7n9 (double s)
static double utbln7n10 (double s)
static double utbln7n11 (double s)
static double utbln7n12 (double s)
static double utbln7n13 (double s)
static double utbln7n14 (double s)
static double utbln7n15 (double s)
static double utbln7n30 (double s)
static double utbln7n100 (double s)
static double utbln8n8 (double s)
static double utbln8n9 (double s)
static double utbln8n10 (double s)
static double utbln8n11 (double s)
static double utbln8n12 (double s)
static double utbln8n13 (double s)
static double utbln8n14 (double s)
static double utbln8n15 (double s)
static double utbln8n30 (double s)
static double utbln8n100 (double s)
static double utbln9n9 (double s)
static double utbln9n10 (double s)
static double utbln9n11 (double s)
static double utbln9n12 (double s)
static double utbln9n13 (double s)
static double utbln9n14 (double s)
static double utbln9n15 (double s)
static double utbln9n30 (double s)
static double utbln9n100 (double s)
static double utbln10n10 (double s)
static double utbln10n11 (double s)
static double utbln10n12 (double s)
static double utbln10n13 (double s)
static double utbln10n14 (double s)
static double utbln10n15 (double s)
static double utbln10n30 (double s)
static double utbln10n100 (double s)
static double utbln11n11 (double s)
static double utbln11n12 (double s)
static double utbln11n13 (double s)
static double utbln11n14 (double s)
static double utbln11n15 (double s)
static double utbln11n30 (double s)
static double utbln11n100 (double s)
static double utbln12n12 (double s)
static double utbln12n13 (double s)
static double utbln12n14 (double s)
static double utbln12n15 (double s)
static double utbln12n30 (double s)
static double utbln12n100 (double s)
static double utbln13n13 (double s)
static double utbln13n14 (double s)
static double utbln13n15 (double s)
static double utbln13n30 (double s)
static double utbln13n100 (double s)
static double utbln14n14 (double s)
static double utbln14n15 (double s)
static double utbln14n30 (double s)
static double utbln14n100 (double s)
static double usigma (double s, int n1, int n2)
Member Function Documentation
mannwhitneyutest() [1/2]
static void alglib.mannwhitneyu.mannwhitneyutest (double[] x, int n, double[] y, int m, ref double bothtails, ref double lefttail, ref double righttail) inline static
References alglib.math.sqr(), and alglib.mannwhitneyu.usigma().
Referenced by alglib.mannwhitneyutest().
ucheb() [1/2]
static void alglib.mannwhitneyu.ucheb (double x, double c, ref double tj, ref double tj1, ref double r) inline static private
Referenced by alglib.mannwhitneyu.utbln10n10(), alglib.mannwhitneyu.utbln10n100(), alglib.mannwhitneyu.utbln10n11(), alglib.mannwhitneyu.utbln10n12(), alglib.mannwhitneyu.utbln10n13(), alglib.mannwhitneyu.utbln10n14(), alglib.mannwhitneyu.utbln10n15(), alglib.mannwhitneyu.utbln10n30(), alglib.mannwhitneyu.utbln11n100(), alglib.mannwhitneyu.utbln11n11(), alglib.mannwhitneyu.utbln11n12(), alglib.mannwhitneyu.utbln11n13(), alglib.mannwhitneyu.utbln11n14(), alglib.mannwhitneyu.utbln11n15(), alglib.mannwhitneyu.utbln11n30(), alglib.mannwhitneyu.utbln12n100(), alglib.mannwhitneyu.utbln12n12(), alglib.mannwhitneyu.utbln12n13(), alglib.mannwhitneyu.utbln12n14(), alglib.mannwhitneyu.utbln12n15(), alglib.mannwhitneyu.utbln12n30(), alglib.mannwhitneyu.utbln13n100(), alglib.mannwhitneyu.utbln13n13(), alglib.mannwhitneyu.utbln13n14(), alglib.mannwhitneyu.utbln13n15(), alglib.mannwhitneyu.utbln13n30(), alglib.mannwhitneyu.utbln14n100(), alglib.mannwhitneyu.utbln14n14(), alglib.mannwhitneyu.utbln14n15(), alglib.mannwhitneyu.utbln14n30(), alglib.mannwhitneyu.utbln5n10(), alglib.mannwhitneyu.utbln5n100(), alglib.mannwhitneyu.utbln5n11(), alglib.mannwhitneyu.utbln5n12(), alglib.mannwhitneyu.utbln5n13(), alglib.mannwhitneyu.utbln5n14(), alglib.mannwhitneyu.utbln5n15(), alglib.mannwhitneyu.utbln5n16(), alglib.mannwhitneyu.utbln5n17(), alglib.mannwhitneyu.utbln5n18(), alglib.mannwhitneyu.utbln5n19(), alglib.mannwhitneyu.utbln5n20(), alglib.mannwhitneyu.utbln5n21(), alglib.mannwhitneyu.utbln5n22(), alglib.mannwhitneyu.utbln5n23(), alglib.mannwhitneyu.utbln5n24(), alglib.mannwhitneyu.utbln5n25(), alglib.mannwhitneyu.utbln5n26(), alglib.mannwhitneyu.utbln5n27(), alglib.mannwhitneyu.utbln5n28(), alglib.mannwhitneyu.utbln5n29(), alglib.mannwhitneyu.utbln5n30(), alglib.mannwhitneyu.utbln5n5(), alglib.mannwhitneyu.utbln5n6(), alglib.mannwhitneyu.utbln5n7(), alglib.mannwhitneyu.utbln5n8(), alglib.mannwhitneyu.utbln5n9(), alglib.mannwhitneyu.utbln6n10(), alglib.mannwhitneyu.utbln6n100(), alglib.mannwhitneyu.utbln6n11(), alglib.mannwhitneyu.utbln6n12(), alglib.mannwhitneyu.utbln6n13(), alglib.mannwhitneyu.utbln6n14(), alglib.mannwhitneyu.utbln6n15(), alglib.mannwhitneyu.utbln6n30(), alglib.mannwhitneyu.utbln6n6(), alglib.mannwhitneyu.utbln6n7(), alglib.mannwhitneyu.utbln6n8(), alglib.mannwhitneyu.utbln6n9(), alglib.mannwhitneyu.utbln7n10(), alglib.mannwhitneyu.utbln7n100(), alglib.mannwhitneyu.utbln7n11(), alglib.mannwhitneyu.utbln7n12(), alglib.mannwhitneyu.utbln7n13(), alglib.mannwhitneyu.utbln7n14(), alglib.mannwhitneyu.utbln7n15(), alglib.mannwhitneyu.utbln7n30(), alglib.mannwhitneyu.utbln7n7(), alglib.mannwhitneyu.utbln7n8(), alglib.mannwhitneyu.utbln7n9(), alglib.mannwhitneyu.utbln8n10(), alglib.mannwhitneyu.utbln8n100(), alglib.mannwhitneyu.utbln8n11(), alglib.mannwhitneyu.utbln8n12(), alglib.mannwhitneyu.utbln8n13(), alglib.mannwhitneyu.utbln8n14(), alglib.mannwhitneyu.utbln8n15(), alglib.mannwhitneyu.utbln8n30(), alglib.mannwhitneyu.utbln8n8(), alglib.mannwhitneyu.utbln8n9(), alglib.mannwhitneyu.utbln9n10(), alglib.mannwhitneyu.utbln9n100(), alglib.mannwhitneyu.utbln9n11(), alglib.mannwhitneyu.utbln9n12(), alglib.mannwhitneyu.utbln9n13(), alglib.mannwhitneyu.utbln9n14(), alglib.mannwhitneyu.utbln9n15(), alglib.mannwhitneyu.utbln9n30(), and alglib.mannwhitneyu.utbln9n9().
uninterpolate() [1/2]
static double alglib.mannwhitneyu.uninterpolate (double p1, double p2, double p3, int n) inline static private
Referenced by alglib.mannwhitneyu.usigma(), alglib.mannwhitneyu.usigma000(), alglib.mannwhitneyu.usigma075(), alglib.mannwhitneyu.usigma150(), alglib.mannwhitneyu.usigma225(), alglib.mannwhitneyu.usigma300(), alglib.mannwhitneyu.usigma333(), alglib.mannwhitneyu.usigma367(), and alglib.mannwhitneyu.usigma400().
usigma000() [1/2]
static double alglib.mannwhitneyu.usigma000 (int n1, int n2) inline static private
References alglib.mannwhitneyu.uninterpolate().
Referenced by alglib.mannwhitneyu.usigma().
usigma075() [1/2]
static double alglib.mannwhitneyu.usigma075 (int n1, int n2) inline static private
References alglib.mannwhitneyu.uninterpolate().
Referenced by alglib.mannwhitneyu.usigma().
usigma150() [1/2]
static double alglib.mannwhitneyu.usigma150 (int n1, int n2) inline static private
References alglib.mannwhitneyu.uninterpolate().
Referenced by alglib.mannwhitneyu.usigma().
usigma225() [1/2]
static double alglib.mannwhitneyu.usigma225 (int n1, int n2) inline static private
References alglib.mannwhitneyu.uninterpolate().
Referenced by alglib.mannwhitneyu.usigma().
usigma300() [1/2]
static double alglib.mannwhitneyu.usigma300 (int n1, int n2) inline static private
References alglib.mannwhitneyu.uninterpolate().
Referenced by alglib.mannwhitneyu.usigma().
usigma333() [1/2]
static double alglib.mannwhitneyu.usigma333 (int n1, int n2) inline static private
References alglib.mannwhitneyu.uninterpolate().
Referenced by alglib.mannwhitneyu.usigma().
usigma367() [1/2]
static double alglib.mannwhitneyu.usigma367 (int n1, int n2) inline static private
References alglib.mannwhitneyu.uninterpolate().
Referenced by alglib.mannwhitneyu.usigma().
usigma400() [1/2]
static double alglib.mannwhitneyu.usigma400 (int n1, int n2) inline static private
References alglib.mannwhitneyu.uninterpolate().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n5() [1/2]
static double alglib.mannwhitneyu.utbln5n5 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n6() [1/2]
static double alglib.mannwhitneyu.utbln5n6 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n7() [1/2]
static double alglib.mannwhitneyu.utbln5n7 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n8() [1/2]
static double alglib.mannwhitneyu.utbln5n8 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n9() [1/2]
static double alglib.mannwhitneyu.utbln5n9 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n10() [1/2]
static double alglib.mannwhitneyu.utbln5n10 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n11() [1/2]
static double alglib.mannwhitneyu.utbln5n11 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n12() [1/2]
static double alglib.mannwhitneyu.utbln5n12 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n13() [1/2]
static double alglib.mannwhitneyu.utbln5n13 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n14() [1/2]
static double alglib.mannwhitneyu.utbln5n14 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n15() [1/2]
static double alglib.mannwhitneyu.utbln5n15 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n16() [1/2]
static double alglib.mannwhitneyu.utbln5n16 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n17() [1/2]
static double alglib.mannwhitneyu.utbln5n17 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n18() [1/2]
static double alglib.mannwhitneyu.utbln5n18 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n19() [1/2]
static double alglib.mannwhitneyu.utbln5n19 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n20() [1/2]
static double alglib.mannwhitneyu.utbln5n20 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n21() [1/2]
static double alglib.mannwhitneyu.utbln5n21 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n22() [1/2]
static double alglib.mannwhitneyu.utbln5n22 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n23() [1/2]
static double alglib.mannwhitneyu.utbln5n23 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n24() [1/2]
static double alglib.mannwhitneyu.utbln5n24 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n25() [1/2]
static double alglib.mannwhitneyu.utbln5n25 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n26() [1/2]
static double alglib.mannwhitneyu.utbln5n26 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n27() [1/2]
static double alglib.mannwhitneyu.utbln5n27 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n28() [1/2]
static double alglib.mannwhitneyu.utbln5n28 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n29() [1/2]
static double alglib.mannwhitneyu.utbln5n29 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n30() [1/2]
static double alglib.mannwhitneyu.utbln5n30 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln5n100() [1/2]
static double alglib.mannwhitneyu.utbln5n100 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln6n6() [1/2]
static double alglib.mannwhitneyu.utbln6n6 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln6n7() [1/2]
static double alglib.mannwhitneyu.utbln6n7 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln6n8() [1/2]
static double alglib.mannwhitneyu.utbln6n8 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln6n9() [1/2]
static double alglib.mannwhitneyu.utbln6n9 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln6n10() [1/2]
static double alglib.mannwhitneyu.utbln6n10 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln6n11() [1/2]
static double alglib.mannwhitneyu.utbln6n11 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln6n12() [1/2]
static double alglib.mannwhitneyu.utbln6n12 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln6n13() [1/2]
static double alglib.mannwhitneyu.utbln6n13 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln6n14() [1/2]
static double alglib.mannwhitneyu.utbln6n14 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln6n15() [1/2]
static double alglib.mannwhitneyu.utbln6n15 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln6n30() [1/2]
static double alglib.mannwhitneyu.utbln6n30 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln6n100() [1/2]
static double alglib.mannwhitneyu.utbln6n100 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln7n7() [1/2]
static double alglib.mannwhitneyu.utbln7n7 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln7n8() [1/2]
static double alglib.mannwhitneyu.utbln7n8 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln7n9() [1/2]
static double alglib.mannwhitneyu.utbln7n9 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln7n10() [1/2]
static double alglib.mannwhitneyu.utbln7n10 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln7n11() [1/2]
static double alglib.mannwhitneyu.utbln7n11 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln7n12() [1/2]
static double alglib.mannwhitneyu.utbln7n12 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln7n13() [1/2]
static double alglib.mannwhitneyu.utbln7n13 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln7n14() [1/2]
static double alglib.mannwhitneyu.utbln7n14 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln7n15() [1/2]
static double alglib.mannwhitneyu.utbln7n15 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln7n30() [1/2]
static double alglib.mannwhitneyu.utbln7n30 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln7n100() [1/2]
static double alglib.mannwhitneyu.utbln7n100 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln8n8() [1/2]
static double alglib.mannwhitneyu.utbln8n8 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln8n9() [1/2]
static double alglib.mannwhitneyu.utbln8n9 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln8n10() [1/2]
static double alglib.mannwhitneyu.utbln8n10 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln8n11() [1/2]
static double alglib.mannwhitneyu.utbln8n11 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln8n12() [1/2]
static double alglib.mannwhitneyu.utbln8n12 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln8n13() [1/2]
static double alglib.mannwhitneyu.utbln8n13 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln8n14() [1/2]
static double alglib.mannwhitneyu.utbln8n14 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln8n15() [1/2]
static double alglib.mannwhitneyu.utbln8n15 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln8n30() [1/2]
static double alglib.mannwhitneyu.utbln8n30 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln8n100() [1/2]
static double alglib.mannwhitneyu.utbln8n100 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln9n9() [1/2]
static double alglib.mannwhitneyu.utbln9n9 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln9n10() [1/2]
static double alglib.mannwhitneyu.utbln9n10 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln9n11() [1/2]
static double alglib.mannwhitneyu.utbln9n11 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln9n12() [1/2]
static double alglib.mannwhitneyu.utbln9n12 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln9n13() [1/2]
static double alglib.mannwhitneyu.utbln9n13 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln9n14() [1/2]
static double alglib.mannwhitneyu.utbln9n14 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln9n15() [1/2]
static double alglib.mannwhitneyu.utbln9n15 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln9n30() [1/2]
static double alglib.mannwhitneyu.utbln9n30 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln9n100() [1/2]
static double alglib.mannwhitneyu.utbln9n100 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln10n10() [1/2]
static double alglib.mannwhitneyu.utbln10n10 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln10n11() [1/2]
static double alglib.mannwhitneyu.utbln10n11 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln10n12() [1/2]
static double alglib.mannwhitneyu.utbln10n12 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln10n13() [1/2]
static double alglib.mannwhitneyu.utbln10n13 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln10n14() [1/2]
static double alglib.mannwhitneyu.utbln10n14 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln10n15() [1/2]
static double alglib.mannwhitneyu.utbln10n15 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln10n30() [1/2]
static double alglib.mannwhitneyu.utbln10n30 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln10n100() [1/2]
static double alglib.mannwhitneyu.utbln10n100 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln11n11() [1/2]
static double alglib.mannwhitneyu.utbln11n11 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln11n12() [1/2]
static double alglib.mannwhitneyu.utbln11n12 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln11n13() [1/2]
static double alglib.mannwhitneyu.utbln11n13 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln11n14() [1/2]
static double alglib.mannwhitneyu.utbln11n14 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln11n15() [1/2]
static double alglib.mannwhitneyu.utbln11n15 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln11n30() [1/2]
static double alglib.mannwhitneyu.utbln11n30 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln11n100() [1/2]
static double alglib.mannwhitneyu.utbln11n100 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln12n12() [1/2]
static double alglib.mannwhitneyu.utbln12n12 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln12n13() [1/2]
static double alglib.mannwhitneyu.utbln12n13 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln12n14() [1/2]
static double alglib.mannwhitneyu.utbln12n14 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln12n15() [1/2]
static double alglib.mannwhitneyu.utbln12n15 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln12n30() [1/2]
static double alglib.mannwhitneyu.utbln12n30 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln12n100() [1/2]
static double alglib.mannwhitneyu.utbln12n100 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln13n13() [1/2]
static double alglib.mannwhitneyu.utbln13n13 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln13n14() [1/2]
static double alglib.mannwhitneyu.utbln13n14 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln13n15() [1/2]
static double alglib.mannwhitneyu.utbln13n15 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln13n30() [1/2]
static double alglib.mannwhitneyu.utbln13n30 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln13n100() [1/2]
static double alglib.mannwhitneyu.utbln13n100 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln14n14() [1/2]
static double alglib.mannwhitneyu.utbln14n14 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln14n15() [1/2]
static double alglib.mannwhitneyu.utbln14n15 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln14n30() [1/2]
static double alglib.mannwhitneyu.utbln14n30 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
utbln14n100() [1/2]
static double alglib.mannwhitneyu.utbln14n100 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
Referenced by alglib.mannwhitneyu.usigma().
usigma() [1/2]
static double alglib.mannwhitneyu.usigma (double s, int n1, int n2) inline static private
References alglib.mannwhitneyu.uninterpolate(), alglib.mannwhitneyu.usigma000(), alglib.mannwhitneyu.usigma075(), alglib.mannwhitneyu.usigma150(), alglib.mannwhitneyu.usigma225(), alglib.mannwhitneyu.usigma300(), alglib.mannwhitneyu.usigma333(), alglib.mannwhitneyu.usigma367(), alglib.mannwhitneyu.usigma400(), alglib.mannwhitneyu.utbln10n10(), alglib.mannwhitneyu.utbln10n100(), alglib.mannwhitneyu.utbln10n11(), alglib.mannwhitneyu.utbln10n12(), alglib.mannwhitneyu.utbln10n13(), alglib.mannwhitneyu.utbln10n14(), alglib.mannwhitneyu.utbln10n15(), alglib.mannwhitneyu.utbln10n30(), alglib.mannwhitneyu.utbln11n100(), alglib.mannwhitneyu.utbln11n11(), alglib.mannwhitneyu.utbln11n12(), alglib.mannwhitneyu.utbln11n13(), alglib.mannwhitneyu.utbln11n14(), alglib.mannwhitneyu.utbln11n15(), alglib.mannwhitneyu.utbln11n30(), alglib.mannwhitneyu.utbln12n100(), alglib.mannwhitneyu.utbln12n12(), alglib.mannwhitneyu.utbln12n13(), alglib.mannwhitneyu.utbln12n14(), alglib.mannwhitneyu.utbln12n15(), alglib.mannwhitneyu.utbln12n30(), alglib.mannwhitneyu.utbln13n100(), alglib.mannwhitneyu.utbln13n13(), alglib.mannwhitneyu.utbln13n14(), alglib.mannwhitneyu.utbln13n15(), alglib.mannwhitneyu.utbln13n30(), alglib.mannwhitneyu.utbln14n100(), alglib.mannwhitneyu.utbln14n14(), alglib.mannwhitneyu.utbln14n15(), alglib.mannwhitneyu.utbln14n30(), alglib.mannwhitneyu.utbln5n10(), alglib.mannwhitneyu.utbln5n100(), alglib.mannwhitneyu.utbln5n11(), alglib.mannwhitneyu.utbln5n12(), alglib.mannwhitneyu.utbln5n13(), alglib.mannwhitneyu.utbln5n14(), alglib.mannwhitneyu.utbln5n15(), alglib.mannwhitneyu.utbln5n16(), alglib.mannwhitneyu.utbln5n17(), alglib.mannwhitneyu.utbln5n18(), alglib.mannwhitneyu.utbln5n19(), alglib.mannwhitneyu.utbln5n20(), alglib.mannwhitneyu.utbln5n21(), alglib.mannwhitneyu.utbln5n22(), alglib.mannwhitneyu.utbln5n23(), alglib.mannwhitneyu.utbln5n24(), alglib.mannwhitneyu.utbln5n25(), alglib.mannwhitneyu.utbln5n26(), alglib.mannwhitneyu.utbln5n27(), alglib.mannwhitneyu.utbln5n28(), alglib.mannwhitneyu.utbln5n29(), alglib.mannwhitneyu.utbln5n30(), alglib.mannwhitneyu.utbln5n5(), alglib.mannwhitneyu.utbln5n6(), alglib.mannwhitneyu.utbln5n7(), alglib.mannwhitneyu.utbln5n8(), alglib.mannwhitneyu.utbln5n9(), alglib.mannwhitneyu.utbln6n10(), alglib.mannwhitneyu.utbln6n100(), alglib.mannwhitneyu.utbln6n11(), alglib.mannwhitneyu.utbln6n12(), alglib.mannwhitneyu.utbln6n13(), alglib.mannwhitneyu.utbln6n14(), alglib.mannwhitneyu.utbln6n15(), alglib.mannwhitneyu.utbln6n30(), alglib.mannwhitneyu.utbln6n6(), alglib.mannwhitneyu.utbln6n7(), alglib.mannwhitneyu.utbln6n8(), alglib.mannwhitneyu.utbln6n9(), alglib.mannwhitneyu.utbln7n10(), alglib.mannwhitneyu.utbln7n100(), alglib.mannwhitneyu.utbln7n11(), alglib.mannwhitneyu.utbln7n12(), alglib.mannwhitneyu.utbln7n13(), alglib.mannwhitneyu.utbln7n14(), alglib.mannwhitneyu.utbln7n15(), alglib.mannwhitneyu.utbln7n30(), alglib.mannwhitneyu.utbln7n7(), alglib.mannwhitneyu.utbln7n8(), alglib.mannwhitneyu.utbln7n9(), alglib.mannwhitneyu.utbln8n10(), alglib.mannwhitneyu.utbln8n100(), alglib.mannwhitneyu.utbln8n11(), alglib.mannwhitneyu.utbln8n12(), alglib.mannwhitneyu.utbln8n13(), alglib.mannwhitneyu.utbln8n14(), alglib.mannwhitneyu.utbln8n15(), alglib.mannwhitneyu.utbln8n30(), alglib.mannwhitneyu.utbln8n8(), alglib.mannwhitneyu.utbln8n9(), alglib.mannwhitneyu.utbln9n10(), alglib.mannwhitneyu.utbln9n100(), alglib.mannwhitneyu.utbln9n11(), alglib.mannwhitneyu.utbln9n12(), alglib.mannwhitneyu.utbln9n13(), alglib.mannwhitneyu.utbln9n14(), alglib.mannwhitneyu.utbln9n15(), alglib.mannwhitneyu.utbln9n30(), and alglib.mannwhitneyu.utbln9n9().
Referenced by alglib.mannwhitneyu.mannwhitneyutest().
mannwhitneyutest() [2/2]
static void alglib.mannwhitneyu.mannwhitneyutest (double[] x, int n, double[] y, int m, ref double bothtails, ref double lefttail, ref double righttail) inline static
References alglib.math.sqr(), and alglib.mannwhitneyu.usigma().
ucheb() [2/2]
static void alglib.mannwhitneyu.ucheb (double x, double c, ref double tj, ref double tj1, ref double r) inline static private
uninterpolate() [2/2]
static double alglib.mannwhitneyu.uninterpolate (double p1, double p2, double p3, int n) inline static private
usigma000() [2/2]
static double alglib.mannwhitneyu.usigma000 (int n1, int n2) inline static private
References alglib.mannwhitneyu.uninterpolate().
usigma075() [2/2]
static double alglib.mannwhitneyu.usigma075 (int n1, int n2) inline static private
References alglib.mannwhitneyu.uninterpolate().
usigma150() [2/2]
static double alglib.mannwhitneyu.usigma150 (int n1, int n2) inline static private
References alglib.mannwhitneyu.uninterpolate().
usigma225() [2/2]
static double alglib.mannwhitneyu.usigma225 (int n1, int n2) inline static private
References alglib.mannwhitneyu.uninterpolate().
usigma300() [2/2]
static double alglib.mannwhitneyu.usigma300 (int n1, int n2) inline static private
References alglib.mannwhitneyu.uninterpolate().
usigma333() [2/2]
static double alglib.mannwhitneyu.usigma333 (int n1, int n2) inline static private
References alglib.mannwhitneyu.uninterpolate().
usigma367() [2/2]
static double alglib.mannwhitneyu.usigma367 (int n1, int n2) inline static private
References alglib.mannwhitneyu.uninterpolate().
usigma400() [2/2]
static double alglib.mannwhitneyu.usigma400 (int n1, int n2) inline static private
References alglib.mannwhitneyu.uninterpolate().
utbln5n5() [2/2]
static double alglib.mannwhitneyu.utbln5n5 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n6() [2/2]
static double alglib.mannwhitneyu.utbln5n6 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n7() [2/2]
static double alglib.mannwhitneyu.utbln5n7 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n8() [2/2]
static double alglib.mannwhitneyu.utbln5n8 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n9() [2/2]
static double alglib.mannwhitneyu.utbln5n9 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n10() [2/2]
static double alglib.mannwhitneyu.utbln5n10 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n11() [2/2]
static double alglib.mannwhitneyu.utbln5n11 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n12() [2/2]
static double alglib.mannwhitneyu.utbln5n12 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n13() [2/2]
static double alglib.mannwhitneyu.utbln5n13 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n14() [2/2]
static double alglib.mannwhitneyu.utbln5n14 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n15() [2/2]
static double alglib.mannwhitneyu.utbln5n15 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n16() [2/2]
static double alglib.mannwhitneyu.utbln5n16 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n17() [2/2]
static double alglib.mannwhitneyu.utbln5n17 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n18() [2/2]
static double alglib.mannwhitneyu.utbln5n18 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n19() [2/2]
static double alglib.mannwhitneyu.utbln5n19 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n20() [2/2]
static double alglib.mannwhitneyu.utbln5n20 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n21() [2/2]
static double alglib.mannwhitneyu.utbln5n21 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n22() [2/2]
static double alglib.mannwhitneyu.utbln5n22 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n23() [2/2]
static double alglib.mannwhitneyu.utbln5n23 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n24() [2/2]
static double alglib.mannwhitneyu.utbln5n24 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n25() [2/2]
static double alglib.mannwhitneyu.utbln5n25 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n26() [2/2]
static double alglib.mannwhitneyu.utbln5n26 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n27() [2/2]
static double alglib.mannwhitneyu.utbln5n27 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n28() [2/2]
static double alglib.mannwhitneyu.utbln5n28 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n29() [2/2]
static double alglib.mannwhitneyu.utbln5n29 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n30() [2/2]
static double alglib.mannwhitneyu.utbln5n30 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln5n100() [2/2]
static double alglib.mannwhitneyu.utbln5n100 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln6n6() [2/2]
static double alglib.mannwhitneyu.utbln6n6 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln6n7() [2/2]
static double alglib.mannwhitneyu.utbln6n7 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln6n8() [2/2]
static double alglib.mannwhitneyu.utbln6n8 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln6n9() [2/2]
static double alglib.mannwhitneyu.utbln6n9 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln6n10() [2/2]
static double alglib.mannwhitneyu.utbln6n10 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln6n11() [2/2]
static double alglib.mannwhitneyu.utbln6n11 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln6n12() [2/2]
static double alglib.mannwhitneyu.utbln6n12 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln6n13() [2/2]
static double alglib.mannwhitneyu.utbln6n13 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln6n14() [2/2]
static double alglib.mannwhitneyu.utbln6n14 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln6n15() [2/2]
static double alglib.mannwhitneyu.utbln6n15 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln6n30() [2/2]
static double alglib.mannwhitneyu.utbln6n30 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln6n100() [2/2]
static double alglib.mannwhitneyu.utbln6n100 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln7n7() [2/2]
static double alglib.mannwhitneyu.utbln7n7 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln7n8() [2/2]
static double alglib.mannwhitneyu.utbln7n8 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln7n9() [2/2]
static double alglib.mannwhitneyu.utbln7n9 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln7n10() [2/2]
static double alglib.mannwhitneyu.utbln7n10 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln7n11() [2/2]
static double alglib.mannwhitneyu.utbln7n11 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln7n12() [2/2]
static double alglib.mannwhitneyu.utbln7n12 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln7n13() [2/2]
static double alglib.mannwhitneyu.utbln7n13 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln7n14() [2/2]
static double alglib.mannwhitneyu.utbln7n14 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln7n15() [2/2]
static double alglib.mannwhitneyu.utbln7n15 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln7n30() [2/2]
static double alglib.mannwhitneyu.utbln7n30 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln7n100() [2/2]
static double alglib.mannwhitneyu.utbln7n100 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln8n8() [2/2]
static double alglib.mannwhitneyu.utbln8n8 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln8n9() [2/2]
static double alglib.mannwhitneyu.utbln8n9 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln8n10() [2/2]
static double alglib.mannwhitneyu.utbln8n10 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln8n11() [2/2]
static double alglib.mannwhitneyu.utbln8n11 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln8n12() [2/2]
static double alglib.mannwhitneyu.utbln8n12 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln8n13() [2/2]
static double alglib.mannwhitneyu.utbln8n13 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln8n14() [2/2]
static double alglib.mannwhitneyu.utbln8n14 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln8n15() [2/2]
static double alglib.mannwhitneyu.utbln8n15 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln8n30() [2/2]
static double alglib.mannwhitneyu.utbln8n30 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln8n100() [2/2]
static double alglib.mannwhitneyu.utbln8n100 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln9n9() [2/2]
static double alglib.mannwhitneyu.utbln9n9 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln9n10() [2/2]
static double alglib.mannwhitneyu.utbln9n10 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln9n11() [2/2]
static double alglib.mannwhitneyu.utbln9n11 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln9n12() [2/2]
static double alglib.mannwhitneyu.utbln9n12 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln9n13() [2/2]
static double alglib.mannwhitneyu.utbln9n13 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln9n14() [2/2]
static double alglib.mannwhitneyu.utbln9n14 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln9n15() [2/2]
static double alglib.mannwhitneyu.utbln9n15 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln9n30() [2/2]
static double alglib.mannwhitneyu.utbln9n30 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln9n100() [2/2]
static double alglib.mannwhitneyu.utbln9n100 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln10n10() [2/2]
static double alglib.mannwhitneyu.utbln10n10 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln10n11() [2/2]
static double alglib.mannwhitneyu.utbln10n11 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln10n12() [2/2]
static double alglib.mannwhitneyu.utbln10n12 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln10n13() [2/2]
static double alglib.mannwhitneyu.utbln10n13 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln10n14() [2/2]
static double alglib.mannwhitneyu.utbln10n14 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln10n15() [2/2]
static double alglib.mannwhitneyu.utbln10n15 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln10n30() [2/2]
static double alglib.mannwhitneyu.utbln10n30 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln10n100() [2/2]
static double alglib.mannwhitneyu.utbln10n100 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln11n11() [2/2]
static double alglib.mannwhitneyu.utbln11n11 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln11n12() [2/2]
static double alglib.mannwhitneyu.utbln11n12 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln11n13() [2/2]
static double alglib.mannwhitneyu.utbln11n13 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln11n14() [2/2]
static double alglib.mannwhitneyu.utbln11n14 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln11n15() [2/2]
static double alglib.mannwhitneyu.utbln11n15 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln11n30() [2/2]
static double alglib.mannwhitneyu.utbln11n30 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln11n100() [2/2]
static double alglib.mannwhitneyu.utbln11n100 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln12n12() [2/2]
static double alglib.mannwhitneyu.utbln12n12 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln12n13() [2/2]
static double alglib.mannwhitneyu.utbln12n13 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln12n14() [2/2]
static double alglib.mannwhitneyu.utbln12n14 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln12n15() [2/2]
static double alglib.mannwhitneyu.utbln12n15 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln12n30() [2/2]
static double alglib.mannwhitneyu.utbln12n30 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln12n100() [2/2]
static double alglib.mannwhitneyu.utbln12n100 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln13n13() [2/2]
static double alglib.mannwhitneyu.utbln13n13 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln13n14() [2/2]
static double alglib.mannwhitneyu.utbln13n14 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln13n15() [2/2]
static double alglib.mannwhitneyu.utbln13n15 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln13n30() [2/2]
static double alglib.mannwhitneyu.utbln13n30 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln13n100() [2/2]
static double alglib.mannwhitneyu.utbln13n100 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln14n14() [2/2]
static double alglib.mannwhitneyu.utbln14n14 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln14n15() [2/2]
static double alglib.mannwhitneyu.utbln14n15 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln14n30() [2/2]
static double alglib.mannwhitneyu.utbln14n30 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
utbln14n100() [2/2]
static double alglib.mannwhitneyu.utbln14n100 (double s) inline static private
References alglib.mannwhitneyu.ucheb().
usigma() [2/2]
static double alglib.mannwhitneyu.usigma (double s, int n1, int n2) inline static private
References alglib.mannwhitneyu.uninterpolate(), alglib.mannwhitneyu.usigma000(), alglib.mannwhitneyu.usigma075(), alglib.mannwhitneyu.usigma150(), alglib.mannwhitneyu.usigma225(), alglib.mannwhitneyu.usigma300(), alglib.mannwhitneyu.usigma333(), alglib.mannwhitneyu.usigma367(), alglib.mannwhitneyu.usigma400(), alglib.mannwhitneyu.utbln10n10(), alglib.mannwhitneyu.utbln10n100(), alglib.mannwhitneyu.utbln10n11(), alglib.mannwhitneyu.utbln10n12(), alglib.mannwhitneyu.utbln10n13(), alglib.mannwhitneyu.utbln10n14(), alglib.mannwhitneyu.utbln10n15(), alglib.mannwhitneyu.utbln10n30(), alglib.mannwhitneyu.utbln11n100(), alglib.mannwhitneyu.utbln11n11(), alglib.mannwhitneyu.utbln11n12(), alglib.mannwhitneyu.utbln11n13(), alglib.mannwhitneyu.utbln11n14(), alglib.mannwhitneyu.utbln11n15(), alglib.mannwhitneyu.utbln11n30(), alglib.mannwhitneyu.utbln12n100(), alglib.mannwhitneyu.utbln12n12(), alglib.mannwhitneyu.utbln12n13(), alglib.mannwhitneyu.utbln12n14(), alglib.mannwhitneyu.utbln12n15(), alglib.mannwhitneyu.utbln12n30(), alglib.mannwhitneyu.utbln13n100(), alglib.mannwhitneyu.utbln13n13(), alglib.mannwhitneyu.utbln13n14(), alglib.mannwhitneyu.utbln13n15(), alglib.mannwhitneyu.utbln13n30(), alglib.mannwhitneyu.utbln14n100(), alglib.mannwhitneyu.utbln14n14(), alglib.mannwhitneyu.utbln14n15(), alglib.mannwhitneyu.utbln14n30(), alglib.mannwhitneyu.utbln5n10(), alglib.mannwhitneyu.utbln5n100(), alglib.mannwhitneyu.utbln5n11(), alglib.mannwhitneyu.utbln5n12(), alglib.mannwhitneyu.utbln5n13(), alglib.mannwhitneyu.utbln5n14(), alglib.mannwhitneyu.utbln5n15(), alglib.mannwhitneyu.utbln5n16(), alglib.mannwhitneyu.utbln5n17(), alglib.mannwhitneyu.utbln5n18(), alglib.mannwhitneyu.utbln5n19(), alglib.mannwhitneyu.utbln5n20(), alglib.mannwhitneyu.utbln5n21(), alglib.mannwhitneyu.utbln5n22(), alglib.mannwhitneyu.utbln5n23(), alglib.mannwhitneyu.utbln5n24(), alglib.mannwhitneyu.utbln5n25(), alglib.mannwhitneyu.utbln5n26(), alglib.mannwhitneyu.utbln5n27(), alglib.mannwhitneyu.utbln5n28(), alglib.mannwhitneyu.utbln5n29(), alglib.mannwhitneyu.utbln5n30(), alglib.mannwhitneyu.utbln5n5(), alglib.mannwhitneyu.utbln5n6(), alglib.mannwhitneyu.utbln5n7(), alglib.mannwhitneyu.utbln5n8(), alglib.mannwhitneyu.utbln5n9(), alglib.mannwhitneyu.utbln6n10(), alglib.mannwhitneyu.utbln6n100(), alglib.mannwhitneyu.utbln6n11(), alglib.mannwhitneyu.utbln6n12(), alglib.mannwhitneyu.utbln6n13(), alglib.mannwhitneyu.utbln6n14(), alglib.mannwhitneyu.utbln6n15(), alglib.mannwhitneyu.utbln6n30(), alglib.mannwhitneyu.utbln6n6(), alglib.mannwhitneyu.utbln6n7(), alglib.mannwhitneyu.utbln6n8(), alglib.mannwhitneyu.utbln6n9(), alglib.mannwhitneyu.utbln7n10(), alglib.mannwhitneyu.utbln7n100(), alglib.mannwhitneyu.utbln7n11(), alglib.mannwhitneyu.utbln7n12(), alglib.mannwhitneyu.utbln7n13(), alglib.mannwhitneyu.utbln7n14(), alglib.mannwhitneyu.utbln7n15(), alglib.mannwhitneyu.utbln7n30(), alglib.mannwhitneyu.utbln7n7(), alglib.mannwhitneyu.utbln7n8(), alglib.mannwhitneyu.utbln7n9(), alglib.mannwhitneyu.utbln8n10(), alglib.mannwhitneyu.utbln8n100(), alglib.mannwhitneyu.utbln8n11(), alglib.mannwhitneyu.utbln8n12(), alglib.mannwhitneyu.utbln8n13(), alglib.mannwhitneyu.utbln8n14(), alglib.mannwhitneyu.utbln8n15(), alglib.mannwhitneyu.utbln8n30(), alglib.mannwhitneyu.utbln8n8(), alglib.mannwhitneyu.utbln8n9(), alglib.mannwhitneyu.utbln9n10(), alglib.mannwhitneyu.utbln9n100(), alglib.mannwhitneyu.utbln9n11(), alglib.mannwhitneyu.utbln9n12(), alglib.mannwhitneyu.utbln9n13(), alglib.mannwhitneyu.utbln9n14(), alglib.mannwhitneyu.utbln9n15(), alglib.mannwhitneyu.utbln9n30(), and alglib.mannwhitneyu.utbln9n9().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/statistics.cs