Doc: IGLib EXTENDED: NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests Class Reference
NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests Class Reference
A series of unit tests to ensure that the type extensions in the portable framework behave the same as their counterparts in the full framework
Public Member Functions
void CanCallTypeInfoOnAllPlatforms ()
void CanGetGenericArguments ()
void CanGetConstructors ()
void CanGetContructorWithParams (Type paramType)
void CanGetGenericConstructor ()
void IsAssignableFromTest ()
void IsInstanceOfTypeTest ()
void CanGetInterfaces (Type type, Type @interface)
void CanGetMember (Type type, string name)
void DoesNotGetStaticMemberOnBaseClass ()
void DoesNotGetPrivateMemberOnBaseClass ()
void CanGetPublicField ()
void DoesNotGetPrivateField ()
void CanGetProperty (Type type, string name)
void DoesNotGetStaticPropertyOnBase ()
void CanGetPropertyWithBindingFlags (Type type, string name, BindingFlags flags, bool shouldFind)
void CanGetMethodByName (Type type, string name, bool shouldFind)
void CanGetMethodByNameAndArgs (Type type, string name, Type[] args, bool shouldFind)
void CanGetMethodByNameAndBindingFlags (Type type, string name, BindingFlags flags, bool shouldFind)
void CanGetStaticMethodsOnBase (BindingFlags flags)
void DoesNotFindStaticMethodsOnBase (BindingFlags flags)
void CanGetGetMethod (string name, bool nonPublic, bool shouldFind)
Static Private Attributes
const bool ONLY_ON_CF = false
Detailed Description
A series of unit tests to ensure that the type extensions in the portable framework behave the same as their counterparts in the full framework
Member Function Documentation
CanCallTypeInfoOnAllPlatforms()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanCallTypeInfoOnAllPlatforms () inline
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
CanGetGenericArguments()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetGenericArguments () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
CanGetConstructors()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetConstructors () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.False, NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
CanGetContructorWithParams()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetContructorWithParams (Type paramType) inline
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
CanGetGenericConstructor()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetGenericConstructor () inline
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
IsAssignableFromTest()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.IsAssignableFromTest () inline
References NUnit.Framework.Is.False, NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
IsInstanceOfTypeTest()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.IsInstanceOfTypeTest () inline
References NUnit.Framework.Is.False, NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
CanGetInterfaces()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetInterfaces (Type type, Type @ interface) inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
CanGetMember()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetMember (Type type, string name) inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
DoesNotGetStaticMemberOnBaseClass()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.DoesNotGetStaticMemberOnBaseClass () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
DoesNotGetPrivateMemberOnBaseClass()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.DoesNotGetPrivateMemberOnBaseClass () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
CanGetPublicField()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetPublicField () inline
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
DoesNotGetPrivateField()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.DoesNotGetPrivateField () inline
References NUnit.Framework.Is.Null, and NUnit.Framework.Assert.That().
CanGetProperty()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetProperty (Type type, string name) inline
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
DoesNotGetStaticPropertyOnBase()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.DoesNotGetStaticPropertyOnBase () inline
References NUnit.Framework.Is.Null, and NUnit.Framework.Assert.That().
CanGetPropertyWithBindingFlags()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetPropertyWithBindingFlags (Type type, string name, BindingFlags flags, bool shouldFind) inline
References NUnit.Framework.Assert.AreEqual().
CanGetMethodByName()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetMethodByName (Type type, string name, bool shouldFind) inline
References NUnit.Framework.Assert.AreEqual().
CanGetMethodByNameAndArgs()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetMethodByNameAndArgs (Type type, string name, Type[] args, bool shouldFind) inline
References NUnit.Framework.Assert.AreEqual().
CanGetMethodByNameAndBindingFlags()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetMethodByNameAndBindingFlags (Type type, string name, BindingFlags flags, bool shouldFind) inline
References NUnit.Framework.Assert.AreEqual().
CanGetStaticMethodsOnBase()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetStaticMethodsOnBase (BindingFlags flags) inline
References NUnit.Framework.Assert.Fail(), and NUnit.Framework.Assert.Pass().
DoesNotFindStaticMethodsOnBase()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.DoesNotFindStaticMethodsOnBase (BindingFlags flags) inline
References NUnit.Framework.Assert.Fail().
CanGetGetMethod()
void NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.CanGetGetMethod (string name, bool nonPublic, bool shouldFind) inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
Member Data Documentation
ONLY_ON_CF
const bool NUnit.Framework.Tests.Compatibility.ReflectionExtensionsTests.ONLY_ON_CF = false static private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Compatibility/ReflectionExtensionsTests.cs