Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAEDA Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAEDA Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAEDA (DCOPY dcopy, DGEMV dgemv, DROT drot, XERBLA xerbla)
DLAEDA ()
void Run (int N, int TLVLS, int CURLVL, int CURPBM, int[] PRMPTR, int offset_prmptr, int[] PERM, int offset_perm, int[] GIVPTR, int offset_givptr, int[] GIVCOL, int offset_givcol, double[] GIVNUM, int offset_givnum, double[] Q, int offset_q, int[] QPTR, int offset_qptr, ref double[] Z, int offset_z, ref double[] ZTEMP, int offset_ztemp, ref int INFO)
Private Attributes
DCOPY _dcopy
DGEMV _dgemv
DROT _drot
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E0
const double HALF = 0.5E0
const double ONE = 1.0E0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAEDA computes the Z vector corresponding to the merge step in the CURLVLth step of the merge process with TLVLS steps for the CURPBMth problem.
/summary>
Constructor & Destructor Documentation
DLAEDA() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAEDA.DLAEDA (DCOPY dcopy, DGEMV dgemv, DROT drot, XERBLA xerbla) inline
DLAEDA() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAEDA.DLAEDA () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAEDA.Run (int N, int TLVLS, int CURLVL, int CURPBM, int[] PRMPTR, int offset_prmptr, int[] PERM, int offset_perm, int[] GIVPTR, int offset_givptr, int[] GIVCOL, int offset_givcol, double[] GIVNUM, int offset_givnum, double[] Q, int offset_q, int[] QPTR, int offset_qptr, ref double[] Z, int offset_z, ref double[] ZTEMP, int offset_ztemp, ref int INFO) inline
Purpose
DLAEDA computes the Z vector corresponding to the merge step in the CURLVLth step of the merge process with TLVLS steps for the CURPBMth problem.
/summary>
Parameters
N (input) INTEGER The dimension of the symmetric tridiagonal matrix. N .GE. 0. /param>
Parameters
TLVLS (input) INTEGER The total number of merging levels in the overall divide and conquer tree. /param>
Parameters
CURLVL (input) INTEGER The current level in the overall merge routine, 0 .LE. curlvl .LE. tlvls. /param>
Parameters
CURPBM (input) INTEGER The current problem in the current level in the overall merge routine (counting from upper left to lower right). /param>
Parameters
PRMPTR (input) INTEGER array, dimension (N lg N) Contains a list of pointers which indicate where in PERM a level's permutation is stored. PRMPTR(i+1) - PRMPTR(i) indicates the size of the permutation and incidentally the size of the full, non-deflated problem. /param>
Parameters
PERM (input) INTEGER array, dimension (N lg N) Contains the permutations (from deflation and sorting) to be applied to each eigenblock. /param>
Parameters
GIVPTR (input) INTEGER array, dimension (N lg N) Contains a list of pointers which indicate where in GIVCOL a level's Givens rotations are stored. GIVPTR(i+1) - GIVPTR(i) indicates the number of Givens rotations. /param>
Parameters
GIVCOL (input) INTEGER array, dimension (2, N lg N) Each pair of numbers indicates a pair of columns to take place in a Givens rotation. /param>
Parameters
GIVNUM (input) DOUBLE PRECISION array, dimension (2, N lg N) Each number indicates the S value to be used in the corresponding Givens rotation. /param>
Parameters
Q (input) DOUBLE PRECISION array, dimension (N**2) Contains the square eigenblocks from previous levels, the starting positions for blocks are given by QPTR. /param>
Parameters
QPTR (input) INTEGER array, dimension (N+2) Contains a list of pointers which indicate where in Q an eigenblock is stored. SQRT(QPTR(i+1) - QPTR(i)) indicates the size of the block. /param>
Parameters
Z (output) DOUBLE PRECISION array, dimension (N) On output this vector contains the updating vector (the last row of the first sub-eigenvector matrix and the first row of the second sub-eigenvector matrix). /param>
Parameters
ZTEMP (workspace) DOUBLE PRECISION array, dimension (N) /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLAEDA.HALF, DotNumerics.LinearAlgebra.CSLapack.DLAEDA.ONE, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DROT.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAEDA.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED7.Run().
Member Data Documentation
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLAEDA._dcopy private
_dgemv
DGEMV DotNumerics.LinearAlgebra.CSLapack.DLAEDA._dgemv private
_drot
DROT DotNumerics.LinearAlgebra.CSLapack.DLAEDA._drot private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLAEDA._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAEDA.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAEDA.Run().
HALF
const double DotNumerics.LinearAlgebra.CSLapack.DLAEDA.HALF = 0.5E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAEDA.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAEDA.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAEDA.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlaeda.cs