Doc: IGLib EXTENDED: NUnit.Framework.Internal.Execution.CountdownEvent Class Reference
NUnit.Framework.Internal.Execution.CountdownEvent Class Reference
A simplified implementation of .NET 4 CountdownEvent for use in earlier versions of .NET. Only the methods used by NUnit are implemented.
Public Member Functions
CountdownEvent (int initialCount)
Construct a CountdownEvent
void Signal ()
Decrement the count by one
void Wait ()
Block the thread until the count reaches zero
Properties
int InitialCount [get]
Gets the initial count established for the CountdownEvent
int CurrentCount [get]
Gets the current count remaining for the CountdownEvent
Private Attributes
int _initialCount
int _remainingCount
object _lock = new object()
ManualResetEvent _event = new ManualResetEvent(false)
Detailed Description
A simplified implementation of .NET 4 CountdownEvent for use in earlier versions of .NET. Only the methods used by NUnit are implemented.
Constructor & Destructor Documentation
CountdownEvent()
NUnit.Framework.Internal.Execution.CountdownEvent.CountdownEvent (int initialCount) inline
Construct a CountdownEvent
Parameters
initialCount The initial count
References NUnit.Framework.Internal.Execution.CountdownEvent._initialCount, and NUnit.Framework.Internal.Execution.CountdownEvent._remainingCount.
Member Function Documentation
Signal()
void NUnit.Framework.Internal.Execution.CountdownEvent.Signal () inline
Decrement the count by one
References NUnit.Framework.Internal.Execution.CountdownEvent._event, NUnit.Framework.Internal.Execution.CountdownEvent._lock, and NUnit.Framework.Internal.Execution.CountdownEvent._remainingCount.
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.CountDownChildTest().
Wait()
void NUnit.Framework.Internal.Execution.CountdownEvent.Wait () inline
Block the thread until the count reaches zero
References NUnit.Framework.Internal.Execution.CountdownEvent._event.
Member Data Documentation
_initialCount
int NUnit.Framework.Internal.Execution.CountdownEvent._initialCount private
Referenced by NUnit.Framework.Internal.Execution.CountdownEvent.CountdownEvent().
_remainingCount
int NUnit.Framework.Internal.Execution.CountdownEvent._remainingCount private
Referenced by NUnit.Framework.Internal.Execution.CountdownEvent.CountdownEvent(), and NUnit.Framework.Internal.Execution.CountdownEvent.Signal().
_lock
object NUnit.Framework.Internal.Execution.CountdownEvent._lock = new object() private
Referenced by NUnit.Framework.Internal.Execution.CountdownEvent.Signal().
_event
ManualResetEvent NUnit.Framework.Internal.Execution.CountdownEvent._event = new ManualResetEvent(false) private
Referenced by NUnit.Framework.Internal.Execution.CountdownEvent.Signal(), and NUnit.Framework.Internal.Execution.CountdownEvent.Wait().
Property Documentation
InitialCount
int NUnit.Framework.Internal.Execution.CountdownEvent.InitialCount get
Gets the initial count established for the CountdownEvent
CurrentCount
int NUnit.Framework.Internal.Execution.CountdownEvent.CurrentCount get
Gets the current count remaining for the CountdownEvent
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.CountDownChildTest().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/Execution/CountdownEvent.cs