Doc: IGLib EXTENDED: alglib.testlinregunit Class Reference
alglib.testlinregunit Class Reference
Static Public Member Functions
static bool testlinreg (bool silent)
static bool testlinreg (bool silent)
static bool _pexec_testlinreg (bool silent)
Static Private Member Functions
static void generaterandomtask (double xl, double xr, bool randomx, double ymin, double ymax, double smin, double smax, int n, ref double[,] xy, ref double[] s)
static void generatetask (double a, double b, double xl, double xr, bool randomx, double smin, double smax, int n, ref double[,] xy, ref double[] s)
static void filltaskwithy (double a, double b, int n, ref double[,] xy, ref double[] s)
static double generatenormal (double mean, double sigma)
static void calculatemv (double[] x, int n, ref double mean, ref double means, ref double stddev, ref double stddevs)
static void unsetlr (linreg.linearmodel lr)
static void generaterandomtask (double xl, double xr, bool randomx, double ymin, double ymax, double smin, double smax, int n, ref double[,] xy, ref double[] s)
static void generatetask (double a, double b, double xl, double xr, bool randomx, double smin, double smax, int n, ref double[,] xy, ref double[] s)
static void filltaskwithy (double a, double b, int n, ref double[,] xy, ref double[] s)
static double generatenormal (double mean, double sigma)
static void calculatemv (double[] x, int n, ref double mean, ref double means, ref double stddev, ref double stddevs)
static void unsetlr (linreg.linearmodel lr)
Member Function Documentation
testlinreg() [1/2]
static bool alglib.testlinregunit.testlinreg (bool silent) inline static
References alglib.ap.assert(), alglib.testlinregunit.calculatemv(), alglib.testlinregunit.filltaskwithy(), alglib.testlinregunit.generatenormal(), alglib.testlinregunit.generaterandomtask(), alglib.testlinregunit.generatetask(), alglib.linreg.lravgerror(), alglib.linreg.lravgrelerror(), alglib.linreg.lrbuild(), alglib.linreg.lrbuilds(), alglib.linreg.lrbuildzs(), alglib.linreg.lrcopy(), alglib.linreg.lrline(), alglib.linreg.lrlines(), alglib.linreg.lrpack(), alglib.linreg.lrprocess(), alglib.linreg.lrrmserror(), alglib.linreg.lrunpack(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.math.sqr(), and alglib.testlinregunit.unsetlr().
Referenced by alglib.testlinregunit._pexec_testlinreg(), and _Test.Main().
generaterandomtask() [1/2]
static void alglib.testlinregunit.generaterandomtask (double xl, double xr, bool randomx, double ymin, double ymax, double smin, double smax, int n, ref double xy[,], ref double[] s) inline static private
References alglib.math.randomreal().
Referenced by alglib.testlinregunit.testlinreg().
generatetask() [1/2]
static void alglib.testlinregunit.generatetask (double a, double b, double xl, double xr, bool randomx, double smin, double smax, int n, ref double xy[,], ref double[] s) inline static private
References alglib.testlinregunit.generatenormal(), and alglib.math.randomreal().
Referenced by alglib.testlinregunit.testlinreg().
filltaskwithy() [1/2]
static void alglib.testlinregunit.filltaskwithy (double a, double b, int n, ref double xy[,], ref double[] s) inline static private
References alglib.testlinregunit.generatenormal().
Referenced by alglib.testlinregunit.testlinreg().
generatenormal() [1/2]
static double alglib.testlinregunit.generatenormal (double mean, double sigma) inline static private
References alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testlinregunit.filltaskwithy(), alglib.testlinregunit.generatetask(), and alglib.testlinregunit.testlinreg().
calculatemv() [1/2]
static void alglib.testlinregunit.calculatemv (double[] x, int n, ref double mean, ref double means, ref double stddev, ref double stddevs) inline static private
References alglib.math.sqr().
Referenced by alglib.testlinregunit.testlinreg().
unsetlr() [1/2]
static void alglib.testlinregunit.unsetlr (linreg.linearmodel lr) inline static private
References alglib.ap.assert(), and alglib.linreg.lrbuild().
Referenced by alglib.testlinregunit.testlinreg().
testlinreg() [2/2]
static bool alglib.testlinregunit.testlinreg (bool silent) inline static
References alglib.ap.assert(), alglib.testlinregunit.calculatemv(), alglib.testlinregunit.filltaskwithy(), alglib.testlinregunit.generatenormal(), alglib.testlinregunit.generaterandomtask(), alglib.testlinregunit.generatetask(), alglib.linreg.lravgerror(), alglib.linreg.lravgrelerror(), alglib.linreg.lrbuild(), alglib.linreg.lrbuilds(), alglib.linreg.lrbuildzs(), alglib.linreg.lrcopy(), alglib.linreg.lrline(), alglib.linreg.lrlines(), alglib.linreg.lrpack(), alglib.linreg.lrprocess(), alglib.linreg.lrrmserror(), alglib.linreg.lrunpack(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.math.sqr(), and alglib.testlinregunit.unsetlr().
_pexec_testlinreg()
static bool alglib.testlinregunit._pexec_testlinreg (bool silent) inline static
References alglib.testlinregunit.testlinreg().
Referenced by _Test.Main().
generaterandomtask() [2/2]
static void alglib.testlinregunit.generaterandomtask (double xl, double xr, bool randomx, double ymin, double ymax, double smin, double smax, int n, ref double xy[,], ref double[] s) inline static private
References alglib.math.randomreal().
generatetask() [2/2]
static void alglib.testlinregunit.generatetask (double a, double b, double xl, double xr, bool randomx, double smin, double smax, int n, ref double xy[,], ref double[] s) inline static private
References alglib.testlinregunit.generatenormal(), and alglib.math.randomreal().
filltaskwithy() [2/2]
static void alglib.testlinregunit.filltaskwithy (double a, double b, int n, ref double xy[,], ref double[] s) inline static private
References alglib.testlinregunit.generatenormal().
generatenormal() [2/2]
static double alglib.testlinregunit.generatenormal (double mean, double sigma) inline static private
References alglib.math.randominteger(), and alglib.math.randomreal().
calculatemv() [2/2]
static void alglib.testlinregunit.calculatemv (double[] x, int n, ref double mean, ref double means, ref double stddev, ref double stddevs) inline static private
References alglib.math.sqr().
unsetlr() [2/2]
static void alglib.testlinregunit.unsetlr (linreg.linearmodel lr) inline static private
References alglib.ap.assert(), and alglib.linreg.lrbuild().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs