Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DORGQR Class Reference
DotNumerics.LinearAlgebra.CSLapack.DORGQR Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DORGQR (DLARFB dlarfb, DLARFT dlarft, DORG2R dorg2r, XERBLA xerbla, ILAENV ilaenv)
DORGQR ()
void Run (int M, int N, int K, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
DLARFB _dlarfb
DLARFT _dlarft
DORG2R _dorg2r
XERBLA _xerbla
ILAENV _ilaenv
Static Private Attributes
const double ZERO = 0.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DORGQR generates an M-by-N real matrix Q with orthonormal columns, which is defined as the first N columns of a product of K elementary reflectors of order M
Q = H(1) H(2) . . . H(k)
as returned by DGEQRF.
/summary>
Constructor & Destructor Documentation
DORGQR() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DORGQR.DORGQR (DLARFB dlarfb, DLARFT dlarft, DORG2R dorg2r, XERBLA xerbla, ILAENV ilaenv) inline
DORGQR() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DORGQR.DORGQR () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DORGQR.Run (int M, int N, int K, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DORGQR generates an M-by-N real matrix Q with orthonormal columns, which is defined as the first N columns of a product of K elementary reflectors of order M
Q = H(1) H(2) . . . H(k)
as returned by DGEQRF.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix Q. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix Q. M .GE. N .GE. 0. /param>
Parameters
K (input) INTEGER The number of elementary reflectors whose product defines the matrix Q. N .GE. K .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the i-th column must contain the vector which defines the elementary reflector H(i), for i = 1,2,...,k, as returned by DGEQRF in the first k columns of its array argument A. On exit, the M-by-N matrix Q. /param>
Parameters
LDA (input) INTEGER The first dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
TAU (input) DOUBLE PRECISION array, dimension (K) TAU(i) must contain the scalar factor of the elementary reflector H(i), as returned by DGEQRF. /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. max(1,N). For optimum performance LWORK .GE. N*NB, where NB is the optimal blocksize.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument has an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DORG2R.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFT.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFB.Run(), and DotNumerics.LinearAlgebra.CSLapack.DORGQR.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORGHR.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGTR.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGBR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run().
Member Data Documentation
_dlarfb
DLARFB DotNumerics.LinearAlgebra.CSLapack.DORGQR._dlarfb private
_dlarft
DLARFT DotNumerics.LinearAlgebra.CSLapack.DORGQR._dlarft private
_dorg2r
DORG2R DotNumerics.LinearAlgebra.CSLapack.DORGQR._dorg2r private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DORGQR._xerbla private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DORGQR._ilaenv private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DORGQR.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORGQR.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dorgqr.cs