Doc: IGLib EXTENDED: NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests Class Reference
NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests Class Reference
Public Member Functions
void EraseInvalidFile ()
void NotWebProject ()
void LoadInvalidFileType ()
void FileNotFoundError ()
void InvalidXmlFormat (string invalidXml)
void NoConfigurations ()
Private Member Functions
void WriteInvalidFile (string text)
Private Attributes
string invalidFile = Path.Combine(Path.GetTempPath(), "invalid.csproj")
Member Function Documentation
WriteInvalidFile()
void NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.WriteInvalidFile (string text) inline private
References NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.invalidFile.
Referenced by NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.InvalidXmlFormat(), and NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.NoConfigurations().
EraseInvalidFile()
void NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.EraseInvalidFile () inline
References NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.invalidFile.
NotWebProject()
void NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.NotWebProject () inline
References NUnit.Framework.Assert.IsFalse(), and NUnit.Engine.Services.ProjectLoaders.VSProject.IsProjectFile().
LoadInvalidFileType()
void NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.LoadInvalidFileType () inline
References NUnit.Framework.Assert.Throws().
FileNotFoundError()
void NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.FileNotFoundError () inline
References NUnit.Framework.Assert.Throws().
InvalidXmlFormat()
void NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.InvalidXmlFormat (string invalidXml) inline
References NUnit.Framework.Assert.Throws(), and NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.WriteInvalidFile().
NoConfigurations()
void NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.NoConfigurations () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Services.ProjectLoaders.VSProject.ConfigNames, and NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.WriteInvalidFile().
Member Data Documentation
invalidFile
string NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.invalidFile = Path.Combine(Path.GetTempPath(), "invalid.csproj") private
Referenced by NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.EraseInvalidFile(), and NUnit.Engine.Services.ProjectLoaders.Tests.VSProjectTests.WriteInvalidFile().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/Addins/addin-tests/VSProjectTests.cs