Doc: IGLib EXTENDED: NUnit.Framework.Attributes.CombinatorialTests Class Reference
NUnit.Framework.Attributes.CombinatorialTests Class Reference
Public Member Functions
void SingleArgument ([Values(1.3, 1.7, 1.5)] double x)
void TwoArguments_Combinatorial ([Values(1, 2, 3)] int x, [Values(10, 20)] int y)
void TwoArguments_Sequential ([Values(1, 2, 3)] int x, [Values(10, 20)] int y)
void ThreeArguments_Combinatorial ([Values(1, 2, 3)] int x, [Values(10, 20)] int y, [Values("Charlie", "Joe", "Frank")] string name)
void ThreeArguments_Sequential ([Values(1, 2, 3)] int x, [Values(10, 20)] int y, [Values("Charlie", "Joe", "Frank")] string name)
void RangeTest ([Range(0.2, 0.6, 0.2)] double a, [Range(10, 20, 5)] int b)
void RandomTest ([Random(32, 212, 5)] int x, [Random(5)] double y, [Random(5)] AttributeTargets z)
void RandomArgsAreIndependent ([Random(1)] double x, [Random(1)] double y)
void CombinatorialIsIgnoredIfThereAreNoArguments ()
Member Function Documentation
SingleArgument()
void NUnit.Framework.Attributes.CombinatorialTests.SingleArgument ([Values(1.3, 1.7, 1.5)] double x) inline
References NUnit.Framework.Assert.That().
TwoArguments_Combinatorial()
void NUnit.Framework.Attributes.CombinatorialTests.TwoArguments_Combinatorial ([Values(1, 2, 3)] int x, [Values(10, 20)] int y) inline
References NUnit.Framework.Assert.That().
TwoArguments_Sequential()
void NUnit.Framework.Attributes.CombinatorialTests.TwoArguments_Sequential ([Values(1, 2, 3)] int x, [Values(10, 20)] int y) inline
References NUnit.Framework.Assert.That().
ThreeArguments_Combinatorial()
void NUnit.Framework.Attributes.CombinatorialTests.ThreeArguments_Combinatorial ([Values(1, 2, 3)] int x, [Values(10, 20)] int y, [Values("Charlie", "Joe", "Frank")] string name) inline
References NUnit.Framework.Assert.That().
ThreeArguments_Sequential()
void NUnit.Framework.Attributes.CombinatorialTests.ThreeArguments_Sequential ([Values(1, 2, 3)] int x, [Values(10, 20)] int y, [Values("Charlie", "Joe", "Frank")] string name) inline
References NUnit.Framework.Assert.That().
RangeTest()
void NUnit.Framework.Attributes.CombinatorialTests.RangeTest ([Range(0.2, 0.6, 0.2)] double a, [Range(10, 20, 5)] int b) inline
RandomTest()
void NUnit.Framework.Attributes.CombinatorialTests.RandomTest ([Random(32, 212, 5)] int x, [Random(5)] double y, [Random(5)] AttributeTargets z) inline
References NUnit.Framework.Is.InRange(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
RandomArgsAreIndependent()
void NUnit.Framework.Attributes.CombinatorialTests.RandomArgsAreIndependent ([Random(1)] double x, [Random(1)] double y) inline
References NUnit.Framework.Assert.AreNotEqual().
CombinatorialIsIgnoredIfThereAreNoArguments()
void NUnit.Framework.Attributes.CombinatorialTests.CombinatorialIsIgnoredIfThereAreNoArguments () inline
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/CombinatorialTests.cs