Doc: IGLib EXTENDED: IG.MPetekLib.Algorithms.Plotting.PlotHQ Class Reference
IG.MPetekLib.Algorithms.Plotting.PlotHQ Class Reference
A pack of 2 class object that are used for plotting: ZedGraphWindow and PlotterZedGraph. The user adds plot objects (e.g. PlotZedGraphCurve) by constructing their classes and specifiying the plotter as an argument.
Public Member Functions
PlotHQ ()
Constructs the PlotHQ object. Creates the window and a plotter.
void ShowPlot ()
Shows the plot window.
Protected Attributes
ZedGraphWindow _window
PlotterZedGraph _plotter
Properties
ZedGraphWindow Window [get, set]
This property provides an access point for the window's appearance settings (Height, Width).
PlotterZedGraph Plotter [get, set]
The plotter holds and displays all the plottable objects. This property provides an access point for the graph's appearance settings (Title, Y2AxisVisible, XAxisLabel, XAxisScaleFont, XAxisLabelFont, TitleFont) and appearance changing methods (ResetView, SetBounds).
Detailed Description
A pack of 2 class object that are used for plotting: ZedGraphWindow and PlotterZedGraph. The user adds plot objects (e.g. PlotZedGraphCurve) by constructing their classes and specifiying the plotter as an argument.
Constructor & Destructor Documentation
PlotHQ()
IG.MPetekLib.Algorithms.Plotting.PlotHQ.PlotHQ () inline
Constructs the PlotHQ object. Creates the window and a plotter.
References IG.MPetekLib.Algorithms.Plotting.PlotHQ._plotter, IG.MPetekLib.Algorithms.Plotting.PlotHQ._window, IG.Gr.PlotterZedGraph.CreateDefault(), and IG.Gr.ZedGraphWindow.GraphControl.
Member Function Documentation
ShowPlot()
void IG.MPetekLib.Algorithms.Plotting.PlotHQ.ShowPlot () inline
Shows the plot window.
References IG.MPetekLib.Algorithms.Plotting.PlotHQ._plotter, IG.MPetekLib.Algorithms.Plotting.PlotHQ._window, and IG.Gr.PlotterZedGraph.Update().
Referenced by IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.FindSteadyStateAmplitude(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.PlaceOfExtremeInPeriod(), IG.MPetekLib.Application.Scripts.LinearOscillator._14PhaseShiftPlot.Run(), IG.MPetekLib.Application.Scripts.NonlinearOscNondim._16SolutionPlot.Run(), IG.MPetekLib.Application.Scripts.NonlinearOscillator._19SingleResonancePlot.Run(), IG.MPetekLib.Application.Scripts.NonlinearOscillator._22SingleResCurveManyPhases.Run(), IG.Script._18ChaoticPlot.Run(), IG.Script._25KickedRotator.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._08SteadyStateAmplitude.Run(), IG.MPetekLib.Application.Scripts.NonlinearOscillator._21MultipleResCurvesPlot.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._04PlotAtanModified.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._12MultipleResCurvesPlot.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._13SolutionAndDrivingFunctionPlot.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._06NumericalVsAnalyticalErrorDiff.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._09SingleResonanceCurvePlot.Run(), IG.MPetekLib.Application.Scripts.NonlinearOscNondim._20MultipleResCurvesPlot.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._05AnalytAndNumSolutionPlot.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._07RichardsonExtrapolation.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._02DrivenPlotSolution.Run(), IG.Script._01LPSimple.Run(), IG.Script._02LPAttenuation.Run(), IG.Script.DemoResonanceCurvePlot.Run(), IG.Script.DemoResonanceCurvePlotExt.Run(), IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.MolecularCatenary.ShowPlot(), and IG.MPetekLib.Application.Scripts.LinearOscillator._05AnalytAndNumSolutionPlot.StartNewStaPlottingThread().
Member Data Documentation
_window
ZedGraphWindow IG.MPetekLib.Algorithms.Plotting.PlotHQ._window protected
Referenced by IG.MPetekLib.Algorithms.Plotting.PlotHQ.PlotHQ(), and IG.MPetekLib.Algorithms.Plotting.PlotHQ.ShowPlot().
_plotter
PlotterZedGraph IG.MPetekLib.Algorithms.Plotting.PlotHQ._plotter protected
Referenced by IG.MPetekLib.Algorithms.Plotting.PlotHQ.PlotHQ(), and IG.MPetekLib.Algorithms.Plotting.PlotHQ.ShowPlot().
Property Documentation
Window
ZedGraphWindow IG.MPetekLib.Algorithms.Plotting.PlotHQ.Window get set
This property provides an access point for the window's appearance settings (Height, Width).
Referenced by IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.FindSteadyStateAmplitude(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.PlaceOfExtremeInPeriod(), IG.MPetekLib.Application.Scripts.LinearOscillator._14PhaseShiftPlot.Run(), IG.MPetekLib.Application.Scripts.NonlinearOscNondim._16SolutionPlot.Run(), IG.MPetekLib.Application.Scripts.NonlinearOscillator._22SingleResCurveManyPhases.Run(), IG.Script._18ChaoticPlot.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._04PlotAtanModified.Run(), IG.MPetekLib.Application.Scripts.NonlinearOscillator._21MultipleResCurvesPlot.Run(), IG.Script._25KickedRotator.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._13SolutionAndDrivingFunctionPlot.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._06NumericalVsAnalyticalErrorDiff.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._12MultipleResCurvesPlot.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._05AnalytAndNumSolutionPlot.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._02DrivenPlotSolution.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._07RichardsonExtrapolation.Run(), IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.MolecularCatenary.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.MolecularCatenary.SimulatedAnnealing(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealingWithPlot().
Plotter
PlotterZedGraph IG.MPetekLib.Algorithms.Plotting.PlotHQ.Plotter get set
The plotter holds and displays all the plottable objects. This property provides an access point for the graph's appearance settings (Title, Y2AxisVisible, XAxisLabel, XAxisScaleFont, XAxisLabelFont, TitleFont) and appearance changing methods (ResetView, SetBounds).
Referenced by IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.FindSteadyStateAmplitude(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.PlaceOfExtremeInPeriod(), IG.MPetekLib.Application.Scripts.LinearOscillator._14PhaseShiftPlot.Run(), IG.MPetekLib.Application.Scripts.NonlinearOscNondim._16SolutionPlot.Run(), IG.MPetekLib.Application.Scripts.NonlinearOscillator._19SingleResonancePlot.Run(), IG.MPetekLib.Application.Scripts.NonlinearOscillator._22SingleResCurveManyPhases.Run(), IG.Script._18ChaoticPlot.Run(), IG.Script._25KickedRotator.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._08SteadyStateAmplitude.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._04PlotAtanModified.Run(), IG.MPetekLib.Application.Scripts.NonlinearOscillator._21MultipleResCurvesPlot.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._06NumericalVsAnalyticalErrorDiff.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._12MultipleResCurvesPlot.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._13SolutionAndDrivingFunctionPlot.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._05AnalytAndNumSolutionPlot.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._09SingleResonanceCurvePlot.Run(), IG.MPetekLib.Application.Scripts.NonlinearOscNondim._20MultipleResCurvesPlot.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._07RichardsonExtrapolation.Run(), IG.MPetekLib.Application.Scripts.LinearOscillator._02DrivenPlotSolution.Run(), IG.Script._01LPSimple.Run(), IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.Run(), IG.Script._02LPAttenuation.Run(), IG.Script.DemoResonanceCurvePlot.Run(), IG.Script.DemoResonanceCurvePlotExt.Run(), IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.MolecularCatenary.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.MolecularCatenary.SimulatedAnnealing(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealingWithPlot(), and IG.MPetekLib.Application.Scripts.LinearOscillator._05AnalytAndNumSolutionPlot.StartNewStaPlottingThread().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/Guest_Marko_Petek_Lib/algorithms/Plotting/PlotHQ.cs