Doc: IGLib EXTENDED: alglib.cqmodels Class Reference
alglib.cqmodels Class Reference
Classes
class convexquadraticmodel
Static Public Member Functions
static void cqminit (int n, convexquadraticmodel s)
static void cqmseta (convexquadraticmodel s, double[,] a, bool isupper, double alpha)
static void cqmrewritedensediagonal (convexquadraticmodel s, double[] z)
static void cqmsetd (convexquadraticmodel s, double[] d, double tau)
static void cqmdropa (convexquadraticmodel s)
static void cqmsetb (convexquadraticmodel s, double[] b)
static void cqmsetq (convexquadraticmodel s, double[,] q, double[] r, int k, double theta)
static void cqmsetactiveset (convexquadraticmodel s, double[] x, bool[] activeset)
static double cqmeval (convexquadraticmodel s, double[] x)
static void cqmevalx (convexquadraticmodel s, double[] x, ref double r, ref double noise)
static void cqmgradunconstrained (convexquadraticmodel s, double[] x, ref double[] g)
static double cqmxtadx2 (convexquadraticmodel s, double[] x)
static void cqmadx (convexquadraticmodel s, double[] x, ref double[] y)
static bool cqmconstrainedoptimum (convexquadraticmodel s, ref double[] x)
static void cqmscalevector (convexquadraticmodel s, ref double[] x)
static double cqmdebugconstrainedevalt (convexquadraticmodel s, double[] x)
static double cqmdebugconstrainedevale (convexquadraticmodel s, double[] x)
static void cqminit (int n, convexquadraticmodel s)
static void cqmseta (convexquadraticmodel s, double[,] a, bool isupper, double alpha)
static void cqmrewritedensediagonal (convexquadraticmodel s, double[] z)
static void cqmsetd (convexquadraticmodel s, double[] d, double tau)
static void cqmdropa (convexquadraticmodel s)
static void cqmsetb (convexquadraticmodel s, double[] b)
static void cqmsetq (convexquadraticmodel s, double[,] q, double[] r, int k, double theta)
static void cqmsetactiveset (convexquadraticmodel s, double[] x, bool[] activeset)
static double cqmeval (convexquadraticmodel s, double[] x)
static void cqmevalx (convexquadraticmodel s, double[] x, ref double r, ref double noise)
static void cqmgradunconstrained (convexquadraticmodel s, double[] x, ref double[] g)
static double cqmxtadx2 (convexquadraticmodel s, double[] x)
static void cqmadx (convexquadraticmodel s, double[] x, ref double[] y)
static bool cqmconstrainedoptimum (convexquadraticmodel s, ref double[] x)
static void cqmscalevector (convexquadraticmodel s, ref double[] x)
static double cqmdebugconstrainedevalt (convexquadraticmodel s, double[] x)
static double cqmdebugconstrainedevale (convexquadraticmodel s, double[] x)
Static Public Attributes
const int newtonrefinementits = 3
Static Private Member Functions
static bool cqmrebuild (convexquadraticmodel s)
static void cqmsolveea (convexquadraticmodel s, ref double[] x, ref double[] tmp)
static bool cqmrebuild (convexquadraticmodel s)
static void cqmsolveea (convexquadraticmodel s, ref double[] x, ref double[] tmp)
Member Function Documentation
cqminit() [1/2]
static void alglib.cqmodels.cqminit (int n, convexquadraticmodel s) inline static
Referenced by alglib.testcqmodelsunit.testcqmodels().
cqmseta() [1/2]
static void alglib.cqmodels.cqmseta (convexquadraticmodel s, double a[,], bool isupper, double alpha) inline static
Referenced by alglib.testcqmodelsunit.testcqmodels().
cqmrewritedensediagonal() [1/2]
static void alglib.cqmodels.cqmrewritedensediagonal (convexquadraticmodel s, double[] z) inline static
Referenced by alglib.testcqmodelsunit.testcqmodels().
cqmsetd() [1/2]
static void alglib.cqmodels.cqmsetd (convexquadraticmodel s, double[] d, double tau) inline static
Referenced by alglib.testcqmodelsunit.testcqmodels().
cqmdropa() [1/2]
static void alglib.cqmodels.cqmdropa (convexquadraticmodel s) inline static
cqmsetb() [1/2]
static void alglib.cqmodels.cqmsetb (convexquadraticmodel s, double[] b) inline static
Referenced by alglib.testcqmodelsunit.testcqmodels().
cqmsetq() [1/2]
static void alglib.cqmodels.cqmsetq (convexquadraticmodel s, double q[,], double[] r, int k, double theta) inline static
Referenced by alglib.testcqmodelsunit.testcqmodels().
cqmsetactiveset() [1/2]
static void alglib.cqmodels.cqmsetactiveset (convexquadraticmodel s, double[] x, bool[] activeset) inline static
Referenced by alglib.testcqmodelsunit.testcqmodels().
cqmeval() [1/2]
static double alglib.cqmodels.cqmeval (convexquadraticmodel s, double[] x) inline static
Referenced by alglib.testcqmodelsunit.testcqmodels().
cqmevalx() [1/2]
static void alglib.cqmodels.cqmevalx (convexquadraticmodel s, double[] x, ref double r, ref double noise) inline static
Referenced by alglib.testcqmodelsunit.testcqmodels().
cqmgradunconstrained() [1/2]
static void alglib.cqmodels.cqmgradunconstrained (convexquadraticmodel s, double[] x, ref double[] g) inline static
Referenced by alglib.cqmodels.cqmconstrainedoptimum(), and alglib.testcqmodelsunit.testcqmodels().
cqmxtadx2() [1/2]
static double alglib.cqmodels.cqmxtadx2 (convexquadraticmodel s, double[] x) inline static
Referenced by alglib.testcqmodelsunit.testcqmodels().
cqmadx() [1/2]
static void alglib.cqmodels.cqmadx (convexquadraticmodel s, double[] x, ref double[] y) inline static
Referenced by alglib.testcqmodelsunit.testcqmodels().
cqmconstrainedoptimum() [1/2]
static bool alglib.cqmodels.cqmconstrainedoptimum (convexquadraticmodel s, ref double[] x) inline static
Referenced by alglib.testcqmodelsunit.testcqmodels().
cqmscalevector() [1/2]
static void alglib.cqmodels.cqmscalevector (convexquadraticmodel s, ref double[] x) inline static
cqmdebugconstrainedevalt() [1/2]
static double alglib.cqmodels.cqmdebugconstrainedevalt (convexquadraticmodel s, double[] x) inline static
Referenced by alglib.testcqmodelsunit.testcqmodels().
cqmdebugconstrainedevale() [1/2]
static double alglib.cqmodels.cqmdebugconstrainedevale (convexquadraticmodel s, double[] x) inline static
Referenced by alglib.testcqmodelsunit.testcqmodels().
cqmrebuild() [1/2]
static bool alglib.cqmodels.cqmrebuild (convexquadraticmodel s) inline static private
Referenced by alglib.cqmodels.cqmconstrainedoptimum(), alglib.cqmodels.cqmdebugconstrainedevale(), and alglib.cqmodels.cqmdebugconstrainedevalt().
cqmsolveea() [1/2]
static void alglib.cqmodels.cqmsolveea (convexquadraticmodel s, ref double[] x, ref double[] tmp) inline static private
Referenced by alglib.cqmodels.cqmconstrainedoptimum().
cqminit() [2/2]
static void alglib.cqmodels.cqminit (int n, convexquadraticmodel s) inline static
References alglib.apserv.bvectorsetlengthatleast(), and alglib.apserv.rvectorsetlengthatleast().
cqmseta() [2/2]
static void alglib.cqmodels.cqmseta (convexquadraticmodel s, double a[,], bool isupper, double alpha) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.apserv.isfinitertrmatrix(), and alglib.apserv.rmatrixsetlengthatleast().
cqmrewritedensediagonal() [2/2]
static void alglib.cqmodels.cqmrewritedensediagonal (convexquadraticmodel s, double[] z) inline static
References alglib.apserv.rmatrixsetlengthatleast().
cqmsetd() [2/2]
static void alglib.cqmodels.cqmsetd (convexquadraticmodel s, double[] d, double tau) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), and alglib.apserv.rvectorsetlengthatleast().
cqmdropa() [2/2]
static void alglib.cqmodels.cqmdropa (convexquadraticmodel s) inline static
cqmsetb() [2/2]
static void alglib.cqmodels.cqmsetb (convexquadraticmodel s, double[] b) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), and alglib.apserv.rvectorsetlengthatleast().
cqmsetq() [2/2]
static void alglib.cqmodels.cqmsetq (convexquadraticmodel s, double q[,], double[] r, int k, double theta) inline static
References alglib.apserv.apservisfinitematrix(), alglib.ap.assert(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), alglib.apserv.rmatrixsetlengthatleast(), and alglib.apserv.rvectorsetlengthatleast().
cqmsetactiveset() [2/2]
static void alglib.cqmodels.cqmsetactiveset (convexquadraticmodel s, double[] x, bool[] activeset) inline static
References alglib.ap.assert(), and alglib.math.isfinite().
cqmeval() [2/2]
static double alglib.cqmodels.cqmeval (convexquadraticmodel s, double[] x) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), and alglib.math.sqr().
cqmevalx() [2/2]
static void alglib.cqmodels.cqmevalx (convexquadraticmodel s, double[] x, ref double r, ref double noise) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), alglib.math.machineepsilon, and alglib.math.sqr().
cqmgradunconstrained() [2/2]
static void alglib.cqmodels.cqmgradunconstrained (convexquadraticmodel s, double[] x, ref double[] g) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), and alglib.apserv.rvectorsetlengthatleast().
cqmxtadx2() [2/2]
static double alglib.cqmodels.cqmxtadx2 (convexquadraticmodel s, double[] x) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), and alglib.math.sqr().
cqmadx() [2/2]
static void alglib.cqmodels.cqmadx (convexquadraticmodel s, double[] x, ref double[] y) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), and alglib.apserv.rvectorsetlengthatleast().
cqmconstrainedoptimum() [2/2]
static bool alglib.cqmodels.cqmconstrainedoptimum (convexquadraticmodel s, ref double[] x) inline static
References alglib.cqmodels.cqmgradunconstrained(), alglib.cqmodels.cqmrebuild(), alglib.cqmodels.cqmsolveea(), alglib.fbls.fblscholeskysolve(), alglib.cqmodels.newtonrefinementits, and alglib.apserv.rvectorsetlengthatleast().
cqmscalevector() [2/2]
static void alglib.cqmodels.cqmscalevector (convexquadraticmodel s, ref double[] x) inline static
cqmdebugconstrainedevalt() [2/2]
static double alglib.cqmodels.cqmdebugconstrainedevalt (convexquadraticmodel s, double[] x) inline static
References alglib.ap.assert(), alglib.cqmodels.cqmrebuild(), alglib.apserv.isfinitevector(), and alglib.math.sqr().
cqmdebugconstrainedevale() [2/2]
static double alglib.cqmodels.cqmdebugconstrainedevale (convexquadraticmodel s, double[] x) inline static
References alglib.ap.assert(), alglib.cqmodels.cqmrebuild(), alglib.apserv.isfinitevector(), and alglib.math.sqr().
cqmrebuild() [2/2]
static bool alglib.cqmodels.cqmrebuild (convexquadraticmodel s) inline static private
References alglib.ap.assert(), alglib.ablas.rmatrixcopy(), alglib.ablas.rmatrixmv(), alglib.ablas.rmatrixrighttrsm(), alglib.apserv.rmatrixsetlengthatleast(), alglib.ablas.rmatrixsyrk(), alglib.apserv.rvectorsetlengthatleast(), alglib.trfac.spdmatrixcholeskyrec(), and alglib.math.sqr().
cqmsolveea() [2/2]
static void alglib.cqmodels.cqmsolveea (convexquadraticmodel s, ref double[] x, ref double[] tmp) inline static private
References alglib.ap.assert(), alglib.fbls.fblscholeskysolve(), and alglib.math.sqr().
Member Data Documentation
newtonrefinementits
const int alglib.cqmodels.newtonrefinementits = 3 static
Referenced by alglib.cqmodels.cqmconstrainedoptimum().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/optimization.cs