Doc: IGLib EXTENDED: IG.Script.Script_Misc Class Reference
IG.Script.Script_Misc Class Reference
Public Member Functions
Script_Misc ()
override void Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings)
Adds commands to the internal interpreter.
string TestListsOperations (string[] arguments)
Test of lists and operations on them.
string TestFileOperations (string[] arguments)
Test of file operations.
string TestSystem (string[] arguments)
Test of system utilities.
string TestStringParser (string[] arguments)
Test of string parsers.
string TestConsoleUtilities (string[] arguments)
Test of console utilities.
string TestSerializationJson (string[] arguments)
Test of JSON serializer.
string TestExpressionEvaluatorJavaScript (string[] arguments)
JavaScript - based expression evaluator.
string TestRegisterable_IdGenerator (string[] arguments)
Test of Registerable classes and ID generators.
string TestExoticAndObsolete (string[] arguments)
Test of exotic and obsolete classes.
Public Member Functions inherited from IG.Lib.LoadableScriptBase
LoadableScriptBase ()
Argument-less constructor. If argument-less constructor is called then initialization is not performed and will be performed later.
string Run (string[] arguments)
Performs the action of this object. Override this in derived classes!
void Initialize (string[] arguments)
Initializes the object. If not called explicitly, this method is automatically called at the first call to the Run method.
virtual string Script_DefaultInitialize (string[] arguments)
Default initialization method for scripts.
virtual string Script_DefaultRun (string[] arguments)
Default run method for the script. Can be used when only installed commands are run by hte script.
virtual ICommandLineApplicationInterpreter Script_CreateInterpreterWithoutCommands ()
Creates and returns an interpreter that can be used as script's internal interpreter for running script's commands.
delegate string Script_CommandDelegate (string[] args)
Delegate for commands that are installed on script's internal interpreter (property Script_Interpreter).
void Script_AddCommand (string commandName, Script_CommandDelegate command, string helpString)
Adds a new internal script command under specified name to the internal interpreter of the current script object.
virtual void Script_AddCommand (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings, string commandName, Script_CommandDelegate command, string helpString)
Adds a new internal script command under specified name to the internal interpreter of the current script object.
string Script_GetHelpString (string scriptCommandName)
Returns help string for internal script command with specified name, or null if help string is not installed for such a command.
void Script_PrintCommandsHelp ()
Prits help for the installed internal commands of the script.
virtual bool Script_ContainsCommand (string commandName)
Returns true if the internal script's interpreter contains a command with specified name, false otherwise.
virtual bool Script_ContainsScriptCommand (string commandName)
Returns true if the specified command is script command (i.e. its first argument is command-name and it is run through the Script_CommandAdapter object).
virtual void Script_RemoveCommand (string commandName)
Removes the specified internal script command from the internal interpreter of the current scripting object.
virtual void Script_RemoveAllCommands ()
Removes ALL internal script commands from the internal interpreter of the current scripting object.
string Script_Run (string[] arguments)
Runs internal script command.
string Script_Run (string commandName, params string[] otherArguments)
Runs internal script command.
virtual void Script_PrintArguments (string messageString, string[] arguments)
Prints the specified array of string arguments (usually passed as command-line arguments).
Static Public Attributes
const string ConstListOperations = "ListOperations"
Tests of list operations.
const string ConstHelpListOperations = "Tests of lists and operations on them."
const string ConstFileOperations = "FileOperations"
Tests of file operations.
const string ConstHelpFileOperations = "Tests of file operations."
const string ConstSystem = "System"
Tests of string parsers.
const string ConstHelpSystem = "Tests of system utilities."
const string ConstStringParser = "StringParser"
Tests of string parsers.
const string ConstHelpStringParser = "Tests of strng parser."
const string ConstConsoleUtilities = "ConsoleUtilities"
Tests of console utilities.
const string ConstHelpConsoleUtilities = "Tests of console utilities."
const string ConstSerializerJson = "SerializerJson"
Test of JSON serializer.
const string ConstHelpSerializerJson = "Tests of JSON serialization."
const string ConstExpressionEvaluatorJavaScript = "ExpressionEvaluatorJs"
JavaScript - based expression evaluator.
const string ConstHelpExpressionEvaluatorJavaScript = "Tests of JavaScript based Expression evaluator."
const string ConstRegisterable_IdGenerator = "Registerable_IdGenerator"
Test of Registerable classes and ID generators.
const string ConstHelpRegisterable_IdGenerator = "Test of IRegisterable interface and ID generator."
const string ConstExoticAndObsolete = "Registerable_IdGenerator"
Test of exotic and obsolete classes.
const string ConstHelpExoticAndObsolete = "Test of IRegisterable interface and ID generator."
Static Public Attributes inherited from IG.Lib.LoadableScriptBase
const string ConstDefaultHelp = "Help"
Default command name for help.
const string ConstHelpDefaultUniversal = "?"
Universal name of the help command.
const string ConstDefaultTestScrip = "TestScript"
Default command name for test method.
Protected Member Functions
override void InitializeThis (string[] arguments)
Initializes the current object.
override string RunThis (string[] arguments)
Runs action of the current object.
Protected Member Functions inherited from IG.Lib.LoadableScriptBase
delegate string CommandMethod (string commandName, string[] args)
Delegate for internal command methods.
ICommandLineApplicationInterpreter Script_CreateInterpreter ()
Creates and returns an interpreter that can be used as script's internal interpreter for running script's commands.
virtual string Script_CommandHelp (string[] arguments)
Prints help.
virtual string Script_CommandTestScript (string[] arguments)
Prints help.
Additional Inherited Members
Protected Attributes inherited from IG.Lib.LoadableScriptBase
string _embeddedCommandName = null
int _outputLevel = DefaultOutputLevel
ICommandLineApplicationInterpreter _script_interpreter
Properties inherited from IG.Lib.LoadableScriptBase
string EmbeddedCommandName [get, set]
Command that was used to launch the current embedded application script.
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
string[] InitializationArguments [get, set]
Arguments used by the initialization method. WARNING: arguments can only be set before initialization is performed. Initialization is performed either implicitly at the first call to the Run method or explicitly by calling the Initialize method.
virtual bool IsInitialized [get, protected set]
Whether the object has been initialized or not.
static int DefaultOutputLevel [get, set]
int OutputLevel [get, set]
Level of output to console produced by some operations of the current object.
virtual ICommandLineApplicationInterpreter Script_Interpreter [get, protected set]
Script's internal interpreter that takes care for execution of installed internal commands.
SortedList< string, string > Script_CommandHelpStrings [get]
Contains help strings associated with script commands installed on interpreter.
Properties inherited from IG.Lib.ILoadableScript
string EmbeddedCommandName [get, set]
Command that was used to launch the current embedded application script.
string[] InitializationArguments [get, set]
Arguments used by the initialization method.
bool IsInitialized [get]
Whether the object has been initialized or not.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Constructor & Destructor Documentation
Script_Misc()
IG.Script.Script_Misc.Script_Misc () inline
Member Function Documentation
InitializeThis()
override void IG.Script.Script_Misc.InitializeThis (string[] arguments) inline protected virtual
Initializes the current object.
Implements IG.Lib.LoadableScriptBase.
References IG.Lib.LoadableScriptBase.Script_DefaultInitialize().
RunThis()
override string IG.Script.Script_Misc.RunThis (string[] arguments) inline protected virtual
Runs action of the current object.
Parameters
arguments Command-line arguments of the action.
Implements IG.Lib.LoadableScriptBase.
References IG.Lib.LoadableScriptBase.Script_DefaultRun().
Script_AddCommands()
override void IG.Script.Script_Misc.Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings) inline virtual
Adds commands to the internal interpreter.
Parameters
interpreter Interpreter where commands are executed.
helpStrings List containg help strings.
Reimplemented from IG.Lib.LoadableScriptBase.
References IG.Script.Script_Misc.ConstConsoleUtilities, IG.Script.Script_Misc.ConstExoticAndObsolete, IG.Script.Script_Misc.ConstExpressionEvaluatorJavaScript, IG.Script.Script_Misc.ConstFileOperations, IG.Script.Script_Misc.ConstHelpConsoleUtilities, IG.Script.Script_Misc.ConstHelpExoticAndObsolete, IG.Script.Script_Misc.ConstHelpExpressionEvaluatorJavaScript, IG.Script.Script_Misc.ConstHelpFileOperations, IG.Script.Script_Misc.ConstHelpListOperations, IG.Script.Script_Misc.ConstHelpRegisterable_IdGenerator, IG.Script.Script_Misc.ConstHelpSerializerJson, IG.Script.Script_Misc.ConstHelpStringParser, IG.Script.Script_Misc.ConstHelpSystem, IG.Script.Script_Misc.ConstListOperations, IG.Script.Script_Misc.ConstRegisterable_IdGenerator, IG.Script.Script_Misc.ConstSerializerJson, IG.Script.Script_Misc.ConstStringParser, IG.Script.Script_Misc.ConstSystem, IG.Lib.LoadableScriptBase.Script_AddCommand(), IG.Script.Script_Misc.TestConsoleUtilities(), IG.Script.Script_Misc.TestExoticAndObsolete(), IG.Script.Script_Misc.TestExpressionEvaluatorJavaScript(), IG.Script.Script_Misc.TestFileOperations(), IG.Script.Script_Misc.TestListsOperations(), IG.Script.Script_Misc.TestRegisterable_IdGenerator(), IG.Script.Script_Misc.TestSerializationJson(), IG.Script.Script_Misc.TestStringParser(), and IG.Script.Script_Misc.TestSystem().
TestListsOperations()
string IG.Script.Script_Misc.TestListsOperations (string[] arguments) inline
Test of lists and operations on them.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Lib.Util.ExampleList(), and IG.Lib.LoadableScriptBase.Script_PrintArguments().
Referenced by IG.Script.Script_Misc.Script_AddCommands().
TestFileOperations()
string IG.Script.Script_Misc.TestFileOperations (string[] arguments) inline
Test of file operations.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Lib.UtilSystem.ExampleRelativePath(), and IG.Lib.LoadableScriptBase.Script_PrintArguments().
Referenced by IG.Script.Script_Misc.Script_AddCommands().
TestSystem()
string IG.Script.Script_Misc.TestSystem (string[] arguments) inline
Test of system utilities.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Lib.UtilSystem.GetComputerName(), IG.Lib.UtilSystem.GetDomainName(), IG.Lib.UtilSystem.GetIpAddressLocal(), and IG.Lib.UtilSystem.GetMacAddressFastest().
Referenced by IG.Script.Script_Misc.Script_AddCommands().
TestStringParser()
string IG.Script.Script_Misc.TestStringParser (string[] arguments) inline
Test of string parsers.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Lib.Parser.Examples(), IG.Lib.LoadableScriptBase.Script_PrintArguments(), and IG.Lib.CharacterBuffer.TestSpeed().
Referenced by IG.Script.Script_Misc.Script_AddCommands().
TestConsoleUtilities()
string IG.Script.Script_Misc.TestConsoleUtilities (string[] arguments) inline
Test of console utilities.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Lib.UtilConsole.Examples(), and IG.Lib.LoadableScriptBase.Script_PrintArguments().
Referenced by IG.Script.Script_Misc.Script_AddCommands().
TestSerializationJson()
string IG.Script.Script_Misc.TestSerializationJson (string[] arguments) inline
Test of JSON serializer.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Lib.SerializerBase.ExampleTestType(), IG.Lib.LoadableScriptBase.Script_PrintArguments(), and IG.Lib.SerializerBase.TestSerializationAll().
Referenced by IG.Script.Script_Misc.Script_AddCommands().
TestExpressionEvaluatorJavaScript()
string IG.Script.Script_Misc.TestExpressionEvaluatorJavaScript (string[] arguments) inline
JavaScript - based expression evaluator.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Lib.ExpressionEvaluatorJs.ExampleCommandLine(), and IG.Lib.LoadableScriptBase.Script_PrintArguments().
Referenced by IG.Script.Script_Misc.Script_AddCommands().
TestRegisterable_IdGenerator()
string IG.Script.Script_Misc.TestRegisterable_IdGenerator (string[] arguments) inline
Test of Registerable classes and ID generators.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Lib.RegisterableExamples.ExampleIdGenerator(), IG.Lib.RegisterableExamples.ExampleRegistrable(), and IG.Lib.LoadableScriptBase.Script_PrintArguments().
Referenced by IG.Script.Script_Misc.Script_AddCommands().
TestExoticAndObsolete()
string IG.Script.Script_Misc.TestExoticAndObsolete (string[] arguments) inline
Test of exotic and obsolete classes.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Num.Scalar.Examples(), and IG.Lib.LoadableScriptBase.Script_PrintArguments().
Referenced by IG.Script.Script_Misc.Script_AddCommands().
Member Data Documentation
ConstListOperations
const string IG.Script.Script_Misc.ConstListOperations = "ListOperations" static
Tests of list operations.
Referenced by IG.Script.Script_Misc.Script_AddCommands(), TestOpt.IGLibShellExtMainProgram.TestMain(), and TestOpt.IGLibShellMainProgram.TestMain().
ConstHelpListOperations
const string IG.Script.Script_Misc.ConstHelpListOperations = "Tests of lists and operations on them." static
Referenced by IG.Script.Script_Misc.Script_AddCommands().
ConstFileOperations
const string IG.Script.Script_Misc.ConstFileOperations = "FileOperations" static
Tests of file operations.
Referenced by IG.Script.Script_Misc.Script_AddCommands(), TestOpt.IGLibShellExtMainProgram.TestMain(), and TestOpt.IGLibShellMainProgram.TestMain().
ConstHelpFileOperations
const string IG.Script.Script_Misc.ConstHelpFileOperations = "Tests of file operations." static
Referenced by IG.Script.Script_Misc.Script_AddCommands().
ConstSystem
const string IG.Script.Script_Misc.ConstSystem = "System" static
Tests of string parsers.
Referenced by IG.Script.Script_Misc.Script_AddCommands().
ConstHelpSystem
const string IG.Script.Script_Misc.ConstHelpSystem = "Tests of system utilities." static
Referenced by IG.Script.Script_Misc.Script_AddCommands().
ConstStringParser
const string IG.Script.Script_Misc.ConstStringParser = "StringParser" static
Tests of string parsers.
Referenced by IG.Script.Script_Misc.Script_AddCommands(), TestOpt.IGLibShellExtMainProgram.TestMain(), and TestOpt.IGLibShellMainProgram.TestMain().
ConstHelpStringParser
const string IG.Script.Script_Misc.ConstHelpStringParser = "Tests of strng parser." static
Referenced by IG.Script.Script_Misc.Script_AddCommands().
ConstConsoleUtilities
const string IG.Script.Script_Misc.ConstConsoleUtilities = "ConsoleUtilities" static
Tests of console utilities.
Referenced by IG.Script.Script_Misc.Script_AddCommands(), TestOpt.IGLibShellExtMainProgram.TestMain(), and TestOpt.IGLibShellMainProgram.TestMain().
ConstHelpConsoleUtilities
const string IG.Script.Script_Misc.ConstHelpConsoleUtilities = "Tests of console utilities." static
Referenced by IG.Script.Script_Misc.Script_AddCommands().
ConstSerializerJson
const string IG.Script.Script_Misc.ConstSerializerJson = "SerializerJson" static
Test of JSON serializer.
Referenced by IG.Script.Script_Misc.Script_AddCommands(), TestOpt.IGLibShellExtMainProgram.TestMain(), and TestOpt.IGLibShellMainProgram.TestMain().
ConstHelpSerializerJson
const string IG.Script.Script_Misc.ConstHelpSerializerJson = "Tests of JSON serialization." static
Referenced by IG.Script.Script_Misc.Script_AddCommands().
ConstExpressionEvaluatorJavaScript
const string IG.Script.Script_Misc.ConstExpressionEvaluatorJavaScript = "ExpressionEvaluatorJs" static
JavaScript - based expression evaluator.
Referenced by IG.Script.Script_Misc.Script_AddCommands(), TestOpt.IGLibShellExtMainProgram.TestMain(), and TestOpt.IGLibShellMainProgram.TestMain().
ConstHelpExpressionEvaluatorJavaScript
const string IG.Script.Script_Misc.ConstHelpExpressionEvaluatorJavaScript = "Tests of JavaScript based Expression evaluator." static
Referenced by IG.Script.Script_Misc.Script_AddCommands().
ConstRegisterable_IdGenerator
const string IG.Script.Script_Misc.ConstRegisterable_IdGenerator = "Registerable_IdGenerator" static
Test of Registerable classes and ID generators.
Referenced by IG.Script.Script_Misc.Script_AddCommands(), TestOpt.IGLibShellExtMainProgram.TestMain(), and TestOpt.IGLibShellMainProgram.TestMain().
ConstHelpRegisterable_IdGenerator
const string IG.Script.Script_Misc.ConstHelpRegisterable_IdGenerator = "Test of IRegisterable interface and ID generator." static
Referenced by IG.Script.Script_Misc.Script_AddCommands().
ConstExoticAndObsolete
const string IG.Script.Script_Misc.ConstExoticAndObsolete = "Registerable_IdGenerator" static
Test of exotic and obsolete classes.
Referenced by IG.Script.Script_Misc.Script_AddCommands().
ConstHelpExoticAndObsolete
const string IG.Script.Script_Misc.ConstHelpExoticAndObsolete = "Test of IRegisterable interface and ID generator." static
Referenced by IG.Script.Script_Misc.Script_AddCommands().
The documentation for this class was generated from the following file:
igtest/IGLibTestShell/00testscriptsopt/tests/Script_Misc.cs