Doc: IGLib EXTENDED: Color.MainForm Class Reference
Color.MainForm Class Reference
Summary description for Form1.
Public Member Functions
MainForm ()
MainForm ()
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void randomizeButton_Click (object sender, System.EventArgs e)
void RandomizeNetwork ()
void UpdateMap ()
void mapPanel_Paint (object sender, System.Windows.Forms.PaintEventArgs e)
void EnableControls (bool enable)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void randomizeButton_Click (object sender, System.EventArgs e)
void RandomizeNetwork ()
void UpdateMap ()
void mapPanel_Paint (object sender, System.Windows.Forms.PaintEventArgs e)
void EnableControls (bool enable)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
delegate void SetTextCallback (System.Windows.Forms.Control control, string text)
void SetText (System.Windows.Forms.Control control, string text)
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void randomizeButton_Click (object sender, System.EventArgs e)
void RandomizeNetwork ()
void UpdateMap ()
void mapPanel_Paint (object sender, System.Windows.Forms.PaintEventArgs e)
delegate void EnableCallback (bool enable)
void EnableControls (bool enable)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
Static Private Member Functions
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
Private Attributes
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.Panel mapPanel
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.Label label1
System.Windows.Forms.TextBox iterationsBox
System.Windows.Forms.Label label2
System.Windows.Forms.TextBox rateBox
System.Windows.Forms.Label label3
System.Windows.Forms.TextBox radiusBox
System.Windows.Forms.Label label4
System.Windows.Forms.Button startButton
System.Windows.Forms.Button stopButton
System.Windows.Forms.Button randomizeButton
System.Windows.Forms.Label label5
System.Windows.Forms.TextBox currentIterationBox
System.ComponentModel.Container components = null
Required designer variable.
DistanceNetwork network
Bitmap mapBitmap
Random rand = new Random()
int iterations = 5000
double learningRate = 0.1
double radius = 15
Thread workerThread = null
bool needToStop = false
volatile bool needToStop = false
Detailed Description
Summary description for Form1.
Summary description for MainForm.
Constructor & Destructor Documentation
MainForm() [1/3]
Color.MainForm.MainForm () inline
References Color.MainForm.InitializeComponent(), Color.MainForm.mapBitmap, Color.MainForm.network, Color.MainForm.RandomizeNetwork(), and Color.MainForm.UpdateSettings().
Referenced by Color.MainForm.Main().
MainForm() [2/3]
Color.MainForm.MainForm () inline
References Color.MainForm.InitializeComponent(), Color.MainForm.mapBitmap, Color.MainForm.network, Color.MainForm.RandomizeNetwork(), and Color.MainForm.UpdateSettings().
MainForm() [3/3]
Color.MainForm.MainForm () inline
References Color.MainForm.InitializeComponent(), Color.MainForm.mapBitmap, Color.MainForm.network, Color.MainForm.RandomizeNetwork(), and Color.MainForm.UpdateSettings().
Member Function Documentation
Dispose() [1/3]
override void Color.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References Color.MainForm.components.
InitializeComponent() [1/3]
void Color.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by Color.MainForm.MainForm().
Main() [1/3]
static void Color.MainForm.Main () inline static private
The main entry point for the application.
References Color.MainForm.MainForm().
MainForm_Closing() [1/3]
void Color.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References Color.MainForm.needToStop, and Color.MainForm.workerThread.
UpdateSettings() [1/3]
void Color.MainForm.UpdateSettings () inline private
References Color.MainForm.iterations, Color.MainForm.iterationsBox, Color.MainForm.learningRate, Color.MainForm.radius, Color.MainForm.radiusBox, and Color.MainForm.rateBox.
Referenced by Color.MainForm.MainForm(), and Color.MainForm.startButton_Click().
randomizeButton_Click() [1/3]
void Color.MainForm.randomizeButton_Click (object sender, System.EventArgs e) inline private
References Color.MainForm.RandomizeNetwork().
RandomizeNetwork() [1/3]
void Color.MainForm.RandomizeNetwork () inline private
References Color.MainForm.network, AForge.Neuro.Network.Randomize(), AForge.Neuro.Neuron.RandRange, and Color.MainForm.UpdateMap().
Referenced by Color.MainForm.MainForm(), and Color.MainForm.randomizeButton_Click().
UpdateMap() [1/3]
void Color.MainForm.UpdateMap () inline private
References Color.MainForm.mapBitmap, Color.MainForm.mapPanel, and Color.MainForm.network.
Referenced by Color.MainForm.RandomizeNetwork(), and Color.MainForm.SearchSolution().
mapPanel_Paint() [1/3]
void Color.MainForm.mapPanel_Paint (object sender, System.Windows.Forms.PaintEventArgs e) inline private
References Color.MainForm.mapBitmap.
EnableControls() [1/3]
void Color.MainForm.EnableControls (bool enable) inline private
References Color.MainForm.iterationsBox, Color.MainForm.radiusBox, Color.MainForm.randomizeButton, Color.MainForm.rateBox, Color.MainForm.startButton, and Color.MainForm.stopButton.
Referenced by Color.MainForm.EnableControls(), Color.MainForm.SearchSolution(), and Color.MainForm.startButton_Click().
startButton_Click() [1/3]
void Color.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References Color.MainForm.EnableControls(), Color.MainForm.iterations, Color.MainForm.iterationsBox, Color.MainForm.learningRate, Color.MainForm.needToStop, Color.MainForm.radius, Color.MainForm.radiusBox, Color.MainForm.rateBox, Color.MainForm.SearchSolution(), Color.MainForm.UpdateSettings(), and Color.MainForm.workerThread.
stopButton_Click() [1/3]
void Color.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References Color.MainForm.needToStop, and Color.MainForm.workerThread.
SearchSolution() [1/3]
void Color.MainForm.SearchSolution () inline private
References Color.MainForm.currentIterationBox, Color.MainForm.EnableControls(), Color.MainForm.iterations, AForge.Neuro.Learning.SOMLearning.LearningRadius, AForge.Neuro.Learning.SOMLearning.LearningRate, Color.MainForm.learningRate, Color.MainForm.needToStop, Color.MainForm.network, Color.MainForm.radius, Color.MainForm.rand, AForge.Neuro.Learning.SOMLearning.Run(), and Color.MainForm.UpdateMap().
Referenced by Color.MainForm.startButton_Click().
Dispose() [2/3]
override void Color.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References Color.MainForm.components.
InitializeComponent() [2/3]
void Color.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [2/3]
static void Color.MainForm.Main () inline static private
The main entry point for the application.
References Color.MainForm.MainForm().
MainForm_Closing() [2/3]
void Color.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References Color.MainForm.needToStop, and Color.MainForm.workerThread.
UpdateSettings() [2/3]
void Color.MainForm.UpdateSettings () inline private
References Color.MainForm.iterations, Color.MainForm.iterationsBox, Color.MainForm.learningRate, Color.MainForm.radius, Color.MainForm.radiusBox, and Color.MainForm.rateBox.
randomizeButton_Click() [2/3]
void Color.MainForm.randomizeButton_Click (object sender, System.EventArgs e) inline private
References Color.MainForm.RandomizeNetwork().
RandomizeNetwork() [2/3]
void Color.MainForm.RandomizeNetwork () inline private
References Color.MainForm.network, AForge.Neuro.Network.Randomize(), AForge.Neuro.Neuron.RandRange, and Color.MainForm.UpdateMap().
UpdateMap() [2/3]
void Color.MainForm.UpdateMap () inline private
References Color.MainForm.mapBitmap, Color.MainForm.mapPanel, and Color.MainForm.network.
mapPanel_Paint() [2/3]
void Color.MainForm.mapPanel_Paint (object sender, System.Windows.Forms.PaintEventArgs e) inline private
References Color.MainForm.mapBitmap.
EnableControls() [2/3]
void Color.MainForm.EnableControls (bool enable) inline private
References Color.MainForm.iterationsBox, Color.MainForm.radiusBox, Color.MainForm.randomizeButton, Color.MainForm.rateBox, Color.MainForm.startButton, and Color.MainForm.stopButton.
startButton_Click() [2/3]
void Color.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References Color.MainForm.EnableControls(), Color.MainForm.iterations, Color.MainForm.iterationsBox, Color.MainForm.learningRate, Color.MainForm.needToStop, Color.MainForm.radius, Color.MainForm.radiusBox, Color.MainForm.rateBox, Color.MainForm.SearchSolution(), Color.MainForm.UpdateSettings(), and Color.MainForm.workerThread.
stopButton_Click() [2/3]
void Color.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References Color.MainForm.needToStop, and Color.MainForm.workerThread.
SearchSolution() [2/3]
void Color.MainForm.SearchSolution () inline private
References Color.MainForm.currentIterationBox, Color.MainForm.EnableControls(), Color.MainForm.iterations, AForge.Neuro.Learning.SOMLearning.LearningRadius, AForge.Neuro.Learning.SOMLearning.LearningRate, Color.MainForm.learningRate, Color.MainForm.needToStop, Color.MainForm.network, Color.MainForm.radius, Color.MainForm.rand, AForge.Neuro.Learning.SOMLearning.Run(), and Color.MainForm.UpdateMap().
Dispose() [3/3]
override void Color.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References Color.MainForm.components.
InitializeComponent() [3/3]
void Color.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [3/3]
static void Color.MainForm.Main () inline static private
The main entry point for the application.
References Color.MainForm.MainForm().
SetTextCallback()
delegate void Color.MainForm.SetTextCallback (System.Windows.Forms.Control control, string text) private
Referenced by Color.MainForm.SetText().
SetText()
void Color.MainForm.SetText (System.Windows.Forms.Control control, string text) inline private
References Color.MainForm.SetTextCallback().
Referenced by Color.MainForm.SearchSolution().
MainForm_Closing() [3/3]
void Color.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References Color.MainForm.needToStop, and Color.MainForm.workerThread.
UpdateSettings() [3/3]
void Color.MainForm.UpdateSettings () inline private
References Color.MainForm.iterations, Color.MainForm.iterationsBox, Color.MainForm.learningRate, Color.MainForm.radius, Color.MainForm.radiusBox, and Color.MainForm.rateBox.
randomizeButton_Click() [3/3]
void Color.MainForm.randomizeButton_Click (object sender, System.EventArgs e) inline private
References Color.MainForm.RandomizeNetwork().
RandomizeNetwork() [3/3]
void Color.MainForm.RandomizeNetwork () inline private
References Color.MainForm.network, AForge.Neuro.Network.Randomize(), AForge.Neuro.Neuron.RandRange, and Color.MainForm.UpdateMap().
UpdateMap() [3/3]
void Color.MainForm.UpdateMap () inline private
References AForge.Neuro.Network.Layers, Color.MainForm.mapBitmap, Color.MainForm.mapPanel, Color.MainForm.network, AForge.Neuro.Layer.Neurons, and AForge.Neuro.Neuron.Weights.
mapPanel_Paint() [3/3]
void Color.MainForm.mapPanel_Paint (object sender, System.Windows.Forms.PaintEventArgs e) inline private
References Color.MainForm.mapBitmap.
EnableCallback()
delegate void Color.MainForm.EnableCallback (bool enable) private
Referenced by Color.MainForm.EnableControls().
EnableControls() [3/3]
void Color.MainForm.EnableControls (bool enable) inline private
References Color.MainForm.EnableCallback(), Color.MainForm.EnableControls(), Color.MainForm.iterationsBox, Color.MainForm.radiusBox, Color.MainForm.randomizeButton, Color.MainForm.rateBox, Color.MainForm.startButton, and Color.MainForm.stopButton.
startButton_Click() [3/3]
void Color.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References Color.MainForm.EnableControls(), Color.MainForm.iterations, Color.MainForm.iterationsBox, Color.MainForm.learningRate, Color.MainForm.needToStop, Color.MainForm.radius, Color.MainForm.radiusBox, Color.MainForm.rateBox, Color.MainForm.SearchSolution(), Color.MainForm.UpdateSettings(), and Color.MainForm.workerThread.
stopButton_Click() [3/3]
void Color.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References Color.MainForm.needToStop, and Color.MainForm.workerThread.
SearchSolution() [3/3]
void Color.MainForm.SearchSolution () inline private
References Color.MainForm.currentIterationBox, Color.MainForm.EnableControls(), Color.MainForm.iterations, AForge.Neuro.Learning.SOMLearning.LearningRadius, AForge.Neuro.Learning.SOMLearning.LearningRate, Color.MainForm.learningRate, Color.MainForm.needToStop, Color.MainForm.network, Color.MainForm.radius, Color.MainForm.rand, AForge.Neuro.Learning.SOMLearning.Run(), Color.MainForm.SetText(), and Color.MainForm.UpdateMap().
Member Data Documentation
groupBox1
System Windows Forms GroupBox Color.MainForm.groupBox1 private
mapPanel
System Windows Forms Panel Color.MainForm.mapPanel private
Referenced by Color.MainForm.UpdateMap().
groupBox2
System Windows Forms GroupBox Color.MainForm.groupBox2 private
label1
System Windows Forms Label Color.MainForm.label1 private
iterationsBox
System Windows Forms TextBox Color.MainForm.iterationsBox private
Referenced by Color.MainForm.EnableControls(), Color.MainForm.startButton_Click(), and Color.MainForm.UpdateSettings().
label2
System Windows Forms Label Color.MainForm.label2 private
rateBox
System Windows Forms TextBox Color.MainForm.rateBox private
Referenced by Color.MainForm.EnableControls(), Color.MainForm.startButton_Click(), and Color.MainForm.UpdateSettings().
label3
System Windows Forms Label Color.MainForm.label3 private
radiusBox
System Windows Forms TextBox Color.MainForm.radiusBox private
Referenced by Color.MainForm.EnableControls(), Color.MainForm.startButton_Click(), and Color.MainForm.UpdateSettings().
label4
System Windows Forms Label Color.MainForm.label4 private
startButton
System Windows Forms Button Color.MainForm.startButton private
Referenced by Color.MainForm.EnableControls().
stopButton
System Windows Forms Button Color.MainForm.stopButton private
Referenced by Color.MainForm.EnableControls().
randomizeButton
System Windows Forms Button Color.MainForm.randomizeButton private
Referenced by Color.MainForm.EnableControls().
label5
System Windows Forms Label Color.MainForm.label5 private
currentIterationBox
System Windows Forms TextBox Color.MainForm.currentIterationBox private
Referenced by Color.MainForm.SearchSolution().
components
System ComponentModel Container Color.MainForm.components = null private
Required designer variable.
Referenced by Color.MainForm.Dispose().
network
DistanceNetwork Color.MainForm.network private
Referenced by Color.MainForm.MainForm(), Color.MainForm.RandomizeNetwork(), Color.MainForm.SearchSolution(), and Color.MainForm.UpdateMap().
mapBitmap
Bitmap Color.MainForm.mapBitmap private
Referenced by Color.MainForm.MainForm(), Color.MainForm.mapPanel_Paint(), and Color.MainForm.UpdateMap().
rand
Random Color.MainForm.rand = new Random() private
Referenced by Color.MainForm.SearchSolution().
iterations
int Color.MainForm.iterations = 5000 private
Referenced by Color.MainForm.SearchSolution(), Color.MainForm.startButton_Click(), and Color.MainForm.UpdateSettings().
learningRate
double Color.MainForm.learningRate = 0.1 private
Referenced by Color.MainForm.SearchSolution(), Color.MainForm.startButton_Click(), and Color.MainForm.UpdateSettings().
radius
double Color.MainForm.radius = 15 private
Referenced by Color.MainForm.SearchSolution(), Color.MainForm.startButton_Click(), and Color.MainForm.UpdateSettings().
workerThread
Thread Color.MainForm.workerThread = null private
Referenced by Color.MainForm.MainForm_Closing(), Color.MainForm.startButton_Click(), and Color.MainForm.stopButton_Click().
needToStop [1/2]
bool Color.MainForm.needToStop = false private
Referenced by Color.MainForm.MainForm_Closing(), Color.MainForm.SearchSolution(), Color.MainForm.startButton_Click(), and Color.MainForm.stopButton_Click().
needToStop [2/2]
volatile bool Color.MainForm.needToStop = false private
The documentation for this class was generated from the following file:
shelldev/lib/external/neuralnetworks/neuro_src/Samples/Neuro/SOM/Color/Backup/MainForm.cs