Doc: IGLib EXTENDED: Test.TridiagonalMatrixTest Class Reference
Test.TridiagonalMatrixTest Class Reference
Public Member Functions
TridiagonalMatrix CreateRandomTridiagonalMatrix (int n)
TridiagonalMatrix CreateRandomTridiagonalMatrix (int n, Random rng)
void TridiagonalMatrixAccessTest ()
void TridiagonalMatrixInvalidSetTest ()
void TridiagonalMatrixArithmeticTest ()
void TridiagonalMatrixDuplicationTest ()
void TridiagonalMatrixLUDecompositionTest ()
Properties
TestContext TestContext [get, set]
Private Attributes
TestContext testContextInstance
Member Function Documentation
CreateRandomTridiagonalMatrix() [1/2]
TridiagonalMatrix Test.TridiagonalMatrixTest.CreateRandomTridiagonalMatrix (int n) inline
Referenced by Test.TridiagonalMatrixTest.TridiagonalMatrixAccessTest(), Test.TridiagonalMatrixTest.TridiagonalMatrixArithmeticTest(), Test.TridiagonalMatrixTest.TridiagonalMatrixDuplicationTest(), and Test.TridiagonalMatrixTest.TridiagonalMatrixLUDecompositionTest().
CreateRandomTridiagonalMatrix() [2/2]
TridiagonalMatrix Test.TridiagonalMatrixTest.CreateRandomTridiagonalMatrix (int n, Random rng) inline
TridiagonalMatrixAccessTest()
void Test.TridiagonalMatrixTest.TridiagonalMatrixAccessTest () inline
References Test.TridiagonalMatrixTest.CreateRandomTridiagonalMatrix().
TridiagonalMatrixInvalidSetTest()
void Test.TridiagonalMatrixTest.TridiagonalMatrixInvalidSetTest () inline
TridiagonalMatrixArithmeticTest()
void Test.TridiagonalMatrixTest.TridiagonalMatrixArithmeticTest () inline
References Test.TridiagonalMatrixTest.CreateRandomTridiagonalMatrix().
TridiagonalMatrixDuplicationTest()
void Test.TridiagonalMatrixTest.TridiagonalMatrixDuplicationTest () inline
References Test.TridiagonalMatrixTest.CreateRandomTridiagonalMatrix(), and Meta.Numerics.Matrices.TridiagonalMatrix.Transpose().
TridiagonalMatrixLUDecompositionTest()
void Test.TridiagonalMatrixTest.TridiagonalMatrixLUDecompositionTest () inline
References Test.TridiagonalMatrixTest.CreateRandomTridiagonalMatrix(), Meta.Numerics.Matrices.TridiagonalLUDecomposition.Determinant(), Meta.Numerics.Matrices.TridiagonalLUDecomposition.Dimension, Meta.Numerics.Matrices.TridiagonalLUDecomposition.Inverse(), and Meta.Numerics.Matrices.TridiagonalLUDecomposition.Solve().
Member Data Documentation
testContextInstance
TestContext Test.TridiagonalMatrixTest.testContextInstance private
Property Documentation
TestContext
TestContext Test.TridiagonalMatrixTest.TestContext get set
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/TridiagonalMatrixTest.cs