Doc: IGLib EXTENDED: NUnit.ConsoleRunner.TestEventHandler Class Reference
NUnit.ConsoleRunner.TestEventHandler Class Reference
TestEventHandler processes events from the running test for the console runner.
Public Member Functions
TestEventHandler (TextWriter outWriter, string displayLabels, bool teamCity)
void OnTestEvent (string report)
Handle a progress report or other event.
override object InitializeLifetimeService ()
Private Member Functions
void TestFinished (XmlNode testResult)
void SuiteFinished (XmlNode testResult)
void WriteTestLabel (string name)
void WriteTestOutput (XmlNode outputNode)
Private Attributes
readonly string _displayLabels
readonly TextWriter _outWriter
readonly TeamCityServiceMessagePublisher _teamCity
Detailed Description
TestEventHandler processes events from the running test for the console runner.
Constructor & Destructor Documentation
TestEventHandler()
NUnit.ConsoleRunner.TestEventHandler.TestEventHandler (TextWriter outWriter, string displayLabels, bool teamCity) inline
References NUnit.ConsoleRunner.TestEventHandler._displayLabels, NUnit.ConsoleRunner.TestEventHandler._outWriter, and NUnit.ConsoleRunner.TestEventHandler._teamCity.
Member Function Documentation
OnTestEvent()
void NUnit.ConsoleRunner.TestEventHandler.OnTestEvent (string report) inline
Handle a progress report or other event.
Parameters
report An XML progress report.
Implements NUnit.Engine.ITestEventListener.
References NUnit.ConsoleRunner.TestEventHandler._teamCity, NUnit.ConsoleRunner.TestEventHandler.SuiteFinished(), and NUnit.ConsoleRunner.TestEventHandler.TestFinished().
TestFinished()
void NUnit.ConsoleRunner.TestEventHandler.TestFinished (XmlNode testResult) inline private
References NUnit.ConsoleRunner.TestEventHandler._displayLabels, NUnit.ConsoleRunner.TestEventHandler.WriteTestLabel(), and NUnit.ConsoleRunner.TestEventHandler.WriteTestOutput().
Referenced by NUnit.ConsoleRunner.TestEventHandler.OnTestEvent().
SuiteFinished()
void NUnit.ConsoleRunner.TestEventHandler.SuiteFinished (XmlNode testResult) inline private
References NUnit.ConsoleRunner.TestEventHandler._displayLabels, NUnit.ConsoleRunner.TestEventHandler.WriteTestLabel(), and NUnit.ConsoleRunner.TestEventHandler.WriteTestOutput().
Referenced by NUnit.ConsoleRunner.TestEventHandler.OnTestEvent().
WriteTestLabel()
void NUnit.ConsoleRunner.TestEventHandler.WriteTestLabel (string name) inline private
References NUnit.ConsoleRunner.TestEventHandler._outWriter.
Referenced by NUnit.ConsoleRunner.TestEventHandler.SuiteFinished(), and NUnit.ConsoleRunner.TestEventHandler.TestFinished().
WriteTestOutput()
void NUnit.ConsoleRunner.TestEventHandler.WriteTestOutput (XmlNode outputNode) inline private
References NUnit.ConsoleRunner.TestEventHandler._outWriter.
Referenced by NUnit.ConsoleRunner.TestEventHandler.SuiteFinished(), and NUnit.ConsoleRunner.TestEventHandler.TestFinished().
InitializeLifetimeService()
override object NUnit.ConsoleRunner.TestEventHandler.InitializeLifetimeService () inline
Member Data Documentation
_displayLabels
readonly string NUnit.ConsoleRunner.TestEventHandler._displayLabels private
Referenced by NUnit.ConsoleRunner.TestEventHandler.SuiteFinished(), NUnit.ConsoleRunner.TestEventHandler.TestEventHandler(), and NUnit.ConsoleRunner.TestEventHandler.TestFinished().
_outWriter
readonly TextWriter NUnit.ConsoleRunner.TestEventHandler._outWriter private
Referenced by NUnit.ConsoleRunner.TestEventHandler.TestEventHandler(), NUnit.ConsoleRunner.TestEventHandler.WriteTestLabel(), and NUnit.ConsoleRunner.TestEventHandler.WriteTestOutput().
_teamCity
readonly TeamCityServiceMessagePublisher NUnit.ConsoleRunner.TestEventHandler._teamCity private
Referenced by NUnit.ConsoleRunner.TestEventHandler.OnTestEvent(), and NUnit.ConsoleRunner.TestEventHandler.TestEventHandler().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitConsole/nunit3-console/TestEventHandler.cs