Doc: IGLib EXTENDED: AForge.Neuro.DistanceNetwork Class Reference
AForge.Neuro.DistanceNetwork Class Reference
Distance network
Public Member Functions
DistanceNetwork (int inputsCount, int neuronsCount)
Initializes a new instance of the DistanceNetwork class
int GetWinner ()
Get winner neuron
DistanceNetwork (int inputsCount, int neuronsCount)
Initializes a new instance of the DistanceNetwork class
int GetWinner ()
Get winner neuron
DistanceNetwork (int inputsCount, int neuronsCount)
Initializes a new instance of the DistanceNetwork class.
int GetWinner ()
Get winner neuron.
Public Member Functions inherited from AForge.Neuro.Network
virtual double[] Compute (double[] input)
Compute output vector of the network
virtual void Randomize ()
Randomize layers of the network
virtual double[] Compute (double[] input)
Compute output vector of the network
virtual void Randomize ()
Randomize layers of the network
virtual double[] Compute (double[] input)
Compute output vector of the network.
virtual void Randomize ()
Randomize layers of the network.
void Save (string fileName)
Save network to specified file.
void Save (Stream stream)
Save network to specified file.
Properties
new DistanceLayer this[int index] [get]
Network's layers accessor
Properties inherited from AForge.Neuro.Network
int InputsCount [get]
Network's inputs count
int LayersCount [get]
Network's layers count
double[] Output [get]
Network's output vector
Layer this[int index] [get]
Network's layers accessor
Layer[] Layers [get]
Network's layers.
Additional Inherited Members
Static Public Member Functions inherited from AForge.Neuro.Network
static Network Load (string fileName)
Load network from specified file.
static Network Load (Stream stream)
Load network from specified file.
Protected Member Functions inherited from AForge.Neuro.Network
Network (int inputsCount, int layersCount)
Initializes a new instance of the Network class
Network (int inputsCount, int layersCount)
Initializes a new instance of the Network class
Network (int inputsCount, int layersCount)
Initializes a new instance of the Network class.
Protected Attributes inherited from AForge.Neuro.Network
int inputsCount
Network's inputs count
int layersCount
Network's layers count
Layer[] layers
Network's layers
double[] output
Network's output vector
Detailed Description
Distance network
Distance network.
Distance network is a neural network of only one distance layer. The network is a base for such neural networks as SOM, Elastic net, etc.
Constructor & Destructor Documentation
DistanceNetwork() [1/3]
AForge.Neuro.DistanceNetwork.DistanceNetwork (int inputsCount, int neuronsCount) inline
Initializes a new instance of the DistanceNetwork class
Parameters
inputsCount Network's inputs count
neuronsCount Network's neurons count
The new network will be randomized (see Neuron.Randomize method) after it is created.
References AForge.Neuro.Network.inputsCount, and AForge.Neuro.Network.layers.
DistanceNetwork() [2/3]
AForge.Neuro.DistanceNetwork.DistanceNetwork (int inputsCount, int neuronsCount) inline
Initializes a new instance of the DistanceNetwork class
Parameters
inputsCount Network's inputs count
neuronsCount Network's neurons count
The new network will be randomized (see Neuron.Randomize method) after it is created.
References AForge.Neuro.Network.inputsCount, and AForge.Neuro.Network.layers.
DistanceNetwork() [3/3]
AForge.Neuro.DistanceNetwork.DistanceNetwork (int inputsCount, int neuronsCount) inline
Initializes a new instance of the DistanceNetwork class.
Parameters
inputsCount Network's inputs count.
neuronsCount Network's neurons count.
The new network is randomized (see Neuron.Randomize method) after it is created.
References AForge.Neuro.Network.inputsCount, and AForge.Neuro.Network.layers.
Member Function Documentation
GetWinner() [1/3]
int AForge.Neuro.DistanceNetwork.GetWinner () inline
Get winner neuron
Returns
Index of the winner neuron
The method returns index of the neuron, which weights have the minimum distance from network's input.
References AForge.Neuro.Network.output.
Referenced by AForge.Neuro.Learning.ElasticNetworkLearning.Run(), AForge.Neuro.Learning.SOMLearning.Run(), and SOMOrganizing.MainForm.UpdateMap().
GetWinner() [2/3]
int AForge.Neuro.DistanceNetwork.GetWinner () inline
Get winner neuron
Returns
Index of the winner neuron
The method returns index of the neuron, which weights have the minimum distance from network's input.
References AForge.Neuro.Network.output.
GetWinner() [3/3]
int AForge.Neuro.DistanceNetwork.GetWinner () inline
Get winner neuron.
Returns
Index of the winner neuron.
The method returns index of the neuron, which weights have the minimum distance from network's input.
References AForge.Neuro.Network.output.
Property Documentation
this[int index]
new DistanceLayer AForge.Neuro.DistanceNetwork.this[int index] get
Network's layers accessor
Parameters
index Layer index
Allows to access network's layer.
The documentation for this class was generated from the following file:
shelldev/lib/external/neuralnetworks/neuro_src/Sources/Backup/Neuro/Networks/DistanceNetwork.cs