Doc: IGLib EXTENDED: AForge.Video.DirectShow.FilterInfo Class Reference
AForge.Video.DirectShow.FilterInfo Class Reference
DirectShow filter information.
Public Member Functions
FilterInfo (string monikerString)
Initializes a new instance of the FilterInfo class.
int CompareTo (object value)
Compare the object with another instance of this class.
Static Public Member Functions
static object CreateFilter (string filterMoniker)
Create an instance of the filter.
Public Attributes
readonly string Name
Filter name.
readonly string MonikerString
Filters's moniker string.
Private Member Functions
string GetMonikerString (IMoniker moniker)
string GetName (IMoniker moniker)
string GetName (string monikerString)
Detailed Description
DirectShow filter information.
Constructor & Destructor Documentation
FilterInfo()
AForge.Video.DirectShow.FilterInfo.FilterInfo (string monikerString) inline
Initializes a new instance of the FilterInfo class.
Parameters
monikerString Filters's moniker string.
References AForge.Video.DirectShow.FilterInfo.GetName(), AForge.Video.DirectShow.FilterInfo.MonikerString, and AForge.Video.DirectShow.FilterInfo.Name.
Referenced by AForge.Video.DirectShow.FilterInfo.CompareTo().
Member Function Documentation
CompareTo()
int AForge.Video.DirectShow.FilterInfo.CompareTo (object value) inline
Compare the object with another instance of this class.
Parameters
value Object to compare with.
Returns
A signed number indicating the relative values of this instance and value.
References AForge.Video.DirectShow.FilterInfo.FilterInfo().
CreateFilter()
static object AForge.Video.DirectShow.FilterInfo.CreateFilter (string filterMoniker) inline static
Create an instance of the filter.
Parameters
filterMoniker Filter's moniker string.
Returns
Returns filter's object, which implements IBaseFilter interface.
The returned filter's object should be released using Marshal.ReleaseComObject().
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.DisplayPropertyPage(), and AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
GetMonikerString()
string AForge.Video.DirectShow.FilterInfo.GetMonikerString (IMoniker moniker) inline private
GetName() [1/2]
string AForge.Video.DirectShow.FilterInfo.GetName (IMoniker moniker) inline private
Referenced by AForge.Video.DirectShow.FilterInfo.FilterInfo(), and AForge.Video.DirectShow.FilterInfo.GetName().
GetName() [2/2]
string AForge.Video.DirectShow.FilterInfo.GetName (string monikerString) inline private
References AForge.Video.DirectShow.FilterInfo.GetName().
Member Data Documentation
Name
readonly string AForge.Video.DirectShow.FilterInfo.Name
Filter name.
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.DisplayPropertyPage(), AForge.Video.DirectShow.FilterInfo.FilterInfo(), Snapshot_Maker.MainForm.MainForm_Load(), and AForge.Video.DirectShow.VideoCaptureDeviceForm.VideoCaptureDeviceForm().
MonikerString
readonly string AForge.Video.DirectShow.FilterInfo.MonikerString
Filters's moniker string.
Referenced by AForge.Video.DirectShow.FilterInfo.FilterInfo().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Video.DirectShow/FilterInfo.cs