Doc: IGLib EXTENDED: AForge.Math.Tests.Matrix3x3Test Class Reference
AForge.Math.Tests.Matrix3x3Test Class Reference
Public Member Functions
Matrix3x3Test ()
void ToArrayTest ()
void CreateFromRowsTest ()
void CreateFromColumnsTest ()
void CreateRotationYTest (float angle)
void CreateRotationXTest (float angle)
void CreateRotationZTest (float angle)
void CreateFromYawPitchRollTest (float yaw, float pitch, float roll)
void ExtractYawPitchRollTest (float yaw, float pitch, float roll)
void CreateDiagonalTest (float v00, float v11, float v22)
void DeterminantTest (float expectedDeterminant, float v00, float v01, float v02, float v10, float v11, float v12, float v20, float v21, float v22)
void InverseTest (float v00, float v01, float v02, float v10, float v11, float v12, float v20, float v21, float v22)
void AddMatricesTest ()
void SubtractMatricesTest ()
void MultiplyMatricesTest ()
Private Member Functions
void CompareMatrixWithArray (Matrix3x3 matrix, float[] array)
bool ApproximateEquals (Matrix3x3 matrix1, Matrix3x3 matrix2)
Private Attributes
Matrix3x3 a1 = new Matrix3x3()
Matrix3x3 a2 = new Matrix3x3()
Static Private Attributes
const float Epsilon = 0.000001f
Constructor & Destructor Documentation
Matrix3x3Test()
AForge.Math.Tests.Matrix3x3Test.Matrix3x3Test () inline
References AForge.Math.Tests.Matrix3x3Test.a1, AForge.Math.Tests.Matrix3x3Test.a2, AForge.Math.Matrix3x3.V00, AForge.Math.Matrix3x3.V01, AForge.Math.Matrix3x3.V02, AForge.Math.Matrix3x3.V10, AForge.Math.Matrix3x3.V11, AForge.Math.Matrix3x3.V12, AForge.Math.Matrix3x3.V20, AForge.Math.Matrix3x3.V21, and AForge.Math.Matrix3x3.V22.
Member Function Documentation
ToArrayTest()
void AForge.Math.Tests.Matrix3x3Test.ToArrayTest () inline
References AForge.Math.Matrix3x3.ToArray(), AForge.Math.Matrix3x3.V00, AForge.Math.Matrix3x3.V01, AForge.Math.Matrix3x3.V02, AForge.Math.Matrix3x3.V10, AForge.Math.Matrix3x3.V11, AForge.Math.Matrix3x3.V12, AForge.Math.Matrix3x3.V20, AForge.Math.Matrix3x3.V21, and AForge.Math.Matrix3x3.V22.
CreateFromRowsTest()
void AForge.Math.Tests.Matrix3x3Test.CreateFromRowsTest () inline
References AForge.Math.Matrix3x3.CreateFromRows(), AForge.Math.Matrix3x3.GetRow(), and AForge.Math.Matrix3x3.ToArray().
CreateFromColumnsTest()
void AForge.Math.Tests.Matrix3x3Test.CreateFromColumnsTest () inline
References AForge.Math.Matrix3x3.CreateFromColumns(), AForge.Math.Matrix3x3.GetColumn(), and AForge.Math.Matrix3x3.ToArray().
CreateRotationYTest()
void AForge.Math.Tests.Matrix3x3Test.CreateRotationYTest (float angle) inline
References AForge.Math.Tests.Matrix3x3Test.CompareMatrixWithArray(), and AForge.Math.Matrix3x3.CreateRotationY().
CreateRotationXTest()
void AForge.Math.Tests.Matrix3x3Test.CreateRotationXTest (float angle) inline
References AForge.Math.Tests.Matrix3x3Test.CompareMatrixWithArray(), and AForge.Math.Matrix3x3.CreateRotationX().
CreateRotationZTest()
void AForge.Math.Tests.Matrix3x3Test.CreateRotationZTest (float angle) inline
References AForge.Math.Tests.Matrix3x3Test.CompareMatrixWithArray(), and AForge.Math.Matrix3x3.CreateRotationZ().
CreateFromYawPitchRollTest()
void AForge.Math.Tests.Matrix3x3Test.CreateFromYawPitchRollTest (float yaw, float pitch, float roll) inline
References AForge.Math.Tests.Matrix3x3Test.CompareMatrixWithArray(), AForge.Math.Matrix3x3.CreateFromYawPitchRoll(), AForge.Math.Matrix3x3.CreateRotationX(), AForge.Math.Matrix3x3.CreateRotationY(), AForge.Math.Matrix3x3.CreateRotationZ(), and AForge.Math.Matrix3x3.ToArray().
ExtractYawPitchRollTest()
void AForge.Math.Tests.Matrix3x3Test.ExtractYawPitchRollTest (float yaw, float pitch, float roll) inline
References AForge.Math.Matrix3x3.CreateFromYawPitchRoll(), AForge.Math.Tests.Matrix3x3Test.Epsilon, and AForge.Math.Matrix3x3.ExtractYawPitchRoll().
CreateDiagonalTest()
void AForge.Math.Tests.Matrix3x3Test.CreateDiagonalTest (float v00, float v11, float v22) inline
References AForge.Math.Tests.Matrix3x3Test.CompareMatrixWithArray(), and AForge.Math.Matrix3x3.CreateDiagonal().
DeterminantTest()
void AForge.Math.Tests.Matrix3x3Test.DeterminantTest (float expectedDeterminant, float v00, float v01, float v02, float v10, float v11, float v12, float v20, float v21, float v22) inline
References AForge.Math.Matrix3x3.Determinant, AForge.Math.Matrix3x3.V00, AForge.Math.Matrix3x3.V01, AForge.Math.Matrix3x3.V02, AForge.Math.Matrix3x3.V10, AForge.Math.Matrix3x3.V11, AForge.Math.Matrix3x3.V12, AForge.Math.Matrix3x3.V20, AForge.Math.Matrix3x3.V21, and AForge.Math.Matrix3x3.V22.
InverseTest()
void AForge.Math.Tests.Matrix3x3Test.InverseTest (float v00, float v01, float v02, float v10, float v11, float v12, float v20, float v21, float v22) inline
References AForge.Math.Tests.Matrix3x3Test.ApproximateEquals(), AForge.Math.Matrix3x3.Identity, AForge.Math.Matrix3x3.Inverse(), AForge.Math.Matrix3x3.V00, AForge.Math.Matrix3x3.V01, AForge.Math.Matrix3x3.V02, AForge.Math.Matrix3x3.V10, AForge.Math.Matrix3x3.V11, AForge.Math.Matrix3x3.V12, AForge.Math.Matrix3x3.V20, AForge.Math.Matrix3x3.V21, and AForge.Math.Matrix3x3.V22.
AddMatricesTest()
void AForge.Math.Tests.Matrix3x3Test.AddMatricesTest () inline
References AForge.Math.Tests.Matrix3x3Test.a1, AForge.Math.Tests.Matrix3x3Test.a2, AForge.Math.Tests.Matrix3x3Test.ApproximateEquals(), AForge.Math.Matrix3x3.V00, AForge.Math.Matrix3x3.V01, AForge.Math.Matrix3x3.V02, AForge.Math.Matrix3x3.V10, AForge.Math.Matrix3x3.V11, AForge.Math.Matrix3x3.V12, AForge.Math.Matrix3x3.V20, AForge.Math.Matrix3x3.V21, and AForge.Math.Matrix3x3.V22.
SubtractMatricesTest()
void AForge.Math.Tests.Matrix3x3Test.SubtractMatricesTest () inline
References AForge.Math.Tests.Matrix3x3Test.a1, AForge.Math.Tests.Matrix3x3Test.a2, AForge.Math.Tests.Matrix3x3Test.ApproximateEquals(), AForge.Math.Matrix3x3.V00, AForge.Math.Matrix3x3.V01, AForge.Math.Matrix3x3.V02, AForge.Math.Matrix3x3.V10, AForge.Math.Matrix3x3.V11, AForge.Math.Matrix3x3.V12, AForge.Math.Matrix3x3.V20, AForge.Math.Matrix3x3.V21, and AForge.Math.Matrix3x3.V22.
MultiplyMatricesTest()
void AForge.Math.Tests.Matrix3x3Test.MultiplyMatricesTest () inline
References AForge.Math.Tests.Matrix3x3Test.a1, AForge.Math.Tests.Matrix3x3Test.a2, AForge.Math.Tests.Matrix3x3Test.ApproximateEquals(), AForge.Math.Matrix3x3.V00, AForge.Math.Matrix3x3.V01, AForge.Math.Matrix3x3.V02, AForge.Math.Matrix3x3.V10, AForge.Math.Matrix3x3.V11, AForge.Math.Matrix3x3.V12, AForge.Math.Matrix3x3.V20, AForge.Math.Matrix3x3.V21, and AForge.Math.Matrix3x3.V22.
CompareMatrixWithArray()
void AForge.Math.Tests.Matrix3x3Test.CompareMatrixWithArray (Matrix3x3 matrix, float[] array) inline private
References AForge.Math.Matrix3x3.ToArray().
Referenced by AForge.Math.Tests.Matrix3x3Test.CreateDiagonalTest(), AForge.Math.Tests.Matrix3x3Test.CreateFromYawPitchRollTest(), AForge.Math.Tests.Matrix3x3Test.CreateRotationXTest(), AForge.Math.Tests.Matrix3x3Test.CreateRotationYTest(), and AForge.Math.Tests.Matrix3x3Test.CreateRotationZTest().
ApproximateEquals()
bool AForge.Math.Tests.Matrix3x3Test.ApproximateEquals (Matrix3x3 matrix1, Matrix3x3 matrix2) inline private
References AForge.Math.Tests.Matrix3x3Test.Epsilon, AForge.Math.Matrix3x3.V00, AForge.Math.Matrix3x3.V01, AForge.Math.Matrix3x3.V02, AForge.Math.Matrix3x3.V10, AForge.Math.Matrix3x3.V11, AForge.Math.Matrix3x3.V12, AForge.Math.Matrix3x3.V20, AForge.Math.Matrix3x3.V21, and AForge.Math.Matrix3x3.V22.
Referenced by AForge.Math.Tests.Matrix3x3Test.AddMatricesTest(), AForge.Math.Tests.Matrix3x3Test.InverseTest(), AForge.Math.Tests.Matrix3x3Test.MultiplyMatricesTest(), and AForge.Math.Tests.Matrix3x3Test.SubtractMatricesTest().
Member Data Documentation
Epsilon
const float AForge.Math.Tests.Matrix3x3Test.Epsilon = 0.000001f static private
Referenced by AForge.Math.Tests.Matrix3x3Test.ApproximateEquals(), and AForge.Math.Tests.Matrix3x3Test.ExtractYawPitchRollTest().
a1
Matrix3x3 AForge.Math.Tests.Matrix3x3Test.a1 = new Matrix3x3() private
Referenced by AForge.Math.Tests.Matrix3x3Test.AddMatricesTest(), AForge.Math.Tests.Matrix3x3Test.Matrix3x3Test(), AForge.Math.Tests.Matrix3x3Test.MultiplyMatricesTest(), and AForge.Math.Tests.Matrix3x3Test.SubtractMatricesTest().
a2
Matrix3x3 AForge.Math.Tests.Matrix3x3Test.a2 = new Matrix3x3() private
Referenced by AForge.Math.Tests.Matrix3x3Test.AddMatricesTest(), AForge.Math.Tests.Matrix3x3Test.Matrix3x3Test(), AForge.Math.Tests.Matrix3x3Test.MultiplyMatricesTest(), and AForge.Math.Tests.Matrix3x3Test.SubtractMatricesTest().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Unit Tests/AForge.Math.Tests/Matrix3x3Test.cs