Doc: IGLib EXTENDED: AForge.Vision.Motion.TwoFramesDifferenceDetector Class Reference
AForge.Vision.Motion.TwoFramesDifferenceDetector Class Reference
Motion detector based on two continues frames difference.
Public Member Functions
TwoFramesDifferenceDetector ()
Initializes a new instance of the TwoFramesDifferenceDetector class.
TwoFramesDifferenceDetector (bool suppressNoise)
Initializes a new instance of the TwoFramesDifferenceDetector class.
unsafe void ProcessFrame (UnmanagedImage videoFrame)
Process new video frame.
void Reset ()
Reset motion detector to initial state.
Properties
int DifferenceThreshold [get, set]
Difference threshold value, [1, 255].
float MotionLevel [get]
Motion level value, [0, 1].
UnmanagedImage MotionFrame [get]
Motion frame containing detected areas of motion.
bool SuppressNoise [get, set]
Suppress noise in video frames or not.
Properties inherited from AForge.Vision.Motion.IMotionDetector
float MotionLevel [get]
Motion level value, [0, 1].
UnmanagedImage MotionFrame [get]
Motion frame containing detected areas of motion.
Private Attributes
int width
int height
int frameSize
UnmanagedImage previousFrame
UnmanagedImage motionFrame
UnmanagedImage tempFrame
int pixelsChanged
bool suppressNoise = true
int differenceThreshold = 15
int differenceThresholdNeg = -15
BinaryErosion3x3 erosionFilter = new BinaryErosion3x3()
object sync = new object()
Detailed Description
Motion detector based on two continues frames difference.
The class implements the simplest motion detection algorithm, which is based on difference of two continues frames. The difference frame is thresholded and the amount of difference pixels is calculated. To suppress stand-alone noisy pixels erosion morphological operator may be applied, which is controlled by SuppressNoise property.
Although the class may be used on its own to perform motion detection, it is preferred to use it in conjunction with MotionDetector class, which provides additional features and allows to use moton post processing algorithms.
Sample usage:
// create motion detector
MotionDetector detector = new MotionDetector(
    new TwoFramesDifferenceDetector( ),
    new MotionAreaHighlighting( ) );
// continuously feed video frames to motion detector
while (...)
{
    // process new video frame and check motion level
    if ( detector.ProcessFrame( videoFrame ) > 0.02 )
    {
        // ring alarm or do somethng else
    }
}
See also
MotionDetector
Constructor & Destructor Documentation
TwoFramesDifferenceDetector() [1/2]
AForge.Vision.Motion.TwoFramesDifferenceDetector.TwoFramesDifferenceDetector () inline
Initializes a new instance of the TwoFramesDifferenceDetector class.
TwoFramesDifferenceDetector() [2/2]
AForge.Vision.Motion.TwoFramesDifferenceDetector.TwoFramesDifferenceDetector (bool suppressNoise) inline
Initializes a new instance of the TwoFramesDifferenceDetector class.
Parameters
suppressNoise Suppress noise in video frames or not (see SuppressNoise property).
References AForge.Vision.Motion.TwoFramesDifferenceDetector.suppressNoise.
Member Function Documentation
ProcessFrame()
unsafe void AForge.Vision.Motion.TwoFramesDifferenceDetector.ProcessFrame (UnmanagedImage videoFrame) inline
Process new video frame.
Parameters
videoFrame Video frame to process (detect motion in).
Processes new frame from video source and detects motion in it.
Check MotionLevel property to get information about amount of motion (changes) in the processed frame.
Implements AForge.Vision.Motion.IMotionDetector.
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.Apply(), AForge.SystemTools.CopyUnmanagedMemory(), AForge.Imaging.UnmanagedImage.Create(), AForge.Vision.Motion.TwoFramesDifferenceDetector.differenceThreshold, AForge.Vision.Motion.TwoFramesDifferenceDetector.differenceThresholdNeg, AForge.Vision.Motion.TwoFramesDifferenceDetector.erosionFilter, AForge.Vision.Motion.TwoFramesDifferenceDetector.frameSize, AForge.Vision.Motion.TwoFramesDifferenceDetector.height, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Vision.Motion.TwoFramesDifferenceDetector.motionFrame, AForge.Vision.Motion.TwoFramesDifferenceDetector.pixelsChanged, AForge.Vision.Motion.TwoFramesDifferenceDetector.previousFrame, AForge.Imaging.UnmanagedImage.Stride, AForge.Vision.Motion.TwoFramesDifferenceDetector.suppressNoise, AForge.Vision.Motion.TwoFramesDifferenceDetector.sync, AForge.Vision.Motion.TwoFramesDifferenceDetector.tempFrame, AForge.Vision.Motion.TwoFramesDifferenceDetector.width, and AForge.Imaging.UnmanagedImage.Width.
Reset()
void AForge.Vision.Motion.TwoFramesDifferenceDetector.Reset () inline
Reset motion detector to initial state.
Resets internal state and variables of motion detection algorithm. Usually this is required to be done before processing new video source, but may be also done at any time to restart motion detection algorithm.
Implements AForge.Vision.Motion.IMotionDetector.
References AForge.Imaging.UnmanagedImage.Dispose(), AForge.Vision.Motion.TwoFramesDifferenceDetector.motionFrame, AForge.Vision.Motion.TwoFramesDifferenceDetector.previousFrame, AForge.Vision.Motion.TwoFramesDifferenceDetector.sync, and AForge.Vision.Motion.TwoFramesDifferenceDetector.tempFrame.
Member Data Documentation
width
int AForge.Vision.Motion.TwoFramesDifferenceDetector.width private
Referenced by AForge.Vision.Motion.TwoFramesDifferenceDetector.ProcessFrame().
height
int AForge.Vision.Motion.TwoFramesDifferenceDetector.height private
Referenced by AForge.Vision.Motion.TwoFramesDifferenceDetector.ProcessFrame().
frameSize
int AForge.Vision.Motion.TwoFramesDifferenceDetector.frameSize private
Referenced by AForge.Vision.Motion.TwoFramesDifferenceDetector.ProcessFrame().
previousFrame
UnmanagedImage AForge.Vision.Motion.TwoFramesDifferenceDetector.previousFrame private
Referenced by AForge.Vision.Motion.TwoFramesDifferenceDetector.ProcessFrame(), and AForge.Vision.Motion.TwoFramesDifferenceDetector.Reset().
motionFrame
UnmanagedImage AForge.Vision.Motion.TwoFramesDifferenceDetector.motionFrame private
Referenced by AForge.Vision.Motion.TwoFramesDifferenceDetector.ProcessFrame(), and AForge.Vision.Motion.TwoFramesDifferenceDetector.Reset().
tempFrame
UnmanagedImage AForge.Vision.Motion.TwoFramesDifferenceDetector.tempFrame private
Referenced by AForge.Vision.Motion.TwoFramesDifferenceDetector.ProcessFrame(), and AForge.Vision.Motion.TwoFramesDifferenceDetector.Reset().
pixelsChanged
int AForge.Vision.Motion.TwoFramesDifferenceDetector.pixelsChanged private
Referenced by AForge.Vision.Motion.TwoFramesDifferenceDetector.ProcessFrame().
suppressNoise
bool AForge.Vision.Motion.TwoFramesDifferenceDetector.suppressNoise = true private
Referenced by AForge.Vision.Motion.TwoFramesDifferenceDetector.ProcessFrame(), and AForge.Vision.Motion.TwoFramesDifferenceDetector.TwoFramesDifferenceDetector().
differenceThreshold
int AForge.Vision.Motion.TwoFramesDifferenceDetector.differenceThreshold = 15 private
Referenced by AForge.Vision.Motion.TwoFramesDifferenceDetector.ProcessFrame().
differenceThresholdNeg
int AForge.Vision.Motion.TwoFramesDifferenceDetector.differenceThresholdNeg = -15 private
Referenced by AForge.Vision.Motion.TwoFramesDifferenceDetector.ProcessFrame().
erosionFilter
BinaryErosion3x3 AForge.Vision.Motion.TwoFramesDifferenceDetector.erosionFilter = new BinaryErosion3x3() private
Referenced by AForge.Vision.Motion.TwoFramesDifferenceDetector.ProcessFrame().
sync
object AForge.Vision.Motion.TwoFramesDifferenceDetector.sync = new object() private
Referenced by AForge.Vision.Motion.TwoFramesDifferenceDetector.ProcessFrame(), and AForge.Vision.Motion.TwoFramesDifferenceDetector.Reset().
Property Documentation
DifferenceThreshold
int AForge.Vision.Motion.TwoFramesDifferenceDetector.DifferenceThreshold get set
Difference threshold value, [1, 255].
The value specifies the amount off difference between pixels, which is treated as motion pixel.
Default value is set to 15.
MotionLevel
float AForge.Vision.Motion.TwoFramesDifferenceDetector.MotionLevel get
Motion level value, [0, 1].
Amount of changes in the last processed frame. For example, if value of this property equals to 0.1, then it means that last processed frame has 10% difference with previous frame.
MotionFrame
UnmanagedImage AForge.Vision.Motion.TwoFramesDifferenceDetector.MotionFrame get
Motion frame containing detected areas of motion.
Motion frame is a grayscale image, which shows areas of detected motion. All black pixels in the motion frame correspond to areas, where no motion is detected. But white pixels correspond to areas, where motion is detected.
<note>The property is set to null after processing of the first video frame by the algorithm.</note>
SuppressNoise
bool AForge.Vision.Motion.TwoFramesDifferenceDetector.SuppressNoise get set
Suppress noise in video frames or not.
The value specifies if additional filtering should be done to suppress standalone noisy pixels by applying 3x3 erosion image processing filter.
Default value is set to true.
<note>Turning the value on leads to more processing time of video frame.</note>
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Vision/Motion/TwoFramesDifferenceDetector.cs