Doc: IGLib EXTENDED: IG.Lib.MsgConst Class Reference
IG.Lib.MsgConst Class Reference
Constants related to msg for communication with BIS, conversion utilities from and to formats used in messageds, etc. Constants are not defined static in order to enable corrections for different variants of the program.
Public Member Functions
DateTime ConvertTime (string timestr)
Converts a atring that represents date and time in the messages to a DateTime object.
string ConvertTime (DateTime t)
Converts a DateTime object to a string that represents date and time in the messages.
string ConvertTime (DateTime t, bool includetime)
Converts a DateTime object to a string that represents date and time in the messages. Seconds are not included even if time is included.
string ConvertTime (DateTime t, bool includetime, bool underscores)
Converts a DateTime object to a string that represents date and time in the messages. Seconds are not included even if time is included.
string ConvertTime (DateTime t, bool includetime, bool includeseconds, bool underscores)
Converts a DateTime object to a string that represents date and time in the messages.
string TimeStamp (bool includetime, bool underscores)
Returns a timestamp for the Current time. The string is produced by ConvertTime() called with the Current time.
string TimeStamp (bool includetime)
Returns a timestamp for the Current time. The string is produced by ConvertTime() called with the Current time.
string TimeStamp ()
Returns a timestamp for the Current time. The string is produced by ConvertTime() called with the Current time.
OeAction ConvertOeAction (string actioncode)
Returns action corresponding to the specified action code for SpecimenObesrvationEvent.
string ConvertOeAction (OeAction action)
Converts OeAction enumerator to string value for Action element.
string ConvertOeActionCode (OeAction action)
Converts OeAction enumerator to string value for Action CODE element.
OoAction ConvertOoAction (string actioncode)
Returns action corresponding to the specified action code for SpecimenObservationOrder.
string ConvertOoAction (OoAction actioncode)
Returns a string corresponding to the specified observation order action code, as stated in the SpecimenObservationOrder specification.
string ConvertOoCode (OoAction actioncode)
Returns a string corresponding to the specified observation order action code, as stated in the SpecimenObservationOrder specification for the message code (not action code). This is used for generation of the appropriate XML message code attribute when this needs to be modified.
OoStatus ConvertOoStatus (string statuscode)
Returns observation order status corresponding to the status code.
string ConvertOoStatus (OoStatus statuscode)
Returns a string corresponding to the specified observation order status code.
ActionPriority ConvertActionPriority (string code)
Returns action priority corresponding to the string code.
string ConvertQuantity (decimal q)
Converts a quantity to string format that is used in messages (9 numerical digits, with eventual leading zeros, last two are after the comma).
decimal ConvertQuantity (string qstr)
Converts a string representation of quantity to number type. String form containts 9 numerical digits, with eventual leading zeros, last two are after the comma.
Properties
static MsgConst Const [get]
Returns the process-wide class containing constants used in BIS messages. Class is initialized with respect to the application variant that is currently running.
Properties inherited from IG.Lib.MsgConstObservationOrder
virtual IReporter R [get]
Reporter for this class.
bool OoCheckAll [set]
Static Private Attributes
static MsgConst _msgConst = null
Additional Inherited Members
Public Attributes inherited from IG.Lib.MsgConstFinancialTransaction
string FtCode = "FIAB_TE000001"
Public Attributes inherited from IG.Lib.MsgConstObservationEvent
string OeActionActivate = "POXX_HN111003"
Public Attributes inherited from IG.Lib.MsgConstObservationOrder
bool OoCheckAliveConsistency = false
string CreationTimeElement = "creationTime"
Name of the Root XML node for all messages.
string OoActionCreate = "POXX_HN121002"
string OoOrderStatusCompleted = "completed"
string OoMessageType = "Observation"
Public Attributes inherited from IG.Lib.MsgConstCommon
string ActionPriorityRoutine = "R"
string DiagnosisCodeSystem = "MKB10"
int DiagnosisTypeClinical = 1
int GenderMale = 1
readonly DateTime NullDateTime = new DateTime(1990, 1, 1)
int NullInt = -1
bool NullBool = false
string LabexId = "Labex"
string OoRootName = "MCCI_MT000100HT03.Message"
int OoGenderMale = 1
Detailed Description
Constants related to msg for communication with BIS, conversion utilities from and to formats used in messageds, etc. Constants are not defined static in order to enable corrections for different variants of the program.
Member Function Documentation
ConvertTime() [1/5]
DateTime IG.Lib.MsgConst.ConvertTime (string timestr) inline
Converts a atring that represents date and time in the messages to a DateTime object.
Parameters
timestr String that represents the time, format is "YYYYMMDDhhmmss".
Returns
Converted date and time object.
References IG.Lib.IReporterBase.Depth, IG.Lib.MsgConstObservationOrder.R, IG.Lib.IReporterBase.ReportInfo(), IG.Lib.IReporterBase.ReportWarning(), IG.Lib.ReporterBase.ReviseException(), and IG.Lib.IReporterBase.TreatInfo.
Referenced by IG.Lib.MsgConst.ConvertTime(), IG.Lib.MsgFinancialTransaction.GenerateMessageId(), IG.Lib.MsgObservationEvent.GenerateMessageId(), IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgFinancialTransaction.Read(), IG.Lib.DocFindings.Read(), IG.Lib.MsgObervationOrder.Read(), IG.Lib.MsgConst.TimeStamp(), IG.Lib.MsgFinancialTransaction.ToXml(), and IG.Lib.MsgObservationEvent.ToXml().
ConvertTime() [2/5]
string IG.Lib.MsgConst.ConvertTime (DateTime t) inline
Converts a DateTime object to a string that represents date and time in the messages.
Parameters
t Time to be converted to a string.
Returns
Converted date and time object string whose format is "YYYYMMDDhhmmss".
References IG.Lib.MsgConst.ConvertTime().
ConvertTime() [3/5]
string IG.Lib.MsgConst.ConvertTime (DateTime t, bool includetime) inline
Converts a DateTime object to a string that represents date and time in the messages. Seconds are not included even if time is included.
Parameters
t Time to be converted to a string. Seconds are not included even if time is included.
includetime If true then time is also included, otherwise only date is included.
Returns
Converted date and time object string whose format is: "YYYYMMDDhhmmss" if includetime = true. "YYYYMMDD" if includetime = false.
References IG.Lib.MsgConst.ConvertTime().
ConvertTime() [4/5]
string IG.Lib.MsgConst.ConvertTime (DateTime t, bool includetime, bool underscores) inline
Converts a DateTime object to a string that represents date and time in the messages. Seconds are not included even if time is included.
Parameters
t Time to be converted to a string.
includetime If true then time is also included, otherwise only date is included.
underscores
Returns
Converted date and time object string whose format can be: "YYYYMMDDhhmmss" (includetime = true, underscores = false) "YYYYMMDD" (includetime = false, underscores = false) "YYYY_MM_DD_hh_mm_ss" (includetime = true, underscores = true) "YYYY_MM_DD" (includetime = false, underscores = true)
References IG.Lib.MsgConst.ConvertTime().
ConvertTime() [5/5]
string IG.Lib.MsgConst.ConvertTime (DateTime t, bool includetime, bool includeseconds, bool underscores) inline
Converts a DateTime object to a string that represents date and time in the messages.
Parameters
t Time to be converted to a string.
includetime If true then time is also included, otherwise only date is included.
includeseconds If true then seconds time are also included in time.
underscores
Returns
Converted date and time object string whose format can be: "YYYYMMDDhhmmss" (includetime = true, underscores = false) "YYYYMMDD" (includetime = false, underscores = false) "YYYY_MM_DD_hh_mm_ss" (includetime = true, underscores = true) "YYYY_MM_DD" (includetime = false, underscores = true)
References IG.Lib.IReporterBase.Depth, IG.Lib.MsgConstObservationOrder.R, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.ReporterBase.ReviseException(), and IG.Lib.IReporterBase.TreatInfo.
TimeStamp() [1/3]
string IG.Lib.MsgConst.TimeStamp (bool includetime, bool underscores) inline
Returns a timestamp for the Current time. The string is produced by ConvertTime() called with the Current time.
References IG.Lib.MsgConst.ConvertTime().
Referenced by LabexBis.BisCommunicationSettings.MessageFileName().
TimeStamp() [2/3]
string IG.Lib.MsgConst.TimeStamp (bool includetime) inline
Returns a timestamp for the Current time. The string is produced by ConvertTime() called with the Current time.
References IG.Lib.MsgConst.ConvertTime().
TimeStamp() [3/3]
string IG.Lib.MsgConst.TimeStamp () inline
Returns a timestamp for the Current time. The string is produced by ConvertTime() called with the Current time.
References IG.Lib.MsgConst.ConvertTime().
ConvertOeAction() [1/2]
OeAction IG.Lib.MsgConst.ConvertOeAction (string actioncode) inline
Returns action corresponding to the specified action code for SpecimenObesrvationEvent.
Parameters
actioncode Action code.
Returns
References IG.Lib.MsgConstObservationEvent.OeActionActivate, IG.Lib.MsgConstObservationEvent.OeActionComplete, IG.Lib.MsgConstObservationEvent.OeActionReviseCompleted, IG.Lib.MsgConstObservationEvent.OeCodeActivate, IG.Lib.MsgConstObservationEvent.OeCodeComplete, and IG.Lib.MsgConstObservationEvent.OeCodeReviseCompleted.
Referenced by IG.Lib.MsgObservationEvent.ToString(), and IG.Lib.MsgObservationEvent.ToXml().
ConvertOeAction() [2/2]
string IG.Lib.MsgConst.ConvertOeAction (OeAction action) inline
Converts OeAction enumerator to string value for Action element.
References IG.Lib.MsgConstObservationEvent.OeActionActivate, IG.Lib.MsgConstObservationEvent.OeActionComplete, and IG.Lib.MsgConstObservationEvent.OeActionReviseCompleted.
ConvertOeActionCode()
string IG.Lib.MsgConst.ConvertOeActionCode (OeAction action) inline
Converts OeAction enumerator to string value for Action CODE element.
References IG.Lib.MsgConstObservationEvent.OeCodeActivate, IG.Lib.MsgConstObservationEvent.OeCodeComplete, and IG.Lib.MsgConstObservationEvent.OeCodeReviseCompleted.
Referenced by IG.Lib.MsgObservationEvent.ToXml().
ConvertOoAction() [1/2]
OoAction IG.Lib.MsgConst.ConvertOoAction (string actioncode) inline
Returns action corresponding to the specified action code for SpecimenObservationOrder.
Parameters
actioncode Action code.
Returns
References IG.Lib.MsgConstObservationOrder.OoActionCreate, IG.Lib.MsgConstObservationOrder.OoActionNullify, IG.Lib.MsgConstObservationOrder.OoActionRevise, IG.Lib.MsgConstObservationOrder.OoCodeCreate, IG.Lib.MsgConstObservationOrder.OoCodeNullify, and IG.Lib.MsgConstObservationOrder.OoCodeRevise.
Referenced by IG.Lib.MsgObervationOrder.Read(), IG.Lib.MsgObervationOrder.SetOoAction(), and IG.Lib.MsgObervationOrder.ToString().
ConvertOoAction() [2/2]
string IG.Lib.MsgConst.ConvertOoAction (OoAction actioncode) inline
Returns a string corresponding to the specified observation order action code, as stated in the SpecimenObservationOrder specification.
References IG.Lib.MsgConstObservationOrder.OoActionCreate, IG.Lib.MsgConstObservationOrder.OoActionNullify, and IG.Lib.MsgConstObservationOrder.OoActionRevise.
ConvertOoCode()
string IG.Lib.MsgConst.ConvertOoCode (OoAction actioncode) inline
Returns a string corresponding to the specified observation order action code, as stated in the SpecimenObservationOrder specification for the message code (not action code). This is used for generation of the appropriate XML message code attribute when this needs to be modified.
References IG.Lib.MsgConstObservationOrder.OoCodeCreate, IG.Lib.MsgConstObservationOrder.OoCodeNullify, and IG.Lib.MsgConstObservationOrder.OoCodeRevise.
Referenced by IG.Lib.MsgObervationOrder.SetOoAction().
ConvertOoStatus() [1/2]
OoStatus IG.Lib.MsgConst.ConvertOoStatus (string statuscode) inline
Returns observation order status corresponding to the status code.
References IG.Lib.MsgConstObservationOrder.OoOrderStatusActive, IG.Lib.MsgConstObservationOrder.OoOrderStatusCompleted, and IG.Lib.MsgConstObservationOrder.OoOrderStatusNullified.
Referenced by IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgFinancialTransaction.Read(), IG.Lib.MsgObervationOrder.Read(), IG.Lib.MsgFinancialTransaction.ToXml(), and IG.Lib.MsgObservationEvent.ToXml().
ConvertOoStatus() [2/2]
string IG.Lib.MsgConst.ConvertOoStatus (OoStatus statuscode) inline
Returns a string corresponding to the specified observation order status code.
References IG.Lib.MsgConstObservationOrder.OoOrderStatusActive, IG.Lib.MsgConstObservationOrder.OoOrderStatusCompleted, and IG.Lib.MsgConstObservationOrder.OoOrderStatusNullified.
ConvertActionPriority()
ActionPriority IG.Lib.MsgConst.ConvertActionPriority (string code) inline
Returns action priority corresponding to the string code.
References IG.Lib.MsgConstCommon.ActionPriorityCritical, IG.Lib.MsgConstCommon.ActionPriorityRoutine, and IG.Lib.MsgConstCommon.ActionPriorityUrgent.
Referenced by IG.Lib.MsgObervationOrder.CheckConsistency(), and IG.Lib.MsgObervationOrder.Read().
ConvertQuantity() [1/2]
string IG.Lib.MsgConst.ConvertQuantity (decimal q) inline
Converts a quantity to string format that is used in messages (9 numerical digits, with eventual leading zeros, last two are after the comma).
Parameters
q Quantity to be converted.
Returns
String representing the quantity in format suitable for messages.
Referenced by IG.Lib.MsgFinancialTransaction.Read(), and IG.Lib.MsgFinancialTransaction.ToXml().
ConvertQuantity() [2/2]
decimal IG.Lib.MsgConst.ConvertQuantity (string qstr) inline
Converts a string representation of quantity to number type. String form containts 9 numerical digits, with eventual leading zeros, last two are after the comma.
Parameters
q Quantity to be converted.
Returns
String representing the quantity in format suitable for messages.
Member Data Documentation
_msgConst
MsgConst IG.Lib.MsgConst._msgConst = null static private
Property Documentation
Const
MsgConst IG.Lib.MsgConst.Const static get
Returns the process-wide class containing constants used in BIS messages. Class is initialized with respect to the application variant that is currently running.
Referenced by IG.Lib.AutopsyAssociatedDisease.AutopsyAssociatedDisease(), IG.Lib.AutopsyBasicDisease.AutopsyBasicDisease(), IG.Lib.AutopsyDeathReason.AutopsyDeathReason(), IG.Lib.AutopsyOtherInformation.AutopsyOtherInformation(), IG.Lib.MsgObervationOrder.PrepareOoNullify(), IG.Lib.DocFindings.Read(), IG.Lib.MsgBase.SetSenderBis(), and IG.Lib.MsgBase.SetSenderLabex().
The documentation for this class was generated from the following file:
igtest/tmp_prem/prlab/LabexBis/MessagesBisConst.cs