Doc: IGLib EXTENDED: IG.Forms.BrowserSimpleWindow Class Reference
IG.Forms.BrowserSimpleWindow Class Reference
Public Member Functions
BrowserSimpleWindow ()
void OpenLocation (string location)
Public Attributes
BrowserSimpleControl browserForm
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void BrowserSimpleWindow_VisibleChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
Constructor & Destructor Documentation
BrowserSimpleWindow()
IG.Forms.BrowserSimpleWindow.BrowserSimpleWindow () inline
References IG.Forms.BrowserSimpleWindow.browserForm, and IG.Forms.BrowserSimpleWindow.InitializeComponent().
Member Function Documentation
BrowserSimpleWindow_VisibleChanged()
void IG.Forms.BrowserSimpleWindow.BrowserSimpleWindow_VisibleChanged (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleWindow.browserForm.
Referenced by IG.Forms.BrowserSimpleWindow.InitializeComponent().
OpenLocation()
void IG.Forms.BrowserSimpleWindow.OpenLocation (string location) inline
References IG.Forms.BrowserSimpleWindow.browserForm, and IG.Forms.BrowserSimpleControl.OpenLocation().
Dispose()
override void IG.Forms.BrowserSimpleWindow.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.BrowserSimpleWindow.components.
InitializeComponent()
void IG.Forms.BrowserSimpleWindow.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.BrowserSimpleWindow.browserForm, IG.Forms.BrowserSimpleWindow.BrowserSimpleWindow_VisibleChanged(), and IG.Forms.BrowserSimpleControl.HomeUrl.
Referenced by IG.Forms.BrowserSimpleWindow.BrowserSimpleWindow().
Member Data Documentation
components
System.ComponentModel.IContainer IG.Forms.BrowserSimpleWindow.components = null private
Required designer variable.
Referenced by IG.Forms.BrowserSimpleWindow.Dispose().
browserForm
BrowserSimpleControl IG.Forms.BrowserSimpleWindow.browserForm
Referenced by IG.Forms.BrowserSimpleWindow.BrowserSimpleWindow(), IG.Forms.BrowserSimpleWindow.BrowserSimpleWindow_VisibleChanged(), IG.Forms.BrowserSimpleWindow.InitializeComponent(), and IG.Forms.BrowserSimpleWindow.OpenLocation().
The documentation for this class was generated from the following files:
iglib/igforms/00_ToBeScrapped/BrowserSimpleWindow.cs
iglib/igforms/00_ToBeScrapped/BrowserSimpleWindow.Designer.cs