Doc: IGLib EXTENDED: NUnit.Engine.Internal.PathUtils Class Reference
NUnit.Engine.Internal.PathUtils Class Reference
Static methods for manipulating project paths, including both directories and files. Some synonyms for System.Path methods are included as well.
Static Public Member Functions
static bool IsAssemblyFileType (string path)
Returns a boolean indicating whether the specified path is that of an assembly - that is a dll or exe file.
static string RelativePath (string from, string to)
Returns the relative path from a base directory to another directory or file.
static string Canonicalize (string path)
Return the canonical form of a path.
static bool SamePathOrUnder (string path1, string path2)
True if the two paths are the same or if the second is directly or indirectly under the first. Note that paths using different network shares or drive letters are considered unrelated, even if they end up referencing the same subtrees in the file system.
static string Combine (string path1, params string[] morePaths)
Combines all the arguments into a single path
Static Public Attributes
const uint FILE_ATTRIBUTE_DIRECTORY = 0x00000010
const uint FILE_ATTRIBUTE_NORMAL = 0x00000080
const int MAX_PATH = 256
Static Protected Attributes
static char DirectorySeparatorChar = Path.DirectorySeparatorChar
static char AltDirectorySeparatorChar = Path.AltDirectorySeparatorChar
Static Private Member Functions
static bool IsWindows ()
static string[] SplitPath (string path)
static bool PathsEqual (string path1, string path2)
Detailed Description
Static methods for manipulating project paths, including both directories and files. Some synonyms for System.Path methods are included as well.
Member Function Documentation
IsAssemblyFileType()
static bool NUnit.Engine.Internal.PathUtils.IsAssemblyFileType (string path) inline static
Returns a boolean indicating whether the specified path is that of an assembly - that is a dll or exe file.
Parameters
path Path to a file.
Returns
True if the file extension is dll or exe, otherwise false.
Referenced by NUnit.Engine.Services.DefaultTestRunnerFactory.MakeTestRunner(), and NUnit.Engine.Services.RuntimeFrameworkService.SelectRuntimeFramework().
RelativePath()
static string NUnit.Engine.Internal.PathUtils.RelativePath (string from, string to) inline static
Returns the relative path from a base directory to another directory or file.
References NUnit.Engine.Internal.PathUtils.DirectorySeparatorChar, NUnit.Engine.Internal.PathUtils.PathsEqual(), and NUnit.Engine.Internal.PathUtils.SplitPath().
Referenced by NUnit.Engine.Services.DomainManager.GetPrivateBinPath(), NUnit.Engine.Internal.Tests.PathUtilTests_Windows.RelativePath(), and NUnit.Engine.Internal.Tests.PathUtilTests_Unix.RelativePath().
Canonicalize()
static string NUnit.Engine.Internal.PathUtils.Canonicalize (string path) inline static
Return the canonical form of a path.
References NUnit.Engine.Internal.PathUtils.AltDirectorySeparatorChar, and NUnit.Engine.Internal.PathUtils.DirectorySeparatorChar.
Referenced by NUnit.Engine.Internal.Tests.PathUtilTests_Windows.Canonicalize(), NUnit.Engine.Internal.Tests.PathUtilTests_Unix.Canonicalize(), and NUnit.Engine.Internal.PathUtils.SamePathOrUnder().
SamePathOrUnder()
static bool NUnit.Engine.Internal.PathUtils.SamePathOrUnder (string path1, string path2) inline static
True if the two paths are the same or if the second is directly or indirectly under the first. Note that paths using different network shares or drive letters are considered unrelated, even if they end up referencing the same subtrees in the file system.
References NUnit.Engine.Internal.PathUtils.Canonicalize(), NUnit.Engine.Internal.PathUtils.DirectorySeparatorChar, and NUnit.Engine.Internal.PathUtils.IsWindows().
Referenced by NUnit.Engine.Services.DomainManager.GetCommonAppBase().
Combine()
static string NUnit.Engine.Internal.PathUtils.Combine (string path1, params string[] morePaths) inline static
Combines all the arguments into a single path
IsWindows()
static bool NUnit.Engine.Internal.PathUtils.IsWindows () inline static private
References NUnit.Engine.Internal.PathUtils.DirectorySeparatorChar.
Referenced by NUnit.Engine.Internal.PathUtils.PathsEqual(), and NUnit.Engine.Internal.PathUtils.SamePathOrUnder().
SplitPath()
static string [] NUnit.Engine.Internal.PathUtils.SplitPath (string path) inline static private
References NUnit.Engine.Internal.PathUtils.AltDirectorySeparatorChar, and NUnit.Engine.Internal.PathUtils.DirectorySeparatorChar.
Referenced by NUnit.Engine.Internal.PathUtils.RelativePath().
PathsEqual()
static bool NUnit.Engine.Internal.PathUtils.PathsEqual (string path1, string path2) inline static private
References NUnit.Engine.Internal.PathUtils.IsWindows().
Referenced by NUnit.Engine.Internal.PathUtils.RelativePath().
Member Data Documentation
FILE_ATTRIBUTE_DIRECTORY
const uint NUnit.Engine.Internal.PathUtils.FILE_ATTRIBUTE_DIRECTORY = 0x00000010 static
FILE_ATTRIBUTE_NORMAL
const uint NUnit.Engine.Internal.PathUtils.FILE_ATTRIBUTE_NORMAL = 0x00000080 static
MAX_PATH
const int NUnit.Engine.Internal.PathUtils.MAX_PATH = 256 static
DirectorySeparatorChar
char NUnit.Engine.Internal.PathUtils.DirectorySeparatorChar = Path.DirectorySeparatorChar static protected
Referenced by NUnit.Engine.Internal.PathUtils.Canonicalize(), NUnit.Engine.Internal.Tests.PathUtilTests.CheckDefaults(), NUnit.Engine.Internal.PathUtils.IsWindows(), NUnit.Engine.Internal.PathUtils.RelativePath(), NUnit.Engine.Internal.Tests.PathUtilTests_Windows.RestoreDefaultSeparators(), NUnit.Engine.Internal.Tests.PathUtilTests_Unix.RestoreDefaultSeparators(), NUnit.Engine.Internal.PathUtils.SamePathOrUnder(), NUnit.Engine.Internal.Tests.PathUtilTests_Windows.SetUpUnixSeparators(), NUnit.Engine.Internal.Tests.PathUtilTests_Unix.SetUpUnixSeparators(), and NUnit.Engine.Internal.PathUtils.SplitPath().
AltDirectorySeparatorChar
char NUnit.Engine.Internal.PathUtils.AltDirectorySeparatorChar = Path.AltDirectorySeparatorChar static protected
Referenced by NUnit.Engine.Internal.PathUtils.Canonicalize(), NUnit.Engine.Internal.Tests.PathUtilTests.CheckDefaults(), NUnit.Engine.Internal.Tests.PathUtilTests_Windows.RestoreDefaultSeparators(), NUnit.Engine.Internal.Tests.PathUtilTests_Unix.RestoreDefaultSeparators(), NUnit.Engine.Internal.Tests.PathUtilTests_Windows.SetUpUnixSeparators(), NUnit.Engine.Internal.Tests.PathUtilTests_Unix.SetUpUnixSeparators(), and NUnit.Engine.Internal.PathUtils.SplitPath().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Internal/PathUtils.cs