Doc: IGLib EXTENDED: CShell.Framework.Results.ShowToolResult< TTool > Class Template Reference
CShell.Framework.Results.ShowToolResult< TTool > Class Template Reference
Public Member Functions
ShowToolResult ()
ShowToolResult (TTool tool)
override void Execute (ActionExecutionContext context)
Private Attributes
readonly Func< TTool > _toolLocator = () => IoC.Get<TTool>()
IShell _shell
Additional Inherited Members
Protected Member Functions inherited from CShell.Framework.Results.OpenResultBase< TTool >
virtual void OnCompleted (Exception exception)
Protected Attributes inherited from CShell.Framework.Results.OpenResultBase< TTool >
Action< TTarget > _setData
Action< TTarget > _onConfigure
Action< TTarget > _onShutDown
Properties inherited from CShell.Framework.Results.OpenResultBase< TTool >
Action< TTarget > IOpenResult< TTarget >. OnConfigure [get, set]
Action< TTarget > IOpenResult< TTarget >. OnShutDown [get, set]
Events inherited from CShell.Framework.Results.OpenResultBase< TTool >
EventHandler< ResultCompletionEventArgs > Completed
Constructor & Destructor Documentation
ShowToolResult() [1/2]
CShell.Framework.Results.ShowToolResult< TTool >.ShowToolResult () inline
ShowToolResult() [2/2]
CShell.Framework.Results.ShowToolResult< TTool >.ShowToolResult (TTool tool) inline
References CShell.Framework.Results.ShowToolResult< TTool >._toolLocator.
Member Function Documentation
Execute()
override void CShell.Framework.Results.ShowToolResult< TTool >.Execute (ActionExecutionContext context) inline virtual
Implements CShell.Framework.Results.OpenResultBase< TTool >.
References CShell.Framework.Results.OpenResultBase< TTool >._onConfigure, CShell.Framework.Results.OpenResultBase< TTool >._onShutDown, CShell.Framework.Results.OpenResultBase< TTool >._setData, CShell.Framework.Results.ShowToolResult< TTool >._shell, CShell.Framework.Results.ShowToolResult< TTool >._toolLocator, CShell.Framework.Results.OpenResultBase< TTool >.OnCompleted(), and CShell.Framework.Services.IShell.ShowTool().
Member Data Documentation
_toolLocator
readonly Func<TTool> CShell.Framework.Results.ShowToolResult< TTool >._toolLocator = () => IoC.Get<TTool>() private
Referenced by CShell.Framework.Results.ShowToolResult< TTool >.Execute(), and CShell.Framework.Results.ShowToolResult< TTool >.ShowToolResult().
_shell
IShell CShell.Framework.Results.ShowToolResult< TTool >._shell private
Referenced by CShell.Framework.Results.ShowToolResult< TTool >.Execute().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore/Framework/Results/ShowToolResult.cs