Doc: IGLib EXTENDED: IG.Crypt.SymStringEncrypt Class Reference
IG.Crypt.SymStringEncrypt Class Reference
Static Public Member Functions
static string Encrypt (string originalStr)
static string Decrypt (string encryptedStr)
static void Test ()
Properties
static byte[] Key [get, set]
static byte[] IV [get, set]
Private Member Functions
SymStringEncrypt ()
Static Private Member Functions
static void RdGenerateSecretKey (RijndaelManaged rdProvider)
static void RdGenerateSecretInitVector (RijndaelManaged rdProvider)
Static Private Attributes
static byte[] savedKey = null
static byte[] savedIV = null
Constructor & Destructor Documentation
SymStringEncrypt()
IG.Crypt.SymStringEncrypt.SymStringEncrypt () inline private
Member Function Documentation
RdGenerateSecretKey()
static void IG.Crypt.SymStringEncrypt.RdGenerateSecretKey (RijndaelManaged rdProvider) inline static private
References IG.Crypt.SymStringEncrypt.savedKey.
Referenced by IG.Crypt.SymStringEncrypt.Encrypt().
RdGenerateSecretInitVector()
static void IG.Crypt.SymStringEncrypt.RdGenerateSecretInitVector (RijndaelManaged rdProvider) inline static private
References IG.Crypt.SymStringEncrypt.savedIV.
Referenced by IG.Crypt.SymStringEncrypt.Encrypt().
Encrypt()
static string IG.Crypt.SymStringEncrypt.Encrypt (string originalStr) inline static
References IG.Crypt.SymStringEncrypt.RdGenerateSecretInitVector(), IG.Crypt.SymStringEncrypt.RdGenerateSecretKey(), IG.Crypt.SymStringEncrypt.savedIV, and IG.Crypt.SymStringEncrypt.savedKey.
Referenced by IG.Crypt.SymStringEncrypt.Test().
Decrypt()
static string IG.Crypt.SymStringEncrypt.Decrypt (string encryptedStr) inline static
References IG.Crypt.SymStringEncrypt.savedIV, and IG.Crypt.SymStringEncrypt.savedKey.
Referenced by IG.Crypt.SymStringEncrypt.Test().
Test()
static void IG.Crypt.SymStringEncrypt.Test () inline static
References IG.Crypt.SymStringEncrypt.Decrypt(), IG.Crypt.SymStringEncrypt.Encrypt(), IG.Crypt.SymStringEncrypt.IV, and IG.Crypt.SymStringEncrypt.Key.
Member Data Documentation
savedKey
byte [] IG.Crypt.SymStringEncrypt.savedKey = null static private
Referenced by IG.Crypt.SymStringEncrypt.Decrypt(), IG.Crypt.SymStringEncrypt.Encrypt(), and IG.Crypt.SymStringEncrypt.RdGenerateSecretKey().
savedIV
byte [] IG.Crypt.SymStringEncrypt.savedIV = null static private
Referenced by IG.Crypt.SymStringEncrypt.Decrypt(), IG.Crypt.SymStringEncrypt.Encrypt(), and IG.Crypt.SymStringEncrypt.RdGenerateSecretInitVector().
Property Documentation
Key
byte [] IG.Crypt.SymStringEncrypt.Key static get set
Referenced by IG.Crypt.SymStringEncrypt.Test().
IV
byte [] IG.Crypt.SymStringEncrypt.IV static get set
Referenced by IG.Crypt.SymStringEncrypt.Test().
The documentation for this class was generated from the following file:
igtest/iglib_sandbox/encryption/EncryptionLib.cs