Doc: IGLib EXTENDED: CShell.Framework.Services.ResourceManager Class Reference
CShell.Framework.Services.ResourceManager Class Reference
Public Member Functions
Stream GetStream (string relativeUri, string assemblyName)
BitmapImage GetBitmap (string relativeUri, string assemblyName)
BitmapImage GetBitmap (string relativeUri)
Member Function Documentation
GetStream()
Stream CShell.Framework.Services.ResourceManager.GetStream (string relativeUri, string assemblyName) inline
Implements CShell.Framework.Services.IResourceManager.
Referenced by CShell.Framework.Services.ResourceManager.GetBitmap().
GetBitmap() [1/2]
BitmapImage CShell.Framework.Services.ResourceManager.GetBitmap (string relativeUri, string assemblyName) inline
Implements CShell.Framework.Services.IResourceManager.
References CShell.Framework.Services.ResourceManager.GetStream().
Referenced by CShell.Framework.Services.ResourceManager.GetBitmap().
GetBitmap() [2/2]
BitmapImage CShell.Framework.Services.ResourceManager.GetBitmap (string relativeUri) inline
Implements CShell.Framework.Services.IResourceManager.
References CShell.Framework.Services.ResourceManager.GetBitmap(), and CShell.Framework.Services.ExtensionMethods.GetExecutingAssemblyName().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore/Framework/Services/ResourceManager.cs