Doc: IGLib EXTENDED: AForge.Math.Tests.Vector3Test Class Reference
AForge.Math.Tests.Vector3Test Class Reference
Public Member Functions
void ConstructorTest ()
void MinMaxTest (float x, float y, float z, float expectedMin, float expectedMax, int expectedMinIndex, int expectedMaxIndex)
void NormTest (float x, float y, float z, float expectedNorm)
void EqualityTest (float x1, float y1, float z1, float x2, float y2, float z2, bool expected)
void AdditionTest (float x1, float y1, float z1, float x2, float y2, float z2, float expectedX, float expectedY, float expectedZ)
void AdditionWithConstTest (float x, float y, float z, float value, float expectedX, float expectedY, float expectedZ)
void SubtractionTest (float x1, float y1, float z1, float x2, float y2, float z2, float expectedX, float expectedY, float expectedZ)
void SubtractionWithConstTest (float x, float y, float z, float value, float expectedX, float expectedY, float expectedZ)
void MultiplicationTest (float x1, float y1, float z1, float x2, float y2, float z2, float expectedX, float expectedY, float expectedZ)
void MultiplicationWithConstTest (float x, float y, float z, float value, float expectedX, float expectedY, float expectedZ)
void DivisionTest (float x1, float y1, float z1, float x2, float y2, float z2, float expectedX, float expectedY, float expectedZ)
void DivisionWithConstTest (float x, float y, float z, float value, float expectedX, float expectedY, float expectedZ)
void NormalizeTest (float x, float y, float z, float expectedX, float expectedY, float expectedZ)
void InverseTest (float x, float y, float z, float expectedX, float expectedY, float expectedZ)
void DotTest (float x1, float y1, float z1, float x2, float y2, float z2, float expectedResult)
void CrossTest (float x1, float y1, float z1, float x2, float y2, float z2, float expectedX, float expectedY, float expectedZ)
Member Function Documentation
ConstructorTest()
void AForge.Math.Tests.Vector3Test.ConstructorTest () inline
References AForge.Math.Vector3.X, AForge.Math.Vector3.Y, and AForge.Math.Vector3.Z.
MinMaxTest()
void AForge.Math.Tests.Vector3Test.MinMaxTest (float x, float y, float z, float expectedMin, float expectedMax, int expectedMinIndex, int expectedMaxIndex) inline
References AForge.Math.Vector3.Max, AForge.Math.Vector3.MaxIndex, AForge.Math.Vector3.Min, and AForge.Math.Vector3.MinIndex.
NormTest()
void AForge.Math.Tests.Vector3Test.NormTest (float x, float y, float z, float expectedNorm) inline
References AForge.Math.Vector3.Norm, and AForge.Math.Vector3.Square.
EqualityTest()
void AForge.Math.Tests.Vector3Test.EqualityTest (float x1, float y1, float z1, float x2, float y2, float z2, bool expected) inline
AdditionTest()
void AForge.Math.Tests.Vector3Test.AdditionTest (float x1, float y1, float z1, float x2, float y2, float z2, float expectedX, float expectedY, float expectedZ) inline
References AForge.Math.Vector3.Add().
AdditionWithConstTest()
void AForge.Math.Tests.Vector3Test.AdditionWithConstTest (float x, float y, float z, float value, float expectedX, float expectedY, float expectedZ) inline
References AForge.Math.Vector3.Add().
SubtractionTest()
void AForge.Math.Tests.Vector3Test.SubtractionTest (float x1, float y1, float z1, float x2, float y2, float z2, float expectedX, float expectedY, float expectedZ) inline
References AForge.Math.Vector3.Subtract().
SubtractionWithConstTest()
void AForge.Math.Tests.Vector3Test.SubtractionWithConstTest (float x, float y, float z, float value, float expectedX, float expectedY, float expectedZ) inline
References AForge.Math.Vector3.Subtract().
MultiplicationTest()
void AForge.Math.Tests.Vector3Test.MultiplicationTest (float x1, float y1, float z1, float x2, float y2, float z2, float expectedX, float expectedY, float expectedZ) inline
References AForge.Math.Vector3.Multiply().
MultiplicationWithConstTest()
void AForge.Math.Tests.Vector3Test.MultiplicationWithConstTest (float x, float y, float z, float value, float expectedX, float expectedY, float expectedZ) inline
References AForge.Math.Vector3.Multiply().
DivisionTest()
void AForge.Math.Tests.Vector3Test.DivisionTest (float x1, float y1, float z1, float x2, float y2, float z2, float expectedX, float expectedY, float expectedZ) inline
References AForge.Math.Vector3.Divide().
DivisionWithConstTest()
void AForge.Math.Tests.Vector3Test.DivisionWithConstTest (float x, float y, float z, float value, float expectedX, float expectedY, float expectedZ) inline
References AForge.Math.Vector3.Divide().
NormalizeTest()
void AForge.Math.Tests.Vector3Test.NormalizeTest (float x, float y, float z, float expectedX, float expectedY, float expectedZ) inline
References AForge.Math.Vector3.Norm, and AForge.Math.Vector3.Normalize().
InverseTest()
void AForge.Math.Tests.Vector3Test.InverseTest (float x, float y, float z, float expectedX, float expectedY, float expectedZ) inline
References AForge.Math.Vector3.Inverse().
DotTest()
void AForge.Math.Tests.Vector3Test.DotTest (float x1, float y1, float z1, float x2, float y2, float z2, float expectedResult) inline
References AForge.Math.Vector3.Dot().
CrossTest()
void AForge.Math.Tests.Vector3Test.CrossTest (float x1, float y1, float z1, float x2, float y2, float z2, float expectedX, float expectedY, float expectedZ) inline
References AForge.Math.Vector3.Cross().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Unit Tests/AForge.Math.Tests/Vector3Test.cs