Doc: IGLib EXTENDED: IG.MPetekLib.Application.Scripts.LinearOscillator._12MultipleResCurvesPlot Class Reference
IG.MPetekLib.Application.Scripts.LinearOscillator._12MultipleResCurvesPlot Class Reference
Narišem nekaj resonančnih krivulj linearnega oscilatorja pri različnih parametrih w0 in b.
Static Public Member Functions
static void Run (string[] arguments)
Performs a driven oscillations test and plots the results.
Detailed Description
Narišem nekaj resonančnih krivulj linearnega oscilatorja pri različnih parametrih w0 in b.
Member Function Documentation
Run()
static void IG.MPetekLib.Application.Scripts.LinearOscillator._12MultipleResCurvesPlot.Run (string[] arguments) inline static
Performs a driven oscillations test and plots the results.
Plotting is performed in the main thread.
References IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.CalcAnalyticalAmplitudeVsDrivingFrequnecy(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.CalcAnalyticalResonantAmplitudeVsResonantDrivingFrequency(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.DampingCoefficient, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.EndDampingCoefficient, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.EndingDrivingAngularFrequency, IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase.NewCurveFromPlottableData(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.NSamplesForResonanceCurve, IG.MPetekLib.Algorithms.Plotting.PlotHQ.Plotter, IG.MPetekLib.Algorithms.Plotting.PlotHQ.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.PlottableODEModelBase.Solver, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.StartDampingCoefficient, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.StartingDrivingAngularFrequency, IG.MPetekLib.Algorithms.Solvers.InitialProblemODE_RK4.InitialProblemSolverBase.StepSize, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.StepSizeDampingCoefficient, and IG.MPetekLib.Algorithms.Plotting.PlotHQ.Window.
Referenced by IG.Script.AppMarkoPetek.App12MultipleResCurvesPlot().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/Guest_Marko_Petek_Lib/application/scripts/LinearOscillator/12MultipleResCurvesPlot.cs