Doc: IGLib EXTENDED: AForge.Imaging.Filters.ConnectedComponentsLabeling Class Reference
AForge.Imaging.Filters.ConnectedComponentsLabeling Class Reference
Connected components labeling.
Public Member Functions
ConnectedComponentsLabeling ()
Initializes a new instance of the ConnectedComponentsLabeling class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage sourceData, UnmanagedImage destinationData)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
BlobCounterBase BlobCounter [get, set]
Blob counter used to locate separate blobs.
static Color[] ColorTable [get, set]
Colors used to color the binary image.
bool FilterBlobs [get, set]
Specifies if blobs should be filtered.
bool CoupledSizeFiltering [get, set]
Specifies if size filetering should be coupled or not.
int MinWidth [get, set]
Minimum allowed width of blob.
int MinHeight [get, set]
Minimum allowed height of blob.
int MaxWidth [get, set]
Maximum allowed width of blob.
int MaxHeight [get, set]
Maximum allowed height of blob.
int ObjectCount [get]
Objects count.
Properties inherited from AForge.Imaging.Filters.BaseFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
BlobCounterBase blobCounter = new BlobCounter()
Static Private Attributes
static Color[] colorTable
Detailed Description
Connected components labeling.
The filter performs labeling of objects in the source image. It colors each separate object using different color. The image processing filter treats all none black pixels as objects' pixels and all black pixel as background.
The filter accepts 8 bpp grayscale images and 24/32 bpp color images and produces 24 bpp RGB image.
Sample usage:
// create filter
ConnectedComponentsLabeling filter = new ConnectedComponentsLabeling();
// apply the filter
Bitmap newImage = filter.Apply(image);
// check objects count
int objectCount = filter.ObjectCount;
Initial image:
Result image:
Constructor & Destructor Documentation
ConnectedComponentsLabeling()
AForge.Imaging.Filters.ConnectedComponentsLabeling.ConnectedComponentsLabeling () inline
Initializes a new instance of the ConnectedComponentsLabeling class.
References AForge.Imaging.Filters.ConnectedComponentsLabeling.formatTranslations.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.ConnectedComponentsLabeling.ProcessFilter (UnmanagedImage sourceData, UnmanagedImage destinationData) inline protected virtual
Process the filter on the specified image.
Parameters
sourceData Source image data.
destinationData Destination image data.
Implements AForge.Imaging.Filters.BaseFilter.
References AForge.Imaging.RGB.B, AForge.Imaging.Filters.ConnectedComponentsLabeling.blobCounter, AForge.Imaging.Filters.ConnectedComponentsLabeling.colorTable, AForge.Imaging.RGB.G, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.BlobCounterBase.ObjectLabels, AForge.Imaging.BlobCounterBase.ProcessImage(), AForge.Imaging.RGB.R, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
Member Data Documentation
colorTable
Color [] AForge.Imaging.Filters.ConnectedComponentsLabeling.colorTable static private
Initial value:
= new Color[]
        {
            Color.Red,      Color.Green,    Color.Blue,         Color.Yellow,
            Color.Violet,   Color.Brown,    Color.Olive,        Color.Cyan,
            Color.Magenta,  Color.Gold,     Color.Indigo,       Color.Ivory,
            Color.HotPink,  Color.DarkRed,  Color.DarkGreen,    Color.DarkBlue,
            Color.DarkSeaGreen, Color.Gray, Color.DarkKhaki,    Color.DarkGray,
            Color.LimeGreen, Color.Tomato,  Color.SteelBlue,    Color.SkyBlue,
            Color.Silver,   Color.Salmon,   Color.SaddleBrown,  Color.RosyBrown,
            Color.PowderBlue, Color.Plum,   Color.PapayaWhip,   Color.Orange
        }
Referenced by AForge.Imaging.Filters.ConnectedComponentsLabeling.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.ConnectedComponentsLabeling.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.ConnectedComponentsLabeling.ConnectedComponentsLabeling().
blobCounter
BlobCounterBase AForge.Imaging.Filters.ConnectedComponentsLabeling.blobCounter = new BlobCounter() private
Referenced by AForge.Imaging.Filters.ConnectedComponentsLabeling.ProcessFilter().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.ConnectedComponentsLabeling.FormatTranslations get
Format translations dictionary.
BlobCounter
BlobCounterBase AForge.Imaging.Filters.ConnectedComponentsLabeling.BlobCounter get set
Blob counter used to locate separate blobs.
The property allows to set blob counter to use for blobs' localization.
Default value is set to BlobCounter.
ColorTable
Color [] AForge.Imaging.Filters.ConnectedComponentsLabeling.ColorTable static get set
Colors used to color the binary image.
FilterBlobs
bool AForge.Imaging.Filters.ConnectedComponentsLabeling.FilterBlobs get set
Specifies if blobs should be filtered.
See documentation for BlobCounterBase.FilterBlobs property of BlobCounterBase class for more information.
CoupledSizeFiltering
bool AForge.Imaging.Filters.ConnectedComponentsLabeling.CoupledSizeFiltering get set
Specifies if size filetering should be coupled or not.
See documentation for BlobCounterBase.CoupledSizeFiltering property of BlobCounterBase class for more information.
MinWidth
int AForge.Imaging.Filters.ConnectedComponentsLabeling.MinWidth get set
Minimum allowed width of blob.
MinHeight
int AForge.Imaging.Filters.ConnectedComponentsLabeling.MinHeight get set
Minimum allowed height of blob.
MaxWidth
int AForge.Imaging.Filters.ConnectedComponentsLabeling.MaxWidth get set
Maximum allowed width of blob.
MaxHeight
int AForge.Imaging.Filters.ConnectedComponentsLabeling.MaxHeight get set
Maximum allowed height of blob.
ObjectCount
int AForge.Imaging.Filters.ConnectedComponentsLabeling.ObjectCount get
Objects count.
The amount of objects found in the last processed image.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Other/ConnectedComponentsLabeling.cs