Doc: IGLib EXTENDED: NUnit.Framework.Internal.TypeHelper Class Reference
NUnit.Framework.Internal.TypeHelper Class Reference
TypeHelper provides static methods that operate on Types.
Classes
class NonmatchingTypeClass
Static Public Member Functions
static string GetDisplayName (Type type)
Gets the display name for a Type as used by NUnit.
static string GetDisplayName (Type type, object[] arglist)
Gets the display name for a Type as used by NUnit.
static Type BestCommonType (Type type1, Type type2)
Returns the best fit for a common type to be used in matching actual arguments to a methods Type parameters.
static bool IsNumeric (Type type)
Determines whether the specified type is numeric.
static void ConvertArgumentList (object[] arglist, IParameterInfo[] parameters)
Convert an argument list to the required parameter types. Currently, only widening numeric conversions are performed.
static bool CanDeduceTypeArgsFromArgs (Type type, object[] arglist, ref Type[] typeArgsOut)
Determines whether this instance can deduce type args for a generic type from the supplied arguments.
static Array GetEnumValues (Type enumType)
Gets the _values for an enumeration, using Enum.GetTypes where available, otherwise through reflection.
static string[] GetEnumNames (Type enumType)
Gets the ids of the _values for an enumeration, using Enum.GetNames where available, otherwise through reflection.
Static Public Attributes
static readonly Type NonmatchingType = typeof(NonmatchingTypeClass)
A special value, which is used to indicate that BestCommonType() method was unable to find a common type for the specified arguments.
Static Private Attributes
const int STRING_MAX = 40
const int STRING_LIMIT = STRING_MAX - 3
const string THREE_DOTS = "..."
Detailed Description
TypeHelper provides static methods that operate on Types.
Member Function Documentation
GetDisplayName() [1/2]
static string NUnit.Framework.Internal.TypeHelper.GetDisplayName (Type type) inline static
Gets the display name for a Type as used by NUnit.
Parameters
type The Type for which a display name is needed.
Returns
The display name for the Type
Referenced by NUnit.Framework.Internal.TypeHelper.GetDisplayName(), NUnit.Framework.Internal.TypeWrapper.GetDisplayName(), and NUnit.Framework.Internal.TypeHelperTests.GetDisplayNameTests().
GetDisplayName() [2/2]
static string NUnit.Framework.Internal.TypeHelper.GetDisplayName (Type type, object[] arglist) inline static
Gets the display name for a Type as used by NUnit.
Parameters
type The Type for which a display name is needed.
arglist The arglist provided.
Returns
The display name for the Type
References NUnit.Framework.Internal.TypeHelper.GetDisplayName(), NUnit.Framework.Internal.TypeHelper.STRING_LIMIT, NUnit.Framework.Internal.TypeHelper.STRING_MAX, and NUnit.Framework.Internal.TypeHelper.THREE_DOTS.
BestCommonType()
static Type NUnit.Framework.Internal.TypeHelper.BestCommonType (Type type1, Type type2) inline static
Returns the best fit for a common type to be used in matching actual arguments to a methods Type parameters.
Parameters
type1 The first type.
type2 The second type.
Returns
Either type1 or type2, depending on which is more general.
References NUnit.Framework.Internal.TypeHelper.IsNumeric(), and NUnit.Framework.Internal.TypeHelper.NonmatchingType.
Referenced by NUnit.Framework.Internal.GenericMethodHelper.ApplyArgType(), and NUnit.Framework.Internal.TypeHelperTests.BestCommonTypeTest().
IsNumeric()
static bool NUnit.Framework.Internal.TypeHelper.IsNumeric (Type type) inline static
Determines whether the specified type is numeric.
Parameters
type The type to be examined.
Returns
true if the specified type is numeric; otherwise, false.
Referenced by NUnit.Framework.Internal.TypeHelper.BestCommonType(), and NUnit.Framework.Internal.TypeHelper.ConvertArgumentList().
ConvertArgumentList()
static void NUnit.Framework.Internal.TypeHelper.ConvertArgumentList (object[] arglist, IParameterInfo[] parameters) inline static
Convert an argument list to the required parameter types. Currently, only widening numeric conversions are performed.
Parameters
arglist An array of args to be converted
parameters A ParameterInfo[] whose types will be used as targets
References NUnit.Framework.Internal.TypeHelper.IsNumeric(), and NUnit.Framework.Interfaces.IParameterInfo.ParameterType.
Referenced by NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.CheckTestMethodSignature().
CanDeduceTypeArgsFromArgs()
static bool NUnit.Framework.Internal.TypeHelper.CanDeduceTypeArgsFromArgs (Type type, object[] arglist, ref Type[] typeArgsOut) inline static
Determines whether this instance can deduce type args for a generic type from the supplied arguments.
Parameters
type The type to be examined.
arglist The arglist.
typeArgsOut The type args to be used.
Returns
true if this the provided args give sufficient information to determine the type args to be used; otherwise, false.
Referenced by NUnit.Framework.Internal.Builders.NUnitTestFixtureBuilder.BuildFrom().
GetEnumValues()
static Array NUnit.Framework.Internal.TypeHelper.GetEnumValues (Type enumType) inline static
Gets the _values for an enumeration, using Enum.GetTypes where available, otherwise through reflection.
Parameters
enumType
Returns
Referenced by NUnit.Framework.ValuesAttribute.GetData(), NUnit.Framework.Internal.Builders.DatapointProvider.GetDataFor(), and NUnit.Framework.Internal.Randomizer.NextEnum().
GetEnumNames()
static string [] NUnit.Framework.Internal.TypeHelper.GetEnumNames (Type enumType) inline static
Gets the ids of the _values for an enumeration, using Enum.GetNames where available, otherwise through reflection.
Parameters
enumType
Returns
Referenced by NUnit.Framework.Internal.RuntimeFramework.IsRuntimeTypeName().
Member Data Documentation
STRING_MAX
const int NUnit.Framework.Internal.TypeHelper.STRING_MAX = 40 static private
Referenced by NUnit.Framework.Internal.TypeHelper.GetDisplayName().
STRING_LIMIT
const int NUnit.Framework.Internal.TypeHelper.STRING_LIMIT = STRING_MAX - 3 static private
Referenced by NUnit.Framework.Internal.TypeHelper.GetDisplayName().
THREE_DOTS
const string NUnit.Framework.Internal.TypeHelper.THREE_DOTS = "..." static private
Referenced by NUnit.Framework.Internal.TypeHelper.GetDisplayName().
NonmatchingType
readonly Type NUnit.Framework.Internal.TypeHelper.NonmatchingType = typeof(NonmatchingTypeClass) static
A special value, which is used to indicate that BestCommonType() method was unable to find a common type for the specified arguments.
Referenced by NUnit.Framework.Internal.TypeHelper.BestCommonType(), and NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.CheckTestMethodSignature().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/TypeHelper.cs