Doc: IGLib EXTENDED: NUnit.Framework.Attributes.PairwiseTest Class Reference
NUnit.Framework.Attributes.PairwiseTest Class Reference
Classes
class LiveTest
class PairCounter
Public Member Functions
void Test (int[] dimensions, int bestSoFar, int targetCases)
Member Function Documentation
Test()
void NUnit.Framework.Attributes.PairwiseTest.Test (int[] dimensions, int bestSoFar, int targetCases) inline
References NUnit.Framework.Is.AtMost(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ICombiningStrategy.GetTestCases(), and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/PairwiseTests.cs