Doc: IGLib EXTENDED: NUnit.Framework.Attributes.TestFixtureAttributeTests Class Reference
NUnit.Framework.Attributes.TestFixtureAttributeTests Class Reference
Public Member Functions
void ConstructWithoutArguments ()
void ConstructWithFixtureArgs ()
void ConstructWithJustTypeArgs ()
void ConstructWithNoArgumentsAndSetTypeArgs ()
void ConstructWithFixtureArgsAndSetTypeArgs ()
void ConstructWithCombinedArgs ()
Static Private Attributes
static object[] fixtureArgs = new object[] { 10, 20, "Charlie" }
static Type[] typeArgs = new Type[] { typeof(int), typeof(string) }
static object[] combinedArgs = new object[] { typeof(int), typeof(string), 10, 20, "Charlie" }
Member Function Documentation
ConstructWithoutArguments()
void NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithoutArguments () inline
References NUnit.Framework.TestFixtureAttribute.Arguments, NUnit.Framework.Assert.That(), and NUnit.Framework.TestFixtureAttribute.TypeArgs.
ConstructWithFixtureArgs()
void NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithFixtureArgs () inline
References NUnit.Framework.TestFixtureAttribute.Arguments, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TestFixtureAttributeTests.fixtureArgs, NUnit.Framework.Assert.That(), and NUnit.Framework.TestFixtureAttribute.TypeArgs.
ConstructWithJustTypeArgs()
void NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithJustTypeArgs () inline
References NUnit.Framework.TestFixtureAttribute.Arguments, NUnit.Framework.Assert.That(), NUnit.Framework.Attributes.TestFixtureAttributeTests.typeArgs, and NUnit.Framework.TestFixtureAttribute.TypeArgs.
ConstructWithNoArgumentsAndSetTypeArgs()
void NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithNoArgumentsAndSetTypeArgs () inline
References NUnit.Framework.TestFixtureAttribute.Arguments, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), NUnit.Framework.Attributes.TestFixtureAttributeTests.typeArgs, and NUnit.Framework.TestFixtureAttribute.TypeArgs.
ConstructWithFixtureArgsAndSetTypeArgs()
void NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithFixtureArgsAndSetTypeArgs () inline
References NUnit.Framework.TestFixtureAttribute.Arguments, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TestFixtureAttributeTests.fixtureArgs, NUnit.Framework.Assert.That(), NUnit.Framework.Attributes.TestFixtureAttributeTests.typeArgs, and NUnit.Framework.TestFixtureAttribute.TypeArgs.
ConstructWithCombinedArgs()
void NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithCombinedArgs () inline
References NUnit.Framework.TestFixtureAttribute.Arguments, NUnit.Framework.Attributes.TestFixtureAttributeTests.combinedArgs, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.TestFixtureAttribute.TypeArgs.
Member Data Documentation
fixtureArgs
object [] NUnit.Framework.Attributes.TestFixtureAttributeTests.fixtureArgs = new object[] { 10, 20, "Charlie" } static private
Referenced by NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithFixtureArgs(), and NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithFixtureArgsAndSetTypeArgs().
typeArgs
Type [] NUnit.Framework.Attributes.TestFixtureAttributeTests.typeArgs = new Type[] { typeof(int), typeof(string) } static private
Referenced by NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithFixtureArgsAndSetTypeArgs(), NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithJustTypeArgs(), and NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithNoArgumentsAndSetTypeArgs().
combinedArgs
object [] NUnit.Framework.Attributes.TestFixtureAttributeTests.combinedArgs = new object[] { typeof(int), typeof(string), 10, 20, "Charlie" } static private
Referenced by NUnit.Framework.Attributes.TestFixtureAttributeTests.ConstructWithCombinedArgs().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/TestFixtureAttributeTests.cs