Doc: IGLib EXTENDED: AForge.DebuggerVisualizers.ImageView Class Reference
AForge.DebuggerVisualizers.ImageView Class Reference
Public Member Functions
ImageView ()
void SetImage (Image image)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void ImageView_Resize (object sender, EventArgs e)
void ImageView_Load (object sender, EventArgs e)
void UpdateViewSize ()
void clipboardButton_Click (object sender, EventArgs e)
void saveButton_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.Panel imagePanel
AForge.Controls.PictureBox pictureBox
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.Button clipboardButton
System.Windows.Forms.Button saveButton
System.Windows.Forms.SaveFileDialog saveFileDialog
Constructor & Destructor Documentation
ImageView()
AForge.DebuggerVisualizers.ImageView.ImageView () inline
References AForge.DebuggerVisualizers.ImageView.InitializeComponent().
Member Function Documentation
ImageView_Resize()
void AForge.DebuggerVisualizers.ImageView.ImageView_Resize (object sender, EventArgs e) inline private
References AForge.DebuggerVisualizers.ImageView.UpdateViewSize().
Referenced by AForge.DebuggerVisualizers.ImageView.InitializeComponent().
ImageView_Load()
void AForge.DebuggerVisualizers.ImageView.ImageView_Load (object sender, EventArgs e) inline private
References AForge.DebuggerVisualizers.ImageView.pictureBox.
Referenced by AForge.DebuggerVisualizers.ImageView.InitializeComponent().
SetImage()
void AForge.DebuggerVisualizers.ImageView.SetImage (Image image) inline
References AForge.DebuggerVisualizers.ImageView.clipboardButton, AForge.DebuggerVisualizers.ImageView.pictureBox, AForge.DebuggerVisualizers.ImageView.saveButton, and AForge.DebuggerVisualizers.ImageView.UpdateViewSize().
Referenced by AForge.DebuggerVisualizers.ImageVisualizer.Show(), AForge.DebuggerVisualizers.UnmanagedImageVisualizer.Show(), and AForge.DebuggerVisualizers.BitmapDataVisualizer.Show().
UpdateViewSize()
void AForge.DebuggerVisualizers.ImageView.UpdateViewSize () inline private
References AForge.DebuggerVisualizers.ImageView.imagePanel, and AForge.DebuggerVisualizers.ImageView.pictureBox.
Referenced by AForge.DebuggerVisualizers.ImageView.ImageView_Resize(), and AForge.DebuggerVisualizers.ImageView.SetImage().
clipboardButton_Click()
void AForge.DebuggerVisualizers.ImageView.clipboardButton_Click (object sender, EventArgs e) inline private
References AForge.DebuggerVisualizers.ImageView.pictureBox.
Referenced by AForge.DebuggerVisualizers.ImageView.InitializeComponent().
saveButton_Click()
void AForge.DebuggerVisualizers.ImageView.saveButton_Click (object sender, EventArgs e) inline private
References AForge.DebuggerVisualizers.ImageView.pictureBox, and AForge.DebuggerVisualizers.ImageView.saveFileDialog.
Referenced by AForge.DebuggerVisualizers.ImageView.InitializeComponent().
Dispose()
override void AForge.DebuggerVisualizers.ImageView.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References AForge.DebuggerVisualizers.ImageView.components.
InitializeComponent()
void AForge.DebuggerVisualizers.ImageView.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References AForge.DebuggerVisualizers.ImageView.clipboardButton, AForge.DebuggerVisualizers.ImageView.clipboardButton_Click(), AForge.DebuggerVisualizers.ImageView.groupBox1, AForge.DebuggerVisualizers.ImageView.groupBox2, AForge.DebuggerVisualizers.ImageView.imagePanel, AForge.DebuggerVisualizers.ImageView.ImageView_Load(), AForge.DebuggerVisualizers.ImageView.ImageView_Resize(), AForge.DebuggerVisualizers.ImageView.pictureBox, AForge.DebuggerVisualizers.ImageView.saveButton, AForge.DebuggerVisualizers.ImageView.saveButton_Click(), and AForge.DebuggerVisualizers.ImageView.saveFileDialog.
Referenced by AForge.DebuggerVisualizers.ImageView.ImageView().
Member Data Documentation
components
System.ComponentModel.IContainer AForge.DebuggerVisualizers.ImageView.components = null private
Required designer variable.
Referenced by AForge.DebuggerVisualizers.ImageView.Dispose().
groupBox1
System.Windows.Forms.GroupBox AForge.DebuggerVisualizers.ImageView.groupBox1 private
Referenced by AForge.DebuggerVisualizers.ImageView.InitializeComponent().
imagePanel
System.Windows.Forms.Panel AForge.DebuggerVisualizers.ImageView.imagePanel private
Referenced by AForge.DebuggerVisualizers.ImageView.InitializeComponent(), and AForge.DebuggerVisualizers.ImageView.UpdateViewSize().
pictureBox
AForge.Controls.PictureBox AForge.DebuggerVisualizers.ImageView.pictureBox private
Referenced by AForge.DebuggerVisualizers.ImageView.clipboardButton_Click(), AForge.DebuggerVisualizers.ImageView.ImageView_Load(), AForge.DebuggerVisualizers.ImageView.InitializeComponent(), AForge.DebuggerVisualizers.ImageView.saveButton_Click(), AForge.DebuggerVisualizers.ImageView.SetImage(), and AForge.DebuggerVisualizers.ImageView.UpdateViewSize().
groupBox2
System.Windows.Forms.GroupBox AForge.DebuggerVisualizers.ImageView.groupBox2 private
Referenced by AForge.DebuggerVisualizers.ImageView.InitializeComponent().
clipboardButton
System.Windows.Forms.Button AForge.DebuggerVisualizers.ImageView.clipboardButton private
Referenced by AForge.DebuggerVisualizers.ImageView.InitializeComponent(), and AForge.DebuggerVisualizers.ImageView.SetImage().
saveButton
System.Windows.Forms.Button AForge.DebuggerVisualizers.ImageView.saveButton private
Referenced by AForge.DebuggerVisualizers.ImageView.InitializeComponent(), and AForge.DebuggerVisualizers.ImageView.SetImage().
saveFileDialog
System.Windows.Forms.SaveFileDialog AForge.DebuggerVisualizers.ImageView.saveFileDialog private
Referenced by AForge.DebuggerVisualizers.ImageView.InitializeComponent(), and AForge.DebuggerVisualizers.ImageView.saveButton_Click().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Tools/DebuggerVisualizers/ImageView.cs
shelldev/lib_ann/aforge.net/Tools/DebuggerVisualizers/ImageView.Designer.cs