Doc: IGLib EXTENDED: alglib.fht Class Reference
alglib.fht Class Reference
Static Public Member Functions
static void fhtr1d (ref double[] a, int n)
static void fhtr1dinv (ref double[] a, int n)
static void fhtr1d (ref double[] a, int n)
static void fhtr1dinv (ref double[] a, int n)
Member Function Documentation
fhtr1d() [1/2]
static void alglib.fht.fhtr1d (ref double[] a, int n) inline static
References alglib.ap.assert(), and alglib.fft.fftr1d().
Referenced by alglib.fhtr1d(), alglib.fht.fhtr1dinv(), and alglib.testfhtunit.testfht().
fhtr1dinv() [1/2]
static void alglib.fht.fhtr1dinv (ref double[] a, int n) inline static
References alglib.ap.assert(), and alglib.fht.fhtr1d().
Referenced by alglib.fhtr1dinv(), and alglib.testfhtunit.testfht().
fhtr1d() [2/2]
static void alglib.fht.fhtr1d (ref double[] a, int n) inline static
References alglib.ap.assert(), and alglib.fft.fftr1d().
fhtr1dinv() [2/2]
static void alglib.fht.fhtr1dinv (ref double[] a, int n) inline static
References alglib.ap.assert(), and alglib.fht.fhtr1d().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/fasttransforms.cs