Doc: IGLib EXTENDED: NUnit.Engine.Runners.TestDomainRunner Class Reference
NUnit.Engine.Runners.TestDomainRunner Class Reference
TestDomainRunner loads and runs tests in a separate domain whose lifetime it controls.
Public Member Functions
TestDomainRunner (IServiceLocator services, TestPackage package)
override void UnloadPackage ()
Unload any loaded TestPackage as well as the AppDomain.
Public Member Functions inherited from NUnit.Engine.Runners.DirectTestRunner
DirectTestRunner (IServiceLocator services, TestPackage package)
override void StopRun (bool force)
Cancel the ongoing test run. If no test is running, the call is ignored.
Public Member Functions inherited from NUnit.Engine.Runners.AbstractTestRunner
AbstractTestRunner (IServiceLocator services, TestPackage package)
TestEngineResult Explore (TestFilter filter)
Explores the TestPackage and returns information about the tests found. Loads the package if not done previously.
TestEngineResult Load ()
Loads the TestPackage for exploration or execution, saving the result.
TestEngineResult Reload ()
Reload the currently loaded test package, saving the result.
void Unload ()
Unload any loaded TestPackage.
int CountTestCases (TestFilter filter)
Count the test cases that would be run under the specified filter, loading the TestPackage if it is not already loaded.
TestEngineResult Run (ITestEventListener listener, TestFilter filter)
Run the tests in the TestPackage, loading the package if this has not already been done.
AsyncTestEngineResult RunAsync (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the loaded TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses.
void StartRun (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses. Loads the TestPackage if not already loaded.
void Dispose ()
Protected Member Functions
override TestEngineResult LoadPackage ()
Load a TestPackage for exploration or execution
Protected Member Functions inherited from NUnit.Engine.Runners.DirectTestRunner
override TestEngineResult ExploreTests (TestFilter filter)
Explores a previously loaded TestPackage and returns information about the tests found.
override int CountTests (TestFilter filter)
Count the test cases that would be run under the specified filter.
override TestEngineResult RunTests (ITestEventListener listener, TestFilter filter)
Run the tests in the loaded TestPackage.
Protected Member Functions inherited from NUnit.Engine.Runners.AbstractTestRunner
virtual TestEngineResult ReloadPackage ()
Reload the currently loaded test package. Overridden in derived classes to take any additional action.
virtual AsyncTestEngineResult RunTestsAsync (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the loaded TestPackage, returning immediately. The tests are run asynchronously and the listener interface is notified as it progresses.
virtual void Dispose (bool disposing)
bool IsProjectPackage (TestPackage package)
Private Attributes
DomainManager _domainManager
Additional Inherited Members
Protected Attributes inherited from NUnit.Engine.Runners.AbstractTestRunner
bool _disposed = false
Static Protected Attributes inherited from NUnit.Engine.Runners.AbstractTestRunner
const string TEST_RUN_ELEMENT = "test-run"
Properties inherited from NUnit.Engine.Runners.DirectTestRunner
AppDomain TestDomain [get, set]
Properties inherited from NUnit.Engine.Runners.AbstractTestRunner
IServiceLocator Services [get, private set]
Our Service Context
IProjectService ProjectService [get, private set]
ITestRunnerFactory TestRunnerFactory [get, private set]
TestPackage TestPackage [get, set]
The TestPackage for which this is the runner
TestEngineResult LoadResult [get, set]
The result of the last call to LoadPackage
bool IsPackageLoaded [get]
Gets an indicator of whether the package has been loaded.
Detailed Description
TestDomainRunner loads and runs tests in a separate domain whose lifetime it controls.
Constructor & Destructor Documentation
TestDomainRunner()
NUnit.Engine.Runners.TestDomainRunner.TestDomainRunner (IServiceLocator services, TestPackage package) inline
References NUnit.Engine.Runners.TestDomainRunner._domainManager, NUnit.Engine.IServiceLocator.GetService(), and NUnit.Engine.Runners.AbstractTestRunner.Services.
Member Function Documentation
LoadPackage()
override TestEngineResult NUnit.Engine.Runners.TestDomainRunner.LoadPackage () inline protected virtual
Load a TestPackage for exploration or execution
Returns
A TestEngineResult.
Reimplemented from NUnit.Engine.Runners.DirectTestRunner.
References NUnit.Engine.Runners.TestDomainRunner._domainManager, NUnit.Engine.Services.DomainManager.CreateDomain(), and NUnit.Engine.Runners.DirectTestRunner.TestDomain.
UnloadPackage()
override void NUnit.Engine.Runners.TestDomainRunner.UnloadPackage () inline virtual
Unload any loaded TestPackage as well as the AppDomain.
Reimplemented from NUnit.Engine.Runners.AbstractTestRunner.
References NUnit.Engine.Runners.DirectTestRunner.TestDomain, and NUnit.Engine.Services.DomainManager.Unload().
Member Data Documentation
_domainManager
DomainManager NUnit.Engine.Runners.TestDomainRunner._domainManager private
Referenced by NUnit.Engine.Runners.TestDomainRunner.LoadPackage(), and NUnit.Engine.Runners.TestDomainRunner.TestDomainRunner().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Runners/TestDomainRunner.cs