Doc: IGLib EXTENDED: NUnit.Framework.Internal.Tests.TestNameGeneratorTests Class Reference
NUnit.Framework.Internal.Tests.TestNameGeneratorTests Class Reference
Public Member Functions
void InitializeMethodInfos ()
string SimpleTestNames (string pattern)
string ParameterizedTests (string pattern, object[] args)
string GenericTestNames (string pattern)
string ErrorInPattern (string pattern)
string SpecialNamedValues (object arg)
Private Member Functions
void TestMethod ()
void GenericTest< T, U, V > ()
Private Attributes
TestMethod _simpleTest
TestMethod _genericTest
Member Function Documentation
InitializeMethodInfos()
void NUnit.Framework.Internal.Tests.TestNameGeneratorTests.InitializeMethodInfos () inline
References NUnit.Framework.Internal.Tests.TestNameGeneratorTests._genericTest, NUnit.Framework.Internal.Tests.TestNameGeneratorTests._simpleTest, NUnit.Framework.Internal.Test.Id, and NUnit.Framework.Internal.Tests.TestNameGeneratorTests.TestMethod().
SimpleTestNames()
string NUnit.Framework.Internal.Tests.TestNameGeneratorTests.SimpleTestNames (string pattern) inline
References NUnit.Framework.Internal.Tests.TestNameGeneratorTests._simpleTest, and NUnit.Framework.Internal.TestNameGenerator.GetDisplayName().
ParameterizedTests()
string NUnit.Framework.Internal.Tests.TestNameGeneratorTests.ParameterizedTests (string pattern, object[] args) inline
References NUnit.Framework.Internal.Tests.TestNameGeneratorTests._simpleTest, and NUnit.Framework.Internal.TestNameGenerator.GetDisplayName().
GenericTestNames()
string NUnit.Framework.Internal.Tests.TestNameGeneratorTests.GenericTestNames (string pattern) inline
References NUnit.Framework.Internal.Tests.TestNameGeneratorTests._genericTest, and NUnit.Framework.Internal.TestNameGenerator.GetDisplayName().
ErrorInPattern()
string NUnit.Framework.Internal.Tests.TestNameGeneratorTests.ErrorInPattern (string pattern) inline
References NUnit.Framework.Internal.Tests.TestNameGeneratorTests._simpleTest, and NUnit.Framework.Internal.TestNameGenerator.GetDisplayName().
SpecialNamedValues()
string NUnit.Framework.Internal.Tests.TestNameGeneratorTests.SpecialNamedValues (object arg) inline
References NUnit.Framework.Internal.Tests.TestNameGeneratorTests._simpleTest, and NUnit.Framework.Internal.TestNameGenerator.GetDisplayName().
TestMethod()
void NUnit.Framework.Internal.Tests.TestNameGeneratorTests.TestMethod () inline private
Referenced by NUnit.Framework.Internal.Tests.TestNameGeneratorTests.InitializeMethodInfos().
GenericTest< T, U, V >()
void NUnit.Framework.Internal.Tests.TestNameGeneratorTests.GenericTest< T, U, V > () inline private
Member Data Documentation
_simpleTest
TestMethod NUnit.Framework.Internal.Tests.TestNameGeneratorTests._simpleTest private
Referenced by NUnit.Framework.Internal.Tests.TestNameGeneratorTests.ErrorInPattern(), NUnit.Framework.Internal.Tests.TestNameGeneratorTests.InitializeMethodInfos(), NUnit.Framework.Internal.Tests.TestNameGeneratorTests.ParameterizedTests(), NUnit.Framework.Internal.Tests.TestNameGeneratorTests.SimpleTestNames(), and NUnit.Framework.Internal.Tests.TestNameGeneratorTests.SpecialNamedValues().
_genericTest
TestMethod NUnit.Framework.Internal.Tests.TestNameGeneratorTests._genericTest private
Referenced by NUnit.Framework.Internal.Tests.TestNameGeneratorTests.GenericTestNames(), and NUnit.Framework.Internal.Tests.TestNameGeneratorTests.InitializeMethodInfos().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/TestNameGeneratorTests.cs