Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGBTF2 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGBTF2 Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGBTF2 (IDAMAX idamax, DGER dger, DSCAL dscal, DSWAP dswap, XERBLA xerbla)
DGBTF2 ()
void Run (int M, int N, int KL, int KU, ref double[] AB, int offset_ab, int LDAB, ref int[] IPIV, int offset_ipiv, ref int INFO)
Private Attributes
IDAMAX _idamax
DGER _dger
DSCAL _dscal
DSWAP _dswap
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGBTF2 computes an LU factorization of a real m-by-n band matrix A using partial pivoting with row interchanges.
This is the unblocked version of the algorithm, calling Level 2 BLAS.
/summary>
Constructor & Destructor Documentation
DGBTF2() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGBTF2.DGBTF2 (IDAMAX idamax, DGER dger, DSCAL dscal, DSWAP dswap, XERBLA xerbla) inline
DGBTF2() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGBTF2.DGBTF2 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGBTF2.Run (int M, int N, int KL, int KU, ref double[] AB, int offset_ab, int LDAB, ref int[] IPIV, int offset_ipiv, ref int INFO) inline
Purpose
DGBTF2 computes an LU factorization of a real m-by-n band matrix A using partial pivoting with row interchanges.
This is the unblocked version of the algorithm, calling Level 2 BLAS.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. 0. /param>
Parameters
KL (input) INTEGER The number of subdiagonals within the band of A. KL .GE. 0. /param>
Parameters
KU (input) INTEGER The number of superdiagonals within the band of A. KU .GE. 0. /param>
Parameters
AB (input/output) DOUBLE PRECISION array, dimension (LDAB,N) On entry, the matrix A in band storage, in rows KL+1 to 2*KL+KU+1; rows 1 to KL of the array need not be set. The j-th column of A is stored in the j-th column of the array AB as follows: AB(kl+ku+1+i-j,j) = A(i,j) for max(1,j-ku).LE.i.LE.min(m,j+kl)
On exit, details of the factorization: U is stored as an upper triangular band matrix with KL+KU superdiagonals in rows 1 to KL+KU+1, and the multipliers used during the factorization are stored in rows KL+KU+2 to 2*KL+KU+1. See below for further details. /param>
Parameters
LDAB (input) INTEGER The leading dimension of the array AB. LDAB .GE. 2*KL+KU+1. /param>
Parameters
IPIV (output) INTEGER array, dimension (min(M,N)) The pivot indices; for 1 .LE. i .LE. min(M,N), row i of the matrix was interchanged with row IPIV(i). /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value .GT. 0: if INFO = +i, U(i,i) is exactly zero. The factorization has been completed, but the factor U is exactly singular, and division by zero will occur if it is used to solve a system of equations. /param>
References DotNumerics.LinearAlgebra.CSLapack.DGBTF2.ONE, DotNumerics.LinearAlgebra.CSLapack.DSWAP.Run(), DotNumerics.LinearAlgebra.CSLapack.IDAMAX.Run(), DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DGER.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGBTF2.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGBTRF.Run().
Member Data Documentation
_idamax
IDAMAX DotNumerics.LinearAlgebra.CSLapack.DGBTF2._idamax private
_dger
DGER DotNumerics.LinearAlgebra.CSLapack.DGBTF2._dger private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DGBTF2._dscal private
_dswap
DSWAP DotNumerics.LinearAlgebra.CSLapack.DGBTF2._dswap private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGBTF2._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGBTF2.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGBTF2.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DGBTF2.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGBTF2.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgbtf2.cs