Doc: IGLib EXTENDED: IG.Forms.TimerControlWorking Class Reference
IG.Forms.TimerControlWorking Class Reference
Public Member Functions
TimerControlWorking ()
Constructs a timer control.
void LoadDefaultSounds ()
virtual void PlaySoundStart ()
Plays the sound associated with clicking the start button.
virtual void PlaySoundStop ()
Plays the sound associated with clicking the stop button.
virtual void PlaySoundReset ()
Plays the sound associated with clicking the reset button.
virtual void PlaySoundSecondTick ()
Plays the sound associated with a second tick.
virtual void PlaySoundMinuteBell ()
Plays the sound associated with the whole minute switch.
virtual void PlaySoundHourBell ()
Plays the sound associated with the whole minute switch.
virtual void PlaySoundAlarmCountdown ()
Plays the sound associated with a countdown end.
void UpdateDisplayFonts ()
Updates fonts that are dependent on the main display font, according to this font.
void SetDisplayFontSize (double sizeInPoints)
Changes size of the display font.
void SetDisplayFontSize (decimal sizeInPointsDecimal)
Changes size of the display font.
virtual void StopwatchStartOrStop ()
Starts (if it is not running) or stops (if it is running) the stopwatch.
virtual void StopwatchStart ()
Starts the stopwatch.
virtual void StopwatchStop ()
Stops the stopwatch timer.
virtual void CountdownStartOrStop ()
Starts (if it is not running) or stops (if it is running) the countdown.
virtual void CountdownStart ()
Starts the countdown timer.
virtual void CountdownStop ()
Stops the countdown timer.
Static Public Attributes
static int DefaultMaxNumTimerErrorReports = 10
Default maximal number of times a report about timer tick exception is launched.
Protected Member Functions
virtual void UpdateDisplays ()
Updates timer's displays.
virtual void UpdateSwDisplay ()
Refreshes stopwatch's display according to elapsed time.
virtual void UpdateSwControls ()
Updates stopwatch controls according to internal properties.
virtual void UpdateDisplayAppearance ()
Updates fonts on the timer's displays.
virtual void UpdateSwButtonsAppearance ()
Updates appearance of the stopwatch buttons.
virtual void OnStopwatchTimerTick ()
Called when the timer event fires (very often, in the range of milliseconds). Raises the StopwatchTimerTick event and updates the display.
virtual void StopwatchResetIt ()
Resets the stopwatch.
virtual void OnStopwatchSecondTick ()
Called when the stopwatch seconds count reaches a whole value (seconds tick). Raises the StopwatchSecondTick event and eventually plays the appropriate "second tick" sound (if not IsSilent and if IsSwSoundSecondTick).
virtual void OnStopwatchMinuteBell ()
Called when the stopwatch minutes count reaches a whole value (minutes signal). Raises the StopwatchMinuteBell event and eventually plays the appropriate "minutes bell" sound (if not IsSilent and if IsSwSoundMinuteBell).
virtual void OnStopwatchHourBell ()
Called when the stopwatch hours count reaches a whole value (hour switch signal). Raises the StopwatchHourBell event and eventually plays the appropriate "hours bell" sound (if not IsSilent and if IsSwSoundHourBell).
virtual void UpdateCdInitialTimeSpan ()
Updates initial TimeSpan of the countdown in such a way that it corresponds to its initial hours, minutes, seconds, and miilliseconds.
virtual void UpdateCdInitialTime ()
Updates initial hours, minutes, seconds, and milliseconds of the countdown in such a way that they correspond to its intial TimeSpan.
virtual void UpdateCdDisplay ()
Refreshes countdown's display according to elapsed time.
virtual void UpdateCdControls ()
Updates countdown controls according to internal properties.
virtual void UpdateCdButtonsAppearance ()
Updates appearance of the stopwatch buttons.
virtual void UpdateWatchDisplay ()
Refreshes watch' display according to the current time.
virtual void OnCountdownTimerTick ()
Called when the timer event fires (very often, in the range of milliseconds). Raises the CountdownTimerTick event and updates the display.
virtual void CountdownResetIt ()
Resets the countdown.
virtual void OnCountdownFinished ()
Called when the countdown reaches 0 and stops counting down. Raises the CountdownFinished event and eventually plays the appropriate alarm (if not IsSilent and if IsCdSoundAlarm).
virtual void OnCountdownSecondTick ()
Called when the countdown seconds count reaches a whole value (seconds tick). Raises the CountdownSecondTick event and eventually plays the appropriate "second tick" sound (if not IsSilent and if IsCdSoundSecondTick).
virtual void OnCountdownMinuteBell ()
Called when the countdown minutes count reaches a whole value (minutes signal). Raises the CountdownMinuteBell event and eventually plays the appropriate "minutes bell" sound (if not IsSilent and if IsCdSoundMinuteBell).
virtual void OnCountdownHourBell ()
Called when the countdown hours count reaches a whole value (hours signal). Raises the CountdownHourBell event and eventually plays the appropriate "hours bell" sound (if not IsSilent and if IsCdSoundHourBell).
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
SoundPlayer _soundPlayerStart = null
SoundPlayer _soundPlayerStop = null
SoundPlayer _soundPlayerReset = null
SoundPlayer _soundPlayerSecondTick = null
SoundPlayer _soundPlayerMinuteBell = null
SoundPlayer _soundPlayerHourBell = null
SoundPlayer _soundPlayerAlarmCountdown = null
Font _displayFont = null
TimeSpan _swPreviousSpan
TimeSpan _swCurrentSpan
TimeSpan _cdPreviousRemainingSpan
TimeSpan _cdCurrentRemainingSpan
bool _isClockRunnng = false
Properties
static int DefaultOutputLevel [get, set]
Default output level for this class of objects.
int OutputLevel [get, set]
Current output level for the current object.
int MaxPlayErrors [get, set]
int NumPlayErrors [get, set]
virtual SoundPlayer SoundPlayerStart [get]
Gets the sound player for playing sound when a start button is pressed. Player is pre-laded with the appropriate sound.
virtual SoundPlayer SoundPlayerStop [get]
Gets the sound player for playing sound when the stop button is pressed. Player is pre-laded with the appropriate sound.
virtual SoundPlayer SoundPlayerReset [get]
Gets the sound player for playing sound when the resett button is pressed. Player is pre-laded with the appropriate sound.
virtual SoundPlayer SoundPlayerSecondTick [get]
Gets the sound player for playing sound when another second passes (a second tick). Player is pre-laded with the appropriate sound.
virtual SoundPlayer SoundPlayerMinuteBell [get]
Gets the sound player for playing sound when another minute passes (a minute bell). Player is pre-laded with the appropriate sound.
virtual SoundPlayer SoundPlayerHourBell [get]
Gets the sound player for playing sound when another hour passes (a hour bell). Player is pre-laded with the appropriate sound.
virtual SoundPlayer SoundPlayerAlarmCountdown [get]
Gets the sound player for playing alarm when countdown finishes. Player is pre-laded with the appropriate sound.
virtual bool IsSwSoundSecondTick [get, set]
Whether a tick sound is switched on (launched every second when the stopwatch is running).
virtual bool IsSwSoundMinuteBell [get, set]
Whether a minutes bell sound is switched on (launched every minute when the stopwatch is running).
virtual bool IsSwSoundHourBell [get, set]
Whether a hour bell sound is switched on (launched every hour when the stopwatch is running).
virtual bool IsSwSoundButtons [get, set]
Whether the stopwatch's button sound is switched on (launched every time a stopwatch button with some effect is pressed, or the same effect is achieved programatically).
virtual bool IsCdSoundSecondTick [get, set]
Whether the countdown's tick sound is switched on (a sound launched every second when the countdown is running).
virtual bool IsCdSoundMinuteBell [get, set]
Whether the countdown's minute bell sound is switched on (a sound launched every minute when the countdown is running).
virtual bool IsCdSoundHourBell [get, set]
Whether the countdown's hpur bell sound is switched on (a sound launched every hour when the countdown is running).
bool IsRunning [get]
Indicates whether the timer is currently running or not.
int TimerIntervalMs [get, set]
Timer interval, in Milliseconds.
virtual bool IsSilent [get, set]
Flag specifying whether the complete timer is in a silent mode.
StopWatch1 SwStopwatch [get]
Stopwatch used to measure elapsed time for the displayed stopwatch.
bool IsStopwatchRunning [get]
Indicates whether the countdown timer is running or not.
TimeSpan StopwatchTotalTimeSpan [get]
Gets the current time span measured by the stopwatch.
double StopWatchTotalTime [get]
Gets the current time span measured by the stopwatch.
Font FontMilli [get, set]
Font used in timer's displays for milliseconds.
Font DisplayFont [get, set]
Font used in timerr's displays.
double MilliSecondsSizeRatio [get, set]
Ratio between the size of millisecond digits and other digits on the stopwatch.
double MinDispayFontSizeInPoints [get, protected set]
Minimal size of display font, in points.
bool SwShowMilliSeconds [get, set]
Whether milliseconds shoulld be shown.
bool SwShowHoursWhenZero [get, set]
Color ColorBgWarning [get, set]
Color ColorBgOk [get, set]
Color ColorInvisible [get]
Color DisplayBg [get, protected set]
Display background color.
Color DisplayFg [get, protected set]
Display foreground color.
string SwStartText [get, set]
Text that is written on the stopwatch start button.
string SwStopText [get, set]
string SwResetText [get, protected set]
Color SwStartColor [get, protected set]
Background color for stopwatch start button.
Color SwStopColor [get, protected set]
Color SwResetColor [get, protected set]
Background color for stopwatch reset button.
Color ControlsFgClosed [get, protected set]
Foreground color for controls opener when controls are closed.
Color ControlsFgOpen [get, protected set]
Foreground color for controls opener when controls are opened.
string ControlsClosedText [get, protected set]
Tect for controls opener when controls are closed.
string ControlsOpenText [get, protected set]
Tect for controls opener when controls are opened.
bool IsSwControlsOpened [get, protected set]
Wheether controls are opened or not.
int MaxTimerErrorReports [get, set]
Macimal number of times a report on exception thrown within the timer tick event can be launched.
int NumTimerErrorReports [get, set]
Number of times a report on exception thrown within the timer tick event has already been launched.
StopWatch1 CdStopwatch [get]
Stopwatch used to measure elapsed time for the displayed cowntdown.
bool IsCountdownRunning [get]
Indicates whether the countdown timer is running or not.
TimeSpan CountdownTotalTimeSpan [get]
Gets the current total time span measured by the countdown's stopwatch.
double CountdownTotalTime [get]
Gets the current time span measured by the countdown's stopwatch.
TimeSpan CountdownRemainingTimeSpan [get]
Gets Countdown's remaining time span.
double CountdownRemainingTime [get]
Returns Countdown's remaining time in seconds.
virtual int CdInitialHours [get, set]
Number of hours initially set in countdown.
virtual int CdInitialMinutes [get, set]
Number of minutes initially set in countdown.
virtual int CdInitialSeconds [get, set]
Number of seconds initially set in countdown.
virtual int CdInitialMilliseconds [get, set]
Number of milliseconds initially set in countdown.
virtual TimeSpan CdInitialTimeSpan [get, set]
Initial time span set in countdown.
bool CdShowMilliSeconds [get, set]
Whether milliseconds shoulld be shown on countdown.
bool CdShowHoursWhenZero [get, set]
virtual bool IsCdSoundButtons [get, set]
Whether the countdown's button sound is switched on (a sound launched every time a countdown button with some effectt is pressed, or the same effect is achieved programatically).
virtual bool IsCdSoundAlarm [get, set]
Whether a countdown's alarm sound is switched on (launched when the countdown is finished, i.e. the countdown reachhes zero).
string CdStartText [get, set]
Text that is written on the stopwatch start button.
string CdStopText [get, set]
string CdResetText [get, protected set]
Color CdStartColor [get, protected set]
Background color for stopwatch start button.
Color CdStopColor [get, protected set]
Color CdResetColor [get, protected set]
bool IsCdControlsOpened [get, protected set]
Wheether controls are opened or not.
bool IsClockRunning [get, set]
Events
EventHandler StopwatchTimerTick
Event that is fired on each stopwatch's timer tick (very often, in the range of milliseconds).
EventHandler StopwatchStarted
Event that is fired when the stopwatch starts.
EventHandler StopwatchStopped
Event that is fired when the stopwatch stops.
EventHandler StopwatchReset
Event that is raised when the counter is reset.
EventHandler StopwatchSecondTick
Event that is fired when second count changes to a whole value (seconds tick).
EventHandler StopwatchMinuteBell
Event that is fired when minutes count changes to a whole value (minutes signal).
EventHandler StopwatchHourBell
Event that is fired when minutes count changes to a whole value (minute switch signal).
EventHandler CountdownTimerTick
Event that is fired on each countdown's timer tick (very often, in the range of milliseconds).
EventHandler CountdownStarted
Event that is fired when the countdown starts.
EventHandler CountdownStopped
Event that is fired when the countdown stops.
EventHandler CountdownReset
Event that is raised when the counter is reset.
EventHandler CountdownFinished
Event that is fired when the countdown reaches 0.
EventHandler CountdownSecondTick
Event that is fired when second count changes to a whole value (seconds tick).
EventHandler CountdownMinuteBell
Event that is fired when minutes count changes to a whole value (minutes signal).
EventHandler CountdownHourBell
Event that is fired when gours count changes to a whole value (hours signal).
Private Member Functions
void ReportSoundError (string soundDescriptor, Exception ex)
void timer1_Tick (object sender, EventArgs e)
Timer event handlesr, executed on every tick of thr timer.
void StopWatchControl_Load (object sender, EventArgs e)
void btnSwControls_Click (object sender, EventArgs e)
Toggles opening/closing stopwatch's controls panel.
void chkSwSilent_CheckedChanged (object sender, EventArgs e)
Toggles silent mode.
void btnSwStartStop_Click (object sender, EventArgs e)
Start / stop button pressed.
void btnSwReset_Click (object sender, EventArgs e)
void flowPanelOuter_SizeChanged (object sender, EventArgs e)
Fired on size change of the outer panel of the control. Currently not used, but this event can be used fo triger the appropriate actions (e.g. adjust the size) of containing controls. Now containing controls are adjusted automatically (by appropriate property setting).
void fontSelectorSw_FontSelected (object sender, FontEventArgs args)
Trigered by font selector control when a new font was selected in it.
void fontSelector_Load (object sender, EventArgs e)
Not used.
void fontSelector_FontSelected (object sender, FontEventArgs args)
When font is selected by the font selector, it sets the display font in this control to the selected font.
void numFontSize_ValueChanged (object sender, EventArgs e)
void numSwFontSize_Enter (object sender, EventArgs e)
Selects the contents for easy changing by typing.
void numSwFontSize_Click (object sender, EventArgs e)
Selects the contents for easy changing by typing.
void chkSwDisplayMilliseconds_CheckedChanged (object sender, EventArgs e)
void chkSwDisplayHours_CheckedChanged (object sender, EventArgs e)
void btnCdControls_Click (object sender, EventArgs e)
Toggles between open / closed control panel for the countdown.
void chkCdSilent_CheckedChanged (object sender, EventArgs e)
Toggles silent mode.
void fontSelectorCd_FontSelected (object sender, FontEventArgs args)
void btnCdStartStop_Click (object sender, EventArgs e)
void btnCdReset_Click (object sender, EventArgs e)
void chkCdDisplayMilliseconds_CheckedChanged (object sender, EventArgs e)
void chkCdDisplayHours_CheckedChanged (object sender, EventArgs e)
void numCdFontSize_ValueChanged (object sender, EventArgs e)
void numCdFontSize_Enter (object sender, EventArgs e)
void numCdFontSize_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
int _outputLevel = DefaultOutputLevel
int _maxPlayErrors = 5
bool _isSwSoundSecondTick = true
bool _isSwSoundMinuteBell = true
bool _isSwSoundHourBell = true
bool _isSwSoundButtonPressed = true
bool _isCdSoundSecondTick = true
bool _isCdSoundMinuteBell = true
bool _isCdSoundHourBell = true
int _timerIntervalMs = 5
bool _isSilent = true
StopWatch1 _swStopwatch
Font _fontMilli = null
double _millisecondsSizeRatio = 0.5
double _minDispayFontSizeInPoints = 2.0
bool _swShowMilliSeconds = true
bool _swShowHoursWhenZero = true
Whether hours shoulld be shown when they are zero.
Color _colorBgWarning = Color.Red
Color _colorBgOk = Color.Green
Color _displayBg = Color.PaleGoldenrod
Color _displayFg = Color.SeaGreen
string _swStartText = "Start"
string _swStopText = "Pause"
string _swResetText = "Reset"
Color _swStartColor = Color.Green
Color _swStopColor = Color.LightSalmon
Background color for stopwatch stop button.
Color _swResetColor = Color.LightSalmon
Color _controlsFgClosed = Color.Black
Color _controlsFgOpen = Color.Blue
string _controlsClosedText = ""
string _ontrolsOpenText = ""
bool _swControlsOpen = false
int _maxTimerErrorReports = DefaultMaxNumTimerErrorReports
int _numTimerErrorReports = 0
StopWatch1 _cdStopwatch
int _cdInitialHours = 0
int _cdInitialMinutes = 0
int _cdInitialSecods = 0
int _cdInitialMs = 0
TimeSpan _cdInitialTimeSpan = new TimeSpan(0, 0, 10, 0)
bool _cdShowMilliSeconds = true
bool _cdShowHoursWhenZero = true
Whether hours shoulld be shown on countdown when they are zero.
bool _isCdSoundButtonPressed = true
bool _isCdSoundAlarm = true
string _cdStartText = "Start"
string _cdStopText = "Pause"
string _cdResetText = "Reset"
Color _cdStartColor = Color.Green
Color _cdStopColor = Color.LightSalmon
Background color for stopwatch stop button.
Color _cdResetColor = Color.LightSalmon
Background color for countdown reset button.
bool _cdControlsOpen = false
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.FlowLayoutPanel flowSwOuter
System.Windows.Forms.FlowLayoutPanel flowSwDisplay
System.Windows.Forms.Label dispSwHours
System.Windows.Forms.Label dispSwHoursSeparator
System.Windows.Forms.Label dispSwMin
System.Windows.Forms.Label dispSwMinSeparator
System.Windows.Forms.Label dispSwSec
System.Windows.Forms.Button btnSwStartStop
System.Windows.Forms.Button btnSwReset
System.Windows.Forms.Timer timer1
System.Windows.Forms.Button btnSwControls
System.Windows.Forms.GroupBox boxSwControls
System.Windows.Forms.Label lbSwlFontSize
System.Windows.Forms.NumericUpDown numSwFontSize
System.Windows.Forms.FlowLayoutPanel flowSwDisplayTop
System.Windows.Forms.FlowLayoutPanel flowSwDisplayBottom
System.Windows.Forms.Label dispSwSecDecimalPoint
System.Windows.Forms.Label dispSwMilliSec
System.Windows.Forms.FlowLayoutPanel flowSwButtosLeft
System.Windows.Forms.FlowLayoutPanel flowSwButtonsRight
System.Windows.Forms.FlowLayoutPanel flowSwButtons
System.Windows.Forms.FlowLayoutPanel flowSwControlsBasic
System.Windows.Forms.Label lblSwTitle
System.Windows.Forms.FlowLayoutPanel flowCdOuter
System.Windows.Forms.Label lblCdTitle
System.Windows.Forms.FlowLayoutPanel flowLayoutPanel3
System.Windows.Forms.FlowLayoutPanel flowLayoutPanel4
System.Windows.Forms.Label dispCdHours
System.Windows.Forms.Label dispCdHoursSeparator
System.Windows.Forms.Label dispCdMin
System.Windows.Forms.Label dispCdMinSeparator
System.Windows.Forms.Label dispCdSec
System.Windows.Forms.FlowLayoutPanel flowLayoutPanel5
System.Windows.Forms.Label dispCdSecDecimalPoint
System.Windows.Forms.Label dispCdMilliSec
System.Windows.Forms.FlowLayoutPanel flowCdButtons
System.Windows.Forms.FlowLayoutPanel flowCdButtonsLeft
System.Windows.Forms.Button btnCdStartStop
System.Windows.Forms.FlowLayoutPanel flowCdButtonsRight
System.Windows.Forms.Button btnCdReset
System.Windows.Forms.FlowLayoutPanel flowTwControlsBasic
System.Windows.Forms.Label lbTwlFontSize
System.Windows.Forms.NumericUpDown numCdFontSize
System.Windows.Forms.Button btnCdControls
System.Windows.Forms.GroupBox boxCdControls
FontSelectorSimple fontSelectorSw
System.Windows.Forms.CheckBox chkSwDisplayHours
System.Windows.Forms.CheckBox chkSwDisplayMilliseconds
System.Windows.Forms.CheckBox chkCdDisplayMilliseconds
System.Windows.Forms.CheckBox chkCdDisplayHours
FontSelectorSimple fontSelectorCd
System.Windows.Forms.FlowLayoutPanel flowOuter
System.Windows.Forms.Label lblHelpOuterFlow
System.Windows.Forms.CheckBox chkCdSilent
System.Windows.Forms.CheckBox chkSwSilent
Static Private Attributes
static int _defaultOutputLevel = 0
Constructor & Destructor Documentation
TimerControlWorking()
IG.Forms.TimerControlWorking.TimerControlWorking () inline
Constructs a timer control.
References IG.Forms.TimerControlWorking.CdInitialTimeSpan, IG.Forms.TimerControlWorking.CdShowHoursWhenZero, IG.Forms.TimerControlWorking.CdShowMilliSeconds, IG.Forms.TimerControlWorking.chkCdDisplayHours, IG.Forms.TimerControlWorking.chkCdDisplayMilliseconds, IG.Forms.TimerControlWorking.chkSwDisplayHours, IG.Forms.TimerControlWorking.chkSwDisplayMilliseconds, IG.Forms.TimerControlWorking.CountdownResetIt(), IG.Forms.TimerControlWorking.DisplayFont, IG.Forms.TimerControlWorking.dispSwSec, IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.TimerControlWorking.IsCdControlsOpened, IG.Forms.TimerControlWorking.IsSwControlsOpened, IG.Forms.TimerControlWorking.StopwatchResetIt(), IG.Forms.TimerControlWorking.SwShowHoursWhenZero, IG.Forms.TimerControlWorking.SwShowMilliSeconds, IG.Forms.TimerControlWorking.UpdateCdControls(), and IG.Forms.TimerControlWorking.UpdateSwControls().
Member Function Documentation
LoadDefaultSounds()
void IG.Forms.TimerControlWorking.LoadDefaultSounds () inline
References IG.Forms.TimerControlWorking.SoundPlayerStart.
ReportSoundError()
void IG.Forms.TimerControlWorking.ReportSoundError (string soundDescriptor, Exception ex) inline private
References IG.Forms.TimerControlWorking.MaxPlayErrors, and IG.Forms.TimerControlWorking.NumPlayErrors.
Referenced by IG.Forms.TimerControlWorking.PlaySoundAlarmCountdown(), IG.Forms.TimerControlWorking.PlaySoundHourBell(), IG.Forms.TimerControlWorking.PlaySoundMinuteBell(), IG.Forms.TimerControlWorking.PlaySoundReset(), IG.Forms.TimerControlWorking.PlaySoundSecondTick(), IG.Forms.TimerControlWorking.PlaySoundStart(), and IG.Forms.TimerControlWorking.PlaySoundStop().
PlaySoundStart()
virtual void IG.Forms.TimerControlWorking.PlaySoundStart () inline virtual
Plays the sound associated with clicking the start button.
References IG.Forms.TimerControlWorking.ReportSoundError(), and IG.Forms.TimerControlWorking.SoundPlayerStart.
Referenced by IG.Forms.TimerControlWorking.CountdownStart(), and IG.Forms.TimerControlWorking.StopwatchStart().
PlaySoundStop()
virtual void IG.Forms.TimerControlWorking.PlaySoundStop () inline virtual
Plays the sound associated with clicking the stop button.
References IG.Forms.TimerControlWorking.ReportSoundError(), and IG.Forms.TimerControlWorking.SoundPlayerStop.
Referenced by IG.Forms.TimerControlWorking.CountdownStop(), and IG.Forms.TimerControlWorking.StopwatchStop().
PlaySoundReset()
virtual void IG.Forms.TimerControlWorking.PlaySoundReset () inline virtual
Plays the sound associated with clicking the reset button.
References IG.Forms.TimerControlWorking.ReportSoundError(), and IG.Forms.TimerControlWorking.SoundPlayerReset.
PlaySoundSecondTick()
virtual void IG.Forms.TimerControlWorking.PlaySoundSecondTick () inline virtual
Plays the sound associated with a second tick.
References IG.Forms.TimerControlWorking.ReportSoundError(), and IG.Forms.TimerControlWorking.SoundPlayerSecondTick.
Referenced by IG.Forms.TimerControlWorking.OnCountdownSecondTick(), and IG.Forms.TimerControlWorking.OnStopwatchSecondTick().
PlaySoundMinuteBell()
virtual void IG.Forms.TimerControlWorking.PlaySoundMinuteBell () inline virtual
Plays the sound associated with the whole minute switch.
References IG.Forms.TimerControlWorking.ReportSoundError(), and IG.Forms.TimerControlWorking.SoundPlayerMinuteBell.
Referenced by IG.Forms.TimerControlWorking.OnCountdownMinuteBell(), and IG.Forms.TimerControlWorking.OnStopwatchMinuteBell().
PlaySoundHourBell()
virtual void IG.Forms.TimerControlWorking.PlaySoundHourBell () inline virtual
Plays the sound associated with the whole minute switch.
References IG.Forms.TimerControlWorking.ReportSoundError(), and IG.Forms.TimerControlWorking.SoundPlayerMinuteBell.
Referenced by IG.Forms.TimerControlWorking.OnCountdownHourBell(), and IG.Forms.TimerControlWorking.OnStopwatchHourBell().
PlaySoundAlarmCountdown()
virtual void IG.Forms.TimerControlWorking.PlaySoundAlarmCountdown () inline virtual
Plays the sound associated with a countdown end.
References IG.Forms.TimerControlWorking.ReportSoundError(), and IG.Forms.TimerControlWorking.SoundPlayerAlarmCountdown.
Referenced by IG.Forms.TimerControlWorking.OnCountdownFinished().
UpdateDisplayFonts()
void IG.Forms.TimerControlWorking.UpdateDisplayFonts () inline
Updates fonts that are dependent on the main display font, according to this font.
References IG.Forms.TimerControlWorking.DisplayFont, IG.Forms.TimerControlWorking.FontMilli, IG.Forms.TimerControlWorking.MilliSecondsSizeRatio, and IG.Forms.TimerControlWorking.MinDispayFontSizeInPoints.
UpdateDisplays()
virtual void IG.Forms.TimerControlWorking.UpdateDisplays () inline protected virtual
Updates timer's displays.
References IG.Forms.TimerControlWorking.UpdateCdDisplay(), IG.Forms.TimerControlWorking.UpdateSwDisplay(), and IG.Forms.TimerControlWorking.UpdateWatchDisplay().
UpdateSwDisplay()
virtual void IG.Forms.TimerControlWorking.UpdateSwDisplay () inline protected virtual
Refreshes stopwatch's display according to elapsed time.
References IG.Forms.TimerControlWorking.dispSwHours, IG.Forms.TimerControlWorking.dispSwHoursSeparator, IG.Forms.TimerControlWorking.dispSwMilliSec, IG.Forms.TimerControlWorking.dispSwMin, IG.Forms.TimerControlWorking.dispSwMinSeparator, IG.Forms.TimerControlWorking.dispSwSec, IG.Forms.TimerControlWorking.dispSwSecDecimalPoint, IG.Num.M.floor(), IG.Forms.TimerControlWorking.StopwatchTotalTimeSpan, and IG.Forms.TimerControlWorking.SwShowHoursWhenZero.
Referenced by IG.Forms.TimerControlWorking.OnStopwatchTimerTick(), IG.Forms.TimerControlWorking.StopwatchResetIt(), IG.Forms.TimerControlWorking.UpdateDisplays(), and IG.Forms.TimerControlWorking.UpdateSwButtonsAppearance().
UpdateSwControls()
virtual void IG.Forms.TimerControlWorking.UpdateSwControls () inline protected virtual
Updates stopwatch controls according to internal properties.
References IG.Forms.TimerControlWorking.boxSwControls, IG.Forms.TimerControlWorking.btnSwControls, IG.Forms.TimerControlWorking.ControlsClosedText, IG.Forms.TimerControlWorking.ControlsFgClosed, IG.Forms.TimerControlWorking.ControlsFgOpen, IG.Forms.TimerControlWorking.ControlsOpenText, and IG.Forms.TimerControlWorking.IsSwControlsOpened.
Referenced by IG.Forms.TimerControlWorking.StopWatchControl_Load(), and IG.Forms.TimerControlWorking.TimerControlWorking().
UpdateDisplayAppearance()
virtual void IG.Forms.TimerControlWorking.UpdateDisplayAppearance () inline protected virtual
Updates fonts on the timer's displays.
References IG.Forms.TimerControlWorking.CdShowMilliSeconds, IG.Forms.TimerControlWorking.dispCdHours, IG.Forms.TimerControlWorking.dispCdHoursSeparator, IG.Forms.TimerControlWorking.dispCdMilliSec, IG.Forms.TimerControlWorking.dispCdMin, IG.Forms.TimerControlWorking.dispCdMinSeparator, IG.Forms.TimerControlWorking.dispCdSec, IG.Forms.TimerControlWorking.dispCdSecDecimalPoint, IG.Forms.TimerControlWorking.DisplayBg, IG.Forms.TimerControlWorking.DisplayFg, IG.Forms.TimerControlWorking.DisplayFont, IG.Forms.TimerControlWorking.dispSwHours, IG.Forms.TimerControlWorking.dispSwHoursSeparator, IG.Forms.TimerControlWorking.dispSwMilliSec, IG.Forms.TimerControlWorking.dispSwMin, IG.Forms.TimerControlWorking.dispSwMinSeparator, IG.Forms.TimerControlWorking.dispSwSec, IG.Forms.TimerControlWorking.dispSwSecDecimalPoint, IG.Forms.TimerControlWorking.flowSwDisplay, IG.Forms.TimerControlWorking.FontMilli, IG.Forms.TimerControlWorking.fontSelectorCd, IG.Forms.TimerControlWorking.fontSelectorSw, IG.Forms.TimerControlWorking.numSwFontSize, IG.Forms.FontSelectorSimple.SelectedFont, and IG.Forms.TimerControlWorking.SwShowMilliSeconds.
Referenced by IG.Forms.TimerControlWorking.OnCountdownFinished().
UpdateSwButtonsAppearance()
virtual void IG.Forms.TimerControlWorking.UpdateSwButtonsAppearance () inline protected virtual
Updates appearance of the stopwatch buttons.
References IG.Forms.TimerControlWorking.btnSwReset, IG.Forms.TimerControlWorking.btnSwStartStop, IG.Forms.TimerControlWorking.IsStopwatchRunning, IG.Forms.TimerControlWorking.SwResetColor, IG.Forms.TimerControlWorking.SwResetText, IG.Forms.TimerControlWorking.SwStartColor, IG.Forms.TimerControlWorking.SwStartText, IG.Forms.TimerControlWorking.SwStopColor, IG.Forms.TimerControlWorking.SwStopText, and IG.Forms.TimerControlWorking.UpdateSwDisplay().
Referenced by IG.Forms.TimerControlWorking.StopwatchResetIt(), IG.Forms.TimerControlWorking.StopwatchStart(), and IG.Forms.TimerControlWorking.StopwatchStop().
timer1_Tick()
void IG.Forms.TimerControlWorking.timer1_Tick (object sender, EventArgs e) inline private
Timer event handlesr, executed on every tick of thr timer.
Parameters
sender
e
References IG.Forms.TimerControlWorking._cdCurrentRemainingSpan, IG.Forms.TimerControlWorking._cdPreviousRemainingSpan, IG.Forms.TimerControlWorking._swCurrentSpan, IG.Forms.TimerControlWorking._swPreviousSpan, IG.Forms.TimerControlWorking.CdStopwatch, IG.Forms.TimerControlWorking.CountdownRemainingTimeSpan, IG.Forms.TimerControlWorking.IsCountdownRunning, IG.Forms.TimerControlWorking.IsStopwatchRunning, IG.Forms.TimerControlWorking.MaxTimerErrorReports, IG.Forms.TimerControlWorking.NumTimerErrorReports, IG.Forms.TimerControlWorking.OnCountdownFinished(), IG.Forms.TimerControlWorking.OnCountdownHourBell(), IG.Forms.TimerControlWorking.OnCountdownMinuteBell(), IG.Forms.TimerControlWorking.OnCountdownSecondTick(), IG.Forms.TimerControlWorking.OnCountdownTimerTick(), IG.Forms.TimerControlWorking.OnStopwatchHourBell(), IG.Forms.TimerControlWorking.OnStopwatchMinuteBell(), IG.Forms.TimerControlWorking.OnStopwatchSecondTick(), IG.Forms.TimerControlWorking.OnStopwatchTimerTick(), IG.Forms.TimerControlWorking.OutputLevel, IG.Lib.StopWatch1.Stop(), IG.Forms.TimerControlWorking.StopwatchTotalTimeSpan, and IG.Forms.TimerControlWorking.UpdateCdDisplay().
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
StopWatchControl_Load()
void IG.Forms.TimerControlWorking.StopWatchControl_Load (object sender, EventArgs e) inline private
References IG.Forms.TimerControlWorking.UpdateSwControls().
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
btnSwControls_Click()
void IG.Forms.TimerControlWorking.btnSwControls_Click (object sender, EventArgs e) inline private
Toggles opening/closing stopwatch's controls panel.
References IG.Forms.TimerControlWorking.IsSwControlsOpened.
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
chkSwSilent_CheckedChanged()
void IG.Forms.TimerControlWorking.chkSwSilent_CheckedChanged (object sender, EventArgs e) inline private
Toggles silent mode.
References IG.Forms.TimerControlWorking.chkSwSilent, and IG.Forms.TimerControlWorking.IsSilent.
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
btnSwStartStop_Click()
void IG.Forms.TimerControlWorking.btnSwStartStop_Click (object sender, EventArgs e) inline private
Start / stop button pressed.
References IG.Forms.TimerControlWorking.StopwatchStartOrStop().
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
btnSwReset_Click()
void IG.Forms.TimerControlWorking.btnSwReset_Click (object sender, EventArgs e) inline private
References IG.Forms.TimerControlWorking.StopwatchResetIt().
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
flowPanelOuter_SizeChanged()
void IG.Forms.TimerControlWorking.flowPanelOuter_SizeChanged (object sender, EventArgs e) inline private
Fired on size change of the outer panel of the control. Currently not used, but this event can be used fo triger the appropriate actions (e.g. adjust the size) of containing controls. Now containing controls are adjusted automatically (by appropriate property setting).
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
fontSelectorSw_FontSelected()
void IG.Forms.TimerControlWorking.fontSelectorSw_FontSelected (object sender, FontEventArgs args) inline private
Trigered by font selector control when a new font was selected in it.
References IG.Forms.TimerControlWorking.DisplayFont, and IG.Forms.FontEventArgs.Font.
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
fontSelector_Load()
void IG.Forms.TimerControlWorking.fontSelector_Load (object sender, EventArgs e) inline private
Not used.
fontSelector_FontSelected()
void IG.Forms.TimerControlWorking.fontSelector_FontSelected (object sender, FontEventArgs args) inline private
When font is selected by the font selector, it sets the display font in this control to the selected font.
Parameters
sender Control that raised the event.
args Contains the selected font.
References IG.Forms.TimerControlWorking.DisplayFont, and IG.Forms.FontEventArgs.Font.
SetDisplayFontSize() [1/2]
void IG.Forms.TimerControlWorking.SetDisplayFontSize (double sizeInPoints) inline
Changes size of the display font.
Parameters
sizeInPoints New size of the display font, in points.
Referenced by IG.Forms.TimerControlWorking.numCdFontSize_ValueChanged(), and IG.Forms.TimerControlWorking.numFontSize_ValueChanged().
SetDisplayFontSize() [2/2]
void IG.Forms.TimerControlWorking.SetDisplayFontSize (decimal sizeInPointsDecimal) inline
Changes size of the display font.
Parameters
sizeinPointsDecimal New size of the display font, in points.
References IG.Forms.TimerControlWorking.DisplayFont, and IG.Forms.TimerControlWorking.MinDispayFontSizeInPoints.
numFontSize_ValueChanged()
void IG.Forms.TimerControlWorking.numFontSize_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.TimerControlWorking.numSwFontSize, and IG.Forms.TimerControlWorking.SetDisplayFontSize().
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
numSwFontSize_Enter()
void IG.Forms.TimerControlWorking.numSwFontSize_Enter (object sender, EventArgs e) inline private
Selects the contents for easy changing by typing.
References IG.Forms.TimerControlWorking.numSwFontSize.
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
numSwFontSize_Click()
void IG.Forms.TimerControlWorking.numSwFontSize_Click (object sender, EventArgs e) inline private
Selects the contents for easy changing by typing.
References IG.Forms.TimerControlWorking.numSwFontSize.
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
chkSwDisplayMilliseconds_CheckedChanged()
void IG.Forms.TimerControlWorking.chkSwDisplayMilliseconds_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.TimerControlWorking.chkSwDisplayMilliseconds, and IG.Forms.TimerControlWorking.SwShowMilliSeconds.
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
chkSwDisplayHours_CheckedChanged()
void IG.Forms.TimerControlWorking.chkSwDisplayHours_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.TimerControlWorking.chkSwDisplayHours, and IG.Forms.TimerControlWorking.SwShowHoursWhenZero.
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
OnStopwatchTimerTick()
virtual void IG.Forms.TimerControlWorking.OnStopwatchTimerTick () inline protected virtual
Called when the timer event fires (very often, in the range of milliseconds). Raises the StopwatchTimerTick event and updates the display.
Sounds can not be assigned to this event.
References IG.Forms.TimerControlWorking.StopwatchTimerTick, and IG.Forms.TimerControlWorking.UpdateSwDisplay().
Referenced by IG.Forms.TimerControlWorking.timer1_Tick().
StopwatchStartOrStop()
virtual void IG.Forms.TimerControlWorking.StopwatchStartOrStop () inline virtual
Starts (if it is not running) or stops (if it is running) the stopwatch.
References IG.Lib.StopWatch1.IsRunning, IG.Forms.TimerControlWorking.StopwatchStart(), IG.Forms.TimerControlWorking.StopwatchStop(), and IG.Forms.TimerControlWorking.SwStopwatch.
Referenced by IG.Forms.TimerControlWorking.btnSwStartStop_Click().
StopwatchStart()
virtual void IG.Forms.TimerControlWorking.StopwatchStart () inline virtual
Starts the stopwatch.
Its internal stopwatch starts running and the StopwatchStarted event is raised.
Eventually the appropriate sound is played (if not IsSilent and if IsSwSoundButtons
If the stopwatch is already runninng or it has already finished, call to this function has no effect.
References IG.Forms.TimerControlWorking.IsSilent, IG.Forms.TimerControlWorking.IsStopwatchRunning, IG.Forms.TimerControlWorking.IsSwSoundButtons, IG.Forms.TimerControlWorking.PlaySoundStart(), IG.Lib.StopWatch1.Start(), IG.Forms.TimerControlWorking.StopwatchStarted, IG.Forms.TimerControlWorking.SwStopwatch, IG.Forms.TimerControlWorking.timer1, and IG.Forms.TimerControlWorking.UpdateSwButtonsAppearance().
Referenced by IG.Forms.TimerControlWorking.StopwatchStartOrStop().
StopwatchStop()
virtual void IG.Forms.TimerControlWorking.StopwatchStop () inline virtual
Stops the stopwatch timer.
Its internal stopwatch stops running and the StopwatchStopped event is raised.
Eventually the appropriate sound is played (if not IsSilent and if IsSwSoundButtons)
If the stopwatch is paused or it has already finished, call to this function has no effect.
References IG.Forms.TimerControlWorking.IsRunning, IG.Forms.TimerControlWorking.IsSilent, IG.Forms.TimerControlWorking.IsStopwatchRunning, IG.Forms.TimerControlWorking.IsSwSoundButtons, IG.Forms.TimerControlWorking.PlaySoundStop(), IG.Lib.StopWatch1.Stop(), IG.Forms.TimerControlWorking.StopwatchStopped, IG.Forms.TimerControlWorking.SwStopwatch, IG.Forms.TimerControlWorking.timer1, and IG.Forms.TimerControlWorking.UpdateSwButtonsAppearance().
Referenced by IG.Forms.TimerControlWorking.StopwatchStartOrStop().
StopwatchResetIt()
virtual void IG.Forms.TimerControlWorking.StopwatchResetIt () inline protected virtual
Resets the stopwatch.
Its internal stopwatch stops running (if it runs) and the StopwatchReset event is raised.
Eventually the appropriate sound is played (if not IsSilent and if IsSwSoundButtons)
References IG.Lib.StopWatch1.IsRunning, IG.Forms.TimerControlWorking.IsRunning, IG.Lib.StopWatch1.Reset(), IG.Lib.StopWatch1.Stop(), IG.Forms.TimerControlWorking.StopwatchReset, IG.Forms.TimerControlWorking.SwStopwatch, IG.Forms.TimerControlWorking.timer1, IG.Forms.TimerControlWorking.UpdateSwButtonsAppearance(), and IG.Forms.TimerControlWorking.UpdateSwDisplay().
Referenced by IG.Forms.TimerControlWorking.btnSwReset_Click(), and IG.Forms.TimerControlWorking.TimerControlWorking().
OnStopwatchSecondTick()
virtual void IG.Forms.TimerControlWorking.OnStopwatchSecondTick () inline protected virtual
Called when the stopwatch seconds count reaches a whole value (seconds tick). Raises the StopwatchSecondTick event and eventually plays the appropriate "second tick" sound (if not IsSilent and if IsSwSoundSecondTick).
References IG.Forms.TimerControlWorking.IsClockRunning, IG.Forms.TimerControlWorking.IsSilent, IG.Forms.TimerControlWorking.IsSwSoundSecondTick, IG.Forms.TimerControlWorking.PlaySoundSecondTick(), and IG.Forms.TimerControlWorking.StopwatchSecondTick.
Referenced by IG.Forms.TimerControlWorking.timer1_Tick().
OnStopwatchMinuteBell()
virtual void IG.Forms.TimerControlWorking.OnStopwatchMinuteBell () inline protected virtual
Called when the stopwatch minutes count reaches a whole value (minutes signal). Raises the StopwatchMinuteBell event and eventually plays the appropriate "minutes bell" sound (if not IsSilent and if IsSwSoundMinuteBell).
References IG.Forms.TimerControlWorking.IsSilent, IG.Forms.TimerControlWorking.IsSwSoundMinuteBell, IG.Forms.TimerControlWorking.PlaySoundMinuteBell(), and IG.Forms.TimerControlWorking.StopwatchMinuteBell.
Referenced by IG.Forms.TimerControlWorking.timer1_Tick().
OnStopwatchHourBell()
virtual void IG.Forms.TimerControlWorking.OnStopwatchHourBell () inline protected virtual
Called when the stopwatch hours count reaches a whole value (hour switch signal). Raises the StopwatchHourBell event and eventually plays the appropriate "hours bell" sound (if not IsSilent and if IsSwSoundHourBell).
References IG.Forms.TimerControlWorking.IsSilent, IG.Forms.TimerControlWorking.IsSwSoundHourBell, IG.Forms.TimerControlWorking.PlaySoundHourBell(), and IG.Forms.TimerControlWorking.StopwatchHourBell.
Referenced by IG.Forms.TimerControlWorking.timer1_Tick().
UpdateCdInitialTimeSpan()
virtual void IG.Forms.TimerControlWorking.UpdateCdInitialTimeSpan () inline protected virtual
Updates initial TimeSpan of the countdown in such a way that it corresponds to its initial hours, minutes, seconds, and miilliseconds.
References IG.Forms.TimerControlWorking.CdInitialHours, IG.Forms.TimerControlWorking.CdInitialMilliseconds, IG.Forms.TimerControlWorking.CdInitialMinutes, IG.Forms.TimerControlWorking.CdInitialSeconds, and IG.Forms.TimerControlWorking.CdInitialTimeSpan.
UpdateCdInitialTime()
virtual void IG.Forms.TimerControlWorking.UpdateCdInitialTime () inline protected virtual
Updates initial hours, minutes, seconds, and milliseconds of the countdown in such a way that they correspond to its intial TimeSpan.
References IG.Forms.TimerControlWorking.CdInitialHours, IG.Forms.TimerControlWorking.CdInitialMilliseconds, IG.Forms.TimerControlWorking.CdInitialMinutes, IG.Forms.TimerControlWorking.CdInitialSeconds, IG.Forms.TimerControlWorking.CdInitialTimeSpan, and IG.Num.M.floor().
UpdateCdDisplay()
virtual void IG.Forms.TimerControlWorking.UpdateCdDisplay () inline protected virtual
Refreshes countdown's display according to elapsed time.
References IG.Forms.TimerControlWorking.CdShowHoursWhenZero, IG.Forms.TimerControlWorking.CountdownRemainingTimeSpan, IG.Forms.TimerControlWorking.dispCdHours, IG.Forms.TimerControlWorking.dispCdHoursSeparator, IG.Forms.TimerControlWorking.dispCdMilliSec, IG.Forms.TimerControlWorking.dispCdMin, IG.Forms.TimerControlWorking.dispCdMinSeparator, IG.Forms.TimerControlWorking.dispCdSec, IG.Forms.TimerControlWorking.dispCdSecDecimalPoint, and IG.Num.M.floor().
Referenced by IG.Forms.TimerControlWorking.CountdownResetIt(), IG.Forms.TimerControlWorking.OnCountdownTimerTick(), IG.Forms.TimerControlWorking.timer1_Tick(), IG.Forms.TimerControlWorking.UpdateCdButtonsAppearance(), and IG.Forms.TimerControlWorking.UpdateDisplays().
UpdateCdControls()
virtual void IG.Forms.TimerControlWorking.UpdateCdControls () inline protected virtual
Updates countdown controls according to internal properties.
References IG.Forms.TimerControlWorking.boxCdControls, IG.Forms.TimerControlWorking.btnCdControls, IG.Forms.TimerControlWorking.ControlsClosedText, IG.Forms.TimerControlWorking.ControlsFgClosed, IG.Forms.TimerControlWorking.ControlsFgOpen, IG.Forms.TimerControlWorking.ControlsOpenText, and IG.Forms.TimerControlWorking.IsCdControlsOpened.
Referenced by IG.Forms.TimerControlWorking.TimerControlWorking().
UpdateCdButtonsAppearance()
virtual void IG.Forms.TimerControlWorking.UpdateCdButtonsAppearance () inline protected virtual
Updates appearance of the stopwatch buttons.
References IG.Forms.TimerControlWorking.btnCdReset, IG.Forms.TimerControlWorking.btnCdStartStop, IG.Forms.TimerControlWorking.CdResetColor, IG.Forms.TimerControlWorking.CdResetText, IG.Forms.TimerControlWorking.CdStartColor, IG.Forms.TimerControlWorking.CdStartText, IG.Forms.TimerControlWorking.CdStopColor, IG.Forms.TimerControlWorking.CdStopText, IG.Forms.TimerControlWorking.CountdownRemainingTime, IG.Forms.TimerControlWorking.IsCountdownRunning, and IG.Forms.TimerControlWorking.UpdateCdDisplay().
Referenced by IG.Forms.TimerControlWorking.CountdownResetIt(), IG.Forms.TimerControlWorking.CountdownStart(), IG.Forms.TimerControlWorking.CountdownStop(), and IG.Forms.TimerControlWorking.OnCountdownFinished().
UpdateWatchDisplay()
virtual void IG.Forms.TimerControlWorking.UpdateWatchDisplay () inline protected virtual
Refreshes watch' display according to the current time.
Referenced by IG.Forms.TimerControlWorking.UpdateDisplays().
btnCdControls_Click()
void IG.Forms.TimerControlWorking.btnCdControls_Click (object sender, EventArgs e) inline private
Toggles between open / closed control panel for the countdown.
Parameters
sender
e
References IG.Forms.TimerControlWorking.IsCdControlsOpened.
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
chkCdSilent_CheckedChanged()
void IG.Forms.TimerControlWorking.chkCdSilent_CheckedChanged (object sender, EventArgs e) inline private
Toggles silent mode.
References IG.Forms.TimerControlWorking.chkCdSilent, and IG.Forms.TimerControlWorking.IsSilent.
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
fontSelectorCd_FontSelected()
void IG.Forms.TimerControlWorking.fontSelectorCd_FontSelected (object sender, FontEventArgs args) inline private
References IG.Forms.TimerControlWorking.DisplayFont, and IG.Forms.FontEventArgs.Font.
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
btnCdStartStop_Click()
void IG.Forms.TimerControlWorking.btnCdStartStop_Click (object sender, EventArgs e) inline private
References IG.Forms.TimerControlWorking.CountdownStartOrStop().
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
btnCdReset_Click()
void IG.Forms.TimerControlWorking.btnCdReset_Click (object sender, EventArgs e) inline private
References IG.Forms.TimerControlWorking.CountdownResetIt().
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
chkCdDisplayMilliseconds_CheckedChanged()
void IG.Forms.TimerControlWorking.chkCdDisplayMilliseconds_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.TimerControlWorking.CdShowMilliSeconds, and IG.Forms.TimerControlWorking.chkCdDisplayMilliseconds.
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
chkCdDisplayHours_CheckedChanged()
void IG.Forms.TimerControlWorking.chkCdDisplayHours_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.TimerControlWorking.CdShowHoursWhenZero, and IG.Forms.TimerControlWorking.chkCdDisplayHours.
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
numCdFontSize_ValueChanged()
void IG.Forms.TimerControlWorking.numCdFontSize_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.TimerControlWorking.numCdFontSize, and IG.Forms.TimerControlWorking.SetDisplayFontSize().
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
numCdFontSize_Enter()
void IG.Forms.TimerControlWorking.numCdFontSize_Enter (object sender, EventArgs e) inline private
References IG.Forms.TimerControlWorking.numCdFontSize.
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
numCdFontSize_Click()
void IG.Forms.TimerControlWorking.numCdFontSize_Click (object sender, EventArgs e) inline private
References IG.Forms.TimerControlWorking.numCdFontSize.
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
OnCountdownTimerTick()
virtual void IG.Forms.TimerControlWorking.OnCountdownTimerTick () inline protected virtual
Called when the timer event fires (very often, in the range of milliseconds). Raises the CountdownTimerTick event and updates the display.
Sounds can not be assigned to this event.
References IG.Forms.TimerControlWorking.CountdownTimerTick, and IG.Forms.TimerControlWorking.UpdateCdDisplay().
Referenced by IG.Forms.TimerControlWorking.timer1_Tick().
CountdownStartOrStop()
virtual void IG.Forms.TimerControlWorking.CountdownStartOrStop () inline virtual
Starts (if it is not running) or stops (if it is running) the countdown.
References IG.Forms.TimerControlWorking.CdStopwatch, IG.Forms.TimerControlWorking.CountdownStart(), IG.Forms.TimerControlWorking.CountdownStop(), and IG.Lib.StopWatch1.IsRunning.
Referenced by IG.Forms.TimerControlWorking.btnCdStartStop_Click().
CountdownStart()
virtual void IG.Forms.TimerControlWorking.CountdownStart () inline virtual
Starts the countdown timer.
Its internal stopwatch starts running and the CountdownStarted event is raised.
Eventually the appropriate sound is played (if not IsSilent and if IsCdSoundButtons
If the countdown is already runninng or it has already finished, call to this function has no effect.
References IG.Forms.TimerControlWorking.CdStopwatch, IG.Forms.TimerControlWorking.CountdownRemainingTime, IG.Forms.TimerControlWorking.CountdownStarted, IG.Forms.TimerControlWorking.IsCdSoundButtons, IG.Forms.TimerControlWorking.IsCountdownRunning, IG.Forms.TimerControlWorking.IsSilent, IG.Forms.TimerControlWorking.PlaySoundStart(), IG.Lib.StopWatch1.Start(), IG.Forms.TimerControlWorking.timer1, and IG.Forms.TimerControlWorking.UpdateCdButtonsAppearance().
Referenced by IG.Forms.TimerControlWorking.CountdownStartOrStop().
CountdownStop()
virtual void IG.Forms.TimerControlWorking.CountdownStop () inline virtual
Stops the countdown timer.
Its internal stopwatch stops running and the CountdownStopped event is raised.
Eventually the appropriate sound is played (if not IsSilent and if IsCdSoundButtons)
If the countdown is paused or it has already finished, call to this function has no effect.
References IG.Forms.TimerControlWorking.CdStopwatch, IG.Forms.TimerControlWorking.CountdownRemainingTime, IG.Forms.TimerControlWorking.CountdownStopped, IG.Forms.TimerControlWorking.IsCdSoundButtons, IG.Forms.TimerControlWorking.IsCountdownRunning, IG.Forms.TimerControlWorking.IsRunning, IG.Forms.TimerControlWorking.IsSilent, IG.Forms.TimerControlWorking.PlaySoundStop(), IG.Lib.StopWatch1.Stop(), IG.Forms.TimerControlWorking.timer1, and IG.Forms.TimerControlWorking.UpdateCdButtonsAppearance().
Referenced by IG.Forms.TimerControlWorking.CountdownStartOrStop().
CountdownResetIt()
virtual void IG.Forms.TimerControlWorking.CountdownResetIt () inline protected virtual
Resets the countdown.
Its internal stopwatch stops running (if it runs) and the CountdownReset event is raised.
Eventually the appropriate sound is played (if not IsSilent and if IsCdSoundButtons)
References IG.Forms.TimerControlWorking.CdStopwatch, IG.Forms.TimerControlWorking.CountdownReset, IG.Lib.StopWatch1.IsRunning, IG.Forms.TimerControlWorking.IsRunning, IG.Lib.StopWatch1.Reset(), IG.Lib.StopWatch1.Stop(), IG.Forms.TimerControlWorking.timer1, IG.Forms.TimerControlWorking.UpdateCdButtonsAppearance(), and IG.Forms.TimerControlWorking.UpdateCdDisplay().
Referenced by IG.Forms.TimerControlWorking.btnCdReset_Click(), and IG.Forms.TimerControlWorking.TimerControlWorking().
OnCountdownFinished()
virtual void IG.Forms.TimerControlWorking.OnCountdownFinished () inline protected virtual
Called when the countdown reaches 0 and stops counting down. Raises the CountdownFinished event and eventually plays the appropriate alarm (if not IsSilent and if IsCdSoundAlarm).
References IG.Forms.TimerControlWorking.CountdownFinished, IG.Forms.TimerControlWorking.IsCdSoundAlarm, IG.Forms.TimerControlWorking.IsSilent, IG.Forms.TimerControlWorking.PlaySoundAlarmCountdown(), IG.Forms.TimerControlWorking.UpdateCdButtonsAppearance(), and IG.Forms.TimerControlWorking.UpdateDisplayAppearance().
Referenced by IG.Forms.TimerControlWorking.timer1_Tick().
OnCountdownSecondTick()
virtual void IG.Forms.TimerControlWorking.OnCountdownSecondTick () inline protected virtual
Called when the countdown seconds count reaches a whole value (seconds tick). Raises the CountdownSecondTick event and eventually plays the appropriate "second tick" sound (if not IsSilent and if IsCdSoundSecondTick).
References IG.Forms.TimerControlWorking.CountdownSecondTick, IG.Forms.TimerControlWorking.IsCdSoundSecondTick, IG.Forms.TimerControlWorking.IsClockRunning, IG.Forms.TimerControlWorking.IsSilent, IG.Forms.TimerControlWorking.IsStopwatchRunning, and IG.Forms.TimerControlWorking.PlaySoundSecondTick().
Referenced by IG.Forms.TimerControlWorking.timer1_Tick().
OnCountdownMinuteBell()
virtual void IG.Forms.TimerControlWorking.OnCountdownMinuteBell () inline protected virtual
Called when the countdown minutes count reaches a whole value (minutes signal). Raises the CountdownMinuteBell event and eventually plays the appropriate "minutes bell" sound (if not IsSilent and if IsCdSoundMinuteBell).
References IG.Forms.TimerControlWorking.CountdownMinuteBell, IG.Forms.TimerControlWorking.IsCdSoundMinuteBell, IG.Forms.TimerControlWorking.IsSilent, and IG.Forms.TimerControlWorking.PlaySoundMinuteBell().
Referenced by IG.Forms.TimerControlWorking.timer1_Tick().
OnCountdownHourBell()
virtual void IG.Forms.TimerControlWorking.OnCountdownHourBell () inline protected virtual
Called when the countdown hours count reaches a whole value (hours signal). Raises the CountdownHourBell event and eventually plays the appropriate "hours bell" sound (if not IsSilent and if IsCdSoundHourBell).
References IG.Forms.TimerControlWorking.CountdownHourBell, IG.Forms.TimerControlWorking.IsCdSoundHourBell, IG.Forms.TimerControlWorking.IsSilent, and IG.Forms.TimerControlWorking.PlaySoundHourBell().
Referenced by IG.Forms.TimerControlWorking.timer1_Tick().
Dispose()
override void IG.Forms.TimerControlWorking.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.TimerControlWorking.components.
InitializeComponent()
void IG.Forms.TimerControlWorking.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.TimerControlWorking.boxCdControls, IG.Forms.TimerControlWorking.boxSwControls, IG.Forms.TimerControlWorking.btnCdControls, IG.Forms.TimerControlWorking.btnCdControls_Click(), IG.Forms.TimerControlWorking.btnCdReset, IG.Forms.TimerControlWorking.btnCdReset_Click(), IG.Forms.TimerControlWorking.btnCdStartStop, IG.Forms.TimerControlWorking.btnCdStartStop_Click(), IG.Forms.TimerControlWorking.btnSwControls, IG.Forms.TimerControlWorking.btnSwControls_Click(), IG.Forms.TimerControlWorking.btnSwReset, IG.Forms.TimerControlWorking.btnSwReset_Click(), IG.Forms.TimerControlWorking.btnSwStartStop, IG.Forms.TimerControlWorking.btnSwStartStop_Click(), IG.Forms.TimerControlWorking.chkCdDisplayHours, IG.Forms.TimerControlWorking.chkCdDisplayHours_CheckedChanged(), IG.Forms.TimerControlWorking.chkCdDisplayMilliseconds, IG.Forms.TimerControlWorking.chkCdDisplayMilliseconds_CheckedChanged(), IG.Forms.TimerControlWorking.chkCdSilent, IG.Forms.TimerControlWorking.chkCdSilent_CheckedChanged(), IG.Forms.TimerControlWorking.chkSwDisplayHours, IG.Forms.TimerControlWorking.chkSwDisplayHours_CheckedChanged(), IG.Forms.TimerControlWorking.chkSwDisplayMilliseconds, IG.Forms.TimerControlWorking.chkSwDisplayMilliseconds_CheckedChanged(), IG.Forms.TimerControlWorking.chkSwSilent, IG.Forms.TimerControlWorking.chkSwSilent_CheckedChanged(), IG.Forms.TimerControlWorking.components, IG.Forms.TimerControlWorking.dispCdHours, IG.Forms.TimerControlWorking.dispCdHoursSeparator, IG.Forms.TimerControlWorking.dispCdMilliSec, IG.Forms.TimerControlWorking.dispCdMin, IG.Forms.TimerControlWorking.dispCdMinSeparator, IG.Forms.TimerControlWorking.dispCdSec, IG.Forms.TimerControlWorking.dispCdSecDecimalPoint, IG.Forms.TimerControlWorking.dispSwHours, IG.Forms.TimerControlWorking.dispSwHoursSeparator, IG.Forms.TimerControlWorking.dispSwMilliSec, IG.Forms.TimerControlWorking.dispSwMin, IG.Forms.TimerControlWorking.dispSwMinSeparator, IG.Forms.TimerControlWorking.dispSwSec, IG.Forms.TimerControlWorking.dispSwSecDecimalPoint, IG.Forms.TimerControlWorking.flowCdButtons, IG.Forms.TimerControlWorking.flowCdButtonsLeft, IG.Forms.TimerControlWorking.flowCdButtonsRight, IG.Forms.TimerControlWorking.flowCdOuter, IG.Forms.TimerControlWorking.flowLayoutPanel3, IG.Forms.TimerControlWorking.flowLayoutPanel4, IG.Forms.TimerControlWorking.flowLayoutPanel5, IG.Forms.TimerControlWorking.flowOuter, IG.Forms.TimerControlWorking.flowPanelOuter_SizeChanged(), IG.Forms.TimerControlWorking.flowSwButtons, IG.Forms.TimerControlWorking.flowSwButtonsRight, IG.Forms.TimerControlWorking.flowSwButtosLeft, IG.Forms.TimerControlWorking.flowSwControlsBasic, IG.Forms.TimerControlWorking.flowSwDisplay, IG.Forms.TimerControlWorking.flowSwDisplayBottom, IG.Forms.TimerControlWorking.flowSwDisplayTop, IG.Forms.TimerControlWorking.flowSwOuter, IG.Forms.TimerControlWorking.flowTwControlsBasic, IG.Forms.FontSelectorSimple.FontSelected, IG.Forms.TimerControlWorking.fontSelectorCd, IG.Forms.TimerControlWorking.fontSelectorCd_FontSelected(), IG.Forms.TimerControlWorking.fontSelectorSw, IG.Forms.TimerControlWorking.fontSelectorSw_FontSelected(), IG.Forms.FontSelectorSimple.InitialFontLabelText, IG.Forms.TimerControlWorking.lblCdTitle, IG.Forms.TimerControlWorking.lblHelpOuterFlow, IG.Forms.TimerControlWorking.lblSwTitle, IG.Forms.TimerControlWorking.lbSwlFontSize, IG.Forms.TimerControlWorking.lbTwlFontSize, IG.Forms.TimerControlWorking.numCdFontSize, IG.Forms.TimerControlWorking.numCdFontSize_Click(), IG.Forms.TimerControlWorking.numCdFontSize_Enter(), IG.Forms.TimerControlWorking.numCdFontSize_ValueChanged(), IG.Forms.TimerControlWorking.numFontSize_ValueChanged(), IG.Forms.TimerControlWorking.numSwFontSize, IG.Forms.TimerControlWorking.numSwFontSize_Click(), IG.Forms.TimerControlWorking.numSwFontSize_Enter(), IG.Forms.FontSelectorSimple.SelectedFont, IG.Forms.TimerControlWorking.StopWatchControl_Load(), IG.Forms.TimerControlWorking.timer1, and IG.Forms.TimerControlWorking.timer1_Tick().
Referenced by IG.Forms.TimerControlWorking.TimerControlWorking().
Member Data Documentation
_defaultOutputLevel
int IG.Forms.TimerControlWorking._defaultOutputLevel = 0 static private
_outputLevel
int IG.Forms.TimerControlWorking._outputLevel = DefaultOutputLevel private
_maxPlayErrors
int IG.Forms.TimerControlWorking._maxPlayErrors = 5 private
_soundPlayerStart
SoundPlayer IG.Forms.TimerControlWorking._soundPlayerStart = null protected
_soundPlayerStop
SoundPlayer IG.Forms.TimerControlWorking._soundPlayerStop = null protected
_soundPlayerReset
SoundPlayer IG.Forms.TimerControlWorking._soundPlayerReset = null protected
_soundPlayerSecondTick
SoundPlayer IG.Forms.TimerControlWorking._soundPlayerSecondTick = null protected
_soundPlayerMinuteBell
SoundPlayer IG.Forms.TimerControlWorking._soundPlayerMinuteBell = null protected
_soundPlayerHourBell
SoundPlayer IG.Forms.TimerControlWorking._soundPlayerHourBell = null protected
_soundPlayerAlarmCountdown
SoundPlayer IG.Forms.TimerControlWorking._soundPlayerAlarmCountdown = null protected
_isSwSoundSecondTick
bool IG.Forms.TimerControlWorking._isSwSoundSecondTick = true private
_isSwSoundMinuteBell
bool IG.Forms.TimerControlWorking._isSwSoundMinuteBell = true private
_isSwSoundHourBell
bool IG.Forms.TimerControlWorking._isSwSoundHourBell = true private
_isSwSoundButtonPressed
bool IG.Forms.TimerControlWorking._isSwSoundButtonPressed = true private
_isCdSoundSecondTick
bool IG.Forms.TimerControlWorking._isCdSoundSecondTick = true private
_isCdSoundMinuteBell
bool IG.Forms.TimerControlWorking._isCdSoundMinuteBell = true private
_isCdSoundHourBell
bool IG.Forms.TimerControlWorking._isCdSoundHourBell = true private
_timerIntervalMs
int IG.Forms.TimerControlWorking._timerIntervalMs = 5 private
_isSilent
bool IG.Forms.TimerControlWorking._isSilent = true private
_swStopwatch
StopWatch1 IG.Forms.TimerControlWorking._swStopwatch private
_fontMilli
Font IG.Forms.TimerControlWorking._fontMilli = null private
_displayFont
Font IG.Forms.TimerControlWorking._displayFont = null protected
_millisecondsSizeRatio
double IG.Forms.TimerControlWorking._millisecondsSizeRatio = 0.5 private
_minDispayFontSizeInPoints
double IG.Forms.TimerControlWorking._minDispayFontSizeInPoints = 2.0 private
_swShowMilliSeconds
bool IG.Forms.TimerControlWorking._swShowMilliSeconds = true private
_swShowHoursWhenZero
bool IG.Forms.TimerControlWorking._swShowHoursWhenZero = true private
Whether hours shoulld be shown when they are zero.
_colorBgWarning
Color IG.Forms.TimerControlWorking._colorBgWarning = Color.Red private
_colorBgOk
Color IG.Forms.TimerControlWorking._colorBgOk = Color.Green private
_displayBg
Color IG.Forms.TimerControlWorking._displayBg = Color.PaleGoldenrod private
_displayFg
Color IG.Forms.TimerControlWorking._displayFg = Color.SeaGreen private
_swStartText
string IG.Forms.TimerControlWorking._swStartText = "Start" private
_swStopText
string IG.Forms.TimerControlWorking._swStopText = "Pause" private
_swResetText
string IG.Forms.TimerControlWorking._swResetText = "Reset" private
_swStartColor
Color IG.Forms.TimerControlWorking._swStartColor = Color.Green private
_swStopColor
Color IG.Forms.TimerControlWorking._swStopColor = Color.LightSalmon private
Background color for stopwatch stop button.
_swResetColor
Color IG.Forms.TimerControlWorking._swResetColor = Color.LightSalmon private
_controlsFgClosed
Color IG.Forms.TimerControlWorking._controlsFgClosed = Color.Black private
_controlsFgOpen
Color IG.Forms.TimerControlWorking._controlsFgOpen = Color.Blue private
_controlsClosedText
string IG.Forms.TimerControlWorking._controlsClosedText = "" private
_ontrolsOpenText
string IG.Forms.TimerControlWorking._ontrolsOpenText = "" private
_swControlsOpen
bool IG.Forms.TimerControlWorking._swControlsOpen = false private
_swPreviousSpan
TimeSpan IG.Forms.TimerControlWorking._swPreviousSpan protected
Referenced by IG.Forms.TimerControlWorking.timer1_Tick().
_swCurrentSpan
TimeSpan IG.Forms.TimerControlWorking._swCurrentSpan protected
Referenced by IG.Forms.TimerControlWorking.timer1_Tick().
_cdPreviousRemainingSpan
TimeSpan IG.Forms.TimerControlWorking._cdPreviousRemainingSpan protected
Referenced by IG.Forms.TimerControlWorking.timer1_Tick().
_cdCurrentRemainingSpan
TimeSpan IG.Forms.TimerControlWorking._cdCurrentRemainingSpan protected
Referenced by IG.Forms.TimerControlWorking.timer1_Tick().
DefaultMaxNumTimerErrorReports
int IG.Forms.TimerControlWorking.DefaultMaxNumTimerErrorReports = 10 static
Default maximal number of times a report about timer tick exception is launched.
_maxTimerErrorReports
int IG.Forms.TimerControlWorking._maxTimerErrorReports = DefaultMaxNumTimerErrorReports private
_numTimerErrorReports
int IG.Forms.TimerControlWorking._numTimerErrorReports = 0 private
_cdStopwatch
StopWatch1 IG.Forms.TimerControlWorking._cdStopwatch private
_cdInitialHours
int IG.Forms.TimerControlWorking._cdInitialHours = 0 private
_cdInitialMinutes
int IG.Forms.TimerControlWorking._cdInitialMinutes = 0 private
_cdInitialSecods
int IG.Forms.TimerControlWorking._cdInitialSecods = 0 private
_cdInitialMs
int IG.Forms.TimerControlWorking._cdInitialMs = 0 private
_cdInitialTimeSpan
TimeSpan IG.Forms.TimerControlWorking._cdInitialTimeSpan = new TimeSpan(0, 0, 10, 0) private
_cdShowMilliSeconds
bool IG.Forms.TimerControlWorking._cdShowMilliSeconds = true private
_cdShowHoursWhenZero
bool IG.Forms.TimerControlWorking._cdShowHoursWhenZero = true private
Whether hours shoulld be shown on countdown when they are zero.
_isCdSoundButtonPressed
bool IG.Forms.TimerControlWorking._isCdSoundButtonPressed = true private
_isCdSoundAlarm
bool IG.Forms.TimerControlWorking._isCdSoundAlarm = true private
_cdStartText
string IG.Forms.TimerControlWorking._cdStartText = "Start" private
_cdStopText
string IG.Forms.TimerControlWorking._cdStopText = "Pause" private
_cdResetText
string IG.Forms.TimerControlWorking._cdResetText = "Reset" private
_cdStartColor
Color IG.Forms.TimerControlWorking._cdStartColor = Color.Green private
_cdStopColor
Color IG.Forms.TimerControlWorking._cdStopColor = Color.LightSalmon private
Background color for stopwatch stop button.
_cdResetColor
Color IG.Forms.TimerControlWorking._cdResetColor = Color.LightSalmon private
Background color for countdown reset button.
_cdControlsOpen
bool IG.Forms.TimerControlWorking._cdControlsOpen = false private
_isClockRunnng
bool IG.Forms.TimerControlWorking._isClockRunnng = false protected
components
System.ComponentModel.IContainer IG.Forms.TimerControlWorking.components = null private
Required designer variable.
Referenced by IG.Forms.TimerControlWorking.Dispose(), and IG.Forms.TimerControlWorking.InitializeComponent().
flowSwOuter
System.Windows.Forms.FlowLayoutPanel IG.Forms.TimerControlWorking.flowSwOuter private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
flowSwDisplay
System.Windows.Forms.FlowLayoutPanel IG.Forms.TimerControlWorking.flowSwDisplay private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), and IG.Forms.TimerControlWorking.UpdateDisplayAppearance().
dispSwHours
System.Windows.Forms.Label IG.Forms.TimerControlWorking.dispSwHours private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.TimerControlWorking.UpdateDisplayAppearance(), and IG.Forms.TimerControlWorking.UpdateSwDisplay().
dispSwHoursSeparator
System.Windows.Forms.Label IG.Forms.TimerControlWorking.dispSwHoursSeparator private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.TimerControlWorking.UpdateDisplayAppearance(), and IG.Forms.TimerControlWorking.UpdateSwDisplay().
dispSwMin
System.Windows.Forms.Label IG.Forms.TimerControlWorking.dispSwMin private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.TimerControlWorking.UpdateDisplayAppearance(), and IG.Forms.TimerControlWorking.UpdateSwDisplay().
dispSwMinSeparator
System.Windows.Forms.Label IG.Forms.TimerControlWorking.dispSwMinSeparator private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.TimerControlWorking.UpdateDisplayAppearance(), and IG.Forms.TimerControlWorking.UpdateSwDisplay().
dispSwSec
System.Windows.Forms.Label IG.Forms.TimerControlWorking.dispSwSec private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.TimerControlWorking.TimerControlWorking(), IG.Forms.TimerControlWorking.UpdateDisplayAppearance(), and IG.Forms.TimerControlWorking.UpdateSwDisplay().
btnSwStartStop
System.Windows.Forms.Button IG.Forms.TimerControlWorking.btnSwStartStop private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), and IG.Forms.TimerControlWorking.UpdateSwButtonsAppearance().
btnSwReset
System.Windows.Forms.Button IG.Forms.TimerControlWorking.btnSwReset private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), and IG.Forms.TimerControlWorking.UpdateSwButtonsAppearance().
timer1
System.Windows.Forms.Timer IG.Forms.TimerControlWorking.timer1 private
Referenced by IG.Forms.TimerControlWorking.CountdownResetIt(), IG.Forms.TimerControlWorking.CountdownStart(), IG.Forms.TimerControlWorking.CountdownStop(), IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.TimerControlWorking.StopwatchResetIt(), IG.Forms.TimerControlWorking.StopwatchStart(), and IG.Forms.TimerControlWorking.StopwatchStop().
btnSwControls
System.Windows.Forms.Button IG.Forms.TimerControlWorking.btnSwControls private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), and IG.Forms.TimerControlWorking.UpdateSwControls().
boxSwControls
System.Windows.Forms.GroupBox IG.Forms.TimerControlWorking.boxSwControls private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), and IG.Forms.TimerControlWorking.UpdateSwControls().
lbSwlFontSize
System.Windows.Forms.Label IG.Forms.TimerControlWorking.lbSwlFontSize private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
numSwFontSize
System.Windows.Forms.NumericUpDown IG.Forms.TimerControlWorking.numSwFontSize private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.TimerControlWorking.numFontSize_ValueChanged(), IG.Forms.TimerControlWorking.numSwFontSize_Click(), IG.Forms.TimerControlWorking.numSwFontSize_Enter(), and IG.Forms.TimerControlWorking.UpdateDisplayAppearance().
flowSwDisplayTop
System.Windows.Forms.FlowLayoutPanel IG.Forms.TimerControlWorking.flowSwDisplayTop private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
flowSwDisplayBottom
System.Windows.Forms.FlowLayoutPanel IG.Forms.TimerControlWorking.flowSwDisplayBottom private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
dispSwSecDecimalPoint
System.Windows.Forms.Label IG.Forms.TimerControlWorking.dispSwSecDecimalPoint private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.TimerControlWorking.UpdateDisplayAppearance(), and IG.Forms.TimerControlWorking.UpdateSwDisplay().
dispSwMilliSec
System.Windows.Forms.Label IG.Forms.TimerControlWorking.dispSwMilliSec private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.TimerControlWorking.UpdateDisplayAppearance(), and IG.Forms.TimerControlWorking.UpdateSwDisplay().
flowSwButtosLeft
System.Windows.Forms.FlowLayoutPanel IG.Forms.TimerControlWorking.flowSwButtosLeft private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
flowSwButtonsRight
System.Windows.Forms.FlowLayoutPanel IG.Forms.TimerControlWorking.flowSwButtonsRight private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
flowSwButtons
System.Windows.Forms.FlowLayoutPanel IG.Forms.TimerControlWorking.flowSwButtons private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
flowSwControlsBasic
System.Windows.Forms.FlowLayoutPanel IG.Forms.TimerControlWorking.flowSwControlsBasic private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
lblSwTitle
System.Windows.Forms.Label IG.Forms.TimerControlWorking.lblSwTitle private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
flowCdOuter
System.Windows.Forms.FlowLayoutPanel IG.Forms.TimerControlWorking.flowCdOuter private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
lblCdTitle
System.Windows.Forms.Label IG.Forms.TimerControlWorking.lblCdTitle private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
flowLayoutPanel3
System.Windows.Forms.FlowLayoutPanel IG.Forms.TimerControlWorking.flowLayoutPanel3 private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
flowLayoutPanel4
System.Windows.Forms.FlowLayoutPanel IG.Forms.TimerControlWorking.flowLayoutPanel4 private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
dispCdHours
System.Windows.Forms.Label IG.Forms.TimerControlWorking.dispCdHours private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.TimerControlWorking.UpdateCdDisplay(), and IG.Forms.TimerControlWorking.UpdateDisplayAppearance().
dispCdHoursSeparator
System.Windows.Forms.Label IG.Forms.TimerControlWorking.dispCdHoursSeparator private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.TimerControlWorking.UpdateCdDisplay(), and IG.Forms.TimerControlWorking.UpdateDisplayAppearance().
dispCdMin
System.Windows.Forms.Label IG.Forms.TimerControlWorking.dispCdMin private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.TimerControlWorking.UpdateCdDisplay(), and IG.Forms.TimerControlWorking.UpdateDisplayAppearance().
dispCdMinSeparator
System.Windows.Forms.Label IG.Forms.TimerControlWorking.dispCdMinSeparator private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.TimerControlWorking.UpdateCdDisplay(), and IG.Forms.TimerControlWorking.UpdateDisplayAppearance().
dispCdSec
System.Windows.Forms.Label IG.Forms.TimerControlWorking.dispCdSec private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.TimerControlWorking.UpdateCdDisplay(), and IG.Forms.TimerControlWorking.UpdateDisplayAppearance().
flowLayoutPanel5
System.Windows.Forms.FlowLayoutPanel IG.Forms.TimerControlWorking.flowLayoutPanel5 private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
dispCdSecDecimalPoint
System.Windows.Forms.Label IG.Forms.TimerControlWorking.dispCdSecDecimalPoint private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.TimerControlWorking.UpdateCdDisplay(), and IG.Forms.TimerControlWorking.UpdateDisplayAppearance().
dispCdMilliSec
System.Windows.Forms.Label IG.Forms.TimerControlWorking.dispCdMilliSec private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.TimerControlWorking.UpdateCdDisplay(), and IG.Forms.TimerControlWorking.UpdateDisplayAppearance().
flowCdButtons
System.Windows.Forms.FlowLayoutPanel IG.Forms.TimerControlWorking.flowCdButtons private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
flowCdButtonsLeft
System.Windows.Forms.FlowLayoutPanel IG.Forms.TimerControlWorking.flowCdButtonsLeft private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
btnCdStartStop
System.Windows.Forms.Button IG.Forms.TimerControlWorking.btnCdStartStop private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), and IG.Forms.TimerControlWorking.UpdateCdButtonsAppearance().
flowCdButtonsRight
System.Windows.Forms.FlowLayoutPanel IG.Forms.TimerControlWorking.flowCdButtonsRight private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
btnCdReset
System.Windows.Forms.Button IG.Forms.TimerControlWorking.btnCdReset private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), and IG.Forms.TimerControlWorking.UpdateCdButtonsAppearance().
flowTwControlsBasic
System.Windows.Forms.FlowLayoutPanel IG.Forms.TimerControlWorking.flowTwControlsBasic private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
lbTwlFontSize
System.Windows.Forms.Label IG.Forms.TimerControlWorking.lbTwlFontSize private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
numCdFontSize
System.Windows.Forms.NumericUpDown IG.Forms.TimerControlWorking.numCdFontSize private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.TimerControlWorking.numCdFontSize_Click(), IG.Forms.TimerControlWorking.numCdFontSize_Enter(), and IG.Forms.TimerControlWorking.numCdFontSize_ValueChanged().
btnCdControls
System.Windows.Forms.Button IG.Forms.TimerControlWorking.btnCdControls private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), and IG.Forms.TimerControlWorking.UpdateCdControls().
boxCdControls
System.Windows.Forms.GroupBox IG.Forms.TimerControlWorking.boxCdControls private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), and IG.Forms.TimerControlWorking.UpdateCdControls().
fontSelectorSw
FontSelectorSimple IG.Forms.TimerControlWorking.fontSelectorSw private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), and IG.Forms.TimerControlWorking.UpdateDisplayAppearance().
chkSwDisplayHours
System.Windows.Forms.CheckBox IG.Forms.TimerControlWorking.chkSwDisplayHours private
Referenced by IG.Forms.TimerControlWorking.chkSwDisplayHours_CheckedChanged(), IG.Forms.TimerControlWorking.InitializeComponent(), and IG.Forms.TimerControlWorking.TimerControlWorking().
chkSwDisplayMilliseconds
System.Windows.Forms.CheckBox IG.Forms.TimerControlWorking.chkSwDisplayMilliseconds private
Referenced by IG.Forms.TimerControlWorking.chkSwDisplayMilliseconds_CheckedChanged(), IG.Forms.TimerControlWorking.InitializeComponent(), and IG.Forms.TimerControlWorking.TimerControlWorking().
chkCdDisplayMilliseconds
System.Windows.Forms.CheckBox IG.Forms.TimerControlWorking.chkCdDisplayMilliseconds private
Referenced by IG.Forms.TimerControlWorking.chkCdDisplayMilliseconds_CheckedChanged(), IG.Forms.TimerControlWorking.InitializeComponent(), and IG.Forms.TimerControlWorking.TimerControlWorking().
chkCdDisplayHours
System.Windows.Forms.CheckBox IG.Forms.TimerControlWorking.chkCdDisplayHours private
Referenced by IG.Forms.TimerControlWorking.chkCdDisplayHours_CheckedChanged(), IG.Forms.TimerControlWorking.InitializeComponent(), and IG.Forms.TimerControlWorking.TimerControlWorking().
fontSelectorCd
FontSelectorSimple IG.Forms.TimerControlWorking.fontSelectorCd private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), and IG.Forms.TimerControlWorking.UpdateDisplayAppearance().
flowOuter
System.Windows.Forms.FlowLayoutPanel IG.Forms.TimerControlWorking.flowOuter private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
lblHelpOuterFlow
System.Windows.Forms.Label IG.Forms.TimerControlWorking.lblHelpOuterFlow private
Referenced by IG.Forms.TimerControlWorking.InitializeComponent().
chkCdSilent
System.Windows.Forms.CheckBox IG.Forms.TimerControlWorking.chkCdSilent private
Referenced by IG.Forms.TimerControlWorking.chkCdSilent_CheckedChanged(), and IG.Forms.TimerControlWorking.InitializeComponent().
chkSwSilent
System.Windows.Forms.CheckBox IG.Forms.TimerControlWorking.chkSwSilent private
Referenced by IG.Forms.TimerControlWorking.chkSwSilent_CheckedChanged(), and IG.Forms.TimerControlWorking.InitializeComponent().
Property Documentation
DefaultOutputLevel
int IG.Forms.TimerControlWorking.DefaultOutputLevel static get set
Default output level for this class of objects.
OutputLevel
int IG.Forms.TimerControlWorking.OutputLevel get set private
Current output level for the current object.
Latger the value more console output is generated.
Referenced by IG.Forms.TimerControlWorking.timer1_Tick().
MaxPlayErrors
int IG.Forms.TimerControlWorking.MaxPlayErrors get set protected
Referenced by IG.Forms.TimerControlWorking.ReportSoundError().
NumPlayErrors
int IG.Forms.TimerControlWorking.NumPlayErrors get set protected
Referenced by IG.Forms.TimerControlWorking.ReportSoundError().
SoundPlayerStart
virtual SoundPlayer IG.Forms.TimerControlWorking.SoundPlayerStart get
Gets the sound player for playing sound when a start button is pressed. Player is pre-laded with the appropriate sound.
Referenced by IG.Forms.TimerControlWorking.LoadDefaultSounds(), and IG.Forms.TimerControlWorking.PlaySoundStart().
SoundPlayerStop
virtual SoundPlayer IG.Forms.TimerControlWorking.SoundPlayerStop get
Gets the sound player for playing sound when the stop button is pressed. Player is pre-laded with the appropriate sound.
Referenced by IG.Forms.TimerControlWorking.PlaySoundStop().
SoundPlayerReset
virtual SoundPlayer IG.Forms.TimerControlWorking.SoundPlayerReset get
Gets the sound player for playing sound when the resett button is pressed. Player is pre-laded with the appropriate sound.
Referenced by IG.Forms.TimerControlWorking.PlaySoundReset().
SoundPlayerSecondTick
virtual SoundPlayer IG.Forms.TimerControlWorking.SoundPlayerSecondTick get
Gets the sound player for playing sound when another second passes (a second tick). Player is pre-laded with the appropriate sound.
Referenced by IG.Forms.TimerControlWorking.PlaySoundSecondTick().
SoundPlayerMinuteBell
virtual SoundPlayer IG.Forms.TimerControlWorking.SoundPlayerMinuteBell get
Gets the sound player for playing sound when another minute passes (a minute bell). Player is pre-laded with the appropriate sound.
Referenced by IG.Forms.TimerControlWorking.PlaySoundHourBell(), and IG.Forms.TimerControlWorking.PlaySoundMinuteBell().
SoundPlayerHourBell
virtual SoundPlayer IG.Forms.TimerControlWorking.SoundPlayerHourBell get
Gets the sound player for playing sound when another hour passes (a hour bell). Player is pre-laded with the appropriate sound.
SoundPlayerAlarmCountdown
virtual SoundPlayer IG.Forms.TimerControlWorking.SoundPlayerAlarmCountdown get
Gets the sound player for playing alarm when countdown finishes. Player is pre-laded with the appropriate sound.
Referenced by IG.Forms.TimerControlWorking.PlaySoundAlarmCountdown().
IsSwSoundSecondTick
virtual bool IG.Forms.TimerControlWorking.IsSwSoundSecondTick get set
Whether a tick sound is switched on (launched every second when the stopwatch is running).
Referenced by IG.Forms.TimerControlWorking.OnStopwatchSecondTick().
IsSwSoundMinuteBell
virtual bool IG.Forms.TimerControlWorking.IsSwSoundMinuteBell get set
Whether a minutes bell sound is switched on (launched every minute when the stopwatch is running).
Referenced by IG.Forms.TimerControlWorking.OnStopwatchMinuteBell().
IsSwSoundHourBell
virtual bool IG.Forms.TimerControlWorking.IsSwSoundHourBell get set
Whether a hour bell sound is switched on (launched every hour when the stopwatch is running).
Referenced by IG.Forms.TimerControlWorking.OnStopwatchHourBell().
IsSwSoundButtons
virtual bool IG.Forms.TimerControlWorking.IsSwSoundButtons get set
Whether the stopwatch's button sound is switched on (launched every time a stopwatch button with some effect is pressed, or the same effect is achieved programatically).
Referenced by IG.Forms.TimerControlWorking.StopwatchStart(), and IG.Forms.TimerControlWorking.StopwatchStop().
IsCdSoundSecondTick
virtual bool IG.Forms.TimerControlWorking.IsCdSoundSecondTick get set
Whether the countdown's tick sound is switched on (a sound launched every second when the countdown is running).
Referenced by IG.Forms.TimerControlWorking.OnCountdownSecondTick().
IsCdSoundMinuteBell
virtual bool IG.Forms.TimerControlWorking.IsCdSoundMinuteBell get set
Whether the countdown's minute bell sound is switched on (a sound launched every minute when the countdown is running).
Referenced by IG.Forms.TimerControlWorking.OnCountdownMinuteBell().
IsCdSoundHourBell
virtual bool IG.Forms.TimerControlWorking.IsCdSoundHourBell get set
Whether the countdown's hpur bell sound is switched on (a sound launched every hour when the countdown is running).
Referenced by IG.Forms.TimerControlWorking.OnCountdownHourBell().
IsRunning
bool IG.Forms.TimerControlWorking.IsRunning get
Indicates whether the timer is currently running or not.
True is returned if either a stopwatch is running, a countdown is running, or the current time is displayed.
Referenced by IG.Forms.TimerControlWorking.CountdownResetIt(), IG.Forms.TimerControlWorking.CountdownStop(), IG.Forms.TimerControlWorking.StopwatchResetIt(), and IG.Forms.TimerControlWorking.StopwatchStop().
TimerIntervalMs
int IG.Forms.TimerControlWorking.TimerIntervalMs get set protected
Timer interval, in Milliseconds.
IsSilent
virtual bool IG.Forms.TimerControlWorking.IsSilent get set
Flag specifying whether the complete timer is in a silent mode.
Referenced by IG.Forms.TimerControlWorking.chkCdSilent_CheckedChanged(), IG.Forms.TimerControlWorking.chkSwSilent_CheckedChanged(), IG.Forms.TimerControlWorking.CountdownStart(), IG.Forms.TimerControlWorking.CountdownStop(), IG.Forms.TimerControlWorking.OnCountdownFinished(), IG.Forms.TimerControlWorking.OnCountdownHourBell(), IG.Forms.TimerControlWorking.OnCountdownMinuteBell(), IG.Forms.TimerControlWorking.OnCountdownSecondTick(), IG.Forms.TimerControlWorking.OnStopwatchHourBell(), IG.Forms.TimerControlWorking.OnStopwatchMinuteBell(), IG.Forms.TimerControlWorking.OnStopwatchSecondTick(), IG.Forms.TimerControlWorking.StopwatchStart(), and IG.Forms.TimerControlWorking.StopwatchStop().
SwStopwatch
StopWatch1 IG.Forms.TimerControlWorking.SwStopwatch get protected
Stopwatch used to measure elapsed time for the displayed stopwatch.
Referenced by IG.Forms.TimerControlWorking.StopwatchResetIt(), IG.Forms.TimerControlWorking.StopwatchStart(), IG.Forms.TimerControlWorking.StopwatchStartOrStop(), and IG.Forms.TimerControlWorking.StopwatchStop().
IsStopwatchRunning
bool IG.Forms.TimerControlWorking.IsStopwatchRunning get
Indicates whether the countdown timer is running or not.
Referenced by IG.Forms.TimerControlWorking.OnCountdownSecondTick(), IG.Forms.TimerControlWorking.StopwatchStart(), IG.Forms.TimerControlWorking.StopwatchStop(), IG.Forms.TimerControlWorking.timer1_Tick(), and IG.Forms.TimerControlWorking.UpdateSwButtonsAppearance().
StopwatchTotalTimeSpan
TimeSpan IG.Forms.TimerControlWorking.StopwatchTotalTimeSpan get
Gets the current time span measured by the stopwatch.
Referenced by IG.Forms.TimerControlWorking.timer1_Tick(), and IG.Forms.TimerControlWorking.UpdateSwDisplay().
StopWatchTotalTime
double IG.Forms.TimerControlWorking.StopWatchTotalTime get
Gets the current time span measured by the stopwatch.
FontMilli
Font IG.Forms.TimerControlWorking.FontMilli get set protected
Font used in timer's displays for milliseconds.
Referenced by IG.Forms.TimerControlWorking.UpdateDisplayAppearance(), and IG.Forms.TimerControlWorking.UpdateDisplayFonts().
DisplayFont
Font IG.Forms.TimerControlWorking.DisplayFont get set protected
Font used in timerr's displays.
Referenced by IG.Forms.TimerControlWorking.fontSelector_FontSelected(), IG.Forms.TimerControlWorking.fontSelectorCd_FontSelected(), IG.Forms.TimerControlWorking.fontSelectorSw_FontSelected(), IG.Forms.TimerControlWorking.SetDisplayFontSize(), IG.Forms.TimerControlWorking.TimerControlWorking(), IG.Forms.TimerControlWorking.UpdateDisplayAppearance(), and IG.Forms.TimerControlWorking.UpdateDisplayFonts().
MilliSecondsSizeRatio
double IG.Forms.TimerControlWorking.MilliSecondsSizeRatio get set
Ratio between the size of millisecond digits and other digits on the stopwatch.
Referenced by IG.Forms.TimerControlWorking.UpdateDisplayFonts().
MinDispayFontSizeInPoints
double IG.Forms.TimerControlWorking.MinDispayFontSizeInPoints get protected set
Minimal size of display font, in points.
Referenced by IG.Forms.TimerControlWorking.SetDisplayFontSize(), and IG.Forms.TimerControlWorking.UpdateDisplayFonts().
SwShowMilliSeconds
bool IG.Forms.TimerControlWorking.SwShowMilliSeconds get set
Whether milliseconds shoulld be shown.
Referenced by IG.Forms.TimerControlWorking.chkSwDisplayMilliseconds_CheckedChanged(), IG.Forms.TimerControlWorking.TimerControlWorking(), and IG.Forms.TimerControlWorking.UpdateDisplayAppearance().
SwShowHoursWhenZero
bool IG.Forms.TimerControlWorking.SwShowHoursWhenZero get set
Referenced by IG.Forms.TimerControlWorking.chkSwDisplayHours_CheckedChanged(), IG.Forms.TimerControlWorking.TimerControlWorking(), and IG.Forms.TimerControlWorking.UpdateSwDisplay().
ColorBgWarning
Color IG.Forms.TimerControlWorking.ColorBgWarning get set
ColorBgOk
Color IG.Forms.TimerControlWorking.ColorBgOk get set
ColorInvisible
Color IG.Forms.TimerControlWorking.ColorInvisible get
DisplayBg
Color IG.Forms.TimerControlWorking.DisplayBg get protected set
Display background color.
Referenced by IG.Forms.TimerControlWorking.UpdateDisplayAppearance().
DisplayFg
Color IG.Forms.TimerControlWorking.DisplayFg get protected set
Display foreground color.
Referenced by IG.Forms.TimerControlWorking.UpdateDisplayAppearance().
SwStartText
string IG.Forms.TimerControlWorking.SwStartText get set
Text that is written on the stopwatch start button.
Referenced by IG.Forms.TimerControlWorking.UpdateSwButtonsAppearance().
SwStopText
string IG.Forms.TimerControlWorking.SwStopText get set
Referenced by IG.Forms.TimerControlWorking.UpdateSwButtonsAppearance().
SwResetText
string IG.Forms.TimerControlWorking.SwResetText get protected set
Referenced by IG.Forms.TimerControlWorking.UpdateSwButtonsAppearance().
SwStartColor
Color IG.Forms.TimerControlWorking.SwStartColor get protected set
Background color for stopwatch start button.
Referenced by IG.Forms.TimerControlWorking.UpdateSwButtonsAppearance().
SwStopColor
Color IG.Forms.TimerControlWorking.SwStopColor get protected set
Referenced by IG.Forms.TimerControlWorking.UpdateSwButtonsAppearance().
SwResetColor
Color IG.Forms.TimerControlWorking.SwResetColor get protected set
Background color for stopwatch reset button.
Referenced by IG.Forms.TimerControlWorking.UpdateSwButtonsAppearance().
ControlsFgClosed
Color IG.Forms.TimerControlWorking.ControlsFgClosed get protected set
Foreground color for controls opener when controls are closed.
Referenced by IG.Forms.TimerControlWorking.UpdateCdControls(), and IG.Forms.TimerControlWorking.UpdateSwControls().
ControlsFgOpen
Color IG.Forms.TimerControlWorking.ControlsFgOpen get protected set
Foreground color for controls opener when controls are opened.
Referenced by IG.Forms.TimerControlWorking.UpdateCdControls(), and IG.Forms.TimerControlWorking.UpdateSwControls().
ControlsClosedText
string IG.Forms.TimerControlWorking.ControlsClosedText get protected set
Tect for controls opener when controls are closed.
Referenced by IG.Forms.TimerControlWorking.UpdateCdControls(), and IG.Forms.TimerControlWorking.UpdateSwControls().
ControlsOpenText
string IG.Forms.TimerControlWorking.ControlsOpenText get protected set
Tect for controls opener when controls are opened.
Referenced by IG.Forms.TimerControlWorking.UpdateCdControls(), and IG.Forms.TimerControlWorking.UpdateSwControls().
IsSwControlsOpened
bool IG.Forms.TimerControlWorking.IsSwControlsOpened get protected set
Wheether controls are opened or not.
Referenced by IG.Forms.TimerControlWorking.btnSwControls_Click(), IG.Forms.TimerControlWorking.TimerControlWorking(), and IG.Forms.TimerControlWorking.UpdateSwControls().
MaxTimerErrorReports
int IG.Forms.TimerControlWorking.MaxTimerErrorReports get set protected
Macimal number of times a report on exception thrown within the timer tick event can be launched.
Referenced by IG.Forms.TimerControlWorking.timer1_Tick().
NumTimerErrorReports
int IG.Forms.TimerControlWorking.NumTimerErrorReports get set protected
Number of times a report on exception thrown within the timer tick event has already been launched.
Referenced by IG.Forms.TimerControlWorking.timer1_Tick().
CdStopwatch
StopWatch1 IG.Forms.TimerControlWorking.CdStopwatch get protected
Stopwatch used to measure elapsed time for the displayed cowntdown.
Referenced by IG.Forms.TimerControlWorking.CountdownResetIt(), IG.Forms.TimerControlWorking.CountdownStart(), IG.Forms.TimerControlWorking.CountdownStartOrStop(), IG.Forms.TimerControlWorking.CountdownStop(), and IG.Forms.TimerControlWorking.timer1_Tick().
IsCountdownRunning
bool IG.Forms.TimerControlWorking.IsCountdownRunning get
Indicates whether the countdown timer is running or not.
Referenced by IG.Forms.TimerControlWorking.CountdownStart(), IG.Forms.TimerControlWorking.CountdownStop(), IG.Forms.TimerControlWorking.timer1_Tick(), and IG.Forms.TimerControlWorking.UpdateCdButtonsAppearance().
CountdownTotalTimeSpan
TimeSpan IG.Forms.TimerControlWorking.CountdownTotalTimeSpan get
Gets the current total time span measured by the countdown's stopwatch.
CountdownTotalTime
double IG.Forms.TimerControlWorking.CountdownTotalTime get
Gets the current time span measured by the countdown's stopwatch.
CountdownRemainingTimeSpan
TimeSpan IG.Forms.TimerControlWorking.CountdownRemainingTimeSpan get
Gets Countdown's remaining time span.
Returns
Referenced by IG.Forms.TimerControlWorking.timer1_Tick(), and IG.Forms.TimerControlWorking.UpdateCdDisplay().
CountdownRemainingTime
double IG.Forms.TimerControlWorking.CountdownRemainingTime get
Returns Countdown's remaining time in seconds.
Returns
Referenced by IG.Forms.TimerControlWorking.CountdownStart(), IG.Forms.TimerControlWorking.CountdownStop(), and IG.Forms.TimerControlWorking.UpdateCdButtonsAppearance().
CdInitialHours
virtual int IG.Forms.TimerControlWorking.CdInitialHours get set protected
Number of hours initially set in countdown.
Referenced by IG.Forms.TimerControlWorking.UpdateCdInitialTime(), and IG.Forms.TimerControlWorking.UpdateCdInitialTimeSpan().
CdInitialMinutes
virtual int IG.Forms.TimerControlWorking.CdInitialMinutes get set protected
Number of minutes initially set in countdown.
Referenced by IG.Forms.TimerControlWorking.UpdateCdInitialTime(), and IG.Forms.TimerControlWorking.UpdateCdInitialTimeSpan().
CdInitialSeconds
virtual int IG.Forms.TimerControlWorking.CdInitialSeconds get set protected
Number of seconds initially set in countdown.
Referenced by IG.Forms.TimerControlWorking.UpdateCdInitialTime(), and IG.Forms.TimerControlWorking.UpdateCdInitialTimeSpan().
CdInitialMilliseconds
virtual int IG.Forms.TimerControlWorking.CdInitialMilliseconds get set protected
Number of milliseconds initially set in countdown.
Referenced by IG.Forms.TimerControlWorking.UpdateCdInitialTime(), and IG.Forms.TimerControlWorking.UpdateCdInitialTimeSpan().
CdInitialTimeSpan
virtual TimeSpan IG.Forms.TimerControlWorking.CdInitialTimeSpan get set protected
Initial time span set in countdown.
Referenced by IG.Forms.TimerControlWorking.TimerControlWorking(), IG.Forms.TimerControlWorking.UpdateCdInitialTime(), and IG.Forms.TimerControlWorking.UpdateCdInitialTimeSpan().
CdShowMilliSeconds
bool IG.Forms.TimerControlWorking.CdShowMilliSeconds get set
Whether milliseconds shoulld be shown on countdown.
Referenced by IG.Forms.TimerControlWorking.chkCdDisplayMilliseconds_CheckedChanged(), IG.Forms.TimerControlWorking.TimerControlWorking(), and IG.Forms.TimerControlWorking.UpdateDisplayAppearance().
CdShowHoursWhenZero
bool IG.Forms.TimerControlWorking.CdShowHoursWhenZero get set
Referenced by IG.Forms.TimerControlWorking.chkCdDisplayHours_CheckedChanged(), IG.Forms.TimerControlWorking.TimerControlWorking(), and IG.Forms.TimerControlWorking.UpdateCdDisplay().
IsCdSoundButtons
virtual bool IG.Forms.TimerControlWorking.IsCdSoundButtons get set
Whether the countdown's button sound is switched on (a sound launched every time a countdown button with some effectt is pressed, or the same effect is achieved programatically).
Referenced by IG.Forms.TimerControlWorking.CountdownStart(), and IG.Forms.TimerControlWorking.CountdownStop().
IsCdSoundAlarm
virtual bool IG.Forms.TimerControlWorking.IsCdSoundAlarm get set
Whether a countdown's alarm sound is switched on (launched when the countdown is finished, i.e. the countdown reachhes zero).
Referenced by IG.Forms.TimerControlWorking.OnCountdownFinished().
CdStartText
string IG.Forms.TimerControlWorking.CdStartText get set
Text that is written on the stopwatch start button.
Referenced by IG.Forms.TimerControlWorking.UpdateCdButtonsAppearance().
CdStopText
string IG.Forms.TimerControlWorking.CdStopText get set
Referenced by IG.Forms.TimerControlWorking.UpdateCdButtonsAppearance().
CdResetText
string IG.Forms.TimerControlWorking.CdResetText get protected set
Referenced by IG.Forms.TimerControlWorking.UpdateCdButtonsAppearance().
CdStartColor
Color IG.Forms.TimerControlWorking.CdStartColor get protected set
Background color for stopwatch start button.
Referenced by IG.Forms.TimerControlWorking.UpdateCdButtonsAppearance().
CdStopColor
Color IG.Forms.TimerControlWorking.CdStopColor get protected set
Referenced by IG.Forms.TimerControlWorking.UpdateCdButtonsAppearance().
CdResetColor
Color IG.Forms.TimerControlWorking.CdResetColor get protected set
Referenced by IG.Forms.TimerControlWorking.UpdateCdButtonsAppearance().
IsCdControlsOpened
bool IG.Forms.TimerControlWorking.IsCdControlsOpened get protected set
Wheether controls are opened or not.
Referenced by IG.Forms.TimerControlWorking.btnCdControls_Click(), IG.Forms.TimerControlWorking.TimerControlWorking(), and IG.Forms.TimerControlWorking.UpdateCdControls().
IsClockRunning
bool IG.Forms.TimerControlWorking.IsClockRunning get set
Referenced by IG.Forms.TimerControlWorking.OnCountdownSecondTick(), and IG.Forms.TimerControlWorking.OnStopwatchSecondTick().
Event Documentation
StopwatchTimerTick
EventHandler IG.Forms.TimerControlWorking.StopwatchTimerTick
Event that is fired on each stopwatch's timer tick (very often, in the range of milliseconds).
This event is usually useful for debugging or for very fine control.
Referenced by IG.Forms.TimerControlWorking.OnStopwatchTimerTick().
StopwatchStarted
EventHandler IG.Forms.TimerControlWorking.StopwatchStarted
Event that is fired when the stopwatch starts.
Referenced by IG.Forms.TimerControlWorking.StopwatchStart().
StopwatchStopped
EventHandler IG.Forms.TimerControlWorking.StopwatchStopped
Event that is fired when the stopwatch stops.
Referenced by IG.Forms.TimerControlWorking.StopwatchStop().
StopwatchReset
EventHandler IG.Forms.TimerControlWorking.StopwatchReset
Event that is raised when the counter is reset.
Referenced by IG.Forms.TimerControlWorking.StopwatchResetIt().
StopwatchSecondTick
EventHandler IG.Forms.TimerControlWorking.StopwatchSecondTick
Event that is fired when second count changes to a whole value (seconds tick).
Referenced by IG.Forms.TimerControlWorking.OnStopwatchSecondTick().
StopwatchMinuteBell
EventHandler IG.Forms.TimerControlWorking.StopwatchMinuteBell
Event that is fired when minutes count changes to a whole value (minutes signal).
Referenced by IG.Forms.TimerControlWorking.OnStopwatchMinuteBell().
StopwatchHourBell
EventHandler IG.Forms.TimerControlWorking.StopwatchHourBell
Event that is fired when minutes count changes to a whole value (minute switch signal).
Referenced by IG.Forms.TimerControlWorking.OnStopwatchHourBell().
CountdownTimerTick
EventHandler IG.Forms.TimerControlWorking.CountdownTimerTick
Event that is fired on each countdown's timer tick (very often, in the range of milliseconds).
This event is usually usef for debugging or for very fine control.
Referenced by IG.Forms.TimerControlWorking.OnCountdownTimerTick().
CountdownStarted
EventHandler IG.Forms.TimerControlWorking.CountdownStarted
Event that is fired when the countdown starts.
Referenced by IG.Forms.TimerControlWorking.CountdownStart().
CountdownStopped
EventHandler IG.Forms.TimerControlWorking.CountdownStopped
Event that is fired when the countdown stops.
Referenced by IG.Forms.TimerControlWorking.CountdownStop().
CountdownReset
EventHandler IG.Forms.TimerControlWorking.CountdownReset
Event that is raised when the counter is reset.
Referenced by IG.Forms.TimerControlWorking.CountdownResetIt().
CountdownFinished
EventHandler IG.Forms.TimerControlWorking.CountdownFinished
Event that is fired when the countdown reaches 0.
Referenced by IG.Forms.TimerControlWorking.OnCountdownFinished().
CountdownSecondTick
EventHandler IG.Forms.TimerControlWorking.CountdownSecondTick
Event that is fired when second count changes to a whole value (seconds tick).
Referenced by IG.Forms.TimerControlWorking.OnCountdownSecondTick().
CountdownMinuteBell
EventHandler IG.Forms.TimerControlWorking.CountdownMinuteBell
Event that is fired when minutes count changes to a whole value (minutes signal).
Referenced by IG.Forms.TimerControlWorking.OnCountdownMinuteBell().
CountdownHourBell
EventHandler IG.Forms.TimerControlWorking.CountdownHourBell
Event that is fired when gours count changes to a whole value (hours signal).
Referenced by IG.Forms.TimerControlWorking.OnCountdownHourBell().
The documentation for this class was generated from the following files:
unittests/Guest_IGTestCopy/Copy_Functions/Copy_Other/SaveWorking/TimerControlWorking.cs
unittests/Guest_IGTestCopy/Copy_Functions/Copy_Other/SaveWorking/TimerControlWorking.Designer.cs