Doc: IGLib EXTENDED: NUnit.Framework.Internal.Filters.EmptyFilterTests Class Reference
NUnit.Framework.Internal.Filters.EmptyFilterTests Class Reference
Public Member Functions
void IsEmpty ()
void BuildFromXml ()
void MatchesAnything ()
void PassesAnything ()
void MatchesNothihngExplicitly ()
Public Member Functions inherited from NUnit.Framework.Internal.Filters.TestFilterTests
void SetUpSuite ()
Additional Inherited Members
Static Public Attributes inherited from NUnit.Framework.Internal.Filters.TestFilterTests
const string DUMMY_CLASS = "NUnit.Framework.Internal.Filters.TestFilterTests+DummyFixture"
Protected Attributes inherited from NUnit.Framework.Internal.Filters.TestFilterTests
readonly TestSuite _dummyFixture = TestBuilder.MakeFixture(typeof(DummyFixture))
readonly TestSuite _anotherFixture = TestBuilder.MakeFixture(typeof(AnotherFixture))
readonly TestSuite _yetAnotherFixture = TestBuilder.MakeFixture(typeof(YetAnotherFixture))
readonly TestSuite _fixtureWithMultipleTests = TestBuilder.MakeFixture (typeof (FixtureWithMultipleTests))
readonly TestSuite _topLevelSuite = new TestSuite("MySuite")
Member Function Documentation
IsEmpty()
void NUnit.Framework.Internal.Filters.EmptyFilterTests.IsEmpty () inline
References NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Internal.TestFilter.IsEmpty, and NUnit.Framework.Assert.That().
BuildFromXml()
void NUnit.Framework.Internal.Filters.EmptyFilterTests.BuildFromXml () inline
References NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Internal.TestFilter.IsEmpty, and NUnit.Framework.Assert.That().
MatchesAnything()
void NUnit.Framework.Internal.Filters.EmptyFilterTests.MatchesAnything () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Internal.Filters.TestFilterTests._yetAnotherFixture, NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Internal.TestFilter.Match(), and NUnit.Framework.Assert.That().
PassesAnything()
void NUnit.Framework.Internal.Filters.EmptyFilterTests.PassesAnything () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Internal.Filters.TestFilterTests._yetAnotherFixture, NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Internal.TestFilter.Match(), and NUnit.Framework.Assert.That().
MatchesNothihngExplicitly()
void NUnit.Framework.Internal.Filters.EmptyFilterTests.MatchesNothihngExplicitly () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Internal.Filters.TestFilterTests._yetAnotherFixture, NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Assert.False(), and NUnit.Framework.Internal.TestFilter.IsExplicitMatch().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/Filters/EmptyFilterTests.cs