Doc: IGLib EXTENDED: IG.Forms.WindowPositioner Class Reference
IG.Forms.WindowPositioner Class Reference
Takes care of windows positioning, relative of absolute to the screen and/or other windows.
Public Member Functions
WindowPositioner ()
Constructs a new window positioner where the positioned and the master window are not yet defined.
WindowPositioner (Form positionedWindow)
Constructs a new window positioner with the specified window to be positioned and unspecified
WindowPositioner (Form positionedWindow, Form masterWindow)
Constructs a new window positioner with the specified window to be positioned and the specified master window.
void PositionWindow ()
Positions the positioned window according to the CalculatedPosition
void SetToCurrentPosition ()
Shanges the shift of window position such that it corresponds to actual current position of the window.
void StickToMaster ()
Sticks the positioned window to master window, if possible.
void UnStickFromMaster ()
Stichs the positioned window to master window (), if possible.
void RememberPosition ()
Starts remembering potitions relative to the master window when the position is changed and this is not due to sticking to the master window.
void StopRememberPosition ()
Stops remembering potitions relative to the master window when the position is changed and this is not due to sticking to the master window.
virtual void InitScreenData ()
Obtains the screen resolution etc. (if data hasen't been obtained yet), and sets the IsScreenDataInitialized property to true.
virtual void InitScreenDataForced ()
Obtains the screen resolution etc., and sets the IsScreenDataInitialized property to true.
WindowPositioner ()
Constructs a new window positioner where the positioned and the master window are not yet defined.
WindowPositioner (Form positionedWindow)
Constructs a new window positioner with the specified window to be positioned and unspecified
WindowPositioner (Form positionedWindow, Form masterWindow)
Constructs a new window positioner with the specified window to be positioned and the specified master window.
void PositionWindow ()
Positions the positioned window according to the CalculatedPosition
void SetToCurrentPosition ()
Shanges the shift of window position such that it corresponds to actual current position of the window.
void StickToMaster ()
Sticks the positioned window to master window, if possible.
void UnStickFromMaster ()
Stichs the positioned window to master window (), if possible.
void RememberPosition ()
Starts remembering potitions relative to the master window when the position is changed and this is not due to sticking to the master window.
void StopRememberPosition ()
Stops remembering potitions relative to the master window when the position is changed and this is not due to sticking to the master window.
virtual void InitScreenData ()
Obtains the screen resolution etc. (if data hasen't been obtained yet), and sets the IsScreenDataInitialized property to true.
virtual void InitScreenDataForced ()
Obtains the screen resolution etc., and sets the IsScreenDataInitialized property to true.
WindowPositioner ()
Constructs a new window positioner where the positioned and the master window are not yet defined.
WindowPositioner (Form positionedWindow)
Constructs a new window positioner with the specified window to be positioned and unspecified
WindowPositioner (Form positionedWindow, Form masterWindow)
Constructs a new window positioner with the specified window to be positioned and the specified master window.
void PositionWindow ()
Positions the positioned window according to the CalculatedPosition
void SetToCurrentPosition ()
Shanges the shift of window position such that it corresponds to actual current position of the window.
void StickToMaster ()
Sticks the positioned window to master window, if possible.
void UnStickFromMaster ()
Stichs the positioned window to master window (), if possible.
void RememberPosition ()
Starts remembering potitions relative to the master window when the position is changed and this is not due to sticking to the master window.
void StopRememberPosition ()
Stops remembering potitions relative to the master window when the position is changed and this is not due to sticking to the master window.
virtual void InitScreenData ()
Obtains the screen resolution etc. (if data hasen't been obtained yet), and sets the IsScreenDataInitialized property to true.
virtual void InitScreenDataForced ()
Obtains the screen resolution etc., and sets the IsScreenDataInitialized property to true.
Static Public Attributes
static double MinimalMovementPauseSeconds = 0.001
Minimal acceptable value for the pause between consecutive movement events that are processed in implementation of sticking window and remembering relative position.
Protected Member Functions
void StickEventHandler (object Sender, EventArgs args)
This event handler is added to the master window so that its position and size changes can be tracked.
void RememberPositionEventHandler (object Sender, EventArgs args)
This event handler is added to the positioned window so that its position and size changes can be remembered when not caused by sticking to the master.
void StickEventHandler (object Sender, EventArgs args)
This event handler is added to the master window so that its position and size changes can be tracked.
void RememberPositionEventHandler (object Sender, EventArgs args)
This event handler is added to the positioned window so that its position and size changes can be remembered when not caused by sticking to the master.
void StickEventHandler (object Sender, EventArgs args)
This event handler is added to the master window so that its position and size changes can be tracked.
void RememberPositionEventHandler (object Sender, EventArgs args)
This event handler is added to the positioned window so that its position and size changes can be remembered when not caused by sticking to the master.
Protected Attributes
bool _positionWindowExecuted = false
DateTime _lastMoved = DateTime.Now
double _movementPauseSeconds = 0.01
bool _isStickedToMaster = false
bool _isRememberPosition = false
vec2 _shiftAbsolute = new vec2(0, 0)
double _masterWeight = 1.0
System.Windows.Forms.Form _window
Alignment _windowAlignment = new Alignment(AlignmentHorizontal.Left, AlignmentVertical.Top)
vec2 _windowShiftRelative = new vec2(0, 0)
System.Windows.Forms.Form _masterWindow
Alignment _masterWindowAlignment = new Alignment(AlignmentHorizontal.Left, AlignmentVertical.Top)
vec2 _masterWindowShiftRelative = new vec2(0, 0)
bool _isScreenDataInitialized = false
Rectangle _screenBounds
Alignment _screenAlignment = new Alignment(AlignmentHorizontal.Left, AlignmentVertical.Top)
vec2 _screenShiftRelative = new vec2(0, 0)
Properties
object Lock [get]
double MovementPauseSeconds [get, set]
Minimal pause, in seconds, between two successive movements of the window due to sticking.
bool IsStickedToMaster [get, set]
Whether or not the position window is sticked to the master window such that it follows its movement.
bool IsRememberPosition [get, set]
Whether or not relative position with respect to master is remembered when movement is not caused by sticking to the master window.
virtual vec2 ShiftAbsolute [get, set]
Additional shift of positioned window in pixels.
virtual double MasterWeight [get, set]
Relative weight (importance) of positioning relative to master window.
virtual double ScreenWeight [get, set]
Relative weight (importance) of positioning relative to screen window.
virtual vec2 CalculatedPosition [get]
Calculated position of the top-left corner of the positioned window.
virtual System.Windows.Forms.Form Window [get, set]
Window to be positioned.
virtual Alignment WindowAlignment [get, set]
Alignment of the positioned window with respect to point of positioning.
virtual vec2 WindowShiftRelative [get, set]
Additional shift of positioned window relative to Window size.
virtual Rectangle WindowBounds [get]
Bounds of the window to be positioned.
virtual vec2 WindowShift [get]
calculated additional shift of the positioned window that depends on that window.
virtual System.Windows.Forms.Form MasterWindow [get, set]
Master window relative to which positioning is calculated.
virtual Alignment MasterWindowAlignment [get, set]
Alignment of the positioned window with respect to point of positioning.
vec2 MasterWindowShiftRelative [get, set]
Additional shift of positioned window relative to Window size.
virtual Rectangle MasterWindowBounds [get]
Bounds of the window to be positioned.
virtual vec2 MasterWindowShift [get]
calculated additional shift of the positioned window that depends on that window.
virtual bool IsScreenDataInitialized [get, set]
Whwtheer screen data has been obtained or not.
Rectangle ScreenBounds [get]
Gets screen bounds.
Alignment ScreenAlignment [get, set]
vec2 ScreenShiftRelative [get, set]
Additional shift of positioned window relative to screen size.
vec2 ScreenShift [get]
calculated additional shift of the position window that is bound to screen.
Private Attributes
object _lock = new object()
Detailed Description
Takes care of windows positioning, relative of absolute to the screen and/or other windows.
$A Igor xx;
Constructor & Destructor Documentation
WindowPositioner() [1/9]
IG.Forms.WindowPositioner.WindowPositioner () inline
Constructs a new window positioner where the positioned and the master window are not yet defined.
WindowPositioner() [2/9]
IG.Forms.WindowPositioner.WindowPositioner (Form positionedWindow) inline
Constructs a new window positioner with the specified window to be positioned and unspecified
master window.
Parameters
positionedWindow Window to be positioned. Can be null.
masterWindow Master window with respect to which the window is also positioned. Can be null.
WindowPositioner() [3/9]
IG.Forms.WindowPositioner.WindowPositioner (Form positionedWindow, Form masterWindow) inline
Constructs a new window positioner with the specified window to be positioned and the specified master window.
Parameters
positionedWindow Window to be positioned. Can be null.
masterWindow Master window with respect to which the window is also positioned. Can be null.
References IG.Forms.WindowPositioner.MasterWindow, and IG.Forms.WindowPositioner.Window.
WindowPositioner() [4/9]
IG.Forms.WindowPositioner.WindowPositioner () inline
Constructs a new window positioner where the positioned and the master window are not yet defined.
WindowPositioner() [5/9]
IG.Forms.WindowPositioner.WindowPositioner (Form positionedWindow) inline
Constructs a new window positioner with the specified window to be positioned and unspecified
master window.
Parameters
positionedWindow Window to be positioned. Can be null.
masterWindow Master window with respect to which the window is also positioned. Can be null.
WindowPositioner() [6/9]
IG.Forms.WindowPositioner.WindowPositioner (Form positionedWindow, Form masterWindow) inline
Constructs a new window positioner with the specified window to be positioned and the specified master window.
Parameters
positionedWindow Window to be positioned. Can be null.
masterWindow Master window with respect to which the window is also positioned. Can be null.
References IG.Forms.WindowPositioner.MasterWindow, and IG.Forms.WindowPositioner.Window.
WindowPositioner() [7/9]
IG.Forms.WindowPositioner.WindowPositioner () inline
Constructs a new window positioner where the positioned and the master window are not yet defined.
WindowPositioner() [8/9]
IG.Forms.WindowPositioner.WindowPositioner (Form positionedWindow) inline
Constructs a new window positioner with the specified window to be positioned and unspecified
master window.
Parameters
positionedWindow Window to be positioned. Can be null.
masterWindow Master window with respect to which the window is also positioned. Can be null.
WindowPositioner() [9/9]
IG.Forms.WindowPositioner.WindowPositioner (Form positionedWindow, Form masterWindow) inline
Constructs a new window positioner with the specified window to be positioned and the specified master window.
Parameters
positionedWindow Window to be positioned. Can be null.
masterWindow Master window with respect to which the window is also positioned. Can be null.
References IG.Forms.WindowPositioner.MasterWindow, and IG.Forms.WindowPositioner.Window.
Member Function Documentation
PositionWindow() [1/3]
void IG.Forms.WindowPositioner.PositionWindow () inline
Positions the positioned window according to the CalculatedPosition
References IG.Forms.WindowPositioner._positionWindowExecuted, IG.Forms.WindowPositioner.CalculatedPosition, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.Window, IG.Num.vec2.x, and IG.Num.vec2.y.
Referenced by IG.Forms.WindowPositionerControl.btnPositionWindows_Click(), IG.Gr3d.Graph3dManipulator.PositionInitializeEventHandler(), and IG.Forms.WindowPositioner.StickEventHandler().
SetToCurrentPosition() [1/3]
void IG.Forms.WindowPositioner.SetToCurrentPosition () inline
Shanges the shift of window position such that it corresponds to actual current position of the window.
This is usually used when user is allowed to adjust relative positinon to the master of a sticking window.
References IG.Forms.WindowPositioner.CalculatedPosition, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.ShiftAbsolute, IG.Forms.WindowPositioner.Window, IG.Num.vec2.x, and IG.Num.vec2.y.
Referenced by IG.Forms.WindowPositionerControl.btnRememberPosition_Click(), and IG.Forms.WindowPositioner.RememberPositionEventHandler().
StickEventHandler() [1/3]
void IG.Forms.WindowPositioner.StickEventHandler (object Sender, EventArgs args) inline protected
This event handler is added to the master window so that its position and size changes can be tracked.
References IG.Forms.WindowPositioner._lastMoved, IG.Forms.WindowPositioner.IsStickedToMaster, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.MasterWindow, IG.Forms.WindowPositioner.MovementPauseSeconds, IG.Forms.WindowPositioner.PositionWindow(), and IG.Forms.WindowPositioner.Window.
Referenced by IG.Forms.WindowPositioner.StickToMaster(), and IG.Forms.WindowPositioner.UnStickFromMaster().
RememberPositionEventHandler() [1/3]
void IG.Forms.WindowPositioner.RememberPositionEventHandler (object Sender, EventArgs args) inline protected
This event handler is added to the positioned window so that its position and size changes can be remembered when not caused by sticking to the master.
References IG.Forms.WindowPositioner._lastMoved, IG.Forms.WindowPositioner._positionWindowExecuted, IG.Forms.WindowPositioner.IsRememberPosition, IG.Forms.WindowPositioner.IsStickedToMaster, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.MasterWindow, IG.Forms.WindowPositioner.MovementPauseSeconds, IG.Forms.WindowPositioner.SetToCurrentPosition(), and IG.Forms.WindowPositioner.Window.
Referenced by IG.Forms.WindowPositioner.RememberPosition(), and IG.Forms.WindowPositioner.StopRememberPosition().
StickToMaster() [1/3]
void IG.Forms.WindowPositioner.StickToMaster () inline
Sticks the positioned window to master window, if possible.
References IG.Forms.WindowPositioner.IsStickedToMaster, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.MasterWindow, IG.Forms.WindowPositioner.StickEventHandler(), and IG.Forms.WindowPositioner.Window.
Referenced by IG.Forms.WindowPositionerControl.btnStickToMaster_Click(), and IG.Gr3d.Graph3dManipulator.InitPositioner().
UnStickFromMaster() [1/3]
void IG.Forms.WindowPositioner.UnStickFromMaster () inline
Stichs the positioned window to master window (), if possible.
References IG.Forms.WindowPositioner.IsStickedToMaster, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.MasterWindow, IG.Forms.WindowPositioner.StickEventHandler(), and IG.Forms.WindowPositioner.Window.
Referenced by IG.Forms.WindowPositionerControl.btnUnStickFromMaster_Click().
RememberPosition() [1/3]
void IG.Forms.WindowPositioner.RememberPosition () inline
Starts remembering potitions relative to the master window when the position is changed and this is not due to sticking to the master window.
References IG.Forms.WindowPositioner.IsRememberPosition, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.MasterWindow, IG.Forms.WindowPositioner.RememberPositionEventHandler(), and IG.Forms.WindowPositioner.Window.
Referenced by IG.Forms.WindowPositionerControl.chkRememberPositions_CheckedChanged(), and IG.Gr3d.Graph3dManipulator.InitPositioner().
StopRememberPosition() [1/3]
void IG.Forms.WindowPositioner.StopRememberPosition () inline
Stops remembering potitions relative to the master window when the position is changed and this is not due to sticking to the master window.
References IG.Forms.WindowPositioner.IsRememberPosition, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.MasterWindow, IG.Forms.WindowPositioner.RememberPositionEventHandler(), and IG.Forms.WindowPositioner.Window.
Referenced by IG.Forms.WindowPositionerControl.chkRememberPositions_CheckedChanged().
InitScreenData() [1/3]
virtual void IG.Forms.WindowPositioner.InitScreenData () inline virtual
Obtains the screen resolution etc. (if data hasen't been obtained yet), and sets the IsScreenDataInitialized property to true.
References IG.Forms.WindowPositioner.InitScreenDataForced(), IG.Forms.WindowPositioner.IsScreenDataInitialized, and IG.Forms.WindowPositioner.Lock.
InitScreenDataForced() [1/3]
virtual void IG.Forms.WindowPositioner.InitScreenDataForced () inline virtual
Obtains the screen resolution etc., and sets the IsScreenDataInitialized property to true.
References IG.Forms.WindowPositioner._screenBounds, IG.Forms.WindowPositioner.IsScreenDataInitialized, IG.Forms.WindowPositioner.Lock, and IG.Forms.WindowPositioner.Window.
Referenced by IG.Forms.WindowPositioner.InitScreenData().
PositionWindow() [2/3]
void IG.Forms.WindowPositioner.PositionWindow () inline
Positions the positioned window according to the CalculatedPosition
References IG.Forms.WindowPositioner._positionWindowExecuted, IG.Forms.WindowPositioner.CalculatedPosition, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.Window, IG.Num.vec2.x, and IG.Num.vec2.y.
SetToCurrentPosition() [2/3]
void IG.Forms.WindowPositioner.SetToCurrentPosition () inline
Shanges the shift of window position such that it corresponds to actual current position of the window.
This is usually used when user is allowed to adjust relative positinon to the master of a sticking window.
References IG.Forms.WindowPositioner.CalculatedPosition, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.ShiftAbsolute, IG.Forms.WindowPositioner.Window, IG.Num.vec2.x, and IG.Num.vec2.y.
StickEventHandler() [2/3]
void IG.Forms.WindowPositioner.StickEventHandler (object Sender, EventArgs args) inline protected
This event handler is added to the master window so that its position and size changes can be tracked.
References IG.Forms.WindowPositioner._lastMoved, IG.Forms.WindowPositioner.IsStickedToMaster, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.MasterWindow, IG.Forms.WindowPositioner.MovementPauseSeconds, IG.Forms.WindowPositioner.PositionWindow(), and IG.Forms.WindowPositioner.Window.
RememberPositionEventHandler() [2/3]
void IG.Forms.WindowPositioner.RememberPositionEventHandler (object Sender, EventArgs args) inline protected
This event handler is added to the positioned window so that its position and size changes can be remembered when not caused by sticking to the master.
References IG.Forms.WindowPositioner._lastMoved, IG.Forms.WindowPositioner._positionWindowExecuted, IG.Forms.WindowPositioner.IsRememberPosition, IG.Forms.WindowPositioner.IsStickedToMaster, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.MasterWindow, IG.Forms.WindowPositioner.MovementPauseSeconds, IG.Forms.WindowPositioner.SetToCurrentPosition(), and IG.Forms.WindowPositioner.Window.
StickToMaster() [2/3]
void IG.Forms.WindowPositioner.StickToMaster () inline
Sticks the positioned window to master window, if possible.
References IG.Forms.WindowPositioner.IsStickedToMaster, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.MasterWindow, IG.Forms.WindowPositioner.StickEventHandler(), and IG.Forms.WindowPositioner.Window.
UnStickFromMaster() [2/3]
void IG.Forms.WindowPositioner.UnStickFromMaster () inline
Stichs the positioned window to master window (), if possible.
References IG.Forms.WindowPositioner.IsStickedToMaster, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.MasterWindow, IG.Forms.WindowPositioner.StickEventHandler(), and IG.Forms.WindowPositioner.Window.
RememberPosition() [2/3]
void IG.Forms.WindowPositioner.RememberPosition () inline
Starts remembering potitions relative to the master window when the position is changed and this is not due to sticking to the master window.
References IG.Forms.WindowPositioner.IsRememberPosition, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.MasterWindow, IG.Forms.WindowPositioner.RememberPositionEventHandler(), and IG.Forms.WindowPositioner.Window.
StopRememberPosition() [2/3]
void IG.Forms.WindowPositioner.StopRememberPosition () inline
Stops remembering potitions relative to the master window when the position is changed and this is not due to sticking to the master window.
References IG.Forms.WindowPositioner.IsRememberPosition, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.MasterWindow, IG.Forms.WindowPositioner.RememberPositionEventHandler(), and IG.Forms.WindowPositioner.Window.
InitScreenData() [2/3]
virtual void IG.Forms.WindowPositioner.InitScreenData () inline virtual
Obtains the screen resolution etc. (if data hasen't been obtained yet), and sets the IsScreenDataInitialized property to true.
References IG.Forms.WindowPositioner.InitScreenDataForced(), IG.Forms.WindowPositioner.IsScreenDataInitialized, and IG.Forms.WindowPositioner.Lock.
InitScreenDataForced() [2/3]
virtual void IG.Forms.WindowPositioner.InitScreenDataForced () inline virtual
Obtains the screen resolution etc., and sets the IsScreenDataInitialized property to true.
References IG.Forms.WindowPositioner._screenBounds, IG.Forms.WindowPositioner.IsScreenDataInitialized, IG.Forms.WindowPositioner.Lock, and IG.Forms.WindowPositioner.Window.
PositionWindow() [3/3]
void IG.Forms.WindowPositioner.PositionWindow () inline
Positions the positioned window according to the CalculatedPosition
References IG.Forms.WindowPositioner._positionWindowExecuted, IG.Forms.WindowPositioner.CalculatedPosition, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.Window, IG.Num.vec2.x, and IG.Num.vec2.y.
SetToCurrentPosition() [3/3]
void IG.Forms.WindowPositioner.SetToCurrentPosition () inline
Shanges the shift of window position such that it corresponds to actual current position of the window.
This is usually used when user is allowed to adjust relative positinon to the master of a sticking window.
References IG.Forms.WindowPositioner.CalculatedPosition, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.ShiftAbsolute, IG.Forms.WindowPositioner.Window, IG.Num.vec2.x, and IG.Num.vec2.y.
StickEventHandler() [3/3]
void IG.Forms.WindowPositioner.StickEventHandler (object Sender, EventArgs args) inline protected
This event handler is added to the master window so that its position and size changes can be tracked.
References IG.Forms.WindowPositioner._lastMoved, IG.Forms.WindowPositioner.IsStickedToMaster, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.MasterWindow, IG.Forms.WindowPositioner.MovementPauseSeconds, IG.Forms.WindowPositioner.PositionWindow(), and IG.Forms.WindowPositioner.Window.
RememberPositionEventHandler() [3/3]
void IG.Forms.WindowPositioner.RememberPositionEventHandler (object Sender, EventArgs args) inline protected
This event handler is added to the positioned window so that its position and size changes can be remembered when not caused by sticking to the master.
References IG.Forms.WindowPositioner._lastMoved, IG.Forms.WindowPositioner._positionWindowExecuted, IG.Forms.WindowPositioner.IsRememberPosition, IG.Forms.WindowPositioner.IsStickedToMaster, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.MasterWindow, IG.Forms.WindowPositioner.MovementPauseSeconds, IG.Forms.WindowPositioner.SetToCurrentPosition(), and IG.Forms.WindowPositioner.Window.
StickToMaster() [3/3]
void IG.Forms.WindowPositioner.StickToMaster () inline
Sticks the positioned window to master window, if possible.
References IG.Forms.WindowPositioner.IsStickedToMaster, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.MasterWindow, IG.Forms.WindowPositioner.StickEventHandler(), and IG.Forms.WindowPositioner.Window.
UnStickFromMaster() [3/3]
void IG.Forms.WindowPositioner.UnStickFromMaster () inline
Stichs the positioned window to master window (), if possible.
References IG.Forms.WindowPositioner.IsStickedToMaster, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.MasterWindow, IG.Forms.WindowPositioner.StickEventHandler(), and IG.Forms.WindowPositioner.Window.
RememberPosition() [3/3]
void IG.Forms.WindowPositioner.RememberPosition () inline
Starts remembering potitions relative to the master window when the position is changed and this is not due to sticking to the master window.
References IG.Forms.WindowPositioner.IsRememberPosition, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.MasterWindow, IG.Forms.WindowPositioner.RememberPositionEventHandler(), and IG.Forms.WindowPositioner.Window.
StopRememberPosition() [3/3]
void IG.Forms.WindowPositioner.StopRememberPosition () inline
Stops remembering potitions relative to the master window when the position is changed and this is not due to sticking to the master window.
References IG.Forms.WindowPositioner.IsRememberPosition, IG.Forms.WindowPositioner.Lock, IG.Forms.WindowPositioner.MasterWindow, IG.Forms.WindowPositioner.RememberPositionEventHandler(), and IG.Forms.WindowPositioner.Window.
InitScreenData() [3/3]
virtual void IG.Forms.WindowPositioner.InitScreenData () inline virtual
Obtains the screen resolution etc. (if data hasen't been obtained yet), and sets the IsScreenDataInitialized property to true.
References IG.Forms.WindowPositioner.InitScreenDataForced(), IG.Forms.WindowPositioner.IsScreenDataInitialized, and IG.Forms.WindowPositioner.Lock.
InitScreenDataForced() [3/3]
virtual void IG.Forms.WindowPositioner.InitScreenDataForced () inline virtual
Obtains the screen resolution etc., and sets the IsScreenDataInitialized property to true.
References IG.Forms.WindowPositioner._screenBounds, IG.Forms.WindowPositioner.IsScreenDataInitialized, IG.Forms.WindowPositioner.Lock, and IG.Forms.WindowPositioner.Window.
Member Data Documentation
_lock
object IG.Forms.WindowPositioner._lock = new object() private
_positionWindowExecuted
bool IG.Forms.WindowPositioner._positionWindowExecuted = false protected
Referenced by IG.Forms.WindowPositioner.PositionWindow(), and IG.Forms.WindowPositioner.RememberPositionEventHandler().
_lastMoved
DateTime IG.Forms.WindowPositioner._lastMoved = DateTime.Now protected
Referenced by IG.Forms.WindowPositioner.RememberPositionEventHandler(), and IG.Forms.WindowPositioner.StickEventHandler().
MinimalMovementPauseSeconds
static double IG.Forms.WindowPositioner.MinimalMovementPauseSeconds = 0.001 static
Minimal acceptable value for the pause between consecutive movement events that are processed in implementation of sticking window and remembering relative position.
_movementPauseSeconds
double IG.Forms.WindowPositioner._movementPauseSeconds = 0.01 protected
_isStickedToMaster
bool IG.Forms.WindowPositioner._isStickedToMaster = false protected
_isRememberPosition
bool IG.Forms.WindowPositioner._isRememberPosition = false protected
_shiftAbsolute
vec2 IG.Forms.WindowPositioner._shiftAbsolute = new vec2(0, 0) protected
_masterWeight
double IG.Forms.WindowPositioner._masterWeight = 1.0 protected
_window
System Windows Forms Form IG.Forms.WindowPositioner._window protected
_windowAlignment
Alignment IG.Forms.WindowPositioner._windowAlignment = new Alignment(AlignmentHorizontal.Left, AlignmentVertical.Top) protected
_windowShiftRelative
vec2 IG.Forms.WindowPositioner._windowShiftRelative = new vec2(0, 0) protected
_masterWindow
System Windows Forms Form IG.Forms.WindowPositioner._masterWindow protected
_masterWindowAlignment
Alignment IG.Forms.WindowPositioner._masterWindowAlignment = new Alignment(AlignmentHorizontal.Left, AlignmentVertical.Top) protected
_masterWindowShiftRelative
vec2 IG.Forms.WindowPositioner._masterWindowShiftRelative = new vec2(0, 0) protected
_isScreenDataInitialized
bool IG.Forms.WindowPositioner._isScreenDataInitialized = false protected
_screenBounds
Rectangle IG.Forms.WindowPositioner._screenBounds protected
Referenced by IG.Forms.WindowPositioner.InitScreenDataForced().
_screenAlignment
Alignment IG.Forms.WindowPositioner._screenAlignment = new Alignment(AlignmentHorizontal.Left, AlignmentVertical.Top) protected
_screenShiftRelative
vec2 IG.Forms.WindowPositioner._screenShiftRelative = new vec2(0, 0) protected
Property Documentation
Lock
object IG.Forms.WindowPositioner.Lock get
Referenced by IG.Forms.WindowPositioner.InitScreenData(), IG.Forms.WindowPositioner.InitScreenDataForced(), IG.Forms.WindowPositioner.PositionWindow(), IG.Forms.WindowPositioner.RememberPosition(), IG.Forms.WindowPositioner.RememberPositionEventHandler(), IG.Forms.WindowPositioner.SetToCurrentPosition(), IG.Forms.WindowPositioner.StickEventHandler(), IG.Forms.WindowPositioner.StickToMaster(), IG.Forms.WindowPositioner.StopRememberPosition(), and IG.Forms.WindowPositioner.UnStickFromMaster().
MovementPauseSeconds
double IG.Forms.WindowPositioner.MovementPauseSeconds get set
Minimal pause, in seconds, between two successive movements of the window due to sticking.
Referenced by IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.CopyDataToPositioner(), IG.Forms.WindowPositioner.RememberPositionEventHandler(), IG.Forms.WindowPositioner.StickEventHandler(), and IG.Forms.WindowPositionerControl.txtPause_Validated().
IsStickedToMaster
bool IG.Forms.WindowPositioner.IsStickedToMaster get set
Whether or not the position window is sticked to the master window such that it follows its movement.
Referenced by IG.Forms.WindowPositioner.RememberPositionEventHandler(), IG.Forms.WindowPositioner.StickEventHandler(), IG.Forms.WindowPositioner.StickToMaster(), and IG.Forms.WindowPositioner.UnStickFromMaster().
IsRememberPosition
bool IG.Forms.WindowPositioner.IsRememberPosition get set
Whether or not relative position with respect to master is remembered when movement is not caused by sticking to the master window.
Positions are only remembered if sticking to master is also performed.
Referenced by IG.Forms.WindowPositioner.RememberPosition(), IG.Forms.WindowPositioner.RememberPositionEventHandler(), and IG.Forms.WindowPositioner.StopRememberPosition().
ShiftAbsolute
vec2 IG.Forms.WindowPositioner.ShiftAbsolute get set
Additional shift of positioned window in pixels.
{0,0} means no shift, otherwise shift is in pixels and menas difference to otherwise calculated position.
Referenced by IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.CopyDataToPositioner(), IG.Gr3d.Graph3dManipulator.InitPositioner(), and IG.Forms.WindowPositioner.SetToCurrentPosition().
MasterWeight
double IG.Forms.WindowPositioner.MasterWeight get set
Relative weight (importance) of positioning relative to master window.
Referenced by IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.CopyDataToPositioner(), and IG.Gr3d.Graph3dManipulator.InitPositioner().
ScreenWeight
double IG.Forms.WindowPositioner.ScreenWeight get set
Relative weight (importance) of positioning relative to screen window.
CalculatedPosition
vec2 IG.Forms.WindowPositioner.CalculatedPosition get
Calculated position of the top-left corner of the positioned window.
Referenced by IG.Forms.WindowPositioner.PositionWindow(), and IG.Forms.WindowPositioner.SetToCurrentPosition().
Window
System Windows Forms Form IG.Forms.WindowPositioner.Window get set
Window to be positioned.
Referenced by IG.Gr3d.Graph3dManipulator.InitPositioner(), IG.Forms.WindowPositioner.InitScreenDataForced(), IG.Forms.WindowPositioner.PositionWindow(), IG.Forms.WindowPositioner.RememberPosition(), IG.Forms.WindowPositioner.RememberPositionEventHandler(), IG.Forms.WindowPositioner.SetToCurrentPosition(), IG.Forms.WindowPositioner.StickEventHandler(), IG.Forms.WindowPositioner.StickToMaster(), IG.Forms.WindowPositioner.StopRememberPosition(), IG.Forms.WindowPositioner.UnStickFromMaster(), and IG.Forms.WindowPositioner.WindowPositioner().
WindowAlignment
Alignment IG.Forms.WindowPositioner.WindowAlignment get set
Alignment of the positioned window with respect to point of positioning.
Referenced by IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.CopyDataToPositioner(), and IG.Gr3d.Graph3dManipulator.InitPositioner().
WindowShiftRelative
vec2 IG.Forms.WindowPositioner.WindowShiftRelative get set
Additional shift of positioned window relative to Window size.
Referenced by IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.CopyDataToPositioner(), and IG.Gr3d.Graph3dManipulator.InitPositioner().
WindowBounds
Rectangle IG.Forms.WindowPositioner.WindowBounds get
Bounds of the window to be positioned.
WindowShift
vec2 IG.Forms.WindowPositioner.WindowShift get
calculated additional shift of the positioned window that depends on that window.
MasterWindow
System Windows Forms Form IG.Forms.WindowPositioner.MasterWindow get set
Master window relative to which positioning is calculated.
Referenced by IG.Gr3d.Graph3dManipulator.InitPositioner(), IG.Forms.WindowPositioner.RememberPosition(), IG.Forms.WindowPositioner.RememberPositionEventHandler(), IG.Forms.WindowPositioner.StickEventHandler(), IG.Forms.WindowPositioner.StickToMaster(), IG.Forms.WindowPositioner.StopRememberPosition(), IG.Forms.WindowPositioner.UnStickFromMaster(), and IG.Forms.WindowPositioner.WindowPositioner().
MasterWindowAlignment
Alignment IG.Forms.WindowPositioner.MasterWindowAlignment get set
Alignment of the positioned window with respect to point of positioning.
Referenced by IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.CopyDataToPositioner(), and IG.Gr3d.Graph3dManipulator.InitPositioner().
MasterWindowShiftRelative
vec2 IG.Forms.WindowPositioner.MasterWindowShiftRelative get set
Additional shift of positioned window relative to Window size.
Referenced by IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.CopyDataToPositioner(), and IG.Gr3d.Graph3dManipulator.InitPositioner().
MasterWindowBounds
Rectangle IG.Forms.WindowPositioner.MasterWindowBounds get
Bounds of the window to be positioned.
MasterWindowShift
vec2 IG.Forms.WindowPositioner.MasterWindowShift get
calculated additional shift of the positioned window that depends on that window.
IsScreenDataInitialized
bool IG.Forms.WindowPositioner.IsScreenDataInitialized get set protected
Whwtheer screen data has been obtained or not.
Referenced by IG.Forms.WindowPositioner.InitScreenData(), and IG.Forms.WindowPositioner.InitScreenDataForced().
ScreenBounds
Rectangle IG.Forms.WindowPositioner.ScreenBounds get
Gets screen bounds.
Referenced by IG.Forms.WindowPositionerControl.LaunchWindows().
ScreenAlignment
Alignment IG.Forms.WindowPositioner.ScreenAlignment get set
Referenced by IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), and IG.Forms.WindowPositionerControl.CopyDataToPositioner().
ScreenShiftRelative
vec2 IG.Forms.WindowPositioner.ScreenShiftRelative get set
Additional shift of positioned window relative to screen size.
Referenced by IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), and IG.Forms.WindowPositionerControl.CopyDataToPositioner().
ScreenShift
vec2 IG.Forms.WindowPositioner.ScreenShift get
calculated additional shift of the position window that is bound to screen.
The documentation for this class was generated from the following file:
iglib/igforms/Utilities/WindowPositioner/WindowPositioner.cs