Doc: IGLib EXTENDED: NUnit.Engine.Services.ResultWriters.Tests.SchemaValidator Class Reference
NUnit.Engine.Services.ResultWriters.Tests.SchemaValidator Class Reference
Public Member Functions
SchemaValidator (string schemaFile)
bool Validate (string xmlFile)
bool Validate (TextReader rdr)
void ValidationEventHandle (object sender, ValidationEventArgs args)
Properties
string[] Errors [get]
Private Attributes
XmlReaderSettings settings
List< string > errors
Constructor & Destructor Documentation
SchemaValidator()
NUnit.Engine.Services.ResultWriters.Tests.SchemaValidator.SchemaValidator (string schemaFile) inline
References NUnit.Engine.Services.ResultWriters.Tests.SchemaValidator.settings, and NUnit.Engine.Services.ResultWriters.Tests.SchemaValidator.ValidationEventHandle().
Member Function Documentation
Validate() [1/2]
bool NUnit.Engine.Services.ResultWriters.Tests.SchemaValidator.Validate (string xmlFile) inline
Referenced by NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.runSchemaValidatorTest().
Validate() [2/2]
bool NUnit.Engine.Services.ResultWriters.Tests.SchemaValidator.Validate (TextReader rdr) inline
References NUnit.Engine.Services.ResultWriters.Tests.SchemaValidator.errors, and NUnit.Framework.Assert.Fail().
ValidationEventHandle()
void NUnit.Engine.Services.ResultWriters.Tests.SchemaValidator.ValidationEventHandle (object sender, ValidationEventArgs args) inline
References NUnit.Engine.Services.ResultWriters.Tests.SchemaValidator.errors.
Referenced by NUnit.Engine.Services.ResultWriters.Tests.SchemaValidator.SchemaValidator().
Member Data Documentation
settings
XmlReaderSettings NUnit.Engine.Services.ResultWriters.Tests.SchemaValidator.settings private
Referenced by NUnit.Engine.Services.ResultWriters.Tests.SchemaValidator.SchemaValidator().
errors
List<string> NUnit.Engine.Services.ResultWriters.Tests.SchemaValidator.errors private
Referenced by NUnit.Engine.Services.ResultWriters.Tests.SchemaValidator.Validate(), and NUnit.Engine.Services.ResultWriters.Tests.SchemaValidator.ValidationEventHandle().
Property Documentation
Errors
string [] NUnit.Engine.Services.ResultWriters.Tests.SchemaValidator.Errors get
Referenced by NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.runSchemaValidatorTest().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Services/ResultWriters/SchemaValidator.cs