Doc: IGLib EXTENDED: ImageViewer.MainForm Class Reference
ImageViewer.MainForm Class Reference
Public Member Functions
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void exitToolStripMenuItem_Click (object sender, EventArgs e)
void openToolStripMenuItem_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.OpenFileDialog openFileDialog
System.Windows.Forms.MenuStrip mainMenuStrip
System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem openToolStripMenuItem
System.Windows.Forms.ToolStripSeparator toolStripMenuItem1
System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem
System.Windows.Forms.StatusStrip statusStrip
System.Windows.Forms.SplitContainer splitContainer1
System.Windows.Forms.PropertyGrid propertyGrid
AForge.Controls.PictureBox pictureBox
Constructor & Destructor Documentation
MainForm()
ImageViewer.MainForm.MainForm () inline
References ImageViewer.MainForm.InitializeComponent().
Member Function Documentation
exitToolStripMenuItem_Click()
void ImageViewer.MainForm.exitToolStripMenuItem_Click (object sender, EventArgs e) inline private
Referenced by ImageViewer.MainForm.InitializeComponent().
openToolStripMenuItem_Click()
void ImageViewer.MainForm.openToolStripMenuItem_Click (object sender, EventArgs e) inline private
References AForge.Imaging.Formats.ImageDecoder.DecodeFromFile(), ImageViewer.MainForm.openFileDialog, ImageViewer.MainForm.pictureBox, and ImageViewer.MainForm.propertyGrid.
Referenced by ImageViewer.MainForm.InitializeComponent().
Dispose()
override void ImageViewer.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References ImageViewer.MainForm.components.
InitializeComponent()
void ImageViewer.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References ImageViewer.MainForm.exitToolStripMenuItem, ImageViewer.MainForm.exitToolStripMenuItem_Click(), ImageViewer.MainForm.fileToolStripMenuItem, ImageViewer.MainForm.mainMenuStrip, ImageViewer.MainForm.openFileDialog, ImageViewer.MainForm.openToolStripMenuItem, ImageViewer.MainForm.openToolStripMenuItem_Click(), ImageViewer.MainForm.pictureBox, ImageViewer.MainForm.propertyGrid, ImageViewer.MainForm.splitContainer1, ImageViewer.MainForm.statusStrip, and ImageViewer.MainForm.toolStripMenuItem1.
Referenced by ImageViewer.MainForm.MainForm().
Member Data Documentation
components
System.ComponentModel.IContainer ImageViewer.MainForm.components = null private
Required designer variable.
Referenced by ImageViewer.MainForm.Dispose().
openFileDialog
System.Windows.Forms.OpenFileDialog ImageViewer.MainForm.openFileDialog private
Referenced by ImageViewer.MainForm.InitializeComponent(), and ImageViewer.MainForm.openToolStripMenuItem_Click().
mainMenuStrip
System.Windows.Forms.MenuStrip ImageViewer.MainForm.mainMenuStrip private
Referenced by ImageViewer.MainForm.InitializeComponent().
fileToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem ImageViewer.MainForm.fileToolStripMenuItem private
Referenced by ImageViewer.MainForm.InitializeComponent().
openToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem ImageViewer.MainForm.openToolStripMenuItem private
Referenced by ImageViewer.MainForm.InitializeComponent().
toolStripMenuItem1
System.Windows.Forms.ToolStripSeparator ImageViewer.MainForm.toolStripMenuItem1 private
Referenced by ImageViewer.MainForm.InitializeComponent().
exitToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem ImageViewer.MainForm.exitToolStripMenuItem private
Referenced by ImageViewer.MainForm.InitializeComponent().
statusStrip
System.Windows.Forms.StatusStrip ImageViewer.MainForm.statusStrip private
Referenced by ImageViewer.MainForm.InitializeComponent().
splitContainer1
System.Windows.Forms.SplitContainer ImageViewer.MainForm.splitContainer1 private
Referenced by ImageViewer.MainForm.InitializeComponent().
propertyGrid
System.Windows.Forms.PropertyGrid ImageViewer.MainForm.propertyGrid private
Referenced by ImageViewer.MainForm.InitializeComponent(), and ImageViewer.MainForm.openToolStripMenuItem_Click().
pictureBox
AForge.Controls.PictureBox ImageViewer.MainForm.pictureBox private
Referenced by ImageViewer.MainForm.InitializeComponent(), and ImageViewer.MainForm.openToolStripMenuItem_Click().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Imaging/ImageViewer/MainForm.cs
shelldev/lib_ann/aforge.net/Samples/Imaging/ImageViewer/MainForm.Designer.cs