Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DSYEVD Class Reference
DotNumerics.LinearAlgebra.CSLapack.DSYEVD Class Reference
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DSYEVD (LSAME lsame, DLAMCH dlamch, DLANSY dlansy, ILAENV ilaenv, DLACPY dlacpy, DLASCL dlascl, DORMTR dormtr, DSCAL dscal, DSTEDC dstedc, DSTERF dsterf, DSYTRD dsytrd, XERBLA xerbla)
DSYEVD ()
void Run (string JOBZ, string UPLO, int N, ref double[] A, int offset_a, int LDA, ref double[] W, int offset_w, ref double[] WORK, int offset_work, int LWORK, ref int[] IWORK, int offset_iwork, int LIWORK, ref int INFO)
Private Attributes
LSAME _lsame
DLAMCH _dlamch
DLANSY _dlansy
ILAENV _ilaenv
DLACPY _dlacpy
DLASCL _dlascl
DORMTR _dormtr
DSCAL _dscal
DSTEDC _dstedc
DSTERF _dsterf
DSYTRD _dsytrd
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DSYEVD computes all eigenvalues and, optionally, eigenvectors of a real symmetric matrix A. If eigenvectors are desired, it uses a divide and conquer algorithm.
The divide and conquer algorithm makes very mild assumptions about floating point arithmetic. It will work on machines with a guard digit in add/subtract, or on those binary machines without guard digits which subtract like the Cray X-MP, Cray Y-MP, Cray C-90, or Cray-2. It could conceivably fail on hexadecimal or decimal machines without guard digits, but we know of none.
Because of large use of BLAS of level 3, DSYEVD needs N**2 more workspace than DSYEVX.
/summary>
Constructor & Destructor Documentation
DSYEVD() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DSYEVD.DSYEVD (LSAME lsame, DLAMCH dlamch, DLANSY dlansy, ILAENV ilaenv, DLACPY dlacpy, DLASCL dlascl, DORMTR dormtr, DSCAL dscal, DSTEDC dstedc, DSTERF dsterf, DSYTRD dsytrd, XERBLA xerbla) inline
DSYEVD() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DSYEVD.DSYEVD () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DSYEVD.Run (string JOBZ, string UPLO, int N, ref double[] A, int offset_a, int LDA, ref double[] W, int offset_w, ref double[] WORK, int offset_work, int LWORK, ref int[] IWORK, int offset_iwork, int LIWORK, ref int INFO) inline
Purpose
DSYEVD computes all eigenvalues and, optionally, eigenvectors of a real symmetric matrix A. If eigenvectors are desired, it uses a divide and conquer algorithm.
The divide and conquer algorithm makes very mild assumptions about floating point arithmetic. It will work on machines with a guard digit in add/subtract, or on those binary machines without guard digits which subtract like the Cray X-MP, Cray Y-MP, Cray C-90, or Cray-2. It could conceivably fail on hexadecimal or decimal machines without guard digits, but we know of none.
Because of large use of BLAS of level 3, DSYEVD needs N**2 more workspace than DSYEVX.
/summary>
Parameters
JOBZ (input) CHARACTER*1 = 'N': Compute eigenvalues only; = 'V': Compute eigenvalues and eigenvectors. /param>
Parameters
UPLO (input) CHARACTER*1 = 'U': Upper triangle of A is stored; = 'L': Lower triangle of A is stored. /param>
Parameters
N (input) INTEGER The order of the matrix A. N .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA, N) On entry, the symmetric matrix A. If UPLO = 'U', the leading N-by-N upper triangular part of A contains the upper triangular part of the matrix A. If UPLO = 'L', the leading N-by-N lower triangular part of A contains the lower triangular part of the matrix A. On exit, if JOBZ = 'V', then if INFO = 0, A contains the orthonormal eigenvectors of the matrix A. If JOBZ = 'N', then on exit the lower triangle (if UPLO='L') or the upper triangle (if UPLO='U') of A, including the diagonal, is destroyed. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,N). /param>
Parameters
W (output) DOUBLE PRECISION array, dimension (N) If INFO = 0, the eigenvalues in ascending order. /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (LWORK) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. If N .LE. 1, LWORK must be at least 1. If JOBZ = 'N' and N .GT. 1, LWORK must be at least 2*N+1. If JOBZ = 'V' and N .GT. 1, LWORK must be at least 1 + 6*N + 2*N**2.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal sizes of the WORK and IWORK arrays, returns these values as the first entries of the WORK and IWORK arrays, and no error message related to LWORK or LIWORK is issued by XERBLA. /param>
Parameters
IWORK (workspace/output) INTEGER array, dimension (MAX(1,LIWORK)) On exit, if INFO = 0, IWORK(1) returns the optimal LIWORK. /param>
Parameters
LIWORK (input) INTEGER The dimension of the array IWORK. If N .LE. 1, LIWORK must be at least 1. If JOBZ = 'N' and N .GT. 1, LIWORK must be at least 1. If JOBZ = 'V' and N .GT. 1, LIWORK must be at least 3 + 5*N.
If LIWORK = -1, then a workspace query is assumed; the routine only calculates the optimal sizes of the WORK and IWORK arrays, returns these values as the first entries of the WORK and IWORK arrays, and no error message related to LWORK or LIWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value .GT. 0: if INFO = i and JOBZ = 'N', then the algorithm failed to converge; i off-diagonal elements of an intermediate tridiagonal form did not converge to zero; if INFO = i and JOBZ = 'V', then the algorithm failed to compute an eigenvalue while working on the submatrix lying in rows and columns INFO/(N+1) through mod(INFO,N+1). /param>
References DotNumerics.LinearAlgebra.CSLapack.DSYEVD.ONE, DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTERF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANSY.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYTRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMTR.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEDC.Run(), and DotNumerics.LinearAlgebra.CSLapack.DSYEVD.ZERO.
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DSYEVD._lsame private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DSYEVD._dlamch private
_dlansy
DLANSY DotNumerics.LinearAlgebra.CSLapack.DSYEVD._dlansy private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DSYEVD._ilaenv private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DSYEVD._dlacpy private
_dlascl
DLASCL DotNumerics.LinearAlgebra.CSLapack.DSYEVD._dlascl private
_dormtr
DORMTR DotNumerics.LinearAlgebra.CSLapack.DSYEVD._dormtr private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DSYEVD._dscal private
_dstedc
DSTEDC DotNumerics.LinearAlgebra.CSLapack.DSYEVD._dstedc private
_dsterf
DSTERF DotNumerics.LinearAlgebra.CSLapack.DSYEVD._dsterf private
_dsytrd
DSYTRD DotNumerics.LinearAlgebra.CSLapack.DSYEVD._dsytrd private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DSYEVD._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DSYEVD.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYEVD.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DSYEVD.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYEVD.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dsyevd.cs