Doc: IGLib EXTENDED: NUnit.Engine.IServiceLocator Interface Reference
NUnit.Engine.IServiceLocator Interface Reference
IServiceLocator allows clients to locate any NUnit services for which the interface is referenced. In normal use, this linits it to those services using interfaces defined in the nunit.engine.api assembly.
Public Member Functions
T GetService< T > ()
Return a specified type of service
object GetService (Type serviceType)
Return a specified type of service
Detailed Description
IServiceLocator allows clients to locate any NUnit services for which the interface is referenced. In normal use, this linits it to those services using interfaces defined in the nunit.engine.api assembly.
Member Function Documentation
GetService< T >()
T NUnit.Engine.IServiceLocator.GetService< T > ()
Return a specified type of service
Implemented in NUnit.Engine.ServiceContext.
Type Constraints
T : class
GetService()
object NUnit.Engine.IServiceLocator.GetService (Type serviceType)
Return a specified type of service
Implemented in NUnit.Engine.ServiceContext.
Referenced by NUnit.Engine.Runners.AbstractTestRunner.AbstractTestRunner(), NUnit.Engine.Api.Tests.ServiceLocatorTests.CanAccessService(), NUnit.ConsoleRunner.ConsoleRunner.ConsoleRunner(), NUnit.Engine.Agents.RemoteTestAgent.Load(), NUnit.Engine.Runners.DirectTestRunner.LoadPackage(), NUnit.Engine.Runners.ProcessRunner.ProcessRunner(), NUnit.Engine.Runners.TestDomainRunner.TestDomainRunner(), and NUnit.Engine.Runners.MasterTestRunner.ValidatePackageSettings().
The documentation for this interface was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.api/IServiceLocator.cs