Doc: IGLib EXTENDED: NeuronDotNet.Core.Initializers.RandomFunction Class Reference
NeuronDotNet.Core.Initializers.RandomFunction Class Reference
An IInitializer using random function
Public Member Functions
RandomFunction ()
Creates a new random initialization function which uses random values from 0 to 1
RandomFunction (double minLimit, double maxLimit)
Creates a new random initialization function using random values between the specified limits.
RandomFunction (SerializationInfo info, StreamingContext context)
Deserialization Constructor
virtual void GetObjectData (SerializationInfo info, StreamingContext context)
Populates the serialization info with the data needed to serialize the initializer
void Initialize (ActivationLayer activationLayer)
Initializes bias values of activation neurons in the activation layer.
void Initialize (BackpropagationConnector connector)
Initializes weights of all backpropagation synapses in the backpropagation connector.
void Initialize (KohonenConnector connector)
Initializes weights of all spatial synapses in a Kohonen connector.
Properties
double MinLimit [get]
Gets the minimum random limit
double MaxLimit [get]
Gets the maximum random limit
Private Attributes
readonly double minLimit
readonly double maxLimit
Detailed Description
An IInitializer using random function
Constructor & Destructor Documentation
RandomFunction() [1/3]
NeuronDotNet.Core.Initializers.RandomFunction.RandomFunction () inline
Creates a new random initialization function which uses random values from 0 to 1
RandomFunction() [2/3]
NeuronDotNet.Core.Initializers.RandomFunction.RandomFunction (double minLimit, double maxLimit) inline
Creates a new random initialization function using random values between the specified limits.
Parameters
minLimit The minimum limit
maxLimit The maximum limit
References NeuronDotNet.Core.Initializers.RandomFunction.maxLimit, and NeuronDotNet.Core.Initializers.RandomFunction.minLimit.
RandomFunction() [3/3]
NeuronDotNet.Core.Initializers.RandomFunction.RandomFunction (SerializationInfo info, StreamingContext context) inline
Deserialization Constructor
Parameters
info Serialization information to deserialize and obtain the data
context Serialization context to use
Exceptions
ArgumentNullException If info is null
References NeuronDotNet.Core.Helper.ValidateNotNull().
Member Function Documentation
GetObjectData()
virtual void NeuronDotNet.Core.Initializers.RandomFunction.GetObjectData (SerializationInfo info, StreamingContext context) inline virtual
Populates the serialization info with the data needed to serialize the initializer
Parameters
info The serialization info to populate the data with
context The serialization context to use
Exceptions
ArgumentNullException If info is null
References NeuronDotNet.Core.Initializers.RandomFunction.maxLimit, NeuronDotNet.Core.Initializers.RandomFunction.minLimit, and NeuronDotNet.Core.Helper.ValidateNotNull().
Initialize() [1/3]
void NeuronDotNet.Core.Initializers.RandomFunction.Initialize (ActivationLayer activationLayer) inline
Initializes bias values of activation neurons in the activation layer.
Parameters
activationLayer The activation layer to initialize
Exceptions
ArgumentNullException If activationLayer is null
Implements NeuronDotNet.Core.IInitializer.
References NeuronDotNet.Core.Initializers.RandomFunction.maxLimit, NeuronDotNet.Core.Initializers.RandomFunction.minLimit, and NeuronDotNet.Core.Helper.ValidateNotNull().
Initialize() [2/3]
void NeuronDotNet.Core.Initializers.RandomFunction.Initialize (BackpropagationConnector connector) inline
Initializes weights of all backpropagation synapses in the backpropagation connector.
Parameters
connector The backpropagation connector to initialize.
Exceptions
ArgumentNullException If connector is null
Implements NeuronDotNet.Core.IInitializer.
References NeuronDotNet.Core.Initializers.RandomFunction.maxLimit, NeuronDotNet.Core.Initializers.RandomFunction.minLimit, NeuronDotNet.Core.Helper.ValidateNotNull(), and NeuronDotNet.Core.Backpropagation.BackpropagationSynapse.Weight.
Initialize() [3/3]
void NeuronDotNet.Core.Initializers.RandomFunction.Initialize (KohonenConnector connector) inline
Initializes weights of all spatial synapses in a Kohonen connector.
Parameters
connector The Kohonen connector to initialize.
Exceptions
ArgumentNullException If connector is null
Implements NeuronDotNet.Core.IInitializer.
References NeuronDotNet.Core.Initializers.RandomFunction.maxLimit, NeuronDotNet.Core.Initializers.RandomFunction.minLimit, NeuronDotNet.Core.Helper.ValidateNotNull(), and NeuronDotNet.Core.SOM.KohonenSynapse.Weight.
Member Data Documentation
minLimit
readonly double NeuronDotNet.Core.Initializers.RandomFunction.minLimit private
Referenced by NeuronDotNet.Core.Initializers.RandomFunction.GetObjectData(), NeuronDotNet.Core.Initializers.RandomFunction.Initialize(), and NeuronDotNet.Core.Initializers.RandomFunction.RandomFunction().
maxLimit
readonly double NeuronDotNet.Core.Initializers.RandomFunction.maxLimit private
Referenced by NeuronDotNet.Core.Initializers.RandomFunction.GetObjectData(), NeuronDotNet.Core.Initializers.RandomFunction.Initialize(), and NeuronDotNet.Core.Initializers.RandomFunction.RandomFunction().
Property Documentation
MinLimit
double NeuronDotNet.Core.Initializers.RandomFunction.MinLimit get
Gets the minimum random limit
Minimum limit to the random initial values
MaxLimit
double NeuronDotNet.Core.Initializers.RandomFunction.MaxLimit get
Gets the maximum random limit
Maximum limit to the random initial values
The documentation for this class was generated from the following file:
shelldev/lib/externalextended/NeuronDotNetGPL/source/Core/Initializers/RandomFunction.cs