Doc: IGLib EXTENDED: AForge.Robotics.Surveyor.SVS Class Reference
AForge.Robotics.Surveyor.SVS Class Reference
Manipulation of Surveyor SVS (Stereo Vision System) board.
Public Types
enum Camera { Camera.Left, Camera.Right }
Enumeration of SVS's Blackfin cameras.
enum ServosBank { ServosBank.Bank0, ServosBank.Bank1, ServosBank.Bank2, ServosBank.Bank3 }
Enumeration of SVS's servos' banks.
Public Member Functions
SVS ()
Initializes a new instance of the SVS class.
void Connect (string ipAddress)
Connect to SVS board.
void Disconnect ()
Disconnect from SVS device.
SRV1Camera GetCamera (Camera camera)
Get SVS's camera.
Bitmap GetImage (Camera camera)
Get single image from the SVS board.
SRV1 GetDirectAccessToSRV1 (Camera camera)
Get direct access to one of the SVS's SRV-1 Blackfin cameras.
string GetVersion ()
Get SVS board's firmware version string.
long GetRunningTime ()
Get SVS's board's running time.
void RunMotors (int leftSpeed, int rightSpeed, int duration)
Run motors connected to the SVS board.
void StopMotors ()
Stop both motors.
void EnableFailsafeMode (int leftSpeed, int rightSpeed)
Enables fail safe mode - setting motors' speed after timeout.
void DisableFailsafeMode ()
Disable fail safe mode.
void ControlMotors (SRV1.MotorCommand command)
Control motors connected to SVS board using predefined commands.
void ControlServos (ServosBank servosBank, int leftServo, int rightServo)
Direct servos control of the SVS board.
float[] UltrasonicPing (Camera camera)
Ping ultrasonic ranging modules.
byte I2CReadByte (Camera camera, byte deviceID, byte register)
Read byte from I2C device.
ushort I2CReadWord (Camera camera, byte deviceID, byte register)
Read word from I2C device.
void I2CWriteByte (Camera camera, byte deviceID, byte register, byte byteToWrite)
Write byte to I2C device.
void I2CWriteWord (Camera camera, byte deviceID, byte register, byte firstByteToWrite, byte secondByteToWrite)
Write two bytes to I2C device.
void SetQuality (int quality)
Set video quality for both cameras.
void SetResolution (SRV1.VideoResolution resolution)
Set video resolution for both cameras.
void FlipVideo (bool isFlipped)
Flip video capture for both cameras or not (for use with upside-down camera).
Properties
string HostAddress [get]
SVS's host address.
bool IsConnected [get]
Connection state.
Private Member Functions
SRV1 SafeGetCommunicator1 ()
SRV1 SafeGetCommunicator2 ()
Private Attributes
string hostAddress
SRV1 communicator1 = null
SRV1 communicator2 = null
SRV1Camera leftCamera
SRV1Camera rightCamera
string sync1 = "1"
string sync2 = "1"
Detailed Description
Manipulation of Surveyor SVS (Stereo Vision System) board.
The class allows to manipulate with Surveyor SVS board (stereo vision system) - getting video from both cameras, manipulating motors and servos, reading ultrasonic modules' values, sending direct commands, etc.
This class essentially creates to instances of SRV1 class to communicate with both SVS's cameras (ports 10001 and 10002 are used) and directs all calls through them.
Sample usage:
SVS svs = new SVS();
// connect to SVS board
svs.Connect("169.254.0.10");
// stop motors
svs.StopMotors();
// set video resolution and quality
svs.SetQuality(7);
svs.SetResolution(SRV1.VideoResolution.Small);
// get version string
string version = svs.GetVersion();
// get left camera
SRV1Camera camera = svs.GetCamera(SVS.Camera.Left);
// set NewFrame event handler
camera.NewFrame += new NewFrameEventHandler(video_NewFrame);
// start the video source
camera.Start();
// ...
private void video_NewFrame(object sender, NewFrameEventArgs eventArgs)
{
    // get new frame
    Bitmap bitmap = eventArgs.Frame;
    // process the frame
}
See also
SRV1Camera, SRV1
Member Enumeration Documentation
Camera
enum AForge.Robotics.Surveyor.SVS.Camera strong
Enumeration of SVS's Blackfin cameras.
Since SVS board consists of two SRV-1 Blackfin cameras, the enumeration is used by different methods to specify which one to access.
Enumerator
Left
Left camera (default port number is 10000).
Right
Right camera (default port number is 10001).
ServosBank
enum AForge.Robotics.Surveyor.SVS.ServosBank strong
Enumeration of SVS's servos' banks.
Enumerator
Bank0
First bank of the first (Camera.Left) SRV-1 Blackfin camera, timers 2 and 3 (marked as TMR2-1 and TMR3-1 on the SVS board). Note: these timers on SVS board are supposed for controlling motors by default (see RunMotors and ControlMotors), so use 0th servos bank only when you've done proper configuration changes on SVS side.
Bank1
Second bank of the first (Camera.Left) SRV-1 Blackfin camera, timers 6 and 7 (marked as TMR6-1 and TMR7-1 on the SVS board).
Bank2
First bank of the second (Camera.Right) SRV-1 Blackfin camera, timers 2 and 3 (marked as TMR2-2 and TMR3-2 on the SVS board).
Bank3
Second bank of the second (Camera.Right) SRV-1 Blackfin camera, timers 6 and 7 (marked as TMR6-2 and TMR7-2 on the SVS board).
Constructor & Destructor Documentation
SVS()
AForge.Robotics.Surveyor.SVS.SVS () inline
Initializes a new instance of the SVS class.
Member Function Documentation
Connect()
void AForge.Robotics.Surveyor.SVS.Connect (string ipAddress) inline
Connect to SVS board.
Parameters
ipAddress IP address of SVS board.
The method establishes connection to SVS board. If it succeeds then other methods can be used to manipulate the board.
<note>The method calls Disconnect before making any connection attempts to make sure previous connection is closed.</note>
Exceptions
ConnectionFailedException Failed connecting to SVS.
References AForge.Robotics.Surveyor.SVS.communicator1, AForge.Robotics.Surveyor.SVS.communicator2, AForge.Robotics.Surveyor.SRV1.Connect(), AForge.Robotics.Surveyor.SVS.Disconnect(), AForge.Robotics.Surveyor.SVS.hostAddress, AForge.Robotics.Surveyor.SVS.sync1, and AForge.Robotics.Surveyor.SVS.sync2.
Referenced by SVSTest.MainForm.Connect().
Disconnect()
void AForge.Robotics.Surveyor.SVS.Disconnect () inline
Disconnect from SVS device.
The method disconnects from SVS board making all other methods unavailable (except Connect method). In the case if user obtained instance of left or right camera using GetCamera method, the video will be stopped automatically (and those SRV1Camera instances should be discarded).
References AForge.Robotics.Surveyor.SVS.communicator1, AForge.Robotics.Surveyor.SVS.communicator2, AForge.Robotics.Surveyor.SRV1.Disconnect(), AForge.Robotics.Surveyor.SVS.hostAddress, AForge.Robotics.Surveyor.SRV1Camera.IsRunning, AForge.Robotics.Surveyor.SVS.leftCamera, AForge.Robotics.Surveyor.SVS.rightCamera, AForge.Robotics.Surveyor.SRV1Camera.SignalToStop(), AForge.Robotics.Surveyor.SRV1Camera.Stop(), AForge.Robotics.Surveyor.SVS.sync1, and AForge.Robotics.Surveyor.SVS.sync2.
Referenced by AForge.Robotics.Surveyor.SVS.Connect(), and SVSTest.MainForm.Disconnect().
GetCamera()
SRV1Camera AForge.Robotics.Surveyor.SVS.GetCamera (Camera camera) inline
Get SVS's camera.
Parameters
camera SVS camera to get.
Returns
Returns SRV1Camera object, which is connected to SVS's Blackfin camera. Use SRV1Camera.Start method to start the camera and start receiving video frames from it.
The method provides an instance of SRV1Camera, which can be used for receiving continuous video frames from the SVS board. In the case if only one image is required, the GetImage method can be used.
Sample usage:
// get SRV-1 camera
SRV1Camera camera = svs.GetCamera(SVS.Camera.Left);
// set NewFrame event handler
camera.NewFrame += new NewFrameEventHandler(video_NewFrame);
// start the video source
camera.Start();
// ...
private void video_NewFrame(object sender, NewFrameEventArgs eventArgs)
{
    // get new frame
    Bitmap bitmap = eventArgs.Frame;
    // process the frame
}
Exceptions
NotConnectedException Not connected to SVS. Connect to SVS board before using this method.
References AForge.Robotics.Surveyor.SRV1.GetCamera(), AForge.Robotics.Surveyor.SVS.leftCamera, AForge.Robotics.Surveyor.SVS.rightCamera, AForge.Robotics.Surveyor.SVS.SafeGetCommunicator1(), and AForge.Robotics.Surveyor.SVS.SafeGetCommunicator2().
Referenced by SVSTest.MainForm.Connect().
GetImage()
Bitmap AForge.Robotics.Surveyor.SVS.GetImage (Camera camera) inline
Get single image from the SVS board.
Parameters
camera Camera to get image from.
Returns
Returns image received from the specified camera of the SVS board or null if failed decoding provided response.
The method provides single video frame retrieved from the specified SVS's camera. However in many cases it is required to receive video frames one after another, so the GetCamera method is more preferred for continuous video frames.
Exceptions
NotConnectedException Not connected to SRV-1. Connect to SRV-1 before using this method.
ConnectionLostException Connection lost or communicaton failure. Try to reconnect.
References AForge.Robotics.Surveyor.SRV1.GetImage(), AForge.Robotics.Surveyor.SVS.SafeGetCommunicator1(), and AForge.Robotics.Surveyor.SVS.SafeGetCommunicator2().
GetDirectAccessToSRV1()
SRV1 AForge.Robotics.Surveyor.SVS.GetDirectAccessToSRV1 (Camera camera) inline
Get direct access to one of the SVS's SRV-1 Blackfin cameras.
Parameters
camera SRV-1 Blackfin to get direct access to.
Returns
Returns SRV1 object connected to the requested SRV-1 Blackfin camera.
The method provides direct access to one of the SVS's SRV-1 Blackfin cameras, so it could be possible to send some direct commands to it using SRV1.Send and SRV1.SendAndReceive methods.
Exceptions
NotConnectedException Not connected to SVS. Connect to SVS board before using this method.
References AForge.Robotics.Surveyor.SVS.SafeGetCommunicator1(), and AForge.Robotics.Surveyor.SVS.SafeGetCommunicator2().
Referenced by AForge.Robotics.Surveyor.SVS.I2CReadByte(), AForge.Robotics.Surveyor.SVS.I2CReadWord(), AForge.Robotics.Surveyor.SVS.I2CWriteByte(), AForge.Robotics.Surveyor.SVS.I2CWriteWord(), and AForge.Robotics.Surveyor.SVS.UltrasonicPing().
GetVersion()
string AForge.Robotics.Surveyor.SVS.GetVersion () inline
Get SVS board's firmware version string.
Returns
Returns SVS's version string.
Exceptions
NotConnectedException Not connected to SVS. Connect to SVS board before using this method.
ConnectionLostException Connection lost or communicaton failure. Try to reconnect.
References AForge.Robotics.Surveyor.SRV1.GetVersion(), and AForge.Robotics.Surveyor.SVS.SafeGetCommunicator1().
Referenced by SVSTest.MainForm.Connect().
GetRunningTime()
long AForge.Robotics.Surveyor.SVS.GetRunningTime () inline
Get SVS's board's running time.
Returns
Returns SVS boards running time in milliseconds.
Exceptions
NotConnectedException Not connected to SVS. Connect to SVS board before using this method.
ConnectionLostException Connection lost or communicaton failure. Try to reconnect.
ApplicationException Failed parsing response from SVS.
References AForge.Robotics.Surveyor.SRV1.GetRunningTime(), and AForge.Robotics.Surveyor.SVS.SafeGetCommunicator1().
RunMotors()
void AForge.Robotics.Surveyor.SVS.RunMotors (int leftSpeed, int rightSpeed, int duration) inline
Run motors connected to the SVS board.
Parameters
leftSpeed Left motor's speed, [-127, 127].
rightSpeed Right motor's speed, [-127, 127].
duration Time duration to run motors measured in number of 10 milliseconds (0 for infinity), [0, 255].
The method sets specified speed to both motors connected to the SVS board. The maximum absolute speed equals to 127, but the sign specifies direction of motor's rotation (forward or backward).
Exceptions
NotConnectedException Not connected to SVS. Connect to SVS board before using this method.
References AForge.Robotics.Surveyor.SRV1.RunMotors(), and AForge.Robotics.Surveyor.SVS.SafeGetCommunicator1().
Referenced by SVSTest.MainForm.DriveMotors(), and AForge.Robotics.Surveyor.SVS.StopMotors().
StopMotors()
void AForge.Robotics.Surveyor.SVS.StopMotors () inline
Stop both motors.
The method stops both motors connected to the SVS board by calling RunMotors method specifying 0 for motors' speed.
Exceptions
NotConnectedException Not connected to SVS. Connect to SVS board before using this method.
References AForge.Robotics.Surveyor.SVS.RunMotors().
Referenced by SVSTest.MainForm.Disconnect(), and SVSTest.MainForm.srvDriverControl_SrvDrivingCommand().
EnableFailsafeMode()
void AForge.Robotics.Surveyor.SVS.EnableFailsafeMode (int leftSpeed, int rightSpeed) inline
Enables fail safe mode - setting motors' speed after timeout.
Parameters
leftSpeed Left motor's speed, [-127, 127].
rightSpeed Right motor's speed, [-127, 127].
In the case if fail safe mode is enabled and no commands are received by SVS robot withing 2 seconds, motors' speed will be set to the specified values. The command is very useful to instruct robot to stop if no other commands were sent within 2 last seconds (probably lost connection).
Exceptions
NotConnectedException Not connected to SVS. Connect to SVS board before using this method.
References AForge.Robotics.Surveyor.SRV1.EnableFailsafeMode(), and AForge.Robotics.Surveyor.SVS.SafeGetCommunicator1().
Referenced by SVSTest.MainForm.Connect().
DisableFailsafeMode()
void AForge.Robotics.Surveyor.SVS.DisableFailsafeMode () inline
Disable fail safe mode.
The method disable fail safe mode, which was set using EnableFailsafeMode method.
Exceptions
NotConnectedException Not connected to SVS. Connect to SVS board before using this method.
References AForge.Robotics.Surveyor.SRV1.DisableFailsafeMode(), and AForge.Robotics.Surveyor.SVS.SafeGetCommunicator1().
ControlMotors()
void AForge.Robotics.Surveyor.SVS.ControlMotors (SRV1.MotorCommand command) inline
Control motors connected to SVS board using predefined commands.
Parameters
command Motor command to send to the SVS board.
<note>Controlling SVS motors with this method is only available after at least one direct motor command is sent, which is done using StopMotors or RunMotors methods.</note>
Exceptions
NotConnectedException Not connected to SVS. Connect to SVS board before using this method.
References AForge.Robotics.Surveyor.SRV1.ControlMotors(), and AForge.Robotics.Surveyor.SVS.SafeGetCommunicator1().
Referenced by SVSTest.MainForm.srvDriverControl_SrvDrivingCommand().
ControlServos()
void AForge.Robotics.Surveyor.SVS.ControlServos (ServosBank servosBank, int leftServo, int rightServo) inline
Direct servos control of the SVS board.
Parameters
servosBank SVS's servo bank to control.
leftServo Left servo setting, [0, 100].
rightServo Right servo setting, [0, 100].
The method performs servos control of the SVS board. For ServosBank.Bank1 and ServosBank.Bank3 banks it calls SRV1.ControlServos method for the corresponding SRV-1 Blackfin camera. In the case of ServosBank.Bank0 or ServosBank.Bank2, the method sends 'Sab' SRV-1 command (see SRV-1 Control Protocol) to the appropriate SRV-1 Blackfin camera.
Exceptions
NotConnectedException Not connected to SVS. Connect to SVS board before using this method.
References AForge.Robotics.Surveyor.SRV1.ControlServos(), AForge.Robotics.Surveyor.SVS.SafeGetCommunicator1(), AForge.Robotics.Surveyor.SVS.SafeGetCommunicator2(), and AForge.Robotics.Surveyor.SRV1.Send().
UltrasonicPing()
float [] AForge.Robotics.Surveyor.SVS.UltrasonicPing (Camera camera) inline
Ping ultrasonic ranging modules.
Parameters
camera SRV-1 Blackfin camera to check ultrasonic modules values.
Returns
Returns array of ranges (distances) obtained from ultrasonic sensors. The ranges are measured in inches.
The method calls SRV1.UltrasonicPing for the specified SRV-1 Blackfin camera.
Exceptions
NotConnectedException Not connected to SVS. Connect to SVS board before using this method.
ConnectionLostException Connection lost or communicaton failure. Try to reconnect.
ApplicationException Failed parsing response from SVS.
References AForge.Robotics.Surveyor.SVS.GetDirectAccessToSRV1(), and AForge.Robotics.Surveyor.SRV1.UltrasonicPing().
I2CReadByte()
byte AForge.Robotics.Surveyor.SVS.I2CReadByte (Camera camera, byte deviceID, byte register) inline
Read byte from I2C device.
Parameters
camera SRV-1 Blackfin camera to access I2C device on.
deviceID I2C device ID (7 bit notation).
register I2C device register to read.
Returns
Returns byte read from the specified register of the specified I2C device.
<note>The IC2 device ID should be specified in 7 bit notation. This means that low bit of the ID is not used for specifying read/write mode as in 8 bit notation. For example, if I2C device IDs are 0x44 for reading and 0x45 for writing in 8 bit notation, then it equals to 0x22 device ID in 7 bit notation. </note>
Exceptions
NotConnectedException Not connected to SVS. Connect to SVS board before using this method.
ConnectionLostException Connection lost or communicaton failure. Try to reconnect.
ApplicationException Failed parsing response from SRV-1.
References AForge.Robotics.Surveyor.SVS.GetDirectAccessToSRV1(), and AForge.Robotics.Surveyor.SRV1.I2CReadByte().
I2CReadWord()
ushort AForge.Robotics.Surveyor.SVS.I2CReadWord (Camera camera, byte deviceID, byte register) inline
Read word from I2C device.
Parameters
camera SRV-1 Blackfin camera to access I2C device on.
deviceID I2C device ID (7 bit notation).
register I2C device register to read.
Returns
Returns word read from the specified register of the specified I2C device.
<note>The IC2 device ID should be specified in 7 bit notation. This means that low bit of the ID is not used for specifying read/write mode as in 8 bit notation. For example, if I2C device IDs are 0x44 for reading and 0x45 for writing in 8 bit notation, then it equals to 0x22 device ID in 7 bit notation. </note>
Exceptions
NotConnectedException Not connected to SVS. Connect to SVS board before using this method.
ConnectionLostException Connection lost or communicaton failure. Try to reconnect.
ApplicationException Failed parsing response from SRV-1.
References AForge.Robotics.Surveyor.SVS.GetDirectAccessToSRV1(), and AForge.Robotics.Surveyor.SRV1.I2CReadWord().
I2CWriteByte()
void AForge.Robotics.Surveyor.SVS.I2CWriteByte (Camera camera, byte deviceID, byte register, byte byteToWrite) inline
Write byte to I2C device.
Parameters
camera SRV-1 Blackfin camera to access I2C device on.
deviceID I2C device ID (7 bit notation).
register I2C device register to write to.
byteToWrite Byte to write to the specified register of the specified device.
<note>The IC2 device ID should be specified in 7 bit notation. This means that low bit of the ID is not used for specifying read/write mode as in 8 bit notation. For example, if I2C device IDs are 0x44 for reading and 0x45 for writing in 8 bit notation, then it equals to 0x22 device ID in 7 bit notation. </note>
Exceptions
NotConnectedException Not connected to SVS. Connect to SVS board before using this method.
ConnectionLostException Connection lost or communicaton failure. Try to reconnect.
References AForge.Robotics.Surveyor.SVS.GetDirectAccessToSRV1(), and AForge.Robotics.Surveyor.SRV1.I2CWriteByte().
I2CWriteWord()
void AForge.Robotics.Surveyor.SVS.I2CWriteWord (Camera camera, byte deviceID, byte register, byte firstByteToWrite, byte secondByteToWrite) inline
Write two bytes to I2C device.
Parameters
camera SRV-1 Blackfin camera to access I2C device on.
deviceID I2C device ID (7 bit notation).
register I2C device register to write to.
firstByteToWrite First byte to write to the specified register of the specified device.
secondByteToWrite Second byte to write to the specified register of the specified device.
<note>The IC2 device ID should be specified in 7 bit notation. This means that low bit of the ID is not used for specifying read/write mode as in 8 bit notation. For example, if I2C device IDs are 0x44 for reading and 0x45 for writing in 8 bit notation, then it equals to 0x22 device ID in 7 bit notation. </note>
Exceptions
NotConnectedException Not connected to SVS. Connect to SVS board before using this method.
ConnectionLostException Connection lost or communicaton failure. Try to reconnect.
References AForge.Robotics.Surveyor.SVS.GetDirectAccessToSRV1(), and AForge.Robotics.Surveyor.SRV1.I2CWriteWord().
SetQuality()
void AForge.Robotics.Surveyor.SVS.SetQuality (int quality) inline
Set video quality for both cameras.
Parameters
quality Video quality to set, [1, 8].
The method sets video quality for both SVS cameras, which is specified in [1, 8] range - 1 is the highest quality level, 8 is the lowest quality level.
<note>Setting higher quality level and resolution may increase delays for other requests sent to SVS. So if robot is used not only for video, but also for controlling servos/motors, and higher response level is required, then do not set very high quality and resolution. </note>
Exceptions
NotConnectedException Not connected to SVS. Connect to SVS board before using this method.
ArgumentOutOfRangeException Invalid quality level was specified.
References AForge.Robotics.Surveyor.SVS.SafeGetCommunicator1(), AForge.Robotics.Surveyor.SVS.SafeGetCommunicator2(), and AForge.Robotics.Surveyor.SRV1.SetQuality().
Referenced by SVSTest.MainForm.Connect(), and SVSTest.MainForm.qualityCombo_SelectedIndexChanged().
SetResolution()
void AForge.Robotics.Surveyor.SVS.SetResolution (SRV1.VideoResolution resolution) inline
Set video resolution for both cameras.
Parameters
resolution Video resolution to set.
<note>Setting higher quality level and resolution may increase delays for other requests sent to SVS. So if robot is used not only for video, but also for controlling servos/motors, and higher response level is required, then do not set very high quality and resolution. </note>
Exceptions
NotConnectedException Not connected to SVS. Connect to SVS board before using this method.
References AForge.Robotics.Surveyor.SVS.SafeGetCommunicator1(), AForge.Robotics.Surveyor.SVS.SafeGetCommunicator2(), and AForge.Robotics.Surveyor.SRV1.SetResolution().
Referenced by SVSTest.MainForm.Connect(), and SVSTest.MainForm.resolutionCombo_SelectedIndexChanged().
FlipVideo()
void AForge.Robotics.Surveyor.SVS.FlipVideo (bool isFlipped) inline
Flip video capture for both cameras or not (for use with upside-down camera).
Parameters
isFlipped Specifies if video should be flipped (true), or not (false).
Exceptions
NotConnectedException Not connected to SVS. Connect to SVS board before using this method.
References AForge.Robotics.Surveyor.SRV1.FlipVideo(), AForge.Robotics.Surveyor.SVS.SafeGetCommunicator1(), and AForge.Robotics.Surveyor.SVS.SafeGetCommunicator2().
Referenced by SVSTest.MainForm.Connect().
SafeGetCommunicator1()
SRV1 AForge.Robotics.Surveyor.SVS.SafeGetCommunicator1 () inline private
References AForge.Robotics.Surveyor.SVS.communicator1, and AForge.Robotics.Surveyor.SVS.sync1.
Referenced by AForge.Robotics.Surveyor.SVS.ControlMotors(), AForge.Robotics.Surveyor.SVS.ControlServos(), AForge.Robotics.Surveyor.SVS.DisableFailsafeMode(), AForge.Robotics.Surveyor.SVS.EnableFailsafeMode(), AForge.Robotics.Surveyor.SVS.FlipVideo(), AForge.Robotics.Surveyor.SVS.GetCamera(), AForge.Robotics.Surveyor.SVS.GetDirectAccessToSRV1(), AForge.Robotics.Surveyor.SVS.GetImage(), AForge.Robotics.Surveyor.SVS.GetRunningTime(), AForge.Robotics.Surveyor.SVS.GetVersion(), AForge.Robotics.Surveyor.SVS.RunMotors(), AForge.Robotics.Surveyor.SVS.SetQuality(), and AForge.Robotics.Surveyor.SVS.SetResolution().
SafeGetCommunicator2()
SRV1 AForge.Robotics.Surveyor.SVS.SafeGetCommunicator2 () inline private
References AForge.Robotics.Surveyor.SVS.communicator2, and AForge.Robotics.Surveyor.SVS.sync2.
Referenced by AForge.Robotics.Surveyor.SVS.ControlServos(), AForge.Robotics.Surveyor.SVS.FlipVideo(), AForge.Robotics.Surveyor.SVS.GetCamera(), AForge.Robotics.Surveyor.SVS.GetDirectAccessToSRV1(), AForge.Robotics.Surveyor.SVS.GetImage(), AForge.Robotics.Surveyor.SVS.SetQuality(), and AForge.Robotics.Surveyor.SVS.SetResolution().
Member Data Documentation
hostAddress
string AForge.Robotics.Surveyor.SVS.hostAddress private
Referenced by AForge.Robotics.Surveyor.SVS.Connect(), and AForge.Robotics.Surveyor.SVS.Disconnect().
communicator1
SRV1 AForge.Robotics.Surveyor.SVS.communicator1 = null private
Referenced by AForge.Robotics.Surveyor.SVS.Connect(), AForge.Robotics.Surveyor.SVS.Disconnect(), and AForge.Robotics.Surveyor.SVS.SafeGetCommunicator1().
communicator2
SRV1 AForge.Robotics.Surveyor.SVS.communicator2 = null private
Referenced by AForge.Robotics.Surveyor.SVS.Connect(), AForge.Robotics.Surveyor.SVS.Disconnect(), and AForge.Robotics.Surveyor.SVS.SafeGetCommunicator2().
leftCamera
SRV1Camera AForge.Robotics.Surveyor.SVS.leftCamera private
Referenced by AForge.Robotics.Surveyor.SVS.Disconnect(), and AForge.Robotics.Surveyor.SVS.GetCamera().
rightCamera
SRV1Camera AForge.Robotics.Surveyor.SVS.rightCamera private
Referenced by AForge.Robotics.Surveyor.SVS.Disconnect(), and AForge.Robotics.Surveyor.SVS.GetCamera().
sync1
string AForge.Robotics.Surveyor.SVS.sync1 = "1" private
Referenced by AForge.Robotics.Surveyor.SVS.Connect(), AForge.Robotics.Surveyor.SVS.Disconnect(), and AForge.Robotics.Surveyor.SVS.SafeGetCommunicator1().
sync2
string AForge.Robotics.Surveyor.SVS.sync2 = "1" private
Referenced by AForge.Robotics.Surveyor.SVS.Connect(), AForge.Robotics.Surveyor.SVS.Disconnect(), and AForge.Robotics.Surveyor.SVS.SafeGetCommunicator2().
Property Documentation
HostAddress
string AForge.Robotics.Surveyor.SVS.HostAddress get
SVS's host address.
The property keeps SVS's IP address if the class is connected to SVS board, otherwise it equals to null..
IsConnected
bool AForge.Robotics.Surveyor.SVS.IsConnected get
Connection state.
The property equals to true if the class is connected to SVS board, otherwise it equals to false.
<note>The property is not updated by the class, when connection was lost or communication failure was detected (which results into ConnectionLostException exception). The property only shows status of Connect method.</note>
Referenced by SVSTest.MainForm.Disconnect(), SVSTest.MainForm.DriveMotors(), SVSTest.MainForm.qualityCombo_SelectedIndexChanged(), SVSTest.MainForm.resolutionCombo_SelectedIndexChanged(), and SVSTest.MainForm.srvDriverControl_SrvDrivingCommand().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Robotics.Surveyor/SVS.cs