Doc: IGLib EXTENDED: NUnit.Framework.Internal.Commands.SetUpTearDownItem Class Reference
NUnit.Framework.Internal.Commands.SetUpTearDownItem Class Reference
SetUpTearDownItem holds the setup and teardown methods for a single level of the inheritance hierarchy.
Public Member Functions
SetUpTearDownItem (IList< MethodInfo > setUpMethods, IList< MethodInfo > tearDownMethods)
Construct a SetUpTearDownNode
void RunSetUp (TestExecutionContext context)
Run SetUp on this level.
void RunTearDown (TestExecutionContext context)
Run TearDown for this level.
Properties
bool HasMethods [get]
Returns true if this level has any methods at all. This flag is used to discard levels that do nothing.
Private Member Functions
void RunSetUpOrTearDownMethod (TestExecutionContext context, MethodInfo method)
object RunNonAsyncMethod (MethodInfo method, TestExecutionContext context)
Private Attributes
IList< MethodInfo > _setUpMethods
IList< MethodInfo > _tearDownMethods
bool _setUpWasRun
Detailed Description
SetUpTearDownItem holds the setup and teardown methods for a single level of the inheritance hierarchy.
Constructor & Destructor Documentation
SetUpTearDownItem()
NUnit.Framework.Internal.Commands.SetUpTearDownItem.SetUpTearDownItem (IList< MethodInfo > setUpMethods, IList< MethodInfo > tearDownMethods) inline
Construct a SetUpTearDownNode
Parameters
setUpMethods A list of setup methods for this level
tearDownMethods A list teardown methods for this level
References NUnit.Framework.Internal.Commands.SetUpTearDownItem._setUpMethods, and NUnit.Framework.Internal.Commands.SetUpTearDownItem._tearDownMethods.
Member Function Documentation
RunSetUp()
void NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp (TestExecutionContext context) inline
Run SetUp on this level.
Parameters
context The execution context to use for running.
References NUnit.Framework.Internal.Commands.SetUpTearDownItem._setUpMethods, NUnit.Framework.Internal.Commands.SetUpTearDownItem._setUpWasRun, and NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUpOrTearDownMethod().
RunTearDown()
void NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunTearDown (TestExecutionContext context) inline
Run TearDown for this level.
Parameters
context
References NUnit.Framework.Internal.Commands.SetUpTearDownItem._setUpWasRun, NUnit.Framework.Internal.Commands.SetUpTearDownItem._tearDownMethods, NUnit.Framework.Internal.TestExecutionContext.CurrentResult, NUnit.Framework.Internal.TestResult.RecordTearDownException(), and NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUpOrTearDownMethod().
RunSetUpOrTearDownMethod()
void NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUpOrTearDownMethod (TestExecutionContext context, MethodInfo method) inline private
References NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunNonAsyncMethod().
Referenced by NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(), and NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunTearDown().
RunNonAsyncMethod()
object NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunNonAsyncMethod (MethodInfo method, TestExecutionContext context) inline private
References NUnit.Framework.Internal.Reflect.InvokeMethod(), and NUnit.Framework.Internal.TestExecutionContext.TestObject.
Referenced by NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUpOrTearDownMethod().
Member Data Documentation
_setUpMethods
IList<MethodInfo> NUnit.Framework.Internal.Commands.SetUpTearDownItem._setUpMethods private
Referenced by NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(), and NUnit.Framework.Internal.Commands.SetUpTearDownItem.SetUpTearDownItem().
_tearDownMethods
IList<MethodInfo> NUnit.Framework.Internal.Commands.SetUpTearDownItem._tearDownMethods private
Referenced by NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunTearDown(), and NUnit.Framework.Internal.Commands.SetUpTearDownItem.SetUpTearDownItem().
_setUpWasRun
bool NUnit.Framework.Internal.Commands.SetUpTearDownItem._setUpWasRun private
Referenced by NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunSetUp(), and NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunTearDown().
Property Documentation
HasMethods
bool NUnit.Framework.Internal.Commands.SetUpTearDownItem.HasMethods get
Returns true if this level has any methods at all. This flag is used to discard levels that do nothing.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/Commands/SetUpTearDownItem.cs