Doc: IGLib EXTENDED: NUnit.Framework.Attributes.ParameterizedTestFixtureTests Class Reference
NUnit.Framework.Attributes.ParameterizedTestFixtureTests Class Reference
Public Member Functions
void CanSpecifyCategory ()
void CanSpecifyMultipleCategories ()
Member Function Documentation
CanSpecifyCategory()
void NUnit.Framework.Attributes.ParameterizedTestFixtureTests.CanSpecifyCategory () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.PropertyNames.Category, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeFixture(), and NUnit.Framework.Internal.Test.Properties.
CanSpecifyMultipleCategories()
void NUnit.Framework.Attributes.ParameterizedTestFixtureTests.CanSpecifyMultipleCategories () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.PropertyNames.Category, NUnit.TestUtilities.TestBuilder.MakeFixture(), and NUnit.Framework.Internal.Test.Properties.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/ParameterizedTestFixtureTests.cs