Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DBDSQR Class Reference
DotNumerics.LinearAlgebra.CSLapack.DBDSQR Class Reference
– LAPACK routine (version 3.1.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. January 2007
Public Member Functions
DBDSQR (LSAME lsame, DLAMCH dlamch, DLARTG dlartg, DLAS2 dlas2, DLASQ1 dlasq1, DLASR dlasr, DLASV2 dlasv2, DROT drot, DSCAL dscal, DSWAP dswap, XERBLA xerbla)
DBDSQR ()
void Run (string UPLO, int N, int NCVT, int NRU, int NCC, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] VT, int offset_vt, int LDVT, ref double[] U, int offset_u, int LDU, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
LSAME _lsame
DLAMCH _dlamch
DLARTG _dlartg
DLAS2 _dlas2
DLASQ1 _dlasq1
DLASR _dlasr
DLASV2 _dlasv2
DROT _drot
DSCAL _dscal
DSWAP _dswap
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
const double NEGONE = - 1.0E0
const double HNDRTH = 0.01E0
const double TEN = 10.0E0
const double HNDRD = 100.0E0
const double MEIGTH = - 0.125E0
const int MAXITR = 6
Detailed Description
– LAPACK routine (version 3.1.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. January 2007
Purpose
DBDSQR computes the singular values and, optionally, the right and/or left singular vectors from the singular value decomposition (SVD) of a real N-by-N (upper or lower) bidiagonal matrix B using the implicit zero-shift QR algorithm. The SVD of B has the form
B = Q * S * P**T
where S is the diagonal matrix of singular values, Q is an orthogonal matrix of left singular vectors, and P is an orthogonal matrix of right singular vectors. If left singular vectors are requested, this subroutine actually returns U*Q instead of Q, and, if right singular vectors are requested, this subroutine returns P**T*VT instead of P**T, for given real input matrices U and VT. When U and VT are the orthogonal matrices that reduce a general matrix A to bidiagonal form: A = U*B*VT, as computed by DGEBRD, then
A = (U*Q) * S * (P**T*VT)
is the SVD of A. Optionally, the subroutine may also compute Q**T*C for a given real input matrix C.
See "Computing Small Singular Values of Bidiagonal Matrices With Guaranteed High Relative Accuracy," by J. Demmel and W. Kahan, LAPACK Working Note #3 (or SIAM J. Sci. Statist. Comput. vol. 11, no. 5, pp. 873-912, Sept 1990) and "Accurate singular values and differential qd algorithms," by B. Parlett and V. Fernando, Technical Report CPAM-554, Mathematics Department, University of California at Berkeley, July 1992 for a detailed description of the algorithm.
/summary>
Constructor & Destructor Documentation
DBDSQR() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DBDSQR.DBDSQR (LSAME lsame, DLAMCH dlamch, DLARTG dlartg, DLAS2 dlas2, DLASQ1 dlasq1, DLASR dlasr, DLASV2 dlasv2, DROT drot, DSCAL dscal, DSWAP dswap, XERBLA xerbla) inline
DBDSQR() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DBDSQR.DBDSQR () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run (string UPLO, int N, int NCVT, int NRU, int NCC, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] VT, int offset_vt, int LDVT, ref double[] U, int offset_u, int LDU, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
DBDSQR computes the singular values and, optionally, the right and/or left singular vectors from the singular value decomposition (SVD) of a real N-by-N (upper or lower) bidiagonal matrix B using the implicit zero-shift QR algorithm. The SVD of B has the form
B = Q * S * P**T
where S is the diagonal matrix of singular values, Q is an orthogonal matrix of left singular vectors, and P is an orthogonal matrix of right singular vectors. If left singular vectors are requested, this subroutine actually returns U*Q instead of Q, and, if right singular vectors are requested, this subroutine returns P**T*VT instead of P**T, for given real input matrices U and VT. When U and VT are the orthogonal matrices that reduce a general matrix A to bidiagonal form: A = U*B*VT, as computed by DGEBRD, then
A = (U*Q) * S * (P**T*VT)
is the SVD of A. Optionally, the subroutine may also compute Q**T*C for a given real input matrix C.
See "Computing Small Singular Values of Bidiagonal Matrices With Guaranteed High Relative Accuracy," by J. Demmel and W. Kahan, LAPACK Working Note #3 (or SIAM J. Sci. Statist. Comput. vol. 11, no. 5, pp. 873-912, Sept 1990) and "Accurate singular values and differential qd algorithms," by B. Parlett and V. Fernando, Technical Report CPAM-554, Mathematics Department, University of California at Berkeley, July 1992 for a detailed description of the algorithm.
/summary>
Parameters
UPLO (input) CHARACTER*1 = 'U': B is upper bidiagonal; = 'L': B is lower bidiagonal. /param>
Parameters
N (input) INTEGER The order of the matrix B. N .GE. 0. /param>
Parameters
NCVT (input) INTEGER The number of columns of the matrix VT. NCVT .GE. 0. /param>
Parameters
NRU (input) INTEGER The number of rows of the matrix U. NRU .GE. 0. /param>
Parameters
NCC (input) INTEGER The number of columns of the matrix C. NCC .GE. 0. /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension (N) On entry, the n diagonal elements of the bidiagonal matrix B. On exit, if INFO=0, the singular values of B in decreasing order. /param>
Parameters
E (input/output) DOUBLE PRECISION array, dimension (N-1) On entry, the N-1 offdiagonal elements of the bidiagonal matrix B. On exit, if INFO = 0, E is destroyed; if INFO .GT. 0, D and E will contain the diagonal and superdiagonal elements of a bidiagonal matrix orthogonally equivalent to the one given as input. /param>
Parameters
VT (input/output) DOUBLE PRECISION array, dimension (LDVT, NCVT) On entry, an N-by-NCVT matrix VT. On exit, VT is overwritten by P**T * VT. Not referenced if NCVT = 0. /param>
Parameters
LDVT (input) INTEGER The leading dimension of the array VT. LDVT .GE. max(1,N) if NCVT .GT. 0; LDVT .GE. 1 if NCVT = 0. /param>
Parameters
U (input/output) DOUBLE PRECISION array, dimension (LDU, N) On entry, an NRU-by-N matrix U. On exit, U is overwritten by U * Q. Not referenced if NRU = 0. /param>
Parameters
LDU (input) INTEGER The leading dimension of the array U. LDU .GE. max(1,NRU). /param>
Parameters
C (input/output) DOUBLE PRECISION array, dimension (LDC, NCC) On entry, an N-by-NCC matrix C. On exit, C is overwritten by Q**T * C. Not referenced if NCC = 0. /param>
Parameters
LDC (input) INTEGER The leading dimension of the array C. LDC .GE. max(1,N) if NCC .GT. 0; LDC .GE.1 if NCC = 0. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (2*N) if NCVT = NRU = NCC = 0, (max(1, 4*N)) otherwise /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: If INFO = -i, the i-th argument had an illegal value .GT. 0: the algorithm did not converge; D and E contain the elements of a bidiagonal matrix which is orthogonally similar to the input matrix B; if INFO = i, i elements of E have not converged to zero. /param>
References DotNumerics.LinearAlgebra.CSLapack.DBDSQR.HNDRD, DotNumerics.LinearAlgebra.CSLapack.DBDSQR.HNDRTH, DotNumerics.LinearAlgebra.CSLapack.DBDSQR.MAXITR, DotNumerics.LinearAlgebra.CSLapack.DBDSQR.MEIGTH, DotNumerics.LinearAlgebra.CSLapack.DBDSQR.NEGONE, DotNumerics.LinearAlgebra.CSLapack.DBDSQR.ONE, DotNumerics.LinearAlgebra.CSLapack.DROT.Run(), DotNumerics.LinearAlgebra.CSLapack.DSWAP.Run(), DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAS2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARTG.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASV2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASQ1.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASR.Run(), DotNumerics.FortranLibrary.FortranLib.Sign(), DotNumerics.LinearAlgebra.CSLapack.DBDSQR.TEN, and DotNumerics.LinearAlgebra.CSLapack.DBDSQR.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASDQ.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DBDSQR._lsame private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DBDSQR._dlamch private
_dlartg
DLARTG DotNumerics.LinearAlgebra.CSLapack.DBDSQR._dlartg private
_dlas2
DLAS2 DotNumerics.LinearAlgebra.CSLapack.DBDSQR._dlas2 private
_dlasq1
DLASQ1 DotNumerics.LinearAlgebra.CSLapack.DBDSQR._dlasq1 private
_dlasr
DLASR DotNumerics.LinearAlgebra.CSLapack.DBDSQR._dlasr private
_dlasv2
DLASV2 DotNumerics.LinearAlgebra.CSLapack.DBDSQR._dlasv2 private
_drot
DROT DotNumerics.LinearAlgebra.CSLapack.DBDSQR._drot private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DBDSQR._dscal private
_dswap
DSWAP DotNumerics.LinearAlgebra.CSLapack.DBDSQR._dswap private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DBDSQR._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DBDSQR.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DBDSQR.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run().
NEGONE
const double DotNumerics.LinearAlgebra.CSLapack.DBDSQR.NEGONE = - 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run().
HNDRTH
const double DotNumerics.LinearAlgebra.CSLapack.DBDSQR.HNDRTH = 0.01E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run().
TEN
const double DotNumerics.LinearAlgebra.CSLapack.DBDSQR.TEN = 10.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run().
HNDRD
const double DotNumerics.LinearAlgebra.CSLapack.DBDSQR.HNDRD = 100.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run().
MEIGTH
const double DotNumerics.LinearAlgebra.CSLapack.DBDSQR.MEIGTH = - 0.125E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run().
MAXITR
const int DotNumerics.LinearAlgebra.CSLapack.DBDSQR.MAXITR = 6 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dbdsqr.cs