Doc: IGLib EXTENDED: AForge.ThreadSafeRandom Class Reference
AForge.ThreadSafeRandom Class Reference
Thread safe version of the System.Random class.
Public Member Functions
ThreadSafeRandom ()
Initializes a new instance of the ThreadSafeRandom class.
ThreadSafeRandom (int seed)
Initializes a new instance of the ThreadSafeRandom class.
override int Next ()
Returns a nonnegative random number.
override int Next (int maxValue)
Returns a nonnegative random number less than the specified maximum.
override int Next (int minValue, int maxValue)
Returns a random number within a specified range.
override void NextBytes (byte[] buffer)
Fills the elements of a specified array of bytes with random numbers.
override double NextDouble ()
Returns a random number between 0.0 and 1.0.
Private Attributes
object sync = new object()
Detailed Description
Thread safe version of the System.Random class.
The class inherits the System.Random and overrides its random numbers generation methods providing thread safety by guarding call to the base class with a lock. See documentation to System.Random for additional information about the base class.
Constructor & Destructor Documentation
ThreadSafeRandom() [1/2]
AForge.ThreadSafeRandom.ThreadSafeRandom () inline
Initializes a new instance of the ThreadSafeRandom class.
See Random.Next() for more information.
ThreadSafeRandom() [2/2]
AForge.ThreadSafeRandom.ThreadSafeRandom (int seed) inline
Initializes a new instance of the ThreadSafeRandom class.
A number used to calculate a starting value for the pseudo-random number sequence. If a negative number is specified, the absolute value of the number is used.
See Random.Next() for more information.
Member Function Documentation
Next() [1/3]
override int AForge.ThreadSafeRandom.Next () inline
Returns a nonnegative random number.
Returns
Returns a 32-bit signed integer greater than or equal to zero and less than int.MaxValue.
See Random.Next() for more information.
References AForge.ThreadSafeRandom.sync.
Referenced by TSP.TSPChromosome.CreateChildUsingCrossover(), AForge.Genetic.PermutationChromosome.CreateChildUsingCrossover(), AForge.Genetic.BinaryChromosome.Crossover(), AForge.Genetic.ShortArrayChromosome.Crossover(), AForge.Genetic.GPTreeChromosome.Crossover(), AForge.Genetic.DoubleArrayChromosome.Crossover(), AForge.Genetic.GEPChromosome.Crossover(), AForge.Genetic.PermutationChromosome.Generate(), AForge.Genetic.GPTreeChromosome.Generate(), AForge.Genetic.ShortArrayChromosome.Generate(), AForge.Genetic.SimpleGeneFunction.Generate(), AForge.Genetic.ExtendedGeneFunction.Generate(), AForge.Genetic.PermutationChromosome.Mutate(), AForge.Genetic.BinaryChromosome.Mutate(), AForge.Genetic.ShortArrayChromosome.Mutate(), AForge.Genetic.GPTreeChromosome.Mutate(), AForge.Genetic.GEPChromosome.Mutate(), AForge.Genetic.DoubleArrayChromosome.Mutate(), AForge.Genetic.GEPChromosome.MutateGene(), AForge.Genetic.GPTreeChromosome.RandomSwap(), AForge.Genetic.GEPChromosome.RecombinationOnePoint(), AForge.Genetic.GEPChromosome.RecombinationTwoPoint(), AForge.Genetic.Population.Shuffle(), AForge.Genetic.GEPChromosome.TransposeIS(), and AForge.Genetic.GEPChromosome.TransposeRoot().
Next() [2/3]
override int AForge.ThreadSafeRandom.Next (int maxValue) inline
Returns a nonnegative random number less than the specified maximum.
Parameters
maxValue The exclusive upper bound of the random number to be generated. maxValue must be greater than or equal to zero.
Returns
Returns a 32-bit signed integer greater than or equal to zero, and less than maxValue ; that is, the range of return values ordinarily includes zero but not maxValue .
See Random.Next(int) for more information.
References AForge.ThreadSafeRandom.sync.
Next() [3/3]
override int AForge.ThreadSafeRandom.Next (int minValue, int maxValue) inline
Returns a random number within a specified range.
Parameters
minValue The inclusive lower bound of the random number returned.
maxValue The exclusive upper bound of the random number returned. maxValue must be greater than or equal to minValue .
Returns
Returns a 32-bit signed integer greater than or equal to minValue and less than maxValue ; that is, the range of return values includes minValue but not maxValue .
See Random.Next(int,int) for more information.
References AForge.ThreadSafeRandom.sync.
NextBytes()
override void AForge.ThreadSafeRandom.NextBytes (byte[] buffer) inline
Fills the elements of a specified array of bytes with random numbers.
Parameters
buffer An array of bytes to contain random numbers.
See Random.NextBytes(byte[]) for more information.
References AForge.ThreadSafeRandom.sync.
Referenced by AForge.Genetic.BinaryChromosome.Generate().
NextDouble()
override double AForge.ThreadSafeRandom.NextDouble () inline
Returns a random number between 0.0 and 1.0.
Returns
Returns a double-precision floating point number greater than or equal to 0.0, and less than 1.0.
See Random.NextDouble() for more information.
References AForge.ThreadSafeRandom.sync.
Referenced by AForge.Genetic.RouletteWheelSelection.ApplySelection(), AForge.Genetic.RankSelection.ApplySelection(), AForge.Genetic.Population.Crossover(), AForge.Genetic.DoubleArrayChromosome.Crossover(), AForge.Genetic.DoubleArrayChromosome.Mutate(), AForge.Genetic.Population.Mutate(), and AForge.Math.Random.UniformOneGenerator.Next().
Member Data Documentation
sync
object AForge.ThreadSafeRandom.sync = new object() private
Referenced by AForge.ThreadSafeRandom.Next(), AForge.ThreadSafeRandom.NextBytes(), and AForge.ThreadSafeRandom.NextDouble().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Core/ThreadSafeRandom.cs