Doc: IGLib EXTENDED: IG.Lib.XmlParser Class Reference
IG.Lib.XmlParser Class Reference
Base class for classes taht contain an Xml document that can be parsed. Provides comfortable utilities for transversing the document and for querying the value, name, and attributes of the current node.
Classes
class Mark
Position mark in the XML document
Public Member Functions
string Attribute (string key)
Returns the value of the specified attribute of the current node. If the attribute does not exist then null is returned.
XmlNode GetNode (string path)
Returns the first node that satisfies a given XPath expression relative to the root node. It does not report any errors (just returns null in case of errors)
XmlNode GetRelative (string path)
Returns the first node that satisfies a given XPath expression relative to the current node. It does not report any errors.
XmlNode GetNextNode (XmlNodeType NodeType, string NodeName, string NodeValue)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode GetNextNode (XmlNodeType NodeType, string NodeName)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode GetNextNode (XmlNodeType NodeType)
Moves the current node to the first sibling node after the current node that is of the specified type.
XmlNode GetNextNode (string NodeName, string NodeValue)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
XmlNode GetNextNode (string NodeName)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
XmlNode GetNextOrCurrentNode (XmlNodeType NodeType, string NodeName, string NodeValue)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode GetNextOrCurrentNode (XmlNodeType NodeType, string NodeName)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode GetNextOrCurrentNode (XmlNodeType NodeType)
Moves the current node to the current or the first sibling node after the current node that is of the specified type.
XmlNode GetNextOrCurrentNode (string NodeName, string NodeValue)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
XmlNode GetNextOrCurrentNode (string NodeName)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
XmlNode GetNextElement (string NodeName, string NodeValue)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode GetNextElement (string NodeName)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode GetNextElement ()
Moves the current node to the first sibling element after the current node.
XmlNode GetNextOrCurrentElement (string NodeName, string NodeValue)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode GetNextOrCurrentElement (string NodeName)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode GetNextOrCurrentElement ()
Moves the current node to the current or the first sibling element after the current node.
void SetMark (string name)
Marks the current state of the XmlParser and sets mark name to name. Position is stored on a stack such that previous stored positions can be restored, either in a reverse way.
void SetMark ()
Marks the current state of the XmlParser. The mark set is not named. Position is stored on a stack such that previous stored positions can be restored, either in a reverse way.
XmlNode GoToMark (bool removemarks)
Restores the parser state to the state contained in the last mark. The current node after operation is returned, or null if there are no marks. If required then the last mark is removed from the list.
XmlNode GoToMark (string name, bool removemarks)
Restores the parser state to the state contained in the last mark with the specified name. The current node after operation is returned, or null if there are no marks with such a name. If required then the targeted and all subsequent marks are removed from the list.
XmlNode GoToMark ()
Restores the parser state to the state contained in the last mark. The current node after operation is returned, or null if there are no marks. The last mark is LEFT on the list.
XmlNode GoToMark (string name)
Restores the parser state to the state contained in the last mark with the specified name. The current node after operation is returned, or null if there are no marks with such a name.
XmlNode BackToMark ()
Restores the parser state to the state contained in the last mark, and REMOVES that mark. The current node after operation is returned, or null if there are no marks.
XmlNode BackToMark (string name)
Restores the parser state to the state contained in the last mark with the specified name, and REMOVES all marks from that mark on (includively). The current node after operation is returned, or null if there are no marks with such a name.
XmlNode RemoveMark ()
Removes the last mark and returns its current node. Position is not affected.
XmlNode RemoveMarks (string name)
Removes all marks from the last mark with the specified name on the list and returns the current node of the specified mark. Position is not affected.
XmlNode Back ()
Moves the current to the previous node, if that node exists. Only one step backwards is enabled.
XmlNode MoveTo (XmlNode node)
Moves the current position to the specified node.
XmlNode MoveTo (string path)
Moves the current position to the first node that satisfies the absolute path specified as an XPath string.
XmlNode MoveRelative (string path)
Moves the current position to the first node that satisfies the relative path specified as an XPath string relative to the current node.
XmlNode GoToParent ()
Sets the current node to the parent node of the current node and returns it. This also works if the Current node is null because the advancing fell out of range or because StepIn was executed but there were no child _gridCoordinates of the current node.
XmlNode GoToRoot ()
Sets the current node to the root node of the current document and returns it.
XmlNode GoToDocument ()
Sets the current node to the root node of the current document and returns it.
XmlNode StepIn ()
Moves the current node to its first child node and returns the node.
XmlNode StepOut ()
Steps out of the current childnodes context and selects the next node of the parent as the current node. This also works if the Current node is null because the advancing fell out of range or because StepIn was executed but there were no child _gridCoordinates of the current node.
XmlNode NextNode ()
Sets the current node to the next sibling node, or to null if the next sibling node does not exist, and returns that node.
XmlNode NextNodeConditional (XmlNodeType NodeType, string NodeName, string NodeValue, bool IncludeCurrent)
Moves the current node to the first sibling node of the current node that satisfies the specified conditions, and returns the current node.
XmlNode NextNode (XmlNodeType NodeType, string NodeName, string NodeValue)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode NextNode (XmlNodeType NodeType, string NodeName)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode NextNode (XmlNodeType NodeType)
Moves the current node to the first sibling node after the current node that is of the specified type.
XmlNode NextNode (string NodeName, string NodeValue)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
XmlNode NextNode (string NodeName)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
XmlNode NextOrCurrentNode (XmlNodeType NodeType, string NodeName, string NodeValue)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode NextOrCurrentNode (XmlNodeType NodeType, string NodeName)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode NextOrCurrentNode (XmlNodeType NodeType)
Moves the current node to the current or the first sibling node after the current node that is of the specified type.
XmlNode NextOrCurrentNode (string NodeName, string NodeValue)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
XmlNode NextOrCurrentNode (string NodeName)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
XmlNode NextElement (string NodeName, string NodeValue)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode NextElement (string NodeName)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode NextElement ()
Moves the current node to the first sibling element after the current node.
XmlNode NextOrCurrentElement (string NodeName, string NodeValue)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode NextOrCurrentElement (string NodeName)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode NextOrCurrentElement ()
Moves the current node to the current or the first sibling element after the current node.
string Attribute (string key)
Returns the value of the specified attribute of the current node. If the attribute does not exist then null is returned.
XmlNode GetNode (string path)
Returns the first node that satisfies a given XPath expression relative to the root node. It does not report any errors (just returns null in case of errors)
XmlNode GetRelative (string path)
Returns the first node that satisfies a given XPath expression relative to the current node. It does not report any errors.
XmlNode GetNextNode (XmlNodeType NodeType, string NodeName, string NodeValue)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode GetNextNode (XmlNodeType NodeType, string NodeName)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode GetNextNode (XmlNodeType NodeType)
Moves the current node to the first sibling node after the current node that is of the specified type.
XmlNode GetNextNode (string NodeName, string NodeValue)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
XmlNode GetNextNode (string NodeName)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
XmlNode GetNextOrCurrentNode (XmlNodeType NodeType, string NodeName, string NodeValue)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode GetNextOrCurrentNode (XmlNodeType NodeType, string NodeName)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode GetNextOrCurrentNode (XmlNodeType NodeType)
Moves the current node to the current or the first sibling node after the current node that is of the specified type.
XmlNode GetNextOrCurrentNode (string NodeName, string NodeValue)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
XmlNode GetNextOrCurrentNode (string NodeName)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
XmlNode GetNextElement (string NodeName, string NodeValue)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode GetNextElement (string NodeName)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode GetNextElement ()
Moves the current node to the first sibling element after the current node.
XmlNode GetNextOrCurrentElement (string NodeName, string NodeValue)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode GetNextOrCurrentElement (string NodeName)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode GetNextOrCurrentElement ()
Moves the current node to the current or the first sibling element after the current node.
void SetMark (string name)
Marks the current state of the XmlParser and sets mark name to name. Position is stored on a stack such that previous stored positions can be restored, either in a reverse way.
void SetMark ()
Marks the current state of the XmlParser. The mark set is not named. Position is stored on a stack such that previous stored positions can be restored, either in a reverse way.
XmlNode GoToMark (bool removemark)
Restores the parser state to the state contained in the last mark. The current node after operation is returned, or null if there are no marks. If required then the last mark is removed from the list.
XmlNode GoToMark (string name, bool removemarks)
Restores the parser state to the state contained in the last mark with the specified name. The current node after operation is returned, or null if there are no marks with such a name. If required then the targeted and all subsequent marks are removed from the list.
XmlNode GoToMark ()
Restores the parser state to the state contained in the last mark. The current node after operation is returned, or null if there are no marks. The last mark is LEFT on the list.
XmlNode GoToMark (string name)
Restores the parser state to the state contained in the last mark with the specified name. The current node after operation is returned, or null if there are no marks with such a name. Marks are NOT REMOVED from the stacks.
XmlNode BackToMark ()
Restores the parser state to the state contained in the last mark, and REMOVES that mark. The current node after operation is returned, or null if there are no marks.
XmlNode BackToMark (string name)
Restores the parser state to the state contained in the last mark with the specified name, and REMOVES all marks from that mark on (includively). The current node after operation is returned, or null if there are no marks with such a name.
XmlNode RemoveMark ()
Removes the last mark and returns its current node. Position is not affected.
XmlNode RemoveMarks (string name)
Removes all marks from the last mark with the specified name on the list and returns the current node of the specified mark. Position is not affected.
XmlNode Back ()
Moves the current to the previous node, if that node exists. Only one step backwards is enabled. Information about Previous node is lost when this method is called.
XmlNode MoveTo (XmlNode node)
Moves the current position to the specified node.
XmlNode MoveTo (string path)
Moves the current position to the first node that satisfies the absolute path specified as an XPath string.
XmlNode MoveRelative (string path)
Moves the current position to the first node that satisfies the relative path specified as an XPath string relative to the current node.
XmlNode GoToParent ()
Sets the current node to the parent node of the current node and returns it. This also works if the Current node is null because the advancing fell out of range or because StepIn was executed but there were no child nodes of the current node.
XmlNode GoToRoot ()
Sets the current node to the root node of the current document and returns it.
XmlNode GoToDocument ()
Sets the current node to the root node of the current document and returns it.
XmlNode StepIn ()
Moves the current node to its first child node and returns the node.
XmlNode StepOut ()
Steps out of the current childnodes context and selects the next node of the parent as the current node. This also works if the Current node is null because the advancing fell out of range or because StepIn was executed but there were no child nodes of the current node.
XmlNode NextNode ()
Sets the current node to the next sibling node, or to null if the next sibling node does not exist, and returns that node.
XmlNode NextNodeConditional (XmlNodeType NodeType, string NodeName, string NodeValue, bool IncludeCurrent)
Moves the current node to the first sibling node of the current node that satisfies the specified conditions, and returns the current node.
XmlNode NextNode (XmlNodeType NodeType, string NodeName, string NodeValue)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode NextNode (XmlNodeType NodeType, string NodeName)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode NextNode (XmlNodeType NodeType)
Moves the current node to the first sibling node after the current node that is of the specified type.
XmlNode NextNode (string NodeName, string NodeValue)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
XmlNode NextNode (string NodeName)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
XmlNode NextOrCurrentNode (XmlNodeType NodeType, string NodeName, string NodeValue)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode NextOrCurrentNode (XmlNodeType NodeType, string NodeName)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode NextOrCurrentNode (XmlNodeType NodeType)
Moves the current node to the current or the first sibling node after the current node that is of the specified type.
XmlNode NextOrCurrentNode (string NodeName, string NodeValue)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
XmlNode NextOrCurrentNode (string NodeName)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
XmlNode NextElement (string NodeName, string NodeValue)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode NextElement (string NodeName)
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode NextElement ()
Moves the current node to the first sibling element after the current node.
XmlNode NextOrCurrentElement (string NodeName, string NodeValue)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode NextOrCurrentElement (string NodeName)
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
XmlNode NextOrCurrentElement ()
Moves the current node to the current or the first sibling element after the current node.
Public Member Functions inherited from IG.Lib.XmlUtilityBase
virtual void Load (string filename)
virtual void LoadXml (string docstr)
virtual void SetDocument (XmlDataDocument doc)
virtual void Load (string filename)
Loads an Xml document from a file.
virtual void LoadXml (string docstr)
Loads Xml document from a string.
virtual void LoadXml (XmlDocument doc)
Loads Xml document.
Static Public Member Functions
static XmlNode GetNextNode (XmlNode StartingNode, XmlNodeType NodeType, string NodeName, string NodeValue, bool IncludeCurrent)
Finds the first sibling node of the starting node (or the current node itself) that satisfies the specified conditions, and returns that node or null if such a node could not be found. This method does not report errors, it just returns null if the node satisfying conditions can not be found.
static XmlNode GetNextNode (XmlNode StartingNode, XmlNodeType NodeType, string NodeName, string NodeValue, bool IncludeCurrent)
Finds the first sibling node of the starting node (or the current node itself) that satisfies the specified conditions, and returns that node or null if such a node could not be found. This method does not report errors, it just returns null if the node satisfying conditions can not be found.
Static Public Member Functions inherited from IG.Lib.XmlUtilityBase
static string GetDefaultNameSpaceUri (XmlElement element)
Gets the default namespace URI if defined, for the specified Xml element.
static string GetDefaultNameSpaceUri (XmlDocument doc)
Gets the default namespace URI of teh Xml document.
static string GetDefaultNameSpaceUri (XmlNode node)
Returns the default namespace URI that applies to the specified Xml node.
static string GetNameSpaceUri (XmlDocument doc, string prefix)
Returns the namespace URI associated with a specific prefix that applies to the specified Xml document.
static string GetNameSpaceUri (XmlNode node, string prefix)
Returns the namespace URI associated with a specific prefix that applies to the specified Xml document.
static string GetDefaultNameSpaceUri (XmlElement element)
Gets the default namespace URI if defined, for the specified Xml element.
static string GetDefaultNameSpaceUri (XmlDocument doc)
Gets the default namespace URI of teh Xml document.
static string GetDefaultNameSpaceUri (XmlNode node)
Returns the default namespace URI that applies to the specified Xml node.
static string GetNameSpaceUri (XmlDocument doc, string prefix)
Returns the namespace URI associated with a specific prefix that applies to the specified Xml document.
static string GetNameSpaceUri (XmlNode node, string prefix)
Returns the namespace URI associated with a specific prefix that applies to the specified Xml document.
Protected Member Functions
XmlNode GoToMark (Mark mark)
Restores the parser state that is stored in the specified mark. The current node after operation is returned, or null if mark is not specified (i.e., it is null).
XmlNode GoToMark (Mark mark)
Restores the parser state that is stored in the specified mark. The current node after operation is returned, or null if mark is not specified (i.e., it is null).
Protected Member Functions inherited from IG.Lib.XmlUtilityBase
bool ContainedInDocument (XmlNode node, XmlDocument doc)
Returns true if an Xml node is contained in the specified Xml document (false if any is null).
bool ContainedInNode (XmlNode node, XmlNode container)
Returns null if an XML node (first argument) is contained in the specified note (second argument). The node can be contained in another node at an arbitrary depth for the function to return true. If any of the _gridCoordinates is null then the function returns false.
bool ContainedInDocument (XmlNode node, XmlDocument doc)
Returns true if an Xml node is contained in the specified Xml document (false if any is null).
bool ContainedInNode (XmlNode node, XmlNode container)
Returns null if an XML node (first argument) is contained in the specified note (second argument). The node can be contained in another node at an arbitrary depth for the function to return true. If any of the nodes is null then the function returns false.
Properties
override XmlDocument Doc [get, set]
Xml document that represents the message.
XmlNode Current [get, set]
The current node on which all queries are performed.
XmlNode Previous [get, set]
The node that was previously set to the current node.
XmlNode Parent [get, private set]
Parent of Current. If Current = null then Parent can still return something, which happens in particular when StepIn was performed before. Parent can be set to a specific node. That node will be returned by Parent when the Current is null (otherwise, the parent of Current is still returned). This is useful when current becomes null, e.g. because of running out of index bounds.
XmlElement ParentElement [get]
XmlElement CurrentElement [get]
XmlElement PreviousElement [get]
string Name [get]
Returns the name of the current node.
string Value [get]
Returns the value of the current node. If the current node is an element then the value of its first text child element is returned.
string InnerText [get]
Returns the inner text of the current node.
Properties inherited from IG.Lib.XmlUtilityBase
virtual IG.Lib.IReporter R [get]
Reporter for this class.
virtual bool HasDefaultNameSpace [get, protected set]
string FileName [get, protected set]
virtual XmlDocument Doc [get, set]
Xml document that represents the message.
XmlNode Root [get, private set]
Root node of the current document.
virtual IReporter R [get]
Reporter for this class.
Private Attributes
XmlNode _current = null
XmlNode _previous = null
XmlNode _parent = null
List< Mark > marks = new List<Mark>()
Additional Inherited Members
Public Attributes inherited from IG.Lib.XmlUtilityBase
string DefaultNameSpace = null
string DefaultNameSpacePrefix = "defaultnsprefix"
Detailed Description
Base class for classes taht contain an Xml document that can be parsed. Provides comfortable utilities for transversing the document and for querying the value, name, and attributes of the current node.
Member Function Documentation
Attribute() [1/2]
string IG.Lib.XmlParser.Attribute (string key) inline
Returns the value of the specified attribute of the current node. If the attribute does not exist then null is returned.
References IG.Lib.XmlParser.CurrentElement.
Referenced by IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgFinancialTransaction.Read(), and IG.Lib.MsgObervationOrder.Read().
GetNode() [1/2]
XmlNode IG.Lib.XmlParser.GetNode (string path) inline
Returns the first node that satisfies a given XPath expression relative to the root node. It does not report any errors (just returns null in case of errors)
Parameters
path XPath expression.
Returns
The first node that satisfies the path, or null if no such node is found.
References IG.Lib.XmlUtilityBase.Root.
Referenced by IG.Lib.XmlParser.MoveTo().
GetRelative() [1/2]
XmlNode IG.Lib.XmlParser.GetRelative (string path) inline
Returns the first node that satisfies a given XPath expression relative to the current node. It does not report any errors.
Parameters
path XPath expression.
Returns
The first node that satisfies the path, or null if no such node is found.
References IG.Lib.XmlParser.Current.
Referenced by IG.Lib.XmlParser.MoveRelative().
GetNextNode() [1/12]
static XmlNode IG.Lib.XmlParser.GetNextNode (XmlNode StartingNode, XmlNodeType NodeType, string NodeName, string NodeValue, bool IncludeCurrent) inline static
Finds the first sibling node of the starting node (or the current node itself) that satisfies the specified conditions, and returns that node or null if such a node could not be found. This method does not report errors, it just returns null if the node satisfying conditions can not be found.
Parameters
StartingNode Starting node at which the search is started.
NodeType If not XmlNodeType.None then the current node must have this type.
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
IncludeCurrent If true then the returned node can also be the current node (if it satisfies the conditions), otherwise the search starts at the next sibling of the current node.
Returns
Referenced by IG.Lib.XmlParser.GetNextElement(), IG.Lib.XmlParser.GetNextNode(), IG.Lib.XmlParser.GetNextOrCurrentElement(), IG.Lib.XmlParser.GetNextOrCurrentNode(), and IG.Lib.XmlParser.NextNodeConditional().
GetNextNode() [2/12]
XmlNode IG.Lib.XmlParser.GetNextNode (XmlNodeType NodeType, string NodeName, string NodeValue) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeType If not None then the current node must have this type.
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextNode() [3/12]
XmlNode IG.Lib.XmlParser.GetNextNode (XmlNodeType NodeType, string NodeName) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeType If not None then the current node must have this type.
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextNode() [4/12]
XmlNode IG.Lib.XmlParser.GetNextNode (XmlNodeType NodeType) inline
Moves the current node to the first sibling node after the current node that is of the specified type.
Parameters
NodeType If not None then the current node must have this type.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextNode() [5/12]
XmlNode IG.Lib.XmlParser.GetNextNode (string NodeName, string NodeValue) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
Parameters
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextNode() [6/12]
XmlNode IG.Lib.XmlParser.GetNextNode (string NodeName) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
Parameters
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextOrCurrentNode() [1/10]
XmlNode IG.Lib.XmlParser.GetNextOrCurrentNode (XmlNodeType NodeType, string NodeName, string NodeValue) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeType If not None then the current node must have this type.
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextOrCurrentNode() [2/10]
XmlNode IG.Lib.XmlParser.GetNextOrCurrentNode (XmlNodeType NodeType, string NodeName) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeType If not None then the current node must have this type.
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextOrCurrentNode() [3/10]
XmlNode IG.Lib.XmlParser.GetNextOrCurrentNode (XmlNodeType NodeType) inline
Moves the current node to the current or the first sibling node after the current node that is of the specified type.
Parameters
NodeType If not None then the current node must have this type.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextOrCurrentNode() [4/10]
XmlNode IG.Lib.XmlParser.GetNextOrCurrentNode (string NodeName, string NodeValue) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
Parameters
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextOrCurrentNode() [5/10]
XmlNode IG.Lib.XmlParser.GetNextOrCurrentNode (string NodeName) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
Parameters
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextElement() [1/6]
XmlNode IG.Lib.XmlParser.GetNextElement (string NodeName, string NodeValue) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextElement() [2/6]
XmlNode IG.Lib.XmlParser.GetNextElement (string NodeName) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextElement() [3/6]
XmlNode IG.Lib.XmlParser.GetNextElement () inline
Moves the current node to the first sibling element after the current node.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextOrCurrentElement() [1/6]
XmlNode IG.Lib.XmlParser.GetNextOrCurrentElement (string NodeName, string NodeValue) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextOrCurrentElement() [2/6]
XmlNode IG.Lib.XmlParser.GetNextOrCurrentElement (string NodeName) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextOrCurrentElement() [3/6]
XmlNode IG.Lib.XmlParser.GetNextOrCurrentElement () inline
Moves the current node to the current or the first sibling element after the current node.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
SetMark() [1/4]
void IG.Lib.XmlParser.SetMark (string name) inline
Marks the current state of the XmlParser and sets mark name to name. Position is stored on a stack such that previous stored positions can be restored, either in a reverse way.
Parameters
name Name assigned to the mark.
References IG.Lib.XmlParser.Current, IG.Lib.XmlParser.Mark.Current, IG.Lib.XmlParser.marks, IG.Lib.XmlParser.Mark.name, IG.Lib.XmlParser.Parent, IG.Lib.XmlParser.Mark.Parent, IG.Lib.XmlParser.Previous, IG.Lib.XmlParser.Mark.Previous, IG.Lib.XmlUtilityBase.R, and IG.Lib.IReporterBase.ReportError().
Referenced by IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgFinancialTransaction.Read(), IG.Lib.DocFindings.Read(), IG.Lib.MsgObervationOrder.Read(), IG.Lib.MsgFinancialTransaction.ToXml(), IG.Lib.MsgObservationEvent.ToXml(), and IG.Lib.DocFindings.ToXml().
SetMark() [2/4]
void IG.Lib.XmlParser.SetMark () inline
Marks the current state of the XmlParser. The mark set is not named. Position is stored on a stack such that previous stored positions can be restored, either in a reverse way.
Referenced by IG.Lib.XmlParser.SetMark().
GoToMark() [1/10]
XmlNode IG.Lib.XmlParser.GoToMark (Mark mark) inline protected
Restores the parser state that is stored in the specified mark. The current node after operation is returned, or null if mark is not specified (i.e., it is null).
Parameters
mark The mark containing the state that is restored.
Returns
The current node after operation.
References IG.Lib.XmlParser.Current, IG.Lib.XmlParser.Mark.Current, IG.Lib.XmlParser.MoveTo(), IG.Lib.XmlParser.Parent, IG.Lib.XmlParser.Mark.Parent, IG.Lib.XmlParser.Previous, and IG.Lib.XmlParser.Mark.Previous.
Referenced by IG.Lib.MsgObervationOrder.Read(), IG.Lib.MsgFinancialTransaction.ToXml(), and IG.Lib.DocFindings.ToXml().
GoToMark() [2/10]
XmlNode IG.Lib.XmlParser.GoToMark (bool removemarks) inline
Restores the parser state to the state contained in the last mark. The current node after operation is returned, or null if there are no marks. If required then the last mark is removed from the list.
Parameters
removemarks If true then all marks from the specified one on (inclusively) are removed.
Returns
The current node after operation or null if there is no valid last mark.
References IG.Lib.XmlParser.GoToMark(), and IG.Lib.XmlParser.marks.
GoToMark() [3/10]
XmlNode IG.Lib.XmlParser.GoToMark (string name, bool removemarks) inline
Restores the parser state to the state contained in the last mark with the specified name. The current node after operation is returned, or null if there are no marks with such a name. If required then the targeted and all subsequent marks are removed from the list.
Parameters
name Name of the mark whose state is restored.
removemarks If true then all marks from the specified one on (inclusively) are removed.
Returns
The current node after operation or null if the specified mark has not been found.
References IG.Lib.XmlParser.GoToMark(), IG.Lib.XmlParser.marks, and IG.Lib.XmlParser.Mark.name.
GoToMark() [4/10]
XmlNode IG.Lib.XmlParser.GoToMark () inline
Restores the parser state to the state contained in the last mark. The current node after operation is returned, or null if there are no marks. The last mark is LEFT on the list.
Returns
The current node after operation or null if there is no valid last mark.
Referenced by IG.Lib.XmlParser.BackToMark(), and IG.Lib.XmlParser.GoToMark().
GoToMark() [5/10]
XmlNode IG.Lib.XmlParser.GoToMark (string name) inline
Restores the parser state to the state contained in the last mark with the specified name. The current node after operation is returned, or null if there are no marks with such a name.
Parameters
name Name of the mark whose state is restored.
Returns
The current node after operation or null if the specified mark has not been found.
References IG.Lib.XmlParser.GoToMark().
BackToMark() [1/4]
XmlNode IG.Lib.XmlParser.BackToMark () inline
Restores the parser state to the state contained in the last mark, and REMOVES that mark. The current node after operation is returned, or null if there are no marks.
Returns
The current node after operation or null if there is no valid last mark.
References IG.Lib.XmlParser.GoToMark().
Referenced by IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgFinancialTransaction.Read(), IG.Lib.DocFindings.Read(), IG.Lib.MsgObervationOrder.Read(), IG.Lib.MsgFinancialTransaction.ToXml(), IG.Lib.MsgObservationEvent.ToXml(), and IG.Lib.DocFindings.ToXml().
BackToMark() [2/4]
XmlNode IG.Lib.XmlParser.BackToMark (string name) inline
Restores the parser state to the state contained in the last mark with the specified name, and REMOVES all marks from that mark on (includively). The current node after operation is returned, or null if there are no marks with such a name.
Parameters
name Name of the mark whose state is restored.
Returns
The current node after operation or null if the specified mark has not been found.
References IG.Lib.XmlParser.GoToMark().
RemoveMark() [1/2]
XmlNode IG.Lib.XmlParser.RemoveMark () inline
Removes the last mark and returns its current node. Position is not affected.
Returns
The current node stored on the last mark, or null if no marks are defined.
References IG.Lib.XmlParser.Mark.Current, and IG.Lib.XmlParser.marks.
Referenced by IG.Lib.MsgObservationEvent.Read(), and IG.Lib.MsgObervationOrder.Read().
RemoveMarks() [1/2]
XmlNode IG.Lib.XmlParser.RemoveMarks (string name) inline
Removes all marks from the last mark with the specified name on the list and returns the current node of the specified mark. Position is not affected.
Returns
The current node stored on the last mark with the specified name, or null if such a mark is not found.
References IG.Lib.XmlParser.Mark.Current, IG.Lib.XmlParser.marks, and IG.Lib.XmlParser.Mark.name.
Referenced by IG.Lib.MsgObervationOrder.Read().
Back() [1/2]
XmlNode IG.Lib.XmlParser.Back () inline
Moves the current to the previous node, if that node exists. Only one step backwards is enabled.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.Previous.
Referenced by IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgFinancialTransaction.Read(), IG.Lib.DocFindings.Read(), IG.Lib.MsgObervationOrder.Read(), IG.Lib.MsgFinancialTransaction.ToXml(), and IG.Lib.MsgObservationEvent.ToXml().
MoveTo() [1/4]
XmlNode IG.Lib.XmlParser.MoveTo (XmlNode node) inline
Moves the current position to the specified node.
References IG.Lib.XmlUtilityBase.ContainedInDocument(), IG.Lib.XmlParser.Current, IG.Lib.XmlParser.Doc, IG.Lib.XmlParser.Parent, IG.Lib.XmlParser.Previous, IG.Lib.XmlUtilityBase.R, and IG.Lib.IReporterBase.ReportError().
Referenced by IG.Lib.XmlParser.GoToMark(), IG.Lib.XmlParser.MoveRelative(), IG.Lib.XmlParser.MoveTo(), IG.Lib.XmlBuilder.MoveToNewest(), and IG.Lib.XmlBuilder.RemoveNode().
MoveTo() [2/4]
XmlNode IG.Lib.XmlParser.MoveTo (string path) inline
Moves the current position to the first node that satisfies the absolute path specified as an XPath string.
Parameters
path XPath string that specifies the node position relative to the document root.
Returns
The node to which the current position has moved, or null if not successful.
References IG.Lib.XmlParser.GetNode(), and IG.Lib.XmlParser.MoveTo().
MoveRelative() [1/2]
XmlNode IG.Lib.XmlParser.MoveRelative (string path) inline
Moves the current position to the first node that satisfies the relative path specified as an XPath string relative to the current node.
Parameters
path XPath string that specifies the node position relative to the current node.
Returns
The node to which the current position has moved, or null if not successful.
References IG.Lib.XmlParser.GetRelative(), and IG.Lib.XmlParser.MoveTo().
GoToParent() [1/2]
XmlNode IG.Lib.XmlParser.GoToParent () inline
Sets the current node to the parent node of the current node and returns it. This also works if the Current node is null because the advancing fell out of range or because StepIn was executed but there were no child _gridCoordinates of the current node.
Returns
The current node.
References IG.Lib.XmlParser.Current, IG.Lib.XmlParser.Parent, and IG.Lib.XmlParser.Previous.
GoToRoot() [1/2]
XmlNode IG.Lib.XmlParser.GoToRoot () inline
Sets the current node to the root node of the current document and returns it.
Returns
The current node.
References IG.Lib.XmlParser.Current, IG.Lib.XmlParser.Previous, and IG.Lib.XmlUtilityBase.Root.
Referenced by IG.Lib.MsgBase.IsDetailedFinancialTransaction(), IG.Lib.MsgBase.IsSpecimenObservationEvent(), IG.Lib.MsgBase.IsSpecimenObservationOrder(), IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgFinancialTransaction.Read(), IG.Lib.DocFindings.Read(), IG.Lib.MsgObervationOrder.Read(), IG.Lib.MsgFinancialTransaction.ToXml(), and IG.Lib.MsgObservationEvent.ToXml().
GoToDocument() [1/2]
XmlNode IG.Lib.XmlParser.GoToDocument () inline
Sets the current node to the root node of the current document and returns it.
Returns
The current node.
References IG.Lib.XmlParser.Current, IG.Lib.XmlParser.Doc, and IG.Lib.XmlParser.Previous.
StepIn() [1/2]
XmlNode IG.Lib.XmlParser.StepIn () inline
Moves the current node to its first child node and returns the node.
References IG.Lib.XmlParser._parent, IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.Previous.
Referenced by IG.Lib.MsgBase.IsDetailedFinancialTransaction(), IG.Lib.MsgBase.IsSpecimenObservationEvent(), IG.Lib.MsgBase.IsSpecimenObservationOrder(), IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgFinancialTransaction.Read(), IG.Lib.DocFindings.Read(), IG.Lib.MsgObervationOrder.Read(), IG.Lib.MsgFinancialTransaction.ToXml(), and IG.Lib.MsgObservationEvent.ToXml().
StepOut() [1/2]
XmlNode IG.Lib.XmlParser.StepOut () inline
Steps out of the current childnodes context and selects the next node of the parent as the current node. This also works if the Current node is null because the advancing fell out of range or because StepIn was executed but there were no child _gridCoordinates of the current node.
Returns
References IG.Lib.XmlParser.Current, IG.Lib.XmlParser.Parent, and IG.Lib.XmlParser.Previous.
Referenced by IG.Lib.MsgObservationEvent.Read(), and IG.Lib.MsgObervationOrder.Read().
NextNode() [1/12]
XmlNode IG.Lib.XmlParser.NextNode () inline
Sets the current node to the next sibling node, or to null if the next sibling node does not exist, and returns that node.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.Previous.
Referenced by IG.Lib.MsgObservationEvent.Read(), and IG.Lib.XmlBuilder.RemoveNode().
NextNodeConditional() [1/2]
XmlNode IG.Lib.XmlParser.NextNodeConditional (XmlNodeType NodeType, string NodeName, string NodeValue, bool IncludeCurrent) inline
Moves the current node to the first sibling node of the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeType If not None then the current node must have this type.
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
IncludeCurrent If true then the new current node can also be the current node (if it satisfies the conditions), otherwise the search starts at the next sibling of the current node.
Returns
References IG.Lib.XmlParser.Current, IG.Lib.XmlParser.GetNextNode(), and IG.Lib.XmlParser.Previous.
Referenced by IG.Lib.XmlParser.NextElement(), IG.Lib.XmlParser.NextNode(), IG.Lib.XmlParser.NextOrCurrentElement(), and IG.Lib.XmlParser.NextOrCurrentNode().
NextNode() [2/12]
XmlNode IG.Lib.XmlParser.NextNode (XmlNodeType NodeType, string NodeName, string NodeValue) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeType If not None then the current node must have this type.
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.NextNodeConditional().
NextNode() [3/12]
XmlNode IG.Lib.XmlParser.NextNode (XmlNodeType NodeType, string NodeName) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeType If not None then the current node must have this type.
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.NextNodeConditional().
NextNode() [4/12]
XmlNode IG.Lib.XmlParser.NextNode (XmlNodeType NodeType) inline
Moves the current node to the first sibling node after the current node that is of the specified type.
Parameters
NodeType If not None then the current node must have this type.
References IG.Lib.XmlParser.NextNodeConditional().
NextNode() [5/12]
XmlNode IG.Lib.XmlParser.NextNode (string NodeName, string NodeValue) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
Parameters
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.NextNodeConditional().
NextNode() [6/12]
XmlNode IG.Lib.XmlParser.NextNode (string NodeName) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
Parameters
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.NextNodeConditional().
NextOrCurrentNode() [1/10]
XmlNode IG.Lib.XmlParser.NextOrCurrentNode (XmlNodeType NodeType, string NodeName, string NodeValue) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeType If not None then the current node must have this type.
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.NextNodeConditional().
NextOrCurrentNode() [2/10]
XmlNode IG.Lib.XmlParser.NextOrCurrentNode (XmlNodeType NodeType, string NodeName) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeType If not None then the current node must have this type.
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.NextNodeConditional().
NextOrCurrentNode() [3/10]
XmlNode IG.Lib.XmlParser.NextOrCurrentNode (XmlNodeType NodeType) inline
Moves the current node to the current or the first sibling node after the current node that is of the specified type.
Parameters
NodeType If not None then the current node must have this type.
References IG.Lib.XmlParser.NextNodeConditional().
NextOrCurrentNode() [4/10]
XmlNode IG.Lib.XmlParser.NextOrCurrentNode (string NodeName, string NodeValue) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
Parameters
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.NextNodeConditional().
NextOrCurrentNode() [5/10]
XmlNode IG.Lib.XmlParser.NextOrCurrentNode (string NodeName) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
Parameters
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.NextNodeConditional().
NextElement() [1/6]
XmlNode IG.Lib.XmlParser.NextElement (string NodeName, string NodeValue) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.NextNodeConditional().
Referenced by IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgFinancialTransaction.Read(), IG.Lib.DocFindings.Read(), IG.Lib.MsgObervationOrder.Read(), and IG.Lib.MsgFinancialTransaction.ToXml().
NextElement() [2/6]
XmlNode IG.Lib.XmlParser.NextElement (string NodeName) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.NextNodeConditional().
NextElement() [3/6]
XmlNode IG.Lib.XmlParser.NextElement () inline
Moves the current node to the first sibling element after the current node.
References IG.Lib.XmlParser.NextNodeConditional().
NextOrCurrentElement() [1/6]
XmlNode IG.Lib.XmlParser.NextOrCurrentElement (string NodeName, string NodeValue) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.NextNodeConditional().
Referenced by IG.Lib.MsgBase.IsDetailedFinancialTransaction(), IG.Lib.MsgBase.IsSpecimenObservationEvent(), IG.Lib.MsgBase.IsSpecimenObservationOrder(), IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgFinancialTransaction.Read(), IG.Lib.DocFindings.Read(), IG.Lib.MsgObervationOrder.Read(), IG.Lib.MsgFinancialTransaction.ToXml(), and IG.Lib.MsgObservationEvent.ToXml().
NextOrCurrentElement() [2/6]
XmlNode IG.Lib.XmlParser.NextOrCurrentElement (string NodeName) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.NextNodeConditional().
NextOrCurrentElement() [3/6]
XmlNode IG.Lib.XmlParser.NextOrCurrentElement () inline
Moves the current node to the current or the first sibling element after the current node.
References IG.Lib.XmlParser.NextNodeConditional().
Attribute() [2/2]
string IG.Lib.XmlParser.Attribute (string key) inline
Returns the value of the specified attribute of the current node. If the attribute does not exist then null is returned.
References IG.Lib.XmlParser.CurrentElement.
GetNode() [2/2]
XmlNode IG.Lib.XmlParser.GetNode (string path) inline
Returns the first node that satisfies a given XPath expression relative to the root node. It does not report any errors (just returns null in case of errors)
Parameters
path XPath expression.
Returns
The first node that satisfies the path, or null if no such node is found.
References IG.Lib.XmlUtilityBase.Root.
GetRelative() [2/2]
XmlNode IG.Lib.XmlParser.GetRelative (string path) inline
Returns the first node that satisfies a given XPath expression relative to the current node. It does not report any errors.
Parameters
path XPath expression.
Returns
The first node that satisfies the path, or null if no such node is found.
References IG.Lib.XmlParser.Current.
GetNextNode() [7/12]
static XmlNode IG.Lib.XmlParser.GetNextNode (XmlNode StartingNode, XmlNodeType NodeType, string NodeName, string NodeValue, bool IncludeCurrent) inline static
Finds the first sibling node of the starting node (or the current node itself) that satisfies the specified conditions, and returns that node or null if such a node could not be found. This method does not report errors, it just returns null if the node satisfying conditions can not be found.
Parameters
StartingNode Starting node at which the search is started.
NodeType If not XmlNodeType.None then the current node must have this type.
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
IncludeCurrent If true then the returned node can also be the current node (if it satisfies the conditions), otherwise the search starts at the next sibling of the current node.
Returns
GetNextNode() [8/12]
XmlNode IG.Lib.XmlParser.GetNextNode (XmlNodeType NodeType, string NodeName, string NodeValue) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeType If not None then the current node must have this type.
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextNode() [9/12]
XmlNode IG.Lib.XmlParser.GetNextNode (XmlNodeType NodeType, string NodeName) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeType If not None then the current node must have this type.
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextNode() [10/12]
XmlNode IG.Lib.XmlParser.GetNextNode (XmlNodeType NodeType) inline
Moves the current node to the first sibling node after the current node that is of the specified type.
Parameters
NodeType If not None then the current node must have this type.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextNode() [11/12]
XmlNode IG.Lib.XmlParser.GetNextNode (string NodeName, string NodeValue) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
Parameters
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextNode() [12/12]
XmlNode IG.Lib.XmlParser.GetNextNode (string NodeName) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
Parameters
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextOrCurrentNode() [6/10]
XmlNode IG.Lib.XmlParser.GetNextOrCurrentNode (XmlNodeType NodeType, string NodeName, string NodeValue) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeType If not None then the current node must have this type.
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextOrCurrentNode() [7/10]
XmlNode IG.Lib.XmlParser.GetNextOrCurrentNode (XmlNodeType NodeType, string NodeName) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeType If not None then the current node must have this type.
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextOrCurrentNode() [8/10]
XmlNode IG.Lib.XmlParser.GetNextOrCurrentNode (XmlNodeType NodeType) inline
Moves the current node to the current or the first sibling node after the current node that is of the specified type.
Parameters
NodeType If not None then the current node must have this type.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextOrCurrentNode() [9/10]
XmlNode IG.Lib.XmlParser.GetNextOrCurrentNode (string NodeName, string NodeValue) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
Parameters
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextOrCurrentNode() [10/10]
XmlNode IG.Lib.XmlParser.GetNextOrCurrentNode (string NodeName) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
Parameters
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextElement() [4/6]
XmlNode IG.Lib.XmlParser.GetNextElement (string NodeName, string NodeValue) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextElement() [5/6]
XmlNode IG.Lib.XmlParser.GetNextElement (string NodeName) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextElement() [6/6]
XmlNode IG.Lib.XmlParser.GetNextElement () inline
Moves the current node to the first sibling element after the current node.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextOrCurrentElement() [4/6]
XmlNode IG.Lib.XmlParser.GetNextOrCurrentElement (string NodeName, string NodeValue) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextOrCurrentElement() [5/6]
XmlNode IG.Lib.XmlParser.GetNextOrCurrentElement (string NodeName) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
GetNextOrCurrentElement() [6/6]
XmlNode IG.Lib.XmlParser.GetNextOrCurrentElement () inline
Moves the current node to the current or the first sibling element after the current node.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.GetNextNode().
SetMark() [3/4]
void IG.Lib.XmlParser.SetMark (string name) inline
Marks the current state of the XmlParser and sets mark name to name. Position is stored on a stack such that previous stored positions can be restored, either in a reverse way.
Parameters
name Name assigned to the mark.
References IG.Lib.XmlParser.Current, IG.Lib.XmlParser.marks, IG.Lib.XmlParser.Parent, IG.Lib.XmlParser.Previous, IG.Lib.XmlUtilityBase.R, and IG.Lib.IReporterBase.ReportError().
SetMark() [4/4]
void IG.Lib.XmlParser.SetMark () inline
Marks the current state of the XmlParser. The mark set is not named. Position is stored on a stack such that previous stored positions can be restored, either in a reverse way.
Parameters
name Name assigned to the mark.
References IG.Lib.XmlParser.SetMark().
GoToMark() [6/10]
XmlNode IG.Lib.XmlParser.GoToMark (Mark mark) inline protected
Restores the parser state that is stored in the specified mark. The current node after operation is returned, or null if mark is not specified (i.e., it is null).
Parameters
mark The mark containing the state that is restored.
Returns
The current node after operation.
References IG.Lib.XmlParser.Current, IG.Lib.XmlParser.MoveTo(), IG.Lib.XmlParser.Parent, and IG.Lib.XmlParser.Previous.
GoToMark() [7/10]
XmlNode IG.Lib.XmlParser.GoToMark (bool removemark) inline
Restores the parser state to the state contained in the last mark. The current node after operation is returned, or null if there are no marks. If required then the last mark is removed from the list.
Parameters
removemarks If true then all marks from the specified one on (inclusively) are removed.
Returns
The current node after operation or null if there is no valid last mark.
References IG.Lib.XmlParser.GoToMark(), and IG.Lib.XmlParser.marks.
GoToMark() [8/10]
XmlNode IG.Lib.XmlParser.GoToMark (string name, bool removemarks) inline
Restores the parser state to the state contained in the last mark with the specified name. The current node after operation is returned, or null if there are no marks with such a name. If required then the targeted and all subsequent marks are removed from the list.
Parameters
name Name of the mark whose state is restored.
removemarks If true then all marks from the specified one on (inclusively) are removed.
Returns
The current node after operation or null if the specified mark has not been found.
References IG.Lib.XmlParser.GoToMark(), and IG.Lib.XmlParser.marks.
GoToMark() [9/10]
XmlNode IG.Lib.XmlParser.GoToMark () inline
Restores the parser state to the state contained in the last mark. The current node after operation is returned, or null if there are no marks. The last mark is LEFT on the list.
Parameters
removemarks If true then all marks from the specified one on (inclusively) are removed.
Returns
The current node after operation or null if there is no valid last mark.
References IG.Lib.XmlParser.GoToMark().
GoToMark() [10/10]
XmlNode IG.Lib.XmlParser.GoToMark (string name) inline
Restores the parser state to the state contained in the last mark with the specified name. The current node after operation is returned, or null if there are no marks with such a name. Marks are NOT REMOVED from the stacks.
Parameters
name Name of the mark whose state is restored.
Returns
The current node after operation or null if the specified mark has not been found.
References IG.Lib.XmlParser.GoToMark().
BackToMark() [3/4]
XmlNode IG.Lib.XmlParser.BackToMark () inline
Restores the parser state to the state contained in the last mark, and REMOVES that mark. The current node after operation is returned, or null if there are no marks.
Returns
The current node after operation or null if there is no valid last mark.
References IG.Lib.XmlParser.GoToMark().
BackToMark() [4/4]
XmlNode IG.Lib.XmlParser.BackToMark (string name) inline
Restores the parser state to the state contained in the last mark with the specified name, and REMOVES all marks from that mark on (includively). The current node after operation is returned, or null if there are no marks with such a name.
Parameters
name Name of the mark whose state is restored.
Returns
The current node after operation or null if the specified mark has not been found.
References IG.Lib.XmlParser.GoToMark().
RemoveMark() [2/2]
XmlNode IG.Lib.XmlParser.RemoveMark () inline
Removes the last mark and returns its current node. Position is not affected.
Returns
The current node stored on the last mark, or null if no marks are defined.
References IG.Lib.XmlParser.marks.
RemoveMarks() [2/2]
XmlNode IG.Lib.XmlParser.RemoveMarks (string name) inline
Removes all marks from the last mark with the specified name on the list and returns the current node of the specified mark. Position is not affected.
Returns
The current node stored on the last mark with the specified name, or null if such a mark is not found.
References IG.Lib.XmlParser.marks.
Back() [2/2]
XmlNode IG.Lib.XmlParser.Back () inline
Moves the current to the previous node, if that node exists. Only one step backwards is enabled. Information about Previous node is lost when this method is called.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.Previous.
MoveTo() [3/4]
XmlNode IG.Lib.XmlParser.MoveTo (XmlNode node) inline
Moves the current position to the specified node.
References IG.Lib.XmlUtilityBase.ContainedInDocument(), IG.Lib.XmlParser.Current, IG.Lib.XmlParser.Doc, IG.Lib.XmlParser.Parent, IG.Lib.XmlParser.Previous, IG.Lib.XmlUtilityBase.R, and IG.Lib.IReporterBase.ReportError().
MoveTo() [4/4]
XmlNode IG.Lib.XmlParser.MoveTo (string path) inline
Moves the current position to the first node that satisfies the absolute path specified as an XPath string.
Parameters
path XPath string that specifies the node position relative to the document root.
Returns
The node to which the current position has moved, or null if not successful.
References IG.Lib.XmlParser.GetNode(), and IG.Lib.XmlParser.MoveTo().
MoveRelative() [2/2]
XmlNode IG.Lib.XmlParser.MoveRelative (string path) inline
Moves the current position to the first node that satisfies the relative path specified as an XPath string relative to the current node.
Parameters
path XPath string that specifies the node position relative to the current node.
Returns
The node to which the current position has moved, or null if not successful.
References IG.Lib.XmlParser.GetRelative(), and IG.Lib.XmlParser.MoveTo().
GoToParent() [2/2]
XmlNode IG.Lib.XmlParser.GoToParent () inline
Sets the current node to the parent node of the current node and returns it. This also works if the Current node is null because the advancing fell out of range or because StepIn was executed but there were no child nodes of the current node.
Returns
The current node.
References IG.Lib.XmlParser.Current, IG.Lib.XmlParser.Parent, and IG.Lib.XmlParser.Previous.
GoToRoot() [2/2]
XmlNode IG.Lib.XmlParser.GoToRoot () inline
Sets the current node to the root node of the current document and returns it.
Returns
The current node.
References IG.Lib.XmlParser.Current, IG.Lib.XmlParser.Previous, and IG.Lib.XmlUtilityBase.Root.
GoToDocument() [2/2]
XmlNode IG.Lib.XmlParser.GoToDocument () inline
Sets the current node to the root node of the current document and returns it.
Returns
The current node.
References IG.Lib.XmlParser.Current, IG.Lib.XmlParser.Doc, and IG.Lib.XmlParser.Previous.
StepIn() [2/2]
XmlNode IG.Lib.XmlParser.StepIn () inline
Moves the current node to its first child node and returns the node.
References IG.Lib.XmlParser._parent, IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.Previous.
StepOut() [2/2]
XmlNode IG.Lib.XmlParser.StepOut () inline
Steps out of the current childnodes context and selects the next node of the parent as the current node. This also works if the Current node is null because the advancing fell out of range or because StepIn was executed but there were no child nodes of the current node.
Returns
References IG.Lib.XmlParser.Current, IG.Lib.XmlParser.Parent, and IG.Lib.XmlParser.Previous.
NextNode() [7/12]
XmlNode IG.Lib.XmlParser.NextNode () inline
Sets the current node to the next sibling node, or to null if the next sibling node does not exist, and returns that node.
References IG.Lib.XmlParser.Current, and IG.Lib.XmlParser.Previous.
NextNodeConditional() [2/2]
XmlNode IG.Lib.XmlParser.NextNodeConditional (XmlNodeType NodeType, string NodeName, string NodeValue, bool IncludeCurrent) inline
Moves the current node to the first sibling node of the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeType If not None then the current node must have this type.
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
IncludeCurrent If true then the new current node can also be the current node (if it satisfies the conditions), otherwise the search starts at the next sibling of the current node.
Returns
References IG.Lib.XmlParser.Current, IG.Lib.XmlParser.GetNextNode(), and IG.Lib.XmlParser.Previous.
NextNode() [8/12]
XmlNode IG.Lib.XmlParser.NextNode (XmlNodeType NodeType, string NodeName, string NodeValue) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeType If not None then the current node must have this type.
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.NextNodeConditional().
NextNode() [9/12]
XmlNode IG.Lib.XmlParser.NextNode (XmlNodeType NodeType, string NodeName) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeType If not None then the current node must have this type.
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.NextNodeConditional().
NextNode() [10/12]
XmlNode IG.Lib.XmlParser.NextNode (XmlNodeType NodeType) inline
Moves the current node to the first sibling node after the current node that is of the specified type.
Parameters
NodeType If not None then the current node must have this type.
References IG.Lib.XmlParser.NextNodeConditional().
NextNode() [11/12]
XmlNode IG.Lib.XmlParser.NextNode (string NodeName, string NodeValue) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
Parameters
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.NextNodeConditional().
NextNode() [12/12]
XmlNode IG.Lib.XmlParser.NextNode (string NodeName) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
Parameters
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.NextNodeConditional().
NextOrCurrentNode() [6/10]
XmlNode IG.Lib.XmlParser.NextOrCurrentNode (XmlNodeType NodeType, string NodeName, string NodeValue) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeType If not None then the current node must have this type.
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.NextNodeConditional().
NextOrCurrentNode() [7/10]
XmlNode IG.Lib.XmlParser.NextOrCurrentNode (XmlNodeType NodeType, string NodeName) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeType If not None then the current node must have this type.
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.NextNodeConditional().
NextOrCurrentNode() [8/10]
XmlNode IG.Lib.XmlParser.NextOrCurrentNode (XmlNodeType NodeType) inline
Moves the current node to the current or the first sibling node after the current node that is of the specified type.
Parameters
NodeType If not None then the current node must have this type.
References IG.Lib.XmlParser.NextNodeConditional().
NextOrCurrentNode() [9/10]
XmlNode IG.Lib.XmlParser.NextOrCurrentNode (string NodeName, string NodeValue) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
Parameters
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.NextNodeConditional().
NextOrCurrentNode() [10/10]
XmlNode IG.Lib.XmlParser.NextOrCurrentNode (string NodeName) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node. Node type is not important.
Parameters
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.NextNodeConditional().
NextElement() [4/6]
XmlNode IG.Lib.XmlParser.NextElement (string NodeName, string NodeValue) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.NextNodeConditional().
NextElement() [5/6]
XmlNode IG.Lib.XmlParser.NextElement (string NodeName) inline
Moves the current node to the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.NextNodeConditional().
NextElement() [6/6]
XmlNode IG.Lib.XmlParser.NextElement () inline
Moves the current node to the first sibling element after the current node.
References IG.Lib.XmlParser.NextNodeConditional().
NextOrCurrentElement() [4/6]
XmlNode IG.Lib.XmlParser.NextOrCurrentElement (string NodeName, string NodeValue) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeName If not null then the current node must have this name.
NodeValue If not null then the current node muust have this value.
References IG.Lib.XmlParser.NextNodeConditional().
NextOrCurrentElement() [5/6]
XmlNode IG.Lib.XmlParser.NextOrCurrentElement (string NodeName) inline
Moves the current node to the current or the first sibling node after the current node that satisfies the specified conditions, and returns the current node.
Parameters
NodeName If not null then the current node must have this name.
References IG.Lib.XmlParser.NextNodeConditional().
NextOrCurrentElement() [6/6]
XmlNode IG.Lib.XmlParser.NextOrCurrentElement () inline
Moves the current node to the current or the first sibling element after the current node.
References IG.Lib.XmlParser.NextNodeConditional().
Member Data Documentation
_current
XmlNode IG.Lib.XmlParser._current = null private
_previous
XmlNode IG.Lib.XmlParser._previous = null private
_parent
XmlNode IG.Lib.XmlParser._parent = null private
Referenced by IG.Lib.XmlParser.StepIn().
marks
List< Mark > IG.Lib.XmlParser.marks = new List<Mark>() private
Referenced by IG.Lib.XmlParser.GoToMark(), IG.Lib.XmlParser.RemoveMark(), IG.Lib.XmlParser.RemoveMarks(), and IG.Lib.XmlParser.SetMark().
Property Documentation
Doc
override XmlDocument IG.Lib.XmlParser.Doc get set
Xml document that represents the message.
Xml document that represents the msg.
Referenced by IG.Lib.XmlBuilder.AddProcessingInstruction(), IG.Lib.XmlBuilder.CreateClone(), IG.Lib.XmlBuilder.CreateNode(), IG.Lib.XmlParser.GoToDocument(), IG.Lib.XmlParser.MoveTo(), IG.Lib.XmlBuilder.NewDocument(), IG.Lib.XmlBuilder.NewXmlDocument(), IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgFinancialTransaction.Read(), IG.Lib.DocFindings.Read(), IG.Lib.MsgObervationOrder.Read(), IG.Lib.XmlBuilder.SetValue(), IG.Lib.MsgFinancialTransaction.ToXml(), IG.Lib.MsgObservationEvent.ToXml(), and IG.Lib.MsgObervationOrder.ToXml().
Current
XmlNode IG.Lib.XmlParser.Current get set
The current node on which all queries are performed.
Referenced by IG.Lib.XmlBuilder.AppendChild(), IG.Lib.XmlParser.Back(), IG.Lib.XmlBuilder.CreateClone(), IG.Lib.XmlParser.GetNextElement(), IG.Lib.XmlParser.GetNextNode(), IG.Lib.XmlParser.GetNextOrCurrentElement(), IG.Lib.XmlParser.GetNextOrCurrentNode(), IG.Lib.XmlParser.GetRelative(), IG.Lib.XmlParser.GoToDocument(), IG.Lib.XmlParser.GoToMark(), IG.Lib.XmlParser.GoToParent(), IG.Lib.XmlParser.GoToRoot(), IG.Lib.XmlBuilder.InsertAfter(), IG.Lib.XmlBuilder.InsertBefore(), IG.Lib.MsgBase.IsDetailedFinancialTransaction(), IG.Lib.MsgBase.IsSpecimenObservationEvent(), IG.Lib.MsgBase.IsSpecimenObservationOrder(), IG.Lib.XmlParser.MoveTo(), IG.Lib.XmlParser.NextNode(), IG.Lib.XmlParser.NextNodeConditional(), IG.Lib.XmlBuilder.PrependChild(), IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgFinancialTransaction.Read(), IG.Lib.DocFindings.Read(), IG.Lib.MsgObervationOrder.Read(), IG.Lib.XmlBuilder.RemoveCurrent(), IG.Lib.XmlBuilder.RemoveNode(), IG.Lib.XmlParser.SetMark(), IG.Lib.XmlParser.StepIn(), IG.Lib.XmlParser.StepOut(), IG.Lib.MsgFinancialTransaction.ToXml(), and IG.Lib.MsgObservationEvent.ToXml().
Previous
XmlNode IG.Lib.XmlParser.Previous get set
The node that was previously set to the current node.
Referenced by IG.Lib.XmlParser.Back(), IG.Lib.XmlParser.GoToDocument(), IG.Lib.XmlParser.GoToMark(), IG.Lib.XmlParser.GoToParent(), IG.Lib.XmlParser.GoToRoot(), IG.Lib.XmlParser.MoveTo(), IG.Lib.XmlParser.NextNode(), IG.Lib.XmlParser.NextNodeConditional(), IG.Lib.XmlBuilder.RemoveNode(), IG.Lib.XmlParser.SetMark(), IG.Lib.XmlParser.StepIn(), and IG.Lib.XmlParser.StepOut().
Parent
XmlNode IG.Lib.XmlParser.Parent get private set
Parent of Current. If Current = null then Parent can still return something, which happens in particular when StepIn was performed before. Parent can be set to a specific node. That node will be returned by Parent when the Current is null (otherwise, the parent of Current is still returned). This is useful when current becomes null, e.g. because of running out of index bounds.
Referenced by IG.Lib.XmlParser.GoToMark(), IG.Lib.XmlParser.GoToParent(), IG.Lib.XmlBuilder.InsertAfter(), IG.Lib.XmlBuilder.InsertBefore(), IG.Lib.XmlParser.MoveTo(), IG.Lib.XmlBuilder.RemoveNode(), IG.Lib.XmlParser.SetMark(), and IG.Lib.XmlParser.StepOut().
ParentElement
XmlElement IG.Lib.XmlParser.ParentElement get protected
CurrentElement
XmlElement IG.Lib.XmlParser.CurrentElement get protected
Referenced by IG.Lib.XmlParser.Attribute(), and IG.Lib.MsgFinancialTransaction.Read().
PreviousElement
XmlElement IG.Lib.XmlParser.PreviousElement get protected
Name
string IG.Lib.XmlParser.Name get
Returns the name of the current node.
Referenced by IG.Lib.MsgBase.IsDetailedFinancialTransaction(), IG.Lib.MsgBase.IsSpecimenObservationEvent(), IG.Lib.MsgBase.IsSpecimenObservationOrder(), IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgFinancialTransaction.Read(), IG.Lib.DocFindings.Read(), IG.Lib.MsgObervationOrder.Read(), IG.Lib.MsgFinancialTransaction.ToXml(), and IG.Lib.MsgObservationEvent.ToXml().
Value
string IG.Lib.XmlParser.Value get
Returns the value of the current node. If the current node is an element then the value of its first text child element is returned.
Returns the value of the current node. If the current node is an element then the value of its first Text child element is returned.
Referenced by IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgFinancialTransaction.Read(), IG.Lib.DocFindings.Read(), and IG.Lib.MsgObervationOrder.Read().
InnerText
string IG.Lib.XmlParser.InnerText get
Returns the inner text of the current node.
Returns the inner Text of the current node.
The documentation for this class was generated from the following files:
iglib/igbase/0unsorted/XmlUtilities.cs
igtest/tmp_prem/prlab/LabexBis/MessagesBis.cs