Doc: IGLib EXTENDED: NUnit.Framework.Attributes.DatapointTests Class Reference
NUnit.Framework.Attributes.DatapointTests Class Reference
Public Member Functions
void WorksOnField ()
void WorksOnArray ()
void WorksOnPropertyReturningArray ()
void WorksOnMethodReturningArray ()
void WorksOnIEnumerableOfT ()
void WorksOnPropertyReturningIEnumerableOfT ()
void WorksOnMethodReturningIEnumerableOfT ()
void WorksOnEnumeratorReturningIEnumerableOfT ()
Private Member Functions
void RunTestOnFixture (Type fixtureType)
Member Function Documentation
RunTestOnFixture()
void NUnit.Framework.Attributes.DatapointTests.RunTestOnFixture (Type fixtureType) inline private
References NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.ResultSummary.Inconclusive, NUnit.TestUtilities.ResultSummary.Passed, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.Framework.Interfaces.ResultState.Success, and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Attributes.DatapointTests.WorksOnArray(), NUnit.Framework.Attributes.DatapointTests.WorksOnEnumeratorReturningIEnumerableOfT(), NUnit.Framework.Attributes.DatapointTests.WorksOnField(), NUnit.Framework.Attributes.DatapointTests.WorksOnIEnumerableOfT(), NUnit.Framework.Attributes.DatapointTests.WorksOnMethodReturningArray(), NUnit.Framework.Attributes.DatapointTests.WorksOnMethodReturningIEnumerableOfT(), NUnit.Framework.Attributes.DatapointTests.WorksOnPropertyReturningArray(), and NUnit.Framework.Attributes.DatapointTests.WorksOnPropertyReturningIEnumerableOfT().
WorksOnField()
void NUnit.Framework.Attributes.DatapointTests.WorksOnField () inline
References NUnit.Framework.Attributes.DatapointTests.RunTestOnFixture().
WorksOnArray()
void NUnit.Framework.Attributes.DatapointTests.WorksOnArray () inline
References NUnit.Framework.Attributes.DatapointTests.RunTestOnFixture().
WorksOnPropertyReturningArray()
void NUnit.Framework.Attributes.DatapointTests.WorksOnPropertyReturningArray () inline
References NUnit.Framework.Attributes.DatapointTests.RunTestOnFixture().
WorksOnMethodReturningArray()
void NUnit.Framework.Attributes.DatapointTests.WorksOnMethodReturningArray () inline
References NUnit.Framework.Attributes.DatapointTests.RunTestOnFixture().
WorksOnIEnumerableOfT()
void NUnit.Framework.Attributes.DatapointTests.WorksOnIEnumerableOfT () inline
References NUnit.Framework.Attributes.DatapointTests.RunTestOnFixture().
WorksOnPropertyReturningIEnumerableOfT()
void NUnit.Framework.Attributes.DatapointTests.WorksOnPropertyReturningIEnumerableOfT () inline
References NUnit.Framework.Attributes.DatapointTests.RunTestOnFixture().
WorksOnMethodReturningIEnumerableOfT()
void NUnit.Framework.Attributes.DatapointTests.WorksOnMethodReturningIEnumerableOfT () inline
References NUnit.Framework.Attributes.DatapointTests.RunTestOnFixture().
WorksOnEnumeratorReturningIEnumerableOfT()
void NUnit.Framework.Attributes.DatapointTests.WorksOnEnumeratorReturningIEnumerableOfT () inline
References NUnit.Framework.Attributes.DatapointTests.RunTestOnFixture().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/DatapointTests.cs