Doc: IGLib EXTENDED: IG.test.GZipTest Class Reference
IG.test.GZipTest Class Reference
Static Public Member Functions
static void ReadFileToMemoryStream (string sourcefile, MemoryStream ms)
static int ReadAllBytesFromStream (Stream stream, byte[] buffer)
static bool CompareData (byte[] buf1, int len1, byte[] buf2, int len2)
Compares data from two defferent buffers.
static byte[] CompressBytes (byte[] Original)
static byte[] UncompressBytes (byte[] zippedArray)
static void GZipCompressDecompress (string filename)
static void Main0 (string[] args)
Static Private Member Functions
static void ReportError (Exception ex)
Static Private Attributes
const int buffer_size = 40
Member Function Documentation
ReportError()
static void IG.test.GZipTest.ReportError (Exception ex) inline static private
Referenced by IG.test.GZipTest.CompressBytes(), and IG.test.GZipTest.UncompressBytes().
ReadFileToMemoryStream()
static void IG.test.GZipTest.ReadFileToMemoryStream (string sourcefile, MemoryStream ms) inline static
References IG.test.GZipTest.buffer_size.
ReadAllBytesFromStream()
static int IG.test.GZipTest.ReadAllBytesFromStream (Stream stream, byte[] buffer) inline static
References IG.test.GZipTest.buffer_size.
CompareData()
static bool IG.test.GZipTest.CompareData (byte[] buf1, int len1, byte[] buf2, int len2) inline static
Compares data from two defferent buffers.
Returns
true if buffers contain the same data, false otherwise.
Referenced by IG.test.GZipTest.GZipCompressDecompress().
CompressBytes()
static byte [] IG.test.GZipTest.CompressBytes (byte[] Original) inline static
References IG.test.GZipTest.ReportError().
Referenced by IG.test.GZipTest.GZipCompressDecompress().
UncompressBytes()
static byte [] IG.test.GZipTest.UncompressBytes (byte[] zippedArray) inline static
References IG.test.GZipTest.ReportError().
Referenced by IG.test.GZipTest.GZipCompressDecompress().
GZipCompressDecompress()
static void IG.test.GZipTest.GZipCompressDecompress (string filename) inline static
References IG.test.GZipTest.CompareData(), IG.test.GZipTest.CompressBytes(), and IG.test.GZipTest.UncompressBytes().
Referenced by IG.test.GZipTest.Main0().
Main0()
static void IG.test.GZipTest.Main0 (string[] args) inline static
References IG.test.GZipTest.GZipCompressDecompress().
Member Data Documentation
buffer_size
const int IG.test.GZipTest.buffer_size = 40 static private
Referenced by IG.test.GZipTest.ReadAllBytesFromStream(), and IG.test.GZipTest.ReadFileToMemoryStream().
The documentation for this class was generated from the following file:
igtest/iglib_form/TestCompression.cs