Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAHR2 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAHR2 Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAHR2 (DAXPY daxpy, DCOPY dcopy, DGEMM dgemm, DGEMV dgemv, DLACPY dlacpy, DLARFG dlarfg, DSCAL dscal, DTRMM dtrmm, DTRMV dtrmv)
DLAHR2 ()
void Run (int N, int K, int NB, ref double[] A, int offset_a, int LDA, ref double[] TAU, int offset_tau, ref double[] T, int offset_t, int LDT, ref double[] Y, int offset_y, int LDY)
Private Attributes
DAXPY _daxpy
DCOPY _dcopy
DGEMM _dgemm
DGEMV _dgemv
DLACPY _dlacpy
DLARFG _dlarfg
DSCAL _dscal
DTRMM _dtrmm
DTRMV _dtrmv
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAHR2 reduces the first NB columns of A real general n-BY-(n-k+1) matrix A so that elements below the k-th subdiagonal are zero. The reduction is performed by an orthogonal similarity transformation Q' * A * Q. The routine returns the matrices V and T which determine Q as a block reflector I - V*T*V', and also the matrix Y = A * V * T.
This is an auxiliary routine called by DGEHRD.
/summary>
Constructor & Destructor Documentation
DLAHR2() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAHR2.DLAHR2 (DAXPY daxpy, DCOPY dcopy, DGEMM dgemm, DGEMV dgemv, DLACPY dlacpy, DLARFG dlarfg, DSCAL dscal, DTRMM dtrmm, DTRMV dtrmv) inline
DLAHR2() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAHR2.DLAHR2 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAHR2.Run (int N, int K, int NB, ref double[] A, int offset_a, int LDA, ref double[] TAU, int offset_tau, ref double[] T, int offset_t, int LDT, ref double[] Y, int offset_y, int LDY) inline
Purpose
DLAHR2 reduces the first NB columns of A real general n-BY-(n-k+1) matrix A so that elements below the k-th subdiagonal are zero. The reduction is performed by an orthogonal similarity transformation Q' * A * Q. The routine returns the matrices V and T which determine Q as a block reflector I - V*T*V', and also the matrix Y = A * V * T.
This is an auxiliary routine called by DGEHRD.
/summary>
Parameters
N (input) INTEGER The order of the matrix A. /param>
Parameters
K (input) INTEGER The offset for the reduction. Elements below the k-th subdiagonal in the first NB columns are reduced to zero. K .LT. N. /param>
Parameters
NB (input) INTEGER The number of columns to be reduced. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N-K+1) On entry, the n-by-(n-k+1) general matrix A. On exit, the elements on and above the k-th subdiagonal in the first NB columns are overwritten with the corresponding elements of the reduced matrix; the elements below the k-th subdiagonal, with the array TAU, represent the matrix Q as a product of elementary reflectors. The other columns of A are unchanged. See Further Details. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,N). /param>
Parameters
TAU (output) DOUBLE PRECISION array, dimension (NB) The scalar factors of the elementary reflectors. See Further Details. /param>
Parameters
T (output) DOUBLE PRECISION array, dimension (LDT,NB) The upper triangular matrix T. /param>
Parameters
LDT (input) INTEGER The leading dimension of the array T. LDT .GE. NB. /param>
Parameters
Y (output) DOUBLE PRECISION array, dimension (LDY,NB) The n-by-nb matrix Y. /param>
Parameters
LDY (input) INTEGER The leading dimension of the array Y. LDY .GE. N. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLAHR2.ONE, DotNumerics.LinearAlgebra.CSLapack.DAXPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRMV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRMM.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAHR2.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEHRD.Run().
Member Data Documentation
_daxpy
DAXPY DotNumerics.LinearAlgebra.CSLapack.DLAHR2._daxpy private
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLAHR2._dcopy private
_dgemm
DGEMM DotNumerics.LinearAlgebra.CSLapack.DLAHR2._dgemm private
_dgemv
DGEMV DotNumerics.LinearAlgebra.CSLapack.DLAHR2._dgemv private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DLAHR2._dlacpy private
_dlarfg
DLARFG DotNumerics.LinearAlgebra.CSLapack.DLAHR2._dlarfg private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DLAHR2._dscal private
_dtrmm
DTRMM DotNumerics.LinearAlgebra.CSLapack.DLAHR2._dtrmm private
_dtrmv
DTRMV DotNumerics.LinearAlgebra.CSLapack.DLAHR2._dtrmv private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAHR2.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAHR2.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAHR2.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAHR2.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlahr2.cs