Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGER Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGER Class Reference
Public Member Functions
DGER (XERBLA xerbla)
DGER ()
void Run (int M, int N, double ALPHA, double[] X, int offset_x, int INCX, double[] Y, int offset_y, int INCY, ref double[] A, int offset_a, int LDA)
Private Attributes
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E+0
Detailed Description
Purpose
DGER performs the rank 1 operation
A := alpha*x*y' + A,
where alpha is a scalar, x is an m element vector, y is an n element vector and A is an m by n matrix.
/summary>
Constructor & Destructor Documentation
DGER() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGER.DGER (XERBLA xerbla) inline
DGER() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGER.DGER () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGER.Run (int M, int N, double ALPHA, double[] X, int offset_x, int INCX, double[] Y, int offset_y, int INCY, ref double[] A, int offset_a, int LDA) inline
Purpose
DGER performs the rank 1 operation
A := alpha*x*y' + A,
where alpha is a scalar, x is an m element vector, y is an n element vector and A is an m by n matrix.
/summary>
Parameters
M
INTEGER. On entry, M specifies the number of rows of the matrix A. M must be at least zero. Unchanged on exit. /param>
Parameters
N
INTEGER. On entry, N specifies the number of columns of the matrix A. N must be at least zero. Unchanged on exit. /param>
Parameters
ALPHA
DOUBLE PRECISION. On entry, ALPHA specifies the scalar alpha. Unchanged on exit. /param>
Parameters
X
DOUBLE PRECISION array of dimension at least (1 + (m - 1)*abs(INCX)). Before entry, the incremented array X must contain the m element vector x. Unchanged on exit. /param>
Parameters
INCX
INTEGER. On entry, INCX specifies the increment for the elements of X. INCX must not be zero. Unchanged on exit. /param>
Parameters
Y
DOUBLE PRECISION array of dimension at least (1 + (n - 1)*abs(INCY)). Before entry, the incremented array Y must contain the n element vector y. Unchanged on exit. /param>
Parameters
INCY
INTEGER. On entry, INCY specifies the increment for the elements of Y. INCY must not be zero. Unchanged on exit. /param>
Parameters
A := alpha*x*y' + A, /param>
Parameters
LDA
INTEGER. On entry, LDA specifies the first dimension of A as declared in the calling (sub) program. LDA must be at least max(1, m). Unchanged on exit.
/param>
References DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGER.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGBTF2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFX.Run(), DotNumerics.LinearAlgebra.CSLapack.DGETF2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARZ.Run(), DotNumerics.LinearAlgebra.CSLapack.DGBTRS.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGBTRF.Run().
Member Data Documentation
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGER._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DGER.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGER.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dger.cs