Doc: IGLib EXTENDED: NUnit.Framework.Attributes.AttributeInheritanceTests Class Reference
NUnit.Framework.Attributes.AttributeInheritanceTests Class Reference
Public Member Functions
void InheritedFixtureAttributeIsRecognized ()
void InheritedTestAttributeIsRecognized ()
Member Function Documentation
InheritedFixtureAttributeIsRecognized()
void NUnit.Framework.Attributes.AttributeInheritanceTests.InheritedFixtureAttributeIsRecognized () inline
References NUnit.TestUtilities.TestBuilder.MakeFixture(), and NUnit.Framework.Assert.That().
InheritedTestAttributeIsRecognized()
void NUnit.Framework.Attributes.AttributeInheritanceTests.InheritedTestAttributeIsRecognized () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestUtilities.TestBuilder.MakeFixture(), and NUnit.Framework.Internal.Test.TestCaseCount.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/AttributeInheritanceTests.cs