Doc: IGLib EXTENDED: alglib.minqp Class Reference
alglib.minqp Class Reference
Classes
class minqpreport
class minqpstate
Static Public Member Functions
static void minqpcreate (int n, minqpstate state)
static void minqpsetlinearterm (minqpstate state, double[] b)
static void minqpsetquadraticterm (minqpstate state, double[,] a, bool isupper)
static void minqpsetstartingpoint (minqpstate state, double[] x)
static void minqpsetorigin (minqpstate state, double[] xorigin)
static void minqpsetalgocholesky (minqpstate state)
static void minqpsetbc (minqpstate state, double[] bndl, double[] bndu)
static void minqpsetlc (minqpstate state, double[,] c, int[] ct, int k)
static void minqpoptimize (minqpstate state)
static void minqpresults (minqpstate state, ref double[] x, minqpreport rep)
static void minqpresultsbuf (minqpstate state, ref double[] x, minqpreport rep)
static void minqpsetlineartermfast (minqpstate state, double[] b)
static void minqpsetquadratictermfast (minqpstate state, double[,] a, bool isupper, double s)
static void minqprewritediagonal (minqpstate state, double[] s)
static void minqpsetstartingpointfast (minqpstate state, double[] x)
static void minqpsetoriginfast (minqpstate state, double[] xorigin)
static void minqpcreate (int n, minqpstate state)
static void minqpsetlinearterm (minqpstate state, double[] b)
static void minqpsetquadraticterm (minqpstate state, double[,] a, bool isupper)
static void minqpsetquadratictermsparse (minqpstate state, sparse.sparsematrix a, bool isupper)
static void minqpsetstartingpoint (minqpstate state, double[] x)
static void minqpsetorigin (minqpstate state, double[] xorigin)
static void minqpsetscale (minqpstate state, double[] s)
static void minqpsetalgocholesky (minqpstate state)
static void minqpsetalgobleic (minqpstate state, double epsg, double epsf, double epsx, int maxits)
static void minqpsetbc (minqpstate state, double[] bndl, double[] bndu)
static void minqpsetlc (minqpstate state, double[,] c, int[] ct, int k)
static void minqpoptimize (minqpstate state)
static void minqpresults (minqpstate state, ref double[] x, minqpreport rep)
static void minqpresultsbuf (minqpstate state, ref double[] x, minqpreport rep)
static void minqpsetlineartermfast (minqpstate state, double[] b)
static void minqpsetquadratictermfast (minqpstate state, double[,] a, bool isupper, double s)
static void minqprewritediagonal (minqpstate state, double[] s)
static void minqpsetstartingpointfast (minqpstate state, double[] x)
static void minqpsetoriginfast (minqpstate state, double[] xorigin)
Static Public Attributes
const int badqpitsbeforetermination = 5
const int maxlagrangeits = 10
const int maxbadnewtonits = 7
const double penaltyfactor = 100.0
Static Private Member Functions
static int minqpdropconstraints (minqpstate state, double[] xc, ref double[] buf)
static int minqpboundedstepandactivation (minqpstate state, ref double[] xc, double[] xn, ref double[] buf)
static double minqpmodelvalue (cqmodels.convexquadraticmodel a, double[] b, double[] xc, int n, ref double[] tmp)
static double minqpgradientandconstraineddescent (minqpstate state, double[] xc, ref double[] gc, ref double[] d)
static bool minqpconstrainedoptimum (cqmodels.convexquadraticmodel a, double anorm, double[] b, bool[] activeb, double[] xc, int n, double[,] c, double[] r, int k, ref double[] xn, ref double[] tmp, ref double[] lagrangec)
static void orthogonalizeactiveconstraints (double[] xc, bool[] activeb, int n, double[,] cleic, bool[] activelin, int ctotal, ref double[,] activecm, ref double[] activecr, ref int nactive)
static int minqpboundedstepandactivation (minqpstate state, double[] xn, ref double[] buf)
static double minqpmodelvalue (cqmodels.convexquadraticmodel a, double[] b, double[] xc, int n, ref double[] tmp)
static bool minqpconstrainedoptimum (minqpstate state, cqmodels.convexquadraticmodel a, double anorm, double[] b, ref double[] xn, ref double[] tmp, ref bool[] tmpb, ref double[] lagrangec)
Member Function Documentation
minqpcreate() [1/2]
static void alglib.minqp.minqpcreate (int n, minqpstate state) inline static
Referenced by alglib.testminqpunit.bleictests(), alglib.testminqpunit.choleskytests(), alglib.testminqpunit.consoletest(), alglib.testminqpunit.ecqptest(), alglib.testminqpunit.functest1(), alglib.testminqpunit.functest2(), alglib.testminqpunit.icqptest(), alglib.minqpcreate(), alglib.testminqpunit.simpletest(), and alglib.testminqpunit.specialicqptests().
minqpsetlinearterm() [1/2]
static void alglib.minqp.minqpsetlinearterm (minqpstate state, double[] b) inline static
Referenced by alglib.testminqpunit.bleictests(), alglib.testminqpunit.consoletest(), alglib.testminqpunit.ecqptest(), alglib.testminqpunit.functest1(), alglib.testminqpunit.functest2(), alglib.testminqpunit.icqptest(), alglib.minqpsetlinearterm(), and alglib.testminqpunit.specialicqptests().
minqpsetquadraticterm() [1/2]
static void alglib.minqp.minqpsetquadraticterm (minqpstate state, double a[,], bool isupper) inline static
Referenced by alglib.testminqpunit.bleictests(), alglib.testminqpunit.choleskytests(), alglib.testminqpunit.consoletest(), alglib.testminqpunit.ecqptest(), alglib.testminqpunit.functest1(), alglib.testminqpunit.functest2(), alglib.testminqpunit.icqptest(), alglib.minqpsetquadraticterm(), alglib.testminqpunit.simpletest(), and alglib.testminqpunit.specialicqptests().
minqpsetstartingpoint() [1/2]
static void alglib.minqp.minqpsetstartingpoint (minqpstate state, double[] x) inline static
Referenced by alglib.testminqpunit.bleictests(), alglib.testminqpunit.choleskytests(), alglib.testminqpunit.ecqptest(), alglib.testminqpunit.functest1(), alglib.testminqpunit.functest2(), alglib.testminqpunit.icqptest(), alglib.minqpsetstartingpoint(), alglib.testminqpunit.simpletest(), and alglib.testminqpunit.specialicqptests().
minqpsetorigin() [1/2]
static void alglib.minqp.minqpsetorigin (minqpstate state, double[] xorigin) inline static
Referenced by alglib.testminqpunit.consoletest(), alglib.testminqpunit.ecqptest(), alglib.testminqpunit.functest1(), alglib.testminqpunit.functest2(), alglib.testminqpunit.icqptest(), alglib.minqpsetorigin(), and alglib.testminqpunit.simpletest().
minqpsetalgocholesky() [1/2]
static void alglib.minqp.minqpsetalgocholesky (minqpstate state) inline static
Referenced by alglib.testminqpunit.choleskytests(), alglib.minqpsetalgocholesky(), and alglib.testminqpunit.setrandomalgo().
minqpsetbc() [1/2]
static void alglib.minqp.minqpsetbc (minqpstate state, double[] bndl, double[] bndu) inline static
Referenced by alglib.testminqpunit.bleictests(), alglib.testminqpunit.choleskytests(), alglib.testminqpunit.consoletest(), alglib.testminqpunit.ecqptest(), alglib.testminqpunit.functest2(), alglib.testminqpunit.icqptest(), alglib.minqpsetbc(), alglib.testminqpunit.simpletest(), and alglib.testminqpunit.specialicqptests().
minqpsetlc() [1/2]
static void alglib.minqp.minqpsetlc (minqpstate state, double c[,], int[] ct, int k) inline static
Referenced by alglib.testminqpunit.bleictests(), alglib.testminqpunit.ecqptest(), alglib.testminqpunit.icqptest(), alglib.minqpsetlc(), and alglib.testminqpunit.specialicqptests().
minqpoptimize() [1/2]
static void alglib.minqp.minqpoptimize (minqpstate state) inline static
Referenced by alglib.testminqpunit.bleictests(), alglib.testminqpunit.choleskytests(), alglib.testminqpunit.consoletest(), alglib.testminqpunit.ecqptest(), alglib.testminqpunit.functest1(), alglib.testminqpunit.functest2(), alglib.testminqpunit.icqptest(), alglib.minqpoptimize(), alglib.testminqpunit.simpletest(), and alglib.testminqpunit.specialicqptests().
minqpresults() [1/2]
static void alglib.minqp.minqpresults (minqpstate state, ref double[] x, minqpreport rep) inline static
Referenced by alglib.testminqpunit.bleictests(), alglib.testminqpunit.choleskytests(), alglib.testminqpunit.consoletest(), alglib.testminqpunit.ecqptest(), alglib.testminqpunit.functest1(), alglib.testminqpunit.functest2(), alglib.testminqpunit.icqptest(), alglib.minqpresults(), alglib.testminqpunit.simpletest(), and alglib.testminqpunit.specialicqptests().
minqpresultsbuf() [1/2]
static void alglib.minqp.minqpresultsbuf (minqpstate state, ref double[] x, minqpreport rep) inline static
Referenced by alglib.minqpresultsbuf().
minqpsetlineartermfast() [1/2]
static void alglib.minqp.minqpsetlineartermfast (minqpstate state, double[] b) inline static
minqpsetquadratictermfast() [1/2]
static void alglib.minqp.minqpsetquadratictermfast (minqpstate state, double a[,], bool isupper, double s) inline static
minqprewritediagonal() [1/2]
static void alglib.minqp.minqprewritediagonal (minqpstate state, double[] s) inline static
minqpsetstartingpointfast() [1/2]
static void alglib.minqp.minqpsetstartingpointfast (minqpstate state, double[] x) inline static
minqpsetoriginfast() [1/2]
static void alglib.minqp.minqpsetoriginfast (minqpstate state, double[] xorigin) inline static
minqpdropconstraints()
static int alglib.minqp.minqpdropconstraints (minqpstate state, double[] xc, ref double[] buf) inline static private
minqpboundedstepandactivation() [1/2]
static int alglib.minqp.minqpboundedstepandactivation (minqpstate state, ref double[] xc, double[] xn, ref double[] buf) inline static private
minqpmodelvalue() [1/2]
static double alglib.minqp.minqpmodelvalue (cqmodels.convexquadraticmodel a, double[] b, double[] xc, int n, ref double[] tmp) inline static private
minqpgradientandconstraineddescent()
static double alglib.minqp.minqpgradientandconstraineddescent (minqpstate state, double[] xc, ref double[] gc, ref double[] d) inline static private
minqpconstrainedoptimum() [1/2]
static bool alglib.minqp.minqpconstrainedoptimum (cqmodels.convexquadraticmodel a, double anorm, double[] b, bool[] activeb, double[] xc, int n, double c[,], double[] r, int k, ref double[] xn, ref double[] tmp, ref double[] lagrangec) inline static private
orthogonalizeactiveconstraints()
static void alglib.minqp.orthogonalizeactiveconstraints (double[] xc, bool[] activeb, int n, double cleic[,], bool[] activelin, int ctotal, ref double activecm[,], ref double[] activecr, ref int nactive) inline static private
minqpcreate() [2/2]
static void alglib.minqp.minqpcreate (int n, minqpstate state) inline static
minqpsetlinearterm() [2/2]
static void alglib.minqp.minqpsetlinearterm (minqpstate state, double[] b) inline static
minqpsetquadraticterm() [2/2]
static void alglib.minqp.minqpsetquadraticterm (minqpstate state, double a[,], bool isupper) inline static
minqpsetquadratictermsparse()
static void alglib.minqp.minqpsetquadratictermsparse (minqpstate state, sparse.sparsematrix a, bool isupper) inline static
Referenced by alglib.testminqpunit.bleictests(), alglib.testminqpunit.choleskytests(), and alglib.minqpsetquadratictermsparse().
minqpsetstartingpoint() [2/2]
static void alglib.minqp.minqpsetstartingpoint (minqpstate state, double[] x) inline static
minqpsetorigin() [2/2]
static void alglib.minqp.minqpsetorigin (minqpstate state, double[] xorigin) inline static
minqpsetscale()
static void alglib.minqp.minqpsetscale (minqpstate state, double[] s) inline static
Referenced by alglib.testminqpunit.bleictests(), and alglib.minqpsetscale().
minqpsetalgocholesky() [2/2]
static void alglib.minqp.minqpsetalgocholesky (minqpstate state) inline static
minqpsetalgobleic()
static void alglib.minqp.minqpsetalgobleic (minqpstate state, double epsg, double epsf, double epsx, int maxits) inline static
Referenced by alglib.testminqpunit.bleictests(), alglib.minqpsetalgobleic(), and alglib.testminqpunit.setrandomalgo().
minqpsetbc() [2/2]
static void alglib.minqp.minqpsetbc (minqpstate state, double[] bndl, double[] bndu) inline static
minqpsetlc() [2/2]
static void alglib.minqp.minqpsetlc (minqpstate state, double c[,], int[] ct, int k) inline static
minqpoptimize() [2/2]
static void alglib.minqp.minqpoptimize (minqpstate state) inline static
minqpresults() [2/2]
static void alglib.minqp.minqpresults (minqpstate state, ref double[] x, minqpreport rep) inline static
minqpresultsbuf() [2/2]
static void alglib.minqp.minqpresultsbuf (minqpstate state, ref double[] x, minqpreport rep) inline static
minqpsetlineartermfast() [2/2]
static void alglib.minqp.minqpsetlineartermfast (minqpstate state, double[] b) inline static
minqpsetquadratictermfast() [2/2]
static void alglib.minqp.minqpsetquadratictermfast (minqpstate state, double a[,], bool isupper, double s) inline static
minqprewritediagonal() [2/2]
static void alglib.minqp.minqprewritediagonal (minqpstate state, double[] s) inline static
minqpsetstartingpointfast() [2/2]
static void alglib.minqp.minqpsetstartingpointfast (minqpstate state, double[] x) inline static
minqpsetoriginfast() [2/2]
static void alglib.minqp.minqpsetoriginfast (minqpstate state, double[] xorigin) inline static
minqpboundedstepandactivation() [2/2]
static int alglib.minqp.minqpboundedstepandactivation (minqpstate state, double[] xn, ref double[] buf) inline static private
minqpmodelvalue() [2/2]
static double alglib.minqp.minqpmodelvalue (cqmodels.convexquadraticmodel a, double[] b, double[] xc, int n, ref double[] tmp) inline static private
minqpconstrainedoptimum() [2/2]
static bool alglib.minqp.minqpconstrainedoptimum (minqpstate state, cqmodels.convexquadraticmodel a, double anorm, double[] b, ref double[] xn, ref double[] tmp, ref bool[] tmpb, ref double[] lagrangec) inline static private
Member Data Documentation
badqpitsbeforetermination
const int alglib.minqp.badqpitsbeforetermination = 5 static
maxlagrangeits
const int alglib.minqp.maxlagrangeits = 10 static
maxbadnewtonits
const int alglib.minqp.maxbadnewtonits = 7 static
penaltyfactor
const double alglib.minqp.penaltyfactor = 100.0 static
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/optimization.cs