Doc: IGLib EXTENDED: AForge.Math.Geometry.Tests.LineTest Class Reference
AForge.Math.Geometry.Tests.LineTest Class Reference
Public Member Functions
void RThetaTest (float x, float y, float theta, float expectedRadius, float expectedSlope, float expectedIntercept)
void IsVerticalTest (float sx, float sy, float ex, float ey, bool expectedResult, float expectedSlope, float expectedIntercept)
void IsHorizontalTest (float sx, float sy, float ex, float ey, bool expectedResult, float expectedSlope, float expectedIntercept)
void GetAngleBetweenLinesTest (float sx1, float sy1, float ex1, float ey1, float sx2, float sy2, float ex2, float ey2, float expectedAngle)
void GetIntersectionPointTest (float sx1, float sy1, float ex1, float ey1, float sx2, float sy2, float ex2, float ey2, float xRet, float yRet, bool hasResult)
void DistanceToPointTest (float x, float y, float x1, float y1, float x2, float y2, float expectedDistance)
Static Private Attributes
const float Error = 0.00001f
Member Function Documentation
RThetaTest()
void AForge.Math.Geometry.Tests.LineTest.RThetaTest (float x, float y, float theta, float expectedRadius, float expectedSlope, float expectedIntercept) inline
References AForge.Math.Geometry.Tests.LineTest.Error, AForge.Point.EuclideanNorm(), AForge.Math.Geometry.Line.FromPointTheta(), AForge.Math.Geometry.Line.FromRTheta(), AForge.Math.Geometry.Line.Intercept, and AForge.Math.Geometry.Line.Slope.
IsVerticalTest()
void AForge.Math.Geometry.Tests.LineTest.IsVerticalTest (float sx, float sy, float ex, float ey, bool expectedResult, float expectedSlope, float expectedIntercept) inline
References AForge.Math.Geometry.Line.FromPoints(), AForge.Math.Geometry.Line.Intercept, AForge.Math.Geometry.Line.IsVertical, and AForge.Math.Geometry.Line.Slope.
IsHorizontalTest()
void AForge.Math.Geometry.Tests.LineTest.IsHorizontalTest (float sx, float sy, float ex, float ey, bool expectedResult, float expectedSlope, float expectedIntercept) inline
References AForge.Math.Geometry.Line.FromPoints(), AForge.Math.Geometry.Line.Intercept, AForge.Math.Geometry.Line.IsHorizontal, and AForge.Math.Geometry.Line.Slope.
GetAngleBetweenLinesTest()
void AForge.Math.Geometry.Tests.LineTest.GetAngleBetweenLinesTest (float sx1, float sy1, float ex1, float ey1, float sx2, float sy2, float ex2, float ey2, float expectedAngle) inline
References AForge.Math.Geometry.Tests.LineTest.Error, AForge.Math.Geometry.Line.FromPoints(), and AForge.Math.Geometry.Line.GetAngleBetweenLines().
GetIntersectionPointTest()
void AForge.Math.Geometry.Tests.LineTest.GetIntersectionPointTest (float sx1, float sy1, float ex1, float ey1, float sx2, float sy2, float ex2, float ey2, float xRet, float yRet, bool hasResult) inline
References AForge.Math.Geometry.Line.FromPoints(), and AForge.Math.Geometry.Line.GetIntersectionWith().
DistanceToPointTest()
void AForge.Math.Geometry.Tests.LineTest.DistanceToPointTest (float x, float y, float x1, float y1, float x2, float y2, float expectedDistance) inline
References AForge.Math.Geometry.Line.DistanceToPoint(), AForge.Math.Geometry.Tests.LineTest.Error, and AForge.Math.Geometry.Line.FromPoints().
Member Data Documentation
Error
const float AForge.Math.Geometry.Tests.LineTest.Error = 0.00001f static private
Referenced by AForge.Math.Geometry.Tests.LineTest.DistanceToPointTest(), AForge.Math.Geometry.Tests.LineTest.GetAngleBetweenLinesTest(), and AForge.Math.Geometry.Tests.LineTest.RThetaTest().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Unit Tests/AForge.Math.Tests/Geometry/LineTest.cs