Doc: IGLib EXTENDED: alglib.testodesolverunit Class Reference
alglib.testodesolverunit Class Reference
Static Public Member Functions
static bool testodesolver (bool silent)
static bool testodesolver (bool silent)
static bool _pexec_testodesolver (bool silent)
Static Private Member Functions
static void unset2d (ref double[,] x)
static void unset1d (ref double[] x)
static void unsetrep (odesolver.odesolverreport rep)
static void unset2d (ref double[,] x)
static void unset1d (ref double[] x)
static void unsetrep (odesolver.odesolverreport rep)
Member Function Documentation
testodesolver() [1/2]
static bool alglib.testodesolverunit.testodesolver (bool silent) inline static
References alglib.ap.assert(), alglib.odesolver.odesolveriteration(), alglib.odesolver.odesolverresults(), alglib.odesolver.odesolverrkck(), alglib.math.randominteger(), alglib.math.randomreal(), and alglib.math.sqr().
Referenced by alglib.testodesolverunit._pexec_testodesolver(), and _Test.Main().
unset2d() [1/2]
static void alglib.testodesolverunit.unset2d (ref double x[,]) inline static private
References alglib.math.randomreal().
unset1d() [1/2]
static void alglib.testodesolverunit.unset1d (ref double[] x) inline static private
References alglib.math.randomreal().
unsetrep() [1/2]
static void alglib.testodesolverunit.unsetrep (odesolver.odesolverreport rep) inline static private
testodesolver() [2/2]
static bool alglib.testodesolverunit.testodesolver (bool silent) inline static
References alglib.ap.assert(), alglib.odesolver.odesolveriteration(), alglib.odesolver.odesolverresults(), alglib.odesolver.odesolverrkck(), alglib.math.randominteger(), alglib.math.randomreal(), and alglib.math.sqr().
_pexec_testodesolver()
static bool alglib.testodesolverunit._pexec_testodesolver (bool silent) inline static
References alglib.testodesolverunit.testodesolver().
Referenced by _Test.Main().
unset2d() [2/2]
static void alglib.testodesolverunit.unset2d (ref double x[,]) inline static private
References alglib.math.randomreal().
unset1d() [2/2]
static void alglib.testodesolverunit.unset1d (ref double[] x) inline static private
References alglib.math.randomreal().
unsetrep() [2/2]
static void alglib.testodesolverunit.unsetrep (odesolver.odesolverreport rep) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs