Doc: IGLib EXTENDED: NUnit.Framework.Constraints.ConstraintFactory Class Reference
NUnit.Framework.Constraints.ConstraintFactory Class Reference
Helper class with properties and methods that supply a number of constraints used in Asserts.
Public Member Functions
ResolvableConstraintExpression Property (string name)
Returns a new PropertyConstraintExpression, which will either test for the existence of the named property on the object being tested or apply any following constraint to that property.
ResolvableConstraintExpression Attribute (Type expectedType)
Returns a new AttributeConstraint checking for the presence of a particular attribute on an object.
ResolvableConstraintExpression Attribute< TExpected > ()
Returns a new AttributeConstraint checking for the presence of a particular attribute on an object.
EqualConstraint EqualTo (object expected)
Returns a constraint that tests two items for equality
SameAsConstraint SameAs (object expected)
Returns a constraint that tests that two references are the same object
GreaterThanConstraint GreaterThan (object expected)
Returns a constraint that tests whether the actual value is greater than the supplied argument
GreaterThanOrEqualConstraint GreaterThanOrEqualTo (object expected)
Returns a constraint that tests whether the actual value is greater than or equal to the supplied argument
GreaterThanOrEqualConstraint AtLeast (object expected)
Returns a constraint that tests whether the actual value is greater than or equal to the supplied argument
LessThanConstraint LessThan (object expected)
Returns a constraint that tests whether the actual value is less than the supplied argument
LessThanOrEqualConstraint LessThanOrEqualTo (object expected)
Returns a constraint that tests whether the actual value is less than or equal to the supplied argument
LessThanOrEqualConstraint AtMost (object expected)
Returns a constraint that tests whether the actual value is less than or equal to the supplied argument
ExactTypeConstraint TypeOf (Type expectedType)
Returns a constraint that tests whether the actual value is of the exact type supplied as an argument.
ExactTypeConstraint TypeOf< TExpected > ()
Returns a constraint that tests whether the actual value is of the exact type supplied as an argument.
InstanceOfTypeConstraint InstanceOf (Type expectedType)
Returns a constraint that tests whether the actual value is of the type supplied as an argument or a derived type.
InstanceOfTypeConstraint InstanceOf< TExpected > ()
Returns a constraint that tests whether the actual value is of the type supplied as an argument or a derived type.
AssignableFromConstraint AssignableFrom (Type expectedType)
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
AssignableFromConstraint AssignableFrom< TExpected > ()
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
AssignableToConstraint AssignableTo (Type expectedType)
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
AssignableToConstraint AssignableTo< TExpected > ()
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
CollectionEquivalentConstraint EquivalentTo (IEnumerable expected)
Returns a constraint that tests whether the actual value is a collection containing the same elements as the collection supplied as an argument.
CollectionSubsetConstraint SubsetOf (IEnumerable expected)
Returns a constraint that tests whether the actual value is a subset of the collection supplied as an argument.
CollectionSupersetConstraint SupersetOf (IEnumerable expected)
Returns a constraint that tests whether the actual value is a superset of the collection supplied as an argument.
CollectionContainsConstraint Member (object expected)
Returns a new CollectionContainsConstraint checking for the presence of a particular object in the collection.
CollectionContainsConstraint Contains (object expected)
Returns a new CollectionContainsConstraint checking for the presence of a particular object in the collection.
ContainsConstraint Contains (string expected)
Returns a new ContainsConstraint. This constraint will, in turn, make use of the appropriate second-level constraint, depending on the type of the actual argument. This overload is only used if the item sought is a string, since any other type implies that we are looking for a collection member.
SubstringConstraint StringContaining (string expected)
Returns a constraint that succeeds if the actual value contains the substring supplied as an argument.
SubstringConstraint ContainsSubstring (string expected)
Returns a constraint that succeeds if the actual value contains the substring supplied as an argument.
SubstringConstraint DoesNotContain (string expected)
Returns a constraint that fails if the actual value contains the substring supplied as an argument.
StartsWithConstraint StartWith (string expected)
Returns a constraint that succeeds if the actual value starts with the substring supplied as an argument.
StartsWithConstraint StartsWith (string expected)
Returns a constraint that succeeds if the actual value starts with the substring supplied as an argument.
StartsWithConstraint StringStarting (string expected)
Returns a constraint that succeeds if the actual value starts with the substring supplied as an argument.
StartsWithConstraint DoesNotStartWith (string expected)
Returns a constraint that fails if the actual value starts with the substring supplied as an argument.
EndsWithConstraint EndWith (string expected)
Returns a constraint that succeeds if the actual value ends with the substring supplied as an argument.
EndsWithConstraint EndsWith (string expected)
Returns a constraint that succeeds if the actual value ends with the substring supplied as an argument.
EndsWithConstraint StringEnding (string expected)
Returns a constraint that succeeds if the actual value ends with the substring supplied as an argument.
EndsWithConstraint DoesNotEndWith (string expected)
Returns a constraint that fails if the actual value ends with the substring supplied as an argument.
RegexConstraint Match (string pattern)
Returns a constraint that succeeds if the actual value matches the regular expression supplied as an argument.
RegexConstraint Matches (string pattern)
Returns a constraint that succeeds if the actual value matches the regular expression supplied as an argument.
RegexConstraint StringMatching (string pattern)
Returns a constraint that succeeds if the actual value matches the regular expression supplied as an argument.
RegexConstraint DoesNotMatch (string pattern)
Returns a constraint that fails if the actual value matches the pattern supplied as an argument.
SamePathConstraint SamePath (string expected)
Returns a constraint that tests whether the path provided is the same as an expected path after canonicalization.
SubPathConstraint SubPathOf (string expected)
Returns a constraint that tests whether the path provided is a subpath of the expected path after canonicalization.
SamePathOrUnderConstraint SamePathOrUnder (string expected)
Returns a constraint that tests whether the path provided is the same path or under an expected path after canonicalization.
RangeConstraint InRange (IComparable from, IComparable to)
Returns a constraint that tests whether the actual value falls within a specified range.
Static Public Member Functions
static ConstraintExpression Exactly (int expectedCount)
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding only if a specified number of them succeed.
Properties
ConstraintExpression Not [get]
Returns a ConstraintExpression that negates any following constraint.
ConstraintExpression No [get]
Returns a ConstraintExpression that negates any following constraint.
ConstraintExpression All [get]
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if all of them succeed.
ConstraintExpression Some [get]
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if at least one of them succeeds.
ConstraintExpression None [get]
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if all of them fail.
ResolvableConstraintExpression Length [get]
Returns a new ConstraintExpression, which will apply the following constraint to the Length property of the object being tested.
ResolvableConstraintExpression Count [get]
Returns a new ConstraintExpression, which will apply the following constraint to the Count property of the object being tested.
ResolvableConstraintExpression Message [get]
Returns a new ConstraintExpression, which will apply the following constraint to the Message property of the object being tested.
ResolvableConstraintExpression InnerException [get]
Returns a new ConstraintExpression, which will apply the following constraint to the InnerException property of the object being tested.
NullConstraint Null [get]
Returns a constraint that tests for null
TrueConstraint True [get]
Returns a constraint that tests for True
FalseConstraint False [get]
Returns a constraint that tests for False
GreaterThanConstraint Positive [get]
Returns a constraint that tests for a positive value
LessThanConstraint Negative [get]
Returns a constraint that tests for a negative value
NaNConstraint NaN [get]
Returns a constraint that tests for NaN
EmptyConstraint Empty [get]
Returns a constraint that tests for empty
UniqueItemsConstraint Unique [get]
Returns a constraint that tests whether a collection contains all unique items.
BinarySerializableConstraint BinarySerializable [get]
Returns a constraint that tests whether an object graph is serializable in binary format.
XmlSerializableConstraint XmlSerializable [get]
Returns a constraint that tests whether an object graph is serializable in xml format.
CollectionOrderedConstraint Ordered [get]
Returns a constraint that tests whether a collection is ordered
Detailed Description
Helper class with properties and methods that supply a number of constraints used in Asserts.
Member Function Documentation
Exactly()
static ConstraintExpression NUnit.Framework.Constraints.ConstraintFactory.Exactly (int expectedCount) inline static
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding only if a specified number of them succeed.
References NUnit.Framework.Has.Exactly().
Property()
ResolvableConstraintExpression NUnit.Framework.Constraints.ConstraintFactory.Property (string name) inline
Returns a new PropertyConstraintExpression, which will either test for the existence of the named property on the object being tested or apply any following constraint to that property.
References NUnit.Framework.Has.Property().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Syntax.PropertyExistsTest.SetUp(), NUnit.Framework.Syntax.PropertyExistsTest_AndFollows.SetUp(), NUnit.Framework.Syntax.AfterTest_PropertyTest.SetUp(), NUnit.Framework.Syntax.PropertyTest_ConstraintFollows.SetUp(), and NUnit.Framework.Syntax.PropertyTest_NotFollows.SetUp().
Attribute()
ResolvableConstraintExpression NUnit.Framework.Constraints.ConstraintFactory.Attribute (Type expectedType) inline
Returns a new AttributeConstraint checking for the presence of a particular attribute on an object.
References NUnit.Framework.Has.Attribute().
Referenced by NUnit.Framework.Constraints.ConstraintFactory.Attribute< TExpected >(), NUnit.Framework.Syntax.AttributeTest.SetUp(), NUnit.Framework.Syntax.AttributeTestWithFollowingConstraint.SetUp(), and NUnit.Framework.Syntax.AttributeTest_Generic.SetUp().
Attribute< TExpected >()
ResolvableConstraintExpression NUnit.Framework.Constraints.ConstraintFactory.Attribute< TExpected > () inline
Returns a new AttributeConstraint checking for the presence of a particular attribute on an object.
References NUnit.Framework.Constraints.ConstraintFactory.Attribute().
EqualTo()
EqualConstraint NUnit.Framework.Constraints.ConstraintFactory.EqualTo (object expected) inline
Returns a constraint that tests two items for equality
Referenced by NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayAndCollection(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayIsEqualToItself(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayOfIntAndArrayOfDouble(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysDeclaredAsDifferentTypes(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfArrays(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfDecimal(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfDouble(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfInt(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfMixedTypes(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfString(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysPassedAsObjects(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysWithDifferentDimensionsMatchedAsCollection(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysWithDifferentRanksComparedAsCollection(), NUnit.Framework.Internal.TextMessageWriterTests.DisplayStringDifferences(), NUnit.Framework.Internal.TextMessageWriterTests.DisplayStringDifferences_NoClipping(), NUnit.Framework.Assertions.ArrayEqualsFixture.DoubleDimensionedArrays(), NUnit.Framework.Tests.AssertSyntaxTests.EqualIgnoringCaseTests(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTests(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTestsWithTolerance(), NUnit.Framework.Assertions.ArrayEqualsFixture.FiveDimensionedArrays(), NUnit.Framework.Assertions.ArrayEqualsFixture.JaggedArrays(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Syntax.EqualToTest.SetUp(), NUnit.Framework.Syntax.AfterTest_SimpleConstraint.SetUp(), NUnit.Framework.Syntax.EqualToTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.EqualToTest_WithinTolerance.SetUp(), NUnit.Framework.Syntax.AndIsEvaluatedBeforePrecedingOr.SetUp(), NUnit.Framework.Assertions.ArrayEqualsFixture.TripleDimensionedArrays(), NUnit.Framework.Internal.TextMessageWriterTests.WriteMessageLine_EmbeddedZeroes(), and NUnit.Framework.Internal.TextMessageWriterTests.WriteMessageLine_EmbeddedZeroesAsArgs().
SameAs()
SameAsConstraint NUnit.Framework.Constraints.ConstraintFactory.SameAs (object expected) inline
Returns a constraint that tests that two references are the same object
GreaterThan()
GreaterThanConstraint NUnit.Framework.Constraints.ConstraintFactory.GreaterThan (object expected) inline
Returns a constraint that tests whether the actual value is greater than the supplied argument
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AndOperator(), NUnit.Framework.Tests.AssertSyntaxTests.ComparisonTests(), NUnit.Framework.Tests.AssertSyntaxTests.ComplexTests(), NUnit.Framework.Tests.AssertSyntaxTests.OrOperator(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Syntax.GreaterThanTest.SetUp(), NUnit.Framework.Syntax.AndOperatorOverride.SetUp(), NUnit.Framework.Syntax.AfterTest_AndOperator.SetUp(), and NUnit.Framework.Syntax.AndTest.SetUp().
GreaterThanOrEqualTo()
GreaterThanOrEqualConstraint NUnit.Framework.Constraints.ConstraintFactory.GreaterThanOrEqualTo (object expected) inline
Returns a constraint that tests whether the actual value is greater than or equal to the supplied argument
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.ComparisonTests(), and NUnit.Framework.Syntax.GreaterThanOrEqualTest.SetUp().
AtLeast()
GreaterThanOrEqualConstraint NUnit.Framework.Constraints.ConstraintFactory.AtLeast (object expected) inline
Returns a constraint that tests whether the actual value is greater than or equal to the supplied argument
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.ComparisonTests(), and NUnit.Framework.Syntax.AtLeastTest.SetUp().
LessThan()
LessThanConstraint NUnit.Framework.Constraints.ConstraintFactory.LessThan (object expected) inline
Returns a constraint that tests whether the actual value is less than the supplied argument
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AndOperator(), NUnit.Framework.Tests.AssertSyntaxTests.ComparisonTests(), NUnit.Framework.Tests.AssertSyntaxTests.ComplexTests(), NUnit.Framework.Tests.AssertSyntaxTests.OrOperator(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Syntax.OrOperatorOverride.SetUp(), NUnit.Framework.Syntax.LessThanTest.SetUp(), NUnit.Framework.Syntax.OrTest.SetUp(), NUnit.Framework.Syntax.OrTest_ThreeOrs.SetUp(), and NUnit.Framework.Syntax.AndIsEvaluatedBeforeFollowingOr.SetUp().
LessThanOrEqualTo()
LessThanOrEqualConstraint NUnit.Framework.Constraints.ConstraintFactory.LessThanOrEqualTo (object expected) inline
Returns a constraint that tests whether the actual value is less than or equal to the supplied argument
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.ComparisonTests(), and NUnit.Framework.Syntax.LessThanOrEqualTest.SetUp().
AtMost()
LessThanOrEqualConstraint NUnit.Framework.Constraints.ConstraintFactory.AtMost (object expected) inline
Returns a constraint that tests whether the actual value is less than or equal to the supplied argument
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.ComparisonTests(), and NUnit.Framework.Syntax.AtMostTest.SetUp().
TypeOf()
ExactTypeConstraint NUnit.Framework.Constraints.ConstraintFactory.TypeOf (Type expectedType) inline
Returns a constraint that tests whether the actual value is of the exact type supplied as an argument.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.ExactTypeTests(), NUnit.Framework.Syntax.ExactTypeTest.SetUp(), and NUnit.Framework.Syntax.ExactTypeTest_Generic.SetUp().
TypeOf< TExpected >()
ExactTypeConstraint NUnit.Framework.Constraints.ConstraintFactory.TypeOf< TExpected > () inline
Returns a constraint that tests whether the actual value is of the exact type supplied as an argument.
InstanceOf()
InstanceOfTypeConstraint NUnit.Framework.Constraints.ConstraintFactory.InstanceOf (Type expectedType) inline
Returns a constraint that tests whether the actual value is of the type supplied as an argument or a derived type.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.InstanceOfTests(), NUnit.Framework.Syntax.InstanceOfTest.SetUp(), and NUnit.Framework.Syntax.InstanceOfTest_Generic.SetUp().
InstanceOf< TExpected >()
InstanceOfTypeConstraint NUnit.Framework.Constraints.ConstraintFactory.InstanceOf< TExpected > () inline
Returns a constraint that tests whether the actual value is of the type supplied as an argument or a derived type.
AssignableFrom()
AssignableFromConstraint NUnit.Framework.Constraints.ConstraintFactory.AssignableFrom (Type expectedType) inline
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AssignableFromTypeTests(), NUnit.Framework.Syntax.AssignableFromTest.SetUp(), and NUnit.Framework.Syntax.AssignableFromTest_Generic.SetUp().
AssignableFrom< TExpected >()
AssignableFromConstraint NUnit.Framework.Constraints.ConstraintFactory.AssignableFrom< TExpected > () inline
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
AssignableTo()
AssignableToConstraint NUnit.Framework.Constraints.ConstraintFactory.AssignableTo (Type expectedType) inline
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
Referenced by NUnit.Framework.Syntax.AssignableToTest.SetUp(), and NUnit.Framework.Syntax.AssignableToTest_Generic.SetUp().
AssignableTo< TExpected >()
AssignableToConstraint NUnit.Framework.Constraints.ConstraintFactory.AssignableTo< TExpected > () inline
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
EquivalentTo()
CollectionEquivalentConstraint NUnit.Framework.Constraints.ConstraintFactory.EquivalentTo (IEnumerable expected) inline
Returns a constraint that tests whether the actual value is a collection containing the same elements as the collection supplied as an argument.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.CollectionEquivalenceTests(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), and NUnit.Framework.Syntax.CollectionEquivalentTest.SetUp().
SubsetOf()
CollectionSubsetConstraint NUnit.Framework.Constraints.ConstraintFactory.SubsetOf (IEnumerable expected) inline
Returns a constraint that tests whether the actual value is a subset of the collection supplied as an argument.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Syntax.CollectionSubsetTest.SetUp(), and NUnit.Framework.Tests.AssertSyntaxTests.SubsetTests().
SupersetOf()
CollectionSupersetConstraint NUnit.Framework.Constraints.ConstraintFactory.SupersetOf (IEnumerable expected) inline
Returns a constraint that tests whether the actual value is a superset of the collection supplied as an argument.
Member()
CollectionContainsConstraint NUnit.Framework.Constraints.ConstraintFactory.Member (object expected) inline
Returns a new CollectionContainsConstraint checking for the presence of a particular object in the collection.
Contains() [1/2]
CollectionContainsConstraint NUnit.Framework.Constraints.ConstraintFactory.Contains (object expected) inline
Returns a new CollectionContainsConstraint checking for the presence of a particular object in the collection.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests(), NUnit.Framework.Syntax.ContainsTest.SetUp(), NUnit.Framework.Syntax.ContainsTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.CollectionContainsTest.SetUp(), and NUnit.Framework.Tests.AssertSyntaxTests.SubstringTests().
Contains() [2/2]
ContainsConstraint NUnit.Framework.Constraints.ConstraintFactory.Contains (string expected) inline
Returns a new ContainsConstraint. This constraint will, in turn, make use of the appropriate second-level constraint, depending on the type of the actual argument. This overload is only used if the item sought is a string, since any other type implies that we are looking for a collection member.
StringContaining()
SubstringConstraint NUnit.Framework.Constraints.ConstraintFactory.StringContaining (string expected) inline
Returns a constraint that succeeds if the actual value contains the substring supplied as an argument.
ContainsSubstring()
SubstringConstraint NUnit.Framework.Constraints.ConstraintFactory.ContainsSubstring (string expected) inline
Returns a constraint that succeeds if the actual value contains the substring supplied as an argument.
DoesNotContain()
SubstringConstraint NUnit.Framework.Constraints.ConstraintFactory.DoesNotContain (string expected) inline
Returns a constraint that fails if the actual value contains the substring supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.ContainsSubstring(), and NUnit.Framework.Constraints.ConstraintExpression.Not.
StartWith()
StartsWithConstraint NUnit.Framework.Constraints.ConstraintFactory.StartWith (string expected) inline
Returns a constraint that succeeds if the actual value starts with the substring supplied as an argument.
StartsWith()
StartsWithConstraint NUnit.Framework.Constraints.ConstraintFactory.StartsWith (string expected) inline
Returns a constraint that succeeds if the actual value starts with the substring supplied as an argument.
Referenced by NUnit.Framework.Syntax.StartsWithTest.SetUp(), NUnit.Framework.Syntax.TextStartsWithTest.SetUp(), NUnit.Framework.Syntax.StartsWithTest_IgnoreCase.SetUp(), and NUnit.Framework.Tests.AssertSyntaxTests.StartsWithTests().
StringStarting()
StartsWithConstraint NUnit.Framework.Constraints.ConstraintFactory.StringStarting (string expected) inline
Returns a constraint that succeeds if the actual value starts with the substring supplied as an argument.
DoesNotStartWith()
StartsWithConstraint NUnit.Framework.Constraints.ConstraintFactory.DoesNotStartWith (string expected) inline
Returns a constraint that fails if the actual value starts with the substring supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Not, and NUnit.Framework.Constraints.ConstraintExpression.StartsWith().
EndWith()
EndsWithConstraint NUnit.Framework.Constraints.ConstraintFactory.EndWith (string expected) inline
Returns a constraint that succeeds if the actual value ends with the substring supplied as an argument.
EndsWith()
EndsWithConstraint NUnit.Framework.Constraints.ConstraintFactory.EndsWith (string expected) inline
Returns a constraint that succeeds if the actual value ends with the substring supplied as an argument.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.EndsWithTests(), NUnit.Framework.Syntax.EndsWithTest.SetUp(), and NUnit.Framework.Syntax.EndsWithTest_IgnoreCase.SetUp().
StringEnding()
EndsWithConstraint NUnit.Framework.Constraints.ConstraintFactory.StringEnding (string expected) inline
Returns a constraint that succeeds if the actual value ends with the substring supplied as an argument.
DoesNotEndWith()
EndsWithConstraint NUnit.Framework.Constraints.ConstraintFactory.DoesNotEndWith (string expected) inline
Returns a constraint that fails if the actual value ends with the substring supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.EndsWith(), and NUnit.Framework.Constraints.ConstraintExpression.Not.
Match()
RegexConstraint NUnit.Framework.Constraints.ConstraintFactory.Match (string pattern) inline
Returns a constraint that succeeds if the actual value matches the regular expression supplied as an argument.
Matches()
RegexConstraint NUnit.Framework.Constraints.ConstraintFactory.Matches (string pattern) inline
Returns a constraint that succeeds if the actual value matches the regular expression supplied as an argument.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.RegularExpressionTests(), NUnit.Framework.Syntax.RegexTest.SetUp(), and NUnit.Framework.Syntax.RegexTest_IgnoreCase.SetUp().
StringMatching()
RegexConstraint NUnit.Framework.Constraints.ConstraintFactory.StringMatching (string pattern) inline
Returns a constraint that succeeds if the actual value matches the regular expression supplied as an argument.
DoesNotMatch()
RegexConstraint NUnit.Framework.Constraints.ConstraintFactory.DoesNotMatch (string pattern) inline
Returns a constraint that fails if the actual value matches the pattern supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Matches(), and NUnit.Framework.Constraints.ConstraintExpression.Not.
SamePath()
SamePathConstraint NUnit.Framework.Constraints.ConstraintFactory.SamePath (string expected) inline
Returns a constraint that tests whether the path provided is the same as an expected path after canonicalization.
Referenced by NUnit.Framework.Syntax.SamePathTest.SetUp(), NUnit.Framework.Syntax.SamePathTest_IgnoreCase.SetUp(), and NUnit.Framework.Syntax.SamePathTest_RespectCase.SetUp().
SubPathOf()
SubPathConstraint NUnit.Framework.Constraints.ConstraintFactory.SubPathOf (string expected) inline
Returns a constraint that tests whether the path provided is a subpath of the expected path after canonicalization.
SamePathOrUnder()
SamePathOrUnderConstraint NUnit.Framework.Constraints.ConstraintFactory.SamePathOrUnder (string expected) inline
Returns a constraint that tests whether the path provided is the same path or under an expected path after canonicalization.
Referenced by NUnit.Framework.Syntax.SamePathOrUnderTest.SetUp(), NUnit.Framework.Syntax.SamePathOrUnderTest_IgnoreCase.SetUp(), and NUnit.Framework.Syntax.SamePathOrUnderTest_RespectCase.SetUp().
InRange()
RangeConstraint NUnit.Framework.Constraints.ConstraintFactory.InRange (IComparable from, IComparable to) inline
Returns a constraint that tests whether the actual value falls within a specified range.
Property Documentation
Not
ConstraintExpression NUnit.Framework.Constraints.ConstraintFactory.Not get
Returns a ConstraintExpression that negates any following constraint.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Assertions.ArrayNotEqualFixture.ArraysDeclaredAsDifferentTypes(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysWithDifferentDimensionsMatchedAsCollection(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysWithDifferentRanksComparedAsCollection(), NUnit.Framework.Tests.AssertSyntaxTests.AssignableFromTypeTests(), NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests(), NUnit.Framework.Tests.AssertSyntaxTests.CollectionEquivalenceTests(), NUnit.Framework.Tests.AssertSyntaxTests.ComplexTests(), NUnit.Framework.Assertions.ArrayNotEqualFixture.DifferentLengthArrays(), NUnit.Framework.Tests.AssertSyntaxTests.EmptyCollectionTests(), NUnit.Framework.Tests.AssertSyntaxTests.EmptyStringTests(), NUnit.Framework.Tests.AssertSyntaxTests.EndsWithTests(), NUnit.Framework.Tests.AssertSyntaxTests.EqualIgnoringCaseTests(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTests(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTestsWithTolerance(), NUnit.Framework.Tests.AssertSyntaxTests.ExactTypeTests(), NUnit.Framework.Tests.AssertSyntaxTests.InstanceOfTests(), NUnit.Framework.Tests.AssertSyntaxTests.IsNotNull(), NUnit.Framework.Tests.AssertSyntaxTests.NotTests(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Tests.AssertSyntaxTests.RegularExpressionTests(), NUnit.Framework.Assertions.ArrayNotEqualFixture.SameLengthDifferentContent(), NUnit.Framework.Syntax.NotTest.SetUp(), NUnit.Framework.Syntax.NotTest_Cascaded.SetUp(), NUnit.Framework.Syntax.NotSamePathTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.NotSamePathTest_RespectCase.SetUp(), NUnit.Framework.Syntax.NotSamePathOrUnderTest_IgnoreCase.SetUp(), NUnit.Framework.Syntax.AndTest_ThreeAndsWithNot.SetUp(), NUnit.Framework.Syntax.NotSamePathOrUnderTest_RespectCase.SetUp(), NUnit.Framework.Tests.AssertSyntaxTests.StartsWithTests(), NUnit.Framework.Tests.AssertSyntaxTests.SubsetTests(), and NUnit.Framework.Tests.AssertSyntaxTests.SubstringTests().
No
ConstraintExpression NUnit.Framework.Constraints.ConstraintFactory.No get
Returns a ConstraintExpression that negates any following constraint.
All
ConstraintExpression NUnit.Framework.Constraints.ConstraintFactory.All get
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if all of them succeed.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests(), NUnit.Framework.Tests.AssertSyntaxTests.EndsWithTests(), NUnit.Framework.Tests.AssertSyntaxTests.EqualIgnoringCaseTests(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Tests.AssertSyntaxTests.RegularExpressionTests(), NUnit.Framework.Syntax.AllTest.SetUp(), NUnit.Framework.Tests.AssertSyntaxTests.StartsWithTests(), and NUnit.Framework.Tests.AssertSyntaxTests.SubstringTests().
Some
ConstraintExpression NUnit.Framework.Constraints.ConstraintFactory.Some get
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if at least one of them succeeds.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Syntax.SomeTest.SetUp(), NUnit.Framework.Syntax.SomeTest_BeforeBinaryOperators.SetUp(), NUnit.Framework.Syntax.SomeTest_NestedSome.SetUp(), NUnit.Framework.Syntax.SomeTest_UseOfAndSome.SetUp(), and NUnit.Framework.Tests.AssertSyntaxTests.SomeItemTests().
None
ConstraintExpression NUnit.Framework.Constraints.ConstraintFactory.None get
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if all of them fail.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests(), NUnit.Framework.Tests.AssertSyntaxTests.NoItemTests(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), and NUnit.Framework.Syntax.NoneTest.SetUp().
Length
ResolvableConstraintExpression NUnit.Framework.Constraints.ConstraintFactory.Length get
Returns a new ConstraintExpression, which will apply the following constraint to the Length property of the object being tested.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), and NUnit.Framework.Syntax.LengthTest.SetUp().
Count
ResolvableConstraintExpression NUnit.Framework.Constraints.ConstraintFactory.Count get
Returns a new ConstraintExpression, which will apply the following constraint to the Count property of the object being tested.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), and NUnit.Framework.Syntax.CountTest.SetUp().
Message
ResolvableConstraintExpression NUnit.Framework.Constraints.ConstraintFactory.Message get
Returns a new ConstraintExpression, which will apply the following constraint to the Message property of the object being tested.
Referenced by NUnit.Framework.Syntax.MessageTest.SetUp().
InnerException
ResolvableConstraintExpression NUnit.Framework.Constraints.ConstraintFactory.InnerException get
Returns a new ConstraintExpression, which will apply the following constraint to the InnerException property of the object being tested.
Null
NullConstraint NUnit.Framework.Constraints.ConstraintFactory.Null get
Returns a constraint that tests for null
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.ComplexTests(), NUnit.Framework.Tests.AssertSyntaxTests.IsNull(), NUnit.Framework.Tests.AssertSyntaxTests.NotOperator(), NUnit.Framework.Syntax.NullTest.SetUp(), and NUnit.Framework.Syntax.NotOperatorOverride.SetUp().
True
TrueConstraint NUnit.Framework.Constraints.ConstraintFactory.True get
Returns a constraint that tests for True
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.IsTrue(), and NUnit.Framework.Syntax.TrueTest.SetUp().
False
FalseConstraint NUnit.Framework.Constraints.ConstraintFactory.False get
Returns a constraint that tests for False
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.IsFalse(), and NUnit.Framework.Syntax.FalseTest.SetUp().
Positive
GreaterThanConstraint NUnit.Framework.Constraints.ConstraintFactory.Positive get
Returns a constraint that tests for a positive value
Referenced by NUnit.Framework.Syntax.PositiveTest.SetUp().
Negative
LessThanConstraint NUnit.Framework.Constraints.ConstraintFactory.Negative get
Returns a constraint that tests for a negative value
Referenced by NUnit.Framework.Syntax.NegativeTest.SetUp().
NaN
NaNConstraint NUnit.Framework.Constraints.ConstraintFactory.NaN get
Returns a constraint that tests for NaN
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.IsNaN(), and NUnit.Framework.Syntax.NaNTest.SetUp().
Empty
EmptyConstraint NUnit.Framework.Constraints.ConstraintFactory.Empty get
Returns a constraint that tests for empty
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.EmptyCollectionTests(), and NUnit.Framework.Tests.AssertSyntaxTests.EmptyStringTests().
Unique
UniqueItemsConstraint NUnit.Framework.Constraints.ConstraintFactory.Unique get
Returns a constraint that tests whether a collection contains all unique items.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), and NUnit.Framework.Syntax.UniqueTest.SetUp().
BinarySerializable
BinarySerializableConstraint NUnit.Framework.Constraints.ConstraintFactory.BinarySerializable get
Returns a constraint that tests whether an object graph is serializable in binary format.
Referenced by NUnit.Framework.Syntax.BinarySerializableTest.SetUp().
XmlSerializable
XmlSerializableConstraint NUnit.Framework.Constraints.ConstraintFactory.XmlSerializable get
Returns a constraint that tests whether an object graph is serializable in xml format.
Referenced by NUnit.Framework.Syntax.XmlSerializableTest.SetUp().
Ordered
CollectionOrderedConstraint NUnit.Framework.Constraints.ConstraintFactory.Ordered get
Returns a constraint that tests whether a collection is ordered
Referenced by NUnit.Framework.Syntax.CollectionOrderedTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Descending.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer_Descending.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Descending.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer.SetUp(), and NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer_Descending.SetUp().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Constraints/ConstraintFactory.cs