Doc: IGLib EXTENDED: FiltersDemo.MainForm Class Reference
FiltersDemo.MainForm Class Reference
Summary description for MainForm.
Public Member Functions
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void exitFilrItem_Click (object sender, System.EventArgs e)
void openFileItem_Click (object sender, System.EventArgs e)
void normalSizeItem_Click (object sender, System.EventArgs e)
void stretchedSizeItem_Click (object sender, System.EventArgs e)
void centeredSizeItem_Click (object sender, System.EventArgs e)
void sizeItem_Popup (object sender, System.EventArgs e)
void ClearCurrentImage ()
void ApplyFilter (IFilter filter)
void noneFiltersItem_Click (object sender, System.EventArgs e)
void grayscaleFiltersItem_Click (object sender, System.EventArgs e)
void sepiaFiltersItem_Click (object sender, System.EventArgs e)
void invertFiltersItem_Click (object sender, System.EventArgs e)
void rotateChannelFiltersItem_Click (object sender, System.EventArgs e)
void colorFiltersItem_Click (object sender, System.EventArgs e)
void hueModifierFiltersItem_Click (object sender, System.EventArgs e)
void saturationAdjustingFiltersItem_Click (object sender, System.EventArgs e)
void brightnessAdjustingFiltersItem_Click (object sender, System.EventArgs e)
void contrastAdjustingFiltersItem_Click (object sender, System.EventArgs e)
void hslFiltersItem_Click (object sender, System.EventArgs e)
void yCbCrLinearFiltersItem_Click (object sender, System.EventArgs e)
void yCbCrFiltersItem_Click (object sender, System.EventArgs e)
void thresholdFiltersItem_Click (object sender, System.EventArgs e)
void floydFiltersItem_Click (object sender, System.EventArgs e)
void orderedDitheringFiltersItem_Click (object sender, System.EventArgs e)
void convolutionFiltersItem_Click (object sender, System.EventArgs e)
void sharpenFiltersItem_Click (object sender, System.EventArgs e)
void differenceEdgesFiltersItem_Click (object sender, System.EventArgs e)
void homogenityEdgesFiltersItem_Click (object sender, System.EventArgs e)
void sobelEdgesFiltersItem_Click (object sender, System.EventArgs e)
void rgbLinearFiltersItem_Click (object sender, System.EventArgs e)
void jitterFiltersItem_Click (object sender, System.EventArgs e)
void oilFiltersItem_Click (object sender, System.EventArgs e)
void gaussianFiltersItem_Click (object sender, EventArgs e)
void textureFiltersItem_Click (object sender, EventArgs e)
Static Private Member Functions
static void Main ()
The main entry point for the application.
Private Attributes
System.Windows.Forms.MenuItem fileItem
System.Windows.Forms.MenuItem openFileItem
System.Windows.Forms.MenuItem menuItem3
System.Windows.Forms.MenuItem exitFilrItem
System.Windows.Forms.OpenFileDialog openFileDialog
System.Windows.Forms.PictureBox pictureBox
System.Windows.Forms.MainMenu mainMenu
System.Windows.Forms.MenuItem sizeItem
System.Windows.Forms.MenuItem normalSizeItem
System.Windows.Forms.MenuItem stretchedSizeItem
System.Windows.Forms.MenuItem centeredSizeItem
System.Windows.Forms.MenuItem filtersItem
System.Windows.Forms.MenuItem noneFiltersItem
System.Windows.Forms.MenuItem menuItem1
System.Windows.Forms.MenuItem sepiaFiltersItem
System.Windows.Forms.MenuItem invertFiltersItem
System.Windows.Forms.MenuItem rotateChannelFiltersItem
System.Windows.Forms.MenuItem grayscaleFiltersItem
System.Windows.Forms.MenuItem colorFiltersItem
System.Windows.Forms.MenuItem menuItem2
System.Windows.Forms.MenuItem hueModifierFiltersItem
System.Windows.Forms.MenuItem saturationAdjustingFiltersItem
System.Windows.Forms.MenuItem brightnessAdjustingFiltersItem
System.Windows.Forms.MenuItem contrastAdjustingFiltersItem
System.Windows.Forms.MenuItem hslFiltersItem
System.Windows.Forms.MenuItem menuItem4
System.Windows.Forms.MenuItem yCbCrLinearFiltersItem
System.Windows.Forms.MenuItem yCbCrFiltersItem
System.Windows.Forms.MenuItem menuItem5
System.Windows.Forms.MenuItem thresholdFiltersItem
System.Windows.Forms.MenuItem floydFiltersItem
System.Windows.Forms.MenuItem orderedDitheringFiltersItem
System.Windows.Forms.MenuItem menuItem6
System.Windows.Forms.MenuItem convolutionFiltersItem
System.Windows.Forms.MenuItem sharpenFiltersItem
System.Windows.Forms.MenuItem menuItem7
System.Windows.Forms.MenuItem differenceEdgesFiltersItem
System.Windows.Forms.MenuItem homogenityEdgesFiltersItem
System.Windows.Forms.MenuItem sobelEdgesFiltersItem
System.Windows.Forms.MenuItem rgbLinearFiltersItem
System.Windows.Forms.MenuItem menuItem8
System.Windows.Forms.MenuItem jitterFiltersItem
System.Windows.Forms.MenuItem oilFiltersItem
MenuItem gaussianFiltersItem
MenuItem textureFiltersItem
IContainer components
System.Drawing.Bitmap sourceImage
System.Drawing.Bitmap filteredImage
Detailed Description
Summary description for MainForm.
Constructor & Destructor Documentation
MainForm()
FiltersDemo.MainForm.MainForm () inline
References FiltersDemo.MainForm.InitializeComponent(), and FiltersDemo.MainForm.pictureBox.
Referenced by FiltersDemo.MainForm.Main().
Member Function Documentation
Dispose()
override void FiltersDemo.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References FiltersDemo.MainForm.components.
InitializeComponent()
void FiltersDemo.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by FiltersDemo.MainForm.MainForm().
Main()
static void FiltersDemo.MainForm.Main () inline static private
The main entry point for the application.
References FiltersDemo.MainForm.MainForm().
exitFilrItem_Click()
void FiltersDemo.MainForm.exitFilrItem_Click (object sender, System.EventArgs e) inline private
openFileItem_Click()
void FiltersDemo.MainForm.openFileItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.ClearCurrentImage(), AForge.Imaging.Image.Clone(), FiltersDemo.MainForm.filtersItem, FiltersDemo.MainForm.noneFiltersItem, FiltersDemo.MainForm.openFileDialog, FiltersDemo.MainForm.pictureBox, and FiltersDemo.MainForm.sourceImage.
normalSizeItem_Click()
void FiltersDemo.MainForm.normalSizeItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.pictureBox.
stretchedSizeItem_Click()
void FiltersDemo.MainForm.stretchedSizeItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.pictureBox.
centeredSizeItem_Click()
void FiltersDemo.MainForm.centeredSizeItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.pictureBox.
sizeItem_Popup()
void FiltersDemo.MainForm.sizeItem_Popup (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.centeredSizeItem, FiltersDemo.MainForm.normalSizeItem, FiltersDemo.MainForm.pictureBox, and FiltersDemo.MainForm.stretchedSizeItem.
ClearCurrentImage()
void FiltersDemo.MainForm.ClearCurrentImage () inline private
References FiltersDemo.MainForm.filteredImage, FiltersDemo.MainForm.filtersItem, FiltersDemo.MainForm.noneFiltersItem, and FiltersDemo.MainForm.pictureBox.
Referenced by FiltersDemo.MainForm.ApplyFilter(), FiltersDemo.MainForm.noneFiltersItem_Click(), and FiltersDemo.MainForm.openFileItem_Click().
ApplyFilter()
void FiltersDemo.MainForm.ApplyFilter (IFilter filter) inline private
References AForge.Imaging.Filters.IFilter.Apply(), FiltersDemo.MainForm.ClearCurrentImage(), FiltersDemo.MainForm.filteredImage, FiltersDemo.MainForm.pictureBox, and FiltersDemo.MainForm.sourceImage.
Referenced by FiltersDemo.MainForm.brightnessAdjustingFiltersItem_Click(), FiltersDemo.MainForm.colorFiltersItem_Click(), FiltersDemo.MainForm.contrastAdjustingFiltersItem_Click(), FiltersDemo.MainForm.convolutionFiltersItem_Click(), FiltersDemo.MainForm.differenceEdgesFiltersItem_Click(), FiltersDemo.MainForm.floydFiltersItem_Click(), FiltersDemo.MainForm.gaussianFiltersItem_Click(), FiltersDemo.MainForm.grayscaleFiltersItem_Click(), FiltersDemo.MainForm.homogenityEdgesFiltersItem_Click(), FiltersDemo.MainForm.hslFiltersItem_Click(), FiltersDemo.MainForm.hueModifierFiltersItem_Click(), FiltersDemo.MainForm.invertFiltersItem_Click(), FiltersDemo.MainForm.jitterFiltersItem_Click(), FiltersDemo.MainForm.oilFiltersItem_Click(), FiltersDemo.MainForm.orderedDitheringFiltersItem_Click(), FiltersDemo.MainForm.rgbLinearFiltersItem_Click(), FiltersDemo.MainForm.rotateChannelFiltersItem_Click(), FiltersDemo.MainForm.saturationAdjustingFiltersItem_Click(), FiltersDemo.MainForm.sepiaFiltersItem_Click(), FiltersDemo.MainForm.sharpenFiltersItem_Click(), FiltersDemo.MainForm.sobelEdgesFiltersItem_Click(), FiltersDemo.MainForm.textureFiltersItem_Click(), FiltersDemo.MainForm.thresholdFiltersItem_Click(), FiltersDemo.MainForm.yCbCrFiltersItem_Click(), and FiltersDemo.MainForm.yCbCrLinearFiltersItem_Click().
noneFiltersItem_Click()
void FiltersDemo.MainForm.noneFiltersItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.ClearCurrentImage(), FiltersDemo.MainForm.noneFiltersItem, FiltersDemo.MainForm.pictureBox, and FiltersDemo.MainForm.sourceImage.
grayscaleFiltersItem_Click()
void FiltersDemo.MainForm.grayscaleFiltersItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.ApplyFilter(), AForge.Imaging.Filters.Grayscale.CommonAlgorithms.BT709, and FiltersDemo.MainForm.grayscaleFiltersItem.
sepiaFiltersItem_Click()
void FiltersDemo.MainForm.sepiaFiltersItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.ApplyFilter(), and FiltersDemo.MainForm.sepiaFiltersItem.
invertFiltersItem_Click()
void FiltersDemo.MainForm.invertFiltersItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.ApplyFilter(), and FiltersDemo.MainForm.invertFiltersItem.
rotateChannelFiltersItem_Click()
void FiltersDemo.MainForm.rotateChannelFiltersItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.ApplyFilter(), and FiltersDemo.MainForm.rotateChannelFiltersItem.
colorFiltersItem_Click()
void FiltersDemo.MainForm.colorFiltersItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.ApplyFilter(), and FiltersDemo.MainForm.colorFiltersItem.
hueModifierFiltersItem_Click()
void FiltersDemo.MainForm.hueModifierFiltersItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.ApplyFilter(), and FiltersDemo.MainForm.hueModifierFiltersItem.
saturationAdjustingFiltersItem_Click()
void FiltersDemo.MainForm.saturationAdjustingFiltersItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.ApplyFilter(), and FiltersDemo.MainForm.saturationAdjustingFiltersItem.
brightnessAdjustingFiltersItem_Click()
void FiltersDemo.MainForm.brightnessAdjustingFiltersItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.ApplyFilter(), and FiltersDemo.MainForm.brightnessAdjustingFiltersItem.
contrastAdjustingFiltersItem_Click()
void FiltersDemo.MainForm.contrastAdjustingFiltersItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.ApplyFilter(), and FiltersDemo.MainForm.contrastAdjustingFiltersItem.
hslFiltersItem_Click()
void FiltersDemo.MainForm.hslFiltersItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.ApplyFilter(), and FiltersDemo.MainForm.hslFiltersItem.
yCbCrLinearFiltersItem_Click()
void FiltersDemo.MainForm.yCbCrLinearFiltersItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.ApplyFilter(), AForge.Imaging.Filters.YCbCrLinear.InCb, and FiltersDemo.MainForm.yCbCrLinearFiltersItem.
yCbCrFiltersItem_Click()
void FiltersDemo.MainForm.yCbCrFiltersItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.ApplyFilter(), and FiltersDemo.MainForm.yCbCrFiltersItem.
thresholdFiltersItem_Click()
void FiltersDemo.MainForm.thresholdFiltersItem_Click (object sender, System.EventArgs e) inline private
References AForge.Imaging.Filters.BaseFilter.Apply(), FiltersDemo.MainForm.ApplyFilter(), AForge.Imaging.Filters.Grayscale.CommonAlgorithms.RMY, FiltersDemo.MainForm.sourceImage, and FiltersDemo.MainForm.thresholdFiltersItem.
floydFiltersItem_Click()
void FiltersDemo.MainForm.floydFiltersItem_Click (object sender, System.EventArgs e) inline private
References AForge.Imaging.Filters.BaseFilter.Apply(), FiltersDemo.MainForm.ApplyFilter(), FiltersDemo.MainForm.floydFiltersItem, AForge.Imaging.Filters.Grayscale.CommonAlgorithms.RMY, and FiltersDemo.MainForm.sourceImage.
orderedDitheringFiltersItem_Click()
void FiltersDemo.MainForm.orderedDitheringFiltersItem_Click (object sender, System.EventArgs e) inline private
References AForge.Imaging.Filters.BaseFilter.Apply(), FiltersDemo.MainForm.ApplyFilter(), FiltersDemo.MainForm.orderedDitheringFiltersItem, AForge.Imaging.Filters.Grayscale.CommonAlgorithms.RMY, and FiltersDemo.MainForm.sourceImage.
convolutionFiltersItem_Click()
void FiltersDemo.MainForm.convolutionFiltersItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.ApplyFilter(), and FiltersDemo.MainForm.convolutionFiltersItem.
sharpenFiltersItem_Click()
void FiltersDemo.MainForm.sharpenFiltersItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.ApplyFilter(), and FiltersDemo.MainForm.sharpenFiltersItem.
differenceEdgesFiltersItem_Click()
void FiltersDemo.MainForm.differenceEdgesFiltersItem_Click (object sender, System.EventArgs e) inline private
References AForge.Imaging.Filters.BaseFilter.Apply(), FiltersDemo.MainForm.ApplyFilter(), FiltersDemo.MainForm.differenceEdgesFiltersItem, AForge.Imaging.Filters.Grayscale.CommonAlgorithms.RMY, and FiltersDemo.MainForm.sourceImage.
homogenityEdgesFiltersItem_Click()
void FiltersDemo.MainForm.homogenityEdgesFiltersItem_Click (object sender, System.EventArgs e) inline private
References AForge.Imaging.Filters.BaseFilter.Apply(), FiltersDemo.MainForm.ApplyFilter(), FiltersDemo.MainForm.homogenityEdgesFiltersItem, AForge.Imaging.Filters.Grayscale.CommonAlgorithms.RMY, and FiltersDemo.MainForm.sourceImage.
sobelEdgesFiltersItem_Click()
void FiltersDemo.MainForm.sobelEdgesFiltersItem_Click (object sender, System.EventArgs e) inline private
References AForge.Imaging.Filters.BaseFilter.Apply(), FiltersDemo.MainForm.ApplyFilter(), AForge.Imaging.Filters.Grayscale.CommonAlgorithms.RMY, FiltersDemo.MainForm.sobelEdgesFiltersItem, and FiltersDemo.MainForm.sourceImage.
rgbLinearFiltersItem_Click()
void FiltersDemo.MainForm.rgbLinearFiltersItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.ApplyFilter(), AForge.Imaging.Filters.LevelsLinear.InBlue, AForge.Imaging.Filters.LevelsLinear.InGreen, AForge.Imaging.Filters.LevelsLinear.InRed, and FiltersDemo.MainForm.rgbLinearFiltersItem.
jitterFiltersItem_Click()
void FiltersDemo.MainForm.jitterFiltersItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.ApplyFilter(), and FiltersDemo.MainForm.jitterFiltersItem.
oilFiltersItem_Click()
void FiltersDemo.MainForm.oilFiltersItem_Click (object sender, System.EventArgs e) inline private
References FiltersDemo.MainForm.ApplyFilter(), and FiltersDemo.MainForm.oilFiltersItem.
gaussianFiltersItem_Click()
void FiltersDemo.MainForm.gaussianFiltersItem_Click (object sender, EventArgs e) inline private
References FiltersDemo.MainForm.ApplyFilter(), and FiltersDemo.MainForm.gaussianFiltersItem.
textureFiltersItem_Click()
void FiltersDemo.MainForm.textureFiltersItem_Click (object sender, EventArgs e) inline private
References FiltersDemo.MainForm.ApplyFilter(), and FiltersDemo.MainForm.textureFiltersItem.
Member Data Documentation
fileItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.fileItem private
openFileItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.openFileItem private
menuItem3
System.Windows.Forms.MenuItem FiltersDemo.MainForm.menuItem3 private
exitFilrItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.exitFilrItem private
openFileDialog
System.Windows.Forms.OpenFileDialog FiltersDemo.MainForm.openFileDialog private
Referenced by FiltersDemo.MainForm.openFileItem_Click().
pictureBox
System.Windows.Forms.PictureBox FiltersDemo.MainForm.pictureBox private
Referenced by FiltersDemo.MainForm.ApplyFilter(), FiltersDemo.MainForm.centeredSizeItem_Click(), FiltersDemo.MainForm.ClearCurrentImage(), FiltersDemo.MainForm.MainForm(), FiltersDemo.MainForm.noneFiltersItem_Click(), FiltersDemo.MainForm.normalSizeItem_Click(), FiltersDemo.MainForm.openFileItem_Click(), FiltersDemo.MainForm.sizeItem_Popup(), and FiltersDemo.MainForm.stretchedSizeItem_Click().
mainMenu
System.Windows.Forms.MainMenu FiltersDemo.MainForm.mainMenu private
sizeItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.sizeItem private
normalSizeItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.normalSizeItem private
Referenced by FiltersDemo.MainForm.sizeItem_Popup().
stretchedSizeItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.stretchedSizeItem private
Referenced by FiltersDemo.MainForm.sizeItem_Popup().
centeredSizeItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.centeredSizeItem private
Referenced by FiltersDemo.MainForm.sizeItem_Popup().
filtersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.filtersItem private
Referenced by FiltersDemo.MainForm.ClearCurrentImage(), and FiltersDemo.MainForm.openFileItem_Click().
noneFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.noneFiltersItem private
Referenced by FiltersDemo.MainForm.ClearCurrentImage(), FiltersDemo.MainForm.noneFiltersItem_Click(), and FiltersDemo.MainForm.openFileItem_Click().
menuItem1
System.Windows.Forms.MenuItem FiltersDemo.MainForm.menuItem1 private
sepiaFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.sepiaFiltersItem private
Referenced by FiltersDemo.MainForm.sepiaFiltersItem_Click().
invertFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.invertFiltersItem private
Referenced by FiltersDemo.MainForm.invertFiltersItem_Click().
rotateChannelFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.rotateChannelFiltersItem private
Referenced by FiltersDemo.MainForm.rotateChannelFiltersItem_Click().
grayscaleFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.grayscaleFiltersItem private
Referenced by FiltersDemo.MainForm.grayscaleFiltersItem_Click().
colorFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.colorFiltersItem private
Referenced by FiltersDemo.MainForm.colorFiltersItem_Click().
menuItem2
System.Windows.Forms.MenuItem FiltersDemo.MainForm.menuItem2 private
hueModifierFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.hueModifierFiltersItem private
Referenced by FiltersDemo.MainForm.hueModifierFiltersItem_Click().
saturationAdjustingFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.saturationAdjustingFiltersItem private
Referenced by FiltersDemo.MainForm.saturationAdjustingFiltersItem_Click().
brightnessAdjustingFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.brightnessAdjustingFiltersItem private
Referenced by FiltersDemo.MainForm.brightnessAdjustingFiltersItem_Click().
contrastAdjustingFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.contrastAdjustingFiltersItem private
Referenced by FiltersDemo.MainForm.contrastAdjustingFiltersItem_Click().
hslFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.hslFiltersItem private
Referenced by FiltersDemo.MainForm.hslFiltersItem_Click().
menuItem4
System.Windows.Forms.MenuItem FiltersDemo.MainForm.menuItem4 private
yCbCrLinearFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.yCbCrLinearFiltersItem private
Referenced by FiltersDemo.MainForm.yCbCrLinearFiltersItem_Click().
yCbCrFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.yCbCrFiltersItem private
Referenced by FiltersDemo.MainForm.yCbCrFiltersItem_Click().
menuItem5
System.Windows.Forms.MenuItem FiltersDemo.MainForm.menuItem5 private
thresholdFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.thresholdFiltersItem private
Referenced by FiltersDemo.MainForm.thresholdFiltersItem_Click().
floydFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.floydFiltersItem private
Referenced by FiltersDemo.MainForm.floydFiltersItem_Click().
orderedDitheringFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.orderedDitheringFiltersItem private
Referenced by FiltersDemo.MainForm.orderedDitheringFiltersItem_Click().
menuItem6
System.Windows.Forms.MenuItem FiltersDemo.MainForm.menuItem6 private
convolutionFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.convolutionFiltersItem private
Referenced by FiltersDemo.MainForm.convolutionFiltersItem_Click().
sharpenFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.sharpenFiltersItem private
Referenced by FiltersDemo.MainForm.sharpenFiltersItem_Click().
menuItem7
System.Windows.Forms.MenuItem FiltersDemo.MainForm.menuItem7 private
differenceEdgesFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.differenceEdgesFiltersItem private
Referenced by FiltersDemo.MainForm.differenceEdgesFiltersItem_Click().
homogenityEdgesFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.homogenityEdgesFiltersItem private
Referenced by FiltersDemo.MainForm.homogenityEdgesFiltersItem_Click().
sobelEdgesFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.sobelEdgesFiltersItem private
Referenced by FiltersDemo.MainForm.sobelEdgesFiltersItem_Click().
rgbLinearFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.rgbLinearFiltersItem private
Referenced by FiltersDemo.MainForm.rgbLinearFiltersItem_Click().
menuItem8
System.Windows.Forms.MenuItem FiltersDemo.MainForm.menuItem8 private
jitterFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.jitterFiltersItem private
Referenced by FiltersDemo.MainForm.jitterFiltersItem_Click().
oilFiltersItem
System.Windows.Forms.MenuItem FiltersDemo.MainForm.oilFiltersItem private
Referenced by FiltersDemo.MainForm.oilFiltersItem_Click().
gaussianFiltersItem
MenuItem FiltersDemo.MainForm.gaussianFiltersItem private
Referenced by FiltersDemo.MainForm.gaussianFiltersItem_Click().
textureFiltersItem
MenuItem FiltersDemo.MainForm.textureFiltersItem private
Referenced by FiltersDemo.MainForm.textureFiltersItem_Click().
components
IContainer FiltersDemo.MainForm.components private
Referenced by FiltersDemo.MainForm.Dispose().
sourceImage
System.Drawing.Bitmap FiltersDemo.MainForm.sourceImage private
Referenced by FiltersDemo.MainForm.ApplyFilter(), FiltersDemo.MainForm.differenceEdgesFiltersItem_Click(), FiltersDemo.MainForm.floydFiltersItem_Click(), FiltersDemo.MainForm.homogenityEdgesFiltersItem_Click(), FiltersDemo.MainForm.noneFiltersItem_Click(), FiltersDemo.MainForm.openFileItem_Click(), FiltersDemo.MainForm.orderedDitheringFiltersItem_Click(), FiltersDemo.MainForm.sobelEdgesFiltersItem_Click(), and FiltersDemo.MainForm.thresholdFiltersItem_Click().
filteredImage
System.Drawing.Bitmap FiltersDemo.MainForm.filteredImage private
Referenced by FiltersDemo.MainForm.ApplyFilter(), and FiltersDemo.MainForm.ClearCurrentImage().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Samples/Imaging/FiltersDemo/MainForm.cs