Doc: IGLib EXTENDED: IG.Neural.Applications.NeuralParametricDemoAboutWindow Class Reference
IG.Neural.Applications.NeuralParametricDemoAboutWindow Class Reference
Window that displays information about Demo application for performing parametric studies on ANN models.
Public Member Functions
NeuralParametricDemoAboutWindow ()
void ShowHelp ()
void ShowWebPage ()
NeuralParametricDemoAboutWindow ()
void ShowHelp ()
void ShowWebPage ()
NeuralParametricDemoAboutWindow ()
void ShowHelp ()
void ShowWebPage ()
NeuralParametricDemoAboutWindow ()
void ShowHelp ()
void ShowWebPage ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
Applications.NeuralParametricDemoAbout neuralParametricDemoAbout1
Detailed Description
Window that displays information about Demo application for performing parametric studies on ANN models.
$A Igor Apr13;
Constructor & Destructor Documentation
NeuralParametricDemoAboutWindow() [1/4]
IG.Neural.Applications.NeuralParametricDemoAboutWindow.NeuralParametricDemoAboutWindow () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindow.InitializeComponent().
NeuralParametricDemoAboutWindow() [2/4]
IG.Neural.Applications.NeuralParametricDemoAboutWindow.NeuralParametricDemoAboutWindow () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindow.InitializeComponent().
NeuralParametricDemoAboutWindow() [3/4]
IG.Neural.Applications.NeuralParametricDemoAboutWindow.NeuralParametricDemoAboutWindow () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindow.InitializeComponent().
NeuralParametricDemoAboutWindow() [4/4]
IG.Neural.Applications.NeuralParametricDemoAboutWindow.NeuralParametricDemoAboutWindow () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindow.InitializeComponent().
Member Function Documentation
ShowHelp() [1/4]
void IG.Neural.Applications.NeuralParametricDemoAboutWindow.ShowHelp () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindow.neuralParametricDemoAbout1, and IG.Neural.Applications.NeuralParametricDemoAbout.ShowHelp().
Referenced by IG.Neural.Applications.AnnAppDemo.NeuralParametricDemo_HelpEventHandlers().
ShowWebPage() [1/4]
void IG.Neural.Applications.NeuralParametricDemoAboutWindow.ShowWebPage () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindow.neuralParametricDemoAbout1, and IG.Neural.Applications.NeuralParametricDemoAbout.ShowWebPage().
Dispose() [1/4]
override void IG.Neural.Applications.NeuralParametricDemoAboutWindow.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralParametricDemoAboutWindow.components.
InitializeComponent() [1/4]
void IG.Neural.Applications.NeuralParametricDemoAboutWindow.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralParametricDemoAboutWindow.neuralParametricDemoAbout1.
Referenced by IG.Neural.Applications.NeuralParametricDemoAboutWindow.NeuralParametricDemoAboutWindow().
ShowHelp() [2/4]
void IG.Neural.Applications.NeuralParametricDemoAboutWindow.ShowHelp () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindow.neuralParametricDemoAbout1, and IG.Neural.Applications.NeuralParametricDemoAbout.ShowHelp().
ShowWebPage() [2/4]
void IG.Neural.Applications.NeuralParametricDemoAboutWindow.ShowWebPage () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindow.neuralParametricDemoAbout1, and IG.Neural.Applications.NeuralParametricDemoAbout.ShowWebPage().
Dispose() [2/4]
override void IG.Neural.Applications.NeuralParametricDemoAboutWindow.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralParametricDemoAboutWindow.components.
InitializeComponent() [2/4]
void IG.Neural.Applications.NeuralParametricDemoAboutWindow.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralParametricDemoAboutWindow.neuralParametricDemoAbout1.
ShowHelp() [3/4]
void IG.Neural.Applications.NeuralParametricDemoAboutWindow.ShowHelp () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindow.neuralParametricDemoAbout1, and IG.Neural.Applications.NeuralParametricDemoAbout.ShowHelp().
ShowWebPage() [3/4]
void IG.Neural.Applications.NeuralParametricDemoAboutWindow.ShowWebPage () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindow.neuralParametricDemoAbout1, and IG.Neural.Applications.NeuralParametricDemoAbout.ShowWebPage().
Dispose() [3/4]
override void IG.Neural.Applications.NeuralParametricDemoAboutWindow.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralParametricDemoAboutWindow.components.
InitializeComponent() [3/4]
void IG.Neural.Applications.NeuralParametricDemoAboutWindow.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralParametricDemoAboutWindow.neuralParametricDemoAbout1.
ShowHelp() [4/4]
void IG.Neural.Applications.NeuralParametricDemoAboutWindow.ShowHelp () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindow.neuralParametricDemoAbout1, and IG.Neural.Applications.NeuralParametricDemoAbout.ShowHelp().
ShowWebPage() [4/4]
void IG.Neural.Applications.NeuralParametricDemoAboutWindow.ShowWebPage () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindow.neuralParametricDemoAbout1, and IG.Neural.Applications.NeuralParametricDemoAbout.ShowWebPage().
Dispose() [4/4]
override void IG.Neural.Applications.NeuralParametricDemoAboutWindow.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralParametricDemoAboutWindow.components.
InitializeComponent() [4/4]
void IG.Neural.Applications.NeuralParametricDemoAboutWindow.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralParametricDemoAboutWindow.neuralParametricDemoAbout1.
Member Data Documentation
components
System ComponentModel IContainer IG.Neural.Applications.NeuralParametricDemoAboutWindow.components = null private
Required designer variable.
Referenced by IG.Neural.Applications.NeuralParametricDemoAboutWindow.Dispose().
neuralParametricDemoAbout1
Applications NeuralParametricDemoAbout IG.Neural.Applications.NeuralParametricDemoAboutWindow.neuralParametricDemoAbout1 private
Referenced by IG.Neural.Applications.NeuralParametricDemoAboutWindow.InitializeComponent(), IG.Neural.Applications.NeuralParametricDemoAboutWindow.ShowHelp(), and IG.Neural.Applications.NeuralParametricDemoAboutWindow.ShowWebPage().
The documentation for this class was generated from the following files:
shelldev/extensions/ExtAppAnnApp/ResponseForms/NeuralParametricDemoAboutWindow.cs
shelldev/extensions/ExtAppAnnApp/ResponseForms/NeuralParametricDemoAboutWindow.Designer.cs