Doc: IGLib EXTENDED: NUnit.Framework.Api.DefaultTestAssemblyBuilder Class Reference
NUnit.Framework.Api.DefaultTestAssemblyBuilder Class Reference
DefaultTestAssemblyBuilder loads a single assembly and builds a TestSuite containing test fixtures present in the assembly.
Public Member Functions
DefaultTestAssemblyBuilder ()
Initializes a new instance of the DefaultTestAssemblyBuilder class.
ITest Build (Assembly assembly, IDictionary options)
Build a suite of tests from a provided assembly
ITest Build (string assemblyName, IDictionary options)
Build a suite of tests given the filename of an assembly
Private Member Functions
TestSuite Build (Assembly assembly, string assemblyPath, IDictionary options)
IList< Test > GetFixtures (Assembly assembly, IList names)
IList< Type > GetCandidateFixtureTypes (Assembly assembly, IList names)
TestSuite BuildTestAssembly (Assembly assembly, string assemblyName, IList< Test > fixtures)
Private Attributes
ISuiteBuilder _defaultSuiteBuilder
The default suite builder used by the test assembly builder.
Static Private Attributes
static Logger log = InternalTrace.GetLogger(typeof(DefaultTestAssemblyBuilder))
Detailed Description
DefaultTestAssemblyBuilder loads a single assembly and builds a TestSuite containing test fixtures present in the assembly.
Constructor & Destructor Documentation
DefaultTestAssemblyBuilder()
NUnit.Framework.Api.DefaultTestAssemblyBuilder.DefaultTestAssemblyBuilder () inline
Initializes a new instance of the DefaultTestAssemblyBuilder class.
References NUnit.Framework.Api.DefaultTestAssemblyBuilder._defaultSuiteBuilder.
Member Function Documentation
Build() [1/3]
ITest NUnit.Framework.Api.DefaultTestAssemblyBuilder.Build (Assembly assembly, IDictionary options) inline
Build a suite of tests from a provided assembly
Parameters
assembly The assembly from which tests are to be built
options A dictionary of options to use in building the suite
Returns
A TestSuite containing the tests found in the assembly
Implements NUnit.Framework.Api.ITestAssemblyBuilder.
References NUnit.Common.Logger.Debug(), NUnit.Common.AssemblyHelper.GetAssemblyName(), NUnit.Common.AssemblyHelper.GetAssemblyPath(), and NUnit.Framework.Api.DefaultTestAssemblyBuilder.log.
Referenced by NUnit.Framework.Api.DefaultTestAssemblyBuilder.Build().
Build() [2/3]
ITest NUnit.Framework.Api.DefaultTestAssemblyBuilder.Build (string assemblyName, IDictionary options) inline
Build a suite of tests given the filename of an assembly
Parameters
assemblyName The filename of the assembly from which tests are to be built
options A dictionary of options to use in building the suite
Returns
A TestSuite containing the tests found in the assembly
Implements NUnit.Framework.Api.ITestAssemblyBuilder.
References NUnit.Framework.Api.DefaultTestAssemblyBuilder.Build(), NUnit.Common.Logger.Debug(), NUnit.Common.AssemblyHelper.Load(), NUnit.Framework.Api.DefaultTestAssemblyBuilder.log, NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Interfaces.IPropertyBag.Set(), and NUnit.Framework.Internal.PropertyNames.SkipReason.
Build() [3/3]
TestSuite NUnit.Framework.Api.DefaultTestAssemblyBuilder.Build (Assembly assembly, string assemblyPath, IDictionary options) inline private
References NUnit.Framework.Api.DefaultTestAssemblyBuilder.BuildTestAssembly(), NUnit.Framework.Api.DefaultTestAssemblyBuilder.GetFixtures(), NUnit.Common.PackageSettings.LOAD, NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Interfaces.IPropertyBag.Set(), and NUnit.Framework.Internal.PropertyNames.SkipReason.
GetFixtures()
IList<Test> NUnit.Framework.Api.DefaultTestAssemblyBuilder.GetFixtures (Assembly assembly, IList names) inline private
References NUnit.Framework.Api.DefaultTestAssemblyBuilder._defaultSuiteBuilder, NUnit.Framework.Internal.TestSuite.Add(), NUnit.Framework.Interfaces.ISuiteBuilder.BuildFrom(), NUnit.Framework.Interfaces.ISuiteBuilder.CanBuildFrom(), NUnit.Common.Logger.Debug(), NUnit.Common.Logger.Error(), NUnit.Framework.Api.DefaultTestAssemblyBuilder.GetCandidateFixtureTypes(), NUnit.Framework.Api.DefaultTestAssemblyBuilder.log, and NUnit.Framework.Internal.Test.TestCaseCount.
Referenced by NUnit.Framework.Api.DefaultTestAssemblyBuilder.Build().
GetCandidateFixtureTypes()
IList<Type> NUnit.Framework.Api.DefaultTestAssemblyBuilder.GetCandidateFixtureTypes (Assembly assembly, IList names) inline private
Referenced by NUnit.Framework.Api.DefaultTestAssemblyBuilder.GetFixtures().
BuildTestAssembly()
TestSuite NUnit.Framework.Api.DefaultTestAssemblyBuilder.BuildTestAssembly (Assembly assembly, string assemblyName, IList< Test > fixtures) inline private
References NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.Add(), NUnit.Framework.Internal.PropertyNames.AppDomain, NUnit.Framework.Internal.Test.ApplyAttributesToTest(), NUnit.Framework.Internal.PropertyNames.ProcessID, NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.RootSuite, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Interfaces.IPropertyBag.Set(), NUnit.Framework.Internal.PropertyNames.SkipReason, and NUnit.Framework.Internal.TestSuite.Sort().
Referenced by NUnit.Framework.Api.DefaultTestAssemblyBuilder.Build().
Member Data Documentation
log
Logger NUnit.Framework.Api.DefaultTestAssemblyBuilder.log = InternalTrace.GetLogger(typeof(DefaultTestAssemblyBuilder)) static private
Referenced by NUnit.Framework.Api.DefaultTestAssemblyBuilder.Build(), and NUnit.Framework.Api.DefaultTestAssemblyBuilder.GetFixtures().
_defaultSuiteBuilder
ISuiteBuilder NUnit.Framework.Api.DefaultTestAssemblyBuilder._defaultSuiteBuilder private
The default suite builder used by the test assembly builder.
Referenced by NUnit.Framework.Api.DefaultTestAssemblyBuilder.DefaultTestAssemblyBuilder(), and NUnit.Framework.Api.DefaultTestAssemblyBuilder.GetFixtures().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Api/DefaultTestAssemblyBuilder.cs