Doc: IGLib EXTENDED: ParallelTest.Program Class Reference
ParallelTest.Program Class Reference
Static Private Member Functions
static void Main (string[] args)
static void Test1 (double[,] a, double[,] b, double[,] c)
static void Test2 (double[,] a, double[,] b, double[,] c)
Member Function Documentation
Main()
static void ParallelTest.Program.Main (string[] args) inline static private
References ParallelTest.Program.Test1(), ParallelTest.Program.Test2(), and AForge.Parallel.ThreadsCount.
Test1()
static void ParallelTest.Program.Test1 (double a[,], double b[,], double c[,]) inline static private
Referenced by ParallelTest.Program.Main().
Test2()
static void ParallelTest.Program.Test2 (double a[,], double b[,], double c[,]) inline static private
References AForge.Parallel.For().
Referenced by ParallelTest.Program.Main().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Samples/Core/ParallelTest/Program.cs