Doc: IGLib EXTENDED: AForge.Video.IVideoSource Interface Reference
AForge.Video.IVideoSource Interface Reference
Video source interface.
Public Member Functions
void Start ()
Start video source.
void SignalToStop ()
Signal video source to stop its work.
void WaitForStop ()
Wait for video source has stopped.
void Stop ()
Stop video source.
Properties
string Source [get]
Video source.
int FramesReceived [get]
Received frames count.
long BytesReceived [get]
Received bytes count.
bool IsRunning [get]
State of the video source.
Events
NewFrameEventHandler NewFrame
New frame event.
VideoSourceErrorEventHandler VideoSourceError
Video source error event.
PlayingFinishedEventHandler PlayingFinished
Video playing finished event.
Detailed Description
Video source interface.
The interface describes common methods for different type of video sources.
Member Function Documentation
Start()
void AForge.Video.IVideoSource.Start ()
Start video source.
Starts video source and return execution to caller. Video source object creates background thread and notifies about new frames with the help of NewFrame event.
Implemented in AForge.Video.DirectShow.VideoCaptureDevice, AForge.Video.JPEGStream, AForge.Video.MJPEGStream, AForge.Video.AsyncVideoSource, AForge.Video.Kinect.KinectVideoCamera, AForge.Video.Kinect.KinectDepthCamera, AForge.Robotics.TeRK.Qwerk.Video, AForge.Video.DirectShow.FileVideoSource, AForge.Video.VFW.AVIFileVideoSource, AForge.Video.Ximea.XimeaVideoSource, and AForge.Robotics.Surveyor.SRV1Camera.
Referenced by AForge.Controls.VideoSourcePlayer.Start(), and AForge.Video.AsyncVideoSource.Start().
SignalToStop()
void AForge.Video.IVideoSource.SignalToStop ()
Signal video source to stop its work.
Signals video source to stop its background thread, stop to provide new frames and free resources.
Implemented in AForge.Video.DirectShow.VideoCaptureDevice, AForge.Video.Kinect.KinectVideoCamera, AForge.Video.JPEGStream, AForge.Video.MJPEGStream, AForge.Video.Kinect.KinectDepthCamera, AForge.Video.AsyncVideoSource, AForge.Video.DirectShow.FileVideoSource, AForge.Robotics.TeRK.Qwerk.Video, AForge.Video.Ximea.XimeaVideoSource, AForge.Video.VFW.AVIFileVideoSource, and AForge.Robotics.Surveyor.SRV1Camera.
Referenced by SRVTest.MainForm.Disconnect(), SVSTest.MainForm.Disconnect(), AForge.Video.AsyncVideoSource.SignalToStop(), and AForge.Controls.VideoSourcePlayer.SignalToStop().
WaitForStop()
void AForge.Video.IVideoSource.WaitForStop ()
Wait for video source has stopped.
Waits for video source stopping after it was signalled to stop using SignalToStop method.
Implemented in AForge.Video.DirectShow.VideoCaptureDevice, AForge.Video.JPEGStream, AForge.Video.Kinect.KinectVideoCamera, AForge.Video.MJPEGStream, AForge.Video.Kinect.KinectDepthCamera, AForge.Video.AsyncVideoSource, AForge.Video.DirectShow.FileVideoSource, AForge.Robotics.TeRK.Qwerk.Video, AForge.Video.Ximea.XimeaVideoSource, AForge.Video.VFW.AVIFileVideoSource, and AForge.Robotics.Surveyor.SRV1Camera.
Referenced by SRVTest.MainForm.Disconnect(), SVSTest.MainForm.Disconnect(), AForge.Video.AsyncVideoSource.WaitForStop(), and AForge.Controls.VideoSourcePlayer.WaitForStop().
Stop()
void AForge.Video.IVideoSource.Stop ()
Stop video source.
Stops video source aborting its thread.
Implemented in AForge.Video.DirectShow.VideoCaptureDevice, AForge.Video.JPEGStream, AForge.Video.MJPEGStream, AForge.Video.Kinect.KinectVideoCamera, AForge.Video.Kinect.KinectDepthCamera, AForge.Video.AsyncVideoSource, AForge.Video.DirectShow.FileVideoSource, AForge.Robotics.TeRK.Qwerk.Video, AForge.Video.Ximea.XimeaVideoSource, AForge.Video.VFW.AVIFileVideoSource, and AForge.Robotics.Surveyor.SRV1Camera.
Referenced by AForge.Controls.VideoSourcePlayer.Stop(), and AForge.Video.AsyncVideoSource.Stop().
Property Documentation
Source
string AForge.Video.IVideoSource.Source get
Video source.
The meaning of the property depends on particular video source. Depending on video source it may be a file name, URL or any other string describing the video source.
FramesReceived
int AForge.Video.IVideoSource.FramesReceived get
Received frames count.
Number of frames the video source provided from the moment of the last access to the property.
Referenced by TwoCamerasTest.MainForm.timer_Tick(), SRVTest.MainForm.timer_Tick(), SVSTest.MainForm.timer_Tick(), Player.MainForm.timer_Tick(), QwerkStart.MainForm.timer_Tick(), and MotionDetectorSample.MainForm.timer_Tick().
BytesReceived
long AForge.Video.IVideoSource.BytesReceived get
Received bytes count.
Number of bytes the video source provided from the moment of the last access to the property.
IsRunning
bool AForge.Video.IVideoSource.IsRunning get
State of the video source.
Current state of video source object - running or not.
Referenced by MotionDetectorSample.MainForm.crossbarVideoSettingsToolStripMenuItem_Click(), and MotionDetectorSample.MainForm.toolsToolStripMenuItem_DropDownOpening().
Event Documentation
NewFrame
NewFrameEventHandler AForge.Video.IVideoSource.NewFrame
New frame event.
This event is used to notify clients about new available video frame.
<note>Since video source may have multiple clients, each client is responsible for making a copy (cloning) of the passed video frame, but video source is responsible for disposing its own original copy after notifying of clients.</note>
Referenced by AForge.Video.AsyncVideoSource.Free(), and AForge.Video.AsyncVideoSource.Start().
VideoSourceError
VideoSourceErrorEventHandler AForge.Video.IVideoSource.VideoSourceError
Video source error event.
This event is used to notify clients about any type of errors occurred in video source object, for example internal exceptions.
PlayingFinished
PlayingFinishedEventHandler AForge.Video.IVideoSource.PlayingFinished
Video playing finished event.
This event is used to notify clients that the video playing has finished.
The documentation for this interface was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Video/IVideoSource.cs