Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAED8 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAED8 Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAED8 (IDAMAX idamax, DLAMCH dlamch, DLAPY2 dlapy2, DCOPY dcopy, DLACPY dlacpy, DLAMRG dlamrg, DROT drot, DSCAL dscal, XERBLA xerbla)
DLAED8 ()
void Run (int ICOMPQ, ref int K, int N, int QSIZ, ref double[] D, int offset_d, ref double[] Q, int offset_q, int LDQ, ref int[] INDXQ, int offset_indxq, ref double RHO, int CUTPNT, ref double[] Z, int offset_z, ref double[] DLAMDA, int offset_dlamda, ref double[] Q2, int offset_q2, int LDQ2, ref double[] W, int offset_w, ref int[] PERM, int offset_perm, ref int GIVPTR, ref int[] GIVCOL, int offset_givcol, ref double[] GIVNUM, int offset_givnum, ref int[] INDXP, int offset_indxp, ref int[] INDX, int offset_indx, ref int INFO)
Private Attributes
IDAMAX _idamax
DLAMCH _dlamch
DLAPY2 _dlapy2
DCOPY _dcopy
DLACPY _dlacpy
DLAMRG _dlamrg
DROT _drot
DSCAL _dscal
XERBLA _xerbla
Static Private Attributes
const double MONE = - 1.0E0
const double ZERO = 0.0E0
const double ONE = 1.0E0
const double TWO = 2.0E0
const double EIGHT = 8.0E0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAED8 merges the two sets of eigenvalues together into a single sorted set. Then it tries to deflate the size of the problem. There are two ways in which deflation can occur: when two or more eigenvalues are close together or if there is a tiny element in the Z vector. For each such occurrence the order of the related secular equation problem is reduced by one.
/summary>
Constructor & Destructor Documentation
DLAED8() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAED8.DLAED8 (IDAMAX idamax, DLAMCH dlamch, DLAPY2 dlapy2, DCOPY dcopy, DLACPY dlacpy, DLAMRG dlamrg, DROT drot, DSCAL dscal, XERBLA xerbla) inline
DLAED8() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAED8.DLAED8 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAED8.Run (int ICOMPQ, ref int K, int N, int QSIZ, ref double[] D, int offset_d, ref double[] Q, int offset_q, int LDQ, ref int[] INDXQ, int offset_indxq, ref double RHO, int CUTPNT, ref double[] Z, int offset_z, ref double[] DLAMDA, int offset_dlamda, ref double[] Q2, int offset_q2, int LDQ2, ref double[] W, int offset_w, ref int[] PERM, int offset_perm, ref int GIVPTR, ref int[] GIVCOL, int offset_givcol, ref double[] GIVNUM, int offset_givnum, ref int[] INDXP, int offset_indxp, ref int[] INDX, int offset_indx, ref int INFO) inline
Purpose
DLAED8 merges the two sets of eigenvalues together into a single sorted set. Then it tries to deflate the size of the problem. There are two ways in which deflation can occur: when two or more eigenvalues are close together or if there is a tiny element in the Z vector. For each such occurrence the order of the related secular equation problem is reduced by one.
/summary>
Parameters
ICOMPQ (input) INTEGER = 0: Compute eigenvalues only. = 1: Compute eigenvectors of original dense symmetric matrix also. On entry, Q contains the orthogonal matrix used to reduce the original matrix to tridiagonal form. /param>
Parameters
K (output) INTEGER The number of non-deflated eigenvalues, and the order of the related secular equation. /param>
Parameters
N (input) INTEGER The dimension of the symmetric tridiagonal matrix. N .GE. 0. /param>
Parameters
QSIZ (input) INTEGER The dimension of the orthogonal matrix used to reduce the full matrix to tridiagonal form. QSIZ .GE. N if ICOMPQ = 1. /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension (N) On entry, the eigenvalues of the two submatrices to be combined. On exit, the trailing (N-K) updated eigenvalues (those which were deflated) sorted into increasing order. /param>
Parameters
Q (input/output) DOUBLE PRECISION array, dimension (LDQ,N) If ICOMPQ = 0, Q is not referenced. Otherwise, on entry, Q contains the eigenvectors of the partially solved system which has been previously updated in matrix multiplies with other partially solved eigensystems. On exit, Q contains the trailing (N-K) updated eigenvectors (those which were deflated) in its last N-K columns. /param>
Parameters
LDQ (input) INTEGER The leading dimension of the array Q. LDQ .GE. max(1,N). /param>
Parameters
INDXQ (input) INTEGER array, dimension (N) The permutation which separately sorts the two sub-problems in D into ascending order. Note that elements in the second half of this permutation must first have CUTPNT added to their values in order to be accurate. /param>
Parameters
RHO (input/output) DOUBLE PRECISION On entry, the off-diagonal element associated with the rank-1 cut which originally split the two submatrices which are now being recombined. On exit, RHO has been modified to the value required by DLAED3. /param>
Parameters
CUTPNT (input) INTEGER The location of the last eigenvalue in the leading sub-matrix. min(1,N) .LE. CUTPNT .LE. N. /param>
Parameters
Z (input) DOUBLE PRECISION array, dimension (N) On entry, Z contains the updating vector (the last row of the first sub-eigenvector matrix and the first row of the second sub-eigenvector matrix). On exit, the contents of Z are destroyed by the updating process. /param>
Parameters
DLAMDA (output) DOUBLE PRECISION array, dimension (N) A copy of the first K eigenvalues which will be used by DLAED3 to form the secular equation. /param>
Parameters
Q2 (output) DOUBLE PRECISION array, dimension (LDQ2,N) If ICOMPQ = 0, Q2 is not referenced. Otherwise, a copy of the first K eigenvectors which will be used by DLAED7 in a matrix multiply (DGEMM) to update the new eigenvectors. /param>
Parameters
LDQ2 (input) INTEGER The leading dimension of the array Q2. LDQ2 .GE. max(1,N). /param>
Parameters
W (output) DOUBLE PRECISION array, dimension (N) The first k values of the final deflation-altered z-vector and will be passed to DLAED3. /param>
Parameters
PERM (output) INTEGER array, dimension (N) The permutations (from deflation and sorting) to be applied to each eigenblock. /param>
Parameters
GIVPTR (output) INTEGER The number of Givens rotations which took place in this subproblem. /param>
Parameters
GIVCOL (output) INTEGER array, dimension (2, N) Each pair of numbers indicates a pair of columns to take place in a Givens rotation. /param>
Parameters
GIVNUM (output) DOUBLE PRECISION array, dimension (2, N) Each number indicates the S value to be used in the corresponding Givens rotation. /param>
Parameters
INDXP (workspace) INTEGER array, dimension (N) The permutation used to place deflated values of D at the end of the array. INDXP(1:K) points to the nondeflated D-values and INDXP(K+1:N) points to the deflated eigenvalues. /param>
Parameters
INDX (workspace) INTEGER array, dimension (N) The permutation used to sort the contents of D into ascending order. /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLAED8.EIGHT, DotNumerics.LinearAlgebra.CSLapack.DLAED8.MONE, DotNumerics.LinearAlgebra.CSLapack.DLAED8.ONE, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DROT.Run(), DotNumerics.LinearAlgebra.CSLapack.IDAMAX.Run(), DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAPY2.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMRG.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED8.TWO, and DotNumerics.LinearAlgebra.CSLapack.DLAED8.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED7.Run().
Member Data Documentation
_idamax
IDAMAX DotNumerics.LinearAlgebra.CSLapack.DLAED8._idamax private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLAED8._dlamch private
_dlapy2
DLAPY2 DotNumerics.LinearAlgebra.CSLapack.DLAED8._dlapy2 private
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLAED8._dcopy private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DLAED8._dlacpy private
_dlamrg
DLAMRG DotNumerics.LinearAlgebra.CSLapack.DLAED8._dlamrg private
_drot
DROT DotNumerics.LinearAlgebra.CSLapack.DLAED8._drot private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DLAED8._dscal private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLAED8._xerbla private
MONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAED8.MONE = - 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED8.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAED8.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED8.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAED8.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED8.Run().
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DLAED8.TWO = 2.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED8.Run().
EIGHT
const double DotNumerics.LinearAlgebra.CSLapack.DLAED8.EIGHT = 8.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED8.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlaed8.cs