Doc: IGLib EXTENDED: AForge.Imaging.Textures.ITextureGenerator Interface Reference
AForge.Imaging.Textures.ITextureGenerator Interface Reference
Texture generator interface.
Public Member Functions
float[,] Generate (int width, int height)
Generate texture.
void Reset ()
Reset generator.
Detailed Description
Texture generator interface.
Each texture generator generates a 2-D texture of the specified size and returns it as two dimensional array of intensities in the range of [0, 1] - texture's values.
Member Function Documentation
Generate()
float [,] AForge.Imaging.Textures.ITextureGenerator.Generate (int width, int height)
Generate texture.
Parameters
width Texture's width.
height Texture's height.
Returns
Two dimensional array of texture's intensities.
Generates new texture of the specified size.
Implemented in AForge.Imaging.Textures.MarbleTexture, AForge.Imaging.Textures.WoodTexture, AForge.Imaging.Textures.CloudsTexture, AForge.Imaging.Textures.LabyrinthTexture, and AForge.Imaging.Textures.TextileTexture.
Referenced by AForge.Imaging.Filters.TexturedMerge.ProcessFilter(), AForge.Imaging.Filters.Texturer.ProcessFilter(), AForge.Imaging.Filters.TexturedFilter.ProcessFilter(), and TexturesDemo.MainForm.ShowTexture().
Reset()
void AForge.Imaging.Textures.ITextureGenerator.Reset ()
Reset generator.
Resets the generator - resets all internal variables, regenerates internal random numbers, etc.
Implemented in AForge.Imaging.Textures.MarbleTexture, AForge.Imaging.Textures.WoodTexture, AForge.Imaging.Textures.TextileTexture, AForge.Imaging.Textures.CloudsTexture, and AForge.Imaging.Textures.LabyrinthTexture.
Referenced by TexturesDemo.MainForm.regenerateButton_Click().
The documentation for this interface was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Textures/ITextureGenerator.cs