Doc: IGLib EXTENDED: alglib.kmeans Class Reference
alglib.kmeans Class Reference
Static Public Member Functions
static void kmeansgenerate (double[,] xy, int npoints, int nvars, int k, int restarts, ref int info, ref double[,] c, ref int[] xyc)
Static Private Member Functions
static bool selectcenterpp (double[,] xy, int npoints, int nvars, ref double[,] centers, bool[] busycenters, int ccnt, ref double[] d2, ref double[] p, ref double[] tmp)
Member Function Documentation
kmeansgenerate()
static void alglib.kmeans.kmeansgenerate (double xy[,], int npoints, int nvars, int k, int restarts, ref int info, ref double c[,], ref int[] xyc) inline static
References alglib.blas.copyandtranspose(), alglib.blas.copymatrix(), alglib.math.maxrealnumber, alglib.math.randominteger(), and alglib.kmeans.selectcenterpp().
Referenced by alglib.kmeansgenerate(), alglib.testkmeansunit.restartstest(), and alglib.testkmeansunit.simpletest1().
selectcenterpp()
static bool alglib.kmeans.selectcenterpp (double xy[,], int npoints, int nvars, ref double centers[,], bool[] busycenters, int ccnt, ref double[] d2, ref double[] p, ref double[] tmp) inline static private
References alglib.math.maxrealnumber, and alglib.math.randomreal().
Referenced by alglib.kmeans.kmeansgenerate().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/dataanalysis.cs