Doc: IGLib EXTENDED: IG.Forms.VectorFunctionPlotter1d Class Reference
IG.Forms.VectorFunctionPlotter1d Class Reference
Form for training artificial neural networks.
Public Member Functions
VectorFunctionPlotter1d ()
virtual double CalculateOutput (IVector parameters, int whichOutput)
Calculates the specified output value of the vector function at the specified parameters.
void ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void PlotParametricTest ()
plots the selected outpt dependend on the selected parameter.
VectorFunctionPlotter1d ()
virtual double CalculateOutput (IVector parameters, int whichOutput)
Calculates the specified output value of the vector function at the specified parameters.
void ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void PlotParametricTest ()
plots the selected outpt dependend on the selected parameter.
VectorFunctionPlotter1d ()
virtual double CalculateOutput (IVector parameters, int whichOutput)
Calculates the specified output value of the vector function at the specified parameters.
void ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void PlotParametricTest ()
plots the selected outpt dependend on the selected parameter.
VectorFunctionPlotter1d ()
virtual double CalculateOutput (IVector parameters, int whichOutput)
Calculates the specified output value of the vector function at the specified parameters.
void ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void PlotParametricTest ()
plots the selected outpt dependend on the selected parameter.
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
int _selectedParameterId = 0
int _selectedOutputId = 0
int _numPoints = 50
Properties
IReporter Reporter [get]
Reorter used for launching info, warning and error reports.
InputOutputDataDefiniton NeuralDataDefinition [get, set]
Data about input and output quantities of the manipulated functions or response.
IScalarFunction ScalarFunction [set]
IVectorFunction Function [get, set]
int NumInputParameters [get]
Gets number of input parameters.
int NumOutputValues [get]
Gets number of output values.
IVector ParameterValues [get]
Vector of current values of input parameters as defined by the DadaGridView.
double[] MinValues [get]
Minimal values of parameters.
double[] MaxValues [get]
Maximal values of parameters.
int SelectedParameterId [get, protected set]
Sequential number of the selected parameter as specified by the user.
double SelectedParameterMin [get]
Minimal value of the selected parameter.
double SelectedParameterMax [get]
Maximal value of the selected parameter as specified by the user.
int SelectedOutputId [get, protected set]
int NumPlotPoints [get, set]
Number of plotting points.
string SelectedParameterLabelText [get]
Gets axis label text for the currently selected parameter.
string SelectedOutputLabelText [get]
Gets axis label text for the currently selected output value.
bool PlotImmediately [get, set]
If true then graph is pletted immediately when any parameter changes that affects it appearance.
bool PlotImmediatelyOnNumPointsValueChanged [get, set]
PlotterZedGraph Plotter [get]
Plotter that is used for plotting the graphs.
Private Member Functions
void btnParmTestStart_Click (object sender, EventArgs e)
Plots the parametric test.
void neuralInputParameterSelector1_SelectedParameterIdChanged (object o, IndexChangeEventArgs e)
Executes when ID of the selected input parameter changes; Plots the parametric test.
void neuralInputParameterSelector1_SelectedParameterMinChanged (object sender, IG.Forms.ValueChangeEventArgs e)
Executes when minimal value of the selected parameter changes by user interaction; Plots the parametric test.
void neuralInputParameterSelector1_SelectedParameterMaxChanged (object sender, ValueChangeEventArgs e)
Executes when maximal value of the selected parameter changes by user interaction; Plots the parametric test.
void neuralOutputValueSelector1_SelectedOutputIdChanged (object sender, IndexChangeEventArgs e)
Executes when ID of the selected output value changes; Plots the parametric test.
void btnTestFunction_Click (object sender, EventArgs e)
Generates a test fuction to be plotted.
void btnCheck_Click (object sender, EventArgs e)
Reports state of data in a fading message.
void btnIdentifyThread_Click (object sender, EventArgs e)
Report identity information of the running thread in a fading message.
void chkPlotImmediately_CheckedChanged (object sender, EventArgs e)
void numNumPlotPoints_Validated (object sender, EventArgs e)
void numNumPlotPoints_ValueChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void btnParmTestStart_Click (object sender, EventArgs e)
Plots the parametric test.
void neuralInputParameterSelector1_SelectedParameterIdChanged (int oldId, int newId)
Executes when ID of the selected input parameter changes; Plots the parametric test.
void neuralInputParameterSelector1_SelectedParameterMinChanged (double oldValue, double newValue)
Executes when minimal value of the selected parameter changes by user interaction; Plots the parametric test.
void neuralInputParameterSelector1_SelectedParameterMaxChanged (double oldValue, double newValue)
Executes when maximal value of the selected parameter changes by user interaction; Plots the parametric test.
void neuralOutputValueSelector1_SelectedOutputIdChanged (int oldId, int newId)
Executes when ID of the selected output value changes; Plots the parametric test.
void btnTestFunction_Click (object sender, EventArgs e)
Generates a test fuction to be plotted.
void btnCheck_Click (object sender, EventArgs e)
Reports state of data in a fading message.
void btnIdentifyThread_Click (object sender, EventArgs e)
Report identity information of the running thread in a fading message.
void chkPlotImmediately_CheckedChanged (object sender, EventArgs e)
void numNumPlotPoints_Validated (object sender, EventArgs e)
void numNumPlotPoints_ValueChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void btnParmTestStart_Click (object sender, EventArgs e)
Plots the parametric test.
void neuralInputParameterSelector1_SelectedParameterIdChanged (object o, IndexChangeEventArgs e)
Executes when ID of the selected input parameter changes; Plots the parametric test.
void neuralInputParameterSelector1_SelectedParameterMinChanged (object sender, IG.Forms.ValueChangeEventArgs e)
Executes when minimal value of the selected parameter changes by user interaction; Plots the parametric test.
void neuralInputParameterSelector1_SelectedParameterMaxChanged (object sender, ValueChangeEventArgs e)
Executes when maximal value of the selected parameter changes by user interaction; Plots the parametric test.
void neuralOutputValueSelector1_SelectedOutputIdChanged (object sender, IndexChangeEventArgs e)
Executes when ID of the selected output value changes; Plots the parametric test.
void btnTestFunction_Click (object sender, EventArgs e)
Generates a test fuction to be plotted.
void btnCheck_Click (object sender, EventArgs e)
Reports state of data in a fading message.
void btnIdentifyThread_Click (object sender, EventArgs e)
Report identity information of the running thread in a fading message.
void chkPlotImmediately_CheckedChanged (object sender, EventArgs e)
void numNumPlotPoints_Validated (object sender, EventArgs e)
void numNumPlotPoints_ValueChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void btnParmTestStart_Click (object sender, EventArgs e)
Plots the parametric test.
void neuralInputParameterSelector1_SelectedParameterIdChanged (object o, IndexChangeEventArgs e)
Executes when ID of the selected input parameter changes; Plots the parametric test.
void neuralInputParameterSelector1_SelectedParameterMinChanged (object sender, IG.Forms.ValueChangeEventArgs e)
Executes when minimal value of the selected parameter changes by user interaction; Plots the parametric test.
void neuralInputParameterSelector1_SelectedParameterMaxChanged (object sender, ValueChangeEventArgs e)
Executes when maximal value of the selected parameter changes by user interaction; Plots the parametric test.
void neuralOutputValueSelector1_SelectedOutputIdChanged (object sender, IndexChangeEventArgs e)
Executes when ID of the selected output value changes; Plots the parametric test.
void btnTestFunction_Click (object sender, EventArgs e)
Generates a test fuction to be plotted.
void btnCheck_Click (object sender, EventArgs e)
Reports state of data in a fading message.
void btnIdentifyThread_Click (object sender, EventArgs e)
Report identity information of the running thread in a fading message.
void chkPlotImmediately_CheckedChanged (object sender, EventArgs e)
void numNumPlotPoints_Validated (object sender, EventArgs e)
void numNumPlotPoints_ValueChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
InputOutputDataDefiniton _neuralDataDefinition
IScalarFunction _scalarFunction
IVectorFunction _function
bool _plotImmediately = false
bool _plotImmediatelyOnNumPointsValueChanged = true
PlotterZedGraph _plotter
System.ComponentModel.IContainer components = null
Required designer variable.
InputParametersControl neuralInputControl1
System.Windows.Forms.Panel pnlGraph
System.Windows.Forms.NumericUpDown numNumPlotPoints
System.Windows.Forms.Label lblNumPointsLine
ZedGraph.ZedGraphControl ParmTestFGraph
System.Windows.Forms.Button btnParamTestStart
Forms.OutputValueSelector neuralOutputValueSelector1
InputParameterSelectorMinMax neuralInputParameterSelector1
System.Windows.Forms.Button btnCheck
System.Windows.Forms.Button btnIdentifyThread
System.Windows.Forms.Button btnTestFunction
System.Windows.Forms.CheckBox chkPlotImmediately
IndicatorLight indicatorLight1
NeuralInputControl neuralInputControl1
Forms.NeuralOutputValueSelector neuralOutputValueSelector1
NeuralInputParameterSelectorMinMax neuralInputParameterSelector1
Detailed Description
Form for training artificial neural networks.
$A Igor Jul13;
Constructor & Destructor Documentation
VectorFunctionPlotter1d() [1/4]
IG.Forms.VectorFunctionPlotter1d.VectorFunctionPlotter1d () inline
References IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately, IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints, IG.Forms.VectorFunctionPlotter1d.NumPlotPoints, and IG.Forms.VectorFunctionPlotter1d.PlotImmediately.
VectorFunctionPlotter1d() [2/4]
IG.Forms.VectorFunctionPlotter1d.VectorFunctionPlotter1d () inline
References IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately, IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints, IG.Forms.VectorFunctionPlotter1d.NumPlotPoints, and IG.Forms.VectorFunctionPlotter1d.PlotImmediately.
VectorFunctionPlotter1d() [3/4]
IG.Forms.VectorFunctionPlotter1d.VectorFunctionPlotter1d () inline
References IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately, IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints, IG.Forms.VectorFunctionPlotter1d.NumPlotPoints, and IG.Forms.VectorFunctionPlotter1d.PlotImmediately.
VectorFunctionPlotter1d() [4/4]
IG.Forms.VectorFunctionPlotter1d.VectorFunctionPlotter1d () inline
References IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately, IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints, IG.Forms.VectorFunctionPlotter1d.NumPlotPoints, and IG.Forms.VectorFunctionPlotter1d.PlotImmediately.
Member Function Documentation
CalculateOutput() [1/4]
virtual double IG.Forms.VectorFunctionPlotter1d.CalculateOutput (IVector parameters, int whichOutput) inline virtual
Calculates the specified output value of the vector function at the specified parameters.
Parameters
parameters Parameter values.
whichOutput Specifies which output value (which element of the vector function) should be calculated.
Returns
The calculated vector function component.
References IG.Forms.VectorFunctionPlotter1d._scalarFunction, IG.Forms.VectorFunctionPlotter1d.Function, IG.Forms.VectorFunctionPlotter1d.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Num.IVectorFunction.Value().
Referenced by IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
ApplyPlotterSettingsDefault() [1/4]
void IG.Forms.VectorFunctionPlotter1d.ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Num.InputOutputDataDefiniton.InputElementList, IG.Gr.PlotterZedGraph.IsShowPointValues, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Forms.VectorFunctionPlotter1d.SelectedOutputLabelText, IG.Forms.VectorFunctionPlotter1d.SelectedParameterLabelText, IG.Gr.PlotterZedGraph.XAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabel.
Referenced by IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
ApplyPlotCurveSettingsDefault() [1/4]
void IG.Forms.VectorFunctionPlotter1d.ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LineWidth, IG.Gr.PlotZedgraphCurve.PointBorderColor, IG.Gr.PlotZedgraphCurve.PointFillColor, and IG.Gr.PlotZedgraphCurve.PointsVisible.
Referenced by IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
PlotParametricTest() [1/4]
void IG.Forms.VectorFunctionPlotter1d.PlotParametricTest () inline
plots the selected outpt dependend on the selected parameter.
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Forms.VectorFunctionPlotter1d.ApplyPlotCurveSettingsDefault(), IG.Forms.VectorFunctionPlotter1d.ApplyPlotterSettingsDefault(), IG.Forms.IndicatorLight.BlinkError(), IG.Forms.VectorFunctionPlotter1d.CalculateOutput(), IG.Num.VectorBase.CopyPlain(), IG.Forms.VectorFunctionPlotter1d.Function, IG.Forms.VectorFunctionPlotter1d.indicatorLight1, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Forms.VectorFunctionPlotter1d.NumInputParameters, IG.Forms.VectorFunctionPlotter1d.NumOutputValues, IG.Forms.VectorFunctionPlotter1d.NumPlotPoints, IG.Forms.VectorFunctionPlotter1d.ParameterValues, IG.Forms.VectorFunctionPlotter1d.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Forms.VectorFunctionPlotter1d.SelectedOutputId, IG.Forms.VectorFunctionPlotter1d.SelectedParameterId, IG.Forms.VectorFunctionPlotter1d.SelectedParameterMax, IG.Forms.VectorFunctionPlotter1d.SelectedParameterMin, IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetOff(), and IG.Forms.IndicatorLight.SetOk().
Referenced by IG.Forms.VectorFunctionPlotter1d.btnParmTestStart_Click(), IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMinChanged(), and IG.Forms.VectorFunctionPlotter1d.neuralOutputValueSelector1_SelectedOutputIdChanged().
btnParmTestStart_Click() [1/4]
void IG.Forms.VectorFunctionPlotter1d.btnParmTestStart_Click (object sender, EventArgs e) inline private
Plots the parametric test.
References IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
neuralInputParameterSelector1_SelectedParameterIdChanged() [1/4]
void IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterIdChanged (object o, IndexChangeEventArgs e) inline private
Executes when ID of the selected input parameter changes; Plots the parametric test.
Parameters
o Control that raised the event.
e Event arguments containing old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter1d.indicatorLight1, IG.Forms.VectorFunctionPlotter1d.PlotImmediately, and IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
neuralInputParameterSelector1_SelectedParameterMinChanged() [1/4]
void IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMinChanged (object sender, IG.Forms.ValueChangeEventArgs e) inline private
Executes when minimal value of the selected parameter changes by user interaction; Plots the parametric test.
Parameters
sender Control that generated the event.
e Event arrguments containing old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter1d.indicatorLight1, IG.Forms.VectorFunctionPlotter1d.PlotImmediately, and IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
neuralInputParameterSelector1_SelectedParameterMaxChanged() [1/4]
void IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMaxChanged (object sender, ValueChangeEventArgs e) inline private
Executes when maximal value of the selected parameter changes by user interaction; Plots the parametric test.
Parameters
sender Control that raised the event.
e Event arguments containing the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter1d.indicatorLight1, IG.Forms.VectorFunctionPlotter1d.PlotImmediately, and IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
neuralOutputValueSelector1_SelectedOutputIdChanged() [1/4]
void IG.Forms.VectorFunctionPlotter1d.neuralOutputValueSelector1_SelectedOutputIdChanged (object sender, IndexChangeEventArgs e) inline private
Executes when ID of the selected output value changes; Plots the parametric test.
Parameters
sender Control that generated the event.
e Event arguments, contain old and new value of the index.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter1d.indicatorLight1, IG.Forms.VectorFunctionPlotter1d.PlotImmediately, and IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
btnTestFunction_Click() [1/4]
void IG.Forms.VectorFunctionPlotter1d.btnTestFunction_Click (object sender, EventArgs e) inline private
Generates a test fuction to be plotted.
References IG.Num.InputOutputDataDefiniton.CreateDefault(), IG.Forms.VectorFunctionPlotter1d.Function, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Num.IVectorFunction.NumParameters, and IG.Num.IVectorFunction.NumValues.
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
btnCheck_Click() [1/4]
void IG.Forms.VectorFunctionPlotter1d.btnCheck_Click (object sender, EventArgs e) inline private
Reports state of data in a fading message.
Parameters
sender
e
References IG.Forms.FadingMessage.Launch(), IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, and IG.Num.InputOutputDataDefiniton.ToString().
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
btnIdentifyThread_Click() [1/4]
void IG.Forms.VectorFunctionPlotter1d.btnIdentifyThread_Click (object sender, EventArgs e) inline private
Report identity information of the running thread in a fading message.
Parameters
sender
e
References IG.Forms.UtilForms.IdentifyCurrentThread().
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
chkPlotImmediately_CheckedChanged() [1/4]
void IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately, and IG.Forms.VectorFunctionPlotter1d.PlotImmediately.
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
numNumPlotPoints_Validated() [1/4]
void IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints, and IG.Forms.VectorFunctionPlotter1d.NumPlotPoints.
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
numNumPlotPoints_ValueChanged() [1/4]
void IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints, IG.Forms.VectorFunctionPlotter1d.NumPlotPoints, and IG.Forms.VectorFunctionPlotter1d.PlotImmediatelyOnNumPointsValueChanged.
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
Dispose() [1/4]
override void IG.Forms.VectorFunctionPlotter1d.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.VectorFunctionPlotter1d.components.
InitializeComponent() [1/4]
void IG.Forms.VectorFunctionPlotter1d.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.VectorFunctionPlotter1d.btnCheck, IG.Forms.VectorFunctionPlotter1d.btnCheck_Click(), IG.Forms.VectorFunctionPlotter1d.btnIdentifyThread, IG.Forms.VectorFunctionPlotter1d.btnIdentifyThread_Click(), IG.Forms.VectorFunctionPlotter1d.btnParamTestStart, IG.Forms.VectorFunctionPlotter1d.btnParmTestStart_Click(), IG.Forms.VectorFunctionPlotter1d.btnTestFunction, IG.Forms.VectorFunctionPlotter1d.btnTestFunction_Click(), IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately, IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately_CheckedChanged(), IG.Forms.IndicatorLight.ColorLabel, IG.Forms.VectorFunctionPlotter1d.components, IG.Forms.OutputValueSelector.DataDefinition, IG.Forms.InputParameterSelectorMinMax.DataDefinition, IG.Forms.InputParametersControl.DataDefinition, IG.Forms.IndicatorLight.FlowDirection, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.VectorFunctionPlotter1d.indicatorLight1, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLight.LabelFont, IG.Forms.IndicatorLight.LabelText, IG.Forms.VectorFunctionPlotter1d.lblNumPointsLine, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.VectorFunctionPlotter1d.neuralInputControl1, IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1, IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter1d.neuralOutputValueSelector1, IG.Forms.VectorFunctionPlotter1d.neuralOutputValueSelector1_SelectedOutputIdChanged(), IG.Forms.OutputValueSelector.NumInputParameters, IG.Forms.InputParameterSelectorMinMax.NumInputParameters, IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints, IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_Validated(), IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_ValueChanged(), IG.Forms.OutputValueSelector.NumOutputValues, IG.Forms.InputParameterSelectorMinMax.NumOutputValues, IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.VectorFunctionPlotter1d.ParmTestFGraph, IG.Forms.VectorFunctionPlotter1d.pnlGraph, IG.Forms.OutputValueSelector.SelectedOutputIdChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterIdChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMaxChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMinChanged, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, and IG.Forms.InputParameterSelectorMinMax.TitleParameterSelection.
Referenced by IG.Forms.VectorFunctionPlotter1d.VectorFunctionPlotter1d().
CalculateOutput() [2/4]
virtual double IG.Forms.VectorFunctionPlotter1d.CalculateOutput (IVector parameters, int whichOutput) inline virtual
Calculates the specified output value of the vector function at the specified parameters.
Parameters
parameters Parameter values.
whichOutput Specifies which output value (which element of the vector function) should be calculated.
Returns
The calculated vector function component.
References IG.Forms.VectorFunctionPlotter1d._scalarFunction, IG.Forms.VectorFunctionPlotter1d.Function, IG.Forms.VectorFunctionPlotter1d.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Num.IVectorFunction.Value().
ApplyPlotterSettingsDefault() [2/4]
void IG.Forms.VectorFunctionPlotter1d.ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Num.InputOutputDataDefiniton.InputElementList, IG.Gr.PlotterZedGraph.IsShowPointValues, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Forms.VectorFunctionPlotter1d.SelectedOutputLabelText, IG.Forms.VectorFunctionPlotter1d.SelectedParameterLabelText, IG.Gr.PlotterZedGraph.XAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabel.
ApplyPlotCurveSettingsDefault() [2/4]
void IG.Forms.VectorFunctionPlotter1d.ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LineWidth, IG.Gr.PlotZedgraphCurve.PointBorderColor, IG.Gr.PlotZedgraphCurve.PointFillColor, and IG.Gr.PlotZedgraphCurve.PointsVisible.
PlotParametricTest() [2/4]
void IG.Forms.VectorFunctionPlotter1d.PlotParametricTest () inline
plots the selected outpt dependend on the selected parameter.
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Forms.VectorFunctionPlotter1d.ApplyPlotCurveSettingsDefault(), IG.Forms.VectorFunctionPlotter1d.ApplyPlotterSettingsDefault(), IG.Forms.IndicatorLight.Blink(), IG.Forms.IndicatorLight.BlinkError(), IG.Forms.VectorFunctionPlotter1d.CalculateOutput(), IG.Num.VectorBase.CopyPlain(), IG.Forms.VectorFunctionPlotter1d.Function, IG.Forms.VectorFunctionPlotter1d.indicatorLight1, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Forms.VectorFunctionPlotter1d.NumInputParameters, IG.Forms.VectorFunctionPlotter1d.NumOutputValues, IG.Forms.VectorFunctionPlotter1d.NumPlotPoints, IG.Forms.VectorFunctionPlotter1d.ParameterValues, IG.Forms.VectorFunctionPlotter1d.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Forms.VectorFunctionPlotter1d.SelectedOutputId, IG.Forms.VectorFunctionPlotter1d.SelectedParameterId, IG.Forms.VectorFunctionPlotter1d.SelectedParameterMax, IG.Forms.VectorFunctionPlotter1d.SelectedParameterMin, IG.Forms.IndicatorLight.SetError(), IG.Forms.IndicatorLight.SetOff(), and IG.Forms.IndicatorLight.SetOk().
btnParmTestStart_Click() [2/4]
void IG.Forms.VectorFunctionPlotter1d.btnParmTestStart_Click (object sender, EventArgs e) inline private
Plots the parametric test.
References IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
neuralInputParameterSelector1_SelectedParameterIdChanged() [2/4]
void IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterIdChanged (int oldId, int newId) inline private
Executes when ID of the selected input parameter changes; Plots the parametric test.
Parameters
oldId Old ID of the selected output value (after change).
newId New ID of the selected output value (after changed).
References IG.Forms.VectorFunctionPlotter1d.PlotImmediately, and IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
neuralInputParameterSelector1_SelectedParameterMinChanged() [2/4]
void IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMinChanged (double oldValue, double newValue) inline private
Executes when minimal value of the selected parameter changes by user interaction; Plots the parametric test.
Parameters
oldValue Old value.
newValue New value.
References IG.Forms.VectorFunctionPlotter1d.PlotImmediately, and IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
neuralInputParameterSelector1_SelectedParameterMaxChanged() [2/4]
void IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMaxChanged (double oldValue, double newValue) inline private
Executes when maximal value of the selected parameter changes by user interaction; Plots the parametric test.
Parameters
oldValue Old value.
newValue New value.
References IG.Forms.VectorFunctionPlotter1d.PlotImmediately, and IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
neuralOutputValueSelector1_SelectedOutputIdChanged() [2/4]
void IG.Forms.VectorFunctionPlotter1d.neuralOutputValueSelector1_SelectedOutputIdChanged (int oldId, int newId) inline private
Executes when ID of the selected output value changes; Plots the parametric test.
Parameters
oldId Old ID of the selected output value (after change).
newId New ID of the selected output value (after changed).
References IG.Forms.VectorFunctionPlotter1d.PlotImmediately, and IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
btnTestFunction_Click() [2/4]
void IG.Forms.VectorFunctionPlotter1d.btnTestFunction_Click (object sender, EventArgs e) inline private
Generates a test fuction to be plotted.
References IG.Num.InputOutputDataDefiniton.CreateDefault(), IG.Forms.VectorFunctionPlotter1d.Function, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Num.IVectorFunction.NumParameters, and IG.Num.IVectorFunction.NumValues.
btnCheck_Click() [2/4]
void IG.Forms.VectorFunctionPlotter1d.btnCheck_Click (object sender, EventArgs e) inline private
Reports state of data in a fading message.
Parameters
sender
e
References IG.Forms.FadingMessage.Launch(), IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, and IG.Num.InputOutputDataDefiniton.ToString().
btnIdentifyThread_Click() [2/4]
void IG.Forms.VectorFunctionPlotter1d.btnIdentifyThread_Click (object sender, EventArgs e) inline private
Report identity information of the running thread in a fading message.
Parameters
sender
e
References IG.Forms.UtilForms.IdentifyCurrentThread().
chkPlotImmediately_CheckedChanged() [2/4]
void IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately, and IG.Forms.VectorFunctionPlotter1d.PlotImmediately.
numNumPlotPoints_Validated() [2/4]
void IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints, and IG.Forms.VectorFunctionPlotter1d.NumPlotPoints.
numNumPlotPoints_ValueChanged() [2/4]
void IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints, IG.Forms.VectorFunctionPlotter1d.NumPlotPoints, and IG.Forms.VectorFunctionPlotter1d.PlotImmediatelyOnNumPointsValueChanged.
Dispose() [2/4]
override void IG.Forms.VectorFunctionPlotter1d.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.VectorFunctionPlotter1d.components.
InitializeComponent() [2/4]
void IG.Forms.VectorFunctionPlotter1d.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.VectorFunctionPlotter1d.btnCheck, IG.Forms.VectorFunctionPlotter1d.btnCheck_Click(), IG.Forms.VectorFunctionPlotter1d.btnIdentifyThread, IG.Forms.VectorFunctionPlotter1d.btnIdentifyThread_Click(), IG.Forms.VectorFunctionPlotter1d.btnParamTestStart, IG.Forms.VectorFunctionPlotter1d.btnParmTestStart_Click(), IG.Forms.VectorFunctionPlotter1d.btnTestFunction, IG.Forms.VectorFunctionPlotter1d.btnTestFunction_Click(), IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately, IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately_CheckedChanged(), IG.Forms.IndicatorLight.ColorLabel, IG.Forms.VectorFunctionPlotter1d.components, IG.Forms.IndicatorLight.FlowDirection, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.VectorFunctionPlotter1d.indicatorLight1, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLight.LabelFont, IG.Forms.IndicatorLight.LabelText, IG.Forms.VectorFunctionPlotter1d.lblNumPointsLine, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.VectorFunctionPlotter1d.neuralInputControl1, IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1, IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter1d.neuralOutputValueSelector1, IG.Forms.VectorFunctionPlotter1d.neuralOutputValueSelector1_SelectedOutputIdChanged(), IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints, IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_Validated(), IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_ValueChanged(), IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.VectorFunctionPlotter1d.ParmTestFGraph, IG.Forms.VectorFunctionPlotter1d.pnlGraph, IG.Forms.OutputValueSelector.SelectedOutputIdChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterIdChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMaxChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMinChanged, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, and IG.Forms.InputParameterSelectorMinMax.TitleParameterSelection.
CalculateOutput() [3/4]
virtual double IG.Forms.VectorFunctionPlotter1d.CalculateOutput (IVector parameters, int whichOutput) inline virtual
Calculates the specified output value of the vector function at the specified parameters.
Parameters
parameters Parameter values.
whichOutput Specifies which output value (which element of the vector function) should be calculated.
Returns
The calculated vector function component.
References IG.Forms.VectorFunctionPlotter1d._scalarFunction, IG.Forms.VectorFunctionPlotter1d.Function, IG.Forms.VectorFunctionPlotter1d.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Num.IVectorFunction.Value().
ApplyPlotterSettingsDefault() [3/4]
void IG.Forms.VectorFunctionPlotter1d.ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Num.InputOutputDataDefiniton.InputElementList, IG.Gr.PlotterZedGraph.IsShowPointValues, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Forms.VectorFunctionPlotter1d.SelectedOutputLabelText, IG.Forms.VectorFunctionPlotter1d.SelectedParameterLabelText, IG.Gr.PlotterZedGraph.XAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabel.
ApplyPlotCurveSettingsDefault() [3/4]
void IG.Forms.VectorFunctionPlotter1d.ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LineWidth, IG.Gr.PlotZedgraphCurve.PointBorderColor, IG.Gr.PlotZedgraphCurve.PointFillColor, and IG.Gr.PlotZedgraphCurve.PointsVisible.
PlotParametricTest() [3/4]
void IG.Forms.VectorFunctionPlotter1d.PlotParametricTest () inline
plots the selected outpt dependend on the selected parameter.
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Forms.VectorFunctionPlotter1d.ApplyPlotCurveSettingsDefault(), IG.Forms.VectorFunctionPlotter1d.ApplyPlotterSettingsDefault(), IG.Forms.IndicatorLight.BlinkError(), IG.Forms.VectorFunctionPlotter1d.CalculateOutput(), IG.Num.VectorBase.CopyPlain(), IG.Forms.VectorFunctionPlotter1d.Function, IG.Forms.VectorFunctionPlotter1d.indicatorLight1, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Forms.VectorFunctionPlotter1d.NumInputParameters, IG.Forms.VectorFunctionPlotter1d.NumOutputValues, IG.Forms.VectorFunctionPlotter1d.NumPlotPoints, IG.Forms.VectorFunctionPlotter1d.ParameterValues, IG.Forms.VectorFunctionPlotter1d.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Forms.VectorFunctionPlotter1d.SelectedOutputId, IG.Forms.VectorFunctionPlotter1d.SelectedParameterId, IG.Forms.VectorFunctionPlotter1d.SelectedParameterMax, IG.Forms.VectorFunctionPlotter1d.SelectedParameterMin, IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetOff(), and IG.Forms.IndicatorLight.SetOk().
btnParmTestStart_Click() [3/4]
void IG.Forms.VectorFunctionPlotter1d.btnParmTestStart_Click (object sender, EventArgs e) inline private
Plots the parametric test.
References IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
neuralInputParameterSelector1_SelectedParameterIdChanged() [3/4]
void IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterIdChanged (object o, IndexChangeEventArgs e) inline private
Executes when ID of the selected input parameter changes; Plots the parametric test.
Parameters
o Control that raised the event.
e Event arguments containing old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter1d.indicatorLight1, IG.Forms.VectorFunctionPlotter1d.PlotImmediately, and IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
neuralInputParameterSelector1_SelectedParameterMinChanged() [3/4]
void IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMinChanged (object sender, IG.Forms.ValueChangeEventArgs e) inline private
Executes when minimal value of the selected parameter changes by user interaction; Plots the parametric test.
Parameters
sender Control that generated the event.
e Event arrguments containing old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter1d.indicatorLight1, IG.Forms.VectorFunctionPlotter1d.PlotImmediately, and IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
neuralInputParameterSelector1_SelectedParameterMaxChanged() [3/4]
void IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMaxChanged (object sender, ValueChangeEventArgs e) inline private
Executes when maximal value of the selected parameter changes by user interaction; Plots the parametric test.
Parameters
sender Control that raised the event.
e Event arguments containing the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter1d.indicatorLight1, IG.Forms.VectorFunctionPlotter1d.PlotImmediately, and IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
neuralOutputValueSelector1_SelectedOutputIdChanged() [3/4]
void IG.Forms.VectorFunctionPlotter1d.neuralOutputValueSelector1_SelectedOutputIdChanged (object sender, IndexChangeEventArgs e) inline private
Executes when ID of the selected output value changes; Plots the parametric test.
Parameters
sender Control that generated the event.
e Event arguments, contain old and new value of the index.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter1d.indicatorLight1, IG.Forms.VectorFunctionPlotter1d.PlotImmediately, and IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
btnTestFunction_Click() [3/4]
void IG.Forms.VectorFunctionPlotter1d.btnTestFunction_Click (object sender, EventArgs e) inline private
Generates a test fuction to be plotted.
References IG.Num.InputOutputDataDefiniton.CreateDefault(), IG.Forms.VectorFunctionPlotter1d.Function, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Num.IVectorFunction.NumParameters, and IG.Num.IVectorFunction.NumValues.
btnCheck_Click() [3/4]
void IG.Forms.VectorFunctionPlotter1d.btnCheck_Click (object sender, EventArgs e) inline private
Reports state of data in a fading message.
Parameters
sender
e
References IG.Forms.FadingMessage.Launch(), IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, and IG.Num.InputOutputDataDefiniton.ToString().
btnIdentifyThread_Click() [3/4]
void IG.Forms.VectorFunctionPlotter1d.btnIdentifyThread_Click (object sender, EventArgs e) inline private
Report identity information of the running thread in a fading message.
Parameters
sender
e
References IG.Forms.UtilForms.IdentifyCurrentThread().
chkPlotImmediately_CheckedChanged() [3/4]
void IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately, and IG.Forms.VectorFunctionPlotter1d.PlotImmediately.
numNumPlotPoints_Validated() [3/4]
void IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints, and IG.Forms.VectorFunctionPlotter1d.NumPlotPoints.
numNumPlotPoints_ValueChanged() [3/4]
void IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints, IG.Forms.VectorFunctionPlotter1d.NumPlotPoints, and IG.Forms.VectorFunctionPlotter1d.PlotImmediatelyOnNumPointsValueChanged.
Dispose() [3/4]
override void IG.Forms.VectorFunctionPlotter1d.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.VectorFunctionPlotter1d.components.
InitializeComponent() [3/4]
void IG.Forms.VectorFunctionPlotter1d.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.VectorFunctionPlotter1d.btnCheck, IG.Forms.VectorFunctionPlotter1d.btnCheck_Click(), IG.Forms.VectorFunctionPlotter1d.btnIdentifyThread, IG.Forms.VectorFunctionPlotter1d.btnIdentifyThread_Click(), IG.Forms.VectorFunctionPlotter1d.btnParamTestStart, IG.Forms.VectorFunctionPlotter1d.btnParmTestStart_Click(), IG.Forms.VectorFunctionPlotter1d.btnTestFunction, IG.Forms.VectorFunctionPlotter1d.btnTestFunction_Click(), IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately, IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately_CheckedChanged(), IG.Forms.IndicatorLight.ColorLabel, IG.Forms.VectorFunctionPlotter1d.components, IG.Forms.OutputValueSelector.DataDefinition, IG.Forms.InputParameterSelectorMinMax.DataDefinition, IG.Forms.InputParametersControl.DataDefinition, IG.Forms.IndicatorLight.FlowDirection, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.VectorFunctionPlotter1d.indicatorLight1, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLight.LabelFont, IG.Forms.IndicatorLight.LabelText, IG.Forms.VectorFunctionPlotter1d.lblNumPointsLine, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.VectorFunctionPlotter1d.neuralInputControl1, IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1, IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter1d.neuralOutputValueSelector1, IG.Forms.VectorFunctionPlotter1d.neuralOutputValueSelector1_SelectedOutputIdChanged(), IG.Forms.OutputValueSelector.NumInputParameters, IG.Forms.InputParameterSelectorMinMax.NumInputParameters, IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints, IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_Validated(), IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_ValueChanged(), IG.Forms.OutputValueSelector.NumOutputValues, IG.Forms.InputParameterSelectorMinMax.NumOutputValues, IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.VectorFunctionPlotter1d.ParmTestFGraph, IG.Forms.VectorFunctionPlotter1d.pnlGraph, IG.Forms.OutputValueSelector.SelectedOutputIdChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterIdChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMaxChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMinChanged, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, and IG.Forms.InputParameterSelectorMinMax.TitleParameterSelection.
CalculateOutput() [4/4]
virtual double IG.Forms.VectorFunctionPlotter1d.CalculateOutput (IVector parameters, int whichOutput) inline virtual
Calculates the specified output value of the vector function at the specified parameters.
Parameters
parameters Parameter values.
whichOutput Specifies which output value (which element of the vector function) should be calculated.
Returns
The calculated vector function component.
References IG.Forms.VectorFunctionPlotter1d._scalarFunction, IG.Forms.VectorFunctionPlotter1d.Function, IG.Forms.VectorFunctionPlotter1d.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Num.IVectorFunction.Value().
ApplyPlotterSettingsDefault() [4/4]
void IG.Forms.VectorFunctionPlotter1d.ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Num.InputOutputDataDefiniton.InputElementList, IG.Gr.PlotterZedGraph.IsShowPointValues, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Forms.VectorFunctionPlotter1d.SelectedOutputLabelText, IG.Forms.VectorFunctionPlotter1d.SelectedParameterLabelText, IG.Gr.PlotterZedGraph.XAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabel.
ApplyPlotCurveSettingsDefault() [4/4]
void IG.Forms.VectorFunctionPlotter1d.ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LineWidth, IG.Gr.PlotZedgraphCurve.PointBorderColor, IG.Gr.PlotZedgraphCurve.PointFillColor, and IG.Gr.PlotZedgraphCurve.PointsVisible.
PlotParametricTest() [4/4]
void IG.Forms.VectorFunctionPlotter1d.PlotParametricTest () inline
plots the selected outpt dependend on the selected parameter.
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Forms.VectorFunctionPlotter1d.ApplyPlotCurveSettingsDefault(), IG.Forms.VectorFunctionPlotter1d.ApplyPlotterSettingsDefault(), IG.Forms.IndicatorLight.BlinkError(), IG.Forms.VectorFunctionPlotter1d.CalculateOutput(), IG.Num.VectorBase.CopyPlain(), IG.Forms.VectorFunctionPlotter1d.Function, IG.Forms.VectorFunctionPlotter1d.indicatorLight1, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Forms.VectorFunctionPlotter1d.NumInputParameters, IG.Forms.VectorFunctionPlotter1d.NumOutputValues, IG.Forms.VectorFunctionPlotter1d.NumPlotPoints, IG.Forms.VectorFunctionPlotter1d.ParameterValues, IG.Forms.VectorFunctionPlotter1d.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Forms.VectorFunctionPlotter1d.SelectedOutputId, IG.Forms.VectorFunctionPlotter1d.SelectedParameterId, IG.Forms.VectorFunctionPlotter1d.SelectedParameterMax, IG.Forms.VectorFunctionPlotter1d.SelectedParameterMin, IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetOff(), and IG.Forms.IndicatorLight.SetOk().
btnParmTestStart_Click() [4/4]
void IG.Forms.VectorFunctionPlotter1d.btnParmTestStart_Click (object sender, EventArgs e) inline private
Plots the parametric test.
References IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
neuralInputParameterSelector1_SelectedParameterIdChanged() [4/4]
void IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterIdChanged (object o, IndexChangeEventArgs e) inline private
Executes when ID of the selected input parameter changes; Plots the parametric test.
Parameters
o Control that raised the event.
e Event arguments containing old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter1d.indicatorLight1, IG.Forms.VectorFunctionPlotter1d.PlotImmediately, and IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
neuralInputParameterSelector1_SelectedParameterMinChanged() [4/4]
void IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMinChanged (object sender, IG.Forms.ValueChangeEventArgs e) inline private
Executes when minimal value of the selected parameter changes by user interaction; Plots the parametric test.
Parameters
sender Control that generated the event.
e Event arrguments containing old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter1d.indicatorLight1, IG.Forms.VectorFunctionPlotter1d.PlotImmediately, and IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
neuralInputParameterSelector1_SelectedParameterMaxChanged() [4/4]
void IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMaxChanged (object sender, ValueChangeEventArgs e) inline private
Executes when maximal value of the selected parameter changes by user interaction; Plots the parametric test.
Parameters
sender Control that raised the event.
e Event arguments containing the old and new value.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter1d.indicatorLight1, IG.Forms.VectorFunctionPlotter1d.PlotImmediately, and IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
neuralOutputValueSelector1_SelectedOutputIdChanged() [4/4]
void IG.Forms.VectorFunctionPlotter1d.neuralOutputValueSelector1_SelectedOutputIdChanged (object sender, IndexChangeEventArgs e) inline private
Executes when ID of the selected output value changes; Plots the parametric test.
Parameters
sender Control that generated the event.
e Event arguments, contain old and new value of the index.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.VectorFunctionPlotter1d.indicatorLight1, IG.Forms.VectorFunctionPlotter1d.PlotImmediately, and IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
btnTestFunction_Click() [4/4]
void IG.Forms.VectorFunctionPlotter1d.btnTestFunction_Click (object sender, EventArgs e) inline private
Generates a test fuction to be plotted.
References IG.Num.InputOutputDataDefiniton.CreateDefault(), IG.Forms.VectorFunctionPlotter1d.Function, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Num.IVectorFunction.NumParameters, and IG.Num.IVectorFunction.NumValues.
btnCheck_Click() [4/4]
void IG.Forms.VectorFunctionPlotter1d.btnCheck_Click (object sender, EventArgs e) inline private
Reports state of data in a fading message.
Parameters
sender
e
References IG.Forms.FadingMessage.Launch(), IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, and IG.Num.InputOutputDataDefiniton.ToString().
btnIdentifyThread_Click() [4/4]
void IG.Forms.VectorFunctionPlotter1d.btnIdentifyThread_Click (object sender, EventArgs e) inline private
Report identity information of the running thread in a fading message.
Parameters
sender
e
References IG.Forms.UtilForms.IdentifyCurrentThread().
chkPlotImmediately_CheckedChanged() [4/4]
void IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately, and IG.Forms.VectorFunctionPlotter1d.PlotImmediately.
numNumPlotPoints_Validated() [4/4]
void IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints, and IG.Forms.VectorFunctionPlotter1d.NumPlotPoints.
numNumPlotPoints_ValueChanged() [4/4]
void IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints, IG.Forms.VectorFunctionPlotter1d.NumPlotPoints, and IG.Forms.VectorFunctionPlotter1d.PlotImmediatelyOnNumPointsValueChanged.
Dispose() [4/4]
override void IG.Forms.VectorFunctionPlotter1d.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.VectorFunctionPlotter1d.components.
InitializeComponent() [4/4]
void IG.Forms.VectorFunctionPlotter1d.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.VectorFunctionPlotter1d.btnCheck, IG.Forms.VectorFunctionPlotter1d.btnCheck_Click(), IG.Forms.VectorFunctionPlotter1d.btnIdentifyThread, IG.Forms.VectorFunctionPlotter1d.btnIdentifyThread_Click(), IG.Forms.VectorFunctionPlotter1d.btnParamTestStart, IG.Forms.VectorFunctionPlotter1d.btnParmTestStart_Click(), IG.Forms.VectorFunctionPlotter1d.btnTestFunction, IG.Forms.VectorFunctionPlotter1d.btnTestFunction_Click(), IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately, IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately_CheckedChanged(), IG.Forms.IndicatorLight.ColorLabel, IG.Forms.VectorFunctionPlotter1d.components, IG.Forms.OutputValueSelector.DataDefinition, IG.Forms.InputParameterSelectorMinMax.DataDefinition, IG.Forms.InputParametersControl.DataDefinition, IG.Forms.IndicatorLight.FlowDirection, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.VectorFunctionPlotter1d.indicatorLight1, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLight.LabelFont, IG.Forms.IndicatorLight.LabelText, IG.Forms.VectorFunctionPlotter1d.lblNumPointsLine, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.VectorFunctionPlotter1d.neuralInputControl1, IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1, IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter1d.neuralOutputValueSelector1, IG.Forms.VectorFunctionPlotter1d.neuralOutputValueSelector1_SelectedOutputIdChanged(), IG.Forms.OutputValueSelector.NumInputParameters, IG.Forms.InputParameterSelectorMinMax.NumInputParameters, IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints, IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_Validated(), IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_ValueChanged(), IG.Forms.OutputValueSelector.NumOutputValues, IG.Forms.InputParameterSelectorMinMax.NumOutputValues, IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.VectorFunctionPlotter1d.ParmTestFGraph, IG.Forms.VectorFunctionPlotter1d.pnlGraph, IG.Forms.OutputValueSelector.SelectedOutputIdChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterIdChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMaxChanged, IG.Forms.InputParameterSelectorMinMax.SelectedParameterMinChanged, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, and IG.Forms.InputParameterSelectorMinMax.TitleParameterSelection.
Member Data Documentation
_neuralDataDefinition
InputOutputDataDefiniton IG.Forms.VectorFunctionPlotter1d._neuralDataDefinition private
_scalarFunction
IScalarFunction IG.Forms.VectorFunctionPlotter1d._scalarFunction private
Referenced by IG.Forms.VectorFunctionPlotter1d.CalculateOutput().
_function
IVectorFunction IG.Forms.VectorFunctionPlotter1d._function private
_selectedParameterId
int IG.Forms.VectorFunctionPlotter1d._selectedParameterId = 0 protected
_selectedOutputId
int IG.Forms.VectorFunctionPlotter1d._selectedOutputId = 0 protected
_numPoints
int IG.Forms.VectorFunctionPlotter1d._numPoints = 50 protected
_plotImmediately
bool IG.Forms.VectorFunctionPlotter1d._plotImmediately = false private
_plotImmediatelyOnNumPointsValueChanged
bool IG.Forms.VectorFunctionPlotter1d._plotImmediatelyOnNumPointsValueChanged = true private
_plotter
PlotterZedGraph IG.Forms.VectorFunctionPlotter1d._plotter private
components
System ComponentModel IContainer IG.Forms.VectorFunctionPlotter1d.components = null private
Required designer variable.
Referenced by IG.Forms.VectorFunctionPlotter1d.Dispose(), and IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
neuralInputControl1 [1/2]
InputParametersControl IG.Forms.VectorFunctionPlotter1d.neuralInputControl1 private
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
pnlGraph
System Windows Forms Panel IG.Forms.VectorFunctionPlotter1d.pnlGraph private
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
numNumPlotPoints
System Windows Forms NumericUpDown IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints private
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_Validated(), IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_ValueChanged(), and IG.Forms.VectorFunctionPlotter1d.VectorFunctionPlotter1d().
lblNumPointsLine
System Windows Forms Label IG.Forms.VectorFunctionPlotter1d.lblNumPointsLine private
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
ParmTestFGraph
ZedGraph ZedGraphControl IG.Forms.VectorFunctionPlotter1d.ParmTestFGraph private
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
btnParamTestStart
System Windows Forms Button IG.Forms.VectorFunctionPlotter1d.btnParamTestStart private
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
neuralOutputValueSelector1 [1/2]
Forms OutputValueSelector IG.Forms.VectorFunctionPlotter1d.neuralOutputValueSelector1 private
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
neuralInputParameterSelector1 [1/2]
InputParameterSelectorMinMax IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1 private
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
btnCheck
System Windows Forms Button IG.Forms.VectorFunctionPlotter1d.btnCheck private
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
btnIdentifyThread
System Windows Forms Button IG.Forms.VectorFunctionPlotter1d.btnIdentifyThread private
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
btnTestFunction
System Windows Forms Button IG.Forms.VectorFunctionPlotter1d.btnTestFunction private
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent().
chkPlotImmediately
System Windows Forms CheckBox IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately private
Referenced by IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately_CheckedChanged(), IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), and IG.Forms.VectorFunctionPlotter1d.VectorFunctionPlotter1d().
indicatorLight1
IndicatorLight IG.Forms.VectorFunctionPlotter1d.indicatorLight1 private
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter1d.neuralOutputValueSelector1_SelectedOutputIdChanged(), and IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
neuralInputControl1 [2/2]
NeuralInputControl IG.Forms.VectorFunctionPlotter1d.neuralInputControl1 private
neuralOutputValueSelector1 [2/2]
Forms.NeuralOutputValueSelector IG.Forms.VectorFunctionPlotter1d.neuralOutputValueSelector1 private
neuralInputParameterSelector1 [2/2]
NeuralInputParameterSelectorMinMax IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1 private
Property Documentation
Reporter
IReporter IG.Forms.VectorFunctionPlotter1d.Reporter get private
Reorter used for launching info, warning and error reports.
Referenced by IG.Forms.VectorFunctionPlotter1d.CalculateOutput(), and IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
NeuralDataDefinition
InputOutputDataDefiniton IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition get set
Data about input and output quantities of the manipulated functions or response.
Referenced by IG.Forms.VectorFunctionPlotter1d.ApplyPlotterSettingsDefault(), IG.Forms.VectorFunctionPlotter1d.btnCheck_Click(), IG.Forms.VectorFunctionScriptControl.btnPlot1d_Click(), IG.Forms.ScalarFunctionScriptControl.btnPlot1d_Click(), IG.Forms.VectorFunctionPlotter1d.btnTestFunction_Click(), IG.Forms.VectorFunctionPlotter1dForm.InitializeComponent(), and IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
ScalarFunction
IScalarFunction IG.Forms.VectorFunctionPlotter1d.ScalarFunction set
Referenced by IG.Forms.ScalarFunctionScriptControl.btnPlot1d_Click().
Function
IVectorFunction IG.Forms.VectorFunctionPlotter1d.Function get set
Referenced by IG.Forms.VectorFunctionScriptControl.btnPlot1d_Click(), IG.Forms.VectorFunctionPlotter1d.btnTestFunction_Click(), IG.Forms.VectorFunctionPlotter1d.CalculateOutput(), IG.Forms.VectorFunctionPlotter1dForm.InitializeComponent(), and IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
NumInputParameters
int IG.Forms.VectorFunctionPlotter1d.NumInputParameters get
Gets number of input parameters.
Referenced by IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
NumOutputValues
int IG.Forms.VectorFunctionPlotter1d.NumOutputValues get
Gets number of output values.
Referenced by IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
ParameterValues
IVector IG.Forms.VectorFunctionPlotter1d.ParameterValues get
Vector of current values of input parameters as defined by the DadaGridView.
Referenced by IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
MinValues
double [] IG.Forms.VectorFunctionPlotter1d.MinValues get
Minimal values of parameters.
MaxValues
double [] IG.Forms.VectorFunctionPlotter1d.MaxValues get
Maximal values of parameters.
SelectedParameterId
int IG.Forms.VectorFunctionPlotter1d.SelectedParameterId get protected set
Sequential number of the selected parameter as specified by the user.
Referenced by IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
SelectedParameterMin
double IG.Forms.VectorFunctionPlotter1d.SelectedParameterMin get
Minimal value of the selected parameter.
Referenced by IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
SelectedParameterMax
double IG.Forms.VectorFunctionPlotter1d.SelectedParameterMax get
Maximal value of the selected parameter as specified by the user.
Referenced by IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
SelectedOutputId
int IG.Forms.VectorFunctionPlotter1d.SelectedOutputId get protected set
Referenced by IG.Forms.VectorFunctionPlotter1d.PlotParametricTest().
NumPlotPoints
int IG.Forms.VectorFunctionPlotter1d.NumPlotPoints get set
Number of plotting points.
Referenced by IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_Validated(), IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_ValueChanged(), IG.Forms.VectorFunctionPlotter1d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter1d.VectorFunctionPlotter1d().
SelectedParameterLabelText
string IG.Forms.VectorFunctionPlotter1d.SelectedParameterLabelText get
Gets axis label text for the currently selected parameter.
Referenced by IG.Forms.VectorFunctionPlotter1d.ApplyPlotterSettingsDefault().
SelectedOutputLabelText
string IG.Forms.VectorFunctionPlotter1d.SelectedOutputLabelText get
Gets axis label text for the currently selected output value.
Referenced by IG.Forms.VectorFunctionPlotter1d.ApplyPlotterSettingsDefault().
PlotImmediately
bool IG.Forms.VectorFunctionPlotter1d.PlotImmediately get set
If true then graph is pletted immediately when any parameter changes that affects it appearance.
Referenced by IG.Forms.VectorFunctionPlotter1d.chkPlotImmediately_CheckedChanged(), IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter1d.neuralOutputValueSelector1_SelectedOutputIdChanged(), and IG.Forms.VectorFunctionPlotter1d.VectorFunctionPlotter1d().
PlotImmediatelyOnNumPointsValueChanged
bool IG.Forms.VectorFunctionPlotter1d.PlotImmediatelyOnNumPointsValueChanged get set
Referenced by IG.Forms.VectorFunctionPlotter1d.numNumPlotPoints_ValueChanged().
Plotter
PlotterZedGraph IG.Forms.VectorFunctionPlotter1d.Plotter get
Plotter that is used for plotting the graphs.
The documentation for this class was generated from the following files:
iglib/extensions/iglibext/Forms/Numeric/FromNeural/VectorFunctionPlotter1d.cs
iglib/extensions/iglibext/Forms/Numeric/FromNeural/VectorFunctionPlotter1d.Designer.cs