Doc: IGLib EXTENDED: NUnit.Framework.Internal.RandomizerTests Class Reference
NUnit.Framework.Internal.RandomizerTests Class Reference
Classes
class Repeatability
Public Member Functions
void CreateRandomizer ()
void RandomIntsAreUnique ()
void RandomIntsInRangeAreUnique ()
void RandomUInt ()
void RandomUIntWithMaximum ()
void RandomUIntInRange ()
void RandomUintInRange_Reversed ()
void RandomUintInRange_MinEqualsMax ()
void RandomUIntsAreUnique ()
void RandomUIntsInRangeAreUnique ()
void RandomShort ()
void RandomShortWithMaximum ()
void RandomShortInRange ()
void RandomShortInRange_Reversed ()
void RandomShortInRange_MinEqualsMax ()
void RandomShortsAreUnique ()
void RandomShortsInRangeAreUnique ()
void RandomUShort ()
void RandomUShortWithMaximum ()
void RandomUShortInRange ()
void RandomUShortInRange_Reversed ()
void RandomUShortInRange_MinEqualsMax ()
void RandomUShortsAreUnique ()
void RandomUShortsInRangeAreUnique ()
void RandomLong ()
void RandomLongWithMaximum ()
void RandomLongInRange ()
void RandomLongInRange_Reversed ()
void RandomLongInRange_MinEqualsMax ()
void RandomLongsAreUnique ()
void RandomLongsInRangeAreUnique ()
void RandomULong ()
void RandomULongWithMaximum ()
void RandomULongInRange ()
void RandomULongInRange_Reversed ()
void RandomULongInRange_MinEqualsMax ()
void RandomULongsAreUnique ()
void RandomULongsInRangeAreUnique ()
void RandomByte ()
void RandomByteWithMaximum ()
void RandomByteInRange ()
void RandomByteInRange_Reversed ()
void RandomByteInRange_MinEqualsMax ()
void RandomBytesAreUnique ()
void RandomBytesInRangeAreUnique ()
void RandomSByte ()
void RandomSByteWithMaximum ()
void RandomSByteInRange ()
void RandomSByteInRange_Reversed ()
void RandomSbyteInRange_MinEqualsMax ()
void RandomSBytesAreUnique ()
void RandomSBytesInRangeAreUnique ()
void RandomBool ()
void RandomBoolWithProbability ()
void RandomBoolWithProbabilityOutOfRange ()
void RandomBoolWithProbabilityZeroIsAlwaysFalse ()
void RandomBoolWithProbabilityOneIsAlwaysTrue ()
void RandomDouble ()
void RandomDoubleWithMaximum ()
void RandomDoubleInRange ()
void RandomDoubleInRange_Reversed ()
void RandomDoubleInRange_MinEqualsMax ()
void RandomDoublesAreUnique ()
void RandomDoublesInRangeAreUnique ()
void RandomFloat ()
void RandomFloatWithMaximum ()
void RandomFloatInRange ()
void RandomFloatInRange_Reversed ()
void RandomFloatInRange_MinEqualsMax ()
void RandomFloatsAreUnique ()
void RandomFloatsInRangeAreUnique ()
float[] GetFloats (int count)
Return an array of random floats between 0.0 and 1.0.
float[] GetFloats (float min, float max, int count)
Return an array of random floats with values in a specified range.
void RandomDecimal ()
void RandomDecimalWithMaximum ()
void RandomDecimalInRange ()
void RandomDecimalInRange_Reversed ()
void RandomDecimalInRange_MinEqualsMax ()
void RandomDecimalRangeTooGreat ()
void RandomDecimalsAreUnique ()
void RandomDecimalsInRangeAreUnique ()
void RandomStringsAreUnique ()
void RandomStringsAreUnique (int outputLength, string allowedChars)
void RandomEnum ()
void RandomEnum_Generic ()
Static Private Member Functions
static void CheckScaleIsZero (decimal d)
Private Attributes
Randomizer _randomizer
Member Function Documentation
CreateRandomizer()
void NUnit.Framework.Internal.RandomizerTests.CreateRandomizer () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer.
RandomIntsAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomIntsAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer.
RandomIntsInRangeAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomIntsInRangeAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer.
RandomUInt()
void NUnit.Framework.Internal.RandomizerTests.RandomUInt () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Is.InRange(), NUnit.Framework.Internal.Randomizer.NextUInt(), and NUnit.Framework.Assert.That().
RandomUIntWithMaximum()
void NUnit.Framework.Internal.RandomizerTests.RandomUIntWithMaximum () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.Randomizer.NextUInt(), and NUnit.Framework.Assert.That().
RandomUIntInRange()
void NUnit.Framework.Internal.RandomizerTests.RandomUIntInRange () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.Randomizer.NextUInt(), and NUnit.Framework.Assert.That().
RandomUintInRange_Reversed()
void NUnit.Framework.Internal.RandomizerTests.RandomUintInRange_Reversed () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Throws.InstanceOf(), NUnit.Framework.Internal.Randomizer.NextUInt(), and NUnit.Framework.Assert.That().
RandomUintInRange_MinEqualsMax()
void NUnit.Framework.Internal.RandomizerTests.RandomUintInRange_MinEqualsMax () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Randomizer.NextUInt(), and NUnit.Framework.Assert.That().
RandomUIntsAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomUIntsAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextUInt().
RandomUIntsInRangeAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomUIntsInRangeAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextUInt().
RandomShort()
void NUnit.Framework.Internal.RandomizerTests.RandomShort () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Is.InRange(), NUnit.Framework.Internal.Randomizer.NextShort(), and NUnit.Framework.Assert.That().
RandomShortWithMaximum()
void NUnit.Framework.Internal.RandomizerTests.RandomShortWithMaximum () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.Randomizer.NextShort(), and NUnit.Framework.Assert.That().
RandomShortInRange()
void NUnit.Framework.Internal.RandomizerTests.RandomShortInRange () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.Randomizer.NextShort(), and NUnit.Framework.Assert.That().
RandomShortInRange_Reversed()
void NUnit.Framework.Internal.RandomizerTests.RandomShortInRange_Reversed () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Throws.InstanceOf(), NUnit.Framework.Internal.Randomizer.NextShort(), and NUnit.Framework.Assert.That().
RandomShortInRange_MinEqualsMax()
void NUnit.Framework.Internal.RandomizerTests.RandomShortInRange_MinEqualsMax () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Randomizer.NextShort(), and NUnit.Framework.Assert.That().
RandomShortsAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomShortsAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextShort().
RandomShortsInRangeAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomShortsInRangeAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextShort().
RandomUShort()
void NUnit.Framework.Internal.RandomizerTests.RandomUShort () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Is.InRange(), NUnit.Framework.Internal.Randomizer.NextUShort(), and NUnit.Framework.Assert.That().
RandomUShortWithMaximum()
void NUnit.Framework.Internal.RandomizerTests.RandomUShortWithMaximum () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.Randomizer.NextUShort(), and NUnit.Framework.Assert.That().
RandomUShortInRange()
void NUnit.Framework.Internal.RandomizerTests.RandomUShortInRange () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.Randomizer.NextUShort(), and NUnit.Framework.Assert.That().
RandomUShortInRange_Reversed()
void NUnit.Framework.Internal.RandomizerTests.RandomUShortInRange_Reversed () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Throws.InstanceOf(), NUnit.Framework.Internal.Randomizer.NextUShort(), and NUnit.Framework.Assert.That().
RandomUShortInRange_MinEqualsMax()
void NUnit.Framework.Internal.RandomizerTests.RandomUShortInRange_MinEqualsMax () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Randomizer.NextUShort(), and NUnit.Framework.Assert.That().
RandomUShortsAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomUShortsAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextUShort().
RandomUShortsInRangeAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomUShortsInRangeAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextUShort().
RandomLong()
void NUnit.Framework.Internal.RandomizerTests.RandomLong () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Is.InRange(), NUnit.Framework.Internal.Randomizer.NextLong(), and NUnit.Framework.Assert.That().
RandomLongWithMaximum()
void NUnit.Framework.Internal.RandomizerTests.RandomLongWithMaximum () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.Randomizer.NextLong(), and NUnit.Framework.Assert.That().
RandomLongInRange()
void NUnit.Framework.Internal.RandomizerTests.RandomLongInRange () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.Randomizer.NextLong(), and NUnit.Framework.Assert.That().
RandomLongInRange_Reversed()
void NUnit.Framework.Internal.RandomizerTests.RandomLongInRange_Reversed () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Throws.InstanceOf(), NUnit.Framework.Internal.Randomizer.NextLong(), and NUnit.Framework.Assert.That().
RandomLongInRange_MinEqualsMax()
void NUnit.Framework.Internal.RandomizerTests.RandomLongInRange_MinEqualsMax () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Randomizer.NextLong(), and NUnit.Framework.Assert.That().
RandomLongsAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomLongsAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextLong().
RandomLongsInRangeAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomLongsInRangeAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextLong().
RandomULong()
void NUnit.Framework.Internal.RandomizerTests.RandomULong () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Is.InRange(), NUnit.Framework.Internal.Randomizer.NextULong(), and NUnit.Framework.Assert.That().
RandomULongWithMaximum()
void NUnit.Framework.Internal.RandomizerTests.RandomULongWithMaximum () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.Randomizer.NextULong(), and NUnit.Framework.Assert.That().
RandomULongInRange()
void NUnit.Framework.Internal.RandomizerTests.RandomULongInRange () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.Randomizer.NextULong(), and NUnit.Framework.Assert.That().
RandomULongInRange_Reversed()
void NUnit.Framework.Internal.RandomizerTests.RandomULongInRange_Reversed () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Throws.InstanceOf(), NUnit.Framework.Internal.Randomizer.NextULong(), and NUnit.Framework.Assert.That().
RandomULongInRange_MinEqualsMax()
void NUnit.Framework.Internal.RandomizerTests.RandomULongInRange_MinEqualsMax () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Randomizer.NextULong(), and NUnit.Framework.Assert.That().
RandomULongsAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomULongsAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextULong().
RandomULongsInRangeAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomULongsInRangeAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextULong().
RandomByte()
void NUnit.Framework.Internal.RandomizerTests.RandomByte () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Is.InRange(), NUnit.Framework.Internal.Randomizer.NextByte(), and NUnit.Framework.Assert.That().
RandomByteWithMaximum()
void NUnit.Framework.Internal.RandomizerTests.RandomByteWithMaximum () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.Randomizer.NextByte(), and NUnit.Framework.Assert.That().
RandomByteInRange()
void NUnit.Framework.Internal.RandomizerTests.RandomByteInRange () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.Randomizer.NextByte(), and NUnit.Framework.Assert.That().
RandomByteInRange_Reversed()
void NUnit.Framework.Internal.RandomizerTests.RandomByteInRange_Reversed () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Throws.InstanceOf(), NUnit.Framework.Internal.Randomizer.NextByte(), and NUnit.Framework.Assert.That().
RandomByteInRange_MinEqualsMax()
void NUnit.Framework.Internal.RandomizerTests.RandomByteInRange_MinEqualsMax () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Randomizer.NextByte(), and NUnit.Framework.Assert.That().
RandomBytesAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomBytesAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextByte().
RandomBytesInRangeAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomBytesInRangeAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextByte().
RandomSByte()
void NUnit.Framework.Internal.RandomizerTests.RandomSByte () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Is.InRange(), NUnit.Framework.Internal.Randomizer.NextSByte(), and NUnit.Framework.Assert.That().
RandomSByteWithMaximum()
void NUnit.Framework.Internal.RandomizerTests.RandomSByteWithMaximum () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.Randomizer.NextSByte(), and NUnit.Framework.Assert.That().
RandomSByteInRange()
void NUnit.Framework.Internal.RandomizerTests.RandomSByteInRange () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.Randomizer.NextSByte(), and NUnit.Framework.Assert.That().
RandomSByteInRange_Reversed()
void NUnit.Framework.Internal.RandomizerTests.RandomSByteInRange_Reversed () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Throws.InstanceOf(), NUnit.Framework.Internal.Randomizer.NextSByte(), and NUnit.Framework.Assert.That().
RandomSbyteInRange_MinEqualsMax()
void NUnit.Framework.Internal.RandomizerTests.RandomSbyteInRange_MinEqualsMax () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Randomizer.NextSByte(), and NUnit.Framework.Assert.That().
RandomSBytesAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomSBytesAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextSByte().
RandomSBytesInRangeAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomSBytesInRangeAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextSByte().
RandomBool()
void NUnit.Framework.Internal.RandomizerTests.RandomBool () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextBool().
RandomBoolWithProbability()
void NUnit.Framework.Internal.RandomizerTests.RandomBoolWithProbability () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextBool().
RandomBoolWithProbabilityOutOfRange()
void NUnit.Framework.Internal.RandomizerTests.RandomBoolWithProbabilityOutOfRange () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Throws.InstanceOf(), NUnit.Framework.Internal.Randomizer.NextBool(), and NUnit.Framework.Assert.That().
RandomBoolWithProbabilityZeroIsAlwaysFalse()
void NUnit.Framework.Internal.RandomizerTests.RandomBoolWithProbabilityZeroIsAlwaysFalse () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Assert.False(), and NUnit.Framework.Internal.Randomizer.NextBool().
RandomBoolWithProbabilityOneIsAlwaysTrue()
void NUnit.Framework.Internal.RandomizerTests.RandomBoolWithProbabilityOneIsAlwaysTrue () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.Randomizer.NextBool(), and NUnit.Framework.Assert.True().
RandomDouble()
void NUnit.Framework.Internal.RandomizerTests.RandomDouble () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Is.InRange(), NUnit.Framework.Internal.Randomizer.NextDouble(), and NUnit.Framework.Assert.That().
RandomDoubleWithMaximum()
void NUnit.Framework.Internal.RandomizerTests.RandomDoubleWithMaximum () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.Randomizer.NextDouble(), and NUnit.Framework.Assert.That().
RandomDoubleInRange()
void NUnit.Framework.Internal.RandomizerTests.RandomDoubleInRange () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.Randomizer.NextDouble(), and NUnit.Framework.Assert.That().
RandomDoubleInRange_Reversed()
void NUnit.Framework.Internal.RandomizerTests.RandomDoubleInRange_Reversed () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Throws.InstanceOf(), NUnit.Framework.Internal.Randomizer.NextDouble(), and NUnit.Framework.Assert.That().
RandomDoubleInRange_MinEqualsMax()
void NUnit.Framework.Internal.RandomizerTests.RandomDoubleInRange_MinEqualsMax () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Randomizer.NextDouble(), and NUnit.Framework.Assert.That().
RandomDoublesAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomDoublesAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextDouble().
RandomDoublesInRangeAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomDoublesInRangeAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextDouble().
RandomFloat()
void NUnit.Framework.Internal.RandomizerTests.RandomFloat () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Is.InRange(), NUnit.Framework.Internal.Randomizer.NextFloat(), and NUnit.Framework.Assert.That().
RandomFloatWithMaximum()
void NUnit.Framework.Internal.RandomizerTests.RandomFloatWithMaximum () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.Randomizer.NextFloat(), and NUnit.Framework.Assert.That().
RandomFloatInRange()
void NUnit.Framework.Internal.RandomizerTests.RandomFloatInRange () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.Randomizer.NextFloat(), and NUnit.Framework.Assert.That().
RandomFloatInRange_Reversed()
void NUnit.Framework.Internal.RandomizerTests.RandomFloatInRange_Reversed () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Throws.InstanceOf(), NUnit.Framework.Internal.Randomizer.NextFloat(), and NUnit.Framework.Assert.That().
RandomFloatInRange_MinEqualsMax()
void NUnit.Framework.Internal.RandomizerTests.RandomFloatInRange_MinEqualsMax () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Randomizer.NextFloat(), and NUnit.Framework.Assert.That().
RandomFloatsAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomFloatsAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextFloat().
RandomFloatsInRangeAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomFloatsInRangeAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextFloat().
GetFloats() [1/2]
float [] NUnit.Framework.Internal.RandomizerTests.GetFloats (int count) inline
Return an array of random floats between 0.0 and 1.0.
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextFloat().
GetFloats() [2/2]
float [] NUnit.Framework.Internal.RandomizerTests.GetFloats (float min, float max, int count) inline
Return an array of random floats with values in a specified range.
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextFloat().
RandomDecimal()
void NUnit.Framework.Internal.RandomizerTests.RandomDecimal () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.RandomizerTests.CheckScaleIsZero(), NUnit.Framework.Is.InRange(), NUnit.Framework.Internal.Randomizer.NextDecimal(), and NUnit.Framework.Assert.That().
CheckScaleIsZero()
static void NUnit.Framework.Internal.RandomizerTests.CheckScaleIsZero (decimal d) inline static private
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Internal.RandomizerTests.RandomDecimal(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalInRange(), and NUnit.Framework.Internal.RandomizerTests.RandomDecimalWithMaximum().
RandomDecimalWithMaximum()
void NUnit.Framework.Internal.RandomizerTests.RandomDecimalWithMaximum () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.RandomizerTests.CheckScaleIsZero(), NUnit.Framework.Is.InRange(), NUnit.Framework.Internal.Randomizer.NextDecimal(), and NUnit.Framework.Assert.That().
RandomDecimalInRange()
void NUnit.Framework.Internal.RandomizerTests.RandomDecimalInRange () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Internal.RandomizerTests.CheckScaleIsZero(), NUnit.Framework.Is.InRange(), NUnit.Framework.Internal.Randomizer.NextDecimal(), and NUnit.Framework.Assert.That().
RandomDecimalInRange_Reversed()
void NUnit.Framework.Internal.RandomizerTests.RandomDecimalInRange_Reversed () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Throws.InstanceOf(), NUnit.Framework.Internal.Randomizer.NextDecimal(), and NUnit.Framework.Assert.That().
RandomDecimalInRange_MinEqualsMax()
void NUnit.Framework.Internal.RandomizerTests.RandomDecimalInRange_MinEqualsMax () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Randomizer.NextDecimal(), and NUnit.Framework.Assert.That().
RandomDecimalRangeTooGreat()
void NUnit.Framework.Internal.RandomizerTests.RandomDecimalRangeTooGreat () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, NUnit.Framework.Throws.InstanceOf(), NUnit.Framework.Internal.Randomizer.NextDecimal(), and NUnit.Framework.Assert.That().
RandomDecimalsAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomDecimalsAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextDecimal().
RandomDecimalsInRangeAreUnique()
void NUnit.Framework.Internal.RandomizerTests.RandomDecimalsInRangeAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextDecimal().
RandomStringsAreUnique() [1/2]
void NUnit.Framework.Internal.RandomizerTests.RandomStringsAreUnique () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.GetString().
RandomStringsAreUnique() [2/2]
void NUnit.Framework.Internal.RandomizerTests.RandomStringsAreUnique (int outputLength, string allowedChars) inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.GetString().
RandomEnum()
void NUnit.Framework.Internal.RandomizerTests.RandomEnum () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextEnum().
RandomEnum_Generic()
void NUnit.Framework.Internal.RandomizerTests.RandomEnum_Generic () inline
References NUnit.Framework.Internal.RandomizerTests._randomizer, and NUnit.Framework.Internal.Randomizer.NextEnum().
Member Data Documentation
_randomizer
Randomizer NUnit.Framework.Internal.RandomizerTests._randomizer private
Referenced by NUnit.Framework.Internal.RandomizerTests.CreateRandomizer(), NUnit.Framework.Internal.RandomizerTests.GetFloats(), NUnit.Framework.Internal.RandomizerTests.RandomBool(), NUnit.Framework.Internal.RandomizerTests.RandomBoolWithProbability(), NUnit.Framework.Internal.RandomizerTests.RandomBoolWithProbabilityOneIsAlwaysTrue(), NUnit.Framework.Internal.RandomizerTests.RandomBoolWithProbabilityOutOfRange(), NUnit.Framework.Internal.RandomizerTests.RandomBoolWithProbabilityZeroIsAlwaysFalse(), NUnit.Framework.Internal.RandomizerTests.RandomByte(), NUnit.Framework.Internal.RandomizerTests.RandomByteInRange(), NUnit.Framework.Internal.RandomizerTests.RandomByteInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomByteInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomBytesAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomBytesInRangeAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomByteWithMaximum(), NUnit.Framework.Internal.RandomizerTests.RandomDecimal(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalInRange(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalRangeTooGreat(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalsAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalsInRangeAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomDecimalWithMaximum(), NUnit.Framework.Internal.RandomizerTests.RandomDouble(), NUnit.Framework.Internal.RandomizerTests.RandomDoubleInRange(), NUnit.Framework.Internal.RandomizerTests.RandomDoubleInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomDoubleInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomDoublesAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomDoublesInRangeAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomDoubleWithMaximum(), NUnit.Framework.Internal.RandomizerTests.RandomEnum(), NUnit.Framework.Internal.RandomizerTests.RandomEnum_Generic(), NUnit.Framework.Internal.RandomizerTests.RandomFloat(), NUnit.Framework.Internal.RandomizerTests.RandomFloatInRange(), NUnit.Framework.Internal.RandomizerTests.RandomFloatInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomFloatInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomFloatsAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomFloatsInRangeAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomFloatWithMaximum(), NUnit.Framework.Internal.RandomizerTests.RandomIntsAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomIntsInRangeAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomLong(), NUnit.Framework.Internal.RandomizerTests.RandomLongInRange(), NUnit.Framework.Internal.RandomizerTests.RandomLongInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomLongInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomLongsAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomLongsInRangeAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomLongWithMaximum(), NUnit.Framework.Internal.RandomizerTests.RandomSByte(), NUnit.Framework.Internal.RandomizerTests.RandomSByteInRange(), NUnit.Framework.Internal.RandomizerTests.RandomSbyteInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomSByteInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomSBytesAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomSBytesInRangeAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomSByteWithMaximum(), NUnit.Framework.Internal.RandomizerTests.RandomShort(), NUnit.Framework.Internal.RandomizerTests.RandomShortInRange(), NUnit.Framework.Internal.RandomizerTests.RandomShortInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomShortInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomShortsAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomShortsInRangeAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomShortWithMaximum(), NUnit.Framework.Internal.RandomizerTests.RandomStringsAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomUInt(), NUnit.Framework.Internal.RandomizerTests.RandomUIntInRange(), NUnit.Framework.Internal.RandomizerTests.RandomUintInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomUintInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomUIntsAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomUIntsInRangeAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomUIntWithMaximum(), NUnit.Framework.Internal.RandomizerTests.RandomULong(), NUnit.Framework.Internal.RandomizerTests.RandomULongInRange(), NUnit.Framework.Internal.RandomizerTests.RandomULongInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomULongInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomULongsAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomULongsInRangeAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomULongWithMaximum(), NUnit.Framework.Internal.RandomizerTests.RandomUShort(), NUnit.Framework.Internal.RandomizerTests.RandomUShortInRange(), NUnit.Framework.Internal.RandomizerTests.RandomUShortInRange_MinEqualsMax(), NUnit.Framework.Internal.RandomizerTests.RandomUShortInRange_Reversed(), NUnit.Framework.Internal.RandomizerTests.RandomUShortsAreUnique(), NUnit.Framework.Internal.RandomizerTests.RandomUShortsInRangeAreUnique(), and NUnit.Framework.Internal.RandomizerTests.RandomUShortWithMaximum().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/RandomizerTests.cs