Doc: IGLib EXTENDED: IG.Lib.DynamicWrapper Class Reference
IG.Lib.DynamicWrapper Class Reference
Dynamic object wrapper class for handling JSON serialization and deserialization of objects, addressing of object via field access and indexing notations, transversal of objects, performing operations on objects and their parts, and as base class to derive object that represent arbitrary tree structures such as DOMs or file structures.
Public Member Functions
DynamicWrapper ()
DynamicWrapper (object obj)
DynamicWrapper (DynamicWrapper otherWrapper)
virtual DynamicWrapper WrapObject (object obj)
Wraps the specified object in a wrapper of the type DynamicWrapper and returns the wrapper.
virtual DynamicWrapper CrateWrapper ()
Creates and returns a new dynamic object wrapper of the type DynamicWrapper.
virtual DynamicWrapper CreateWrapper (object wrappedObject)
Creates and returns a new dynamic object wrapper (a subtype of DynamicWrapper) of the specific type corresponding to the type of the object on which the method is called.
virtual WrapperType CreateArrayWrapper< WrapperType > ()
Creates and returns a new wrapped object of an appropriate type, which can act as array of objects.
virtual object CreateStructWrapper< WrapperType > ()
Creates and returns a new wrapped object of the appropriate type, which can act as a struct containing other objects as named fields.
virtual object CreateArrayObject ()
Creates and returns an obect of the appropriate type, which can act as array (or list) of other objects.
virtual object CreateStructObject< WrapperType > ()
Creates and returns an obect of the appropriate type, which can act struct that contains arbitrary numbe of other objects in as named fields.
virtual object UnwrapObject (DynamicWrapper wrapper)
Returns the internal object that is wrapped by the wrapper , or null if wrapper is null.
virtual object UnwrapObjectIfWrapped (object wrappedOrPlain)
If wrappedOrPlain is a wrapper of type DynamicWrapper or its subtype, this method returns the unwrapped object that it contains, otherwise it returns the wrappedOrPlain itself.
virtual WrapperType WrapObject< WrapperType > (object obj)
Wraps the specified object (obj) in to a dynamic wrapper of type WrapperType and returns the wrapped object.
virtual object GetObject ()
Returns the wrapped object.
virtual void SetObject (object obj)
Sets the wrapped object to obj .
virtual bool IsStruct ()
Returns true if the wrapped object implements IDictionary<string, object> interface, meaning that it contains fields addressable by field names, thus behaving like a struct.
virtual bool IsArray ()
Returns true if the wrapped object implements IDictionary interface, meaning that it contains fields addressable by field names, thus behaving like a struct.
virtual bool IsLeaf ()
Returns true if the currently wrapped object is a leaf object, i.e., it is neither an array object nor a struct-like object.
virtual int NumStructFields ()
Returns the number of struct fields of the currently wrapped object, or 0 if this object is not a struct-like object with field members.
virtual int NumArrayElements ()
Returns the number of array elements of the currently wrapped object, of 0 if this object is not an array-like object with indexed elements.
virtual IDictionary< String, object > GetStructElements ()
Returns a dictionary of struct elements of the currently wrapped object, or null if this object is not a struct-like object containing named fields.
virtual ICollection< string > GetStructKeys ()
Returns a collection of field names of the currently wrapped element, or null if this object is not a struct-like object containing named fields.
virtual IList< string > GetStrucKeysAsList ()
Returns a list of field names of the currently wrapped element, or null if this object is not a struct-like object containing named fields.
virtual IList< object > GetArrayElements ()
Returns a list of array elements of the currently wrapped element, or null if this object is not an array-like object containing indexed elements.
virtual object GetArrayElement (int arrayIndex)
Returns the specified array element of the currently wrapped element, or null if this object is not an array-lika object.
virtual object GetStructElemet (string fieldName)
Returns the specified field of the currently wrapped object, or null if this object is not a struct-like object containing named fields.
override bool TryGetMember (GetMemberBinder binder, out object result)
Overrides DynamicObject.TryGetMember(GetMemberBinder, out object) so that we can reference fields on this wrapper object in such a way that they directly reference fields of the wrapped object (in case that wrapped object has internal fields).
override bool TrySetMember (SetMemberBinder binder, object value)
Overrides DynamicObject.TrySetMember(GetMemberBinder, object) so that we can have write access to elements of this wrapper object in such a way that they directly reference elements of the wrapped object (in case that wrapped object has internal fields).
override bool TryGetIndex (GetIndexBinder binder, object[] indexes, out object result)
Overrides DynamicObject.TryGetIndex(GetIndexBinder, object[], out object) so that we can reference fields on this wrapper object in such a way that they directly reference fields of the wrapped object (in case that wrapped object has internal fields).
override bool TrySetIndex (SetIndexBinder binder, object[] indexes, object val)
Overrides DynamicObject.TrySetIndex(SetIndexBinder, object[], object) so that we can reference table elements on this wrapper object in such a way that they directly reference elements of the wrapped object (in case that wrapped object has internal fields).
virtual string SerializeJson (object obj, bool inReadableFom=false)
Serializes the specified object to JSON string and returns that string.
virtual string SerializeJson (bool inReadableFom=false)
Serializes the current object to JSON string and returns that string.
virtual object DeserializeJsonPlain (string jsonString)
Deserialized the specified JSON string parameter jsonString into an object and returns that object.
virtual WrapperType DeserializeJson< WrapperType > (string jsonString)
Deserialized the specified JSON string parameter jsonString into an object and returns that object wrapped into a dynamic object wrapper of type WrapperType .
virtual DynamicWrapper DeserializeJson (string jsonString)
Deserialized the specified JSON string parameter jsonString into an object and returns that object wrapped into a dynamic object wrapper of the appropriate type for wotrk with the current object type.
virtual string ToString (bool inReadableForm)
Returns string representation of the current wrapper object in JSON format, wrapped in container that also indicates the type of the wrapper.
override string ToString ()
Returns string representation of the current wrapper object in JSON format, wrapped in container that also indicates the type of the wrapper.
Public Member Functions inherited from IG.Lib.DynamicWrapperBase
virtual object GetArrayElementS (object nodeObject, int arrayIndex)
Returns the specified array element of the currently wrapped element, or null if this object is not an array-lika object.
Static Public Member Functions
static void ExampleJsonSerialization (string[] predefinedSampleNames=null, string[] jsonFilePaths=null, int numRepetitions=1, int sleepMsSerialization=0, int sleepMsDeserialization=0, double cpuIterationFactor=1.0e5)
static void ExampleJsonSpeedTest (string[] predefinedSampleNames=null, string[] jsonFilePaths=null, int numRepetitions=1, int sleepMsSerialization=0, int sleepMsDeserialization=0, double cpuIterationFactor=1.0e5)
static void ExampleElementReferencing ()
Example that demonstrates how parss of the wrapped object graph can be referenced.
static void Examples ()
Static Public Member Functions inherited from IG.Lib.DynamicWrapperBase
static WrapperType CreateArrayWrapperS< WrapperType > ()
Creates and returns a new wrapped object of an appropriate type, which can act as array of objects.
static object CreateStructWrapperS< WrapperType > ()
Creates and returns a new wrapped object of the appropriate type, which can act as a struct containing other objects as named fields.
static object CreateArrayObjectS ()
Creates and returns an obect of the appropriate type, which can act as array (or list) of other objects.
static object CreateStructObjectS< WrapperType > ()
Creates and returns an obect of the appropriate type, which can act struct that contains arbitrary numbe of other objects in as named fields.
static object UnwrapObjectS (DynamicWrapper wrappedObject)
Returns the object that is wrapped by the wrappedObject , or null if wrappedObject is null.
static object UnwrapObjectIfWrappedS (object wrappedOrPlain)
If wrappedOrPlain is a wrapper of type DynamicWrapper or its subtype, this method returns the unwrapped object that it contains, otherwise it returns the wrappedOrPlain itself.
static WrapperType WrapObjectS< WrapperType > (object obj)
Wraps the specified object (obj) in to a dynamic wrapper of type WrapperType and returns the wrapped object.
static bool IsStructS (object nodeObject)
Returns true if the wrapped object implements IDictionary<string, object> interface, meaning that it contains fields addressable by field names, thus behaving like a struct.
static bool IsArrayS (object nodeObject)
Returns true if the wrapped object implements IDictionary interface, meaning that it contains fields addressable by field names, thus behaving like a struct.
static bool IsLeafS (object nodeObject)
Returns true if the currently wrapped object is a leaf object, i.e., it is neither an array object nor a struct-like object.
static int NumStructFieldsS (object nodeObject)
Returns the number of struct fields of the currently wrapped object, or 0 if this object is not a struct-like object with field members.
static int NumArrayElementsS (object nodeObject)
Returns the number of array elements of the currently wrapped object, of 0 if this object is not an array-like object with indexed elements.
static IDictionary< String, object > GetStructElementsS (object nodeObject)
Returns a dictionary of struct elements of the currently wrapped object, or null if this object is not a struct-like object containing named fields.
static ICollection< string > GetStructKeysS (object nodeObject)
Returns a collection of field names of the currently wrapped element, or null if this object is not a struct-like object containing named fields.
static IList< string > GetStrucKeysAsListS (object nodeObject)
Returns a list of field names of the currently wrapped element, or null if this object is not a struct-like object containing named fields.
static IList< object > GetArrayElementsS (object nodeObject)
Returns a list of array elements of the currently wrapped element, or null if this object is not an array-like object containing indexed elements.
static object GetStructElemetS (object nodeObject, string fieldName)
Returns the specified field of the currently wrapped object, or null if this object is not a struct-like object containing named fields.
static string GetReadableJsonStringS (string jsonString)
Returns a re-formatred input JSON string jsonString formated in such a way that it is more readable (with newlines and indentation added).
static string SerializeJsonS (object obj, bool inReadableForm=false)
Serializes the first argument obj into a JSON string and returns that string.
static object DeserializeJsonPlainS (string jsonString)
Deserialized the specified JSON string parameter jsonString into an object and returns that object.
static WrapperType DeserializeJsonS< WrapperType > (string jsonString)
Deserialized the specified JSON string parameter jsonString into an object and returns that object wrapped into a dynamic object wrapper of type WrapperType .
Static Protected Member Functions
static string PrintExampleHeader (string exampleName)
Returns a header to be printed at the beginning of each example.
static string PrintExampleFooter (string exampleName)
Returns a footer to be printed at the end of each example.
static void ExampleJsonSerializationOrSpeedTest (bool isSpeedTest, string[] predefinedSampleNames, string[] jsonFilePaths, int numRepetitions, int sleepMsSerialization, int sleepMsDeserialization, double cpuIterationFactor)
Does the job for either the example of performing JSON serialization and deserialization (method ExampleJsonSerialization) or a speed test of serialization/deserialization operations (method) with DynamicWrapper class.
static Dictionary< string, string > GetExampleJsonObjects (string[] predefinedSampleNames=null, string[] jsonFilePaths=null)
Returns a set of named JSON samples that can be uses in examples and tests.
Static Protected Attributes
const string exArrayExample = "ArrayExample"
const string exNestedArrayExample = "NestedArrayExample"
const string exStructExample = "StructExample"
const string exNestedStructExample = "NestedStructExample"
const string exComplexExample = "ComplexExample"
Private Attributes
object _objectInternal3859385032
Detailed Description
Dynamic object wrapper class for handling JSON serialization and deserialization of objects, addressing of object via field access and indexing notations, transversal of objects, performing operations on objects and their parts, and as base class to derive object that represent arbitrary tree structures such as DOMs or file structures.
This class is especially suitable for representation of objects where direct mapping between JSON and object graphs exist.
A number of standard operations are implemented such as indexing of table elements and setting of object fields vie member operator (.), JSON serialization / deserialization, wrapping and unwrapping, transversal, etc. Functionality can be extended in subclasses.
$A Igor Nov18;
Constructor & Destructor Documentation
DynamicWrapper() [1/3]
IG.Lib.DynamicWrapper.DynamicWrapper () inline
Referenced by IG.Lib.DynamicWrapper.CrateWrapper(), IG.Lib.DynamicWrapper.TrySetIndex(), and IG.Lib.DynamicWrapper.TrySetMember().
DynamicWrapper() [2/3]
IG.Lib.DynamicWrapper.DynamicWrapper (object obj) inline
References IG.Lib.DynamicWrapper.SetObject().
DynamicWrapper() [3/3]
IG.Lib.DynamicWrapper.DynamicWrapper (DynamicWrapper otherWrapper) inline
References IG.Lib.DynamicWrapper.GetObject(), and IG.Lib.DynamicWrapper.SetObject().
Member Function Documentation
WrapObject()
virtual DynamicWrapper IG.Lib.DynamicWrapper.WrapObject (object obj) inline virtual
Wraps the specified object in a wrapper of the type DynamicWrapper and returns the wrapper.
This method should normally be overriden in every derived class.
Parameters
obj Object that is wrapped.
Referenced by IG.Lib.DynamicWrapper.TryGetIndex(), and IG.Lib.DynamicWrapper.TryGetMember().
CrateWrapper()
virtual DynamicWrapper IG.Lib.DynamicWrapper.CrateWrapper () inline virtual
Creates and returns a new dynamic object wrapper of the type DynamicWrapper.
This method should be overridden in all derived classes because it specifies the type of the wrappers returned by indexers and field reference operators, and this type must be consistend with the type of object on which the method is called.
References IG.Lib.DynamicWrapper.DynamicWrapper().
Referenced by IG.Lib.DynamicWrapper.CreateWrapper().
CreateWrapper()
virtual DynamicWrapper IG.Lib.DynamicWrapper.CreateWrapper (object wrappedObject) inline virtual
Creates and returns a new dynamic object wrapper (a subtype of DynamicWrapper) of the specific type corresponding to the type of the object on which the method is called.
References IG.Lib.DynamicWrapper.CrateWrapper().
CreateArrayWrapper< WrapperType >()
virtual WrapperType IG.Lib.DynamicWrapper.CreateArrayWrapper< WrapperType > () inline virtual
Creates and returns a new wrapped object of an appropriate type, which can act as array of objects.
Template Parameters
WrapperType Type of the wrapper class (subtype of DynamicWrapper) of which the returned object is.
Type Constraints
WrapperType : DynamicWrapper
WrapperType : new()
References IG.Lib.DynamicWrapperBase.CreateArrayWrapperS< WrapperType >().
CreateStructWrapper< WrapperType >()
virtual object IG.Lib.DynamicWrapper.CreateStructWrapper< WrapperType > () inline virtual
Creates and returns a new wrapped object of the appropriate type, which can act as a struct containing other objects as named fields.
Template Parameters
WrapperType Type of the wrapper class (subtype of DynamicWrapper) of which the returned object is.
Type Constraints
WrapperType : DynamicWrapper
WrapperType : new()
References IG.Lib.DynamicWrapperBase.CreateStructWrapperS< WrapperType >().
CreateArrayObject()
virtual object IG.Lib.DynamicWrapper.CreateArrayObject () inline virtual
Creates and returns an obect of the appropriate type, which can act as array (or list) of other objects.
This is a helper method whose purpose is to ensure uniform typing of objects composing object graphs that are wrapped by wrappers of type DynamicWrapper or its subtypes
References IG.Lib.DynamicWrapperBase.CreateArrayObjectS().
CreateStructObject< WrapperType >()
virtual object IG.Lib.DynamicWrapper.CreateStructObject< WrapperType > () inline virtual
Creates and returns an obect of the appropriate type, which can act struct that contains arbitrary numbe of other objects in as named fields.
This is a helper method whose purpose is to ensure uniform types of objects composing object graphs that are wrapped by wrappers of type DynamicWrapper or its subtypes
Type Constraints
WrapperType : DynamicWrapper
WrapperType : new()
References IG.Lib.DynamicWrapperBase.CreateStructObjectS< WrapperType >().
UnwrapObject()
virtual object IG.Lib.DynamicWrapper.UnwrapObject (DynamicWrapper wrapper) inline virtual
Returns the internal object that is wrapped by the wrapper , or null if wrapper is null.
UnwrapObject(wrapper) is equivalent to wrapper.GetObject(), except when wrapper==null, in which case the later expression would throw exception while the first one returns null.
Parameters
wrapper Object that whose internal unwrapped object is returned.
References IG.Lib.DynamicWrapper.GetObject().
Referenced by IG.Lib.DynamicWrapper.TrySetIndex(), and IG.Lib.DynamicWrapper.TrySetMember().
UnwrapObjectIfWrapped()
virtual object IG.Lib.DynamicWrapper.UnwrapObjectIfWrapped (object wrappedOrPlain) inline virtual
If wrappedOrPlain is a wrapper of type DynamicWrapper or its subtype, this method returns the unwrapped object that it contains, otherwise it returns the wrappedOrPlain itself.
Parameters
wrappedOrPlain Object that is unwrapped (when applicable) and returned.
References IG.Lib.DynamicWrapperBase.UnwrapObjectIfWrappedS().
WrapObject< WrapperType >()
virtual WrapperType IG.Lib.DynamicWrapper.WrapObject< WrapperType > (object obj) inline virtual
Wraps the specified object (obj) in to a dynamic wrapper of type WrapperType and returns the wrapped object.
Template Parameters
WrapperType Type of the dynamic wrapper into which object is wrapped.
Parameters
obj
Type Constraints
WrapperType : DynamicWrapper
WrapperType : new()
References IG.Lib.DynamicWrapperBase.WrapObjectS< WrapperType >().
GetObject()
virtual object IG.Lib.DynamicWrapper.GetObject () inline virtual
Returns the wrapped object.
References IG.Lib.DynamicWrapper._objectInternal3859385032.
Referenced by IG.Lib.DynamicWrapper.DynamicWrapper(), IG.Lib.DynamicWrapper.GetArrayElement(), IG.Lib.DynamicWrapper.GetArrayElements(), IG.Lib.DynamicWrapper.GetStructElements(), IG.Lib.DynamicWrapper.GetStructElemet(), IG.Lib.DynamicWrapper.IsArray(), IG.Lib.DynamicWrapper.IsLeaf(), IG.Lib.DynamicWrapper.IsStruct(), IG.Lib.DynamicWrapper.NumArrayElements(), IG.Lib.DynamicWrapper.NumStructFields(), IG.Lib.DynamicWrapper.SetObject(), IG.Lib.DynamicWrapper.UnwrapObject(), IG.Lib.DynamicWrapperBase.UnwrapObjectIfWrappedS(), and IG.Lib.DynamicWrapperBase.UnwrapObjectS().
SetObject()
virtual void IG.Lib.DynamicWrapper.SetObject (object obj) inline virtual
Sets the wrapped object to obj .
Parameters
obj
References IG.Lib.DynamicWrapper._objectInternal3859385032, and IG.Lib.DynamicWrapper.GetObject().
Referenced by IG.Lib.DynamicWrapper.DynamicWrapper().
IsStruct()
virtual bool IG.Lib.DynamicWrapper.IsStruct () inline virtual
Returns true if the wrapped object implements IDictionary<string, object> interface, meaning that it contains fields addressable by field names, thus behaving like a struct.
Returns
True if wrapped object behaves like struct and implements IDIctionary interface.
References IG.Lib.DynamicWrapper.GetObject().
Referenced by IG.Lib.DynamicWrapper.IsLeaf().
IsArray()
virtual bool IG.Lib.DynamicWrapper.IsArray () inline virtual
Returns true if the wrapped object implements IDictionary interface, meaning that it contains fields addressable by field names, thus behaving like a struct.
Returns
True if wrapped object behaves like struct and implements IDIctionary interface.
References IG.Lib.DynamicWrapper.GetObject().
Referenced by IG.Lib.DynamicWrapper.IsLeaf().
IsLeaf()
virtual bool IG.Lib.DynamicWrapper.IsLeaf () inline virtual
Returns true if the currently wrapped object is a leaf object, i.e., it is neither an array object nor a struct-like object.
References IG.Lib.DynamicWrapper.GetObject(), IG.Lib.DynamicWrapper.IsArray(), and IG.Lib.DynamicWrapper.IsStruct().
NumStructFields()
virtual int IG.Lib.DynamicWrapper.NumStructFields () inline virtual
Returns the number of struct fields of the currently wrapped object, or 0 if this object is not a struct-like object with field members.
References IG.Lib.DynamicWrapper.GetObject().
NumArrayElements()
virtual int IG.Lib.DynamicWrapper.NumArrayElements () inline virtual
Returns the number of array elements of the currently wrapped object, of 0 if this object is not an array-like object with indexed elements.
Returns
References IG.Lib.DynamicWrapper.GetObject().
GetStructElements()
virtual IDictionary<String, object> IG.Lib.DynamicWrapper.GetStructElements () inline virtual
Returns a dictionary of struct elements of the currently wrapped object, or null if this object is not a struct-like object containing named fields.
Returns
References IG.Lib.DynamicWrapper.GetObject().
Referenced by IG.Lib.DynamicWrapper.GetStructKeys(), IG.Lib.DynamicWrapper.TryGetMember(), and IG.Lib.DynamicWrapper.TrySetMember().
GetStructKeys()
virtual ICollection<string> IG.Lib.DynamicWrapper.GetStructKeys () inline virtual
Returns a collection of field names of the currently wrapped element, or null if this object is not a struct-like object containing named fields.
References IG.Lib.DynamicWrapper.GetStructElements().
Referenced by IG.Lib.DynamicWrapper.GetStrucKeysAsList().
GetStrucKeysAsList()
virtual IList<string> IG.Lib.DynamicWrapper.GetStrucKeysAsList () inline virtual
Returns a list of field names of the currently wrapped element, or null if this object is not a struct-like object containing named fields.
References IG.Lib.DynamicWrapper.GetStructKeys().
GetArrayElements()
virtual IList<object> IG.Lib.DynamicWrapper.GetArrayElements () inline virtual
Returns a list of array elements of the currently wrapped element, or null if this object is not an array-like object containing indexed elements.
References IG.Lib.DynamicWrapper.GetObject().
Referenced by IG.Lib.DynamicWrapper.TryGetIndex(), and IG.Lib.DynamicWrapper.TrySetIndex().
GetArrayElement()
virtual object IG.Lib.DynamicWrapper.GetArrayElement (int arrayIndex) inline virtual
Returns the specified array element of the currently wrapped element, or null if this object is not an array-lika object.
Parameters
arrayIndex Index of the array element to be returned.
Returns
References IG.Lib.DynamicWrapper.GetObject().
Referenced by IG.Lib.DynamicWrapper.TryGetIndex().
GetStructElemet()
virtual object IG.Lib.DynamicWrapper.GetStructElemet (string fieldName) inline virtual
Returns the specified field of the currently wrapped object, or null if this object is not a struct-like object containing named fields.
Parameters
fieldName Name of the field of a struct-like object to be returned.
Returns
References IG.Lib.DynamicWrapper.GetObject().
Referenced by IG.Lib.DynamicWrapper.TryGetIndex().
TryGetMember()
override bool IG.Lib.DynamicWrapper.TryGetMember (GetMemberBinder binder, out object result) inline
Overrides DynamicObject.TryGetMember(GetMemberBinder, out object) so that we can reference fields on this wrapper object in such a way that they directly reference fields of the wrapped object (in case that wrapped object has internal fields).
Parameters
binder Binder.
result Parametr through which value of the field is returned.
Returns
True if operation is successful (if the given field exists on the dynamically wrapped object and if the obect contains fields at all (it could also be an array)), false otherwise.
References IG.Lib.DynamicWrapper.GetStructElements(), and IG.Lib.DynamicWrapper.WrapObject().
TrySetMember()
override bool IG.Lib.DynamicWrapper.TrySetMember (SetMemberBinder binder, object value) inline
Overrides DynamicObject.TrySetMember(GetMemberBinder, object) so that we can have write access to elements of this wrapper object in such a way that they directly reference elements of the wrapped object (in case that wrapped object has internal fields).
Parameters
binder Binder taking care of binding.
value Value to which the field specified by binder is set.
Returns
True if operation is successful, false otherwise.
References IG.Lib.DynamicWrapper.DynamicWrapper(), IG.Lib.DynamicWrapper.GetStructElements(), and IG.Lib.DynamicWrapper.UnwrapObject().
TryGetIndex()
override bool IG.Lib.DynamicWrapper.TryGetIndex (GetIndexBinder binder, object[] indexes, out object result) inline
Overrides DynamicObject.TryGetIndex(GetIndexBinder, object[], out object) so that we can reference fields on this wrapper object in such a way that they directly reference fields of the wrapped object (in case that wrapped object has internal fields).
Parameters
binder Provides information about dynamic operation.
result Parametr through which value of the array element is returned.
Returns
True if operation is successful (if the dynamically wrapped object is array and if indices are within bounds), false otherwise.
References IG.Lib.DynamicWrapper.GetArrayElement(), IG.Lib.DynamicWrapper.GetArrayElements(), IG.Lib.DynamicWrapper.GetStructElemet(), and IG.Lib.DynamicWrapper.WrapObject().
TrySetIndex()
override bool IG.Lib.DynamicWrapper.TrySetIndex (SetIndexBinder binder, object[] indexes, object val) inline
Overrides DynamicObject.TrySetIndex(SetIndexBinder, object[], object) so that we can reference table elements on this wrapper object in such a way that they directly reference elements of the wrapped object (in case that wrapped object has internal fields).
Parameters
binder Binder object that binds array elemets to indices.
indexes Table of indices. Only one integer index is allowed, otherwise the operation fails..
val Parametr through which value of the element at specific index is returned.
Returns
True if operation is successful (if the dynamically wrapped object represents a one-dimensional array and if a single index is contained in indexes and it is not out of bounds of the actual table that object wrapped in this object.
References IG.Lib.DynamicWrapper.DynamicWrapper(), IG.Lib.DynamicWrapper.GetArrayElements(), and IG.Lib.DynamicWrapper.UnwrapObject().
SerializeJson() [1/2]
virtual string IG.Lib.DynamicWrapper.SerializeJson (object obj, bool inReadableFom = false) inline virtual
Serializes the specified object to JSON string and returns that string.
Parameters
obj Object that si serialized.
inReadableFom If true then the returned JSON string is formatted to a more readable form, with newlines ande indentation added.
References IG.Lib.DynamicWrapperBase.SerializeJsonS().
Referenced by IG.Lib.DynamicWrapper.ToString().
SerializeJson() [2/2]
virtual string IG.Lib.DynamicWrapper.SerializeJson (bool inReadableFom = false) inline virtual
Serializes the current object to JSON string and returns that string.
Parameters
inReadableFom If true then the returned JSON string is formatted to a more readable form, with newlines ande indentation added.
References IG.Lib.DynamicWrapperBase.SerializeJsonS().
DeserializeJsonPlain()
virtual object IG.Lib.DynamicWrapper.DeserializeJsonPlain (string jsonString) inline virtual
Deserialized the specified JSON string parameter jsonString into an object and returns that object.
Parameters
jsonString JSON string from which the returned object is deserialized.
Returns
References IG.Lib.DynamicWrapperBase.DeserializeJsonPlainS().
DeserializeJson< WrapperType >()
virtual WrapperType IG.Lib.DynamicWrapper.DeserializeJson< WrapperType > (string jsonString) inline virtual
Deserialized the specified JSON string parameter jsonString into an object and returns that object wrapped into a dynamic object wrapper of type WrapperType .
Template Parameters
WrapperType generic parameter specifying the type of the wrapper object by which the deseralized object is wrapped.
Parameters
jsonString String from which the object is deserialized.
Returns
Deserialized object (from the specified JSON string) wrapped into the dynamic object wrapper of type
Template Parameters
WrapperType
Type Constraints
WrapperType : DynamicWrapper
WrapperType : new()
References IG.Lib.DynamicWrapperBase.DeserializeJsonS< WrapperType >().
DeserializeJson()
virtual DynamicWrapper IG.Lib.DynamicWrapper.DeserializeJson (string jsonString) inline virtual
Deserialized the specified JSON string parameter jsonString into an object and returns that object wrapped into a dynamic object wrapper of the appropriate type for wotrk with the current object type.
Parameters
jsonString String from which the object is deserialized.
Returns
Deserialized object (from the specified JSON string) wrapped into the dynamic object wrapper of the appropriate type according to the current wrapper type.
ToString() [1/2]
virtual string IG.Lib.DynamicWrapper.ToString (bool inReadableForm) inline virtual
Returns string representation of the current wrapper object in JSON format, wrapped in container that also indicates the type of the wrapper.
Parameters
inReadableForm If true then the returned string representation of is formatted in more readable way, with line breaks and indentation.
References IG.Lib.DynamicWrapper.SerializeJson().
Referenced by IG.Lib.DynamicWrapper.ExampleJsonSerializationOrSpeedTest().
ToString() [2/2]
override string IG.Lib.DynamicWrapper.ToString () inline
Returns string representation of the current wrapper object in JSON format, wrapped in container that also indicates the type of the wrapper.
Returned string is in condensed form. For human readable form, use ToString(bool)(true).
Parameters
inReadableForm If true then the returned string representation of is formatted in more readable way, with line breaks and indentation.
PrintExampleHeader()
static string IG.Lib.DynamicWrapper.PrintExampleHeader (string exampleName) inline static protected
Returns a header to be printed at the beginning of each example.
Parameters
exampleName Name of the example for which a header is returned.
Referenced by IG.Lib.DynamicWrapper.ExampleElementReferencing(), and IG.Lib.DynamicWrapper.ExampleJsonSerializationOrSpeedTest().
PrintExampleFooter()
static string IG.Lib.DynamicWrapper.PrintExampleFooter (string exampleName) inline static protected
Returns a footer to be printed at the end of each example.
Parameters
exampleName Name of the example for which a footer is returned.
Referenced by IG.Lib.DynamicWrapper.ExampleElementReferencing(), and IG.Lib.DynamicWrapper.ExampleJsonSerializationOrSpeedTest().
ExampleJsonSerialization()
static void IG.Lib.DynamicWrapper.ExampleJsonSerialization (string[] predefinedSampleNames = null, string[] jsonFilePaths = null, int numRepetitions = 1, int sleepMsSerialization = 0, int sleepMsDeserialization = 0, double cpuIterationFactor = 1.0e5) inline static
Parameters
predefinedSampleNames Array containing pre-defined names of samples. If null then all pre-defined samples are taken into account, if empty array than no predefined samples are taken into account.
jsonFilePaths Paths to JSON files whose contents are included in this example.
If null or empty array then no samples obttaind from files are included.
Parameters
numRepetitions Number of repetitions of each serialization or deserialization.
sleepMsSerialization Provisional parameter, deprecated. Number of milliseconds for which sleep is performed during each serialization, do simulate processing times when all samples are small.
sleepMsDeserialization Provisional parameter, deprecated. Number of milliseconds for which sleep is performed during each deserialization, do simulate processing times when all samples are small.
cpuIterationFactor Provisional parameter, deprecated. Factor defining number of iterations executing floting pint operations with respect to sleep times specified by sleepMsSerialization and sleepMsSerialization .
References IG.Lib.DynamicWrapper.ExampleJsonSerializationOrSpeedTest().
Referenced by IG.Lib.DynamicWrapper.Examples().
ExampleJsonSpeedTest()
static void IG.Lib.DynamicWrapper.ExampleJsonSpeedTest (string[] predefinedSampleNames = null, string[] jsonFilePaths = null, int numRepetitions = 1, int sleepMsSerialization = 0, int sleepMsDeserialization = 0, double cpuIterationFactor = 1.0e5) inline static
Parameters
predefinedSampleNames Array containing pre-defined names of samples. If null then all pre-defined samples are taken into account, if empty array than no predefined samples are taken into account.
jsonFilePaths Paths to JSON files whose contents are included in this example.
If null or empty array then no samples obttaind from files are included.
Parameters
numRepetitions Number of repetitions of each serialization or deserialization.
sleepMsSerialization Provisional parameter, deprecated. Number of milliseconds for which sleep is performed during each serialization, do simulate processing times when all samples are small.
sleepMsDeserialization Provisional parameter, deprecated. Number of milliseconds for which sleep is performed during each deserialization, do simulate processing times when all samples are small.
cpuIterationFactor Provisional parameter, deprecated. Factor defining number of iterations executing floting pint operations with respect to sleep times specified by sleepMsSerialization and sleepMsSerialization .
References IG.Lib.DynamicWrapper.ExampleJsonSerializationOrSpeedTest().
Referenced by IG.Lib.DynamicWrapper.Examples().
ExampleJsonSerializationOrSpeedTest()
static void IG.Lib.DynamicWrapper.ExampleJsonSerializationOrSpeedTest (bool isSpeedTest, string[] predefinedSampleNames, string[] jsonFilePaths, int numRepetitions, int sleepMsSerialization, int sleepMsDeserialization, double cpuIterationFactor) inline static protected
Does the job for either the example of performing JSON serialization and deserialization (method ExampleJsonSerialization) or a speed test of serialization/deserialization operations (method) with DynamicWrapper class.
Parameters
isSpeedTest Specified whether a speed test should be performed rather than just a serialization/deserialization demonstration.
predefinedSampleNames Array containing pre-defined names of samples. If null then all pre-defined samples are taken into account, if empty array than no predefined samples are taken into account.
jsonFilePaths Paths to JSON files whose contents are included in this example.
If null or empty array then no samples obttaind from files are included.
Parameters
numRepetitions Number of repetitions of each serialization / deserialization.
This is used in case of small samples where single serialization/deserialization times may be very short, in order to measure times better.
Parameters
sleepMsSerialization Provisional parameter, deprecated. Number of milliseconds for which sleep is performed during each serialization, do simulate processing times when all samples are small.
sleepMsDeserialization Provisional parameter, deprecated. Number of milliseconds for which sleep is performed during each deserialization, do simulate processing times when all samples are small.
cpuIterationFactor Provisional parameter, deprecated. Factor defining number of iterations executing floting pint operations with respect to sleep times specified by sleepMsSerialization and sleepMsSerialization .
References IG.Lib.DynamicWrapper.GetExampleJsonObjects(), IG.Lib.DynamicWrapper.PrintExampleFooter(), IG.Lib.DynamicWrapper.PrintExampleHeader(), IG.Lib.DynamicWrapperBase.SerializeJsonS(), and IG.Lib.DynamicWrapper.ToString().
Referenced by IG.Lib.DynamicWrapper.ExampleJsonSerialization(), and IG.Lib.DynamicWrapper.ExampleJsonSpeedTest().
ExampleElementReferencing()
static void IG.Lib.DynamicWrapper.ExampleElementReferencing () inline static
Example that demonstrates how parss of the wrapped object graph can be referenced.
References IG.Lib.DynamicWrapper.exNestedStructExample, IG.Lib.DynamicWrapper.GetExampleJsonObjects(), IG.Lib.DynamicWrapper.PrintExampleFooter(), IG.Lib.DynamicWrapper.PrintExampleHeader(), IG.Lib.DynamicWrapperBase.UnwrapObjectIfWrappedS(), and IG.Lib.DynamicWrapperBase.UnwrapObjectS().
Referenced by IG.Test.Json.Main_DynamicWrapperExamples().
Examples()
static void IG.Lib.DynamicWrapper.Examples () inline static
References IG.Lib.DynamicWrapper.ExampleJsonSerialization(), and IG.Lib.DynamicWrapper.ExampleJsonSpeedTest().
GetExampleJsonObjects()
static Dictionary<string, string> IG.Lib.DynamicWrapper.GetExampleJsonObjects (string[] predefinedSampleNames = null, string[] jsonFilePaths = null) inline static protected
Returns a set of named JSON samples that can be uses in examples and tests.
Parameters
predefinedSampleNames Array containing pre-defined names of samples.
If null then all pre-defined samples are taken into account.
If empty array than no predefined samples are taken into account.
Parameters
jsonFilePaths Paths to JSON files whose contents are included in this example.
If null or empty array then no samples obtaind from files are included.
References IG.Lib.DynamicWrapper.exArrayExample, IG.Lib.DynamicWrapper.exComplexExample, IG.Lib.DynamicWrapper.exNestedArrayExample, IG.Lib.DynamicWrapper.exNestedStructExample, and IG.Lib.DynamicWrapper.exStructExample.
Referenced by IG.Lib.DynamicWrapper.ExampleElementReferencing(), and IG.Lib.DynamicWrapper.ExampleJsonSerializationOrSpeedTest().
Member Data Documentation
_objectInternal3859385032
object IG.Lib.DynamicWrapper._objectInternal3859385032 private
Referenced by IG.Lib.DynamicWrapper.GetObject(), and IG.Lib.DynamicWrapper.SetObject().
exArrayExample
const string IG.Lib.DynamicWrapper.exArrayExample = "ArrayExample" static protected
Referenced by IG.Lib.DynamicWrapper.GetExampleJsonObjects().
exNestedArrayExample
const string IG.Lib.DynamicWrapper.exNestedArrayExample = "NestedArrayExample" static protected
Referenced by IG.Lib.DynamicWrapper.GetExampleJsonObjects().
exStructExample
const string IG.Lib.DynamicWrapper.exStructExample = "StructExample" static protected
Referenced by IG.Lib.DynamicWrapper.GetExampleJsonObjects().
exNestedStructExample
const string IG.Lib.DynamicWrapper.exNestedStructExample = "NestedStructExample" static protected
Referenced by IG.Lib.DynamicWrapper.ExampleElementReferencing(), and IG.Lib.DynamicWrapper.GetExampleJsonObjects().
exComplexExample
const string IG.Lib.DynamicWrapper.exComplexExample = "ComplexExample" static protected
Referenced by IG.Lib.DynamicWrapper.GetExampleJsonObjects().
The documentation for this class was generated from the following file:
unittests/Guest_IGTestQuick/DynamicWrapper/DynamicWrapper.cs