Doc: IGLib EXTENDED: AForge.Imaging.DocumentSkewChecker Class Reference
AForge.Imaging.DocumentSkewChecker Class Reference
Skew angle checker for scanned documents.
Public Member Functions
DocumentSkewChecker ()
Initializes a new instance of the DocumentSkewChecker class.
double GetSkewAngle (Bitmap image)
Get skew angle of the provided document image.
double GetSkewAngle (Bitmap image, Rectangle rect)
Get skew angle of the provided document image.
double GetSkewAngle (BitmapData imageData)
Get skew angle of the provided document image.
double GetSkewAngle (BitmapData imageData, Rectangle rect)
Get skew angle of the provided document image.
double GetSkewAngle (UnmanagedImage image)
Get skew angle of the provided document image.
double GetSkewAngle (UnmanagedImage image, Rectangle rect)
Get skew angle of the provided document image.
Properties
int StepsPerDegree [get, set]
Steps per degree, [1, 10].
double MaxSkewToDetect [get, set]
Maximum skew angle to detect, [0, 45] degrees.
double MinBeta [get, set]
Minimum angle to detect skew in degrees.
double MaxBeta [get, set]
Maximum angle to detect skew in degrees.
int LocalPeakRadius [get, set]
Radius for searching local peak value, [1, 10].
Private Member Functions
HoughLine[] GetMostIntensiveLines (int count)
void CollectLines (short minLineIntensity)
void InitHoughMap ()
Private Attributes
int stepsPerDegree
int houghHeight
double thetaStep
double maxSkewToDetect
double[] sinMap
double[] cosMap
bool needToInitialize = true
short[,] houghMap
short maxMapIntensity = 0
int localPeakRadius = 4
ArrayList lines = new ArrayList()
Detailed Description
Skew angle checker for scanned documents.
The class implements document's skew checking algorithm, which is based on Hough line transformation. The algorithm is based on searching for text base lines - black line of text bottoms' followed by white line below.
<note>The routine supposes that a white-background document is provided with black letters. The algorithm is not supposed for any type of objects, but for document images with text.</note>
The range of angles to detect is controlled by MaxSkewToDetect property.
The filter accepts 8 bpp grayscale images for processing.
Sample usage:
// create instance of skew checker
DocumentSkewChecker skewChecker = new DocumentSkewChecker();
// get documents skew angle
double angle = skewChecker.GetSkewAngle(documentImage);
// create rotation filter
RotateBilinear rotationFilter = new RotateBilinear(-angle);
rotationFilter.FillColor = Color.White;
// rotate image applying the filter
Bitmap rotatedImage = rotationFilter.Apply(documentImage);
Initial image:
Deskewed image:
See also
HoughLineTransformation
Constructor & Destructor Documentation
DocumentSkewChecker()
AForge.Imaging.DocumentSkewChecker.DocumentSkewChecker () inline
Initializes a new instance of the DocumentSkewChecker class.
References AForge.Imaging.DocumentSkewChecker.MaxSkewToDetect, and AForge.Imaging.DocumentSkewChecker.StepsPerDegree.
Member Function Documentation
GetSkewAngle() [1/6]
double AForge.Imaging.DocumentSkewChecker.GetSkewAngle (Bitmap image) inline
Get skew angle of the provided document image.
Parameters
image Document's image to get skew angle of.
Returns
Returns document's skew angle. If the returned angle equals to -90, then document skew detection has failed.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.DocumentSkewChecker.GetSkewAngle().
GetSkewAngle() [2/6]
double AForge.Imaging.DocumentSkewChecker.GetSkewAngle (Bitmap image, Rectangle rect) inline
Get skew angle of the provided document image.
Parameters
image Document's image to get skew angle of.
rect Image's rectangle to process (used to exclude processing of regions, which are not relevant to skew detection).
Returns
Returns document's skew angle. If the returned angle equals to -90, then document skew detection has failed.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Imaging.DocumentSkewChecker.GetSkewAngle(), and AForge.Math.Geometry.Rectangle.
GetSkewAngle() [3/6]
double AForge.Imaging.DocumentSkewChecker.GetSkewAngle (BitmapData imageData) inline
Get skew angle of the provided document image.
Parameters
imageData Document's image data to get skew angle of.
Returns
Returns document's skew angle. If the returned angle equals to -90, then document skew detection has failed.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Imaging.DocumentSkewChecker.GetSkewAngle(), and AForge.Math.Geometry.Rectangle.
GetSkewAngle() [4/6]
double AForge.Imaging.DocumentSkewChecker.GetSkewAngle (BitmapData imageData, Rectangle rect) inline
Get skew angle of the provided document image.
Parameters
imageData Document's image data to get skew angle of.
rect Image's rectangle to process (used to exclude processing of regions, which are not relevant to skew detection).
Returns
Returns document's skew angle. If the returned angle equals to -90, then document skew detection has failed.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Imaging.DocumentSkewChecker.GetSkewAngle().
GetSkewAngle() [5/6]
double AForge.Imaging.DocumentSkewChecker.GetSkewAngle (UnmanagedImage image) inline
Get skew angle of the provided document image.
Parameters
image Document's unmanaged image to get skew angle of.
Returns
Returns document's skew angle. If the returned angle equals to -90, then document skew detection has failed.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Imaging.DocumentSkewChecker.GetSkewAngle(), AForge.Imaging.UnmanagedImage.Height, AForge.Math.Geometry.Rectangle, and AForge.Imaging.UnmanagedImage.Width.
GetSkewAngle() [6/6]
double AForge.Imaging.DocumentSkewChecker.GetSkewAngle (UnmanagedImage image, Rectangle rect) inline
Get skew angle of the provided document image.
Parameters
image Document's unmanaged image to get skew angle of.
rect Image's rectangle to process (used to exclude processing of regions, which are not relevant to skew detection).
Returns
Returns document's skew angle. If the returned angle equals to -90, then document skew detection has failed.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Imaging.DocumentSkewChecker.CollectLines(), AForge.Imaging.DocumentSkewChecker.cosMap, AForge.Imaging.DocumentSkewChecker.GetMostIntensiveLines(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.DocumentSkewChecker.houghHeight, AForge.Imaging.DocumentSkewChecker.houghMap, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.DocumentSkewChecker.InitHoughMap(), AForge.Imaging.DocumentSkewChecker.maxMapIntensity, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Math.Geometry.Rectangle, AForge.Imaging.HoughLine.RelativeIntensity, AForge.Imaging.DocumentSkewChecker.sinMap, AForge.Imaging.UnmanagedImage.Stride, AForge.Imaging.HoughLine.Theta, and AForge.Imaging.UnmanagedImage.Width.
GetMostIntensiveLines()
HoughLine [] AForge.Imaging.DocumentSkewChecker.GetMostIntensiveLines (int count) inline private
References AForge.Imaging.DocumentSkewChecker.lines.
Referenced by AForge.Imaging.DocumentSkewChecker.GetSkewAngle().
CollectLines()
void AForge.Imaging.DocumentSkewChecker.CollectLines (short minLineIntensity) inline private
References AForge.Imaging.DocumentSkewChecker.houghMap, AForge.Imaging.DocumentSkewChecker.lines, AForge.Imaging.DocumentSkewChecker.localPeakRadius, AForge.Imaging.DocumentSkewChecker.maxMapIntensity, AForge.Imaging.DocumentSkewChecker.maxSkewToDetect, and AForge.Imaging.DocumentSkewChecker.stepsPerDegree.
Referenced by AForge.Imaging.DocumentSkewChecker.GetSkewAngle().
InitHoughMap()
void AForge.Imaging.DocumentSkewChecker.InitHoughMap () inline private
References AForge.Imaging.DocumentSkewChecker.cosMap, AForge.Imaging.DocumentSkewChecker.houghHeight, AForge.Imaging.DocumentSkewChecker.maxSkewToDetect, AForge.Imaging.DocumentSkewChecker.needToInitialize, AForge.Imaging.DocumentSkewChecker.sinMap, AForge.Imaging.DocumentSkewChecker.stepsPerDegree, and AForge.Imaging.DocumentSkewChecker.thetaStep.
Referenced by AForge.Imaging.DocumentSkewChecker.GetSkewAngle().
Member Data Documentation
stepsPerDegree
int AForge.Imaging.DocumentSkewChecker.stepsPerDegree private
Referenced by AForge.Imaging.DocumentSkewChecker.CollectLines(), and AForge.Imaging.DocumentSkewChecker.InitHoughMap().
houghHeight
int AForge.Imaging.DocumentSkewChecker.houghHeight private
Referenced by AForge.Imaging.DocumentSkewChecker.GetSkewAngle(), and AForge.Imaging.DocumentSkewChecker.InitHoughMap().
thetaStep
double AForge.Imaging.DocumentSkewChecker.thetaStep private
Referenced by AForge.Imaging.DocumentSkewChecker.InitHoughMap().
maxSkewToDetect
double AForge.Imaging.DocumentSkewChecker.maxSkewToDetect private
Referenced by AForge.Imaging.DocumentSkewChecker.CollectLines(), and AForge.Imaging.DocumentSkewChecker.InitHoughMap().
sinMap
double [] AForge.Imaging.DocumentSkewChecker.sinMap private
Referenced by AForge.Imaging.DocumentSkewChecker.GetSkewAngle(), and AForge.Imaging.DocumentSkewChecker.InitHoughMap().
cosMap
double [] AForge.Imaging.DocumentSkewChecker.cosMap private
Referenced by AForge.Imaging.DocumentSkewChecker.GetSkewAngle(), and AForge.Imaging.DocumentSkewChecker.InitHoughMap().
needToInitialize
bool AForge.Imaging.DocumentSkewChecker.needToInitialize = true private
Referenced by AForge.Imaging.DocumentSkewChecker.InitHoughMap().
houghMap
short [,] AForge.Imaging.DocumentSkewChecker.houghMap private
Referenced by AForge.Imaging.DocumentSkewChecker.CollectLines(), and AForge.Imaging.DocumentSkewChecker.GetSkewAngle().
maxMapIntensity
short AForge.Imaging.DocumentSkewChecker.maxMapIntensity = 0 private
Referenced by AForge.Imaging.DocumentSkewChecker.CollectLines(), and AForge.Imaging.DocumentSkewChecker.GetSkewAngle().
localPeakRadius
int AForge.Imaging.DocumentSkewChecker.localPeakRadius = 4 private
Referenced by AForge.Imaging.DocumentSkewChecker.CollectLines().
lines
ArrayList AForge.Imaging.DocumentSkewChecker.lines = new ArrayList() private
Referenced by AForge.Imaging.DocumentSkewChecker.CollectLines(), and AForge.Imaging.DocumentSkewChecker.GetMostIntensiveLines().
Property Documentation
StepsPerDegree
int AForge.Imaging.DocumentSkewChecker.StepsPerDegree get set
Steps per degree, [1, 10].
The value defines quality of Hough transform and its ability to detect line slope precisely.
Default value is set to 1.
Referenced by AForge.Imaging.DocumentSkewChecker.DocumentSkewChecker().
MaxSkewToDetect
double AForge.Imaging.DocumentSkewChecker.MaxSkewToDetect get set
Maximum skew angle to detect, [0, 45] degrees.
The value sets maximum document's skew angle to detect. Document's skew angle can be as positive (rotated counter clockwise), as negative (rotated clockwise). So setting this value to 25, for example, will lead to [-25, 25] degrees detection range.
Scanned documents usually have skew in the [-20, 20] degrees range.
Default value is set to 30.
Referenced by AForge.Imaging.DocumentSkewChecker.DocumentSkewChecker().
MinBeta
double AForge.Imaging.DocumentSkewChecker.MinBeta get set
Minimum angle to detect skew in degrees.
<note>The property is deprecated and setting it has not any effect. Use MaxSkewToDetect property instead.</note>
MaxBeta
double AForge.Imaging.DocumentSkewChecker.MaxBeta get set
Maximum angle to detect skew in degrees.
<note>The property is deprecated and setting it has not any effect. Use MaxSkewToDetect property instead.</note>
LocalPeakRadius
int AForge.Imaging.DocumentSkewChecker.LocalPeakRadius get set
Radius for searching local peak value, [1, 10].
The value determines radius around a map's value, which is analyzed to determine if the map's value is a local maximum in specified area.
Default value is set to 4.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/DocumentSkewChecker.cs