Doc: IGLib EXTENDED: AForge.Imaging.Filters.BaseTransformationFilter Class Reference
AForge.Imaging.Filters.BaseTransformationFilter Class Reference abstract
Base class for filters, which may produce new image of different size as a result of image processing.
Public Member Functions
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
Protected Member Functions
abstract System.Drawing.Size CalculateNewImageSize (UnmanagedImage sourceData)
Calculates new image size.
abstract unsafe void ProcessFilter (UnmanagedImage sourceData, UnmanagedImage destinationData)
Process the filter on the specified image.
Properties
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Member Functions
void CheckSourceFormat (PixelFormat pixelFormat)
Detailed Description
Base class for filters, which may produce new image of different size as a result of image processing.
The abstract class is the base class for all filters, which do image processing creating new image of the size, which may differ from the size of source image. Filters based on this class cannot be applied directly to the source image, which is kept unchanged.
The base class itself does not define supported pixel formats of source image and resulting pixel formats of destination image. Filters inheriting from this base class, should specify supported pixel formats and their transformations overriding abstract FormatTranslations property.
Member Function Documentation
Apply() [1/4]
Bitmap AForge.Imaging.Filters.BaseTransformationFilter.Apply (Bitmap image) inline
Apply filter to an image.
Parameters
image Source image to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The method keeps the source image unchanged and returns the result of image processing filter as new image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.Filters.QuadrilateralTransformationBilinear.ProcessFilter(), AForge.Imaging.Filters.QuadrilateralTransformationNearestNeighbor.ProcessFilter(), and AForge.Imaging.Filters.FlatFieldCorrection.ProcessFilter().
Apply() [2/4]
Bitmap AForge.Imaging.Filters.BaseTransformationFilter.Apply (BitmapData imageData) inline
Apply filter to an image.
Parameters
imageData Source image to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The filter accepts bitmap data as input and returns the result of image processing filter as new image. The source image data are kept unchanged.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.BaseTransformationFilter.CalculateNewImageSize(), AForge.Imaging.Filters.BaseTransformationFilter.CheckSourceFormat(), AForge.Imaging.Image.CreateGrayscaleImage(), AForge.Imaging.Filters.BaseTransformationFilter.FormatTranslations, AForge.Imaging.Filters.BaseTransformationFilter.ProcessFilter(), AForge.Math.Geometry.Rectangle, and AForge.Imaging.Size.
Apply() [3/4]
UnmanagedImage AForge.Imaging.Filters.BaseTransformationFilter.Apply (UnmanagedImage image) inline
Apply filter to an image in unmanaged memory.
Parameters
image Source image in unmanaged memory to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The method keeps the source image unchanged and returns the result of image processing filter as new image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.BaseTransformationFilter.CalculateNewImageSize(), AForge.Imaging.Filters.BaseTransformationFilter.CheckSourceFormat(), AForge.Imaging.UnmanagedImage.Create(), AForge.Imaging.Filters.BaseTransformationFilter.FormatTranslations, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.Filters.BaseTransformationFilter.ProcessFilter(), and AForge.Imaging.Size.
Apply() [4/4]
void AForge.Imaging.Filters.BaseTransformationFilter.Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage) inline
Apply filter to an image in unmanaged memory.
Parameters
sourceImage Source image in unmanaged memory to apply filter to.
destinationImage Destination image in unmanaged memory to put result into.
The method keeps the source image unchanged and puts result of image processing into destination image.
<note>The destination image must have the same width and height as source image. Also destination image must have pixel format, which is expected by particular filter (see FormatTranslations property for information about pixel format conversions).</note>
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
InvalidImagePropertiesException Incorrect destination pixel format.
InvalidImagePropertiesException Destination image has wrong width and/or height.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.BaseTransformationFilter.CalculateNewImageSize(), AForge.Imaging.Filters.BaseTransformationFilter.CheckSourceFormat(), AForge.Imaging.Filters.BaseTransformationFilter.FormatTranslations, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.Filters.BaseTransformationFilter.ProcessFilter(), AForge.Imaging.Size, and AForge.Imaging.UnmanagedImage.Width.
CalculateNewImageSize()
abstract System.Drawing.Size AForge.Imaging.Filters.BaseTransformationFilter.CalculateNewImageSize (UnmanagedImage sourceData) protected pure virtual
Calculates new image size.
Parameters
sourceData Source image data.
Returns
New image size - size of the destination image.
Implemented in AForge.Imaging.Filters.SimpleQuadrilateralTransformation, AForge.Imaging.Filters.QuadrilateralTransformation, AForge.Imaging.Filters.TransformToPolar, AForge.Imaging.Filters.TransformFromPolar, AForge.Imaging.Filters.QuadrilateralTransformationBilinear, AForge.Imaging.Filters.QuadrilateralTransformationNearestNeighbor, AForge.Imaging.Filters.BaseRotateFilter, AForge.Imaging.Filters.Shrink, AForge.Imaging.Filters.Crop, and AForge.Imaging.Filters.BaseResizeFilter.
Referenced by AForge.Imaging.Filters.BaseTransformationFilter.Apply().
ProcessFilter()
abstract unsafe void AForge.Imaging.Filters.BaseTransformationFilter.ProcessFilter (UnmanagedImage sourceData, UnmanagedImage destinationData) protected pure virtual
Process the filter on the specified image.
Parameters
sourceData Source image data.
destinationData Destination image data.
Implemented in AForge.Imaging.Filters.SimpleQuadrilateralTransformation, AForge.Imaging.Filters.QuadrilateralTransformation, AForge.Imaging.Filters.TransformToPolar, AForge.Imaging.Filters.TransformFromPolar, AForge.Imaging.Filters.Shrink, AForge.Imaging.Filters.QuadrilateralTransformationBilinear, AForge.Imaging.Filters.QuadrilateralTransformationNearestNeighbor, AForge.Imaging.Filters.Crop, AForge.Imaging.Filters.RotateBicubic, AForge.Imaging.Filters.RotateNearestNeighbor, AForge.Imaging.Filters.RotateBilinear, AForge.Imaging.Filters.ResizeNearestNeighbor, AForge.Imaging.Filters.ResizeBicubic, and AForge.Imaging.Filters.ResizeBilinear.
Referenced by AForge.Imaging.Filters.BaseTransformationFilter.Apply().
CheckSourceFormat()
void AForge.Imaging.Filters.BaseTransformationFilter.CheckSourceFormat (PixelFormat pixelFormat) inline private
References AForge.Imaging.Filters.BaseTransformationFilter.FormatTranslations.
Referenced by AForge.Imaging.Filters.BaseTransformationFilter.Apply().
Property Documentation
FormatTranslations
abstract Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.BaseTransformationFilter.FormatTranslations get
Format translations dictionary.
The dictionary defines, which pixel formats are supported for source images and which pixel format will be used for resulting image.
See IFilterInformation.FormatTranslations for more information.
Referenced by AForge.Imaging.Filters.BaseTransformationFilter.Apply(), and AForge.Imaging.Filters.BaseTransformationFilter.CheckSourceFormat().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Base classes/BaseTransformationFilter.cs