Doc: IGLib EXTENDED: AForge.Fuzzy.Rule Class Reference
AForge.Fuzzy.Rule Class Reference
This class represents a Fuzzy Rule, a linguistic expression representing some behavioral aspect of a Fuzzy Inference System.
Public Member Functions
Rule (Database fuzzyDatabase, string name, string rule, INorm normOperator, ICoNorm coNormOperator)
Initializes a new instance of the Rule class.
Rule (Database fuzzyDatabase, string name, string rule)
Initializes a new instance of the Rule class using as CoNorm the MaximumCoNorm and as Norm the MinimumNorm.
string GetRPNExpression ()
Converts the RPN fuzzy expression into a string representation.
float EvaluateFiringStrength ()
Evaluates the firing strength of the Rule, the degree of confidence that the consequent of this Rule must be executed.
Properties
string Name [get, set]
The name of the fuzzy rule.
Clause Output [get]
The fuzzy Clause that represents the consequent of the Rule.
Private Member Functions
int Priority (string Operator)
Defines the priority of the fuzzy operators.
void ParseRule ()
Converts the Fuzzy Rule to RPN (Reverse Polish Notation). For debug proposes, the string representation of the RPN expression can be acessed by calling GetRPNExpression method.
string[] GetRuleTokens (string rule)
Performs a preprocessing on the rule, placing unary operators in proper position and breaking the string space separated tokens.
Private Attributes
string name
string rule
List< object > rpnTokenList
Clause output
Database database
INorm normOperator
ICoNorm conormOperator
IUnaryOperator notOperator
string unaryOperators = "NOT;VERY"
Detailed Description
This class represents a Fuzzy Rule, a linguistic expression representing some behavioral aspect of a Fuzzy Inference System.
A Fuzzy Rule is a fuzzy linguistic instruction that can be executed by a fuzzy system. The format of the Fuzzy Rule is:
IF antecedent THEN consequent
The antecedent is composed by a set of fuzzy clauses (see Clause) connected by fuzzy operations, like AND or OR. The operator NOT can be used to negate expressions:
...Clause1 AND (Clause2 OR Clause3) AND NOT Clause4 ...
Fuzzy clauses are written in form Variable IS Value. The NOT operator can be used to negate linguistic values as well:
...Variable1 IS Value1 AND Variable2 IS NOT Value2 ...
The consequent is a single of fuzzy clauses (Clause). To perform the linguistic computing, the Rule evaluates the clauses and then applies the fuzzy operators. Once this is done a value representing the confidence in the antecedent being true is obtained, and this is called firing strength of the Rule.
The firing strength is used to discover with how much confidence the consequent of a rule is true.
Sample usage:
// create the linguistic labels (fuzzy sets) that compose the temperature
TrapezoidalFunction function1 = new TrapezoidalFunction(
    10, 15, TrapezoidalFunction.EdgeType.Right );
FuzzySet fsCold = new FuzzySet("Cold", function1);
TrapezoidalFunction function2 = new TrapezoidalFunction(10, 15, 20, 25);
FuzzySet fsCool = new FuzzySet("Cool", function2);
TrapezoidalFunction function3 = new TrapezoidalFunction(20, 25, 30, 35);
FuzzySet fsWarm = new FuzzySet("Warm", function3);
TrapezoidalFunction function4 = new TrapezoidalFunction(
    30, 35, TrapezoidalFunction.EdgeType.Left );
FuzzySet fsHot = new FuzzySet("Hot", function4);
// create a linguistic variable to represent steel temperature
LinguisticVariable lvSteel = new LinguisticVariable("Steel", 0, 80);
// adding labels to the variable
lvSteel.AddLabel(fsCold);
lvSteel.AddLabel(fsCool);
lvSteel.AddLabel(fsWarm);
lvSteel.AddLabel(fsHot);
// create a linguistic variable to represent stove temperature
LinguisticVariable lvStove = new LinguisticVariable("Stove", 0, 80);
// adding labels to the variable
lvStove.AddLabel(fsCold);
lvStove.AddLabel(fsCool);
lvStove.AddLabel(fsWarm);
lvStove.AddLabel(fsHot);
// create the linguistic labels (fuzzy sets) that compose the pressure
TrapezoidalFunction function5 = new TrapezoidalFunction(
    20, 40, TrapezoidalFunction.EdgeType.Right );
FuzzySet fsLow = new FuzzySet("Low", function5);
TrapezoidalFunction function6 = new TrapezoidalFunction(20, 40, 60, 80);
FuzzySet fsMedium = new FuzzySet("Medium", function6);
TrapezoidalFunction function7 = new TrapezoidalFunction(
    60, 80, TrapezoidalFunction.EdgeType.Left );
FuzzySet fsHigh = new FuzzySet("High", function7);
// create a linguistic variable to represent pressure
LinguisticVariable lvPressure = new LinguisticVariable("Pressure", 0, 100);
// adding labels to the variable
lvPressure.AddLabel(fsLow);
lvPressure.AddLabel(fsMedium);
lvPressure.AddLabel(fsHigh);
// create a linguistic variable database
Database db = new Database();
db.AddVariable(lvSteel);
db.AddVariable(lvStove);
db.AddVariable(lvPressure);
// sample rules just to test the expression parsing
Rule r1 = new Rule(db, "Test1", "IF Steel is not Cold and Stove is Hot then Pressure is Low");
Rule r2 = new Rule(db, "Test2", "IF Steel is Cold and not (Stove is Warm or Stove is Hot) then Pressure is Medium");
Rule r3 = new Rule(db, "Test3", "IF Steel is Cold and Stove is Warm or Stove is Hot then Pressure is High");
// testing the firing strength
lvSteel.NumericInput = 12;
lvStove.NumericInput = 35;
float result = r1.EvaluateFiringStrength();
Console.WriteLine(result.ToString());
Constructor & Destructor Documentation
Rule() [1/2]
AForge.Fuzzy.Rule.Rule (Database fuzzyDatabase, string name, string rule, INorm normOperator, ICoNorm coNormOperator) inline
Initializes a new instance of the Rule class.
Parameters
fuzzyDatabase A fuzzy Database containig the linguistic variables (see LinguisticVariable) that will be used in the Rule.
Parameters
name Name of this Rule.
Parameters
rule A string representing the Rule. It must be a "IF..THEN" statement. For a more detailed description see Rule class.
Parameters
normOperator A class that implements a INorm interface to evaluate the AND operations of the Rule.
Parameters
coNormOperator A class that implements a ICoNorm interface to evaluate the OR operations of the Rule.
References AForge.Fuzzy.Rule.name, AForge.Fuzzy.Rule.normOperator, AForge.Fuzzy.Rule.ParseRule(), AForge.Fuzzy.Rule.rpnTokenList, and AForge.Fuzzy.Rule.rule.
Rule() [2/2]
AForge.Fuzzy.Rule.Rule (Database fuzzyDatabase, string name, string rule) inline
Initializes a new instance of the Rule class using as CoNorm the MaximumCoNorm and as Norm the MinimumNorm.
Parameters
fuzzyDatabase A fuzzy Database containig the linguistic variables (see LinguisticVariable) that will be used in the Rule.
Parameters
name Name of this Rule.
Parameters
rule A string representing the Rule. It must be a "IF..THEN" statement. For a more detailed description see Rule class.
Member Function Documentation
GetRPNExpression()
string AForge.Fuzzy.Rule.GetRPNExpression () inline
Converts the RPN fuzzy expression into a string representation.
Returns
String representation of the RPN fuzzy expression.
References AForge.Fuzzy.Rule.rpnTokenList.
Priority()
int AForge.Fuzzy.Rule.Priority (string Operator) inline private
Defines the priority of the fuzzy operators.
Parameters
Operator A fuzzy operator or openning parenthesis.
Returns
A number indicating the priority of the operator, and zero for openning parenthesis.
References AForge.Fuzzy.Rule.unaryOperators.
Referenced by AForge.Fuzzy.Rule.ParseRule().
ParseRule()
void AForge.Fuzzy.Rule.ParseRule () inline private
Converts the Fuzzy Rule to RPN (Reverse Polish Notation). For debug proposes, the string representation of the RPN expression can be acessed by calling GetRPNExpression method.
References AForge.Fuzzy.Rule.database, AForge.Fuzzy.LinguisticVariable.GetLabel(), AForge.Fuzzy.Rule.GetRuleTokens(), AForge.Fuzzy.Database.GetVariable(), AForge.Fuzzy.LinguisticVariable.Name, AForge.Fuzzy.Rule.output, AForge.Fuzzy.Rule.Priority(), AForge.Fuzzy.Rule.rpnTokenList, AForge.Fuzzy.Rule.rule, and AForge.Fuzzy.Rule.unaryOperators.
Referenced by AForge.Fuzzy.Rule.Rule().
GetRuleTokens()
string [] AForge.Fuzzy.Rule.GetRuleTokens (string rule) inline private
Performs a preprocessing on the rule, placing unary operators in proper position and breaking the string space separated tokens.
Parameters
rule Rule in string format.
Returns
An array of strings with tokens of the rule.
References AForge.Fuzzy.Rule.rule, and AForge.Fuzzy.Rule.unaryOperators.
Referenced by AForge.Fuzzy.Rule.ParseRule().
EvaluateFiringStrength()
float AForge.Fuzzy.Rule.EvaluateFiringStrength () inline
Evaluates the firing strength of the Rule, the degree of confidence that the consequent of this Rule must be executed.
Returns
The firing strength [0..1] of the Rule.
References AForge.Fuzzy.Rule.conormOperator, AForge.Fuzzy.IUnaryOperator.Evaluate(), AForge.Fuzzy.INorm.Evaluate(), AForge.Fuzzy.ICoNorm.Evaluate(), AForge.Fuzzy.Rule.normOperator, AForge.Fuzzy.Rule.notOperator, AForge.Fuzzy.Rule.rpnTokenList, and AForge.Fuzzy.Rule.unaryOperators.
Referenced by AForge.Fuzzy.InferenceSystem.ExecuteInference().
Member Data Documentation
name
string AForge.Fuzzy.Rule.name private
Referenced by AForge.Fuzzy.Rule.Rule().
rule
string AForge.Fuzzy.Rule.rule private
Referenced by AForge.Fuzzy.Rule.GetRuleTokens(), AForge.Fuzzy.Rule.ParseRule(), and AForge.Fuzzy.Rule.Rule().
rpnTokenList
List<object> AForge.Fuzzy.Rule.rpnTokenList private
Referenced by AForge.Fuzzy.Rule.EvaluateFiringStrength(), AForge.Fuzzy.Rule.GetRPNExpression(), AForge.Fuzzy.Rule.ParseRule(), and AForge.Fuzzy.Rule.Rule().
output
Clause AForge.Fuzzy.Rule.output private
Referenced by AForge.Fuzzy.Rule.ParseRule().
database
Database AForge.Fuzzy.Rule.database private
Referenced by AForge.Fuzzy.Rule.ParseRule().
normOperator
INorm AForge.Fuzzy.Rule.normOperator private
Referenced by AForge.Fuzzy.Rule.EvaluateFiringStrength(), and AForge.Fuzzy.Rule.Rule().
conormOperator
ICoNorm AForge.Fuzzy.Rule.conormOperator private
Referenced by AForge.Fuzzy.Rule.EvaluateFiringStrength().
notOperator
IUnaryOperator AForge.Fuzzy.Rule.notOperator private
Referenced by AForge.Fuzzy.Rule.EvaluateFiringStrength().
unaryOperators
string AForge.Fuzzy.Rule.unaryOperators = "NOT;VERY" private
Referenced by AForge.Fuzzy.Rule.EvaluateFiringStrength(), AForge.Fuzzy.Rule.GetRuleTokens(), AForge.Fuzzy.Rule.ParseRule(), and AForge.Fuzzy.Rule.Priority().
Property Documentation
Name
string AForge.Fuzzy.Rule.Name get set
The name of the fuzzy rule.
Referenced by AForge.Fuzzy.Rulebase.AddRule().
Output
Clause AForge.Fuzzy.Rule.Output get
The fuzzy Clause that represents the consequent of the Rule.
Referenced by AForge.Fuzzy.InferenceSystem.ExecuteInference().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Fuzzy/Rule.cs