Doc: IGLib EXTENDED: NUnit.Framework.Internal.PlatformDetectionTests Class Reference
NUnit.Framework.Internal.PlatformDetectionTests Class Reference
Summary description for PlatformHelperTests.
Public Member Functions
void DetectWin95 ()
void DetectWin98 ()
void DetectWinMe ()
void DetectWinCE ()
void DetectNT3 ()
void DetectNT4 ()
void DetectWin2K ()
void DetectWinXP ()
void DetectWinXPProfessionalX64 ()
void DetectWin2003Server ()
void DetectVista ()
void DetectWin2008ServerOriginal ()
void DetectWin2008ServerR2 ()
void DetectWindows7 ()
void DetectWindows2012ServerOriginal ()
void DetectWindows2012ServerR2 ()
void DetectWindows8 ()
void DetectWindows81 ()
void DetectWindows10 ()
void DetectWindowsServer ()
void DetectUnixUnderMicrosoftDotNet ()
void DetectUnixUnderMono ()
void DetectXbox ()
void DetectMacOSX ()
void DetectNet10 ()
void DetectNet11 ()
void DetectNet20 ()
void DetectNet30 ()
void DetectNet35 ()
void DetectNet40 ()
void DetectNetCF ()
void DetectSSCLI ()
void DetectMono10 ()
void DetectMono20 ()
void DetectMono30 ()
void DetectMono35 ()
void DetectMono40 ()
void DetectMonoTouch ()
void DetectSilverlight30 ()
void DetectSilverlight40 ()
void DetectSilverlight50 ()
void DetectExactVersion ()
void ArrayOfPlatforms ()
void PlatformAttribute_Include ()
void PlatformAttribute_Exclude ()
void PlatformAttribute_IncludeAndExclude ()
void PlatformAttribute_InvalidPlatform ()
void PlatformAttribute_ProcessBitNess ()
Private Member Functions
void CheckOSPlatforms (OSPlatform os, string expectedPlatforms)
void CheckRuntimePlatforms (RuntimeFramework runtimeFramework, string expectedPlatforms)
void CheckPlatforms (PlatformHelper helper, string expectedPlatforms, string checkPlatforms)
Static Private Attributes
static readonly PlatformHelper win95Helper
static readonly PlatformHelper winXPHelper
Detailed Description
Summary description for PlatformHelperTests.
Member Function Documentation
CheckOSPlatforms()
void NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms (OSPlatform os, string expectedPlatforms) inline private
References NUnit.Framework.Internal.PlatformDetectionTests.CheckPlatforms(), NUnit.Framework.Internal.RuntimeFramework.CurrentFramework, NUnit.Framework.Internal.PlatformHelper.OSPlatforms, NUnit.Framework.Is.SubsetOf(), and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Internal.PlatformDetectionTests.DetectMacOSX(), NUnit.Framework.Internal.PlatformDetectionTests.DetectNT3(), NUnit.Framework.Internal.PlatformDetectionTests.DetectNT4(), NUnit.Framework.Internal.PlatformDetectionTests.DetectUnixUnderMicrosoftDotNet(), NUnit.Framework.Internal.PlatformDetectionTests.DetectUnixUnderMono(), NUnit.Framework.Internal.PlatformDetectionTests.DetectVista(), NUnit.Framework.Internal.PlatformDetectionTests.DetectWin2003Server(), NUnit.Framework.Internal.PlatformDetectionTests.DetectWin2008ServerOriginal(), NUnit.Framework.Internal.PlatformDetectionTests.DetectWin2008ServerR2(), NUnit.Framework.Internal.PlatformDetectionTests.DetectWin2K(), NUnit.Framework.Internal.PlatformDetectionTests.DetectWin95(), NUnit.Framework.Internal.PlatformDetectionTests.DetectWin98(), NUnit.Framework.Internal.PlatformDetectionTests.DetectWinCE(), NUnit.Framework.Internal.PlatformDetectionTests.DetectWindows10(), NUnit.Framework.Internal.PlatformDetectionTests.DetectWindows2012ServerOriginal(), NUnit.Framework.Internal.PlatformDetectionTests.DetectWindows2012ServerR2(), NUnit.Framework.Internal.PlatformDetectionTests.DetectWindows7(), NUnit.Framework.Internal.PlatformDetectionTests.DetectWindows8(), NUnit.Framework.Internal.PlatformDetectionTests.DetectWindows81(), NUnit.Framework.Internal.PlatformDetectionTests.DetectWindowsServer(), NUnit.Framework.Internal.PlatformDetectionTests.DetectWinMe(), NUnit.Framework.Internal.PlatformDetectionTests.DetectWinXP(), NUnit.Framework.Internal.PlatformDetectionTests.DetectWinXPProfessionalX64(), and NUnit.Framework.Internal.PlatformDetectionTests.DetectXbox().
CheckRuntimePlatforms()
void NUnit.Framework.Internal.PlatformDetectionTests.CheckRuntimePlatforms (RuntimeFramework runtimeFramework, string expectedPlatforms) inline private
References NUnit.Framework.Internal.PlatformDetectionTests.CheckPlatforms(), NUnit.Framework.Internal.OSPlatform.CurrentPlatform, and NUnit.Framework.Internal.PlatformHelper.RuntimePlatforms.
Referenced by NUnit.Framework.Internal.PlatformDetectionTests.DetectMono10(), NUnit.Framework.Internal.PlatformDetectionTests.DetectMono20(), NUnit.Framework.Internal.PlatformDetectionTests.DetectMono30(), NUnit.Framework.Internal.PlatformDetectionTests.DetectMono35(), NUnit.Framework.Internal.PlatformDetectionTests.DetectMono40(), NUnit.Framework.Internal.PlatformDetectionTests.DetectMonoTouch(), NUnit.Framework.Internal.PlatformDetectionTests.DetectNet10(), NUnit.Framework.Internal.PlatformDetectionTests.DetectNet11(), NUnit.Framework.Internal.PlatformDetectionTests.DetectNet20(), NUnit.Framework.Internal.PlatformDetectionTests.DetectNet30(), NUnit.Framework.Internal.PlatformDetectionTests.DetectNet35(), NUnit.Framework.Internal.PlatformDetectionTests.DetectNet40(), NUnit.Framework.Internal.PlatformDetectionTests.DetectNetCF(), NUnit.Framework.Internal.PlatformDetectionTests.DetectSilverlight30(), NUnit.Framework.Internal.PlatformDetectionTests.DetectSilverlight40(), NUnit.Framework.Internal.PlatformDetectionTests.DetectSilverlight50(), and NUnit.Framework.Internal.PlatformDetectionTests.DetectSSCLI().
CheckPlatforms()
void NUnit.Framework.Internal.PlatformDetectionTests.CheckPlatforms (PlatformHelper helper, string expectedPlatforms, string checkPlatforms) inline private
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.Fail().
Referenced by NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms(), and NUnit.Framework.Internal.PlatformDetectionTests.CheckRuntimePlatforms().
DetectWin95()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectWin95 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectWin98()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectWin98 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectWinMe()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectWinMe () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectWinCE()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectWinCE () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectNT3()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectNT3 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectNT4()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectNT4 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectWin2K()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectWin2K () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectWinXP()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectWinXP () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectWinXPProfessionalX64()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectWinXPProfessionalX64 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectWin2003Server()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectWin2003Server () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectVista()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectVista () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectWin2008ServerOriginal()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectWin2008ServerOriginal () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectWin2008ServerR2()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectWin2008ServerR2 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectWindows7()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectWindows7 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectWindows2012ServerOriginal()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectWindows2012ServerOriginal () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectWindows2012ServerR2()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectWindows2012ServerR2 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectWindows8()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectWindows8 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectWindows81()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectWindows81 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectWindows10()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectWindows10 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectWindowsServer()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectWindowsServer () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectUnixUnderMicrosoftDotNet()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectUnixUnderMicrosoftDotNet () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms(), and NUnit.Framework.Internal.OSPlatform.UnixPlatformID_Microsoft.
DetectUnixUnderMono()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectUnixUnderMono () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms(), and NUnit.Framework.Internal.OSPlatform.UnixPlatformID_Mono.
DetectXbox()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectXbox () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectMacOSX()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectMacOSX () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckOSPlatforms().
DetectNet10()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectNet10 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckRuntimePlatforms().
DetectNet11()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectNet11 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckRuntimePlatforms().
DetectNet20()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectNet20 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckRuntimePlatforms().
DetectNet30()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectNet30 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckRuntimePlatforms().
DetectNet35()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectNet35 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckRuntimePlatforms().
DetectNet40()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectNet40 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckRuntimePlatforms().
DetectNetCF()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectNetCF () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckRuntimePlatforms().
DetectSSCLI()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectSSCLI () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckRuntimePlatforms().
DetectMono10()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectMono10 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckRuntimePlatforms().
DetectMono20()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectMono20 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckRuntimePlatforms().
DetectMono30()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectMono30 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckRuntimePlatforms().
DetectMono35()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectMono35 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckRuntimePlatforms().
DetectMono40()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectMono40 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckRuntimePlatforms().
DetectMonoTouch()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectMonoTouch () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckRuntimePlatforms().
DetectSilverlight30()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectSilverlight30 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckRuntimePlatforms().
DetectSilverlight40()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectSilverlight40 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckRuntimePlatforms().
DetectSilverlight50()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectSilverlight50 () inline
References NUnit.Framework.Internal.PlatformDetectionTests.CheckRuntimePlatforms().
DetectExactVersion()
void NUnit.Framework.Internal.PlatformDetectionTests.DetectExactVersion () inline
References NUnit.Framework.Assert.IsFalse(), NUnit.Framework.Internal.PlatformHelper.IsPlatformSupported(), NUnit.Framework.Assert.IsTrue(), and NUnit.Framework.Internal.PlatformDetectionTests.winXPHelper.
ArrayOfPlatforms()
void NUnit.Framework.Internal.PlatformDetectionTests.ArrayOfPlatforms () inline
References NUnit.Framework.Assert.IsFalse(), NUnit.Framework.Internal.PlatformHelper.IsPlatformSupported(), NUnit.Framework.Assert.IsTrue(), NUnit.Framework.Internal.PlatformDetectionTests.win95Helper, and NUnit.Framework.Internal.PlatformDetectionTests.winXPHelper.
PlatformAttribute_Include()
void NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_Include () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Assert.IsFalse(), NUnit.Framework.Internal.PlatformHelper.IsPlatformSupported(), NUnit.Framework.Assert.IsTrue(), NUnit.Framework.Internal.PlatformHelper.Reason, NUnit.Framework.Internal.PlatformDetectionTests.win95Helper, and NUnit.Framework.Internal.PlatformDetectionTests.winXPHelper.
PlatformAttribute_Exclude()
void NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_Exclude () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.IncludeExcludeAttribute.Exclude, NUnit.Framework.Assert.IsFalse(), NUnit.Framework.Internal.PlatformHelper.IsPlatformSupported(), NUnit.Framework.Assert.IsTrue(), NUnit.Framework.Internal.PlatformHelper.Reason, NUnit.Framework.Internal.PlatformDetectionTests.win95Helper, and NUnit.Framework.Internal.PlatformDetectionTests.winXPHelper.
PlatformAttribute_IncludeAndExclude()
void NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_IncludeAndExclude () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.IncludeExcludeAttribute.Exclude, NUnit.Framework.Assert.IsFalse(), NUnit.Framework.Internal.PlatformHelper.IsPlatformSupported(), NUnit.Framework.Assert.IsTrue(), NUnit.Framework.Internal.PlatformHelper.Reason, NUnit.Framework.Internal.PlatformDetectionTests.win95Helper, and NUnit.Framework.Internal.PlatformDetectionTests.winXPHelper.
PlatformAttribute_InvalidPlatform()
void NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_InvalidPlatform () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Assert.IsFalse(), NUnit.Framework.Internal.PlatformHelper.IsPlatformSupported(), NUnit.Framework.Internal.PlatformHelper.Reason, NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Internal.PlatformDetectionTests.winXPHelper.
PlatformAttribute_ProcessBitNess()
void NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_ProcessBitNess () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.False(), NUnit.Framework.Internal.PlatformHelper.IsPlatformSupported(), and NUnit.Framework.Assert.That().
Member Data Documentation
win95Helper
readonly PlatformHelper NUnit.Framework.Internal.PlatformDetectionTests.win95Helper static private
Initial value:
= new PlatformHelper(
            new OSPlatform( PlatformID.Win32Windows , new Version( 4, 0 ) ),
            new RuntimeFramework( RuntimeType.Net, new Version( 1, 1, 4322, 0 ) ) )
Referenced by NUnit.Framework.Internal.PlatformDetectionTests.ArrayOfPlatforms(), NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_Exclude(), NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_Include(), and NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_IncludeAndExclude().
winXPHelper
readonly PlatformHelper NUnit.Framework.Internal.PlatformDetectionTests.winXPHelper static private
Initial value:
= new PlatformHelper(
            new OSPlatform( PlatformID.Win32NT , new Version( 5,1 ) ),
            new RuntimeFramework( RuntimeType.Net, new Version( 1, 1, 4322, 0 ) ) )
Referenced by NUnit.Framework.Internal.PlatformDetectionTests.ArrayOfPlatforms(), NUnit.Framework.Internal.PlatformDetectionTests.DetectExactVersion(), NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_Exclude(), NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_Include(), NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_IncludeAndExclude(), and NUnit.Framework.Internal.PlatformDetectionTests.PlatformAttribute_InvalidPlatform().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/PlatformDetectionTests.cs