Doc: IGLib EXTENDED: CalcWebService.localhost.Service1 Class Reference
CalcWebService.localhost.Service1 Class Reference
Public Member Functions
Service1 ()
double Add (int a, int b, int c)
void AddAsync (int a, int b, int c)
void AddAsync (int a, int b, int c, object userState)
new void CancelAsync (object userState)
Service1 ()
double Add (int a, int b, int c)
void AddAsync (int a, int b, int c)
void AddAsync (int a, int b, int c, object userState)
new void CancelAsync (object userState)
Properties
new string Url [get, set]
new bool UseDefaultCredentials [get, set]
Events
AddCompletedEventHandler AddCompleted
Private Member Functions
void OnAddOperationCompleted (object arg)
bool IsLocalFileSystemWebService (string url)
void OnAddOperationCompleted (object arg)
bool IsLocalFileSystemWebService (string url)
Private Attributes
System.Threading.SendOrPostCallback AddOperationCompleted
bool useDefaultCredentialsSetExplicitly
Detailed Description
Constructor & Destructor Documentation
Service1() [1/2]
CalcWebService.localhost.Service1.Service1 () inline
References CalcWebService.localhost.Service1.IsLocalFileSystemWebService(), CalcWebService.localhost.Service1.Url, and CalcWebService.localhost.Service1.UseDefaultCredentials.
Service1() [2/2]
CalcWebService.localhost.Service1.Service1 () inline
References CalcWebService.localhost.Service1.IsLocalFileSystemWebService(), CalcWebService.localhost.Service1.Url, and CalcWebService.localhost.Service1.UseDefaultCredentials.
Member Function Documentation
Add() [1/2]
double CalcWebService.localhost.Service1.Add (int a, int b, int c) inline
Referenced by CalcWebService.AddData.btnAdd_Click().
AddAsync() [1/4]
void CalcWebService.localhost.Service1.AddAsync (int a, int b, int c) inline
Referenced by CalcWebService.localhost.Service1.AddAsync().
AddAsync() [2/4]
void CalcWebService.localhost.Service1.AddAsync (int a, int b, int c, object userState) inline
References CalcWebService.localhost.Service1.AddOperationCompleted, and CalcWebService.localhost.Service1.OnAddOperationCompleted().
OnAddOperationCompleted() [1/2]
void CalcWebService.localhost.Service1.OnAddOperationCompleted (object arg) inline private
References CalcWebService.localhost.Service1.AddCompleted.
Referenced by CalcWebService.localhost.Service1.AddAsync().
CancelAsync() [1/2]
new void CalcWebService.localhost.Service1.CancelAsync (object userState) inline
IsLocalFileSystemWebService() [1/2]
bool CalcWebService.localhost.Service1.IsLocalFileSystemWebService (string url) inline private
Referenced by CalcWebService.localhost.Service1.Service1().
Add() [2/2]
double CalcWebService.localhost.Service1.Add (int a, int b, int c) inline
AddAsync() [3/4]
void CalcWebService.localhost.Service1.AddAsync (int a, int b, int c) inline
References CalcWebService.localhost.Service1.AddAsync().
AddAsync() [4/4]
void CalcWebService.localhost.Service1.AddAsync (int a, int b, int c, object userState) inline
References CalcWebService.localhost.Service1.AddOperationCompleted, and CalcWebService.localhost.Service1.OnAddOperationCompleted().
OnAddOperationCompleted() [2/2]
void CalcWebService.localhost.Service1.OnAddOperationCompleted (object arg) inline private
References CalcWebService.localhost.Service1.AddCompleted.
CancelAsync() [2/2]
new void CalcWebService.localhost.Service1.CancelAsync (object userState) inline
IsLocalFileSystemWebService() [2/2]
bool CalcWebService.localhost.Service1.IsLocalFileSystemWebService (string url) inline private
Member Data Documentation
AddOperationCompleted
System Threading SendOrPostCallback CalcWebService.localhost.Service1.AddOperationCompleted private
Referenced by CalcWebService.localhost.Service1.AddAsync().
useDefaultCredentialsSetExplicitly
bool CalcWebService.localhost.Service1.useDefaultCredentialsSetExplicitly private
Property Documentation
Url
new string CalcWebService.localhost.Service1.Url get set
Referenced by CalcWebService.localhost.Service1.Service1().
UseDefaultCredentials
new bool CalcWebService.localhost.Service1.UseDefaultCredentials get set
Referenced by CalcWebService.localhost.Service1.Service1().
Event Documentation
AddCompleted
AddCompletedEventHandler CalcWebService.localhost.Service1.AddCompleted
Referenced by CalcWebService.localhost.Service1.OnAddOperationCompleted().
The documentation for this class was generated from the following file:
igtest/ws_templates/CalcWebService/Backup/CalcWebService/Web References/localhost/Reference.cs