Doc: IGLib EXTENDED: Meta.Numerics.Matrices.RectangularMatrix Class Reference
Meta.Numerics.Matrices.RectangularMatrix Class Reference
A rectangular matrix of real numbers.
Public Member Functions
RectangularMatrix (int rowCount, int columnCount)
Initializes a rectangular matrix with the given dimensions.
RectangularMatrix (double[,] source)
Initializes a rectangular matrix from the given 2D array.
override double OneNorm ()
Computes the 1-norm of the matrix.
override double InfinityNorm ()
Computes the &#x221E;-norm of the matrix.
override ColumnVector Column (int c)
Gets a copy of the specified column.
override RowVector Row (int r)
Gets a copy of the specified row.
RectangularMatrix Copy ()
Copies the matrix.
RectangularMatrix Transpose ()
Returns the transpose of the matrix.
QRDecomposition QRDecomposition ()
Computes the QR decomposition of the matrix.
SingularValueDecomposition SingularValueDecomposition ()
Computes the singular value decomposition of the matrix.
Public Member Functions inherited from Meta.Numerics.Matrices.AnyRectangularMatrix
virtual double FrobeniusNorm ()
Computes the Frobenius-norm of the matrix.
virtual SymmetricMatrix MultiplySelfByTranspose ()
Computes the product of the matrix and its transpose.
virtual SymmetricMatrix MultiplyTransposeBySelf ()
Computes the product of the matrix's transpose and itself.
bool Equals (AnyRectangularMatrix other)
Determines whether the given matrix equals the current matrix.
override bool Equals (object obj)
Determines whether the given object is an equal matrix.
override int GetHashCode ()
Not a valid operation.
Public Member Functions inherited from Meta.Numerics.Matrices.AnyMatrix< double >
virtual void Fill (Func< int, int, T > f)
Sets all matrix entries according to a supplied fill function.
virtual T[,] ToArray ()
Copies the matrix into an array.
Static Public Member Functions
static RectangularMatrix operator+ (RectangularMatrix A, RectangularMatrix B)
Adds two real, rectangular matrices.
static RectangularMatrix operator- (RectangularMatrix A, RectangularMatrix B)
Subtracts two real, rectangular matrices.
static RectangularMatrix operator* (RectangularMatrix A, RectangularMatrix B)
Multiplies two real, rectangular matrices.
static RectangularMatrix operator* (double alpha, RectangularMatrix A)
Multiply a real, rectangular matrix by a real constant.
static RectangularMatrix operator* (RectangularMatrix A, double alpha)
Divides a real, rectangular matrix by a real constant.
static RectangularMatrix operator- (RectangularMatrix A)
Negates a real, rectangular matrix.
static ColumnVector operator* (RectangularMatrix A, ColumnVector v)
Computes the product of a rectangular matrix and a column vector.
static operator SquareMatrix (RectangularMatrix A)
Casts a rectangular matrix to a square matrix.
Static Public Member Functions inherited from Meta.Numerics.Matrices.AnyRectangularMatrix
static RectangularMatrix operator+ (AnyRectangularMatrix A, AnyRectangularMatrix B)
Adds any two real, rectangular matrices.
static RectangularMatrix operator- (AnyRectangularMatrix A, AnyRectangularMatrix B)
Subtracts any two real, rectangular matrices.
static RectangularMatrix operator* (AnyRectangularMatrix A, AnyRectangularMatrix B)
Multiplies any two real, rectangular matrices.
static RectangularMatrix operator* (double alpha, AnyRectangularMatrix A)
Multiplies any real, rectangular matrix by a real constant.
static ColumnVector operator* (AnyRectangularMatrix A, ColumnVector v)
Multiplies any real, rectangular matrix with a real column vector.
static bool operator== (AnyRectangularMatrix A, AnyRectangularMatrix B)
Determines whether two matrices are equal.
static bool operator!= (AnyRectangularMatrix A, AnyRectangularMatrix B)
Determines whether two matrices are not equal.
Properties
override double this[int r, int c] [get, set]
override int RowCount [get]
override int ColumnCount [get]
Properties inherited from Meta.Numerics.Matrices.AnyMatrix< double >
abstract int RowCount [get]
Gets the number of matrix rows.
abstract int ColumnCount [get]
Gets the number of matrix columns.
abstract T this[int r, int c] [get, set]
Gets or sets the value of a matrix entry.
bool IsReadOnly [get, set]
Gets a flag indicating whether the matrix is read-only.
Private Attributes
readonly double[] store
readonly int rows
readonly int cols
Additional Inherited Members
Protected Member Functions inherited from Meta.Numerics.Matrices.AnyRectangularMatrix
AnyRectangularMatrix ()
Protected Member Functions inherited from Meta.Numerics.Matrices.AnyMatrix< double >
AnyMatrix ()
Detailed Description
A rectangular matrix of real numbers.
Constructor & Destructor Documentation
RectangularMatrix() [1/2]
Meta.Numerics.Matrices.RectangularMatrix.RectangularMatrix (int rowCount, int columnCount) inline
Initializes a rectangular matrix with the given dimensions.
Parameters
rowCount The number of rows.
columnCount The number of columns.
Exceptions
ArgumentOutOfRangeException rowCount or columnCount is less than one.
References Meta.Numerics.Matrices.RectangularMatrix.cols, Meta.Numerics.Matrices.RectangularMatrix.rows, and Meta.Numerics.Matrices.RectangularMatrix.store.
Referenced by Meta.Numerics.Matrices.RectangularMatrix.Copy(), Meta.Numerics.Matrices.RectangularMatrix.operator*(), Meta.Numerics.Matrices.RectangularMatrix.operator+(), Meta.Numerics.Matrices.RectangularMatrix.operator-(), and Meta.Numerics.Matrices.RectangularMatrix.Transpose().
RectangularMatrix() [2/2]
Meta.Numerics.Matrices.RectangularMatrix.RectangularMatrix (double source[,]) inline
Initializes a rectangular matrix from the given 2D array.
Parameters
source The source 2D array.
References Meta.Numerics.Matrices.RectangularMatrix.cols, Meta.Numerics.Matrices.RectangularMatrix.rows, and Meta.Numerics.Matrices.RectangularMatrix.store.
Member Function Documentation
OneNorm()
override double Meta.Numerics.Matrices.RectangularMatrix.OneNorm () inline virtual
Computes the 1-norm of the matrix.
Reimplemented from Meta.Numerics.Matrices.AnyRectangularMatrix.
References Meta.Numerics.Matrices.RectangularMatrix.cols, Meta.Numerics.Matrices.RectangularMatrix.rows, and Meta.Numerics.Matrices.RectangularMatrix.store.
InfinityNorm()
override double Meta.Numerics.Matrices.RectangularMatrix.InfinityNorm () inline virtual
Computes the &#x221E;-norm of the matrix.
Reimplemented from Meta.Numerics.Matrices.AnyRectangularMatrix.
References Meta.Numerics.Matrices.RectangularMatrix.cols, Meta.Numerics.Matrices.RectangularMatrix.rows, and Meta.Numerics.Matrices.RectangularMatrix.store.
Column()
override ColumnVector Meta.Numerics.Matrices.RectangularMatrix.Column (int c) inline virtual
Gets a copy of the specified column.
Reimplemented from Meta.Numerics.Matrices.AnyRectangularMatrix.
References Meta.Numerics.Matrices.RectangularMatrix.cols, Meta.Numerics.Matrices.RectangularMatrix.rows, and Meta.Numerics.Matrices.RectangularMatrix.store.
Row()
override RowVector Meta.Numerics.Matrices.RectangularMatrix.Row (int r) inline virtual
Gets a copy of the specified row.
Reimplemented from Meta.Numerics.Matrices.AnyRectangularMatrix.
References Meta.Numerics.Matrices.RectangularMatrix.cols, Meta.Numerics.Matrices.RectangularMatrix.rows, and Meta.Numerics.Matrices.RectangularMatrix.store.
operator+()
static RectangularMatrix Meta.Numerics.Matrices.RectangularMatrix.operator+ (RectangularMatrix A, RectangularMatrix B) inline static
Adds two real, rectangular matrices.
Parameters
A The first matrix.
B The second matrix.
Returns
The sum matrix A + B .
References Meta.Numerics.Matrices.RectangularMatrix.RectangularMatrix().
operator-() [1/2]
static RectangularMatrix Meta.Numerics.Matrices.RectangularMatrix.operator- (RectangularMatrix A, RectangularMatrix B) inline static
Subtracts two real, rectangular matrices.
Parameters
A The first matrix.
B The second matrix.
Returns
The sum matrix A - B .
References Meta.Numerics.Matrices.RectangularMatrix.RectangularMatrix().
operator*() [1/4]
static RectangularMatrix Meta.Numerics.Matrices.RectangularMatrix.operator* (RectangularMatrix A, RectangularMatrix B) inline static
Multiplies two real, rectangular matrices.
Parameters
A The first matrix.
B The second matrix.
Returns
The product matrix AB.
References Meta.Numerics.Matrices.RectangularMatrix.RectangularMatrix().
operator*() [2/4]
static RectangularMatrix Meta.Numerics.Matrices.RectangularMatrix.operator* (double alpha, RectangularMatrix A) inline static
Multiply a real, rectangular matrix by a real constant.
Parameters
alpha The constant.
A The matrix.
Returns
The product aA.
References Meta.Numerics.Matrices.RectangularMatrix.RectangularMatrix(), and Meta.Numerics.Matrices.RectangularMatrix.store.
operator*() [3/4]
static RectangularMatrix Meta.Numerics.Matrices.RectangularMatrix.operator* (RectangularMatrix A, double alpha) inline static
Divides a real, rectangular matrix by a real constant.
Parameters
A The matrix.
alpha The constant.
Returns
The quotient A/a.
References Meta.Numerics.Matrices.RectangularMatrix.RectangularMatrix(), and Meta.Numerics.Matrices.RectangularMatrix.store.
operator-() [2/2]
static RectangularMatrix Meta.Numerics.Matrices.RectangularMatrix.operator- (RectangularMatrix A) inline static
Negates a real, rectangular matrix.
Parameters
A The matrix.
Returns
The matrix -A.
References Meta.Numerics.Matrices.RectangularMatrix.RectangularMatrix(), and Meta.Numerics.Matrices.RectangularMatrix.store.
Copy()
RectangularMatrix Meta.Numerics.Matrices.RectangularMatrix.Copy () inline
Copies the matrix.
Returns
An indpendent copy of the matrix.
References Meta.Numerics.Matrices.RectangularMatrix.cols, Meta.Numerics.Matrices.RectangularMatrix.Copy(), Meta.Numerics.Matrices.RectangularMatrix.RectangularMatrix(), Meta.Numerics.Matrices.RectangularMatrix.rows, and Meta.Numerics.Matrices.RectangularMatrix.store.
Referenced by Meta.Numerics.Matrices.RectangularMatrix.Copy(), and Test.RectangularMatrixTest.RectangularMatrixAccess().
Transpose()
RectangularMatrix Meta.Numerics.Matrices.RectangularMatrix.Transpose () inline
Returns the transpose of the matrix.
Returns
MT
References Meta.Numerics.Matrices.RectangularMatrix.cols, Meta.Numerics.Matrices.RectangularMatrix.RectangularMatrix(), Meta.Numerics.Matrices.RectangularMatrix.rows, Meta.Numerics.Matrices.RectangularMatrix.store, and Meta.Numerics.Matrices.RectangularMatrix.Transpose().
Referenced by Test.RectangularMatrixTest.RectangularMatrixArithmetic(), and Meta.Numerics.Matrices.RectangularMatrix.Transpose().
QRDecomposition()
QRDecomposition Meta.Numerics.Matrices.RectangularMatrix.QRDecomposition () inline
Computes the QR decomposition of the matrix.
Returns
The QR decomposition of the matrix.
Only matrices with a number of rows greater than or equal to the number of columns can be QR decomposed. If your matrix has more columns than rows, you can QR decompose its transpose.
See also
QRDecomposition
References Meta.Numerics.Matrices.RectangularMatrix.cols, Meta.Numerics.Matrices.RectangularMatrix.rows, and Meta.Numerics.Matrices.RectangularMatrix.store.
SingularValueDecomposition()
SingularValueDecomposition Meta.Numerics.Matrices.RectangularMatrix.SingularValueDecomposition () inline
Computes the singular value decomposition of the matrix.
Returns
The SVD of the matrix.
References Meta.Numerics.Matrices.RectangularMatrix.cols, Meta.Numerics.Matrices.RectangularMatrix.rows, and Meta.Numerics.Matrices.RectangularMatrix.store.
Referenced by Test.RectangularMatrixTest.PC(), Test.RectangularMatrixTest.RandomRectangularSVD(), and Meta.Numerics.Matrices.SquareMatrix.SingularValueDecomposition().
operator*() [4/4]
static ColumnVector Meta.Numerics.Matrices.RectangularMatrix.operator* (RectangularMatrix A, ColumnVector v) inline static
Computes the product of a rectangular matrix and a column vector.
Parameters
A The matrix.
v The column vector.
Returns
The column vector Av.
Exceptions
ArgumentNullException A or v is null.
DimensionMismatchException The column count of A is not the same as the dimension of v .
References Meta.Numerics.Matrices.VectorBase.stride.
operator SquareMatrix()
static Meta.Numerics.Matrices.RectangularMatrix.operator SquareMatrix (RectangularMatrix A) inline explicit static
Casts a rectangular matrix to a square matrix.
Parameters
A The matrix to cast, which must have an equal number of rows and columns.
Returns
A square matrix, not independent of the original matrix.
It can occur that the mode of construction of a RectangularMatrix guarantees that it is actually square. For example, if you multiply an N X M rectangular matrix by an M X N rectangular matrix, the result is an N X N square matrix. However, when determining the type of the product, the .NET compiler considers only the types of the multiplicants. Since a RectangularMatrix times a RectangularMatrix yields a RectangularMatrix, it will consider the type of the product to be RetangularMatrix, even though its rows and column dimensions will be equal. You can use this explicit cast to obtain a SquareMatrix type.
Note that the output of the cast is not independent of the original matrix. This makes the cast operation fast, but changes to the resulting SquareMatrix will also change the original RectangularMatrix. To obtain an independent matrix, use the Copy method.
Exceptions
InvalidCastException The row and column dimensions of the matrix are not equal.
Member Data Documentation
store
readonly double [] Meta.Numerics.Matrices.RectangularMatrix.store private
Referenced by Meta.Numerics.Matrices.RectangularMatrix.Column(), Meta.Numerics.Matrices.RectangularMatrix.Copy(), Meta.Numerics.Matrices.RectangularMatrix.InfinityNorm(), Meta.Numerics.Matrices.RectangularMatrix.OneNorm(), Meta.Numerics.Matrices.RectangularMatrix.operator*(), Meta.Numerics.Matrices.RectangularMatrix.operator-(), Meta.Numerics.Matrices.RectangularMatrix.QRDecomposition(), Meta.Numerics.Matrices.RectangularMatrix.RectangularMatrix(), Meta.Numerics.Matrices.RectangularMatrix.Row(), Meta.Numerics.Matrices.RectangularMatrix.SingularValueDecomposition(), and Meta.Numerics.Matrices.RectangularMatrix.Transpose().
rows
readonly int Meta.Numerics.Matrices.RectangularMatrix.rows private
Referenced by Meta.Numerics.Matrices.RectangularMatrix.Column(), Meta.Numerics.Matrices.RectangularMatrix.Copy(), Meta.Numerics.Matrices.RectangularMatrix.InfinityNorm(), Meta.Numerics.Matrices.RectangularMatrix.OneNorm(), Meta.Numerics.Matrices.RectangularMatrix.QRDecomposition(), Meta.Numerics.Matrices.RectangularMatrix.RectangularMatrix(), Meta.Numerics.Matrices.RectangularMatrix.Row(), Meta.Numerics.Matrices.RectangularMatrix.SingularValueDecomposition(), and Meta.Numerics.Matrices.RectangularMatrix.Transpose().
cols
readonly int Meta.Numerics.Matrices.RectangularMatrix.cols private
Referenced by Meta.Numerics.Matrices.RectangularMatrix.Column(), Meta.Numerics.Matrices.RectangularMatrix.Copy(), Meta.Numerics.Matrices.RectangularMatrix.InfinityNorm(), Meta.Numerics.Matrices.RectangularMatrix.OneNorm(), Meta.Numerics.Matrices.RectangularMatrix.QRDecomposition(), Meta.Numerics.Matrices.RectangularMatrix.RectangularMatrix(), Meta.Numerics.Matrices.RectangularMatrix.Row(), Meta.Numerics.Matrices.RectangularMatrix.SingularValueDecomposition(), and Meta.Numerics.Matrices.RectangularMatrix.Transpose().
Property Documentation
this[int r, int c]
override double Meta.Numerics.Matrices.RectangularMatrix.this[int r, int c] get set
RowCount
override int Meta.Numerics.Matrices.RectangularMatrix.RowCount get
Referenced by Test.VectorTest.MixedVectorArithmetic(), Test.RectangularMatrixTest.RandomRectangularSVD(), Test.RectangularMatrixTest.RectangularMatrixAccess(), Test.RectangularMatrixTest.RectangularMatrixArithmetic(), and Test.RectangularMatrixTest.RectangularQRDecomposition().
ColumnCount
override int Meta.Numerics.Matrices.RectangularMatrix.ColumnCount get
Referenced by Test.VectorTest.MixedVectorArithmetic(), Test.RectangularMatrixTest.RandomRectangularSVD(), Test.RectangularMatrixTest.RectangularMatrixAccess(), Test.RectangularMatrixTest.RectangularMatrixArithmetic(), and Test.RectangularMatrixTest.RectangularQRDecomposition().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Matrices/RectangularMatrix.cs