Doc: IGLib EXTENDED: NUnit.Framework.Internal.TestNameGenerator.NameFragment Class Reference
NUnit.Framework.Internal.TestNameGenerator.NameFragment Class Reference abstract
Public Member Functions
virtual string GetText (TestMethod testMethod, object[] args)
abstract string GetText (MethodInfo method, object[] args)
Static Protected Member Functions
static void AppendGenericTypeNames (StringBuilder sb, MethodInfo method)
static string GetDisplayString (object arg, int stringMax)
Static Private Member Functions
static string EscapeSingleChar (char c)
static string EscapeCharInString (char c)
static string EscapeControlChar (char c)
Static Private Attributes
const string THREE_DOTS = "..."
Member Function Documentation
GetText() [1/2]
virtual string NUnit.Framework.Internal.TestNameGenerator.NameFragment.GetText (TestMethod testMethod, object[] args) inline virtual
Reimplemented in NUnit.Framework.Internal.TestNameGenerator.TestIDFragment.
References NUnit.Framework.Internal.Test.Method, and NUnit.Framework.Interfaces.IMethodInfo.MethodInfo.
GetText() [2/2]
abstract string NUnit.Framework.Internal.TestNameGenerator.NameFragment.GetText (MethodInfo method, object[] args) pure virtual
Implemented in NUnit.Framework.Internal.TestNameGenerator.ArgumentFragment, NUnit.Framework.Internal.TestNameGenerator.ClassFullNameFragment, NUnit.Framework.Internal.TestNameGenerator.ClassNameFragment, NUnit.Framework.Internal.TestNameGenerator.MethodFullNameFragment, NUnit.Framework.Internal.TestNameGenerator.NamespaceFragment, NUnit.Framework.Internal.TestNameGenerator.MethodNameFragment, NUnit.Framework.Internal.TestNameGenerator.FixedTextFragment, NUnit.Framework.Internal.TestNameGenerator.TestIDFragment, and NUnit.Framework.Internal.TestNameGenerator.ArgListFragment.
AppendGenericTypeNames()
static void NUnit.Framework.Internal.TestNameGenerator.NameFragment.AppendGenericTypeNames (StringBuilder sb, MethodInfo method) inline static protected
Referenced by NUnit.Framework.Internal.TestNameGenerator.MethodNameFragment.GetText(), and NUnit.Framework.Internal.TestNameGenerator.MethodFullNameFragment.GetText().
GetDisplayString()
static string NUnit.Framework.Internal.TestNameGenerator.NameFragment.GetDisplayString (object arg, int stringMax) inline static protected
References NUnit.Framework.Internal.TestNameGenerator.NameFragment.EscapeCharInString(), NUnit.Framework.Internal.TestNameGenerator.NameFragment.EscapeSingleChar(), and NUnit.Framework.Internal.TestNameGenerator.NameFragment.THREE_DOTS.
Referenced by NUnit.Framework.Internal.TestNameGenerator.ArgListFragment.GetText(), and NUnit.Framework.Internal.TestNameGenerator.ArgumentFragment.GetText().
EscapeSingleChar()
static string NUnit.Framework.Internal.TestNameGenerator.NameFragment.EscapeSingleChar (char c) inline static private
References NUnit.Framework.Internal.TestNameGenerator.NameFragment.EscapeControlChar().
Referenced by NUnit.Framework.Internal.TestNameGenerator.NameFragment.GetDisplayString().
EscapeCharInString()
static string NUnit.Framework.Internal.TestNameGenerator.NameFragment.EscapeCharInString (char c) inline static private
References NUnit.Framework.Internal.TestNameGenerator.NameFragment.EscapeControlChar().
Referenced by NUnit.Framework.Internal.TestNameGenerator.NameFragment.GetDisplayString().
EscapeControlChar()
static string NUnit.Framework.Internal.TestNameGenerator.NameFragment.EscapeControlChar (char c) inline static private
Referenced by NUnit.Framework.Internal.TestNameGenerator.NameFragment.EscapeCharInString(), and NUnit.Framework.Internal.TestNameGenerator.NameFragment.EscapeSingleChar().
Member Data Documentation
THREE_DOTS
const string NUnit.Framework.Internal.TestNameGenerator.NameFragment.THREE_DOTS = "..." static private
Referenced by NUnit.Framework.Internal.TestNameGenerator.NameFragment.GetDisplayString().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/TestNameGenerator.cs