Doc: IGLib EXTENDED: IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary Class Reference
IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary Class Reference
Static Public Member Functions
static void ShowPlot ()
The plotting thread. Start after the molecular chain is instanitated in the main thread. Creates a PlotHQ and loads a curve (molecular chain) to the plotter. Then shows the plot. After this the thread can't do anything else, since it's displaying the plot window.
static void Run (string[] arguments)
We initialize the molecular chain, start the plotting thread, then continue changing the chain in this thread and calling update on the shared PlotHQ object.
Static Public Attributes
static MolecularCatenary catenary
static PlotHQ plothq1
static PlotZedgraphCurve curve1
Member Function Documentation
ShowPlot()
static void IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.ShowPlot () inline static
The plotting thread. Start after the molecular chain is instanitated in the main thread. Creates a PlotHQ and loads a curve (molecular chain) to the plotter. Then shows the plot. After this the thread can't do anything else, since it's displaying the plot window.
References IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.catenary, IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.curve1, IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase.NewCurveFromPlottableData(), IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.plothq1, IG.MPetekLib.Algorithms.Plotting.PlotHQ.Plotter, IG.Gr.PlotterZedGraph.SetBounds(), IG.MPetekLib.Algorithms.Plotting.PlotHQ.ShowPlot(), IG.Gr.PlotterZedGraph.Title, and IG.MPetekLib.Algorithms.Plotting.PlotHQ.Window.
Referenced by IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.Run().
Run()
static void IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.Run (string[] arguments) inline static
We initialize the molecular chain, start the plotting thread, then continue changing the chain in this thread and calling update on the shared PlotHQ object.
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.MolecularCatenary.Beta, IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.catenary, IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.curve1, IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase.LoadPlottableDataToCurve(), IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.plothq1, IG.MPetekLib.Algorithms.Plotting.PlotHQ.Plotter, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.MolecularCatenary.PotentialEnergy, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.MolecularCatenary.ShiftALink(), IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.ShowPlot(), and IG.Gr.PlotterZedGraph.Update().
Referenced by IG.Script.AppMarkoPetek.App01AnnealingCatenary().
Member Data Documentation
catenary
MolecularCatenary IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.catenary static
Referenced by IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.Run(), and IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.ShowPlot().
plothq1
PlotHQ IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.plothq1 static
Referenced by IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.Run(), and IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.ShowPlot().
curve1
PlotZedgraphCurve IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.curve1 static
Referenced by IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.Run(), and IG.MPetekLib.Application.Scripts.CompPhys._01AnnealingCatenary.ShowPlot().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/Guest_Marko_Petek_Lib/application/scripts/CompPhys/01AnnealingCatenary.cs