Doc: IGLib EXTENDED: NUnit.Engine.Api.Tests.TestFilterTests Class Reference
NUnit.Engine.Api.Tests.TestFilterTests Class Reference
Public Member Functions
void EmptyFilter ()
void FilterWithOneTest ()
void FilterWithThreeTests ()
Member Function Documentation
EmptyFilter()
void NUnit.Engine.Api.Tests.TestFilterTests.EmptyFilter () inline
References NUnit.Engine.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Engine.TestFilter.Text, and NUnit.Framework.Assert.That().
FilterWithOneTest()
void NUnit.Engine.Api.Tests.TestFilterTests.FilterWithOneTest () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Engine.TestFilter.Text, and NUnit.Framework.Assert.That().
FilterWithThreeTests()
void NUnit.Engine.Api.Tests.TestFilterTests.FilterWithThreeTests () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Engine.TestFilter.Text, and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Api/TestFilterTests.cs