Doc: IGLib EXTENDED: IG.Forms.CookingTimerForm Class Reference
IG.Forms.CookingTimerForm Class Reference
Public Member Functions
CookingTimerForm ()
CookingTimerForm ()
CookingTimerForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
CookingTimerControl cookingStopwatchControl1
Constructor & Destructor Documentation
CookingTimerForm() [1/3]
IG.Forms.CookingTimerForm.CookingTimerForm () inline
References IG.Forms.CookingTimerForm.InitializeComponent().
CookingTimerForm() [2/3]
IG.Forms.CookingTimerForm.CookingTimerForm () inline
References IG.Forms.CookingTimerForm.InitializeComponent().
CookingTimerForm() [3/3]
IG.Forms.CookingTimerForm.CookingTimerForm () inline
References IG.Forms.CookingTimerForm.InitializeComponent().
Member Function Documentation
Dispose() [1/3]
override void IG.Forms.CookingTimerForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.CookingTimerForm.components.
InitializeComponent() [1/3]
void IG.Forms.CookingTimerForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.CookingTimerForm.cookingStopwatchControl1.
Referenced by IG.Forms.CookingTimerForm.CookingTimerForm().
Dispose() [2/3]
override void IG.Forms.CookingTimerForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.CookingTimerForm.components.
InitializeComponent() [2/3]
void IG.Forms.CookingTimerForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.CookingTimerForm.cookingStopwatchControl1.
Dispose() [3/3]
override void IG.Forms.CookingTimerForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.CookingTimerForm.components.
InitializeComponent() [3/3]
void IG.Forms.CookingTimerForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.CookingTimerForm.cookingStopwatchControl1.
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.CookingTimerForm.components = null private
Required designer variable.
Referenced by IG.Forms.CookingTimerForm.Dispose().
cookingStopwatchControl1
CookingTimerControl IG.Forms.CookingTimerForm.cookingStopwatchControl1 private
Referenced by IG.Forms.CookingTimerForm.InitializeComponent().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/Timer/CookingTimerForm.cs
iglib/igforms/Utilities/Timer/CookingTimerForm.Designer.cs