Doc: IGLib EXTENDED: AForge.Math.PerlinNoise Class Reference
AForge.Math.PerlinNoise Class Reference
Perlin noise function.
Public Member Functions
PerlinNoise ()
Initializes a new instance of the PerlinNoise class.
PerlinNoise (int octaves, double persistence)
Initializes a new instance of the PerlinNoise class.
PerlinNoise (int octaves, double persistence, double initFrequency, double initAmplitude)
Initializes a new instance of the PerlinNoise class.
double Function (double x)
1-D Perlin noise function.
double Function2D (double x, double y)
2-D Perlin noise function.
Properties
double InitFrequency [get, set]
Initial frequency.
double InitAmplitude [get, set]
Initial amplitude.
double Persistence [get, set]
Persistence value.
int Octaves [get, set]
Number of octaves, [1, 32].
Private Member Functions
double Noise (int x)
Ordinary noise function
double Noise (int x, int y)
double SmoothedNoise (double x)
Smoothed noise.
double SmoothedNoise (double x, double y)
double CosineInterpolate (double x1, double x2, double a)
Cosine interpolation.
Private Attributes
double initFrequency = 1.0
double initAmplitude = 1.0
double persistence = 0.65
int octaves = 4
Detailed Description
Perlin noise function.
The class implements 1-D and 2-D Perlin noise functions, which represent sum of several smooth noise functions with different frequency and amplitude. The description of Perlin noise function and its calculation may be found on Hugo Elias's page.
The number of noise functions, which comprise the resulting Perlin noise function, is set by Octaves property. Amplitude and frequency values for each octave start from values, which are set by InitFrequency and InitAmplitude properties.
Sample usage (clouds effect):
// create Perlin noise function
PerlinNoise noise = new PerlinNoise(8, 0.5, 1.0 / 32);
// generate clouds effect
float[,] texture = new float[height, width];
for (int y = 0; y < height; y++)
{
    for ( int x = 0; x < width; x++ )
    {
        texture[y, x] =
            Math.Max( 0.0f, Math.Min( 1.0f,
                (float) noise.Function2D( x, y ) * 0.5f + 0.5f
            ) );
    }
}
Constructor & Destructor Documentation
PerlinNoise() [1/3]
AForge.Math.PerlinNoise.PerlinNoise () inline
Initializes a new instance of the PerlinNoise class.
PerlinNoise() [2/3]
AForge.Math.PerlinNoise.PerlinNoise (int octaves, double persistence) inline
Initializes a new instance of the PerlinNoise class.
Parameters
octaves Number of octaves (see Octaves property).
persistence Persistence value (see Persistence property).
References AForge.Math.PerlinNoise.octaves, and AForge.Math.PerlinNoise.persistence.
PerlinNoise() [3/3]
AForge.Math.PerlinNoise.PerlinNoise (int octaves, double persistence, double initFrequency, double initAmplitude) inline
Initializes a new instance of the PerlinNoise class.
Parameters
octaves Number of octaves (see Octaves property).
persistence Persistence value (see Persistence property).
initFrequency Initial frequency (see InitFrequency property).
initAmplitude Initial amplitude (see InitAmplitude property).
References AForge.Math.PerlinNoise.initAmplitude, AForge.Math.PerlinNoise.initFrequency, AForge.Math.PerlinNoise.octaves, and AForge.Math.PerlinNoise.persistence.
Member Function Documentation
Function()
double AForge.Math.PerlinNoise.Function (double x) inline
1-D Perlin noise function.
Parameters
x x value.
Returns
Returns function's value at point x .
References AForge.Math.PerlinNoise.initAmplitude, AForge.Math.PerlinNoise.initFrequency, AForge.Math.PerlinNoise.octaves, AForge.Math.PerlinNoise.persistence, and AForge.Math.PerlinNoise.SmoothedNoise().
Function2D()
double AForge.Math.PerlinNoise.Function2D (double x, double y) inline
2-D Perlin noise function.
Parameters
x x value.
y y value.
Returns
Returns function's value at point (x , y).
References AForge.Math.PerlinNoise.initAmplitude, AForge.Math.PerlinNoise.initFrequency, AForge.Math.PerlinNoise.octaves, AForge.Math.PerlinNoise.persistence, and AForge.Math.PerlinNoise.SmoothedNoise().
Referenced by AForge.Imaging.Textures.CloudsTexture.Generate(), AForge.Imaging.Textures.LabyrinthTexture.Generate(), AForge.Imaging.Textures.TextileTexture.Generate(), AForge.Imaging.Textures.WoodTexture.Generate(), and AForge.Imaging.Textures.MarbleTexture.Generate().
Noise() [1/2]
double AForge.Math.PerlinNoise.Noise (int x) inline private
Ordinary noise function
Referenced by AForge.Math.PerlinNoise.SmoothedNoise().
Noise() [2/2]
double AForge.Math.PerlinNoise.Noise (int x, int y) inline private
SmoothedNoise() [1/2]
double AForge.Math.PerlinNoise.SmoothedNoise (double x) inline private
Smoothed noise.
References AForge.Math.PerlinNoise.CosineInterpolate(), and AForge.Math.PerlinNoise.Noise().
Referenced by AForge.Math.PerlinNoise.Function(), and AForge.Math.PerlinNoise.Function2D().
SmoothedNoise() [2/2]
double AForge.Math.PerlinNoise.SmoothedNoise (double x, double y) inline private
References AForge.Math.PerlinNoise.CosineInterpolate(), and AForge.Math.PerlinNoise.Noise().
CosineInterpolate()
double AForge.Math.PerlinNoise.CosineInterpolate (double x1, double x2, double a) inline private
Cosine interpolation.
Referenced by AForge.Math.PerlinNoise.SmoothedNoise().
Member Data Documentation
initFrequency
double AForge.Math.PerlinNoise.initFrequency = 1.0 private
Referenced by AForge.Math.PerlinNoise.Function(), AForge.Math.PerlinNoise.Function2D(), and AForge.Math.PerlinNoise.PerlinNoise().
initAmplitude
double AForge.Math.PerlinNoise.initAmplitude = 1.0 private
Referenced by AForge.Math.PerlinNoise.Function(), AForge.Math.PerlinNoise.Function2D(), and AForge.Math.PerlinNoise.PerlinNoise().
persistence
double AForge.Math.PerlinNoise.persistence = 0.65 private
Referenced by AForge.Math.PerlinNoise.Function(), AForge.Math.PerlinNoise.Function2D(), and AForge.Math.PerlinNoise.PerlinNoise().
octaves
int AForge.Math.PerlinNoise.octaves = 4 private
Referenced by AForge.Math.PerlinNoise.Function(), AForge.Math.PerlinNoise.Function2D(), and AForge.Math.PerlinNoise.PerlinNoise().
Property Documentation
InitFrequency
double AForge.Math.PerlinNoise.InitFrequency get set
Initial frequency.
The property sets initial frequency of the first octave. Frequencies for next octaves are calculated using the next equation:
frequencyi = InitFrequency * 2i, where i = [0, Octaves).
Default value is set to 1.
InitAmplitude
double AForge.Math.PerlinNoise.InitAmplitude get set
Initial amplitude.
The property sets initial amplitude of the first octave. Amplitudes for next octaves are calculated using the next equation:
amplitudei = InitAmplitude * Persistencei, where i = [0, Octaves).
Default value is set to 1.
Persistence
double AForge.Math.PerlinNoise.Persistence get set
Persistence value.
The property sets so called persistence value, which controls the way how amplitude is calculated for each octave comprising the Perlin noise function.
Default value is set to 0.65.
Octaves
int AForge.Math.PerlinNoise.Octaves get set
Number of octaves, [1, 32].
The property sets the number of noise functions, which sum up the resulting Perlin noise function.
Default value is set to 4.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Math/PerlinNoise.cs