Doc: IGLib EXTENDED: AForge.Imaging.Filters.TopHat Class Reference
AForge.Imaging.Filters.TopHat Class Reference
Top-hat operator from Mathematical Morphology.
Public Member Functions
TopHat ()
Initializes a new instance of the TopHat class.
TopHat (short[,] se)
Initializes a new instance of the TopHat class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlaceFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.BaseInPlaceFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
Opening opening = new Opening()
Subtract subtract = new Subtract()
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Top-hat operator from Mathematical Morphology.
Top-hat morphological operator subtracts result of morphological opening on the input image from the input image itself.
Applied to binary image, the filter allows to get all those object (their parts) which were removed by opening filter, but never restored.
The filter accepts 8 and 16 bpp grayscale images and 24 and 48 bpp color images for processing.
Sample usage:
// create filter
TopHat filter = new TopHat();
// apply the filter
filter.Apply(image);
Initial image:
Result image:
BottomHat
Constructor & Destructor Documentation
TopHat() [1/2]
AForge.Imaging.Filters.TopHat.TopHat () inline
Initializes a new instance of the TopHat class.
References AForge.Imaging.Filters.TopHat.formatTranslations.
TopHat() [2/2]
AForge.Imaging.Filters.TopHat.TopHat (short se[,]) inline
Initializes a new instance of the TopHat class.
Parameters
se Structuring element to pass to Opening operator.
References AForge.Imaging.Filters.TopHat.opening.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.TopHat.ProcessFilter (UnmanagedImage image) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
Implements AForge.Imaging.Filters.BaseInPlaceFilter.
References AForge.Imaging.Filters.Opening.Apply(), AForge.Imaging.Filters.BaseInPlaceFilter.ApplyInPlace(), AForge.Imaging.UnmanagedImage.Dispose(), AForge.Imaging.Filters.TopHat.opening, AForge.Imaging.Filters.TopHat.subtract, and AForge.Imaging.Filters.BaseInPlaceFilter2.UnmanagedOverlayImage.
Member Data Documentation
opening
Opening AForge.Imaging.Filters.TopHat.opening = new Opening() private
Referenced by AForge.Imaging.Filters.TopHat.ProcessFilter(), and AForge.Imaging.Filters.TopHat.TopHat().
subtract
Subtract AForge.Imaging.Filters.TopHat.subtract = new Subtract() private
Referenced by AForge.Imaging.Filters.TopHat.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.TopHat.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.TopHat.TopHat().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.TopHat.FormatTranslations get
Format translations dictionary.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Morphology/TopHat.cs