Doc: IGLib EXTENDED: AForge.Imaging.Filters.OtsuThreshold Class Reference
AForge.Imaging.Filters.OtsuThreshold Class Reference
Otsu thresholding.
Public Member Functions
OtsuThreshold ()
Initializes a new instance of the OtsuThreshold class.
int CalculateThreshold (Bitmap image, Rectangle rect)
Calculate binarization threshold for the given image.
int CalculateThreshold (BitmapData image, Rectangle rect)
Calculate binarization threshold for the given image.
int CalculateThreshold (UnmanagedImage image, Rectangle rect)
Calculate binarization threshold for the given image.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image, Rectangle rect)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
int ThresholdValue [get]
Threshold value.
Properties inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
Threshold thresholdFilter = new Threshold()
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Otsu thresholding.
The class implements Otsu thresholding, which is described in N. Otsu, "A threshold selection method from gray-level histograms", IEEE Trans. Systems, Man and Cybernetics 9(1), pp. 62–66, 1979.
This implementation instead of minimizing the weighted within-class variance does maximization of between-class variance, what gives the same result. The approach is described in this presentation.
The filter accepts 8 bpp grayscale images for processing.
Sample usage:
// create filter
OtsuThreshold filter = new OtsuThreshold();
// apply the filter
filter.ApplyInPlace(image);
// check threshold value
byte t = filter.ThresholdValue;
// ...
Initial image:
Result image (calculated threshold is 97):
See also
IterativeThreshold, SISThreshold
Constructor & Destructor Documentation
OtsuThreshold()
AForge.Imaging.Filters.OtsuThreshold.OtsuThreshold () inline
Initializes a new instance of the OtsuThreshold class.
References AForge.Imaging.Filters.OtsuThreshold.formatTranslations.
Member Function Documentation
CalculateThreshold() [1/3]
int AForge.Imaging.Filters.OtsuThreshold.CalculateThreshold (Bitmap image, Rectangle rect) inline
Calculate binarization threshold for the given image.
Parameters
image Image to calculate binarization threshold for.
rect Rectangle to calculate binarization threshold for.
Returns
Returns binarization threshold.
The method is used to calculate binarization threshold only. The threshold later may be applied to the image using Threshold image processing filter.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported by the routine. It should be 8 bpp grayscale (indexed) image.
References AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.Filters.OtsuThreshold.CalculateThreshold(), and AForge.Imaging.Filters.OtsuThreshold.ProcessFilter().
CalculateThreshold() [2/3]
int AForge.Imaging.Filters.OtsuThreshold.CalculateThreshold (BitmapData image, Rectangle rect) inline
Calculate binarization threshold for the given image.
Parameters
image Image to calculate binarization threshold for.
rect Rectangle to calculate binarization threshold for.
Returns
Returns binarization threshold.
The method is used to calculate binarization threshold only. The threshold later may be applied to the image using Threshold image processing filter.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported by the routine. It should be 8 bpp grayscale (indexed) image.
References AForge.Imaging.Filters.OtsuThreshold.CalculateThreshold().
CalculateThreshold() [3/3]
int AForge.Imaging.Filters.OtsuThreshold.CalculateThreshold (UnmanagedImage image, Rectangle rect) inline
Calculate binarization threshold for the given image.
Parameters
image Image to calculate binarization threshold for.
rect Rectangle to calculate binarization threshold for.
Returns
Returns binarization threshold.
The method is used to calculate binarization threshold only. The threshold later may be applied to the image using Threshold image processing filter.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported by the routine. It should be 8 bpp grayscale (indexed) image.
References AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, and AForge.Imaging.UnmanagedImage.Stride.
ProcessFilter()
override unsafe void AForge.Imaging.Filters.OtsuThreshold.ProcessFilter (UnmanagedImage image, Rectangle rect) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
rect Image rectangle for processing by the filter.
Implements AForge.Imaging.Filters.BaseInPlacePartialFilter.
References AForge.Imaging.Filters.BaseInPlacePartialFilter.ApplyInPlace(), AForge.Imaging.Filters.OtsuThreshold.CalculateThreshold(), AForge.Imaging.Filters.OtsuThreshold.thresholdFilter, and AForge.Imaging.Filters.Threshold.ThresholdValue.
Member Data Documentation
thresholdFilter
Threshold AForge.Imaging.Filters.OtsuThreshold.thresholdFilter = new Threshold() private
Referenced by AForge.Imaging.Filters.OtsuThreshold.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.OtsuThreshold.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.OtsuThreshold.OtsuThreshold().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.OtsuThreshold.FormatTranslations get
Format translations dictionary.
ThresholdValue
int AForge.Imaging.Filters.OtsuThreshold.ThresholdValue get
Threshold value.
The property is read only and represents the value, which was automaticaly calculated using Otsu algorithm.
Referenced by IPPrototyperSample.CoinsFinder.Process().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Adaptive Binarization/OtsuThreshold.cs