Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLATRS Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLATRS Class Reference
– LAPACK auxiliary routine (version 3.0) – Univ. of Tennessee, Univ. of California Berkeley, NAG Ltd., Courant Institute, Argonne National Lab, and Rice University June 30, 1992
Public Member Functions
DLATRS (LSAME lsame, IDAMAX idamax, DASUM dasum, DDOT ddot, DLAMCH dlamch, DAXPY daxpy, DSCAL dscal, DTRSV dtrsv, XERBLA xerbla)
DLATRS ()
void Run (string UPLO, string TRANS, string DIAG, string NORMIN, int N, double[] A, int offset_a, int LDA, ref double[] X, int offset_x, ref double SCALE, ref double[] CNORM, int offset_cnorm, ref int INFO)
Private Attributes
LSAME _lsame
IDAMAX _idamax
DASUM _dasum
DDOT _ddot
DLAMCH _dlamch
DAXPY _daxpy
DSCAL _dscal
DTRSV _dtrsv
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E+0
const double HALF = 0.5E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.0) – Univ. of Tennessee, Univ. of California Berkeley, NAG Ltd., Courant Institute, Argonne National Lab, and Rice University June 30, 1992
Purpose
DLATRS solves one of the triangular systems
A *x = s*b or A'*x = s*b
with scaling to prevent overflow. Here A is an upper or lower triangular matrix, A' denotes the transpose of A, x and b are n-element vectors, and s is a scaling factor, usually less than or equal to 1, chosen so that the components of x will be less than the overflow threshold. If the unscaled problem will not cause overflow, the Level 2 BLAS routine DTRSV is called. If the matrix A is singular (A(j,j) = 0 for some j), then s is set to 0 and a non-trivial solution to A*x = 0 is returned.
/summary>
Constructor & Destructor Documentation
DLATRS() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLATRS.DLATRS (LSAME lsame, IDAMAX idamax, DASUM dasum, DDOT ddot, DLAMCH dlamch, DAXPY daxpy, DSCAL dscal, DTRSV dtrsv, XERBLA xerbla) inline
DLATRS() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLATRS.DLATRS () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLATRS.Run (string UPLO, string TRANS, string DIAG, string NORMIN, int N, double[] A, int offset_a, int LDA, ref double[] X, int offset_x, ref double SCALE, ref double[] CNORM, int offset_cnorm, ref int INFO) inline
Purpose
DLATRS solves one of the triangular systems
A *x = s*b or A'*x = s*b
with scaling to prevent overflow. Here A is an upper or lower triangular matrix, A' denotes the transpose of A, x and b are n-element vectors, and s is a scaling factor, usually less than or equal to 1, chosen so that the components of x will be less than the overflow threshold. If the unscaled problem will not cause overflow, the Level 2 BLAS routine DTRSV is called. If the matrix A is singular (A(j,j) = 0 for some j), then s is set to 0 and a non-trivial solution to A*x = 0 is returned.
/summary>
Parameters
UPLO (input) CHARACTER*1 Specifies whether the matrix A is upper or lower triangular. = 'U': Upper triangular = 'L': Lower triangular /param>
Parameters
TRANS (input) CHARACTER*1 Specifies the operation applied to A. = 'N': Solve A * x = s*b (No transpose) = 'T': Solve A'* x = s*b (Transpose) = 'C': Solve A'* x = s*b (Conjugate transpose = Transpose) /param>
Parameters
DIAG (input) CHARACTER*1 Specifies whether or not the matrix A is unit triangular. = 'N': Non-unit triangular = 'U': Unit triangular /param>
Parameters
NORMIN (input) CHARACTER*1 Specifies whether CNORM has been set or not. = 'Y': CNORM contains the column norms on entry = 'N': CNORM is not set on entry. On exit, the norms will be computed and stored in CNORM. /param>
Parameters
N (input) INTEGER The order of the matrix A. N .GE. 0. /param>
Parameters
A x = s*b or A'*x = s*b /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max (1,N). /param>
Parameters
X (input/output) DOUBLE PRECISION array, dimension (N) On entry, the right hand side b of the triangular system. On exit, X is overwritten by the solution vector x. /param>
Parameters
SCALE (output) DOUBLE PRECISION The scaling factor s for the triangular system A * x = s*b or A' x = s*b. If SCALE = 0, the matrix A is singular or badly scaled, and the vector x is an exact or approximate solution to A*x = 0. /param>
Parameters
CNORM (input or output) DOUBLE PRECISION array, dimension (N)
If NORMIN = 'Y', CNORM is an input argument and CNORM(j) contains the norm of the off-diagonal part of the j-th column of A. If TRANS = 'N', CNORM(j) must be greater than or equal to the infinity-norm, and if TRANS = 'T' or 'C', CNORM(j) must be greater than or equal to the 1-norm.
If NORMIN = 'N', CNORM is an output argument and CNORM(j) returns the 1-norm of the offdiagonal part of the j-th column of A. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -k, the k-th argument had an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.DLATRS.HALF, DotNumerics.LinearAlgebra.CSLapack.DLATRS.ONE, DotNumerics.LinearAlgebra.CSLapack.DAXPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DDOT.Run(), DotNumerics.LinearAlgebra.CSLapack.DASUM.Run(), DotNumerics.LinearAlgebra.CSLapack.IDAMAX.Run(), DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRSV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLATRS.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTRCON.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLATRS._lsame private
_idamax
IDAMAX DotNumerics.LinearAlgebra.CSLapack.DLATRS._idamax private
_dasum
DASUM DotNumerics.LinearAlgebra.CSLapack.DLATRS._dasum private
_ddot
DDOT DotNumerics.LinearAlgebra.CSLapack.DLATRS._ddot private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLATRS._dlamch private
_daxpy
DAXPY DotNumerics.LinearAlgebra.CSLapack.DLATRS._daxpy private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DLATRS._dscal private
_dtrsv
DTRSV DotNumerics.LinearAlgebra.CSLapack.DLATRS._dtrsv private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLATRS._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLATRS.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLATRS.Run().
HALF
const double DotNumerics.LinearAlgebra.CSLapack.DLATRS.HALF = 0.5E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLATRS.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLATRS.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLATRS.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlatrs.cs