Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DNRM2 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DNRM2 Class Reference
Public Member Functions
DNRM2 ()
double Run (int N, double[] X, int offset_x, int INCX)
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Constructor & Destructor Documentation
DNRM2()
DotNumerics.LinearAlgebra.CSLapack.DNRM2.DNRM2 () inline
Member Function Documentation
Run()
double DotNumerics.LinearAlgebra.CSLapack.DNRM2.Run (int N, double[] X, int offset_x, int INCX) inline
Implements DotNumerics.LinearAlgebra.CSLapack.IDNRM2.
References DotNumerics.LinearAlgebra.CSLapack.DNRM2.ONE, and DotNumerics.LinearAlgebra.CSLapack.DNRM2.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEQPF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQP2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED9.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQP3.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQPS.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD8.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED3.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD3.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLALS0.Run().
Member Data Documentation
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DNRM2.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DNRM2.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DNRM2.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DNRM2.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dnrm2.cs