Doc: IGLib EXTENDED: NeuronDotNet.Core.Network Class Reference
NeuronDotNet.Core.Network Class Reference abstract
Public Member Functions
Network (SerializationInfo info, StreamingContext context)
Deserialization constructor. It is assumed that the serialization info provided contains valid data.
virtual void GetObjectData (SerializationInfo info, StreamingContext context)
Populates the serialization info with the data necessary to serialize the network.
void SetLearningRate (double learningRate)
Sets the learning rate to the given value. All layers in the network will use this constant value as learning rate during the learning process.
void SetLearningRate (double initialLearningRate, double finalLearningRate)
Sets the initial and final values for learning rate. During the learning process, all layers in the network will use an efeective learning rate which varies uniformly from the initial value to the final value.
void SetLearningRate (ILearningRateFunction learningRateFunction)
Sets the learning rate function.
virtual void Initialize ()
Initializes all layers and connectors and makes them ready to undergo fresh training.
virtual double[] Run (double[] input)
Runs the neural network against the given input
virtual void Learn (TrainingSet trainingSet, int trainingEpochs)
Trains the neural network for the given training set (Batch Training)
virtual void Learn (TrainingSample trainingSample, int currentIteration, int trainingEpochs)
Trains the network for the given training sample (Online training mode). Note that this method trains the sample only once, irrespective of what current epoch is. The arguments are just used to find out training progress and adjust parameters depending on it.
void StopLearning ()
If the network is currently learning, this method stops the learning.
Protected Member Functions
Network (ILayer inputLayer, ILayer outputLayer, TrainingMethod trainingMethod)
Creates a new neural network
virtual void OnBeginEpoch (int currentIteration, TrainingSet trainingSet)
Invokes BeginEpochEvent
virtual void OnEndEpoch (int currentIteration, TrainingSet trainingSet)
Invokes EndEpochEvent
virtual void OnBeginSample (int currentIteration, TrainingSample currentSample)
Invokes BeginSampleEvent
virtual void OnEndSample (int currentIteration, TrainingSample currentSample)
Invokes BeginSampleEvent
abstract void LearnSample (TrainingSample trainingSample, int currentIteration, int trainingEpochs)
A protected helper function used to train single learning sample
Protected Attributes
readonly ILayer inputLayer
The input layer
readonly ILayer outputLayer
The output layer
readonly IList< ILayer > layers
List of layers in the network, ordered acyclically (first layer being input layer and last one being output layer)
readonly IList< IConnector > connectors
A list of connectors between layers.
readonly TrainingMethod trainingMethod
The method of training used to train the network
int jitterEpoch
Epoch(interval) at which Jitter operation is performed. If this value is zero, not jitter is performed.
double jitterNoiseLimit
Maximum absolute limit to the random noise added during Jitter operation
bool isStopping = false
This flag is set to true, whenever training needs to be stopped immmediately
Properties
ILayer InputLayer [get]
Gets the input layer of the network
ILayer OutputLayer [get]
Gets the output layer of the network
int LayerCount [get]
Gets the number of layers in the network.
IEnumerable< ILayer > Layers [get]
Exposes an enumerator to iterate over layers in the network.
ILayer this[int index] [get]
Layer Indexer
int ConnectorCount [get]
Gets the number of connectors in the network.
IEnumerable< IConnector > Connectors [get]
Exposes an enumerator to iterate over connectors in the network.
double JitterNoiseLimit [get, set]
Gets or sets maximum absolute limit to the jitter noise
int JitterEpoch [get, set]
Gets or sets the jitter epoch
Properties inherited from NeuronDotNet.Core.INetwork
ILayer InputLayer [get]
Gets the input layer of the network
ILayer OutputLayer [get]
Gets the output layer of the network
int LayerCount [get]
Gets the number of layers in the network.
IEnumerable< ILayer > Layers [get]
Exposes an enumerator to iterate over layers in the network.
ILayer this[int index] [get]
Layer Indexer
int ConnectorCount [get]
Gets the number of connectors in the network.
IEnumerable< IConnector > Connectors [get]
Exposes an enumerator to iterate over connectors in the network.
double JitterNoiseLimit [get, set]
Gets or sets maximum absolute limit to the jitter noise
int JitterEpoch [get, set]
Gets or sets the jitter epoch
Events
TrainingEpochEventHandler BeginEpochEvent
This event is invoked during the commencement of a new training iteration during 'Batch training' mode.
TrainingSampleEventHandler BeginSampleEvent
This event is invoked whenever the network is about to learn a training sample.
TrainingSampleEventHandler EndSampleEvent
This event is invoked whenever the network has successfully completed learning a training sample.
TrainingEpochEventHandler EndEpochEvent
This event is invoked whenever a training iteration is successfully completed during 'Batch training' mode.
Events inherited from NeuronDotNet.Core.INetwork
TrainingEpochEventHandler BeginEpochEvent
This event is invoked during the commencement of a new training iteration during 'Batch training' mode.
TrainingSampleEventHandler BeginSampleEvent
This event is invoked whenever the network is about to learn a training sample.
TrainingSampleEventHandler EndSampleEvent
This event is invoked whenever the network has successfully completed learning a training sample.
TrainingEpochEventHandler EndEpochEvent
This event is invoked whenever a training iteration is successfully completed during 'Batch training' mode.
Detailed Description
An abstract base class to represent a neural network. A typical neural network consists of a set of ILayers acyclically interconnected by various IConnectors. Input layer gets the input from the user and network output is obtained from the output layer.
To create a neural network, follow these steps
Create and customize layers
Establish connections between layers (No cycles should exist)
Construct Network specifying the desired input and output layers
There are two modes in which a neural network can be trained. In 'Batch Training', the neural network is allowed to learn by specifying a predefined training set containing various training samples. In 'Online training mode', a random training sample is generated every time (usually by another neural network, called 'teacher' network) and is used for training. Both modes are supported by overloaded Learn() methods. Run() method is used to run a neural network against a particular input.
Constructor & Destructor Documentation
Network() [1/2]
NeuronDotNet.Core.Network.Network (ILayer inputLayer, ILayer outputLayer, TrainingMethod trainingMethod) inline protected
Creates a new neural network
Parameters
inputLayer The input layer
outputLayer The output layer
trainingMethod Training method to use
Exceptions
ArgumentNullException If inputLayer or outputLayer is null.
ArgumentException If trainingMethod is invalid
References NeuronDotNet.Core.Network.connectors, NeuronDotNet.Core.Network.Initialize(), NeuronDotNet.Core.Network.inputLayer, NeuronDotNet.Core.Network.layers, NeuronDotNet.Core.Network.outputLayer, NeuronDotNet.Core.ILayer.SourceConnectors, NeuronDotNet.Core.ILayer.TargetConnectors, NeuronDotNet.Core.IConnector.TargetLayer, NeuronDotNet.Core.Network.trainingMethod, and NeuronDotNet.Core.Helper.ValidateNotNull().
Network() [2/2]
NeuronDotNet.Core.Network.Network (SerializationInfo info, StreamingContext context) inline
Deserialization constructor. It is assumed that the serialization info provided contains valid data.
Parameters
info The serialization info to deserialize and obtain values
context Serialization context
Exceptions
ArgumentNullException If info is null
References NeuronDotNet.Core.Helper.ValidateNotNull().
Member Function Documentation
GetObjectData()
virtual void NeuronDotNet.Core.Network.GetObjectData (SerializationInfo info, StreamingContext context) inline virtual
Populates the serialization info with the data necessary to serialize the network.
Parameters
info The info to populate serialization data with
context Serialization context to use
Exceptions
ArgumentNullException If info is null
References NeuronDotNet.Core.Network.connectors, NeuronDotNet.Core.Network.inputLayer, NeuronDotNet.Core.Network.jitterEpoch, NeuronDotNet.Core.Network.jitterNoiseLimit, NeuronDotNet.Core.Network.layers, NeuronDotNet.Core.Network.outputLayer, NeuronDotNet.Core.Network.trainingMethod, and NeuronDotNet.Core.Helper.ValidateNotNull().
OnBeginEpoch()
virtual void NeuronDotNet.Core.Network.OnBeginEpoch (int currentIteration, TrainingSet trainingSet) inline protected virtual
Invokes BeginEpochEvent
Parameters
currentIteration Current training iteration
trainingSet Training set which is about to be trained
Reimplemented in NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.
References NeuronDotNet.Core.Network.BeginEpochEvent.
Referenced by NeuronDotNet.Core.Network.Learn().
OnEndEpoch()
virtual void NeuronDotNet.Core.Network.OnEndEpoch (int currentIteration, TrainingSet trainingSet) inline protected virtual
Invokes EndEpochEvent
Parameters
currentIteration Current training iteration
trainingSet Training set which got trained successfully this epoch
Reimplemented in NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.
References NeuronDotNet.Core.Network.EndEpochEvent.
Referenced by NeuronDotNet.Core.Network.Learn().
OnBeginSample()
virtual void NeuronDotNet.Core.Network.OnBeginSample (int currentIteration, TrainingSample currentSample) inline protected virtual
Invokes BeginSampleEvent
Parameters
currentIteration Current training iteration
currentSample Current sample which is about to be trained
References NeuronDotNet.Core.Network.BeginSampleEvent.
Referenced by NeuronDotNet.Core.Network.Learn(), IG.Neural.NeuralApproximatorNeuron.MyNeuronBackPropagation.Learn(), and IG.Neural.NeuronBackPropagationLEarning.Learn().
OnEndSample()
virtual void NeuronDotNet.Core.Network.OnEndSample (int currentIteration, TrainingSample currentSample) inline protected virtual
Invokes BeginSampleEvent
Parameters
currentIteration Current training iteration
currentSample Current sample which got trained successfully
References NeuronDotNet.Core.Network.EndSampleEvent.
Referenced by NeuronDotNet.Core.Network.Learn(), IG.Neural.NeuralApproximatorNeuron.MyNeuronBackPropagation.Learn(), and IG.Neural.NeuronBackPropagationLEarning.Learn().
SetLearningRate() [1/3]
void NeuronDotNet.Core.Network.SetLearningRate (double learningRate) inline
Sets the learning rate to the given value. All layers in the network will use this constant value as learning rate during the learning process.
Parameters
learningRate The learning rate
Implements NeuronDotNet.Core.INetwork.
References NeuronDotNet.Core.Network.layers.
Referenced by IG.Neural.NeuralApproximatorNeuron.CreateNetwork().
SetLearningRate() [2/3]
void NeuronDotNet.Core.Network.SetLearningRate (double initialLearningRate, double finalLearningRate) inline
Sets the initial and final values for learning rate. During the learning process, all layers in the network will use an efeective learning rate which varies uniformly from the initial value to the final value.
Parameters
initialLearningRate Initial value of learning rate
finalLearningRate Final value of learning rate
Implements NeuronDotNet.Core.INetwork.
References NeuronDotNet.Core.Network.layers.
SetLearningRate() [3/3]
void NeuronDotNet.Core.Network.SetLearningRate (ILearningRateFunction learningRateFunction) inline
Sets the learning rate function.
Parameters
learningRateFunction Learning rate function to use.
Exceptions
ArgumentNullException If learningRateFunction is null
Implements NeuronDotNet.Core.INetwork.
References NeuronDotNet.Core.Network.layers.
Initialize()
virtual void NeuronDotNet.Core.Network.Initialize () inline virtual
Initializes all layers and connectors and makes them ready to undergo fresh training.
Implements NeuronDotNet.Core.INetwork.
References NeuronDotNet.Core.IConnector.Initialize(), and NeuronDotNet.Core.Network.layers.
Referenced by NeuronDotNet.Core.Network.Learn(), NeuronDotNet.Core.Network.Network(), and IG.Neural.NeuralApproximatorNeuron.ResetNetwork().
Run()
virtual double [] NeuronDotNet.Core.Network.Run (double[] input) inline virtual
Runs the neural network against the given input
Parameters
input Input to the network
Returns
The output of the network
Exceptions
ArgumentNullException If input is null
Implements NeuronDotNet.Core.INetwork.
References NeuronDotNet.Core.ILayer.GetOutput(), NeuronDotNet.Core.Network.inputLayer, NeuronDotNet.Core.Network.layers, NeuronDotNet.Core.Network.outputLayer, and NeuronDotNet.Core.ILayer.SetInput().
Referenced by IG.Neural.NeuralApproximatorNeuron.CalculateOutput().
Learn() [1/2]
virtual void NeuronDotNet.Core.Network.Learn (TrainingSet trainingSet, int trainingEpochs) inline virtual
Trains the neural network for the given training set (Batch Training)
Parameters
trainingSet The training set to use
trainingEpochs Number of training epochs. (All samples are trained in some random order, in every training epoch)
Exceptions
ArgumentNullException if trainingSet is null
ArgumentException if trainingEpochs is zero or negative
Implements NeuronDotNet.Core.INetwork.
Reimplemented in IG.Neural.NeuronBackPropagationLEarning, and IG.Neural.NeuralApproximatorNeuron.MyNeuronBackPropagation.
References NeuronDotNet.Core.Network.connectors, NeuronDotNet.Core.Helper.GetRandomOrder(), NeuronDotNet.Core.Network.Initialize(), NeuronDotNet.Core.Network.inputLayer, NeuronDotNet.Core.TrainingSet.InputVectorLength, NeuronDotNet.Core.Network.isStopping, NeuronDotNet.Core.Network.jitterEpoch, NeuronDotNet.Core.Network.jitterNoiseLimit, NeuronDotNet.Core.Network.LearnSample(), NeuronDotNet.Core.ILayer.NeuronCount, NeuronDotNet.Core.Network.OnBeginEpoch(), NeuronDotNet.Core.Network.OnBeginSample(), NeuronDotNet.Core.Network.OnEndEpoch(), NeuronDotNet.Core.Network.OnEndSample(), NeuronDotNet.Core.Network.outputLayer, NeuronDotNet.Core.TrainingSet.OutputVectorLength, NeuronDotNet.Core.Network.trainingMethod, NeuronDotNet.Core.TrainingSet.TrainingSampleCount, NeuronDotNet.Core.Helper.ValidateNotNull(), and NeuronDotNet.Core.Helper.ValidatePositive().
Learn() [2/2]
virtual void NeuronDotNet.Core.Network.Learn (TrainingSample trainingSample, int currentIteration, int trainingEpochs) inline virtual
Trains the network for the given training sample (Online training mode). Note that this method trains the sample only once, irrespective of what current epoch is. The arguments are just used to find out training progress and adjust parameters depending on it.
Parameters
trainingSample Training sample to use
currentIteration Current training iteration
trainingEpochs Number of training epochs
Exceptions
ArgumentNullException If trainingSample is null
ArgumentException If trainingEpochs is not positive
ArgumentOutOfRangeException If currentIteration is negative or, if it is not less than trainingEpochs
Implements NeuronDotNet.Core.INetwork.
Reimplemented in NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.
References NeuronDotNet.Core.Network.LearnSample(), NeuronDotNet.Core.Network.OnBeginSample(), NeuronDotNet.Core.Network.OnEndSample(), NeuronDotNet.Core.Helper.ValidateNotNull(), and NeuronDotNet.Core.Helper.ValidatePositive().
StopLearning()
void NeuronDotNet.Core.Network.StopLearning () inline
If the network is currently learning, this method stops the learning.
Implements NeuronDotNet.Core.INetwork.
References NeuronDotNet.Core.Network.isStopping.
LearnSample()
abstract void NeuronDotNet.Core.Network.LearnSample (TrainingSample trainingSample, int currentIteration, int trainingEpochs) protected pure virtual
A protected helper function used to train single learning sample
Parameters
trainingSample Training sample to use
currentIteration Current training epoch (Assumed to be positive and less than trainingEpochs)
trainingEpochs Number of training epochs (Assumed to be positive)
Implemented in NeuronDotNet.Core.Backpropagation.BackpropagationNetwork, and NeuronDotNet.Core.SOM.KohonenNetwork.
Referenced by NeuronDotNet.Core.Network.Learn().
Member Data Documentation
inputLayer
readonly ILayer NeuronDotNet.Core.Network.inputLayer protected
The input layer
Referenced by NeuronDotNet.Core.Network.GetObjectData(), NeuronDotNet.Core.Network.Learn(), IG.Neural.NeuralApproximatorNeuron.MyNeuronBackPropagation.Learn(), IG.Neural.NeuronBackPropagationLEarning.Learn(), NeuronDotNet.Core.SOM.KohonenNetwork.LearnSample(), NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.LearnSample(), NeuronDotNet.Core.Network.Network(), and NeuronDotNet.Core.Network.Run().
outputLayer
readonly ILayer NeuronDotNet.Core.Network.outputLayer protected
The output layer
Referenced by NeuronDotNet.Core.Network.GetObjectData(), NeuronDotNet.Core.Network.Learn(), IG.Neural.NeuralApproximatorNeuron.MyNeuronBackPropagation.Learn(), IG.Neural.NeuronBackPropagationLEarning.Learn(), NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.LearnSample(), NeuronDotNet.Core.Network.Network(), and NeuronDotNet.Core.Network.Run().
layers
readonly IList<ILayer> NeuronDotNet.Core.Network.layers protected
List of layers in the network, ordered acyclically (first layer being input layer and last one being output layer)
Referenced by NeuronDotNet.Core.Network.GetObjectData(), NeuronDotNet.Core.Network.Initialize(), NeuronDotNet.Core.SOM.KohonenNetwork.LearnSample(), NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.LearnSample(), NeuronDotNet.Core.Network.Network(), NeuronDotNet.Core.Network.Run(), and NeuronDotNet.Core.Network.SetLearningRate().
connectors
readonly IList<IConnector> NeuronDotNet.Core.Network.connectors protected
A list of connectors between layers.
Referenced by NeuronDotNet.Core.Network.GetObjectData(), NeuronDotNet.Core.Network.Learn(), IG.Neural.NeuralApproximatorNeuron.MyNeuronBackPropagation.Learn(), IG.Neural.NeuronBackPropagationLEarning.Learn(), and NeuronDotNet.Core.Network.Network().
trainingMethod
readonly TrainingMethod NeuronDotNet.Core.Network.trainingMethod protected
The method of training used to train the network
Referenced by NeuronDotNet.Core.Network.GetObjectData(), NeuronDotNet.Core.Network.Learn(), IG.Neural.NeuralApproximatorNeuron.MyNeuronBackPropagation.Learn(), IG.Neural.NeuronBackPropagationLEarning.Learn(), and NeuronDotNet.Core.Network.Network().
jitterEpoch
int NeuronDotNet.Core.Network.jitterEpoch protected
Epoch(interval) at which Jitter operation is performed. If this value is zero, not jitter is performed.
Referenced by NeuronDotNet.Core.Network.GetObjectData(), NeuronDotNet.Core.Network.Learn(), IG.Neural.NeuralApproximatorNeuron.MyNeuronBackPropagation.Learn(), and IG.Neural.NeuronBackPropagationLEarning.Learn().
jitterNoiseLimit
double NeuronDotNet.Core.Network.jitterNoiseLimit protected
Maximum absolute limit to the random noise added during Jitter operation
Referenced by NeuronDotNet.Core.Network.GetObjectData(), NeuronDotNet.Core.Network.Learn(), IG.Neural.NeuralApproximatorNeuron.MyNeuronBackPropagation.Learn(), and IG.Neural.NeuronBackPropagationLEarning.Learn().
isStopping
bool NeuronDotNet.Core.Network.isStopping = false protected
This flag is set to true, whenever training needs to be stopped immmediately
Referenced by NeuronDotNet.Core.Network.Learn(), IG.Neural.NeuralApproximatorNeuron.MyNeuronBackPropagation.Learn(), IG.Neural.NeuronBackPropagationLEarning.Learn(), and NeuronDotNet.Core.Network.StopLearning().
Property Documentation
InputLayer
ILayer NeuronDotNet.Core.Network.InputLayer get
Gets the input layer of the network
Input Layer of the network. This property is never null.
OutputLayer
ILayer NeuronDotNet.Core.Network.OutputLayer get
Gets the output layer of the network
Output Layer of the network. This property is never null.
LayerCount
int NeuronDotNet.Core.Network.LayerCount get
Gets the number of layers in the network.
Layer Count. This value is always positive.
Layers
IEnumerable<ILayer> NeuronDotNet.Core.Network.Layers get
Exposes an enumerator to iterate over layers in the network.
Layer Enumerator. No layer in the network can be null.
this[int index]
ILayer NeuronDotNet.Core.Network.this[int index] get
Layer Indexer
Parameters
index The index
Returns
Layer at the given index
Exceptions
IndexOutOfRangeException If the index is out of range
ConnectorCount
int NeuronDotNet.Core.Network.ConnectorCount get
Gets the number of connectors in the network.
Connector Count. This value is never negative.
Connectors
IEnumerable<IConnector> NeuronDotNet.Core.Network.Connectors get
Exposes an enumerator to iterate over connectors in the network.
Connector Enumerator. No connector in a network can be null.
JitterNoiseLimit
double NeuronDotNet.Core.Network.JitterNoiseLimit get set
Gets or sets maximum absolute limit to the jitter noise
Maximum absolute limit to the random noise added while Jitter
Referenced by IG.Neural.NeuralApproximatorNeuron.CreateNetwork().
JitterEpoch
int NeuronDotNet.Core.Network.JitterEpoch get set
Gets or sets the jitter epoch
The epoch (interval) at which jitter is performed. If this value is not positive, no jitter is performed.
Referenced by IG.Neural.NeuralApproximatorNeuron.CreateNetwork().
Event Documentation
BeginEpochEvent
TrainingEpochEventHandler NeuronDotNet.Core.Network.BeginEpochEvent
This event is invoked during the commencement of a new training iteration during 'Batch training' mode.
Referenced by NeuronDotNet.Core.Network.OnBeginEpoch().
BeginSampleEvent
TrainingSampleEventHandler NeuronDotNet.Core.Network.BeginSampleEvent
This event is invoked whenever the network is about to learn a training sample.
Referenced by NeuronDotNet.Core.Network.OnBeginSample().
EndSampleEvent
TrainingSampleEventHandler NeuronDotNet.Core.Network.EndSampleEvent
This event is invoked whenever the network has successfully completed learning a training sample.
Referenced by NeuronDotNet.Core.Network.OnEndSample().
EndEpochEvent
TrainingEpochEventHandler NeuronDotNet.Core.Network.EndEpochEvent
This event is invoked whenever a training iteration is successfully completed during 'Batch training' mode.
Referenced by NeuronDotNet.Core.Network.OnEndEpoch().
The documentation for this class was generated from the following file:
shelldev/lib/externalextended/NeuronDotNetGPL/source/Core/Network.cs