Doc: IGLib EXTENDED: NUnit.Framework.Constraints.ConstraintExpression Class Reference
NUnit.Framework.Constraints.ConstraintExpression Class Reference
ConstraintExpression represents a compound constraint in the process of being constructed from a series of syntactic elements.
Public Member Functions
ConstraintExpression ()
Initializes a new instance of the ConstraintExpression class.
ConstraintExpression (ConstraintBuilder builder)
Initializes a new instance of the ConstraintExpression class passing in a ConstraintBuilder, which may be pre-populated.
override string ToString ()
Returns a string representation of the expression as it currently stands. This should only be used for testing, since it has the side-effect of resolving the expression.
ConstraintExpression Append (ConstraintOperator op)
Appends an operator to the expression and returns the resulting expression itself.
ResolvableConstraintExpression Append (SelfResolvingOperator op)
Appends a self-resolving operator to the expression and returns a new ResolvableConstraintExpression.
Constraint Append (Constraint constraint)
Appends a constraint to the expression and returns that constraint, which is associated with the current state of the expression being built. Note that the constraint is not reduced at this time. For example, if there is a NotOperator on the stack we don't reduce and return a NotConstraint. The original constraint must be returned because it may support modifiers that are yet to be applied.
ConstraintExpression Exactly (int expectedCount)
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding only if a specified number of them succeed.
ResolvableConstraintExpression Property (string name)
Returns a new PropertyConstraintExpression, which will either test for the existence of the named property on the object being tested or apply any following constraint to that property.
ResolvableConstraintExpression Attribute (Type expectedType)
Returns a new AttributeConstraint checking for the presence of a particular attribute on an object.
ResolvableConstraintExpression Attribute< TExpected > ()
Returns a new AttributeConstraint checking for the presence of a particular attribute on an object.
Constraint Matches (IResolveConstraint constraint)
Returns the constraint provided as an argument - used to allow custom custom constraints to easily participate in the syntax.
Constraint Matches< TActual > (Predicate< TActual > predicate)
Returns the constraint provided as an argument - used to allow custom custom constraints to easily participate in the syntax.
EqualConstraint EqualTo (object expected)
Returns a constraint that tests two items for equality
SameAsConstraint SameAs (object expected)
Returns a constraint that tests that two references are the same object
GreaterThanConstraint GreaterThan (object expected)
Returns a constraint that tests whether the actual value is greater than the supplied argument
GreaterThanOrEqualConstraint GreaterThanOrEqualTo (object expected)
Returns a constraint that tests whether the actual value is greater than or equal to the supplied argument
GreaterThanOrEqualConstraint AtLeast (object expected)
Returns a constraint that tests whether the actual value is greater than or equal to the supplied argument
LessThanConstraint LessThan (object expected)
Returns a constraint that tests whether the actual value is less than the supplied argument
LessThanOrEqualConstraint LessThanOrEqualTo (object expected)
Returns a constraint that tests whether the actual value is less than or equal to the supplied argument
LessThanOrEqualConstraint AtMost (object expected)
Returns a constraint that tests whether the actual value is less than or equal to the supplied argument
ExactTypeConstraint TypeOf (Type expectedType)
Returns a constraint that tests whether the actual value is of the exact type supplied as an argument.
ExactTypeConstraint TypeOf< TExpected > ()
Returns a constraint that tests whether the actual value is of the exact type supplied as an argument.
InstanceOfTypeConstraint InstanceOf (Type expectedType)
Returns a constraint that tests whether the actual value is of the type supplied as an argument or a derived type.
InstanceOfTypeConstraint InstanceOf< TExpected > ()
Returns a constraint that tests whether the actual value is of the type supplied as an argument or a derived type.
AssignableFromConstraint AssignableFrom (Type expectedType)
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
AssignableFromConstraint AssignableFrom< TExpected > ()
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
AssignableToConstraint AssignableTo (Type expectedType)
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
AssignableToConstraint AssignableTo< TExpected > ()
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
CollectionEquivalentConstraint EquivalentTo (IEnumerable expected)
Returns a constraint that tests whether the actual value is a collection containing the same elements as the collection supplied as an argument.
CollectionSubsetConstraint SubsetOf (IEnumerable expected)
Returns a constraint that tests whether the actual value is a subset of the collection supplied as an argument.
CollectionSupersetConstraint SupersetOf (IEnumerable expected)
Returns a constraint that tests whether the actual value is a superset of the collection supplied as an argument.
CollectionContainsConstraint Member (object expected)
Returns a new CollectionContainsConstraint checking for the presence of a particular object in the collection.
CollectionContainsConstraint Contains (object expected)
Returns a new CollectionContainsConstraint checking for the presence of a particular object in the collection.
ContainsConstraint Contains (string expected)
Returns a new ContainsConstraint. This constraint will, in turn, make use of the appropriate second-level constraint, depending on the type of the actual argument. This overload is only used if the item sought is a string, since any other type implies that we are looking for a collection member.
ContainsConstraint Contain (string expected)
Returns a new ContainsConstraint. This constraint will, in turn, make use of the appropriate second-level constraint, depending on the type of the actual argument. This overload is only used if the item sought is a string, since any other type implies that we are looking for a collection member.
SubstringConstraint StringContaining (string expected)
Returns a constraint that succeeds if the actual value contains the substring supplied as an argument.
SubstringConstraint ContainsSubstring (string expected)
Returns a constraint that succeeds if the actual value contains the substring supplied as an argument.
StartsWithConstraint StartWith (string expected)
Returns a constraint that succeeds if the actual value starts with the substring supplied as an argument.
StartsWithConstraint StartsWith (string expected)
Returns a constraint that succeeds if the actual value starts with the substring supplied as an argument.
StartsWithConstraint StringStarting (string expected)
Returns a constraint that succeeds if the actual value starts with the substring supplied as an argument.
EndsWithConstraint EndWith (string expected)
Returns a constraint that succeeds if the actual value ends with the substring supplied as an argument.
EndsWithConstraint EndsWith (string expected)
Returns a constraint that succeeds if the actual value ends with the substring supplied as an argument.
EndsWithConstraint StringEnding (string expected)
Returns a constraint that succeeds if the actual value ends with the substring supplied as an argument.
RegexConstraint Match (string pattern)
Returns a constraint that succeeds if the actual value matches the regular expression supplied as an argument.
RegexConstraint Matches (string pattern)
Returns a constraint that succeeds if the actual value matches the regular expression supplied as an argument.
RegexConstraint StringMatching (string pattern)
Returns a constraint that succeeds if the actual value matches the regular expression supplied as an argument.
SamePathConstraint SamePath (string expected)
Returns a constraint that tests whether the path provided is the same as an expected path after canonicalization.
SubPathConstraint SubPathOf (string expected)
Returns a constraint that tests whether the path provided is the a subpath of the expected path after canonicalization.
SamePathOrUnderConstraint SamePathOrUnder (string expected)
Returns a constraint that tests whether the path provided is the same path or under an expected path after canonicalization.
RangeConstraint InRange (IComparable from, IComparable to)
Returns a constraint that tests whether the actual value falls within a specified range.
Protected Attributes
ConstraintBuilder builder
The ConstraintBuilder holding the elements recognized so far
Properties
ConstraintExpression Not [get]
Returns a ConstraintExpression that negates any following constraint.
ConstraintExpression No [get]
Returns a ConstraintExpression that negates any following constraint.
ConstraintExpression All [get]
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if all of them succeed.
ConstraintExpression Some [get]
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if at least one of them succeeds.
ConstraintExpression None [get]
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if all of them fail.
ResolvableConstraintExpression Length [get]
Returns a new ConstraintExpression, which will apply the following constraint to the Length property of the object being tested.
ResolvableConstraintExpression Count [get]
Returns a new ConstraintExpression, which will apply the following constraint to the Count property of the object being tested.
ResolvableConstraintExpression Message [get]
Returns a new ConstraintExpression, which will apply the following constraint to the Message property of the object being tested.
ResolvableConstraintExpression InnerException [get]
Returns a new ConstraintExpression, which will apply the following constraint to the InnerException property of the object being tested.
ConstraintExpression With [get]
With is currently a NOP - reserved for future use.
NullConstraint Null [get]
Returns a constraint that tests for null
TrueConstraint True [get]
Returns a constraint that tests for True
FalseConstraint False [get]
Returns a constraint that tests for False
GreaterThanConstraint Positive [get]
Returns a constraint that tests for a positive value
LessThanConstraint Negative [get]
Returns a constraint that tests for a negative value
NaNConstraint NaN [get]
Returns a constraint that tests for NaN
EmptyConstraint Empty [get]
Returns a constraint that tests for empty
UniqueItemsConstraint Unique [get]
Returns a constraint that tests whether a collection contains all unique items.
BinarySerializableConstraint BinarySerializable [get]
Returns a constraint that tests whether an object graph is serializable in binary format.
XmlSerializableConstraint XmlSerializable [get]
Returns a constraint that tests whether an object graph is serializable in xml format.
CollectionOrderedConstraint Ordered [get]
Returns a constraint that tests whether a collection is ordered
Constraint Exist [get]
Returns a constraint that succeeds if the value is a file or directory and it exists.
Detailed Description
ConstraintExpression represents a compound constraint in the process of being constructed from a series of syntactic elements.
Individual elements are appended to the expression as they are reorganized. When a constraint is appended, it is returned as the value of the operation so that modifiers may be applied. However, any partially built expression is attached to the constraint for later resolution. When an operator is appended, the partial expression is returned. If it's a self-resolving operator, then a ResolvableConstraintExpression is returned.
Constructor & Destructor Documentation
ConstraintExpression() [1/2]
NUnit.Framework.Constraints.ConstraintExpression.ConstraintExpression () inline
Initializes a new instance of the ConstraintExpression class.
ConstraintExpression() [2/2]
NUnit.Framework.Constraints.ConstraintExpression.ConstraintExpression (ConstraintBuilder builder) inline
Initializes a new instance of the ConstraintExpression class passing in a ConstraintBuilder, which may be pre-populated.
Parameters
builder The builder.
References NUnit.Framework.Constraints.ConstraintExpression.builder.
Member Function Documentation
ToString()
override string NUnit.Framework.Constraints.ConstraintExpression.ToString () inline
Returns a string representation of the expression as it currently stands. This should only be used for testing, since it has the side-effect of resolving the expression.
Returns
References NUnit.Framework.Constraints.ConstraintExpression.builder, and NUnit.Framework.Constraints.ConstraintBuilder.Resolve().
Append() [1/3]
ConstraintExpression NUnit.Framework.Constraints.ConstraintExpression.Append (ConstraintOperator op) inline
Appends an operator to the expression and returns the resulting expression itself.
References NUnit.Framework.Constraints.ConstraintBuilder.Append(), and NUnit.Framework.Constraints.ConstraintExpression.builder.
Referenced by NUnit.Framework.Constraints.ConstraintExpression.AssignableFrom(), NUnit.Framework.Constraints.ConstraintExpression.AssignableFrom< TExpected >(), NUnit.Framework.Constraints.ConstraintExpression.AssignableTo(), NUnit.Framework.Constraints.ConstraintExpression.AssignableTo< TExpected >(), NUnit.Framework.Constraints.ConstraintExpression.AtLeast(), NUnit.Framework.Constraints.ConstraintExpression.AtMost(), NUnit.Framework.Constraints.ConstraintExpression.Attribute(), NUnit.Framework.Constraints.ConstraintExpression.Contain(), NUnit.Framework.Constraints.ConstraintExpression.Contains(), NUnit.Framework.Constraints.ConstraintExpression.ContainsSubstring(), NUnit.Framework.Constraints.ConstraintExpression.EndsWith(), NUnit.Framework.Constraints.ConstraintExpression.EndWith(), NUnit.Framework.Constraints.ConstraintExpression.EqualTo(), NUnit.Framework.Constraints.ConstraintExpression.EquivalentTo(), NUnit.Framework.Constraints.ConstraintExpression.Exactly(), NUnit.Framework.Constraints.ConstraintExpression.GreaterThan(), NUnit.Framework.Constraints.ConstraintExpression.GreaterThanOrEqualTo(), NUnit.Framework.Constraints.ConstraintExpression.InRange(), NUnit.Framework.Constraints.ConstraintExpression.InstanceOf(), NUnit.Framework.Constraints.ConstraintExpression.InstanceOf< TExpected >(), NUnit.Framework.Constraints.ConstraintExpression.LessThan(), NUnit.Framework.Constraints.ConstraintExpression.LessThanOrEqualTo(), NUnit.Framework.Constraints.ConstraintExpression.Match(), NUnit.Framework.Constraints.ConstraintExpression.Matches(), NUnit.Framework.Constraints.ConstraintExpression.Matches< TActual >(), NUnit.Framework.Constraints.ConstraintExpression.Member(), NUnit.Framework.Constraints.ConstraintExpression.Property(), NUnit.Framework.Constraints.ConstraintExpression.SameAs(), NUnit.Framework.Constraints.ConstraintExpression.SamePath(), NUnit.Framework.Constraints.ConstraintExpression.SamePathOrUnder(), NUnit.Framework.Constraints.ConstraintExpression.StartsWith(), NUnit.Framework.Constraints.ConstraintExpression.StartWith(), NUnit.Framework.Constraints.ConstraintExpression.StringContaining(), NUnit.Framework.Constraints.ConstraintExpression.StringEnding(), NUnit.Framework.Constraints.ConstraintExpression.StringMatching(), NUnit.Framework.Constraints.ConstraintExpression.StringStarting(), NUnit.Framework.Constraints.ConstraintExpression.SubPathOf(), NUnit.Framework.Constraints.ConstraintExpression.SubsetOf(), NUnit.Framework.Constraints.ConstraintExpression.SupersetOf(), NUnit.Framework.Constraints.ConstraintExpression.TypeOf(), and NUnit.Framework.Constraints.ConstraintExpression.TypeOf< TExpected >().
Append() [2/3]
ResolvableConstraintExpression NUnit.Framework.Constraints.ConstraintExpression.Append (SelfResolvingOperator op) inline
Appends a self-resolving operator to the expression and returns a new ResolvableConstraintExpression.
References NUnit.Framework.Constraints.ConstraintBuilder.Append(), and NUnit.Framework.Constraints.ConstraintExpression.builder.
Append() [3/3]
Constraint NUnit.Framework.Constraints.ConstraintExpression.Append (Constraint constraint) inline
Appends a constraint to the expression and returns that constraint, which is associated with the current state of the expression being built. Note that the constraint is not reduced at this time. For example, if there is a NotOperator on the stack we don't reduce and return a NotConstraint. The original constraint must be returned because it may support modifiers that are yet to be applied.
References NUnit.Framework.Constraints.ConstraintBuilder.Append(), and NUnit.Framework.Constraints.ConstraintExpression.builder.
Exactly()
ConstraintExpression NUnit.Framework.Constraints.ConstraintExpression.Exactly (int expectedCount) inline
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding only if a specified number of them succeed.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Has.Exactly().
Property()
ResolvableConstraintExpression NUnit.Framework.Constraints.ConstraintExpression.Property (string name) inline
Returns a new PropertyConstraintExpression, which will either test for the existence of the named property on the object being tested or apply any following constraint to that property.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.ApplyMatchesToProperty(), NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests(), NUnit.Framework.Has.Property(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Syntax.AttributeTestWithFollowingConstraint.SetUp(), NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionTypeOfAndConstraint(), NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionWithConstraint(), NUnit.Framework.Syntax.ThrowsTests.ThrowsTypeOfAndConstraint(), and NUnit.Framework.Syntax.ThrowsTests.ThrowsTypeOfWithConstraint().
Attribute()
ResolvableConstraintExpression NUnit.Framework.Constraints.ConstraintExpression.Attribute (Type expectedType) inline
Returns a new AttributeConstraint checking for the presence of a particular attribute on an object.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Has.Attribute(), and NUnit.Framework.Constraints.ConstraintExpression.Attribute< TExpected >().
Attribute< TExpected >()
ResolvableConstraintExpression NUnit.Framework.Constraints.ConstraintExpression.Attribute< TExpected > () inline
Returns a new AttributeConstraint checking for the presence of a particular attribute on an object.
References NUnit.Framework.Constraints.ConstraintExpression.Attribute().
Matches() [1/2]
Constraint NUnit.Framework.Constraints.ConstraintExpression.Matches (IResolveConstraint constraint) inline
Returns the constraint provided as an argument - used to allow custom custom constraints to easily participate in the syntax.
References NUnit.Framework.Constraints.ConstraintExpression.Append(), and NUnit.Framework.Constraints.IResolveConstraint.Resolve().
Referenced by NUnit.Framework.Syntax.ArbitraryConstraintMatching.ApplyMatchesToProperty(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraint(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraintAfterPrefix(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraintsUnderAndOperator(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchLambda(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchPredicate(), NUnit.Framework.Constraints.ConstraintFactory.DoesNotMatch(), and NUnit.Framework.Tests.AssertSyntaxTests.RegularExpressionTests().
Matches< TActual >()
Constraint NUnit.Framework.Constraints.ConstraintExpression.Matches< TActual > (Predicate< TActual > predicate) inline
Returns the constraint provided as an argument - used to allow custom custom constraints to easily participate in the syntax.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
EqualTo()
EqualConstraint NUnit.Framework.Constraints.ConstraintExpression.EqualTo (object expected) inline
Returns a constraint that tests two items for equality
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.ApplyMatchesToProperty(), NUnit.Framework.CollectionAssert.AreNotEqual(), NUnit.Framework.Assertions.ArrayNotEqualFixture.ArraysDeclaredAsDifferentTypes(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysWithDifferentDimensionsMatchedAsCollection(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysWithDifferentRanksComparedAsCollection(), NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests(), NUnit.Framework.Assertions.ArrayNotEqualFixture.DifferentLengthArrays(), NUnit.Framework.Tests.AssertSyntaxTests.EqualIgnoringCaseTests(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTests(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTestsWithTolerance(), NUnit.Framework.Constraints.NotConstraintTests.NotHonorsIgnoreCaseUsingPrefixNotation(), NUnit.Framework.Constraints.NotConstraintTests.NotHonorsTolerance(), NUnit.Framework.Tests.AssertSyntaxTests.NotTests(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Assertions.ArrayNotEqualFixture.SameLengthDifferentContent(), NUnit.Framework.Syntax.PropertyExistsTest_AndFollows.SetUp(), NUnit.Framework.Syntax.AfterTest_PropertyTest.SetUp(), NUnit.Framework.Syntax.SomeTest.SetUp(), NUnit.Framework.Syntax.SomeTest_BeforeBinaryOperators.SetUp(), NUnit.Framework.Syntax.CountTest.SetUp(), NUnit.Framework.Syntax.OrTest_ThreeOrs.SetUp(), NUnit.Framework.Syntax.AndIsEvaluatedBeforeFollowingOr.SetUp(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestGlobalDefaultTolerance_Failure(), NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionTypeOfAndConstraint(), NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionWithConstraint(), NUnit.Framework.Syntax.ThrowsTests.ThrowsTypeOfAndConstraint(), and NUnit.Framework.Syntax.ThrowsTests.ThrowsTypeOfWithConstraint().
SameAs()
SameAsConstraint NUnit.Framework.Constraints.ConstraintExpression.SameAs (object expected) inline
Returns a constraint that tests that two references are the same object
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests().
GreaterThan()
GreaterThanConstraint NUnit.Framework.Constraints.ConstraintExpression.GreaterThan (object expected) inline
Returns a constraint that tests whether the actual value is greater than the supplied argument
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests(), NUnit.Framework.Syntax.MixedOperatorOverrides.ComplexTests(), NUnit.Framework.Tests.AssertSyntaxTests.ComplexTests(), NUnit.Framework.Tests.AssertSyntaxTests.NoItemTests(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Syntax.AndOperatorOverride.SetUp(), NUnit.Framework.Syntax.PropertyTest_ConstraintFollows.SetUp(), NUnit.Framework.Syntax.AllTest.SetUp(), NUnit.Framework.Syntax.PropertyTest_NotFollows.SetUp(), NUnit.Framework.Syntax.LengthTest.SetUp(), NUnit.Framework.Syntax.SomeTest_BeforeBinaryOperators.SetUp(), NUnit.Framework.Syntax.SomeTest_UseOfAndSome.SetUp(), NUnit.Framework.Syntax.AndTest_ThreeAndsWithNot.SetUp(), NUnit.Framework.Syntax.OrTest.SetUp(), NUnit.Framework.Syntax.OrTest_ThreeOrs.SetUp(), NUnit.Framework.Syntax.AndIsEvaluatedBeforeFollowingOr.SetUp(), and NUnit.Framework.Syntax.AndIsEvaluatedBeforePrecedingOr.SetUp().
GreaterThanOrEqualTo()
GreaterThanOrEqualConstraint NUnit.Framework.Constraints.ConstraintExpression.GreaterThanOrEqualTo (object expected) inline
Returns a constraint that tests whether the actual value is greater than or equal to the supplied argument
References NUnit.Framework.Constraints.ConstraintExpression.Append().
AtLeast()
GreaterThanOrEqualConstraint NUnit.Framework.Constraints.ConstraintExpression.AtLeast (object expected) inline
Returns a constraint that tests whether the actual value is greater than or equal to the supplied argument
References NUnit.Framework.Constraints.ConstraintExpression.Append().
LessThan()
LessThanConstraint NUnit.Framework.Constraints.ConstraintExpression.LessThan (object expected) inline
Returns a constraint that tests whether the actual value is less than the supplied argument
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests(), NUnit.Framework.Syntax.MixedOperatorOverrides.ComplexTests(), NUnit.Framework.Tests.AssertSyntaxTests.ComplexTests(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Syntax.AndOperatorOverride.SetUp(), NUnit.Framework.Syntax.OrOperatorOverride.SetUp(), NUnit.Framework.Syntax.AfterTest_AndOperator.SetUp(), NUnit.Framework.Syntax.SomeTest_BeforeBinaryOperators.SetUp(), NUnit.Framework.Syntax.SomeTest_NestedSome.SetUp(), NUnit.Framework.Syntax.SomeTest_UseOfAndSome.SetUp(), NUnit.Framework.Syntax.NoneTest.SetUp(), NUnit.Framework.Syntax.AndTest.SetUp(), NUnit.Framework.Syntax.AndTest_ThreeAndsWithNot.SetUp(), and NUnit.Framework.Syntax.AndIsEvaluatedBeforePrecedingOr.SetUp().
LessThanOrEqualTo()
LessThanOrEqualConstraint NUnit.Framework.Constraints.ConstraintExpression.LessThanOrEqualTo (object expected) inline
Returns a constraint that tests whether the actual value is less than or equal to the supplied argument
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests().
AtMost()
LessThanOrEqualConstraint NUnit.Framework.Constraints.ConstraintExpression.AtMost (object expected) inline
Returns a constraint that tests whether the actual value is less than or equal to the supplied argument
References NUnit.Framework.Constraints.ConstraintExpression.Append().
TypeOf()
ExactTypeConstraint NUnit.Framework.Constraints.ConstraintExpression.TypeOf (Type expectedType) inline
Returns a constraint that tests whether the actual value is of the exact type supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.ExactTypeTests(), NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests.FailsWhenKeyIsMissing(), NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests.FailsWhenValueIsMissing(), NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionTypeOf(), NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionTypeOfAndConstraint(), and NUnit.Framework.Throws.TypeOf().
TypeOf< TExpected >()
ExactTypeConstraint NUnit.Framework.Constraints.ConstraintExpression.TypeOf< TExpected > () inline
Returns a constraint that tests whether the actual value is of the exact type supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
InstanceOf()
InstanceOfTypeConstraint NUnit.Framework.Constraints.ConstraintExpression.InstanceOf (Type expectedType) inline
Returns a constraint that tests whether the actual value is of the type supplied as an argument or a derived type.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.CollectionAssert.AllItemsAreInstancesOfType(), NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Throws.InstanceOf(), NUnit.Framework.Tests.AssertSyntaxTests.InstanceOfTests(), NUnit.Framework.Tests.AssertSyntaxTests.NoItemTests(), NUnit.Framework.Tests.AssertSyntaxTests.SomeItemTests(), and NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionInstanceOf().
InstanceOf< TExpected >()
InstanceOfTypeConstraint NUnit.Framework.Constraints.ConstraintExpression.InstanceOf< TExpected > () inline
Returns a constraint that tests whether the actual value is of the type supplied as an argument or a derived type.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
AssignableFrom()
AssignableFromConstraint NUnit.Framework.Constraints.ConstraintExpression.AssignableFrom (Type expectedType) inline
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AssignableFromTypeTests().
AssignableFrom< TExpected >()
AssignableFromConstraint NUnit.Framework.Constraints.ConstraintExpression.AssignableFrom< TExpected > () inline
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
AssignableTo()
AssignableToConstraint NUnit.Framework.Constraints.ConstraintExpression.AssignableTo (Type expectedType) inline
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
AssignableTo< TExpected >()
AssignableToConstraint NUnit.Framework.Constraints.ConstraintExpression.AssignableTo< TExpected > () inline
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
EquivalentTo()
CollectionEquivalentConstraint NUnit.Framework.Constraints.ConstraintExpression.EquivalentTo (IEnumerable expected) inline
Returns a constraint that tests whether the actual value is a collection containing the same elements as the collection supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.CollectionAssert.AreNotEquivalent(), and NUnit.Framework.Tests.AssertSyntaxTests.CollectionEquivalenceTests().
SubsetOf()
CollectionSubsetConstraint NUnit.Framework.Constraints.ConstraintExpression.SubsetOf (IEnumerable expected) inline
Returns a constraint that tests whether the actual value is a subset of the collection supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.CollectionAssert.IsNotSubsetOf(), and NUnit.Framework.Tests.AssertSyntaxTests.SubsetTests().
SupersetOf()
CollectionSupersetConstraint NUnit.Framework.Constraints.ConstraintExpression.SupersetOf (IEnumerable expected) inline
Returns a constraint that tests whether the actual value is a superset of the collection supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.CollectionAssert.IsNotSupersetOf().
Member()
CollectionContainsConstraint NUnit.Framework.Constraints.ConstraintExpression.Member (object expected) inline
Returns a new CollectionContainsConstraint checking for the presence of a particular object in the collection.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests(), and NUnit.Framework.CollectionAssert.DoesNotContain().
Contains() [1/2]
CollectionContainsConstraint NUnit.Framework.Constraints.ConstraintExpression.Contains (object expected) inline
Returns a new CollectionContainsConstraint checking for the presence of a particular object in the collection.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests(), NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests.FailsWhenNotUsedAgainstADictionary(), NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests.FailsWhenNotUsedAgainstADictionary(), NUnit.Framework.Tests.AssertSyntaxTests.SubstringTests(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestModeMustFollowTolerance(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestModesCanOnlyBeUsedOnce(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestNumericToleranceRequired(), and NUnit.Framework.Tests.Constraints.ToleranceTests.TestWithinCanOnlyBeUsedOnce().
Contains() [2/2]
ContainsConstraint NUnit.Framework.Constraints.ConstraintExpression.Contains (string expected) inline
Returns a new ContainsConstraint. This constraint will, in turn, make use of the appropriate second-level constraint, depending on the type of the actual argument. This overload is only used if the item sought is a string, since any other type implies that we are looking for a collection member.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Contain()
ContainsConstraint NUnit.Framework.Constraints.ConstraintExpression.Contain (string expected) inline
Returns a new ContainsConstraint. This constraint will, in turn, make use of the appropriate second-level constraint, depending on the type of the actual argument. This overload is only used if the item sought is a string, since any other type implies that we are looking for a collection member.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.StringAssert.DoesNotContain().
StringContaining()
SubstringConstraint NUnit.Framework.Constraints.ConstraintExpression.StringContaining (string expected) inline
Returns a constraint that succeeds if the actual value contains the substring supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), and NUnit.Framework.Tests.AssertSyntaxTests.SubstringTests().
ContainsSubstring()
SubstringConstraint NUnit.Framework.Constraints.ConstraintExpression.ContainsSubstring (string expected) inline
Returns a constraint that succeeds if the actual value contains the substring supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Constraints.ConstraintFactory.DoesNotContain().
StartWith()
StartsWithConstraint NUnit.Framework.Constraints.ConstraintExpression.StartWith (string expected) inline
Returns a constraint that succeeds if the actual value starts with the substring supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.StringAssert.DoesNotStartWith().
StartsWith()
StartsWithConstraint NUnit.Framework.Constraints.ConstraintExpression.StartsWith (string expected) inline
Returns a constraint that succeeds if the actual value starts with the substring supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Constraints.ConstraintFactory.DoesNotStartWith(), NUnit.Framework.Tests.AssertSyntaxTests.NoItemTests(), NUnit.Framework.Syntax.MessageTest.SetUp(), NUnit.Framework.Tests.AssertSyntaxTests.SomeItemTests(), and NUnit.Framework.Tests.AssertSyntaxTests.StartsWithTests().
StringStarting()
StartsWithConstraint NUnit.Framework.Constraints.ConstraintExpression.StringStarting (string expected) inline
Returns a constraint that succeeds if the actual value starts with the substring supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.StartsWithTests().
EndWith()
EndsWithConstraint NUnit.Framework.Constraints.ConstraintExpression.EndWith (string expected) inline
Returns a constraint that succeeds if the actual value ends with the substring supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.StringAssert.DoesNotEndWith().
EndsWith()
EndsWithConstraint NUnit.Framework.Constraints.ConstraintExpression.EndsWith (string expected) inline
Returns a constraint that succeeds if the actual value ends with the substring supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Constraints.ConstraintFactory.DoesNotEndWith(), and NUnit.Framework.Tests.AssertSyntaxTests.EndsWithTests().
StringEnding()
EndsWithConstraint NUnit.Framework.Constraints.ConstraintExpression.StringEnding (string expected) inline
Returns a constraint that succeeds if the actual value ends with the substring supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.EndsWithTests().
Match()
RegexConstraint NUnit.Framework.Constraints.ConstraintExpression.Match (string pattern) inline
Returns a constraint that succeeds if the actual value matches the regular expression supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Matches() [2/2]
RegexConstraint NUnit.Framework.Constraints.ConstraintExpression.Matches (string pattern) inline
Returns a constraint that succeeds if the actual value matches the regular expression supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
StringMatching()
RegexConstraint NUnit.Framework.Constraints.ConstraintExpression.StringMatching (string pattern) inline
Returns a constraint that succeeds if the actual value matches the regular expression supplied as an argument.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.RegularExpressionTests().
SamePath()
SamePathConstraint NUnit.Framework.Constraints.ConstraintExpression.SamePath (string expected) inline
Returns a constraint that tests whether the path provided is the same as an expected path after canonicalization.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Syntax.NotSamePathTest_IgnoreCase.SetUp(), and NUnit.Framework.Syntax.NotSamePathTest_RespectCase.SetUp().
SubPathOf()
SubPathConstraint NUnit.Framework.Constraints.ConstraintExpression.SubPathOf (string expected) inline
Returns a constraint that tests whether the path provided is the a subpath of the expected path after canonicalization.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
SamePathOrUnder()
SamePathOrUnderConstraint NUnit.Framework.Constraints.ConstraintExpression.SamePathOrUnder (string expected) inline
Returns a constraint that tests whether the path provided is the same path or under an expected path after canonicalization.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Referenced by NUnit.Framework.Syntax.NotSamePathOrUnderTest_IgnoreCase.SetUp(), and NUnit.Framework.Syntax.NotSamePathOrUnderTest_RespectCase.SetUp().
InRange()
RangeConstraint NUnit.Framework.Constraints.ConstraintExpression.InRange (IComparable from, IComparable to) inline
Returns a constraint that tests whether the actual value falls within a specified range.
References NUnit.Framework.Constraints.ConstraintExpression.Append().
Member Data Documentation
builder
ConstraintBuilder NUnit.Framework.Constraints.ConstraintExpression.builder protected
The ConstraintBuilder holding the elements recognized so far
Referenced by NUnit.Framework.Constraints.ConstraintExpression.Append(), NUnit.Framework.Constraints.ConstraintExpression.ConstraintExpression(), NUnit.Framework.Constraints.ResolvableConstraintExpression.Resolve(), and NUnit.Framework.Constraints.ConstraintExpression.ToString().
Property Documentation
Not
ConstraintExpression NUnit.Framework.Constraints.ConstraintExpression.Not get
Returns a ConstraintExpression that negates any following constraint.
Referenced by NUnit.Framework.CollectionAssert.AllItemsAreNotNull(), NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Constraints.ConstraintFactory.DoesNotContain(), NUnit.Framework.Constraints.ConstraintFactory.DoesNotEndWith(), NUnit.Framework.Constraints.ConstraintFactory.DoesNotMatch(), NUnit.Framework.Constraints.ConstraintFactory.DoesNotStartWith(), NUnit.Framework.Tests.AssertSyntaxTests.NotTests(), NUnit.Framework.Syntax.NotTest_Cascaded.SetUp(), NUnit.Framework.Syntax.PropertyTest_NotFollows.SetUp(), NUnit.Framework.Syntax.AttributeTestWithFollowingConstraint.SetUp(), NUnit.Framework.Syntax.AndTest_ThreeAndsWithNot.SetUp(), and NUnit.Framework.Tests.AssertSyntaxTests.SomeItemTests().
No
ConstraintExpression NUnit.Framework.Constraints.ConstraintExpression.No get
Returns a ConstraintExpression that negates any following constraint.
All
ConstraintExpression NUnit.Framework.Constraints.ConstraintExpression.All get
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if all of them succeed.
Some
ConstraintExpression NUnit.Framework.Constraints.ConstraintExpression.Some get
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if at least one of them succeeds.
Referenced by NUnit.Framework.Syntax.SomeTest_NestedSome.SetUp(), and NUnit.Framework.Syntax.SomeTest_UseOfAndSome.SetUp().
None
ConstraintExpression NUnit.Framework.Constraints.ConstraintExpression.None get
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if all of them fail.
Length
ResolvableConstraintExpression NUnit.Framework.Constraints.ConstraintExpression.Length get
Returns a new ConstraintExpression, which will apply the following constraint to the Length property of the object being tested.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests(), and NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests().
Count
ResolvableConstraintExpression NUnit.Framework.Constraints.ConstraintExpression.Count get
Returns a new ConstraintExpression, which will apply the following constraint to the Count property of the object being tested.
Referenced by NUnit.Framework.Syntax.ArbitraryConstraintMatching.ApplyMatchesToProperty().
Message
ResolvableConstraintExpression NUnit.Framework.Constraints.ConstraintExpression.Message get
Returns a new ConstraintExpression, which will apply the following constraint to the Message property of the object being tested.
Referenced by NUnit.Framework.Tests.Constraints.DictionaryContainsKeyConstraintTests.FailsWhenNotUsedAgainstADictionary(), NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests.FailsWhenNotUsedAgainstADictionary(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestModeMustFollowTolerance(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestModesCanOnlyBeUsedOnce(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestNumericToleranceRequired(), and NUnit.Framework.Tests.Constraints.ToleranceTests.TestWithinCanOnlyBeUsedOnce().
InnerException
ResolvableConstraintExpression NUnit.Framework.Constraints.ConstraintExpression.InnerException get
Returns a new ConstraintExpression, which will apply the following constraint to the InnerException property of the object being tested.
With
ConstraintExpression NUnit.Framework.Constraints.ConstraintExpression.With get
With is currently a NOP - reserved for future use.
Referenced by NUnit.Framework.Syntax.ArbitraryConstraintMatching.ApplyMatchesToProperty(), NUnit.Framework.Syntax.SomeTest_NestedSome.SetUp(), and NUnit.Framework.Syntax.ThrowsTests.ThrowsExceptionWithConstraint().
Null
NullConstraint NUnit.Framework.Constraints.ConstraintExpression.Null get
Returns a constraint that tests for null
Referenced by NUnit.Framework.CollectionAssert.AllItemsAreNotNull(), NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Syntax.MixedOperatorOverrides.ComplexTests(), NUnit.Framework.Tests.AssertSyntaxTests.ComplexTests(), NUnit.Framework.Tests.AssertSyntaxTests.IsNotNull(), NUnit.Framework.Assert.IsNotNull(), NUnit.Framework.Tests.AssertSyntaxTests.NoItemTests(), NUnit.Framework.Assert.NotNull(), NUnit.Framework.Tests.AssertSyntaxTests.NotTests(), NUnit.Framework.Syntax.NotOperatorOverride.SetUp(), NUnit.Framework.Syntax.NotTest.SetUp(), NUnit.Framework.Syntax.NotTest_Cascaded.SetUp(), NUnit.Framework.Syntax.AttributeTestWithFollowingConstraint.SetUp(), NUnit.Framework.Syntax.AndTest_ThreeAndsWithNot.SetUp(), and NUnit.Framework.Tests.AssertSyntaxTests.SomeItemTests().
True
TrueConstraint NUnit.Framework.Constraints.ConstraintExpression.True get
Returns a constraint that tests for True
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.NotTests().
False
FalseConstraint NUnit.Framework.Constraints.ConstraintExpression.False get
Returns a constraint that tests for False
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.NotTests().
Positive
GreaterThanConstraint NUnit.Framework.Constraints.ConstraintExpression.Positive get
Returns a constraint that tests for a positive value
Negative
LessThanConstraint NUnit.Framework.Constraints.ConstraintExpression.Negative get
Returns a constraint that tests for a negative value
NaN
NaNConstraint NUnit.Framework.Constraints.ConstraintExpression.NaN get
Returns a constraint that tests for NaN
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.NotTests().
Empty
EmptyConstraint NUnit.Framework.Constraints.ConstraintExpression.Empty get
Returns a constraint that tests for empty
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.EmptyCollectionTests(), NUnit.Framework.Tests.AssertSyntaxTests.EmptyStringTests(), and NUnit.Framework.Assert.IsNotEmpty().
Unique
UniqueItemsConstraint NUnit.Framework.Constraints.ConstraintExpression.Unique get
Returns a constraint that tests whether a collection contains all unique items.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests().
BinarySerializable
BinarySerializableConstraint NUnit.Framework.Constraints.ConstraintExpression.BinarySerializable get
Returns a constraint that tests whether an object graph is serializable in binary format.
XmlSerializable
XmlSerializableConstraint NUnit.Framework.Constraints.ConstraintExpression.XmlSerializable get
Returns a constraint that tests whether an object graph is serializable in xml format.
Ordered
CollectionOrderedConstraint NUnit.Framework.Constraints.ConstraintExpression.Ordered get
Returns a constraint that tests whether a collection is ordered
Exist
Constraint NUnit.Framework.Constraints.ConstraintExpression.Exist get
Returns a constraint that succeeds if the value is a file or directory and it exists.
Referenced by NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenDirectoryInfoDoesNotExist(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenDirectoryStringDoesNotExist(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenFileInfoDoesNotExist(), NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.FailsWhenFileStringDoesNotExist(), and NUnit.Framework.Tests.Constraints.FileOrDirectoryExistsConstraintTests.SetUp().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Constraints/ConstraintExpression.cs