Doc: IGLib EXTENDED: alglib.testsparseunit Class Reference
alglib.testsparseunit Class Reference
Static Public Member Functions
static bool testsparse (bool silent)
static bool basicfunctest ()
static bool basicfunctestcrs ()
static bool basicfuncrandomtest ()
static bool linearfunctionstest ()
static bool linearfunctionsstest ()
static bool linearfunctionsmmtest ()
static bool linearfunctionssmmtest ()
static bool basiccopyfunctest (bool silent)
static bool copyfunctest (bool silent)
static bool testsparse (bool silent)
static bool _pexec_testsparse (bool silent)
static bool basicfunctest ()
static bool basicfunctestcrs ()
static bool basicfuncrandomtest ()
static bool linearfunctionstest ()
static bool linearfunctionsstest ()
static bool linearfunctionsmmtest ()
static bool linearfunctionssmmtest ()
static bool basiccopyfunctest (bool silent)
static bool copyfunctest (bool silent)
Static Private Member Functions
static void createrandom (int m, int n, int pkind, int ckind, int p0, int p1, ref double[,] da, sparse.sparsematrix sa)
static bool enumeratetest ()
static bool rewriteexistingtest ()
static void createrandom (int m, int n, int pkind, int ckind, int p0, int p1, ref double[,] da, sparse.sparsematrix sa)
static bool enumeratetest ()
static bool rewriteexistingtest ()
static bool testgetrow ()
static bool testconvertsm ()
static bool testgcmatrixtype ()
Member Function Documentation
testsparse() [1/2]
static bool alglib.testsparseunit.testsparse (bool silent) inline static
References alglib.testsparseunit.basiccopyfunctest(), alglib.testsparseunit.basicfuncrandomtest(), alglib.testsparseunit.basicfunctest(), alglib.testsparseunit.basicfunctestcrs(), alglib.testsparseunit.copyfunctest(), alglib.testsparseunit.enumeratetest(), alglib.testsparseunit.linearfunctionsmmtest(), alglib.testsparseunit.linearfunctionssmmtest(), alglib.testsparseunit.linearfunctionsstest(), alglib.testsparseunit.linearfunctionstest(), and alglib.testsparseunit.rewriteexistingtest().
Referenced by alglib.testsparseunit._pexec_testsparse(), and _Test.Main().
basicfunctest() [1/2]
static bool alglib.testsparseunit.basicfunctest () inline static
References alglib.sparse.sparseadd(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparseget(), and alglib.sparse.sparseset().
Referenced by alglib.testsparseunit.testsparse().
basicfunctestcrs() [1/2]
static bool alglib.testsparseunit.basicfunctestcrs () inline static
References alglib.math.machineepsilon, alglib.sparse.sparsecreatecrs(), alglib.sparse.sparseget(), alglib.sparse.sparsemtv(), alglib.sparse.sparsemv(), and alglib.sparse.sparseset().
Referenced by alglib.testsparseunit.testsparse().
basicfuncrandomtest() [1/2]
static bool alglib.testsparseunit.basicfuncrandomtest () inline static
References alglib.math.randominteger(), alglib.sparse.sparseadd(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparseget(), and alglib.sparse.sparseset().
Referenced by alglib.testsparseunit.testsparse().
linearfunctionstest() [1/2]
static bool alglib.testsparseunit.linearfunctionstest () inline static
References alglib.testsparseunit.createrandom(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.sparse.sparsemtv(), alglib.sparse.sparsemv(), and alglib.sparse.sparsemv2().
Referenced by alglib.testsparseunit.testsparse().
linearfunctionsstest() [1/2]
static bool alglib.testsparseunit.linearfunctionsstest () inline static
References alglib.testsparseunit.createrandom(), alglib.math.machineepsilon, alglib.math.randomreal(), and alglib.sparse.sparsesmv().
Referenced by alglib.testsparseunit.testsparse().
linearfunctionsmmtest() [1/2]
static bool alglib.testsparseunit.linearfunctionsmmtest () inline static
References alglib.testsparseunit.createrandom(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.sparse.sparsemm(), alglib.sparse.sparsemm2(), and alglib.sparse.sparsemtm().
Referenced by alglib.testsparseunit.testsparse().
linearfunctionssmmtest() [1/2]
static bool alglib.testsparseunit.linearfunctionssmmtest () inline static
References alglib.testsparseunit.createrandom(), alglib.math.machineepsilon, alglib.math.randomreal(), and alglib.sparse.sparsesmm().
Referenced by alglib.testsparseunit.testsparse().
basiccopyfunctest() [1/2]
static bool alglib.testsparseunit.basiccopyfunctest (bool silent) inline static
References alglib.sparse.sparseadd(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecopy(), alglib.sparse.sparsecreate(), alglib.sparse.sparsecreatecrs(), alglib.sparse.sparseget(), and alglib.sparse.sparseset().
Referenced by alglib.testsparseunit.testsparse().
copyfunctest() [1/2]
static bool alglib.testsparseunit.copyfunctest (bool silent) inline static
References alglib.testsparseunit.createrandom(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.sparse.sparsecopy(), alglib.sparse.sparseget(), alglib.sparse.sparsemtv(), alglib.sparse.sparsemv(), and alglib.sparse.sparsemv2().
Referenced by alglib.testsparseunit.testsparse().
createrandom() [1/2]
static void alglib.testsparseunit.createrandom (int m, int n, int pkind, int ckind, int p0, int p1, ref double da[,], sparse.sparsematrix sa) inline static private
References alglib.ap.assert(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.sparse.sparseadd(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparsecreatecrs(), and alglib.sparse.sparseset().
Referenced by alglib.testsparseunit.copyfunctest(), alglib.testsparseunit.linearfunctionsmmtest(), alglib.testsparseunit.linearfunctionssmmtest(), alglib.testsparseunit.linearfunctionsstest(), and alglib.testsparseunit.linearfunctionstest().
enumeratetest() [1/2]
static bool alglib.testsparseunit.enumeratetest () inline static private
References alglib.math.randominteger(), alglib.math.randomreal(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparseenumerate(), and alglib.sparse.sparseset().
Referenced by alglib.testsparseunit.testsparse().
rewriteexistingtest() [1/2]
static bool alglib.testsparseunit.rewriteexistingtest () inline static private
References alglib.math.randominteger(), alglib.math.randomreal(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparseget(), alglib.sparse.sparserewriteexisting(), and alglib.sparse.sparseset().
Referenced by alglib.testsparseunit.testsparse().
testsparse() [2/2]
static bool alglib.testsparseunit.testsparse (bool silent) inline static
References alglib.testsparseunit.basiccopyfunctest(), alglib.testsparseunit.basicfuncrandomtest(), alglib.testsparseunit.basicfunctest(), alglib.testsparseunit.basicfunctestcrs(), alglib.testsparseunit.copyfunctest(), alglib.testsparseunit.enumeratetest(), alglib.testsparseunit.linearfunctionsmmtest(), alglib.testsparseunit.linearfunctionssmmtest(), alglib.testsparseunit.linearfunctionsstest(), alglib.testsparseunit.linearfunctionstest(), alglib.testsparseunit.rewriteexistingtest(), alglib.testsparseunit.testconvertsm(), alglib.testsparseunit.testgcmatrixtype(), and alglib.testsparseunit.testgetrow().
_pexec_testsparse()
static bool alglib.testsparseunit._pexec_testsparse (bool silent) inline static
References alglib.testsparseunit.testsparse().
Referenced by _Test.Main().
basicfunctest() [2/2]
static bool alglib.testsparseunit.basicfunctest () inline static
References alglib.sparse.sparseadd(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparseget(), alglib.sparse.sparsegetdiagonal(), and alglib.sparse.sparseset().
basicfunctestcrs() [2/2]
static bool alglib.testsparseunit.basicfunctestcrs () inline static
References alglib.math.machineepsilon, alglib.sparse.sparsecreatecrs(), alglib.sparse.sparseget(), alglib.sparse.sparsemtv(), alglib.sparse.sparsemv(), and alglib.sparse.sparseset().
basicfuncrandomtest() [2/2]
static bool alglib.testsparseunit.basicfuncrandomtest () inline static
References alglib.math.randominteger(), alglib.sparse.sparseadd(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparseget(), and alglib.sparse.sparseset().
linearfunctionstest() [2/2]
static bool alglib.testsparseunit.linearfunctionstest () inline static
References alglib.testsparseunit.createrandom(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.sparse.sparsemtv(), alglib.sparse.sparsemv(), and alglib.sparse.sparsemv2().
linearfunctionsstest() [2/2]
static bool alglib.testsparseunit.linearfunctionsstest () inline static
References alglib.testsparseunit.createrandom(), alglib.math.machineepsilon, alglib.math.randomreal(), and alglib.sparse.sparsesmv().
linearfunctionsmmtest() [2/2]
static bool alglib.testsparseunit.linearfunctionsmmtest () inline static
References alglib.testsparseunit.createrandom(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.sparse.sparsemm(), alglib.sparse.sparsemm2(), and alglib.sparse.sparsemtm().
linearfunctionssmmtest() [2/2]
static bool alglib.testsparseunit.linearfunctionssmmtest () inline static
References alglib.testsparseunit.createrandom(), alglib.math.machineepsilon, alglib.math.randomreal(), and alglib.sparse.sparsesmm().
basiccopyfunctest() [2/2]
static bool alglib.testsparseunit.basiccopyfunctest (bool silent) inline static
References alglib.sparse.sparseadd(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecopy(), alglib.sparse.sparsecreate(), alglib.sparse.sparsecreatecrs(), alglib.sparse.sparseget(), and alglib.sparse.sparseset().
copyfunctest() [2/2]
static bool alglib.testsparseunit.copyfunctest (bool silent) inline static
References alglib.testsparseunit.createrandom(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.sparse.sparsecopy(), alglib.sparse.sparseget(), alglib.sparse.sparsemtv(), alglib.sparse.sparsemv(), and alglib.sparse.sparsemv2().
createrandom() [2/2]
static void alglib.testsparseunit.createrandom (int m, int n, int pkind, int ckind, int p0, int p1, ref double da[,], sparse.sparsematrix sa) inline static private
References alglib.ap.assert(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.sparse.sparseadd(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparsecreatecrs(), and alglib.sparse.sparseset().
enumeratetest() [2/2]
static bool alglib.testsparseunit.enumeratetest () inline static private
References alglib.math.randominteger(), alglib.math.randomreal(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparseenumerate(), and alglib.sparse.sparseset().
rewriteexistingtest() [2/2]
static bool alglib.testsparseunit.rewriteexistingtest () inline static private
References alglib.math.randominteger(), alglib.math.randomreal(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparseget(), alglib.sparse.sparserewriteexisting(), and alglib.sparse.sparseset().
testgetrow()
static bool alglib.testsparseunit.testgetrow () inline static private
References alglib.math.randominteger(), alglib.math.randomreal(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparseget(), alglib.sparse.sparsegetrow(), and alglib.sparse.sparseset().
Referenced by alglib.testsparseunit.testsparse().
testconvertsm()
static bool alglib.testsparseunit.testconvertsm () inline static private
References alglib.math.randominteger(), alglib.math.randomreal(), alglib.sparse.sparseadd(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparseconverttohash(), alglib.sparse.sparsecopy(), alglib.sparse.sparsecopytocrs(), alglib.sparse.sparsecopytohash(), alglib.sparse.sparsecreatecrs(), alglib.sparse.sparseget(), and alglib.sparse.sparseset().
Referenced by alglib.testsparseunit.testsparse().
testgcmatrixtype()
static bool alglib.testsparseunit.testgcmatrixtype () inline static private
References alglib.sparse.sparseconverttocrs(), alglib.sparse.sparseconverttohash(), alglib.sparse.sparsecopytocrs(), alglib.sparse.sparsecopytohash(), alglib.sparse.sparsecreate(), alglib.sparse.sparsegetmatrixtype(), alglib.sparse.sparseiscrs(), and alglib.sparse.sparseishash().
Referenced by alglib.testsparseunit.testsparse().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs