Doc: IGLib EXTENDED: NUnit.TestUtilities.Comparers.ObjectComparer Class Reference
NUnit.TestUtilities.Comparers.ObjectComparer Class Reference
ObjectComparer is used in testing to ensure that only methods of the IComparer interface are used.
Public Attributes
bool WasCalled = false
Static Public Attributes
static readonly IComparer Default = new ObjectComparer()
Private Member Functions
int IComparer. Compare (object x, object y)
Detailed Description
ObjectComparer is used in testing to ensure that only methods of the IComparer interface are used.
Member Function Documentation
Compare()
int IComparer. NUnit.TestUtilities.Comparers.ObjectComparer.Compare (object x, object y) inline private
References NUnit.TestUtilities.Comparers.ObjectComparer.WasCalled.
Member Data Documentation
WasCalled
bool NUnit.TestUtilities.Comparers.ObjectComparer.WasCalled = false
Referenced by NUnit.TestUtilities.Comparers.ObjectComparer.Compare().
Default
readonly IComparer NUnit.TestUtilities.Comparers.ObjectComparer.Default = new ObjectComparer() static
Referenced by NUnit.Framework.Constraints.CollectionOrderedConstraintTests.IsOrderedBy_Comparer(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer_Descending.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer.SetUp(), and NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer_Descending.SetUp().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/TestUtilities/Comparers/ObjectComparer.cs