Doc: IGLib EXTENDED: IG.Forms.FadingMessage Class Reference
IG.Forms.FadingMessage Class Reference
Manages a fading message window. Windows containing a message are launched in separate threads, closing after a specified time.
Public Member Functions
FadingMessage (bool doLaunch=true)
Argument-less constructor, does not launch the window in a parallel thread.
FadingMessage (string msgtext, bool doLaunch=true)
Shows a fading message in a new thread, with message text equal to mshtext and without a title;.
FadingMessage (string msgtext, int showtime, bool doLaunch=true)
Shows a fading message in a new thread, with message text equal to msgtext and with specified showing time in ms.
FadingMessage (string msgtext, int showtime, double fadeportion, bool doLaunch=true)
Shows a fading message in a new thread, with message text equal to msgtext and with specified showing time in ms and fading time portion.
FadingMessage (string title, string msgtext, bool doLaunch=true)
Shows the consform in a new thread, with a title and with message text equal to msgtext.
FadingMessage (string title, string msgtext, int showtime, bool doLaunch=true)
Shows a fading message in a new thread, with a title and with message text equal to msgtext, with specified showing time in ms.
FadingMessage (string title, string msgtext, int showtime, double fadeportion, bool doLaunch=true)
Shows a fading message in a new thread, with a title and with message text equal to msgtext, with specified showing time in ms and fading time portion.
void SetScreenPosition (int left=-1, int top=-1)
Sets position of the message window on the screen.
virtual FadingMessage Launch (bool inParallelThread)
Launches the fading messsage as specified by parameters.
void LaunchInNewThread ()
Shows a fading message in a new thread.
void CloseForm ()
Closes the fading message control by properly (i.e. thread-safe) calling the Close() and Dispose().
void CopyMessageToClipboard ()
Static Public Member Functions
static void Example ()
Launches a sample fading message, with some instructions of how to use it.
static void ExampleLargeNum (double maxDurationInSeconds=5.0, double launchIntervalInSeconds=0.05, bool launchInCurrentThreadWhenPossible=true)
Launches a larger number of fading messages to check that the system is capable of correct display.
static void ExampleInferior ()
A less relevant example.
Public Attributes
Color ForeGroundColorTitle = DefaultForeGroundColorTitle
Color of the title (if shown in fading message).
Color ForeGroundColorMsg = Color.Black
Color of the message text shown in the fading message.
Color BackGroundColor = DefaultBackGroundColor
Active background color of the fading message.
Color FadeColor = DefaultFadeColor
Final (faded) color of the fading message.
string MsgTitle = null
bool IsReady = false
bool BlockMaxShownCurrent = false
Indicates to block launching new messges when too many are processed.
Static Public Attributes
static readonly Color DefaultForeGroundColorTitle = Color.Blue
static readonly Color DefaultForeGroundColorMessage = Color.Black
static readonly Color DefaultBackGroundColor = Color.LightYellow
static readonly Color DefaultInfoBackgroundColor = DefaultBackGroundColor
static readonly Color DefaultWarningBackgroundColor = Color.Orange
static readonly Color DefaultErrorBackgroundColor = Color.Red
static readonly Color DefaultFadeColor = Color.DarkGray
static int MaxShown = 50
If false then the consform can not be closed or dispoded.
static bool BlockMaxShown = false
Indicates how many messages can be shown simultaneously.
Protected Member Functions
virtual void InitFadingMessageBegin ()
Begins initialization of the fading message (it does not launch it).
void InitFadingMessageBegin (string msgtext)
Begins initialization of the fading message (it does not launch it).
void InitFadingMessageBegin (string msgtext, int showtime)
Begins initialization of the fading message (it does not launch it).
void InitFadingMessageBegin (string msgtext, int showtime, double fadeportion)
Begins initialization of the fading message (it does not launch it).
void InitFadingMessageBegin (string title, string msgtext)
Begins initialization of the fading message (it does not launch it).
void InitFadingMessageBegin (string title, string msgtext, int showtime)
Begins initialization of the fading message (it does not launch it).
void InitFadingMessageBegin (string title, string msgtext, int showtime, double fadeportion)
Begins initialization of the fading message (it does not launch it).
virtual void InitFadingMessageEndBase (bool doLaunch, bool inParallelThread)
Ends initialization of the fading message as specified by parameters.
virtual void InitFadingMessageEnd (bool doLaunch)
Finalizes initialization of the fading message, which may include launching the message.
void InitFadingMessage (bool doLaunch=true)
Begins initialization of the fading message (it does not launch it).
void InitFadingMessage (string msgtext, bool doLaunch=true)
Begins initialization of the fading message (it does not launch it).
void InitFadingMessage (string msgtext, int showtime, bool doLaunch=true)
Begins initialization of the fading message (it does not launch it).
void InitFadingMessage (string msgtext, int showtime, double fadeportion, bool doLaunch=true)
Begins initialization of the fading message (it does not launch it).
void InitFadingMessage (string title, string msgtext, bool doLaunch=true)
Begins initialization of the fading message (it does not launch it).
void InitFadingMessage (string title, string msgtext, int showtime, bool doLaunch=true)
Begins initialization of the fading message (it does not launch it).
void InitFadingMessage (string title, string msgtext, int showtime, double fadeportion, bool doLaunch=true)
Begins initialization of the fading message (it does not launch it).
void IncrementNumLaunched ()
Increments the total number of launched fading messages.
void IncrementNumShown ()
Increments the number of currently active (displayed) fading messages.
void DecrementNumShown ()
Decrements the number of currently active (displayed) fading messages.
void LauncherNewThread ()
Launches the current fading message in a parallel thread.
void LauncherCurrentThread ()
Launches the current fading message in the current thread, which should be a GUI thread (with a message loop running).
virtual void LauncherMethod (bool launchedInNewThread)
This method is used to launch the fading message, either in a parallel thread to the caller thread or on the caller thread. Parameter specified in which way the message is launched.
override void Dispose (bool disposing)
Clean up any resources being used.
Static Protected Member Functions
static int GetNextId ()
Protected Attributes
bool IsClosable = true
Returns true if control has been created and is ready to work with.
Static Protected Attributes
static int _idStatic = -1
Properties
static object LockStatic [get]
Static lock object that can be used by all fadiing message objects.
object Lock [get]
ILockable's lock object.
int Id [get]
ID of the current fading message object.
static int NumLaunched [get]
Gets the total number of launched fading messages.
static int NumShown [get]
Gets the total number of fading messages that aree currently active (displayed).
static int OutputLevel [get, set]
Level of output printed to console (for debugging).
bool IsTopMostWindow [get, set]
Whether or not the launched fading message is a topmost window.
bool LaunchedAtMouseCursor [get, set]
Whether the message should be launched at the position of the mouse cursor.
int ShowTime [get, set]
Total time, in milliseconds, for which the message is displayed.
double FadingTimePortion [get, set]
Portion of display time in which the message background color fades at the end of its display time.
bool WasLaunched [get, protected set]
Specifies whether the current fading message has already been launched.
bool LaunchedInParallelThread [get, set]
Specifies whether the current fading message has been launched in a parallel thread.
DateTime StartTime [get, protected set]
Time when the fading message was launched.
TimeSpan ElapsedTimeSpan [get]
Gets the amount of time during which the message has been displayed until now.
TimeSpan ShowTimeSpan [get, set]
Gets or sets the total time span for which the message is to be displayed.
TimeSpan RemainingTimeSpan [get, protected set]
Gets the remaining time span for which the message will be displayed.
int MinTickinterval [get, set]
Minimal tick interval in milliseconds.
int MaxTicks [get, set]
Maximal number of timer ticks before the message fades out (this refers to the second part of the message).
int NumTicks [get, set]
Number of timer ticks that occurred after the fading message has been launched.
int TotalTicks [get, set]
Total number of timerr ticks in the fading portion of the message display time.
int FirstTickInterval [get, set]
Length of the first timer tick interval in milliseconds. <pra>The first tick marks start of the fading portion of the display time. After the first tick, tick interval is reduced to enable smooth color transition.</pra>
int TickInterval [get, set]
Current tick interval in milliseconds.
double FadingFactor [get, set]
Current fading factor - extent to which the active bacground color has changed to the faded color.
bool IsFormClosing [get]
Gets a flag indicating whether the fading message is currently being closed.
bool IsFormClosedOrClosing [get]
Gets aa flag indicating whether the form has been closed or is currently being closed.
double MinimalRemainingSecondsWithMenu [get, set]
Minimal remaining show time, in seconds, when user launches a context menu.
Private Member Functions
void ManipulationThreadFunc ()
A parallel thread that takes care of launching the thread that manages the form. This thread also takes care that the form is disposed after the prescribed time elapses.
void timer1_Tick (object sender, EventArgs e)
Timer event, handles color change, closing after display time is passed, etc.
void FadeMessage_MouseDown (object sender, MouseEventArgs e)
Enables dragging by mouse.
void FadeMessage_MouseMove (object sender, MouseEventArgs e)
Enables dragging by mouse.
void SetFadeLevel (double fadefactor)
Sets control's background accordig to the fading factor.
void SetCommonEvents (Control f)
This method is used to set the common event handlers for the curren fading message control and its subcontrols.
void FadeMessage_Load (object sender, System.EventArgs e)
void FadeMessage_Disposed (object sender, System.EventArgs e)
void FadeMessage_FormClosing (object sender, FormClosingEventArgs e)
void CancelBtn_Click (object sender, EventArgs e)
void FadeMessage_MouseClick (object sender, MouseEventArgs e)
Handles mouse click events for the current fading message control.
void FadeMessage_KeyPress (object sender, KeyPressEventArgs e)
Handles mouse click events for the current fading message control.
void menuStrip1_ItemClicked (object sender, ToolStripItemClickedEventArgs e)
void menuCopyMessage_Click (object sender, EventArgs e)
Copies message text to clipboard.
void menuClose_Click (object sender, EventArgs e)
void menuMain_Opening (object sender, CancelEventArgs e)
Executed when the context menue is opening.
void menuIdentifyThread_Click (object sender, EventArgs e)
void menuLaunchSameThread_Click (object sender, EventArgs e)
void menuLaunchMessageParallel_Click (object sender, EventArgs e)
void menuExample_Click (object sender, EventArgs e)
Launches a demonstrative example message.
void menuExampleMassive_Click (object sender, EventArgs e)
Runs a massive launch demo.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
readonly object _lock = new object()
volatile int _id = GetNextId()
bool _isTopMostWindow = true
bool _launchesAtMouseCursor = false
string MsgText = null
int _showTime = defaultShowtime
double _fadingTimePortion = defaultFadingTimePortion
Thread _formthread = null
Thread _manipulationthread = null
bool _wasLaunched = false
bool _launchedInParallelThread = false
DateTime _startTime
int _minTickInterval = 40
int _maxTicks = 50
int _numTicks = 0
int _totalTicks = 20
int _firstTick = 1000
int _tickInterval = 100
double _fadingFactor = 0
volatile bool _isFormClosing = false
volatile bool _isFormClosed = false
int m_PrevX
int m_PrevY
double _minRemainingSecMenu = 8.0
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Timer timer1
System.Windows.Forms.Button btnCancel
System.Windows.Forms.Label lblStatus
System.Windows.Forms.Panel BodyPnl
System.Windows.Forms.Label lblMEssage
System.Windows.Forms.Label lblTitle
System.Windows.Forms.Panel PnlStatus
System.Windows.Forms.Label labelBottom
System.Windows.Forms.ContextMenuStrip menuMain
System.Windows.Forms.ToolStripMenuItem menuCopyMessage
System.Windows.Forms.ToolStripMenuItem menuClose
System.Windows.Forms.ToolStripMenuItem menuLaunchThreadParallel
System.Windows.Forms.ToolStripMenuItem menuIdentifyThread
System.Windows.Forms.ToolStripMenuItem menuLaunchSameThread
System.Windows.Forms.ToolStripMenuItem menuExample
System.Windows.Forms.ToolStripMenuItem menuExampleMassive
Static Private Attributes
static object _lockStatic = null
static volatile int _numLaunched = 0
static volatile int _numShown = 0
static int _outputLevel = 0
static int defaultShowtime = 3000
Instructs just for the current index to block launching the messge when too many are processed.
static double defaultFadingTimePortion = 0.3
Detailed Description
Manages a fading message window. Windows containing a message are launched in separate threads, closing after a specified time.
This class' constructors call virtual methods. This should in general be avoides and should be considered exceptional case.
Because of this, in derived classes, constructors should just directly call constructors of base class with the same arguments!
$A Igor jul08;
Constructor & Destructor Documentation
FadingMessage() [1/7]
IG.Forms.FadingMessage.FadingMessage (bool doLaunch = true) inline
Argument-less constructor, does not launch the window in a parallel thread.
References IG.Forms.FadingMessage.InitFadingMessage().
Referenced by IG.Forms.FadingMessage.CopyMessageToClipboard(), IG.Forms.FadingMessage.Example(), IG.Forms.FadingMessage.ExampleInferior(), IG.Forms.FadingMessage.ExampleLargeNum(), IG.Forms.FadingMessage.menuIdentifyThread_Click(), IG.Forms.FadingMessage.menuLaunchMessageParallel_Click(), and IG.Forms.FadingMessage.menuLaunchSameThread_Click().
FadingMessage() [2/7]
IG.Forms.FadingMessage.FadingMessage (string msgtext, bool doLaunch = true) inline
Shows a fading message in a new thread, with message text equal to mshtext and without a title;.
References IG.Forms.FadingMessage.InitFadingMessage().
FadingMessage() [3/7]
IG.Forms.FadingMessage.FadingMessage (string msgtext, int showtime, bool doLaunch = true) inline
Shows a fading message in a new thread, with message text equal to msgtext and with specified showing time in ms.
References IG.Forms.FadingMessage.InitFadingMessage().
FadingMessage() [4/7]
IG.Forms.FadingMessage.FadingMessage (string msgtext, int showtime, double fadeportion, bool doLaunch = true) inline
Shows a fading message in a new thread, with message text equal to msgtext and with specified showing time in ms and fading time portion.
References IG.Forms.FadingMessage.InitFadingMessage().
FadingMessage() [5/7]
IG.Forms.FadingMessage.FadingMessage (string title, string msgtext, bool doLaunch = true) inline
Shows the consform in a new thread, with a title and with message text equal to msgtext.
References IG.Forms.FadingMessage.InitFadingMessage().
FadingMessage() [6/7]
IG.Forms.FadingMessage.FadingMessage (string title, string msgtext, int showtime, bool doLaunch = true) inline
Shows a fading message in a new thread, with a title and with message text equal to msgtext, with specified showing time in ms.
References IG.Forms.FadingMessage.InitFadingMessage().
FadingMessage() [7/7]
IG.Forms.FadingMessage.FadingMessage (string title, string msgtext, int showtime, double fadeportion, bool doLaunch = true) inline
Shows a fading message in a new thread, with a title and with message text equal to msgtext, with specified showing time in ms and fading time portion.
References IG.Forms.FadingMessage.InitFadingMessage().
Member Function Documentation
InitFadingMessageBegin() [1/7]
virtual void IG.Forms.FadingMessage.InitFadingMessageBegin () inline protected virtual
Begins initialization of the fading message (it does not launch it).
If necessary, this method can be
References IG.Forms.FadingMessage.InitializeComponent(), and IG.Forms.FadingMessage.IsTopMostWindow.
Referenced by IG.Forms.FadingMessage.InitFadingMessage(), and IG.Forms.FadingMessage.InitFadingMessageBegin().
InitFadingMessageBegin() [2/7]
void IG.Forms.FadingMessage.InitFadingMessageBegin (string msgtext) inline protected
Begins initialization of the fading message (it does not launch it).
Parameters
msgtext Fading message's text (the message).
References IG.Forms.FadingMessage.InitFadingMessageBegin(), and IG.Forms.FadingMessage.MsgText.
InitFadingMessageBegin() [3/7]
void IG.Forms.FadingMessage.InitFadingMessageBegin (string msgtext, int showtime) inline protected
Begins initialization of the fading message (it does not launch it).
Parameters
msgtext Fading message's text (the message).
showtime Time (in miilliiseconds) in which the message is shown.
References IG.Forms.FadingMessage.InitFadingMessageBegin(), IG.Forms.FadingMessage.MsgText, and IG.Forms.FadingMessage.ShowTime.
InitFadingMessageBegin() [4/7]
void IG.Forms.FadingMessage.InitFadingMessageBegin (string msgtext, int showtime, double fadeportion) inline protected
Begins initialization of the fading message (it does not launch it).
Parameters
msgtext Fading message's text (the message).
showtime Time (in miilliiseconds) in which the message is shown.
fadeportion Portion of the show time in shich teh message background fades.
References IG.Forms.FadingMessage.FadingTimePortion, IG.Forms.FadingMessage.InitFadingMessageBegin(), IG.Forms.FadingMessage.MsgText, and IG.Forms.FadingMessage.ShowTime.
InitFadingMessageBegin() [5/7]
void IG.Forms.FadingMessage.InitFadingMessageBegin (string title, string msgtext) inline protected
Begins initialization of the fading message (it does not launch it).
Parameters
title Fading message's title.
msgtext Fading message's text (the message).
References IG.Forms.FadingMessage.InitFadingMessageBegin(), IG.Forms.FadingMessage.MsgText, and IG.Forms.FadingMessage.MsgTitle.
InitFadingMessageBegin() [6/7]
void IG.Forms.FadingMessage.InitFadingMessageBegin (string title, string msgtext, int showtime) inline protected
Begins initialization of the fading message (it does not launch it).
Parameters
title Fading message's title.
msgtext Fading message's text (the message).
showtime Time (in miilliiseconds) in which the message is shown.
References IG.Forms.FadingMessage.InitFadingMessageBegin(), IG.Forms.FadingMessage.MsgText, IG.Forms.FadingMessage.MsgTitle, and IG.Forms.FadingMessage.ShowTime.
InitFadingMessageBegin() [7/7]
void IG.Forms.FadingMessage.InitFadingMessageBegin (string title, string msgtext, int showtime, double fadeportion) inline protected
Begins initialization of the fading message (it does not launch it).
Parameters
title Fading message's title.
msgtext Fading message's text (the message).
showtime Time (in miilliiseconds) in which the message is shown.
fadeportion Portion of the show time in shich teh message background fades.
References IG.Forms.FadingMessage.FadingTimePortion, IG.Forms.FadingMessage.InitFadingMessageBegin(), IG.Forms.FadingMessage.MsgText, IG.Forms.FadingMessage.MsgTitle, and IG.Forms.FadingMessage.ShowTime.
InitFadingMessageEndBase()
virtual void IG.Forms.FadingMessage.InitFadingMessageEndBase (bool doLaunch, bool inParallelThread) inline protected virtual
Ends initialization of the fading message as specified by parameters.
This method can be overridden in derived classes.
Parameters
doLaunch If true then fading message is automatically launched when initialization is done.
inParallelThread If true then mafing message is launched in a paralleel thread.
References IG.Forms.FadingMessage.Launch().
Referenced by IG.Forms.FadingMessage.InitFadingMessageEnd().
InitFadingMessageEnd()
virtual void IG.Forms.FadingMessage.InitFadingMessageEnd (bool doLaunch) inline protected virtual
Finalizes initialization of the fading message, which may include launching the message.
Parameters
doLaunch Whether the message should also be launched.
References IG.Forms.FadingMessage.InitFadingMessageEndBase().
Referenced by IG.Forms.FadingMessage.InitFadingMessage().
InitFadingMessage() [1/7]
void IG.Forms.FadingMessage.InitFadingMessage (bool doLaunch = true) inline protected
Begins initialization of the fading message (it does not launch it).
If necessary, this method can be overridden in derived classes.
Parameters
doLaunch Whether the message should also be launched.
References IG.Forms.FadingMessage.InitFadingMessageBegin(), and IG.Forms.FadingMessage.InitFadingMessageEnd().
Referenced by IG.Forms.FadingMessage.FadingMessage().
InitFadingMessage() [2/7]
void IG.Forms.FadingMessage.InitFadingMessage (string msgtext, bool doLaunch = true) inline protected
Begins initialization of the fading message (it does not launch it).
Parameters
msgtext Fading message's text (the message).
doLaunch Whether the message should also be launched.
References IG.Forms.FadingMessage.InitFadingMessageBegin(), and IG.Forms.FadingMessage.InitFadingMessageEnd().
InitFadingMessage() [3/7]
void IG.Forms.FadingMessage.InitFadingMessage (string msgtext, int showtime, bool doLaunch = true) inline protected
Begins initialization of the fading message (it does not launch it).
Parameters
msgtext Fading message's text (the message).
showtime Time (in miilliiseconds) in which the message is shown.
doLaunch Whether the message should also be launched.
References IG.Forms.FadingMessage.InitFadingMessageBegin(), and IG.Forms.FadingMessage.InitFadingMessageEnd().
InitFadingMessage() [4/7]
void IG.Forms.FadingMessage.InitFadingMessage (string msgtext, int showtime, double fadeportion, bool doLaunch = true) inline protected
Begins initialization of the fading message (it does not launch it).
Parameters
msgtext Fading message's text (the message).
showtime Time (in miilliiseconds) in which the message is shown.
fadeportion Portion of the show time in shich teh message background fades.
doLaunch Whether the message should also be launched.
References IG.Forms.FadingMessage.InitFadingMessageBegin(), and IG.Forms.FadingMessage.InitFadingMessageEnd().
InitFadingMessage() [5/7]
void IG.Forms.FadingMessage.InitFadingMessage (string title, string msgtext, bool doLaunch = true) inline protected
Begins initialization of the fading message (it does not launch it).
Parameters
title Fading message's title.
msgtext Fading message's text (the message).
doLaunch Whether the message should also be launched.
References IG.Forms.FadingMessage.InitFadingMessageBegin(), and IG.Forms.FadingMessage.InitFadingMessageEnd().
InitFadingMessage() [6/7]
void IG.Forms.FadingMessage.InitFadingMessage (string title, string msgtext, int showtime, bool doLaunch = true) inline protected
Begins initialization of the fading message (it does not launch it).
Parameters
title Fading message's title.
msgtext Fading message's text (the message).
showtime Time (in miilliiseconds) in which the message is shown.
doLaunch Whether the message should also be launched.
References IG.Forms.FadingMessage.InitFadingMessageBegin(), and IG.Forms.FadingMessage.InitFadingMessageEnd().
InitFadingMessage() [7/7]
void IG.Forms.FadingMessage.InitFadingMessage (string title, string msgtext, int showtime, double fadeportion, bool doLaunch = true) inline protected
Begins initialization of the fading message (it does not launch it).
Parameters
title Fading message's title.
msgtext Fading message's text (the message).
showtime Time (in miilliiseconds) in which the message is shown.
fadeportion Portion of the show time in shich teh message background fades.
doLaunch Whether the message should also be launched.
References IG.Forms.FadingMessage.InitFadingMessageBegin(), and IG.Forms.FadingMessage.InitFadingMessageEnd().
GetNextId()
static int IG.Forms.FadingMessage.GetNextId () inline static protected
References IG.Forms.FadingMessage._idStatic, and IG.Forms.FadingMessage.LockStatic.
IncrementNumLaunched()
void IG.Forms.FadingMessage.IncrementNumLaunched () inline protected
Increments the total number of launched fading messages.
References IG.Forms.FadingMessage._numLaunched, and IG.Forms.FadingMessage.LockStatic.
Referenced by IG.Forms.FadingMessage.LauncherMethod().
IncrementNumShown()
void IG.Forms.FadingMessage.IncrementNumShown () inline protected
Increments the number of currently active (displayed) fading messages.
References IG.Forms.FadingMessage._numShown, and IG.Forms.FadingMessage.LockStatic.
Referenced by IG.Forms.FadingMessage.LauncherMethod().
DecrementNumShown()
void IG.Forms.FadingMessage.DecrementNumShown () inline protected
Decrements the number of currently active (displayed) fading messages.
References IG.Forms.FadingMessage._numShown, and IG.Forms.FadingMessage.LockStatic.
Referenced by IG.Forms.FadingMessage.CloseForm().
SetScreenPosition()
void IG.Forms.FadingMessage.SetScreenPosition (int left = -1, int top = -1) inline
Sets position of the message window on the screen.
If position arguments are less than 0 then mouse cursor position is taken.
Parameters
left Distance of window from the left edge of the screen.
If less than 0, it is set at mouse cursor horizontal position.
Parameters
top Distance of window from the top edge of the screen.
If less than 0, it is set at mouse cursor vertical position.
References IG.Lib.Left, IG.Forms.FadingMessage.OutputLevel, IG.Lib.Top, and AForge.Point.X.
Referenced by IG.Forms.FadingMessage.LauncherMethod().
ManipulationThreadFunc()
void IG.Forms.FadingMessage.ManipulationThreadFunc () inline private
A parallel thread that takes care of launching the thread that manages the form. This thread also takes care that the form is disposed after the prescribed time elapses.
References IG.Forms.FadingMessage._formthread, IG.Forms.FadingMessage.CloseForm(), IG.Forms.FadingMessage.LauncherNewThread(), IG.Forms.FadingMessage.MaxShown, IG.Forms.FadingMessage.NumShown, IG.Forms.FadingMessage.OutputLevel, and IG.Forms.FadingMessage.RemainingTimeSpan.
Referenced by IG.Forms.FadingMessage.LaunchInNewThread().
Launch()
virtual FadingMessage IG.Forms.FadingMessage.Launch (bool inParallelThread) inline virtual
Launches the fading messsage as specified by parameters.
Parameters
inParallelThread If true then fading message is launched in a parallel thread. Otherwise, it is launched in the current thread.
Returns
The current fading message form that has been launched.
References IG.Forms.FadingMessage.LauncherCurrentThread(), IG.Forms.FadingMessage.LaunchInNewThread(), and IG.Forms.FadingMessage.WasLaunched.
Referenced by IG.Forms.VectorFunctionPlotter1d.btnCheck_Click(), IG.Forms.VectorFunctionPlotter2d.btnCheck_Click(), IG.Neural.Forms.NeuralInputControl.btnIdentifyThread_Click(), IG.Forms.ScalarFunctionEvaluatorControl.btnIdentifyThread_Click(), IG.Forms.FadingMessage.CopyMessageToClipboard(), IG.Forms.ReporterForms.DefaultReport_FadeMessage(), IG.Forms.ReporterForms.DefaultReserveReportErrorForms(), IG.Forms.FadingMessage.Example(), IG.Forms.FadingMessage.ExampleLargeNum(), IG.Forms.FadingMessage.InitFadingMessageEndBase(), IG.Forms.FadingMessage.menuIdentifyThread_Click(), IG.Forms.FadingMessage.menuLaunchSameThread_Click(), IG.Forms.OutputValueSelector.menuSummary_Click(), IG.Forms.InputOutputDataDefinitionControl.menuSummary_Click(), IG.Forms.InputParameterSelectorMinMax.menuSummary_Click(), IG.Forms.DialogControl.menuSummary_Click(), IG.Forms.XMLTreeViewFormOld_Keep_Some_time.ReportError0(), and IG.Forms.XmlTreeViewControl.ReportError0().
LaunchInNewThread()
void IG.Forms.FadingMessage.LaunchInNewThread () inline
Shows a fading message in a new thread.
It first launches a new thread that launches the thread managing the form. In this way, the calling thread returns quickly and robust manipulation of the consform can be done.
References IG.Forms.FadingMessage._manipulationthread, IG.Forms.FadingMessage.ManipulationThreadFunc(), IG.Forms.FadingMessage.MaxShown, IG.Forms.FadingMessage.NumShown, and IG.Forms.FadingMessage.OutputLevel.
Referenced by IG.Forms.FadingMessage.Launch(), and IG.Forms.ConsoleForm.ReserveReportError0().
LauncherNewThread()
void IG.Forms.FadingMessage.LauncherNewThread () inline protected
Launches the current fading message in a parallel thread.
References IG.Forms.FadingMessage.LauncherMethod().
Referenced by IG.Forms.FadingMessage.ManipulationThreadFunc().
LauncherCurrentThread()
void IG.Forms.FadingMessage.LauncherCurrentThread () inline protected
Launches the current fading message in the current thread, which should be a GUI thread (with a message loop running).
References IG.Forms.FadingMessage.LauncherMethod().
Referenced by IG.Forms.FadingMessage.Launch().
LauncherMethod()
virtual void IG.Forms.FadingMessage.LauncherMethod (bool launchedInNewThread) inline protected virtual
This method is used to launch the fading message, either in a parallel thread to the caller thread or on the caller thread. Parameter specified in which way the message is launched.
Parameters
launchedInNewThread If true then the message is launched in a new parallel thread, which means that the message loop must be run by calling ShowDialog() method.
Launches the message.
References IG.Forms.FadingMessage.FadingTimePortion, IG.Forms.FadingMessage.FirstTickInterval, IG.Forms.FadingMessage.IncrementNumLaunched(), IG.Forms.FadingMessage.IncrementNumShown(), IG.Forms.FadingMessage.LaunchedAtMouseCursor, IG.Forms.FadingMessage.LaunchedInParallelThread, IG.Forms.FadingMessage.MaxTicks, IG.Forms.FadingMessage.MinTickinterval, IG.Forms.FadingMessage.MsgText, IG.Forms.FadingMessage.OutputLevel, IG.Forms.FadingMessage.RemainingTimeSpan, IG.Forms.FadingMessage.SetScreenPosition(), IG.Forms.FadingMessage.ShowTime, IG.Forms.FadingMessage.StartTime, IG.Forms.FadingMessage.TickInterval, IG.Forms.FadingMessage.timer1, IG.Forms.FadingMessage.TotalTicks, and IG.Forms.FadingMessage.WasLaunched.
Referenced by IG.Forms.FadingMessage.LauncherCurrentThread(), and IG.Forms.FadingMessage.LauncherNewThread().
timer1_Tick()
void IG.Forms.FadingMessage.timer1_Tick (object sender, EventArgs e) inline private
Timer event, handles color change, closing after display time is passed, etc.
Parameters
sender
e
References IG.Forms.FadingMessage.CloseForm(), IG.Forms.FadingMessage.FadingFactor, IG.Forms.FadingMessage.IsFormClosedOrClosing, IG.Forms.FadingMessage.NumTicks, IG.Forms.FadingMessage.OutputLevel, IG.Forms.FadingMessage.RemainingTimeSpan, IG.Forms.FadingMessage.SetFadeLevel(), IG.Forms.FadingMessage.TickInterval, IG.Forms.FadingMessage.timer1, and IG.Forms.FadingMessage.TotalTicks.
CloseForm()
void IG.Forms.FadingMessage.CloseForm () inline
Closes the fading message control by properly (i.e. thread-safe) calling the Close() and Dispose().
References IG.Forms.FadingMessage._isFormClosed, IG.Forms.FadingMessage._isFormClosing, IG.Forms.FadingMessage.DecrementNumShown(), IG.Forms.FadingMessage.Dispose(), IG.Forms.FadingMessage.Lock, IG.Forms.FadingMessage.NumLaunched, IG.Forms.FadingMessage.NumShown, IG.Forms.FadingMessage.OutputLevel, IG.Forms.FadingMessage.RemainingTimeSpan, and IG.Forms.FadingMessage.timer1.
Referenced by IG.Forms.FadingMessage.CancelBtn_Click(), IG.Forms.FadingMessage.FadeMessage_MouseClick(), IG.Forms.FadingMessage.ManipulationThreadFunc(), IG.Forms.FadingMessage.menuClose_Click(), and IG.Forms.FadingMessage.timer1_Tick().
FadeMessage_MouseDown()
void IG.Forms.FadingMessage.FadeMessage_MouseDown (object sender, MouseEventArgs e) inline private
Enables dragging by mouse.
References IG.Forms.FadingMessage.m_PrevX, and IG.Forms.FadingMessage.m_PrevY.
Referenced by IG.Forms.FadingMessage.SetCommonEvents().
FadeMessage_MouseMove()
void IG.Forms.FadingMessage.FadeMessage_MouseMove (object sender, MouseEventArgs e) inline private
Enables dragging by mouse.
References IG.Lib.Left, IG.Forms.FadingMessage.m_PrevX, IG.Forms.FadingMessage.m_PrevY, and IG.Lib.Top.
Referenced by IG.Forms.FadingMessage.SetCommonEvents().
SetFadeLevel()
void IG.Forms.FadingMessage.SetFadeLevel (double fadefactor) inline private
Sets control's background accordig to the fading factor.
Parameters
fadefactor
References IG.Forms.FadingMessage.BackGroundColor, IG.Forms.FadingMessage.FadeColor, and IG.Forms.UtilForms.SetBackColorRec().
Referenced by IG.Forms.FadingMessage.timer1_Tick().
SetCommonEvents()
void IG.Forms.FadingMessage.SetCommonEvents (Control f) inline private
This method is used to set the common event handlers for the curren fading message control and its subcontrols.
Parameters
f Control on which common event handlers are set.
References IG.Forms.FadingMessage.FadeMessage_KeyPress(), IG.Forms.FadingMessage.FadeMessage_MouseClick(), IG.Forms.FadingMessage.FadeMessage_MouseDown(), and IG.Forms.FadingMessage.FadeMessage_MouseMove().
Referenced by IG.Forms.FadingMessage.FadeMessage_Load().
FadeMessage_Load()
void IG.Forms.FadingMessage.FadeMessage_Load (object sender, System.EventArgs e) inline private
References IG.Forms.FadingMessage.BackGroundColor, IG.Forms.FadingMessage.BodyPnl, IG.Forms.FadingMessage.btnCancel, IG.Forms.ControlDelegate(), IG.Forms.FadingMessage.FadingTimePortion, IG.Forms.FadingMessage.FirstTickInterval, IG.Forms.FadingMessage.ForeGroundColorMsg, IG.Forms.FadingMessage.ForeGroundColorTitle, IG.Forms.FadingMessage.labelBottom, IG.Forms.FadingMessage.lblMEssage, IG.Forms.FadingMessage.lblStatus, IG.Forms.FadingMessage.lblTitle, IG.Forms.FadingMessage.MaxTicks, IG.Forms.FadingMessage.MinTickinterval, IG.Forms.FadingMessage.MsgText, IG.Forms.FadingMessage.MsgTitle, IG.Forms.FadingMessage.PnlStatus, IG.Forms.UtilForms.RecursiveControlDelegate(), IG.Forms.UtilForms.SetBackColorRec(), IG.Forms.FadingMessage.SetCommonEvents(), IG.Forms.FadingMessage.ShowTime, IG.Forms.FadingMessage.TickInterval, IG.Forms.FadingMessage.timer1, and IG.Forms.FadingMessage.TotalTicks.
FadeMessage_Disposed()
void IG.Forms.FadingMessage.FadeMessage_Disposed (object sender, System.EventArgs e) inline private
FadeMessage_FormClosing()
void IG.Forms.FadingMessage.FadeMessage_FormClosing (object sender, FormClosingEventArgs e) inline private
References IG.Forms.FadingMessage.OutputLevel, and IG.Forms.FadingMessage.RemainingTimeSpan.
CancelBtn_Click()
void IG.Forms.FadingMessage.CancelBtn_Click (object sender, EventArgs e) inline private
References IG.Forms.FadingMessage.CloseForm().
FadeMessage_MouseClick()
void IG.Forms.FadingMessage.FadeMessage_MouseClick (object sender, MouseEventArgs e) inline private
Handles mouse click events for the current fading message control.
References IG.Forms.FadingMessage.CloseForm(), and IG.Forms.FadingMessage.menuMain.
Referenced by IG.Forms.FadingMessage.SetCommonEvents().
FadeMessage_KeyPress()
void IG.Forms.FadingMessage.FadeMessage_KeyPress (object sender, KeyPressEventArgs e) inline private
Handles mouse click events for the current fading message control.
References IG.Forms.FadingMessage.CopyMessageToClipboard().
Referenced by IG.Forms.FadingMessage.SetCommonEvents().
menuStrip1_ItemClicked()
void IG.Forms.FadingMessage.menuStrip1_ItemClicked (object sender, ToolStripItemClickedEventArgs e) inline private
menuCopyMessage_Click()
void IG.Forms.FadingMessage.menuCopyMessage_Click (object sender, EventArgs e) inline private
Copies message text to clipboard.
References IG.Forms.FadingMessage.CopyMessageToClipboard().
CopyMessageToClipboard()
void IG.Forms.FadingMessage.CopyMessageToClipboard () inline
References IG.Forms.FadingMessage.FadingMessage(), IG.Forms.FadingMessage.Launch(), and IG.Forms.FadingMessage.lblMEssage.
Referenced by IG.Forms.FadingMessage.FadeMessage_KeyPress(), and IG.Forms.FadingMessage.menuCopyMessage_Click().
menuClose_Click()
void IG.Forms.FadingMessage.menuClose_Click (object sender, EventArgs e) inline private
References IG.Forms.FadingMessage.CloseForm().
menuMain_Opening()
void IG.Forms.FadingMessage.menuMain_Opening (object sender, CancelEventArgs e) inline private
Executed when the context menue is opening.
If necessary, display time of the fading message is extended, such that the user has time to select items from the menu.
References IG.Forms.FadingMessage.MinimalRemainingSecondsWithMenu, IG.Forms.FadingMessage.OutputLevel, and IG.Forms.FadingMessage.RemainingTimeSpan.
menuIdentifyThread_Click()
void IG.Forms.FadingMessage.menuIdentifyThread_Click (object sender, EventArgs e) inline private
References IG.Forms.FadingMessage.FadingMessage(), IG.Forms.UtilForms.GetCurrentThreadInfo(), IG.Forms.FadingMessage.Id, IG.Forms.FadingMessage.Launch(), IG.Forms.FadingMessage.LaunchedInParallelThread, IG.Forms.FadingMessage.RemainingTimeSpan, and IG.Forms.FadingMessage.WasLaunched.
menuLaunchSameThread_Click()
void IG.Forms.FadingMessage.menuLaunchSameThread_Click (object sender, EventArgs e) inline private
References IG.Forms.FadingMessage.FadingMessage(), and IG.Forms.FadingMessage.Launch().
menuLaunchMessageParallel_Click()
void IG.Forms.FadingMessage.menuLaunchMessageParallel_Click (object sender, EventArgs e) inline private
References IG.Forms.FadingMessage.FadingMessage().
menuExample_Click()
void IG.Forms.FadingMessage.menuExample_Click (object sender, EventArgs e) inline private
Launches a demonstrative example message.
References IG.Forms.FadingMessage.Example().
menuExampleMassive_Click()
void IG.Forms.FadingMessage.menuExampleMassive_Click (object sender, EventArgs e) inline private
Runs a massive launch demo.
References IG.Forms.FadingMessage.ExampleLargeNum().
Example()
static void IG.Forms.FadingMessage.Example () inline static
Launches a sample fading message, with some instructions of how to use it.
References IG.Forms.FadingMessage.FadingMessage(), and IG.Forms.FadingMessage.Launch().
Referenced by IG.Script.AppExtBase.FormDemoFunctionFadingMessage(), igform_console_test.test_igform_console_program.Main(), and IG.Forms.FadingMessage.menuExample_Click().
ExampleLargeNum()
static void IG.Forms.FadingMessage.ExampleLargeNum (double maxDurationInSeconds = 5.0, double launchIntervalInSeconds = 0.05, bool launchInCurrentThreadWhenPossible = true) inline static
Launches a larger number of fading messages to check that the system is capable of correct display.
References IG.Forms.FadingMessage.BackGroundColor, IG.Forms.FadingMessage.FadingMessage(), IG.Forms.UtilForms.IsMainGuiThread(), IG.Forms.FadingMessage.IsTopMostWindow, IG.Forms.FadingMessage.Launch(), and IG.Forms.FadingMessage.LaunchedAtMouseCursor.
Referenced by IG.Forms.FadingMessage.menuExampleMassive_Click().
ExampleInferior()
static void IG.Forms.FadingMessage.ExampleInferior () inline static
A less relevant example.
References IG.Forms.FadingMessage.FadingMessage(), IG.Forms.FadingMessage.MsgText, and IG.Forms.FadingMessage.MsgTitle.
Referenced by IG.Script.AppExtBase.FormDemoFunctionFadingMessage(), and igform_console_test.test_igform_console_program.Main().
Dispose()
override void IG.Forms.FadingMessage.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.FadingMessage.components.
Referenced by IG.Forms.FadingMessage.CloseForm().
InitializeComponent()
void IG.Forms.FadingMessage.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by IG.Forms.FadingMessage.InitFadingMessageBegin().
Member Data Documentation
_lockStatic
object IG.Forms.FadingMessage._lockStatic = null static private
_lock
readonly object IG.Forms.FadingMessage._lock = new object() private
_idStatic
int IG.Forms.FadingMessage._idStatic = -1 static protected
Referenced by IG.Forms.FadingMessage.GetNextId().
_id
volatile int IG.Forms.FadingMessage._id = GetNextId() private
_numLaunched
volatile int IG.Forms.FadingMessage._numLaunched = 0 static private
Referenced by IG.Forms.FadingMessage.IncrementNumLaunched().
_numShown
volatile int IG.Forms.FadingMessage._numShown = 0 static private
Referenced by IG.Forms.FadingMessage.DecrementNumShown(), and IG.Forms.FadingMessage.IncrementNumShown().
_outputLevel
int IG.Forms.FadingMessage._outputLevel = 0 static private
_isTopMostWindow
bool IG.Forms.FadingMessage._isTopMostWindow = true private
_launchesAtMouseCursor
bool IG.Forms.FadingMessage._launchesAtMouseCursor = false private
DefaultForeGroundColorTitle
readonly Color IG.Forms.FadingMessage.DefaultForeGroundColorTitle = Color.Blue static
DefaultForeGroundColorMessage
readonly Color IG.Forms.FadingMessage.DefaultForeGroundColorMessage = Color.Black static
DefaultBackGroundColor
readonly Color IG.Forms.FadingMessage.DefaultBackGroundColor = Color.LightYellow static
Referenced by IG.Forms.HashControl.SetGeneralProperties().
DefaultInfoBackgroundColor
readonly Color IG.Forms.FadingMessage.DefaultInfoBackgroundColor = DefaultBackGroundColor static
DefaultWarningBackgroundColor
readonly Color IG.Forms.FadingMessage.DefaultWarningBackgroundColor = Color.Orange static
DefaultErrorBackgroundColor
readonly Color IG.Forms.FadingMessage.DefaultErrorBackgroundColor = Color.Red static
DefaultFadeColor
readonly Color IG.Forms.FadingMessage.DefaultFadeColor = Color.DarkGray static
ForeGroundColorTitle
Color IG.Forms.FadingMessage.ForeGroundColorTitle = DefaultForeGroundColorTitle
Color of the title (if shown in fading message).
Referenced by IG.Forms.ReporterForms.DefaultReport_FadeMessage(), IG.Forms.ReporterForms.DefaultReserveReportErrorForms(), and IG.Forms.FadingMessage.FadeMessage_Load().
ForeGroundColorMsg
Color IG.Forms.FadingMessage.ForeGroundColorMsg = Color.Black
Color of the message text shown in the fading message.
Referenced by IG.Forms.ReporterForms.DefaultReport_FadeMessage(), IG.Forms.ReporterForms.DefaultReserveReportErrorForms(), and IG.Forms.FadingMessage.FadeMessage_Load().
BackGroundColor
Color IG.Forms.FadingMessage.BackGroundColor = DefaultBackGroundColor
Active background color of the fading message.
Referenced by IG.Forms.ReporterForms.DefaultReport_FadeMessage(), IG.Forms.ReporterForms.DefaultReserveReportErrorForms(), IG.Forms.FadingMessage.ExampleLargeNum(), IG.Forms.FadingMessage.FadeMessage_Load(), IG.Forms.HashControl.FadingMessageError(), IG.Forms.HashControl.FadingMessageInfo(), IG.Forms.HashControl.FadingMessageWarning(), IG.Forms.XMLTreeViewFormOld_Keep_Some_time.ReportError0(), IG.Forms.XmlTreeViewControl.ReportError0(), IG.Forms.ConsoleForm.ReserveReportError0(), IG.Forms.FadingMessage.SetFadeLevel(), and IG.Forms.HashControl.SetGeneralProperties().
FadeColor
Color IG.Forms.FadingMessage.FadeColor = DefaultFadeColor
Final (faded) color of the fading message.
Referenced by IG.Forms.ReporterForms.DefaultReport_FadeMessage(), IG.Forms.ReporterForms.DefaultReserveReportErrorForms(), and IG.Forms.FadingMessage.SetFadeLevel().
MsgTitle
string IG.Forms.FadingMessage.MsgTitle = null
Referenced by IG.Forms.ReporterForms.DefaultReport_FadeMessage(), IG.Forms.ReporterForms.DefaultReserveReportErrorForms(), IG.Forms.FadingMessageOld.Example2(), IG.Forms.FadingMessage.ExampleInferior(), IG.Forms.FadingMessage.FadeMessage_Load(), IG.Forms.FadingMessage.InitFadingMessageBegin(), IG.Forms.XMLTreeViewFormOld_Keep_Some_time.ReportError0(), IG.Forms.XmlTreeViewControl.ReportError0(), and IG.Forms.ConsoleForm.ReserveReportError0().
MsgText
string IG.Forms.FadingMessage.MsgText = null private
Referenced by IG.Forms.ReporterForms.DefaultReport_FadeMessage(), IG.Forms.ReporterForms.DefaultReserveReportErrorForms(), IG.Forms.FadingMessageOld.Example2(), IG.Forms.FadingMessage.ExampleInferior(), IG.Forms.FadingMessage.FadeMessage_Load(), IG.Forms.FadingMessage.InitFadingMessageBegin(), IG.Forms.FadingMessage.LauncherMethod(), IG.Forms.XMLTreeViewFormOld_Keep_Some_time.ReportError0(), IG.Forms.XmlTreeViewControl.ReportError0(), and IG.Forms.ConsoleForm.ReserveReportError0().
IsReady
bool IG.Forms.FadingMessage.IsReady = false
IsClosable
bool IG.Forms.FadingMessage.IsClosable = true protected
Returns true if control has been created and is ready to work with.
MaxShown
int IG.Forms.FadingMessage.MaxShown = 50 static
If false then the consform can not be closed or dispoded.
Referenced by IG.Forms.FadingMessage.LaunchInNewThread(), and IG.Forms.FadingMessage.ManipulationThreadFunc().
BlockMaxShown
bool IG.Forms.FadingMessage.BlockMaxShown = false static
Indicates how many messages can be shown simultaneously.
BlockMaxShownCurrent
bool IG.Forms.FadingMessage.BlockMaxShownCurrent = false
Indicates to block launching new messges when too many are processed.
defaultShowtime
int IG.Forms.FadingMessage.defaultShowtime = 3000 static private
Instructs just for the current index to block launching the messge when too many are processed.
defaultFadingTimePortion
double IG.Forms.FadingMessage.defaultFadingTimePortion = 0.3 static private
_showTime
int IG.Forms.FadingMessage._showTime = defaultShowtime private
_fadingTimePortion
double IG.Forms.FadingMessage._fadingTimePortion = defaultFadingTimePortion private
_formthread
Thread IG.Forms.FadingMessage._formthread = null private
Referenced by IG.Forms.FadingMessage.ManipulationThreadFunc().
_manipulationthread
Thread IG.Forms.FadingMessage._manipulationthread = null private
Referenced by IG.Forms.FadingMessage.LaunchInNewThread().
_wasLaunched
bool IG.Forms.FadingMessage._wasLaunched = false private
_launchedInParallelThread
bool IG.Forms.FadingMessage._launchedInParallelThread = false private
_startTime
DateTime IG.Forms.FadingMessage._startTime private
_minTickInterval
int IG.Forms.FadingMessage._minTickInterval = 40 private
_maxTicks
int IG.Forms.FadingMessage._maxTicks = 50 private
_numTicks
int IG.Forms.FadingMessage._numTicks = 0 private
_totalTicks
int IG.Forms.FadingMessage._totalTicks = 20 private
_firstTick
int IG.Forms.FadingMessage._firstTick = 1000 private
_tickInterval
int IG.Forms.FadingMessage._tickInterval = 100 private
_fadingFactor
double IG.Forms.FadingMessage._fadingFactor = 0 private
_isFormClosing
volatile bool IG.Forms.FadingMessage._isFormClosing = false private
Referenced by IG.Forms.FadingMessage.CloseForm().
_isFormClosed
volatile bool IG.Forms.FadingMessage._isFormClosed = false private
Referenced by IG.Forms.FadingMessage.CloseForm().
m_PrevX
int IG.Forms.FadingMessage.m_PrevX private
Referenced by IG.Forms.FadingMessage.FadeMessage_MouseDown(), and IG.Forms.FadingMessage.FadeMessage_MouseMove().
m_PrevY
int IG.Forms.FadingMessage.m_PrevY private
Referenced by IG.Forms.FadingMessage.FadeMessage_MouseDown(), and IG.Forms.FadingMessage.FadeMessage_MouseMove().
_minRemainingSecMenu
double IG.Forms.FadingMessage._minRemainingSecMenu = 8.0 private
components
System.ComponentModel.IContainer IG.Forms.FadingMessage.components = null private
Required designer variable.
Referenced by IG.Forms.FadingMessage.Dispose().
timer1
System.Windows.Forms.Timer IG.Forms.FadingMessage.timer1 private
Referenced by IG.Forms.FadingMessage.CloseForm(), IG.Forms.FadingMessage.FadeMessage_Load(), IG.Forms.FadingMessage.LauncherMethod(), and IG.Forms.FadingMessage.timer1_Tick().
btnCancel
System.Windows.Forms.Button IG.Forms.FadingMessage.btnCancel private
Referenced by IG.Forms.FadingMessage.FadeMessage_Load().
lblStatus
System.Windows.Forms.Label IG.Forms.FadingMessage.lblStatus private
Referenced by IG.Forms.FadingMessage.FadeMessage_Load().
BodyPnl
System.Windows.Forms.Panel IG.Forms.FadingMessage.BodyPnl private
Referenced by IG.Forms.FadingMessage.FadeMessage_Load().
lblMEssage
System.Windows.Forms.Label IG.Forms.FadingMessage.lblMEssage private
Referenced by IG.Forms.FadingMessage.CopyMessageToClipboard(), and IG.Forms.FadingMessage.FadeMessage_Load().
lblTitle
System.Windows.Forms.Label IG.Forms.FadingMessage.lblTitle private
Referenced by IG.Forms.FadingMessage.FadeMessage_Load().
PnlStatus
System.Windows.Forms.Panel IG.Forms.FadingMessage.PnlStatus private
Referenced by IG.Forms.FadingMessage.FadeMessage_Load().
labelBottom
System.Windows.Forms.Label IG.Forms.FadingMessage.labelBottom private
Referenced by IG.Forms.FadingMessage.FadeMessage_Load().
menuMain
System.Windows.Forms.ContextMenuStrip IG.Forms.FadingMessage.menuMain private
Referenced by IG.Forms.FadingMessage.FadeMessage_MouseClick().
menuCopyMessage
System.Windows.Forms.ToolStripMenuItem IG.Forms.FadingMessage.menuCopyMessage private
menuClose
System.Windows.Forms.ToolStripMenuItem IG.Forms.FadingMessage.menuClose private
menuLaunchThreadParallel
System.Windows.Forms.ToolStripMenuItem IG.Forms.FadingMessage.menuLaunchThreadParallel private
menuIdentifyThread
System.Windows.Forms.ToolStripMenuItem IG.Forms.FadingMessage.menuIdentifyThread private
menuLaunchSameThread
System.Windows.Forms.ToolStripMenuItem IG.Forms.FadingMessage.menuLaunchSameThread private
menuExample
System.Windows.Forms.ToolStripMenuItem IG.Forms.FadingMessage.menuExample private
menuExampleMassive
System.Windows.Forms.ToolStripMenuItem IG.Forms.FadingMessage.menuExampleMassive private
Property Documentation
LockStatic
object IG.Forms.FadingMessage.LockStatic static get
Static lock object that can be used by all fadiing message objects.
Referenced by IG.Forms.FadingMessage.DecrementNumShown(), IG.Forms.FadingMessage.GetNextId(), IG.Forms.FadingMessage.IncrementNumLaunched(), and IG.Forms.FadingMessage.IncrementNumShown().
Lock
object IG.Forms.FadingMessage.Lock get
ILockable's lock object.
Referenced by IG.Forms.FadingMessage.CloseForm().
Id
int IG.Forms.FadingMessage.Id get
ID of the current fading message object.
Referenced by IG.Forms.FadingMessage.menuIdentifyThread_Click().
NumLaunched
int IG.Forms.FadingMessage.NumLaunched static get
Gets the total number of launched fading messages.
Referenced by IG.Forms.FadingMessage.CloseForm().
NumShown
int IG.Forms.FadingMessage.NumShown static get
Gets the total number of fading messages that aree currently active (displayed).
Referenced by IG.Forms.FadingMessage.CloseForm(), IG.Forms.FadingMessage.LaunchInNewThread(), and IG.Forms.FadingMessage.ManipulationThreadFunc().
OutputLevel
int IG.Forms.FadingMessage.OutputLevel static get set protected
Level of output printed to console (for debugging).
Referenced by IG.Forms.FadingMessage.CloseForm(), IG.Forms.FadingMessage.FadeMessage_FormClosing(), IG.Forms.FadingMessage.LauncherMethod(), IG.Forms.FadingMessage.LaunchInNewThread(), IG.Forms.FadingMessage.ManipulationThreadFunc(), IG.Forms.FadingMessage.menuMain_Opening(), IG.Forms.FadingMessage.SetScreenPosition(), and IG.Forms.FadingMessage.timer1_Tick().
IsTopMostWindow
bool IG.Forms.FadingMessage.IsTopMostWindow get set
Whether or not the launched fading message is a topmost window.
Referenced by IG.Forms.ReporterForms.DefaultReport_FadeMessage(), IG.Forms.FadingMessage.ExampleLargeNum(), IG.Forms.UtilForms.IdentifyCurrentThread(), IG.Forms.FadingMessage.InitFadingMessageBegin(), and IG.Forms.HashControl.SetGeneralProperties().
LaunchedAtMouseCursor
bool IG.Forms.FadingMessage.LaunchedAtMouseCursor get set
Whether the message should be launched at the position of the mouse cursor.
If set when the message is displayed, the form moves to the position of mouse cursor.
Referenced by IG.Neural.Applications.NeuralDemoAbout.BrowseHelp(), IG.Neural.Applications.NeuralDemoAbout.BrowseWebPage(), IG.Forms.ReporterForms.DefaultReport_FadeMessage(), IG.Forms.FadingMessage.ExampleLargeNum(), IG.Neural.Applications.NeuralDemoAbout.HelpBrowse(), IG.Forms.HashAboutControl.HelpBrowse(), IG.Neural.Applications.NeuralDemoAbout.HelpPdf(), IG.Forms.HashAboutControl.HelpPdf(), IG.Forms.FadingMessage.LauncherMethod(), IG.Forms.HashControl.SetGeneralProperties(), IG.Neural.Applications.NeuralDemoAbout.WebPageBrowse(), and IG.Forms.HashAboutControl.WebPageBrowse().
ShowTime
int IG.Forms.FadingMessage.ShowTime get set
Total time, in milliseconds, for which the message is displayed.
Referenced by IG.Forms.ReporterForms.DefaultReport_FadeMessage(), IG.Forms.ReporterForms.DefaultReserveReportErrorForms(), IG.Forms.FadingMessage.FadeMessage_Load(), IG.Forms.FadingMessage.InitFadingMessageBegin(), IG.Forms.FadingMessage.LauncherMethod(), IG.Forms.XMLTreeViewFormOld_Keep_Some_time.ReportError0(), IG.Forms.XmlTreeViewControl.ReportError0(), and IG.Forms.ConsoleForm.ReserveReportError0().
FadingTimePortion
double IG.Forms.FadingMessage.FadingTimePortion get set
Portion of display time in which the message background color fades at the end of its display time.
Referenced by IG.Forms.ReporterForms.DefaultReport_FadeMessage(), IG.Forms.ReporterForms.DefaultReserveReportErrorForms(), IG.Forms.FadingMessage.FadeMessage_Load(), IG.Forms.FadingMessage.InitFadingMessageBegin(), and IG.Forms.FadingMessage.LauncherMethod().
WasLaunched
bool IG.Forms.FadingMessage.WasLaunched get protected set
Specifies whether the current fading message has already been launched.
Referenced by IG.Forms.FadingMessage.Launch(), IG.Forms.FadingMessage.LauncherMethod(), and IG.Forms.FadingMessage.menuIdentifyThread_Click().
LaunchedInParallelThread
bool IG.Forms.FadingMessage.LaunchedInParallelThread get set
Specifies whether the current fading message has been launched in a parallel thread.
Referenced by IG.Neural.Applications.NeuralDemoAbout.BrowseHelp(), IG.Neural.Applications.NeuralDemoAbout.BrowseWebPage(), IG.Neural.Applications.NeuralDemoAbout.HelpBrowse(), IG.Forms.HashAboutControl.HelpBrowse(), IG.Neural.Applications.NeuralDemoAbout.HelpPdf(), IG.Forms.HashAboutControl.HelpPdf(), IG.Forms.FadingMessage.LauncherMethod(), IG.Forms.FadingMessage.menuIdentifyThread_Click(), IG.Forms.OutputValueSelector.menuSummary_Click(), IG.Forms.InputParameterSelectorMinMax.menuSummary_Click(), IG.Forms.HashControl.SetGeneralProperties(), IG.Neural.Applications.NeuralDemoAbout.WebPageBrowse(), and IG.Forms.HashAboutControl.WebPageBrowse().
StartTime
DateTime IG.Forms.FadingMessage.StartTime get protected set
Time when the fading message was launched.
Referenced by IG.Forms.FadingMessage.LauncherMethod().
ElapsedTimeSpan
TimeSpan IG.Forms.FadingMessage.ElapsedTimeSpan get protected
Gets the amount of time during which the message has been displayed until now.
Zero time span is returned if the message has not yett been displayed.
ShowTimeSpan
TimeSpan IG.Forms.FadingMessage.ShowTimeSpan get set
Gets or sets the total time span for which the message is to be displayed.
RemainingTimeSpan
TimeSpan IG.Forms.FadingMessage.RemainingTimeSpan get protected set
Gets the remaining time span for which the message will be displayed.
Can be negative.
Referenced by IG.Forms.FadingMessage.CloseForm(), IG.Forms.FadingMessage.FadeMessage_FormClosing(), IG.Forms.FadingMessage.LauncherMethod(), IG.Forms.FadingMessage.ManipulationThreadFunc(), IG.Forms.FadingMessage.menuIdentifyThread_Click(), IG.Forms.FadingMessage.menuMain_Opening(), and IG.Forms.FadingMessage.timer1_Tick().
MinTickinterval
int IG.Forms.FadingMessage.MinTickinterval get set private
Minimal tick interval in milliseconds.
Referenced by IG.Forms.FadingMessage.FadeMessage_Load(), and IG.Forms.FadingMessage.LauncherMethod().
MaxTicks
int IG.Forms.FadingMessage.MaxTicks get set private
Maximal number of timer ticks before the message fades out (this refers to the second part of the message).
Referenced by IG.Forms.FadingMessage.FadeMessage_Load(), and IG.Forms.FadingMessage.LauncherMethod().
NumTicks
int IG.Forms.FadingMessage.NumTicks get set private
Number of timer ticks that occurred after the fading message has been launched.
This onlly counts ticks in the fading portion of display time.
Referenced by IG.Forms.FadingMessage.timer1_Tick().
TotalTicks
int IG.Forms.FadingMessage.TotalTicks get set private
Total number of timerr ticks in the fading portion of the message display time.
Referenced by IG.Forms.FadingMessage.FadeMessage_Load(), IG.Forms.FadingMessage.LauncherMethod(), and IG.Forms.FadingMessage.timer1_Tick().
FirstTickInterval
int IG.Forms.FadingMessage.FirstTickInterval get set private
Length of the first timer tick interval in milliseconds. <pra>The first tick marks start of the fading portion of the display time. After the first tick, tick interval is reduced to enable smooth color transition.</pra>
Referenced by IG.Forms.FadingMessage.FadeMessage_Load(), and IG.Forms.FadingMessage.LauncherMethod().
TickInterval
int IG.Forms.FadingMessage.TickInterval get set private
Current tick interval in milliseconds.
Referenced by IG.Forms.FadingMessage.FadeMessage_Load(), IG.Forms.FadingMessage.LauncherMethod(), and IG.Forms.FadingMessage.timer1_Tick().
FadingFactor
double IG.Forms.FadingMessage.FadingFactor get set protected
Current fading factor - extent to which the active bacground color has changed to the faded color.
Referenced by IG.Forms.FadingMessage.timer1_Tick().
IsFormClosing
bool IG.Forms.FadingMessage.IsFormClosing get
Gets a flag indicating whether the fading message is currently being closed.
IsFormClosedOrClosing
bool IG.Forms.FadingMessage.IsFormClosedOrClosing get
Gets aa flag indicating whether the form has been closed or is currently being closed.
Referenced by IG.Forms.FadingMessage.timer1_Tick().
MinimalRemainingSecondsWithMenu
double IG.Forms.FadingMessage.MinimalRemainingSecondsWithMenu get set protected
Minimal remaining show time, in seconds, when user launches a context menu.
If in that case the remaining display time of the message is lesser than the minimum time, the display time is extented accordingly.
Referenced by IG.Forms.FadingMessage.menuMain_Opening().
The documentation for this class was generated from the following files:
iglib/igforms/Basic/FadingMessage.cs
iglib/igforms/Basic/FadingMessage.Designer.cs