Doc: IGLib EXTENDED: NUnit.Framework.Internal.Builders.DatapointProvider Class Reference
NUnit.Framework.Internal.Builders.DatapointProvider Class Reference
Provides data from fields marked with the DatapointAttribute or the DatapointsAttribute.
Public Member Functions
bool HasDataFor (IParameterInfo parameter)
Determine whether any data is available for a parameter.
System.Collections.IEnumerable GetDataFor (IParameterInfo parameter)
Return an IEnumerable providing data for use with the supplied parameter.
Private Member Functions
Type GetTypeFromMemberInfo (MemberInfo member)
Type GetElementTypeFromMemberInfo (MemberInfo member)
Detailed Description
Provides data from fields marked with the DatapointAttribute or the DatapointsAttribute.
Member Function Documentation
HasDataFor()
bool NUnit.Framework.Internal.Builders.DatapointProvider.HasDataFor (IParameterInfo parameter) inline
Determine whether any data is available for a parameter.
Parameters
parameter A ParameterInfo representing one argument to a parameterized test
Returns
True if any data is available, otherwise false.
Implements NUnit.Framework.Interfaces.IParameterDataProvider.
References NUnit.Framework.Internal.Builders.DatapointProvider.GetElementTypeFromMemberInfo(), NUnit.Framework.Internal.Builders.DatapointProvider.GetTypeFromMemberInfo(), NUnit.Framework.Interfaces.IParameterInfo.Method, and NUnit.Framework.Interfaces.IParameterInfo.ParameterType.
GetDataFor()
System.Collections.IEnumerable NUnit.Framework.Internal.Builders.DatapointProvider.GetDataFor (IParameterInfo parameter) inline
Return an IEnumerable providing data for use with the supplied parameter.
Parameters
parameter A ParameterInfo representing one argument to a parameterized test
Returns
An IEnumerable providing the required data
Implements NUnit.Framework.Interfaces.IParameterDataProvider.
References NUnit.Framework.Internal.Builders.DatapointProvider.GetElementTypeFromMemberInfo(), NUnit.Framework.Internal.TypeHelper.GetEnumValues(), NUnit.Framework.Internal.Builders.ProviderCache.GetInstanceOf(), NUnit.Framework.Internal.Builders.DatapointProvider.GetTypeFromMemberInfo(), NUnit.Framework.Interfaces.IParameterInfo.Method, NUnit.Framework.Interfaces.IParameterInfo.ParameterType, NUnit.Framework.Interfaces.ITypeInfo.Type, and NUnit.Framework.Interfaces.IMethodInfo.TypeInfo.
GetTypeFromMemberInfo()
Type NUnit.Framework.Internal.Builders.DatapointProvider.GetTypeFromMemberInfo (MemberInfo member) inline private
Referenced by NUnit.Framework.Internal.Builders.DatapointProvider.GetDataFor(), NUnit.Framework.Internal.Builders.DatapointProvider.GetElementTypeFromMemberInfo(), and NUnit.Framework.Internal.Builders.DatapointProvider.HasDataFor().
GetElementTypeFromMemberInfo()
Type NUnit.Framework.Internal.Builders.DatapointProvider.GetElementTypeFromMemberInfo (MemberInfo member) inline private
References NUnit.Framework.Internal.Builders.DatapointProvider.GetTypeFromMemberInfo().
Referenced by NUnit.Framework.Internal.Builders.DatapointProvider.GetDataFor(), and NUnit.Framework.Internal.Builders.DatapointProvider.HasDataFor().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/Builders/DatapointProvider.cs