Doc: IGLib EXTENDED: AForge.Genetic.BinaryChromosome Class Reference
AForge.Genetic.BinaryChromosome Class Reference
Binary chromosome, which supports length from 2 till 64.
Public Member Functions
BinaryChromosome (int length)
Initializes a new instance of the BinaryChromosome class.
override string ToString ()
Get string representation of the chromosome.
override void Generate ()
Generate random chromosome value.
override IChromosome CreateNew ()
Create new random chromosome with same parameters (factory method).
override IChromosome Clone ()
Clone the chromosome.
override void Mutate ()
Mutation operator.
override void Crossover (IChromosome pair)
Crossover operator.
Public Member Functions inherited from AForge.Genetic.ChromosomeBase
void Evaluate (IFitnessFunction function)
Evaluate chromosome with specified fitness function.
int CompareTo (object o)
Compare two chromosomes.
Static Public Attributes
const int MaxLength = 64
Chromosome's maximum length.
Protected Member Functions
BinaryChromosome (BinaryChromosome source)
Initializes a new instance of the BinaryChromosome class.
Protected Attributes
int length
Chromosome's length in bits.
ulong val = 0
Numerical chromosome's value.
Protected Attributes inherited from AForge.Genetic.ChromosomeBase
double fitness = 0
Chromosome's fintess value.
Static Protected Attributes
static ThreadSafeRandom rand = new ThreadSafeRandom()
Random number generator for chromosoms generation, crossover, mutation, etc.
Properties
int Length [get]
Chromosome's length.
ulong Value [get]
Chromosome's value.
ulong MaxValue [get]
Max possible chromosome's value.
Properties inherited from AForge.Genetic.ChromosomeBase
double Fitness [get]
Chromosome's fintess value.
Properties inherited from AForge.Genetic.IChromosome
double Fitness [get]
Chromosome's fintess value.
Detailed Description
Binary chromosome, which supports length from 2 till 64.
The binary chromosome is the simplest type of chromosomes, which is represented by a set of bits. Maximum number of bits comprising the chromosome is 64.
Constructor & Destructor Documentation
BinaryChromosome() [1/2]
AForge.Genetic.BinaryChromosome.BinaryChromosome (int length) inline
Initializes a new instance of the BinaryChromosome class.
Parameters
length Chromosome's length in bits, [2, MaxLength].
References AForge.Genetic.BinaryChromosome.Generate(), AForge.Genetic.BinaryChromosome.length, and AForge.Genetic.BinaryChromosome.MaxLength.
Referenced by AForge.Genetic.BinaryChromosome.Clone(), AForge.Genetic.BinaryChromosome.CreateNew(), and AForge.Genetic.BinaryChromosome.Crossover().
BinaryChromosome() [2/2]
AForge.Genetic.BinaryChromosome.BinaryChromosome (BinaryChromosome source) inline protected
Initializes a new instance of the BinaryChromosome class.
Parameters
source Source chromosome to copy.
This is a copy constructor, which creates the exact copy of specified chromosome.
References AForge.Genetic.ChromosomeBase.fitness, AForge.Genetic.BinaryChromosome.length, and AForge.Genetic.BinaryChromosome.val.
Member Function Documentation
ToString()
override string AForge.Genetic.BinaryChromosome.ToString () inline
Get string representation of the chromosome.
Returns
Returns string representation of the chromosome.
References AForge.Genetic.BinaryChromosome.length, and AForge.Genetic.BinaryChromosome.val.
Generate()
override void AForge.Genetic.BinaryChromosome.Generate () inline virtual
Generate random chromosome value.
Regenerates chromosome's value using random number generator.
Implements AForge.Genetic.ChromosomeBase.
References AForge.ThreadSafeRandom.NextBytes(), AForge.Genetic.BinaryChromosome.rand, and AForge.Genetic.BinaryChromosome.val.
Referenced by AForge.Genetic.BinaryChromosome.BinaryChromosome().
CreateNew()
override IChromosome AForge.Genetic.BinaryChromosome.CreateNew () inline virtual
Create new random chromosome with same parameters (factory method).
The method creates new chromosome of the same type, but randomly initialized. The method is useful as factory method for those classes, which work with chromosome's interface, but not with particular chromosome type.
Implements AForge.Genetic.ChromosomeBase.
References AForge.Genetic.BinaryChromosome.BinaryChromosome(), and AForge.Genetic.BinaryChromosome.length.
Clone()
override IChromosome AForge.Genetic.BinaryChromosome.Clone () inline virtual
Clone the chromosome.
Returns
Return's clone of the chromosome.
The method clones the chromosome returning the exact copy of it.
Implements AForge.Genetic.ChromosomeBase.
References AForge.Genetic.BinaryChromosome.BinaryChromosome().
Mutate()
override void AForge.Genetic.BinaryChromosome.Mutate () inline virtual
Mutation operator.
The method performs chromosome's mutation, changing randomly one of its bits.
Implements AForge.Genetic.ChromosomeBase.
References AForge.Genetic.BinaryChromosome.length, AForge.ThreadSafeRandom.Next(), AForge.Genetic.BinaryChromosome.rand, and AForge.Genetic.BinaryChromosome.val.
Crossover()
override void AForge.Genetic.BinaryChromosome.Crossover (IChromosome pair) inline virtual
Crossover operator.
Parameters
pair Pair chromosome to crossover with.
The method performs crossover between two chromosomes – interchanging range of bits between these chromosomes.
Implements AForge.Genetic.ChromosomeBase.
References AForge.Genetic.BinaryChromosome.BinaryChromosome(), AForge.Genetic.BinaryChromosome.length, AForge.ThreadSafeRandom.Next(), AForge.Genetic.BinaryChromosome.rand, and AForge.Genetic.BinaryChromosome.val.
Member Data Documentation
length
int AForge.Genetic.BinaryChromosome.length protected
Chromosome's length in bits.
Referenced by AForge.Genetic.BinaryChromosome.BinaryChromosome(), AForge.Genetic.BinaryChromosome.CreateNew(), AForge.Genetic.BinaryChromosome.Crossover(), AForge.Genetic.BinaryChromosome.Mutate(), and AForge.Genetic.BinaryChromosome.ToString().
val
ulong AForge.Genetic.BinaryChromosome.val = 0 protected
Numerical chromosome's value.
Referenced by AForge.Genetic.BinaryChromosome.BinaryChromosome(), AForge.Genetic.BinaryChromosome.Crossover(), AForge.Genetic.BinaryChromosome.Generate(), AForge.Genetic.BinaryChromosome.Mutate(), and AForge.Genetic.BinaryChromosome.ToString().
rand
ThreadSafeRandom AForge.Genetic.BinaryChromosome.rand = new ThreadSafeRandom() static protected
Random number generator for chromosoms generation, crossover, mutation, etc.
Referenced by AForge.Genetic.BinaryChromosome.Crossover(), AForge.Genetic.BinaryChromosome.Generate(), and AForge.Genetic.BinaryChromosome.Mutate().
MaxLength
const int AForge.Genetic.BinaryChromosome.MaxLength = 64 static
Chromosome's maximum length.
Maxim chromosome's length in bits, which is supported by the class
Referenced by AForge.Genetic.BinaryChromosome.BinaryChromosome().
Property Documentation
Length
int AForge.Genetic.BinaryChromosome.Length get
Chromosome's length.
Length of the chromosome in bits.
Value
ulong AForge.Genetic.BinaryChromosome.Value get
Chromosome's value.
Current numerical value of the chromosome.
MaxValue
ulong AForge.Genetic.BinaryChromosome.MaxValue get
Max possible chromosome's value.
Maximum possible numerical value, which may be represented by the chromosome of current length.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Genetic/Chromosomes/BinaryChromosome.cs