Doc: IGLib EXTENDED: IG.Forms.TestTcpClient Class Reference
IG.Forms.TestTcpClient Class Reference
Public Member Functions
TestTcpClient ()
TestTcpClient (string IP, int portnum)
void Connect ()
void DisConnect ()
void Ping ()
void SendData (string Data)
void ClientTest ()
void ClientExampleMain ()
void Report (string str)
void ReportMarked (string str)
void ReportError (string str)
void ReportError (Exception e, string additionalmessage)
void ReportError (Exception e)
Public Attributes
int Port = 8000
string IPAddr = "127.0.0.1"
int ID = 0
Properties
ConsoleForm ClientConsole [get, set]
Returns the client's own console.
Private Member Functions
bool ConsoleReady ()
void CloseConsoleHandler (object sender, System.EventArgs e)
Private Attributes
int MaxReportLength = 60
string ReceivedMessage = null
int NumRequests = 0
TcpClient client = null
NetworkStream stream = null
BinaryWriter w = null
BinaryReader r =null
bool Connected = false
ConsoleForm clientcons = null
ConsoleForm auxcons
int reccount = 0
Static Private Attributes
static int numinstances = 0
static int totcount = 0
Constructor & Destructor Documentation
TestTcpClient() [1/2]
IG.Forms.TestTcpClient.TestTcpClient () inline
References IG.Forms.TestTcpClient.ID, and IG.Forms.TestTcpClient.numinstances.
TestTcpClient() [2/2]
IG.Forms.TestTcpClient.TestTcpClient (string IP, int portnum) inline
References IG.Forms.TestTcpClient.ID, IG.Forms.TestTcpClient.IPAddr, IG.Forms.TestTcpClient.numinstances, and IG.Forms.TestTcpClient.Port.
Member Function Documentation
Connect()
void IG.Forms.TestTcpClient.Connect () inline
References IG.Forms.TestTcpClient.client, IG.Forms.ServerMessages.ConnectAcknowledged, IG.Forms.TestTcpClient.Connected, IG.Forms.TestTcpClient.IPAddr, IG.Forms.TestTcpClient.NumRequests, IG.Forms.TestTcpClient.Port, IG.Forms.TestTcpClient.r, IG.Forms.TestTcpClient.ReceivedMessage, IG.Forms.TestTcpClient.Report(), IG.Forms.TestTcpClient.ReportError(), IG.Forms.ClientMessages.RequestConnect, IG.Forms.TestTcpClient.stream, and IG.Forms.TestTcpClient.w.
Referenced by IG.Forms.TestTcpClient.ClientTest(), and IG.Forms.TestTcpClient.Ping().
DisConnect()
void IG.Forms.TestTcpClient.DisConnect () inline
References IG.Forms.TestTcpClient.client, IG.Forms.TestTcpClient.Connected, IG.Forms.ServerMessages.DisconnectAcknowledged, IG.Forms.ClientMessages.DisconnectClient, IG.Forms.TestTcpClient.MaxReportLength, IG.Forms.TestTcpClient.r, IG.Forms.TestTcpClient.ReceivedMessage, IG.Forms.TestTcpClient.Report(), IG.Forms.TestTcpClient.ReportError(), and IG.Forms.TestTcpClient.w.
Referenced by IG.Forms.TestTcpClient.ClientTest(), and IG.Forms.TestTcpClient.Ping().
Ping()
void IG.Forms.TestTcpClient.Ping () inline
References IG.Forms.TestTcpClient.Connect(), IG.Forms.TestTcpClient.Connected, IG.Forms.TestTcpClient.DisConnect(), IG.Forms.TestTcpClient.IPAddr, IG.Forms.TestTcpClient.NumRequests, IG.Forms.ServerMessages.PingAcknowledgeSrv, IG.Forms.ClientMessages.PingRequestClient, IG.Forms.TestTcpClient.Port, IG.Forms.TestTcpClient.r, IG.Forms.TestTcpClient.ReceivedMessage, IG.Forms.TestTcpClient.Report(), IG.Forms.TestTcpClient.ReportError(), and IG.Forms.TestTcpClient.w.
Referenced by IG.Forms.TestTcpClient.ClientTest().
SendData()
void IG.Forms.TestTcpClient.SendData (string Data) inline
References IG.Forms.TestTcpClient.Connected, IG.Forms.TestTcpClient.MaxReportLength, IG.Forms.TestTcpClient.r, IG.Forms.ServerMessages.ReadySrv, IG.Forms.TestTcpClient.ReceivedMessage, IG.Forms.ServerMessages.ReceivedSrv, IG.Forms.TestTcpClient.Report(), IG.Forms.TestTcpClient.ReportError(), IG.Forms.ClientMessages.SendClient, and IG.Forms.TestTcpClient.w.
Referenced by IG.Forms.TestTcpClient.ClientTest().
ClientTest()
void IG.Forms.TestTcpClient.ClientTest () inline
References IG.Forms.TestTcpClient.ClientConsole, IG.Forms.TestTcpClient.Connect(), IG.Forms.TestTcpClient.DisConnect(), IG.Forms.TestTcpClient.Ping(), IG.Forms.ConsoleForm.ReadLine(), IG.Forms.TestTcpClient.ReportError(), IG.Forms.TestTcpClient.ReportMarked(), and IG.Forms.TestTcpClient.SendData().
Referenced by IG.Forms.client_program.Main().
ClientExampleMain()
void IG.Forms.TestTcpClient.ClientExampleMain () inline
References IG.Forms.TestTcpClient.client, IG.Forms.TestTcpClient.ClientConsole, IG.Forms.ServerMessages.ConnectAcknowledged, IG.Forms.ClientMessages.DisconnectClient, IG.Forms.TestTcpClient.IPAddr, IG.Forms.TestTcpClient.Port, IG.Forms.TestTcpClient.r, IG.Forms.ConsoleForm.ReadLine(), IG.Forms.TestTcpClient.Report(), IG.Forms.TestTcpClient.ReportError(), IG.Forms.ClientMessages.RequestConnect, IG.Forms.TestTcpClient.stream, and IG.Forms.TestTcpClient.w.
ConsoleReady()
bool IG.Forms.TestTcpClient.ConsoleReady () inline private
References IG.Forms.TestTcpClient.clientcons.
Referenced by IG.Forms.TestTcpClient.Report(), IG.Forms.TestTcpClient.ReportError(), and IG.Forms.TestTcpClient.ReportMarked().
CloseConsoleHandler()
void IG.Forms.TestTcpClient.CloseConsoleHandler (object sender, System.EventArgs e) inline private
Report()
void IG.Forms.TestTcpClient.Report (string str) inline
References IG.Forms.TestTcpClient.auxcons, IG.Forms.TestTcpClient.ClientConsole, IG.Forms.TestTcpClient.ConsoleReady(), IG.Forms.UtilForms.Reporter, IG.Forms.ConsoleForm.Style, and IG.Forms.ConsoleForm.WriteLine().
Referenced by IG.Forms.TestTcpClient.ClientExampleMain(), IG.Forms.TestTcpClient.Connect(), IG.Forms.TestTcpClient.DisConnect(), IG.Forms.TestTcpClient.Ping(), and IG.Forms.TestTcpClient.SendData().
ReportMarked()
void IG.Forms.TestTcpClient.ReportMarked (string str) inline
References IG.Forms.TestTcpClient.auxcons, IG.Forms.TestTcpClient.ClientConsole, IG.Forms.TestTcpClient.ConsoleReady(), IG.Forms.UtilForms.Reporter, IG.Forms.ConsoleForm.Style, and IG.Forms.ConsoleForm.WriteLine().
Referenced by IG.Forms.TestTcpClient.ClientTest().
ReportError() [1/3]
void IG.Forms.TestTcpClient.ReportError (string str) inline
References IG.Forms.TestTcpClient.auxcons, IG.Forms.TestTcpClient.ClientConsole, IG.Forms.TestTcpClient.ConsoleReady(), IG.Forms.UtilForms.Reporter, IG.Forms.ConsoleForm.Style, and IG.Forms.ConsoleForm.WriteLine().
Referenced by IG.Forms.TestTcpClient.ClientExampleMain(), IG.Forms.TestTcpClient.ClientTest(), IG.Forms.TestTcpClient.Connect(), IG.Forms.TestTcpClient.DisConnect(), IG.Forms.TestTcpClient.Ping(), IG.Forms.TestTcpClient.ReportError(), and IG.Forms.TestTcpClient.SendData().
ReportError() [2/3]
void IG.Forms.TestTcpClient.ReportError (Exception e, string additionalmessage) inline
References IG.Forms.UtilForms.Reporter, and IG.Forms.TestTcpClient.ReportError().
ReportError() [3/3]
void IG.Forms.TestTcpClient.ReportError (Exception e) inline
References IG.Forms.TestTcpClient.ReportError().
Referenced by IG.Forms.TestTcpClient.ReportError().
Member Data Documentation
Port
int IG.Forms.TestTcpClient.Port = 8000
Referenced by IG.Forms.TestTcpClient.ClientExampleMain(), IG.Forms.TestTcpClient.Connect(), IG.Forms.TestTcpClient.Ping(), and IG.Forms.TestTcpClient.TestTcpClient().
IPAddr
string IG.Forms.TestTcpClient.IPAddr = "127.0.0.1"
Referenced by IG.Forms.TestTcpClient.ClientExampleMain(), IG.Forms.TestTcpClient.Connect(), IG.Forms.TestTcpClient.Ping(), and IG.Forms.TestTcpClient.TestTcpClient().
MaxReportLength
int IG.Forms.TestTcpClient.MaxReportLength = 60 private
Referenced by IG.Forms.TestTcpClient.DisConnect(), and IG.Forms.TestTcpClient.SendData().
ID
int IG.Forms.TestTcpClient.ID = 0
Referenced by IG.Forms.TestTcpClient.TestTcpClient().
numinstances
int IG.Forms.TestTcpClient.numinstances = 0 static private
Referenced by IG.Forms.TestTcpClient.TestTcpClient().
ReceivedMessage
string IG.Forms.TestTcpClient.ReceivedMessage = null private
Referenced by IG.Forms.TestTcpClient.Connect(), IG.Forms.TestTcpClient.DisConnect(), IG.Forms.TestTcpClient.Ping(), and IG.Forms.TestTcpClient.SendData().
NumRequests
int IG.Forms.TestTcpClient.NumRequests = 0 private
Referenced by IG.Forms.TestTcpClient.Connect(), and IG.Forms.TestTcpClient.Ping().
client
TcpClient IG.Forms.TestTcpClient.client = null private
Referenced by IG.Forms.TestTcpClient.ClientExampleMain(), IG.Forms.TestTcpClient.Connect(), and IG.Forms.TestTcpClient.DisConnect().
stream
NetworkStream IG.Forms.TestTcpClient.stream = null private
Referenced by IG.Forms.TestTcpClient.ClientExampleMain(), and IG.Forms.TestTcpClient.Connect().
w
BinaryWriter IG.Forms.TestTcpClient.w = null private
Referenced by IG.Forms.TestTcpClient.ClientExampleMain(), IG.Forms.TestTcpClient.Connect(), IG.Forms.TestTcpClient.DisConnect(), IG.Forms.TestTcpClient.Ping(), and IG.Forms.TestTcpClient.SendData().
r
BinaryReader IG.Forms.TestTcpClient.r =null private
Referenced by IG.Forms.TestTcpClient.ClientExampleMain(), IG.Forms.TestTcpClient.Connect(), IG.Forms.TestTcpClient.DisConnect(), IG.Forms.TestTcpClient.Ping(), and IG.Forms.TestTcpClient.SendData().
Connected
bool IG.Forms.TestTcpClient.Connected = false private
Referenced by IG.Forms.TestTcpClient.Connect(), IG.Forms.TestTcpClient.DisConnect(), IG.Forms.TestTcpClient.Ping(), and IG.Forms.TestTcpClient.SendData().
clientcons
ConsoleForm IG.Forms.TestTcpClient.clientcons = null private
Referenced by IG.Forms.TestTcpClient.ConsoleReady().
auxcons
ConsoleForm IG.Forms.TestTcpClient.auxcons private
Referenced by IG.Forms.TestTcpClient.Report(), IG.Forms.TestTcpClient.ReportError(), and IG.Forms.TestTcpClient.ReportMarked().
reccount
int IG.Forms.TestTcpClient.reccount = 0 private
totcount
int IG.Forms.TestTcpClient.totcount = 0 static private
Property Documentation
ClientConsole
ConsoleForm IG.Forms.TestTcpClient.ClientConsole get set
Returns the client's own console.
Referenced by IG.Forms.TestTcpClient.ClientExampleMain(), IG.Forms.TestTcpClient.ClientTest(), IG.Forms.TestTcpClient.Report(), IG.Forms.TestTcpClient.ReportError(), and IG.Forms.TestTcpClient.ReportMarked().
The documentation for this class was generated from the following file:
igtest/iglib_sandbox/testclient/client_program.cs