Doc: IGLib EXTENDED: IG.Num.SimCastingRobertFileManager Class Reference
IG.Num.SimCastingRobertFileManager Class Reference
File manager for interfacing simulation casting simulator of Robert Vertnik.
Public Member Functions
SimCastingRobertFileManager (string rootDirectory, string projectName, string simulationName)
Constructs a file manager for interfacing simulation casting simulator of Robert Vertnik.
void UpdateRootDirectory ()
Updates the root directory path.
void RemoveTemporaryFilesFromExecutableDirpath ()
Removes temporary files from teh executable directory. This is crucial for normal working of the interface (otherwise there are errors saying for some temporary files that they are readonly).
virtual void ReadInputParameters (ref IVector inputParameters)
Reads optimization input parameters form the file at a standard location.
virtual void WriteInputParameters (IVector inputParameters)
Writes optimization input parameters to the standard location.
virtual void DeleteOutputFiles ()
Deletes the output files.
virtual void ReadOutputValues (ref IVector outputValues)
Reads optimization output values form the file at a standard location.
virtual void WriteOutputValues (IVector outputValues)
Writes optimization ouptut values to the standard location.
void RunSimulator ()
Runs the simulaor interfaced by the current object. This method only runs the simulator, it does not prepare any input.
void RunSimulator (string[] commandlineArguments)
Runns the simulator with the specified command-line arguments. Warning: this method should be used for testing only because the command-line arguments that should be passed to the simulator are specified by the interrface rules and can not be specified arbitrarily. Otherwise, run the overloaded method with no arguments. This method only runs the simulator, it does not prepare any input.
virtual void CalculateVectorResponse (IVector inputParameters, ref IVector outputValues)
Calculates simulator's response at the specified input parameters.
override string ToString ()
Returns a stirng that contains basic information about the current interfacing object, especially various relevant names (such as project name, etc.) and directory and file paths.
Protected Attributes
string _rootDirectory = null
string _projectName
string _simulationName
string _executableDirname = SimCastingRobertConst.ExecutableDirname
int _numInputParameters
int _numOutputValues
Static Protected Attributes
static string[] emptyCommandArguments = new string[0]
Properties
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
object InternalLock [get]
Used internally for locking access to internal fields.
int OutputLevel [get, set]
Level of information that is output to the console by some methods.
string RootDirectory [get, protected set]
Root directory for accessing casting simulator.
string ProjectName [get, protected set]
Casting simulator project name, specifies names of subdirextories of the main directories, where data actually resides.
string SimulationName [get, protected set]
Casting simulator simulation name, determines e.g. names of the optimization input and output files.
virtual string ExecutableDirpath [get, protected set]
Path of the directory where executable is located. Setter takes only pure directory name, without path information. If set to null then directory path is set to null and will be recalculated when getter is called.
virtual string InputDirpath [get, protected set]
Path of the directory where input files are located. Setter takes only pure directory name, without path information. If set to null then directory path is set to null and will be recalculated when getter is called.
virtual string OutputDirpath [get, protected set]
Path of the directory where output files are located. Setter takes only pure directory name, without path information. If set to null then directory path is set to null and will be recalculated when getter is called.
virtual string PlotOutputDirpath [get, protected set]
Path of the directory where plot files are located. Setter takes only pure directory name, without path information. If set to null then directory path is set to null and will be recalculated when getter is called.
virtual string MaterialDirpath [get, protected set]
Path of the directory where material data is located. Setter takes only pure directory name, without path information. If set to null then directory path is set to null and will be recalculated when getter is called.
virtual string RootDirectoryContainingFilepath [get, protected set]
File path of the file that contains the path of the directory containing the simulation directory structure. This file is important because it contents must be consistent with the actual location, otherwise simulation executable will not work. Only pure file name can be provided (if the full path is provided then only the file name is extracted, and the related path is calculated when firs needed). If set to null then file path is set to null and will be recalculated when getter is called.
virtual string ExecutablePath [get, protected set]
File path of simulator's executable. Only pure file name can be provided (if the full path is provided then only the file name is extracted, and the related path is calculated when firs needed). If set to null then file path is set to null and will be recalculated when getter is called.
virtual string SimulationNamePath [get, protected set]
Path to the file that contains the simulation name. Data found in this file specifies the names of input and output files. Only pure file name can be provided (if the full path is provided then only the file name is extracted, and the related path is calculated when firs needed). If set to null then file path is set to null and will be recalculated when getter is called.
virtual string OptInputJsonPath [get, protected set]
Path to the file that contains optimization input (usually stored by the caller of simulator). Only pure file name can be provided (if the full path is provided then only the file name is extracted, and the related path is calculated when firs needed). If set to null then file path is set to null and will be recalculated when getter is called.
virtual string OptOutputJsonPath [get, protected set]
Path to the file where optimization output values are stored by simulator. Only pure file name can be provided (if the full path is provided then only the file name is extracted, and the related path is calculated when firs needed). If set to null then file path is set to null and will be recalculated when getter is called.
virtual int NumInputParameters [get, set]
Number of input optimization parameters for the simulator.
virtual int NumOutputValues [get, set]
Number of optimization output values produced by the simulator.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Member Functions
SimCastingRobertFileManager ()
Private Attributes
object _mainLock = new object()
object _internalLock = new object()
int _outputLevel = Util.OutputLevel
string _executableDirpath = null
string _inputDirname = SimCastingRobertConst.InputDirname
string _inputDirpath = null
string _outputDirname = SimCastingRobertConst.OutputDirname
string _outputDirpath = null
string _plotoutputDirname = SimCastingRobertConst.PlotoutputDirname
string _plotoutputDirpath = null
string _materialDirname = SimCastingRobertConst.MaterialDirname
string _materialDirpath = null
string _rootDirectoryContainingFilename = SimCastingRobertConst.RootDirectoryContainingFilename
string _rootDirectoryContainingPath = null
string _executableFilename = SimCastingRobertConst.ExecutableFilename
string _executablePath = null
string _simulationNameFilename = SimCastingRobertConst.SimulationNameFilename
string _simulationNamePath = null
string _simJsonExtension = SimCastingRobertConst.SimJsonExtension
string _optInputJsonFilename = null
string _optInputJsonPath = null
string _optOutputJsonFilename = null
string _optOutputJsonPath = null
Detailed Description
File manager for interfacing simulation casting simulator of Robert Vertnik.
$A Igor Jul11;
Constructor & Destructor Documentation
SimCastingRobertFileManager() [1/2]
IG.Num.SimCastingRobertFileManager.SimCastingRobertFileManager () inline private
SimCastingRobertFileManager() [2/2]
IG.Num.SimCastingRobertFileManager.SimCastingRobertFileManager (string rootDirectory, string projectName, string simulationName) inline
Constructs a file manager for interfacing simulation casting simulator of Robert Vertnik.
Parameters
rootDirectory Root directory containing all base directories for simulator data.
projectName Name of the project, which determines nmes of subdirectories of base directories that contain data for the current project.
simulationName Simulation name, which determines e.g. names of optimization input and output files used for data exchange between optimization and simulation.
References IG.Num.SimCastingRobertFileManager.ProjectName, IG.Num.SimCastingRobertFileManager.RemoveTemporaryFilesFromExecutableDirpath(), IG.Num.SimCastingRobertFileManager.RootDirectory, IG.Num.SimCastingRobertFileManager.SimulationName, and IG.Num.SimCastingRobertFileManager.UpdateRootDirectory().
Member Function Documentation
UpdateRootDirectory()
void IG.Num.SimCastingRobertFileManager.UpdateRootDirectory () inline
Updates the root directory path.
References IG.Num.SimCastingRobertFileManager.OutputLevel, IG.Num.SimCastingRobertFileManager.RootDirectory, IG.Num.SimCastingRobertFileManager.RootDirectoryContainingFilepath, and IG.Lib.UtilSystem.StandardizeDirectoryPath().
Referenced by IG.Num.SimCastingRobertFileManager.SimCastingRobertFileManager().
RemoveTemporaryFilesFromExecutableDirpath()
void IG.Num.SimCastingRobertFileManager.RemoveTemporaryFilesFromExecutableDirpath () inline
Removes temporary files from teh executable directory. This is crucial for normal working of the interface (otherwise there are errors saying for some temporary files that they are readonly).
References IG.Num.SimCastingRobertFileManager.ExecutableDirpath, and IG.Num.SimCastingRobertFileManager.OutputLevel.
Referenced by IG.Num.SimCastingRobertFileManager.SimCastingRobertFileManager().
ReadInputParameters()
virtual void IG.Num.SimCastingRobertFileManager.ReadInputParameters (ref IVector inputParameters) inline virtual
Reads optimization input parameters form the file at a standard location.
Parameters
inputParameters Reference to an object where input parameters are stored.
Reimplemented in IG.Num.ConvectionRobertFileManager.
References IG.Num.VectorBase.LoadJson(), IG.Num.SimCastingRobertFileManager.Lock, IG.Num.SimCastingRobertFileManager.NumInputParameters, and IG.Num.SimCastingRobertFileManager.OptInputJsonPath.
WriteInputParameters()
virtual void IG.Num.SimCastingRobertFileManager.WriteInputParameters (IVector inputParameters) inline virtual
Writes optimization input parameters to the standard location.
Parameters
outputValues Parameters to be written.
Reimplemented in IG.Num.ConvectionRobertFileManager, and IG.Num.ConvectionRev1RobertFileManager.
References IG.Num.IVector< T >.Length, IG.Num.SimCastingRobertFileManager.NumInputParameters, IG.Num.SimCastingRobertFileManager.OptInputJsonPath, and IG.Num.VectorBase.SaveJson().
Referenced by IG.Num.SimCastingRobertFileManager.CalculateVectorResponse().
DeleteOutputFiles()
virtual void IG.Num.SimCastingRobertFileManager.DeleteOutputFiles () inline virtual
Deletes the output files.
It is recommendable to delete simulation output before running simulation. In this way, one would know if the simulation program has been broken because the output file would not exist or would be corrupted (otherwise, one could simply read the output file genenerated in some previout run, without noticing that something is wrong).
Reimplemented in IG.Num.ConvectionRobertFileManager.
References IG.Num.SimCastingRobertFileManager.Lock, and IG.Num.SimCastingRobertFileManager.OptOutputJsonPath.
Referenced by IG.Num.SimCastingRobertFileManager.CalculateVectorResponse().
ReadOutputValues()
virtual void IG.Num.SimCastingRobertFileManager.ReadOutputValues (ref IVector outputValues) inline virtual
Reads optimization output values form the file at a standard location.
If for some reason the file does not exist or it is corrupted, the vector of output values is set to null.
Parameters
outputValues Reference to an object where output parameters will be stored.
Reimplemented in IG.Num.ConvectionRobertFileManager.
References IG.Num.VectorBase.LoadJson(), IG.Num.SimCastingRobertFileManager.Lock, IG.Num.SimCastingRobertFileManager.NumOutputValues, and IG.Num.SimCastingRobertFileManager.OptOutputJsonPath.
Referenced by IG.Num.SimCastingRobertFileManager.CalculateVectorResponse().
WriteOutputValues()
virtual void IG.Num.SimCastingRobertFileManager.WriteOutputValues (IVector outputValues) inline virtual
Writes optimization ouptut values to the standard location.
Parameters
outputValues Values to be written.
Reimplemented in IG.Num.ConvectionRobertFileManager.
References IG.Num.IVector< T >.Length, IG.Num.SimCastingRobertFileManager.Lock, IG.Num.SimCastingRobertFileManager.NumOutputValues, IG.Num.SimCastingRobertFileManager.OptOutputJsonPath, and IG.Num.VectorBase.SaveJson().
RunSimulator() [1/2]
void IG.Num.SimCastingRobertFileManager.RunSimulator () inline
Runs the simulaor interfaced by the current object. This method only runs the simulator, it does not prepare any input.
References IG.Num.SimCastingRobertFileManager.emptyCommandArguments.
Referenced by IG.Num.SimCastingRobertFileManager.CalculateVectorResponse().
RunSimulator() [2/2]
void IG.Num.SimCastingRobertFileManager.RunSimulator (string[] commandlineArguments) inline
Runns the simulator with the specified command-line arguments. Warning: this method should be used for testing only because the command-line arguments that should be passed to the simulator are specified by the interrface rules and can not be specified arbitrarily. Otherwise, run the overloaded method with no arguments. This method only runs the simulator, it does not prepare any input.
Parameters
commandlineArguments Command-line arguments that are passed to the simulator program.
References IG.Num.SimCastingRobertFileManager.ExecutableDirpath, IG.Num.SimCastingRobertFileManager.ExecutablePath, and IG.Lib.UtilSystem.ExecuteSystemCommand().
CalculateVectorResponse()
virtual void IG.Num.SimCastingRobertFileManager.CalculateVectorResponse (IVector inputParameters, ref IVector outputValues) inline virtual
Calculates simulator's response at the specified input parameters.
Parameters
inputParameters Input parameters for which response is calculated.
outputValues Vector object where the calculated response is stored after calculation.
Implements IG.Num.IResponseEvaluatorVectorSimple.
References IG.Num.SimCastingRobertFileManager.DeleteOutputFiles(), IG.Num.IVector< T >.Length, IG.Num.SimCastingRobertFileManager.Lock, IG.Num.SimCastingRobertFileManager.NumInputParameters, IG.Num.SimCastingRobertFileManager.NumOutputValues, IG.Num.SimCastingRobertFileManager.OptOutputJsonPath, IG.Num.SimCastingRobertFileManager.OutputLevel, IG.Num.SimCastingRobertFileManager.ReadOutputValues(), IG.Num.SimCastingRobertFileManager.RunSimulator(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.StopWatch1.Time, IG.Num.IVector< T >.ToStringMath(), IG.Lib.StopWatch1.TotalTime, and IG.Num.SimCastingRobertFileManager.WriteInputParameters().
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.TestSimulationExecution().
ToString()
override string IG.Num.SimCastingRobertFileManager.ToString () inline
Returns a stirng that contains basic information about the current interfacing object, especially various relevant names (such as project name, etc.) and directory and file paths.
References IG.Num.SimCastingRobertFileManager.ExecutableDirpath, IG.Num.SimCastingRobertFileManager.ExecutablePath, IG.Num.SimCastingRobertFileManager.InputDirpath, IG.Num.SimCastingRobertFileManager.OptInputJsonPath, IG.Num.SimCastingRobertFileManager.OptOutputJsonPath, IG.Num.SimCastingRobertFileManager.OutputDirpath, IG.Num.SimCastingRobertFileManager.ProjectName, IG.Num.SimCastingRobertFileManager.RootDirectory, IG.Num.SimCastingRobertFileManager.SimulationName, and IG.Num.SimCastingRobertFileManager.SimulationNamePath.
Referenced by IG.Script.S_13_5_Convection.InitializeThis(), IG.Script.S_13_7_ConvectionRev1.InitializeThis(), IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00.InitializeThis(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.InitializeThis(), IG.Num.ConvectionRev1RobertFileManager.WriteInputParameters(), and IG.Num.ConvectionRobertFileManager.WriteInputParameters().
Member Data Documentation
_mainLock
object IG.Num.SimCastingRobertFileManager._mainLock = new object() private
_internalLock
object IG.Num.SimCastingRobertFileManager._internalLock = new object() private
_outputLevel
int IG.Num.SimCastingRobertFileManager._outputLevel = Util.OutputLevel private
_rootDirectory
string IG.Num.SimCastingRobertFileManager._rootDirectory = null protected
_projectName
string IG.Num.SimCastingRobertFileManager._projectName protected
_simulationName
string IG.Num.SimCastingRobertFileManager._simulationName protected
_executableDirname
string IG.Num.SimCastingRobertFileManager._executableDirname = SimCastingRobertConst.ExecutableDirname protected
_executableDirpath
string IG.Num.SimCastingRobertFileManager._executableDirpath = null private
_inputDirname
string IG.Num.SimCastingRobertFileManager._inputDirname = SimCastingRobertConst.InputDirname private
_inputDirpath
string IG.Num.SimCastingRobertFileManager._inputDirpath = null private
_outputDirname
string IG.Num.SimCastingRobertFileManager._outputDirname = SimCastingRobertConst.OutputDirname private
_outputDirpath
string IG.Num.SimCastingRobertFileManager._outputDirpath = null private
_plotoutputDirname
string IG.Num.SimCastingRobertFileManager._plotoutputDirname = SimCastingRobertConst.PlotoutputDirname private
_plotoutputDirpath
string IG.Num.SimCastingRobertFileManager._plotoutputDirpath = null private
_materialDirname
string IG.Num.SimCastingRobertFileManager._materialDirname = SimCastingRobertConst.MaterialDirname private
_materialDirpath
string IG.Num.SimCastingRobertFileManager._materialDirpath = null private
_rootDirectoryContainingFilename
string IG.Num.SimCastingRobertFileManager._rootDirectoryContainingFilename = SimCastingRobertConst.RootDirectoryContainingFilename private
_rootDirectoryContainingPath
string IG.Num.SimCastingRobertFileManager._rootDirectoryContainingPath = null private
_executableFilename
string IG.Num.SimCastingRobertFileManager._executableFilename = SimCastingRobertConst.ExecutableFilename private
_executablePath
string IG.Num.SimCastingRobertFileManager._executablePath = null private
_simulationNameFilename
string IG.Num.SimCastingRobertFileManager._simulationNameFilename = SimCastingRobertConst.SimulationNameFilename private
_simulationNamePath
string IG.Num.SimCastingRobertFileManager._simulationNamePath = null private
_simJsonExtension
string IG.Num.SimCastingRobertFileManager._simJsonExtension = SimCastingRobertConst.SimJsonExtension private
_optInputJsonFilename
string IG.Num.SimCastingRobertFileManager._optInputJsonFilename = null private
_optInputJsonPath
string IG.Num.SimCastingRobertFileManager._optInputJsonPath = null private
_optOutputJsonFilename
string IG.Num.SimCastingRobertFileManager._optOutputJsonFilename = null private
_optOutputJsonPath
string IG.Num.SimCastingRobertFileManager._optOutputJsonPath = null private
_numInputParameters
int IG.Num.SimCastingRobertFileManager._numInputParameters protected
_numOutputValues
int IG.Num.SimCastingRobertFileManager._numOutputValues protected
emptyCommandArguments
string [] IG.Num.SimCastingRobertFileManager.emptyCommandArguments = new string[0] static protected
Referenced by IG.Num.SimCastingRobertFileManager.RunSimulator().
Property Documentation
Lock
object IG.Num.SimCastingRobertFileManager.Lock get
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Referenced by IG.Num.SimCastingRobertFileManager.CalculateVectorResponse(), IG.Num.SimCastingRobertFileManager.DeleteOutputFiles(), IG.Num.SimCastingRobertFileManager.ReadInputParameters(), IG.Num.SimCastingRobertFileManager.ReadOutputValues(), and IG.Num.SimCastingRobertFileManager.WriteOutputValues().
InternalLock
object IG.Num.SimCastingRobertFileManager.InternalLock get protected
Used internally for locking access to internal fields.
OutputLevel
int IG.Num.SimCastingRobertFileManager.OutputLevel get set
Level of information that is output to the console by some methods.
Referenced by IG.Num.SimCastingRobertFileManager.CalculateVectorResponse(), IG.Script.S_13_7_ConvectionRev1.InitializeThis(), IG.Script.S_13_5_Convection.InitializeThis(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.InitializeThis(), IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00.InitializeThis(), IG.Num.SimCastingRobertFileManager.RemoveTemporaryFilesFromExecutableDirpath(), and IG.Num.SimCastingRobertFileManager.UpdateRootDirectory().
RootDirectory
string IG.Num.SimCastingRobertFileManager.RootDirectory get protected set
Root directory for accessing casting simulator.
Referenced by IG.Num.SimCastingRobertFileManager.SimCastingRobertFileManager(), IG.Num.SimCastingRobertFileManager.ToString(), and IG.Num.SimCastingRobertFileManager.UpdateRootDirectory().
ProjectName
string IG.Num.SimCastingRobertFileManager.ProjectName get protected set
Casting simulator project name, specifies names of subdirextories of the main directories, where data actually resides.
Referenced by IG.Num.SimCastingRobertFileManager.SimCastingRobertFileManager(), and IG.Num.SimCastingRobertFileManager.ToString().
SimulationName
string IG.Num.SimCastingRobertFileManager.SimulationName get protected set
Casting simulator simulation name, determines e.g. names of the optimization input and output files.
Referenced by IG.Num.SimCastingRobertFileManager.SimCastingRobertFileManager(), and IG.Num.SimCastingRobertFileManager.ToString().
ExecutableDirpath
virtual string IG.Num.SimCastingRobertFileManager.ExecutableDirpath get protected set
Path of the directory where executable is located. Setter takes only pure directory name, without path information. If set to null then directory path is set to null and will be recalculated when getter is called.
Referenced by IG.Num.SimCastingRobertFileManager.RemoveTemporaryFilesFromExecutableDirpath(), IG.Num.SimCastingRobertFileManager.RunSimulator(), and IG.Num.SimCastingRobertFileManager.ToString().
InputDirpath
virtual string IG.Num.SimCastingRobertFileManager.InputDirpath get protected set
Path of the directory where input files are located. Setter takes only pure directory name, without path information. If set to null then directory path is set to null and will be recalculated when getter is called.
Referenced by IG.Num.SimCastingRobertFileManager.ToString().
OutputDirpath
virtual string IG.Num.SimCastingRobertFileManager.OutputDirpath get protected set
Path of the directory where output files are located. Setter takes only pure directory name, without path information. If set to null then directory path is set to null and will be recalculated when getter is called.
Referenced by IG.Num.SimCastingRobertFileManager.ToString().
PlotOutputDirpath
virtual string IG.Num.SimCastingRobertFileManager.PlotOutputDirpath get protected set
Path of the directory where plot files are located. Setter takes only pure directory name, without path information. If set to null then directory path is set to null and will be recalculated when getter is called.
MaterialDirpath
virtual string IG.Num.SimCastingRobertFileManager.MaterialDirpath get protected set
Path of the directory where material data is located. Setter takes only pure directory name, without path information. If set to null then directory path is set to null and will be recalculated when getter is called.
RootDirectoryContainingFilepath
virtual string IG.Num.SimCastingRobertFileManager.RootDirectoryContainingFilepath get protected set
File path of the file that contains the path of the directory containing the simulation directory structure. This file is important because it contents must be consistent with the actual location, otherwise simulation executable will not work. Only pure file name can be provided (if the full path is provided then only the file name is extracted, and the related path is calculated when firs needed). If set to null then file path is set to null and will be recalculated when getter is called.
Referenced by IG.Num.SimCastingRobertFileManager.UpdateRootDirectory().
ExecutablePath
virtual string IG.Num.SimCastingRobertFileManager.ExecutablePath get protected set
File path of simulator's executable. Only pure file name can be provided (if the full path is provided then only the file name is extracted, and the related path is calculated when firs needed). If set to null then file path is set to null and will be recalculated when getter is called.
Referenced by IG.Num.SimCastingRobertFileManager.RunSimulator(), and IG.Num.SimCastingRobertFileManager.ToString().
SimulationNamePath
virtual string IG.Num.SimCastingRobertFileManager.SimulationNamePath get protected set
Path to the file that contains the simulation name. Data found in this file specifies the names of input and output files. Only pure file name can be provided (if the full path is provided then only the file name is extracted, and the related path is calculated when firs needed). If set to null then file path is set to null and will be recalculated when getter is called.
Referenced by IG.Num.SimCastingRobertFileManager.ToString().
OptInputJsonPath
virtual string IG.Num.SimCastingRobertFileManager.OptInputJsonPath get protected set
Path to the file that contains optimization input (usually stored by the caller of simulator). Only pure file name can be provided (if the full path is provided then only the file name is extracted, and the related path is calculated when firs needed). If set to null then file path is set to null and will be recalculated when getter is called.
Referenced by IG.Num.SimCastingRobertFileManager.ReadInputParameters(), IG.Num.SimCastingRobertFileManager.ToString(), and IG.Num.SimCastingRobertFileManager.WriteInputParameters().
OptOutputJsonPath
virtual string IG.Num.SimCastingRobertFileManager.OptOutputJsonPath get protected set
Path to the file where optimization output values are stored by simulator. Only pure file name can be provided (if the full path is provided then only the file name is extracted, and the related path is calculated when firs needed). If set to null then file path is set to null and will be recalculated when getter is called.
Referenced by IG.Num.SimCastingRobertFileManager.CalculateVectorResponse(), IG.Num.SimCastingRobertFileManager.DeleteOutputFiles(), IG.Num.SimCastingRobertFileManager.ReadOutputValues(), IG.Num.SimCastingRobertFileManager.ToString(), and IG.Num.SimCastingRobertFileManager.WriteOutputValues().
NumInputParameters
virtual int IG.Num.SimCastingRobertFileManager.NumInputParameters get set
Number of input optimization parameters for the simulator.
Referenced by IG.Num.SimCastingRobertFileManager.CalculateVectorResponse(), IG.Num.SimCastingRobertFileManager.ReadInputParameters(), and IG.Num.SimCastingRobertFileManager.WriteInputParameters().
NumOutputValues
virtual int IG.Num.SimCastingRobertFileManager.NumOutputValues get set
Number of optimization output values produced by the simulator.
Referenced by IG.Num.SimCastingRobertFileManager.CalculateVectorResponse(), IG.Num.SimCastingRobertFileManager.ReadOutputValues(), and IG.Num.SimCastingRobertFileManager.WriteOutputValues().
The documentation for this class was generated from the following file:
shelldev/lib/extended/LibNeuralExt/interfaces_simulations/robert/SimCastingRobertFileManager.cs