Doc: IGLib EXTENDED: NUnit.Framework.Attributes.ApartmentAttributeTests Class Reference
NUnit.Framework.Attributes.ApartmentAttributeTests Class Reference
Classes
class ChildFixtureRequiresMTA
class ChildFixtureRequiresSTA
class FixtureRequiresMTA
class FixtureRequiresSTA
Public Member Functions
void ApartmentStateUnknownThrowsException ()
void TestWithRequiresSTARunsInSTA ()
void TestWithRequiresMTARunsInMTA ()
Public Member Functions inherited from NUnit.Framework.Attributes.ThreadingTests
void GetParentThreadInfo ()
Additional Inherited Members
Static Protected Member Functions inherited from NUnit.Framework.Attributes.ThreadingTests
static ApartmentState GetApartmentState (Thread thread)
Properties inherited from NUnit.Framework.Attributes.ThreadingTests
Thread ParentThread [get, private set]
ApartmentState ParentThreadApartment [get, private set]
Member Function Documentation
ApartmentStateUnknownThrowsException()
void NUnit.Framework.Attributes.ApartmentAttributeTests.ApartmentStateUnknownThrowsException () inline
References NUnit.Framework.Throws.ArgumentException, and NUnit.Framework.Assert.That().
TestWithRequiresSTARunsInSTA()
void NUnit.Framework.Attributes.ApartmentAttributeTests.TestWithRequiresSTARunsInSTA () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.ThreadingTests.GetApartmentState(), NUnit.Framework.Attributes.ThreadingTests.ParentThread, NUnit.Framework.Attributes.ThreadingTests.ParentThreadApartment, and NUnit.Framework.Assert.That().
TestWithRequiresMTARunsInMTA()
void NUnit.Framework.Attributes.ApartmentAttributeTests.TestWithRequiresMTARunsInMTA () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.ThreadingTests.GetApartmentState(), NUnit.Framework.Attributes.ThreadingTests.ParentThread, NUnit.Framework.Attributes.ThreadingTests.ParentThreadApartment, and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/ApartmentAttributeTests.cs