Doc: IGLib EXTENDED: AForge.Neuro.Learning.SOMLearning Class Reference
AForge.Neuro.Learning.SOMLearning Class Reference
Kohonen Self Organizing Map (SOM) learning algorithm
Public Member Functions
SOMLearning (DistanceNetwork network)
Initializes a new instance of the SOMLearning class
SOMLearning (DistanceNetwork network, int width, int height)
Initializes a new instance of the SOMLearning class
double Run (double[] input)
Runs learning iteration
double RunEpoch (double[][] input)
Runs learning epoch
SOMLearning (DistanceNetwork network)
Initializes a new instance of the SOMLearning class
SOMLearning (DistanceNetwork network, int width, int height)
Initializes a new instance of the SOMLearning class
double Run (double[] input)
Runs learning iteration
double RunEpoch (double[][] input)
Runs learning epoch
SOMLearning (DistanceNetwork network)
Initializes a new instance of the SOMLearning class.
SOMLearning (DistanceNetwork network, int width, int height)
Initializes a new instance of the SOMLearning class.
double Run (double[] input)
Runs learning iteration.
double RunEpoch (double[][] input)
Runs learning epoch.
Properties
double LearningRate [get, set]
Learning rate
double LearningRadius [get, set]
Learning radius
Private Attributes
DistanceNetwork network
int width
int height
double learningRate = 0.1
double learningRadius = 7
double squaredRadius2 = 2 * 7 * 7
Detailed Description
Kohonen Self Organizing Map (SOM) learning algorithm
Kohonen Self Organizing Map (SOM) learning algorithm.
This class implements Kohonen's SOM learning algorithm and is widelí used in clusterization tasks. The class allows to train Distance Networks.
This class implements Kohonen's SOM learning algorithm and is widely used in clusterization tasks. The class allows to train Distance Networks.
Sample usage (clustering RGB colors):
// set range for randomization neurons' weights
Neuron.RandRange = new Range(0, 255);
// create network
DistanceNetwork network = new DistanceNetwork(
        3, // thress inputs in the network
        100 * 100 ); // 10000 neurons
// create learning algorithm
SOMLearning trainer = new SOMLearning(network);
// network's input
double[] input = new double[3];
// loop
while (!needToStop)
{
    input[0] = rand.Next( 256 );
    input[1] = rand.Next( 256 );
    input[2] = rand.Next( 256 );
    trainer.Run( input );
    // ...
    // update learning rate and radius continuously,
    // so networks may come steady state
}
Constructor & Destructor Documentation
SOMLearning() [1/6]
AForge.Neuro.Learning.SOMLearning.SOMLearning (DistanceNetwork network) inline
Initializes a new instance of the SOMLearning class
Parameters
network Neural network to train
This constructor supposes that a square network will be passed for training - it should be possible to get square root of network's neurons amount.
References AForge.Neuro.Learning.SOMLearning.height, AForge.Neuro.Learning.SOMLearning.network, and AForge.Neuro.Learning.SOMLearning.width.
SOMLearning() [2/6]
AForge.Neuro.Learning.SOMLearning.SOMLearning (DistanceNetwork network, int width, int height) inline
Initializes a new instance of the SOMLearning class
Parameters
network Neural network to train
width Neural network's width
height Neural network's height
The constructor allows to pass network of arbitrary rectangular shape. The amount of neurons in the network should be equal to width * height.
References AForge.Neuro.Learning.SOMLearning.height, AForge.Neuro.Learning.SOMLearning.network, and AForge.Neuro.Learning.SOMLearning.width.
SOMLearning() [3/6]
AForge.Neuro.Learning.SOMLearning.SOMLearning (DistanceNetwork network) inline
Initializes a new instance of the SOMLearning class
Parameters
network Neural network to train
This constructor supposes that a square network will be passed for training - it should be possible to get square root of network's neurons amount.
References AForge.Neuro.Learning.SOMLearning.height, AForge.Neuro.Learning.SOMLearning.network, and AForge.Neuro.Learning.SOMLearning.width.
SOMLearning() [4/6]
AForge.Neuro.Learning.SOMLearning.SOMLearning (DistanceNetwork network, int width, int height) inline
Initializes a new instance of the SOMLearning class
Parameters
network Neural network to train
width Neural network's width
height Neural network's height
The constructor allows to pass network of arbitrary rectangular shape. The amount of neurons in the network should be equal to width * height.
References AForge.Neuro.Learning.SOMLearning.height, AForge.Neuro.Learning.SOMLearning.network, and AForge.Neuro.Learning.SOMLearning.width.
SOMLearning() [5/6]
AForge.Neuro.Learning.SOMLearning.SOMLearning (DistanceNetwork network) inline
Initializes a new instance of the SOMLearning class.
Parameters
network Neural network to train.
This constructor supposes that a square network will be passed for training - it should be possible to get square root of network's neurons amount.
Exceptions
ArgumentException Invalid network size - square network is expected.
References AForge.Neuro.Network.Layers, AForge.Neuro.Learning.SOMLearning.network, AForge.Neuro.Layer.Neurons, and AForge.Neuro.Learning.SOMLearning.width.
SOMLearning() [6/6]
AForge.Neuro.Learning.SOMLearning.SOMLearning (DistanceNetwork network, int width, int height) inline
Initializes a new instance of the SOMLearning class.
Parameters
network Neural network to train.
width Neural network's width.
height Neural network's height.
The constructor allows to pass network of arbitrary rectangular shape. The amount of neurons in the network should be equal to width * height.
Exceptions
ArgumentException Invalid network size - network size does not correspond to specified width and height.
References AForge.Neuro.Learning.SOMLearning.height, AForge.Neuro.Network.Layers, AForge.Neuro.Learning.SOMLearning.network, AForge.Neuro.Layer.Neurons, and AForge.Neuro.Learning.SOMLearning.width.
Member Function Documentation
Run() [1/3]
double AForge.Neuro.Learning.SOMLearning.Run (double[] input) inline
Runs learning iteration
Parameters
input input vector
Returns
Returns learning error - summary absolute difference between updated weights and according inputs. The difference is measured according to the neurons distance to the winner neuron.
Implements AForge.Neuro.Learning.IUnsupervisedLearning.
References AForge.Neuro.Network.Compute(), AForge.Neuro.DistanceNetwork.GetWinner(), AForge.Neuro.Neuron.InputsCount, AForge.Neuro.Learning.SOMLearning.learningRadius, AForge.Neuro.Learning.SOMLearning.learningRate, AForge.Neuro.Learning.SOMLearning.network, AForge.Neuro.Layer.NeuronsCount, AForge.Neuro.Learning.SOMLearning.squaredRadius2, and AForge.Neuro.Learning.SOMLearning.width.
Referenced by AForge.Neuro.Learning.SOMLearning.RunEpoch(), and Color.MainForm.SearchSolution().
RunEpoch() [1/3]
double AForge.Neuro.Learning.SOMLearning.RunEpoch (double input[][]) inline
Runs learning epoch
Parameters
input array of input vectors
Returns
Returns summary learning error for the epoch. See Run method for details about learning error calculation.
Implements AForge.Neuro.Learning.IUnsupervisedLearning.
References AForge.Neuro.Learning.SOMLearning.Run().
Referenced by SOMOrganizing.MainForm.SearchSolution().
Run() [2/3]
double AForge.Neuro.Learning.SOMLearning.Run (double[] input) inline
Runs learning iteration
Parameters
input input vector
Returns
Returns learning error - summary absolute difference between updated weights and according inputs. The difference is measured according to the neurons distance to the winner neuron.
Implements AForge.Neuro.Learning.IUnsupervisedLearning.
References AForge.Neuro.Network.Compute(), AForge.Neuro.DistanceNetwork.GetWinner(), AForge.Neuro.Neuron.InputsCount, AForge.Neuro.Learning.SOMLearning.learningRadius, AForge.Neuro.Learning.SOMLearning.learningRate, AForge.Neuro.Learning.SOMLearning.network, AForge.Neuro.Layer.NeuronsCount, AForge.Neuro.Learning.SOMLearning.squaredRadius2, and AForge.Neuro.Learning.SOMLearning.width.
RunEpoch() [2/3]
double AForge.Neuro.Learning.SOMLearning.RunEpoch (double input[][]) inline
Runs learning epoch
Parameters
input array of input vectors
Returns
Returns summary learning error for the epoch. See Run method for details about learning error calculation.
Implements AForge.Neuro.Learning.IUnsupervisedLearning.
References AForge.Neuro.Learning.SOMLearning.Run().
Run() [3/3]
double AForge.Neuro.Learning.SOMLearning.Run (double[] input) inline
Runs learning iteration.
Parameters
input Input vector.
Returns
Returns learning error - summary absolute difference between neurons' weights and appropriate inputs. The difference is measured according to the neurons distance to the winner neuron.
The method runs one learning iterations - finds winner neuron (the neuron which has weights with values closest to the specified input vector) and updates its weight (as well as weights of neighbor neurons) in the way to decrease difference with the specified input vector.
Implements AForge.Neuro.Learning.IUnsupervisedLearning.
References AForge.Neuro.Network.Compute(), AForge.Neuro.DistanceNetwork.GetWinner(), AForge.Neuro.Network.Layers, AForge.Neuro.Learning.SOMLearning.learningRadius, AForge.Neuro.Learning.SOMLearning.learningRate, AForge.Neuro.Learning.SOMLearning.network, AForge.Neuro.Layer.Neurons, AForge.Neuro.Learning.SOMLearning.squaredRadius2, AForge.Neuro.Neuron.Weights, and AForge.Neuro.Learning.SOMLearning.width.
RunEpoch() [3/3]
double AForge.Neuro.Learning.SOMLearning.RunEpoch (double input[][]) inline
Runs learning epoch.
Parameters
input Array of input vectors.
Returns
Returns summary learning error for the epoch. See Run method for details about learning error calculation.
The method runs one learning epoch, by calling Run method for each vector provided in the input array.
Implements AForge.Neuro.Learning.IUnsupervisedLearning.
References AForge.Neuro.Learning.SOMLearning.Run().
Member Data Documentation
network
DistanceNetwork AForge.Neuro.Learning.SOMLearning.network private
Referenced by AForge.Neuro.Learning.SOMLearning.Run(), and AForge.Neuro.Learning.SOMLearning.SOMLearning().
width
int AForge.Neuro.Learning.SOMLearning.width private
Referenced by AForge.Neuro.Learning.SOMLearning.Run(), and AForge.Neuro.Learning.SOMLearning.SOMLearning().
height
int AForge.Neuro.Learning.SOMLearning.height private
Referenced by AForge.Neuro.Learning.SOMLearning.SOMLearning().
learningRate
double AForge.Neuro.Learning.SOMLearning.learningRate = 0.1 private
Referenced by AForge.Neuro.Learning.SOMLearning.Run().
learningRadius
double AForge.Neuro.Learning.SOMLearning.learningRadius = 7 private
Referenced by AForge.Neuro.Learning.SOMLearning.Run().
squaredRadius2
double AForge.Neuro.Learning.SOMLearning.squaredRadius2 = 2 * 7 * 7 private
Referenced by AForge.Neuro.Learning.SOMLearning.Run().
Property Documentation
LearningRate
double AForge.Neuro.Learning.SOMLearning.LearningRate get set
Learning rate
Learning rate, [0, 1].
Determines speed of learning. Value range is [0, 1]. Default value equals to 0.1.
Determines speed of learning.
Default value equals to 0.1.
Referenced by Color.MainForm.SearchSolution(), and SOMOrganizing.MainForm.SearchSolution().
LearningRadius
double AForge.Neuro.Learning.SOMLearning.LearningRadius get set
Learning radius
Learning radius.
Determines the amount of neurons to be updated around winner neuron. Neurons, which are in the circle of specified radius, are updated during the learning procedure. Neurons, which are closer to the winner neuron, get more update.
Default value equals to 7.
Determines the amount of neurons to be updated around winner neuron. Neurons, which are in the circle of specified radius, are updated during the learning procedure. Neurons, which are closer to the winner neuron, get more update.
<note>In the case if learning rate is set to 0, then only winner neuron's weights are updated.</note>
Default value equals to 7.
Referenced by Color.MainForm.SearchSolution(), and SOMOrganizing.MainForm.SearchSolution().
The documentation for this class was generated from the following file:
shelldev/lib/external/neuralnetworks/neuro_src/Sources/Backup/Neuro/Learning/SOMLearning.cs