Doc: IGLib EXTENDED: alglib.ibetaf Class Reference
alglib.ibetaf Class Reference
Static Public Member Functions
static double incompletebeta (double a, double b, double x)
static double invincompletebeta (double a, double b, double y)
static double incompletebeta (double a, double b, double x)
static double invincompletebeta (double a, double b, double y)
Static Private Member Functions
static double incompletebetafe (double a, double b, double x, double big, double biginv)
static double incompletebetafe2 (double a, double b, double x, double big, double biginv)
static double incompletebetaps (double a, double b, double x, double maxgam)
static double incompletebetafe (double a, double b, double x, double big, double biginv)
static double incompletebetafe2 (double a, double b, double x, double big, double biginv)
static double incompletebetaps (double a, double b, double x, double maxgam)
Member Function Documentation
incompletebeta() [1/2]
static double alglib.ibetaf.incompletebeta (double a, double b, double x) inline static
References alglib.ap.assert(), alglib.gammafunc.gammafunction(), alglib.ibetaf.incompletebetafe(), alglib.ibetaf.incompletebetafe2(), alglib.ibetaf.incompletebetaps(), alglib.gammafunc.lngamma(), alglib.math.machineepsilon, alglib.math.maxrealnumber, and alglib.math.minrealnumber.
Referenced by alglib.binomialdistr.binomialcdistribution(), alglib.binomialdistr.binomialdistribution(), alglib.fdistr.fcdistribution(), alglib.fdistr.fdistribution(), alglib.incompletebeta(), alglib.binomialdistr.invbinomialdistribution(), alglib.fdistr.invfdistribution(), alglib.ibetaf.invincompletebeta(), alglib.studenttdistr.studenttdistribution(), and alglib.studentttests.unequalvariancettest().
invincompletebeta() [1/2]
static double alglib.ibetaf.invincompletebeta (double a, double b, double y) inline static
References alglib.ap.assert(), alglib.ibetaf.incompletebeta(), alglib.normaldistr.invnormaldistribution(), alglib.gammafunc.lngamma(), alglib.math.machineepsilon, alglib.math.maxrealnumber, and alglib.math.minrealnumber.
Referenced by alglib.binomialdistr.invbinomialdistribution(), alglib.fdistr.invfdistribution(), alglib.invincompletebeta(), and alglib.studenttdistr.invstudenttdistribution().
incompletebetafe() [1/2]
static double alglib.ibetaf.incompletebetafe (double a, double b, double x, double big, double biginv) inline static private
References alglib.math.machineepsilon.
Referenced by alglib.ibetaf.incompletebeta().
incompletebetafe2() [1/2]
static double alglib.ibetaf.incompletebetafe2 (double a, double b, double x, double big, double biginv) inline static private
References alglib.math.machineepsilon.
Referenced by alglib.ibetaf.incompletebeta().
incompletebetaps() [1/2]
static double alglib.ibetaf.incompletebetaps (double a, double b, double x, double maxgam) inline static private
References alglib.gammafunc.gammafunction(), alglib.gammafunc.lngamma(), alglib.math.machineepsilon, alglib.math.maxrealnumber, and alglib.math.minrealnumber.
Referenced by alglib.ibetaf.incompletebeta().
incompletebeta() [2/2]
static double alglib.ibetaf.incompletebeta (double a, double b, double x) inline static
References alglib.ap.assert(), alglib.gammafunc.gammafunction(), alglib.ibetaf.incompletebetafe(), alglib.ibetaf.incompletebetafe2(), alglib.ibetaf.incompletebetaps(), alglib.gammafunc.lngamma(), alglib.math.machineepsilon, alglib.math.maxrealnumber, and alglib.math.minrealnumber.
invincompletebeta() [2/2]
static double alglib.ibetaf.invincompletebeta (double a, double b, double y) inline static
References alglib.ap.assert(), alglib.ibetaf.incompletebeta(), alglib.normaldistr.invnormaldistribution(), alglib.gammafunc.lngamma(), alglib.math.machineepsilon, alglib.math.maxrealnumber, and alglib.math.minrealnumber.
incompletebetafe() [2/2]
static double alglib.ibetaf.incompletebetafe (double a, double b, double x, double big, double biginv) inline static private
References alglib.math.machineepsilon.
incompletebetafe2() [2/2]
static double alglib.ibetaf.incompletebetafe2 (double a, double b, double x, double big, double biginv) inline static private
References alglib.math.machineepsilon.
incompletebetaps() [2/2]
static double alglib.ibetaf.incompletebetaps (double a, double b, double x, double maxgam) inline static private
References alglib.gammafunc.gammafunction(), alglib.gammafunc.lngamma(), alglib.math.machineepsilon, alglib.math.maxrealnumber, and alglib.math.minrealnumber.
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/specialfunctions.cs