Doc: IGLib EXTENDED: AForge.Math.Geometry.Tests.LineSegmentTest Class Reference
AForge.Math.Geometry.Tests.LineSegmentTest Class Reference
Public Types
enum IntersectionType {
IntersectionType.None, IntersectionType.LinesOnly, IntersectionType.SegmentA, IntersectionType.SegmentB,
IntersectionType.AllFour
}
Public Member Functions
void LengthTest (float sx, float sy, float ex, float ey, float expectedResult)
void DistanceToPointTest (float x, float y, float x1, float y1, float x2, float y2, float expectedDistance)
void IntersectionPointTest (float ax1, float ay1, float ax2, float ay2, float bx1, float by1, float bx2, float by2, float ix, float iy, IntersectionType type)
void ParallelIntersectionPointTest (float ax1, float ay1, float ax2, float ay2, float bx1, float by1, float bx2, float by2)
void CollinearIntersectionPointTest (float ax1, float ay1, float ax2, float ay2, float bx1, float by1, float bx2, float by2)
void CommonIntersectionPointTest (float ax1, float ay1, float ax2, float ay2, float bx1, float by1, float bx2, float by2, float ix, float iy)
void OverlappingSegmentIntersectionPointTest (float ax1, float ay1, float ax2, float ay2, float bx1, float by1, float bx2, float by2)
Member Enumeration Documentation
IntersectionType
enum AForge.Math.Geometry.Tests.LineSegmentTest.IntersectionType strong
Enumerator
None
LinesOnly
SegmentA
SegmentB
AllFour
Member Function Documentation
LengthTest()
void AForge.Math.Geometry.Tests.LineSegmentTest.LengthTest (float sx, float sy, float ex, float ey, float expectedResult) inline
References AForge.Math.Geometry.LineSegment.Length.
DistanceToPointTest()
void AForge.Math.Geometry.Tests.LineSegmentTest.DistanceToPointTest (float x, float y, float x1, float y1, float x2, float y2, float expectedDistance) inline
References AForge.Math.Geometry.LineSegment.DistanceToPoint().
IntersectionPointTest()
void AForge.Math.Geometry.Tests.LineSegmentTest.IntersectionPointTest (float ax1, float ay1, float ax2, float ay2, float bx1, float by1, float bx2, float by2, float ix, float iy, IntersectionType type) inline
References AForge.Math.Geometry.LineSegment.GetIntersectionWith().
ParallelIntersectionPointTest()
void AForge.Math.Geometry.Tests.LineSegmentTest.ParallelIntersectionPointTest (float ax1, float ay1, float ax2, float ay2, float bx1, float by1, float bx2, float by2) inline
References AForge.Math.Geometry.Line.GetIntersectionWith().
CollinearIntersectionPointTest()
void AForge.Math.Geometry.Tests.LineSegmentTest.CollinearIntersectionPointTest (float ax1, float ay1, float ax2, float ay2, float bx1, float by1, float bx2, float by2) inline
References AForge.Math.Geometry.LineSegment.GetIntersectionWith().
CommonIntersectionPointTest()
void AForge.Math.Geometry.Tests.LineSegmentTest.CommonIntersectionPointTest (float ax1, float ay1, float ax2, float ay2, float bx1, float by1, float bx2, float by2, float ix, float iy) inline
References AForge.Math.Geometry.LineSegment.GetIntersectionWith().
OverlappingSegmentIntersectionPointTest()
void AForge.Math.Geometry.Tests.LineSegmentTest.OverlappingSegmentIntersectionPointTest (float ax1, float ay1, float ax2, float ay2, float bx1, float by1, float bx2, float by2) inline
References AForge.Math.Geometry.LineSegment.GetIntersectionWith().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Unit Tests/AForge.Math.Tests/Geometry/LineSegmentTest.cs