Doc: IGLib EXTENDED: IG.Test.TestVectorOperations Class Reference
IG.Test.TestVectorOperations Class Reference
Unit tests for vector operations.
Public Member Functions
void AccessOutOfRangeVector1 ()
void AccessOutOfRangeVector2 ()
void OrthogonalizationGramSchmidtRobustD7 ()
Tests robust Gramm-Schmidt orthogonalization. The number of original vectors is smaller than the number of requested resulting vectors.
void OrthogonalizationGramSchmidtNormalizedUnmodifiedD5 ()
Gramm-Schmidt orthogonalization, normalized vectors, unmodified (less stable) procedure. Tested on 5 dimensional randomly generated vectors.
void OrthogonalizationGramSchmidtNormalizedD5 ()
Gramm-Schmidt orthogonalization, normalized vectors, modified (more stable) procedure. Tested on 5 dimensional randomly generated vectors.
void OrthogonalizationGramSchmidtUnmodifiedD5 ()
Gramm-Schmidt orthogonalization, vectors are not normalized, unmodified (less stable) procedure. Tested on 5 dimensional randomly generated vectors.
void OrthogonalizationGramSchmidtD5 ()
Gramm-Schmidt orthogonalization, vectors are not normalized, modified (more stable) procedure. Tested on 5 dimensional randomly generated vectors.
void OrthogonalizationGramSchmidtNonRobustNormalizedUnmodifiedD5 ()
Gramm-Schmidt orthogonalization, normalized vectors, unmodified (less stable) procedure. Tested on 5 dimensional randomly generated vectors.
void OrthogonalizationGramSchmidtNonRobustNormalizedD5 ()
Gramm-Schmidt orthogonalization, normalized vectors, modified (more stable) procedure. Tested on 5 dimensional randomly generated vectors. vector is less than the number of these vectors.
void OrthogonalizationGramSchmidtNonRobustUnmodifiedD5 ()
Gramm-Schmidt orthogonalization, vectors are not normalized, unmodified (less stable) procedure. Tested on 5 dimensional randomly generated vectors. vector is less than the number of these vectors.
void OrthogonalizationGramSchmidtNonRobustD5 ()
Gramm-Schmidt orthogonalization, vectors are not normalized, modified (more stable) procedure. Tested on 5 dimensional randomly generated vectors. vector is less than the number of these vectors.
void AccessOutOfRangeVector1 ()
void AccessOutOfRangeVector2 ()
void OrthogonalizationGramSchmidtRobustD7 ()
Tests robust Gramm-Schmidt orthogonalization. The number of original vectors is smaller than the number of requested resulting vectors.
void OrthogonalizationGramSchmidtNormalizedUnmodifiedD5 ()
Gramm-Schmidt orthogonalization, normalized vectors, unmodified (less stable) procedure. Tested on 5 dimensional randomly generated vectors.
void OrthogonalizationGramSchmidtNormalizedD5 ()
Gramm-Schmidt orthogonalization, normalized vectors, modified (more stable) procedure. Tested on 5 dimensional randomly generated vectors.
void OrthogonalizationGramSchmidtUnmodifiedD5 ()
Gramm-Schmidt orthogonalization, vectors are not normalized, unmodified (less stable) procedure. Tested on 5 dimensional randomly generated vectors.
void OrthogonalizationGramSchmidtD5 ()
Gramm-Schmidt orthogonalization, vectors are not normalized, modified (more stable) procedure. Tested on 5 dimensional randomly generated vectors.
void OrthogonalizationGramSchmidtNonRobustNormalizedUnmodifiedD5 ()
Gramm-Schmidt orthogonalization, normalized vectors, unmodified (less stable) procedure. Tested on 5 dimensional randomly generated vectors.
void OrthogonalizationGramSchmidtNonRobustNormalizedD5 ()
Gramm-Schmidt orthogonalization, normalized vectors, modified (more stable) procedure. Tested on 5 dimensional randomly generated vectors. vector is less than the number of these vectors.
void OrthogonalizationGramSchmidtNonRobustUnmodifiedD5 ()
Gramm-Schmidt orthogonalization, vectors are not normalized, unmodified (less stable) procedure. Tested on 5 dimensional randomly generated vectors. vector is less than the number of these vectors.
void OrthogonalizationGramSchmidtNonRobustD5 ()
Gramm-Schmidt orthogonalization, vectors are not normalized, modified (more stable) procedure. Tested on 5 dimensional randomly generated vectors. vector is less than the number of these vectors.
Static Public Member Functions
static bool TestGramSchmidtOrthogonalization (int dim, out double maxErrorMixed, out double maxErrorDiagonal, int numRepetitions=1, double tol=1e-8, int outputLevel=0, IRandomGenerator randomGenerator=null, bool normalize=false, bool modifiedGrammSchmidt=true, bool nonRobust=false)
Performs a test of Gramm-Schmidt orthogonalization on a set of random vectors.
static bool TestGramSchmidtOrthogonalization (int dim, out double maxErrorMixed, out double maxErrorDiagonal, int numRepetitions=1, double tol=1e-8, int outputLevel=0, IRandomGenerator randomGenerator=null, bool normalize=false, bool modifiedGrammSchmidt=true, bool nonRobust=false)
Performs a test of Gramm-Schmidt orthogonalization on a set of random vectors.
Detailed Description
Unit tests for vector operations.
$A Igor May09 Dec14;
Member Function Documentation
AccessOutOfRangeVector1() [1/2]
void IG.Test.TestVectorOperations.AccessOutOfRangeVector1 () inline
AccessOutOfRangeVector2() [1/2]
void IG.Test.TestVectorOperations.AccessOutOfRangeVector2 () inline
OrthogonalizationGramSchmidtRobustD7() [1/2]
void IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtRobustD7 () inline
Tests robust Gramm-Schmidt orthogonalization. The number of original vectors is smaller than the number of requested resulting vectors.
References IG.Num.VectorBase.Add(), IG.Num.VectorBase.Copy(), IG.Num.IVector< T >.GetCopy(), IG.Num.VectorBase.Multiply(), IG.Num.VectorBase.Norm2Plain(), IG.Num.VectorBase.OrthogonalizeGramSchmidt(), IG.Num.VectorBase.ScalarProduct(), and IG.Num.VectorBase.SetRandom().
TestGramSchmidtOrthogonalization() [1/2]
static bool IG.Test.TestVectorOperations.TestGramSchmidtOrthogonalization (int dim, out double maxErrorMixed, out double maxErrorDiagonal, int numRepetitions = 1, double tol = 1e-8, int outputLevel = 0, IRandomGenerator randomGenerator = null, bool normalize = false, bool modifiedGrammSchmidt = true, bool nonRobust = false) inline static
Performs a test of Gramm-Schmidt orthogonalization on a set of random vectors.
Parameters
dim dimension of vectors to be orthogonalized.
maxErrorDiagonal Maximal absolute inner product of two resulting vectors that are not the same.
maxErrorMixed Maximal absolute value of difference between 1 and dot product of an resulting vector by itself.
numRepetitions Nomber of repetitions (how many times the procedure is repeated).
tol Tolerance for zero length of resulting vectors.
outputLevel Level of output.
randomGenerator Random generator used.
normalize Whether resulting vectors are normalized.
modifiedGrammSchmidt Whether a modified gramm-schmidt algorithm is used.
Returns
True if the test has passed, false otherwise.
References IG.Num.VectorBase.Add(), IG.Lib.StopWatch1.CpuTime, IG.Num.RandomGenerator.Global, IG.Num.VectorBase.OrthogonalizeGramSchmidt(), IG.Num.VectorBase.OrthogonalizeGramSchmidtNonRobust(), IG.Num.Vector.Random(), IG.Num.VectorBase.ScalarProduct(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.StopWatch1.Time, and IG.Num.VectorBase.ToStringMath().
Referenced by IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtD5(), IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNonRobustD5(), IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNonRobustNormalizedD5(), IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNonRobustNormalizedUnmodifiedD5(), IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNonRobustUnmodifiedD5(), IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNormalizedD5(), IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNormalizedUnmodifiedD5(), and IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtUnmodifiedD5().
OrthogonalizationGramSchmidtNormalizedUnmodifiedD5() [1/2]
void IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNormalizedUnmodifiedD5 () inline
Gramm-Schmidt orthogonalization, normalized vectors, unmodified (less stable) procedure. Tested on 5 dimensional randomly generated vectors.
References IG.Test.TestVectorOperations.TestGramSchmidtOrthogonalization().
OrthogonalizationGramSchmidtNormalizedD5() [1/2]
void IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNormalizedD5 () inline
Gramm-Schmidt orthogonalization, normalized vectors, modified (more stable) procedure. Tested on 5 dimensional randomly generated vectors.
References IG.Test.TestVectorOperations.TestGramSchmidtOrthogonalization().
OrthogonalizationGramSchmidtUnmodifiedD5() [1/2]
void IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtUnmodifiedD5 () inline
Gramm-Schmidt orthogonalization, vectors are not normalized, unmodified (less stable) procedure. Tested on 5 dimensional randomly generated vectors.
References IG.Test.TestVectorOperations.TestGramSchmidtOrthogonalization().
OrthogonalizationGramSchmidtD5() [1/2]
void IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtD5 () inline
Gramm-Schmidt orthogonalization, vectors are not normalized, modified (more stable) procedure. Tested on 5 dimensional randomly generated vectors.
References IG.Test.TestVectorOperations.TestGramSchmidtOrthogonalization().
OrthogonalizationGramSchmidtNonRobustNormalizedUnmodifiedD5() [1/2]
void IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNonRobustNormalizedUnmodifiedD5 () inline
Gramm-Schmidt orthogonalization, normalized vectors, unmodified (less stable) procedure. Tested on 5 dimensional randomly generated vectors.
Nonrobust method is used, which fails if the dimension of space spanned by the provided original vector is less than the number of these vectors.
References IG.Test.TestVectorOperations.TestGramSchmidtOrthogonalization().
OrthogonalizationGramSchmidtNonRobustNormalizedD5() [1/2]
void IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNonRobustNormalizedD5 () inline
Gramm-Schmidt orthogonalization, normalized vectors, modified (more stable) procedure. Tested on 5 dimensional randomly generated vectors. vector is less than the number of these vectors.
References IG.Test.TestVectorOperations.TestGramSchmidtOrthogonalization().
OrthogonalizationGramSchmidtNonRobustUnmodifiedD5() [1/2]
void IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNonRobustUnmodifiedD5 () inline
Gramm-Schmidt orthogonalization, vectors are not normalized, unmodified (less stable) procedure. Tested on 5 dimensional randomly generated vectors. vector is less than the number of these vectors.
References IG.Test.TestVectorOperations.TestGramSchmidtOrthogonalization().
OrthogonalizationGramSchmidtNonRobustD5() [1/2]
void IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNonRobustD5 () inline
Gramm-Schmidt orthogonalization, vectors are not normalized, modified (more stable) procedure. Tested on 5 dimensional randomly generated vectors. vector is less than the number of these vectors.
References IG.Test.TestVectorOperations.TestGramSchmidtOrthogonalization().
AccessOutOfRangeVector1() [2/2]
void IG.Test.TestVectorOperations.AccessOutOfRangeVector1 () inline
References NUnit.Framework.Assert.Throws().
AccessOutOfRangeVector2() [2/2]
void IG.Test.TestVectorOperations.AccessOutOfRangeVector2 () inline
References NUnit.Framework.Assert.Throws().
OrthogonalizationGramSchmidtRobustD7() [2/2]
void IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtRobustD7 () inline
Tests robust Gramm-Schmidt orthogonalization. The number of original vectors is smaller than the number of requested resulting vectors.
References IG.Num.VectorBase.Add(), NUnit.Framework.Assert.AreEqual(), IG.Num.VectorBase.Copy(), IG.Num.IVector< T >.GetCopy(), NUnit.Framework.Assert.IsTrue(), IG.Num.VectorBase.Multiply(), IG.Num.VectorBase.Norm2Plain(), IG.Num.VectorBase.OrthogonalizeGramSchmidt(), IG.Num.VectorBase.ScalarProduct(), and IG.Num.VectorBase.SetRandom().
TestGramSchmidtOrthogonalization() [2/2]
static bool IG.Test.TestVectorOperations.TestGramSchmidtOrthogonalization (int dim, out double maxErrorMixed, out double maxErrorDiagonal, int numRepetitions = 1, double tol = 1e-8, int outputLevel = 0, IRandomGenerator randomGenerator = null, bool normalize = false, bool modifiedGrammSchmidt = true, bool nonRobust = false) inline static
Performs a test of Gramm-Schmidt orthogonalization on a set of random vectors.
Parameters
dim dimension of vectors to be orthogonalized.
maxErrorDiagonal Maximal absolute inner product of two resulting vectors that are not the same.
maxErrorMixed Maximal absolute value of difference between 1 and dot product of an resulting vector by itself.
numRepetitions Nomber of repetitions (how many times the procedure is repeated).
tol Tolerance for zero length of resulting vectors.
outputLevel Level of output.
randomGenerator Random generator used.
normalize Whether resulting vectors are normalized.
modifiedGrammSchmidt Whether a modified gramm-schmidt algorithm is used.
Returns
True if the test has passed, false otherwise.
References IG.Num.VectorBase.Add(), IG.Lib.StopWatch1.CpuTime, IG.Num.RandomGenerator.Global, IG.Num.VectorBase.OrthogonalizeGramSchmidt(), IG.Num.VectorBase.OrthogonalizeGramSchmidtNonRobust(), IG.Num.Vector.Random(), IG.Num.VectorBase.ScalarProduct(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.StopWatch1.Time, and IG.Num.VectorBase.ToStringMath().
OrthogonalizationGramSchmidtNormalizedUnmodifiedD5() [2/2]
void IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNormalizedUnmodifiedD5 () inline
Gramm-Schmidt orthogonalization, normalized vectors, unmodified (less stable) procedure. Tested on 5 dimensional randomly generated vectors.
References NUnit.Framework.Assert.IsTrue(), and IG.Test.TestVectorOperations.TestGramSchmidtOrthogonalization().
OrthogonalizationGramSchmidtNormalizedD5() [2/2]
void IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNormalizedD5 () inline
Gramm-Schmidt orthogonalization, normalized vectors, modified (more stable) procedure. Tested on 5 dimensional randomly generated vectors.
References NUnit.Framework.Assert.IsTrue(), and IG.Test.TestVectorOperations.TestGramSchmidtOrthogonalization().
OrthogonalizationGramSchmidtUnmodifiedD5() [2/2]
void IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtUnmodifiedD5 () inline
Gramm-Schmidt orthogonalization, vectors are not normalized, unmodified (less stable) procedure. Tested on 5 dimensional randomly generated vectors.
References NUnit.Framework.Assert.IsTrue(), and IG.Test.TestVectorOperations.TestGramSchmidtOrthogonalization().
OrthogonalizationGramSchmidtD5() [2/2]
void IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtD5 () inline
Gramm-Schmidt orthogonalization, vectors are not normalized, modified (more stable) procedure. Tested on 5 dimensional randomly generated vectors.
References NUnit.Framework.Assert.IsTrue(), and IG.Test.TestVectorOperations.TestGramSchmidtOrthogonalization().
OrthogonalizationGramSchmidtNonRobustNormalizedUnmodifiedD5() [2/2]
void IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNonRobustNormalizedUnmodifiedD5 () inline
Gramm-Schmidt orthogonalization, normalized vectors, unmodified (less stable) procedure. Tested on 5 dimensional randomly generated vectors.
Nonrobust method is used, which fails if the dimension of space spanned by the provided original vector is less than the number of these vectors.
References NUnit.Framework.Assert.IsTrue(), and IG.Test.TestVectorOperations.TestGramSchmidtOrthogonalization().
OrthogonalizationGramSchmidtNonRobustNormalizedD5() [2/2]
void IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNonRobustNormalizedD5 () inline
Gramm-Schmidt orthogonalization, normalized vectors, modified (more stable) procedure. Tested on 5 dimensional randomly generated vectors. vector is less than the number of these vectors.
References NUnit.Framework.Assert.IsTrue(), and IG.Test.TestVectorOperations.TestGramSchmidtOrthogonalization().
OrthogonalizationGramSchmidtNonRobustUnmodifiedD5() [2/2]
void IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNonRobustUnmodifiedD5 () inline
Gramm-Schmidt orthogonalization, vectors are not normalized, unmodified (less stable) procedure. Tested on 5 dimensional randomly generated vectors. vector is less than the number of these vectors.
References NUnit.Framework.Assert.IsTrue(), and IG.Test.TestVectorOperations.TestGramSchmidtOrthogonalization().
OrthogonalizationGramSchmidtNonRobustD5() [2/2]
void IG.Test.TestVectorOperations.OrthogonalizationGramSchmidtNonRobustD5 () inline
Gramm-Schmidt orthogonalization, vectors are not normalized, modified (more stable) procedure. Tested on 5 dimensional randomly generated vectors. vector is less than the number of these vectors.
References NUnit.Framework.Assert.IsTrue(), and IG.Test.TestVectorOperations.TestGramSchmidtOrthogonalization().
The documentation for this class was generated from the following file:
unittests/MSTests/TestNumeric/TstVectorOperations.cs