Doc: IGLib EXTENDED: AForge.Math.Statistics Class Reference
AForge.Math.Statistics Class Reference
Set of statistics functions.
Static Public Member Functions
static double Mean (int[] values)
Calculate mean value.
static double StdDev (int[] values)
Calculate standard deviation.
static double StdDev (int[] values, double mean)
Calculate standard deviation.
static int Median (int[] values)
Calculate median value.
static IntRange GetRange (int[] values, double percent)
Get range around median containing specified percentage of values.
static double Entropy (int[] values)
Calculate entropy value.
static int Mode (int[] values)
Calculate mode value.
Detailed Description
Set of statistics functions.
The class represents collection of simple functions used in statistics.
Member Function Documentation
Mean()
static double AForge.Math.Statistics.Mean (int[] values) inline static
Calculate mean value.
Parameters
values Histogram array.
Returns
Returns mean value.
The input array is treated as histogram, i.e. its indexes are treated as values of stochastic function, but array values are treated as "probabilities" (total amount of hits).
Sample usage:
// create histogram array
int[] histogram = new int[] { 1, 1, 2, 3, 6, 8, 11, 12, 7, 3 };
// calculate mean value
double mean = Statistics.Mean(histogram);
// output it (5.759)
Console.WriteLine("mean = " + mean.ToString("F3"));
Referenced by AForge.Math.Statistics.StdDev(), and AForge.Math.Histogram.Update().
StdDev() [1/2]
static double AForge.Math.Statistics.StdDev (int[] values) inline static
Calculate standard deviation.
Parameters
values Histogram array.
Returns
Returns value of standard deviation.
The input array is treated as histogram, i.e. its indexes are treated as values of stochastic function, but array values are treated as "probabilities" (total amount of hits).
Sample usage:
// create histogram array
int[] histogram = new int[] { 1, 1, 2, 3, 6, 8, 11, 12, 7, 3 };
// calculate standard deviation value
double stdDev = Statistics.StdDev(histogram);
// output it (1.999)
Console.WriteLine("std.dev. = " + stdDev.ToString("F3"));
References AForge.Math.Statistics.Mean().
Referenced by AForge.Math.Histogram.Update().
StdDev() [2/2]
static double AForge.Math.Statistics.StdDev (int[] values, double mean) inline static
Calculate standard deviation.
Parameters
values Histogram array.
mean Mean value of the histogram.
Returns
Returns value of standard deviation.
The input array is treated as histogram, i.e. its indexes are treated as values of stochastic function, but array values are treated as "probabilities" (total amount of hits).
The method is an equevalent to the StdDev(int[]) method, but it relieas on the passed mean value, which is previously calculated using Mean method.
Median()
static int AForge.Math.Statistics.Median (int[] values) inline static
Calculate median value.
Parameters
values Histogram array.
Returns
Returns value of median.
The input array is treated as histogram, i.e. its indexes are treated as values of stochastic function, but array values are treated as "probabilities" (total amount of hits).
<note>The median value is calculated accumulating histogram's values starting from the left point until the sum reaches 50% of histogram's sum.</note>
Sample usage:
// create histogram array
int[] histogram = new int[] { 1, 1, 2, 3, 6, 8, 11, 12, 7, 3 };
// calculate median value
int median = Statistics.Median(histogram);
// output it (6)
Console.WriteLine("median = " + median);
Referenced by AForge.Math.Histogram.Update().
GetRange()
static IntRange AForge.Math.Statistics.GetRange (int[] values, double percent) inline static
Get range around median containing specified percentage of values.
Parameters
values Histogram array.
percent Values percentage around median.
Returns
Returns the range which containes specifies percentage of values.
The input array is treated as histogram, i.e. its indexes are treated as values of stochastic function, but array values are treated as "probabilities" (total amount of hits).
The method calculates range of stochastic variable, which summary probability comprises the specified percentage of histogram's hits.
Sample usage:
// create histogram array
int[] histogram = new int[] { 1, 1, 2, 3, 6, 8, 11, 12, 7, 3 };
// get 75% range around median
IntRange range = Statistics.GetRange(histogram, 0.75);
// output it ([4, 8])
Console.WriteLine("range = [" + range.Min + ", " + range.Max + "]");
Referenced by AForge.Math.Histogram.GetRange().
Entropy()
static double AForge.Math.Statistics.Entropy (int[] values) inline static
Calculate entropy value.
Parameters
values Histogram array.
Returns
Returns entropy value of the specified histagram array.
The input array is treated as histogram, i.e. its indexes are treated as values of stochastic function, but array values are treated as "probabilities" (total amount of hits).
Sample usage:
// create histogram array with 2 values of equal probabilities
int[] histogram1 = new int[2] { 3, 3 };
// calculate entropy
double entropy1 = Statistics.Entropy(histogram1);
// output it (1.000)
Console.WriteLine("entropy1 = " + entropy1.ToString("F3"));
// create histogram array with 4 values of equal probabilities
int[] histogram2 = new int[4] { 1, 1, 1, 1 };
// calculate entropy
double entropy2 = Statistics.Entropy(histogram2);
// output it (2.000)
Console.WriteLine("entropy2 = " + entropy2.ToString("F3"));
// create histogram array with 4 values of different probabilities
int[] histogram3 = new int[4] { 1, 2, 3, 4 };
// calculate entropy
double entropy3 = Statistics.Entropy(histogram3);
// output it (1.846)
Console.WriteLine("entropy3 = " + entropy3.ToString("F3"));
Mode()
static int AForge.Math.Statistics.Mode (int[] values) inline static
Calculate mode value.
Parameters
values Histogram array.
Returns
Returns mode value of the histogram array.
The input array is treated as histogram, i.e. its indexes are treated as values of stochastic function, but array values are treated as "probabilities" (total amount of hits).
<note>Returns the minimum mode value if the specified histogram is multimodal.</note>
Sample usage:
// create array
int[] values = new int[] { 1, 1, 2, 3, 6, 8, 11, 12, 7, 3 };
// calculate mode value
int mode = Statistics.Mode(values);
// output it (7)
Console.WriteLine("mode = " + mode);
Referenced by AForge.Math.Tests.StatisticsTest.ModeTest().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Math/Statistics.cs