Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAZQ3 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAZQ3 Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAZQ3 (DLASQ5 dlasq5, DLASQ6 dlasq6, DLAZQ4 dlazq4, DLAMCH dlamch)
DLAZQ3 ()
void Run (int I0, ref int N0, ref double[] Z, int offset_z, int PP, ref double DMIN, ref double SIGMA, ref double DESIG, ref double QMAX, ref int NFAIL, ref int ITER, ref int NDIV, bool IEEE, ref int TTYPE, ref double DMIN1, ref double DMIN2, ref double DN, ref double DN1, ref double DN2, ref double TAU)
Private Attributes
DLASQ5 _dlasq5
DLASQ6 _dlasq6
DLAZQ4 _dlazq4
DLAMCH _dlamch
Static Private Attributes
const double CBIAS = 1.50E0
const double ZERO = 0.0E0
const double QURTR = 0.250E0
const double HALF = 0.5E0
const double ONE = 1.0E0
const double TWO = 2.0E0
const double HUNDRD = 100.0E0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAZQ3 checks for deflation, computes a shift (TAU) and calls dqds. In case of failure it changes shifts, and tries again until output is positive.
/summary>
Constructor & Destructor Documentation
DLAZQ3() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.DLAZQ3 (DLASQ5 dlasq5, DLASQ6 dlasq6, DLAZQ4 dlazq4, DLAMCH dlamch) inline
DLAZQ3() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.DLAZQ3 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.Run (int I0, ref int N0, ref double[] Z, int offset_z, int PP, ref double DMIN, ref double SIGMA, ref double DESIG, ref double QMAX, ref int NFAIL, ref int ITER, ref int NDIV, bool IEEE, ref int TTYPE, ref double DMIN1, ref double DMIN2, ref double DN, ref double DN1, ref double DN2, ref double TAU) inline
Purpose
DLAZQ3 checks for deflation, computes a shift (TAU) and calls dqds. In case of failure it changes shifts, and tries again until output is positive.
/summary>
Parameters
I0 (input) INTEGER First index. /param>
Parameters
N0 (input) INTEGER Last index. /param>
Parameters
Z (input) DOUBLE PRECISION array, dimension (4*N) Z holds the qd array. /param>
Parameters
PP (input) INTEGER PP=0 for ping, PP=1 for pong. /param>
Parameters
DMIN (output) DOUBLE PRECISION Minimum value of d. /param>
Parameters
SIGMA (output) DOUBLE PRECISION Sum of shifts used in current segment. /param>
Parameters
DESIG (input/output) DOUBLE PRECISION Lower order part of SIGMA /param>
Parameters
QMAX (input) DOUBLE PRECISION Maximum value of q. /param>
Parameters
NFAIL (output) INTEGER Number of times shift was too big. /param>
Parameters
ITER (output) INTEGER Number of iterations. /param>
Parameters
NDIV (output) INTEGER Number of divisions. /param>
Parameters
IEEE (input) LOGICAL Flag for IEEE or non IEEE arithmetic (passed to DLASQ5). /param>
Parameters
TTYPE (input/output) INTEGER Shift type. TTYPE is passed as an argument in order to save its value between calls to DLAZQ3 /param>
Parameters
DMIN1 (input/output) REAL /param>
Parameters
DMIN2 (input/output) REAL /param>
Parameters
DN (input/output) REAL /param>
Parameters
DN1 (input/output) REAL /param>
Parameters
DN2 (input/output) REAL /param>
Parameters
TAU (input/output) REAL These are passed as arguments in order to save their values between calls to DLAZQ3 /param>
References DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.CBIAS, DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.HALF, DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.HUNDRD, DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.ONE, DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.QURTR, DotNumerics.LinearAlgebra.CSLapack.DLASQ5.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASQ6.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAZQ4.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.TWO, and DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASQ2.Run().
Member Data Documentation
_dlasq5
DLASQ5 DotNumerics.LinearAlgebra.CSLapack.DLAZQ3._dlasq5 private
_dlasq6
DLASQ6 DotNumerics.LinearAlgebra.CSLapack.DLAZQ3._dlasq6 private
_dlazq4
DLAZQ4 DotNumerics.LinearAlgebra.CSLapack.DLAZQ3._dlazq4 private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLAZQ3._dlamch private
CBIAS
const double DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.CBIAS = 1.50E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.Run().
QURTR
const double DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.QURTR = 0.250E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.Run().
HALF
const double DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.HALF = 0.5E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.Run().
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.TWO = 2.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.Run().
HUNDRD
const double DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.HUNDRD = 100.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlazq3.cs