Doc: IGLib EXTENDED: IG.Forms.FileViewerForm Class Reference
IG.Forms.FileViewerForm Class Reference
Public Member Functions
FileViewerForm ()
FileViewerForm ()
FileViewerForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
FileViewerControl imageViewerControl1
Constructor & Destructor Documentation
FileViewerForm() [1/3]
IG.Forms.FileViewerForm.FileViewerForm () inline
References IG.Forms.FileViewerForm.InitializeComponent().
FileViewerForm() [2/3]
IG.Forms.FileViewerForm.FileViewerForm () inline
References IG.Forms.FileViewerForm.InitializeComponent().
FileViewerForm() [3/3]
IG.Forms.FileViewerForm.FileViewerForm () inline
References IG.Forms.FileViewerForm.InitializeComponent().
Member Function Documentation
Dispose() [1/3]
override void IG.Forms.FileViewerForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.FileViewerForm.components.
InitializeComponent() [1/3]
void IG.Forms.FileViewerForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.FileViewerControl.CanViewFiles, IG.Forms.FileViewerControl.CanViewStreams, IG.Forms.FileViewerControl.CanViewUrls, IG.Forms.FileViewerForm.components, IG.Forms.FileViewerForm.imageViewerControl1, IG.Forms.FileViewerControl.IsBrowsable, IG.Forms.FileViewerControl.IsControlsVisible, IG.Forms.FileViewerControl.IsDragAndDrop, IG.Forms.FileViewerControl.IsShownImmediately, IG.Forms.FileViewerControl.ViewedFile, and IG.Forms.FileViewerControl.ViewedStream.
Referenced by IG.Forms.FileViewerForm.FileViewerForm().
Dispose() [2/3]
override void IG.Forms.FileViewerForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.FileViewerForm.components.
InitializeComponent() [2/3]
void IG.Forms.FileViewerForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.FileViewerControl.CanViewFiles, IG.Forms.FileViewerControl.CanViewStreams, IG.Forms.FileViewerControl.CanViewUrls, IG.Forms.FileViewerForm.components, IG.Forms.FileViewerForm.imageViewerControl1, IG.Forms.FileViewerControl.IsBrowsable, IG.Forms.FileViewerControl.IsControlsVisible, IG.Forms.FileViewerControl.IsDragAndDrop, IG.Forms.FileViewerControl.IsShownImmediately, IG.Forms.FileViewerControl.ViewedFile, and IG.Forms.FileViewerControl.ViewedStream.
Dispose() [3/3]
override void IG.Forms.FileViewerForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.FileViewerForm.components.
InitializeComponent() [3/3]
void IG.Forms.FileViewerForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.FileViewerControl.CanViewFiles, IG.Forms.FileViewerControl.CanViewStreams, IG.Forms.FileViewerControl.CanViewUrls, IG.Forms.FileViewerForm.components, IG.Forms.FileViewerForm.imageViewerControl1, IG.Forms.FileViewerControl.IsBrowsable, IG.Forms.FileViewerControl.IsControlsVisible, IG.Forms.FileViewerControl.IsDragAndDrop, IG.Forms.FileViewerControl.IsShownImmediately, IG.Forms.FileViewerControl.ViewedFile, and IG.Forms.FileViewerControl.ViewedStream.
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.FileViewerForm.components = null private
Required designer variable.
Referenced by IG.Forms.FileViewerForm.Dispose(), and IG.Forms.FileViewerForm.InitializeComponent().
imageViewerControl1
FileViewerControl IG.Forms.FileViewerForm.imageViewerControl1 private
Referenced by IG.Forms.FileViewerForm.InitializeComponent().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/Viewers/FileViewerForm.cs
iglib/igforms/Utilities/Viewers/FileViewerForm.Designer.cs