Doc: IGLib EXTENDED: NUnit.Engine.Services.Tests.ServiceDependencyTests Class Reference
NUnit.Engine.Services.Tests.ServiceDependencyTests Class Reference
Public Member Functions
void CreateServiceContext ()
void RecentFilesService_SettingsServiceError ()
void RecentFilesService_SettingsServiceMissing ()
void DefaultTestRunnerFactory_ProjectServiceError ()
void DefaultTestRunnerFactory_ProjectServiceMissing ()
void TestAgency_RuntimeFrameworkServiceError ()
void TestAgency_RuntimeFrameworkServiceMissing ()
Private Attributes
ServiceContext _services
Member Function Documentation
CreateServiceContext()
void NUnit.Engine.Services.Tests.ServiceDependencyTests.CreateServiceContext () inline
References NUnit.Engine.Services.Tests.ServiceDependencyTests._services.
RecentFilesService_SettingsServiceError()
void NUnit.Engine.Services.Tests.ServiceDependencyTests.RecentFilesService_SettingsServiceError () inline
References NUnit.Engine.Services.Tests.ServiceDependencyTests._services, NUnit.Engine.ServiceContext.Add(), NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
RecentFilesService_SettingsServiceMissing()
void NUnit.Engine.Services.Tests.ServiceDependencyTests.RecentFilesService_SettingsServiceMissing () inline
References NUnit.Engine.Services.Tests.ServiceDependencyTests._services, NUnit.Engine.ServiceContext.Add(), NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
DefaultTestRunnerFactory_ProjectServiceError()
void NUnit.Engine.Services.Tests.ServiceDependencyTests.DefaultTestRunnerFactory_ProjectServiceError () inline
References NUnit.Engine.Services.Tests.ServiceDependencyTests._services, NUnit.Engine.ServiceContext.Add(), NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
DefaultTestRunnerFactory_ProjectServiceMissing()
void NUnit.Engine.Services.Tests.ServiceDependencyTests.DefaultTestRunnerFactory_ProjectServiceMissing () inline
References NUnit.Engine.Services.Tests.ServiceDependencyTests._services, NUnit.Engine.ServiceContext.Add(), NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
TestAgency_RuntimeFrameworkServiceError()
void NUnit.Engine.Services.Tests.ServiceDependencyTests.TestAgency_RuntimeFrameworkServiceError () inline
References NUnit.Engine.Services.Tests.ServiceDependencyTests._services, NUnit.Engine.ServiceContext.Add(), NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
TestAgency_RuntimeFrameworkServiceMissing()
void NUnit.Engine.Services.Tests.ServiceDependencyTests.TestAgency_RuntimeFrameworkServiceMissing () inline
References NUnit.Engine.Services.Tests.ServiceDependencyTests._services, NUnit.Engine.ServiceContext.Add(), NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
Member Data Documentation
_services
ServiceContext NUnit.Engine.Services.Tests.ServiceDependencyTests._services private
Referenced by NUnit.Engine.Services.Tests.ServiceDependencyTests.CreateServiceContext(), NUnit.Engine.Services.Tests.ServiceDependencyTests.DefaultTestRunnerFactory_ProjectServiceError(), NUnit.Engine.Services.Tests.ServiceDependencyTests.DefaultTestRunnerFactory_ProjectServiceMissing(), NUnit.Engine.Services.Tests.ServiceDependencyTests.RecentFilesService_SettingsServiceError(), NUnit.Engine.Services.Tests.ServiceDependencyTests.RecentFilesService_SettingsServiceMissing(), NUnit.Engine.Services.Tests.ServiceDependencyTests.TestAgency_RuntimeFrameworkServiceError(), and NUnit.Engine.Services.Tests.ServiceDependencyTests.TestAgency_RuntimeFrameworkServiceMissing().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Services/ServiceDependencyTests.cs