Doc: IGLib EXTENDED: AForge.Imaging.Filters.BaseInPlaceFilter Class Reference
AForge.Imaging.Filters.BaseInPlaceFilter Class Reference abstract
Base class for filters, which may be applied directly to the source image.
Public Member Functions
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
Protected Member Functions
abstract unsafe void ProcessFilter (UnmanagedImage image)
Process the filter on the specified image.
Properties
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Member Functions
void CheckSourceFormat (PixelFormat pixelFormat)
Detailed Description
Base class for filters, which may be applied directly to the source image.
The abstract class is the base class for all filters, which can be applied to an image producing new image as a result of image processing or applied directly to the source image without changing its size and pixel format.
Member Function Documentation
Apply() [1/4]
Bitmap AForge.Imaging.Filters.BaseInPlaceFilter.Apply (Bitmap image) inline
Apply filter to an image.
Parameters
image Source image to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The method keeps the source image unchanged and returns the result of image processing filter as new image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.Filters.BaseInPlaceFilter.Apply(), and SVSTest.StereoViewForm.stereoThread().
Apply() [2/4]
Bitmap AForge.Imaging.Filters.BaseInPlaceFilter.Apply (BitmapData imageData) inline
Apply filter to an image.
Parameters
imageData Source image to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The filter accepts bitmap data as input and returns the result of image processing filter as new image. The source image data are kept unchanged.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.BaseInPlaceFilter.CheckSourceFormat(), AForge.SystemTools.CopyUnmanagedMemory(), AForge.Imaging.Image.CreateGrayscaleImage(), AForge.Imaging.Filters.BaseInPlaceFilter.ProcessFilter(), and AForge.Math.Geometry.Rectangle.
Apply() [3/4]
UnmanagedImage AForge.Imaging.Filters.BaseInPlaceFilter.Apply (UnmanagedImage image) inline
Apply filter to an image in unmanaged memory.
Parameters
image Source image in unmanaged memory to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The method keeps the source image unchanged and returns the result of image processing filter as new image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.BaseInPlaceFilter.Apply(), AForge.Imaging.Filters.BaseInPlaceFilter.CheckSourceFormat(), AForge.Imaging.UnmanagedImage.Create(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.PixelFormat, and AForge.Imaging.UnmanagedImage.Width.
Apply() [4/4]
void AForge.Imaging.Filters.BaseInPlaceFilter.Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage) inline
Apply filter to an image in unmanaged memory.
Parameters
sourceImage Source image in unmanaged memory to apply filter to.
destinationImage Destination image in unmanaged memory to put result into.
The method keeps the source image unchanged and puts result of image processing into destination image.
<note>The destination image must have the same width and height as source image. Also destination image must have pixel format, which is expected by particular filter (see FormatTranslations property for information about pixel format conversions).</note>
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
InvalidImagePropertiesException Incorrect destination pixel format.
InvalidImagePropertiesException Destination image has wrong width and/or height.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.BaseInPlaceFilter.CheckSourceFormat(), AForge.SystemTools.CopyUnmanagedMemory(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.Filters.BaseInPlaceFilter.ProcessFilter(), AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
ApplyInPlace() [1/3]
void AForge.Imaging.Filters.BaseInPlaceFilter.ApplyInPlace (Bitmap image) inline
Apply filter to an image.
Parameters
image Image to apply filter to.
The method applies the filter directly to the provided source image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlaceFilter.
References AForge.Imaging.Filters.BaseInPlaceFilter.CheckSourceFormat(), AForge.Imaging.Filters.BaseInPlaceFilter.ProcessFilter(), and AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.Filters.BottomHat.ProcessFilter(), and AForge.Imaging.Filters.TopHat.ProcessFilter().
ApplyInPlace() [2/3]
void AForge.Imaging.Filters.BaseInPlaceFilter.ApplyInPlace (BitmapData imageData) inline
Apply filter to an image.
Parameters
imageData Image data to apply filter to.
The method applies the filter directly to the provided source image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlaceFilter.
References AForge.Imaging.Filters.BaseInPlaceFilter.CheckSourceFormat(), and AForge.Imaging.Filters.BaseInPlaceFilter.ProcessFilter().
ApplyInPlace() [3/3]
void AForge.Imaging.Filters.BaseInPlaceFilter.ApplyInPlace (UnmanagedImage image) inline
Apply filter to an unmanaged image.
Parameters
image Unmanaged image to apply filter to.
The method applies the filter directly to the provided source unmanaged image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlaceFilter.
References AForge.Imaging.Filters.BaseInPlaceFilter.CheckSourceFormat(), AForge.Imaging.UnmanagedImage.PixelFormat, and AForge.Imaging.Filters.BaseInPlaceFilter.ProcessFilter().
ProcessFilter()
abstract unsafe void AForge.Imaging.Filters.BaseInPlaceFilter.ProcessFilter (UnmanagedImage image) protected pure virtual
Process the filter on the specified image.
Parameters
image Source image data.
Implemented in AForge.Imaging.Filters.BackwardQuadrilateralTransformation, AForge.Imaging.Filters.BlobsFiltering, AForge.Imaging.Filters.CanvasCrop, AForge.Imaging.Filters.CanvasMove, AForge.Imaging.Filters.CanvasFill, AForge.Imaging.Filters.FlatFieldCorrection, AForge.Imaging.Filters.BaseInPlaceFilter2, AForge.Imaging.Filters.FillHoles, AForge.Imaging.Filters.BradleyLocalThresholding, AForge.Imaging.Filters.CornersMarker, AForge.Imaging.Filters.BottomHat, and AForge.Imaging.Filters.TopHat.
Referenced by AForge.Imaging.Filters.BaseInPlaceFilter.Apply(), and AForge.Imaging.Filters.BaseInPlaceFilter.ApplyInPlace().
CheckSourceFormat()
void AForge.Imaging.Filters.BaseInPlaceFilter.CheckSourceFormat (PixelFormat pixelFormat) inline private
References AForge.Imaging.Filters.BaseInPlaceFilter.FormatTranslations.
Referenced by AForge.Imaging.Filters.BaseInPlaceFilter.Apply(), and AForge.Imaging.Filters.BaseInPlaceFilter.ApplyInPlace().
Property Documentation
FormatTranslations
abstract Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.BaseInPlaceFilter.FormatTranslations get
Format translations dictionary.
The dictionary defines, which pixel formats are supported for source images and which pixel format will be used for resulting image.
See IFilterInformation.FormatTranslations for more information.
Referenced by AForge.Imaging.Filters.BaseInPlaceFilter.CheckSourceFormat().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Base classes/BaseInPlaceFilter.cs