Doc: IGLib EXTENDED: NUnit.Framework.Attributes.RandomAttributeTests Class Reference
NUnit.Framework.Attributes.RandomAttributeTests Class Reference
Classes
class MethodNames
Public Member Functions
void CheckRandomResult (string methodName)
Member Function Documentation
CheckRandomResult()
void NUnit.Framework.Attributes.RandomAttributeTests.CheckRandomResult (string methodName) inline
References NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.COUNT, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.Fail(), NUnit.TestUtilities.TestBuilder.RunParameterizedMethodSuite(), NUnit.Framework.Interfaces.ResultState.Success, and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/RandomAttributeTests.cs