Doc: IGLib EXTENDED: AForge.Math.Geometry.Line Class Reference
AForge.Math.Geometry.Line Class Reference
The class encapsulates 2D line and provides some tool methods related to lines.
Public Member Functions
float GetAngleBetweenLines (Line secondLine)
Calculate minimum angle between this line and the specified line measured in [0, 90] degrees range.
Point? GetIntersectionWith (Line secondLine)
Finds intersection point with the specified line.
Point? GetIntersectionWith (LineSegment other)
Finds, provided it exists, the intersection point with the specified LineSegment.
float DistanceToPoint (Point point)
Calculate Euclidean distance between a point and a line.
override bool Equals (object obj)
Check if this instance of Line equals to the specified one.
override int GetHashCode ()
Get hash code for this instance.
override string ToString ()
Get string representation of the class.
Static Public Member Functions
static Line FromPoints (Point point1, Point point2)
Creates a Line that goes through the two specified points.
static Line FromSlopeIntercept (float slope, float intercept)
Creates a Line with the specified slope and intercept.
static Line FromRTheta (float radius, float theta)
Constructs a Line from a radius and an angle (in degrees).
static Line FromPointTheta (Point point, float theta)
Constructs a Line from a point and an angle (in degrees).
static bool operator== (Line line1, Line line2)
Equality operator - checks if two lines have equal parameters.
static bool operator!= (Line line1, Line line2)
Inequality operator - checks if two lines have different parameters.
Properties
bool IsVertical [get]
Checks if the line vertical or not.
bool IsHorizontal [get]
Checks if the line horizontal or not.
float Slope [get]
Gets the slope of the line.
float Intercept [get]
If not IsVertical, gets the Line's Y-intercept. If IsVertical gets the line's X-intercept.
Private Member Functions
Line (Point start, Point end)
Line (float slope, float intercept)
Line (float radius, float theta, bool unused)
Line (Point point, float theta)
Private Attributes
readonly float k
readonly float b
Detailed Description
The class encapsulates 2D line and provides some tool methods related to lines.
The class provides some methods which are related to lines: angle between lines, distance to point, finding intersection point, etc.
Generally, the equation of the line is y = Slope * x + Intercept. However, when Slope is an Infinity, would normally be meaningless, and it would be impossible to distinguish the line x = 5 from the line x = -5. Therefore, if Slope is float.PositiveInfinity or float.NegativeInfinity, the line's equation is instead x = Intercept.
Sample usage:
// create a line
Line line = Line.FromPoints(new Point(0, 0), new Point(3, 4));
// check if it is vertical or horizontal
if (line.IsVertical || line.IsHorizontal)
{
    // ...
}
// get intersection point with another line
Point intersection = line.GetIntersectionWith(
    Line.FromPoints( new Point( 3, 0 ), new Point( 0, 4 ) ) );
Constructor & Destructor Documentation
Line() [1/4]
AForge.Math.Geometry.Line.Line (Point start, Point end) inline private
References AForge.Math.Geometry.Line.b, AForge.Math.Geometry.Line.k, AForge.Point.X, and AForge.Point.Y.
Referenced by AForge.Math.Geometry.Line.Equals(), AForge.Math.Geometry.Line.FromPoints(), AForge.Math.Geometry.Line.FromPointTheta(), AForge.Math.Geometry.Line.FromRTheta(), and AForge.Math.Geometry.Line.FromSlopeIntercept().
Line() [2/4]
AForge.Math.Geometry.Line.Line (float slope, float intercept) inline private
References AForge.Math.Geometry.Line.b, and AForge.Math.Geometry.Line.k.
Line() [3/4]
AForge.Math.Geometry.Line.Line (float radius, float theta, bool unused) inline private
References AForge.Math.Geometry.Line.b, AForge.Math.Geometry.Line.k, AForge.Point.X, and AForge.Point.Y.
Line() [4/4]
AForge.Math.Geometry.Line.Line (Point point, float theta) inline private
References AForge.Math.Geometry.Line.b, AForge.Math.Geometry.Line.k, AForge.Point.X, and AForge.Point.Y.
Member Function Documentation
FromPoints()
static Line AForge.Math.Geometry.Line.FromPoints (Point point1, Point point2) inline static
Creates a Line that goes through the two specified points.
Parameters
point1 One point on the line.
point2 Another point on the line.
Returns
Returns a Line representing the line between point1 and point2 .
Exceptions
ArgumentException Thrown if the two points are the same.
References AForge.Math.Geometry.Line.Line().
Referenced by AForge.Math.Geometry.Tests.LineTest.DistanceToPointTest(), AForge.Math.Geometry.GeometryTools.GetAngleBetweenLines(), AForge.Math.Geometry.Tests.LineTest.GetAngleBetweenLinesTest(), AForge.Math.Geometry.Tests.LineTest.GetIntersectionPointTest(), AForge.Math.Geometry.Tests.LineTest.IsHorizontalTest(), AForge.Math.Geometry.Tests.LineTest.IsVerticalTest(), and AForge.Math.Geometry.LineSegment.LineSegment().
FromSlopeIntercept()
static Line AForge.Math.Geometry.Line.FromSlopeIntercept (float slope, float intercept) inline static
Creates a Line with the specified slope and intercept.
Parameters
slope The slope of the line
intercept The Y-intercept of the line, unless the slope is an infinity, in which case the line's equation is "x = intercept" instead.
Returns
Returns a Line representing the specified line.
The construction here follows the same rules as for the rest of this class. Most lines are expressed as y = slope * x + intercept. Vertical lines, however, are x = intercept. This is indicated by IsVertical being true or by Slope returning float.PositiveInfinity or float.NegativeInfinity.
References AForge.Math.Geometry.Line.Line().
FromRTheta()
static Line AForge.Math.Geometry.Line.FromRTheta (float radius, float theta) inline static
Constructs a Line from a radius and an angle (in degrees).
Parameters
radius The minimum distance from the line to the origin.
theta The angle of the vector from the origin to the line.
Returns
Returns a Line representing the specified line.
radius is the minimum distance from the origin to the line, and theta is the counterclockwise rotation from the positive X axis to the vector through the origin and normal to the line.
This means that if theta is in [0,180), the point on the line closest to the origin is on the positive X or Y axes, or in quadrants I or II. Likewise, if theta is in [180,360), the point on the line closest to the origin is on the negative X or Y axes, or in quadrants III or IV.
Exceptions
ArgumentOutOfRangeException Thrown if radius is negative.
References AForge.Math.Geometry.Line.Line().
Referenced by AForge.Math.Geometry.Tests.LineTest.RThetaTest().
FromPointTheta()
static Line AForge.Math.Geometry.Line.FromPointTheta (Point point, float theta) inline static
Constructs a Line from a point and an angle (in degrees).
Parameters
point The minimum distance from the line to the origin.
theta The angle of the normal vector from the origin to the line.
theta is the counterclockwise rotation from the positive X axis to the vector through the origin and normal to the line.
This means that if theta is in [0,180), the point on the line closest to the origin is on the positive X or Y axes, or in quadrants I or II. Likewise, if theta is in [180,360), the point on the line closest to the origin is on the negative X or Y axes, or in quadrants III or IV.
Returns
Returns a Line representing the specified line.
References AForge.Math.Geometry.Line.Line().
Referenced by AForge.Math.Geometry.Tests.LineTest.RThetaTest().
GetAngleBetweenLines()
float AForge.Math.Geometry.Line.GetAngleBetweenLines (Line secondLine) inline
Calculate minimum angle between this line and the specified line measured in [0, 90] degrees range.
Parameters
secondLine The line to find angle between.
Returns
Returns minimum angle between lines.
References AForge.Math.Geometry.Line.IsVertical, and AForge.Math.Geometry.Line.k.
Referenced by AForge.Math.Geometry.GeometryTools.GetAngleBetweenLines(), and AForge.Math.Geometry.Tests.LineTest.GetAngleBetweenLinesTest().
GetIntersectionWith() [1/2]
Point? AForge.Math.Geometry.Line.GetIntersectionWith (Line secondLine) inline
Finds intersection point with the specified line.
Parameters
secondLine Line to find intersection with.
Returns
Returns intersection point with the specified line, or null if the lines are parallel and distinct.
Exceptions
InvalidOperationException Thrown if the specified line is the same line as this line.
References AForge.Math.Geometry.Line.b, AForge.Math.Geometry.Line.IsVertical, and AForge.Math.Geometry.Line.k.
Referenced by AForge.Math.Geometry.Tests.LineTest.GetIntersectionPointTest(), AForge.Math.Geometry.LineSegment.GetIntersectionWith(), and AForge.Math.Geometry.Tests.LineSegmentTest.ParallelIntersectionPointTest().
GetIntersectionWith() [2/2]
Point? AForge.Math.Geometry.Line.GetIntersectionWith (LineSegment other) inline
Finds, provided it exists, the intersection point with the specified LineSegment.
Parameters
other LineSegment to find intersection with.
Returns
Returns intersection point with the specified LineSegment, or null, if this line does not intersect with the segment.
If the line and segment do not intersect, the method returns null. If the line and segment share multiple points, the method throws an InvalidOperationException.
Exceptions
InvalidOperationException Thrown if other is a portion of this line.
References AForge.Math.Geometry.LineSegment.GetIntersectionWith().
DistanceToPoint()
float AForge.Math.Geometry.Line.DistanceToPoint (Point point) inline
Calculate Euclidean distance between a point and a line.
Parameters
point The point to calculate distance to.
Returns
Returns the Euclidean distance between this line and the specified point. Unlike LineSegment.DistanceToPoint, this returns the distance from the infinite line. (0,0) is 0 units from the line defined by (0,5) and (0,8), but is 5 units from the segment with those endpoints.
References AForge.Math.Geometry.Line.b, AForge.Math.Geometry.Line.IsVertical, AForge.Math.Geometry.Line.k, AForge.Point.X, and AForge.Point.Y.
Referenced by AForge.Math.Geometry.LineSegment.DistanceToPoint(), and AForge.Math.Geometry.Tests.LineTest.DistanceToPointTest().
operator==()
static bool AForge.Math.Geometry.Line.operator== (Line line1, Line line2) inline static
Equality operator - checks if two lines have equal parameters.
Parameters
line1 First line to check.
line2 Second line to check.
Returns
Returns true if parameters of specified lines are equal.
References AForge.Math.Geometry.Line.b, and AForge.Math.Geometry.Line.k.
operator!=()
static bool AForge.Math.Geometry.Line.operator!= (Line line1, Line line2) inline static
Inequality operator - checks if two lines have different parameters.
Parameters
line1 First line to check.
line2 Second line to check.
Returns
Returns true if parameters of specified lines are not equal.
Equals()
override bool AForge.Math.Geometry.Line.Equals (object obj) inline
Check if this instance of Line equals to the specified one.
Parameters
obj Another line to check equalty to.
Returns
Return true if objects are equal.
References AForge.Math.Geometry.Line.Line().
GetHashCode()
override int AForge.Math.Geometry.Line.GetHashCode () inline
Get hash code for this instance.
Returns
Returns the hash code for this instance.
References AForge.Math.Geometry.Line.b, and AForge.Math.Geometry.Line.k.
ToString()
override string AForge.Math.Geometry.Line.ToString () inline
Get string representation of the class.
Returns
Returns string, which contains values of the like in readable form.
References AForge.Math.Geometry.Line.b, and AForge.Math.Geometry.Line.k.
Member Data Documentation
k
readonly float AForge.Math.Geometry.Line.k private
Referenced by AForge.Math.Geometry.Line.DistanceToPoint(), AForge.Math.Geometry.Line.GetAngleBetweenLines(), AForge.Math.Geometry.Line.GetHashCode(), AForge.Math.Geometry.Line.GetIntersectionWith(), AForge.Math.Geometry.Line.Line(), AForge.Math.Geometry.Line.operator==(), and AForge.Math.Geometry.Line.ToString().
b
readonly float AForge.Math.Geometry.Line.b private
Referenced by AForge.Math.Geometry.Line.DistanceToPoint(), AForge.Math.Geometry.Line.GetHashCode(), AForge.Math.Geometry.Line.GetIntersectionWith(), AForge.Math.Geometry.Line.Line(), AForge.Math.Geometry.Line.operator==(), and AForge.Math.Geometry.Line.ToString().
Property Documentation
IsVertical
bool AForge.Math.Geometry.Line.IsVertical get
Checks if the line vertical or not.
Referenced by AForge.Math.Geometry.Line.DistanceToPoint(), AForge.Math.Geometry.Line.GetAngleBetweenLines(), AForge.Math.Geometry.LineSegment.GetIntersectionWith(), AForge.Math.Geometry.Line.GetIntersectionWith(), and AForge.Math.Geometry.Tests.LineTest.IsVerticalTest().
IsHorizontal
bool AForge.Math.Geometry.Line.IsHorizontal get
Checks if the line horizontal or not.
Referenced by AForge.Math.Geometry.Tests.LineTest.IsHorizontalTest().
Slope
float AForge.Math.Geometry.Line.Slope get
Gets the slope of the line.
Referenced by AForge.Math.Geometry.LineSegment.GetIntersectionWith(), AForge.Math.Geometry.Tests.LineTest.IsHorizontalTest(), AForge.Math.Geometry.Tests.LineTest.IsVerticalTest(), and AForge.Math.Geometry.Tests.LineTest.RThetaTest().
Intercept
float AForge.Math.Geometry.Line.Intercept get
If not IsVertical, gets the Line's Y-intercept. If IsVertical gets the line's X-intercept.
Referenced by AForge.Math.Geometry.LineSegment.GetIntersectionWith(), AForge.Math.Geometry.Tests.LineTest.IsHorizontalTest(), AForge.Math.Geometry.Tests.LineTest.IsVerticalTest(), and AForge.Math.Geometry.Tests.LineTest.RThetaTest().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Math/Geometry/Line.cs