Doc: IGLib EXTENDED: alglib.testnormestimatorunit Class Reference
alglib.testnormestimatorunit Class Reference
Static Public Member Functions
static bool testnormestimator (bool silent)
static bool testnormestimator (bool silent)
static bool _pexec_testnormestimator (bool silent)
Member Function Documentation
testnormestimator() [1/2]
static bool alglib.testnormestimatorunit.testnormestimator (bool silent) inline static
References alglib.normestimator.normestimatorcreate(), alglib.normestimator.normestimatorestimatesparse(), alglib.normestimator.normestimatorresults(), alglib.normestimator.normestimatorsetseed(), alglib.math.randomreal(), alglib.matgen.rmatrixrndcond(), alglib.matgen.rmatrixrndorthogonal(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), and alglib.sparse.sparseset().
Referenced by alglib.testnormestimatorunit._pexec_testnormestimator(), and _Test.Main().
testnormestimator() [2/2]
static bool alglib.testnormestimatorunit.testnormestimator (bool silent) inline static
References alglib.normestimator.normestimatorcreate(), alglib.normestimator.normestimatorestimatesparse(), alglib.normestimator.normestimatorresults(), alglib.normestimator.normestimatorsetseed(), alglib.math.randomreal(), alglib.matgen.rmatrixrndcond(), alglib.matgen.rmatrixrndorthogonal(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), and alglib.sparse.sparseset().
_pexec_testnormestimator()
static bool alglib.testnormestimatorunit._pexec_testnormestimator (bool silent) inline static
References alglib.testnormestimatorunit.testnormestimator().
Referenced by _Test.Main().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs