Doc: IGLib EXTENDED: CShell.ScriptingEngine Class Reference
CShell.ScriptingEngine Class Reference
Public Member Functions
ScriptingEngine ()
void Dispose ()
Task< EvaluatorResult > EvaluateAsync (string input)
Task< EvaluatorResult > EvaluateAsync (string input, string sourceFile)
Task< EvaluatorResult > EvaluateAsync (string input, string sourceFile, CancellationToken cancellationToken)
EvaluatorResult Evaluate (string input)
EvaluatorResult Evaluate (string input, string sourceFile)
void Interrupt ()
void ReferenceAssembly (Assembly assembly)
void ReferenceAssembly (string file)
string GetUsing ()
string GetVars ()
Properties
CSharpCompletion CodeCompletion [get]
Events
EventHandler< ConsoleEventArgs > ConsoleOutput
EventHandler< EvaluateStartedEventArgs > EvaluateStarted
EventHandler< EvaluateCompletedEventArgs > EvaluateCompleted
Private Member Functions
void OnConsoleOutput (string text, TextType textType)
void OnConsoleOutput (ConsoleEventArgs e)
void OnEvaluateStarted (string input, string sourceFile)
void OnEvaluateCompleted (EvaluateCompletedEventArgs e)
Static Private Member Functions
static bool IsMessage (string message, string messageType)
Private Attributes
readonly Evaluator evaluator
readonly CompilerContext context
readonly TaskFactory taskFactory
readonly CancellationTokenSource tokenSource
readonly CSharpCompletion codeCompletion
Constructor & Destructor Documentation
ScriptingEngine()
CShell.ScriptingEngine.ScriptingEngine () inline
References CShell.ScriptingEngine.codeCompletion, CShell.ScriptingEngine.context, CShell.Code.ScriptingInteractiveBase.Error, CShell.ScriptingEngine.Evaluate(), CShell.Code.ScriptingInteractiveBase.Evaluator, CShell.ScriptingEngine.evaluator, CShell.ScriptingEngine.OnConsoleOutput(), CShell.Code.ScriptingInteractiveBase.Output, CShell.ScriptingEngine.taskFactory, and CShell.ScriptingEngine.tokenSource.
Member Function Documentation
Dispose()
void CShell.ScriptingEngine.Dispose () inline
References CShell.ScriptingEngine.tokenSource.
OnConsoleOutput() [1/2]
void CShell.ScriptingEngine.OnConsoleOutput (string text, TextType textType) inline private
Referenced by CShell.ScriptingEngine.ScriptingEngine().
OnConsoleOutput() [2/2]
void CShell.ScriptingEngine.OnConsoleOutput (ConsoleEventArgs e) inline private
References CShell.ScriptingEngine.ConsoleOutput.
OnEvaluateStarted()
void CShell.ScriptingEngine.OnEvaluateStarted (string input, string sourceFile) inline private
References CShell.ScriptingEngine.EvaluateStarted.
Referenced by CShell.ScriptingEngine.Evaluate().
OnEvaluateCompleted()
void CShell.ScriptingEngine.OnEvaluateCompleted (EvaluateCompletedEventArgs e) inline private
References CShell.ScriptingEngine.EvaluateCompleted.
Referenced by CShell.ScriptingEngine.Evaluate().
EvaluateAsync() [1/3]
Task<EvaluatorResult> CShell.ScriptingEngine.EvaluateAsync (string input) inline
Referenced by CShell.Modules.Repl.Controls.CSRepl.CommandEntered(), CShell.ScriptingEngine.EvaluateAsync(), and CShell.Framework.Results.RunCodeResult.Execute().
EvaluateAsync() [2/3]
Task<EvaluatorResult> CShell.ScriptingEngine.EvaluateAsync (string input, string sourceFile) inline
References CShell.ScriptingEngine.EvaluateAsync().
EvaluateAsync() [3/3]
Task<EvaluatorResult> CShell.ScriptingEngine.EvaluateAsync (string input, string sourceFile, CancellationToken cancellationToken) inline
References CShell.ScriptingEngine.Evaluate(), and CShell.ScriptingEngine.taskFactory.
Evaluate() [1/2]
EvaluatorResult CShell.ScriptingEngine.Evaluate (string input) inline
Referenced by CShell.ScriptingEngine.EvaluateAsync(), CShell.Shell.EvaluateFile(), and CShell.ScriptingEngine.ScriptingEngine().
Evaluate() [2/2]
EvaluatorResult CShell.ScriptingEngine.Evaluate (string input, string sourceFile) inline
References CShell.ScriptingEngine.codeCompletion, CShell.ScriptingEngine.context, CShell.ScriptingEngine.evaluator, CShell.ScriptingEngine.IsMessage(), CShell.ScriptingEngine.OnEvaluateCompleted(), CShell.ScriptingEngine.OnEvaluateStarted(), and CShellCore.CodeCompletion.CSharpCompletion.ProcessInput().
IsMessage()
static bool CShell.ScriptingEngine.IsMessage (string message, string messageType) inline static private
Referenced by CShell.ScriptingEngine.Evaluate().
Interrupt()
void CShell.ScriptingEngine.Interrupt () inline
References CShell.ScriptingEngine.evaluator.
Referenced by CShell.Modules.Repl.Controls.CSRepl.TextAreaOnPreviewKeyDown().
ReferenceAssembly() [1/2]
void CShell.ScriptingEngine.ReferenceAssembly (Assembly assembly) inline
References CShellCore.CodeCompletion.CSharpCompletion.AddAssembly(), CShell.ScriptingEngine.codeCompletion, and CShell.ScriptingEngine.evaluator.
Referenced by CShell.AssemblyReferences.InsertItem(), and CShell.AssemblyReferences.SetItem().
ReferenceAssembly() [2/2]
void CShell.ScriptingEngine.ReferenceAssembly (string file) inline
References CShellCore.CodeCompletion.CSharpCompletion.AddAssembly(), CShell.ScriptingEngine.codeCompletion, and CShell.ScriptingEngine.evaluator.
GetUsing()
string CShell.ScriptingEngine.GetUsing () inline
Implements CShellCore.CodeCompletion.ICSharpScriptProvider.
References CShell.ScriptingEngine.evaluator.
GetVars()
string CShell.ScriptingEngine.GetVars () inline
Implements CShellCore.CodeCompletion.ICSharpScriptProvider.
References CShell.ScriptingEngine.evaluator.
Member Data Documentation
evaluator
readonly Evaluator CShell.ScriptingEngine.evaluator private
Referenced by CShell.ScriptingEngine.Evaluate(), CShell.ScriptingEngine.GetUsing(), CShell.ScriptingEngine.GetVars(), CShell.ScriptingEngine.Interrupt(), CShell.ScriptingEngine.ReferenceAssembly(), and CShell.ScriptingEngine.ScriptingEngine().
context
readonly CompilerContext CShell.ScriptingEngine.context private
Referenced by CShell.ScriptingEngine.Evaluate(), and CShell.ScriptingEngine.ScriptingEngine().
taskFactory
readonly TaskFactory CShell.ScriptingEngine.taskFactory private
Referenced by CShell.ScriptingEngine.EvaluateAsync(), and CShell.ScriptingEngine.ScriptingEngine().
tokenSource
readonly CancellationTokenSource CShell.ScriptingEngine.tokenSource private
Referenced by CShell.ScriptingEngine.Dispose(), and CShell.ScriptingEngine.ScriptingEngine().
codeCompletion
readonly CSharpCompletion CShell.ScriptingEngine.codeCompletion private
Referenced by CShell.ScriptingEngine.Evaluate(), CShell.ScriptingEngine.ReferenceAssembly(), and CShell.ScriptingEngine.ScriptingEngine().
Property Documentation
CodeCompletion
CSharpCompletion CShell.ScriptingEngine.CodeCompletion get
Referenced by CShell.Modules.Editors.ViewModels.EditorViewModel.OnViewLoaded().
Event Documentation
ConsoleOutput
EventHandler<ConsoleEventArgs> CShell.ScriptingEngine.ConsoleOutput
Referenced by CShell.Modules.Repl.ViewModels.OutputViewModel.Handle(), CShell.ScriptingEngine.OnConsoleOutput(), and CShell.Modules.Repl.ViewModels.OutputViewModel.OutputViewModel().
EvaluateStarted
EventHandler<EvaluateStartedEventArgs> CShell.ScriptingEngine.EvaluateStarted
Referenced by CShell.ScriptingEngine.OnEvaluateStarted().
EvaluateCompleted
EventHandler<EvaluateCompletedEventArgs> CShell.ScriptingEngine.EvaluateCompleted
Referenced by CShell.ScriptingEngine.OnEvaluateCompleted().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore/ScriptingEngine.cs