Doc: IGLib EXTENDED: NUnit.Engine.Internal.ResultHelper Class Reference
NUnit.Engine.Internal.ResultHelper Class Reference
ResultHelper provides static methods for working with TestEngineResults to wrap, combiner and aggregate them in various ways.
Static Public Member Functions
static TestEngineResult Aggregate (this TestEngineResult result, string elementName, string suiteType, string name, string fullName)
Aggregate the XmlNodes under a TestEngineResult into a single XmlNode.
static TestEngineResult Aggregate (this TestEngineResult result, string elementName, string name, string fullName)
Aggregate the XmlNodes under a TestEngineResult into a single XmlNode.
static TestEngineResult MakePackageResult (this TestEngineResult result, string name, string fullName)
Aggregate all the separate assembly results of a project as a single node.
static TestEngineResult Merge (IList< TestEngineResult > results)
Merges multiple test engine results into a single result. The result element contains all the XML nodes found in the input.
static XmlNode Aggregate (string elementName, string name, string fullName, IList< XmlNode > resultNodes)
Aggregates a collection of XmlNodes under a single XmlNode.
static XmlNode Aggregate (string elementName, string testType, string name, string fullName, IList< XmlNode > resultNodes)
Aggregates a collection of XmlNodes under a single XmlNode.
Static Private Attributes
const string TEST_SUITE_ELEMENT = "test-suite"
const string PROJECT_SUITE_TYPE = "Project"
Detailed Description
ResultHelper provides static methods for working with TestEngineResults to wrap, combiner and aggregate them in various ways.
Member Function Documentation
Aggregate() [1/4]
static TestEngineResult NUnit.Engine.Internal.ResultHelper.Aggregate (this TestEngineResult result, string elementName, string suiteType, string name, string fullName) inline static
Aggregate the XmlNodes under a TestEngineResult into a single XmlNode.
Parameters
result A new TestEngineResult with xml nodes for each assembly or project.
elementName The root node name under which to aggregate the nodes.
suiteType The suite type to associate with the TestEngineResult.
name The name of the TestEngineResult.
fullName The full name of the TestEngineResult.
Returns
A TestEngineResult with a single top-level element.
References NUnit.Engine.TestEngineResult.XmlNodes.
Referenced by NUnit.Engine.Internal.ResultHelper.Aggregate(), NUnit.Engine.Internal.Tests.ResultHelperTests.AggregateXmlNodes(), and NUnit.Engine.Internal.ResultHelper.MakePackageResult().
Aggregate() [2/4]
static TestEngineResult NUnit.Engine.Internal.ResultHelper.Aggregate (this TestEngineResult result, string elementName, string name, string fullName) inline static
Aggregate the XmlNodes under a TestEngineResult into a single XmlNode.
Parameters
result A new TestEngineResult with xml nodes for each assembly or project.
elementName The root node name under which to aggregate the results.
name The name of the TestEngineResult.
fullName The full name of the TestEngineResult.
Returns
A TestEngineResult with a single top-level element.
References NUnit.Engine.Internal.ResultHelper.Aggregate(), and NUnit.Engine.TestEngineResult.XmlNodes.
MakePackageResult()
static TestEngineResult NUnit.Engine.Internal.ResultHelper.MakePackageResult (this TestEngineResult result, string name, string fullName) inline static
Aggregate all the separate assembly results of a project as a single node.
Parameters
result A new TestEngineResult with xml nodes for each assembly or project.
name The name of the TestEngineResult.
fullName The full name of the TestEngineResult.
Returns
A TestEngineResult with a single top-level element.
References NUnit.Engine.Internal.ResultHelper.Aggregate(), NUnit.Engine.Internal.ResultHelper.PROJECT_SUITE_TYPE, and NUnit.Engine.Internal.ResultHelper.TEST_SUITE_ELEMENT.
Merge()
static TestEngineResult NUnit.Engine.Internal.ResultHelper.Merge (IList< TestEngineResult > results) inline static
Merges multiple test engine results into a single result. The result element contains all the XML nodes found in the input.
Parameters
results A collection of TestEngineResult to merge.
Returns
A TestEngineResult merging all the input results.
Used by AbstractTestRunner MakePackageResult method.
References NUnit.Engine.TestEngineResult.XmlNodes.
Referenced by NUnit.Engine.Runners.AggregatingTestRunner.ExploreTests(), NUnit.Engine.Runners.AggregatingTestRunner.LoadPackage(), NUnit.Engine.Internal.Tests.ResultHelperTests.MergeAndAggregateTestResults(), NUnit.Engine.Internal.Tests.ResultHelperTests.MergeTestResults(), and NUnit.Engine.Runners.AggregatingTestRunner.RunTests().
Aggregate() [3/4]
static XmlNode NUnit.Engine.Internal.ResultHelper.Aggregate (string elementName, string name, string fullName, IList< XmlNode > resultNodes) inline static
Aggregates a collection of XmlNodes under a single XmlNode.
Parameters
elementName The root node name under which to aggregate the results.
name The name to associated with the root node.
fullName The full name to associated with the root node.
resultNodes A collection of XmlNodes to aggregate
Returns
A single XmlNode containing the aggregated list of XmlNodes.
References NUnit.Engine.Internal.ResultHelper.Aggregate().
Aggregate() [4/4]
static XmlNode NUnit.Engine.Internal.ResultHelper.Aggregate (string elementName, string testType, string name, string fullName, IList< XmlNode > resultNodes) inline static
Aggregates a collection of XmlNodes under a single XmlNode.
Parameters
elementName The root node name under which to aggregate the results.
testType The type to associated with the root node.
name The name to associated with the root node.
fullName The full name to associated with the root node.
resultNodes A collection of XmlNodes to aggregate
Returns
A single XmlNode containing the aggregated list of XmlNodes.
Member Data Documentation
TEST_SUITE_ELEMENT
const string NUnit.Engine.Internal.ResultHelper.TEST_SUITE_ELEMENT = "test-suite" static private
Referenced by NUnit.Engine.Internal.ResultHelper.MakePackageResult().
PROJECT_SUITE_TYPE
const string NUnit.Engine.Internal.ResultHelper.PROJECT_SUITE_TYPE = "Project" static private
Referenced by NUnit.Engine.Internal.ResultHelper.MakePackageResult().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Internal/ResultHelper.cs