Doc: IGLib EXTENDED: NUnit.Framework.Constraints.ConstraintTestBase Class Reference
NUnit.Framework.Constraints.ConstraintTestBase Class Reference
Public Member Functions
void SucceedsWithGoodValues (object value)
void FailsWithBadValues (object badValue, string message)
Public Member Functions inherited from NUnit.Framework.Constraints.ConstraintTestBaseNoData
void ProvidesProperDescription ()
void ProvidesProperStringRepresentation ()
Additional Inherited Members
Protected Attributes inherited from NUnit.Framework.Constraints.ConstraintTestBaseNoData
Constraint theConstraint
string expectedDescription = "<NOT SET>"
string stringRepresentation = "<NOT SET>"
Member Function Documentation
SucceedsWithGoodValues()
void NUnit.Framework.Constraints.ConstraintTestBase.SucceedsWithGoodValues (object value) inline
References NUnit.Framework.Assert.Fail(), and NUnit.Framework.Constraints.ConstraintTestBaseNoData.theConstraint.
FailsWithBadValues()
void NUnit.Framework.Constraints.ConstraintTestBase.FailsWithBadValues (object badValue, string message) inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Constraints.ConstraintTestBaseNoData.expectedDescription, NUnit.Framework.Assert.IsFalse(), NUnit.Env.NewLine, NUnit.Framework.Internal.TextMessageWriter.Pfx_Actual, NUnit.Framework.Internal.TextMessageWriter.Pfx_Expected, NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.ConstraintTestBaseNoData.theConstraint.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/ConstraintTestBase.cs