Doc: IGLib EXTENDED: IG.Neural.Applications.NeuralDemoAbout Class Reference
IG.Neural.Applications.NeuralDemoAbout Class Reference
Public Member Functions
NeuralDemoAbout ()
virtual string GetHelpLocationInExecutableDirectory ()
virtual string GetHelpLocationPdfInExecutableDirectory ()
void HelpBrowse ()
void HelpPdf ()
void WebPageBrowse ()
void HelpShow ()
void WebPageShow ()
NeuralDemoAbout ()
virtual string GetHelpLocationInExecutableDirectory ()
void BrowseHelp ()
void BrowseWebPage ()
void ShowHelp ()
void ShowWebPage ()
NeuralDemoAbout ()
virtual string GetHelpLocationInExecutableDirectory ()
void BrowseHelp ()
void BrowseWebPage ()
void ShowHelp ()
void ShowWebPage ()
Public Attributes
string DefaultApplicationName = "NeurApp"
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
string _homePageShort
string _helpLocation
string _helpLocationPdf
BrowserSimpleForm _browser
string _applicationName
int _fadingMessageShowTimeMs = 1000
Properties
virtual string HomePageShort [get, protected set]
Short version of the application's home page.
virtual string HomePage [get]
virtual string HelpLocation [get]
Location of the help file that can be displayed in a web browser.
virtual string HelpLocationPdf [get]
Location of the help file that can be displayed in a web browser.
BrowserSimpleForm Browser [get]
string ApplicationName [get]
Private Member Functions
void lblAboutWeb_Click (object sender, EventArgs e)
void btnHelpPdf_Click (object sender, EventArgs e)
void btnHelpHtml_Click (object sender, EventArgs e)
void btnWeb_Click (object sender, EventArgs e)
void pnlAbout_Paint (object sender, PaintEventArgs e)
Triggered on each repaint of the panel. can be attemted to make background transparent.
void lblBrowseHelp_Click (object sender, EventArgs e)
void lblHelpPdf_Click (object sender, EventArgs e)
void lblBrowseHome_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void lblAboutWeb_Click (object sender, EventArgs e)
void btnHelp_Click (object sender, EventArgs e)
void btnWeb_Click (object sender, EventArgs e)
void pnlAbout_Paint (object sender, PaintEventArgs e)
Triggered on each repaint of the panel. can be attemted to make background transparent.
void lblBrowseHelp_Click (object sender, EventArgs e)
void lblBrowseHome_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void lblAboutWeb_Click (object sender, EventArgs e)
void btnHelp_Click (object sender, EventArgs e)
void btnWeb_Click (object sender, EventArgs e)
void pnlAbout_Paint (object sender, PaintEventArgs e)
Triggered on each repaint of the panel. can be attemted to make background transparent.
void lblBrowseHelp_Click (object sender, EventArgs e)
void lblBrowseHome_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Label lblTitle
System.Windows.Forms.Button btnHelpHtml
System.Windows.Forms.Panel pnlAbout
System.Windows.Forms.Label lblAboutAuthors
System.Windows.Forms.Label lblAboutAuthorsIntro
System.Windows.Forms.Label lblAboutTitle
System.Windows.Forms.Label lblAboutWeb
System.Windows.Forms.Label lblAboutContact
System.Windows.Forms.Label lblAbourContactIntro
System.Windows.Forms.PictureBox pbIGLib
System.Windows.Forms.Label lblPoweredIGLib
System.Windows.Forms.Panel pnlIGLib
System.Windows.Forms.Button btnWeb
System.Windows.Forms.Label lblHomeBrowse
System.Windows.Forms.Label lblHelpBrowse
System.Windows.Forms.Button btnHelpPdf
System.Windows.Forms.Button btnHelp
System.Windows.Forms.Label lblAboutAuthorGui
System.Windows.Forms.Label lblBrowseHome
System.Windows.Forms.Label lblBrowseHelp
Static Private Attributes
const string DefaultHomePageShort = "www2.arnes.si/~ljc3m2/igor/software/NeurApp/"
const string DefaultHelpLocation = "http://www2.arnes.si/~ljc3m2/igor/software/NeurApp/doc/NeurApp_help.html"
const string DefaultHelpLocationPdf = "http://www2.arnes.si/~ljc3m2/igor/software/NeurApp/doc/NeurApp_help.pdf"
Constructor & Destructor Documentation
NeuralDemoAbout() [1/3]
IG.Neural.Applications.NeuralDemoAbout.NeuralDemoAbout () inline
References IG.Neural.Applications.NeuralDemoAbout.DefaultHomePageShort, IG.Neural.Applications.NeuralDemoAbout.InitializeComponent(), and IG.Neural.Applications.NeuralDemoAbout.lblAboutWeb.
NeuralDemoAbout() [2/3]
IG.Neural.Applications.NeuralDemoAbout.NeuralDemoAbout () inline
References IG.Neural.Applications.NeuralDemoAbout.DefaultHomePageShort, IG.Neural.Applications.NeuralDemoAbout.InitializeComponent(), and IG.Neural.Applications.NeuralDemoAbout.lblAboutWeb.
NeuralDemoAbout() [3/3]
IG.Neural.Applications.NeuralDemoAbout.NeuralDemoAbout () inline
References IG.Neural.Applications.NeuralDemoAbout.DefaultHomePageShort, IG.Neural.Applications.NeuralDemoAbout.InitializeComponent(), and IG.Neural.Applications.NeuralDemoAbout.lblAboutWeb.
Member Function Documentation
GetHelpLocationInExecutableDirectory() [1/3]
virtual string IG.Neural.Applications.NeuralDemoAbout.GetHelpLocationInExecutableDirectory () inline virtual
References IG.Neural.Applications.NeuralDemoAbout.ApplicationName.
GetHelpLocationPdfInExecutableDirectory()
virtual string IG.Neural.Applications.NeuralDemoAbout.GetHelpLocationPdfInExecutableDirectory () inline virtual
References IG.Neural.Applications.NeuralDemoAbout.ApplicationName.
HelpBrowse()
void IG.Neural.Applications.NeuralDemoAbout.HelpBrowse () inline
References IG.Neural.Applications.NeuralDemoAbout._fadingMessageShowTimeMs, IG.Neural.Applications.NeuralDemoAbout.HelpLocation, IG.Forms.FadingMessage.LaunchedAtMouseCursor, and IG.Forms.FadingMessage.LaunchedInParallelThread.
Referenced by IG.Neural.Applications.NeuralDemoAbout.lblBrowseHelp_Click().
HelpPdf()
void IG.Neural.Applications.NeuralDemoAbout.HelpPdf () inline
References IG.Neural.Applications.NeuralDemoAbout._fadingMessageShowTimeMs, IG.Neural.Applications.NeuralDemoAbout.HelpLocationPdf, IG.Forms.FadingMessage.LaunchedAtMouseCursor, and IG.Forms.FadingMessage.LaunchedInParallelThread.
Referenced by IG.Neural.Applications.NeuralDemoAbout.btnHelpPdf_Click(), and IG.Neural.Applications.NeuralDemoAbout.lblHelpPdf_Click().
WebPageBrowse()
void IG.Neural.Applications.NeuralDemoAbout.WebPageBrowse () inline
References IG.Neural.Applications.NeuralDemoAbout._fadingMessageShowTimeMs, IG.Neural.Applications.NeuralDemoAbout.HomePage, IG.Forms.FadingMessage.LaunchedAtMouseCursor, and IG.Forms.FadingMessage.LaunchedInParallelThread.
Referenced by IG.Neural.Applications.NeuralDemoAbout.lblBrowseHome_Click().
HelpShow()
void IG.Neural.Applications.NeuralDemoAbout.HelpShow () inline
References IG.Neural.Applications.NeuralDemoAbout.Browser, IG.Neural.Applications.NeuralDemoAbout.HelpLocation, and IG.Forms.BrowserSimpleForm.OpenLocation().
Referenced by IG.Neural.Applications.NeuralDemoAbout.btnHelpHtml_Click(), and IG.Neural.Applications.NeuralDemo.HelpEventHandlers().
WebPageShow()
void IG.Neural.Applications.NeuralDemoAbout.WebPageShow () inline
References IG.Neural.Applications.NeuralDemoAbout.Browser, IG.Neural.Applications.NeuralDemoAbout.HomePage, and IG.Forms.BrowserSimpleForm.OpenLocation().
Referenced by IG.Neural.Applications.NeuralDemoAbout.btnWeb_Click().
lblAboutWeb_Click() [1/3]
void IG.Neural.Applications.NeuralDemoAbout.lblAboutWeb_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralDemoAbout.lblAboutWeb.
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
btnHelpPdf_Click()
void IG.Neural.Applications.NeuralDemoAbout.btnHelpPdf_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralDemoAbout.HelpPdf().
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
btnHelpHtml_Click()
void IG.Neural.Applications.NeuralDemoAbout.btnHelpHtml_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralDemoAbout.HelpShow().
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
btnWeb_Click() [1/3]
void IG.Neural.Applications.NeuralDemoAbout.btnWeb_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralDemoAbout.WebPageShow().
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
pnlAbout_Paint() [1/3]
void IG.Neural.Applications.NeuralDemoAbout.pnlAbout_Paint (object sender, PaintEventArgs e) inline private
Triggered on each repaint of the panel. can be attemted to make background transparent.
Does not work. Color.FromArgb(25, Color.White); gets the closest to doing something.
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
lblBrowseHelp_Click() [1/3]
void IG.Neural.Applications.NeuralDemoAbout.lblBrowseHelp_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralDemoAbout.HelpBrowse().
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
lblHelpPdf_Click()
void IG.Neural.Applications.NeuralDemoAbout.lblHelpPdf_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralDemoAbout.HelpPdf().
lblBrowseHome_Click() [1/3]
void IG.Neural.Applications.NeuralDemoAbout.lblBrowseHome_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralDemoAbout.WebPageBrowse().
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
Dispose() [1/3]
override void IG.Neural.Applications.NeuralDemoAbout.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralDemoAbout.components.
InitializeComponent() [1/3]
void IG.Neural.Applications.NeuralDemoAbout.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralDemoAbout.btnHelpHtml, IG.Neural.Applications.NeuralDemoAbout.btnHelpHtml_Click(), IG.Neural.Applications.NeuralDemoAbout.btnHelpPdf, IG.Neural.Applications.NeuralDemoAbout.btnHelpPdf_Click(), IG.Neural.Applications.NeuralDemoAbout.btnWeb, IG.Neural.Applications.NeuralDemoAbout.btnWeb_Click(), IG.Neural.Applications.NeuralDemoAbout.lblAbourContactIntro, IG.Neural.Applications.NeuralDemoAbout.lblAboutAuthors, IG.Neural.Applications.NeuralDemoAbout.lblAboutAuthorsIntro, IG.Neural.Applications.NeuralDemoAbout.lblAboutContact, IG.Neural.Applications.NeuralDemoAbout.lblAboutTitle, IG.Neural.Applications.NeuralDemoAbout.lblAboutWeb, IG.Neural.Applications.NeuralDemoAbout.lblAboutWeb_Click(), IG.Neural.Applications.NeuralDemoAbout.lblBrowseHelp_Click(), IG.Neural.Applications.NeuralDemoAbout.lblBrowseHome_Click(), IG.Neural.Applications.NeuralDemoAbout.lblHelpBrowse, IG.Neural.Applications.NeuralDemoAbout.lblHomeBrowse, IG.Neural.Applications.NeuralDemoAbout.lblPoweredIGLib, IG.Neural.Applications.NeuralDemoAbout.lblTitle, IG.Neural.Applications.NeuralDemoAbout.pbIGLib, IG.Neural.Applications.NeuralDemoAbout.pnlAbout, IG.Neural.Applications.NeuralDemoAbout.pnlAbout_Paint(), and IG.Neural.Applications.NeuralDemoAbout.pnlIGLib.
Referenced by IG.Neural.Applications.NeuralDemoAbout.NeuralDemoAbout().
GetHelpLocationInExecutableDirectory() [2/3]
virtual string IG.Neural.Applications.NeuralDemoAbout.GetHelpLocationInExecutableDirectory () inline virtual
References IG.Neural.Applications.NeuralDemoAbout.ApplicationName.
BrowseHelp() [1/2]
void IG.Neural.Applications.NeuralDemoAbout.BrowseHelp () inline
References IG.Neural.Applications.NeuralDemoAbout._fadingMessageShowTimeMs, IG.Neural.Applications.NeuralDemoAbout.HelpLocation, IG.Forms.FadingMessage.LaunchedAtMouseCursor, and IG.Forms.FadingMessage.LaunchedInParallelThread.
Referenced by IG.Neural.Applications.NeuralDemoAbout.lblBrowseHelp_Click().
BrowseWebPage() [1/2]
void IG.Neural.Applications.NeuralDemoAbout.BrowseWebPage () inline
References IG.Neural.Applications.NeuralDemoAbout._fadingMessageShowTimeMs, IG.Neural.Applications.NeuralDemoAbout.HomePage, IG.Forms.FadingMessage.LaunchedAtMouseCursor, and IG.Forms.FadingMessage.LaunchedInParallelThread.
Referenced by IG.Neural.Applications.NeuralDemoAbout.lblBrowseHome_Click().
ShowHelp() [1/2]
void IG.Neural.Applications.NeuralDemoAbout.ShowHelp () inline
References IG.Neural.Applications.NeuralDemoAbout.Browser, IG.Neural.Applications.NeuralDemoAbout.HelpLocation, and IG.Forms.BrowserSimpleForm.OpenLocation().
Referenced by IG.Neural.Applications.NeuralDemoAbout.btnHelp_Click(), and IG.Neural.Applications.NeuralDemo.HelpEventHandlers().
ShowWebPage() [1/2]
void IG.Neural.Applications.NeuralDemoAbout.ShowWebPage () inline
References IG.Neural.Applications.NeuralDemoAbout.Browser, IG.Neural.Applications.NeuralDemoAbout.HomePage, and IG.Forms.BrowserSimpleForm.OpenLocation().
Referenced by IG.Neural.Applications.NeuralDemoAbout.btnWeb_Click().
lblAboutWeb_Click() [2/3]
void IG.Neural.Applications.NeuralDemoAbout.lblAboutWeb_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralDemoAbout.lblAboutWeb.
btnHelp_Click() [1/2]
void IG.Neural.Applications.NeuralDemoAbout.btnHelp_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralDemoAbout.ShowHelp().
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
btnWeb_Click() [2/3]
void IG.Neural.Applications.NeuralDemoAbout.btnWeb_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralDemoAbout.ShowWebPage().
pnlAbout_Paint() [2/3]
void IG.Neural.Applications.NeuralDemoAbout.pnlAbout_Paint (object sender, PaintEventArgs e) inline private
Triggered on each repaint of the panel. can be attemted to make background transparent.
Does not work. Color.FromArgb(25, Color.White); gets the closest to doing something.
lblBrowseHelp_Click() [2/3]
void IG.Neural.Applications.NeuralDemoAbout.lblBrowseHelp_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralDemoAbout.BrowseHelp().
lblBrowseHome_Click() [2/3]
void IG.Neural.Applications.NeuralDemoAbout.lblBrowseHome_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralDemoAbout.BrowseWebPage().
Dispose() [2/3]
override void IG.Neural.Applications.NeuralDemoAbout.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralDemoAbout.components.
InitializeComponent() [2/3]
void IG.Neural.Applications.NeuralDemoAbout.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralDemoAbout.btnHelp, IG.Neural.Applications.NeuralDemoAbout.btnHelp_Click(), IG.Neural.Applications.NeuralDemoAbout.btnWeb, IG.Neural.Applications.NeuralDemoAbout.btnWeb_Click(), IG.Neural.Applications.NeuralDemoAbout.lblAbourContactIntro, IG.Neural.Applications.NeuralDemoAbout.lblAboutAuthorGui, IG.Neural.Applications.NeuralDemoAbout.lblAboutAuthors, IG.Neural.Applications.NeuralDemoAbout.lblAboutAuthorsIntro, IG.Neural.Applications.NeuralDemoAbout.lblAboutContact, IG.Neural.Applications.NeuralDemoAbout.lblAboutTitle, IG.Neural.Applications.NeuralDemoAbout.lblAboutWeb, IG.Neural.Applications.NeuralDemoAbout.lblAboutWeb_Click(), IG.Neural.Applications.NeuralDemoAbout.lblBrowseHelp, IG.Neural.Applications.NeuralDemoAbout.lblBrowseHelp_Click(), IG.Neural.Applications.NeuralDemoAbout.lblBrowseHome, IG.Neural.Applications.NeuralDemoAbout.lblBrowseHome_Click(), IG.Neural.Applications.NeuralDemoAbout.lblPoweredIGLib, IG.Neural.Applications.NeuralDemoAbout.lblTitle, IG.Neural.Applications.NeuralDemoAbout.pbIGLib, IG.Neural.Applications.NeuralDemoAbout.pnlAbout, IG.Neural.Applications.NeuralDemoAbout.pnlAbout_Paint(), and IG.Neural.Applications.NeuralDemoAbout.pnlIGLib.
GetHelpLocationInExecutableDirectory() [3/3]
virtual string IG.Neural.Applications.NeuralDemoAbout.GetHelpLocationInExecutableDirectory () inline virtual
References IG.Neural.Applications.NeuralDemoAbout.ApplicationName.
BrowseHelp() [2/2]
void IG.Neural.Applications.NeuralDemoAbout.BrowseHelp () inline
References IG.Neural.Applications.NeuralDemoAbout._fadingMessageShowTimeMs, IG.Neural.Applications.NeuralDemoAbout.HelpLocation, IG.Forms.FadingMessage.LaunchedAtMouseCursor, and IG.Forms.FadingMessage.LaunchedInParallelThread.
BrowseWebPage() [2/2]
void IG.Neural.Applications.NeuralDemoAbout.BrowseWebPage () inline
References IG.Neural.Applications.NeuralDemoAbout._fadingMessageShowTimeMs, IG.Neural.Applications.NeuralDemoAbout.HomePage, IG.Forms.FadingMessage.LaunchedAtMouseCursor, and IG.Forms.FadingMessage.LaunchedInParallelThread.
ShowHelp() [2/2]
void IG.Neural.Applications.NeuralDemoAbout.ShowHelp () inline
References IG.Neural.Applications.NeuralDemoAbout.Browser, IG.Neural.Applications.NeuralDemoAbout.HelpLocation, and IG.Forms.BrowserSimpleForm.OpenLocation().
ShowWebPage() [2/2]
void IG.Neural.Applications.NeuralDemoAbout.ShowWebPage () inline
References IG.Neural.Applications.NeuralDemoAbout.Browser, IG.Neural.Applications.NeuralDemoAbout.HomePage, and IG.Forms.BrowserSimpleForm.OpenLocation().
lblAboutWeb_Click() [3/3]
void IG.Neural.Applications.NeuralDemoAbout.lblAboutWeb_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralDemoAbout.lblAboutWeb.
btnHelp_Click() [2/2]
void IG.Neural.Applications.NeuralDemoAbout.btnHelp_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralDemoAbout.ShowHelp().
btnWeb_Click() [3/3]
void IG.Neural.Applications.NeuralDemoAbout.btnWeb_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralDemoAbout.ShowWebPage().
pnlAbout_Paint() [3/3]
void IG.Neural.Applications.NeuralDemoAbout.pnlAbout_Paint (object sender, PaintEventArgs e) inline private
Triggered on each repaint of the panel. can be attemted to make background transparent.
Does not work. Color.FromArgb(25, Color.White); gets the closest to doing something.
lblBrowseHelp_Click() [3/3]
void IG.Neural.Applications.NeuralDemoAbout.lblBrowseHelp_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralDemoAbout.BrowseHelp().
lblBrowseHome_Click() [3/3]
void IG.Neural.Applications.NeuralDemoAbout.lblBrowseHome_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralDemoAbout.BrowseWebPage().
Dispose() [3/3]
override void IG.Neural.Applications.NeuralDemoAbout.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralDemoAbout.components.
InitializeComponent() [3/3]
void IG.Neural.Applications.NeuralDemoAbout.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralDemoAbout.btnHelp, IG.Neural.Applications.NeuralDemoAbout.btnHelp_Click(), IG.Neural.Applications.NeuralDemoAbout.btnWeb, IG.Neural.Applications.NeuralDemoAbout.btnWeb_Click(), IG.Neural.Applications.NeuralDemoAbout.lblAbourContactIntro, IG.Neural.Applications.NeuralDemoAbout.lblAboutAuthorGui, IG.Neural.Applications.NeuralDemoAbout.lblAboutAuthors, IG.Neural.Applications.NeuralDemoAbout.lblAboutAuthorsIntro, IG.Neural.Applications.NeuralDemoAbout.lblAboutContact, IG.Neural.Applications.NeuralDemoAbout.lblAboutTitle, IG.Neural.Applications.NeuralDemoAbout.lblAboutWeb, IG.Neural.Applications.NeuralDemoAbout.lblAboutWeb_Click(), IG.Neural.Applications.NeuralDemoAbout.lblBrowseHelp, IG.Neural.Applications.NeuralDemoAbout.lblBrowseHelp_Click(), IG.Neural.Applications.NeuralDemoAbout.lblBrowseHome, IG.Neural.Applications.NeuralDemoAbout.lblBrowseHome_Click(), IG.Neural.Applications.NeuralDemoAbout.lblPoweredIGLib, IG.Neural.Applications.NeuralDemoAbout.lblTitle, IG.Neural.Applications.NeuralDemoAbout.pbIGLib, IG.Neural.Applications.NeuralDemoAbout.pnlAbout, IG.Neural.Applications.NeuralDemoAbout.pnlAbout_Paint(), and IG.Neural.Applications.NeuralDemoAbout.pnlIGLib.
Member Data Documentation
DefaultHomePageShort
const string IG.Neural.Applications.NeuralDemoAbout.DefaultHomePageShort = "www2.arnes.si/~ljc3m2/igor/software/NeurApp/" static private
Referenced by IG.Neural.Applications.NeuralDemoAbout.NeuralDemoAbout().
_homePageShort
string IG.Neural.Applications.NeuralDemoAbout._homePageShort protected
DefaultHelpLocation
const string IG.Neural.Applications.NeuralDemoAbout.DefaultHelpLocation = "http://www2.arnes.si/~ljc3m2/igor/software/NeurApp/doc/NeurApp_help.html" static private
_helpLocation
string IG.Neural.Applications.NeuralDemoAbout._helpLocation protected
DefaultHelpLocationPdf
const string IG.Neural.Applications.NeuralDemoAbout.DefaultHelpLocationPdf = "http://www2.arnes.si/~ljc3m2/igor/software/NeurApp/doc/NeurApp_help.pdf" static private
_helpLocationPdf
string IG.Neural.Applications.NeuralDemoAbout._helpLocationPdf protected
_browser
BrowserSimpleForm IG.Neural.Applications.NeuralDemoAbout._browser protected
DefaultApplicationName
string IG.Neural.Applications.NeuralDemoAbout.DefaultApplicationName = "NeurApp"
_applicationName
string IG.Neural.Applications.NeuralDemoAbout._applicationName protected
_fadingMessageShowTimeMs
int IG.Neural.Applications.NeuralDemoAbout._fadingMessageShowTimeMs = 1000 protected
Referenced by IG.Neural.Applications.NeuralDemoAbout.BrowseHelp(), IG.Neural.Applications.NeuralDemoAbout.BrowseWebPage(), IG.Neural.Applications.NeuralDemoAbout.HelpBrowse(), IG.Neural.Applications.NeuralDemoAbout.HelpPdf(), and IG.Neural.Applications.NeuralDemoAbout.WebPageBrowse().
components
System ComponentModel IContainer IG.Neural.Applications.NeuralDemoAbout.components = null private
Required designer variable.
Referenced by IG.Neural.Applications.NeuralDemoAbout.Dispose().
lblTitle
System Windows Forms Label IG.Neural.Applications.NeuralDemoAbout.lblTitle private
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
btnHelpHtml
System.Windows.Forms.Button IG.Neural.Applications.NeuralDemoAbout.btnHelpHtml private
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
pnlAbout
System Windows Forms Panel IG.Neural.Applications.NeuralDemoAbout.pnlAbout private
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
lblAboutAuthors
System Windows Forms Label IG.Neural.Applications.NeuralDemoAbout.lblAboutAuthors private
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
lblAboutAuthorsIntro
System Windows Forms Label IG.Neural.Applications.NeuralDemoAbout.lblAboutAuthorsIntro private
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
lblAboutTitle
System Windows Forms Label IG.Neural.Applications.NeuralDemoAbout.lblAboutTitle private
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
lblAboutWeb
System Windows Forms Label IG.Neural.Applications.NeuralDemoAbout.lblAboutWeb private
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent(), IG.Neural.Applications.NeuralDemoAbout.lblAboutWeb_Click(), and IG.Neural.Applications.NeuralDemoAbout.NeuralDemoAbout().
lblAboutContact
System Windows Forms Label IG.Neural.Applications.NeuralDemoAbout.lblAboutContact private
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
lblAbourContactIntro
System Windows Forms Label IG.Neural.Applications.NeuralDemoAbout.lblAbourContactIntro private
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
pbIGLib
System Windows Forms PictureBox IG.Neural.Applications.NeuralDemoAbout.pbIGLib private
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
lblPoweredIGLib
System Windows Forms Label IG.Neural.Applications.NeuralDemoAbout.lblPoweredIGLib private
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
pnlIGLib
System Windows Forms Panel IG.Neural.Applications.NeuralDemoAbout.pnlIGLib private
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
btnWeb
System Windows Forms Button IG.Neural.Applications.NeuralDemoAbout.btnWeb private
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
lblHomeBrowse
System.Windows.Forms.Label IG.Neural.Applications.NeuralDemoAbout.lblHomeBrowse private
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
lblHelpBrowse
System.Windows.Forms.Label IG.Neural.Applications.NeuralDemoAbout.lblHelpBrowse private
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
btnHelpPdf
System.Windows.Forms.Button IG.Neural.Applications.NeuralDemoAbout.btnHelpPdf private
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
btnHelp
System Windows Forms Button IG.Neural.Applications.NeuralDemoAbout.btnHelp private
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
lblAboutAuthorGui
System Windows Forms Label IG.Neural.Applications.NeuralDemoAbout.lblAboutAuthorGui private
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
lblBrowseHome
System Windows Forms Label IG.Neural.Applications.NeuralDemoAbout.lblBrowseHome private
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
lblBrowseHelp
System Windows Forms Label IG.Neural.Applications.NeuralDemoAbout.lblBrowseHelp private
Referenced by IG.Neural.Applications.NeuralDemoAbout.InitializeComponent().
Property Documentation
HomePageShort
string IG.Neural.Applications.NeuralDemoAbout.HomePageShort get protected set
Short version of the application's home page.
HomePage
string IG.Neural.Applications.NeuralDemoAbout.HomePage get
Referenced by IG.Neural.Applications.NeuralDemoAbout.BrowseWebPage(), IG.Neural.Applications.NeuralDemoAbout.ShowWebPage(), IG.Neural.Applications.NeuralDemoAbout.WebPageBrowse(), and IG.Neural.Applications.NeuralDemoAbout.WebPageShow().
HelpLocation
string IG.Neural.Applications.NeuralDemoAbout.HelpLocation get
Location of the help file that can be displayed in a web browser.
Referenced by IG.Neural.Applications.NeuralDemoAbout.BrowseHelp(), IG.Neural.Applications.NeuralDemoAbout.HelpBrowse(), IG.Neural.Applications.NeuralDemoAbout.HelpShow(), and IG.Neural.Applications.NeuralDemoAbout.ShowHelp().
HelpLocationPdf
virtual string IG.Neural.Applications.NeuralDemoAbout.HelpLocationPdf get
Location of the help file that can be displayed in a web browser.
Referenced by IG.Neural.Applications.NeuralDemoAbout.HelpPdf().
Browser
BrowserSimpleForm IG.Neural.Applications.NeuralDemoAbout.Browser get protected
Referenced by IG.Neural.Applications.NeuralDemoAbout.HelpShow(), IG.Neural.Applications.NeuralDemoAbout.ShowHelp(), IG.Neural.Applications.NeuralDemoAbout.ShowWebPage(), and IG.Neural.Applications.NeuralDemoAbout.WebPageShow().
ApplicationName
string IG.Neural.Applications.NeuralDemoAbout.ApplicationName get
Referenced by IG.Neural.Applications.NeuralDemoAbout.GetHelpLocationInExecutableDirectory(), and IG.Neural.Applications.NeuralDemoAbout.GetHelpLocationPdfInExecutableDirectory().
The documentation for this class was generated from the following files:
shelldev/lib/extended/LibNeuralExtForms/FormsExperimental/NeuralApplications/NeuralDemoAbout.cs
shelldev/lib/extended/LibNeuralExtForms/FormsExperimental/NeuralApplications/NeuralDemoAbout.Designer.cs