Doc: IGLib EXTENDED: UsingConfigurationClass.ConfigurationMain Class Reference
UsingConfigurationClass.ConfigurationMain Class Reference
Static Public Member Functions
static void UserMenu ()
Static Private Member Functions
static void Main1 (string[] args)
Member Function Documentation
UserMenu()
static void UsingConfigurationClass.ConfigurationMain.UserMenu () inline static
Referenced by UsingConfigurationClass.ConfigurationMain.Main1().
Main1()
static void UsingConfigurationClass.ConfigurationMain.Main1 (string[] args) inline static private
References UsingConfigurationClass.CreateConfigurationFile(), UsingConfigurationClass.GetConfigurationInformation(), UsingConfigurationClass.GetCustomSection(), UsingConfigurationClass.GetSections(), UsingConfigurationClass.SaveConfigurationFile(), and UsingConfigurationClass.ConfigurationMain.UserMenu().
The documentation for this class was generated from the following file:
igtest/IGLibTestShell/Configuration.cs