Doc: IGLib EXTENDED: IG.Neural.Applications.NeuralApp2D Class Reference
IG.Neural.Applications.NeuralApp2D Class Reference
Public Member Functions
NeuralApp2D ()
NeuralApp2D ()
NeuralApp2D ()
NeuralApp2D ()
NeuralApp2D ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void neuralControl2D1_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void neuralControl2D1_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void neuralControl2D1_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void neuralControl2D1_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void neuralControl2D1_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
NeuralControl2D neuralControl2D1
Constructor & Destructor Documentation
NeuralApp2D() [1/5]
IG.Neural.Applications.NeuralApp2D.NeuralApp2D () inline
References IG.Neural.Applications.NeuralApp2D.InitializeComponent().
NeuralApp2D() [2/5]
IG.Neural.Applications.NeuralApp2D.NeuralApp2D () inline
References IG.Neural.Applications.NeuralApp2D.InitializeComponent().
NeuralApp2D() [3/5]
IG.Neural.Applications.NeuralApp2D.NeuralApp2D () inline
References IG.Neural.Applications.NeuralApp2D.InitializeComponent().
NeuralApp2D() [4/5]
IG.Neural.Applications.NeuralApp2D.NeuralApp2D () inline
References IG.Neural.Applications.NeuralApp2D.InitializeComponent().
NeuralApp2D() [5/5]
IG.Neural.Applications.NeuralApp2D.NeuralApp2D () inline
References IG.Neural.Applications.NeuralApp2D.InitializeComponent().
Member Function Documentation
neuralControl2D1_Load() [1/5]
void IG.Neural.Applications.NeuralApp2D.neuralControl2D1_Load (object sender, EventArgs e) inline private
Referenced by IG.Neural.Applications.NeuralApp2D.InitializeComponent().
Dispose() [1/5]
override void IG.Neural.Applications.NeuralApp2D.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralApp2D.components.
InitializeComponent() [1/5]
void IG.Neural.Applications.NeuralApp2D.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralControl2D.BreakTraining, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Applications.NeuralApp2D.neuralControl2D1, and IG.Neural.Applications.NeuralApp2D.neuralControl2D1_Load().
Referenced by IG.Neural.Applications.NeuralApp2D.NeuralApp2D().
neuralControl2D1_Load() [2/5]
void IG.Neural.Applications.NeuralApp2D.neuralControl2D1_Load (object sender, EventArgs e) inline private
Dispose() [2/5]
override void IG.Neural.Applications.NeuralApp2D.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralApp2D.components.
InitializeComponent() [2/5]
void IG.Neural.Applications.NeuralApp2D.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralControl2D.BreakTraining, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Applications.NeuralApp2D.neuralControl2D1, and IG.Neural.Applications.NeuralApp2D.neuralControl2D1_Load().
neuralControl2D1_Load() [3/5]
void IG.Neural.Applications.NeuralApp2D.neuralControl2D1_Load (object sender, EventArgs e) inline private
Dispose() [3/5]
override void IG.Neural.Applications.NeuralApp2D.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralApp2D.components.
InitializeComponent() [3/5]
void IG.Neural.Applications.NeuralApp2D.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralControl2D.BreakTraining, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Applications.NeuralApp2D.neuralControl2D1, and IG.Neural.Applications.NeuralApp2D.neuralControl2D1_Load().
neuralControl2D1_Load() [4/5]
void IG.Neural.Applications.NeuralApp2D.neuralControl2D1_Load (object sender, EventArgs e) inline private
Dispose() [4/5]
override void IG.Neural.Applications.NeuralApp2D.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralApp2D.components.
InitializeComponent() [4/5]
void IG.Neural.Applications.NeuralApp2D.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralControl2D.BreakTraining, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Applications.NeuralApp2D.neuralControl2D1, and IG.Neural.Applications.NeuralApp2D.neuralControl2D1_Load().
neuralControl2D1_Load() [5/5]
void IG.Neural.Applications.NeuralApp2D.neuralControl2D1_Load (object sender, EventArgs e) inline private
Dispose() [5/5]
override void IG.Neural.Applications.NeuralApp2D.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralApp2D.components.
InitializeComponent() [5/5]
void IG.Neural.Applications.NeuralApp2D.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralControl2D.BreakTraining, IG.Neural.Forms.NeuralControl2D.NeuralApproximator, IG.Neural.Applications.NeuralApp2D.neuralControl2D1, and IG.Neural.Applications.NeuralApp2D.neuralControl2D1_Load().
Member Data Documentation
components
System ComponentModel IContainer IG.Neural.Applications.NeuralApp2D.components = null private
Required designer variable.
Referenced by IG.Neural.Applications.NeuralApp2D.Dispose().
neuralControl2D1
NeuralControl2D IG.Neural.Applications.NeuralApp2D.neuralControl2D1 private
Referenced by IG.Neural.Applications.NeuralApp2D.InitializeComponent().
The documentation for this class was generated from the following files:
shelldev/lib/extended/LibNeuralExtForms/FormsExperimental/NeuralForms/NeuralApp2D.cs
shelldev/lib/extended/LibNeuralExtForms/FormsExperimental/NeuralForms/NeuralApp2D.Designer.cs