Doc: IGLib EXTENDED: ChemicalCompoundDto Class Reference
ChemicalCompoundDto Class Reference
DTO (Data Transfer Objects) for chemical element properties (the ChemicalCompound class). Used to store a state of a chemical element properties object.
Public Member Functions
ChemicalCompoundDto ()
Default constructor, sets IsNull to true.
ChemicalCompoundDto (ChemicalCompound elementProperties)
Constructor, prepares the current DTO for storing a specific chemical element properties object (type ChemicalCompound).
override ChemicalCompound CreateObject ()
Creates and returns a new chemical compound.
Public Member Functions inherited from IG.Lib.SerializationDtoBase< ChemicalCompound, ChemicalCompound >
SerializationDtoBase ()
virtual bool GetNull ()
Returns a flag indicating whether the object represented by the current DTO is null.
virtual void SetNull (bool isNull)
Sets a flag indicating whether the object represented by the current DTO is null.
virtual void CopyFromBase (BaseType obj)
Copies data to the current DTO from an object of type BaseType.
virtual void CopyToBase (ref BaseType obj)
Copies data from the current DTO to an object of the base type. Object is created anew if necessary by using the CreateObject() method.
virtual void CopyFrom (Type obj)
Copies data to the current DTO from an object of type Type.
virtual void CopyTo (ref Type obj)
Copies data from the current DTO to an object of type Type. Object is created anew if necessary by using the CreateObject() method.
virtual void CopyFromObject (object obj)
Copies data to the current DTO from an object of type object. The necessary casts are performed.
virtual void CopyToObject (ref object obj)
Copies data from the current DTO to an object of type object. Object is created anew if necessary by using the CreateObject() method. The necessary casts are performed.
override string ToString ()
Creates and returns string representation of the current DTO (data transfer object).
Protected Member Functions
override void CopyFromPlain (ChemicalCompound compound)
Copies data to the current DTO from a chemical compound object.
override void CopyToPlain (ref ChemicalCompound compound)
Copies data from the current DTO to a chemical compound object.
Protected Member Functions inherited from IG.Lib.SerializationDtoBase< ChemicalCompound, ChemicalCompound >
abstract void CopyFromPlain (BaseType obj)
Copies contents of the specified object to the current DTO (Data Transfer Object).
abstract void CopyToPlain (ref BaseType obj)
Copies contents of the current DTO (Data Transfer Object) to the specified object.
Private Attributes
int NumElements
ChemicalElementQuantityDto[] Elements
Additional Inherited Members
Protected Attributes inherited from IG.Lib.SerializationDtoBase< ChemicalCompound, ChemicalCompound >
bool _isNull
Properties inherited from IG.Lib.SerializationDtoBase< ChemicalCompound, ChemicalCompound >
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Detailed Description
DTO (Data Transfer Objects) for chemical element properties (the ChemicalCompound class). Used to store a state of a chemical element properties object.
Template Parameters
ChemicalCompoundType Type parameter specifying the specific chemical element type for which concrete DTO is designed.
$A Igor Nov09;
Constructor & Destructor Documentation
ChemicalCompoundDto() [1/2]
ChemicalCompoundDto.ChemicalCompoundDto () inline
Default constructor, sets IsNull to true.
References IG.Lib.SerializationDtoBase< ChemicalCompound, ChemicalCompound >.SetNull().
ChemicalCompoundDto() [2/2]
ChemicalCompoundDto.ChemicalCompoundDto (ChemicalCompound elementProperties) inline
Constructor, prepares the current DTO for storing a specific chemical element properties object (type ChemicalCompound).
Parameters
length Element properties object whose data is stored in the current DTO.
References IG.Lib.SerializationDtoBase< ChemicalCompound, ChemicalCompound >.CopyFrom(), and IG.Lib.SerializationDtoBase< ChemicalCompound, ChemicalCompound >.SetNull().
Member Function Documentation
CreateObject()
override ChemicalCompound ChemicalCompoundDto.CreateObject () inline virtual
Creates and returns a new chemical compound.
Implements IG.Lib.SerializationDtoBase< ChemicalCompound, ChemicalCompound >.
Referenced by CopyToPlain().
CopyFromPlain()
override void ChemicalCompoundDto.CopyFromPlain (ChemicalCompound compound) inline protected
Copies data to the current DTO from a chemical compound object.
Parameters
compound Chemical compound object from which data is copied.
References Elements, IG.Physics.ChemicalCompound.GetElements(), NumElements, IG.Physics.ChemicalCompound.NumElements, and IG.Lib.SerializationDtoBase< ChemicalCompound, ChemicalCompound >.SetNull().
CopyToPlain()
override void ChemicalCompoundDto.CopyToPlain (ref ChemicalCompound compound) inline protected
Copies data from the current DTO to a chemical compound object.
Parameters
compound Chemical compound object that data is copied to.
References CreateObject(), IG.Physics.ChemicalElementDtoBase< ChemicalElementType >.CreateObject(), Elements, and IG.Lib.SerializationDtoBase< ChemicalCompound, ChemicalCompound >.GetNull().
Member Data Documentation
NumElements
int ChemicalCompoundDto.NumElements private
Referenced by CopyFromPlain().
Elements
ChemicalElementQuantityDto [] ChemicalCompoundDto.Elements private
Referenced by CopyFromPlain(), and CopyToPlain().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/physics/chemistry/dtos/ChemicalCompoundDto.cs