Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DTRCON Class Reference
DotNumerics.LinearAlgebra.CSLapack.DTRCON Class Reference
– LAPACK routine (version 3.0) – Univ. of Tennessee, Univ. of California Berkeley, NAG Ltd., Courant Institute, Argonne National Lab, and Rice University March 31, 1993
Public Member Functions
DTRCON (LSAME lsame, IDAMAX idamax, DLAMCH dlamch, DLANTR dlantr, DLACON dlacon, DLATRS dlatrs, DRSCL drscl, XERBLA xerbla)
DTRCON ()
void Run (string NORM, string UPLO, string DIAG, int N, double[] A, int offset_a, int LDA, ref double RCOND, ref double[] WORK, int offset_work, ref int[] IWORK, int offset_iwork, ref int INFO)
Private Attributes
LSAME _lsame
IDAMAX _idamax
DLAMCH _dlamch
DLANTR _dlantr
DLACON _dlacon
DLATRS _dlatrs
DRSCL _drscl
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
– LAPACK routine (version 3.0) – Univ. of Tennessee, Univ. of California Berkeley, NAG Ltd., Courant Institute, Argonne National Lab, and Rice University March 31, 1993
Purpose
DTRCON estimates the reciprocal of the condition number of a triangular matrix A, in either the 1-norm or the infinity-norm.
The norm of A is computed and an estimate is obtained for norm(inv(A)), then the reciprocal of the condition number is computed as RCOND = 1 / (norm(A) * norm(inv(A))).
/summary>
Constructor & Destructor Documentation
DTRCON() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DTRCON.DTRCON (LSAME lsame, IDAMAX idamax, DLAMCH dlamch, DLANTR dlantr, DLACON dlacon, DLATRS dlatrs, DRSCL drscl, XERBLA xerbla) inline
DTRCON() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DTRCON.DTRCON () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DTRCON.Run (string NORM, string UPLO, string DIAG, int N, double[] A, int offset_a, int LDA, ref double RCOND, ref double[] WORK, int offset_work, ref int[] IWORK, int offset_iwork, ref int INFO) inline
Purpose
DTRCON estimates the reciprocal of the condition number of a triangular matrix A, in either the 1-norm or the infinity-norm.
The norm of A is computed and an estimate is obtained for norm(inv(A)), then the reciprocal of the condition number is computed as RCOND = 1 / (norm(A) * norm(inv(A))).
/summary>
Parameters
NORM (input) CHARACTER*1 Specifies whether the 1-norm condition number or the infinity-norm condition number is required: = '1' or 'O': 1-norm; = 'I': Infinity-norm. /param>
Parameters
UPLO (input) CHARACTER*1 = 'U': A is upper triangular; = 'L': A is lower triangular. /param>
Parameters
DIAG (input) CHARACTER*1 = 'N': A is non-unit triangular; = 'U': A is unit triangular. /param>
Parameters
N (input) INTEGER The order of the matrix A. N .GE. 0. /param>
Parameters
A (input) DOUBLE PRECISION array, dimension (LDA,N) The triangular matrix A. If UPLO = 'U', the leading N-by-N upper triangular part of the array A contains the upper triangular matrix, and the strictly lower triangular part of A is not referenced. If UPLO = 'L', the leading N-by-N lower triangular part of the array A contains the lower triangular matrix, and the strictly upper triangular part of A is not referenced. If DIAG = 'U', the diagonal elements of A are also not referenced and are assumed to be 1. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,N). /param>
Parameters
RCOND (output) DOUBLE PRECISION The reciprocal of the condition number of the matrix A, computed as RCOND = 1/(norm(A) * norm(inv(A))). /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (3*N) /param>
Parameters
IWORK (workspace) INTEGER array, dimension (N) /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value /param>
References DotNumerics.FortranLibrary.FortranLib.Copy(), DotNumerics.LinearAlgebra.CSLapack.DTRCON.ONE, DotNumerics.LinearAlgebra.CSLapack.IDAMAX.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DRSCL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACON.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANTR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLATRS.Run(), and DotNumerics.LinearAlgebra.CSLapack.DTRCON.ZERO.
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DTRCON._lsame private
_idamax
IDAMAX DotNumerics.LinearAlgebra.CSLapack.DTRCON._idamax private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DTRCON._dlamch private
_dlantr
DLANTR DotNumerics.LinearAlgebra.CSLapack.DTRCON._dlantr private
_dlacon
DLACON DotNumerics.LinearAlgebra.CSLapack.DTRCON._dlacon private
_dlatrs
DLATRS DotNumerics.LinearAlgebra.CSLapack.DTRCON._dlatrs private
_drscl
DRSCL DotNumerics.LinearAlgebra.CSLapack.DTRCON._drscl private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DTRCON._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DTRCON.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTRCON.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DTRCON.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTRCON.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dtrcon.cs