Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DTRMV Class Reference
DotNumerics.LinearAlgebra.CSLapack.DTRMV Class Reference
Public Member Functions
DTRMV (LSAME lsame, XERBLA xerbla)
DTRMV ()
void Run (string UPLO, string TRANS, string DIAG, int N, double[] A, int offset_a, int LDA, ref double[] X, int offset_x, int INCX)
Private Attributes
LSAME _lsame
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E+0
Detailed Description
Purpose
DTRMV performs one of the matrix-vector operations
x := A*x, or x := A'*x,
where x is an n element vector and A is an n by n unit, or non-unit, upper or lower triangular matrix.
Parameters
UPLO - CHARACTER*1. On entry, UPLO specifies whether the matrix is an upper or lower triangular matrix as follows:
UPLO = 'U' or 'u' A is an upper triangular matrix.
UPLO = 'L' or 'l' A is a lower triangular matrix.
Unchanged on exit.
TRANS - CHARACTER*1. On entry, TRANS specifies the operation to be performed as follows:
TRANS = 'N' or 'n' x := A*x.
TRANS = 'T' or 't' x := A'*x.
TRANS = 'C' or 'c' x := A'*x.
Unchanged on exit.
DIAG - CHARACTER*1. On entry, DIAG specifies whether or not A is unit triangular as follows:
DIAG = 'U' or 'u' A is assumed to be unit triangular.
DIAG = 'N' or 'n' A is not assumed to be unit triangular.
Unchanged on exit.
N - INTEGER. On entry, N specifies the order of the matrix A. N must be at least zero. Unchanged on exit.
A - DOUBLE PRECISION array of DIMENSION (LDA, n). Before entry with UPLO = 'U' or 'u', the leading n by n upper triangular part of the array A must contain the upper triangular matrix and the strictly lower triangular part of A is not referenced. Before entry with UPLO = 'L' or 'l', the leading n by n lower triangular part of the array A must contain the lower triangular matrix and the strictly upper triangular part of A is not referenced. Note that when DIAG = 'U' or 'u', the diagonal elements of A are not referenced either, but are assumed to be unity. Unchanged on exit.
LDA - INTEGER. On entry, LDA specifies the first dimension of A as declared in the calling (sub) program. LDA must be at least max(1, n). Unchanged on exit.
X - DOUBLE PRECISION array of dimension at least (1 + (n - 1)*abs(INCX)). Before entry, the incremented array X must contain the n element vector x. On exit, X is overwritten with the tranformed vector x.
INCX - INTEGER. On entry, INCX specifies the increment for the elements of X. INCX must not be zero. Unchanged on exit. /summary>
Constructor & Destructor Documentation
DTRMV() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DTRMV.DTRMV (LSAME lsame, XERBLA xerbla) inline
DTRMV() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DTRMV.DTRMV () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DTRMV.Run (string UPLO, string TRANS, string DIAG, int N, double[] A, int offset_a, int LDA, ref double[] X, int offset_x, int INCX) inline
Purpose
DTRMV performs one of the matrix-vector operations
x := A*x, or x := A'*x,
where x is an n element vector and A is an n by n unit, or non-unit, upper or lower triangular matrix.
Parameters
UPLO - CHARACTER*1. On entry, UPLO specifies whether the matrix is an upper or lower triangular matrix as follows:
UPLO = 'U' or 'u' A is an upper triangular matrix.
UPLO = 'L' or 'l' A is a lower triangular matrix.
Unchanged on exit.
TRANS - CHARACTER*1. On entry, TRANS specifies the operation to be performed as follows:
TRANS = 'N' or 'n' x := A*x.
TRANS = 'T' or 't' x := A'*x.
TRANS = 'C' or 'c' x := A'*x.
Unchanged on exit.
DIAG - CHARACTER*1. On entry, DIAG specifies whether or not A is unit triangular as follows:
DIAG = 'U' or 'u' A is assumed to be unit triangular.
DIAG = 'N' or 'n' A is not assumed to be unit triangular.
Unchanged on exit.
N - INTEGER. On entry, N specifies the order of the matrix A. N must be at least zero. Unchanged on exit.
A - DOUBLE PRECISION array of DIMENSION (LDA, n). Before entry with UPLO = 'U' or 'u', the leading n by n upper triangular part of the array A must contain the upper triangular matrix and the strictly lower triangular part of A is not referenced. Before entry with UPLO = 'L' or 'l', the leading n by n lower triangular part of the array A must contain the lower triangular matrix and the strictly upper triangular part of A is not referenced. Note that when DIAG = 'U' or 'u', the diagonal elements of A are not referenced either, but are assumed to be unity. Unchanged on exit.
LDA - INTEGER. On entry, LDA specifies the first dimension of A as declared in the calling (sub) program. LDA must be at least max(1, n). Unchanged on exit.
X - DOUBLE PRECISION array of dimension at least (1 + (n - 1)*abs(INCX)). Before entry, the incremented array X must contain the n element vector x. On exit, X is overwritten with the tranformed vector x.
INCX - INTEGER. On entry, INCX specifies the increment for the elements of X. INCX must not be zero. Unchanged on exit. /summary>
Parameters
UPLO
CHARACTER*1. On entry, UPLO specifies whether the matrix is an upper or lower triangular matrix as follows:
UPLO = 'U' or 'u' A is an upper triangular matrix.
UPLO = 'L' or 'l' A is a lower triangular matrix.
Unchanged on exit. /param>
Parameters
TRANS
CHARACTER*1. On entry, TRANS specifies the operation to be performed as follows:
TRANS = 'N' or 'n' x := A*x.
TRANS = 'T' or 't' x := A'*x.
TRANS = 'C' or 'c' x := A'*x.
Unchanged on exit. /param>
Parameters
DIAG
CHARACTER*1. On entry, DIAG specifies whether or not A is unit triangular as follows:
DIAG = 'U' or 'u' A is assumed to be unit triangular.
DIAG = 'N' or 'n' A is not assumed to be unit triangular.
Unchanged on exit. /param>
Parameters
N
INTEGER. On entry, N specifies the order of the matrix A. N must be at least zero. Unchanged on exit. /param>
Parameters
A
DOUBLE PRECISION array of DIMENSION (LDA, n). Before entry with UPLO = 'U' or 'u', the leading n by n upper triangular part of the array A must contain the upper triangular matrix and the strictly lower triangular part of A is not referenced. Before entry with UPLO = 'L' or 'l', the leading n by n lower triangular part of the array A must contain the lower triangular matrix and the strictly upper triangular part of A is not referenced. Note that when DIAG = 'U' or 'u', the diagonal elements of A are not referenced either, but are assumed to be unity. Unchanged on exit. /param>
Parameters
LDA
INTEGER. On entry, LDA specifies the first dimension of A as declared in the calling (sub) program. LDA must be at least max(1, n). Unchanged on exit. /param>
Parameters
X := A*x, or x := A'*x, /param>
Parameters
INCX
INTEGER. On entry, INCX specifies the increment for the elements of X. INCX must not be zero. Unchanged on exit.
/param>
References DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), and DotNumerics.LinearAlgebra.CSLapack.DTRMV.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTRTI2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAHR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARZT.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGGLSE.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DTRMV._lsame private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DTRMV._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DTRMV.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTRMV.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dtrmv.cs