Doc: IGLib EXTENDED: alglib.bdsvd Class Reference
alglib.bdsvd Class Reference
Static Public Member Functions
static bool rmatrixbdsvd (ref double[] d, double[] e, int n, bool isupper, bool isfractionalaccuracyrequired, ref double[,] u, int nru, ref double[,] c, int ncc, ref double[,] vt, int ncvt)
static bool bidiagonalsvddecomposition (ref double[] d, double[] e, int n, bool isupper, bool isfractionalaccuracyrequired, ref double[,] u, int nru, ref double[,] c, int ncc, ref double[,] vt, int ncvt)
static bool rmatrixbdsvd (ref double[] d, double[] e, int n, bool isupper, bool isfractionalaccuracyrequired, ref double[,] u, int nru, ref double[,] c, int ncc, ref double[,] vt, int ncvt)
static bool bidiagonalsvddecomposition (ref double[] d, double[] e, int n, bool isupper, bool isfractionalaccuracyrequired, ref double[,] u, int nru, ref double[,] c, int ncc, ref double[,] vt, int ncvt)
Static Private Member Functions
static bool bidiagonalsvddecompositioninternal (ref double[] d, double[] e, int n, bool isupper, bool isfractionalaccuracyrequired, ref double[,] u, int ustart, int nru, ref double[,] c, int cstart, int ncc, ref double[,] vt, int vstart, int ncvt)
static double extsignbdsqr (double a, double b)
static void svd2x2 (double f, double g, double h, ref double ssmin, ref double ssmax)
static void svdv2x2 (double f, double g, double h, ref double ssmin, ref double ssmax, ref double snr, ref double csr, ref double snl, ref double csl)
static bool bidiagonalsvddecompositioninternal (ref double[] d, double[] e, int n, bool isupper, bool isfractionalaccuracyrequired, ref double[,] u, int ustart, int nru, ref double[,] c, int cstart, int ncc, ref double[,] vt, int vstart, int ncvt)
static double extsignbdsqr (double a, double b)
static void svd2x2 (double f, double g, double h, ref double ssmin, ref double ssmax)
static void svdv2x2 (double f, double g, double h, ref double ssmin, ref double ssmax, ref double snr, ref double csr, ref double snl, ref double csl)
Member Function Documentation
rmatrixbdsvd() [1/2]
static bool alglib.bdsvd.rmatrixbdsvd (ref double[] d, double[] e, int n, bool isupper, bool isfractionalaccuracyrequired, ref double u[,], int nru, ref double c[,], int ncc, ref double vt[,], int ncvt) inline static
Referenced by alglib.rmatrixbdsvd(), alglib.testbdsvdunit.testbdsvd(), and alglib.testbdsvdunit.testbdsvdproblem().
bidiagonalsvddecomposition() [1/2]
static bool alglib.bdsvd.bidiagonalsvddecomposition (ref double[] d, double[] e, int n, bool isupper, bool isfractionalaccuracyrequired, ref double u[,], int nru, ref double c[,], int ncc, ref double vt[,], int ncvt) inline static
bidiagonalsvddecompositioninternal() [1/2]
static bool alglib.bdsvd.bidiagonalsvddecompositioninternal (ref double[] d, double[] e, int n, bool isupper, bool isfractionalaccuracyrequired, ref double u[,], int ustart, int nru, ref double c[,], int cstart, int ncc, ref double vt[,], int vstart, int ncvt) inline static private
extsignbdsqr() [1/2]
static double alglib.bdsvd.extsignbdsqr (double a, double b) inline static private
svd2x2() [1/2]
static void alglib.bdsvd.svd2x2 (double f, double g, double h, ref double ssmin, ref double ssmax) inline static private
svdv2x2() [1/2]
static void alglib.bdsvd.svdv2x2 (double f, double g, double h, ref double ssmin, ref double ssmax, ref double snr, ref double csr, ref double snl, ref double csl) inline static private
rmatrixbdsvd() [2/2]
static bool alglib.bdsvd.rmatrixbdsvd (ref double[] d, double[] e, int n, bool isupper, bool isfractionalaccuracyrequired, ref double u[,], int nru, ref double c[,], int ncc, ref double vt[,], int ncvt) inline static
bidiagonalsvddecomposition() [2/2]
static bool alglib.bdsvd.bidiagonalsvddecomposition (ref double[] d, double[] e, int n, bool isupper, bool isfractionalaccuracyrequired, ref double u[,], int nru, ref double c[,], int ncc, ref double vt[,], int ncvt) inline static
bidiagonalsvddecompositioninternal() [2/2]
static bool alglib.bdsvd.bidiagonalsvddecompositioninternal (ref double[] d, double[] e, int n, bool isupper, bool isfractionalaccuracyrequired, ref double u[,], int ustart, int nru, ref double c[,], int cstart, int ncc, ref double vt[,], int vstart, int ncvt) inline static private
extsignbdsqr() [2/2]
static double alglib.bdsvd.extsignbdsqr (double a, double b) inline static private
svd2x2() [2/2]
static void alglib.bdsvd.svd2x2 (double f, double g, double h, ref double ssmin, ref double ssmax) inline static private
svdv2x2() [2/2]
static void alglib.bdsvd.svdv2x2 (double f, double g, double h, ref double ssmin, ref double ssmax, ref double snr, ref double csr, ref double snl, ref double csl) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/linalg.cs