Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGEMV Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGEMV Class Reference
Public Member Functions
DGEMV (LSAME lsame, XERBLA xerbla)
DGEMV ()
void Run (string TRANS, int M, int N, double ALPHA, double[] A, int offset_a, int LDA, double[] X, int offset_x, int INCX, double BETA, ref double[] Y, int offset_y, int INCY)
Private Attributes
LSAME _lsame
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
Purpose
DGEMV performs one of the matrix-vector operations
y := alpha*A*x + beta*y, or y := alpha*A'*x + beta*y,
where alpha and beta are scalars, x and y are vectors and A is an m by n matrix.
Parameters
TRANS - CHARACTER*1. On entry, TRANS specifies the operation to be performed as follows:
TRANS = 'N' or 'n' y := alpha*A*x + beta*y.
TRANS = 'T' or 't' y := alpha*A'*x + beta*y.
TRANS = 'C' or 'c' y := alpha*A'*x + beta*y.
Unchanged on exit.
M - INTEGER. On entry, M specifies the number of rows of the matrix A. M must be at least zero. Unchanged on exit.
N - INTEGER. On entry, N specifies the number of columns of the matrix A. N must be at least zero. Unchanged on exit.
ALPHA - DOUBLE PRECISION. On entry, ALPHA specifies the scalar alpha. Unchanged on exit.
A - DOUBLE PRECISION array of DIMENSION (LDA, n). Before entry, the leading m by n part of the array A must contain the matrix of coefficients. Unchanged on exit.
LDA - INTEGER. On entry, LDA specifies the first dimension of A as declared in the calling (sub) program. LDA must be at least max(1, m). Unchanged on exit.
X - DOUBLE PRECISION array of DIMENSION at least (1 + (n - 1)*abs(INCX)) when TRANS = 'N' or 'n' and at least (1 + (m - 1)*abs(INCX)) otherwise. Before entry, the incremented array X must contain the vector x. Unchanged on exit.
INCX - INTEGER. On entry, INCX specifies the increment for the elements of X. INCX must not be zero. Unchanged on exit.
BETA - DOUBLE PRECISION. On entry, BETA specifies the scalar beta. When BETA is supplied as zero then Y need not be set on input. Unchanged on exit.
Y - DOUBLE PRECISION array of DIMENSION at least (1 + (m - 1)*abs(INCY)) when TRANS = 'N' or 'n' and at least (1 + (n - 1)*abs(INCY)) otherwise. Before entry with BETA non-zero, the incremented array Y must contain the vector y. On exit, Y is overwritten by the updated vector y.
INCY - INTEGER. On entry, INCY specifies the increment for the elements of Y. INCY must not be zero. Unchanged on exit. /summary>
Constructor & Destructor Documentation
DGEMV() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGEMV.DGEMV (LSAME lsame, XERBLA xerbla) inline
DGEMV() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGEMV.DGEMV () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run (string TRANS, int M, int N, double ALPHA, double[] A, int offset_a, int LDA, double[] X, int offset_x, int INCX, double BETA, ref double[] Y, int offset_y, int INCY) inline
Purpose
DGEMV performs one of the matrix-vector operations
y := alpha*A*x + beta*y, or y := alpha*A'*x + beta*y,
where alpha and beta are scalars, x and y are vectors and A is an m by n matrix.
Parameters
TRANS - CHARACTER*1. On entry, TRANS specifies the operation to be performed as follows:
TRANS = 'N' or 'n' y := alpha*A*x + beta*y.
TRANS = 'T' or 't' y := alpha*A'*x + beta*y.
TRANS = 'C' or 'c' y := alpha*A'*x + beta*y.
Unchanged on exit.
M - INTEGER. On entry, M specifies the number of rows of the matrix A. M must be at least zero. Unchanged on exit.
N - INTEGER. On entry, N specifies the number of columns of the matrix A. N must be at least zero. Unchanged on exit.
ALPHA - DOUBLE PRECISION. On entry, ALPHA specifies the scalar alpha. Unchanged on exit.
A - DOUBLE PRECISION array of DIMENSION (LDA, n). Before entry, the leading m by n part of the array A must contain the matrix of coefficients. Unchanged on exit.
LDA - INTEGER. On entry, LDA specifies the first dimension of A as declared in the calling (sub) program. LDA must be at least max(1, m). Unchanged on exit.
X - DOUBLE PRECISION array of DIMENSION at least (1 + (n - 1)*abs(INCX)) when TRANS = 'N' or 'n' and at least (1 + (m - 1)*abs(INCX)) otherwise. Before entry, the incremented array X must contain the vector x. Unchanged on exit.
INCX - INTEGER. On entry, INCX specifies the increment for the elements of X. INCX must not be zero. Unchanged on exit.
BETA - DOUBLE PRECISION. On entry, BETA specifies the scalar beta. When BETA is supplied as zero then Y need not be set on input. Unchanged on exit.
Y - DOUBLE PRECISION array of DIMENSION at least (1 + (m - 1)*abs(INCY)) when TRANS = 'N' or 'n' and at least (1 + (n - 1)*abs(INCY)) otherwise. Before entry with BETA non-zero, the incremented array Y must contain the vector y. On exit, Y is overwritten by the updated vector y.
INCY - INTEGER. On entry, INCY specifies the increment for the elements of Y. INCY must not be zero. Unchanged on exit. /summary>
Parameters
TRANS
CHARACTER*1. On entry, TRANS specifies the operation to be performed as follows:
TRANS = 'N' or 'n' y := alpha*A*x + beta*y.
TRANS = 'T' or 't' y := alpha*A'*x + beta*y.
TRANS = 'C' or 'c' y := alpha*A'*x + beta*y.
Unchanged on exit. /param>
Parameters
M
INTEGER. On entry, M specifies the number of rows of the matrix A. M must be at least zero. Unchanged on exit. /param>
Parameters
N
INTEGER. On entry, N specifies the number of columns of the matrix A. N must be at least zero. Unchanged on exit. /param>
Parameters
ALPHA
DOUBLE PRECISION. On entry, ALPHA specifies the scalar alpha. Unchanged on exit. /param>
Parameters
A
DOUBLE PRECISION array of DIMENSION (LDA, n). Before entry, the leading m by n part of the array A must contain the matrix of coefficients. Unchanged on exit. /param>
Parameters
LDA
INTEGER. On entry, LDA specifies the first dimension of A as declared in the calling (sub) program. LDA must be at least max(1, m). Unchanged on exit. /param>
Parameters
X
DOUBLE PRECISION array of DIMENSION at least (1 + (n - 1)*abs(INCX)) when TRANS = 'N' or 'n' and at least (1 + (m - 1)*abs(INCX)) otherwise. Before entry, the incremented array X must contain the vector x. Unchanged on exit. /param>
Parameters
INCX
INTEGER. On entry, INCX specifies the increment for the elements of X. INCX must not be zero. Unchanged on exit. /param>
Parameters
BETA
DOUBLE PRECISION. On entry, BETA specifies the scalar beta. When BETA is supplied as zero then Y need not be set on input. Unchanged on exit. /param>
Parameters
Y := alpha*A*x + beta*y, or y := alpha*A'*x + beta*y, /param>
Parameters
INCY
INTEGER. On entry, INCY specifies the increment for the elements of Y. INCY must not be zero. Unchanged on exit.
/param>
References DotNumerics.LinearAlgebra.CSLapack.DGEMV.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGEMV.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLARF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFX.Run(), DotNumerics.LinearAlgebra.CSLapack.DGETRI.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARZ.Run(), DotNumerics.LinearAlgebra.CSLapack.DGBTRS.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAEDA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAHR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARZT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQPS.Run(), DotNumerics.LinearAlgebra.CSLapack.DLATRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLABRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGLSE.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGGLM.Run(), DotNumerics.LinearAlgebra.CSLapack.DTREVC.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLALS0.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DGEMV._lsame private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGEMV._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGEMV.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DGEMV.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgemv.cs