Doc: IGLib EXTENDED: IGTest.FindingsRtfTest Class Reference
IGTest.FindingsRtfTest Class Reference
Public Member Functions
FindingsRtfTest ()
FindingsRtfTest ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
DocFindings Findings [get, set]
Findings object used in testing.
Private Member Functions
void btnClose_Click (object sender, EventArgs e)
Exit the form.
void btnClear_Click (object sender, EventArgs e)
Clears rich textbox containing Macro description.
void btnImportInput_Click (object sender, EventArgs e)
Imports findings from the input file whose path is defined in its textbox.
void btnImportOutput_Click (object sender, EventArgs e)
Imports findings from the output file whose path is defined in its textbox.
void btnSaveOutput_Click (object sender, EventArgs e)
Exports findings to the output file whose path is defined in its textbox.
void btnImportInputRtf_Click (object sender, EventArgs e)
Imports findings from the input file whose path is defined in its textbox, and loads macro description in RTF.
void btnImportOutputRtf_Click (object sender, EventArgs e)
Imports findings from the output file whose path is defined in its textbox, and loads macro description in RTF.
void btnSaveOutputRtf_Click (object sender, EventArgs e)
Exports findings to the output file whose path is defined in its textbox; Macro description is stored to XML in RTF.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void btnClose_Click (object sender, EventArgs e)
Exit the form.
void btnClear_Click (object sender, EventArgs e)
Clears rich textbox containing Macro description.
void btnImportInput_Click (object sender, EventArgs e)
Imports findings from the input file whose path is defined in its textbox.
void btnImportOutput_Click (object sender, EventArgs e)
Imports findings from the output file whose path is defined in its textbox.
void btnSaveOutput_Click (object sender, EventArgs e)
Exports findings to the output file whose path is defined in its textbox.
void btnImportInputRtf_Click (object sender, EventArgs e)
Imports findings from the input file whose path is defined in its textbox, and loads macro description in RTF.
void btnImportOutputRtf_Click (object sender, EventArgs e)
Imports findings from the output file whose path is defined in its textbox, and loads macro description in RTF.
void btnSaveOutputRtf_Click (object sender, EventArgs e)
Exports findings to the output file whose path is defined in its textbox; Macro description is stored to XML in RTF.
void txtInputFile_TextChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
DocFindings _findings = null
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Label lblMacro
System.Windows.Forms.RichTextBox rtMacro
System.Windows.Forms.Label lblInputFile
System.Windows.Forms.TextBox txtInputFile
System.Windows.Forms.Label lblOutputFile
System.Windows.Forms.TextBox txtOutputFile
System.Windows.Forms.Button btnImportInput
System.Windows.Forms.Button btnImportOutput
System.Windows.Forms.Button btnSaveOutput
System.Windows.Forms.Button btnClose
System.Windows.Forms.Button btnClear
System.Windows.Forms.Button btnImportInputRtf
System.Windows.Forms.Button btnImportOutputRtf
System.Windows.Forms.Button btnSaveOutputRtf
Constructor & Destructor Documentation
FindingsRtfTest() [1/2]
IGTest.FindingsRtfTest.FindingsRtfTest () inline
References IGTest.FindingsRtfTest.InitializeComponent().
FindingsRtfTest() [2/2]
IGTest.FindingsRtfTest.FindingsRtfTest () inline
References IGTest.FindingsRtfTest.InitializeComponent().
Member Function Documentation
btnClose_Click() [1/2]
void IGTest.FindingsRtfTest.btnClose_Click (object sender, EventArgs e) inline private
Exit the form.
Referenced by IGTest.FindingsRtfTest.InitializeComponent().
btnClear_Click() [1/2]
void IGTest.FindingsRtfTest.btnClear_Click (object sender, EventArgs e) inline private
Clears rich textbox containing Macro description.
References IGTest.FindingsRtfTest.rtMacro.
Referenced by IGTest.FindingsRtfTest.InitializeComponent().
btnImportInput_Click() [1/2]
void IGTest.FindingsRtfTest.btnImportInput_Click (object sender, EventArgs e) inline private
Imports findings from the input file whose path is defined in its textbox.
References IGTest.FindingsRtfTest.Findings, IGTest.FindingsRtfTest.rtMacro, and IGTest.FindingsRtfTest.txtInputFile.
Referenced by IGTest.FindingsRtfTest.InitializeComponent().
btnImportOutput_Click() [1/2]
void IGTest.FindingsRtfTest.btnImportOutput_Click (object sender, EventArgs e) inline private
Imports findings from the output file whose path is defined in its textbox.
References IGTest.FindingsRtfTest.Findings, IGTest.FindingsRtfTest.rtMacro, and IGTest.FindingsRtfTest.txtOutputFile.
Referenced by IGTest.FindingsRtfTest.InitializeComponent().
btnSaveOutput_Click() [1/2]
void IGTest.FindingsRtfTest.btnSaveOutput_Click (object sender, EventArgs e) inline private
Exports findings to the output file whose path is defined in its textbox.
References IGTest.FindingsRtfTest.Findings, IGTest.FindingsRtfTest.rtMacro, and IGTest.FindingsRtfTest.txtOutputFile.
Referenced by IGTest.FindingsRtfTest.InitializeComponent().
btnImportInputRtf_Click() [1/2]
void IGTest.FindingsRtfTest.btnImportInputRtf_Click (object sender, EventArgs e) inline private
Imports findings from the input file whose path is defined in its textbox, and loads macro description in RTF.
References IGTest.FindingsRtfTest.Findings, IGTest.FindingsRtfTest.rtMacro, and IGTest.FindingsRtfTest.txtInputFile.
Referenced by IGTest.FindingsRtfTest.InitializeComponent().
btnImportOutputRtf_Click() [1/2]
void IGTest.FindingsRtfTest.btnImportOutputRtf_Click (object sender, EventArgs e) inline private
Imports findings from the output file whose path is defined in its textbox, and loads macro description in RTF.
References IGTest.FindingsRtfTest.Findings, IGTest.FindingsRtfTest.rtMacro, and IGTest.FindingsRtfTest.txtOutputFile.
Referenced by IGTest.FindingsRtfTest.InitializeComponent().
btnSaveOutputRtf_Click() [1/2]
void IGTest.FindingsRtfTest.btnSaveOutputRtf_Click (object sender, EventArgs e) inline private
Exports findings to the output file whose path is defined in its textbox; Macro description is stored to XML in RTF.
References IGTest.FindingsRtfTest.Findings, IGTest.FindingsRtfTest.rtMacro, and IGTest.FindingsRtfTest.txtOutputFile.
Referenced by IGTest.FindingsRtfTest.InitializeComponent().
Dispose()
override void IGTest.FindingsRtfTest.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IGTest.FindingsRtfTest.components.
InitializeComponent() [1/2]
void IGTest.FindingsRtfTest.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IGTest.FindingsRtfTest.btnClear, IGTest.FindingsRtfTest.btnClear_Click(), IGTest.FindingsRtfTest.btnClose, IGTest.FindingsRtfTest.btnClose_Click(), IGTest.FindingsRtfTest.btnImportInput, IGTest.FindingsRtfTest.btnImportInput_Click(), IGTest.FindingsRtfTest.btnImportInputRtf, IGTest.FindingsRtfTest.btnImportInputRtf_Click(), IGTest.FindingsRtfTest.btnImportOutput, IGTest.FindingsRtfTest.btnImportOutput_Click(), IGTest.FindingsRtfTest.btnImportOutputRtf, IGTest.FindingsRtfTest.btnImportOutputRtf_Click(), IGTest.FindingsRtfTest.btnSaveOutput, IGTest.FindingsRtfTest.btnSaveOutput_Click(), IGTest.FindingsRtfTest.btnSaveOutputRtf, IGTest.FindingsRtfTest.btnSaveOutputRtf_Click(), IGTest.FindingsRtfTest.lblInputFile, IGTest.FindingsRtfTest.lblMacro, IGTest.FindingsRtfTest.lblOutputFile, IGTest.FindingsRtfTest.rtMacro, IGTest.FindingsRtfTest.txtInputFile, and IGTest.FindingsRtfTest.txtOutputFile.
Referenced by IGTest.FindingsRtfTest.FindingsRtfTest().
btnClose_Click() [2/2]
void IGTest.FindingsRtfTest.btnClose_Click (object sender, EventArgs e) inline private
Exit the form.
btnClear_Click() [2/2]
void IGTest.FindingsRtfTest.btnClear_Click (object sender, EventArgs e) inline private
Clears rich textbox containing Macro description.
References IGTest.FindingsRtfTest.rtMacro.
btnImportInput_Click() [2/2]
void IGTest.FindingsRtfTest.btnImportInput_Click (object sender, EventArgs e) inline private
Imports findings from the input file whose path is defined in its textbox.
References IGTest.FindingsRtfTest.Findings, IG.Lib.ParsableXmlObject.Load(), IG.Lib.DocFindings.MacroDescription, IG.Lib.DocFindings.Read(), IGTest.FindingsRtfTest.rtMacro, IGTest.FindingsRtfTest.txtInputFile, and IG.Lib.DocFindings.UsePlainText.
btnImportOutput_Click() [2/2]
void IGTest.FindingsRtfTest.btnImportOutput_Click (object sender, EventArgs e) inline private
Imports findings from the output file whose path is defined in its textbox.
References IGTest.FindingsRtfTest.Findings, IG.Lib.ParsableXmlObject.Load(), IG.Lib.DocFindings.MacroDescription, IG.Lib.DocFindings.Read(), IGTest.FindingsRtfTest.rtMacro, IGTest.FindingsRtfTest.txtOutputFile, and IG.Lib.DocFindings.UsePlainText.
btnSaveOutput_Click() [2/2]
void IGTest.FindingsRtfTest.btnSaveOutput_Click (object sender, EventArgs e) inline private
Exports findings to the output file whose path is defined in its textbox.
References IGTest.FindingsRtfTest.Findings, IG.Lib.DocFindings.MacroDescription, IGTest.FindingsRtfTest.rtMacro, IG.Lib.ParsableXmlObject.Save(), IG.Lib.DocFindings.ToXml(), IGTest.FindingsRtfTest.txtOutputFile, and IG.Lib.DocFindings.UsePlainText.
btnImportInputRtf_Click() [2/2]
void IGTest.FindingsRtfTest.btnImportInputRtf_Click (object sender, EventArgs e) inline private
Imports findings from the input file whose path is defined in its textbox, and loads macro description in RTF.
References IGTest.FindingsRtfTest.Findings, IG.Lib.ParsableXmlObject.Load(), IG.Lib.DocFindings.MacroDescription, IG.Lib.DocFindings.Read(), IGTest.FindingsRtfTest.rtMacro, IGTest.FindingsRtfTest.txtInputFile, and IG.Lib.DocFindings.UsePlainText.
btnImportOutputRtf_Click() [2/2]
void IGTest.FindingsRtfTest.btnImportOutputRtf_Click (object sender, EventArgs e) inline private
Imports findings from the output file whose path is defined in its textbox, and loads macro description in RTF.
References IGTest.FindingsRtfTest.Findings, IG.Lib.ParsableXmlObject.Load(), IG.Lib.DocFindings.MacroDescription, IG.Lib.DocFindings.Read(), IGTest.FindingsRtfTest.rtMacro, IGTest.FindingsRtfTest.txtOutputFile, and IG.Lib.DocFindings.UsePlainText.
btnSaveOutputRtf_Click() [2/2]
void IGTest.FindingsRtfTest.btnSaveOutputRtf_Click (object sender, EventArgs e) inline private
Exports findings to the output file whose path is defined in its textbox; Macro description is stored to XML in RTF.
References IGTest.FindingsRtfTest.Findings, IG.Lib.DocFindings.MacroDescription, IGTest.FindingsRtfTest.rtMacro, IG.Lib.ParsableXmlObject.Save(), IG.Lib.DocFindings.ToXml(), IGTest.FindingsRtfTest.txtOutputFile, and IG.Lib.DocFindings.UsePlainText.
txtInputFile_TextChanged()
void IGTest.FindingsRtfTest.txtInputFile_TextChanged (object sender, EventArgs e) inline private
Referenced by IGTest.FindingsRtfTest.InitializeComponent().
InitializeComponent() [2/2]
void IGTest.FindingsRtfTest.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IGTest.FindingsRtfTest.btnClear, IGTest.FindingsRtfTest.btnClear_Click(), IGTest.FindingsRtfTest.btnClose, IGTest.FindingsRtfTest.btnClose_Click(), IGTest.FindingsRtfTest.btnImportInput, IGTest.FindingsRtfTest.btnImportInput_Click(), IGTest.FindingsRtfTest.btnImportInputRtf, IGTest.FindingsRtfTest.btnImportInputRtf_Click(), IGTest.FindingsRtfTest.btnImportOutput, IGTest.FindingsRtfTest.btnImportOutput_Click(), IGTest.FindingsRtfTest.btnImportOutputRtf, IGTest.FindingsRtfTest.btnImportOutputRtf_Click(), IGTest.FindingsRtfTest.btnSaveOutput, IGTest.FindingsRtfTest.btnSaveOutput_Click(), IGTest.FindingsRtfTest.btnSaveOutputRtf, IGTest.FindingsRtfTest.btnSaveOutputRtf_Click(), IGTest.FindingsRtfTest.lblInputFile, IGTest.FindingsRtfTest.lblMacro, IGTest.FindingsRtfTest.lblOutputFile, IGTest.FindingsRtfTest.rtMacro, IGTest.FindingsRtfTest.txtInputFile, IGTest.FindingsRtfTest.txtInputFile_TextChanged(), and IGTest.FindingsRtfTest.txtOutputFile.
Member Data Documentation
_findings
DocFindings IGTest.FindingsRtfTest._findings = null private
components
System ComponentModel IContainer IGTest.FindingsRtfTest.components = null private
Required designer variable.
Referenced by IGTest.FindingsRtfTest.Dispose().
lblMacro
System Windows Forms Label IGTest.FindingsRtfTest.lblMacro private
Referenced by IGTest.FindingsRtfTest.InitializeComponent().
rtMacro
System Windows Forms RichTextBox IGTest.FindingsRtfTest.rtMacro private
Referenced by IGTest.FindingsRtfTest.btnClear_Click(), IGTest.FindingsRtfTest.btnImportInput_Click(), IGTest.FindingsRtfTest.btnImportInputRtf_Click(), IGTest.FindingsRtfTest.btnImportOutput_Click(), IGTest.FindingsRtfTest.btnImportOutputRtf_Click(), IGTest.FindingsRtfTest.btnSaveOutput_Click(), IGTest.FindingsRtfTest.btnSaveOutputRtf_Click(), and IGTest.FindingsRtfTest.InitializeComponent().
lblInputFile
System Windows Forms Label IGTest.FindingsRtfTest.lblInputFile private
Referenced by IGTest.FindingsRtfTest.InitializeComponent().
txtInputFile
System Windows Forms TextBox IGTest.FindingsRtfTest.txtInputFile private
Referenced by IGTest.FindingsRtfTest.btnImportInput_Click(), IGTest.FindingsRtfTest.btnImportInputRtf_Click(), and IGTest.FindingsRtfTest.InitializeComponent().
lblOutputFile
System Windows Forms Label IGTest.FindingsRtfTest.lblOutputFile private
Referenced by IGTest.FindingsRtfTest.InitializeComponent().
txtOutputFile
System Windows Forms TextBox IGTest.FindingsRtfTest.txtOutputFile private
Referenced by IGTest.FindingsRtfTest.btnImportOutput_Click(), IGTest.FindingsRtfTest.btnImportOutputRtf_Click(), IGTest.FindingsRtfTest.btnSaveOutput_Click(), IGTest.FindingsRtfTest.btnSaveOutputRtf_Click(), and IGTest.FindingsRtfTest.InitializeComponent().
btnImportInput
System Windows Forms Button IGTest.FindingsRtfTest.btnImportInput private
Referenced by IGTest.FindingsRtfTest.InitializeComponent().
btnImportOutput
System Windows Forms Button IGTest.FindingsRtfTest.btnImportOutput private
Referenced by IGTest.FindingsRtfTest.InitializeComponent().
btnSaveOutput
System Windows Forms Button IGTest.FindingsRtfTest.btnSaveOutput private
Referenced by IGTest.FindingsRtfTest.InitializeComponent().
btnClose
System Windows Forms Button IGTest.FindingsRtfTest.btnClose private
Referenced by IGTest.FindingsRtfTest.InitializeComponent().
btnClear
System Windows Forms Button IGTest.FindingsRtfTest.btnClear private
Referenced by IGTest.FindingsRtfTest.InitializeComponent().
btnImportInputRtf
System Windows Forms Button IGTest.FindingsRtfTest.btnImportInputRtf private
Referenced by IGTest.FindingsRtfTest.InitializeComponent().
btnImportOutputRtf
System Windows Forms Button IGTest.FindingsRtfTest.btnImportOutputRtf private
Referenced by IGTest.FindingsRtfTest.InitializeComponent().
btnSaveOutputRtf
System Windows Forms Button IGTest.FindingsRtfTest.btnSaveOutputRtf private
Referenced by IGTest.FindingsRtfTest.InitializeComponent().
Property Documentation
Findings
DocFindings IGTest.FindingsRtfTest.Findings get set
Findings object used in testing.
Referenced by IGTest.FindingsRtfTest.btnImportInput_Click(), IGTest.FindingsRtfTest.btnImportInputRtf_Click(), IGTest.FindingsRtfTest.btnImportOutput_Click(), IGTest.FindingsRtfTest.btnImportOutputRtf_Click(), IGTest.FindingsRtfTest.btnSaveOutput_Click(), and IGTest.FindingsRtfTest.btnSaveOutputRtf_Click().
The documentation for this class was generated from the following files:
igtest/tmp_prem/prlab/IGTest/FindingsRtfTest.cs
igtest/tmp_prem/prlab/IGTest/FindingsRtfTest.Designer.cs