Doc: IGLib EXTENDED: IG.MPetekLib.Application.Scripts.LinearOscillator._04PlotAtanModified Class Reference
IG.MPetekLib.Application.Scripts.LinearOscillator._04PlotAtanModified Class Reference
Static Public Member Functions
static void Run (string[] arguments)
Nariše nestandardni arctan(x).
Member Function Documentation
Run()
static void IG.MPetekLib.Application.Scripts.LinearOscillator._04PlotAtanModified.Run (string[] arguments) inline static
Nariše nestandardni arctan(x).
References IG.MPetekLib.Algorithms.Plotting.PlotHQ.Plotter, IG.Gr.PlotterZedGraph.SetBounds(), IG.MPetekLib.Algorithms.Plotting.PlotHQ.ShowPlot(), IG.Gr.PlotterZedGraph.Title, IG.MPetekLib.Algorithms.Plotting.PlotHQ.Window, IG.Gr.PlotterZedGraph.XAxisScaleFont, IG.Gr.PlotterZedGraph.YAxis, and IG.Gr.PlotterZedGraph.YAxisScaleFont.
Referenced by IG.Script.AppMarkoPetek.App04PlotAtanModified().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/Guest_Marko_Petek_Lib/application/scripts/LinearOscillator/04PlotAtanModified.cs