Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGETRF Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGETRF Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGETRF (DGEMM dgemm, DGETF2 dgetf2, DLASWP dlaswp, DTRSM dtrsm, XERBLA xerbla, ILAENV ilaenv)
DGETRF ()
void Run (int M, int N, ref double[] A, int offset_a, int LDA, ref int[] IPIV, int offset_ipiv, ref int INFO)
Private Attributes
DGEMM _dgemm
DGETF2 _dgetf2
DLASWP _dlaswp
DTRSM _dtrsm
XERBLA _xerbla
ILAENV _ilaenv
Static Private Attributes
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGETRF computes an LU factorization of a general M-by-N matrix A using partial pivoting with row interchanges.
The factorization has the form A = P * L * U where P is a permutation matrix, L is lower triangular with unit diagonal elements (lower trapezoidal if m .GT. n), and U is upper triangular (upper trapezoidal if m .LT. n).
This is the right-looking Level 3 BLAS version of the algorithm.
/summary>
Constructor & Destructor Documentation
DGETRF() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGETRF.DGETRF (DGEMM dgemm, DGETF2 dgetf2, DLASWP dlaswp, DTRSM dtrsm, XERBLA xerbla, ILAENV ilaenv) inline
DGETRF() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGETRF.DGETRF () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGETRF.Run (int M, int N, ref double[] A, int offset_a, int LDA, ref int[] IPIV, int offset_ipiv, ref int INFO) inline
Purpose
DGETRF computes an LU factorization of a general M-by-N matrix A using partial pivoting with row interchanges.
The factorization has the form A = P * L * U where P is a permutation matrix, L is lower triangular with unit diagonal elements (lower trapezoidal if m .GT. n), and U is upper triangular (upper trapezoidal if m .LT. n).
This is the right-looking Level 3 BLAS version of the algorithm.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the M-by-N matrix to be factored. On exit, the factors L and U from the factorization A = P*L*U; the unit diagonal elements of L are not stored. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
IPIV (output) INTEGER array, dimension (min(M,N)) The pivot indices; for 1 .LE. i .LE. min(M,N), row i of the matrix was interchanged with row IPIV(i). /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value .GT. 0: if INFO = i, U(i,i) is exactly zero. The factorization has been completed, but the factor U is exactly singular, and division by zero will occur if it is used to solve a system of equations. /param>
References DotNumerics.LinearAlgebra.CSLapack.DGETRF.ONE, DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASWP.Run(), DotNumerics.LinearAlgebra.CSLapack.DGETF2.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), and DotNumerics.LinearAlgebra.CSLapack.DTRSM.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGESV.Run().
Member Data Documentation
_dgemm
DGEMM DotNumerics.LinearAlgebra.CSLapack.DGETRF._dgemm private
_dgetf2
DGETF2 DotNumerics.LinearAlgebra.CSLapack.DGETRF._dgetf2 private
_dlaswp
DLASWP DotNumerics.LinearAlgebra.CSLapack.DGETRF._dlaswp private
_dtrsm
DTRSM DotNumerics.LinearAlgebra.CSLapack.DGETRF._dtrsm private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGETRF._xerbla private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DGETRF._ilaenv private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGETRF.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGETRF.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgetrf.cs