Doc: IGLib EXTENDED: NUnit.Engine.Services.NUnit3XmlResultWriter Class Reference
NUnit.Engine.Services.NUnit3XmlResultWriter Class Reference
NUnit3XmlResultWriter is responsible for writing the results of a test to a file in NUnit 3.0 format.
Public Member Functions
void CheckWritability (string outputPath)
Checks if the output is writable by creating a stub result file. If the output is not writable, this method should throw an exception.
void WriteResultFile (XmlNode resultNode, string outputPath)
Writes result to the specified output path.
void WriteResultFile (XmlNode resultNode, TextWriter writer)
Writes result to a TextWriter.
Private Member Functions
XmlNode GetStubResult ()
Detailed Description
NUnit3XmlResultWriter is responsible for writing the results of a test to a file in NUnit 3.0 format.
Member Function Documentation
CheckWritability()
void NUnit.Engine.Services.NUnit3XmlResultWriter.CheckWritability (string outputPath) inline
Checks if the output is writable by creating a stub result file. If the output is not writable, this method should throw an exception.
Parameters
outputPath
Implements NUnit.Engine.Extensibility.IResultWriter.
References NUnit.Engine.Services.NUnit3XmlResultWriter.GetStubResult(), and NUnit.Engine.Services.NUnit3XmlResultWriter.WriteResultFile().
WriteResultFile() [1/2]
void NUnit.Engine.Services.NUnit3XmlResultWriter.WriteResultFile (XmlNode resultNode, string outputPath) inline
Writes result to the specified output path.
Parameters
resultNode XmlNode for the result
outputPath Path to which it should be written
Implements NUnit.Engine.Extensibility.IResultWriter.
Referenced by NUnit.Engine.Services.NUnit3XmlResultWriter.CheckWritability().
WriteResultFile() [2/2]
void NUnit.Engine.Services.NUnit3XmlResultWriter.WriteResultFile (XmlNode resultNode, TextWriter writer) inline
Writes result to a TextWriter.
Parameters
resultNode XmlNode for the result
writer TextWriter to which it should be written
Implements NUnit.Engine.Extensibility.IResultWriter.
GetStubResult()
XmlNode NUnit.Engine.Services.NUnit3XmlResultWriter.GetStubResult () inline private
Referenced by NUnit.Engine.Services.NUnit3XmlResultWriter.CheckWritability().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Services/ResultWriters/NUnit3XmlResultWriter.cs