Doc: IGLib EXTENDED: IG.Forms.VectorFunctionScriptControl Class Reference
IG.Forms.VectorFunctionScriptControl Class Reference
Public Member Functions
VectorFunctionScriptControl ()
Constructs and initializes the vector function script control.
void CopyDataFromController ()
Copies data from the internal DTO to the current control.
void SynchronizeData (bool syncParameterNames=false, bool syncFunctionNames=true)
Synchronizes data for the current vector function definition.
string CreateFunctonSummary ()
VectorFunctionScriptControl ()
Constructs and initializes the vector function script control.
void CopyDataFromController ()
Copies data from the internal DTO to the current control.
void SynchronizeData (bool syncParameterNames=false, bool syncFunctionNames=true)
Synchronizes data for the current vector function definition.
string CreateFunctonSummary ()
VectorFunctionScriptControl ()
Constructs and initializes the vector function script control.
void CopyDataFromController ()
Copies data from the internal DTO to the current control.
void SynchronizeData (bool syncParameterNames=false, bool syncFunctionNames=true)
Synchronizes data for the current vector function definition.
string CreateFunctonSummary ()
VectorFunctionScriptControl ()
Constructs and initializes the vector function script control.
void CopyDataFromController ()
Copies data from the internal DTO to the current control.
void SynchronizeData (bool syncParameterNames=false, bool syncFunctionNames=true)
Synchronizes data for the current vector function definition.
string CreateFunctonSummary ()
Protected Member Functions
string GetFunctionSignature ()
Returns function signature created from the data.
override void Dispose (bool disposing)
Clean up any resources being used.
string GetFunctionSignature ()
Returns function signature created from the data.
override void Dispose (bool disposing)
Clean up any resources being used.
string GetFunctionSignature ()
Returns function signature created from the data.
override void Dispose (bool disposing)
Clean up any resources being used.
string GetFunctionSignature ()
Returns function signature created from the data.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
string ScalarFunctionNotDefinedString = "<< not defined >>"
Properties
IG.Lib.IReporter Reporter [get]
string FunctionNameTitleNormal [get, set]
Normal text of the label that introduces function name input box.
string FunctionNameTitleModified [get, set]
Normal text of the label that introduces function name input box.
VectorFunctionScriptController FunctionController [get, set]
IVectorFunction Function [get]
Gets the function generated according to the function definition contained in this control and stored in FunctionController.
virtual string[] InitialScalarFunctionDefinitionStrings [get, set]
This property contains initial definitions of scalar functions (i.e.their values defined in terms of parameters). If defined then these definitions are asigned in initialization.
bool HasUnsavedChanges [get, set, protected set]
Whether the current function definition has unsaved changes.
bool HasChildUnsavedChanges [get, set]
Indicates whether child control (of type ScalarFunctionScriptControl) has unsaved changes.
int CurrentScalarFunctionIndex [get, set]
Gets or sets index of the current scalar funciton that is worked on.
ScalarFunctionScriptController?? CurrentScalarFunctionController [get, set]
Scalar function controller that represents the element of the vector function that is currently edited.
bool IsLoaderConsistent [get, protected set]
Whether function loader is in consistent state.
string FunctionName [get, set]
Name of the function.
string FunctionDescription [get, set]
int NumParameters [get, set]
Gets or sets number of parameters of the represented vector function.
int NumValues [get, set]
Gets or sets number of values of the represented vector function (i.e., dimension of its codomain).
string[] ParameterNames [get, set]
Names of function parameters.
string[] FunctionNames [get, set]
Names of scalar function components that define individual values of the represented vector function.
InputOutputDataDefiniton DataDefinition [get, set]
Definition of input and output data for the represented scalar function.
FileSelector FileSelector [get]
GUI component for seclecting files.
bool PrepareStandardDefinitions [get, set]
Private Member Functions
void CopyDataToController ()
Copies data from the current control to the internal function DTO.
void txtFunctionName_Validated (object sender, EventArgs e)
void txtFunctionDescription_Validated (object sender, EventArgs e)
void txtParameterNames_Validated (object sender, EventArgs e)
void txtFunctionNames_Validated (object sender, EventArgs e)
void numNumParameters_Validated (object sender, EventArgs e)
void numNumFunctions_Validated (object sender, EventArgs e)
void numCurrentFunction_ValueChanged (object sender, EventArgs e)
void numCurrentFunction_Validated (object sender, EventArgs e)
void btnCreateFunction_Click (object sender, EventArgs e)
void btnSummary_Click (object sender, EventArgs e)
void btnValueCalculator_Click (object sender, EventArgs e)
void btnPlot1d_Click (object sender, EventArgs e)
Launches 1D parametric plots of the function defined in this control.
void btnPlot2d_Click (object sender, EventArgs e)
Launches 2D parametric plots of the function defined in this control.
void btnSave_Click (object sender, EventArgs e)
Saves the current fucntion definition to a JSON file.
void btnLoad_Click (object sender, EventArgs e)
Loads vector funcition definition from a file.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void CopyDataToController ()
Copies data from the current control to the internal function DTO.
void txtFunctionName_Validated (object sender, EventArgs e)
void txtFunctionDescription_Validated (object sender, EventArgs e)
void txtParameterNames_Validated (object sender, EventArgs e)
void txtFunctionNames_Validated (object sender, EventArgs e)
void numNumParameters_Validated (object sender, EventArgs e)
void numNumFunctions_Validated (object sender, EventArgs e)
void numCurrentFunction_ValueChanged (object sender, EventArgs e)
void numCurrentFunction_Validated (object sender, EventArgs e)
void btnCreateFunction_Click (object sender, EventArgs e)
void btnSummary_Click (object sender, EventArgs e)
void btnValueCalculator_Click (object sender, EventArgs e)
void btnPlot1d_Click (object sender, EventArgs e)
Launches 1D parametric plots of the function defined in this control.
void btnPlot2d_Click (object sender, EventArgs e)
Launches 2D parametric plots of the function defined in this control.
void btnSave_Click (object sender, EventArgs e)
Saves the current fucntion definition to a JSON file.
void btnLoad_Click (object sender, EventArgs e)
Loads vector funcition definition from a file.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void CopyDataToController ()
Copies data from the current control to the internal function DTO.
void txtFunctionName_Validated (object sender, EventArgs e)
void txtFunctionDescription_Validated (object sender, EventArgs e)
void txtParameterNames_Validated (object sender, EventArgs e)
void txtFunctionNames_Validated (object sender, EventArgs e)
void numNumParameters_Validated (object sender, EventArgs e)
void numNumFunctions_Validated (object sender, EventArgs e)
void numCurrentFunction_ValueChanged (object sender, EventArgs e)
void numCurrentFunction_Validated (object sender, EventArgs e)
void btnCreateFunction_Click (object sender, EventArgs e)
void btnSummary_Click (object sender, EventArgs e)
void btnValueCalculator_Click (object sender, EventArgs e)
void btnPlot1d_Click (object sender, EventArgs e)
Launches 1D parametric plots of the function defined in this control.
void btnPlot2d_Click (object sender, EventArgs e)
Launches 2D parametric plots of the function defined in this control.
void btnSave_Click (object sender, EventArgs e)
Saves the current fucntion definition to a JSON file.
void btnLoad_Click (object sender, EventArgs e)
Loads vector funcition definition from a file.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void CopyDataToController ()
Copies data from the current control to the internal function DTO.
void txtFunctionName_Validated (object sender, EventArgs e)
void txtFunctionDescription_Validated (object sender, EventArgs e)
void txtParameterNames_Validated (object sender, EventArgs e)
void txtFunctionNames_Validated (object sender, EventArgs e)
void numNumParameters_Validated (object sender, EventArgs e)
void numNumFunctions_Validated (object sender, EventArgs e)
void numCurrentFunction_ValueChanged (object sender, EventArgs e)
void numCurrentFunction_Validated (object sender, EventArgs e)
void btnCreateFunction_Click (object sender, EventArgs e)
void btnSummary_Click (object sender, EventArgs e)
void btnValueCalculator_Click (object sender, EventArgs e)
void btnPlot1d_Click (object sender, EventArgs e)
Launches 1D parametric plots of the function defined in this control.
void btnPlot2d_Click (object sender, EventArgs e)
Launches 2D parametric plots of the function defined in this control.
void btnSave_Click (object sender, EventArgs e)
Saves the current fucntion definition to a JSON file.
void btnLoad_Click (object sender, EventArgs e)
Loads vector funcition definition from a file.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
string _functionNameTitleNormal = "Function Name: "
string _functionNameTitleModified = "Function Name: (*)"
VectorFunctionScriptController _functionController
string[] _initialScalarFunctionDefinitionStrings
bool _hasUnsavedChanges = false
int _currentScalarFunctionIndex = 0
ScalarFunctionScriptController _currentScalarFunctionController = null
bool _isLoaderConsistent = false
InputOutputDataDefiniton _dataDefinition = null
bool _prepareStandardDefinitions = true
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Panel pnlVector
System.Windows.Forms.Label label1
System.Windows.Forms.Label lblCurrentFunction
System.Windows.Forms.Panel pnlOuter
System.Windows.Forms.NumericUpDown numCurrentFunction
System.Windows.Forms.Label lblTitle
System.Windows.Forms.NumericUpDown numNumFunctions
System.Windows.Forms.Label lblCurrentFunctionLabelTitle
System.Windows.Forms.NumericUpDown numNumParameters
System.Windows.Forms.Label lblNumParameters
System.Windows.Forms.Label lblParameterNames
System.Windows.Forms.Panel pnlDimensions
System.Windows.Forms.Label lblCurrentFunctionName
System.Windows.Forms.Label lblFunctionNames
System.Windows.Forms.Panel pnlFunctionNames
System.Windows.Forms.TextBox txtFunctionNames
System.Windows.Forms.Panel pnlParameterNames
System.Windows.Forms.TextBox txtParameterNames
IG.Forms.ScalarFunctionScriptControl scalarFunctionScriptControl1
System.Windows.Forms.Panel pnlButtons
System.Windows.Forms.Button btnCreateFunction
System.Windows.Forms.Button btnValueCalculator
System.Windows.Forms.Button btnLoad
System.Windows.Forms.Button btnSave
System.Windows.Forms.Button btnSummary
System.Windows.Forms.Panel pnlPlotButtons
System.Windows.Forms.Button btnPlot1d
System.Windows.Forms.Button btnPlot2d
System.Windows.Forms.Panel pnlFunctionDescription
System.Windows.Forms.TextBox txtFunctionDescription
System.Windows.Forms.Label lblFunctionDescription
System.Windows.Forms.Panel pnlFunctionName
System.Windows.Forms.TextBox txtFunctionName
System.Windows.Forms.Label lblFunctionName
Constructor & Destructor Documentation
VectorFunctionScriptControl() [1/4]
IG.Forms.VectorFunctionScriptControl.VectorFunctionScriptControl () inline
Constructs and initializes the vector function script control.
References IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionIndex, IG.Forms.VectorFunctionScriptControl.FunctionNameTitleNormal, IG.Forms.VectorFunctionScriptControl.HasChildUnsavedChanges, IG.Forms.VectorFunctionScriptControl.HasUnsavedChanges, IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, IG.Forms.VectorFunctionScriptControl.InitializeComponent(), IG.Forms.VectorFunctionScriptControl.lblCurrentFunctionName, IG.Forms.VectorFunctionScriptControl.lblFunctionName, IG.Forms.VectorFunctionScriptControl.ScalarFunctionNotDefinedString, IG.Forms.VectorFunctionScriptControl.scalarFunctionScriptControl1, IG.Forms.VectorFunctionScriptControl.SynchronizeData(), and IG.Forms.ScalarFunctionScriptControl.VectorFunctionControl.
VectorFunctionScriptControl() [2/4]
IG.Forms.VectorFunctionScriptControl.VectorFunctionScriptControl () inline
Constructs and initializes the vector function script control.
References IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionIndex, IG.Forms.VectorFunctionScriptControl.HasUnsavedChanges, IG.Forms.VectorFunctionScriptControl.InitializeComponent(), IG.Forms.VectorFunctionScriptControl.lblCurrentFunctionName, IG.Forms.VectorFunctionScriptControl.ScalarFunctionNotDefinedString, and IG.Forms.VectorFunctionScriptControl.SynchronizeData().
VectorFunctionScriptControl() [3/4]
IG.Forms.VectorFunctionScriptControl.VectorFunctionScriptControl () inline
Constructs and initializes the vector function script control.
References IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionIndex, IG.Forms.VectorFunctionScriptControl.FunctionNameTitleNormal, IG.Forms.VectorFunctionScriptControl.HasChildUnsavedChanges, IG.Forms.VectorFunctionScriptControl.HasUnsavedChanges, IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, IG.Forms.VectorFunctionScriptControl.InitializeComponent(), IG.Forms.VectorFunctionScriptControl.lblCurrentFunctionName, IG.Forms.VectorFunctionScriptControl.lblFunctionName, IG.Forms.VectorFunctionScriptControl.ScalarFunctionNotDefinedString, IG.Forms.VectorFunctionScriptControl.scalarFunctionScriptControl1, IG.Forms.VectorFunctionScriptControl.SynchronizeData(), and IG.Forms.ScalarFunctionScriptControl.VectorFunctionControl.
VectorFunctionScriptControl() [4/4]
IG.Forms.VectorFunctionScriptControl.VectorFunctionScriptControl () inline
Constructs and initializes the vector function script control.
References IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionIndex, IG.Forms.VectorFunctionScriptControl.FunctionNameTitleNormal, IG.Forms.VectorFunctionScriptControl.HasChildUnsavedChanges, IG.Forms.VectorFunctionScriptControl.HasUnsavedChanges, IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, IG.Forms.VectorFunctionScriptControl.InitializeComponent(), IG.Forms.VectorFunctionScriptControl.lblCurrentFunctionName, IG.Forms.VectorFunctionScriptControl.lblFunctionName, IG.Forms.VectorFunctionScriptControl.ScalarFunctionNotDefinedString, IG.Forms.VectorFunctionScriptControl.scalarFunctionScriptControl1, IG.Forms.VectorFunctionScriptControl.SynchronizeData(), and IG.Forms.ScalarFunctionScriptControl.VectorFunctionControl.
Member Function Documentation
CopyDataToController() [1/4]
void IG.Forms.VectorFunctionScriptControl.CopyDataToController () inline private
Copies data from the current control to the internal function DTO.
References IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.ConvertParameterNamesToArray(), IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.Description, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.FunctionNames, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.Name, IG.Forms.VectorFunctionScriptControl.numNumFunctions, IG.Forms.VectorFunctionScriptControl.numNumParameters, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.NumParameters, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.NumValues, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.ParameterNames, IG.Forms.VectorFunctionScriptControl.txtFunctionDescription, IG.Forms.VectorFunctionScriptControl.txtFunctionName, IG.Forms.VectorFunctionScriptControl.txtFunctionNames, and IG.Forms.VectorFunctionScriptControl.txtParameterNames.
CopyDataFromController() [1/4]
void IG.Forms.VectorFunctionScriptControl.CopyDataFromController () inline
Copies data from the internal DTO to the current control.
References IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.Description, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetFunctionsString(), IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetParametersString(), IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.Name, IG.Forms.VectorFunctionScriptControl.numNumFunctions, IG.Forms.VectorFunctionScriptControl.numNumParameters, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.NumParameters, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.NumValues, IG.Forms.VectorFunctionScriptControl.txtFunctionDescription, IG.Forms.VectorFunctionScriptControl.txtFunctionName, IG.Forms.VectorFunctionScriptControl.txtFunctionNames, and IG.Forms.VectorFunctionScriptControl.txtParameterNames.
Referenced by IG.Forms.VectorFunctionScriptControl.SynchronizeData().
SynchronizeData() [1/4]
void IG.Forms.VectorFunctionScriptControl.SynchronizeData (bool syncParameterNames = false, bool syncFunctionNames = true) inline
Synchronizes data for the current vector function definition.
This method checks number of parameters and number of funcion values, then goes through all scalar funciton elemennts and checks if their data is allocated and consistent. It also takes care that data for the currently edited scalar function is updated according to the true state.
Parameters
syncParameterNames If true then parameterr names are also synchroniized.
syncFunctionNames If true then function names are also synchronized.
References IG.Forms.VectorFunctionScriptControl.CopyDataFromController(), IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionController, IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionIndex, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.FunctionNames, IG.Forms.VectorFunctionScriptControl.lblCurrentFunctionName, IG.Forms.VectorFunctionScriptControl.NumValues, IG.Forms.VectorFunctionScriptControl.ScalarFunctionNotDefinedString, and IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.SynchronizeData().
Referenced by IG.Forms.VectorFunctionScriptControl.VectorFunctionScriptControl(), and IG.Forms.VectorFunctionScriptForm.VectorFunctionScriptForm().
GetFunctionSignature() [1/4]
string IG.Forms.VectorFunctionScriptControl.GetFunctionSignature () inline protected
Returns function signature created from the data.
References IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.FunctionName, IG.Lib.UtilStr.GetParametersStringPlain(), and IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.ParameterNames.
CreateFunctonSummary() [1/4]
string IG.Forms.VectorFunctionScriptControl.CreateFunctonSummary () inline
References IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.FunctionName, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetFunctionsString(), IG.Lib.UtilStr.GetParametersStringPlain(), IG.Forms.VectorFunctionScriptControl.NumValues, IG.Forms.VectorFunctionScriptControl.ParameterNames, IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
Referenced by IG.Forms.VectorFunctionScriptControl.btnSummary_Click().
txtFunctionName_Validated() [1/4]
void IG.Forms.VectorFunctionScriptControl.txtFunctionName_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.FunctionName, and IG.Forms.VectorFunctionScriptControl.txtFunctionName.
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
txtFunctionDescription_Validated() [1/4]
void IG.Forms.VectorFunctionScriptControl.txtFunctionDescription_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.FunctionDescription, and IG.Forms.VectorFunctionScriptControl.txtFunctionDescription.
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
txtParameterNames_Validated() [1/4]
void IG.Forms.VectorFunctionScriptControl.txtParameterNames_Validated (object sender, EventArgs e) inline private
References IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.ConvertParameterNamesToArray(), IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.ParameterNames, and IG.Forms.VectorFunctionScriptControl.txtParameterNames.
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
txtFunctionNames_Validated() [1/4]
void IG.Forms.VectorFunctionScriptControl.txtFunctionNames_Validated (object sender, EventArgs e) inline private
References IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.ConvertParameterNamesToArray(), IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.FunctionNames, and IG.Forms.VectorFunctionScriptControl.txtFunctionNames.
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
numNumParameters_Validated() [1/4]
void IG.Forms.VectorFunctionScriptControl.numNumParameters_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.numNumParameters, and IG.Forms.VectorFunctionScriptControl.NumParameters.
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
numNumFunctions_Validated() [1/4]
void IG.Forms.VectorFunctionScriptControl.numNumFunctions_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.numNumFunctions, and IG.Forms.VectorFunctionScriptControl.NumValues.
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
numCurrentFunction_ValueChanged() [1/4]
void IG.Forms.VectorFunctionScriptControl.numCurrentFunction_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionIndex, IG.Forms.VectorFunctionScriptControl.numCurrentFunction, and IG.Forms.VectorFunctionScriptControl.NumValues.
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
numCurrentFunction_Validated() [1/4]
void IG.Forms.VectorFunctionScriptControl.numCurrentFunction_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.numCurrentFunction, and IG.Forms.VectorFunctionScriptControl.NumValues.
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
btnCreateFunction_Click() [1/4]
void IG.Forms.VectorFunctionScriptControl.btnCreateFunction_Click (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetFunction(), IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
btnSummary_Click() [1/4]
void IG.Forms.VectorFunctionScriptControl.btnSummary_Click (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.CreateFunctonSummary().
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
btnValueCalculator_Click() [1/4]
void IG.Forms.VectorFunctionScriptControl.btnValueCalculator_Click (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
btnPlot1d_Click() [1/4]
void IG.Forms.VectorFunctionScriptControl.btnPlot1d_Click (object sender, EventArgs e) inline private
Launches 1D parametric plots of the function defined in this control.
References IG.Forms.VectorFunctionScriptControl.DataDefinition, IG.Forms.VectorFunctionScriptControl.Function, IG.Forms.VectorFunctionPlotter1d.Function, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.VectorFunctionPlotter1dForm.MainControl, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
btnPlot2d_Click() [1/4]
void IG.Forms.VectorFunctionScriptControl.btnPlot2d_Click (object sender, EventArgs e) inline private
Launches 2D parametric plots of the function defined in this control.
References IG.Forms.VectorFunctionScriptControl.DataDefinition, IG.Forms.VectorFunctionScriptControl.Function, IG.Forms.VectorFunctionPlotter2d.Function, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.VectorFunctionPlotter2dForm.MainControl, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
btnSave_Click() [1/4]
void IG.Forms.VectorFunctionScriptControl.btnSave_Click (object sender, EventArgs e) inline private
Saves the current fucntion definition to a JSON file.
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.VectorFunctionScriptControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.FileSelector.Filter, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.VectorFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.IReporterBase.ReportWarning(), and IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.SaveJson().
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
btnLoad_Click() [1/4]
void IG.Forms.VectorFunctionScriptControl.btnLoad_Click (object sender, EventArgs e) inline private
Loads vector funcition definition from a file.
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionController, IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionIndex, IG.Forms.VectorFunctionScriptControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.FileSelector.Filter, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.HasUnsavedChanges, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.LoadJson(), IG.Forms.VectorFunctionScriptControl.NumValues, IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
Dispose() [1/4]
override void IG.Forms.VectorFunctionScriptControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.VectorFunctionScriptControl.components.
InitializeComponent() [1/4]
void IG.Forms.VectorFunctionScriptControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.VectorFunctionScriptControl.btnCreateFunction, IG.Forms.VectorFunctionScriptControl.btnCreateFunction_Click(), IG.Forms.VectorFunctionScriptControl.btnLoad, IG.Forms.VectorFunctionScriptControl.btnLoad_Click(), IG.Forms.VectorFunctionScriptControl.btnPlot1d, IG.Forms.VectorFunctionScriptControl.btnPlot1d_Click(), IG.Forms.VectorFunctionScriptControl.btnPlot2d, IG.Forms.VectorFunctionScriptControl.btnPlot2d_Click(), IG.Forms.VectorFunctionScriptControl.btnSave, IG.Forms.VectorFunctionScriptControl.btnSave_Click(), IG.Forms.VectorFunctionScriptControl.btnSummary, IG.Forms.VectorFunctionScriptControl.btnSummary_Click(), IG.Forms.VectorFunctionScriptControl.btnValueCalculator, IG.Forms.VectorFunctionScriptControl.btnValueCalculator_Click(), IG.Forms.ScalarFunctionScriptControl.Dimension, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.FunctionDescription, IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Forms.VectorFunctionScriptControl.label1, IG.Forms.VectorFunctionScriptControl.lblCurrentFunction, IG.Forms.VectorFunctionScriptControl.lblCurrentFunctionLabelTitle, IG.Forms.VectorFunctionScriptControl.lblCurrentFunctionName, IG.Forms.VectorFunctionScriptControl.lblFunctionDescription, IG.Forms.VectorFunctionScriptControl.lblFunctionName, IG.Forms.VectorFunctionScriptControl.lblFunctionNames, IG.Forms.VectorFunctionScriptControl.lblNumParameters, IG.Forms.VectorFunctionScriptControl.lblParameterNames, IG.Forms.VectorFunctionScriptControl.lblTitle, IG.Forms.VectorFunctionScriptControl.numCurrentFunction, IG.Forms.VectorFunctionScriptControl.numCurrentFunction_Validated(), IG.Forms.VectorFunctionScriptControl.numCurrentFunction_ValueChanged(), IG.Forms.VectorFunctionScriptControl.numNumFunctions, IG.Forms.VectorFunctionScriptControl.numNumFunctions_Validated(), IG.Forms.VectorFunctionScriptControl.numNumParameters, IG.Forms.VectorFunctionScriptControl.numNumParameters_Validated(), IG.Forms.ScalarFunctionScriptControl.ParameterNames, IG.Forms.VectorFunctionScriptControl.pnlButtons, IG.Forms.VectorFunctionScriptControl.pnlDimensions, IG.Forms.VectorFunctionScriptControl.pnlFunctionDescription, IG.Forms.VectorFunctionScriptControl.pnlFunctionName, IG.Forms.VectorFunctionScriptControl.pnlFunctionNames, IG.Forms.VectorFunctionScriptControl.pnlOuter, IG.Forms.VectorFunctionScriptControl.pnlParameterNames, IG.Forms.VectorFunctionScriptControl.pnlPlotButtons, IG.Forms.VectorFunctionScriptControl.pnlVector, IG.Forms.VectorFunctionScriptControl.scalarFunctionScriptControl1, IG.Forms.VectorFunctionScriptControl.txtFunctionDescription, IG.Forms.VectorFunctionScriptControl.txtFunctionDescription_Validated(), IG.Forms.VectorFunctionScriptControl.txtFunctionName, IG.Forms.VectorFunctionScriptControl.txtFunctionName_Validated(), IG.Forms.VectorFunctionScriptControl.txtFunctionNames, IG.Forms.VectorFunctionScriptControl.txtFunctionNames_Validated(), IG.Forms.VectorFunctionScriptControl.txtParameterNames, IG.Forms.VectorFunctionScriptControl.txtParameterNames_Validated(), IG.Forms.ScalarFunctionScriptControl.ValueDefinition, and IG.Forms.ScalarFunctionScriptControl.VectorFunctionControl.
Referenced by IG.Forms.VectorFunctionScriptControl.VectorFunctionScriptControl().
CopyDataToController() [2/4]
void IG.Forms.VectorFunctionScriptControl.CopyDataToController () inline private
Copies data from the current control to the internal function DTO.
References IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.ConvertParameterNamesToArray(), IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.Description, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.FunctionNames, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.Name, IG.Forms.VectorFunctionScriptControl.numNumFunctions, IG.Forms.VectorFunctionScriptControl.numNumParameters, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.NumParameters, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.NumValues, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.ParameterNames, IG.Forms.VectorFunctionScriptControl.txtFunctionDescription, IG.Forms.VectorFunctionScriptControl.txtFunctionName, IG.Forms.VectorFunctionScriptControl.txtFunctionNames, and IG.Forms.VectorFunctionScriptControl.txtParameterNames.
CopyDataFromController() [2/4]
void IG.Forms.VectorFunctionScriptControl.CopyDataFromController () inline
Copies data from the internal DTO to the current control.
References IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.Description, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetFunctionsString(), IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetParametersString(), IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.Name, IG.Forms.VectorFunctionScriptControl.numNumFunctions, IG.Forms.VectorFunctionScriptControl.numNumParameters, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.NumParameters, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.NumValues, IG.Forms.VectorFunctionScriptControl.txtFunctionDescription, IG.Forms.VectorFunctionScriptControl.txtFunctionName, IG.Forms.VectorFunctionScriptControl.txtFunctionNames, and IG.Forms.VectorFunctionScriptControl.txtParameterNames.
SynchronizeData() [2/4]
void IG.Forms.VectorFunctionScriptControl.SynchronizeData (bool syncParameterNames = false, bool syncFunctionNames = true) inline
Synchronizes data for the current vector function definition.
This method checks number of parameters and number of funcion values, then goes through all scalar funciton elemennts and checks if their data is allocated and consistent. It also takes care that data for the currently edited scalar function is updated according to the true state.
Parameters
syncParameterNames If true then parameterr names are also synchroniized.
syncFunctionNames If true then function names are also synchronized.
References IG.Forms.VectorFunctionScriptControl.CopyDataFromController(), IG.Forms.ScalarFunctionScriptControl.CopyDataFromController(), IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionController, IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionIndex, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.NumValues, IG.Forms.VectorFunctionScriptControl.scalarFunctionScriptControl1, and IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.SynchronizeData().
GetFunctionSignature() [2/4]
string IG.Forms.VectorFunctionScriptControl.GetFunctionSignature () inline protected
Returns function signature created from the data.
References IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.FunctionName, IG.Lib.UtilStr.GetParametersStringPlain(), and IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.ParameterNames.
CreateFunctonSummary() [2/4]
string IG.Forms.VectorFunctionScriptControl.CreateFunctonSummary () inline
References IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.FunctionName, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetFunctionsString(), IG.Lib.UtilStr.GetParametersStringPlain(), IG.Forms.VectorFunctionScriptControl.NumValues, IG.Forms.VectorFunctionScriptControl.ParameterNames, IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
txtFunctionName_Validated() [2/4]
void IG.Forms.VectorFunctionScriptControl.txtFunctionName_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.FunctionName, and IG.Forms.VectorFunctionScriptControl.txtFunctionName.
txtFunctionDescription_Validated() [2/4]
void IG.Forms.VectorFunctionScriptControl.txtFunctionDescription_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.FunctionDescription, and IG.Forms.VectorFunctionScriptControl.txtFunctionDescription.
txtParameterNames_Validated() [2/4]
void IG.Forms.VectorFunctionScriptControl.txtParameterNames_Validated (object sender, EventArgs e) inline private
References IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.ConvertParameterNamesToArray(), IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.ParameterNames, and IG.Forms.VectorFunctionScriptControl.txtParameterNames.
txtFunctionNames_Validated() [2/4]
void IG.Forms.VectorFunctionScriptControl.txtFunctionNames_Validated (object sender, EventArgs e) inline private
References IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.ConvertParameterNamesToArray(), IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.FunctionNames, and IG.Forms.VectorFunctionScriptControl.txtFunctionNames.
numNumParameters_Validated() [2/4]
void IG.Forms.VectorFunctionScriptControl.numNumParameters_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.numNumParameters, and IG.Forms.VectorFunctionScriptControl.NumParameters.
numNumFunctions_Validated() [2/4]
void IG.Forms.VectorFunctionScriptControl.numNumFunctions_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.numNumFunctions, and IG.Forms.VectorFunctionScriptControl.NumValues.
numCurrentFunction_ValueChanged() [2/4]
void IG.Forms.VectorFunctionScriptControl.numCurrentFunction_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionIndex, IG.Forms.VectorFunctionScriptControl.numCurrentFunction, and IG.Forms.VectorFunctionScriptControl.NumValues.
numCurrentFunction_Validated() [2/4]
void IG.Forms.VectorFunctionScriptControl.numCurrentFunction_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.numCurrentFunction, and IG.Forms.VectorFunctionScriptControl.NumValues.
btnCreateFunction_Click() [2/4]
void IG.Forms.VectorFunctionScriptControl.btnCreateFunction_Click (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetFunction(), IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
btnSummary_Click() [2/4]
void IG.Forms.VectorFunctionScriptControl.btnSummary_Click (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.CreateFunctonSummary().
btnValueCalculator_Click() [2/4]
void IG.Forms.VectorFunctionScriptControl.btnValueCalculator_Click (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
btnPlot1d_Click() [2/4]
void IG.Forms.VectorFunctionScriptControl.btnPlot1d_Click (object sender, EventArgs e) inline private
Launches 1D parametric plots of the function defined in this control.
References IG.Forms.VectorFunctionScriptControl.DataDefinition, IG.Forms.VectorFunctionScriptControl.Function, IG.Forms.VectorFunctionPlotter1d.Function, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.VectorFunctionPlotter1dForm.MainControl, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
btnPlot2d_Click() [2/4]
void IG.Forms.VectorFunctionScriptControl.btnPlot2d_Click (object sender, EventArgs e) inline private
Launches 2D parametric plots of the function defined in this control.
References IG.Forms.VectorFunctionScriptControl.DataDefinition, IG.Forms.VectorFunctionScriptControl.Function, IG.Forms.VectorFunctionPlotter2d.Function, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.VectorFunctionPlotter2dForm.MainControl, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
btnSave_Click() [2/4]
void IG.Forms.VectorFunctionScriptControl.btnSave_Click (object sender, EventArgs e) inline private
Saves the current fucntion definition to a JSON file.
References IG.Forms.FileSelector.BrowseFile(), IG.Forms.VectorFunctionScriptControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.VectorFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.IReporterBase.ReportWarning(), and IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.SaveJson().
btnLoad_Click() [2/4]
void IG.Forms.VectorFunctionScriptControl.btnLoad_Click (object sender, EventArgs e) inline private
Loads vector funcition definition from a file.
References IG.Forms.FileSelector.BrowseFile(), IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionController, IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionIndex, IG.Forms.VectorFunctionScriptControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.HasUnsavedChanges, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.LoadJson(), IG.Forms.VectorFunctionScriptControl.NumValues, IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
Dispose() [2/4]
override void IG.Forms.VectorFunctionScriptControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.VectorFunctionScriptControl.components.
InitializeComponent() [2/4]
void IG.Forms.VectorFunctionScriptControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.VectorFunctionScriptControl.btnCreateFunction, IG.Forms.VectorFunctionScriptControl.btnCreateFunction_Click(), IG.Forms.VectorFunctionScriptControl.btnLoad, IG.Forms.VectorFunctionScriptControl.btnLoad_Click(), IG.Forms.VectorFunctionScriptControl.btnPlot1d, IG.Forms.VectorFunctionScriptControl.btnPlot1d_Click(), IG.Forms.VectorFunctionScriptControl.btnPlot2d, IG.Forms.VectorFunctionScriptControl.btnPlot2d_Click(), IG.Forms.VectorFunctionScriptControl.btnSave, IG.Forms.VectorFunctionScriptControl.btnSave_Click(), IG.Forms.VectorFunctionScriptControl.btnSummary, IG.Forms.VectorFunctionScriptControl.btnSummary_Click(), IG.Forms.VectorFunctionScriptControl.btnValueCalculator, IG.Forms.VectorFunctionScriptControl.btnValueCalculator_Click(), IG.Forms.ScalarFunctionScriptControl.Dimension, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.FunctionDescription, IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Forms.VectorFunctionScriptControl.label1, IG.Forms.VectorFunctionScriptControl.lblCurrentFunction, IG.Forms.VectorFunctionScriptControl.lblCurrentFunctionLabelTitle, IG.Forms.VectorFunctionScriptControl.lblCurrentFunctionName, IG.Forms.VectorFunctionScriptControl.lblFunctionDescription, IG.Forms.VectorFunctionScriptControl.lblFunctionName, IG.Forms.VectorFunctionScriptControl.lblFunctionNames, IG.Forms.VectorFunctionScriptControl.lblNumParameters, IG.Forms.VectorFunctionScriptControl.lblParameterNames, IG.Forms.VectorFunctionScriptControl.lblTitle, IG.Forms.VectorFunctionScriptControl.numCurrentFunction, IG.Forms.VectorFunctionScriptControl.numCurrentFunction_Validated(), IG.Forms.VectorFunctionScriptControl.numCurrentFunction_ValueChanged(), IG.Forms.VectorFunctionScriptControl.numNumFunctions, IG.Forms.VectorFunctionScriptControl.numNumFunctions_Validated(), IG.Forms.VectorFunctionScriptControl.numNumParameters, IG.Forms.VectorFunctionScriptControl.numNumParameters_Validated(), IG.Forms.ScalarFunctionScriptControl.ParameterNames, IG.Forms.VectorFunctionScriptControl.pnlButtons, IG.Forms.VectorFunctionScriptControl.pnlDimensions, IG.Forms.VectorFunctionScriptControl.pnlFunctionDescription, IG.Forms.VectorFunctionScriptControl.pnlFunctionName, IG.Forms.VectorFunctionScriptControl.pnlFunctionNames, IG.Forms.VectorFunctionScriptControl.pnlOuter, IG.Forms.VectorFunctionScriptControl.pnlParameterNames, IG.Forms.VectorFunctionScriptControl.pnlPlotButtons, IG.Forms.VectorFunctionScriptControl.pnlVector, IG.Forms.VectorFunctionScriptControl.scalarFunctionScriptControl1, IG.Forms.VectorFunctionScriptControl.txtFunctionDescription, IG.Forms.VectorFunctionScriptControl.txtFunctionDescription_Validated(), IG.Forms.VectorFunctionScriptControl.txtFunctionName, IG.Forms.VectorFunctionScriptControl.txtFunctionName_Validated(), IG.Forms.VectorFunctionScriptControl.txtFunctionNames, IG.Forms.VectorFunctionScriptControl.txtFunctionNames_Validated(), IG.Forms.VectorFunctionScriptControl.txtParameterNames, IG.Forms.VectorFunctionScriptControl.txtParameterNames_Validated(), and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
CopyDataToController() [3/4]
void IG.Forms.VectorFunctionScriptControl.CopyDataToController () inline private
Copies data from the current control to the internal function DTO.
References IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.ConvertParameterNamesToArray(), IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.Description, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.FunctionNames, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.Name, IG.Forms.VectorFunctionScriptControl.numNumFunctions, IG.Forms.VectorFunctionScriptControl.numNumParameters, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.NumParameters, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.NumValues, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.ParameterNames, IG.Forms.VectorFunctionScriptControl.txtFunctionDescription, IG.Forms.VectorFunctionScriptControl.txtFunctionName, IG.Forms.VectorFunctionScriptControl.txtFunctionNames, and IG.Forms.VectorFunctionScriptControl.txtParameterNames.
CopyDataFromController() [3/4]
void IG.Forms.VectorFunctionScriptControl.CopyDataFromController () inline
Copies data from the internal DTO to the current control.
References IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.Description, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetFunctionsString(), IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetParametersString(), IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.Name, IG.Forms.VectorFunctionScriptControl.numNumFunctions, IG.Forms.VectorFunctionScriptControl.numNumParameters, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.NumParameters, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.NumValues, IG.Forms.VectorFunctionScriptControl.txtFunctionDescription, IG.Forms.VectorFunctionScriptControl.txtFunctionName, IG.Forms.VectorFunctionScriptControl.txtFunctionNames, and IG.Forms.VectorFunctionScriptControl.txtParameterNames.
SynchronizeData() [3/4]
void IG.Forms.VectorFunctionScriptControl.SynchronizeData (bool syncParameterNames = false, bool syncFunctionNames = true) inline
Synchronizes data for the current vector function definition.
This method checks number of parameters and number of funcion values, then goes through all scalar funciton elemennts and checks if their data is allocated and consistent. It also takes care that data for the currently edited scalar function is updated according to the true state.
Parameters
syncParameterNames If true then parameterr names are also synchroniized.
syncFunctionNames If true then function names are also synchronized.
References IG.Forms.VectorFunctionScriptControl.CopyDataFromController(), IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionController, IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionIndex, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.FunctionNames, IG.Forms.VectorFunctionScriptControl.lblCurrentFunctionName, IG.Forms.VectorFunctionScriptControl.NumValues, IG.Forms.VectorFunctionScriptControl.ScalarFunctionNotDefinedString, and IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.SynchronizeData().
GetFunctionSignature() [3/4]
string IG.Forms.VectorFunctionScriptControl.GetFunctionSignature () inline protected
Returns function signature created from the data.
References IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.FunctionName, IG.Lib.UtilStr.GetParametersStringPlain(), and IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.ParameterNames.
CreateFunctonSummary() [3/4]
string IG.Forms.VectorFunctionScriptControl.CreateFunctonSummary () inline
References IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.FunctionName, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetFunctionsString(), IG.Lib.UtilStr.GetParametersStringPlain(), IG.Forms.VectorFunctionScriptControl.NumValues, IG.Forms.VectorFunctionScriptControl.ParameterNames, IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
txtFunctionName_Validated() [3/4]
void IG.Forms.VectorFunctionScriptControl.txtFunctionName_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.FunctionName, and IG.Forms.VectorFunctionScriptControl.txtFunctionName.
txtFunctionDescription_Validated() [3/4]
void IG.Forms.VectorFunctionScriptControl.txtFunctionDescription_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.FunctionDescription, and IG.Forms.VectorFunctionScriptControl.txtFunctionDescription.
txtParameterNames_Validated() [3/4]
void IG.Forms.VectorFunctionScriptControl.txtParameterNames_Validated (object sender, EventArgs e) inline private
References IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.ConvertParameterNamesToArray(), IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.ParameterNames, and IG.Forms.VectorFunctionScriptControl.txtParameterNames.
txtFunctionNames_Validated() [3/4]
void IG.Forms.VectorFunctionScriptControl.txtFunctionNames_Validated (object sender, EventArgs e) inline private
References IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.ConvertParameterNamesToArray(), IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.FunctionNames, and IG.Forms.VectorFunctionScriptControl.txtFunctionNames.
numNumParameters_Validated() [3/4]
void IG.Forms.VectorFunctionScriptControl.numNumParameters_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.numNumParameters, and IG.Forms.VectorFunctionScriptControl.NumParameters.
numNumFunctions_Validated() [3/4]
void IG.Forms.VectorFunctionScriptControl.numNumFunctions_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.numNumFunctions, and IG.Forms.VectorFunctionScriptControl.NumValues.
numCurrentFunction_ValueChanged() [3/4]
void IG.Forms.VectorFunctionScriptControl.numCurrentFunction_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionIndex, IG.Forms.VectorFunctionScriptControl.numCurrentFunction, and IG.Forms.VectorFunctionScriptControl.NumValues.
numCurrentFunction_Validated() [3/4]
void IG.Forms.VectorFunctionScriptControl.numCurrentFunction_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.numCurrentFunction, and IG.Forms.VectorFunctionScriptControl.NumValues.
btnCreateFunction_Click() [3/4]
void IG.Forms.VectorFunctionScriptControl.btnCreateFunction_Click (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetFunction(), IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
btnSummary_Click() [3/4]
void IG.Forms.VectorFunctionScriptControl.btnSummary_Click (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.CreateFunctonSummary().
btnValueCalculator_Click() [3/4]
void IG.Forms.VectorFunctionScriptControl.btnValueCalculator_Click (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
btnPlot1d_Click() [3/4]
void IG.Forms.VectorFunctionScriptControl.btnPlot1d_Click (object sender, EventArgs e) inline private
Launches 1D parametric plots of the function defined in this control.
References IG.Forms.VectorFunctionScriptControl.DataDefinition, IG.Forms.VectorFunctionScriptControl.Function, IG.Forms.VectorFunctionPlotter1d.Function, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.VectorFunctionPlotter1dForm.MainControl, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
btnPlot2d_Click() [3/4]
void IG.Forms.VectorFunctionScriptControl.btnPlot2d_Click (object sender, EventArgs e) inline private
Launches 2D parametric plots of the function defined in this control.
References IG.Forms.VectorFunctionScriptControl.DataDefinition, IG.Forms.VectorFunctionScriptControl.Function, IG.Forms.VectorFunctionPlotter2d.Function, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.VectorFunctionPlotter2dForm.MainControl, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
btnSave_Click() [3/4]
void IG.Forms.VectorFunctionScriptControl.btnSave_Click (object sender, EventArgs e) inline private
Saves the current fucntion definition to a JSON file.
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.VectorFunctionScriptControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.FileSelector.Filter, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.VectorFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.IReporterBase.ReportWarning(), and IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.SaveJson().
btnLoad_Click() [3/4]
void IG.Forms.VectorFunctionScriptControl.btnLoad_Click (object sender, EventArgs e) inline private
Loads vector funcition definition from a file.
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionController, IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionIndex, IG.Forms.VectorFunctionScriptControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.FileSelector.Filter, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.HasUnsavedChanges, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.LoadJson(), IG.Forms.VectorFunctionScriptControl.NumValues, IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
Dispose() [3/4]
override void IG.Forms.VectorFunctionScriptControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.VectorFunctionScriptControl.components.
InitializeComponent() [3/4]
void IG.Forms.VectorFunctionScriptControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.VectorFunctionScriptControl.btnCreateFunction, IG.Forms.VectorFunctionScriptControl.btnCreateFunction_Click(), IG.Forms.VectorFunctionScriptControl.btnLoad, IG.Forms.VectorFunctionScriptControl.btnLoad_Click(), IG.Forms.VectorFunctionScriptControl.btnPlot1d, IG.Forms.VectorFunctionScriptControl.btnPlot1d_Click(), IG.Forms.VectorFunctionScriptControl.btnPlot2d, IG.Forms.VectorFunctionScriptControl.btnPlot2d_Click(), IG.Forms.VectorFunctionScriptControl.btnSave, IG.Forms.VectorFunctionScriptControl.btnSave_Click(), IG.Forms.VectorFunctionScriptControl.btnSummary, IG.Forms.VectorFunctionScriptControl.btnSummary_Click(), IG.Forms.VectorFunctionScriptControl.btnValueCalculator, IG.Forms.VectorFunctionScriptControl.btnValueCalculator_Click(), IG.Forms.ScalarFunctionScriptControl.Dimension, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.FunctionDescription, IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Forms.VectorFunctionScriptControl.label1, IG.Forms.VectorFunctionScriptControl.lblCurrentFunction, IG.Forms.VectorFunctionScriptControl.lblCurrentFunctionLabelTitle, IG.Forms.VectorFunctionScriptControl.lblCurrentFunctionName, IG.Forms.VectorFunctionScriptControl.lblFunctionDescription, IG.Forms.VectorFunctionScriptControl.lblFunctionName, IG.Forms.VectorFunctionScriptControl.lblFunctionNames, IG.Forms.VectorFunctionScriptControl.lblNumParameters, IG.Forms.VectorFunctionScriptControl.lblParameterNames, IG.Forms.VectorFunctionScriptControl.lblTitle, IG.Forms.VectorFunctionScriptControl.numCurrentFunction, IG.Forms.VectorFunctionScriptControl.numCurrentFunction_Validated(), IG.Forms.VectorFunctionScriptControl.numCurrentFunction_ValueChanged(), IG.Forms.VectorFunctionScriptControl.numNumFunctions, IG.Forms.VectorFunctionScriptControl.numNumFunctions_Validated(), IG.Forms.VectorFunctionScriptControl.numNumParameters, IG.Forms.VectorFunctionScriptControl.numNumParameters_Validated(), IG.Forms.ScalarFunctionScriptControl.ParameterNames, IG.Forms.VectorFunctionScriptControl.pnlButtons, IG.Forms.VectorFunctionScriptControl.pnlDimensions, IG.Forms.VectorFunctionScriptControl.pnlFunctionDescription, IG.Forms.VectorFunctionScriptControl.pnlFunctionName, IG.Forms.VectorFunctionScriptControl.pnlFunctionNames, IG.Forms.VectorFunctionScriptControl.pnlOuter, IG.Forms.VectorFunctionScriptControl.pnlParameterNames, IG.Forms.VectorFunctionScriptControl.pnlPlotButtons, IG.Forms.VectorFunctionScriptControl.pnlVector, IG.Forms.VectorFunctionScriptControl.scalarFunctionScriptControl1, IG.Forms.VectorFunctionScriptControl.txtFunctionDescription, IG.Forms.VectorFunctionScriptControl.txtFunctionDescription_Validated(), IG.Forms.VectorFunctionScriptControl.txtFunctionName, IG.Forms.VectorFunctionScriptControl.txtFunctionName_Validated(), IG.Forms.VectorFunctionScriptControl.txtFunctionNames, IG.Forms.VectorFunctionScriptControl.txtFunctionNames_Validated(), IG.Forms.VectorFunctionScriptControl.txtParameterNames, IG.Forms.VectorFunctionScriptControl.txtParameterNames_Validated(), IG.Forms.ScalarFunctionScriptControl.ValueDefinition, and IG.Forms.ScalarFunctionScriptControl.VectorFunctionControl.
CopyDataToController() [4/4]
void IG.Forms.VectorFunctionScriptControl.CopyDataToController () inline private
Copies data from the current control to the internal function DTO.
References IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.ConvertParameterNamesToArray(), IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.Description, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.FunctionNames, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.Name, IG.Forms.VectorFunctionScriptControl.numNumFunctions, IG.Forms.VectorFunctionScriptControl.numNumParameters, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.NumParameters, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.NumValues, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.ParameterNames, IG.Forms.VectorFunctionScriptControl.txtFunctionDescription, IG.Forms.VectorFunctionScriptControl.txtFunctionName, IG.Forms.VectorFunctionScriptControl.txtFunctionNames, and IG.Forms.VectorFunctionScriptControl.txtParameterNames.
CopyDataFromController() [4/4]
void IG.Forms.VectorFunctionScriptControl.CopyDataFromController () inline
Copies data from the internal DTO to the current control.
References IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.Description, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetFunctionsString(), IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetParametersString(), IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.Name, IG.Forms.VectorFunctionScriptControl.numNumFunctions, IG.Forms.VectorFunctionScriptControl.numNumParameters, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.NumParameters, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.NumValues, IG.Forms.VectorFunctionScriptControl.txtFunctionDescription, IG.Forms.VectorFunctionScriptControl.txtFunctionName, IG.Forms.VectorFunctionScriptControl.txtFunctionNames, and IG.Forms.VectorFunctionScriptControl.txtParameterNames.
SynchronizeData() [4/4]
void IG.Forms.VectorFunctionScriptControl.SynchronizeData (bool syncParameterNames = false, bool syncFunctionNames = true) inline
Synchronizes data for the current vector function definition.
This method checks number of parameters and number of funcion values, then goes through all scalar funciton elemennts and checks if their data is allocated and consistent. It also takes care that data for the currently edited scalar function is updated according to the true state.
Parameters
syncParameterNames If true then parameterr names are also synchroniized.
syncFunctionNames If true then function names are also synchronized.
References IG.Forms.VectorFunctionScriptControl.CopyDataFromController(), IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionController, IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionIndex, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.FunctionNames, IG.Forms.VectorFunctionScriptControl.lblCurrentFunctionName, IG.Forms.VectorFunctionScriptControl.NumValues, IG.Forms.VectorFunctionScriptControl.ScalarFunctionNotDefinedString, and IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.SynchronizeData().
GetFunctionSignature() [4/4]
string IG.Forms.VectorFunctionScriptControl.GetFunctionSignature () inline protected
Returns function signature created from the data.
References IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.FunctionName, IG.Lib.UtilStr.GetParametersStringPlain(), and IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.ParameterNames.
CreateFunctonSummary() [4/4]
string IG.Forms.VectorFunctionScriptControl.CreateFunctonSummary () inline
References IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.FunctionName, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetFunctionsString(), IG.Lib.UtilStr.GetParametersStringPlain(), IG.Forms.VectorFunctionScriptControl.NumValues, IG.Forms.VectorFunctionScriptControl.ParameterNames, IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
txtFunctionName_Validated() [4/4]
void IG.Forms.VectorFunctionScriptControl.txtFunctionName_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.FunctionName, and IG.Forms.VectorFunctionScriptControl.txtFunctionName.
txtFunctionDescription_Validated() [4/4]
void IG.Forms.VectorFunctionScriptControl.txtFunctionDescription_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.FunctionDescription, and IG.Forms.VectorFunctionScriptControl.txtFunctionDescription.
txtParameterNames_Validated() [4/4]
void IG.Forms.VectorFunctionScriptControl.txtParameterNames_Validated (object sender, EventArgs e) inline private
References IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.ConvertParameterNamesToArray(), IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.ParameterNames, and IG.Forms.VectorFunctionScriptControl.txtParameterNames.
txtFunctionNames_Validated() [4/4]
void IG.Forms.VectorFunctionScriptControl.txtFunctionNames_Validated (object sender, EventArgs e) inline private
References IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.ConvertParameterNamesToArray(), IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.FunctionNames, and IG.Forms.VectorFunctionScriptControl.txtFunctionNames.
numNumParameters_Validated() [4/4]
void IG.Forms.VectorFunctionScriptControl.numNumParameters_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.numNumParameters, and IG.Forms.VectorFunctionScriptControl.NumParameters.
numNumFunctions_Validated() [4/4]
void IG.Forms.VectorFunctionScriptControl.numNumFunctions_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.numNumFunctions, and IG.Forms.VectorFunctionScriptControl.NumValues.
numCurrentFunction_ValueChanged() [4/4]
void IG.Forms.VectorFunctionScriptControl.numCurrentFunction_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionIndex, IG.Forms.VectorFunctionScriptControl.numCurrentFunction, and IG.Forms.VectorFunctionScriptControl.NumValues.
numCurrentFunction_Validated() [4/4]
void IG.Forms.VectorFunctionScriptControl.numCurrentFunction_Validated (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.numCurrentFunction, and IG.Forms.VectorFunctionScriptControl.NumValues.
btnCreateFunction_Click() [4/4]
void IG.Forms.VectorFunctionScriptControl.btnCreateFunction_Click (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetFunction(), IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
btnSummary_Click() [4/4]
void IG.Forms.VectorFunctionScriptControl.btnSummary_Click (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.CreateFunctonSummary().
btnValueCalculator_Click() [4/4]
void IG.Forms.VectorFunctionScriptControl.btnValueCalculator_Click (object sender, EventArgs e) inline private
References IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
btnPlot1d_Click() [4/4]
void IG.Forms.VectorFunctionScriptControl.btnPlot1d_Click (object sender, EventArgs e) inline private
Launches 1D parametric plots of the function defined in this control.
References IG.Forms.VectorFunctionScriptControl.DataDefinition, IG.Forms.VectorFunctionScriptControl.Function, IG.Forms.VectorFunctionPlotter1d.Function, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.VectorFunctionPlotter1dForm.MainControl, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
btnPlot2d_Click() [4/4]
void IG.Forms.VectorFunctionScriptControl.btnPlot2d_Click (object sender, EventArgs e) inline private
Launches 2D parametric plots of the function defined in this control.
References IG.Forms.VectorFunctionScriptControl.DataDefinition, IG.Forms.VectorFunctionScriptControl.Function, IG.Forms.VectorFunctionPlotter2d.Function, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.VectorFunctionPlotter2dForm.MainControl, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
btnSave_Click() [4/4]
void IG.Forms.VectorFunctionScriptControl.btnSave_Click (object sender, EventArgs e) inline private
Saves the current fucntion definition to a JSON file.
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.VectorFunctionScriptControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.FileSelector.Filter, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.VectorFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.IReporterBase.ReportWarning(), and IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.SaveJson().
btnLoad_Click() [4/4]
void IG.Forms.VectorFunctionScriptControl.btnLoad_Click (object sender, EventArgs e) inline private
Loads vector funcition definition from a file.
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionController, IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionIndex, IG.Forms.VectorFunctionScriptControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.FileSelector.Filter, IG.Forms.VectorFunctionScriptControl.FunctionController, IG.Forms.VectorFunctionScriptControl.HasUnsavedChanges, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.LoadJson(), IG.Forms.VectorFunctionScriptControl.NumValues, IG.Forms.VectorFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
Dispose() [4/4]
override void IG.Forms.VectorFunctionScriptControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.VectorFunctionScriptControl.components.
InitializeComponent() [4/4]
void IG.Forms.VectorFunctionScriptControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.VectorFunctionScriptControl.btnCreateFunction, IG.Forms.VectorFunctionScriptControl.btnCreateFunction_Click(), IG.Forms.VectorFunctionScriptControl.btnLoad, IG.Forms.VectorFunctionScriptControl.btnLoad_Click(), IG.Forms.VectorFunctionScriptControl.btnPlot1d, IG.Forms.VectorFunctionScriptControl.btnPlot1d_Click(), IG.Forms.VectorFunctionScriptControl.btnPlot2d, IG.Forms.VectorFunctionScriptControl.btnPlot2d_Click(), IG.Forms.VectorFunctionScriptControl.btnSave, IG.Forms.VectorFunctionScriptControl.btnSave_Click(), IG.Forms.VectorFunctionScriptControl.btnSummary, IG.Forms.VectorFunctionScriptControl.btnSummary_Click(), IG.Forms.VectorFunctionScriptControl.btnValueCalculator, IG.Forms.VectorFunctionScriptControl.btnValueCalculator_Click(), IG.Forms.ScalarFunctionScriptControl.Dimension, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.FunctionDescription, IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Forms.VectorFunctionScriptControl.label1, IG.Forms.VectorFunctionScriptControl.lblCurrentFunction, IG.Forms.VectorFunctionScriptControl.lblCurrentFunctionLabelTitle, IG.Forms.VectorFunctionScriptControl.lblCurrentFunctionName, IG.Forms.VectorFunctionScriptControl.lblFunctionDescription, IG.Forms.VectorFunctionScriptControl.lblFunctionName, IG.Forms.VectorFunctionScriptControl.lblFunctionNames, IG.Forms.VectorFunctionScriptControl.lblNumParameters, IG.Forms.VectorFunctionScriptControl.lblParameterNames, IG.Forms.VectorFunctionScriptControl.lblTitle, IG.Forms.VectorFunctionScriptControl.numCurrentFunction, IG.Forms.VectorFunctionScriptControl.numCurrentFunction_Validated(), IG.Forms.VectorFunctionScriptControl.numCurrentFunction_ValueChanged(), IG.Forms.VectorFunctionScriptControl.numNumFunctions, IG.Forms.VectorFunctionScriptControl.numNumFunctions_Validated(), IG.Forms.VectorFunctionScriptControl.numNumParameters, IG.Forms.VectorFunctionScriptControl.numNumParameters_Validated(), IG.Forms.ScalarFunctionScriptControl.ParameterNames, IG.Forms.VectorFunctionScriptControl.pnlButtons, IG.Forms.VectorFunctionScriptControl.pnlDimensions, IG.Forms.VectorFunctionScriptControl.pnlFunctionDescription, IG.Forms.VectorFunctionScriptControl.pnlFunctionName, IG.Forms.VectorFunctionScriptControl.pnlFunctionNames, IG.Forms.VectorFunctionScriptControl.pnlOuter, IG.Forms.VectorFunctionScriptControl.pnlParameterNames, IG.Forms.VectorFunctionScriptControl.pnlPlotButtons, IG.Forms.VectorFunctionScriptControl.pnlVector, IG.Forms.VectorFunctionScriptControl.scalarFunctionScriptControl1, IG.Forms.VectorFunctionScriptControl.txtFunctionDescription, IG.Forms.VectorFunctionScriptControl.txtFunctionDescription_Validated(), IG.Forms.VectorFunctionScriptControl.txtFunctionName, IG.Forms.VectorFunctionScriptControl.txtFunctionName_Validated(), IG.Forms.VectorFunctionScriptControl.txtFunctionNames, IG.Forms.VectorFunctionScriptControl.txtFunctionNames_Validated(), IG.Forms.VectorFunctionScriptControl.txtParameterNames, IG.Forms.VectorFunctionScriptControl.txtParameterNames_Validated(), IG.Forms.ScalarFunctionScriptControl.ValueDefinition, and IG.Forms.ScalarFunctionScriptControl.VectorFunctionControl.
Member Data Documentation
_functionNameTitleNormal
string IG.Forms.VectorFunctionScriptControl._functionNameTitleNormal = "Function Name: " private
_functionNameTitleModified
string IG.Forms.VectorFunctionScriptControl._functionNameTitleModified = "Function Name: (*)" private
_functionController
VectorFunctionScriptController IG.Forms.VectorFunctionScriptControl._functionController private
_initialScalarFunctionDefinitionStrings
string [] IG.Forms.VectorFunctionScriptControl._initialScalarFunctionDefinitionStrings private
ScalarFunctionNotDefinedString
string IG.Forms.VectorFunctionScriptControl.ScalarFunctionNotDefinedString = "<< not defined >>" protected
Referenced by IG.Forms.VectorFunctionScriptControl.SynchronizeData(), and IG.Forms.VectorFunctionScriptControl.VectorFunctionScriptControl().
_hasUnsavedChanges
bool IG.Forms.VectorFunctionScriptControl._hasUnsavedChanges = false private
_currentScalarFunctionIndex
int IG.Forms.VectorFunctionScriptControl._currentScalarFunctionIndex = 0 private
_currentScalarFunctionController
ScalarFunctionScriptController IG.Forms.VectorFunctionScriptControl._currentScalarFunctionController = null private
_isLoaderConsistent
bool IG.Forms.VectorFunctionScriptControl._isLoaderConsistent = false private
_dataDefinition
InputOutputDataDefiniton IG.Forms.VectorFunctionScriptControl._dataDefinition = null private
_prepareStandardDefinitions
bool IG.Forms.VectorFunctionScriptControl._prepareStandardDefinitions = true private
components
System ComponentModel IContainer IG.Forms.VectorFunctionScriptControl.components = null private
Required designer variable.
Referenced by IG.Forms.VectorFunctionScriptControl.Dispose().
pnlVector
System Windows Forms Panel IG.Forms.VectorFunctionScriptControl.pnlVector private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
label1
System Windows Forms Label IG.Forms.VectorFunctionScriptControl.label1 private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
lblCurrentFunction
System Windows Forms Label IG.Forms.VectorFunctionScriptControl.lblCurrentFunction private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
pnlOuter
System Windows Forms Panel IG.Forms.VectorFunctionScriptControl.pnlOuter private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
numCurrentFunction
System Windows Forms NumericUpDown IG.Forms.VectorFunctionScriptControl.numCurrentFunction private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent(), IG.Forms.VectorFunctionScriptControl.numCurrentFunction_Validated(), and IG.Forms.VectorFunctionScriptControl.numCurrentFunction_ValueChanged().
lblTitle
System Windows Forms Label IG.Forms.VectorFunctionScriptControl.lblTitle private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
numNumFunctions
System Windows Forms NumericUpDown IG.Forms.VectorFunctionScriptControl.numNumFunctions private
Referenced by IG.Forms.VectorFunctionScriptControl.CopyDataFromController(), IG.Forms.VectorFunctionScriptControl.CopyDataToController(), IG.Forms.VectorFunctionScriptControl.InitializeComponent(), and IG.Forms.VectorFunctionScriptControl.numNumFunctions_Validated().
lblCurrentFunctionLabelTitle
System Windows Forms Label IG.Forms.VectorFunctionScriptControl.lblCurrentFunctionLabelTitle private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
numNumParameters
System Windows Forms NumericUpDown IG.Forms.VectorFunctionScriptControl.numNumParameters private
Referenced by IG.Forms.VectorFunctionScriptControl.CopyDataFromController(), IG.Forms.VectorFunctionScriptControl.CopyDataToController(), IG.Forms.VectorFunctionScriptControl.InitializeComponent(), and IG.Forms.VectorFunctionScriptControl.numNumParameters_Validated().
lblNumParameters
System Windows Forms Label IG.Forms.VectorFunctionScriptControl.lblNumParameters private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
lblParameterNames
System Windows Forms Label IG.Forms.VectorFunctionScriptControl.lblParameterNames private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
pnlDimensions
System Windows Forms Panel IG.Forms.VectorFunctionScriptControl.pnlDimensions private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
lblCurrentFunctionName
System Windows Forms Label IG.Forms.VectorFunctionScriptControl.lblCurrentFunctionName private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent(), IG.Forms.VectorFunctionScriptControl.SynchronizeData(), and IG.Forms.VectorFunctionScriptControl.VectorFunctionScriptControl().
lblFunctionNames
System Windows Forms Label IG.Forms.VectorFunctionScriptControl.lblFunctionNames private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
pnlFunctionNames
System Windows Forms Panel IG.Forms.VectorFunctionScriptControl.pnlFunctionNames private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
txtFunctionNames
System Windows Forms TextBox IG.Forms.VectorFunctionScriptControl.txtFunctionNames private
Referenced by IG.Forms.VectorFunctionScriptControl.CopyDataFromController(), IG.Forms.VectorFunctionScriptControl.CopyDataToController(), IG.Forms.VectorFunctionScriptControl.InitializeComponent(), and IG.Forms.VectorFunctionScriptControl.txtFunctionNames_Validated().
pnlParameterNames
System Windows Forms Panel IG.Forms.VectorFunctionScriptControl.pnlParameterNames private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
txtParameterNames
System Windows Forms TextBox IG.Forms.VectorFunctionScriptControl.txtParameterNames private
Referenced by IG.Forms.VectorFunctionScriptControl.CopyDataFromController(), IG.Forms.VectorFunctionScriptControl.CopyDataToController(), IG.Forms.VectorFunctionScriptControl.InitializeComponent(), and IG.Forms.VectorFunctionScriptControl.txtParameterNames_Validated().
scalarFunctionScriptControl1
IG Forms ScalarFunctionScriptControl IG.Forms.VectorFunctionScriptControl.scalarFunctionScriptControl1 private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent(), IG.Forms.VectorFunctionScriptControl.SynchronizeData(), and IG.Forms.VectorFunctionScriptControl.VectorFunctionScriptControl().
pnlButtons
System Windows Forms Panel IG.Forms.VectorFunctionScriptControl.pnlButtons private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
btnCreateFunction
System Windows Forms Button IG.Forms.VectorFunctionScriptControl.btnCreateFunction private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
btnValueCalculator
System Windows Forms Button IG.Forms.VectorFunctionScriptControl.btnValueCalculator private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
btnLoad
System Windows Forms Button IG.Forms.VectorFunctionScriptControl.btnLoad private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
btnSave
System Windows Forms Button IG.Forms.VectorFunctionScriptControl.btnSave private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
btnSummary
System Windows Forms Button IG.Forms.VectorFunctionScriptControl.btnSummary private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
pnlPlotButtons
System Windows Forms Panel IG.Forms.VectorFunctionScriptControl.pnlPlotButtons private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
btnPlot1d
System Windows Forms Button IG.Forms.VectorFunctionScriptControl.btnPlot1d private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
btnPlot2d
System Windows Forms Button IG.Forms.VectorFunctionScriptControl.btnPlot2d private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
pnlFunctionDescription
System Windows Forms Panel IG.Forms.VectorFunctionScriptControl.pnlFunctionDescription private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
txtFunctionDescription
System Windows Forms TextBox IG.Forms.VectorFunctionScriptControl.txtFunctionDescription private
Referenced by IG.Forms.VectorFunctionScriptControl.CopyDataFromController(), IG.Forms.VectorFunctionScriptControl.CopyDataToController(), IG.Forms.VectorFunctionScriptControl.InitializeComponent(), and IG.Forms.VectorFunctionScriptControl.txtFunctionDescription_Validated().
lblFunctionDescription
System Windows Forms Label IG.Forms.VectorFunctionScriptControl.lblFunctionDescription private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
pnlFunctionName
System Windows Forms Panel IG.Forms.VectorFunctionScriptControl.pnlFunctionName private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent().
txtFunctionName
System Windows Forms TextBox IG.Forms.VectorFunctionScriptControl.txtFunctionName private
Referenced by IG.Forms.VectorFunctionScriptControl.CopyDataFromController(), IG.Forms.VectorFunctionScriptControl.CopyDataToController(), IG.Forms.VectorFunctionScriptControl.InitializeComponent(), and IG.Forms.VectorFunctionScriptControl.txtFunctionName_Validated().
lblFunctionName
System Windows Forms Label IG.Forms.VectorFunctionScriptControl.lblFunctionName private
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent(), and IG.Forms.VectorFunctionScriptControl.VectorFunctionScriptControl().
Property Documentation
Reporter
IG Lib IReporter IG.Forms.VectorFunctionScriptControl.Reporter get protected
Referenced by IG.Forms.VectorFunctionScriptControl.btnCreateFunction_Click(), IG.Forms.VectorFunctionScriptControl.btnLoad_Click(), IG.Forms.VectorFunctionScriptControl.btnPlot1d_Click(), IG.Forms.VectorFunctionScriptControl.btnPlot2d_Click(), IG.Forms.VectorFunctionScriptControl.btnSave_Click(), IG.Forms.VectorFunctionScriptControl.btnValueCalculator_Click(), and IG.Forms.VectorFunctionScriptControl.CreateFunctonSummary().
FunctionNameTitleNormal
string IG.Forms.VectorFunctionScriptControl.FunctionNameTitleNormal get set protected
Normal text of the label that introduces function name input box.
Referenced by IG.Forms.VectorFunctionScriptControl.VectorFunctionScriptControl().
FunctionNameTitleModified
string IG.Forms.VectorFunctionScriptControl.FunctionNameTitleModified get set protected
Normal text of the label that introduces function name input box.
FunctionController
VectorFunctionScriptController IG.Forms.VectorFunctionScriptControl.FunctionController get set protected
Referenced by IG.Forms.VectorFunctionScriptControl.btnCreateFunction_Click(), IG.Forms.VectorFunctionScriptControl.btnLoad_Click(), IG.Forms.VectorFunctionScriptControl.btnPlot1d_Click(), IG.Forms.VectorFunctionScriptControl.btnPlot2d_Click(), IG.Forms.VectorFunctionScriptControl.btnSave_Click(), IG.Forms.VectorFunctionScriptControl.CopyDataFromController(), IG.Forms.VectorFunctionScriptControl.CopyDataToController(), IG.Forms.VectorFunctionScriptControl.CreateFunctonSummary(), IG.Forms.VectorFunctionScriptControl.GetFunctionSignature(), IG.Forms.VectorFunctionScriptControl.SynchronizeData(), IG.Forms.VectorFunctionScriptControl.txtFunctionNames_Validated(), and IG.Forms.VectorFunctionScriptControl.txtParameterNames_Validated().
Function
IVectorFunction IG.Forms.VectorFunctionScriptControl.Function get
Gets the function generated according to the function definition contained in this control and stored in FunctionController.
Function loaders from the FunctionController's elements (scalar function script controllers) are used to generate the function.
Referenced by IG.Forms.VectorFunctionScriptControl.btnPlot1d_Click(), and IG.Forms.VectorFunctionScriptControl.btnPlot2d_Click().
InitialScalarFunctionDefinitionStrings
virtual string [] IG.Forms.VectorFunctionScriptControl.InitialScalarFunctionDefinitionStrings get set
This property contains initial definitions of scalar functions (i.e.their values defined in terms of parameters). If defined then these definitions are asigned in initialization.
Referenced by IG.Forms.VectorFunctionScriptForm.InitializeComponent(), and IG.Forms.VectorFunctionScriptForm.VectorFunctionScriptForm().
HasUnsavedChanges
bool IG.Forms.VectorFunctionScriptControl.HasUnsavedChanges get set protected set
Whether the current function definition has unsaved changes.
Referenced by IG.Forms.VectorFunctionScriptControl.btnLoad_Click(), IG.Forms.ScalarFunctionScriptControl.HasParentUnsavedChanges(), IG.Forms.VectorFunctionScriptControl.VectorFunctionScriptControl(), and IG.Forms.VectorFunctionScriptForm.VectorFunctionScriptForm().
HasChildUnsavedChanges
bool IG.Forms.VectorFunctionScriptControl.HasChildUnsavedChanges get set
Indicates whether child control (of type ScalarFunctionScriptControl) has unsaved changes.
Referenced by IG.Forms.VectorFunctionScriptControl.VectorFunctionScriptControl(), and IG.Forms.VectorFunctionScriptForm.VectorFunctionScriptForm().
CurrentScalarFunctionIndex
int IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionIndex get set private
Gets or sets index of the current scalar funciton that is worked on.
Changing this property affect which function is edited in the scalar function definition frame.
Referenced by IG.Forms.VectorFunctionScriptControl.btnLoad_Click(), IG.Forms.VectorFunctionScriptControl.numCurrentFunction_ValueChanged(), IG.Forms.VectorFunctionScriptControl.SynchronizeData(), and IG.Forms.VectorFunctionScriptControl.VectorFunctionScriptControl().
CurrentScalarFunctionController
ScalarFunctionScriptController IG.Forms.VectorFunctionScriptControl.CurrentScalarFunctionController get set protected
Scalar function controller that represents the element of the vector function that is currently edited.
Referenced by IG.Forms.VectorFunctionScriptControl.btnLoad_Click(), and IG.Forms.VectorFunctionScriptControl.SynchronizeData().
IsLoaderConsistent
bool IG.Forms.VectorFunctionScriptControl.IsLoaderConsistent get protected set
Whether function loader is in consistent state.
This method shoulld be elaborated or dropped.
FunctionName
string IG.Forms.VectorFunctionScriptControl.FunctionName get set
Name of the function.
Referenced by IG.Forms.VectorFunctionScriptControl.CreateFunctonSummary(), IG.Forms.VectorFunctionScriptControl.GetFunctionSignature(), IG.Forms.VectorFunctionScriptForm.InitializeComponent(), and IG.Forms.VectorFunctionScriptControl.txtFunctionName_Validated().
FunctionDescription
string IG.Forms.VectorFunctionScriptControl.FunctionDescription get set
Referenced by IG.Forms.VectorFunctionScriptForm.InitializeComponent(), and IG.Forms.VectorFunctionScriptControl.txtFunctionDescription_Validated().
NumParameters
int IG.Forms.VectorFunctionScriptControl.NumParameters get set
Gets or sets number of parameters of the represented vector function.
Referenced by IG.Forms.VectorFunctionScriptForm.InitializeComponent(), and IG.Forms.VectorFunctionScriptControl.numNumParameters_Validated().
NumValues
int IG.Forms.VectorFunctionScriptControl.NumValues get set
Gets or sets number of values of the represented vector function (i.e., dimension of its codomain).
Referenced by IG.Forms.VectorFunctionScriptControl.btnLoad_Click(), IG.Forms.VectorFunctionScriptControl.CreateFunctonSummary(), IG.Forms.VectorFunctionScriptForm.InitializeComponent(), IG.Forms.VectorFunctionScriptControl.numCurrentFunction_Validated(), IG.Forms.VectorFunctionScriptControl.numCurrentFunction_ValueChanged(), IG.Forms.VectorFunctionScriptControl.numNumFunctions_Validated(), and IG.Forms.VectorFunctionScriptControl.SynchronizeData().
ParameterNames
string [] IG.Forms.VectorFunctionScriptControl.ParameterNames get set
Names of function parameters.
Referenced by IG.Forms.VectorFunctionScriptControl.CreateFunctonSummary(), IG.Forms.VectorFunctionScriptForm.InitializeComponent(), and IG.Forms.VectorFunctionScriptControl.txtParameterNames_Validated().
FunctionNames
string [] IG.Forms.VectorFunctionScriptControl.FunctionNames get set
Names of scalar function components that define individual values of the represented vector function.
Referenced by IG.Forms.VectorFunctionScriptForm.InitializeComponent(), IG.Forms.VectorFunctionScriptControl.SynchronizeData(), and IG.Forms.VectorFunctionScriptControl.txtFunctionNames_Validated().
DataDefinition
InputOutputDataDefiniton IG.Forms.VectorFunctionScriptControl.DataDefinition get set private
Definition of input and output data for the represented scalar function.
Referenced by IG.Forms.VectorFunctionScriptControl.btnLoad_Click(), IG.Forms.VectorFunctionScriptControl.btnPlot1d_Click(), IG.Forms.VectorFunctionScriptControl.btnPlot2d_Click(), and IG.Forms.VectorFunctionScriptControl.btnSave_Click().
FileSelector
FileSelector IG.Forms.VectorFunctionScriptControl.FileSelector get
GUI component for seclecting files.
PrepareStandardDefinitions
bool IG.Forms.VectorFunctionScriptControl.PrepareStandardDefinitions get set private
The documentation for this class was generated from the following files:
iglib/extensions/iglibext/Forms/Numeric/VectorFunctionScriptControl.cs
iglib/extensions/iglibext/Forms/Numeric/VectorFunctionScriptControl.Designer.cs