Doc: IGLib EXTENDED: IG.Lib.MultiDimensionalArray< ElementType > Class Template Reference
IG.Lib.MultiDimensionalArray< ElementType > Class Template Reference
Multidimensional arrays.
Public Member Functions
delegate void MultidimensionalArrayIterator< ElementType > (MultiDimensionalArray< ElementType > array, int[] indices, int currentLevel)
Delegate that is used to do work at specific point in various methods that iterate over multidimensional arrays.
MultiDimensionalArray (params int[] dimensions)
Constructs a new multidimensional array with specified dimensions.
void ClearElements ()
Sets all elements to the default value for the specific element type.
void SetDimensions (params int[] dimensions)
Sets new dimensions of the current multidimensional array.
int Dimension (int which)
Returns the specified dimension of the multidimensional array.
int GetLinearIndex (params int[] indices)
Returns a linear index that corresponds to the specified table of indices, i.e. index of the element specified by these indices in the onedimensional data array.
int[] GetIndices (int linearIndex)
Returns indices of the element whose linear index is specified (i.e. the index of element in the one dimensional data array that actually holds the data).
void Iterate (MultidimensionalArrayIterator< ElementType > beginLevel, MultidimensionalArrayIterator< ElementType > endLevel, MultidimensionalArrayIterator< ElementType > workElement)
Iterates over all elements of the multdimensional array, and executes the specified delegates at different events.
string IndicesToStringNoBrackets (int[] indices)
Creates and returns a string representation of indices as a plain comma separated list of integers in a single line (without brackets).
string IndicesToString (int[] indices)
Creates and returns a string representation of indices as a comma separated list of integers in a single line and tightly embedded in curly brackets.
string ToStringSimple ()
Returns a simple string representation of a multidimensional array. Each element is written in its own line starting with element indices and a colon.
string ToStringTest ()
Returns a simple string representation of a multidimensional array. Each element is written in its own line starting with element indices and a colon.
string ToStringOld ()
Returns a string representation of a multidimensional array. Each element is written in its own line starting with element indices and a colon.
override string ToString ()
Returns a string representation of a multidimensional array in the Mathematica-like set notation.
string ToString (bool newLinesLast)
Returns a string representation of a multidimensional array in the Mathematica-like set notation.
Static Public Member Functions
static void ExampleFillArray (MultiDimensionalArray< int > array)
Fills the specified multidimensional array of integers in such a way that element values are related to positions within the array in a simple and easily identifiable way.
static void Example (params int[] dimensions)
Example of use of multidimensional arrays.
static void Example ()
Example of use of multidimensional arrays.
Public Attributes
int _numElements
Protected Member Functions
void IterateAux (int[] indices, int level, MultidimensionalArrayIterator< ElementType > beginLevel, MultidimensionalArrayIterator< ElementType > endLevel, MultidimensionalArrayIterator< ElementType > workElement)
Auxiliary method for Iterate, recursive.
Protected Attributes
readonly object _lock = new object()
ElementType[] _data
int[] _dimensions
int _numIndices
int[] _subTableLengths
Array of subtable lengths. Last element is always one.
Properties
object Lock [get]
Object used for thread locking.
ElementType[] Data [get, set]
Array containing data of the multidimensional array.
int[] Dimensions [get, set]
Gets or sets dimensions of the multidimensional array.
int NumIndices [get]
Gets numbet of indices of the multidimensional array.
int NumElements [get]
Gets total number of elements of the multidimensional array.
int[] SubTableLengths [get]
Gets an array of lengths of the subtables with specified number of indices defined.
ElementType this[params int[] indices [get, set]
Index operator, gets or sets the specified element of the multidimensional array.
Private Member Functions
MultiDimensionalArray ()
Prevents calling argument-less constructor.
Detailed Description
Multidimensional arrays.
$A Igor xx;
Constructor & Destructor Documentation
MultiDimensionalArray() [1/2]
IG.Lib.MultiDimensionalArray< ElementType >.MultiDimensionalArray () inline private
Prevents calling argument-less constructor.
MultiDimensionalArray() [2/2]
IG.Lib.MultiDimensionalArray< ElementType >.MultiDimensionalArray (params int[] dimensions) inline
Constructs a new multidimensional array with specified dimensions.
Parameters
dimensions Dimensions of the multidimensional array.
Can be null, meaning a zero rank array containing a sigle element.
References IG.Lib.MultiDimensionalArray< ElementType >.Dimensions.
Member Function Documentation
MultidimensionalArrayIterator< ElementType >()
delegate void IG.Lib.MultiDimensionalArray< ElementType >.MultidimensionalArrayIterator< ElementType > (MultiDimensionalArray< ElementType > array, int[] indices, int currentLevel)
Delegate that is used to do work at specific point in various methods that iterate over multidimensional arrays.
Template Parameters
ElementType Type of array element.
Parameters
array Array on which the method operates.
indices Indices of the current element of sub-array.
currentLevel Current level of iteration. Starts with 0 for the level where outermost sub-arrays are iterated, until the number of dimensions where individual element is worked on.
ClearElements()
void IG.Lib.MultiDimensionalArray< ElementType >.ClearElements () inline
Sets all elements to the default value for the specific element type.
References IG.Lib.MultiDimensionalArray< ElementType >._data, and IG.Lib.MultiDimensionalArray< ElementType >.Lock.
SetDimensions()
void IG.Lib.MultiDimensionalArray< ElementType >.SetDimensions (params int[] dimensions) inline
Sets new dimensions of the current multidimensional array.
Parameters
dimensions New dimensions.
Setter of the index operator is used.
References IG.Lib.MultiDimensionalArray< ElementType >.Dimensions.
Dimension()
int IG.Lib.MultiDimensionalArray< ElementType >.Dimension (int which) inline
Returns the specified dimension of the multidimensional array.
Parameters
which Specifies which dimension is returned.
References IG.Lib.MultiDimensionalArray< ElementType >._dimensions, IG.Lib.MultiDimensionalArray< ElementType >._numIndices, and IG.Lib.MultiDimensionalArray< ElementType >.Lock.
Referenced by IG.Lib.MultiDimensionalArray< ElementType >.ToStringOld().
GetLinearIndex()
int IG.Lib.MultiDimensionalArray< ElementType >.GetLinearIndex (params int[] indices) inline
Returns a linear index that corresponds to the specified table of indices, i.e. index of the element specified by these indices in the onedimensional data array.
Parameters
indices Set of indices that specify the desired element.
If the array has zero rank then indices can be null, in this case 0 is returned (pointing at teh only element).
References IG.Lib.MultiDimensionalArray< ElementType >._dimensions, IG.Lib.MultiDimensionalArray< ElementType >._numElements, IG.Lib.MultiDimensionalArray< ElementType >._numIndices, IG.Lib.MultiDimensionalArray< ElementType >._subTableLengths, IG.Lib.MultiDimensionalArray< ElementType >.indices, and IG.Lib.MultiDimensionalArray< ElementType >.Lock.
GetIndices()
int [] IG.Lib.MultiDimensionalArray< ElementType >.GetIndices (int linearIndex) inline
Returns indices of the element whose linear index is specified (i.e. the index of element in the one dimensional data array that actually holds the data).
Parameters
linearIndex Linear index of the element in the one dimensional array of elements, for which the multidimensional index is returned.
References IG.Lib.MultiDimensionalArray< ElementType >._numElements, IG.Lib.MultiDimensionalArray< ElementType >._numIndices, IG.Lib.MultiDimensionalArray< ElementType >._subTableLengths, and IG.Lib.MultiDimensionalArray< ElementType >.Lock.
Referenced by IG.Lib.MultiDimensionalArray< ElementType >.ExampleFillArray().
IterateAux()
void IG.Lib.MultiDimensionalArray< ElementType >.IterateAux (int[] indices, int level, MultidimensionalArrayIterator< ElementType > beginLevel, MultidimensionalArrayIterator< ElementType > endLevel, MultidimensionalArrayIterator< ElementType > workElement) inline protected
Auxiliary method for Iterate, recursive.
This method is usually called by the Iterate method to iterate recursively over elements.
Parameters
indices Current array of indices that selects a specific element (if level == NumIndices) or define the subtable over which to iterate in the next level.
Initial call (outermost recursion level) to this method should be with all indices equal to 0.
The first index is associated with the outer-most recursion level and varies most slowly durig recursion.
Parameters
level Current level of iteration; starts with 0.
Initial call (outermost recursion level) to this method should be with level equal to 0.
Parameters
beginLevel Delegate that executes when a new level is begun. This is not executed for each single element, but only for subarrays.
endLevel delegate that executes when a new level ends. This is not executed for each single element, but only for subarrays.
workElement Delegate that executes in the final level, for each element of the multidimensional array.
The level argument equals the number of indices that are fixed at the current recursion level.
The workElement delegate is executed only in the deepest recursion level when individual elements are worked. At this level, the level argument equals the number of array dimensions (i.e. NumIndices).
At the top-most iteration level (when the method is first called), the level parameter equals 0, and no indices are specified at this level.
References IG.Lib.MultiDimensionalArray< ElementType >._dimensions, IG.Lib.MultiDimensionalArray< ElementType >._numIndices, and IG.Lib.MultiDimensionalArray< ElementType >.indices.
Referenced by IG.Lib.MultiDimensionalArray< ElementType >.Iterate().
Iterate()
void IG.Lib.MultiDimensionalArray< ElementType >.Iterate (MultidimensionalArrayIterator< ElementType > beginLevel, MultidimensionalArrayIterator< ElementType > endLevel, MultidimensionalArrayIterator< ElementType > workElement) inline
Iterates over all elements of the multdimensional array, and executes the specified delegates at different events.
This is initiation method for iteration over elements, and the recursive method IterateAux is called to actually do the job. See that method for more detailed description.
Parameters
beginLevel Executed when a new level begins. This is not executed for each single element, but only for subarrays.
endLevel Execuded when a new level ends. This is not executed for each single element, but only for subarrays.
workElement Executed on each element (i.e. only on the last level).
References IG.Lib.MultiDimensionalArray< ElementType >._numElements, IG.Lib.MultiDimensionalArray< ElementType >._numIndices, IG.Lib.MultiDimensionalArray< ElementType >.indices, IG.Lib.MultiDimensionalArray< ElementType >.IterateAux(), and IG.Lib.MultiDimensionalArray< ElementType >.Lock.
Referenced by IG.Lib.MultiDimensionalArray< ElementType >.ToString(), IG.Lib.MultiDimensionalArray< ElementType >.ToStringOld(), IG.Lib.MultiDimensionalArray< ElementType >.ToStringSimple(), and IG.Lib.MultiDimensionalArray< ElementType >.ToStringTest().
IndicesToStringNoBrackets()
string IG.Lib.MultiDimensionalArray< ElementType >.IndicesToStringNoBrackets (int[] indices) inline
Creates and returns a string representation of indices as a plain comma separated list of integers in a single line (without brackets).
Parameters
indices Indices whose string representation is returned.
References IG.Lib.MultiDimensionalArray< ElementType >.indices, and IG.Lib.MultiDimensionalArray< ElementType >.ToString().
Referenced by IG.Lib.MultiDimensionalArray< ElementType >.IndicesToString().
IndicesToString()
string IG.Lib.MultiDimensionalArray< ElementType >.IndicesToString (int[] indices) inline
Creates and returns a string representation of indices as a comma separated list of integers in a single line and tightly embedded in curly brackets.
Parameters
indices Indices whose string representation is returned.
References IG.Lib.MultiDimensionalArray< ElementType >.indices, and IG.Lib.MultiDimensionalArray< ElementType >.IndicesToStringNoBrackets().
Referenced by IG.Lib.MultiDimensionalArray< ElementType >.ToString(), IG.Lib.MultiDimensionalArray< ElementType >.ToStringOld(), IG.Lib.MultiDimensionalArray< ElementType >.ToStringSimple(), and IG.Lib.MultiDimensionalArray< ElementType >.ToStringTest().
ToStringSimple()
string IG.Lib.MultiDimensionalArray< ElementType >.ToStringSimple () inline
Returns a simple string representation of a multidimensional array. Each element is written in its own line starting with element indices and a colon.
Returns
References IG.Lib.MultiDimensionalArray< ElementType >.Dimensions, IG.Lib.MultiDimensionalArray< ElementType >.indices, IG.Lib.MultiDimensionalArray< ElementType >.IndicesToString(), IG.Lib.MultiDimensionalArray< ElementType >.Iterate(), and IG.Lib.MultiDimensionalArray< ElementType >.ToString().
ToStringTest()
string IG.Lib.MultiDimensionalArray< ElementType >.ToStringTest () inline
Returns a simple string representation of a multidimensional array. Each element is written in its own line starting with element indices and a colon.
Returns
References IG.Lib.MultiDimensionalArray< ElementType >.Dimensions, IG.Lib.MultiDimensionalArray< ElementType >.indices, IG.Lib.MultiDimensionalArray< ElementType >.IndicesToString(), IG.Lib.MultiDimensionalArray< ElementType >.Iterate(), and IG.Lib.MultiDimensionalArray< ElementType >.ToString().
Referenced by IG.Lib.MultiDimensionalArray< ElementType >.Example().
ToStringOld()
string IG.Lib.MultiDimensionalArray< ElementType >.ToStringOld () inline
Returns a string representation of a multidimensional array. Each element is written in its own line starting with element indices and a colon.
Returns
References IG.Lib.MultiDimensionalArray< ElementType >._numIndices, IG.Lib.MultiDimensionalArray< ElementType >.Dimension(), IG.Lib.MultiDimensionalArray< ElementType >.Dimensions, IG.Lib.MultiDimensionalArray< ElementType >.indices, IG.Lib.MultiDimensionalArray< ElementType >.IndicesToString(), IG.Lib.MultiDimensionalArray< ElementType >.Iterate(), IG.Lib.MultiDimensionalArray< ElementType >.NumIndices, and IG.Lib.MultiDimensionalArray< ElementType >.ToString().
ToString() [1/2]
override string IG.Lib.MultiDimensionalArray< ElementType >.ToString () inline
Returns a string representation of a multidimensional array in the Mathematica-like set notation.
Elements are written in nested curly brackets.
Referenced by IG.Lib.MultiDimensionalArray< ElementType >.Example(), IG.Lib.MultiDimensionalArray< ElementType >.IndicesToStringNoBrackets(), IG.Lib.MultiDimensionalArray< ElementType >.ToString(), IG.Lib.MultiDimensionalArray< ElementType >.ToStringOld(), IG.Lib.MultiDimensionalArray< ElementType >.ToStringSimple(), and IG.Lib.MultiDimensionalArray< ElementType >.ToStringTest().
ToString() [2/2]
string IG.Lib.MultiDimensionalArray< ElementType >.ToString (bool newLinesLast) inline
Returns a string representation of a multidimensional array in the Mathematica-like set notation.
Elements are written in nested curly brackets.
Parameters
newLinesLast If true then elements of the last level are written with newlines between.
References IG.Lib.MultiDimensionalArray< ElementType >._dimensions, IG.Lib.MultiDimensionalArray< ElementType >._numIndices, IG.Lib.MultiDimensionalArray< ElementType >.Dimensions, IG.Lib.MultiDimensionalArray< ElementType >.indices, IG.Lib.MultiDimensionalArray< ElementType >.IndicesToString(), IG.Lib.MultiDimensionalArray< ElementType >.Iterate(), and IG.Lib.MultiDimensionalArray< ElementType >.ToString().
ExampleFillArray()
static void IG.Lib.MultiDimensionalArray< ElementType >.ExampleFillArray (MultiDimensionalArray< int > array) inline static
Fills the specified multidimensional array of integers in such a way that element values are related to positions within the array in a simple and easily identifiable way.
Parameters
array
References IG.Lib.MultiDimensionalArray< ElementType >.GetIndices(), IG.Lib.MultiDimensionalArray< ElementType >.indices, IG.Lib.MultiDimensionalArray< ElementType >.Lock, IG.Lib.MultiDimensionalArray< ElementType >.NumElements, and IG.Lib.MultiDimensionalArray< ElementType >.NumIndices.
Referenced by IG.Lib.MultiDimensionalArray< ElementType >.Example().
Example() [1/2]
static void IG.Lib.MultiDimensionalArray< ElementType >.Example (params int[] dimensions) inline static
Example of use of multidimensional arrays.
References IG.Lib.MultiDimensionalArray< ElementType >.ExampleFillArray(), IG.Lib.MultiDimensionalArray< ElementType >.ToString(), and IG.Lib.MultiDimensionalArray< ElementType >.ToStringTest().
Referenced by IG.Script.AppTestShell.DataStructuresFunctionTestMultiDimArrayApp().
Example() [2/2]
static void IG.Lib.MultiDimensionalArray< ElementType >.Example () inline static
Example of use of multidimensional arrays.
Member Data Documentation
_lock
readonly object IG.Lib.MultiDimensionalArray< ElementType >._lock = new object() protected
_data
ElementType [] IG.Lib.MultiDimensionalArray< ElementType >._data protected
Referenced by IG.Lib.MultiDimensionalArray< ElementType >.ClearElements().
_dimensions
int [] IG.Lib.MultiDimensionalArray< ElementType >._dimensions protected
Referenced by IG.Lib.MultiDimensionalArray< ElementType >.Dimension(), IG.Lib.MultiDimensionalArray< ElementType >.GetLinearIndex(), IG.Lib.MultiDimensionalArray< ElementType >.IterateAux(), and IG.Lib.MultiDimensionalArray< ElementType >.ToString().
_numIndices
int IG.Lib.MultiDimensionalArray< ElementType >._numIndices protected
Referenced by IG.Lib.MultiDimensionalArray< ElementType >.Dimension(), IG.Lib.MultiDimensionalArray< ElementType >.GetIndices(), IG.Lib.MultiDimensionalArray< ElementType >.GetLinearIndex(), IG.Lib.MultiDimensionalArray< ElementType >.Iterate(), IG.Lib.MultiDimensionalArray< ElementType >.IterateAux(), IG.Lib.MultiDimensionalArray< ElementType >.ToString(), and IG.Lib.MultiDimensionalArray< ElementType >.ToStringOld().
_numElements
int IG.Lib.MultiDimensionalArray< ElementType >._numElements
Referenced by IG.Lib.MultiDimensionalArray< ElementType >.GetIndices(), IG.Lib.MultiDimensionalArray< ElementType >.GetLinearIndex(), and IG.Lib.MultiDimensionalArray< ElementType >.Iterate().
_subTableLengths
int [] IG.Lib.MultiDimensionalArray< ElementType >._subTableLengths protected
Array of subtable lengths. Last element is always one.
Referenced by IG.Lib.MultiDimensionalArray< ElementType >.GetIndices(), and IG.Lib.MultiDimensionalArray< ElementType >.GetLinearIndex().
Property Documentation
Lock
object IG.Lib.MultiDimensionalArray< ElementType >.Lock get
Object used for thread locking.
Referenced by IG.Lib.MultiDimensionalArray< ElementType >.ClearElements(), IG.Lib.MultiDimensionalArray< ElementType >.Dimension(), IG.Lib.MultiDimensionalArray< ElementType >.ExampleFillArray(), IG.Lib.MultiDimensionalArray< ElementType >.GetIndices(), IG.Lib.MultiDimensionalArray< ElementType >.GetLinearIndex(), and IG.Lib.MultiDimensionalArray< ElementType >.Iterate().
Data
ElementType [] IG.Lib.MultiDimensionalArray< ElementType >.Data get set protected
Array containing data of the multidimensional array.
Dimensions
int [] IG.Lib.MultiDimensionalArray< ElementType >.Dimensions get set
Gets or sets dimensions of the multidimensional array.
Getter creates and returns a copy of internal dimensions.
Referenced by IG.Lib.MultiDimensionalArray< ElementType >.MultiDimensionalArray(), IG.Lib.MultiDimensionalArray< ElementType >.SetDimensions(), IG.Lib.MultiDimensionalArray< ElementType >.ToString(), IG.Lib.MultiDimensionalArray< ElementType >.ToStringOld(), IG.Lib.MultiDimensionalArray< ElementType >.ToStringSimple(), and IG.Lib.MultiDimensionalArray< ElementType >.ToStringTest().
NumIndices
int IG.Lib.MultiDimensionalArray< ElementType >.NumIndices get
Gets numbet of indices of the multidimensional array.
Referenced by IG.Lib.MultiDimensionalArray< ElementType >.ExampleFillArray(), and IG.Lib.MultiDimensionalArray< ElementType >.ToStringOld().
NumElements
int IG.Lib.MultiDimensionalArray< ElementType >.NumElements get
Gets total number of elements of the multidimensional array.
Referenced by IG.Lib.MultiDimensionalArray< ElementType >.ExampleFillArray().
SubTableLengths
int [] IG.Lib.MultiDimensionalArray< ElementType >.SubTableLengths get
Gets an array of lengths of the subtables with specified number of indices defined.
Getter creates and returns a copy of internal subtable lengths.
indices
ElementType this[params int[] IG.Lib.MultiDimensionalArray< ElementType >.indices get set
Index operator, gets or sets the specified element of the multidimensional array.
A single index can be specified, treated as linear index of the element in the data array.
Parameters
indices Indices that specify the element of the multidimensional array.
Can either be a full set of indices, or only one linear index (or array with one element) indicating the index of the element in the internal one dimensional data array.
If the array is zero rank then indices can be null.
Referenced by IG.Lib.MultiDimensionalArray< ElementType >.ExampleFillArray(), IG.Lib.MultiDimensionalArray< ElementType >.GetLinearIndex(), IG.Lib.MultiDimensionalArray< ElementType >.IndicesToString(), IG.Lib.MultiDimensionalArray< ElementType >.IndicesToStringNoBrackets(), IG.Lib.MultiDimensionalArray< ElementType >.Iterate(), IG.Lib.MultiDimensionalArray< ElementType >.IterateAux(), IG.Lib.MultiDimensionalArray< ElementType >.ToString(), IG.Lib.MultiDimensionalArray< ElementType >.ToStringOld(), IG.Lib.MultiDimensionalArray< ElementType >.ToStringSimple(), and IG.Lib.MultiDimensionalArray< ElementType >.ToStringTest().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/datastructures/MultiIndexArray.cs