Doc: IGLib EXTENDED: IG.MPetekLib.Application.Scripts.LinearOscillator._02DrivenPlotSolution Class Reference
IG.MPetekLib.Application.Scripts.LinearOscillator._02DrivenPlotSolution Class Reference
Testiram risanje grafov.
Static Public Member Functions
static void Run (string[] arguments)
Performs a driven oscillations test and plots the results.
Detailed Description
Testiram risanje grafov.
Member Function Documentation
Run()
static void IG.MPetekLib.Application.Scripts.LinearOscillator._02DrivenPlotSolution.Run (string[] arguments) inline static
Performs a driven oscillations test and plots the results.
Plotting is performed in the main thread.
References IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.AngularFrequencySquare, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.DampingCoefficient, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.DrivingAngularFrequency, IG.MPetekLib.Algorithms.Solvers.InitialProblemODE_RK4.InitialProblemSolverBase.EndPoint, IG.MPetekLib.Algorithms.PlottableModels.PlottableODEModelBase.InitialConditions, IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LinesVisible, IG.Gr.PlotZedgraphCurve.LineWidth, IG.MPetekLib.Algorithms.Plotting.PlotHQ.Plotter, IG.Gr.PlotZedgraphCurve.PointColor, IG.Gr.PlotZedgraphCurve.PointSize, IG.Gr.PlotZedgraphCurve.PointsVisible, IG.MPetekLib.Algorithms.Plotting.PlotHQ.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.PlottableODEModelBase.SolveNumerically(), IG.MPetekLib.Algorithms.PlottableModels.PlottableODEModelBase.Solver, IG.MPetekLib.Algorithms.Solvers.InitialProblemODE_RK4.InitialProblemSolverBase.StepSize, IG.Gr.PlotterZedGraph.Title, IG.MPetekLib.Algorithms.Plotting.PlotHQ.Window, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.X_vs_T(), IG.Gr.PlotterZedGraph.XAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabel.
Referenced by IG.Script.AppMarkoPetek.App02DrivenPlotSolution().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/Guest_Marko_Petek_Lib/application/scripts/LinearOscillator/02DrivenPlotSolution.cs