Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGEEV Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGEEV Class Reference
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGEEV (DGEBAK dgebak, DGEBAL dgebal, DGEHRD dgehrd, DHSEQR dhseqr, DLABAD dlabad, DLACPY dlacpy, DLARTG dlartg, DLASCL dlascl, DORGHR dorghr, DROT drot, DSCAL dscal, DTREVC dtrevc, XERBLA xerbla, LSAME lsame, IDAMAX idamax, ILAENV ilaenv, DLAMCH dlamch, DLANGE dlange, DLAPY2 dlapy2, DNRM2 dnrm2)
DGEEV ()
void Run (string JOBVL, string JOBVR, int N, ref double[] A, int offset_a, int LDA, ref double[] WR, int offset_wr, ref double[] WI, int offset_wi, ref double[] VL, int offset_vl, int LDVL, ref double[] VR, int offset_vr, int LDVR, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
DGEBAK _dgebak
DGEBAL _dgebal
DGEHRD _dgehrd
DHSEQR _dhseqr
DLABAD _dlabad
DLACPY _dlacpy
DLARTG _dlartg
DLASCL _dlascl
DORGHR _dorghr
DROT _drot
DSCAL _dscal
DTREVC _dtrevc
XERBLA _xerbla
LSAME _lsame
IDAMAX _idamax
ILAENV _ilaenv
DLAMCH _dlamch
DLANGE _dlange
DLAPY2 _dlapy2
DNRM2 _dnrm2
bool[] SELECT = new bool[1]
double[] DUM = new double[1]
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
Detailed Description
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGEEV computes for an N-by-N real nonsymmetric matrix A, the eigenvalues and, optionally, the left and/or right eigenvectors.
The right eigenvector v(j) of A satisfies A * v(j) = lambda(j) * v(j) where lambda(j) is its eigenvalue. The left eigenvector u(j) of A satisfies u(j)**H * A = lambda(j) * u(j)**H where u(j)**H denotes the conjugate transpose of u(j).
The computed eigenvectors are normalized to have Euclidean norm equal to 1 and largest component real.
/summary>
Constructor & Destructor Documentation
DGEEV() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGEEV.DGEEV (DGEBAK dgebak, DGEBAL dgebal, DGEHRD dgehrd, DHSEQR dhseqr, DLABAD dlabad, DLACPY dlacpy, DLARTG dlartg, DLASCL dlascl, DORGHR dorghr, DROT drot, DSCAL dscal, DTREVC dtrevc, XERBLA xerbla, LSAME lsame, IDAMAX idamax, ILAENV ilaenv, DLAMCH dlamch, DLANGE dlange, DLAPY2 dlapy2, DNRM2 dnrm2) inline
DGEEV() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGEEV.DGEEV () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run (string JOBVL, string JOBVR, int N, ref double[] A, int offset_a, int LDA, ref double[] WR, int offset_wr, ref double[] WI, int offset_wi, ref double[] VL, int offset_vl, int LDVL, ref double[] VR, int offset_vr, int LDVR, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DGEEV computes for an N-by-N real nonsymmetric matrix A, the eigenvalues and, optionally, the left and/or right eigenvectors.
The right eigenvector v(j) of A satisfies A * v(j) = lambda(j) * v(j) where lambda(j) is its eigenvalue. The left eigenvector u(j) of A satisfies u(j)**H * A = lambda(j) * u(j)**H where u(j)**H denotes the conjugate transpose of u(j).
The computed eigenvectors are normalized to have Euclidean norm equal to 1 and largest component real.
/summary>
Parameters
JOBVL (input) CHARACTER*1 = 'N': left eigenvectors of A are not computed; = 'V': left eigenvectors of A are computed. /param>
Parameters
JOBVR (input) CHARACTER*1 = 'N': right eigenvectors of A are not computed; = 'V': right eigenvectors of A are computed. /param>
Parameters
N (input) INTEGER The order of the matrix A. N .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the N-by-N matrix A. On exit, A has been overwritten. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,N). /param>
Parameters
WR (output) DOUBLE PRECISION array, dimension (N) /param>
Parameters
WI (output) DOUBLE PRECISION array, dimension (N) WR and WI contain the real and imaginary parts, respectively, of the computed eigenvalues. Complex conjugate pairs of eigenvalues appear consecutively with the eigenvalue having the positive imaginary part first. /param>
Parameters
VL (output) DOUBLE PRECISION array, dimension (LDVL,N) If JOBVL = 'V', the left eigenvectors u(j) are stored one after another in the columns of VL, in the same order as their eigenvalues. If JOBVL = 'N', VL is not referenced. If the j-th eigenvalue is real, then u(j) = VL(:,j), the j-th column of VL. If the j-th and (j+1)-st eigenvalues form a complex conjugate pair, then u(j) = VL(:,j) + i*VL(:,j+1) and u(j+1) = VL(:,j) - i*VL(:,j+1). /param>
Parameters
LDVL (input) INTEGER The leading dimension of the array VL. LDVL .GE. 1; if JOBVL = 'V', LDVL .GE. N. /param>
Parameters
VR (output) DOUBLE PRECISION array, dimension (LDVR,N) If JOBVR = 'V', the right eigenvectors v(j) are stored one after another in the columns of VR, in the same order as their eigenvalues. If JOBVR = 'N', VR is not referenced. If the j-th eigenvalue is real, then v(j) = VR(:,j), the j-th column of VR. If the j-th and (j+1)-st eigenvalues form a complex conjugate pair, then v(j) = VR(:,j) + i*VR(:,j+1) and v(j+1) = VR(:,j) - i*VR(:,j+1). /param>
Parameters
LDVR (input) INTEGER The leading dimension of the array VR. LDVR .GE. 1; if JOBVR = 'V', LDVR .GE. N. /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. max(1,3*N), and if JOBVL = 'V' or JOBVR = 'V', LWORK .GE. 4*N. For good performance, LWORK must generally be larger.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value. .GT. 0: if INFO = i, the QR algorithm failed to compute all the eigenvalues, and no eigenvectors have been computed; elements i+1:N of WR and WI contain eigenvalues which have converged. /param>
References DotNumerics.FortranLibrary.FortranLib.Copy(), DotNumerics.LinearAlgebra.CSLapack.DGEEV.DUM, DotNumerics.LinearAlgebra.CSLapack.DGEEV.ONE, DotNumerics.LinearAlgebra.CSLapack.DROT.Run(), DotNumerics.LinearAlgebra.CSLapack.DNRM2.Run(), DotNumerics.LinearAlgebra.CSLapack.IDAMAX.Run(), DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAPY2.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLABAD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARTG.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBAK.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANGE.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGHR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBAL.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEHRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DTREVC.Run(), DotNumerics.LinearAlgebra.CSLapack.DHSEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEEV.SELECT, and DotNumerics.LinearAlgebra.CSLapack.DGEEV.ZERO.
Member Data Documentation
_dgebak
DGEBAK DotNumerics.LinearAlgebra.CSLapack.DGEEV._dgebak private
_dgebal
DGEBAL DotNumerics.LinearAlgebra.CSLapack.DGEEV._dgebal private
_dgehrd
DGEHRD DotNumerics.LinearAlgebra.CSLapack.DGEEV._dgehrd private
_dhseqr
DHSEQR DotNumerics.LinearAlgebra.CSLapack.DGEEV._dhseqr private
_dlabad
DLABAD DotNumerics.LinearAlgebra.CSLapack.DGEEV._dlabad private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DGEEV._dlacpy private
_dlartg
DLARTG DotNumerics.LinearAlgebra.CSLapack.DGEEV._dlartg private
_dlascl
DLASCL DotNumerics.LinearAlgebra.CSLapack.DGEEV._dlascl private
_dorghr
DORGHR DotNumerics.LinearAlgebra.CSLapack.DGEEV._dorghr private
_drot
DROT DotNumerics.LinearAlgebra.CSLapack.DGEEV._drot private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DGEEV._dscal private
_dtrevc
DTREVC DotNumerics.LinearAlgebra.CSLapack.DGEEV._dtrevc private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGEEV._xerbla private
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DGEEV._lsame private
_idamax
IDAMAX DotNumerics.LinearAlgebra.CSLapack.DGEEV._idamax private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DGEEV._ilaenv private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DGEEV._dlamch private
_dlange
DLANGE DotNumerics.LinearAlgebra.CSLapack.DGEEV._dlange private
_dlapy2
DLAPY2 DotNumerics.LinearAlgebra.CSLapack.DGEEV._dlapy2 private
_dnrm2
DNRM2 DotNumerics.LinearAlgebra.CSLapack.DGEEV._dnrm2 private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DGEEV.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGEEV.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run().
SELECT
bool [] DotNumerics.LinearAlgebra.CSLapack.DGEEV.SELECT = new bool[1] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run().
DUM
double [] DotNumerics.LinearAlgebra.CSLapack.DGEEV.DUM = new double[1] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgeev.cs