Doc: IGLib EXTENDED: IG.Physics.ChemicalElementDtoBase< ChemicalElementType > Class Template Reference
IG.Physics.ChemicalElementDtoBase< ChemicalElementType > Class Template Reference abstract
Base class for various DTOs (Data Transfer Objects) for chemical elements and derived classes.
Public Member Functions
ChemicalElementDtoBase ()
Default constructor, sets IsNull to true.
ChemicalElementDtoBase (ChemicalElementType element)
Constructor, prepares the current DTO for storing a specific chemical element.
abstract ChemicalElementType CreateElement ()
Creates and returns a new chemical element.
override ChemicalElementType CreateObject ()
Creates and returns a new chemical element of the appropriate type.
Public Member Functions inherited from IG.Lib.SerializationDtoBase< ChemicalElementType, ChemicalElement >
SerializationDtoBase ()
virtual bool GetNull ()
Returns a flag indicating whether the object represented by the current DTO is null.
virtual void SetNull (bool isNull)
Sets a flag indicating whether the object represented by the current DTO is null.
virtual void CopyFromBase (BaseType obj)
Copies data to the current DTO from an object of type BaseType.
virtual void CopyToBase (ref BaseType obj)
Copies data from the current DTO to an object of the base type. Object is created anew if necessary by using the CreateObject() method.
virtual void CopyFrom (Type obj)
Copies data to the current DTO from an object of type Type.
virtual void CopyTo (ref Type obj)
Copies data from the current DTO to an object of type Type. Object is created anew if necessary by using the CreateObject() method.
virtual void CopyFromObject (object obj)
Copies data to the current DTO from an object of type object. The necessary casts are performed.
virtual void CopyToObject (ref object obj)
Copies data from the current DTO to an object of type object. Object is created anew if necessary by using the CreateObject() method. The necessary casts are performed.
override string ToString ()
Creates and returns string representation of the current DTO (data transfer object).
Public Attributes
ChemicalElements Element
Enum of type ChemicalElements specifying which chemical element this is.
string Symbol
Chemical element's symbol.
string Name
Long name of the chemical element.
int AtomicNumber
Atomic number of the chemical element.
double AtomicWeight
Standard atomic weight in atomic mass units.
ChemicalElementPropertiesDto Properties
Protected Member Functions
override void CopyFromPlain (ChemicalElement element)
Copies data to the current DTO from a chemical element object.
override void CopyToPlain (ref ChemicalElement element)
Copies data from the current DTO to a chemical element object.
Protected Member Functions inherited from IG.Lib.SerializationDtoBase< ChemicalElementType, ChemicalElement >
abstract void CopyFromPlain (BaseType obj)
Copies contents of the specified object to the current DTO (Data Transfer Object).
abstract void CopyToPlain (ref BaseType obj)
Copies contents of the current DTO (Data Transfer Object) to the specified object.
Additional Inherited Members
Protected Attributes inherited from IG.Lib.SerializationDtoBase< ChemicalElementType, ChemicalElement >
bool _isNull
Properties inherited from IG.Lib.SerializationDtoBase< ChemicalElementType, ChemicalElement >
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Detailed Description
Base class for various DTOs (Data Transfer Objects) for chemical elements and derived classes.
Used to store a state of a chemical element.
Template Parameters
ChemicalElementType Type parameter specifying the specific chemical element type for which concrete DTO is designed.
$A Igor Oct09;
Type Constraints
ChemicalElementType : ChemicalElement
Constructor & Destructor Documentation
ChemicalElementDtoBase() [1/2]
IG.Physics.ChemicalElementDtoBase< ChemicalElementType >.ChemicalElementDtoBase () inline
Default constructor, sets IsNull to true.
ChemicalElementDtoBase() [2/2]
IG.Physics.ChemicalElementDtoBase< ChemicalElementType >.ChemicalElementDtoBase (ChemicalElementType element) inline
Constructor, prepares the current DTO for storing a specific chemical element.
Parameters
length Element whose data is stored in the current DTO.
Member Function Documentation
CreateElement()
abstract ChemicalElementType IG.Physics.ChemicalElementDtoBase< ChemicalElementType >.CreateElement () pure virtual
Creates and returns a new chemical element.
Implemented in IG.Physics.ChemicalElementQuantityDto, and IG.Physics.ChemicalElementDto.
Referenced by IG.Physics.ChemicalElementDtoBase< ChemicalElementQuantity >.CreateObject().
CreateObject()
override ChemicalElementType IG.Physics.ChemicalElementDtoBase< ChemicalElementType >.CreateObject () inline virtual
Creates and returns a new chemical element of the appropriate type.
Implements IG.Lib.SerializationDtoBase< ChemicalElementType, ChemicalElement >.
Referenced by ChemicalCompoundDto.CopyToPlain(), and IG.Physics.ChemicalElementDtoBase< ChemicalElementQuantity >.CopyToPlain().
CopyFromPlain()
override void IG.Physics.ChemicalElementDtoBase< ChemicalElementType >.CopyFromPlain (ChemicalElement element) inline protected
Copies data to the current DTO from a chemical element object.
Parameters
element Chemical element object from which data is copied.
CopyToPlain()
override void IG.Physics.ChemicalElementDtoBase< ChemicalElementType >.CopyToPlain (ref ChemicalElement element) inline protected
Copies data from the current DTO to a chemical element object.
Parameters
element Chemical element object that data is copied to.
Member Data Documentation
Element
ChemicalElements IG.Physics.ChemicalElementDtoBase< ChemicalElementType >.Element
Enum of type ChemicalElements specifying which chemical element this is.
Referenced by IG.Physics.ChemicalElementDtoBase< ChemicalElementQuantity >.CopyToPlain().
Symbol
string IG.Physics.ChemicalElementDtoBase< ChemicalElementType >.Symbol
Chemical element's symbol.
Referenced by IG.Physics.ChemicalElementDtoBase< ChemicalElementQuantity >.CopyToPlain().
Name
string IG.Physics.ChemicalElementDtoBase< ChemicalElementType >.Name
Long name of the chemical element.
Referenced by IG.Physics.ChemicalElementDtoBase< ChemicalElementQuantity >.CopyToPlain().
AtomicNumber
int IG.Physics.ChemicalElementDtoBase< ChemicalElementType >.AtomicNumber
Atomic number of the chemical element.
Referenced by IG.Physics.ChemicalElementDtoBase< ChemicalElementQuantity >.CopyToPlain().
AtomicWeight
double IG.Physics.ChemicalElementDtoBase< ChemicalElementType >.AtomicWeight
Standard atomic weight in atomic mass units.
Referenced by IG.Physics.ChemicalElementDtoBase< ChemicalElementQuantity >.CopyToPlain().
Properties
ChemicalElementPropertiesDto IG.Physics.ChemicalElementDtoBase< ChemicalElementType >.Properties
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/physics/chemistry/dtos/ChemicalElementDto.cs