Doc: IGLib EXTENDED: IG.Forms.DialogFormDemoControl Class Reference
IG.Forms.DialogFormDemoControl Class Reference
Public Member Functions
DialogFormDemoControl ()
void CreateNewDialogWindow ()
Creates a new testing dialog window.
void CopyDataToDialogs ()
Applies all data and settings forom the current control to the embedded and window test dialogs.
void CopyButtonDataToDialogs ()
Applies all data and settings forom the current control to the embedded and window test dialogs.
DialogFormDemoControl ()
void CreateNewDialogWindow ()
Creates a new testing dialog window.
void CopyDataToDialogs ()
Applies all data and settings forom the current control to the embedded and window test dialogs.
void CopyButtonDataToDialogs ()
Applies all data and settings forom the current control to the embedded and window test dialogs.
DialogFormDemoControl ()
void CreateNewDialogWindow ()
Creates a new testing dialog window.
void CopyDataToDialogs ()
Applies all data and settings forom the current control to the embedded and window test dialogs.
void CopyButtonDataToDialogs ()
Applies all data and settings forom the current control to the embedded and window test dialogs.
Protected Member Functions
void UpdateResults ()
Updates controls that stow dialog's results.
override void Dispose (bool disposing)
Clean up any resources being used.
void UpdateResults ()
Updates controls that stow dialog's results.
override void Dispose (bool disposing)
Clean up any resources being used.
void UpdateResults ()
Updates controls that stow dialog's results.
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
bool IsDialogFormActive [get]
Returns true if the dialog form is active, i. e. if it is located, visible, and not yet disposed.
Private Member Functions
void txtTitle_TextChanged (object sender, EventArgs e)
void txtTitle_Validated (object sender, EventArgs e)
void txtMessage_TextChanged (object sender, EventArgs e)
void txtMessage_Validated (object sender, EventArgs e)
void txtText_TextChanged (object sender, EventArgs e)
void txtText_Validated (object sender, EventArgs e)
void textBotxtButtons_TextChanged (object sender, EventArgs e)
void textBotxtButtons_Validated (object sender, EventArgs e)
void chkImmediateText_CheckedChanged (object sender, EventArgs e)
void btnLaunchDialog_Click (object sender, EventArgs e)
void btnRefreshDialog_Click (object sender, EventArgs e)
void btnRefreshText_Click (object sender, EventArgs e)
void chkTextVisible_CheckedChanged (object sender, EventArgs e)
void chkTextCausesVisible_CheckedChanged (object sender, EventArgs e)
void chkTextEditable_CheckedChanged (object sender, EventArgs e)
void chkTextSettable_CheckedChanged (object sender, EventArgs e)
void chkTextSetExceptions_CheckedChanged (object sender, EventArgs e)
void chkTextMultiLine_CheckedChanged (object sender, EventArgs e)
void chkTextImmediate_CheckedChanged (object sender, EventArgs e)
void chkTextPassword_CheckedChanged (object sender, EventArgs e)
void numTextBoxWidth_Validated (object sender, EventArgs e)
void numTextBoxHeight_Validated (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void txtTitle_TextChanged (object sender, EventArgs e)
void txtTitle_Validated (object sender, EventArgs e)
void txtMessage_TextChanged (object sender, EventArgs e)
void txtMessage_Validated (object sender, EventArgs e)
void txtText_TextChanged (object sender, EventArgs e)
void txtText_Validated (object sender, EventArgs e)
void textBotxtButtons_TextChanged (object sender, EventArgs e)
void textBotxtButtons_Validated (object sender, EventArgs e)
void chkImmediateText_CheckedChanged (object sender, EventArgs e)
void btnLaunchDialog_Click (object sender, EventArgs e)
void btnRefreshDialog_Click (object sender, EventArgs e)
void btnRefreshText_Click (object sender, EventArgs e)
void chkTextVisible_CheckedChanged (object sender, EventArgs e)
void chkTextCausesVisible_CheckedChanged (object sender, EventArgs e)
void chkTextEditable_CheckedChanged (object sender, EventArgs e)
void chkTextSettable_CheckedChanged (object sender, EventArgs e)
void chkTextSetExceptions_CheckedChanged (object sender, EventArgs e)
void chkTextMultiLine_CheckedChanged (object sender, EventArgs e)
void chkTextImmediate_CheckedChanged (object sender, EventArgs e)
void chkTextPassword_CheckedChanged (object sender, EventArgs e)
void numTextBoxWidth_Validated (object sender, EventArgs e)
void numTextBoxHeight_Validated (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void txtTitle_TextChanged (object sender, EventArgs e)
void txtTitle_Validated (object sender, EventArgs e)
void txtMessage_TextChanged (object sender, EventArgs e)
void txtMessage_Validated (object sender, EventArgs e)
void txtText_TextChanged (object sender, EventArgs e)
void txtText_Validated (object sender, EventArgs e)
void textBotxtButtons_TextChanged (object sender, EventArgs e)
void textBotxtButtons_Validated (object sender, EventArgs e)
void chkImmediateText_CheckedChanged (object sender, EventArgs e)
void btnLaunchDialog_Click (object sender, EventArgs e)
void btnRefreshDialog_Click (object sender, EventArgs e)
void btnRefreshText_Click (object sender, EventArgs e)
void chkTextVisible_CheckedChanged (object sender, EventArgs e)
void chkTextCausesVisible_CheckedChanged (object sender, EventArgs e)
void chkTextEditable_CheckedChanged (object sender, EventArgs e)
void chkTextSettable_CheckedChanged (object sender, EventArgs e)
void chkTextSetExceptions_CheckedChanged (object sender, EventArgs e)
void chkTextMultiLine_CheckedChanged (object sender, EventArgs e)
void chkTextImmediate_CheckedChanged (object sender, EventArgs e)
void chkTextPassword_CheckedChanged (object sender, EventArgs e)
void numTextBoxWidth_Validated (object sender, EventArgs e)
void numTextBoxHeight_Validated (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
DialogControl dialogControl1
DialogForm dialogForm1
System.Windows.Forms.Label lblMainTitle
System.Windows.Forms.Label lblTitle
System.Windows.Forms.TextBox txtTitle
System.Windows.Forms.TextBox txtMessage
System.Windows.Forms.Label lblMessage
System.Windows.Forms.Label lblText
System.Windows.Forms.TextBox txtText
System.Windows.Forms.Label lblButtons
System.Windows.Forms.TextBox textBotxtButtons
System.Windows.Forms.GroupBox grpResults
System.Windows.Forms.Label lblResultText
System.Windows.Forms.Label lblResultButton
System.Windows.Forms.Label lblResultTitleText
System.Windows.Forms.Label lblResultTitleButton
System.Windows.Forms.GroupBox grpDialogControl
System.Windows.Forms.FlowLayoutPanel flowDialogControlAndResults
System.Windows.Forms.Button btnLaunchDialog
System.Windows.Forms.Button btnRefreshDialog
System.Windows.Forms.GroupBox grpSettings
System.Windows.Forms.CheckBox chkTextEditable
System.Windows.Forms.CheckBox chkTextMultiLine
System.Windows.Forms.CheckBox chkTextSettable
System.Windows.Forms.CheckBox chkImmediateText
System.Windows.Forms.NumericUpDown numTextBoxHeight
System.Windows.Forms.NumericUpDown numTextBoxWidth
System.Windows.Forms.Label lblTextBoxWidth
System.Windows.Forms.GroupBox grpEvents
System.Windows.Forms.Label lblTextBoxHeight
IndicatorLight indicatorButtonResultChanged
IndicatorLight indicatorTextChanged
IndicatorLight indicatorButtonPressed
System.Windows.Forms.Button btnRefreshText
System.Windows.Forms.CheckBox chkTextSetExceptions
IndicatorLight indicatorSettingsApplied
System.Windows.Forms.CheckBox chkTextVisible
System.Windows.Forms.CheckBox chkTextImmediate
System.Windows.Forms.GroupBox grpActions
System.Windows.Forms.CheckBox chkTextCausesVisible
System.Windows.Forms.CheckBox chkTextPassword
Constructor & Destructor Documentation
DialogFormDemoControl() [1/3]
IG.Forms.DialogFormDemoControl.DialogFormDemoControl () inline
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.DialogControl.ButtonPressed, IG.Forms.DialogControl.ButtonResultChanged, IG.Forms.DialogFormDemoControl.CopyButtonDataToDialogs(), IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.indicatorButtonPressed, IG.Forms.DialogFormDemoControl.indicatorButtonResultChanged, IG.Forms.DialogFormDemoControl.indicatorTextChanged, IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.DialogFormDemoControl.IsDialogFormActive, IG.Forms.DialogControl.Text, IG.Forms.DialogControl.TextChanged, and IG.Forms.DialogFormDemoControl.UpdateResults().
DialogFormDemoControl() [2/3]
IG.Forms.DialogFormDemoControl.DialogFormDemoControl () inline
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.DialogControl.ButtonPressed, IG.Forms.DialogControl.ButtonResultChanged, IG.Forms.DialogFormDemoControl.CopyButtonDataToDialogs(), IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.indicatorButtonPressed, IG.Forms.DialogFormDemoControl.indicatorButtonResultChanged, IG.Forms.DialogFormDemoControl.indicatorTextChanged, IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.DialogFormDemoControl.IsDialogFormActive, IG.Forms.DialogControl.Text, IG.Forms.DialogControl.TextChanged, and IG.Forms.DialogFormDemoControl.UpdateResults().
DialogFormDemoControl() [3/3]
IG.Forms.DialogFormDemoControl.DialogFormDemoControl () inline
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.DialogControl.ButtonPressed, IG.Forms.DialogControl.ButtonResultChanged, IG.Forms.DialogFormDemoControl.CopyButtonDataToDialogs(), IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.indicatorButtonPressed, IG.Forms.DialogFormDemoControl.indicatorButtonResultChanged, IG.Forms.DialogFormDemoControl.indicatorTextChanged, IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.DialogFormDemoControl.IsDialogFormActive, IG.Forms.DialogControl.Text, IG.Forms.DialogControl.TextChanged, and IG.Forms.DialogFormDemoControl.UpdateResults().
Member Function Documentation
CreateNewDialogWindow() [1/3]
void IG.Forms.DialogFormDemoControl.CreateNewDialogWindow () inline
Creates a new testing dialog window.
References IG.Forms.IndicatorLight.BlinkError(), IG.Forms.IndicatorLight.BlinkOk(), IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.DialogControl.ButtonPressed, IG.Forms.DialogControl.ButtonResultChanged, IG.Forms.DialogFormDemoControl.CopyButtonDataToDialogs(), IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.dialogForm1, IG.Forms.DialogFormDemoControl.indicatorButtonPressed, IG.Forms.DialogFormDemoControl.indicatorButtonResultChanged, IG.Forms.DialogFormDemoControl.indicatorTextChanged, IG.Forms.DialogForm.MainControl, IG.Forms.DialogControl.Text, IG.Forms.DialogControl.TextChanged, and IG.Forms.DialogFormDemoControl.UpdateResults().
Referenced by IG.Forms.DialogFormDemoControl.btnLaunchDialog_Click(), and IG.Forms.DialogFormDemoControl.btnRefreshDialog_Click().
UpdateResults() [1/3]
void IG.Forms.DialogFormDemoControl.UpdateResults () inline protected
Updates controls that stow dialog's results.
References IG.Forms.DialogForm.ButtonResult, IG.Forms.DialogControl.ButtonResult, IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.dialogForm1, IG.Forms.DialogFormDemoControl.lblResultButton, IG.Forms.DialogFormDemoControl.lblResultText, IG.Forms.DialogForm.Text, IG.Forms.DialogControl.Text, and IG.Forms.DialogFormDemoControl.txtText.
Referenced by IG.Forms.DialogFormDemoControl.btnLaunchDialog_Click(), IG.Forms.DialogFormDemoControl.btnRefreshDialog_Click(), IG.Forms.DialogFormDemoControl.btnRefreshText_Click(), IG.Forms.DialogFormDemoControl.CreateNewDialogWindow(), and IG.Forms.DialogFormDemoControl.DialogFormDemoControl().
CopyDataToDialogs() [1/3]
void IG.Forms.DialogFormDemoControl.CopyDataToDialogs () inline
Applies all data and settings forom the current control to the embedded and window test dialogs.
This does not copy the buttons data, which is performed specially by the CopyButtonDataToDialogs function.
References IG.Forms.IndicatorLight.BlinkOk(), IG.Forms.DialogFormDemoControl.chkTextCausesVisible, IG.Forms.DialogFormDemoControl.chkTextEditable, IG.Forms.DialogFormDemoControl.chkTextImmediate, IG.Forms.DialogFormDemoControl.chkTextMultiLine, IG.Forms.DialogFormDemoControl.chkTextPassword, IG.Forms.DialogFormDemoControl.chkTextSetExceptions, IG.Forms.DialogFormDemoControl.chkTextSettable, IG.Forms.DialogFormDemoControl.chkTextVisible, IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.dialogForm1, IG.Forms.DialogFormDemoControl.indicatorSettingsApplied, IG.Forms.DialogForm.IsTextCausesVisible, IG.Forms.DialogControl.IsTextCausesVisible, IG.Forms.DialogForm.IsTextChangedEventOnValidationOnly, IG.Forms.DialogControl.IsTextChangedEventOnValidationOnly, IG.Forms.DialogForm.IsTextEditable, IG.Forms.DialogControl.IsTextEditable, IG.Forms.DialogForm.IsTextMultiLine, IG.Forms.DialogControl.IsTextMultiLine, IG.Forms.DialogForm.IsTextPassword, IG.Forms.DialogControl.IsTextPassword, IG.Forms.DialogForm.IsTextSettable, IG.Forms.DialogControl.IsTextSettable, IG.Forms.DialogForm.IsTextSetThrows, IG.Forms.DialogControl.IsTextSetThrows, IG.Forms.DialogForm.IsTextVisible, IG.Forms.DialogControl.IsTextVisible, IG.Forms.DialogForm.Message, IG.Forms.DialogControl.Message, IG.Forms.DialogFormDemoControl.numTextBoxHeight, IG.Forms.DialogFormDemoControl.numTextBoxWidth, IG.Forms.DialogForm.Text, IG.Forms.DialogControl.Text, IG.Forms.DialogForm.TextBoxHeight, IG.Forms.DialogControl.TextBoxHeight, IG.Forms.DialogForm.TextBoxWidth, IG.Forms.DialogControl.TextBoxWidth, IG.Forms.DialogForm.Title, IG.Forms.DialogControl.Title, IG.Forms.DialogFormDemoControl.txtMessage, IG.Forms.DialogFormDemoControl.txtText, and IG.Forms.DialogFormDemoControl.txtTitle.
Referenced by IG.Forms.DialogFormDemoControl.btnLaunchDialog_Click(), IG.Forms.DialogFormDemoControl.btnRefreshDialog_Click(), IG.Forms.DialogFormDemoControl.chkTextCausesVisible_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextEditable_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextImmediate_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextMultiLine_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextPassword_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextSetExceptions_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextSettable_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextVisible_CheckedChanged(), IG.Forms.DialogFormDemoControl.CreateNewDialogWindow(), IG.Forms.DialogFormDemoControl.DialogFormDemoControl(), IG.Forms.DialogFormDemoControl.numTextBoxHeight_Validated(), IG.Forms.DialogFormDemoControl.numTextBoxWidth_Validated(), IG.Forms.DialogFormDemoControl.txtMessage_TextChanged(), IG.Forms.DialogFormDemoControl.txtMessage_Validated(), IG.Forms.DialogFormDemoControl.txtText_TextChanged(), IG.Forms.DialogFormDemoControl.txtText_Validated(), IG.Forms.DialogFormDemoControl.txtTitle_TextChanged(), and IG.Forms.DialogFormDemoControl.txtTitle_Validated().
CopyButtonDataToDialogs() [1/3]
void IG.Forms.DialogFormDemoControl.CopyButtonDataToDialogs () inline
Applies all data and settings forom the current control to the embedded and window test dialogs.
This does not copy the buttons data, which is performed specially by the CopyButtonDataToDialogs function.
References IG.Forms.IndicatorLight.BlinkBusy(), IG.Forms.DialogForm.Buttons, IG.Forms.DialogControl.Buttons, IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.dialogForm1, IG.Forms.DialogFormDemoControl.indicatorSettingsApplied, and IG.Forms.DialogFormDemoControl.textBotxtButtons.
Referenced by IG.Forms.DialogFormDemoControl.btnRefreshDialog_Click(), IG.Forms.DialogFormDemoControl.CreateNewDialogWindow(), IG.Forms.DialogFormDemoControl.DialogFormDemoControl(), and IG.Forms.DialogFormDemoControl.textBotxtButtons_Validated().
txtTitle_TextChanged() [1/3]
void IG.Forms.DialogFormDemoControl.txtTitle_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.chkImmediateText, and IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
txtTitle_Validated() [1/3]
void IG.Forms.DialogFormDemoControl.txtTitle_Validated (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
txtMessage_TextChanged() [1/3]
void IG.Forms.DialogFormDemoControl.txtMessage_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.chkImmediateText, and IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
txtMessage_Validated() [1/3]
void IG.Forms.DialogFormDemoControl.txtMessage_Validated (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
txtText_TextChanged() [1/3]
void IG.Forms.DialogFormDemoControl.txtText_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.chkImmediateText, and IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
txtText_Validated() [1/3]
void IG.Forms.DialogFormDemoControl.txtText_Validated (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
textBotxtButtons_TextChanged() [1/3]
void IG.Forms.DialogFormDemoControl.textBotxtButtons_TextChanged (object sender, EventArgs e) inline private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
textBotxtButtons_Validated() [1/3]
void IG.Forms.DialogFormDemoControl.textBotxtButtons_Validated (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyButtonDataToDialogs().
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
chkImmediateText_CheckedChanged() [1/3]
void IG.Forms.DialogFormDemoControl.chkImmediateText_CheckedChanged (object sender, EventArgs e) inline private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
btnLaunchDialog_Click() [1/3]
void IG.Forms.DialogFormDemoControl.btnLaunchDialog_Click (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), IG.Forms.DialogFormDemoControl.CreateNewDialogWindow(), and IG.Forms.DialogFormDemoControl.UpdateResults().
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
btnRefreshDialog_Click() [1/3]
void IG.Forms.DialogFormDemoControl.btnRefreshDialog_Click (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyButtonDataToDialogs(), IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), IG.Forms.DialogFormDemoControl.CreateNewDialogWindow(), IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.dialogForm1, and IG.Forms.DialogFormDemoControl.UpdateResults().
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
btnRefreshText_Click() [1/3]
void IG.Forms.DialogFormDemoControl.btnRefreshText_Click (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.UpdateResults().
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
chkTextVisible_CheckedChanged() [1/3]
void IG.Forms.DialogFormDemoControl.chkTextVisible_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
chkTextCausesVisible_CheckedChanged() [1/3]
void IG.Forms.DialogFormDemoControl.chkTextCausesVisible_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
chkTextEditable_CheckedChanged() [1/3]
void IG.Forms.DialogFormDemoControl.chkTextEditable_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
chkTextSettable_CheckedChanged() [1/3]
void IG.Forms.DialogFormDemoControl.chkTextSettable_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
chkTextSetExceptions_CheckedChanged() [1/3]
void IG.Forms.DialogFormDemoControl.chkTextSetExceptions_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
chkTextMultiLine_CheckedChanged() [1/3]
void IG.Forms.DialogFormDemoControl.chkTextMultiLine_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
chkTextImmediate_CheckedChanged() [1/3]
void IG.Forms.DialogFormDemoControl.chkTextImmediate_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
chkTextPassword_CheckedChanged() [1/3]
void IG.Forms.DialogFormDemoControl.chkTextPassword_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
numTextBoxWidth_Validated() [1/3]
void IG.Forms.DialogFormDemoControl.numTextBoxWidth_Validated (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
numTextBoxHeight_Validated() [1/3]
void IG.Forms.DialogFormDemoControl.numTextBoxHeight_Validated (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
Dispose() [1/3]
override void IG.Forms.DialogFormDemoControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.DialogFormDemoControl.components.
InitializeComponent() [1/3]
void IG.Forms.DialogFormDemoControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.DialogFormDemoControl.btnLaunchDialog, IG.Forms.DialogFormDemoControl.btnLaunchDialog_Click(), IG.Forms.DialogFormDemoControl.btnRefreshDialog, IG.Forms.DialogFormDemoControl.btnRefreshDialog_Click(), IG.Forms.DialogFormDemoControl.btnRefreshText, IG.Forms.DialogFormDemoControl.btnRefreshText_Click(), IG.Forms.DialogControl.Buttons, IG.Forms.DialogFormDemoControl.chkImmediateText, IG.Forms.DialogFormDemoControl.chkImmediateText_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextCausesVisible, IG.Forms.DialogFormDemoControl.chkTextCausesVisible_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextEditable, IG.Forms.DialogFormDemoControl.chkTextEditable_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextImmediate, IG.Forms.DialogFormDemoControl.chkTextImmediate_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextMultiLine, IG.Forms.DialogFormDemoControl.chkTextMultiLine_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextPassword, IG.Forms.DialogFormDemoControl.chkTextPassword_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextSetExceptions, IG.Forms.DialogFormDemoControl.chkTextSetExceptions_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextSettable, IG.Forms.DialogFormDemoControl.chkTextSettable_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextVisible, IG.Forms.DialogFormDemoControl.chkTextVisible_CheckedChanged(), IG.Forms.IndicatorLight.ColorLabel, IG.Forms.DialogFormDemoControl.components, IG.Forms.DialogControl.ControlText, IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.flowDialogControlAndResults, IG.Forms.IndicatorLight.FlowDirection, IG.Forms.DialogFormDemoControl.grpActions, IG.Forms.DialogFormDemoControl.grpDialogControl, IG.Forms.DialogFormDemoControl.grpEvents, IG.Forms.DialogFormDemoControl.grpResults, IG.Forms.DialogFormDemoControl.grpSettings, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.DialogFormDemoControl.indicatorButtonPressed, IG.Forms.DialogFormDemoControl.indicatorButtonResultChanged, IG.Forms.DialogFormDemoControl.indicatorSettingsApplied, IG.Forms.DialogFormDemoControl.indicatorTextChanged, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.DialogControl.IsTextCausesVisible, IG.Forms.DialogControl.IsTextChangedEventOnValidationOnly, IG.Forms.DialogControl.IsTextEditable, IG.Forms.DialogControl.IsTextMultiLine, IG.Forms.DialogControl.IsTextPassword, IG.Forms.DialogControl.IsTextSettable, IG.Forms.DialogControl.IsTextSetThrows, IG.Forms.DialogControl.IsTextVisible, IG.Forms.IndicatorLight.LabelFont, IG.Forms.IndicatorLight.LabelText, IG.Forms.DialogFormDemoControl.lblButtons, IG.Forms.DialogFormDemoControl.lblMainTitle, IG.Forms.DialogFormDemoControl.lblMessage, IG.Forms.DialogFormDemoControl.lblResultButton, IG.Forms.DialogFormDemoControl.lblResultText, IG.Forms.DialogFormDemoControl.lblResultTitleButton, IG.Forms.DialogFormDemoControl.lblResultTitleText, IG.Forms.DialogFormDemoControl.lblText, IG.Forms.DialogFormDemoControl.lblTextBoxHeight, IG.Forms.DialogFormDemoControl.lblTextBoxWidth, IG.Forms.DialogFormDemoControl.lblTitle, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.DialogControl.Message, IG.Forms.DialogFormDemoControl.numTextBoxHeight, IG.Forms.DialogFormDemoControl.numTextBoxHeight_Validated(), IG.Forms.DialogFormDemoControl.numTextBoxWidth, IG.Forms.DialogFormDemoControl.numTextBoxWidth_Validated(), IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.DialogFormDemoControl.textBotxtButtons, IG.Forms.DialogFormDemoControl.textBotxtButtons_TextChanged(), IG.Forms.DialogFormDemoControl.textBotxtButtons_Validated(), IG.Forms.DialogControl.TextBoxHeight, IG.Forms.DialogControl.TextBoxWidth, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, IG.Forms.DialogControl.Title, IG.Forms.DialogFormDemoControl.txtMessage, IG.Forms.DialogFormDemoControl.txtMessage_TextChanged(), IG.Forms.DialogFormDemoControl.txtMessage_Validated(), IG.Forms.DialogFormDemoControl.txtText, IG.Forms.DialogFormDemoControl.txtText_TextChanged(), IG.Forms.DialogFormDemoControl.txtText_Validated(), IG.Forms.DialogFormDemoControl.txtTitle, IG.Forms.DialogFormDemoControl.txtTitle_TextChanged(), IG.Forms.DialogFormDemoControl.txtTitle_Validated(), and IG.Forms.DialogControl.ZoomFactor.
Referenced by IG.Forms.DialogFormDemoControl.DialogFormDemoControl().
CreateNewDialogWindow() [2/3]
void IG.Forms.DialogFormDemoControl.CreateNewDialogWindow () inline
Creates a new testing dialog window.
References IG.Forms.IndicatorLight.BlinkError(), IG.Forms.IndicatorLight.BlinkOk(), IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.DialogControl.ButtonPressed, IG.Forms.DialogControl.ButtonResultChanged, IG.Forms.DialogFormDemoControl.CopyButtonDataToDialogs(), IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.dialogForm1, IG.Forms.DialogFormDemoControl.indicatorButtonPressed, IG.Forms.DialogFormDemoControl.indicatorButtonResultChanged, IG.Forms.DialogFormDemoControl.indicatorTextChanged, IG.Forms.DialogForm.MainControl, IG.Forms.DialogControl.Text, IG.Forms.DialogControl.TextChanged, and IG.Forms.DialogFormDemoControl.UpdateResults().
UpdateResults() [2/3]
void IG.Forms.DialogFormDemoControl.UpdateResults () inline protected
Updates controls that stow dialog's results.
References IG.Forms.DialogForm.ButtonResult, IG.Forms.DialogControl.ButtonResult, IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.dialogForm1, IG.Forms.DialogFormDemoControl.lblResultButton, IG.Forms.DialogFormDemoControl.lblResultText, IG.Forms.DialogForm.Text, IG.Forms.DialogControl.Text, and IG.Forms.DialogFormDemoControl.txtText.
CopyDataToDialogs() [2/3]
void IG.Forms.DialogFormDemoControl.CopyDataToDialogs () inline
Applies all data and settings forom the current control to the embedded and window test dialogs.
This does not copy the buttons data, which is performed specially by the CopyButtonDataToDialogs function.
References IG.Forms.IndicatorLight.BlinkOk(), IG.Forms.DialogFormDemoControl.chkTextCausesVisible, IG.Forms.DialogFormDemoControl.chkTextEditable, IG.Forms.DialogFormDemoControl.chkTextImmediate, IG.Forms.DialogFormDemoControl.chkTextMultiLine, IG.Forms.DialogFormDemoControl.chkTextPassword, IG.Forms.DialogFormDemoControl.chkTextSetExceptions, IG.Forms.DialogFormDemoControl.chkTextSettable, IG.Forms.DialogFormDemoControl.chkTextVisible, IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.dialogForm1, IG.Forms.DialogFormDemoControl.indicatorSettingsApplied, IG.Forms.DialogForm.IsTextCausesVisible, IG.Forms.DialogControl.IsTextCausesVisible, IG.Forms.DialogForm.IsTextChangedEventOnValidationOnly, IG.Forms.DialogControl.IsTextChangedEventOnValidationOnly, IG.Forms.DialogForm.IsTextEditable, IG.Forms.DialogControl.IsTextEditable, IG.Forms.DialogForm.IsTextMultiLine, IG.Forms.DialogControl.IsTextMultiLine, IG.Forms.DialogForm.IsTextPassword, IG.Forms.DialogControl.IsTextPassword, IG.Forms.DialogForm.IsTextSettable, IG.Forms.DialogControl.IsTextSettable, IG.Forms.DialogForm.IsTextSetThrows, IG.Forms.DialogControl.IsTextSetThrows, IG.Forms.DialogForm.IsTextVisible, IG.Forms.DialogControl.IsTextVisible, IG.Forms.DialogForm.Message, IG.Forms.DialogControl.Message, IG.Forms.DialogFormDemoControl.numTextBoxHeight, IG.Forms.DialogFormDemoControl.numTextBoxWidth, IG.Forms.DialogForm.Text, IG.Forms.DialogControl.Text, IG.Forms.DialogForm.TextBoxHeight, IG.Forms.DialogControl.TextBoxHeight, IG.Forms.DialogForm.TextBoxWidth, IG.Forms.DialogControl.TextBoxWidth, IG.Forms.DialogForm.Title, IG.Forms.DialogControl.Title, IG.Forms.DialogFormDemoControl.txtMessage, IG.Forms.DialogFormDemoControl.txtText, and IG.Forms.DialogFormDemoControl.txtTitle.
CopyButtonDataToDialogs() [2/3]
void IG.Forms.DialogFormDemoControl.CopyButtonDataToDialogs () inline
Applies all data and settings forom the current control to the embedded and window test dialogs.
This does not copy the buttons data, which is performed specially by the CopyButtonDataToDialogs function.
References IG.Forms.IndicatorLight.BlinkBusy(), IG.Forms.DialogForm.Buttons, IG.Forms.DialogControl.Buttons, IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.dialogForm1, IG.Forms.DialogFormDemoControl.indicatorSettingsApplied, and IG.Forms.DialogFormDemoControl.textBotxtButtons.
txtTitle_TextChanged() [2/3]
void IG.Forms.DialogFormDemoControl.txtTitle_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.chkImmediateText, and IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
txtTitle_Validated() [2/3]
void IG.Forms.DialogFormDemoControl.txtTitle_Validated (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
txtMessage_TextChanged() [2/3]
void IG.Forms.DialogFormDemoControl.txtMessage_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.chkImmediateText, and IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
txtMessage_Validated() [2/3]
void IG.Forms.DialogFormDemoControl.txtMessage_Validated (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
txtText_TextChanged() [2/3]
void IG.Forms.DialogFormDemoControl.txtText_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.chkImmediateText, and IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
txtText_Validated() [2/3]
void IG.Forms.DialogFormDemoControl.txtText_Validated (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
textBotxtButtons_TextChanged() [2/3]
void IG.Forms.DialogFormDemoControl.textBotxtButtons_TextChanged (object sender, EventArgs e) inline private
textBotxtButtons_Validated() [2/3]
void IG.Forms.DialogFormDemoControl.textBotxtButtons_Validated (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyButtonDataToDialogs().
chkImmediateText_CheckedChanged() [2/3]
void IG.Forms.DialogFormDemoControl.chkImmediateText_CheckedChanged (object sender, EventArgs e) inline private
btnLaunchDialog_Click() [2/3]
void IG.Forms.DialogFormDemoControl.btnLaunchDialog_Click (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), IG.Forms.DialogFormDemoControl.CreateNewDialogWindow(), and IG.Forms.DialogFormDemoControl.UpdateResults().
btnRefreshDialog_Click() [2/3]
void IG.Forms.DialogFormDemoControl.btnRefreshDialog_Click (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyButtonDataToDialogs(), IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), IG.Forms.DialogFormDemoControl.CreateNewDialogWindow(), IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.dialogForm1, and IG.Forms.DialogFormDemoControl.UpdateResults().
btnRefreshText_Click() [2/3]
void IG.Forms.DialogFormDemoControl.btnRefreshText_Click (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.UpdateResults().
chkTextVisible_CheckedChanged() [2/3]
void IG.Forms.DialogFormDemoControl.chkTextVisible_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
chkTextCausesVisible_CheckedChanged() [2/3]
void IG.Forms.DialogFormDemoControl.chkTextCausesVisible_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
chkTextEditable_CheckedChanged() [2/3]
void IG.Forms.DialogFormDemoControl.chkTextEditable_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
chkTextSettable_CheckedChanged() [2/3]
void IG.Forms.DialogFormDemoControl.chkTextSettable_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
chkTextSetExceptions_CheckedChanged() [2/3]
void IG.Forms.DialogFormDemoControl.chkTextSetExceptions_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
chkTextMultiLine_CheckedChanged() [2/3]
void IG.Forms.DialogFormDemoControl.chkTextMultiLine_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
chkTextImmediate_CheckedChanged() [2/3]
void IG.Forms.DialogFormDemoControl.chkTextImmediate_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
chkTextPassword_CheckedChanged() [2/3]
void IG.Forms.DialogFormDemoControl.chkTextPassword_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
numTextBoxWidth_Validated() [2/3]
void IG.Forms.DialogFormDemoControl.numTextBoxWidth_Validated (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
numTextBoxHeight_Validated() [2/3]
void IG.Forms.DialogFormDemoControl.numTextBoxHeight_Validated (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
Dispose() [2/3]
override void IG.Forms.DialogFormDemoControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.DialogFormDemoControl.components.
InitializeComponent() [2/3]
void IG.Forms.DialogFormDemoControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.DialogFormDemoControl.btnLaunchDialog, IG.Forms.DialogFormDemoControl.btnLaunchDialog_Click(), IG.Forms.DialogFormDemoControl.btnRefreshDialog, IG.Forms.DialogFormDemoControl.btnRefreshDialog_Click(), IG.Forms.DialogFormDemoControl.btnRefreshText, IG.Forms.DialogFormDemoControl.btnRefreshText_Click(), IG.Forms.DialogControl.Buttons, IG.Forms.DialogFormDemoControl.chkImmediateText, IG.Forms.DialogFormDemoControl.chkImmediateText_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextCausesVisible, IG.Forms.DialogFormDemoControl.chkTextCausesVisible_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextEditable, IG.Forms.DialogFormDemoControl.chkTextEditable_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextImmediate, IG.Forms.DialogFormDemoControl.chkTextImmediate_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextMultiLine, IG.Forms.DialogFormDemoControl.chkTextMultiLine_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextPassword, IG.Forms.DialogFormDemoControl.chkTextPassword_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextSetExceptions, IG.Forms.DialogFormDemoControl.chkTextSetExceptions_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextSettable, IG.Forms.DialogFormDemoControl.chkTextSettable_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextVisible, IG.Forms.DialogFormDemoControl.chkTextVisible_CheckedChanged(), IG.Forms.IndicatorLight.ColorLabel, IG.Forms.DialogFormDemoControl.components, IG.Forms.DialogControl.ControlText, IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.flowDialogControlAndResults, IG.Forms.IndicatorLight.FlowDirection, IG.Forms.DialogFormDemoControl.grpActions, IG.Forms.DialogFormDemoControl.grpDialogControl, IG.Forms.DialogFormDemoControl.grpEvents, IG.Forms.DialogFormDemoControl.grpResults, IG.Forms.DialogFormDemoControl.grpSettings, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.DialogFormDemoControl.indicatorButtonPressed, IG.Forms.DialogFormDemoControl.indicatorButtonResultChanged, IG.Forms.DialogFormDemoControl.indicatorSettingsApplied, IG.Forms.DialogFormDemoControl.indicatorTextChanged, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.DialogControl.IsTextCausesVisible, IG.Forms.DialogControl.IsTextChangedEventOnValidationOnly, IG.Forms.DialogControl.IsTextEditable, IG.Forms.DialogControl.IsTextMultiLine, IG.Forms.DialogControl.IsTextPassword, IG.Forms.DialogControl.IsTextSettable, IG.Forms.DialogControl.IsTextSetThrows, IG.Forms.DialogControl.IsTextVisible, IG.Forms.IndicatorLight.LabelFont, IG.Forms.IndicatorLight.LabelText, IG.Forms.DialogFormDemoControl.lblButtons, IG.Forms.DialogFormDemoControl.lblMainTitle, IG.Forms.DialogFormDemoControl.lblMessage, IG.Forms.DialogFormDemoControl.lblResultButton, IG.Forms.DialogFormDemoControl.lblResultText, IG.Forms.DialogFormDemoControl.lblResultTitleButton, IG.Forms.DialogFormDemoControl.lblResultTitleText, IG.Forms.DialogFormDemoControl.lblText, IG.Forms.DialogFormDemoControl.lblTextBoxHeight, IG.Forms.DialogFormDemoControl.lblTextBoxWidth, IG.Forms.DialogFormDemoControl.lblTitle, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.DialogControl.Message, IG.Forms.DialogFormDemoControl.numTextBoxHeight, IG.Forms.DialogFormDemoControl.numTextBoxHeight_Validated(), IG.Forms.DialogFormDemoControl.numTextBoxWidth, IG.Forms.DialogFormDemoControl.numTextBoxWidth_Validated(), IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.DialogFormDemoControl.textBotxtButtons, IG.Forms.DialogFormDemoControl.textBotxtButtons_TextChanged(), IG.Forms.DialogFormDemoControl.textBotxtButtons_Validated(), IG.Forms.DialogControl.TextBoxHeight, IG.Forms.DialogControl.TextBoxWidth, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, IG.Forms.DialogControl.Title, IG.Forms.DialogFormDemoControl.txtMessage, IG.Forms.DialogFormDemoControl.txtMessage_TextChanged(), IG.Forms.DialogFormDemoControl.txtMessage_Validated(), IG.Forms.DialogFormDemoControl.txtText, IG.Forms.DialogFormDemoControl.txtText_TextChanged(), IG.Forms.DialogFormDemoControl.txtText_Validated(), IG.Forms.DialogFormDemoControl.txtTitle, IG.Forms.DialogFormDemoControl.txtTitle_TextChanged(), IG.Forms.DialogFormDemoControl.txtTitle_Validated(), and IG.Forms.DialogControl.ZoomFactor.
CreateNewDialogWindow() [3/3]
void IG.Forms.DialogFormDemoControl.CreateNewDialogWindow () inline
Creates a new testing dialog window.
References IG.Forms.IndicatorLight.BlinkError(), IG.Forms.IndicatorLight.BlinkOk(), IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.DialogControl.ButtonPressed, IG.Forms.DialogControl.ButtonResultChanged, IG.Forms.DialogFormDemoControl.CopyButtonDataToDialogs(), IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.dialogForm1, IG.Forms.DialogFormDemoControl.indicatorButtonPressed, IG.Forms.DialogFormDemoControl.indicatorButtonResultChanged, IG.Forms.DialogFormDemoControl.indicatorTextChanged, IG.Forms.DialogForm.MainControl, IG.Forms.DialogControl.Text, IG.Forms.DialogControl.TextChanged, and IG.Forms.DialogFormDemoControl.UpdateResults().
UpdateResults() [3/3]
void IG.Forms.DialogFormDemoControl.UpdateResults () inline protected
Updates controls that stow dialog's results.
References IG.Forms.DialogForm.ButtonResult, IG.Forms.DialogControl.ButtonResult, IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.dialogForm1, IG.Forms.DialogFormDemoControl.lblResultButton, IG.Forms.DialogFormDemoControl.lblResultText, IG.Forms.DialogForm.Text, IG.Forms.DialogControl.Text, and IG.Forms.DialogFormDemoControl.txtText.
CopyDataToDialogs() [3/3]
void IG.Forms.DialogFormDemoControl.CopyDataToDialogs () inline
Applies all data and settings forom the current control to the embedded and window test dialogs.
This does not copy the buttons data, which is performed specially by the CopyButtonDataToDialogs function.
References IG.Forms.IndicatorLight.BlinkOk(), IG.Forms.DialogFormDemoControl.chkTextCausesVisible, IG.Forms.DialogFormDemoControl.chkTextEditable, IG.Forms.DialogFormDemoControl.chkTextImmediate, IG.Forms.DialogFormDemoControl.chkTextMultiLine, IG.Forms.DialogFormDemoControl.chkTextPassword, IG.Forms.DialogFormDemoControl.chkTextSetExceptions, IG.Forms.DialogFormDemoControl.chkTextSettable, IG.Forms.DialogFormDemoControl.chkTextVisible, IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.dialogForm1, IG.Forms.DialogFormDemoControl.indicatorSettingsApplied, IG.Forms.DialogForm.IsTextCausesVisible, IG.Forms.DialogControl.IsTextCausesVisible, IG.Forms.DialogForm.IsTextChangedEventOnValidationOnly, IG.Forms.DialogControl.IsTextChangedEventOnValidationOnly, IG.Forms.DialogForm.IsTextEditable, IG.Forms.DialogControl.IsTextEditable, IG.Forms.DialogForm.IsTextMultiLine, IG.Forms.DialogControl.IsTextMultiLine, IG.Forms.DialogForm.IsTextPassword, IG.Forms.DialogControl.IsTextPassword, IG.Forms.DialogForm.IsTextSettable, IG.Forms.DialogControl.IsTextSettable, IG.Forms.DialogForm.IsTextSetThrows, IG.Forms.DialogControl.IsTextSetThrows, IG.Forms.DialogForm.IsTextVisible, IG.Forms.DialogControl.IsTextVisible, IG.Forms.DialogForm.Message, IG.Forms.DialogControl.Message, IG.Forms.DialogFormDemoControl.numTextBoxHeight, IG.Forms.DialogFormDemoControl.numTextBoxWidth, IG.Forms.DialogForm.Text, IG.Forms.DialogControl.Text, IG.Forms.DialogForm.TextBoxHeight, IG.Forms.DialogControl.TextBoxHeight, IG.Forms.DialogForm.TextBoxWidth, IG.Forms.DialogControl.TextBoxWidth, IG.Forms.DialogForm.Title, IG.Forms.DialogControl.Title, IG.Forms.DialogFormDemoControl.txtMessage, IG.Forms.DialogFormDemoControl.txtText, and IG.Forms.DialogFormDemoControl.txtTitle.
CopyButtonDataToDialogs() [3/3]
void IG.Forms.DialogFormDemoControl.CopyButtonDataToDialogs () inline
Applies all data and settings forom the current control to the embedded and window test dialogs.
This does not copy the buttons data, which is performed specially by the CopyButtonDataToDialogs function.
References IG.Forms.IndicatorLight.BlinkBusy(), IG.Forms.DialogForm.Buttons, IG.Forms.DialogControl.Buttons, IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.dialogForm1, IG.Forms.DialogFormDemoControl.indicatorSettingsApplied, and IG.Forms.DialogFormDemoControl.textBotxtButtons.
txtTitle_TextChanged() [3/3]
void IG.Forms.DialogFormDemoControl.txtTitle_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.chkImmediateText, and IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
txtTitle_Validated() [3/3]
void IG.Forms.DialogFormDemoControl.txtTitle_Validated (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
txtMessage_TextChanged() [3/3]
void IG.Forms.DialogFormDemoControl.txtMessage_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.chkImmediateText, and IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
txtMessage_Validated() [3/3]
void IG.Forms.DialogFormDemoControl.txtMessage_Validated (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
txtText_TextChanged() [3/3]
void IG.Forms.DialogFormDemoControl.txtText_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.chkImmediateText, and IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
txtText_Validated() [3/3]
void IG.Forms.DialogFormDemoControl.txtText_Validated (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
textBotxtButtons_TextChanged() [3/3]
void IG.Forms.DialogFormDemoControl.textBotxtButtons_TextChanged (object sender, EventArgs e) inline private
textBotxtButtons_Validated() [3/3]
void IG.Forms.DialogFormDemoControl.textBotxtButtons_Validated (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyButtonDataToDialogs().
chkImmediateText_CheckedChanged() [3/3]
void IG.Forms.DialogFormDemoControl.chkImmediateText_CheckedChanged (object sender, EventArgs e) inline private
btnLaunchDialog_Click() [3/3]
void IG.Forms.DialogFormDemoControl.btnLaunchDialog_Click (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), IG.Forms.DialogFormDemoControl.CreateNewDialogWindow(), and IG.Forms.DialogFormDemoControl.UpdateResults().
btnRefreshDialog_Click() [3/3]
void IG.Forms.DialogFormDemoControl.btnRefreshDialog_Click (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyButtonDataToDialogs(), IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), IG.Forms.DialogFormDemoControl.CreateNewDialogWindow(), IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.dialogForm1, and IG.Forms.DialogFormDemoControl.UpdateResults().
btnRefreshText_Click() [3/3]
void IG.Forms.DialogFormDemoControl.btnRefreshText_Click (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.UpdateResults().
chkTextVisible_CheckedChanged() [3/3]
void IG.Forms.DialogFormDemoControl.chkTextVisible_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
chkTextCausesVisible_CheckedChanged() [3/3]
void IG.Forms.DialogFormDemoControl.chkTextCausesVisible_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
chkTextEditable_CheckedChanged() [3/3]
void IG.Forms.DialogFormDemoControl.chkTextEditable_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
chkTextSettable_CheckedChanged() [3/3]
void IG.Forms.DialogFormDemoControl.chkTextSettable_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
chkTextSetExceptions_CheckedChanged() [3/3]
void IG.Forms.DialogFormDemoControl.chkTextSetExceptions_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
chkTextMultiLine_CheckedChanged() [3/3]
void IG.Forms.DialogFormDemoControl.chkTextMultiLine_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
chkTextImmediate_CheckedChanged() [3/3]
void IG.Forms.DialogFormDemoControl.chkTextImmediate_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
chkTextPassword_CheckedChanged() [3/3]
void IG.Forms.DialogFormDemoControl.chkTextPassword_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
numTextBoxWidth_Validated() [3/3]
void IG.Forms.DialogFormDemoControl.numTextBoxWidth_Validated (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
numTextBoxHeight_Validated() [3/3]
void IG.Forms.DialogFormDemoControl.numTextBoxHeight_Validated (object sender, EventArgs e) inline private
References IG.Forms.DialogFormDemoControl.CopyDataToDialogs().
Dispose() [3/3]
override void IG.Forms.DialogFormDemoControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.DialogFormDemoControl.components.
InitializeComponent() [3/3]
void IG.Forms.DialogFormDemoControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.DialogFormDemoControl.btnLaunchDialog, IG.Forms.DialogFormDemoControl.btnLaunchDialog_Click(), IG.Forms.DialogFormDemoControl.btnRefreshDialog, IG.Forms.DialogFormDemoControl.btnRefreshDialog_Click(), IG.Forms.DialogFormDemoControl.btnRefreshText, IG.Forms.DialogFormDemoControl.btnRefreshText_Click(), IG.Forms.DialogControl.Buttons, IG.Forms.DialogFormDemoControl.chkImmediateText, IG.Forms.DialogFormDemoControl.chkImmediateText_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextCausesVisible, IG.Forms.DialogFormDemoControl.chkTextCausesVisible_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextEditable, IG.Forms.DialogFormDemoControl.chkTextEditable_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextImmediate, IG.Forms.DialogFormDemoControl.chkTextImmediate_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextMultiLine, IG.Forms.DialogFormDemoControl.chkTextMultiLine_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextPassword, IG.Forms.DialogFormDemoControl.chkTextPassword_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextSetExceptions, IG.Forms.DialogFormDemoControl.chkTextSetExceptions_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextSettable, IG.Forms.DialogFormDemoControl.chkTextSettable_CheckedChanged(), IG.Forms.DialogFormDemoControl.chkTextVisible, IG.Forms.DialogFormDemoControl.chkTextVisible_CheckedChanged(), IG.Forms.IndicatorLight.ColorLabel, IG.Forms.DialogFormDemoControl.components, IG.Forms.DialogControl.ControlText, IG.Forms.DialogFormDemoControl.dialogControl1, IG.Forms.DialogFormDemoControl.flowDialogControlAndResults, IG.Forms.IndicatorLight.FlowDirection, IG.Forms.DialogFormDemoControl.grpActions, IG.Forms.DialogFormDemoControl.grpDialogControl, IG.Forms.DialogFormDemoControl.grpEvents, IG.Forms.DialogFormDemoControl.grpResults, IG.Forms.DialogFormDemoControl.grpSettings, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.DialogFormDemoControl.indicatorButtonPressed, IG.Forms.DialogFormDemoControl.indicatorButtonResultChanged, IG.Forms.DialogFormDemoControl.indicatorSettingsApplied, IG.Forms.DialogFormDemoControl.indicatorTextChanged, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.DialogControl.IsTextCausesVisible, IG.Forms.DialogControl.IsTextChangedEventOnValidationOnly, IG.Forms.DialogControl.IsTextEditable, IG.Forms.DialogControl.IsTextMultiLine, IG.Forms.DialogControl.IsTextPassword, IG.Forms.DialogControl.IsTextSettable, IG.Forms.DialogControl.IsTextSetThrows, IG.Forms.DialogControl.IsTextVisible, IG.Forms.IndicatorLight.LabelFont, IG.Forms.IndicatorLight.LabelText, IG.Forms.DialogFormDemoControl.lblButtons, IG.Forms.DialogFormDemoControl.lblMainTitle, IG.Forms.DialogFormDemoControl.lblMessage, IG.Forms.DialogFormDemoControl.lblResultButton, IG.Forms.DialogFormDemoControl.lblResultText, IG.Forms.DialogFormDemoControl.lblResultTitleButton, IG.Forms.DialogFormDemoControl.lblResultTitleText, IG.Forms.DialogFormDemoControl.lblText, IG.Forms.DialogFormDemoControl.lblTextBoxHeight, IG.Forms.DialogFormDemoControl.lblTextBoxWidth, IG.Forms.DialogFormDemoControl.lblTitle, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.DialogControl.Message, IG.Forms.DialogFormDemoControl.numTextBoxHeight, IG.Forms.DialogFormDemoControl.numTextBoxHeight_Validated(), IG.Forms.DialogFormDemoControl.numTextBoxWidth, IG.Forms.DialogFormDemoControl.numTextBoxWidth_Validated(), IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.DialogFormDemoControl.textBotxtButtons, IG.Forms.DialogFormDemoControl.textBotxtButtons_TextChanged(), IG.Forms.DialogFormDemoControl.textBotxtButtons_Validated(), IG.Forms.DialogControl.TextBoxHeight, IG.Forms.DialogControl.TextBoxWidth, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, IG.Forms.DialogControl.Title, IG.Forms.DialogFormDemoControl.txtMessage, IG.Forms.DialogFormDemoControl.txtMessage_TextChanged(), IG.Forms.DialogFormDemoControl.txtMessage_Validated(), IG.Forms.DialogFormDemoControl.txtText, IG.Forms.DialogFormDemoControl.txtText_TextChanged(), IG.Forms.DialogFormDemoControl.txtText_Validated(), IG.Forms.DialogFormDemoControl.txtTitle, IG.Forms.DialogFormDemoControl.txtTitle_TextChanged(), IG.Forms.DialogFormDemoControl.txtTitle_Validated(), and IG.Forms.DialogControl.ZoomFactor.
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.DialogFormDemoControl.components = null private
Required designer variable.
Referenced by IG.Forms.DialogFormDemoControl.Dispose(), and IG.Forms.DialogFormDemoControl.InitializeComponent().
dialogControl1
DialogControl IG.Forms.DialogFormDemoControl.dialogControl1 private
Referenced by IG.Forms.DialogFormDemoControl.btnRefreshDialog_Click(), IG.Forms.DialogFormDemoControl.CopyButtonDataToDialogs(), IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), IG.Forms.DialogFormDemoControl.CreateNewDialogWindow(), IG.Forms.DialogFormDemoControl.DialogFormDemoControl(), IG.Forms.DialogFormDemoControl.InitializeComponent(), and IG.Forms.DialogFormDemoControl.UpdateResults().
dialogForm1
DialogForm IG.Forms.DialogFormDemoControl.dialogForm1 private
Referenced by IG.Forms.DialogFormDemoControl.btnRefreshDialog_Click(), IG.Forms.DialogFormDemoControl.CopyButtonDataToDialogs(), IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), IG.Forms.DialogFormDemoControl.CreateNewDialogWindow(), and IG.Forms.DialogFormDemoControl.UpdateResults().
lblMainTitle
System Windows Forms Label IG.Forms.DialogFormDemoControl.lblMainTitle private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
lblTitle
System Windows Forms Label IG.Forms.DialogFormDemoControl.lblTitle private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
txtTitle
System Windows Forms TextBox IG.Forms.DialogFormDemoControl.txtTitle private
Referenced by IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), and IG.Forms.DialogFormDemoControl.InitializeComponent().
txtMessage
System Windows Forms TextBox IG.Forms.DialogFormDemoControl.txtMessage private
Referenced by IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), and IG.Forms.DialogFormDemoControl.InitializeComponent().
lblMessage
System Windows Forms Label IG.Forms.DialogFormDemoControl.lblMessage private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
lblText
System Windows Forms Label IG.Forms.DialogFormDemoControl.lblText private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
txtText
System Windows Forms TextBox IG.Forms.DialogFormDemoControl.txtText private
Referenced by IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), IG.Forms.DialogFormDemoControl.InitializeComponent(), and IG.Forms.DialogFormDemoControl.UpdateResults().
lblButtons
System Windows Forms Label IG.Forms.DialogFormDemoControl.lblButtons private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
textBotxtButtons
System Windows Forms TextBox IG.Forms.DialogFormDemoControl.textBotxtButtons private
Referenced by IG.Forms.DialogFormDemoControl.CopyButtonDataToDialogs(), and IG.Forms.DialogFormDemoControl.InitializeComponent().
grpResults
System Windows Forms GroupBox IG.Forms.DialogFormDemoControl.grpResults private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
lblResultText
System Windows Forms Label IG.Forms.DialogFormDemoControl.lblResultText private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent(), and IG.Forms.DialogFormDemoControl.UpdateResults().
lblResultButton
System Windows Forms Label IG.Forms.DialogFormDemoControl.lblResultButton private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent(), and IG.Forms.DialogFormDemoControl.UpdateResults().
lblResultTitleText
System Windows Forms Label IG.Forms.DialogFormDemoControl.lblResultTitleText private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
lblResultTitleButton
System Windows Forms Label IG.Forms.DialogFormDemoControl.lblResultTitleButton private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
grpDialogControl
System Windows Forms GroupBox IG.Forms.DialogFormDemoControl.grpDialogControl private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
flowDialogControlAndResults
System Windows Forms FlowLayoutPanel IG.Forms.DialogFormDemoControl.flowDialogControlAndResults private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
btnLaunchDialog
System Windows Forms Button IG.Forms.DialogFormDemoControl.btnLaunchDialog private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
btnRefreshDialog
System Windows Forms Button IG.Forms.DialogFormDemoControl.btnRefreshDialog private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
grpSettings
System Windows Forms GroupBox IG.Forms.DialogFormDemoControl.grpSettings private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
chkTextEditable
System Windows Forms CheckBox IG.Forms.DialogFormDemoControl.chkTextEditable private
Referenced by IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), and IG.Forms.DialogFormDemoControl.InitializeComponent().
chkTextMultiLine
System Windows Forms CheckBox IG.Forms.DialogFormDemoControl.chkTextMultiLine private
Referenced by IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), and IG.Forms.DialogFormDemoControl.InitializeComponent().
chkTextSettable
System Windows Forms CheckBox IG.Forms.DialogFormDemoControl.chkTextSettable private
Referenced by IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), and IG.Forms.DialogFormDemoControl.InitializeComponent().
chkImmediateText
System Windows Forms CheckBox IG.Forms.DialogFormDemoControl.chkImmediateText private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.DialogFormDemoControl.txtMessage_TextChanged(), IG.Forms.DialogFormDemoControl.txtText_TextChanged(), and IG.Forms.DialogFormDemoControl.txtTitle_TextChanged().
numTextBoxHeight
System Windows Forms NumericUpDown IG.Forms.DialogFormDemoControl.numTextBoxHeight private
Referenced by IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), and IG.Forms.DialogFormDemoControl.InitializeComponent().
numTextBoxWidth
System Windows Forms NumericUpDown IG.Forms.DialogFormDemoControl.numTextBoxWidth private
Referenced by IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), and IG.Forms.DialogFormDemoControl.InitializeComponent().
lblTextBoxWidth
System Windows Forms Label IG.Forms.DialogFormDemoControl.lblTextBoxWidth private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
grpEvents
System Windows Forms GroupBox IG.Forms.DialogFormDemoControl.grpEvents private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
lblTextBoxHeight
System Windows Forms Label IG.Forms.DialogFormDemoControl.lblTextBoxHeight private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
indicatorButtonResultChanged
IndicatorLight IG.Forms.DialogFormDemoControl.indicatorButtonResultChanged private
Referenced by IG.Forms.DialogFormDemoControl.CreateNewDialogWindow(), IG.Forms.DialogFormDemoControl.DialogFormDemoControl(), and IG.Forms.DialogFormDemoControl.InitializeComponent().
indicatorTextChanged
IndicatorLight IG.Forms.DialogFormDemoControl.indicatorTextChanged private
Referenced by IG.Forms.DialogFormDemoControl.CreateNewDialogWindow(), IG.Forms.DialogFormDemoControl.DialogFormDemoControl(), and IG.Forms.DialogFormDemoControl.InitializeComponent().
indicatorButtonPressed
IndicatorLight IG.Forms.DialogFormDemoControl.indicatorButtonPressed private
Referenced by IG.Forms.DialogFormDemoControl.CreateNewDialogWindow(), IG.Forms.DialogFormDemoControl.DialogFormDemoControl(), and IG.Forms.DialogFormDemoControl.InitializeComponent().
btnRefreshText
System Windows Forms Button IG.Forms.DialogFormDemoControl.btnRefreshText private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
chkTextSetExceptions
System Windows Forms CheckBox IG.Forms.DialogFormDemoControl.chkTextSetExceptions private
Referenced by IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), and IG.Forms.DialogFormDemoControl.InitializeComponent().
indicatorSettingsApplied
IndicatorLight IG.Forms.DialogFormDemoControl.indicatorSettingsApplied private
Referenced by IG.Forms.DialogFormDemoControl.CopyButtonDataToDialogs(), IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), and IG.Forms.DialogFormDemoControl.InitializeComponent().
chkTextVisible
System Windows Forms CheckBox IG.Forms.DialogFormDemoControl.chkTextVisible private
Referenced by IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), and IG.Forms.DialogFormDemoControl.InitializeComponent().
chkTextImmediate
System Windows Forms CheckBox IG.Forms.DialogFormDemoControl.chkTextImmediate private
Referenced by IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), and IG.Forms.DialogFormDemoControl.InitializeComponent().
grpActions
System Windows Forms GroupBox IG.Forms.DialogFormDemoControl.grpActions private
Referenced by IG.Forms.DialogFormDemoControl.InitializeComponent().
chkTextCausesVisible
System Windows Forms CheckBox IG.Forms.DialogFormDemoControl.chkTextCausesVisible private
Referenced by IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), and IG.Forms.DialogFormDemoControl.InitializeComponent().
chkTextPassword
System Windows Forms CheckBox IG.Forms.DialogFormDemoControl.chkTextPassword private
Referenced by IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), and IG.Forms.DialogFormDemoControl.InitializeComponent().
Property Documentation
IsDialogFormActive
bool IG.Forms.DialogFormDemoControl.IsDialogFormActive get
Returns true if the dialog form is active, i. e. if it is located, visible, and not yet disposed.
This is used e.g. in cases where functions of the dialog form can be taken over by the embedded dialog control when the former is not active (such as events, for example).
Referenced by IG.Forms.DialogFormDemoControl.DialogFormDemoControl().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/BasicControls/DialogFormDemoControl.cs
iglib/igforms/Utilities/BasicControls/DialogFormDemoControl.Designer.cs