Doc: IGLib EXTENDED: NUnit.Framework.Internal.TypeWrapper Class Reference
NUnit.Framework.Internal.TypeWrapper Class Reference
The TypeWrapper class wraps a Type so it may be used in a platform-independent manner.
Public Member Functions
TypeWrapper (Type type)
Construct a TypeWrapper for a specified Type.
bool IsType (Type type)
Returns true if the Type wrapped is T
string GetDisplayName ()
Get the display name for this type
string GetDisplayName (object[] args)
Get the display name for an object of this type, constructed with the specified args.
ITypeInfo MakeGenericType (Type[] typeArgs)
Returns a new ITypeInfo representing an instance of this generic Type using the supplied Type arguments
Type GetGenericTypeDefinition ()
Returns a Type representing a generic type definition from which this Type can be constructed.
T[] GetCustomAttributes< T > (bool inherit)
Returns an array of custom attributes of the specified type applied to this type
bool IsDefined< T > (bool inherit)
Returns a value indicating whether the type has an attribute of the specified type.
bool HasMethodWithAttribute (Type attributeType)
Returns a flag indicating whether this type has a method with an attribute of the specified type.
IMethodInfo[] GetMethods (BindingFlags flags)
Returns an array of IMethodInfos for methods of this Type that match the specified flags.
bool HasConstructor (Type[] argTypes)
Returns a value indicating whether this Type has a public constructor taking the specified argument Types.
object Construct (object[] args)
Construct an object of this Type, using the specified arguments.
override string ToString ()
Override ToString() so that error messages in NUnit's own tests make sense
Properties
Type Type [get, private set]
Gets the underlying Type on which this TypeWrapper is based.
ITypeInfo? BaseType [get]
Gets the base type of this type as an ITypeInfo
string Name [get]
Gets the Name of the Type
string FullName [get]
Gets the FullName of the Type
Assembly Assembly [get]
Gets the assembly in which the type is declared
string Namespace [get]
Gets the namespace of the Type
bool IsAbstract [get]
Gets a value indicating whether the type is abstract.
bool IsGenericType [get]
Gets a value indicating whether the Type is a generic Type
bool ContainsGenericParameters [get]
Gets a value indicating whether the Type has generic parameters that have not been replaced by specific Types.
bool IsGenericTypeDefinition [get]
Gets a value indicating whether the Type is a generic Type definition
bool IsSealed [get]
Gets a value indicating whether the type is sealed.
bool IsStaticClass [get]
Gets a value indicating whether this type represents a static class.
Properties inherited from NUnit.Framework.Interfaces.ITypeInfo
Type Type [get]
Gets the underlying Type on which this ITypeInfo is based
ITypeInfo BaseType [get]
Gets the base type of this type as an ITypeInfo
string Name [get]
Gets the Name of the Type
string FullName [get]
Gets the FullName of the Type
Assembly Assembly [get]
Gets the assembly in which the type is declared
string Namespace [get]
Gets the Namespace of the Type
bool IsAbstract [get]
Gets a value indicating whether the type is abstract.
bool IsGenericType [get]
Gets a value indicating whether the Type is a generic Type
bool ContainsGenericParameters [get]
Gets a value indicating whether the Type has generic parameters that have not been replaced by specific Types.
bool IsGenericTypeDefinition [get]
Gets a value indicating whether the Type is a generic Type definition
bool IsSealed [get]
Gets a value indicating whether the type is sealed.
bool IsStaticClass [get]
Gets a value indicating whether this type is a static class.
Detailed Description
The TypeWrapper class wraps a Type so it may be used in a platform-independent manner.
Constructor & Destructor Documentation
TypeWrapper()
NUnit.Framework.Internal.TypeWrapper.TypeWrapper (Type type) inline
Construct a TypeWrapper for a specified Type.
References NUnit.Framework.Internal.TypeWrapper.Type.
Referenced by NUnit.Framework.Internal.TypeWrapper.MakeGenericType().
Member Function Documentation
IsType()
bool NUnit.Framework.Internal.TypeWrapper.IsType (Type type) inline
Returns true if the Type wrapped is T
Implements NUnit.Framework.Interfaces.ITypeInfo.
References NUnit.Framework.Internal.TypeWrapper.Type.
GetDisplayName() [1/2]
string NUnit.Framework.Internal.TypeWrapper.GetDisplayName () inline
Get the display name for this type
Implements NUnit.Framework.Interfaces.ITypeInfo.
References NUnit.Framework.Internal.TypeHelper.GetDisplayName(), and NUnit.Framework.Internal.TypeWrapper.Type.
GetDisplayName() [2/2]
string NUnit.Framework.Internal.TypeWrapper.GetDisplayName (object[] args) inline
Get the display name for an object of this type, constructed with the specified args.
Implements NUnit.Framework.Interfaces.ITypeInfo.
References NUnit.Framework.Internal.TypeHelper.GetDisplayName(), and NUnit.Framework.Internal.TypeWrapper.Type.
MakeGenericType()
ITypeInfo NUnit.Framework.Internal.TypeWrapper.MakeGenericType (Type[] typeArgs) inline
Returns a new ITypeInfo representing an instance of this generic Type using the supplied Type arguments
Implements NUnit.Framework.Interfaces.ITypeInfo.
References NUnit.Framework.Internal.TypeWrapper.Type, and NUnit.Framework.Internal.TypeWrapper.TypeWrapper().
GetGenericTypeDefinition()
Type NUnit.Framework.Internal.TypeWrapper.GetGenericTypeDefinition () inline
Returns a Type representing a generic type definition from which this Type can be constructed.
Implements NUnit.Framework.Interfaces.ITypeInfo.
References NUnit.Framework.Internal.TypeWrapper.Type.
GetCustomAttributes< T >()
T [] NUnit.Framework.Internal.TypeWrapper.GetCustomAttributes< T > (bool inherit) inline
Returns an array of custom attributes of the specified type applied to this type
Implements NUnit.Framework.Interfaces.IReflectionInfo.
Type Constraints
T : class
References NUnit.Framework.Internal.TypeWrapper.Type.
IsDefined< T >()
bool NUnit.Framework.Internal.TypeWrapper.IsDefined< T > (bool inherit) inline
Returns a value indicating whether the type has an attribute of the specified type.
Template Parameters
T
Parameters
inherit
Returns
Implements NUnit.Framework.Interfaces.IReflectionInfo.
References NUnit.Framework.Internal.TypeWrapper.Type.
HasMethodWithAttribute()
bool NUnit.Framework.Internal.TypeWrapper.HasMethodWithAttribute (Type attributeType) inline
Returns a flag indicating whether this type has a method with an attribute of the specified type.
Parameters
attributeType
Returns
Implements NUnit.Framework.Interfaces.ITypeInfo.
References NUnit.Framework.Internal.Reflect.HasMethodWithAttribute(), and NUnit.Framework.Internal.TypeWrapper.Type.
GetMethods()
IMethodInfo [] NUnit.Framework.Internal.TypeWrapper.GetMethods (BindingFlags flags) inline
Returns an array of IMethodInfos for methods of this Type that match the specified flags.
Implements NUnit.Framework.Interfaces.ITypeInfo.
References NUnit.Framework.Internal.TypeWrapper.Type.
HasConstructor()
bool NUnit.Framework.Internal.TypeWrapper.HasConstructor (Type[] argTypes) inline
Returns a value indicating whether this Type has a public constructor taking the specified argument Types.
Implements NUnit.Framework.Interfaces.ITypeInfo.
References NUnit.Framework.Internal.TypeWrapper.Type.
Construct()
object NUnit.Framework.Internal.TypeWrapper.Construct (object[] args) inline
Construct an object of this Type, using the specified arguments.
Implements NUnit.Framework.Interfaces.ITypeInfo.
References NUnit.Framework.Internal.Reflect.Construct(), and NUnit.Framework.Internal.TypeWrapper.Type.
ToString()
override string NUnit.Framework.Internal.TypeWrapper.ToString () inline
Override ToString() so that error messages in NUnit's own tests make sense
References NUnit.Framework.Internal.TypeWrapper.Type.
Property Documentation
Type
Type NUnit.Framework.Internal.TypeWrapper.Type get private set
Gets the underlying Type on which this TypeWrapper is based.
Referenced by NUnit.Framework.Internal.TypeWrapper.Construct(), NUnit.Framework.Internal.TypeWrapper.GetCustomAttributes< T >(), NUnit.Framework.Internal.TypeWrapper.GetDisplayName(), NUnit.Framework.Internal.TypeWrapper.GetGenericTypeDefinition(), NUnit.Framework.Internal.TypeWrapper.GetMethods(), NUnit.Framework.Internal.TypeWrapper.HasConstructor(), NUnit.Framework.Internal.TypeWrapper.HasMethodWithAttribute(), NUnit.Framework.Internal.TypeWrapper.IsDefined< T >(), NUnit.Framework.Internal.TypeWrapper.IsType(), NUnit.Framework.Internal.TypeWrapper.MakeGenericType(), NUnit.Framework.Internal.TypeWrapper.ToString(), and NUnit.Framework.Internal.TypeWrapper.TypeWrapper().
BaseType
ITypeInfo? NUnit.Framework.Internal.TypeWrapper.BaseType get
Gets the base type of this type as an ITypeInfo
Name
string NUnit.Framework.Internal.TypeWrapper.Name get
Gets the Name of the Type
FullName
string NUnit.Framework.Internal.TypeWrapper.FullName get
Gets the FullName of the Type
Assembly
Assembly NUnit.Framework.Internal.TypeWrapper.Assembly get
Gets the assembly in which the type is declared
Namespace
string NUnit.Framework.Internal.TypeWrapper.Namespace get
Gets the namespace of the Type
IsAbstract
bool NUnit.Framework.Internal.TypeWrapper.IsAbstract get
Gets a value indicating whether the type is abstract.
IsGenericType
bool NUnit.Framework.Internal.TypeWrapper.IsGenericType get
Gets a value indicating whether the Type is a generic Type
ContainsGenericParameters
bool NUnit.Framework.Internal.TypeWrapper.ContainsGenericParameters get
Gets a value indicating whether the Type has generic parameters that have not been replaced by specific Types.
IsGenericTypeDefinition
bool NUnit.Framework.Internal.TypeWrapper.IsGenericTypeDefinition get
Gets a value indicating whether the Type is a generic Type definition
IsSealed
bool NUnit.Framework.Internal.TypeWrapper.IsSealed get
Gets a value indicating whether the type is sealed.
IsStaticClass
bool NUnit.Framework.Internal.TypeWrapper.IsStaticClass get
Gets a value indicating whether this type represents a static class.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/TypeWrapper.cs