Doc: IGLib EXTENDED: NUnit.Framework.Assertions.NotEqualFixture Class Reference
NUnit.Framework.Assertions.NotEqualFixture Class Reference
Public Member Functions
void NotEqual ()
void NotEqualFails ()
void NullNotEqualToNonNull ()
void NullEqualsNull ()
void ArraysNotEqual ()
void ArraysNotEqualFails ()
void UInt ()
void NotEqualSameTypes ()
Member Function Documentation
NotEqual()
void NUnit.Framework.Assertions.NotEqualFixture.NotEqual () inline
References NUnit.Framework.Assert.AreNotEqual().
NotEqualFails()
void NUnit.Framework.Assertions.NotEqualFixture.NotEqualFails () inline
References NUnit.Framework.Assert.AreNotEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Env.NewLine, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
NullNotEqualToNonNull()
void NUnit.Framework.Assertions.NotEqualFixture.NullNotEqualToNonNull () inline
References NUnit.Framework.Assert.AreNotEqual().
NullEqualsNull()
void NUnit.Framework.Assertions.NotEqualFixture.NullEqualsNull () inline
References NUnit.Framework.Assert.AreNotEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Env.NewLine, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
ArraysNotEqual()
void NUnit.Framework.Assertions.NotEqualFixture.ArraysNotEqual () inline
References NUnit.Framework.Assert.AreNotEqual().
ArraysNotEqualFails()
void NUnit.Framework.Assertions.NotEqualFixture.ArraysNotEqualFails () inline
References NUnit.Framework.Assert.AreNotEqual(), NUnit.Env.NewLine, and NUnit.Framework.Assert.Throws().
UInt()
void NUnit.Framework.Assertions.NotEqualFixture.UInt () inline
References NUnit.Framework.Assert.AreNotEqual().
NotEqualSameTypes()
void NUnit.Framework.Assertions.NotEqualFixture.NotEqualSameTypes () inline
References NUnit.Framework.Assert.AreNotEqual().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/NotEqualFixture.cs