Doc: IGLib EXTENDED: IG.Test.Program_Marko_Ext Class Reference
IG.Test.Program_Marko_Ext Class Reference
Class containing the main method.
Static Public Member Functions
static void Main (string[] args)
Entry point of the application.
static void AddScriptAssembliesExt ()
Detailed Description
Class containing the main method.
Follows standard scheme for IGLib-based simple application.
$A Igor Oct12 Jan13;
Member Function Documentation
Main()
static void IG.Test.Program_Marko_Ext.Main (string[] args) inline static
Entry point of the application.
Parameters
AppArguments Application arguments.
References IG.Test.Program_Marko_Ext.AddScriptAssembliesExt(), and IG.Lib.ILoadableScript.Run().
AddScriptAssembliesExt()
static void IG.Test.Program_Marko_Ext.AddScriptAssembliesExt () inline static
References IG.Lib.ScriptLoaderBase.AddDefaultAssemblies().
Referenced by IG.Test.Program_Marko_Ext.Main().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/extended/Guest_Marko_Petek_AppExt/Program_Marko_Ext.cs