Doc: IGLib EXTENDED: AForge.Imaging.Filters.YCbCrFiltering Class Reference
AForge.Imaging.Filters.YCbCrFiltering Class Reference
Color filtering in YCbCr color space.
Public Member Functions
YCbCrFiltering ()
Initializes a new instance of the YCbCrFiltering class.
YCbCrFiltering (Range yRange, Range cbRange, Range crRange)
Initializes a new instance of the YCbCrFiltering class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image, Rectangle rect)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Range Y [get, set]
Range of Y component, [0, 1].
Range Cb [get, set]
Range of Cb component, [-0.5, 0.5].
Range Cr [get, set]
Range of Cr component, [-0.5, 0.5].
YCbCr FillColor [get, set]
Fill color used to fill filtered pixels.
bool FillOutsideRange [get, set]
Determines, if pixels should be filled inside or outside specified color range.
bool UpdateY [get, set]
Determines, if Y value of filtered pixels should be updated.
bool UpdateCb [get, set]
Determines, if Cb value of filtered pixels should be updated.
bool UpdateCr [get, set]
Determines, if Cr value of filtered pixels should be updated.
Properties inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
Range yRange = new Range(0.0f, 1.0f)
Range cbRange = new Range(-0.5f, 0.5f)
Range crRange = new Range(-0.5f, 0.5f)
float fillY = 0.0f
float fillCb = 0.0f
float fillCr = 0.0f
bool fillOutsideRange = true
bool updateY = true
bool updateCb = true
bool updateCr = true
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Color filtering in YCbCr color space.
The filter operates in YCbCr color space and filters pixels, which color is inside/outside of the specified YCbCr range - it keeps pixels with colors inside/outside of the specified range and fills the rest with specified color.
The filter accepts 24 and 32 bpp color images for processing.
Sample usage:
// create filter
YCbCrFiltering filter = new YCbCrFiltering();
// set color ranges to keep
filter.Cb = new Range(-0.2f, 0.0f);
filter.Cr = new Range(0.26f, 0.5f);
// apply the filter
filter.ApplyInPlace(image);
Initial image:
Result image:
See also
ColorFiltering, HSLFiltering
Constructor & Destructor Documentation
YCbCrFiltering() [1/2]
AForge.Imaging.Filters.YCbCrFiltering.YCbCrFiltering () inline
Initializes a new instance of the YCbCrFiltering class.
References AForge.Imaging.Filters.YCbCrFiltering.formatTranslations.
YCbCrFiltering() [2/2]
AForge.Imaging.Filters.YCbCrFiltering.YCbCrFiltering (Range yRange, Range cbRange, Range crRange) inline
Initializes a new instance of the YCbCrFiltering class.
Parameters
yRange Range of Y component.
cbRange Range of Cb component.
crRange Range of Cr component.
References AForge.Imaging.Filters.YCbCrFiltering.cbRange, AForge.Imaging.Filters.YCbCrFiltering.crRange, and AForge.Imaging.Filters.YCbCrFiltering.yRange.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.YCbCrFiltering.ProcessFilter (UnmanagedImage image, Rectangle rect) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
rect Image rectangle for processing by the filter.
Implements AForge.Imaging.Filters.BaseInPlacePartialFilter.
References AForge.Imaging.RGB.B, AForge.Imaging.RGB.Blue, AForge.Imaging.YCbCr.Cb, AForge.Imaging.Filters.YCbCrFiltering.cbRange, AForge.Imaging.YCbCr.Cr, AForge.Imaging.Filters.YCbCrFiltering.crRange, AForge.Imaging.Filters.YCbCrFiltering.fillCb, AForge.Imaging.Filters.YCbCrFiltering.fillCr, AForge.Imaging.Filters.YCbCrFiltering.fillOutsideRange, AForge.Imaging.Filters.YCbCrFiltering.fillY, AForge.Imaging.YCbCr.FromRGB(), AForge.Imaging.RGB.G, AForge.Imaging.RGB.Green, AForge.Imaging.UnmanagedImage.ImageData, AForge.Range.Max, AForge.Range.Min, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, AForge.Imaging.RGB.Red, AForge.Imaging.UnmanagedImage.Stride, AForge.Imaging.YCbCr.ToRGB(), AForge.Imaging.Filters.YCbCrFiltering.updateCb, AForge.Imaging.Filters.YCbCrFiltering.updateCr, AForge.Imaging.Filters.YCbCrFiltering.updateY, AForge.Imaging.YCbCr.Y, and AForge.Imaging.Filters.YCbCrFiltering.yRange.
Member Data Documentation
yRange
Range AForge.Imaging.Filters.YCbCrFiltering.yRange = new Range(0.0f, 1.0f) private
Referenced by AForge.Imaging.Filters.YCbCrFiltering.ProcessFilter(), and AForge.Imaging.Filters.YCbCrFiltering.YCbCrFiltering().
cbRange
Range AForge.Imaging.Filters.YCbCrFiltering.cbRange = new Range(-0.5f, 0.5f) private
Referenced by AForge.Imaging.Filters.YCbCrFiltering.ProcessFilter(), and AForge.Imaging.Filters.YCbCrFiltering.YCbCrFiltering().
crRange
Range AForge.Imaging.Filters.YCbCrFiltering.crRange = new Range(-0.5f, 0.5f) private
Referenced by AForge.Imaging.Filters.YCbCrFiltering.ProcessFilter(), and AForge.Imaging.Filters.YCbCrFiltering.YCbCrFiltering().
fillY
float AForge.Imaging.Filters.YCbCrFiltering.fillY = 0.0f private
Referenced by AForge.Imaging.Filters.YCbCrFiltering.ProcessFilter().
fillCb
float AForge.Imaging.Filters.YCbCrFiltering.fillCb = 0.0f private
Referenced by AForge.Imaging.Filters.YCbCrFiltering.ProcessFilter().
fillCr
float AForge.Imaging.Filters.YCbCrFiltering.fillCr = 0.0f private
Referenced by AForge.Imaging.Filters.YCbCrFiltering.ProcessFilter().
fillOutsideRange
bool AForge.Imaging.Filters.YCbCrFiltering.fillOutsideRange = true private
Referenced by AForge.Imaging.Filters.YCbCrFiltering.ProcessFilter().
updateY
bool AForge.Imaging.Filters.YCbCrFiltering.updateY = true private
Referenced by AForge.Imaging.Filters.YCbCrFiltering.ProcessFilter().
updateCb
bool AForge.Imaging.Filters.YCbCrFiltering.updateCb = true private
Referenced by AForge.Imaging.Filters.YCbCrFiltering.ProcessFilter().
updateCr
bool AForge.Imaging.Filters.YCbCrFiltering.updateCr = true private
Referenced by AForge.Imaging.Filters.YCbCrFiltering.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.YCbCrFiltering.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.YCbCrFiltering.YCbCrFiltering().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.YCbCrFiltering.FormatTranslations get
Format translations dictionary.
Y
Range AForge.Imaging.Filters.YCbCrFiltering.Y get set
Range of Y component, [0, 1].
Cb
Range AForge.Imaging.Filters.YCbCrFiltering.Cb get set
Range of Cb component, [-0.5, 0.5].
Cr
Range AForge.Imaging.Filters.YCbCrFiltering.Cr get set
Range of Cr component, [-0.5, 0.5].
FillColor
YCbCr AForge.Imaging.Filters.YCbCrFiltering.FillColor get set
Fill color used to fill filtered pixels.
FillOutsideRange
bool AForge.Imaging.Filters.YCbCrFiltering.FillOutsideRange get set
Determines, if pixels should be filled inside or outside specified color range.
Default value is set to true, which means the filter removes colors outside of the specified range.
UpdateY
bool AForge.Imaging.Filters.YCbCrFiltering.UpdateY get set
Determines, if Y value of filtered pixels should be updated.
The property specifies if Y channel of filtered pixels should be updated with value from fill color or not.
Default value is set to true.
UpdateCb
bool AForge.Imaging.Filters.YCbCrFiltering.UpdateCb get set
Determines, if Cb value of filtered pixels should be updated.
The property specifies if Cb channel of filtered pixels should be updated with value from fill color or not.
Default value is set to true.
UpdateCr
bool AForge.Imaging.Filters.YCbCrFiltering.UpdateCr get set
Determines, if Cr value of filtered pixels should be updated.
The property specifies if Cr channel of filtered pixels should be updated with value from fill color or not.
Default value is set to true.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/YCbCr Filters/YCbCrFiltering.cs