Doc: IGLib EXTENDED: alglib.minlbfgs Class Reference
alglib.minlbfgs Class Reference
Classes
class minlbfgsreport
class minlbfgsstate
Static Public Member Functions
static void minlbfgscreate (int n, int m, double[] x, minlbfgsstate state)
static void minlbfgscreatef (int n, int m, double[] x, double diffstep, minlbfgsstate state)
static void minlbfgssetcond (minlbfgsstate state, double epsg, double epsf, double epsx, int maxits)
static void minlbfgssetxrep (minlbfgsstate state, bool needxrep)
static void minlbfgssetstpmax (minlbfgsstate state, double stpmax)
static void minlbfgssetscale (minlbfgsstate state, double[] s)
static void minlbfgscreatex (int n, int m, double[] x, int flags, double diffstep, minlbfgsstate state)
static void minlbfgssetprecdefault (minlbfgsstate state)
static void minlbfgssetpreccholesky (minlbfgsstate state, double[,] p, bool isupper)
static void minlbfgssetprecdiag (minlbfgsstate state, double[] d)
static void minlbfgssetprecscale (minlbfgsstate state)
static bool minlbfgsiteration (minlbfgsstate state)
static void minlbfgsresults (minlbfgsstate state, ref double[] x, minlbfgsreport rep)
static void minlbfgsresultsbuf (minlbfgsstate state, ref double[] x, minlbfgsreport rep)
static void minlbfgsrestartfrom (minlbfgsstate state, double[] x)
static void minlbfgssetgradientcheck (minlbfgsstate state, double teststep)
static void minlbfgscreate (int n, int m, double[] x, minlbfgsstate state)
static void minlbfgscreatef (int n, int m, double[] x, double diffstep, minlbfgsstate state)
static void minlbfgssetcond (minlbfgsstate state, double epsg, double epsf, double epsx, int maxits)
static void minlbfgssetxrep (minlbfgsstate state, bool needxrep)
static void minlbfgssetstpmax (minlbfgsstate state, double stpmax)
static void minlbfgssetscale (minlbfgsstate state, double[] s)
static void minlbfgscreatex (int n, int m, double[] x, int flags, double diffstep, minlbfgsstate state)
static void minlbfgssetprecdefault (minlbfgsstate state)
static void minlbfgssetpreccholesky (minlbfgsstate state, double[,] p, bool isupper)
static void minlbfgssetprecdiag (minlbfgsstate state, double[] d)
static void minlbfgssetprecscale (minlbfgsstate state)
static bool minlbfgsiteration (minlbfgsstate state)
static void minlbfgsresults (minlbfgsstate state, ref double[] x, minlbfgsreport rep)
static void minlbfgsresultsbuf (minlbfgsstate state, ref double[] x, minlbfgsreport rep)
static void minlbfgsrestartfrom (minlbfgsstate state, double[] x)
static void minlbfgssetgradientcheck (minlbfgsstate state, double teststep)
Static Public Attributes
const double gtol = 0.4
Static Private Member Functions
static void clearrequestfields (minlbfgsstate state)
static void clearrequestfields (minlbfgsstate state)
Member Function Documentation
minlbfgscreate() [1/2]
static void alglib.minlbfgs.minlbfgscreate (int n, int m, double[] x, minlbfgsstate state) inline static
References alglib.ap.assert().
Referenced by alglib.testminlbfgsunit.gradientchecktest(), alglib.minlbfgscreate(), alglib.testminlbfgsunit.testminlbfgs(), alglib.testminlbfgsunit.testother(), and alglib.testminlbfgsunit.testpreconditioning().
minlbfgscreatef() [1/2]
static void alglib.minlbfgs.minlbfgscreatef (int n, int m, double[] x, double diffstep, minlbfgsstate state) inline static
Referenced by alglib.minlbfgscreatef(), alglib.testminlbfgsunit.testminlbfgs(), and alglib.testminlbfgsunit.testother().
minlbfgssetcond() [1/2]
static void alglib.minlbfgs.minlbfgssetcond (minlbfgsstate state, double epsg, double epsf, double epsx, int maxits) inline static
Referenced by alglib.testminlbfgsunit.gradientchecktest(), alglib.minlbfgssetcond(), alglib.testminlbfgsunit.testminlbfgs(), and alglib.testminlbfgsunit.testother().
minlbfgssetxrep() [1/2]
static void alglib.minlbfgs.minlbfgssetxrep (minlbfgsstate state, bool needxrep) inline static
Referenced by alglib.minlbfgssetxrep(), and alglib.testminlbfgsunit.testother().
minlbfgssetstpmax() [1/2]
static void alglib.minlbfgs.minlbfgssetstpmax (minlbfgsstate state, double stpmax) inline static
Referenced by alglib.minlbfgssetstpmax(), alglib.testminlbfgsunit.testminlbfgs(), and alglib.testminlbfgsunit.testother().
minlbfgssetscale() [1/2]
static void alglib.minlbfgs.minlbfgssetscale (minlbfgsstate state, double[] s) inline static
Referenced by alglib.minlbfgssetscale(), alglib.testminlbfgsunit.testother(), and alglib.testminlbfgsunit.testpreconditioning().
minlbfgscreatex() [1/2]
static void alglib.minlbfgs.minlbfgscreatex (int n, int m, double[] x, int flags, double diffstep, minlbfgsstate state) inline static
minlbfgssetprecdefault() [1/2]
static void alglib.minlbfgs.minlbfgssetprecdefault (minlbfgsstate state) inline static
Referenced by alglib.minlbfgssetprecdefault(), and alglib.testminlbfgsunit.testpreconditioning().
minlbfgssetpreccholesky() [1/2]
static void alglib.minlbfgs.minlbfgssetpreccholesky (minlbfgsstate state, double p[,], bool isupper) inline static
Referenced by alglib.minlbfgssetpreccholesky(), and alglib.testminlbfgsunit.testpreconditioning().
minlbfgssetprecdiag() [1/2]
static void alglib.minlbfgs.minlbfgssetprecdiag (minlbfgsstate state, double[] d) inline static
Referenced by alglib.minlbfgssetprecdiag(), alglib.testminlbfgsunit.testother(), and alglib.testminlbfgsunit.testpreconditioning().
minlbfgssetprecscale() [1/2]
static void alglib.minlbfgs.minlbfgssetprecscale (minlbfgsstate state) inline static
Referenced by alglib.minlbfgssetprecscale(), alglib.testminlbfgsunit.testother(), and alglib.testminlbfgsunit.testpreconditioning().
minlbfgsiteration() [1/2]
static bool alglib.minlbfgs.minlbfgsiteration (minlbfgsstate state) inline static
Referenced by alglib.testminlbfgsunit.gradientchecktest(), alglib.minlbfgsiteration(), alglib.testminlbfgsunit.testminlbfgs(), alglib.testminlbfgsunit.testother(), and alglib.testminlbfgsunit.testpreconditioning().
minlbfgsresults() [1/2]
static void alglib.minlbfgs.minlbfgsresults (minlbfgsstate state, ref double[] x, minlbfgsreport rep) inline static
Referenced by alglib.testminlbfgsunit.gradientchecktest(), alglib.minlbfgsresults(), alglib.testminlbfgsunit.testminlbfgs(), alglib.testminlbfgsunit.testother(), and alglib.testminlbfgsunit.testpreconditioning().
minlbfgsresultsbuf() [1/2]
static void alglib.minlbfgs.minlbfgsresultsbuf (minlbfgsstate state, ref double[] x, minlbfgsreport rep) inline static
Referenced by alglib.minlbfgsresultsbuf().
minlbfgsrestartfrom() [1/2]
static void alglib.minlbfgs.minlbfgsrestartfrom (minlbfgsstate state, double[] x) inline static
Referenced by alglib.testminlbfgsunit.gradientchecktest(), alglib.minlbfgsrestartfrom(), alglib.testminlbfgsunit.testminlbfgs(), alglib.testminlbfgsunit.testother(), and alglib.testminlbfgsunit.testpreconditioning().
minlbfgssetgradientcheck() [1/2]
static void alglib.minlbfgs.minlbfgssetgradientcheck (minlbfgsstate state, double teststep) inline static
Referenced by alglib.testminlbfgsunit.gradientchecktest(), and alglib.minlbfgssetgradientcheck().
clearrequestfields() [1/2]
static void alglib.minlbfgs.clearrequestfields (minlbfgsstate state) inline static private
minlbfgscreate() [2/2]
static void alglib.minlbfgs.minlbfgscreate (int n, int m, double[] x, minlbfgsstate state) inline static
minlbfgscreatef() [2/2]
static void alglib.minlbfgs.minlbfgscreatef (int n, int m, double[] x, double diffstep, minlbfgsstate state) inline static
minlbfgssetcond() [2/2]
static void alglib.minlbfgs.minlbfgssetcond (minlbfgsstate state, double epsg, double epsf, double epsx, int maxits) inline static
minlbfgssetxrep() [2/2]
static void alglib.minlbfgs.minlbfgssetxrep (minlbfgsstate state, bool needxrep) inline static
minlbfgssetstpmax() [2/2]
static void alglib.minlbfgs.minlbfgssetstpmax (minlbfgsstate state, double stpmax) inline static
minlbfgssetscale() [2/2]
static void alglib.minlbfgs.minlbfgssetscale (minlbfgsstate state, double[] s) inline static
minlbfgscreatex() [2/2]
static void alglib.minlbfgs.minlbfgscreatex (int n, int m, double[] x, int flags, double diffstep, minlbfgsstate state) inline static
minlbfgssetprecdefault() [2/2]
static void alglib.minlbfgs.minlbfgssetprecdefault (minlbfgsstate state) inline static
minlbfgssetpreccholesky() [2/2]
static void alglib.minlbfgs.minlbfgssetpreccholesky (minlbfgsstate state, double p[,], bool isupper) inline static
minlbfgssetprecdiag() [2/2]
static void alglib.minlbfgs.minlbfgssetprecdiag (minlbfgsstate state, double[] d) inline static
minlbfgssetprecscale() [2/2]
static void alglib.minlbfgs.minlbfgssetprecscale (minlbfgsstate state) inline static
minlbfgsiteration() [2/2]
static bool alglib.minlbfgs.minlbfgsiteration (minlbfgsstate state) inline static
minlbfgsresults() [2/2]
static void alglib.minlbfgs.minlbfgsresults (minlbfgsstate state, ref double[] x, minlbfgsreport rep) inline static
minlbfgsresultsbuf() [2/2]
static void alglib.minlbfgs.minlbfgsresultsbuf (minlbfgsstate state, ref double[] x, minlbfgsreport rep) inline static
minlbfgsrestartfrom() [2/2]
static void alglib.minlbfgs.minlbfgsrestartfrom (minlbfgsstate state, double[] x) inline static
minlbfgssetgradientcheck() [2/2]
static void alglib.minlbfgs.minlbfgssetgradientcheck (minlbfgsstate state, double teststep) inline static
clearrequestfields() [2/2]
static void alglib.minlbfgs.clearrequestfields (minlbfgsstate state) inline static private
Member Data Documentation
gtol
const double alglib.minlbfgs.gtol = 0.4 static
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/optimization.cs