Doc: IGLib EXTENDED: NUnit.Framework.Attributes.RequiresThreadAttributeTests Class Reference
NUnit.Framework.Attributes.RequiresThreadAttributeTests Class Reference
Classes
class ChildFixtureRequiresThread
class FixtureRequiresThread
Public Member Functions
void GetSetUpThreadInfo ()
void TestWithRequiresThreadRunsInSeparateThread ()
void TestWithRequiresThreadRunsSetUpAndTestOnSameThread ()
void TestWithRequiresThreadWithSTAArgRunsOnSeparateThreadInSTA ()
void TestWithRequiresThreadWithMTAArgRunsOnSeparateThreadInMTA ()
Public Member Functions inherited from NUnit.Framework.Attributes.ThreadingTests
void GetParentThreadInfo ()
Properties
Thread SetupThread [get, set]
Properties inherited from NUnit.Framework.Attributes.ThreadingTests
Thread ParentThread [get, private set]
ApartmentState ParentThreadApartment [get, private set]
Additional Inherited Members
Static Protected Member Functions inherited from NUnit.Framework.Attributes.ThreadingTests
static ApartmentState GetApartmentState (Thread thread)
Member Function Documentation
GetSetUpThreadInfo()
void NUnit.Framework.Attributes.RequiresThreadAttributeTests.GetSetUpThreadInfo () inline
References NUnit.Framework.Attributes.RequiresThreadAttributeTests.SetupThread.
TestWithRequiresThreadRunsInSeparateThread()
void NUnit.Framework.Attributes.RequiresThreadAttributeTests.TestWithRequiresThreadRunsInSeparateThread () inline
References NUnit.Framework.Is.Not, NUnit.Framework.Attributes.ThreadingTests.ParentThread, and NUnit.Framework.Assert.That().
TestWithRequiresThreadRunsSetUpAndTestOnSameThread()
void NUnit.Framework.Attributes.RequiresThreadAttributeTests.TestWithRequiresThreadRunsSetUpAndTestOnSameThread () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.RequiresThreadAttributeTests.SetupThread, and NUnit.Framework.Assert.That().
TestWithRequiresThreadWithSTAArgRunsOnSeparateThreadInSTA()
void NUnit.Framework.Attributes.RequiresThreadAttributeTests.TestWithRequiresThreadWithSTAArgRunsOnSeparateThreadInSTA () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.ThreadingTests.GetApartmentState(), NUnit.Framework.Is.Not, NUnit.Framework.Attributes.ThreadingTests.ParentThread, and NUnit.Framework.Assert.That().
TestWithRequiresThreadWithMTAArgRunsOnSeparateThreadInMTA()
void NUnit.Framework.Attributes.RequiresThreadAttributeTests.TestWithRequiresThreadWithMTAArgRunsOnSeparateThreadInMTA () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.ThreadingTests.GetApartmentState(), NUnit.Framework.Is.Not, NUnit.Framework.Attributes.ThreadingTests.ParentThread, and NUnit.Framework.Assert.That().
Property Documentation
SetupThread
Thread NUnit.Framework.Attributes.RequiresThreadAttributeTests.SetupThread get set private
Referenced by NUnit.Framework.Attributes.RequiresThreadAttributeTests.GetSetUpThreadInfo(), and NUnit.Framework.Attributes.RequiresThreadAttributeTests.TestWithRequiresThreadRunsSetUpAndTestOnSameThread().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/RequiresThreadAttributeTests.cs