Doc: IGLib EXTENDED: IG.Forms.DirectorySelector Class Reference
IG.Forms.DirectorySelector Class Reference
Public Member Functions
DirectorySelector ()
string GetFilePathRepresentation (string directoryPath)
Returns the presentational form of the specified directory path, with eventual environment variables expanded and with conversion to the appropriate form (relative or absolute).
void BrowseDirectory ()
Browses for the file to be hashed.
void ClearHistory ()
DirectorySelector ()
string GetFilePathRepresentation (string directoryPath)
Returns the presentational form of the specified directory path, with eventual environment variables expanded and with conversion to the appropriate form (relative or absolute).
void BrowseDirectory ()
Browses for the file to be hashed.
void ClearHistory ()
DirectorySelector ()
string GetFilePathRepresentation (string directoryPath)
Returns the presentational form of the specified directory path, with eventual environment variables expanded and with conversion to the appropriate form (relative or absolute).
void BrowseDirectory ()
Browses for the file to be hashed.
void ClearHistory ()
Protected Member Functions
virtual void UpdateErrorState ()
Updates controls according to error state.
virtual void OnDirectorySelected ()
Called whenever the selected directory changes.
virtual void OnDirectoryChanged ()
Called whenever the directory containing the selected file changes.
void Handle_CtrlA_CtrlBackspace (TextBox textBox, object sender, KeyEventArgs e)
Handle the Ctrl-A (select all) and Ctrl-Backspace events for the specified text box.
override void Dispose (bool disposing)
Clean up any resources being used.
virtual void UpdateErrorState ()
Updates controls according to error state.
virtual void OnDirectorySelected ()
Called whenever the selected directory changes.
virtual void OnDirectoryChanged ()
Called whenever the directory containing the selected file changes.
void Handle_CtrlA_CtrlBackspace (TextBox textBox, object sender, KeyEventArgs e)
Handle the Ctrl-A (select all) and Ctrl-Backspace events for the specified text box.
override void Dispose (bool disposing)
Clean up any resources being used.
virtual void UpdateErrorState ()
Updates controls according to error state.
virtual void OnDirectorySelected ()
Called whenever the selected directory changes.
virtual void OnDirectoryChanged ()
Called whenever the directory containing the selected file changes.
void Handle_CtrlA_CtrlBackspace (TextBox textBox, object sender, KeyEventArgs e)
Handle the Ctrl-A (select all) and Ctrl-Backspace events for the specified text box.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
string _containingDirectoryPath
string _directoryPath
Properties
bool FileTextBoxInitialized [get, set]
string InitialDirectoryPath [get, protected set]
Directory where files are currently selected.
bool AllowEnvironmentVariables [get, set]
If true then environment variables can be used in paths.
bool AllowExistentDirectories [get, set]
If true then existent files are allowed to be selected.
bool AllowNonexistentDirectories [get, set]
If true then non-existend files are allowed to be selected.
bool UseRelativePaths [get, set]
If true then relative paths are used in representation of the selseted file path.
bool UseAbsolutePaths [get, set]
If true then absolute paths are used in representation of the selseted file path.
bool UseFileDialog [get, set]
If true then an OpenFileDialog is used to browse for directory, rather than Directorydialog bool UseFileDialog
string DirectoryPath [get, set]
Path to the file that is currently selected.
string OriginalDirectoryPath [get, set]
Gets the original file path representation (as set by user), without any post processing (like environment variables expansion or conversion to relative or absolute path).
virtual bool IsErrorState [get]
Returns true if the current selection is invalid, false if it is valid.
virtual Color ErrorBackground [get, set]
Background color of selection's text in case of error.
virtual Color ErrorForeground [get, set]
Foreground color of button in case of error.
virtual Color NormalBackground [get, set]
Background color of selection's text in case of NO error.
virtual Color NormalForeground [get, set]
Foreground color of button in case of NO error.
bool IsBrowsable [get, set]
Gets or sets the flag specifying whether one can browse for the file to be opened (e.g. by using the file selection dialog).
bool IsDragAndDrop [get, set]
Whether the selector provides drag & drop capability.
Events
EventHandler DirectorySelected
Event that is fired whenever the selected directory changes.
EventHandler DirectoryChanged
Event that is fired whenever directory containing the selected file changes.
Private Member Functions
void btnFileBrowse_Click (object sender, EventArgs e)
Browses for the file whose hash values will be calculated.
void txtFile_Click (object sender, EventArgs e)
void comboBoxFile_SelectedIndexChanged (object sender, EventArgs e)
void comboBoxFile_Enter (object sender, EventArgs e)
void comboBoxFile_Validated (object sender, EventArgs e)
void comboBoxFile_KeyUp (object sender, KeyEventArgs e)
void comboBoxFile_MouseEnter (object sender, EventArgs e)
void comboBoxFile_TextChanged (object sender, EventArgs e)
void FileSelector_DragEnter (object sender, DragEventArgs e)
void FileSelector_DragDrop (object sender, DragEventArgs e)
void menuClearHistory_Click (object sender, EventArgs e)
void menuAllowNonexistent_CheckedChanged (object sender, EventArgs e)
void menuAllowExistent_CheckedChanged (object sender, EventArgs e)
void menuExpandEnvironment_CheckedChanged (object sender, EventArgs e)
void menuAbsolutePaths_CheckedChanged (object sender, EventArgs e)
void menuRelativePaths_CheckedChanged (object sender, EventArgs e)
void menuPathRepresentation_Click (object sender, EventArgs e)
void menuInputTextBox_Click (object sender, EventArgs e)
void menuInputTextBox_Validated (object sender, EventArgs e)
void menuInputTextBox_KeyUp (object sender, KeyEventArgs e)
void menuAllowNonexistent_Click (object sender, EventArgs e)
Reopens the context menu at its previous position.
void menuAllowExistent_Click (object sender, EventArgs e)
Reopens the context menu at its previous position.
void menuExpandEnvironment_Click (object sender, EventArgs e)
Reopens the context menu at its previous position.
void menuUseFileDialog_Click (object sender, EventArgs e)
void menuUseFileDialog_CheckedChanged (object sender, EventArgs e)
void menuAbsolutePaths_Click (object sender, EventArgs e)
Reopens the context menu at its previous position.
void menuRelativePaths_Click (object sender, EventArgs e)
Reopens the context menu at its previous position.
void contextMenuMain_Opened (object sender, EventArgs e)
Stores the position where the menu item has last opened.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void btnFileBrowse_Click (object sender, EventArgs e)
Browses for the file whose hash values will be calculated.
void txtFile_Click (object sender, EventArgs e)
void comboBoxFile_SelectedIndexChanged (object sender, EventArgs e)
void comboBoxFile_Enter (object sender, EventArgs e)
void comboBoxFile_Validated (object sender, EventArgs e)
void comboBoxFile_KeyUp (object sender, KeyEventArgs e)
void comboBoxFile_MouseEnter (object sender, EventArgs e)
void comboBoxFile_TextChanged (object sender, EventArgs e)
void FileSelector_DragEnter (object sender, DragEventArgs e)
void FileSelector_DragDrop (object sender, DragEventArgs e)
void menuClearHistory_Click (object sender, EventArgs e)
void menuAllowNonexistent_CheckedChanged (object sender, EventArgs e)
void menuAllowExistent_CheckedChanged (object sender, EventArgs e)
void menuExpandEnvironment_CheckedChanged (object sender, EventArgs e)
void menuAbsolutePaths_CheckedChanged (object sender, EventArgs e)
void menuRelativePaths_CheckedChanged (object sender, EventArgs e)
void menuPathRepresentation_Click (object sender, EventArgs e)
void menuInputTextBox_Click (object sender, EventArgs e)
void menuInputTextBox_Validated (object sender, EventArgs e)
void menuInputTextBox_KeyUp (object sender, KeyEventArgs e)
void menuAllowNonexistent_Click (object sender, EventArgs e)
Reopens the context menu at its previous position.
void menuAllowExistent_Click (object sender, EventArgs e)
Reopens the context menu at its previous position.
void menuExpandEnvironment_Click (object sender, EventArgs e)
Reopens the context menu at its previous position.
void menuUseFileDialog_Click (object sender, EventArgs e)
void menuUseFileDialog_CheckedChanged (object sender, EventArgs e)
void menuAbsolutePaths_Click (object sender, EventArgs e)
Reopens the context menu at its previous position.
void menuRelativePaths_Click (object sender, EventArgs e)
Reopens the context menu at its previous position.
void contextMenuMain_Opened (object sender, EventArgs e)
Stores the position where the menu item has last opened.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void btnFileBrowse_Click (object sender, EventArgs e)
Browses for the file whose hash values will be calculated.
void txtFile_Click (object sender, EventArgs e)
void comboBoxFile_SelectedIndexChanged (object sender, EventArgs e)
void comboBoxFile_Enter (object sender, EventArgs e)
void comboBoxFile_Validated (object sender, EventArgs e)
void comboBoxFile_KeyUp (object sender, KeyEventArgs e)
void comboBoxFile_MouseEnter (object sender, EventArgs e)
void comboBoxFile_TextChanged (object sender, EventArgs e)
void FileSelector_DragEnter (object sender, DragEventArgs e)
void FileSelector_DragDrop (object sender, DragEventArgs e)
void menuClearHistory_Click (object sender, EventArgs e)
void menuAllowNonexistent_CheckedChanged (object sender, EventArgs e)
void menuAllowExistent_CheckedChanged (object sender, EventArgs e)
void menuExpandEnvironment_CheckedChanged (object sender, EventArgs e)
void menuAbsolutePaths_CheckedChanged (object sender, EventArgs e)
void menuRelativePaths_CheckedChanged (object sender, EventArgs e)
void menuPathRepresentation_Click (object sender, EventArgs e)
void menuInputTextBox_Click (object sender, EventArgs e)
void menuInputTextBox_Validated (object sender, EventArgs e)
void menuInputTextBox_KeyUp (object sender, KeyEventArgs e)
void menuAllowNonexistent_Click (object sender, EventArgs e)
Reopens the context menu at its previous position.
void menuAllowExistent_Click (object sender, EventArgs e)
Reopens the context menu at its previous position.
void menuExpandEnvironment_Click (object sender, EventArgs e)
Reopens the context menu at its previous position.
void menuUseFileDialog_Click (object sender, EventArgs e)
void menuUseFileDialog_CheckedChanged (object sender, EventArgs e)
void menuAbsolutePaths_Click (object sender, EventArgs e)
Reopens the context menu at its previous position.
void menuRelativePaths_Click (object sender, EventArgs e)
Reopens the context menu at its previous position.
void contextMenuMain_Opened (object sender, EventArgs e)
Stores the position where the menu item has last opened.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
bool _fileTextBoxInitialized = false
bool _allowEnvironmentVariables = true
bool _allowExistentDirectories = true
bool _allowNonexistentDirectories = true
bool _useRelativePaths = false
bool _useAbsolutePaths = false
bool _useFileDialog = true
Color _errorBackground = Color.Orange
Color _errorForeground = Color.Red
Color _normalBackground = Color.White
Color _normalforeground = Color.Black
bool _isBrowsable = true
bool _isDragAndDrop = true
bool _skipFileValidationEvent = false
Point _lasContectMenuPosition = new Point(0, 0)
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Button btnFileBrowse
System.Windows.Forms.Label lblFile
System.Windows.Forms.FolderBrowserDialog openDirectoryDialog1
System.Windows.Forms.ComboBox comboBoxFile
System.Windows.Forms.ContextMenuStrip contextMenuMain
System.Windows.Forms.ToolStripMenuItem menuClearHistory
System.Windows.Forms.ToolStripMenuItem menuAllowNonexistent
System.Windows.Forms.ToolStripMenuItem menuAllowExistent
System.Windows.Forms.ToolStripMenuItem menuExpandEnvironment
System.Windows.Forms.ToolStripMenuItem menuAbsolutePaths
System.Windows.Forms.ToolStripMenuItem menuRelativePaths
System.Windows.Forms.ToolStripMenuItem menuShowPath
System.Windows.Forms.ToolStripMenuItem menuPathRepresentation
System.Windows.Forms.ToolStripMenuItem menuInputPath
System.Windows.Forms.ToolStripTextBox menuInputTextBox
System.Windows.Forms.ToolStripMenuItem menuUseFileDialog
System.Windows.Forms.OpenFileDialog openFileDialog1
Constructor & Destructor Documentation
DirectorySelector() [1/3]
IG.Forms.DirectorySelector.DirectorySelector () inline
References IG.Forms.DirectorySelector.AllowEnvironmentVariables, IG.Forms.DirectorySelector.AllowExistentDirectories, IG.Forms.DirectorySelector.AllowNonexistentDirectories, IG.Forms.DirectorySelector.comboBoxFile, IG.Forms.DirectorySelector.DirectoryPath, IG.Forms.DirectorySelector.InitializeComponent(), IG.Forms.DirectorySelector.menuAbsolutePaths, IG.Forms.DirectorySelector.menuAllowExistent, IG.Forms.DirectorySelector.menuAllowNonexistent, IG.Forms.DirectorySelector.menuExpandEnvironment, IG.Forms.DirectorySelector.menuInputTextBox, IG.Forms.DirectorySelector.menuPathRepresentation, IG.Forms.DirectorySelector.menuRelativePaths, IG.Forms.DirectorySelector.menuUseFileDialog, IG.Forms.DirectorySelector.NormalBackground, IG.Forms.DirectorySelector.OriginalDirectoryPath, IG.Forms.DirectorySelector.UpdateErrorState(), IG.Forms.DirectorySelector.UseAbsolutePaths, IG.Forms.DirectorySelector.UseFileDialog, and IG.Forms.DirectorySelector.UseRelativePaths.
DirectorySelector() [2/3]
IG.Forms.DirectorySelector.DirectorySelector () inline
References IG.Forms.DirectorySelector.AllowEnvironmentVariables, IG.Forms.DirectorySelector.AllowExistentDirectories, IG.Forms.DirectorySelector.AllowNonexistentDirectories, IG.Forms.DirectorySelector.comboBoxFile, IG.Forms.DirectorySelector.DirectoryPath, IG.Forms.DirectorySelector.InitializeComponent(), IG.Forms.DirectorySelector.menuAbsolutePaths, IG.Forms.DirectorySelector.menuAllowExistent, IG.Forms.DirectorySelector.menuAllowNonexistent, IG.Forms.DirectorySelector.menuExpandEnvironment, IG.Forms.DirectorySelector.menuInputTextBox, IG.Forms.DirectorySelector.menuPathRepresentation, IG.Forms.DirectorySelector.menuRelativePaths, IG.Forms.DirectorySelector.menuUseFileDialog, IG.Forms.DirectorySelector.NormalBackground, IG.Forms.DirectorySelector.OriginalDirectoryPath, IG.Forms.DirectorySelector.UpdateErrorState(), IG.Forms.DirectorySelector.UseAbsolutePaths, IG.Forms.DirectorySelector.UseFileDialog, and IG.Forms.DirectorySelector.UseRelativePaths.
DirectorySelector() [3/3]
IG.Forms.DirectorySelector.DirectorySelector () inline
References IG.Forms.DirectorySelector.AllowEnvironmentVariables, IG.Forms.DirectorySelector.AllowExistentDirectories, IG.Forms.DirectorySelector.AllowNonexistentDirectories, IG.Forms.DirectorySelector.comboBoxFile, IG.Forms.DirectorySelector.DirectoryPath, IG.Forms.DirectorySelector.InitializeComponent(), IG.Forms.DirectorySelector.menuAbsolutePaths, IG.Forms.DirectorySelector.menuAllowExistent, IG.Forms.DirectorySelector.menuAllowNonexistent, IG.Forms.DirectorySelector.menuExpandEnvironment, IG.Forms.DirectorySelector.menuInputTextBox, IG.Forms.DirectorySelector.menuPathRepresentation, IG.Forms.DirectorySelector.menuRelativePaths, IG.Forms.DirectorySelector.menuUseFileDialog, IG.Forms.DirectorySelector.NormalBackground, IG.Forms.DirectorySelector.OriginalDirectoryPath, IG.Forms.DirectorySelector.UpdateErrorState(), IG.Forms.DirectorySelector.UseAbsolutePaths, IG.Forms.DirectorySelector.UseFileDialog, and IG.Forms.DirectorySelector.UseRelativePaths.
Member Function Documentation
GetFilePathRepresentation() [1/3]
string IG.Forms.DirectorySelector.GetFilePathRepresentation (string directoryPath) inline
Returns the presentational form of the specified directory path, with eventual environment variables expanded and with conversion to the appropriate form (relative or absolute).
Parameters
directoryPath Directory path whose presentational form is returned.
Presentational form depends on the following properties: <pra> - AllowEnvironmentVariables: If true then environment variable references are expanded.
In Unix-like systems, enviironment variables are referenced as $varName, and on Windows with varName%.
</pra>
- UseAbsolutePaths: If true then paths are presented as absolute paths (independend of the current working directory).
- UseRelativePaths: If true then paths are represented relative to the current working directory.
References IG.Forms.DirectorySelector.AllowEnvironmentVariables, IG.Forms.DirectorySelector.AllowExistentDirectories, IG.Forms.DirectorySelector.AllowNonexistentDirectories, IG.Lib.UtilSystem.GetAbsolutePath(), IG.Lib.UtilSystem.GetRelativePath(), IG.Forms.DirectorySelector.UseAbsolutePaths, and IG.Forms.DirectorySelector.UseRelativePaths.
UpdateErrorState() [1/3]
virtual void IG.Forms.DirectorySelector.UpdateErrorState () inline protected virtual
Updates controls according to error state.
References IG.Forms.DirectorySelector.btnFileBrowse, IG.Forms.DirectorySelector.comboBoxFile, IG.Forms.DirectorySelector.ErrorBackground, IG.Forms.DirectorySelector.ErrorForeground, IG.Forms.DirectorySelector.IsErrorState, IG.Forms.DirectorySelector.NormalBackground, and IG.Forms.DirectorySelector.NormalForeground.
Referenced by IG.Forms.DirectorySelector.DirectorySelector().
BrowseDirectory() [1/3]
void IG.Forms.DirectorySelector.BrowseDirectory () inline
Browses for the file to be hashed.
References IG.Forms.DirectorySelector.AllowExistentDirectories, IG.Forms.DirectorySelector.AllowNonexistentDirectories, IG.Forms.DirectorySelector.DirectoryPath, IG.Forms.DirectorySelector.InitialDirectoryPath, IG.Forms.DirectorySelector.openDirectoryDialog1, IG.Forms.DirectorySelector.openFileDialog1, and IG.Forms.DirectorySelector.UseFileDialog.
Referenced by IG.Forms.DirectorySelector.BrowseDirectory(), and IG.Forms.DirectorySelector.btnFileBrowse_Click().
ClearHistory() [1/3]
void IG.Forms.DirectorySelector.ClearHistory () inline
References IG.Forms.DirectorySelector.comboBoxFile.
Referenced by IG.Forms.DirectorySelector.menuClearHistory_Click().
OnDirectorySelected() [1/3]
virtual void IG.Forms.DirectorySelector.OnDirectorySelected () inline protected virtual
Called whenever the selected directory changes.
References IG.Forms.DirectorySelector.DirectorySelected.
OnDirectoryChanged() [1/3]
virtual void IG.Forms.DirectorySelector.OnDirectoryChanged () inline protected virtual
Called whenever the directory containing the selected file changes.
References IG.Forms.DirectorySelector.DirectoryChanged.
btnFileBrowse_Click() [1/3]
void IG.Forms.DirectorySelector.btnFileBrowse_Click (object sender, EventArgs e) inline private
Browses for the file whose hash values will be calculated.
References IG.Forms.DirectorySelector.BrowseDirectory(), and IG.Forms.DirectorySelector.DirectoryPath.
Referenced by IG.Forms.DirectorySelector.InitializeComponent().
Handle_CtrlA_CtrlBackspace() [1/3]
void IG.Forms.DirectorySelector.Handle_CtrlA_CtrlBackspace (TextBox textBox, object sender, KeyEventArgs e) inline protected
Handle the Ctrl-A (select all) and Ctrl-Backspace events for the specified text box.
Parameters
textBox Text box for wich the event is handled.
txtFile_Click() [1/3]
void IG.Forms.DirectorySelector.txtFile_Click (object sender, EventArgs e) inline private
comboBoxFile_SelectedIndexChanged() [1/3]
void IG.Forms.DirectorySelector.comboBoxFile_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.comboBoxFile, and IG.Forms.DirectorySelector.DirectoryPath.
Referenced by IG.Forms.DirectorySelector.InitializeComponent().
comboBoxFile_Enter() [1/3]
void IG.Forms.DirectorySelector.comboBoxFile_Enter (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.comboBoxFile, and IG.Forms.DirectorySelector.FileTextBoxInitialized.
Referenced by IG.Forms.DirectorySelector.InitializeComponent().
comboBoxFile_Validated() [1/3]
void IG.Forms.DirectorySelector.comboBoxFile_Validated (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector._skipFileValidationEvent, IG.Forms.DirectorySelector.comboBoxFile, IG.Forms.DirectorySelector.DirectoryPath, IG.Forms.DirectorySelector.FileTextBoxInitialized, and IG.Forms.DirectorySelector.OriginalDirectoryPath.
Referenced by IG.Forms.DirectorySelector.comboBoxFile_KeyUp(), IG.Forms.DirectorySelector.FileSelector_DragDrop(), and IG.Forms.DirectorySelector.InitializeComponent().
comboBoxFile_KeyUp() [1/3]
void IG.Forms.DirectorySelector.comboBoxFile_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Forms.DirectorySelector.comboBoxFile, IG.Forms.DirectorySelector.comboBoxFile_Validated(), and IG.Forms.DirectorySelector.FileTextBoxInitialized.
Referenced by IG.Forms.DirectorySelector.InitializeComponent().
comboBoxFile_MouseEnter() [1/3]
void IG.Forms.DirectorySelector.comboBoxFile_MouseEnter (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.comboBoxFile, and IG.Forms.DirectorySelector.FileTextBoxInitialized.
Referenced by IG.Forms.DirectorySelector.InitializeComponent().
comboBoxFile_TextChanged() [1/3]
void IG.Forms.DirectorySelector.comboBoxFile_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.FileTextBoxInitialized.
Referenced by IG.Forms.DirectorySelector.InitializeComponent().
FileSelector_DragEnter() [1/3]
void IG.Forms.DirectorySelector.FileSelector_DragEnter (object sender, DragEventArgs e) inline private
References IG.Forms.DirectorySelector.IsDragAndDrop.
Referenced by IG.Forms.DirectorySelector.InitializeComponent().
FileSelector_DragDrop() [1/3]
void IG.Forms.DirectorySelector.FileSelector_DragDrop (object sender, DragEventArgs e) inline private
References IG.Forms.DirectorySelector.comboBoxFile, IG.Forms.DirectorySelector.comboBoxFile_Validated(), and IG.Forms.DirectorySelector.IsDragAndDrop.
Referenced by IG.Forms.DirectorySelector.InitializeComponent().
menuClearHistory_Click() [1/3]
void IG.Forms.DirectorySelector.menuClearHistory_Click (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.ClearHistory().
menuAllowNonexistent_CheckedChanged() [1/3]
void IG.Forms.DirectorySelector.menuAllowNonexistent_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.AllowNonexistentDirectories, and IG.Forms.DirectorySelector.menuAllowNonexistent.
menuAllowExistent_CheckedChanged() [1/3]
void IG.Forms.DirectorySelector.menuAllowExistent_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.AllowExistentDirectories, and IG.Forms.DirectorySelector.menuAllowExistent.
menuExpandEnvironment_CheckedChanged() [1/3]
void IG.Forms.DirectorySelector.menuExpandEnvironment_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.AllowEnvironmentVariables, and IG.Forms.DirectorySelector.menuExpandEnvironment.
menuAbsolutePaths_CheckedChanged() [1/3]
void IG.Forms.DirectorySelector.menuAbsolutePaths_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.menuAbsolutePaths, and IG.Forms.DirectorySelector.UseAbsolutePaths.
menuRelativePaths_CheckedChanged() [1/3]
void IG.Forms.DirectorySelector.menuRelativePaths_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.menuRelativePaths, and IG.Forms.DirectorySelector.UseRelativePaths.
menuPathRepresentation_Click() [1/3]
void IG.Forms.DirectorySelector.menuPathRepresentation_Click (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.DirectoryPath, IG.Forms.DirectorySelector.InitialDirectoryPath, and IG.Forms.DirectorySelector.OriginalDirectoryPath.
menuInputTextBox_Click() [1/3]
void IG.Forms.DirectorySelector.menuInputTextBox_Click (object sender, EventArgs e) inline private
menuInputTextBox_Validated() [1/3]
void IG.Forms.DirectorySelector.menuInputTextBox_Validated (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.DirectoryPath, and IG.Forms.DirectorySelector.menuInputTextBox.
Referenced by IG.Forms.DirectorySelector.menuInputTextBox_KeyUp().
menuInputTextBox_KeyUp() [1/3]
void IG.Forms.DirectorySelector.menuInputTextBox_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Forms.DirectorySelector.comboBoxFile, and IG.Forms.DirectorySelector.menuInputTextBox_Validated().
menuAllowNonexistent_Click() [1/3]
void IG.Forms.DirectorySelector.menuAllowNonexistent_Click (object sender, EventArgs e) inline private
Reopens the context menu at its previous position.
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
menuAllowExistent_Click() [1/3]
void IG.Forms.DirectorySelector.menuAllowExistent_Click (object sender, EventArgs e) inline private
Reopens the context menu at its previous position.
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
menuExpandEnvironment_Click() [1/3]
void IG.Forms.DirectorySelector.menuExpandEnvironment_Click (object sender, EventArgs e) inline private
Reopens the context menu at its previous position.
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
menuUseFileDialog_Click() [1/3]
void IG.Forms.DirectorySelector.menuUseFileDialog_Click (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
menuUseFileDialog_CheckedChanged() [1/3]
void IG.Forms.DirectorySelector.menuUseFileDialog_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.menuUseFileDialog, and IG.Forms.DirectorySelector.UseFileDialog.
menuAbsolutePaths_Click() [1/3]
void IG.Forms.DirectorySelector.menuAbsolutePaths_Click (object sender, EventArgs e) inline private
Reopens the context menu at its previous position.
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
menuRelativePaths_Click() [1/3]
void IG.Forms.DirectorySelector.menuRelativePaths_Click (object sender, EventArgs e) inline private
Reopens the context menu at its previous position.
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
contextMenuMain_Opened() [1/3]
void IG.Forms.DirectorySelector.contextMenuMain_Opened (object sender, EventArgs e) inline private
Stores the position where the menu item has last opened.
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
Dispose() [1/3]
override void IG.Forms.DirectorySelector.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.DirectorySelector.components.
InitializeComponent() [1/3]
void IG.Forms.DirectorySelector.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.DirectorySelector.btnFileBrowse, IG.Forms.DirectorySelector.btnFileBrowse_Click(), IG.Forms.DirectorySelector.comboBoxFile, IG.Forms.DirectorySelector.comboBoxFile_Enter(), IG.Forms.DirectorySelector.comboBoxFile_KeyUp(), IG.Forms.DirectorySelector.comboBoxFile_MouseEnter(), IG.Forms.DirectorySelector.comboBoxFile_SelectedIndexChanged(), IG.Forms.DirectorySelector.comboBoxFile_TextChanged(), IG.Forms.DirectorySelector.comboBoxFile_Validated(), IG.Forms.DirectorySelector.components, IG.Forms.DirectorySelector.contextMenuMain, IG.Forms.DirectorySelector.FileSelector_DragDrop(), IG.Forms.DirectorySelector.FileSelector_DragEnter(), IG.Forms.DirectorySelector.lblFile, IG.Forms.DirectorySelector.menuAbsolutePaths, IG.Forms.DirectorySelector.menuAllowExistent, IG.Forms.DirectorySelector.menuAllowNonexistent, IG.Forms.DirectorySelector.menuClearHistory, IG.Forms.DirectorySelector.menuExpandEnvironment, IG.Forms.DirectorySelector.menuInputPath, IG.Forms.DirectorySelector.menuInputTextBox, IG.Forms.DirectorySelector.menuPathRepresentation, IG.Forms.DirectorySelector.menuRelativePaths, IG.Forms.DirectorySelector.menuShowPath, IG.Forms.DirectorySelector.menuUseFileDialog, IG.Forms.DirectorySelector.openDirectoryDialog1, and IG.Forms.DirectorySelector.openFileDialog1.
Referenced by IG.Forms.DirectorySelector.DirectorySelector().
GetFilePathRepresentation() [2/3]
string IG.Forms.DirectorySelector.GetFilePathRepresentation (string directoryPath) inline
Returns the presentational form of the specified directory path, with eventual environment variables expanded and with conversion to the appropriate form (relative or absolute).
Parameters
directoryPath Directory path whose presentational form is returned.
Presentational form depends on the following properties: <pra> - AllowEnvironmentVariables: If true then environment variable references are expanded.
In Unix-like systems, enviironment variables are referenced as $varName, and on Windows with varName%.
</pra>
- UseAbsolutePaths: If true then paths are presented as absolute paths (independend of the current working directory).
- UseRelativePaths: If true then paths are represented relative to the current working directory.
References IG.Forms.DirectorySelector.AllowEnvironmentVariables, IG.Forms.DirectorySelector.AllowExistentDirectories, IG.Forms.DirectorySelector.AllowNonexistentDirectories, IG.Lib.UtilSystem.GetAbsolutePath(), IG.Lib.UtilSystem.GetRelativePath(), IG.Forms.DirectorySelector.UseAbsolutePaths, and IG.Forms.DirectorySelector.UseRelativePaths.
UpdateErrorState() [2/3]
virtual void IG.Forms.DirectorySelector.UpdateErrorState () inline protected virtual
Updates controls according to error state.
References IG.Forms.DirectorySelector.btnFileBrowse, IG.Forms.DirectorySelector.comboBoxFile, IG.Forms.DirectorySelector.ErrorBackground, IG.Forms.DirectorySelector.ErrorForeground, IG.Forms.DirectorySelector.IsErrorState, IG.Forms.DirectorySelector.NormalBackground, and IG.Forms.DirectorySelector.NormalForeground.
BrowseDirectory() [2/3]
void IG.Forms.DirectorySelector.BrowseDirectory () inline
Browses for the file to be hashed.
References IG.Forms.DirectorySelector.AllowExistentDirectories, IG.Forms.DirectorySelector.AllowNonexistentDirectories, IG.Forms.DirectorySelector.BrowseDirectory(), IG.Forms.DirectorySelector.DirectoryPath, IG.Forms.DirectorySelector.InitialDirectoryPath, IG.Forms.DirectorySelector.openDirectoryDialog1, IG.Forms.DirectorySelector.openFileDialog1, and IG.Forms.DirectorySelector.UseFileDialog.
ClearHistory() [2/3]
void IG.Forms.DirectorySelector.ClearHistory () inline
References IG.Forms.DirectorySelector.comboBoxFile.
OnDirectorySelected() [2/3]
virtual void IG.Forms.DirectorySelector.OnDirectorySelected () inline protected virtual
Called whenever the selected directory changes.
References IG.Forms.DirectorySelector.DirectorySelected.
OnDirectoryChanged() [2/3]
virtual void IG.Forms.DirectorySelector.OnDirectoryChanged () inline protected virtual
Called whenever the directory containing the selected file changes.
References IG.Forms.DirectorySelector.DirectoryChanged.
btnFileBrowse_Click() [2/3]
void IG.Forms.DirectorySelector.btnFileBrowse_Click (object sender, EventArgs e) inline private
Browses for the file whose hash values will be calculated.
References IG.Forms.DirectorySelector.BrowseDirectory(), and IG.Forms.DirectorySelector.DirectoryPath.
Handle_CtrlA_CtrlBackspace() [2/3]
void IG.Forms.DirectorySelector.Handle_CtrlA_CtrlBackspace (TextBox textBox, object sender, KeyEventArgs e) inline protected
Handle the Ctrl-A (select all) and Ctrl-Backspace events for the specified text box.
Parameters
textBox Text box for wich the event is handled.
txtFile_Click() [2/3]
void IG.Forms.DirectorySelector.txtFile_Click (object sender, EventArgs e) inline private
comboBoxFile_SelectedIndexChanged() [2/3]
void IG.Forms.DirectorySelector.comboBoxFile_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.comboBoxFile, and IG.Forms.DirectorySelector.DirectoryPath.
comboBoxFile_Enter() [2/3]
void IG.Forms.DirectorySelector.comboBoxFile_Enter (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.comboBoxFile, and IG.Forms.DirectorySelector.FileTextBoxInitialized.
comboBoxFile_Validated() [2/3]
void IG.Forms.DirectorySelector.comboBoxFile_Validated (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector._skipFileValidationEvent, IG.Forms.DirectorySelector.comboBoxFile, IG.Forms.DirectorySelector.DirectoryPath, IG.Forms.DirectorySelector.FileTextBoxInitialized, and IG.Forms.DirectorySelector.OriginalDirectoryPath.
comboBoxFile_KeyUp() [2/3]
void IG.Forms.DirectorySelector.comboBoxFile_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Forms.DirectorySelector.comboBoxFile, IG.Forms.DirectorySelector.comboBoxFile_Validated(), and IG.Forms.DirectorySelector.FileTextBoxInitialized.
comboBoxFile_MouseEnter() [2/3]
void IG.Forms.DirectorySelector.comboBoxFile_MouseEnter (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.comboBoxFile, and IG.Forms.DirectorySelector.FileTextBoxInitialized.
comboBoxFile_TextChanged() [2/3]
void IG.Forms.DirectorySelector.comboBoxFile_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.FileTextBoxInitialized.
FileSelector_DragEnter() [2/3]
void IG.Forms.DirectorySelector.FileSelector_DragEnter (object sender, DragEventArgs e) inline private
References IG.Forms.DirectorySelector.IsDragAndDrop.
FileSelector_DragDrop() [2/3]
void IG.Forms.DirectorySelector.FileSelector_DragDrop (object sender, DragEventArgs e) inline private
References IG.Forms.DirectorySelector.comboBoxFile, IG.Forms.DirectorySelector.comboBoxFile_Validated(), and IG.Forms.DirectorySelector.IsDragAndDrop.
menuClearHistory_Click() [2/3]
void IG.Forms.DirectorySelector.menuClearHistory_Click (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.ClearHistory().
menuAllowNonexistent_CheckedChanged() [2/3]
void IG.Forms.DirectorySelector.menuAllowNonexistent_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.AllowNonexistentDirectories, and IG.Forms.DirectorySelector.menuAllowNonexistent.
menuAllowExistent_CheckedChanged() [2/3]
void IG.Forms.DirectorySelector.menuAllowExistent_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.AllowExistentDirectories, and IG.Forms.DirectorySelector.menuAllowExistent.
menuExpandEnvironment_CheckedChanged() [2/3]
void IG.Forms.DirectorySelector.menuExpandEnvironment_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.AllowEnvironmentVariables, and IG.Forms.DirectorySelector.menuExpandEnvironment.
menuAbsolutePaths_CheckedChanged() [2/3]
void IG.Forms.DirectorySelector.menuAbsolutePaths_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.menuAbsolutePaths, and IG.Forms.DirectorySelector.UseAbsolutePaths.
menuRelativePaths_CheckedChanged() [2/3]
void IG.Forms.DirectorySelector.menuRelativePaths_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.menuRelativePaths, and IG.Forms.DirectorySelector.UseRelativePaths.
menuPathRepresentation_Click() [2/3]
void IG.Forms.DirectorySelector.menuPathRepresentation_Click (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.DirectoryPath, IG.Forms.DirectorySelector.InitialDirectoryPath, and IG.Forms.DirectorySelector.OriginalDirectoryPath.
menuInputTextBox_Click() [2/3]
void IG.Forms.DirectorySelector.menuInputTextBox_Click (object sender, EventArgs e) inline private
menuInputTextBox_Validated() [2/3]
void IG.Forms.DirectorySelector.menuInputTextBox_Validated (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.DirectoryPath, and IG.Forms.DirectorySelector.menuInputTextBox.
menuInputTextBox_KeyUp() [2/3]
void IG.Forms.DirectorySelector.menuInputTextBox_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Forms.DirectorySelector.comboBoxFile, and IG.Forms.DirectorySelector.menuInputTextBox_Validated().
menuAllowNonexistent_Click() [2/3]
void IG.Forms.DirectorySelector.menuAllowNonexistent_Click (object sender, EventArgs e) inline private
Reopens the context menu at its previous position.
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
menuAllowExistent_Click() [2/3]
void IG.Forms.DirectorySelector.menuAllowExistent_Click (object sender, EventArgs e) inline private
Reopens the context menu at its previous position.
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
menuExpandEnvironment_Click() [2/3]
void IG.Forms.DirectorySelector.menuExpandEnvironment_Click (object sender, EventArgs e) inline private
Reopens the context menu at its previous position.
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
menuUseFileDialog_Click() [2/3]
void IG.Forms.DirectorySelector.menuUseFileDialog_Click (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
menuUseFileDialog_CheckedChanged() [2/3]
void IG.Forms.DirectorySelector.menuUseFileDialog_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.menuUseFileDialog, and IG.Forms.DirectorySelector.UseFileDialog.
menuAbsolutePaths_Click() [2/3]
void IG.Forms.DirectorySelector.menuAbsolutePaths_Click (object sender, EventArgs e) inline private
Reopens the context menu at its previous position.
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
menuRelativePaths_Click() [2/3]
void IG.Forms.DirectorySelector.menuRelativePaths_Click (object sender, EventArgs e) inline private
Reopens the context menu at its previous position.
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
contextMenuMain_Opened() [2/3]
void IG.Forms.DirectorySelector.contextMenuMain_Opened (object sender, EventArgs e) inline private
Stores the position where the menu item has last opened.
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
Dispose() [2/3]
override void IG.Forms.DirectorySelector.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.DirectorySelector.components.
InitializeComponent() [2/3]
void IG.Forms.DirectorySelector.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.DirectorySelector.btnFileBrowse, IG.Forms.DirectorySelector.btnFileBrowse_Click(), IG.Forms.DirectorySelector.comboBoxFile, IG.Forms.DirectorySelector.comboBoxFile_Enter(), IG.Forms.DirectorySelector.comboBoxFile_KeyUp(), IG.Forms.DirectorySelector.comboBoxFile_MouseEnter(), IG.Forms.DirectorySelector.comboBoxFile_SelectedIndexChanged(), IG.Forms.DirectorySelector.comboBoxFile_TextChanged(), IG.Forms.DirectorySelector.comboBoxFile_Validated(), IG.Forms.DirectorySelector.components, IG.Forms.DirectorySelector.contextMenuMain, IG.Forms.DirectorySelector.FileSelector_DragDrop(), IG.Forms.DirectorySelector.FileSelector_DragEnter(), IG.Forms.DirectorySelector.lblFile, IG.Forms.DirectorySelector.menuAbsolutePaths, IG.Forms.DirectorySelector.menuAllowExistent, IG.Forms.DirectorySelector.menuAllowNonexistent, IG.Forms.DirectorySelector.menuClearHistory, IG.Forms.DirectorySelector.menuExpandEnvironment, IG.Forms.DirectorySelector.menuInputPath, IG.Forms.DirectorySelector.menuInputTextBox, IG.Forms.DirectorySelector.menuPathRepresentation, IG.Forms.DirectorySelector.menuRelativePaths, IG.Forms.DirectorySelector.menuShowPath, IG.Forms.DirectorySelector.menuUseFileDialog, IG.Forms.DirectorySelector.openDirectoryDialog1, and IG.Forms.DirectorySelector.openFileDialog1.
GetFilePathRepresentation() [3/3]
string IG.Forms.DirectorySelector.GetFilePathRepresentation (string directoryPath) inline
Returns the presentational form of the specified directory path, with eventual environment variables expanded and with conversion to the appropriate form (relative or absolute).
Parameters
directoryPath Directory path whose presentational form is returned.
Presentational form depends on the following properties: <pra> - AllowEnvironmentVariables: If true then environment variable references are expanded.
In Unix-like systems, enviironment variables are referenced as $varName, and on Windows with varName%.
</pra>
- UseAbsolutePaths: If true then paths are presented as absolute paths (independend of the current working directory).
- UseRelativePaths: If true then paths are represented relative to the current working directory.
References IG.Forms.DirectorySelector.AllowEnvironmentVariables, IG.Forms.DirectorySelector.AllowExistentDirectories, IG.Forms.DirectorySelector.AllowNonexistentDirectories, IG.Lib.UtilSystem.GetAbsolutePath(), IG.Lib.UtilSystem.GetRelativePath(), IG.Forms.DirectorySelector.UseAbsolutePaths, and IG.Forms.DirectorySelector.UseRelativePaths.
UpdateErrorState() [3/3]
virtual void IG.Forms.DirectorySelector.UpdateErrorState () inline protected virtual
Updates controls according to error state.
References IG.Forms.DirectorySelector.btnFileBrowse, IG.Forms.DirectorySelector.comboBoxFile, IG.Forms.DirectorySelector.ErrorBackground, IG.Forms.DirectorySelector.ErrorForeground, IG.Forms.DirectorySelector.IsErrorState, IG.Forms.DirectorySelector.NormalBackground, and IG.Forms.DirectorySelector.NormalForeground.
BrowseDirectory() [3/3]
void IG.Forms.DirectorySelector.BrowseDirectory () inline
Browses for the file to be hashed.
References IG.Forms.DirectorySelector.AllowExistentDirectories, IG.Forms.DirectorySelector.AllowNonexistentDirectories, IG.Forms.DirectorySelector.BrowseDirectory(), IG.Forms.DirectorySelector.DirectoryPath, IG.Forms.DirectorySelector.InitialDirectoryPath, IG.Forms.DirectorySelector.openDirectoryDialog1, IG.Forms.DirectorySelector.openFileDialog1, and IG.Forms.DirectorySelector.UseFileDialog.
ClearHistory() [3/3]
void IG.Forms.DirectorySelector.ClearHistory () inline
References IG.Forms.DirectorySelector.comboBoxFile.
OnDirectorySelected() [3/3]
virtual void IG.Forms.DirectorySelector.OnDirectorySelected () inline protected virtual
Called whenever the selected directory changes.
References IG.Forms.DirectorySelector.DirectorySelected.
OnDirectoryChanged() [3/3]
virtual void IG.Forms.DirectorySelector.OnDirectoryChanged () inline protected virtual
Called whenever the directory containing the selected file changes.
References IG.Forms.DirectorySelector.DirectoryChanged.
btnFileBrowse_Click() [3/3]
void IG.Forms.DirectorySelector.btnFileBrowse_Click (object sender, EventArgs e) inline private
Browses for the file whose hash values will be calculated.
References IG.Forms.DirectorySelector.BrowseDirectory(), and IG.Forms.DirectorySelector.DirectoryPath.
Handle_CtrlA_CtrlBackspace() [3/3]
void IG.Forms.DirectorySelector.Handle_CtrlA_CtrlBackspace (TextBox textBox, object sender, KeyEventArgs e) inline protected
Handle the Ctrl-A (select all) and Ctrl-Backspace events for the specified text box.
Parameters
textBox Text box for wich the event is handled.
txtFile_Click() [3/3]
void IG.Forms.DirectorySelector.txtFile_Click (object sender, EventArgs e) inline private
comboBoxFile_SelectedIndexChanged() [3/3]
void IG.Forms.DirectorySelector.comboBoxFile_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.comboBoxFile, and IG.Forms.DirectorySelector.DirectoryPath.
comboBoxFile_Enter() [3/3]
void IG.Forms.DirectorySelector.comboBoxFile_Enter (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.comboBoxFile, and IG.Forms.DirectorySelector.FileTextBoxInitialized.
comboBoxFile_Validated() [3/3]
void IG.Forms.DirectorySelector.comboBoxFile_Validated (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector._skipFileValidationEvent, IG.Forms.DirectorySelector.comboBoxFile, IG.Forms.DirectorySelector.DirectoryPath, IG.Forms.DirectorySelector.FileTextBoxInitialized, and IG.Forms.DirectorySelector.OriginalDirectoryPath.
comboBoxFile_KeyUp() [3/3]
void IG.Forms.DirectorySelector.comboBoxFile_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Forms.DirectorySelector.comboBoxFile, IG.Forms.DirectorySelector.comboBoxFile_Validated(), and IG.Forms.DirectorySelector.FileTextBoxInitialized.
comboBoxFile_MouseEnter() [3/3]
void IG.Forms.DirectorySelector.comboBoxFile_MouseEnter (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.comboBoxFile, and IG.Forms.DirectorySelector.FileTextBoxInitialized.
comboBoxFile_TextChanged() [3/3]
void IG.Forms.DirectorySelector.comboBoxFile_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.FileTextBoxInitialized.
FileSelector_DragEnter() [3/3]
void IG.Forms.DirectorySelector.FileSelector_DragEnter (object sender, DragEventArgs e) inline private
References IG.Forms.DirectorySelector.IsDragAndDrop.
FileSelector_DragDrop() [3/3]
void IG.Forms.DirectorySelector.FileSelector_DragDrop (object sender, DragEventArgs e) inline private
References IG.Forms.DirectorySelector.comboBoxFile, IG.Forms.DirectorySelector.comboBoxFile_Validated(), and IG.Forms.DirectorySelector.IsDragAndDrop.
menuClearHistory_Click() [3/3]
void IG.Forms.DirectorySelector.menuClearHistory_Click (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.ClearHistory().
menuAllowNonexistent_CheckedChanged() [3/3]
void IG.Forms.DirectorySelector.menuAllowNonexistent_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.AllowNonexistentDirectories, and IG.Forms.DirectorySelector.menuAllowNonexistent.
menuAllowExistent_CheckedChanged() [3/3]
void IG.Forms.DirectorySelector.menuAllowExistent_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.AllowExistentDirectories, and IG.Forms.DirectorySelector.menuAllowExistent.
menuExpandEnvironment_CheckedChanged() [3/3]
void IG.Forms.DirectorySelector.menuExpandEnvironment_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.AllowEnvironmentVariables, and IG.Forms.DirectorySelector.menuExpandEnvironment.
menuAbsolutePaths_CheckedChanged() [3/3]
void IG.Forms.DirectorySelector.menuAbsolutePaths_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.menuAbsolutePaths, and IG.Forms.DirectorySelector.UseAbsolutePaths.
menuRelativePaths_CheckedChanged() [3/3]
void IG.Forms.DirectorySelector.menuRelativePaths_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.menuRelativePaths, and IG.Forms.DirectorySelector.UseRelativePaths.
menuPathRepresentation_Click() [3/3]
void IG.Forms.DirectorySelector.menuPathRepresentation_Click (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.DirectoryPath, IG.Forms.DirectorySelector.InitialDirectoryPath, and IG.Forms.DirectorySelector.OriginalDirectoryPath.
menuInputTextBox_Click() [3/3]
void IG.Forms.DirectorySelector.menuInputTextBox_Click (object sender, EventArgs e) inline private
menuInputTextBox_Validated() [3/3]
void IG.Forms.DirectorySelector.menuInputTextBox_Validated (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.DirectoryPath, and IG.Forms.DirectorySelector.menuInputTextBox.
menuInputTextBox_KeyUp() [3/3]
void IG.Forms.DirectorySelector.menuInputTextBox_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Forms.DirectorySelector.comboBoxFile, and IG.Forms.DirectorySelector.menuInputTextBox_Validated().
menuAllowNonexistent_Click() [3/3]
void IG.Forms.DirectorySelector.menuAllowNonexistent_Click (object sender, EventArgs e) inline private
Reopens the context menu at its previous position.
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
menuAllowExistent_Click() [3/3]
void IG.Forms.DirectorySelector.menuAllowExistent_Click (object sender, EventArgs e) inline private
Reopens the context menu at its previous position.
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
menuExpandEnvironment_Click() [3/3]
void IG.Forms.DirectorySelector.menuExpandEnvironment_Click (object sender, EventArgs e) inline private
Reopens the context menu at its previous position.
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
menuUseFileDialog_Click() [3/3]
void IG.Forms.DirectorySelector.menuUseFileDialog_Click (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
menuUseFileDialog_CheckedChanged() [3/3]
void IG.Forms.DirectorySelector.menuUseFileDialog_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.DirectorySelector.menuUseFileDialog, and IG.Forms.DirectorySelector.UseFileDialog.
menuAbsolutePaths_Click() [3/3]
void IG.Forms.DirectorySelector.menuAbsolutePaths_Click (object sender, EventArgs e) inline private
Reopens the context menu at its previous position.
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
menuRelativePaths_Click() [3/3]
void IG.Forms.DirectorySelector.menuRelativePaths_Click (object sender, EventArgs e) inline private
Reopens the context menu at its previous position.
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
contextMenuMain_Opened() [3/3]
void IG.Forms.DirectorySelector.contextMenuMain_Opened (object sender, EventArgs e) inline private
Stores the position where the menu item has last opened.
References IG.Forms.DirectorySelector._lasContectMenuPosition, and IG.Forms.DirectorySelector.contextMenuMain.
Dispose() [3/3]
override void IG.Forms.DirectorySelector.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.DirectorySelector.components.
InitializeComponent() [3/3]
void IG.Forms.DirectorySelector.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.DirectorySelector.btnFileBrowse, IG.Forms.DirectorySelector.btnFileBrowse_Click(), IG.Forms.DirectorySelector.comboBoxFile, IG.Forms.DirectorySelector.comboBoxFile_Enter(), IG.Forms.DirectorySelector.comboBoxFile_KeyUp(), IG.Forms.DirectorySelector.comboBoxFile_MouseEnter(), IG.Forms.DirectorySelector.comboBoxFile_SelectedIndexChanged(), IG.Forms.DirectorySelector.comboBoxFile_TextChanged(), IG.Forms.DirectorySelector.comboBoxFile_Validated(), IG.Forms.DirectorySelector.components, IG.Forms.DirectorySelector.contextMenuMain, IG.Forms.DirectorySelector.FileSelector_DragDrop(), IG.Forms.DirectorySelector.FileSelector_DragEnter(), IG.Forms.DirectorySelector.lblFile, IG.Forms.DirectorySelector.menuAbsolutePaths, IG.Forms.DirectorySelector.menuAllowExistent, IG.Forms.DirectorySelector.menuAllowNonexistent, IG.Forms.DirectorySelector.menuClearHistory, IG.Forms.DirectorySelector.menuExpandEnvironment, IG.Forms.DirectorySelector.menuInputPath, IG.Forms.DirectorySelector.menuInputTextBox, IG.Forms.DirectorySelector.menuPathRepresentation, IG.Forms.DirectorySelector.menuRelativePaths, IG.Forms.DirectorySelector.menuShowPath, IG.Forms.DirectorySelector.menuUseFileDialog, IG.Forms.DirectorySelector.openDirectoryDialog1, and IG.Forms.DirectorySelector.openFileDialog1.
Member Data Documentation
_fileTextBoxInitialized
bool IG.Forms.DirectorySelector._fileTextBoxInitialized = false private
_containingDirectoryPath
string IG.Forms.DirectorySelector._containingDirectoryPath protected
_allowEnvironmentVariables
bool IG.Forms.DirectorySelector._allowEnvironmentVariables = true private
_allowExistentDirectories
bool IG.Forms.DirectorySelector._allowExistentDirectories = true private
_allowNonexistentDirectories
bool IG.Forms.DirectorySelector._allowNonexistentDirectories = true private
_useRelativePaths
bool IG.Forms.DirectorySelector._useRelativePaths = false private
_useAbsolutePaths
bool IG.Forms.DirectorySelector._useAbsolutePaths = false private
_useFileDialog
bool IG.Forms.DirectorySelector._useFileDialog = true private
_directoryPath
string IG.Forms.DirectorySelector._directoryPath protected
_errorBackground
Color IG.Forms.DirectorySelector._errorBackground = Color.Orange private
_errorForeground
Color IG.Forms.DirectorySelector._errorForeground = Color.Red private
_normalBackground
Color IG.Forms.DirectorySelector._normalBackground = Color.White private
_normalforeground
Color IG.Forms.DirectorySelector._normalforeground = Color.Black private
_isBrowsable
bool IG.Forms.DirectorySelector._isBrowsable = true private
_isDragAndDrop
bool IG.Forms.DirectorySelector._isDragAndDrop = true private
_skipFileValidationEvent
bool IG.Forms.DirectorySelector._skipFileValidationEvent = false private
Referenced by IG.Forms.DirectorySelector.comboBoxFile_Validated().
_lasContectMenuPosition
Point IG.Forms.DirectorySelector._lasContectMenuPosition = new Point(0, 0) private
Referenced by IG.Forms.DirectorySelector.contextMenuMain_Opened(), IG.Forms.DirectorySelector.menuAbsolutePaths_Click(), IG.Forms.DirectorySelector.menuAllowExistent_Click(), IG.Forms.DirectorySelector.menuAllowNonexistent_Click(), IG.Forms.DirectorySelector.menuExpandEnvironment_Click(), IG.Forms.DirectorySelector.menuRelativePaths_Click(), and IG.Forms.DirectorySelector.menuUseFileDialog_Click().
components
System ComponentModel IContainer IG.Forms.DirectorySelector.components = null private
Required designer variable.
Referenced by IG.Forms.DirectorySelector.Dispose(), and IG.Forms.DirectorySelector.InitializeComponent().
btnFileBrowse
System Windows Forms Button IG.Forms.DirectorySelector.btnFileBrowse private
Referenced by IG.Forms.DirectorySelector.InitializeComponent(), and IG.Forms.DirectorySelector.UpdateErrorState().
lblFile
System Windows Forms Label IG.Forms.DirectorySelector.lblFile private
Referenced by IG.Forms.DirectorySelector.InitializeComponent().
openDirectoryDialog1
System Windows Forms FolderBrowserDialog IG.Forms.DirectorySelector.openDirectoryDialog1 private
Referenced by IG.Forms.DirectorySelector.BrowseDirectory(), and IG.Forms.DirectorySelector.InitializeComponent().
comboBoxFile
System Windows Forms ComboBox IG.Forms.DirectorySelector.comboBoxFile private
Referenced by IG.Forms.DirectorySelector.ClearHistory(), IG.Forms.DirectorySelector.comboBoxFile_Enter(), IG.Forms.DirectorySelector.comboBoxFile_KeyUp(), IG.Forms.DirectorySelector.comboBoxFile_MouseEnter(), IG.Forms.DirectorySelector.comboBoxFile_SelectedIndexChanged(), IG.Forms.DirectorySelector.comboBoxFile_Validated(), IG.Forms.DirectorySelector.DirectorySelector(), IG.Forms.DirectorySelector.FileSelector_DragDrop(), IG.Forms.DirectorySelector.InitializeComponent(), IG.Forms.DirectorySelector.menuInputTextBox_KeyUp(), and IG.Forms.DirectorySelector.UpdateErrorState().
contextMenuMain
System Windows Forms ContextMenuStrip IG.Forms.DirectorySelector.contextMenuMain private
Referenced by IG.Forms.DirectorySelector.contextMenuMain_Opened(), IG.Forms.DirectorySelector.InitializeComponent(), IG.Forms.DirectorySelector.menuAbsolutePaths_Click(), IG.Forms.DirectorySelector.menuAllowExistent_Click(), IG.Forms.DirectorySelector.menuAllowNonexistent_Click(), IG.Forms.DirectorySelector.menuExpandEnvironment_Click(), IG.Forms.DirectorySelector.menuRelativePaths_Click(), and IG.Forms.DirectorySelector.menuUseFileDialog_Click().
menuClearHistory
System Windows Forms ToolStripMenuItem IG.Forms.DirectorySelector.menuClearHistory private
Referenced by IG.Forms.DirectorySelector.InitializeComponent().
menuAllowNonexistent
System Windows Forms ToolStripMenuItem IG.Forms.DirectorySelector.menuAllowNonexistent private
Referenced by IG.Forms.DirectorySelector.DirectorySelector(), IG.Forms.DirectorySelector.InitializeComponent(), and IG.Forms.DirectorySelector.menuAllowNonexistent_CheckedChanged().
menuAllowExistent
System Windows Forms ToolStripMenuItem IG.Forms.DirectorySelector.menuAllowExistent private
Referenced by IG.Forms.DirectorySelector.DirectorySelector(), IG.Forms.DirectorySelector.InitializeComponent(), and IG.Forms.DirectorySelector.menuAllowExistent_CheckedChanged().
menuExpandEnvironment
System Windows Forms ToolStripMenuItem IG.Forms.DirectorySelector.menuExpandEnvironment private
Referenced by IG.Forms.DirectorySelector.DirectorySelector(), IG.Forms.DirectorySelector.InitializeComponent(), and IG.Forms.DirectorySelector.menuExpandEnvironment_CheckedChanged().
menuAbsolutePaths
System Windows Forms ToolStripMenuItem IG.Forms.DirectorySelector.menuAbsolutePaths private
Referenced by IG.Forms.DirectorySelector.DirectorySelector(), IG.Forms.DirectorySelector.InitializeComponent(), and IG.Forms.DirectorySelector.menuAbsolutePaths_CheckedChanged().
menuRelativePaths
System Windows Forms ToolStripMenuItem IG.Forms.DirectorySelector.menuRelativePaths private
Referenced by IG.Forms.DirectorySelector.DirectorySelector(), IG.Forms.DirectorySelector.InitializeComponent(), and IG.Forms.DirectorySelector.menuRelativePaths_CheckedChanged().
menuShowPath
System Windows Forms ToolStripMenuItem IG.Forms.DirectorySelector.menuShowPath private
Referenced by IG.Forms.DirectorySelector.InitializeComponent().
menuPathRepresentation
System Windows Forms ToolStripMenuItem IG.Forms.DirectorySelector.menuPathRepresentation private
Referenced by IG.Forms.DirectorySelector.DirectorySelector(), and IG.Forms.DirectorySelector.InitializeComponent().
menuInputPath
System Windows Forms ToolStripMenuItem IG.Forms.DirectorySelector.menuInputPath private
Referenced by IG.Forms.DirectorySelector.InitializeComponent().
menuInputTextBox
System Windows Forms ToolStripTextBox IG.Forms.DirectorySelector.menuInputTextBox private
Referenced by IG.Forms.DirectorySelector.DirectorySelector(), IG.Forms.DirectorySelector.InitializeComponent(), and IG.Forms.DirectorySelector.menuInputTextBox_Validated().
menuUseFileDialog
System Windows Forms ToolStripMenuItem IG.Forms.DirectorySelector.menuUseFileDialog private
Referenced by IG.Forms.DirectorySelector.DirectorySelector(), IG.Forms.DirectorySelector.InitializeComponent(), and IG.Forms.DirectorySelector.menuUseFileDialog_CheckedChanged().
openFileDialog1
System Windows Forms OpenFileDialog IG.Forms.DirectorySelector.openFileDialog1 private
Referenced by IG.Forms.DirectorySelector.BrowseDirectory(), and IG.Forms.DirectorySelector.InitializeComponent().
Property Documentation
FileTextBoxInitialized
bool IG.Forms.DirectorySelector.FileTextBoxInitialized get set protected
Referenced by IG.Forms.DirectorySelector.comboBoxFile_Enter(), IG.Forms.DirectorySelector.comboBoxFile_KeyUp(), IG.Forms.DirectorySelector.comboBoxFile_MouseEnter(), IG.Forms.DirectorySelector.comboBoxFile_TextChanged(), and IG.Forms.DirectorySelector.comboBoxFile_Validated().
InitialDirectoryPath
string IG.Forms.DirectorySelector.InitialDirectoryPath get protected set
Directory where files are currently selected.
Referenced by IG.Forms.DirectorySelector.BrowseDirectory(), and IG.Forms.DirectorySelector.menuPathRepresentation_Click().
AllowEnvironmentVariables
bool IG.Forms.DirectorySelector.AllowEnvironmentVariables get set
If true then environment variables can be used in paths.
Referenced by IG.Forms.DirectorySelector.DirectorySelector(), IG.Forms.DirectorySelector.GetFilePathRepresentation(), and IG.Forms.DirectorySelector.menuExpandEnvironment_CheckedChanged().
AllowExistentDirectories
bool IG.Forms.DirectorySelector.AllowExistentDirectories get set
If true then existent files are allowed to be selected.
It might be impossible to insert such a path through the file dialog (launched by the "Browse" button), but one can insert it in the text box.
Referenced by IG.Forms.DirectorySelector.BrowseDirectory(), IG.Forms.DirectorySelector.DirectorySelector(), IG.Forms.DirectorySelector.GetFilePathRepresentation(), and IG.Forms.DirectorySelector.menuAllowExistent_CheckedChanged().
AllowNonexistentDirectories
bool IG.Forms.DirectorySelector.AllowNonexistentDirectories get set
If true then non-existend files are allowed to be selected.
It might be impossible to insert such a path through the file dialog (launched by the "Browse" button), but one can insert it in the text box.
Referenced by IG.Forms.DirectorySelector.BrowseDirectory(), IG.Forms.DirectorySelector.DirectorySelector(), IG.Forms.DirectorySelector.GetFilePathRepresentation(), and IG.Forms.DirectorySelector.menuAllowNonexistent_CheckedChanged().
UseRelativePaths
bool IG.Forms.DirectorySelector.UseRelativePaths get set
If true then relative paths are used in representation of the selseted file path.
This property is mutually exclusive with UseAbsolutePaths (only one can be true, but both can be false).
Referenced by IG.Forms.DirectorySelector.DirectorySelector(), IG.Forms.DirectorySelector.GetFilePathRepresentation(), and IG.Forms.DirectorySelector.menuRelativePaths_CheckedChanged().
UseAbsolutePaths
bool IG.Forms.DirectorySelector.UseAbsolutePaths get set
If true then absolute paths are used in representation of the selseted file path.
This property is mutually exclusive with UseRelativePaths (only one can be true, but both can be false).
Referenced by IG.Forms.DirectorySelector.DirectorySelector(), IG.Forms.DirectorySelector.GetFilePathRepresentation(), and IG.Forms.DirectorySelector.menuAbsolutePaths_CheckedChanged().
UseFileDialog
bool IG.Forms.DirectorySelector.UseFileDialog get set private
If true then an OpenFileDialog is used to browse for directory, rather than Directorydialog bool UseFileDialog
Referenced by IG.Forms.DirectorySelector.BrowseDirectory(), IG.Forms.DirectorySelector.DirectorySelector(), and IG.Forms.DirectorySelector.menuUseFileDialog_CheckedChanged().
DirectoryPath
string IG.Forms.DirectorySelector.DirectoryPath get set
Path to the file that is currently selected.
Getter returns the output representation of the path, with eventual environment variables expansion (dependent on AllowEnvironmentVariables properties) and in appropriate form (relative or absolute path, according to UseRelativePaths and UseAbsolutePaths properties).
Original path ca be retrieved by the OriginalDirectoryPath property.
Referenced by IG.Forms.DirectorySelector.BrowseDirectory(), IG.Forms.DirectorySelector.btnFileBrowse_Click(), IG.Forms.DirectorySelector.comboBoxFile_SelectedIndexChanged(), IG.Forms.DirectorySelector.comboBoxFile_Validated(), IG.Forms.DirectorySelector.DirectorySelector(), IG.Forms.DirectorySelector.menuInputTextBox_Validated(), and IG.Forms.DirectorySelector.menuPathRepresentation_Click().
OriginalDirectoryPath
string IG.Forms.DirectorySelector.OriginalDirectoryPath get set
Gets the original file path representation (as set by user), without any post processing (like environment variables expansion or conversion to relative or absolute path).
Setter just calls the setter of the DirectoryPath property.
Referenced by IG.Forms.DirectorySelector.comboBoxFile_Validated(), IG.Forms.DirectorySelector.DirectorySelector(), and IG.Forms.DirectorySelector.menuPathRepresentation_Click().
IsErrorState
bool IG.Forms.DirectorySelector.IsErrorState get
Returns true if the current selection is invalid, false if it is valid.
In the case of invalid selection, OriginalDirectoryPath may return a non-null path but DirectoryPath does not.
Referenced by IG.Forms.DirectorySelector.UpdateErrorState().
ErrorBackground
Color IG.Forms.DirectorySelector.ErrorBackground get set
Background color of selection's text in case of error.
Referenced by IG.Forms.DirectorySelector.UpdateErrorState().
ErrorForeground
Color IG.Forms.DirectorySelector.ErrorForeground get set
Foreground color of button in case of error.
Referenced by IG.Forms.DirectorySelector.UpdateErrorState().
NormalBackground
Color IG.Forms.DirectorySelector.NormalBackground get set
Background color of selection's text in case of NO error.
Referenced by IG.Forms.DirectorySelector.DirectorySelector(), and IG.Forms.DirectorySelector.UpdateErrorState().
NormalForeground
Color IG.Forms.DirectorySelector.NormalForeground get set
Foreground color of button in case of NO error.
Referenced by IG.Forms.DirectorySelector.UpdateErrorState().
IsBrowsable
bool IG.Forms.DirectorySelector.IsBrowsable get set
Gets or sets the flag specifying whether one can browse for the file to be opened (e.g. by using the file selection dialog).
If the viewer does not at all have browser capability then setting to true should NOT throw an exception (therefore, the user should verify by getter if setting actually worked).
Setter can be used to disable browsing (e.g. for security, or when used as embedded control and browsing would be disturbing).
IsDragAndDrop
bool IG.Forms.DirectorySelector.IsDragAndDrop get set
Whether the selector provides drag & drop capability.
Setter can be used to disable drag & drop (e.g. for security, or when used with an embedded control and drag & drop would be disturbing).
Referenced by IG.Forms.DirectorySelector.FileSelector_DragDrop(), and IG.Forms.DirectorySelector.FileSelector_DragEnter().
Event Documentation
DirectorySelected
EventHandler IG.Forms.DirectorySelector.DirectorySelected
Event that is fired whenever the selected directory changes.
Referenced by IG.Forms.DirectorySelector.OnDirectorySelected().
DirectoryChanged
EventHandler IG.Forms.DirectorySelector.DirectoryChanged
Event that is fired whenever directory containing the selected file changes.
Referenced by IG.Forms.DirectorySelector.OnDirectoryChanged().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/BasicControls/DirectorySelector.cs
iglib/igforms/Utilities/BasicControls/DirectorySelector.Designer.cs