Doc: IGLib EXTENDED: PoseEstimation.MatrixControl Class Reference
PoseEstimation.MatrixControl Class Reference
Public Member Functions
MatrixControl ()
void SetMatrix (Matrix4x4 matrix)
MatrixControl ()
void SetMatrix (Matrix4x4 matrix)
void Clear ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
string Title [get, set]
Private Member Functions
void MatrixControl_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MatrixControl_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Static Private Member Functions
static string FormatFloat (float floatValue)
static string FormatFloat (float floatValue)
Private Attributes
Dictionary< string, TextBox > textBoxes = new Dictionary<string, TextBox>()
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.GroupBox groupBox
System.Windows.Forms.TextBox i0_j0_Box
System.Windows.Forms.TextBox i3_j3_Box
System.Windows.Forms.TextBox i3_j2_Box
System.Windows.Forms.TextBox i3_j1_Box
System.Windows.Forms.TextBox i3_j0_Box
System.Windows.Forms.TextBox i2_j3_Box
System.Windows.Forms.TextBox i2_j2_Box
System.Windows.Forms.TextBox i2_j1_Box
System.Windows.Forms.TextBox i2_j0_Box
System.Windows.Forms.TextBox i1_j3_Box
System.Windows.Forms.TextBox i1_j2_Box
System.Windows.Forms.TextBox i1_j1_Box
System.Windows.Forms.TextBox i1_j0_Box
System.Windows.Forms.TextBox i0_j3_Box
System.Windows.Forms.TextBox i0_j2_Box
System.Windows.Forms.TextBox i0_j1_Box
Constructor & Destructor Documentation
MatrixControl() [1/2]
PoseEstimation.MatrixControl.MatrixControl () inline
References PoseEstimation.MatrixControl.InitializeComponent().
MatrixControl() [2/2]
PoseEstimation.MatrixControl.MatrixControl () inline
References PoseEstimation.MatrixControl.InitializeComponent().
Member Function Documentation
SetMatrix() [1/2]
void PoseEstimation.MatrixControl.SetMatrix (Matrix4x4 matrix) inline
References PoseEstimation.MatrixControl.FormatFloat(), PoseEstimation.MatrixControl.textBoxes, and AForge.Math.Matrix4x4.ToArray().
Referenced by PoseEstimation.MainForm.EstimatePose(), PoseEstimation.MainForm.UpdateEstimationInformation(), PoseEstimation.MainForm.UpdateTransformationMatrix(), and PoseEstimation.MainForm.UpdateViewMatrix().
FormatFloat() [1/2]
static string PoseEstimation.MatrixControl.FormatFloat (float floatValue) inline static private
Referenced by PoseEstimation.MatrixControl.SetMatrix().
MatrixControl_Load() [1/2]
void PoseEstimation.MatrixControl.MatrixControl_Load (object sender, EventArgs e) inline private
References PoseEstimation.MatrixControl.groupBox, and PoseEstimation.MatrixControl.textBoxes.
Referenced by PoseEstimation.MatrixControl.InitializeComponent().
Dispose() [1/2]
override void PoseEstimation.MatrixControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References PoseEstimation.MatrixControl.components.
InitializeComponent() [1/2]
void PoseEstimation.MatrixControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References PoseEstimation.MatrixControl.groupBox, PoseEstimation.MatrixControl.i0_j0_Box, PoseEstimation.MatrixControl.i0_j1_Box, PoseEstimation.MatrixControl.i0_j2_Box, PoseEstimation.MatrixControl.i0_j3_Box, PoseEstimation.MatrixControl.i1_j0_Box, PoseEstimation.MatrixControl.i1_j1_Box, PoseEstimation.MatrixControl.i1_j2_Box, PoseEstimation.MatrixControl.i1_j3_Box, PoseEstimation.MatrixControl.i2_j0_Box, PoseEstimation.MatrixControl.i2_j1_Box, PoseEstimation.MatrixControl.i2_j2_Box, PoseEstimation.MatrixControl.i2_j3_Box, PoseEstimation.MatrixControl.i3_j0_Box, PoseEstimation.MatrixControl.i3_j1_Box, PoseEstimation.MatrixControl.i3_j2_Box, PoseEstimation.MatrixControl.i3_j3_Box, and PoseEstimation.MatrixControl.MatrixControl_Load().
Referenced by PoseEstimation.MatrixControl.MatrixControl().
SetMatrix() [2/2]
void PoseEstimation.MatrixControl.SetMatrix (Matrix4x4 matrix) inline
References PoseEstimation.MatrixControl.FormatFloat(), PoseEstimation.MatrixControl.textBoxes, and AForge.Math.Matrix4x4.ToArray().
Clear()
void PoseEstimation.MatrixControl.Clear () inline
References PoseEstimation.MatrixControl.textBoxes.
Referenced by PoseEstimation.MainForm.ClearEstimation().
FormatFloat() [2/2]
static string PoseEstimation.MatrixControl.FormatFloat (float floatValue) inline static private
MatrixControl_Load() [2/2]
void PoseEstimation.MatrixControl.MatrixControl_Load (object sender, EventArgs e) inline private
References PoseEstimation.MatrixControl.groupBox, and PoseEstimation.MatrixControl.textBoxes.
Dispose() [2/2]
override void PoseEstimation.MatrixControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References PoseEstimation.MatrixControl.components.
InitializeComponent() [2/2]
void PoseEstimation.MatrixControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References PoseEstimation.MatrixControl.groupBox, PoseEstimation.MatrixControl.i0_j0_Box, PoseEstimation.MatrixControl.i0_j1_Box, PoseEstimation.MatrixControl.i0_j2_Box, PoseEstimation.MatrixControl.i0_j3_Box, PoseEstimation.MatrixControl.i1_j0_Box, PoseEstimation.MatrixControl.i1_j1_Box, PoseEstimation.MatrixControl.i1_j2_Box, PoseEstimation.MatrixControl.i1_j3_Box, PoseEstimation.MatrixControl.i2_j0_Box, PoseEstimation.MatrixControl.i2_j1_Box, PoseEstimation.MatrixControl.i2_j2_Box, PoseEstimation.MatrixControl.i2_j3_Box, PoseEstimation.MatrixControl.i3_j0_Box, PoseEstimation.MatrixControl.i3_j1_Box, PoseEstimation.MatrixControl.i3_j2_Box, PoseEstimation.MatrixControl.i3_j3_Box, and PoseEstimation.MatrixControl.MatrixControl_Load().
Member Data Documentation
textBoxes
Dictionary< string, TextBox > PoseEstimation.MatrixControl.textBoxes = new Dictionary<string, TextBox>() private
Referenced by PoseEstimation.MatrixControl.Clear(), PoseEstimation.MatrixControl.MatrixControl_Load(), and PoseEstimation.MatrixControl.SetMatrix().
components
System ComponentModel IContainer PoseEstimation.MatrixControl.components = null private
Required designer variable.
Referenced by PoseEstimation.MatrixControl.Dispose().
groupBox
System Windows Forms GroupBox PoseEstimation.MatrixControl.groupBox private
Referenced by PoseEstimation.MatrixControl.InitializeComponent(), and PoseEstimation.MatrixControl.MatrixControl_Load().
i0_j0_Box
System Windows Forms TextBox PoseEstimation.MatrixControl.i0_j0_Box private
Referenced by PoseEstimation.MatrixControl.InitializeComponent().
i3_j3_Box
System Windows Forms TextBox PoseEstimation.MatrixControl.i3_j3_Box private
Referenced by PoseEstimation.MatrixControl.InitializeComponent().
i3_j2_Box
System Windows Forms TextBox PoseEstimation.MatrixControl.i3_j2_Box private
Referenced by PoseEstimation.MatrixControl.InitializeComponent().
i3_j1_Box
System Windows Forms TextBox PoseEstimation.MatrixControl.i3_j1_Box private
Referenced by PoseEstimation.MatrixControl.InitializeComponent().
i3_j0_Box
System Windows Forms TextBox PoseEstimation.MatrixControl.i3_j0_Box private
Referenced by PoseEstimation.MatrixControl.InitializeComponent().
i2_j3_Box
System Windows Forms TextBox PoseEstimation.MatrixControl.i2_j3_Box private
Referenced by PoseEstimation.MatrixControl.InitializeComponent().
i2_j2_Box
System Windows Forms TextBox PoseEstimation.MatrixControl.i2_j2_Box private
Referenced by PoseEstimation.MatrixControl.InitializeComponent().
i2_j1_Box
System Windows Forms TextBox PoseEstimation.MatrixControl.i2_j1_Box private
Referenced by PoseEstimation.MatrixControl.InitializeComponent().
i2_j0_Box
System Windows Forms TextBox PoseEstimation.MatrixControl.i2_j0_Box private
Referenced by PoseEstimation.MatrixControl.InitializeComponent().
i1_j3_Box
System Windows Forms TextBox PoseEstimation.MatrixControl.i1_j3_Box private
Referenced by PoseEstimation.MatrixControl.InitializeComponent().
i1_j2_Box
System Windows Forms TextBox PoseEstimation.MatrixControl.i1_j2_Box private
Referenced by PoseEstimation.MatrixControl.InitializeComponent().
i1_j1_Box
System Windows Forms TextBox PoseEstimation.MatrixControl.i1_j1_Box private
Referenced by PoseEstimation.MatrixControl.InitializeComponent().
i1_j0_Box
System Windows Forms TextBox PoseEstimation.MatrixControl.i1_j0_Box private
Referenced by PoseEstimation.MatrixControl.InitializeComponent().
i0_j3_Box
System Windows Forms TextBox PoseEstimation.MatrixControl.i0_j3_Box private
Referenced by PoseEstimation.MatrixControl.InitializeComponent().
i0_j2_Box
System Windows Forms TextBox PoseEstimation.MatrixControl.i0_j2_Box private
Referenced by PoseEstimation.MatrixControl.InitializeComponent().
i0_j1_Box
System Windows Forms TextBox PoseEstimation.MatrixControl.i0_j1_Box private
Referenced by PoseEstimation.MatrixControl.InitializeComponent().
Property Documentation
Title
string PoseEstimation.MatrixControl.Title get set
Referenced by PoseEstimation.MainForm.InitializeComponent().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Math/Pose Estimation/MatrixControl.cs
shelldev/lib_ann/aforge.net/Samples/Math/Pose Estimation/MatrixControl.Designer.cs