Doc: IGLib EXTENDED: alglib.testfblsunit Class Reference
alglib.testfblsunit Class Reference
Static Public Member Functions
static bool testfbls (bool silent)
static bool testfbls (bool silent)
static bool _pexec_testfbls (bool silent)
Member Function Documentation
testfbls() [1/2]
static bool alglib.testfblsunit.testfbls (bool silent) inline static
References alglib.fbls.fblscgcreate(), alglib.fbls.fblscgiteration(), alglib.fbls.fblssolvecgx(), alglib.fbls.fblssolvels(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), and alglib.ablas.rmatrixmv().
Referenced by alglib.testfblsunit._pexec_testfbls(), and _Test.Main().
testfbls() [2/2]
static bool alglib.testfblsunit.testfbls (bool silent) inline static
References alglib.fbls.fblscgcreate(), alglib.fbls.fblscgiteration(), alglib.fbls.fblssolvecgx(), alglib.fbls.fblssolvels(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), and alglib.ablas.rmatrixmv().
_pexec_testfbls()
static bool alglib.testfblsunit._pexec_testfbls (bool silent) inline static
References alglib.testfblsunit.testfbls().
Referenced by _Test.Main().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs