Doc: IGLib EXTENDED: AForge.Imaging.Filters.BilateralSmoothing Class Reference
AForge.Imaging.Filters.BilateralSmoothing Class Reference
Bilateral filter implementation - edge preserving smoothing and noise reduction that uses chromatic and spatial factors.
Public Member Functions
BilateralSmoothing ()
Initializes a new instance of the BilateralSmoothing class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseUsingCopyPartialFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage source, UnmanagedImage destination, Rectangle rect)
Process the filter on the specified image.
Properties
bool LimitKernelSize [get, set]
Specifies if exception must be thrown in the case a large kernel size is used which may lead to significant performance issues.
bool EnableParallelProcessing [get, set]
Enable or not parallel processing on multi-core CPUs.
int KernelSize [get, set]
Size of a square for limiting surrounding pixels that take part in calculations, [3, 255].
double SpatialFactor [get, set]
Determines smoothing power within a color domain (neighbor pixels of similar color).
double SpatialPower [get, set]
Exponent power, used in Spatial function calculation.
double ColorFactor [get, set]
Determines the variance of color for a color domain .
double ColorPower [get, set]
Exponent power, used in Color function calculation.
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.BaseUsingCopyPartialFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Member Functions
void InitSpatialFunc ()
void InitColorFunc ()
void InitFilter ()
unsafe void ProcessWithoutChecksParallel (UnmanagedImage source, UnmanagedImage destination, Rectangle rect)
unsafe void ProcessWithoutChecks (UnmanagedImage source, UnmanagedImage destination, Rectangle rect)
unsafe void ProcessWithEdgeChecks (UnmanagedImage source, UnmanagedImage destination, Rectangle rect)
Private Attributes
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
int kernelSize = 9
double spatialFactor = 10
double spatialPower = 2
double colorFactor = 50
double colorPower = 2
bool spatialPropertiesChanged = true
bool colorPropertiesChanged = true
bool limitKernelSize = true
bool enableParallelProcessing = false
double[,] spatialFunc
double[,] colorFunc
Static Private Attributes
const int maxKernelSize = 255
const int colorsCount = 256
Detailed Description
Bilateral filter implementation - edge preserving smoothing and noise reduction that uses chromatic and spatial factors.
Bilateral filter conducts "selective" Gaussian smoothing of areas of same color (domains) which removes noise and contrast artifacts while preserving sharp edges.
Two major parameters SpatialFactor and ColorFactor define the result of the filter. By changing these parameters you may achieve either only noise reduction with little change to the image or get nice looking effect to the entire image.
Although the filter can use parallel processing large KernelSize values (greater than 25) on high resolution images may decrease speed of processing. Also on high resolution images small KernelSize values (less than 9) may not provide noticeable results.
More details on the algorithm can be found by following this link.
The filter accepts 8 bpp grayscale images and 24/32 bpp color images for processing.
Sample usage:
// create filter
BilateralSmoothing filter = new BilateralSmoothing();
filter.KernelSize    = 7;
filter.SpatialFactor = 10;
filter.ColorFactor   = 60;
filter.ColorPower    = 0.5;
// apply the filter
filter.ApplyInPlace(image);
Initial image:
Result image:
Constructor & Destructor Documentation
BilateralSmoothing()
AForge.Imaging.Filters.BilateralSmoothing.BilateralSmoothing () inline
Initializes a new instance of the BilateralSmoothing class.
References AForge.Imaging.Filters.BilateralSmoothing.formatTranslations.
Member Function Documentation
InitSpatialFunc()
void AForge.Imaging.Filters.BilateralSmoothing.InitSpatialFunc () inline private
References AForge.Imaging.Filters.BilateralSmoothing.kernelSize, AForge.Imaging.Filters.BilateralSmoothing.spatialFactor, AForge.Imaging.Filters.BilateralSmoothing.spatialFunc, AForge.Imaging.Filters.BilateralSmoothing.spatialPower, and AForge.Imaging.Filters.BilateralSmoothing.spatialPropertiesChanged.
Referenced by AForge.Imaging.Filters.BilateralSmoothing.InitFilter().
InitColorFunc()
void AForge.Imaging.Filters.BilateralSmoothing.InitColorFunc () inline private
References AForge.Imaging.Filters.BilateralSmoothing.colorFactor, AForge.Imaging.Filters.BilateralSmoothing.colorFunc, AForge.Imaging.Filters.BilateralSmoothing.colorPower, AForge.Imaging.Filters.BilateralSmoothing.colorPropertiesChanged, and AForge.Imaging.Filters.BilateralSmoothing.colorsCount.
Referenced by AForge.Imaging.Filters.BilateralSmoothing.InitFilter().
InitFilter()
void AForge.Imaging.Filters.BilateralSmoothing.InitFilter () inline private
References AForge.Imaging.Filters.BilateralSmoothing.InitColorFunc(), and AForge.Imaging.Filters.BilateralSmoothing.InitSpatialFunc().
Referenced by AForge.Imaging.Filters.BilateralSmoothing.ProcessFilter().
ProcessFilter()
override unsafe void AForge.Imaging.Filters.BilateralSmoothing.ProcessFilter (UnmanagedImage source, UnmanagedImage destination, Rectangle rect) inline protected virtual
Process the filter on the specified image.
Parameters
source Source image data.
destination Destination image data.
rect Image rectangle for processing by the filter.
Implements AForge.Imaging.Filters.BaseUsingCopyPartialFilter.
References AForge.Imaging.Filters.BilateralSmoothing.enableParallelProcessing, AForge.Imaging.Filters.BilateralSmoothing.InitFilter(), AForge.Imaging.Filters.BilateralSmoothing.kernelSize, AForge.Imaging.Filters.BilateralSmoothing.ProcessWithEdgeChecks(), AForge.Imaging.Filters.BilateralSmoothing.ProcessWithoutChecks(), AForge.Imaging.Filters.BilateralSmoothing.ProcessWithoutChecksParallel(), and AForge.Math.Geometry.Rectangle.
ProcessWithoutChecksParallel()
unsafe void AForge.Imaging.Filters.BilateralSmoothing.ProcessWithoutChecksParallel (UnmanagedImage source, UnmanagedImage destination, Rectangle rect) inline private
References AForge.Imaging.RGB.B, AForge.Imaging.Filters.BilateralSmoothing.colorFunc, AForge.Parallel.For(), AForge.Imaging.RGB.G, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.Filters.BilateralSmoothing.kernelSize, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, AForge.Imaging.Filters.BilateralSmoothing.spatialFunc, and AForge.Imaging.UnmanagedImage.Stride.
Referenced by AForge.Imaging.Filters.BilateralSmoothing.ProcessFilter().
ProcessWithoutChecks()
unsafe void AForge.Imaging.Filters.BilateralSmoothing.ProcessWithoutChecks (UnmanagedImage source, UnmanagedImage destination, Rectangle rect) inline private
References AForge.Imaging.RGB.B, AForge.Imaging.Filters.BilateralSmoothing.colorFunc, AForge.Imaging.RGB.G, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.Filters.BilateralSmoothing.kernelSize, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, AForge.Imaging.Filters.BilateralSmoothing.spatialFunc, and AForge.Imaging.UnmanagedImage.Stride.
Referenced by AForge.Imaging.Filters.BilateralSmoothing.ProcessFilter().
ProcessWithEdgeChecks()
unsafe void AForge.Imaging.Filters.BilateralSmoothing.ProcessWithEdgeChecks (UnmanagedImage source, UnmanagedImage destination, Rectangle rect) inline private
References AForge.Imaging.RGB.B, AForge.Imaging.Filters.BilateralSmoothing.colorFunc, AForge.Imaging.RGB.G, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.Filters.BilateralSmoothing.kernelSize, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, AForge.Imaging.Filters.BilateralSmoothing.spatialFunc, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
Referenced by AForge.Imaging.Filters.BilateralSmoothing.ProcessFilter().
Member Data Documentation
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.BilateralSmoothing.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.BilateralSmoothing.BilateralSmoothing().
maxKernelSize
const int AForge.Imaging.Filters.BilateralSmoothing.maxKernelSize = 255 static private
colorsCount
const int AForge.Imaging.Filters.BilateralSmoothing.colorsCount = 256 static private
Referenced by AForge.Imaging.Filters.BilateralSmoothing.InitColorFunc().
kernelSize
int AForge.Imaging.Filters.BilateralSmoothing.kernelSize = 9 private
Referenced by AForge.Imaging.Filters.BilateralSmoothing.InitSpatialFunc(), AForge.Imaging.Filters.BilateralSmoothing.ProcessFilter(), AForge.Imaging.Filters.BilateralSmoothing.ProcessWithEdgeChecks(), AForge.Imaging.Filters.BilateralSmoothing.ProcessWithoutChecks(), and AForge.Imaging.Filters.BilateralSmoothing.ProcessWithoutChecksParallel().
spatialFactor
double AForge.Imaging.Filters.BilateralSmoothing.spatialFactor = 10 private
Referenced by AForge.Imaging.Filters.BilateralSmoothing.InitSpatialFunc().
spatialPower
double AForge.Imaging.Filters.BilateralSmoothing.spatialPower = 2 private
Referenced by AForge.Imaging.Filters.BilateralSmoothing.InitSpatialFunc().
colorFactor
double AForge.Imaging.Filters.BilateralSmoothing.colorFactor = 50 private
Referenced by AForge.Imaging.Filters.BilateralSmoothing.InitColorFunc().
colorPower
double AForge.Imaging.Filters.BilateralSmoothing.colorPower = 2 private
Referenced by AForge.Imaging.Filters.BilateralSmoothing.InitColorFunc().
spatialPropertiesChanged
bool AForge.Imaging.Filters.BilateralSmoothing.spatialPropertiesChanged = true private
Referenced by AForge.Imaging.Filters.BilateralSmoothing.InitSpatialFunc().
colorPropertiesChanged
bool AForge.Imaging.Filters.BilateralSmoothing.colorPropertiesChanged = true private
Referenced by AForge.Imaging.Filters.BilateralSmoothing.InitColorFunc().
limitKernelSize
bool AForge.Imaging.Filters.BilateralSmoothing.limitKernelSize = true private
enableParallelProcessing
bool AForge.Imaging.Filters.BilateralSmoothing.enableParallelProcessing = false private
Referenced by AForge.Imaging.Filters.BilateralSmoothing.ProcessFilter().
spatialFunc
double [,] AForge.Imaging.Filters.BilateralSmoothing.spatialFunc private
Referenced by AForge.Imaging.Filters.BilateralSmoothing.InitSpatialFunc(), AForge.Imaging.Filters.BilateralSmoothing.ProcessWithEdgeChecks(), AForge.Imaging.Filters.BilateralSmoothing.ProcessWithoutChecks(), and AForge.Imaging.Filters.BilateralSmoothing.ProcessWithoutChecksParallel().
colorFunc
double [,] AForge.Imaging.Filters.BilateralSmoothing.colorFunc private
Referenced by AForge.Imaging.Filters.BilateralSmoothing.InitColorFunc(), AForge.Imaging.Filters.BilateralSmoothing.ProcessWithEdgeChecks(), AForge.Imaging.Filters.BilateralSmoothing.ProcessWithoutChecks(), and AForge.Imaging.Filters.BilateralSmoothing.ProcessWithoutChecksParallel().
Property Documentation
LimitKernelSize
bool AForge.Imaging.Filters.BilateralSmoothing.LimitKernelSize get set
Specifies if exception must be thrown in the case a large kernel size is used which may lead to significant performance issues.
Default value is set to true.
EnableParallelProcessing
bool AForge.Imaging.Filters.BilateralSmoothing.EnableParallelProcessing get set
Enable or not parallel processing on multi-core CPUs.
If the property is set to true, then this image processing routine will run in parallel on the systems with multiple core/CPUs. The AForge.Parallel.For is used to make it parallel.
Default value is set to false.
KernelSize
int AForge.Imaging.Filters.BilateralSmoothing.KernelSize get set
Size of a square for limiting surrounding pixels that take part in calculations, [3, 255].
The greater the value the more is the general power of the filter. Small values (less than 9) on high resolution images (3000 pixels wide) do not give significant results. Large values increase the number of calculations and degrade performance.
<note>The value of this property must be an odd integer in the [3, 255] range if LimitKernelSize is set to false or in the [3, 25] range otherwise.</note>
Default value is set to 9.
Exceptions
ArgumentOutOfRangeException The specified value is out of range (see eception message for details).
ArgumentException The value of this must be an odd integer.
SpatialFactor
double AForge.Imaging.Filters.BilateralSmoothing.SpatialFactor get set
Determines smoothing power within a color domain (neighbor pixels of similar color).
Default value is set to 10.
SpatialPower
double AForge.Imaging.Filters.BilateralSmoothing.SpatialPower get set
Exponent power, used in Spatial function calculation.
Default value is set to 2.
ColorFactor
double AForge.Imaging.Filters.BilateralSmoothing.ColorFactor get set
Determines the variance of color for a color domain .
Default value is set to 50.
ColorPower
double AForge.Imaging.Filters.BilateralSmoothing.ColorPower get set
Exponent power, used in Color function calculation.
Default value is set to 2.
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.BilateralSmoothing.FormatTranslations get
Format translations dictionary.
See IFilterInformation.FormatTranslations documentation for additional information.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Smooting/BilateralSmoothing.cs