Doc: IGLib EXTENDED: IG.Neural.Applications.ProgramAnnApp Class Reference
IG.Neural.Applications.ProgramAnnApp Class Reference
Static Protected Member Functions
static void SetWorkingDirectoryHardCoded ()
Properties
static AnnApp App [get]
Application driver.
Static Private Member Functions
static void Main (string[] args)
Static Private Attributes
static bool NormalModeNewForm = true
Member Function Documentation
SetWorkingDirectoryHardCoded()
static void IG.Neural.Applications.ProgramAnnApp.SetWorkingDirectoryHardCoded () inline static protected
References IG.Neural.Applications.ProgramAnnApp.App, IG.Lib.UtilSystem.IsUserIgor, IG.Lib.UtilSystem.IsUserTadej, and IG.Neural.Applications.AnnApp.WorkingDirectory.
Referenced by IG.Neural.Applications.ProgramAnnApp.Main().
Main()
static void IG.Neural.Applications.ProgramAnnApp.Main (string[] args) inline static private
References IG.Neural.Applications.ProgramAnnApp.App, IG.Neural.Applications.AnnApp.Init(), IG.Neural.NeuralApproximatorAforge.InitType(), IG.Neural.NeuralApproximatorNeuron.InitType(), IG.Neural.Applications.AnnApp.IsDevelopMode, IG.Neural.Applications.AnnApp.IsDirectoryCasting, IG.Neural.Applications.AnnApp.IsDirectoryConvection2d, IG.Neural.Applications.AnnApp.IsDirectoryCustom, IG.Neural.Applications.AnnApp.IsDirectoryDefault, IG.Neural.Applications.AnnApp.IsDirectoryProcessChain, IG.Neural.Applications.AnnApp.IsDirectoryTestModel, IG.Neural.Applications.AnnApp.IsExperimentalMode, IG.Neural.Applications.AnnApp.IsNormalMode, IG.Neural.Applications.AnnApp.IsOldTestMode, IG.Neural.Applications.AnnApp.IsPredictionMode, IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleData, IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleParametric, IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleSampling, IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleTrain, IG.Neural.Applications.AnnApp.IsVerbose, IG.Neural.Applications.ProgramAnnApp.NormalModeNewForm, IG.Neural.Applications.AnnApp.SetWorkingDirectoryCasting(), IG.Neural.Applications.AnnApp.SetWorkingDirectoryConvection2d(), IG.Neural.Applications.AnnApp.SetWorkingDirectoryCustom(), IG.Neural.Applications.AnnApp.SetWorkingDirectoryDefault(), IG.Neural.Applications.ProgramAnnApp.SetWorkingDirectoryHardCoded(), IG.Neural.Applications.AnnApp.SetWorkingDirectoryProcessChain(), IG.Neural.Applications.AnnApp.SetWorkingDirectoryTestModel(), and IG.Neural.Applications.AnnApp.WorkingDirectory.
Member Data Documentation
NormalModeNewForm
bool IG.Neural.Applications.ProgramAnnApp.NormalModeNewForm = true static private
Referenced by IG.Neural.Applications.ProgramAnnApp.Main().
Property Documentation
App
AnnApp IG.Neural.Applications.ProgramAnnApp.App static get
Application driver.
Referenced by IG.Neural.Applications.ProgramAnnApp.Main(), and IG.Neural.Applications.ProgramAnnApp.SetWorkingDirectoryHardCoded().
The documentation for this class was generated from the following file:
shelldev/extensions/ExtAppAnnApp/ProgramAnnApp.cs