Doc: IGLib EXTENDED: CShell.Modules.Editors.Module Class Reference
CShell.Modules.Editors.Module Class Reference
Public Member Functions
Module ()
override void Initialize ()
IEnumerable< IResult > ExecuteFile ()
IEnumerable< IResult > ExecuteSelection ()
IEnumerable< IResult > Undo ()
IEnumerable< IResult > Redo ()
IEnumerable< IResult > Cut ()
IEnumerable< IResult > Copy ()
IEnumerable< IResult > Paste ()
IEnumerable< IResult > SelectAll ()
IEnumerable< IResult > Comment ()
IEnumerable< IResult > Uncomment ()
Public Member Functions inherited from CShell.Framework.ModuleBase
void Dispose ()
Private Member Functions
IEnumerable< IResult > TryDocumentAction (Action< ITextDocument > action)
Private Attributes
IWorkspaceActivator workspaceActivator
Additional Inherited Members
Protected Member Functions inherited from CShell.Framework.ModuleBase
virtual void Dispose (bool disposing)
Properties inherited from CShell.Framework.ModuleBase
IShell Shell [get]
IMenu MainMenu [get]
IToolBar ToolBar [get]
int Order [get, set]
Properties inherited from CShell.Framework.IModule
int Order [get]
Constructor & Destructor Documentation
Module()
CShell.Modules.Editors.Module.Module () inline
References CShell.Framework.ModuleBase.Order.
Member Function Documentation
Initialize()
override void CShell.Modules.Editors.Module.Initialize () inline virtual
Implements CShell.Framework.ModuleBase.
References CShell.Framework.Menus.IToolBar.Add(), CShell.Modules.Editors.Module.Comment(), CShell.Modules.Editors.Module.Copy(), CShell.Modules.Editors.Module.Cut(), CShell.Modules.Editors.Module.ExecuteFile(), CShell.Modules.Editors.Module.ExecuteSelection(), CShell.Framework.ModuleBase.MainMenu, CShell.Modules.Editors.Module.Paste(), CShell.Modules.Editors.Module.Redo(), CShell.Modules.Editors.Module.SelectAll(), CShell.Framework.Menus.MenuItemBase.Separator, CShell.Framework.ModuleBase.ToolBar, CShell.Modules.Editors.Module.Uncomment(), CShell.Modules.Editors.Module.Undo(), and CShell.Modules.Editors.Module.workspaceActivator.
ExecuteFile()
IEnumerable<IResult> CShell.Modules.Editors.Module.ExecuteFile () inline
References CShell.Framework.Results.Run.Code(), and CShell.Modules.Editors.ViewModels.EditorViewModel.Text.
Referenced by CShell.Modules.Editors.Module.Initialize().
ExecuteSelection()
IEnumerable<IResult> CShell.Modules.Editors.Module.ExecuteSelection () inline
References CShell.Framework.Results.Run.Code(), and CShell.Modules.Editors.ViewModels.EditorViewModel.GetSelectionOrCurrentLine().
Referenced by CShell.Modules.Editors.Module.Initialize().
Undo()
IEnumerable<IResult> CShell.Modules.Editors.Module.Undo () inline
References CShell.Modules.Editors.Module.TryDocumentAction().
Referenced by CShell.Modules.Editors.Module.Initialize().
Redo()
IEnumerable<IResult> CShell.Modules.Editors.Module.Redo () inline
References CShell.Modules.Editors.Module.TryDocumentAction().
Referenced by CShell.Modules.Editors.Module.Initialize().
Cut()
IEnumerable<IResult> CShell.Modules.Editors.Module.Cut () inline
References CShell.Modules.Editors.Module.TryDocumentAction().
Referenced by CShell.Modules.Editors.Module.Initialize().
Copy()
IEnumerable<IResult> CShell.Modules.Editors.Module.Copy () inline
References CShell.Modules.Editors.Module.TryDocumentAction().
Referenced by CShell.Modules.Editors.Module.Initialize().
Paste()
IEnumerable<IResult> CShell.Modules.Editors.Module.Paste () inline
References CShell.Modules.Editors.Module.TryDocumentAction().
Referenced by CShell.Modules.Editors.Module.Initialize().
SelectAll()
IEnumerable<IResult> CShell.Modules.Editors.Module.SelectAll () inline
References CShell.Modules.Editors.Module.TryDocumentAction().
Referenced by CShell.Modules.Editors.Module.Initialize().
Comment()
IEnumerable<IResult> CShell.Modules.Editors.Module.Comment () inline
References CShell.Modules.Editors.Module.TryDocumentAction().
Referenced by CShell.Modules.Editors.Module.Initialize().
Uncomment()
IEnumerable<IResult> CShell.Modules.Editors.Module.Uncomment () inline
References CShell.Modules.Editors.Module.TryDocumentAction().
Referenced by CShell.Modules.Editors.Module.Initialize().
TryDocumentAction()
IEnumerable<IResult> CShell.Modules.Editors.Module.TryDocumentAction (Action< ITextDocument > action) inline private
Referenced by CShell.Modules.Editors.Module.Comment(), CShell.Modules.Editors.Module.Copy(), CShell.Modules.Editors.Module.Cut(), CShell.Modules.Editors.Module.Paste(), CShell.Modules.Editors.Module.Redo(), CShell.Modules.Editors.Module.SelectAll(), CShell.Modules.Editors.Module.Uncomment(), and CShell.Modules.Editors.Module.Undo().
Member Data Documentation
workspaceActivator
IWorkspaceActivator CShell.Modules.Editors.Module.workspaceActivator private
Referenced by CShell.Modules.Editors.Module.Initialize().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Editors/Module.cs