Doc: IGLib EXTENDED: NUnit.Framework.Internal.Commands.TestActionCommand Class Reference
NUnit.Framework.Internal.Commands.TestActionCommand Class Reference
TestActionCommand runs the BeforeTest actions for a test, then runs the test and finally runs the AfterTestActions.
Public Member Functions
TestActionCommand (TestCommand innerCommand)
Initializes a new instance of the TestActionCommand class.
override TestResult Execute (TestExecutionContext context)
Runs the test, saving a TestResult in the supplied TestExecutionContext.
Public Member Functions inherited from NUnit.Framework.Internal.Commands.TestCommand
TestCommand (Test test)
Construct a TestCommand for a test.
Private Attributes
IList< TestActionItem > _actions = new List<TestActionItem>()
Additional Inherited Members
Protected Member Functions inherited from NUnit.Framework.Internal.Commands.DelegatingTestCommand
DelegatingTestCommand (TestCommand innerCommand)
TODO: Documentation needed for constructor
Protected Attributes inherited from NUnit.Framework.Internal.Commands.DelegatingTestCommand
TestCommand innerCommand
TODO: Documentation needed for field
Properties inherited from NUnit.Framework.Internal.Commands.TestCommand
Test Test [get, private set]
Gets the test associated with this command.
Detailed Description
TestActionCommand runs the BeforeTest actions for a test, then runs the test and finally runs the AfterTestActions.
Constructor & Destructor Documentation
TestActionCommand()
NUnit.Framework.Internal.Commands.TestActionCommand.TestActionCommand (TestCommand innerCommand) inline
Initializes a new instance of the TestActionCommand class.
Parameters
innerCommand The inner command.
References NUnit.Framework.Internal.Commands.DelegatingTestCommand.innerCommand, and NUnit.Framework.Internal.Commands.TestCommand.Test.
Member Function Documentation
Execute()
override TestResult NUnit.Framework.Internal.Commands.TestActionCommand.Execute (TestExecutionContext context) inline virtual
Runs the test, saving a TestResult in the supplied TestExecutionContext.
Parameters
context The context in which the test should run.
Returns
A TestResult
Implements NUnit.Framework.Internal.Commands.TestCommand.
References NUnit.Framework.Internal.Commands.TestActionCommand._actions, NUnit.Framework.Internal.Commands.TestCommand.Execute(), NUnit.Framework.Internal.Commands.DelegatingTestCommand.innerCommand, NUnit.Framework.Internal.TestResult.RecordException(), NUnit.Framework.ITestAction.Targets, and NUnit.Framework.Internal.TestExecutionContext.TestObject.
Member Data Documentation
_actions
IList<TestActionItem> NUnit.Framework.Internal.Commands.TestActionCommand._actions = new List<TestActionItem>() private
Referenced by NUnit.Framework.Internal.Commands.TestActionCommand.Execute().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/Commands/TestActionCommand.cs