Doc: IGLib EXTENDED: IG.Forms.OutputValueSelector Class Reference
IG.Forms.OutputValueSelector Class Reference
Selection of the output value of interest in an ANN model.
Public Member Functions
OutputValueSelector ()
void UpdateDataDefinition ()
Initialiyes data after data definition object been set or changed.
void SetSelectedOutputId (int id)
Replacement for the SelectedOutputId setter that has a lower access level.
void UpdateSelectedParameterIdDependencies ()
Updates things that depend on the selected parameter's index.
OutputValueSelector ()
void UpdateDataDefinition ()
Initialiyes data after data definition object been set or changed.
void SetSelectedOutputId (int id)
Replacement for the SelectedOutputId setter that has a lower access level.
void UpdateSelectedParameterIdDependencies ()
Updates things that depend on the selected parameter's index.
OutputValueSelector ()
void UpdateDataDefinition ()
Initialiyes data after data definition object been set or changed.
void SetSelectedOutputId (int id)
Replacement for the SelectedOutputId setter that has a lower access level.
void UpdateSelectedParameterIdDependencies ()
Updates things that depend on the selected parameter's index.
Protected Member Functions
void OnSelectedOutputChanged (int oldId, int newId)
Raises the SelectedOutputIdChanged event. This method should be called preferrably, rather than the event itself.
override void Dispose (bool disposing)
Clean up any resources being used.
void OnSelectedOutputChanged (int oldId, int newId)
Raises the SelectedOutputIdChanged event. This method should be called preferrably, rather than the event itself.
override void Dispose (bool disposing)
Clean up any resources being used.
void OnSelectedOutputChanged (int oldId, int newId)
Raises the SelectedOutputIdChanged event. This method should be called preferrably, rather than the event itself.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
int _selectedOutputId = 0
Properties
InputOutputDataDefiniton DataDefinition [get, set]
Data about input and output quantities of the manipulated functions or response.
int NumInputParameters [get, set]
Gets number of input parameters.
int NumOutputValues [get, set]
Gets number of output values.
int SelectedOutputId [get, protected set]
Sequential number of the selected parameter as specified by the user.
Events
EventHandler< IndexChangeEventArgs > SelectedOutputIdChanged
Occurs when selected output value ID is changed.
Private Member Functions
void comboBoxSelection_SelectedIndexChanged (object sender, EventArgs e)
void txtParamNum_ValueChanged (object sender, EventArgs e)
void btnDecrease_Click (object sender, EventArgs e)
void btnIncrease_Click (object sender, EventArgs e)
void menuSummary_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void comboBoxSelection_SelectedIndexChanged (object sender, EventArgs e)
void txtParamNum_ValueChanged (object sender, EventArgs e)
void btnDecrease_Click (object sender, EventArgs e)
void btnIncrease_Click (object sender, EventArgs e)
void menuSummary_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void comboBoxSelection_SelectedIndexChanged (object sender, EventArgs e)
void txtParamNum_ValueChanged (object sender, EventArgs e)
void btnDecrease_Click (object sender, EventArgs e)
void btnIncrease_Click (object sender, EventArgs e)
void menuSummary_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
InputOutputDataDefiniton _dataDefinition
int _numInputParameters = 2
int _numOutputValues = 2
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Label lblParamNum
System.Windows.Forms.Label lblSelectParameter
System.Windows.Forms.NumericUpDown txtValueNum
System.Windows.Forms.ComboBox comboBoxSelection
System.Windows.Forms.Button btnDecrease
System.Windows.Forms.Button btnIncrease
System.Windows.Forms.Panel pnlMain
System.Windows.Forms.ContextMenuStrip contextMenuStrip1
System.Windows.Forms.ToolStripMenuItem menuSummary
Detailed Description
Selection of the output value of interest in an ANN model.
$A Igor Apr13 March16;
Constructor & Destructor Documentation
OutputValueSelector() [1/3]
IG.Forms.OutputValueSelector.OutputValueSelector () inline
References IG.Forms.OutputValueSelector.InitializeComponent().
OutputValueSelector() [2/3]
IG.Forms.OutputValueSelector.OutputValueSelector () inline
References IG.Forms.OutputValueSelector.InitializeComponent().
OutputValueSelector() [3/3]
IG.Forms.OutputValueSelector.OutputValueSelector () inline
References IG.Forms.OutputValueSelector.InitializeComponent().
Member Function Documentation
UpdateDataDefinition() [1/3]
void IG.Forms.OutputValueSelector.UpdateDataDefinition () inline
Initialiyes data after data definition object been set or changed.
References IG.Forms.OutputValueSelector.comboBoxSelection, IG.Forms.OutputValueSelector.DataDefinition, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.Name, IG.Forms.OutputValueSelector.NumInputParameters, IG.Forms.OutputValueSelector.NumOutputValues, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Num.InputOutputDataDefiniton.OutputLength, IG.Forms.OutputValueSelector.SelectedOutputId, IG.Num.InputOutputElementDefinition.Title, and IG.Forms.OutputValueSelector.UpdateSelectedParameterIdDependencies().
OnSelectedOutputChanged() [1/3]
void IG.Forms.OutputValueSelector.OnSelectedOutputChanged (int oldId, int newId) inline protected
Raises the SelectedOutputIdChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldId Old output element Id.
newId New output element Id.
References IG.Forms.OutputValueSelector.SelectedOutputIdChanged.
SetSelectedOutputId() [1/3]
void IG.Forms.OutputValueSelector.SetSelectedOutputId (int id) inline
Replacement for the SelectedOutputId setter that has a lower access level.
Parameters
id Sequential number of the output valuee to be selected.
References IG.Forms.OutputValueSelector.SelectedOutputId.
UpdateSelectedParameterIdDependencies() [1/3]
void IG.Forms.OutputValueSelector.UpdateSelectedParameterIdDependencies () inline
Updates things that depend on the selected parameter's index.
References IG.Forms.OutputValueSelector.comboBoxSelection, IG.Forms.OutputValueSelector.SelectedOutputId, and IG.Forms.OutputValueSelector.txtValueNum.
Referenced by IG.Forms.OutputValueSelector.UpdateDataDefinition().
comboBoxSelection_SelectedIndexChanged() [1/3]
void IG.Forms.OutputValueSelector.comboBoxSelection_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Forms.OutputValueSelector.comboBoxSelection, and IG.Forms.OutputValueSelector.SelectedOutputId.
Referenced by IG.Forms.OutputValueSelector.InitializeComponent().
txtParamNum_ValueChanged() [1/3]
void IG.Forms.OutputValueSelector.txtParamNum_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.OutputValueSelector.SelectedOutputId, and IG.Forms.OutputValueSelector.txtValueNum.
Referenced by IG.Forms.OutputValueSelector.InitializeComponent().
btnDecrease_Click() [1/3]
void IG.Forms.OutputValueSelector.btnDecrease_Click (object sender, EventArgs e) inline private
References IG.Forms.OutputValueSelector.SelectedOutputId.
Referenced by IG.Forms.OutputValueSelector.InitializeComponent().
btnIncrease_Click() [1/3]
void IG.Forms.OutputValueSelector.btnIncrease_Click (object sender, EventArgs e) inline private
References IG.Forms.OutputValueSelector.SelectedOutputId.
Referenced by IG.Forms.OutputValueSelector.InitializeComponent().
menuSummary_Click() [1/3]
void IG.Forms.OutputValueSelector.menuSummary_Click (object sender, EventArgs e) inline private
References IG.Forms.OutputValueSelector.DataDefinition, IG.Forms.FadingMessage.Launch(), IG.Forms.FadingMessage.LaunchedInParallelThread, IG.Forms.OutputValueSelector.NumInputParameters, IG.Forms.OutputValueSelector.NumOutputValues, IG.Forms.OutputValueSelector.SelectedOutputId, and IG.Forms.OutputValueSelector.SelectedOutputIdChanged.
Dispose() [1/3]
override void IG.Forms.OutputValueSelector.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.OutputValueSelector.components.
InitializeComponent() [1/3]
void IG.Forms.OutputValueSelector.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.OutputValueSelector.btnDecrease, IG.Forms.OutputValueSelector.btnDecrease_Click(), IG.Forms.OutputValueSelector.btnIncrease, IG.Forms.OutputValueSelector.btnIncrease_Click(), IG.Forms.OutputValueSelector.comboBoxSelection, IG.Forms.OutputValueSelector.comboBoxSelection_SelectedIndexChanged(), IG.Forms.OutputValueSelector.components, IG.Forms.OutputValueSelector.contextMenuStrip1, IG.Forms.OutputValueSelector.lblParamNum, IG.Forms.OutputValueSelector.lblSelectParameter, IG.Forms.OutputValueSelector.menuSummary, IG.Forms.OutputValueSelector.pnlMain, IG.Forms.OutputValueSelector.txtParamNum_ValueChanged(), and IG.Forms.OutputValueSelector.txtValueNum.
Referenced by IG.Forms.OutputValueSelector.OutputValueSelector().
UpdateDataDefinition() [2/3]
void IG.Forms.OutputValueSelector.UpdateDataDefinition () inline
Initialiyes data after data definition object been set or changed.
References IG.Forms.OutputValueSelector.comboBoxSelection, IG.Forms.OutputValueSelector.DataDefinition, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.Name, IG.Forms.OutputValueSelector.NumInputParameters, IG.Forms.OutputValueSelector.NumOutputValues, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Num.InputOutputDataDefiniton.OutputLength, IG.Forms.OutputValueSelector.SelectedOutputId, IG.Num.InputOutputElementDefinition.Title, and IG.Forms.OutputValueSelector.UpdateSelectedParameterIdDependencies().
OnSelectedOutputChanged() [2/3]
void IG.Forms.OutputValueSelector.OnSelectedOutputChanged (int oldId, int newId) inline protected
Raises the SelectedOutputIdChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldId Old output element Id.
newId New output element Id.
References IG.Forms.OutputValueSelector.SelectedOutputIdChanged.
SetSelectedOutputId() [2/3]
void IG.Forms.OutputValueSelector.SetSelectedOutputId (int id) inline
Replacement for the SelectedOutputId setter that has a lower access level.
Parameters
id Sequential number of the output valuee to be selected.
References IG.Forms.OutputValueSelector.SelectedOutputId.
UpdateSelectedParameterIdDependencies() [2/3]
void IG.Forms.OutputValueSelector.UpdateSelectedParameterIdDependencies () inline
Updates things that depend on the selected parameter's index.
References IG.Forms.OutputValueSelector.comboBoxSelection, IG.Forms.OutputValueSelector.SelectedOutputId, and IG.Forms.OutputValueSelector.txtValueNum.
comboBoxSelection_SelectedIndexChanged() [2/3]
void IG.Forms.OutputValueSelector.comboBoxSelection_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Forms.OutputValueSelector.comboBoxSelection, and IG.Forms.OutputValueSelector.SelectedOutputId.
txtParamNum_ValueChanged() [2/3]
void IG.Forms.OutputValueSelector.txtParamNum_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.OutputValueSelector.SelectedOutputId, and IG.Forms.OutputValueSelector.txtValueNum.
btnDecrease_Click() [2/3]
void IG.Forms.OutputValueSelector.btnDecrease_Click (object sender, EventArgs e) inline private
References IG.Forms.OutputValueSelector.SelectedOutputId.
btnIncrease_Click() [2/3]
void IG.Forms.OutputValueSelector.btnIncrease_Click (object sender, EventArgs e) inline private
References IG.Forms.OutputValueSelector.SelectedOutputId.
menuSummary_Click() [2/3]
void IG.Forms.OutputValueSelector.menuSummary_Click (object sender, EventArgs e) inline private
References IG.Forms.OutputValueSelector.DataDefinition, IG.Forms.FadingMessage.Launch(), IG.Forms.FadingMessage.LaunchedInParallelThread, IG.Forms.OutputValueSelector.NumInputParameters, IG.Forms.OutputValueSelector.NumOutputValues, IG.Forms.OutputValueSelector.SelectedOutputId, and IG.Forms.OutputValueSelector.SelectedOutputIdChanged.
Dispose() [2/3]
override void IG.Forms.OutputValueSelector.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.OutputValueSelector.components.
InitializeComponent() [2/3]
void IG.Forms.OutputValueSelector.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.OutputValueSelector.btnDecrease, IG.Forms.OutputValueSelector.btnDecrease_Click(), IG.Forms.OutputValueSelector.btnIncrease, IG.Forms.OutputValueSelector.btnIncrease_Click(), IG.Forms.OutputValueSelector.comboBoxSelection, IG.Forms.OutputValueSelector.comboBoxSelection_SelectedIndexChanged(), IG.Forms.OutputValueSelector.components, IG.Forms.OutputValueSelector.contextMenuStrip1, IG.Forms.OutputValueSelector.lblParamNum, IG.Forms.OutputValueSelector.lblSelectParameter, IG.Forms.OutputValueSelector.menuSummary, IG.Forms.OutputValueSelector.pnlMain, IG.Forms.OutputValueSelector.txtParamNum_ValueChanged(), and IG.Forms.OutputValueSelector.txtValueNum.
UpdateDataDefinition() [3/3]
void IG.Forms.OutputValueSelector.UpdateDataDefinition () inline
Initialiyes data after data definition object been set or changed.
References IG.Forms.OutputValueSelector.comboBoxSelection, IG.Forms.OutputValueSelector.DataDefinition, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.Name, IG.Forms.OutputValueSelector.NumInputParameters, IG.Forms.OutputValueSelector.NumOutputValues, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Num.InputOutputDataDefiniton.OutputLength, IG.Forms.OutputValueSelector.SelectedOutputId, IG.Num.InputOutputElementDefinition.Title, and IG.Forms.OutputValueSelector.UpdateSelectedParameterIdDependencies().
OnSelectedOutputChanged() [3/3]
void IG.Forms.OutputValueSelector.OnSelectedOutputChanged (int oldId, int newId) inline protected
Raises the SelectedOutputIdChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldId Old output element Id.
newId New output element Id.
References IG.Forms.OutputValueSelector.SelectedOutputIdChanged.
SetSelectedOutputId() [3/3]
void IG.Forms.OutputValueSelector.SetSelectedOutputId (int id) inline
Replacement for the SelectedOutputId setter that has a lower access level.
Parameters
id Sequential number of the output valuee to be selected.
References IG.Forms.OutputValueSelector.SelectedOutputId.
UpdateSelectedParameterIdDependencies() [3/3]
void IG.Forms.OutputValueSelector.UpdateSelectedParameterIdDependencies () inline
Updates things that depend on the selected parameter's index.
References IG.Forms.OutputValueSelector.comboBoxSelection, IG.Forms.OutputValueSelector.SelectedOutputId, and IG.Forms.OutputValueSelector.txtValueNum.
comboBoxSelection_SelectedIndexChanged() [3/3]
void IG.Forms.OutputValueSelector.comboBoxSelection_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Forms.OutputValueSelector.comboBoxSelection, and IG.Forms.OutputValueSelector.SelectedOutputId.
txtParamNum_ValueChanged() [3/3]
void IG.Forms.OutputValueSelector.txtParamNum_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.OutputValueSelector.SelectedOutputId, and IG.Forms.OutputValueSelector.txtValueNum.
btnDecrease_Click() [3/3]
void IG.Forms.OutputValueSelector.btnDecrease_Click (object sender, EventArgs e) inline private
References IG.Forms.OutputValueSelector.SelectedOutputId.
btnIncrease_Click() [3/3]
void IG.Forms.OutputValueSelector.btnIncrease_Click (object sender, EventArgs e) inline private
References IG.Forms.OutputValueSelector.SelectedOutputId.
menuSummary_Click() [3/3]
void IG.Forms.OutputValueSelector.menuSummary_Click (object sender, EventArgs e) inline private
References IG.Forms.OutputValueSelector.DataDefinition, IG.Forms.FadingMessage.Launch(), IG.Forms.FadingMessage.LaunchedInParallelThread, IG.Forms.OutputValueSelector.NumInputParameters, IG.Forms.OutputValueSelector.NumOutputValues, IG.Forms.OutputValueSelector.SelectedOutputId, and IG.Forms.OutputValueSelector.SelectedOutputIdChanged.
Dispose() [3/3]
override void IG.Forms.OutputValueSelector.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.OutputValueSelector.components.
InitializeComponent() [3/3]
void IG.Forms.OutputValueSelector.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.OutputValueSelector.btnDecrease, IG.Forms.OutputValueSelector.btnDecrease_Click(), IG.Forms.OutputValueSelector.btnIncrease, IG.Forms.OutputValueSelector.btnIncrease_Click(), IG.Forms.OutputValueSelector.comboBoxSelection, IG.Forms.OutputValueSelector.comboBoxSelection_SelectedIndexChanged(), IG.Forms.OutputValueSelector.components, IG.Forms.OutputValueSelector.contextMenuStrip1, IG.Forms.OutputValueSelector.lblParamNum, IG.Forms.OutputValueSelector.lblSelectParameter, IG.Forms.OutputValueSelector.menuSummary, IG.Forms.OutputValueSelector.pnlMain, IG.Forms.OutputValueSelector.txtParamNum_ValueChanged(), and IG.Forms.OutputValueSelector.txtValueNum.
Member Data Documentation
_dataDefinition
InputOutputDataDefiniton IG.Forms.OutputValueSelector._dataDefinition private
_numInputParameters
int IG.Forms.OutputValueSelector._numInputParameters = 2 private
_numOutputValues
int IG.Forms.OutputValueSelector._numOutputValues = 2 private
_selectedOutputId
int IG.Forms.OutputValueSelector._selectedOutputId = 0 protected
components
System ComponentModel IContainer IG.Forms.OutputValueSelector.components = null private
Required designer variable.
Referenced by IG.Forms.OutputValueSelector.Dispose(), and IG.Forms.OutputValueSelector.InitializeComponent().
lblParamNum
System Windows Forms Label IG.Forms.OutputValueSelector.lblParamNum private
Referenced by IG.Forms.OutputValueSelector.InitializeComponent().
lblSelectParameter
System Windows Forms Label IG.Forms.OutputValueSelector.lblSelectParameter private
Referenced by IG.Forms.OutputValueSelector.InitializeComponent().
txtValueNum
System Windows Forms NumericUpDown IG.Forms.OutputValueSelector.txtValueNum private
Referenced by IG.Forms.OutputValueSelector.InitializeComponent(), IG.Forms.OutputValueSelector.txtParamNum_ValueChanged(), and IG.Forms.OutputValueSelector.UpdateSelectedParameterIdDependencies().
comboBoxSelection
System Windows Forms ComboBox IG.Forms.OutputValueSelector.comboBoxSelection private
Referenced by IG.Forms.OutputValueSelector.comboBoxSelection_SelectedIndexChanged(), IG.Forms.OutputValueSelector.InitializeComponent(), IG.Forms.OutputValueSelector.UpdateDataDefinition(), and IG.Forms.OutputValueSelector.UpdateSelectedParameterIdDependencies().
btnDecrease
System Windows Forms Button IG.Forms.OutputValueSelector.btnDecrease private
Referenced by IG.Forms.OutputValueSelector.InitializeComponent().
btnIncrease
System Windows Forms Button IG.Forms.OutputValueSelector.btnIncrease private
Referenced by IG.Forms.OutputValueSelector.InitializeComponent().
pnlMain
System Windows Forms Panel IG.Forms.OutputValueSelector.pnlMain private
Referenced by IG.Forms.OutputValueSelector.InitializeComponent().
contextMenuStrip1
System Windows Forms ContextMenuStrip IG.Forms.OutputValueSelector.contextMenuStrip1 private
Referenced by IG.Forms.OutputValueSelector.InitializeComponent().
menuSummary
System Windows Forms ToolStripMenuItem IG.Forms.OutputValueSelector.menuSummary private
Referenced by IG.Forms.OutputValueSelector.InitializeComponent().
Property Documentation
DataDefinition
InputOutputDataDefiniton IG.Forms.OutputValueSelector.DataDefinition get set
Data about input and output quantities of the manipulated functions or response.
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.OutputValueSelector.menuSummary_Click(), and IG.Forms.OutputValueSelector.UpdateDataDefinition().
NumInputParameters
int IG.Forms.OutputValueSelector.NumInputParameters get set
Gets number of input parameters.
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.OutputValueSelector.menuSummary_Click(), and IG.Forms.OutputValueSelector.UpdateDataDefinition().
NumOutputValues
int IG.Forms.OutputValueSelector.NumOutputValues get set
Gets number of output values.
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.OutputValueSelector.menuSummary_Click(), and IG.Forms.OutputValueSelector.UpdateDataDefinition().
SelectedOutputId
int IG.Forms.OutputValueSelector.SelectedOutputId get protected set
Sequential number of the selected parameter as specified by the user.
Referenced by IG.Forms.OutputValueSelector.btnDecrease_Click(), IG.Forms.OutputValueSelector.btnIncrease_Click(), IG.Forms.OutputValueSelector.comboBoxSelection_SelectedIndexChanged(), IG.Forms.OutputValueSelector.menuSummary_Click(), IG.Forms.OutputValueSelector.SetSelectedOutputId(), IG.Forms.OutputValueSelector.txtParamNum_ValueChanged(), IG.Forms.OutputValueSelector.UpdateDataDefinition(), and IG.Forms.OutputValueSelector.UpdateSelectedParameterIdDependencies().
Event Documentation
SelectedOutputIdChanged
EventHandler< IndexChangeEventArgs > IG.Forms.OutputValueSelector.SelectedOutputIdChanged
Occurs when selected output value ID is changed.
Referenced by IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.OutputValueSelector.menuSummary_Click(), and IG.Forms.OutputValueSelector.OnSelectedOutputChanged().
The documentation for this class was generated from the following files:
iglib/extensions/iglibext/Forms/Numeric/FromNeural/Basic/ParametricOutputValueSelector.cs
iglib/extensions/iglibext/Forms/Numeric/FromNeural/Basic/ParametricOutputValueSelector.Designer.cs