Doc: IGLib EXTENDED: BlobsExplorer.MainForm Class Reference
BlobsExplorer.MainForm Class Reference
Public Member Functions
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void MainForm_Load (object sender, EventArgs e)
void exitToolStripMenuItem_Click (object sender, EventArgs e)
void openToolStripMenuItem_Click (object sender, EventArgs e)
void ProcessImage (Bitmap image)
void blobsBrowser_BlobSelected (object sender, Blob blob)
void loaddemoImageToolStripMenuItem_Click (object sender, EventArgs e)
void LoadDemo ()
void aboutToolStripMenuItem_Click (object sender, EventArgs e)
void highlightTypeCombo_SelectedIndexChanged (object sender, EventArgs e)
void showRectangleAroundSelectionCheck_CheckedChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.MenuStrip mainMenu
System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem
System.Windows.Forms.StatusStrip statusStrip
System.Windows.Forms.ToolStripMenuItem openToolStripMenuItem
System.Windows.Forms.ToolStripSeparator toolStripMenuItem1
System.Windows.Forms.OpenFileDialog openFileDialog
System.Windows.Forms.SplitContainer splitContainer
System.Windows.Forms.PropertyGrid propertyGrid
BlobsBrowser blobsBrowser
System.Windows.Forms.ToolStripStatusLabel blobsCountLabel
System.Windows.Forms.ToolStripMenuItem loaddemoImageToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.ComboBox highlightTypeCombo
System.Windows.Forms.CheckBox showRectangleAroundSelectionCheck
Constructor & Destructor Documentation
MainForm()
BlobsExplorer.MainForm.MainForm () inline
References BlobsExplorer.MainForm.blobsBrowser, BlobsExplorer.MainForm.highlightTypeCombo, BlobsExplorer.MainForm.InitializeComponent(), BlobsExplorer.BlobsBrowser.ShowRectangleAroundSelection, and BlobsExplorer.MainForm.showRectangleAroundSelectionCheck.
Member Function Documentation
MainForm_Load()
void BlobsExplorer.MainForm.MainForm_Load (object sender, EventArgs e) inline private
References BlobsExplorer.MainForm.LoadDemo().
exitToolStripMenuItem_Click()
void BlobsExplorer.MainForm.exitToolStripMenuItem_Click (object sender, EventArgs e) inline private
Referenced by BlobsExplorer.MainForm.InitializeComponent().
openToolStripMenuItem_Click()
void BlobsExplorer.MainForm.openToolStripMenuItem_Click (object sender, EventArgs e) inline private
References BlobsExplorer.MainForm.openFileDialog, and BlobsExplorer.MainForm.ProcessImage().
Referenced by BlobsExplorer.MainForm.InitializeComponent().
ProcessImage()
void BlobsExplorer.MainForm.ProcessImage (Bitmap image) inline private
References BlobsExplorer.MainForm.blobsBrowser, BlobsExplorer.MainForm.blobsCountLabel, BlobsExplorer.MainForm.propertyGrid, and BlobsExplorer.BlobsBrowser.SetImage().
Referenced by BlobsExplorer.MainForm.LoadDemo(), and BlobsExplorer.MainForm.openToolStripMenuItem_Click().
blobsBrowser_BlobSelected()
void BlobsExplorer.MainForm.blobsBrowser_BlobSelected (object sender, Blob blob) inline private
References BlobsExplorer.MainForm.propertyGrid.
loaddemoImageToolStripMenuItem_Click()
void BlobsExplorer.MainForm.loaddemoImageToolStripMenuItem_Click (object sender, EventArgs e) inline private
References BlobsExplorer.MainForm.LoadDemo().
Referenced by BlobsExplorer.MainForm.InitializeComponent().
LoadDemo()
void BlobsExplorer.MainForm.LoadDemo () inline private
References BlobsExplorer.MainForm.ProcessImage().
Referenced by BlobsExplorer.MainForm.loaddemoImageToolStripMenuItem_Click(), and BlobsExplorer.MainForm.MainForm_Load().
aboutToolStripMenuItem_Click()
void BlobsExplorer.MainForm.aboutToolStripMenuItem_Click (object sender, EventArgs e) inline private
highlightTypeCombo_SelectedIndexChanged()
void BlobsExplorer.MainForm.highlightTypeCombo_SelectedIndexChanged (object sender, EventArgs e) inline private
References BlobsExplorer.MainForm.blobsBrowser, BlobsExplorer.BlobsBrowser.Highlighting, and BlobsExplorer.MainForm.highlightTypeCombo.
showRectangleAroundSelectionCheck_CheckedChanged()
void BlobsExplorer.MainForm.showRectangleAroundSelectionCheck_CheckedChanged (object sender, EventArgs e) inline private
References BlobsExplorer.MainForm.blobsBrowser, BlobsExplorer.BlobsBrowser.ShowRectangleAroundSelection, and BlobsExplorer.MainForm.showRectangleAroundSelectionCheck.
Dispose()
override void BlobsExplorer.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References BlobsExplorer.MainForm.components.
InitializeComponent()
void BlobsExplorer.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References BlobsExplorer.MainForm.aboutToolStripMenuItem, BlobsExplorer.MainForm.blobsBrowser, BlobsExplorer.MainForm.blobsCountLabel, BlobsExplorer.MainForm.exitToolStripMenuItem, BlobsExplorer.MainForm.exitToolStripMenuItem_Click(), BlobsExplorer.MainForm.fileToolStripMenuItem, BlobsExplorer.MainForm.groupBox1, BlobsExplorer.MainForm.helpToolStripMenuItem, BlobsExplorer.MainForm.highlightTypeCombo, BlobsExplorer.MainForm.loaddemoImageToolStripMenuItem, BlobsExplorer.MainForm.loaddemoImageToolStripMenuItem_Click(), BlobsExplorer.MainForm.mainMenu, BlobsExplorer.MainForm.openFileDialog, BlobsExplorer.MainForm.openToolStripMenuItem, BlobsExplorer.MainForm.openToolStripMenuItem_Click(), BlobsExplorer.MainForm.propertyGrid, BlobsExplorer.MainForm.showRectangleAroundSelectionCheck, BlobsExplorer.MainForm.splitContainer, BlobsExplorer.MainForm.statusStrip, and BlobsExplorer.MainForm.toolStripMenuItem1.
Referenced by BlobsExplorer.MainForm.MainForm().
Member Data Documentation
components
System.ComponentModel.IContainer BlobsExplorer.MainForm.components = null private
Required designer variable.
Referenced by BlobsExplorer.MainForm.Dispose().
mainMenu
System.Windows.Forms.MenuStrip BlobsExplorer.MainForm.mainMenu private
Referenced by BlobsExplorer.MainForm.InitializeComponent().
fileToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem BlobsExplorer.MainForm.fileToolStripMenuItem private
Referenced by BlobsExplorer.MainForm.InitializeComponent().
exitToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem BlobsExplorer.MainForm.exitToolStripMenuItem private
Referenced by BlobsExplorer.MainForm.InitializeComponent().
statusStrip
System.Windows.Forms.StatusStrip BlobsExplorer.MainForm.statusStrip private
Referenced by BlobsExplorer.MainForm.InitializeComponent().
openToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem BlobsExplorer.MainForm.openToolStripMenuItem private
Referenced by BlobsExplorer.MainForm.InitializeComponent().
toolStripMenuItem1
System.Windows.Forms.ToolStripSeparator BlobsExplorer.MainForm.toolStripMenuItem1 private
Referenced by BlobsExplorer.MainForm.InitializeComponent().
openFileDialog
System.Windows.Forms.OpenFileDialog BlobsExplorer.MainForm.openFileDialog private
Referenced by BlobsExplorer.MainForm.InitializeComponent(), and BlobsExplorer.MainForm.openToolStripMenuItem_Click().
splitContainer
System.Windows.Forms.SplitContainer BlobsExplorer.MainForm.splitContainer private
Referenced by BlobsExplorer.MainForm.InitializeComponent().
propertyGrid
System.Windows.Forms.PropertyGrid BlobsExplorer.MainForm.propertyGrid private
Referenced by BlobsExplorer.MainForm.blobsBrowser_BlobSelected(), BlobsExplorer.MainForm.InitializeComponent(), and BlobsExplorer.MainForm.ProcessImage().
blobsBrowser
BlobsBrowser BlobsExplorer.MainForm.blobsBrowser private
Referenced by BlobsExplorer.MainForm.highlightTypeCombo_SelectedIndexChanged(), BlobsExplorer.MainForm.InitializeComponent(), BlobsExplorer.MainForm.MainForm(), BlobsExplorer.MainForm.ProcessImage(), and BlobsExplorer.MainForm.showRectangleAroundSelectionCheck_CheckedChanged().
blobsCountLabel
System.Windows.Forms.ToolStripStatusLabel BlobsExplorer.MainForm.blobsCountLabel private
Referenced by BlobsExplorer.MainForm.InitializeComponent(), and BlobsExplorer.MainForm.ProcessImage().
loaddemoImageToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem BlobsExplorer.MainForm.loaddemoImageToolStripMenuItem private
Referenced by BlobsExplorer.MainForm.InitializeComponent().
helpToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem BlobsExplorer.MainForm.helpToolStripMenuItem private
Referenced by BlobsExplorer.MainForm.InitializeComponent().
aboutToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem BlobsExplorer.MainForm.aboutToolStripMenuItem private
Referenced by BlobsExplorer.MainForm.InitializeComponent().
groupBox1
System.Windows.Forms.GroupBox BlobsExplorer.MainForm.groupBox1 private
Referenced by BlobsExplorer.MainForm.InitializeComponent().
highlightTypeCombo
System.Windows.Forms.ComboBox BlobsExplorer.MainForm.highlightTypeCombo private
Referenced by BlobsExplorer.MainForm.highlightTypeCombo_SelectedIndexChanged(), BlobsExplorer.MainForm.InitializeComponent(), and BlobsExplorer.MainForm.MainForm().
showRectangleAroundSelectionCheck
System.Windows.Forms.CheckBox BlobsExplorer.MainForm.showRectangleAroundSelectionCheck private
Referenced by BlobsExplorer.MainForm.InitializeComponent(), BlobsExplorer.MainForm.MainForm(), and BlobsExplorer.MainForm.showRectangleAroundSelectionCheck_CheckedChanged().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Imaging/BlobsExplorer/MainForm.cs
shelldev/lib_ann/aforge.net/Samples/Imaging/BlobsExplorer/MainForm.Designer.cs