Doc: IGLib EXTENDED: Test.ComplexTest Class Reference
Test.ComplexTest Class Reference
This is a test class for ComplexTest and is intended to contain all ComplexTest Unit Tests /summary>
Public Member Functions
void ComplexComponents ()
void ComplexEquality ()
void ComplexConjugation ()
void ComplexNegation ()
void ComplexSubtraction ()
void ComplexMultiplication ()
void ComplexExplicitCast ()
void ComplexExplicitCastFailure ()
void ComplexAddition ()
void ComplexEquals ()
Properties
TestContext TestContext [get, set]
Gets or sets the test context which provides information about and functionality for the current test run. /summary>
Private Attributes
TestContext testContextInstance
Complex a = new Complex(1.5, -2.2)
Complex b = new Complex(-7.4, 3.8)
Complex c = new Complex(5.9, 6.0)
Detailed Description
This is a test class for ComplexTest and is intended to contain all ComplexTest Unit Tests /summary>
Member Function Documentation
ComplexComponents()
void Test.ComplexTest.ComplexComponents () inline
ComplexEquality()
void Test.ComplexTest.ComplexEquality () inline
References Test.ComplexTest.a, Test.ComplexTest.b, Meta.Numerics.Complex.Equals(), and Meta.Numerics.Complex.GetHashCode().
ComplexConjugation()
void Test.ComplexTest.ComplexConjugation () inline
References Test.ComplexTest.a, Meta.Numerics.Complex.Conjugate, Meta.Numerics.Complex.Im, and Meta.Numerics.Complex.Re.
ComplexNegation()
void Test.ComplexTest.ComplexNegation () inline
References Test.ComplexTest.a.
ComplexSubtraction()
void Test.ComplexTest.ComplexSubtraction () inline
References Test.ComplexTest.a, and Test.ComplexTest.b.
ComplexMultiplication()
void Test.ComplexTest.ComplexMultiplication () inline
References Test.ComplexTest.a, Test.ComplexTest.b, and Test.ComplexTest.c.
ComplexExplicitCast()
void Test.ComplexTest.ComplexExplicitCast () inline
References Test.ComplexTest.a, Test.ComplexTest.b, and Meta.Numerics.Complex.Re.
ComplexExplicitCastFailure()
void Test.ComplexTest.ComplexExplicitCastFailure () inline
References Test.ComplexTest.a, and Test.ComplexTest.b.
ComplexAddition()
void Test.ComplexTest.ComplexAddition () inline
References Test.ComplexTest.a, and Test.ComplexTest.b.
ComplexEquals()
void Test.ComplexTest.ComplexEquals () inline
References Test.ComplexTest.a, Test.ComplexTest.b, and Meta.Numerics.Complex.Equals().
Member Data Documentation
testContextInstance
TestContext Test.ComplexTest.testContextInstance private
a
Complex Test.ComplexTest.a = new Complex(1.5, -2.2) private
Referenced by Test.ComplexTest.ComplexAddition(), Test.ComplexTest.ComplexConjugation(), Test.ComplexTest.ComplexEquality(), Test.ComplexTest.ComplexEquals(), Test.ComplexTest.ComplexExplicitCast(), Test.ComplexTest.ComplexExplicitCastFailure(), Test.ComplexTest.ComplexMultiplication(), Test.ComplexTest.ComplexNegation(), and Test.ComplexTest.ComplexSubtraction().
b
Complex Test.ComplexTest.b = new Complex(-7.4, 3.8) private
Referenced by Test.ComplexTest.ComplexAddition(), Test.ComplexTest.ComplexEquality(), Test.ComplexTest.ComplexEquals(), Test.ComplexTest.ComplexExplicitCast(), Test.ComplexTest.ComplexExplicitCastFailure(), Test.ComplexTest.ComplexMultiplication(), and Test.ComplexTest.ComplexSubtraction().
c
Complex Test.ComplexTest.c = new Complex(5.9, 6.0) private
Referenced by Test.ComplexTest.ComplexMultiplication().
Property Documentation
TestContext
TestContext Test.ComplexTest.TestContext get set
Gets or sets the test context which provides information about and functionality for the current test run. /summary>
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/ComplexTest.cs