Doc: IGLib EXTENDED: AForge.Genetic.GEPChromosome Class Reference
AForge.Genetic.GEPChromosome Class Reference
The chromosome represents a Gene Expression, which is used for different tasks of Genetic Expression Programming (GEP).
Public Member Functions
GEPChromosome (IGPGene ancestor, int headLength)
Initializes a new instance of the GEPChromosome class.
override string ToString ()
Get string representation of the chromosome by providing its expression in reverse polish notation (postfix notation).
string ToStringNative ()
Get string representation of the chromosome.
override void Generate ()
Generate random chromosome value.
override IChromosome CreateNew ()
Create new random chromosome with same parameters (factory method).
override IChromosome Clone ()
Clone the chromosome.
override void Mutate ()
Mutation operator.
override void Crossover (IChromosome pair)
Crossover operator.
void RecombinationOnePoint (GEPChromosome pair)
One-point recombination (crossover).
void RecombinationTwoPoint (GEPChromosome pair)
Two point recombination (crossover).
Public Member Functions inherited from AForge.Genetic.ChromosomeBase
void Evaluate (IFitnessFunction function)
Evaluate chromosome with specified fitness function.
int CompareTo (object o)
Compare two chromosomes.
Protected Member Functions
GEPChromosome (GEPChromosome source)
Initializes a new instance of the GEPChromosome class.
GPTreeNode GetTree ()
Get tree representation of the chromosome.
void MutateGene ()
Usual gene mutation.
void TransposeIS ()
Transposition of IS elements (insertion sequence).
void TransposeRoot ()
Root transposition.
Static Protected Member Functions
static void Recombine (IGPGene[] src1, IGPGene[] src2, int point, int length)
Swap parts of two chromosomes.
Protected Attributes
int headLength
Length of GEP chromosome's head.
int length
GEP chromosome's length.
IGPGene[] genes
Array of chromosome's genes.
Protected Attributes inherited from AForge.Genetic.ChromosomeBase
double fitness = 0
Chromosome's fintess value.
Static Protected Attributes
static ThreadSafeRandom rand = new ThreadSafeRandom()
Random generator used for chromosoms' generation.
Additional Inherited Members
Properties inherited from AForge.Genetic.ChromosomeBase
double Fitness [get]
Chromosome's fintess value.
Properties inherited from AForge.Genetic.IChromosome
double Fitness [get]
Chromosome's fintess value.
Detailed Description
The chromosome represents a Gene Expression, which is used for different tasks of Genetic Expression Programming (GEP).
This type of chromosome represents combination of ideas taken from Genetic Algorithms (GA), where chromosomes are linear structures of fixed length, and Genetic Programming (GP), where chromosomes are expression trees. The GEP chromosome is also a fixed length linear structure, but with some additional features which make it possible to generate valid expression tree from any GEP chromosome.
The theory of Gene Expression Programming is well described in the next paper: Ferreira, C., 2001. Gene Expression Programming: A New Adaptive Algorithm for Solving Problems. Complex Systems, Vol. 13, issue 2: 87-129. A copy of the paper may be obtained on the gene expression programming web site.
Constructor & Destructor Documentation
GEPChromosome() [1/2]
AForge.Genetic.GEPChromosome.GEPChromosome (IGPGene ancestor, int headLength) inline
Initializes a new instance of the GEPChromosome class.
Parameters
ancestor A gene, which is used as generator for the genetic tree.
headLength Length of GEP chromosome's head (see headLength).
This constructor creates a randomly generated GEP chromosome, which has all genes of the same type and properties as the specified ancestor .
References AForge.Genetic.GEPChromosome.Generate(), AForge.Genetic.GEPChromosome.genes, AForge.Genetic.GEPChromosome.headLength, AForge.Genetic.GEPChromosome.length, and AForge.Genetic.IGPGene.MaxArgumentsCount.
Referenced by AForge.Genetic.GEPChromosome.Clone(), AForge.Genetic.GEPChromosome.CreateNew(), and AForge.Genetic.GEPChromosome.Crossover().
GEPChromosome() [2/2]
AForge.Genetic.GEPChromosome.GEPChromosome (GEPChromosome source) inline protected
Initializes a new instance of the GEPChromosome class.
Parameters
source Source GEP chromosome to clone from.
References AForge.Genetic.IGPGene.Clone(), AForge.Genetic.ChromosomeBase.fitness, AForge.Genetic.GEPChromosome.genes, AForge.Genetic.GEPChromosome.headLength, and AForge.Genetic.GEPChromosome.length.
Member Function Documentation
ToString()
override string AForge.Genetic.GEPChromosome.ToString () inline
Get string representation of the chromosome by providing its expression in reverse polish notation (postfix notation).
Returns
Returns string representation of the expression represented by the GEP chromosome.
References AForge.Genetic.GEPChromosome.GetTree(), and AForge.Genetic.GPTreeNode.ToString().
ToStringNative()
string AForge.Genetic.GEPChromosome.ToStringNative () inline
Get string representation of the chromosome.
Returns
Returns the chromosome in native linear representation.
<note>The method is used for debugging mostly.</note>
References AForge.Genetic.GEPChromosome.genes.
Generate()
override void AForge.Genetic.GEPChromosome.Generate () inline virtual
Generate random chromosome value.
Regenerates chromosome's value using random number generator.
Implements AForge.Genetic.ChromosomeBase.
References AForge.Genetic.IGPGene.CreateNew(), AForge.Genetic.IGPGene.Generate(), AForge.Genetic.GEPChromosome.genes, AForge.Genetic.GEPChromosome.headLength, and AForge.Genetic.GEPChromosome.length.
Referenced by AForge.Genetic.GEPChromosome.GEPChromosome().
GetTree()
GPTreeNode AForge.Genetic.GEPChromosome.GetTree () inline protected
Get tree representation of the chromosome.
Returns
Returns expression's tree represented by the chromosome.
The method builds expression's tree for the native linear representation of the GEP chromosome.
References AForge.Genetic.IGPGene.ArgumentsCount, AForge.Genetic.GPTreeNode.Children, AForge.Genetic.GPTreeNode.Gene, AForge.Genetic.GEPChromosome.genes, and AForge.Genetic.GEPChromosome.length.
Referenced by AForge.Genetic.GEPChromosome.ToString().
CreateNew()
override IChromosome AForge.Genetic.GEPChromosome.CreateNew () inline virtual
Create new random chromosome with same parameters (factory method).
The method creates new chromosome of the same type, but randomly initialized. The method is useful as factory method for those classes, which work with chromosome's interface, but not with particular chromosome type.
Implements AForge.Genetic.ChromosomeBase.
References AForge.Genetic.GEPChromosome.Clone(), AForge.Genetic.GEPChromosome.genes, AForge.Genetic.GEPChromosome.GEPChromosome(), and AForge.Genetic.GEPChromosome.headLength.
Clone()
override IChromosome AForge.Genetic.GEPChromosome.Clone () inline virtual
Clone the chromosome.
Returns
Return's clone of the chromosome.
The method clones the chromosome returning the exact copy of it.
Implements AForge.Genetic.ChromosomeBase.
References AForge.Genetic.GEPChromosome.GEPChromosome().
Referenced by AForge.Genetic.GEPChromosome.CreateNew().
Mutate()
override void AForge.Genetic.GEPChromosome.Mutate () inline virtual
Mutation operator.
The method performs chromosome's mutation by calling on of the methods randomly: MutateGene, TransposeIS, TransposeRoot.
Implements AForge.Genetic.ChromosomeBase.
References AForge.Genetic.GEPChromosome.MutateGene(), AForge.ThreadSafeRandom.Next(), AForge.Genetic.GEPChromosome.rand, AForge.Genetic.GEPChromosome.TransposeIS(), and AForge.Genetic.GEPChromosome.TransposeRoot().
MutateGene()
void AForge.Genetic.GEPChromosome.MutateGene () inline protected
Usual gene mutation.
The method performs usual gene mutation by randomly changing randomly selected gene.
References AForge.Genetic.IGPGene.Generate(), AForge.Genetic.GEPChromosome.genes, AForge.Genetic.GEPChromosome.headLength, AForge.Genetic.GEPChromosome.length, AForge.ThreadSafeRandom.Next(), and AForge.Genetic.GEPChromosome.rand.
Referenced by AForge.Genetic.GEPChromosome.Mutate().
TransposeIS()
void AForge.Genetic.GEPChromosome.TransposeIS () inline protected
Transposition of IS elements (insertion sequence).
The method performs transposition of IS elements by copying randomly selected region of genes into chromosome's head (into randomly selected position). First gene of the chromosome's head is not affected - can not be selected as target point.
References AForge.Genetic.IGPGene.Clone(), AForge.Genetic.GEPChromosome.genes, AForge.Genetic.GEPChromosome.headLength, AForge.Genetic.GEPChromosome.length, AForge.ThreadSafeRandom.Next(), and AForge.Genetic.GEPChromosome.rand.
Referenced by AForge.Genetic.GEPChromosome.Mutate().
TransposeRoot()
void AForge.Genetic.GEPChromosome.TransposeRoot () inline protected
Root transposition.
The method performs root transposition of the GEP chromosome - inserting new root of the chromosome and shifting existing one. The method first of all randomly selects a function gene in chromosome's head - starting point of the sequence to put into chromosome's head. Then it randomly selects the length of the sequence making sure that the entire sequence is located within head. Once the starting point and the length of the sequence are known, it is copied into chromosome's head shifting existing elements in the head.
References AForge.Genetic.IGPGene.Clone(), AForge.Genetic.GEPChromosome.genes, AForge.Genetic.GEPChromosome.headLength, AForge.ThreadSafeRandom.Next(), and AForge.Genetic.GEPChromosome.rand.
Referenced by AForge.Genetic.GEPChromosome.Mutate().
Crossover()
override void AForge.Genetic.GEPChromosome.Crossover (IChromosome pair) inline virtual
Crossover operator.
Parameters
pair Pair chromosome to crossover with.
The method performs one-point or two-point crossover selecting them randomly with equal probability.
Implements AForge.Genetic.ChromosomeBase.
References AForge.Genetic.GEPChromosome.GEPChromosome(), AForge.ThreadSafeRandom.Next(), AForge.Genetic.GEPChromosome.rand, AForge.Genetic.GEPChromosome.RecombinationOnePoint(), and AForge.Genetic.GEPChromosome.RecombinationTwoPoint().
RecombinationOnePoint()
void AForge.Genetic.GEPChromosome.RecombinationOnePoint (GEPChromosome pair) inline
One-point recombination (crossover).
Parameters
pair Pair chromosome to crossover with.
References AForge.Genetic.GEPChromosome.genes, AForge.Genetic.GEPChromosome.length, AForge.ThreadSafeRandom.Next(), AForge.Genetic.GEPChromosome.rand, and AForge.Genetic.GEPChromosome.Recombine().
Referenced by AForge.Genetic.GEPChromosome.Crossover().
RecombinationTwoPoint()
void AForge.Genetic.GEPChromosome.RecombinationTwoPoint (GEPChromosome pair) inline
Two point recombination (crossover).
Parameters
pair Pair chromosome to crossover with.
References AForge.Genetic.GEPChromosome.genes, AForge.Genetic.GEPChromosome.length, AForge.ThreadSafeRandom.Next(), AForge.Genetic.GEPChromosome.rand, and AForge.Genetic.GEPChromosome.Recombine().
Referenced by AForge.Genetic.GEPChromosome.Crossover().
Recombine()
static void AForge.Genetic.GEPChromosome.Recombine (IGPGene[] src1, IGPGene[] src2, int point, int length) inline static protected
Swap parts of two chromosomes.
Parameters
src1 First chromosome participating in genes' interchange.
src2 Second chromosome participating in genes' interchange.
point Index of the first gene in the interchange sequence.
length Length of the interchange sequence - number of genes to interchange.
The method performs interchanging of genes between two chromosomes starting from the point position.
References AForge.Genetic.GEPChromosome.length.
Referenced by AForge.Genetic.GEPChromosome.RecombinationOnePoint(), and AForge.Genetic.GEPChromosome.RecombinationTwoPoint().
Member Data Documentation
headLength
int AForge.Genetic.GEPChromosome.headLength protected
Length of GEP chromosome's head.
GEP chromosome's head is a part of chromosome, which may contain both functions' and arguments' nodes. The rest of chromosome (tail) may contain only arguments' nodes.
Referenced by AForge.Genetic.GEPChromosome.CreateNew(), AForge.Genetic.GEPChromosome.Generate(), AForge.Genetic.GEPChromosome.GEPChromosome(), AForge.Genetic.GEPChromosome.MutateGene(), AForge.Genetic.GEPChromosome.TransposeIS(), and AForge.Genetic.GEPChromosome.TransposeRoot().
length
int AForge.Genetic.GEPChromosome.length protected
GEP chromosome's length.
<note>The variable keeps chromosome's length, but not expression length represented by the chromosome.</note>
Referenced by AForge.Genetic.GEPChromosome.Generate(), AForge.Genetic.GEPChromosome.GEPChromosome(), AForge.Genetic.GEPChromosome.GetTree(), AForge.Genetic.GEPChromosome.MutateGene(), AForge.Genetic.GEPChromosome.RecombinationOnePoint(), AForge.Genetic.GEPChromosome.RecombinationTwoPoint(), AForge.Genetic.GEPChromosome.Recombine(), and AForge.Genetic.GEPChromosome.TransposeIS().
genes
IGPGene [] AForge.Genetic.GEPChromosome.genes protected
Array of chromosome's genes.
Referenced by AForge.Genetic.GEPChromosome.CreateNew(), AForge.Genetic.GEPChromosome.Generate(), AForge.Genetic.GEPChromosome.GEPChromosome(), AForge.Genetic.GEPChromosome.GetTree(), AForge.Genetic.GEPChromosome.MutateGene(), AForge.Genetic.GEPChromosome.RecombinationOnePoint(), AForge.Genetic.GEPChromosome.RecombinationTwoPoint(), AForge.Genetic.GEPChromosome.ToStringNative(), AForge.Genetic.GEPChromosome.TransposeIS(), and AForge.Genetic.GEPChromosome.TransposeRoot().
rand
ThreadSafeRandom AForge.Genetic.GEPChromosome.rand = new ThreadSafeRandom() static protected
Random generator used for chromosoms' generation.
Referenced by AForge.Genetic.GEPChromosome.Crossover(), AForge.Genetic.GEPChromosome.Mutate(), AForge.Genetic.GEPChromosome.MutateGene(), AForge.Genetic.GEPChromosome.RecombinationOnePoint(), AForge.Genetic.GEPChromosome.RecombinationTwoPoint(), AForge.Genetic.GEPChromosome.TransposeIS(), and AForge.Genetic.GEPChromosome.TransposeRoot().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Genetic/Chromosomes/GP/GEPChromosome.cs