Doc: IGLib EXTENDED: SOMOrganizing.MainForm Class Reference
SOMOrganizing.MainForm Class Reference
Summary description for Form1.
Public Member Functions
MainForm ()
MainForm ()
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void generateButton_Click (object sender, System.EventArgs e)
void GeneratePoints ()
void pointsPanel_Paint (object sender, System.Windows.Forms.PaintEventArgs e)
void mapPanel_Paint (object sender, System.Windows.Forms.PaintEventArgs e)
void EnableControls (bool enable)
void showConnectionsCheck_CheckedChanged (object sender, System.EventArgs e)
void showInactiveCheck_CheckedChanged (object sender, System.EventArgs e)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void UpdateMap (DistanceNetwork network)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void generateButton_Click (object sender, System.EventArgs e)
void GeneratePoints ()
void pointsPanel_Paint (object sender, System.Windows.Forms.PaintEventArgs e)
void mapPanel_Paint (object sender, System.Windows.Forms.PaintEventArgs e)
void EnableControls (bool enable)
void showConnectionsCheck_CheckedChanged (object sender, System.EventArgs e)
void showInactiveCheck_CheckedChanged (object sender, System.EventArgs e)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void UpdateMap (DistanceNetwork network)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
delegate void SetTextCallback (System.Windows.Forms.Control control, string text)
void SetText (System.Windows.Forms.Control control, string text)
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void generateButton_Click (object sender, System.EventArgs e)
void GeneratePoints ()
void pointsPanel_Paint (object sender, System.Windows.Forms.PaintEventArgs e)
void mapPanel_Paint (object sender, System.Windows.Forms.PaintEventArgs e)
delegate void EnableCallback (bool enable)
void EnableControls (bool enable)
void showConnectionsCheck_CheckedChanged (object sender, System.EventArgs e)
void showInactiveCheck_CheckedChanged (object sender, System.EventArgs e)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void UpdateMap (DistanceNetwork network)
Static Private Member Functions
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
Private Attributes
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.Button generateButton
System.Windows.Forms.Panel pointsPanel
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.Panel mapPanel
System.Windows.Forms.CheckBox showConnectionsCheck
System.Windows.Forms.CheckBox showInactiveCheck
System.Windows.Forms.GroupBox groupBox3
System.Windows.Forms.Label label1
System.Windows.Forms.TextBox sizeBox
System.Windows.Forms.Label label2
System.Windows.Forms.Label label3
System.Windows.Forms.TextBox radiusBox
System.Windows.Forms.Label label4
System.Windows.Forms.TextBox rateBox
System.Windows.Forms.Label label5
System.Windows.Forms.TextBox iterationsBox
System.Windows.Forms.Label label6
System.Windows.Forms.Label label7
System.Windows.Forms.TextBox currentIterationBox
System.Windows.Forms.Label label8
System.Windows.Forms.Button stopButton
System.Windows.Forms.Button startButton
System.ComponentModel.Container components = null
Required designer variable.
int[,] points = new int[pointsCount, 2]
double[][] trainingSet = new double[pointsCount][]
int[,,] map
int networkSize = 15
int iterations = 500
double learningRate = 0.3
int learningRadius = 3
Random rand = new Random()
Thread workerThread = null
bool needToStop = false
volatile bool needToStop = false
Static Private Attributes
const int groupRadius = 20
const int pointsCount = 100
Detailed Description
Summary description for Form1.
Summary description for MainForm.
Constructor & Destructor Documentation
MainForm() [1/3]
SOMOrganizing.MainForm.MainForm () inline
References SOMOrganizing.MainForm.GeneratePoints(), SOMOrganizing.MainForm.InitializeComponent(), and SOMOrganizing.MainForm.UpdateSettings().
Referenced by SOMOrganizing.MainForm.Main().
MainForm() [2/3]
SOMOrganizing.MainForm.MainForm () inline
References SOMOrganizing.MainForm.GeneratePoints(), SOMOrganizing.MainForm.InitializeComponent(), and SOMOrganizing.MainForm.UpdateSettings().
MainForm() [3/3]
SOMOrganizing.MainForm.MainForm () inline
References SOMOrganizing.MainForm.GeneratePoints(), SOMOrganizing.MainForm.InitializeComponent(), and SOMOrganizing.MainForm.UpdateSettings().
Member Function Documentation
Dispose() [1/3]
override void SOMOrganizing.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References SOMOrganizing.MainForm.components.
InitializeComponent() [1/3]
void SOMOrganizing.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by SOMOrganizing.MainForm.MainForm().
Main() [1/3]
static void SOMOrganizing.MainForm.Main () inline static private
The main entry point for the application.
References SOMOrganizing.MainForm.MainForm().
MainForm_Closing() [1/3]
void SOMOrganizing.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References SOMOrganizing.MainForm.needToStop, and SOMOrganizing.MainForm.workerThread.
UpdateSettings() [1/3]
void SOMOrganizing.MainForm.UpdateSettings () inline private
References SOMOrganizing.MainForm.iterations, SOMOrganizing.MainForm.iterationsBox, SOMOrganizing.MainForm.learningRadius, SOMOrganizing.MainForm.learningRate, SOMOrganizing.MainForm.networkSize, SOMOrganizing.MainForm.radiusBox, SOMOrganizing.MainForm.rateBox, and SOMOrganizing.MainForm.sizeBox.
Referenced by SOMOrganizing.MainForm.MainForm(), and SOMOrganizing.MainForm.startButton_Click().
generateButton_Click() [1/3]
void SOMOrganizing.MainForm.generateButton_Click (object sender, System.EventArgs e) inline private
References SOMOrganizing.MainForm.GeneratePoints().
GeneratePoints() [1/3]
void SOMOrganizing.MainForm.GeneratePoints () inline private
References SOMOrganizing.MainForm.groupRadius, SOMOrganizing.MainForm.map, SOMOrganizing.MainForm.mapPanel, SOMOrganizing.MainForm.points, SOMOrganizing.MainForm.pointsCount, SOMOrganizing.MainForm.pointsPanel, and SOMOrganizing.MainForm.rand.
Referenced by SOMOrganizing.MainForm.generateButton_Click(), and SOMOrganizing.MainForm.MainForm().
pointsPanel_Paint() [1/3]
void SOMOrganizing.MainForm.pointsPanel_Paint (object sender, System.Windows.Forms.PaintEventArgs e) inline private
References SOMOrganizing.MainForm.points.
mapPanel_Paint() [1/3]
void SOMOrganizing.MainForm.mapPanel_Paint (object sender, System.Windows.Forms.PaintEventArgs e) inline private
References SOMOrganizing.MainForm.map, SOMOrganizing.MainForm.showConnectionsCheck, and SOMOrganizing.MainForm.showInactiveCheck.
EnableControls() [1/3]
void SOMOrganizing.MainForm.EnableControls (bool enable) inline private
References SOMOrganizing.MainForm.generateButton, SOMOrganizing.MainForm.iterationsBox, SOMOrganizing.MainForm.radiusBox, SOMOrganizing.MainForm.rateBox, SOMOrganizing.MainForm.sizeBox, SOMOrganizing.MainForm.startButton, and SOMOrganizing.MainForm.stopButton.
Referenced by SOMOrganizing.MainForm.EnableControls(), SOMOrganizing.MainForm.SearchSolution(), and SOMOrganizing.MainForm.startButton_Click().
showConnectionsCheck_CheckedChanged() [1/3]
void SOMOrganizing.MainForm.showConnectionsCheck_CheckedChanged (object sender, System.EventArgs e) inline private
References SOMOrganizing.MainForm.mapPanel.
showInactiveCheck_CheckedChanged() [1/3]
void SOMOrganizing.MainForm.showInactiveCheck_CheckedChanged (object sender, System.EventArgs e) inline private
References SOMOrganizing.MainForm.mapPanel.
startButton_Click() [1/3]
void SOMOrganizing.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References SOMOrganizing.MainForm.EnableControls(), SOMOrganizing.MainForm.iterations, SOMOrganizing.MainForm.iterationsBox, SOMOrganizing.MainForm.learningRadius, SOMOrganizing.MainForm.learningRate, SOMOrganizing.MainForm.needToStop, SOMOrganizing.MainForm.networkSize, SOMOrganizing.MainForm.points, SOMOrganizing.MainForm.pointsCount, SOMOrganizing.MainForm.radiusBox, SOMOrganizing.MainForm.rateBox, SOMOrganizing.MainForm.SearchSolution(), SOMOrganizing.MainForm.sizeBox, SOMOrganizing.MainForm.trainingSet, SOMOrganizing.MainForm.UpdateSettings(), and SOMOrganizing.MainForm.workerThread.
stopButton_Click() [1/3]
void SOMOrganizing.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References SOMOrganizing.MainForm.needToStop, and SOMOrganizing.MainForm.workerThread.
SearchSolution() [1/3]
void SOMOrganizing.MainForm.SearchSolution () inline private
References SOMOrganizing.MainForm.currentIterationBox, SOMOrganizing.MainForm.EnableControls(), SOMOrganizing.MainForm.iterations, AForge.Neuro.Learning.SOMLearning.LearningRadius, SOMOrganizing.MainForm.learningRadius, AForge.Neuro.Learning.SOMLearning.LearningRate, SOMOrganizing.MainForm.learningRate, SOMOrganizing.MainForm.map, SOMOrganizing.MainForm.needToStop, SOMOrganizing.MainForm.networkSize, SOMOrganizing.MainForm.pointsPanel, AForge.Neuro.Neuron.RandRange, AForge.Neuro.Learning.SOMLearning.RunEpoch(), SOMOrganizing.MainForm.trainingSet, and SOMOrganizing.MainForm.UpdateMap().
Referenced by SOMOrganizing.MainForm.startButton_Click().
UpdateMap() [1/3]
void SOMOrganizing.MainForm.UpdateMap (DistanceNetwork network) inline private
References AForge.Neuro.Network.Compute(), AForge.Neuro.DistanceNetwork.GetWinner(), SOMOrganizing.MainForm.map, SOMOrganizing.MainForm.mapPanel, SOMOrganizing.MainForm.networkSize, AForge.Neuro.Layer.NeuronsCount, SOMOrganizing.MainForm.pointsCount, and SOMOrganizing.MainForm.trainingSet.
Referenced by SOMOrganizing.MainForm.SearchSolution().
Dispose() [2/3]
override void SOMOrganizing.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References SOMOrganizing.MainForm.components.
InitializeComponent() [2/3]
void SOMOrganizing.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [2/3]
static void SOMOrganizing.MainForm.Main () inline static private
The main entry point for the application.
References SOMOrganizing.MainForm.MainForm().
MainForm_Closing() [2/3]
void SOMOrganizing.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References SOMOrganizing.MainForm.needToStop, and SOMOrganizing.MainForm.workerThread.
UpdateSettings() [2/3]
void SOMOrganizing.MainForm.UpdateSettings () inline private
References SOMOrganizing.MainForm.iterations, SOMOrganizing.MainForm.iterationsBox, SOMOrganizing.MainForm.learningRadius, SOMOrganizing.MainForm.learningRate, SOMOrganizing.MainForm.networkSize, SOMOrganizing.MainForm.radiusBox, SOMOrganizing.MainForm.rateBox, and SOMOrganizing.MainForm.sizeBox.
generateButton_Click() [2/3]
void SOMOrganizing.MainForm.generateButton_Click (object sender, System.EventArgs e) inline private
References SOMOrganizing.MainForm.GeneratePoints().
GeneratePoints() [2/3]
void SOMOrganizing.MainForm.GeneratePoints () inline private
References SOMOrganizing.MainForm.groupRadius, SOMOrganizing.MainForm.map, SOMOrganizing.MainForm.mapPanel, SOMOrganizing.MainForm.points, SOMOrganizing.MainForm.pointsCount, SOMOrganizing.MainForm.pointsPanel, and SOMOrganizing.MainForm.rand.
pointsPanel_Paint() [2/3]
void SOMOrganizing.MainForm.pointsPanel_Paint (object sender, System.Windows.Forms.PaintEventArgs e) inline private
References SOMOrganizing.MainForm.points.
mapPanel_Paint() [2/3]
void SOMOrganizing.MainForm.mapPanel_Paint (object sender, System.Windows.Forms.PaintEventArgs e) inline private
References SOMOrganizing.MainForm.map, SOMOrganizing.MainForm.showConnectionsCheck, and SOMOrganizing.MainForm.showInactiveCheck.
EnableControls() [2/3]
void SOMOrganizing.MainForm.EnableControls (bool enable) inline private
References SOMOrganizing.MainForm.generateButton, SOMOrganizing.MainForm.iterationsBox, SOMOrganizing.MainForm.radiusBox, SOMOrganizing.MainForm.rateBox, SOMOrganizing.MainForm.sizeBox, SOMOrganizing.MainForm.startButton, and SOMOrganizing.MainForm.stopButton.
showConnectionsCheck_CheckedChanged() [2/3]
void SOMOrganizing.MainForm.showConnectionsCheck_CheckedChanged (object sender, System.EventArgs e) inline private
References SOMOrganizing.MainForm.mapPanel.
showInactiveCheck_CheckedChanged() [2/3]
void SOMOrganizing.MainForm.showInactiveCheck_CheckedChanged (object sender, System.EventArgs e) inline private
References SOMOrganizing.MainForm.mapPanel.
startButton_Click() [2/3]
void SOMOrganizing.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References SOMOrganizing.MainForm.EnableControls(), SOMOrganizing.MainForm.iterations, SOMOrganizing.MainForm.iterationsBox, SOMOrganizing.MainForm.learningRadius, SOMOrganizing.MainForm.learningRate, SOMOrganizing.MainForm.needToStop, SOMOrganizing.MainForm.networkSize, SOMOrganizing.MainForm.points, SOMOrganizing.MainForm.pointsCount, SOMOrganizing.MainForm.radiusBox, SOMOrganizing.MainForm.rateBox, SOMOrganizing.MainForm.SearchSolution(), SOMOrganizing.MainForm.sizeBox, SOMOrganizing.MainForm.trainingSet, SOMOrganizing.MainForm.UpdateSettings(), and SOMOrganizing.MainForm.workerThread.
stopButton_Click() [2/3]
void SOMOrganizing.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References SOMOrganizing.MainForm.needToStop, and SOMOrganizing.MainForm.workerThread.
SearchSolution() [2/3]
void SOMOrganizing.MainForm.SearchSolution () inline private
References SOMOrganizing.MainForm.currentIterationBox, SOMOrganizing.MainForm.EnableControls(), SOMOrganizing.MainForm.iterations, AForge.Neuro.Learning.SOMLearning.LearningRadius, SOMOrganizing.MainForm.learningRadius, AForge.Neuro.Learning.SOMLearning.LearningRate, SOMOrganizing.MainForm.learningRate, SOMOrganizing.MainForm.map, SOMOrganizing.MainForm.needToStop, SOMOrganizing.MainForm.networkSize, SOMOrganizing.MainForm.pointsPanel, AForge.Neuro.Neuron.RandRange, AForge.Neuro.Learning.SOMLearning.RunEpoch(), SOMOrganizing.MainForm.trainingSet, and SOMOrganizing.MainForm.UpdateMap().
UpdateMap() [2/3]
void SOMOrganizing.MainForm.UpdateMap (DistanceNetwork network) inline private
References AForge.Neuro.Network.Compute(), AForge.Neuro.DistanceNetwork.GetWinner(), SOMOrganizing.MainForm.map, SOMOrganizing.MainForm.mapPanel, SOMOrganizing.MainForm.networkSize, AForge.Neuro.Layer.NeuronsCount, SOMOrganizing.MainForm.pointsCount, and SOMOrganizing.MainForm.trainingSet.
Dispose() [3/3]
override void SOMOrganizing.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References SOMOrganizing.MainForm.components.
InitializeComponent() [3/3]
void SOMOrganizing.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [3/3]
static void SOMOrganizing.MainForm.Main () inline static private
The main entry point for the application.
References SOMOrganizing.MainForm.MainForm().
SetTextCallback()
delegate void SOMOrganizing.MainForm.SetTextCallback (System.Windows.Forms.Control control, string text) private
Referenced by SOMOrganizing.MainForm.SetText().
SetText()
void SOMOrganizing.MainForm.SetText (System.Windows.Forms.Control control, string text) inline private
References SOMOrganizing.MainForm.SetTextCallback().
Referenced by SOMOrganizing.MainForm.SearchSolution().
MainForm_Closing() [3/3]
void SOMOrganizing.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References SOMOrganizing.MainForm.needToStop, and SOMOrganizing.MainForm.workerThread.
UpdateSettings() [3/3]
void SOMOrganizing.MainForm.UpdateSettings () inline private
References SOMOrganizing.MainForm.iterations, SOMOrganizing.MainForm.iterationsBox, SOMOrganizing.MainForm.learningRadius, SOMOrganizing.MainForm.learningRate, SOMOrganizing.MainForm.networkSize, SOMOrganizing.MainForm.radiusBox, SOMOrganizing.MainForm.rateBox, and SOMOrganizing.MainForm.sizeBox.
generateButton_Click() [3/3]
void SOMOrganizing.MainForm.generateButton_Click (object sender, System.EventArgs e) inline private
References SOMOrganizing.MainForm.GeneratePoints().
GeneratePoints() [3/3]
void SOMOrganizing.MainForm.GeneratePoints () inline private
References SOMOrganizing.MainForm.groupRadius, SOMOrganizing.MainForm.map, SOMOrganizing.MainForm.mapPanel, SOMOrganizing.MainForm.points, SOMOrganizing.MainForm.pointsCount, SOMOrganizing.MainForm.pointsPanel, and SOMOrganizing.MainForm.rand.
pointsPanel_Paint() [3/3]
void SOMOrganizing.MainForm.pointsPanel_Paint (object sender, System.Windows.Forms.PaintEventArgs e) inline private
References SOMOrganizing.MainForm.points.
mapPanel_Paint() [3/3]
void SOMOrganizing.MainForm.mapPanel_Paint (object sender, System.Windows.Forms.PaintEventArgs e) inline private
References SOMOrganizing.MainForm.map, SOMOrganizing.MainForm.showConnectionsCheck, and SOMOrganizing.MainForm.showInactiveCheck.
EnableCallback()
delegate void SOMOrganizing.MainForm.EnableCallback (bool enable) private
Referenced by SOMOrganizing.MainForm.EnableControls().
EnableControls() [3/3]
void SOMOrganizing.MainForm.EnableControls (bool enable) inline private
References SOMOrganizing.MainForm.EnableCallback(), SOMOrganizing.MainForm.EnableControls(), SOMOrganizing.MainForm.generateButton, SOMOrganizing.MainForm.iterationsBox, SOMOrganizing.MainForm.radiusBox, SOMOrganizing.MainForm.rateBox, SOMOrganizing.MainForm.sizeBox, SOMOrganizing.MainForm.startButton, and SOMOrganizing.MainForm.stopButton.
showConnectionsCheck_CheckedChanged() [3/3]
void SOMOrganizing.MainForm.showConnectionsCheck_CheckedChanged (object sender, System.EventArgs e) inline private
References SOMOrganizing.MainForm.mapPanel.
showInactiveCheck_CheckedChanged() [3/3]
void SOMOrganizing.MainForm.showInactiveCheck_CheckedChanged (object sender, System.EventArgs e) inline private
References SOMOrganizing.MainForm.mapPanel.
startButton_Click() [3/3]
void SOMOrganizing.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References SOMOrganizing.MainForm.EnableControls(), SOMOrganizing.MainForm.iterations, SOMOrganizing.MainForm.iterationsBox, SOMOrganizing.MainForm.learningRadius, SOMOrganizing.MainForm.learningRate, SOMOrganizing.MainForm.needToStop, SOMOrganizing.MainForm.networkSize, SOMOrganizing.MainForm.points, SOMOrganizing.MainForm.pointsCount, SOMOrganizing.MainForm.radiusBox, SOMOrganizing.MainForm.rateBox, SOMOrganizing.MainForm.SearchSolution(), SOMOrganizing.MainForm.sizeBox, SOMOrganizing.MainForm.trainingSet, SOMOrganizing.MainForm.UpdateSettings(), and SOMOrganizing.MainForm.workerThread.
stopButton_Click() [3/3]
void SOMOrganizing.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References SOMOrganizing.MainForm.needToStop, and SOMOrganizing.MainForm.workerThread.
SearchSolution() [3/3]
void SOMOrganizing.MainForm.SearchSolution () inline private
References SOMOrganizing.MainForm.currentIterationBox, SOMOrganizing.MainForm.EnableControls(), SOMOrganizing.MainForm.iterations, AForge.Neuro.Learning.SOMLearning.LearningRadius, SOMOrganizing.MainForm.learningRadius, AForge.Neuro.Learning.SOMLearning.LearningRate, SOMOrganizing.MainForm.learningRate, SOMOrganizing.MainForm.map, SOMOrganizing.MainForm.needToStop, SOMOrganizing.MainForm.networkSize, SOMOrganizing.MainForm.pointsPanel, AForge.Neuro.Neuron.RandRange, AForge.Neuro.Learning.SOMLearning.RunEpoch(), SOMOrganizing.MainForm.SetText(), SOMOrganizing.MainForm.trainingSet, and SOMOrganizing.MainForm.UpdateMap().
UpdateMap() [3/3]
void SOMOrganizing.MainForm.UpdateMap (DistanceNetwork network) inline private
References AForge.Neuro.Network.Compute(), AForge.Neuro.DistanceNetwork.GetWinner(), AForge.Neuro.Network.Layers, SOMOrganizing.MainForm.map, SOMOrganizing.MainForm.mapPanel, SOMOrganizing.MainForm.networkSize, AForge.Neuro.Layer.Neurons, SOMOrganizing.MainForm.pointsCount, SOMOrganizing.MainForm.trainingSet, and AForge.Neuro.Neuron.Weights.
Member Data Documentation
groupBox1
System Windows Forms GroupBox SOMOrganizing.MainForm.groupBox1 private
generateButton
System Windows Forms Button SOMOrganizing.MainForm.generateButton private
Referenced by SOMOrganizing.MainForm.EnableControls().
pointsPanel
System Windows Forms Panel SOMOrganizing.MainForm.pointsPanel private
Referenced by SOMOrganizing.MainForm.GeneratePoints(), and SOMOrganizing.MainForm.SearchSolution().
groupBox2
System Windows Forms GroupBox SOMOrganizing.MainForm.groupBox2 private
mapPanel
System Windows Forms Panel SOMOrganizing.MainForm.mapPanel private
Referenced by SOMOrganizing.MainForm.GeneratePoints(), SOMOrganizing.MainForm.showConnectionsCheck_CheckedChanged(), SOMOrganizing.MainForm.showInactiveCheck_CheckedChanged(), and SOMOrganizing.MainForm.UpdateMap().
showConnectionsCheck
System Windows Forms CheckBox SOMOrganizing.MainForm.showConnectionsCheck private
Referenced by SOMOrganizing.MainForm.mapPanel_Paint().
showInactiveCheck
System Windows Forms CheckBox SOMOrganizing.MainForm.showInactiveCheck private
Referenced by SOMOrganizing.MainForm.mapPanel_Paint().
groupBox3
System Windows Forms GroupBox SOMOrganizing.MainForm.groupBox3 private
label1
System Windows Forms Label SOMOrganizing.MainForm.label1 private
sizeBox
System Windows Forms TextBox SOMOrganizing.MainForm.sizeBox private
Referenced by SOMOrganizing.MainForm.EnableControls(), SOMOrganizing.MainForm.startButton_Click(), and SOMOrganizing.MainForm.UpdateSettings().
label2
System Windows Forms Label SOMOrganizing.MainForm.label2 private
label3
System Windows Forms Label SOMOrganizing.MainForm.label3 private
radiusBox
System Windows Forms TextBox SOMOrganizing.MainForm.radiusBox private
Referenced by SOMOrganizing.MainForm.EnableControls(), SOMOrganizing.MainForm.startButton_Click(), and SOMOrganizing.MainForm.UpdateSettings().
label4
System Windows Forms Label SOMOrganizing.MainForm.label4 private
rateBox
System Windows Forms TextBox SOMOrganizing.MainForm.rateBox private
Referenced by SOMOrganizing.MainForm.EnableControls(), SOMOrganizing.MainForm.startButton_Click(), and SOMOrganizing.MainForm.UpdateSettings().
label5
System Windows Forms Label SOMOrganizing.MainForm.label5 private
iterationsBox
System Windows Forms TextBox SOMOrganizing.MainForm.iterationsBox private
Referenced by SOMOrganizing.MainForm.EnableControls(), SOMOrganizing.MainForm.startButton_Click(), and SOMOrganizing.MainForm.UpdateSettings().
label6
System Windows Forms Label SOMOrganizing.MainForm.label6 private
label7
System Windows Forms Label SOMOrganizing.MainForm.label7 private
currentIterationBox
System Windows Forms TextBox SOMOrganizing.MainForm.currentIterationBox private
Referenced by SOMOrganizing.MainForm.SearchSolution().
label8
System Windows Forms Label SOMOrganizing.MainForm.label8 private
stopButton
System Windows Forms Button SOMOrganizing.MainForm.stopButton private
Referenced by SOMOrganizing.MainForm.EnableControls().
startButton
System Windows Forms Button SOMOrganizing.MainForm.startButton private
Referenced by SOMOrganizing.MainForm.EnableControls().
components
System ComponentModel Container SOMOrganizing.MainForm.components = null private
Required designer variable.
Referenced by SOMOrganizing.MainForm.Dispose().
groupRadius
const int SOMOrganizing.MainForm.groupRadius = 20 static private
Referenced by SOMOrganizing.MainForm.GeneratePoints().
pointsCount
const int SOMOrganizing.MainForm.pointsCount = 100 static private
Referenced by SOMOrganizing.MainForm.GeneratePoints(), SOMOrganizing.MainForm.startButton_Click(), and SOMOrganizing.MainForm.UpdateMap().
points
int [,] SOMOrganizing.MainForm.points = new int[pointsCount, 2] private
Referenced by SOMOrganizing.MainForm.GeneratePoints(), SOMOrganizing.MainForm.pointsPanel_Paint(), and SOMOrganizing.MainForm.startButton_Click().
trainingSet
double [][] SOMOrganizing.MainForm.trainingSet = new double[pointsCount][] private
Referenced by SOMOrganizing.MainForm.SearchSolution(), SOMOrganizing.MainForm.startButton_Click(), and SOMOrganizing.MainForm.UpdateMap().
map
int [,,] SOMOrganizing.MainForm.map private
Referenced by SOMOrganizing.MainForm.GeneratePoints(), SOMOrganizing.MainForm.mapPanel_Paint(), SOMOrganizing.MainForm.SearchSolution(), and SOMOrganizing.MainForm.UpdateMap().
networkSize
int SOMOrganizing.MainForm.networkSize = 15 private
Referenced by SOMOrganizing.MainForm.SearchSolution(), SOMOrganizing.MainForm.startButton_Click(), SOMOrganizing.MainForm.UpdateMap(), and SOMOrganizing.MainForm.UpdateSettings().
iterations
int SOMOrganizing.MainForm.iterations = 500 private
Referenced by SOMOrganizing.MainForm.SearchSolution(), SOMOrganizing.MainForm.startButton_Click(), and SOMOrganizing.MainForm.UpdateSettings().
learningRate
double SOMOrganizing.MainForm.learningRate = 0.3 private
Referenced by SOMOrganizing.MainForm.SearchSolution(), SOMOrganizing.MainForm.startButton_Click(), and SOMOrganizing.MainForm.UpdateSettings().
learningRadius
int SOMOrganizing.MainForm.learningRadius = 3 private
Referenced by SOMOrganizing.MainForm.SearchSolution(), SOMOrganizing.MainForm.startButton_Click(), and SOMOrganizing.MainForm.UpdateSettings().
rand
Random SOMOrganizing.MainForm.rand = new Random() private
Referenced by SOMOrganizing.MainForm.GeneratePoints().
workerThread
Thread SOMOrganizing.MainForm.workerThread = null private
Referenced by SOMOrganizing.MainForm.MainForm_Closing(), SOMOrganizing.MainForm.startButton_Click(), and SOMOrganizing.MainForm.stopButton_Click().
needToStop [1/2]
bool SOMOrganizing.MainForm.needToStop = false private
Referenced by SOMOrganizing.MainForm.MainForm_Closing(), SOMOrganizing.MainForm.SearchSolution(), SOMOrganizing.MainForm.startButton_Click(), and SOMOrganizing.MainForm.stopButton_Click().
needToStop [2/2]
volatile bool SOMOrganizing.MainForm.needToStop = false private
The documentation for this class was generated from the following file:
shelldev/lib/external/neuralnetworks/neuro_src/Samples/Neuro/SOM/2DOrganizing/Backup/MainForm.cs