Doc: IGLib EXTENDED: IG.Forms.InputParametersControl Class Reference
IG.Forms.InputParametersControl Class Reference
Control for editing input parameter values.
Public Member Functions
InputParametersControl ()
DataGridView GetGridControl ()
Returns the DataGridView control that is used for setting values of the input parameters.
void CopyDataToGrid ()
Initializes contents of the DataGridView.
void ClearCells ()
Clears contents of all DataGridView cells.
void ClearDataGrid ()
Removes all the data from the DataGridView.
void ResetToDefault ()
void ResetToCenter ()
void SetValues (IVector values)
Sets the values of input parameters on the DataViewGrid to the elements of the specified vector.
void ShowContextMenuControl (object sender, MouseEventArgs e)
InputParametersControl ()
DataGridView GetGridControl ()
Returns the DataGridView control that is used for setting values of the input parameters.
void CopyDataToGrid ()
Initializes contents of the DataGridView.
void ClearCells ()
Clears contents of all DataGridView cells.
void ClearDataGrid ()
Removes all the data from the DataGridView.
void ResetToDefault ()
void ResetToCenter ()
void SetValues (IVector values)
Sets the values of input parameters on the DataViewGrid to the elements of the specified vector.
void ShowContextMenuControl (object sender, MouseEventArgs e)
InputParametersControl ()
DataGridView GetGridControl ()
Returns the DataGridView control that is used for setting values of the input parameters.
void CopyDataToGrid ()
Initializes contents of the DataGridView.
void ClearCells ()
Clears contents of all DataGridView cells.
void ClearDataGrid ()
Removes all the data from the DataGridView.
void ResetToDefault ()
void ResetToCenter ()
void SetValues (IVector values)
Sets the values of input parameters on the DataViewGrid to the elements of the specified vector.
void ShowContextMenuControl (object sender, MouseEventArgs e)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
int _colNumValue = 2
Vector _values
Properties
InputOutputDataDefiniton DataDefinition [get, set]
Data about input and output quantities of the manipulated functions or response.
int ColNumValue [get]
Number of DataGrid Column that contains the value.
int NumValues [get]
Current number of values, otained form the DataGridView.
IVector Values [get, protected set]
Vector of current values of input parameters as defined by the DadaGridView.
Private Member Functions
void InputParametersControl_MouseClick (object sender, MouseEventArgs e)
void dGridInputParam_MouseClick (object sender, MouseEventArgs e)
void btnResetDefault_Click (object sender, EventArgs e)
void btnResetCenter_Click (object sender, EventArgs e)
void resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e)
void resetToCenterToolStripMenuItem_Click (object sender, EventArgs e)
void dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InputParametersControl_MouseClick (object sender, MouseEventArgs e)
void dGridInputParam_MouseClick (object sender, MouseEventArgs e)
void btnResetDefault_Click (object sender, EventArgs e)
void btnResetCenter_Click (object sender, EventArgs e)
void resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e)
void resetToCenterToolStripMenuItem_Click (object sender, EventArgs e)
void dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InputParametersControl_MouseClick (object sender, MouseEventArgs e)
void dGridInputParam_MouseClick (object sender, MouseEventArgs e)
void btnResetDefault_Click (object sender, EventArgs e)
void btnResetCenter_Click (object sender, EventArgs e)
void resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e)
void resetToCenterToolStripMenuItem_Click (object sender, EventArgs e)
void dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
InputOutputDataDefiniton _dataDefinition
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.DataGridView dGridInputParam
System.Windows.Forms.Button btnResetDefault
System.Windows.Forms.Button btnResetCenter
System.Windows.Forms.ContextMenuStrip contextMenuControl
System.Windows.Forms.ToolStripMenuItem resetToDefaultToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem resetToCenterToolStripMenuItem
System.Windows.Forms.DataGridViewTextBoxColumn columnId
System.Windows.Forms.DataGridViewTextBoxColumn columnTitle
System.Windows.Forms.DataGridViewTextBoxColumn columnValue
Detailed Description
Control for editing input parameter values.
$A Igor Apr13 Mar16;
Constructor & Destructor Documentation
InputParametersControl() [1/3]
IG.Forms.InputParametersControl.InputParametersControl () inline
References IG.Forms.InputParametersControl.InitializeComponent().
InputParametersControl() [2/3]
IG.Forms.InputParametersControl.InputParametersControl () inline
References IG.Forms.InputParametersControl.InitializeComponent().
InputParametersControl() [3/3]
IG.Forms.InputParametersControl.InputParametersControl () inline
References IG.Forms.InputParametersControl.InitializeComponent().
Member Function Documentation
GetGridControl() [1/3]
DataGridView IG.Forms.InputParametersControl.GetGridControl () inline
Returns the DataGridView control that is used for setting values of the input parameters.
Returns
References IG.Forms.InputParametersControl.dGridInputParam.
CopyDataToGrid() [1/3]
void IG.Forms.InputParametersControl.CopyDataToGrid () inline
Initializes contents of the DataGridView.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Forms.InputParametersControl.DataDefinition, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Forms.InputParametersControl.dGridInputParam, IG.Num.InputOutputElementDefinition.ElementIndex, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, and IG.Num.InputOutputElementDefinition.Title.
Referenced by IG.Forms.InputParametersControl.ResetToCenter(), and IG.Forms.InputParametersControl.ResetToDefault().
ClearCells() [1/3]
void IG.Forms.InputParametersControl.ClearCells () inline
Clears contents of all DataGridView cells.
References IG.Forms.InputParametersControl.DataDefinition, IG.Forms.InputParametersControl.dGridInputParam, and IG.Num.InputOutputDataDefiniton.InputLength.
ClearDataGrid() [1/3]
void IG.Forms.InputParametersControl.ClearDataGrid () inline
Removes all the data from the DataGridView.
References IG.Forms.InputParametersControl.dGridInputParam.
ResetToDefault() [1/3]
void IG.Forms.InputParametersControl.ResetToDefault () inline
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Forms.InputParametersControl.ColNumValue, IG.Forms.InputParametersControl.CopyDataToGrid(), IG.Forms.InputParametersControl.DataDefinition, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Forms.InputParametersControl.dGridInputParam, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, and IG.Num.InputOutputElementDefinition.MinimalValue.
Referenced by IG.Forms.InputParametersControl.btnResetDefault_Click(), and IG.Forms.InputParametersControl.resetToDefaultToolStripMenuItem_Click().
ResetToCenter() [1/3]
void IG.Forms.InputParametersControl.ResetToCenter () inline
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Forms.InputParametersControl.ColNumValue, IG.Forms.InputParametersControl.CopyDataToGrid(), IG.Forms.InputParametersControl.DataDefinition, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Forms.InputParametersControl.dGridInputParam, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, and IG.Num.InputOutputElementDefinition.MinimalValue.
Referenced by IG.Forms.InputParametersControl.btnResetCenter_Click(), and IG.Forms.InputParametersControl.resetToCenterToolStripMenuItem_Click().
SetValues() [1/3]
void IG.Forms.InputParametersControl.SetValues (IVector values) inline
Sets the values of input parameters on the DataViewGrid to the elements of the specified vector.
Parameters
values Vectors defining the values to be set.
References IG.Forms.InputParametersControl.Values.
ShowContextMenuControl() [1/3]
void IG.Forms.InputParametersControl.ShowContextMenuControl (object sender, MouseEventArgs e) inline
References IG.Forms.InputParametersControl.contextMenuControl.
Referenced by IG.Forms.InputParametersControl.dGridInputParam_MouseClick(), and IG.Forms.InputParametersControl.InputParametersControl_MouseClick().
InputParametersControl_MouseClick() [1/3]
void IG.Forms.InputParametersControl.InputParametersControl_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Forms.InputParametersControl.ShowContextMenuControl().
dGridInputParam_MouseClick() [1/3]
void IG.Forms.InputParametersControl.dGridInputParam_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Forms.InputParametersControl.ShowContextMenuControl().
btnResetDefault_Click() [1/3]
void IG.Forms.InputParametersControl.btnResetDefault_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParametersControl.ResetToDefault().
Referenced by IG.Forms.InputParametersControl.InitializeComponent().
btnResetCenter_Click() [1/3]
void IG.Forms.InputParametersControl.btnResetCenter_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParametersControl.ResetToCenter().
Referenced by IG.Forms.InputParametersControl.InitializeComponent().
resetToDefaultToolStripMenuItem_Click() [1/3]
void IG.Forms.InputParametersControl.resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParametersControl.ResetToDefault().
resetToCenterToolStripMenuItem_Click() [1/3]
void IG.Forms.InputParametersControl.resetToCenterToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParametersControl.ResetToCenter().
dGridInputParam_CellValueChanged() [1/3]
void IG.Forms.InputParametersControl.dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e) inline private
References IG.Forms.InputParametersControl.btnResetDefault, and IG.Lib.Util.SleepSeconds().
Dispose() [1/3]
override void IG.Forms.InputParametersControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.InputParametersControl.components.
InitializeComponent() [1/3]
void IG.Forms.InputParametersControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.InputParametersControl.btnResetCenter, IG.Forms.InputParametersControl.btnResetCenter_Click(), IG.Forms.InputParametersControl.btnResetDefault, IG.Forms.InputParametersControl.btnResetDefault_Click(), IG.Forms.InputParametersControl.columnId, IG.Forms.InputParametersControl.columnTitle, IG.Forms.InputParametersControl.columnValue, IG.Forms.InputParametersControl.components, IG.Forms.InputParametersControl.contextMenuControl, IG.Forms.InputParametersControl.dGridInputParam, IG.Forms.InputParametersControl.groupBox1, IG.Forms.InputParametersControl.resetToCenterToolStripMenuItem, and IG.Forms.InputParametersControl.resetToDefaultToolStripMenuItem.
Referenced by IG.Forms.InputParametersControl.InputParametersControl().
GetGridControl() [2/3]
DataGridView IG.Forms.InputParametersControl.GetGridControl () inline
Returns the DataGridView control that is used for setting values of the input parameters.
Returns
References IG.Forms.InputParametersControl.dGridInputParam.
CopyDataToGrid() [2/3]
void IG.Forms.InputParametersControl.CopyDataToGrid () inline
Initializes contents of the DataGridView.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Forms.InputParametersControl.DataDefinition, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Forms.InputParametersControl.dGridInputParam, IG.Num.InputOutputElementDefinition.ElementIndex, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, and IG.Num.InputOutputElementDefinition.Title.
ClearCells() [2/3]
void IG.Forms.InputParametersControl.ClearCells () inline
Clears contents of all DataGridView cells.
References IG.Forms.InputParametersControl.DataDefinition, IG.Forms.InputParametersControl.dGridInputParam, and IG.Num.InputOutputDataDefiniton.InputLength.
ClearDataGrid() [2/3]
void IG.Forms.InputParametersControl.ClearDataGrid () inline
Removes all the data from the DataGridView.
References IG.Forms.InputParametersControl.dGridInputParam.
ResetToDefault() [2/3]
void IG.Forms.InputParametersControl.ResetToDefault () inline
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Forms.InputParametersControl.ColNumValue, IG.Forms.InputParametersControl.CopyDataToGrid(), IG.Forms.InputParametersControl.DataDefinition, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Forms.InputParametersControl.dGridInputParam, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, and IG.Num.InputOutputElementDefinition.MinimalValue.
ResetToCenter() [2/3]
void IG.Forms.InputParametersControl.ResetToCenter () inline
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Forms.InputParametersControl.ColNumValue, IG.Forms.InputParametersControl.CopyDataToGrid(), IG.Forms.InputParametersControl.DataDefinition, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Forms.InputParametersControl.dGridInputParam, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, and IG.Num.InputOutputElementDefinition.MinimalValue.
SetValues() [2/3]
void IG.Forms.InputParametersControl.SetValues (IVector values) inline
Sets the values of input parameters on the DataViewGrid to the elements of the specified vector.
Parameters
values Vectors defining the values to be set.
References IG.Forms.InputParametersControl.Values.
ShowContextMenuControl() [2/3]
void IG.Forms.InputParametersControl.ShowContextMenuControl (object sender, MouseEventArgs e) inline
References IG.Forms.InputParametersControl.contextMenuControl.
InputParametersControl_MouseClick() [2/3]
void IG.Forms.InputParametersControl.InputParametersControl_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Forms.InputParametersControl.ShowContextMenuControl().
dGridInputParam_MouseClick() [2/3]
void IG.Forms.InputParametersControl.dGridInputParam_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Forms.InputParametersControl.ShowContextMenuControl().
btnResetDefault_Click() [2/3]
void IG.Forms.InputParametersControl.btnResetDefault_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParametersControl.ResetToDefault().
btnResetCenter_Click() [2/3]
void IG.Forms.InputParametersControl.btnResetCenter_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParametersControl.ResetToCenter().
resetToDefaultToolStripMenuItem_Click() [2/3]
void IG.Forms.InputParametersControl.resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParametersControl.ResetToDefault().
resetToCenterToolStripMenuItem_Click() [2/3]
void IG.Forms.InputParametersControl.resetToCenterToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParametersControl.ResetToCenter().
dGridInputParam_CellValueChanged() [2/3]
void IG.Forms.InputParametersControl.dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e) inline private
References IG.Forms.InputParametersControl.btnResetDefault, and IG.Lib.Util.SleepSeconds().
Dispose() [2/3]
override void IG.Forms.InputParametersControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.InputParametersControl.components.
InitializeComponent() [2/3]
void IG.Forms.InputParametersControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.InputParametersControl.btnResetCenter, IG.Forms.InputParametersControl.btnResetCenter_Click(), IG.Forms.InputParametersControl.btnResetDefault, IG.Forms.InputParametersControl.btnResetDefault_Click(), IG.Forms.InputParametersControl.columnId, IG.Forms.InputParametersControl.columnTitle, IG.Forms.InputParametersControl.columnValue, IG.Forms.InputParametersControl.components, IG.Forms.InputParametersControl.contextMenuControl, IG.Forms.InputParametersControl.dGridInputParam, IG.Forms.InputParametersControl.groupBox1, IG.Forms.InputParametersControl.resetToCenterToolStripMenuItem, and IG.Forms.InputParametersControl.resetToDefaultToolStripMenuItem.
GetGridControl() [3/3]
DataGridView IG.Forms.InputParametersControl.GetGridControl () inline
Returns the DataGridView control that is used for setting values of the input parameters.
Returns
References IG.Forms.InputParametersControl.dGridInputParam.
CopyDataToGrid() [3/3]
void IG.Forms.InputParametersControl.CopyDataToGrid () inline
Initializes contents of the DataGridView.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Forms.InputParametersControl.DataDefinition, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Forms.InputParametersControl.dGridInputParam, IG.Num.InputOutputElementDefinition.ElementIndex, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, and IG.Num.InputOutputElementDefinition.Title.
ClearCells() [3/3]
void IG.Forms.InputParametersControl.ClearCells () inline
Clears contents of all DataGridView cells.
References IG.Forms.InputParametersControl.DataDefinition, IG.Forms.InputParametersControl.dGridInputParam, and IG.Num.InputOutputDataDefiniton.InputLength.
ClearDataGrid() [3/3]
void IG.Forms.InputParametersControl.ClearDataGrid () inline
Removes all the data from the DataGridView.
References IG.Forms.InputParametersControl.dGridInputParam.
ResetToDefault() [3/3]
void IG.Forms.InputParametersControl.ResetToDefault () inline
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Forms.InputParametersControl.ColNumValue, IG.Forms.InputParametersControl.CopyDataToGrid(), IG.Forms.InputParametersControl.DataDefinition, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Forms.InputParametersControl.dGridInputParam, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, and IG.Num.InputOutputElementDefinition.MinimalValue.
ResetToCenter() [3/3]
void IG.Forms.InputParametersControl.ResetToCenter () inline
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Forms.InputParametersControl.ColNumValue, IG.Forms.InputParametersControl.CopyDataToGrid(), IG.Forms.InputParametersControl.DataDefinition, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Forms.InputParametersControl.dGridInputParam, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, and IG.Num.InputOutputElementDefinition.MinimalValue.
SetValues() [3/3]
void IG.Forms.InputParametersControl.SetValues (IVector values) inline
Sets the values of input parameters on the DataViewGrid to the elements of the specified vector.
Parameters
values Vectors defining the values to be set.
References IG.Forms.InputParametersControl.Values.
ShowContextMenuControl() [3/3]
void IG.Forms.InputParametersControl.ShowContextMenuControl (object sender, MouseEventArgs e) inline
References IG.Forms.InputParametersControl.contextMenuControl.
InputParametersControl_MouseClick() [3/3]
void IG.Forms.InputParametersControl.InputParametersControl_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Forms.InputParametersControl.ShowContextMenuControl().
dGridInputParam_MouseClick() [3/3]
void IG.Forms.InputParametersControl.dGridInputParam_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Forms.InputParametersControl.ShowContextMenuControl().
btnResetDefault_Click() [3/3]
void IG.Forms.InputParametersControl.btnResetDefault_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParametersControl.ResetToDefault().
btnResetCenter_Click() [3/3]
void IG.Forms.InputParametersControl.btnResetCenter_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParametersControl.ResetToCenter().
resetToDefaultToolStripMenuItem_Click() [3/3]
void IG.Forms.InputParametersControl.resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParametersControl.ResetToDefault().
resetToCenterToolStripMenuItem_Click() [3/3]
void IG.Forms.InputParametersControl.resetToCenterToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.InputParametersControl.ResetToCenter().
dGridInputParam_CellValueChanged() [3/3]
void IG.Forms.InputParametersControl.dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e) inline private
References IG.Forms.InputParametersControl.btnResetDefault, and IG.Lib.Util.SleepSeconds().
Dispose() [3/3]
override void IG.Forms.InputParametersControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.InputParametersControl.components.
InitializeComponent() [3/3]
void IG.Forms.InputParametersControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.InputParametersControl.btnResetCenter, IG.Forms.InputParametersControl.btnResetCenter_Click(), IG.Forms.InputParametersControl.btnResetDefault, IG.Forms.InputParametersControl.btnResetDefault_Click(), IG.Forms.InputParametersControl.columnId, IG.Forms.InputParametersControl.columnTitle, IG.Forms.InputParametersControl.columnValue, IG.Forms.InputParametersControl.components, IG.Forms.InputParametersControl.contextMenuControl, IG.Forms.InputParametersControl.dGridInputParam, IG.Forms.InputParametersControl.groupBox1, IG.Forms.InputParametersControl.resetToCenterToolStripMenuItem, and IG.Forms.InputParametersControl.resetToDefaultToolStripMenuItem.
Member Data Documentation
_dataDefinition
InputOutputDataDefiniton IG.Forms.InputParametersControl._dataDefinition private
_colNumValue
int IG.Forms.InputParametersControl._colNumValue = 2 protected
_values
Vector IG.Forms.InputParametersControl._values protected
components
System ComponentModel IContainer IG.Forms.InputParametersControl.components = null private
Required designer variable.
Referenced by IG.Forms.InputParametersControl.Dispose(), and IG.Forms.InputParametersControl.InitializeComponent().
groupBox1
System Windows Forms GroupBox IG.Forms.InputParametersControl.groupBox1 private
Referenced by IG.Forms.InputParametersControl.InitializeComponent().
dGridInputParam
System Windows Forms DataGridView IG.Forms.InputParametersControl.dGridInputParam private
Referenced by IG.Forms.InputParametersControl.ClearCells(), IG.Forms.InputParametersControl.ClearDataGrid(), IG.Forms.InputParametersControl.CopyDataToGrid(), IG.Forms.InputParametersControl.GetGridControl(), IG.Forms.InputParametersControl.InitializeComponent(), IG.Forms.InputParametersControl.ResetToCenter(), and IG.Forms.InputParametersControl.ResetToDefault().
btnResetDefault
System Windows Forms Button IG.Forms.InputParametersControl.btnResetDefault private
Referenced by IG.Forms.InputParametersControl.dGridInputParam_CellValueChanged(), and IG.Forms.InputParametersControl.InitializeComponent().
btnResetCenter
System Windows Forms Button IG.Forms.InputParametersControl.btnResetCenter private
Referenced by IG.Forms.InputParametersControl.InitializeComponent().
contextMenuControl
System Windows Forms ContextMenuStrip IG.Forms.InputParametersControl.contextMenuControl private
Referenced by IG.Forms.InputParametersControl.InitializeComponent(), and IG.Forms.InputParametersControl.ShowContextMenuControl().
resetToDefaultToolStripMenuItem
System Windows Forms ToolStripMenuItem IG.Forms.InputParametersControl.resetToDefaultToolStripMenuItem private
Referenced by IG.Forms.InputParametersControl.InitializeComponent().
resetToCenterToolStripMenuItem
System Windows Forms ToolStripMenuItem IG.Forms.InputParametersControl.resetToCenterToolStripMenuItem private
Referenced by IG.Forms.InputParametersControl.InitializeComponent().
columnId
System Windows Forms DataGridViewTextBoxColumn IG.Forms.InputParametersControl.columnId private
Referenced by IG.Forms.InputParametersControl.InitializeComponent().
columnTitle
System Windows Forms DataGridViewTextBoxColumn IG.Forms.InputParametersControl.columnTitle private
Referenced by IG.Forms.InputParametersControl.InitializeComponent().
columnValue
System Windows Forms DataGridViewTextBoxColumn IG.Forms.InputParametersControl.columnValue private
Referenced by IG.Forms.InputParametersControl.InitializeComponent().
Property Documentation
DataDefinition
InputOutputDataDefiniton IG.Forms.InputParametersControl.DataDefinition get set
Data about input and output quantities of the manipulated functions or response.
Referenced by IG.Forms.InputParametersControl.ClearCells(), IG.Forms.InputParametersControl.CopyDataToGrid(), IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.InputParametersControl.ResetToCenter(), and IG.Forms.InputParametersControl.ResetToDefault().
ColNumValue
int IG.Forms.InputParametersControl.ColNumValue get
Number of DataGrid Column that contains the value.
Referenced by IG.Forms.InputParametersControl.ResetToCenter(), and IG.Forms.InputParametersControl.ResetToDefault().
NumValues
int IG.Forms.InputParametersControl.NumValues get
Current number of values, otained form the DataGridView.
Values
IVector IG.Forms.InputParametersControl.Values get protected set
Vector of current values of input parameters as defined by the DadaGridView.
Referenced by IG.Forms.InputParametersControl.SetValues().
The documentation for this class was generated from the following files:
iglib/extensions/iglibext/Forms/Numeric/FromNeural/Basic/InputParametersControl.cs
iglib/extensions/iglibext/Forms/Numeric/FromNeural/Basic/InputParametersControl.Designer.cs