Doc: IGLib EXTENDED: ShapeChecker.MainForm Class Reference
ShapeChecker.MainForm Class Reference
Public Member Functions
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void exitToolStripMenuItem_Click (object sender, EventArgs e)
void MainForm_Load (object sender, EventArgs e)
void openToolStripMenuItem_Click (object sender, EventArgs e)
void loadDemoImage1ToolStripMenuItem_Click (object sender, EventArgs e)
void loadDemoImage2ToolStripMenuItem_Click (object sender, EventArgs e)
void loadDemoImage3ToolStripMenuItem_Click (object sender, EventArgs e)
void loadDemoImage4ToolStripMenuItem_Click (object sender, EventArgs e)
void LoadDemo (string embeddedFileName)
void ProcessImage (Bitmap bitmap)
void splitContainer_Panel2_Resize (object sender, EventArgs e)
void UpdatePictureBoxPosition ()
System.Drawing.Point[] ToPointsArray (List< IntPoint > points)
void aboutToolStripMenuItem_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.PictureBox pictureBox
System.Windows.Forms.MenuStrip menuStrip
System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem openToolStripMenuItem
System.Windows.Forms.ToolStripSeparator toolStripMenuItem1
System.Windows.Forms.ToolStripMenuItem loadDemoImage1ToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem loadDemoImage2ToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem loadDemoImage3ToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem loadDemoImage4ToolStripMenuItem
System.Windows.Forms.ToolStripSeparator toolStripMenuItem2
System.Windows.Forms.OpenFileDialog openFileDialog
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.Label label1
System.Windows.Forms.Label label3
System.Windows.Forms.Label label4
System.Windows.Forms.Label label2
System.Windows.Forms.Label label5
System.Windows.Forms.Label label6
System.Windows.Forms.Label label7
System.Windows.Forms.Label label8
System.Windows.Forms.Label label9
System.Windows.Forms.Label label10
System.Windows.Forms.SplitContainer splitContainer
System.Windows.Forms.ToolTip toolTip
System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem
Constructor & Destructor Documentation
MainForm()
ShapeChecker.MainForm.MainForm () inline
References ShapeChecker.MainForm.InitializeComponent().
Member Function Documentation
exitToolStripMenuItem_Click()
void ShapeChecker.MainForm.exitToolStripMenuItem_Click (object sender, EventArgs e) inline private
Referenced by ShapeChecker.MainForm.InitializeComponent().
MainForm_Load()
void ShapeChecker.MainForm.MainForm_Load (object sender, EventArgs e) inline private
References ShapeChecker.MainForm.LoadDemo().
openToolStripMenuItem_Click()
void ShapeChecker.MainForm.openToolStripMenuItem_Click (object sender, EventArgs e) inline private
References ShapeChecker.MainForm.openFileDialog, and ShapeChecker.MainForm.ProcessImage().
Referenced by ShapeChecker.MainForm.InitializeComponent().
loadDemoImage1ToolStripMenuItem_Click()
void ShapeChecker.MainForm.loadDemoImage1ToolStripMenuItem_Click (object sender, EventArgs e) inline private
References ShapeChecker.MainForm.LoadDemo().
Referenced by ShapeChecker.MainForm.InitializeComponent().
loadDemoImage2ToolStripMenuItem_Click()
void ShapeChecker.MainForm.loadDemoImage2ToolStripMenuItem_Click (object sender, EventArgs e) inline private
References ShapeChecker.MainForm.LoadDemo().
Referenced by ShapeChecker.MainForm.InitializeComponent().
loadDemoImage3ToolStripMenuItem_Click()
void ShapeChecker.MainForm.loadDemoImage3ToolStripMenuItem_Click (object sender, EventArgs e) inline private
References ShapeChecker.MainForm.LoadDemo().
Referenced by ShapeChecker.MainForm.InitializeComponent().
loadDemoImage4ToolStripMenuItem_Click()
void ShapeChecker.MainForm.loadDemoImage4ToolStripMenuItem_Click (object sender, EventArgs e) inline private
References ShapeChecker.MainForm.LoadDemo().
Referenced by ShapeChecker.MainForm.InitializeComponent().
LoadDemo()
void ShapeChecker.MainForm.LoadDemo (string embeddedFileName) inline private
References ShapeChecker.MainForm.ProcessImage().
Referenced by ShapeChecker.MainForm.loadDemoImage1ToolStripMenuItem_Click(), ShapeChecker.MainForm.loadDemoImage2ToolStripMenuItem_Click(), ShapeChecker.MainForm.loadDemoImage3ToolStripMenuItem_Click(), ShapeChecker.MainForm.loadDemoImage4ToolStripMenuItem_Click(), and ShapeChecker.MainForm.MainForm_Load().
ProcessImage()
void ShapeChecker.MainForm.ProcessImage (Bitmap bitmap) inline private
References AForge.Imaging.Filters.BaseInPlacePartialFilter.ApplyInPlace(), AForge.Imaging.Filters.ColorFiltering.Blue, AForge.Math.Geometry.SimpleShapeChecker.CheckPolygonSubType(), AForge.Imaging.Filters.ColorFiltering.FillOutsideRange, AForge.Imaging.BlobCounterBase.FilterBlobs, AForge.Imaging.BlobCounterBase.GetBlobsEdgePoints(), AForge.Imaging.BlobCounterBase.GetObjectsInformation(), AForge.Imaging.Filters.ColorFiltering.Green, AForge.Math.Geometry.SimpleShapeChecker.IsCircle(), AForge.Math.Geometry.SimpleShapeChecker.IsConvexPolygon(), AForge.Imaging.BlobCounterBase.MinHeight, AForge.Imaging.BlobCounterBase.MinWidth, ShapeChecker.MainForm.pictureBox, AForge.Imaging.BlobCounterBase.ProcessImage(), AForge.Math.Geometry.Rectangle, AForge.Imaging.Filters.ColorFiltering.Red, ShapeChecker.MainForm.ToPointsArray(), and ShapeChecker.MainForm.UpdatePictureBoxPosition().
Referenced by ShapeChecker.MainForm.LoadDemo(), and ShapeChecker.MainForm.openToolStripMenuItem_Click().
splitContainer_Panel2_Resize()
void ShapeChecker.MainForm.splitContainer_Panel2_Resize (object sender, EventArgs e) inline private
References ShapeChecker.MainForm.UpdatePictureBoxPosition().
UpdatePictureBoxPosition()
void ShapeChecker.MainForm.UpdatePictureBoxPosition () inline private
References ShapeChecker.MainForm.pictureBox, AForge.Math.Geometry.Rectangle, AForge.Imaging.Size, and ShapeChecker.MainForm.splitContainer.
Referenced by ShapeChecker.MainForm.ProcessImage(), and ShapeChecker.MainForm.splitContainer_Panel2_Resize().
ToPointsArray()
System.Drawing.Point [] ShapeChecker.MainForm.ToPointsArray (List< IntPoint > points) inline private
Referenced by ShapeChecker.MainForm.ProcessImage().
aboutToolStripMenuItem_Click()
void ShapeChecker.MainForm.aboutToolStripMenuItem_Click (object sender, EventArgs e) inline private
Dispose()
override void ShapeChecker.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References ShapeChecker.MainForm.components.
InitializeComponent()
void ShapeChecker.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References ShapeChecker.MainForm.aboutToolStripMenuItem, ShapeChecker.MainForm.components, ShapeChecker.MainForm.exitToolStripMenuItem, ShapeChecker.MainForm.exitToolStripMenuItem_Click(), ShapeChecker.MainForm.fileToolStripMenuItem, ShapeChecker.MainForm.groupBox1, ShapeChecker.MainForm.helpToolStripMenuItem, ShapeChecker.MainForm.label1, ShapeChecker.MainForm.label10, ShapeChecker.MainForm.label2, ShapeChecker.MainForm.label3, ShapeChecker.MainForm.label4, ShapeChecker.MainForm.label5, ShapeChecker.MainForm.label6, ShapeChecker.MainForm.label7, ShapeChecker.MainForm.label8, ShapeChecker.MainForm.label9, ShapeChecker.MainForm.loadDemoImage1ToolStripMenuItem, ShapeChecker.MainForm.loadDemoImage1ToolStripMenuItem_Click(), ShapeChecker.MainForm.loadDemoImage2ToolStripMenuItem, ShapeChecker.MainForm.loadDemoImage2ToolStripMenuItem_Click(), ShapeChecker.MainForm.loadDemoImage3ToolStripMenuItem, ShapeChecker.MainForm.loadDemoImage3ToolStripMenuItem_Click(), ShapeChecker.MainForm.loadDemoImage4ToolStripMenuItem, ShapeChecker.MainForm.loadDemoImage4ToolStripMenuItem_Click(), ShapeChecker.MainForm.menuStrip, ShapeChecker.MainForm.openFileDialog, ShapeChecker.MainForm.openToolStripMenuItem, ShapeChecker.MainForm.openToolStripMenuItem_Click(), ShapeChecker.MainForm.pictureBox, ShapeChecker.MainForm.splitContainer, ShapeChecker.MainForm.toolStripMenuItem1, ShapeChecker.MainForm.toolStripMenuItem2, and ShapeChecker.MainForm.toolTip.
Referenced by ShapeChecker.MainForm.MainForm().
Member Data Documentation
components
System.ComponentModel.IContainer ShapeChecker.MainForm.components = null private
Required designer variable.
Referenced by ShapeChecker.MainForm.Dispose(), and ShapeChecker.MainForm.InitializeComponent().
pictureBox
System.Windows.Forms.PictureBox ShapeChecker.MainForm.pictureBox private
Referenced by ShapeChecker.MainForm.InitializeComponent(), ShapeChecker.MainForm.ProcessImage(), and ShapeChecker.MainForm.UpdatePictureBoxPosition().
menuStrip
System.Windows.Forms.MenuStrip ShapeChecker.MainForm.menuStrip private
Referenced by ShapeChecker.MainForm.InitializeComponent().
fileToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem ShapeChecker.MainForm.fileToolStripMenuItem private
Referenced by ShapeChecker.MainForm.InitializeComponent().
exitToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem ShapeChecker.MainForm.exitToolStripMenuItem private
Referenced by ShapeChecker.MainForm.InitializeComponent().
openToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem ShapeChecker.MainForm.openToolStripMenuItem private
Referenced by ShapeChecker.MainForm.InitializeComponent().
toolStripMenuItem1
System.Windows.Forms.ToolStripSeparator ShapeChecker.MainForm.toolStripMenuItem1 private
Referenced by ShapeChecker.MainForm.InitializeComponent().
loadDemoImage1ToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem ShapeChecker.MainForm.loadDemoImage1ToolStripMenuItem private
Referenced by ShapeChecker.MainForm.InitializeComponent().
loadDemoImage2ToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem ShapeChecker.MainForm.loadDemoImage2ToolStripMenuItem private
Referenced by ShapeChecker.MainForm.InitializeComponent().
loadDemoImage3ToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem ShapeChecker.MainForm.loadDemoImage3ToolStripMenuItem private
Referenced by ShapeChecker.MainForm.InitializeComponent().
loadDemoImage4ToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem ShapeChecker.MainForm.loadDemoImage4ToolStripMenuItem private
Referenced by ShapeChecker.MainForm.InitializeComponent().
toolStripMenuItem2
System.Windows.Forms.ToolStripSeparator ShapeChecker.MainForm.toolStripMenuItem2 private
Referenced by ShapeChecker.MainForm.InitializeComponent().
openFileDialog
System.Windows.Forms.OpenFileDialog ShapeChecker.MainForm.openFileDialog private
Referenced by ShapeChecker.MainForm.InitializeComponent(), and ShapeChecker.MainForm.openToolStripMenuItem_Click().
groupBox1
System.Windows.Forms.GroupBox ShapeChecker.MainForm.groupBox1 private
Referenced by ShapeChecker.MainForm.InitializeComponent().
label1
System.Windows.Forms.Label ShapeChecker.MainForm.label1 private
Referenced by ShapeChecker.MainForm.InitializeComponent().
label3
System.Windows.Forms.Label ShapeChecker.MainForm.label3 private
Referenced by ShapeChecker.MainForm.InitializeComponent().
label4
System.Windows.Forms.Label ShapeChecker.MainForm.label4 private
Referenced by ShapeChecker.MainForm.InitializeComponent().
label2
System.Windows.Forms.Label ShapeChecker.MainForm.label2 private
Referenced by ShapeChecker.MainForm.InitializeComponent().
label5
System.Windows.Forms.Label ShapeChecker.MainForm.label5 private
Referenced by ShapeChecker.MainForm.InitializeComponent().
label6
System.Windows.Forms.Label ShapeChecker.MainForm.label6 private
Referenced by ShapeChecker.MainForm.InitializeComponent().
label7
System.Windows.Forms.Label ShapeChecker.MainForm.label7 private
Referenced by ShapeChecker.MainForm.InitializeComponent().
label8
System.Windows.Forms.Label ShapeChecker.MainForm.label8 private
Referenced by ShapeChecker.MainForm.InitializeComponent().
label9
System.Windows.Forms.Label ShapeChecker.MainForm.label9 private
Referenced by ShapeChecker.MainForm.InitializeComponent().
label10
System.Windows.Forms.Label ShapeChecker.MainForm.label10 private
Referenced by ShapeChecker.MainForm.InitializeComponent().
splitContainer
System.Windows.Forms.SplitContainer ShapeChecker.MainForm.splitContainer private
Referenced by ShapeChecker.MainForm.InitializeComponent(), and ShapeChecker.MainForm.UpdatePictureBoxPosition().
toolTip
System.Windows.Forms.ToolTip ShapeChecker.MainForm.toolTip private
Referenced by ShapeChecker.MainForm.InitializeComponent().
helpToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem ShapeChecker.MainForm.helpToolStripMenuItem private
Referenced by ShapeChecker.MainForm.InitializeComponent().
aboutToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem ShapeChecker.MainForm.aboutToolStripMenuItem private
Referenced by ShapeChecker.MainForm.InitializeComponent().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Imaging/ShapeChecker/MainForm.cs
shelldev/lib_ann/aforge.net/Samples/Imaging/ShapeChecker/MainForm.Designer.cs