Doc: IGLib EXTENDED: NUnit.Framework.Attributes.ValueSourceTests Class Reference
NUnit.Framework.Attributes.ValueSourceTests Class Reference
Classes
class DivideDataProvider
class ValueProvider
Public Member Functions
void ValueSourceCanBeStaticProperty ([ValueSource("StaticProperty")] string source)
void ValueSourceMayNotBeInstanceProperty ()
void MethodWithValueSourceInstanceProperty ([ValueSource("InstanceProperty")] string source)
void ValueSourceCanBeStaticMethod ([ValueSource("StaticMethod")] string source)
void ValueSourceMayNotBeInstanceMethod ()
void MethodWithValueSourceInstanceMethod ([ValueSource("InstanceMethod")] string source)
void ValueSourceCanBeStaticField ([ValueSource("StaticField")] string source)
void ValueSourceMayNotBeInstanceField ()
void MethodWithValueSourceInstanceField ([ValueSource("InstanceField")] string source)
void MultipleArguments ([ValueSource("Numerators")] int n, [ValueSource("Denominators")] int d, [ValueSource("Quotients")] int q)
void ValueSourceMayBeInAnotherClass ([ValueSource(typeof(DivideDataProvider), "Numerators")] int n, [ValueSource(typeof(DivideDataProvider), "Denominators")] int d, [ValueSource(typeof(DivideDataProvider), "Quotients")] int q)
void ValueSourceMayBeGeneric ([ValueSourceAttribute(typeof(ValueProvider), "IntegerProvider")] int val)
Properties
static IEnumerable StaticProperty [get]
IEnumerable InstanceProperty [get]
Private Member Functions
IEnumerable InstanceMethod ()
Static Private Member Functions
static IEnumerable StaticMethod ()
Member Function Documentation
ValueSourceCanBeStaticProperty()
void NUnit.Framework.Attributes.ValueSourceTests.ValueSourceCanBeStaticProperty ([ValueSource("StaticProperty")] string source) inline
References NUnit.Framework.Assert.AreEqual().
ValueSourceMayNotBeInstanceProperty()
void NUnit.Framework.Attributes.ValueSourceTests.ValueSourceMayNotBeInstanceProperty () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.NotRunnable, NUnit.TestUtilities.TestBuilder.RunParameterizedMethodSuite(), and NUnit.Framework.Assert.That().
MethodWithValueSourceInstanceProperty()
void NUnit.Framework.Attributes.ValueSourceTests.MethodWithValueSourceInstanceProperty ([ValueSource("InstanceProperty")] string source) inline
References NUnit.Framework.Assert.AreEqual().
ValueSourceCanBeStaticMethod()
void NUnit.Framework.Attributes.ValueSourceTests.ValueSourceCanBeStaticMethod ([ValueSource("StaticMethod")] string source) inline
References NUnit.Framework.Assert.AreEqual().
StaticMethod()
static IEnumerable NUnit.Framework.Attributes.ValueSourceTests.StaticMethod () inline static private
ValueSourceMayNotBeInstanceMethod()
void NUnit.Framework.Attributes.ValueSourceTests.ValueSourceMayNotBeInstanceMethod () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.NotRunnable, NUnit.TestUtilities.TestBuilder.RunParameterizedMethodSuite(), and NUnit.Framework.Assert.That().
MethodWithValueSourceInstanceMethod()
void NUnit.Framework.Attributes.ValueSourceTests.MethodWithValueSourceInstanceMethod ([ValueSource("InstanceMethod")] string source) inline
References NUnit.Framework.Assert.AreEqual().
InstanceMethod()
IEnumerable NUnit.Framework.Attributes.ValueSourceTests.InstanceMethod () inline private
ValueSourceCanBeStaticField()
void NUnit.Framework.Attributes.ValueSourceTests.ValueSourceCanBeStaticField ([ValueSource("StaticField")] string source) inline
References NUnit.Framework.Assert.AreEqual().
ValueSourceMayNotBeInstanceField()
void NUnit.Framework.Attributes.ValueSourceTests.ValueSourceMayNotBeInstanceField () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.NotRunnable, NUnit.TestUtilities.TestBuilder.RunParameterizedMethodSuite(), and NUnit.Framework.Assert.That().
MethodWithValueSourceInstanceField()
void NUnit.Framework.Attributes.ValueSourceTests.MethodWithValueSourceInstanceField ([ValueSource("InstanceField")] string source) inline
References NUnit.Framework.Assert.AreEqual().
MultipleArguments()
void NUnit.Framework.Attributes.ValueSourceTests.MultipleArguments ([ValueSource("Numerators")] int n, [ValueSource("Denominators")] int d, [ValueSource("Quotients")] int q) inline
References NUnit.Framework.Assert.AreEqual().
ValueSourceMayBeInAnotherClass()
void NUnit.Framework.Attributes.ValueSourceTests.ValueSourceMayBeInAnotherClass ([ValueSource(typeof(DivideDataProvider), "Numerators")] int n, [ValueSource(typeof(DivideDataProvider), "Denominators")] int d, [ValueSource(typeof(DivideDataProvider), "Quotients")] int q) inline
References NUnit.Framework.Assert.AreEqual().
ValueSourceMayBeGeneric()
void NUnit.Framework.Attributes.ValueSourceTests.ValueSourceMayBeGeneric ([ValueSourceAttribute(typeof(ValueProvider), "IntegerProvider")] int val) inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
Property Documentation
StaticProperty
IEnumerable NUnit.Framework.Attributes.ValueSourceTests.StaticProperty static get private
InstanceProperty
IEnumerable NUnit.Framework.Attributes.ValueSourceTests.InstanceProperty get private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/ValueSourceTests.cs