Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAMC3 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAMC3 Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAMC3 ()
double Run (double A, double B)
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAMC3 is intended to force A and B to be stored prior to doing the addition of A and B , for use in situations where optimizers might hold one of these in a register.
/summary>
Constructor & Destructor Documentation
DLAMC3()
DotNumerics.LinearAlgebra.CSLapack.DLAMC3.DLAMC3 () inline
Member Function Documentation
Run()
double DotNumerics.LinearAlgebra.CSLapack.DLAMC3.Run (double A, double B) inline
Purpose
DLAMC3 is intended to force A and B to be stored prior to doing the addition of A and B , for use in situations where optimizers might hold one of these in a register.
/summary>
Parameters
A (input) DOUBLE PRECISION /param>
Parameters
B (input) DOUBLE PRECISION The values A and B. /param>
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED9.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD8.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED3.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD3.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALS0.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMC1.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMC2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMC4.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAMC5.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlamch.cs