Doc: IGLib EXTENDED: AForge.Imaging.Filters.LevelsLinear16bpp Class Reference
AForge.Imaging.Filters.LevelsLinear16bpp Class Reference
Linear correction of RGB channels for images, which have 16 bpp planes (16 bit gray images or 48/64 bit colour images).
Public Member Functions
LevelsLinear16bpp ()
Initializes a new instance of the LevelsLinear class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image, Rectangle rect)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
IntRange InRed [get, set]
Red component's input range.
IntRange InGreen [get, set]
Green component's input range.
IntRange InBlue [get, set]
Blue component's input range.
IntRange InGray [get, set]
Gray component's input range.
IntRange Input [set]
Input range for RGB components.
IntRange OutRed [get, set]
Red component's output range.
IntRange OutGreen [get, set]
Green component's output range.
IntRange OutBlue [get, set]
Blue component's output range.
IntRange OutGray [get, set]
Gray component's output range.
IntRange Output [set]
Output range for RGB components.
Properties inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Member Functions
void CalculateMap (IntRange inRange, IntRange outRange, ushort[] map)
Calculate conversion map.
Private Attributes
IntRange inRed = new IntRange(0, 65535)
IntRange inGreen = new IntRange(0, 65535)
IntRange inBlue = new IntRange(0, 65535)
IntRange outRed = new IntRange(0, 65535)
IntRange outGreen = new IntRange(0, 65535)
IntRange outBlue = new IntRange(0, 65535)
ushort[] mapRed = new ushort[65536]
ushort[] mapGreen = new ushort[65536]
ushort[] mapBlue = new ushort[65536]
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Linear correction of RGB channels for images, which have 16 bpp planes (16 bit gray images or 48/64 bit colour images).
The filter performs linear correction of RGB channels by mapping specified channels' input ranges to output ranges. This version of the filter processes only images with 16 bpp colour planes. See LevelsLinear for 8 bpp version.
The filter accepts 16 bpp grayscale and 48/64 bpp colour images for processing.
Sample usage:
// create filter
LevelsLinear16bpp filter = new LevelsLinear16bpp();
// set ranges
filter.InRed   = new IntRange(3000, 42000);
filter.InGreen = new IntRange(5000, 37500);
filter.InBlue  = new IntRange(1000, 60000);
// apply the filter
filter.ApplyInPlace(image);
See also
LevelsLinear
Constructor & Destructor Documentation
LevelsLinear16bpp()
AForge.Imaging.Filters.LevelsLinear16bpp.LevelsLinear16bpp () inline
Initializes a new instance of the LevelsLinear class.
References AForge.Imaging.Filters.LevelsLinear16bpp.CalculateMap(), AForge.Imaging.Filters.LevelsLinear16bpp.formatTranslations, AForge.Imaging.Filters.LevelsLinear16bpp.inBlue, AForge.Imaging.Filters.LevelsLinear16bpp.inGreen, AForge.Imaging.Filters.LevelsLinear16bpp.inRed, AForge.Imaging.Filters.LevelsLinear16bpp.mapBlue, AForge.Imaging.Filters.LevelsLinear16bpp.mapGreen, AForge.Imaging.Filters.LevelsLinear16bpp.mapRed, AForge.Imaging.Filters.LevelsLinear16bpp.outBlue, AForge.Imaging.Filters.LevelsLinear16bpp.outGreen, and AForge.Imaging.Filters.LevelsLinear16bpp.outRed.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.LevelsLinear16bpp.ProcessFilter (UnmanagedImage image, Rectangle rect) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
rect Image rectangle for processing by the filter.
Implements AForge.Imaging.Filters.BaseInPlacePartialFilter.
References AForge.Imaging.RGB.B, AForge.Imaging.RGB.G, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.Filters.LevelsLinear16bpp.mapBlue, AForge.Imaging.Filters.LevelsLinear16bpp.mapGreen, AForge.Imaging.Filters.LevelsLinear16bpp.mapRed, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, and AForge.Imaging.UnmanagedImage.Stride.
CalculateMap()
void AForge.Imaging.Filters.LevelsLinear16bpp.CalculateMap (IntRange inRange, IntRange outRange, ushort[] map) inline private
Calculate conversion map.
Parameters
inRange Input range.
outRange Output range.
map Conversion map.
References AForge.IntRange.Max, and AForge.IntRange.Min.
Referenced by AForge.Imaging.Filters.LevelsLinear16bpp.LevelsLinear16bpp().
Member Data Documentation
inRed
IntRange AForge.Imaging.Filters.LevelsLinear16bpp.inRed = new IntRange(0, 65535) private
Referenced by AForge.Imaging.Filters.LevelsLinear16bpp.LevelsLinear16bpp().
inGreen
IntRange AForge.Imaging.Filters.LevelsLinear16bpp.inGreen = new IntRange(0, 65535) private
Referenced by AForge.Imaging.Filters.LevelsLinear16bpp.LevelsLinear16bpp().
inBlue
IntRange AForge.Imaging.Filters.LevelsLinear16bpp.inBlue = new IntRange(0, 65535) private
Referenced by AForge.Imaging.Filters.LevelsLinear16bpp.LevelsLinear16bpp().
outRed
IntRange AForge.Imaging.Filters.LevelsLinear16bpp.outRed = new IntRange(0, 65535) private
Referenced by AForge.Imaging.Filters.LevelsLinear16bpp.LevelsLinear16bpp().
outGreen
IntRange AForge.Imaging.Filters.LevelsLinear16bpp.outGreen = new IntRange(0, 65535) private
Referenced by AForge.Imaging.Filters.LevelsLinear16bpp.LevelsLinear16bpp().
outBlue
IntRange AForge.Imaging.Filters.LevelsLinear16bpp.outBlue = new IntRange(0, 65535) private
Referenced by AForge.Imaging.Filters.LevelsLinear16bpp.LevelsLinear16bpp().
mapRed
ushort [] AForge.Imaging.Filters.LevelsLinear16bpp.mapRed = new ushort[65536] private
Referenced by AForge.Imaging.Filters.LevelsLinear16bpp.LevelsLinear16bpp(), and AForge.Imaging.Filters.LevelsLinear16bpp.ProcessFilter().
mapGreen
ushort [] AForge.Imaging.Filters.LevelsLinear16bpp.mapGreen = new ushort[65536] private
Referenced by AForge.Imaging.Filters.LevelsLinear16bpp.LevelsLinear16bpp(), and AForge.Imaging.Filters.LevelsLinear16bpp.ProcessFilter().
mapBlue
ushort [] AForge.Imaging.Filters.LevelsLinear16bpp.mapBlue = new ushort[65536] private
Referenced by AForge.Imaging.Filters.LevelsLinear16bpp.LevelsLinear16bpp(), and AForge.Imaging.Filters.LevelsLinear16bpp.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.LevelsLinear16bpp.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.LevelsLinear16bpp.LevelsLinear16bpp().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.LevelsLinear16bpp.FormatTranslations get
Format translations dictionary.
InRed
IntRange AForge.Imaging.Filters.LevelsLinear16bpp.InRed get set
Red component's input range.
InGreen
IntRange AForge.Imaging.Filters.LevelsLinear16bpp.InGreen get set
Green component's input range.
InBlue
IntRange AForge.Imaging.Filters.LevelsLinear16bpp.InBlue get set
Blue component's input range.
InGray
IntRange AForge.Imaging.Filters.LevelsLinear16bpp.InGray get set
Gray component's input range.
Input
IntRange AForge.Imaging.Filters.LevelsLinear16bpp.Input set
Input range for RGB components.
The property allows to set red, green and blue input ranges to the same value.
OutRed
IntRange AForge.Imaging.Filters.LevelsLinear16bpp.OutRed get set
Red component's output range.
OutGreen
IntRange AForge.Imaging.Filters.LevelsLinear16bpp.OutGreen get set
Green component's output range.
OutBlue
IntRange AForge.Imaging.Filters.LevelsLinear16bpp.OutBlue get set
Blue component's output range.
OutGray
IntRange AForge.Imaging.Filters.LevelsLinear16bpp.OutGray get set
Gray component's output range.
Output
IntRange AForge.Imaging.Filters.LevelsLinear16bpp.Output set
Output range for RGB components.
The property allows to set red, green and blue output ranges to the same value.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Color Filters/LevelsLinear16bpp.cs