Doc: IGLib EXTENDED: NUnit.Engine.Runners.AbstractTestRunner Class Reference
NUnit.Engine.Runners.AbstractTestRunner Class Reference abstract
AbstractTestRunner is the base class for all runners within the NUnit Engine. It implements the ITestRunner interface, which is used by clients of the engine and uses a Template pattern with abstract methods overridden by the derived runners.
Public Member Functions
AbstractTestRunner (IServiceLocator services, TestPackage package)
virtual void UnloadPackage ()
Unload any loaded TestPackage. Overridden in derived classes to take any necessary action.
abstract void StopRun (bool force)
Cancel the ongoing test run. If no test is running, the call is ignored.
TestEngineResult Explore (TestFilter filter)
Explores the TestPackage and returns information about the tests found. Loads the package if not done previously.
TestEngineResult Load ()
Loads the TestPackage for exploration or execution, saving the result.
TestEngineResult Reload ()
Reload the currently loaded test package, saving the result.
void Unload ()
Unload any loaded TestPackage.
int CountTestCases (TestFilter filter)
Count the test cases that would be run under the specified filter, loading the TestPackage if it is not already loaded.
TestEngineResult Run (ITestEventListener listener, TestFilter filter)
Run the tests in the TestPackage, loading the package if this has not already been done.
AsyncTestEngineResult RunAsync (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the loaded TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses.
void StartRun (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses. Loads the TestPackage if not already loaded.
void Dispose ()
Protected Member Functions
abstract TestEngineResult LoadPackage ()
Loads the TestPackage for exploration or execution.
virtual TestEngineResult ReloadPackage ()
Reload the currently loaded test package. Overridden in derived classes to take any additional action.
abstract TestEngineResult ExploreTests (TestFilter filter)
Explores a previously loaded TestPackage and returns information about the tests found.
abstract int CountTests (TestFilter filter)
Count the test cases that would be run under the specified filter.
abstract TestEngineResult RunTests (ITestEventListener listener, TestFilter filter)
Run the tests in the loaded TestPackage.
virtual AsyncTestEngineResult RunTestsAsync (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the loaded TestPackage, returning immediately. The tests are run asynchronously and the listener interface is notified as it progresses.
virtual void Dispose (bool disposing)
bool IsProjectPackage (TestPackage package)
Protected Attributes
bool _disposed = false
Static Protected Attributes
const string TEST_RUN_ELEMENT = "test-run"
Properties
IServiceLocator Services [get, private set]
Our Service Context
IProjectService ProjectService [get, private set]
ITestRunnerFactory TestRunnerFactory [get, private set]
TestPackage TestPackage [get, set]
The TestPackage for which this is the runner
TestEngineResult LoadResult [get, set]
The result of the last call to LoadPackage
bool IsPackageLoaded [get]
Gets an indicator of whether the package has been loaded.
Private Member Functions
void EnsurePackageIsLoaded ()
Detailed Description
AbstractTestRunner is the base class for all runners within the NUnit Engine. It implements the ITestRunner interface, which is used by clients of the engine and uses a Template pattern with abstract methods overridden by the derived runners.
Constructor & Destructor Documentation
AbstractTestRunner()
NUnit.Engine.Runners.AbstractTestRunner.AbstractTestRunner (IServiceLocator services, TestPackage package) inline
References NUnit.Engine.IServiceLocator.GetService(), NUnit.Engine.Runners.AbstractTestRunner.Services, and NUnit.Engine.Runners.AbstractTestRunner.TestRunnerFactory.
Member Function Documentation
LoadPackage()
abstract TestEngineResult NUnit.Engine.Runners.AbstractTestRunner.LoadPackage () protected pure virtual
Loads the TestPackage for exploration or execution.
Returns
A TestEngineResult.
Implemented in NUnit.Engine.Runners.ProcessRunner, NUnit.Engine.Runners.DirectTestRunner, NUnit.Engine.Runners.AggregatingTestRunner, NUnit.Engine.Runners.MasterTestRunner, and NUnit.Engine.Runners.TestDomainRunner.
Referenced by NUnit.Engine.Runners.AbstractTestRunner.EnsurePackageIsLoaded(), NUnit.Engine.Runners.AbstractTestRunner.Load(), and NUnit.Engine.Runners.AbstractTestRunner.ReloadPackage().
ReloadPackage()
virtual TestEngineResult NUnit.Engine.Runners.AbstractTestRunner.ReloadPackage () inline protected virtual
Reload the currently loaded test package. Overridden in derived classes to take any additional action.
Returns
A TestEngineResult.
References NUnit.Engine.Runners.AbstractTestRunner.LoadPackage().
Referenced by NUnit.Engine.Runners.AbstractTestRunner.Reload().
UnloadPackage()
virtual void NUnit.Engine.Runners.AbstractTestRunner.UnloadPackage () inline virtual
Unload any loaded TestPackage. Overridden in derived classes to take any necessary action.
Reimplemented in NUnit.Engine.Runners.ProcessRunner, NUnit.Engine.Runners.AggregatingTestRunner, NUnit.Engine.Runners.MasterTestRunner, and NUnit.Engine.Runners.TestDomainRunner.
Referenced by NUnit.Engine.Runners.AbstractTestRunner.Unload().
ExploreTests()
abstract TestEngineResult NUnit.Engine.Runners.AbstractTestRunner.ExploreTests (TestFilter filter) protected pure virtual
Explores a previously loaded TestPackage and returns information about the tests found.
Parameters
filter The TestFilter to be used to select tests
Returns
A TestEngineResult.
Implemented in NUnit.Engine.Runners.ProcessRunner, NUnit.Engine.Runners.DirectTestRunner, NUnit.Engine.Runners.AggregatingTestRunner, and NUnit.Engine.Runners.MasterTestRunner.
Referenced by NUnit.Engine.Runners.AbstractTestRunner.Explore().
CountTests()
abstract int NUnit.Engine.Runners.AbstractTestRunner.CountTests (TestFilter filter) protected pure virtual
Count the test cases that would be run under the specified filter.
Parameters
filter A TestFilter
Returns
The count of test cases.
Implemented in NUnit.Engine.Runners.ProcessRunner, NUnit.Engine.Runners.DirectTestRunner, NUnit.Engine.Runners.AggregatingTestRunner, and NUnit.Engine.Runners.MasterTestRunner.
Referenced by NUnit.Engine.Runners.AbstractTestRunner.CountTestCases().
RunTests()
abstract TestEngineResult NUnit.Engine.Runners.AbstractTestRunner.RunTests (ITestEventListener listener, TestFilter filter) protected pure virtual
Run the tests in the loaded TestPackage.
Parameters
listener An ITestEventHandler to receive events
filter A TestFilter used to select tests
Returns
A TestEngineResult giving the result of the test execution
Implemented in NUnit.Engine.Runners.ProcessRunner, NUnit.Engine.Runners.DirectTestRunner, NUnit.Engine.Runners.AggregatingTestRunner, and NUnit.Engine.Runners.MasterTestRunner.
Referenced by NUnit.Engine.Runners.AbstractTestRunner.Run(), and NUnit.Engine.Runners.AbstractTestRunner.RunTestsAsync().
RunTestsAsync()
virtual AsyncTestEngineResult NUnit.Engine.Runners.AbstractTestRunner.RunTestsAsync (ITestEventListener listener, TestFilter filter) inline protected virtual
Start a run of the tests in the loaded TestPackage, returning immediately. The tests are run asynchronously and the listener interface is notified as it progresses.
Parameters
listener An ITestEventHandler to receive events
filter A TestFilter used to select tests
Returns
An AsyncTestEngineResult that will provide the result of the test execution
Reimplemented in NUnit.Engine.Runners.ProcessRunner.
References NUnit.Engine.Runners.AbstractTestRunner.RunTests().
Referenced by NUnit.Engine.Runners.AbstractTestRunner.RunAsync().
StopRun()
abstract void NUnit.Engine.Runners.AbstractTestRunner.StopRun (bool force) pure virtual
Cancel the ongoing test run. If no test is running, the call is ignored.
Parameters
force If true, cancel any ongoing test threads, otherwise wait for them to complete.
Implements NUnit.Engine.ITestEngineRunner.
Implemented in NUnit.Engine.Runners.ProcessRunner, NUnit.Engine.Runners.AggregatingTestRunner, NUnit.Engine.Runners.DirectTestRunner, and NUnit.Engine.Runners.MasterTestRunner.
Explore()
TestEngineResult NUnit.Engine.Runners.AbstractTestRunner.Explore (TestFilter filter) inline
Explores the TestPackage and returns information about the tests found. Loads the package if not done previously.
Parameters
filter The TestFilter to be used to select tests
Returns
A TestEngineResult.
Implements NUnit.Engine.ITestEngineRunner.
References NUnit.Engine.Runners.AbstractTestRunner.EnsurePackageIsLoaded(), and NUnit.Engine.Runners.AbstractTestRunner.ExploreTests().
Load()
TestEngineResult NUnit.Engine.Runners.AbstractTestRunner.Load () inline
Loads the TestPackage for exploration or execution, saving the result.
Returns
A TestEngineResult.
Implements NUnit.Engine.ITestEngineRunner.
References NUnit.Engine.Runners.AbstractTestRunner.LoadPackage(), and NUnit.Engine.Runners.AbstractTestRunner.LoadResult.
Reload()
TestEngineResult NUnit.Engine.Runners.AbstractTestRunner.Reload () inline
Reload the currently loaded test package, saving the result.
Returns
A TestEngineResult.
Exceptions
InvalidOperationException If no package has been loaded
Implements NUnit.Engine.ITestEngineRunner.
References NUnit.Engine.Runners.AbstractTestRunner.LoadResult, and NUnit.Engine.Runners.AbstractTestRunner.ReloadPackage().
Unload()
void NUnit.Engine.Runners.AbstractTestRunner.Unload () inline
Unload any loaded TestPackage.
Implements NUnit.Engine.ITestEngineRunner.
References NUnit.Engine.Runners.AbstractTestRunner.LoadResult, and NUnit.Engine.Runners.AbstractTestRunner.UnloadPackage().
Referenced by NUnit.Engine.Runners.AbstractTestRunner.Dispose(), and NUnit.Engine.Runners.ProcessRunner.LoadPackage().
CountTestCases()
int NUnit.Engine.Runners.AbstractTestRunner.CountTestCases (TestFilter filter) inline
Count the test cases that would be run under the specified filter, loading the TestPackage if it is not already loaded.
Parameters
filter A TestFilter
Returns
The count of test cases.
Implements NUnit.Engine.ITestEngineRunner.
References NUnit.Engine.Runners.AbstractTestRunner.CountTests(), and NUnit.Engine.Runners.AbstractTestRunner.EnsurePackageIsLoaded().
Referenced by NUnit.Engine.Runners.MasterTestRunner.RunTests().
Run()
TestEngineResult NUnit.Engine.Runners.AbstractTestRunner.Run (ITestEventListener listener, TestFilter filter) inline
Run the tests in the TestPackage, loading the package if this has not already been done.
Parameters
listener An ITestEventHandler to receive events
filter A TestFilter used to select tests
Returns
A TestEngineResult giving the result of the test execution
Implements NUnit.Engine.ITestEngineRunner.
References NUnit.Engine.Runners.AbstractTestRunner.EnsurePackageIsLoaded(), and NUnit.Engine.Runners.AbstractTestRunner.RunTests().
RunAsync()
AsyncTestEngineResult NUnit.Engine.Runners.AbstractTestRunner.RunAsync (ITestEventListener listener, TestFilter filter) inline
Start a run of the tests in the loaded TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses.
Parameters
listener An ITestEventHandler to receive events
filter A TestFilter used to select tests
Returns
An AsyncTestEngineResult that will provide the result of the test execution
Implements NUnit.Engine.ITestEngineRunner.
References NUnit.Engine.Runners.AbstractTestRunner.EnsurePackageIsLoaded(), and NUnit.Engine.Runners.AbstractTestRunner.RunTestsAsync().
Referenced by NUnit.Engine.Runners.AbstractTestRunner.StartRun().
StartRun()
void NUnit.Engine.Runners.AbstractTestRunner.StartRun (ITestEventListener listener, TestFilter filter) inline
Start a run of the tests in the TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses. Loads the TestPackage if not already loaded.
Parameters
listener An ITestEventHandler to receive events
filter A TestFilter used to select tests
Implements NUnit.Engine.ITestEngineRunner.
References NUnit.Engine.Runners.AbstractTestRunner.RunAsync().
Dispose() [1/2]
void NUnit.Engine.Runners.AbstractTestRunner.Dispose () inline
Dispose() [2/2]
virtual void NUnit.Engine.Runners.AbstractTestRunner.Dispose (bool disposing) inline protected virtual
Reimplemented in NUnit.Engine.Runners.ProcessRunner, NUnit.Engine.Runners.AggregatingTestRunner, and NUnit.Engine.Runners.MasterTestRunner.
References NUnit.Engine.Runners.AbstractTestRunner._disposed, and NUnit.Engine.Runners.AbstractTestRunner.Unload().
IsProjectPackage()
bool NUnit.Engine.Runners.AbstractTestRunner.IsProjectPackage (TestPackage package) inline protected
Referenced by NUnit.Engine.Runners.AggregatingTestRunner.ExploreTests(), NUnit.Engine.Runners.DirectTestRunner.ExploreTests(), NUnit.Engine.Runners.DirectTestRunner.LoadPackage(), NUnit.Engine.Runners.AggregatingTestRunner.RunTests(), and NUnit.Engine.Runners.DirectTestRunner.RunTests().
EnsurePackageIsLoaded()
void NUnit.Engine.Runners.AbstractTestRunner.EnsurePackageIsLoaded () inline private
References NUnit.Engine.Runners.AbstractTestRunner.IsPackageLoaded, NUnit.Engine.Runners.AbstractTestRunner.LoadPackage(), and NUnit.Engine.Runners.AbstractTestRunner.LoadResult.
Referenced by NUnit.Engine.Runners.AbstractTestRunner.CountTestCases(), NUnit.Engine.Runners.AbstractTestRunner.Explore(), NUnit.Engine.Runners.AbstractTestRunner.Run(), and NUnit.Engine.Runners.AbstractTestRunner.RunAsync().
Member Data Documentation
TEST_RUN_ELEMENT
const string NUnit.Engine.Runners.AbstractTestRunner.TEST_RUN_ELEMENT = "test-run" static protected
Referenced by NUnit.Engine.Runners.MasterTestRunner.ExploreTests(), and NUnit.Engine.Runners.MasterTestRunner.LoadPackage().
_disposed
bool NUnit.Engine.Runners.AbstractTestRunner._disposed = false protected
Referenced by NUnit.Engine.Runners.MasterTestRunner.Dispose(), and NUnit.Engine.Runners.AbstractTestRunner.Dispose().
Property Documentation
Services
IServiceLocator NUnit.Engine.Runners.AbstractTestRunner.Services get private set protected
Our Service Context
Referenced by NUnit.Engine.Runners.AbstractTestRunner.AbstractTestRunner(), NUnit.Engine.Runners.MultipleTestDomainRunner.CreateRunner(), NUnit.Engine.Runners.MultipleTestProcessRunner.CreateRunner(), NUnit.Engine.Runners.DirectTestRunner.LoadPackage(), NUnit.Engine.Runners.ProcessRunner.ProcessRunner(), NUnit.Engine.Runners.TestDomainRunner.TestDomainRunner(), and NUnit.Engine.Runners.MasterTestRunner.ValidatePackageSettings().
ProjectService
IProjectService NUnit.Engine.Runners.AbstractTestRunner.ProjectService get private set protected
Referenced by NUnit.Engine.Runners.AggregatingTestRunner.LoadPackage().
TestRunnerFactory
ITestRunnerFactory NUnit.Engine.Runners.AbstractTestRunner.TestRunnerFactory get private set protected
Referenced by NUnit.Engine.Runners.AbstractTestRunner.AbstractTestRunner(), NUnit.Engine.Runners.AggregatingTestRunner.CreateRunner(), and NUnit.Engine.Runners.MasterTestRunner.LoadPackage().
TestPackage
TestPackage NUnit.Engine.Runners.AbstractTestRunner.TestPackage get set protected
The TestPackage for which this is the runner
LoadResult
TestEngineResult NUnit.Engine.Runners.AbstractTestRunner.LoadResult get set protected
The result of the last call to LoadPackage
Referenced by NUnit.Engine.Runners.AbstractTestRunner.EnsurePackageIsLoaded(), NUnit.Engine.Runners.AbstractTestRunner.Load(), NUnit.Engine.Runners.AbstractTestRunner.Reload(), and NUnit.Engine.Runners.AbstractTestRunner.Unload().
IsPackageLoaded
bool NUnit.Engine.Runners.AbstractTestRunner.IsPackageLoaded get protected
Gets an indicator of whether the package has been loaded.
Referenced by NUnit.Engine.Runners.AbstractTestRunner.EnsurePackageIsLoaded().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Runners/AbstractTestRunner.cs