Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLANV2 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLANV2 Class Reference
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLANV2 (DLAMCH dlamch, DLAPY2 dlapy2)
DLANV2 ()
void Run (ref double A, ref double B, ref double C, ref double D, ref double RT1R, ref double RT1I, ref double RT2R, ref double RT2I, ref double CS, ref double SN)
Private Attributes
DLAMCH _dlamch
DLAPY2 _dlapy2
Static Private Attributes
const double ZERO = 0.0E+0
const double HALF = 0.5E+0
const double ONE = 1.0E+0
const double MULTPL = 4.0E+0
Detailed Description
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLANV2 computes the Schur factorization of a real 2-by-2 nonsymmetric matrix in standard form:
[ A B ] = [ CS -SN ] [ AA BB ] [ CS SN ] [ C D ] [ SN CS ] [ CC DD ] [-SN CS ]
where either 1) CC = 0 so that AA and DD are real eigenvalues of the matrix, or 2) AA = DD and BB*CC .LT. 0, so that AA + or - sqrt(BB*CC) are complex conjugate eigenvalues.
/summary>
Constructor & Destructor Documentation
DLANV2() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLANV2.DLANV2 (DLAMCH dlamch, DLAPY2 dlapy2) inline
DLANV2() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLANV2.DLANV2 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLANV2.Run (ref double A, ref double B, ref double C, ref double D, ref double RT1R, ref double RT1I, ref double RT2R, ref double RT2I, ref double CS, ref double SN) inline
Purpose
DLANV2 computes the Schur factorization of a real 2-by-2 nonsymmetric matrix in standard form:
[ A B ] = [ CS -SN ] [ AA BB ] [ CS SN ] [ C D ] [ SN CS ] [ CC DD ] [-SN CS ]
where either 1) CC = 0 so that AA and DD are real eigenvalues of the matrix, or 2) AA = DD and BB*CC .LT. 0, so that AA + or - sqrt(BB*CC) are complex conjugate eigenvalues.
/summary>
Parameters
A (input/output) DOUBLE PRECISION /param>
Parameters
B (input/output) DOUBLE PRECISION /param>
Parameters
C (input/output) DOUBLE PRECISION /param>
Parameters
D (input/output) DOUBLE PRECISION On entry, the elements of the input matrix. On exit, they are overwritten by the elements of the standardised Schur form. /param>
Parameters
RT1R (output) DOUBLE PRECISION /param>
Parameters
RT1I (output) DOUBLE PRECISION /param>
Parameters
RT2R (output) DOUBLE PRECISION /param>
Parameters
RT2I (output) DOUBLE PRECISION The real and imaginary parts of the eigenvalues. If the eigenvalues are a complex conjugate pair, RT1I .GT. 0. /param>
Parameters
CS (output) DOUBLE PRECISION /param>
Parameters
SN (output) DOUBLE PRECISION Parameters of the rotation matrix. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLANV2.HALF, DotNumerics.LinearAlgebra.CSLapack.DLANV2.MULTPL, DotNumerics.LinearAlgebra.CSLapack.DLANV2.ONE, DotNumerics.LinearAlgebra.CSLapack.DLAPY2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.FortranLibrary.FortranLib.Sign(), and DotNumerics.LinearAlgebra.CSLapack.DLANV2.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAEXC.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAHQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR3.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR4.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAQR0.Run().
Member Data Documentation
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLANV2._dlamch private
_dlapy2
DLAPY2 DotNumerics.LinearAlgebra.CSLapack.DLANV2._dlapy2 private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLANV2.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLANV2.Run().
HALF
const double DotNumerics.LinearAlgebra.CSLapack.DLANV2.HALF = 0.5E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLANV2.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLANV2.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLANV2.Run().
MULTPL
const double DotNumerics.LinearAlgebra.CSLapack.DLANV2.MULTPL = 4.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLANV2.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlanv2.cs