Doc: IGLib EXTENDED: NUnit.Framework.Attributes.PropertyAttributeTests Class Reference
NUnit.Framework.Attributes.PropertyAttributeTests Class Reference
Public Member Functions
void CreateFixture ()
void PropertyWithStringValue ()
void PropertiesWithNumericValues ()
void PropertyWorksOnFixtures ()
void CanDeriveFromPropertyAttribute ()
void CustomPropertyAttribute ()
Private Attributes
TestSuite fixture
Member Function Documentation
CreateFixture()
void NUnit.Framework.Attributes.PropertyAttributeTests.CreateFixture () inline
References NUnit.Framework.Attributes.PropertyAttributeTests.fixture, and NUnit.TestUtilities.TestBuilder.MakeFixture().
PropertyWithStringValue()
void NUnit.Framework.Attributes.PropertyAttributeTests.PropertyWithStringValue () inline
References NUnit.Framework.Attributes.PropertyAttributeTests.fixture, NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.TestSuite.Tests, and NUnit.Framework.Assert.That().
PropertiesWithNumericValues()
void NUnit.Framework.Attributes.PropertyAttributeTests.PropertiesWithNumericValues () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Attributes.PropertyAttributeTests.fixture, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, and NUnit.Framework.Internal.TestSuite.Tests.
PropertyWorksOnFixtures()
void NUnit.Framework.Attributes.PropertyAttributeTests.PropertyWorksOnFixtures () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Attributes.PropertyAttributeTests.fixture, NUnit.Framework.Interfaces.IPropertyBag.Get(), and NUnit.Framework.Internal.Test.Properties.
CanDeriveFromPropertyAttribute()
void NUnit.Framework.Attributes.PropertyAttributeTests.CanDeriveFromPropertyAttribute () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Attributes.PropertyAttributeTests.fixture, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, and NUnit.Framework.Internal.TestSuite.Tests.
CustomPropertyAttribute()
void NUnit.Framework.Attributes.PropertyAttributeTests.CustomPropertyAttribute () inline
References NUnit.Framework.Attributes.PropertyAttributeTests.fixture, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Assert.IsNotNull(), NUnit.Framework.Internal.Test.Properties, and NUnit.Framework.Internal.TestSuite.Tests.
Member Data Documentation
fixture
TestSuite NUnit.Framework.Attributes.PropertyAttributeTests.fixture private
Referenced by NUnit.Framework.Attributes.PropertyAttributeTests.CanDeriveFromPropertyAttribute(), NUnit.Framework.Attributes.PropertyAttributeTests.CreateFixture(), NUnit.Framework.Attributes.PropertyAttributeTests.CustomPropertyAttribute(), NUnit.Framework.Attributes.PropertyAttributeTests.PropertiesWithNumericValues(), NUnit.Framework.Attributes.PropertyAttributeTests.PropertyWithStringValue(), and NUnit.Framework.Attributes.PropertyAttributeTests.PropertyWorksOnFixtures().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/PropertyAttributeTests.cs