Doc: IGLib EXTENDED: IG.Gr3d.TestVtkGraphicBase Class Reference
IG.Gr3d.TestVtkGraphicBase Class Reference
Tests of 3D graphics enabled by ActiViz (VTK wrapper library).
Classes
class CustomImplicitFunction
An vtkImplicitFunction class that represents a custom function of 3 variables used for plotting contours.
Static Public Member Functions
static void Run ()
static void Test1 ()
static void Test2 ()
static void ColorBar ()
static void Legend ()
static void ExampleParametricCurve (int numT)
Example of plotting parametric curves in 3D space.
static void ExampleStructuredGridVolumeContours ()
Example that demonstrates generaton of contours on a 3D structured grid.
static void ExampleStructuredGridVolumeContours (int sizex, int sizey, int sizez, int numContours)
Example that demonstrates generaton of contours on a 3D structured grid.
static void ExampleCellsGridContours ()
ExamExample of plotting contours on surfaces in 3D (graphs of functions of 2 variables or parametric surfaces) by using graphic primitives (cells) connected to polydata. Default division numbers of the shown graph are taken.
static void ExampleCellsGridContours (int sizex, int sizey, int numContours)
Example of plotting contours on surfaces in 3D (graphs of functions of 2 variables or parametric surfaces) by using graphic primitives (cells) connected to polydata.
static void ExampleCellsGridEfficient ()
Example of efficient plotting surfaces in 3D (graphs of functions of 2 variables or parametric surfaces) by using graphic primitives (cells). Default division numbers of the shown graph are taken.
static void ExampleQuadCells ()
Example that demonstrates the ability to use simple primitives for plotting surfaces in 3D (graphs of functions of 2 variables or parametric surfaces).
static void ExampleQuadCells (int sizex, int sizey)
Example that demonstrates the ability to use simple primitives for plotting surfaces in 3D (graphs of functions of 2 variables or parametric surfaces).
static void ExampleStructuredGrid ()
Example that demonstrates the ability to use structured grids for plotting surfaces in 3D (graphs of functions of 2 variables or parametric surfaces).
static void ExampleAxisHendler ()
static void ExampleStructuredGrid (int sizex, int sizey, int sizez)
Example that demonstrates the ability to use structured grids for plotting surfaces in 3D (graphs of functions of 2 variables or parametric surfaces).
static ColorScale CreateGreenRedYellow (double minValue, double maxValue)
Static Private Member Functions
static double f (double x, double y)
Example function of 2 variables to generate a surface plot. In the future, ScalarFunction class will be used for this purpose.
static double GetX (int i)
Returns x coordinate corresponding to the specific index.
static double GetY (int j)
Returns y coordinate corresponding to the specific index.
static double GetZ (int k)
Returns z coordinate corresponding to the specific index.
static double f3d (double x, double y, double z)
static void ExampleCellsGridEfficient (int sizex, int sizey)
Example of efficient plotting surfaces in 3D (graphs of functions of 2 variables or parametric surfaces) by using graphic primitives (cells).
Static Private Attributes
static int numi = 6
static int numj = 6
static int numk = 2
static double minX = -1
static double maxX = 1
static double minY = -1
static double maxY = 1
static double minZ = -1
static double maxZ = 1
static double minValue = 0
static double maxValue = 0
static StopWatch1 timer = new StopWatch1()
StopWatch for measuring time.
Detailed Description
Tests of 3D graphics enabled by ActiViz (VTK wrapper library).
$A Tako78 Sep11; Igor Oct11;
Member Function Documentation
Run()
static void IG.Gr3d.TestVtkGraphicBase.Run () inline static
References IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGridVolumeContours().
Test1()
static void IG.Gr3d.TestVtkGraphicBase.Test1 () inline static
Test2()
static void IG.Gr3d.TestVtkGraphicBase.Test2 () inline static
ColorBar()
static void IG.Gr3d.TestVtkGraphicBase.ColorBar () inline static
References IG.Lib.color.B, IG.Lib.ColorScaleBase.CreateBlueRedYellow(), IG.Lib.color.G, IG.Lib.ColorScaleBase.GetColor(), IG.Lib.ColorScale.MaxValue, IG.Lib.ColorScale.MinValue, IG.Lib.color.Opacity, and IG.Lib.color.R.
Legend()
static void IG.Gr3d.TestVtkGraphicBase.Legend () inline static
f()
static double IG.Gr3d.TestVtkGraphicBase.f (double x, double y) inline static private
Example function of 2 variables to generate a surface plot. In the future, ScalarFunction class will be used for this purpose.
Referenced by IG.Gr3d.TestVtkGraphicBase.ExampleAxisHendler(), IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridContours(), IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridEfficient(), IG.Gr3d.TestVtkGraphicBase.ExampleQuadCells(), IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGrid(), and IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGridVolumeContours().
GetX()
static double IG.Gr3d.TestVtkGraphicBase.GetX (int i) inline static private
Returns x coordinate corresponding to the specific index.
References IG.Gr3d.TestVtkGraphicBase.maxX, IG.Gr3d.TestVtkGraphicBase.minX, and IG.Gr3d.TestVtkGraphicBase.numi.
Referenced by IG.Gr3d.TestVtkGraphicBase.ExampleAxisHendler(), IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridContours(), IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridEfficient(), IG.Gr3d.TestVtkGraphicBase.ExampleQuadCells(), IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGrid(), and IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGridVolumeContours().
GetY()
static double IG.Gr3d.TestVtkGraphicBase.GetY (int j) inline static private
Returns y coordinate corresponding to the specific index.
References IG.Gr3d.TestVtkGraphicBase.maxY, IG.Gr3d.TestVtkGraphicBase.minY, and IG.Gr3d.TestVtkGraphicBase.numj.
Referenced by IG.Gr3d.TestVtkGraphicBase.ExampleAxisHendler(), IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridContours(), IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridEfficient(), IG.Gr3d.TestVtkGraphicBase.ExampleQuadCells(), IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGrid(), and IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGridVolumeContours().
GetZ()
static double IG.Gr3d.TestVtkGraphicBase.GetZ (int k) inline static private
Returns z coordinate corresponding to the specific index.
References IG.Gr3d.TestVtkGraphicBase.maxZ, IG.Gr3d.TestVtkGraphicBase.minZ, and IG.Gr3d.TestVtkGraphicBase.numk.
Referenced by IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGridVolumeContours().
ExampleParametricCurve()
static void IG.Gr3d.TestVtkGraphicBase.ExampleParametricCurve (int numT) inline static
Example of plotting parametric curves in 3D space.
Parameters
numT Number fo divisions.
See also:
http://www.vtk.org/Wiki/VTK/Examples/Cxx/PolyData/RibbonFilter
f3d()
static double IG.Gr3d.TestVtkGraphicBase.f3d (double x, double y, double z) inline static private
Referenced by IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGridVolumeContours().
ExampleStructuredGridVolumeContours() [1/2]
static void IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGridVolumeContours () inline static
Example that demonstrates generaton of contours on a 3D structured grid.
See also:
http://www.vtk.org/Wiki/VTK/Examples/Cxx#vtkStructuredGrid
Referenced by IG.Gr3d.TestVtkGraphicBase.Run(), and IG.Script.ScriptGraphics3DBase.VtkFunctionStructuredGridVolumeContours().
ExampleStructuredGridVolumeContours() [2/2]
static void IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGridVolumeContours (int sizex, int sizey, int sizez, int numContours) inline static
Example that demonstrates generaton of contours on a 3D structured grid.
Parameters
sizex Number of points in x direction.
sizey Number of points in y direction.
sizez Number of points in z direction.
See also:
http://www.vtk.org/VTK/help/examplecode.html - generating contours of implicit function of 3 variables, probably useful only when you actually have an implicit function. http://www.vtk.org/Wiki/VTK/Examples/Cxx/ImplicitFunctions/SampleFunction - sample implicit function, 1 contour
http://www.vtk.org/Wiki/VTK/Examples/Cxx#vtkStructuredGrid
See Delaunay3D triangularization. http://public.kitware.com/cgi-bin/viewcvs.cgi/*checkout*‍/Examples/Modelling/Cxx/Delaunay3D.cxx?root=VTK&content-type=text/plain http://www.vtk.org/doc/release/5.6/html/a00464.html - Delaunay3D class reference http://www.vtk.org/Wiki/VTK/Examples/Cxx/Modelling/Delaunay3D - Delaunay triangularization in 3D
this is used to convert structured grid or any other form containing points to a 3d mesh of tetrahetrons.
See vtkContourGrid http://nullege.com/codes/show/src%40p%40y%40pyvisi-HEAD%40trunk%40examples%40renderers%40vtk%40isosurfacePlot.py/25/vtk.vtkContourGrid/python
Python example - triangulate and generate contour. http://www.vtk.org/doc/release/5.6/html/a00380.html - vtkContourGrid class reference.
See vtkBandedPolyDataContourFilter http://www.vtk.org/doc/release/5.6/html/a00177.html - vtkBandedPolyDataContourFilter class reference. This does not generate inner contur surfaces, but only outer contours on 3D body surface. http://www.vtk.org/Wiki/VTK/Examples/Cxx/VisualizationAlgorithms/BandedPolyDataContourFilter - filled grids on surface
References IG.Lib.ColorScaleBase.Create(), IG.Gr3d.VtkDecorationHandler.CubeAxesColor, IG.Gr3d.VtkDecorationHandler.CubeAxesFlyMode, IG.Gr3d.TestVtkGraphicBase.f(), IG.Gr3d.TestVtkGraphicBase.f3d(), IG.Lib.IColorScale.GetColor(), IG.Num.BoundingBoxBase.GetMax(), IG.Num.BoundingBoxBase.GetMin(), IG.Gr3d.TestVtkGraphicBase.GetX(), IG.Gr3d.TestVtkGraphicBase.GetY(), IG.Gr3d.TestVtkGraphicBase.GetZ(), IG.Lib.color.IntB, IG.Lib.color.IntG, IG.Lib.color.IntR, IG.Gr3d.TestVtkGraphicBase.maxValue, IG.Gr3d.TestVtkGraphicBase.maxX, IG.Gr3d.TestVtkGraphicBase.maxY, IG.Gr3d.TestVtkGraphicBase.maxZ, IG.Gr3d.TestVtkGraphicBase.minValue, IG.Gr3d.TestVtkGraphicBase.minX, IG.Gr3d.TestVtkGraphicBase.minY, IG.Gr3d.TestVtkGraphicBase.minZ, IG.Gr3d.TestVtkGraphicBase.numi, IG.Gr3d.TestVtkGraphicBase.numj, IG.Gr3d.TestVtkGraphicBase.numk, IG.Lib.StopWatch1.Reset(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.StopWatch1.Time, IG.Gr3d.TestVtkGraphicBase.timer, IG.Num.BoundingBoxBase.ToString(), IG.Lib.StopWatch1.TotalTime, and IG.Num.BoundingBoxBase.Update().
ExampleCellsGridContours() [1/2]
static void IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridContours () inline static
ExamExample of plotting contours on surfaces in 3D (graphs of functions of 2 variables or parametric surfaces) by using graphic primitives (cells) connected to polydata. Default division numbers of the shown graph are taken.
Parameters
sizex Number of points in x direction.
sizey Number of points in y direction.
See also:
http://www.vtk.org/Wiki/VTK/Examples/Cxx/GeometricObjects/LongLine
Referenced by IG.Script.ScriptGraphics3DBase.VtkFunctionCellGridContours().
ExampleCellsGridContours() [2/2]
static void IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridContours (int sizex, int sizey, int numContours) inline static
Example of plotting contours on surfaces in 3D (graphs of functions of 2 variables or parametric surfaces) by using graphic primitives (cells) connected to polydata.
Parameters
sizex Number of points in x direction.
sizey Number of points in y direction.
numContours Number of contours to be plotted.
See also:
http://www.vtk.org/Wiki/VTK/Examples/Cxx/GeometricObjects/Quad - quadric cells
http://www.vtk.org/Wiki/VTK/Examples/Cxx/GeometricObjects/ColoredLines - for adding line cells
http://www.vtk.org/Wiki/VTK/Examples/Cxx/VisualizationAlgorithms/BandedPolyDataContourFilter - discrete consours
http://www.vtk.org/Wiki/VTK/Examples/Cxx/PolyData/PolyDataIsoLines - for contours
http://www.vtk.org/Wiki/VTK/Examples/Cxx/VisualizationAlgorithms/FilledContours - this is more complex, approach taken here is simpler.
http://www.vtk.org/Wiki/VTK/Examples/Cxx/Visualization/LabelContours - labeling contours
References IG.Lib.color.Average(), IG.Lib.ColorScaleBase.Create(), IG.Gr3d.VtkDecorationHandler.CubeAxesColor, IG.Gr3d.VtkDecorationHandler.CubeAxesFlyMode, IG.Gr3d.VtkDecorationHandler.CubeAxesXLabel, IG.Gr3d.TestVtkGraphicBase.f(), IG.Lib.IColorScale.GetColor(), IG.Lib.ColorScaleBase.GetColor(), IG.Num.BoundingBoxBase.GetMax(), IG.Num.BoundingBoxBase.GetMin(), IG.Gr3d.TestVtkGraphicBase.GetX(), IG.Gr3d.TestVtkGraphicBase.GetY(), IG.Lib.color.IntB, IG.Lib.color.IntG, IG.Lib.color.IntR, IG.Gr3d.TestVtkGraphicBase.maxX, IG.Gr3d.TestVtkGraphicBase.maxY, IG.Gr3d.TestVtkGraphicBase.maxZ, IG.Gr3d.TestVtkGraphicBase.minX, IG.Gr3d.TestVtkGraphicBase.minY, IG.Gr3d.TestVtkGraphicBase.minZ, IG.Gr3d.TestVtkGraphicBase.numi, IG.Gr3d.TestVtkGraphicBase.numj, IG.Gr3d.TestVtkGraphicBase.numk, IG.Lib.StopWatch1.Reset(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.StopWatch1.Time, IG.Gr3d.TestVtkGraphicBase.timer, IG.Lib.StopWatch1.TotalTime, and IG.Num.BoundingBoxBase.Update().
ExampleCellsGridEfficient() [1/2]
static void IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridEfficient () inline static
Example of efficient plotting surfaces in 3D (graphs of functions of 2 variables or parametric surfaces) by using graphic primitives (cells). Default division numbers of the shown graph are taken.
Parameters
sizex Number of points in x direction.
sizey Number of points in y direction.
See also:
http://www.vtk.org/Wiki/VTK/Examples/Cxx/GeometricObjects/Quad - quadric cells
http://www.vtk.org/Wiki/VTK/Examples/Cxx/GeometricObjects/LongLine
ExampleCellsGridEfficient() [2/2]
static void IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridEfficient (int sizex, int sizey) inline static private
Example of efficient plotting surfaces in 3D (graphs of functions of 2 variables or parametric surfaces) by using graphic primitives (cells).
Parameters
sizex Number of points in x direction.
sizey Number of points in y direction.
See also:
http://www.vtk.org/Wiki/VTK/Examples/Cxx/GeometricObjects/ColoredLines
http://www.vtk.org/Wiki/VTK/Examples/Cxx/GeometricObjects/LongLine
References IG.Lib.color.Average(), IG.Lib.ColorScaleBase.Create(), IG.Gr3d.VtkDecorationHandler.CubeAxesColor, IG.Gr3d.VtkDecorationHandler.CubeAxesFlyMode, IG.Gr3d.VtkDecorationHandler.CubeAxesXLabel, IG.Gr3d.TestVtkGraphicBase.f(), IG.Lib.IColorScale.GetColor(), IG.Num.BoundingBoxBase.GetMax(), IG.Num.BoundingBoxBase.GetMin(), IG.Gr3d.TestVtkGraphicBase.GetX(), IG.Gr3d.TestVtkGraphicBase.GetY(), IG.Lib.color.IntB, IG.Lib.color.IntG, IG.Lib.color.IntR, IG.Gr3d.TestVtkGraphicBase.maxX, IG.Gr3d.TestVtkGraphicBase.maxY, IG.Gr3d.TestVtkGraphicBase.maxZ, IG.Gr3d.TestVtkGraphicBase.minX, IG.Gr3d.TestVtkGraphicBase.minY, IG.Gr3d.TestVtkGraphicBase.minZ, IG.Gr3d.TestVtkGraphicBase.numi, IG.Gr3d.TestVtkGraphicBase.numj, IG.Gr3d.TestVtkGraphicBase.numk, IG.Lib.StopWatch1.Reset(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.StopWatch1.Time, IG.Gr3d.TestVtkGraphicBase.timer, IG.Lib.StopWatch1.TotalTime, and IG.Num.BoundingBoxBase.Update().
ExampleQuadCells() [1/2]
static void IG.Gr3d.TestVtkGraphicBase.ExampleQuadCells () inline static
Example that demonstrates the ability to use simple primitives for plotting surfaces in 3D (graphs of functions of 2 variables or parametric surfaces).
See also:
http://www.vtk.org/Wiki/VTK/Examples/Cxx/GeometricObjects/Quad
Referenced by IG.Script.ScriptGraphics3DBase.VtkFunctionQuadCells().
ExampleQuadCells() [2/2]
static void IG.Gr3d.TestVtkGraphicBase.ExampleQuadCells (int sizex, int sizey) inline static
Example that demonstrates the ability to use simple primitives for plotting surfaces in 3D (graphs of functions of 2 variables or parametric surfaces).
Parameters
sizex Number of points in x direction.
sizey Number of points in y direction.
See also:
http://www.vtk.org/Wiki/VTK/Examples/Cxx/GeometricObjects/Quad
References IG.Gr3d.VtkDecorationHandler.CubeAxesColor, IG.Gr3d.VtkDecorationHandler.CubeAxesFlyMode, IG.Gr3d.VtkDecorationHandler.CubeAxesXLabel, IG.Gr3d.TestVtkGraphicBase.f(), IG.Gr3d.TestVtkGraphicBase.GetX(), IG.Gr3d.TestVtkGraphicBase.GetY(), IG.Gr3d.TestVtkGraphicBase.maxX, IG.Gr3d.TestVtkGraphicBase.maxY, IG.Gr3d.TestVtkGraphicBase.minX, IG.Gr3d.TestVtkGraphicBase.minY, IG.Gr3d.TestVtkGraphicBase.numi, IG.Gr3d.TestVtkGraphicBase.numj, IG.Gr3d.TestVtkGraphicBase.numk, IG.Lib.StopWatch1.Reset(), IG.Gr3d.VtkDecorationHandler.SetActorScale(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.StopWatch1.Time, IG.Gr3d.TestVtkGraphicBase.timer, IG.Lib.StopWatch1.TotalTime, and IG.Gr3d.UtilVtk.UpdateBounds().
ExampleStructuredGrid() [1/2]
static void IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGrid () inline static
Example that demonstrates the ability to use structured grids for plotting surfaces in 3D (graphs of functions of 2 variables or parametric surfaces).
See also:
http://www.vtk.org/Wiki/VTK/Examples/Cxx#vtkStructuredGrid
Referenced by IG.Script.ScriptGraphics3DBase.VtkFunctionStructuredGrid().
ExampleAxisHendler()
static void IG.Gr3d.TestVtkGraphicBase.ExampleAxisHendler () inline static
References IG.Gr3d.UtilVtk.CreateBounds(), IG.Gr3d.TestVtkGraphicBase.f(), IG.Gr3d.TestVtkGraphicBase.GetX(), IG.Gr3d.TestVtkGraphicBase.GetY(), IG.Gr3d.TestVtkGraphicBase.numk, and IG.Gr3d.UtilVtk.SetBounds().
ExampleStructuredGrid() [2/2]
static void IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGrid (int sizex, int sizey, int sizez) inline static
Example that demonstrates the ability to use structured grids for plotting surfaces in 3D (graphs of functions of 2 variables or parametric surfaces).
Parameters
sizex Number of points in x direction.
sizey Number of points in y direction.
sizez Number of points in z direction.
See also:
http://www.vtk.org/Wiki/VTK/Examples/Cxx#vtkStructuredGrid
References IG.Lib.ColorScaleBase.Create(), IG.Gr3d.UtilVtk.CreateBounds(), IG.Gr3d.TestVtkGraphicBase.f(), IG.Lib.IColorScale.GetColor(), IG.Num.BoundingBoxBase.GetMax(), IG.Num.BoundingBoxBase.GetMin(), IG.Gr3d.TestVtkGraphicBase.GetX(), IG.Gr3d.TestVtkGraphicBase.GetY(), IG.Lib.color.IntB, IG.Lib.color.IntG, IG.Lib.color.IntR, IG.Gr3d.TestVtkGraphicBase.maxZ, IG.Gr3d.TestVtkGraphicBase.minZ, IG.Gr3d.TestVtkGraphicBase.numi, IG.Gr3d.TestVtkGraphicBase.numj, IG.Gr3d.TestVtkGraphicBase.numk, IG.Lib.StopWatch1.Reset(), IG.Gr3d.UtilVtk.SetBounds(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.StopWatch1.Time, IG.Gr3d.TestVtkGraphicBase.timer, IG.Lib.StopWatch1.TotalTime, and IG.Num.BoundingBoxBase.Update().
CreateGreenRedYellow()
static ColorScale IG.Gr3d.TestVtkGraphicBase.CreateGreenRedYellow (double minValue, double maxValue) inline static
References IG.Gr3d.TestVtkGraphicBase.maxValue, and IG.Gr3d.TestVtkGraphicBase.minValue.
Referenced by IG.Gr3d.TestVtkGraphic.ExampleNeuralTadej().
Member Data Documentation
numi
int IG.Gr3d.TestVtkGraphicBase.numi = 6 static private
Referenced by IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridContours(), IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridEfficient(), IG.Gr3d.TestVtkGraphicBase.ExampleQuadCells(), IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGrid(), IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGridVolumeContours(), and IG.Gr3d.TestVtkGraphicBase.GetX().
numj
int IG.Gr3d.TestVtkGraphicBase.numj = 6 static private
Referenced by IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridContours(), IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridEfficient(), IG.Gr3d.TestVtkGraphicBase.ExampleQuadCells(), IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGrid(), IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGridVolumeContours(), and IG.Gr3d.TestVtkGraphicBase.GetY().
numk
int IG.Gr3d.TestVtkGraphicBase.numk = 2 static private
Referenced by IG.Gr3d.TestVtkGraphicBase.ExampleAxisHendler(), IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridContours(), IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridEfficient(), IG.Gr3d.TestVtkGraphicBase.ExampleQuadCells(), IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGrid(), IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGridVolumeContours(), and IG.Gr3d.TestVtkGraphicBase.GetZ().
minX
double IG.Gr3d.TestVtkGraphicBase.minX = -1 static private
Referenced by IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridContours(), IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridEfficient(), IG.Gr3d.TestVtkGraphicBase.ExampleQuadCells(), IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGridVolumeContours(), and IG.Gr3d.TestVtkGraphicBase.GetX().
maxX
double IG.Gr3d.TestVtkGraphicBase.maxX = 1 static private
Referenced by IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridContours(), IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridEfficient(), IG.Gr3d.TestVtkGraphicBase.ExampleQuadCells(), IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGridVolumeContours(), and IG.Gr3d.TestVtkGraphicBase.GetX().
minY
double IG.Gr3d.TestVtkGraphicBase.minY = -1 static private
Referenced by IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridContours(), IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridEfficient(), IG.Gr3d.TestVtkGraphicBase.ExampleQuadCells(), IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGridVolumeContours(), and IG.Gr3d.TestVtkGraphicBase.GetY().
maxY
double IG.Gr3d.TestVtkGraphicBase.maxY = 1 static private
Referenced by IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridContours(), IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridEfficient(), IG.Gr3d.TestVtkGraphicBase.ExampleQuadCells(), IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGridVolumeContours(), and IG.Gr3d.TestVtkGraphicBase.GetY().
minZ
double IG.Gr3d.TestVtkGraphicBase.minZ = -1 static private
Referenced by IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridContours(), IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridEfficient(), IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGrid(), IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGridVolumeContours(), and IG.Gr3d.TestVtkGraphicBase.GetZ().
maxZ
double IG.Gr3d.TestVtkGraphicBase.maxZ = 1 static private
Referenced by IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridContours(), IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridEfficient(), IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGrid(), IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGridVolumeContours(), and IG.Gr3d.TestVtkGraphicBase.GetZ().
minValue
double IG.Gr3d.TestVtkGraphicBase.minValue = 0 static private
Referenced by IG.Gr3d.TestVtkGraphicBase.CreateGreenRedYellow(), and IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGridVolumeContours().
maxValue
double IG.Gr3d.TestVtkGraphicBase.maxValue = 0 static private
Referenced by IG.Gr3d.TestVtkGraphicBase.CreateGreenRedYellow(), and IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGridVolumeContours().
timer
StopWatch1 IG.Gr3d.TestVtkGraphicBase.timer = new StopWatch1() static private
StopWatch for measuring time.
Referenced by IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridContours(), IG.Gr3d.TestVtkGraphicBase.ExampleCellsGridEfficient(), IG.Gr3d.TestVtkGraphicBase.ExampleQuadCells(), IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGrid(), and IG.Gr3d.TestVtkGraphicBase.ExampleStructuredGridVolumeContours().
The documentation for this class was generated from the following file:
iglib/extensions/igplot3d/plot3d/Examples/TestVtkGraphic.cs