Doc: IGLib EXTENDED: AForge.Video.DirectShow.VideoCaptureDevice Class Reference
AForge.Video.DirectShow.VideoCaptureDevice Class Reference
Video source for local video capture device (for example USB webcam).
Classes
class Grabber
Public Member Functions
VideoCaptureDevice ()
Initializes a new instance of the VideoCaptureDevice class.
VideoCaptureDevice (string deviceMoniker)
Initializes a new instance of the VideoCaptureDevice class.
void Start ()
Start video source.
void SignalToStop ()
Signal video source to stop its work.
void WaitForStop ()
Wait for video source has stopped.
void Stop ()
Stop video source.
void DisplayPropertyPage (IntPtr parentWindow)
Display property window for the video capture device providing its configuration capabilities.
void DisplayCrossbarPropertyPage (IntPtr parentWindow)
Display property page of video crossbar (Analog Video Crossbar filter).
bool CheckIfCrossbarAvailable ()
Check if running video source provides crossbar for configuration.
void SimulateTrigger ()
Simulates an external trigger.
Properties
VideoInput CrossbarVideoInput [get, set]
Current video input of capture card.
VideoInput[]? AvailableCrossbarVideoInputs [get]
Available inputs of the video capture card.
bool ProvideSnapshots [get, set]
Specifies if snapshots should be provided or not.
virtual string Source [get, set]
Video source.
int FramesReceived [get]
Received frames count.
long BytesReceived [get]
Received bytes count.
bool IsRunning [get]
State of the video source.
Size DesiredFrameSize [get, set]
Desired size of captured video frames.
Size DesiredSnapshotSize [get, set]
Desired size of captured snapshot frames.
int DesiredFrameRate [get, set]
Desired capture frame rate.
VideoCapabilities[]? VideoCapabilities [get]
Video capabilities of the device.
VideoCapabilities[]? SnapshotCapabilities [get]
Snapshot capabilities of the device.
object SourceObject [get]
Source COM object of camera capture device.
Properties inherited from AForge.Video.IVideoSource
string Source [get]
Video source.
int FramesReceived [get]
Received frames count.
long BytesReceived [get]
Received bytes count.
bool IsRunning [get]
State of the video source.
Events
NewFrameEventHandler NewFrame
New frame event.
NewFrameEventHandler SnapshotFrame
Snapshot frame event.
VideoSourceErrorEventHandler VideoSourceError
Video source error event.
PlayingFinishedEventHandler PlayingFinished
Video playing finished event.
Events inherited from AForge.Video.IVideoSource
NewFrameEventHandler NewFrame
New frame event.
VideoSourceErrorEventHandler VideoSourceError
Video source error event.
PlayingFinishedEventHandler PlayingFinished
Video playing finished event.
Private Member Functions
void Free ()
Free resource.
void WorkerThread ()
Worker thread.
void WorkerThread (bool runGraph)
void SetFrameSizeAndRate (IAMStreamConfig streamConfig, Size size, int frameRate)
void GetPinCapabilitiesAndConfigureSizeAndRate (ICaptureGraphBuilder2 graphBuilder, IBaseFilter baseFilter, Guid pinCategory, Size size, int frameRate, ref VideoCapabilities[] capabilities)
void DisplayPropertyPage (IntPtr parentWindow, object sourceObject)
VideoInput[] ColletCrossbarVideoInputs (IAMCrossbar crossbar)
VideoInput GetCurrentCrossbarInput (IAMCrossbar crossbar)
void SetCurrentCrossbarInput (IAMCrossbar crossbar, VideoInput videoInput)
void OnNewFrame (Bitmap image)
Notifies clients about new frame.
void OnSnapshotFrame (Bitmap image)
Notifies clients about new snapshot frame.
Private Attributes
string deviceMoniker
int framesReceived
long bytesReceived
Size desiredFrameSize = new Size(0, 0)
int desiredFrameRate = 0
Size desiredSnapshotSize = new Size(0, 0)
bool provideSnapshots = false
Thread thread = null
ManualResetEvent stopEvent = null
VideoCapabilities[] videoCapabilities
VideoCapabilities[] snapshotCapabilities
bool needToSetVideoInput = false
bool needToSimulateTrigger = false
bool needToDisplayPropertyPage = false
bool needToDisplayCrossBarPropertyPage = false
IntPtr parentWindowForPropertyPage = IntPtr.Zero
object sourceObject = null
DateTime startTime = new DateTime()
object sync = new object()
bool? isCrossbarAvailable = null
VideoInput[] crossbarVideoInputs = null
VideoInput crossbarVideoInput = VideoInput.Default
Static Private Attributes
static Dictionary< string, VideoCapabilities[]> cacheVideoCapabilities = new Dictionary<string,VideoCapabilities[]>()
static Dictionary< string, VideoCapabilities[]> cacheSnapshotCapabilities = new Dictionary<string,VideoCapabilities[]>()
static Dictionary< string, VideoInput[]> cacheCrossbarVideoInputs = new Dictionary<string,VideoInput[]>()
Detailed Description
Video source for local video capture device (for example USB webcam).
This video source class captures video data from local video capture device, like USB web camera (or internal), frame grabber, capture board - anything which supports DirectShow interface. For devices which has a shutter button or support external software triggering, the class also allows to do snapshots. Both video size and snapshot size can be configured.
Sample usage:
// enumerate video devices
videoDevices = new FilterInfoCollection(FilterCategory.VideoInputDevice);
// create video source
VideoCaptureDevice videoSource = new VideoCaptureDevice(videoDevices[0].MonikerString);
// set NewFrame event handler
videoSource.NewFrame += new NewFrameEventHandler(video_NewFrame);
// start the video source
videoSource.Start();
// ...
// signal to stop when you no longer need capturing
videoSource.SignalToStop();
// ...
private void video_NewFrame(object sender, NewFrameEventArgs eventArgs)
{
    // get new frame
    Bitmap bitmap = eventArgs.Frame;
    // process the frame
}
Constructor & Destructor Documentation
VideoCaptureDevice() [1/2]
AForge.Video.DirectShow.VideoCaptureDevice.VideoCaptureDevice () inline
Initializes a new instance of the VideoCaptureDevice class.
VideoCaptureDevice() [2/2]
AForge.Video.DirectShow.VideoCaptureDevice.VideoCaptureDevice (string deviceMoniker) inline
Initializes a new instance of the VideoCaptureDevice class.
Parameters
deviceMoniker Moniker string of video capture device.
References AForge.Video.DirectShow.VideoCaptureDevice.deviceMoniker.
Member Function Documentation
Start()
void AForge.Video.DirectShow.VideoCaptureDevice.Start () inline
Start video source.
Starts video source and return execution to caller. Video source object creates background thread and notifies about new frames with the help of NewFrame event.
Implements AForge.Video.IVideoSource.
References AForge.Video.DirectShow.VideoCaptureDevice.bytesReceived, AForge.Video.DirectShow.VideoCaptureDevice.deviceMoniker, AForge.Video.DirectShow.VideoCaptureDevice.framesReceived, AForge.Video.DirectShow.VideoCaptureDevice.isCrossbarAvailable, AForge.Video.DirectShow.VideoCaptureDevice.IsRunning, AForge.Video.DirectShow.VideoCaptureDevice.needToSetVideoInput, AForge.Video.DirectShow.VideoCaptureDevice.stopEvent, AForge.Video.DirectShow.VideoCaptureDevice.sync, AForge.Video.DirectShow.VideoCaptureDevice.thread, and AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
SignalToStop()
void AForge.Video.DirectShow.VideoCaptureDevice.SignalToStop () inline
Signal video source to stop its work.
Signals video source to stop its background thread, stop to provide new frames and free resources.
Implements AForge.Video.IVideoSource.
References AForge.Video.DirectShow.VideoCaptureDevice.stopEvent, and AForge.Video.DirectShow.VideoCaptureDevice.thread.
WaitForStop()
void AForge.Video.DirectShow.VideoCaptureDevice.WaitForStop () inline
Wait for video source has stopped.
Waits for source stopping after it was signalled to stop using SignalToStop method.
Implements AForge.Video.IVideoSource.
References AForge.Video.DirectShow.VideoCaptureDevice.Free(), and AForge.Video.DirectShow.VideoCaptureDevice.thread.
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.Stop().
Stop()
void AForge.Video.DirectShow.VideoCaptureDevice.Stop () inline
Stop video source.
Stops video source aborting its thread.
<note>Since the method aborts background thread, its usage is highly not preferred and should be done only if there are no other options. The correct way of stopping camera is signaling it stop and then waiting for background thread's completion.</note>
Implements AForge.Video.IVideoSource.
References AForge.Video.DirectShow.VideoCaptureDevice.IsRunning, and AForge.Video.DirectShow.VideoCaptureDevice.WaitForStop().
Free()
void AForge.Video.DirectShow.VideoCaptureDevice.Free () inline private
Free resource.
References AForge.Video.DirectShow.VideoCaptureDevice.stopEvent, and AForge.Video.DirectShow.VideoCaptureDevice.thread.
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.WaitForStop().
DisplayPropertyPage() [1/2]
void AForge.Video.DirectShow.VideoCaptureDevice.DisplayPropertyPage (IntPtr parentWindow) inline
Display property window for the video capture device providing its configuration capabilities.
Parameters
parentWindow Handle of parent window.
<note>If you pass parent window's handle to this method, then the displayed property page will become modal window and none of the controls from the parent window will be accessible. In order to make it modeless it is required to pass IntPtr.Zero as parent window's handle. </note>
Exceptions
NotSupportedException The video source does not support configuration property page.
References AForge.Video.DirectShow.FilterInfo.CreateFilter(), AForge.Video.DirectShow.VideoCaptureDevice.deviceMoniker, AForge.Video.DirectShow.VideoCaptureDevice.IsRunning, AForge.Video.DirectShow.VideoCaptureDevice.needToDisplayPropertyPage, AForge.Video.DirectShow.VideoCaptureDevice.parentWindowForPropertyPage, and AForge.Video.DirectShow.VideoCaptureDevice.sync.
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
DisplayCrossbarPropertyPage()
void AForge.Video.DirectShow.VideoCaptureDevice.DisplayCrossbarPropertyPage (IntPtr parentWindow) inline
Display property page of video crossbar (Analog Video Crossbar filter).
Parameters
parentWindow Handle of parent window.
The Analog Video Crossbar filter is modeled after a general switching matrix, with n inputs and m outputs. For example, a video card might have two external connectors: a coaxial connector for TV, and an S-video input. These would be represented as input pins on the filter. The displayed property page allows to configure the crossbar by selecting input of a video card to use.
<note>This method can be invoked only when video source is running (IsRunning is true). Otherwise it generates exception.</note>
Use CheckIfCrossbarAvailable method to check if running video source provides crossbar configuration.
Exceptions
ApplicationException The video source must be running in order to display crossbar property page.
NotSupportedException Crossbar configuration is not supported by currently running video source.
References AForge.Video.DirectShow.VideoCaptureDevice.isCrossbarAvailable, AForge.Video.DirectShow.VideoCaptureDevice.IsRunning, AForge.Video.DirectShow.VideoCaptureDevice.needToDisplayCrossBarPropertyPage, AForge.Video.DirectShow.VideoCaptureDevice.parentWindowForPropertyPage, and AForge.Video.DirectShow.VideoCaptureDevice.sync.
CheckIfCrossbarAvailable()
bool AForge.Video.DirectShow.VideoCaptureDevice.CheckIfCrossbarAvailable () inline
Check if running video source provides crossbar for configuration.
Returns
Returns true if crossbar configuration is available or false otherwise.
The method reports if the video source provides crossbar configuration using DisplayCrossbarPropertyPage.
References AForge.Video.DirectShow.VideoCaptureDevice.isCrossbarAvailable, AForge.Video.DirectShow.VideoCaptureDevice.IsRunning, AForge.Video.DirectShow.VideoCaptureDevice.sync, and AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
SimulateTrigger()
void AForge.Video.DirectShow.VideoCaptureDevice.SimulateTrigger () inline
Simulates an external trigger.
The method simulates external trigger for video cameras, which support providing still image snapshots. The effect is equivalent as pressing camera's shutter button - a snapshot will be provided through SnapshotFrame event.
<note>The ProvideSnapshots property must be set to true to enable receiving snapshots.</note>
References AForge.Video.DirectShow.VideoCaptureDevice.needToSimulateTrigger.
Referenced by Snapshot_Maker.MainForm.triggerButton_Click().
WorkerThread() [1/2]
void AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread () inline private
Worker thread.
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.CheckIfCrossbarAvailable(), and AForge.Video.DirectShow.VideoCaptureDevice.Start().
WorkerThread() [2/2]
void AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread (bool runGraph) inline private
References AForge.Video.DirectShow.VideoCaptureDevice.cacheSnapshotCapabilities, AForge.Video.DirectShow.VideoCaptureDevice.cacheVideoCapabilities, AForge.Video.DirectShow.VideoCaptureDevice.ColletCrossbarVideoInputs(), AForge.Video.DirectShow.FilterInfo.CreateFilter(), AForge.Video.DirectShow.VideoCaptureDevice.crossbarVideoInput, AForge.Video.DirectShow.VideoCaptureDevice.crossbarVideoInputs, AForge.Video.DirectShow.VideoCaptureDevice.desiredFrameRate, AForge.Video.DirectShow.VideoCaptureDevice.desiredFrameSize, AForge.Video.DirectShow.VideoCaptureDevice.desiredSnapshotSize, AForge.Video.DirectShow.VideoCaptureDevice.deviceMoniker, AForge.Video.DirectShow.VideoCaptureDevice.DisplayPropertyPage(), AForge.Video.DirectShow.VideoCaptureDevice.GetCurrentCrossbarInput(), AForge.Video.DirectShow.VideoCaptureDevice.GetPinCapabilitiesAndConfigureSizeAndRate(), AForge.Video.DirectShow.VideoCaptureDevice.Grabber.Height, AForge.Video.DirectShow.VideoCaptureDevice.isCrossbarAvailable, AForge.Video.DirectShow.VideoCaptureDevice.needToDisplayCrossBarPropertyPage, AForge.Video.DirectShow.VideoCaptureDevice.needToDisplayPropertyPage, AForge.Video.DirectShow.VideoCaptureDevice.needToSetVideoInput, AForge.Video.DirectShow.VideoCaptureDevice.needToSimulateTrigger, AForge.Video.DirectShow.VideoCaptureDevice.parentWindowForPropertyPage, AForge.Video.DirectShow.VideoCaptureDevice.PlayingFinished, AForge.Video.DirectShow.VideoCaptureDevice.provideSnapshots, AForge.Video.DirectShow.VideoCaptureDevice.SetCurrentCrossbarInput(), AForge.Video.DirectShow.VideoCaptureDevice.snapshotCapabilities, AForge.Video.DirectShow.VideoCaptureDevice.sourceObject, AForge.Video.DirectShow.VideoCaptureDevice.startTime, AForge.Video.DirectShow.VideoCaptureDevice.stopEvent, AForge.Video.DirectShow.VideoCaptureDevice.videoCapabilities, AForge.Video.DirectShow.VideoCaptureDevice.VideoSourceError, and AForge.Video.DirectShow.VideoCaptureDevice.Grabber.Width.
SetFrameSizeAndRate()
void AForge.Video.DirectShow.VideoCaptureDevice.SetFrameSizeAndRate (IAMStreamConfig streamConfig, Size size, int frameRate) inline private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.GetPinCapabilitiesAndConfigureSizeAndRate().
GetPinCapabilitiesAndConfigureSizeAndRate()
void AForge.Video.DirectShow.VideoCaptureDevice.GetPinCapabilitiesAndConfigureSizeAndRate (ICaptureGraphBuilder2 graphBuilder, IBaseFilter baseFilter, Guid pinCategory, Size size, int frameRate, ref VideoCapabilities[] capabilities) inline private
References AForge.Video.DirectShow.VideoCaptureDevice.SetFrameSizeAndRate().
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
DisplayPropertyPage() [2/2]
void AForge.Video.DirectShow.VideoCaptureDevice.DisplayPropertyPage (IntPtr parentWindow, object sourceObject) inline private
References AForge.Video.DirectShow.VideoCaptureDevice.deviceMoniker, AForge.Video.DirectShow.FilterInfo.Name, and AForge.Video.DirectShow.VideoCaptureDevice.sourceObject.
ColletCrossbarVideoInputs()
VideoInput [] AForge.Video.DirectShow.VideoCaptureDevice.ColletCrossbarVideoInputs (IAMCrossbar crossbar) inline private
References AForge.Video.DirectShow.VideoCaptureDevice.cacheCrossbarVideoInputs, and AForge.Video.DirectShow.VideoCaptureDevice.deviceMoniker.
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
GetCurrentCrossbarInput()
VideoInput AForge.Video.DirectShow.VideoCaptureDevice.GetCurrentCrossbarInput (IAMCrossbar crossbar) inline private
References AForge.Video.DirectShow.VideoInput.Default.
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
SetCurrentCrossbarInput()
void AForge.Video.DirectShow.VideoCaptureDevice.SetCurrentCrossbarInput (IAMCrossbar crossbar, VideoInput videoInput) inline private
References AForge.Video.DirectShow.VideoInput.Type.
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
OnNewFrame()
void AForge.Video.DirectShow.VideoCaptureDevice.OnNewFrame (Bitmap image) inline private
Notifies clients about new frame.
Parameters
image New frame's image.
References AForge.Video.DirectShow.VideoCaptureDevice.bytesReceived, AForge.Video.DirectShow.VideoCaptureDevice.framesReceived, AForge.Video.DirectShow.VideoCaptureDevice.NewFrame, and AForge.Video.DirectShow.VideoCaptureDevice.stopEvent.
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.Grabber.BufferCB().
OnSnapshotFrame()
void AForge.Video.DirectShow.VideoCaptureDevice.OnSnapshotFrame (Bitmap image) inline private
Notifies clients about new snapshot frame.
Parameters
image New snapshot's image.
References AForge.Video.DirectShow.VideoCaptureDevice.SnapshotFrame, AForge.Video.DirectShow.VideoCaptureDevice.startTime, and AForge.Video.DirectShow.VideoCaptureDevice.stopEvent.
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.Grabber.BufferCB().
Member Data Documentation
deviceMoniker
string AForge.Video.DirectShow.VideoCaptureDevice.deviceMoniker private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.ColletCrossbarVideoInputs(), AForge.Video.DirectShow.VideoCaptureDevice.DisplayPropertyPage(), AForge.Video.DirectShow.VideoCaptureDevice.Start(), AForge.Video.DirectShow.VideoCaptureDevice.VideoCaptureDevice(), and AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
framesReceived
int AForge.Video.DirectShow.VideoCaptureDevice.framesReceived private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.OnNewFrame(), and AForge.Video.DirectShow.VideoCaptureDevice.Start().
bytesReceived
long AForge.Video.DirectShow.VideoCaptureDevice.bytesReceived private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.OnNewFrame(), and AForge.Video.DirectShow.VideoCaptureDevice.Start().
desiredFrameSize
Size AForge.Video.DirectShow.VideoCaptureDevice.desiredFrameSize = new Size(0, 0) private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
desiredFrameRate
int AForge.Video.DirectShow.VideoCaptureDevice.desiredFrameRate = 0 private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
desiredSnapshotSize
Size AForge.Video.DirectShow.VideoCaptureDevice.desiredSnapshotSize = new Size(0, 0) private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
provideSnapshots
bool AForge.Video.DirectShow.VideoCaptureDevice.provideSnapshots = false private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
thread
Thread AForge.Video.DirectShow.VideoCaptureDevice.thread = null private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.Free(), AForge.Video.DirectShow.VideoCaptureDevice.SignalToStop(), AForge.Video.DirectShow.VideoCaptureDevice.Start(), and AForge.Video.DirectShow.VideoCaptureDevice.WaitForStop().
stopEvent
ManualResetEvent AForge.Video.DirectShow.VideoCaptureDevice.stopEvent = null private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.Free(), AForge.Video.DirectShow.VideoCaptureDevice.OnNewFrame(), AForge.Video.DirectShow.VideoCaptureDevice.OnSnapshotFrame(), AForge.Video.DirectShow.VideoCaptureDevice.SignalToStop(), AForge.Video.DirectShow.VideoCaptureDevice.Start(), and AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
videoCapabilities
VideoCapabilities [] AForge.Video.DirectShow.VideoCaptureDevice.videoCapabilities private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
snapshotCapabilities
VideoCapabilities [] AForge.Video.DirectShow.VideoCaptureDevice.snapshotCapabilities private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
needToSetVideoInput
bool AForge.Video.DirectShow.VideoCaptureDevice.needToSetVideoInput = false private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.Start(), and AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
needToSimulateTrigger
bool AForge.Video.DirectShow.VideoCaptureDevice.needToSimulateTrigger = false private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.SimulateTrigger(), and AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
needToDisplayPropertyPage
bool AForge.Video.DirectShow.VideoCaptureDevice.needToDisplayPropertyPage = false private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.DisplayPropertyPage(), and AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
needToDisplayCrossBarPropertyPage
bool AForge.Video.DirectShow.VideoCaptureDevice.needToDisplayCrossBarPropertyPage = false private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.DisplayCrossbarPropertyPage(), and AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
parentWindowForPropertyPage
IntPtr AForge.Video.DirectShow.VideoCaptureDevice.parentWindowForPropertyPage = IntPtr.Zero private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.DisplayCrossbarPropertyPage(), AForge.Video.DirectShow.VideoCaptureDevice.DisplayPropertyPage(), and AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
sourceObject
object AForge.Video.DirectShow.VideoCaptureDevice.sourceObject = null private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.DisplayPropertyPage(), and AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
startTime
DateTime AForge.Video.DirectShow.VideoCaptureDevice.startTime = new DateTime() private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.OnSnapshotFrame(), and AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
sync
object AForge.Video.DirectShow.VideoCaptureDevice.sync = new object() private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.CheckIfCrossbarAvailable(), AForge.Video.DirectShow.VideoCaptureDevice.DisplayCrossbarPropertyPage(), AForge.Video.DirectShow.VideoCaptureDevice.DisplayPropertyPage(), and AForge.Video.DirectShow.VideoCaptureDevice.Start().
isCrossbarAvailable
bool? AForge.Video.DirectShow.VideoCaptureDevice.isCrossbarAvailable = null private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.CheckIfCrossbarAvailable(), AForge.Video.DirectShow.VideoCaptureDevice.DisplayCrossbarPropertyPage(), AForge.Video.DirectShow.VideoCaptureDevice.Start(), and AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
crossbarVideoInputs
VideoInput [] AForge.Video.DirectShow.VideoCaptureDevice.crossbarVideoInputs = null private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
crossbarVideoInput
VideoInput AForge.Video.DirectShow.VideoCaptureDevice.crossbarVideoInput = VideoInput.Default private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
cacheVideoCapabilities
Dictionary<string, VideoCapabilities[]> AForge.Video.DirectShow.VideoCaptureDevice.cacheVideoCapabilities = new Dictionary<string,VideoCapabilities[]>() static private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
cacheSnapshotCapabilities
Dictionary<string, VideoCapabilities[]> AForge.Video.DirectShow.VideoCaptureDevice.cacheSnapshotCapabilities = new Dictionary<string,VideoCapabilities[]>() static private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
cacheCrossbarVideoInputs
Dictionary<string, VideoInput[]> AForge.Video.DirectShow.VideoCaptureDevice.cacheCrossbarVideoInputs = new Dictionary<string,VideoInput[]>() static private
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.ColletCrossbarVideoInputs().
Property Documentation
CrossbarVideoInput
VideoInput AForge.Video.DirectShow.VideoCaptureDevice.CrossbarVideoInput get set
Current video input of capture card.
The property specifies video input to use for video devices like capture cards (those which provide crossbar configuration). List of available video inputs can be obtained from AvailableCrossbarVideoInputs property.
To check if the video device supports crossbar configuration, the CheckIfCrossbarAvailable method can be used.
<note>This property can be set as before running video device, as while running it.</note>
By default this property is set to VideoInput.Default, which means video input will not be set when running video device, but currently configured will be used. After video device is started this property will be updated anyway to tell current video input.
Referenced by AForge.Video.DirectShow.VideoCaptureDeviceForm.okButton_Click().
AvailableCrossbarVideoInputs
VideoInput []? AForge.Video.DirectShow.VideoCaptureDevice.AvailableCrossbarVideoInputs get
Available inputs of the video capture card.
The property provides list of video inputs for devices like video capture cards. Such devices usually provide several video inputs, which can be selected using crossbar. If video device represented by the object of this class supports crossbar, then this property will list all video inputs. However if it is a regular USB camera, for example, which does not provide crossbar configuration, the property will provide zero length array.
Video input to be used can be selected using CrossbarVideoInput. See also DisplayCrossbarPropertyPage method, which provides crossbar configuration dialog.
<note>It is recomended not to call this property immediately after Start method, since device may not start yet and provide its information. It is better to call the property before starting device or a bit after (but not immediately after).</note>
Referenced by AForge.Video.DirectShow.VideoCaptureDeviceForm.EnumeratedSupportedFrameSizes().
ProvideSnapshots
bool AForge.Video.DirectShow.VideoCaptureDevice.ProvideSnapshots get set
Specifies if snapshots should be provided or not.
Some USB cameras/devices may have a shutter button, which may result into snapshot if it is pressed. So the property specifies if the video source will try providing snapshots or not - it will check if the camera supports providing still image snapshots. If camera supports snapshots and the property is set to true, then snapshots will be provided through SnapshotFrame event.
Check supported sizes of snapshots using SnapshotCapabilities property and set the desired size using DesiredSnapshotSize property.
<note>The property must be set before running the video source to take effect.</note>
Default value of the property is set to false.
Referenced by Snapshot_Maker.MainForm.connectButton_Click(), Snapshot_Maker.MainForm.Disconnect(), AForge.Video.DirectShow.VideoCaptureDeviceForm.okButton_Click(), and Snapshot_Maker.MainForm.triggerButton_Click().
Source
virtual string AForge.Video.DirectShow.VideoCaptureDevice.Source get set
Video source.
Video source is represented by moniker string of video capture device.
Referenced by AForge.Video.DirectShow.VideoCaptureDeviceForm.okButton_Click().
FramesReceived
int AForge.Video.DirectShow.VideoCaptureDevice.FramesReceived get
Received frames count.
Number of frames the video source provided from the moment of the last access to the property.
BytesReceived
long AForge.Video.DirectShow.VideoCaptureDevice.BytesReceived get
Received bytes count.
Number of bytes the video source provided from the moment of the last access to the property.
IsRunning
bool AForge.Video.DirectShow.VideoCaptureDevice.IsRunning get
State of the video source.
Current state of video source object - running or not.
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.CheckIfCrossbarAvailable(), AForge.Video.DirectShow.VideoCaptureDevice.DisplayCrossbarPropertyPage(), AForge.Video.DirectShow.VideoCaptureDevice.DisplayPropertyPage(), AForge.Video.DirectShow.VideoCaptureDevice.Start(), and AForge.Video.DirectShow.VideoCaptureDevice.Stop().
DesiredFrameSize
Size AForge.Video.DirectShow.VideoCaptureDevice.DesiredFrameSize get set
Desired size of captured video frames.
The property sets desired video frame size. However capture device may not always provide video frames of configured size due to the fact that the size is not supported by it.
If the property is set to size (0, 0), then capture device uses its own default video frame size configuration.
Default value of the property is set to (0, 0).
<note>The property should be configured before video source is started to take effect.</note>
Referenced by Snapshot_Maker.MainForm.connectButton_Click(), and AForge.Video.DirectShow.VideoCaptureDeviceForm.okButton_Click().
DesiredSnapshotSize
Size AForge.Video.DirectShow.VideoCaptureDevice.DesiredSnapshotSize get set
Desired size of captured snapshot frames.
The property sets desired snapshot size. However capture device may not always provide snapshots of configured size due to the fact that the size is not supported by it.
If the property is set to size (0, 0), then capture device uses its own default snapshot size configuration.
See documentation to ProvideSnapshots for additional information.
Default value of the property is set to (0, 0).
<note>The property should be configured before video source is started to take effect.</note>
See also
ProvideSnapshots
Referenced by Snapshot_Maker.MainForm.connectButton_Click(), and AForge.Video.DirectShow.VideoCaptureDeviceForm.okButton_Click().
DesiredFrameRate
int AForge.Video.DirectShow.VideoCaptureDevice.DesiredFrameRate get set
Desired capture frame rate.
The property sets desired capture frame rate. However capture device may not always provide the exact configured frame rate due to its capabilities, system performance, etc.
If the property is set to 0, then capture device uses its own default frame rate.
Default value of the property is set to 0.
<note>The property should be configured before video source is started to take effect.</note>
Referenced by AForge.Video.DirectShow.VideoCaptureDeviceForm.okButton_Click(), and TwoCamerasTest.MainForm.StartCameras().
VideoCapabilities
VideoCapabilities []? AForge.Video.DirectShow.VideoCaptureDevice.VideoCapabilities get
Video capabilities of the device.
The property provides list of device's video capabilities.
<note>It is recomended not to call this property immediately after Start method, since device may not start yet and provide its information. It is better to call the property before starting device or a bit after (but not immediately after).</note>
Referenced by Snapshot_Maker.MainForm.EnumeratedSupportedFrameSizes(), and AForge.Video.DirectShow.VideoCaptureDeviceForm.EnumeratedSupportedFrameSizes().
SnapshotCapabilities
VideoCapabilities []? AForge.Video.DirectShow.VideoCaptureDevice.SnapshotCapabilities get
Snapshot capabilities of the device.
The property provides list of device's snapshot capabilities.
If the array has zero length, then it means that this device does not support making snapshots.
See documentation to ProvideSnapshots for additional information.
<note>It is recomended not to call this property immediately after Start method, since device may not start yet and provide its information. It is better to call the property before starting device or a bit after (but not immediately after).</note>
See also
ProvideSnapshots
Referenced by Snapshot_Maker.MainForm.EnumeratedSupportedFrameSizes(), and AForge.Video.DirectShow.VideoCaptureDeviceForm.EnumeratedSupportedFrameSizes().
SourceObject
object AForge.Video.DirectShow.VideoCaptureDevice.SourceObject get
Source COM object of camera capture device.
The source COM object of camera capture device is exposed for the case when user may need get direct access to the object for making some custom configuration of camera through DirectShow interface, for example.
If camera is not running, the property is set to null.
Event Documentation
NewFrame
NewFrameEventHandler AForge.Video.DirectShow.VideoCaptureDevice.NewFrame
New frame event.
Notifies clients about new available frame from video source.
<note>Since video source may have multiple clients, each client is responsible for making a copy (cloning) of the passed video frame, because the video source disposes its own original copy after notifying of clients.</note>
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.Grabber.BufferCB(), and AForge.Video.DirectShow.VideoCaptureDevice.OnNewFrame().
SnapshotFrame
NewFrameEventHandler AForge.Video.DirectShow.VideoCaptureDevice.SnapshotFrame
Snapshot frame event.
Notifies clients about new available snapshot frame - the one which comes when camera's snapshot/shutter button is pressed.
See documentation to ProvideSnapshots for additional information.
<note>Since video source may have multiple clients, each client is responsible for making a copy (cloning) of the passed snapshot frame, because the video source disposes its own original copy after notifying of clients.</note>
See also
ProvideSnapshots
Referenced by Snapshot_Maker.MainForm.connectButton_Click(), Snapshot_Maker.MainForm.Disconnect(), and AForge.Video.DirectShow.VideoCaptureDevice.OnSnapshotFrame().
VideoSourceError
VideoSourceErrorEventHandler AForge.Video.DirectShow.VideoCaptureDevice.VideoSourceError
Video source error event.
This event is used to notify clients about any type of errors occurred in video source object, for example internal exceptions.
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
PlayingFinished
PlayingFinishedEventHandler AForge.Video.DirectShow.VideoCaptureDevice.PlayingFinished
Video playing finished event.
This event is used to notify clients that the video playing has finished.
Referenced by AForge.Video.DirectShow.VideoCaptureDevice.WorkerThread().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Video.DirectShow/VideoCaptureDevice.cs