Doc: IGLib EXTENDED: AForge.Genetic.ExtendedGeneFunction Class Reference
AForge.Genetic.ExtendedGeneFunction Class Reference
Genetic programming gene, which represents arithmetic functions, common mathematical functions and arguments.
Public Member Functions
ExtendedGeneFunction (int variablesCount)
Initializes a new instance of the ExtendedGeneFunction class.
ExtendedGeneFunction (int variablesCount, GPGeneType type)
Initializes a new instance of the ExtendedGeneFunction class.
override string ToString ()
Get string representation of the gene.
IGPGene Clone ()
Clone the gene.
void Generate ()
Randomize gene with random type and value.
void Generate (GPGeneType type)
Randomize gene with random value.
IGPGene CreateNew ()
Creates new gene with random type and value.
IGPGene CreateNew (GPGeneType type)
Creates new gene with certain type and random value.
Protected Types
enum Functions {
Functions.Add, Functions.Subtract, Functions.Multiply, Functions.Divide,
Functions.Sin, Functions.Cos, Functions.Ln, Functions.Exp,
Functions.Sqrt
}
Enumeration of supported functions.
Static Protected Attributes
const int FunctionsCount = 9
Number of different functions supported by the class.
static ThreadSafeRandom rand = new ThreadSafeRandom()
Random number generator for chromosoms generation.
Properties
GPGeneType GeneType [get]
Gene type.
int ArgumentsCount [get]
Arguments count.
int MaxArgumentsCount [get]
Maximum arguments count.
Properties inherited from AForge.Genetic.IGPGene
GPGeneType GeneType [get]
Gene type.
int ArgumentsCount [get]
Arguments count.
int MaxArgumentsCount [get]
Maximum arguments count.
Private Member Functions
ExtendedGeneFunction (int variablesCount, bool random)
Private Attributes
GPGeneType type
int variablesCount
int val
int argumentsCount = 0
Detailed Description
Genetic programming gene, which represents arithmetic functions, common mathematical functions and arguments.
Extended gene function may represent arithmetic functions (+, -, *, /), some common mathematical functions (sin, cos, ln, exp, sqrt) or an argument to functions. This class is used by Genetic Programming (or Gene Expression Programming) chromosomes to build arbitrary expressions with help of genetic operators.
Member Enumeration Documentation
Functions
enum AForge.Genetic.ExtendedGeneFunction.Functions strong protected
Enumeration of supported functions.
Enumerator
Add
Addition operator.
Subtract
Suntraction operator.
Multiply
Multiplication operator.
Divide
Division operator.
Sin
Sine function.
Cos
Cosine function.
Ln
Natural logarithm function.
Exp
Exponent function.
Sqrt
Square root function.
Constructor & Destructor Documentation
ExtendedGeneFunction() [1/3]
AForge.Genetic.ExtendedGeneFunction.ExtendedGeneFunction (int variablesCount) inline
Initializes a new instance of the ExtendedGeneFunction class.
Parameters
variablesCount Total amount of variables in the task which is supposed to be solved.
The constructor creates randomly initialized gene with random type and value by calling Generate() method.
Referenced by AForge.Genetic.ExtendedGeneFunction.Clone(), and AForge.Genetic.ExtendedGeneFunction.CreateNew().
ExtendedGeneFunction() [2/3]
AForge.Genetic.ExtendedGeneFunction.ExtendedGeneFunction (int variablesCount, GPGeneType type) inline
Initializes a new instance of the ExtendedGeneFunction class.
Parameters
variablesCount Total amount of variables in the task which is supposed to be solved.
type Gene type to set.
The constructor creates randomly initialized gene with random value and preset gene type.
References AForge.Genetic.ExtendedGeneFunction.Generate(), AForge.Genetic.ExtendedGeneFunction.type, and AForge.Genetic.ExtendedGeneFunction.variablesCount.
ExtendedGeneFunction() [3/3]
AForge.Genetic.ExtendedGeneFunction.ExtendedGeneFunction (int variablesCount, bool random) inline private
References AForge.Genetic.ExtendedGeneFunction.Generate(), and AForge.Genetic.ExtendedGeneFunction.variablesCount.
Member Function Documentation
ToString()
override string AForge.Genetic.ExtendedGeneFunction.ToString () inline
Get string representation of the gene.
Returns
Returns string representation of the gene.
References AForge.Genetic.ExtendedGeneFunction.type, and AForge.Genetic.ExtendedGeneFunction.val.
Clone()
IGPGene AForge.Genetic.ExtendedGeneFunction.Clone () inline
Clone the gene.
The method clones the chromosome returning the exact copy of it.
Implements AForge.Genetic.IGPGene.
References AForge.Genetic.ExtendedGeneFunction.argumentsCount, AForge.Genetic.ExtendedGeneFunction.ExtendedGeneFunction(), AForge.Genetic.ExtendedGeneFunction.type, AForge.Genetic.ExtendedGeneFunction.val, and AForge.Genetic.ExtendedGeneFunction.variablesCount.
Generate() [1/2]
void AForge.Genetic.ExtendedGeneFunction.Generate () inline
Randomize gene with random type and value.
The method randomizes the gene, setting its type and value randomly.
Implements AForge.Genetic.IGPGene.
References AForge.ThreadSafeRandom.Next(), and AForge.Genetic.ExtendedGeneFunction.rand.
Referenced by AForge.Genetic.ExtendedGeneFunction.ExtendedGeneFunction().
Generate() [2/2]
void AForge.Genetic.ExtendedGeneFunction.Generate (GPGeneType type) inline
Randomize gene with random value.
Parameters
type Gene type to set.
The method randomizes a gene, setting its value randomly, but type is set to the specified one.
Implements AForge.Genetic.IGPGene.
References AForge.Genetic.ExtendedGeneFunction.argumentsCount, AForge.Genetic.ExtendedGeneFunction.FunctionsCount, AForge.ThreadSafeRandom.Next(), AForge.Genetic.ExtendedGeneFunction.rand, AForge.Genetic.ExtendedGeneFunction.type, AForge.Genetic.ExtendedGeneFunction.val, and AForge.Genetic.ExtendedGeneFunction.variablesCount.
CreateNew() [1/2]
IGPGene AForge.Genetic.ExtendedGeneFunction.CreateNew () inline
Creates new gene with random type and value.
The method creates new randomly initialized gene . The method is useful as factory method for those classes, which work with gene's interface, but not with particular gene class.
Implements AForge.Genetic.IGPGene.
References AForge.Genetic.ExtendedGeneFunction.ExtendedGeneFunction(), and AForge.Genetic.ExtendedGeneFunction.variablesCount.
CreateNew() [2/2]
IGPGene AForge.Genetic.ExtendedGeneFunction.CreateNew (GPGeneType type) inline
Creates new gene with certain type and random value.
Parameters
type Gene type to create.
The method creates new gene with specified type, but random value. The method is useful as factory method for those classes, which work with gene's interface, but not with particular gene class.
Implements AForge.Genetic.IGPGene.
References AForge.Genetic.ExtendedGeneFunction.ExtendedGeneFunction(), AForge.Genetic.ExtendedGeneFunction.type, and AForge.Genetic.ExtendedGeneFunction.variablesCount.
Member Data Documentation
FunctionsCount
const int AForge.Genetic.ExtendedGeneFunction.FunctionsCount = 9 static protected
Number of different functions supported by the class.
Referenced by AForge.Genetic.ExtendedGeneFunction.Generate().
type
GPGeneType AForge.Genetic.ExtendedGeneFunction.type private
Referenced by AForge.Genetic.ExtendedGeneFunction.Clone(), AForge.Genetic.ExtendedGeneFunction.CreateNew(), AForge.Genetic.ExtendedGeneFunction.ExtendedGeneFunction(), AForge.Genetic.ExtendedGeneFunction.Generate(), and AForge.Genetic.ExtendedGeneFunction.ToString().
variablesCount
int AForge.Genetic.ExtendedGeneFunction.variablesCount private
Referenced by AForge.Genetic.ExtendedGeneFunction.Clone(), AForge.Genetic.ExtendedGeneFunction.CreateNew(), AForge.Genetic.ExtendedGeneFunction.ExtendedGeneFunction(), and AForge.Genetic.ExtendedGeneFunction.Generate().
val
int AForge.Genetic.ExtendedGeneFunction.val private
Referenced by AForge.Genetic.ExtendedGeneFunction.Clone(), AForge.Genetic.ExtendedGeneFunction.Generate(), and AForge.Genetic.ExtendedGeneFunction.ToString().
argumentsCount
int AForge.Genetic.ExtendedGeneFunction.argumentsCount = 0 private
Referenced by AForge.Genetic.ExtendedGeneFunction.Clone(), and AForge.Genetic.ExtendedGeneFunction.Generate().
rand
ThreadSafeRandom AForge.Genetic.ExtendedGeneFunction.rand = new ThreadSafeRandom() static protected
Random number generator for chromosoms generation.
Referenced by AForge.Genetic.ExtendedGeneFunction.Generate().
Property Documentation
GeneType
GPGeneType AForge.Genetic.ExtendedGeneFunction.GeneType get
Gene type.
The property represents type of a gene - function, argument, etc.
ArgumentsCount
int AForge.Genetic.ExtendedGeneFunction.ArgumentsCount get
Arguments count.
Arguments count of a particular function gene.
MaxArgumentsCount
int AForge.Genetic.ExtendedGeneFunction.MaxArgumentsCount get
Maximum arguments count.
Maximum arguments count of a function gene supported by the class. The property may be used by chromosomes' classes to allocate correctly memory for functions' arguments, for example.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Genetic/Chromosomes/GP/ExtendedGeneFunction.cs