Doc: IGLib EXTENDED: Test.ExtremaTest Class Reference
Test.ExtremaTest Class Reference
Public Member Functions
void FindMinimaFromInterval ()
void FindMinimaFromPoint ()
void FindMaximaFromInterval ()
void FindMaximaFromPoint ()
void FindMinimumOfGamma ()
void FindSpaceMinimumOfRosenbock ()
void MinimizeGoldsteinPrice ()
Properties
TestContext TestContext [get, set]
Private Attributes
TestContext testContextInstance
TestExtremum[] testMinima
TestExtremum[] testMaxima
Member Function Documentation
FindMinimaFromInterval()
void Test.ExtremaTest.FindMinimaFromInterval () inline
References Meta.Numerics.Analysis.FunctionMath.FindMinimum(), Meta.Numerics.Analysis.Extremum.Location, Test.ExtremaTest.testMinima, and Meta.Numerics.Analysis.Extremum.Value.
FindMinimaFromPoint()
void Test.ExtremaTest.FindMinimaFromPoint () inline
References Meta.Numerics.Analysis.FunctionMath.FindMinimum(), Meta.Numerics.Analysis.Extremum.Location, Test.ExtremaTest.testMinima, and Meta.Numerics.Analysis.Extremum.Value.
FindMaximaFromInterval()
void Test.ExtremaTest.FindMaximaFromInterval () inline
References Meta.Numerics.Analysis.FunctionMath.FindMaximum(), Meta.Numerics.Analysis.Extremum.Location, Test.ExtremaTest.testMaxima, and Meta.Numerics.Analysis.Extremum.Value.
FindMaximaFromPoint()
void Test.ExtremaTest.FindMaximaFromPoint () inline
References Meta.Numerics.Analysis.FunctionMath.FindMaximum(), Meta.Numerics.Analysis.Extremum.Location, Test.ExtremaTest.testMaxima, and Meta.Numerics.Analysis.Extremum.Value.
FindMinimumOfGamma()
void Test.ExtremaTest.FindMinimumOfGamma () inline
References Meta.Numerics.Analysis.Extremum.Curvature, Meta.Numerics.Analysis.SpaceExtremum.Curvature(), Meta.Numerics.Matrices.SymmetricMatrix.Dimension, Meta.Numerics.Analysis.SpaceExtremum.Dimension, Meta.Numerics.Analysis.FunctionMath.FindMinimum(), Meta.Numerics.Functions.AdvancedMath.Gamma(), Meta.Numerics.Analysis.Extremum.Location, Meta.Numerics.Analysis.SpaceExtremum.Location(), Meta.Numerics.Analysis.Extremum.Value, and Meta.Numerics.Analysis.SpaceExtremum.Value.
FindSpaceMinimumOfRosenbock()
void Test.ExtremaTest.FindSpaceMinimumOfRosenbock () inline
References Meta.Numerics.Analysis.FunctionMath.FindMinimum(), Meta.Numerics.Analysis.SpaceExtremum.Location(), and Meta.Numerics.MoreMath.Pow().
MinimizeGoldsteinPrice()
void Test.ExtremaTest.MinimizeGoldsteinPrice () inline
References Meta.Numerics.Analysis.FunctionMath.FindMinimum(), and Meta.Numerics.MoreMath.Pow().
Member Data Documentation
testContextInstance
TestContext Test.ExtremaTest.testContextInstance private
testMinima
TestExtremum [] Test.ExtremaTest.testMinima private
Initial value:
= new TestExtremum[] {
            new TestExtremum(x => x * Math.Log(x), Interval.FromEndpoints(0.1, 1.0), 1.0 / Math.E, -1.0 / Math.E, Math.E),
            new TestExtremum(x => Math.Cos(x), Interval.FromEndpoints(0.0, 5.0), Math.PI, -1.0, 1.0),
            new TestExtremum(AdvancedMath.Gamma, Interval.FromEndpoints(0.0, 2.0), 1.461632144968362, 0.885603194410889, Double.NaN),
            new TestExtremum(Math.Abs, Interval.FromEndpoints(-2.0, 3.0), 0.0, 0.0, Double.NaN),
            new TestExtremum(Math.Cosh, Interval.FromEndpoints(-1.5, 2.5), 0.0, 1.0, 1.0),
            new TestExtremum(x => MoreMath.Pow(x, 4), Interval.FromEndpoints(-2.0, 1.0), 0.0, 0.0, Double.NaN)
        }
Referenced by Test.ExtremaTest.FindMinimaFromInterval(), and Test.ExtremaTest.FindMinimaFromPoint().
testMaxima
TestExtremum [] Test.ExtremaTest.testMaxima private
Initial value:
= new TestExtremum[] {
            new TestExtremum(Math.Sin, Interval.FromEndpoints(0.0, 5.0), Math.PI / 2.0, 1.0, 1.0),
            new TestExtremum(AdvancedMath.Dawson, Interval.FromEndpoints(0.0, 1.0), 0.92413887300459176701, 0.54104422463518169847, Double.NaN)
        }
Referenced by Test.ExtremaTest.FindMaximaFromInterval(), and Test.ExtremaTest.FindMaximaFromPoint().
Property Documentation
TestContext
TestContext Test.ExtremaTest.TestContext get set
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/ExtremaTest.cs