Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGBTRF Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGBTRF Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGBTRF (IDAMAX idamax, ILAENV ilaenv, DCOPY dcopy, DGBTF2 dgbtf2, DGEMM dgemm, DGER dger, DLASWP dlaswp, DSCAL dscal, DSWAP dswap, DTRSM dtrsm, XERBLA xerbla)
DGBTRF ()
void Run (int M, int N, int KL, int KU, ref double[] AB, int offset_ab, int LDAB, ref int[] IPIV, int offset_ipiv, ref int INFO)
Private Attributes
IDAMAX _idamax
ILAENV _ilaenv
DCOPY _dcopy
DGBTF2 _dgbtf2
DGEMM _dgemm
DGER _dger
DLASWP _dlaswp
DSCAL _dscal
DSWAP _dswap
DTRSM _dtrsm
XERBLA _xerbla
double[] WORK13 = new double[LDWORK * NBMAX]
double[] WORK31 = new double[LDWORK * NBMAX]
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
const int NBMAX = 64
const int LDWORK = NBMAX + 1
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGBTRF computes an LU factorization of a real m-by-n band matrix A using partial pivoting with row interchanges.
This is the blocked version of the algorithm, calling Level 3 BLAS.
/summary>
Constructor & Destructor Documentation
DGBTRF() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGBTRF.DGBTRF (IDAMAX idamax, ILAENV ilaenv, DCOPY dcopy, DGBTF2 dgbtf2, DGEMM dgemm, DGER dger, DLASWP dlaswp, DSCAL dscal, DSWAP dswap, DTRSM dtrsm, XERBLA xerbla) inline
DGBTRF() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGBTRF.DGBTRF () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGBTRF.Run (int M, int N, int KL, int KU, ref double[] AB, int offset_ab, int LDAB, ref int[] IPIV, int offset_ipiv, ref int INFO) inline
Purpose
DGBTRF computes an LU factorization of a real m-by-n band matrix A using partial pivoting with row interchanges.
This is the blocked version of the algorithm, calling Level 3 BLAS.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. 0. /param>
Parameters
KL (input) INTEGER The number of subdiagonals within the band of A. KL .GE. 0. /param>
Parameters
KU (input) INTEGER The number of superdiagonals within the band of A. KU .GE. 0. /param>
Parameters
AB (input/output) DOUBLE PRECISION array, dimension (LDAB,N) On entry, the matrix A in band storage, in rows KL+1 to 2*KL+KU+1; rows 1 to KL of the array need not be set. The j-th column of A is stored in the j-th column of the array AB as follows: AB(kl+ku+1+i-j,j) = A(i,j) for max(1,j-ku).LE.i.LE.min(m,j+kl)
On exit, details of the factorization: U is stored as an upper triangular band matrix with KL+KU superdiagonals in rows 1 to KL+KU+1, and the multipliers used during the factorization are stored in rows KL+KU+2 to 2*KL+KU+1. See below for further details. /param>
Parameters
LDAB (input) INTEGER The leading dimension of the array AB. LDAB .GE. 2*KL+KU+1. /param>
Parameters
IPIV (output) INTEGER array, dimension (min(M,N)) The pivot indices; for 1 .LE. i .LE. min(M,N), row i of the matrix was interchanged with row IPIV(i). /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value .GT. 0: if INFO = +i, U(i,i) is exactly zero. The factorization has been completed, but the factor U is exactly singular, and division by zero will occur if it is used to solve a system of equations. /param>
References DotNumerics.LinearAlgebra.CSLapack.DGBTRF.LDWORK, DotNumerics.LinearAlgebra.CSLapack.DGBTRF.NBMAX, DotNumerics.LinearAlgebra.CSLapack.DGBTRF.ONE, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.IDAMAX.Run(), DotNumerics.LinearAlgebra.CSLapack.DSWAP.Run(), DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASWP.Run(), DotNumerics.LinearAlgebra.CSLapack.DGBTF2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGER.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRSM.Run(), DotNumerics.LinearAlgebra.CSLapack.DGBTRF.WORK13, DotNumerics.LinearAlgebra.CSLapack.DGBTRF.WORK31, and DotNumerics.LinearAlgebra.CSLapack.DGBTRF.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGBSV.Run().
Member Data Documentation
_idamax
IDAMAX DotNumerics.LinearAlgebra.CSLapack.DGBTRF._idamax private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DGBTRF._ilaenv private
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DGBTRF._dcopy private
_dgbtf2
DGBTF2 DotNumerics.LinearAlgebra.CSLapack.DGBTRF._dgbtf2 private
_dgemm
DGEMM DotNumerics.LinearAlgebra.CSLapack.DGBTRF._dgemm private
_dger
DGER DotNumerics.LinearAlgebra.CSLapack.DGBTRF._dger private
_dlaswp
DLASWP DotNumerics.LinearAlgebra.CSLapack.DGBTRF._dlaswp private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DGBTRF._dscal private
_dswap
DSWAP DotNumerics.LinearAlgebra.CSLapack.DGBTRF._dswap private
_dtrsm
DTRSM DotNumerics.LinearAlgebra.CSLapack.DGBTRF._dtrsm private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGBTRF._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGBTRF.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGBTRF.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DGBTRF.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGBTRF.Run().
NBMAX
const int DotNumerics.LinearAlgebra.CSLapack.DGBTRF.NBMAX = 64 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGBTRF.Run().
LDWORK
const int DotNumerics.LinearAlgebra.CSLapack.DGBTRF.LDWORK = NBMAX + 1 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGBTRF.Run().
WORK13
double [] DotNumerics.LinearAlgebra.CSLapack.DGBTRF.WORK13 = new double[LDWORK * NBMAX] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGBTRF.Run().
WORK31
double [] DotNumerics.LinearAlgebra.CSLapack.DGBTRF.WORK31 = new double[LDWORK * NBMAX] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGBTRF.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgbtrf.cs