Doc: IGLib EXTENDED: Approximation.MainForm Class Reference
Approximation.MainForm Class Reference
Summary description for Form1.
Public Member Functions
MainForm ()
MainForm ()
MainForm ()
MainForm ()
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
delegate void SetTextCallback (System.Windows.Forms.Control control, string text)
The main entry point for the application.
delegate void ClearListCallback (System.Windows.Forms.ListView control)
delegate ListViewItem AddListItemCallback (System.Windows.Forms.ListView control, string itemText)
delegate void AddListSubitemCallback (ListViewItem item, string subItemText)
void SetText (System.Windows.Forms.Control control, string text)
void ClearList (System.Windows.Forms.ListView control)
ListViewItem AddListItem (System.Windows.Forms.ListView control, string itemText)
void AddListSubitem (ListViewItem item, string subItemText)
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void btLoad_Click_1 (object sender, EventArgs e)
void loadButton_Click (object sender, System.EventArgs e)
void UpdateSettings ()
void ChooseFile ()
void UpdateDataListView ()
void UpdateDataListViewTKTest ()
void oneNeuronForTwoCheck_CheckedChanged (object sender, System.EventArgs e)
delegate void EnableCallback (bool enable)
void EnableControls (bool enable)
void ClearSolution ()
void btStart_Click (object sender, EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void startButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void lvPodatki_SelectedIndexChanged (object sender, EventArgs e)
void tbClasses_TextChanged (object sender, EventArgs e)
void neuronsBox_TextChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void loadDataButton_Click (object sender, System.EventArgs e)
void UpdateDataListView ()
void EnableControls (bool enable)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void loadDataButton_Click (object sender, System.EventArgs e)
void UpdateDataListView ()
void EnableControls (bool enable)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
delegate void SetTextCallback (System.Windows.Forms.Control control, string text)
void SetText (System.Windows.Forms.Control control, string text)
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void loadDataButton_Click (object sender, System.EventArgs e)
void UpdateDataListView ()
delegate void EnableCallback (bool enable)
void EnableControls (bool enable)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
delegate void SetTextCallback (System.Windows.Forms.Control control, string text)
void SetText (System.Windows.Forms.Control control, string text)
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void loadDataButton_Click (object sender, System.EventArgs e)
void UpdateDataListView ()
delegate void EnableCallback (bool enable)
void EnableControls (bool enable)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
Static Private Member Functions
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
Private Attributes
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.Button loadButton
System.Windows.Forms.OpenFileDialog openFileDialog
System.Windows.Forms.ListView dataList
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.TextBox learningRateBox
System.Windows.Forms.Label label1
System.Windows.Forms.Label label2
System.Windows.Forms.TextBox alphaBox
System.Windows.Forms.Label label3
System.Windows.Forms.TextBox errorLimitBox
System.Windows.Forms.Label label4
System.Windows.Forms.TextBox iterationsBox
System.Windows.Forms.Label label5
System.Windows.Forms.Label label6
System.Windows.Forms.TextBox neuronsBox
System.Windows.Forms.CheckBox oneNeuronForTwoCheck
System.Windows.Forms.Label label7
System.Windows.Forms.Label label8
System.Windows.Forms.TextBox currentIterationBox
System.Windows.Forms.Button stopButton
System.Windows.Forms.Button startButton
System.Windows.Forms.Label label9
System.Windows.Forms.Label label10
System.Windows.Forms.TextBox classesBox
System.Windows.Forms.CheckBox errorLimitCheck
System.Windows.Forms.Label label11
System.Windows.Forms.TextBox currentErrorBox
System.Windows.Forms.GroupBox groupBox3
System.Windows.Forms.Label label12
System.Windows.Forms.ListView weightsList
System.Windows.Forms.Label label13
System.Windows.Forms.ColumnHeader columnHeader1
System.Windows.Forms.ColumnHeader columnHeader2
System.Windows.Forms.ColumnHeader columnHeader3
System.Windows.Forms.CheckBox saveFilesCheck
AForge.Controls.Chart errorChart
System.ComponentModel.Container components = null
Required designer variable.
int samples = 0
int variables = 0
double[,] data = null
int[] classes = null
int classesCount = 0
int[] samplesPerClass = null
int neuronsCount = 0
double learningRate = 0.1
double sigmoidAlphaValue = 2.0
double learningErrorLimit = 0.1
double iterationLimit = 1000
bool useOneNeuronForTwoClasses = false
bool useErrorLimit = true
bool saveStatisticsToFiles = false
Thread workerThread = null
ListView lvPodatki
Button btLoad
Label label14
TextBox tbClasses
Button btStart
bool needToStop = false
string _filePath = "../../data/aforge/"
bool _fileChosen = false
System.Windows.Forms.Button loadDataButton
System.Windows.Forms.ColumnHeader xColumnHeader
System.Windows.Forms.ColumnHeader yColumnHeader
AForge.Controls.Chart chart
System.Windows.Forms.TextBox momentumBox
System.Windows.Forms.GroupBox groupBox4
double momentum = 0.0
int neuronsInFirstLayer = 20
int iterations = 1000
System.Windows.Forms.TextBox populationSizeBox
System.Windows.Forms.ComboBox selectionBox
System.Windows.Forms.ComboBox functionsSetBox
System.Windows.Forms.ComboBox geneticMethodBox
System.Windows.Forms.GroupBox groupBox5
System.Windows.Forms.TextBox solutionBox
int populationSize = 100
int selectionMethod = 0
int functionsSet = 0
int geneticMethod = 0
volatile bool needToStop = false
Detailed Description
Summary description for Form1.
Constructor & Destructor Documentation
MainForm() [1/5]
Approximation.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), Approximation.MainForm.errorChart, Approximation.MainForm.InitializeComponent(), and Approximation.MainForm.UpdateSettings().
Referenced by Approximation.MainForm.Main().
MainForm() [2/5]
Approximation.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), Approximation.MainForm.chart, Approximation.MainForm.InitializeComponent(), and Approximation.MainForm.UpdateSettings().
MainForm() [3/5]
Approximation.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), Approximation.MainForm.chart, Approximation.MainForm.InitializeComponent(), and Approximation.MainForm.UpdateSettings().
MainForm() [4/5]
Approximation.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), Approximation.MainForm.chart, Approximation.MainForm.functionsSet, Approximation.MainForm.functionsSetBox, Approximation.MainForm.geneticMethod, Approximation.MainForm.geneticMethodBox, Approximation.MainForm.InitializeComponent(), Approximation.MainForm.selectionBox, Approximation.MainForm.selectionMethod, and Approximation.MainForm.UpdateSettings().
MainForm() [5/5]
Approximation.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), Approximation.MainForm.chart, Approximation.MainForm.InitializeComponent(), and Approximation.MainForm.UpdateSettings().
Member Function Documentation
Dispose() [1/5]
override void Approximation.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References Approximation.MainForm.components.
InitializeComponent() [1/5]
void Approximation.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by Approximation.MainForm.MainForm().
SetTextCallback() [1/3]
delegate void Approximation.MainForm.SetTextCallback (System.Windows.Forms.Control control, string text) private
The main entry point for the application.
Referenced by Approximation.MainForm.SetText().
ClearListCallback()
delegate void Approximation.MainForm.ClearListCallback (System.Windows.Forms.ListView control) private
Referenced by Approximation.MainForm.ClearList().
AddListItemCallback()
delegate ListViewItem Approximation.MainForm.AddListItemCallback (System.Windows.Forms.ListView control, string itemText) private
Referenced by Approximation.MainForm.AddListItem().
AddListSubitemCallback()
delegate void Approximation.MainForm.AddListSubitemCallback (ListViewItem item, string subItemText) private
Referenced by Approximation.MainForm.AddListSubitem().
SetText() [1/3]
void Approximation.MainForm.SetText (System.Windows.Forms.Control control, string text) inline private
References Approximation.MainForm.SetTextCallback().
Referenced by Approximation.MainForm.SearchSolution(), and Approximation.MainForm.SetText().
ClearList()
void Approximation.MainForm.ClearList (System.Windows.Forms.ListView control) inline private
References Approximation.MainForm.ClearListCallback().
Referenced by Approximation.MainForm.SearchSolution().
AddListItem()
ListViewItem Approximation.MainForm.AddListItem (System.Windows.Forms.ListView control, string itemText) inline private
References Approximation.MainForm.AddListItemCallback().
Referenced by Approximation.MainForm.SearchSolution().
AddListSubitem()
void Approximation.MainForm.AddListSubitem (ListViewItem item, string subItemText) inline private
References Approximation.MainForm.AddListSubitemCallback().
Referenced by Approximation.MainForm.SearchSolution().
MainForm_Closing() [1/5]
void Approximation.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References Approximation.MainForm.needToStop, and Approximation.MainForm.workerThread.
btLoad_Click_1()
void Approximation.MainForm.btLoad_Click_1 (object sender, EventArgs e) inline private
References Approximation.MainForm.classes, Approximation.MainForm.classesCount, Approximation.MainForm.ClearSolution(), Approximation.MainForm.data, Approximation.MainForm.neuronsBox, Approximation.MainForm.neuronsCount, Approximation.MainForm.oneNeuronForTwoCheck, Approximation.MainForm.openFileDialog, Approximation.MainForm.samples, Approximation.MainForm.samplesPerClass, Approximation.MainForm.startButton, Approximation.MainForm.tbClasses, Approximation.MainForm.UpdateDataListViewTKTest(), Approximation.MainForm.useOneNeuronForTwoClasses, and Approximation.MainForm.variables.
loadButton_Click()
void Approximation.MainForm.loadButton_Click (object sender, System.EventArgs e) inline private
References Approximation.MainForm.classes, Approximation.MainForm.classesBox, Approximation.MainForm.classesCount, Approximation.MainForm.ClearSolution(), Approximation.MainForm.data, Approximation.MainForm.neuronsBox, Approximation.MainForm.neuronsCount, Approximation.MainForm.oneNeuronForTwoCheck, Approximation.MainForm.openFileDialog, Approximation.MainForm.samples, Approximation.MainForm.samplesPerClass, Approximation.MainForm.startButton, Approximation.MainForm.UpdateDataListView(), Approximation.MainForm.useOneNeuronForTwoClasses, and Approximation.MainForm.variables.
UpdateSettings() [1/5]
void Approximation.MainForm.UpdateSettings () inline private
References Approximation.MainForm.alphaBox, Approximation.MainForm.errorLimitBox, Approximation.MainForm.errorLimitCheck, Approximation.MainForm.iterationLimit, Approximation.MainForm.iterationsBox, Approximation.MainForm.learningErrorLimit, Approximation.MainForm.learningRate, Approximation.MainForm.learningRateBox, Approximation.MainForm.oneNeuronForTwoCheck, Approximation.MainForm.saveFilesCheck, Approximation.MainForm.saveStatisticsToFiles, Approximation.MainForm.sigmoidAlphaValue, Approximation.MainForm.useErrorLimit, and Approximation.MainForm.useOneNeuronForTwoClasses.
Referenced by Approximation.MainForm.btStart_Click(), Approximation.MainForm.MainForm(), and Approximation.MainForm.startButton_Click().
ChooseFile()
void Approximation.MainForm.ChooseFile () inline private
References Approximation.MainForm._fileChosen, and Approximation.MainForm._filePath.
UpdateDataListView() [1/5]
void Approximation.MainForm.UpdateDataListView () inline private
References Approximation.MainForm.classes, Approximation.MainForm.data, Approximation.MainForm.dataList, Approximation.MainForm.samples, and Approximation.MainForm.variables.
Referenced by Approximation.MainForm.loadButton_Click(), and Approximation.MainForm.loadDataButton_Click().
UpdateDataListViewTKTest()
void Approximation.MainForm.UpdateDataListViewTKTest () inline private
References Approximation.MainForm.classes, Approximation.MainForm.data, Approximation.MainForm.lvPodatki, Approximation.MainForm.samples, and Approximation.MainForm.variables.
Referenced by Approximation.MainForm.btLoad_Click_1().
oneNeuronForTwoCheck_CheckedChanged()
void Approximation.MainForm.oneNeuronForTwoCheck_CheckedChanged (object sender, System.EventArgs e) inline private
References Approximation.MainForm.classesCount, Approximation.MainForm.neuronsBox, Approximation.MainForm.neuronsCount, Approximation.MainForm.oneNeuronForTwoCheck, and Approximation.MainForm.useOneNeuronForTwoClasses.
EnableCallback() [1/3]
delegate void Approximation.MainForm.EnableCallback (bool enable) private
Referenced by Approximation.MainForm.EnableControls().
EnableControls() [1/5]
void Approximation.MainForm.EnableControls (bool enable) inline private
References Approximation.MainForm.alphaBox, Approximation.MainForm.classesCount, Approximation.MainForm.EnableCallback(), Approximation.MainForm.errorLimitBox, Approximation.MainForm.errorLimitCheck, Approximation.MainForm.iterationsBox, Approximation.MainForm.learningRateBox, Approximation.MainForm.loadButton, Approximation.MainForm.oneNeuronForTwoCheck, Approximation.MainForm.saveFilesCheck, Approximation.MainForm.startButton, and Approximation.MainForm.stopButton.
Referenced by Approximation.MainForm.btStart_Click(), Approximation.MainForm.EnableControls(), Approximation.MainForm.SearchSolution(), and Approximation.MainForm.startButton_Click().
ClearSolution()
void Approximation.MainForm.ClearSolution () inline private
References Approximation.MainForm.currentErrorBox, Approximation.MainForm.currentIterationBox, Approximation.MainForm.errorChart, AForge.Controls.Chart.UpdateDataSeries(), and Approximation.MainForm.weightsList.
Referenced by Approximation.MainForm.btLoad_Click_1(), and Approximation.MainForm.loadButton_Click().
btStart_Click()
void Approximation.MainForm.btStart_Click (object sender, EventArgs e) inline private
References Approximation.MainForm.alphaBox, Approximation.MainForm.EnableControls(), Approximation.MainForm.errorLimitBox, Approximation.MainForm.errorLimitCheck, Approximation.MainForm.iterationLimit, Approximation.MainForm.iterationsBox, Approximation.MainForm.learningErrorLimit, Approximation.MainForm.learningRate, Approximation.MainForm.learningRateBox, Approximation.MainForm.needToStop, Approximation.MainForm.oneNeuronForTwoCheck, Approximation.MainForm.saveFilesCheck, Approximation.MainForm.saveStatisticsToFiles, Approximation.MainForm.SearchSolution(), Approximation.MainForm.sigmoidAlphaValue, Approximation.MainForm.UpdateSettings(), Approximation.MainForm.useErrorLimit, Approximation.MainForm.useOneNeuronForTwoClasses, and Approximation.MainForm.workerThread.
stopButton_Click() [1/5]
void Approximation.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References Approximation.MainForm.needToStop, and Approximation.MainForm.workerThread.
startButton_Click() [1/5]
void Approximation.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References Approximation.MainForm.alphaBox, Approximation.MainForm.EnableControls(), Approximation.MainForm.errorLimitBox, Approximation.MainForm.errorLimitCheck, Approximation.MainForm.iterationLimit, Approximation.MainForm.iterationsBox, Approximation.MainForm.learningErrorLimit, Approximation.MainForm.learningRate, Approximation.MainForm.learningRateBox, Approximation.MainForm.needToStop, Approximation.MainForm.oneNeuronForTwoCheck, Approximation.MainForm.saveFilesCheck, Approximation.MainForm.saveStatisticsToFiles, Approximation.MainForm.SearchSolution(), Approximation.MainForm.sigmoidAlphaValue, Approximation.MainForm.UpdateSettings(), Approximation.MainForm.useErrorLimit, Approximation.MainForm.useOneNeuronForTwoClasses, and Approximation.MainForm.workerThread.
SearchSolution() [1/5]
void Approximation.MainForm.SearchSolution () inline private
References Approximation.MainForm.AddListItem(), Approximation.MainForm.AddListSubitem(), Approximation.MainForm.classes, Approximation.MainForm.classesCount, Approximation.MainForm.ClearList(), Approximation.MainForm.currentErrorBox, Approximation.MainForm.currentIterationBox, Approximation.MainForm.data, Approximation.MainForm.EnableControls(), Approximation.MainForm.errorChart, Approximation.MainForm.iterationLimit, Approximation.MainForm.learningErrorLimit, AForge.Neuro.Learning.DeltaRuleLearning.LearningRate, Approximation.MainForm.learningRate, Approximation.MainForm.needToStop, Approximation.MainForm.neuronsCount, AForge.Controls.Chart.RangeX, AForge.Neuro.Learning.DeltaRuleLearning.RunEpoch(), Approximation.MainForm.samples, Approximation.MainForm.saveStatisticsToFiles, Approximation.MainForm.SetText(), Approximation.MainForm.sigmoidAlphaValue, AForge.Controls.Chart.UpdateDataSeries(), Approximation.MainForm.useErrorLimit, Approximation.MainForm.useOneNeuronForTwoClasses, Approximation.MainForm.variables, and Approximation.MainForm.weightsList.
Referenced by Approximation.MainForm.btStart_Click(), and Approximation.MainForm.startButton_Click().
lvPodatki_SelectedIndexChanged()
void Approximation.MainForm.lvPodatki_SelectedIndexChanged (object sender, EventArgs e) inline private
tbClasses_TextChanged()
void Approximation.MainForm.tbClasses_TextChanged (object sender, EventArgs e) inline private
neuronsBox_TextChanged()
void Approximation.MainForm.neuronsBox_TextChanged (object sender, EventArgs e) inline private
Dispose() [2/5]
override void Approximation.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References Approximation.MainForm.components.
InitializeComponent() [2/5]
void Approximation.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [1/4]
static void Approximation.MainForm.Main () inline static private
The main entry point for the application.
References Approximation.MainForm.MainForm().
MainForm_Closing() [2/5]
void Approximation.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References Approximation.MainForm.needToStop, and Approximation.MainForm.workerThread.
UpdateSettings() [2/5]
void Approximation.MainForm.UpdateSettings () inline private
References Approximation.MainForm.alphaBox, Approximation.MainForm.iterations, Approximation.MainForm.iterationsBox, Approximation.MainForm.learningRate, Approximation.MainForm.learningRateBox, Approximation.MainForm.momentum, Approximation.MainForm.momentumBox, Approximation.MainForm.neuronsBox, Approximation.MainForm.neuronsInFirstLayer, and Approximation.MainForm.sigmoidAlphaValue.
loadDataButton_Click() [1/4]
void Approximation.MainForm.loadDataButton_Click (object sender, System.EventArgs e) inline private
References Approximation.MainForm.chart, Approximation.MainForm.data, Approximation.MainForm.openFileDialog, AForge.Controls.Chart.RangeX, Approximation.MainForm.startButton, Approximation.MainForm.UpdateDataListView(), and AForge.Controls.Chart.UpdateDataSeries().
UpdateDataListView() [2/5]
void Approximation.MainForm.UpdateDataListView () inline private
References Approximation.MainForm.data, and Approximation.MainForm.dataList.
EnableControls() [2/5]
void Approximation.MainForm.EnableControls (bool enable) inline private
References Approximation.MainForm.alphaBox, Approximation.MainForm.iterationsBox, Approximation.MainForm.learningRateBox, Approximation.MainForm.loadDataButton, Approximation.MainForm.momentumBox, Approximation.MainForm.neuronsBox, Approximation.MainForm.startButton, and Approximation.MainForm.stopButton.
startButton_Click() [2/5]
void Approximation.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References Approximation.MainForm.alphaBox, Approximation.MainForm.EnableControls(), Approximation.MainForm.iterations, Approximation.MainForm.iterationsBox, Approximation.MainForm.learningRate, Approximation.MainForm.learningRateBox, Approximation.MainForm.momentum, Approximation.MainForm.momentumBox, Approximation.MainForm.needToStop, Approximation.MainForm.neuronsBox, Approximation.MainForm.neuronsInFirstLayer, Approximation.MainForm.SearchSolution(), Approximation.MainForm.sigmoidAlphaValue, Approximation.MainForm.UpdateSettings(), and Approximation.MainForm.workerThread.
stopButton_Click() [2/5]
void Approximation.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References Approximation.MainForm.needToStop, and Approximation.MainForm.workerThread.
SearchSolution() [2/5]
void Approximation.MainForm.SearchSolution () inline private
References Approximation.MainForm.chart, AForge.Neuro.Network.Compute(), Approximation.MainForm.currentErrorBox, Approximation.MainForm.currentIterationBox, Approximation.MainForm.data, Approximation.MainForm.EnableControls(), Approximation.MainForm.iterations, AForge.Neuro.Learning.BackPropagationLearning.LearningRate, Approximation.MainForm.learningRate, AForge.DoubleRange.Length, AForge.DoubleRange.Min, AForge.Neuro.Learning.BackPropagationLearning.Momentum, Approximation.MainForm.momentum, Approximation.MainForm.needToStop, Approximation.MainForm.neuronsInFirstLayer, AForge.Controls.Chart.RangeX, AForge.Controls.Chart.RangeY, AForge.Neuro.Learning.BackPropagationLearning.RunEpoch(), Approximation.MainForm.samples, Approximation.MainForm.sigmoidAlphaValue, and AForge.Controls.Chart.UpdateDataSeries().
Dispose() [3/5]
override void Approximation.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References Approximation.MainForm.components.
InitializeComponent() [3/5]
void Approximation.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [2/4]
static void Approximation.MainForm.Main () inline static private
The main entry point for the application.
References Approximation.MainForm.MainForm().
MainForm_Closing() [3/5]
void Approximation.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References Approximation.MainForm.needToStop, and Approximation.MainForm.workerThread.
UpdateSettings() [3/5]
void Approximation.MainForm.UpdateSettings () inline private
References Approximation.MainForm.alphaBox, Approximation.MainForm.iterations, Approximation.MainForm.iterationsBox, Approximation.MainForm.learningRate, Approximation.MainForm.learningRateBox, Approximation.MainForm.momentum, Approximation.MainForm.momentumBox, Approximation.MainForm.neuronsBox, Approximation.MainForm.neuronsInFirstLayer, and Approximation.MainForm.sigmoidAlphaValue.
loadDataButton_Click() [2/4]
void Approximation.MainForm.loadDataButton_Click (object sender, System.EventArgs e) inline private
References Approximation.MainForm.chart, Approximation.MainForm.data, Approximation.MainForm.openFileDialog, AForge.Controls.Chart.RangeX, Approximation.MainForm.startButton, Approximation.MainForm.UpdateDataListView(), and AForge.Controls.Chart.UpdateDataSeries().
UpdateDataListView() [3/5]
void Approximation.MainForm.UpdateDataListView () inline private
References Approximation.MainForm.data, and Approximation.MainForm.dataList.
EnableControls() [3/5]
void Approximation.MainForm.EnableControls (bool enable) inline private
References Approximation.MainForm.alphaBox, Approximation.MainForm.iterationsBox, Approximation.MainForm.learningRateBox, Approximation.MainForm.loadDataButton, Approximation.MainForm.momentumBox, Approximation.MainForm.neuronsBox, Approximation.MainForm.startButton, and Approximation.MainForm.stopButton.
startButton_Click() [3/5]
void Approximation.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References Approximation.MainForm.alphaBox, Approximation.MainForm.EnableControls(), Approximation.MainForm.iterations, Approximation.MainForm.iterationsBox, Approximation.MainForm.learningRate, Approximation.MainForm.learningRateBox, Approximation.MainForm.momentum, Approximation.MainForm.momentumBox, Approximation.MainForm.needToStop, Approximation.MainForm.neuronsBox, Approximation.MainForm.neuronsInFirstLayer, Approximation.MainForm.SearchSolution(), Approximation.MainForm.sigmoidAlphaValue, Approximation.MainForm.UpdateSettings(), and Approximation.MainForm.workerThread.
stopButton_Click() [3/5]
void Approximation.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References Approximation.MainForm.needToStop, and Approximation.MainForm.workerThread.
SearchSolution() [3/5]
void Approximation.MainForm.SearchSolution () inline private
References Approximation.MainForm.chart, AForge.Neuro.Network.Compute(), Approximation.MainForm.currentErrorBox, Approximation.MainForm.currentIterationBox, Approximation.MainForm.data, Approximation.MainForm.EnableControls(), Approximation.MainForm.iterations, AForge.Neuro.Learning.BackPropagationLearning.LearningRate, Approximation.MainForm.learningRate, AForge.DoubleRange.Length, AForge.DoubleRange.Min, AForge.Neuro.Learning.BackPropagationLearning.Momentum, Approximation.MainForm.momentum, Approximation.MainForm.needToStop, Approximation.MainForm.neuronsInFirstLayer, AForge.Controls.Chart.RangeX, AForge.Controls.Chart.RangeY, AForge.Neuro.Learning.BackPropagationLearning.RunEpoch(), Approximation.MainForm.samples, Approximation.MainForm.sigmoidAlphaValue, and AForge.Controls.Chart.UpdateDataSeries().
Dispose() [4/5]
override void Approximation.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References Approximation.MainForm.components.
InitializeComponent() [4/5]
void Approximation.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [3/4]
static void Approximation.MainForm.Main () inline static private
The main entry point for the application.
References Approximation.MainForm.MainForm().
SetTextCallback() [2/3]
delegate void Approximation.MainForm.SetTextCallback (System.Windows.Forms.Control control, string text) private
SetText() [2/3]
void Approximation.MainForm.SetText (System.Windows.Forms.Control control, string text) inline private
References Approximation.MainForm.SetText(), and Approximation.MainForm.SetTextCallback().
MainForm_Closing() [4/5]
void Approximation.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References Approximation.MainForm.needToStop, and Approximation.MainForm.workerThread.
UpdateSettings() [4/5]
void Approximation.MainForm.UpdateSettings () inline private
References Approximation.MainForm.iterations, Approximation.MainForm.iterationsBox, Approximation.MainForm.populationSize, and Approximation.MainForm.populationSizeBox.
loadDataButton_Click() [3/4]
void Approximation.MainForm.loadDataButton_Click (object sender, System.EventArgs e) inline private
References Approximation.MainForm.chart, Approximation.MainForm.data, Approximation.MainForm.openFileDialog, AForge.Controls.Chart.RangeX, Approximation.MainForm.startButton, Approximation.MainForm.UpdateDataListView(), and AForge.Controls.Chart.UpdateDataSeries().
UpdateDataListView() [4/5]
void Approximation.MainForm.UpdateDataListView () inline private
References Approximation.MainForm.data, and Approximation.MainForm.dataList.
EnableCallback() [2/3]
delegate void Approximation.MainForm.EnableCallback (bool enable) private
EnableControls() [4/5]
void Approximation.MainForm.EnableControls (bool enable) inline private
References Approximation.MainForm.EnableCallback(), Approximation.MainForm.EnableControls(), Approximation.MainForm.functionsSetBox, Approximation.MainForm.geneticMethodBox, Approximation.MainForm.iterationsBox, Approximation.MainForm.loadDataButton, Approximation.MainForm.populationSizeBox, Approximation.MainForm.selectionBox, Approximation.MainForm.startButton, and Approximation.MainForm.stopButton.
startButton_Click() [4/5]
void Approximation.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References Approximation.MainForm.EnableControls(), Approximation.MainForm.functionsSet, Approximation.MainForm.functionsSetBox, Approximation.MainForm.geneticMethod, Approximation.MainForm.geneticMethodBox, Approximation.MainForm.iterations, Approximation.MainForm.iterationsBox, Approximation.MainForm.needToStop, Approximation.MainForm.populationSize, Approximation.MainForm.populationSizeBox, Approximation.MainForm.SearchSolution(), Approximation.MainForm.selectionBox, Approximation.MainForm.selectionMethod, Approximation.MainForm.solutionBox, Approximation.MainForm.UpdateSettings(), and Approximation.MainForm.workerThread.
stopButton_Click() [4/5]
void Approximation.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References Approximation.MainForm.needToStop, and Approximation.MainForm.workerThread.
SearchSolution() [4/5]
void Approximation.MainForm.SearchSolution () inline private
References AForge.Genetic.Population.BestChromosome, Approximation.MainForm.chart, Approximation.MainForm.currentErrorBox, Approximation.MainForm.currentIterationBox, Approximation.MainForm.data, Approximation.MainForm.EnableControls(), AForge.PolishExpression.Evaluate(), Approximation.MainForm.functionsSet, Approximation.MainForm.geneticMethod, Approximation.MainForm.iterations, AForge.DoubleRange.Length, AForge.DoubleRange.Min, Approximation.MainForm.needToStop, Approximation.MainForm.populationSize, AForge.Controls.Chart.RangeX, AForge.Genetic.Population.RunEpoch(), Approximation.MainForm.selectionMethod, Approximation.MainForm.SetText(), Approximation.MainForm.solutionBox, and AForge.Controls.Chart.UpdateDataSeries().
Dispose() [5/5]
override void Approximation.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References Approximation.MainForm.components.
InitializeComponent() [5/5]
void Approximation.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [4/4]
static void Approximation.MainForm.Main () inline static private
The main entry point for the application.
References Approximation.MainForm.MainForm().
SetTextCallback() [3/3]
delegate void Approximation.MainForm.SetTextCallback (System.Windows.Forms.Control control, string text) private
SetText() [3/3]
void Approximation.MainForm.SetText (System.Windows.Forms.Control control, string text) inline private
References Approximation.MainForm.SetText(), and Approximation.MainForm.SetTextCallback().
MainForm_Closing() [5/5]
void Approximation.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References Approximation.MainForm.needToStop, and Approximation.MainForm.workerThread.
UpdateSettings() [5/5]
void Approximation.MainForm.UpdateSettings () inline private
References Approximation.MainForm.alphaBox, Approximation.MainForm.iterations, Approximation.MainForm.iterationsBox, Approximation.MainForm.learningRate, Approximation.MainForm.learningRateBox, Approximation.MainForm.momentum, Approximation.MainForm.momentumBox, Approximation.MainForm.neuronsBox, Approximation.MainForm.neuronsInFirstLayer, and Approximation.MainForm.sigmoidAlphaValue.
loadDataButton_Click() [4/4]
void Approximation.MainForm.loadDataButton_Click (object sender, System.EventArgs e) inline private
References Approximation.MainForm.chart, Approximation.MainForm.data, Approximation.MainForm.openFileDialog, AForge.Controls.Chart.RangeX, Approximation.MainForm.startButton, Approximation.MainForm.UpdateDataListView(), and AForge.Controls.Chart.UpdateDataSeries().
UpdateDataListView() [5/5]
void Approximation.MainForm.UpdateDataListView () inline private
References Approximation.MainForm.data, and Approximation.MainForm.dataList.
EnableCallback() [3/3]
delegate void Approximation.MainForm.EnableCallback (bool enable) private
EnableControls() [5/5]
void Approximation.MainForm.EnableControls (bool enable) inline private
References Approximation.MainForm.alphaBox, Approximation.MainForm.EnableCallback(), Approximation.MainForm.EnableControls(), Approximation.MainForm.iterationsBox, Approximation.MainForm.learningRateBox, Approximation.MainForm.loadDataButton, Approximation.MainForm.momentumBox, Approximation.MainForm.neuronsBox, Approximation.MainForm.startButton, and Approximation.MainForm.stopButton.
startButton_Click() [5/5]
void Approximation.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References Approximation.MainForm.alphaBox, Approximation.MainForm.EnableControls(), Approximation.MainForm.iterations, Approximation.MainForm.iterationsBox, Approximation.MainForm.learningRate, Approximation.MainForm.learningRateBox, Approximation.MainForm.momentum, Approximation.MainForm.momentumBox, Approximation.MainForm.needToStop, Approximation.MainForm.neuronsBox, Approximation.MainForm.neuronsInFirstLayer, Approximation.MainForm.SearchSolution(), Approximation.MainForm.sigmoidAlphaValue, Approximation.MainForm.UpdateSettings(), and Approximation.MainForm.workerThread.
stopButton_Click() [5/5]
void Approximation.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References Approximation.MainForm.needToStop, and Approximation.MainForm.workerThread.
SearchSolution() [5/5]
void Approximation.MainForm.SearchSolution () inline private
References Approximation.MainForm.chart, AForge.Neuro.Network.Compute(), Approximation.MainForm.currentErrorBox, Approximation.MainForm.currentIterationBox, Approximation.MainForm.data, Approximation.MainForm.EnableControls(), Approximation.MainForm.iterations, AForge.Neuro.Learning.BackPropagationLearning.LearningRate, Approximation.MainForm.learningRate, AForge.DoubleRange.Length, AForge.DoubleRange.Min, AForge.Neuro.Learning.BackPropagationLearning.Momentum, Approximation.MainForm.momentum, Approximation.MainForm.needToStop, Approximation.MainForm.neuronsInFirstLayer, AForge.Controls.Chart.RangeX, AForge.Controls.Chart.RangeY, AForge.Neuro.Learning.BackPropagationLearning.RunEpoch(), Approximation.MainForm.samples, Approximation.MainForm.SetText(), Approximation.MainForm.sigmoidAlphaValue, and AForge.Controls.Chart.UpdateDataSeries().
Member Data Documentation
groupBox1
System Windows Forms GroupBox Approximation.MainForm.groupBox1 private
loadButton
System.Windows.Forms.Button Approximation.MainForm.loadButton private
Referenced by Approximation.MainForm.EnableControls().
openFileDialog
System Windows Forms OpenFileDialog Approximation.MainForm.openFileDialog private
Referenced by Approximation.MainForm.btLoad_Click_1(), Approximation.MainForm.loadButton_Click(), and Approximation.MainForm.loadDataButton_Click().
dataList
System Windows Forms ListView Approximation.MainForm.dataList private
Referenced by Approximation.MainForm.UpdateDataListView().
groupBox2
System Windows Forms GroupBox Approximation.MainForm.groupBox2 private
learningRateBox
System Windows Forms TextBox Approximation.MainForm.learningRateBox private
Referenced by Approximation.MainForm.btStart_Click(), Approximation.MainForm.EnableControls(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
label1
System Windows Forms Label Approximation.MainForm.label1 private
label2
System Windows Forms Label Approximation.MainForm.label2 private
alphaBox
System Windows Forms TextBox Approximation.MainForm.alphaBox private
Referenced by Approximation.MainForm.btStart_Click(), Approximation.MainForm.EnableControls(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
label3
System Windows Forms Label Approximation.MainForm.label3 private
errorLimitBox
System.Windows.Forms.TextBox Approximation.MainForm.errorLimitBox private
Referenced by Approximation.MainForm.btStart_Click(), Approximation.MainForm.EnableControls(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
label4
System Windows Forms Label Approximation.MainForm.label4 private
iterationsBox
System Windows Forms TextBox Approximation.MainForm.iterationsBox private
Referenced by Approximation.MainForm.btStart_Click(), Approximation.MainForm.EnableControls(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
label5
System Windows Forms Label Approximation.MainForm.label5 private
label6
System Windows Forms Label Approximation.MainForm.label6 private
neuronsBox
System Windows Forms TextBox Approximation.MainForm.neuronsBox private
Referenced by Approximation.MainForm.btLoad_Click_1(), Approximation.MainForm.EnableControls(), Approximation.MainForm.loadButton_Click(), Approximation.MainForm.oneNeuronForTwoCheck_CheckedChanged(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
oneNeuronForTwoCheck
System.Windows.Forms.CheckBox Approximation.MainForm.oneNeuronForTwoCheck private
Referenced by Approximation.MainForm.btLoad_Click_1(), Approximation.MainForm.btStart_Click(), Approximation.MainForm.EnableControls(), Approximation.MainForm.loadButton_Click(), Approximation.MainForm.oneNeuronForTwoCheck_CheckedChanged(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
label7
System Windows Forms Label Approximation.MainForm.label7 private
label8
System Windows Forms Label Approximation.MainForm.label8 private
currentIterationBox
System Windows Forms TextBox Approximation.MainForm.currentIterationBox private
Referenced by Approximation.MainForm.ClearSolution(), and Approximation.MainForm.SearchSolution().
stopButton
System Windows Forms Button Approximation.MainForm.stopButton private
Referenced by Approximation.MainForm.EnableControls().
startButton
System Windows Forms Button Approximation.MainForm.startButton private
Referenced by Approximation.MainForm.btLoad_Click_1(), Approximation.MainForm.EnableControls(), Approximation.MainForm.loadButton_Click(), and Approximation.MainForm.loadDataButton_Click().
label9
System Windows Forms Label Approximation.MainForm.label9 private
label10
System Windows Forms Label Approximation.MainForm.label10 private
classesBox
System.Windows.Forms.TextBox Approximation.MainForm.classesBox private
Referenced by Approximation.MainForm.loadButton_Click().
errorLimitCheck
System.Windows.Forms.CheckBox Approximation.MainForm.errorLimitCheck private
Referenced by Approximation.MainForm.btStart_Click(), Approximation.MainForm.EnableControls(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
label11
System.Windows.Forms.Label Approximation.MainForm.label11 private
currentErrorBox
System Windows Forms TextBox Approximation.MainForm.currentErrorBox private
Referenced by Approximation.MainForm.ClearSolution(), and Approximation.MainForm.SearchSolution().
groupBox3
System Windows Forms GroupBox Approximation.MainForm.groupBox3 private
label12
System.Windows.Forms.Label Approximation.MainForm.label12 private
weightsList
System.Windows.Forms.ListView Approximation.MainForm.weightsList private
Referenced by Approximation.MainForm.ClearSolution(), and Approximation.MainForm.SearchSolution().
label13
System.Windows.Forms.Label Approximation.MainForm.label13 private
columnHeader1
System.Windows.Forms.ColumnHeader Approximation.MainForm.columnHeader1 private
columnHeader2
System.Windows.Forms.ColumnHeader Approximation.MainForm.columnHeader2 private
columnHeader3
System.Windows.Forms.ColumnHeader Approximation.MainForm.columnHeader3 private
saveFilesCheck
System.Windows.Forms.CheckBox Approximation.MainForm.saveFilesCheck private
Referenced by Approximation.MainForm.btStart_Click(), Approximation.MainForm.EnableControls(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
errorChart
AForge.Controls.Chart Approximation.MainForm.errorChart private
Referenced by Approximation.MainForm.ClearSolution(), Approximation.MainForm.MainForm(), and Approximation.MainForm.SearchSolution().
components
System ComponentModel Container Approximation.MainForm.components = null private
Required designer variable.
Referenced by Approximation.MainForm.Dispose().
samples
int Approximation.MainForm.samples = 0 private
Referenced by Approximation.MainForm.btLoad_Click_1(), Approximation.MainForm.loadButton_Click(), Approximation.MainForm.SearchSolution(), Approximation.MainForm.UpdateDataListView(), and Approximation.MainForm.UpdateDataListViewTKTest().
variables
int Approximation.MainForm.variables = 0 private
Referenced by Approximation.MainForm.btLoad_Click_1(), Approximation.MainForm.loadButton_Click(), Approximation.MainForm.SearchSolution(), Approximation.MainForm.UpdateDataListView(), and Approximation.MainForm.UpdateDataListViewTKTest().
data
double [,] Approximation.MainForm.data = null private
Referenced by Approximation.MainForm.btLoad_Click_1(), Approximation.MainForm.loadButton_Click(), Approximation.MainForm.loadDataButton_Click(), Approximation.MainForm.SearchSolution(), Approximation.MainForm.UpdateDataListView(), and Approximation.MainForm.UpdateDataListViewTKTest().
classes
int [] Approximation.MainForm.classes = null private
Referenced by Approximation.MainForm.btLoad_Click_1(), Approximation.MainForm.loadButton_Click(), Approximation.MainForm.SearchSolution(), Approximation.MainForm.UpdateDataListView(), and Approximation.MainForm.UpdateDataListViewTKTest().
classesCount
int Approximation.MainForm.classesCount = 0 private
Referenced by Approximation.MainForm.btLoad_Click_1(), Approximation.MainForm.EnableControls(), Approximation.MainForm.loadButton_Click(), Approximation.MainForm.oneNeuronForTwoCheck_CheckedChanged(), and Approximation.MainForm.SearchSolution().
samplesPerClass
int [] Approximation.MainForm.samplesPerClass = null private
Referenced by Approximation.MainForm.btLoad_Click_1(), and Approximation.MainForm.loadButton_Click().
neuronsCount
int Approximation.MainForm.neuronsCount = 0 private
Referenced by Approximation.MainForm.btLoad_Click_1(), Approximation.MainForm.loadButton_Click(), Approximation.MainForm.oneNeuronForTwoCheck_CheckedChanged(), and Approximation.MainForm.SearchSolution().
learningRate
double Approximation.MainForm.learningRate = 0.1 private
Referenced by Approximation.MainForm.btStart_Click(), Approximation.MainForm.SearchSolution(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
sigmoidAlphaValue
double Approximation.MainForm.sigmoidAlphaValue = 2.0 private
Referenced by Approximation.MainForm.btStart_Click(), Approximation.MainForm.SearchSolution(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
learningErrorLimit
double Approximation.MainForm.learningErrorLimit = 0.1 private
Referenced by Approximation.MainForm.btStart_Click(), Approximation.MainForm.SearchSolution(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
iterationLimit
double Approximation.MainForm.iterationLimit = 1000 private
Referenced by Approximation.MainForm.btStart_Click(), Approximation.MainForm.SearchSolution(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
useOneNeuronForTwoClasses
bool Approximation.MainForm.useOneNeuronForTwoClasses = false private
Referenced by Approximation.MainForm.btLoad_Click_1(), Approximation.MainForm.btStart_Click(), Approximation.MainForm.loadButton_Click(), Approximation.MainForm.oneNeuronForTwoCheck_CheckedChanged(), Approximation.MainForm.SearchSolution(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
useErrorLimit
bool Approximation.MainForm.useErrorLimit = true private
Referenced by Approximation.MainForm.btStart_Click(), Approximation.MainForm.SearchSolution(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
saveStatisticsToFiles
bool Approximation.MainForm.saveStatisticsToFiles = false private
Referenced by Approximation.MainForm.btStart_Click(), Approximation.MainForm.SearchSolution(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
workerThread
Thread Approximation.MainForm.workerThread = null private
Referenced by Approximation.MainForm.btStart_Click(), Approximation.MainForm.MainForm_Closing(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.stopButton_Click().
lvPodatki
ListView Approximation.MainForm.lvPodatki private
Referenced by Approximation.MainForm.UpdateDataListViewTKTest().
btLoad
Button Approximation.MainForm.btLoad private
label14
Label Approximation.MainForm.label14 private
tbClasses
TextBox Approximation.MainForm.tbClasses private
Referenced by Approximation.MainForm.btLoad_Click_1().
btStart
Button Approximation.MainForm.btStart private
needToStop [1/2]
volatile bool Approximation.MainForm.needToStop = false private
Referenced by Approximation.MainForm.btStart_Click(), Approximation.MainForm.MainForm_Closing(), Approximation.MainForm.SearchSolution(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.stopButton_Click().
_filePath
string Approximation.MainForm._filePath = "../../data/aforge/" private
Referenced by Approximation.MainForm.ChooseFile().
_fileChosen
bool Approximation.MainForm._fileChosen = false private
Referenced by Approximation.MainForm.ChooseFile().
loadDataButton
System Windows Forms Button Approximation.MainForm.loadDataButton private
Referenced by Approximation.MainForm.EnableControls().
xColumnHeader
System Windows Forms ColumnHeader Approximation.MainForm.xColumnHeader private
yColumnHeader
System Windows Forms ColumnHeader Approximation.MainForm.yColumnHeader private
chart
AForge Controls Chart Approximation.MainForm.chart private
Referenced by Approximation.MainForm.loadDataButton_Click(), Approximation.MainForm.MainForm(), and Approximation.MainForm.SearchSolution().
momentumBox
System Windows Forms TextBox Approximation.MainForm.momentumBox private
Referenced by Approximation.MainForm.EnableControls(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
groupBox4
System Windows Forms GroupBox Approximation.MainForm.groupBox4 private
momentum
double Approximation.MainForm.momentum = 0.0 private
Referenced by Approximation.MainForm.SearchSolution(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
neuronsInFirstLayer
int Approximation.MainForm.neuronsInFirstLayer = 20 private
Referenced by Approximation.MainForm.SearchSolution(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
iterations
int Approximation.MainForm.iterations = 1000 private
Referenced by Approximation.MainForm.SearchSolution(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
populationSizeBox
System.Windows.Forms.TextBox Approximation.MainForm.populationSizeBox private
Referenced by Approximation.MainForm.EnableControls(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
selectionBox
System.Windows.Forms.ComboBox Approximation.MainForm.selectionBox private
Referenced by Approximation.MainForm.EnableControls(), Approximation.MainForm.MainForm(), and Approximation.MainForm.startButton_Click().
functionsSetBox
System.Windows.Forms.ComboBox Approximation.MainForm.functionsSetBox private
Referenced by Approximation.MainForm.EnableControls(), Approximation.MainForm.MainForm(), and Approximation.MainForm.startButton_Click().
geneticMethodBox
System.Windows.Forms.ComboBox Approximation.MainForm.geneticMethodBox private
Referenced by Approximation.MainForm.EnableControls(), Approximation.MainForm.MainForm(), and Approximation.MainForm.startButton_Click().
groupBox5
System.Windows.Forms.GroupBox Approximation.MainForm.groupBox5 private
solutionBox
System.Windows.Forms.TextBox Approximation.MainForm.solutionBox private
Referenced by Approximation.MainForm.SearchSolution(), and Approximation.MainForm.startButton_Click().
populationSize
int Approximation.MainForm.populationSize = 100 private
Referenced by Approximation.MainForm.SearchSolution(), Approximation.MainForm.startButton_Click(), and Approximation.MainForm.UpdateSettings().
selectionMethod
int Approximation.MainForm.selectionMethod = 0 private
Referenced by Approximation.MainForm.MainForm(), Approximation.MainForm.SearchSolution(), and Approximation.MainForm.startButton_Click().
functionsSet
int Approximation.MainForm.functionsSet = 0 private
Referenced by Approximation.MainForm.MainForm(), Approximation.MainForm.SearchSolution(), and Approximation.MainForm.startButton_Click().
geneticMethod
int Approximation.MainForm.geneticMethod = 0 private
Referenced by Approximation.MainForm.MainForm(), Approximation.MainForm.SearchSolution(), and Approximation.MainForm.startButton_Click().
needToStop [2/2]
volatile bool Approximation.MainForm.needToStop = false private
The documentation for this class was generated from the following files:
shelldev/extensions_shell/shell/Test_Tadej/Neuro/Approximation/MainFormNeuralApproximation.cs
shelldev/lib/external/neuralnetworks/neuro_src/Samples/Neuro/Back Propagation/Approximation/Backup/MainForm.cs