Doc: IGLib EXTENDED: AForge.Robotics.TeRK.Qwerk.Motors Class Reference
AForge.Robotics.TeRK.Qwerk.Motors Class Reference
Provides access to Qwerk's motors' controllers.
Public Member Functions
Motors (Qwerk qwerk)
Initializes a new instance of the Qwerk.Motors class.
void StopMotor (int motor)
Stop specified motor.
void StopMotors ()
Stop all motors.
void SetMotorVelocity (int motor, int velocity)
Set velocity of specified motor.
Static Public Attributes
const int Count = 4
Number of available motors' controllers, 4.
Private Member Functions
TeRKIceLib.MotorCommand CreateCommand ()
void ExecuteCommand (TeRKIceLib.MotorCommand command)
Private Attributes
TeRKIceLib.MotorControllerPrx motorController = null
Static Private Attributes
const int DefaultAcceleration = 16000
Detailed Description
Provides access to Qwerk's motors' controllers.
The class allows to manipulate Qwerk's motors. The total number of available motors equals to Motors.Count.
Sample usage:
// get Qwerk's motors service
Qwerk.Motors motors = qwerk.GetMotorsService();
// stop all motors
motors.StopMotors();
// run first motor
motors.SetMotorVelocity(0, 10000);
Constructor & Destructor Documentation
Motors()
AForge.Robotics.TeRK.Qwerk.Motors.Motors (Qwerk qwerk) inline
Initializes a new instance of the Qwerk.Motors class.
Parameters
qwerk Reference to Qwerk object, which is connected to Qwerk board.
Exceptions
NotConnectedException The passed reference to Qwerk object is not connected to Qwerk board.
ConnectionFailedException Failed connecting to the requested service.
ServiceAccessFailedException Failed accessing to the requested service.
References AForge.Robotics.TeRK.Qwerk.hostAddress, AForge.Robotics.TeRK.Qwerk.Motors.motorController, and AForge.Robotics.TeRK.Qwerk.qwerk.
Member Function Documentation
StopMotor()
void AForge.Robotics.TeRK.Qwerk.Motors.StopMotor (int motor) inline
Stop specified motor.
Parameters
motor Motor to stop, [0, Motors.Count).
Exceptions
ArgumentOutOfRangeException Invalid motor is specified.
NotConnectedException No connection to Qwerk or its service.
ConnectionLostException Connestion to Qwerk is lost.
References AForge.Robotics.TeRK.Qwerk.Motors.Count, AForge.Robotics.TeRK.Qwerk.Motors.CreateCommand(), and AForge.Robotics.TeRK.Qwerk.Motors.ExecuteCommand().
StopMotors()
void AForge.Robotics.TeRK.Qwerk.Motors.StopMotors () inline
Stop all motors.
Exceptions
NotConnectedException No connection to Qwerk or its service.
ConnectionLostException Connestion to Qwerk is lost.
References AForge.Robotics.TeRK.Qwerk.Motors.Count, AForge.Robotics.TeRK.Qwerk.Motors.CreateCommand(), and AForge.Robotics.TeRK.Qwerk.Motors.ExecuteCommand().
SetMotorVelocity()
void AForge.Robotics.TeRK.Qwerk.Motors.SetMotorVelocity (int motor, int velocity) inline
Set velocity of specified motor.
Parameters
motor Motor to set velocity for, [0, Motors.Count).
velocity Velocity to set.
The method sets specified motor's velocity, which is measured in ticks per second. "Ticks" is a made-up term, which does not depend on specific motor, but is an unknown in distance and rotation (see Qwerk documentation for details).
Exceptions
ArgumentOutOfRangeException Invalid motor is specified.
NotConnectedException No connection to Qwerk or its service.
ConnectionLostException Connestion to Qwerk is lost.
References AForge.Robotics.TeRK.Qwerk.Motors.Count, AForge.Robotics.TeRK.Qwerk.Motors.CreateCommand(), AForge.Robotics.TeRK.Qwerk.Motors.DefaultAcceleration, and AForge.Robotics.TeRK.Qwerk.Motors.ExecuteCommand().
CreateCommand()
TeRKIceLib.MotorCommand AForge.Robotics.TeRK.Qwerk.Motors.CreateCommand () inline private
References AForge.Robotics.TeRK.Qwerk.Motors.Count.
Referenced by AForge.Robotics.TeRK.Qwerk.Motors.SetMotorVelocity(), AForge.Robotics.TeRK.Qwerk.Motors.StopMotor(), and AForge.Robotics.TeRK.Qwerk.Motors.StopMotors().
ExecuteCommand()
void AForge.Robotics.TeRK.Qwerk.Motors.ExecuteCommand (TeRKIceLib.MotorCommand command) inline private
References AForge.Robotics.TeRK.Qwerk.Motors.motorController.
Referenced by AForge.Robotics.TeRK.Qwerk.Motors.SetMotorVelocity(), AForge.Robotics.TeRK.Qwerk.Motors.StopMotor(), and AForge.Robotics.TeRK.Qwerk.Motors.StopMotors().
Member Data Documentation
motorController
TeRKIceLib.MotorControllerPrx AForge.Robotics.TeRK.Qwerk.Motors.motorController = null private
Referenced by AForge.Robotics.TeRK.Qwerk.Motors.ExecuteCommand(), and AForge.Robotics.TeRK.Qwerk.Motors.Motors().
Count
const int AForge.Robotics.TeRK.Qwerk.Motors.Count = 4 static
Number of available motors' controllers, 4.
Referenced by AForge.Robotics.TeRK.Qwerk.Motors.CreateCommand(), AForge.Robotics.TeRK.Qwerk.Motors.SetMotorVelocity(), AForge.Robotics.TeRK.Qwerk.Motors.StopMotor(), and AForge.Robotics.TeRK.Qwerk.Motors.StopMotors().
DefaultAcceleration
const int AForge.Robotics.TeRK.Qwerk.Motors.DefaultAcceleration = 16000 static private
Referenced by AForge.Robotics.TeRK.Qwerk.Motors.SetMotorVelocity().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Robotics.TeRK/Qwerk.Motors.cs