Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLASDT Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLASDT Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLASDT ()
void Run (int N, ref int LVL, ref int ND, ref int[] INODE, int offset_inode, ref int[] NDIML, int offset_ndiml, ref int[] NDIMR, int offset_ndimr, int MSUB)
Static Private Attributes
const double TWO = 2.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLASDT creates a tree of subproblems for bidiagonal divide and conquer.
/summary>
Constructor & Destructor Documentation
DLASDT()
DotNumerics.LinearAlgebra.CSLapack.DLASDT.DLASDT () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLASDT.Run (int N, ref int LVL, ref int ND, ref int[] INODE, int offset_inode, ref int[] NDIML, int offset_ndiml, ref int[] NDIMR, int offset_ndimr, int MSUB) inline
Purpose
DLASDT creates a tree of subproblems for bidiagonal divide and conquer.
/summary>
Parameters
N (input) INTEGER On entry, the number of diagonal elements of the bidiagonal matrix. /param>
Parameters
LVL (output) INTEGER On exit, the number of levels on the computation tree. /param>
Parameters
ND (output) INTEGER On exit, the number of nodes on the tree. /param>
Parameters
INODE (output) INTEGER array, dimension (N) On exit, centers of subproblems. /param>
Parameters
NDIML (output) INTEGER array, dimension (N) On exit, row dimensions of left children. /param>
Parameters
NDIMR (output) INTEGER array, dimension (N) On exit, row dimensions of right children. /param>
Parameters
MSUB (input) INTEGER. On entry, the maximum row dimension each subproblem at the bottom of the tree can be of. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLASDT.TWO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD0.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALSA.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLASDA.Run().
Member Data Documentation
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DLASDT.TWO = 2.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASDT.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlasdt.cs