Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DTRTRI Class Reference
DotNumerics.LinearAlgebra.CSLapack.DTRTRI Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DTRTRI (LSAME lsame, ILAENV ilaenv, DTRMM dtrmm, DTRSM dtrsm, DTRTI2 dtrti2, XERBLA xerbla)
DTRTRI ()
void Run (string UPLO, string DIAG, int N, ref double[] A, int offset_a, int LDA, ref int INFO)
Private Attributes
LSAME _lsame
ILAENV _ilaenv
DTRMM _dtrmm
DTRSM _dtrsm
DTRTI2 _dtrti2
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DTRTRI computes the inverse of a real upper or lower triangular matrix A.
This is the Level 3 BLAS version of the algorithm.
/summary>
Constructor & Destructor Documentation
DTRTRI() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DTRTRI.DTRTRI (LSAME lsame, ILAENV ilaenv, DTRMM dtrmm, DTRSM dtrsm, DTRTI2 dtrti2, XERBLA xerbla) inline
DTRTRI() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DTRTRI.DTRTRI () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DTRTRI.Run (string UPLO, string DIAG, int N, ref double[] A, int offset_a, int LDA, ref int INFO) inline
Purpose
DTRTRI computes the inverse of a real upper or lower triangular matrix A.
This is the Level 3 BLAS version of the algorithm.
/summary>
Parameters
UPLO (input) CHARACTER*1 = 'U': A is upper triangular; = 'L': A is lower triangular. /param>
Parameters
DIAG (input) CHARACTER*1 = 'N': A is non-unit triangular; = 'U': A is unit triangular. /param>
Parameters
N (input) INTEGER The order of the matrix A. N .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the triangular matrix A. If UPLO = 'U', the leading N-by-N upper triangular part of the array A contains the upper triangular matrix, and the strictly lower triangular part of A is not referenced. If UPLO = 'L', the leading N-by-N lower triangular part of the array A contains the lower triangular matrix, and the strictly upper triangular part of A is not referenced. If DIAG = 'U', the diagonal elements of A are also not referenced and are assumed to be 1. On exit, the (triangular) inverse of the original matrix, in the same storage format. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,N). /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value .GT. 0: if INFO = i, A(i,i) is exactly zero. The triangular matrix is singular and its inverse can not be computed. /param>
References DotNumerics.LinearAlgebra.CSLapack.DTRTRI.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRTI2.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRSM.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRMM.Run(), and DotNumerics.LinearAlgebra.CSLapack.DTRTRI.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGETRI.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DTRTRI._lsame private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DTRTRI._ilaenv private
_dtrmm
DTRMM DotNumerics.LinearAlgebra.CSLapack.DTRTRI._dtrmm private
_dtrsm
DTRSM DotNumerics.LinearAlgebra.CSLapack.DTRTRI._dtrsm private
_dtrti2
DTRTI2 DotNumerics.LinearAlgebra.CSLapack.DTRTRI._dtrti2 private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DTRTRI._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DTRTRI.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTRTRI.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DTRTRI.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTRTRI.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dtrtri.cs