Doc: IGLib EXTENDED: IJS.Example.ExampleIJS Class Reference
IJS.Example.ExampleIJS Class Reference
Examples of how to operate with files contained in data exchange directory for neural network based approximation.
Static Public Member Functions
static void WriteNeuralInputParameters (string directoryPath, double[] inputParameters)
This is how to write neural network input parameters.
static void ReadNeuralOutput (string directoryPath, out double[] outputValues)
This is how to read output values approximated by neural network.
static void ExtractData (string directoryPath)
This example demonstrates how to extract data necessary for definition of optimization problems.
Detailed Description
Examples of how to operate with files contained in data exchange directory for neural network based approximation.
$A Igor Jun11;
Member Function Documentation
WriteNeuralInputParameters()
static void IJS.Example.ExampleIJS.WriteNeuralInputParameters (string directoryPath, double[] inputParameters) inline static
This is how to write neural network input parameters.
Parameters
directoryPath Path to the directory containing data exchange and other files for neural network approximation.
inputParameters Table containing input parameters.
References IG.Neural.NeuraApproximationFileManager.WriteNeuralInput().
ReadNeuralOutput()
static void IJS.Example.ExampleIJS.ReadNeuralOutput (string directoryPath, out double[] outputValues) inline static
This is how to read output values approximated by neural network.
Parameters
directoryPath Path to the directory containing data exchange and other files for neural network approximation.
outputValues Table where output values are returned.
References IG.Neural.NeuraApproximationFileManager.ReadNeuralOutput().
ExtractData()
static void IJS.Example.ExampleIJS.ExtractData (string directoryPath) inline static
This example demonstrates how to extract data necessary for definition of optimization problems.
Parameters
directoryPath Path to the directory containing data exchange and other files for neural network approximation.
$A Igor Jun11;
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Num.InputOutputElementDefinition.Description, IG.Num.InputOutputDataDefiniton.LoadJson(), IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, IG.Neural.NeuraApproximationFileManager.NeuralDataDefinitionPath, and IG.Num.InputOutputElementDefinition.TargetValue.
The documentation for this class was generated from the following file:
shelldev/extensions_shell/shell/ShellAppMess/applications/ExampleIJS.cs