Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGELSD Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGELSD Class Reference
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGELSD (DGEBRD dgebrd, DGELQF dgelqf, DGEQRF dgeqrf, DLABAD dlabad, DLACPY dlacpy, DLALSD dlalsd, DLASCL dlascl, DLASET dlaset, DORMBR dormbr, DORMLQ dormlq, DORMQR dormqr, XERBLA xerbla, ILAENV ilaenv, DLAMCH dlamch, DLANGE dlange)
DGELSD ()
void Run (int M, int N, int NRHS, ref double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB, ref double[] S, int offset_s, double RCOND, ref int RANK, ref double[] WORK, int offset_work, int LWORK, ref int[] IWORK, int offset_iwork, ref int INFO)
Private Attributes
DGEBRD _dgebrd
DGELQF _dgelqf
DGEQRF _dgeqrf
DLABAD _dlabad
DLACPY _dlacpy
DLALSD _dlalsd
DLASCL _dlascl
DLASET _dlaset
DORMBR _dormbr
DORMLQ _dormlq
DORMQR _dormqr
XERBLA _xerbla
ILAENV _ilaenv
DLAMCH _dlamch
DLANGE _dlange
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
const double TWO = 2.0E0
Detailed Description
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGELSD computes the minimum-norm solution to a real linear least squares problem: minimize 2-norm(| b - A*x |) using the singular value decomposition (SVD) of A. A is an M-by-N matrix which may be rank-deficient.
Several right hand side vectors b and solution vectors x can be handled in a single call; they are stored as the columns of the M-by-NRHS right hand side matrix B and the N-by-NRHS solution matrix X.
The problem is solved in three steps: (1) Reduce the coefficient matrix A to bidiagonal form with Householder transformations, reducing the original problem into a "bidiagonal least squares problem" (BLS) (2) Solve the BLS using a divide and conquer approach. (3) Apply back all the Householder tranformations to solve the original least squares problem.
The effective rank of A is determined by treating as zero those singular values which are less than RCOND times the largest singular value.
The divide and conquer algorithm makes very mild assumptions about floating point arithmetic. It will work on machines with a guard digit in add/subtract, or on those binary machines without guard digits which subtract like the Cray X-MP, Cray Y-MP, Cray C-90, or Cray-2. It could conceivably fail on hexadecimal or decimal machines without guard digits, but we know of none.
/summary>
Constructor & Destructor Documentation
DGELSD() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGELSD.DGELSD (DGEBRD dgebrd, DGELQF dgelqf, DGEQRF dgeqrf, DLABAD dlabad, DLACPY dlacpy, DLALSD dlalsd, DLASCL dlascl, DLASET dlaset, DORMBR dormbr, DORMLQ dormlq, DORMQR dormqr, XERBLA xerbla, ILAENV ilaenv, DLAMCH dlamch, DLANGE dlange) inline
DGELSD() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGELSD.DGELSD () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGELSD.Run (int M, int N, int NRHS, ref double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB, ref double[] S, int offset_s, double RCOND, ref int RANK, ref double[] WORK, int offset_work, int LWORK, ref int[] IWORK, int offset_iwork, ref int INFO) inline
Purpose
DGELSD computes the minimum-norm solution to a real linear least squares problem: minimize 2-norm(| b - A*x |) using the singular value decomposition (SVD) of A. A is an M-by-N matrix which may be rank-deficient.
Several right hand side vectors b and solution vectors x can be handled in a single call; they are stored as the columns of the M-by-NRHS right hand side matrix B and the N-by-NRHS solution matrix X.
The problem is solved in three steps: (1) Reduce the coefficient matrix A to bidiagonal form with Householder transformations, reducing the original problem into a "bidiagonal least squares problem" (BLS) (2) Solve the BLS using a divide and conquer approach. (3) Apply back all the Householder tranformations to solve the original least squares problem.
The effective rank of A is determined by treating as zero those singular values which are less than RCOND times the largest singular value.
The divide and conquer algorithm makes very mild assumptions about floating point arithmetic. It will work on machines with a guard digit in add/subtract, or on those binary machines without guard digits which subtract like the Cray X-MP, Cray Y-MP, Cray C-90, or Cray-2. It could conceivably fail on hexadecimal or decimal machines without guard digits, but we know of none.
/summary>
Parameters
M (input) INTEGER The number of rows of A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of A. N .GE. 0. /param>
Parameters
NRHS (input) INTEGER The number of right hand sides, i.e., the number of columns of the matrices B and X. NRHS .GE. 0. /param>
Parameters
A (input) DOUBLE PRECISION array, dimension (LDA,N) On entry, the M-by-N matrix A. On exit, A has been destroyed. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
B (input/output) DOUBLE PRECISION array, dimension (LDB,NRHS) On entry, the M-by-NRHS right hand side matrix B. On exit, B is overwritten by the N-by-NRHS solution matrix X. If m .GE. n and RANK = n, the residual sum-of-squares for the solution in the i-th column is given by the sum of squares of elements n+1:m in that column. /param>
Parameters
LDB (input) INTEGER The leading dimension of the array B. LDB .GE. max(1,max(M,N)). /param>
Parameters
S (output) DOUBLE PRECISION array, dimension (min(M,N)) The singular values of A in decreasing order. The condition number of A in the 2-norm = S(1)/S(min(m,n)). /param>
Parameters
RCOND (input) DOUBLE PRECISION RCOND is used to determine the effective rank of A. Singular values S(i) .LE. RCOND*S(1) are treated as zero. If RCOND .LT. 0, machine precision is used instead. /param>
Parameters
RANK (output) INTEGER The effective rank of A, i.e., the number of singular values which are greater than RCOND*S(1). /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK must be at least 1. The exact minimum amount of workspace needed depends on M, N and NRHS. As long as LWORK is at least 12*N + 2*N*SMLSIZ + 8*N*NLVL + N*NRHS + (SMLSIZ+1)**2, if M is greater than or equal to N or 12*M + 2*M*SMLSIZ + 8*M*NLVL + M*NRHS + (SMLSIZ+1)**2, if M is less than N, the code will execute correctly. SMLSIZ is returned by ILAENV and is equal to the maximum size of the subproblems at the bottom of the computation tree (usually about 25), and NLVL = MAX(0, INT(LOG_2(MIN(M,N)/(SMLSIZ+1))) + 1) For good performance, LWORK should generally be larger.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
IWORK (workspace) INTEGER array, dimension (MAX(1,LIWORK)) LIWORK .GE. 3 * MINMN * NLVL + 11 * MINMN, where MINMN = MIN(M,N). /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value. .GT. 0: the algorithm for computing the SVD failed to converge; if INFO = i, i off-diagonal elements of an intermediate bidiagonal form did not converge to zero. /param>
References DotNumerics.LinearAlgebra.CSLapack.DGELSD.ONE, DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLABAD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASET.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELQF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANGE.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMLQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMBR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALSD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELSD.TWO, and DotNumerics.LinearAlgebra.CSLapack.DGELSD.ZERO.
Member Data Documentation
_dgebrd
DGEBRD DotNumerics.LinearAlgebra.CSLapack.DGELSD._dgebrd private
_dgelqf
DGELQF DotNumerics.LinearAlgebra.CSLapack.DGELSD._dgelqf private
_dgeqrf
DGEQRF DotNumerics.LinearAlgebra.CSLapack.DGELSD._dgeqrf private
_dlabad
DLABAD DotNumerics.LinearAlgebra.CSLapack.DGELSD._dlabad private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DGELSD._dlacpy private
_dlalsd
DLALSD DotNumerics.LinearAlgebra.CSLapack.DGELSD._dlalsd private
_dlascl
DLASCL DotNumerics.LinearAlgebra.CSLapack.DGELSD._dlascl private
_dlaset
DLASET DotNumerics.LinearAlgebra.CSLapack.DGELSD._dlaset private
_dormbr
DORMBR DotNumerics.LinearAlgebra.CSLapack.DGELSD._dormbr private
_dormlq
DORMLQ DotNumerics.LinearAlgebra.CSLapack.DGELSD._dormlq private
_dormqr
DORMQR DotNumerics.LinearAlgebra.CSLapack.DGELSD._dormqr private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGELSD._xerbla private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DGELSD._ilaenv private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DGELSD._dlamch private
_dlange
DLANGE DotNumerics.LinearAlgebra.CSLapack.DGELSD._dlange private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DGELSD.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGELSD.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGELSD.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGELSD.Run().
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DGELSD.TWO = 2.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGELSD.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgelsd.cs