Doc: IGLib EXTENDED: IG.Web.Forms.WSClientFormsAboutWindow Class Reference
IG.Web.Forms.WSClientFormsAboutWindow Class Reference
Window that displays information about Demo application for performing parametric studies on ANN models.
Public Member Functions
WSClientFormsAboutWindow ()
void ShowHelp ()
void ShowWebPage ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
WSClientFormsAboutForm wsClientFormsAbout1
Detailed Description
Window that displays information about Demo application for performing parametric studies on ANN models.
$A Igor Apr13;
Constructor & Destructor Documentation
WSClientFormsAboutWindow()
IG.Web.Forms.WSClientFormsAboutWindow.WSClientFormsAboutWindow () inline
References IG.Web.Forms.WSClientFormsAboutWindow.InitializeComponent().
Member Function Documentation
ShowHelp()
void IG.Web.Forms.WSClientFormsAboutWindow.ShowHelp () inline
References IG.Web.Forms.WSClientFormsAboutForm.ShowHelp(), and IG.Web.Forms.WSClientFormsAboutWindow.wsClientFormsAbout1.
Referenced by IG.Web.Forms.WSClientsForm.NeuralParametricDemo_HelpEventHandlers().
ShowWebPage()
void IG.Web.Forms.WSClientFormsAboutWindow.ShowWebPage () inline
References IG.Web.Forms.WSClientFormsAboutForm.ShowWebPage(), and IG.Web.Forms.WSClientFormsAboutWindow.wsClientFormsAbout1.
Dispose()
override void IG.Web.Forms.WSClientFormsAboutWindow.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Web.Forms.WSClientFormsAboutWindow.components.
InitializeComponent()
void IG.Web.Forms.WSClientFormsAboutWindow.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Web.Forms.WSClientFormsAboutWindow.wsClientFormsAbout1.
Referenced by IG.Web.Forms.WSClientFormsAboutWindow.WSClientFormsAboutWindow().
Member Data Documentation
components
System.ComponentModel.IContainer IG.Web.Forms.WSClientFormsAboutWindow.components = null private
Required designer variable.
Referenced by IG.Web.Forms.WSClientFormsAboutWindow.Dispose().
wsClientFormsAbout1
WSClientFormsAboutForm IG.Web.Forms.WSClientFormsAboutWindow.wsClientFormsAbout1 private
Referenced by IG.Web.Forms.WSClientFormsAboutWindow.InitializeComponent(), IG.Web.Forms.WSClientFormsAboutWindow.ShowHelp(), and IG.Web.Forms.WSClientFormsAboutWindow.ShowWebPage().
The documentation for this class was generated from the following files:
igtest/IGLibTestShell/WebServices/WebServiceForms/WSClientsFormAboutWindow.cs
igtest/IGLibTestShell/WebServices/WebServiceForms/WSClientsFormAboutWindow.Designer.cs