Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLATRD Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLATRD Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLATRD (DAXPY daxpy, DGEMV dgemv, DLARFG dlarfg, DSCAL dscal, DSYMV dsymv, LSAME lsame, DDOT ddot)
DLATRD ()
void Run (string UPLO, int N, int NB, ref double[] A, int offset_a, int LDA, ref double[] E, int offset_e, ref double[] TAU, int offset_tau, ref double[] W, int offset_w, int LDW)
Private Attributes
DAXPY _daxpy
DGEMV _dgemv
DLARFG _dlarfg
DSCAL _dscal
DSYMV _dsymv
LSAME _lsame
DDOT _ddot
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
const double HALF = 0.5E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLATRD reduces NB rows and columns of a real symmetric matrix A to symmetric tridiagonal form by an orthogonal similarity transformation Q' * A * Q, and returns the matrices V and W which are needed to apply the transformation to the unreduced part of A.
If UPLO = 'U', DLATRD reduces the last NB rows and columns of a matrix, of which the upper triangle is supplied; if UPLO = 'L', DLATRD reduces the first NB rows and columns of a matrix, of which the lower triangle is supplied.
This is an auxiliary routine called by DSYTRD.
/summary>
Constructor & Destructor Documentation
DLATRD() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLATRD.DLATRD (DAXPY daxpy, DGEMV dgemv, DLARFG dlarfg, DSCAL dscal, DSYMV dsymv, LSAME lsame, DDOT ddot) inline
DLATRD() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLATRD.DLATRD () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLATRD.Run (string UPLO, int N, int NB, ref double[] A, int offset_a, int LDA, ref double[] E, int offset_e, ref double[] TAU, int offset_tau, ref double[] W, int offset_w, int LDW) inline
Purpose
DLATRD reduces NB rows and columns of a real symmetric matrix A to symmetric tridiagonal form by an orthogonal similarity transformation Q' * A * Q, and returns the matrices V and W which are needed to apply the transformation to the unreduced part of A.
If UPLO = 'U', DLATRD reduces the last NB rows and columns of a matrix, of which the upper triangle is supplied; if UPLO = 'L', DLATRD reduces the first NB rows and columns of a matrix, of which the lower triangle is supplied.
This is an auxiliary routine called by DSYTRD.
/summary>
Parameters
UPLO (input) CHARACTER*1 Specifies whether the upper or lower triangular part of the symmetric matrix A is stored: = 'U': Upper triangular = 'L': Lower triangular /param>
Parameters
N (input) INTEGER The order of the matrix A. /param>
Parameters
NB (input) INTEGER The number of rows and columns to be reduced. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the symmetric matrix A. If UPLO = 'U', the leading n-by-n upper triangular part of A contains the upper triangular part of the matrix A, and the strictly lower triangular part of A is not referenced. If UPLO = 'L', the leading n-by-n lower triangular part of A contains the lower triangular part of the matrix A, and the strictly upper triangular part of A is not referenced. On exit: if UPLO = 'U', the last NB columns have been reduced to tridiagonal form, with the diagonal elements overwriting the diagonal elements of A; the elements above the diagonal with the array TAU, represent the orthogonal matrix Q as a product of elementary reflectors; if UPLO = 'L', the first NB columns have been reduced to tridiagonal form, with the diagonal elements overwriting the diagonal elements of A; the elements below the diagonal with the array TAU, represent the orthogonal matrix Q as a product of elementary reflectors. See Further Details. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. (1,N). /param>
Parameters
E (output) DOUBLE PRECISION array, dimension (N-1) If UPLO = 'U', E(n-nb:n-1) contains the superdiagonal elements of the last NB columns of the reduced matrix; if UPLO = 'L', E(1:nb) contains the subdiagonal elements of the first NB columns of the reduced matrix. /param>
Parameters
TAU (output) DOUBLE PRECISION array, dimension (N-1) The scalar factors of the elementary reflectors, stored in TAU(n-nb:n-1) if UPLO = 'U', and in TAU(1:nb) if UPLO = 'L'. See Further Details. /param>
Parameters
W (output) DOUBLE PRECISION array, dimension (LDW,NB) The n-by-nb matrix W required to update the unreduced part of A. /param>
Parameters
LDW (input) INTEGER The leading dimension of the array W. LDW .GE. max(1,N). /param>
References DotNumerics.LinearAlgebra.CSLapack.DLATRD.HALF, DotNumerics.LinearAlgebra.CSLapack.DLATRD.ONE, DotNumerics.LinearAlgebra.CSLapack.DDOT.Run(), DotNumerics.LinearAlgebra.CSLapack.DAXPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYMV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLATRD.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYTRD.Run().
Member Data Documentation
_daxpy
DAXPY DotNumerics.LinearAlgebra.CSLapack.DLATRD._daxpy private
_dgemv
DGEMV DotNumerics.LinearAlgebra.CSLapack.DLATRD._dgemv private
_dlarfg
DLARFG DotNumerics.LinearAlgebra.CSLapack.DLATRD._dlarfg private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DLATRD._dscal private
_dsymv
DSYMV DotNumerics.LinearAlgebra.CSLapack.DLATRD._dsymv private
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLATRD._lsame private
_ddot
DDOT DotNumerics.LinearAlgebra.CSLapack.DLATRD._ddot private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLATRD.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLATRD.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLATRD.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLATRD.Run().
HALF
const double DotNumerics.LinearAlgebra.CSLapack.DLATRD.HALF = 0.5E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLATRD.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlatrd.cs