Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAQR3 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAQR3 Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006 /summary>
Public Member Functions
DLAQR3 (DLAMCH dlamch, ILAENV ilaenv, DCOPY dcopy, DGEHRD dgehrd, DGEMM dgemm, DLABAD dlabad, DLACPY dlacpy, DLAHQR dlahqr, DLANV2 dlanv2, DLAQR4 dlaqr4, DLARF dlarf, DLARFG dlarfg, DLASET dlaset, DORGHR dorghr, DTREXC dtrexc)
DLAQR3 ()
void Run (bool WANTT, bool WANTZ, int N, int KTOP, int KBOT, int NW, ref double[] H, int offset_h, int LDH, int ILOZ, int IHIZ, ref double[] Z, int offset_z, int LDZ, ref int NS, ref int ND, ref double[] SR, int offset_sr, ref double[] SI, int offset_si, ref double[] V, int offset_v, int LDV, int NH, ref double[] T, int offset_t, int LDT, int NV, ref double[] WV, int offset_wv, int LDWV, ref double[] WORK, int offset_work, int LWORK)
Private Attributes
DLAMCH _dlamch
ILAENV _ilaenv
DCOPY _dcopy
DGEHRD _dgehrd
DGEMM _dgemm
DLABAD _dlabad
DLACPY _dlacpy
DLAHQR _dlahqr
DLANV2 _dlanv2
DLAQR4 _dlaqr4
DLARF _dlarf
DLARFG _dlarfg
DLASET _dlaset
DORGHR _dorghr
DTREXC _dtrexc
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006 /summary>
Constructor & Destructor Documentation
DLAQR3() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAQR3.DLAQR3 (DLAMCH dlamch, ILAENV ilaenv, DCOPY dcopy, DGEHRD dgehrd, DGEMM dgemm, DLABAD dlabad, DLACPY dlacpy, DLAHQR dlahqr, DLANV2 dlanv2, DLAQR4 dlaqr4, DLARF dlarf, DLARFG dlarfg, DLASET dlaset, DORGHR dorghr, DTREXC dtrexc) inline
DLAQR3() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAQR3.DLAQR3 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAQR3.Run (bool WANTT, bool WANTZ, int N, int KTOP, int KBOT, int NW, ref double[] H, int offset_h, int LDH, int ILOZ, int IHIZ, ref double[] Z, int offset_z, int LDZ, ref int NS, ref int ND, ref double[] SR, int offset_sr, ref double[] SI, int offset_si, ref double[] V, int offset_v, int LDV, int NH, ref double[] T, int offset_t, int LDT, int NV, ref double[] WV, int offset_wv, int LDWV, ref double[] WORK, int offset_work, int LWORK) inline
Parameters
WANTT (input) LOGICAL If .TRUE., then the Hessenberg matrix H is fully updated so that the quasi-triangular Schur factor may be computed (in cooperation with the calling subroutine). If .FALSE., then only enough of H is updated to preserve the eigenvalues. /param>
Parameters
WANTZ (input) LOGICAL If .TRUE., then the orthogonal matrix Z is updated so so that the orthogonal Schur factor may be computed (in cooperation with the calling subroutine). If .FALSE., then Z is not referenced. /param>
Parameters
N (input) INTEGER The order of the matrix H and (if WANTZ is .TRUE.) the order of the orthogonal matrix Z. /param>
Parameters
KTOP (input) INTEGER It is assumed that either KTOP = 1 or H(KTOP,KTOP-1)=0. KBOT and KTOP together determine an isolated block along the diagonal of the Hessenberg matrix. /param>
Parameters
KBOT (input) INTEGER It is assumed without a check that either KBOT = N or H(KBOT+1,KBOT)=0. KBOT and KTOP together determine an isolated block along the diagonal of the Hessenberg matrix. /param>
Parameters
NW (input) INTEGER Deflation window size. 1 .LE. NW .LE. (KBOT-KTOP+1). /param>
Parameters
H (input/output) DOUBLE PRECISION array, dimension (LDH,N) On input the initial N-by-N section of H stores the Hessenberg matrix undergoing aggressive early deflation. On output H has been transformed by an orthogonal similarity transformation, perturbed, and the returned to Hessenberg form that (it is to be hoped) has some zero subdiagonal entries. /param>
Parameters
LDH (input) integer Leading dimension of H just as declared in the calling subroutine. N .LE. LDH /param>
Parameters
ILOZ (input) INTEGER /param>
Parameters
IHIZ (input) INTEGER Specify the rows of Z to which transformations must be applied if WANTZ is .TRUE.. 1 .LE. ILOZ .LE. IHIZ .LE. N. /param>
Parameters
Z (input/output) DOUBLE PRECISION array, dimension (LDZ,IHI) IF WANTZ is .TRUE., then on output, the orthogonal similarity transformation mentioned above has been accumulated into Z(ILOZ:IHIZ,ILO:IHI) from the right. If WANTZ is .FALSE., then Z is unreferenced. /param>
Parameters
LDZ (input) integer The leading dimension of Z just as declared in the calling subroutine. 1 .LE. LDZ. /param>
Parameters
NS (output) integer The number of unconverged (ie approximate) eigenvalues returned in SR and SI that may be used as shifts by the calling subroutine. /param>
Parameters
ND (output) integer The number of converged eigenvalues uncovered by this subroutine. /param>
Parameters
SR (output) DOUBLE PRECISION array, dimension KBOT /param>
Parameters
SI (output) DOUBLE PRECISION array, dimension KBOT On output, the real and imaginary parts of approximate eigenvalues that may be used for shifts are stored in SR(KBOT-ND-NS+1) through SR(KBOT-ND) and SI(KBOT-ND-NS+1) through SI(KBOT-ND), respectively. The real and imaginary parts of converged eigenvalues are stored in SR(KBOT-ND+1) through SR(KBOT) and SI(KBOT-ND+1) through SI(KBOT), respectively. /param>
Parameters
V (workspace) DOUBLE PRECISION array, dimension (LDV,NW) An NW-by-NW work array. /param>
Parameters
LDV (input) integer scalar The leading dimension of V just as declared in the calling subroutine. NW .LE. LDV /param>
Parameters
NH (input) integer scalar The number of columns of T. NH.GE.NW. /param>
Parameters
T (workspace) DOUBLE PRECISION array, dimension (LDT,NW) /param>
Parameters
LDT (input) integer The leading dimension of T just as declared in the calling subroutine. NW .LE. LDT /param>
Parameters
NV (input) integer The number of rows of work array WV available for workspace. NV.GE.NW. /param>
Parameters
WV (workspace) DOUBLE PRECISION array, dimension (LDWV,NW) /param>
Parameters
LDWV (input) integer The leading dimension of W just as declared in the calling subroutine. NW .LE. LDV /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension LWORK. On exit, WORK(1) is set to an estimate of the optimal value of LWORK for the given values of N, NW, KTOP and KBOT. /param>
Parameters
LWORK (input) integer The dimension of the work array WORK. LWORK = 2*NW suffices, but greater efficiency may result from larger values of LWORK.
If LWORK = -1, then a workspace query is assumed; DLAQR3 only estimates the optimal workspace size for the given values of N, NW, KTOP and KBOT. The estimate is returned in WORK(1). No error message related to LWORK is issued by XERBLA. Neither H nor Z are accessed. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLAQR3.ONE, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLABAD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASET.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANV2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGHR.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEHRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DTREXC.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAHQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR4.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAQR3.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQR0.Run().
Member Data Documentation
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLAQR3._dlamch private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DLAQR3._ilaenv private
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLAQR3._dcopy private
_dgehrd
DGEHRD DotNumerics.LinearAlgebra.CSLapack.DLAQR3._dgehrd private
_dgemm
DGEMM DotNumerics.LinearAlgebra.CSLapack.DLAQR3._dgemm private
_dlabad
DLABAD DotNumerics.LinearAlgebra.CSLapack.DLAQR3._dlabad private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DLAQR3._dlacpy private
_dlahqr
DLAHQR DotNumerics.LinearAlgebra.CSLapack.DLAQR3._dlahqr private
_dlanv2
DLANV2 DotNumerics.LinearAlgebra.CSLapack.DLAQR3._dlanv2 private
_dlaqr4
DLAQR4 DotNumerics.LinearAlgebra.CSLapack.DLAQR3._dlaqr4 private
_dlarf
DLARF DotNumerics.LinearAlgebra.CSLapack.DLAQR3._dlarf private
_dlarfg
DLARFG DotNumerics.LinearAlgebra.CSLapack.DLAQR3._dlarfg private
_dlaset
DLASET DotNumerics.LinearAlgebra.CSLapack.DLAQR3._dlaset private
_dorghr
DORGHR DotNumerics.LinearAlgebra.CSLapack.DLAQR3._dorghr private
_dtrexc
DTREXC DotNumerics.LinearAlgebra.CSLapack.DLAQR3._dtrexc private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAQR3.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQR3.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAQR3.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQR3.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlaqr3.cs