Doc: IGLib EXTENDED: AForge.Imaging.Textures.TextileTexture Class Reference
AForge.Imaging.Textures.TextileTexture Class Reference
Textile texture.
Public Member Functions
TextileTexture ()
Initializes a new instance of the TextileTexture class.
float[,] Generate (int width, int height)
Generate texture.
void Reset ()
Reset generator.
Private Attributes
AForge.Math.PerlinNoise noise = new AForge.Math.PerlinNoise(3, 0.65, 1.0 / 8, 1.0)
Random rand = new Random()
int r
Detailed Description
Textile texture.
The texture generator creates textures with effect of textile.
The generator is based on the Perlin noise function.
Sample usage:
// create texture generator
TextileTexture textureGenerator = new TextileTexture();
// generate new texture
float[,] texture = textureGenerator.Generate(320, 240);
// convert it to image to visualize
Bitmap textureImage = TextureTools.ToBitmap(texture);
Result image:
Constructor & Destructor Documentation
TextileTexture()
AForge.Imaging.Textures.TextileTexture.TextileTexture () inline
Initializes a new instance of the TextileTexture class.
References AForge.Imaging.Textures.TextileTexture.Reset().
Member Function Documentation
Generate()
float [,] AForge.Imaging.Textures.TextileTexture.Generate (int width, int height) inline
Generate texture.
Parameters
width Texture's width.
height Texture's height.
Returns
Two dimensional array of intensities.
Generates new texture of the specified size.
Implements AForge.Imaging.Textures.ITextureGenerator.
References AForge.Math.PerlinNoise.Function2D(), AForge.Imaging.Textures.TextileTexture.noise, and AForge.Imaging.Textures.TextileTexture.r.
Reset()
void AForge.Imaging.Textures.TextileTexture.Reset () inline
Reset generator.
Regenerates internal random numbers.
Implements AForge.Imaging.Textures.ITextureGenerator.
References AForge.Imaging.Textures.TextileTexture.r, and AForge.Imaging.Textures.TextileTexture.rand.
Referenced by AForge.Imaging.Textures.TextileTexture.TextileTexture().
Member Data Documentation
noise
AForge.Math.PerlinNoise AForge.Imaging.Textures.TextileTexture.noise = new AForge.Math.PerlinNoise(3, 0.65, 1.0 / 8, 1.0) private
Referenced by AForge.Imaging.Textures.TextileTexture.Generate().
rand
Random AForge.Imaging.Textures.TextileTexture.rand = new Random() private
Referenced by AForge.Imaging.Textures.TextileTexture.Reset().
r
int AForge.Imaging.Textures.TextileTexture.r private
Referenced by AForge.Imaging.Textures.TextileTexture.Generate(), and AForge.Imaging.Textures.TextileTexture.Reset().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Textures/TextileTexture.cs