Doc: IGLib EXTENDED: NUnit.Engine.Tests.AsyncTestEngineResultTests Class Reference
NUnit.Engine.Tests.AsyncTestEngineResultTests Class Reference
Public Member Functions
void SetUp ()
void Result_ThrowsIfNotSet ()
void SetResult_ThrowsIfNull ()
void SetResult_ThrowsIfSetTwice ()
void IsComplete_FalseIfNotComplete ()
void IsComplete_TrueIfComplete ()
void Wait_ReturnsFalseTillTestCompletes ()
void Wait_AllowsMultipleWaits ()
Private Attributes
AsyncTestEngineResult _asyncResult
Member Function Documentation
SetUp()
void NUnit.Engine.Tests.AsyncTestEngineResultTests.SetUp () inline
References NUnit.Engine.Tests.AsyncTestEngineResultTests._asyncResult.
Result_ThrowsIfNotSet()
void NUnit.Engine.Tests.AsyncTestEngineResultTests.Result_ThrowsIfNotSet () inline
References NUnit.Engine.Tests.AsyncTestEngineResultTests._asyncResult, NUnit.Engine.AsyncTestEngineResult.EngineResult, NUnit.Framework.Assert.Throws(), and NUnit.Engine.TestEngineResult.Xml.
SetResult_ThrowsIfNull()
void NUnit.Engine.Tests.AsyncTestEngineResultTests.SetResult_ThrowsIfNull () inline
References NUnit.Engine.Tests.AsyncTestEngineResultTests._asyncResult, NUnit.Engine.AsyncTestEngineResult.SetResult(), and NUnit.Framework.Assert.Throws().
SetResult_ThrowsIfSetTwice()
void NUnit.Engine.Tests.AsyncTestEngineResultTests.SetResult_ThrowsIfSetTwice () inline
References NUnit.Engine.Tests.AsyncTestEngineResultTests._asyncResult, NUnit.Engine.AsyncTestEngineResult.SetResult(), and NUnit.Framework.Assert.Throws().
IsComplete_FalseIfNotComplete()
void NUnit.Engine.Tests.AsyncTestEngineResultTests.IsComplete_FalseIfNotComplete () inline
References NUnit.Engine.Tests.AsyncTestEngineResultTests._asyncResult, NUnit.Engine.AsyncTestEngineResult.IsComplete, and NUnit.Framework.Assert.IsFalse().
IsComplete_TrueIfComplete()
void NUnit.Engine.Tests.AsyncTestEngineResultTests.IsComplete_TrueIfComplete () inline
References NUnit.Engine.Tests.AsyncTestEngineResultTests._asyncResult, NUnit.Engine.AsyncTestEngineResult.IsComplete, NUnit.Framework.Assert.IsTrue(), and NUnit.Engine.AsyncTestEngineResult.SetResult().
Wait_ReturnsFalseTillTestCompletes()
void NUnit.Engine.Tests.AsyncTestEngineResultTests.Wait_ReturnsFalseTillTestCompletes () inline
References NUnit.Engine.Tests.AsyncTestEngineResultTests._asyncResult, NUnit.Framework.Assert.AreEqual(), NUnit.Engine.AsyncTestEngineResult.EngineResult, NUnit.Framework.Assert.IsFalse(), NUnit.Framework.Assert.IsTrue(), NUnit.Engine.AsyncTestEngineResult.SetResult(), NUnit.Engine.AsyncTestEngineResult.Wait(), and NUnit.Engine.TestEngineResult.Xml.
Wait_AllowsMultipleWaits()
void NUnit.Engine.Tests.AsyncTestEngineResultTests.Wait_AllowsMultipleWaits () inline
References NUnit.Engine.Tests.AsyncTestEngineResultTests._asyncResult, NUnit.Framework.Assert.IsTrue(), NUnit.Engine.AsyncTestEngineResult.SetResult(), and NUnit.Engine.AsyncTestEngineResult.Wait().
Member Data Documentation
_asyncResult
AsyncTestEngineResult NUnit.Engine.Tests.AsyncTestEngineResultTests._asyncResult private
Referenced by NUnit.Engine.Tests.AsyncTestEngineResultTests.IsComplete_FalseIfNotComplete(), NUnit.Engine.Tests.AsyncTestEngineResultTests.IsComplete_TrueIfComplete(), NUnit.Engine.Tests.AsyncTestEngineResultTests.Result_ThrowsIfNotSet(), NUnit.Engine.Tests.AsyncTestEngineResultTests.SetResult_ThrowsIfNull(), NUnit.Engine.Tests.AsyncTestEngineResultTests.SetResult_ThrowsIfSetTwice(), NUnit.Engine.Tests.AsyncTestEngineResultTests.SetUp(), NUnit.Engine.Tests.AsyncTestEngineResultTests.Wait_AllowsMultipleWaits(), and NUnit.Engine.Tests.AsyncTestEngineResultTests.Wait_ReturnsFalseTillTestCompletes().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/AsyncTestEngineResultTests.cs