Doc: IGLib EXTENDED: alglib.testschurunit Class Reference
alglib.testschurunit Class Reference
Static Public Member Functions
static bool testschur (bool silent)
static bool testschur (bool silent)
static bool _pexec_testschur (bool silent)
Static Private Member Functions
static void fillsparsea (ref double[,] a, int n, double sparcity)
static void testschurproblem (double[,] a, int n, ref double materr, ref double orterr, ref bool errstruct, ref bool wfailed)
static void fillsparsea (ref double[,] a, int n, double sparcity)
static void testschurproblem (double[,] a, int n, ref double materr, ref double orterr, ref bool errstruct, ref bool wfailed)
Member Function Documentation
testschur() [1/2]
static bool alglib.testschurunit.testschur (bool silent) inline static
References alglib.testschurunit.fillsparsea(), alglib.math.machineepsilon, alglib.math.randomreal(), and alglib.testschurunit.testschurproblem().
Referenced by alglib.testschurunit._pexec_testschur(), and _Test.Main().
fillsparsea() [1/2]
static void alglib.testschurunit.fillsparsea (ref double a[,], int n, double sparcity) inline static private
References alglib.math.randomreal().
Referenced by alglib.testschurunit.testschur().
testschurproblem() [1/2]
static void alglib.testschurunit.testschurproblem (double a[,], int n, ref double materr, ref double orterr, ref bool errstruct, ref bool wfailed) inline static private
References alglib.schur.rmatrixschur().
Referenced by alglib.testschurunit.testschur().
testschur() [2/2]
static bool alglib.testschurunit.testschur (bool silent) inline static
References alglib.testschurunit.fillsparsea(), alglib.math.machineepsilon, alglib.math.randomreal(), and alglib.testschurunit.testschurproblem().
_pexec_testschur()
static bool alglib.testschurunit._pexec_testschur (bool silent) inline static
References alglib.testschurunit.testschur().
Referenced by _Test.Main().
fillsparsea() [2/2]
static void alglib.testschurunit.fillsparsea (ref double a[,], int n, double sparcity) inline static private
References alglib.math.randomreal().
testschurproblem() [2/2]
static void alglib.testschurunit.testschurproblem (double a[,], int n, ref double materr, ref double orterr, ref bool errstruct, ref bool wfailed) inline static private
References alglib.schur.rmatrixschur().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs