Doc: IGLib EXTENDED: AForge.Imaging.Filters.Jitter Class Reference
AForge.Imaging.Filters.Jitter Class Reference
Jitter filter.
Public Member Functions
Jitter ()
Initializes a new instance of the Jitter class.
Jitter (int radius)
Initializes a new instance of the Jitter class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseUsingCopyPartialFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage source, UnmanagedImage destination, Rectangle rect)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
int Radius [get, set]
Jittering radius, [1, 10]
Properties inherited from AForge.Imaging.Filters.BaseUsingCopyPartialFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
int radius = 2
Random rand = new Random()
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Jitter filter.
The filter moves each pixel of a source image in random direction within a window of specified radius.
The filter accepts 8 bpp grayscale images and 24/32 color images for processing.
Sample usage:
// create filter
Jitter filter = new Jitter(4);
// apply the filter
filter.ApplyInPlace(image);
Initial image:
Result image:
Constructor & Destructor Documentation
Jitter() [1/2]
AForge.Imaging.Filters.Jitter.Jitter () inline
Initializes a new instance of the Jitter class.
References AForge.Imaging.Filters.Jitter.formatTranslations.
Jitter() [2/2]
AForge.Imaging.Filters.Jitter.Jitter (int radius) inline
Initializes a new instance of the Jitter class.
Parameters
radius Jittering radius.
References AForge.Imaging.Filters.Jitter.radius, and AForge.Imaging.Filters.Jitter.Radius.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.Jitter.ProcessFilter (UnmanagedImage source, UnmanagedImage destination, Rectangle rect) inline protected virtual
Process the filter on the specified image.
Parameters
source Source image data.
destination Destination image data.
rect Image rectangle for processing by the filter.
Implements AForge.Imaging.Filters.BaseUsingCopyPartialFilter.
References AForge.SystemTools.CopyUnmanagedMemory(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.Filters.Jitter.radius, AForge.Imaging.Filters.Jitter.rand, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
Member Data Documentation
radius
int AForge.Imaging.Filters.Jitter.radius = 2 private
Referenced by AForge.Imaging.Filters.Jitter.Jitter(), and AForge.Imaging.Filters.Jitter.ProcessFilter().
rand
Random AForge.Imaging.Filters.Jitter.rand = new Random() private
Referenced by AForge.Imaging.Filters.Jitter.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.Jitter.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.Jitter.Jitter().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.Jitter.FormatTranslations get
Format translations dictionary.
See IFilterInformation.FormatTranslations documentation for additional information.
Radius
int AForge.Imaging.Filters.Jitter.Radius get set
Jittering radius, [1, 10]
Determines radius in which pixels can move.
Default value is set to 2.
Referenced by AForge.Imaging.Filters.Jitter.Jitter().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Other/Jitter.cs