Doc: IGLib EXTENDED: IG.Forms.VectorFunctionScriptForm Class Reference
IG.Forms.VectorFunctionScriptForm Class Reference
Public Member Functions
VectorFunctionScriptForm ()
VectorFunctionScriptForm ()
VectorFunctionScriptForm ()
VectorFunctionScriptForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
VectorFunctionScriptControl MainControl [get]
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
IG.Forms.VectorFunctionScriptControl vectorFunctionScriptControl1
Constructor & Destructor Documentation
VectorFunctionScriptForm() [1/4]
IG.Forms.VectorFunctionScriptForm.VectorFunctionScriptForm () inline
References IG.Forms.VectorFunctionScriptControl.HasChildUnsavedChanges, IG.Forms.VectorFunctionScriptControl.HasUnsavedChanges, IG.Forms.VectorFunctionScriptForm.InitializeComponent(), IG.Forms.VectorFunctionScriptControl.InitialScalarFunctionDefinitionStrings, IG.Forms.VectorFunctionScriptForm.MainControl, and IG.Forms.VectorFunctionScriptControl.SynchronizeData().
VectorFunctionScriptForm() [2/4]
IG.Forms.VectorFunctionScriptForm.VectorFunctionScriptForm () inline
References IG.Forms.VectorFunctionScriptForm.InitializeComponent(), IG.Forms.VectorFunctionScriptControl.InitialScalarFunctionDefinitionStrings, IG.Forms.VectorFunctionScriptForm.MainControl, and IG.Forms.VectorFunctionScriptControl.SynchronizeData().
VectorFunctionScriptForm() [3/4]
IG.Forms.VectorFunctionScriptForm.VectorFunctionScriptForm () inline
References IG.Forms.VectorFunctionScriptControl.HasChildUnsavedChanges, IG.Forms.VectorFunctionScriptControl.HasUnsavedChanges, IG.Forms.VectorFunctionScriptForm.InitializeComponent(), IG.Forms.VectorFunctionScriptControl.InitialScalarFunctionDefinitionStrings, IG.Forms.VectorFunctionScriptForm.MainControl, and IG.Forms.VectorFunctionScriptControl.SynchronizeData().
VectorFunctionScriptForm() [4/4]
IG.Forms.VectorFunctionScriptForm.VectorFunctionScriptForm () inline
References IG.Forms.VectorFunctionScriptControl.HasChildUnsavedChanges, IG.Forms.VectorFunctionScriptControl.HasUnsavedChanges, IG.Forms.VectorFunctionScriptForm.InitializeComponent(), IG.Forms.VectorFunctionScriptControl.InitialScalarFunctionDefinitionStrings, IG.Forms.VectorFunctionScriptForm.MainControl, and IG.Forms.VectorFunctionScriptControl.SynchronizeData().
Member Function Documentation
Dispose() [1/4]
override void IG.Forms.VectorFunctionScriptForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.VectorFunctionScriptForm.components.
InitializeComponent() [1/4]
void IG.Forms.VectorFunctionScriptForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.VectorFunctionScriptControl.FunctionDescription, IG.Forms.VectorFunctionScriptControl.FunctionName, IG.Forms.VectorFunctionScriptControl.FunctionNames, IG.Forms.VectorFunctionScriptControl.InitialScalarFunctionDefinitionStrings, IG.Forms.VectorFunctionScriptControl.NumParameters, IG.Forms.VectorFunctionScriptControl.NumValues, IG.Forms.VectorFunctionScriptControl.ParameterNames, and IG.Forms.VectorFunctionScriptForm.vectorFunctionScriptControl1.
Referenced by IG.Forms.VectorFunctionScriptForm.VectorFunctionScriptForm().
Dispose() [2/4]
override void IG.Forms.VectorFunctionScriptForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.VectorFunctionScriptForm.components.
InitializeComponent() [2/4]
void IG.Forms.VectorFunctionScriptForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.VectorFunctionScriptControl.FunctionDescription, IG.Forms.VectorFunctionScriptControl.FunctionName, IG.Forms.VectorFunctionScriptControl.FunctionNames, IG.Forms.VectorFunctionScriptControl.InitialScalarFunctionDefinitionStrings, IG.Forms.VectorFunctionScriptControl.NumParameters, IG.Forms.VectorFunctionScriptControl.NumValues, IG.Forms.VectorFunctionScriptControl.ParameterNames, and IG.Forms.VectorFunctionScriptForm.vectorFunctionScriptControl1.
Dispose() [3/4]
override void IG.Forms.VectorFunctionScriptForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.VectorFunctionScriptForm.components.
InitializeComponent() [3/4]
void IG.Forms.VectorFunctionScriptForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.VectorFunctionScriptControl.FunctionDescription, IG.Forms.VectorFunctionScriptControl.FunctionName, IG.Forms.VectorFunctionScriptControl.FunctionNames, IG.Forms.VectorFunctionScriptControl.InitialScalarFunctionDefinitionStrings, IG.Forms.VectorFunctionScriptControl.NumParameters, IG.Forms.VectorFunctionScriptControl.NumValues, IG.Forms.VectorFunctionScriptControl.ParameterNames, and IG.Forms.VectorFunctionScriptForm.vectorFunctionScriptControl1.
Dispose() [4/4]
override void IG.Forms.VectorFunctionScriptForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.VectorFunctionScriptForm.components.
InitializeComponent() [4/4]
void IG.Forms.VectorFunctionScriptForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.VectorFunctionScriptControl.FunctionDescription, IG.Forms.VectorFunctionScriptControl.FunctionName, IG.Forms.VectorFunctionScriptControl.FunctionNames, IG.Forms.VectorFunctionScriptControl.InitialScalarFunctionDefinitionStrings, IG.Forms.VectorFunctionScriptControl.NumParameters, IG.Forms.VectorFunctionScriptControl.NumValues, IG.Forms.VectorFunctionScriptControl.ParameterNames, and IG.Forms.VectorFunctionScriptForm.vectorFunctionScriptControl1.
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.VectorFunctionScriptForm.components = null private
Required designer variable.
Referenced by IG.Forms.VectorFunctionScriptForm.Dispose().
vectorFunctionScriptControl1
IG Forms VectorFunctionScriptControl IG.Forms.VectorFunctionScriptForm.vectorFunctionScriptControl1 private
Referenced by IG.Forms.VectorFunctionScriptForm.InitializeComponent().
Property Documentation
MainControl
VectorFunctionScriptControl IG.Forms.VectorFunctionScriptForm.MainControl get private
Referenced by IG.Forms.VectorFunctionScriptForm.VectorFunctionScriptForm().
The documentation for this class was generated from the following files:
iglib/extensions/iglibext/Forms/Numeric/VectorFunctionScriptForm.cs
iglib/extensions/iglibext/Forms/Numeric/VectorFunctionScriptForm.Designer.cs