Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DBDSDC Class Reference
DotNumerics.LinearAlgebra.CSLapack.DBDSDC Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DBDSDC (LSAME lsame, ILAENV ilaenv, DLAMCH dlamch, DLANST dlanst, DCOPY dcopy, DLARTG dlartg, DLASCL dlascl, DLASD0 dlasd0, DLASDA dlasda, DLASDQ dlasdq, DLASET dlaset, DLASR dlasr, DSWAP dswap, XERBLA xerbla)
DBDSDC ()
void Run (string UPLO, string COMPQ, int N, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] U, int offset_u, int LDU, ref double[] VT, int offset_vt, int LDVT, ref double[] Q, int offset_q, ref int[] IQ, int offset_iq, ref double[] WORK, int offset_work, ref int[] IWORK, int offset_iwork, ref int INFO)
Private Attributes
LSAME _lsame
ILAENV _ilaenv
DLAMCH _dlamch
DLANST _dlanst
DCOPY _dcopy
DLARTG _dlartg
DLASCL _dlascl
DLASD0 _dlasd0
DLASDA _dlasda
DLASDQ _dlasdq
DLASET _dlaset
DLASR _dlasr
DSWAP _dswap
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
const double TWO = 2.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DBDSDC computes the singular value decomposition (SVD) of a real N-by-N (upper or lower) bidiagonal matrix B: B = U * S * VT, using a divide and conquer method, where S is a diagonal matrix with non-negative diagonal elements (the singular values of B), and U and VT are orthogonal matrices of left and right singular vectors, respectively. DBDSDC can be used to compute all singular values, and optionally, singular vectors or singular vectors in compact form.
This code makes very mild assumptions about floating point arithmetic. It will work on machines with a guard digit in add/subtract, or on those binary machines without guard digits which subtract like the Cray X-MP, Cray Y-MP, Cray C-90, or Cray-2. It could conceivably fail on hexadecimal or decimal machines without guard digits, but we know of none. See DLASD3 for details.
The code currently calls DLASDQ if singular values only are desired. However, it can be slightly modified to compute singular values using the divide and conquer method.
/summary>
Constructor & Destructor Documentation
DBDSDC() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DBDSDC.DBDSDC (LSAME lsame, ILAENV ilaenv, DLAMCH dlamch, DLANST dlanst, DCOPY dcopy, DLARTG dlartg, DLASCL dlascl, DLASD0 dlasd0, DLASDA dlasda, DLASDQ dlasdq, DLASET dlaset, DLASR dlasr, DSWAP dswap, XERBLA xerbla) inline
DBDSDC() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DBDSDC.DBDSDC () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DBDSDC.Run (string UPLO, string COMPQ, int N, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] U, int offset_u, int LDU, ref double[] VT, int offset_vt, int LDVT, ref double[] Q, int offset_q, ref int[] IQ, int offset_iq, ref double[] WORK, int offset_work, ref int[] IWORK, int offset_iwork, ref int INFO) inline
Purpose
DBDSDC computes the singular value decomposition (SVD) of a real N-by-N (upper or lower) bidiagonal matrix B: B = U * S * VT, using a divide and conquer method, where S is a diagonal matrix with non-negative diagonal elements (the singular values of B), and U and VT are orthogonal matrices of left and right singular vectors, respectively. DBDSDC can be used to compute all singular values, and optionally, singular vectors or singular vectors in compact form.
This code makes very mild assumptions about floating point arithmetic. It will work on machines with a guard digit in add/subtract, or on those binary machines without guard digits which subtract like the Cray X-MP, Cray Y-MP, Cray C-90, or Cray-2. It could conceivably fail on hexadecimal or decimal machines without guard digits, but we know of none. See DLASD3 for details.
The code currently calls DLASDQ if singular values only are desired. However, it can be slightly modified to compute singular values using the divide and conquer method.
/summary>
Parameters
UPLO (input) CHARACTER*1 = 'U': B is upper bidiagonal. = 'L': B is lower bidiagonal. /param>
Parameters
COMPQ (input) CHARACTER*1 Specifies whether singular vectors are to be computed as follows: = 'N': Compute singular values only; = 'P': Compute singular values and compute singular vectors in compact form; = 'I': Compute singular values and singular vectors. /param>
Parameters
N (input) INTEGER The order of the matrix B. N .GE. 0. /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension (N) On entry, the n diagonal elements of the bidiagonal matrix B. On exit, if INFO=0, the singular values of B. /param>
Parameters
E (input/output) DOUBLE PRECISION array, dimension (N-1) On entry, the elements of E contain the offdiagonal elements of the bidiagonal matrix whose SVD is desired. On exit, E has been destroyed. /param>
Parameters
U (output) DOUBLE PRECISION array, dimension (LDU,N) If COMPQ = 'I', then: On exit, if INFO = 0, U contains the left singular vectors of the bidiagonal matrix. For other values of COMPQ, U is not referenced. /param>
Parameters
LDU (input) INTEGER The leading dimension of the array U. LDU .GE. 1. If singular vectors are desired, then LDU .GE. max(1, N). /param>
Parameters
VT (output) DOUBLE PRECISION array, dimension (LDVT,N) If COMPQ = 'I', then: On exit, if INFO = 0, VT' contains the right singular vectors of the bidiagonal matrix. For other values of COMPQ, VT is not referenced. /param>
Parameters
LDVT (input) INTEGER The leading dimension of the array VT. LDVT .GE. 1. If singular vectors are desired, then LDVT .GE. max(1, N). /param>
Parameters
Q (output) DOUBLE PRECISION array, dimension (LDQ) If COMPQ = 'P', then: On exit, if INFO = 0, Q and IQ contain the left and right singular vectors in a compact form, requiring O(N log N) space instead of 2*N**2. In particular, Q contains all the DOUBLE PRECISION data in LDQ .GE. N*(11 + 2*SMLSIZ + 8*INT(LOG_2(N/(SMLSIZ+1)))) words of memory, where SMLSIZ is returned by ILAENV and is equal to the maximum size of the subproblems at the bottom of the computation tree (usually about 25). For other values of COMPQ, Q is not referenced. /param>
Parameters
IQ (output) INTEGER array, dimension (LDIQ) If COMPQ = 'P', then: On exit, if INFO = 0, Q and IQ contain the left and right singular vectors in a compact form, requiring O(N log N) space instead of 2*N**2. In particular, IQ contains all INTEGER data in LDIQ .GE. N*(3 + 3*INT(LOG_2(N/(SMLSIZ+1)))) words of memory, where SMLSIZ is returned by ILAENV and is equal to the maximum size of the subproblems at the bottom of the computation tree (usually about 25). For other values of COMPQ, IQ is not referenced. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) If COMPQ = 'N' then LWORK .GE. (4 * N). If COMPQ = 'P' then LWORK .GE. (6 * N). If COMPQ = 'I' then LWORK .GE. (3 * N**2 + 4 * N). /param>
Parameters
IWORK (workspace) INTEGER array, dimension (8*N) /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. .GT. 0: The algorithm failed to compute an singular value. The update process of divide and conquer failed. /param>
References DotNumerics.LinearAlgebra.CSLapack.DBDSDC.ONE, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DSWAP.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASET.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARTG.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANST.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD0.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASDQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASDA.Run(), DotNumerics.FortranLibrary.FortranLib.Sign(), DotNumerics.LinearAlgebra.CSLapack.DBDSDC.TWO, and DotNumerics.LinearAlgebra.CSLapack.DBDSDC.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DBDSDC._lsame private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DBDSDC._ilaenv private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DBDSDC._dlamch private
_dlanst
DLANST DotNumerics.LinearAlgebra.CSLapack.DBDSDC._dlanst private
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DBDSDC._dcopy private
_dlartg
DLARTG DotNumerics.LinearAlgebra.CSLapack.DBDSDC._dlartg private
_dlascl
DLASCL DotNumerics.LinearAlgebra.CSLapack.DBDSDC._dlascl private
_dlasd0
DLASD0 DotNumerics.LinearAlgebra.CSLapack.DBDSDC._dlasd0 private
_dlasda
DLASDA DotNumerics.LinearAlgebra.CSLapack.DBDSDC._dlasda private
_dlasdq
DLASDQ DotNumerics.LinearAlgebra.CSLapack.DBDSDC._dlasdq private
_dlaset
DLASET DotNumerics.LinearAlgebra.CSLapack.DBDSDC._dlaset private
_dlasr
DLASR DotNumerics.LinearAlgebra.CSLapack.DBDSDC._dlasr private
_dswap
DSWAP DotNumerics.LinearAlgebra.CSLapack.DBDSDC._dswap private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DBDSDC._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DBDSDC.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DBDSDC.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DBDSDC.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DBDSDC.Run().
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DBDSDC.TWO = 2.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DBDSDC.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dbdsdc.cs