Doc: IGLib EXTENDED: IG.Num.SimJMatProFileManagerBase.SimulationInfoBase Class Reference
IG.Num.SimJMatProFileManagerBase.SimulationInfoBase Class Reference
Contains information about the particular bundle of simulations to be performed.
Public Member Functions
SimulationInfoBase (SimJMatProFileManagerBase jmatFmArg, string argSimulationBundleName)
Constructs a manioulation objects for performing simulations on basis of material data calculated by JMatPro.
SimulationInfoBase (SimJMatProFileManagerBase jmatFmArg, string argSimulationBundleName, int numSimulationsPerMaterial)
Constructs a manioulation objects for performing simulations on basis of material data calculated by JMatPro.
MaterialDirectoryInfoBase CreateMaterialdirectoryInfo (string approximateDirectoryPath)
virtual MaterialDirectoryInfoBase CreateMaterialdirectoryInfo (DirectoryInfo dirInfo)
virtual void UpdateMaterialDirectories ()
Protected Attributes
string _simulationBundleName
int _numSimulationsPerMaterial = 1
List< MaterialDirectoryInfoBase > _materialDirectories = new List<MaterialDirectoryInfoBase>()
Properties
SimJMatProFileManagerBase JMatFm [get]
JMatPro file manager that is used for extracting information about the directory.
virtual string SimulationBundleName [get, protected set]
Name of the current simulation bundle.
virtual int NumSimulationsPerMaterial [get, set]
Number of simulations to be performed for each material.
List< MaterialDirectoryInfoBase > MaterialDirectories [get]
Private Member Functions
SimulationInfoBase ()
SimulationInfoBase (SimJMatProFileManagerBase jmatFmArg)
Constructs a manioulation objects for performing simulations on basis of material data calculated by JMatPro.
Private Attributes
readonly SimJMatProFileManagerBase _jMatFm
Detailed Description
Contains information about the particular bundle of simulations to be performed.
Objects of this class contain everything that is necessary to perform simulations:
- JMatPro file manager.
- A list of material directory information objects.
- A simulator performing numerical simulations.
Internally, the objects contain the folloeing data:
- A list of material directory information objects that are used to keep track how many simulations have already been performed for the specific material.
- Maximal number of simulations that must be performed for the specified object.
- Name of the simulation that is used to locate relevant information such as process parameter bounds and the location of the file where simulation results are stored.
The object provides the following fuctionality:
- Generation of the next set of process parameters for a given material.
- Calculation fo the output values for given combination of material and process parameters.
- Storage of previously calculated outputs and newly calculated outputs to the appropriate file in the material directory.
$A Igor Dec12;
Constructor & Destructor Documentation
SimulationInfoBase() [1/4]
IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.SimulationInfoBase () inline private
SimulationInfoBase() [2/4]
IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.SimulationInfoBase (SimJMatProFileManagerBase jmatFmArg) inline private
Constructs a manioulation objects for performing simulations on basis of material data calculated by JMatPro.
Used only as insomplete constructor to perform one part of initialization, thus it is defined as private.
Parameters
jmatFmArg JMatPro file manager used for manipulation with material calculations and other basic tasks.
References IG.Num.SimJMatProFileManagerBase.SimulationInfoBase._jMatFm.
SimulationInfoBase() [3/4]
IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.SimulationInfoBase (SimJMatProFileManagerBase jmatFmArg, string argSimulationBundleName) inline
Constructs a manioulation objects for performing simulations on basis of material data calculated by JMatPro.
Parameters
jmatFmArg JMatPro file manager used for manipulation with material calculations and other basic tasks.
argSimulationBundleName Name of the bundle of simulations represented by the current object.
References IG.Num.SimJMatProFileManagerBase.SimulationInfoBase._simulationBundleName.
SimulationInfoBase() [4/4]
IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.SimulationInfoBase (SimJMatProFileManagerBase jmatFmArg, string argSimulationBundleName, int numSimulationsPerMaterial) inline
Constructs a manioulation objects for performing simulations on basis of material data calculated by JMatPro.
Parameters
jmatFmArg JMatPro file manager used for manipulation with material calculations and other basic tasks.
argSimulationBundleName Name of the bundle of simulations represented by the current object.
References IG.Num.SimJMatProFileManagerBase.SimulationInfoBase._numSimulationsPerMaterial.
Member Function Documentation
CreateMaterialdirectoryInfo() [1/2]
MaterialDirectoryInfoBase IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.CreateMaterialdirectoryInfo (string approximateDirectoryPath) inline
References IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoryPath(), and IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.JMatFm.
Referenced by IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.UpdateMaterialDirectories().
CreateMaterialdirectoryInfo() [2/2]
virtual MaterialDirectoryInfoBase IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.CreateMaterialdirectoryInfo (DirectoryInfo dirInfo) inline virtual
References IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.JMatFm.
UpdateMaterialDirectories()
virtual void IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.UpdateMaterialDirectories () inline virtual
References IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.CreateMaterialdirectoryInfo(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereMaterialCalculated(), IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.JMatFm, and IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.MaterialDirectories.
Member Data Documentation
_jMatFm
readonly SimJMatProFileManagerBase IG.Num.SimJMatProFileManagerBase.SimulationInfoBase._jMatFm private
Referenced by IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.SimulationInfoBase().
_simulationBundleName
string IG.Num.SimJMatProFileManagerBase.SimulationInfoBase._simulationBundleName protected
Referenced by IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.SimulationInfoBase().
_numSimulationsPerMaterial
int IG.Num.SimJMatProFileManagerBase.SimulationInfoBase._numSimulationsPerMaterial = 1 protected
Referenced by IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.SimulationInfoBase().
_materialDirectories
List<MaterialDirectoryInfoBase> IG.Num.SimJMatProFileManagerBase.SimulationInfoBase._materialDirectories = new List<MaterialDirectoryInfoBase>() protected
Property Documentation
JMatFm
SimJMatProFileManagerBase IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.JMatFm get
JMatPro file manager that is used for extracting information about the directory.
Referenced by IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.CreateMaterialdirectoryInfo(), and IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.UpdateMaterialDirectories().
SimulationBundleName
virtual string IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.SimulationBundleName get protected set
Name of the current simulation bundle.
NumSimulationsPerMaterial
virtual int IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.NumSimulationsPerMaterial get set
Number of simulations to be performed for each material.
MaterialDirectories
List<MaterialDirectoryInfoBase> IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.MaterialDirectories get
Referenced by IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.UpdateMaterialDirectories().
The documentation for this class was generated from the following file:
shelldev/lib/extended/LibNeuralExt/interfaces_simulations/jmatpro/SimJMatProFMSimClasses.cs