Doc: IGLib EXTENDED: AForge.Neuro.Learning.ElasticNetworkLearning Class Reference
AForge.Neuro.Learning.ElasticNetworkLearning Class Reference
Elastic network learning algorithm
Public Member Functions
ElasticNetworkLearning (DistanceNetwork network)
Initializes a new instance of the ElasticNetworkLearning class
double Run (double[] input)
Runs learning iteration
double RunEpoch (double[][] input)
Runs learning epoch
ElasticNetworkLearning (DistanceNetwork network)
Initializes a new instance of the ElasticNetworkLearning class
double Run (double[] input)
Runs learning iteration
double RunEpoch (double[][] input)
Runs learning epoch
ElasticNetworkLearning (DistanceNetwork network)
Initializes a new instance of the ElasticNetworkLearning class.
double Run (double[] input)
Runs learning iteration.
double RunEpoch (double[][] input)
Runs learning epoch.
Properties
double LearningRate [get, set]
Learning rate
double LearningRadius [get, set]
Learning radius
Private Attributes
DistanceNetwork network
double[] distance
double learningRate = 0.1
double learningRadius = 0.5
double squaredRadius2 = 2 * 7 * 7
Detailed Description
Elastic network learning algorithm
Elastic network learning algorithm.
This class implements elastic network's learning algorithm and allows to train Distance Networks.
This class implements elastic network's learning algorithm and allows to train Distance Networks.
Constructor & Destructor Documentation
ElasticNetworkLearning() [1/3]
AForge.Neuro.Learning.ElasticNetworkLearning.ElasticNetworkLearning (DistanceNetwork network) inline
Initializes a new instance of the ElasticNetworkLearning class
Parameters
network Neural network to train
References AForge.Neuro.Learning.ElasticNetworkLearning.distance, and AForge.Neuro.Learning.ElasticNetworkLearning.network.
ElasticNetworkLearning() [2/3]
AForge.Neuro.Learning.ElasticNetworkLearning.ElasticNetworkLearning (DistanceNetwork network) inline
Initializes a new instance of the ElasticNetworkLearning class
Parameters
network Neural network to train
References AForge.Neuro.Learning.ElasticNetworkLearning.distance, and AForge.Neuro.Learning.ElasticNetworkLearning.network.
ElasticNetworkLearning() [3/3]
AForge.Neuro.Learning.ElasticNetworkLearning.ElasticNetworkLearning (DistanceNetwork network) inline
Initializes a new instance of the ElasticNetworkLearning class.
Parameters
network Neural network to train.
References AForge.Neuro.Learning.ElasticNetworkLearning.distance, AForge.Neuro.Network.Layers, AForge.Neuro.Learning.ElasticNetworkLearning.network, and AForge.Neuro.Layer.Neurons.
Member Function Documentation
Run() [1/3]
double AForge.Neuro.Learning.ElasticNetworkLearning.Run (double[] input) inline
Runs learning iteration
Parameters
input input vector
Returns
Returns learning error - summary absolute difference between updated weights and according inputs. The difference is measured according to the neurons distance to the winner neuron.
Implements AForge.Neuro.Learning.IUnsupervisedLearning.
References AForge.Neuro.Network.Compute(), AForge.Neuro.Learning.ElasticNetworkLearning.distance, AForge.Neuro.DistanceNetwork.GetWinner(), AForge.Neuro.Neuron.InputsCount, AForge.Neuro.Learning.ElasticNetworkLearning.learningRate, AForge.Neuro.Learning.ElasticNetworkLearning.network, AForge.Neuro.Layer.NeuronsCount, and AForge.Neuro.Learning.ElasticNetworkLearning.squaredRadius2.
Referenced by AForge.Neuro.Learning.ElasticNetworkLearning.RunEpoch(), and TSP.MainForm.SearchSolution().
RunEpoch() [1/3]
double AForge.Neuro.Learning.ElasticNetworkLearning.RunEpoch (double input[][]) inline
Runs learning epoch
Parameters
input array of input vectors
Returns
Returns summary learning error for the epoch. See Run method for details about learning error calculation.
Implements AForge.Neuro.Learning.IUnsupervisedLearning.
References AForge.Neuro.Learning.ElasticNetworkLearning.Run().
Run() [2/3]
double AForge.Neuro.Learning.ElasticNetworkLearning.Run (double[] input) inline
Runs learning iteration
Parameters
input input vector
Returns
Returns learning error - summary absolute difference between updated weights and according inputs. The difference is measured according to the neurons distance to the winner neuron.
Implements AForge.Neuro.Learning.IUnsupervisedLearning.
References AForge.Neuro.Network.Compute(), AForge.Neuro.Learning.ElasticNetworkLearning.distance, AForge.Neuro.DistanceNetwork.GetWinner(), AForge.Neuro.Neuron.InputsCount, AForge.Neuro.Learning.ElasticNetworkLearning.learningRate, AForge.Neuro.Learning.ElasticNetworkLearning.network, AForge.Neuro.Layer.NeuronsCount, and AForge.Neuro.Learning.ElasticNetworkLearning.squaredRadius2.
RunEpoch() [2/3]
double AForge.Neuro.Learning.ElasticNetworkLearning.RunEpoch (double input[][]) inline
Runs learning epoch
Parameters
input array of input vectors
Returns
Returns summary learning error for the epoch. See Run method for details about learning error calculation.
Implements AForge.Neuro.Learning.IUnsupervisedLearning.
References AForge.Neuro.Learning.ElasticNetworkLearning.Run().
Run() [3/3]
double AForge.Neuro.Learning.ElasticNetworkLearning.Run (double[] input) inline
Runs learning iteration.
Parameters
input Input vector.
Returns
Returns learning error - summary absolute difference between neurons' weights and appropriate inputs. The difference is measured according to the neurons distance to the winner neuron.
The method runs one learning iterations - finds winner neuron (the neuron which has weights with values closest to the specified input vector) and updates its weight (as well as weights of neighbor neurons) in the way to decrease difference with the specified input vector.
Implements AForge.Neuro.Learning.IUnsupervisedLearning.
References AForge.Neuro.Network.Compute(), AForge.Neuro.Learning.ElasticNetworkLearning.distance, AForge.Neuro.DistanceNetwork.GetWinner(), AForge.Neuro.Network.Layers, AForge.Neuro.Learning.ElasticNetworkLearning.learningRate, AForge.Neuro.Learning.ElasticNetworkLearning.network, AForge.Neuro.Layer.Neurons, AForge.Neuro.Learning.ElasticNetworkLearning.squaredRadius2, and AForge.Neuro.Neuron.Weights.
RunEpoch() [3/3]
double AForge.Neuro.Learning.ElasticNetworkLearning.RunEpoch (double input[][]) inline
Runs learning epoch.
Parameters
input Array of input vectors.
Returns
Returns summary learning error for the epoch. See Run method for details about learning error calculation.
The method runs one learning epoch, by calling Run method for each vector provided in the input array.
Implements AForge.Neuro.Learning.IUnsupervisedLearning.
References AForge.Neuro.Learning.ElasticNetworkLearning.Run().
Member Data Documentation
network
DistanceNetwork AForge.Neuro.Learning.ElasticNetworkLearning.network private
Referenced by AForge.Neuro.Learning.ElasticNetworkLearning.ElasticNetworkLearning(), and AForge.Neuro.Learning.ElasticNetworkLearning.Run().
distance
double [] AForge.Neuro.Learning.ElasticNetworkLearning.distance private
Referenced by AForge.Neuro.Learning.ElasticNetworkLearning.ElasticNetworkLearning(), and AForge.Neuro.Learning.ElasticNetworkLearning.Run().
learningRate
double AForge.Neuro.Learning.ElasticNetworkLearning.learningRate = 0.1 private
Referenced by AForge.Neuro.Learning.ElasticNetworkLearning.Run().
learningRadius
double AForge.Neuro.Learning.ElasticNetworkLearning.learningRadius = 0.5 private
squaredRadius2
double AForge.Neuro.Learning.ElasticNetworkLearning.squaredRadius2 = 2 * 7 * 7 private
Referenced by AForge.Neuro.Learning.ElasticNetworkLearning.Run().
Property Documentation
LearningRate
double AForge.Neuro.Learning.ElasticNetworkLearning.LearningRate get set
Learning rate
Learning rate, [0, 1].
Determines speed of learning. Value range is [0, 1]. Default value equals to 0.1.
Determines speed of learning.
Default value equals to 0.1.
Referenced by TSP.MainForm.SearchSolution().
LearningRadius
double AForge.Neuro.Learning.ElasticNetworkLearning.LearningRadius get set
Learning radius
Learning radius, [0, 1].
Determines the amount of neurons to be updated around winner neuron. Neurons, which are in the circle of specified radius, are updated during the learning procedure. Neurons, which are closer to the winner neuron, get more update.
Default value equals to 0.5.
Determines the amount of neurons to be updated around winner neuron. Neurons, which are in the circle of specified radius, are updated during the learning procedure. Neurons, which are closer to the winner neuron, get more update.
Default value equals to 0.5.
Referenced by TSP.MainForm.SearchSolution().
The documentation for this class was generated from the following file:
shelldev/lib/external/neuralnetworks/neuro_src/Sources/Backup/Neuro/Learning/ElasticNetworkLearning.cs