Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLASD2 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLASD2 Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLASD2 (DLAMCH dlamch, DLAPY2 dlapy2, DCOPY dcopy, DLACPY dlacpy, DLAMRG dlamrg, DLASET dlaset, DROT drot, XERBLA xerbla)
DLASD2 ()
void Run (int NL, int NR, int SQRE, ref int K, ref double[] D, int offset_d, ref double[] Z, int offset_z, double ALPHA, double BETA, ref double[] U, int offset_u, int LDU, ref double[] VT, int offset_vt, int LDVT, ref double[] DSIGMA, int offset_dsigma, ref double[] U2, int offset_u2, int LDU2, ref double[] VT2, int offset_vt2, int LDVT2, ref int[] IDXP, int offset_idxp, ref int[] IDX, int offset_idx, ref int[] IDXC, int offset_idxc, ref int[] IDXQ, int offset_idxq, ref int[] COLTYP, int offset_coltyp, ref int INFO)
Private Attributes
DLAMCH _dlamch
DLAPY2 _dlapy2
DCOPY _dcopy
DLACPY _dlacpy
DLAMRG _dlamrg
DLASET _dlaset
DROT _drot
XERBLA _xerbla
int[] CTOT = new int[4]
int[] PSM = new int[4]
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
const double TWO = 2.0E+0
const double EIGHT = 8.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLASD2 merges the two sets of singular values together into a single sorted set. Then it tries to deflate the size of the problem. There are two ways in which deflation can occur: when two or more singular values are close together or if there is a tiny entry in the Z vector. For each such occurrence the order of the related secular equation problem is reduced by one.
DLASD2 is called from DLASD1.
/summary>
Constructor & Destructor Documentation
DLASD2() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLASD2.DLASD2 (DLAMCH dlamch, DLAPY2 dlapy2, DCOPY dcopy, DLACPY dlacpy, DLAMRG dlamrg, DLASET dlaset, DROT drot, XERBLA xerbla) inline
DLASD2() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLASD2.DLASD2 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLASD2.Run (int NL, int NR, int SQRE, ref int K, ref double[] D, int offset_d, ref double[] Z, int offset_z, double ALPHA, double BETA, ref double[] U, int offset_u, int LDU, ref double[] VT, int offset_vt, int LDVT, ref double[] DSIGMA, int offset_dsigma, ref double[] U2, int offset_u2, int LDU2, ref double[] VT2, int offset_vt2, int LDVT2, ref int[] IDXP, int offset_idxp, ref int[] IDX, int offset_idx, ref int[] IDXC, int offset_idxc, ref int[] IDXQ, int offset_idxq, ref int[] COLTYP, int offset_coltyp, ref int INFO) inline
Purpose
DLASD2 merges the two sets of singular values together into a single sorted set. Then it tries to deflate the size of the problem. There are two ways in which deflation can occur: when two or more singular values are close together or if there is a tiny entry in the Z vector. For each such occurrence the order of the related secular equation problem is reduced by one.
DLASD2 is called from DLASD1.
/summary>
Parameters
NL (input) INTEGER The row dimension of the upper block. NL .GE. 1. /param>
Parameters
NR (input) INTEGER The row dimension of the lower block. NR .GE. 1. /param>
Parameters
SQRE (input) INTEGER = 0: the lower block is an NR-by-NR square matrix. = 1: the lower block is an NR-by-(NR+1) rectangular matrix.
The bidiagonal matrix has N = NL + NR + 1 rows and M = N + SQRE .GE. N columns. /param>
Parameters
K (output) INTEGER Contains the dimension of the non-deflated matrix, This is the order of the related secular equation. 1 .LE. K .LE.N. /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension(N) On entry D contains the singular values of the two submatrices to be combined. On exit D contains the trailing (N-K) updated singular values (those which were deflated) sorted into increasing order. /param>
Parameters
Z (output) DOUBLE PRECISION array, dimension(N) On exit Z contains the updating row vector in the secular equation. /param>
Parameters
ALPHA (input) DOUBLE PRECISION Contains the diagonal element associated with the added row. /param>
Parameters
BETA (input) DOUBLE PRECISION Contains the off-diagonal element associated with the added row. /param>
Parameters
U (input/output) DOUBLE PRECISION array, dimension(LDU,N) On entry U contains the left singular vectors of two submatrices in the two square blocks with corners at (1,1), (NL, NL), and (NL+2, NL+2), (N,N). On exit U contains the trailing (N-K) updated left singular vectors (those which were deflated) in its last N-K columns. /param>
Parameters
LDU (input) INTEGER The leading dimension of the array U. LDU .GE. N. /param>
Parameters
VT (input/output) DOUBLE PRECISION array, dimension(LDVT,M) On entry VT' contains the right singular vectors of two submatrices in the two square blocks with corners at (1,1), (NL+1, NL+1), and (NL+2, NL+2), (M,M). On exit VT' contains the trailing (N-K) updated right singular vectors (those which were deflated) in its last N-K columns. In case SQRE =1, the last row of VT spans the right null space. /param>
Parameters
LDVT (input) INTEGER The leading dimension of the array VT. LDVT .GE. M. /param>
Parameters
DSIGMA (output) DOUBLE PRECISION array, dimension (N) Contains a copy of the diagonal elements (K-1 singular values and one zero) in the secular equation. /param>
Parameters
U2 (output) DOUBLE PRECISION array, dimension(LDU2,N) Contains a copy of the first K-1 left singular vectors which will be used by DLASD3 in a matrix multiply (DGEMM) to solve for the new left singular vectors. U2 is arranged into four blocks. The first block contains a column with 1 at NL+1 and zero everywhere else; the second block contains non-zero entries only at and above NL; the third contains non-zero entries only below NL+1; and the fourth is dense. /param>
Parameters
LDU2 (input) INTEGER The leading dimension of the array U2. LDU2 .GE. N. /param>
Parameters
VT2 (output) DOUBLE PRECISION array, dimension(LDVT2,N) VT2' contains a copy of the first K right singular vectors which will be used by DLASD3 in a matrix multiply (DGEMM) to solve for the new right singular vectors. VT2 is arranged into three blocks. The first block contains a row that corresponds to the special 0 diagonal element in SIGMA; the second block contains non-zeros only at and before NL +1; the third block contains non-zeros only at and after NL +2. /param>
Parameters
LDVT2 (input) INTEGER The leading dimension of the array VT2. LDVT2 .GE. M. /param>
Parameters
IDXP (workspace) INTEGER array dimension(N) This will contain the permutation used to place deflated values of D at the end of the array. On output IDXP(2:K) points to the nondeflated D-values and IDXP(K+1:N) points to the deflated singular values. /param>
Parameters
IDX (workspace) INTEGER array dimension(N) This will contain the permutation used to sort the contents of D into ascending order. /param>
Parameters
IDXC (output) INTEGER array dimension(N) This will contain the permutation used to arrange the columns of the deflated U matrix into three groups: the first group contains non-zero entries only at and above NL, the second contains non-zero entries only below NL+2, and the third is dense. /param>
Parameters
IDXQ (input/output) INTEGER array dimension(N) This contains the permutation which separately sorts the two sub-problems in D into ascending order. Note that entries in the first hlaf of this permutation must first be moved one position backward; and entries in the second half must first have NL+1 added to their values. /param>
Parameters
COLTYP (workspace/output) INTEGER array dimension(N) As workspace, this will contain a label which will indicate which of the following types a column in the U2 matrix or a row in the VT2 matrix is: 1 : non-zero in the upper half only 2 : non-zero in the lower half only 3 : dense 4 : deflated
On exit, it is an array of dimension 4, with COLTYP(I) being the dimension of the I-th type columns. /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLASD2.CTOT, DotNumerics.LinearAlgebra.CSLapack.DLASD2.EIGHT, DotNumerics.LinearAlgebra.CSLapack.DLASD2.ONE, DotNumerics.LinearAlgebra.CSLapack.DLASD2.PSM, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DROT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAPY2.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMRG.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASET.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD2.TWO, and DotNumerics.LinearAlgebra.CSLapack.DLASD2.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD1.Run().
Member Data Documentation
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLASD2._dlamch private
_dlapy2
DLAPY2 DotNumerics.LinearAlgebra.CSLapack.DLASD2._dlapy2 private
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLASD2._dcopy private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DLASD2._dlacpy private
_dlamrg
DLAMRG DotNumerics.LinearAlgebra.CSLapack.DLASD2._dlamrg private
_dlaset
DLASET DotNumerics.LinearAlgebra.CSLapack.DLASD2._dlaset private
_drot
DROT DotNumerics.LinearAlgebra.CSLapack.DLASD2._drot private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLASD2._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLASD2.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD2.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLASD2.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD2.Run().
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DLASD2.TWO = 2.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD2.Run().
EIGHT
const double DotNumerics.LinearAlgebra.CSLapack.DLASD2.EIGHT = 8.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD2.Run().
CTOT
int [] DotNumerics.LinearAlgebra.CSLapack.DLASD2.CTOT = new int[4] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD2.Run().
PSM
int [] DotNumerics.LinearAlgebra.CSLapack.DLASD2.PSM = new int[4] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD2.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlasd2.cs