Doc: IGLib EXTENDED: Test.OrthogonalPolynomialsTest Class Reference
Test.OrthogonalPolynomialsTest Class Reference
Public Member Functions
void HermiteSpecialCases ()
void HermiteReflection ()
void HermiteRecurrence ()
void HermiteAddition ()
void HermiteSum ()
void HermiteOrthonormality ()
void HermiteInvalidOrder ()
void LaguerreSpecialCases ()
void LaguerreRecurrence ()
void LaguerreInequality ()
void LaguerreInvalidOrder ()
void LaguerreInvalidArgument ()
void LaguerreOrthonormality ()
void AssociatedLaguerreSpecialCases ()
void AssociatedLaguerreAlphaRecurrence ()
void AssociatedLaguerreSum ()
void AssociatedLaguerreOrthonormality ()
void ChebyshevSpecialCases ()
void ChebyshevInequality ()
void ChebyshevRecurrence ()
void ChebyshevReflection ()
void ChebyshevDoubling ()
void ChebyshevMultiplication ()
void ChebyshevCosine ()
void ChebyshevInvalidArgument ()
void LegendreSpecialCases ()
void LegendreInequality ()
void LegendreTuronInequality ()
void LegendreRecurrence ()
void LegendreReflection ()
void LegendreNegativeOrder ()
void LegendreInvalidArgument ()
void LegendreOrthonormality ()
void SphericalHarmonicSpecialCases ()
void SphericalHarmonicLegendre ()
void SphericalHarmonicConjugation ()
void SphericalHarmonicNormalization ()
void SphericalHarmonicAddition ()
void SphericalHarmonicLowOrders ()
void ZernikeSpecialCases ()
void ZernikeOrthonormality ()
void ZernikeBessel ()
void AssociatedLegendreLowOrders ()
void AssociatedLegendreAgreement ()
void AssociatedLegendreRecurrenceL ()
void AssociatedLegendreRecurrenceM ()
void AssociatedLegendreOrthonormalityL ()
Properties
TestContext TestContext [get, set]
Private Member Functions
double[] GenerateRandomAngles (double lower, double upper, int n)
Private Attributes
TestContext testContextInstance
int[] orders = new int[] { 3, 4, 33, 44, 333, 444 }
double[] aArguments = new double[] { 0.00011, 0.11, 1.1, 11.1, 111.1, 1111.1 }
double[] bArguments = new double[] { 0.00001, 0.02, 0.34, 0.56, 0.78, 0.99999 }
Member Function Documentation
HermiteSpecialCases()
void Test.OrthogonalPolynomialsTest.HermiteSpecialCases () inline
References Test.OrthogonalPolynomialsTest.aArguments, Meta.Numerics.Functions.AdvancedIntegerMath.Factorial(), Meta.Numerics.Functions.OrthogonalPolynomials.HermiteH(), and Test.OrthogonalPolynomialsTest.orders.
HermiteReflection()
void Test.OrthogonalPolynomialsTest.HermiteReflection () inline
References Meta.Numerics.Functions.OrthogonalPolynomials.HermiteH().
HermiteRecurrence()
void Test.OrthogonalPolynomialsTest.HermiteRecurrence () inline
References Meta.Numerics.Functions.OrthogonalPolynomials.HermiteH().
HermiteAddition()
void Test.OrthogonalPolynomialsTest.HermiteAddition () inline
References Test.OrthogonalPolynomialsTest.aArguments, Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficient(), Meta.Numerics.Functions.OrthogonalPolynomials.HermiteH(), and Test.OrthogonalPolynomialsTest.orders.
HermiteSum()
void Test.OrthogonalPolynomialsTest.HermiteSum () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficient(), Meta.Numerics.Functions.AdvancedIntegerMath.Factorial(), and Meta.Numerics.Functions.OrthogonalPolynomials.HermiteH().
HermiteOrthonormality()
void Test.OrthogonalPolynomialsTest.HermiteOrthonormality () inline
References Meta.Numerics.Functions.AdvancedIntegerMath.Factorial(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Functions.OrthogonalPolynomials.HermiteH(), and Meta.Numerics.Analysis.FunctionMath.Integrate().
HermiteInvalidOrder()
void Test.OrthogonalPolynomialsTest.HermiteInvalidOrder () inline
References Meta.Numerics.Functions.OrthogonalPolynomials.HermiteH().
LaguerreSpecialCases()
void Test.OrthogonalPolynomialsTest.LaguerreSpecialCases () inline
References Meta.Numerics.Functions.OrthogonalPolynomials.LaguerreL().
LaguerreRecurrence()
void Test.OrthogonalPolynomialsTest.LaguerreRecurrence () inline
References Meta.Numerics.Functions.OrthogonalPolynomials.LaguerreL().
LaguerreInequality()
void Test.OrthogonalPolynomialsTest.LaguerreInequality () inline
References Meta.Numerics.Functions.OrthogonalPolynomials.LaguerreL().
LaguerreInvalidOrder()
void Test.OrthogonalPolynomialsTest.LaguerreInvalidOrder () inline
References Meta.Numerics.Functions.OrthogonalPolynomials.LaguerreL().
LaguerreInvalidArgument()
void Test.OrthogonalPolynomialsTest.LaguerreInvalidArgument () inline
References Meta.Numerics.Functions.OrthogonalPolynomials.LaguerreL().
LaguerreOrthonormality()
void Test.OrthogonalPolynomialsTest.LaguerreOrthonormality () inline
References Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.FunctionMath.Integrate(), Meta.Numerics.Functions.OrthogonalPolynomials.LaguerreL(), and Test.OrthogonalPolynomialsTest.orders.
AssociatedLaguerreSpecialCases()
void Test.OrthogonalPolynomialsTest.AssociatedLaguerreSpecialCases () inline
References Meta.Numerics.Functions.OrthogonalPolynomials.LaguerreL().
AssociatedLaguerreAlphaRecurrence()
void Test.OrthogonalPolynomialsTest.AssociatedLaguerreAlphaRecurrence () inline
References Meta.Numerics.Functions.OrthogonalPolynomials.LaguerreL().
AssociatedLaguerreSum()
void Test.OrthogonalPolynomialsTest.AssociatedLaguerreSum () inline
References Meta.Numerics.Functions.OrthogonalPolynomials.LaguerreL().
AssociatedLaguerreOrthonormality()
void Test.OrthogonalPolynomialsTest.AssociatedLaguerreOrthonormality () inline
References Meta.Numerics.Analysis.EvaluationSettings.AbsolutePrecision, Meta.Numerics.Functions.AdvancedIntegerMath.Factorial(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Functions.AdvancedMath.Gamma(), Meta.Numerics.Analysis.FunctionMath.Integrate(), Meta.Numerics.Functions.OrthogonalPolynomials.LaguerreL(), and Meta.Numerics.Analysis.EvaluationSettings.RelativePrecision.
ChebyshevSpecialCases()
void Test.OrthogonalPolynomialsTest.ChebyshevSpecialCases () inline
References Test.OrthogonalPolynomialsTest.bArguments, Meta.Numerics.Functions.OrthogonalPolynomials.ChebyshevT(), and Test.OrthogonalPolynomialsTest.orders.
ChebyshevInequality()
void Test.OrthogonalPolynomialsTest.ChebyshevInequality () inline
References Test.OrthogonalPolynomialsTest.bArguments, Meta.Numerics.Functions.OrthogonalPolynomials.ChebyshevT(), and Test.OrthogonalPolynomialsTest.orders.
ChebyshevRecurrence()
void Test.OrthogonalPolynomialsTest.ChebyshevRecurrence () inline
References Test.OrthogonalPolynomialsTest.bArguments, Meta.Numerics.Functions.OrthogonalPolynomials.ChebyshevT(), and Test.OrthogonalPolynomialsTest.orders.
ChebyshevReflection()
void Test.OrthogonalPolynomialsTest.ChebyshevReflection () inline
References Test.OrthogonalPolynomialsTest.bArguments, Meta.Numerics.Functions.OrthogonalPolynomials.ChebyshevT(), and Test.OrthogonalPolynomialsTest.orders.
ChebyshevDoubling()
void Test.OrthogonalPolynomialsTest.ChebyshevDoubling () inline
References Test.OrthogonalPolynomialsTest.bArguments, and Meta.Numerics.Functions.OrthogonalPolynomials.ChebyshevT().
ChebyshevMultiplication()
void Test.OrthogonalPolynomialsTest.ChebyshevMultiplication () inline
References Test.OrthogonalPolynomialsTest.bArguments, Meta.Numerics.Functions.OrthogonalPolynomials.ChebyshevT(), and Test.OrthogonalPolynomialsTest.orders.
ChebyshevCosine()
void Test.OrthogonalPolynomialsTest.ChebyshevCosine () inline
References Meta.Numerics.Functions.OrthogonalPolynomials.ChebyshevT(), and Test.OrthogonalPolynomialsTest.GenerateRandomAngles().
ChebyshevInvalidArgument()
void Test.OrthogonalPolynomialsTest.ChebyshevInvalidArgument () inline
References Meta.Numerics.Functions.OrthogonalPolynomials.ChebyshevT().
LegendreSpecialCases()
void Test.OrthogonalPolynomialsTest.LegendreSpecialCases () inline
References Test.OrthogonalPolynomialsTest.bArguments, Meta.Numerics.Functions.OrthogonalPolynomials.LegendreP(), and Test.OrthogonalPolynomialsTest.orders.
LegendreInequality()
void Test.OrthogonalPolynomialsTest.LegendreInequality () inline
References Test.OrthogonalPolynomialsTest.bArguments, Meta.Numerics.Functions.OrthogonalPolynomials.LegendreP(), and Test.OrthogonalPolynomialsTest.orders.
LegendreTuronInequality()
void Test.OrthogonalPolynomialsTest.LegendreTuronInequality () inline
References Test.OrthogonalPolynomialsTest.bArguments, Meta.Numerics.Functions.OrthogonalPolynomials.LegendreP(), Test.OrthogonalPolynomialsTest.orders, and Meta.Numerics.MoreMath.Pow().
LegendreRecurrence()
void Test.OrthogonalPolynomialsTest.LegendreRecurrence () inline
References Test.OrthogonalPolynomialsTest.bArguments, Meta.Numerics.Functions.OrthogonalPolynomials.LegendreP(), and Test.OrthogonalPolynomialsTest.orders.
LegendreReflection()
void Test.OrthogonalPolynomialsTest.LegendreReflection () inline
References Test.OrthogonalPolynomialsTest.bArguments, Meta.Numerics.Functions.OrthogonalPolynomials.LegendreP(), and Test.OrthogonalPolynomialsTest.orders.
LegendreNegativeOrder()
void Test.OrthogonalPolynomialsTest.LegendreNegativeOrder () inline
References Test.OrthogonalPolynomialsTest.bArguments, Meta.Numerics.Functions.OrthogonalPolynomials.LegendreP(), and Test.OrthogonalPolynomialsTest.orders.
LegendreInvalidArgument()
void Test.OrthogonalPolynomialsTest.LegendreInvalidArgument () inline
References Meta.Numerics.Functions.OrthogonalPolynomials.LegendreP().
LegendreOrthonormality()
void Test.OrthogonalPolynomialsTest.LegendreOrthonormality () inline
References Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.FunctionMath.Integrate(), and Meta.Numerics.Functions.OrthogonalPolynomials.LegendreP().
GenerateRandomAngles()
double [] Test.OrthogonalPolynomialsTest.GenerateRandomAngles (double lower, double upper, int n) inline private
Referenced by Test.OrthogonalPolynomialsTest.ChebyshevCosine(), Test.OrthogonalPolynomialsTest.SphericalHarmonicAddition(), Test.OrthogonalPolynomialsTest.SphericalHarmonicConjugation(), Test.OrthogonalPolynomialsTest.SphericalHarmonicLegendre(), Test.OrthogonalPolynomialsTest.SphericalHarmonicLowOrders(), Test.OrthogonalPolynomialsTest.SphericalHarmonicNormalization(), and Test.OrthogonalPolynomialsTest.SphericalHarmonicSpecialCases().
SphericalHarmonicSpecialCases()
void Test.OrthogonalPolynomialsTest.SphericalHarmonicSpecialCases () inline
References Test.OrthogonalPolynomialsTest.GenerateRandomAngles(), and Meta.Numerics.Functions.AdvancedMath.SphericalHarmonic().
SphericalHarmonicLegendre()
void Test.OrthogonalPolynomialsTest.SphericalHarmonicLegendre () inline
References Test.OrthogonalPolynomialsTest.GenerateRandomAngles(), Meta.Numerics.Functions.OrthogonalPolynomials.LegendreP(), and Meta.Numerics.Functions.AdvancedMath.SphericalHarmonic().
SphericalHarmonicConjugation()
void Test.OrthogonalPolynomialsTest.SphericalHarmonicConjugation () inline
References Meta.Numerics.Complex.Conjugate, Test.OrthogonalPolynomialsTest.GenerateRandomAngles(), and Meta.Numerics.Functions.AdvancedMath.SphericalHarmonic().
SphericalHarmonicNormalization()
void Test.OrthogonalPolynomialsTest.SphericalHarmonicNormalization () inline
References Test.OrthogonalPolynomialsTest.GenerateRandomAngles(), and Meta.Numerics.Functions.AdvancedMath.SphericalHarmonic().
SphericalHarmonicAddition()
void Test.OrthogonalPolynomialsTest.SphericalHarmonicAddition () inline
References Meta.Numerics.Complex.Conjugate, Test.OrthogonalPolynomialsTest.GenerateRandomAngles(), Meta.Numerics.Functions.OrthogonalPolynomials.LegendreP(), and Meta.Numerics.Functions.AdvancedMath.SphericalHarmonic().
SphericalHarmonicLowOrders()
void Test.OrthogonalPolynomialsTest.SphericalHarmonicLowOrders () inline
References Test.OrthogonalPolynomialsTest.GenerateRandomAngles(), and Meta.Numerics.Functions.AdvancedMath.SphericalHarmonic().
ZernikeSpecialCases()
void Test.OrthogonalPolynomialsTest.ZernikeSpecialCases () inline
References Meta.Numerics.Functions.OrthogonalPolynomials.ZernikeR().
ZernikeOrthonormality()
void Test.OrthogonalPolynomialsTest.ZernikeOrthonormality () inline
References Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.FunctionMath.Integrate(), and Meta.Numerics.Functions.OrthogonalPolynomials.ZernikeR().
ZernikeBessel()
void Test.OrthogonalPolynomialsTest.ZernikeBessel () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.FunctionMath.Integrate(), and Meta.Numerics.Functions.OrthogonalPolynomials.ZernikeR().
AssociatedLegendreLowOrders()
void Test.OrthogonalPolynomialsTest.AssociatedLegendreLowOrders () inline
References Meta.Numerics.Functions.OrthogonalPolynomials.LegendreP().
AssociatedLegendreAgreement()
void Test.OrthogonalPolynomialsTest.AssociatedLegendreAgreement () inline
References Meta.Numerics.Functions.OrthogonalPolynomials.LegendreP().
AssociatedLegendreRecurrenceL()
void Test.OrthogonalPolynomialsTest.AssociatedLegendreRecurrenceL () inline
References Meta.Numerics.Functions.OrthogonalPolynomials.LegendreP().
AssociatedLegendreRecurrenceM()
void Test.OrthogonalPolynomialsTest.AssociatedLegendreRecurrenceM () inline
References Meta.Numerics.Functions.OrthogonalPolynomials.LegendreP().
AssociatedLegendreOrthonormalityL()
void Test.OrthogonalPolynomialsTest.AssociatedLegendreOrthonormalityL () inline
References Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.FunctionMath.Integrate(), Meta.Numerics.Functions.OrthogonalPolynomials.LegendreP(), and Meta.Numerics.Functions.AdvancedIntegerMath.LogFactorial().
Member Data Documentation
testContextInstance
TestContext Test.OrthogonalPolynomialsTest.testContextInstance private
orders
int [] Test.OrthogonalPolynomialsTest.orders = new int[] { 3, 4, 33, 44, 333, 444 } private
Referenced by Test.OrthogonalPolynomialsTest.ChebyshevInequality(), Test.OrthogonalPolynomialsTest.ChebyshevMultiplication(), Test.OrthogonalPolynomialsTest.ChebyshevRecurrence(), Test.OrthogonalPolynomialsTest.ChebyshevReflection(), Test.OrthogonalPolynomialsTest.ChebyshevSpecialCases(), Test.OrthogonalPolynomialsTest.HermiteAddition(), Test.OrthogonalPolynomialsTest.HermiteSpecialCases(), Test.OrthogonalPolynomialsTest.LaguerreOrthonormality(), Test.OrthogonalPolynomialsTest.LegendreInequality(), Test.OrthogonalPolynomialsTest.LegendreNegativeOrder(), Test.OrthogonalPolynomialsTest.LegendreRecurrence(), Test.OrthogonalPolynomialsTest.LegendreReflection(), Test.OrthogonalPolynomialsTest.LegendreSpecialCases(), and Test.OrthogonalPolynomialsTest.LegendreTuronInequality().
aArguments
double [] Test.OrthogonalPolynomialsTest.aArguments = new double[] { 0.00011, 0.11, 1.1, 11.1, 111.1, 1111.1 } private
Referenced by Test.OrthogonalPolynomialsTest.HermiteAddition(), and Test.OrthogonalPolynomialsTest.HermiteSpecialCases().
bArguments
double [] Test.OrthogonalPolynomialsTest.bArguments = new double[] { 0.00001, 0.02, 0.34, 0.56, 0.78, 0.99999 } private
Referenced by Test.OrthogonalPolynomialsTest.ChebyshevDoubling(), Test.OrthogonalPolynomialsTest.ChebyshevInequality(), Test.OrthogonalPolynomialsTest.ChebyshevMultiplication(), Test.OrthogonalPolynomialsTest.ChebyshevRecurrence(), Test.OrthogonalPolynomialsTest.ChebyshevReflection(), Test.OrthogonalPolynomialsTest.ChebyshevSpecialCases(), Test.OrthogonalPolynomialsTest.LegendreInequality(), Test.OrthogonalPolynomialsTest.LegendreNegativeOrder(), Test.OrthogonalPolynomialsTest.LegendreRecurrence(), Test.OrthogonalPolynomialsTest.LegendreReflection(), Test.OrthogonalPolynomialsTest.LegendreSpecialCases(), and Test.OrthogonalPolynomialsTest.LegendreTuronInequality().
Property Documentation
TestContext
TestContext Test.OrthogonalPolynomialsTest.TestContext get set
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/OrthogonalPolynomialsTest.cs