Doc: IGLib EXTENDED: AForge.Robotics.TeRK.Qwerk.Servos Class Reference
AForge.Robotics.TeRK.Qwerk.Servos Class Reference
Provides access to Qwerk's servos' controllers.
Public Member Functions
Servos (Qwerk qwerk)
Initializes a new instance of the Qwerk.Servos class.
int StopServo (int servo)
Stop specified servo.
int[] StopServos ()
Stop all servos.
int[] StopServos (bool[] mask)
Stop specified servos.
int SetPosition (int servo, int position)
Set position of a single servo.
int[] SetPositions (bool[] mask, int[] positions)
Set positions of specified servos.
int GetPosition (int servo)
Get current position of a single servo.
int[] GetPositions ()
Get current positions of all servos.
void SetBound (int servo, IntRange bound)
Set bounds for the specified servo.
void SetBounds (bool[] mask, IntRange[] bounds)
Set bounds for specified servos.
IntRange GetBound (int servo)
Get bounds for the specified servo.
IntRange[] GetBounds ()
Get bounds of all servos.
Static Public Attributes
const int Count = 16
Number of available servos' controllers, 16.
Private Member Functions
TeRKIceLib.ServoCommand CreateCommand ()
Private Attributes
TeRKIceLib.ServoControllerPrx servoController = null
Static Private Attributes
const int DefaultSpeed = 1000
Detailed Description
Provides access to Qwerk's servos' controllers.
The class allows to manipulate Qwerk's servos. The total number of available servos equals to Servos.Count.
Each servo has logical and physical positions, which may or may not be equal. Both positions may vary in the [0, 255] range. Physical and logical positions are equal, when servo's physical moving bound (range) is set to [0, 255] (see SetBound). In this case setting servo's logical position with SetPosition method results in servo's physical moving in the [0, 255] range. However, of physical bound is set to [10, 20], for example, then physically the servo will move only in this range. But logical position is still may be set in [0, 255] range, which is mapped to physical range.
Sample usage:
// get Qwerk's servos service
Qwerk.Servos servos = qwerk.GetServosService();
// stop all servos
servos.StopServos();
// set 0th servo's bounds
servos.SetBound(0, new IntRange(10, 100));
// set servo's position
servos.SetPosition(0, 50);
// ...
// get 0th servo's position
int currentPosition = servos.GetPosition(0);
Constructor & Destructor Documentation
Servos()
AForge.Robotics.TeRK.Qwerk.Servos.Servos (Qwerk qwerk) inline
Initializes a new instance of the Qwerk.Servos class.
Parameters
qwerk Reference to Qwerk object, which is connected to Qwerk board.
Exceptions
NotConnectedException The passed reference to Qwerk object is not connected to Qwerk board.
ConnectionFailedException Failed connecting to the requested service.
ServiceAccessFailedException Failed accessing to the requested service.
References AForge.Robotics.TeRK.Qwerk.hostAddress, AForge.Robotics.TeRK.Qwerk.qwerk, and AForge.Robotics.TeRK.Qwerk.Servos.servoController.
Member Function Documentation
StopServo()
int AForge.Robotics.TeRK.Qwerk.Servos.StopServo (int servo) inline
Stop specified servo.
Parameters
servo Servo to stop, [0, Servos.Count).
Returns
Returns current position of the specified servo.
Exceptions
ArgumentOutOfRangeException Invalid servo is specified.
NotConnectedException No connection to Qwerk or its service.
ConnectionLostException Connestion to Qwerk is lost.
References AForge.Robotics.TeRK.Qwerk.Servos.Count, and AForge.Robotics.TeRK.Qwerk.Servos.StopServos().
StopServos() [1/2]
int [] AForge.Robotics.TeRK.Qwerk.Servos.StopServos () inline
Stop all servos.
Returns
Returns array of current servos' positions.
Exceptions
NotConnectedException No connection to Qwerk or its service.
ConnectionLostException Connestion to Qwerk is lost.
References AForge.Robotics.TeRK.Qwerk.Servos.Count.
Referenced by AForge.Robotics.TeRK.Qwerk.Servos.StopServo().
StopServos() [2/2]
int [] AForge.Robotics.TeRK.Qwerk.Servos.StopServos (bool[] mask) inline
Stop specified servos.
Parameters
mask Mask array specifying which servos need to stop.
Returns
Returns array of current servos' positions.
The mask array specifies which Qwerk's servo need to be stopped. If value of the mask array is set to true, then corresponding servo is stopped.
Exceptions
ArgumentException Incorrect length of mask array.
NotConnectedException No connection to Qwerk or its service.
ConnectionLostException Connestion to Qwerk is lost.
References AForge.Robotics.TeRK.Qwerk.Servos.Count, AForge.Robotics.TeRK.Qwerk.Servos.CreateCommand(), and AForge.Robotics.TeRK.Qwerk.Servos.servoController.
SetPosition()
int AForge.Robotics.TeRK.Qwerk.Servos.SetPosition (int servo, int position) inline
Set position of a single servo.
Parameters
servo Servo to set position for, [0, Servos.Count).
position Position to set for the specified servo, [0, 255].
Returns
Returns current position of the specified servo.
The method sets position of single Qwerk's servo, which index is specified. It is preferred to use SetPositions for setting positions of multiple servos, which does it at once.
Exceptions
ArgumentOutOfRangeException Invalid servo is specified.
NotConnectedException No connection to Qwerk or its service.
ConnectionLostException Connestion to Qwerk is lost.
References AForge.Robotics.TeRK.Qwerk.Servos.Count, and AForge.Robotics.TeRK.Qwerk.Servos.SetPositions().
SetPositions()
int [] AForge.Robotics.TeRK.Qwerk.Servos.SetPositions (bool[] mask, int[] positions) inline
Set positions of specified servos.
Parameters
mask Mask array specifying which servos need to be set.
positions Array of servos' positions to set. Each position is in [0, 255] range.
Returns
Returns array of current servos' positions.
The mask and positions arrays specify which Qwerk's servo's state should be updated. If value of the mask array is set to true, then corresponding servo's state is changed to the state, which is specified in positions array.
Exceptions
ArgumentException Incorrect length of mask or positions array.
NotConnectedException No connection to Qwerk or its service.
ConnectionLostException Connestion to Qwerk is lost.
References AForge.Robotics.TeRK.Qwerk.Servos.Count, AForge.Robotics.TeRK.Qwerk.Servos.CreateCommand(), AForge.Robotics.TeRK.Qwerk.Servos.DefaultSpeed, and AForge.Robotics.TeRK.Qwerk.Servos.servoController.
Referenced by AForge.Robotics.TeRK.Qwerk.Servos.GetPositions(), and AForge.Robotics.TeRK.Qwerk.Servos.SetPosition().
GetPosition()
int AForge.Robotics.TeRK.Qwerk.Servos.GetPosition (int servo) inline
Get current position of a single servo.
Parameters
servo Servo to get position for, [0, Servos.Count).
Returns
Returns current position of the specified servo.
Exceptions
ArgumentOutOfRangeException Invalid servo is specified.
NotConnectedException No connection to Qwerk or its service.
ConnectionLostException Connestion to Qwerk is lost.
References AForge.Robotics.TeRK.Qwerk.Servos.Count, and AForge.Robotics.TeRK.Qwerk.Servos.GetPositions().
GetPositions()
int [] AForge.Robotics.TeRK.Qwerk.Servos.GetPositions () inline
Get current positions of all servos.
Returns
Returns array of current servos' positions.
Exceptions
NotConnectedException No connection to Qwerk or its service.
ConnectionLostException Connestion to Qwerk is lost.
References AForge.Robotics.TeRK.Qwerk.Servos.Count, and AForge.Robotics.TeRK.Qwerk.Servos.SetPositions().
Referenced by AForge.Robotics.TeRK.Qwerk.Servos.GetPosition().
SetBound()
void AForge.Robotics.TeRK.Qwerk.Servos.SetBound (int servo, IntRange bound) inline
Set bounds for the specified servo.
Parameters
servo Servo to set bounds for, [0, Servos.Count).
bound Bounds to set for the specified servo.
The method sets servo's physical bounds in which it may move. See documentation to Qwerk.Servos for clarification.
Exceptions
ArgumentOutOfRangeException Invalid servo is specified.
NotConnectedException No connection to Qwerk or its service.
ConnectionLostException Connestion to Qwerk is lost.
References AForge.Robotics.TeRK.Qwerk.Servos.Count, and AForge.Robotics.TeRK.Qwerk.Servos.SetBounds().
SetBounds()
void AForge.Robotics.TeRK.Qwerk.Servos.SetBounds (bool[] mask, IntRange[] bounds) inline
Set bounds for specified servos.
Parameters
mask Mask array specifying which servos need to be set.
bounds Array of servos' bounds. Each bound may be in [0, 255] range.
The method sets servos' physical bounds in which they may move. See documentation to Qwerk.Servos for clarification.
Exceptions
ArgumentException Incorrect length of mask , or bounds array.
NotConnectedException No connection to Qwerk or its service.
ConnectionLostException Connestion to Qwerk is lost.
References AForge.Robotics.TeRK.Qwerk.Servos.Count, AForge.IntRange.Length, AForge.IntRange.Max, AForge.IntRange.Min, and AForge.Robotics.TeRK.Qwerk.Servos.servoController.
Referenced by AForge.Robotics.TeRK.Qwerk.Servos.SetBound().
GetBound()
IntRange AForge.Robotics.TeRK.Qwerk.Servos.GetBound (int servo) inline
Get bounds for the specified servo.
Parameters
servo Servo to get bounds for, [0, Servos.Count).
Returns
Returns configured bounds of the specified servo.
Exceptions
ArgumentOutOfRangeException Invalid servo is specified.
NotConnectedException No connection to Qwerk or its service.
ConnectionLostException Connestion to Qwerk is lost.
References AForge.Robotics.TeRK.Qwerk.Servos.Count, and AForge.Robotics.TeRK.Qwerk.Servos.GetBounds().
GetBounds()
IntRange [] AForge.Robotics.TeRK.Qwerk.Servos.GetBounds () inline
Get bounds of all servos.
Returns
Returns array of configured servos' bounds.
Exceptions
NotConnectedException No connection to Qwerk or its service.
ConnectionLostException Connestion to Qwerk is lost.
References AForge.Robotics.TeRK.Qwerk.Servos.Count, and AForge.Robotics.TeRK.Qwerk.Servos.servoController.
Referenced by AForge.Robotics.TeRK.Qwerk.Servos.GetBound().
CreateCommand()
TeRKIceLib.ServoCommand AForge.Robotics.TeRK.Qwerk.Servos.CreateCommand () inline private
References AForge.Robotics.TeRK.Qwerk.Servos.Count.
Referenced by AForge.Robotics.TeRK.Qwerk.Servos.SetPositions(), and AForge.Robotics.TeRK.Qwerk.Servos.StopServos().
Member Data Documentation
servoController
TeRKIceLib.ServoControllerPrx AForge.Robotics.TeRK.Qwerk.Servos.servoController = null private
Referenced by AForge.Robotics.TeRK.Qwerk.Servos.GetBounds(), AForge.Robotics.TeRK.Qwerk.Servos.Servos(), AForge.Robotics.TeRK.Qwerk.Servos.SetBounds(), AForge.Robotics.TeRK.Qwerk.Servos.SetPositions(), and AForge.Robotics.TeRK.Qwerk.Servos.StopServos().
Count
const int AForge.Robotics.TeRK.Qwerk.Servos.Count = 16 static
Number of available servos' controllers, 16.
Referenced by AForge.Robotics.TeRK.Qwerk.Servos.CreateCommand(), AForge.Robotics.TeRK.Qwerk.Servos.GetBound(), AForge.Robotics.TeRK.Qwerk.Servos.GetBounds(), AForge.Robotics.TeRK.Qwerk.Servos.GetPosition(), AForge.Robotics.TeRK.Qwerk.Servos.GetPositions(), AForge.Robotics.TeRK.Qwerk.Servos.SetBound(), AForge.Robotics.TeRK.Qwerk.Servos.SetBounds(), AForge.Robotics.TeRK.Qwerk.Servos.SetPosition(), AForge.Robotics.TeRK.Qwerk.Servos.SetPositions(), AForge.Robotics.TeRK.Qwerk.Servos.StopServo(), and AForge.Robotics.TeRK.Qwerk.Servos.StopServos().
DefaultSpeed
const int AForge.Robotics.TeRK.Qwerk.Servos.DefaultSpeed = 1000 static private
Referenced by AForge.Robotics.TeRK.Qwerk.Servos.SetPositions().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Robotics.TeRK/Qwerk.Servos.cs