Doc: IGLib EXTENDED: IG.Forms.ScalarFunctionScriptForm Class Reference
IG.Forms.ScalarFunctionScriptForm Class Reference
Window for definition of scalar functions by user defined expressions (through script loader).
Public Member Functions
ScalarFunctionScriptForm ()
ScalarFunctionScriptForm ()
ScalarFunctionScriptForm ()
ScalarFunctionScriptForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
IG.Forms.ScalarFunctionScriptControl scalarFunctionScriptControl1 = null
Detailed Description
Window for definition of scalar functions by user defined expressions (through script loader).
$A Igor Jun14;
Constructor & Destructor Documentation
ScalarFunctionScriptForm() [1/4]
IG.Forms.ScalarFunctionScriptForm.ScalarFunctionScriptForm () inline
References IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, IG.Forms.ScalarFunctionScriptForm.InitializeComponent(), and IG.Forms.ScalarFunctionScriptForm.scalarFunctionScriptControl1.
ScalarFunctionScriptForm() [2/4]
IG.Forms.ScalarFunctionScriptForm.ScalarFunctionScriptForm () inline
References IG.Forms.ScalarFunctionScriptForm.InitializeComponent().
ScalarFunctionScriptForm() [3/4]
IG.Forms.ScalarFunctionScriptForm.ScalarFunctionScriptForm () inline
References IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, IG.Forms.ScalarFunctionScriptForm.InitializeComponent(), and IG.Forms.ScalarFunctionScriptForm.scalarFunctionScriptControl1.
ScalarFunctionScriptForm() [4/4]
IG.Forms.ScalarFunctionScriptForm.ScalarFunctionScriptForm () inline
References IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, IG.Forms.ScalarFunctionScriptForm.InitializeComponent(), and IG.Forms.ScalarFunctionScriptForm.scalarFunctionScriptControl1.
Member Function Documentation
Dispose() [1/4]
override void IG.Forms.ScalarFunctionScriptForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ScalarFunctionScriptForm.components.
InitializeComponent() [1/4]
void IG.Forms.ScalarFunctionScriptForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ScalarFunctionScriptControl.Dimension, IG.Forms.ScalarFunctionScriptControl.FunctionDescription, IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Forms.ScalarFunctionScriptControl.ParameterNames, IG.Forms.ScalarFunctionScriptForm.scalarFunctionScriptControl1, and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
Referenced by IG.Forms.ScalarFunctionScriptForm.ScalarFunctionScriptForm().
Dispose() [2/4]
override void IG.Forms.ScalarFunctionScriptForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ScalarFunctionScriptForm.components.
InitializeComponent() [2/4]
void IG.Forms.ScalarFunctionScriptForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ScalarFunctionScriptControl.Dimension, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.FunctionDescription, IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Forms.ScalarFunctionScriptControl.ParameterNames, IG.Forms.ScalarFunctionScriptForm.scalarFunctionScriptControl1, and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
Dispose() [3/4]
override void IG.Forms.ScalarFunctionScriptForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ScalarFunctionScriptForm.components.
InitializeComponent() [3/4]
void IG.Forms.ScalarFunctionScriptForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ScalarFunctionScriptControl.Dimension, IG.Forms.ScalarFunctionScriptControl.FunctionDescription, IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Forms.ScalarFunctionScriptControl.ParameterNames, IG.Forms.ScalarFunctionScriptForm.scalarFunctionScriptControl1, and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
Dispose() [4/4]
override void IG.Forms.ScalarFunctionScriptForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ScalarFunctionScriptForm.components.
InitializeComponent() [4/4]
void IG.Forms.ScalarFunctionScriptForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ScalarFunctionScriptControl.Dimension, IG.Forms.ScalarFunctionScriptControl.FunctionDescription, IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Forms.ScalarFunctionScriptControl.ParameterNames, IG.Forms.ScalarFunctionScriptForm.scalarFunctionScriptControl1, and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.ScalarFunctionScriptForm.components = null private
Required designer variable.
Referenced by IG.Forms.ScalarFunctionScriptForm.Dispose().
scalarFunctionScriptControl1
IG Forms ScalarFunctionScriptControl IG.Forms.ScalarFunctionScriptForm.scalarFunctionScriptControl1 = null private
Referenced by IG.Forms.ScalarFunctionScriptForm.InitializeComponent(), and IG.Forms.ScalarFunctionScriptForm.ScalarFunctionScriptForm().
The documentation for this class was generated from the following files:
iglib/extensions/iglibext/Forms/Numeric/ScalarFunctionScriptForm.cs
iglib/extensions/iglibext/Forms/Numeric/ScalarFunctionScriptForm.Designer.cs