Doc: IGLib EXTENDED: NUnit.Framework.Tests.Attributes.TestOfTests Class Reference
NUnit.Framework.Tests.Attributes.TestOfTests Class Reference
Public Member Functions
void ReflectionTest ()
void TestOf ()
void NoTestOf ()
void FixtureTestOf ()
void SeparateTestOfAttribute ()
void SeparateTestOfStringMethod ()
void TestOfOnTestCase ()
Static Private Attributes
static readonly Type FixtureType = typeof(TestOfFixture)
Member Function Documentation
ReflectionTest()
void NUnit.Framework.Tests.Attributes.TestOfTests.ReflectionTest () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Tests.Attributes.TestOfTests.FixtureType, NUnit.TestUtilities.TestBuilder.MakeTestCase(), and NUnit.Framework.Internal.Test.RunState.
TestOf()
void NUnit.Framework.Tests.Attributes.TestOfTests.TestOf () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Tests.Attributes.TestOfTests.FixtureType, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeTestCase(), NUnit.Framework.Internal.Test.Properties, and NUnit.Framework.Internal.PropertyNames.TestOf.
NoTestOf()
void NUnit.Framework.Tests.Attributes.TestOfTests.NoTestOf () inline
References NUnit.Framework.Tests.Attributes.TestOfTests.FixtureType, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Assert.IsNull(), NUnit.TestUtilities.TestBuilder.MakeTestCase(), NUnit.Framework.Internal.Test.Properties, and NUnit.Framework.Internal.PropertyNames.TestOf.
FixtureTestOf()
void NUnit.Framework.Tests.Attributes.TestOfTests.FixtureTestOf () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Tests.Attributes.TestOfTests.FixtureType, NUnit.TestUtilities.TestBuilder.MakeFixture(), and NUnit.Framework.Internal.PropertyNames.TestOf.
SeparateTestOfAttribute()
void NUnit.Framework.Tests.Attributes.TestOfTests.SeparateTestOfAttribute () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Tests.Attributes.TestOfTests.FixtureType, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeTestCase(), NUnit.Framework.Internal.Test.Properties, and NUnit.Framework.Internal.PropertyNames.TestOf.
SeparateTestOfStringMethod()
void NUnit.Framework.Tests.Attributes.TestOfTests.SeparateTestOfStringMethod () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Tests.Attributes.TestOfTests.FixtureType, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeTestCase(), NUnit.Framework.Internal.Test.Properties, and NUnit.Framework.Internal.PropertyNames.TestOf.
TestOfOnTestCase()
void NUnit.Framework.Tests.Attributes.TestOfTests.TestOfOnTestCase () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Tests.Attributes.TestOfTests.FixtureType, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.PropertyNames.TestOf, and NUnit.Framework.Internal.TestSuite.Tests.
Member Data Documentation
FixtureType
readonly Type NUnit.Framework.Tests.Attributes.TestOfTests.FixtureType = typeof(TestOfFixture) static private
Referenced by NUnit.Framework.Tests.Attributes.TestOfTests.FixtureTestOf(), NUnit.Framework.Tests.Attributes.TestOfTests.NoTestOf(), NUnit.Framework.Tests.Attributes.TestOfTests.ReflectionTest(), NUnit.Framework.Tests.Attributes.TestOfTests.SeparateTestOfAttribute(), NUnit.Framework.Tests.Attributes.TestOfTests.SeparateTestOfStringMethod(), NUnit.Framework.Tests.Attributes.TestOfTests.TestOf(), and NUnit.Framework.Tests.Attributes.TestOfTests.TestOfOnTestCase().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/TestOfTests.cs