Doc: IGLib EXTENDED: IG.Script.DemoResonanceCurvePlot Class Reference
IG.Script.DemoResonanceCurvePlot Class Reference
Try-it-yourself script class.
Static Public Member Functions
static void Run (string[] arguments)
Plots the analytical resonance curve for the linear oscillator, then numerically calculates
Detailed Description
Try-it-yourself script class.
Member Function Documentation
Run()
static void IG.Script.DemoResonanceCurvePlot.Run (string[] arguments) inline static
Plots the analytical resonance curve for the linear oscillator, then numerically calculates
some points of the curve and plots them on top. The deviation can then be compared.
References IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.AngularFrequencySquare, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.CalcAnalyticalAmplitudeVsDrivingFrequnecy(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.CalcSteadyStateAmplitudeVsDrivingFrequency(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.DampingCoefficient, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.DomainDensityMultiplier, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.EndingDrivingAngularFrequency, IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase.NewCurveFromPlottableData(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.NSamplesForResonanceCurve, IG.MPetekLib.Algorithms.Plotting.PlotHQ.Plotter, IG.MPetekLib.Algorithms.Plotting.PlotHQ.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.PlottableODEModelBase.Solver, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.StartingDrivingAngularFrequency, and IG.MPetekLib.Algorithms.Solvers.InitialProblemODE_RK4.InitialProblemSolverBase.StepSize.
Referenced by IG.Script.AppMarkoPetekDerivedScript.AppExecuteDemoResCurvePlot().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/Guest_Marko_Petek_App/AppMarkoPetekDerivedScript.cs