Doc: IGLib EXTENDED: NUnit.Framework.Internal.Execution.CompositeWorkItem Class Reference
NUnit.Framework.Internal.Execution.CompositeWorkItem Class Reference
A CompositeWorkItem represents a test suite and encapsulates the execution of the suite as well as all its child tests.
Public Member Functions
CompositeWorkItem (TestSuite suite, ITestFilter childFilter)
Construct a CompositeWorkItem for executing a test suite using a filter to select child tests.
Public Member Functions inherited from NUnit.Framework.Internal.Execution.WorkItem
WorkItem (Test test)
Construct a WorkItem for a particular test.
void InitializeContext (TestExecutionContext context)
Initialize the TestExecutionContext. This must be done before executing the WorkItem.
virtual void Execute ()
Execute the current work item, including any child work items.
Protected Member Functions
override void PerformWork ()
Method that actually performs the work. Overridden in CompositeWorkItem to do setup, run all child items and then do teardown.
Protected Member Functions inherited from NUnit.Framework.Internal.Execution.WorkItem
void WorkItemComplete ()
Method called by the derived class when all work is complete
Private Member Functions
bool CheckForCancellation ()
void InitializeSetUpAndTearDownCommands ()
void PerformOneTimeSetUp ()
void RunChildren ()
void CreateChildWorkItems ()
void SkipFixture (ResultState resultState, string message, string stackTrace)
void SkipChildren (TestSuite suite, ResultState resultState, string message)
void PerformOneTimeTearDown ()
string GetSkipReason ()
string GetProviderStackTrace ()
void OnChildCompleted (object sender, EventArgs e)
void CountDownChildTest ()
Static Private Member Functions
static bool IsStaticClass (Type type)
Private Attributes
TestSuite _suite
ITestFilter _childFilter
TestCommand _setupCommand
TestCommand _teardownCommand
List< WorkItem > _children
CountdownEvent _childTestCountdown
object _completionLock = new object()
Additional Inherited Members
Static Public Member Functions inherited from NUnit.Framework.Internal.Execution.WorkItem
static WorkItem CreateWorkItem (ITest test, ITestFilter filter)
Creates a work item.
Properties inherited from NUnit.Framework.Internal.Execution.WorkItem
WorkItemState State [get]
Gets the current state of the WorkItem
Test Test [get]
The test being executed by the work item
TestExecutionContext Context [get]
The execution context
List< ITestAction > Actions [get]
The test actions to be performed before and after this test
TestResult Result [get, protected set]
The test result
Events inherited from NUnit.Framework.Internal.Execution.WorkItem
EventHandler Completed
Event triggered when the item is complete
Detailed Description
A CompositeWorkItem represents a test suite and encapsulates the execution of the suite as well as all its child tests.
Constructor & Destructor Documentation
CompositeWorkItem()
NUnit.Framework.Internal.Execution.CompositeWorkItem.CompositeWorkItem (TestSuite suite, ITestFilter childFilter) inline
Construct a CompositeWorkItem for executing a test suite using a filter to select child tests.
Parameters
suite The TestSuite to be executed
childFilter A filter used to select child tests
References NUnit.Framework.Internal.Execution.CompositeWorkItem._childFilter, and NUnit.Framework.Internal.Execution.CompositeWorkItem._suite.
Member Function Documentation
PerformWork()
override void NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork () inline protected virtual
Method that actually performs the work. Overridden in CompositeWorkItem to do setup, run all child items and then do teardown.
Implements NUnit.Framework.Internal.Execution.WorkItem.
References NUnit.Framework.Internal.Execution.CompositeWorkItem._childFilter, NUnit.Framework.Internal.Execution.CompositeWorkItem._children, NUnit.Framework.Internal.Execution.CompositeWorkItem._suite, NUnit.Framework.Internal.Execution.CompositeWorkItem.CheckForCancellation(), NUnit.Framework.Internal.Execution.WorkItem.Context, NUnit.Framework.Internal.Execution.CompositeWorkItem.CreateChildWorkItems(), NUnit.Framework.Internal.TestExecutionContext.ExecutionStatus, NUnit.Framework.Interfaces.ResultState.Explicit, NUnit.Framework.Internal.Execution.CompositeWorkItem.GetProviderStackTrace(), NUnit.Framework.Internal.Execution.CompositeWorkItem.GetSkipReason(), NUnit.Framework.Interfaces.ResultState.Ignored, NUnit.Framework.Internal.Execution.CompositeWorkItem.InitializeSetUpAndTearDownCommands(), NUnit.Framework.Interfaces.ITestFilter.IsExplicitMatch(), NUnit.Framework.Internal.TestResult.Message, NUnit.Framework.Interfaces.ResultState.NotRunnable, NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeSetUp(), NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeTearDown(), NUnit.Framework.Internal.Execution.WorkItem.Result, NUnit.Framework.Internal.TestResult.ResultState, NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren(), NUnit.Framework.Internal.TestResult.SetResult(), NUnit.Framework.Internal.Execution.CompositeWorkItem.SkipChildren(), NUnit.Framework.Internal.Execution.CompositeWorkItem.SkipFixture(), NUnit.Framework.Interfaces.ResultState.Skipped, NUnit.Framework.Interfaces.ResultState.Status, NUnit.Framework.Interfaces.ResultState.Success, NUnit.Framework.Interfaces.ResultState.WithSite(), and NUnit.Framework.Internal.Execution.WorkItem.WorkItemComplete().
CheckForCancellation()
bool NUnit.Framework.Internal.Execution.CompositeWorkItem.CheckForCancellation () inline private
References NUnit.Framework.Interfaces.ResultState.Cancelled, NUnit.Framework.Internal.Execution.WorkItem.Context, NUnit.Framework.Internal.TestExecutionContext.ExecutionStatus, NUnit.Framework.Internal.Execution.WorkItem.Result, and NUnit.Framework.Internal.TestResult.SetResult().
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork(), and NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren().
InitializeSetUpAndTearDownCommands()
void NUnit.Framework.Internal.Execution.CompositeWorkItem.InitializeSetUpAndTearDownCommands () inline private
References NUnit.Framework.Internal.Execution.CompositeWorkItem._setupCommand, NUnit.Framework.Internal.Execution.CompositeWorkItem._suite, NUnit.Framework.Internal.Execution.CompositeWorkItem._teardownCommand, NUnit.Framework.Internal.Execution.WorkItem.Actions, NUnit.Framework.Internal.Execution.CommandBuilder.BuildSetUpTearDownList(), NUnit.Framework.Internal.Execution.WorkItem.Context, NUnit.Framework.Internal.Execution.CommandBuilder.MakeOneTimeSetUpCommand(), NUnit.Framework.Internal.Execution.CommandBuilder.MakeOneTimeTearDownCommand(), NUnit.Framework.ITestAction.Targets, NUnit.Framework.Interfaces.ITypeInfo.Type, NUnit.Framework.Internal.Test.TypeInfo, and NUnit.Framework.Internal.TestExecutionContext.UpstreamActions.
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork().
PerformOneTimeSetUp()
void NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeSetUp () inline private
References NUnit.Framework.Internal.Execution.CompositeWorkItem._setupCommand, NUnit.Framework.Internal.Execution.WorkItem.Context, NUnit.Framework.Internal.Commands.TestCommand.Execute(), NUnit.Framework.Internal.TestResult.RecordException(), NUnit.Framework.Internal.Execution.WorkItem.Result, and NUnit.Framework.Internal.TestExecutionContext.UpdateContextFromEnvironment().
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork().
RunChildren()
void NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren () inline private
References NUnit.Framework.Internal.Execution.CompositeWorkItem._children, NUnit.Framework.Internal.Execution.CompositeWorkItem._childTestCountdown, NUnit.Framework.Internal.Execution.CompositeWorkItem.CheckForCancellation(), NUnit.Framework.Internal.Execution.WorkItem.Completed, NUnit.Framework.Internal.Execution.WorkItem.Context, NUnit.Framework.Internal.Execution.CompositeWorkItem.CountDownChildTest(), NUnit.Framework.Internal.Execution.IWorkItemDispatcher.Dispatch(), NUnit.Framework.Internal.Execution.WorkItem.InitializeContext(), and NUnit.Framework.Internal.Execution.CompositeWorkItem.OnChildCompleted().
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork().
CreateChildWorkItems()
void NUnit.Framework.Internal.Execution.CompositeWorkItem.CreateChildWorkItems () inline private
References NUnit.Framework.Internal.Execution.CompositeWorkItem._childFilter, NUnit.Framework.Internal.Execution.CompositeWorkItem._children, NUnit.Framework.Internal.Execution.CompositeWorkItem._suite, NUnit.Framework.Internal.Execution.WorkItem.CreateWorkItem(), NUnit.Framework.Interfaces.ITestFilter.Pass(), and NUnit.Framework.Internal.TestSuite.Tests.
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork().
SkipFixture()
void NUnit.Framework.Internal.Execution.CompositeWorkItem.SkipFixture (ResultState resultState, string message, string stackTrace) inline private
References NUnit.Framework.Internal.Execution.CompositeWorkItem._suite, NUnit.Framework.Internal.StackFilter.Filter(), NUnit.Framework.Internal.Execution.WorkItem.Result, NUnit.Framework.Internal.TestResult.SetResult(), NUnit.Framework.Internal.Execution.CompositeWorkItem.SkipChildren(), and NUnit.Framework.Interfaces.ResultState.WithSite().
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork().
SkipChildren()
void NUnit.Framework.Internal.Execution.CompositeWorkItem.SkipChildren (TestSuite suite, ResultState resultState, string message) inline private
References NUnit.Framework.Internal.Execution.CompositeWorkItem._childFilter, NUnit.Framework.Internal.TestResult.AddResult(), NUnit.Framework.Internal.Execution.WorkItem.Context, NUnit.Framework.Internal.Test.IsSuite, NUnit.Framework.Internal.Test.MakeTestResult(), NUnit.Framework.Interfaces.ITestFilter.Pass(), NUnit.Framework.Internal.Execution.WorkItem.Result, NUnit.Framework.Internal.TestResult.SetResult(), and NUnit.Framework.Interfaces.ITestListener.TestFinished().
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork(), and NUnit.Framework.Internal.Execution.CompositeWorkItem.SkipFixture().
PerformOneTimeTearDown()
void NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeTearDown () inline private
References NUnit.Framework.Internal.Execution.WorkItem.Context, NUnit.Framework.Internal.TestExecutionContext.EstablishExecutionEnvironment(), and NUnit.Framework.Internal.Commands.TestCommand.Execute().
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.CountDownChildTest(), and NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork().
GetSkipReason()
string NUnit.Framework.Internal.Execution.CompositeWorkItem.GetSkipReason () inline private
References NUnit.Framework.Internal.PropertyNames.SkipReason.
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork().
GetProviderStackTrace()
string NUnit.Framework.Internal.Execution.CompositeWorkItem.GetProviderStackTrace () inline private
References NUnit.Framework.Internal.PropertyNames.ProviderStackTrace.
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork().
OnChildCompleted()
void NUnit.Framework.Internal.Execution.CompositeWorkItem.OnChildCompleted (object sender, EventArgs e) inline private
References NUnit.Framework.Internal.Execution.CompositeWorkItem._completionLock, NUnit.Framework.Internal.TestResult.AddResult(), NUnit.Framework.Internal.Execution.WorkItem.Completed, NUnit.Framework.Internal.Execution.WorkItem.Context, NUnit.Framework.Internal.Execution.CompositeWorkItem.CountDownChildTest(), NUnit.Framework.Internal.TestExecutionContext.ExecutionStatus, NUnit.Framework.Internal.Execution.WorkItem.Result, NUnit.Framework.Internal.TestResult.ResultState, NUnit.Framework.Interfaces.ResultState.Status, NUnit.Framework.Internal.TestExecutionContext.StopOnError, and NUnit.Framework.Internal.Execution.WorkItem.WorkItem().
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren().
CountDownChildTest()
void NUnit.Framework.Internal.Execution.CompositeWorkItem.CountDownChildTest () inline private
References NUnit.Framework.Internal.Execution.CompositeWorkItem._childTestCountdown, NUnit.Framework.Interfaces.ResultState.Cancelled, NUnit.Framework.Internal.TestResult.Children, NUnit.Framework.Internal.Execution.WorkItem.Context, NUnit.Framework.Internal.Execution.CountdownEvent.CurrentCount, NUnit.Framework.Internal.TestExecutionContext.ExecutionStatus, NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeTearDown(), NUnit.Framework.Internal.Execution.WorkItem.Result, NUnit.Framework.Internal.TestResult.SetResult(), NUnit.Framework.Internal.Execution.CountdownEvent.Signal(), and NUnit.Framework.Internal.Execution.WorkItem.WorkItemComplete().
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.OnChildCompleted(), and NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren().
IsStaticClass()
static bool NUnit.Framework.Internal.Execution.CompositeWorkItem.IsStaticClass (Type type) inline static private
Member Data Documentation
_suite
TestSuite NUnit.Framework.Internal.Execution.CompositeWorkItem._suite private
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.CompositeWorkItem(), NUnit.Framework.Internal.Execution.CompositeWorkItem.CreateChildWorkItems(), NUnit.Framework.Internal.Execution.CompositeWorkItem.InitializeSetUpAndTearDownCommands(), NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork(), and NUnit.Framework.Internal.Execution.CompositeWorkItem.SkipFixture().
_childFilter
ITestFilter NUnit.Framework.Internal.Execution.CompositeWorkItem._childFilter private
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.CompositeWorkItem(), NUnit.Framework.Internal.Execution.CompositeWorkItem.CreateChildWorkItems(), NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork(), and NUnit.Framework.Internal.Execution.CompositeWorkItem.SkipChildren().
_setupCommand
TestCommand NUnit.Framework.Internal.Execution.CompositeWorkItem._setupCommand private
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.InitializeSetUpAndTearDownCommands(), and NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeSetUp().
_teardownCommand
TestCommand NUnit.Framework.Internal.Execution.CompositeWorkItem._teardownCommand private
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.InitializeSetUpAndTearDownCommands().
_children
List<WorkItem> NUnit.Framework.Internal.Execution.CompositeWorkItem._children private
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.CreateChildWorkItems(), NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork(), and NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren().
_childTestCountdown
CountdownEvent NUnit.Framework.Internal.Execution.CompositeWorkItem._childTestCountdown private
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.CountDownChildTest(), and NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren().
_completionLock
object NUnit.Framework.Internal.Execution.CompositeWorkItem._completionLock = new object() private
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.OnChildCompleted().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/Execution/CompositeWorkItem.cs