Doc: IGLib EXTENDED: Test_Igor.ProgramTestIgor Class Reference
Test_Igor.ProgramTestIgor Class Reference
Testing program for Igor Grešovnik.
Static Public Member Functions
static void TestPathMethods ()
Static Private Member Functions
static void Main (string[] args)
Detailed Description
Testing program for Igor Grešovnik.
Member Function Documentation
Main()
static void Test_Igor.ProgramTestIgor.Main (string[] args) inline static private
References IG.Num.NeuralApproximatorBase.ExampleSaveNetwork(), and Test_Igor.ProgramTestIgor.TestPathMethods().
TestPathMethods()
static void Test_Igor.ProgramTestIgor.TestPathMethods () inline static
Referenced by Test_Igor.ProgramTestIgor.Main().
The documentation for this class was generated from the following file:
shelldev/extensions_shell/shell/Test_Igor/ProgramTestIgor.cs