Doc: IGLib EXTENDED: NUnit.Framework.Internal.PropertyBagTests Class Reference
NUnit.Framework.Internal.PropertyBagTests Class Reference
Public Member Functions
void SetUp ()
void IndexGetsListOfValues ()
void IndexGetsEmptyListIfNameIsNotPresent ()
void IndexSetsListOfValues ()
void AllKeysAreListed ()
void ContainsKey ()
void GetReturnsSingleValue ()
void SetAddsNewSingleValue ()
void SetReplacesOldValues ()
void XmlIsProducedCorrectly ()
Private Attributes
PropertyBag bag
Member Function Documentation
SetUp()
void NUnit.Framework.Internal.PropertyBagTests.SetUp () inline
References NUnit.Framework.Internal.PropertyBag.Add(), and NUnit.Framework.Internal.PropertyBagTests.bag.
IndexGetsListOfValues()
void NUnit.Framework.Internal.PropertyBagTests.IndexGetsListOfValues () inline
References NUnit.Framework.Internal.PropertyBagTests.bag, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Contains.Item(), and NUnit.Framework.Assert.That().
IndexGetsEmptyListIfNameIsNotPresent()
void NUnit.Framework.Internal.PropertyBagTests.IndexGetsEmptyListIfNameIsNotPresent () inline
References NUnit.Framework.Internal.PropertyBagTests.bag, NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
IndexSetsListOfValues()
void NUnit.Framework.Internal.PropertyBagTests.IndexSetsListOfValues () inline
References NUnit.Framework.Internal.PropertyBagTests.bag, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Contains.Item(), and NUnit.Framework.Assert.That().
AllKeysAreListed()
void NUnit.Framework.Internal.PropertyBagTests.AllKeysAreListed () inline
References NUnit.Framework.Internal.PropertyBagTests.bag, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.PropertyBag.Keys, NUnit.Framework.Has.Member(), and NUnit.Framework.Assert.That().
ContainsKey()
void NUnit.Framework.Internal.PropertyBagTests.ContainsKey () inline
References NUnit.Framework.Internal.PropertyBagTests.bag, NUnit.Framework.Internal.PropertyBag.ContainsKey(), NUnit.Framework.Assert.False(), and NUnit.Framework.Assert.That().
GetReturnsSingleValue()
void NUnit.Framework.Internal.PropertyBagTests.GetReturnsSingleValue () inline
References NUnit.Framework.Internal.PropertyBagTests.bag, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.PropertyBag.Get(), and NUnit.Framework.Assert.That().
SetAddsNewSingleValue()
void NUnit.Framework.Internal.PropertyBagTests.SetAddsNewSingleValue () inline
References NUnit.Framework.Internal.PropertyBagTests.bag, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.PropertyBag.Get(), NUnit.Framework.Has.Member(), NUnit.Framework.Internal.PropertyBag.Set(), and NUnit.Framework.Assert.That().
SetReplacesOldValues()
void NUnit.Framework.Internal.PropertyBagTests.SetReplacesOldValues () inline
References NUnit.Framework.Internal.PropertyBagTests.bag, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.PropertyBag.Get(), NUnit.Framework.Internal.PropertyBag.Set(), and NUnit.Framework.Assert.That().
XmlIsProducedCorrectly()
void NUnit.Framework.Internal.PropertyBagTests.XmlIsProducedCorrectly () inline
References NUnit.Framework.Interfaces.TNode.Attributes, NUnit.Framework.Internal.PropertyBagTests.bag, NUnit.Framework.Interfaces.TNode.ChildNodes, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.EquivalentTo(), NUnit.Framework.Interfaces.TNode.Name, NUnit.Framework.Assert.That(), and NUnit.Framework.Internal.PropertyBag.ToXml().
Member Data Documentation
bag
PropertyBag NUnit.Framework.Internal.PropertyBagTests.bag private
Referenced by NUnit.Framework.Internal.PropertyBagTests.AllKeysAreListed(), NUnit.Framework.Internal.PropertyBagTests.ContainsKey(), NUnit.Framework.Internal.PropertyBagTests.GetReturnsSingleValue(), NUnit.Framework.Internal.PropertyBagTests.IndexGetsEmptyListIfNameIsNotPresent(), NUnit.Framework.Internal.PropertyBagTests.IndexGetsListOfValues(), NUnit.Framework.Internal.PropertyBagTests.IndexSetsListOfValues(), NUnit.Framework.Internal.PropertyBagTests.SetAddsNewSingleValue(), NUnit.Framework.Internal.PropertyBagTests.SetReplacesOldValues(), NUnit.Framework.Internal.PropertyBagTests.SetUp(), and NUnit.Framework.Internal.PropertyBagTests.XmlIsProducedCorrectly().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/PropertyBagTests.cs