Doc: IGLib EXTENDED: AForge.Imaging.IntegralImage Class Reference
AForge.Imaging.IntegralImage Class Reference
Integral image.
Public Member Functions
uint GetRectangleSum (int x1, int y1, int x2, int y2)
Calculate sum of pixels in the specified rectangle.
int GetHaarXWavelet (int x, int y, int radius)
Calculate horizontal (X) haar wavelet at the specified point.
int GetHaarYWavelet (int x, int y, int radius)
Calculate vertical (Y) haar wavelet at the specified point.
uint GetRectangleSumUnsafe (int x1, int y1, int x2, int y2)
Calculate sum of pixels in the specified rectangle without checking it's coordinates.
uint GetRectangleSum (int x, int y, int radius)
Calculate sum of pixels in the specified rectangle.
uint GetRectangleSumUnsafe (int x, int y, int radius)
Calculate sum of pixels in the specified rectangle without checking it's coordinates.
float GetRectangleMean (int x1, int y1, int x2, int y2)
Calculate mean value of pixels in the specified rectangle.
float GetRectangleMeanUnsafe (int x1, int y1, int x2, int y2)
Calculate mean value of pixels in the specified rectangle without checking it's coordinates.
float GetRectangleMean (int x, int y, int radius)
Calculate mean value of pixels in the specified rectangle.
float GetRectangleMeanUnsafe (int x, int y, int radius)
Calculate mean value of pixels in the specified rectangle without checking it's coordinates.
Static Public Member Functions
static IntegralImage FromBitmap (Bitmap image)
Construct integral image from source grayscale image.
static IntegralImage FromBitmap (BitmapData imageData)
Construct integral image from source grayscale image.
static IntegralImage FromBitmap (UnmanagedImage image)
Construct integral image from source grayscale image.
Protected Member Functions
IntegralImage (int width, int height)
Initializes a new instance of the IntegralImage class.
Protected Attributes
uint[,] integralImage = null
Intergral image's array.
Properties
int Width [get]
Width of the source image the integral image was constructed for.
int Height [get]
Height of the source image the integral image was constructed for.
uint[,] InternalData [get]
Provides access to internal array keeping integral image data.
Private Attributes
int width
int height
Detailed Description
Integral image.
The class implements integral image concept, which is described by Viola and Jones in: P. Viola and M. J. Jones, "Robust real-time face detection", Int. Journal of Computer Vision 57(2), pp. 137–154, 2004.
"An integral image I of an input image G is defined as the image in which the intensity at a pixel position is equal to the sum of the intensities of all the pixels above and to the left of that position in the original image."
The intensity at position (x, y) can be written as:
          x    y
I(x,y) = SUM(SUM(G(i,j)))
         i=0  j=0
<note>The class uses 32-bit integers to represent integral image.</note>
<note>The class processes only grayscale (8 bpp indexed) images.</note>
<note>This class contains two versions of each method: safe and unsafe. Safe methods do checks of provided coordinates and ensure that these coordinates belong to the image, what makes these methods slower. Unsafe methods do not do coordinates' checks and rely that these coordinates belong to the image, what makes these methods faster.</note>
Sample usage:
// create integral image
IntegralImage im = IntegralImage.FromBitmap(image);
// get pixels' mean value in the specified rectangle
float mean = im.GetRectangleMean(10, 10, 20, 30)
Constructor & Destructor Documentation
IntegralImage()
AForge.Imaging.IntegralImage.IntegralImage (int width, int height) inline protected
Initializes a new instance of the IntegralImage class.
Parameters
width Image width.
height Image height.
The constractor is protected, what makes it imposible to instantiate this class directly. To create an instance of this class FromBitmap(Bitmap) or FromBitmap(BitmapData) method should be used.
References AForge.Imaging.IntegralImage.height, AForge.Imaging.IntegralImage.integralImage, and AForge.Imaging.IntegralImage.width.
Referenced by AForge.Imaging.IntegralImage.FromBitmap().
Member Function Documentation
FromBitmap() [1/3]
static IntegralImage AForge.Imaging.IntegralImage.FromBitmap (Bitmap image) inline static
Construct integral image from source grayscale image.
Parameters
image Source grayscale image.
Returns
Returns integral image.
Exceptions
UnsupportedImageFormatException The source image has incorrect pixel format.
References AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.IntegralImage.FromBitmap(), AForge.Imaging.Tests.IntegralImageTest.IntegralImageTest(), and AForge.Imaging.Filters.BradleyLocalThresholding.ProcessFilter().
FromBitmap() [2/3]
static IntegralImage AForge.Imaging.IntegralImage.FromBitmap (BitmapData imageData) inline static
Construct integral image from source grayscale image.
Parameters
imageData Source image data.
Returns
Returns integral image.
Exceptions
UnsupportedImageFormatException The source image has incorrect pixel format.
References AForge.Imaging.IntegralImage.FromBitmap().
FromBitmap() [3/3]
static IntegralImage AForge.Imaging.IntegralImage.FromBitmap (UnmanagedImage image) inline static
Construct integral image from source grayscale image.
Parameters
image Source unmanaged image.
Returns
Returns integral image.
Exceptions
UnsupportedImageFormatException The source image has incorrect pixel format.
References AForge.Imaging.IntegralImage.height, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.IntegralImage.integralImage, AForge.Imaging.IntegralImage.IntegralImage(), AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.UnmanagedImage.Stride, AForge.Imaging.IntegralImage.width, and AForge.Imaging.UnmanagedImage.Width.
GetRectangleSum() [1/2]
uint AForge.Imaging.IntegralImage.GetRectangleSum (int x1, int y1, int x2, int y2) inline
Calculate sum of pixels in the specified rectangle.
Parameters
x1 X coordinate of left-top rectangle's corner.
y1 Y coordinate of left-top rectangle's corner.
x2 X coordinate of right-bottom rectangle's corner.
y2 Y coordinate of right-bottom rectangle's corner.
Returns
Returns sum of pixels in the specified rectangle.
Both specified points are included into the calculation rectangle.
References AForge.Imaging.IntegralImage.height, AForge.Imaging.IntegralImage.integralImage, and AForge.Imaging.IntegralImage.width.
Referenced by AForge.Imaging.IntegralImage.GetHaarXWavelet(), AForge.Imaging.IntegralImage.GetHaarYWavelet(), AForge.Imaging.IntegralImage.GetRectangleSum(), AForge.Imaging.Tests.IntegralImageTest.GetRectangleSumTest(), and AForge.Imaging.Tests.IntegralImageTest.GetRectangleSumUnsafeTest().
GetHaarXWavelet()
int AForge.Imaging.IntegralImage.GetHaarXWavelet (int x, int y, int radius) inline
Calculate horizontal (X) haar wavelet at the specified point.
Parameters
x X coordinate of the point to calculate wavelet at.
y Y coordinate of the point to calculate wavelet at.
radius Wavelet size to calculate.
Returns
Returns value of the horizontal wavelet at the specified point.
The method calculates horizontal wavelet, which is a difference of two horizontally adjacent boxes' sums, i.e. A-B. A is the sum of rectangle with coordinates (x, y-radius, x+radius-1, y+radius-1). B is the sum of rectangle with coordinates (x-radius, y-radius, x-1, y+radiys-1).
References AForge.Imaging.IntegralImage.GetRectangleSum().
Referenced by AForge.Imaging.Tests.IntegralImageTest.GetHaarXWavelet().
GetHaarYWavelet()
int AForge.Imaging.IntegralImage.GetHaarYWavelet (int x, int y, int radius) inline
Calculate vertical (Y) haar wavelet at the specified point.
Parameters
x X coordinate of the point to calculate wavelet at.
y Y coordinate of the point to calculate wavelet at.
radius Wavelet size to calculate.
Returns
Returns value of the vertical wavelet at the specified point.
The method calculates vertical wavelet, which is a difference of two vertical adjacent boxes' sums, i.e. A-B. A is the sum of rectangle with coordinates (x-radius, y, x+radius-1, y+radius-1). B is the sum of rectangle with coordinates (x-radius, y-radius, x+radius-1, y-1).
References AForge.Imaging.IntegralImage.GetRectangleSum().
Referenced by AForge.Imaging.Tests.IntegralImageTest.GetHaarYWavelet().
GetRectangleSumUnsafe() [1/2]
uint AForge.Imaging.IntegralImage.GetRectangleSumUnsafe (int x1, int y1, int x2, int y2) inline
Calculate sum of pixels in the specified rectangle without checking it's coordinates.
Parameters
x1 X coordinate of left-top rectangle's corner.
y1 Y coordinate of left-top rectangle's corner.
x2 X coordinate of right-bottom rectangle's corner.
y2 Y coordinate of right-bottom rectangle's corner.
Returns
Returns sum of pixels in the specified rectangle.
Both specified points are included into the calculation rectangle.
References AForge.Imaging.IntegralImage.integralImage.
Referenced by AForge.Imaging.IntegralImage.GetRectangleSumUnsafe().
GetRectangleSum() [2/2]
uint AForge.Imaging.IntegralImage.GetRectangleSum (int x, int y, int radius) inline
Calculate sum of pixels in the specified rectangle.
Parameters
x X coordinate of central point of the rectangle.
y Y coordinate of central point of the rectangle.
radius Radius of the rectangle.
Returns
Returns sum of pixels in the specified rectangle.
The method calculates sum of pixels in square rectangle with odd width and height. In the case if it is required to calculate sum of 3x3 rectangle, then it is required to specify its center and radius equal to 1.
References AForge.Imaging.IntegralImage.GetRectangleSum().
GetRectangleSumUnsafe() [2/2]
uint AForge.Imaging.IntegralImage.GetRectangleSumUnsafe (int x, int y, int radius) inline
Calculate sum of pixels in the specified rectangle without checking it's coordinates.
Parameters
x X coordinate of central point of the rectangle.
y Y coordinate of central point of the rectangle.
radius Radius of the rectangle.
Returns
Returns sum of pixels in the specified rectangle.
The method calculates sum of pixels in square rectangle with odd width and height. In the case if it is required to calculate sum of 3x3 rectangle, then it is required to specify its center and radius equal to 1.
References AForge.Imaging.IntegralImage.GetRectangleSumUnsafe().
GetRectangleMean() [1/2]
float AForge.Imaging.IntegralImage.GetRectangleMean (int x1, int y1, int x2, int y2) inline
Calculate mean value of pixels in the specified rectangle.
Parameters
x1 X coordinate of left-top rectangle's corner.
y1 Y coordinate of left-top rectangle's corner.
x2 X coordinate of right-bottom rectangle's corner.
y2 Y coordinate of right-bottom rectangle's corner.
Returns
Returns mean value of pixels in the specified rectangle.
Both specified points are included into the calculation rectangle.
References AForge.Imaging.IntegralImage.height, AForge.Imaging.IntegralImage.integralImage, and AForge.Imaging.IntegralImage.width.
Referenced by AForge.Imaging.IntegralImage.GetRectangleMean(), and AForge.Imaging.Tests.IntegralImageTest.GetRectangleMeanTest().
GetRectangleMeanUnsafe() [1/2]
float AForge.Imaging.IntegralImage.GetRectangleMeanUnsafe (int x1, int y1, int x2, int y2) inline
Calculate mean value of pixels in the specified rectangle without checking it's coordinates.
Parameters
x1 X coordinate of left-top rectangle's corner.
y1 Y coordinate of left-top rectangle's corner.
x2 X coordinate of right-bottom rectangle's corner.
y2 Y coordinate of right-bottom rectangle's corner.
Returns
Returns mean value of pixels in the specified rectangle.
Both specified points are included into the calculation rectangle.
References AForge.Imaging.IntegralImage.integralImage.
Referenced by AForge.Imaging.IntegralImage.GetRectangleMeanUnsafe(), and AForge.Imaging.Filters.BradleyLocalThresholding.ProcessFilter().
GetRectangleMean() [2/2]
float AForge.Imaging.IntegralImage.GetRectangleMean (int x, int y, int radius) inline
Calculate mean value of pixels in the specified rectangle.
Parameters
x X coordinate of central point of the rectangle.
y Y coordinate of central point of the rectangle.
radius Radius of the rectangle.
Returns
Returns mean value of pixels in the specified rectangle.
The method calculates mean value of pixels in square rectangle with odd width and height. In the case if it is required to calculate mean value of 3x3 rectangle, then it is required to specify its center and radius equal to 1.
References AForge.Imaging.IntegralImage.GetRectangleMean().
GetRectangleMeanUnsafe() [2/2]
float AForge.Imaging.IntegralImage.GetRectangleMeanUnsafe (int x, int y, int radius) inline
Calculate mean value of pixels in the specified rectangle without checking it's coordinates.
Parameters
x X coordinate of central point of the rectangle.
y Y coordinate of central point of the rectangle.
radius Radius of the rectangle.
Returns
Returns mean value of pixels in the specified rectangle.
The method calculates mean value of pixels in square rectangle with odd width and height. In the case if it is required to calculate mean value of 3x3 rectangle, then it is required to specify its center and radius equal to 1.
References AForge.Imaging.IntegralImage.GetRectangleMeanUnsafe().
Member Data Documentation
integralImage
uint [,] AForge.Imaging.IntegralImage.integralImage = null protected
Intergral image's array.
See remarks to InternalData property.
Referenced by AForge.Imaging.IntegralImage.FromBitmap(), AForge.Imaging.IntegralImage.GetRectangleMean(), AForge.Imaging.IntegralImage.GetRectangleMeanUnsafe(), AForge.Imaging.IntegralImage.GetRectangleSum(), AForge.Imaging.IntegralImage.GetRectangleSumUnsafe(), and AForge.Imaging.IntegralImage.IntegralImage().
width
int AForge.Imaging.IntegralImage.width private
Referenced by AForge.Imaging.IntegralImage.FromBitmap(), AForge.Imaging.IntegralImage.GetRectangleMean(), AForge.Imaging.IntegralImage.GetRectangleSum(), and AForge.Imaging.IntegralImage.IntegralImage().
height
int AForge.Imaging.IntegralImage.height private
Referenced by AForge.Imaging.IntegralImage.FromBitmap(), AForge.Imaging.IntegralImage.GetRectangleMean(), AForge.Imaging.IntegralImage.GetRectangleSum(), and AForge.Imaging.IntegralImage.IntegralImage().
Property Documentation
Width
int AForge.Imaging.IntegralImage.Width get
Width of the source image the integral image was constructed for.
Height
int AForge.Imaging.IntegralImage.Height get
Height of the source image the integral image was constructed for.
InternalData
uint [,] AForge.Imaging.IntegralImage.InternalData get
Provides access to internal array keeping integral image data.
<note>The array should be accessed by [y, x] indexing.</note>
<note>The array's size is [Height+1, Width+1]. The first row and column are filled with zeros, what is done for more efficient calculation of rectangles' sums.</note>
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/IntegralImage.cs