Doc: IGLib EXTENDED: AForge.Math.Complex Struct Reference
AForge.Math.Complex Struct Reference
Complex number wrapper class.
Public Member Functions
Complex (double re, double im)
Initializes a new instance of the Complex class.
Complex (Complex c)
Initializes a new instance of the Complex class.
override int GetHashCode ()
Returns the hashcode for this instance.
override bool Equals (object obj)
Returns a value indicating whether this instance is equal to the specified object.
override string ToString ()
Returns a string representation of this object.
object ICloneable. Clone ()
Creates an exact copy of this Complex object.
Complex Clone ()
Creates an exact copy of this Complex object.
void GetObjectData (SerializationInfo info, StreamingContext context)
Populates a SerializationInfo with the data needed to serialize the target object.
Static Public Member Functions
static Complex Add (Complex a, Complex b)
Adds two complex numbers.
static Complex Add (Complex a, double s)
Adds scalar value to a complex number.
static void Add (Complex a, Complex b, ref Complex result)
Adds two complex numbers and puts the result into the third complex number.
static void Add (Complex a, double s, ref Complex result)
Adds scalar value to a complex number and puts the result into another complex number.
static Complex Subtract (Complex a, Complex b)
Subtracts one complex number from another.
static Complex Subtract (Complex a, double s)
Subtracts a scalar from a complex number.
static Complex Subtract (double s, Complex a)
Subtracts a complex number from a scalar value.
static void Subtract (Complex a, Complex b, ref Complex result)
Subtracts one complex number from another and puts the result in the third complex number.
static void Subtract (Complex a, double s, ref Complex result)
Subtracts a scalar value from a complex number and puts the result into another complex number.
static void Subtract (double s, Complex a, ref Complex result)
Subtracts a complex number from a scalar value and puts the result into another complex number.
static Complex Multiply (Complex a, Complex b)
Multiplies two complex numbers.
static Complex Multiply (Complex a, double s)
Multiplies a complex number by a scalar value.
static void Multiply (Complex a, Complex b, ref Complex result)
Multiplies two complex numbers and puts the result in a third complex number.
static void Multiply (Complex a, double s, ref Complex result)
Multiplies a complex number by a scalar value and puts the result into another complex number.
static Complex Divide (Complex a, Complex b)
Divides one complex number by another complex number.
static Complex Divide (Complex a, double s)
Divides a complex number by a scalar value.
static Complex Divide (double s, Complex a)
Divides a scalar value by a complex number.
static void Divide (Complex a, Complex b, ref Complex result)
Divides one complex number by another complex number and puts the result in a third complex number.
static void Divide (Complex a, double s, ref Complex result)
Divides a complex number by a scalar value and puts the result into another complex number.
static void Divide (double s, Complex a, ref Complex result)
Divides a scalar value by a complex number and puts the result into another complex number.
static Complex Negate (Complex a)
Negates a complex number.
static bool ApproxEqual (Complex a, Complex b)
Tests whether two complex numbers are approximately equal using default tolerance value.
static bool ApproxEqual (Complex a, Complex b, double tolerance)
Tests whether two complex numbers are approximately equal given a tolerance value.
static Complex Parse (string s)
Converts the specified string to its Complex equivalent.
static bool TryParse (string s, out Complex result)
Try to convert the specified string to its Complex equivalent.
static Complex Sqrt (Complex a)
Calculates square root of a complex number.
static Complex Log (Complex a)
Calculates natural (base e) logarithm of a complex number.
static Complex Exp (Complex a)
Calculates exponent (e raised to the specified power) of a complex number.
static Complex Sin (Complex a)
Calculates Sine value of the complex number.
static Complex Cos (Complex a)
Calculates Cosine value of the complex number.
static Complex Tan (Complex a)
Calculates Tangent value of the complex number.
static bool operator== (Complex u, Complex v)
Tests whether two specified complex numbers are equal.
static bool operator!= (Complex u, Complex v)
Tests whether two specified complex numbers are not equal.
static Complex operator- (Complex a)
Negates the complex number.
static Complex operator+ (Complex a, Complex b)
Adds two complex numbers.
static Complex operator+ (Complex a, double s)
Adds a complex number and a scalar value.
static Complex operator+ (double s, Complex a)
Adds a complex number and a scalar value.
static Complex operator- (Complex a, Complex b)
Subtracts one complex number from another complex number.
static Complex operator- (Complex a, double s)
Subtracts a scalar value from a complex number.
static Complex operator- (double s, Complex a)
Subtracts a complex number from a scalar value.
static Complex operator* (Complex a, Complex b)
Multiplies two complex numbers.
static Complex operator* (double s, Complex a)
Multiplies a complex number by a scalar value.
static Complex operator* (Complex a, double s)
Multiplies a complex number by a scalar value.
static Complex operator/ (Complex a, Complex b)
Divides one complex number by another complex number.
static Complex operator/ (Complex a, double s)
Divides a complex number by a scalar value.
static Complex operator/ (double s, Complex a)
Divides a scalar value by a complex number.
static operator Complex (float value)
Converts from a single-precision real number to a complex number.
static operator Complex (double value)
Converts from a double-precision real number to a complex number.
Public Attributes
double Re
Real part of the complex number.
double Im
Imaginary part of the complex number.
Static Public Attributes
static readonly Complex Zero = new Complex(0, 0)
A double-precision complex number that represents zero.
static readonly Complex One = new Complex(1, 0)
A double-precision complex number that represents one.
static readonly Complex I = new Complex(0, 1)
A double-precision complex number that represents the squere root of (-1).
Properties
double Magnitude [get]
Magnitude value of the complex number.
double Phase [get]
Phase value of the complex number.
double SquaredMagnitude [get]
Squared magnitude value of the complex number.
Detailed Description
Complex number wrapper class.
The class encapsulates complex number and provides set of different operators to manipulate it, lake adding, subtractio, multiplication, etc.
Sample usage:
// define two complex numbers
Complex c1 = new Complex(3, 9);
Complex c2 = new Complex(8, 3);
// sum
Complex s1 = Complex.Add(c1, c2);
Complex s2 = c1 + c2;
Complex s3 = c1 + 5;
// difference
Complex d1 = Complex.Subtract(c1, c2);
Complex d2 = c1 - c2;
Complex d3 = c1 - 2;
Constructor & Destructor Documentation
Complex() [1/2]
AForge.Math.Complex.Complex (double re, double im) inline
Initializes a new instance of the Complex class.
Parameters
re Real part.
im Imaginary part.
Referenced by AForge.Math.Complex.Add(), AForge.Math.Complex.Clone(), AForge.Math.Complex.Divide(), AForge.Math.Complex.Equals(), AForge.Math.Complex.Multiply(), AForge.Math.Complex.Negate(), AForge.Math.Complex.operator Complex(), AForge.Math.Complex.Subtract(), and AForge.Math.Complex.TryParse().
Complex() [2/2]
AForge.Math.Complex.Complex (Complex c) inline
Initializes a new instance of the Complex class.
Parameters
c Source complex number.
Member Function Documentation
Add() [1/4]
static Complex AForge.Math.Complex.Add (Complex a, Complex b) inline static
Adds two complex numbers.
Parameters
a A Complex instance.
b A Complex instance.
Returns
Returns new Complex instance containing the sum of specified complex numbers.
References AForge.Math.Complex.Complex(), AForge.Math.Complex.Im, and AForge.Math.Complex.Re.
Referenced by AForge.Math.Complex.operator+().
Add() [2/4]
static Complex AForge.Math.Complex.Add (Complex a, double s) inline static
Adds scalar value to a complex number.
Parameters
a A Complex instance.
s A scalar value.
Returns
Returns new Complex instance containing the sum of specified complex number and scalar value.
References AForge.Math.Complex.Complex().
Add() [3/4]
static void AForge.Math.Complex.Add (Complex a, Complex b, ref Complex result) inline static
Adds two complex numbers and puts the result into the third complex number.
Parameters
a A Complex instance.
b A Complex instance.
result A Complex instance to hold the result.
References AForge.Math.Complex.Im, and AForge.Math.Complex.Re.
Add() [4/4]
static void AForge.Math.Complex.Add (Complex a, double s, ref Complex result) inline static
Adds scalar value to a complex number and puts the result into another complex number.
Parameters
a A Complex instance.
s A scalar value.
result A Complex instance to hold the result.
Subtract() [1/6]
static Complex AForge.Math.Complex.Subtract (Complex a, Complex b) inline static
Subtracts one complex number from another.
Parameters
a A Complex instance to subtract from.
b A Complex instance to be subtracted.
Returns
Returns new Complex instance containing the subtraction result (a - b).
References AForge.Math.Complex.Complex(), AForge.Math.Complex.Im, and AForge.Math.Complex.Re.
Referenced by AForge.Math.Complex.operator-().
Subtract() [2/6]
static Complex AForge.Math.Complex.Subtract (Complex a, double s) inline static
Subtracts a scalar from a complex number.
Parameters
a A Complex instance to subtract from.
s A scalar value to be subtracted.
Returns
Returns new Complex instance containing the subtraction result (a - s).
References AForge.Math.Complex.Complex().
Subtract() [3/6]
static Complex AForge.Math.Complex.Subtract (double s, Complex a) inline static
Subtracts a complex number from a scalar value.
Parameters
s A scalar value to subtract from.
a A Complex instance to be subtracted.
Returns
Returns new Complex instance containing the subtraction result (s - a).
References AForge.Math.Complex.Complex().
Subtract() [4/6]
static void AForge.Math.Complex.Subtract (Complex a, Complex b, ref Complex result) inline static
Subtracts one complex number from another and puts the result in the third complex number.
Parameters
a A Complex instance to subtract from.
b A Complex instance to be subtracted.
result A Complex instance to hold the result.
References AForge.Math.Complex.Im, and AForge.Math.Complex.Re.
Subtract() [5/6]
static void AForge.Math.Complex.Subtract (Complex a, double s, ref Complex result) inline static
Subtracts a scalar value from a complex number and puts the result into another complex number.
Parameters
a A Complex instance to subtract from.
s A scalar value to be subtracted.
result A Complex instance to hold the result.
Subtract() [6/6]
static void AForge.Math.Complex.Subtract (double s, Complex a, ref Complex result) inline static
Subtracts a complex number from a scalar value and puts the result into another complex number.
Parameters
s A scalar value to subtract from.
a A Complex instance to be subtracted.
result A Complex instance to hold the result.
Multiply() [1/4]
static Complex AForge.Math.Complex.Multiply (Complex a, Complex b) inline static
Multiplies two complex numbers.
Parameters
a A Complex instance.
b A Complex instance.
Returns
Returns new Complex instance containing the result of multiplication.
References AForge.Math.Complex.Complex(), AForge.Math.Complex.Im, and AForge.Math.Complex.Re.
Referenced by AForge.Math.Complex.operator*().
Multiply() [2/4]
static Complex AForge.Math.Complex.Multiply (Complex a, double s) inline static
Multiplies a complex number by a scalar value.
Parameters
a A Complex instance.
s A scalar value.
Returns
Returns new Complex instance containing the result of multiplication.
References AForge.Math.Complex.Complex().
Multiply() [3/4]
static void AForge.Math.Complex.Multiply (Complex a, Complex b, ref Complex result) inline static
Multiplies two complex numbers and puts the result in a third complex number.
Parameters
a A Complex instance.
b A Complex instance.
result A Complex instance to hold the result.
References AForge.Math.Complex.Im, and AForge.Math.Complex.Re.
Multiply() [4/4]
static void AForge.Math.Complex.Multiply (Complex a, double s, ref Complex result) inline static
Multiplies a complex number by a scalar value and puts the result into another complex number.
Parameters
a A Complex instance.
s A scalar value.
result A Complex instance to hold the result.
Divide() [1/6]
static Complex AForge.Math.Complex.Divide (Complex a, Complex b) inline static
Divides one complex number by another complex number.
Parameters
a A Complex instance.
b A Complex instance.
Returns
Returns new Complex instance containing the result.
Exceptions
DivideByZeroException Can not divide by zero.
References AForge.Math.Complex.Complex(), AForge.Math.Complex.Im, and AForge.Math.Complex.Re.
Referenced by AForge.Math.Complex.operator/().
Divide() [2/6]
static Complex AForge.Math.Complex.Divide (Complex a, double s) inline static
Divides a complex number by a scalar value.
Parameters
a A Complex instance.
s A scalar value.
Returns
Returns new Complex instance containing the result.
Exceptions
DivideByZeroException Can not divide by zero.
References AForge.Math.Complex.Complex().
Divide() [3/6]
static Complex AForge.Math.Complex.Divide (double s, Complex a) inline static
Divides a scalar value by a complex number.
Parameters
s A scalar value.
a A Complex instance.
Returns
Returns new Complex instance containing the result.
Exceptions
DivideByZeroException Can not divide by zero.
References AForge.Math.Complex.Complex().
Divide() [4/6]
static void AForge.Math.Complex.Divide (Complex a, Complex b, ref Complex result) inline static
Divides one complex number by another complex number and puts the result in a third complex number.
Parameters
a A Complex instance.
b A Complex instance.
result A Complex instance to hold the result.
Exceptions
DivideByZeroException Can not divide by zero.
References AForge.Math.Complex.Im, and AForge.Math.Complex.Re.
Divide() [5/6]
static void AForge.Math.Complex.Divide (Complex a, double s, ref Complex result) inline static
Divides a complex number by a scalar value and puts the result into another complex number.
Parameters
a A Complex instance.
s A scalar value.
result A Complex instance to hold the result.
Exceptions
DivideByZeroException Can not divide by zero.
Divide() [6/6]
static void AForge.Math.Complex.Divide (double s, Complex a, ref Complex result) inline static
Divides a scalar value by a complex number and puts the result into another complex number.
Parameters
a A Complex instance.
s A scalar value.
result A Complex instance to hold the result.
Exceptions
DivideByZeroException Can not divide by zero.
Negate()
static Complex AForge.Math.Complex.Negate (Complex a) inline static
Negates a complex number.
Parameters
a A Complex instance.
Returns
Returns new Complex instance containing the negated values.
References AForge.Math.Complex.Complex().
ApproxEqual() [1/2]
static bool AForge.Math.Complex.ApproxEqual (Complex a, Complex b) inline static
Tests whether two complex numbers are approximately equal using default tolerance value.
Parameters
a A Complex instance.
b A Complex instance.
Returns
Return true if the two vectors are approximately equal or false otherwise.
The default tolerance value, which is used for the test, equals to 8.8817841970012523233891E-16.
ApproxEqual() [2/2]
static bool AForge.Math.Complex.ApproxEqual (Complex a, Complex b, double tolerance) inline static
Tests whether two complex numbers are approximately equal given a tolerance value.
Parameters
a A Complex instance.
b A Complex instance.
tolerance The tolerance value used to test approximate equality.
The default tolerance value, which is used for the test, equals to 8.8817841970012523233891E-16.
References AForge.Math.Complex.Im, and AForge.Math.Complex.Re.
Parse()
static Complex AForge.Math.Complex.Parse (string s) inline static
Converts the specified string to its Complex equivalent.
Parameters
s A string representation of a complex number.
Returns
Returns new Complex instance that represents the complex number specified by the s parameter.
Exceptions
FormatException String representation of the complex number is not correctly formatted.
Referenced by AForge.Math.Complex.TryParse().
TryParse()
static bool AForge.Math.Complex.TryParse (string s, out Complex result) inline static
Try to convert the specified string to its Complex equivalent.
Parameters
s A string representation of a complex number.
Parameters
result Complex instance to output the result to.
Returns
Returns boolean value that indicates if the parse was successful or not.
References AForge.Math.Complex.Complex(), and AForge.Math.Complex.Parse().
Sqrt()
static Complex AForge.Math.Complex.Sqrt (Complex a) inline static
Calculates square root of a complex number.
Parameters
a A Complex instance.
Returns
Returns new Complex instance containing the square root of the specified complex number.
References AForge.Math.Complex.Im, AForge.Math.Complex.Re, and AForge.Math.Complex.Zero.
Log()
static Complex AForge.Math.Complex.Log (Complex a) inline static
Calculates natural (base e) logarithm of a complex number.
Parameters
a A Complex instance.
Returns
Returns new Complex instance containing the natural logarithm of the specified complex number.
References AForge.Math.Complex.Im, AForge.Math.Complex.Re, and AForge.Math.Complex.Zero.
Exp()
static Complex AForge.Math.Complex.Exp (Complex a) inline static
Calculates exponent (e raised to the specified power) of a complex number.
Parameters
a A Complex instance.
Returns
Returns new Complex instance containing the exponent of the specified complex number.
References AForge.Math.Complex.Im, AForge.Math.Complex.Re, and AForge.Math.Complex.Zero.
Sin()
static Complex AForge.Math.Complex.Sin (Complex a) inline static
Calculates Sine value of the complex number.
Parameters
a A Complex instance.
Returns
Returns new Complex instance containing the Sine value of the specified complex number.
References AForge.Math.Complex.Im, AForge.Math.Complex.Re, and AForge.Math.Complex.Zero.
Cos()
static Complex AForge.Math.Complex.Cos (Complex a) inline static
Calculates Cosine value of the complex number.
Parameters
a A Complex instance.
Returns
Returns new Complex instance containing the Cosine value of the specified complex number.
References AForge.Math.Complex.Im, AForge.Math.Complex.Re, and AForge.Math.Complex.Zero.
Tan()
static Complex AForge.Math.Complex.Tan (Complex a) inline static
Calculates Tangent value of the complex number.
Parameters
a A Complex instance.
Returns
Returns new Complex instance containing the Tangent value of the specified complex number.
References AForge.Math.Complex.Im, AForge.Math.Complex.Re, and AForge.Math.Complex.Zero.
GetHashCode()
override int AForge.Math.Complex.GetHashCode () inline
Returns the hashcode for this instance.
Returns
A 32-bit signed integer hash code.
Equals()
override bool AForge.Math.Complex.Equals (object obj) inline
Returns a value indicating whether this instance is equal to the specified object.
Parameters
obj An object to compare to this instance.
Returns
Returns true if obj is a Complex and has the same values as this instance or false otherwise.
References AForge.Math.Complex.Complex().
ToString()
override string AForge.Math.Complex.ToString () inline
Returns a string representation of this object.
Returns
A string representation of this object.
References AForge.Math.Complex.Im, and AForge.Math.Complex.Re.
operator==()
static bool AForge.Math.Complex.operator== (Complex u, Complex v) inline static
Tests whether two specified complex numbers are equal.
Parameters
u The left-hand complex number.
v The right-hand complex number.
Returns
Returns true if the two complex numbers are equal or false otherwise.
operator!=()
static bool AForge.Math.Complex.operator!= (Complex u, Complex v) inline static
Tests whether two specified complex numbers are not equal.
Parameters
u The left-hand complex number.
v The right-hand complex number.
Returns
Returns true if the two complex numbers are not equal or false otherwise.
operator-() [1/4]
static Complex AForge.Math.Complex.operator- (Complex a) inline static
Negates the complex number.
Parameters
a A Complex instance.
Returns
Returns new Complex instance containing the negated values.
operator+() [1/3]
static Complex AForge.Math.Complex.operator+ (Complex a, Complex b) inline static
Adds two complex numbers.
Parameters
a A Complex instance.
b A Complex instance.
Returns
Returns new Complex instance containing the sum.
operator+() [2/3]
static Complex AForge.Math.Complex.operator+ (Complex a, double s) inline static
Adds a complex number and a scalar value.
Parameters
a A Complex instance.
s A scalar value.
Returns
Returns new Complex instance containing the sum.
References AForge.Math.Complex.Add().
operator+() [3/3]
static Complex AForge.Math.Complex.operator+ (double s, Complex a) inline static
Adds a complex number and a scalar value.
Parameters
a A Complex instance.
s A scalar value.
Returns
Returns new Complex instance containing the sum.
References AForge.Math.Complex.Add().
operator-() [2/4]
static Complex AForge.Math.Complex.operator- (Complex a, Complex b) inline static
Subtracts one complex number from another complex number.
Parameters
a A Complex instance.
b A Complex instance.
Returns
Returns new Complex instance containing the difference.
References AForge.Math.Complex.Subtract().
operator-() [3/4]
static Complex AForge.Math.Complex.operator- (Complex a, double s) inline static
Subtracts a scalar value from a complex number.
Parameters
a A Complex instance.
s A scalar value.
Returns
Returns new Complex instance containing the difference.
References AForge.Math.Complex.Subtract().
operator-() [4/4]
static Complex AForge.Math.Complex.operator- (double s, Complex a) inline static
Subtracts a complex number from a scalar value.
Parameters
s A scalar value.
a A Complex instance.
Returns
Returns new Complex instance containing the difference.
References AForge.Math.Complex.Subtract().
operator*() [1/3]
static Complex AForge.Math.Complex.operator* (Complex a, Complex b) inline static
Multiplies two complex numbers.
Parameters
a A Complex instance.
b A Complex instance.
Returns
Returns new Complex instance containing the result of multiplication.
References AForge.Math.Complex.Multiply().
operator*() [2/3]
static Complex AForge.Math.Complex.operator* (double s, Complex a) inline static
Multiplies a complex number by a scalar value.
Parameters
s A scalar value.
a A Complex instance.
Returns
Returns new Complex instance containing the result of multiplication.
References AForge.Math.Complex.Multiply().
operator*() [3/3]
static Complex AForge.Math.Complex.operator* (Complex a, double s) inline static
Multiplies a complex number by a scalar value.
Parameters
a A Complex instance.
s A scalar value.
Returns
Returns new Complex instance containing the result of multiplication.
References AForge.Math.Complex.Multiply().
operator/() [1/3]
static Complex AForge.Math.Complex.operator/ (Complex a, Complex b) inline static
Divides one complex number by another complex number.
Parameters
a A Complex instance.
b A Complex instance.
Returns
A new Complex instance containing the result.
Returns new Complex instance containing the result of division.
References AForge.Math.Complex.Divide().
operator/() [2/3]
static Complex AForge.Math.Complex.operator/ (Complex a, double s) inline static
Divides a complex number by a scalar value.
Parameters
a A Complex instance.
s A scalar value.
Returns
Returns new Complex instance containing the result of division.
References AForge.Math.Complex.Divide().
operator/() [3/3]
static Complex AForge.Math.Complex.operator/ (double s, Complex a) inline static
Divides a scalar value by a complex number.
Parameters
a A Complex instance.
s A scalar value.
Returns
Returns new Complex instance containing the result of division.
References AForge.Math.Complex.Divide().
operator Complex() [1/2]
static AForge.Math.Complex.operator Complex (float value) inline explicit static
Converts from a single-precision real number to a complex number.
Parameters
value Single-precision real number to convert to complex number.
Returns
Returns new Complex instance containing complex number with real part initialized to the specified value.
operator Complex() [2/2]
static AForge.Math.Complex.operator Complex (double value) inline explicit static
Converts from a double-precision real number to a complex number.
Parameters
value Double-precision real number to convert to complex number.
Returns
Returns new Complex instance containing complex number with real part initialized to the specified value.
References AForge.Math.Complex.Complex().
Clone() [1/2]
object ICloneable. AForge.Math.Complex.Clone () inline
Creates an exact copy of this Complex object.
Returns
Returns clone of the complex number.
Clone() [2/2]
Complex AForge.Math.Complex.Clone () inline
Creates an exact copy of this Complex object.
Returns
Returns clone of the complex number.
References AForge.Math.Complex.Complex().
GetObjectData()
void AForge.Math.Complex.GetObjectData (SerializationInfo info, StreamingContext context) inline
Populates a SerializationInfo with the data needed to serialize the target object.
Parameters
info The SerializationInfo to populate with data.
context The destination (see StreamingContext) for this serialization.
Member Data Documentation
Re
double AForge.Math.Complex.Re
Real part of the complex number.
Referenced by AForge.Math.Complex.Add(), AForge.Imaging.ComplexFilters.FrequencyFilter.Apply(), AForge.Math.Complex.ApproxEqual(), AForge.Imaging.ComplexImage.BackwardFourierTransform(), AForge.Math.Complex.Cos(), AForge.Math.FourierTransform.DFT(), AForge.Math.FourierTransform.DFT2(), AForge.Math.Complex.Divide(), AForge.Math.Complex.Exp(), AForge.Math.FourierTransform.FFT(), AForge.Imaging.ComplexImage.ForwardFourierTransform(), AForge.Imaging.ComplexImage.FromBitmap(), AForge.Math.Complex.Log(), AForge.Math.Complex.Multiply(), AForge.Math.Complex.Sin(), AForge.Math.Complex.Sqrt(), AForge.Math.Complex.Subtract(), AForge.Math.Complex.Tan(), and AForge.Math.Complex.ToString().
Im
double AForge.Math.Complex.Im
Imaginary part of the complex number.
Referenced by AForge.Math.Complex.Add(), AForge.Imaging.ComplexFilters.FrequencyFilter.Apply(), AForge.Math.Complex.ApproxEqual(), AForge.Imaging.ComplexImage.BackwardFourierTransform(), AForge.Math.Complex.Cos(), AForge.Math.FourierTransform.DFT(), AForge.Math.FourierTransform.DFT2(), AForge.Math.Complex.Divide(), AForge.Math.Complex.Exp(), AForge.Math.FourierTransform.FFT(), AForge.Imaging.ComplexImage.ForwardFourierTransform(), AForge.Math.Complex.Log(), AForge.Math.Complex.Multiply(), AForge.Math.Complex.Sin(), AForge.Math.Complex.Sqrt(), AForge.Math.Complex.Subtract(), AForge.Math.Complex.Tan(), and AForge.Math.Complex.ToString().
Zero
readonly Complex AForge.Math.Complex.Zero = new Complex(0, 0) static
A double-precision complex number that represents zero.
Referenced by AForge.Math.Complex.Cos(), AForge.Math.FourierTransform.DFT(), AForge.Math.FourierTransform.DFT2(), AForge.Math.Complex.Exp(), AForge.Math.Complex.Log(), AForge.Math.Complex.Sin(), AForge.Math.Complex.Sqrt(), and AForge.Math.Complex.Tan().
One
readonly Complex AForge.Math.Complex.One = new Complex(1, 0) static
A double-precision complex number that represents one.
I
readonly Complex AForge.Math.Complex.I = new Complex(0, 1) static
A double-precision complex number that represents the squere root of (-1).
Property Documentation
Magnitude
double AForge.Math.Complex.Magnitude get
Magnitude value of the complex number.
Magnitude of the complex number, which equals to Sqrt(Re * Re + Im * Im).
Referenced by AForge.Imaging.ComplexImage.ToBitmap().
Phase
double AForge.Math.Complex.Phase get
Phase value of the complex number.
Phase of the complex number, which equals to Atan(Im / Re).
SquaredMagnitude
double AForge.Math.Complex.SquaredMagnitude get
Squared magnitude value of the complex number.
The documentation for this struct was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Math/Complex.cs