Doc: IGLib EXTENDED: NUnit.Framework.Internal.MinimumDurationResultTests Class Reference
NUnit.Framework.Internal.MinimumDurationResultTests Class Reference
Public Member Functions
void TestResultHasMinimumDuration ()
Public Member Functions inherited from NUnit.Framework.Internal.TestResultTests
void SetUp ()
void TestResultBasicInfo ()
void SuiteResultBasicInfo ()
void TestResultXmlNodeBasicInfo ()
void SuiteResultXmlNodeBasicInfo ()
Protected Member Functions
override void SimulateTestRun ()
Properties
override ResultState ResultState [get]
Properties inherited from NUnit.Framework.Internal.TestResultTests
virtual ResultState ResultState [get]
virtual string ReasonNodeName [get]
Additional Inherited Members
Protected Attributes inherited from NUnit.Framework.Internal.TestResultTests
TestResult testResult
TestResult suiteResult
TestMethod test
double expectedDuration
DateTime expectedStart
DateTime expectedEnd
Member Function Documentation
SimulateTestRun()
override void NUnit.Framework.Internal.MinimumDurationResultTests.SimulateTestRun () inline protected virtual
Implements NUnit.Framework.Internal.TestResultTests.
References NUnit.Framework.Internal.TestResult.AddResult(), NUnit.Framework.Internal.TestResult.AssertCount, NUnit.Framework.Internal.TestResult.Duration, NUnit.Framework.Internal.TestResult.EndTime, NUnit.Framework.Internal.TestResultTests.expectedDuration, NUnit.Framework.Internal.TestResultTests.expectedEnd, NUnit.Framework.Internal.TestResultTests.expectedStart, NUnit.Framework.Internal.TestResult.SetResult(), NUnit.Framework.Internal.TestResult.StartTime, NUnit.Framework.Interfaces.ResultState.Success, NUnit.Framework.Internal.TestResultTests.suiteResult, and NUnit.Framework.Internal.TestResultTests.testResult.
TestResultHasMinimumDuration()
void NUnit.Framework.Internal.MinimumDurationResultTests.TestResultHasMinimumDuration () inline
References NUnit.Framework.Internal.TestResult.Duration, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestResultTests.suiteResult, NUnit.Framework.Internal.TestResultTests.testResult, and NUnit.Framework.Assert.That().
Property Documentation
ResultState
override ResultState NUnit.Framework.Internal.MinimumDurationResultTests.ResultState get protected
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/TestResultTests.cs