Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLARFB Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLARFB Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLARFB (LSAME lsame, DCOPY dcopy, DGEMM dgemm, DTRMM dtrmm)
DLARFB ()
void Run (string SIDE, string TRANS, string DIRECT, string STOREV, int M, int N, int K, double[] V, int offset_v, int LDV, double[] T, int offset_t, int LDT, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work, int LDWORK)
Private Attributes
LSAME _lsame
DCOPY _dcopy
DGEMM _dgemm
DTRMM _dtrmm
Static Private Attributes
const double ONE = 1.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLARFB applies a real block reflector H or its transpose H' to a real m by n matrix C, from either the left or the right.
/summary>
Constructor & Destructor Documentation
DLARFB() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLARFB.DLARFB (LSAME lsame, DCOPY dcopy, DGEMM dgemm, DTRMM dtrmm) inline
DLARFB() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLARFB.DLARFB () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLARFB.Run (string SIDE, string TRANS, string DIRECT, string STOREV, int M, int N, int K, double[] V, int offset_v, int LDV, double[] T, int offset_t, int LDT, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work, int LDWORK) inline
Purpose
DLARFB applies a real block reflector H or its transpose H' to a real m by n matrix C, from either the left or the right.
/summary>
Parameters
SIDE (input) CHARACTER*1 = 'L': apply H or H' from the Left = 'R': apply H or H' from the Right /param>
Parameters
TRANS (input) CHARACTER*1 = 'N': apply H (No transpose) = 'T': apply H' (Transpose) /param>
Parameters
DIRECT (input) CHARACTER*1 Indicates how H is formed from a product of elementary reflectors = 'F': H = H(1) H(2) . . . H(k) (Forward) = 'B': H = H(k) . . . H(2) H(1) (Backward) /param>
Parameters
STOREV (input) CHARACTER*1 Indicates how the vectors which define the elementary reflectors are stored: = 'C': Columnwise = 'R': Rowwise /param>
Parameters
M (input) INTEGER The number of rows of the matrix C. /param>
Parameters
N (input) INTEGER The number of columns of the matrix C. /param>
Parameters
K (input) INTEGER The order of the matrix T (= the number of elementary reflectors whose product defines the block reflector). /param>
Parameters
V (input) DOUBLE PRECISION array, dimension (LDV,K) if STOREV = 'C' (LDV,M) if STOREV = 'R' and SIDE = 'L' (LDV,N) if STOREV = 'R' and SIDE = 'R' The matrix V. See further details. /param>
Parameters
LDV (input) INTEGER The leading dimension of the array V. If STOREV = 'C' and SIDE = 'L', LDV .GE. max(1,M); if STOREV = 'C' and SIDE = 'R', LDV .GE. max(1,N); if STOREV = 'R', LDV .GE. K. /param>
Parameters
T (input) DOUBLE PRECISION array, dimension (LDT,K) The triangular k by k matrix T in the representation of the block reflector. /param>
Parameters
LDT (input) INTEGER The leading dimension of the array T. LDT .GE. K. /param>
Parameters
C (input/output) DOUBLE PRECISION array, dimension (LDC,N) On entry, the m by n matrix C. On exit, C is overwritten by H*C or H'*C or C*H or C*H'. /param>
Parameters
LDC (input) INTEGER The leading dimension of the array C. LDA .GE. max(1,M). /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (LDWORK,K) /param>
Parameters
LDWORK (input) INTEGER The leading dimension of the array WORK. If SIDE = 'L', LDWORK .GE. max(1,N); if SIDE = 'R', LDWORK .GE. max(1,M). /param>
References DotNumerics.FortranLibrary.FortranLib.Copy(), DotNumerics.LinearAlgebra.CSLapack.DLARFB.ONE, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), and DotNumerics.LinearAlgebra.CSLapack.DTRMM.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGELQF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGERQF.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGLQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGQL.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEHRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMQL.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMLQ.Run(), and DotNumerics.LinearAlgebra.CSLapack.DORMRQ.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLARFB._lsame private
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLARFB._dcopy private
_dgemm
DGEMM DotNumerics.LinearAlgebra.CSLapack.DLARFB._dgemm private
_dtrmm
DTRMM DotNumerics.LinearAlgebra.CSLapack.DLARFB._dtrmm private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLARFB.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLARFB.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlarfb.cs