Doc: IGLib EXTENDED: XimeaSample.MainForm Class Reference
XimeaSample.MainForm Class Reference
Public Member Functions
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void MainForm_Load (object sender, EventArgs e)
void MainForm_FormClosing (object sender, FormClosingEventArgs e)
void EnableConnectionControls (bool enable)
void connectButton_Click (object sender, EventArgs e)
void disconnectButton_Click (object sender, EventArgs e)
void CloseCamera ()
void timer_Tick (object sender, EventArgs e)
void widthUpDown_ValueChanged (object sender, EventArgs e)
void heightUpDown_ValueChanged (object sender, EventArgs e)
void exposureUpDown_ValueChanged (object sender, EventArgs e)
void gainUpDown_ValueChanged (object sender, EventArgs e)
void offsetXUpDown_ValueChanged (object sender, EventArgs e)
void offsetYUpDown_ValueChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
XimeaVideoSource videoSource = null
Stopwatch stopWatch = null
System.ComponentModel.IContainer components = null
Required designer variable.
AForge.Controls.VideoSourcePlayer videoSourcePlayer
System.Windows.Forms.StatusStrip statusStrip
System.Windows.Forms.Panel topPanel
System.Windows.Forms.Panel mainPanel
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.Label label1
System.Windows.Forms.Button disconnectButton
System.Windows.Forms.Button connectButton
System.Windows.Forms.ComboBox deviceCombo
System.Windows.Forms.ToolStripStatusLabel fpsLabel
System.Windows.Forms.ToolStripStatusLabel spareLabel
System.Windows.Forms.Timer timer
System.Windows.Forms.TextBox typeBox
System.Windows.Forms.TextBox snBox
System.Windows.Forms.TextBox nameBox
System.Windows.Forms.Label label4
System.Windows.Forms.Label label3
System.Windows.Forms.Label label2
System.Windows.Forms.NumericUpDown exposureUpDown
System.Windows.Forms.Label label5
System.Windows.Forms.NumericUpDown heightUpDown
System.Windows.Forms.Label label8
System.Windows.Forms.NumericUpDown widthUpDown
System.Windows.Forms.Label label7
System.Windows.Forms.NumericUpDown gainUpDown
System.Windows.Forms.Label label6
System.Windows.Forms.NumericUpDown offsetYUpDown
System.Windows.Forms.Label label9
System.Windows.Forms.NumericUpDown offsetXUpDown
System.Windows.Forms.Label label10
Constructor & Destructor Documentation
MainForm()
XimeaSample.MainForm.MainForm () inline
References XimeaSample.MainForm.InitializeComponent().
Member Function Documentation
MainForm_Load()
void XimeaSample.MainForm.MainForm_Load (object sender, EventArgs e) inline private
References AForge.Video.Ximea.XimeaCamera.CamerasCount, XimeaSample.MainForm.connectButton, XimeaSample.MainForm.deviceCombo, and XimeaSample.MainForm.EnableConnectionControls().
Referenced by XimeaSample.MainForm.InitializeComponent().
MainForm_FormClosing()
void XimeaSample.MainForm.MainForm_FormClosing (object sender, FormClosingEventArgs e) inline private
References XimeaSample.MainForm.CloseCamera().
Referenced by XimeaSample.MainForm.InitializeComponent().
EnableConnectionControls()
void XimeaSample.MainForm.EnableConnectionControls (bool enable) inline private
References XimeaSample.MainForm.connectButton, XimeaSample.MainForm.deviceCombo, XimeaSample.MainForm.disconnectButton, XimeaSample.MainForm.exposureUpDown, XimeaSample.MainForm.gainUpDown, XimeaSample.MainForm.heightUpDown, XimeaSample.MainForm.offsetXUpDown, XimeaSample.MainForm.offsetYUpDown, and XimeaSample.MainForm.widthUpDown.
Referenced by XimeaSample.MainForm.connectButton_Click(), XimeaSample.MainForm.disconnectButton_Click(), and XimeaSample.MainForm.MainForm_Load().
connectButton_Click()
void XimeaSample.MainForm.connectButton_Click (object sender, EventArgs e) inline private
References XimeaSample.MainForm.CloseCamera(), XimeaSample.MainForm.deviceCombo, AForge.Video.Ximea.CameraParameter.DeviceName, AForge.Video.Ximea.CameraParameter.DeviceSerialNumber, AForge.Video.Ximea.CameraParameter.DeviceType, XimeaSample.MainForm.EnableConnectionControls(), AForge.Video.Ximea.CameraParameter.ExposureMax, AForge.Video.Ximea.CameraParameter.ExposureMin, XimeaSample.MainForm.exposureUpDown, AForge.Video.Ximea.CameraParameter.Gain, AForge.Video.Ximea.CameraParameter.GainMax, AForge.Video.Ximea.CameraParameter.GainMin, XimeaSample.MainForm.gainUpDown, AForge.Video.Ximea.XimeaVideoSource.GetParamFloat(), AForge.Video.Ximea.XimeaVideoSource.GetParamInt(), AForge.Video.Ximea.XimeaVideoSource.GetParamString(), AForge.Video.Ximea.CameraParameter.HeightMax, AForge.Video.Ximea.CameraParameter.HeightMin, XimeaSample.MainForm.heightUpDown, XimeaSample.MainForm.nameBox, XimeaSample.MainForm.snBox, AForge.Video.Ximea.XimeaVideoSource.Start(), XimeaSample.MainForm.stopWatch, XimeaSample.MainForm.timer, XimeaSample.MainForm.typeBox, XimeaSample.MainForm.videoSource, XimeaSample.MainForm.videoSourcePlayer, AForge.Video.Ximea.CameraParameter.WidthMax, AForge.Video.Ximea.CameraParameter.WidthMin, and XimeaSample.MainForm.widthUpDown.
Referenced by XimeaSample.MainForm.InitializeComponent().
disconnectButton_Click()
void XimeaSample.MainForm.disconnectButton_Click (object sender, EventArgs e) inline private
References XimeaSample.MainForm.CloseCamera(), and XimeaSample.MainForm.EnableConnectionControls().
Referenced by XimeaSample.MainForm.InitializeComponent().
CloseCamera()
void XimeaSample.MainForm.CloseCamera () inline private
References AForge.Video.Ximea.XimeaVideoSource.SignalToStop(), XimeaSample.MainForm.timer, XimeaSample.MainForm.videoSource, XimeaSample.MainForm.videoSourcePlayer, and AForge.Video.Ximea.XimeaVideoSource.WaitForStop().
Referenced by XimeaSample.MainForm.connectButton_Click(), XimeaSample.MainForm.disconnectButton_Click(), and XimeaSample.MainForm.MainForm_FormClosing().
timer_Tick()
void XimeaSample.MainForm.timer_Tick (object sender, EventArgs e) inline private
References XimeaSample.MainForm.fpsLabel, AForge.Video.Ximea.XimeaVideoSource.FramesReceived, XimeaSample.MainForm.stopWatch, and XimeaSample.MainForm.videoSource.
Referenced by XimeaSample.MainForm.InitializeComponent().
widthUpDown_ValueChanged()
void XimeaSample.MainForm.widthUpDown_ValueChanged (object sender, EventArgs e) inline private
References XimeaSample.MainForm.offsetXUpDown, AForge.Video.Ximea.XimeaVideoSource.SetParam(), XimeaSample.MainForm.videoSource, AForge.Video.Ximea.CameraParameter.Width, and XimeaSample.MainForm.widthUpDown.
Referenced by XimeaSample.MainForm.InitializeComponent().
heightUpDown_ValueChanged()
void XimeaSample.MainForm.heightUpDown_ValueChanged (object sender, EventArgs e) inline private
References AForge.Video.Ximea.CameraParameter.Height, XimeaSample.MainForm.heightUpDown, XimeaSample.MainForm.offsetYUpDown, AForge.Video.Ximea.XimeaVideoSource.SetParam(), and XimeaSample.MainForm.videoSource.
Referenced by XimeaSample.MainForm.InitializeComponent().
exposureUpDown_ValueChanged()
void XimeaSample.MainForm.exposureUpDown_ValueChanged (object sender, EventArgs e) inline private
References AForge.Video.Ximea.CameraParameter.Exposure, XimeaSample.MainForm.exposureUpDown, AForge.Video.Ximea.XimeaVideoSource.FrameInterval, AForge.Video.Ximea.CameraParameter.FramerateMax, AForge.Video.Ximea.XimeaVideoSource.FramesReceived, AForge.Video.Ximea.XimeaVideoSource.GetParamFloat(), AForge.Video.Ximea.XimeaVideoSource.SetParam(), XimeaSample.MainForm.spareLabel, XimeaSample.MainForm.stopWatch, and XimeaSample.MainForm.videoSource.
Referenced by XimeaSample.MainForm.InitializeComponent().
gainUpDown_ValueChanged()
void XimeaSample.MainForm.gainUpDown_ValueChanged (object sender, EventArgs e) inline private
References AForge.Video.Ximea.CameraParameter.Gain, XimeaSample.MainForm.gainUpDown, AForge.Video.Ximea.XimeaVideoSource.SetParam(), and XimeaSample.MainForm.videoSource.
Referenced by XimeaSample.MainForm.InitializeComponent().
offsetXUpDown_ValueChanged()
void XimeaSample.MainForm.offsetXUpDown_ValueChanged (object sender, EventArgs e) inline private
References AForge.Video.Ximea.CameraParameter.OffsetX, XimeaSample.MainForm.offsetXUpDown, AForge.Video.Ximea.XimeaVideoSource.SetParam(), and XimeaSample.MainForm.videoSource.
Referenced by XimeaSample.MainForm.InitializeComponent().
offsetYUpDown_ValueChanged()
void XimeaSample.MainForm.offsetYUpDown_ValueChanged (object sender, EventArgs e) inline private
References AForge.Video.Ximea.CameraParameter.OffsetY, XimeaSample.MainForm.offsetYUpDown, AForge.Video.Ximea.XimeaVideoSource.SetParam(), and XimeaSample.MainForm.videoSource.
Referenced by XimeaSample.MainForm.InitializeComponent().
Dispose()
override void XimeaSample.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References XimeaSample.MainForm.components.
InitializeComponent()
void XimeaSample.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References XimeaSample.MainForm.components, XimeaSample.MainForm.connectButton, XimeaSample.MainForm.connectButton_Click(), XimeaSample.MainForm.deviceCombo, XimeaSample.MainForm.disconnectButton, XimeaSample.MainForm.disconnectButton_Click(), XimeaSample.MainForm.exposureUpDown, XimeaSample.MainForm.exposureUpDown_ValueChanged(), XimeaSample.MainForm.fpsLabel, XimeaSample.MainForm.gainUpDown, XimeaSample.MainForm.gainUpDown_ValueChanged(), XimeaSample.MainForm.groupBox1, XimeaSample.MainForm.heightUpDown, XimeaSample.MainForm.heightUpDown_ValueChanged(), XimeaSample.MainForm.label1, XimeaSample.MainForm.label10, XimeaSample.MainForm.label2, XimeaSample.MainForm.label3, XimeaSample.MainForm.label4, XimeaSample.MainForm.label5, XimeaSample.MainForm.label6, XimeaSample.MainForm.label7, XimeaSample.MainForm.label8, XimeaSample.MainForm.label9, XimeaSample.MainForm.MainForm_FormClosing(), XimeaSample.MainForm.MainForm_Load(), XimeaSample.MainForm.mainPanel, XimeaSample.MainForm.nameBox, XimeaSample.MainForm.offsetXUpDown, XimeaSample.MainForm.offsetXUpDown_ValueChanged(), XimeaSample.MainForm.offsetYUpDown, XimeaSample.MainForm.offsetYUpDown_ValueChanged(), XimeaSample.MainForm.snBox, XimeaSample.MainForm.spareLabel, XimeaSample.MainForm.statusStrip, XimeaSample.MainForm.timer, XimeaSample.MainForm.timer_Tick(), XimeaSample.MainForm.topPanel, XimeaSample.MainForm.typeBox, XimeaSample.MainForm.videoSourcePlayer, XimeaSample.MainForm.widthUpDown, and XimeaSample.MainForm.widthUpDown_ValueChanged().
Referenced by XimeaSample.MainForm.MainForm().
Member Data Documentation
videoSource
XimeaVideoSource XimeaSample.MainForm.videoSource = null private
Referenced by XimeaSample.MainForm.CloseCamera(), XimeaSample.MainForm.connectButton_Click(), XimeaSample.MainForm.exposureUpDown_ValueChanged(), XimeaSample.MainForm.gainUpDown_ValueChanged(), XimeaSample.MainForm.heightUpDown_ValueChanged(), XimeaSample.MainForm.offsetXUpDown_ValueChanged(), XimeaSample.MainForm.offsetYUpDown_ValueChanged(), XimeaSample.MainForm.timer_Tick(), and XimeaSample.MainForm.widthUpDown_ValueChanged().
stopWatch
Stopwatch XimeaSample.MainForm.stopWatch = null private
Referenced by XimeaSample.MainForm.connectButton_Click(), XimeaSample.MainForm.exposureUpDown_ValueChanged(), and XimeaSample.MainForm.timer_Tick().
components
System.ComponentModel.IContainer XimeaSample.MainForm.components = null private
Required designer variable.
Referenced by XimeaSample.MainForm.Dispose(), and XimeaSample.MainForm.InitializeComponent().
videoSourcePlayer
AForge.Controls.VideoSourcePlayer XimeaSample.MainForm.videoSourcePlayer private
Referenced by XimeaSample.MainForm.CloseCamera(), XimeaSample.MainForm.connectButton_Click(), and XimeaSample.MainForm.InitializeComponent().
statusStrip
System.Windows.Forms.StatusStrip XimeaSample.MainForm.statusStrip private
Referenced by XimeaSample.MainForm.InitializeComponent().
topPanel
System.Windows.Forms.Panel XimeaSample.MainForm.topPanel private
Referenced by XimeaSample.MainForm.InitializeComponent().
mainPanel
System.Windows.Forms.Panel XimeaSample.MainForm.mainPanel private
Referenced by XimeaSample.MainForm.InitializeComponent().
groupBox1
System.Windows.Forms.GroupBox XimeaSample.MainForm.groupBox1 private
Referenced by XimeaSample.MainForm.InitializeComponent().
label1
System.Windows.Forms.Label XimeaSample.MainForm.label1 private
Referenced by XimeaSample.MainForm.InitializeComponent().
disconnectButton
System.Windows.Forms.Button XimeaSample.MainForm.disconnectButton private
Referenced by XimeaSample.MainForm.EnableConnectionControls(), and XimeaSample.MainForm.InitializeComponent().
connectButton
System.Windows.Forms.Button XimeaSample.MainForm.connectButton private
Referenced by XimeaSample.MainForm.EnableConnectionControls(), XimeaSample.MainForm.InitializeComponent(), and XimeaSample.MainForm.MainForm_Load().
deviceCombo
System.Windows.Forms.ComboBox XimeaSample.MainForm.deviceCombo private
Referenced by XimeaSample.MainForm.connectButton_Click(), XimeaSample.MainForm.EnableConnectionControls(), XimeaSample.MainForm.InitializeComponent(), and XimeaSample.MainForm.MainForm_Load().
fpsLabel
System.Windows.Forms.ToolStripStatusLabel XimeaSample.MainForm.fpsLabel private
Referenced by XimeaSample.MainForm.InitializeComponent(), and XimeaSample.MainForm.timer_Tick().
spareLabel
System.Windows.Forms.ToolStripStatusLabel XimeaSample.MainForm.spareLabel private
Referenced by XimeaSample.MainForm.exposureUpDown_ValueChanged(), and XimeaSample.MainForm.InitializeComponent().
timer
System.Windows.Forms.Timer XimeaSample.MainForm.timer private
Referenced by XimeaSample.MainForm.CloseCamera(), XimeaSample.MainForm.connectButton_Click(), and XimeaSample.MainForm.InitializeComponent().
typeBox
System.Windows.Forms.TextBox XimeaSample.MainForm.typeBox private
Referenced by XimeaSample.MainForm.connectButton_Click(), and XimeaSample.MainForm.InitializeComponent().
snBox
System.Windows.Forms.TextBox XimeaSample.MainForm.snBox private
Referenced by XimeaSample.MainForm.connectButton_Click(), and XimeaSample.MainForm.InitializeComponent().
nameBox
System.Windows.Forms.TextBox XimeaSample.MainForm.nameBox private
Referenced by XimeaSample.MainForm.connectButton_Click(), and XimeaSample.MainForm.InitializeComponent().
label4
System.Windows.Forms.Label XimeaSample.MainForm.label4 private
Referenced by XimeaSample.MainForm.InitializeComponent().
label3
System.Windows.Forms.Label XimeaSample.MainForm.label3 private
Referenced by XimeaSample.MainForm.InitializeComponent().
label2
System.Windows.Forms.Label XimeaSample.MainForm.label2 private
Referenced by XimeaSample.MainForm.InitializeComponent().
exposureUpDown
System.Windows.Forms.NumericUpDown XimeaSample.MainForm.exposureUpDown private
Referenced by XimeaSample.MainForm.connectButton_Click(), XimeaSample.MainForm.EnableConnectionControls(), XimeaSample.MainForm.exposureUpDown_ValueChanged(), and XimeaSample.MainForm.InitializeComponent().
label5
System.Windows.Forms.Label XimeaSample.MainForm.label5 private
Referenced by XimeaSample.MainForm.InitializeComponent().
heightUpDown
System.Windows.Forms.NumericUpDown XimeaSample.MainForm.heightUpDown private
Referenced by XimeaSample.MainForm.connectButton_Click(), XimeaSample.MainForm.EnableConnectionControls(), XimeaSample.MainForm.heightUpDown_ValueChanged(), and XimeaSample.MainForm.InitializeComponent().
label8
System.Windows.Forms.Label XimeaSample.MainForm.label8 private
Referenced by XimeaSample.MainForm.InitializeComponent().
widthUpDown
System.Windows.Forms.NumericUpDown XimeaSample.MainForm.widthUpDown private
Referenced by XimeaSample.MainForm.connectButton_Click(), XimeaSample.MainForm.EnableConnectionControls(), XimeaSample.MainForm.InitializeComponent(), and XimeaSample.MainForm.widthUpDown_ValueChanged().
label7
System.Windows.Forms.Label XimeaSample.MainForm.label7 private
Referenced by XimeaSample.MainForm.InitializeComponent().
gainUpDown
System.Windows.Forms.NumericUpDown XimeaSample.MainForm.gainUpDown private
Referenced by XimeaSample.MainForm.connectButton_Click(), XimeaSample.MainForm.EnableConnectionControls(), XimeaSample.MainForm.gainUpDown_ValueChanged(), and XimeaSample.MainForm.InitializeComponent().
label6
System.Windows.Forms.Label XimeaSample.MainForm.label6 private
Referenced by XimeaSample.MainForm.InitializeComponent().
offsetYUpDown
System.Windows.Forms.NumericUpDown XimeaSample.MainForm.offsetYUpDown private
Referenced by XimeaSample.MainForm.EnableConnectionControls(), XimeaSample.MainForm.heightUpDown_ValueChanged(), XimeaSample.MainForm.InitializeComponent(), and XimeaSample.MainForm.offsetYUpDown_ValueChanged().
label9
System.Windows.Forms.Label XimeaSample.MainForm.label9 private
Referenced by XimeaSample.MainForm.InitializeComponent().
offsetXUpDown
System.Windows.Forms.NumericUpDown XimeaSample.MainForm.offsetXUpDown private
Referenced by XimeaSample.MainForm.EnableConnectionControls(), XimeaSample.MainForm.InitializeComponent(), XimeaSample.MainForm.offsetXUpDown_ValueChanged(), and XimeaSample.MainForm.widthUpDown_ValueChanged().
label10
System.Windows.Forms.Label XimeaSample.MainForm.label10 private
Referenced by XimeaSample.MainForm.InitializeComponent().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Video/Ximea Sample/MainForm.cs
shelldev/lib_ann/aforge.net/Samples/Video/Ximea Sample/MainForm.Designer.cs