Doc: IGLib EXTENDED: NUnit.Framework.Constraints.EqualTests Class Reference
NUnit.Framework.Constraints.EqualTests Class Reference
Classes
class SomeClass
Public Member Functions
void FailedStringMatchShowsFailurePosition ()
void LongStringsAreTruncated ()
void LongStringsAreTruncatedAtBothEndsIfNecessary ()
void LongStringsAreTruncatedAtFrontEndIfNecessary ()
void CheckExceptionMessage (Exception ex)
void TestPropertyWithPrivateSetter ()
Static Private Attributes
static readonly string testString = "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
Member Function Documentation
FailedStringMatchShowsFailurePosition()
void NUnit.Framework.Constraints.EqualTests.FailedStringMatchShowsFailurePosition () inline
References NUnit.Framework.Constraints.EqualTests.CheckExceptionMessage(), and NUnit.Framework.Assert.Throws().
LongStringsAreTruncated()
void NUnit.Framework.Constraints.EqualTests.LongStringsAreTruncated () inline
References NUnit.Framework.Constraints.EqualTests.CheckExceptionMessage(), NUnit.Framework.Constraints.EqualTests.testString, and NUnit.Framework.Assert.Throws().
LongStringsAreTruncatedAtBothEndsIfNecessary()
void NUnit.Framework.Constraints.EqualTests.LongStringsAreTruncatedAtBothEndsIfNecessary () inline
References NUnit.Framework.Constraints.EqualTests.CheckExceptionMessage(), NUnit.Framework.Constraints.EqualTests.testString, and NUnit.Framework.Assert.Throws().
LongStringsAreTruncatedAtFrontEndIfNecessary()
void NUnit.Framework.Constraints.EqualTests.LongStringsAreTruncatedAtFrontEndIfNecessary () inline
References NUnit.Framework.Constraints.EqualTests.CheckExceptionMessage(), NUnit.Framework.Constraints.EqualTests.testString, and NUnit.Framework.Assert.Throws().
CheckExceptionMessage()
void NUnit.Framework.Constraints.EqualTests.CheckExceptionMessage (Exception ex) inline
References NUnit.Framework.Assert.Fail(), NUnit.Env.NewLine, and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Constraints.EqualTests.FailedStringMatchShowsFailurePosition(), NUnit.Framework.Constraints.EqualTests.LongStringsAreTruncated(), NUnit.Framework.Constraints.EqualTests.LongStringsAreTruncatedAtBothEndsIfNecessary(), and NUnit.Framework.Constraints.EqualTests.LongStringsAreTruncatedAtFrontEndIfNecessary().
TestPropertyWithPrivateSetter()
void NUnit.Framework.Constraints.EqualTests.TestPropertyWithPrivateSetter () inline
References NUnit.Framework.Constraints.EqualTests.SomeClass.BrokenProp, NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
Member Data Documentation
testString
readonly string NUnit.Framework.Constraints.EqualTests.testString = "abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789" static private
Referenced by NUnit.Framework.Constraints.EqualTests.LongStringsAreTruncated(), NUnit.Framework.Constraints.EqualTests.LongStringsAreTruncatedAtBothEndsIfNecessary(), and NUnit.Framework.Constraints.EqualTests.LongStringsAreTruncatedAtFrontEndIfNecessary().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/EqualTest.cs