Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAED7 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAED7 Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAED7 (DGEMM dgemm, DLAED8 dlaed8, DLAED9 dlaed9, DLAEDA dlaeda, DLAMRG dlamrg, XERBLA xerbla)
DLAED7 ()
void Run (int ICOMPQ, int N, int QSIZ, int TLVLS, int CURLVL, int CURPBM, ref double[] D, int offset_d, ref double[] Q, int offset_q, int LDQ, ref int[] INDXQ, int offset_indxq, ref double RHO, int CUTPNT, ref double[] QSTORE, int offset_qstore, ref int[] QPTR, int offset_qptr, ref int[] PRMPTR, int offset_prmptr, ref int[] PERM, int offset_perm, ref int[] GIVPTR, int offset_givptr, ref int[] GIVCOL, int offset_givcol, ref double[] GIVNUM, int offset_givnum, ref double[] WORK, int offset_work, ref int[] IWORK, int offset_iwork, ref int INFO)
Private Attributes
DGEMM _dgemm
DLAED8 _dlaed8
DLAED9 _dlaed9
DLAEDA _dlaeda
DLAMRG _dlamrg
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E0
const double ZERO = 0.0E0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAED7 computes the updated eigensystem of a diagonal matrix after modification by a rank-one symmetric matrix. This routine is used only for the eigenproblem which requires all eigenvalues and optionally eigenvectors of a dense symmetric matrix that has been reduced to tridiagonal form. DLAED1 handles the case in which all eigenvalues and eigenvectors of a symmetric tridiagonal matrix are desired.
T = Q(in) (D(in) + RHO * Z*Z') Q'(in) = Q(out) * D(out) * Q'(out)
where Z = Q'u, u is a vector of length N with ones in the CUTPNT and CUTPNT + 1 th elements and zeros elsewhere.
The eigenvectors of the original matrix are stored in Q, and the eigenvalues are in D. The algorithm consists of three stages:
The first stage consists of deflating the size of the problem when there are multiple eigenvalues or if there is a zero in the Z vector. For each such occurence the dimension of the secular equation problem is reduced by one. This stage is performed by the routine DLAED8.
The second stage consists of calculating the updated eigenvalues. This is done by finding the roots of the secular equation via the routine DLAED4 (as called by DLAED9). This routine also calculates the eigenvectors of the current problem.
The final stage consists of computing the updated eigenvectors directly using the updated eigenvalues. The eigenvectors for the current problem are multiplied with the eigenvectors from the overall problem.
/summary>
Constructor & Destructor Documentation
DLAED7() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAED7.DLAED7 (DGEMM dgemm, DLAED8 dlaed8, DLAED9 dlaed9, DLAEDA dlaeda, DLAMRG dlamrg, XERBLA xerbla) inline
DLAED7() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAED7.DLAED7 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAED7.Run (int ICOMPQ, int N, int QSIZ, int TLVLS, int CURLVL, int CURPBM, ref double[] D, int offset_d, ref double[] Q, int offset_q, int LDQ, ref int[] INDXQ, int offset_indxq, ref double RHO, int CUTPNT, ref double[] QSTORE, int offset_qstore, ref int[] QPTR, int offset_qptr, ref int[] PRMPTR, int offset_prmptr, ref int[] PERM, int offset_perm, ref int[] GIVPTR, int offset_givptr, ref int[] GIVCOL, int offset_givcol, ref double[] GIVNUM, int offset_givnum, ref double[] WORK, int offset_work, ref int[] IWORK, int offset_iwork, ref int INFO) inline
Purpose
DLAED7 computes the updated eigensystem of a diagonal matrix after modification by a rank-one symmetric matrix. This routine is used only for the eigenproblem which requires all eigenvalues and optionally eigenvectors of a dense symmetric matrix that has been reduced to tridiagonal form. DLAED1 handles the case in which all eigenvalues and eigenvectors of a symmetric tridiagonal matrix are desired.
T = Q(in) (D(in) + RHO * Z*Z') Q'(in) = Q(out) * D(out) * Q'(out)
where Z = Q'u, u is a vector of length N with ones in the CUTPNT and CUTPNT + 1 th elements and zeros elsewhere.
The eigenvectors of the original matrix are stored in Q, and the eigenvalues are in D. The algorithm consists of three stages:
The first stage consists of deflating the size of the problem when there are multiple eigenvalues or if there is a zero in the Z vector. For each such occurence the dimension of the secular equation problem is reduced by one. This stage is performed by the routine DLAED8.
The second stage consists of calculating the updated eigenvalues. This is done by finding the roots of the secular equation via the routine DLAED4 (as called by DLAED9). This routine also calculates the eigenvectors of the current problem.
The final stage consists of computing the updated eigenvectors directly using the updated eigenvalues. The eigenvectors for the current problem are multiplied with the eigenvectors from the overall problem.
/summary>
Parameters
ICOMPQ (input) INTEGER = 0: Compute eigenvalues only. = 1: Compute eigenvectors of original dense symmetric matrix also. On entry, Q contains the orthogonal matrix used to reduce the original matrix to tridiagonal form. /param>
Parameters
N (input) INTEGER The dimension of the symmetric tridiagonal matrix. N .GE. 0. /param>
Parameters
QSIZ (input) INTEGER The dimension of the orthogonal matrix used to reduce the full matrix to tridiagonal form. QSIZ .GE. N if ICOMPQ = 1. /param>
Parameters
TLVLS (input) INTEGER The total number of merging levels in the overall divide and conquer tree. /param>
Parameters
CURLVL (input) INTEGER The current level in the overall merge routine, 0 .LE. CURLVL .LE. TLVLS. /param>
Parameters
CURPBM (input) INTEGER The current problem in the current level in the overall merge routine (counting from upper left to lower right). /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension (N) On entry, the eigenvalues of the rank-1-perturbed matrix. On exit, the eigenvalues of the repaired matrix. /param>
Parameters
Q (input/output) DOUBLE PRECISION array, dimension (LDQ, N) On entry, the eigenvectors of the rank-1-perturbed matrix. On exit, the eigenvectors of the repaired tridiagonal matrix. /param>
Parameters
LDQ (input) INTEGER The leading dimension of the array Q. LDQ .GE. max(1,N). /param>
Parameters
INDXQ (output) INTEGER array, dimension (N) The permutation which will reintegrate the subproblem just solved back into sorted order, i.e., D(INDXQ(I = 1, N)) will be in ascending order. /param>
Parameters
RHO (input) DOUBLE PRECISION The subdiagonal element used to create the rank-1 modification. /param>
Parameters
CUTPNT (input) INTEGER Contains the location of the last eigenvalue in the leading sub-matrix. min(1,N) .LE. CUTPNT .LE. N. /param>
Parameters
QSTORE (input/output) DOUBLE PRECISION array, dimension (N**2+1) Stores eigenvectors of submatrices encountered during divide and conquer, packed together. QPTR points to beginning of the submatrices. /param>
Parameters
QPTR (input/output) INTEGER array, dimension (N+2) List of indices pointing to beginning of submatrices stored in QSTORE. The submatrices are numbered starting at the bottom left of the divide and conquer tree, from left to right and bottom to top. /param>
Parameters
PRMPTR (input) INTEGER array, dimension (N lg N) Contains a list of pointers which indicate where in PERM a level's permutation is stored. PRMPTR(i+1) - PRMPTR(i) indicates the size of the permutation and also the size of the full, non-deflated problem. /param>
Parameters
PERM (input) INTEGER array, dimension (N lg N) Contains the permutations (from deflation and sorting) to be applied to each eigenblock. /param>
Parameters
GIVPTR (input) INTEGER array, dimension (N lg N) Contains a list of pointers which indicate where in GIVCOL a level's Givens rotations are stored. GIVPTR(i+1) - GIVPTR(i) indicates the number of Givens rotations. /param>
Parameters
GIVCOL (input) INTEGER array, dimension (2, N lg N) Each pair of numbers indicates a pair of columns to take place in a Givens rotation. /param>
Parameters
GIVNUM (input) DOUBLE PRECISION array, dimension (2, N lg N) Each number indicates the S value to be used in the corresponding Givens rotation. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (3*N+QSIZ*N) /param>
Parameters
IWORK (workspace) INTEGER array, dimension (4*N) /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. .GT. 0: if INFO = 1, an eigenvalue did not converge /param>
References DotNumerics.LinearAlgebra.CSLapack.DLAED7.ONE, DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMRG.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED9.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAEDA.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED8.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAED7.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED0.Run().
Member Data Documentation
_dgemm
DGEMM DotNumerics.LinearAlgebra.CSLapack.DLAED7._dgemm private
_dlaed8
DLAED8 DotNumerics.LinearAlgebra.CSLapack.DLAED7._dlaed8 private
_dlaed9
DLAED9 DotNumerics.LinearAlgebra.CSLapack.DLAED7._dlaed9 private
_dlaeda
DLAEDA DotNumerics.LinearAlgebra.CSLapack.DLAED7._dlaeda private
_dlamrg
DLAMRG DotNumerics.LinearAlgebra.CSLapack.DLAED7._dlamrg private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLAED7._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAED7.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED7.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAED7.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED7.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlaed7.cs