Doc: IGLib EXTENDED: NUnit.Framework.Constraints.ConstraintBuilder Class Reference
NUnit.Framework.Constraints.ConstraintBuilder Class Reference
ConstraintBuilder maintains the stacks that are used in processing a ConstraintExpression. An OperatorStack is used to hold operators that are waiting for their operands to be reorganized. a ConstraintStack holds input constraints as well as the results of each operator applied.
Classes
class ConstraintStack
ConstraintStack is a type-safe stack for holding Constraints
class OperatorStack
OperatorStack is a type-safe stack for holding ConstraintOperators
Public Member Functions
ConstraintBuilder ()
Initializes a new instance of the ConstraintBuilder class.
void Append (ConstraintOperator op)
Appends the specified operator to the expression by first reducing the operator stack and then pushing the new operator on the stack.
void Append (Constraint constraint)
Appends the specified constraint to the expression by pushing it on the constraint stack.
IConstraint Resolve ()
Resolves this instance, returning a Constraint. If the Builder is not currently in a resolvable state, an exception is thrown.
Properties
bool IsResolvable [get]
Gets a value indicating whether this instance is resolvable.
Private Member Functions
void SetTopOperatorRightContext (object rightContext)
Sets the top operator right context.
void ReduceOperatorStack (int targetPrecedence)
Reduces the operator stack until the topmost item precedence is greater than or equal to the target precedence.
Private Attributes
readonly OperatorStack ops
readonly ConstraintStack constraints
object lastPushed
Detailed Description
ConstraintBuilder maintains the stacks that are used in processing a ConstraintExpression. An OperatorStack is used to hold operators that are waiting for their operands to be reorganized. a ConstraintStack holds input constraints as well as the results of each operator applied.
Constructor & Destructor Documentation
ConstraintBuilder()
NUnit.Framework.Constraints.ConstraintBuilder.ConstraintBuilder () inline
Initializes a new instance of the ConstraintBuilder class.
Member Function Documentation
Append() [1/2]
void NUnit.Framework.Constraints.ConstraintBuilder.Append (ConstraintOperator op) inline
Appends the specified operator to the expression by first reducing the operator stack and then pushing the new operator on the stack.
Parameters
op The operator to push.
References NUnit.Framework.Constraints.ConstraintBuilder.lastPushed, NUnit.Framework.Constraints.ConstraintOperator.LeftContext, NUnit.Framework.Constraints.ConstraintOperator.LeftPrecedence, NUnit.Framework.Constraints.ConstraintBuilder.ops, NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack.Push(), NUnit.Framework.Constraints.ConstraintBuilder.ReduceOperatorStack(), and NUnit.Framework.Constraints.ConstraintBuilder.SetTopOperatorRightContext().
Referenced by NUnit.Framework.Constraints.ConstraintExpression.Append().
Append() [2/2]
void NUnit.Framework.Constraints.ConstraintBuilder.Append (Constraint constraint) inline
Appends the specified constraint to the expression by pushing it on the constraint stack.
Parameters
constraint The constraint to push.
References NUnit.Framework.Constraints.Constraint.Builder, NUnit.Framework.Constraints.ConstraintBuilder.constraints, NUnit.Framework.Constraints.ConstraintBuilder.lastPushed, NUnit.Framework.Constraints.ConstraintBuilder.ConstraintStack.Push(), and NUnit.Framework.Constraints.ConstraintBuilder.SetTopOperatorRightContext().
SetTopOperatorRightContext()
void NUnit.Framework.Constraints.ConstraintBuilder.SetTopOperatorRightContext (object rightContext) inline private
Sets the top operator right context.
Parameters
rightContext The right context.
References NUnit.Framework.Constraints.ConstraintOperator.LeftPrecedence, NUnit.Framework.Constraints.ConstraintBuilder.ops, NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack.Pop(), NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack.Push(), NUnit.Framework.Constraints.ConstraintBuilder.ReduceOperatorStack(), NUnit.Framework.Constraints.ConstraintOperator.RightContext, and NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack.Top.
Referenced by NUnit.Framework.Constraints.ConstraintBuilder.Append().
ReduceOperatorStack()
void NUnit.Framework.Constraints.ConstraintBuilder.ReduceOperatorStack (int targetPrecedence) inline private
Reduces the operator stack until the topmost item precedence is greater than or equal to the target precedence.
Parameters
targetPrecedence The target precedence.
References NUnit.Framework.Constraints.ConstraintBuilder.constraints, NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack.Empty, NUnit.Framework.Constraints.ConstraintBuilder.ops, NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack.Pop(), NUnit.Framework.Constraints.ConstraintOperator.Reduce(), NUnit.Framework.Constraints.ConstraintOperator.RightPrecedence, and NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack.Top.
Referenced by NUnit.Framework.Constraints.ConstraintBuilder.Append(), and NUnit.Framework.Constraints.ConstraintBuilder.SetTopOperatorRightContext().
Resolve()
IConstraint NUnit.Framework.Constraints.ConstraintBuilder.Resolve () inline
Resolves this instance, returning a Constraint. If the Builder is not currently in a resolvable state, an exception is thrown.
Returns
The resolved constraint
Implements NUnit.Framework.Constraints.IResolveConstraint.
References NUnit.Framework.Constraints.ConstraintBuilder.constraints, NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack.Empty, NUnit.Framework.Constraints.ConstraintBuilder.IsResolvable, NUnit.Framework.Constraints.ConstraintBuilder.ops, NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack.Pop(), NUnit.Framework.Constraints.ConstraintBuilder.ConstraintStack.Pop(), and NUnit.Framework.Constraints.ConstraintOperator.Reduce().
Referenced by NUnit.Framework.Constraints.Constraint.After(), NUnit.Framework.Constraints.ResolvableConstraintExpression.Resolve(), NUnit.Framework.Constraints.Constraint.Resolve(), and NUnit.Framework.Constraints.ConstraintExpression.ToString().
Member Data Documentation
ops
readonly OperatorStack NUnit.Framework.Constraints.ConstraintBuilder.ops private
Referenced by NUnit.Framework.Constraints.ConstraintBuilder.Append(), NUnit.Framework.Constraints.ConstraintBuilder.ReduceOperatorStack(), NUnit.Framework.Constraints.ConstraintBuilder.Resolve(), and NUnit.Framework.Constraints.ConstraintBuilder.SetTopOperatorRightContext().
constraints
readonly ConstraintStack NUnit.Framework.Constraints.ConstraintBuilder.constraints private
Referenced by NUnit.Framework.Constraints.ConstraintBuilder.Append(), NUnit.Framework.Constraints.ConstraintBuilder.ReduceOperatorStack(), and NUnit.Framework.Constraints.ConstraintBuilder.Resolve().
lastPushed
object NUnit.Framework.Constraints.ConstraintBuilder.lastPushed private
Referenced by NUnit.Framework.Constraints.ConstraintBuilder.Append().
Property Documentation
IsResolvable
bool NUnit.Framework.Constraints.ConstraintBuilder.IsResolvable get private
Gets a value indicating whether this instance is resolvable.
true if this instance is resolvable; otherwise, false.
Referenced by NUnit.Framework.Constraints.ConstraintBuilder.Resolve().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Constraints/ConstraintBuilder.cs