Doc: IGLib EXTENDED: IG.Neural.Forms.NeuralPredictionControl Class Reference
IG.Neural.Forms.NeuralPredictionControl Class Reference
Control for making predictions of output values based on ANN model.
Public Member Functions
NeuralPredictionControl ()
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
NeuralPredictionControl ()
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
NeuralPredictionControl ()
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
NeuralPredictionControl ()
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
INeuralModelContainer _neuralModelContainerControl
Properties
INeuralModel NeuralModel [get, protected set]
Neural network - based model.
INeuralApproximator TrainedNetwork [get]
Traint artificial neural network.
InputOutputDataDefiniton NeuralDataDefinition [get]
Neural data definition.
Properties inherited from IG.Neural.INeuralModelContainer
INeuralModel NeuralModel [get]
Artificial neural network - based model.
Private Member Functions
void btnPredict_Click (object sender, EventArgs e)
void OnInputValueValueChanged (object sender, DataGridViewCellEventArgs e)
Event handler that executes when a value is changed in the input parameters DataGridView. Clears the output values.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void btnPredict_Click (object sender, EventArgs e)
void OnInputValueValueChanged (object sender, DataGridViewCellEventArgs e)
Event handler that executes when a value is changed in the input parameters DataGridView. Clears the output values.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void btnPredict_Click (object sender, EventArgs e)
void OnInputValueValueChanged (object sender, DataGridViewCellEventArgs e)
Event handler that executes when a value is changed in the input parameters DataGridView. Clears the output values.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void btnPredict_Click (object sender, EventArgs e)
void OnInputValueValueChanged (object sender, DataGridViewCellEventArgs e)
Event handler that executes when a value is changed in the input parameters DataGridView. Clears the output values.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
INeuralModel _neuralModel
System.ComponentModel.IContainer components = null
Required designer variable.
NeuralInputControl neuralInputControl1
NeuralOutputControl neuralOutputControl1
System.Windows.Forms.Button btnPredict
System.Windows.Forms.Button btnReset
Detailed Description
Control for making predictions of output values based on ANN model.
$A Igor Apr13;
Constructor & Destructor Documentation
NeuralPredictionControl() [1/4]
IG.Neural.Forms.NeuralPredictionControl.NeuralPredictionControl () inline
References IG.Neural.Forms.NeuralInputControl.GetGridControl(), IG.Neural.Forms.NeuralPredictionControl.InitializeComponent(), IG.Neural.Forms.NeuralPredictionControl.neuralInputControl1, and IG.Neural.Forms.NeuralPredictionControl.OnInputValueValueChanged().
NeuralPredictionControl() [2/4]
IG.Neural.Forms.NeuralPredictionControl.NeuralPredictionControl () inline
References IG.Neural.Forms.NeuralInputControl.GetGridControl(), IG.Neural.Forms.NeuralPredictionControl.InitializeComponent(), IG.Neural.Forms.NeuralPredictionControl.neuralInputControl1, and IG.Neural.Forms.NeuralPredictionControl.OnInputValueValueChanged().
NeuralPredictionControl() [3/4]
IG.Neural.Forms.NeuralPredictionControl.NeuralPredictionControl () inline
References IG.Neural.Forms.NeuralInputControl.GetGridControl(), IG.Neural.Forms.NeuralPredictionControl.InitializeComponent(), IG.Neural.Forms.NeuralPredictionControl.neuralInputControl1, and IG.Neural.Forms.NeuralPredictionControl.OnInputValueValueChanged().
NeuralPredictionControl() [4/4]
IG.Neural.Forms.NeuralPredictionControl.NeuralPredictionControl () inline
References IG.Neural.Forms.NeuralInputControl.GetGridControl(), IG.Neural.Forms.NeuralPredictionControl.InitializeComponent(), IG.Neural.Forms.NeuralPredictionControl.neuralInputControl1, and IG.Neural.Forms.NeuralPredictionControl.OnInputValueValueChanged().
Member Function Documentation
SetNeuralModel() [1/4]
void IG.Neural.Forms.NeuralPredictionControl.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
Implements IG.Neural.INeuralModelContainer.
References IG.Neural.Forms.NeuralPredictionControl.NeuralModel.
btnPredict_Click() [1/4]
void IG.Neural.Forms.NeuralPredictionControl.btnPredict_Click (object sender, EventArgs e) inline private
References IG.Num.IVectorApproximator.CalculateOutput(), IG.Neural.Forms.NeuralPredictionControl.neuralInputControl1, IG.Neural.Forms.NeuralPredictionControl.neuralOutputControl1, IG.Neural.Forms.NeuralOutputControl.SetValues(), IG.Neural.Forms.NeuralPredictionControl.TrainedNetwork, and IG.Neural.Forms.NeuralInputControl.Values.
Referenced by IG.Neural.Forms.NeuralPredictionControl.InitializeComponent().
OnInputValueValueChanged() [1/4]
void IG.Neural.Forms.NeuralPredictionControl.OnInputValueValueChanged (object sender, DataGridViewCellEventArgs e) inline private
Event handler that executes when a value is changed in the input parameters DataGridView. Clears the output values.
Parameters
sender
e
References IG.Neural.Forms.NeuralOutputControl.ClearValues(), and IG.Neural.Forms.NeuralPredictionControl.neuralOutputControl1.
Referenced by IG.Neural.Forms.NeuralPredictionControl.NeuralPredictionControl().
Dispose() [1/4]
override void IG.Neural.Forms.NeuralPredictionControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralPredictionControl.components.
InitializeComponent() [1/4]
void IG.Neural.Forms.NeuralPredictionControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralPredictionControl.btnPredict, IG.Neural.Forms.NeuralPredictionControl.btnPredict_Click(), IG.Neural.Forms.NeuralPredictionControl.btnReset, IG.Neural.Forms.NeuralPredictionControl.neuralInputControl1, and IG.Neural.Forms.NeuralPredictionControl.neuralOutputControl1.
Referenced by IG.Neural.Forms.NeuralPredictionControl.NeuralPredictionControl().
SetNeuralModel() [2/4]
void IG.Neural.Forms.NeuralPredictionControl.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
Implements IG.Neural.INeuralModelContainer.
References IG.Neural.Forms.NeuralPredictionControl.NeuralModel.
btnPredict_Click() [2/4]
void IG.Neural.Forms.NeuralPredictionControl.btnPredict_Click (object sender, EventArgs e) inline private
References IG.Num.IVectorApproximator.CalculateOutput(), IG.Neural.Forms.NeuralPredictionControl.neuralInputControl1, IG.Neural.Forms.NeuralPredictionControl.neuralOutputControl1, IG.Neural.Forms.NeuralOutputControl.SetValues(), IG.Neural.Forms.NeuralPredictionControl.TrainedNetwork, and IG.Neural.Forms.NeuralInputControl.Values.
OnInputValueValueChanged() [2/4]
void IG.Neural.Forms.NeuralPredictionControl.OnInputValueValueChanged (object sender, DataGridViewCellEventArgs e) inline private
Event handler that executes when a value is changed in the input parameters DataGridView. Clears the output values.
Parameters
sender
e
References IG.Neural.Forms.NeuralOutputControl.ClearValues(), and IG.Neural.Forms.NeuralPredictionControl.neuralOutputControl1.
Dispose() [2/4]
override void IG.Neural.Forms.NeuralPredictionControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralPredictionControl.components.
InitializeComponent() [2/4]
void IG.Neural.Forms.NeuralPredictionControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralPredictionControl.btnPredict, IG.Neural.Forms.NeuralPredictionControl.btnPredict_Click(), IG.Neural.Forms.NeuralPredictionControl.btnReset, IG.Neural.Forms.NeuralPredictionControl.neuralInputControl1, and IG.Neural.Forms.NeuralPredictionControl.neuralOutputControl1.
SetNeuralModel() [3/4]
void IG.Neural.Forms.NeuralPredictionControl.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
Implements IG.Neural.INeuralModelContainer.
References IG.Neural.Forms.NeuralPredictionControl.NeuralModel.
btnPredict_Click() [3/4]
void IG.Neural.Forms.NeuralPredictionControl.btnPredict_Click (object sender, EventArgs e) inline private
References IG.Num.IVectorApproximator.CalculateOutput(), IG.Neural.Forms.NeuralPredictionControl.neuralInputControl1, IG.Neural.Forms.NeuralPredictionControl.neuralOutputControl1, IG.Neural.Forms.NeuralOutputControl.SetValues(), IG.Neural.Forms.NeuralPredictionControl.TrainedNetwork, and IG.Neural.Forms.NeuralInputControl.Values.
OnInputValueValueChanged() [3/4]
void IG.Neural.Forms.NeuralPredictionControl.OnInputValueValueChanged (object sender, DataGridViewCellEventArgs e) inline private
Event handler that executes when a value is changed in the input parameters DataGridView. Clears the output values.
Parameters
sender
e
References IG.Neural.Forms.NeuralOutputControl.ClearValues(), and IG.Neural.Forms.NeuralPredictionControl.neuralOutputControl1.
Dispose() [3/4]
override void IG.Neural.Forms.NeuralPredictionControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralPredictionControl.components.
InitializeComponent() [3/4]
void IG.Neural.Forms.NeuralPredictionControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralPredictionControl.btnPredict, IG.Neural.Forms.NeuralPredictionControl.btnPredict_Click(), IG.Neural.Forms.NeuralPredictionControl.btnReset, IG.Neural.Forms.NeuralPredictionControl.neuralInputControl1, and IG.Neural.Forms.NeuralPredictionControl.neuralOutputControl1.
SetNeuralModel() [4/4]
void IG.Neural.Forms.NeuralPredictionControl.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
Implements IG.Neural.INeuralModelContainer.
References IG.Neural.Forms.NeuralPredictionControl.NeuralModel.
btnPredict_Click() [4/4]
void IG.Neural.Forms.NeuralPredictionControl.btnPredict_Click (object sender, EventArgs e) inline private
References IG.Num.IVectorApproximator.CalculateOutput(), IG.Neural.Forms.NeuralPredictionControl.neuralInputControl1, IG.Neural.Forms.NeuralPredictionControl.neuralOutputControl1, IG.Neural.Forms.NeuralOutputControl.SetValues(), IG.Neural.Forms.NeuralPredictionControl.TrainedNetwork, and IG.Neural.Forms.NeuralInputControl.Values.
OnInputValueValueChanged() [4/4]
void IG.Neural.Forms.NeuralPredictionControl.OnInputValueValueChanged (object sender, DataGridViewCellEventArgs e) inline private
Event handler that executes when a value is changed in the input parameters DataGridView. Clears the output values.
Parameters
sender
e
References IG.Neural.Forms.NeuralOutputControl.ClearValues(), and IG.Neural.Forms.NeuralPredictionControl.neuralOutputControl1.
Dispose() [4/4]
override void IG.Neural.Forms.NeuralPredictionControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralPredictionControl.components.
InitializeComponent() [4/4]
void IG.Neural.Forms.NeuralPredictionControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralPredictionControl.btnPredict, IG.Neural.Forms.NeuralPredictionControl.btnPredict_Click(), IG.Neural.Forms.NeuralPredictionControl.btnReset, IG.Neural.Forms.NeuralPredictionControl.neuralInputControl1, and IG.Neural.Forms.NeuralPredictionControl.neuralOutputControl1.
Member Data Documentation
_neuralModelContainerControl
INeuralModelContainer IG.Neural.Forms.NeuralPredictionControl._neuralModelContainerControl protected
_neuralModel
INeuralModel IG.Neural.Forms.NeuralPredictionControl._neuralModel private
components
System ComponentModel IContainer IG.Neural.Forms.NeuralPredictionControl.components = null private
Required designer variable.
Referenced by IG.Neural.Forms.NeuralPredictionControl.Dispose().
neuralInputControl1
NeuralInputControl IG.Neural.Forms.NeuralPredictionControl.neuralInputControl1 private
Referenced by IG.Neural.Forms.NeuralPredictionControl.btnPredict_Click(), IG.Neural.Forms.NeuralPredictionControl.InitializeComponent(), and IG.Neural.Forms.NeuralPredictionControl.NeuralPredictionControl().
neuralOutputControl1
NeuralOutputControl IG.Neural.Forms.NeuralPredictionControl.neuralOutputControl1 private
Referenced by IG.Neural.Forms.NeuralPredictionControl.btnPredict_Click(), IG.Neural.Forms.NeuralPredictionControl.InitializeComponent(), and IG.Neural.Forms.NeuralPredictionControl.OnInputValueValueChanged().
btnPredict
System Windows Forms Button IG.Neural.Forms.NeuralPredictionControl.btnPredict private
Referenced by IG.Neural.Forms.NeuralPredictionControl.InitializeComponent().
btnReset
System Windows Forms Button IG.Neural.Forms.NeuralPredictionControl.btnReset private
Referenced by IG.Neural.Forms.NeuralPredictionControl.InitializeComponent().
Property Documentation
NeuralModel
INeuralModel IG.Neural.Forms.NeuralPredictionControl.NeuralModel get protected set
Neural network - based model.
Contains data definition and trained neural network approximator.
Referenced by IG.Neural.Forms.NeuralPredictionControl.SetNeuralModel().
TrainedNetwork
INeuralApproximator IG.Neural.Forms.NeuralPredictionControl.TrainedNetwork get
Traint artificial neural network.
Referenced by IG.Neural.Forms.NeuralPredictionControl.btnPredict_Click().
NeuralDataDefinition
InputOutputDataDefiniton IG.Neural.Forms.NeuralPredictionControl.NeuralDataDefinition get
Neural data definition.
The documentation for this class was generated from the following files:
shelldev/extensions/ExtAppAnnApp/ResponseForms/NeuralPredictionControl.cs
shelldev/extensions/ExtAppAnnApp/ResponseForms/NeuralPredictionControl.Designer.cs