Doc: IGLib EXTENDED: Test.FourierTest Class Reference
Test.FourierTest Class Reference
Public Member Functions
void FourierTiming ()
void FourierSpecialCases ()
void FourierInverse ()
void FourierLinearity ()
void FourierParseval ()
void TestMethod1 ()
Static Public Attributes
static int[] sizes = new int[] { 2, 3, 5, 8, 13, 21, 34, 55, 89, 144 }
Member Function Documentation
FourierTiming()
void Test.FourierTest.FourierTiming () inline
FourierSpecialCases()
void Test.FourierTest.FourierSpecialCases () inline
References Meta.Numerics.ComplexMath.Abs(), Meta.Numerics.SignalProcessing.FourierTransformer.InverseTransform(), and Meta.Numerics.SignalProcessing.FourierTransformer.Length.
FourierInverse()
void Test.FourierTest.FourierInverse () inline
References Meta.Numerics.SignalProcessing.FourierTransformer.InverseTransform(), and Test.FourierTest.sizes.
FourierLinearity()
void Test.FourierTest.FourierLinearity () inline
References Test.FourierTest.sizes.
FourierParseval()
void Test.FourierTest.FourierParseval () inline
References Meta.Numerics.Complex.Conjugate, and Test.FourierTest.sizes.
TestMethod1()
void Test.FourierTest.TestMethod1 () inline
References Meta.Numerics.SignalProcessing.FourierTransformer.InverseTransform().
Member Data Documentation
sizes
int [] Test.FourierTest.sizes = new int[] { 2, 3, 5, 8, 13, 21, 34, 55, 89, 144 } static
Referenced by Test.FourierTest.FourierInverse(), Test.FourierTest.FourierLinearity(), and Test.FourierTest.FourierParseval().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/FourierTest.cs