Doc: IGLib EXTENDED: TSP.TSPChromosome Class Reference
TSP.TSPChromosome Class Reference
The chromosome is to solve TSP task (Travailing Salesman Problem).
Public Member Functions
TSPChromosome (double[,] map)
Constructor
override IChromosome CreateNew ()
Create new random chromosome (factory method)
override IChromosome Clone ()
Clone the chromosome
override void Crossover (IChromosome pair)
Crossover operator
Public Member Functions inherited from AForge.Genetic.PermutationChromosome
PermutationChromosome (int length)
Initializes a new instance of the PermutationChromosome class.
override void Generate ()
Generate random chromosome value.
override IChromosome CreateNew ()
Create new random chromosome with same parameters (factory method).
override IChromosome Clone ()
Clone the chromosome.
override void Mutate ()
Mutation operator.
override void Crossover (IChromosome pair)
Crossover operator.
Public Member Functions inherited from AForge.Genetic.ShortArrayChromosome
ShortArrayChromosome (int length)
Initializes a new instance of the ShortArrayChromosome class.
ShortArrayChromosome (int length, int maxValue)
Initializes a new instance of the ShortArrayChromosome class.
override string ToString ()
Get string representation of the chromosome.
override void Generate ()
Generate random chromosome value.
override IChromosome CreateNew ()
Create new random chromosome with same parameters (factory method).
override IChromosome Clone ()
Clone the chromosome.
override void Mutate ()
Mutation operator.
override void Crossover (IChromosome pair)
Crossover operator.
Public Member Functions inherited from AForge.Genetic.ChromosomeBase
void Evaluate (IFitnessFunction function)
Evaluate chromosome with specified fitness function.
int CompareTo (object o)
Compare two chromosomes.
Protected Member Functions
TSPChromosome (TSPChromosome source)
Copy Constructor
Protected Member Functions inherited from AForge.Genetic.PermutationChromosome
PermutationChromosome (PermutationChromosome source)
Initializes a new instance of the PermutationChromosome class.
Protected Member Functions inherited from AForge.Genetic.ShortArrayChromosome
ShortArrayChromosome (ShortArrayChromosome source)
Initializes a new instance of the ShortArrayChromosome class.
Private Member Functions
void CreateChildUsingCrossover (ushort[] parent1, ushort[] parent2, ushort[] child)
Private Attributes
double[,] map = null
Additional Inherited Members
Static Public Attributes inherited from AForge.Genetic.ShortArrayChromosome
const int MaxLength = 65536
Chromosome's maximum length.
Protected Attributes inherited from AForge.Genetic.ShortArrayChromosome
int length
Chromosome's length in number of elements.
int maxValue
Maximum value of chromosome's gene (element).
ushort[] val = null
Chromosome's value.
Protected Attributes inherited from AForge.Genetic.ChromosomeBase
double fitness = 0
Chromosome's fintess value.
Static Protected Attributes inherited from AForge.Genetic.ShortArrayChromosome
static ThreadSafeRandom rand = new ThreadSafeRandom()
Random number generator for chromosoms generation, crossover, mutation, etc.
Properties inherited from AForge.Genetic.ShortArrayChromosome
int Length [get]
Chromosome's length.
ushort[] Value [get]
Chromosome's value.
int MaxValue [get]
Max possible value of single chromosomes element - gene.
Properties inherited from AForge.Genetic.ChromosomeBase
double Fitness [get]
Chromosome's fintess value.
Properties inherited from AForge.Genetic.IChromosome
double Fitness [get]
Chromosome's fintess value.
Detailed Description
The chromosome is to solve TSP task (Travailing Salesman Problem).
Constructor & Destructor Documentation
TSPChromosome() [1/2]
TSP.TSPChromosome.TSPChromosome (double map[,]) inline
Constructor
References TSP.TSPChromosome.map.
Referenced by TSP.TSPChromosome.Clone(), TSP.TSPChromosome.CreateNew(), and TSP.TSPChromosome.Crossover().
TSPChromosome() [2/2]
TSP.TSPChromosome.TSPChromosome (TSPChromosome source) inline protected
Copy Constructor
References TSP.TSPChromosome.map.
Member Function Documentation
CreateNew()
override IChromosome TSP.TSPChromosome.CreateNew () inline virtual
Create new random chromosome (factory method)
Implements AForge.Genetic.ChromosomeBase.
References TSP.TSPChromosome.map, and TSP.TSPChromosome.TSPChromosome().
Clone()
override IChromosome TSP.TSPChromosome.Clone () inline virtual
Clone the chromosome
Implements AForge.Genetic.ChromosomeBase.
References TSP.TSPChromosome.TSPChromosome().
Crossover()
override void TSP.TSPChromosome.Crossover (IChromosome pair) inline virtual
Crossover operator
Implements AForge.Genetic.ChromosomeBase.
References TSP.TSPChromosome.CreateChildUsingCrossover(), AForge.Genetic.ShortArrayChromosome.length, TSP.TSPChromosome.TSPChromosome(), and AForge.Genetic.ShortArrayChromosome.val.
CreateChildUsingCrossover()
void TSP.TSPChromosome.CreateChildUsingCrossover (ushort[] parent1, ushort[] parent2, ushort[] child) inline private
References AForge.Genetic.ShortArrayChromosome.length, TSP.TSPChromosome.map, AForge.ThreadSafeRandom.Next(), and AForge.Genetic.ShortArrayChromosome.rand.
Referenced by TSP.TSPChromosome.Crossover().
Member Data Documentation
map
double [,] TSP.TSPChromosome.map = null private
Referenced by TSP.TSPChromosome.CreateChildUsingCrossover(), TSP.TSPChromosome.CreateNew(), and TSP.TSPChromosome.TSPChromosome().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Samples/Genetic/TSP/TSPChromosome.cs