Doc: IGLib EXTENDED: NUnit.Framework.Interfaces.ITestFilter Interface Reference
NUnit.Framework.Interfaces.ITestFilter Interface Reference
Interface to be implemented by filters applied to tests. The filter applies when running the test, after it has been loaded, since this is the only time an ITest exists.
Public Member Functions
bool Pass (ITest test)
Determine if a particular test passes the filter criteria. Pass may examine the parents and/or descendants of a test, depending on the semantics of the particular filter
bool IsExplicitMatch (ITest test)
Determine if a test matches the filter expicitly. That is, it must be a direct match of the test itself or one of it's children.
Public Member Functions inherited from NUnit.Framework.Interfaces.IXmlNodeBuilder
TNode ToXml (bool recursive)
Returns a TNode representing the current object.
TNode AddToXml (TNode parentNode, bool recursive)
Returns a TNode representing the current object after adding it as a child of the supplied parent node.
Detailed Description
Interface to be implemented by filters applied to tests. The filter applies when running the test, after it has been loaded, since this is the only time an ITest exists.
Member Function Documentation
Pass()
bool NUnit.Framework.Interfaces.ITestFilter.Pass (ITest test)
Determine if a particular test passes the filter criteria. Pass may examine the parents and/or descendants of a test, depending on the semantics of the particular filter
Parameters
test The test to which the filter is applied
Returns
True if the test passes the filter, otherwise false
Implemented in NUnit.Framework.Internal.TestFilter.EmptyFilter, NUnit.Framework.Internal.TestFilter, NUnit.Framework.Internal.Filters.NotFilter, NUnit.Framework.Internal.Filters.AndFilter, and NUnit.Framework.Internal.Filters.OrFilter.
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.CreateChildWorkItems(), NUnit.Framework.Internal.Filters.OrFilter.Pass(), NUnit.Framework.Internal.Filters.AndFilter.Pass(), and NUnit.Framework.Internal.Execution.CompositeWorkItem.SkipChildren().
IsExplicitMatch()
bool NUnit.Framework.Interfaces.ITestFilter.IsExplicitMatch (ITest test)
Determine if a test matches the filter expicitly. That is, it must be a direct match of the test itself or one of it's children.
Parameters
test The test to which the filter is applied
Returns
True if the test matches the filter explicityly, otherwise false
Implemented in NUnit.Framework.Internal.TestFilter.EmptyFilter, NUnit.Framework.Internal.Filters.NotFilter, and NUnit.Framework.Internal.TestFilter.
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork(), and NUnit.Framework.Internal.Execution.SimpleWorkItem.SimpleWorkItem().
The documentation for this interface was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Interfaces/ITestFilter.cs