Doc: IGLib EXTENDED: IG.MPetekLib.Algorithms.Models.RoughBilliard Class Reference
IG.MPetekLib.Algorithms.Models.RoughBilliard Class Reference
Public Member Functions
RoughBilliard ()
void PropagateRay ()
Propagate the ray from the current to the next point. The current r0 and A0 should already be known. Overwrites the r0 and A0 with the new values.
void FollowATrajectory ()
Follows a trajectory of a billiard ball and writes the results to the list r.
void WriteATrajectoryToFile (int fileNumber)
void WriteStateSpaceTrajectoryToFile (int fileNumber)
void ExploreStateSpace (double initCosGamma, double finalCosGamma, int stepsCosGamma, double initPhi, double finalPhi, int stepsPhi)
Constructs a grid of initial conditions and runs a simulation for each of them.
Properties
double a [get, set]
The amplitude of the boundary's roughness (waviness).
int n [get, set]
The roughness of the boundary.
double[] InitialPointPolar [get, set]
The initial point of the current ray in polar coordinates.
double InitialDirectionAngle [set]
The direction vector of the current ray.
double InitialPhi [get, set]
double InitialCosGamma [get, set]
int FirstScanIntervals [get, set]
The number of intervals on which the presence of a solution is tested.
double AccuracyGoal [get, set]
The accuracy of the bisection.
int NPropagations [get, set]
The number of propagations that the FollowATrajectory() method will execute.
Private Member Functions
double IntersectionFunction (double phi)
Used to calculate the intersections of rays, which don't go through the origin, with the billiard boundary. If this method returns 0, then there is an intersection located at the input polar angle phi.
double RadiusFunction (double phi)
Returns the radius at which the boundary exists at a certain phi.
double K (double phi)
The normalization factor of the tangent and the normal to the boundary.
double Comp1 (double phi)
The x component of the tangent to the boundary.
double Comp2 (double phi)
The y component of the tangent to the boundary.
Private Attributes
double _a = 0.1
The amplitude of the boundary's roughness (waviness).
int _n = 5
The roughness of the boundary.
double[] _r0Cart = new double[2]
The initial point of the current ray.
double[] _r0Polar = new double[2]
The initial point of the current ray in polar coordinates.
double[] _A0Cart = new double[2]
The direction vector of the current ray.
double _initialPhi
double _initialCosGamma
double[] _A1Cart = new double[2]
A temporaray variable.
double[] _r1Cart = new double[2]
The initial point of the next ray. A temporary variable.
double _alpha0
The angle between the ray and the x-axis in case the ray goes through the origin.
List< double[]> _vPolar = new List<double[]>(10)
A list of all the polar coordinates of the intersections between the ray and the boundary.
List< double[]> _vCart = new List<double[]>(10)
A list of all the cartesian coordinates of the intersections between the ray and the boundary.
double _d0
The angular momentum. Also the distance between the current ray and the origin.
double _beta0
The angle between the distance vector and the x-axis.
double[] _n0Cart = new double[2]
The normal vector to the boundary. Points outwards.
int _firstScanIntervals = 10000
The number of intervals on which the presence of a solution is tested.
double intervalWidth
The interval width of the "search for rough positions of the intersections" method.
List< double[]> solutionIntervals = new List<double[]>(10)
The found intervals on which the solution exists.
double firstValue
The values at the start and at the end of the interval.
double secondValue
double leftPoint
The variables used for bisection - searching for precise positions of the solutions.
double midPoint
double rightPoint
double leftValue
double midValue
double rightValue
double _accuracyGoal = 0.000000001
The accuracy of the bisection.
double t
A multiplier used at searching for the closest point in the direction of A.
double chosenT
double _comp1
The x component of the tangent to the boundary.
double _comp2
The y component of the tangent to the boundary.
double _K
The normalization factor of the tangent to the boundary.
double _cosGamma = Double.NaN
The projection of the direction vector on the tangent to the boundary.
int _nPropagations = 500
List< double[]> _r = new List<double[]>(100)
A list of points marking the ray's path.
List< double[]> _stateCoordinates = new List<double[]>(100)
A list of projections of the direction vector on the tangent to the boundary.
Constructor & Destructor Documentation
RoughBilliard()
IG.MPetekLib.Algorithms.Models.RoughBilliard.RoughBilliard () inline
References IG.MPetekLib.Algorithms.Models.RoughBilliard._firstScanIntervals, IG.MPetekLib.Algorithms.Models.RoughBilliard._nPropagations, IG.MPetekLib.Algorithms.Models.RoughBilliard._r, IG.MPetekLib.Algorithms.Models.RoughBilliard._stateCoordinates, and IG.MPetekLib.Algorithms.Models.RoughBilliard.intervalWidth.
Member Function Documentation
IntersectionFunction()
double IG.MPetekLib.Algorithms.Models.RoughBilliard.IntersectionFunction (double phi) inline private
Used to calculate the intersections of rays, which don't go through the origin, with the billiard boundary. If this method returns 0, then there is an intersection located at the input polar angle phi.
Parameters
phi The input polar angle.
Returns
Zero if an intersection is found.
References IG.MPetekLib.Algorithms.Models.RoughBilliard._a, IG.MPetekLib.Algorithms.Models.RoughBilliard._beta0, IG.MPetekLib.Algorithms.Models.RoughBilliard._d0, and IG.MPetekLib.Algorithms.Models.RoughBilliard._n.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
RadiusFunction()
double IG.MPetekLib.Algorithms.Models.RoughBilliard.RadiusFunction (double phi) inline private
Returns the radius at which the boundary exists at a certain phi.
Parameters
phi The phi at which the boundary radius is being calculated.
Returns
The boundary radius.
References IG.MPetekLib.Algorithms.Models.RoughBilliard._a, and IG.MPetekLib.Algorithms.Models.RoughBilliard._n.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.Comp1(), IG.MPetekLib.Algorithms.Models.RoughBilliard.Comp2(), IG.MPetekLib.Algorithms.Models.RoughBilliard.K(), and IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
K()
double IG.MPetekLib.Algorithms.Models.RoughBilliard.K (double phi) inline private
The normalization factor of the tangent and the normal to the boundary.
Parameters
phi The angle coordinate.
References IG.MPetekLib.Algorithms.Models.RoughBilliard._a, IG.MPetekLib.Algorithms.Models.RoughBilliard._n, and IG.MPetekLib.Algorithms.Models.RoughBilliard.RadiusFunction().
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
Comp1()
double IG.MPetekLib.Algorithms.Models.RoughBilliard.Comp1 (double phi) inline private
The x component of the tangent to the boundary.
Parameters
phi The angle coordinate.
References IG.MPetekLib.Algorithms.Models.RoughBilliard._a, IG.MPetekLib.Algorithms.Models.RoughBilliard._n, and IG.MPetekLib.Algorithms.Models.RoughBilliard.RadiusFunction().
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
Comp2()
double IG.MPetekLib.Algorithms.Models.RoughBilliard.Comp2 (double phi) inline private
The y component of the tangent to the boundary.
Parameters
phi The angle coordinate.
References IG.MPetekLib.Algorithms.Models.RoughBilliard._a, IG.MPetekLib.Algorithms.Models.RoughBilliard._n, and IG.MPetekLib.Algorithms.Models.RoughBilliard.RadiusFunction().
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
PropagateRay()
void IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay () inline
Propagate the ray from the current to the next point. The current r0 and A0 should already be known. Overwrites the r0 and A0 with the new values.
References IG.MPetekLib.Algorithms.Models.RoughBilliard._a, IG.MPetekLib.Algorithms.Models.RoughBilliard._A0Cart, IG.MPetekLib.Algorithms.Models.RoughBilliard._A1Cart, IG.MPetekLib.Algorithms.Models.RoughBilliard._accuracyGoal, IG.MPetekLib.Algorithms.Models.RoughBilliard._alpha0, IG.MPetekLib.Algorithms.Models.RoughBilliard._beta0, IG.MPetekLib.Algorithms.Models.RoughBilliard._comp1, IG.MPetekLib.Algorithms.Models.RoughBilliard._comp2, IG.MPetekLib.Algorithms.Models.RoughBilliard._cosGamma, IG.MPetekLib.Algorithms.Models.RoughBilliard._d0, IG.MPetekLib.Algorithms.Models.RoughBilliard._firstScanIntervals, IG.MPetekLib.Algorithms.Models.RoughBilliard._K, IG.MPetekLib.Algorithms.Models.RoughBilliard._n, IG.MPetekLib.Algorithms.Models.RoughBilliard._n0Cart, IG.MPetekLib.Algorithms.Models.RoughBilliard._r0Cart, IG.MPetekLib.Algorithms.Models.RoughBilliard._r0Polar, IG.MPetekLib.Algorithms.Models.RoughBilliard._r1Cart, IG.MPetekLib.Algorithms.Models.RoughBilliard._vCart, IG.MPetekLib.Algorithms.Models.RoughBilliard._vPolar, IG.MPetekLib.Algorithms.Models.RoughBilliard.chosenT, IG.MPetekLib.Algorithms.Models.RoughBilliard.Comp1(), IG.MPetekLib.Algorithms.Models.RoughBilliard.Comp2(), IG.MPetekLib.Algorithms.Models.RoughBilliard.firstValue, IG.MPetekLib.Algorithms.Models.RoughBilliard.IntersectionFunction(), IG.MPetekLib.Algorithms.Models.RoughBilliard.intervalWidth, IG.MPetekLib.Algorithms.Models.RoughBilliard.K(), IG.MPetekLib.Algorithms.Models.RoughBilliard.leftPoint, IG.MPetekLib.Algorithms.Models.RoughBilliard.leftValue, IG.MPetekLib.Algorithms.Models.RoughBilliard.midPoint, IG.MPetekLib.Algorithms.Models.RoughBilliard.midValue, IG.MPetekLib.Algorithms.Models.RoughBilliard.RadiusFunction(), IG.MPetekLib.Algorithms.Models.RoughBilliard.rightPoint, IG.MPetekLib.Algorithms.Models.RoughBilliard.rightValue, IG.MPetekLib.Algorithms.Models.RoughBilliard.secondValue, IG.MPetekLib.Algorithms.Models.RoughBilliard.solutionIntervals, and IG.MPetekLib.Algorithms.Models.RoughBilliard.t.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.FollowATrajectory().
FollowATrajectory()
void IG.MPetekLib.Algorithms.Models.RoughBilliard.FollowATrajectory () inline
Follows a trajectory of a billiard ball and writes the results to the list r.
References IG.MPetekLib.Algorithms.Models.RoughBilliard._cosGamma, IG.MPetekLib.Algorithms.Models.RoughBilliard._n, IG.MPetekLib.Algorithms.Models.RoughBilliard._nPropagations, IG.MPetekLib.Algorithms.Models.RoughBilliard._r, IG.MPetekLib.Algorithms.Models.RoughBilliard._r0Cart, IG.MPetekLib.Algorithms.Models.RoughBilliard._r0Polar, IG.MPetekLib.Algorithms.Models.RoughBilliard._stateCoordinates, and IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.ExploreStateSpace().
WriteATrajectoryToFile()
void IG.MPetekLib.Algorithms.Models.RoughBilliard.WriteATrajectoryToFile (int fileNumber) inline
References IG.MPetekLib.Algorithms.Models.RoughBilliard._r.
WriteStateSpaceTrajectoryToFile()
void IG.MPetekLib.Algorithms.Models.RoughBilliard.WriteStateSpaceTrajectoryToFile (int fileNumber) inline
References IG.MPetekLib.Algorithms.Models.RoughBilliard._stateCoordinates.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.ExploreStateSpace().
ExploreStateSpace()
void IG.MPetekLib.Algorithms.Models.RoughBilliard.ExploreStateSpace (double initCosGamma, double finalCosGamma, int stepsCosGamma, double initPhi, double finalPhi, int stepsPhi) inline
Constructs a grid of initial conditions and runs a simulation for each of them.
///
Parameters
initCosGamma Initial projection of the momentum to the boundary.
finalCosGamma Final projection of the momentum to the boundary.
stepsCosGamma
initPhi
finalPhi
stepsPhi
References IG.MPetekLib.Algorithms.Models.RoughBilliard.FollowATrajectory(), IG.MPetekLib.Algorithms.Models.RoughBilliard.InitialCosGamma, IG.MPetekLib.Algorithms.Models.RoughBilliard.InitialPhi, and IG.MPetekLib.Algorithms.Models.RoughBilliard.WriteStateSpaceTrajectoryToFile().
Referenced by IG.MPetekLib.Application.Scripts._27Billiard.Run().
Member Data Documentation
_a
double IG.MPetekLib.Algorithms.Models.RoughBilliard._a = 0.1 private
The amplitude of the boundary's roughness (waviness).
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.Comp1(), IG.MPetekLib.Algorithms.Models.RoughBilliard.Comp2(), IG.MPetekLib.Algorithms.Models.RoughBilliard.IntersectionFunction(), IG.MPetekLib.Algorithms.Models.RoughBilliard.K(), IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay(), and IG.MPetekLib.Algorithms.Models.RoughBilliard.RadiusFunction().
_n
int IG.MPetekLib.Algorithms.Models.RoughBilliard._n = 5 private
The roughness of the boundary.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.Comp1(), IG.MPetekLib.Algorithms.Models.RoughBilliard.Comp2(), IG.MPetekLib.Algorithms.Models.RoughBilliard.FollowATrajectory(), IG.MPetekLib.Algorithms.Models.RoughBilliard.IntersectionFunction(), IG.MPetekLib.Algorithms.Models.RoughBilliard.K(), IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay(), and IG.MPetekLib.Algorithms.Models.RoughBilliard.RadiusFunction().
_r0Cart
double [] IG.MPetekLib.Algorithms.Models.RoughBilliard._r0Cart = new double[2] private
The initial point of the current ray.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.FollowATrajectory(), and IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
_r0Polar
double [] IG.MPetekLib.Algorithms.Models.RoughBilliard._r0Polar = new double[2] private
The initial point of the current ray in polar coordinates.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.FollowATrajectory(), and IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
_A0Cart
double [] IG.MPetekLib.Algorithms.Models.RoughBilliard._A0Cart = new double[2] private
The direction vector of the current ray.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
_initialPhi
double IG.MPetekLib.Algorithms.Models.RoughBilliard._initialPhi private
_initialCosGamma
double IG.MPetekLib.Algorithms.Models.RoughBilliard._initialCosGamma private
_A1Cart
double [] IG.MPetekLib.Algorithms.Models.RoughBilliard._A1Cart = new double[2] private
A temporaray variable.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
_r1Cart
double [] IG.MPetekLib.Algorithms.Models.RoughBilliard._r1Cart = new double[2] private
The initial point of the next ray. A temporary variable.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
_alpha0
double IG.MPetekLib.Algorithms.Models.RoughBilliard._alpha0 private
The angle between the ray and the x-axis in case the ray goes through the origin.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
_vPolar
List<double[]> IG.MPetekLib.Algorithms.Models.RoughBilliard._vPolar = new List<double[]>(10) private
A list of all the polar coordinates of the intersections between the ray and the boundary.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
_vCart
List<double[]> IG.MPetekLib.Algorithms.Models.RoughBilliard._vCart = new List<double[]>(10) private
A list of all the cartesian coordinates of the intersections between the ray and the boundary.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
_d0
double IG.MPetekLib.Algorithms.Models.RoughBilliard._d0 private
The angular momentum. Also the distance between the current ray and the origin.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.IntersectionFunction(), and IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
_beta0
double IG.MPetekLib.Algorithms.Models.RoughBilliard._beta0 private
The angle between the distance vector and the x-axis.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.IntersectionFunction(), and IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
_n0Cart
double [] IG.MPetekLib.Algorithms.Models.RoughBilliard._n0Cart = new double[2] private
The normal vector to the boundary. Points outwards.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
_firstScanIntervals
int IG.MPetekLib.Algorithms.Models.RoughBilliard._firstScanIntervals = 10000 private
The number of intervals on which the presence of a solution is tested.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay(), and IG.MPetekLib.Algorithms.Models.RoughBilliard.RoughBilliard().
intervalWidth
double IG.MPetekLib.Algorithms.Models.RoughBilliard.intervalWidth private
The interval width of the "search for rough positions of the intersections" method.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay(), and IG.MPetekLib.Algorithms.Models.RoughBilliard.RoughBilliard().
solutionIntervals
List<double[]> IG.MPetekLib.Algorithms.Models.RoughBilliard.solutionIntervals = new List<double[]>(10) private
The found intervals on which the solution exists.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
firstValue
double IG.MPetekLib.Algorithms.Models.RoughBilliard.firstValue private
The values at the start and at the end of the interval.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
secondValue
double IG.MPetekLib.Algorithms.Models.RoughBilliard.secondValue private
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
leftPoint
double IG.MPetekLib.Algorithms.Models.RoughBilliard.leftPoint private
The variables used for bisection - searching for precise positions of the solutions.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
midPoint
double IG.MPetekLib.Algorithms.Models.RoughBilliard.midPoint private
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
rightPoint
double IG.MPetekLib.Algorithms.Models.RoughBilliard.rightPoint private
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
leftValue
double IG.MPetekLib.Algorithms.Models.RoughBilliard.leftValue private
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
midValue
double IG.MPetekLib.Algorithms.Models.RoughBilliard.midValue private
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
rightValue
double IG.MPetekLib.Algorithms.Models.RoughBilliard.rightValue private
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
_accuracyGoal
double IG.MPetekLib.Algorithms.Models.RoughBilliard._accuracyGoal = 0.000000001 private
The accuracy of the bisection.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
t
double IG.MPetekLib.Algorithms.Models.RoughBilliard.t private
A multiplier used at searching for the closest point in the direction of A.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
chosenT
double IG.MPetekLib.Algorithms.Models.RoughBilliard.chosenT private
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
_comp1
double IG.MPetekLib.Algorithms.Models.RoughBilliard._comp1 private
The x component of the tangent to the boundary.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
_comp2
double IG.MPetekLib.Algorithms.Models.RoughBilliard._comp2 private
The y component of the tangent to the boundary.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
_K
double IG.MPetekLib.Algorithms.Models.RoughBilliard._K private
The normalization factor of the tangent to the boundary.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
_cosGamma
double IG.MPetekLib.Algorithms.Models.RoughBilliard._cosGamma = Double.NaN private
The projection of the direction vector on the tangent to the boundary.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.FollowATrajectory(), and IG.MPetekLib.Algorithms.Models.RoughBilliard.PropagateRay().
_nPropagations
int IG.MPetekLib.Algorithms.Models.RoughBilliard._nPropagations = 500 private
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.FollowATrajectory(), and IG.MPetekLib.Algorithms.Models.RoughBilliard.RoughBilliard().
_r
List<double[]> IG.MPetekLib.Algorithms.Models.RoughBilliard._r = new List<double[]>(100) private
A list of points marking the ray's path.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.FollowATrajectory(), IG.MPetekLib.Algorithms.Models.RoughBilliard.RoughBilliard(), and IG.MPetekLib.Algorithms.Models.RoughBilliard.WriteATrajectoryToFile().
_stateCoordinates
List<double[]> IG.MPetekLib.Algorithms.Models.RoughBilliard._stateCoordinates = new List<double[]>(100) private
A list of projections of the direction vector on the tangent to the boundary.
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.FollowATrajectory(), IG.MPetekLib.Algorithms.Models.RoughBilliard.RoughBilliard(), and IG.MPetekLib.Algorithms.Models.RoughBilliard.WriteStateSpaceTrajectoryToFile().
Property Documentation
a
double IG.MPetekLib.Algorithms.Models.RoughBilliard.a get set
The amplitude of the boundary's roughness (waviness).
Referenced by IG.MPetekLib.Application.Scripts._27Billiard.Run().
n
int IG.MPetekLib.Algorithms.Models.RoughBilliard.n get set
The roughness of the boundary.
Referenced by IG.MPetekLib.Application.Scripts._27Billiard.Run().
InitialPointPolar
double [] IG.MPetekLib.Algorithms.Models.RoughBilliard.InitialPointPolar get set
The initial point of the current ray in polar coordinates.
InitialDirectionAngle
double IG.MPetekLib.Algorithms.Models.RoughBilliard.InitialDirectionAngle set
The direction vector of the current ray.
InitialPhi
double IG.MPetekLib.Algorithms.Models.RoughBilliard.InitialPhi get set
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.ExploreStateSpace().
InitialCosGamma
double IG.MPetekLib.Algorithms.Models.RoughBilliard.InitialCosGamma get set
Referenced by IG.MPetekLib.Algorithms.Models.RoughBilliard.ExploreStateSpace().
FirstScanIntervals
int IG.MPetekLib.Algorithms.Models.RoughBilliard.FirstScanIntervals get set
The number of intervals on which the presence of a solution is tested.
AccuracyGoal
double IG.MPetekLib.Algorithms.Models.RoughBilliard.AccuracyGoal get set
The accuracy of the bisection.
NPropagations
int IG.MPetekLib.Algorithms.Models.RoughBilliard.NPropagations get set
The number of propagations that the FollowATrajectory() method will execute.
Referenced by IG.MPetekLib.Application.Scripts._27Billiard.Run().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/Guest_Marko_Petek_Lib/algorithms/Models/RoughBilliard.cs