Doc: IGLib EXTENDED: IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel Class Reference
IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel Class Reference
Classes
class SpinStateCollection
A nested class providing the indexed property functionality for the _spinState list.
Public Member Functions
IsingModel ()
The constructors starts the state list in an extremely ordered state. We also need to instantiate the fake indexed SpinState property.
void TryTurnRandomSpin ()
Tries to turn a random spin in the lattice. If the energy change is positive and the dice roll falls above the exponential curve defined by the beta parameter, the change is discarded.
void SimulatedAnnealingWithPlot ()
Anneals the Ising model while plotting the results.
void SimulatedAnnealing ()
Anneals the Ising model, no plotting.
double ConfigurationEnergy ()
Calculates the configuration energy by accounting for every bond in the lattice. Takes into account the B-vK boundary conditions.
double AverageConfigEnergy ()
Calculates the average configuration energy at a certain temperature.
void AvgConfigEnergyVsTemp (double initTemp, double finalTemp, double nSamples)
Calculates the average configuration energy on a temperature range and writes the results to a file.
double MagMoment ()
Calculates the magnetization by accounting for each spin in the lattice.
double AverageMagMoment ()
Calculates the average magnetization at a certain temperature.
void AvgMagMomentVsTemp (double initTemp, double finalTemp, double nSamples)
Calculates the average magnetization on a temperature range and writes the results to a file.
double AverageSusceptibilityN ()
Calculates the average susceptibility times N at a certain temperature.
void AvgSusceptibilityNVsTemp (double initTemp, double finalTemp, double nSamples)
Calculates the average susceptibility times N on a temperature range and writes the results to a file.
double EnergyVariance ()
Calculates the expected value of energy squared minus square of the expected value of energy.
double AvgEnergyVariance ()
Calculates the average energy variance, used when calculating the specific heat.
void AvgSpecificHeatNVsTemp (double initTemp, double finalTemp, double nSamples)
Calculates the average specific heat times N at a certain temperature range and writes the results to a file.
double OnlineEnergyVariance ()
Calculates the online energy variance.
double AvgOnlineEnergyVariance ()
Calculates the average online energy variance, used when calculating the specific heat.
void AvgSpecificHeatNVsTemp2 (double initTemp, double finalTemp, double nSamples)
Calculates the average specific heat times N at a certain temperature range and writes the results to a file.
Public Member Functions inherited from IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase
PlotZedgraphCurve NewCurveFromPlottableData (PlotterZedGraph plotter, int x, int y)
Creates a new PlotZedgraphCurve object from the available plottable data.
void LoadPlottableDataToCurve (PlotZedgraphCurve curve, int x, int y)
Copies the calculated data to the existing PlotZedgraphCurve object. Enough space must be available on the curve object's list.
Protected Attributes
double _initialBeta = 0.005
double _finalBeta = 30
int _stepsAtTemperature = 5000
int _coolingLevels = 7
double _gamma
The factor for which the inverse temperature beta rises after each cooling level. The inverse alpha, where alpha is the analogous factor asocciated with the gradual fall of the temperature.
int _plotEveryNShifts = 50
Protected Attributes inherited from IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase
string _title
Properties
int LatticeXDim [get, set]
Rectangular lattice's x-dimension.
int LatticeYDim [get, set]
Rectangular lattice's y-dimension.
double Beta [get, set]
The parameter beta of the falling exponential (Boltzmann) distribution. The "inverse" temperature.
double Temperature [get, set]
Temperature is an inverse with beta. Boltzmann constant = 1.
double J [get, set]
Coupling constant between spins: 1 -> paramagnetism (same direction: lower energy), -1 -> diamagnetism.
double H [get, set]
Coupling constant between a spin and the external magnetic field: 1 -> (same direction: lower energy).
int StateChosenSpin [get, set]
The state of the spin that's been chosen by the RNG. This property should make the code more readable.
int StateAboveSpin [get, set]
The state of the spin above the chosen spin. This property should make the code more readable.
int StateBelowSpin [get, set]
The state of the spin below the chosen spin. This property should make the code more readable.
int StateLeftSpin [get, set]
The state of the spin left of the chosen spin. This property should make the code more readable.
int StateRightSpin [get, set]
The state of the spin right of the chosen spin. This property should make the code more readable.
double InitialBeta [get, set]
The initial inverse temperature for the simulated annealing process.
double InitialTemperature [get, set]
The initial temperature for the simulated annealing process.
double FinalBeta [get, set]
The final inverse temperature for the simulated annealing process.
double FinalTemperature [get, set]
The final temperature for the simulated annealing process.
int StepsAtTemperature [get, set]
How many spin turns the method will make at a certain temperature.
int CoolingLevels [get, set]
How granular the cooling will be. Example: T0 = 1000, TN=100, CoolingLevels = 10: 1000, 900, 800, ..., 200, 100. More levels means higher reliability, but also more time wasted.
int PlotEveryNShifts [get, set]
How often the plotting window should refresh. A smaller number means more often and makes it more interesting. However, a bigger number makes the whole calculation much faster.
int NumOfAnnealingsToAvgOver [get, set]
How many terms should be added together before averaging takes place. Used by all the averaging methods.
Properties inherited from IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase
string Title [get, set]
The plottable model's name. Also used as a plot title.
List< double[]> PlottableData [get, set]
The main solution array, which is used by the plotter.
Private Member Functions
void UpdateLatticeRowCurves ()
Used by the main thread. Updates the points shown by the plotting thread to the most recent state.
void ShowPlot ()
This method runs on the plotting thread. Its only job is to display the plotting window.
Private Attributes
List< List< int > > _spinState
SpinStateCollection SpinState
Holds the states (1 or -1) of all the spins in the lattice. Each spin's position in the lattice can be inferred from the indices, since the lattice is rectangular. The indices are cyclic (periodic boundary condition). An indexed property.
List< PlotZedgraphCurve > _latticeRowCurve
A list of all the rows of spins in the spin lattice. Each row is represented by a PlotZedGraphCurve object.
PlotHQ _plothq1
A PlotHQ object used by the plotting thread.
int _latticeXDim = 100
int _latticeYDim = 100
double _beta = 0.3
double _j = 1
double _h = 0
Random _rng = new Random()
An all-purpose RNG.
double _diceRoll
A random real number between 0 and 1. Used for the simulated annealing (Boltzmann) criterion.
int _randomSpinX
The RNG chooses a random spin. This is its x-index.
int _randomSpinY
The RNG chooses a random spin. This is its y-index.
double _energyChange
The difference between the new and the old energy.
readonly object _locker = new object()
A locker for wait/pulse methods.
bool _go = false
A blocking condition for the wait/pulse methods.
int _numOfAnnealingsToAvgOver = 10
Constructor & Destructor Documentation
IsingModel()
IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.IsingModel () inline
The constructors starts the state list in an extremely ordered state. We also need to instantiate the fake indexed SpinState property.
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeXDim, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeYDim, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._spinState, and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SpinState.
Member Function Documentation
UpdateLatticeRowCurves()
void IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.UpdateLatticeRowCurves () inline private
Used by the main thread. Updates the points shown by the plotting thread to the most recent state.
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeRowCurve, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeXDim, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeYDim, and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._spinState.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealingWithPlot().
ShowPlot()
void IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.ShowPlot () inline private
This method runs on the plotting thread. Its only job is to display the plotting window.
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._go, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeRowCurve, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeYDim, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._locker, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._plothq1, IG.Gr.ZedGraphWindow.GraphControl, IG.MPetekLib.Algorithms.Plotting.PlotHQ.Plotter, IG.Gr.PlotterZedGraph.SetBounds(), IG.MPetekLib.Algorithms.Plotting.PlotHQ.ShowPlot(), IG.Gr.PlotterZedGraph.Title, and IG.MPetekLib.Algorithms.Plotting.PlotHQ.Window.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealingWithPlot().
TryTurnRandomSpin()
void IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.TryTurnRandomSpin () inline
Tries to turn a random spin in the lattice. If the energy change is positive and the dice roll falls above the exponential curve defined by the beta parameter, the change is discarded.
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._beta, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._diceRoll, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._energyChange, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._h, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._j, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeXDim, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeYDim, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._randomSpinX, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._randomSpinY, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._rng, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.StateAboveSpin, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.StateBelowSpin, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.StateChosenSpin, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.StateLeftSpin, and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.StateRightSpin.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealing(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealingWithPlot().
SimulatedAnnealingWithPlot()
void IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealingWithPlot () inline
Anneals the Ising model while plotting the results.
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._beta, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._coolingLevels, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._finalBeta, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._gamma, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._go, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._initialBeta, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._locker, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._plotEveryNShifts, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._plothq1, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._stepsAtTemperature, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.ConfigurationEnergy(), IG.MPetekLib.Algorithms.Plotting.PlotHQ.Plotter, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.TryTurnRandomSpin(), IG.Gr.PlotterZedGraph.Update(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.UpdateLatticeRowCurves(), and IG.MPetekLib.Algorithms.Plotting.PlotHQ.Window.
Referenced by IG.MPetekLib.Application.Scripts.CompPhys._03AnnealingIsingModel.Run().
SimulatedAnnealing()
void IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealing () inline
Anneals the Ising model, no plotting.
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._beta, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._coolingLevels, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._finalBeta, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._gamma, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._initialBeta, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._stepsAtTemperature, and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.TryTurnRandomSpin().
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AverageConfigEnergy(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AverageMagMoment(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AverageSusceptibilityN(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgEnergyVariance(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgOnlineEnergyVariance().
ConfigurationEnergy()
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.ConfigurationEnergy () inline
Calculates the configuration energy by accounting for every bond in the lattice. Takes into account the B-vK boundary conditions.
Returns
Current configuration energy.
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._h, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._j, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeXDim, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeYDim, and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SpinState.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AverageConfigEnergy(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealingWithPlot().
AverageConfigEnergy()
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AverageConfigEnergy () inline
Calculates the average configuration energy at a certain temperature.
Returns
Average configuration energy.
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._numOfAnnealingsToAvgOver, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.ConfigurationEnergy(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealing().
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgConfigEnergyVsTemp().
AvgConfigEnergyVsTemp()
void IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgConfigEnergyVsTemp (double initTemp, double finalTemp, double nSamples) inline
Calculates the average configuration energy on a temperature range and writes the results to a file.
Parameters
initTemp Initial temperature.
finalTemp Final temperature.
nSamples The number of samples on the temperature range.
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AverageConfigEnergy(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.FinalTemperature.
Referenced by IG.MPetekLib.Application.Scripts.CompPhys._04IsingAvgEnergy.Run().
MagMoment()
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.MagMoment () inline
Calculates the magnetization by accounting for each spin in the lattice.
Returns
Current magnetization.
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeXDim, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeYDim, and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._spinState.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AverageMagMoment(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AverageSusceptibilityN().
AverageMagMoment()
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AverageMagMoment () inline
Calculates the average magnetization at a certain temperature.
Returns
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._numOfAnnealingsToAvgOver, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.MagMoment(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealing().
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgMagMomentVsTemp().
AvgMagMomentVsTemp()
void IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgMagMomentVsTemp (double initTemp, double finalTemp, double nSamples) inline
Calculates the average magnetization on a temperature range and writes the results to a file.
Parameters
initTemp Initial temperature.
finalTemp Final temperature.
nSamples The number of samples on the temperature range.
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AverageMagMoment(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.FinalTemperature.
AverageSusceptibilityN()
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AverageSusceptibilityN () inline
Calculates the average susceptibility times N at a certain temperature.
Returns
Average susceptibility.
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeXDim, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeYDim, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._numOfAnnealingsToAvgOver, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.FinalTemperature, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.MagMoment(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealing().
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgSusceptibilityNVsTemp().
AvgSusceptibilityNVsTemp()
void IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgSusceptibilityNVsTemp (double initTemp, double finalTemp, double nSamples) inline
Calculates the average susceptibility times N on a temperature range and writes the results to a file.
Parameters
initTemp Initial temperature.
finalTemp Final temperature.
nSamples The number of samples on the temperature range.
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AverageSusceptibilityN(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.FinalTemperature.
EnergyVariance()
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.EnergyVariance () inline
Calculates the expected value of energy squared minus square of the expected value of energy.
Returns
The variance of energy.
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._h, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._j, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeXDim, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeYDim, and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SpinState.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgEnergyVariance().
AvgEnergyVariance()
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgEnergyVariance () inline
Calculates the average energy variance, used when calculating the specific heat.
Returns
Average energy variance.
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._numOfAnnealingsToAvgOver, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.EnergyVariance(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealing().
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgSpecificHeatNVsTemp().
AvgSpecificHeatNVsTemp()
void IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgSpecificHeatNVsTemp (double initTemp, double finalTemp, double nSamples) inline
Calculates the average specific heat times N at a certain temperature range and writes the results to a file.
Parameters
initTemp Initial temperature.
finalTemp Final temperature.
nSamples The number of samples on the temperature range.
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgEnergyVariance(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.FinalTemperature.
OnlineEnergyVariance()
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.OnlineEnergyVariance () inline
Calculates the online energy variance.
Returns
Energy variance.
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._h, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._j, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeXDim, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeYDim, and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SpinState.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgOnlineEnergyVariance().
AvgOnlineEnergyVariance()
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgOnlineEnergyVariance () inline
Calculates the average online energy variance, used when calculating the specific heat.
Returns
Average energy variance.
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._numOfAnnealingsToAvgOver, IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.OnlineEnergyVariance(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealing().
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgSpecificHeatNVsTemp2().
AvgSpecificHeatNVsTemp2()
void IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgSpecificHeatNVsTemp2 (double initTemp, double finalTemp, double nSamples) inline
Calculates the average specific heat times N at a certain temperature range and writes the results to a file.
Parameters
initTemp Initial temperature.
finalTemp Final temperature.
nSamples The number of samples on the temperature range.
References IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgOnlineEnergyVariance(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.FinalTemperature.
Referenced by IG.MPetekLib.Application.Scripts.CompPhys._05IsingAvgMagnetization.Run().
Member Data Documentation
_spinState
List<List<int> > IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._spinState private
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.IsingModel(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.MagMoment(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.UpdateLatticeRowCurves().
SpinState
SpinStateCollection IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SpinState private
Holds the states (1 or -1) of all the spins in the lattice. Each spin's position in the lattice can be inferred from the indices, since the lattice is rectangular. The indices are cyclic (periodic boundary condition). An indexed property.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.ConfigurationEnergy(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.EnergyVariance(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.IsingModel(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.OnlineEnergyVariance().
_latticeRowCurve
List<PlotZedgraphCurve> IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeRowCurve private
A list of all the rows of spins in the spin lattice. Each row is represented by a PlotZedGraphCurve object.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.ShowPlot(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.UpdateLatticeRowCurves().
_plothq1
PlotHQ IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._plothq1 private
A PlotHQ object used by the plotting thread.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.ShowPlot(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealingWithPlot().
_latticeXDim
int IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeXDim = 100 private
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AverageSusceptibilityN(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.ConfigurationEnergy(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.EnergyVariance(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.IsingModel(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.MagMoment(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.OnlineEnergyVariance(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.TryTurnRandomSpin(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.UpdateLatticeRowCurves().
_latticeYDim
int IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._latticeYDim = 100 private
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AverageSusceptibilityN(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.ConfigurationEnergy(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.EnergyVariance(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.IsingModel(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.MagMoment(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.OnlineEnergyVariance(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.TryTurnRandomSpin(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.UpdateLatticeRowCurves().
_beta
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._beta = 0.3 private
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealing(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealingWithPlot(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.TryTurnRandomSpin().
_j
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._j = 1 private
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.ConfigurationEnergy(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.EnergyVariance(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.OnlineEnergyVariance(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.TryTurnRandomSpin().
_h
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._h = 0 private
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.ConfigurationEnergy(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.EnergyVariance(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.OnlineEnergyVariance(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.TryTurnRandomSpin().
_rng
Random IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._rng = new Random() private
An all-purpose RNG.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.TryTurnRandomSpin().
_diceRoll
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._diceRoll private
A random real number between 0 and 1. Used for the simulated annealing (Boltzmann) criterion.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.TryTurnRandomSpin().
_randomSpinX
int IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._randomSpinX private
The RNG chooses a random spin. This is its x-index.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.TryTurnRandomSpin().
_randomSpinY
int IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._randomSpinY private
The RNG chooses a random spin. This is its y-index.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.TryTurnRandomSpin().
_energyChange
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._energyChange private
The difference between the new and the old energy.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.TryTurnRandomSpin().
_initialBeta
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._initialBeta = 0.005 protected
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealing(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealingWithPlot().
_finalBeta
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._finalBeta = 30 protected
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealing(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealingWithPlot().
_stepsAtTemperature
int IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._stepsAtTemperature = 5000 protected
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealing(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealingWithPlot().
_coolingLevels
int IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._coolingLevels = 7 protected
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealing(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealingWithPlot().
_gamma
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._gamma protected
The factor for which the inverse temperature beta rises after each cooling level. The inverse alpha, where alpha is the analogous factor asocciated with the gradual fall of the temperature.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealing(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealingWithPlot().
_plotEveryNShifts
int IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._plotEveryNShifts = 50 protected
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealingWithPlot().
_locker
readonly object IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._locker = new object() private
A locker for wait/pulse methods.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.ShowPlot(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealingWithPlot().
_go
bool IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._go = false private
A blocking condition for the wait/pulse methods.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.ShowPlot(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.SimulatedAnnealingWithPlot().
_numOfAnnealingsToAvgOver
int IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel._numOfAnnealingsToAvgOver = 10 private
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AverageConfigEnergy(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AverageMagMoment(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AverageSusceptibilityN(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgEnergyVariance(), and IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgOnlineEnergyVariance().
Property Documentation
LatticeXDim
int IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.LatticeXDim get set
Rectangular lattice's x-dimension.
LatticeYDim
int IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.LatticeYDim get set
Rectangular lattice's y-dimension.
Beta
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.Beta get set
The parameter beta of the falling exponential (Boltzmann) distribution. The "inverse" temperature.
Temperature
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.Temperature get set
Temperature is an inverse with beta. Boltzmann constant = 1.
J
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.J get set
Coupling constant between spins: 1 -> paramagnetism (same direction: lower energy), -1 -> diamagnetism.
Referenced by IG.MPetekLib.Application.Scripts.CompPhys._04IsingAvgEnergy.Run(), and IG.MPetekLib.Application.Scripts.CompPhys._05IsingAvgMagnetization.Run().
H
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.H get set
Coupling constant between a spin and the external magnetic field: 1 -> (same direction: lower energy).
Referenced by IG.MPetekLib.Application.Scripts.CompPhys._03AnnealingIsingModel.Run(), IG.MPetekLib.Application.Scripts.CompPhys._05IsingAvgMagnetization.Run(), and IG.MPetekLib.Application.Scripts.CompPhys._04IsingAvgEnergy.Run().
StateChosenSpin
int IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.StateChosenSpin get set private
The state of the spin that's been chosen by the RNG. This property should make the code more readable.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.TryTurnRandomSpin().
StateAboveSpin
int IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.StateAboveSpin get set private
The state of the spin above the chosen spin. This property should make the code more readable.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.TryTurnRandomSpin().
StateBelowSpin
int IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.StateBelowSpin get set private
The state of the spin below the chosen spin. This property should make the code more readable.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.TryTurnRandomSpin().
StateLeftSpin
int IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.StateLeftSpin get set private
The state of the spin left of the chosen spin. This property should make the code more readable.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.TryTurnRandomSpin().
StateRightSpin
int IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.StateRightSpin get set private
The state of the spin right of the chosen spin. This property should make the code more readable.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.TryTurnRandomSpin().
InitialBeta
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.InitialBeta get set
The initial inverse temperature for the simulated annealing process.
InitialTemperature
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.InitialTemperature get set
The initial temperature for the simulated annealing process.
Referenced by IG.MPetekLib.Application.Scripts.CompPhys._03AnnealingIsingModel.Run(), IG.MPetekLib.Application.Scripts.CompPhys._05IsingAvgMagnetization.Run(), and IG.MPetekLib.Application.Scripts.CompPhys._04IsingAvgEnergy.Run().
FinalBeta
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.FinalBeta get set
The final inverse temperature for the simulated annealing process.
FinalTemperature
double IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.FinalTemperature get set
The final temperature for the simulated annealing process.
Referenced by IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AverageSusceptibilityN(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgConfigEnergyVsTemp(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgMagMomentVsTemp(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgSpecificHeatNVsTemp(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgSpecificHeatNVsTemp2(), IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.AvgSusceptibilityNVsTemp(), IG.MPetekLib.Application.Scripts.CompPhys._03AnnealingIsingModel.Run(), IG.MPetekLib.Application.Scripts.CompPhys._05IsingAvgMagnetization.Run(), and IG.MPetekLib.Application.Scripts.CompPhys._04IsingAvgEnergy.Run().
StepsAtTemperature
int IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.StepsAtTemperature get set
How many spin turns the method will make at a certain temperature.
Referenced by IG.MPetekLib.Application.Scripts.CompPhys._03AnnealingIsingModel.Run(), IG.MPetekLib.Application.Scripts.CompPhys._05IsingAvgMagnetization.Run(), and IG.MPetekLib.Application.Scripts.CompPhys._04IsingAvgEnergy.Run().
CoolingLevels
int IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.CoolingLevels get set
How granular the cooling will be. Example: T0 = 1000, TN=100, CoolingLevels = 10: 1000, 900, 800, ..., 200, 100. More levels means higher reliability, but also more time wasted.
Referenced by IG.MPetekLib.Application.Scripts.CompPhys._03AnnealingIsingModel.Run(), IG.MPetekLib.Application.Scripts.CompPhys._05IsingAvgMagnetization.Run(), and IG.MPetekLib.Application.Scripts.CompPhys._04IsingAvgEnergy.Run().
PlotEveryNShifts
int IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.PlotEveryNShifts get set
How often the plotting window should refresh. A smaller number means more often and makes it more interesting. However, a bigger number makes the whole calculation much faster.
Referenced by IG.MPetekLib.Application.Scripts.CompPhys._03AnnealingIsingModel.Run().
NumOfAnnealingsToAvgOver
int IG.MPetekLib.Algorithms.PlottableModels.CompPhys.IsingModel.NumOfAnnealingsToAvgOver get set
How many terms should be added together before averaging takes place. Used by all the averaging methods.
Referenced by IG.MPetekLib.Application.Scripts.CompPhys._05IsingAvgMagnetization.Run().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/Guest_Marko_Petek_Lib/algorithms/PlottableModels/CompPhys/01IsingModel.cs