Doc: IGLib EXTENDED: MatrixDecomposition.MatrixDecompositionProgram Class Reference
MatrixDecomposition.MatrixDecompositionProgram Class Reference
Static Private Member Functions
static void Main (string[] args)
static double[][] MatrixCreate (int rows, int cols)
static double[][] MatrixRandom (int rows, int cols, double minVal, double maxVal, int seed)
static double[][] MatrixIdentity (int n)
static string MatrixAsString (double[][] matrix)
static bool MatrixAreEqual (double[][] matrixA, double[][] matrixB, double epsilon)
static double[][] MatrixProduct (double[][] matrixA, double[][] matrixB)
static double[] MatrixVectorProduct (double[][] matrix, double[] vector)
static double[][] MatrixDecompose (double[][] matrix, out int[] perm, out int toggle)
static double[][] MatrixInverse (double[][] matrix)
static double MatrixDeterminant (double[][] matrix)
static double[] HelperSolve (double[][] luMatrix, double[] b)
static double[] SystemSolve (double[][] A, double[] b)
static double[][] MatrixDuplicate (double[][] matrix)
static double[][] ExtractLower (double[][] matrix)
static double[][] ExtractUpper (double[][] matrix)
static double[][] PermArrayToMatrix (int[] perm)
static double[][] UnPermute (double[][] luProduct, int[] perm)
static string VectorAsString (double[] vector)
static string VectorAsString (int[] vector)
Member Function Documentation
Main()
static void MatrixDecomposition.MatrixDecompositionProgram.Main (string[] args) inline static private
References MatrixDecomposition.MatrixDecompositionProgram.ExtractLower(), MatrixDecomposition.MatrixDecompositionProgram.ExtractUpper(), MatrixDecomposition.MatrixDecompositionProgram.MatrixAreEqual(), MatrixDecomposition.MatrixDecompositionProgram.MatrixAsString(), MatrixDecomposition.MatrixDecompositionProgram.MatrixCreate(), MatrixDecomposition.MatrixDecompositionProgram.MatrixDecompose(), MatrixDecomposition.MatrixDecompositionProgram.MatrixDeterminant(), MatrixDecomposition.MatrixDecompositionProgram.MatrixInverse(), MatrixDecomposition.MatrixDecompositionProgram.MatrixProduct(), MatrixDecomposition.MatrixDecompositionProgram.PermArrayToMatrix(), MatrixDecomposition.MatrixDecompositionProgram.SystemSolve(), MatrixDecomposition.MatrixDecompositionProgram.UnPermute(), and MatrixDecomposition.MatrixDecompositionProgram.VectorAsString().
MatrixCreate()
static double [][] MatrixDecomposition.MatrixDecompositionProgram.MatrixCreate (int rows, int cols) inline static private
Referenced by MatrixDecomposition.MatrixDecompositionProgram.ExtractLower(), MatrixDecomposition.MatrixDecompositionProgram.ExtractUpper(), MatrixDecomposition.MatrixDecompositionProgram.Main(), MatrixDecomposition.MatrixDecompositionProgram.MatrixDuplicate(), MatrixDecomposition.MatrixDecompositionProgram.MatrixIdentity(), MatrixDecomposition.MatrixDecompositionProgram.MatrixProduct(), MatrixDecomposition.MatrixDecompositionProgram.MatrixRandom(), and MatrixDecomposition.MatrixDecompositionProgram.PermArrayToMatrix().
MatrixRandom()
static double [][] MatrixDecomposition.MatrixDecompositionProgram.MatrixRandom (int rows, int cols, double minVal, double maxVal, int seed) inline static private
References MatrixDecomposition.MatrixDecompositionProgram.MatrixCreate().
MatrixIdentity()
static double [][] MatrixDecomposition.MatrixDecompositionProgram.MatrixIdentity (int n) inline static private
References MatrixDecomposition.MatrixDecompositionProgram.MatrixCreate().
MatrixAsString()
static string MatrixDecomposition.MatrixDecompositionProgram.MatrixAsString (double matrix[][]) inline static private
Referenced by MatrixDecomposition.MatrixDecompositionProgram.Main().
MatrixAreEqual()
static bool MatrixDecomposition.MatrixDecompositionProgram.MatrixAreEqual (double matrixA[][], double matrixB[][], double epsilon) inline static private
Referenced by MatrixDecomposition.MatrixDecompositionProgram.Main().
MatrixProduct()
static double [][] MatrixDecomposition.MatrixDecompositionProgram.MatrixProduct (double matrixA[][], double matrixB[][]) inline static private
References MatrixDecomposition.MatrixDecompositionProgram.MatrixCreate().
Referenced by MatrixDecomposition.MatrixDecompositionProgram.Main().
MatrixVectorProduct()
static double [] MatrixDecomposition.MatrixDecompositionProgram.MatrixVectorProduct (double matrix[][], double[] vector) inline static private
MatrixDecompose()
static double [][] MatrixDecomposition.MatrixDecompositionProgram.MatrixDecompose (double matrix[][], out int[] perm, out int toggle) inline static private
References MatrixDecomposition.MatrixDecompositionProgram.MatrixDuplicate().
Referenced by MatrixDecomposition.MatrixDecompositionProgram.Main(), MatrixDecomposition.MatrixDecompositionProgram.MatrixDeterminant(), MatrixDecomposition.MatrixDecompositionProgram.MatrixInverse(), and MatrixDecomposition.MatrixDecompositionProgram.SystemSolve().
MatrixInverse()
static double [][] MatrixDecomposition.MatrixDecompositionProgram.MatrixInverse (double matrix[][]) inline static private
References MatrixDecomposition.MatrixDecompositionProgram.HelperSolve(), MatrixDecomposition.MatrixDecompositionProgram.MatrixDecompose(), and MatrixDecomposition.MatrixDecompositionProgram.MatrixDuplicate().
Referenced by MatrixDecomposition.MatrixDecompositionProgram.Main().
MatrixDeterminant()
static double MatrixDecomposition.MatrixDecompositionProgram.MatrixDeterminant (double matrix[][]) inline static private
References MatrixDecomposition.MatrixDecompositionProgram.MatrixDecompose().
Referenced by MatrixDecomposition.MatrixDecompositionProgram.Main().
HelperSolve()
static double [] MatrixDecomposition.MatrixDecompositionProgram.HelperSolve (double luMatrix[][], double[] b) inline static private
Referenced by MatrixDecomposition.MatrixDecompositionProgram.MatrixInverse(), and MatrixDecomposition.MatrixDecompositionProgram.SystemSolve().
SystemSolve()
static double [] MatrixDecomposition.MatrixDecompositionProgram.SystemSolve (double A[][], double[] b) inline static private
References MatrixDecomposition.MatrixDecompositionProgram.HelperSolve(), and MatrixDecomposition.MatrixDecompositionProgram.MatrixDecompose().
Referenced by MatrixDecomposition.MatrixDecompositionProgram.Main().
MatrixDuplicate()
static double [][] MatrixDecomposition.MatrixDecompositionProgram.MatrixDuplicate (double matrix[][]) inline static private
References MatrixDecomposition.MatrixDecompositionProgram.MatrixCreate().
Referenced by MatrixDecomposition.MatrixDecompositionProgram.MatrixDecompose(), MatrixDecomposition.MatrixDecompositionProgram.MatrixInverse(), and MatrixDecomposition.MatrixDecompositionProgram.UnPermute().
ExtractLower()
static double [][] MatrixDecomposition.MatrixDecompositionProgram.ExtractLower (double matrix[][]) inline static private
References MatrixDecomposition.MatrixDecompositionProgram.MatrixCreate().
Referenced by MatrixDecomposition.MatrixDecompositionProgram.Main().
ExtractUpper()
static double [][] MatrixDecomposition.MatrixDecompositionProgram.ExtractUpper (double matrix[][]) inline static private
References MatrixDecomposition.MatrixDecompositionProgram.MatrixCreate().
Referenced by MatrixDecomposition.MatrixDecompositionProgram.Main().
PermArrayToMatrix()
static double [][] MatrixDecomposition.MatrixDecompositionProgram.PermArrayToMatrix (int[] perm) inline static private
References MatrixDecomposition.MatrixDecompositionProgram.MatrixCreate().
Referenced by MatrixDecomposition.MatrixDecompositionProgram.Main().
UnPermute()
static double [][] MatrixDecomposition.MatrixDecompositionProgram.UnPermute (double luProduct[][], int[] perm) inline static private
References MatrixDecomposition.MatrixDecompositionProgram.MatrixDuplicate().
Referenced by MatrixDecomposition.MatrixDecompositionProgram.Main().
VectorAsString() [1/2]
static string MatrixDecomposition.MatrixDecompositionProgram.VectorAsString (double[] vector) inline static private
Referenced by MatrixDecomposition.MatrixDecompositionProgram.Main().
VectorAsString() [2/2]
static string MatrixDecomposition.MatrixDecompositionProgram.VectorAsString (int[] vector) inline static private
The documentation for this class was generated from the following file:
igtest/numerics/McCaffreyMatrix1212/ludecomp_McCaffrey_original/MatrixDecompositionProgram.cs