Doc: IGLib EXTENDED: AForge.Robotics.Surveyor.SRV1 Class Reference
AForge.Robotics.Surveyor.SRV1 Class Reference
Manipulation of Surveyor SRV-1 Blackfin robot/camera.
Classes
class CommunicationRequest
Public Types
enum MotorCommand {
MotorCommand.DriveForward = '8', MotorCommand.DriveBack = '2', MotorCommand.DriveLeft = '4', MotorCommand.DriveRight = '6',
MotorCommand.DriftLeft = '7', MotorCommand.DriftRight = '9', MotorCommand.Stop = '5', MotorCommand.DriveBackRight = '3',
MotorCommand.DriveBackLeft = '1', MotorCommand.RotateLeft = '0', MotorCommand.RotateRight = '.', MotorCommand.IncreaseSpeed = '+',
MotorCommand.DecreaseSpeed = '-'
}
Enumeration of predefined motors' commands.
enum VideoResolution { VideoResolution.Tiny = 'a', VideoResolution.Small = 'b', VideoResolution.Medium = 'c', VideoResolution.Large = 'd' }
Enumeration of Surveyor SRV-1 Blackfin cameras resolutions.
Public Member Functions
SRV1 ()
Initializes a new instance of the SRV1 class.
void Connect (string ip, int port)
Connect to SRV-1 Blackfin robot/camera.
void Disconnect ()
Disconnect from SRV-1 Blackfin robot.
SRV1Camera GetCamera ()
Get camera object for the SRV-1 Blackfin robot/camera.
void Send (byte[] request)
Enqueue communication request.
int SendAndReceive (byte[] request, byte[] responseBuffer)
Enqueue communication request and wait for reply.
Bitmap GetImage ()
Get single image from the SRV-1 Blackfin camera.
string GetVersion ()
Get SRV-1 firmware version string.
long GetRunningTime ()
Get SRV-1 running time.
void RunMotors (int leftSpeed, int rightSpeed, int duration)
Run motors connected to SRV-1 robot.
void StopMotors ()
Stop both motors.
void EnableFailsafeMode (int leftSpeed, int rightSpeed)
Enables fail safe mode - setting motors' speed after timeout.
void DisableFailsafeMode ()
Disable fail safe mode.
void ControlServos (int leftServo, int rightServo)
Direct servos control of SRV-1 robot.
void ControlMotors (MotorCommand command)
Control SRV-1 robot's motors using predefined commands.
void SetQuality (int quality)
Set video quality.
void SetResolution (VideoResolution resolution)
Set video resolution.
void FlipVideo (bool isFlipped)
Flip video capture or not (for use with upside-down camera).
float[] UltrasonicPing ()
Ping ultrasonic ranging modules.
byte I2CReadByte (byte deviceID, byte register)
Read byte from I2C device.
ushort I2CReadWord (byte deviceID, byte register)
Read word from I2C device.
void I2CWriteByte (byte deviceID, byte register, byte byteToWrite)
Write byte to I2C device.
void I2CWriteWord (byte deviceID, byte register, byte firstByteToWrite, byte secondByteToWrite)
Write two bytes to I2C device.
Properties
string? HostAddress [get]
SRV-1 host address.
int? Port [get]
SRV-1 port number.
bool IsConnected [get]
Connection state.
Private Member Functions
void Reconnect ()
void CommunicationThread ()
void DiscardIncomingData (Socket socket, ManualResetEvent stopEvent)
Private Attributes
object sync = new object()
IPEndPoint endPoint = null
Socket socket = null
Thread thread = null
ManualResetEvent stopEvent = null
AutoResetEvent requestIsAvailable
AutoResetEvent replyIsAvailable
CommunicationRequest lastRequestWithReply
Queue< CommunicationRequest > communicationQueue = new Queue<CommunicationRequest>()
SRV1Camera camera
Static Private Attributes
const int readSize = 1024
Detailed Description
Manipulation of Surveyor SRV-1 Blackfin robot/camera.
The class allows to manipulate with Surveyor SRV-1 Blackfin Robot
getting video from its camera, manipulating motors and servos, reading ultrasonic modules' values, sending direct commands, etc.
Sample usage:
SRV1 srv = new SRV1();
// connect to SRV-1 robot
srv.Connect("169.254.0.10", 10001);
// stop motors
srv.StopMotors();
// set video resolution and quality
srv.SetQuality(7);
srv.SetResolution(SRV1.VideoResolution.Small);
// get version string
string version = srv.GetVersion();
// get robot's camera
SRV1Camera camera = srv.GetCamera();
// set NewFrame event handler
camera.NewFrame += new NewFrameEventHandler(video_NewFrame);
// start the video source
camera.Start();
// ...
private void video_NewFrame(object sender, NewFrameEventArgs eventArgs)
{
    // get new frame
    Bitmap bitmap = eventArgs.Frame;
    // process the frame
}
See also
SRV1Camera
Member Enumeration Documentation
MotorCommand
enum AForge.Robotics.Surveyor.SRV1.MotorCommand strong
Enumeration of predefined motors' commands.
This enumeration defines set of motors' commands, which can be executed using ControlMotors method.
<note>Controlling SRV-1 motors with these commands is only possible after at least one direct motor command is sent, which is done using StopMotors or RunMotors methods.</note>
<note>The IncreaseSpeed and DecreaseSpeed commands do not have any effect unless another driving command is sent. In other words, these do not increase/decrease speed of current operation, but affect speed of all following commands.</note>
<note>The RotateLeft and RotateRight commands may be useful only for the original Surveyor SRV-1 Blackfin Robot. For most of other robots, which may have different motors and moving base, these commands will not be accurate – will not rotate for 20 degrees. </note>
Enumerator
DriveForward
Robot drive forward.
DriveBack
Robot drive back.
DriveLeft
Robot drive left.
DriveRight
Robot drive right.
DriftLeft
Robot drift left.
DriftRight
Robot drift right.
Stop
Robot stop.
DriveBackRight
Robot drive back and right.
DriveBackLeft
Robot drive back and left.
RotateLeft
Robot rotate left 20 degrees.
RotateRight
Robot rotate right 20 degrees.
IncreaseSpeed
Increase motors' speed.
DecreaseSpeed
Decrease motors' speed.
VideoResolution
enum AForge.Robotics.Surveyor.SRV1.VideoResolution strong
Enumeration of Surveyor SRV-1 Blackfin cameras resolutions.
Enumerator
Tiny
160x120
Small
320x240
Medium
640x480
Large
1280x1024
Constructor & Destructor Documentation
SRV1()
AForge.Robotics.Surveyor.SRV1.SRV1 () inline
Initializes a new instance of the SRV1 class.
Member Function Documentation
Connect()
void AForge.Robotics.Surveyor.SRV1.Connect (string ip, int port) inline
Connect to SRV-1 Blackfin robot/camera.
Parameters
ip IP address of SRV-1 robot.
port Port number to connect to.
The method establishes connection to SRV-1 Blackfin robot/camera. If it succeeds then other methods can be used to manipulate the robot.
<note>The method calls Disconnect before making any connection attempts to make sure previous connection is closed.</note>
Exceptions
ConnectionFailedException Failed connecting to SRV-1.
References AForge.Robotics.Surveyor.SRV1.communicationQueue, AForge.Robotics.Surveyor.SRV1.CommunicationThread(), AForge.Robotics.Surveyor.SRV1.Disconnect(), AForge.Robotics.Surveyor.SRV1.endPoint, AForge.Robotics.Surveyor.SRV1.replyIsAvailable, AForge.Robotics.Surveyor.SRV1.requestIsAvailable, AForge.Robotics.Surveyor.SRV1.socket, AForge.Robotics.Surveyor.SRV1.stopEvent, AForge.Robotics.Surveyor.SRV1.sync, and AForge.Robotics.Surveyor.SRV1.thread.
Referenced by SRVTest.MainForm.Connect(), and AForge.Robotics.Surveyor.SVS.Connect().
Disconnect()
void AForge.Robotics.Surveyor.SRV1.Disconnect () inline
Disconnect from SRV-1 Blackfin robot.
The method disconnects from SRV-1 robot making all other methods unavailable (except Connect method). In the case if user obtained instance of camera using GetCamera method, the video will be stopped automatically (and those SRV1Camera instances should be discarded).
References AForge.Robotics.Surveyor.SRV1.camera, AForge.Robotics.Surveyor.SRV1.endPoint, AForge.Robotics.Surveyor.SRV1Camera.IsRunning, AForge.Robotics.Surveyor.SRV1.replyIsAvailable, AForge.Robotics.Surveyor.SRV1.requestIsAvailable, AForge.Robotics.Surveyor.SRV1Camera.SignalToStop(), AForge.Robotics.Surveyor.SRV1.socket, AForge.Robotics.Surveyor.SRV1Camera.Stop(), AForge.Robotics.Surveyor.SRV1.stopEvent, AForge.Robotics.Surveyor.SRV1.sync, and AForge.Robotics.Surveyor.SRV1.thread.
Referenced by AForge.Robotics.Surveyor.SRV1.Connect(), SRVTest.MainForm.Disconnect(), and AForge.Robotics.Surveyor.SVS.Disconnect().
Reconnect()
void AForge.Robotics.Surveyor.SRV1.Reconnect () inline private
References AForge.Robotics.Surveyor.SRV1.endPoint, and AForge.Robotics.Surveyor.SRV1.socket.
Referenced by AForge.Robotics.Surveyor.SRV1.CommunicationThread().
GetCamera()
SRV1Camera AForge.Robotics.Surveyor.SRV1.GetCamera () inline
Get camera object for the SRV-1 Blackfin robot/camera.
Returns
Returns SRV1Camera object, which is connected to SRV1 Blackfin camera. Use SRV1Camera.Start method to start the camera and start receiving video frames it.
The method provides an instance of SRV1Camera, which can be used for receiving continuous video frames from the SRV-1 Blackfin camera. In the case if only one image is required, the GetImage method can be used.
Sample usage:
// get SRV-1 camera
SRV1Camera camera = srv.GetCamera();
// set NewFrame event handler
camera.NewFrame += new NewFrameEventHandler(video_NewFrame);
// start the video source
camera.Start();
// ...
private void video_NewFrame(object sender, NewFrameEventArgs eventArgs)
{
    // get new frame
    Bitmap bitmap = eventArgs.Frame;
    // process the frame
}
Exceptions
NotConnectedException Not connected to SRV-1. Connect to SRV-1 robot/camera before using this method.
References AForge.Robotics.Surveyor.SRV1.camera, AForge.Robotics.Surveyor.SRV1.socket, and AForge.Robotics.Surveyor.SRV1.sync.
Referenced by SRVTest.MainForm.Connect(), and AForge.Robotics.Surveyor.SVS.GetCamera().
Send()
void AForge.Robotics.Surveyor.SRV1.Send (byte[] request) inline
Enqueue communication request.
Parameters
request Array of bytes (command) to send to SRV-1 Blackfin robot/camera.
The method puts specified command into communication queue and leaves immediately. Once internal communication thread becomes free from sending/receiving previous commands/replies, it will send the queued command.
The method is useful for those SRV-1 commands, which does not assume any response data in the command's reply.
<note>Since the method only queues a communication request, it does not provide any status of request's delivery and it does not generate any exceptions on failure.</note>
References AForge.Robotics.Surveyor.SRV1.communicationQueue, and AForge.Robotics.Surveyor.SRV1.requestIsAvailable.
Referenced by AForge.Robotics.Surveyor.SRV1.ControlMotors(), AForge.Robotics.Surveyor.SVS.ControlServos(), AForge.Robotics.Surveyor.SRV1.ControlServos(), AForge.Robotics.Surveyor.SRV1.DisableFailsafeMode(), AForge.Robotics.Surveyor.SRV1.EnableFailsafeMode(), AForge.Robotics.Surveyor.SRV1.FlipVideo(), AForge.Robotics.Surveyor.SRV1.RunMotors(), AForge.Robotics.Surveyor.SRV1.SetQuality(), and AForge.Robotics.Surveyor.SRV1.SetResolution().
SendAndReceive()
int AForge.Robotics.Surveyor.SRV1.SendAndReceive (byte[] request, byte[] responseBuffer) inline
Enqueue communication request and wait for reply.
Parameters
request Array of bytes (command) to send to SRV-1 Blackfin robot/camera.
responseBuffer Buffer to read response into.
Returns
Returns total bytes read into the response buffer.
The method puts specified command into communication queue and waits until the command is sent to SRV-1 Blackfin robot and reply is received.
<note>If SRV-1 responds with more data than response buffer can fit, then the response buffer will take all the data it can store, but the rest of response will be discarded. The only exception is image request - if response buffer is too small to fit image response, then IndexOutOfRangeException exception is thrown. It is user's responsibility to provide response buffer of the correct size. Check definition of the SRV-1 Control Protocol for information about supported commands and responses.</note>
Exceptions
NotConnectedException Not connected to SRV-1.
ConnectionLostException Connection lost or communicaton failure.
IndexOutOfRangeException Response buffer is too small.
References AForge.Robotics.Surveyor.SRV1.CommunicationRequest.BytesRead, AForge.Robotics.Surveyor.SRV1.communicationQueue, AForge.Robotics.Surveyor.SRV1.lastRequestWithReply, AForge.Robotics.Surveyor.SRV1.replyIsAvailable, AForge.Robotics.Surveyor.SRV1.requestIsAvailable, AForge.Robotics.Surveyor.SRV1.socket, and AForge.Robotics.Surveyor.SRV1.sync.
Referenced by AForge.Robotics.Surveyor.SRV1.GetImage(), AForge.Robotics.Surveyor.SRV1.GetRunningTime(), AForge.Robotics.Surveyor.SRV1.GetVersion(), AForge.Robotics.Surveyor.SRV1.I2CReadByte(), AForge.Robotics.Surveyor.SRV1.I2CReadWord(), AForge.Robotics.Surveyor.SRV1.I2CWriteByte(), AForge.Robotics.Surveyor.SRV1.I2CWriteWord(), AForge.Robotics.Surveyor.SRV1.UltrasonicPing(), and AForge.Robotics.Surveyor.SRV1Camera.WorkerThread().
GetImage()
Bitmap AForge.Robotics.Surveyor.SRV1.GetImage () inline
Get single image from the SRV-1 Blackfin camera.
Returns
Returns image received from the SRV-1 Blackfin camera or null if failed decoding provided response.
The method provides single video frame retrieved from the SRV-1 Blackfin camera. However in many cases it is required to receive video frames one after another, so the GetCamera method is more preferred for continuous video frames.
Exceptions
NotConnectedException Not connected to SRV-1. Connect to SRV-1 before using this method.
ConnectionLostException Connection lost or communicaton failure. Try to reconnect.
References AForge.Robotics.Surveyor.SRV1.SendAndReceive().
Referenced by AForge.Robotics.Surveyor.SVS.GetImage().
GetVersion()
string AForge.Robotics.Surveyor.SRV1.GetVersion () inline
Get SRV-1 firmware version string.
Returns
Returns SRV-1 version string.
Exceptions
NotConnectedException Not connected to SRV-1. Connect to SRV-1 before using this method.
ConnectionLostException Connection lost or communicaton failure. Try to reconnect.
References AForge.Robotics.Surveyor.SRV1.SendAndReceive().
Referenced by SRVTest.MainForm.Connect(), and AForge.Robotics.Surveyor.SVS.GetVersion().
GetRunningTime()
long AForge.Robotics.Surveyor.SRV1.GetRunningTime () inline
Get SRV-1 running time.
Returns
Returns SRV-1 running time in milliseconds.
Exceptions
NotConnectedException Not connected to SRV-1. Connect to SRV-1 before using this method.
ConnectionLostException Connection lost or communicaton failure. Try to reconnect.
ApplicationException Failed parsing response from SRV-1.
References AForge.Robotics.Surveyor.SRV1.SendAndReceive().
Referenced by AForge.Robotics.Surveyor.SVS.GetRunningTime().
RunMotors()
void AForge.Robotics.Surveyor.SRV1.RunMotors (int leftSpeed, int rightSpeed, int duration) inline
Run motors connected to SRV-1 robot.
Parameters
leftSpeed Left motor's speed, [-127, 127].
rightSpeed Right motor's speed, [-127, 127].
duration Time duration to run motors measured in number of 10 milliseconds (0 for infinity), [0, 255].
The method provides direct access to motors setting specified, speed to both motors connected to the SRV-1 robot. The maximum absolute speed equals to 127, but the sign specifies direction of motor's rotation (forward or backward).
<note>The method sends 'Mabc' SRV-1 command (see SRV-1 Control Protocol), which uses 2nd and 3rd timers for controlling motors/servos.</note>
References AForge.Robotics.Surveyor.SRV1.Send().
Referenced by SRVTest.MainForm.DriveMotors(), AForge.Robotics.Surveyor.SVS.RunMotors(), and AForge.Robotics.Surveyor.SRV1.StopMotors().
StopMotors()
void AForge.Robotics.Surveyor.SRV1.StopMotors () inline
Stop both motors.
The method stops both motors connected to the SRV-1 robot by calling RunMotors method specifying 0 for motors' speed.
References AForge.Robotics.Surveyor.SRV1.RunMotors().
Referenced by SRVTest.MainForm.Disconnect(), and SRVTest.MainForm.srvDriverControl_SrvDrivingCommand().
EnableFailsafeMode()
void AForge.Robotics.Surveyor.SRV1.EnableFailsafeMode (int leftSpeed, int rightSpeed) inline
Enables fail safe mode - setting motors' speed after timeout.
Parameters
leftSpeed Left motor's speed, [-127, 127].
rightSpeed Right motor's speed, [-127, 127].
In the case if fail safe mode is enabled and no commands are received by SRV-1 robot withing 2 seconds, motors' speed will be set to the specified values. The command is very useful to instruct robot to stop if no other commands were sent within 2 last seconds (probably lost connection).
References AForge.Robotics.Surveyor.SRV1.Send().
Referenced by SRVTest.MainForm.Connect(), and AForge.Robotics.Surveyor.SVS.EnableFailsafeMode().
DisableFailsafeMode()
void AForge.Robotics.Surveyor.SRV1.DisableFailsafeMode () inline
Disable fail safe mode.
The method disable fail safe mode, which was set using EnableFailsafeMode method.
References AForge.Robotics.Surveyor.SRV1.Send().
Referenced by AForge.Robotics.Surveyor.SVS.DisableFailsafeMode().
ControlServos()
void AForge.Robotics.Surveyor.SRV1.ControlServos (int leftServo, int rightServo) inline
Direct servos control of SRV-1 robot.
Parameters
leftServo Left servo setting, [0, 100].
rightServo Right servo setting, [0, 100].
Servo settings represent timing pulse widths ranging from 1ms to 2ms. 0 corresponds to a 1ms pulse, 100 corresponds to a 2ms pulse, and 50 is midrange with a 1.5ms pulse.
<note>The method sends 'sab' SRV-1 command (see SRV-1 Control Protocol), which controls 2nd bank of servos using 6th and 7th timers.</note>
References AForge.Robotics.Surveyor.SRV1.Send().
Referenced by AForge.Robotics.Surveyor.SVS.ControlServos().
ControlMotors()
void AForge.Robotics.Surveyor.SRV1.ControlMotors (MotorCommand command) inline
Control SRV-1 robot's motors using predefined commands.
Parameters
command Motor command to send to the SRV-1 Blackfin robot.
<note>Controlling SRV-1 motors with this method is only available after at least one direct motor command is sent, which is done using StopMotors or RunMotors methods.</note>
References AForge.Robotics.Surveyor.SRV1.Send().
Referenced by AForge.Robotics.Surveyor.SVS.ControlMotors(), and SRVTest.MainForm.srvDriverControl_SrvDrivingCommand().
SetQuality()
void AForge.Robotics.Surveyor.SRV1.SetQuality (int quality) inline
Set video quality.
Parameters
quality Video quality to set, [1, 8].
The method sets video quality, which is specified in [1, 8] range - 1 is the highest quality level, 8 is the lowest quality level.
<note>Setting higher quality level and resolution may increase delays for other requests sent to SRV-1. So if robot is used not only for video, but also for controlling servos/motors, and higher response level is required, then do not set very high quality and resolution. </note>
Exceptions
ArgumentOutOfRangeException Invalid quality level was specified.
References AForge.Robotics.Surveyor.SRV1.Send().
Referenced by SRVTest.MainForm.Connect(), SRVTest.MainForm.qualityCombo_SelectedIndexChanged(), AForge.Robotics.Surveyor.SRV1Camera.SetQuality(), and AForge.Robotics.Surveyor.SVS.SetQuality().
SetResolution()
void AForge.Robotics.Surveyor.SRV1.SetResolution (VideoResolution resolution) inline
Set video resolution.
Parameters
resolution Video resolution to set.
<note>Setting higher quality level and resolution may increase delays for other requests sent to SRV-1. So if robot is used not only for video, but also for controlling servos/motors, and higher response level is required, then do not set very high quality and resolution. </note>
Exceptions
ArgumentOutOfRangeException Invalid resolution was specified.
References AForge.Robotics.Surveyor.SRV1.Send().
Referenced by SRVTest.MainForm.Connect(), SRVTest.MainForm.resolutionCombo_SelectedIndexChanged(), AForge.Robotics.Surveyor.SRV1Camera.SetResolution(), and AForge.Robotics.Surveyor.SVS.SetResolution().
FlipVideo()
void AForge.Robotics.Surveyor.SRV1.FlipVideo (bool isFlipped) inline
Flip video capture or not (for use with upside-down camera).
Parameters
isFlipped Specifies if video should be flipped (true), or not (false).
References AForge.Robotics.Surveyor.SRV1.Send().
Referenced by SRVTest.MainForm.Connect(), AForge.Robotics.Surveyor.SRV1Camera.FlipVideo(), and AForge.Robotics.Surveyor.SVS.FlipVideo().
UltrasonicPing()
float [] AForge.Robotics.Surveyor.SRV1.UltrasonicPing () inline
Ping ultrasonic ranging modules.
Returns
Returns array of ranges (distances) obtained from ultrasonic sensors. The ranges are measured in inches.
The method sends 'p' SRV-1 command (see SRV-1 Control Protocol), which gets values from ultrasonic ranging modules attached to pins 27, 28, 29, 30 with trigger on pin 18. Supports Maxbotics EZ0 and EZ1 ultrasonic modules.
Exceptions
NotConnectedException Not connected to SRV-1. Connect to SRV-1 before using this method.
ConnectionLostException Connection lost or communicaton failure. Try to reconnect.
ApplicationException Failed parsing response from SRV-1.
References AForge.Robotics.Surveyor.SRV1.SendAndReceive().
Referenced by AForge.Robotics.Surveyor.SVS.UltrasonicPing().
I2CReadByte()
byte AForge.Robotics.Surveyor.SRV1.I2CReadByte (byte deviceID, byte register) inline
Read byte from I2C device.
Parameters
deviceID I2C device ID (7 bit notation).
register I2C device register to read.
Returns
Returns byte read from the specified register of the specified I2C device.
<note>The IC2 device ID should be specified in 7 bit notation. This means that low bit of the ID is not used for specifying read/write mode as in 8 bit notation. For example, if I2C device IDs are 0x44 for reading and 0x45 for writing in 8 bit notation, then it equals to 0x22 device ID in 7 bit notation. </note>
Exceptions
NotConnectedException Not connected to SRV-1. Connect to SRV-1 before using this method.
ConnectionLostException Connection lost or communicaton failure. Try to reconnect.
ApplicationException Failed parsing response from SRV-1.
References AForge.Robotics.Surveyor.SRV1.SendAndReceive().
Referenced by AForge.Robotics.Surveyor.SVS.I2CReadByte().
I2CReadWord()
ushort AForge.Robotics.Surveyor.SRV1.I2CReadWord (byte deviceID, byte register) inline
Read word from I2C device.
Parameters
deviceID I2C device ID (7 bit notation).
register I2C device register to read.
Returns
Returns word read from the specified register of the specified I2C device.
<note>The IC2 device ID should be specified in 7 bit notation. This means that low bit of the ID is not used for specifying read/write mode as in 8 bit notation. For example, if I2C device IDs are 0x44 for reading and 0x45 for writing in 8 bit notation, then it equals to 0x22 device ID in 7 bit notation. </note>
Exceptions
NotConnectedException Not connected to SRV-1. Connect to SRV-1 before using this method.
ConnectionLostException Connection lost or communicaton failure. Try to reconnect.
ApplicationException Failed parsing response from SRV-1.
References AForge.Robotics.Surveyor.SRV1.SendAndReceive().
Referenced by AForge.Robotics.Surveyor.SVS.I2CReadWord().
I2CWriteByte()
void AForge.Robotics.Surveyor.SRV1.I2CWriteByte (byte deviceID, byte register, byte byteToWrite) inline
Write byte to I2C device.
Parameters
deviceID I2C device ID (7 bit notation).
register I2C device register to write to.
byteToWrite Byte to write to the specified register of the specified device.
<note>The IC2 device ID should be specified in 7 bit notation. This means that low bit of the ID is not used for specifying read/write mode as in 8 bit notation. For example, if I2C device IDs are 0x44 for reading and 0x45 for writing in 8 bit notation, then it equals to 0x22 device ID in 7 bit notation. </note>
Exceptions
NotConnectedException Not connected to SRV-1. Connect to SRV-1 before using this method.
ConnectionLostException Connection lost or communicaton failure. Try to reconnect.
References AForge.Robotics.Surveyor.SRV1.SendAndReceive().
Referenced by AForge.Robotics.Surveyor.SVS.I2CWriteByte().
I2CWriteWord()
void AForge.Robotics.Surveyor.SRV1.I2CWriteWord (byte deviceID, byte register, byte firstByteToWrite, byte secondByteToWrite) inline
Write two bytes to I2C device.
Parameters
deviceID I2C device ID (7 bit notation).
register I2C device register to write to.
firstByteToWrite First byte to write to the specified register of the specified device.
secondByteToWrite Second byte to write to the specified register of the specified device.
<note>The IC2 device ID should be specified in 7 bit notation. This means that low bit of the ID is not used for specifying read/write mode as in 8 bit notation. For example, if I2C device IDs are 0x44 for reading and 0x45 for writing in 8 bit notation, then it equals to 0x22 device ID in 7 bit notation. </note>
Exceptions
NotConnectedException Not connected to SRV-1. Connect to SRV-1 before using this method.
ConnectionLostException Connection lost or communicaton failure. Try to reconnect.
References AForge.Robotics.Surveyor.SRV1.SendAndReceive().
Referenced by AForge.Robotics.Surveyor.SVS.I2CWriteWord().
CommunicationThread()
void AForge.Robotics.Surveyor.SRV1.CommunicationThread () inline private
References AForge.Robotics.Surveyor.SRV1.CommunicationRequest.BytesRead, AForge.Robotics.Surveyor.SRV1.communicationQueue, AForge.Robotics.Surveyor.SRV1.DiscardIncomingData(), AForge.Robotics.Surveyor.SRV1.lastRequestWithReply, AForge.Robotics.Surveyor.SRV1.readSize, AForge.Robotics.Surveyor.SRV1.Reconnect(), AForge.Robotics.Surveyor.SRV1.replyIsAvailable, AForge.Robotics.Surveyor.SRV1.CommunicationRequest.Request, AForge.Robotics.Surveyor.SRV1.requestIsAvailable, AForge.Robotics.Surveyor.SRV1.CommunicationRequest.ResponseBuffer, AForge.Robotics.Surveyor.SRV1.socket, and AForge.Robotics.Surveyor.SRV1.stopEvent.
Referenced by AForge.Robotics.Surveyor.SRV1.Connect().
DiscardIncomingData()
void AForge.Robotics.Surveyor.SRV1.DiscardIncomingData (Socket socket, ManualResetEvent stopEvent) inline private
References AForge.Robotics.Surveyor.SRV1.socket, and AForge.Robotics.Surveyor.SRV1.stopEvent.
Referenced by AForge.Robotics.Surveyor.SRV1.CommunicationThread().
Member Data Documentation
sync
object AForge.Robotics.Surveyor.SRV1.sync = new object() private
Referenced by AForge.Robotics.Surveyor.SRV1.Connect(), AForge.Robotics.Surveyor.SRV1.Disconnect(), AForge.Robotics.Surveyor.SRV1.GetCamera(), and AForge.Robotics.Surveyor.SRV1.SendAndReceive().
endPoint
IPEndPoint AForge.Robotics.Surveyor.SRV1.endPoint = null private
Referenced by AForge.Robotics.Surveyor.SRV1.Connect(), AForge.Robotics.Surveyor.SRV1.Disconnect(), and AForge.Robotics.Surveyor.SRV1.Reconnect().
socket
Socket AForge.Robotics.Surveyor.SRV1.socket = null private
Referenced by AForge.Robotics.Surveyor.SRV1.CommunicationThread(), AForge.Robotics.Surveyor.SRV1.Connect(), AForge.Robotics.Surveyor.SRV1.DiscardIncomingData(), AForge.Robotics.Surveyor.SRV1.Disconnect(), AForge.Robotics.Surveyor.SRV1.GetCamera(), AForge.Robotics.Surveyor.SRV1.Reconnect(), and AForge.Robotics.Surveyor.SRV1.SendAndReceive().
thread
Thread AForge.Robotics.Surveyor.SRV1.thread = null private
Referenced by AForge.Robotics.Surveyor.SRV1.Connect(), and AForge.Robotics.Surveyor.SRV1.Disconnect().
stopEvent
ManualResetEvent AForge.Robotics.Surveyor.SRV1.stopEvent = null private
Referenced by AForge.Robotics.Surveyor.SRV1.CommunicationThread(), AForge.Robotics.Surveyor.SRV1.Connect(), AForge.Robotics.Surveyor.SRV1.DiscardIncomingData(), and AForge.Robotics.Surveyor.SRV1.Disconnect().
requestIsAvailable
AutoResetEvent AForge.Robotics.Surveyor.SRV1.requestIsAvailable private
Referenced by AForge.Robotics.Surveyor.SRV1.CommunicationThread(), AForge.Robotics.Surveyor.SRV1.Connect(), AForge.Robotics.Surveyor.SRV1.Disconnect(), AForge.Robotics.Surveyor.SRV1.Send(), and AForge.Robotics.Surveyor.SRV1.SendAndReceive().
replyIsAvailable
AutoResetEvent AForge.Robotics.Surveyor.SRV1.replyIsAvailable private
Referenced by AForge.Robotics.Surveyor.SRV1.CommunicationThread(), AForge.Robotics.Surveyor.SRV1.Connect(), AForge.Robotics.Surveyor.SRV1.Disconnect(), and AForge.Robotics.Surveyor.SRV1.SendAndReceive().
lastRequestWithReply
CommunicationRequest AForge.Robotics.Surveyor.SRV1.lastRequestWithReply private
Referenced by AForge.Robotics.Surveyor.SRV1.CommunicationThread(), and AForge.Robotics.Surveyor.SRV1.SendAndReceive().
communicationQueue
Queue<CommunicationRequest> AForge.Robotics.Surveyor.SRV1.communicationQueue = new Queue<CommunicationRequest>() private
Referenced by AForge.Robotics.Surveyor.SRV1.CommunicationThread(), AForge.Robotics.Surveyor.SRV1.Connect(), AForge.Robotics.Surveyor.SRV1.Send(), and AForge.Robotics.Surveyor.SRV1.SendAndReceive().
camera
SRV1Camera AForge.Robotics.Surveyor.SRV1.camera private
Referenced by AForge.Robotics.Surveyor.SRV1.Disconnect(), and AForge.Robotics.Surveyor.SRV1.GetCamera().
readSize
const int AForge.Robotics.Surveyor.SRV1.readSize = 1024 static private
Referenced by AForge.Robotics.Surveyor.SRV1.CommunicationThread().
Property Documentation
HostAddress
string? AForge.Robotics.Surveyor.SRV1.HostAddress get
SRV-1 host address.
The property keeps SRV-1 IP address if the class is connected to SRV-1 Blackfin robot/camera, otherwise it equals to null..
Port
int? AForge.Robotics.Surveyor.SRV1.Port get
SRV-1 port number.
The property keeps SRV-1 port number if the class is connected to SRV-1 Blackfin robot/camera, otherwise it equals to 0.
IsConnected
bool AForge.Robotics.Surveyor.SRV1.IsConnected get
Connection state.
The property equals to true if the class is connected to SRV-1 Blackfin robot/camera, otherwise it equals to false.
<note>The property is not updated by the class, when connection was lost or communication failure was detected (which results into ConnectionLostException exception). The property only shows status of Connect method.</note>
Referenced by SRVTest.MainForm.Disconnect(), SRVTest.MainForm.DriveMotors(), SRVTest.MainForm.qualityCombo_SelectedIndexChanged(), SRVTest.MainForm.resolutionCombo_SelectedIndexChanged(), and SRVTest.MainForm.srvDriverControl_SrvDrivingCommand().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Robotics.Surveyor/SRV1.cs