Doc: IGLib EXTENDED: NUnit.Framework.Syntax.StartsWithTest_IgnoreCase Class Reference
NUnit.Framework.Syntax.StartsWithTest_IgnoreCase Class Reference
Public Member Functions
void SetUp ()
Public Member Functions inherited from NUnit.Framework.Syntax.SyntaxTest
void SupportedByStaticSyntax ()
void SupportedByConstraintBuilder ()
void SupportedByInheritedSyntax ()
Additional Inherited Members
Protected Member Functions inherited from NUnit.Framework.Syntax.SyntaxTest
AssertionHelper Helper ()
ConstraintExpression Builder ()
Protected Attributes inherited from NUnit.Framework.Syntax.SyntaxTest
string parseTree
IResolveConstraint staticSyntax
IResolveConstraint inheritedSyntax
IResolveConstraint builderSyntax
Member Function Documentation
SetUp()
void NUnit.Framework.Syntax.StartsWithTest_IgnoreCase.SetUp () inline
References NUnit.Framework.Syntax.SyntaxTest.Builder(), NUnit.Framework.Syntax.SyntaxTest.builderSyntax, NUnit.Framework.Syntax.SyntaxTest.Helper(), NUnit.Framework.Constraints.StringConstraint.IgnoreCase, NUnit.Framework.Syntax.SyntaxTest.inheritedSyntax, NUnit.Framework.Syntax.SyntaxTest.parseTree, NUnit.Framework.Constraints.ConstraintFactory.StartsWith(), NUnit.Framework.Does.StartWith(), and NUnit.Framework.Syntax.SyntaxTest.staticSyntax.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Syntax/StringConstraints.cs