Doc: IGLib EXTENDED: IG.Neural.Applications.formLoadCSV Class Reference
IG.Neural.Applications.formLoadCSV Class Reference
GUI Form for loading the training set.
Public Member Functions
formLoadCSV ()
formLoadCSV ()
formLoadCSV ()
Public Attributes
TadejFormOld tadejForm
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void btnSelectTrainCSV_Click (object sender, EventArgs e)
void btnLoadCSV_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void btnSelectTrainCSV_Click (object sender, EventArgs e)
void btnLoadCSV_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void btnSelectTrainCSV_Click (object sender, EventArgs e)
void btnLoadCSV_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
string filePathLoad
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Button btnSelectTrainCSV
System.Windows.Forms.Label label1
System.Windows.Forms.Label label2
System.Windows.Forms.Label label3
System.Windows.Forms.Label label4
System.Windows.Forms.CheckBox cBxNameSpec
System.Windows.Forms.CheckBox cBxDescSpec
System.Windows.Forms.Button btnLoadCSV
System.Windows.Forms.OpenFileDialog openFdCSV
System.Windows.Forms.NumericUpDown numInputParm
System.Windows.Forms.NumericUpDown numOutputParam
System.Windows.Forms.CheckBox cBxTitlesSpec
System.Windows.Forms.Label label5
Detailed Description
GUI Form for loading the training set.
$A Tako78 May11;
Constructor & Destructor Documentation
formLoadCSV() [1/3]
IG.Neural.Applications.formLoadCSV.formLoadCSV () inline
References IG.Neural.Applications.formLoadCSV.InitializeComponent().
formLoadCSV() [2/3]
IG.Neural.Applications.formLoadCSV.formLoadCSV () inline
References IG.Neural.Applications.formLoadCSV.InitializeComponent().
formLoadCSV() [3/3]
IG.Neural.Applications.formLoadCSV.formLoadCSV () inline
References IG.Neural.Applications.formLoadCSV.InitializeComponent().
Member Function Documentation
btnSelectTrainCSV_Click() [1/3]
void IG.Neural.Applications.formLoadCSV.btnSelectTrainCSV_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.formLoadCSV.filePathLoad, and IG.Neural.Applications.formLoadCSV.tadejForm.
Referenced by IG.Neural.Applications.formLoadCSV.InitializeComponent().
btnLoadCSV_Click() [1/3]
void IG.Neural.Applications.formLoadCSV.btnLoadCSV_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.formLoadCSV.cBxDescSpec, IG.Neural.Applications.formLoadCSV.cBxNameSpec, IG.Neural.Applications.formLoadCSV.cBxTitlesSpec, IG.Neural.Applications.TadejFormOld.definitionData, IG.Neural.Applications.formLoadCSV.filePathLoad, IG.Neural.NeuralTadej.LoadTrainingDataCSV(), IG.Neural.Applications.formLoadCSV.numInputParm, IG.Neural.Applications.formLoadCSV.numOutputParam, IG.Neural.Applications.formLoadCSV.tadejForm, and IG.Neural.Applications.TadejFormOld.trainingData.
Referenced by IG.Neural.Applications.formLoadCSV.InitializeComponent().
Dispose() [1/3]
override void IG.Neural.Applications.formLoadCSV.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.formLoadCSV.components.
InitializeComponent() [1/3]
void IG.Neural.Applications.formLoadCSV.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.formLoadCSV.btnLoadCSV, IG.Neural.Applications.formLoadCSV.btnLoadCSV_Click(), IG.Neural.Applications.formLoadCSV.btnSelectTrainCSV, IG.Neural.Applications.formLoadCSV.btnSelectTrainCSV_Click(), IG.Neural.Applications.formLoadCSV.cBxDescSpec, IG.Neural.Applications.formLoadCSV.cBxNameSpec, IG.Neural.Applications.formLoadCSV.cBxTitlesSpec, IG.Neural.Applications.formLoadCSV.label1, IG.Neural.Applications.formLoadCSV.label2, IG.Neural.Applications.formLoadCSV.label3, IG.Neural.Applications.formLoadCSV.label4, IG.Neural.Applications.formLoadCSV.label5, IG.Neural.Applications.formLoadCSV.numInputParm, IG.Neural.Applications.formLoadCSV.numOutputParam, and IG.Neural.Applications.formLoadCSV.openFdCSV.
Referenced by IG.Neural.Applications.formLoadCSV.formLoadCSV().
btnSelectTrainCSV_Click() [2/3]
void IG.Neural.Applications.formLoadCSV.btnSelectTrainCSV_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.formLoadCSV.filePathLoad, and IG.Neural.Applications.formLoadCSV.tadejForm.
btnLoadCSV_Click() [2/3]
void IG.Neural.Applications.formLoadCSV.btnLoadCSV_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.formLoadCSV.cBxDescSpec, IG.Neural.Applications.formLoadCSV.cBxNameSpec, IG.Neural.Applications.formLoadCSV.cBxTitlesSpec, IG.Neural.Applications.TadejFormOld.definitionData, IG.Neural.Applications.formLoadCSV.filePathLoad, IG.Neural.NeuralTadej.LoadTrainingDataCSV(), IG.Neural.Applications.formLoadCSV.numInputParm, IG.Neural.Applications.formLoadCSV.numOutputParam, IG.Neural.Applications.formLoadCSV.tadejForm, and IG.Neural.Applications.TadejFormOld.trainingData.
Dispose() [2/3]
override void IG.Neural.Applications.formLoadCSV.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.formLoadCSV.components.
InitializeComponent() [2/3]
void IG.Neural.Applications.formLoadCSV.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.formLoadCSV.btnLoadCSV, IG.Neural.Applications.formLoadCSV.btnLoadCSV_Click(), IG.Neural.Applications.formLoadCSV.btnSelectTrainCSV, IG.Neural.Applications.formLoadCSV.btnSelectTrainCSV_Click(), IG.Neural.Applications.formLoadCSV.cBxDescSpec, IG.Neural.Applications.formLoadCSV.cBxNameSpec, IG.Neural.Applications.formLoadCSV.cBxTitlesSpec, IG.Neural.Applications.formLoadCSV.label1, IG.Neural.Applications.formLoadCSV.label2, IG.Neural.Applications.formLoadCSV.label3, IG.Neural.Applications.formLoadCSV.label4, IG.Neural.Applications.formLoadCSV.label5, IG.Neural.Applications.formLoadCSV.numInputParm, IG.Neural.Applications.formLoadCSV.numOutputParam, and IG.Neural.Applications.formLoadCSV.openFdCSV.
btnSelectTrainCSV_Click() [3/3]
void IG.Neural.Applications.formLoadCSV.btnSelectTrainCSV_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.formLoadCSV.filePathLoad, and IG.Neural.Applications.formLoadCSV.tadejForm.
btnLoadCSV_Click() [3/3]
void IG.Neural.Applications.formLoadCSV.btnLoadCSV_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.formLoadCSV.cBxDescSpec, IG.Neural.Applications.formLoadCSV.cBxNameSpec, IG.Neural.Applications.formLoadCSV.cBxTitlesSpec, IG.Neural.Applications.TadejFormOld.definitionData, IG.Neural.Applications.formLoadCSV.filePathLoad, IG.Neural.NeuralTadej.LoadTrainingDataCSV(), IG.Neural.Applications.formLoadCSV.numInputParm, IG.Neural.Applications.formLoadCSV.numOutputParam, IG.Neural.Applications.formLoadCSV.tadejForm, and IG.Neural.Applications.TadejFormOld.trainingData.
Dispose() [3/3]
override void IG.Neural.Applications.formLoadCSV.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.formLoadCSV.components.
InitializeComponent() [3/3]
void IG.Neural.Applications.formLoadCSV.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.formLoadCSV.btnLoadCSV, IG.Neural.Applications.formLoadCSV.btnLoadCSV_Click(), IG.Neural.Applications.formLoadCSV.btnSelectTrainCSV, IG.Neural.Applications.formLoadCSV.btnSelectTrainCSV_Click(), IG.Neural.Applications.formLoadCSV.cBxDescSpec, IG.Neural.Applications.formLoadCSV.cBxNameSpec, IG.Neural.Applications.formLoadCSV.cBxTitlesSpec, IG.Neural.Applications.formLoadCSV.label1, IG.Neural.Applications.formLoadCSV.label2, IG.Neural.Applications.formLoadCSV.label3, IG.Neural.Applications.formLoadCSV.label4, IG.Neural.Applications.formLoadCSV.label5, IG.Neural.Applications.formLoadCSV.numInputParm, IG.Neural.Applications.formLoadCSV.numOutputParam, and IG.Neural.Applications.formLoadCSV.openFdCSV.
Member Data Documentation
tadejForm
TadejFormOld IG.Neural.Applications.formLoadCSV.tadejForm
Referenced by IG.Neural.Applications.formLoadCSV.btnLoadCSV_Click(), IG.Neural.Applications.TadejFormOld.btnLoadTrainCSV_Click(), and IG.Neural.Applications.formLoadCSV.btnSelectTrainCSV_Click().
filePathLoad
string IG.Neural.Applications.formLoadCSV.filePathLoad private
Referenced by IG.Neural.Applications.formLoadCSV.btnLoadCSV_Click(), and IG.Neural.Applications.formLoadCSV.btnSelectTrainCSV_Click().
components
System ComponentModel IContainer IG.Neural.Applications.formLoadCSV.components = null private
Required designer variable.
Referenced by IG.Neural.Applications.formLoadCSV.Dispose().
btnSelectTrainCSV
System Windows Forms Button IG.Neural.Applications.formLoadCSV.btnSelectTrainCSV private
Referenced by IG.Neural.Applications.formLoadCSV.InitializeComponent().
label1
System Windows Forms Label IG.Neural.Applications.formLoadCSV.label1 private
Referenced by IG.Neural.Applications.formLoadCSV.InitializeComponent().
label2
System Windows Forms Label IG.Neural.Applications.formLoadCSV.label2 private
Referenced by IG.Neural.Applications.formLoadCSV.InitializeComponent().
label3
System Windows Forms Label IG.Neural.Applications.formLoadCSV.label3 private
Referenced by IG.Neural.Applications.formLoadCSV.InitializeComponent().
label4
System Windows Forms Label IG.Neural.Applications.formLoadCSV.label4 private
Referenced by IG.Neural.Applications.formLoadCSV.InitializeComponent().
cBxNameSpec
System Windows Forms CheckBox IG.Neural.Applications.formLoadCSV.cBxNameSpec private
Referenced by IG.Neural.Applications.formLoadCSV.btnLoadCSV_Click(), and IG.Neural.Applications.formLoadCSV.InitializeComponent().
cBxDescSpec
System Windows Forms CheckBox IG.Neural.Applications.formLoadCSV.cBxDescSpec private
Referenced by IG.Neural.Applications.formLoadCSV.btnLoadCSV_Click(), and IG.Neural.Applications.formLoadCSV.InitializeComponent().
btnLoadCSV
System Windows Forms Button IG.Neural.Applications.formLoadCSV.btnLoadCSV private
Referenced by IG.Neural.Applications.formLoadCSV.InitializeComponent().
openFdCSV
System Windows Forms OpenFileDialog IG.Neural.Applications.formLoadCSV.openFdCSV private
Referenced by IG.Neural.Applications.formLoadCSV.InitializeComponent().
numInputParm
System Windows Forms NumericUpDown IG.Neural.Applications.formLoadCSV.numInputParm private
Referenced by IG.Neural.Applications.formLoadCSV.btnLoadCSV_Click(), and IG.Neural.Applications.formLoadCSV.InitializeComponent().
numOutputParam
System Windows Forms NumericUpDown IG.Neural.Applications.formLoadCSV.numOutputParam private
Referenced by IG.Neural.Applications.formLoadCSV.btnLoadCSV_Click(), and IG.Neural.Applications.formLoadCSV.InitializeComponent().
cBxTitlesSpec
System Windows Forms CheckBox IG.Neural.Applications.formLoadCSV.cBxTitlesSpec private
Referenced by IG.Neural.Applications.formLoadCSV.btnLoadCSV_Click(), and IG.Neural.Applications.formLoadCSV.InitializeComponent().
label5
System Windows Forms Label IG.Neural.Applications.formLoadCSV.label5 private
Referenced by IG.Neural.Applications.formLoadCSV.InitializeComponent().
The documentation for this class was generated from the following files:
shelldev/lib/extended/LibNeuralExtForms/FormsExperimental/NeuralApplications/TadejFormOld/LoadCSV.cs
shelldev/lib/extended/LibNeuralExtForms/FormsExperimental/NeuralApplications/TadejFormOld/LoadCSV.Designer.cs