Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLASD4 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLASD4 Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLASD4 (DLAED6 dlaed6, DLASD5 dlasd5, DLAMCH dlamch)
DLASD4 ()
void Run (int N, int I, double[] D, int offset_d, double[] Z, int offset_z, ref double[] DELTA, int offset_delta, double RHO, ref double SIGMA, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
DLAED6 _dlaed6
DLASD5 _dlasd5
DLAMCH _dlamch
double[] DD = new double[3]
double[] ZZ = new double[3]
Static Private Attributes
const int MAXIT = 20
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
const double TWO = 2.0E+0
const double THREE = 3.0E+0
const double FOUR = 4.0E+0
const double EIGHT = 8.0E+0
const double TEN = 10.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
This subroutine computes the square root of the I-th updated eigenvalue of a positive symmetric rank-one modification to a positive diagonal matrix whose entries are given as the squares of the corresponding entries in the array d, and that
0 .LE. D(i) .LT. D(j) for i .LT. j
and that RHO .GT. 0. This is arranged by the calling routine, and is no loss in generality. The rank-one modified system is thus
diag(D) * diag(D) + RHO * Z * Z_transpose.
where we assume the Euclidean norm of Z is 1.
The method consists of approximating the rational functions in the secular equation by simpler interpolating rational functions.
/summary>
Constructor & Destructor Documentation
DLASD4() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLASD4.DLASD4 (DLAED6 dlaed6, DLASD5 dlasd5, DLAMCH dlamch) inline
DLASD4() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLASD4.DLASD4 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLASD4.Run (int N, int I, double[] D, int offset_d, double[] Z, int offset_z, ref double[] DELTA, int offset_delta, double RHO, ref double SIGMA, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
This subroutine computes the square root of the I-th updated eigenvalue of a positive symmetric rank-one modification to a positive diagonal matrix whose entries are given as the squares of the corresponding entries in the array d, and that
0 .LE. D(i) .LT. D(j) for i .LT. j
and that RHO .GT. 0. This is arranged by the calling routine, and is no loss in generality. The rank-one modified system is thus
diag(D) * diag(D) + RHO * Z * Z_transpose.
where we assume the Euclidean norm of Z is 1.
The method consists of approximating the rational functions in the secular equation by simpler interpolating rational functions.
/summary>
Parameters
N (input) INTEGER The length of all arrays. /param>
Parameters
I (input) INTEGER The index of the eigenvalue to be computed. 1 .LE. I .LE. N. /param>
Parameters
D (input) DOUBLE PRECISION array, dimension (N) The original eigenvalues. It is assumed that they are in order, 0 .LE. D(I) .LT. D(J) for I .LT. J. /param>
Parameters
Z (input) DOUBLE PRECISION array, dimension (N) The components of the updating vector. /param>
Parameters
DELTA (output) DOUBLE PRECISION array, dimension (N) If N .ne. 1, DELTA contains (D(j) - sigma_I) in its j-th component. If N = 1, then DELTA(1) = 1. The vector DELTA contains the information necessary to construct the (singular) eigenvectors. /param>
Parameters
RHO (input) DOUBLE PRECISION The scalar in the symmetric updating formula. /param>
Parameters
SIGMA (output) DOUBLE PRECISION The computed sigma_I, the I-th updated eigenvalue. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (N) If N .ne. 1, WORK contains (D(j) + sigma_I) in its j-th component. If N = 1, then WORK(1) = 1. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .GT. 0: if INFO = 1, the updating process failed. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLASD4.DD, DotNumerics.LinearAlgebra.CSLapack.DLASD4.EIGHT, DotNumerics.LinearAlgebra.CSLapack.DLASD4.FOUR, DotNumerics.LinearAlgebra.CSLapack.DLASD4.MAXIT, DotNumerics.LinearAlgebra.CSLapack.DLASD4.ONE, DotNumerics.LinearAlgebra.CSLapack.DLASD5.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED6.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD4.TEN, DotNumerics.LinearAlgebra.CSLapack.DLASD4.THREE, DotNumerics.LinearAlgebra.CSLapack.DLASD4.TWO, DotNumerics.LinearAlgebra.CSLapack.DLASD4.ZERO, and DotNumerics.LinearAlgebra.CSLapack.DLASD4.ZZ.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD8.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLASD3.Run().
Member Data Documentation
_dlaed6
DLAED6 DotNumerics.LinearAlgebra.CSLapack.DLASD4._dlaed6 private
_dlasd5
DLASD5 DotNumerics.LinearAlgebra.CSLapack.DLASD4._dlasd5 private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLASD4._dlamch private
MAXIT
const int DotNumerics.LinearAlgebra.CSLapack.DLASD4.MAXIT = 20 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD4.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLASD4.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD4.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLASD4.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD4.Run().
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DLASD4.TWO = 2.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD4.Run().
THREE
const double DotNumerics.LinearAlgebra.CSLapack.DLASD4.THREE = 3.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD4.Run().
FOUR
const double DotNumerics.LinearAlgebra.CSLapack.DLASD4.FOUR = 4.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD4.Run().
EIGHT
const double DotNumerics.LinearAlgebra.CSLapack.DLASD4.EIGHT = 8.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD4.Run().
TEN
const double DotNumerics.LinearAlgebra.CSLapack.DLASD4.TEN = 10.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD4.Run().
DD
double [] DotNumerics.LinearAlgebra.CSLapack.DLASD4.DD = new double[3] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD4.Run().
ZZ
double [] DotNumerics.LinearAlgebra.CSLapack.DLASD4.ZZ = new double[3] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD4.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlasd4.cs