Doc: IGLib EXTENDED: NUnit.Framework.TestCaseSourceAttribute Class Reference
NUnit.Framework.TestCaseSourceAttribute Class Reference
TestCaseSourceAttribute indicates the source to be used to provide test cases for a test method.
Public Member Functions
TestCaseSourceAttribute (string sourceName)
Construct with the name of the method, property or field that will provide data
TestCaseSourceAttribute (Type sourceType, string sourceName)
Construct with a Type and name
TestCaseSourceAttribute (Type sourceType)
Construct with a Type
IEnumerable< TestMethod > BuildFrom (IMethodInfo method, Test suite)
Construct one or more TestMethods from a given MethodInfo, using available parameter data.
Public Member Functions inherited from NUnit.Framework.NUnitAttribute
NUnitAttribute ()
Default constructor
Properties
string SourceName [get, private set]
The name of a the method, property or fiend to be used as a source
Type SourceType [get, private set]
A Type to be used as a source
string Category [get, set]
Gets or sets the category associated with every fixture created from this attribute. May be a single category or a comma-separated list.
Private Member Functions
IEnumerable< ITestCaseData > GetTestCasesFor (IMethodInfo method)
Returns a set of ITestCaseDataItems for use as arguments to a parameterized test method.
IEnumerable GetTestCaseSource (IMethodInfo method)
Static Private Member Functions
static IEnumerable SourceMustBeStaticError ()
Private Attributes
NUnitTestCaseBuilder _builder = new NUnitTestCaseBuilder()
Detailed Description
TestCaseSourceAttribute indicates the source to be used to provide test cases for a test method.
Constructor & Destructor Documentation
TestCaseSourceAttribute() [1/3]
NUnit.Framework.TestCaseSourceAttribute.TestCaseSourceAttribute (string sourceName) inline
Construct with the name of the method, property or field that will provide data
Parameters
sourceName The name of a static method, property or field that will provide data.
References NUnit.Framework.TestCaseSourceAttribute.SourceName.
TestCaseSourceAttribute() [2/3]
NUnit.Framework.TestCaseSourceAttribute.TestCaseSourceAttribute (Type sourceType, string sourceName) inline
Construct with a Type and name
Parameters
sourceType The Type that will provide data
sourceName The name of a static method, property or field that will provide data.
References NUnit.Framework.TestCaseSourceAttribute.SourceName, and NUnit.Framework.TestCaseSourceAttribute.SourceType.
TestCaseSourceAttribute() [3/3]
NUnit.Framework.TestCaseSourceAttribute.TestCaseSourceAttribute (Type sourceType) inline
Construct with a Type
Parameters
sourceType The type that will provide data
References NUnit.Framework.TestCaseSourceAttribute.SourceType.
Member Function Documentation
BuildFrom()
IEnumerable<TestMethod> NUnit.Framework.TestCaseSourceAttribute.BuildFrom (IMethodInfo method, Test suite) inline
Construct one or more TestMethods from a given MethodInfo, using available parameter data.
Parameters
method The IMethod for which tests are to be constructed.
suite The suite to which the tests will be added.
Returns
One or more TestMethods
Implements NUnit.Framework.Interfaces.ITestBuilder.
References NUnit.Framework.TestCaseSourceAttribute._builder, NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.BuildTestMethod(), and NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor().
GetTestCasesFor()
IEnumerable<ITestCaseData> NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor (IMethodInfo method) inline private
Returns a set of ITestCaseDataItems for use as arguments to a parameterized test method.
Parameters
method The method for which data is needed.
Returns
References NUnit.Framework.Interfaces.IPropertyBag.Add(), NUnit.Framework.Internal.PropertyNames.Category, NUnit.Framework.TestCaseSourceAttribute.Category, NUnit.Framework.Interfaces.IMethodInfo.GetParameters(), NUnit.Framework.TestCaseSourceAttribute.GetTestCaseSource(), NUnit.Framework.Interfaces.IMethodInfo.IsGenericMethodDefinition, and NUnit.Framework.Internal.TestParameters.Properties.
Referenced by NUnit.Framework.TestCaseSourceAttribute.BuildFrom().
GetTestCaseSource()
IEnumerable NUnit.Framework.TestCaseSourceAttribute.GetTestCaseSource (IMethodInfo method) inline private
References NUnit.Framework.Internal.Reflect.Construct(), NUnit.Framework.TestCaseSourceAttribute.SourceMustBeStaticError(), NUnit.Framework.TestCaseSourceAttribute.SourceName, NUnit.Framework.TestCaseSourceAttribute.SourceType, NUnit.Framework.Interfaces.ITypeInfo.Type, and NUnit.Framework.Interfaces.IMethodInfo.TypeInfo.
Referenced by NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor().
SourceMustBeStaticError()
static IEnumerable NUnit.Framework.TestCaseSourceAttribute.SourceMustBeStaticError () inline static private
References NUnit.Framework.Internal.PropertyNames.SkipReason.
Referenced by NUnit.Framework.TestCaseSourceAttribute.GetTestCaseSource().
Member Data Documentation
_builder
NUnitTestCaseBuilder NUnit.Framework.TestCaseSourceAttribute._builder = new NUnitTestCaseBuilder() private
Referenced by NUnit.Framework.TestCaseSourceAttribute.BuildFrom().
Property Documentation
SourceName
string NUnit.Framework.TestCaseSourceAttribute.SourceName get private set
The name of a the method, property or fiend to be used as a source
Referenced by NUnit.Framework.TestCaseSourceAttribute.GetTestCaseSource(), and NUnit.Framework.TestCaseSourceAttribute.TestCaseSourceAttribute().
SourceType
Type NUnit.Framework.TestCaseSourceAttribute.SourceType get private set
A Type to be used as a source
Referenced by NUnit.Framework.TestCaseSourceAttribute.GetTestCaseSource(), and NUnit.Framework.TestCaseSourceAttribute.TestCaseSourceAttribute().
Category
string NUnit.Framework.TestCaseSourceAttribute.Category get set
Gets or sets the category associated with every fixture created from this attribute. May be a single category or a comma-separated list.
Referenced by NUnit.Framework.TestCaseSourceAttribute.GetTestCasesFor().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Attributes/TestCaseSourceAttribute.cs