Doc: IGLib EXTENDED: IG.Neural.AnalysisFileServerNeural Class Reference
IG.Neural.AnalysisFileServerNeural Class Reference
Class containing direct analysis (in optimization) based on neural network optimization.
Public Member Functions
AnalysisFileServerNeural (string workingDirectoryPath)
Constructor, sets object's working directory to the specified path.
virtual void Analyse (IAnalysisResults analysisData)
Performs analysis - calculates requested results and writes them to the provided data structure.
override void ClearMessages ()
Clears all messages in the neural network approximator's file client/server directory.
virtual void ServerAnalyse ()
Performs server-side direct analysis. Reads analysis input from standard location, calculates output and writes it to the standard location.
virtual void ClientCalculateAnalysisResults (AnalysisResults anRes)
Calculates analysis results by using the analysis server.
virtual void ClientTestCalculateAnalysisResults (string inputFilePath, bool reqObjective, bool reqConstraints, bool reqObjectiveGradient, bool reqConstraintGradients, string outputFilePath)
Performs client-side test calculation of analysis response.
Public Member Functions inherited from IG.Neural.ApproximationFileServerNeural
ApproximationFileServerNeural (string workingDirectoryPath)
virtual void ServerCalculateApproximation ()
Performs server-side calculation of the approximation. Reads input from standard location, calculates output and writes it to the standard location.
virtual void ClientCalculateApproximation (IVector input, ref IVector output)
Calculates the neural network based approximated values.
virtual void ClientTestCalculateApproximation (string inputFilePath, string outputFilePath)
Performs client-side test calculation of neural network based approximation where input parameters are read from a specified JSON file, and calculated output values are written to the specified file.
Protected Member Functions
virtual void AnalysisToApproximationInput (IVector anInput, ref IVector approximationInput)
Converts analysis input parameters to approximation input parameters.
virtual void ApproximationToAnalysisOutput (IVector approxOuptut, IAnalysisResults anResults)
Converts approximation output to direct analysis results.
Sets objective function to sum of squares of approximated values.
WARNING:
This method should be overridden in derived classes.
Properties
OptFileManager OptimizationFileManager [get, set]
int NumParameters [get, set]
Number of parameters.
int NumObjectives [get, set]
Number of objective functions (normally 1 for this type, but can be 0).
int NumConstraints [get, set]
Number of constraints.
int NumEqualityConstraints [get, set]
Number of equality constraints.
Properties inherited from IG.Neural.ApproximationFileServerNeural
virtual string Directory [get, protected set]
Gets or sets working directory of the current object.
NeuraApproximationFileManager NeuralFileManager [get, set]
Properties inherited from IG.Num.IAnalysis
int NumParameters [get, set]
Number of parameters.
int NumObjectives [get, set]
Number of objective functions (normally 1 for this type, but can be 0).
int NumConstraints [get, set]
Number of constraints.
int NumEqualityConstraints [get, set]
Number of equality constraints.
Private Attributes
OptFileManager _optFileManager
Detailed Description
Class containing direct analysis (in optimization) based on neural network optimization.
Constructor & Destructor Documentation
AnalysisFileServerNeural()
IG.Neural.AnalysisFileServerNeural.AnalysisFileServerNeural (string workingDirectoryPath) inline
Constructor, sets object's working directory to the specified path.
Parameters
workingDirectoryPath
References IG.Num.OptFileManager.Analysis, and IG.Neural.AnalysisFileServerNeural.OptimizationFileManager.
Member Function Documentation
Analyse()
virtual void IG.Neural.AnalysisFileServerNeural.Analyse (IAnalysisResults analysisData) inline virtual
Performs analysis - calculates requested results and writes them to the provided data structure.
Parameters
analysisData Data structure where analysis request parameters are obtained and where analysis results are written.
Implements IG.Num.IAnalysis.
References IG.Neural.AnalysisFileServerNeural.AnalysisToApproximationInput(), IG.Neural.AnalysisFileServerNeural.ApproximationToAnalysisOutput(), IG.Neural.NeuraApproximationFileManager.ClientReadNeuralOutput(), IG.Neural.NeuraApproximationFileManager.ClientWriteNeuralInput(), IG.Neural.ApproximationFileServerNeural.NeuralFileManager, IG.Num.IAnalysisResults.Parameters, and IG.Neural.NeuraApproximationFileManager.ServerCalculateApproximation().
AnalysisToApproximationInput()
virtual void IG.Neural.AnalysisFileServerNeural.AnalysisToApproximationInput (IVector anInput, ref IVector approximationInput) inline protected virtual
Converts analysis input parameters to approximation input parameters.
Parameters
anInput Input parameters for direct analysis.
approximationInput Input parameters for response approximation.
Reimplemented in IG.Neural.AnalysisFileServerNeuralExtBase, IG.Neural.AnalysisFileServerNeuralExtBase, and IG.Neural.AnalysisFileServerNeuralStoreBase.
References IG.Num.VectorBase.Copy().
Referenced by IG.Neural.AnalysisFileServerNeural.Analyse().
ApproximationToAnalysisOutput()
virtual void IG.Neural.AnalysisFileServerNeural.ApproximationToAnalysisOutput (IVector approxOuptut, IAnalysisResults anResults) inline protected virtual
Converts approximation output to direct analysis results.
Sets objective function to sum of squares of approximated values.
WARNING:
This method should be overridden in derived classes.
Parameters
approxOuptut Vector of approximated output values.
anResults Direct analysis results.
Reimplemented in IG.Neural.AnalysisFileServerNeuralExtBase, IG.Neural.AnalysisFileServerNeuralExtBase, and IG.Neural.AnalysisFileServerNeuralStoreBase.
References IG.Num.IAnalysisResults.CalculatedObjective, IG.Num.IVector< T >.Length, and IG.Num.IAnalysisResults.ReqObjective.
Referenced by IG.Neural.AnalysisFileServerNeural.Analyse().
ClearMessages()
override void IG.Neural.AnalysisFileServerNeural.ClearMessages () inline virtual
Clears all messages in the neural network approximator's file client/server directory.
Reimplemented from IG.Neural.ApproximationFileServerNeural.
References IG.Neural.NeuraApproximationFileManager.ClearMessages(), and IG.Neural.ApproximationFileServerNeural.NeuralFileManager.
ServerAnalyse()
virtual void IG.Neural.AnalysisFileServerNeural.ServerAnalyse () inline virtual
Performs server-side direct analysis. Reads analysis input from standard location, calculates output and writes it to the standard location.
References IG.Neural.AnalysisFileServerNeural.OptimizationFileManager, and IG.Num.OptFileManager.ServerAnalyse().
Referenced by IG.Neural.AnalysisFileServerNeuralExtBase.CmdAnalyseServer_ijs_11_05(), and IG.Neural.AnalysisFileServerNeuralStoreBase.CmdAnalyseServer_ijs_11_05().
ClientCalculateAnalysisResults()
virtual void IG.Neural.AnalysisFileServerNeural.ClientCalculateAnalysisResults (AnalysisResults anRes) inline virtual
Calculates analysis results by using the analysis server.
Parameters
inputParameters Intput parameters for which approximation is calculated.
outputValues Vector where approximation output values are stored.
References IG.Num.OptFileManager.ClientCalculateAnalysisResults(), and IG.Neural.AnalysisFileServerNeural.OptimizationFileManager.
ClientTestCalculateAnalysisResults()
virtual void IG.Neural.AnalysisFileServerNeural.ClientTestCalculateAnalysisResults (string inputFilePath, bool reqObjective, bool reqConstraints, bool reqObjectiveGradient, bool reqConstraintGradients, string outputFilePath) inline virtual
Performs client-side test calculation of analysis response.
Parameters
inputFilePath Path to the JSON file where input parameters are read from. The file pointed at must exist.
reqObjective Flag indicating whether objective function must be calculated.
reqConstraints Flag indicating whether constraint functions must be calculated.
reqGradObjective Flag indicating whether objective function gradientmust be calculated.
reqGradOConstraints Fleg indicating whether constraint function gradients must be calculated.
deletedFilePath Path of a file where the calculated analysis response in JSON is written to. It can be null or empty string, in this case response is not written to a file (but it is output on console).
References IG.Num.OptFileManager.ClientTestCalculateAnalysisResults(), and IG.Neural.AnalysisFileServerNeural.OptimizationFileManager.
Referenced by IG.Neural.AnalysisFileServerNeuralExtBase.CmdAnalyseClient_ijs_11_05(), and IG.Neural.AnalysisFileServerNeuralStoreBase.CmdAnalyseClient_ijs_11_05().
Member Data Documentation
_optFileManager
OptFileManager IG.Neural.AnalysisFileServerNeural._optFileManager private
Property Documentation
OptimizationFileManager
OptFileManager IG.Neural.AnalysisFileServerNeural.OptimizationFileManager get set
Referenced by IG.Neural.AnalysisFileServerNeural.AnalysisFileServerNeural(), IG.Neural.AnalysisFileServerNeural.ClientCalculateAnalysisResults(), IG.Neural.AnalysisFileServerNeural.ClientTestCalculateAnalysisResults(), IG.Neural.AnalysisFileServerNeuralExtBase.CmdAnalyseServer_ijs_11_05(), IG.Neural.AnalysisFileServerNeuralStoreBase.CmdAnalyseServer_ijs_11_05(), and IG.Neural.AnalysisFileServerNeural.ServerAnalyse().
NumParameters
int IG.Neural.AnalysisFileServerNeural.NumParameters get set
Number of parameters.
NumObjectives
int IG.Neural.AnalysisFileServerNeural.NumObjectives get set
Number of objective functions (normally 1 for this type, but can be 0).
NumConstraints
int IG.Neural.AnalysisFileServerNeural.NumConstraints get set
Number of constraints.
NumEqualityConstraints
int IG.Neural.AnalysisFileServerNeural.NumEqualityConstraints get set
Number of equality constraints.
The documentation for this class was generated from the following file:
iglib/extensions/iglibneural/neural/neural_server/NeuralAnalysisFileServer.cs