Doc: IGLib EXTENDED: NUnit.Engine.Tests.TestEngineResultTests Class Reference
NUnit.Engine.Tests.TestEngineResultTests Class Reference
Public Member Functions
void CanCreateFromXmlString ()
void CanCreateFromXmlNode ()
Static Private Attributes
static readonly string xmlText = "<test-assembly result=\"Passed\" total=\"23\" passed=\"23\" failed=\"0\" inconclusive=\"0\" skipped=\"0\" asserts=\"40\" />"
Member Function Documentation
CanCreateFromXmlString()
void NUnit.Engine.Tests.TestEngineResultTests.CanCreateFromXmlString () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Engine.TestEngineResult.IsSingle, NUnit.Framework.Assert.That(), NUnit.Framework.Assert.True(), NUnit.Engine.TestEngineResult.Xml, and NUnit.Engine.Tests.TestEngineResultTests.xmlText.
CanCreateFromXmlNode()
void NUnit.Engine.Tests.TestEngineResultTests.CanCreateFromXmlNode () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Engine.TestEngineResult.IsSingle, NUnit.Framework.Assert.That(), NUnit.Framework.Assert.True(), NUnit.Engine.TestEngineResult.Xml, and NUnit.Engine.Tests.TestEngineResultTests.xmlText.
Member Data Documentation
xmlText
readonly string NUnit.Engine.Tests.TestEngineResultTests.xmlText = "<test-assembly result=\"Passed\" total=\"23\" passed=\"23\" failed=\"0\" inconclusive=\"0\" skipped=\"0\" asserts=\"40\" />" static private
Referenced by NUnit.Engine.Tests.TestEngineResultTests.CanCreateFromXmlNode(), and NUnit.Engine.Tests.TestEngineResultTests.CanCreateFromXmlString().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/TestEngineResultTests.cs