Doc: IGLib EXTENDED: NUnit.Framework.Internal.Execution.TextCapture Class Reference
NUnit.Framework.Internal.Execution.TextCapture Class Reference
The TextCapture class intercepts console output and writes it to the current execution context, if one is present on the thread. If no execution context is found, the output is written to a default destination, normally the original destination of the intercepted output.
Public Member Functions
TextCapture (TextWriter defaultWriter)
Construct a TextCapture object
override void Write (char value)
Writes a single character
override void Write (string value)
Writes a string
override void WriteLine (string value)
Writes a string followed by a line terminator
Properties
override System.Text.Encoding Encoding [get]
Gets the Encoding in use by this TextWriter
Private Attributes
TextWriter _defaultWriter
Detailed Description
The TextCapture class intercepts console output and writes it to the current execution context, if one is present on the thread. If no execution context is found, the output is written to a default destination, normally the original destination of the intercepted output.
Constructor & Destructor Documentation
TextCapture()
NUnit.Framework.Internal.Execution.TextCapture.TextCapture (TextWriter defaultWriter) inline
Construct a TextCapture object
Parameters
defaultWriter The default destination for non-intercepted output
References NUnit.Framework.Internal.Execution.TextCapture._defaultWriter.
Member Function Documentation
Write() [1/2]
override void NUnit.Framework.Internal.Execution.TextCapture.Write (char value) inline
Writes a single character
Parameters
value The char to write
References NUnit.Framework.Internal.Execution.TextCapture._defaultWriter, NUnit.Framework.Internal.TestExecutionContext.CurrentResult, NUnit.Framework.Internal.TestExecutionContext.GetTestExecutionContext(), and NUnit.Framework.Internal.TestResult.OutWriter.
Write() [2/2]
override void NUnit.Framework.Internal.Execution.TextCapture.Write (string value) inline
Writes a string
Parameters
value The string to write
References NUnit.Framework.Internal.Execution.TextCapture._defaultWriter, NUnit.Framework.Internal.TestExecutionContext.CurrentResult, NUnit.Framework.Internal.TestExecutionContext.GetTestExecutionContext(), and NUnit.Framework.Internal.TestResult.OutWriter.
WriteLine()
override void NUnit.Framework.Internal.Execution.TextCapture.WriteLine (string value) inline
Writes a string followed by a line terminator
Parameters
value The string to write
References NUnit.Framework.Internal.Execution.TextCapture._defaultWriter, NUnit.Framework.Internal.TestExecutionContext.CurrentResult, NUnit.Framework.Internal.TestExecutionContext.GetTestExecutionContext(), and NUnit.Framework.Internal.TestResult.OutWriter.
Member Data Documentation
_defaultWriter
TextWriter NUnit.Framework.Internal.Execution.TextCapture._defaultWriter private
Referenced by NUnit.Framework.Internal.Execution.TextCapture.TextCapture(), NUnit.Framework.Internal.Execution.TextCapture.Write(), and NUnit.Framework.Internal.Execution.TextCapture.WriteLine().
Property Documentation
Encoding
override System.Text.Encoding NUnit.Framework.Internal.Execution.TextCapture.Encoding get
Gets the Encoding in use by this TextWriter
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/Execution/TextCapture.cs