Doc: IGLib EXTENDED: NUnit.Framework.Internal.TestNameGenerator Class Reference
NUnit.Framework.Internal.TestNameGenerator Class Reference
TestNameGenerator is able to create test names according to a coded pattern.
Classes
class ArgListFragment
class ArgumentFragment
class ClassFullNameFragment
class ClassNameFragment
class FixedTextFragment
class MethodFullNameFragment
class MethodNameFragment
class NameFragment
class NamespaceFragment
class TestIDFragment
Public Member Functions
TestNameGenerator (string pattern)
Construct a TestNameGenerator
string GetDisplayName (TestMethod testMethod)
Get the display name for a TestMethod and it's arguments
string GetDisplayName (TestMethod testMethod, object[] args)
Get the display name for a TestMethod and it's arguments
Private Member Functions
string GetDisplayName (MethodInfo method)
Get the display name for a MethodInfo
string GetDisplayName (MethodInfo method, object[] args)
Get the display name for a method with args
Private Attributes
List< NameFragment > _fragments = new List<NameFragment>()
Detailed Description
TestNameGenerator is able to create test names according to a coded pattern.
Constructor & Destructor Documentation
TestNameGenerator()
NUnit.Framework.Internal.TestNameGenerator.TestNameGenerator (string pattern) inline
Construct a TestNameGenerator
Parameters
pattern The pattern used by this generator.
References NUnit.Framework.Internal.TestNameGenerator._fragments.
Member Function Documentation
GetDisplayName() [1/4]
string NUnit.Framework.Internal.TestNameGenerator.GetDisplayName (TestMethod testMethod) inline
Get the display name for a TestMethod and it's arguments
Parameters
testMethod A TestMethod
Returns
The display name
Referenced by NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.BuildTestMethod(), NUnit.Framework.Internal.Tests.TestNameGeneratorTests.ErrorInPattern(), NUnit.Framework.Internal.Tests.TestNameGeneratorTests.GenericTestNames(), NUnit.Framework.Internal.TestNameGenerator.GetDisplayName(), NUnit.Framework.Internal.Tests.TestNameGeneratorTests.ParameterizedTests(), NUnit.Framework.Internal.Tests.TestNameGeneratorTests.SimpleTestNames(), and NUnit.Framework.Internal.Tests.TestNameGeneratorTests.SpecialNamedValues().
GetDisplayName() [2/4]
string NUnit.Framework.Internal.TestNameGenerator.GetDisplayName (TestMethod testMethod, object[] args) inline
Get the display name for a TestMethod and it's arguments
Parameters
testMethod A TestMethod
args Arguments to be used
Returns
The display name
References NUnit.Framework.Internal.TestNameGenerator._fragments.
GetDisplayName() [3/4]
string NUnit.Framework.Internal.TestNameGenerator.GetDisplayName (MethodInfo method) inline private
Get the display name for a MethodInfo
Parameters
method A MethodInfo
Returns
The display name
References NUnit.Framework.Internal.TestNameGenerator.GetDisplayName().
GetDisplayName() [4/4]
string NUnit.Framework.Internal.TestNameGenerator.GetDisplayName (MethodInfo method, object[] args) inline private
Get the display name for a method with args
Parameters
method A MethodInfo
args Argument list for the method
Returns
The display name
References NUnit.Framework.Internal.TestNameGenerator._fragments.
Member Data Documentation
_fragments
List<NameFragment> NUnit.Framework.Internal.TestNameGenerator._fragments = new List<NameFragment>() private
Referenced by NUnit.Framework.Internal.TestNameGenerator.GetDisplayName(), and NUnit.Framework.Internal.TestNameGenerator.TestNameGenerator().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/TestNameGenerator.cs