Doc: IGLib EXTENDED: AForge.Imaging.Filters.IterativeThreshold Class Reference
AForge.Imaging.Filters.IterativeThreshold Class Reference
Iterative threshold search and binarization.
Public Member Functions
IterativeThreshold ()
Initializes a new instance of the IterativeThreshold class.
IterativeThreshold (int minError)
Initializes a new instance of the IterativeThreshold class.
IterativeThreshold (int minError, int threshold)
Initializes a new instance of the IterativeThreshold class.
int CalculateThreshold (Bitmap image, Rectangle rect)
Calculate binarization threshold for the given image.
int CalculateThreshold (BitmapData image, Rectangle rect)
Calculate binarization threshold for the given image.
int CalculateThreshold (UnmanagedImage image, Rectangle rect)
Calculate binarization threshold for the given image.
Public Member Functions inherited from AForge.Imaging.Filters.Threshold
Threshold ()
Initializes a new instance of the Threshold class.
Threshold (int threshold)
Initializes a new instance of the Threshold class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image, Rectangle rect)
Process the filter on the specified image.
Protected Member Functions inherited from AForge.Imaging.Filters.Threshold
override unsafe void ProcessFilter (UnmanagedImage image, Rectangle rect)
Process the filter on the specified image.
Properties
int MinimumError [get, set]
Minimum error, value when iterative threshold search is stopped.
Properties inherited from AForge.Imaging.Filters.Threshold
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
int ThresholdValue [get, set]
Threshold value.
Properties inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
int minError = 0
Additional Inherited Members
Protected Attributes inherited from AForge.Imaging.Filters.Threshold
int threshold = 128
Threshold value.
Detailed Description
Iterative threshold search and binarization.
The algorithm works in the following way:
select any start threshold;
compute average value of Background (µB) and Object (µO) values: 1) all pixels with a value that is below threshold, belong to the Background values; 2) all pixels greater or equal threshold, belong to the Object values.
calculate new thresghold: (µB + µO) / 2;
if |oldThreshold - newThreshold| is less than a given manimum allowed error, then stop iteration process and create the binary image with the new threshold.
For additional information see Digital Image Processing, Gonzalez/Woods. Ch.10 page:599.
The filter accepts 8 and 16 bpp grayscale images for processing.
<note>Since the filter can be applied as to 8 bpp and to 16 bpp images, the initial value of Threshold.ThresholdValue property should be set appropriately to the pixel format. In the case of 8 bpp images the threshold value is in the [0, 255] range, but in the case of 16 bpp images the threshold value is in the [0, 65535] range.</note>
Sample usage:
// create filter
IterativeThreshold filter = new IterativeThreshold(2, 128);
// apply the filter
Bitmap newImage = filter.Apply(image);
Initial image:
Result image (calculated threshold is 102):
See also
OtsuThreshold, SISThreshold
Constructor & Destructor Documentation
IterativeThreshold() [1/3]
AForge.Imaging.Filters.IterativeThreshold.IterativeThreshold () inline
Initializes a new instance of the IterativeThreshold class.
IterativeThreshold() [2/3]
AForge.Imaging.Filters.IterativeThreshold.IterativeThreshold (int minError) inline
Initializes a new instance of the IterativeThreshold class.
Parameters
minError Minimum allowed error, that ends the iteration process.
References AForge.Imaging.Filters.IterativeThreshold.minError.
IterativeThreshold() [3/3]
AForge.Imaging.Filters.IterativeThreshold.IterativeThreshold (int minError, int threshold) inline
Initializes a new instance of the IterativeThreshold class.
Parameters
minError Minimum allowed error, that ends the iteration process.
threshold Initial threshold value.
References AForge.Imaging.Filters.IterativeThreshold.minError, and AForge.Imaging.Filters.Threshold.threshold.
Member Function Documentation
CalculateThreshold() [1/3]
int AForge.Imaging.Filters.IterativeThreshold.CalculateThreshold (Bitmap image, Rectangle rect) inline
Calculate binarization threshold for the given image.
Parameters
image Image to calculate binarization threshold for.
rect Rectangle to calculate binarization threshold for.
Returns
Returns binarization threshold.
The method is used to calculate binarization threshold only. The threshold later may be applied to the image using Threshold image processing filter.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported by the routine. It should 8 bpp grayscale (indexed) or 16 bpp grayscale image.
References AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.Filters.IterativeThreshold.CalculateThreshold(), and AForge.Imaging.Filters.IterativeThreshold.ProcessFilter().
CalculateThreshold() [2/3]
int AForge.Imaging.Filters.IterativeThreshold.CalculateThreshold (BitmapData image, Rectangle rect) inline
Calculate binarization threshold for the given image.
Parameters
image Image to calculate binarization threshold for.
rect Rectangle to calculate binarization threshold for.
Returns
Returns binarization threshold.
The method is used to calculate binarization threshold only. The threshold later may be applied to the image using Threshold image processing filter.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported by the routine. It should 8 bpp grayscale (indexed) or 16 bpp grayscale image.
References AForge.Imaging.Filters.IterativeThreshold.CalculateThreshold().
CalculateThreshold() [3/3]
int AForge.Imaging.Filters.IterativeThreshold.CalculateThreshold (UnmanagedImage image, Rectangle rect) inline
Calculate binarization threshold for the given image.
Parameters
image Image to calculate binarization threshold for.
rect Rectangle to calculate binarization threshold for.
Returns
Returns binarization threshold.
The method is used to calculate binarization threshold only. The threshold later may be applied to the image using Threshold image processing filter.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported by the routine. It should 8 bpp grayscale (indexed) or 16 bpp grayscale image.
References AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.Filters.IterativeThreshold.minError, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.Filters.Threshold.threshold.
ProcessFilter()
override unsafe void AForge.Imaging.Filters.IterativeThreshold.ProcessFilter (UnmanagedImage image, Rectangle rect) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
rect Image rectangle for processing by the filter.
Implements AForge.Imaging.Filters.BaseInPlacePartialFilter.
References AForge.Imaging.Filters.IterativeThreshold.CalculateThreshold(), and AForge.Imaging.Filters.Threshold.threshold.
Member Data Documentation
minError
int AForge.Imaging.Filters.IterativeThreshold.minError = 0 private
Referenced by AForge.Imaging.Filters.IterativeThreshold.CalculateThreshold(), and AForge.Imaging.Filters.IterativeThreshold.IterativeThreshold().
Property Documentation
MinimumError
int AForge.Imaging.Filters.IterativeThreshold.MinimumError get set
Minimum error, value when iterative threshold search is stopped.
Default value is set to 0.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Adaptive Binarization/IterativeThreshold.cs