Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLARFT Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLARFT Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLARFT (DGEMV dgemv, DTRMV dtrmv, LSAME lsame)
DLARFT ()
void Run (string DIRECT, string STOREV, int N, int K, ref double[] V, int offset_v, int LDV, double[] TAU, int offset_tau, ref double[] T, int offset_t, int LDT)
Private Attributes
DGEMV _dgemv
DTRMV _dtrmv
LSAME _lsame
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLARFT forms the triangular factor T of a real block reflector H of order n, which is defined as a product of k elementary reflectors.
If DIRECT = 'F', H = H(1) H(2) . . . H(k) and T is upper triangular;
If DIRECT = 'B', H = H(k) . . . H(2) H(1) and T is lower triangular.
If STOREV = 'C', the vector which defines the elementary reflector H(i) is stored in the i-th column of the array V, and
H = I - V * T * V'
If STOREV = 'R', the vector which defines the elementary reflector H(i) is stored in the i-th row of the array V, and
H = I - V' * T * V
/summary>
Constructor & Destructor Documentation
DLARFT() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLARFT.DLARFT (DGEMV dgemv, DTRMV dtrmv, LSAME lsame) inline
DLARFT() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLARFT.DLARFT () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLARFT.Run (string DIRECT, string STOREV, int N, int K, ref double[] V, int offset_v, int LDV, double[] TAU, int offset_tau, ref double[] T, int offset_t, int LDT) inline
Purpose
DLARFT forms the triangular factor T of a real block reflector H of order n, which is defined as a product of k elementary reflectors.
If DIRECT = 'F', H = H(1) H(2) . . . H(k) and T is upper triangular;
If DIRECT = 'B', H = H(k) . . . H(2) H(1) and T is lower triangular.
If STOREV = 'C', the vector which defines the elementary reflector H(i) is stored in the i-th column of the array V, and
H = I - V * T * V'
If STOREV = 'R', the vector which defines the elementary reflector H(i) is stored in the i-th row of the array V, and
H = I - V' * T * V
/summary>
Parameters
DIRECT (input) CHARACTER*1 Specifies the order in which the elementary reflectors are multiplied to form the block reflector: = 'F': H = H(1) H(2) . . . H(k) (Forward) = 'B': H = H(k) . . . H(2) H(1) (Backward) /param>
Parameters
STOREV (input) CHARACTER*1 Specifies how the vectors which define the elementary reflectors are stored (see also Further Details): = 'C': columnwise = 'R': rowwise /param>
Parameters
N (input) INTEGER The order of the block reflector H. N .GE. 0. /param>
Parameters
K (input) INTEGER The order of the triangular factor T (= the number of elementary reflectors). K .GE. 1. /param>
Parameters
V (input/output) DOUBLE PRECISION array, dimension (LDV,K) if STOREV = 'C' (LDV,N) if STOREV = 'R' The matrix V. See further details. /param>
Parameters
LDV (input) INTEGER The leading dimension of the array V. If STOREV = 'C', LDV .GE. max(1,N); if STOREV = 'R', LDV .GE. K. /param>
Parameters
TAU (input) DOUBLE PRECISION array, dimension (K) TAU(i) must contain the scalar factor of the elementary reflector H(i). /param>
Parameters
T (output) DOUBLE PRECISION array, dimension (LDT,K) The k by k triangular factor T of the block reflector. If DIRECT = 'F', T is upper triangular; if DIRECT = 'B', T is lower triangular. The rest of the array is not used. /param>
Parameters
LDT (input) INTEGER The leading dimension of the array T. LDT .GE. K. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLARFT.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRMV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLARFT.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGELQF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGERQF.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGLQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGQL.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMQL.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMRQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMQR.Run(), and DotNumerics.LinearAlgebra.CSLapack.DORMLQ.Run().
Member Data Documentation
_dgemv
DGEMV DotNumerics.LinearAlgebra.CSLapack.DLARFT._dgemv private
_dtrmv
DTRMV DotNumerics.LinearAlgebra.CSLapack.DLARFT._dtrmv private
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLARFT._lsame private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLARFT.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLARFT.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLARFT.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLARFT.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlarft.cs