Doc: IGLib EXTENDED: NUnit.Engine.TestEngineActivator Class Reference
NUnit.Engine.TestEngineActivator Class Reference
TestEngineActivator creates an instance of the test engine and returns an ITestEngine interface.
Static Public Member Functions
static ITestEngine CreateInstance (bool privateCopy=false)
Create an instance of the test engine.
static ITestEngine CreateInstance (Version minVersion, bool privateCopy=false)
Create an instance of the test engine with a minimum version.
Static Private Member Functions
static Assembly FindNewestEngine (Version minVersion, bool privateCopy)
static Assembly CheckPathForEngine (string path, Version minVersion, ref Version newestVersionFound, Assembly newestAssemblyFound)
static string FindEngineInRegistry (RegistryKey rootKey, string subKey)
Static Private Attributes
const string DefaultAssemblyName = "nunit.engine.dll"
const string NunitInstallRegKey = @"SOFTWARE\Nunit.org\Engine"
const string NunitInstallRegKeyWow64 = @"SOFTWARE\Wow6432Node\Nunit.org\Engine"
Detailed Description
TestEngineActivator creates an instance of the test engine and returns an ITestEngine interface.
Member Function Documentation
CreateInstance() [1/2]
static ITestEngine NUnit.Engine.TestEngineActivator.CreateInstance (bool privateCopy = false) inline static
Create an instance of the test engine.
If private copy is false, the search order is the NUnit install directory for the current user, then the install directory for the local machine and finally the current AppDomain's ApplicationBase.
Parameters
privateCopy if set to true loads the engine found in the application base directory, otherwise searches for the test engine with the highest version installed. Defaults to true.
Exceptions
NUnitEngineNotFoundException Thrown when a test engine of the required minimum version is not found
Returns
An NUnit.Engine.ITestEngine
Referenced by NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.InitializeTestEngineResult(), and NUnit.ConsoleRunner.Program.Main().
CreateInstance() [2/2]
static ITestEngine NUnit.Engine.TestEngineActivator.CreateInstance (Version minVersion, bool privateCopy = false) inline static
Create an instance of the test engine with a minimum version.
If private copy is false, the search order is the NUnit install directory for the current user, then the install directory for the local machine and finally the current AppDomain's ApplicationBase.
Parameters
minVersion The minimum version of the engine to return inclusive.
privateCopy if set to true loads the engine found in the application base directory, otherwise searches for the test engine with the highest version installed. Defaults to true.
Exceptions
NUnitEngineNotFoundException Thrown when a test engine of the given minimum version is not found
Returns
An ITestEngine
References NUnit.Engine.TestEngineActivator.FindNewestEngine().
FindNewestEngine()
static Assembly NUnit.Engine.TestEngineActivator.FindNewestEngine (Version minVersion, bool privateCopy) inline static private
References NUnit.Engine.TestEngineActivator.CheckPathForEngine(), NUnit.Engine.TestEngineActivator.DefaultAssemblyName, NUnit.Engine.TestEngineActivator.FindEngineInRegistry(), NUnit.Engine.TestEngineActivator.NunitInstallRegKey, and NUnit.Engine.TestEngineActivator.NunitInstallRegKeyWow64.
Referenced by NUnit.Engine.TestEngineActivator.CreateInstance().
CheckPathForEngine()
static Assembly NUnit.Engine.TestEngineActivator.CheckPathForEngine (string path, Version minVersion, ref Version newestVersionFound, Assembly newestAssemblyFound) inline static private
Referenced by NUnit.Engine.TestEngineActivator.FindNewestEngine().
FindEngineInRegistry()
static string NUnit.Engine.TestEngineActivator.FindEngineInRegistry (RegistryKey rootKey, string subKey) inline static private
Referenced by NUnit.Engine.TestEngineActivator.FindNewestEngine().
Member Data Documentation
DefaultAssemblyName
const string NUnit.Engine.TestEngineActivator.DefaultAssemblyName = "nunit.engine.dll" static private
Referenced by NUnit.Engine.TestEngineActivator.FindNewestEngine().
NunitInstallRegKey
const string NUnit.Engine.TestEngineActivator.NunitInstallRegKey = @"SOFTWARE\Nunit.org\Engine" static private
Referenced by NUnit.Engine.TestEngineActivator.FindNewestEngine().
NunitInstallRegKeyWow64
const string NUnit.Engine.TestEngineActivator.NunitInstallRegKeyWow64 = @"SOFTWARE\Wow6432Node\Nunit.org\Engine" static private
Referenced by NUnit.Engine.TestEngineActivator.FindNewestEngine().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.api/TestEngineActivator.cs