Doc: IGLib EXTENDED: AForge.Neuro.Learning.DeltaRuleLearning Class Reference
AForge.Neuro.Learning.DeltaRuleLearning Class Reference
Delta rule learning algorithm
Public Member Functions
DeltaRuleLearning (ActivationNetwork network)
Initializes a new instance of the DeltaRuleLearning class
double Run (double[] input, double[] output)
Runs learning iteration
double RunEpoch (double[][] input, double[][] output)
Runs learning epoch
DeltaRuleLearning (ActivationNetwork network)
Initializes a new instance of the DeltaRuleLearning class
double Run (double[] input, double[] output)
Runs learning iteration
double RunEpoch (double[][] input, double[][] output)
Runs learning epoch
DeltaRuleLearning (ActivationNetwork network)
Initializes a new instance of the DeltaRuleLearning class.
double Run (double[] input, double[] output)
Runs learning iteration.
double RunEpoch (double[][] input, double[][] output)
Runs learning epoch.
Properties
double LearningRate [get, set]
Learning rate
Private Attributes
ActivationNetwork network
double learningRate = 0.1
Detailed Description
Delta rule learning algorithm
Delta rule learning algorithm.
This learning algorithm is used to train one layer neural network of Activation Neurons with continuous activation function, see SigmoidFunction for example.
This learning algorithm is used to train one layer neural network of Activation Neurons with continuous activation function, see SigmoidFunction for example.
See information about delta rule learning algorithm.
Constructor & Destructor Documentation
DeltaRuleLearning() [1/3]
AForge.Neuro.Learning.DeltaRuleLearning.DeltaRuleLearning (ActivationNetwork network) inline
Initializes a new instance of the DeltaRuleLearning class
Parameters
network Network to teach
References AForge.Neuro.Network.LayersCount, and AForge.Neuro.Learning.DeltaRuleLearning.network.
DeltaRuleLearning() [2/3]
AForge.Neuro.Learning.DeltaRuleLearning.DeltaRuleLearning (ActivationNetwork network) inline
Initializes a new instance of the DeltaRuleLearning class
Parameters
network Network to teach
References AForge.Neuro.Network.LayersCount, and AForge.Neuro.Learning.DeltaRuleLearning.network.
DeltaRuleLearning() [3/3]
AForge.Neuro.Learning.DeltaRuleLearning.DeltaRuleLearning (ActivationNetwork network) inline
Initializes a new instance of the DeltaRuleLearning class.
Parameters
network Network to teach.
Exceptions
ArgumentException Invalid nuaral network. It should have one layer only.
References AForge.Neuro.Network.Layers, and AForge.Neuro.Learning.DeltaRuleLearning.network.
Member Function Documentation
Run() [1/3]
double AForge.Neuro.Learning.DeltaRuleLearning.Run (double[] input, double[] output) inline
Runs learning iteration
Parameters
input input vector
output desired output vector
Returns
Returns squared error divided by 2
Runs one learning iteration and updates neuron's weights.
Implements AForge.Neuro.Learning.ISupervisedLearning.
References AForge.Neuro.Network.Compute(), AForge.Neuro.IActivationFunction.Derivative2(), AForge.Neuro.Neuron.InputsCount, AForge.Neuro.Learning.DeltaRuleLearning.learningRate, AForge.Neuro.Learning.DeltaRuleLearning.network, AForge.Neuro.Layer.NeuronsCount, and AForge.Neuro.ActivationNeuron.Threshold.
Referenced by AForge.Neuro.Learning.DeltaRuleLearning.RunEpoch().
RunEpoch() [1/3]
double AForge.Neuro.Learning.DeltaRuleLearning.RunEpoch (double input[][], double output[][]) inline
Runs learning epoch
Parameters
input array of input vectors
output array of output vectors
Returns
Returns sum of squared errors divided by 2
Runs series of learning iterations - one iteration for each input sample. Updates neuron's weights after each sample presented.
Implements AForge.Neuro.Learning.ISupervisedLearning.
References AForge.Neuro.Learning.DeltaRuleLearning.Run().
Referenced by Classifier.MainForm.SearchSolution(), and Approximation.MainForm.SearchSolution().
Run() [2/3]
double AForge.Neuro.Learning.DeltaRuleLearning.Run (double[] input, double[] output) inline
Runs learning iteration
Parameters
input input vector
output desired output vector
Returns
Returns squared error divided by 2
Runs one learning iteration and updates neuron's weights.
Implements AForge.Neuro.Learning.ISupervisedLearning.
References AForge.Neuro.Network.Compute(), AForge.Neuro.IActivationFunction.Derivative2(), AForge.Neuro.Neuron.InputsCount, AForge.Neuro.Learning.DeltaRuleLearning.learningRate, AForge.Neuro.Learning.DeltaRuleLearning.network, AForge.Neuro.Layer.NeuronsCount, and AForge.Neuro.ActivationNeuron.Threshold.
RunEpoch() [2/3]
double AForge.Neuro.Learning.DeltaRuleLearning.RunEpoch (double input[][], double output[][]) inline
Runs learning epoch
Parameters
input array of input vectors
output array of output vectors
Returns
Returns sum of squared errors divided by 2
Runs series of learning iterations - one iteration for each input sample. Updates neuron's weights after each sample presented.
Implements AForge.Neuro.Learning.ISupervisedLearning.
References AForge.Neuro.Learning.DeltaRuleLearning.Run().
Run() [3/3]
double AForge.Neuro.Learning.DeltaRuleLearning.Run (double[] input, double[] output) inline
Runs learning iteration.
Parameters
input Input vector.
output Desired output vector.
Returns
Returns squared error (difference between current network's output and desired output) divided by 2.
Runs one learning iteration and updates neuron's weights.
Implements AForge.Neuro.Learning.ISupervisedLearning.
References AForge.Neuro.Network.Compute(), AForge.Neuro.IActivationFunction.Derivative2(), AForge.Neuro.Network.Layers, AForge.Neuro.Learning.DeltaRuleLearning.learningRate, AForge.Neuro.Learning.DeltaRuleLearning.network, AForge.Neuro.Layer.Neurons, AForge.Neuro.ActivationNeuron.Threshold, and AForge.Neuro.Neuron.Weights.
RunEpoch() [3/3]
double AForge.Neuro.Learning.DeltaRuleLearning.RunEpoch (double input[][], double output[][]) inline
Runs learning epoch.
Parameters
input Array of input vectors.
output Array of output vectors.
Returns
Returns summary learning error for the epoch. See Run method for details about learning error calculation.
The method runs one learning epoch, by calling Run method for each vector provided in the input array.
Implements AForge.Neuro.Learning.ISupervisedLearning.
References AForge.Neuro.Learning.DeltaRuleLearning.Run().
Member Data Documentation
network
ActivationNetwork AForge.Neuro.Learning.DeltaRuleLearning.network private
Referenced by AForge.Neuro.Learning.DeltaRuleLearning.DeltaRuleLearning(), and AForge.Neuro.Learning.DeltaRuleLearning.Run().
learningRate
double AForge.Neuro.Learning.DeltaRuleLearning.learningRate = 0.1 private
Referenced by AForge.Neuro.Learning.DeltaRuleLearning.Run().
Property Documentation
LearningRate
double AForge.Neuro.Learning.DeltaRuleLearning.LearningRate get set
Learning rate
Learning rate, [0, 1].
The value determines speed of learning in the range of [0, 1]. Default value equals to 0.1.
The value determines speed of learning.
Default value equals to 0.1.
Referenced by Classifier.MainForm.SearchSolution(), and Approximation.MainForm.SearchSolution().
The documentation for this class was generated from the following file:
shelldev/lib/external/neuralnetworks/neuro_src/Sources/Backup/Neuro/Learning/DeltaRuleLearning.cs