Doc: IGLib EXTENDED: AForge.Imaging.ImageStatistics Class Reference
AForge.Imaging.ImageStatistics Class Reference
Gather statistics about image in RGB color space.
Public Member Functions
ImageStatistics (Bitmap image)
Initializes a new instance of the ImageStatistics class.
ImageStatistics (Bitmap image, Bitmap mask)
Initializes a new instance of the ImageStatistics class.
ImageStatistics (Bitmap image, byte[,] mask)
Initializes a new instance of the ImageStatistics class.
ImageStatistics (UnmanagedImage image)
Initializes a new instance of the ImageStatistics class.
ImageStatistics (UnmanagedImage image, UnmanagedImage mask)
Initializes a new instance of the ImageStatistics class.
ImageStatistics (UnmanagedImage image, byte[,] mask)
Initializes a new instance of the ImageStatistics class.
Properties
Histogram Red [get]
Histogram of red channel.
Histogram Green [get]
Histogram of green channel.
Histogram Blue [get]
Histogram of blue channel.
Histogram Gray [get]
Histogram of gray channel.
Histogram RedWithoutBlack [get]
Histogram of red channel excluding black pixels.
Histogram GreenWithoutBlack [get]
Histogram of green channel excluding black pixels.
Histogram BlueWithoutBlack [get]
Histogram of blue channel excluding black pixels
Histogram GrayWithoutBlack [get]
Histogram of gray channel channel excluding black pixels.
int PixelsCount [get]
Total pixels count in the processed image.
int PixelsCountWithoutBlack [get]
Total pixels count in the processed image excluding black pixels.
bool IsGrayscale [get]
Value wich specifies if the processed image was color or grayscale.
Private Member Functions
unsafe void ProcessImage (UnmanagedImage image, byte *mask, int maskLineSize)
void CheckSourceFormat (PixelFormat pixelFormat)
void CheckMaskProperties (PixelFormat maskFormat, Size maskSize, Size sourceImageSize)
Private Attributes
Histogram red
Histogram green
Histogram blue
Histogram gray
Histogram redWithoutBlack
Histogram greenWithoutBlack
Histogram blueWithoutBlack
Histogram grayWithoutBlack
int pixels
int pixelsWithoutBlack
Detailed Description
Gather statistics about image in RGB color space.
The class is used to accumulate statistical values about images, like histogram, mean, standard deviation, etc. for each color channel in RGB color space.
The class accepts 8 bpp grayscale and 24/32 bpp color images for processing.
Sample usage:
// gather statistics
ImageStatistics stat = new ImageStatistics(image);
// get red channel's histogram
Histogram red = stat.Red;
// check mean value of red channel
if (red.Mean > 128)
{
    // do further processing
}
See also
AForge.Math.Histogram
Constructor & Destructor Documentation
ImageStatistics() [1/6]
AForge.Imaging.ImageStatistics.ImageStatistics (Bitmap image) inline
Initializes a new instance of the ImageStatistics class.
Parameters
image Image to gather statistics about.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported.
References AForge.Imaging.ImageStatistics.CheckSourceFormat(), AForge.Imaging.ImageStatistics.ProcessImage(), and AForge.Math.Geometry.Rectangle.
ImageStatistics() [2/6]
AForge.Imaging.ImageStatistics.ImageStatistics (Bitmap image, Bitmap mask) inline
Initializes a new instance of the ImageStatistics class.
Parameters
image Image to gather statistics about.
mask Mask image which specifies areas to collect statistics for.
The mask image must be a grayscale/binary (8bpp) image of the same size as the specified source image, where black pixels (value 0) correspond to areas which should be excluded from processing. So statistics is calculated only for pixels, which are none black in the mask image.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported.
ArgumentException Mask image must be 8 bpp grayscale image.
ArgumentException Mask must have the same size as the source image to get statistics for.
References AForge.Imaging.ImageStatistics.CheckMaskProperties(), AForge.Imaging.ImageStatistics.CheckSourceFormat(), AForge.Imaging.ImageStatistics.ProcessImage(), AForge.Math.Geometry.Rectangle, AForge.Imaging.Size, and AForge.Imaging.UnmanagedImage.Stride.
ImageStatistics() [3/6]
AForge.Imaging.ImageStatistics.ImageStatistics (Bitmap image, byte mask[,]) inline
Initializes a new instance of the ImageStatistics class.
Parameters
image Image to gather statistics about.
mask Mask array which specifies areas to collect statistics for.
The mask array must be of the same size as the specified source image, where 0 values correspond to areas which should be excluded from processing. So statistics is calculated only for pixels, which have none zero corresponding value in the mask.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported.
ArgumentException Mask must have the same size as the source image to get statistics for.
References AForge.Imaging.ImageStatistics.CheckMaskProperties(), AForge.Imaging.ImageStatistics.CheckSourceFormat(), AForge.Imaging.ImageStatistics.ProcessImage(), AForge.Math.Geometry.Rectangle, and AForge.Imaging.Size.
ImageStatistics() [4/6]
AForge.Imaging.ImageStatistics.ImageStatistics (UnmanagedImage image) inline
Initializes a new instance of the ImageStatistics class.
Parameters
image Unmanaged image to gather statistics about.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported.
References AForge.Imaging.ImageStatistics.CheckSourceFormat(), AForge.Imaging.UnmanagedImage.PixelFormat, and AForge.Imaging.ImageStatistics.ProcessImage().
ImageStatistics() [5/6]
AForge.Imaging.ImageStatistics.ImageStatistics (UnmanagedImage image, UnmanagedImage mask) inline
Initializes a new instance of the ImageStatistics class.
Parameters
image Image to gather statistics about.
mask Mask image which specifies areas to collect statistics for.
The mask image must be a grayscale/binary (8bpp) image of the same size as the specified source image, where black pixels (value 0) correspond to areas which should be excluded from processing. So statistics is calculated only for pixels, which are none black in the mask image.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported.
ArgumentException Mask image must be 8 bpp grayscale image.
ArgumentException Mask must have the same size as the source image to get statistics for.
References AForge.Imaging.ImageStatistics.CheckMaskProperties(), AForge.Imaging.ImageStatistics.CheckSourceFormat(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.ImageStatistics.ProcessImage(), AForge.Imaging.Size, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
ImageStatistics() [6/6]
AForge.Imaging.ImageStatistics.ImageStatistics (UnmanagedImage image, byte mask[,]) inline
Initializes a new instance of the ImageStatistics class.
Parameters
image Image to gather statistics about.
mask Mask array which specifies areas to collect statistics for.
The mask array must be of the same size as the specified source image, where 0 values correspond to areas which should be excluded from processing. So statistics is calculated only for pixels, which have none zero corresponding value in the mask.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported.
ArgumentException Mask must have the same size as the source image to get statistics for.
References AForge.Imaging.ImageStatistics.CheckMaskProperties(), AForge.Imaging.ImageStatistics.CheckSourceFormat(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.ImageStatistics.ProcessImage(), AForge.Imaging.Size, and AForge.Imaging.UnmanagedImage.Width.
Member Function Documentation
ProcessImage()
unsafe void AForge.Imaging.ImageStatistics.ProcessImage (UnmanagedImage image, byte * mask, int maskLineSize) inline private
References AForge.Imaging.RGB.B, AForge.Imaging.ImageStatistics.blue, AForge.Imaging.ImageStatistics.blueWithoutBlack, AForge.Imaging.RGB.G, AForge.Imaging.ImageStatistics.gray, AForge.Imaging.ImageStatistics.grayWithoutBlack, AForge.Imaging.ImageStatistics.green, AForge.Imaging.ImageStatistics.greenWithoutBlack, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.ImageStatistics.pixels, AForge.Imaging.ImageStatistics.pixelsWithoutBlack, AForge.Imaging.RGB.R, AForge.Imaging.ImageStatistics.red, AForge.Imaging.ImageStatistics.redWithoutBlack, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
Referenced by AForge.Imaging.ImageStatistics.ImageStatistics().
CheckSourceFormat()
void AForge.Imaging.ImageStatistics.CheckSourceFormat (PixelFormat pixelFormat) inline private
Referenced by AForge.Imaging.ImageStatistics.ImageStatistics().
CheckMaskProperties()
void AForge.Imaging.ImageStatistics.CheckMaskProperties (PixelFormat maskFormat, Size maskSize, Size sourceImageSize) inline private
Referenced by AForge.Imaging.ImageStatistics.ImageStatistics().
Member Data Documentation
red
Histogram AForge.Imaging.ImageStatistics.red private
Referenced by AForge.Imaging.ImageStatistics.ProcessImage().
green
Histogram AForge.Imaging.ImageStatistics.green private
Referenced by AForge.Imaging.ImageStatistics.ProcessImage().
blue
Histogram AForge.Imaging.ImageStatistics.blue private
Referenced by AForge.Imaging.ImageStatistics.ProcessImage().
gray
Histogram AForge.Imaging.ImageStatistics.gray private
Referenced by AForge.Imaging.ImageStatistics.ProcessImage().
redWithoutBlack
Histogram AForge.Imaging.ImageStatistics.redWithoutBlack private
Referenced by AForge.Imaging.ImageStatistics.ProcessImage().
greenWithoutBlack
Histogram AForge.Imaging.ImageStatistics.greenWithoutBlack private
Referenced by AForge.Imaging.ImageStatistics.ProcessImage().
blueWithoutBlack
Histogram AForge.Imaging.ImageStatistics.blueWithoutBlack private
Referenced by AForge.Imaging.ImageStatistics.ProcessImage().
grayWithoutBlack
Histogram AForge.Imaging.ImageStatistics.grayWithoutBlack private
Referenced by AForge.Imaging.ImageStatistics.ProcessImage().
pixels
int AForge.Imaging.ImageStatistics.pixels private
Referenced by AForge.Imaging.ImageStatistics.ProcessImage().
pixelsWithoutBlack
int AForge.Imaging.ImageStatistics.pixelsWithoutBlack private
Referenced by AForge.Imaging.ImageStatistics.ProcessImage().
Property Documentation
Red
Histogram AForge.Imaging.ImageStatistics.Red get
Histogram of red channel.
<note>The property is valid only for color images (see IsGrayscale property).</note>
Referenced by AForge.Imaging.Filters.FlatFieldCorrection.ProcessFilter().
Green
Histogram AForge.Imaging.ImageStatistics.Green get
Histogram of green channel.
<note>The property is valid only for color images (see IsGrayscale property).</note>
Referenced by AForge.Imaging.Filters.FlatFieldCorrection.ProcessFilter().
Blue
Histogram AForge.Imaging.ImageStatistics.Blue get
Histogram of blue channel.
<note>The property is valid only for color images (see IsGrayscale property).</note>
Referenced by AForge.Imaging.Filters.FlatFieldCorrection.ProcessFilter().
Gray
Histogram AForge.Imaging.ImageStatistics.Gray get
Histogram of gray channel.
<note>The property is valid only for grayscale images (see IsGrayscale property).</note>
Referenced by AForge.Imaging.Filters.FlatFieldCorrection.ProcessFilter().
RedWithoutBlack
Histogram AForge.Imaging.ImageStatistics.RedWithoutBlack get
Histogram of red channel excluding black pixels.
The property keeps statistics about red channel, which excludes all black pixels, what affects mean, standard deviation, etc.
<note>The property is valid only for color images (see IsGrayscale property).</note>
GreenWithoutBlack
Histogram AForge.Imaging.ImageStatistics.GreenWithoutBlack get
Histogram of green channel excluding black pixels.
The property keeps statistics about green channel, which excludes all black pixels, what affects mean, standard deviation, etc.
<note>The property is valid only for color images (see IsGrayscale property).</note>
BlueWithoutBlack
Histogram AForge.Imaging.ImageStatistics.BlueWithoutBlack get
Histogram of blue channel excluding black pixels
The property keeps statistics about blue channel, which excludes all black pixels, what affects mean, standard deviation, etc.
<note>The property is valid only for color images (see IsGrayscale property).</note>
GrayWithoutBlack
Histogram AForge.Imaging.ImageStatistics.GrayWithoutBlack get
Histogram of gray channel channel excluding black pixels.
The property keeps statistics about gray channel, which excludes all black pixels, what affects mean, standard deviation, etc.
<note>The property is valid only for grayscale images (see IsGrayscale property).</note>
PixelsCount
int AForge.Imaging.ImageStatistics.PixelsCount get
Total pixels count in the processed image.
PixelsCountWithoutBlack
int AForge.Imaging.ImageStatistics.PixelsCountWithoutBlack get
Total pixels count in the processed image excluding black pixels.
IsGrayscale
bool AForge.Imaging.ImageStatistics.IsGrayscale get
Value wich specifies if the processed image was color or grayscale.
If the value is set to true then Gray property should be used to get statistics information about image. Otherwise Red, Green and Blue properties should be used for color images.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/ImageStatistics.cs