Doc: IGLib EXTENDED: TstPerson Class Reference
TstPerson Class Reference
Public Member Functions
TstPerson ()
void NUnit_Example_Init ()
void NUnit_Example_IsNameJohnSmith ()
void NUnit_Example_IsAgeEqual ()
void NUnit_Example_IsNameJohnAbraham ()
void NUnit_Example_BalanceBeforeCarPurchase ()
void NUnit_Example_BalanceAfterCarPurchase ()
Private Attributes
Person pTest
Constructor & Destructor Documentation
TstPerson()
TstPerson.TstPerson () inline
Member Function Documentation
NUnit_Example_Init()
void TstPerson.NUnit_Example_Init () inline
References pTest.
NUnit_Example_IsNameJohnSmith()
void TstPerson.NUnit_Example_IsNameJohnSmith () inline
References TestExampleNunit.Person.FullName, NUnit.Framework.Assert.IsFalse(), and pTest.
NUnit_Example_IsAgeEqual()
void TstPerson.NUnit_Example_IsAgeEqual () inline
References TestExampleNunit.Person.Age, NUnit.Framework.Assert.AreEqual(), and pTest.
NUnit_Example_IsNameJohnAbraham()
void TstPerson.NUnit_Example_IsNameJohnAbraham () inline
References NUnit.Framework.Assert.AreEqual(), TestExampleNunit.Person.FullName, and pTest.
NUnit_Example_BalanceBeforeCarPurchase()
void TstPerson.NUnit_Example_BalanceBeforeCarPurchase () inline
References NUnit.Framework.Assert.AreEqual(), TestExampleNunit.Person.CashBalance, and pTest.
NUnit_Example_BalanceAfterCarPurchase()
void TstPerson.NUnit_Example_BalanceAfterCarPurchase () inline
References NUnit.Framework.Assert.AreEqual(), TestExampleNunit.Person.BuyCar(), TestExampleNunit.Person.CashBalance, and pTest.
Member Data Documentation
pTest
Person TstPerson.pTest private
Referenced by NUnit_Example_BalanceAfterCarPurchase(), NUnit_Example_BalanceBeforeCarPurchase(), NUnit_Example_Init(), NUnit_Example_IsAgeEqual(), NUnit_Example_IsNameJohnAbraham(), and NUnit_Example_IsNameJohnSmith().
The documentation for this class was generated from the following file:
unittests/TestExampleNunitNew/TstPerson.cs