Doc: IGLib EXTENDED: IG.Num.SimJMatProFileManagerBase Class Reference
IG.Num.SimJMatProFileManagerBase Class Reference
File manager for interfacing the JMatPro software.
Classes
class JMatResultInfo
Class for checking and obtaining information about JMatPro results.
class MaterialDirectoryInfoBase
Contains information about the state of specific calculation related to material directory.
class SimulationInfoBase
Contains information about the particular bundle of simulations to be performed.
Public Types
enum CalculationStatus {
CalculationStatus.None = 0, CalculationStatus.Successful = 1 << 0, CalculationStatus.Incomplete = 1 << 1, CalculationStatus.Corrupted = 1 << 2,
CalculationStatus.Timedout = 1 << 3, CalculationStatus.Failed = 1 << 4, CalculationStatus.Unsuccessful = Corrupted | Timedout | Failed | Incomplete
}
Public Member Functions
SimJMatProFileManagerBase (string workingDirectoryPath)
Construct JMatPro interface's file manager, with specified working directory.
SimJMatProFileManagerBase (string workingDirectoryPath, string settingsFilePath)
Construct JMatPro interface's file manager, with specified working directory and path to the file where settings are stored.
SimJMatProFileManagerBase (string workingDirectoryPath, SimJmatProSettingsDto settings)
Construct JMatPro interface's file manager, with specified working directory and settings object.
bool LockFileMutexCheckAbandoned ()
Check whether the file system locking mutex (property LockFileMutex) has been abandoned, and returns true if it has been (otherwise, false is returned).
void Error (string errorMsg)
Temporary utility for reporting errors in the development stage.
void ErrorNotImplemented (string errorMsg)
Temporary utility for reporting errors in the development stage.
virtual void GetRandomMaterialParameters (ref IVector result)
Generates a random vector of material parameters whose elements (components) lie within the lower and upper bounds on parameters, and stores it to the specified vector.
virtual void GetRandomMaterialParameters (IRandomGenerator rand, ref IVector result)
Generates a random vector of material parameters whose elements (components) lie within the lower and upper bounds on parameters, and stores it to the specified vector.
virtual void CreateJointParameters (IVector materialParameters, IVector processParameters, ref IVector jointParameters)
Combines the specified vectors of materaial and process parameters into a joint vector of process parameters and stored it into the specified variable.
virtual void ExtractMaterialParameters (IVector jointParameters, ref IVector materialParameters)
Extracts the vector of material parameters from the specified joint vector of problem parameters, and stores it to the specified variable.
virtual void ExtractProcessParameters (IVector jointParameters, ref IVector processParameters)
Extracts the vector of process parameters from the specified joint vector of problem parameters, and stores it to the specified variable.
virtual void ExtractMaterialAndProcessParameters (IVector jointParameters, ref IVector materialParameters, ref IVector processParameters)
Extracts the vectors of material and process parameters from the specified joint vector of problem parameters, and stores them to the specified variable.
virtual string GetMaterialDirectoryName (IVector parameters)
Returns name of the material directory for the specified material parameters.
virtual bool CreateMaterialDataDirectory ()
Creates the data directory for the current material (specified by material parameters).
bool MoveMaterialDirectory (string materialDirectoryPath, string storageDirectoryPath)
Moves the specified material directory to the specified storage directory.
int MoveMaterialDirectoryToStorageMaterialCalculated ()
Moves to the appropeiate storage directory those material directories for which material properties have been successfully calculated.
int MoveMaterialDirectoryToStorageBusyFlagSet ()
Moves to the appropeiate storage directory those material directories for which busy flag remained set.
int MoveMaterialDirectoryToStorageTimedout ()
Moves to the appropeiate storage directory those material directories for which material properties calculation has timed out.
int MoveMaterialDirectoryToStorageCalculationFailed ()
Moves to the appropeiate storage directory those material directories for which material properties calculation failed (regardless of reason).
int MoveMaterialDirectoryToStorageDataCorrupted ()
Moves to the appropeiate storage directory those material directories for which material data is corrupted (e.g. material parameters are not written properly).
int MoveMaterialDirectoriesToStorageAll (bool moveBusy, bool moveMaterialCalculated)
Moves all material directries to the appropriate storage directories, dependent on the state of calculation in any particular directory.
bool IsMaterialCalculationBusy ()
Flag indicating whether material calculation for the current material parameters is in progress.
virtual void ClearMaterialCalculationBusy ()
Clears the flag indicating that material calculation is in progress.
virtual bool SetMaterialCalculationBusy ()
Sets the flag indicating that material calculation directory is used, and returns true if the flag was successfully set.
bool IsMaterialCalculationFinished ()
Flag indicating whether material calculation for the current material parameters is finished.
virtual void ClearMaterialCalculationFinished ()
Clears the flag indicating that material calculation is finished.
virtual void SetMaterialCalculationFinished ()
Sets the flag indicating that material calculation is finished.
bool IsMaterialCalculationTimedout ()
Flag indicating whether material calculation for the current material parameters has timed out.
virtual void ClearMaterialCalculationTimedout ()
Clears the flag indicating that material calculation has timed out.
virtual void SetMaterialCalculationTimedout (double timeOutSeconds)
Sets the flag indicating that material calculation has timed out.
bool IsMaterialResultsWrong ()
Flag indicating whether material results are incorrect.
virtual void ClearMaterialResultsWrong ()
Clears the flag indicating that material result file is incorrect.
virtual void SetMaterialResultsWrong (string errorsString)
Sets the flag indicating that material result file is incorrect.
virtual void JMatLaunch ()
Safely launches the JMatpPro software.
virtual void JMatOpen ()
Just starts the JMatPro software.
virtual void JMatRepair ()
Repairs JMatPro, e.g. if it has been stopped abruptly or if another version is already running somewhere such that we could not start it.
virtual void JMatClose ()
Closes JMatPro normally, by simulated user interaction.
virtual void JMatStartCalculation ()
Starts JMatPro calculation.
virtual void JMatSaveResults ()
Saves results of JMatPro calculation.
virtual void JMatChangeTemperatureUnit ()
Changes (toggles once) temperature unit in an open window of JMatPro (software must be running and its main window on the top of window stack) by running the appropriate script.
virtual void JMatChangeFractionUnit ()
Changes (toggles once) fraction unit in an open window of JMatPro (software must be running and its main window on the top of window stack) by running the appropriate script.
virtual bool JMatWaitCalculation ()
Waits until JMatPro calculation finishes.
virtual bool JMatWaitResultsSaved ()
Waits until JMatPro results are saved.
void PrepareDataDefinitionsFromSuperset ()
Prepares data definitions from the superset data definition file.
void PrapareDefaultMaterialParameters ()
Calculates default material parameters as the middle point of allowed intervals, and saves the parameters.
void PrepareSettingsTemplate ()
Saves the current settings to a file used as template for settings file for JMatPro interface' file manager.
string GetMaterialDirectoryPath (string specifiedMaterialDirectoryPath)
Returns a valid (existent) material data directory path that is obtaines form the specified path, or throws exception if such a directory could not be obtained.
virtual string GetMaterialDirectoryPath (string specifiedMaterialDirectoryPath, bool throwExceptions)
Returns a valid (existent) material data directory path that is obtaines form the specified path, or null if such a directory could not be obtained (or, if throwExceptions is true, exception is thrown in this case).
virtual void ClearMaterialResultsWrongFlag (string materialDirectoryPath)
Clears the flag indicating that material result file is incorrect.
virtual void SetMaterialResultsWrongFlag (string materialDirectoryPath, string dataErrorDescriptions)
Sets the flag indicating that material result file is incorrect.
bool ClearBusyFlag (string materialDirectoryPath)
Clears the busy flag from the specified material directory, and returns a flag indicating whether clearing of a flag has actually occurred.
virtual void ClearMaterialCalculationFinishedFlag (string materialDirectoryPath)
Clears the flag indicating that material calculation is successfully finished, from the specified directory.
bool GetMaterialParameters (string materialDirectoryPath, ref IVector parameters)
Gets (reads) material parameters from the specified material data directory.
bool IsMaterialDirectoryCorrupted (string materialDirectoryPath)
Returns a flag indicated whether the specified material data directory is corrupted in the sense that some material data in it is corrupted (i.e. the vector of material parameters is not properly written).
void GetMaterialDirectories (ref List< DirectoryInfo > directories)
Obtains a list of paths of all material directories, and stores them on the specified list.
void GetMaterialDirectoriesWhereCalculationFailed (ref List< DirectoryInfo > directories)
Obtains a list of paths of all material directories where material properties calculation has failed. These are characterized as material directories where the busy flag is not set but material data is also not available (which means that material results file does not exist or is too small or the message file for the material calculation finished message does not exist).
void GetMaterialDirectoriesWhereBusySet (ref List< DirectoryInfo > directories)
Obtains a list of paths of all material directories where the busy flag is set (which may be a consequence of some failure).
void GetMaterialDirectoriesWhereTimedout (ref List< DirectoryInfo > directories)
Obtains a list of all material directories where material calculation has timed out.
void GetMaterialDirectoriesWhereMaterialCalculated (ref List< DirectoryInfo > directories)
Obtains a list of paths of all material directories where material properties were successfully calculated. These are characterized as material directories where the busy flag is not set but material data is also available (which means that material results file exists and is large enough and the message file for the material calculation finished message exists).
void GetMaterialDirectoriesWhereMaterialDataCorrupted (ref List< DirectoryInfo > directories)
Obtains a list of paths of all material directories where material data is corrupted. The method IsMaterialDirectoryCorrupted is used to test material directories for corruption.
int WriteMaterialCalculationStatistics (bool printIndividualDirectories, bool includeCorrupted)
Prints statistics of material properties calculation.
int WriteMaterialDirectoriesWhereMaterialCalculated ()
Prints (to console and log file) information about material directories where material properties were successfully calculated.
bool ReleaseAbandonedMutex ()
Releases the mutex in the case it has been abandoned, and returns a flag indicating whether the mutex has actually been abandoned. Has no effect if mutex is not abandoned.
void ClearBusyFlags ()
Clears the busy flag in all directories where it is still set (possibly because some procedure has hanged).
void RetryCalculateMaterialProperties (string materialDirectoryPath)
Retries calculation of
void RetryCalculateMaterialProperties (string materialDirectoryPath, int whichCalculation, int numCalculations)
Retries calculation of
int RetryCalculateMaterialProperties ()
Retries calculation of material properties in the directories where calculation obviously failed.
void KillJMatPro ()
Kills the JMatPro process.
bool IsJMatProRunning ()
Returns a flag indicating whether the JMatPro application is currently running.
bool IsMaterialDataDirectoryPrepared ()
Whether material data is prepared.
void CalculateMaterialPropertiesRandomSet (int numParameterSets)
Calculates material properties by JMatPro for a set of random parameters.
void CalculateMaterialProperties (string parametersPath)
Calculates material properties at parameters that are read from a file.
void CalculateMaterialPropertiesDef (string parametersPath)
Calculates material properties at parameters that are read from a data definition file as default values.
void CalculateMaterialProperties (IVector parameters)
Calculates the material properties at the specified vector of material parameters, and stores results to the appropriate directory.
void CalculateMaterialProperties ()
Calculates the material properties at the current vector of material parameters, and stores results to the appropriate directory.
void MaterialCalculationsStatisticsPrint (string introductionString)
Prints calculation statistics after another material calculation is finished.
void MaterialCalculationStatisticsReset (int numIntendedCalculations)
Resets material calculation statistics counters.
void MaterialCalculationStatisticsStart ()
Updates material calculaiton statistics counters at the beginning of a new material calculation.
void MaterialCalculationStatisticsStop (CalculationStatus status)
Updates material calculation statistics counters after completion of a single calculation.
virtual void GetMaterialParametersDefault (ref IG.Num.IVector parameters)
Returns vector containing default values for material parameters.
virtual List< JMatProElemetData > CalculateJMatInput (IVector materialParameters)
Calculates and returns input data for JMatPro from the vector of material parameters.
virtual void PrepareJMatInput (IVector materialParameters, string filePath)
Prepares input file for JMatPro (composition of steel) according to the specified material parameters.
override string ToString ()
virtual void CopyToSettingsPlain< FmType > (SimJMatProSettingsDto< FmType > settings)
Copies settings from the current JMatPro file manager to the specified settings object.
virtual void CopyFromSettingsPlain< FmType > (SimJMatProSettingsDto< FmType > settings)
Copies settings fom the specified settings object to the current JMatPro file manager.
void SaveSettings (string filePath)
Saves (serializes) the settings of the current JMatPro interface' file manager to the specified JSON file.
void SaveSettings (string filePath, bool append)
Saves (serializes) the settings of the current JMatPro interface' file manager to the specified JSON file.
void LoadSettings (string filePath)
Restores (deserializes) the current JMatPro interface' file manager settings from the specified file in JSON format.
JMatProElemetData GetElementData (string elementSymbol)
Returns data about the specified chemical element.
double GetElementAtomicMass (string elementSymbol)
Returns atomic mass of the chemical elemen with the specified symbol.
string GetElementName (string elementSymbol)
Returns name of the chemical elemen with the specified symbol.
int GetNumCompositionElements ()
Returns number of elements that are included in JMatPro input files for steel.
string GetCompositionElementSymbol (int which)
Returns the chemical symbol of the specified element.
string GetSimulatorBaseDirectoryName (int whichSimulator)
Calculates and returns name of the base simulator directory with the specified index (zero-based).
string GetSimulatorBaseDirectoryPath (int whichSimulator)
Calculates and returns path of the root simulator directory with the specified index (zero-based).
virtual string GetSimulatorCastingRobertDirectoryPath (int whichsimulator)
Calculates and returns path of the Robert Vertnik's casting simulator's main directory with the specified index (zero-based).
virtual void InitSimCastingRobert (string rootDirectory, string projectName, string simulationName)
Initializes the data for casting simulation interface.
void PrepareSimulatorData (SimCastingRobertFileManager simulator, string materialDirectoryPath)
Prepares input data for simulator, in particular the material properties, which are obtained from the material data directory whose path is specified.
virtual void CalculateSimulatedResponse (SimCastingRobertFileManager simulator, string materialDirectory, IVector inputProcessParameters, ref IVector inputJointParameters, ref IVector outputValues)
Calculates simulator's response at the specified process parameters, for the specified material directory (that specifies material parameters and properties), and stores joint input parameters and output values.
virtual int CalculateSimulatedResponse (SimCastingRobertFileManager simulator, string materialDirectory, string datasetName, params IVector[] inputProcessParameters)
Calculates response by the specified simulator, for the specified process parameter vectors and the specified material (specified by the material directory approximate path), and stores calculated data in the appropriate file in the material data directory (defined by the datasetName).
virtual int CalculateSimulatedResponseDefault (SimCastingRobertFileManager simulator, string materialDirectory, string datasetName)
Calculates response by the specified simulator, for the specified process parameter vectors and the specified material (specified by the material directory approximate path), and stores calculated data in the appropriate file in the material data directory (defined by the datasetName).
Static Public Member Functions
static void SaveSettings (SimJmatProSettingsDto settings, string filePath)
Saves (serializes) the specified settings of the JMatPro interface' file manager to the specified JSON file.
static void SaveSettings (SimJmatProSettingsDto settings, string filePath, bool append)
Saves (serializes) the specified settings for JMatPro interface' file manager to the specified JSON file.
static void LoadSettings (string filePath, ref SimJmatProSettingsDto settings)
Restores (deserializes) JMatPro interface' settings from the specified file in JSON format.
static JMatProElemetData FindElementData (List< JMatProElemetData > elements, string elementSymbol)
Finds data for the specified element on the specified list of element data, and returns the data (or null if the data is not be found).
Public Attributes
string _userInteractionCommand = SimJMatProConst.UserInteractionCommand
string _userInteractionRecordDir = SimJMatProConst.DefaultUserInteractionRecordDir
string _userInteractionRecordExtension = SimJMatProConst.UserInteractionRecordExtension
string _userInteractionRecordNameStartJMat = SimJMatProConst.UserInteractionRecordNameStartJMat
string _userInteractionRecordPathStartJMat
string _userInteractionRecordNameCloseJMat = SimJMatProConst.UserInteractionRecordNameCloseJMat
string _userInteractionRecordPathCloseJMat
string _userInteractionRecordNameRepairJMat = SimJMatProConst.UserInteractionRecordNameRepairJMat
string _userInteractionRecordPathRepairJMat
string _userInteractionRecordNameStartCalculation = SimJMatProConst.UserInteractionRecordNameStartCalculation
string _userInteractionRecordPathStartCalculation
double _jMatTimeoutWaitCalculationSeconds = SimJMatProConst.JMatTimeoutWaitCalculationSeconds
double _jMatTimeoutWaitResultsSavedSeconds = SimJMatProConst.JMatTimeoutWaitResultsSavedSeconds
Protected Member Functions
bool IsMaterialDirectory (DirectoryInfo dir)
Returns a flag indicating whether teh specified directory is considered a material directory or not. This method is usually used to extract all material directoried from the root data directory (which may for some reason contain other directories, too).
bool IsMaterialCalculated (string materialDirectoryPath)
For the specified material data directory, returns a flag that indicates whether material properties have been calculated for the corresponding material or not. This is obtained by checking the corresponding message file as well as existence and size of the material results file.
bool IsTimedoutFlagSet (string materialDirectoryPath)
For the specified material data directory, returns a flag that indicates whether material calculation has not finished because of timeout. This is obtained by checking the corresponding message file.
bool IsMaterialResultsWrongFlagSet (string materialDirectoryPath)
For the specified material data directory, returns a flag that indicates whether material result file contents are incorrect. This is obtained by checking the corresponding message file.
bool IsBusyFlagSet (string materialDirectoryPath)
For the specified material data directory, returns a flag that indicates whether the busy flag is set.
string ReplacePathSeparator (string path)
Returns a string obtained by replacing the '\' path separator by the more standard '/' in the specified path string, or null if the string is null.
void AddElements< ElType > (List< ElType > l, params ElType[] elements)
Adds the specified elements to the specified list.
void InitElements ()
Creates a list of chemical element data.
virtual SimCastingRobertFileManager GetSimCastingRobert (int whichSimulator)
Returns a newly created Robert Vertnik's casting simulator with the specified index (zero-based)
virtual int CalculateSimulatedResponse (SimCastingRobertFileManager simulator, string materialDirectory, ref SampledDataSet sampledData, params IVector[] inputProcessParameters)
Calculates response by the specified simulator, for the specified process parameter vectors and the specified material (specified by the material directory approximate path), and stores calculated data in the specified sampled data set (object of type SampledDataSet).
Protected Attributes
string _lockFileMutexName = SimJMatProConst.LockFileMutexName
Mutex _lockFileMutex
string _nameJMatProBase
string _jmatInstallationPath
string _executableFileName
string _executableFilePath
string _jmatDataPath
string _jmatCompositionFilename = SimJMatProConst.JmatCompositionRelativepath
string _jmatCompositionFilePath
string _jmatResultsFilename = SimJMatProConst.JMatResultsRelativePath
string _jmatResultsFilePath
string _jmatCompletionDetectionFilename = SimJMatProConst.JMatCompletionDetectionRelativePath
string _jmatCompletionDetectionFilePath
double _jmatCompletionDetectionSleepTimeSeconds = SimJMatProConst.JMatCompletionDetectionSleepTimeSeconds
int _jmatCompletionDetectionSize = SimJMatProConst.JmatCompletionDetectionSize
double _jmatBeforeSaveSleepTimeSeconds = SimJMatProConst.JMatBeforeSaveSleepTimeSeconds
bool _checkWorkingDirectoryExistence = true
string _workingDirectory = null
string _dataDefinitionSupersetFilename = SimJMatProConst.DataDefinitionSupersetFilename
string _dataDefinitionSupersetFilePath
string _dataDefinitionJMatFilename = SimJMatProConst.DataDefinitionJMatFilename
string _dataDefinitionJMatFilePath
string _dataDefinitionProcessFilename = SimJMatProConst.DataDefinitionProcessFilename
string _dataDefinitionProcessFilePath
string _dataDefinitionJointFilename = SimJMatProConst.DataDefinitionJointFilename
string _dataDefinitionJointFilePath
string _dataDefinitionJMatFilenameNoNitrogen = SimJMatProConst.DataDefinitionJMatFilenameNoNitrogen
string _dataDefinitionJMatFilePathNoNitrogen
string _dataDefinitionJointFilenameNoNitrogen = SimJMatProConst.DataDefinitionJointFilenameNoNitrogen
string _dataDefinitionJointFilePathNoNitrogen
InputOutputDataDefiniton _dataDefinitionSuperset
InputOutputDataDefiniton _dataDefinitionJMat
IBoundingBox _materialParameterBounds
InputOutputDataDefiniton _dataDefinitionProcess
InputOutputDataDefiniton _dataDefinitionJoint
string _workingmaterialParametersPath
string _materialParametersDefFilename = SimJMatProConst.MaterialParametersDefFilename
string _workingmaterialParametersDefPath
string _rootDataDirectoryname = SimJMatProConst.RootDataDirectoryName
string _rootDataDirectoryPath
string _logFileName = SimJMatProConst.LogfileName
string _logFilePath
TextWriter _logFileWriter
string _materialDirectoryName
string _materialDataDirectoryPath
string _materialParametersFilename = SimJMatProConst.MaterialParametersFilename
string _materialParametersPath
string _materialCompositionFilename = SimJMatProConst.JMatCompositionFilename
string _materialCompositionPath
string _materialResultsFilename = SimJMatProConst.JMatResultsFilename
string _materialResultsPath
int _jMatResultsMinimalSize = SimJMatProConst.JMatResultsMinimalSize
int _jMatResultsGoodSize = SimJMatProConst.JMatResultsGoodSize
string _msgMaterialCalculationBusyFilename = SimJMatProConst.MsgMaterialCalculationBusyFilename
string _msgMaterialCalculationBusyPath
string _msgMaterialCalculationFinishedFilename = SimJMatProConst.MsgMaterialCalculationFinishedFilename
string _msgMaterialCalculationFinishedPath
string _msgMaterialCalculationTimedoutFilename = SimJMatProConst.MsgMaterialCalculationTimedoutFilename
string _msgMaterialCalculationTimedoutPath
string _msgMaterialResultsWrongFilename = SimJMatProConst.MsgMaterialResultsWrongFilename
string _msgMaterialResultsWrongPath
string _storageMaterialCalculatedDirectoryname = SimJMatProConst.StorageMaterialCalculatedDirectoryname
string _storageMaterialCalculatedDirectoryPath
string _storageBusyFlagSetDirectoryname = SimJMatProConst.StorageBusyFlagSetDirectoryname
string _storageBusyFlagSetDirectoryPath
string _storageTimedoutDirectoryname = SimJMatProConst.StorageTimedoutDirectoryname
string _storageTimedoutDirectoryPath
string _storageMaterialCalculationFailedDirectoryname = SimJMatProConst.StorageMaterialCalculationFailedDirectoryname
string _storageMaterialCalculationFailedDirectoryPath
string _storageMaterialMaterialDataCorruptedDirectoryname = SimJMatProConst.StorageMaterialDataCorruptedDirectoryname
string _storageMaterialMaterialDataCorruptedDirectoryPath
double _waitSleepTimeSeconds = SimJMatProConst.WaitSleepTime
string _userInteractionRecordNameSaveResults = SimJMatProConst.UserInteractionRecordNameSaveResults
string _userInteractionRecordPathSaveResults
string _userInteractionRecordNameChangeTemperatureUnit = SimJMatProConst.UserInteractionRecordNameChangeTemperatureUnit
string _userInteractionRecordPathChangeTemperatureUnit
string _userInteractionRecordNameChangeFractionUnit = SimJMatProConst.UserInteractionRecordNameChangeFractionUnit
string _userInteractionRecordPathChangeFractionUnit
int _jMatResultsSavedDetectionSize = SimJMatProConst.JMatResultsSavedDetectionSize
double _jMatBeforeResultsSavedSleepTimeSeconds = SimJMatProConst.JMatBeforeResultsSavedSleepTimeSeconds
string _processNameSubstringJava = SimJMatProConst.ProcessNameSubstringJava
string _processNameSubstringJMatMain = SimJMatProConst.ProcessNameSubstringJMatMain
string _processNameSubstringJMatSolver = SimJMatProConst.ProcessNameSubstringJMatSolver
CalculationStatus _materialCalculationStatus = CalculationStatus.None
StopWatch1 _materialCalculationTimer
double _longestMaterialCalculationTime
double _materialCalculationTime
int _numMaterialCalculationsIndended
int _numMaterialCalculationsPerformed
int _numMaterialCalculationsSuccessful
int _numMaterialCalculationsTimedout
int _numMaterialCalculationsUnsuccessful
int _numConsecutiveMaterialcalculationUnsuccessful
int _numConsecutiveMaterialcalculationTimedout
int _numConsecutiveMaterialcalculationSuccessful
IVector _materialParameters
List< JMatProElemetData > _compositionData
Storage of composition data.
volatile List< JMatProElemetData > _elementData
string[] _compositionElementSymbols
string _projectName
string _simulationName
string _rootSimulationDirectoryname = SimJMatProConst.RootSimulationDirectoryName
string _rootSimulationDirectoryPath
string _simulatorBaseTemplateDirectoryname
string _simulatorBaseTemplateDirectoryPath
string _simulatorCastingRobertDirectoryname = SimJMatProConst.SimulatorCastingRobertDirectoryname
int _whichSimulation = 0
string _simulatorBaseDirectoryPath
string _simCastingRobertRootDirectoryPath
SimCastingRobertFileManager _simCastingRobertFM
Static Protected Attributes
static bool _elementsInitialized = false
Properties
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
object InternalLock [get]
Used internally for locking access to internal fields.
string LockFileMutexName [get, protected set]
Name of the mutex for system-wide locking of files.
Mutex LockFileMutex [get]
Mutex for system-wide exclusive locks for file system operations related to the current class.
int OutputLevel [get, set]
Level of information that is output to the console by some methods.
abstract string NameJMatProBase [get, set]
Name of the JMatPro directory (without root directories) and executable.
virtual string JMatInstallationPath [get, set]
Path of the directory where JMAtPro executable is located. Setter takes only pure directory name, without path information. If set to null then directory path is set to null and will be recalculated when getter is called.
virtual string JMatExecutableFileName [get, set]
JMatPro executable relative path to installation directory.
virtual string JMatExecutableFilePath [get, set]
Path to the JMatPro executable.
virtual string JMatDataPath [get, set]
Path to the JMatPro data directory (containing material data, input and output data, etc.)
virtual string JMatCompositionFilename [get, set]
Relative path, with respect to JMatPro data directory, of the file containing material composition (input for JMatPro calculation).
virtual string JMatCompositionFilePath [get, set]
Path of the file containing material composition (input for JMatPro calculation).
virtual string JMatResultsFilename [get, set]
Relative path, with respect to JMatPro data directory, of the file containing material results of JMatPro calculation.
virtual string JMatResultsFilePath [get, set]
Path of the file containing results of JMatPro calculation.
virtual string JMatCompletionDetectionFilename [get, set]
Relative path, with respect to JMatPro data directory, of the file used to detect whether calculation is still going on.
virtual string JMatCompletionDetectionFilePath [get, set]
Path of the file used to detect whether calculation is still going on.
virtual double JMatCompletionDetectionSleepTimeSeconds [get, set]
Sleeping time used in detectiong whether JMatPro calculation is still going on.
virtual int JMatCompletionDetectionSize [get, set]
Minimal size of calculation detection file above which calculation is considered finished.
virtual double JMatBeforeSaveSleepTimeSeconds [get, set]
Waiting time (in seconds) after last increase in file size used before assuming that calculation is finished, to eventually prevent too early detection that calculation was finished.
bool CheckWorkingDirectoryExistence [get, set]
Whether existence of working directory is checked when directory is created. Default is true.
string WorkingDirectory [get, set]
Working directory where configuration files and other files are located.
virtual string DataDefinitionSupersetFilename [get, set]
Name of the file containing definition data for the superset of all input parameters and output values.
virtual string DataDefinitionSupersetFilePath [get, set]
Path to the file containing definition data for the superset of all input parameters and output values.
virtual string DataDefinitionJMatFilename [get, set]
Name of the file containing data definition for all JMatPro input parameters (i.e. material composition expressed as mass fractions for individual parameters).
virtual string DataDefinitionJMatFilePath [get, set]
Path to the file containing data definition for all JMatPro input parameters (i.e. material composition expressed as mass fractions for individual parameters).
virtual string DataDefinitionProcessFilename [get, set]
Name of the file containing data definition for all process input and output parameters.
virtual string DataDefinitionProcessFilePath [get, set]
Path to the file containing data definition for all process input and output parameters.
virtual string DataDefinitionJointFilename [get, set]
Name of the file containing definition data for the superset of all input parameters and output values.
virtual string DataDefinitionJointFilePath [get, set]
Path to the file containing definition data for the Joint of all input parameters and output values.
virtual string DataDefinitionJMatFilenameNoNitrogen [get, set]
Name of the file containing data definition for all JMatPro input parameters (i.e. material composition expressed as mass fractions for individual parameters).
virtual string DataDefinitionJMatFilePathNoNitrogen [get, set]
Path to the file containing data definition for all JMatPro input parameters (i.e. material composition expressed as mass fractions for individual parameters).
virtual string DataDefinitionJointFilenameNoNitrogen [get, set]
Name of the file containing definition data for the superset of all input parameters and output values.
virtual string DataDefinitionJointFilePathNoNitrogen [get, set]
Path to the file containing definition data for the Joint of all input parameters and output values.
InputOutputDataDefiniton DataDefinitionSuperset [get, protected set]
Data definitions for the superset of all input parameters and output values.
InputOutputDataDefiniton DataDefinitionJMat [get, protected set]
Data definitions for all JMatPro input parameters (i.e. material composition expressed as mass fractions for individual parameters).
virtual IBoundingBox MaterialParameterBounds [get, protected set]
Bounds on neural input parameters.
InputOutputDataDefiniton DataDefinitionProcess [get, protected set]
Data definitions for the Process parameters and output values.
InputOutputDataDefiniton DataDefinitionJoint [get, protected set]
Data definitions for all input parameters and output values, including material and process parameters.
int NumMaterialParameters [get]
Gets the number of material parameters.
int NumProcessParameters [get]
Gets the number of process parameters.
int NumParameters [get]
Gets the total number of all parameters.
int NumOutputValues [get]
Gets the number of output values for the process.
virtual string WorkingMaterialParametersPath [get, protected set]
File path of the file in working directory where material parameters for calculation are stored. If set to null then path is set to null and will be recalculated when getter is called.
virtual string MaterialParametersDefFilename [get, set]
Name of the file in material data directory where material parameters are stored.
virtual string WorkingMaterialParametersDefPath [get, protected set]
File path of the file in working directory where material parameters for calculation are stored as default values in a data definition file. If set to null then path is set to null and will be recalculated when getter is called.
string RootDataDirectoryName [get, set]
Name of the root data directory.
virtual string RootDataDirectoryPath [get, set]
Path to the root directory that contains directories with calculated material data for different parameters defining chemical compositions.
virtual string LogFileName [get, set]
Name of the log file where operations are logged.
virtual string LogFilePath [get, set]
Path to the log file where basic operations are logged.
TextWriter LogFileWriter [get, set]
Textwriter for log file.
string MaterialDirectoryName [get, protected set]
Name of the material directory.
virtual string MaterialDataDirectoryPath [get, protected set]
Data directory for the current material parameters.
virtual string MaterialParametersFilename [get, set]
Name of the file in material data directory where material parameters are stored.
virtual string MaterialParametersPath [get, protected set]
File path of the file where material parameters are stored. If set to null then path is set to null and will be recalculated when getter is called.
virtual string MaterialCompositionFilename [get, set]
Name of the file in material data directory where material composition is stored.
virtual string MaterialCompositionPath [get, protected set]
File path of the file (normally in the material data directory) where material composition is stored. If set to null then path is set to null and will be recalculated when getter is called.
virtual string MaterialResultsFilename [get, set]
Name of the file in material data directory where material results are stored.
virtual string MaterialResultsPath [get, protected set]
File path of the file (normally in the material data directory) where material reslts are stored. If set to null then path is set to null and will be recalculated when getter is called.
virtual int JMatResultsMinimalSize [get, protected set]
Minimal size of JMatPro results file in order to consider results valid.
virtual int JMatResultsGoodSize [get, protected set]
Size of the materials result file that is considered a good size - the file is expected to be at least of this size if calculation was performed without errors.
virtual string MsgMaterialCalculationBusyPath [get, protected set]
File path of the material calculation in progress flag file. Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
virtual string MsgMaterialCalculationFinishedPath [get, protected set]
File path of the "material calculation finished" flag file. Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
virtual string MsgMaterialCalculationTimedoutPath [get, protected set]
File path of the "material calculation timeout occurred" flag file. Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
virtual string MsgMaterialResultsWrongPath [get, protected set]
File path of the "material results wrong" flag file. Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
virtual string StorageMaterialCalculatedDirectoryname [get, set]
Name of the storage directory for material directories for which material properties have been successfully calculated.
virtual string StorageMaterialCalculatedDirectoryPath [get, protected set]
Path to the storage directory for material directories for which material properties have been successfully calculated.
virtual string StorageBusyFlagSetDirectoryname [get, set]
Name of the storage directory for material directories for which busy flag remained set.
virtual string StorageBusyFlagSetDirectoryPath [get, protected set]
Path to the storage directory for material directories for which busy flag remained set.
virtual string StorageTimedoutDirectoryname [get, set]
Name of the storage directory for material directories for which material properties calculation has timed out.
virtual string StorageTimedoutDirectoryPath [get, protected set]
Path to the storage directory for material directories for which material properties calculation has timed out.
virtual string StorageMaterialCalculationFailedDirectoryname [get, set]
Path to the storage directory for material directories for which calculation of material properties has failed.
virtual string StorageMaterialCalculationFailedDirectoryPath [get, protected set]
Path to the storage directory for material directories for which calculation of material properties has failed.
virtual string StorageMaterialMaterialDataCorruptedDirectoryname [get, set]
Path to the storage directory for material directories for which calculation of material properties has failed.
virtual string StorageMaterialMaterialDataCorruptedDirectoryPath [get, protected set]
Path to the storage directory for material directories for which calculation of material properties has failed.
virtual string UserInteractionCommand [get, set]
Command for playback of recorded user interaction (i.e. emulation of keyboard and mouse events) for various actions.
virtual string UserInteractionRecordDir [get, set]
Dierctory containing recorded user interactions for different actions.
virtual string UserInteractionRecordExtension [get, set]
Extension of files with recorded user interaction.
virtual string UserInteractionRecordNameStartJMat [get, set]
Name of the user interaction record for starting JMatPro software via system GUI.
virtual string UserInteractionRecordPathStartJMat [get, set]
Name of the user interaction record for closing JMatPro software via system GUI.
virtual string UserInteractionRecordNameCloseJMat [get, set]
Name of the user interaction record for closing JMatPro software normally via GUI.
virtual string UserInteractionRecordPathCloseJMat [get, set]
Name of the user interaction record for closing JMatPro software normally via GUI.
virtual string UserInteractionRecordNameRepairJMat [get, set]
Name of the file containing records of user interaction necessary repair JMatPro in case it is damaged or another unwanted copy is running.
virtual string UserInteractionRecordPathRepairJMat [get, set]
Path of the file containing records of user interaction necessary repair JMatPro in case it is damaged or another unwanted copy is running.
virtual string UserInteractionRecordNameStartCalculation [get, set]
Name of the file containing recors of user interaction necessary to start JMatPro.
virtual string UserInteractionRecordPathStartCalculation [get, set]
Name of the file containing recors of user interaction necessary to start JMatPro.
virtual string UserInteractionRecordNameSaveResults [get, set]
Name of the file containing records of user interaction necessary to save results of JMatPro calculation.
virtual string UserInteractionRecordPathSaveResults [get, set]
Path to the file containing recors of user interaction necessary to save results of JMatPro calculation.
virtual string UserInteractionRecordNameChangeTemperatureUnit [get, set]
Name of the file containing records of user interaction necessary to change temperature uits in JMatPro that is already launched.
virtual string UserInteractionRecordPathChangeTemperatureUnit [get, set]
Path to the file containing recors of user interaction necessary to change temperature uits in JMatPro that is already launched.
virtual string UserInteractionRecordNameChangeFractionUnit [get, set]
Name of the file containing records of user interaction necessary to change fraction uits in JMatPro that is already launched.
virtual string UserInteractionRecordPathChangeFractionUnit [get, set]
Path to the file containing recors of user interaction necessary to change fraction uits in JMatPro that is already launched.
double JMatTimeoutWaitCalculationSeconds [get, protected set]
Timeout for waiting completion of calculation, in seconds.
virtual double JMatTimeoutWaitResultsSavedSeconds [get, protected set]
Timeout for waiting until results are completely saved, in seconds.
virtual int JMatResultsSavedDetectionSize [get, set]
Minimal size of result file file, above which saving results can be considered finished.
virtual double JMatBeforeResultsSavedSleepTimeSeconds [get, set]
Waiting time (in seconds) after last increase in file size used before assuming that saving result is finished, to eventually prevent too early detection that calculation was finished.
string ProcessNameSubstringJava [get, protected set]
Substring of java virtual machine process name, used to kill the process or check whether it is running.
string ProcessNameSubstringJMatMain [get, protected set]
Substring of JMatPro main process name, used to kill the process or check whether it is running.
string ProcessNameSubstringJMatSolver [get, protected set]
Substring of JMatPro solver process name, used to kill the process or check whether it is running.
CalculationStatus MaterialCalculationStatus [get, protected set]
Status of the last material calculation.
StopWatch1 MaterialCalculationTimer [get]
Timer for measuring total calculation time in methods that perform multiple material calculations.
double LongestMaterialCalculationTime [get, protected set]
Longest material calculation time by now, reset at the beginning of every top level calculation function.
double MaterialCalculationTime [get, set]
int NumMaterialCalculationsIntended [get, protected set]
Total number of intended material calculations attempted by now.k
int NumMaterialCalculationsPerformed [get, protected set]
Number of (completed) material calculations attempted by now.
int NumMaterialCalculationsSuccessful [get, protected set]
Number of material calculations by now that have successfully completed.
int NumMaterialCalculationsTimedout [get, protected set]
Number of material calculations by now where timeout occurred.
int NumMaterialCalculationsUnsuccessful [get, protected set]
Number of material calculations by now where calculation has failed.
int NumconsecutiveMaterialCalculationsUnsuccessful [get, set]
Number fo consecutive events where material calculation was not successfule.
int NumconsecutiveMaterialCalculationTimedout [get, set]
Number fo consecutive events where timeout occurred during material calculation.
int NumconsecutiveMaterialCalculationsSuccessful [get, set]
Number fo consecutive events where material calculation was not successful.
IVector MaterialParameters [get, set]
Parameters that define chemical composition of steel for which material properties are calculated.
virtual IRandomGenerator Random [get, protected set]
Random generator used by the current object.
List< JMatProElemetData > Elements [get, set]
List of element data to be used in JMatPro.
string[] CompositionElementSymbols [get, set]
Array of element symbols sorted as required gor the JMatPro input file.
virtual string SymbolIron [get]
virtual string ProjectName [get, protected set]
Name of the current project, used in some simulation and other interfaces.
virtual string SimulationName [get, protected set]
Name of the current simulation, used in some simulation and other interfaces.
string RootSimulationDirectoryName [get, set]
Name of the root simulation directory.
virtual string RootSimulationDirectoryPath [get, set]
Path to the root simulator directory that contains directories with simulators' data (there may be more than one such directory in the case of parallel simulators.
string SimulatorBaseTemplateDirectoryname [get, set]
Name of the simulator template directory. This is the root simulator directory that contains all simuator related data and must be copied in order to produce a new active simulator.
virtual string SimulatorBaseTemplateDirectoryPath [get, protected set]
Path to the simulator template directory. This is the root simulator directory that contains all simuator related data and must be copied in order to produce a new active simulator.
string SimulatorCastingRobertDirectoryname [get, set]
Name of the main directory of the Robert Vertnik's casting simulator.
virtual string SimCastingRobertProjectName [get, set]
Project name for interfacing Robert Vertnik's casting simulator.
virtual string SimCastingRobertSimulationName [get, set]
Simulation name for interfacing Robert Vertnik's casting simulator.
int WhichSimulator [get, protected set]
Specifies which simulator is in use by the current file manager (this is 0 if simulators are not run in parallel and there is a single simulator).
virtual string SimulatorBaseDirectoryPath [get, protected set]
Path to the base directory of the current simulator in use. This directory is directly contained in the
virtual string SimCastingRobertRootDirectoryPath [get, protected set]
Path of the main directory of the Robert Vertnik's casting simulator that is currently in use.
virtual SimCastingRobertFileManager SimCastingRobertFM [get, set]
File manager for interfacing Robert Vertnik's casting simulator. Lazy evaluation: The object is created when first accessed, if possible. For this, ProjectName, SimulationName and SimCastingRobertRootDirectoryPath must be defined.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
object _mainLock = new object()
object _internalLock = new object()
int _outputLevel = Util.OutputLevel
IRandomGenerator _randGen
Detailed Description
File manager for interfacing the JMatPro software.
JMatPro is a software for calculation of material parameters.
Since JMatPro is interactive software, user interaction must be emulated in order to transform it to noninteractive mode. External software is used for this.
Parts of this interface have been created for quick implementatio of needed functionality, sometimes on account of modularity and etensibility. Interface depends on many settings (different directory and file paths), therefore usual way of initialization is by providing a settings file of type SimJmatProSettingsDto that contains these settings.
$A Igor Sep12 Nov12;
Simulation part of the class definition:
This part of the JMatPro file manager class contains definitions of utilites related to simulators.
Simulation part of the class definition - SUBCLASSES:
This part of the JMatPro file manager class contains definitions of classes for managing simulators.
Member Enumeration Documentation
CalculationStatus
enum IG.Num.SimJMatProFileManagerBase.CalculationStatus strong
Enumerator
None
Successful
Incomplete
Corrupted
Timedout
Failed
Unsuccessful
Constructor & Destructor Documentation
SimJMatProFileManagerBase() [1/3]
IG.Num.SimJMatProFileManagerBase.SimJMatProFileManagerBase (string workingDirectoryPath) inline
Construct JMatPro interface's file manager, with specified working directory.
If settings file exists at the default location in this directory (i.e. SimJMatProConst.SettingsFileName) then settings are loaded from this file.
Parameters
workingDirectoryPath Path of the working directory.
References IG.Num.SimJMatProFileManagerBase.LoadSettings(), IG.Lib.SimJMatProConst.SettingsFileName, and IG.Num.SimJMatProFileManagerBase.WorkingDirectory.
SimJMatProFileManagerBase() [2/3]
IG.Num.SimJMatProFileManagerBase.SimJMatProFileManagerBase (string workingDirectoryPath, string settingsFilePath) inline
Construct JMatPro interface's file manager, with specified working directory and path to the file where settings are stored.
Parameters
workingDirectoryPath Path of the working directory.
settingsFilePath Path to the file containing settings.
It can be specified as absolute path or relative to the current directory or relative to the working directory. If null or empty string then default path is taken.
References IG.Num.SimJMatProFileManagerBase.LoadSettings(), IG.Lib.SimJMatProConst.SettingsFileName, IG.Lib.UtilSystem.StandardizeDirectoryPath(), and IG.Num.SimJMatProFileManagerBase.WorkingDirectory.
SimJMatProFileManagerBase() [3/3]
IG.Num.SimJMatProFileManagerBase.SimJMatProFileManagerBase (string workingDirectoryPath, SimJmatProSettingsDto settings) inline
Construct JMatPro interface's file manager, with specified working directory and settings object.
Parameters
workingDirectoryPath Path of the working directory.
settings Object containing settings for hte JMatpro file manager.
References IG.Num.SimJMatProFileManagerBase.WorkingDirectory.
Member Function Documentation
LockFileMutexCheckAbandoned()
bool IG.Num.SimJMatProFileManagerBase.LockFileMutexCheckAbandoned () inline
Check whether the file system locking mutex (property LockFileMutex) has been abandoned, and returns true if it has been (otherwise, false is returned).
After the call, mutex is no longer in abandoned state (WaitOne() will not throw an exception) if it has been before the call.
Call does not block.
Returns
true if mutex has been abandoned, false otherwise.
References IG.Num.SimJMatProFileManagerBase.LockFileMutex, and IG.Lib.Util.MutexCheckAbandoned().
Error()
void IG.Num.SimJMatProFileManagerBase.Error (string errorMsg) inline
Temporary utility for reporting errors in the development stage.
Parameters
errorMsg Error message.
Referenced by IG.Num.SimJMatProFileManagerBase.GetMaterialParametersDefault().
ErrorNotImplemented()
void IG.Num.SimJMatProFileManagerBase.ErrorNotImplemented (string errorMsg) inline
Temporary utility for reporting errors in the development stage.
Parameters
errorMsg Error message.
GetRandomMaterialParameters() [1/2]
virtual void IG.Num.SimJMatProFileManagerBase.GetRandomMaterialParameters (ref IVector result) inline virtual
Generates a random vector of material parameters whose elements (components) lie within the lower and upper bounds on parameters, and stores it to the specified vector.
Random generator of the current JMatPro interface objects is used.
Parameters
result Vector object where the generated random vector is stored; allocated if necessary.
References IG.Num.SimJMatProFileManagerBase.Random.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialPropertiesRandomSet().
GetRandomMaterialParameters() [2/2]
virtual void IG.Num.SimJMatProFileManagerBase.GetRandomMaterialParameters (IRandomGenerator rand, ref IVector result) inline virtual
Generates a random vector of material parameters whose elements (components) lie within the lower and upper bounds on parameters, and stores it to the specified vector.
Parameters
rand Random number generator used to generate the elements.
result Vector object where the generated random vector is stored; allocated if necessary.
References IG.Num.IBoundingBox.GetRandomPoint(), and IG.Num.SimJMatProFileManagerBase.MaterialParameterBounds.
CreateJointParameters()
virtual void IG.Num.SimJMatProFileManagerBase.CreateJointParameters (IVector materialParameters, IVector processParameters, ref IVector jointParameters) inline virtual
Combines the specified vectors of materaial and process parameters into a joint vector of process parameters and stored it into the specified variable.
Vectors of material and process parameters must be of correct dimensons, otherwise exception is thrown.
Parameters
materialParameters Vector of material parameters.
processParameters Vector of process parameters.
jointParameters Vector variable where combined vector of problem parameters is stored.
References IG.Num.IVector< T >.Length, IG.Num.SimJMatProFileManagerBase.NumMaterialParameters, IG.Num.SimJMatProFileManagerBase.NumParameters, IG.Num.SimJMatProFileManagerBase.NumProcessParameters, and IG.Num.VectorBase.Resize().
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateSimulatedResponse().
ExtractMaterialParameters()
virtual void IG.Num.SimJMatProFileManagerBase.ExtractMaterialParameters (IVector jointParameters, ref IVector materialParameters) inline virtual
Extracts the vector of material parameters from the specified joint vector of problem parameters, and stores it to the specified variable.
Parameters
jointParameters Complete vector of problem parameters.
materialParameters Vector variable where the extracted material parameters are stored.
References IG.Num.SimJMatProFileManagerBase.NumMaterialParameters, and IG.Num.VectorBase.Resize().
Referenced by IG.Num.SimJMatProFileManagerBase.ExtractMaterialAndProcessParameters().
ExtractProcessParameters()
virtual void IG.Num.SimJMatProFileManagerBase.ExtractProcessParameters (IVector jointParameters, ref IVector processParameters) inline virtual
Extracts the vector of process parameters from the specified joint vector of problem parameters, and stores it to the specified variable.
Parameters
jointParameters Complete vector of problem parameters.
processParameters Vector variable where the extracted process parameters are stored.
References IG.Num.SimJMatProFileManagerBase.NumMaterialParameters, IG.Num.SimJMatProFileManagerBase.NumProcessParameters, and IG.Num.VectorBase.Resize().
Referenced by IG.Num.SimJMatProFileManagerBase.ExtractMaterialAndProcessParameters().
ExtractMaterialAndProcessParameters()
virtual void IG.Num.SimJMatProFileManagerBase.ExtractMaterialAndProcessParameters (IVector jointParameters, ref IVector materialParameters, ref IVector processParameters) inline virtual
Extracts the vectors of material and process parameters from the specified joint vector of problem parameters, and stores them to the specified variable.
Parameters
jointParameters Complete vector of problem parameters.
materialParameters Vector variable where the extracted material parameters are stored.
processParameters Vector variable where the extracted process parameters are stored.
References IG.Num.SimJMatProFileManagerBase.ExtractMaterialParameters(), and IG.Num.SimJMatProFileManagerBase.ExtractProcessParameters().
GetMaterialDirectoryName()
virtual string IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoryName (IVector parameters) inline virtual
Returns name of the material directory for the specified material parameters.
Parameters
parameters Material parameters to which the returned directory name corresponds.
References IG.Lib.SimJMatProConst.DataDirectoryPrefix, and IG.Num.VectorBase.GetHashFunctionString().
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Script.S_12_09_jmatpro.CommandTestRestart(), and IG.Num.SimJMatProFileManagerBase.RetryCalculateMaterialProperties().
CreateMaterialDataDirectory()
virtual bool IG.Num.SimJMatProFileManagerBase.CreateMaterialDataDirectory () inline virtual
Creates the data directory for the current material (specified by material parameters).
Returns
True if directory has been created, false if not (this usually means that directory had existed before).
References IG.Num.SimJMatProFileManagerBase.LockFileMutex, and IG.Num.SimJMatProFileManagerBase.MaterialDataDirectoryPath.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties().
MoveMaterialDirectory()
bool IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectory (string materialDirectoryPath, string storageDirectoryPath) inline
Moves the specified material directory to the specified storage directory.
Directory is not moved if a busy flag is set. In this case, a report is written to the log file.
Paths must be valid paths, not just short approximate paths. You can use
Operation is performed in a colision safe way by using a mutex.
Parameters
materialDirectoryPath Path to the material directory that is moved. It must be a valid path to the directory, not only approximate path. Directory existence is checked prior to operation.
storageDirectoryPath Path to the storage directory into which directory is moved. If the dtorage directory does not yet exist then it is created.
Exceptions
Returns
True if directory was successfully moved, false otherwise.
References IG.Num.SimJMatProFileManagerBase.IsBusyFlagSet(), IG.Num.SimJMatProFileManagerBase.LockFileMutex, and IG.Num.SimJMatProFileManagerBase.LogFileWriter.
Referenced by IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageBusyFlagSet(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageCalculationFailed(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageDataCorrupted(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageMaterialCalculated(), and IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageTimedout().
MoveMaterialDirectoryToStorageMaterialCalculated()
int IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageMaterialCalculated () inline
Moves to the appropeiate storage directory those material directories for which material properties have been successfully calculated.
Returns
The number of directories that were actually moved.
References IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereMaterialCalculated(), IG.Num.SimJMatProFileManagerBase.IsBusyFlagSet(), IG.Num.SimJMatProFileManagerBase.IsMaterialCalculated(), IG.Num.SimJMatProFileManagerBase.IsMaterialDirectoryCorrupted(), IG.Num.SimJMatProFileManagerBase.LogFileWriter, IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectory(), and IG.Num.SimJMatProFileManagerBase.StorageMaterialCalculatedDirectoryPath.
Referenced by IG.Script.S_12_09_jmatpro.CommandMoveMaterialDirectoriesMaterialCalculated(), and IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoriesToStorageAll().
MoveMaterialDirectoryToStorageBusyFlagSet()
int IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageBusyFlagSet () inline
Moves to the appropeiate storage directory those material directories for which busy flag remained set.
Returns
The number of directories that were actually moved.
References IG.Num.SimJMatProFileManagerBase.ClearBusyFlag(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereBusySet(), IG.Num.SimJMatProFileManagerBase.IsBusyFlagSet(), IG.Num.SimJMatProFileManagerBase.LogFileWriter, IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectory(), and IG.Num.SimJMatProFileManagerBase.StorageBusyFlagSetDirectoryPath.
Referenced by IG.Script.S_12_09_jmatpro.CommandMoveMaterialDirectoriesBusyFlagSet(), and IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoriesToStorageAll().
MoveMaterialDirectoryToStorageTimedout()
int IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageTimedout () inline
Moves to the appropeiate storage directory those material directories for which material properties calculation has timed out.
Returns
The number of directories that were actually moved.
References IG.Num.SimJMatProFileManagerBase.ClearBusyFlag(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereTimedout(), IG.Num.SimJMatProFileManagerBase.IsBusyFlagSet(), IG.Num.SimJMatProFileManagerBase.IsTimedoutFlagSet(), IG.Num.SimJMatProFileManagerBase.LogFileWriter, IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectory(), and IG.Num.SimJMatProFileManagerBase.StorageTimedoutDirectoryPath.
Referenced by IG.Script.S_12_09_jmatpro.CommandMoveMaterialDirectoriesTimedout(), and IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoriesToStorageAll().
MoveMaterialDirectoryToStorageCalculationFailed()
int IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageCalculationFailed () inline
Moves to the appropeiate storage directory those material directories for which material properties calculation failed (regardless of reason).
Returns
The number of directories that were actually moved.
References IG.Num.SimJMatProFileManagerBase.ClearBusyFlag(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereCalculationFailed(), IG.Num.SimJMatProFileManagerBase.IsBusyFlagSet(), IG.Num.SimJMatProFileManagerBase.IsMaterialCalculated(), IG.Num.SimJMatProFileManagerBase.LogFileWriter, IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectory(), and IG.Num.SimJMatProFileManagerBase.StorageMaterialCalculationFailedDirectoryPath.
Referenced by IG.Script.S_12_09_jmatpro.CommandMoveMaterialDirectoriesCalculationFailed(), and IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoriesToStorageAll().
MoveMaterialDirectoryToStorageDataCorrupted()
int IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageDataCorrupted () inline
Moves to the appropeiate storage directory those material directories for which material data is corrupted (e.g. material parameters are not written properly).
Returns
The number of directories that were actually moved.
References IG.Num.SimJMatProFileManagerBase.ClearBusyFlag(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereMaterialDataCorrupted(), IG.Num.SimJMatProFileManagerBase.IsBusyFlagSet(), IG.Num.SimJMatProFileManagerBase.IsMaterialDirectoryCorrupted(), IG.Num.SimJMatProFileManagerBase.LogFileWriter, IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectory(), and IG.Num.SimJMatProFileManagerBase.StorageMaterialCalculationFailedDirectoryPath.
Referenced by IG.Script.S_12_09_jmatpro.CommandMoveMaterialDirectoriesDataCorrupted(), and IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoriesToStorageAll().
MoveMaterialDirectoriesToStorageAll()
int IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoriesToStorageAll (bool moveBusy, bool moveMaterialCalculated) inline
Moves all material directries to the appropriate storage directories, dependent on the state of calculation in any particular directory.
Parameters
moveBusy Whether directories where busy flag is set are also moved.
moveMaterialCalculated Whether directories where material properties were successfully calculated are also moved.
Returns
References IG.Num.SimJMatProFileManagerBase.LogFileWriter, IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageBusyFlagSet(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageCalculationFailed(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageDataCorrupted(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageMaterialCalculated(), and IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageTimedout().
Referenced by IG.Script.S_12_09_jmatpro.CommandMoveMaterialDirectoriesAll().
IsMaterialCalculationBusy()
bool IG.Num.SimJMatProFileManagerBase.IsMaterialCalculationBusy () inline
Flag indicating whether material calculation for the current material parameters is in progress.
References IG.Num.SimJMatProFileManagerBase.LockFileMutex, IG.Num.SimJMatProFileManagerBase.MaterialDataDirectoryPath, and IG.Num.SimJMatProFileManagerBase.MsgMaterialCalculationBusyPath.
ClearMaterialCalculationBusy()
virtual void IG.Num.SimJMatProFileManagerBase.ClearMaterialCalculationBusy () inline virtual
Clears the flag indicating that material calculation is in progress.
References IG.Num.SimJMatProFileManagerBase.LockFileMutex, and IG.Num.SimJMatProFileManagerBase.MsgMaterialCalculationBusyPath.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties().
SetMaterialCalculationBusy()
virtual bool IG.Num.SimJMatProFileManagerBase.SetMaterialCalculationBusy () inline virtual
Sets the flag indicating that material calculation directory is used, and returns true if the flag was successfully set.
If the flag is currently set then this method blocks until it is released.
References IG.Num.SimJMatProFileManagerBase._waitSleepTimeSeconds, IG.Num.SimJMatProFileManagerBase.LockFileMutex, IG.Num.SimJMatProFileManagerBase.MsgMaterialCalculationBusyPath, and IG.Lib.Util.SleepSeconds().
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties().
IsMaterialCalculationFinished()
bool IG.Num.SimJMatProFileManagerBase.IsMaterialCalculationFinished () inline
Flag indicating whether material calculation for the current material parameters is finished.
References IG.Num.SimJMatProFileManagerBase.LockFileMutex, IG.Num.SimJMatProFileManagerBase.MaterialDataDirectoryPath, and IG.Num.SimJMatProFileManagerBase.MsgMaterialCalculationFinishedPath.
ClearMaterialCalculationFinished()
virtual void IG.Num.SimJMatProFileManagerBase.ClearMaterialCalculationFinished () inline virtual
Clears the flag indicating that material calculation is finished.
References IG.Num.SimJMatProFileManagerBase.LockFileMutex, and IG.Num.SimJMatProFileManagerBase.MsgMaterialCalculationFinishedPath.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), and IG.Num.SimJMatProFileManagerBase.SetMaterialResultsWrong().
SetMaterialCalculationFinished()
virtual void IG.Num.SimJMatProFileManagerBase.SetMaterialCalculationFinished () inline virtual
Sets the flag indicating that material calculation is finished.
References IG.Num.SimJMatProFileManagerBase.LockFileMutex, and IG.Num.SimJMatProFileManagerBase.MsgMaterialCalculationFinishedPath.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties().
IsMaterialCalculationTimedout()
bool IG.Num.SimJMatProFileManagerBase.IsMaterialCalculationTimedout () inline
Flag indicating whether material calculation for the current material parameters has timed out.
References IG.Num.SimJMatProFileManagerBase.LockFileMutex, IG.Num.SimJMatProFileManagerBase.MaterialDataDirectoryPath, and IG.Num.SimJMatProFileManagerBase.MsgMaterialCalculationTimedoutPath.
ClearMaterialCalculationTimedout()
virtual void IG.Num.SimJMatProFileManagerBase.ClearMaterialCalculationTimedout () inline virtual
Clears the flag indicating that material calculation has timed out.
References IG.Num.SimJMatProFileManagerBase.LockFileMutex, and IG.Num.SimJMatProFileManagerBase.MsgMaterialCalculationTimedoutPath.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties().
SetMaterialCalculationTimedout()
virtual void IG.Num.SimJMatProFileManagerBase.SetMaterialCalculationTimedout (double timeOutSeconds) inline virtual
Sets the flag indicating that material calculation has timed out.
References IG.Num.SimJMatProFileManagerBase.LockFileMutex, and IG.Num.SimJMatProFileManagerBase.MsgMaterialCalculationTimedoutPath.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties().
IsMaterialResultsWrong()
bool IG.Num.SimJMatProFileManagerBase.IsMaterialResultsWrong () inline
Flag indicating whether material results are incorrect.
References IG.Num.SimJMatProFileManagerBase.LockFileMutex, IG.Num.SimJMatProFileManagerBase.MaterialDataDirectoryPath, and IG.Num.SimJMatProFileManagerBase.MsgMaterialResultsWrongPath.
ClearMaterialResultsWrong()
virtual void IG.Num.SimJMatProFileManagerBase.ClearMaterialResultsWrong () inline virtual
Clears the flag indicating that material result file is incorrect.
References IG.Num.SimJMatProFileManagerBase.LockFileMutex, and IG.Num.SimJMatProFileManagerBase.MsgMaterialResultsWrongPath.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties().
SetMaterialResultsWrong()
virtual void IG.Num.SimJMatProFileManagerBase.SetMaterialResultsWrong (string errorsString) inline virtual
Sets the flag indicating that material result file is incorrect.
Parameters
errorsString String containing detected errors in the result file.
References IG.Num.SimJMatProFileManagerBase.ClearMaterialCalculationFinished(), IG.Num.SimJMatProFileManagerBase.LockFileMutex, and IG.Num.SimJMatProFileManagerBase.MsgMaterialResultsWrongPath.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties().
JMatLaunch()
virtual void IG.Num.SimJMatProFileManagerBase.JMatLaunch () inline virtual
Safely launches the JMatpPro software.
Tries to ensure that software has actually been launched.
References IG.Num.SimJMatProFileManagerBase.IsJMatProRunning(), IG.Num.SimJMatProFileManagerBase.JMatClose(), IG.Num.SimJMatProFileManagerBase.JMatOpen(), IG.Num.SimJMatProFileManagerBase.JMatRepair(), IG.Num.SimJMatProFileManagerBase.KillJMatPro(), and IG.Num.SimJMatProFileManagerBase.LogFileWriter.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties().
JMatOpen()
virtual void IG.Num.SimJMatProFileManagerBase.JMatOpen () inline virtual
Just starts the JMatPro software.
References IG.Lib.UtilSystem.ExecuteSystemCommand(), IG.Num.SimJMatProFileManagerBase.UserInteractionCommand, and IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathStartJMat.
Referenced by IG.Num.SimJMatProFileManagerBase.JMatLaunch().
JMatRepair()
virtual void IG.Num.SimJMatProFileManagerBase.JMatRepair () inline virtual
Repairs JMatPro, e.g. if it has been stopped abruptly or if another version is already running somewhere such that we could not start it.
After calling this method, JMatPro should be able to start normally.
References IG.Lib.UtilSystem.ExecuteSystemCommand(), IG.Num.SimJMatProFileManagerBase.UserInteractionCommand, and IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathRepairJMat.
Referenced by IG.Num.SimJMatProFileManagerBase.JMatLaunch().
JMatClose()
virtual void IG.Num.SimJMatProFileManagerBase.JMatClose () inline virtual
Closes JMatPro normally, by simulated user interaction.
References IG.Lib.UtilSystem.ExecuteSystemCommand(), IG.Num.SimJMatProFileManagerBase.UserInteractionCommand, and IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathCloseJMat.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), and IG.Num.SimJMatProFileManagerBase.JMatLaunch().
JMatStartCalculation()
virtual void IG.Num.SimJMatProFileManagerBase.JMatStartCalculation () inline virtual
Starts JMatPro calculation.
References IG.Lib.UtilSystem.ExecuteSystemCommand(), IG.Num.SimJMatProFileManagerBase.UserInteractionCommand, and IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathStartCalculation.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties().
JMatSaveResults()
virtual void IG.Num.SimJMatProFileManagerBase.JMatSaveResults () inline virtual
Saves results of JMatPro calculation.
References IG.Lib.UtilSystem.ExecuteSystemCommand(), IG.Num.SimJMatProFileManagerBase.UserInteractionCommand, and IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathSaveResults.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties().
JMatChangeTemperatureUnit()
virtual void IG.Num.SimJMatProFileManagerBase.JMatChangeTemperatureUnit () inline virtual
Changes (toggles once) temperature unit in an open window of JMatPro (software must be running and its main window on the top of window stack) by running the appropriate script.
References IG.Lib.UtilSystem.ExecuteSystemCommand(), IG.Num.SimJMatProFileManagerBase.UserInteractionCommand, and IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathChangeTemperatureUnit.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties().
JMatChangeFractionUnit()
virtual void IG.Num.SimJMatProFileManagerBase.JMatChangeFractionUnit () inline virtual
Changes (toggles once) fraction unit in an open window of JMatPro (software must be running and its main window on the top of window stack) by running the appropriate script.
References IG.Lib.UtilSystem.ExecuteSystemCommand(), IG.Num.SimJMatProFileManagerBase.UserInteractionCommand, and IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathChangeFractionUnit.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties().
JMatWaitCalculation()
virtual bool IG.Num.SimJMatProFileManagerBase.JMatWaitCalculation () inline virtual
Waits until JMatPro calculation finishes.
Returns true if it could be detected properly that calculation finished, false otherwise.
Timeout is defined by the JMatTimeoutWaitCalculationSeconds property.
References IG.Num.SimJMatProFileManagerBase.JMatBeforeSaveSleepTimeSeconds, IG.Num.SimJMatProFileManagerBase.JMatCompletionDetectionFilePath, IG.Num.SimJMatProFileManagerBase.JMatCompletionDetectionSize, IG.Num.SimJMatProFileManagerBase.JMatCompletionDetectionSleepTimeSeconds, IG.Num.SimJMatProFileManagerBase.JMatTimeoutWaitCalculationSeconds, IG.Num.SimJMatProFileManagerBase.Lock, IG.Lib.Util.SleepSeconds(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.StopWatch1.Time, and IG.Lib.StopWatch1.TotalTime.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties().
JMatWaitResultsSaved()
virtual bool IG.Num.SimJMatProFileManagerBase.JMatWaitResultsSaved () inline virtual
Waits until JMatPro results are saved.
Returns true if it could be detected properly that results were saved, false otherwise (i.e. timeout occurred).
Timeout is defined by the JMatTimeoutWaitResultsSavedSeconds property.
References IG.Num.SimJMatProFileManagerBase.JMatBeforeResultsSavedSleepTimeSeconds, IG.Num.SimJMatProFileManagerBase.JMatResultsFilePath, IG.Num.SimJMatProFileManagerBase.JMatResultsSavedDetectionSize, IG.Num.SimJMatProFileManagerBase.JMatTimeoutWaitResultsSavedSeconds, IG.Num.SimJMatProFileManagerBase.Lock, IG.Lib.Util.SleepSeconds(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.StopWatch1.Time, and IG.Lib.StopWatch1.TotalTime.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties().
PrepareDataDefinitionsFromSuperset()
void IG.Num.SimJMatProFileManagerBase.PrepareDataDefinitionsFromSuperset () inline
Prepares data definitions from the superset data definition file.
Definitions for material parameters and for joint process and material parameters are prepared and saved to the corresponding files.
References IG.Num.InputOutputDataDefiniton.AddInputElement(), IG.Num.InputOutputDataDefiniton.AddOutputElement(), IG.Num.SimJMatProFileManagerBase.DataDefinitionJMatFilePath, IG.Num.SimJMatProFileManagerBase.DataDefinitionJMatFilePathNoNitrogen, IG.Num.SimJMatProFileManagerBase.DataDefinitionJointFilePath, IG.Num.SimJMatProFileManagerBase.DataDefinitionJointFilePathNoNitrogen, IG.Num.SimJMatProFileManagerBase.DataDefinitionProcess, IG.Num.SimJMatProFileManagerBase.DataDefinitionSuperset, IG.Num.SimJMatProFileManagerBase.GetCompositionElementSymbol(), IG.Num.InputElementDefinition.GetCopy(), IG.Num.OutputElementDefinition.GetCopy(), IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.InputOutputDataDefiniton.GetInputIndex(), IG.Num.SimJMatProFileManagerBase.GetNumCompositionElements(), IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.SimJMatProFileManagerBase.LogFileWriter, IG.Lib.SimJMatProConst.NitrogenSymbol, IG.Num.InputOutputDataDefiniton.OutputLength, IG.Num.SimJMatProFileManagerBase.OutputLevel, and IG.Num.InputOutputDataDefiniton.SaveJson().
Referenced by IG.Script.S_12_09_jmatpro.CommandPrepareData().
PrapareDefaultMaterialParameters()
void IG.Num.SimJMatProFileManagerBase.PrapareDefaultMaterialParameters () inline
Calculates default material parameters as the middle point of allowed intervals, and saves the parameters.
Data is saved in two ways: simply as vector (path defined by WorkingMaterialParametersPath, default file name SimJMatProConst.MaterialParametersFilename) and as default values in data definition object (path defined by WorkingMaterialParametersDefPath, default file name SimJMatProConst.MaterialParametersDefFilename)
References IG.Num.InputOutputDataDefiniton.AddInputElement(), IG.Num.SimJMatProFileManagerBase.DataDefinitionJMat, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.SimJMatProFileManagerBase.GetMaterialParametersDefault(), IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.SimJMatProFileManagerBase.LogFileWriter, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, IG.Num.InputOutputElementDefinition.Name, IG.Num.InputOutputDataDefiniton.SaveJson(), IG.Num.VectorBase.SaveJson(), IG.Num.SimJMatProFileManagerBase.WorkingMaterialParametersDefPath, and IG.Num.SimJMatProFileManagerBase.WorkingMaterialParametersPath.
Referenced by IG.Script.S_12_09_jmatpro.CommandPrepareData().
PrepareSettingsTemplate()
void IG.Num.SimJMatProFileManagerBase.PrepareSettingsTemplate () inline
Saves the current settings to a file used as template for settings file for JMatPro interface' file manager.
Settings are stored to file in the working directory named SimJMatProConst.SettingsTemplateFilename
References IG.Num.SimJMatProFileManagerBase.SaveSettings(), IG.Lib.SimJMatProConst.SettingsTemplateFilename, and IG.Num.SimJMatProFileManagerBase.WorkingDirectory.
Referenced by IG.Script.S_12_09_jmatpro.CommandPrepareData().
GetMaterialDirectoryPath() [1/2]
string IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoryPath (string specifiedMaterialDirectoryPath) inline
Returns a valid (existent) material data directory path that is obtaines form the specified path, or throws exception if such a directory could not be obtained.
The specified material directory path can be specified as absolute path or relative to material data root (i.e. just directory name) or relative to working directory.
Parameters
specifiedMaterialDirectoryPath The specified APPROXIMATE path of the material data directory. It can be specified as absolute path or relative to material data root (i.e. just directory name) or relative to working directory.
Exceptions
ArgumentException Thrown when the specified approximate path is a null or empty string or when it dese not represent an existing material data directory (not even relative to the working directory or material data root).
Returns
Valid path to the material data directory that is inferred from the specified approximate path. If such a path could not be obtained then exception is thrown.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateSimulatedResponse(), IG.Num.SimJMatProFileManagerBase.ClearBusyFlag(), IG.Script.S_12_09_jmatpro.CommandTestMaterialResults(), IG.Script.S_12_09_jmatpro.CommandTestRestart(), IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.CreateMaterialdirectoryInfo(), IG.Num.SimJMatProFileManagerBase.MaterialDirectoryInfoBase.MaterialDirectoryInfoBase(), and IG.Num.SimJMatProFileManagerBase.RetryCalculateMaterialProperties().
GetMaterialDirectoryPath() [2/2]
virtual string IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoryPath (string specifiedMaterialDirectoryPath, bool throwExceptions) inline virtual
Returns a valid (existent) material data directory path that is obtaines form the specified path, or null if such a directory could not be obtained (or, if throwExceptions is true, exception is thrown in this case).
The specified material directory path can be specified as absolute path or relative to material data root (i.e. just directory name) or relative to working directory.
Parameters
specifiedMaterialDirectoryPath The specified APPROXIMATE path of the material data directory. It can be specified as absolute path or relative to material data root (i.e. just directory name) or relative to working directory.
throwExceptions Flag indicating whether exception is thrown if a valid directory coud not be obtained from the specified directory path or name. If false then null is returned when the valid (i.e. existent) directory path can not be extracted from the specified path.
Exceptions
ArgumentException Thrown when the specified approximate path is a null or empty string or when it dese not represent an existing material data directory (not even relative to the working directory or material data root), but only when the throwExceptions parameter is true.
Returns
Valid path to the material data directory that is inferred from the specified approximate path, of null if such a path could not be obtained.
References IG.Num.SimJMatProFileManagerBase.RootDataDirectoryPath, and IG.Num.SimJMatProFileManagerBase.WorkingDirectory.
IsMaterialDirectory()
bool IG.Num.SimJMatProFileManagerBase.IsMaterialDirectory (DirectoryInfo dir) inline protected
Returns a flag indicating whether teh specified directory is considered a material directory or not. This method is usually used to extract all material directoried from the root data directory (which may for some reason contain other directories, too).
Parameters
dir Directory info for the directory that is checked. If null then false is returned (no exception thrown).
Returns
True if the specified directory is considered a material data directory, false if not.
References IG.Lib.SimJMatProConst.DataDirectoryPrefix.
Referenced by IG.Num.SimJMatProFileManagerBase.GetMaterialDirectories(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereBusySet(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereCalculationFailed(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereMaterialCalculated(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereMaterialDataCorrupted(), and IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereTimedout().
IsMaterialCalculated()
bool IG.Num.SimJMatProFileManagerBase.IsMaterialCalculated (string materialDirectoryPath) inline protected
For the specified material data directory, returns a flag that indicates whether material properties have been calculated for the corresponding material or not. This is obtained by checking the corresponding message file as well as existence and size of the material results file.
Performed in colision safe way by using a mutex.
Parameters
materialDirectoryPath Path to the material data directory that is checked. It must be a valid path to existent directory.
References IG.Num.SimJMatProFileManagerBase._msgMaterialCalculationFinishedFilename, IG.Num.SimJMatProFileManagerBase.JMatResultsMinimalSize, IG.Num.SimJMatProFileManagerBase.LockFileMutex, and IG.Num.SimJMatProFileManagerBase.MaterialResultsFilename.
Referenced by IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereCalculationFailed(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereMaterialCalculated(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageCalculationFailed(), and IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageMaterialCalculated().
IsTimedoutFlagSet()
bool IG.Num.SimJMatProFileManagerBase.IsTimedoutFlagSet (string materialDirectoryPath) inline protected
For the specified material data directory, returns a flag that indicates whether material calculation has not finished because of timeout. This is obtained by checking the corresponding message file.
Performed in colision safe way by using a mutex.
Parameters
materialDirectoryPath Path to the material data directory that is checked. It must be a valid path to existent directory.
References IG.Num.SimJMatProFileManagerBase._msgMaterialCalculationTimedoutFilename, and IG.Num.SimJMatProFileManagerBase.LockFileMutex.
Referenced by IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereTimedout(), and IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageTimedout().
IsMaterialResultsWrongFlagSet()
bool IG.Num.SimJMatProFileManagerBase.IsMaterialResultsWrongFlagSet (string materialDirectoryPath) inline protected
For the specified material data directory, returns a flag that indicates whether material result file contents are incorrect. This is obtained by checking the corresponding message file.
Performed in colision safe way by using a mutex.
Parameters
materialDirectoryPath Path to the material data directory that is checked. It must be a valid path to existent directory.
References IG.Num.SimJMatProFileManagerBase._msgMaterialResultsWrongFilename, and IG.Num.SimJMatProFileManagerBase.LockFileMutex.
ClearMaterialResultsWrongFlag()
virtual void IG.Num.SimJMatProFileManagerBase.ClearMaterialResultsWrongFlag (string materialDirectoryPath) inline virtual
Clears the flag indicating that material result file is incorrect.
Parameters
materialDirectoryPath Path to the material data directory that is checked. It must be a valid path to existent directory.
References IG.Num.SimJMatProFileManagerBase._msgMaterialResultsWrongFilename, and IG.Num.SimJMatProFileManagerBase.LockFileMutex.
SetMaterialResultsWrongFlag()
virtual void IG.Num.SimJMatProFileManagerBase.SetMaterialResultsWrongFlag (string materialDirectoryPath, string dataErrorDescriptions) inline virtual
Sets the flag indicating that material result file is incorrect.
Parameters
dataErrorDescriptions String containing detected errors in the result file.
materialDirectoryPath Path to the material data directory that is checked. It must be a valid path to existent directory.
References IG.Num.SimJMatProFileManagerBase._msgMaterialResultsWrongFilename, IG.Num.SimJMatProFileManagerBase.ClearMaterialCalculationFinishedFlag(), and IG.Num.SimJMatProFileManagerBase.LockFileMutex.
Referenced by IG.Script.S_12_09_jmatpro.CommandTestMaterialResults().
IsBusyFlagSet()
bool IG.Num.SimJMatProFileManagerBase.IsBusyFlagSet (string materialDirectoryPath) inline protected
For the specified material data directory, returns a flag that indicates whether the busy flag is set.
Performed in colision safe way by using a mutex.
Parameters
materialDirectoryPath Path to the material data directory that is checked. It must be a valid path to existent directory.
References IG.Num.SimJMatProFileManagerBase._msgMaterialCalculationBusyFilename, and IG.Num.SimJMatProFileManagerBase.LockFileMutex.
Referenced by IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereBusySet(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereCalculationFailed(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereMaterialCalculated(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectory(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageBusyFlagSet(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageCalculationFailed(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageDataCorrupted(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageMaterialCalculated(), and IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageTimedout().
ClearBusyFlag()
bool IG.Num.SimJMatProFileManagerBase.ClearBusyFlag (string materialDirectoryPath) inline
Clears the busy flag from the specified material directory, and returns a flag indicating whether clearing of a flag has actually occurred.
Parameters
materialDirectoryPath Path to the directory in which busy flag is cleared.
It can be specified as absolute path or relative to mat. data root (i.e. just dir. name) or relative to working directory.
Returns
True if parameters flag was actually cleared, false otherwise (e.g. flag was not set at all, or it could not be cleared for some reason).
References IG.Num.SimJMatProFileManagerBase._msgMaterialCalculationBusyFilename, IG.Num.SimJMatProFileManagerBase._msgMaterialCalculationFinishedFilename, IG.Num.SimJMatProFileManagerBase._msgMaterialCalculationTimedoutFilename, IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoryPath(), IG.Num.SimJMatProFileManagerBase.LockFileMutex, and IG.Num.SimJMatProFileManagerBase.LogFileWriter.
Referenced by IG.Num.SimJMatProFileManagerBase.ClearBusyFlags(), IG.Script.S_12_09_jmatpro.CommandClearBusyFlags(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageBusyFlagSet(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageCalculationFailed(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageDataCorrupted(), and IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageTimedout().
ClearMaterialCalculationFinishedFlag()
virtual void IG.Num.SimJMatProFileManagerBase.ClearMaterialCalculationFinishedFlag (string materialDirectoryPath) inline virtual
Clears the flag indicating that material calculation is successfully finished, from the specified directory.
Parameters
materialDirectoryPath Path to the material data directory where flag is cleared. It must be a valid path to existent directory.
References IG.Num.SimJMatProFileManagerBase._msgMaterialCalculationFinishedFilename, and IG.Num.SimJMatProFileManagerBase.LockFileMutex.
Referenced by IG.Num.SimJMatProFileManagerBase.SetMaterialResultsWrongFlag().
GetMaterialParameters()
bool IG.Num.SimJMatProFileManagerBase.GetMaterialParameters (string materialDirectoryPath, ref IVector parameters) inline
Gets (reads) material parameters from the specified material data directory.
Parameters
materialDirectoryPath Path to the material data directory where parameters are read from. It must be a valid path of an existent material data directory.
parameters Vector where the obtained material parameters are stored.
Returns
True if parameters were successfully obtained, false otherwise.
References IG.Num.VectorBase.LoadJson(), IG.Num.SimJMatProFileManagerBase.LockFileMutex, and IG.Num.SimJMatProFileManagerBase.MaterialParametersFilename.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateSimulatedResponse(), IG.Script.S_12_09_jmatpro.CommandTestRestart(), IG.Num.SimJMatProFileManagerBase.IsMaterialDirectoryCorrupted(), and IG.Num.SimJMatProFileManagerBase.RetryCalculateMaterialProperties().
IsMaterialDirectoryCorrupted()
bool IG.Num.SimJMatProFileManagerBase.IsMaterialDirectoryCorrupted (string materialDirectoryPath) inline
Returns a flag indicated whether the specified material data directory is corrupted in the sense that some material data in it is corrupted (i.e. the vector of material parameters is not properly written).
Parameters
materialDirectoryPath Path to the material data directory whose integrity is checked. It must be a valid path of an existent material data directory.
Returns
True if the directory is corrupted, false otherwise.
References IG.Num.SimJMatProFileManagerBase._msgMaterialCalculationBusyFilename, IG.Num.SimJMatProFileManagerBase.GetMaterialParameters(), and IG.Num.SimJMatProFileManagerBase.LockFileMutex.
Referenced by IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereMaterialDataCorrupted(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageDataCorrupted(), and IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageMaterialCalculated().
GetMaterialDirectories()
void IG.Num.SimJMatProFileManagerBase.GetMaterialDirectories (ref List< DirectoryInfo > directories) inline
Obtains a list of paths of all material directories, and stores them on the specified list.
Parameters
directories List where directory infos are stored. Reallocated and cleared if necessary.
References IG.Num.SimJMatProFileManagerBase.IsMaterialDirectory(), and IG.Num.SimJMatProFileManagerBase.RootDataDirectoryPath.
Referenced by IG.Num.SimJMatProFileManagerBase.WriteMaterialCalculationStatistics().
GetMaterialDirectoriesWhereCalculationFailed()
void IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereCalculationFailed (ref List< DirectoryInfo > directories) inline
Obtains a list of paths of all material directories where material properties calculation has failed. These are characterized as material directories where the busy flag is not set but material data is also not available (which means that material results file does not exist or is too small or the message file for the material calculation finished message does not exist).
Parameters
directories List where directory infos are stored. Reallocated and cleared if necessary.
References IG.Num.SimJMatProFileManagerBase.IsBusyFlagSet(), IG.Num.SimJMatProFileManagerBase.IsMaterialCalculated(), IG.Num.SimJMatProFileManagerBase.IsMaterialDirectory(), and IG.Num.SimJMatProFileManagerBase.RootDataDirectoryPath.
Referenced by IG.Script.S_12_09_jmatpro.CommandTestRestart(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageCalculationFailed(), IG.Num.SimJMatProFileManagerBase.RetryCalculateMaterialProperties(), and IG.Num.SimJMatProFileManagerBase.WriteMaterialCalculationStatistics().
GetMaterialDirectoriesWhereBusySet()
void IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereBusySet (ref List< DirectoryInfo > directories) inline
Obtains a list of paths of all material directories where the busy flag is set (which may be a consequence of some failure).
Parameters
directories List where directory infos are stored. Reallocated and cleared if necessary.
References IG.Num.SimJMatProFileManagerBase.IsBusyFlagSet(), IG.Num.SimJMatProFileManagerBase.IsMaterialDirectory(), and IG.Num.SimJMatProFileManagerBase.RootDataDirectoryPath.
Referenced by IG.Num.SimJMatProFileManagerBase.ClearBusyFlags(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageBusyFlagSet(), and IG.Num.SimJMatProFileManagerBase.WriteMaterialCalculationStatistics().
GetMaterialDirectoriesWhereTimedout()
void IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereTimedout (ref List< DirectoryInfo > directories) inline
Obtains a list of all material directories where material calculation has timed out.
Parameters
directories List where directory infos are stored. Reallocated and cleared if necessary.
References IG.Num.SimJMatProFileManagerBase.IsMaterialDirectory(), IG.Num.SimJMatProFileManagerBase.IsTimedoutFlagSet(), and IG.Num.SimJMatProFileManagerBase.RootDataDirectoryPath.
Referenced by IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageTimedout(), and IG.Num.SimJMatProFileManagerBase.WriteMaterialCalculationStatistics().
GetMaterialDirectoriesWhereMaterialCalculated()
void IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereMaterialCalculated (ref List< DirectoryInfo > directories) inline
Obtains a list of paths of all material directories where material properties were successfully calculated. These are characterized as material directories where the busy flag is not set but material data is also available (which means that material results file exists and is large enough and the message file for the material calculation finished message exists).
Parameters
directories List where directory infos are stored. Reallocated and cleared if necessary.
References IG.Num.SimJMatProFileManagerBase.IsBusyFlagSet(), IG.Num.SimJMatProFileManagerBase.IsMaterialCalculated(), IG.Num.SimJMatProFileManagerBase.IsMaterialDirectory(), and IG.Num.SimJMatProFileManagerBase.RootDataDirectoryPath.
Referenced by IG.Script.S_12_09_jmatpro.CommandTestMaterialResults(), IG.Script.S_12_09_jmatpro.CommandTestRestart(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageMaterialCalculated(), IG.Num.SimJMatProFileManagerBase.SimulationInfoBase.UpdateMaterialDirectories(), IG.Num.SimJMatProFileManagerBase.WriteMaterialCalculationStatistics(), and IG.Num.SimJMatProFileManagerBase.WriteMaterialDirectoriesWhereMaterialCalculated().
GetMaterialDirectoriesWhereMaterialDataCorrupted()
void IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereMaterialDataCorrupted (ref List< DirectoryInfo > directories) inline
Obtains a list of paths of all material directories where material data is corrupted. The method IsMaterialDirectoryCorrupted is used to test material directories for corruption.
Parameters
directories List where directory infos are stored. Reallocated and cleared if necessary.
References IG.Num.SimJMatProFileManagerBase.IsMaterialDirectory(), IG.Num.SimJMatProFileManagerBase.IsMaterialDirectoryCorrupted(), and IG.Num.SimJMatProFileManagerBase.RootDataDirectoryPath.
Referenced by IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageDataCorrupted(), and IG.Num.SimJMatProFileManagerBase.WriteMaterialCalculationStatistics().
WriteMaterialCalculationStatistics()
int IG.Num.SimJMatProFileManagerBase.WriteMaterialCalculationStatistics (bool printIndividualDirectories, bool includeCorrupted) inline
Prints statistics of material properties calculation.
Parameters
printIndividualDirectories Whether individual directories are printed (if false then only number of directories in each group is printed).
includeCorrupted If true then a list of corrupted directories is also printed. Detection of corrupted directories takes considerably longer than detection of other groups.
Returns
Number of successfully calculated materials.
References IG.Num.SimJMatProFileManagerBase.GetMaterialDirectories(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereBusySet(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereCalculationFailed(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereMaterialCalculated(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereMaterialDataCorrupted(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereTimedout(), and IG.Num.SimJMatProFileManagerBase.LogFileWriter.
Referenced by IG.Script.S_12_09_jmatpro.CommandWriteMaterialStatistics().
WriteMaterialDirectoriesWhereMaterialCalculated()
int IG.Num.SimJMatProFileManagerBase.WriteMaterialDirectoriesWhereMaterialCalculated () inline
Prints (to console and log file) information about material directories where material properties were successfully calculated.
Returns
Number of directories where material properties were successfully calculated.
References IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereMaterialCalculated(), IG.Num.SimJMatProFileManagerBase.JMatResultsGoodSize, IG.Num.SimJMatProFileManagerBase.JMatResultsMinimalSize, IG.Num.SimJMatProFileManagerBase.LogFileWriter, and IG.Num.SimJMatProFileManagerBase.MaterialResultsFilename.
Referenced by IG.Script.S_12_09_jmatpro.CommandWriteMaterialsCalculated().
ReleaseAbandonedMutex()
bool IG.Num.SimJMatProFileManagerBase.ReleaseAbandonedMutex () inline
Releases the mutex in the case it has been abandoned, and returns a flag indicating whether the mutex has actually been abandoned. Has no effect if mutex is not abandoned.
References IG.Num.SimJMatProFileManagerBase.LockFileMutex, and IG.Num.SimJMatProFileManagerBase.LogFileWriter.
Referenced by IG.Script.S_12_09_jmatpro.CommandReleaseAbandonedMutex().
ClearBusyFlags()
void IG.Num.SimJMatProFileManagerBase.ClearBusyFlags () inline
Clears the busy flag in all directories where it is still set (possibly because some procedure has hanged).
References IG.Num.SimJMatProFileManagerBase.ClearBusyFlag(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereBusySet(), IG.Num.SimJMatProFileManagerBase.LogFileWriter, and IG.Lib.UtilConsole.Read().
Referenced by IG.Script.S_12_09_jmatpro.CommandClearBusyFlags().
RetryCalculateMaterialProperties() [1/3]
void IG.Num.SimJMatProFileManagerBase.RetryCalculateMaterialProperties (string materialDirectoryPath) inline
Retries calculation of
Parameters
materialDirectoryPath Path to the directory in which busy flag is cleared.
Can be specified as absolute path or relative to mat. data root (i.e. just dir. name) or relative to working directory.
References IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsReset(), and IG.Num.SimJMatProFileManagerBase.RetryCalculateMaterialProperties().
Referenced by IG.Script.S_12_09_jmatpro.CommandRetryCalculateMaterialProperties().
RetryCalculateMaterialProperties() [2/3]
void IG.Num.SimJMatProFileManagerBase.RetryCalculateMaterialProperties (string materialDirectoryPath, int whichCalculation, int numCalculations) inline
Retries calculation of
Parameters
materialDirectoryPath Path to the directory in which busy flag is cleared.
Can be specified as absolute path or relative to mat. data root (i.e. just dir. name) or relative to working directory.
Parameters
whichCalculation Specifies which calculation in row is this (used just for output).
numCalculations Specifies how many are all calculations that are performed in a row (used just for output).
References IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoryName(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoryPath(), IG.Num.SimJMatProFileManagerBase.GetMaterialParameters(), IG.Num.SimJMatProFileManagerBase.LogFileWriter, and IG.Num.SimJMatProFileManagerBase.MaterialCalculationsStatisticsPrint().
RetryCalculateMaterialProperties() [3/3]
int IG.Num.SimJMatProFileManagerBase.RetryCalculateMaterialProperties () inline
Retries calculation of material properties in the directories where calculation obviously failed.
Returns
Number of directories where calculation was retried.
References IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereCalculationFailed(), IG.Num.SimJMatProFileManagerBase.LogFileWriter, and IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsReset().
Referenced by IG.Num.SimJMatProFileManagerBase.RetryCalculateMaterialProperties().
KillJMatPro()
void IG.Num.SimJMatProFileManagerBase.KillJMatPro () inline
Kills the JMatPro process.
References IG.Lib.UtilSystem.KillAllProcesses(), IG.Num.SimJMatProFileManagerBase.ProcessNameSubstringJava, IG.Num.SimJMatProFileManagerBase.ProcessNameSubstringJMatMain, and IG.Num.SimJMatProFileManagerBase.ProcessNameSubstringJMatSolver.
Referenced by IG.Script.S_12_09_jmatpro.CommandKillJmat(), and IG.Num.SimJMatProFileManagerBase.JMatLaunch().
IsJMatProRunning()
bool IG.Num.SimJMatProFileManagerBase.IsJMatProRunning () inline
Returns a flag indicating whether the JMatPro application is currently running.
References IG.Lib.UtilSystem.IsProcessRunning(), IG.Num.SimJMatProFileManagerBase.ProcessNameSubstringJava, and IG.Num.SimJMatProFileManagerBase.ProcessNameSubstringJMatMain.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Script.S_12_09_jmatpro.CommandIsJmatRunning(), IG.Script.S_12_09_jmatpro.CommandKillJmat(), and IG.Num.SimJMatProFileManagerBase.JMatLaunch().
IsMaterialDataDirectoryPrepared()
bool IG.Num.SimJMatProFileManagerBase.IsMaterialDataDirectoryPrepared () inline
Whether material data is prepared.
References IG.Num.SimJMatProFileManagerBase.MaterialDataDirectoryPath, and IG.Num.SimJMatProFileManagerBase.MaterialParameters.
CalculateMaterialPropertiesRandomSet()
void IG.Num.SimJMatProFileManagerBase.CalculateMaterialPropertiesRandomSet (int numParameterSets) inline
Calculates material properties by JMatPro for a set of random parameters.
Parameters
numParameterSets Number of parameters in the set.
References IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Num.SimJMatProFileManagerBase.GetRandomMaterialParameters(), IG.Num.SimJMatProFileManagerBase.LogFileWriter, IG.Num.SimJMatProFileManagerBase.MaterialCalculationsStatisticsPrint(), and IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsReset().
Referenced by IG.Script.S_12_09_jmatpro.CommandCalculateMaterialsRandom().
CalculateMaterialProperties() [1/3]
void IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties (string parametersPath) inline
Calculates material properties at parameters that are read from a file.
Parameters
parametersPath Path to the file containing material parameters.
Parameters must be written in a file as vector in JSON format.
Path can be relative to the current directory or working directory, or it can be absolute path. If null or empty string then default path is taken.
References IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Num.VectorBase.LoadJson(), IG.Lib.UtilSystem.StandardizeDirectoryPath(), IG.Num.SimJMatProFileManagerBase.WorkingDirectory, and IG.Num.SimJMatProFileManagerBase.WorkingMaterialParametersPath.
Referenced by IG.Script.S_12_09_jmatpro.CommandCalculateMaterial().
CalculateMaterialPropertiesDef()
void IG.Num.SimJMatProFileManagerBase.CalculateMaterialPropertiesDef (string parametersPath) inline
Calculates material properties at parameters that are read from a data definition file as default values.
Parameters
parametersPath Path to the file containing material parameters in form of data definition (default values are taken).
Parameters must be written in a file as definition data in JSON format.
Path can be relative to the current directory or working directory, or it can be absolute path. If null or empty string then default path is taken.
References IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Num.InputOutputDataDefiniton.LoadJson(), IG.Lib.UtilSystem.StandardizeDirectoryPath(), IG.Num.SimJMatProFileManagerBase.WorkingDirectory, and IG.Num.SimJMatProFileManagerBase.WorkingMaterialParametersDefPath.
Referenced by IG.Script.S_12_09_jmatpro.CommandCalculateMaterialDef().
CalculateMaterialProperties() [2/3]
void IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties (IVector parameters) inline
Calculates the material properties at the specified vector of material parameters, and stores results to the appropriate directory.
Vector of current parameters is permanently set to parameters .
Parameters
parameters Vector containing material parameters (related to chemical composition) for which material properties must be calculated.
References IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Num.SimJMatProFileManagerBase.Lock, and IG.Num.SimJMatProFileManagerBase.MaterialParameters.
CalculateMaterialProperties() [3/3]
void IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties () inline
Calculates the material properties at the current vector of material parameters, and stores results to the appropriate directory.
References IG.Num.SimJMatProFileManagerBase.ClearMaterialCalculationBusy(), IG.Num.SimJMatProFileManagerBase.ClearMaterialCalculationFinished(), IG.Num.SimJMatProFileManagerBase.ClearMaterialCalculationTimedout(), IG.Num.SimJMatProFileManagerBase.ClearMaterialResultsWrong(), IG.Num.SimJMatProFileManagerBase.CreateMaterialDataDirectory(), IG.Num.SimJMatProFileManagerBase.JMatResultInfo.DataErrorDescriptions, IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoryName(), IG.Num.SimJMatProFileManagerBase.JMatResultInfo.IsDataCorrect, IG.Num.SimJMatProFileManagerBase.JMatResultInfo.IsFractionUnitCorrect, IG.Num.SimJMatProFileManagerBase.IsJMatProRunning(), IG.Num.SimJMatProFileManagerBase.JMatResultInfo.IsTemperatureUnitCorrect, IG.Num.SimJMatProFileManagerBase.JMatResultInfo.IsTemperatureUnitKelvin, IG.Num.SimJMatProFileManagerBase.JMatChangeFractionUnit(), IG.Num.SimJMatProFileManagerBase.JMatChangeTemperatureUnit(), IG.Num.SimJMatProFileManagerBase.JMatClose(), IG.Num.SimJMatProFileManagerBase.JMatCompletionDetectionFilePath, IG.Num.SimJMatProFileManagerBase.JMatCompositionFilePath, IG.Num.SimJMatProFileManagerBase.JMatLaunch(), IG.Num.SimJMatProFileManagerBase.JMatResultsFilePath, IG.Num.SimJMatProFileManagerBase.JMatSaveResults(), IG.Num.SimJMatProFileManagerBase.JMatStartCalculation(), IG.Num.SimJMatProFileManagerBase.JMatTimeoutWaitCalculationSeconds, IG.Num.SimJMatProFileManagerBase.JMatTimeoutWaitResultsSavedSeconds, IG.Num.SimJMatProFileManagerBase.JMatWaitCalculation(), IG.Num.SimJMatProFileManagerBase.JMatWaitResultsSaved(), IG.Num.SimJMatProFileManagerBase.Lock, IG.Num.SimJMatProFileManagerBase.LogFileWriter, IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsStart(), IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsStop(), IG.Num.SimJMatProFileManagerBase.MaterialCompositionPath, IG.Num.SimJMatProFileManagerBase.MaterialParameters, IG.Num.SimJMatProFileManagerBase.MaterialParametersPath, IG.Num.SimJMatProFileManagerBase.MaterialResultsPath, IG.Num.SimJMatProFileManagerBase.PrepareJMatInput(), IG.Num.VectorBase.SaveJson(), IG.Num.SimJMatProFileManagerBase.SetMaterialCalculationBusy(), IG.Num.SimJMatProFileManagerBase.SetMaterialCalculationFinished(), IG.Num.SimJMatProFileManagerBase.SetMaterialCalculationTimedout(), IG.Num.SimJMatProFileManagerBase.SetMaterialResultsWrong(), IG.Lib.Util.SleepSeconds(), IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.StopWatch1.Time, IG.Num.IVector< T >.ToString(), IG.Num.SimJMatProFileManagerBase.JMatResultInfo.ToString(), and IG.Lib.StopWatch1.TotalTime.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Num.SimJMatProFileManagerBase.CalculateMaterialPropertiesDef(), IG.Num.SimJMatProFileManagerBase.CalculateMaterialPropertiesRandomSet(), and IG.Num.SimJMatProFileManagerBase.RetryCalculateMaterialProperties().
MaterialCalculationsStatisticsPrint()
void IG.Num.SimJMatProFileManagerBase.MaterialCalculationsStatisticsPrint (string introductionString) inline
Prints calculation statistics after another material calculation is finished.
Parameters
introductionString String that introduces the calculation for which statistics is printed, without any spaces or punctation marks at the end (these are added by the method).
References IG.Lib.StopWatch1.GetTimeSpan(), IG.Num.SimJMatProFileManagerBase.LogFileWriter, IG.Num.SimJMatProFileManagerBase.LongestMaterialCalculationTime, IG.Num.SimJMatProFileManagerBase.MaterialCalculationTime, IG.Num.SimJMatProFileManagerBase.MaterialCalculationTimer, IG.Num.SimJMatProFileManagerBase.NumMaterialCalculationsIntended, IG.Num.SimJMatProFileManagerBase.NumMaterialCalculationsPerformed, IG.Num.SimJMatProFileManagerBase.NumMaterialCalculationsSuccessful, IG.Num.SimJMatProFileManagerBase.NumMaterialCalculationsTimedout, IG.Lib.StopWatch1.TotalTime, and IG.Lib.StopWatch1.TotalTimeSpan.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialPropertiesRandomSet(), and IG.Num.SimJMatProFileManagerBase.RetryCalculateMaterialProperties().
MaterialCalculationStatisticsReset()
void IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsReset (int numIntendedCalculations) inline
Resets material calculation statistics counters.
References IG.Num.SimJMatProFileManagerBase.Lock, IG.Num.SimJMatProFileManagerBase.LongestMaterialCalculationTime, IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatus, IG.Num.SimJMatProFileManagerBase.MaterialCalculationTime, IG.Num.SimJMatProFileManagerBase.MaterialCalculationTimer, IG.Num.SimJMatProFileManagerBase.NumconsecutiveMaterialCalculationsUnsuccessful, IG.Num.SimJMatProFileManagerBase.NumconsecutiveMaterialCalculationTimedout, IG.Num.SimJMatProFileManagerBase.NumMaterialCalculationsIntended, IG.Num.SimJMatProFileManagerBase.NumMaterialCalculationsPerformed, IG.Num.SimJMatProFileManagerBase.NumMaterialCalculationsSuccessful, IG.Num.SimJMatProFileManagerBase.NumMaterialCalculationsTimedout, IG.Num.SimJMatProFileManagerBase.NumMaterialCalculationsUnsuccessful, and IG.Lib.StopWatch1.Reset().
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialPropertiesRandomSet(), and IG.Num.SimJMatProFileManagerBase.RetryCalculateMaterialProperties().
MaterialCalculationStatisticsStart()
void IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsStart () inline
Updates material calculaiton statistics counters at the beginning of a new material calculation.
References IG.Lib.StopWatch1.IsRunning, IG.Num.SimJMatProFileManagerBase.Lock, IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatus, IG.Num.SimJMatProFileManagerBase.MaterialCalculationTime, IG.Num.SimJMatProFileManagerBase.MaterialCalculationTimer, IG.Lib.StopWatch1.Start(), and IG.Lib.StopWatch1.Stop().
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties().
MaterialCalculationStatisticsStop()
void IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsStop (CalculationStatus status) inline
Updates material calculation statistics counters after completion of a single calculation.
Parameters
status Status with which calculation has completed.
References IG.Lib.StopWatch1.IsRunning, IG.Num.SimJMatProFileManagerBase.Lock, IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatus, IG.Num.SimJMatProFileManagerBase.MaterialCalculationTime, IG.Num.SimJMatProFileManagerBase.MaterialCalculationTimer, IG.Num.SimJMatProFileManagerBase.NumconsecutiveMaterialCalculationsSuccessful, IG.Num.SimJMatProFileManagerBase.NumconsecutiveMaterialCalculationsUnsuccessful, IG.Num.SimJMatProFileManagerBase.NumconsecutiveMaterialCalculationTimedout, IG.Num.SimJMatProFileManagerBase.NumMaterialCalculationsPerformed, IG.Num.SimJMatProFileManagerBase.NumMaterialCalculationsSuccessful, IG.Num.SimJMatProFileManagerBase.NumMaterialCalculationsTimedout, IG.Num.SimJMatProFileManagerBase.NumMaterialCalculationsUnsuccessful, IG.Lib.StopWatch1.Stop(), and IG.Lib.StopWatch1.Time.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties().
GetMaterialParametersDefault()
virtual void IG.Num.SimJMatProFileManagerBase.GetMaterialParametersDefault (ref IG.Num.IVector parameters) inline virtual
Returns vector containing default values for material parameters.
Parameters
parameters Vector of material parameters.
Material parameters are mass fractions of individual elements involved in composition (excluding iron, whose fraction is not a parameter but is calculated form other fractions).
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Num.SimJMatProFileManagerBase.DataDefinitionJMat, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Num.SimJMatProFileManagerBase.Error(), IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, IG.Num.InputOutputElementDefinition.Name, and IG.Num.VectorBase.Resize().
Referenced by IG.Num.SimJMatProFileManagerBase.PrapareDefaultMaterialParameters().
CalculateJMatInput()
virtual List<JMatProElemetData> IG.Num.SimJMatProFileManagerBase.CalculateJMatInput (IVector materialParameters) inline virtual
Calculates and returns input data for JMatPro from the vector of material parameters.
Parameters
materialParameters Vector of material parameters.
Returns
List of element data that contains elements in the same order as must be specified in JMatPro, and each element contains its
References IG.Num.SimJMatProFileManagerBase._compositionData, IG.Lib.JMatProElemetData.AtomicWeight, IG.Num.SimJMatProFileManagerBase.DataDefinitionJMat, IG.Num.SimJMatProFileManagerBase.FindElementData(), IG.Num.SimJMatProFileManagerBase.GetCompositionElementSymbol(), IG.Lib.JMatProElemetData.Getcopy(), IG.Num.SimJMatProFileManagerBase.GetElementData(), IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.SimJMatProFileManagerBase.GetNumCompositionElements(), IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.SimJMatProFileManagerBase.Lock, IG.Lib.JMatProElemetData.MassFraction, IG.Lib.JMatProElemetData.MoleFraction, IG.Lib.JMatProElemetData.Name, IG.Num.InputOutputElementDefinition.Name, and IG.Num.SimJMatProFileManagerBase.SymbolIron.
Referenced by IG.Num.SimJMatProFileManagerBase.PrepareJMatInput().
PrepareJMatInput()
virtual void IG.Num.SimJMatProFileManagerBase.PrepareJMatInput (IVector materialParameters, string filePath) inline virtual
Prepares input file for JMatPro (composition of steel) according to the specified material parameters.
Parameters
materialParameters Vector of material parameter values.
inputFilePath Path of the file where composition is written.
References IG.Num.SimJMatProFileManagerBase.CalculateJMatInput(), IG.Num.SimJMatProFileManagerBase.Lock, IG.Lib.JMatProElemetData.MassFraction, IG.Num.SimJMatProFileManagerBase.MaterialParameters, IG.Lib.JMatProElemetData.MoleFraction, and IG.Lib.JMatProElemetData.Symbol.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties().
ToString()
override string IG.Num.SimJMatProFileManagerBase.ToString () inline
References IG.Num.SimJMatProFileManagerBase.JMatInstallationPath, IG.Num.SimJMatProFileManagerBase.NameJMatProBase, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordDir, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordExtension, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameSaveResults, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameStartCalculation, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathSaveResults, and IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathStartCalculation.
Referenced by IG.Script.S_12_09_jmatpro.CommandCalculateMaterialsRandom(), IG.Script.S_12_09_jmatpro.CommandClearBusyFlags(), IG.Script.S_12_09_jmatpro.CommandCustom(), IG.Script.S_12_09_jmatpro.CommandIsJmatRunning(), IG.Script.S_12_09_jmatpro.CommandMoveMaterialDirectoriesAll(), IG.Script.S_12_09_jmatpro.CommandMoveMaterialDirectoriesBusyFlagSet(), IG.Script.S_12_09_jmatpro.CommandMoveMaterialDirectoriesCalculationFailed(), IG.Script.S_12_09_jmatpro.CommandMoveMaterialDirectoriesDataCorrupted(), IG.Script.S_12_09_jmatpro.CommandMoveMaterialDirectoriesMaterialCalculated(), IG.Script.S_12_09_jmatpro.CommandMoveMaterialDirectoriesTimedout(), IG.Script.S_12_09_jmatpro.CommandReleaseAbandonedMutex(), IG.Script.S_12_09_jmatpro.CommandRetryCalculateMaterialProperties(), IG.Script.S_12_09_jmatpro.CommandWriteMaterialsCalculated(), and IG.Script.S_12_09_jmatpro.CommandWriteMaterialStatistics().
ReplacePathSeparator()
string IG.Num.SimJMatProFileManagerBase.ReplacePathSeparator (string path) inline protected
Returns a string obtained by replacing the '\' path separator by the more standard '/' in the specified path string, or null if the string is null.
Parameters
path String in which path separators are to be replaces, can be null.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
CopyToSettingsPlain< FmType >()
virtual void IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType > (SimJMatProSettingsDto< FmType > settings) inline virtual
Copies settings from the current JMatPro file manager to the specified settings object.
Template Parameters
FmType Type of file manager that the method operates on.
Parameters
settings Settings object on which current settings are stored.
Type Constraints
FmType : SimJMatProFileManagerBase
References IG.Num.SimJMatProFileManagerBase.DataDefinitionJMatFilename, IG.Num.SimJMatProFileManagerBase.DataDefinitionJMatFilePath, IG.Num.SimJMatProFileManagerBase.DataDefinitionJointFilename, IG.Num.SimJMatProFileManagerBase.DataDefinitionJointFilePath, IG.Num.SimJMatProFileManagerBase.DataDefinitionProcessFilename, IG.Num.SimJMatProFileManagerBase.DataDefinitionProcessFilePath, IG.Num.SimJMatProFileManagerBase.JMatBeforeResultsSavedSleepTimeSeconds, IG.Num.SimJMatProFileManagerBase.JMatBeforeSaveSleepTimeSeconds, IG.Num.SimJMatProFileManagerBase.JMatCompletionDetectionFilename, IG.Num.SimJMatProFileManagerBase.JMatCompletionDetectionFilePath, IG.Num.SimJMatProFileManagerBase.JMatCompletionDetectionSize, IG.Num.SimJMatProFileManagerBase.JMatCompletionDetectionSleepTimeSeconds, IG.Num.SimJMatProFileManagerBase.JMatCompositionFilename, IG.Num.SimJMatProFileManagerBase.JMatCompositionFilePath, IG.Num.SimJMatProFileManagerBase.JMatDataPath, IG.Num.SimJMatProFileManagerBase.JMatExecutableFileName, IG.Num.SimJMatProFileManagerBase.JMatExecutableFilePath, IG.Num.SimJMatProFileManagerBase.JMatInstallationPath, IG.Num.SimJMatProFileManagerBase.JMatResultsFilename, IG.Num.SimJMatProFileManagerBase.JMatResultsFilePath, IG.Num.SimJMatProFileManagerBase.JMatResultsGoodSize, IG.Num.SimJMatProFileManagerBase.JMatResultsMinimalSize, IG.Num.SimJMatProFileManagerBase.JMatResultsSavedDetectionSize, IG.Num.SimJMatProFileManagerBase.JMatTimeoutWaitCalculationSeconds, IG.Num.SimJMatProFileManagerBase.JMatTimeoutWaitResultsSavedSeconds, IG.Num.SimJMatProFileManagerBase.LogFileName, IG.Num.SimJMatProFileManagerBase.LogFilePath, IG.Num.SimJMatProFileManagerBase.MaterialCompositionFilename, IG.Num.SimJMatProFileManagerBase.MaterialCompositionPath, IG.Num.SimJMatProFileManagerBase.MaterialDataDirectoryPath, IG.Num.SimJMatProFileManagerBase.MaterialParametersFilename, IG.Num.SimJMatProFileManagerBase.MaterialParametersPath, IG.Num.SimJMatProFileManagerBase.MaterialResultsFilename, IG.Num.SimJMatProFileManagerBase.MaterialResultsPath, IG.Num.SimJMatProFileManagerBase.NameJMatProBase, IG.Num.SimJMatProFileManagerBase.ReplacePathSeparator(), IG.Num.SimJMatProFileManagerBase.RootDataDirectoryName, IG.Num.SimJMatProFileManagerBase.RootDataDirectoryPath, IG.Num.SimJMatProFileManagerBase.UserInteractionCommand, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordDir, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordExtension, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameChangeFractionUnit, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameChangeTemperatureUnit, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameCloseJMat, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameRepairJMat, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameSaveResults, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameStartCalculation, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameStartJMat, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathChangeFractionUnit, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathChangeTemperatureUnit, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathCloseJMat, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathRepairJMat, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathSaveResults, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathStartCalculation, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathStartJMat, IG.Num.SimJMatProFileManagerBase.WorkingDirectory, and IG.Num.SimJMatProFileManagerBase.WorkingMaterialParametersPath.
CopyFromSettingsPlain< FmType >()
virtual void IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType > (SimJMatProSettingsDto< FmType > settings) inline virtual
Copies settings fom the specified settings object to the current JMatPro file manager.
Template Parameters
FmType Type of file manager on which method operates.
Parameters
settings Settings object for which settigs for the current JMatPro file manager are copied.
Type Constraints
FmType : SimJMatProFileManagerBase
References IG.Num.SimJMatProFileManagerBase.DataDefinitionJMatFilename, IG.Num.SimJMatProFileManagerBase.DataDefinitionJMatFilePath, IG.Num.SimJMatProFileManagerBase.DataDefinitionJointFilename, IG.Num.SimJMatProFileManagerBase.DataDefinitionJointFilePath, IG.Num.SimJMatProFileManagerBase.DataDefinitionProcessFilename, IG.Num.SimJMatProFileManagerBase.DataDefinitionProcessFilePath, IG.Num.SimJMatProFileManagerBase.JMatBeforeResultsSavedSleepTimeSeconds, IG.Num.SimJMatProFileManagerBase.JMatBeforeSaveSleepTimeSeconds, IG.Num.SimJMatProFileManagerBase.JMatCompletionDetectionFilename, IG.Num.SimJMatProFileManagerBase.JMatCompletionDetectionFilePath, IG.Num.SimJMatProFileManagerBase.JMatCompletionDetectionSize, IG.Num.SimJMatProFileManagerBase.JMatCompletionDetectionSleepTimeSeconds, IG.Num.SimJMatProFileManagerBase.JMatCompositionFilename, IG.Num.SimJMatProFileManagerBase.JMatCompositionFilePath, IG.Num.SimJMatProFileManagerBase.JMatDataPath, IG.Num.SimJMatProFileManagerBase.JMatExecutableFileName, IG.Num.SimJMatProFileManagerBase.JMatExecutableFilePath, IG.Num.SimJMatProFileManagerBase.JMatInstallationPath, IG.Num.SimJMatProFileManagerBase.JMatResultsFilename, IG.Num.SimJMatProFileManagerBase.JMatResultsFilePath, IG.Num.SimJMatProFileManagerBase.JMatResultsGoodSize, IG.Num.SimJMatProFileManagerBase.JMatResultsMinimalSize, IG.Num.SimJMatProFileManagerBase.JMatResultsSavedDetectionSize, IG.Num.SimJMatProFileManagerBase.JMatTimeoutWaitCalculationSeconds, IG.Num.SimJMatProFileManagerBase.JMatTimeoutWaitResultsSavedSeconds, IG.Num.SimJMatProFileManagerBase.LogFileName, IG.Num.SimJMatProFileManagerBase.LogFilePath, IG.Num.SimJMatProFileManagerBase.MaterialCompositionFilename, IG.Num.SimJMatProFileManagerBase.MaterialCompositionPath, IG.Num.SimJMatProFileManagerBase.MaterialDataDirectoryPath, IG.Num.SimJMatProFileManagerBase.MaterialParametersFilename, IG.Num.SimJMatProFileManagerBase.MaterialParametersPath, IG.Num.SimJMatProFileManagerBase.MaterialResultsFilename, IG.Num.SimJMatProFileManagerBase.MaterialResultsPath, IG.Num.SimJMatProFileManagerBase.NameJMatProBase, IG.Num.SimJMatProFileManagerBase.RootDataDirectoryName, IG.Num.SimJMatProFileManagerBase.RootDataDirectoryPath, IG.Num.SimJMatProFileManagerBase.UserInteractionCommand, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordDir, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordExtension, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameChangeFractionUnit, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameChangeTemperatureUnit, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameCloseJMat, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameRepairJMat, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameSaveResults, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameStartCalculation, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameStartJMat, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathChangeFractionUnit, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathChangeTemperatureUnit, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathCloseJMat, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathRepairJMat, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathSaveResults, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathStartCalculation, IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathStartJMat, IG.Num.SimJMatProFileManagerBase.WorkingDirectory, and IG.Num.SimJMatProFileManagerBase.WorkingMaterialParametersPath.
SaveSettings() [1/4]
void IG.Num.SimJMatProFileManagerBase.SaveSettings (string filePath) inline
Saves (serializes) the settings of the current JMatPro interface' file manager to the specified JSON file.
If the file already exists, contents overwrite the file.
Parameters
inputFilePath Path to the file in which settings are saved.
Referenced by IG.Script.S_12_09_jmatpro.CommandCustom(), IG.Script.S_12_09_jmatpro.CommandSaveSettings(), IG.Num.SimJMatProFileManagerBase.PrepareSettingsTemplate(), and IG.Num.SimJMatProFileManagerBase.SaveSettings().
SaveSettings() [2/4]
void IG.Num.SimJMatProFileManagerBase.SaveSettings (string filePath, bool append) inline
Saves (serializes) the settings of the current JMatPro interface' file manager to the specified JSON file.
If the file already exists, contents either overwrite the file or are appended at the end, dependent on the value of the append flag.
Parameters
inputFilePath Path to the file in which settings are saved.
append Specifies whether serialized data is appended at the end of the file in the case that the file already exists.
References IG.Num.SimJMatProFileManagerBase.SaveSettings().
LoadSettings() [1/2]
void IG.Num.SimJMatProFileManagerBase.LoadSettings (string filePath) inline
Restores (deserializes) the current JMatPro interface' file manager settings from the specified file in JSON format.
Parameters
inputFilePath File from which object is restored.
Referenced by IG.Num.SimJMatProFileManagerBase.SimJMatProFileManagerBase().
SaveSettings() [3/4]
static void IG.Num.SimJMatProFileManagerBase.SaveSettings (SimJmatProSettingsDto settings, string filePath) inline static
Saves (serializes) the specified settings of the JMatPro interface' file manager to the specified JSON file.
If the file already exists, contents overwrite the file.
Parameters
settings JMatPro interface' settings that are saved to a file.
inputFilePath Path to the file into which settings are saved.
References IG.Num.SimJMatProFileManagerBase.SaveSettings().
SaveSettings() [4/4]
static void IG.Num.SimJMatProFileManagerBase.SaveSettings (SimJmatProSettingsDto settings, string filePath, bool append) inline static
Saves (serializes) the specified settings for JMatPro interface' file manager to the specified JSON file.
If the file already exists, contents either overwrite the file or are appended at the end, dependent on the value of the append flag.
Parameters
settings JMatPro interface' settings that are saved to a file.
inputFilePath Path to the file in which settings are saved.
append Specifies whether serialized data is appended at the end of the file in the case that the file already exists.
LoadSettings() [2/2]
static void IG.Num.SimJMatProFileManagerBase.LoadSettings (string filePath, ref SimJmatProSettingsDto settings) inline static
Restores (deserializes) JMatPro interface' settings from the specified file in JSON format.
Parameters
inputFilePath File from which object is restored.
settings JMatPro interface' settings that are restored by deserialization.
FindElementData()
static JMatProElemetData IG.Num.SimJMatProFileManagerBase.FindElementData (List< JMatProElemetData > elements, string elementSymbol) inline static
Finds data for the specified element on the specified list of element data, and returns the data (or null if the data is not be found).
Parameters
elements List of elements where data for the specific element is searched for.
elementSymbol Symbol of chemical element whose data is searched for.
References IG.Lib.JMatProElemetData.Symbol.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateJMatInput().
GetElementData()
JMatProElemetData IG.Num.SimJMatProFileManagerBase.GetElementData (string elementSymbol) inline
Returns data about the specified chemical element.
Parameters
elementSymbol Symbol of the chemical element.
Exceptions
ArgumentException When element symbol is not specified or there is no data about chemical element with such symbol.
References IG.Num.SimJMatProFileManagerBase.Elements, IG.Lib.JMatProElemetData.Getcopy(), and IG.Lib.JMatProElemetData.Symbol.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateJMatInput(), IG.Num.SimJMatProFileManagerBase.GetElementAtomicMass(), and IG.Num.SimJMatProFileManagerBase.GetElementName().
GetElementAtomicMass()
double IG.Num.SimJMatProFileManagerBase.GetElementAtomicMass (string elementSymbol) inline
Returns atomic mass of the chemical elemen with the specified symbol.
Parameters
elementSymbol Symbol of the chemical element.
References IG.Lib.JMatProElemetData.AtomicWeight, and IG.Num.SimJMatProFileManagerBase.GetElementData().
GetElementName()
string IG.Num.SimJMatProFileManagerBase.GetElementName (string elementSymbol) inline
Returns name of the chemical elemen with the specified symbol.
If element name is not defined for the specified element then its symbol is returned.
Parameters
elementSymbol Symbol of the chemical element.
References IG.Num.SimJMatProFileManagerBase.GetElementData(), and IG.Lib.JMatProElemetData.Name.
AddElements< ElType >()
void IG.Num.SimJMatProFileManagerBase.AddElements< ElType > (List< ElType > l, params ElType[] elements) inline protected
Adds the specified elements to the specified list.
Template Parameters
ElType Type of elements of the list.
Parameters
l List on which elements will be added.
elements Elements to be added to the list (variable length).
GetNumCompositionElements()
int IG.Num.SimJMatProFileManagerBase.GetNumCompositionElements () inline
Returns number of elements that are included in JMatPro input files for steel.
References IG.Num.SimJMatProFileManagerBase.CompositionElementSymbols.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateJMatInput(), and IG.Num.SimJMatProFileManagerBase.PrepareDataDefinitionsFromSuperset().
GetCompositionElementSymbol()
string IG.Num.SimJMatProFileManagerBase.GetCompositionElementSymbol (int which) inline
Returns the chemical symbol of the specified element.
Parameters
which Index of the element included in composition in JMatPro.
References IG.Num.SimJMatProFileManagerBase.CompositionElementSymbols.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateJMatInput(), and IG.Num.SimJMatProFileManagerBase.PrepareDataDefinitionsFromSuperset().
InitElements()
void IG.Num.SimJMatProFileManagerBase.InitElements () inline protected
Creates a list of chemical element data.
References IG.Num.SimJMatProFileManagerBase._compositionElementSymbols, IG.Num.SimJMatProFileManagerBase._elementData, IG.Num.SimJMatProFileManagerBase._elementsInitialized, and IG.Num.SimJMatProFileManagerBase.Lock.
GetSimulatorBaseDirectoryName()
string IG.Num.SimJMatProFileManagerBase.GetSimulatorBaseDirectoryName (int whichSimulator) inline
Calculates and returns name of the base simulator directory with the specified index (zero-based).
Parameters
whichSimulator Index of the simulator.
References IG.Lib.SimJMatProConst.SimulatorDirectoryPrefix, and IG.Num.SimJMatProFileManagerBase.WhichSimulator.
Referenced by IG.Num.SimJMatProFileManagerBase.GetSimulatorBaseDirectoryPath().
GetSimulatorBaseDirectoryPath()
string IG.Num.SimJMatProFileManagerBase.GetSimulatorBaseDirectoryPath (int whichSimulator) inline
Calculates and returns path of the root simulator directory with the specified index (zero-based).
Parameters
whichSimulator Index of the simulator.
References IG.Num.SimJMatProFileManagerBase.GetSimulatorBaseDirectoryName(), and IG.Num.SimJMatProFileManagerBase.RootSimulationDirectoryPath.
Referenced by IG.Num.SimJMatProFileManagerBase.GetSimCastingRobert(), and IG.Num.SimJMatProFileManagerBase.GetSimulatorCastingRobertDirectoryPath().
GetSimulatorCastingRobertDirectoryPath()
virtual string IG.Num.SimJMatProFileManagerBase.GetSimulatorCastingRobertDirectoryPath (int whichsimulator) inline virtual
Calculates and returns path of the Robert Vertnik's casting simulator's main directory with the specified index (zero-based).
Parameters
whichSimulator Index of the simulator.
References IG.Num.SimJMatProFileManagerBase.GetSimulatorBaseDirectoryPath(), IG.Num.SimJMatProFileManagerBase.SimulatorCastingRobertDirectoryname, and IG.Num.SimJMatProFileManagerBase.WhichSimulator.
Referenced by IG.Num.SimJMatProFileManagerBase.GetSimCastingRobert().
InitSimCastingRobert()
virtual void IG.Num.SimJMatProFileManagerBase.InitSimCastingRobert (string rootDirectory, string projectName, string simulationName) inline virtual
Initializes the data for casting simulation interface.
Parameters
rootDirectory Root directory of the simulator.
projectName Simulator's project name.
simulationName Simulation name.
References IG.Num.SimJMatProFileManagerBase.SimCastingRobertProjectName, IG.Num.SimJMatProFileManagerBase.SimCastingRobertRootDirectoryPath, and IG.Num.SimJMatProFileManagerBase.SimCastingRobertSimulationName.
GetSimCastingRobert()
virtual SimCastingRobertFileManager IG.Num.SimJMatProFileManagerBase.GetSimCastingRobert (int whichSimulator) inline protected virtual
Returns a newly created Robert Vertnik's casting simulator with the specified index (zero-based)
Parameters
whichSimulator Index of the simulator.
References IG.Lib.UtilSystem.CopyRecursive(), IG.Num.SimJMatProFileManagerBase.GetSimulatorBaseDirectoryPath(), IG.Num.SimJMatProFileManagerBase.GetSimulatorCastingRobertDirectoryPath(), IG.Num.SimJMatProFileManagerBase.SimCastingRobertProjectName, IG.Num.SimJMatProFileManagerBase.SimCastingRobertRootDirectoryPath, IG.Num.SimJMatProFileManagerBase.SimCastingRobertSimulationName, and IG.Num.SimJMatProFileManagerBase.SimulatorBaseTemplateDirectoryPath.
PrepareSimulatorData()
void IG.Num.SimJMatProFileManagerBase.PrepareSimulatorData (SimCastingRobertFileManager simulator, string materialDirectoryPath) inline
Prepares input data for simulator, in particular the material properties, which are obtained from the material data directory whose path is specified.
Parameters
simulator Simulator for which data is prepared.
materialDirectoryPath Path to the material data directory.
References IG.Num.SimJMatProFileManagerBase.MaterialResultsFilename.
CalculateSimulatedResponse() [1/3]
virtual void IG.Num.SimJMatProFileManagerBase.CalculateSimulatedResponse (SimCastingRobertFileManager simulator, string materialDirectory, IVector inputProcessParameters, ref IVector inputJointParameters, ref IVector outputValues) inline virtual
Calculates simulator's response at the specified process parameters, for the specified material directory (that specifies material parameters and properties), and stores joint input parameters and output values.
Parameters
simulator Simulator of type SimCastingRobertFileManager used to perform the numerical simulation at specified material and process parameters.
materialDirectory Approximate path to the material data directory from which material parameters and calculated material properties (input for simulation) are taken.
It can be specified as absolute path or relative to mat. data root (i.e. just dir. name) or relative to working directory.
Parameters
inputProcessParameters Input parameters for which response is calculated. These parameters are combined with material parameters that are obtained from the material directory (parameter materialDirectory) in order to produce a complete vector of parameters (that are stored to parameter inputJointParameters).
inputJointParameters Vector where joint parameters are stored (obtained be combination of material and process parameters).
outputValues Vector object where the calculated output values are stored after calculation.
References IG.Num.SimJMatProFileManagerBase.CreateJointParameters(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoryPath(), IG.Num.SimJMatProFileManagerBase.GetMaterialParameters(), IG.Num.IVector< T >.Length, IG.Num.SimJMatProFileManagerBase.NumParameters, and IG.Num.SimJMatProFileManagerBase.NumProcessParameters.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateSimulatedResponse().
CalculateSimulatedResponse() [2/3]
virtual int IG.Num.SimJMatProFileManagerBase.CalculateSimulatedResponse (SimCastingRobertFileManager simulator, string materialDirectory, ref SampledDataSet sampledData, params IVector[] inputProcessParameters) inline protected virtual
Calculates response by the specified simulator, for the specified process parameter vectors and the specified material (specified by the material directory approximate path), and stores calculated data in the specified sampled data set (object of type SampledDataSet).
If the specified data set is null then it is created anew, but if its input and output dimension don't match then exception is thrown.
Parameters
simulator Simulator of type SimCastingRobertFileManager used to perform the numerical simulation at specified material and process parameters.
materialDirectory Approximate path to the material data directory from which material parameters and calculated material properties (input for simulation) are taken.
It can be specified as absolute path or relative to mat. data root (i.e. just dir. name) or relative to working directory.
Parameters
sampledData Object of type SampledDataSet where calculated response is stored. If it is null then it is created anew, fut if input and output dimensions don't match dimensions of the current object then exception is thrown.
inputProcessParameters Input parameters for which response is calculated. These parameters are combined with material parameters that are obtained from the material directory (parameter materialDirectory) in order to produce a complete vector of parameters (that are stored to parameter inputJointParameters).
Returns
Number of actually calculated responses (i.e. the number of iput/output elements loaded to the dataset).
Exceptions
ArgumentException When data set for storing calculated responses (param. sampledData) is specified but has incorrect input and output dimensions.
References IG.Num.SimJMatProFileManagerBase.CalculateSimulatedResponse(), IG.Num.SimJMatProFileManagerBase.NumOutputValues, and IG.Num.SimJMatProFileManagerBase.NumParameters.
CalculateSimulatedResponse() [3/3]
virtual int IG.Num.SimJMatProFileManagerBase.CalculateSimulatedResponse (SimCastingRobertFileManager simulator, string materialDirectory, string datasetName, params IVector[] inputProcessParameters) inline virtual
Calculates response by the specified simulator, for the specified process parameter vectors and the specified material (specified by the material directory approximate path), and stores calculated data in the appropriate file in the material data directory (defined by the datasetName).
Results of previous calculations may already be stored in the appropriate file within the material data directory (whose name is defined by parameter datasetName). In this case, newly calculated results are added to the existend file. Otherwise, a new file within the material data directory is created to which results are stored.
Parameters
simulator Simulator of type SimCastingRobertFileManager used to perform the numerical simulation at specified material and process parameters.
materialDirectory Approximate path to the material data directory from which material parameters and calculated material properties (input for simulation) are taken.
It can be specified as absolute path or relative to mat. data root (i.e. just dir. name) or relative to working directory.
Parameters
datasetName Name of the data set that calculation refers to. This name defines the definition data for the specified calculation (which is not used here because process input paremeters are explicitly specified) and also the name of the file within the material directory where results of previous calculations for the same data set are stored and to which this mathod adds results of new calculations.
inputProcessParameters Input parameters for which response is calculated. These parameters are combined with material parameters that are obtained from the material directory (parameter materialDirectory) in order to produce a complete vector of parameters (that are stored to parameter inputJointParameters).
Returns
Number of actually calculated responses (i.e. the number of iput/output elements loaded to the dataset).
Exceptions
ArgumentException When data set for storing calculated responses (param. sampledData) is specified but has incorrect input and output dimensions.
References IG.Num.SimJMatProFileManagerBase.CalculateSimulatedResponse().
CalculateSimulatedResponseDefault()
virtual int IG.Num.SimJMatProFileManagerBase.CalculateSimulatedResponseDefault (SimCastingRobertFileManager simulator, string materialDirectory, string datasetName) inline virtual
Calculates response by the specified simulator, for the specified process parameter vectors and the specified material (specified by the material directory approximate path), and stores calculated data in the appropriate file in the material data directory (defined by the datasetName).
Results of previous calculations may already be stored in the appropriate file within the material data directory (whose name is defined by parameter datasetName). In this case, newly calculated results are added to the existend file. Otherwise, a new file within the material data directory is created to which results are stored.
Parameters
simulator Simulator of type SimCastingRobertFileManager used to perform the numerical simulation at specified material and process parameters.
materialDirectory Approximate path to the material data directory from which material parameters and calculated material properties (input for simulation) are taken.
It can be specified as absolute path or relative to mat. data root (i.e. just dir. name) or relative to working directory.
Parameters
datasetName Name of the data set that calculation refers to. This name defines the definition data for the specified calculation (which is not used here because process input paremeters are explicitly specified) and also the name of the file within the material directory where results of previous calculations for the same data set are stored and to which this mathod adds results of new calculations.
Returns
Number of actually calculated responses (i.e. the number of iput/output elements loaded to the dataset).
Exceptions
ArgumentException When data set for storing calculated responses (param. sampledData) is specified but has incorrect input and output dimensions.
Member Data Documentation
_mainLock
object IG.Num.SimJMatProFileManagerBase._mainLock = new object() private
_internalLock
object IG.Num.SimJMatProFileManagerBase._internalLock = new object() private
_lockFileMutexName
string IG.Num.SimJMatProFileManagerBase._lockFileMutexName = SimJMatProConst.LockFileMutexName protected
_lockFileMutex
Mutex IG.Num.SimJMatProFileManagerBase._lockFileMutex protected
_outputLevel
int IG.Num.SimJMatProFileManagerBase._outputLevel = Util.OutputLevel private
_nameJMatProBase
string IG.Num.SimJMatProFileManagerBase._nameJMatProBase protected
_jmatInstallationPath
string IG.Num.SimJMatProFileManagerBase._jmatInstallationPath protected
_executableFileName
string IG.Num.SimJMatProFileManagerBase._executableFileName protected
_executableFilePath
string IG.Num.SimJMatProFileManagerBase._executableFilePath protected
_jmatDataPath
string IG.Num.SimJMatProFileManagerBase._jmatDataPath protected
_jmatCompositionFilename
string IG.Num.SimJMatProFileManagerBase._jmatCompositionFilename = SimJMatProConst.JmatCompositionRelativepath protected
_jmatCompositionFilePath
string IG.Num.SimJMatProFileManagerBase._jmatCompositionFilePath protected
_jmatResultsFilename
string IG.Num.SimJMatProFileManagerBase._jmatResultsFilename = SimJMatProConst.JMatResultsRelativePath protected
_jmatResultsFilePath
string IG.Num.SimJMatProFileManagerBase._jmatResultsFilePath protected
_jmatCompletionDetectionFilename
string IG.Num.SimJMatProFileManagerBase._jmatCompletionDetectionFilename = SimJMatProConst.JMatCompletionDetectionRelativePath protected
_jmatCompletionDetectionFilePath
string IG.Num.SimJMatProFileManagerBase._jmatCompletionDetectionFilePath protected
_jmatCompletionDetectionSleepTimeSeconds
double IG.Num.SimJMatProFileManagerBase._jmatCompletionDetectionSleepTimeSeconds = SimJMatProConst.JMatCompletionDetectionSleepTimeSeconds protected
_jmatCompletionDetectionSize
int IG.Num.SimJMatProFileManagerBase._jmatCompletionDetectionSize = SimJMatProConst.JmatCompletionDetectionSize protected
_jmatBeforeSaveSleepTimeSeconds
double IG.Num.SimJMatProFileManagerBase._jmatBeforeSaveSleepTimeSeconds = SimJMatProConst.JMatBeforeSaveSleepTimeSeconds protected
_checkWorkingDirectoryExistence
bool IG.Num.SimJMatProFileManagerBase._checkWorkingDirectoryExistence = true protected
_workingDirectory
string IG.Num.SimJMatProFileManagerBase._workingDirectory = null protected
_dataDefinitionSupersetFilename
string IG.Num.SimJMatProFileManagerBase._dataDefinitionSupersetFilename = SimJMatProConst.DataDefinitionSupersetFilename protected
_dataDefinitionSupersetFilePath
string IG.Num.SimJMatProFileManagerBase._dataDefinitionSupersetFilePath protected
_dataDefinitionJMatFilename
string IG.Num.SimJMatProFileManagerBase._dataDefinitionJMatFilename = SimJMatProConst.DataDefinitionJMatFilename protected
_dataDefinitionJMatFilePath
string IG.Num.SimJMatProFileManagerBase._dataDefinitionJMatFilePath protected
_dataDefinitionProcessFilename
string IG.Num.SimJMatProFileManagerBase._dataDefinitionProcessFilename = SimJMatProConst.DataDefinitionProcessFilename protected
_dataDefinitionProcessFilePath
string IG.Num.SimJMatProFileManagerBase._dataDefinitionProcessFilePath protected
_dataDefinitionJointFilename
string IG.Num.SimJMatProFileManagerBase._dataDefinitionJointFilename = SimJMatProConst.DataDefinitionJointFilename protected
_dataDefinitionJointFilePath
string IG.Num.SimJMatProFileManagerBase._dataDefinitionJointFilePath protected
_dataDefinitionJMatFilenameNoNitrogen
string IG.Num.SimJMatProFileManagerBase._dataDefinitionJMatFilenameNoNitrogen = SimJMatProConst.DataDefinitionJMatFilenameNoNitrogen protected
_dataDefinitionJMatFilePathNoNitrogen
string IG.Num.SimJMatProFileManagerBase._dataDefinitionJMatFilePathNoNitrogen protected
_dataDefinitionJointFilenameNoNitrogen
string IG.Num.SimJMatProFileManagerBase._dataDefinitionJointFilenameNoNitrogen = SimJMatProConst.DataDefinitionJointFilenameNoNitrogen protected
_dataDefinitionJointFilePathNoNitrogen
string IG.Num.SimJMatProFileManagerBase._dataDefinitionJointFilePathNoNitrogen protected
_dataDefinitionSuperset
InputOutputDataDefiniton IG.Num.SimJMatProFileManagerBase._dataDefinitionSuperset protected
_dataDefinitionJMat
InputOutputDataDefiniton IG.Num.SimJMatProFileManagerBase._dataDefinitionJMat protected
_materialParameterBounds
IBoundingBox IG.Num.SimJMatProFileManagerBase._materialParameterBounds protected
_dataDefinitionProcess
InputOutputDataDefiniton IG.Num.SimJMatProFileManagerBase._dataDefinitionProcess protected
_dataDefinitionJoint
InputOutputDataDefiniton IG.Num.SimJMatProFileManagerBase._dataDefinitionJoint protected
_workingmaterialParametersPath
string IG.Num.SimJMatProFileManagerBase._workingmaterialParametersPath protected
_materialParametersDefFilename
string IG.Num.SimJMatProFileManagerBase._materialParametersDefFilename = SimJMatProConst.MaterialParametersDefFilename protected
_workingmaterialParametersDefPath
string IG.Num.SimJMatProFileManagerBase._workingmaterialParametersDefPath protected
_rootDataDirectoryname
string IG.Num.SimJMatProFileManagerBase._rootDataDirectoryname = SimJMatProConst.RootDataDirectoryName protected
_rootDataDirectoryPath
string IG.Num.SimJMatProFileManagerBase._rootDataDirectoryPath protected
_logFileName
string IG.Num.SimJMatProFileManagerBase._logFileName = SimJMatProConst.LogfileName protected
_logFilePath
string IG.Num.SimJMatProFileManagerBase._logFilePath protected
_logFileWriter
TextWriter IG.Num.SimJMatProFileManagerBase._logFileWriter protected
_materialDirectoryName
string IG.Num.SimJMatProFileManagerBase._materialDirectoryName protected
_materialDataDirectoryPath
string IG.Num.SimJMatProFileManagerBase._materialDataDirectoryPath protected
_materialParametersFilename
string IG.Num.SimJMatProFileManagerBase._materialParametersFilename = SimJMatProConst.MaterialParametersFilename protected
_materialParametersPath
string IG.Num.SimJMatProFileManagerBase._materialParametersPath protected
_materialCompositionFilename
string IG.Num.SimJMatProFileManagerBase._materialCompositionFilename = SimJMatProConst.JMatCompositionFilename protected
_materialCompositionPath
string IG.Num.SimJMatProFileManagerBase._materialCompositionPath protected
_materialResultsFilename
string IG.Num.SimJMatProFileManagerBase._materialResultsFilename = SimJMatProConst.JMatResultsFilename protected
_materialResultsPath
string IG.Num.SimJMatProFileManagerBase._materialResultsPath protected
_jMatResultsMinimalSize
int IG.Num.SimJMatProFileManagerBase._jMatResultsMinimalSize = SimJMatProConst.JMatResultsMinimalSize protected
_jMatResultsGoodSize
int IG.Num.SimJMatProFileManagerBase._jMatResultsGoodSize = SimJMatProConst.JMatResultsGoodSize protected
_msgMaterialCalculationBusyFilename
string IG.Num.SimJMatProFileManagerBase._msgMaterialCalculationBusyFilename = SimJMatProConst.MsgMaterialCalculationBusyFilename protected
Referenced by IG.Num.SimJMatProFileManagerBase.ClearBusyFlag(), IG.Num.SimJMatProFileManagerBase.IsBusyFlagSet(), and IG.Num.SimJMatProFileManagerBase.IsMaterialDirectoryCorrupted().
_msgMaterialCalculationBusyPath
string IG.Num.SimJMatProFileManagerBase._msgMaterialCalculationBusyPath protected
_msgMaterialCalculationFinishedFilename
string IG.Num.SimJMatProFileManagerBase._msgMaterialCalculationFinishedFilename = SimJMatProConst.MsgMaterialCalculationFinishedFilename protected
Referenced by IG.Num.SimJMatProFileManagerBase.ClearBusyFlag(), IG.Num.SimJMatProFileManagerBase.ClearMaterialCalculationFinishedFlag(), and IG.Num.SimJMatProFileManagerBase.IsMaterialCalculated().
_msgMaterialCalculationFinishedPath
string IG.Num.SimJMatProFileManagerBase._msgMaterialCalculationFinishedPath protected
_msgMaterialCalculationTimedoutFilename
string IG.Num.SimJMatProFileManagerBase._msgMaterialCalculationTimedoutFilename = SimJMatProConst.MsgMaterialCalculationTimedoutFilename protected
Referenced by IG.Num.SimJMatProFileManagerBase.ClearBusyFlag(), and IG.Num.SimJMatProFileManagerBase.IsTimedoutFlagSet().
_msgMaterialCalculationTimedoutPath
string IG.Num.SimJMatProFileManagerBase._msgMaterialCalculationTimedoutPath protected
_msgMaterialResultsWrongFilename
string IG.Num.SimJMatProFileManagerBase._msgMaterialResultsWrongFilename = SimJMatProConst.MsgMaterialResultsWrongFilename protected
Referenced by IG.Num.SimJMatProFileManagerBase.ClearMaterialResultsWrongFlag(), IG.Num.SimJMatProFileManagerBase.IsMaterialResultsWrongFlagSet(), and IG.Num.SimJMatProFileManagerBase.SetMaterialResultsWrongFlag().
_msgMaterialResultsWrongPath
string IG.Num.SimJMatProFileManagerBase._msgMaterialResultsWrongPath protected
_storageMaterialCalculatedDirectoryname
string IG.Num.SimJMatProFileManagerBase._storageMaterialCalculatedDirectoryname = SimJMatProConst.StorageMaterialCalculatedDirectoryname protected
_storageMaterialCalculatedDirectoryPath
string IG.Num.SimJMatProFileManagerBase._storageMaterialCalculatedDirectoryPath protected
_storageBusyFlagSetDirectoryname
string IG.Num.SimJMatProFileManagerBase._storageBusyFlagSetDirectoryname = SimJMatProConst.StorageBusyFlagSetDirectoryname protected
_storageBusyFlagSetDirectoryPath
string IG.Num.SimJMatProFileManagerBase._storageBusyFlagSetDirectoryPath protected
_storageTimedoutDirectoryname
string IG.Num.SimJMatProFileManagerBase._storageTimedoutDirectoryname = SimJMatProConst.StorageTimedoutDirectoryname protected
_storageTimedoutDirectoryPath
string IG.Num.SimJMatProFileManagerBase._storageTimedoutDirectoryPath protected
_storageMaterialCalculationFailedDirectoryname
string IG.Num.SimJMatProFileManagerBase._storageMaterialCalculationFailedDirectoryname = SimJMatProConst.StorageMaterialCalculationFailedDirectoryname protected
_storageMaterialCalculationFailedDirectoryPath
string IG.Num.SimJMatProFileManagerBase._storageMaterialCalculationFailedDirectoryPath protected
_storageMaterialMaterialDataCorruptedDirectoryname
string IG.Num.SimJMatProFileManagerBase._storageMaterialMaterialDataCorruptedDirectoryname = SimJMatProConst.StorageMaterialDataCorruptedDirectoryname protected
_storageMaterialMaterialDataCorruptedDirectoryPath
string IG.Num.SimJMatProFileManagerBase._storageMaterialMaterialDataCorruptedDirectoryPath protected
_waitSleepTimeSeconds
double IG.Num.SimJMatProFileManagerBase._waitSleepTimeSeconds = SimJMatProConst.WaitSleepTime protected
Referenced by IG.Num.SimJMatProFileManagerBase.SetMaterialCalculationBusy().
_userInteractionCommand
string IG.Num.SimJMatProFileManagerBase._userInteractionCommand = SimJMatProConst.UserInteractionCommand
_userInteractionRecordDir
string IG.Num.SimJMatProFileManagerBase._userInteractionRecordDir = SimJMatProConst.DefaultUserInteractionRecordDir
_userInteractionRecordExtension
string IG.Num.SimJMatProFileManagerBase._userInteractionRecordExtension = SimJMatProConst.UserInteractionRecordExtension
_userInteractionRecordNameStartJMat
string IG.Num.SimJMatProFileManagerBase._userInteractionRecordNameStartJMat = SimJMatProConst.UserInteractionRecordNameStartJMat
_userInteractionRecordPathStartJMat
string IG.Num.SimJMatProFileManagerBase._userInteractionRecordPathStartJMat
_userInteractionRecordNameCloseJMat
string IG.Num.SimJMatProFileManagerBase._userInteractionRecordNameCloseJMat = SimJMatProConst.UserInteractionRecordNameCloseJMat
_userInteractionRecordPathCloseJMat
string IG.Num.SimJMatProFileManagerBase._userInteractionRecordPathCloseJMat
_userInteractionRecordNameRepairJMat
string IG.Num.SimJMatProFileManagerBase._userInteractionRecordNameRepairJMat = SimJMatProConst.UserInteractionRecordNameRepairJMat
_userInteractionRecordPathRepairJMat
string IG.Num.SimJMatProFileManagerBase._userInteractionRecordPathRepairJMat
_userInteractionRecordNameStartCalculation
string IG.Num.SimJMatProFileManagerBase._userInteractionRecordNameStartCalculation = SimJMatProConst.UserInteractionRecordNameStartCalculation
_userInteractionRecordPathStartCalculation
string IG.Num.SimJMatProFileManagerBase._userInteractionRecordPathStartCalculation
_userInteractionRecordNameSaveResults
string IG.Num.SimJMatProFileManagerBase._userInteractionRecordNameSaveResults = SimJMatProConst.UserInteractionRecordNameSaveResults protected
_userInteractionRecordPathSaveResults
string IG.Num.SimJMatProFileManagerBase._userInteractionRecordPathSaveResults protected
_userInteractionRecordNameChangeTemperatureUnit
string IG.Num.SimJMatProFileManagerBase._userInteractionRecordNameChangeTemperatureUnit = SimJMatProConst.UserInteractionRecordNameChangeTemperatureUnit protected
_userInteractionRecordPathChangeTemperatureUnit
string IG.Num.SimJMatProFileManagerBase._userInteractionRecordPathChangeTemperatureUnit protected
_userInteractionRecordNameChangeFractionUnit
string IG.Num.SimJMatProFileManagerBase._userInteractionRecordNameChangeFractionUnit = SimJMatProConst.UserInteractionRecordNameChangeFractionUnit protected
_userInteractionRecordPathChangeFractionUnit
string IG.Num.SimJMatProFileManagerBase._userInteractionRecordPathChangeFractionUnit protected
_jMatTimeoutWaitCalculationSeconds
double IG.Num.SimJMatProFileManagerBase._jMatTimeoutWaitCalculationSeconds = SimJMatProConst.JMatTimeoutWaitCalculationSeconds
_jMatTimeoutWaitResultsSavedSeconds
double IG.Num.SimJMatProFileManagerBase._jMatTimeoutWaitResultsSavedSeconds = SimJMatProConst.JMatTimeoutWaitResultsSavedSeconds
_jMatResultsSavedDetectionSize
int IG.Num.SimJMatProFileManagerBase._jMatResultsSavedDetectionSize = SimJMatProConst.JMatResultsSavedDetectionSize protected
_jMatBeforeResultsSavedSleepTimeSeconds
double IG.Num.SimJMatProFileManagerBase._jMatBeforeResultsSavedSleepTimeSeconds = SimJMatProConst.JMatBeforeResultsSavedSleepTimeSeconds protected
_processNameSubstringJava
string IG.Num.SimJMatProFileManagerBase._processNameSubstringJava = SimJMatProConst.ProcessNameSubstringJava protected
_processNameSubstringJMatMain
string IG.Num.SimJMatProFileManagerBase._processNameSubstringJMatMain = SimJMatProConst.ProcessNameSubstringJMatMain protected
_processNameSubstringJMatSolver
string IG.Num.SimJMatProFileManagerBase._processNameSubstringJMatSolver = SimJMatProConst.ProcessNameSubstringJMatSolver protected
_materialCalculationStatus
CalculationStatus IG.Num.SimJMatProFileManagerBase._materialCalculationStatus = CalculationStatus.None protected
_materialCalculationTimer
StopWatch1 IG.Num.SimJMatProFileManagerBase._materialCalculationTimer protected
_longestMaterialCalculationTime
double IG.Num.SimJMatProFileManagerBase._longestMaterialCalculationTime protected
_materialCalculationTime
double IG.Num.SimJMatProFileManagerBase._materialCalculationTime protected
_numMaterialCalculationsIndended
int IG.Num.SimJMatProFileManagerBase._numMaterialCalculationsIndended protected
_numMaterialCalculationsPerformed
int IG.Num.SimJMatProFileManagerBase._numMaterialCalculationsPerformed protected
_numMaterialCalculationsSuccessful
int IG.Num.SimJMatProFileManagerBase._numMaterialCalculationsSuccessful protected
_numMaterialCalculationsTimedout
int IG.Num.SimJMatProFileManagerBase._numMaterialCalculationsTimedout protected
_numMaterialCalculationsUnsuccessful
int IG.Num.SimJMatProFileManagerBase._numMaterialCalculationsUnsuccessful protected
_numConsecutiveMaterialcalculationUnsuccessful
int IG.Num.SimJMatProFileManagerBase._numConsecutiveMaterialcalculationUnsuccessful protected
_numConsecutiveMaterialcalculationTimedout
int IG.Num.SimJMatProFileManagerBase._numConsecutiveMaterialcalculationTimedout protected
_numConsecutiveMaterialcalculationSuccessful
int IG.Num.SimJMatProFileManagerBase._numConsecutiveMaterialcalculationSuccessful protected
_materialParameters
IVector IG.Num.SimJMatProFileManagerBase._materialParameters protected
_compositionData
List<JMatProElemetData> IG.Num.SimJMatProFileManagerBase._compositionData protected
Storage of composition data.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateJMatInput().
_randGen
IRandomGenerator IG.Num.SimJMatProFileManagerBase._randGen private
_elementData
volatile List<JMatProElemetData> IG.Num.SimJMatProFileManagerBase._elementData protected
Referenced by IG.Num.SimJMatProFileManagerBase.InitElements().
_compositionElementSymbols
string [] IG.Num.SimJMatProFileManagerBase._compositionElementSymbols protected
Referenced by IG.Num.SimJMatProFileManagerBase.InitElements().
_elementsInitialized
bool IG.Num.SimJMatProFileManagerBase._elementsInitialized = false static protected
Referenced by IG.Num.SimJMatProFileManagerBase.InitElements().
_projectName
string IG.Num.SimJMatProFileManagerBase._projectName protected
_simulationName
string IG.Num.SimJMatProFileManagerBase._simulationName protected
_rootSimulationDirectoryname
string IG.Num.SimJMatProFileManagerBase._rootSimulationDirectoryname = SimJMatProConst.RootSimulationDirectoryName protected
_rootSimulationDirectoryPath
string IG.Num.SimJMatProFileManagerBase._rootSimulationDirectoryPath protected
_simulatorBaseTemplateDirectoryname
string IG.Num.SimJMatProFileManagerBase._simulatorBaseTemplateDirectoryname protected
_simulatorBaseTemplateDirectoryPath
string IG.Num.SimJMatProFileManagerBase._simulatorBaseTemplateDirectoryPath protected
_simulatorCastingRobertDirectoryname
string IG.Num.SimJMatProFileManagerBase._simulatorCastingRobertDirectoryname = SimJMatProConst.SimulatorCastingRobertDirectoryname protected
_whichSimulation
int IG.Num.SimJMatProFileManagerBase._whichSimulation = 0 protected
_simulatorBaseDirectoryPath
string IG.Num.SimJMatProFileManagerBase._simulatorBaseDirectoryPath protected
_simCastingRobertRootDirectoryPath
string IG.Num.SimJMatProFileManagerBase._simCastingRobertRootDirectoryPath protected
_simCastingRobertFM
SimCastingRobertFileManager IG.Num.SimJMatProFileManagerBase._simCastingRobertFM protected
Property Documentation
Lock
object IG.Num.SimJMatProFileManagerBase.Lock get
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateJMatInput(), IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Num.SimJMatProFileManagerBase.InitElements(), IG.Num.SimJMatProFileManagerBase.JMatWaitCalculation(), IG.Num.SimJMatProFileManagerBase.JMatWaitResultsSaved(), IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsReset(), IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsStart(), IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsStop(), and IG.Num.SimJMatProFileManagerBase.PrepareJMatInput().
InternalLock
object IG.Num.SimJMatProFileManagerBase.InternalLock get protected
Used internally for locking access to internal fields.
LockFileMutexName
string IG.Num.SimJMatProFileManagerBase.LockFileMutexName get protected set
Name of the mutex for system-wide locking of files.
LockFileMutex
Mutex IG.Num.SimJMatProFileManagerBase.LockFileMutex get protected
Mutex for system-wide exclusive locks for file system operations related to the current class.
Referenced by IG.Num.SimJMatProFileManagerBase.ClearBusyFlag(), IG.Num.SimJMatProFileManagerBase.ClearMaterialCalculationBusy(), IG.Num.SimJMatProFileManagerBase.ClearMaterialCalculationFinished(), IG.Num.SimJMatProFileManagerBase.ClearMaterialCalculationFinishedFlag(), IG.Num.SimJMatProFileManagerBase.ClearMaterialCalculationTimedout(), IG.Num.SimJMatProFileManagerBase.ClearMaterialResultsWrong(), IG.Num.SimJMatProFileManagerBase.ClearMaterialResultsWrongFlag(), IG.Num.SimJMatProFileManagerBase.CreateMaterialDataDirectory(), IG.Num.SimJMatProFileManagerBase.GetMaterialParameters(), IG.Num.SimJMatProFileManagerBase.IsBusyFlagSet(), IG.Num.SimJMatProFileManagerBase.IsMaterialCalculated(), IG.Num.SimJMatProFileManagerBase.IsMaterialCalculationBusy(), IG.Num.SimJMatProFileManagerBase.IsMaterialCalculationFinished(), IG.Num.SimJMatProFileManagerBase.IsMaterialCalculationTimedout(), IG.Num.SimJMatProFileManagerBase.IsMaterialDirectoryCorrupted(), IG.Num.SimJMatProFileManagerBase.IsMaterialResultsWrong(), IG.Num.SimJMatProFileManagerBase.IsMaterialResultsWrongFlagSet(), IG.Num.SimJMatProFileManagerBase.IsTimedoutFlagSet(), IG.Num.SimJMatProFileManagerBase.LockFileMutexCheckAbandoned(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectory(), IG.Num.SimJMatProFileManagerBase.ReleaseAbandonedMutex(), IG.Num.SimJMatProFileManagerBase.SetMaterialCalculationBusy(), IG.Num.SimJMatProFileManagerBase.SetMaterialCalculationFinished(), IG.Num.SimJMatProFileManagerBase.SetMaterialCalculationTimedout(), IG.Num.SimJMatProFileManagerBase.SetMaterialResultsWrong(), and IG.Num.SimJMatProFileManagerBase.SetMaterialResultsWrongFlag().
OutputLevel
int IG.Num.SimJMatProFileManagerBase.OutputLevel get set
Level of information that is output to the console by some methods.
Referenced by IG.Num.SimJMatProFileManagerBase.PrepareDataDefinitionsFromSuperset().
NameJMatProBase
abstract string IG.Num.SimJMatProFileManagerBase.NameJMatProBase get set
Name of the JMatPro directory (without root directories) and executable.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.ToString().
JMatInstallationPath
virtual string IG.Num.SimJMatProFileManagerBase.JMatInstallationPath get set
Path of the directory where JMAtPro executable is located. Setter takes only pure directory name, without path information. If set to null then directory path is set to null and will be recalculated when getter is called.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.ToString().
JMatExecutableFileName
virtual string IG.Num.SimJMatProFileManagerBase.JMatExecutableFileName get set
JMatPro executable relative path to installation directory.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
JMatExecutableFilePath
virtual string IG.Num.SimJMatProFileManagerBase.JMatExecutableFilePath get set
Path to the JMatPro executable.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
JMatDataPath
virtual string IG.Num.SimJMatProFileManagerBase.JMatDataPath get set
Path to the JMatPro data directory (containing material data, input and output data, etc.)
By default, this path is just set to installation path (in version 4.0, all data is stored in installation directory).
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
JMatCompositionFilename
virtual string IG.Num.SimJMatProFileManagerBase.JMatCompositionFilename get set
Relative path, with respect to JMatPro data directory, of the file containing material composition (input for JMatPro calculation).
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
JMatCompositionFilePath
virtual string IG.Num.SimJMatProFileManagerBase.JMatCompositionFilePath get set
Path of the file containing material composition (input for JMatPro calculation).
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
JMatResultsFilename
virtual string IG.Num.SimJMatProFileManagerBase.JMatResultsFilename get set
Relative path, with respect to JMatPro data directory, of the file containing material results of JMatPro calculation.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
JMatResultsFilePath
virtual string IG.Num.SimJMatProFileManagerBase.JMatResultsFilePath get set
Path of the file containing results of JMatPro calculation.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.JMatWaitResultsSaved().
JMatCompletionDetectionFilename
virtual string IG.Num.SimJMatProFileManagerBase.JMatCompletionDetectionFilename get set
Relative path, with respect to JMatPro data directory, of the file used to detect whether calculation is still going on.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
JMatCompletionDetectionFilePath
virtual string IG.Num.SimJMatProFileManagerBase.JMatCompletionDetectionFilePath get set
Path of the file used to detect whether calculation is still going on.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.JMatWaitCalculation().
JMatCompletionDetectionSleepTimeSeconds
virtual double IG.Num.SimJMatProFileManagerBase.JMatCompletionDetectionSleepTimeSeconds get set
Sleeping time used in detectiong whether JMatPro calculation is still going on.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.JMatWaitCalculation().
JMatCompletionDetectionSize
virtual int IG.Num.SimJMatProFileManagerBase.JMatCompletionDetectionSize get set
Minimal size of calculation detection file above which calculation is considered finished.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.JMatWaitCalculation().
JMatBeforeSaveSleepTimeSeconds
virtual double IG.Num.SimJMatProFileManagerBase.JMatBeforeSaveSleepTimeSeconds get set
Waiting time (in seconds) after last increase in file size used before assuming that calculation is finished, to eventually prevent too early detection that calculation was finished.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.JMatWaitCalculation().
CheckWorkingDirectoryExistence
bool IG.Num.SimJMatProFileManagerBase.CheckWorkingDirectoryExistence get set
Whether existence of working directory is checked when directory is created. Default is true.
WorkingDirectory
string IG.Num.SimJMatProFileManagerBase.WorkingDirectory get set
Working directory where configuration files and other files are located.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Num.SimJMatProFileManagerBase.CalculateMaterialPropertiesDef(), IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoryPath(), IG.Num.SimJMatProFileManagerBase.PrepareSettingsTemplate(), and IG.Num.SimJMatProFileManagerBase.SimJMatProFileManagerBase().
DataDefinitionSupersetFilename
virtual string IG.Num.SimJMatProFileManagerBase.DataDefinitionSupersetFilename get set
Name of the file containing definition data for the superset of all input parameters and output values.
This file may contain descriptions for more parameters and output values than those used, but it must contain all these parameters.
DataDefinitionSupersetFilePath
virtual string IG.Num.SimJMatProFileManagerBase.DataDefinitionSupersetFilePath get set
Path to the file containing definition data for the superset of all input parameters and output values.
This file may contain descriptions for more parameters and output values than those used, but it must contain all these parameters.
DataDefinitionJMatFilename
virtual string IG.Num.SimJMatProFileManagerBase.DataDefinitionJMatFilename get set
Name of the file containing data definition for all JMatPro input parameters (i.e. material composition expressed as mass fractions for individual parameters).
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
DataDefinitionJMatFilePath
virtual string IG.Num.SimJMatProFileManagerBase.DataDefinitionJMatFilePath get set
Path to the file containing data definition for all JMatPro input parameters (i.e. material composition expressed as mass fractions for individual parameters).
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.PrepareDataDefinitionsFromSuperset().
DataDefinitionProcessFilename
virtual string IG.Num.SimJMatProFileManagerBase.DataDefinitionProcessFilename get set
Name of the file containing data definition for all process input and output parameters.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
DataDefinitionProcessFilePath
virtual string IG.Num.SimJMatProFileManagerBase.DataDefinitionProcessFilePath get set
Path to the file containing data definition for all process input and output parameters.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
DataDefinitionJointFilename
virtual string IG.Num.SimJMatProFileManagerBase.DataDefinitionJointFilename get set
Name of the file containing definition data for the superset of all input parameters and output values.
This incluses definition of material parameters (i.e. composition expressed by mass fractions) followed by process parameters.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
DataDefinitionJointFilePath
virtual string IG.Num.SimJMatProFileManagerBase.DataDefinitionJointFilePath get set
Path to the file containing definition data for the Joint of all input parameters and output values.
This incluses definition of material parameters (i.e. composition expressed by mass fractions) followed by process parameters.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.PrepareDataDefinitionsFromSuperset().
DataDefinitionJMatFilenameNoNitrogen
virtual string IG.Num.SimJMatProFileManagerBase.DataDefinitionJMatFilenameNoNitrogen get set
Name of the file containing data definition for all JMatPro input parameters (i.e. material composition expressed as mass fractions for individual parameters).
DataDefinitionJMatFilePathNoNitrogen
virtual string IG.Num.SimJMatProFileManagerBase.DataDefinitionJMatFilePathNoNitrogen get set
Path to the file containing data definition for all JMatPro input parameters (i.e. material composition expressed as mass fractions for individual parameters).
Referenced by IG.Num.SimJMatProFileManagerBase.PrepareDataDefinitionsFromSuperset().
DataDefinitionJointFilenameNoNitrogen
virtual string IG.Num.SimJMatProFileManagerBase.DataDefinitionJointFilenameNoNitrogen get set
Name of the file containing definition data for the superset of all input parameters and output values.
This incluses definition of material parameters (i.e. composition expressed by mass fractions) followed by process parameters.
DataDefinitionJointFilePathNoNitrogen
virtual string IG.Num.SimJMatProFileManagerBase.DataDefinitionJointFilePathNoNitrogen get set
Path to the file containing definition data for the Joint of all input parameters and output values.
This incluses definition of material parameters (i.e. composition expressed by mass fractions) followed by process parameters.
Referenced by IG.Num.SimJMatProFileManagerBase.PrepareDataDefinitionsFromSuperset().
DataDefinitionSuperset
InputOutputDataDefiniton IG.Num.SimJMatProFileManagerBase.DataDefinitionSuperset get protected set
Data definitions for the superset of all input parameters and output values.
This may contain descriptions for more parameters and output values than those used, but it must contain all these parameters.
Referenced by IG.Num.SimJMatProFileManagerBase.PrepareDataDefinitionsFromSuperset().
DataDefinitionJMat
InputOutputDataDefiniton IG.Num.SimJMatProFileManagerBase.DataDefinitionJMat get protected set
Data definitions for all JMatPro input parameters (i.e. material composition expressed as mass fractions for individual parameters).
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateJMatInput(), IG.Num.SimJMatProFileManagerBase.GetMaterialParametersDefault(), and IG.Num.SimJMatProFileManagerBase.PrapareDefaultMaterialParameters().
MaterialParameterBounds
virtual IBoundingBox IG.Num.SimJMatProFileManagerBase.MaterialParameterBounds get protected set
Bounds on neural input parameters.
Referenced by IG.Num.SimJMatProFileManagerBase.GetRandomMaterialParameters().
DataDefinitionProcess
InputOutputDataDefiniton IG.Num.SimJMatProFileManagerBase.DataDefinitionProcess get protected set
Data definitions for the Process parameters and output values.
Referenced by IG.Num.SimJMatProFileManagerBase.PrepareDataDefinitionsFromSuperset().
DataDefinitionJoint
InputOutputDataDefiniton IG.Num.SimJMatProFileManagerBase.DataDefinitionJoint get protected set
Data definitions for all input parameters and output values, including material and process parameters.
NumMaterialParameters
int IG.Num.SimJMatProFileManagerBase.NumMaterialParameters get
Gets the number of material parameters.
Referenced by IG.Num.SimJMatProFileManagerBase.CreateJointParameters(), IG.Num.SimJMatProFileManagerBase.ExtractMaterialParameters(), and IG.Num.SimJMatProFileManagerBase.ExtractProcessParameters().
NumProcessParameters
int IG.Num.SimJMatProFileManagerBase.NumProcessParameters get
Gets the number of process parameters.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateSimulatedResponse(), IG.Num.SimJMatProFileManagerBase.CreateJointParameters(), and IG.Num.SimJMatProFileManagerBase.ExtractProcessParameters().
NumParameters
int IG.Num.SimJMatProFileManagerBase.NumParameters get
Gets the total number of all parameters.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateSimulatedResponse(), and IG.Num.SimJMatProFileManagerBase.CreateJointParameters().
NumOutputValues
int IG.Num.SimJMatProFileManagerBase.NumOutputValues get
Gets the number of output values for the process.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateSimulatedResponse().
WorkingMaterialParametersPath
virtual string IG.Num.SimJMatProFileManagerBase.WorkingMaterialParametersPath get protected set
File path of the file in working directory where material parameters for calculation are stored. If set to null then path is set to null and will be recalculated when getter is called.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.PrapareDefaultMaterialParameters().
MaterialParametersDefFilename
virtual string IG.Num.SimJMatProFileManagerBase.MaterialParametersDefFilename get set
Name of the file in material data directory where material parameters are stored.
WorkingMaterialParametersDefPath
virtual string IG.Num.SimJMatProFileManagerBase.WorkingMaterialParametersDefPath get protected set
File path of the file in working directory where material parameters for calculation are stored as default values in a data definition file. If set to null then path is set to null and will be recalculated when getter is called.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialPropertiesDef(), and IG.Num.SimJMatProFileManagerBase.PrapareDefaultMaterialParameters().
RootDataDirectoryName
string IG.Num.SimJMatProFileManagerBase.RootDataDirectoryName get set
Name of the root data directory.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
RootDataDirectoryPath
virtual string IG.Num.SimJMatProFileManagerBase.RootDataDirectoryPath get set
Path to the root directory that contains directories with calculated material data for different parameters defining chemical compositions.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectories(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereBusySet(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereCalculationFailed(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereMaterialCalculated(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereMaterialDataCorrupted(), IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoriesWhereTimedout(), and IG.Num.SimJMatProFileManagerBase.GetMaterialDirectoryPath().
LogFileName
virtual string IG.Num.SimJMatProFileManagerBase.LogFileName get set
Name of the log file where operations are logged.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
LogFilePath
virtual string IG.Num.SimJMatProFileManagerBase.LogFilePath get set
Path to the log file where basic operations are logged.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
LogFileWriter
TextWriter IG.Num.SimJMatProFileManagerBase.LogFileWriter get set
Textwriter for log file.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Num.SimJMatProFileManagerBase.CalculateMaterialPropertiesRandomSet(), IG.Num.SimJMatProFileManagerBase.ClearBusyFlag(), IG.Num.SimJMatProFileManagerBase.ClearBusyFlags(), IG.Script.S_12_09_jmatpro.CommandClearBusyFlags(), IG.Script.S_12_09_jmatpro.CommandPrepareData(), IG.Script.S_12_09_jmatpro.CommandRetryCalculateMaterialProperties(), IG.Script.S_12_09_jmatpro.CommandTestMaterialResults(), IG.Num.SimJMatProFileManagerBase.JMatLaunch(), IG.Num.SimJMatProFileManagerBase.MaterialCalculationsStatisticsPrint(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoriesToStorageAll(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectory(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageBusyFlagSet(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageCalculationFailed(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageDataCorrupted(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageMaterialCalculated(), IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageTimedout(), IG.Num.SimJMatProFileManagerBase.PrapareDefaultMaterialParameters(), IG.Num.SimJMatProFileManagerBase.PrepareDataDefinitionsFromSuperset(), IG.Num.SimJMatProFileManagerBase.ReleaseAbandonedMutex(), IG.Num.SimJMatProFileManagerBase.RetryCalculateMaterialProperties(), IG.Num.SimJMatProFileManagerBase.WriteMaterialCalculationStatistics(), and IG.Num.SimJMatProFileManagerBase.WriteMaterialDirectoriesWhereMaterialCalculated().
MaterialDirectoryName
string IG.Num.SimJMatProFileManagerBase.MaterialDirectoryName get protected set
Name of the material directory.
Getter forms name form material parameters if it is not specified. And vice versa, setting parameters will set the name (and consequently the material directory path) to null.
MaterialDataDirectoryPath
virtual string IG.Num.SimJMatProFileManagerBase.MaterialDataDirectoryPath get protected set
Data directory for the current material parameters.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CreateMaterialDataDirectory(), IG.Num.SimJMatProFileManagerBase.IsMaterialCalculationBusy(), IG.Num.SimJMatProFileManagerBase.IsMaterialCalculationFinished(), IG.Num.SimJMatProFileManagerBase.IsMaterialCalculationTimedout(), IG.Num.SimJMatProFileManagerBase.IsMaterialDataDirectoryPrepared(), and IG.Num.SimJMatProFileManagerBase.IsMaterialResultsWrong().
MaterialParametersFilename
virtual string IG.Num.SimJMatProFileManagerBase.MaterialParametersFilename get set
Name of the file in material data directory where material parameters are stored.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.GetMaterialParameters().
MaterialParametersPath
virtual string IG.Num.SimJMatProFileManagerBase.MaterialParametersPath get protected set
File path of the file where material parameters are stored. If set to null then path is set to null and will be recalculated when getter is called.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
MaterialCompositionFilename
virtual string IG.Num.SimJMatProFileManagerBase.MaterialCompositionFilename get set
Name of the file in material data directory where material composition is stored.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
MaterialCompositionPath
virtual string IG.Num.SimJMatProFileManagerBase.MaterialCompositionPath get protected set
File path of the file (normally in the material data directory) where material composition is stored. If set to null then path is set to null and will be recalculated when getter is called.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
MaterialResultsFilename
virtual string IG.Num.SimJMatProFileManagerBase.MaterialResultsFilename get set
Name of the file in material data directory where material results are stored.
Referenced by IG.Script.S_12_09_jmatpro.CommandTestMaterialResults(), IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.IsMaterialCalculated(), IG.Num.SimJMatProFileManagerBase.PrepareSimulatorData(), and IG.Num.SimJMatProFileManagerBase.WriteMaterialDirectoriesWhereMaterialCalculated().
MaterialResultsPath
virtual string IG.Num.SimJMatProFileManagerBase.MaterialResultsPath get protected set
File path of the file (normally in the material data directory) where material reslts are stored. If set to null then path is set to null and will be recalculated when getter is called.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
JMatResultsMinimalSize
virtual int IG.Num.SimJMatProFileManagerBase.JMatResultsMinimalSize get protected set
Minimal size of JMatPro results file in order to consider results valid.
Used to check the validity of the results.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.IsMaterialCalculated(), and IG.Num.SimJMatProFileManagerBase.WriteMaterialDirectoriesWhereMaterialCalculated().
JMatResultsGoodSize
virtual int IG.Num.SimJMatProFileManagerBase.JMatResultsGoodSize get protected set
Size of the materials result file that is considered a good size - the file is expected to be at least of this size if calculation was performed without errors.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.WriteMaterialDirectoriesWhereMaterialCalculated().
MsgMaterialCalculationBusyPath
virtual string IG.Num.SimJMatProFileManagerBase.MsgMaterialCalculationBusyPath get protected set
File path of the material calculation in progress flag file. Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
Referenced by IG.Num.SimJMatProFileManagerBase.ClearMaterialCalculationBusy(), IG.Num.SimJMatProFileManagerBase.IsMaterialCalculationBusy(), and IG.Num.SimJMatProFileManagerBase.SetMaterialCalculationBusy().
MsgMaterialCalculationFinishedPath
virtual string IG.Num.SimJMatProFileManagerBase.MsgMaterialCalculationFinishedPath get protected set
File path of the "material calculation finished" flag file. Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
Referenced by IG.Num.SimJMatProFileManagerBase.ClearMaterialCalculationFinished(), IG.Num.SimJMatProFileManagerBase.IsMaterialCalculationFinished(), and IG.Num.SimJMatProFileManagerBase.SetMaterialCalculationFinished().
MsgMaterialCalculationTimedoutPath
virtual string IG.Num.SimJMatProFileManagerBase.MsgMaterialCalculationTimedoutPath get protected set
File path of the "material calculation timeout occurred" flag file. Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
Referenced by IG.Num.SimJMatProFileManagerBase.ClearMaterialCalculationTimedout(), IG.Num.SimJMatProFileManagerBase.IsMaterialCalculationTimedout(), and IG.Num.SimJMatProFileManagerBase.SetMaterialCalculationTimedout().
MsgMaterialResultsWrongPath
virtual string IG.Num.SimJMatProFileManagerBase.MsgMaterialResultsWrongPath get protected set
File path of the "material results wrong" flag file. Setter takes only pure file name, without path information. If set to null then path is set to null and will be recalculated when getter is called.
Referenced by IG.Num.SimJMatProFileManagerBase.ClearMaterialResultsWrong(), IG.Num.SimJMatProFileManagerBase.IsMaterialResultsWrong(), and IG.Num.SimJMatProFileManagerBase.SetMaterialResultsWrong().
StorageMaterialCalculatedDirectoryname
virtual string IG.Num.SimJMatProFileManagerBase.StorageMaterialCalculatedDirectoryname get set
Name of the storage directory for material directories for which material properties have been successfully calculated.
StorageMaterialCalculatedDirectoryPath
virtual string IG.Num.SimJMatProFileManagerBase.StorageMaterialCalculatedDirectoryPath get protected set
Path to the storage directory for material directories for which material properties have been successfully calculated.
Referenced by IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageMaterialCalculated().
StorageBusyFlagSetDirectoryname
virtual string IG.Num.SimJMatProFileManagerBase.StorageBusyFlagSetDirectoryname get set
Name of the storage directory for material directories for which busy flag remained set.
StorageBusyFlagSetDirectoryPath
virtual string IG.Num.SimJMatProFileManagerBase.StorageBusyFlagSetDirectoryPath get protected set
Path to the storage directory for material directories for which busy flag remained set.
Referenced by IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageBusyFlagSet().
StorageTimedoutDirectoryname
virtual string IG.Num.SimJMatProFileManagerBase.StorageTimedoutDirectoryname get set
Name of the storage directory for material directories for which material properties calculation has timed out.
StorageTimedoutDirectoryPath
virtual string IG.Num.SimJMatProFileManagerBase.StorageTimedoutDirectoryPath get protected set
Path to the storage directory for material directories for which material properties calculation has timed out.
Referenced by IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageTimedout().
StorageMaterialCalculationFailedDirectoryname
virtual string IG.Num.SimJMatProFileManagerBase.StorageMaterialCalculationFailedDirectoryname get set
Path to the storage directory for material directories for which calculation of material properties has failed.
StorageMaterialCalculationFailedDirectoryPath
virtual string IG.Num.SimJMatProFileManagerBase.StorageMaterialCalculationFailedDirectoryPath get protected set
Path to the storage directory for material directories for which calculation of material properties has failed.
Referenced by IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageCalculationFailed(), and IG.Num.SimJMatProFileManagerBase.MoveMaterialDirectoryToStorageDataCorrupted().
StorageMaterialMaterialDataCorruptedDirectoryname
virtual string IG.Num.SimJMatProFileManagerBase.StorageMaterialMaterialDataCorruptedDirectoryname get set
Path to the storage directory for material directories for which calculation of material properties has failed.
StorageMaterialMaterialDataCorruptedDirectoryPath
virtual string IG.Num.SimJMatProFileManagerBase.StorageMaterialMaterialDataCorruptedDirectoryPath get protected set
Path to the storage directory for material directories for which calculation of material properties has failed.
UserInteractionCommand
virtual string IG.Num.SimJMatProFileManagerBase.UserInteractionCommand get set
Command for playback of recorded user interaction (i.e. emulation of keyboard and mouse events) for various actions.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.JMatChangeFractionUnit(), IG.Num.SimJMatProFileManagerBase.JMatChangeTemperatureUnit(), IG.Num.SimJMatProFileManagerBase.JMatClose(), IG.Num.SimJMatProFileManagerBase.JMatOpen(), IG.Num.SimJMatProFileManagerBase.JMatRepair(), IG.Num.SimJMatProFileManagerBase.JMatSaveResults(), and IG.Num.SimJMatProFileManagerBase.JMatStartCalculation().
UserInteractionRecordDir
virtual string IG.Num.SimJMatProFileManagerBase.UserInteractionRecordDir get set
Dierctory containing recorded user interactions for different actions.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.ToString().
UserInteractionRecordExtension
virtual string IG.Num.SimJMatProFileManagerBase.UserInteractionRecordExtension get set
Extension of files with recorded user interaction.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.ToString().
UserInteractionRecordNameStartJMat
virtual string IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameStartJMat get set
Name of the user interaction record for starting JMatPro software via system GUI.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
UserInteractionRecordPathStartJMat
virtual string IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathStartJMat get set
Name of the user interaction record for closing JMatPro software via system GUI.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.JMatOpen().
UserInteractionRecordNameCloseJMat
virtual string IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameCloseJMat get set
Name of the user interaction record for closing JMatPro software normally via GUI.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
UserInteractionRecordPathCloseJMat
virtual string IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathCloseJMat get set
Name of the user interaction record for closing JMatPro software normally via GUI.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.JMatClose().
UserInteractionRecordNameRepairJMat
virtual string IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameRepairJMat get set
Name of the file containing records of user interaction necessary repair JMatPro in case it is damaged or another unwanted copy is running.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
UserInteractionRecordPathRepairJMat
virtual string IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathRepairJMat get set
Path of the file containing records of user interaction necessary repair JMatPro in case it is damaged or another unwanted copy is running.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.JMatRepair().
UserInteractionRecordNameStartCalculation
virtual string IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameStartCalculation get set
Name of the file containing recors of user interaction necessary to start JMatPro.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.ToString().
UserInteractionRecordPathStartCalculation
virtual string IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathStartCalculation get set
Name of the file containing recors of user interaction necessary to start JMatPro.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.JMatStartCalculation(), and IG.Num.SimJMatProFileManagerBase.ToString().
UserInteractionRecordNameSaveResults
virtual string IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameSaveResults get set
Name of the file containing records of user interaction necessary to save results of JMatPro calculation.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.ToString().
UserInteractionRecordPathSaveResults
virtual string IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathSaveResults get set
Path to the file containing recors of user interaction necessary to save results of JMatPro calculation.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.JMatSaveResults(), and IG.Num.SimJMatProFileManagerBase.ToString().
UserInteractionRecordNameChangeTemperatureUnit
virtual string IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameChangeTemperatureUnit get set
Name of the file containing records of user interaction necessary to change temperature uits in JMatPro that is already launched.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
UserInteractionRecordPathChangeTemperatureUnit
virtual string IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathChangeTemperatureUnit get set
Path to the file containing recors of user interaction necessary to change temperature uits in JMatPro that is already launched.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.JMatChangeTemperatureUnit().
UserInteractionRecordNameChangeFractionUnit
virtual string IG.Num.SimJMatProFileManagerBase.UserInteractionRecordNameChangeFractionUnit get set
Name of the file containing records of user interaction necessary to change fraction uits in JMatPro that is already launched.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >().
UserInteractionRecordPathChangeFractionUnit
virtual string IG.Num.SimJMatProFileManagerBase.UserInteractionRecordPathChangeFractionUnit get set
Path to the file containing recors of user interaction necessary to change fraction uits in JMatPro that is already launched.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.JMatChangeFractionUnit().
JMatTimeoutWaitCalculationSeconds
double IG.Num.SimJMatProFileManagerBase.JMatTimeoutWaitCalculationSeconds get protected set
Timeout for waiting completion of calculation, in seconds.
If greater than 0 and results of calculation are waiter for more time than the timeout specifies, waiting is broken and it is considered that calculation could not be completed.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.JMatWaitCalculation().
JMatTimeoutWaitResultsSavedSeconds
virtual double IG.Num.SimJMatProFileManagerBase.JMatTimeoutWaitResultsSavedSeconds get protected set
Timeout for waiting until results are completely saved, in seconds.
If greater than 0 and saving results is waited for more time than the timeout specifies, waiting is broken and it is considered that saving could not be completed.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.JMatWaitResultsSaved().
JMatResultsSavedDetectionSize
virtual int IG.Num.SimJMatProFileManagerBase.JMatResultsSavedDetectionSize get set
Minimal size of result file file, above which saving results can be considered finished.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.JMatWaitResultsSaved().
JMatBeforeResultsSavedSleepTimeSeconds
virtual double IG.Num.SimJMatProFileManagerBase.JMatBeforeResultsSavedSleepTimeSeconds get set
Waiting time (in seconds) after last increase in file size used before assuming that saving result is finished, to eventually prevent too early detection that calculation was finished.
Referenced by IG.Num.SimJMatProFileManagerBase.CopyFromSettingsPlain< FmType >(), IG.Num.SimJMatProFileManagerBase.CopyToSettingsPlain< FmType >(), and IG.Num.SimJMatProFileManagerBase.JMatWaitResultsSaved().
ProcessNameSubstringJava
string IG.Num.SimJMatProFileManagerBase.ProcessNameSubstringJava get protected set
Substring of java virtual machine process name, used to kill the process or check whether it is running.
Referenced by IG.Num.SimJMatProFileManagerBase.IsJMatProRunning(), and IG.Num.SimJMatProFileManagerBase.KillJMatPro().
ProcessNameSubstringJMatMain
string IG.Num.SimJMatProFileManagerBase.ProcessNameSubstringJMatMain get protected set
Substring of JMatPro main process name, used to kill the process or check whether it is running.
Referenced by IG.Num.SimJMatProFileManagerBase.IsJMatProRunning(), and IG.Num.SimJMatProFileManagerBase.KillJMatPro().
ProcessNameSubstringJMatSolver
string IG.Num.SimJMatProFileManagerBase.ProcessNameSubstringJMatSolver get protected set
Substring of JMatPro solver process name, used to kill the process or check whether it is running.
Referenced by IG.Num.SimJMatProFileManagerBase.KillJMatPro().
MaterialCalculationStatus
CalculationStatus IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatus get protected set
Status of the last material calculation.
At the beginning of each material calculation, status is set to CalculationStatus.None.
Referenced by IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsReset(), IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsStart(), and IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsStop().
MaterialCalculationTimer
StopWatch1 IG.Num.SimJMatProFileManagerBase.MaterialCalculationTimer get
Timer for measuring total calculation time in methods that perform multiple material calculations.
Referenced by IG.Num.SimJMatProFileManagerBase.MaterialCalculationsStatisticsPrint(), IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsReset(), IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsStart(), and IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsStop().
LongestMaterialCalculationTime
double IG.Num.SimJMatProFileManagerBase.LongestMaterialCalculationTime get protected set
Longest material calculation time by now, reset at the beginning of every top level calculation function.
Referenced by IG.Num.SimJMatProFileManagerBase.MaterialCalculationsStatisticsPrint(), and IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsReset().
MaterialCalculationTime
double IG.Num.SimJMatProFileManagerBase.MaterialCalculationTime get set
Referenced by IG.Num.SimJMatProFileManagerBase.MaterialCalculationsStatisticsPrint(), IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsReset(), IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsStart(), and IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsStop().
NumMaterialCalculationsIntended
int IG.Num.SimJMatProFileManagerBase.NumMaterialCalculationsIntended get protected set
Total number of intended material calculations attempted by now.k
Reset at the beginning of every top level calculations.
Referenced by IG.Num.SimJMatProFileManagerBase.MaterialCalculationsStatisticsPrint(), and IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsReset().
NumMaterialCalculationsPerformed
int IG.Num.SimJMatProFileManagerBase.NumMaterialCalculationsPerformed get protected set
Number of (completed) material calculations attempted by now.
Reset at the beginning of every top level calculations.
Referenced by IG.Num.SimJMatProFileManagerBase.MaterialCalculationsStatisticsPrint(), IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsReset(), and IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsStop().
NumMaterialCalculationsSuccessful
int IG.Num.SimJMatProFileManagerBase.NumMaterialCalculationsSuccessful get protected set
Number of material calculations by now that have successfully completed.
Reset at the beginning of every top level calculations.
Referenced by IG.Num.SimJMatProFileManagerBase.MaterialCalculationsStatisticsPrint(), IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsReset(), and IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsStop().
NumMaterialCalculationsTimedout
int IG.Num.SimJMatProFileManagerBase.NumMaterialCalculationsTimedout get protected set
Number of material calculations by now where timeout occurred.
Reset at the beginning of every top level calculations.
Referenced by IG.Num.SimJMatProFileManagerBase.MaterialCalculationsStatisticsPrint(), IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsReset(), and IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsStop().
NumMaterialCalculationsUnsuccessful
int IG.Num.SimJMatProFileManagerBase.NumMaterialCalculationsUnsuccessful get protected set
Number of material calculations by now where calculation has failed.
Reset at the beginning of every top level calculations.
Referenced by IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsReset(), and IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsStop().
NumconsecutiveMaterialCalculationsUnsuccessful
int IG.Num.SimJMatProFileManagerBase.NumconsecutiveMaterialCalculationsUnsuccessful get set
Number fo consecutive events where material calculation was not successfule.
Referenced by IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsReset(), and IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsStop().
NumconsecutiveMaterialCalculationTimedout
int IG.Num.SimJMatProFileManagerBase.NumconsecutiveMaterialCalculationTimedout get set
Number fo consecutive events where timeout occurred during material calculation.
Referenced by IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsReset(), and IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsStop().
NumconsecutiveMaterialCalculationsSuccessful
int IG.Num.SimJMatProFileManagerBase.NumconsecutiveMaterialCalculationsSuccessful get set
Number fo consecutive events where material calculation was not successful.
Referenced by IG.Num.SimJMatProFileManagerBase.MaterialCalculationStatisticsStop().
MaterialParameters
IVector IG.Num.SimJMatProFileManagerBase.MaterialParameters get set
Parameters that define chemical composition of steel for which material properties are calculated.
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateMaterialProperties(), IG.Num.SimJMatProFileManagerBase.IsMaterialDataDirectoryPrepared(), and IG.Num.SimJMatProFileManagerBase.PrepareJMatInput().
Random
virtual IRandomGenerator IG.Num.SimJMatProFileManagerBase.Random get protected set
Random generator used by the current object.
Lazy evaluation, created when needed for the first time.
The generator is thread safe and initialized with a time dependent seed.
Referenced by IG.Num.SimJMatProFileManagerBase.GetRandomMaterialParameters().
Elements
List<JMatProElemetData> IG.Num.SimJMatProFileManagerBase.Elements get set protected
List of element data to be used in JMatPro.
Referenced by IG.Num.SimJMatProFileManagerBase.GetElementData().
CompositionElementSymbols
string [] IG.Num.SimJMatProFileManagerBase.CompositionElementSymbols get set protected
Array of element symbols sorted as required gor the JMatPro input file.
Referenced by IG.Num.SimJMatProFileManagerBase.GetCompositionElementSymbol(), and IG.Num.SimJMatProFileManagerBase.GetNumCompositionElements().
SymbolIron
virtual string IG.Num.SimJMatProFileManagerBase.SymbolIron get
Referenced by IG.Num.SimJMatProFileManagerBase.CalculateJMatInput().
ProjectName
virtual string IG.Num.SimJMatProFileManagerBase.ProjectName get protected set
Name of the current project, used in some simulation and other interfaces.
SimulationName
virtual string IG.Num.SimJMatProFileManagerBase.SimulationName get protected set
Name of the current simulation, used in some simulation and other interfaces.
RootSimulationDirectoryName
string IG.Num.SimJMatProFileManagerBase.RootSimulationDirectoryName get set
Name of the root simulation directory.
RootSimulationDirectoryPath
virtual string IG.Num.SimJMatProFileManagerBase.RootSimulationDirectoryPath get set
Path to the root simulator directory that contains directories with simulators' data (there may be more than one such directory in the case of parallel simulators.
Referenced by IG.Num.SimJMatProFileManagerBase.GetSimulatorBaseDirectoryPath().
SimulatorBaseTemplateDirectoryname
string IG.Num.SimJMatProFileManagerBase.SimulatorBaseTemplateDirectoryname get set
Name of the simulator template directory. This is the root simulator directory that contains all simuator related data and must be copied in order to produce a new active simulator.
SimulatorBaseTemplateDirectoryPath
virtual string IG.Num.SimJMatProFileManagerBase.SimulatorBaseTemplateDirectoryPath get protected set
Path to the simulator template directory. This is the root simulator directory that contains all simuator related data and must be copied in order to produce a new active simulator.
Referenced by IG.Num.SimJMatProFileManagerBase.GetSimCastingRobert().
SimulatorCastingRobertDirectoryname
string IG.Num.SimJMatProFileManagerBase.SimulatorCastingRobertDirectoryname get set
Name of the main directory of the Robert Vertnik's casting simulator.
Referenced by IG.Num.SimJMatProFileManagerBase.GetSimulatorCastingRobertDirectoryPath().
SimCastingRobertProjectName
virtual string IG.Num.SimJMatProFileManagerBase.SimCastingRobertProjectName get set protected
Project name for interfacing Robert Vertnik's casting simulator.
Referenced by IG.Num.SimJMatProFileManagerBase.GetSimCastingRobert(), and IG.Num.SimJMatProFileManagerBase.InitSimCastingRobert().
SimCastingRobertSimulationName
virtual string IG.Num.SimJMatProFileManagerBase.SimCastingRobertSimulationName get set protected
Simulation name for interfacing Robert Vertnik's casting simulator.
Referenced by IG.Num.SimJMatProFileManagerBase.GetSimCastingRobert(), and IG.Num.SimJMatProFileManagerBase.InitSimCastingRobert().
WhichSimulator
int IG.Num.SimJMatProFileManagerBase.WhichSimulator get protected set
Specifies which simulator is in use by the current file manager (this is 0 if simulators are not run in parallel and there is a single simulator).
Referenced by IG.Num.SimJMatProFileManagerBase.GetSimulatorBaseDirectoryName(), and IG.Num.SimJMatProFileManagerBase.GetSimulatorCastingRobertDirectoryPath().
SimulatorBaseDirectoryPath
virtual string IG.Num.SimJMatProFileManagerBase.SimulatorBaseDirectoryPath get protected set
Path to the base directory of the current simulator in use. This directory is directly contained in the
SimCastingRobertRootDirectoryPath
virtual string IG.Num.SimJMatProFileManagerBase.SimCastingRobertRootDirectoryPath get protected set
Path of the main directory of the Robert Vertnik's casting simulator that is currently in use.
Referenced by IG.Num.SimJMatProFileManagerBase.GetSimCastingRobert(), and IG.Num.SimJMatProFileManagerBase.InitSimCastingRobert().
SimCastingRobertFM
virtual SimCastingRobertFileManager IG.Num.SimJMatProFileManagerBase.SimCastingRobertFM get set
File manager for interfacing Robert Vertnik's casting simulator. Lazy evaluation: The object is created when first accessed, if possible. For this, ProjectName, SimulationName and SimCastingRobertRootDirectoryPath must be defined.
The documentation for this class was generated from the following files:
shelldev/lib/extended/LibNeuralExt/interfaces_simulations/jmatpro/SimJMatProFileManager.cs
shelldev/lib/extended/LibNeuralExt/interfaces_simulations/jmatpro/SimJMatProFMSim.cs