Doc: IGLib EXTENDED: AForge.Imaging.Image Class Reference
AForge.Imaging.Image Class Reference
Core image relatad methods.
Static Public Member Functions
static bool IsGrayscale (Bitmap image)
Check if specified 8 bpp image is grayscale.
static Bitmap CreateGrayscaleImage (int width, int height)
Create and initialize new 8 bpp grayscale image.
static void SetGrayscalePalette (Bitmap image)
Set pallete of the 8 bpp indexed image to grayscale.
static Bitmap Clone (Bitmap source, PixelFormat format)
Clone image.
static Bitmap Clone (Bitmap source)
Clone image.
static Bitmap Clone (BitmapData sourceData)
Clone image.
static void FormatImage (ref Bitmap image)
Format an image.
static System.Drawing.Bitmap FromFile (string fileName)
Load bitmap from file.
static Bitmap Convert16bppTo8bpp (Bitmap bimap)
Convert bitmap with 16 bits per plane to a bitmap with 8 bits per plane.
static Bitmap Convert8bppTo16bpp (Bitmap bimap)
Convert bitmap with 8 bits per plane to a bitmap with 16 bits per plane.
Detailed Description
Core image relatad methods.
All methods of this class are static and represent general routines used by different image processing classes.
Member Function Documentation
IsGrayscale()
static bool AForge.Imaging.Image.IsGrayscale (Bitmap image) inline static
Check if specified 8 bpp image is grayscale.
Parameters
image Image to check.
Returns
Returns true if the image is grayscale or false otherwise.
The methods checks if the image is a grayscale image of 256 gradients. The method first examines if the image's pixel format is Format8bppIndexed and then it examines its palette to check if the image is grayscale or not.
Referenced by AForge.Imaging.Image.FormatImage().
CreateGrayscaleImage()
static Bitmap AForge.Imaging.Image.CreateGrayscaleImage (int width, int height) inline static
Create and initialize new 8 bpp grayscale image.
Parameters
width Image width.
height Image height.
Returns
Returns the created grayscale image.
The method creates new 8 bpp grayscale image and initializes its palette. Grayscale image is represented as Format8bppIndexed image with palette initialized to 256 gradients of gray color.
References AForge.Imaging.Image.SetGrayscalePalette().
Referenced by AForge.Imaging.Filters.BaseInPlaceFilter.Apply(), AForge.Imaging.Filters.BaseInPlacePartialFilter.Apply(), AForge.Imaging.Filters.BaseTransformationFilter.Apply(), AForge.Imaging.Filters.BaseFilter.Apply(), AForge.Imaging.Filters.BaseUsingCopyPartialFilter.Apply(), AForge.Imaging.Image.Convert16bppTo8bpp(), AForge.Video.Kinect.KinectVideoCamera.HandleDataReceived(), AForge.Imaging.Textures.TextureTools.ToBitmap(), AForge.Imaging.ComplexImage.ToBitmap(), AForge.Imaging.HoughCircleTransformation.ToBitmap(), AForge.Imaging.HoughLineTransformation.ToBitmap(), and AForge.Imaging.UnmanagedImage.ToManagedImage().
SetGrayscalePalette()
static void AForge.Imaging.Image.SetGrayscalePalette (Bitmap image) inline static
Set pallete of the 8 bpp indexed image to grayscale.
Parameters
image Image to initialize.
The method initializes palette of Format8bppIndexed image with 256 gradients of gray color.
Exceptions
UnsupportedImageFormatException Provided image is not 8 bpp indexed image.
Referenced by AForge.Imaging.Image.CreateGrayscaleImage(), and AForge.Imaging.UnmanagedImage.ToManagedImage().
Clone() [1/3]
static Bitmap AForge.Imaging.Image.Clone (Bitmap source, PixelFormat format) inline static
Clone image.
Parameters
source Source image.
format Pixel format of result image.
Returns
Returns clone of the source image with specified pixel format.
The original Bitmap.Clone() does not produce the desired result - it does not create a clone with specified pixel format. More of it, the original method does not create an actual clone - it does not create a copy of the image. That is why this method was implemented to provide the functionality.
Referenced by AForge.Imaging.Image.Clone(), AForge.Imaging.Image.FormatImage(), AForge.Controls.VideoSourcePlayer.GetCurrentVideoFrame(), SVSTest.StereoViewForm.OnNewLeftFrame(), SVSTest.StereoViewForm.OnNewRightFrame(), FiltersDemo.MainForm.openFileItem_Click(), HoughTransform.MainForm.openToolStripMenuItem_Click(), and BlobsExplorer.BlobsBrowser.SetImage().
Clone() [2/3]
static Bitmap AForge.Imaging.Image.Clone (Bitmap source) inline static
Clone image.
Parameters
source Source image.
Returns
Return clone of the source image.
The original Bitmap.Clone() does not produce the desired result - it does not create an actual clone (it does not create a copy of the image). That is why this method was implemented to provide the functionality.
References AForge.Imaging.Image.Clone(), and AForge.Math.Geometry.Rectangle.
Clone() [3/3]
static Bitmap AForge.Imaging.Image.Clone (BitmapData sourceData) inline static
Clone image.
Parameters
sourceData Source image data.
Returns
Clones image from source image data. The message does not clone pallete in the case if the source image has indexed pixel format.
References AForge.SystemTools.CopyUnmanagedMemory(), and AForge.Math.Geometry.Rectangle.
FormatImage()
static void AForge.Imaging.Image.FormatImage (ref Bitmap image) inline static
Format an image.
Parameters
image Source image to format.
Formats the image to one of the formats, which are supported by the AForge.Imaging library. The image is left untouched in the case if it is already of Format24bppRgb or Format32bppRgb or Format32bppArgb or Format48bppRgb or Format64bppArgb format or it is grayscale, otherwise the image is converted to Format24bppRgb format.
<note>The method is deprecated and Clone(Bitmap, PixelFormat) method should be used instead with specifying desired pixel format.</note>
References AForge.Imaging.Image.Clone(), and AForge.Imaging.Image.IsGrayscale().
Referenced by HoughTransform.MainForm.openToolStripMenuItem_Click().
FromFile()
static System.Drawing.Bitmap AForge.Imaging.Image.FromFile (string fileName) inline static
Load bitmap from file.
Parameters
fileName File name to load bitmap from.
Returns
Returns loaded bitmap.
The method is provided as an alternative of System.Drawing.Image.FromFile(string) method to solve the issues of locked file. The standard .NET's method locks the source file until image's object is disposed, so the file can not be deleted or overwritten. This method workarounds the issue and does not lock the source file.
Sample usage:
Bitmap image = AForge.Imaging.Image.FromFile("test.jpg");
Convert16bppTo8bpp()
static Bitmap AForge.Imaging.Image.Convert16bppTo8bpp (Bitmap bimap) inline static
Convert bitmap with 16 bits per plane to a bitmap with 8 bits per plane.
Parameters
bimap Source image to convert.
Returns
Returns new image which is a copy of the source image but with 8 bits per plane.
The routine does the next pixel format conversions:
Format16bppGrayScale to Format8bppIndexed with grayscale palette;
Format48bppRgb to Format24bppRgb;
Format64bppArgb to Format32bppArgb;
Format64bppPArgb to Format32bppPArgb.
Exceptions
UnsupportedImageFormatException Invalid pixel format of the source image.
References AForge.Imaging.Image.CreateGrayscaleImage(), and AForge.Math.Geometry.Rectangle.
Referenced by AForge.Controls.VideoSourcePlayer.videoSource_NewFrame().
Convert8bppTo16bpp()
static Bitmap AForge.Imaging.Image.Convert8bppTo16bpp (Bitmap bimap) inline static
Convert bitmap with 8 bits per plane to a bitmap with 16 bits per plane.
Parameters
bimap Source image to convert.
Returns
Returns new image which is a copy of the source image but with 16 bits per plane.
The routine does the next pixel format conversions:
Format8bppIndexed (grayscale palette assumed) to Format16bppGrayScale;
Format24bppRgb to Format48bppRgb;
Format32bppArgb to Format64bppArgb;
Format32bppPArgb to Format64bppPArgb.
Exceptions
UnsupportedImageFormatException Invalid pixel format of the source image.
References AForge.Math.Geometry.Rectangle.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Image.cs