Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAEXC Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAEXC Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAEXC (DLAMCH dlamch, DLANGE dlange, DLACPY dlacpy, DLANV2 dlanv2, DLARFG dlarfg, DLARFX dlarfx, DLARTG dlartg, DLASY2 dlasy2, DROT drot)
DLAEXC ()
void Run (bool WANTQ, int N, ref double[] T, int offset_t, int LDT, ref double[] Q, int offset_q, int LDQ, int J1, int N1, int N2, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
DLAMCH _dlamch
DLANGE _dlange
DLACPY _dlacpy
DLANV2 _dlanv2
DLARFG _dlarfg
DLARFX _dlarfx
DLARTG _dlartg
DLASY2 _dlasy2
DROT _drot
double[] D = new double[LDD * 4]
double[] U = new double[3]
double[] U1 = new double[3]
double[] U2 = new double[3]
double[] X = new double[LDX * 2]
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
const double TEN = 1.0E+1
const int LDD = 4
const int LDX = 2
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAEXC swaps adjacent diagonal blocks T11 and T22 of order 1 or 2 in an upper quasi-triangular matrix T by an orthogonal similarity transformation.
T must be in Schur canonical form, that is, block upper triangular with 1-by-1 and 2-by-2 diagonal blocks; each 2-by-2 diagonal block has its diagonal elemnts equal and its off-diagonal elements of opposite sign.
/summary>
Constructor & Destructor Documentation
DLAEXC() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAEXC.DLAEXC (DLAMCH dlamch, DLANGE dlange, DLACPY dlacpy, DLANV2 dlanv2, DLARFG dlarfg, DLARFX dlarfx, DLARTG dlartg, DLASY2 dlasy2, DROT drot) inline
DLAEXC() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAEXC.DLAEXC () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAEXC.Run (bool WANTQ, int N, ref double[] T, int offset_t, int LDT, ref double[] Q, int offset_q, int LDQ, int J1, int N1, int N2, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
DLAEXC swaps adjacent diagonal blocks T11 and T22 of order 1 or 2 in an upper quasi-triangular matrix T by an orthogonal similarity transformation.
T must be in Schur canonical form, that is, block upper triangular with 1-by-1 and 2-by-2 diagonal blocks; each 2-by-2 diagonal block has its diagonal elemnts equal and its off-diagonal elements of opposite sign.
/summary>
Parameters
WANTQ (input) LOGICAL = .TRUE. : accumulate the transformation in the matrix Q; = .FALSE.: do not accumulate the transformation. /param>
Parameters
N (input) INTEGER The order of the matrix T. N .GE. 0. /param>
Parameters
T must be in Schur canonical form, that is, block upper triangular /param>
Parameters
LDT (input) INTEGER The leading dimension of the array T. LDT .GE. max(1,N). /param>
Parameters
Q (input/output) DOUBLE PRECISION array, dimension (LDQ,N) On entry, if WANTQ is .TRUE., the orthogonal matrix Q. On exit, if WANTQ is .TRUE., the updated matrix Q. If WANTQ is .FALSE., Q is not referenced. /param>
Parameters
LDQ (input) INTEGER The leading dimension of the array Q. LDQ .GE. 1; and if WANTQ is .TRUE., LDQ .GE. N. /param>
Parameters
J1 (input) INTEGER The index of the first row of the first block T11. /param>
Parameters
N1 (input) INTEGER The order of the first block T11. N1 = 0, 1 or 2. /param>
Parameters
N2 (input) INTEGER The order of the second block T22. N2 = 0, 1 or 2. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (N) /param>
Parameters
INFO (output) INTEGER = 0: successful exit = 1: the transformed matrix T would be too far from Schur form; the blocks are not swapped and T and Q are unchanged. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLAEXC.D, DotNumerics.LinearAlgebra.CSLapack.DLAEXC.LDD, DotNumerics.LinearAlgebra.CSLapack.DLAEXC.LDX, DotNumerics.LinearAlgebra.CSLapack.DLAEXC.ONE, DotNumerics.LinearAlgebra.CSLapack.DROT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARTG.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANV2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFX.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANGE.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASY2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAEXC.TEN, DotNumerics.LinearAlgebra.CSLapack.DLAEXC.U, DotNumerics.LinearAlgebra.CSLapack.DLAEXC.U1, DotNumerics.LinearAlgebra.CSLapack.DLAEXC.U2, DotNumerics.LinearAlgebra.CSLapack.DLAEXC.X, and DotNumerics.LinearAlgebra.CSLapack.DLAEXC.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTREXC.Run().
Member Data Documentation
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLAEXC._dlamch private
_dlange
DLANGE DotNumerics.LinearAlgebra.CSLapack.DLAEXC._dlange private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DLAEXC._dlacpy private
_dlanv2
DLANV2 DotNumerics.LinearAlgebra.CSLapack.DLAEXC._dlanv2 private
_dlarfg
DLARFG DotNumerics.LinearAlgebra.CSLapack.DLAEXC._dlarfg private
_dlarfx
DLARFX DotNumerics.LinearAlgebra.CSLapack.DLAEXC._dlarfx private
_dlartg
DLARTG DotNumerics.LinearAlgebra.CSLapack.DLAEXC._dlartg private
_dlasy2
DLASY2 DotNumerics.LinearAlgebra.CSLapack.DLAEXC._dlasy2 private
_drot
DROT DotNumerics.LinearAlgebra.CSLapack.DLAEXC._drot private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAEXC.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAEXC.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAEXC.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAEXC.Run().
TEN
const double DotNumerics.LinearAlgebra.CSLapack.DLAEXC.TEN = 1.0E+1 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAEXC.Run().
LDD
const int DotNumerics.LinearAlgebra.CSLapack.DLAEXC.LDD = 4 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAEXC.Run().
LDX
const int DotNumerics.LinearAlgebra.CSLapack.DLAEXC.LDX = 2 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAEXC.Run().
D
double [] DotNumerics.LinearAlgebra.CSLapack.DLAEXC.D = new double[LDD * 4] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAEXC.Run().
U
double [] DotNumerics.LinearAlgebra.CSLapack.DLAEXC.U = new double[3] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAEXC.Run().
U1
double [] DotNumerics.LinearAlgebra.CSLapack.DLAEXC.U1 = new double[3] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAEXC.Run().
U2
double [] DotNumerics.LinearAlgebra.CSLapack.DLAEXC.U2 = new double[3] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAEXC.Run().
X
double [] DotNumerics.LinearAlgebra.CSLapack.DLAEXC.X = new double[LDX * 2] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAEXC.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlaexc.cs