Doc: IGLib EXTENDED: IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11 Class Reference
IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11 Class Reference
Window that displays information about Demo application for performing parametric studies on ANN models.
Public Member Functions
NeuralParametricDemoAboutWindowOld11 ()
void ShowHelp ()
void ShowWebPage ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
Applications.NeuralParametricDemoAboutOld11 neuralParametricDemoAbout1
Detailed Description
Window that displays information about Demo application for performing parametric studies on ANN models.
$A Igor Apr13;
Constructor & Destructor Documentation
NeuralParametricDemoAboutWindowOld11()
IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11.NeuralParametricDemoAboutWindowOld11 () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11.InitializeComponent().
Member Function Documentation
ShowHelp()
void IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11.ShowHelp () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11.neuralParametricDemoAbout1, and IG.Neural.Applications.NeuralParametricDemoAboutOld11.ShowHelp().
Referenced by IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemo_HelpEventHandlers().
ShowWebPage()
void IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11.ShowWebPage () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11.neuralParametricDemoAbout1, and IG.Neural.Applications.NeuralParametricDemoAboutOld11.ShowWebPage().
Dispose()
override void IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11.components.
InitializeComponent()
void IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11.neuralParametricDemoAbout1.
Referenced by IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11.NeuralParametricDemoAboutWindowOld11().
Member Data Documentation
components
System.ComponentModel.IContainer IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11.components = null private
Required designer variable.
Referenced by IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11.Dispose().
neuralParametricDemoAbout1
Applications.NeuralParametricDemoAboutOld11 IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11.neuralParametricDemoAbout1 private
Referenced by IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11.InitializeComponent(), IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11.ShowHelp(), and IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11.ShowWebPage().
The documentation for this class was generated from the following files:
shelldev/extensions/ExtAppAnnApp/FormsOld/NeuralParametricDemoAboutWindowOld11.cs
shelldev/extensions/ExtAppAnnApp/FormsOld/NeuralParametricDemoAboutWindowOld11.Designer.cs