Doc: IGLib EXTENDED: AForge.Video.Ximea.XimeaCamera Class Reference
AForge.Video.Ximea.XimeaCamera Class Reference
The class provides access to XIMEA cameras.
Public Member Functions
void Open (int deviceID)
Open XIMEA camera.
void Close ()
Close opened camera (if any) and release allocated resources.
void StartAcquisition ()
Begin camera's work cycle and start data acquisition from it.
void StopAcquisition ()
End camera's work cycle and stops data acquisition.
void SetParam (string parameterName, int value)
Set camera's parameter.
void SetParam (string parameterName, float value)
Set camera's parameter.
int GetParamInt (string parameterName)
Get camera's parameter as integer value.
float GetParamFloat (string parameterName)
Get camera's parameter as float value.
string GetParamString (string parameterName)
Get camera's parameter as string value.
unsafe Bitmap GetImage ()
Get image from the opened XIMEA camera.
unsafe Bitmap GetImage (int timeout)
Get image from the opened XIMEA camera.
Bitmap GetImage (int timeout, bool makeCopy)
Get image from the opened XIMEA camera.
Properties
static int CamerasCount [get]
Get number of XIMEA camera connected to the system.
bool IsAcquisitionStarted [get]
Specifies if camera's data acquisition is currently active for the opened camera (if any).
bool IsDeviceOpen [get]
Specifies if a camera is currently opened by the instance of the class.
int DeviceID [get]
ID of the the recently opened XIMEA camera.
Private Member Functions
void CheckConnection ()
Static Private Member Functions
static void HandleError (int errorCode)
Private Attributes
IntPtr deviceHandle = IntPtr.Zero
bool isAcquisitionStarted = false
int deviceID = 0
object sync = new object()
Detailed Description
The class provides access to XIMEA cameras.
The class allows to perform image acquisition from XIMEA cameras. It wraps XIMEA'a xiAPI, which means that users of this class will also require m3api.dll and a correct TM file for the camera model connected to the system (both are provided with XIMEA API software package).
Sample usage:
XimeaCamera camera = new XimeaCamera();
// open camera and start data acquisition
camera.Open(0);
camera.StartAcquisition();
// set exposure time to 10 milliseconds
camera.SetParam(CameraParameter.Exposure, 10 * 1000);
// get image from the camera
Bitmap bitmap = camera.GetImage();
// process the image
// ...
// dispose the image when it is no longer needed
bitmap.Dispose();
// stop data acquisition and close the camera
camera.StopAcquisition();
camera.Close();
See also
XimeaVideoSource
Member Function Documentation
Open()
void AForge.Video.Ximea.XimeaCamera.Open (int deviceID) inline
Open XIMEA camera.
Parameters
deviceID Camera ID to open.
Opens the specified XIMEA camera preparing it for starting video acquisition which is done using StartAcquisition method. The IsDeviceOpen property can be used at any time to find if a camera was opened or not.
Exceptions
VideoException An error occurred while communicating with a camera. See error message for additional information.
References AForge.Video.Ximea.XimeaCamera.deviceHandle, AForge.Video.Ximea.XimeaCamera.deviceID, AForge.Video.Ximea.XimeaCamera.HandleError(), and AForge.Video.Ximea.XimeaCamera.sync.
Referenced by AForge.Video.Ximea.XimeaVideoSource.Start().
Close()
void AForge.Video.Ximea.XimeaCamera.Close () inline
Close opened camera (if any) and release allocated resources.
<note>The method also calls StopAcquisition method if it was not done by user.</note>
Exceptions
VideoException An error occurred while communicating with a camera. See error message for additional information.
References AForge.Video.Ximea.XimeaCamera.deviceHandle, AForge.Video.Ximea.XimeaCamera.HandleError(), AForge.Video.Ximea.XimeaCamera.isAcquisitionStarted, AForge.Video.Ximea.XimeaCamera.StopAcquisition(), and AForge.Video.Ximea.XimeaCamera.sync.
Referenced by AForge.Video.Ximea.XimeaVideoSource.Free().
StartAcquisition()
void AForge.Video.Ximea.XimeaCamera.StartAcquisition () inline
Begin camera's work cycle and start data acquisition from it.
The IsAcquisitionStarted property can be used at any time to find if the acquisition was started or not.
Exceptions
VideoException An error occurred while communicating with a camera. See error message for additional information.
NotConnectedException No camera was opened, so can not access its methods.
References AForge.Video.Ximea.XimeaCamera.CheckConnection(), AForge.Video.Ximea.XimeaCamera.deviceHandle, AForge.Video.Ximea.XimeaCamera.HandleError(), AForge.Video.Ximea.XimeaCamera.isAcquisitionStarted, and AForge.Video.Ximea.XimeaCamera.sync.
Referenced by AForge.Video.Ximea.XimeaVideoSource.WorkerThread().
StopAcquisition()
void AForge.Video.Ximea.XimeaCamera.StopAcquisition () inline
End camera's work cycle and stops data acquisition.
Exceptions
VideoException An error occurred while communicating with a camera. See error message for additional information.
NotConnectedException No camera was opened, so can not access its methods.
References AForge.Video.Ximea.XimeaCamera.CheckConnection(), AForge.Video.Ximea.XimeaCamera.deviceHandle, AForge.Video.Ximea.XimeaCamera.HandleError(), AForge.Video.Ximea.XimeaCamera.isAcquisitionStarted, and AForge.Video.Ximea.XimeaCamera.sync.
Referenced by AForge.Video.Ximea.XimeaCamera.Close(), and AForge.Video.Ximea.XimeaVideoSource.WorkerThread().
SetParam() [1/2]
void AForge.Video.Ximea.XimeaCamera.SetParam (string parameterName, int value) inline
Set camera's parameter.
Parameters
parameterName Parameter name.
value Integer parameter value.
The method allows to control different camera's parameters, like exposure time, gain value, etc. See CameraParameter class for the list of some possible configuration parameters. See XIMEA documentation for the complete list of supported parameters.
Exceptions
VideoException An error occurred while communicating with a camera. See error message for additional information.
NotConnectedException No camera was opened, so can not access its methods.
References AForge.Video.Ximea.XimeaCamera.CheckConnection(), AForge.Video.Ximea.XimeaCamera.deviceHandle, AForge.Video.Ximea.XimeaCamera.HandleError(), and AForge.Video.Ximea.XimeaCamera.sync.
Referenced by AForge.Video.Ximea.XimeaVideoSource.SetParam().
SetParam() [2/2]
void AForge.Video.Ximea.XimeaCamera.SetParam (string parameterName, float value) inline
Set camera's parameter.
Parameters
parameterName Parameter name.
value Float parameter value.
The method allows to control different camera's parameters, like exposure time, gain value, etc. See CameraParameter class for the list of some possible configuration parameters. See XIMEA documentation for the complete list of supported parameters.
Exceptions
VideoException An error occurred while communicating with a camera. See error message for additional information.
NotConnectedException No camera was opened, so can not access its methods.
References AForge.Video.Ximea.XimeaCamera.CheckConnection(), AForge.Video.Ximea.XimeaCamera.deviceHandle, AForge.Video.Ximea.XimeaCamera.HandleError(), and AForge.Video.Ximea.XimeaCamera.sync.
GetParamInt()
int AForge.Video.Ximea.XimeaCamera.GetParamInt (string parameterName) inline
Get camera's parameter as integer value.
Parameters
parameterName Parameter name to get from camera.
Returns
Returns integer value of the requested parameter.
See CameraParameter class for the list of some possible configuration parameters. See XIMEA documentation for the complete list of supported parameters.
Exceptions
VideoException An error occurred while communicating with a camera. See error message for additional information.
NotConnectedException No camera was opened, so can not access its methods.
References AForge.Video.Ximea.XimeaCamera.CheckConnection(), AForge.Video.Ximea.XimeaCamera.deviceHandle, AForge.Video.Ximea.XimeaCamera.HandleError(), and AForge.Video.Ximea.XimeaCamera.sync.
Referenced by AForge.Video.Ximea.XimeaVideoSource.GetParamInt().
GetParamFloat()
float AForge.Video.Ximea.XimeaCamera.GetParamFloat (string parameterName) inline
Get camera's parameter as float value.
Parameters
parameterName Parameter name to get from camera.
Returns
Returns float value of the requested parameter.
See CameraParameter class for the list of some possible configuration parameters. See XIMEA documentation for the complete list of supported parameters.
Exceptions
VideoException An error occurred while communicating with a camera. See error message for additional information.
NotConnectedException No camera was opened, so can not access its methods.
References AForge.Video.Ximea.XimeaCamera.CheckConnection(), AForge.Video.Ximea.XimeaCamera.deviceHandle, AForge.Video.Ximea.XimeaCamera.HandleError(), and AForge.Video.Ximea.XimeaCamera.sync.
Referenced by AForge.Video.Ximea.XimeaVideoSource.GetParamFloat().
GetParamString()
string AForge.Video.Ximea.XimeaCamera.GetParamString (string parameterName) inline
Get camera's parameter as string value.
Parameters
parameterName Parameter name to get from camera.
Returns
Returns string value of the requested parameter.
See CameraParameter class for the list of some possible configuration parameters. See XIMEA documentation for the complete list of supported parameters.
Exceptions
VideoException An error occurred while communicating with a camera. See error message for additional information.
NotConnectedException No camera was opened, so can not access its methods.
References AForge.Video.Ximea.XimeaCamera.CheckConnection(), AForge.Video.Ximea.XimeaCamera.deviceHandle, AForge.Video.Ximea.XimeaCamera.HandleError(), and AForge.Video.Ximea.XimeaCamera.sync.
Referenced by AForge.Video.Ximea.XimeaVideoSource.GetParamString().
GetImage() [1/3]
unsafe Bitmap AForge.Video.Ximea.XimeaCamera.GetImage () inline
Get image from the opened XIMEA camera.
Returns
Returns image retrieved from the camera.
The method calls GetImage(int) method specifying 5000 as the timeout value.
Referenced by AForge.Video.Ximea.XimeaCamera.GetImage(), and AForge.Video.Ximea.XimeaVideoSource.WorkerThread().
GetImage() [2/3]
unsafe Bitmap AForge.Video.Ximea.XimeaCamera.GetImage (int timeout) inline
Get image from the opened XIMEA camera.
Parameters
timeout Maximum time to wait in milliseconds till image becomes available.
Returns
Returns image retrieved from the camera.
The method calls GetImage(int,bool) method specifying true the makeCopy parameter.
References AForge.Video.Ximea.XimeaCamera.GetImage().
GetImage() [3/3]
Bitmap AForge.Video.Ximea.XimeaCamera.GetImage (int timeout, bool makeCopy) inline
Get image from the opened XIMEA camera.
Parameters
timeout Maximum time to wait in milliseconds till image becomes available.
makeCopy Make a copy of the camera's image or not.
Returns
Returns image retrieved from the camera.
If the makeCopy is set to true, then the method creates a managed copy of the camera's image, so the managed image stays valid even when the camera is closed. However, setting this parameter to false creates a managed image which is just a wrapper around camera's unmanaged image. So if camera is closed and its resources are freed, the managed image becomes no longer valid and accessing it will generate an exception.
Exceptions
VideoException An error occurred while communicating with a camera. See error message for additional information.
NotConnectedException No camera was opened, so can not access its methods.
TimeoutException Time out value reached - no image is available within specified time value.
References AForge.Video.Ximea.XimeaCamera.CheckConnection(), AForge.SystemTools.CopyUnmanagedMemory(), AForge.Video.Ximea.XimeaCamera.deviceHandle, AForge.Video.Ximea.XimeaCamera.HandleError(), and AForge.Video.Ximea.XimeaCamera.sync.
HandleError()
static void AForge.Video.Ximea.XimeaCamera.HandleError (int errorCode) inline static private
Referenced by AForge.Video.Ximea.XimeaCamera.Close(), AForge.Video.Ximea.XimeaCamera.GetImage(), AForge.Video.Ximea.XimeaCamera.GetParamFloat(), AForge.Video.Ximea.XimeaCamera.GetParamInt(), AForge.Video.Ximea.XimeaCamera.GetParamString(), AForge.Video.Ximea.XimeaCamera.Open(), AForge.Video.Ximea.XimeaCamera.SetParam(), AForge.Video.Ximea.XimeaCamera.StartAcquisition(), and AForge.Video.Ximea.XimeaCamera.StopAcquisition().
CheckConnection()
void AForge.Video.Ximea.XimeaCamera.CheckConnection () inline private
References AForge.Video.Ximea.XimeaCamera.deviceHandle.
Referenced by AForge.Video.Ximea.XimeaCamera.GetImage(), AForge.Video.Ximea.XimeaCamera.GetParamFloat(), AForge.Video.Ximea.XimeaCamera.GetParamInt(), AForge.Video.Ximea.XimeaCamera.GetParamString(), AForge.Video.Ximea.XimeaCamera.SetParam(), AForge.Video.Ximea.XimeaCamera.StartAcquisition(), and AForge.Video.Ximea.XimeaCamera.StopAcquisition().
Member Data Documentation
deviceHandle
IntPtr AForge.Video.Ximea.XimeaCamera.deviceHandle = IntPtr.Zero private
Referenced by AForge.Video.Ximea.XimeaCamera.CheckConnection(), AForge.Video.Ximea.XimeaCamera.Close(), AForge.Video.Ximea.XimeaCamera.GetImage(), AForge.Video.Ximea.XimeaCamera.GetParamFloat(), AForge.Video.Ximea.XimeaCamera.GetParamInt(), AForge.Video.Ximea.XimeaCamera.GetParamString(), AForge.Video.Ximea.XimeaCamera.Open(), AForge.Video.Ximea.XimeaCamera.SetParam(), AForge.Video.Ximea.XimeaCamera.StartAcquisition(), and AForge.Video.Ximea.XimeaCamera.StopAcquisition().
isAcquisitionStarted
bool AForge.Video.Ximea.XimeaCamera.isAcquisitionStarted = false private
Referenced by AForge.Video.Ximea.XimeaCamera.Close(), AForge.Video.Ximea.XimeaCamera.StartAcquisition(), and AForge.Video.Ximea.XimeaCamera.StopAcquisition().
deviceID
int AForge.Video.Ximea.XimeaCamera.deviceID = 0 private
Referenced by AForge.Video.Ximea.XimeaCamera.Open().
sync
object AForge.Video.Ximea.XimeaCamera.sync = new object() private
Referenced by AForge.Video.Ximea.XimeaCamera.Close(), AForge.Video.Ximea.XimeaCamera.GetImage(), AForge.Video.Ximea.XimeaCamera.GetParamFloat(), AForge.Video.Ximea.XimeaCamera.GetParamInt(), AForge.Video.Ximea.XimeaCamera.GetParamString(), AForge.Video.Ximea.XimeaCamera.Open(), AForge.Video.Ximea.XimeaCamera.SetParam(), AForge.Video.Ximea.XimeaCamera.StartAcquisition(), and AForge.Video.Ximea.XimeaCamera.StopAcquisition().
Property Documentation
CamerasCount
int AForge.Video.Ximea.XimeaCamera.CamerasCount static get
Get number of XIMEA camera connected to the system.
Referenced by XimeaSample.MainForm.MainForm_Load(), and AForge.Video.Ximea.XimeaVideoSource.Start().
IsAcquisitionStarted
bool AForge.Video.Ximea.XimeaCamera.IsAcquisitionStarted get
Specifies if camera's data acquisition is currently active for the opened camera (if any).
IsDeviceOpen
bool AForge.Video.Ximea.XimeaCamera.IsDeviceOpen get
Specifies if a camera is currently opened by the instance of the class.
DeviceID
int AForge.Video.Ximea.XimeaCamera.DeviceID get
ID of the the recently opened XIMEA camera.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Video.Ximea/XimeaCamera.cs