Doc: IGLib EXTENDED: SVSTest.StereoViewForm Class Reference
SVSTest.StereoViewForm Class Reference
Public Member Functions
StereoViewForm ()
void OnNewLeftFrame (object sender, ref Bitmap image)
void OnNewRightFrame (object sender, ref Bitmap image)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void StereoViewForm_FormClosing (object sender, FormClosingEventArgs e)
void stereoThread ()
delegate void UpdateWindowSizeCallback ()
void UpdateWindowSize ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
ManualResetEvent leftFrameIsAvailable
ManualResetEvent rightFrameIsAvailable
Thread backgroundThread
Bitmap leftFrame
Bitmap rightFrame
StereoAnaglyph stereoFilter = new StereoAnaglyph()
bool needToExit = false
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.PictureBox pictureBox
Constructor & Destructor Documentation
StereoViewForm()
SVSTest.StereoViewForm.StereoViewForm () inline
References SVSTest.StereoViewForm.backgroundThread, SVSTest.StereoViewForm.InitializeComponent(), SVSTest.StereoViewForm.leftFrameIsAvailable, SVSTest.StereoViewForm.rightFrameIsAvailable, and SVSTest.StereoViewForm.stereoThread().
Member Function Documentation
StereoViewForm_FormClosing()
void SVSTest.StereoViewForm.StereoViewForm_FormClosing (object sender, FormClosingEventArgs e) inline private
References SVSTest.StereoViewForm.backgroundThread, SVSTest.StereoViewForm.leftFrameIsAvailable, SVSTest.StereoViewForm.needToExit, and SVSTest.StereoViewForm.rightFrameIsAvailable.
Referenced by SVSTest.StereoViewForm.InitializeComponent().
OnNewLeftFrame()
void SVSTest.StereoViewForm.OnNewLeftFrame (object sender, ref Bitmap image) inline
References AForge.Imaging.Image.Clone(), SVSTest.StereoViewForm.leftFrame, and SVSTest.StereoViewForm.leftFrameIsAvailable.
Referenced by SVSTest.MainForm.showStereoButton_Click(), and SVSTest.MainForm.stereoViewForm_OnFormClosing().
OnNewRightFrame()
void SVSTest.StereoViewForm.OnNewRightFrame (object sender, ref Bitmap image) inline
References AForge.Imaging.Image.Clone(), SVSTest.StereoViewForm.rightFrame, and SVSTest.StereoViewForm.rightFrameIsAvailable.
Referenced by SVSTest.MainForm.showStereoButton_Click(), and SVSTest.MainForm.stereoViewForm_OnFormClosing().
stereoThread()
void SVSTest.StereoViewForm.stereoThread () inline private
References AForge.Imaging.Filters.BaseInPlaceFilter.Apply(), SVSTest.StereoViewForm.leftFrame, SVSTest.StereoViewForm.leftFrameIsAvailable, SVSTest.StereoViewForm.needToExit, AForge.Imaging.Filters.BaseInPlaceFilter2.OverlayImage, SVSTest.StereoViewForm.pictureBox, SVSTest.StereoViewForm.rightFrame, SVSTest.StereoViewForm.rightFrameIsAvailable, SVSTest.StereoViewForm.stereoFilter, and SVSTest.StereoViewForm.UpdateWindowSize().
Referenced by SVSTest.StereoViewForm.StereoViewForm().
UpdateWindowSizeCallback()
delegate void SVSTest.StereoViewForm.UpdateWindowSizeCallback () private
Referenced by SVSTest.StereoViewForm.UpdateWindowSize().
UpdateWindowSize()
void SVSTest.StereoViewForm.UpdateWindowSize () inline private
References SVSTest.StereoViewForm.leftFrame, SVSTest.StereoViewForm.pictureBox, SVSTest.StereoViewForm.rightFrame, and SVSTest.StereoViewForm.UpdateWindowSizeCallback().
Referenced by SVSTest.StereoViewForm.stereoThread().
Dispose()
override void SVSTest.StereoViewForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References SVSTest.StereoViewForm.components.
InitializeComponent()
void SVSTest.StereoViewForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References SVSTest.StereoViewForm.pictureBox, and SVSTest.StereoViewForm.StereoViewForm_FormClosing().
Referenced by SVSTest.StereoViewForm.StereoViewForm().
Member Data Documentation
leftFrameIsAvailable
ManualResetEvent SVSTest.StereoViewForm.leftFrameIsAvailable private
Referenced by SVSTest.StereoViewForm.OnNewLeftFrame(), SVSTest.StereoViewForm.stereoThread(), SVSTest.StereoViewForm.StereoViewForm(), and SVSTest.StereoViewForm.StereoViewForm_FormClosing().
rightFrameIsAvailable
ManualResetEvent SVSTest.StereoViewForm.rightFrameIsAvailable private
Referenced by SVSTest.StereoViewForm.OnNewRightFrame(), SVSTest.StereoViewForm.stereoThread(), SVSTest.StereoViewForm.StereoViewForm(), and SVSTest.StereoViewForm.StereoViewForm_FormClosing().
backgroundThread
Thread SVSTest.StereoViewForm.backgroundThread private
Referenced by SVSTest.StereoViewForm.StereoViewForm(), and SVSTest.StereoViewForm.StereoViewForm_FormClosing().
leftFrame
Bitmap SVSTest.StereoViewForm.leftFrame private
Referenced by SVSTest.StereoViewForm.OnNewLeftFrame(), SVSTest.StereoViewForm.stereoThread(), and SVSTest.StereoViewForm.UpdateWindowSize().
rightFrame
Bitmap SVSTest.StereoViewForm.rightFrame private
Referenced by SVSTest.StereoViewForm.OnNewRightFrame(), SVSTest.StereoViewForm.stereoThread(), and SVSTest.StereoViewForm.UpdateWindowSize().
stereoFilter
StereoAnaglyph SVSTest.StereoViewForm.stereoFilter = new StereoAnaglyph() private
Referenced by SVSTest.StereoViewForm.stereoThread().
needToExit
bool SVSTest.StereoViewForm.needToExit = false private
Referenced by SVSTest.StereoViewForm.stereoThread(), and SVSTest.StereoViewForm.StereoViewForm_FormClosing().
components
System.ComponentModel.IContainer SVSTest.StereoViewForm.components = null private
Required designer variable.
Referenced by SVSTest.StereoViewForm.Dispose().
pictureBox
System.Windows.Forms.PictureBox SVSTest.StereoViewForm.pictureBox private
Referenced by SVSTest.StereoViewForm.InitializeComponent(), SVSTest.StereoViewForm.stereoThread(), and SVSTest.StereoViewForm.UpdateWindowSize().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Robotics/Surveyor/SVSTest/StereoViewForm.cs
shelldev/lib_ann/aforge.net/Samples/Robotics/Surveyor/SVSTest/StereoViewForm.Designer.cs