Doc: IGLib EXTENDED: IG.Lib.LoadableScriptShellBase Class Reference
IG.Lib.LoadableScriptShellBase Class Reference
Loadable script base class for the shell application that includes tols for definition of optiimization problems, definition of vector response functions, a couple of interfaces with simulation programs, etc. AGREEMENTS: The first argument to initialization and executable method is working directory where data between different applications is exchanged. If overrigding the InitializeThis(...) method, call the base class' method first, and keep the agreement that the first argument must be the working directory. When implementing the executable (RunThis(...)) method, its first argument should also be the working directory (the same as for initialization). This is to enable use of the class in scenarios where initialization and execution arguments must be the same.
Classes
class StoredScriptSettings
In methods of this class you will find all the settings that apply to this script.
Public Member Functions
LoadableScriptShellBase ()
Constructor.
virtual bool RepairSimulationParameters (IVector parameters)
Repairs simulation parameters, if necessary, in such a way that values are consistent with simuation data (e.g. spacing of nodes).
virtual void SimulatorCalculateResponse (IResponseEvaluatorVectorSimple simulator, IVector inputParameters, ref IVector outputValues)
Calculates vector response by the specified simulator, and stores output values to the specified vector variable.
void SimulatorCalculateResponse (IVector parameters, ref IVector outputValues)
Calculates vector response by the main simulator of the script, and stores output values to the specified vector variable.
LoadableScriptShellBase ()
Public Member Functions inherited from IG.Lib.LoadableScriptOptShellBaseControllable
LoadableScriptOptShellBaseControllable ()
Creates a LoadableScriptOptBase object.
Public Member Functions inherited from IG.Lib.LoadableScriptOptBase
LoadableScriptOptBase ()
Creates the LoadableScriptOptBase object.
abstract void Analyse (IAnalysisResults anRes)
Performs direct analysis for optimization problems. This method must be overridden in derived classes where one wants to have direct analysis defined.
Public Member Functions inherited from IG.Lib.LoadableScriptBase
LoadableScriptBase ()
Argument-less constructor. If argument-less constructor is called then initialization is not performed and will be performed later.
string Run (string[] arguments)
Performs the action of this object. Override this in derived classes!
void Initialize (string[] arguments)
Initializes the object. If not called explicitly, this method is automatically called at the first call to the Run method.
virtual string Script_DefaultInitialize (string[] arguments)
Default initialization method for scripts.
virtual string Script_DefaultRun (string[] arguments)
Default run method for the script. Can be used when only installed commands are run by hte script.
virtual ICommandLineApplicationInterpreter Script_CreateInterpreterWithoutCommands ()
Creates and returns an interpreter that can be used as script's internal interpreter for running script's commands.
virtual void Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings)
Add wscript's internal commands to the specified interpreter.
delegate string Script_CommandDelegate (string[] args)
Delegate for commands that are installed on script's internal interpreter (property Script_Interpreter).
void Script_AddCommand (string commandName, Script_CommandDelegate command, string helpString)
Adds a new internal script command under specified name to the internal interpreter of the current script object.
virtual void Script_AddCommand (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings, string commandName, Script_CommandDelegate command, string helpString)
Adds a new internal script command under specified name to the internal interpreter of the current script object.
string Script_GetHelpString (string scriptCommandName)
Returns help string for internal script command with specified name, or null if help string is not installed for such a command.
void Script_PrintCommandsHelp ()
Prits help for the installed internal commands of the script.
virtual bool Script_ContainsCommand (string commandName)
Returns true if the internal script's interpreter contains a command with specified name, false otherwise.
virtual bool Script_ContainsScriptCommand (string commandName)
Returns true if the specified command is script command (i.e. its first argument is command-name and it is run through the Script_CommandAdapter object).
virtual void Script_RemoveCommand (string commandName)
Removes the specified internal script command from the internal interpreter of the current scripting object.
virtual void Script_RemoveAllCommands ()
Removes ALL internal script commands from the internal interpreter of the current scripting object.
string Script_Run (string[] arguments)
Runs internal script command.
string Script_Run (string commandName, params string[] otherArguments)
Runs internal script command.
virtual void Script_PrintArguments (string messageString, string[] arguments)
Prints the specified array of string arguments (usually passed as command-line arguments).
Protected Member Functions
override void InitializeThis (string[] arguments)
Inializes the current script object.
virtual void CreateNewSimulator (string simulatorPath, ref IResponseEvaluatorVectorSimple simulator)
Creates a new simulator that uses the specified simulator directory, and stores it to the specified variable.
override void InitializeThis (string[] arguments)
Inializes the current script object.
Protected Member Functions inherited from IG.Lib.LoadableScriptBase
delegate string CommandMethod (string commandName, string[] args)
Delegate for internal command methods.
abstract string RunThis (string[] arguments)
Performs the action of this object. Override this in derived classes!
ICommandLineApplicationInterpreter Script_CreateInterpreter ()
Creates and returns an interpreter that can be used as script's internal interpreter for running script's commands.
virtual string Script_CommandHelp (string[] arguments)
Prints help.
virtual string Script_CommandTestScript (string[] arguments)
Prints help.
Protected Attributes
IResponseEvaluatorVectorSimple _simulator
string _projectName
string _simulationName
Protected Attributes inherited from IG.Lib.LoadableScriptOptBase
StopWatch1 _timer = null
bool _checkOptimizationDirectoryExistence = true
Whether to check existence of optimization directory when set. Also applies to working directory.
Protected Attributes inherited from IG.Lib.LoadableScriptBase
string _embeddedCommandName = null
int _outputLevel = DefaultOutputLevel
ICommandLineApplicationInterpreter _script_interpreter
Properties
abstract IResponseEvaluatorVectorSimple Simulator [get, protected set]
Simulator that is used to calculate vector response.
virtual bool SimulatorSuppressOutput [get, set]
A flag indicating whether simulators should suppress output or not, default is false.
virtual string ProjectName [get, set, protected set]
Name of the current project, used in some simulation and other interfaces.
virtual string SimulationName [get, set, protected set]
Name of the current simulation, used in some simulation and other interfaces.
string CastingRobertProjectName [get, set]
Project name for interfacing Robert Vertnik's casting simulator.
string CastingRobertSimulationName [get, set]
Simulation name for interfacing Robert Vertnik's casting simulator.
string CastingRobertRootDirectory [get, set]
Root directory for casting simulator.
SimCastingRobertFileManager CastingRobertFileManager [get, set]
File manager for interfacing Robert Vertnik's casting simulator. Lazy evaluation: The object is created when first accessed, if possible. For this, ProjectName, SimulationName and CastingRobertRootDirectory must be defined.
Properties inherited from IG.Lib.LoadableScriptOptShellBaseControllable
bool IsLoadable [get, set]
Either or not the script can be dynamically loaded.
bool IsRunnable [get, set]
Either or not the script can be run (some scripts only support other tasks).
Properties inherited from IG.Lib.LoadableScriptOptBase
StopWatch1 Timer [get]
virtual IRandomGenerator Random [get, protected set]
Random generator used by the current object.
virtual string OptimizationDirectory [get, set]
Optimization directory. This directory is a base directory for data used optimization and neural network - based approximation servers and for other directories that contain data for specific tasks.
virtual string WorkingDirectory [get, set]
Working directory. This directory is a base directory for data used by the script. It is usually obtained as parent directory of the optimization directory.
virtual IAnalysis Analysis [get, protected set]
Direct analysis object used in optimization. Initialized when first accessed with the embedded class, whose analysis function calls Analyse(...).
Properties inherited from IG.Lib.LoadableScriptBase
string EmbeddedCommandName [get, set]
Command that was used to launch the current embedded application script.
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
string[] InitializationArguments [get, set]
Arguments used by the initialization method. WARNING: arguments can only be set before initialization is performed. Initialization is performed either implicitly at the first call to the Run method or explicitly by calling the Initialize method.
virtual bool IsInitialized [get, protected set]
Whether the object has been initialized or not.
static int DefaultOutputLevel [get, set]
int OutputLevel [get, set]
Level of output to console produced by some operations of the current object.
virtual ICommandLineApplicationInterpreter Script_Interpreter [get, protected set]
Script's internal interpreter that takes care for execution of installed internal commands.
SortedList< string, string > Script_CommandHelpStrings [get]
Contains help strings associated with script commands installed on interpreter.
Properties inherited from IG.Lib.ILoadableScript
string EmbeddedCommandName [get, set]
Command that was used to launch the current embedded application script.
string[] InitializationArguments [get, set]
Arguments used by the initialization method.
bool IsInitialized [get]
Whether the object has been initialized or not.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Properties inherited from IG.Lib.ILoadableScriptC
bool IsLoadable [get, set]
Either or not the script can be dynamically loaded.
bool IsRunnable [get, set]
Either or not the script can be run (some scripts only support other tasks).
Private Attributes
bool _simulatorSuppressOutput = false
SimCastingRobertFileManager _CastingRobertFilemanager
string _castingRobertRootDirectory
string _castingRobertProjectName
string _castingRobertSimulationName
Additional Inherited Members
Static Public Attributes inherited from IG.Lib.LoadableScriptBase
const string ConstDefaultHelp = "Help"
Default command name for help.
const string ConstHelpDefaultUniversal = "?"
Universal name of the help command.
const string ConstDefaultTestScrip = "TestScript"
Default command name for test method.
Detailed Description
Loadable script base class for the shell application that includes tols for definition of optiimization problems, definition of vector response functions, a couple of interfaces with simulation programs, etc. AGREEMENTS: The first argument to initialization and executable method is working directory where data between different applications is exchanged. If overrigding the InitializeThis(...) method, call the base class' method first, and keep the agreement that the first argument must be the working directory. When implementing the executable (RunThis(...)) method, its first argument should also be the working directory (the same as for initialization). This is to enable use of the class in scenarios where initialization and execution arguments must be the same.
$A Igor Aug11;
Constructor & Destructor Documentation
LoadableScriptShellBase() [1/2]
IG.Lib.LoadableScriptShellBase.LoadableScriptShellBase () inline
Constructor.
LoadableScriptShellBase() [2/2]
IG.Lib.LoadableScriptShellBase.LoadableScriptShellBase () inline
Member Function Documentation
InitializeThis() [1/2]
override void IG.Lib.LoadableScriptShellBase.InitializeThis (string[] arguments) inline protected virtual
Inializes the current script object.
Parameters
arguments Initialization arguments. The first argument must be the working directory path.
Reimplemented from IG.Lib.LoadableScriptOptShellBaseControllable.
Reimplemented in IG.Script.S_12_09_jmatpro, IG.Script.S_12_09_jmatpro, IG.Script.LoadableScriptShellNeuralBase, IG.Script.LoadableScriptShellNeuralITOriginalBase, IG.Script.LoadableScriptShellNeural, IG.Script.S_11_10_clanek_neural_00, IG.Script.Script_11_10_clanek_neural_01, IG.Script.LoadableScriptShellNeuralIT, IG.Script.S_12_01_Paper_NeuralOptCasting_00, IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00, IG.Script.S_12_02_paper_neural_process_chain_model, IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00, IG.Script.S_12_02_paper_neural_process_chain_model, IG.Script.S_12_03_paper_gk, IG.Script.S_13_5_Convection, and IG.Script.S_13_7_ConvectionRev1.
CreateNewSimulator()
virtual void IG.Lib.LoadableScriptShellBase.CreateNewSimulator (string simulatorPath, ref IResponseEvaluatorVectorSimple simulator) inline protected virtual
Creates a new simulator that uses the specified simulator directory, and stores it to the specified variable.
This method always creates simulator anew, regardless of whether the variable to hold it is already assigned.
Parameters
simulatorPath Path to the simulator directory.
simuator Variable where the created simulator is stored.
In many scripts, it is this method that sould be overridden in order to sort out everything with respect to simulator creation.
Reimplemented in IG.Script.S_12_03_paper_gk.
Referenced by IG.Script.LoadableScriptShellNeuralITOriginalBase.ParSimGetSimulator(), and IG.Script.LoadableScriptShellNeuralBase.ParSimGetSimulator().
RepairSimulationParameters()
virtual bool IG.Lib.LoadableScriptShellBase.RepairSimulationParameters (IVector parameters) inline virtual
Repairs simulation parameters, if necessary, in such a way that values are consistent with simuation data (e.g. spacing of nodes).
Parameters
parameters Vector of parameters to be repaired. Repaired values are stored in the same vector.
Returns
true if parameters were corrected, false otherwise.
This method should be overridden in the derived classes, in the case that reparation can actual take place. The base class method does nothing (it only returns false).
Reimplemented in IG.Script.S_12_03_paper_gk.
Referenced by IG.Lib.LoadableScriptShellBase.SimulatorCalculateResponse().
SimulatorCalculateResponse() [1/2]
virtual void IG.Lib.LoadableScriptShellBase.SimulatorCalculateResponse (IResponseEvaluatorVectorSimple simulator, IVector inputParameters, ref IVector outputValues) inline virtual
Calculates vector response by the specified simulator, and stores output values to the specified vector variable.
Parameters
simulator Simulator used to calculate the response.
inputParameters Vector of input parameters.<paramparam name="outputValues">Variable where the calculated response (output values) is stored.</paramparam>
This method is seldom overridden in derived classes because it does everything it is expected to do. The method calls the RepairSimulationParameters method, which is often overridden in derived classes. Warning message is written to console if vectr of input parameters had to be repaired.
References IG.Num.IResponseEvaluatorVectorSimple.CalculateVectorResponse(), and IG.Lib.LoadableScriptShellBase.RepairSimulationParameters().
Referenced by IG.Script.LoadableScriptShellNeuralITOriginalBase.ParSimRunJob(), IG.Script.LoadableScriptShellNeuralBase.ParSimRunJob(), IG.Lib.LoadableScriptShellBase.SimulatorCalculateResponse(), and IG.Script.S_12_03_paper_gk.TestSimulator().
SimulatorCalculateResponse() [2/2]
void IG.Lib.LoadableScriptShellBase.SimulatorCalculateResponse (IVector parameters, ref IVector outputValues) inline
Calculates vector response by the main simulator of the script, and stores output values to the specified vector variable.
Parameters
inputParameters Vector of input parameters.<paramparam name="outputValues">Variable where the calculated response (output values) is stored.</paramparam>
This method can not be overridden in derived classes, but its overload where simulator is an argument, can be overridden.
References IG.Lib.LoadableScriptShellBase.Simulator, and IG.Lib.LoadableScriptShellBase.SimulatorCalculateResponse().
InitializeThis() [2/2]
override void IG.Lib.LoadableScriptShellBase.InitializeThis (string[] arguments) inline protected virtual
Inializes the current script object.
Parameters
arguments Initialization arguments. The first argument must be the working directory path.
Reimplemented from IG.Lib.LoadableScriptOptShellBaseControllable.
Reimplemented in IG.Script.LoadableScriptShellNeuralITOriginalBase, and IG.Script.LoadableScriptShellNeuralIT.
Member Data Documentation
_simulator
IResponseEvaluatorVectorSimple IG.Lib.LoadableScriptShellBase._simulator protected
_simulatorSuppressOutput
bool IG.Lib.LoadableScriptShellBase._simulatorSuppressOutput = false private
_projectName
string IG.Lib.LoadableScriptShellBase._projectName protected
_simulationName
string IG.Lib.LoadableScriptShellBase._simulationName protected
_CastingRobertFilemanager
SimCastingRobertFileManager IG.Lib.LoadableScriptShellBase._CastingRobertFilemanager private
_castingRobertRootDirectory
string IG.Lib.LoadableScriptShellBase._castingRobertRootDirectory private
_castingRobertProjectName
string IG.Lib.LoadableScriptShellBase._castingRobertProjectName private
_castingRobertSimulationName
string IG.Lib.LoadableScriptShellBase._castingRobertSimulationName private
Property Documentation
Simulator
abstract IResponseEvaluatorVectorSimple IG.Lib.LoadableScriptShellBase.Simulator get protected set
Simulator that is used to calculate vector response.
Referenced by IG.Lib.LoadableScriptShellBase.SimulatorCalculateResponse().
SimulatorSuppressOutput
virtual bool IG.Lib.LoadableScriptShellBase.SimulatorSuppressOutput get set
A flag indicating whether simulators should suppress output or not, default is false.
Current value of this flag affects newly created simulators (usually this is implemented in the CreateNewSimulator method).
Not all simulator interfaces support suppressing output, therefore for some simulator this flag has no effect.
Referenced by IG.Script.S_12_03_paper_gk.CreateNewSimulator().
ProjectName
string IG.Lib.LoadableScriptShellBase.ProjectName get set protected set
Name of the current project, used in some simulation and other interfaces.
SimulationName
string IG.Lib.LoadableScriptShellBase.SimulationName get set protected set
Name of the current simulation, used in some simulation and other interfaces.
CastingRobertProjectName
string IG.Lib.LoadableScriptShellBase.CastingRobertProjectName get set
Project name for interfacing Robert Vertnik's casting simulator.
CastingRobertSimulationName
string IG.Lib.LoadableScriptShellBase.CastingRobertSimulationName get set
Simulation name for interfacing Robert Vertnik's casting simulator.
CastingRobertRootDirectory
string IG.Lib.LoadableScriptShellBase.CastingRobertRootDirectory get set
Root directory for casting simulator.
CastingRobertFileManager
SimCastingRobertFileManager IG.Lib.LoadableScriptShellBase.CastingRobertFileManager get set
File manager for interfacing Robert Vertnik's casting simulator. Lazy evaluation: The object is created when first accessed, if possible. For this, ProjectName, SimulationName and CastingRobertRootDirectory must be defined.
The documentation for this class was generated from the following files:
iglib/extensions/iglibneural/neural/scripts_base/ScriptShellBase.cs
shelldev/extensions_shell/shell/Shell/optimization/LoadableScriptShell.cs