Doc: IGLib EXTENDED: Classifier.MainForm Class Reference
Classifier.MainForm Class Reference
Summary description for Form1.
Public Member Functions
MainForm ()
MainForm ()
MainForm ()
MainForm ()
MainForm ()
MainForm ()
MainForm ()
MainForm ()
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void loadButton_Click (object sender, System.EventArgs e)
void UpdateSettings ()
void UpdateDataListView ()
void oneNeuronForTwoCheck_CheckedChanged (object sender, System.EventArgs e)
void EnableControls (bool enable)
void ClearSolution ()
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void loadButton_Click (object sender, System.EventArgs e)
void UpdateSettings ()
void UpdateDataListView ()
void oneNeuronForTwoCheck_CheckedChanged (object sender, System.EventArgs e)
void EnableControls (bool enable)
void ClearSolution ()
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void loadButton_Click (object sender, System.EventArgs e)
void UpdateSettings ()
void ShowTrainingData ()
void EnableControls (bool enable)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void MainForm_Load (object sender, System.EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void loadButton_Click (object sender, System.EventArgs e)
void UpdateSettings ()
void ShowTrainingData ()
void EnableControls (bool enable)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void MainForm_Load (object sender, System.EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void loadButton_Click (object sender, System.EventArgs e)
void UpdateSettings ()
void UpdateDataListView ()
void ShowTrainingData ()
void EnableControls (bool enable)
void ClearCurrentSolution ()
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void loadButton_Click (object sender, System.EventArgs e)
void UpdateSettings ()
void UpdateDataListView ()
void ShowTrainingData ()
void EnableControls (bool enable)
void ClearCurrentSolution ()
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
delegate void SetTextCallback (System.Windows.Forms.Control control, string text)
delegate void ClearListCallback (System.Windows.Forms.ListView control)
delegate ListViewItem AddListItemCallback (System.Windows.Forms.ListView control, string itemText)
delegate void AddListSubitemCallback (ListViewItem item, string subItemText)
void SetText (System.Windows.Forms.Control control, string text)
void ClearList (System.Windows.Forms.ListView control)
ListViewItem AddListItem (System.Windows.Forms.ListView control, string itemText)
void AddListSubitem (ListViewItem item, string subItemText)
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void loadButton_Click (object sender, System.EventArgs e)
void UpdateSettings ()
void UpdateDataListView ()
void oneNeuronForTwoCheck_CheckedChanged (object sender, System.EventArgs e)
delegate void EnableCallback (bool enable)
void EnableControls (bool enable)
void ClearSolution ()
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
delegate void SetTextCallback (System.Windows.Forms.Control control, string text)
delegate void ClearListCallback (System.Windows.Forms.ListView control)
delegate ListViewItem AddListItemCallback (System.Windows.Forms.ListView control, string itemText)
delegate void AddListSubitemCallback (ListViewItem item, string subItemText)
void SetText (System.Windows.Forms.Control control, string text)
void ClearList (System.Windows.Forms.ListView control)
ListViewItem AddListItem (System.Windows.Forms.ListView control, string itemText)
void AddListSubitem (ListViewItem item, string subItemText)
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void loadButton_Click (object sender, System.EventArgs e)
void UpdateSettings ()
void ShowTrainingData ()
delegate void EnableCallback (bool enable)
void EnableControls (bool enable)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
delegate void SetTextCallback (System.Windows.Forms.Control control, string text)
delegate void ClearListCallback (System.Windows.Forms.ListView control)
delegate ListViewItem AddListItemCallback (System.Windows.Forms.ListView control, string itemText)
delegate void AddListSubitemCallback (ListViewItem item, string subItemText)
void SetText (System.Windows.Forms.Control control, string text)
void ClearList (System.Windows.Forms.ListView control)
ListViewItem AddListItem (System.Windows.Forms.ListView control, string itemText)
void AddListSubitem (ListViewItem item, string subItemText)
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void loadButton_Click (object sender, System.EventArgs e)
void UpdateSettings ()
void UpdateDataListView ()
void ShowTrainingData ()
delegate void EnableCallback (bool enable)
void EnableControls (bool enable)
void ClearCurrentSolution ()
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
Static Private Member Functions
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
Private Attributes
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.Button loadButton
System.Windows.Forms.OpenFileDialog openFileDialog
System.Windows.Forms.ListView dataList
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.TextBox learningRateBox
System.Windows.Forms.Label label1
System.Windows.Forms.Label label2
System.Windows.Forms.TextBox alphaBox
System.Windows.Forms.Label label3
System.Windows.Forms.TextBox errorLimitBox
System.Windows.Forms.Label label4
System.Windows.Forms.TextBox iterationsBox
System.Windows.Forms.Label label5
System.Windows.Forms.Label label6
System.Windows.Forms.TextBox neuronsBox
System.Windows.Forms.CheckBox oneNeuronForTwoCheck
System.Windows.Forms.Label label7
System.Windows.Forms.Label label8
System.Windows.Forms.TextBox currentIterationBox
System.Windows.Forms.Button stopButton
System.Windows.Forms.Button startButton
System.Windows.Forms.Label label9
System.Windows.Forms.Label label10
System.Windows.Forms.TextBox classesBox
System.Windows.Forms.CheckBox errorLimitCheck
System.Windows.Forms.Label label11
System.Windows.Forms.TextBox currentErrorBox
System.Windows.Forms.GroupBox groupBox3
System.Windows.Forms.Label label12
System.Windows.Forms.ListView weightsList
System.Windows.Forms.Label label13
System.Windows.Forms.ColumnHeader columnHeader1
System.Windows.Forms.ColumnHeader columnHeader2
System.Windows.Forms.ColumnHeader columnHeader3
System.Windows.Forms.CheckBox saveFilesCheck
AForge.Controls.Chart errorChart
System.ComponentModel.Container components = null
Required designer variable.
int samples = 0
int variables = 0
double[,] data = null
int[] classes = null
int classesCount = 0
int[] samplesPerClass = null
int neuronsCount = 0
double learningRate = 0.1
double sigmoidAlphaValue = 2.0
double learningErrorLimit = 0.1
double iterationLimit = 1000
bool useOneNeuronForTwoClasses = false
bool useErrorLimit = true
bool saveStatisticsToFiles = false
Thread workerThread = null
bool needToStop = false
AForge.Controls.Chart chart
System.Windows.Forms.Label noVisualizationLabel
volatile bool needToStop = false
Static Private Attributes
static Color[] dataSereisColors
Detailed Description
Summary description for Form1.
Constructor & Destructor Documentation
MainForm() [1/9]
Classifier.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), Classifier.MainForm.errorChart, Classifier.MainForm.InitializeComponent(), and Classifier.MainForm.UpdateSettings().
Referenced by Classifier.MainForm.Main().
MainForm() [2/9]
Classifier.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), Classifier.MainForm.errorChart, Classifier.MainForm.InitializeComponent(), and Classifier.MainForm.UpdateSettings().
MainForm() [3/9]
Classifier.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), Classifier.MainForm.errorChart, Classifier.MainForm.InitializeComponent(), Classifier.MainForm.saveFilesCheck, Classifier.MainForm.saveStatisticsToFiles, and Classifier.MainForm.UpdateSettings().
MainForm() [4/9]
Classifier.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), Classifier.MainForm.errorChart, Classifier.MainForm.InitializeComponent(), Classifier.MainForm.saveFilesCheck, Classifier.MainForm.saveStatisticsToFiles, and Classifier.MainForm.UpdateSettings().
MainForm() [5/9]
Classifier.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), Classifier.MainForm.chart, Classifier.MainForm.errorChart, Classifier.MainForm.InitializeComponent(), Classifier.MainForm.saveFilesCheck, Classifier.MainForm.saveStatisticsToFiles, and Classifier.MainForm.UpdateSettings().
MainForm() [6/9]
Classifier.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), Classifier.MainForm.chart, Classifier.MainForm.errorChart, Classifier.MainForm.InitializeComponent(), Classifier.MainForm.saveFilesCheck, Classifier.MainForm.saveStatisticsToFiles, and Classifier.MainForm.UpdateSettings().
MainForm() [7/9]
Classifier.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), Classifier.MainForm.errorChart, Classifier.MainForm.InitializeComponent(), and Classifier.MainForm.UpdateSettings().
MainForm() [8/9]
Classifier.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), Classifier.MainForm.errorChart, Classifier.MainForm.InitializeComponent(), Classifier.MainForm.saveFilesCheck, Classifier.MainForm.saveStatisticsToFiles, and Classifier.MainForm.UpdateSettings().
MainForm() [9/9]
Classifier.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), Classifier.MainForm.chart, Classifier.MainForm.errorChart, Classifier.MainForm.InitializeComponent(), Classifier.MainForm.saveFilesCheck, Classifier.MainForm.saveStatisticsToFiles, and Classifier.MainForm.UpdateSettings().
Member Function Documentation
Dispose() [1/9]
override void Classifier.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References Classifier.MainForm.components.
InitializeComponent() [1/9]
void Classifier.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by Classifier.MainForm.MainForm().
Main() [1/9]
static void Classifier.MainForm.Main () inline static private
The main entry point for the application.
References Classifier.MainForm.MainForm().
MainForm_Closing() [1/9]
void Classifier.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References Classifier.MainForm.needToStop, and Classifier.MainForm.workerThread.
loadButton_Click() [1/9]
void Classifier.MainForm.loadButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.classes, Classifier.MainForm.classesBox, Classifier.MainForm.classesCount, Classifier.MainForm.ClearSolution(), Classifier.MainForm.data, Classifier.MainForm.neuronsBox, Classifier.MainForm.neuronsCount, Classifier.MainForm.oneNeuronForTwoCheck, Classifier.MainForm.openFileDialog, Classifier.MainForm.samples, Classifier.MainForm.samplesPerClass, Classifier.MainForm.startButton, Classifier.MainForm.UpdateDataListView(), Classifier.MainForm.useOneNeuronForTwoClasses, and Classifier.MainForm.variables.
UpdateSettings() [1/9]
void Classifier.MainForm.UpdateSettings () inline private
References Classifier.MainForm.alphaBox, Classifier.MainForm.errorLimitBox, Classifier.MainForm.errorLimitCheck, Classifier.MainForm.iterationLimit, Classifier.MainForm.iterationsBox, Classifier.MainForm.learningErrorLimit, Classifier.MainForm.learningRate, Classifier.MainForm.learningRateBox, Classifier.MainForm.oneNeuronForTwoCheck, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.saveStatisticsToFiles, Classifier.MainForm.sigmoidAlphaValue, Classifier.MainForm.useErrorLimit, and Classifier.MainForm.useOneNeuronForTwoClasses.
Referenced by Classifier.MainForm.MainForm(), and Classifier.MainForm.startButton_Click().
UpdateDataListView() [1/6]
void Classifier.MainForm.UpdateDataListView () inline private
References Classifier.MainForm.classes, Classifier.MainForm.data, Classifier.MainForm.dataList, Classifier.MainForm.samples, and Classifier.MainForm.variables.
Referenced by Classifier.MainForm.loadButton_Click().
oneNeuronForTwoCheck_CheckedChanged() [1/3]
void Classifier.MainForm.oneNeuronForTwoCheck_CheckedChanged (object sender, System.EventArgs e) inline private
References Classifier.MainForm.classesCount, Classifier.MainForm.neuronsBox, Classifier.MainForm.neuronsCount, Classifier.MainForm.oneNeuronForTwoCheck, and Classifier.MainForm.useOneNeuronForTwoClasses.
EnableControls() [1/9]
void Classifier.MainForm.EnableControls (bool enable) inline private
References Classifier.MainForm.alphaBox, Classifier.MainForm.classesCount, Classifier.MainForm.errorLimitBox, Classifier.MainForm.errorLimitCheck, Classifier.MainForm.iterationsBox, Classifier.MainForm.learningRateBox, Classifier.MainForm.loadButton, Classifier.MainForm.oneNeuronForTwoCheck, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.startButton, and Classifier.MainForm.stopButton.
Referenced by Classifier.MainForm.EnableControls(), Classifier.MainForm.SearchSolution(), and Classifier.MainForm.startButton_Click().
ClearSolution() [1/3]
void Classifier.MainForm.ClearSolution () inline private
References Classifier.MainForm.currentErrorBox, Classifier.MainForm.currentIterationBox, Classifier.MainForm.errorChart, AForge.Controls.Chart.UpdateDataSeries(), and Classifier.MainForm.weightsList.
Referenced by Classifier.MainForm.loadButton_Click().
startButton_Click() [1/9]
void Classifier.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.alphaBox, Classifier.MainForm.EnableControls(), Classifier.MainForm.errorLimitBox, Classifier.MainForm.errorLimitCheck, Classifier.MainForm.iterationLimit, Classifier.MainForm.iterationsBox, Classifier.MainForm.learningErrorLimit, Classifier.MainForm.learningRate, Classifier.MainForm.learningRateBox, Classifier.MainForm.needToStop, Classifier.MainForm.oneNeuronForTwoCheck, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.saveStatisticsToFiles, Classifier.MainForm.SearchSolution(), Classifier.MainForm.sigmoidAlphaValue, Classifier.MainForm.UpdateSettings(), Classifier.MainForm.useErrorLimit, Classifier.MainForm.useOneNeuronForTwoClasses, and Classifier.MainForm.workerThread.
stopButton_Click() [1/9]
void Classifier.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.needToStop, and Classifier.MainForm.workerThread.
SearchSolution() [1/9]
void Classifier.MainForm.SearchSolution () inline private
References Classifier.MainForm.classes, Classifier.MainForm.classesCount, Classifier.MainForm.currentErrorBox, Classifier.MainForm.currentIterationBox, Classifier.MainForm.data, Classifier.MainForm.EnableControls(), Classifier.MainForm.errorChart, Classifier.MainForm.iterationLimit, Classifier.MainForm.learningErrorLimit, AForge.Neuro.Learning.DeltaRuleLearning.LearningRate, Classifier.MainForm.learningRate, Classifier.MainForm.needToStop, Classifier.MainForm.neuronsCount, AForge.Controls.Chart.RangeX, AForge.Neuro.Learning.DeltaRuleLearning.RunEpoch(), Classifier.MainForm.samples, Classifier.MainForm.saveStatisticsToFiles, Classifier.MainForm.sigmoidAlphaValue, AForge.Controls.Chart.UpdateDataSeries(), Classifier.MainForm.useErrorLimit, Classifier.MainForm.useOneNeuronForTwoClasses, Classifier.MainForm.variables, and Classifier.MainForm.weightsList.
Referenced by Classifier.MainForm.startButton_Click().
Dispose() [2/9]
override void Classifier.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References Classifier.MainForm.components.
InitializeComponent() [2/9]
void Classifier.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [2/9]
static void Classifier.MainForm.Main () inline static private
The main entry point for the application.
References Classifier.MainForm.MainForm().
MainForm_Closing() [2/9]
void Classifier.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References Classifier.MainForm.needToStop, and Classifier.MainForm.workerThread.
loadButton_Click() [2/9]
void Classifier.MainForm.loadButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.classes, Classifier.MainForm.classesBox, Classifier.MainForm.classesCount, Classifier.MainForm.ClearSolution(), Classifier.MainForm.data, Classifier.MainForm.neuronsBox, Classifier.MainForm.neuronsCount, Classifier.MainForm.oneNeuronForTwoCheck, Classifier.MainForm.openFileDialog, Classifier.MainForm.samples, Classifier.MainForm.samplesPerClass, Classifier.MainForm.startButton, Classifier.MainForm.UpdateDataListView(), Classifier.MainForm.useOneNeuronForTwoClasses, and Classifier.MainForm.variables.
UpdateSettings() [2/9]
void Classifier.MainForm.UpdateSettings () inline private
References Classifier.MainForm.alphaBox, Classifier.MainForm.errorLimitBox, Classifier.MainForm.errorLimitCheck, Classifier.MainForm.iterationLimit, Classifier.MainForm.iterationsBox, Classifier.MainForm.learningErrorLimit, Classifier.MainForm.learningRate, Classifier.MainForm.learningRateBox, Classifier.MainForm.oneNeuronForTwoCheck, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.saveStatisticsToFiles, Classifier.MainForm.sigmoidAlphaValue, Classifier.MainForm.useErrorLimit, and Classifier.MainForm.useOneNeuronForTwoClasses.
UpdateDataListView() [2/6]
void Classifier.MainForm.UpdateDataListView () inline private
References Classifier.MainForm.classes, Classifier.MainForm.data, Classifier.MainForm.dataList, Classifier.MainForm.samples, and Classifier.MainForm.variables.
oneNeuronForTwoCheck_CheckedChanged() [2/3]
void Classifier.MainForm.oneNeuronForTwoCheck_CheckedChanged (object sender, System.EventArgs e) inline private
References Classifier.MainForm.classesCount, Classifier.MainForm.neuronsBox, Classifier.MainForm.neuronsCount, Classifier.MainForm.oneNeuronForTwoCheck, and Classifier.MainForm.useOneNeuronForTwoClasses.
EnableControls() [2/9]
void Classifier.MainForm.EnableControls (bool enable) inline private
References Classifier.MainForm.alphaBox, Classifier.MainForm.classesCount, Classifier.MainForm.errorLimitBox, Classifier.MainForm.errorLimitCheck, Classifier.MainForm.iterationsBox, Classifier.MainForm.learningRateBox, Classifier.MainForm.loadButton, Classifier.MainForm.oneNeuronForTwoCheck, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.startButton, and Classifier.MainForm.stopButton.
ClearSolution() [2/3]
void Classifier.MainForm.ClearSolution () inline private
References Classifier.MainForm.currentErrorBox, Classifier.MainForm.currentIterationBox, Classifier.MainForm.errorChart, AForge.Controls.Chart.UpdateDataSeries(), and Classifier.MainForm.weightsList.
startButton_Click() [2/9]
void Classifier.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.alphaBox, Classifier.MainForm.EnableControls(), Classifier.MainForm.errorLimitBox, Classifier.MainForm.errorLimitCheck, Classifier.MainForm.iterationLimit, Classifier.MainForm.iterationsBox, Classifier.MainForm.learningErrorLimit, Classifier.MainForm.learningRate, Classifier.MainForm.learningRateBox, Classifier.MainForm.needToStop, Classifier.MainForm.oneNeuronForTwoCheck, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.saveStatisticsToFiles, Classifier.MainForm.SearchSolution(), Classifier.MainForm.sigmoidAlphaValue, Classifier.MainForm.UpdateSettings(), Classifier.MainForm.useErrorLimit, Classifier.MainForm.useOneNeuronForTwoClasses, and Classifier.MainForm.workerThread.
stopButton_Click() [2/9]
void Classifier.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.needToStop, and Classifier.MainForm.workerThread.
SearchSolution() [2/9]
void Classifier.MainForm.SearchSolution () inline private
References Classifier.MainForm.classes, Classifier.MainForm.classesCount, Classifier.MainForm.currentErrorBox, Classifier.MainForm.currentIterationBox, Classifier.MainForm.data, Classifier.MainForm.EnableControls(), Classifier.MainForm.errorChart, Classifier.MainForm.iterationLimit, Classifier.MainForm.learningErrorLimit, AForge.Neuro.Learning.DeltaRuleLearning.LearningRate, Classifier.MainForm.learningRate, Classifier.MainForm.needToStop, Classifier.MainForm.neuronsCount, AForge.Controls.Chart.RangeX, AForge.Neuro.Learning.DeltaRuleLearning.RunEpoch(), Classifier.MainForm.samples, Classifier.MainForm.saveStatisticsToFiles, Classifier.MainForm.sigmoidAlphaValue, AForge.Controls.Chart.UpdateDataSeries(), Classifier.MainForm.useErrorLimit, Classifier.MainForm.useOneNeuronForTwoClasses, Classifier.MainForm.variables, and Classifier.MainForm.weightsList.
Dispose() [3/9]
override void Classifier.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References Classifier.MainForm.components.
InitializeComponent() [3/9]
void Classifier.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [3/9]
static void Classifier.MainForm.Main () inline static private
The main entry point for the application.
References Classifier.MainForm.MainForm().
MainForm_Closing() [3/9]
void Classifier.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References Classifier.MainForm.needToStop, and Classifier.MainForm.workerThread.
loadButton_Click() [3/9]
void Classifier.MainForm.loadButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.chart, Classifier.MainForm.classes, Classifier.MainForm.classesCount, Classifier.MainForm.data, Classifier.MainForm.errorChart, Classifier.MainForm.openFileDialog, AForge.Controls.Chart.RangeX, Classifier.MainForm.samples, Classifier.MainForm.samplesPerClass, Classifier.MainForm.ShowTrainingData(), Classifier.MainForm.startButton, AForge.Controls.Chart.UpdateDataSeries(), and Classifier.MainForm.weightsList.
UpdateSettings() [3/9]
void Classifier.MainForm.UpdateSettings () inline private
References Classifier.MainForm.learningRate, and Classifier.MainForm.learningRateBox.
ShowTrainingData() [1/6]
void Classifier.MainForm.ShowTrainingData () inline private
References AForge.Controls.Chart.AddDataSeries(), Classifier.MainForm.chart, Classifier.MainForm.classes, Classifier.MainForm.classesCount, Classifier.MainForm.data, Classifier.MainForm.dataSereisColors, AForge.Controls.Chart.RemoveAllDataSeries(), Classifier.MainForm.samples, Classifier.MainForm.samplesPerClass, and AForge.Controls.Chart.UpdateDataSeries().
Referenced by Classifier.MainForm.loadButton_Click().
EnableControls() [3/9]
void Classifier.MainForm.EnableControls (bool enable) inline private
References Classifier.MainForm.learningRateBox, Classifier.MainForm.loadButton, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.startButton, and Classifier.MainForm.stopButton.
startButton_Click() [3/9]
void Classifier.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.EnableControls(), Classifier.MainForm.learningRate, Classifier.MainForm.learningRateBox, Classifier.MainForm.needToStop, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.saveStatisticsToFiles, Classifier.MainForm.SearchSolution(), Classifier.MainForm.UpdateSettings(), and Classifier.MainForm.workerThread.
stopButton_Click() [3/9]
void Classifier.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.needToStop, and Classifier.MainForm.workerThread.
SearchSolution() [3/9]
void Classifier.MainForm.SearchSolution () inline private
References Classifier.MainForm.chart, Classifier.MainForm.classes, Classifier.MainForm.classesCount, Classifier.MainForm.data, Classifier.MainForm.EnableControls(), Classifier.MainForm.errorChart, Classifier.MainForm.iterationsBox, AForge.Neuro.Learning.PerceptronLearning.LearningRate, Classifier.MainForm.learningRate, AForge.DoubleRange.Max, AForge.DoubleRange.Min, Classifier.MainForm.needToStop, AForge.Controls.Chart.RangeX, AForge.Neuro.Learning.PerceptronLearning.RunEpoch(), Classifier.MainForm.samples, Classifier.MainForm.saveStatisticsToFiles, AForge.Controls.Chart.UpdateDataSeries(), and Classifier.MainForm.weightsList.
MainForm_Load() [1/2]
void Classifier.MainForm.MainForm_Load (object sender, System.EventArgs e) inline private
Dispose() [4/9]
override void Classifier.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References Classifier.MainForm.components.
InitializeComponent() [4/9]
void Classifier.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [4/9]
static void Classifier.MainForm.Main () inline static private
The main entry point for the application.
References Classifier.MainForm.MainForm().
MainForm_Closing() [4/9]
void Classifier.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References Classifier.MainForm.needToStop, and Classifier.MainForm.workerThread.
loadButton_Click() [4/9]
void Classifier.MainForm.loadButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.chart, Classifier.MainForm.classes, Classifier.MainForm.classesCount, Classifier.MainForm.data, Classifier.MainForm.errorChart, Classifier.MainForm.openFileDialog, AForge.Controls.Chart.RangeX, Classifier.MainForm.samples, Classifier.MainForm.samplesPerClass, Classifier.MainForm.ShowTrainingData(), Classifier.MainForm.startButton, AForge.Controls.Chart.UpdateDataSeries(), and Classifier.MainForm.weightsList.
UpdateSettings() [4/9]
void Classifier.MainForm.UpdateSettings () inline private
References Classifier.MainForm.learningRate, and Classifier.MainForm.learningRateBox.
ShowTrainingData() [2/6]
void Classifier.MainForm.ShowTrainingData () inline private
References AForge.Controls.Chart.AddDataSeries(), Classifier.MainForm.chart, Classifier.MainForm.classes, Classifier.MainForm.classesCount, Classifier.MainForm.data, Classifier.MainForm.dataSereisColors, AForge.Controls.Chart.RemoveAllDataSeries(), Classifier.MainForm.samples, Classifier.MainForm.samplesPerClass, and AForge.Controls.Chart.UpdateDataSeries().
EnableControls() [4/9]
void Classifier.MainForm.EnableControls (bool enable) inline private
References Classifier.MainForm.learningRateBox, Classifier.MainForm.loadButton, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.startButton, and Classifier.MainForm.stopButton.
startButton_Click() [4/9]
void Classifier.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.EnableControls(), Classifier.MainForm.learningRate, Classifier.MainForm.learningRateBox, Classifier.MainForm.needToStop, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.saveStatisticsToFiles, Classifier.MainForm.SearchSolution(), Classifier.MainForm.UpdateSettings(), and Classifier.MainForm.workerThread.
stopButton_Click() [4/9]
void Classifier.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.needToStop, and Classifier.MainForm.workerThread.
SearchSolution() [4/9]
void Classifier.MainForm.SearchSolution () inline private
References Classifier.MainForm.chart, Classifier.MainForm.classes, Classifier.MainForm.classesCount, Classifier.MainForm.data, Classifier.MainForm.EnableControls(), Classifier.MainForm.errorChart, Classifier.MainForm.iterationsBox, AForge.Neuro.Learning.PerceptronLearning.LearningRate, Classifier.MainForm.learningRate, AForge.DoubleRange.Max, AForge.DoubleRange.Min, Classifier.MainForm.needToStop, AForge.Controls.Chart.RangeX, AForge.Neuro.Learning.PerceptronLearning.RunEpoch(), Classifier.MainForm.samples, Classifier.MainForm.saveStatisticsToFiles, AForge.Controls.Chart.UpdateDataSeries(), and Classifier.MainForm.weightsList.
MainForm_Load() [2/2]
void Classifier.MainForm.MainForm_Load (object sender, System.EventArgs e) inline private
Dispose() [5/9]
override void Classifier.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References Classifier.MainForm.components.
InitializeComponent() [5/9]
void Classifier.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [5/9]
static void Classifier.MainForm.Main () inline static private
The main entry point for the application.
References Classifier.MainForm.MainForm().
MainForm_Closing() [5/9]
void Classifier.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References Classifier.MainForm.needToStop, and Classifier.MainForm.workerThread.
loadButton_Click() [5/9]
void Classifier.MainForm.loadButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.chart, Classifier.MainForm.classes, Classifier.MainForm.ClearCurrentSolution(), Classifier.MainForm.data, Classifier.MainForm.noVisualizationLabel, Classifier.MainForm.openFileDialog, AForge.Controls.Chart.RangeX, Classifier.MainForm.samples, Classifier.MainForm.ShowTrainingData(), Classifier.MainForm.startButton, Classifier.MainForm.UpdateDataListView(), and Classifier.MainForm.variables.
UpdateSettings() [5/9]
void Classifier.MainForm.UpdateSettings () inline private
References Classifier.MainForm.learningRate, and Classifier.MainForm.learningRateBox.
UpdateDataListView() [3/6]
void Classifier.MainForm.UpdateDataListView () inline private
References Classifier.MainForm.classes, Classifier.MainForm.data, Classifier.MainForm.dataList, Classifier.MainForm.samples, and Classifier.MainForm.variables.
ShowTrainingData() [3/6]
void Classifier.MainForm.ShowTrainingData () inline private
References Classifier.MainForm.chart, Classifier.MainForm.classes, Classifier.MainForm.data, Classifier.MainForm.samples, and AForge.Controls.Chart.UpdateDataSeries().
EnableControls() [5/9]
void Classifier.MainForm.EnableControls (bool enable) inline private
References Classifier.MainForm.learningRateBox, Classifier.MainForm.loadButton, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.startButton, and Classifier.MainForm.stopButton.
ClearCurrentSolution() [1/3]
void Classifier.MainForm.ClearCurrentSolution () inline private
References Classifier.MainForm.chart, Classifier.MainForm.errorChart, AForge.Controls.Chart.UpdateDataSeries(), and Classifier.MainForm.weightsList.
Referenced by Classifier.MainForm.loadButton_Click().
startButton_Click() [5/9]
void Classifier.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.EnableControls(), Classifier.MainForm.learningRate, Classifier.MainForm.learningRateBox, Classifier.MainForm.needToStop, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.saveStatisticsToFiles, Classifier.MainForm.SearchSolution(), Classifier.MainForm.UpdateSettings(), and Classifier.MainForm.workerThread.
stopButton_Click() [5/9]
void Classifier.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.needToStop, and Classifier.MainForm.workerThread.
SearchSolution() [5/9]
void Classifier.MainForm.SearchSolution () inline private
References Classifier.MainForm.chart, Classifier.MainForm.classes, Classifier.MainForm.data, Classifier.MainForm.EnableControls(), Classifier.MainForm.errorChart, AForge.Neuro.Neuron.InputsCount, Classifier.MainForm.iterationsBox, AForge.Neuro.Learning.PerceptronLearning.LearningRate, Classifier.MainForm.learningRate, AForge.DoubleRange.Max, AForge.DoubleRange.Min, Classifier.MainForm.needToStop, AForge.Controls.Chart.RangeX, AForge.Controls.Chart.RangeY, AForge.Neuro.Learning.PerceptronLearning.RunEpoch(), Classifier.MainForm.samples, Classifier.MainForm.saveStatisticsToFiles, AForge.Neuro.ActivationNeuron.Threshold, AForge.Controls.Chart.UpdateDataSeries(), Classifier.MainForm.variables, and Classifier.MainForm.weightsList.
Dispose() [6/9]
override void Classifier.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References Classifier.MainForm.components.
InitializeComponent() [6/9]
void Classifier.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [6/9]
static void Classifier.MainForm.Main () inline static private
The main entry point for the application.
References Classifier.MainForm.MainForm().
MainForm_Closing() [6/9]
void Classifier.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References Classifier.MainForm.needToStop, and Classifier.MainForm.workerThread.
loadButton_Click() [6/9]
void Classifier.MainForm.loadButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.chart, Classifier.MainForm.classes, Classifier.MainForm.ClearCurrentSolution(), Classifier.MainForm.data, Classifier.MainForm.noVisualizationLabel, Classifier.MainForm.openFileDialog, AForge.Controls.Chart.RangeX, Classifier.MainForm.samples, Classifier.MainForm.ShowTrainingData(), Classifier.MainForm.startButton, Classifier.MainForm.UpdateDataListView(), and Classifier.MainForm.variables.
UpdateSettings() [6/9]
void Classifier.MainForm.UpdateSettings () inline private
References Classifier.MainForm.learningRate, and Classifier.MainForm.learningRateBox.
UpdateDataListView() [4/6]
void Classifier.MainForm.UpdateDataListView () inline private
References Classifier.MainForm.classes, Classifier.MainForm.data, Classifier.MainForm.dataList, Classifier.MainForm.samples, and Classifier.MainForm.variables.
ShowTrainingData() [4/6]
void Classifier.MainForm.ShowTrainingData () inline private
References Classifier.MainForm.chart, Classifier.MainForm.classes, Classifier.MainForm.data, Classifier.MainForm.samples, and AForge.Controls.Chart.UpdateDataSeries().
EnableControls() [6/9]
void Classifier.MainForm.EnableControls (bool enable) inline private
References Classifier.MainForm.learningRateBox, Classifier.MainForm.loadButton, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.startButton, and Classifier.MainForm.stopButton.
ClearCurrentSolution() [2/3]
void Classifier.MainForm.ClearCurrentSolution () inline private
References Classifier.MainForm.chart, Classifier.MainForm.errorChart, AForge.Controls.Chart.UpdateDataSeries(), and Classifier.MainForm.weightsList.
startButton_Click() [6/9]
void Classifier.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.EnableControls(), Classifier.MainForm.learningRate, Classifier.MainForm.learningRateBox, Classifier.MainForm.needToStop, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.saveStatisticsToFiles, Classifier.MainForm.SearchSolution(), Classifier.MainForm.UpdateSettings(), and Classifier.MainForm.workerThread.
stopButton_Click() [6/9]
void Classifier.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.needToStop, and Classifier.MainForm.workerThread.
SearchSolution() [6/9]
void Classifier.MainForm.SearchSolution () inline private
References Classifier.MainForm.chart, Classifier.MainForm.classes, Classifier.MainForm.data, Classifier.MainForm.EnableControls(), Classifier.MainForm.errorChart, AForge.Neuro.Neuron.InputsCount, Classifier.MainForm.iterationsBox, AForge.Neuro.Learning.PerceptronLearning.LearningRate, Classifier.MainForm.learningRate, AForge.DoubleRange.Max, AForge.DoubleRange.Min, Classifier.MainForm.needToStop, AForge.Controls.Chart.RangeX, AForge.Controls.Chart.RangeY, AForge.Neuro.Learning.PerceptronLearning.RunEpoch(), Classifier.MainForm.samples, Classifier.MainForm.saveStatisticsToFiles, AForge.Neuro.ActivationNeuron.Threshold, AForge.Controls.Chart.UpdateDataSeries(), Classifier.MainForm.variables, and Classifier.MainForm.weightsList.
Dispose() [7/9]
override void Classifier.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References Classifier.MainForm.components.
InitializeComponent() [7/9]
void Classifier.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [7/9]
static void Classifier.MainForm.Main () inline static private
The main entry point for the application.
References Classifier.MainForm.MainForm().
SetTextCallback() [1/3]
delegate void Classifier.MainForm.SetTextCallback (System.Windows.Forms.Control control, string text) private
Referenced by Classifier.MainForm.SetText().
ClearListCallback() [1/3]
delegate void Classifier.MainForm.ClearListCallback (System.Windows.Forms.ListView control) private
Referenced by Classifier.MainForm.ClearList().
AddListItemCallback() [1/3]
delegate ListViewItem Classifier.MainForm.AddListItemCallback (System.Windows.Forms.ListView control, string itemText) private
Referenced by Classifier.MainForm.AddListItem().
AddListSubitemCallback() [1/3]
delegate void Classifier.MainForm.AddListSubitemCallback (ListViewItem item, string subItemText) private
Referenced by Classifier.MainForm.AddListSubitem().
SetText() [1/3]
void Classifier.MainForm.SetText (System.Windows.Forms.Control control, string text) inline private
References Classifier.MainForm.SetTextCallback().
Referenced by Classifier.MainForm.SearchSolution(), and Classifier.MainForm.SetText().
ClearList() [1/3]
void Classifier.MainForm.ClearList (System.Windows.Forms.ListView control) inline private
References Classifier.MainForm.ClearListCallback().
Referenced by Classifier.MainForm.ClearList(), and Classifier.MainForm.SearchSolution().
AddListItem() [1/3]
ListViewItem Classifier.MainForm.AddListItem (System.Windows.Forms.ListView control, string itemText) inline private
References Classifier.MainForm.AddListItemCallback().
Referenced by Classifier.MainForm.AddListItem(), and Classifier.MainForm.SearchSolution().
AddListSubitem() [1/3]
void Classifier.MainForm.AddListSubitem (ListViewItem item, string subItemText) inline private
References Classifier.MainForm.AddListSubitemCallback().
Referenced by Classifier.MainForm.AddListSubitem(), and Classifier.MainForm.SearchSolution().
MainForm_Closing() [7/9]
void Classifier.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References Classifier.MainForm.needToStop, and Classifier.MainForm.workerThread.
loadButton_Click() [7/9]
void Classifier.MainForm.loadButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.classes, Classifier.MainForm.classesBox, Classifier.MainForm.classesCount, Classifier.MainForm.ClearSolution(), Classifier.MainForm.data, Classifier.MainForm.neuronsBox, Classifier.MainForm.neuronsCount, Classifier.MainForm.oneNeuronForTwoCheck, Classifier.MainForm.openFileDialog, Classifier.MainForm.samples, Classifier.MainForm.samplesPerClass, Classifier.MainForm.startButton, Classifier.MainForm.UpdateDataListView(), Classifier.MainForm.useOneNeuronForTwoClasses, and Classifier.MainForm.variables.
UpdateSettings() [7/9]
void Classifier.MainForm.UpdateSettings () inline private
References Classifier.MainForm.alphaBox, Classifier.MainForm.errorLimitBox, Classifier.MainForm.errorLimitCheck, Classifier.MainForm.iterationLimit, Classifier.MainForm.iterationsBox, Classifier.MainForm.learningErrorLimit, Classifier.MainForm.learningRate, Classifier.MainForm.learningRateBox, Classifier.MainForm.oneNeuronForTwoCheck, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.saveStatisticsToFiles, Classifier.MainForm.sigmoidAlphaValue, Classifier.MainForm.useErrorLimit, and Classifier.MainForm.useOneNeuronForTwoClasses.
UpdateDataListView() [5/6]
void Classifier.MainForm.UpdateDataListView () inline private
References Classifier.MainForm.classes, Classifier.MainForm.data, Classifier.MainForm.dataList, Classifier.MainForm.samples, and Classifier.MainForm.variables.
oneNeuronForTwoCheck_CheckedChanged() [3/3]
void Classifier.MainForm.oneNeuronForTwoCheck_CheckedChanged (object sender, System.EventArgs e) inline private
References Classifier.MainForm.classesCount, Classifier.MainForm.neuronsBox, Classifier.MainForm.neuronsCount, Classifier.MainForm.oneNeuronForTwoCheck, and Classifier.MainForm.useOneNeuronForTwoClasses.
EnableCallback() [1/3]
delegate void Classifier.MainForm.EnableCallback (bool enable) private
Referenced by Classifier.MainForm.EnableControls().
EnableControls() [7/9]
void Classifier.MainForm.EnableControls (bool enable) inline private
References Classifier.MainForm.alphaBox, Classifier.MainForm.classesCount, Classifier.MainForm.EnableCallback(), Classifier.MainForm.EnableControls(), Classifier.MainForm.errorLimitBox, Classifier.MainForm.errorLimitCheck, Classifier.MainForm.iterationsBox, Classifier.MainForm.learningRateBox, Classifier.MainForm.loadButton, Classifier.MainForm.oneNeuronForTwoCheck, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.startButton, and Classifier.MainForm.stopButton.
ClearSolution() [3/3]
void Classifier.MainForm.ClearSolution () inline private
References Classifier.MainForm.currentErrorBox, Classifier.MainForm.currentIterationBox, Classifier.MainForm.errorChart, AForge.Controls.Chart.UpdateDataSeries(), and Classifier.MainForm.weightsList.
startButton_Click() [7/9]
void Classifier.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.alphaBox, Classifier.MainForm.EnableControls(), Classifier.MainForm.errorLimitBox, Classifier.MainForm.errorLimitCheck, Classifier.MainForm.iterationLimit, Classifier.MainForm.iterationsBox, Classifier.MainForm.learningErrorLimit, Classifier.MainForm.learningRate, Classifier.MainForm.learningRateBox, Classifier.MainForm.needToStop, Classifier.MainForm.oneNeuronForTwoCheck, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.saveStatisticsToFiles, Classifier.MainForm.SearchSolution(), Classifier.MainForm.sigmoidAlphaValue, Classifier.MainForm.UpdateSettings(), Classifier.MainForm.useErrorLimit, Classifier.MainForm.useOneNeuronForTwoClasses, and Classifier.MainForm.workerThread.
stopButton_Click() [7/9]
void Classifier.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.needToStop, and Classifier.MainForm.workerThread.
SearchSolution() [7/9]
void Classifier.MainForm.SearchSolution () inline private
References Classifier.MainForm.AddListItem(), Classifier.MainForm.AddListSubitem(), Classifier.MainForm.classes, Classifier.MainForm.classesCount, Classifier.MainForm.ClearList(), Classifier.MainForm.currentErrorBox, Classifier.MainForm.currentIterationBox, Classifier.MainForm.data, Classifier.MainForm.EnableControls(), Classifier.MainForm.errorChart, Classifier.MainForm.iterationLimit, AForge.Neuro.Network.Layers, Classifier.MainForm.learningErrorLimit, AForge.Neuro.Learning.DeltaRuleLearning.LearningRate, Classifier.MainForm.learningRate, Classifier.MainForm.needToStop, AForge.Neuro.Layer.Neurons, Classifier.MainForm.neuronsCount, AForge.Controls.Chart.RangeX, AForge.Neuro.Learning.DeltaRuleLearning.RunEpoch(), Classifier.MainForm.samples, Classifier.MainForm.saveStatisticsToFiles, Classifier.MainForm.SetText(), Classifier.MainForm.sigmoidAlphaValue, AForge.Controls.Chart.UpdateDataSeries(), Classifier.MainForm.useErrorLimit, Classifier.MainForm.useOneNeuronForTwoClasses, Classifier.MainForm.variables, AForge.Neuro.Neuron.Weights, and Classifier.MainForm.weightsList.
Dispose() [8/9]
override void Classifier.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References Classifier.MainForm.components.
InitializeComponent() [8/9]
void Classifier.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [8/9]
static void Classifier.MainForm.Main () inline static private
The main entry point for the application.
References Classifier.MainForm.MainForm().
SetTextCallback() [2/3]
delegate void Classifier.MainForm.SetTextCallback (System.Windows.Forms.Control control, string text) private
ClearListCallback() [2/3]
delegate void Classifier.MainForm.ClearListCallback (System.Windows.Forms.ListView control) private
AddListItemCallback() [2/3]
delegate ListViewItem Classifier.MainForm.AddListItemCallback (System.Windows.Forms.ListView control, string itemText) private
AddListSubitemCallback() [2/3]
delegate void Classifier.MainForm.AddListSubitemCallback (ListViewItem item, string subItemText) private
SetText() [2/3]
void Classifier.MainForm.SetText (System.Windows.Forms.Control control, string text) inline private
References Classifier.MainForm.SetText(), and Classifier.MainForm.SetTextCallback().
ClearList() [2/3]
void Classifier.MainForm.ClearList (System.Windows.Forms.ListView control) inline private
References Classifier.MainForm.ClearList(), and Classifier.MainForm.ClearListCallback().
AddListItem() [2/3]
ListViewItem Classifier.MainForm.AddListItem (System.Windows.Forms.ListView control, string itemText) inline private
References Classifier.MainForm.AddListItem(), and Classifier.MainForm.AddListItemCallback().
AddListSubitem() [2/3]
void Classifier.MainForm.AddListSubitem (ListViewItem item, string subItemText) inline private
References Classifier.MainForm.AddListSubitem(), and Classifier.MainForm.AddListSubitemCallback().
MainForm_Closing() [8/9]
void Classifier.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References Classifier.MainForm.needToStop, and Classifier.MainForm.workerThread.
loadButton_Click() [8/9]
void Classifier.MainForm.loadButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.chart, Classifier.MainForm.classes, Classifier.MainForm.classesCount, Classifier.MainForm.data, Classifier.MainForm.errorChart, Classifier.MainForm.openFileDialog, AForge.Controls.Chart.RangeX, Classifier.MainForm.samples, Classifier.MainForm.samplesPerClass, Classifier.MainForm.ShowTrainingData(), Classifier.MainForm.startButton, AForge.Controls.Chart.UpdateDataSeries(), and Classifier.MainForm.weightsList.
UpdateSettings() [8/9]
void Classifier.MainForm.UpdateSettings () inline private
References Classifier.MainForm.learningRate, and Classifier.MainForm.learningRateBox.
ShowTrainingData() [5/6]
void Classifier.MainForm.ShowTrainingData () inline private
References AForge.Controls.Chart.AddDataSeries(), Classifier.MainForm.chart, Classifier.MainForm.classes, Classifier.MainForm.classesCount, Classifier.MainForm.data, Classifier.MainForm.dataSereisColors, AForge.Controls.Chart.RemoveAllDataSeries(), Classifier.MainForm.samples, Classifier.MainForm.samplesPerClass, and AForge.Controls.Chart.UpdateDataSeries().
EnableCallback() [2/3]
delegate void Classifier.MainForm.EnableCallback (bool enable) private
EnableControls() [8/9]
void Classifier.MainForm.EnableControls (bool enable) inline private
References Classifier.MainForm.EnableCallback(), Classifier.MainForm.EnableControls(), Classifier.MainForm.learningRateBox, Classifier.MainForm.loadButton, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.startButton, and Classifier.MainForm.stopButton.
startButton_Click() [8/9]
void Classifier.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.EnableControls(), Classifier.MainForm.learningRate, Classifier.MainForm.learningRateBox, Classifier.MainForm.needToStop, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.saveStatisticsToFiles, Classifier.MainForm.SearchSolution(), Classifier.MainForm.UpdateSettings(), and Classifier.MainForm.workerThread.
stopButton_Click() [8/9]
void Classifier.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.needToStop, and Classifier.MainForm.workerThread.
SearchSolution() [8/9]
void Classifier.MainForm.SearchSolution () inline private
References Classifier.MainForm.AddListItem(), Classifier.MainForm.AddListSubitem(), Classifier.MainForm.chart, Classifier.MainForm.classes, Classifier.MainForm.classesCount, Classifier.MainForm.ClearList(), Classifier.MainForm.data, Classifier.MainForm.EnableControls(), Classifier.MainForm.errorChart, Classifier.MainForm.iterationsBox, AForge.Neuro.Network.Layers, AForge.Neuro.Learning.PerceptronLearning.LearningRate, Classifier.MainForm.learningRate, AForge.DoubleRange.Max, AForge.DoubleRange.Min, Classifier.MainForm.needToStop, AForge.Neuro.Layer.Neurons, AForge.Controls.Chart.RangeX, AForge.Neuro.Learning.PerceptronLearning.RunEpoch(), Classifier.MainForm.samples, Classifier.MainForm.saveStatisticsToFiles, Classifier.MainForm.SetText(), AForge.Controls.Chart.UpdateDataSeries(), AForge.Neuro.Neuron.Weights, and Classifier.MainForm.weightsList.
Dispose() [9/9]
override void Classifier.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References Classifier.MainForm.components.
InitializeComponent() [9/9]
void Classifier.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [9/9]
static void Classifier.MainForm.Main () inline static private
The main entry point for the application.
References Classifier.MainForm.MainForm().
SetTextCallback() [3/3]
delegate void Classifier.MainForm.SetTextCallback (System.Windows.Forms.Control control, string text) private
ClearListCallback() [3/3]
delegate void Classifier.MainForm.ClearListCallback (System.Windows.Forms.ListView control) private
AddListItemCallback() [3/3]
delegate ListViewItem Classifier.MainForm.AddListItemCallback (System.Windows.Forms.ListView control, string itemText) private
AddListSubitemCallback() [3/3]
delegate void Classifier.MainForm.AddListSubitemCallback (ListViewItem item, string subItemText) private
SetText() [3/3]
void Classifier.MainForm.SetText (System.Windows.Forms.Control control, string text) inline private
References Classifier.MainForm.SetText(), and Classifier.MainForm.SetTextCallback().
ClearList() [3/3]
void Classifier.MainForm.ClearList (System.Windows.Forms.ListView control) inline private
References Classifier.MainForm.ClearList(), and Classifier.MainForm.ClearListCallback().
AddListItem() [3/3]
ListViewItem Classifier.MainForm.AddListItem (System.Windows.Forms.ListView control, string itemText) inline private
References Classifier.MainForm.AddListItem(), and Classifier.MainForm.AddListItemCallback().
AddListSubitem() [3/3]
void Classifier.MainForm.AddListSubitem (ListViewItem item, string subItemText) inline private
References Classifier.MainForm.AddListSubitem(), and Classifier.MainForm.AddListSubitemCallback().
MainForm_Closing() [9/9]
void Classifier.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References Classifier.MainForm.needToStop, and Classifier.MainForm.workerThread.
loadButton_Click() [9/9]
void Classifier.MainForm.loadButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.chart, Classifier.MainForm.classes, Classifier.MainForm.ClearCurrentSolution(), Classifier.MainForm.data, Classifier.MainForm.noVisualizationLabel, Classifier.MainForm.openFileDialog, AForge.Controls.Chart.RangeX, Classifier.MainForm.samples, Classifier.MainForm.ShowTrainingData(), Classifier.MainForm.startButton, Classifier.MainForm.UpdateDataListView(), and Classifier.MainForm.variables.
UpdateSettings() [9/9]
void Classifier.MainForm.UpdateSettings () inline private
References Classifier.MainForm.learningRate, and Classifier.MainForm.learningRateBox.
UpdateDataListView() [6/6]
void Classifier.MainForm.UpdateDataListView () inline private
References Classifier.MainForm.classes, Classifier.MainForm.data, Classifier.MainForm.dataList, Classifier.MainForm.samples, and Classifier.MainForm.variables.
ShowTrainingData() [6/6]
void Classifier.MainForm.ShowTrainingData () inline private
References Classifier.MainForm.chart, Classifier.MainForm.classes, Classifier.MainForm.data, Classifier.MainForm.samples, and AForge.Controls.Chart.UpdateDataSeries().
EnableCallback() [3/3]
delegate void Classifier.MainForm.EnableCallback (bool enable) private
EnableControls() [9/9]
void Classifier.MainForm.EnableControls (bool enable) inline private
References Classifier.MainForm.EnableCallback(), Classifier.MainForm.EnableControls(), Classifier.MainForm.learningRateBox, Classifier.MainForm.loadButton, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.startButton, and Classifier.MainForm.stopButton.
ClearCurrentSolution() [3/3]
void Classifier.MainForm.ClearCurrentSolution () inline private
References Classifier.MainForm.chart, Classifier.MainForm.errorChart, AForge.Controls.Chart.UpdateDataSeries(), and Classifier.MainForm.weightsList.
startButton_Click() [9/9]
void Classifier.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.EnableControls(), Classifier.MainForm.learningRate, Classifier.MainForm.learningRateBox, Classifier.MainForm.needToStop, Classifier.MainForm.saveFilesCheck, Classifier.MainForm.saveStatisticsToFiles, Classifier.MainForm.SearchSolution(), Classifier.MainForm.UpdateSettings(), and Classifier.MainForm.workerThread.
stopButton_Click() [9/9]
void Classifier.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References Classifier.MainForm.needToStop, and Classifier.MainForm.workerThread.
SearchSolution() [9/9]
void Classifier.MainForm.SearchSolution () inline private
References Classifier.MainForm.AddListItem(), Classifier.MainForm.AddListSubitem(), Classifier.MainForm.chart, Classifier.MainForm.classes, Classifier.MainForm.ClearList(), Classifier.MainForm.data, Classifier.MainForm.EnableControls(), Classifier.MainForm.errorChart, AForge.Neuro.Neuron.InputsCount, Classifier.MainForm.iterationsBox, AForge.Neuro.Network.Layers, AForge.Neuro.Learning.PerceptronLearning.LearningRate, Classifier.MainForm.learningRate, AForge.DoubleRange.Max, AForge.DoubleRange.Min, Classifier.MainForm.needToStop, AForge.Neuro.Layer.Neurons, AForge.Controls.Chart.RangeX, AForge.Controls.Chart.RangeY, AForge.Neuro.Learning.PerceptronLearning.RunEpoch(), Classifier.MainForm.samples, Classifier.MainForm.saveStatisticsToFiles, Classifier.MainForm.SetText(), AForge.Neuro.ActivationNeuron.Threshold, AForge.Controls.Chart.UpdateDataSeries(), Classifier.MainForm.variables, AForge.Neuro.Neuron.Weights, and Classifier.MainForm.weightsList.
Member Data Documentation
groupBox1
System Windows Forms GroupBox Classifier.MainForm.groupBox1 private
loadButton
System Windows Forms Button Classifier.MainForm.loadButton private
Referenced by Classifier.MainForm.EnableControls().
openFileDialog
System Windows Forms OpenFileDialog Classifier.MainForm.openFileDialog private
Referenced by Classifier.MainForm.loadButton_Click().
dataList
System Windows Forms ListView Classifier.MainForm.dataList private
Referenced by Classifier.MainForm.UpdateDataListView().
groupBox2
System Windows Forms GroupBox Classifier.MainForm.groupBox2 private
learningRateBox
System Windows Forms TextBox Classifier.MainForm.learningRateBox private
Referenced by Classifier.MainForm.EnableControls(), Classifier.MainForm.startButton_Click(), and Classifier.MainForm.UpdateSettings().
label1
System Windows Forms Label Classifier.MainForm.label1 private
label2
System Windows Forms Label Classifier.MainForm.label2 private
alphaBox
System Windows Forms TextBox Classifier.MainForm.alphaBox private
Referenced by Classifier.MainForm.EnableControls(), Classifier.MainForm.startButton_Click(), and Classifier.MainForm.UpdateSettings().
label3
System Windows Forms Label Classifier.MainForm.label3 private
errorLimitBox
System Windows Forms TextBox Classifier.MainForm.errorLimitBox private
Referenced by Classifier.MainForm.EnableControls(), Classifier.MainForm.startButton_Click(), and Classifier.MainForm.UpdateSettings().
label4
System Windows Forms Label Classifier.MainForm.label4 private
iterationsBox
System Windows Forms TextBox Classifier.MainForm.iterationsBox private
Referenced by Classifier.MainForm.EnableControls(), Classifier.MainForm.SearchSolution(), Classifier.MainForm.startButton_Click(), and Classifier.MainForm.UpdateSettings().
label5
System Windows Forms Label Classifier.MainForm.label5 private
label6
System Windows Forms Label Classifier.MainForm.label6 private
neuronsBox
System Windows Forms TextBox Classifier.MainForm.neuronsBox private
Referenced by Classifier.MainForm.loadButton_Click(), and Classifier.MainForm.oneNeuronForTwoCheck_CheckedChanged().
oneNeuronForTwoCheck
System Windows Forms CheckBox Classifier.MainForm.oneNeuronForTwoCheck private
Referenced by Classifier.MainForm.EnableControls(), Classifier.MainForm.loadButton_Click(), Classifier.MainForm.oneNeuronForTwoCheck_CheckedChanged(), Classifier.MainForm.startButton_Click(), and Classifier.MainForm.UpdateSettings().
label7
System Windows Forms Label Classifier.MainForm.label7 private
label8
System Windows Forms Label Classifier.MainForm.label8 private
currentIterationBox
System Windows Forms TextBox Classifier.MainForm.currentIterationBox private
Referenced by Classifier.MainForm.ClearSolution(), and Classifier.MainForm.SearchSolution().
stopButton
System Windows Forms Button Classifier.MainForm.stopButton private
Referenced by Classifier.MainForm.EnableControls().
startButton
System Windows Forms Button Classifier.MainForm.startButton private
Referenced by Classifier.MainForm.EnableControls(), and Classifier.MainForm.loadButton_Click().
label9
System Windows Forms Label Classifier.MainForm.label9 private
label10
System Windows Forms Label Classifier.MainForm.label10 private
classesBox
System Windows Forms TextBox Classifier.MainForm.classesBox private
Referenced by Classifier.MainForm.loadButton_Click().
errorLimitCheck
System Windows Forms CheckBox Classifier.MainForm.errorLimitCheck private
Referenced by Classifier.MainForm.EnableControls(), Classifier.MainForm.startButton_Click(), and Classifier.MainForm.UpdateSettings().
label11
System Windows Forms Label Classifier.MainForm.label11 private
currentErrorBox
System Windows Forms TextBox Classifier.MainForm.currentErrorBox private
Referenced by Classifier.MainForm.ClearSolution(), and Classifier.MainForm.SearchSolution().
groupBox3
System Windows Forms GroupBox Classifier.MainForm.groupBox3 private
label12
System Windows Forms Label Classifier.MainForm.label12 private
weightsList
System Windows Forms ListView Classifier.MainForm.weightsList private
Referenced by Classifier.MainForm.ClearCurrentSolution(), Classifier.MainForm.ClearSolution(), Classifier.MainForm.loadButton_Click(), and Classifier.MainForm.SearchSolution().
label13
System Windows Forms Label Classifier.MainForm.label13 private
columnHeader1
System Windows Forms ColumnHeader Classifier.MainForm.columnHeader1 private
columnHeader2
System Windows Forms ColumnHeader Classifier.MainForm.columnHeader2 private
columnHeader3
System Windows Forms ColumnHeader Classifier.MainForm.columnHeader3 private
saveFilesCheck
System Windows Forms CheckBox Classifier.MainForm.saveFilesCheck private
Referenced by Classifier.MainForm.EnableControls(), Classifier.MainForm.MainForm(), Classifier.MainForm.startButton_Click(), and Classifier.MainForm.UpdateSettings().
errorChart
AForge Controls Chart Classifier.MainForm.errorChart private
Referenced by Classifier.MainForm.ClearCurrentSolution(), Classifier.MainForm.ClearSolution(), Classifier.MainForm.loadButton_Click(), Classifier.MainForm.MainForm(), and Classifier.MainForm.SearchSolution().
components
System ComponentModel Container Classifier.MainForm.components = null private
Required designer variable.
Referenced by Classifier.MainForm.Dispose().
samples
int Classifier.MainForm.samples = 0 private
Referenced by Classifier.MainForm.loadButton_Click(), Classifier.MainForm.SearchSolution(), Classifier.MainForm.ShowTrainingData(), and Classifier.MainForm.UpdateDataListView().
variables
int Classifier.MainForm.variables = 0 private
Referenced by Classifier.MainForm.loadButton_Click(), Classifier.MainForm.SearchSolution(), and Classifier.MainForm.UpdateDataListView().
data
double [,] Classifier.MainForm.data = null private
Referenced by Classifier.MainForm.loadButton_Click(), Classifier.MainForm.SearchSolution(), Classifier.MainForm.ShowTrainingData(), and Classifier.MainForm.UpdateDataListView().
classes
int [] Classifier.MainForm.classes = null private
Referenced by Classifier.MainForm.loadButton_Click(), Classifier.MainForm.SearchSolution(), Classifier.MainForm.ShowTrainingData(), and Classifier.MainForm.UpdateDataListView().
classesCount
int Classifier.MainForm.classesCount = 0 private
Referenced by Classifier.MainForm.EnableControls(), Classifier.MainForm.loadButton_Click(), Classifier.MainForm.oneNeuronForTwoCheck_CheckedChanged(), Classifier.MainForm.SearchSolution(), and Classifier.MainForm.ShowTrainingData().
samplesPerClass
int [] Classifier.MainForm.samplesPerClass = null private
Referenced by Classifier.MainForm.loadButton_Click(), and Classifier.MainForm.ShowTrainingData().
neuronsCount
int Classifier.MainForm.neuronsCount = 0 private
Referenced by Classifier.MainForm.loadButton_Click(), Classifier.MainForm.oneNeuronForTwoCheck_CheckedChanged(), and Classifier.MainForm.SearchSolution().
learningRate
double Classifier.MainForm.learningRate = 0.1 private
Referenced by Classifier.MainForm.SearchSolution(), Classifier.MainForm.startButton_Click(), and Classifier.MainForm.UpdateSettings().
sigmoidAlphaValue
double Classifier.MainForm.sigmoidAlphaValue = 2.0 private
Referenced by Classifier.MainForm.SearchSolution(), Classifier.MainForm.startButton_Click(), and Classifier.MainForm.UpdateSettings().
learningErrorLimit
double Classifier.MainForm.learningErrorLimit = 0.1 private
Referenced by Classifier.MainForm.SearchSolution(), Classifier.MainForm.startButton_Click(), and Classifier.MainForm.UpdateSettings().
iterationLimit
double Classifier.MainForm.iterationLimit = 1000 private
Referenced by Classifier.MainForm.SearchSolution(), Classifier.MainForm.startButton_Click(), and Classifier.MainForm.UpdateSettings().
useOneNeuronForTwoClasses
bool Classifier.MainForm.useOneNeuronForTwoClasses = false private
Referenced by Classifier.MainForm.loadButton_Click(), Classifier.MainForm.oneNeuronForTwoCheck_CheckedChanged(), Classifier.MainForm.SearchSolution(), Classifier.MainForm.startButton_Click(), and Classifier.MainForm.UpdateSettings().
useErrorLimit
bool Classifier.MainForm.useErrorLimit = true private
Referenced by Classifier.MainForm.SearchSolution(), Classifier.MainForm.startButton_Click(), and Classifier.MainForm.UpdateSettings().
saveStatisticsToFiles
bool Classifier.MainForm.saveStatisticsToFiles = false private
Referenced by Classifier.MainForm.MainForm(), Classifier.MainForm.SearchSolution(), Classifier.MainForm.startButton_Click(), and Classifier.MainForm.UpdateSettings().
workerThread
Thread Classifier.MainForm.workerThread = null private
Referenced by Classifier.MainForm.MainForm_Closing(), Classifier.MainForm.startButton_Click(), and Classifier.MainForm.stopButton_Click().
needToStop [1/2]
volatile bool Classifier.MainForm.needToStop = false private
Referenced by Classifier.MainForm.MainForm_Closing(), Classifier.MainForm.SearchSolution(), Classifier.MainForm.startButton_Click(), and Classifier.MainForm.stopButton_Click().
chart
AForge Controls Chart Classifier.MainForm.chart private
Referenced by Classifier.MainForm.ClearCurrentSolution(), Classifier.MainForm.loadButton_Click(), Classifier.MainForm.MainForm(), Classifier.MainForm.SearchSolution(), and Classifier.MainForm.ShowTrainingData().
dataSereisColors
Color [] Classifier.MainForm.dataSereisColors static private
Initial value:
= new Color[10] {
                                                                     Color.Red,     Color.Blue,
                                                                     Color.Green,   Color.DarkOrange,
                                                                     Color.Violet,  Color.Brown,
                                                                     Color.Black,   Color.Pink,
                                                                     Color.Olive,   Color.Navy }
Referenced by Classifier.MainForm.ShowTrainingData().
noVisualizationLabel
System Windows Forms Label Classifier.MainForm.noVisualizationLabel private
Referenced by Classifier.MainForm.loadButton_Click().
needToStop [2/2]
volatile bool Classifier.MainForm.needToStop = false private
The documentation for this class was generated from the following file:
shelldev/lib/external/neuralnetworks/neuro_src/Samples/Neuro/Simple/Delta Rule Learning/Backup/MainForm.cs