Doc: IGLib EXTENDED: alglib.matinv Class Reference
alglib.matinv Class Reference
Classes
class matinvreport
Static Public Member Functions
static void rmatrixluinverse (ref double[,] a, int[] pivots, int n, ref int info, matinvreport rep)
static void rmatrixinverse (ref double[,] a, int n, ref int info, matinvreport rep)
static void cmatrixluinverse (ref complex[,] a, int[] pivots, int n, ref int info, matinvreport rep)
static void cmatrixinverse (ref complex[,] a, int n, ref int info, matinvreport rep)
static void spdmatrixcholeskyinverse (ref double[,] a, int n, bool isupper, ref int info, matinvreport rep)
static void spdmatrixinverse (ref double[,] a, int n, bool isupper, ref int info, matinvreport rep)
static void hpdmatrixcholeskyinverse (ref complex[,] a, int n, bool isupper, ref int info, matinvreport rep)
static void hpdmatrixinverse (ref complex[,] a, int n, bool isupper, ref int info, matinvreport rep)
static void rmatrixtrinverse (ref double[,] a, int n, bool isupper, bool isunit, ref int info, matinvreport rep)
static void cmatrixtrinverse (ref complex[,] a, int n, bool isupper, bool isunit, ref int info, matinvreport rep)
static void rmatrixluinverse (ref double[,] a, int[] pivots, int n, ref int info, matinvreport rep)
static void rmatrixinverse (ref double[,] a, int n, ref int info, matinvreport rep)
static void cmatrixluinverse (ref complex[,] a, int[] pivots, int n, ref int info, matinvreport rep)
static void cmatrixinverse (ref complex[,] a, int n, ref int info, matinvreport rep)
static void spdmatrixcholeskyinverse (ref double[,] a, int n, bool isupper, ref int info, matinvreport rep)
static void spdmatrixinverse (ref double[,] a, int n, bool isupper, ref int info, matinvreport rep)
static void hpdmatrixcholeskyinverse (ref complex[,] a, int n, bool isupper, ref int info, matinvreport rep)
static void hpdmatrixinverse (ref complex[,] a, int n, bool isupper, ref int info, matinvreport rep)
static void rmatrixtrinverse (ref double[,] a, int n, bool isupper, bool isunit, ref int info, matinvreport rep)
static void cmatrixtrinverse (ref complex[,] a, int n, bool isupper, bool isunit, ref int info, matinvreport rep)
Static Private Member Functions
static void rmatrixtrinverserec (ref double[,] a, int offs, int n, bool isupper, bool isunit, ref double[] tmp, ref int info, matinvreport rep)
static void cmatrixtrinverserec (ref complex[,] a, int offs, int n, bool isupper, bool isunit, ref complex[] tmp, ref int info, matinvreport rep)
static void rmatrixluinverserec (ref double[,] a, int offs, int n, ref double[] work, ref int info, matinvreport rep)
static void cmatrixluinverserec (ref complex[,] a, int offs, int n, ref complex[] work, ref int info, matinvreport rep)
static void spdmatrixcholeskyinverserec (ref double[,] a, int offs, int n, bool isupper, ref double[] tmp)
static void hpdmatrixcholeskyinverserec (ref complex[,] a, int offs, int n, bool isupper, ref complex[] tmp)
static void rmatrixtrinverserec (ref double[,] a, int offs, int n, bool isupper, bool isunit, ref double[] tmp, ref int info, matinvreport rep)
static void cmatrixtrinverserec (ref complex[,] a, int offs, int n, bool isupper, bool isunit, ref complex[] tmp, ref int info, matinvreport rep)
static void rmatrixluinverserec (ref double[,] a, int offs, int n, ref double[] work, ref int info, matinvreport rep)
static void cmatrixluinverserec (ref complex[,] a, int offs, int n, ref complex[] work, ref int info, matinvreport rep)
static void spdmatrixcholeskyinverserec (ref double[,] a, int offs, int n, bool isupper, ref double[] tmp)
static void hpdmatrixcholeskyinverserec (ref complex[,] a, int offs, int n, bool isupper, ref complex[] tmp)
Member Function Documentation
rmatrixluinverse() [1/2]
static void alglib.matinv.rmatrixluinverse (ref double a[,], int[] pivots, int n, ref int info, matinvreport rep) inline static
Referenced by alglib.rmatrixluinverse(), and alglib.testmatinvunit.testrinv().
rmatrixinverse() [1/2]
static void alglib.matinv.rmatrixinverse (ref double a[,], int n, ref int info, matinvreport rep) inline static
Referenced by alglib.rmatrixinverse(), and alglib.testmatinvunit.testrinv().
cmatrixluinverse() [1/2]
static void alglib.matinv.cmatrixluinverse (ref complex a[,], int[] pivots, int n, ref int info, matinvreport rep) inline static
Referenced by alglib.cmatrixluinverse(), and alglib.testmatinvunit.testcinv().
cmatrixinverse() [1/2]
static void alglib.matinv.cmatrixinverse (ref complex a[,], int n, ref int info, matinvreport rep) inline static
Referenced by alglib.cmatrixinverse(), and alglib.testmatinvunit.testcinv().
spdmatrixcholeskyinverse() [1/2]
static void alglib.matinv.spdmatrixcholeskyinverse (ref double a[,], int n, bool isupper, ref int info, matinvreport rep) inline static
Referenced by alglib.spdmatrixcholeskyinverse(), and alglib.testmatinvunit.testspdinv().
spdmatrixinverse() [1/2]
static void alglib.matinv.spdmatrixinverse (ref double a[,], int n, bool isupper, ref int info, matinvreport rep) inline static
Referenced by alglib.lsfit.estimateerrors(), alglib.spdmatrixinverse(), and alglib.testmatinvunit.testspdinv().
hpdmatrixcholeskyinverse() [1/2]
static void alglib.matinv.hpdmatrixcholeskyinverse (ref complex a[,], int n, bool isupper, ref int info, matinvreport rep) inline static
Referenced by alglib.hpdmatrixcholeskyinverse(), and alglib.testmatinvunit.testhpdinv().
hpdmatrixinverse() [1/2]
static void alglib.matinv.hpdmatrixinverse (ref complex a[,], int n, bool isupper, ref int info, matinvreport rep) inline static
Referenced by alglib.hpdmatrixinverse(), and alglib.testmatinvunit.testhpdinv().
rmatrixtrinverse() [1/2]
static void alglib.matinv.rmatrixtrinverse (ref double a[,], int n, bool isupper, bool isunit, ref int info, matinvreport rep) inline static
Referenced by alglib.rmatrixtrinverse(), and alglib.testmatinvunit.testrtrinv().
cmatrixtrinverse() [1/2]
static void alglib.matinv.cmatrixtrinverse (ref complex a[,], int n, bool isupper, bool isunit, ref int info, matinvreport rep) inline static
Referenced by alglib.cmatrixtrinverse(), and alglib.testmatinvunit.testctrinv().
rmatrixtrinverserec() [1/2]
static void alglib.matinv.rmatrixtrinverserec (ref double a[,], int offs, int n, bool isupper, bool isunit, ref double[] tmp, ref int info, matinvreport rep) inline static private
cmatrixtrinverserec() [1/2]
static void alglib.matinv.cmatrixtrinverserec (ref complex a[,], int offs, int n, bool isupper, bool isunit, ref complex[] tmp, ref int info, matinvreport rep) inline static private
rmatrixluinverserec() [1/2]
static void alglib.matinv.rmatrixluinverserec (ref double a[,], int offs, int n, ref double[] work, ref int info, matinvreport rep) inline static private
cmatrixluinverserec() [1/2]
static void alglib.matinv.cmatrixluinverserec (ref complex a[,], int offs, int n, ref complex[] work, ref int info, matinvreport rep) inline static private
spdmatrixcholeskyinverserec() [1/2]
static void alglib.matinv.spdmatrixcholeskyinverserec (ref double a[,], int offs, int n, bool isupper, ref double[] tmp) inline static private
hpdmatrixcholeskyinverserec() [1/2]
static void alglib.matinv.hpdmatrixcholeskyinverserec (ref complex a[,], int offs, int n, bool isupper, ref complex[] tmp) inline static private
rmatrixluinverse() [2/2]
static void alglib.matinv.rmatrixluinverse (ref double a[,], int[] pivots, int n, ref int info, matinvreport rep) inline static
rmatrixinverse() [2/2]
static void alglib.matinv.rmatrixinverse (ref double a[,], int n, ref int info, matinvreport rep) inline static
cmatrixluinverse() [2/2]
static void alglib.matinv.cmatrixluinverse (ref complex a[,], int[] pivots, int n, ref int info, matinvreport rep) inline static
cmatrixinverse() [2/2]
static void alglib.matinv.cmatrixinverse (ref complex a[,], int n, ref int info, matinvreport rep) inline static
spdmatrixcholeskyinverse() [2/2]
static void alglib.matinv.spdmatrixcholeskyinverse (ref double a[,], int n, bool isupper, ref int info, matinvreport rep) inline static
spdmatrixinverse() [2/2]
static void alglib.matinv.spdmatrixinverse (ref double a[,], int n, bool isupper, ref int info, matinvreport rep) inline static
hpdmatrixcholeskyinverse() [2/2]
static void alglib.matinv.hpdmatrixcholeskyinverse (ref complex a[,], int n, bool isupper, ref int info, matinvreport rep) inline static
hpdmatrixinverse() [2/2]
static void alglib.matinv.hpdmatrixinverse (ref complex a[,], int n, bool isupper, ref int info, matinvreport rep) inline static
rmatrixtrinverse() [2/2]
static void alglib.matinv.rmatrixtrinverse (ref double a[,], int n, bool isupper, bool isunit, ref int info, matinvreport rep) inline static
cmatrixtrinverse() [2/2]
static void alglib.matinv.cmatrixtrinverse (ref complex a[,], int n, bool isupper, bool isunit, ref int info, matinvreport rep) inline static
rmatrixtrinverserec() [2/2]
static void alglib.matinv.rmatrixtrinverserec (ref double a[,], int offs, int n, bool isupper, bool isunit, ref double[] tmp, ref int info, matinvreport rep) inline static private
cmatrixtrinverserec() [2/2]
static void alglib.matinv.cmatrixtrinverserec (ref complex a[,], int offs, int n, bool isupper, bool isunit, ref complex[] tmp, ref int info, matinvreport rep) inline static private
rmatrixluinverserec() [2/2]
static void alglib.matinv.rmatrixluinverserec (ref double a[,], int offs, int n, ref double[] work, ref int info, matinvreport rep) inline static private
cmatrixluinverserec() [2/2]
static void alglib.matinv.cmatrixluinverserec (ref complex a[,], int offs, int n, ref complex[] work, ref int info, matinvreport rep) inline static private
spdmatrixcholeskyinverserec() [2/2]
static void alglib.matinv.spdmatrixcholeskyinverserec (ref double a[,], int offs, int n, bool isupper, ref double[] tmp) inline static private
hpdmatrixcholeskyinverserec() [2/2]
static void alglib.matinv.hpdmatrixcholeskyinverserec (ref complex a[,], int offs, int n, bool isupper, ref complex[] tmp) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/linalg.cs