Doc: IGLib EXTENDED: AForge.Imaging.ColorReduction.OrderedColorDithering Class Reference
AForge.Imaging.ColorReduction.OrderedColorDithering Class Reference
Color dithering with a thresold matrix (ordered dithering).
Public Member Functions
OrderedColorDithering ()
Initializes a new instance of the OrderedColorDithering class.
OrderedColorDithering (byte[,] matrix)
Initializes a new instance of the OrderedColorDithering class.
Bitmap Apply (Bitmap sourceImage)
Perform color dithering for the specified image.
unsafe Bitmap Apply (UnmanagedImage sourceImage)
Properties
byte[,] ThresholdMatrix [get, set]
Threshold matrix - values to add source image's values.
Color[] ColorTable [get, set]
Color table to use for image dithering. Must contain 2-256 colors.
bool UseCaching [get, set]
Use color caching during color dithering or not.
Private Member Functions
Color GetClosestColor (int red, int green, int blue, out byte colorIndex)
Private Attributes
bool useCaching = false
Color[] colorTable
byte[,] matrix
Dictionary< Color, byte > cache = new Dictionary<Color, byte>()
Detailed Description
Color dithering with a thresold matrix (ordered dithering).
The class implements ordered color dithering as described on Wikipedia. The algorithm achieves dithering by applying a threshold map on the pixels displayed, causing some of the pixels to be rendered at a different color, depending on how far in between the color is of available color entries.
The image processing routine accepts 24/32 bpp color images for processing. As a result this routine produces 4 bpp or 8 bpp indexed image, which depends on size of the specified color table - 4 bpp result for color tables with 16 colors or less; 8 bpp result for larger color tables.
Sample usage:
// create color image quantization routine
ColorImageQuantizer ciq = new ColorImageQuantizer(new MedianCutQuantizer());
// create 256 colors table
Color[] colorTable = ciq.CalculatePalette(image, 256);
// create dithering routine
OrderedColorDithering dithering = new OrderedColorDithering();
dithering.ColorTable = colorTable;
// apply the dithering routine
Bitmap newImage = dithering.Apply(image);
Initial image:
Result image:
Constructor & Destructor Documentation
OrderedColorDithering() [1/2]
AForge.Imaging.ColorReduction.OrderedColorDithering.OrderedColorDithering () inline
Initializes a new instance of the OrderedColorDithering class.
OrderedColorDithering() [2/2]
AForge.Imaging.ColorReduction.OrderedColorDithering.OrderedColorDithering (byte matrix[,]) inline
Initializes a new instance of the OrderedColorDithering class.
Parameters
matrix Threshold matrix (see ThresholdMatrix property).
References AForge.Imaging.ColorReduction.OrderedColorDithering.matrix, and AForge.Imaging.ColorReduction.OrderedColorDithering.ThresholdMatrix.
Member Function Documentation
Apply() [1/2]
Bitmap AForge.Imaging.ColorReduction.OrderedColorDithering.Apply (Bitmap sourceImage) inline
Perform color dithering for the specified image.
Parameters
sourceImage Source image to do color dithering for.
Returns
Returns color dithered image. See ColorTable for information about format of the result image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image. It must 24 or 32 bpp color image.
References AForge.Math.Geometry.Rectangle.
Apply() [2/2]
unsafe Bitmap AForge.Imaging.ColorReduction.OrderedColorDithering.Apply (UnmanagedImage sourceImage) inline
Perform color dithering for the specified image.
Parameters
sourceImage Source image to do color dithering for.
Returns
Returns color dithered image. See ColorTable for information about format of the result image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image. It must 24 or 32 bpp color image.
References AForge.Imaging.RGB.B, AForge.Imaging.ColorReduction.OrderedColorDithering.cache, AForge.Imaging.ColorReduction.OrderedColorDithering.colorTable, AForge.Imaging.RGB.G, AForge.Imaging.ColorReduction.OrderedColorDithering.GetClosestColor(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.ColorReduction.OrderedColorDithering.matrix, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, AForge.Math.Geometry.Rectangle, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
GetClosestColor()
Color AForge.Imaging.ColorReduction.OrderedColorDithering.GetClosestColor (int red, int green, int blue, out byte colorIndex) inline private
References AForge.Imaging.ColorReduction.OrderedColorDithering.cache, AForge.Imaging.ColorReduction.OrderedColorDithering.colorTable, and AForge.Imaging.ColorReduction.OrderedColorDithering.useCaching.
Referenced by AForge.Imaging.ColorReduction.OrderedColorDithering.Apply().
Member Data Documentation
useCaching
bool AForge.Imaging.ColorReduction.OrderedColorDithering.useCaching = false private
Referenced by AForge.Imaging.ColorReduction.OrderedColorDithering.GetClosestColor().
colorTable
Color [] AForge.Imaging.ColorReduction.OrderedColorDithering.colorTable private
Initial value:
= new Color[16]
        {
            Color.Black,   Color.DarkBlue,    Color.DarkGreen, Color.DarkCyan,
            Color.DarkRed, Color.DarkMagenta, Color.DarkKhaki, Color.LightGray,
            Color.Gray,    Color.Blue,        Color.Green,     Color.Cyan,
            Color.Red,     Color.Magenta,     Color.Yellow,    Color.White
        }
Referenced by AForge.Imaging.ColorReduction.OrderedColorDithering.Apply(), and AForge.Imaging.ColorReduction.OrderedColorDithering.GetClosestColor().
matrix
byte [,] AForge.Imaging.ColorReduction.OrderedColorDithering.matrix private
Initial value:
= new byte[4, 4]
        {
            {  2, 18,  6, 22 },
            { 26, 10, 30, 14 },
            {  8, 24,  4, 20 },
            { 32, 16, 28, 12 }
        }
Referenced by AForge.Imaging.ColorReduction.OrderedColorDithering.Apply(), and AForge.Imaging.ColorReduction.OrderedColorDithering.OrderedColorDithering().
cache
Dictionary<Color, byte> AForge.Imaging.ColorReduction.OrderedColorDithering.cache = new Dictionary<Color, byte>() private
Referenced by AForge.Imaging.ColorReduction.OrderedColorDithering.Apply(), and AForge.Imaging.ColorReduction.OrderedColorDithering.GetClosestColor().
Property Documentation
ThresholdMatrix
byte [,] AForge.Imaging.ColorReduction.OrderedColorDithering.ThresholdMatrix get set
Threshold matrix - values to add source image's values.
The property keeps a threshold matrix, which is applied to values of a source image to dither. By adding these values to the source image the algorithm produces the effect when pixels of the same color in source image may have different color in the result image (which depends on pixel's position). This threshold map is also known as an index matrix or Bayer matrix.
By default the property is inialized with the below matrix:
 2   18    6   22
26   10   30   14
 8   24    4   20
32   16   28   12
Referenced by AForge.Imaging.ColorReduction.OrderedColorDithering.OrderedColorDithering().
ColorTable
Color [] AForge.Imaging.ColorReduction.OrderedColorDithering.ColorTable get set
Color table to use for image dithering. Must contain 2-256 colors.
Color table size determines format of the resulting image produced by this image processing routine. If color table contains 16 color or less, then result image will have 4 bpp indexed pixel format. If color table contains more than 16 colors, then result image will have 8 bpp indexed pixel format.
By default the property is initialized with default 16 colors, which are: Black, Dark Blue, Dark Green, Dark Cyan, Dark Red, Dark Magenta, Dark Khaki, Light Gray, Gray, Blue, Green, Cyan, Red, Magenta, Yellow and White.
Exceptions
ArgumentException Color table length must be in the [2, 256] range.
UseCaching
bool AForge.Imaging.ColorReduction.OrderedColorDithering.UseCaching get set
Use color caching during color dithering or not.
The property specifies if internal cache of already processed colors should be used or not. For each pixel in the original image the color dithering routine does search in target color palette to find the best matching color. To avoid doing the search again and again for already processed colors, the class may use internal dictionary which maps colors of original image to indexes in target color palette.
<note>The property provides a trade off. On one hand it may speedup color dithering routine, but on another hand it increases memory usage. Also cache usage may not be efficient for very small target color tables.</note>
Default value is set to false.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Color Reduction/OrderedColorDithering.cs