Doc: IGLib EXTENDED: IG.Gr3d.I3dGraphicsControl Interface Reference
IG.Gr3d.I3dGraphicsControl Interface Reference
Interface for 3D graphics controls that can be manipulated via a standard set of commands for rotation etc.
Public Member Functions
void ChangeZoom (double factor)
Changes CameraViewAngle by the factor defined by the specified factor.
void RotateAzimuth (double angleStepDegrees)
Rotates the camera in the fi direction.
void RotatePitch (double angleStepDegrees)
Rotates the camera in the theta direction.
void RotateRoll (double angleStepDegrees)
Rotates the camera around the viewing direction.
Properties
double RotationStep [get, set]
double ZoomFactor [get, set]
Zoom step, in degrees, that is used in a single zoom operation.
double CameraViewAngle [get, set]
Viewing angle of the camera, in degrees (defines the zoom level).
double CameraRoll [get, set]
Roll of the camera (amount of rotation abount viewing direction)
vec3 CameraPosition [get, set]
Gets or sets camera position.
vec3 CameraFocalPoint [get, set]
Gets or sets camera focal point.
vec3 CameraViewUp [get, set]
Gets or sets the camera viewing up position.
vec3 CameraDirection [get, set]
Camera direction.
vec3 CameraDirectionSpherical [get, set]
Gets or sets camera direction in spherical coordinates.
Detailed Description
Interface for 3D graphics controls that can be manipulated via a standard set of commands for rotation etc.
$A Igor xx;
Member Function Documentation
ChangeZoom()
void IG.Gr3d.I3dGraphicsControl.ChangeZoom (double factor)
Changes CameraViewAngle by the factor defined by the specified factor.
Parameters
factor Factor by which the view angle is increased (must be greater than 1).
Implemented in IG.Gr3d.VtkControlBase.
Referenced by IG.Gr3d.Graph3dManipulator.btnZoomIn_Click(), and IG.Gr3d.Graph3dManipulator.btnZoomOut_Click().
RotateAzimuth()
void IG.Gr3d.I3dGraphicsControl.RotateAzimuth (double angleStepDegrees)
Rotates the camera in the fi direction.
Parameters
angleStepDegrees Step, in degrees, by which the camera is rotated clockwise.
Implemented in IG.Gr3d.VtkControlBase.
Referenced by IG.Gr3d.Graph3dManipulator.btnDownLeft_Click(), IG.Gr3d.Graph3dManipulator.btnDownRight_Click(), IG.Gr3d.Graph3dManipulator.btnLeft_Click(), IG.Gr3d.Graph3dManipulator.btnRight_Click(), IG.Gr3d.Graph3dManipulator.btnUpLeft_Click(), and IG.Gr3d.Graph3dManipulator.btnUpRight_Click().
RotatePitch()
void IG.Gr3d.I3dGraphicsControl.RotatePitch (double angleStepDegrees)
Rotates the camera in the theta direction.
Parameters
angleStepDegrees Step, in degrees, by which the camera is rotated.
Implemented in IG.Gr3d.VtkControlBase.
Referenced by IG.Gr3d.Graph3dManipulator.btnDown_Click(), IG.Gr3d.Graph3dManipulator.btnDownLeft_Click(), IG.Gr3d.Graph3dManipulator.btnDownRight_Click(), IG.Gr3d.Graph3dManipulator.btnUp_Click(), IG.Gr3d.Graph3dManipulator.btnUpLeft_Click(), and IG.Gr3d.Graph3dManipulator.btnUpRight_Click().
RotateRoll()
void IG.Gr3d.I3dGraphicsControl.RotateRoll (double angleStepDegrees)
Rotates the camera around the viewing direction.
Parameters
angleStepDegrees Step, in degrees, by which the camera is rotated.
Implemented in IG.Gr3d.VtkControlBase.
Referenced by IG.Gr3d.Graph3dManipulator.btnRollClockwise_Click(), and IG.Gr3d.Graph3dManipulator.btnRollCounterClockwise_Click().
Property Documentation
RotationStep
double IG.Gr3d.I3dGraphicsControl.RotationStep get set
Referenced by IG.Gr3d.Graph3dManipulator.btnDown_Click(), IG.Gr3d.Graph3dManipulator.btnDownLeft_Click(), IG.Gr3d.Graph3dManipulator.btnDownRight_Click(), IG.Gr3d.Graph3dManipulator.btnLeft_Click(), IG.Gr3d.Graph3dManipulator.btnRight_Click(), IG.Gr3d.Graph3dManipulator.btnRollClockwise_Click(), IG.Gr3d.Graph3dManipulator.btnRollCounterClockwise_Click(), IG.Gr3d.Graph3dManipulator.btnUp_Click(), IG.Gr3d.Graph3dManipulator.btnUpLeft_Click(), IG.Gr3d.Graph3dManipulator.btnUpRight_Click(), IG.Gr3d.Graph3dManipulator.txtRotationStep_Validated(), and IG.Gr3d.Graph3dManipulator.UpdateTextFields().
ZoomFactor
double IG.Gr3d.I3dGraphicsControl.ZoomFactor get set
Zoom step, in degrees, that is used in a single zoom operation.
Must be greater than 1.
Referenced by IG.Gr3d.Graph3dManipulator.btnZoomIn_Click(), IG.Gr3d.Graph3dManipulator.btnZoomOut_Click(), IG.Gr3d.Graph3dManipulator.txtZoomFactor_Validated(), and IG.Gr3d.Graph3dManipulator.UpdateTextFields().
CameraViewAngle
double IG.Gr3d.I3dGraphicsControl.CameraViewAngle get set
Viewing angle of the camera, in degrees (defines the zoom level).
Parameters
angleStepDegrees Step, in degrees, by which the camera is rotated.
Referenced by IG.Gr3d.Graph3dManipulator.txtViewAngle_Validated(), and IG.Gr3d.Graph3dManipulator.UpdateTextFields().
CameraRoll
double IG.Gr3d.I3dGraphicsControl.CameraRoll get set
Roll of the camera (amount of rotation abount viewing direction)
Referenced by IG.Gr3d.Graph3dManipulator.txtRoll_Validated(), and IG.Gr3d.Graph3dManipulator.UpdateTextFields().
CameraPosition
vec3 IG.Gr3d.I3dGraphicsControl.CameraPosition get set
Gets or sets camera position.
CameraFocalPoint
vec3 IG.Gr3d.I3dGraphicsControl.CameraFocalPoint get set
Gets or sets camera focal point.
CameraViewUp
vec3 IG.Gr3d.I3dGraphicsControl.CameraViewUp get set
Gets or sets the camera viewing up position.
CameraDirection
vec3 IG.Gr3d.I3dGraphicsControl.CameraDirection get set
Camera direction.
Getter obtains it as difference between the camera focal point and camera position.
Setter sets the camera focal points in such a way that camera direction has the specified value.
CameraDirectionSpherical
vec3 IG.Gr3d.I3dGraphicsControl.CameraDirectionSpherical get set
Gets or sets camera direction in spherical coordinates.
Referenced by IG.Gr3d.Graph3dManipulator.txtFi_Validated(), IG.Gr3d.Graph3dManipulator.txtR_Validated(), IG.Gr3d.Graph3dManipulator.txtTheta_Validated(), and IG.Gr3d.Graph3dManipulator.UpdateTextFields().
The documentation for this interface was generated from the following file:
iglib/extensions/igplot3d/plot3d/vtkbased/Forms/testforms/I3dGraphicsControl.cs