Doc: IGLib EXTENDED: Meta.Numerics.Statistics.Distributions.PearsonRDistribution Class Reference
Meta.Numerics.Statistics.Distributions.PearsonRDistribution Class Reference
Represents the distribution of Pearsons's r statistic.
Public Member Functions
PearsonRDistribution (int n)
Initializes a new instance of the Pearson r distribution for the given number of pairs.
override double ProbabilityDensity (double x)
Returns the probability density at the given point.
override double MomentAboutMean (int r)
Computes a central moment of the distribution.
override double Moment (int r)
Computes a raw moment of the distribution.
override double LeftProbability (double x)
Returns the cumulative probability to the left of (below) the given point.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double RightProbability (double x)
Return the cumulative probability to the right of (above) the given point.
virtual double InverseLeftProbability (double P)
Returns the point at which the cumulative distribution function attains a given value.
virtual double InverseRightProbability (double Q)
Returns the point at which the right probability function attains the given value.
virtual double ExpectationValue (Func< double, double > f)
Computes the expectation value of the given function.
virtual double GetRandomValue (Random rng)
Returns a random value.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Cumulant (int r)
Computes a cumulant of the distribution.
Properties
override Interval Support [get]
override double Mean [get]
override double Variance [get]
override double Skewness [get]
Properties inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double Median [get]
Gets the median of the distribution.
virtual Interval Support [get]
Gets the interval over which the distribution is nonvanishing.
Properties inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Mean [get]
Gets the mean of the distribution.
virtual double Variance [get]
Gets the variance of the distribution.
virtual double StandardDeviation [get]
Gets the standard deviation of the distribution.
virtual double Skewness [get]
Gets the skewness of the distribution.
virtual double ExcessKurtosis [get]
Gets the excess kurtosis of the distribution.
Private Attributes
int n
Detailed Description
Represents the distribution of Pearsons's r statistic.
Constructor & Destructor Documentation
PearsonRDistribution()
Meta.Numerics.Statistics.Distributions.PearsonRDistribution.PearsonRDistribution (int n) inline
Initializes a new instance of the Pearson r distribution for the given number of pairs.
Parameters
n The number of pairs, which must be three or more.
References Meta.Numerics.Statistics.Distributions.PearsonRDistribution.n.
Member Function Documentation
ProbabilityDensity()
override double Meta.Numerics.Statistics.Distributions.PearsonRDistribution.ProbabilityDensity (double x) inline virtual
Returns the probability density at the given point.
Implements Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Functions.AdvancedMath.Beta(), and Meta.Numerics.Statistics.Distributions.PearsonRDistribution.n.
MomentAboutMean()
override double Meta.Numerics.Statistics.Distributions.PearsonRDistribution.MomentAboutMean (int r) inline virtual
Computes a central moment of the distribution.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.PearsonRDistribution.n.
Referenced by Meta.Numerics.Statistics.Distributions.PearsonRDistribution.Moment().
Moment()
override double Meta.Numerics.Statistics.Distributions.PearsonRDistribution.Moment (int r) inline virtual
Computes a raw moment of the distribution.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.PearsonRDistribution.MomentAboutMean().
LeftProbability()
override double Meta.Numerics.Statistics.Distributions.PearsonRDistribution.LeftProbability (double x) inline virtual
Returns the cumulative probability to the left of (below) the given point.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Functions.AdvancedMath.Beta(), and Meta.Numerics.Statistics.Distributions.PearsonRDistribution.n.
Member Data Documentation
n
int Meta.Numerics.Statistics.Distributions.PearsonRDistribution.n private
Referenced by Meta.Numerics.Statistics.Distributions.PearsonRDistribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.PearsonRDistribution.MomentAboutMean(), Meta.Numerics.Statistics.Distributions.PearsonRDistribution.PearsonRDistribution(), and Meta.Numerics.Statistics.Distributions.PearsonRDistribution.ProbabilityDensity().
Property Documentation
Support
override Interval Meta.Numerics.Statistics.Distributions.PearsonRDistribution.Support get
Mean
override double Meta.Numerics.Statistics.Distributions.PearsonRDistribution.Mean get
Variance
override double Meta.Numerics.Statistics.Distributions.PearsonRDistribution.Variance get
Skewness
override double Meta.Numerics.Statistics.Distributions.PearsonRDistribution.Skewness get
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/Distributions/PearsonRDistribution.cs