Doc: IGLib EXTENDED: NUnit.Framework.Assertions.GreaterEqualFixture Class Reference
NUnit.Framework.Assertions.GreaterEqualFixture Class Reference
Public Member Functions
void GreaterOrEqual_Int32 ()
void GreaterOrEqual_UInt32 ()
void GreaterOrEqual_Long ()
void GreaterOrEqual_ULong ()
void GreaterOrEqual_Double ()
void GreaterOrEqual_Decimal ()
void GreaterOrEqual_Float ()
void MixedTypes ()
void NotGreaterOrEqual ()
void NotGreaterEqualIComparable ()
void FailureMessage ()
Private Attributes
readonly int i1 = 5
readonly int i2 = 4
readonly uint u1 = 12345879
readonly uint u2 = 12345678
readonly long l1 = 12345879
readonly long l2 = 12345678
readonly ulong ul1 = 12345879
readonly ulong ul2 = 12345678
readonly float f1 = 3.543F
readonly float f2 = 2.543F
readonly decimal de1 = 53.4M
readonly decimal de2 = 33.4M
readonly double d1 = 4.85948654
readonly double d2 = 1.0
readonly System.Enum e1 = RunState.Explicit
readonly System.Enum e2 = RunState.Ignored
Member Function Documentation
GreaterOrEqual_Int32()
void NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_Int32 () inline
References NUnit.Framework.Assert.GreaterOrEqual(), NUnit.Framework.Assertions.GreaterEqualFixture.i1, and NUnit.Framework.Assertions.GreaterEqualFixture.i2.
GreaterOrEqual_UInt32()
void NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_UInt32 () inline
References NUnit.Framework.Assert.GreaterOrEqual(), NUnit.Framework.Assertions.GreaterEqualFixture.u1, and NUnit.Framework.Assertions.GreaterEqualFixture.u2.
GreaterOrEqual_Long()
void NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_Long () inline
References NUnit.Framework.Assert.GreaterOrEqual(), NUnit.Framework.Assertions.GreaterEqualFixture.l1, and NUnit.Framework.Assertions.GreaterEqualFixture.l2.
GreaterOrEqual_ULong()
void NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_ULong () inline
References NUnit.Framework.Assert.GreaterOrEqual(), NUnit.Framework.Assertions.GreaterEqualFixture.ul1, and NUnit.Framework.Assertions.GreaterEqualFixture.ul2.
GreaterOrEqual_Double()
void NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_Double () inline
References NUnit.Framework.Assertions.GreaterEqualFixture.d1, NUnit.Framework.Assertions.GreaterEqualFixture.d2, and NUnit.Framework.Assert.GreaterOrEqual().
GreaterOrEqual_Decimal()
void NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_Decimal () inline
References NUnit.Framework.Assertions.GreaterEqualFixture.de1, NUnit.Framework.Assertions.GreaterEqualFixture.de2, and NUnit.Framework.Assert.GreaterOrEqual().
GreaterOrEqual_Float()
void NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_Float () inline
References NUnit.Framework.Assertions.GreaterEqualFixture.f1, NUnit.Framework.Assertions.GreaterEqualFixture.f2, and NUnit.Framework.Assert.GreaterOrEqual().
MixedTypes()
void NUnit.Framework.Assertions.GreaterEqualFixture.MixedTypes () inline
References NUnit.Framework.Assert.GreaterOrEqual().
NotGreaterOrEqual()
void NUnit.Framework.Assertions.GreaterEqualFixture.NotGreaterOrEqual () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.GreaterOrEqual(), NUnit.Framework.Assertions.GreaterEqualFixture.i1, NUnit.Framework.Assertions.GreaterEqualFixture.i2, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
NotGreaterEqualIComparable()
void NUnit.Framework.Assertions.GreaterEqualFixture.NotGreaterEqualIComparable () inline
References NUnit.Framework.Assertions.GreaterEqualFixture.e1, NUnit.Framework.Assertions.GreaterEqualFixture.e2, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.GreaterOrEqual(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
FailureMessage()
void NUnit.Framework.Assertions.GreaterEqualFixture.FailureMessage () inline
References NUnit.Framework.StringAssert.Contains(), NUnit.Framework.Assert.GreaterOrEqual(), NUnit.Framework.Internal.TextMessageWriter.Pfx_Actual, and NUnit.Framework.Internal.TextMessageWriter.Pfx_Expected.
Member Data Documentation
i1
readonly int NUnit.Framework.Assertions.GreaterEqualFixture.i1 = 5 private
Referenced by NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_Int32(), and NUnit.Framework.Assertions.GreaterEqualFixture.NotGreaterOrEqual().
i2
readonly int NUnit.Framework.Assertions.GreaterEqualFixture.i2 = 4 private
Referenced by NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_Int32(), and NUnit.Framework.Assertions.GreaterEqualFixture.NotGreaterOrEqual().
u1
readonly uint NUnit.Framework.Assertions.GreaterEqualFixture.u1 = 12345879 private
Referenced by NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_UInt32().
u2
readonly uint NUnit.Framework.Assertions.GreaterEqualFixture.u2 = 12345678 private
Referenced by NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_UInt32().
l1
readonly long NUnit.Framework.Assertions.GreaterEqualFixture.l1 = 12345879 private
Referenced by NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_Long().
l2
readonly long NUnit.Framework.Assertions.GreaterEqualFixture.l2 = 12345678 private
Referenced by NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_Long().
ul1
readonly ulong NUnit.Framework.Assertions.GreaterEqualFixture.ul1 = 12345879 private
Referenced by NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_ULong().
ul2
readonly ulong NUnit.Framework.Assertions.GreaterEqualFixture.ul2 = 12345678 private
Referenced by NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_ULong().
f1
readonly float NUnit.Framework.Assertions.GreaterEqualFixture.f1 = 3.543F private
Referenced by NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_Float().
f2
readonly float NUnit.Framework.Assertions.GreaterEqualFixture.f2 = 2.543F private
Referenced by NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_Float().
de1
readonly decimal NUnit.Framework.Assertions.GreaterEqualFixture.de1 = 53.4M private
Referenced by NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_Decimal().
de2
readonly decimal NUnit.Framework.Assertions.GreaterEqualFixture.de2 = 33.4M private
Referenced by NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_Decimal().
d1
readonly double NUnit.Framework.Assertions.GreaterEqualFixture.d1 = 4.85948654 private
Referenced by NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_Double().
d2
readonly double NUnit.Framework.Assertions.GreaterEqualFixture.d2 = 1.0 private
Referenced by NUnit.Framework.Assertions.GreaterEqualFixture.GreaterOrEqual_Double().
e1
readonly System.Enum NUnit.Framework.Assertions.GreaterEqualFixture.e1 = RunState.Explicit private
Referenced by NUnit.Framework.Assertions.GreaterEqualFixture.NotGreaterEqualIComparable().
e2
readonly System.Enum NUnit.Framework.Assertions.GreaterEqualFixture.e2 = RunState.Ignored private
Referenced by NUnit.Framework.Assertions.GreaterEqualFixture.NotGreaterEqualIComparable().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/GreaterEqualFixture.cs