Doc: IGLib EXTENDED: alglib.testmincgunit Class Reference
alglib.testmincgunit Class Reference
Static Public Member Functions
static bool testmincg (bool silent)
static void testother (ref bool err)
static bool testmincg (bool silent)
static bool _pexec_testmincg (bool silent)
static void testother (ref bool err)
Static Private Member Functions
static void testfunc1 (mincg.mincgstate state)
static void testfunc2 (mincg.mincgstate state)
static void testfunc3 (mincg.mincgstate state)
static void calciip2 (mincg.mincgstate state, int n)
static void calclowrank (mincg.mincgstate state, int n, int vcnt, double[] d, double[,] v, double[] vd, double[] x0)
static void testpreconditioning (ref bool err)
static bool gradientchecktest ()
static void funcderiv (double a, double b, double c, double d, double x0, double x1, double x2, double[] x, int functype, ref double f, ref double[] g)
static void testfunc1 (mincg.mincgstate state)
static void testfunc2 (mincg.mincgstate state)
static void testfunc3 (mincg.mincgstate state)
static void calciip2 (mincg.mincgstate state, int n)
static void calclowrank (mincg.mincgstate state, int n, int vcnt, double[] d, double[,] v, double[] vd, double[] x0)
static void testpreconditioning (ref bool err)
static bool gradientchecktest ()
static void funcderiv (double a, double b, double c, double d, double x0, double x1, double x2, double[] x, int functype, ref double f, ref double[] g)
Member Function Documentation
testmincg() [1/2]
static bool alglib.testmincgunit.testmincg (bool silent) inline static
References alglib.testmincgunit.gradientchecktest(), alglib.mincg.mincgcreate(), alglib.mincg.mincgcreatef(), alglib.mincg.mincgiteration(), alglib.mincg.mincgrestartfrom(), alglib.mincg.mincgresults(), alglib.mincg.mincgsetcgtype(), alglib.mincg.mincgsetcond(), alglib.mincg.mincgsetstpmax(), alglib.math.randomreal(), alglib.math.sqr(), alglib.testmincgunit.testfunc2(), alglib.testmincgunit.testfunc3(), alglib.testmincgunit.testother(), and alglib.testmincgunit.testpreconditioning().
Referenced by alglib.testmincgunit._pexec_testmincg(), and _Test.Main().
testother() [1/2]
static void alglib.testmincgunit.testother (ref bool err) inline static
References alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.mincg.mincgcreate(), alglib.mincg.mincgcreatef(), alglib.mincg.mincgiteration(), alglib.mincg.mincgrestartfrom(), alglib.mincg.mincgresults(), alglib.mincg.mincgsetcgtype(), alglib.mincg.mincgsetcond(), alglib.mincg.mincgsetprecdiag(), alglib.mincg.mincgsetprecscale(), alglib.mincg.mincgsetscale(), alglib.mincg.mincgsetstpmax(), alglib.mincg.mincgsetxrep(), alglib.math.randomreal(), and alglib.math.sqr().
Referenced by alglib.testmincgunit.testmincg().
testfunc1() [1/2]
static void alglib.testmincgunit.testfunc1 (mincg.mincgstate state) inline static private
References alglib.math.maxrealnumber, and alglib.math.sqr().
testfunc2() [1/2]
static void alglib.testmincgunit.testfunc2 (mincg.mincgstate state) inline static private
References alglib.math.maxrealnumber, and alglib.math.sqr().
Referenced by alglib.testmincgunit.testmincg().
testfunc3() [1/2]
static void alglib.testmincgunit.testfunc3 (mincg.mincgstate state) inline static private
References alglib.math.maxrealnumber, and alglib.math.sqr().
Referenced by alglib.testmincgunit.testmincg().
calciip2() [1/2]
static void alglib.testmincgunit.calciip2 (mincg.mincgstate state, int n) inline static private
References alglib.math.sqr().
Referenced by alglib.testmincgunit.testpreconditioning().
calclowrank() [1/2]
static void alglib.testmincgunit.calclowrank (mincg.mincgstate state, int n, int vcnt, double[] d, double v[,], double[] vd, double[] x0) inline static private
Referenced by alglib.testmincgunit.testpreconditioning().
testpreconditioning() [1/2]
static void alglib.testmincgunit.testpreconditioning (ref bool err) inline static private
References alglib.testmincgunit.calciip2(), alglib.testmincgunit.calclowrank(), alglib.mincg.mincgcreate(), alglib.mincg.mincgiteration(), alglib.mincg.mincgrestartfrom(), alglib.mincg.mincgresults(), alglib.mincg.mincgsetcgtype(), alglib.mincg.mincgsetprecdefault(), alglib.mincg.mincgsetprecdiag(), alglib.mincg.mincgsetpreclowrankfast(), alglib.mincg.mincgsetprecscale(), alglib.mincg.mincgsetscale(), alglib.math.randomreal(), and alglib.math.sqr().
Referenced by alglib.testmincgunit.testmincg().
gradientchecktest() [1/2]
static bool alglib.testmincgunit.gradientchecktest () inline static private
References alglib.testmincgunit.funcderiv(), alglib.mincg.mincgcreate(), alglib.mincg.mincgiteration(), alglib.mincg.mincgrestartfrom(), alglib.mincg.mincgresults(), alglib.mincg.mincgsetcond(), alglib.mincg.mincgsetgradientcheck(), alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testmincgunit.testmincg().
funcderiv() [1/2]
static void alglib.testmincgunit.funcderiv (double a, double b, double c, double d, double x0, double x1, double x2, double[] x, int functype, ref double f, ref double[] g) inline static private
References alglib.ap.assert(), alglib.math.isfinite(), and alglib.math.sqr().
Referenced by alglib.testmincgunit.gradientchecktest().
testmincg() [2/2]
static bool alglib.testmincgunit.testmincg (bool silent) inline static
References alglib.testmincgunit.gradientchecktest(), alglib.mincg.mincgcreate(), alglib.mincg.mincgcreatef(), alglib.mincg.mincgiteration(), alglib.mincg.mincgrestartfrom(), alglib.mincg.mincgresults(), alglib.mincg.mincgsetcgtype(), alglib.mincg.mincgsetcond(), alglib.mincg.mincgsetstpmax(), alglib.math.randomreal(), alglib.math.sqr(), alglib.testmincgunit.testfunc2(), alglib.testmincgunit.testfunc3(), alglib.testmincgunit.testother(), and alglib.testmincgunit.testpreconditioning().
_pexec_testmincg()
static bool alglib.testmincgunit._pexec_testmincg (bool silent) inline static
References alglib.testmincgunit.testmincg().
Referenced by _Test.Main().
testother() [2/2]
static void alglib.testmincgunit.testother (ref bool err) inline static
References alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.mincg.mincgcreate(), alglib.mincg.mincgcreatef(), alglib.mincg.mincgiteration(), alglib.mincg.mincgrestartfrom(), alglib.mincg.mincgresults(), alglib.mincg.mincgsetcgtype(), alglib.mincg.mincgsetcond(), alglib.mincg.mincgsetprecdiag(), alglib.mincg.mincgsetprecscale(), alglib.mincg.mincgsetscale(), alglib.mincg.mincgsetstpmax(), alglib.mincg.mincgsetxrep(), alglib.math.randomreal(), and alglib.math.sqr().
testfunc1() [2/2]
static void alglib.testmincgunit.testfunc1 (mincg.mincgstate state) inline static private
References alglib.math.maxrealnumber, and alglib.math.sqr().
testfunc2() [2/2]
static void alglib.testmincgunit.testfunc2 (mincg.mincgstate state) inline static private
References alglib.math.maxrealnumber, and alglib.math.sqr().
testfunc3() [2/2]
static void alglib.testmincgunit.testfunc3 (mincg.mincgstate state) inline static private
References alglib.math.maxrealnumber, and alglib.math.sqr().
calciip2() [2/2]
static void alglib.testmincgunit.calciip2 (mincg.mincgstate state, int n) inline static private
References alglib.math.sqr().
calclowrank() [2/2]
static void alglib.testmincgunit.calclowrank (mincg.mincgstate state, int n, int vcnt, double[] d, double v[,], double[] vd, double[] x0) inline static private
testpreconditioning() [2/2]
static void alglib.testmincgunit.testpreconditioning (ref bool err) inline static private
References alglib.testmincgunit.calciip2(), alglib.testmincgunit.calclowrank(), alglib.mincg.mincgcreate(), alglib.mincg.mincgiteration(), alglib.mincg.mincgrestartfrom(), alglib.mincg.mincgresults(), alglib.mincg.mincgsetcgtype(), alglib.mincg.mincgsetprecdefault(), alglib.mincg.mincgsetprecdiag(), alglib.mincg.mincgsetpreclowrankfast(), alglib.mincg.mincgsetprecscale(), alglib.mincg.mincgsetscale(), alglib.math.randomreal(), and alglib.math.sqr().
gradientchecktest() [2/2]
static bool alglib.testmincgunit.gradientchecktest () inline static private
References alglib.testmincgunit.funcderiv(), alglib.mincg.mincgcreate(), alglib.mincg.mincgiteration(), alglib.mincg.mincgrestartfrom(), alglib.mincg.mincgresults(), alglib.mincg.mincgsetcond(), alglib.mincg.mincgsetgradientcheck(), alglib.math.randominteger(), alglib.apserv.randomnormal(), and alglib.math.randomreal().
funcderiv() [2/2]
static void alglib.testmincgunit.funcderiv (double a, double b, double c, double d, double x0, double x1, double x2, double[] x, int functype, ref double f, ref double[] g) inline static private
References alglib.ap.assert(), alglib.math.isfinite(), and alglib.math.sqr().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs