Doc: IGLib EXTENDED: Meta.Numerics.Interval Struct Reference
Meta.Numerics.Interval Struct Reference
Represents an interval on the real number line.
Public Member Functions
bool OpenContains (double x)
Determines whether the argument lies in the open interval.
bool ClosedContains (double x)
Determines whether the argument lies in the closed interval.
override bool Equals (object obj)
Determines whether a given object is an equal interval.
override int GetHashCode ()
override string ToString ()
Produces a string representation of the interval.
Static Public Member Functions
static Interval FromEndpoints (double a, double b)
Creates a new interval, given its endpoints.
static Interval FromEndpointAndWidth (double endpoint, double width)
Creates a new interval, given its lower endpoint and width.
static Interval FromMidpointAndWidth (double midpoint, double width)
Creates a new interval, given its midpoint and width.
static bool operator== (Interval i1, Interval i2)
Determines whether two intervals are equal.
static bool operator!= (Interval i1, Interval i2)
Determines whether two intervals are not equal.
Public Attributes
double b
double w
Properties
double LeftEndpoint [get]
Gets the left (lower) endpoint of the interval.
double RightEndpoint [get]
Gets the right (upper) endpoint of the interval.
double Width [get]
Gets the width of the interval.
double Midpoint [get]
Gets the mid-point of the interval.
Private Member Functions
Interval (double a, double b, double w)
Private Attributes
double a
Detailed Description
Represents an interval on the real number line.
Use the static methods FromEndpoints, FromMidpointAndWidth, and FromEndpointAndWidth to instantiate intervals.
Constructor & Destructor Documentation
Interval()
Meta.Numerics.Interval.Interval (double a, double b, double w) inline private
References Meta.Numerics.Interval.a, Meta.Numerics.Interval.b, and Meta.Numerics.Interval.w.
Referenced by Meta.Numerics.Interval.Equals(), Meta.Numerics.Interval.FromEndpointAndWidth(), Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Interval.FromMidpointAndWidth().
Member Function Documentation
OpenContains()
bool Meta.Numerics.Interval.OpenContains (double x) inline
Determines whether the argument lies in the open interval.
Parameters
x The argument.
Returns
True if x lies in (a,b), otherwise False.
References Meta.Numerics.Interval.a, and Meta.Numerics.Interval.b.
Referenced by Test.IntervalTest.IntervalOpenContains().
ClosedContains()
bool Meta.Numerics.Interval.ClosedContains (double x) inline
Determines whether the argument lies in the closed interval.
Parameters
x The argument.
Returns
True if x lies in [a,b], otherwise False.
References Meta.Numerics.Interval.a, and Meta.Numerics.Interval.b.
Referenced by Test.IntervalTest.IntervalClosedContains(), Test.BivariateSampleTest.LinearLogisticRegression(), Meta.Numerics.Statistics.Distributions.UniformDistribution.ProbabilityDensity(), Test.SampleTest.SampleMoments(), and Test.MultiIntegrateTest.SteinmetzVolume().
FromEndpoints()
static Interval Meta.Numerics.Interval.FromEndpoints (double a, double b) inline static
Creates a new interval, given its endpoints.
Parameters
a The left (lower) endpoint of the interval.
b The right (upper) endpoint of the interval.
Returns
The specified interval.
If width of the interval is very much smaller than its endpoint values, accuracy will be better maintained by constructing the interval using one endpoint and its width.
References Meta.Numerics.Interval.a, Meta.Numerics.Interval.b, and Meta.Numerics.Interval.Interval().
Referenced by Test.MultiExtremumTest.Ackley(), Test.AdvancedMathTest.AiryBairyIntegral(), Test.AdvancedMathTest.AiryIntegral(), Test.AdvancedMathTest.AiryIntegrals(), Test.OrthogonalPolynomialsTest.AssociatedLaguerreOrthonormality(), Test.OrthogonalPolynomialsTest.AssociatedLegendreOrthonormalityL(), Test.AdvancedMathTest.BesselJ0Integral(), Test.AdvancedMathTest.BesselKapteynIntegral(), Test.AdvancedMathTest.BesselLipshitzIntegral(), Test.AdvancedMathTest.BesselWeberIntegral(), Test.AdvancedMathTest.BesselY0Integral(), Test.AdvancedMathTest.BetaIntegral(), Test.MultiExtremumTest.Bukin(), Test.AdvancedMathTest.CatalanIntegralTest(), Test.AdvancedMathTest.ClausenIntegral(), Test.AdvancedMathTest.DawsonIntegralTest(), Test.AdvancedMathTest.DiLogExpIntegral(), Test.AdvancedMathTest.DiLogLogIntegral(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.DiscreteAsContinuousDistribution(), Test.DistributionTest.DistributionProbabilityIntegral(), Test.MultiExtremumTest.Easom(), Test.AdvancedMathTest.EllipticEIntegration(), Test.AdvancedMathTest.EllipticFIntegral(), Test.AdvancedMathTest.EllipticFIntegration(), Test.AdvancedMathTest.EllipticKCatalanIntegral(), Test.AdvancedMathTest.EllipticKIntegration(), Test.AdvancedMathTest.ErfcIntegral(), Test.AdvancedMathTest.ErfIntegralTest(), Meta.Numerics.Statistics.BinaryContingencyTable.FisherExactTest(), Test.DataSetTest.FitDataToLinearFunctionTest(), Test.DataSetTest.FitDataToLineChiSquaredTest(), Test.DataSetTest.FitDataToLineTest(), Test.DataSetTest.FitDataToPolynomialChiSquaredTest(), Test.DataSetTest.FitDataToPolynomialTest(), Test.DataSetTest.FitDataToProportionalityTest(), Test.DataSetTest.FitToFunctionLinearCompatibilityTest(), Test.DataSetTest.FitToFunctionPolynomialCompatibilityTest(), Test.AdvancedMathTest.FresnelCIntegralTest(), Test.AdvancedMathTest.FresnelSIntegralTest(), Test.IntervalTest.FromTest(), Test.AdvancedMathTest.GammaIntegral(), Test.MultiIntegrateTest.GaussianIntegrals(), Test.DistributionTest.GetDistributions(), Test.MultiExtremumTest.GoldsteinPrice(), Test.MultiExtremumTest.Griewank(), Test.OrthogonalPolynomialsTest.HermiteOrthonormality(), Test.AdvancedMathTest.IntegerBesselJIntegral(), Test.AdvancedMathTest.IntegralCiSiIntegrals(), Test.AdvancedMathTest.IntegralEIntegral(), Test.AdvancedMathTest.IntegralSiDefinition(), Meta.Numerics.Analysis.FunctionMath.Integrate(), Meta.Numerics.Analysis.MultiFunctionMath.Integrate(), Test.IntervalTest.IntervalClosedContains(), Test.IntervalTest.IntervalEndpoints(), Test.IntervalTest.IntervalFromEndpoints(), Test.IntervalTest.IntervalMidpoint(), Test.IntervalTest.IntervalOpenContains(), Test.IntervalTest.IntervalWidth(), Test.IntervalTest.IntervalZeroWidth(), Test.AdvancedMathTest.InverseErfIntegralTest(), Test.MultiIntegrateTest.IsingIntegrals(), Meta.Numerics.Statistics.BivariateSample.KendallTauTest(), Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), Test.OrthogonalPolynomialsTest.LaguerreOrthonormality(), Meta.Numerics.Statistics.Distributions.Distribution.LeftProbability(), Test.OrthogonalPolynomialsTest.LegendreOrthonormality(), Test.AdvancedMathTest.ModifiedBesselIntegralTest(), Meta.Numerics.Statistics.Distributions.DiscreteInterval.operator Interval(), Test.MultiExtremumTest.PackCirclesInCircle(), Test.MultiExtremumTest.PackCirclesInSquare(), Test.MultiExtremumTest.PackSpheresInCube(), Test.AdvancedMathTest.PolyGammaIntegral(), Test.AdvancedMathTest.PolyLogIntegration(), Test.PolynomialTest.PolynomialCalculus(), Test.AdvancedMathTest.RealBesselJIntegral(), Test.RootsTest.RootOfEi(), Test.RootsTest.RootOfJ0(), Test.SampleTest.SampleKolmogorovSmirnovTest(), Test.MultiExtremumTest.Schwefel(), Meta.Numerics.Statistics.BivariateSample.SpearmanRhoTest(), FutureTest.FutureTest.STA(), Test.MultiIntegrateTest.SymmetricUnitCube(), FutureTest.FutureTest.TestNormalOrderStatistic(), FutureTest.FutureTest.TestOldMinimization(), Test.MultiExtremumTest.ThompsonProblem(), Test.SpinTest.ThreeJLegendreIntegral(), Test.IntervalTest.ToTest(), Meta.Numerics.Statistics.Distributions.UniformDistribution.UniformDistribution(), Test.MultiIntegrateTest.UnitCube(), Test.MultiIntegrateTest.WatsonIntegrals(), Test.OrthogonalPolynomialsTest.ZernikeBessel(), and Test.OrthogonalPolynomialsTest.ZernikeOrthonormality().
FromEndpointAndWidth()
static Interval Meta.Numerics.Interval.FromEndpointAndWidth (double endpoint, double width) inline static
Creates a new interval, given its lower endpoint and width.
Parameters
endpoint The left (lower) endpoint of the interval.
width The width of the interval.
Returns
The specified interval.
References Meta.Numerics.Interval.Interval().
FromMidpointAndWidth()
static Interval Meta.Numerics.Interval.FromMidpointAndWidth (double midpoint, double width) inline static
Creates a new interval, given its midpoint and width.
Parameters
midpoint The midpoint of the interval.
width The width of the interval.
Returns
The specified interval.
References Meta.Numerics.Interval.Interval().
Referenced by Meta.Numerics.UncertainValue.ConfidenceInterval(), and Test.IntervalTest.IntervalFromMidpointAndWidth().
operator==()
static bool Meta.Numerics.Interval.operator== (Interval i1, Interval i2) inline static
Determines whether two intervals are equal.
Parameters
i1 The first interval.
i2 The second interval.
Returns
True if i1 and i2 are equal, otherwise false.
References Meta.Numerics.Interval.a, and Meta.Numerics.Interval.w.
operator!=()
static bool Meta.Numerics.Interval.operator!= (Interval i1, Interval i2) inline static
Determines whether two intervals are not equal.
Parameters
i1 The first interval.
i2 The second interval.
Returns
True if i1 and i2 are not equal, otherwise false.
Equals()
override bool Meta.Numerics.Interval.Equals (object obj) inline
Determines whether a given object is an equal interval.
Parameters
obj An object.
Returns
True if obj is an equal Interval, otherwise false.
References Meta.Numerics.Interval.Interval().
GetHashCode()
override int Meta.Numerics.Interval.GetHashCode () inline
References Meta.Numerics.Interval.a, and Meta.Numerics.Interval.w.
Referenced by Test.IntervalTest.IntervalFromEndpoints().
ToString()
override string Meta.Numerics.Interval.ToString () inline
Produces a string representation of the interval.
Returns
A string representation of the interval.
References Meta.Numerics.Interval.a, and Meta.Numerics.Interval.b.
Member Data Documentation
a
double Meta.Numerics.Interval.a private
Referenced by Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Interval.GetHashCode(), Meta.Numerics.Interval.Interval(), Meta.Numerics.Interval.OpenContains(), Meta.Numerics.Interval.operator==(), and Meta.Numerics.Interval.ToString().
b
double Meta.Numerics.Interval.b
Referenced by Meta.Numerics.Interval.ClosedContains(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Interval.Interval(), Meta.Numerics.Interval.OpenContains(), and Meta.Numerics.Interval.ToString().
w
double Meta.Numerics.Interval.w
Referenced by Meta.Numerics.Interval.GetHashCode(), Meta.Numerics.Interval.Interval(), and Meta.Numerics.Interval.operator==().
Property Documentation
LeftEndpoint
double Meta.Numerics.Interval.LeftEndpoint get
Gets the left (lower) endpoint of the interval.
Referenced by Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.ComputeEffectiveBin(), Test.DistributionTest.DistributionProbabilityIntegral(), Meta.Numerics.Analysis.FunctionMath.FindMaximum(), Meta.Numerics.Analysis.FunctionMath.FindMinimum(), Meta.Numerics.Analysis.FunctionMath.FindZero(), Test.IntervalTest.FromTest(), Meta.Numerics.Analysis.FunctionMath.Integrate(), Meta.Numerics.Analysis.MultiFunctionMath.Integrate(), Test.IntervalTest.IntervalEndpoints(), Test.IntervalTest.IntervalFromEndpoints(), Test.IntervalTest.IntervalFromMidpointAndWidth(), Test.IntervalTest.IntervalZeroWidth(), Meta.Numerics.Statistics.Distributions.UniformDistribution.InverseProbability(), Meta.Numerics.Statistics.Distributions.Distribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.UniformDistribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.UniformDistribution.Moment(), Test.DistributionTest.OutsideDistributionSupport(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.ProbabilityDensity(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.RightProbability(), and Test.SampleTest.SampleInterquartileRange().
RightEndpoint
double Meta.Numerics.Interval.RightEndpoint get
Gets the right (upper) endpoint of the interval.
Referenced by Test.DistributionTest.DistributionProbabilityIntegral(), Meta.Numerics.Analysis.FunctionMath.FindMaximum(), Meta.Numerics.Analysis.FunctionMath.FindMinimum(), Meta.Numerics.Analysis.FunctionMath.FindZero(), Meta.Numerics.Analysis.FunctionMath.Integrate(), Meta.Numerics.Analysis.MultiFunctionMath.Integrate(), Test.IntervalTest.IntervalEndpoints(), Test.IntervalTest.IntervalFromEndpoints(), Test.IntervalTest.IntervalFromMidpointAndWidth(), Test.IntervalTest.IntervalZeroWidth(), Meta.Numerics.Statistics.Distributions.UniformDistribution.InverseProbability(), Meta.Numerics.Statistics.Distributions.Distribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.UniformDistribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.UniformDistribution.Moment(), Test.DistributionTest.OutsideDistributionSupport(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.ProbabilityDensity(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.RightProbability(), Test.SampleTest.SampleInterquartileRange(), and Test.IntervalTest.ToTest().
Width
double Meta.Numerics.Interval.Width get
Gets the width of the interval.
Referenced by Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.ComputeEffectiveBin(), Meta.Numerics.Statistics.Distributions.UniformDistribution.Cumulant(), Test.DistributionTest.DistributionProbabilityIntegral(), Test.IntervalTest.IntervalFromEndpoints(), Test.IntervalTest.IntervalFromMidpointAndWidth(), Test.IntervalTest.IntervalWidth(), Test.IntervalTest.IntervalZeroWidth(), Meta.Numerics.Statistics.Distributions.UniformDistribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.MomentAboutMean(), Meta.Numerics.Statistics.Distributions.UniformDistribution.MomentAboutMean(), Meta.Numerics.Statistics.Distributions.UniformDistribution.ProbabilityDensity(), and Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.ProbabilityDensity().
Midpoint
double Meta.Numerics.Interval.Midpoint get
Gets the mid-point of the interval.
Referenced by Meta.Numerics.Statistics.Distributions.UniformDistribution.Cumulant(), Test.IntervalTest.IntervalFromMidpointAndWidth(), Test.IntervalTest.IntervalMidpoint(), and Test.IntervalTest.IntervalZeroWidth().
The documentation for this struct was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Core/Interval.cs