Doc: IGLib EXTENDED: AForge.Imaging.Filters.FillHoles Class Reference
AForge.Imaging.Filters.FillHoles Class Reference
Fill holes in objects in binary image.
Public Member Functions
FillHoles ()
Initializes a new instance of the FillHoles class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlaceFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image)
Process the filter on the specified image.
Properties
bool CoupledSizeFiltering [get, set]
Specifies if size filetering should be coupled or not.
int MaxHoleWidth [get, set]
Maximum width of a hole to fill.
int MaxHoleHeight [get, set]
Maximum height of a hole to fill.
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.BaseInPlaceFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
bool coupledSizeFiltering = true
int maxHoleWidth = int.MaxValue
int maxHoleHeight = int.MaxValue
Detailed Description
Fill holes in objects in binary image.
The filter allows to fill black holes in white object in a binary image. It is possible to specify maximum holes' size to fill using MaxHoleWidth and MaxHoleHeight properties.
The filter accepts binary image only, which are represented as 8 bpp images.
Sample usage:
// create and configure the filter
FillHoles filter = new FillHoles();
filter.MaxHoleHeight = 20;
filter.MaxHoleWidth  = 20;
filter.CoupledSizeFiltering = false;
// apply the filter
Bitmap result = filter.Apply(image);
Initial image:
Result image:
Constructor & Destructor Documentation
FillHoles()
AForge.Imaging.Filters.FillHoles.FillHoles () inline
Initializes a new instance of the FillHoles class.
References AForge.Imaging.Filters.FillHoles.formatTranslations.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.FillHoles.ProcessFilter (UnmanagedImage image) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
Implements AForge.Imaging.Filters.BaseInPlaceFilter.
References AForge.Imaging.Filters.BaseInPlacePartialFilter.Apply(), AForge.Imaging.Filters.FillHoles.coupledSizeFiltering, AForge.Imaging.BlobCounterBase.GetObjectsInformation(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.Blob.ID, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.Filters.FillHoles.maxHoleHeight, AForge.Imaging.Filters.FillHoles.maxHoleWidth, AForge.Imaging.BlobCounterBase.ObjectLabels, AForge.Imaging.BlobCounterBase.ProcessImage(), AForge.Imaging.Blob.Rectangle, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
Member Data Documentation
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.FillHoles.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.FillHoles.FillHoles().
coupledSizeFiltering
bool AForge.Imaging.Filters.FillHoles.coupledSizeFiltering = true private
Referenced by AForge.Imaging.Filters.FillHoles.ProcessFilter().
maxHoleWidth
int AForge.Imaging.Filters.FillHoles.maxHoleWidth = int.MaxValue private
Referenced by AForge.Imaging.Filters.FillHoles.ProcessFilter().
maxHoleHeight
int AForge.Imaging.Filters.FillHoles.maxHoleHeight = int.MaxValue private
Referenced by AForge.Imaging.Filters.FillHoles.ProcessFilter().
Property Documentation
CoupledSizeFiltering
bool AForge.Imaging.Filters.FillHoles.CoupledSizeFiltering get set
Specifies if size filetering should be coupled or not.
In uncoupled filtering mode, holes are filled in the case if their width is smaller than or equal to MaxHoleWidth or height is smaller than or equal to MaxHoleHeight. But in coupled filtering mode, holes are filled only in the case if both width and height are smaller or equal to the corresponding value.
Default value is set to true, what means coupled filtering by size.
MaxHoleWidth
int AForge.Imaging.Filters.FillHoles.MaxHoleWidth get set
Maximum width of a hole to fill.
All holes, which have width greater than this value, are kept unfilled. See CoupledSizeFiltering for additional information.
Default value is set to int.MaxValue.
MaxHoleHeight
int AForge.Imaging.Filters.FillHoles.MaxHoleHeight get set
Maximum height of a hole to fill.
All holes, which have height greater than this value, are kept unfilled. See CoupledSizeFiltering for additional information.
Default value is set to int.MaxValue.
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.FillHoles.FormatTranslations get
Format translations dictionary.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Other/FillHoles.cs