Doc: IGLib EXTENDED: NUnit.Engine.Services.Tests.TestFilteringTests Class Reference
NUnit.Engine.Services.Tests.TestFilteringTests Class Reference
Public Member Functions
void LoadAssembly ()
void UsingXml (string filter, int count)
void UsingTestFilterBuilderAddTest (string testName, int count)
void UsingTestFilterBuilderSelectWhere (string expression, int count)
Private Attributes
NUnit3FrameworkDriver _driver
Static Private Attributes
const string MOCK_ASSEMBLY = "mock-nunit-assembly.exe"
Member Function Documentation
LoadAssembly()
void NUnit.Engine.Services.Tests.TestFilteringTests.LoadAssembly () inline
References NUnit.Engine.Services.Tests.TestFilteringTests._driver, NUnit.Framework.TestContext.CurrentContext, NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(), NUnit.Engine.Services.Tests.TestFilteringTests.MOCK_ASSEMBLY, and NUnit.Framework.TestContext.TestDirectory.
UsingXml()
void NUnit.Engine.Services.Tests.TestFilteringTests.UsingXml (string filter, int count) inline
References NUnit.Engine.Services.Tests.TestFilteringTests._driver, NUnit.Engine.Drivers.NUnit3FrameworkDriver.CountTestCases(), NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
UsingTestFilterBuilderAddTest()
void NUnit.Engine.Services.Tests.TestFilteringTests.UsingTestFilterBuilderAddTest (string testName, int count) inline
References NUnit.Engine.Services.Tests.TestFilteringTests._driver, NUnit.Engine.Drivers.NUnit3FrameworkDriver.CountTestCases(), NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
UsingTestFilterBuilderSelectWhere()
void NUnit.Engine.Services.Tests.TestFilteringTests.UsingTestFilterBuilderSelectWhere (string expression, int count) inline
References NUnit.Engine.Services.Tests.TestFilteringTests._driver, NUnit.Engine.Drivers.NUnit3FrameworkDriver.CountTestCases(), NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
Member Data Documentation
MOCK_ASSEMBLY
const string NUnit.Engine.Services.Tests.TestFilteringTests.MOCK_ASSEMBLY = "mock-nunit-assembly.exe" static private
Referenced by NUnit.Engine.Services.Tests.TestFilteringTests.LoadAssembly().
_driver
NUnit3FrameworkDriver NUnit.Engine.Services.Tests.TestFilteringTests._driver private
Referenced by NUnit.Engine.Services.Tests.TestFilteringTests.LoadAssembly(), NUnit.Engine.Services.Tests.TestFilteringTests.UsingTestFilterBuilderAddTest(), NUnit.Engine.Services.Tests.TestFilteringTests.UsingTestFilterBuilderSelectWhere(), and NUnit.Engine.Services.Tests.TestFilteringTests.UsingXml().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Services/TestFilteringTests.cs