Doc: IGLib EXTENDED: QwerkStart.MainForm Class Reference
QwerkStart.MainForm Class Reference
Public Member Functions
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void MainForm_FormClosing (object sender, FormClosingEventArgs e)
void EnableContols (bool enable)
void connectButton_Click (object sender, EventArgs e)
void disconnectButton_Click (object sender, EventArgs e)
bool Connect (string host)
void HandleLostConnection ()
void Disconnect ()
void timer_Tick (object sender, EventArgs e)
void ledButton_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Qwerk qwerk = new Qwerk()
int statIndex = 0
int statReady = 0
int[] statCount = new int[statLength]
bool[] ledStates
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.Button disconnectButton
System.Windows.Forms.Button connectButton
System.Windows.Forms.TextBox qwerkIPBox
System.Windows.Forms.Label label1
System.Windows.Forms.GroupBox groupBox2
AForge.Controls.VideoSourcePlayer videoSourcePlayer
System.Windows.Forms.StatusStrip statusStrip
System.Windows.Forms.ToolStripStatusLabel statusLabel
System.Windows.Forms.ToolStripStatusLabel voltageLabel
System.Windows.Forms.ToolStripStatusLabel fpsLabel
System.Windows.Forms.Timer timer
System.Windows.Forms.GroupBox groupBox3
System.Windows.Forms.Button led9Button
System.Windows.Forms.Button led8Button
System.Windows.Forms.Button led7Button
System.Windows.Forms.Button led6Button
System.Windows.Forms.Button led5Button
System.Windows.Forms.Button led4Button
System.Windows.Forms.Button led3Button
System.Windows.Forms.Button led2Button
System.Windows.Forms.Button led1Button
System.Windows.Forms.Button led0Button
Static Private Attributes
const int statLength = 15
Constructor & Destructor Documentation
MainForm()
QwerkStart.MainForm.MainForm () inline
References QwerkStart.MainForm.EnableContols(), and QwerkStart.MainForm.InitializeComponent().
Member Function Documentation
MainForm_FormClosing()
void QwerkStart.MainForm.MainForm_FormClosing (object sender, FormClosingEventArgs e) inline private
References QwerkStart.MainForm.Disconnect().
Referenced by QwerkStart.MainForm.InitializeComponent().
EnableContols()
void QwerkStart.MainForm.EnableContols (bool enable) inline private
References QwerkStart.MainForm.connectButton, QwerkStart.MainForm.disconnectButton, QwerkStart.MainForm.led0Button, QwerkStart.MainForm.led1Button, QwerkStart.MainForm.led2Button, QwerkStart.MainForm.led3Button, QwerkStart.MainForm.led4Button, QwerkStart.MainForm.led5Button, QwerkStart.MainForm.led6Button, QwerkStart.MainForm.led7Button, QwerkStart.MainForm.led8Button, and QwerkStart.MainForm.led9Button.
Referenced by QwerkStart.MainForm.connectButton_Click(), QwerkStart.MainForm.Disconnect(), and QwerkStart.MainForm.MainForm().
connectButton_Click()
void QwerkStart.MainForm.connectButton_Click (object sender, EventArgs e) inline private
References QwerkStart.MainForm.Connect(), QwerkStart.MainForm.EnableContols(), QwerkStart.MainForm.qwerkIPBox, and QwerkStart.MainForm.statusLabel.
Referenced by QwerkStart.MainForm.InitializeComponent().
disconnectButton_Click()
void QwerkStart.MainForm.disconnectButton_Click (object sender, EventArgs e) inline private
References QwerkStart.MainForm.Disconnect(), QwerkStart.MainForm.fpsLabel, QwerkStart.MainForm.statusLabel, and QwerkStart.MainForm.voltageLabel.
Referenced by QwerkStart.MainForm.InitializeComponent().
Connect()
bool QwerkStart.MainForm.Connect (string host) inline private
References AForge.Robotics.TeRK.Qwerk.Connect(), AForge.Robotics.TeRK.Qwerk.GetLedsService(), AForge.Robotics.TeRK.Qwerk.GetVideoService(), QwerkStart.MainForm.qwerk, QwerkStart.MainForm.qwerkIPBox, QwerkStart.MainForm.statIndex, QwerkStart.MainForm.statReady, QwerkStart.MainForm.timer, and QwerkStart.MainForm.videoSourcePlayer.
Referenced by QwerkStart.MainForm.connectButton_Click().
HandleLostConnection()
void QwerkStart.MainForm.HandleLostConnection () inline private
References QwerkStart.MainForm.Disconnect(), QwerkStart.MainForm.fpsLabel, QwerkStart.MainForm.statusLabel, and QwerkStart.MainForm.voltageLabel.
Referenced by QwerkStart.MainForm.ledButton_Click(), and QwerkStart.MainForm.timer_Tick().
Disconnect()
void QwerkStart.MainForm.Disconnect () inline private
References AForge.Robotics.TeRK.Qwerk.Disconnect(), QwerkStart.MainForm.EnableContols(), AForge.Robotics.TeRK.Qwerk.GetLedsService(), AForge.Robotics.TeRK.Qwerk.GetVideoService(), AForge.Robotics.TeRK.Qwerk.IsConnected, QwerkStart.MainForm.qwerk, and QwerkStart.MainForm.timer.
Referenced by QwerkStart.MainForm.disconnectButton_Click(), QwerkStart.MainForm.HandleLostConnection(), and QwerkStart.MainForm.MainForm_FormClosing().
timer_Tick()
void QwerkStart.MainForm.timer_Tick (object sender, EventArgs e) inline private
References QwerkStart.MainForm.fpsLabel, AForge.Video.IVideoSource.FramesReceived, AForge.Robotics.TeRK.Qwerk.GetPower(), QwerkStart.MainForm.HandleLostConnection(), QwerkStart.MainForm.qwerk, QwerkStart.MainForm.statCount, QwerkStart.MainForm.statIndex, QwerkStart.MainForm.statLength, QwerkStart.MainForm.statReady, QwerkStart.MainForm.videoSourcePlayer, and QwerkStart.MainForm.voltageLabel.
Referenced by QwerkStart.MainForm.InitializeComponent().
ledButton_Click()
void QwerkStart.MainForm.ledButton_Click (object sender, EventArgs e) inline private
References AForge.Robotics.TeRK.Qwerk.GetLedsService(), QwerkStart.MainForm.HandleLostConnection(), QwerkStart.MainForm.ledStates, and QwerkStart.MainForm.qwerk.
Referenced by QwerkStart.MainForm.InitializeComponent().
Dispose()
override void QwerkStart.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References QwerkStart.MainForm.components.
InitializeComponent()
void QwerkStart.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References QwerkStart.MainForm.components, QwerkStart.MainForm.connectButton, QwerkStart.MainForm.connectButton_Click(), QwerkStart.MainForm.disconnectButton, QwerkStart.MainForm.disconnectButton_Click(), QwerkStart.MainForm.fpsLabel, QwerkStart.MainForm.groupBox1, QwerkStart.MainForm.groupBox2, QwerkStart.MainForm.groupBox3, QwerkStart.MainForm.label1, QwerkStart.MainForm.led0Button, QwerkStart.MainForm.led1Button, QwerkStart.MainForm.led2Button, QwerkStart.MainForm.led3Button, QwerkStart.MainForm.led4Button, QwerkStart.MainForm.led5Button, QwerkStart.MainForm.led6Button, QwerkStart.MainForm.led7Button, QwerkStart.MainForm.led8Button, QwerkStart.MainForm.led9Button, QwerkStart.MainForm.ledButton_Click(), QwerkStart.MainForm.MainForm_FormClosing(), QwerkStart.MainForm.qwerkIPBox, QwerkStart.MainForm.statusLabel, QwerkStart.MainForm.statusStrip, QwerkStart.MainForm.timer, QwerkStart.MainForm.timer_Tick(), QwerkStart.MainForm.videoSourcePlayer, and QwerkStart.MainForm.voltageLabel.
Referenced by QwerkStart.MainForm.MainForm().
Member Data Documentation
qwerk
Qwerk QwerkStart.MainForm.qwerk = new Qwerk() private
Referenced by QwerkStart.MainForm.Connect(), QwerkStart.MainForm.Disconnect(), QwerkStart.MainForm.ledButton_Click(), and QwerkStart.MainForm.timer_Tick().
statLength
const int QwerkStart.MainForm.statLength = 15 static private
Referenced by QwerkStart.MainForm.timer_Tick().
statIndex
int QwerkStart.MainForm.statIndex = 0 private
Referenced by QwerkStart.MainForm.Connect(), and QwerkStart.MainForm.timer_Tick().
statReady
int QwerkStart.MainForm.statReady = 0 private
Referenced by QwerkStart.MainForm.Connect(), and QwerkStart.MainForm.timer_Tick().
statCount
int [] QwerkStart.MainForm.statCount = new int[statLength] private
Referenced by QwerkStart.MainForm.timer_Tick().
ledStates
bool [] QwerkStart.MainForm.ledStates private
Initial value:
= new bool[10]
        {
            false, false, false, false, false, false, false, false, false, false
        }
Referenced by QwerkStart.MainForm.ledButton_Click().
components
System.ComponentModel.IContainer QwerkStart.MainForm.components = null private
Required designer variable.
Referenced by QwerkStart.MainForm.Dispose(), and QwerkStart.MainForm.InitializeComponent().
groupBox1
System.Windows.Forms.GroupBox QwerkStart.MainForm.groupBox1 private
Referenced by QwerkStart.MainForm.InitializeComponent().
disconnectButton
System.Windows.Forms.Button QwerkStart.MainForm.disconnectButton private
Referenced by QwerkStart.MainForm.EnableContols(), and QwerkStart.MainForm.InitializeComponent().
connectButton
System.Windows.Forms.Button QwerkStart.MainForm.connectButton private
Referenced by QwerkStart.MainForm.EnableContols(), and QwerkStart.MainForm.InitializeComponent().
qwerkIPBox
System.Windows.Forms.TextBox QwerkStart.MainForm.qwerkIPBox private
Referenced by QwerkStart.MainForm.Connect(), QwerkStart.MainForm.connectButton_Click(), and QwerkStart.MainForm.InitializeComponent().
label1
System.Windows.Forms.Label QwerkStart.MainForm.label1 private
Referenced by QwerkStart.MainForm.InitializeComponent().
groupBox2
System.Windows.Forms.GroupBox QwerkStart.MainForm.groupBox2 private
Referenced by QwerkStart.MainForm.InitializeComponent().
videoSourcePlayer
AForge.Controls.VideoSourcePlayer QwerkStart.MainForm.videoSourcePlayer private
Referenced by QwerkStart.MainForm.Connect(), QwerkStart.MainForm.InitializeComponent(), and QwerkStart.MainForm.timer_Tick().
statusStrip
System.Windows.Forms.StatusStrip QwerkStart.MainForm.statusStrip private
Referenced by QwerkStart.MainForm.InitializeComponent().
statusLabel
System.Windows.Forms.ToolStripStatusLabel QwerkStart.MainForm.statusLabel private
Referenced by QwerkStart.MainForm.connectButton_Click(), QwerkStart.MainForm.disconnectButton_Click(), QwerkStart.MainForm.HandleLostConnection(), and QwerkStart.MainForm.InitializeComponent().
voltageLabel
System.Windows.Forms.ToolStripStatusLabel QwerkStart.MainForm.voltageLabel private
Referenced by QwerkStart.MainForm.disconnectButton_Click(), QwerkStart.MainForm.HandleLostConnection(), QwerkStart.MainForm.InitializeComponent(), and QwerkStart.MainForm.timer_Tick().
fpsLabel
System.Windows.Forms.ToolStripStatusLabel QwerkStart.MainForm.fpsLabel private
Referenced by QwerkStart.MainForm.disconnectButton_Click(), QwerkStart.MainForm.HandleLostConnection(), QwerkStart.MainForm.InitializeComponent(), and QwerkStart.MainForm.timer_Tick().
timer
System.Windows.Forms.Timer QwerkStart.MainForm.timer private
Referenced by QwerkStart.MainForm.Connect(), QwerkStart.MainForm.Disconnect(), and QwerkStart.MainForm.InitializeComponent().
groupBox3
System.Windows.Forms.GroupBox QwerkStart.MainForm.groupBox3 private
Referenced by QwerkStart.MainForm.InitializeComponent().
led9Button
System.Windows.Forms.Button QwerkStart.MainForm.led9Button private
Referenced by QwerkStart.MainForm.EnableContols(), and QwerkStart.MainForm.InitializeComponent().
led8Button
System.Windows.Forms.Button QwerkStart.MainForm.led8Button private
Referenced by QwerkStart.MainForm.EnableContols(), and QwerkStart.MainForm.InitializeComponent().
led7Button
System.Windows.Forms.Button QwerkStart.MainForm.led7Button private
Referenced by QwerkStart.MainForm.EnableContols(), and QwerkStart.MainForm.InitializeComponent().
led6Button
System.Windows.Forms.Button QwerkStart.MainForm.led6Button private
Referenced by QwerkStart.MainForm.EnableContols(), and QwerkStart.MainForm.InitializeComponent().
led5Button
System.Windows.Forms.Button QwerkStart.MainForm.led5Button private
Referenced by QwerkStart.MainForm.EnableContols(), and QwerkStart.MainForm.InitializeComponent().
led4Button
System.Windows.Forms.Button QwerkStart.MainForm.led4Button private
Referenced by QwerkStart.MainForm.EnableContols(), and QwerkStart.MainForm.InitializeComponent().
led3Button
System.Windows.Forms.Button QwerkStart.MainForm.led3Button private
Referenced by QwerkStart.MainForm.EnableContols(), and QwerkStart.MainForm.InitializeComponent().
led2Button
System.Windows.Forms.Button QwerkStart.MainForm.led2Button private
Referenced by QwerkStart.MainForm.EnableContols(), and QwerkStart.MainForm.InitializeComponent().
led1Button
System.Windows.Forms.Button QwerkStart.MainForm.led1Button private
Referenced by QwerkStart.MainForm.EnableContols(), and QwerkStart.MainForm.InitializeComponent().
led0Button
System.Windows.Forms.Button QwerkStart.MainForm.led0Button private
Referenced by QwerkStart.MainForm.EnableContols(), and QwerkStart.MainForm.InitializeComponent().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Robotics/TeRK/QwerkStart/MainForm.cs
shelldev/lib_ann/aforge.net/Samples/Robotics/TeRK/QwerkStart/MainForm.Designer.cs