Doc: IGLib EXTENDED: NUnit.Framework.Constraints.EqualConstraintTests.DictionaryEquality Class Reference
NUnit.Framework.Constraints.EqualConstraintTests.DictionaryEquality Class Reference
Public Member Functions
void CanMatchDictionaries_SameOrder ()
void CanMatchDictionaries_Failure ()
void CanMatchDictionaries_DifferentOrder ()
void CanMatchHashtables_SameOrder ()
void CanMatchHashtables_Failure ()
void CanMatchHashtables_DifferentOrder ()
void CanMatchHashtableWithDictionary ()
Member Function Documentation
CanMatchDictionaries_SameOrder()
void NUnit.Framework.Constraints.EqualConstraintTests.DictionaryEquality.CanMatchDictionaries_SameOrder () inline
References NUnit.Framework.Assert.AreEqual().
CanMatchDictionaries_Failure()
void NUnit.Framework.Constraints.EqualConstraintTests.DictionaryEquality.CanMatchDictionaries_Failure () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.Throws().
CanMatchDictionaries_DifferentOrder()
void NUnit.Framework.Constraints.EqualConstraintTests.DictionaryEquality.CanMatchDictionaries_DifferentOrder () inline
References NUnit.Framework.Assert.AreEqual().
CanMatchHashtables_SameOrder()
void NUnit.Framework.Constraints.EqualConstraintTests.DictionaryEquality.CanMatchHashtables_SameOrder () inline
References NUnit.Framework.Assert.AreEqual().
CanMatchHashtables_Failure()
void NUnit.Framework.Constraints.EqualConstraintTests.DictionaryEquality.CanMatchHashtables_Failure () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.Throws().
CanMatchHashtables_DifferentOrder()
void NUnit.Framework.Constraints.EqualConstraintTests.DictionaryEquality.CanMatchHashtables_DifferentOrder () inline
References NUnit.Framework.Assert.AreEqual().
CanMatchHashtableWithDictionary()
void NUnit.Framework.Constraints.EqualConstraintTests.DictionaryEquality.CanMatchHashtableWithDictionary () inline
References NUnit.Framework.Assert.AreEqual().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/EqualConstraintTests.cs