Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DDISNA Class Reference
DotNumerics.LinearAlgebra.CSLapack.DDISNA Class Reference
– LAPACK routine (version 3.0) – Univ. of Tennessee, Univ. of California Berkeley, NAG Ltd., Courant Institute, Argonne National Lab, and Rice University September 30, 1994
Public Member Functions
DDISNA (LSAME lsame, DLAMCH dlamch, XERBLA xerbla)
DDISNA ()
void Run (string JOB, int M, int N, double[] D, int offset_d, ref double[] SEP, int offset_sep, ref int INFO)
Private Attributes
LSAME _lsame
DLAMCH _dlamch
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E+0
Detailed Description
– LAPACK routine (version 3.0) – Univ. of Tennessee, Univ. of California Berkeley, NAG Ltd., Courant Institute, Argonne National Lab, and Rice University September 30, 1994
Purpose
DDISNA computes the reciprocal condition numbers for the eigenvectors of a real symmetric or complex Hermitian matrix or for the left or right singular vectors of a general m-by-n matrix. The reciprocal condition number is the 'gap' between the corresponding eigenvalue or singular value and the nearest other one.
The bound on the error, measured by angle in radians, in the I-th computed vector is given by
DLAMCH('E') * (ANORM / SEP(I))
where ANORM = 2-norm(A) = max(abs(D(j))). SEP(I) is not allowed to be smaller than DLAMCH('E')*ANORM in order to limit the size of the error bound.
DDISNA may also be used to compute error bounds for eigenvectors of the generalized symmetric definite eigenproblem.
/summary>
Constructor & Destructor Documentation
DDISNA() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DDISNA.DDISNA (LSAME lsame, DLAMCH dlamch, XERBLA xerbla) inline
DDISNA() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DDISNA.DDISNA () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DDISNA.Run (string JOB, int M, int N, double[] D, int offset_d, ref double[] SEP, int offset_sep, ref int INFO) inline
Purpose
DDISNA computes the reciprocal condition numbers for the eigenvectors of a real symmetric or complex Hermitian matrix or for the left or right singular vectors of a general m-by-n matrix. The reciprocal condition number is the 'gap' between the corresponding eigenvalue or singular value and the nearest other one.
The bound on the error, measured by angle in radians, in the I-th computed vector is given by
DLAMCH('E') * (ANORM / SEP(I))
where ANORM = 2-norm(A) = max(abs(D(j))). SEP(I) is not allowed to be smaller than DLAMCH('E')*ANORM in order to limit the size of the error bound.
DDISNA may also be used to compute error bounds for eigenvectors of the generalized symmetric definite eigenproblem.
/summary>
Parameters
JOB (input) CHARACTER*1 Specifies for which problem the reciprocal condition numbers should be computed: = 'E': the eigenvectors of a symmetric/Hermitian matrix; = 'L': the left singular vectors of a general matrix; = 'R': the right singular vectors of a general matrix. /param>
Parameters
M (input) INTEGER The number of rows of the matrix. M .GE. 0. /param>
Parameters
N (input) INTEGER If JOB = 'L' or 'R', the number of columns of the matrix, in which case N .GE. 0. Ignored if JOB = 'E'. /param>
Parameters
D (input) DOUBLE PRECISION array, dimension (M) if JOB = 'E' dimension (min(M,N)) if JOB = 'L' or 'R' The eigenvalues (if JOB = 'E') or singular values (if JOB = 'L' or 'R') of the matrix, in either increasing or decreasing order. If singular values, they must be non-negative. /param>
Parameters
SEP (output) DOUBLE PRECISION array, dimension (M) if JOB = 'E' dimension (min(M,N)) if JOB = 'L' or 'R' The reciprocal condition numbers of the vectors. /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. /param>
References DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), and DotNumerics.LinearAlgebra.CSLapack.DDISNA.ZERO.
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DDISNA._lsame private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DDISNA._dlamch private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DDISNA._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DDISNA.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DDISNA.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/ddisna.cs