Doc: IGLib EXTENDED: CShell.Modules.Shell.ViewModels.ShellViewModel Class Reference
CShell.Modules.Shell.ViewModels.ShellViewModel Class Reference
Public Member Functions
ShellViewModel ()
void ShowTool (ITool model)
void OpenDocument (IDocument model)
void ActivateDocument (IDocument document)
void CloseDocument (IDocument document)
void Opened (string[] args)
void Close ()
IEnumerable< IResult > Closing (CancelEventArgs e)
void SaveLayout (XmlWriter xmlWriter)
void LoadLayout (XmlReader xmlReader)
Protected Member Functions
override void OnViewLoaded (object view)
override void OnDeactivate (bool close)
Properties
string Title [get, set]
ImageSource Icon [get, set]
IMenu MainMenu [get]
IToolBar ToolBar [get]
IStatusBar StatusBar [get]
IObservableCollection< ITool > ToolsObservable [get]
IEnumerable< ITool > Tools [get]
IEnumerable< IDocument > Documents [get]
Properties inherited from CShell.Framework.Services.IShell
string Title [get, set]
ImageSource Icon [get, set]
IMenu MainMenu [get]
IToolBar ToolBar [get]
IStatusBar StatusBar [get]
IScreen ActiveItem [get]
IEnumerable< IDocument > Documents [get]
IEnumerable< ITool > Tools [get]
Private Attributes
IShellView shellView
readonly ILog log = LogManager.GetLog(typeof(IShell))
string _title = "[Default Title]"
ImageSource _icon
IMenu _mainMenu
IToolBar _toolBar
IStatusBar _statusBar
readonly BindableCollection< ITool > _tools
Constructor & Destructor Documentation
ShellViewModel()
CShell.Modules.Shell.ViewModels.ShellViewModel.ShellViewModel () inline
References CShell.Modules.Shell.ViewModels.ShellViewModel._tools.
Member Function Documentation
OnViewLoaded()
override void CShell.Modules.Shell.ViewModels.ShellViewModel.OnViewLoaded (object view) inline protected
References CShell.Modules.Shell.ViewModels.ShellViewModel.StatusBar, CShell.Modules.Shell.ViewModels.ShellViewModel.Title, CShell.Framework.Services.IStatusBar.UpdateMessage(), and CShell.Framework.Services.IStatusBar.UpdateProgress().
ShowTool()
void CShell.Modules.Shell.ViewModels.ShellViewModel.ShowTool (ITool model) inline
Implements CShell.Framework.Services.IShell.
References CShell.Framework.ITool.IsVisible, and CShell.Modules.Shell.ViewModels.ShellViewModel.ToolsObservable.
OpenDocument()
void CShell.Modules.Shell.ViewModels.ShellViewModel.OpenDocument (IDocument model) inline
Implements CShell.Framework.Services.IShell.
ActivateDocument()
void CShell.Modules.Shell.ViewModels.ShellViewModel.ActivateDocument (IDocument document) inline
Implements CShell.Framework.Services.IShell.
CloseDocument()
void CShell.Modules.Shell.ViewModels.ShellViewModel.CloseDocument (IDocument document) inline
Implements CShell.Framework.Services.IShell.
Opened()
void CShell.Modules.Shell.ViewModels.ShellViewModel.Opened (string[] args) inline
Implements CShell.Framework.Services.IShell.
References CShell.Constants.CShellDefaultFilePath.
Close()
void CShell.Modules.Shell.ViewModels.ShellViewModel.Close () inline
Implements CShell.Framework.Services.IShell.
OnDeactivate()
override void CShell.Modules.Shell.ViewModels.ShellViewModel.OnDeactivate (bool close) inline protected
Closing()
IEnumerable<IResult> CShell.Modules.Shell.ViewModels.ShellViewModel.Closing (CancelEventArgs e) inline
References CShell.Shell.Workspace.
SaveLayout()
void CShell.Modules.Shell.ViewModels.ShellViewModel.SaveLayout (XmlWriter xmlWriter) inline
Implements CShell.Framework.Services.IShell.
References CShell.Modules.Shell.Views.IShellView.DockingManager, CShell.Framework.Services.Execute.OnUIThreadEx(), and CShell.Modules.Shell.ViewModels.ShellViewModel.shellView.
LoadLayout()
void CShell.Modules.Shell.ViewModels.ShellViewModel.LoadLayout (XmlReader xmlReader) inline
Implements CShell.Framework.Services.IShell.
References CShell.Modules.Shell.ViewModels.ShellViewModel._tools, CShell.Modules.Shell.Views.IShellView.DockingManager, CShell.Shell.GetDocument(), CShell.Shell.GetSink(), CShell.Shell.GetTool(), CShell.Modules.Shell.ViewModels.ShellViewModel.log, CShell.Framework.Services.Execute.OnUIThreadEx(), and CShell.Modules.Shell.ViewModels.ShellViewModel.shellView.
Member Data Documentation
shellView
IShellView CShell.Modules.Shell.ViewModels.ShellViewModel.shellView private
Referenced by CShell.Modules.Shell.ViewModels.ShellViewModel.LoadLayout(), and CShell.Modules.Shell.ViewModels.ShellViewModel.SaveLayout().
log
readonly ILog CShell.Modules.Shell.ViewModels.ShellViewModel.log = LogManager.GetLog(typeof(IShell)) private
Referenced by CShell.Modules.Shell.ViewModels.ShellViewModel.LoadLayout().
_title
string CShell.Modules.Shell.ViewModels.ShellViewModel._title = "[Default Title]" private
_icon
ImageSource CShell.Modules.Shell.ViewModels.ShellViewModel._icon private
_mainMenu
IMenu CShell.Modules.Shell.ViewModels.ShellViewModel._mainMenu private
_toolBar
IToolBar CShell.Modules.Shell.ViewModels.ShellViewModel._toolBar private
_statusBar
IStatusBar CShell.Modules.Shell.ViewModels.ShellViewModel._statusBar private
_tools
readonly BindableCollection<ITool> CShell.Modules.Shell.ViewModels.ShellViewModel._tools private
Referenced by CShell.Modules.Shell.ViewModels.ShellViewModel.LoadLayout(), and CShell.Modules.Shell.ViewModels.ShellViewModel.ShellViewModel().
Property Documentation
Title
string CShell.Modules.Shell.ViewModels.ShellViewModel.Title get set
Referenced by CShell.Modules.Shell.ViewModels.ShellViewModel.OnViewLoaded().
Icon
ImageSource CShell.Modules.Shell.ViewModels.ShellViewModel.Icon get set
MainMenu
IMenu CShell.Modules.Shell.ViewModels.ShellViewModel.MainMenu get
ToolBar
IToolBar CShell.Modules.Shell.ViewModels.ShellViewModel.ToolBar get
StatusBar
IStatusBar CShell.Modules.Shell.ViewModels.ShellViewModel.StatusBar get
Referenced by CShell.Modules.Shell.ViewModels.ShellViewModel.OnViewLoaded().
ToolsObservable
IObservableCollection<ITool> CShell.Modules.Shell.ViewModels.ShellViewModel.ToolsObservable get
Referenced by CShell.Modules.Shell.ViewModels.ShellViewModel.ShowTool().
Tools
IEnumerable<ITool> CShell.Modules.Shell.ViewModels.ShellViewModel.Tools get
Documents
IEnumerable<IDocument> CShell.Modules.Shell.ViewModels.ShellViewModel.Documents get
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Shell/ViewModels/ShellViewModel.cs