Doc: IGLib EXTENDED: NUnitLite.Tests.CreateTestFilterTests Class Reference
NUnitLite.Tests.CreateTestFilterTests Class Reference
Public Member Functions
void EmptyFilter ()
void OneTestSelected ()
void ThreeTestsSelected ()
void ThreeTestsFromATestListFile ()
void SixTestsFromTwoTestListFiles ()
void TestListFileMissing ()
void WhereClauseSpecified ()
void TwoTestsAndWhereClauseSpecified ()
Private Member Functions
TestFilter GetFilter (params string[] args)
Member Function Documentation
EmptyFilter()
void NUnitLite.Tests.CreateTestFilterTests.EmptyFilter () inline
References NUnitLite.Tests.CreateTestFilterTests.GetFilter(), and NUnit.Framework.Assert.That().
OneTestSelected()
void NUnitLite.Tests.CreateTestFilterTests.OneTestSelected () inline
References NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.CreateTestFilterTests.GetFilter(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
ThreeTestsSelected()
void NUnitLite.Tests.CreateTestFilterTests.ThreeTestsSelected () inline
References NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.CreateTestFilterTests.GetFilter(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
ThreeTestsFromATestListFile()
void NUnitLite.Tests.CreateTestFilterTests.ThreeTestsFromATestListFile () inline
References NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.CreateTestFilterTests.GetFilter(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
SixTestsFromTwoTestListFiles()
void NUnitLite.Tests.CreateTestFilterTests.SixTestsFromTwoTestListFiles () inline
References NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.CreateTestFilterTests.GetFilter(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
TestListFileMissing()
void NUnitLite.Tests.CreateTestFilterTests.TestListFileMissing () inline
References NUnit.Framework.Does.Contain(), NUnitLite.TextRunner.CreateTestFilter(), NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
WhereClauseSpecified()
void NUnitLite.Tests.CreateTestFilterTests.WhereClauseSpecified () inline
References NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.CreateTestFilterTests.GetFilter(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
TwoTestsAndWhereClauseSpecified()
void NUnitLite.Tests.CreateTestFilterTests.TwoTestsAndWhereClauseSpecified () inline
References NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.CreateTestFilterTests.GetFilter(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
GetFilter()
TestFilter NUnitLite.Tests.CreateTestFilterTests.GetFilter (params string[] args) inline private
References NUnitLite.TextRunner.CreateTestFilter().
Referenced by NUnitLite.Tests.CreateTestFilterTests.EmptyFilter(), NUnitLite.Tests.CreateTestFilterTests.OneTestSelected(), NUnitLite.Tests.CreateTestFilterTests.SixTestsFromTwoTestListFiles(), NUnitLite.Tests.CreateTestFilterTests.ThreeTestsFromATestListFile(), NUnitLite.Tests.CreateTestFilterTests.ThreeTestsSelected(), NUnitLite.Tests.CreateTestFilterTests.TwoTestsAndWhereClauseSpecified(), and NUnitLite.Tests.CreateTestFilterTests.WhereClauseSpecified().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/nunitlite.tests/CreateTestFilterTests.cs