Doc: IGLib EXTENDED: AForge.Imaging.MemoryManager Class Reference
AForge.Imaging.MemoryManager Class Reference
Internal memory manager used by image processing routines.
Classes
class CacheBlock
Static Public Member Functions
static IntPtr Alloc (int size)
Allocate unmanaged memory.
static void Free (IntPtr pointer)
Free unmanaged memory.
static int FreeUnusedMemory ()
Force freeing unused memory.
Properties
static int MaximumCacheSize [get, set]
Maximum amount of memory blocks to keep in cache.
static int CurrentCacheSize [get]
Current amount of memory blocks in cache.
static int BusyMemoryBlocks [get]
Amount of busy memory blocks in cache (which were not freed yet by user).
static int FreeMemoryBlocks [get]
Amount of free memory blocks in cache (which are not busy by users).
static int CachedMemory [get]
Amount of cached memory in bytes.
static int MaxSizeToCache [get, set]
Maximum memory block's size in bytes, which could be cached.
static int MinSizeToCache [get, set]
Minimum memory block's size in bytes, which could be cached.
Static Private Attributes
static int maximumCacheSize = 3
static int currentCacheSize = 0
static int busyBlocks = 0
static int cachedMemory = 0
static int maxSizeToCache = 20 * 1024 * 1024
static int minSizeToCache = 10 * 1024
static List< CacheBlock > memoryBlocks = new List<CacheBlock>()
Detailed Description
Internal memory manager used by image processing routines.
The memory manager supports memory allocation/deallocation caching. Caching means that memory blocks may be not freed on request, but kept for later reuse.
Member Function Documentation
Alloc()
static IntPtr AForge.Imaging.MemoryManager.Alloc (int size) inline static
Allocate unmanaged memory.
Parameters
size Memory size to allocate.
Returns
Return's pointer to the allocated memory buffer.
The method allocates requested amount of memory and returns pointer to it. It may avoid allocation in the case some caching scheme is uses and there is already enough allocated memory available.
Exceptions
OutOfMemoryException There is insufficient memory to satisfy the request.
References AForge.Imaging.MemoryManager.busyBlocks, AForge.Imaging.MemoryManager.cachedMemory, AForge.Imaging.MemoryManager.currentCacheSize, AForge.Imaging.MemoryManager.CacheBlock.Free, AForge.Imaging.MemoryManager.maximumCacheSize, AForge.Imaging.MemoryManager.maxSizeToCache, AForge.Imaging.MemoryManager.CacheBlock.MemoryBlock, AForge.Imaging.MemoryManager.memoryBlocks, AForge.Imaging.MemoryManager.minSizeToCache, and AForge.Imaging.MemoryManager.CacheBlock.Size.
Referenced by AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace().
Free()
static void AForge.Imaging.MemoryManager.Free (IntPtr pointer) inline static
Free unmanaged memory.
Parameters
pointer Pointer to memory buffer to free.
This method may skip actual deallocation of memory and keep it for future Alloc requests, if some caching scheme is used.
References AForge.Imaging.MemoryManager.busyBlocks, AForge.Imaging.MemoryManager.currentCacheSize, and AForge.Imaging.MemoryManager.memoryBlocks.
Referenced by AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace(), and AForge.Imaging.MemoryManager.FreeUnusedMemory().
FreeUnusedMemory()
static int AForge.Imaging.MemoryManager.FreeUnusedMemory () inline static
Force freeing unused memory.
Frees and removes from cache memory blocks, which are not used by users.
Returns
Returns number of freed memory blocks.
References AForge.Imaging.MemoryManager.cachedMemory, AForge.Imaging.MemoryManager.currentCacheSize, AForge.Imaging.MemoryManager.Free(), and AForge.Imaging.MemoryManager.memoryBlocks.
Member Data Documentation
maximumCacheSize
int AForge.Imaging.MemoryManager.maximumCacheSize = 3 static private
Referenced by AForge.Imaging.MemoryManager.Alloc().
currentCacheSize
int AForge.Imaging.MemoryManager.currentCacheSize = 0 static private
Referenced by AForge.Imaging.MemoryManager.Alloc(), AForge.Imaging.MemoryManager.Free(), and AForge.Imaging.MemoryManager.FreeUnusedMemory().
busyBlocks
int AForge.Imaging.MemoryManager.busyBlocks = 0 static private
Referenced by AForge.Imaging.MemoryManager.Alloc(), and AForge.Imaging.MemoryManager.Free().
cachedMemory
int AForge.Imaging.MemoryManager.cachedMemory = 0 static private
Referenced by AForge.Imaging.MemoryManager.Alloc(), and AForge.Imaging.MemoryManager.FreeUnusedMemory().
maxSizeToCache
int AForge.Imaging.MemoryManager.maxSizeToCache = 20 * 1024 * 1024 static private
Referenced by AForge.Imaging.MemoryManager.Alloc().
minSizeToCache
int AForge.Imaging.MemoryManager.minSizeToCache = 10 * 1024 static private
Referenced by AForge.Imaging.MemoryManager.Alloc().
memoryBlocks
List<CacheBlock> AForge.Imaging.MemoryManager.memoryBlocks = new List<CacheBlock>() static private
Referenced by AForge.Imaging.MemoryManager.Alloc(), AForge.Imaging.MemoryManager.Free(), and AForge.Imaging.MemoryManager.FreeUnusedMemory().
Property Documentation
MaximumCacheSize
int AForge.Imaging.MemoryManager.MaximumCacheSize static get set
Maximum amount of memory blocks to keep in cache.
The value specifies the amount of memory blocks, which could be cached by the memory manager.
Default value is set to 3. Maximum value is 10.
CurrentCacheSize
int AForge.Imaging.MemoryManager.CurrentCacheSize static get
Current amount of memory blocks in cache.
BusyMemoryBlocks
int AForge.Imaging.MemoryManager.BusyMemoryBlocks static get
Amount of busy memory blocks in cache (which were not freed yet by user).
FreeMemoryBlocks
int AForge.Imaging.MemoryManager.FreeMemoryBlocks static get
Amount of free memory blocks in cache (which are not busy by users).
CachedMemory
int AForge.Imaging.MemoryManager.CachedMemory static get
Amount of cached memory in bytes.
MaxSizeToCache
int AForge.Imaging.MemoryManager.MaxSizeToCache static get set
Maximum memory block's size in bytes, which could be cached.
Memory blocks, which size is greater than this value, are not cached.
MinSizeToCache
int AForge.Imaging.MemoryManager.MinSizeToCache static get set
Minimum memory block's size in bytes, which could be cached.
Memory blocks, which size is less than this value, are not cached.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/MemoryManager.cs