Doc: IGLib EXTENDED: IG.Forms.IndicatorLight Class Reference
IG.Forms.IndicatorLight Class Reference
Public Member Functions
IndicatorLight ()
void SetProperties ()
bool SetOff ()
Sets indicator to off, returns true if successful and false if not (which can be vecause the indictor does not have this state).
bool UnsetOff ()
Unsets the Off state, if set. Switches to a suitable other state available.
bool SetOk ()
Sets indicator to OK, returns true if successful and false if not (which can be vecause the indictor does not have this state).
bool UnsetOk ()
Unsets the OK state, if set. Switches to a suitable other state available.
bool SetBusy ()
Sets indicator to Busy, returns true if successful and false if not (which can be vecause the indictor does not have this state).
bool UnsetBusy ()
Unsets the Busy state, if set. Switches to a suitable other state available.
bool SetError ()
Sets indicator to Error, returns true if successful and false if not (which can be vecause the indictor does not have this state).
bool UnsetError ()
Unsets the Error state, if set. Switches to a suitable other state available.
void Blink (int numTimes=2)
Blninks indicator light in the currently active color for the specified number of times.
void BlinkSpecial (Color blinkColor, int numTimes=2)
Blinks the indicator link in chosen color, for a specified number of times.
void BlinkOk (int numTimes=2)
Blinks the indicator light in the color indicating teh OK state, for the specified numberr of times. This is done independently of the current active color of the indicator light.
void BlinkBusy (int numTimes=2)
Blinks the indicator light in the color indicating teh Busy state, for the specified numberr of times. This is done independently of the current active color of the indicator light.
void BlinkError (int numTimes=2)
Blinks the indicator light in the color indicating teh Error state, for the specified numberr of times. This is done independently of the current active color of the indicator light.
IndicatorLight ()
void SetProperties ()
bool SetOff ()
Sets indicator to off, returns true if successful and false if not (which can be vecause the indictor does not have this state).
bool UnsetOff ()
Unsets the Off state, if set. Switches to a suitable other state available.
bool SetOk ()
Sets indicator to OK, returns true if successful and false if not (which can be vecause the indictor does not have this state).
bool UnsetOk ()
Unsets the OK state, if set. Switches to a suitable other state available.
bool SetBusy ()
Sets indicator to Busy, returns true if successful and false if not (which can be vecause the indictor does not have this state).
bool UnsetBusy ()
Unsets the Busy state, if set. Switches to a suitable other state available.
bool SetError ()
Sets indicator to Error, returns true if successful and false if not (which can be vecause the indictor does not have this state).
bool UnsetError ()
Unsets the Error state, if set. Switches to a suitable other state available.
void Blink (int numTimes=2)
Blninks indicator light in the currently active color for the specified number of times.
void BlinkSpecial (Color blinkColor, int numTimes=2)
Blinks the indicator link in chosen color, for a specified number of times.
void BlinkOk (int numTimes=2)
Blinks the indicator light in the color indicating teh OK state, for the specified numberr of times. This is done independently of the current active color of the indicator light.
void BlinkBusy (int numTimes=2)
Blinks the indicator light in the color indicating teh Busy state, for the specified numberr of times. This is done independently of the current active color of the indicator light.
void BlinkError (int numTimes=2)
Blinks the indicator light in the color indicating teh Error state, for the specified numberr of times. This is done independently of the current active color of the indicator light.
IndicatorLight ()
void SetProperties ()
bool SetOff ()
Sets indicator to off, returns true if successful and false if not (which can be vecause the indictor does not have this state).
bool UnsetOff ()
Unsets the Off state, if set. Switches to a suitable other state available.
bool SetOk ()
Sets indicator to OK, returns true if successful and false if not (which can be vecause the indictor does not have this state).
bool UnsetOk ()
Unsets the OK state, if set. Switches to a suitable other state available.
bool SetBusy ()
Sets indicator to Busy, returns true if successful and false if not (which can be vecause the indictor does not have this state).
bool UnsetBusy ()
Unsets the Busy state, if set. Switches to a suitable other state available.
bool SetError ()
Sets indicator to Error, returns true if successful and false if not (which can be vecause the indictor does not have this state).
bool UnsetError ()
Unsets the Error state, if set. Switches to a suitable other state available.
void Blink (int numTimes=2)
Blninks indicator light in the currently active color for the specified number of times.
void BlinkSpecial (Color blinkColor, int numTimes=2)
Blinks the indicator link in chosen color, for a specified number of times.
void BlinkOk (int numTimes=2)
Blinks the indicator light in the color indicating teh OK state, for the specified numberr of times. This is done independently of the current active color of the indicator light.
void BlinkBusy (int numTimes=2)
Blinks the indicator light in the color indicating teh Busy state, for the specified numberr of times. This is done independently of the current active color of the indicator light.
void BlinkError (int numTimes=2)
Blinks the indicator light in the color indicating teh Error state, for the specified numberr of times. This is done independently of the current active color of the indicator light.
Protected Member Functions
void ClearAll ()
Auxiliary, clears all flags withoud side effects.
bool IsAny ()
Auxiliary, returns a flag indicating whether any mode is active.
void SetFirstAvailable ()
Switch on the first available indicator light if none is currently switched on.
void StartBlinking ()
Starts blinking the indicator light.
void StopBlinking ()
Stops blinking the indicator light.
void OnStateChanged ()
This method is executed when state changes. It fires the StateChanged event.
override void Dispose (bool disposing)
Clean up any resources being used.
void ClearAll ()
Auxiliary, clears all flags withoud side effects.
bool IsAny ()
Auxiliary, returns a flag indicating whether any mode is active.
void SetFirstAvailable ()
Switch on the first available indicator light if none is currently switched on.
void StartBlinking ()
Starts blinking the indicator light.
void StopBlinking ()
Stops blinking the indicator light.
void OnStateChanged ()
This method is executed when state changes. It fires the StateChanged event.
override void Dispose (bool disposing)
Clean up any resources being used.
void ClearAll ()
Auxiliary, clears all flags withoud side effects.
bool IsAny ()
Auxiliary, returns a flag indicating whether any mode is active.
void SetFirstAvailable ()
Switch on the first available indicator light if none is currently switched on.
void StartBlinking ()
Starts blinking the indicator light.
void StopBlinking ()
Stops blinking the indicator light.
void OnStateChanged ()
This method is executed when state changes. It fires the StateChanged event.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
bool _isOff = true
bool _isOk = false
bool _isBusy = false
bool _isError = false
int _numRemainingSpecialBlinks = 0
Color _specialBlinkColor = Color.Yellow
Properties
Color LightColor [get, set]
Color ActiveColor [get]
Gets current active color for the light indicator.
bool IsOff [get, protected set]
Flag indicating whether the indicator is off.
bool IsOk [get, protected set]
Flag indicating whether the indicator state is OK.
bool IsBusy [get, protected set]
Flag indicating whether the indicator state is Busy.
bool IsError [get, protected set]
Flag indicating whether the indicator state is Busy.
int NumRemainingBlinks [get, protected set]
int NumRemainingSpecialBlinks [get, protected set]
Color SpecialBlinkColor [get, protected set]
bool IsBlinkOn [get, set]
Specifies, when the indicator light is blinking, whether the blinking color is currently on or it is off. This flag is toggled by the timer when blinking is on, and the consequence is that the light color changes.
bool IsBlinking [get, set]
Gets or sets the flag indicating whetherr the indicator light is continuously blinking in its active color.
int BlinkIntervalMilliSeconds [get, set]
bool ThrowOnInvalidSwitch [get, set]
Gets or sets a flag indicating whether exception is thrown when an invalid switch is attempted (i.e. one that is not available).
bool HasOff [get, set]
Gets or sets a flag indicating whether the indicator light has an Off state.
bool HasOk [get, set]
Gets or sets a flag indicating whether the indicator light has an OK state.
bool HasBusy [get, set]
Gets or sets a flag indicating whether the indicator light has a Busy state.
bool HasError [get, set]
Gets or sets a flag indicating whether the indicator light has an Error state.
FlowDirection FlowDirection [get, set]
Directional arrangemnt of the contained light (a pannel) and label within the containing outer flow layout panel.
string LabelText [get, set]
Text on the label besid the light (can be null).
Font LabelFont [get, set]
Color ColorLabel [get, set]
Color ColorOff [get, protected set]
Color ColorOk [get, protected set]
Color ColorError [get, protected set]
Color ColorBusy [get, protected set]
bool BorderOut [get, set]
Whether there is a border around control (more precisely, around its outer panel).
bool BorderLabel [get, set]
Whether label has a border.
int MarginOut [get, set]
Margin of teh outer panel.
int PaddingOut [get, set]
Padding of the outer panel.
int MarginLabel [get, set]
Margin of the label.
int PaddingLabel [get, set]
Padding of the label.
static int DefaultBlinkIntervalMilliSeconds [get, set]
static Color DefaultColorLabel [get, protected set]
static Color DefaultColorOff [get, protected set]
static Color DefaultColorOk [get, protected set]
static Color DefaultColorError [get, protected set]
static Color DefaultColorBusy [get, protected set]
static bool DefaultBorderOut [get, set]
static bool DefaultBorderLabel [get, set]
static int DefaultMarginOut [get, set]
static int DefaultPaddingOut [get, set]
static int DefaultMarginLabel [get, set]
static int DefaultPaddingLabel [get, set]
Events
EventHandler StateChanged
Event that is fired whenever the selected file changes.
Private Member Functions
void timer1_Tick (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void timer1_Tick (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void timer1_Tick (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Color _lightColor = DefaultColorOff
int _numRemainingBlinks = 0
bool _blinkOn = false
bool _isBlinking = false
int _blinkIntervalMilliseconds = DefaultBlinkIntervalMilliSeconds
bool _throwOnInvalidSwitch = false
bool _hasOff = true
bool _hasOk = true
bool _hasBusy = true
bool _hasError = true
FlowDirection _direction = FlowDirection.LeftToRight
string _labelText = null
Font _labelFont = null
Color _colorLabel = DefaultColorLabel
Color _colorLightOff = DefaultColorOff
Color _colorLightOk = DefaultColorOk
Color _colorLightBusy = DefaultColorBusy
Color _colorLightError = DefaultColorError
bool _borderOut = DefaultBorderOut
bool _borderLabel = DefaultBorderLabel
int _marginOut = DefaultMarginOut
int _paddingOut = DefaultPaddingOut
int _marginLabel = DefaultMarginLabel
int _paddingLabel = DefaultPaddingLabel
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.FlowLayoutPanel flowOuter
System.Windows.Forms.Panel pnlLight
System.Windows.Forms.Label lblText
System.Windows.Forms.Timer timer1
Static Private Attributes
static int _defaultBlinkIntervalMilliseconds = 500
static Color _defaultColorLabel = Color.Black
static Color _defaultColorLightOff = Color.DarkSlateGray
static Color _defaultColorLightOk = Color.LimeGreen
static Color _defaultColorLightBusy = Color.DarkRed
static Color _defaultColorLightError = Color.Red
static bool _defaultBorderOut = false
static bool _defaultBorderLabel = false
static int _defaultMarginOut = 2
static int _defaultPaddingOut = 2
static int _defaultMarginLabel = 2
static int _defaultPaddingLabel = 2
Constructor & Destructor Documentation
IndicatorLight() [1/3]
IG.Forms.IndicatorLight.IndicatorLight () inline
References IG.Forms.IndicatorLight._isBlinking, IG.Forms.IndicatorLight.ActiveColor, IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.IndicatorLight.ClearAll(), IG.Forms.IndicatorLight.ColorLabel, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLight.InitializeComponent(), IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLight.IsBusy, IG.Forms.IndicatorLight.IsError, IG.Forms.IndicatorLight.IsOff, IG.Forms.IndicatorLight.IsOk, IG.Forms.IndicatorLight.LabelText, IG.Forms.IndicatorLight.lblText, IG.Forms.IndicatorLight.LightColor, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, and IG.Forms.IndicatorLight.timer1.
IndicatorLight() [2/3]
IG.Forms.IndicatorLight.IndicatorLight () inline
References IG.Forms.IndicatorLight._isBlinking, IG.Forms.IndicatorLight.ActiveColor, IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.IndicatorLight.ClearAll(), IG.Forms.IndicatorLight.ColorLabel, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLight.InitializeComponent(), IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLight.IsBusy, IG.Forms.IndicatorLight.IsError, IG.Forms.IndicatorLight.IsOff, IG.Forms.IndicatorLight.IsOk, IG.Forms.IndicatorLight.LabelText, IG.Forms.IndicatorLight.lblText, IG.Forms.IndicatorLight.LightColor, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, and IG.Forms.IndicatorLight.timer1.
IndicatorLight() [3/3]
IG.Forms.IndicatorLight.IndicatorLight () inline
References IG.Forms.IndicatorLight._isBlinking, IG.Forms.IndicatorLight.ActiveColor, IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.IndicatorLight.ClearAll(), IG.Forms.IndicatorLight.ColorLabel, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLight.InitializeComponent(), IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLight.IsBusy, IG.Forms.IndicatorLight.IsError, IG.Forms.IndicatorLight.IsOff, IG.Forms.IndicatorLight.IsOk, IG.Forms.IndicatorLight.LabelText, IG.Forms.IndicatorLight.lblText, IG.Forms.IndicatorLight.LightColor, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, and IG.Forms.IndicatorLight.timer1.
Member Function Documentation
SetProperties() [1/3]
void IG.Forms.IndicatorLight.SetProperties () inline
ClearAll() [1/3]
void IG.Forms.IndicatorLight.ClearAll () inline protected
Auxiliary, clears all flags withoud side effects.
References IG.Forms.IndicatorLight._isBusy, IG.Forms.IndicatorLight._isError, IG.Forms.IndicatorLight._isOff, and IG.Forms.IndicatorLight._isOk.
Referenced by IG.Forms.IndicatorLight.IndicatorLight().
IsAny() [1/3]
bool IG.Forms.IndicatorLight.IsAny () inline protected
Auxiliary, returns a flag indicating whether any mode is active.
References IG.Forms.IndicatorLight._isBusy, IG.Forms.IndicatorLight._isError, IG.Forms.IndicatorLight._isOff, and IG.Forms.IndicatorLight._isOk.
Referenced by IG.Forms.IndicatorLight.SetFirstAvailable(), IG.Forms.IndicatorLight.UnsetBusy(), IG.Forms.IndicatorLight.UnsetError(), IG.Forms.IndicatorLight.UnsetOff(), and IG.Forms.IndicatorLight.UnsetOk().
SetFirstAvailable() [1/3]
void IG.Forms.IndicatorLight.SetFirstAvailable () inline protected
Switch on the first available indicator light if none is currently switched on.
This helps ensure that at least one indicator is on when availability of different types of lights changes (and the indicator that was on becomes unavailable).
References IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLight.IsAny(), IG.Forms.IndicatorLight.IsBusy, IG.Forms.IndicatorLight.IsError, IG.Forms.IndicatorLight.IsOff, and IG.Forms.IndicatorLight.IsOk.
SetOff() [1/3]
bool IG.Forms.IndicatorLight.SetOff () inline
Sets indicator to off, returns true if successful and false if not (which can be vecause the indictor does not have this state).
References IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.IsOff, and IG.Forms.IndicatorLight.ThrowOnInvalidSwitch.
Referenced by IG.Forms.HashControl.backgroundWorker1_RunWorkerCompleted(), IG.Forms.IndicatorLightTestControl.chkOff_CheckedChanged(), IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.HashControl(), IG.Forms.VectorFunctionPlotter1d.PlotParametricTest(), IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), IG.Forms.IndicatorLight.UnsetBusy(), IG.Forms.IndicatorLight.UnsetError(), and IG.Forms.IndicatorLight.UnsetOk().
UnsetOff() [1/3]
bool IG.Forms.IndicatorLight.UnsetOff () inline
Unsets the Off state, if set. Switches to a suitable other state available.
Returns
True if successful and some other state was activated, false if not successful or if this state was not set when called.
References IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLight.IsAny(), IG.Forms.IndicatorLight.IsOff, IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetError(), and IG.Forms.IndicatorLight.SetOk().
Referenced by IG.Forms.IndicatorLightTestControl.chkOff_CheckedChanged().
SetOk() [1/3]
bool IG.Forms.IndicatorLight.SetOk () inline
Sets indicator to OK, returns true if successful and false if not (which can be vecause the indictor does not have this state).
References IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLight.IsOk, and IG.Forms.IndicatorLight.ThrowOnInvalidSwitch.
Referenced by IG.Forms.HashControl.backgroundWorker1_RunWorkerCompleted(), IG.Forms.HashControl.chkMd5_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkOk_CheckedChanged(), IG.Forms.HashControl.chkSha1_CheckedChanged(), IG.Forms.HashControl.chkSha256_CheckedChanged(), IG.Forms.HashControl.chkSha512_CheckedChanged(), IG.Forms.VectorFunctionPlotter1d.PlotParametricTest(), IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), IG.Forms.IndicatorLight.UnsetBusy(), IG.Forms.IndicatorLight.UnsetError(), and IG.Forms.IndicatorLight.UnsetOff().
UnsetOk() [1/3]
bool IG.Forms.IndicatorLight.UnsetOk () inline
Unsets the OK state, if set. Switches to a suitable other state available.
Returns
True if successful and some other state was activated, false if not successful or if this state was not set when called.
References IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.IsAny(), IG.Forms.IndicatorLight.IsOk, IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetError(), and IG.Forms.IndicatorLight.SetOff().
Referenced by IG.Forms.IndicatorLightTestControl.chkOk_CheckedChanged().
SetBusy() [1/3]
bool IG.Forms.IndicatorLight.SetBusy () inline
Sets indicator to Busy, returns true if successful and false if not (which can be vecause the indictor does not have this state).
References IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.IsBusy, and IG.Forms.IndicatorLight.ThrowOnInvalidSwitch.
Referenced by IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.IndicatorLightTestControl.chkBusy_CheckedChanged(), IG.Forms.VectorFunctionPlotter1d.PlotParametricTest(), IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), IG.Forms.IndicatorLight.UnsetError(), IG.Forms.IndicatorLight.UnsetOff(), and IG.Forms.IndicatorLight.UnsetOk().
UnsetBusy() [1/3]
bool IG.Forms.IndicatorLight.UnsetBusy () inline
Unsets the Busy state, if set. Switches to a suitable other state available.
Returns
True if successful and some other state was activated, false if not successful or if this state was not set when called.
References IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLight.IsAny(), IG.Forms.IndicatorLight.IsBusy, IG.Forms.IndicatorLight.SetError(), IG.Forms.IndicatorLight.SetOff(), and IG.Forms.IndicatorLight.SetOk().
Referenced by IG.Forms.IndicatorLightTestControl.chkBusy_CheckedChanged().
SetError() [1/3]
bool IG.Forms.IndicatorLight.SetError () inline
Sets indicator to Error, returns true if successful and false if not (which can be vecause the indictor does not have this state).
References IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.IsError, and IG.Forms.IndicatorLight.ThrowOnInvalidSwitch.
Referenced by IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.CalculateHashes(), IG.Forms.IndicatorLightTestControl.chkError_CheckedChanged(), IG.Forms.VectorFunctionPlotter1d.PlotParametricTest(), IG.Forms.VectorFunctionPlotter2d.PlotParametricTest(), IG.Forms.HashControl.txtFile_Validated(), IG.Forms.IndicatorLight.UnsetBusy(), IG.Forms.IndicatorLight.UnsetOff(), and IG.Forms.IndicatorLight.UnsetOk().
UnsetError() [1/3]
bool IG.Forms.IndicatorLight.UnsetError () inline
Unsets the Error state, if set. Switches to a suitable other state available.
Returns
True if successful and some other state was activated, false if not successful or if this state was not set when called.
References IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLight.IsAny(), IG.Forms.IndicatorLight.IsError, IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetOff(), and IG.Forms.IndicatorLight.SetOk().
Referenced by IG.Forms.IndicatorLightTestControl.chkError_CheckedChanged().
StartBlinking() [1/3]
void IG.Forms.IndicatorLight.StartBlinking () inline protected
Starts blinking the indicator light.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.IsBlinkOn, and IG.Forms.IndicatorLight.timer1.
Referenced by IG.Forms.IndicatorLight.Blink(), and IG.Forms.IndicatorLight.BlinkSpecial().
StopBlinking() [1/3]
void IG.Forms.IndicatorLight.StopBlinking () inline protected
Stops blinking the indicator light.
References IG.Forms.IndicatorLight.IsBlinkOn, IG.Forms.IndicatorLight.NumRemainingBlinks, and IG.Forms.IndicatorLight.timer1.
Blink() [1/3]
void IG.Forms.IndicatorLight.Blink (int numTimes = 2) inline
Blninks indicator light in the currently active color for the specified number of times.
Parameters
numTimes The number of times indicator blinks, default is 2.
References IG.Forms.IndicatorLight.NumRemainingBlinks, and IG.Forms.IndicatorLight.StartBlinking().
Referenced by IG.Forms.IndicatorLightTestControl.btnBlinkOnce_Click(), IG.Forms.IndicatorLightTestControl.btnBlinkTwice_Click(), IG.Forms.VectorFunctionPlotter1d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest().
BlinkSpecial() [1/3]
void IG.Forms.IndicatorLight.BlinkSpecial (Color blinkColor, int numTimes = 2) inline
Blinks the indicator link in chosen color, for a specified number of times.
Parameters
blinkColor Color in which light blinks.
numTimes Number of times the indictor blinks. Default is 2.
References IG.Forms.IndicatorLight.NumRemainingSpecialBlinks, IG.Forms.IndicatorLight.SpecialBlinkColor, and IG.Forms.IndicatorLight.StartBlinking().
Referenced by IG.Forms.HashControl.backgroundWorker1_RunWorkerCompleted(), IG.Forms.IndicatorLight.BlinkBusy(), IG.Forms.IndicatorLight.BlinkError(), IG.Forms.IndicatorLight.BlinkOk(), IG.Forms.IndicatorLightTestControl.btnBlinkYellow3_Click(), IG.Forms.DialogFormDemoControl.CreateNewDialogWindow(), IG.Forms.DialogFormDemoControl.DialogFormDemoControl(), IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter1d.neuralInputParameterSelector1_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector1_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMaxChanged(), IG.Forms.VectorFunctionPlotter2d.neuralInputSelector2_SelectedParameterMinChanged(), IG.Forms.VectorFunctionPlotter1d.neuralOutputValueSelector1_SelectedOutputIdChanged(), IG.Forms.VectorFunctionPlotter2d.neuralOutputValueSelector1_SelectedOutputIdChanged(), IG.Forms.InputOutputDataDefinitionControl.OnDefinitionObjectChanged(), IG.Forms.InpuOrOutputtDataDefinitionControl.OnDefinitionObjectChanged(), IG.Forms.InpuOrOutputtDataDefinitionControl.OnElementDataChanged(), and IG.Forms.InpuOrOutputtDataDefinitionControl.OnNumElementsChanged().
BlinkOk() [1/3]
void IG.Forms.IndicatorLight.BlinkOk (int numTimes = 2) inline
Blinks the indicator light in the color indicating teh OK state, for the specified numberr of times. This is done independently of the current active color of the indicator light.
Parameters
numTimes Number of time the light blinks. Default is 2.
References IG.Forms.IndicatorLight.BlinkSpecial(), and IG.Forms.IndicatorLight.ColorOk.
Referenced by IG.Forms.DialogFormDemoControl.CopyDataToDialogs(), and IG.Forms.DialogFormDemoControl.CreateNewDialogWindow().
BlinkBusy() [1/3]
void IG.Forms.IndicatorLight.BlinkBusy (int numTimes = 2) inline
Blinks the indicator light in the color indicating teh Busy state, for the specified numberr of times. This is done independently of the current active color of the indicator light.
Parameters
numTimes Number of time the light blinks. Default is 2.
References IG.Forms.IndicatorLight.BlinkSpecial(), and IG.Forms.IndicatorLight.ColorBusy.
Referenced by IG.Forms.DialogFormDemoControl.CopyButtonDataToDialogs().
BlinkError() [1/3]
void IG.Forms.IndicatorLight.BlinkError (int numTimes = 2) inline
Blinks the indicator light in the color indicating teh Error state, for the specified numberr of times. This is done independently of the current active color of the indicator light.
Parameters
numTimes Number of time the light blinks. Default is 2.
References IG.Forms.IndicatorLight.BlinkSpecial(), and IG.Forms.IndicatorLight.ColorError.
Referenced by IG.Forms.IndicatorLightTestControl.btnBlinkError2x_Click(), IG.Forms.HashControl.CalculateHashes(), IG.Forms.DialogFormDemoControl.CreateNewDialogWindow(), IG.Forms.VectorFunctionPlotter1d.PlotParametricTest(), and IG.Forms.VectorFunctionPlotter2d.PlotParametricTest().
OnStateChanged() [1/3]
void IG.Forms.IndicatorLight.OnStateChanged () inline protected
This method is executed when state changes. It fires the StateChanged event.
References IG.Forms.IndicatorLight.ActiveColor, IG.Forms.IndicatorLight.LightColor, and IG.Forms.IndicatorLight.StateChanged.
timer1_Tick() [1/3]
void IG.Forms.IndicatorLight.timer1_Tick (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLight.IsBlinkOn, IG.Forms.IndicatorLight.NumRemainingBlinks, IG.Forms.IndicatorLight.NumRemainingSpecialBlinks, and IG.Forms.IndicatorLight.timer1.
Referenced by IG.Forms.IndicatorLight.InitializeComponent().
Dispose() [1/3]
override void IG.Forms.IndicatorLight.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.IndicatorLight.components.
InitializeComponent() [1/3]
void IG.Forms.IndicatorLight.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.IndicatorLight.components, IG.Forms.IndicatorLight.flowOuter, IG.Forms.IndicatorLight.lblText, IG.Forms.IndicatorLight.pnlLight, IG.Forms.IndicatorLight.timer1, and IG.Forms.IndicatorLight.timer1_Tick().
Referenced by IG.Forms.IndicatorLight.IndicatorLight().
SetProperties() [2/3]
void IG.Forms.IndicatorLight.SetProperties () inline
ClearAll() [2/3]
void IG.Forms.IndicatorLight.ClearAll () inline protected
Auxiliary, clears all flags withoud side effects.
References IG.Forms.IndicatorLight._isBusy, IG.Forms.IndicatorLight._isError, IG.Forms.IndicatorLight._isOff, and IG.Forms.IndicatorLight._isOk.
IsAny() [2/3]
bool IG.Forms.IndicatorLight.IsAny () inline protected
Auxiliary, returns a flag indicating whether any mode is active.
References IG.Forms.IndicatorLight._isBusy, IG.Forms.IndicatorLight._isError, IG.Forms.IndicatorLight._isOff, and IG.Forms.IndicatorLight._isOk.
SetFirstAvailable() [2/3]
void IG.Forms.IndicatorLight.SetFirstAvailable () inline protected
Switch on the first available indicator light if none is currently switched on.
This helps ensure that at least one indicator is on when availability of different types of lights changes (and the indicator that was on becomes unavailable).
References IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLight.IsAny(), IG.Forms.IndicatorLight.IsBusy, IG.Forms.IndicatorLight.IsError, IG.Forms.IndicatorLight.IsOff, and IG.Forms.IndicatorLight.IsOk.
SetOff() [2/3]
bool IG.Forms.IndicatorLight.SetOff () inline
Sets indicator to off, returns true if successful and false if not (which can be vecause the indictor does not have this state).
References IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.IsOff, and IG.Forms.IndicatorLight.ThrowOnInvalidSwitch.
UnsetOff() [2/3]
bool IG.Forms.IndicatorLight.UnsetOff () inline
Unsets the Off state, if set. Switches to a suitable other state available.
Returns
True if successful and some other state was activated, false if not successful or if this state was not set when called.
References IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLight.IsAny(), IG.Forms.IndicatorLight.IsOff, IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetError(), and IG.Forms.IndicatorLight.SetOk().
SetOk() [2/3]
bool IG.Forms.IndicatorLight.SetOk () inline
Sets indicator to OK, returns true if successful and false if not (which can be vecause the indictor does not have this state).
References IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLight.IsOk, and IG.Forms.IndicatorLight.ThrowOnInvalidSwitch.
UnsetOk() [2/3]
bool IG.Forms.IndicatorLight.UnsetOk () inline
Unsets the OK state, if set. Switches to a suitable other state available.
Returns
True if successful and some other state was activated, false if not successful or if this state was not set when called.
References IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.IsAny(), IG.Forms.IndicatorLight.IsOk, IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetError(), and IG.Forms.IndicatorLight.SetOff().
SetBusy() [2/3]
bool IG.Forms.IndicatorLight.SetBusy () inline
Sets indicator to Busy, returns true if successful and false if not (which can be vecause the indictor does not have this state).
References IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.IsBusy, and IG.Forms.IndicatorLight.ThrowOnInvalidSwitch.
UnsetBusy() [2/3]
bool IG.Forms.IndicatorLight.UnsetBusy () inline
Unsets the Busy state, if set. Switches to a suitable other state available.
Returns
True if successful and some other state was activated, false if not successful or if this state was not set when called.
References IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLight.IsAny(), IG.Forms.IndicatorLight.IsBusy, IG.Forms.IndicatorLight.SetError(), IG.Forms.IndicatorLight.SetOff(), and IG.Forms.IndicatorLight.SetOk().
SetError() [2/3]
bool IG.Forms.IndicatorLight.SetError () inline
Sets indicator to Error, returns true if successful and false if not (which can be vecause the indictor does not have this state).
References IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.IsError, and IG.Forms.IndicatorLight.ThrowOnInvalidSwitch.
UnsetError() [2/3]
bool IG.Forms.IndicatorLight.UnsetError () inline
Unsets the Error state, if set. Switches to a suitable other state available.
Returns
True if successful and some other state was activated, false if not successful or if this state was not set when called.
References IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLight.IsAny(), IG.Forms.IndicatorLight.IsError, IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetOff(), and IG.Forms.IndicatorLight.SetOk().
StartBlinking() [2/3]
void IG.Forms.IndicatorLight.StartBlinking () inline protected
Starts blinking the indicator light.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.IsBlinkOn, and IG.Forms.IndicatorLight.timer1.
StopBlinking() [2/3]
void IG.Forms.IndicatorLight.StopBlinking () inline protected
Stops blinking the indicator light.
References IG.Forms.IndicatorLight.IsBlinkOn, IG.Forms.IndicatorLight.NumRemainingBlinks, and IG.Forms.IndicatorLight.timer1.
Blink() [2/3]
void IG.Forms.IndicatorLight.Blink (int numTimes = 2) inline
Blninks indicator light in the currently active color for the specified number of times.
Parameters
numTimes The number of times indicator blinks, default is 2.
References IG.Forms.IndicatorLight.NumRemainingBlinks, and IG.Forms.IndicatorLight.StartBlinking().
BlinkSpecial() [2/3]
void IG.Forms.IndicatorLight.BlinkSpecial (Color blinkColor, int numTimes = 2) inline
Blinks the indicator link in chosen color, for a specified number of times.
Parameters
blinkColor Color in which light blinks.
numTimes Number of times the indictor blinks. Default is 2.
References IG.Forms.IndicatorLight.NumRemainingSpecialBlinks, IG.Forms.IndicatorLight.SpecialBlinkColor, and IG.Forms.IndicatorLight.StartBlinking().
BlinkOk() [2/3]
void IG.Forms.IndicatorLight.BlinkOk (int numTimes = 2) inline
Blinks the indicator light in the color indicating teh OK state, for the specified numberr of times. This is done independently of the current active color of the indicator light.
Parameters
numTimes Number of time the light blinks. Default is 2.
References IG.Forms.IndicatorLight.BlinkSpecial(), and IG.Forms.IndicatorLight.ColorOk.
BlinkBusy() [2/3]
void IG.Forms.IndicatorLight.BlinkBusy (int numTimes = 2) inline
Blinks the indicator light in the color indicating teh Busy state, for the specified numberr of times. This is done independently of the current active color of the indicator light.
Parameters
numTimes Number of time the light blinks. Default is 2.
References IG.Forms.IndicatorLight.BlinkSpecial(), and IG.Forms.IndicatorLight.ColorBusy.
BlinkError() [2/3]
void IG.Forms.IndicatorLight.BlinkError (int numTimes = 2) inline
Blinks the indicator light in the color indicating teh Error state, for the specified numberr of times. This is done independently of the current active color of the indicator light.
Parameters
numTimes Number of time the light blinks. Default is 2.
References IG.Forms.IndicatorLight.BlinkSpecial(), and IG.Forms.IndicatorLight.ColorError.
OnStateChanged() [2/3]
void IG.Forms.IndicatorLight.OnStateChanged () inline protected
This method is executed when state changes. It fires the StateChanged event.
References IG.Forms.IndicatorLight.ActiveColor, IG.Forms.IndicatorLight.LightColor, and IG.Forms.IndicatorLight.StateChanged.
timer1_Tick() [2/3]
void IG.Forms.IndicatorLight.timer1_Tick (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLight.IsBlinkOn, IG.Forms.IndicatorLight.NumRemainingBlinks, IG.Forms.IndicatorLight.NumRemainingSpecialBlinks, and IG.Forms.IndicatorLight.timer1.
Dispose() [2/3]
override void IG.Forms.IndicatorLight.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.IndicatorLight.components.
InitializeComponent() [2/3]
void IG.Forms.IndicatorLight.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.IndicatorLight.components, IG.Forms.IndicatorLight.flowOuter, IG.Forms.IndicatorLight.lblText, IG.Forms.IndicatorLight.pnlLight, IG.Forms.IndicatorLight.timer1, and IG.Forms.IndicatorLight.timer1_Tick().
SetProperties() [3/3]
void IG.Forms.IndicatorLight.SetProperties () inline
ClearAll() [3/3]
void IG.Forms.IndicatorLight.ClearAll () inline protected
Auxiliary, clears all flags withoud side effects.
References IG.Forms.IndicatorLight._isBusy, IG.Forms.IndicatorLight._isError, IG.Forms.IndicatorLight._isOff, and IG.Forms.IndicatorLight._isOk.
IsAny() [3/3]
bool IG.Forms.IndicatorLight.IsAny () inline protected
Auxiliary, returns a flag indicating whether any mode is active.
References IG.Forms.IndicatorLight._isBusy, IG.Forms.IndicatorLight._isError, IG.Forms.IndicatorLight._isOff, and IG.Forms.IndicatorLight._isOk.
SetFirstAvailable() [3/3]
void IG.Forms.IndicatorLight.SetFirstAvailable () inline protected
Switch on the first available indicator light if none is currently switched on.
This helps ensure that at least one indicator is on when availability of different types of lights changes (and the indicator that was on becomes unavailable).
References IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLight.IsAny(), IG.Forms.IndicatorLight.IsBusy, IG.Forms.IndicatorLight.IsError, IG.Forms.IndicatorLight.IsOff, and IG.Forms.IndicatorLight.IsOk.
SetOff() [3/3]
bool IG.Forms.IndicatorLight.SetOff () inline
Sets indicator to off, returns true if successful and false if not (which can be vecause the indictor does not have this state).
References IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.IsOff, and IG.Forms.IndicatorLight.ThrowOnInvalidSwitch.
UnsetOff() [3/3]
bool IG.Forms.IndicatorLight.UnsetOff () inline
Unsets the Off state, if set. Switches to a suitable other state available.
Returns
True if successful and some other state was activated, false if not successful or if this state was not set when called.
References IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLight.IsAny(), IG.Forms.IndicatorLight.IsOff, IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetError(), and IG.Forms.IndicatorLight.SetOk().
SetOk() [3/3]
bool IG.Forms.IndicatorLight.SetOk () inline
Sets indicator to OK, returns true if successful and false if not (which can be vecause the indictor does not have this state).
References IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLight.IsOk, and IG.Forms.IndicatorLight.ThrowOnInvalidSwitch.
UnsetOk() [3/3]
bool IG.Forms.IndicatorLight.UnsetOk () inline
Unsets the OK state, if set. Switches to a suitable other state available.
Returns
True if successful and some other state was activated, false if not successful or if this state was not set when called.
References IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.IsAny(), IG.Forms.IndicatorLight.IsOk, IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetError(), and IG.Forms.IndicatorLight.SetOff().
SetBusy() [3/3]
bool IG.Forms.IndicatorLight.SetBusy () inline
Sets indicator to Busy, returns true if successful and false if not (which can be vecause the indictor does not have this state).
References IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.IsBusy, and IG.Forms.IndicatorLight.ThrowOnInvalidSwitch.
UnsetBusy() [3/3]
bool IG.Forms.IndicatorLight.UnsetBusy () inline
Unsets the Busy state, if set. Switches to a suitable other state available.
Returns
True if successful and some other state was activated, false if not successful or if this state was not set when called.
References IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLight.IsAny(), IG.Forms.IndicatorLight.IsBusy, IG.Forms.IndicatorLight.SetError(), IG.Forms.IndicatorLight.SetOff(), and IG.Forms.IndicatorLight.SetOk().
SetError() [3/3]
bool IG.Forms.IndicatorLight.SetError () inline
Sets indicator to Error, returns true if successful and false if not (which can be vecause the indictor does not have this state).
References IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.IsError, and IG.Forms.IndicatorLight.ThrowOnInvalidSwitch.
UnsetError() [3/3]
bool IG.Forms.IndicatorLight.UnsetError () inline
Unsets the Error state, if set. Switches to a suitable other state available.
Returns
True if successful and some other state was activated, false if not successful or if this state was not set when called.
References IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLight.IsAny(), IG.Forms.IndicatorLight.IsError, IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetOff(), and IG.Forms.IndicatorLight.SetOk().
StartBlinking() [3/3]
void IG.Forms.IndicatorLight.StartBlinking () inline protected
Starts blinking the indicator light.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.IsBlinkOn, and IG.Forms.IndicatorLight.timer1.
StopBlinking() [3/3]
void IG.Forms.IndicatorLight.StopBlinking () inline protected
Stops blinking the indicator light.
References IG.Forms.IndicatorLight.IsBlinkOn, IG.Forms.IndicatorLight.NumRemainingBlinks, and IG.Forms.IndicatorLight.timer1.
Blink() [3/3]
void IG.Forms.IndicatorLight.Blink (int numTimes = 2) inline
Blninks indicator light in the currently active color for the specified number of times.
Parameters
numTimes The number of times indicator blinks, default is 2.
References IG.Forms.IndicatorLight.NumRemainingBlinks, and IG.Forms.IndicatorLight.StartBlinking().
BlinkSpecial() [3/3]
void IG.Forms.IndicatorLight.BlinkSpecial (Color blinkColor, int numTimes = 2) inline
Blinks the indicator link in chosen color, for a specified number of times.
Parameters
blinkColor Color in which light blinks.
numTimes Number of times the indictor blinks. Default is 2.
References IG.Forms.IndicatorLight.NumRemainingSpecialBlinks, IG.Forms.IndicatorLight.SpecialBlinkColor, and IG.Forms.IndicatorLight.StartBlinking().
BlinkOk() [3/3]
void IG.Forms.IndicatorLight.BlinkOk (int numTimes = 2) inline
Blinks the indicator light in the color indicating teh OK state, for the specified numberr of times. This is done independently of the current active color of the indicator light.
Parameters
numTimes Number of time the light blinks. Default is 2.
References IG.Forms.IndicatorLight.BlinkSpecial(), and IG.Forms.IndicatorLight.ColorOk.
BlinkBusy() [3/3]
void IG.Forms.IndicatorLight.BlinkBusy (int numTimes = 2) inline
Blinks the indicator light in the color indicating teh Busy state, for the specified numberr of times. This is done independently of the current active color of the indicator light.
Parameters
numTimes Number of time the light blinks. Default is 2.
References IG.Forms.IndicatorLight.BlinkSpecial(), and IG.Forms.IndicatorLight.ColorBusy.
BlinkError() [3/3]
void IG.Forms.IndicatorLight.BlinkError (int numTimes = 2) inline
Blinks the indicator light in the color indicating teh Error state, for the specified numberr of times. This is done independently of the current active color of the indicator light.
Parameters
numTimes Number of time the light blinks. Default is 2.
References IG.Forms.IndicatorLight.BlinkSpecial(), and IG.Forms.IndicatorLight.ColorError.
OnStateChanged() [3/3]
void IG.Forms.IndicatorLight.OnStateChanged () inline protected
This method is executed when state changes. It fires the StateChanged event.
References IG.Forms.IndicatorLight.ActiveColor, IG.Forms.IndicatorLight.LightColor, and IG.Forms.IndicatorLight.StateChanged.
timer1_Tick() [3/3]
void IG.Forms.IndicatorLight.timer1_Tick (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLight.IsBlinkOn, IG.Forms.IndicatorLight.NumRemainingBlinks, IG.Forms.IndicatorLight.NumRemainingSpecialBlinks, and IG.Forms.IndicatorLight.timer1.
Dispose() [3/3]
override void IG.Forms.IndicatorLight.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.IndicatorLight.components.
InitializeComponent() [3/3]
void IG.Forms.IndicatorLight.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.IndicatorLight.components, IG.Forms.IndicatorLight.flowOuter, IG.Forms.IndicatorLight.lblText, IG.Forms.IndicatorLight.pnlLight, IG.Forms.IndicatorLight.timer1, and IG.Forms.IndicatorLight.timer1_Tick().
Member Data Documentation
_lightColor
Color IG.Forms.IndicatorLight._lightColor = DefaultColorOff private
_isOff
bool IG.Forms.IndicatorLight._isOff = true protected
Referenced by IG.Forms.IndicatorLight.ClearAll(), and IG.Forms.IndicatorLight.IsAny().
_isOk
bool IG.Forms.IndicatorLight._isOk = false protected
Referenced by IG.Forms.IndicatorLight.ClearAll(), and IG.Forms.IndicatorLight.IsAny().
_isBusy
bool IG.Forms.IndicatorLight._isBusy = false protected
Referenced by IG.Forms.IndicatorLight.ClearAll(), and IG.Forms.IndicatorLight.IsAny().
_isError
bool IG.Forms.IndicatorLight._isError = false protected
Referenced by IG.Forms.IndicatorLight.ClearAll(), and IG.Forms.IndicatorLight.IsAny().
_numRemainingBlinks
int IG.Forms.IndicatorLight._numRemainingBlinks = 0 private
_numRemainingSpecialBlinks
int IG.Forms.IndicatorLight._numRemainingSpecialBlinks = 0 protected
_specialBlinkColor
Color IG.Forms.IndicatorLight._specialBlinkColor = Color.Yellow protected
_blinkOn
bool IG.Forms.IndicatorLight._blinkOn = false private
_isBlinking
bool IG.Forms.IndicatorLight._isBlinking = false private
Referenced by IG.Forms.IndicatorLight.IndicatorLight().
_blinkIntervalMilliseconds
int IG.Forms.IndicatorLight._blinkIntervalMilliseconds = DefaultBlinkIntervalMilliSeconds private
_throwOnInvalidSwitch
bool IG.Forms.IndicatorLight._throwOnInvalidSwitch = false private
_hasOff
bool IG.Forms.IndicatorLight._hasOff = true private
_hasOk
bool IG.Forms.IndicatorLight._hasOk = true private
_hasBusy
bool IG.Forms.IndicatorLight._hasBusy = true private
_hasError
bool IG.Forms.IndicatorLight._hasError = true private
_direction
FlowDirection IG.Forms.IndicatorLight._direction = FlowDirection.LeftToRight private
_labelText
string IG.Forms.IndicatorLight._labelText = null private
_labelFont
Font IG.Forms.IndicatorLight._labelFont = null private
_colorLabel
Color IG.Forms.IndicatorLight._colorLabel = DefaultColorLabel private
_colorLightOff
Color IG.Forms.IndicatorLight._colorLightOff = DefaultColorOff private
_colorLightOk
Color IG.Forms.IndicatorLight._colorLightOk = DefaultColorOk private
_colorLightBusy
Color IG.Forms.IndicatorLight._colorLightBusy = DefaultColorBusy private
_colorLightError
Color IG.Forms.IndicatorLight._colorLightError = DefaultColorError private
_borderOut
bool IG.Forms.IndicatorLight._borderOut = DefaultBorderOut private
_borderLabel
bool IG.Forms.IndicatorLight._borderLabel = DefaultBorderLabel private
_marginOut
int IG.Forms.IndicatorLight._marginOut = DefaultMarginOut private
_paddingOut
int IG.Forms.IndicatorLight._paddingOut = DefaultPaddingOut private
_marginLabel
int IG.Forms.IndicatorLight._marginLabel = DefaultMarginLabel private
_paddingLabel
int IG.Forms.IndicatorLight._paddingLabel = DefaultPaddingLabel private
_defaultBlinkIntervalMilliseconds
static int IG.Forms.IndicatorLight._defaultBlinkIntervalMilliseconds = 500 static private
_defaultColorLabel
static Color IG.Forms.IndicatorLight._defaultColorLabel = Color.Black static private
_defaultColorLightOff
static Color IG.Forms.IndicatorLight._defaultColorLightOff = Color.DarkSlateGray static private
_defaultColorLightOk
static Color IG.Forms.IndicatorLight._defaultColorLightOk = Color.LimeGreen static private
_defaultColorLightBusy
static Color IG.Forms.IndicatorLight._defaultColorLightBusy = Color.DarkRed static private
_defaultColorLightError
static Color IG.Forms.IndicatorLight._defaultColorLightError = Color.Red static private
_defaultBorderOut
static bool IG.Forms.IndicatorLight._defaultBorderOut = false static private
_defaultBorderLabel
static bool IG.Forms.IndicatorLight._defaultBorderLabel = false static private
_defaultMarginOut
static int IG.Forms.IndicatorLight._defaultMarginOut = 2 static private
_defaultPaddingOut
static int IG.Forms.IndicatorLight._defaultPaddingOut = 2 static private
_defaultMarginLabel
static int IG.Forms.IndicatorLight._defaultMarginLabel = 2 static private
_defaultPaddingLabel
static int IG.Forms.IndicatorLight._defaultPaddingLabel = 2 static private
components
System ComponentModel IContainer IG.Forms.IndicatorLight.components = null private
Required designer variable.
Referenced by IG.Forms.IndicatorLight.Dispose(), and IG.Forms.IndicatorLight.InitializeComponent().
flowOuter
System Windows Forms FlowLayoutPanel IG.Forms.IndicatorLight.flowOuter private
Referenced by IG.Forms.IndicatorLight.InitializeComponent().
pnlLight
System Windows Forms Panel IG.Forms.IndicatorLight.pnlLight private
Referenced by IG.Forms.IndicatorLight.InitializeComponent().
lblText
System Windows Forms Label IG.Forms.IndicatorLight.lblText private
Referenced by IG.Forms.IndicatorLight.IndicatorLight(), and IG.Forms.IndicatorLight.InitializeComponent().
timer1
System Windows Forms Timer IG.Forms.IndicatorLight.timer1 private
Referenced by IG.Forms.IndicatorLight.IndicatorLight(), IG.Forms.IndicatorLight.InitializeComponent(), IG.Forms.IndicatorLight.StartBlinking(), IG.Forms.IndicatorLight.StopBlinking(), and IG.Forms.IndicatorLight.timer1_Tick().
Property Documentation
LightColor
Color IG.Forms.IndicatorLight.LightColor get set protected
Referenced by IG.Forms.IndicatorLight.IndicatorLight(), and IG.Forms.IndicatorLight.OnStateChanged().
ActiveColor
Color IG.Forms.IndicatorLight.ActiveColor get protected
Gets current active color for the light indicator.
Referenced by IG.Forms.IndicatorLight.IndicatorLight(), and IG.Forms.IndicatorLight.OnStateChanged().
IsOff
bool IG.Forms.IndicatorLight.IsOff get protected set
Flag indicating whether the indicator is off.
Referenced by IG.Forms.IndicatorLightTestControl.CopyState(), IG.Forms.IndicatorLight.IndicatorLight(), IG.Forms.IndicatorLight.SetFirstAvailable(), IG.Forms.IndicatorLight.SetOff(), and IG.Forms.IndicatorLight.UnsetOff().
IsOk
bool IG.Forms.IndicatorLight.IsOk get protected set
Flag indicating whether the indicator state is OK.
Referenced by IG.Forms.IndicatorLightTestControl.CopyState(), IG.Forms.IndicatorLight.IndicatorLight(), IG.Forms.IndicatorLight.SetFirstAvailable(), IG.Forms.IndicatorLight.SetOk(), and IG.Forms.IndicatorLight.UnsetOk().
IsBusy
bool IG.Forms.IndicatorLight.IsBusy get protected set
Flag indicating whether the indicator state is Busy.
Referenced by IG.Forms.IndicatorLightTestControl.CopyState(), IG.Forms.IndicatorLight.IndicatorLight(), IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetFirstAvailable(), and IG.Forms.IndicatorLight.UnsetBusy().
IsError
bool IG.Forms.IndicatorLight.IsError get protected set
Flag indicating whether the indicator state is Busy.
Referenced by IG.Forms.IndicatorLightTestControl.CopyState(), IG.Forms.IndicatorLight.IndicatorLight(), IG.Forms.IndicatorLight.SetError(), IG.Forms.IndicatorLight.SetFirstAvailable(), and IG.Forms.IndicatorLight.UnsetError().
NumRemainingBlinks
int IG.Forms.IndicatorLight.NumRemainingBlinks get protected set
Referenced by IG.Forms.IndicatorLight.Blink(), IG.Forms.IndicatorLight.StopBlinking(), and IG.Forms.IndicatorLight.timer1_Tick().
NumRemainingSpecialBlinks
int IG.Forms.IndicatorLight.NumRemainingSpecialBlinks get protected set
Referenced by IG.Forms.IndicatorLight.BlinkSpecial(), and IG.Forms.IndicatorLight.timer1_Tick().
SpecialBlinkColor
Color IG.Forms.IndicatorLight.SpecialBlinkColor get protected set
Referenced by IG.Forms.IndicatorLight.BlinkSpecial().
IsBlinkOn
bool IG.Forms.IndicatorLight.IsBlinkOn get set protected
Specifies, when the indicator light is blinking, whether the blinking color is currently on or it is off. This flag is toggled by the timer when blinking is on, and the consequence is that the light color changes.
Referenced by IG.Forms.IndicatorLight.StartBlinking(), IG.Forms.IndicatorLight.StopBlinking(), and IG.Forms.IndicatorLight.timer1_Tick().
IsBlinking
bool IG.Forms.IndicatorLight.IsBlinking get set
Gets or sets the flag indicating whetherr the indicator light is continuously blinking in its active color.
Referenced by IG.Forms.IndicatorLightTestControl.chkBlinking_CheckedChanged(), IG.Forms.IndicatorLightTestControl.CopyState(), IG.Forms.IndicatorLight.IndicatorLight(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), and IG.Forms.IndicatorLight.timer1_Tick().
BlinkIntervalMilliSeconds
int IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds get set
Referenced by IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.HashControl.HashControl(), IG.Forms.IndicatorLight.IndicatorLight(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.IndicatorLightTestControl.numBlinkTime_ValueChanged(), IG.Forms.IndicatorLight.StartBlinking(), and IG.Forms.IndicatorLight.timer1_Tick().
ThrowOnInvalidSwitch
bool IG.Forms.IndicatorLight.ThrowOnInvalidSwitch get set
Gets or sets a flag indicating whether exception is thrown when an invalid switch is attempted (i.e. one that is not available).
Referenced by IG.Forms.IndicatorLightTestControl.chkThrowOnInvalid_CheckedChanged(), IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetError(), IG.Forms.IndicatorLight.SetOff(), and IG.Forms.IndicatorLight.SetOk().
HasOff
bool IG.Forms.IndicatorLight.HasOff get set
Gets or sets a flag indicating whether the indicator light has an Off state.
Referenced by IG.Forms.IndicatorLightTestControl.chkHasOff_CheckedChanged(), IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLight.IndicatorLight(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.IndicatorLight.SetFirstAvailable(), IG.Forms.IndicatorLight.SetOff(), IG.Forms.IndicatorLight.UnsetBusy(), IG.Forms.IndicatorLight.UnsetError(), and IG.Forms.IndicatorLight.UnsetOk().
HasOk
bool IG.Forms.IndicatorLight.HasOk get set
Gets or sets a flag indicating whether the indicator light has an OK state.
Referenced by IG.Forms.IndicatorLightTestControl.chkHasOk_CheckedChanged(), IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLight.IndicatorLight(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.IndicatorLight.SetFirstAvailable(), IG.Forms.IndicatorLight.SetOk(), IG.Forms.IndicatorLight.UnsetBusy(), IG.Forms.IndicatorLight.UnsetError(), and IG.Forms.IndicatorLight.UnsetOff().
HasBusy
bool IG.Forms.IndicatorLight.HasBusy get set
Gets or sets a flag indicating whether the indicator light has a Busy state.
Referenced by IG.Forms.IndicatorLightTestControl.chkHasBusy_CheckedChanged(), IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLight.IndicatorLight(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetFirstAvailable(), IG.Forms.IndicatorLight.UnsetError(), IG.Forms.IndicatorLight.UnsetOff(), and IG.Forms.IndicatorLight.UnsetOk().
HasError
bool IG.Forms.IndicatorLight.HasError get set
Gets or sets a flag indicating whether the indicator light has an Error state.
Referenced by IG.Forms.IndicatorLightTestControl.chkHasError_CheckedChanged(), IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLight.IndicatorLight(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.IndicatorLight.SetError(), IG.Forms.IndicatorLight.SetFirstAvailable(), IG.Forms.IndicatorLight.UnsetBusy(), IG.Forms.IndicatorLight.UnsetOff(), and IG.Forms.IndicatorLight.UnsetOk().
FlowDirection
FlowDirection IG.Forms.IndicatorLight.FlowDirection get set
Directional arrangemnt of the contained light (a pannel) and label within the containing outer flow layout panel.
Referenced by IG.Forms.IndicatorLightTestControl.comboDirection_SelectedIndexChanged(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), and IG.Forms.IndicatorLightTestControl.InitializeComponent().
LabelText
string IG.Forms.IndicatorLight.LabelText get set
Text on the label besid the light (can be null).
Referenced by IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLight.IndicatorLight(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.IndicatorLightTestControl.txtLabelText_TextChanged(), and IG.Forms.IndicatorLightTestControl.txtLabelText_Validated().
LabelFont
Font IG.Forms.IndicatorLight.LabelFont get set
Referenced by IG.Forms.IndicatorLightTestControl.fontSelectorSimple1_FontSelected(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), and IG.Forms.IndicatorLightTestControl.InitializeComponent().
ColorLabel
Color IG.Forms.IndicatorLight.ColorLabel get set
Referenced by IG.Forms.IndicatorLightTestControl.btnLabelColor_Click(), IG.Forms.IndicatorLight.IndicatorLight(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.HashControl.InitializeComponent(), and IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
ColorOff
Color IG.Forms.IndicatorLight.ColorOff get protected set
ColorOk
Color IG.Forms.IndicatorLight.ColorOk get protected set
Referenced by IG.Forms.IndicatorLight.BlinkOk().
ColorError
Color IG.Forms.IndicatorLight.ColorError get protected set
Referenced by IG.Forms.IndicatorLight.BlinkError().
ColorBusy
Color IG.Forms.IndicatorLight.ColorBusy get protected set
Referenced by IG.Forms.IndicatorLight.BlinkBusy().
BorderOut
bool IG.Forms.IndicatorLight.BorderOut get set
Whether there is a border around control (more precisely, around its outer panel).
Referenced by IG.Forms.IndicatorLightTestControl.chkOuterBorder_CheckedChanged(), IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLight.IndicatorLight(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), and IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
BorderLabel
bool IG.Forms.IndicatorLight.BorderLabel get set
Whether label has a border.
Referenced by IG.Forms.IndicatorLightTestControl.chkLabelBorder_CheckedChanged(), IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLight.IndicatorLight(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), and IG.Forms.VectorFunctionPlotter2d.InitializeComponent().
MarginOut
int IG.Forms.IndicatorLight.MarginOut get set
Margin of teh outer panel.
Referenced by IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLight.IndicatorLight(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.HashControl.InitializeComponent(), and IG.Forms.IndicatorLightTestControl.numOuterMargin_ValueChanged().
PaddingOut
int IG.Forms.IndicatorLight.PaddingOut get set
Padding of the outer panel.
Referenced by IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLight.IndicatorLight(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.HashControl.InitializeComponent(), and IG.Forms.IndicatorLightTestControl.numOuterPadding_ValueChanged().
MarginLabel
int IG.Forms.IndicatorLight.MarginLabel get set
Margin of the label.
Referenced by IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLight.IndicatorLight(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.HashControl.InitializeComponent(), and IG.Forms.IndicatorLightTestControl.numLabelMargin_ValueChanged().
PaddingLabel
int IG.Forms.IndicatorLight.PaddingLabel get set
Padding of the label.
Referenced by IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLight.IndicatorLight(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.DialogFormDemoControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter2d.InitializeComponent(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), IG.Forms.VectorFunctionPlotter1d.InitializeComponent(), IG.Forms.HashControl.InitializeComponent(), and IG.Forms.IndicatorLightTestControl.numLabelPadding_ValueChanged().
DefaultBlinkIntervalMilliSeconds
static int IG.Forms.IndicatorLight.DefaultBlinkIntervalMilliSeconds static get set
DefaultColorLabel
static Color IG.Forms.IndicatorLight.DefaultColorLabel static get protected set
DefaultColorOff
static Color IG.Forms.IndicatorLight.DefaultColorOff static get protected set
DefaultColorOk
static Color IG.Forms.IndicatorLight.DefaultColorOk static get protected set
DefaultColorError
static Color IG.Forms.IndicatorLight.DefaultColorError static get protected set
DefaultColorBusy
static Color IG.Forms.IndicatorLight.DefaultColorBusy static get protected set
DefaultBorderOut
static bool IG.Forms.IndicatorLight.DefaultBorderOut static get set
DefaultBorderLabel
static bool IG.Forms.IndicatorLight.DefaultBorderLabel static get set
DefaultMarginOut
static int IG.Forms.IndicatorLight.DefaultMarginOut static get set
DefaultPaddingOut
static int IG.Forms.IndicatorLight.DefaultPaddingOut static get set
DefaultMarginLabel
static int IG.Forms.IndicatorLight.DefaultMarginLabel static get set
DefaultPaddingLabel
static int IG.Forms.IndicatorLight.DefaultPaddingLabel static get set
Event Documentation
StateChanged
EventHandler IG.Forms.IndicatorLight.StateChanged
Event that is fired whenever the selected file changes.
Referenced by IG.Forms.IndicatorLight.OnStateChanged().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/BasicControls/IndicatorLight.cs
iglib/igforms/Utilities/BasicControls/IndicatorLight.Designer.cs