Doc: IGLib EXTENDED: alglib.teststudentttestsunit Class Reference
alglib.teststudentttestsunit Class Reference
Static Public Member Functions
static bool teststudentttests (bool silent)
static bool _pexec_teststudentttests (bool silent)
Member Function Documentation
teststudentttests()
static bool alglib.teststudentttestsunit.teststudentttests (bool silent) inline static
References alglib.studentttests.studentttest1(), alglib.studentttests.studentttest2(), and alglib.studentttests.unequalvariancettest().
Referenced by alglib.teststudentttestsunit._pexec_teststudentttests(), and _Test.Main().
_pexec_teststudentttests()
static bool alglib.teststudentttestsunit._pexec_teststudentttests (bool silent) inline static
References alglib.teststudentttestsunit.teststudentttests().
Referenced by _Test.Main().
The documentation for this class was generated from the following file:
igtest/numerics/alglib_0.8.2/tests/test_c.cs