Doc: IGLib EXTENDED: IG.Forms.BrowserSimpleForm Class Reference
IG.Forms.BrowserSimpleForm Class Reference
Public Member Functions
BrowserSimpleForm ()
void OpenLocation (string location)
Static Public Member Functions
static void BrowserMain ()
static void Example ()
Public Attributes
BrowserSimpleControl browserForm
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void BrowserSimpleWindow_VisibleChanged (object sender, EventArgs e)
void MenuStrip_ItemClicked (object sender, ToolStripItemClickedEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
Constructor & Destructor Documentation
BrowserSimpleForm()
IG.Forms.BrowserSimpleForm.BrowserSimpleForm () inline
References IG.Forms.BrowserSimpleForm.browserForm, and IG.Forms.BrowserSimpleForm.InitializeComponent().
Referenced by IG.Forms.BrowserSimpleForm.BrowserMain().
Member Function Documentation
BrowserSimpleWindow_VisibleChanged()
void IG.Forms.BrowserSimpleForm.BrowserSimpleWindow_VisibleChanged (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleForm.browserForm.
Referenced by IG.Forms.BrowserSimpleForm.InitializeComponent().
OpenLocation()
void IG.Forms.BrowserSimpleForm.OpenLocation (string location) inline
References IG.Forms.BrowserSimpleForm.browserForm, and IG.Forms.BrowserSimpleControl.OpenLocation().
Referenced by IG.Neural.Applications.NeuralDemoAbout.HelpShow(), IG.Forms.HashAboutControl.HelpShow(), IG.Neural.Applications.AbautAnnapControl.ShowHelp(), IG.Web.Forms.WSClientFormsAboutForm.ShowHelp(), IG.Neural.Applications.NeuralParametricDemoAboutOld11.ShowHelp(), IG.Neural.Applications.NeuralParametricDemoAbout.ShowHelp(), IG.Neural.Applications.NeuralParametricDemoAboutOld.ShowHelp(), IG.Neural.Applications.NeuralDemoAbout.ShowHelp(), IG.Neural.Applications.AbautAnnapControl.ShowWebPage(), IG.Neural.Applications.NeuralParametricDemoAboutOld11.ShowWebPage(), IG.Neural.Applications.NeuralParametricDemoAbout.ShowWebPage(), IG.Web.Forms.WSClientFormsAboutForm.ShowWebPage(), IG.Neural.Applications.NeuralParametricDemoAboutOld.ShowWebPage(), IG.Neural.Applications.NeuralDemoAbout.ShowWebPage(), IG.Neural.Applications.NeuralDemoAbout.WebPageShow(), and IG.Forms.HashAboutControl.WebPageShow().
BrowserMain()
static void IG.Forms.BrowserSimpleForm.BrowserMain () inline static
References IG.Forms.BrowserSimpleForm.BrowserSimpleForm().
Referenced by IG.Forms.BrowserSimpleForm.Example().
MenuStrip_ItemClicked()
void IG.Forms.BrowserSimpleForm.MenuStrip_ItemClicked (object sender, ToolStripItemClickedEventArgs e) inline private
Example()
static void IG.Forms.BrowserSimpleForm.Example () inline static
References IG.Forms.BrowserSimpleForm.BrowserMain().
Referenced by igform_console_test.test_igform_console_program.Main().
Dispose()
override void IG.Forms.BrowserSimpleForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.BrowserSimpleForm.components.
InitializeComponent()
void IG.Forms.BrowserSimpleForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.BrowserSimpleForm.browserForm, IG.Forms.BrowserSimpleForm.BrowserSimpleWindow_VisibleChanged(), IG.Forms.BrowserSimpleControl.FileToOpen, IG.Forms.BrowserSimpleControl.HomeUrl, and IG.Forms.BrowserSimpleControl.SearchUrl.
Referenced by IG.Forms.BrowserSimpleForm.BrowserSimpleForm().
Member Data Documentation
components
System.ComponentModel.IContainer IG.Forms.BrowserSimpleForm.components = null private
Required designer variable.
Referenced by IG.Forms.BrowserSimpleForm.Dispose().
browserForm
BrowserSimpleControl IG.Forms.BrowserSimpleForm.browserForm
Referenced by IG.Forms.BrowserSimpleForm.BrowserSimpleForm(), IG.Forms.BrowserSimpleForm.BrowserSimpleWindow_VisibleChanged(), IG.Forms.BrowserSimpleForm.InitializeComponent(), and IG.Forms.BrowserSimpleForm.OpenLocation().
The documentation for this class was generated from the following files:
iglib/igforms/Basic/BrowserSimpleForm.cs
iglib/igforms/Basic/BrowserSimpleForm.Designer.cs