Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DSYTRD Class Reference
DotNumerics.LinearAlgebra.CSLapack.DSYTRD Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DSYTRD (DLATRD dlatrd, DSYR2K dsyr2k, DSYTD2 dsytd2, XERBLA xerbla, LSAME lsame, ILAENV ilaenv)
DSYTRD ()
void Run (string UPLO, int N, ref double[] A, int offset_a, int LDA, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
DLATRD _dlatrd
DSYR2K _dsyr2k
DSYTD2 _dsytd2
XERBLA _xerbla
LSAME _lsame
ILAENV _ilaenv
Static Private Attributes
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DSYTRD reduces a real symmetric matrix A to real symmetric tridiagonal form T by an orthogonal similarity transformation: Q**T * A * Q = T.
/summary>
Constructor & Destructor Documentation
DSYTRD() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DSYTRD.DSYTRD (DLATRD dlatrd, DSYR2K dsyr2k, DSYTD2 dsytd2, XERBLA xerbla, LSAME lsame, ILAENV ilaenv) inline
DSYTRD() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DSYTRD.DSYTRD () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DSYTRD.Run (string UPLO, int N, ref double[] A, int offset_a, int LDA, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DSYTRD reduces a real symmetric matrix A to real symmetric tridiagonal form T by an orthogonal similarity transformation: Q**T * A * Q = T.
/summary>
Parameters
UPLO (input) CHARACTER*1 = 'U': Upper triangle of A is stored; = 'L': Lower triangle of A is stored. /param>
Parameters
N (input) INTEGER The order of the matrix A. N .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the symmetric matrix A. If UPLO = 'U', the leading N-by-N upper triangular part of A contains the upper triangular part of the matrix A, and the strictly lower triangular part of A is not referenced. If UPLO = 'L', the leading N-by-N lower triangular part of A contains the lower triangular part of the matrix A, and the strictly upper triangular part of A is not referenced. On exit, if UPLO = 'U', the diagonal and first superdiagonal of A are overwritten by the corresponding elements of the tridiagonal matrix T, and the elements above the first superdiagonal, with the array TAU, represent the orthogonal matrix Q as a product of elementary reflectors; if UPLO = 'L', the diagonal and first subdiagonal of A are over- written by the corresponding elements of the tridiagonal matrix T, and the elements below the first subdiagonal, with the array TAU, represent the orthogonal matrix Q as a product of elementary reflectors. See Further Details. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,N). /param>
Parameters
D (output) DOUBLE PRECISION array, dimension (N) The diagonal elements of the tridiagonal matrix T: D(i) = A(i,i). /param>
Parameters
E (output) DOUBLE PRECISION array, dimension (N-1) The off-diagonal elements of the tridiagonal matrix T: E(i) = A(i,i+1) if UPLO = 'U', E(i) = A(i+1,i) if UPLO = 'L'. /param>
Parameters
TAU (output) DOUBLE PRECISION array, dimension (N-1) The scalar factors of the elementary reflectors (see Further Details). /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. 1. For optimum performance LWORK .GE. N*NB, where NB is the optimal blocksize.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.DSYTRD.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYTD2.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLATRD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DSYR2K.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYEV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DSYEVD.Run().
Member Data Documentation
_dlatrd
DLATRD DotNumerics.LinearAlgebra.CSLapack.DSYTRD._dlatrd private
_dsyr2k
DSYR2K DotNumerics.LinearAlgebra.CSLapack.DSYTRD._dsyr2k private
_dsytd2
DSYTD2 DotNumerics.LinearAlgebra.CSLapack.DSYTRD._dsytd2 private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DSYTRD._xerbla private
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DSYTRD._lsame private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DSYTRD._ilaenv private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DSYTRD.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYTRD.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dsytrd.cs