Doc: IGLib EXTENDED: NUnit.Framework.Assertions.AssertIgnoreTests Class Reference
NUnit.Framework.Assertions.AssertIgnoreTests Class Reference
Tests of IgnoreException and Assert.Ignore
Public Member Functions
void ThrowsIgnoreException ()
void ThrowsIgnoreExceptionWithMessage ()
void ThrowsIgnoreExceptionWithMessageAndArgs ()
void IgnoreWorksForTestCase ()
void IgnoreWorksForTestSuite ()
void IgnoreWorksFromSetUp ()
void IgnoreWithUserMessage ()
void IgnoreWithUserMessage_OneArg ()
void IgnoreWithUserMessage_ThreeArgs ()
void IgnoreWithUserMessage_ArrayOfArgs ()
Detailed Description
Tests of IgnoreException and Assert.Ignore
Member Function Documentation
ThrowsIgnoreException()
void NUnit.Framework.Assertions.AssertIgnoreTests.ThrowsIgnoreException () inline
References NUnit.Framework.Assert.Ignore(), NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
ThrowsIgnoreExceptionWithMessage()
void NUnit.Framework.Assertions.AssertIgnoreTests.ThrowsIgnoreExceptionWithMessage () inline
References NUnit.Framework.Assert.Ignore(), NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
ThrowsIgnoreExceptionWithMessageAndArgs()
void NUnit.Framework.Assertions.AssertIgnoreTests.ThrowsIgnoreExceptionWithMessageAndArgs () inline
References NUnit.Framework.Assert.Ignore(), NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
IgnoreWorksForTestCase()
void NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWorksForTestCase () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.Ignored, NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, and NUnit.TestUtilities.TestBuilder.RunTestCase().
IgnoreWorksForTestSuite()
void NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWorksForTestSuite () inline
References NUnit.Framework.Internal.TestSuite.Add(), NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ITestResult.Children, NUnit.Framework.Interfaces.ResultState.Ignored, NUnit.TestUtilities.TestBuilder.MakeFixture(), NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTestSuite(), and NUnit.Framework.Interfaces.ResultState.WithSite().
IgnoreWorksFromSetUp()
void NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWorksFromSetUp () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ITestResult.Children, NUnit.Framework.Interfaces.ResultState.Ignored, NUnit.Framework.Internal.TestResult.ResultState, and NUnit.TestUtilities.TestBuilder.RunTestFixture().
IgnoreWithUserMessage()
void NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWithUserMessage () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.Ignore().
IgnoreWithUserMessage_OneArg()
void NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWithUserMessage_OneArg () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.Ignore().
IgnoreWithUserMessage_ThreeArgs()
void NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWithUserMessage_ThreeArgs () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.Ignore().
IgnoreWithUserMessage_ArrayOfArgs()
void NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWithUserMessage_ArrayOfArgs () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.Ignore().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/AssertIgnoreTests.cs