Doc: IGLib EXTENDED: alglib.hpccores Class Reference
alglib.hpccores Class Reference
Classes
class mlpbuffers
Static Public Member Functions
static void hpcpreparechunkedgradient (double[] weights, int wcount, int ntotal, int nin, int nout, mlpbuffers buf)
static void hpcfinalizechunkedgradient (mlpbuffers buf, double[] grad)
static bool hpcchunkedgradient (double[] weights, int[] structinfo, double[] columnmeans, double[] columnsigmas, double[,] xy, int cstart, int csize, double[] batch4buf, double[] hpcbuf, ref double e, bool naturalerrorfunc)
static bool hpcchunkedprocess (double[] weights, int[] structinfo, double[] columnmeans, double[] columnsigmas, double[,] xy, int cstart, int csize, double[] batch4buf, double[] hpcbuf)
Static Private Member Functions
static bool hpcpreparechunkedgradientx (double[] weights, int wcount, double[] hpcbuf)
static bool hpcfinalizechunkedgradientx (double[] buf, int wcount, double[] grad)
Member Function Documentation
hpcpreparechunkedgradient()
static void alglib.hpccores.hpcpreparechunkedgradient (double[] weights, int wcount, int ntotal, int nin, int nout, mlpbuffers buf) inline static
References alglib.hpccores.mlpbuffers.batch4buf, alglib.hpccores.mlpbuffers.chunksize, alglib.hpccores.mlpbuffers.desiredy, alglib.hpccores.mlpbuffers.g, alglib.hpccores.mlpbuffers.hpcbuf, alglib.hpccores.hpcpreparechunkedgradientx(), alglib.hpccores.mlpbuffers.nin, alglib.hpccores.mlpbuffers.nout, alglib.hpccores.mlpbuffers.ntotal, alglib.hpccores.mlpbuffers.wcount, alglib.hpccores.mlpbuffers.x, alglib.hpccores.mlpbuffers.xy, alglib.hpccores.mlpbuffers.xy2, alglib.hpccores.mlpbuffers.xyrow, and alglib.hpccores.mlpbuffers.y.
hpcfinalizechunkedgradient()
static void alglib.hpccores.hpcfinalizechunkedgradient (mlpbuffers buf, double[] grad) inline static
References alglib.hpccores.mlpbuffers.hpcbuf, alglib.hpccores.hpcfinalizechunkedgradientx(), and alglib.hpccores.mlpbuffers.wcount.
hpcchunkedgradient()
static bool alglib.hpccores.hpcchunkedgradient (double[] weights, int[] structinfo, double[] columnmeans, double[] columnsigmas, double xy[,], int cstart, int csize, double[] batch4buf, double[] hpcbuf, ref double e, bool naturalerrorfunc) inline static
hpcchunkedprocess()
static bool alglib.hpccores.hpcchunkedprocess (double[] weights, int[] structinfo, double[] columnmeans, double[] columnsigmas, double xy[,], int cstart, int csize, double[] batch4buf, double[] hpcbuf) inline static
hpcpreparechunkedgradientx()
static bool alglib.hpccores.hpcpreparechunkedgradientx (double[] weights, int wcount, double[] hpcbuf) inline static private
Referenced by alglib.hpccores.hpcpreparechunkedgradient().
hpcfinalizechunkedgradientx()
static bool alglib.hpccores.hpcfinalizechunkedgradientx (double[] buf, int wcount, double[] grad) inline static private
Referenced by alglib.hpccores.hpcfinalizechunkedgradient().
The documentation for this class was generated from the following file:
igtest/numerics/alglib_0.8.2/src/alglibinternal.cs