Doc: IGLib EXTENDED: alglib.testcorrunit Class Reference
alglib.testcorrunit Class Reference
Static Public Member Functions
static bool testcorr (bool silent)
static bool testcorr (bool silent)
static bool _pexec_testcorr (bool silent)
Static Private Member Functions
static void refcorrc1d (complex[] signal, int n, complex[] pattern, int m, ref complex[] r)
static void refcorrc1dcircular (complex[] signal, int n, complex[] pattern, int m, ref complex[] r)
static void refcorrr1d (double[] signal, int n, double[] pattern, int m, ref double[] r)
static void refcorrr1dcircular (double[] signal, int n, double[] pattern, int m, ref double[] r)
static void refconvc1d (complex[] a, int m, complex[] b, int n, ref complex[] r)
static void refconvc1dcircular (complex[] a, int m, complex[] b, int n, ref complex[] r)
static void refconvr1d (double[] a, int m, double[] b, int n, ref double[] r)
static void refconvr1dcircular (double[] a, int m, double[] b, int n, ref double[] r)
static void refcorrc1d (complex[] signal, int n, complex[] pattern, int m, ref complex[] r)
static void refcorrc1dcircular (complex[] signal, int n, complex[] pattern, int m, ref complex[] r)
static void refcorrr1d (double[] signal, int n, double[] pattern, int m, ref double[] r)
static void refcorrr1dcircular (double[] signal, int n, double[] pattern, int m, ref double[] r)
static void refconvc1d (complex[] a, int m, complex[] b, int n, ref complex[] r)
static void refconvc1dcircular (complex[] a, int m, complex[] b, int n, ref complex[] r)
static void refconvr1d (double[] a, int m, double[] b, int n, ref double[] r)
static void refconvr1dcircular (double[] a, int m, double[] b, int n, ref double[] r)
Member Function Documentation
testcorr() [1/2]
static bool alglib.testcorrunit.testcorr (bool silent) inline static
References alglib.math.abscomplex(), alglib.corr.corrc1d(), alglib.corr.corrc1dcircular(), alglib.corr.corrr1d(), alglib.corr.corrr1dcircular(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.testcorrunit.refcorrc1d(), alglib.testcorrunit.refcorrc1dcircular(), alglib.testcorrunit.refcorrr1d(), alglib.testcorrunit.refcorrr1dcircular(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.testcorrunit._pexec_testcorr(), and _Test.Main().
refcorrc1d() [1/2]
static void alglib.testcorrunit.refcorrc1d (complex[] signal, int n, complex[] pattern, int m, ref complex[] r) inline static private
References alglib.math.conj().
Referenced by alglib.testcorrunit.testcorr().
refcorrc1dcircular() [1/2]
static void alglib.testcorrunit.refcorrc1dcircular (complex[] signal, int n, complex[] pattern, int m, ref complex[] r) inline static private
References alglib.math.conj().
Referenced by alglib.testcorrunit.testcorr().
refcorrr1d() [1/2]
static void alglib.testcorrunit.refcorrr1d (double[] signal, int n, double[] pattern, int m, ref double[] r) inline static private
Referenced by alglib.testcorrunit.testcorr().
refcorrr1dcircular() [1/2]
static void alglib.testcorrunit.refcorrr1dcircular (double[] signal, int n, double[] pattern, int m, ref double[] r) inline static private
Referenced by alglib.testcorrunit.testcorr().
refconvc1d() [1/2]
static void alglib.testcorrunit.refconvc1d (complex[] a, int m, complex[] b, int n, ref complex[] r) inline static private
Referenced by alglib.testcorrunit.refconvc1dcircular().
refconvc1dcircular() [1/2]
static void alglib.testcorrunit.refconvc1dcircular (complex[] a, int m, complex[] b, int n, ref complex[] r) inline static private
References alglib.testcorrunit.refconvc1d().
refconvr1d() [1/2]
static void alglib.testcorrunit.refconvr1d (double[] a, int m, double[] b, int n, ref double[] r) inline static private
Referenced by alglib.testcorrunit.refconvr1dcircular().
refconvr1dcircular() [1/2]
static void alglib.testcorrunit.refconvr1dcircular (double[] a, int m, double[] b, int n, ref double[] r) inline static private
References alglib.testcorrunit.refconvr1d().
testcorr() [2/2]
static bool alglib.testcorrunit.testcorr (bool silent) inline static
References alglib.math.abscomplex(), alglib.corr.corrc1d(), alglib.corr.corrc1dcircular(), alglib.corr.corrr1d(), alglib.corr.corrr1dcircular(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.testcorrunit.refcorrc1d(), alglib.testcorrunit.refcorrc1dcircular(), alglib.testcorrunit.refcorrr1d(), alglib.testcorrunit.refcorrr1dcircular(), alglib.complex.x, and alglib.complex.y.
_pexec_testcorr()
static bool alglib.testcorrunit._pexec_testcorr (bool silent) inline static
References alglib.testcorrunit.testcorr().
Referenced by _Test.Main().
refcorrc1d() [2/2]
static void alglib.testcorrunit.refcorrc1d (complex[] signal, int n, complex[] pattern, int m, ref complex[] r) inline static private
References alglib.math.conj().
refcorrc1dcircular() [2/2]
static void alglib.testcorrunit.refcorrc1dcircular (complex[] signal, int n, complex[] pattern, int m, ref complex[] r) inline static private
References alglib.math.conj().
refcorrr1d() [2/2]
static void alglib.testcorrunit.refcorrr1d (double[] signal, int n, double[] pattern, int m, ref double[] r) inline static private
refcorrr1dcircular() [2/2]
static void alglib.testcorrunit.refcorrr1dcircular (double[] signal, int n, double[] pattern, int m, ref double[] r) inline static private
refconvc1d() [2/2]
static void alglib.testcorrunit.refconvc1d (complex[] a, int m, complex[] b, int n, ref complex[] r) inline static private
refconvc1dcircular() [2/2]
static void alglib.testcorrunit.refconvc1dcircular (complex[] a, int m, complex[] b, int n, ref complex[] r) inline static private
References alglib.testcorrunit.refconvc1d().
refconvr1d() [2/2]
static void alglib.testcorrunit.refconvr1d (double[] a, int m, double[] b, int n, ref double[] r) inline static private
refconvr1dcircular() [2/2]
static void alglib.testcorrunit.refconvr1dcircular (double[] a, int m, double[] b, int n, ref double[] r) inline static private
References alglib.testcorrunit.refconvr1d().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs