Doc: IGLib EXTENDED: IG.Lib.WSDevelopRef.WSDevelop Class Reference
IG.Lib.WSDevelopRef.WSDevelop Class Reference
Public Member Functions
WSDevelop ()
string ReturnClientTable ()
void ReturnClientTableAsync ()
void ReturnClientTableAsync (object userState)
ClientDataBase[] GetClientData (int Number)
void GetClientDataAsync (int Number)
void GetClientDataAsync (int Number, object userState)
string GetServiceName ()
void GetServiceNameAsync ()
void GetServiceNameAsync (object userState)
void SetServiceName (string name)
void SetServiceNameAsync (string name)
void SetServiceNameAsync (string name, object userState)
string TestService ()
void TestServiceAsync ()
void TestServiceAsync (object userState)
string TestServiceCmd (string commandlineArguments)
void TestServiceCmdAsync (string commandlineArguments)
void TestServiceCmdAsync (string commandlineArguments, object userState)
string TestServiceArgs (string[] commandlineArguments)
void TestServiceArgsAsync (string[] commandlineArguments)
void TestServiceArgsAsync (string[] commandlineArguments, object userState)
string TestCount ()
void TestCountAsync ()
void TestCountAsync (object userState)
new void CancelAsync (object userState)
Properties
new string Url [get, set]
new bool UseDefaultCredentials [get, set]
Events
ReturnClientTableCompletedEventHandler ReturnClientTableCompleted
GetClientDataCompletedEventHandler GetClientDataCompleted
GetServiceNameCompletedEventHandler GetServiceNameCompleted
SetServiceNameCompletedEventHandler SetServiceNameCompleted
TestServiceCompletedEventHandler TestServiceCompleted
TestServiceCmdCompletedEventHandler TestServiceCmdCompleted
TestServiceArgsCompletedEventHandler TestServiceArgsCompleted
TestCountCompletedEventHandler TestCountCompleted
Private Member Functions
void OnReturnClientTableOperationCompleted (object arg)
void OnGetClientDataOperationCompleted (object arg)
void OnGetServiceNameOperationCompleted (object arg)
void OnSetServiceNameOperationCompleted (object arg)
void OnTestServiceOperationCompleted (object arg)
void OnTestServiceCmdOperationCompleted (object arg)
void OnTestServiceArgsOperationCompleted (object arg)
void OnTestCountOperationCompleted (object arg)
bool IsLocalFileSystemWebService (string url)
Private Attributes
System.Threading.SendOrPostCallback ReturnClientTableOperationCompleted
System.Threading.SendOrPostCallback GetClientDataOperationCompleted
System.Threading.SendOrPostCallback GetServiceNameOperationCompleted
System.Threading.SendOrPostCallback SetServiceNameOperationCompleted
System.Threading.SendOrPostCallback TestServiceOperationCompleted
System.Threading.SendOrPostCallback TestServiceCmdOperationCompleted
System.Threading.SendOrPostCallback TestServiceArgsOperationCompleted
System.Threading.SendOrPostCallback TestCountOperationCompleted
bool useDefaultCredentialsSetExplicitly
Detailed Description
Constructor & Destructor Documentation
WSDevelop()
IG.Lib.WSDevelopRef.WSDevelop.WSDevelop () inline
References IG.Lib.WSDevelopRef.WSDevelop.IsLocalFileSystemWebService(), IG.Lib.WSDevelopRef.WSDevelop.Url, and IG.Lib.WSDevelopRef.WSDevelop.UseDefaultCredentials.
Member Function Documentation
ReturnClientTable()
string IG.Lib.WSDevelopRef.WSDevelop.ReturnClientTable () inline
ReturnClientTableAsync() [1/2]
void IG.Lib.WSDevelopRef.WSDevelop.ReturnClientTableAsync () inline
ReturnClientTableAsync() [2/2]
void IG.Lib.WSDevelopRef.WSDevelop.ReturnClientTableAsync (object userState) inline
References IG.Lib.WSDevelopRef.WSDevelop.OnReturnClientTableOperationCompleted(), and IG.Lib.WSDevelopRef.WSDevelop.ReturnClientTableOperationCompleted.
OnReturnClientTableOperationCompleted()
void IG.Lib.WSDevelopRef.WSDevelop.OnReturnClientTableOperationCompleted (object arg) inline private
References IG.Lib.WSDevelopRef.WSDevelop.ReturnClientTableCompleted.
Referenced by IG.Lib.WSDevelopRef.WSDevelop.ReturnClientTableAsync().
GetClientData()
ClientDataBase [] IG.Lib.WSDevelopRef.WSDevelop.GetClientData (int Number) inline
GetClientDataAsync() [1/2]
void IG.Lib.WSDevelopRef.WSDevelop.GetClientDataAsync (int Number) inline
GetClientDataAsync() [2/2]
void IG.Lib.WSDevelopRef.WSDevelop.GetClientDataAsync (int Number, object userState) inline
References IG.Lib.WSDevelopRef.WSDevelop.GetClientDataOperationCompleted, and IG.Lib.WSDevelopRef.WSDevelop.OnGetClientDataOperationCompleted().
OnGetClientDataOperationCompleted()
void IG.Lib.WSDevelopRef.WSDevelop.OnGetClientDataOperationCompleted (object arg) inline private
References IG.Lib.WSDevelopRef.WSDevelop.GetClientDataCompleted.
Referenced by IG.Lib.WSDevelopRef.WSDevelop.GetClientDataAsync().
GetServiceName()
string IG.Lib.WSDevelopRef.WSDevelop.GetServiceName () inline
GetServiceNameAsync() [1/2]
void IG.Lib.WSDevelopRef.WSDevelop.GetServiceNameAsync () inline
GetServiceNameAsync() [2/2]
void IG.Lib.WSDevelopRef.WSDevelop.GetServiceNameAsync (object userState) inline
References IG.Lib.WSDevelopRef.WSDevelop.GetServiceNameOperationCompleted, and IG.Lib.WSDevelopRef.WSDevelop.OnGetServiceNameOperationCompleted().
OnGetServiceNameOperationCompleted()
void IG.Lib.WSDevelopRef.WSDevelop.OnGetServiceNameOperationCompleted (object arg) inline private
References IG.Lib.WSDevelopRef.WSDevelop.GetServiceNameCompleted.
Referenced by IG.Lib.WSDevelopRef.WSDevelop.GetServiceNameAsync().
SetServiceName()
void IG.Lib.WSDevelopRef.WSDevelop.SetServiceName (string name) inline
SetServiceNameAsync() [1/2]
void IG.Lib.WSDevelopRef.WSDevelop.SetServiceNameAsync (string name) inline
SetServiceNameAsync() [2/2]
void IG.Lib.WSDevelopRef.WSDevelop.SetServiceNameAsync (string name, object userState) inline
References IG.Lib.WSDevelopRef.WSDevelop.OnSetServiceNameOperationCompleted(), and IG.Lib.WSDevelopRef.WSDevelop.SetServiceNameOperationCompleted.
OnSetServiceNameOperationCompleted()
void IG.Lib.WSDevelopRef.WSDevelop.OnSetServiceNameOperationCompleted (object arg) inline private
References IG.Lib.WSDevelopRef.WSDevelop.SetServiceNameCompleted.
Referenced by IG.Lib.WSDevelopRef.WSDevelop.SetServiceNameAsync().
TestService()
string IG.Lib.WSDevelopRef.WSDevelop.TestService () inline
TestServiceAsync() [1/2]
void IG.Lib.WSDevelopRef.WSDevelop.TestServiceAsync () inline
TestServiceAsync() [2/2]
void IG.Lib.WSDevelopRef.WSDevelop.TestServiceAsync (object userState) inline
References IG.Lib.WSDevelopRef.WSDevelop.OnTestServiceOperationCompleted(), and IG.Lib.WSDevelopRef.WSDevelop.TestServiceOperationCompleted.
OnTestServiceOperationCompleted()
void IG.Lib.WSDevelopRef.WSDevelop.OnTestServiceOperationCompleted (object arg) inline private
References IG.Lib.WSDevelopRef.WSDevelop.TestServiceCompleted.
Referenced by IG.Lib.WSDevelopRef.WSDevelop.TestServiceAsync().
TestServiceCmd()
string IG.Lib.WSDevelopRef.WSDevelop.TestServiceCmd (string commandlineArguments) inline
TestServiceCmdAsync() [1/2]
void IG.Lib.WSDevelopRef.WSDevelop.TestServiceCmdAsync (string commandlineArguments) inline
TestServiceCmdAsync() [2/2]
void IG.Lib.WSDevelopRef.WSDevelop.TestServiceCmdAsync (string commandlineArguments, object userState) inline
References IG.Lib.WSDevelopRef.WSDevelop.OnTestServiceCmdOperationCompleted(), and IG.Lib.WSDevelopRef.WSDevelop.TestServiceCmdOperationCompleted.
OnTestServiceCmdOperationCompleted()
void IG.Lib.WSDevelopRef.WSDevelop.OnTestServiceCmdOperationCompleted (object arg) inline private
References IG.Lib.WSDevelopRef.WSDevelop.TestServiceCmdCompleted.
Referenced by IG.Lib.WSDevelopRef.WSDevelop.TestServiceCmdAsync().
TestServiceArgs()
string IG.Lib.WSDevelopRef.WSDevelop.TestServiceArgs (string[] commandlineArguments) inline
TestServiceArgsAsync() [1/2]
void IG.Lib.WSDevelopRef.WSDevelop.TestServiceArgsAsync (string[] commandlineArguments) inline
TestServiceArgsAsync() [2/2]
void IG.Lib.WSDevelopRef.WSDevelop.TestServiceArgsAsync (string[] commandlineArguments, object userState) inline
References IG.Lib.WSDevelopRef.WSDevelop.OnTestServiceArgsOperationCompleted(), and IG.Lib.WSDevelopRef.WSDevelop.TestServiceArgsOperationCompleted.
OnTestServiceArgsOperationCompleted()
void IG.Lib.WSDevelopRef.WSDevelop.OnTestServiceArgsOperationCompleted (object arg) inline private
References IG.Lib.WSDevelopRef.WSDevelop.TestServiceArgsCompleted.
Referenced by IG.Lib.WSDevelopRef.WSDevelop.TestServiceArgsAsync().
TestCount()
string IG.Lib.WSDevelopRef.WSDevelop.TestCount () inline
TestCountAsync() [1/2]
void IG.Lib.WSDevelopRef.WSDevelop.TestCountAsync () inline
TestCountAsync() [2/2]
void IG.Lib.WSDevelopRef.WSDevelop.TestCountAsync (object userState) inline
References IG.Lib.WSDevelopRef.WSDevelop.OnTestCountOperationCompleted(), and IG.Lib.WSDevelopRef.WSDevelop.TestCountOperationCompleted.
OnTestCountOperationCompleted()
void IG.Lib.WSDevelopRef.WSDevelop.OnTestCountOperationCompleted (object arg) inline private
References IG.Lib.WSDevelopRef.WSDevelop.TestCountCompleted.
Referenced by IG.Lib.WSDevelopRef.WSDevelop.TestCountAsync().
CancelAsync()
new void IG.Lib.WSDevelopRef.WSDevelop.CancelAsync (object userState) inline
IsLocalFileSystemWebService()
bool IG.Lib.WSDevelopRef.WSDevelop.IsLocalFileSystemWebService (string url) inline private
Referenced by IG.Lib.WSDevelopRef.WSDevelop.WSDevelop().
Member Data Documentation
ReturnClientTableOperationCompleted
System.Threading.SendOrPostCallback IG.Lib.WSDevelopRef.WSDevelop.ReturnClientTableOperationCompleted private
Referenced by IG.Lib.WSDevelopRef.WSDevelop.ReturnClientTableAsync().
GetClientDataOperationCompleted
System.Threading.SendOrPostCallback IG.Lib.WSDevelopRef.WSDevelop.GetClientDataOperationCompleted private
Referenced by IG.Lib.WSDevelopRef.WSDevelop.GetClientDataAsync().
GetServiceNameOperationCompleted
System.Threading.SendOrPostCallback IG.Lib.WSDevelopRef.WSDevelop.GetServiceNameOperationCompleted private
Referenced by IG.Lib.WSDevelopRef.WSDevelop.GetServiceNameAsync().
SetServiceNameOperationCompleted
System.Threading.SendOrPostCallback IG.Lib.WSDevelopRef.WSDevelop.SetServiceNameOperationCompleted private
Referenced by IG.Lib.WSDevelopRef.WSDevelop.SetServiceNameAsync().
TestServiceOperationCompleted
System.Threading.SendOrPostCallback IG.Lib.WSDevelopRef.WSDevelop.TestServiceOperationCompleted private
Referenced by IG.Lib.WSDevelopRef.WSDevelop.TestServiceAsync().
TestServiceCmdOperationCompleted
System.Threading.SendOrPostCallback IG.Lib.WSDevelopRef.WSDevelop.TestServiceCmdOperationCompleted private
Referenced by IG.Lib.WSDevelopRef.WSDevelop.TestServiceCmdAsync().
TestServiceArgsOperationCompleted
System.Threading.SendOrPostCallback IG.Lib.WSDevelopRef.WSDevelop.TestServiceArgsOperationCompleted private
Referenced by IG.Lib.WSDevelopRef.WSDevelop.TestServiceArgsAsync().
TestCountOperationCompleted
System.Threading.SendOrPostCallback IG.Lib.WSDevelopRef.WSDevelop.TestCountOperationCompleted private
Referenced by IG.Lib.WSDevelopRef.WSDevelop.TestCountAsync().
useDefaultCredentialsSetExplicitly
bool IG.Lib.WSDevelopRef.WSDevelop.useDefaultCredentialsSetExplicitly private
Property Documentation
Url
new string IG.Lib.WSDevelopRef.WSDevelop.Url get set
Referenced by IG.Lib.WSDevelopRef.WSDevelop.WSDevelop().
UseDefaultCredentials
new bool IG.Lib.WSDevelopRef.WSDevelop.UseDefaultCredentials get set
Referenced by IG.Lib.WSDevelopRef.WSDevelop.WSDevelop().
Event Documentation
ReturnClientTableCompleted
ReturnClientTableCompletedEventHandler IG.Lib.WSDevelopRef.WSDevelop.ReturnClientTableCompleted
Referenced by IG.Lib.WSDevelopRef.WSDevelop.OnReturnClientTableOperationCompleted().
GetClientDataCompleted
GetClientDataCompletedEventHandler IG.Lib.WSDevelopRef.WSDevelop.GetClientDataCompleted
Referenced by IG.Lib.WSDevelopRef.WSDevelop.OnGetClientDataOperationCompleted().
GetServiceNameCompleted
GetServiceNameCompletedEventHandler IG.Lib.WSDevelopRef.WSDevelop.GetServiceNameCompleted
Referenced by IG.Lib.WSDevelopRef.WSDevelop.OnGetServiceNameOperationCompleted().
SetServiceNameCompleted
SetServiceNameCompletedEventHandler IG.Lib.WSDevelopRef.WSDevelop.SetServiceNameCompleted
Referenced by IG.Lib.WSDevelopRef.WSDevelop.OnSetServiceNameOperationCompleted().
TestServiceCompleted
TestServiceCompletedEventHandler IG.Lib.WSDevelopRef.WSDevelop.TestServiceCompleted
Referenced by IG.Lib.WSDevelopRef.WSDevelop.OnTestServiceOperationCompleted().
TestServiceCmdCompleted
TestServiceCmdCompletedEventHandler IG.Lib.WSDevelopRef.WSDevelop.TestServiceCmdCompleted
Referenced by IG.Lib.WSDevelopRef.WSDevelop.OnTestServiceCmdOperationCompleted().
TestServiceArgsCompleted
TestServiceArgsCompletedEventHandler IG.Lib.WSDevelopRef.WSDevelop.TestServiceArgsCompleted
Referenced by IG.Lib.WSDevelopRef.WSDevelop.OnTestServiceArgsOperationCompleted().
TestCountCompleted
TestCountCompletedEventHandler IG.Lib.WSDevelopRef.WSDevelop.TestCountCompleted
Referenced by IG.Lib.WSDevelopRef.WSDevelop.OnTestCountOperationCompleted().
The documentation for this class was generated from the following file:
igtest/IGLibTestShell/Web References/WSDevelopRef/Reference.cs