Doc: IGLib EXTENDED: IG.Forms.IndicatorLightTestControl Class Reference
IG.Forms.IndicatorLightTestControl Class Reference
Public Member Functions
IndicatorLightTestControl ()
void CopyState ()
Copies indicator light's state to controls of the current control.
void CopySettings ()
Copies indicator light's properties (without the state) to the state of this testing control.
IndicatorLightTestControl ()
void CopyState ()
Copies indicator light's state to controls of the current control.
void CopySettings ()
Copies indicator light's properties (without the state) to the state of this testing control.
IndicatorLightTestControl ()
void CopyState ()
Copies indicator light's state to controls of the current control.
void CopySettings ()
Copies indicator light's properties (without the state) to the state of this testing control.
Protected Member Functions
void CopyAll ()
override void Dispose (bool disposing)
Clean up any resources being used.
void CopyAll ()
override void Dispose (bool disposing)
Clean up any resources being used.
void CopyAll ()
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
IndicatorLight Indicator [get]
Private Member Functions
void chkOff_CheckedChanged (object sender, EventArgs e)
void chkOk_CheckedChanged (object sender, EventArgs e)
void chkBusy_CheckedChanged (object sender, EventArgs e)
void chkError_CheckedChanged (object sender, EventArgs e)
void btnBlinkOnce_Click (object sender, EventArgs e)
void btnBlinkTwice_Click (object sender, EventArgs e)
void chkBlinking_CheckedChanged (object sender, EventArgs e)
void chkThrowOnInvalid_CheckedChanged (object sender, EventArgs e)
void chkOuterBorder_CheckedChanged (object sender, EventArgs e)
void chkLabelBorder_CheckedChanged (object sender, EventArgs e)
void chkHasOff_CheckedChanged (object sender, EventArgs e)
void chkHasOk_CheckedChanged (object sender, EventArgs e)
void chkHasBusy_CheckedChanged (object sender, EventArgs e)
void chkHasError_CheckedChanged (object sender, EventArgs e)
void txtLabelText_Validated (object sender, EventArgs e)
void txtLabelText_TextChanged (object sender, EventArgs e)
void btnLabelColor_Click (object sender, EventArgs e)
void numOuterMargin_ValueChanged (object sender, EventArgs e)
void numOuterPadding_ValueChanged (object sender, EventArgs e)
void numLabelMargin_ValueChanged (object sender, EventArgs e)
void numLabelPadding_ValueChanged (object sender, EventArgs e)
void numBlinkTime_ValueChanged (object sender, EventArgs e)
void fontSelectorSimple1_FontSelected (object sender, FontEventArgs args)
void btnBlinkYellow3_Click (object sender, EventArgs e)
void btnBlinkError2x_Click (object sender, EventArgs e)
void comboDirection_SelectedIndexChanged (object sender, EventArgs e)
void comboDirection_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void chkOff_CheckedChanged (object sender, EventArgs e)
void chkOk_CheckedChanged (object sender, EventArgs e)
void chkBusy_CheckedChanged (object sender, EventArgs e)
void chkError_CheckedChanged (object sender, EventArgs e)
void btnBlinkOnce_Click (object sender, EventArgs e)
void btnBlinkTwice_Click (object sender, EventArgs e)
void chkBlinking_CheckedChanged (object sender, EventArgs e)
void chkThrowOnInvalid_CheckedChanged (object sender, EventArgs e)
void chkOuterBorder_CheckedChanged (object sender, EventArgs e)
void chkLabelBorder_CheckedChanged (object sender, EventArgs e)
void chkHasOff_CheckedChanged (object sender, EventArgs e)
void chkHasOk_CheckedChanged (object sender, EventArgs e)
void chkHasBusy_CheckedChanged (object sender, EventArgs e)
void chkHasError_CheckedChanged (object sender, EventArgs e)
void txtLabelText_Validated (object sender, EventArgs e)
void txtLabelText_TextChanged (object sender, EventArgs e)
void btnLabelColor_Click (object sender, EventArgs e)
void numOuterMargin_ValueChanged (object sender, EventArgs e)
void numOuterPadding_ValueChanged (object sender, EventArgs e)
void numLabelMargin_ValueChanged (object sender, EventArgs e)
void numLabelPadding_ValueChanged (object sender, EventArgs e)
void numBlinkTime_ValueChanged (object sender, EventArgs e)
void fontSelectorSimple1_FontSelected (object sender, FontEventArgs args)
void btnBlinkYellow3_Click (object sender, EventArgs e)
void btnBlinkError2x_Click (object sender, EventArgs e)
void comboDirection_SelectedIndexChanged (object sender, EventArgs e)
void comboDirection_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void chkOff_CheckedChanged (object sender, EventArgs e)
void chkOk_CheckedChanged (object sender, EventArgs e)
void chkBusy_CheckedChanged (object sender, EventArgs e)
void chkError_CheckedChanged (object sender, EventArgs e)
void btnBlinkOnce_Click (object sender, EventArgs e)
void btnBlinkTwice_Click (object sender, EventArgs e)
void chkBlinking_CheckedChanged (object sender, EventArgs e)
void chkThrowOnInvalid_CheckedChanged (object sender, EventArgs e)
void chkOuterBorder_CheckedChanged (object sender, EventArgs e)
void chkLabelBorder_CheckedChanged (object sender, EventArgs e)
void chkHasOff_CheckedChanged (object sender, EventArgs e)
void chkHasOk_CheckedChanged (object sender, EventArgs e)
void chkHasBusy_CheckedChanged (object sender, EventArgs e)
void chkHasError_CheckedChanged (object sender, EventArgs e)
void txtLabelText_Validated (object sender, EventArgs e)
void txtLabelText_TextChanged (object sender, EventArgs e)
void btnLabelColor_Click (object sender, EventArgs e)
void numOuterMargin_ValueChanged (object sender, EventArgs e)
void numOuterPadding_ValueChanged (object sender, EventArgs e)
void numLabelMargin_ValueChanged (object sender, EventArgs e)
void numLabelPadding_ValueChanged (object sender, EventArgs e)
void numBlinkTime_ValueChanged (object sender, EventArgs e)
void fontSelectorSimple1_FontSelected (object sender, FontEventArgs args)
void btnBlinkYellow3_Click (object sender, EventArgs e)
void btnBlinkError2x_Click (object sender, EventArgs e)
void comboDirection_SelectedIndexChanged (object sender, EventArgs e)
void comboDirection_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
IG.Forms.IndicatorLight indicatorLight1
System.Windows.Forms.CheckBox chkThrowOnInvalid
System.Windows.Forms.CheckBox chkOuterBorder
System.Windows.Forms.CheckBox chkLabelBorder
System.Windows.Forms.CheckBox chkHasOff
System.Windows.Forms.CheckBox chkHasOk
System.Windows.Forms.CheckBox chkHasBusy
System.Windows.Forms.CheckBox chkHasError
System.Windows.Forms.GroupBox grpProperties
System.Windows.Forms.TextBox txtLabelText
System.Windows.Forms.NumericUpDown numOuterPadding
System.Windows.Forms.NumericUpDown numOuterMargin
System.Windows.Forms.Label lblLabelMargin
System.Windows.Forms.Label lblOuterMargin
System.Windows.Forms.NumericUpDown numLabelPadding
System.Windows.Forms.NumericUpDown numLabelMargin
System.Windows.Forms.Button btnLabelColor
System.Windows.Forms.GroupBox grpState
System.Windows.Forms.CheckBox chkOff
System.Windows.Forms.ColorDialog colorDialog1
System.Windows.Forms.CheckBox chkBlinking
System.Windows.Forms.CheckBox chkError
System.Windows.Forms.CheckBox chkBusy
System.Windows.Forms.CheckBox chkOk
System.Windows.Forms.Button btnBlinkTwice
System.Windows.Forms.Button btnBlinkOnce
System.Windows.Forms.Label lblBlinkTime
System.Windows.Forms.NumericUpDown numBlinkTime
System.Windows.Forms.Label label1
System.Windows.Forms.Label lblFont
FontSelectorSimple fontSelectorSimple1
System.Windows.Forms.Label lblLabelFont
System.Windows.Forms.Button btnBlinkYellow3
System.Windows.Forms.Button btnBlinkError2x
System.Windows.Forms.ComboBox comboDirection
System.Windows.Forms.Label lblFlowDirection
System.Windows.Forms.Panel pnlIndicatorContainerInner
System.Windows.Forms.Panel pnlIndicatorContainerOuter
Constructor & Destructor Documentation
IndicatorLightTestControl() [1/3]
IG.Forms.IndicatorLightTestControl.IndicatorLightTestControl () inline
References IG.Forms.IndicatorLightTestControl.comboDirection, IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLightTestControl.CopyState(), and IG.Forms.IndicatorLightTestControl.InitializeComponent().
IndicatorLightTestControl() [2/3]
IG.Forms.IndicatorLightTestControl.IndicatorLightTestControl () inline
References IG.Forms.IndicatorLightTestControl.comboDirection, IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLightTestControl.CopyState(), and IG.Forms.IndicatorLightTestControl.InitializeComponent().
IndicatorLightTestControl() [3/3]
IG.Forms.IndicatorLightTestControl.IndicatorLightTestControl () inline
References IG.Forms.IndicatorLightTestControl.comboDirection, IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLightTestControl.CopyState(), and IG.Forms.IndicatorLightTestControl.InitializeComponent().
Member Function Documentation
CopyAll() [1/3]
void IG.Forms.IndicatorLightTestControl.CopyAll () inline protected
References IG.Forms.IndicatorLightTestControl.CopySettings(), and IG.Forms.IndicatorLightTestControl.CopyState().
Referenced by IG.Forms.IndicatorLightTestControl.btnLabelColor_Click(), IG.Forms.IndicatorLightTestControl.chkBlinking_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkBusy_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkError_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkHasBusy_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkHasError_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkHasOff_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkHasOk_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkLabelBorder_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkOff_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkOk_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkOuterBorder_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkThrowOnInvalid_CheckedChanged(), IG.Forms.IndicatorLightTestControl.numLabelMargin_ValueChanged(), IG.Forms.IndicatorLightTestControl.numLabelPadding_ValueChanged(), IG.Forms.IndicatorLightTestControl.numOuterMargin_ValueChanged(), IG.Forms.IndicatorLightTestControl.numOuterPadding_ValueChanged(), and IG.Forms.IndicatorLightTestControl.txtLabelText_Validated().
CopyState() [1/3]
void IG.Forms.IndicatorLightTestControl.CopyState () inline
Copies indicator light's state to controls of the current control.
By state we just mean state that is meant to change during operation, i.e. mode of the light (like Off, OK, ..., IsBlinking).
References IG.Forms.IndicatorLightTestControl.chkBlinking, IG.Forms.IndicatorLightTestControl.chkBusy, IG.Forms.IndicatorLightTestControl.chkError, IG.Forms.IndicatorLightTestControl.chkOff, IG.Forms.IndicatorLightTestControl.chkOk, IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLight.IsBusy, IG.Forms.IndicatorLight.IsError, IG.Forms.IndicatorLight.IsOff, and IG.Forms.IndicatorLight.IsOk.
Referenced by IG.Forms.IndicatorLightTestControl.CopyAll(), and IG.Forms.IndicatorLightTestControl.IndicatorLightTestControl().
CopySettings() [1/3]
void IG.Forms.IndicatorLightTestControl.CopySettings () inline
Copies indicator light's properties (without the state) to the state of this testing control.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.IndicatorLightTestControl.chkHasBusy, IG.Forms.IndicatorLightTestControl.chkHasError, IG.Forms.IndicatorLightTestControl.chkHasOff, IG.Forms.IndicatorLightTestControl.chkHasOk, IG.Forms.IndicatorLightTestControl.chkLabelBorder, IG.Forms.IndicatorLightTestControl.chkOuterBorder, IG.Forms.IndicatorLightTestControl.chkThrowOnInvalid, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.LabelText, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.IndicatorLightTestControl.numBlinkTime, IG.Forms.IndicatorLightTestControl.numLabelMargin, IG.Forms.IndicatorLightTestControl.numLabelPadding, IG.Forms.IndicatorLightTestControl.numOuterMargin, IG.Forms.IndicatorLightTestControl.numOuterPadding, IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, and IG.Forms.IndicatorLightTestControl.txtLabelText.
Referenced by IG.Forms.IndicatorLightTestControl.CopyAll(), and IG.Forms.IndicatorLightTestControl.IndicatorLightTestControl().
chkOff_CheckedChanged() [1/3]
void IG.Forms.IndicatorLightTestControl.chkOff_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkOff, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.UtilForms.Reporter, IG.Forms.IndicatorLight.SetOff(), and IG.Forms.IndicatorLight.UnsetOff().
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkOk_CheckedChanged() [1/3]
void IG.Forms.IndicatorLightTestControl.chkOk_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkOk, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.UtilForms.Reporter, IG.Forms.IndicatorLight.SetOk(), and IG.Forms.IndicatorLight.UnsetOk().
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkBusy_CheckedChanged() [1/3]
void IG.Forms.IndicatorLightTestControl.chkBusy_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkBusy, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.UtilForms.Reporter, IG.Forms.IndicatorLight.SetBusy(), and IG.Forms.IndicatorLight.UnsetBusy().
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkError_CheckedChanged() [1/3]
void IG.Forms.IndicatorLightTestControl.chkError_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkError, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.UtilForms.Reporter, IG.Forms.IndicatorLight.SetError(), and IG.Forms.IndicatorLight.UnsetError().
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
btnBlinkOnce_Click() [1/3]
void IG.Forms.IndicatorLightTestControl.btnBlinkOnce_Click (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.Blink(), and IG.Forms.IndicatorLightTestControl.Indicator.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
btnBlinkTwice_Click() [1/3]
void IG.Forms.IndicatorLightTestControl.btnBlinkTwice_Click (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.Blink(), and IG.Forms.IndicatorLightTestControl.Indicator.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkBlinking_CheckedChanged() [1/3]
void IG.Forms.IndicatorLightTestControl.chkBlinking_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkBlinking, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, and IG.Forms.IndicatorLight.IsBlinking.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkThrowOnInvalid_CheckedChanged() [1/3]
void IG.Forms.IndicatorLightTestControl.chkThrowOnInvalid_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkThrowOnInvalid, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, and IG.Forms.IndicatorLight.ThrowOnInvalidSwitch.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkOuterBorder_CheckedChanged() [1/3]
void IG.Forms.IndicatorLightTestControl.chkOuterBorder_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.BorderOut, IG.Forms.IndicatorLightTestControl.chkOuterBorder, IG.Forms.IndicatorLightTestControl.CopyAll(), and IG.Forms.IndicatorLightTestControl.Indicator.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkLabelBorder_CheckedChanged() [1/3]
void IG.Forms.IndicatorLightTestControl.chkLabelBorder_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLightTestControl.chkLabelBorder, IG.Forms.IndicatorLightTestControl.CopyAll(), and IG.Forms.IndicatorLightTestControl.Indicator.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkHasOff_CheckedChanged() [1/3]
void IG.Forms.IndicatorLightTestControl.chkHasOff_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkHasOff, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLight.HasOff, and IG.Forms.IndicatorLightTestControl.Indicator.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkHasOk_CheckedChanged() [1/3]
void IG.Forms.IndicatorLightTestControl.chkHasOk_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkHasOk, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLight.HasOk, and IG.Forms.IndicatorLightTestControl.Indicator.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkHasBusy_CheckedChanged() [1/3]
void IG.Forms.IndicatorLightTestControl.chkHasBusy_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkHasBusy, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLight.HasBusy, and IG.Forms.IndicatorLightTestControl.Indicator.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkHasError_CheckedChanged() [1/3]
void IG.Forms.IndicatorLightTestControl.chkHasError_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkHasError, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLight.HasError, and IG.Forms.IndicatorLightTestControl.Indicator.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
txtLabelText_Validated() [1/3]
void IG.Forms.IndicatorLightTestControl.txtLabelText_Validated (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.LabelText, and IG.Forms.IndicatorLightTestControl.txtLabelText.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
txtLabelText_TextChanged() [1/3]
void IG.Forms.IndicatorLightTestControl.txtLabelText_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.LabelText, and IG.Forms.IndicatorLightTestControl.txtLabelText.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
btnLabelColor_Click() [1/3]
void IG.Forms.IndicatorLightTestControl.btnLabelColor_Click (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.colorDialog1, IG.Forms.IndicatorLight.ColorLabel, IG.Forms.IndicatorLightTestControl.CopyAll(), and IG.Forms.IndicatorLightTestControl.Indicator.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
numOuterMargin_ValueChanged() [1/3]
void IG.Forms.IndicatorLightTestControl.numOuterMargin_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.MarginOut, and IG.Forms.IndicatorLightTestControl.numOuterMargin.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
numOuterPadding_ValueChanged() [1/3]
void IG.Forms.IndicatorLightTestControl.numOuterPadding_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLightTestControl.numOuterPadding, and IG.Forms.IndicatorLight.PaddingOut.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
numLabelMargin_ValueChanged() [1/3]
void IG.Forms.IndicatorLightTestControl.numLabelMargin_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.MarginLabel, and IG.Forms.IndicatorLightTestControl.numLabelMargin.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
numLabelPadding_ValueChanged() [1/3]
void IG.Forms.IndicatorLightTestControl.numLabelPadding_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLightTestControl.numLabelPadding, and IG.Forms.IndicatorLight.PaddingLabel.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
numBlinkTime_ValueChanged() [1/3]
void IG.Forms.IndicatorLightTestControl.numBlinkTime_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLightTestControl.Indicator, and IG.Forms.IndicatorLightTestControl.numBlinkTime.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
fontSelectorSimple1_FontSelected() [1/3]
void IG.Forms.IndicatorLightTestControl.fontSelectorSimple1_FontSelected (object sender, FontEventArgs args) inline private
References IG.Forms.IndicatorLightTestControl.fontSelectorSimple1, IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.LabelFont, and IG.Forms.FontSelectorSimple.SelectedFont.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
btnBlinkYellow3_Click() [1/3]
void IG.Forms.IndicatorLightTestControl.btnBlinkYellow3_Click (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.BlinkSpecial(), and IG.Forms.IndicatorLightTestControl.Indicator.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
btnBlinkError2x_Click() [1/3]
void IG.Forms.IndicatorLightTestControl.btnBlinkError2x_Click (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.BlinkError(), and IG.Forms.IndicatorLightTestControl.Indicator.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
comboDirection_SelectedIndexChanged() [1/3]
void IG.Forms.IndicatorLightTestControl.comboDirection_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.comboDirection, IG.Forms.IndicatorLight.FlowDirection, and IG.Forms.IndicatorLightTestControl.Indicator.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
comboDirection_Click() [1/3]
void IG.Forms.IndicatorLightTestControl.comboDirection_Click (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.comboDirection.
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
Dispose() [1/3]
override void IG.Forms.IndicatorLightTestControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.IndicatorLightTestControl.components.
InitializeComponent() [1/3]
void IG.Forms.IndicatorLightTestControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.IndicatorLightTestControl.btnBlinkError2x, IG.Forms.IndicatorLightTestControl.btnBlinkError2x_Click(), IG.Forms.IndicatorLightTestControl.btnBlinkOnce, IG.Forms.IndicatorLightTestControl.btnBlinkOnce_Click(), IG.Forms.IndicatorLightTestControl.btnBlinkTwice, IG.Forms.IndicatorLightTestControl.btnBlinkTwice_Click(), IG.Forms.IndicatorLightTestControl.btnBlinkYellow3, IG.Forms.IndicatorLightTestControl.btnBlinkYellow3_Click(), IG.Forms.IndicatorLightTestControl.btnLabelColor, IG.Forms.IndicatorLightTestControl.btnLabelColor_Click(), IG.Forms.IndicatorLightTestControl.chkBlinking, IG.Forms.IndicatorLightTestControl.chkBlinking_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkBusy, IG.Forms.IndicatorLightTestControl.chkBusy_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkError, IG.Forms.IndicatorLightTestControl.chkError_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkHasBusy, IG.Forms.IndicatorLightTestControl.chkHasBusy_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkHasError, IG.Forms.IndicatorLightTestControl.chkHasError_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkHasOff, IG.Forms.IndicatorLightTestControl.chkHasOff_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkHasOk, IG.Forms.IndicatorLightTestControl.chkHasOk_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkLabelBorder, IG.Forms.IndicatorLightTestControl.chkLabelBorder_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkOff, IG.Forms.IndicatorLightTestControl.chkOff_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkOk, IG.Forms.IndicatorLightTestControl.chkOk_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkOuterBorder, IG.Forms.IndicatorLightTestControl.chkOuterBorder_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkThrowOnInvalid, IG.Forms.IndicatorLightTestControl.chkThrowOnInvalid_CheckedChanged(), IG.Forms.IndicatorLightTestControl.colorDialog1, IG.Forms.IndicatorLight.ColorLabel, IG.Forms.IndicatorLightTestControl.comboDirection, IG.Forms.IndicatorLightTestControl.comboDirection_Click(), IG.Forms.IndicatorLightTestControl.comboDirection_SelectedIndexChanged(), IG.Forms.IndicatorLight.FlowDirection, IG.Forms.FontSelectorSimple.FontSelected, IG.Forms.IndicatorLightTestControl.fontSelectorSimple1, IG.Forms.IndicatorLightTestControl.fontSelectorSimple1_FontSelected(), IG.Forms.IndicatorLightTestControl.grpProperties, IG.Forms.IndicatorLightTestControl.grpState, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLightTestControl.indicatorLight1, IG.Forms.FontSelectorSimple.InitialFontLabelText, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLightTestControl.label1, IG.Forms.IndicatorLight.LabelFont, IG.Forms.IndicatorLight.LabelText, IG.Forms.IndicatorLightTestControl.lblBlinkTime, IG.Forms.IndicatorLightTestControl.lblFlowDirection, IG.Forms.IndicatorLightTestControl.lblFont, IG.Forms.IndicatorLightTestControl.lblLabelFont, IG.Forms.IndicatorLightTestControl.lblLabelMargin, IG.Forms.IndicatorLightTestControl.lblOuterMargin, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.IndicatorLightTestControl.numBlinkTime, IG.Forms.IndicatorLightTestControl.numBlinkTime_ValueChanged(), IG.Forms.IndicatorLightTestControl.numLabelMargin, IG.Forms.IndicatorLightTestControl.numLabelMargin_ValueChanged(), IG.Forms.IndicatorLightTestControl.numLabelPadding, IG.Forms.IndicatorLightTestControl.numLabelPadding_ValueChanged(), IG.Forms.IndicatorLightTestControl.numOuterMargin, IG.Forms.IndicatorLightTestControl.numOuterMargin_ValueChanged(), IG.Forms.IndicatorLightTestControl.numOuterPadding, IG.Forms.IndicatorLightTestControl.numOuterPadding_ValueChanged(), IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.IndicatorLightTestControl.pnlIndicatorContainerInner, IG.Forms.IndicatorLightTestControl.pnlIndicatorContainerOuter, IG.Forms.FontSelectorSimple.SelectedFont, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, IG.Forms.IndicatorLightTestControl.txtLabelText, IG.Forms.IndicatorLightTestControl.txtLabelText_TextChanged(), and IG.Forms.IndicatorLightTestControl.txtLabelText_Validated().
Referenced by IG.Forms.IndicatorLightTestControl.IndicatorLightTestControl().
CopyAll() [2/3]
void IG.Forms.IndicatorLightTestControl.CopyAll () inline protected
References IG.Forms.IndicatorLightTestControl.CopySettings(), and IG.Forms.IndicatorLightTestControl.CopyState().
CopyState() [2/3]
void IG.Forms.IndicatorLightTestControl.CopyState () inline
Copies indicator light's state to controls of the current control.
By state we just mean state that is meant to change during operation, i.e. mode of the light (like Off, OK, ..., IsBlinking).
References IG.Forms.IndicatorLightTestControl.chkBlinking, IG.Forms.IndicatorLightTestControl.chkBusy, IG.Forms.IndicatorLightTestControl.chkError, IG.Forms.IndicatorLightTestControl.chkOff, IG.Forms.IndicatorLightTestControl.chkOk, IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLight.IsBusy, IG.Forms.IndicatorLight.IsError, IG.Forms.IndicatorLight.IsOff, and IG.Forms.IndicatorLight.IsOk.
CopySettings() [2/3]
void IG.Forms.IndicatorLightTestControl.CopySettings () inline
Copies indicator light's properties (without the state) to the state of this testing control.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.IndicatorLightTestControl.chkHasBusy, IG.Forms.IndicatorLightTestControl.chkHasError, IG.Forms.IndicatorLightTestControl.chkHasOff, IG.Forms.IndicatorLightTestControl.chkHasOk, IG.Forms.IndicatorLightTestControl.chkLabelBorder, IG.Forms.IndicatorLightTestControl.chkOuterBorder, IG.Forms.IndicatorLightTestControl.chkThrowOnInvalid, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.LabelText, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.IndicatorLightTestControl.numBlinkTime, IG.Forms.IndicatorLightTestControl.numLabelMargin, IG.Forms.IndicatorLightTestControl.numLabelPadding, IG.Forms.IndicatorLightTestControl.numOuterMargin, IG.Forms.IndicatorLightTestControl.numOuterPadding, IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, and IG.Forms.IndicatorLightTestControl.txtLabelText.
chkOff_CheckedChanged() [2/3]
void IG.Forms.IndicatorLightTestControl.chkOff_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkOff, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.UtilForms.Reporter, IG.Forms.IndicatorLight.SetOff(), and IG.Forms.IndicatorLight.UnsetOff().
chkOk_CheckedChanged() [2/3]
void IG.Forms.IndicatorLightTestControl.chkOk_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkOk, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.UtilForms.Reporter, IG.Forms.IndicatorLight.SetOk(), and IG.Forms.IndicatorLight.UnsetOk().
chkBusy_CheckedChanged() [2/3]
void IG.Forms.IndicatorLightTestControl.chkBusy_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkBusy, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.UtilForms.Reporter, IG.Forms.IndicatorLight.SetBusy(), and IG.Forms.IndicatorLight.UnsetBusy().
chkError_CheckedChanged() [2/3]
void IG.Forms.IndicatorLightTestControl.chkError_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkError, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.UtilForms.Reporter, IG.Forms.IndicatorLight.SetError(), and IG.Forms.IndicatorLight.UnsetError().
btnBlinkOnce_Click() [2/3]
void IG.Forms.IndicatorLightTestControl.btnBlinkOnce_Click (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.Blink(), and IG.Forms.IndicatorLightTestControl.Indicator.
btnBlinkTwice_Click() [2/3]
void IG.Forms.IndicatorLightTestControl.btnBlinkTwice_Click (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.Blink(), and IG.Forms.IndicatorLightTestControl.Indicator.
chkBlinking_CheckedChanged() [2/3]
void IG.Forms.IndicatorLightTestControl.chkBlinking_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkBlinking, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, and IG.Forms.IndicatorLight.IsBlinking.
chkThrowOnInvalid_CheckedChanged() [2/3]
void IG.Forms.IndicatorLightTestControl.chkThrowOnInvalid_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkThrowOnInvalid, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, and IG.Forms.IndicatorLight.ThrowOnInvalidSwitch.
chkOuterBorder_CheckedChanged() [2/3]
void IG.Forms.IndicatorLightTestControl.chkOuterBorder_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.BorderOut, IG.Forms.IndicatorLightTestControl.chkOuterBorder, IG.Forms.IndicatorLightTestControl.CopyAll(), and IG.Forms.IndicatorLightTestControl.Indicator.
chkLabelBorder_CheckedChanged() [2/3]
void IG.Forms.IndicatorLightTestControl.chkLabelBorder_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLightTestControl.chkLabelBorder, IG.Forms.IndicatorLightTestControl.CopyAll(), and IG.Forms.IndicatorLightTestControl.Indicator.
chkHasOff_CheckedChanged() [2/3]
void IG.Forms.IndicatorLightTestControl.chkHasOff_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkHasOff, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLight.HasOff, and IG.Forms.IndicatorLightTestControl.Indicator.
chkHasOk_CheckedChanged() [2/3]
void IG.Forms.IndicatorLightTestControl.chkHasOk_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkHasOk, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLight.HasOk, and IG.Forms.IndicatorLightTestControl.Indicator.
chkHasBusy_CheckedChanged() [2/3]
void IG.Forms.IndicatorLightTestControl.chkHasBusy_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkHasBusy, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLight.HasBusy, and IG.Forms.IndicatorLightTestControl.Indicator.
chkHasError_CheckedChanged() [2/3]
void IG.Forms.IndicatorLightTestControl.chkHasError_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkHasError, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLight.HasError, and IG.Forms.IndicatorLightTestControl.Indicator.
txtLabelText_Validated() [2/3]
void IG.Forms.IndicatorLightTestControl.txtLabelText_Validated (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.LabelText, and IG.Forms.IndicatorLightTestControl.txtLabelText.
txtLabelText_TextChanged() [2/3]
void IG.Forms.IndicatorLightTestControl.txtLabelText_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.LabelText, and IG.Forms.IndicatorLightTestControl.txtLabelText.
btnLabelColor_Click() [2/3]
void IG.Forms.IndicatorLightTestControl.btnLabelColor_Click (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.colorDialog1, IG.Forms.IndicatorLight.ColorLabel, IG.Forms.IndicatorLightTestControl.CopyAll(), and IG.Forms.IndicatorLightTestControl.Indicator.
numOuterMargin_ValueChanged() [2/3]
void IG.Forms.IndicatorLightTestControl.numOuterMargin_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.MarginOut, and IG.Forms.IndicatorLightTestControl.numOuterMargin.
numOuterPadding_ValueChanged() [2/3]
void IG.Forms.IndicatorLightTestControl.numOuterPadding_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLightTestControl.numOuterPadding, and IG.Forms.IndicatorLight.PaddingOut.
numLabelMargin_ValueChanged() [2/3]
void IG.Forms.IndicatorLightTestControl.numLabelMargin_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.MarginLabel, and IG.Forms.IndicatorLightTestControl.numLabelMargin.
numLabelPadding_ValueChanged() [2/3]
void IG.Forms.IndicatorLightTestControl.numLabelPadding_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLightTestControl.numLabelPadding, and IG.Forms.IndicatorLight.PaddingLabel.
numBlinkTime_ValueChanged() [2/3]
void IG.Forms.IndicatorLightTestControl.numBlinkTime_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLightTestControl.Indicator, and IG.Forms.IndicatorLightTestControl.numBlinkTime.
fontSelectorSimple1_FontSelected() [2/3]
void IG.Forms.IndicatorLightTestControl.fontSelectorSimple1_FontSelected (object sender, FontEventArgs args) inline private
References IG.Forms.IndicatorLightTestControl.fontSelectorSimple1, IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.LabelFont, and IG.Forms.FontSelectorSimple.SelectedFont.
btnBlinkYellow3_Click() [2/3]
void IG.Forms.IndicatorLightTestControl.btnBlinkYellow3_Click (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.BlinkSpecial(), and IG.Forms.IndicatorLightTestControl.Indicator.
btnBlinkError2x_Click() [2/3]
void IG.Forms.IndicatorLightTestControl.btnBlinkError2x_Click (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.BlinkError(), and IG.Forms.IndicatorLightTestControl.Indicator.
comboDirection_SelectedIndexChanged() [2/3]
void IG.Forms.IndicatorLightTestControl.comboDirection_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.comboDirection, IG.Forms.IndicatorLight.FlowDirection, and IG.Forms.IndicatorLightTestControl.Indicator.
comboDirection_Click() [2/3]
void IG.Forms.IndicatorLightTestControl.comboDirection_Click (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.comboDirection.
Dispose() [2/3]
override void IG.Forms.IndicatorLightTestControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.IndicatorLightTestControl.components.
InitializeComponent() [2/3]
void IG.Forms.IndicatorLightTestControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.IndicatorLightTestControl.btnBlinkError2x, IG.Forms.IndicatorLightTestControl.btnBlinkError2x_Click(), IG.Forms.IndicatorLightTestControl.btnBlinkOnce, IG.Forms.IndicatorLightTestControl.btnBlinkOnce_Click(), IG.Forms.IndicatorLightTestControl.btnBlinkTwice, IG.Forms.IndicatorLightTestControl.btnBlinkTwice_Click(), IG.Forms.IndicatorLightTestControl.btnBlinkYellow3, IG.Forms.IndicatorLightTestControl.btnBlinkYellow3_Click(), IG.Forms.IndicatorLightTestControl.btnLabelColor, IG.Forms.IndicatorLightTestControl.btnLabelColor_Click(), IG.Forms.IndicatorLightTestControl.chkBlinking, IG.Forms.IndicatorLightTestControl.chkBlinking_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkBusy, IG.Forms.IndicatorLightTestControl.chkBusy_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkError, IG.Forms.IndicatorLightTestControl.chkError_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkHasBusy, IG.Forms.IndicatorLightTestControl.chkHasBusy_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkHasError, IG.Forms.IndicatorLightTestControl.chkHasError_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkHasOff, IG.Forms.IndicatorLightTestControl.chkHasOff_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkHasOk, IG.Forms.IndicatorLightTestControl.chkHasOk_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkLabelBorder, IG.Forms.IndicatorLightTestControl.chkLabelBorder_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkOff, IG.Forms.IndicatorLightTestControl.chkOff_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkOk, IG.Forms.IndicatorLightTestControl.chkOk_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkOuterBorder, IG.Forms.IndicatorLightTestControl.chkOuterBorder_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkThrowOnInvalid, IG.Forms.IndicatorLightTestControl.chkThrowOnInvalid_CheckedChanged(), IG.Forms.IndicatorLightTestControl.colorDialog1, IG.Forms.IndicatorLight.ColorLabel, IG.Forms.IndicatorLightTestControl.comboDirection, IG.Forms.IndicatorLightTestControl.comboDirection_Click(), IG.Forms.IndicatorLightTestControl.comboDirection_SelectedIndexChanged(), IG.Forms.IndicatorLight.FlowDirection, IG.Forms.FontSelectorSimple.FontSelected, IG.Forms.IndicatorLightTestControl.fontSelectorSimple1, IG.Forms.IndicatorLightTestControl.fontSelectorSimple1_FontSelected(), IG.Forms.IndicatorLightTestControl.grpProperties, IG.Forms.IndicatorLightTestControl.grpState, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLightTestControl.indicatorLight1, IG.Forms.FontSelectorSimple.InitialFontLabelText, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLightTestControl.label1, IG.Forms.IndicatorLight.LabelFont, IG.Forms.IndicatorLight.LabelText, IG.Forms.IndicatorLightTestControl.lblBlinkTime, IG.Forms.IndicatorLightTestControl.lblFlowDirection, IG.Forms.IndicatorLightTestControl.lblFont, IG.Forms.IndicatorLightTestControl.lblLabelFont, IG.Forms.IndicatorLightTestControl.lblLabelMargin, IG.Forms.IndicatorLightTestControl.lblOuterMargin, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.IndicatorLightTestControl.numBlinkTime, IG.Forms.IndicatorLightTestControl.numBlinkTime_ValueChanged(), IG.Forms.IndicatorLightTestControl.numLabelMargin, IG.Forms.IndicatorLightTestControl.numLabelMargin_ValueChanged(), IG.Forms.IndicatorLightTestControl.numLabelPadding, IG.Forms.IndicatorLightTestControl.numLabelPadding_ValueChanged(), IG.Forms.IndicatorLightTestControl.numOuterMargin, IG.Forms.IndicatorLightTestControl.numOuterMargin_ValueChanged(), IG.Forms.IndicatorLightTestControl.numOuterPadding, IG.Forms.IndicatorLightTestControl.numOuterPadding_ValueChanged(), IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.IndicatorLightTestControl.pnlIndicatorContainerInner, IG.Forms.IndicatorLightTestControl.pnlIndicatorContainerOuter, IG.Forms.FontSelectorSimple.SelectedFont, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, IG.Forms.IndicatorLightTestControl.txtLabelText, IG.Forms.IndicatorLightTestControl.txtLabelText_TextChanged(), and IG.Forms.IndicatorLightTestControl.txtLabelText_Validated().
CopyAll() [3/3]
void IG.Forms.IndicatorLightTestControl.CopyAll () inline protected
References IG.Forms.IndicatorLightTestControl.CopySettings(), and IG.Forms.IndicatorLightTestControl.CopyState().
CopyState() [3/3]
void IG.Forms.IndicatorLightTestControl.CopyState () inline
Copies indicator light's state to controls of the current control.
By state we just mean state that is meant to change during operation, i.e. mode of the light (like Off, OK, ..., IsBlinking).
References IG.Forms.IndicatorLightTestControl.chkBlinking, IG.Forms.IndicatorLightTestControl.chkBusy, IG.Forms.IndicatorLightTestControl.chkError, IG.Forms.IndicatorLightTestControl.chkOff, IG.Forms.IndicatorLightTestControl.chkOk, IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLight.IsBusy, IG.Forms.IndicatorLight.IsError, IG.Forms.IndicatorLight.IsOff, and IG.Forms.IndicatorLight.IsOk.
CopySettings() [3/3]
void IG.Forms.IndicatorLightTestControl.CopySettings () inline
Copies indicator light's properties (without the state) to the state of this testing control.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.IndicatorLightTestControl.chkHasBusy, IG.Forms.IndicatorLightTestControl.chkHasError, IG.Forms.IndicatorLightTestControl.chkHasOff, IG.Forms.IndicatorLightTestControl.chkHasOk, IG.Forms.IndicatorLightTestControl.chkLabelBorder, IG.Forms.IndicatorLightTestControl.chkOuterBorder, IG.Forms.IndicatorLightTestControl.chkThrowOnInvalid, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.LabelText, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.IndicatorLightTestControl.numBlinkTime, IG.Forms.IndicatorLightTestControl.numLabelMargin, IG.Forms.IndicatorLightTestControl.numLabelPadding, IG.Forms.IndicatorLightTestControl.numOuterMargin, IG.Forms.IndicatorLightTestControl.numOuterPadding, IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, and IG.Forms.IndicatorLightTestControl.txtLabelText.
chkOff_CheckedChanged() [3/3]
void IG.Forms.IndicatorLightTestControl.chkOff_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkOff, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.UtilForms.Reporter, IG.Forms.IndicatorLight.SetOff(), and IG.Forms.IndicatorLight.UnsetOff().
chkOk_CheckedChanged() [3/3]
void IG.Forms.IndicatorLightTestControl.chkOk_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkOk, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.UtilForms.Reporter, IG.Forms.IndicatorLight.SetOk(), and IG.Forms.IndicatorLight.UnsetOk().
chkBusy_CheckedChanged() [3/3]
void IG.Forms.IndicatorLightTestControl.chkBusy_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkBusy, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.UtilForms.Reporter, IG.Forms.IndicatorLight.SetBusy(), and IG.Forms.IndicatorLight.UnsetBusy().
chkError_CheckedChanged() [3/3]
void IG.Forms.IndicatorLightTestControl.chkError_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkError, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.UtilForms.Reporter, IG.Forms.IndicatorLight.SetError(), and IG.Forms.IndicatorLight.UnsetError().
btnBlinkOnce_Click() [3/3]
void IG.Forms.IndicatorLightTestControl.btnBlinkOnce_Click (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.Blink(), and IG.Forms.IndicatorLightTestControl.Indicator.
btnBlinkTwice_Click() [3/3]
void IG.Forms.IndicatorLightTestControl.btnBlinkTwice_Click (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.Blink(), and IG.Forms.IndicatorLightTestControl.Indicator.
chkBlinking_CheckedChanged() [3/3]
void IG.Forms.IndicatorLightTestControl.chkBlinking_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkBlinking, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, and IG.Forms.IndicatorLight.IsBlinking.
chkThrowOnInvalid_CheckedChanged() [3/3]
void IG.Forms.IndicatorLightTestControl.chkThrowOnInvalid_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkThrowOnInvalid, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, and IG.Forms.IndicatorLight.ThrowOnInvalidSwitch.
chkOuterBorder_CheckedChanged() [3/3]
void IG.Forms.IndicatorLightTestControl.chkOuterBorder_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.BorderOut, IG.Forms.IndicatorLightTestControl.chkOuterBorder, IG.Forms.IndicatorLightTestControl.CopyAll(), and IG.Forms.IndicatorLightTestControl.Indicator.
chkLabelBorder_CheckedChanged() [3/3]
void IG.Forms.IndicatorLightTestControl.chkLabelBorder_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLightTestControl.chkLabelBorder, IG.Forms.IndicatorLightTestControl.CopyAll(), and IG.Forms.IndicatorLightTestControl.Indicator.
chkHasOff_CheckedChanged() [3/3]
void IG.Forms.IndicatorLightTestControl.chkHasOff_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkHasOff, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLight.HasOff, and IG.Forms.IndicatorLightTestControl.Indicator.
chkHasOk_CheckedChanged() [3/3]
void IG.Forms.IndicatorLightTestControl.chkHasOk_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkHasOk, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLight.HasOk, and IG.Forms.IndicatorLightTestControl.Indicator.
chkHasBusy_CheckedChanged() [3/3]
void IG.Forms.IndicatorLightTestControl.chkHasBusy_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkHasBusy, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLight.HasBusy, and IG.Forms.IndicatorLightTestControl.Indicator.
chkHasError_CheckedChanged() [3/3]
void IG.Forms.IndicatorLightTestControl.chkHasError_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.chkHasError, IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLight.HasError, and IG.Forms.IndicatorLightTestControl.Indicator.
txtLabelText_Validated() [3/3]
void IG.Forms.IndicatorLightTestControl.txtLabelText_Validated (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.LabelText, and IG.Forms.IndicatorLightTestControl.txtLabelText.
txtLabelText_TextChanged() [3/3]
void IG.Forms.IndicatorLightTestControl.txtLabelText_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.LabelText, and IG.Forms.IndicatorLightTestControl.txtLabelText.
btnLabelColor_Click() [3/3]
void IG.Forms.IndicatorLightTestControl.btnLabelColor_Click (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.colorDialog1, IG.Forms.IndicatorLight.ColorLabel, IG.Forms.IndicatorLightTestControl.CopyAll(), and IG.Forms.IndicatorLightTestControl.Indicator.
numOuterMargin_ValueChanged() [3/3]
void IG.Forms.IndicatorLightTestControl.numOuterMargin_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.MarginOut, and IG.Forms.IndicatorLightTestControl.numOuterMargin.
numOuterPadding_ValueChanged() [3/3]
void IG.Forms.IndicatorLightTestControl.numOuterPadding_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLightTestControl.numOuterPadding, and IG.Forms.IndicatorLight.PaddingOut.
numLabelMargin_ValueChanged() [3/3]
void IG.Forms.IndicatorLightTestControl.numLabelMargin_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.MarginLabel, and IG.Forms.IndicatorLightTestControl.numLabelMargin.
numLabelPadding_ValueChanged() [3/3]
void IG.Forms.IndicatorLightTestControl.numLabelPadding_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.CopyAll(), IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLightTestControl.numLabelPadding, and IG.Forms.IndicatorLight.PaddingLabel.
numBlinkTime_ValueChanged() [3/3]
void IG.Forms.IndicatorLightTestControl.numBlinkTime_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLightTestControl.Indicator, and IG.Forms.IndicatorLightTestControl.numBlinkTime.
fontSelectorSimple1_FontSelected() [3/3]
void IG.Forms.IndicatorLightTestControl.fontSelectorSimple1_FontSelected (object sender, FontEventArgs args) inline private
References IG.Forms.IndicatorLightTestControl.fontSelectorSimple1, IG.Forms.IndicatorLightTestControl.Indicator, IG.Forms.IndicatorLight.LabelFont, and IG.Forms.FontSelectorSimple.SelectedFont.
btnBlinkYellow3_Click() [3/3]
void IG.Forms.IndicatorLightTestControl.btnBlinkYellow3_Click (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.BlinkSpecial(), and IG.Forms.IndicatorLightTestControl.Indicator.
btnBlinkError2x_Click() [3/3]
void IG.Forms.IndicatorLightTestControl.btnBlinkError2x_Click (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLight.BlinkError(), and IG.Forms.IndicatorLightTestControl.Indicator.
comboDirection_SelectedIndexChanged() [3/3]
void IG.Forms.IndicatorLightTestControl.comboDirection_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.comboDirection, IG.Forms.IndicatorLight.FlowDirection, and IG.Forms.IndicatorLightTestControl.Indicator.
comboDirection_Click() [3/3]
void IG.Forms.IndicatorLightTestControl.comboDirection_Click (object sender, EventArgs e) inline private
References IG.Forms.IndicatorLightTestControl.comboDirection.
Dispose() [3/3]
override void IG.Forms.IndicatorLightTestControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.IndicatorLightTestControl.components.
InitializeComponent() [3/3]
void IG.Forms.IndicatorLightTestControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.IndicatorLightTestControl.btnBlinkError2x, IG.Forms.IndicatorLightTestControl.btnBlinkError2x_Click(), IG.Forms.IndicatorLightTestControl.btnBlinkOnce, IG.Forms.IndicatorLightTestControl.btnBlinkOnce_Click(), IG.Forms.IndicatorLightTestControl.btnBlinkTwice, IG.Forms.IndicatorLightTestControl.btnBlinkTwice_Click(), IG.Forms.IndicatorLightTestControl.btnBlinkYellow3, IG.Forms.IndicatorLightTestControl.btnBlinkYellow3_Click(), IG.Forms.IndicatorLightTestControl.btnLabelColor, IG.Forms.IndicatorLightTestControl.btnLabelColor_Click(), IG.Forms.IndicatorLightTestControl.chkBlinking, IG.Forms.IndicatorLightTestControl.chkBlinking_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkBusy, IG.Forms.IndicatorLightTestControl.chkBusy_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkError, IG.Forms.IndicatorLightTestControl.chkError_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkHasBusy, IG.Forms.IndicatorLightTestControl.chkHasBusy_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkHasError, IG.Forms.IndicatorLightTestControl.chkHasError_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkHasOff, IG.Forms.IndicatorLightTestControl.chkHasOff_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkHasOk, IG.Forms.IndicatorLightTestControl.chkHasOk_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkLabelBorder, IG.Forms.IndicatorLightTestControl.chkLabelBorder_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkOff, IG.Forms.IndicatorLightTestControl.chkOff_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkOk, IG.Forms.IndicatorLightTestControl.chkOk_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkOuterBorder, IG.Forms.IndicatorLightTestControl.chkOuterBorder_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkThrowOnInvalid, IG.Forms.IndicatorLightTestControl.chkThrowOnInvalid_CheckedChanged(), IG.Forms.IndicatorLightTestControl.colorDialog1, IG.Forms.IndicatorLight.ColorLabel, IG.Forms.IndicatorLightTestControl.comboDirection, IG.Forms.IndicatorLightTestControl.comboDirection_Click(), IG.Forms.IndicatorLightTestControl.comboDirection_SelectedIndexChanged(), IG.Forms.IndicatorLight.FlowDirection, IG.Forms.FontSelectorSimple.FontSelected, IG.Forms.IndicatorLightTestControl.fontSelectorSimple1, IG.Forms.IndicatorLightTestControl.fontSelectorSimple1_FontSelected(), IG.Forms.IndicatorLightTestControl.grpProperties, IG.Forms.IndicatorLightTestControl.grpState, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.IndicatorLightTestControl.indicatorLight1, IG.Forms.FontSelectorSimple.InitialFontLabelText, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLightTestControl.label1, IG.Forms.IndicatorLight.LabelFont, IG.Forms.IndicatorLight.LabelText, IG.Forms.IndicatorLightTestControl.lblBlinkTime, IG.Forms.IndicatorLightTestControl.lblFlowDirection, IG.Forms.IndicatorLightTestControl.lblFont, IG.Forms.IndicatorLightTestControl.lblLabelFont, IG.Forms.IndicatorLightTestControl.lblLabelMargin, IG.Forms.IndicatorLightTestControl.lblOuterMargin, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.IndicatorLightTestControl.numBlinkTime, IG.Forms.IndicatorLightTestControl.numBlinkTime_ValueChanged(), IG.Forms.IndicatorLightTestControl.numLabelMargin, IG.Forms.IndicatorLightTestControl.numLabelMargin_ValueChanged(), IG.Forms.IndicatorLightTestControl.numLabelPadding, IG.Forms.IndicatorLightTestControl.numLabelPadding_ValueChanged(), IG.Forms.IndicatorLightTestControl.numOuterMargin, IG.Forms.IndicatorLightTestControl.numOuterMargin_ValueChanged(), IG.Forms.IndicatorLightTestControl.numOuterPadding, IG.Forms.IndicatorLightTestControl.numOuterPadding_ValueChanged(), IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.IndicatorLightTestControl.pnlIndicatorContainerInner, IG.Forms.IndicatorLightTestControl.pnlIndicatorContainerOuter, IG.Forms.FontSelectorSimple.SelectedFont, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, IG.Forms.IndicatorLightTestControl.txtLabelText, IG.Forms.IndicatorLightTestControl.txtLabelText_TextChanged(), and IG.Forms.IndicatorLightTestControl.txtLabelText_Validated().
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.IndicatorLightTestControl.components = null private
Required designer variable.
Referenced by IG.Forms.IndicatorLightTestControl.Dispose().
indicatorLight1
IG Forms IndicatorLight IG.Forms.IndicatorLightTestControl.indicatorLight1 private
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkThrowOnInvalid
System Windows Forms CheckBox IG.Forms.IndicatorLightTestControl.chkThrowOnInvalid private
Referenced by IG.Forms.IndicatorLightTestControl.chkThrowOnInvalid_CheckedChanged(), IG.Forms.IndicatorLightTestControl.CopySettings(), and IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkOuterBorder
System Windows Forms CheckBox IG.Forms.IndicatorLightTestControl.chkOuterBorder private
Referenced by IG.Forms.IndicatorLightTestControl.chkOuterBorder_CheckedChanged(), IG.Forms.IndicatorLightTestControl.CopySettings(), and IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkLabelBorder
System Windows Forms CheckBox IG.Forms.IndicatorLightTestControl.chkLabelBorder private
Referenced by IG.Forms.IndicatorLightTestControl.chkLabelBorder_CheckedChanged(), IG.Forms.IndicatorLightTestControl.CopySettings(), and IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkHasOff
System Windows Forms CheckBox IG.Forms.IndicatorLightTestControl.chkHasOff private
Referenced by IG.Forms.IndicatorLightTestControl.chkHasOff_CheckedChanged(), IG.Forms.IndicatorLightTestControl.CopySettings(), and IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkHasOk
System Windows Forms CheckBox IG.Forms.IndicatorLightTestControl.chkHasOk private
Referenced by IG.Forms.IndicatorLightTestControl.chkHasOk_CheckedChanged(), IG.Forms.IndicatorLightTestControl.CopySettings(), and IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkHasBusy
System Windows Forms CheckBox IG.Forms.IndicatorLightTestControl.chkHasBusy private
Referenced by IG.Forms.IndicatorLightTestControl.chkHasBusy_CheckedChanged(), IG.Forms.IndicatorLightTestControl.CopySettings(), and IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkHasError
System Windows Forms CheckBox IG.Forms.IndicatorLightTestControl.chkHasError private
Referenced by IG.Forms.IndicatorLightTestControl.chkHasError_CheckedChanged(), IG.Forms.IndicatorLightTestControl.CopySettings(), and IG.Forms.IndicatorLightTestControl.InitializeComponent().
grpProperties
System Windows Forms GroupBox IG.Forms.IndicatorLightTestControl.grpProperties private
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
txtLabelText
System Windows Forms TextBox IG.Forms.IndicatorLightTestControl.txtLabelText private
Referenced by IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), IG.Forms.IndicatorLightTestControl.txtLabelText_TextChanged(), and IG.Forms.IndicatorLightTestControl.txtLabelText_Validated().
numOuterPadding
System Windows Forms NumericUpDown IG.Forms.IndicatorLightTestControl.numOuterPadding private
Referenced by IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), and IG.Forms.IndicatorLightTestControl.numOuterPadding_ValueChanged().
numOuterMargin
System Windows Forms NumericUpDown IG.Forms.IndicatorLightTestControl.numOuterMargin private
Referenced by IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), and IG.Forms.IndicatorLightTestControl.numOuterMargin_ValueChanged().
lblLabelMargin
System Windows Forms Label IG.Forms.IndicatorLightTestControl.lblLabelMargin private
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
lblOuterMargin
System Windows Forms Label IG.Forms.IndicatorLightTestControl.lblOuterMargin private
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
numLabelPadding
System Windows Forms NumericUpDown IG.Forms.IndicatorLightTestControl.numLabelPadding private
Referenced by IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), and IG.Forms.IndicatorLightTestControl.numLabelPadding_ValueChanged().
numLabelMargin
System Windows Forms NumericUpDown IG.Forms.IndicatorLightTestControl.numLabelMargin private
Referenced by IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), and IG.Forms.IndicatorLightTestControl.numLabelMargin_ValueChanged().
btnLabelColor
System Windows Forms Button IG.Forms.IndicatorLightTestControl.btnLabelColor private
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
grpState
System Windows Forms GroupBox IG.Forms.IndicatorLightTestControl.grpState private
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkOff
System Windows Forms CheckBox IG.Forms.IndicatorLightTestControl.chkOff private
Referenced by IG.Forms.IndicatorLightTestControl.chkOff_CheckedChanged(), IG.Forms.IndicatorLightTestControl.CopyState(), and IG.Forms.IndicatorLightTestControl.InitializeComponent().
colorDialog1
System Windows Forms ColorDialog IG.Forms.IndicatorLightTestControl.colorDialog1 private
Referenced by IG.Forms.IndicatorLightTestControl.btnLabelColor_Click(), and IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkBlinking
System Windows Forms CheckBox IG.Forms.IndicatorLightTestControl.chkBlinking private
Referenced by IG.Forms.IndicatorLightTestControl.chkBlinking_CheckedChanged(), IG.Forms.IndicatorLightTestControl.CopyState(), and IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkError
System Windows Forms CheckBox IG.Forms.IndicatorLightTestControl.chkError private
Referenced by IG.Forms.IndicatorLightTestControl.chkError_CheckedChanged(), IG.Forms.IndicatorLightTestControl.CopyState(), and IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkBusy
System Windows Forms CheckBox IG.Forms.IndicatorLightTestControl.chkBusy private
Referenced by IG.Forms.IndicatorLightTestControl.chkBusy_CheckedChanged(), IG.Forms.IndicatorLightTestControl.CopyState(), and IG.Forms.IndicatorLightTestControl.InitializeComponent().
chkOk
System Windows Forms CheckBox IG.Forms.IndicatorLightTestControl.chkOk private
Referenced by IG.Forms.IndicatorLightTestControl.chkOk_CheckedChanged(), IG.Forms.IndicatorLightTestControl.CopyState(), and IG.Forms.IndicatorLightTestControl.InitializeComponent().
btnBlinkTwice
System Windows Forms Button IG.Forms.IndicatorLightTestControl.btnBlinkTwice private
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
btnBlinkOnce
System Windows Forms Button IG.Forms.IndicatorLightTestControl.btnBlinkOnce private
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
lblBlinkTime
System Windows Forms Label IG.Forms.IndicatorLightTestControl.lblBlinkTime private
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
numBlinkTime
System Windows Forms NumericUpDown IG.Forms.IndicatorLightTestControl.numBlinkTime private
Referenced by IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), and IG.Forms.IndicatorLightTestControl.numBlinkTime_ValueChanged().
label1
System Windows Forms Label IG.Forms.IndicatorLightTestControl.label1 private
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
lblFont
System Windows Forms Label IG.Forms.IndicatorLightTestControl.lblFont private
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
fontSelectorSimple1
FontSelectorSimple IG.Forms.IndicatorLightTestControl.fontSelectorSimple1 private
Referenced by IG.Forms.IndicatorLightTestControl.fontSelectorSimple1_FontSelected(), and IG.Forms.IndicatorLightTestControl.InitializeComponent().
lblLabelFont
System Windows Forms Label IG.Forms.IndicatorLightTestControl.lblLabelFont private
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
btnBlinkYellow3
System Windows Forms Button IG.Forms.IndicatorLightTestControl.btnBlinkYellow3 private
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
btnBlinkError2x
System Windows Forms Button IG.Forms.IndicatorLightTestControl.btnBlinkError2x private
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
comboDirection
System Windows Forms ComboBox IG.Forms.IndicatorLightTestControl.comboDirection private
Referenced by IG.Forms.IndicatorLightTestControl.comboDirection_Click(), IG.Forms.IndicatorLightTestControl.comboDirection_SelectedIndexChanged(), IG.Forms.IndicatorLightTestControl.IndicatorLightTestControl(), and IG.Forms.IndicatorLightTestControl.InitializeComponent().
lblFlowDirection
System Windows Forms Label IG.Forms.IndicatorLightTestControl.lblFlowDirection private
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
pnlIndicatorContainerInner
System Windows Forms Panel IG.Forms.IndicatorLightTestControl.pnlIndicatorContainerInner private
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
pnlIndicatorContainerOuter
System Windows Forms Panel IG.Forms.IndicatorLightTestControl.pnlIndicatorContainerOuter private
Referenced by IG.Forms.IndicatorLightTestControl.InitializeComponent().
Property Documentation
Indicator
IndicatorLight IG.Forms.IndicatorLightTestControl.Indicator get protected
Referenced by IG.Forms.IndicatorLightTestControl.btnBlinkError2x_Click(), IG.Forms.IndicatorLightTestControl.btnBlinkOnce_Click(), IG.Forms.IndicatorLightTestControl.btnBlinkTwice_Click(), IG.Forms.IndicatorLightTestControl.btnBlinkYellow3_Click(), IG.Forms.IndicatorLightTestControl.btnLabelColor_Click(), IG.Forms.IndicatorLightTestControl.chkBlinking_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkBusy_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkError_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkHasBusy_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkHasError_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkHasOff_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkHasOk_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkLabelBorder_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkOff_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkOk_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkOuterBorder_CheckedChanged(), IG.Forms.IndicatorLightTestControl.chkThrowOnInvalid_CheckedChanged(), IG.Forms.IndicatorLightTestControl.comboDirection_SelectedIndexChanged(), IG.Forms.IndicatorLightTestControl.CopySettings(), IG.Forms.IndicatorLightTestControl.CopyState(), IG.Forms.IndicatorLightTestControl.fontSelectorSimple1_FontSelected(), IG.Forms.IndicatorLightTestControl.numBlinkTime_ValueChanged(), IG.Forms.IndicatorLightTestControl.numLabelMargin_ValueChanged(), IG.Forms.IndicatorLightTestControl.numLabelPadding_ValueChanged(), IG.Forms.IndicatorLightTestControl.numOuterMargin_ValueChanged(), IG.Forms.IndicatorLightTestControl.numOuterPadding_ValueChanged(), IG.Forms.IndicatorLightTestControl.txtLabelText_TextChanged(), and IG.Forms.IndicatorLightTestControl.txtLabelText_Validated().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/BasicControls/IndicatorLightTestControl.cs
iglib/igforms/Utilities/BasicControls/IndicatorLightTestControl.Designer.cs