Doc: IGLib EXTENDED: IG.Forms.NeuralOutputValueSelector Class Reference
IG.Forms.NeuralOutputValueSelector Class Reference
Selection of the output value of interest in an ANN model.
Public Member Functions
NeuralOutputValueSelector ()
void SetSelectedOutputId (int id)
Replacement for the SelectedOutputId setter that has a lower access level.
void UpdateSelectedParameterIdDependencies ()
Updates things that depend on the selected parameter's index.
void InitializeData ()
Initialiyes data after neural model has been set or changed.
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
int _selectedOutputId = 0
Properties
InputOutputDataDefiniton NeuralDataDefinition [get, set]
Data about input and output quantities of the manipulated functions or response.
int NumInputParameters [get]
Gets number of input parameters.
int NumOutputValues [get]
Gets number of output values.
int SelectedOutputId [get, protected set]
Sequential number of the selected parameter as specified by the user.
Events
SelectedIdEventHandler SelectedOutputIdChanged
Occurs when selected output value ID is changed.
Private Member Functions
void comboBoxSelection_SelectedIndexChanged (object sender, EventArgs e)
void txtParamNum_ValueChanged (object sender, EventArgs e)
void btnDecrease_Click (object sender, EventArgs e)
void btnIncrease_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
InputOutputDataDefiniton _neuralDataDefinition
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Label lblParamNum
System.Windows.Forms.Label lblSelectParameter
System.Windows.Forms.NumericUpDown txtValueNum
System.Windows.Forms.ComboBox comboBoxSelection
System.Windows.Forms.Button btnDecrease
System.Windows.Forms.Button btnIncrease
System.Windows.Forms.Panel pnlMain
Detailed Description
Selection of the output value of interest in an ANN model.
$A Igor Apr13;
Constructor & Destructor Documentation
NeuralOutputValueSelector()
IG.Forms.NeuralOutputValueSelector.NeuralOutputValueSelector () inline
References IG.Forms.NeuralOutputValueSelector.InitializeComponent().
Member Function Documentation
SetSelectedOutputId()
void IG.Forms.NeuralOutputValueSelector.SetSelectedOutputId (int id) inline
Replacement for the SelectedOutputId setter that has a lower access level.
Parameters
id Sequential number of the output valuee to be selected.
References IG.Forms.NeuralOutputValueSelector.SelectedOutputId.
UpdateSelectedParameterIdDependencies()
void IG.Forms.NeuralOutputValueSelector.UpdateSelectedParameterIdDependencies () inline
Updates things that depend on the selected parameter's index.
References IG.Forms.NeuralOutputValueSelector.comboBoxSelection, IG.Forms.NeuralOutputValueSelector.SelectedOutputId, and IG.Forms.NeuralOutputValueSelector.txtValueNum.
Referenced by IG.Forms.NeuralOutputValueSelector.InitializeData().
InitializeData()
void IG.Forms.NeuralOutputValueSelector.InitializeData () inline
Initialiyes data after neural model has been set or changed.
References IG.Forms.NeuralOutputValueSelector.comboBoxSelection, IG.Num.InputOutputElementDefinition.Name, IG.Forms.NeuralOutputValueSelector.NeuralDataDefinition, IG.Forms.NeuralOutputValueSelector.NumOutputValues, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Num.InputOutputDataDefiniton.OutputLength, IG.Forms.NeuralOutputValueSelector.SelectedOutputId, IG.Num.InputOutputElementDefinition.Title, IG.Forms.NeuralOutputValueSelector.txtValueNum, and IG.Forms.NeuralOutputValueSelector.UpdateSelectedParameterIdDependencies().
comboBoxSelection_SelectedIndexChanged()
void IG.Forms.NeuralOutputValueSelector.comboBoxSelection_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Forms.NeuralOutputValueSelector.comboBoxSelection, and IG.Forms.NeuralOutputValueSelector.SelectedOutputId.
Referenced by IG.Forms.NeuralOutputValueSelector.InitializeComponent().
txtParamNum_ValueChanged()
void IG.Forms.NeuralOutputValueSelector.txtParamNum_ValueChanged (object sender, EventArgs e) inline private
References IG.Forms.NeuralOutputValueSelector.SelectedOutputId, and IG.Forms.NeuralOutputValueSelector.txtValueNum.
Referenced by IG.Forms.NeuralOutputValueSelector.InitializeComponent().
btnDecrease_Click()
void IG.Forms.NeuralOutputValueSelector.btnDecrease_Click (object sender, EventArgs e) inline private
References IG.Forms.NeuralOutputValueSelector.SelectedOutputId.
Referenced by IG.Forms.NeuralOutputValueSelector.InitializeComponent().
btnIncrease_Click()
void IG.Forms.NeuralOutputValueSelector.btnIncrease_Click (object sender, EventArgs e) inline private
References IG.Forms.NeuralOutputValueSelector.SelectedOutputId.
Referenced by IG.Forms.NeuralOutputValueSelector.InitializeComponent().
Dispose()
override void IG.Forms.NeuralOutputValueSelector.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.NeuralOutputValueSelector.components.
InitializeComponent()
void IG.Forms.NeuralOutputValueSelector.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.NeuralOutputValueSelector.btnDecrease, IG.Forms.NeuralOutputValueSelector.btnDecrease_Click(), IG.Forms.NeuralOutputValueSelector.btnIncrease, IG.Forms.NeuralOutputValueSelector.btnIncrease_Click(), IG.Forms.NeuralOutputValueSelector.comboBoxSelection, IG.Forms.NeuralOutputValueSelector.comboBoxSelection_SelectedIndexChanged(), IG.Forms.NeuralOutputValueSelector.lblParamNum, IG.Forms.NeuralOutputValueSelector.lblSelectParameter, IG.Forms.NeuralOutputValueSelector.pnlMain, IG.Forms.NeuralOutputValueSelector.txtParamNum_ValueChanged(), and IG.Forms.NeuralOutputValueSelector.txtValueNum.
Referenced by IG.Forms.NeuralOutputValueSelector.NeuralOutputValueSelector().
Member Data Documentation
_neuralDataDefinition
InputOutputDataDefiniton IG.Forms.NeuralOutputValueSelector._neuralDataDefinition private
_selectedOutputId
int IG.Forms.NeuralOutputValueSelector._selectedOutputId = 0 protected
components
System.ComponentModel.IContainer IG.Forms.NeuralOutputValueSelector.components = null private
Required designer variable.
Referenced by IG.Forms.NeuralOutputValueSelector.Dispose().
lblParamNum
System.Windows.Forms.Label IG.Forms.NeuralOutputValueSelector.lblParamNum private
Referenced by IG.Forms.NeuralOutputValueSelector.InitializeComponent().
lblSelectParameter
System.Windows.Forms.Label IG.Forms.NeuralOutputValueSelector.lblSelectParameter private
Referenced by IG.Forms.NeuralOutputValueSelector.InitializeComponent().
txtValueNum
System.Windows.Forms.NumericUpDown IG.Forms.NeuralOutputValueSelector.txtValueNum private
Referenced by IG.Forms.NeuralOutputValueSelector.InitializeComponent(), IG.Forms.NeuralOutputValueSelector.InitializeData(), IG.Forms.NeuralOutputValueSelector.txtParamNum_ValueChanged(), and IG.Forms.NeuralOutputValueSelector.UpdateSelectedParameterIdDependencies().
comboBoxSelection
System.Windows.Forms.ComboBox IG.Forms.NeuralOutputValueSelector.comboBoxSelection private
Referenced by IG.Forms.NeuralOutputValueSelector.comboBoxSelection_SelectedIndexChanged(), IG.Forms.NeuralOutputValueSelector.InitializeComponent(), IG.Forms.NeuralOutputValueSelector.InitializeData(), and IG.Forms.NeuralOutputValueSelector.UpdateSelectedParameterIdDependencies().
btnDecrease
System.Windows.Forms.Button IG.Forms.NeuralOutputValueSelector.btnDecrease private
Referenced by IG.Forms.NeuralOutputValueSelector.InitializeComponent().
btnIncrease
System.Windows.Forms.Button IG.Forms.NeuralOutputValueSelector.btnIncrease private
Referenced by IG.Forms.NeuralOutputValueSelector.InitializeComponent().
pnlMain
System.Windows.Forms.Panel IG.Forms.NeuralOutputValueSelector.pnlMain private
Referenced by IG.Forms.NeuralOutputValueSelector.InitializeComponent().
Property Documentation
NeuralDataDefinition
InputOutputDataDefiniton IG.Forms.NeuralOutputValueSelector.NeuralDataDefinition get set
Data about input and output quantities of the manipulated functions or response.
Referenced by IG.Forms.NeuralOutputValueSelector.InitializeData().
NumInputParameters
int IG.Forms.NeuralOutputValueSelector.NumInputParameters get
Gets number of input parameters.
NumOutputValues
int IG.Forms.NeuralOutputValueSelector.NumOutputValues get
Gets number of output values.
Referenced by IG.Forms.NeuralOutputValueSelector.InitializeData().
SelectedOutputId
int IG.Forms.NeuralOutputValueSelector.SelectedOutputId get protected set
Sequential number of the selected parameter as specified by the user.
Referenced by IG.Forms.NeuralOutputValueSelector.btnDecrease_Click(), IG.Forms.NeuralOutputValueSelector.btnIncrease_Click(), IG.Forms.NeuralOutputValueSelector.comboBoxSelection_SelectedIndexChanged(), IG.Forms.NeuralOutputValueSelector.InitializeData(), IG.Forms.NeuralOutputValueSelector.SetSelectedOutputId(), IG.Forms.NeuralOutputValueSelector.txtParamNum_ValueChanged(), and IG.Forms.NeuralOutputValueSelector.UpdateSelectedParameterIdDependencies().
Event Documentation
SelectedOutputIdChanged
SelectedIdEventHandler IG.Forms.NeuralOutputValueSelector.SelectedOutputIdChanged
Occurs when selected output value ID is changed.
The documentation for this class was generated from the following files:
unittests/Guest_IGTestCopy/Copy_Forms/11/Numeric/FromNeural/Basic/ParametricOutputValueSelector.cs
unittests/Guest_IGTestCopy/Copy_Forms/11/Numeric/FromNeural/Basic/ParametricOutputValueSelector.Designer.cs