Doc: IGLib EXTENDED: IG.Forms.XMLTestPathForm Class Reference
IG.Forms.XMLTestPathForm Class Reference
Public Member Functions
delegate void MyDelegate ()
XMLTestPathForm (string Path)
XMLTestPathForm ()
Public Attributes
MyDelegate CloseDelegate = null
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void XMLTestPathBas (string Path)
void XMLTestPath_Load (object sender, EventArgs e)
void btnClose_Click (object sender, EventArgs e)
close the consform, not the application
void XMLTestPath_Closing (object sender, FormClosingEventArgs e)
Private Attributes
GroupBox groupBoxButtons
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.GroupBox gbxExpression
System.Windows.Forms.Button btnTest
System.Windows.Forms.GroupBox gbxResults
System.Windows.Forms.RichTextBox rtbResults
System.Windows.Forms.Button btnClose
System.Windows.Forms.RadioButton optOuterXml
System.Windows.Forms.RadioButton optInnerXml
System.Windows.Forms.RadioButton optValueOnly
System.ComponentModel.ComponentResourceManager res = new System.ComponentModel.ComponentResourceManager(typeof(XMLTestPathForm))
Constructor & Destructor Documentation
XMLTestPathForm() [1/2]
IG.Forms.XMLTestPathForm.XMLTestPathForm (string Path) inline
References IG.Forms.XMLTestPathForm.XMLTestPathBas().
XMLTestPathForm() [2/2]
IG.Forms.XMLTestPathForm.XMLTestPathForm () inline
References IG.Forms.XMLTestPathForm.XMLTestPathBas().
Member Function Documentation
MyDelegate()
delegate void IG.Forms.XMLTestPathForm.MyDelegate ()
Referenced by IG.Forms.XmlTreeViewControl.MenuTools_TestXPath_Click(), and IG.Forms.XMLTreeViewFormOld_Keep_Some_time.MenuTools_TestXPath_Click().
Dispose()
override void IG.Forms.XMLTestPathForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.XMLTestPathForm.components.
Referenced by IG.Forms.XMLTestPathForm.btnClose_Click().
InitializeComponent()
void IG.Forms.XMLTestPathForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.XMLTestPathForm.btnClose, IG.Forms.XMLTestPathForm.btnClose_Click(), IG.Forms.XMLTestPathForm.btnTest, IG.Forms.XMLTestPathForm.gbxExpression, IG.Forms.XMLTestPathForm.gbxResults, IG.Forms.XMLTestPathForm.optInnerXml, IG.Forms.XMLTestPathForm.optOuterXml, IG.Forms.XMLTestPathForm.optValueOnly, IG.Forms.XMLTestPathForm.rtbResults, IG.Forms.XMLTestPathForm.XMLTestPath_Closing(), and IG.Forms.XMLTestPathForm.XMLTestPath_Load().
Referenced by IG.Forms.XMLTestPathForm.XMLTestPathBas().
XMLTestPathBas()
void IG.Forms.XMLTestPathForm.XMLTestPathBas (string Path) inline private
References IG.Forms.XMLTestPathForm.InitializeComponent().
Referenced by IG.Forms.XMLTestPathForm.XMLTestPathForm().
XMLTestPath_Load()
void IG.Forms.XMLTestPathForm.XMLTestPath_Load (object sender, EventArgs e) inline private
Referenced by IG.Forms.XMLTestPathForm.InitializeComponent().
btnClose_Click()
void IG.Forms.XMLTestPathForm.btnClose_Click (object sender, EventArgs e) inline private
close the consform, not the application
Parameters
sender
e
References IG.Forms.XMLTestPathForm.Dispose().
Referenced by IG.Forms.XMLTestPathForm.InitializeComponent().
XMLTestPath_Closing()
void IG.Forms.XMLTestPathForm.XMLTestPath_Closing (object sender, FormClosingEventArgs e) inline private
References IG.Forms.XMLTestPathForm.CloseDelegate.
Referenced by IG.Forms.XMLTestPathForm.InitializeComponent().
Member Data Documentation
CloseDelegate
MyDelegate IG.Forms.XMLTestPathForm.CloseDelegate = null
Referenced by IG.Forms.XmlTreeViewControl.MenuTools_TestXPath_Click(), IG.Forms.XMLTreeViewFormOld_Keep_Some_time.MenuTools_TestXPath_Click(), and IG.Forms.XMLTestPathForm.XMLTestPath_Closing().
groupBoxButtons
GroupBox IG.Forms.XMLTestPathForm.groupBoxButtons private
components
System.ComponentModel.IContainer IG.Forms.XMLTestPathForm.components = null private
Required designer variable.
Referenced by IG.Forms.XMLTestPathForm.Dispose().
gbxExpression
System.Windows.Forms.GroupBox IG.Forms.XMLTestPathForm.gbxExpression private
Referenced by IG.Forms.XMLTestPathForm.InitializeComponent().
btnTest
System.Windows.Forms.Button IG.Forms.XMLTestPathForm.btnTest private
Referenced by IG.Forms.XMLTestPathForm.InitializeComponent().
gbxResults
System.Windows.Forms.GroupBox IG.Forms.XMLTestPathForm.gbxResults private
Referenced by IG.Forms.XMLTestPathForm.InitializeComponent().
rtbResults
System.Windows.Forms.RichTextBox IG.Forms.XMLTestPathForm.rtbResults private
Referenced by IG.Forms.XMLTestPathForm.InitializeComponent().
btnClose
System.Windows.Forms.Button IG.Forms.XMLTestPathForm.btnClose private
Referenced by IG.Forms.XMLTestPathForm.InitializeComponent().
optOuterXml
System.Windows.Forms.RadioButton IG.Forms.XMLTestPathForm.optOuterXml private
Referenced by IG.Forms.XMLTestPathForm.InitializeComponent().
optInnerXml
System.Windows.Forms.RadioButton IG.Forms.XMLTestPathForm.optInnerXml private
Referenced by IG.Forms.XMLTestPathForm.InitializeComponent().
optValueOnly
System.Windows.Forms.RadioButton IG.Forms.XMLTestPathForm.optValueOnly private
Referenced by IG.Forms.XMLTestPathForm.InitializeComponent().
res
System.ComponentModel.ComponentResourceManager IG.Forms.XMLTestPathForm.res = new System.ComponentModel.ComponentResourceManager(typeof(XMLTestPathForm)) private
The documentation for this class was generated from the following file:
iglib/igforms/Basic/XMLTestPathForm.cs