Doc: IGLib EXTENDED: NeuronDotNet.Core.Helper Class Reference
NeuronDotNet.Core.Helper Class Reference
This static class contains all helper functions used in this project.
Static Public Member Functions
static void ValidateNotNull (object value, string name)
Validates that a value is not null.
static void ValidatePositive (double value, string name)
Validates that a numerical argument is positive
static int[] GetRandomOrder (int size)
Generates an array of given size containing integers from 0 to 'size - 1' in random order
Static Private Attributes
static readonly Random random = new Random()
Detailed Description
This static class contains all helper functions used in this project.
Member Function Documentation
ValidateNotNull()
static void NeuronDotNet.Core.Helper.ValidateNotNull (object value, string name) inline static
Validates that a value is not null.
Parameters
value The value to validate
name The name of the argument
Exceptions
ArgumentNullException If value is null
Referenced by NeuronDotNet.Core.LearningRateFunctions.AbstractFunction.AbstractFunction(), NeuronDotNet.Core.Backpropagation.ActivationNeuron.ActivationNeuron(), NeuronDotNet.Core.TrainingSet.Add(), NeuronDotNet.Core.Connector< ActivationLayer, ActivationLayer, BackpropagationSynapse >.Connector(), NeuronDotNet.Core.Initializers.ConstantFunction.ConstantFunction(), NeuronDotNet.Core.SOM.NeighborhoodFunctions.GaussianFunction.EvaluateNeighborhood(), NeuronDotNet.Core.SOM.NeighborhoodFunctions.MexicanHatFunction.EvaluateNeighborhood(), NeuronDotNet.Core.SOM.NeighborhoodFunctions.GaussianFunction.GaussianFunction(), NeuronDotNet.Core.Initializers.ConstantFunction.GetObjectData(), NeuronDotNet.Core.Initializers.NguyenWidrowFunction.GetObjectData(), NeuronDotNet.Core.LearningRateFunctions.AbstractFunction.GetObjectData(), NeuronDotNet.Core.Initializers.RandomFunction.GetObjectData(), NeuronDotNet.Core.SOM.NeighborhoodFunctions.GaussianFunction.GetObjectData(), NeuronDotNet.Core.SOM.NeighborhoodFunctions.MexicanHatFunction.GetObjectData(), NeuronDotNet.Core.TrainingSample.GetObjectData(), NeuronDotNet.Core.TrainingSet.GetObjectData(), NeuronDotNet.Core.Layer< ActivationNeuron >.GetObjectData(), NeuronDotNet.Core.Connector< ActivationLayer, ActivationLayer, BackpropagationSynapse >.GetObjectData(), NeuronDotNet.Core.Network.GetObjectData(), NeuronDotNet.Core.Initializers.NormalizedRandomFunction.Initialize(), NeuronDotNet.Core.Initializers.ConstantFunction.Initialize(), NeuronDotNet.Core.Initializers.NguyenWidrowFunction.Initialize(), NeuronDotNet.Core.Initializers.RandomFunction.Initialize(), NeuronDotNet.Core.SOM.KohonenLayer.KohonenLayer(), NeuronDotNet.Core.Layer< ActivationNeuron >.Layer(), NeuronDotNet.Core.Network.Learn(), IG.Neural.NeuralApproximatorNeuron.MyNeuronBackPropagation.Learn(), IG.Neural.NeuronBackPropagationLEarning.Learn(), NeuronDotNet.Core.SOM.NeighborhoodFunctions.MexicanHatFunction.MexicanHatFunction(), NeuronDotNet.Core.Network.Network(), NeuronDotNet.Core.Initializers.NguyenWidrowFunction.NguyenWidrowFunction(), NeuronDotNet.Core.SOM.PositionNeuron.PositionNeuron(), NeuronDotNet.Core.Initializers.RandomFunction.RandomFunction(), NeuronDotNet.Core.Backpropagation.ActivationLayer.SetErrors(), NeuronDotNet.Core.Layer< ActivationNeuron >.SetInput(), NeuronDotNet.Core.Layer< ActivationNeuron >.SetLearningRate(), NeuronDotNet.Core.TrainingSample.TrainingSample(), and NeuronDotNet.Core.TrainingSet.TrainingSet().
ValidatePositive()
static void NeuronDotNet.Core.Helper.ValidatePositive (double value, string name) inline static
Validates that a numerical argument is positive
Parameters
value The numerical value to validate
name The name of the argument
Exceptions
ArgumentException If value is zero or negative
Referenced by NeuronDotNet.Core.SOM.NeighborhoodFunctions.GaussianFunction.EvaluateNeighborhood(), NeuronDotNet.Core.SOM.NeighborhoodFunctions.MexicanHatFunction.EvaluateNeighborhood(), NeuronDotNet.Core.LearningRateFunctions.LinearFunction.GetLearningRate(), NeuronDotNet.Core.LearningRateFunctions.HyperbolicFunction.GetLearningRate(), NeuronDotNet.Core.LearningRateFunctions.ExponentialFunction.GetLearningRate(), NeuronDotNet.Core.SOM.KohonenLayer.KohonenLayer(), NeuronDotNet.Core.Layer< ActivationNeuron >.Layer(), NeuronDotNet.Core.Network.Learn(), IG.Neural.NeuralApproximatorNeuron.MyNeuronBackPropagation.Learn(), IG.Neural.NeuronBackPropagationLEarning.Learn(), and NeuronDotNet.Core.TrainingSet.TrainingSet().
GetRandomOrder()
static int [] NeuronDotNet.Core.Helper.GetRandomOrder (int size) inline static
Generates an array of given size containing integers from 0 to 'size - 1' in random order
Parameters
size Size of the array to generate.
Returns
The generated array.
References NeuronDotNet.Core.Helper.random.
Referenced by NeuronDotNet.Core.Network.Learn(), IG.Neural.NeuralApproximatorNeuron.MyNeuronBackPropagation.Learn(), and IG.Neural.NeuronBackPropagationLEarning.Learn().
Member Data Documentation
random
readonly Random NeuronDotNet.Core.Helper.random = new Random() static private
Referenced by NeuronDotNet.Core.Helper.GetRandomOrder().
The documentation for this class was generated from the following file:
shelldev/lib/externalextended/NeuronDotNetGPL/source/Core/Helper.cs