Doc: IGLib EXTENDED: IG.Forms.ControlViewerControl Class Reference
IG.Forms.ControlViewerControl Class Reference
Public Member Functions
ControlViewerControl ()
ControlViewerControl (Control viewedControl)
void ShowControl (Type controlType)
ControlViewerControl ()
ControlViewerControl (Control viewedControl)
void ShowControl (Type controlType)
ControlViewerControl ()
ControlViewerControl (Control viewedControl)
void ShowControl (Type controlType)
Static Public Member Functions
static Control CreateNewControl (Type controlType, bool throwIfIncorrectType)
static Control CreateNewControl (Type controlType, bool throwIfIncorrectType)
static Control CreateNewControl (Type controlType, bool throwIfIncorrectType)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
bool ShowDummyContents [get, set]
Whether the dummy contents of the contaier that holds the viewed control is shown.
Control DisplayedControl [get, set]
Gets or sets the control that is displayed by the current control.
Private Member Functions
void btnCloseControls_Click (object sender, EventArgs e)
void btnZoomOut_Click (object sender, EventArgs e)
void btnZoomIn_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void btnCloseControls_Click (object sender, EventArgs e)
void btnZoomOut_Click (object sender, EventArgs e)
void btnZoomIn_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void btnCloseControls_Click (object sender, EventArgs e)
void btnZoomOut_Click (object sender, EventArgs e)
void btnZoomIn_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
bool _showDummyContents = true
Control _displayedControl = null
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.FlowLayoutPanel flowLayoutPanel1
System.Windows.Forms.FlowLayoutPanel pnlControlContainer
System.Windows.Forms.Button btnControlPosition
System.Windows.Forms.Panel pnlControls
System.Windows.Forms.Label lblControls
System.Windows.Forms.Button btnCloseControls
System.Windows.Forms.Button btnTest
System.Windows.Forms.Button btnZoomIn
System.Windows.Forms.Button btnZoomOut
System.Windows.Forms.Button btnUnderConstruction_To_Delete
Constructor & Destructor Documentation
ControlViewerControl() [1/6]
IG.Forms.ControlViewerControl.ControlViewerControl () inline
References IG.Forms.ControlViewerControl.btnControlPosition, IG.Forms.ControlViewerControl.InitializeComponent(), and IG.Forms.ControlViewerControl.ShowDummyContents.
ControlViewerControl() [2/6]
IG.Forms.ControlViewerControl.ControlViewerControl (Control viewedControl) inline
References IG.Forms.ControlViewerControl.DisplayedControl.
ControlViewerControl() [3/6]
IG.Forms.ControlViewerControl.ControlViewerControl () inline
References IG.Forms.ControlViewerControl.btnControlPosition, IG.Forms.ControlViewerControl.InitializeComponent(), and IG.Forms.ControlViewerControl.ShowDummyContents.
ControlViewerControl() [4/6]
IG.Forms.ControlViewerControl.ControlViewerControl (Control viewedControl) inline
References IG.Forms.ControlViewerControl.DisplayedControl.
ControlViewerControl() [5/6]
IG.Forms.ControlViewerControl.ControlViewerControl () inline
References IG.Forms.ControlViewerControl.btnControlPosition, IG.Forms.ControlViewerControl.InitializeComponent(), and IG.Forms.ControlViewerControl.ShowDummyContents.
ControlViewerControl() [6/6]
IG.Forms.ControlViewerControl.ControlViewerControl (Control viewedControl) inline
References IG.Forms.ControlViewerControl.DisplayedControl.
Member Function Documentation
CreateNewControl() [1/3]
static Control IG.Forms.ControlViewerControl.CreateNewControl (Type controlType, bool throwIfIncorrectType) inline static
Referenced by IG.Forms.ControlViewerControl.ShowControl().
ShowControl() [1/3]
void IG.Forms.ControlViewerControl.ShowControl (Type controlType) inline
References IG.Forms.ControlViewerControl.CreateNewControl(), and IG.Forms.ControlViewerControl.DisplayedControl.
btnCloseControls_Click() [1/3]
void IG.Forms.ControlViewerControl.btnCloseControls_Click (object sender, EventArgs e) inline private
References IG.Forms.ControlViewerControl.pnlControlContainer.
Referenced by IG.Forms.ControlViewerControl.InitializeComponent().
btnZoomOut_Click() [1/3]
void IG.Forms.ControlViewerControl.btnZoomOut_Click (object sender, EventArgs e) inline private
References IG.Forms.ControlViewerControl.btnControlPosition, and IG.Forms.ControlViewerControl.DisplayedControl.
Referenced by IG.Forms.ControlViewerControl.InitializeComponent().
btnZoomIn_Click() [1/3]
void IG.Forms.ControlViewerControl.btnZoomIn_Click (object sender, EventArgs e) inline private
References IG.Forms.ControlViewerControl.btnControlPosition, and IG.Forms.ControlViewerControl.DisplayedControl.
Referenced by IG.Forms.ControlViewerControl.InitializeComponent().
Dispose() [1/3]
override void IG.Forms.ControlViewerControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ControlViewerControl.components.
InitializeComponent() [1/3]
void IG.Forms.ControlViewerControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ControlViewerControl.btnCloseControls, IG.Forms.ControlViewerControl.btnCloseControls_Click(), IG.Forms.ControlViewerControl.btnControlPosition, IG.Forms.ControlViewerControl.btnTest, IG.Forms.ControlViewerControl.btnUnderConstruction_To_Delete, IG.Forms.ControlViewerControl.btnZoomIn, IG.Forms.ControlViewerControl.btnZoomIn_Click(), IG.Forms.ControlViewerControl.btnZoomOut, IG.Forms.ControlViewerControl.btnZoomOut_Click(), IG.Forms.ControlViewerControl.flowLayoutPanel1, IG.Forms.ControlViewerControl.lblControls, IG.Forms.ControlViewerControl.pnlControlContainer, and IG.Forms.ControlViewerControl.pnlControls.
Referenced by IG.Forms.ControlViewerControl.ControlViewerControl().
CreateNewControl() [2/3]
static Control IG.Forms.ControlViewerControl.CreateNewControl (Type controlType, bool throwIfIncorrectType) inline static
ShowControl() [2/3]
void IG.Forms.ControlViewerControl.ShowControl (Type controlType) inline
References IG.Forms.ControlViewerControl.CreateNewControl(), and IG.Forms.ControlViewerControl.DisplayedControl.
btnCloseControls_Click() [2/3]
void IG.Forms.ControlViewerControl.btnCloseControls_Click (object sender, EventArgs e) inline private
References IG.Forms.ControlViewerControl.pnlControlContainer.
btnZoomOut_Click() [2/3]
void IG.Forms.ControlViewerControl.btnZoomOut_Click (object sender, EventArgs e) inline private
References IG.Forms.ControlViewerControl.btnControlPosition, and IG.Forms.ControlViewerControl.DisplayedControl.
btnZoomIn_Click() [2/3]
void IG.Forms.ControlViewerControl.btnZoomIn_Click (object sender, EventArgs e) inline private
References IG.Forms.ControlViewerControl.btnControlPosition, and IG.Forms.ControlViewerControl.DisplayedControl.
Dispose() [2/3]
override void IG.Forms.ControlViewerControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ControlViewerControl.components.
InitializeComponent() [2/3]
void IG.Forms.ControlViewerControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ControlViewerControl.btnCloseControls, IG.Forms.ControlViewerControl.btnCloseControls_Click(), IG.Forms.ControlViewerControl.btnControlPosition, IG.Forms.ControlViewerControl.btnTest, IG.Forms.ControlViewerControl.btnUnderConstruction_To_Delete, IG.Forms.ControlViewerControl.btnZoomIn, IG.Forms.ControlViewerControl.btnZoomIn_Click(), IG.Forms.ControlViewerControl.btnZoomOut, IG.Forms.ControlViewerControl.btnZoomOut_Click(), IG.Forms.ControlViewerControl.flowLayoutPanel1, IG.Forms.ControlViewerControl.lblControls, IG.Forms.ControlViewerControl.pnlControlContainer, and IG.Forms.ControlViewerControl.pnlControls.
CreateNewControl() [3/3]
static Control IG.Forms.ControlViewerControl.CreateNewControl (Type controlType, bool throwIfIncorrectType) inline static
ShowControl() [3/3]
void IG.Forms.ControlViewerControl.ShowControl (Type controlType) inline
References IG.Forms.ControlViewerControl.CreateNewControl(), and IG.Forms.ControlViewerControl.DisplayedControl.
btnCloseControls_Click() [3/3]
void IG.Forms.ControlViewerControl.btnCloseControls_Click (object sender, EventArgs e) inline private
References IG.Forms.ControlViewerControl.pnlControlContainer.
btnZoomOut_Click() [3/3]
void IG.Forms.ControlViewerControl.btnZoomOut_Click (object sender, EventArgs e) inline private
References IG.Forms.ControlViewerControl.btnControlPosition, and IG.Forms.ControlViewerControl.DisplayedControl.
btnZoomIn_Click() [3/3]
void IG.Forms.ControlViewerControl.btnZoomIn_Click (object sender, EventArgs e) inline private
References IG.Forms.ControlViewerControl.btnControlPosition, and IG.Forms.ControlViewerControl.DisplayedControl.
Dispose() [3/3]
override void IG.Forms.ControlViewerControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ControlViewerControl.components.
InitializeComponent() [3/3]
void IG.Forms.ControlViewerControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ControlViewerControl.btnCloseControls, IG.Forms.ControlViewerControl.btnCloseControls_Click(), IG.Forms.ControlViewerControl.btnControlPosition, IG.Forms.ControlViewerControl.btnTest, IG.Forms.ControlViewerControl.btnUnderConstruction_To_Delete, IG.Forms.ControlViewerControl.btnZoomIn, IG.Forms.ControlViewerControl.btnZoomIn_Click(), IG.Forms.ControlViewerControl.btnZoomOut, IG.Forms.ControlViewerControl.btnZoomOut_Click(), IG.Forms.ControlViewerControl.flowLayoutPanel1, IG.Forms.ControlViewerControl.lblControls, IG.Forms.ControlViewerControl.pnlControlContainer, and IG.Forms.ControlViewerControl.pnlControls.
Member Data Documentation
_showDummyContents
bool IG.Forms.ControlViewerControl._showDummyContents = true private
_displayedControl
Control IG.Forms.ControlViewerControl._displayedControl = null private
components
System ComponentModel IContainer IG.Forms.ControlViewerControl.components = null private
Required designer variable.
Referenced by IG.Forms.ControlViewerControl.Dispose().
flowLayoutPanel1
System Windows Forms FlowLayoutPanel IG.Forms.ControlViewerControl.flowLayoutPanel1 private
Referenced by IG.Forms.ControlViewerControl.InitializeComponent().
pnlControlContainer
System Windows Forms FlowLayoutPanel IG.Forms.ControlViewerControl.pnlControlContainer private
Referenced by IG.Forms.ControlViewerControl.btnCloseControls_Click(), and IG.Forms.ControlViewerControl.InitializeComponent().
btnControlPosition
System Windows Forms Button IG.Forms.ControlViewerControl.btnControlPosition private
Referenced by IG.Forms.ControlViewerControl.btnZoomIn_Click(), IG.Forms.ControlViewerControl.btnZoomOut_Click(), IG.Forms.ControlViewerControl.ControlViewerControl(), and IG.Forms.ControlViewerControl.InitializeComponent().
pnlControls
System Windows Forms Panel IG.Forms.ControlViewerControl.pnlControls private
Referenced by IG.Forms.ControlViewerControl.InitializeComponent().
lblControls
System Windows Forms Label IG.Forms.ControlViewerControl.lblControls private
Referenced by IG.Forms.ControlViewerControl.InitializeComponent().
btnCloseControls
System Windows Forms Button IG.Forms.ControlViewerControl.btnCloseControls private
Referenced by IG.Forms.ControlViewerControl.InitializeComponent().
btnTest
System Windows Forms Button IG.Forms.ControlViewerControl.btnTest private
Referenced by IG.Forms.ControlViewerControl.InitializeComponent().
btnZoomIn
System Windows Forms Button IG.Forms.ControlViewerControl.btnZoomIn private
Referenced by IG.Forms.ControlViewerControl.InitializeComponent().
btnZoomOut
System Windows Forms Button IG.Forms.ControlViewerControl.btnZoomOut private
Referenced by IG.Forms.ControlViewerControl.InitializeComponent().
btnUnderConstruction_To_Delete
System Windows Forms Button IG.Forms.ControlViewerControl.btnUnderConstruction_To_Delete private
Referenced by IG.Forms.ControlViewerControl.InitializeComponent().
Property Documentation
ShowDummyContents
bool IG.Forms.ControlViewerControl.ShowDummyContents get set
Whether the dummy contents of the contaier that holds the viewed control is shown.
Showing dummy contents (usually just a button) can serve to verify that layout of the form is rendered correctly.
Referenced by IG.Forms.ControlViewerControl.ControlViewerControl(), and IG.Forms.ControlViewerForm.InitializeComponent().
DisplayedControl
Control IG.Forms.ControlViewerControl.DisplayedControl get set
Gets or sets the control that is displayed by the current control.
Referenced by IG.Forms.ControlViewerControl.btnZoomIn_Click(), IG.Forms.ControlViewerControl.btnZoomOut_Click(), IG.Forms.ControlViewerControl.ControlViewerControl(), IG.Forms.ControlViewerForm.ControlViewerForm(), IG.Forms.ControlViewerForm.InitializeComponent(), and IG.Forms.ControlViewerControl.ShowControl().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/Viewers/ControlViewerControl.cs
iglib/igforms/Utilities/Viewers/ControlViewerControl.Designer.cs