Doc: IGLib EXTENDED: AForge.Imaging.ExhaustiveTemplateMatching Class Reference
AForge.Imaging.ExhaustiveTemplateMatching Class Reference
Exhaustive template matching.
Classes
class MatchingsSorter
Public Member Functions
ExhaustiveTemplateMatching ()
Initializes a new instance of the ExhaustiveTemplateMatching class.
ExhaustiveTemplateMatching (float similarityThreshold)
Initializes a new instance of the ExhaustiveTemplateMatching class.
TemplateMatch[] ProcessImage (Bitmap image, Bitmap template)
Process image looking for matchings with specified template.
TemplateMatch[] ProcessImage (Bitmap image, Bitmap template, Rectangle searchZone)
Process image looking for matchings with specified template.
TemplateMatch[] ProcessImage (BitmapData imageData, BitmapData templateData)
Process image looking for matchings with specified template.
TemplateMatch[] ProcessImage (BitmapData imageData, BitmapData templateData, Rectangle searchZone)
Process image looking for matchings with specified template.
TemplateMatch[] ProcessImage (UnmanagedImage image, UnmanagedImage template)
Process image looking for matchings with specified template.
TemplateMatch[] ProcessImage (UnmanagedImage image, UnmanagedImage template, Rectangle searchZone)
Process image looking for matchings with specified template.
Properties
float SimilarityThreshold [get, set]
Similarity threshold, [0..1].
Private Attributes
float similarityThreshold = 0.9f
Detailed Description
Exhaustive template matching.
The class implements exhaustive template matching algorithm, which performs complete scan of source image, comparing each pixel with corresponding pixel of template.
The class processes only grayscale 8 bpp and color 24 bpp images.
Sample usage:
// create template matching algorithm's instance
ExhaustiveTemplateMatching tm = new ExhaustiveTemplateMatching(0.9f);
// find all matchings with specified above similarity
TemplateMatch[] matchings = tm.ProcessImage(sourceImage, templateImage);
// highlight found matchings
BitmapData data = sourceImage.LockBits(
    new Rectangle( 0, 0, sourceImage.Width, sourceImage.Height ),
    ImageLockMode.ReadWrite, sourceImage.PixelFormat );
foreach (TemplateMatch m in matchings)
{
    Drawing.Rectangle( data, m.Rectangle, Color.White );
    // do something else with matching
}
sourceImage.UnlockBits(data);
The class also can be used to get similarity level between two image of the same size, which can be useful to get information about how different/similar are images:
// create template matching algorithm's instance
// use zero similarity to make sure algorithm will provide anything
ExhaustiveTemplateMatching tm = new ExhaustiveTemplateMatching(0);
// compare two images
TemplateMatch[] matchings = tm.ProcessImage(image1, image2);
// check similarity level
if (matchings[0].Similarity > 0.95f)
{
    // do something with quite similar images
}
Constructor & Destructor Documentation
ExhaustiveTemplateMatching() [1/2]
AForge.Imaging.ExhaustiveTemplateMatching.ExhaustiveTemplateMatching () inline
Initializes a new instance of the ExhaustiveTemplateMatching class.
ExhaustiveTemplateMatching() [2/2]
AForge.Imaging.ExhaustiveTemplateMatching.ExhaustiveTemplateMatching (float similarityThreshold) inline
Initializes a new instance of the ExhaustiveTemplateMatching class.
Parameters
similarityThreshold Similarity threshold.
References AForge.Imaging.ExhaustiveTemplateMatching.similarityThreshold.
Member Function Documentation
ProcessImage() [1/6]
TemplateMatch [] AForge.Imaging.ExhaustiveTemplateMatching.ProcessImage (Bitmap image, Bitmap template) inline
Process image looking for matchings with specified template.
Parameters
image Source image to process.
template Template image to search for.
Returns
Returns array of found template matches. The array is sorted by similarity of found matches in descending order.
Exceptions
UnsupportedImageFormatException The source image has incorrect pixel format.
InvalidImagePropertiesException Template image is bigger than source image.
References AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.ExhaustiveTemplateMatching.ProcessImage().
ProcessImage() [2/6]
TemplateMatch [] AForge.Imaging.ExhaustiveTemplateMatching.ProcessImage (Bitmap image, Bitmap template, Rectangle searchZone) inline
Process image looking for matchings with specified template.
Parameters
image Source image to process.
template Template image to search for.
searchZone Rectangle in source image to search template for.
Returns
Returns array of found template matches. The array is sorted by similarity of found matches in descending order.
Exceptions
UnsupportedImageFormatException The source image has incorrect pixel format.
InvalidImagePropertiesException Template image is bigger than source image.
Implements AForge.Imaging.ITemplateMatching.
References AForge.Imaging.ExhaustiveTemplateMatching.ProcessImage(), and AForge.Math.Geometry.Rectangle.
ProcessImage() [3/6]
TemplateMatch [] AForge.Imaging.ExhaustiveTemplateMatching.ProcessImage (BitmapData imageData, BitmapData templateData) inline
Process image looking for matchings with specified template.
Parameters
imageData Source image data to process.
templateData Template image to search for.
Returns
Returns array of found template matches. The array is sorted by similarity of found matches in descending order.
Exceptions
UnsupportedImageFormatException The source image has incorrect pixel format.
InvalidImagePropertiesException Template image is bigger than source image.
References AForge.Imaging.ExhaustiveTemplateMatching.ProcessImage(), and AForge.Math.Geometry.Rectangle.
ProcessImage() [4/6]
TemplateMatch [] AForge.Imaging.ExhaustiveTemplateMatching.ProcessImage (BitmapData imageData, BitmapData templateData, Rectangle searchZone) inline
Process image looking for matchings with specified template.
Parameters
imageData Source image data to process.
templateData Template image to search for.
searchZone Rectangle in source image to search template for.
Returns
Returns array of found template matches. The array is sorted by similarity of found matches in descending order.
Exceptions
UnsupportedImageFormatException The source image has incorrect pixel format.
InvalidImagePropertiesException Template image is bigger than source image.
Implements AForge.Imaging.ITemplateMatching.
References AForge.Imaging.ExhaustiveTemplateMatching.ProcessImage().
ProcessImage() [5/6]
TemplateMatch [] AForge.Imaging.ExhaustiveTemplateMatching.ProcessImage (UnmanagedImage image, UnmanagedImage template) inline
Process image looking for matchings with specified template.
Parameters
image Unmanaged source image to process.
template Unmanaged template image to search for.
Returns
Returns array of found template matches. The array is sorted by similarity of found matches in descending order.
Exceptions
UnsupportedImageFormatException The source image has incorrect pixel format.
InvalidImagePropertiesException Template image is bigger than source image.
References AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.ExhaustiveTemplateMatching.ProcessImage(), AForge.Math.Geometry.Rectangle, and AForge.Imaging.UnmanagedImage.Width.
ProcessImage() [6/6]
TemplateMatch [] AForge.Imaging.ExhaustiveTemplateMatching.ProcessImage (UnmanagedImage image, UnmanagedImage template, Rectangle searchZone) inline
Process image looking for matchings with specified template.
Parameters
image Unmanaged source image to process.
template Unmanaged template image to search for.
searchZone Rectangle in source image to search template for.
Returns
Returns array of found template matches. The array is sorted by similarity of found matches in descending order.
Exceptions
UnsupportedImageFormatException The source image has incorrect pixel format.
InvalidImagePropertiesException Template image is bigger than search zone.
Implements AForge.Imaging.ITemplateMatching.
References AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Math.Geometry.Rectangle, AForge.Imaging.ExhaustiveTemplateMatching.similarityThreshold, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
Member Data Documentation
similarityThreshold
float AForge.Imaging.ExhaustiveTemplateMatching.similarityThreshold = 0.9f private
Referenced by AForge.Imaging.ExhaustiveTemplateMatching.ExhaustiveTemplateMatching(), and AForge.Imaging.ExhaustiveTemplateMatching.ProcessImage().
Property Documentation
SimilarityThreshold
float AForge.Imaging.ExhaustiveTemplateMatching.SimilarityThreshold get set
Similarity threshold, [0..1].
The property sets the minimal acceptable similarity between template and potential found candidate. If similarity is lower than this value, then object is not treated as matching with template.
Default value is set to 0.9.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/ExhaustiveTemplateMatching.cs