Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAED3 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAED3 Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAED3 (DLAMC3 dlamc3, DNRM2 dnrm2, DCOPY dcopy, DGEMM dgemm, DLACPY dlacpy, DLAED4 dlaed4, DLASET dlaset, XERBLA xerbla)
DLAED3 ()
void Run (int K, int N, int N1, ref double[] D, int offset_d, ref double[] Q, int offset_q, int LDQ, double RHO, ref double[] DLAMDA, int offset_dlamda, double[] Q2, int offset_q2, int[] INDX, int offset_indx, int[] CTOT, int offset_ctot, ref double[] W, int offset_w, ref double[] S, int offset_s, ref int INFO)
Private Attributes
DLAMC3 _dlamc3
DNRM2 _dnrm2
DCOPY _dcopy
DGEMM _dgemm
DLACPY _dlacpy
DLAED4 _dlaed4
DLASET _dlaset
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E0
const double ZERO = 0.0E0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAED3 finds the roots of the secular equation, as defined by the values in D, W, and RHO, between 1 and K. It makes the appropriate calls to DLAED4 and then updates the eigenvectors by multiplying the matrix of eigenvectors of the pair of eigensystems being combined by the matrix of eigenvectors of the K-by-K system which is solved here.
This code makes very mild assumptions about floating point arithmetic. It will work on machines with a guard digit in add/subtract, or on those binary machines without guard digits which subtract like the Cray X-MP, Cray Y-MP, Cray C-90, or Cray-2. It could conceivably fail on hexadecimal or decimal machines without guard digits, but we know of none.
/summary>
Constructor & Destructor Documentation
DLAED3() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAED3.DLAED3 (DLAMC3 dlamc3, DNRM2 dnrm2, DCOPY dcopy, DGEMM dgemm, DLACPY dlacpy, DLAED4 dlaed4, DLASET dlaset, XERBLA xerbla) inline
DLAED3() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAED3.DLAED3 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAED3.Run (int K, int N, int N1, ref double[] D, int offset_d, ref double[] Q, int offset_q, int LDQ, double RHO, ref double[] DLAMDA, int offset_dlamda, double[] Q2, int offset_q2, int[] INDX, int offset_indx, int[] CTOT, int offset_ctot, ref double[] W, int offset_w, ref double[] S, int offset_s, ref int INFO) inline
Purpose
DLAED3 finds the roots of the secular equation, as defined by the values in D, W, and RHO, between 1 and K. It makes the appropriate calls to DLAED4 and then updates the eigenvectors by multiplying the matrix of eigenvectors of the pair of eigensystems being combined by the matrix of eigenvectors of the K-by-K system which is solved here.
This code makes very mild assumptions about floating point arithmetic. It will work on machines with a guard digit in add/subtract, or on those binary machines without guard digits which subtract like the Cray X-MP, Cray Y-MP, Cray C-90, or Cray-2. It could conceivably fail on hexadecimal or decimal machines without guard digits, but we know of none.
/summary>
Parameters
K (input) INTEGER The number of terms in the rational function to be solved by DLAED4. K .GE. 0. /param>
Parameters
N (input) INTEGER The number of rows and columns in the Q matrix. N .GE. K (deflation may result in N.GT.K). /param>
Parameters
N1 (input) INTEGER The location of the last eigenvalue in the leading submatrix. min(1,N) .LE. N1 .LE. N/2. /param>
Parameters
D (output) DOUBLE PRECISION array, dimension (N) D(I) contains the updated eigenvalues for 1 .LE. I .LE. K. /param>
Parameters
Q (output) DOUBLE PRECISION array, dimension (LDQ,N) Initially the first K columns are used as workspace. On output the columns 1 to K contain the updated eigenvectors. /param>
Parameters
LDQ (input) INTEGER The leading dimension of the array Q. LDQ .GE. max(1,N). /param>
Parameters
RHO (input) DOUBLE PRECISION The value of the parameter in the rank one update equation. RHO .GE. 0 required. /param>
Parameters
DLAMDA (input/output) DOUBLE PRECISION array, dimension (K) The first K elements of this array contain the old roots of the deflated updating problem. These are the poles of the secular equation. May be changed on output by having lowest order bit set to zero on Cray X-MP, Cray Y-MP, Cray-2, or Cray C-90, as described above. /param>
Parameters
Q2 (input) DOUBLE PRECISION array, dimension (LDQ2, N) The first K columns of this matrix contain the non-deflated eigenvectors for the split problem. /param>
Parameters
INDX (input) INTEGER array, dimension (N) The permutation used to arrange the columns of the deflated Q matrix into three groups (see DLAED2). The rows of the eigenvectors found by DLAED4 must be likewise permuted before the matrix multiply can take place. /param>
Parameters
CTOT (input) INTEGER array, dimension (4) A count of the total number of the various types of columns in Q, as described in INDX. The fourth column type is any column which has been deflated. /param>
Parameters
W (input/output) DOUBLE PRECISION array, dimension (K) The first K elements of this array contain the components of the deflation-adjusted updating vector. Destroyed on output. /param>
Parameters
S (workspace) DOUBLE PRECISION array, dimension (N1 + 1)*K Will contain the eigenvectors of the repaired matrix which will be multiplied by the previously accumulated eigenvectors to update the system. /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. .GT. 0: if INFO = 1, an eigenvalue did not converge /param>
References DotNumerics.LinearAlgebra.CSLapack.DLAED3.ONE, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DNRM2.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASET.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED4.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMC3.Run(), DotNumerics.FortranLibrary.FortranLib.Sign(), and DotNumerics.LinearAlgebra.CSLapack.DLAED3.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED1.Run().
Member Data Documentation
_dlamc3
DLAMC3 DotNumerics.LinearAlgebra.CSLapack.DLAED3._dlamc3 private
_dnrm2
DNRM2 DotNumerics.LinearAlgebra.CSLapack.DLAED3._dnrm2 private
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLAED3._dcopy private
_dgemm
DGEMM DotNumerics.LinearAlgebra.CSLapack.DLAED3._dgemm private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DLAED3._dlacpy private
_dlaed4
DLAED4 DotNumerics.LinearAlgebra.CSLapack.DLAED3._dlaed4 private
_dlaset
DLASET DotNumerics.LinearAlgebra.CSLapack.DLAED3._dlaset private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLAED3._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAED3.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED3.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAED3.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED3.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlaed3.cs