Doc: IGLib EXTENDED: IG.Test.ProgramTestNumericsIgor Class Reference
IG.Test.ProgramTestNumericsIgor Class Reference
Static Public Member Functions
static int TestList (IList< int > l)
static void Test ()
Static Private Member Functions
static void Main (string[] args)
Main program for testing numerical utilities.
Member Function Documentation
TestList()
static int IG.Test.ProgramTestNumericsIgor.TestList (IList< int > l) inline static
Main()
static void IG.Test.ProgramTestNumericsIgor.Main (string[] args) inline static private
Main program for testing numerical utilities.
References IG.Num.A, IG.Num.MatrixBase.TestCholeskyDecomposition(), IG.Num.SpeedTestCpu.TestComputationalTimesCholesky_IGLib(), IG.Num.VectorBase.TestGramSchmidtOrthogonalization(), IG.Num.MatrixBase.TestLdltDecomposition(), IG.Num.MatrixBase.TestLuDecomposition(), IG.Num.MatrixBase.TestLuDecompositionDemo(), IG.Num.ApproximatorWlsLinearBase.TestWeightedLeastSquaresMultipleQuadraticBasis(), and IG.Num.ApproximatorWlsLinearBase.TestWeightedLeastSquaresQuadraticBasis().
Test()
static void IG.Test.ProgramTestNumericsIgor.Test () inline static
The documentation for this class was generated from the following file:
igtest/numerics/test_numerics_igor/test_numerics_igor/ProgramTestNumericsIgor.cs