Doc: IGLib EXTENDED: IG.MPetekLib.Application.Scripts.NonlinearOscNondim._20MultipleResCurvesPlot Class Reference
IG.MPetekLib.Application.Scripts.NonlinearOscNondim._20MultipleResCurvesPlot Class Reference
Static Public Member Functions
static void Run (string[] arguments)
Poženi preko batch datoteke. Pri fiksnih parametrih, ki jih podamo preko argumentov skripta,
Member Function Documentation
Run()
static void IG.MPetekLib.Application.Scripts.NonlinearOscNondim._20MultipleResCurvesPlot.Run (string[] arguments) inline static
Poženi preko batch datoteke. Pri fiksnih parametrih, ki jih podamo preko argumentov skripta,
se izračuna in nariše več resonančnih krivulj pri različnih karakterističnih kotnih frekvencah.
Parameters
arguments Kar. čas, kar. kotna frekvenca vsiljevanja, začetna brezdim. kotna frekv. vsiljevanja, končna, število točk vzorčenja.
References IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.CalcSteadyStateAmplitudeVsDrivingFrequency(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenNonlinOscNondim.CharacteristicDrivingAngFreq, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenNonlinOscNondim.CharacteristicOscAngFreq, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenNonlinOscNondim.CharacteristicTime, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.EndingDrivingAngularFrequency, IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase.NewCurveFromPlottableData(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.NSamplesForResonanceCurve, IG.MPetekLib.Algorithms.Plotting.PlotHQ.Plotter, IG.MPetekLib.Algorithms.Plotting.PlotHQ.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.PlottableODEModelBase.Solver, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.StartingDrivingAngularFrequency, and IG.MPetekLib.Algorithms.Solvers.InitialProblemODE_RK4.InitialProblemSolverBase.StepSize.
Referenced by IG.Script.AppMarkoPetek.App20MultipleResCurvesPlot().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/Guest_Marko_Petek_Lib/application/scripts/NonlinearOscNondim/20MultipleResCurvesPlot.cs