Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DORG2R Class Reference
DotNumerics.LinearAlgebra.CSLapack.DORG2R Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DORG2R (DLARF dlarf, DSCAL dscal, XERBLA xerbla)
DORG2R ()
void Run (int M, int N, int K, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
DLARF _dlarf
DSCAL _dscal
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DORG2R generates an m by n real matrix Q with orthonormal columns, which is defined as the first n columns of a product of k elementary reflectors of order m
Q = H(1) H(2) . . . H(k)
as returned by DGEQRF.
/summary>
Constructor & Destructor Documentation
DORG2R() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DORG2R.DORG2R (DLARF dlarf, DSCAL dscal, XERBLA xerbla) inline
DORG2R() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DORG2R.DORG2R () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DORG2R.Run (int M, int N, int K, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
DORG2R generates an m by n real matrix Q with orthonormal columns, which is defined as the first n columns of a product of k elementary reflectors of order m
Q = H(1) H(2) . . . H(k)
as returned by DGEQRF.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix Q. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix Q. M .GE. N .GE. 0. /param>
Parameters
K (input) INTEGER The number of elementary reflectors whose product defines the matrix Q. N .GE. K .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the i-th column must contain the vector which defines the elementary reflector H(i), for i = 1,2,...,k, as returned by DGEQRF in the first k columns of its array argument A. On exit, the m-by-n matrix Q. /param>
Parameters
LDA (input) INTEGER The first dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
TAU (input) DOUBLE PRECISION array, dimension (K) TAU(i) must contain the scalar factor of the elementary reflector H(i), as returned by DGEQRF. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (N) /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument has an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.DORG2R.ONE, DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARF.Run(), and DotNumerics.LinearAlgebra.CSLapack.DORG2R.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORGQR.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGGSVP.Run().
Member Data Documentation
_dlarf
DLARF DotNumerics.LinearAlgebra.CSLapack.DORG2R._dlarf private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DORG2R._dscal private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DORG2R._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DORG2R.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORG2R.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DORG2R.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORG2R.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dorg2r.cs