Doc: IGLib EXTENDED: IG.MPetekLib.Application.Scripts.LinearOscillator._01NondrivenPrintSolution Class Reference
IG.MPetekLib.Application.Scripts.LinearOscillator._01NondrivenPrintSolution Class Reference
Testiram delovanje solverja RK4. Izvede se samo izračun brez risanja grafov.
Static Public Member Functions
static InitialProblemSolverRK4 ReturnSolver ()
Detailed Description
Testiram delovanje solverja RK4. Izvede se samo izračun brez risanja grafov.
Member Function Documentation
ReturnSolver()
static InitialProblemSolverRK4 IG.MPetekLib.Application.Scripts.LinearOscillator._01NondrivenPrintSolution.ReturnSolver () inline static
References IG.MPetekLib.Algorithms.Solvers.InitialProblemODE_RK4.InitialProblemSolverBase.EndPoint, IG.MPetekLib.Algorithms.Solvers.InitialProblemODE_RK4.InitialProblemSolverBase.HighestDerivative, IG.MPetekLib.Algorithms.Solvers.InitialProblemODE_RK4.InitialProblemSolverBase.InitialConditions, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.SimpleHarmonicOscillator.ODE(), IG.MPetekLib.Algorithms.Solvers.InitialProblemODE_RK4.InitialProblemSolverBase.Solve(), and IG.MPetekLib.Algorithms.Solvers.InitialProblemODE_RK4.InitialProblemSolverBase.StepSize.
Referenced by IG.Script.AppMarkoPetek.App01NondrivenPrintSolution().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/Guest_Marko_Petek_Lib/application/scripts/LinearOscillator/01NondrivenPrintSolution.cs