Doc: IGLib EXTENDED: NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture Class Reference
NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture Class Reference
Public Member Functions
void InstanceTestMethod ()
void TestMethodWithArgumentsNotProvided (int x, int y, string label)
void TestMethodWithArgumentsNotProvidedAndExtraAttributes (int x, int y, string label)
void TestMethodWithoutParametersWithArgumentsProvided ()
void TestMethodWithArgumentsProvided (int x, int y, string label)
void TestMethodWithWrongNumberOfArgumentsProvided (int x, int y, string label)
void TestMethodWithWrongArgumentTypesProvided (int x, int y, string label)
void TestMethodWithConvertibleArguments (double x, double y, double sum)
void TestMethodWithNonConvertibleArguments (int x, int y, int sum)
void TestMethodWithMultipleTestCases (int n, int d, int q)
bool TestMethodWithReturnType ()
bool TestMethodWithExpectedReturnType ()
Static Public Member Functions
static void StaticTestMethod ()
static void StaticTestMethodWithArgumentsNotProvided (int x, int y, string label)
static void StaticTestMethodWithArgumentsProvided (int x, int y, string label)
static void StaticTestMethodWithWrongNumberOfArgumentsProvided (int x, int y, string label)
static void StaticTestMethodWithWrongArgumentTypesProvided (int x, int y, string label)
Static Public Attributes
static int Tests = 21
static int Runnable = 12
static int NotRunnable = 9
static int Errors = 3
static int Failures = 0
Protected Member Functions
void ProtectedTestMethod ()
Private Member Functions
void PrivateTestMethod ()
Member Function Documentation
InstanceTestMethod()
void NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.InstanceTestMethod () inline
StaticTestMethod()
static void NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.StaticTestMethod () inline static
TestMethodWithArgumentsNotProvided()
void NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.TestMethodWithArgumentsNotProvided (int x, int y, string label) inline
TestMethodWithArgumentsNotProvidedAndExtraAttributes()
void NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.TestMethodWithArgumentsNotProvidedAndExtraAttributes (int x, int y, string label) inline
StaticTestMethodWithArgumentsNotProvided()
static void NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.StaticTestMethodWithArgumentsNotProvided (int x, int y, string label) inline static
TestMethodWithoutParametersWithArgumentsProvided()
void NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.TestMethodWithoutParametersWithArgumentsProvided () inline
TestMethodWithArgumentsProvided()
void NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.TestMethodWithArgumentsProvided (int x, int y, string label) inline
References NUnit.Framework.Assert.AreEqual().
StaticTestMethodWithArgumentsProvided()
static void NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.StaticTestMethodWithArgumentsProvided (int x, int y, string label) inline static
References NUnit.Framework.Assert.AreEqual().
TestMethodWithWrongNumberOfArgumentsProvided()
void NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.TestMethodWithWrongNumberOfArgumentsProvided (int x, int y, string label) inline
TestMethodWithWrongArgumentTypesProvided()
void NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.TestMethodWithWrongArgumentTypesProvided (int x, int y, string label) inline
StaticTestMethodWithWrongNumberOfArgumentsProvided()
static void NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.StaticTestMethodWithWrongNumberOfArgumentsProvided (int x, int y, string label) inline static
StaticTestMethodWithWrongArgumentTypesProvided()
static void NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.StaticTestMethodWithWrongArgumentTypesProvided (int x, int y, string label) inline static
TestMethodWithConvertibleArguments()
void NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.TestMethodWithConvertibleArguments (double x, double y, double sum) inline
References NUnit.Framework.Assert.AreEqual().
TestMethodWithNonConvertibleArguments()
void NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.TestMethodWithNonConvertibleArguments (int x, int y, int sum) inline
References NUnit.Framework.Assert.AreEqual().
TestMethodWithMultipleTestCases()
void NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.TestMethodWithMultipleTestCases (int n, int d, int q) inline
References NUnit.Framework.Assert.AreEqual().
ProtectedTestMethod()
void NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.ProtectedTestMethod () inline protected
PrivateTestMethod()
void NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.PrivateTestMethod () inline private
TestMethodWithReturnType()
bool NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.TestMethodWithReturnType () inline
TestMethodWithExpectedReturnType()
bool NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.TestMethodWithExpectedReturnType () inline
Member Data Documentation
Tests
int NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.Tests = 21 static
Referenced by NUnit.Framework.Internal.TestMethodSignatureTests.RunningTestsThroughFixtureGivesCorrectResults().
Runnable
int NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.Runnable = 12 static
NotRunnable
int NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.NotRunnable = 9 static
Referenced by NUnit.Framework.Internal.TestMethodSignatureTests.RunningTestsThroughFixtureGivesCorrectResults().
Errors
int NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.Errors = 3 static
Referenced by NUnit.Framework.Internal.TestMethodSignatureTests.RunningTestsThroughFixtureGivesCorrectResults().
Failures
int NUnit.TestData.TestMethodSignatureFixture.TestMethodSignatureFixture.Failures = 0 static
Referenced by NUnit.Framework.Internal.TestMethodSignatureTests.RunningTestsThroughFixtureGivesCorrectResults().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/testdata/TestMethodSignatureFixture.cs