Doc: IGLib EXTENDED: AForge.Imaging.Filters.TexturedFilter Class Reference
AForge.Imaging.Filters.TexturedFilter Class Reference
Textured filter - filter an image using texture.
Public Member Functions
TexturedFilter (float[,] texture, IFilter filter1)
Initializes a new instance of the TexturedFilter class.
TexturedFilter (float[,] texture, IFilter filter1, IFilter filter2)
Initializes a new instance of the TexturedFilter class.
TexturedFilter (ITextureGenerator generator, IFilter filter1)
Initializes a new instance of the TexturedFilter class.
TexturedFilter (ITextureGenerator generator, IFilter filter1, IFilter filter2)
Initializes a new instance of the TexturedFilter class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage sourceData, UnmanagedImage destinationData)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
double FilterLevel [get, set]
Filter level value, [0, 1].
double PreserveLevel [get, set]
Preserve level value
float[,] Texture [get, set]
Generated texture.
ITextureGenerator TextureGenerator [get, set]
Texture generator.
IFilter Filter1 [get, set]
First filter.
IFilter Filter2 [get, set]
Second filter
Properties inherited from AForge.Imaging.Filters.BaseFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Member Functions
TexturedFilter ()
Private Attributes
ITextureGenerator textureGenerator
float[,] texture = null
IFilter filter1 = null
IFilter filter2 = null
double filterLevel = 1.0
double preserveLevel = 0.0
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Textured filter - filter an image using texture.
The filter is similar to TexturedMerge filter in its nature, but instead of working with source image and overly, it uses provided filters to create images to merge (see Filter1 and Filter2 properties). In addition, it uses a bit more complex formula for calculation of destination pixel's value, which gives greater amount of flexibility:
dst = FilterLevel * (src1 * textureValue + src2 * (1.0 - textureValue)) + PreserveLevel * src2, where src1 is value of pixel from the image produced by Filter1, src2 is value of pixel from the image produced by Filter2, dst is value of pixel in a destination image and textureValue is corresponding value from provided texture (see TextureGenerator or Texture).
<note>It is possible to set Filter2 to null. In this case original source image will be used instead of result produced by the second filter.</note>
The filter 24 bpp color images for processing.
Sample usage #1:
// create filter
TexturedFilter filter = new TexturedFilter(new CloudsTexture(),
    new HueModifier( 50 ) );
// apply the filter
Bitmap newImage = filter.Apply(image);
Sample usage #2:
// create filter
TexturedFilter filter = new TexturedFilter(new CloudsTexture(),
    new GrayscaleBT709( ), new Sepia( ) );
// apply the filter
Bitmap newImage = filter.Apply(image);
Initial image:
Result image #1:
Result image #2:
Constructor & Destructor Documentation
TexturedFilter() [1/5]
AForge.Imaging.Filters.TexturedFilter.TexturedFilter () inline private
References AForge.Imaging.Filters.TexturedFilter.formatTranslations.
TexturedFilter() [2/5]
AForge.Imaging.Filters.TexturedFilter.TexturedFilter (float texture[,], IFilter filter1) inline
Initializes a new instance of the TexturedFilter class.
Parameters
texture Generated texture.
filter1 First filter.
References AForge.Imaging.Filters.TexturedFilter.filter1, and AForge.Imaging.Filters.TexturedFilter.texture.
TexturedFilter() [3/5]
AForge.Imaging.Filters.TexturedFilter.TexturedFilter (float texture[,], IFilter filter1, IFilter filter2) inline
Initializes a new instance of the TexturedFilter class.
Parameters
texture Generated texture.
filter1 First filter.
filter2 Second filter.
References AForge.Imaging.Filters.TexturedFilter.filter1, AForge.Imaging.Filters.TexturedFilter.filter2, and AForge.Imaging.Filters.TexturedFilter.texture.
TexturedFilter() [4/5]
AForge.Imaging.Filters.TexturedFilter.TexturedFilter (ITextureGenerator generator, IFilter filter1) inline
Initializes a new instance of the TexturedFilter class.
Parameters
generator Texture generator.
filter1 First filter.
References AForge.Imaging.Filters.TexturedFilter.filter1.
TexturedFilter() [5/5]
AForge.Imaging.Filters.TexturedFilter.TexturedFilter (ITextureGenerator generator, IFilter filter1, IFilter filter2) inline
Initializes a new instance of the TexturedFilter class.
Parameters
generator Texture generator.
filter1 First filter.
filter2 Second filter.
References AForge.Imaging.Filters.TexturedFilter.filter1, and AForge.Imaging.Filters.TexturedFilter.filter2.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.TexturedFilter.ProcessFilter (UnmanagedImage sourceData, UnmanagedImage destinationData) inline protected virtual
Process the filter on the specified image.
Parameters
sourceData Source image data.
destinationData Destination image data.
Exceptions
InvalidImagePropertiesException Texture size does not match image size.
ApplicationException Filters should not change image dimension.
Implements AForge.Imaging.Filters.BaseFilter.
References AForge.Imaging.Filters.IFilter.Apply(), AForge.Imaging.Filters.BaseFilter.Apply(), AForge.Imaging.UnmanagedImage.Dispose(), AForge.Imaging.Filters.TexturedFilter.filter1, AForge.Imaging.Filters.TexturedFilter.filter2, AForge.Imaging.Filters.TexturedFilter.filterLevel, AForge.Imaging.Textures.ITextureGenerator.Generate(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.Filters.TexturedFilter.preserveLevel, AForge.Imaging.UnmanagedImage.Stride, AForge.Imaging.Filters.TexturedFilter.texture, AForge.Imaging.Filters.TexturedFilter.textureGenerator, and AForge.Imaging.UnmanagedImage.Width.
Member Data Documentation
textureGenerator
ITextureGenerator AForge.Imaging.Filters.TexturedFilter.textureGenerator private
Referenced by AForge.Imaging.Filters.TexturedFilter.ProcessFilter().
texture
float [,] AForge.Imaging.Filters.TexturedFilter.texture = null private
Referenced by AForge.Imaging.Filters.TexturedFilter.ProcessFilter(), and AForge.Imaging.Filters.TexturedFilter.TexturedFilter().
filter1
IFilter AForge.Imaging.Filters.TexturedFilter.filter1 = null private
Referenced by AForge.Imaging.Filters.TexturedFilter.ProcessFilter(), and AForge.Imaging.Filters.TexturedFilter.TexturedFilter().
filter2
IFilter AForge.Imaging.Filters.TexturedFilter.filter2 = null private
Referenced by AForge.Imaging.Filters.TexturedFilter.ProcessFilter(), and AForge.Imaging.Filters.TexturedFilter.TexturedFilter().
filterLevel
double AForge.Imaging.Filters.TexturedFilter.filterLevel = 1.0 private
Referenced by AForge.Imaging.Filters.TexturedFilter.ProcessFilter().
preserveLevel
double AForge.Imaging.Filters.TexturedFilter.preserveLevel = 0.0 private
Referenced by AForge.Imaging.Filters.TexturedFilter.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.TexturedFilter.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.TexturedFilter.TexturedFilter().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.TexturedFilter.FormatTranslations get
Format translations dictionary.
See IFilterInformation.FormatTranslations for more information.
FilterLevel
double AForge.Imaging.Filters.TexturedFilter.FilterLevel get set
Filter level value, [0, 1].
Filtering factor determines portion of the destionation image, which is formed as a result of merging source images using specified texture.
Default value is set to 1.0.
See TexturedFilter class description for more details.
PreserveLevel
double AForge.Imaging.Filters.TexturedFilter.PreserveLevel get set
Preserve level value
Preserving factor determines portion taken from the image produced by Filter2 (or from original source) without applying textured merge to it.
Default value is set to 0.0.
See TexturedFilter class description for more details.
Texture
float [,] AForge.Imaging.Filters.TexturedFilter.Texture get set
Generated texture.
Two dimensional array of texture intensities.
<note>Size of the provided texture should be the same as size of images, which will be passed to the filter.</note>
<note>The TextureGenerator property has priority over this property - if generator is specified than the static generated texture is not used.</note>
TextureGenerator
ITextureGenerator AForge.Imaging.Filters.TexturedFilter.TextureGenerator get set
Texture generator.
Generator used to generate texture.
<note>The property has priority over the Texture property.</note>
Filter1
IFilter AForge.Imaging.Filters.TexturedFilter.Filter1 get set
First filter.
Filter, which is used to produce first image for the merge. The filter needs to implement IFilterInformation interface, so it could be possible to get information about the filter. The filter must be able to process color 24 bpp images and produce color 24 bpp or grayscale 8 bppp images as result.
Exceptions
UnsupportedImageFormatException The specified filter does not support 24 bpp color images.
UnsupportedImageFormatException The specified filter does not produce image of supported format.
ArgumentException The specified filter does not implement IFilterInformation interface.
Filter2
IFilter AForge.Imaging.Filters.TexturedFilter.Filter2 get set
Second filter
Filter, which is used to produce second image for the merge. The filter needs to implement IFilterInformation interface, so it could be possible to get information about the filter. The filter must be able to process color 24 bpp images and produce color 24 bpp or grayscale 8 bppp images as result.
<note>The filter may be set to null. In this case original source image is used as a second image for the merge.</note>
Exceptions
UnsupportedImageFormatException The specified filter does not support 24 bpp color images.
UnsupportedImageFormatException The specified filter does not produce image of supported format.
ArgumentException The specified filter does not implement IFilterInformation interface.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Other/TexturedFilter.cs