Doc: IGLib EXTENDED: alglib.matdet Class Reference
alglib.matdet Class Reference
Static Public Member Functions
static double rmatrixludet (double[,] a, int[] pivots, int n)
static double rmatrixdet (double[,] a, int n)
static complex cmatrixludet (complex[,] a, int[] pivots, int n)
static complex cmatrixdet (complex[,] a, int n)
static double spdmatrixcholeskydet (double[,] a, int n)
static double spdmatrixdet (double[,] a, int n, bool isupper)
static double rmatrixludet (double[,] a, int[] pivots, int n)
static double rmatrixdet (double[,] a, int n)
static complex cmatrixludet (complex[,] a, int[] pivots, int n)
static complex cmatrixdet (complex[,] a, int n)
static double spdmatrixcholeskydet (double[,] a, int n)
static double spdmatrixdet (double[,] a, int n, bool isupper)
Member Function Documentation
rmatrixludet() [1/2]
static double alglib.matdet.rmatrixludet (double a[,], int[] pivots, int n) inline static
Referenced by alglib.rmatrixludet().
rmatrixdet() [1/2]
static double alglib.matdet.rmatrixdet (double a[,], int n) inline static
Referenced by alglib.rmatrixdet().
cmatrixludet() [1/2]
static complex alglib.matdet.cmatrixludet (complex a[,], int[] pivots, int n) inline static
Referenced by alglib.cmatrixludet().
cmatrixdet() [1/2]
static complex alglib.matdet.cmatrixdet (complex a[,], int n) inline static
Referenced by alglib.cmatrixdet().
spdmatrixcholeskydet() [1/2]
static double alglib.matdet.spdmatrixcholeskydet (double a[,], int n) inline static
Referenced by alglib.spdmatrixcholeskydet().
spdmatrixdet() [1/2]
static double alglib.matdet.spdmatrixdet (double a[,], int n, bool isupper) inline static
Referenced by alglib.spdmatrixdet().
rmatrixludet() [2/2]
static double alglib.matdet.rmatrixludet (double a[,], int[] pivots, int n) inline static
rmatrixdet() [2/2]
static double alglib.matdet.rmatrixdet (double a[,], int n) inline static
cmatrixludet() [2/2]
static complex alglib.matdet.cmatrixludet (complex a[,], int[] pivots, int n) inline static
cmatrixdet() [2/2]
static complex alglib.matdet.cmatrixdet (complex a[,], int n) inline static
spdmatrixcholeskydet() [2/2]
static double alglib.matdet.spdmatrixcholeskydet (double a[,], int n) inline static
spdmatrixdet() [2/2]
static double alglib.matdet.spdmatrixdet (double a[,], int n, bool isupper) inline static
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/linalg.cs