Doc: IGLib EXTENDED: IG.Forms.HashAllControl Class Reference
IG.Forms.HashAllControl Class Reference
Public Member Functions
HashAllControl ()
HashAllControl ()
HashAllControl ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void tabControl1_KeyUp (object sender, KeyEventArgs e)
void hashControl1_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void tabControl1_KeyUp (object sender, KeyEventArgs e)
void hashControl1_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void tabControl1_KeyUp (object sender, KeyEventArgs e)
void hashControl1_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.TabControl tabControl1
System.Windows.Forms.TabPage tabPageHash
System.Windows.Forms.TabPage tabPageDir
System.Windows.Forms.TabPage tabPageAbout
HashControl hashControl1
IG.Forms.HashDirControl hashDirControl1
IG.Forms.HashAboutControl hashFormAbout1
Constructor & Destructor Documentation
HashAllControl() [1/3]
IG.Forms.HashAllControl.HashAllControl () inline
References IG.Forms.HashAllControl.InitializeComponent().
HashAllControl() [2/3]
IG.Forms.HashAllControl.HashAllControl () inline
References IG.Forms.HashAllControl.InitializeComponent().
HashAllControl() [3/3]
IG.Forms.HashAllControl.HashAllControl () inline
References IG.Forms.HashAllControl.InitializeComponent().
Member Function Documentation
tabControl1_KeyUp() [1/3]
void IG.Forms.HashAllControl.tabControl1_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Forms.HashAllControl.hashControl1, and IG.Forms.HashControl.KeyUpHandler().
Referenced by IG.Forms.HashAllControl.InitializeComponent().
hashControl1_Load() [1/3]
void IG.Forms.HashAllControl.hashControl1_Load (object sender, EventArgs e) inline private
Referenced by IG.Forms.HashAllControl.InitializeComponent().
Dispose() [1/3]
override void IG.Forms.HashAllControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.HashAllControl.components.
InitializeComponent() [1/3]
void IG.Forms.HashAllControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.HashControl.DirectoryPath, IG.Forms.HashControl.FilePath, IG.Forms.HashAllControl.hashControl1, IG.Forms.HashAllControl.hashControl1_Load(), IG.Forms.HashAllControl.hashDirControl1, IG.Forms.HashAllControl.hashFormAbout1, IG.Forms.HashAllControl.tabControl1, IG.Forms.HashAllControl.tabControl1_KeyUp(), IG.Forms.HashAllControl.tabPageAbout, IG.Forms.HashAllControl.tabPageDir, and IG.Forms.HashAllControl.tabPageHash.
Referenced by IG.Forms.HashAllControl.HashAllControl().
tabControl1_KeyUp() [2/3]
void IG.Forms.HashAllControl.tabControl1_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Forms.HashAllControl.hashControl1, and IG.Forms.HashControl.KeyUpHandler().
hashControl1_Load() [2/3]
void IG.Forms.HashAllControl.hashControl1_Load (object sender, EventArgs e) inline private
Dispose() [2/3]
override void IG.Forms.HashAllControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.HashAllControl.components.
InitializeComponent() [2/3]
void IG.Forms.HashAllControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.HashControl.DirectoryPath, IG.Forms.HashControl.FilePath, IG.Forms.HashAllControl.hashControl1, IG.Forms.HashAllControl.hashControl1_Load(), IG.Forms.HashAllControl.hashDirControl1, IG.Forms.HashAllControl.hashFormAbout1, IG.Forms.HashAllControl.tabControl1, IG.Forms.HashAllControl.tabControl1_KeyUp(), IG.Forms.HashAllControl.tabPageAbout, IG.Forms.HashAllControl.tabPageDir, and IG.Forms.HashAllControl.tabPageHash.
tabControl1_KeyUp() [3/3]
void IG.Forms.HashAllControl.tabControl1_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Forms.HashAllControl.hashControl1, and IG.Forms.HashControl.KeyUpHandler().
hashControl1_Load() [3/3]
void IG.Forms.HashAllControl.hashControl1_Load (object sender, EventArgs e) inline private
Dispose() [3/3]
override void IG.Forms.HashAllControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.HashAllControl.components.
InitializeComponent() [3/3]
void IG.Forms.HashAllControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.HashControl.DirectoryPath, IG.Forms.HashControl.FilePath, IG.Forms.HashAllControl.hashControl1, IG.Forms.HashAllControl.hashControl1_Load(), IG.Forms.HashAllControl.hashDirControl1, IG.Forms.HashAllControl.hashFormAbout1, IG.Forms.HashAllControl.tabControl1, IG.Forms.HashAllControl.tabControl1_KeyUp(), IG.Forms.HashAllControl.tabPageAbout, IG.Forms.HashAllControl.tabPageDir, and IG.Forms.HashAllControl.tabPageHash.
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.HashAllControl.components = null private
Required designer variable.
Referenced by IG.Forms.HashAllControl.Dispose().
tabControl1
System Windows Forms TabControl IG.Forms.HashAllControl.tabControl1 private
Referenced by IG.Forms.HashAllControl.InitializeComponent().
tabPageHash
System Windows Forms TabPage IG.Forms.HashAllControl.tabPageHash private
Referenced by IG.Forms.HashAllControl.InitializeComponent().
tabPageDir
System Windows Forms TabPage IG.Forms.HashAllControl.tabPageDir private
Referenced by IG.Forms.HashAllControl.InitializeComponent().
tabPageAbout
System Windows Forms TabPage IG.Forms.HashAllControl.tabPageAbout private
Referenced by IG.Forms.HashAllControl.InitializeComponent().
hashControl1
HashControl IG.Forms.HashAllControl.hashControl1 private
Referenced by IG.Forms.HashAllControl.InitializeComponent(), and IG.Forms.HashAllControl.tabControl1_KeyUp().
hashDirControl1
IG Forms HashDirControl IG.Forms.HashAllControl.hashDirControl1 private
Referenced by IG.Forms.HashAllControl.InitializeComponent().
hashFormAbout1
IG Forms HashAboutControl IG.Forms.HashAllControl.hashFormAbout1 private
Referenced by IG.Forms.HashAllControl.InitializeComponent().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/Cryptography/HashAllControl.cs
iglib/igforms/Utilities/Cryptography/HashAllControl.Designer.cs