Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLANSY Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLANSY Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLANSY (DLASSQ dlassq, LSAME lsame)
DLANSY ()
double Run (string NORM, string UPLO, int N, double[] A, int offset_a, int LDA, ref double[] WORK, int offset_work)
Private Attributes
DLASSQ _dlassq
LSAME _lsame
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLANSY returns the value of the one norm, or the Frobenius norm, or the infinity norm, or the element of largest absolute value of a real symmetric matrix A.
Description
DLANSY returns the value
DLANSY = (max(abs(A(i,j))), NORM = 'M' or 'm' ((norm1(A), NORM = '1', 'O' or 'o' ((normI(A), NORM = 'I' or 'i' ((normF(A), NORM = 'F', 'f', 'E' or 'e'
where norm1 denotes the one norm of a matrix (maximum column sum), normI denotes the infinity norm of a matrix (maximum row sum) and normF denotes the Frobenius norm of a matrix (square root of sum of squares). Note that max(abs(A(i,j))) is not a consistent matrix norm.
/summary>
Constructor & Destructor Documentation
DLANSY() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLANSY.DLANSY (DLASSQ dlassq, LSAME lsame) inline
DLANSY() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLANSY.DLANSY () inline
Member Function Documentation
Run()
double DotNumerics.LinearAlgebra.CSLapack.DLANSY.Run (string NORM, string UPLO, int N, double[] A, int offset_a, int LDA, ref double[] WORK, int offset_work) inline
Purpose
DLANSY returns the value of the one norm, or the Frobenius norm, or the infinity norm, or the element of largest absolute value of a real symmetric matrix A.
Description
DLANSY returns the value
DLANSY = (max(abs(A(i,j))), NORM = 'M' or 'm' ((norm1(A), NORM = '1', 'O' or 'o' ((normI(A), NORM = 'I' or 'i' ((normF(A), NORM = 'F', 'f', 'E' or 'e'
where norm1 denotes the one norm of a matrix (maximum column sum), normI denotes the infinity norm of a matrix (maximum row sum) and normF denotes the Frobenius norm of a matrix (square root of sum of squares). Note that max(abs(A(i,j))) is not a consistent matrix norm.
/summary>
Parameters
NORM (input) CHARACTER*1 Specifies the value to be returned in DLANSY as described above. /param>
Parameters
UPLO (input) CHARACTER*1 Specifies whether the upper or lower triangular part of the symmetric matrix A is to be referenced. = 'U': Upper triangular part of A is referenced = 'L': Lower triangular part of A is referenced /param>
Parameters
N (input) INTEGER The order of the matrix A. N .GE. 0. When N = 0, DLANSY is set to zero. /param>
Parameters
A (input) DOUBLE PRECISION array, dimension (LDA,N) The symmetric matrix A. If UPLO = 'U', the leading n by n upper triangular part of A contains the upper triangular part of the matrix A, and the strictly lower triangular part of A is not referenced. If UPLO = 'L', the leading n by n lower triangular part of A contains the lower triangular part of the matrix A, and the strictly upper triangular part of A is not referenced. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(N,1). /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (MAX(1,LWORK)), where LWORK .GE. N when NORM = 'I' or '1' or 'O'; otherwise, WORK is not referenced. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLANSY.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASSQ.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLANSY.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYEV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DSYEVD.Run().
Member Data Documentation
_dlassq
DLASSQ DotNumerics.LinearAlgebra.CSLapack.DLANSY._dlassq private
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLANSY._lsame private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLANSY.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLANSY.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLANSY.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLANSY.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlansy.cs