Doc: IGLib EXTENDED: IG.Test.Tasks Class Reference
IG.Test.Tasks Class Reference
Classes
class Test
Static Public Member Functions
static void Run ()
static void Main_TaskBasic ()
static void Main_TaskCancel ()
How to cancel tasks. See: https://msdn.microsoft.com/en-us/library/dd537607%28v=vs.110%29.aspx
static DateTime DoWork ()
static void Main_TaskStatus ()
static void Main_TaskScheduler ()
See: https://msdn.microsoft.com/en-us/library/system.threading.tasks.taskscheduler%28v=vs.110%29.aspx
Static Private Member Functions
static void DoSomeWork1 (int taskNum, CancellationToken ct)
static async Task< int > AccessTheWebAsync (int a, int b)
static void DoSomeWork (int taskNum, CancellationToken ct)
static void Main_TaskContinuation ()
Task continuation example. See: https://msdn.microsoft.com/en-us/library/ee372288%28v=vs.110%29.aspx
Member Function Documentation
Run()
static void IG.Test.Tasks.Run () inline static
References IG.Test.Tasks.Main_TaskBasic().
Main_TaskBasic()
static void IG.Test.Tasks.Main_TaskBasic () inline static
References IG.Test.Tasks.AccessTheWebAsync(), and IG.Test.Tasks.DoSomeWork().
Referenced by IG.Test.Tasks.Run().
DoSomeWork1()
static void IG.Test.Tasks.DoSomeWork1 (int taskNum, CancellationToken ct) inline static private
AccessTheWebAsync()
static async Task<int> IG.Test.Tasks.AccessTheWebAsync (int a, int b) inline static private
Referenced by IG.Test.Tasks.Main_TaskBasic().
Main_TaskCancel()
static void IG.Test.Tasks.Main_TaskCancel () inline static
How to cancel tasks. See: https://msdn.microsoft.com/en-us/library/dd537607%28v=vs.110%29.aspx
References IG.Test.Tasks.DoSomeWork().
DoSomeWork()
static void IG.Test.Tasks.DoSomeWork (int taskNum, CancellationToken ct) inline static private
Referenced by IG.Test.Tasks.Main_TaskBasic(), and IG.Test.Tasks.Main_TaskCancel().
DoWork()
static DateTime IG.Test.Tasks.DoWork () inline static
Referenced by IG.Test.Tasks.Main_TaskContinuation().
Main_TaskContinuation()
static void IG.Test.Tasks.Main_TaskContinuation () inline static private
Task continuation example. See: https://msdn.microsoft.com/en-us/library/ee372288%28v=vs.110%29.aspx
References IG.Test.Tasks.DoWork().
Main_TaskStatus()
static void IG.Test.Tasks.Main_TaskStatus () inline static
Main_TaskScheduler()
static void IG.Test.Tasks.Main_TaskScheduler () inline static
See: https://msdn.microsoft.com/en-us/library/system.threading.tasks.taskscheduler%28v=vs.110%29.aspx
The documentation for this class was generated from the following file:
unittests/Guest_IGTestQuick/Async_Tasks_TAP.cs