Doc: IGLib EXTENDED: NUnit.Agent.NUnitTestAgent Class Reference
NUnit.Agent.NUnitTestAgent Class Reference
Summary description for Program.
Static Public Member Functions
static int Main (string[] args)
The main entry point for the application.
Static Private Attributes
static Guid AgentId
static string AgencyUrl
static ITestAgency Agency
static TcpChannel Channel
Channel used for communications with the agency and with clients
Detailed Description
Summary description for Program.
Member Function Documentation
Main()
static int NUnit.Agent.NUnitTestAgent.Main (string[] args) inline static
The main entry point for the application.
References NUnit.Engine.ServiceContext.Add(), NUnit.Agent.NUnitTestAgent.Agency, NUnit.Agent.NUnitTestAgent.AgencyUrl, NUnit.Agent.NUnitTestAgent.AgentId, NUnit.Agent.NUnitTestAgent.Channel, NUnit.Engine.RuntimeFramework.CurrentFramework, NUnit.Engine.RuntimeFramework.DisplayName, NUnit.Engine.Internal.ServerUtilities.GetTcpChannel(), NUnit.Engine.TestEngine.Initialize(), NUnit.Engine.TestEngine.Services, NUnit.Engine.Agents.RemoteTestAgent.Start(), and NUnit.Engine.Agents.RemoteTestAgent.WaitForStop().
Member Data Documentation
AgentId
Guid NUnit.Agent.NUnitTestAgent.AgentId static private
Referenced by NUnit.Agent.NUnitTestAgent.Main().
AgencyUrl
string NUnit.Agent.NUnitTestAgent.AgencyUrl static private
Referenced by NUnit.Agent.NUnitTestAgent.Main().
Agency
ITestAgency NUnit.Agent.NUnitTestAgent.Agency static private
Referenced by NUnit.Agent.NUnitTestAgent.Main().
Channel
TcpChannel NUnit.Agent.NUnitTestAgent.Channel static private
Channel used for communications with the agency and with clients
Referenced by NUnit.Agent.NUnitTestAgent.Main().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit-agent/Program.cs