Doc: IGLib EXTENDED: AForge.Imaging.Tests.IntegralImageTest Class Reference
AForge.Imaging.Tests.IntegralImageTest Class Reference
Public Member Functions
IntegralImageTest ()
void GetRectangleSumTest (int x1, int y1, int x2, int y2, uint expectedSum)
void GetRectangleSumUnsafeTest (int x1, int y1, int x2, int y2, uint expectedSum)
void GetRectangleSumTest (int x, int y, int radius, uint expectedSum)
void GetRectangleSumUnsafeTest (int x, int y, int radius, uint expectedSum)
void GetRectangleMeanTest (int x1, int y1, int x2, int y2, float expectedMean)
void GetHaarXWavelet (int x, int y, int radius, int expectedValue)
void GetHaarYWavelet (int x, int y, int radius, int expectedValue)
Private Attributes
IntegralImage integralImage = null
Constructor & Destructor Documentation
IntegralImageTest()
AForge.Imaging.Tests.IntegralImageTest.IntegralImageTest () inline
References AForge.Imaging.UnmanagedImage.Create(), AForge.Imaging.IntegralImage.FromBitmap(), AForge.Imaging.Tests.IntegralImageTest.integralImage, and AForge.Imaging.UnmanagedImage.SetPixel().
Member Function Documentation
GetRectangleSumTest() [1/2]
void AForge.Imaging.Tests.IntegralImageTest.GetRectangleSumTest (int x1, int y1, int x2, int y2, uint expectedSum) inline
References AForge.Imaging.IntegralImage.GetRectangleSum(), and AForge.Imaging.Tests.IntegralImageTest.integralImage.
GetRectangleSumUnsafeTest() [1/2]
void AForge.Imaging.Tests.IntegralImageTest.GetRectangleSumUnsafeTest (int x1, int y1, int x2, int y2, uint expectedSum) inline
References AForge.Imaging.IntegralImage.GetRectangleSum(), and AForge.Imaging.Tests.IntegralImageTest.integralImage.
GetRectangleSumTest() [2/2]
void AForge.Imaging.Tests.IntegralImageTest.GetRectangleSumTest (int x, int y, int radius, uint expectedSum) inline
References AForge.Imaging.IntegralImage.GetRectangleSum(), and AForge.Imaging.Tests.IntegralImageTest.integralImage.
GetRectangleSumUnsafeTest() [2/2]
void AForge.Imaging.Tests.IntegralImageTest.GetRectangleSumUnsafeTest (int x, int y, int radius, uint expectedSum) inline
References AForge.Imaging.IntegralImage.GetRectangleSum(), and AForge.Imaging.Tests.IntegralImageTest.integralImage.
GetRectangleMeanTest()
void AForge.Imaging.Tests.IntegralImageTest.GetRectangleMeanTest (int x1, int y1, int x2, int y2, float expectedMean) inline
References AForge.Imaging.IntegralImage.GetRectangleMean(), and AForge.Imaging.Tests.IntegralImageTest.integralImage.
GetHaarXWavelet()
void AForge.Imaging.Tests.IntegralImageTest.GetHaarXWavelet (int x, int y, int radius, int expectedValue) inline
References AForge.Imaging.IntegralImage.GetHaarXWavelet(), and AForge.Imaging.Tests.IntegralImageTest.integralImage.
GetHaarYWavelet()
void AForge.Imaging.Tests.IntegralImageTest.GetHaarYWavelet (int x, int y, int radius, int expectedValue) inline
References AForge.Imaging.IntegralImage.GetHaarYWavelet(), and AForge.Imaging.Tests.IntegralImageTest.integralImage.
Member Data Documentation
integralImage
IntegralImage AForge.Imaging.Tests.IntegralImageTest.integralImage = null private
Referenced by AForge.Imaging.Tests.IntegralImageTest.GetHaarXWavelet(), AForge.Imaging.Tests.IntegralImageTest.GetHaarYWavelet(), AForge.Imaging.Tests.IntegralImageTest.GetRectangleMeanTest(), AForge.Imaging.Tests.IntegralImageTest.GetRectangleSumTest(), AForge.Imaging.Tests.IntegralImageTest.GetRectangleSumUnsafeTest(), and AForge.Imaging.Tests.IntegralImageTest.IntegralImageTest().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Unit Tests/AForge.Imaging.Tests/IntegralImageTest.cs