Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DSTEDC Class Reference
DotNumerics.LinearAlgebra.CSLapack.DSTEDC Class Reference
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DSTEDC (LSAME lsame, ILAENV ilaenv, DLAMCH dlamch, DLANST dlanst, DGEMM dgemm, DLACPY dlacpy, DLAED0 dlaed0, DLASCL dlascl, DLASET dlaset, DLASRT dlasrt, DSTEQR dsteqr, DSTERF dsterf, DSWAP dswap, XERBLA xerbla)
DSTEDC ()
void Run (string COMPZ, int N, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] Z, int offset_z, int LDZ, ref double[] WORK, int offset_work, int LWORK, ref int[] IWORK, int offset_iwork, int LIWORK, ref int INFO)
Private Attributes
LSAME _lsame
ILAENV _ilaenv
DLAMCH _dlamch
DLANST _dlanst
DGEMM _dgemm
DLACPY _dlacpy
DLAED0 _dlaed0
DLASCL _dlascl
DLASET _dlaset
DLASRT _dlasrt
DSTEQR _dsteqr
DSTERF _dsterf
DSWAP _dswap
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
const double TWO = 2.0E0
Detailed Description
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DSTEDC computes all eigenvalues and, optionally, eigenvectors of a symmetric tridiagonal matrix using the divide and conquer method. The eigenvectors of a full or band real symmetric matrix can also be found if DSYTRD or DSPTRD or DSBTRD has been used to reduce this matrix to tridiagonal form.
This code makes very mild assumptions about floating point arithmetic. It will work on machines with a guard digit in add/subtract, or on those binary machines without guard digits which subtract like the Cray X-MP, Cray Y-MP, Cray C-90, or Cray-2. It could conceivably fail on hexadecimal or decimal machines without guard digits, but we know of none. See DLAED3 for details.
/summary>
Constructor & Destructor Documentation
DSTEDC() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DSTEDC.DSTEDC (LSAME lsame, ILAENV ilaenv, DLAMCH dlamch, DLANST dlanst, DGEMM dgemm, DLACPY dlacpy, DLAED0 dlaed0, DLASCL dlascl, DLASET dlaset, DLASRT dlasrt, DSTEQR dsteqr, DSTERF dsterf, DSWAP dswap, XERBLA xerbla) inline
DSTEDC() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DSTEDC.DSTEDC () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DSTEDC.Run (string COMPZ, int N, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] Z, int offset_z, int LDZ, ref double[] WORK, int offset_work, int LWORK, ref int[] IWORK, int offset_iwork, int LIWORK, ref int INFO) inline
Purpose
DSTEDC computes all eigenvalues and, optionally, eigenvectors of a symmetric tridiagonal matrix using the divide and conquer method. The eigenvectors of a full or band real symmetric matrix can also be found if DSYTRD or DSPTRD or DSBTRD has been used to reduce this matrix to tridiagonal form.
This code makes very mild assumptions about floating point arithmetic. It will work on machines with a guard digit in add/subtract, or on those binary machines without guard digits which subtract like the Cray X-MP, Cray Y-MP, Cray C-90, or Cray-2. It could conceivably fail on hexadecimal or decimal machines without guard digits, but we know of none. See DLAED3 for details.
/summary>
Parameters
COMPZ (input) CHARACTER*1 = 'N': Compute eigenvalues only. = 'I': Compute eigenvectors of tridiagonal matrix also. = 'V': Compute eigenvectors of original dense symmetric matrix also. On entry, Z contains the orthogonal matrix used to reduce the original matrix to tridiagonal form. /param>
Parameters
N (input) INTEGER The dimension of the symmetric tridiagonal matrix. N .GE. 0. /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension (N) On entry, the diagonal elements of the tridiagonal matrix. On exit, if INFO = 0, the eigenvalues in ascending order. /param>
Parameters
E (input/output) DOUBLE PRECISION array, dimension (N-1) On entry, the subdiagonal elements of the tridiagonal matrix. On exit, E has been destroyed. /param>
Parameters
Z (input/output) DOUBLE PRECISION array, dimension (LDZ,N) On entry, if COMPZ = 'V', then Z contains the orthogonal matrix used in the reduction to tridiagonal form. On exit, if INFO = 0, then if COMPZ = 'V', Z contains the orthonormal eigenvectors of the original symmetric matrix, and if COMPZ = 'I', Z contains the orthonormal eigenvectors of the symmetric tridiagonal matrix. If COMPZ = 'N', then Z is not referenced. /param>
Parameters
LDZ (input) INTEGER The leading dimension of the array Z. LDZ .GE. 1. If eigenvectors are desired, then LDZ .GE. max(1,N). /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (LWORK) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. If COMPZ = 'N' or N .LE. 1 then LWORK must be at least 1. If COMPZ = 'V' and N .GT. 1 then LWORK must be at least (1 + 3*N + 2*N*lg N + 3*N**2), where lg(N) = smallest integer k such that 2**k .GE. N. If COMPZ = 'I' and N .GT. 1 then LWORK must be at least (1 + 4*N + N**2). Note that for COMPZ = 'I' or 'V', then if N is less than or equal to the minimum divide size, usually 25, then LWORK need only be max(1,2*(N-1)).
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
IWORK (workspace/output) INTEGER array, dimension (MAX(1,LIWORK)) On exit, if INFO = 0, IWORK(1) returns the optimal LIWORK. /param>
Parameters
LIWORK (input) INTEGER The dimension of the array IWORK. If COMPZ = 'N' or N .LE. 1 then LIWORK must be at least 1. If COMPZ = 'V' and N .GT. 1 then LIWORK must be at least (6 + 6*N + 5*N*lg N). If COMPZ = 'I' and N .GT. 1 then LIWORK must be at least (3 + 5*N). Note that for COMPZ = 'I' or 'V', then if N is less than or equal to the minimum divide size, usually 25, then LIWORK need only be 1.
If LIWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the IWORK array, returns this value as the first entry of the IWORK array, and no error message related to LIWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. .GT. 0: The algorithm failed to compute an eigenvalue while working on the submatrix lying in rows and columns INFO/(N+1) through mod(INFO,N+1). /param>
References DotNumerics.FortranLibrary.FortranLib.Mod(), DotNumerics.LinearAlgebra.CSLapack.DSTEDC.ONE, DotNumerics.LinearAlgebra.CSLapack.DSWAP.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASRT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASET.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTERF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANST.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED0.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEDC.TWO, and DotNumerics.LinearAlgebra.CSLapack.DSTEDC.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSBEVD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DSYEVD.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DSTEDC._lsame private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DSTEDC._ilaenv private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DSTEDC._dlamch private
_dlanst
DLANST DotNumerics.LinearAlgebra.CSLapack.DSTEDC._dlanst private
_dgemm
DGEMM DotNumerics.LinearAlgebra.CSLapack.DSTEDC._dgemm private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DSTEDC._dlacpy private
_dlaed0
DLAED0 DotNumerics.LinearAlgebra.CSLapack.DSTEDC._dlaed0 private
_dlascl
DLASCL DotNumerics.LinearAlgebra.CSLapack.DSTEDC._dlascl private
_dlaset
DLASET DotNumerics.LinearAlgebra.CSLapack.DSTEDC._dlaset private
_dlasrt
DLASRT DotNumerics.LinearAlgebra.CSLapack.DSTEDC._dlasrt private
_dsteqr
DSTEQR DotNumerics.LinearAlgebra.CSLapack.DSTEDC._dsteqr private
_dsterf
DSTERF DotNumerics.LinearAlgebra.CSLapack.DSTEDC._dsterf private
_dswap
DSWAP DotNumerics.LinearAlgebra.CSLapack.DSTEDC._dswap private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DSTEDC._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DSTEDC.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTEDC.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DSTEDC.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTEDC.Run().
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DSTEDC.TWO = 2.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTEDC.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dstedc.cs