Doc: IGLib EXTENDED: CShell.Modules.Workspace.ViewModels.FolderViewModel Class Reference
CShell.Modules.Workspace.ViewModels.FolderViewModel Class Reference
Public Member Functions
FolderViewModel (DirectoryInfo info, CShell.Workspace workspace)
IEnumerable< IResult > AddNewFile ()
IEnumerable< IResult > AddNewFolder ()
IEnumerable< IResult > Delete ()
IEnumerable< IResult > Rename ()
Public Member Functions inherited from CShell.Modules.Workspace.ViewModels.TreeViewModel
IEnumerable< TreeViewModel > GetAllChildren ()
Recursively returns all children in the tree.
void Dispose ()
Static Public Member Functions
static string WildcardToRegex (string pattern)
Protected Member Functions
FolderViewModel (string path, CShell.Workspace workspace)
BindableCollection< TreeViewModel > LoadChildren ()
override void EditModeFinished ()
Protected Member Functions inherited from CShell.Modules.Workspace.ViewModels.TreeViewModel
virtual void Dispose (bool disposing)
Protected Attributes
DirectoryInfo directoryInfo
Properties
override Uri IconSource [get]
string RelativePath [get]
string ToolTip [get]
override IObservableCollection< TreeViewModel >?? Children [get]
Properties inherited from CShell.Modules.Workspace.ViewModels.TreeViewModel
virtual string DisplayName [get, set]
virtual Uri IconSource [get]
virtual IObservableCollection< TreeViewModel > Children [get]
bool IsSelected [get, set]
bool IsExpanded [get, set]
bool IsEditable [get, set]
virtual bool IsInEditMode [get, set]
Private Attributes
readonly CShell.Workspace workspace
BindableCollection< TreeViewModel > children
Constructor & Destructor Documentation
FolderViewModel() [1/2]
CShell.Modules.Workspace.ViewModels.FolderViewModel.FolderViewModel (string path, CShell.Workspace workspace) inline protected
Referenced by CShell.Modules.Workspace.ViewModels.FolderViewModel.LoadChildren().
FolderViewModel() [2/2]
CShell.Modules.Workspace.ViewModels.FolderViewModel.FolderViewModel (DirectoryInfo info, CShell.Workspace workspace) inline
References CShell.Modules.Workspace.ViewModels.FolderViewModel.directoryInfo, CShell.Modules.Workspace.ViewModels.TreeViewModel.DisplayName, CShell.Modules.Workspace.ViewModels.TreeViewModel.IsEditable, and CShell.Modules.Workspace.ViewModels.FolderViewModel.workspace.
Member Function Documentation
LoadChildren()
BindableCollection<TreeViewModel> CShell.Modules.Workspace.ViewModels.FolderViewModel.LoadChildren () inline protected
References CShell.Modules.Workspace.ViewModels.FolderViewModel.directoryInfo, CShell.Workspace.Filter, CShell.Modules.Workspace.ViewModels.FolderViewModel.FolderViewModel(), CShell.Modules.Workspace.ViewModels.FolderViewModel.WildcardToRegex(), and CShell.Modules.Workspace.ViewModels.FolderViewModel.workspace.
Referenced by CShell.Modules.Workspace.ViewModels.RootFolderViewModel.OnChanged(), CShell.Modules.Workspace.ViewModels.RootFolderViewModel.OnRenamed(), and CShell.Modules.Workspace.ViewModels.RootFolderViewModel.WorkspaceOnPropertyChanged().
AddNewFile()
IEnumerable<IResult> CShell.Modules.Workspace.ViewModels.FolderViewModel.AddNewFile () inline
References CShell.Constants.DefaultExtension, CShell.Framework.Results.Show.Dialog(), CShell.Modules.Workspace.ViewModels.FolderViewModel.directoryInfo, and CShell.Constants.FileTypes.
Referenced by CShell.Modules.Workspace.Module.AddNewFile().
AddNewFolder()
IEnumerable<IResult> CShell.Modules.Workspace.ViewModels.FolderViewModel.AddNewFolder () inline
References CShell.Modules.Workspace.ViewModels.FolderViewModel.directoryInfo, CShell.Framework.Results.Show.FolderDialog(), and CShell.Framework.Results.ShowFolderDialogResult.SelectedFolder.
Referenced by CShell.Modules.Workspace.Module.AddNewFolder().
Delete()
IEnumerable<IResult> CShell.Modules.Workspace.ViewModels.FolderViewModel.Delete () inline
References CShell.Modules.Workspace.ViewModels.FolderViewModel.directoryInfo, and CShell.Modules.Workspace.ViewModels.TreeViewModel.IsEditable.
Rename()
IEnumerable<IResult> CShell.Modules.Workspace.ViewModels.FolderViewModel.Rename () inline
References CShell.Modules.Workspace.ViewModels.TreeViewModel.IsEditable, and CShell.Modules.Workspace.ViewModels.TreeViewModel.IsInEditMode.
EditModeFinished()
override void CShell.Modules.Workspace.ViewModels.FolderViewModel.EditModeFinished () inline protected virtual
Reimplemented from CShell.Modules.Workspace.ViewModels.TreeViewModel.
References CShell.Modules.Workspace.ViewModels.FolderViewModel.directoryInfo, and CShell.Modules.Workspace.ViewModels.TreeViewModel.DisplayName.
WildcardToRegex()
static string CShell.Modules.Workspace.ViewModels.FolderViewModel.WildcardToRegex (string pattern) inline static
Referenced by CShell.Modules.Workspace.ViewModels.FolderViewModel.LoadChildren().
Member Data Documentation
directoryInfo
DirectoryInfo CShell.Modules.Workspace.ViewModels.FolderViewModel.directoryInfo protected
Referenced by CShell.Modules.Workspace.ViewModels.FolderViewModel.AddNewFile(), CShell.Modules.Workspace.ViewModels.FolderViewModel.AddNewFolder(), CShell.Modules.Workspace.ViewModels.FolderViewModel.Delete(), CShell.Modules.Workspace.ViewModels.FolderViewModel.EditModeFinished(), CShell.Modules.Workspace.ViewModels.FolderViewModel.FolderViewModel(), CShell.Modules.Workspace.ViewModels.RootFolderViewModel.Initialize(), CShell.Modules.Workspace.ViewModels.FolderViewModel.LoadChildren(), CShell.Modules.Workspace.ViewModels.RootFolderViewModel.RootFolderViewModel(), and CShell.Modules.Workspace.ViewModels.RootFolderViewModel.WorkspaceOnPropertyChanged().
workspace
readonly CShell.Workspace CShell.Modules.Workspace.ViewModels.FolderViewModel.workspace private
Referenced by CShell.Modules.Workspace.ViewModels.FolderViewModel.FolderViewModel(), and CShell.Modules.Workspace.ViewModels.FolderViewModel.LoadChildren().
children
BindableCollection<TreeViewModel> CShell.Modules.Workspace.ViewModels.FolderViewModel.children private
Property Documentation
IconSource
override Uri CShell.Modules.Workspace.ViewModels.FolderViewModel.IconSource get
RelativePath
string CShell.Modules.Workspace.ViewModels.FolderViewModel.RelativePath get
Referenced by CShell.Modules.Workspace.ViewModels.RootFolderViewModel.WorkspaceOnPropertyChanged().
ToolTip
string CShell.Modules.Workspace.ViewModels.FolderViewModel.ToolTip get
Referenced by CShell.Modules.Workspace.ViewModels.RootFolderViewModel.WorkspaceOnPropertyChanged().
Children
override IObservableCollection<TreeViewModel>?? CShell.Modules.Workspace.ViewModels.FolderViewModel.Children get
Referenced by CShell.Modules.Workspace.ViewModels.RootFolderViewModel.OnChanged(), CShell.Modules.Workspace.ViewModels.RootFolderViewModel.OnRenamed(), and CShell.Modules.Workspace.ViewModels.RootFolderViewModel.WorkspaceOnPropertyChanged().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Workspace/ViewModels/FolderViewModel.cs