Doc: IGLib EXTENDED: AForge.Imaging.Filters.SISThreshold Class Reference
AForge.Imaging.Filters.SISThreshold Class Reference
Threshold using Simple Image Statistics (SIS).
Public Member Functions
SISThreshold ()
Initializes a new instance of the SISThreshold class.
int CalculateThreshold (Bitmap image, Rectangle rect)
Calculate binarization threshold for the given image.
int CalculateThreshold (BitmapData image, Rectangle rect)
Calculate binarization threshold for the given image.
int CalculateThreshold (UnmanagedImage image, Rectangle rect)
Calculate binarization threshold for the given image.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image, Rectangle rect)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
int ThresholdValue [get]
Threshold value.
Properties inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
Threshold thresholdFilter = new Threshold()
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Threshold using Simple Image Statistics (SIS).
The filter performs image thresholding calculating threshold automatically using simple image statistics method. For each pixel:
two gradients are calculated - ex = |I(x + 1, y) - I(x - 1, y)| and |I(x, y + 1) - I(x, y - 1)|;
weight is calculated as maximum of two gradients;
sum of weights is updated (weightTotal += weight);
sum of weighted pixel values is updated (total += weight * I(x, y)).
The result threshold is calculated as sum of weighted pixel values divided by sum of weight.
The filter accepts 8 bpp grayscale images for processing.
Sample usage:
// create filter
SISThreshold filter = new SISThreshold();
// apply the filter
filter.ApplyInPlace(image);
Initial image:
Result image (calculated threshold is 127):
See also
IterativeThreshold, OtsuThreshold
Constructor & Destructor Documentation
SISThreshold()
AForge.Imaging.Filters.SISThreshold.SISThreshold () inline
Initializes a new instance of the SISThreshold class.
References AForge.Imaging.Filters.SISThreshold.formatTranslations.
Member Function Documentation
CalculateThreshold() [1/3]
int AForge.Imaging.Filters.SISThreshold.CalculateThreshold (Bitmap image, Rectangle rect) inline
Calculate binarization threshold for the given image.
Parameters
image Image to calculate binarization threshold for.
rect Rectangle to calculate binarization threshold for.
Returns
Returns binarization threshold.
The method is used to calculate binarization threshold only. The threshold later may be applied to the image using Threshold image processing filter.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported by the routine. It should be 8 bpp grayscale (indexed) image.
References AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.Filters.SISThreshold.CalculateThreshold(), and AForge.Imaging.Filters.SISThreshold.ProcessFilter().
CalculateThreshold() [2/3]
int AForge.Imaging.Filters.SISThreshold.CalculateThreshold (BitmapData image, Rectangle rect) inline
Calculate binarization threshold for the given image.
Parameters
image Image to calculate binarization threshold for.
rect Rectangle to calculate binarization threshold for.
Returns
Returns binarization threshold.
The method is used to calculate binarization threshold only. The threshold later may be applied to the image using Threshold image processing filter.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported by the routine. It should be 8 bpp grayscale (indexed) image.
References AForge.Imaging.Filters.SISThreshold.CalculateThreshold().
CalculateThreshold() [3/3]
int AForge.Imaging.Filters.SISThreshold.CalculateThreshold (UnmanagedImage image, Rectangle rect) inline
Calculate binarization threshold for the given image.
Parameters
image Image to calculate binarization threshold for.
rect Rectangle to calculate binarization threshold for.
Returns
Returns binarization threshold.
The method is used to calculate binarization threshold only. The threshold later may be applied to the image using Threshold image processing filter.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported by the routine. It should be 8 bpp grayscale (indexed) image.
References AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, and AForge.Imaging.UnmanagedImage.Stride.
ProcessFilter()
override unsafe void AForge.Imaging.Filters.SISThreshold.ProcessFilter (UnmanagedImage image, Rectangle rect) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
rect Image rectangle for processing by the filter.
Implements AForge.Imaging.Filters.BaseInPlacePartialFilter.
References AForge.Imaging.Filters.BaseInPlacePartialFilter.ApplyInPlace(), AForge.Imaging.Filters.SISThreshold.CalculateThreshold(), AForge.Imaging.Filters.SISThreshold.thresholdFilter, and AForge.Imaging.Filters.Threshold.ThresholdValue.
Member Data Documentation
thresholdFilter
Threshold AForge.Imaging.Filters.SISThreshold.thresholdFilter = new Threshold() private
Referenced by AForge.Imaging.Filters.SISThreshold.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.SISThreshold.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.SISThreshold.SISThreshold().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.SISThreshold.FormatTranslations get
Format translations dictionary.
ThresholdValue
int AForge.Imaging.Filters.SISThreshold.ThresholdValue get
Threshold value.
The property is read only and represents the value, which was automaticaly calculated using image statistics.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Adaptive Binarization/SISThreshold.cs