Doc: IGLib EXTENDED: MotionDetectorSample.MotionRegionsForm Class Reference
MotionDetectorSample.MotionRegionsForm Class Reference
Public Member Functions
MotionRegionsForm ()
Protected Member Functions
override void OnLoad (EventArgs e)
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
Bitmap VideoFrame [set]
Rectangle[] MotionRectangles [get, set]
Private Member Functions
void rectangleButton_Click (object sender, EventArgs e)
void defineRegionsControl_NewRectangleHandler (object sender, Rectangle rect)
void clearButton_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
DefineRegionsControl defineRegionsControl
System.Windows.Forms.ToolStrip toolStrip
System.Windows.Forms.Button okButton
System.Windows.Forms.Button cancelButton
System.Windows.Forms.ToolStripButton rectangleButton
System.Windows.Forms.ToolStripSeparator toolStripSeparator1
System.Windows.Forms.ToolStripButton clearButton
Constructor & Destructor Documentation
MotionRegionsForm()
MotionDetectorSample.MotionRegionsForm.MotionRegionsForm () inline
References MotionDetectorSample.MotionRegionsForm.defineRegionsControl, MotionDetectorSample.MotionRegionsForm.defineRegionsControl_NewRectangleHandler(), MotionDetectorSample.MotionRegionsForm.InitializeComponent(), MotionDetectorSample.NewRectangleHandler(), and MotionDetectorSample.DefineRegionsControl.OnNewRectangle.
Member Function Documentation
OnLoad()
override void MotionDetectorSample.MotionRegionsForm.OnLoad (EventArgs e) inline protected
References MotionDetectorSample.DefineRegionsControl.BackgroundImage, and MotionDetectorSample.MotionRegionsForm.defineRegionsControl.
rectangleButton_Click()
void MotionDetectorSample.MotionRegionsForm.rectangleButton_Click (object sender, EventArgs e) inline private
References MotionDetectorSample.MotionRegionsForm.defineRegionsControl, MotionDetectorSample.DefineRegionsControl.DrawingMode, and MotionDetectorSample.MotionRegionsForm.rectangleButton.
Referenced by MotionDetectorSample.MotionRegionsForm.InitializeComponent().
defineRegionsControl_NewRectangleHandler()
void MotionDetectorSample.MotionRegionsForm.defineRegionsControl_NewRectangleHandler (object sender, Rectangle rect) inline private
References MotionDetectorSample.MotionRegionsForm.rectangleButton.
Referenced by MotionDetectorSample.MotionRegionsForm.MotionRegionsForm().
clearButton_Click()
void MotionDetectorSample.MotionRegionsForm.clearButton_Click (object sender, EventArgs e) inline private
References MotionDetectorSample.MotionRegionsForm.defineRegionsControl, and MotionDetectorSample.DefineRegionsControl.RemoveAllRegions().
Referenced by MotionDetectorSample.MotionRegionsForm.InitializeComponent().
Dispose()
override void MotionDetectorSample.MotionRegionsForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References MotionDetectorSample.MotionRegionsForm.components.
InitializeComponent()
void MotionDetectorSample.MotionRegionsForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References MotionDetectorSample.DefineRegionsControl.BackgroundImage, MotionDetectorSample.MotionRegionsForm.cancelButton, MotionDetectorSample.MotionRegionsForm.clearButton, MotionDetectorSample.MotionRegionsForm.clearButton_Click(), MotionDetectorSample.MotionRegionsForm.defineRegionsControl, MotionDetectorSample.DefineRegionsControl.DrawingMode, MotionDetectorSample.MotionRegionsForm.okButton, MotionDetectorSample.MotionRegionsForm.rectangleButton, MotionDetectorSample.MotionRegionsForm.rectangleButton_Click(), MotionDetectorSample.MotionRegionsForm.toolStrip, and MotionDetectorSample.MotionRegionsForm.toolStripSeparator1.
Referenced by MotionDetectorSample.MotionRegionsForm.MotionRegionsForm().
Member Data Documentation
components
System.ComponentModel.IContainer MotionDetectorSample.MotionRegionsForm.components = null private
Required designer variable.
Referenced by MotionDetectorSample.MotionRegionsForm.Dispose().
defineRegionsControl
DefineRegionsControl MotionDetectorSample.MotionRegionsForm.defineRegionsControl private
Referenced by MotionDetectorSample.MotionRegionsForm.clearButton_Click(), MotionDetectorSample.MotionRegionsForm.InitializeComponent(), MotionDetectorSample.MotionRegionsForm.MotionRegionsForm(), MotionDetectorSample.MotionRegionsForm.OnLoad(), and MotionDetectorSample.MotionRegionsForm.rectangleButton_Click().
toolStrip
System.Windows.Forms.ToolStrip MotionDetectorSample.MotionRegionsForm.toolStrip private
Referenced by MotionDetectorSample.MotionRegionsForm.InitializeComponent().
okButton
System.Windows.Forms.Button MotionDetectorSample.MotionRegionsForm.okButton private
Referenced by MotionDetectorSample.MotionRegionsForm.InitializeComponent().
cancelButton
System.Windows.Forms.Button MotionDetectorSample.MotionRegionsForm.cancelButton private
Referenced by MotionDetectorSample.MotionRegionsForm.InitializeComponent().
rectangleButton
System.Windows.Forms.ToolStripButton MotionDetectorSample.MotionRegionsForm.rectangleButton private
Referenced by MotionDetectorSample.MotionRegionsForm.defineRegionsControl_NewRectangleHandler(), MotionDetectorSample.MotionRegionsForm.InitializeComponent(), and MotionDetectorSample.MotionRegionsForm.rectangleButton_Click().
toolStripSeparator1
System.Windows.Forms.ToolStripSeparator MotionDetectorSample.MotionRegionsForm.toolStripSeparator1 private
Referenced by MotionDetectorSample.MotionRegionsForm.InitializeComponent().
clearButton
System.Windows.Forms.ToolStripButton MotionDetectorSample.MotionRegionsForm.clearButton private
Referenced by MotionDetectorSample.MotionRegionsForm.InitializeComponent().
Property Documentation
VideoFrame
Bitmap MotionDetectorSample.MotionRegionsForm.VideoFrame set
Referenced by MotionDetectorSample.MainForm.defineMotionregionsToolStripMenuItem_Click().
MotionRectangles
Rectangle [] MotionDetectorSample.MotionRegionsForm.MotionRectangles get set
Referenced by MotionDetectorSample.MainForm.defineMotionregionsToolStripMenuItem_Click().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Vision/MotionDetector/MotionRegionsForm.cs
shelldev/lib_ann/aforge.net/Samples/Vision/MotionDetector/MotionRegionsForm.Designer.cs