Doc: IGLib EXTENDED: AForge.Imaging.Filters.LevelsLinear Class Reference
AForge.Imaging.Filters.LevelsLinear Class Reference
Linear correction of RGB channels.
Public Member Functions
LevelsLinear ()
Initializes a new instance of the LevelsLinear class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image, Rectangle rect)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
IntRange InRed [get, set]
Red component's input range.
IntRange InGreen [get, set]
Green component's input range.
IntRange InBlue [get, set]
Blue component's input range.
IntRange InGray [get, set]
Gray component's input range.
IntRange Input [set]
Input range for RGB components.
IntRange OutRed [get, set]
Red component's output range.
IntRange OutGreen [get, set]
Green component's output range.
IntRange OutBlue [get, set]
Blue component's output range.
IntRange OutGray [get, set]
Gray component's output range.
IntRange Output [set]
Output range for RGB components.
Properties inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Member Functions
void CalculateMap (IntRange inRange, IntRange outRange, byte[] map)
Calculate conversion map.
Private Attributes
IntRange inRed = new IntRange(0, 255)
IntRange inGreen = new IntRange(0, 255)
IntRange inBlue = new IntRange(0, 255)
IntRange outRed = new IntRange(0, 255)
IntRange outGreen = new IntRange(0, 255)
IntRange outBlue = new IntRange(0, 255)
byte[] mapRed = new byte[256]
byte[] mapGreen = new byte[256]
byte[] mapBlue = new byte[256]
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Linear correction of RGB channels.
The filter performs linear correction of RGB channels by mapping specified channels' input ranges to output ranges. It is similar to the ColorRemapping, but the remapping is linear.
The filter accepts 8 bpp grayscale and 24/32 bpp color images for processing.
Sample usage:
// create filter
LevelsLinear filter = new LevelsLinear();
// set ranges
filter.InRed   = new IntRange(30, 230);
filter.InGreen = new IntRange(50, 240);
filter.InBlue  = new IntRange(10, 210);
// apply the filter
filter.ApplyInPlace(image);
Initial image:
Result image:
See also
HSLLinear, YCbCrLinear
Constructor & Destructor Documentation
LevelsLinear()
AForge.Imaging.Filters.LevelsLinear.LevelsLinear () inline
Initializes a new instance of the LevelsLinear class.
References AForge.Imaging.Filters.LevelsLinear.CalculateMap(), AForge.Imaging.Filters.LevelsLinear.formatTranslations, AForge.Imaging.Filters.LevelsLinear.inBlue, AForge.Imaging.Filters.LevelsLinear.inGreen, AForge.Imaging.Filters.LevelsLinear.inRed, AForge.Imaging.Filters.LevelsLinear.mapBlue, AForge.Imaging.Filters.LevelsLinear.mapGreen, AForge.Imaging.Filters.LevelsLinear.mapRed, AForge.Imaging.Filters.LevelsLinear.outBlue, AForge.Imaging.Filters.LevelsLinear.outGreen, and AForge.Imaging.Filters.LevelsLinear.outRed.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.LevelsLinear.ProcessFilter (UnmanagedImage image, Rectangle rect) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
rect Image rectangle for processing by the filter.
Implements AForge.Imaging.Filters.BaseInPlacePartialFilter.
References AForge.Imaging.RGB.B, AForge.Imaging.RGB.G, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.Filters.LevelsLinear.mapBlue, AForge.Imaging.Filters.LevelsLinear.mapGreen, AForge.Imaging.Filters.LevelsLinear.mapRed, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, and AForge.Imaging.UnmanagedImage.Stride.
CalculateMap()
void AForge.Imaging.Filters.LevelsLinear.CalculateMap (IntRange inRange, IntRange outRange, byte[] map) inline private
Calculate conversion map.
Parameters
inRange Input range.
outRange Output range.
map Conversion map.
References AForge.IntRange.Max, and AForge.IntRange.Min.
Referenced by AForge.Imaging.Filters.LevelsLinear.LevelsLinear().
Member Data Documentation
inRed
IntRange AForge.Imaging.Filters.LevelsLinear.inRed = new IntRange(0, 255) private
Referenced by AForge.Imaging.Filters.LevelsLinear.LevelsLinear().
inGreen
IntRange AForge.Imaging.Filters.LevelsLinear.inGreen = new IntRange(0, 255) private
Referenced by AForge.Imaging.Filters.LevelsLinear.LevelsLinear().
inBlue
IntRange AForge.Imaging.Filters.LevelsLinear.inBlue = new IntRange(0, 255) private
Referenced by AForge.Imaging.Filters.LevelsLinear.LevelsLinear().
outRed
IntRange AForge.Imaging.Filters.LevelsLinear.outRed = new IntRange(0, 255) private
Referenced by AForge.Imaging.Filters.LevelsLinear.LevelsLinear().
outGreen
IntRange AForge.Imaging.Filters.LevelsLinear.outGreen = new IntRange(0, 255) private
Referenced by AForge.Imaging.Filters.LevelsLinear.LevelsLinear().
outBlue
IntRange AForge.Imaging.Filters.LevelsLinear.outBlue = new IntRange(0, 255) private
Referenced by AForge.Imaging.Filters.LevelsLinear.LevelsLinear().
mapRed
byte [] AForge.Imaging.Filters.LevelsLinear.mapRed = new byte[256] private
Referenced by AForge.Imaging.Filters.LevelsLinear.LevelsLinear(), and AForge.Imaging.Filters.LevelsLinear.ProcessFilter().
mapGreen
byte [] AForge.Imaging.Filters.LevelsLinear.mapGreen = new byte[256] private
Referenced by AForge.Imaging.Filters.LevelsLinear.LevelsLinear(), and AForge.Imaging.Filters.LevelsLinear.ProcessFilter().
mapBlue
byte [] AForge.Imaging.Filters.LevelsLinear.mapBlue = new byte[256] private
Referenced by AForge.Imaging.Filters.LevelsLinear.LevelsLinear(), and AForge.Imaging.Filters.LevelsLinear.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.LevelsLinear.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.LevelsLinear.LevelsLinear().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.LevelsLinear.FormatTranslations get
Format translations dictionary.
InRed
IntRange AForge.Imaging.Filters.LevelsLinear.InRed get set
Red component's input range.
Referenced by AForge.Imaging.Filters.ContrastStretch.ProcessFilter(), and FiltersDemo.MainForm.rgbLinearFiltersItem_Click().
InGreen
IntRange AForge.Imaging.Filters.LevelsLinear.InGreen get set
Green component's input range.
Referenced by AForge.Imaging.Filters.ContrastStretch.ProcessFilter(), and FiltersDemo.MainForm.rgbLinearFiltersItem_Click().
InBlue
IntRange AForge.Imaging.Filters.LevelsLinear.InBlue get set
Blue component's input range.
Referenced by AForge.Imaging.Filters.ContrastStretch.ProcessFilter(), and FiltersDemo.MainForm.rgbLinearFiltersItem_Click().
InGray
IntRange AForge.Imaging.Filters.LevelsLinear.InGray get set
Gray component's input range.
Referenced by AForge.Imaging.Filters.ContrastStretch.ProcessFilter().
Input
IntRange AForge.Imaging.Filters.LevelsLinear.Input set
Input range for RGB components.
The property allows to set red, green and blue input ranges to the same value.
OutRed
IntRange AForge.Imaging.Filters.LevelsLinear.OutRed get set
Red component's output range.
OutGreen
IntRange AForge.Imaging.Filters.LevelsLinear.OutGreen get set
Green component's output range.
OutBlue
IntRange AForge.Imaging.Filters.LevelsLinear.OutBlue get set
Blue component's output range.
OutGray
IntRange AForge.Imaging.Filters.LevelsLinear.OutGray get set
Gray component's output range.
Output
IntRange AForge.Imaging.Filters.LevelsLinear.Output set
Output range for RGB components.
The property allows to set red, green and blue output ranges to the same value.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Color Filters/LevelsLinear.cs