Doc: IGLib EXTENDED: alglib.studentttests Class Reference
alglib.studentttests Class Reference
Static Public Member Functions
static void studentttest1 (double[] x, int n, double mean, ref double bothtails, ref double lefttail, ref double righttail)
static void studentttest2 (double[] x, int n, double[] y, int m, ref double bothtails, ref double lefttail, ref double righttail)
static void unequalvariancettest (double[] x, int n, double[] y, int m, ref double bothtails, ref double lefttail, ref double righttail)
static void studentttest1 (double[] x, int n, double mean, ref double bothtails, ref double lefttail, ref double righttail)
static void studentttest2 (double[] x, int n, double[] y, int m, ref double bothtails, ref double lefttail, ref double righttail)
static void unequalvariancettest (double[] x, int n, double[] y, int m, ref double bothtails, ref double lefttail, ref double righttail)
Member Function Documentation
studentttest1() [1/2]
static void alglib.studentttests.studentttest1 (double[] x, int n, double mean, ref double bothtails, ref double lefttail, ref double righttail) inline static
References alglib.math.sqr(), and alglib.studenttdistr.studenttdistribution().
Referenced by alglib.studentttest1(), alglib.teststudentttestsunit.teststudentttests(), and alglib.studentttests.unequalvariancettest().
studentttest2() [1/2]
static void alglib.studentttests.studentttest2 (double[] x, int n, double[] y, int m, ref double bothtails, ref double lefttail, ref double righttail) inline static
References alglib.math.sqr(), and alglib.studenttdistr.studenttdistribution().
Referenced by alglib.studentttest2(), and alglib.teststudentttestsunit.teststudentttests().
unequalvariancettest() [1/2]
static void alglib.studentttests.unequalvariancettest (double[] x, int n, double[] y, int m, ref double bothtails, ref double lefttail, ref double righttail) inline static
References alglib.ibetaf.incompletebeta(), and alglib.math.sqr().
Referenced by alglib.teststudentttestsunit.teststudentttests(), and alglib.unequalvariancettest().
studentttest1() [2/2]
static void alglib.studentttests.studentttest1 (double[] x, int n, double mean, ref double bothtails, ref double lefttail, ref double righttail) inline static
References alglib.math.sqr(), and alglib.studenttdistr.studenttdistribution().
studentttest2() [2/2]
static void alglib.studentttests.studentttest2 (double[] x, int n, double[] y, int m, ref double bothtails, ref double lefttail, ref double righttail) inline static
References alglib.math.sqr(), and alglib.studenttdistr.studenttdistribution().
unequalvariancettest() [2/2]
static void alglib.studentttests.unequalvariancettest (double[] x, int n, double[] y, int m, ref double bothtails, ref double lefttail, ref double righttail) inline static
References alglib.ibetaf.incompletebeta(), alglib.math.sqr(), and alglib.studentttests.studentttest1().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/statistics.cs