Doc: IGLib EXTENDED: NUnit.Framework.Tests.Constraints.ToleranceTests Class Reference
NUnit.Framework.Tests.Constraints.ToleranceTests Class Reference
Public Member Functions
void TearDown ()
void TestGlobalDefaultTolerance_Success ()
void TestGlobalDefaultTolerance_Failure ()
void TestToleranceDefault ()
void TestToleranceExact ()
void TestWithinCanOnlyBeUsedOnce ()
void TestModesCanOnlyBeUsedOnce ()
void TestNumericToleranceRequired ()
void TestModeMustFollowTolerance ()
Private Attributes
NUnitEqualityComparer _comparer
Member Function Documentation
TearDown()
void NUnit.Framework.Tests.Constraints.ToleranceTests.TearDown () inline
References NUnit.Framework.Tests.Constraints.ToleranceTests._comparer, and NUnit.Framework.GlobalSettings.DefaultFloatingPointTolerance.
TestGlobalDefaultTolerance_Success()
void NUnit.Framework.Tests.Constraints.ToleranceTests.TestGlobalDefaultTolerance_Success () inline
References NUnit.Framework.GlobalSettings.DefaultFloatingPointTolerance, NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
TestGlobalDefaultTolerance_Failure()
void NUnit.Framework.Tests.Constraints.ToleranceTests.TestGlobalDefaultTolerance_Failure () inline
References NUnit.Framework.GlobalSettings.DefaultFloatingPointTolerance, NUnit.Framework.Constraints.ConstraintExpression.EqualTo(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
TestToleranceDefault()
void NUnit.Framework.Tests.Constraints.ToleranceTests.TestToleranceDefault () inline
References NUnit.Framework.Tests.Constraints.ToleranceTests._comparer, NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(), NUnit.Framework.Constraints.Tolerance.Default, NUnit.Framework.GlobalSettings.DefaultFloatingPointTolerance, and NUnit.Framework.Assert.IsTrue().
TestToleranceExact()
void NUnit.Framework.Tests.Constraints.ToleranceTests.TestToleranceExact () inline
References NUnit.Framework.Tests.Constraints.ToleranceTests._comparer, NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(), NUnit.Framework.GlobalSettings.DefaultFloatingPointTolerance, NUnit.Framework.Constraints.Tolerance.Exact, and NUnit.Framework.Assert.IsFalse().
TestWithinCanOnlyBeUsedOnce()
void NUnit.Framework.Tests.Constraints.ToleranceTests.TestWithinCanOnlyBeUsedOnce () inline
References NUnit.Framework.Constraints.ConstraintExpression.Contains(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Constraints.ConstraintExpression.Message, NUnit.Framework.Assert.That(), NUnit.Framework.Throws.TypeOf(), NUnit.Framework.Constraints.Constraint.With, and NUnit.Framework.Constraints.EqualConstraint.Within().
TestModesCanOnlyBeUsedOnce()
void NUnit.Framework.Tests.Constraints.ToleranceTests.TestModesCanOnlyBeUsedOnce () inline
References NUnit.Framework.Constraints.ConstraintExpression.Contains(), NUnit.Framework.Constraints.ConstraintExpression.Message, NUnit.Framework.Assert.That(), NUnit.Framework.Throws.TypeOf(), and NUnit.Framework.Constraints.Constraint.With.
TestNumericToleranceRequired()
void NUnit.Framework.Tests.Constraints.ToleranceTests.TestNumericToleranceRequired () inline
References NUnit.Framework.Constraints.ConstraintExpression.Contains(), NUnit.Framework.Constraints.ConstraintExpression.Message, NUnit.Framework.Assert.That(), NUnit.Framework.Throws.TypeOf(), and NUnit.Framework.Constraints.Constraint.With.
TestModeMustFollowTolerance()
void NUnit.Framework.Tests.Constraints.ToleranceTests.TestModeMustFollowTolerance () inline
References NUnit.Framework.Constraints.ConstraintExpression.Contains(), NUnit.Framework.Constraints.Tolerance.Default, NUnit.Framework.Constraints.ConstraintExpression.Message, NUnit.Framework.Assert.That(), NUnit.Framework.Throws.TypeOf(), and NUnit.Framework.Constraints.Constraint.With.
Member Data Documentation
_comparer
NUnitEqualityComparer NUnit.Framework.Tests.Constraints.ToleranceTests._comparer private
Referenced by NUnit.Framework.Tests.Constraints.ToleranceTests.TearDown(), NUnit.Framework.Tests.Constraints.ToleranceTests.TestToleranceDefault(), and NUnit.Framework.Tests.Constraints.ToleranceTests.TestToleranceExact().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/ToleranceTests.cs