Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGGSVP Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGGSVP Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGGSVP (LSAME lsame, DGEQPF dgeqpf, DGEQR2 dgeqr2, DGERQ2 dgerq2, DLACPY dlacpy, DLAPMT dlapmt, DLASET dlaset, DORG2R dorg2r, DORM2R dorm2r, DORMR2 dormr2, XERBLA xerbla)
DGGSVP ()
void Run (string JOBU, string JOBV, string JOBQ, int M, int P, int N, ref double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB, double TOLA, double TOLB, ref int K, ref int L, ref double[] U, int offset_u, int LDU, ref double[] V, int offset_v, int LDV, ref double[] Q, int offset_q, int LDQ, ref int[] IWORK, int offset_iwork, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
LSAME _lsame
DGEQPF _dgeqpf
DGEQR2 _dgeqr2
DGERQ2 _dgerq2
DLACPY _dlacpy
DLAPMT _dlapmt
DLASET _dlaset
DORG2R _dorg2r
DORM2R _dorm2r
DORMR2 _dormr2
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGGSVP computes orthogonal matrices U, V and Q such that
N-K-L K L U'*A*Q = K (0 A12 A13) if M-K-L .GE. 0; L (0 0 A23) M-K-L (0 0 0)
N-K-L K L = K (0 A12 A13) if M-K-L .LT. 0; M-K (0 0 A23)
N-K-L K L V'*B*Q = L (0 0 B13) P-L (0 0 0)
where the K-by-K matrix A12 and L-by-L matrix B13 are nonsingular upper triangular; A23 is L-by-L upper triangular if M-K-L .GE. 0, otherwise A23 is (M-K)-by-L upper trapezoidal. K+L = the effective numerical rank of the (M+P)-by-N matrix (A',B')'. Z' denotes the transpose of Z.
This decomposition is the preprocessing step for computing the Generalized Singular Value Decomposition (GSVD), see subroutine DGGSVD.
/summary>
Constructor & Destructor Documentation
DGGSVP() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGGSVP.DGGSVP (LSAME lsame, DGEQPF dgeqpf, DGEQR2 dgeqr2, DGERQ2 dgerq2, DLACPY dlacpy, DLAPMT dlapmt, DLASET dlaset, DORG2R dorg2r, DORM2R dorm2r, DORMR2 dormr2, XERBLA xerbla) inline
DGGSVP() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGGSVP.DGGSVP () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGGSVP.Run (string JOBU, string JOBV, string JOBQ, int M, int P, int N, ref double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB, double TOLA, double TOLB, ref int K, ref int L, ref double[] U, int offset_u, int LDU, ref double[] V, int offset_v, int LDV, ref double[] Q, int offset_q, int LDQ, ref int[] IWORK, int offset_iwork, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
DGGSVP computes orthogonal matrices U, V and Q such that
N-K-L K L U'*A*Q = K (0 A12 A13) if M-K-L .GE. 0; L (0 0 A23) M-K-L (0 0 0)
N-K-L K L = K (0 A12 A13) if M-K-L .LT. 0; M-K (0 0 A23)
N-K-L K L V'*B*Q = L (0 0 B13) P-L (0 0 0)
where the K-by-K matrix A12 and L-by-L matrix B13 are nonsingular upper triangular; A23 is L-by-L upper triangular if M-K-L .GE. 0, otherwise A23 is (M-K)-by-L upper trapezoidal. K+L = the effective numerical rank of the (M+P)-by-N matrix (A',B')'. Z' denotes the transpose of Z.
This decomposition is the preprocessing step for computing the Generalized Singular Value Decomposition (GSVD), see subroutine DGGSVD.
/summary>
Parameters
JOBU (input) CHARACTER*1 = 'U': Orthogonal matrix U is computed; = 'N': U is not computed. /param>
Parameters
JOBV (input) CHARACTER*1 = 'V': Orthogonal matrix V is computed; = 'N': V is not computed. /param>
Parameters
JOBQ (input) CHARACTER*1 = 'Q': Orthogonal matrix Q is computed; = 'N': Q is not computed. /param>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
P (input) INTEGER The number of rows of the matrix B. P .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrices A and B. N .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the M-by-N matrix A. On exit, A contains the triangular (or trapezoidal) matrix described in the Purpose section. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
B (input/output) DOUBLE PRECISION array, dimension (LDB,N) On entry, the P-by-N matrix B. On exit, B contains the triangular matrix described in the Purpose section. /param>
Parameters
LDB (input) INTEGER The leading dimension of the array B. LDB .GE. max(1,P). /param>
Parameters
TOLA (input) DOUBLE PRECISION /param>
Parameters
TOLB (input) DOUBLE PRECISION TOLA and TOLB are the thresholds to determine the effective numerical rank of matrix B and a subblock of A. Generally, they are set to TOLA = MAX(M,N)*norm(A)*MAZHEPS, TOLB = MAX(P,N)*norm(B)*MAZHEPS. The size of TOLA and TOLB may affect the size of backward errors of the decomposition. /param>
Parameters
K (output) INTEGER /param>
Parameters
L (0 0 A23) /param>
Parameters
U (output) DOUBLE PRECISION array, dimension (LDU,M) If JOBU = 'U', U contains the orthogonal matrix U. If JOBU = 'N', U is not referenced. /param>
Parameters
LDU (input) INTEGER The leading dimension of the array U. LDU .GE. max(1,M) if JOBU = 'U'; LDU .GE. 1 otherwise. /param>
Parameters
V (output) DOUBLE PRECISION array, dimension (LDV,M) If JOBV = 'V', V contains the orthogonal matrix V. If JOBV = 'N', V is not referenced. /param>
Parameters
LDV (input) INTEGER The leading dimension of the array V. LDV .GE. max(1,P) if JOBV = 'V'; LDV .GE. 1 otherwise. /param>
Parameters
Q (output) DOUBLE PRECISION array, dimension (LDQ,N) If JOBQ = 'Q', Q contains the orthogonal matrix Q. If JOBQ = 'N', Q is not referenced. /param>
Parameters
LDQ (input) INTEGER The leading dimension of the array Q. LDQ .GE. max(1,N) if JOBQ = 'Q'; LDQ .GE. 1 otherwise. /param>
Parameters
IWORK (workspace) INTEGER array, dimension (N) /param>
Parameters
TAU (workspace) DOUBLE PRECISION array, dimension (N) /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (max(3*N,M,P)) /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value.
/param>
References DotNumerics.LinearAlgebra.CSLapack.DGGSVP.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAPMT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASET.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGERQ2.Run(), DotNumerics.LinearAlgebra.CSLapack.DORG2R.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQPF.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DORM2R.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGGSVP.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGGSVD.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DGGSVP._lsame private
_dgeqpf
DGEQPF DotNumerics.LinearAlgebra.CSLapack.DGGSVP._dgeqpf private
_dgeqr2
DGEQR2 DotNumerics.LinearAlgebra.CSLapack.DGGSVP._dgeqr2 private
_dgerq2
DGERQ2 DotNumerics.LinearAlgebra.CSLapack.DGGSVP._dgerq2 private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DGGSVP._dlacpy private
_dlapmt
DLAPMT DotNumerics.LinearAlgebra.CSLapack.DGGSVP._dlapmt private
_dlaset
DLASET DotNumerics.LinearAlgebra.CSLapack.DGGSVP._dlaset private
_dorg2r
DORG2R DotNumerics.LinearAlgebra.CSLapack.DGGSVP._dorg2r private
_dorm2r
DORM2R DotNumerics.LinearAlgebra.CSLapack.DGGSVP._dorm2r private
_dormr2
DORMR2 DotNumerics.LinearAlgebra.CSLapack.DGGSVP._dormr2 private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGGSVP._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DGGSVP.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGGSVP.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGGSVP.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGGSVP.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dggsvp.cs