Doc: IGLib EXTENDED: AForge.Imaging.Filters.IFilter Interface Reference
AForge.Imaging.Filters.IFilter Interface Reference
Image processing filter interface.
Public Member Functions
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image.
Detailed Description
Image processing filter interface.
The interface defines the set of methods, which should be provided by all image processing filters. Methods of this interface keep the source image unchanged and returt the result of image processing filter as new image.
See also
IInPlaceFilter, IInPlacePartialFilter
Member Function Documentation
Apply() [1/4]
Bitmap AForge.Imaging.Filters.IFilter.Apply (Bitmap image)
Apply filter to an image.
Parameters
image Source image to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The method keeps the source image unchanged and returns the result of image processing filter as new image.
Implemented in AForge.Imaging.Filters.FilterIterator, AForge.Imaging.Filters.ExtractBiggestBlob, AForge.Imaging.Filters.Closing, AForge.Imaging.Filters.Opening, AForge.Imaging.Filters.FiltersSequence, AForge.Imaging.Filters.BaseUsingCopyPartialFilter, AForge.Imaging.Filters.BaseFilter, AForge.Imaging.Filters.BaseTransformationFilter, AForge.Imaging.Filters.BaseInPlacePartialFilter, and AForge.Imaging.Filters.BaseInPlaceFilter.
Referenced by AForge.Imaging.Filters.FilterIterator.Apply(), FiltersDemo.MainForm.ApplyFilter(), AForge.Imaging.Filters.TexturedFilter.ProcessFilter(), and AForge.Imaging.Filters.MaskedFilter.ProcessImage().
Apply() [2/4]
Bitmap AForge.Imaging.Filters.IFilter.Apply (BitmapData imageData)
Apply filter to an image.
Parameters
imageData Source image to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The filter accepts bitmap data as input and returns the result of image processing filter as new image. The source image data are kept unchanged.
Implemented in AForge.Imaging.Filters.FilterIterator, AForge.Imaging.Filters.ExtractBiggestBlob, AForge.Imaging.Filters.FiltersSequence, AForge.Imaging.Filters.Closing, AForge.Imaging.Filters.Opening, AForge.Imaging.Filters.BaseUsingCopyPartialFilter, AForge.Imaging.Filters.BaseFilter, AForge.Imaging.Filters.BaseTransformationFilter, AForge.Imaging.Filters.BaseInPlacePartialFilter, and AForge.Imaging.Filters.BaseInPlaceFilter.
Apply() [3/4]
UnmanagedImage AForge.Imaging.Filters.IFilter.Apply (UnmanagedImage image)
Apply filter to an image.
Parameters
image Image in unmanaged memory.
Returns
Returns filter's result obtained by applying the filter to the source image.
The method keeps the source image unchanged and returns the result of image processing filter as new image.
Implemented in AForge.Imaging.Filters.ExtractBiggestBlob, AForge.Imaging.Filters.FilterIterator, AForge.Imaging.Filters.FiltersSequence, AForge.Imaging.Filters.BaseUsingCopyPartialFilter, AForge.Imaging.Filters.BaseFilter, AForge.Imaging.Filters.BaseTransformationFilter, AForge.Imaging.Filters.Closing, AForge.Imaging.Filters.Opening, AForge.Imaging.Filters.BaseInPlacePartialFilter, and AForge.Imaging.Filters.BaseInPlaceFilter.
Apply() [4/4]
void AForge.Imaging.Filters.IFilter.Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image.
Parameters
sourceImage Source image to be processed.
destinationImage Destination image to store filter's result.
The method keeps the source image unchanged and puts the the result of image processing filter into destination image.
<note>The destination image must have the size, which is expected by the filter.</note>
Exceptions
InvalidImagePropertiesException In the case if destination image has incorrect size.
Implemented in AForge.Imaging.Filters.ExtractBiggestBlob, AForge.Imaging.Filters.FilterIterator, AForge.Imaging.Filters.FiltersSequence, AForge.Imaging.Filters.BaseUsingCopyPartialFilter, AForge.Imaging.Filters.BaseTransformationFilter, AForge.Imaging.Filters.BaseFilter, AForge.Imaging.Filters.BaseInPlacePartialFilter, AForge.Imaging.Filters.BaseInPlaceFilter, AForge.Imaging.Filters.Closing, and AForge.Imaging.Filters.Opening.
The documentation for this interface was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/IFilter.cs