Doc: IGLib EXTENDED: NeuronDotNet.Core.Initializers.NormalizedRandomFunction Class Reference
NeuronDotNet.Core.Initializers.NormalizedRandomFunction Class Reference
An IInitializer using Normalized Random function.
Public Member Functions
NormalizedRandomFunction ()
Creates a new normalized random function
NormalizedRandomFunction (SerializationInfo info, StreamingContext context)
Deserialization Constructor
void GetObjectData (SerializationInfo info, StreamingContext context)
Populates the serialization info with the data needed to serialize the initializer
void Initialize (ActivationLayer activationLayer)
Initializes bias values of activation neurons in the activation layer.
void Initialize (BackpropagationConnector connector)
Initializes weights of all backpropagation synapses in the backpropagation connector.
void Initialize (KohonenConnector connector)
Initializes weights of all spatial synapses in a Kohonen connector.
Detailed Description
An IInitializer using Normalized Random function.
Constructor & Destructor Documentation
NormalizedRandomFunction() [1/2]
NeuronDotNet.Core.Initializers.NormalizedRandomFunction.NormalizedRandomFunction () inline
Creates a new normalized random function
NormalizedRandomFunction() [2/2]
NeuronDotNet.Core.Initializers.NormalizedRandomFunction.NormalizedRandomFunction (SerializationInfo info, StreamingContext context) inline
Deserialization Constructor
Parameters
info Serialization information to deserialize and obtain the data
context Serialization context to use
Member Function Documentation
GetObjectData()
void NeuronDotNet.Core.Initializers.NormalizedRandomFunction.GetObjectData (SerializationInfo info, StreamingContext context) inline
Populates the serialization info with the data needed to serialize the initializer
Parameters
info The serialization info to populate the data with
context The serialization context to use
Initialize() [1/3]
void NeuronDotNet.Core.Initializers.NormalizedRandomFunction.Initialize (ActivationLayer activationLayer) inline
Initializes bias values of activation neurons in the activation layer.
Parameters
activationLayer The activation layer to initialize
Exceptions
ArgumentNullException If activationLayer is null
Implements NeuronDotNet.Core.IInitializer.
References NeuronDotNet.Core.Layer< TNeuron >.NeuronCount, and NeuronDotNet.Core.Helper.ValidateNotNull().
Initialize() [2/3]
void NeuronDotNet.Core.Initializers.NormalizedRandomFunction.Initialize (BackpropagationConnector connector) inline
Initializes weights of all backpropagation synapses in the backpropagation connector.
Parameters
connector The backpropagation connector to initialize.
Exceptions
ArgumentNullException If connector is null
Implements NeuronDotNet.Core.IInitializer.
References NeuronDotNet.Core.Connector< TSourceLayer, TTargetLayer, TSynapse >.SynapseCount, NeuronDotNet.Core.Helper.ValidateNotNull(), and NeuronDotNet.Core.Backpropagation.BackpropagationSynapse.Weight.
Initialize() [3/3]
void NeuronDotNet.Core.Initializers.NormalizedRandomFunction.Initialize (KohonenConnector connector) inline
Initializes weights of all spatial synapses in a Kohonen connector.
Parameters
connector The Kohonen connector to initialize.
Exceptions
ArgumentNullException If connector is null
Implements NeuronDotNet.Core.IInitializer.
References NeuronDotNet.Core.Connector< TSourceLayer, TTargetLayer, TSynapse >.SynapseCount, NeuronDotNet.Core.Helper.ValidateNotNull(), and NeuronDotNet.Core.SOM.KohonenSynapse.Weight.
The documentation for this class was generated from the following file:
shelldev/lib/externalextended/NeuronDotNetGPL/source/Core/Initializers/NormalizedRandomFunction.cs