Doc: IGLib EXTENDED: IG.Script._25KickedRotator Class Reference
IG.Script._25KickedRotator Class Reference
Plots a state space portrait of the kicked rotator.
Static Public Member Functions
static void Run (string[] arguments)
Detailed Description
Plots a state space portrait of the kicked rotator.
Member Function Documentation
Run()
static void IG.Script._25KickedRotator.Run (string[] arguments) inline static
References IG.Lib.ColorScaleBase.Create(), IG.MPetekLib.Algorithms.PlottableModels.KickedRotator.Fi0, IG.Lib.ColorScaleBase.GetColor(), IG.MPetekLib.Algorithms.PlottableModels.KickedRotator.Konst, IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase.NewCurveFromPlottableData(), IG.MPetekLib.Algorithms.PlottableModels.KickedRotator.NSteps, IG.MPetekLib.Algorithms.PlottableModels.KickedRotator.P0, IG.MPetekLib.Algorithms.Plotting.PlotHQ.Plotter, IG.MPetekLib.Algorithms.Plotting.PlotHQ.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.KickedRotator.Solve(), IG.MPetekLib.Algorithms.PlottableModels.KickedRotator.Tau, and IG.MPetekLib.Algorithms.Plotting.PlotHQ.Window.
Referenced by IG.Script.AppMarkoPetek.App25KickedRotator().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/Guest_Marko_Petek_Lib/application/scripts/25KickedRotator.cs