Doc: IGLib EXTENDED: NUnit.Framework.Internal.Filters.NotFilter Class Reference
NUnit.Framework.Internal.Filters.NotFilter Class Reference
NotFilter negates the operation of another filter
Public Member Functions
NotFilter (TestFilter baseFilter)
Construct a not filter on another filter
override bool Pass (ITest test)
Determine if a particular test passes the filter criteria. The default implementation checks the test itself, its parents and any descendants.
override bool Match (ITest test)
Check whether the filter matches a test
override bool IsExplicitMatch (ITest test)
Determine if a test matches the filter expicitly. That is, it must be a direct match of the test itself or one of it's children.
override TNode AddToXml (TNode parentNode, bool recursive)
Adds an XML node
Public Member Functions inherited from NUnit.Framework.Internal.TestFilter
bool MatchParent (ITest test)
Determine whether any ancestor of the test matches the filter criteria
TNode ToXml (bool recursive)
Adds an XML node
Properties
TestFilter BaseFilter [get, private set]
Gets the base filter
Properties inherited from NUnit.Framework.Internal.TestFilter
bool IsEmpty [get]
Indicates whether this is the EmptyFilter
bool TopLevel [get, set]
Indicates whether this is a top-level filter, not contained in any other filter.
Additional Inherited Members
Static Public Member Functions inherited from NUnit.Framework.Internal.TestFilter
static TestFilter FromXml (string xmlText)
Create a TestFilter instance from an xml representation.
static TestFilter FromXml (TNode node)
Create a TestFilter from it's TNode representation
Static Public Attributes inherited from NUnit.Framework.Internal.TestFilter
static readonly TestFilter Empty = new EmptyFilter()
Unique Empty filter.
Protected Member Functions inherited from NUnit.Framework.Internal.TestFilter
virtual bool MatchDescendant (ITest test)
Determine whether any descendant of the test matches the filter criteria.
Detailed Description
NotFilter negates the operation of another filter
Constructor & Destructor Documentation
NotFilter()
NUnit.Framework.Internal.Filters.NotFilter.NotFilter (TestFilter baseFilter) inline
Construct a not filter on another filter
Parameters
baseFilter The filter to be negated
References NUnit.Framework.Internal.Filters.NotFilter.BaseFilter.
Member Function Documentation
Pass()
override bool NUnit.Framework.Internal.Filters.NotFilter.Pass (ITest test) inline virtual
Determine if a particular test passes the filter criteria. The default implementation checks the test itself, its parents and any descendants.
Derived classes may override this method or any of the Match methods to change the behavior of the filter.
Parameters
test The test to which the filter is applied
Returns
True if the test passes the filter, otherwise false
Reimplemented from NUnit.Framework.Internal.TestFilter.
References NUnit.Framework.Internal.Filters.NotFilter.BaseFilter, NUnit.Framework.Internal.TestFilter.Match(), and NUnit.Framework.Internal.TestFilter.MatchParent().
Match()
override bool NUnit.Framework.Internal.Filters.NotFilter.Match (ITest test) inline virtual
Check whether the filter matches a test
Parameters
test The test to be matched
Returns
True if it matches, otherwise false
Implements NUnit.Framework.Internal.TestFilter.
References NUnit.Framework.Internal.Filters.NotFilter.BaseFilter, and NUnit.Framework.Internal.TestFilter.Match().
IsExplicitMatch()
override bool NUnit.Framework.Internal.Filters.NotFilter.IsExplicitMatch (ITest test) inline virtual
Determine if a test matches the filter expicitly. That is, it must be a direct match of the test itself or one of it's children.
Parameters
test The test to which the filter is applied
Returns
True if the test matches the filter explicityly, otherwise false
Reimplemented from NUnit.Framework.Internal.TestFilter.
AddToXml()
override TNode NUnit.Framework.Internal.Filters.NotFilter.AddToXml (TNode parentNode, bool recursive) inline virtual
Adds an XML node
Parameters
parentNode Parent node
recursive True if recursive
Returns
The added XML node
Implements NUnit.Framework.Internal.TestFilter.
References NUnit.Framework.Interfaces.TNode.AddElement(), NUnit.Framework.Internal.TestFilter.AddToXml(), and NUnit.Framework.Internal.Filters.NotFilter.BaseFilter.
Property Documentation
BaseFilter
TestFilter NUnit.Framework.Internal.Filters.NotFilter.BaseFilter get private set
Gets the base filter
Referenced by NUnit.Framework.Internal.Filters.NotFilter.AddToXml(), NUnit.Framework.Internal.Filters.NotFilter.Match(), NUnit.Framework.Internal.Filters.NotFilter.NotFilter(), and NUnit.Framework.Internal.Filters.NotFilter.Pass().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/Filters/NotFilter.cs