Doc: IGLib EXTENDED: NUnit.Engine.Services.ProjectService Class Reference
NUnit.Engine.Services.ProjectService Class Reference
Summary description for ProjectService.
Public Member Functions
bool CanLoadFrom (string path)
Returns true if the file indicated is one that this loader knows how to load.
void ExpandProjectPackage (TestPackage package)
Expands a TestPackage based on a known project format, populating it with the project contents and any settings the project provides. Note that the package file path must be checked to ensure that it is a known project format before calling this method.
override void StartService ()
Initialize the Service
Public Member Functions inherited from NUnit.Engine.Services.Service
virtual void StopService ()
Do any cleanup needed before terminating the service
void Dispose ()
Private Member Functions
IProject LoadFrom (string path)
ExtensionNode GetNodeForPath (string path)
Private Attributes
Dictionary< string, ExtensionNode > _extensionIndex = new Dictionary<string, ExtensionNode>()
Additional Inherited Members
Protected Member Functions inherited from NUnit.Engine.Services.Service
virtual void Dispose (bool disposing)
Protected Attributes inherited from NUnit.Engine.Services.Service
bool _disposed = false
Properties inherited from NUnit.Engine.Services.Service
IServiceLocator ServiceContext [get, set]
The ServiceContext
ServiceStatus Status [get, protected set]
Gets the ServiceStatus of this service
Properties inherited from NUnit.Engine.IService
IServiceLocator ServiceContext [get, set]
The ServiceContext
ServiceStatus Status [get]
Gets the ServiceStatus of this service
Detailed Description
Summary description for ProjectService.
Member Function Documentation
CanLoadFrom()
bool NUnit.Engine.Services.ProjectService.CanLoadFrom (string path) inline
Returns true if the file indicated is one that this loader knows how to load.
Parameters
path The path of the project file
Returns
True if the loader knows how to load this file, otherwise false
Implements NUnit.Engine.Services.IProjectService.
References NUnit.Engine.Extensibility.ExtensionNode.ExtensionObject, and NUnit.Engine.Services.ProjectService.GetNodeForPath().
ExpandProjectPackage()
void NUnit.Engine.Services.ProjectService.ExpandProjectPackage (TestPackage package) inline
Expands a TestPackage based on a known project format, populating it with the project contents and any settings the project provides. Note that the package file path must be checked to ensure that it is a known project format before calling this method.
Parameters
package The TestPackage to be expanded
Implements NUnit.Engine.Services.IProjectService.
References NUnit.Common.PackageSettings.ActiveConfig, NUnit.Common.Guard.ArgumentNotNull(), NUnit.Common.Guard.ArgumentValid(), NUnit.Common.PackageSettings.ConfigurationFile, NUnit.Engine.TestPackage.FullName, NUnit.Engine.Extensibility.IProject.GetTestPackage(), NUnit.Engine.Services.ProjectService.LoadFrom(), NUnit.Engine.TestPackage.Settings, and NUnit.Engine.TestPackage.SubPackages.
StartService()
override void NUnit.Engine.Services.ProjectService.StartService () inline virtual
Initialize the Service
Reimplemented from NUnit.Engine.Services.Service.
References NUnit.Engine.Services.ProjectService._extensionIndex, NUnit.Engine.ServiceContext.GetService(), and NUnit.Engine.Services.Service.Status.
LoadFrom()
IProject NUnit.Engine.Services.ProjectService.LoadFrom (string path) inline private
References NUnit.Engine.Extensibility.ExtensionNode.ExtensionObject, NUnit.Engine.Services.ProjectService.GetNodeForPath(), and NUnit.Engine.Extensibility.IProjectLoader.LoadFrom().
Referenced by NUnit.Engine.Services.ProjectService.ExpandProjectPackage().
GetNodeForPath()
ExtensionNode NUnit.Engine.Services.ProjectService.GetNodeForPath (string path) inline private
References NUnit.Engine.Services.ProjectService._extensionIndex.
Referenced by NUnit.Engine.Services.ProjectService.CanLoadFrom(), and NUnit.Engine.Services.ProjectService.LoadFrom().
Member Data Documentation
_extensionIndex
Dictionary<string, ExtensionNode> NUnit.Engine.Services.ProjectService._extensionIndex = new Dictionary<string, ExtensionNode>() private
Referenced by NUnit.Engine.Services.ProjectService.GetNodeForPath(), and NUnit.Engine.Services.ProjectService.StartService().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Services/ProjectService.cs