Doc: IGLib EXTENDED: Meta.Numerics.Matrices.RowVector Class Reference
Meta.Numerics.Matrices.RowVector Class Reference
A row vector of real numbers.
Public Member Functions
RowVector (int dimension)
Initializes a new row vector with the given dimension.
RowVector (IList< double > list)
Initializes a new row vector from the given component list.
RowVector (params double[] list)
Initializes a new row vector with the given components.
ColumnVector Transpose ()
Returns the transpose of the row vector.
RowVector Copy ()
Returns a copy of the row vector.
Public Member Functions inherited from Meta.Numerics.Matrices.VectorBase
virtual double Norm ()
Computes the magnitude of the vector.
virtual new double[] ToArray ()
Returns the vector elements in an independent array.
IEnumerator< double > GetEnumerator ()
Gets an enumerator of the vector components.
Public Member Functions inherited from Meta.Numerics.Matrices.AnyRectangularMatrix
virtual double OneNorm ()
Computes the 1-norm of the matrix.
virtual double InfinityNorm ()
Computes the &#x221E;-norm of the matrix.
virtual double FrobeniusNorm ()
Computes the Frobenius-norm of the matrix.
virtual ColumnVector Column (int c)
Gets a copy of the specified column.
virtual RowVector Row (int r)
Gets a copy of the specified row.
virtual SymmetricMatrix MultiplySelfByTranspose ()
Computes the product of the matrix and its transpose.
virtual SymmetricMatrix MultiplyTransposeBySelf ()
Computes the product of the matrix's transpose and itself.
bool Equals (AnyRectangularMatrix other)
Determines whether the given matrix equals the current matrix.
override bool Equals (object obj)
Determines whether the given object is an equal matrix.
override int GetHashCode ()
Not a valid operation.
Public Member Functions inherited from Meta.Numerics.Matrices.AnyMatrix< double >
virtual void Fill (Func< int, int, T > f)
Sets all matrix entries according to a supplied fill function.
Static Public Member Functions
static RowVector operator+ (RowVector v1, RowVector v2)
Computes the sum of two row vectors.
static RowVector operator- (RowVector v1, RowVector v2)
Computes the difference of two column vectors.
static RowVector operator* (double alpha, RowVector v)
Multiplies a row vector by a real, scalar constant.
static RowVector operator/ (RowVector v, double alpha)
Divides a row vector by a real, scalar constant.
static RowVector operator- (RowVector v)
Negates a row vector.
static RowVector operator* (RowVector v, AnyRectangularMatrix A)
Multiplies any real, rectangular matrix by a row vector.
static double operator* (RowVector v, ColumnVector u)
Computes the inner (scalar or dot) product of a row and a column vector.
Static Public Member Functions inherited from Meta.Numerics.Matrices.AnyRectangularMatrix
static RectangularMatrix operator+ (AnyRectangularMatrix A, AnyRectangularMatrix B)
Adds any two real, rectangular matrices.
static RectangularMatrix operator- (AnyRectangularMatrix A, AnyRectangularMatrix B)
Subtracts any two real, rectangular matrices.
static RectangularMatrix operator* (AnyRectangularMatrix A, AnyRectangularMatrix B)
Multiplies any two real, rectangular matrices.
static RectangularMatrix operator* (double alpha, AnyRectangularMatrix A)
Multiplies any real, rectangular matrix by a real constant.
static ColumnVector operator* (AnyRectangularMatrix A, ColumnVector v)
Multiplies any real, rectangular matrix with a real column vector.
static bool operator== (AnyRectangularMatrix A, AnyRectangularMatrix B)
Determines whether two matrices are equal.
static bool operator!= (AnyRectangularMatrix A, AnyRectangularMatrix B)
Determines whether two matrices are not equal.
Properties
override int RowCount [get]
override int ColumnCount [get]
override double this[int r, int c] [get, set]
Properties inherited from Meta.Numerics.Matrices.VectorBase
virtual double this[int index] [get, set]
Gets or sets the specified vector component.
virtual int Dimension [get]
Gets the dimension of the vector.
int ICollection< double >. Count [get]
bool ICollection< double >. IsReadOnly [get]
Properties inherited from Meta.Numerics.Matrices.AnyMatrix< double >
abstract int RowCount [get]
Gets the number of matrix rows.
abstract int ColumnCount [get]
Gets the number of matrix columns.
abstract T this[int r, int c] [get, set]
Gets or sets the value of a matrix entry.
bool IsReadOnly [get, set]
Gets a flag indicating whether the matrix is read-only.
Additional Inherited Members
Protected Member Functions inherited from Meta.Numerics.Matrices.AnyRectangularMatrix
AnyRectangularMatrix ()
Protected Member Functions inherited from Meta.Numerics.Matrices.AnyMatrix< double >
AnyMatrix ()
Detailed Description
A row vector of real numbers.
An N-dimensional row vector is an 1 X N dimensional matrix.
Constructor & Destructor Documentation
RowVector() [1/3]
Meta.Numerics.Matrices.RowVector.RowVector (int dimension) inline
Initializes a new row vector with the given dimension.
Parameters
dimension The dimension of the vector, which must be positive.
Referenced by Meta.Numerics.Matrices.RowVector.Copy(), Meta.Numerics.Matrices.RowVector.operator*(), Meta.Numerics.Matrices.RowVector.operator+(), Meta.Numerics.Matrices.RowVector.operator-(), and Meta.Numerics.Matrices.RowVector.operator/().
RowVector() [2/3]
Meta.Numerics.Matrices.RowVector.RowVector (IList< double > list) inline
Initializes a new row vector from the given component list.
Parameters
list A list of vector components.
RowVector() [3/3]
Meta.Numerics.Matrices.RowVector.RowVector (params double[] list) inline
Initializes a new row vector with the given components.
Parameters
list A list of vector components.
Member Function Documentation
Transpose()
ColumnVector Meta.Numerics.Matrices.RowVector.Transpose () inline
Returns the transpose of the row vector.
Returns
An independent column vector with the same components as the row vector.
References Meta.Numerics.Matrices.ColumnVector.Copy(), and Meta.Numerics.Matrices.VectorBase.stride.
Referenced by Test.VectorTest.RowVectorArithmetic().
Copy()
RowVector Meta.Numerics.Matrices.RowVector.Copy () inline
Returns a copy of the row vector.
Returns
An independent copy of the row vector.
References Meta.Numerics.Matrices.RowVector.Copy(), Meta.Numerics.Matrices.RowVector.RowVector(), and Meta.Numerics.Matrices.VectorBase.stride.
Referenced by Meta.Numerics.Matrices.RowVector.Copy(), Test.MultivariateSampleTest.PrincipalComponentAnalysis(), Test.VectorTest.RowVectorCopy(), and Meta.Numerics.Matrices.ColumnVector.Transpose().
operator+()
static RowVector Meta.Numerics.Matrices.RowVector.operator+ (RowVector v1, RowVector v2) inline static
Computes the sum of two row vectors.
Parameters
v1 The first row vector.
v2 The second row vector.
Returns
The sum v1 + v2 .
References Meta.Numerics.Matrices.RowVector.RowVector(), and Meta.Numerics.Matrices.VectorBase.stride.
operator-() [1/2]
static RowVector Meta.Numerics.Matrices.RowVector.operator- (RowVector v1, RowVector v2) inline static
Computes the difference of two column vectors.
Parameters
v1 The first column vector.
v2 The second column vector.
Returns
The difference v1 - v2 .
References Meta.Numerics.Matrices.RowVector.RowVector(), and Meta.Numerics.Matrices.VectorBase.stride.
operator*() [1/3]
static RowVector Meta.Numerics.Matrices.RowVector.operator* (double alpha, RowVector v) inline static
Multiplies a row vector by a real, scalar constant.
Parameters
alpha The real, scalar constant.
v The row vector.
Returns
The product.
References Meta.Numerics.Matrices.RowVector.RowVector(), and Meta.Numerics.Matrices.VectorBase.stride.
operator/()
static RowVector Meta.Numerics.Matrices.RowVector.operator/ (RowVector v, double alpha) inline static
Divides a row vector by a real, scalar constant.
Parameters
alpha The real, scalar constant.
v The row vector.
Returns
The result.
References Meta.Numerics.Matrices.RowVector.RowVector(), and Meta.Numerics.Matrices.VectorBase.stride.
operator-() [2/2]
static RowVector Meta.Numerics.Matrices.RowVector.operator- (RowVector v) inline static
Negates a row vector.
Parameters
v The row vector.
Returns
-v
operator*() [2/3]
static RowVector Meta.Numerics.Matrices.RowVector.operator* (RowVector v, AnyRectangularMatrix A) inline static
Multiplies any real, rectangular matrix by a row vector.
Parameters
v The row vector.
A The matrix.
Returns
The product row vector.
References Meta.Numerics.Matrices.VectorBase.Dimension, and Meta.Numerics.Matrices.RowVector.RowVector().
operator*() [3/3]
static double Meta.Numerics.Matrices.RowVector.operator* (RowVector v, ColumnVector u) inline static
Computes the inner (scalar or dot) product of a row and a column vector.
Parameters
v The row vector.
u The column vector.
Returns
The value of the scalar product.
References Meta.Numerics.Matrices.VectorBase.stride.
Property Documentation
RowCount
override int Meta.Numerics.Matrices.RowVector.RowCount get
ColumnCount
override int Meta.Numerics.Matrices.RowVector.ColumnCount get
this[int r, int c]
override double Meta.Numerics.Matrices.RowVector.this[int r, int c] get set
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Matrices/RowVector.cs