Doc: IGLib EXTENDED: IG.Neural.NeuronBackPropagationLEarning Class Reference
IG.Neural.NeuronBackPropagationLEarning Class Reference
Public Member Functions
NeuronBackPropagationLEarning (NeuronDotNet.Core.Backpropagation.ActivationLayer inputLayer, NeuronDotNet.Core.Backpropagation.ActivationLayer outputLayer)
Creates a new Back Propagation Network, with the specified input and output layers. (You are required to connect all layers using appropriate synapses, before using the constructor. Any changes made to the structure of the network after its creation may lead to complete malfunctioning)
NeuronBackPropagationLEarning (SerializationInfo info, StreamingContext context)
Deserialization Constructor
override void Learn (TrainingSet trainingSet, int trainingEpochs)
Trains the neural network for the given training set (Batch Training)
Public Member Functions inherited from NeuronDotNet.Core.Backpropagation.BackpropagationNetwork
BackpropagationNetwork (ActivationLayer inputLayer, ActivationLayer outputLayer)
Creates a new Back Propagation Network, with the specified input and output layers. (You are required to connect all layers using appropriate synapses, before using the constructor. Any changes made to the structure of the network after its creation may lead to complete malfunctioning)
BackpropagationNetwork (SerializationInfo info, StreamingContext context)
Deserialization Constructor
override void Learn (TrainingSample trainingSample, int currentIteration, int trainingEpochs)
Public Member Functions inherited from NeuronDotNet.Core.Network
Network (SerializationInfo info, StreamingContext context)
Deserialization constructor. It is assumed that the serialization info provided contains valid data.
virtual void GetObjectData (SerializationInfo info, StreamingContext context)
Populates the serialization info with the data necessary to serialize the network.
void SetLearningRate (double learningRate)
Sets the learning rate to the given value. All layers in the network will use this constant value as learning rate during the learning process.
void SetLearningRate (double initialLearningRate, double finalLearningRate)
Sets the initial and final values for learning rate. During the learning process, all layers in the network will use an efeective learning rate which varies uniformly from the initial value to the final value.
void SetLearningRate (ILearningRateFunction learningRateFunction)
Sets the learning rate function.
virtual void Initialize ()
Initializes all layers and connectors and makes them ready to undergo fresh training.
virtual double[] Run (double[] input)
Runs the neural network against the given input
void StopLearning ()
If the network is currently learning, this method stops the learning.
Additional Inherited Members
Protected Member Functions inherited from NeuronDotNet.Core.Backpropagation.BackpropagationNetwork
override void OnBeginEpoch (int currentIteration, TrainingSet trainingSet)
Invokes BeginEpochEvent
override void OnEndEpoch (int currentIteration, TrainingSet trainingSet)
Invokes EndEpochEvent
override void LearnSample (TrainingSample trainingSample, int currentIteration, int trainingEpochs)
A protected helper function used to train single learning sample
Protected Member Functions inherited from NeuronDotNet.Core.Network
Network (ILayer inputLayer, ILayer outputLayer, TrainingMethod trainingMethod)
Creates a new neural network
virtual void OnBeginSample (int currentIteration, TrainingSample currentSample)
Invokes BeginSampleEvent
virtual void OnEndSample (int currentIteration, TrainingSample currentSample)
Invokes BeginSampleEvent
Protected Attributes inherited from NeuronDotNet.Core.Network
readonly ILayer inputLayer
The input layer
readonly ILayer outputLayer
The output layer
readonly IList< ILayer > layers
List of layers in the network, ordered acyclically (first layer being input layer and last one being output layer)
readonly IList< IConnector > connectors
A list of connectors between layers.
readonly TrainingMethod trainingMethod
The method of training used to train the network
int jitterEpoch
Epoch(interval) at which Jitter operation is performed. If this value is zero, not jitter is performed.
double jitterNoiseLimit
Maximum absolute limit to the random noise added during Jitter operation
bool isStopping = false
This flag is set to true, whenever training needs to be stopped immmediately
Properties inherited from NeuronDotNet.Core.Backpropagation.BackpropagationNetwork
double? MeanSquaredError [get]
Gets the value of mean squared error
Properties inherited from NeuronDotNet.Core.Network
ILayer InputLayer [get]
Gets the input layer of the network
ILayer OutputLayer [get]
Gets the output layer of the network
int LayerCount [get]
Gets the number of layers in the network.
IEnumerable< ILayer > Layers [get]
Exposes an enumerator to iterate over layers in the network.
ILayer this[int index] [get]
Layer Indexer
int ConnectorCount [get]
Gets the number of connectors in the network.
IEnumerable< IConnector > Connectors [get]
Exposes an enumerator to iterate over connectors in the network.
double JitterNoiseLimit [get, set]
Gets or sets maximum absolute limit to the jitter noise
int JitterEpoch [get, set]
Gets or sets the jitter epoch
Properties inherited from NeuronDotNet.Core.INetwork
ILayer InputLayer [get]
Gets the input layer of the network
ILayer OutputLayer [get]
Gets the output layer of the network
int LayerCount [get]
Gets the number of layers in the network.
IEnumerable< ILayer > Layers [get]
Exposes an enumerator to iterate over layers in the network.
ILayer this[int index] [get]
Layer Indexer
int ConnectorCount [get]
Gets the number of connectors in the network.
IEnumerable< IConnector > Connectors [get]
Exposes an enumerator to iterate over connectors in the network.
double JitterNoiseLimit [get, set]
Gets or sets maximum absolute limit to the jitter noise
int JitterEpoch [get, set]
Gets or sets the jitter epoch
Events inherited from NeuronDotNet.Core.Network
TrainingEpochEventHandler BeginEpochEvent
This event is invoked during the commencement of a new training iteration during 'Batch training' mode.
TrainingSampleEventHandler BeginSampleEvent
This event is invoked whenever the network is about to learn a training sample.
TrainingSampleEventHandler EndSampleEvent
This event is invoked whenever the network has successfully completed learning a training sample.
TrainingEpochEventHandler EndEpochEvent
This event is invoked whenever a training iteration is successfully completed during 'Batch training' mode.
Events inherited from NeuronDotNet.Core.INetwork
TrainingEpochEventHandler BeginEpochEvent
This event is invoked during the commencement of a new training iteration during 'Batch training' mode.
TrainingSampleEventHandler BeginSampleEvent
This event is invoked whenever the network is about to learn a training sample.
TrainingSampleEventHandler EndSampleEvent
This event is invoked whenever the network has successfully completed learning a training sample.
TrainingEpochEventHandler EndEpochEvent
This event is invoked whenever a training iteration is successfully completed during 'Batch training' mode.
Constructor & Destructor Documentation
NeuronBackPropagationLEarning() [1/2]
IG.Neural.NeuronBackPropagationLEarning.NeuronBackPropagationLEarning (NeuronDotNet.Core.Backpropagation.ActivationLayer inputLayer, NeuronDotNet.Core.Backpropagation.ActivationLayer outputLayer) inline
Creates a new Back Propagation Network, with the specified input and output layers. (You are required to connect all layers using appropriate synapses, before using the constructor. Any changes made to the structure of the network after its creation may lead to complete malfunctioning)
Parameters
inputLayer The input layer
outputLayer The output layer
Exceptions
ArgumentNullException If inputLayer or outputLayer is null
NeuronBackPropagationLEarning() [2/2]
IG.Neural.NeuronBackPropagationLEarning.NeuronBackPropagationLEarning (SerializationInfo info, StreamingContext context) inline
Deserialization Constructor
Parameters
info Serialization information to deserialize and obtain the data
context Serialization context to use
Exceptions
ArgumentNullException If info is null
Member Function Documentation
Learn()
override void IG.Neural.NeuronBackPropagationLEarning.Learn (TrainingSet trainingSet, int trainingEpochs) inline virtual
Trains the neural network for the given training set (Batch Training)
Parameters
trainingSet The training set to use
trainingEpochs Number of training epochs. (All samples are trained in some random order, in every training epoch)
Exceptions
ArgumentNullException if trainingSet is null
ArgumentException if trainingEpochs is zero or negative
Reimplemented from NeuronDotNet.Core.Network.
References NeuronDotNet.Core.Network.connectors, NeuronDotNet.Core.Helper.GetRandomOrder(), NeuronDotNet.Core.Network.inputLayer, NeuronDotNet.Core.TrainingSet.InputVectorLength, NeuronDotNet.Core.Network.isStopping, NeuronDotNet.Core.Network.jitterEpoch, NeuronDotNet.Core.Network.jitterNoiseLimit, NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.LearnSample(), NeuronDotNet.Core.ILayer.NeuronCount, NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.OnBeginEpoch(), NeuronDotNet.Core.Network.OnBeginSample(), NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.OnEndEpoch(), NeuronDotNet.Core.Network.OnEndSample(), NeuronDotNet.Core.Network.outputLayer, NeuronDotNet.Core.TrainingSet.OutputVectorLength, NeuronDotNet.Core.Network.trainingMethod, NeuronDotNet.Core.TrainingSet.TrainingSampleCount, NeuronDotNet.Core.Helper.ValidateNotNull(), and NeuronDotNet.Core.Helper.ValidatePositive().
The documentation for this class was generated from the following file:
shelldev/extensions_shell/ExtTestTadej/ProgramExtTestTadej.cs