Doc: IGLib EXTENDED: NUnit.Engine.Services.DomainManager.DomainUnloader Class Reference
NUnit.Engine.Services.DomainManager.DomainUnloader Class Reference
Public Member Functions
DomainUnloader (AppDomain domain)
void Unload ()
Private Member Functions
void UnloadOnThread ()
Private Attributes
Thread thread
AppDomain domain
Constructor & Destructor Documentation
DomainUnloader()
NUnit.Engine.Services.DomainManager.DomainUnloader.DomainUnloader (AppDomain domain) inline
References NUnit.Engine.Services.DomainManager.DomainUnloader.domain.
Member Function Documentation
Unload()
void NUnit.Engine.Services.DomainManager.DomainUnloader.Unload () inline
References NUnit.Common.Logger.Error(), NUnit.Common.Logger.Info(), NUnit.Engine.Services.DomainManager.log, NUnit.Engine.Services.DomainManager.DomainUnloader.thread, and NUnit.Engine.Services.DomainManager.DomainUnloader.UnloadOnThread().
Referenced by NUnit.Engine.Services.DomainManager.Unload().
UnloadOnThread()
void NUnit.Engine.Services.DomainManager.DomainUnloader.UnloadOnThread () inline private
References NUnit.Engine.Services.DomainManager.DeleteCacheDir(), NUnit.Engine.Services.DomainManager.DomainUnloader.domain, NUnit.Common.Logger.Error(), and NUnit.Engine.Services.DomainManager.log.
Referenced by NUnit.Engine.Services.DomainManager.DomainUnloader.Unload().
Member Data Documentation
thread
Thread NUnit.Engine.Services.DomainManager.DomainUnloader.thread private
Referenced by NUnit.Engine.Services.DomainManager.DomainUnloader.Unload().
domain
AppDomain NUnit.Engine.Services.DomainManager.DomainUnloader.domain private
Referenced by NUnit.Engine.Services.DomainManager.DomainUnloader.DomainUnloader(), and NUnit.Engine.Services.DomainManager.DomainUnloader.UnloadOnThread().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Services/DomainManager.cs