Doc: IGLib EXTENDED: AForge.Imaging.Textures.MarbleTexture Class Reference
AForge.Imaging.Textures.MarbleTexture Class Reference
Marble texture.
Public Member Functions
MarbleTexture ()
Initializes a new instance of the MarbleTexture class.
MarbleTexture (double xPeriod, double yPeriod)
Initializes a new instance of the MarbleTexture class.
float[,] Generate (int width, int height)
Generate texture.
void Reset ()
Reset generator.
Properties
double XPeriod [get, set]
X period value, ≥ 2.
double YPeriod [get, set]
Y period value, ≥ 2.
Private Attributes
AForge.Math.PerlinNoise noise = new AForge.Math.PerlinNoise(2, 0.65, 1.0 / 32, 1.0)
Random rand = new Random()
int r
double xPeriod = 5.0
double yPeriod = 10.0
Detailed Description
Marble texture.
The texture generator creates textures with effect of marble. The XPeriod and YPeriod properties allow to control the look of marble texture in X/Y directions.
The generator is based on the Perlin noise function.
Sample usage:
// create texture generator
MarbleTexture textureGenerator = new MarbleTexture();
// generate new texture
float[,] texture = textureGenerator.Generate(320, 240);
// convert it to image to visualize
Bitmap textureImage = TextureTools.ToBitmap(texture);
Result image:
Constructor & Destructor Documentation
MarbleTexture() [1/2]
AForge.Imaging.Textures.MarbleTexture.MarbleTexture () inline
Initializes a new instance of the MarbleTexture class.
References AForge.Imaging.Textures.MarbleTexture.Reset().
MarbleTexture() [2/2]
AForge.Imaging.Textures.MarbleTexture.MarbleTexture (double xPeriod, double yPeriod) inline
Initializes a new instance of the MarbleTexture class.
Parameters
xPeriod X period value.
yPeriod Y period value.
References AForge.Imaging.Textures.MarbleTexture.Reset(), AForge.Imaging.Textures.MarbleTexture.xPeriod, and AForge.Imaging.Textures.MarbleTexture.yPeriod.
Member Function Documentation
Generate()
float [,] AForge.Imaging.Textures.MarbleTexture.Generate (int width, int height) inline
Generate texture.
Parameters
width Texture's width.
height Texture's height.
Returns
Two dimensional array of intensities.
Generates new texture of the specified size.
Implements AForge.Imaging.Textures.ITextureGenerator.
References AForge.Math.PerlinNoise.Function2D(), AForge.Imaging.Textures.MarbleTexture.noise, AForge.Imaging.Textures.MarbleTexture.r, AForge.Imaging.Textures.MarbleTexture.xPeriod, and AForge.Imaging.Textures.MarbleTexture.yPeriod.
Reset()
void AForge.Imaging.Textures.MarbleTexture.Reset () inline
Reset generator.
Regenerates internal random numbers.
Implements AForge.Imaging.Textures.ITextureGenerator.
References AForge.Imaging.Textures.MarbleTexture.r, and AForge.Imaging.Textures.MarbleTexture.rand.
Referenced by AForge.Imaging.Textures.MarbleTexture.MarbleTexture().
Member Data Documentation
noise
AForge.Math.PerlinNoise AForge.Imaging.Textures.MarbleTexture.noise = new AForge.Math.PerlinNoise(2, 0.65, 1.0 / 32, 1.0) private
Referenced by AForge.Imaging.Textures.MarbleTexture.Generate().
rand
Random AForge.Imaging.Textures.MarbleTexture.rand = new Random() private
Referenced by AForge.Imaging.Textures.MarbleTexture.Reset().
r
int AForge.Imaging.Textures.MarbleTexture.r private
Referenced by AForge.Imaging.Textures.MarbleTexture.Generate(), and AForge.Imaging.Textures.MarbleTexture.Reset().
xPeriod
double AForge.Imaging.Textures.MarbleTexture.xPeriod = 5.0 private
Referenced by AForge.Imaging.Textures.MarbleTexture.Generate(), and AForge.Imaging.Textures.MarbleTexture.MarbleTexture().
yPeriod
double AForge.Imaging.Textures.MarbleTexture.yPeriod = 10.0 private
Referenced by AForge.Imaging.Textures.MarbleTexture.Generate(), and AForge.Imaging.Textures.MarbleTexture.MarbleTexture().
Property Documentation
XPeriod
double AForge.Imaging.Textures.MarbleTexture.XPeriod get set
X period value, ≥ 2.
Default value is set to 5.
YPeriod
double AForge.Imaging.Textures.MarbleTexture.YPeriod get set
Y period value, ≥ 2.
Default value is set to 10.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Textures/MarbleTexture.cs