Doc: IGLib EXTENDED: Meta.Numerics.Statistics.Distributions.IParameterizedDistribution Interface Reference
Meta.Numerics.Statistics.Distributions.IParameterizedDistribution Interface Reference
Represents an parameterized likelihood distribution.
Public Member Functions
double[] GetParameters ()
Gets the parameter values of the distribution.
void SetParameters (IList< double > parameters)
Sets the parameter values of the distribution.
double Likelihood (double x)
Gets the likelihood of a value, given the current parameters.
Detailed Description
Represents an parameterized likelihood distribution.
Member Function Documentation
GetParameters()
double [] Meta.Numerics.Statistics.Distributions.IParameterizedDistribution.GetParameters ()
Gets the parameter values of the distribution.
Returns
The parameter values characterizing the distribution.
Implemented in Meta.Numerics.Statistics.Distributions.WeibullDistribution, Meta.Numerics.Statistics.Distributions.LognormalDistribution, Meta.Numerics.Statistics.Distributions.NormalDistribution, Meta.Numerics.Statistics.Distributions.LogisticDistribution, and Meta.Numerics.Statistics.Distributions.ExponentialDistribution.
Referenced by Meta.Numerics.Statistics.Sample.MaximumLikelihoodFit().
SetParameters()
void Meta.Numerics.Statistics.Distributions.IParameterizedDistribution.SetParameters (IList< double > parameters)
Sets the parameter values of the distribution.
Parameters
parameters A list of parameter values.
Implemented in Meta.Numerics.Statistics.Distributions.WeibullDistribution, Meta.Numerics.Statistics.Distributions.LognormalDistribution, Meta.Numerics.Statistics.Distributions.NormalDistribution, Meta.Numerics.Statistics.Distributions.LogisticDistribution, and Meta.Numerics.Statistics.Distributions.ExponentialDistribution.
Referenced by Meta.Numerics.Statistics.Sample.MaximumLikelihoodFit().
Likelihood()
double Meta.Numerics.Statistics.Distributions.IParameterizedDistribution.Likelihood (double x)
Gets the likelihood of a value, given the current parameters.
Parameters
x The value.
Returns
The likelihood of the value.
Implemented in Meta.Numerics.Statistics.Distributions.WeibullDistribution, Meta.Numerics.Statistics.Distributions.LognormalDistribution, Meta.Numerics.Statistics.Distributions.NormalDistribution, Meta.Numerics.Statistics.Distributions.LogisticDistribution, and Meta.Numerics.Statistics.Distributions.ExponentialDistribution.
Referenced by Meta.Numerics.Statistics.Sample.MaximumLikelihoodFit().
The documentation for this interface was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/Distributions/Distribution.cs