Doc: IGLib EXTENDED: alglib.testlaguerreunit Class Reference
alglib.testlaguerreunit Class Reference
Static Public Member Functions
static bool testlaguerre (bool silent)
static bool testlaguerre (bool silent)
static bool _pexec_testlaguerre (bool silent)
Member Function Documentation
testlaguerre() [1/2]
static bool alglib.testlaguerreunit.testlaguerre (bool silent) inline static
References alglib.laguerre.laguerrecalculate(), alglib.laguerre.laguerrecoefficients(), alglib.laguerre.laguerresum(), and alglib.math.randomreal().
Referenced by alglib.testlaguerreunit._pexec_testlaguerre(), and _Test.Main().
testlaguerre() [2/2]
static bool alglib.testlaguerreunit.testlaguerre (bool silent) inline static
References alglib.laguerre.laguerrecalculate(), alglib.laguerre.laguerrecoefficients(), alglib.laguerre.laguerresum(), and alglib.math.randomreal().
_pexec_testlaguerre()
static bool alglib.testlaguerreunit._pexec_testlaguerre (bool silent) inline static
References alglib.testlaguerreunit.testlaguerre().
Referenced by _Test.Main().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs