Doc: IGLib EXTENDED: NeuronDotNet.Core.Backpropagation.ActivationNeuron Class Reference
NeuronDotNet.Core.Backpropagation.ActivationNeuron Class Reference
Activation Neuron is a buiding block of a back-propagation neural network.
Public Member Functions
ActivationNeuron (ActivationLayer parent)
Create a new activation neuron
void Run ()
Obtains input from source synapses and activates to update the output
void EvaluateError ()
Backpropagates the target synapses and evaluates the error
void Learn (double learningRate)
Optimizes the bias value (if not UseFixedBiasValues) and the weights of all the source synapses using back propagation algorithm
Properties
double Input [get, set]
Gets or sets the neuron input.
double Output [get]
Gets the output of the neuron.
double Error [get]
Gets the neuron error
double Bias [get]
Gets the neuron bias
IList< ISynapse > SourceSynapses [get]
Gets the list of source synapses associated with this neuron
IList< ISynapse > TargetSynapses [get]
Gets the list of target synapses associated with this neuron
ActivationLayer Parent [get]
Gets the parent layer containing this neuron
ILayer INeuron. Parent [get]
Properties inherited from NeuronDotNet.Core.INeuron
double Input [get, set]
Gets or sets the neuron input.
double Output [get]
Gets the output of the neuron.
IList< ISynapse > SourceSynapses [get]
Gets the list of source synapses associated with this neuron
IList< ISynapse > TargetSynapses [get]
Gets the list of target synapses associated with this neuron
ILayer Parent [get]
Gets the parent layer containing this neuron
Private Attributes
readonly IList< ISynapse > sourceSynapses = new List<ISynapse>()
readonly IList< ISynapse > targetSynapses = new List<ISynapse>()
ActivationLayer parent
Detailed Description
Activation Neuron is a buiding block of a back-propagation neural network.
Constructor & Destructor Documentation
ActivationNeuron()
NeuronDotNet.Core.Backpropagation.ActivationNeuron.ActivationNeuron (ActivationLayer parent) inline
Create a new activation neuron
Parameters
parent The parent layer containing this neuron
Exceptions
System.ArgumentNullException If parent is null
References NeuronDotNet.Core.Backpropagation.ActivationNeuron.parent, and NeuronDotNet.Core.Helper.ValidateNotNull().
Member Function Documentation
Run()
void NeuronDotNet.Core.Backpropagation.ActivationNeuron.Run () inline
Obtains input from source synapses and activates to update the output
Implements NeuronDotNet.Core.INeuron.
References NeuronDotNet.Core.Backpropagation.ActivationLayer.Activate(), NeuronDotNet.Core.Backpropagation.ActivationNeuron.parent, and NeuronDotNet.Core.Backpropagation.ActivationNeuron.sourceSynapses.
EvaluateError()
void NeuronDotNet.Core.Backpropagation.ActivationNeuron.EvaluateError () inline
Backpropagates the target synapses and evaluates the error
References NeuronDotNet.Core.Backpropagation.BackpropagationSynapse.Backpropagate(), NeuronDotNet.Core.Backpropagation.ActivationLayer.Derivative(), NeuronDotNet.Core.Backpropagation.ActivationNeuron.parent, and NeuronDotNet.Core.Backpropagation.ActivationNeuron.targetSynapses.
Learn()
void NeuronDotNet.Core.Backpropagation.ActivationNeuron.Learn (double learningRate) inline
Optimizes the bias value (if not UseFixedBiasValues) and the weights of all the source synapses using back propagation algorithm
Parameters
learningRate The current learning rate (this depends on training progress as well)
Implements NeuronDotNet.Core.INeuron.
References NeuronDotNet.Core.Backpropagation.ActivationNeuron.parent, and NeuronDotNet.Core.Backpropagation.ActivationNeuron.sourceSynapses.
Member Data Documentation
sourceSynapses
readonly IList<ISynapse> NeuronDotNet.Core.Backpropagation.ActivationNeuron.sourceSynapses = new List<ISynapse>() private
Referenced by NeuronDotNet.Core.Backpropagation.ActivationNeuron.Learn(), and NeuronDotNet.Core.Backpropagation.ActivationNeuron.Run().
targetSynapses
readonly IList<ISynapse> NeuronDotNet.Core.Backpropagation.ActivationNeuron.targetSynapses = new List<ISynapse>() private
Referenced by NeuronDotNet.Core.Backpropagation.ActivationNeuron.EvaluateError().
parent
ActivationLayer NeuronDotNet.Core.Backpropagation.ActivationNeuron.parent private
Referenced by NeuronDotNet.Core.Backpropagation.ActivationNeuron.ActivationNeuron(), NeuronDotNet.Core.Backpropagation.ActivationNeuron.EvaluateError(), NeuronDotNet.Core.Backpropagation.ActivationNeuron.Learn(), and NeuronDotNet.Core.Backpropagation.ActivationNeuron.Run().
Property Documentation
Input
double NeuronDotNet.Core.Backpropagation.ActivationNeuron.Input get set
Gets or sets the neuron input.
Input to the neuron. For input neurons, this value is specified by user, whereas other neurons will have their inputs updated when the source synapses propagate
Output
double NeuronDotNet.Core.Backpropagation.ActivationNeuron.Output get
Gets the output of the neuron.
Neuron Output
Error
double NeuronDotNet.Core.Backpropagation.ActivationNeuron.Error get
Gets the neuron error
Neuron Error
Bias
double NeuronDotNet.Core.Backpropagation.ActivationNeuron.Bias get
Gets the neuron bias
The current value of neuron bias
SourceSynapses
IList<ISynapse> NeuronDotNet.Core.Backpropagation.ActivationNeuron.SourceSynapses get
Gets the list of source synapses associated with this neuron
A list of source synapses. It can neither be null, nor contain null elements.
TargetSynapses
IList<ISynapse> NeuronDotNet.Core.Backpropagation.ActivationNeuron.TargetSynapses get
Gets the list of target synapses associated with this neuron
A list of target synapses. It can neither be null, nor contains null elements.
Parent [1/2]
ActivationLayer NeuronDotNet.Core.Backpropagation.ActivationNeuron.Parent get
Gets the parent layer containing this neuron
The parent layer containing this neuron. It is never null
Parent [2/2]
ILayer INeuron. NeuronDotNet.Core.Backpropagation.ActivationNeuron.Parent get private
The documentation for this class was generated from the following file:
shelldev/lib/externalextended/NeuronDotNetGPL/source/Core/Backpropagation/ActivationNeuron.cs