Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGELSY Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGELSY Class Reference
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGELSY (ILAENV ilaenv, DLAMCH dlamch, DLANGE dlange, DCOPY dcopy, DGEQP3 dgeqp3, DLABAD dlabad, DLAIC1 dlaic1, DLASCL dlascl, DLASET dlaset, DORMQR dormqr, DORMRZ dormrz, DTRSM dtrsm, DTZRZF dtzrzf, XERBLA xerbla)
DGELSY ()
void Run (int M, int N, int NRHS, ref double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB, ref int[] JPVT, int offset_jpvt, double RCOND, ref int RANK, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
ILAENV _ilaenv
DLAMCH _dlamch
DLANGE _dlange
DCOPY _dcopy
DGEQP3 _dgeqp3
DLABAD _dlabad
DLAIC1 _dlaic1
DLASCL _dlascl
DLASET _dlaset
DORMQR _dormqr
DORMRZ _dormrz
DTRSM _dtrsm
DTZRZF _dtzrzf
XERBLA _xerbla
Static Private Attributes
const int IMAX = 1
const int IMIN = 2
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGELSY computes the minimum-norm solution to a real linear least squares problem: minimize || A * X - B || using a complete orthogonal factorization of A. A is an M-by-N matrix which may be rank-deficient.
Several right hand side vectors b and solution vectors x can be handled in a single call; they are stored as the columns of the M-by-NRHS right hand side matrix B and the N-by-NRHS solution matrix X.
The routine first computes a QR factorization with column pivoting: A * P = Q * [ R11 R12 ] [ 0 R22 ] with R11 defined as the largest leading submatrix whose estimated condition number is less than 1/RCOND. The order of R11, RANK, is the effective rank of A.
Then, R22 is considered to be negligible, and R12 is annihilated by orthogonal transformations from the right, arriving at the complete orthogonal factorization: A * P = Q * [ T11 0 ] * Z [ 0 0 ] The minimum-norm solution is then X = P * Z' [ inv(T11)*Q1'*B ] [ 0 ] where Q1 consists of the first RANK columns of Q.
This routine is basically identical to the original xGELSX except three differences: o The call to the subroutine xGEQPF has been substituted by the the call to the subroutine xGEQP3. This subroutine is a Blas-3 version of the QR factorization with column pivoting. o Matrix B (the right hand side) is updated with Blas-3. o The permutation of matrix B (the right hand side) is faster and more simple.
/summary>
Constructor & Destructor Documentation
DGELSY() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGELSY.DGELSY (ILAENV ilaenv, DLAMCH dlamch, DLANGE dlange, DCOPY dcopy, DGEQP3 dgeqp3, DLABAD dlabad, DLAIC1 dlaic1, DLASCL dlascl, DLASET dlaset, DORMQR dormqr, DORMRZ dormrz, DTRSM dtrsm, DTZRZF dtzrzf, XERBLA xerbla) inline
DGELSY() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGELSY.DGELSY () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGELSY.Run (int M, int N, int NRHS, ref double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB, ref int[] JPVT, int offset_jpvt, double RCOND, ref int RANK, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DGELSY computes the minimum-norm solution to a real linear least squares problem: minimize || A * X - B || using a complete orthogonal factorization of A. A is an M-by-N matrix which may be rank-deficient.
Several right hand side vectors b and solution vectors x can be handled in a single call; they are stored as the columns of the M-by-NRHS right hand side matrix B and the N-by-NRHS solution matrix X.
The routine first computes a QR factorization with column pivoting: A * P = Q * [ R11 R12 ] [ 0 R22 ] with R11 defined as the largest leading submatrix whose estimated condition number is less than 1/RCOND. The order of R11, RANK, is the effective rank of A.
Then, R22 is considered to be negligible, and R12 is annihilated by orthogonal transformations from the right, arriving at the complete orthogonal factorization: A * P = Q * [ T11 0 ] * Z [ 0 0 ] The minimum-norm solution is then X = P * Z' [ inv(T11)*Q1'*B ] [ 0 ] where Q1 consists of the first RANK columns of Q.
This routine is basically identical to the original xGELSX except three differences: o The call to the subroutine xGEQPF has been substituted by the the call to the subroutine xGEQP3. This subroutine is a Blas-3 version of the QR factorization with column pivoting. o Matrix B (the right hand side) is updated with Blas-3. o The permutation of matrix B (the right hand side) is faster and more simple.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. 0. /param>
Parameters
NRHS (input) INTEGER The number of right hand sides, i.e., the number of columns of matrices B and X. NRHS .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the M-by-N matrix A. On exit, A has been overwritten by details of its complete orthogonal factorization. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
B (input/output) DOUBLE PRECISION array, dimension (LDB,NRHS) On entry, the M-by-NRHS right hand side matrix B. On exit, the N-by-NRHS solution matrix X. /param>
Parameters
LDB (input) INTEGER The leading dimension of the array B. LDB .GE. max(1,M,N). /param>
Parameters
JPVT (input/output) INTEGER array, dimension (N) On entry, if JPVT(i) .ne. 0, the i-th column of A is permuted to the front of AP, otherwise column i is a free column. On exit, if JPVT(i) = k, then the i-th column of AP was the k-th column of A. /param>
Parameters
RCOND (input) DOUBLE PRECISION RCOND is used to determine the effective rank of A, which is defined as the order of the largest leading triangular submatrix R11 in the QR factorization with pivoting of A, whose estimated condition number .LT. 1/RCOND. /param>
Parameters
RANK (output) INTEGER The effective rank of A, i.e., the order of the submatrix R11. This is the same as the order of the submatrix T11 in the complete orthogonal factorization of A. /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. The unblocked strategy requires that: LWORK .GE. MAX(MN+3*N+1, 2*MN+NRHS), where MN = min(M, N). The block algorithm requires that: LWORK .GE. MAX(MN+2*N+NB*(N+1), 2*MN+NB*NRHS), where NB is an upper bound on the blocksize returned by ILAENV for the routines DGEQP3, DTZRZF, STZRQF, DORMQR, and DORMRZ.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: If INFO = -i, the i-th argument had an illegal value. /param>
References DotNumerics.LinearAlgebra.CSLapack.DGELSY.IMAX, DotNumerics.LinearAlgebra.CSLapack.DGELSY.IMIN, DotNumerics.LinearAlgebra.CSLapack.DGELSY.ONE, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLABAD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASET.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANGE.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.LinearAlgebra.CSLapack.DTZRZF.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQP3.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAIC1.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRSM.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMRZ.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGELSY.ZERO.
Member Data Documentation
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DGELSY._ilaenv private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DGELSY._dlamch private
_dlange
DLANGE DotNumerics.LinearAlgebra.CSLapack.DGELSY._dlange private
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DGELSY._dcopy private
_dgeqp3
DGEQP3 DotNumerics.LinearAlgebra.CSLapack.DGELSY._dgeqp3 private
_dlabad
DLABAD DotNumerics.LinearAlgebra.CSLapack.DGELSY._dlabad private
_dlaic1
DLAIC1 DotNumerics.LinearAlgebra.CSLapack.DGELSY._dlaic1 private
_dlascl
DLASCL DotNumerics.LinearAlgebra.CSLapack.DGELSY._dlascl private
_dlaset
DLASET DotNumerics.LinearAlgebra.CSLapack.DGELSY._dlaset private
_dormqr
DORMQR DotNumerics.LinearAlgebra.CSLapack.DGELSY._dormqr private
_dormrz
DORMRZ DotNumerics.LinearAlgebra.CSLapack.DGELSY._dormrz private
_dtrsm
DTRSM DotNumerics.LinearAlgebra.CSLapack.DGELSY._dtrsm private
_dtzrzf
DTZRZF DotNumerics.LinearAlgebra.CSLapack.DGELSY._dtzrzf private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGELSY._xerbla private
IMAX
const int DotNumerics.LinearAlgebra.CSLapack.DGELSY.IMAX = 1 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGELSY.Run().
IMIN
const int DotNumerics.LinearAlgebra.CSLapack.DGELSY.IMIN = 2 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGELSY.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DGELSY.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGELSY.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGELSY.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGELSY.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgelsy.cs