Doc: IGLib EXTENDED: NUnit.Common.Tests.AssemblyHelperTests Class Reference
NUnit.Common.Tests.AssemblyHelperTests Class Reference
Public Member Functions
void GetNameForAssembly ()
void GetPathForAssembly ()
void GetPathForType ()
void GetAssemblyPathFromCodeBase (string uri, string expectedPath)
Static Private Attributes
static readonly string THIS_ASSEMBLY_PATH = "nunit.framework.tests.dll"
static readonly string THIS_ASSEMBLY_NAME = "nunit.framework.tests"
Member Function Documentation
GetNameForAssembly()
void NUnit.Common.Tests.AssemblyHelperTests.GetNameForAssembly () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Common.AssemblyHelper.GetAssemblyName(), and NUnit.Framework.Assert.That().
GetPathForAssembly()
void NUnit.Common.Tests.AssemblyHelperTests.GetPathForAssembly () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Common.AssemblyHelper.GetAssemblyPath(), and NUnit.Framework.Assert.That().
GetPathForType()
void NUnit.Common.Tests.AssemblyHelperTests.GetPathForType () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Common.AssemblyHelper.GetAssemblyPath(), and NUnit.Framework.Assert.That().
GetAssemblyPathFromCodeBase()
void NUnit.Common.Tests.AssemblyHelperTests.GetAssemblyPathFromCodeBase (string uri, string expectedPath) inline
References NUnit.Common.AssemblyHelper.GetAssemblyPathFromCodeBase(), NUnit.Framework.Is.SamePath(), and NUnit.Framework.Assert.That().
Member Data Documentation
THIS_ASSEMBLY_PATH
readonly string NUnit.Common.Tests.AssemblyHelperTests.THIS_ASSEMBLY_PATH = "nunit.framework.tests.dll" static private
THIS_ASSEMBLY_NAME
readonly string NUnit.Common.Tests.AssemblyHelperTests.THIS_ASSEMBLY_NAME = "nunit.framework.tests" static private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/tests/AssemblyHelperTests.cs