Doc: IGLib EXTENDED: NUnit.Framework.Interfaces.IApplyToContext Interface Reference
NUnit.Framework.Interfaces.IApplyToContext Interface Reference
The IApplyToContext interface is implemented by attributes that want to make changes to the execution context before a test is run.
Public Member Functions
void ApplyToContext (TestExecutionContext context)
Apply changes to the execution context
Detailed Description
The IApplyToContext interface is implemented by attributes that want to make changes to the execution context before a test is run.
Member Function Documentation
ApplyToContext()
void NUnit.Framework.Interfaces.IApplyToContext.ApplyToContext (TestExecutionContext context)
Apply changes to the execution context
Parameters
context The execution context
Implemented in NUnit.Framework.ParallelizableAttribute, NUnit.Framework.TimeoutAttribute, NUnit.Framework.SetCultureAttribute, and NUnit.Framework.SetUICultureAttribute.
Referenced by NUnit.Framework.Internal.Commands.ApplyChangesToContextCommand.Execute(), NUnit.Framework.Attributes.ApplyToContextTests.SetCultureAttribute(), NUnit.Framework.Attributes.ApplyToContextTests.SetUICultureAttribute(), and NUnit.Framework.Attributes.ApplyToContextTests.TimeoutAttribute().
The documentation for this interface was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Interfaces/IApplyToContext.cs