Doc: IGLib EXTENDED: AForge.Genetic.Population Class Reference
AForge.Genetic.Population Class Reference
Population of chromosomes.
Public Member Functions
Population (int size, IChromosome ancestor, IFitnessFunction fitnessFunction, ISelectionMethod selectionMethod)
Initializes a new instance of the Population class.
void Regenerate ()
Regenerate population.
virtual void Crossover ()
Do crossover in the population.
virtual void Mutate ()
Do mutation in the population.
virtual void Selection ()
Do selection.
void RunEpoch ()
Run one epoch of the population.
void Shuffle ()
Shuffle randomly current population.
void AddChromosome (IChromosome chromosome)
Add chromosome to the population.
void Migrate (Population anotherPopulation, int numberOfMigrants, ISelectionMethod migrantsSelector)
Perform migration between two populations.
void Resize (int newPopulationSize)
Resize population to the new specified size.
void Resize (int newPopulationSize, ISelectionMethod membersSelector)
Resize population to the new specified size.
Properties
double CrossoverRate [get, set]
Crossover rate, [0.1, 1].
double MutationRate [get, set]
Mutation rate, [0.1, 1].
double RandomSelectionPortion [get, set]
Random selection portion, [0, 0.9].
bool AutoShuffling [get, set]
Determines of auto shuffling is on or off.
ISelectionMethod SelectionMethod [get, set]
Selection method to use with the population.
IFitnessFunction FitnessFunction [get, set]
Fitness function to apply to the population.
double FitnessMax [get]
Maximum fitness of the population.
double FitnessSum [get]
Summary fitness of the population.
double FitnessAvg [get]
Average fitness of the population.
IChromosome BestChromosome [get]
Best chromosome of the population.
int Size [get]
Size of the population.
IChromosome this[int index] [get]
Get chromosome with specified index.
Private Member Functions
void FindBestChromosome ()
Private Attributes
IFitnessFunction fitnessFunction
ISelectionMethod selectionMethod
List< IChromosome > population = new List<IChromosome>()
int size
double randomSelectionPortion = 0.0
bool autoShuffling = false
double crossoverRate = 0.75
double mutationRate = 0.10
double fitnessMax = 0
double fitnessSum = 0
double fitnessAvg = 0
IChromosome bestChromosome = null
Static Private Attributes
static ThreadSafeRandom rand = new ThreadSafeRandom()
Detailed Description
Population of chromosomes.
The class represents population - collection of individuals (chromosomes) and provides functionality for common population's life cycle - population growing with help of genetic operators and selection of chromosomes to new generation with help of selection algorithm. The class may work with any type of chromosomes implementing IChromosome interface, use any type of fitness functions implementing IFitnessFunction interface and use any type of selection algorithms implementing ISelectionMethod interface.
Constructor & Destructor Documentation
Population()
AForge.Genetic.Population.Population (int size, IChromosome ancestor, IFitnessFunction fitnessFunction, ISelectionMethod selectionMethod) inline
Initializes a new instance of the Population class.
Parameters
size Initial size of population.
ancestor Ancestor chromosome to use for population creatioin.
fitnessFunction Fitness function to use for calculating chromosome's fitness values.
selectionMethod Selection algorithm to use for selection chromosome's to new generation.
Creates new population of specified size. The specified ancestor becomes first member of the population and is used to create other members with same parameters, which were used for ancestor's creation.
Exceptions
ArgumentException Too small population's size was specified. The exception is thrown in the case if size is smaller than 2.
References AForge.Genetic.IChromosome.Clone(), AForge.Genetic.IChromosome.CreateNew(), AForge.Genetic.IChromosome.Evaluate(), AForge.Genetic.Population.fitnessFunction, AForge.Genetic.Population.population, AForge.Genetic.Population.selectionMethod, and AForge.Genetic.Population.size.
Member Function Documentation
Regenerate()
void AForge.Genetic.Population.Regenerate () inline
Regenerate population.
The method regenerates population filling it with random chromosomes.
References AForge.Genetic.IChromosome.CreateNew(), AForge.Genetic.Population.fitnessFunction, AForge.Genetic.Population.population, and AForge.Genetic.Population.size.
Crossover()
virtual void AForge.Genetic.Population.Crossover () inline virtual
Do crossover in the population.
The method walks through the population and performs crossover operator taking each two chromosomes in the order of their presence in the population. The total amount of paired chromosomes is determined by crossover rate.
References AForge.Genetic.IChromosome.Crossover(), AForge.Genetic.Population.crossoverRate, AForge.Genetic.IChromosome.Evaluate(), AForge.Genetic.Population.fitnessFunction, AForge.ThreadSafeRandom.NextDouble(), AForge.Genetic.Population.population, AForge.Genetic.Population.rand, and AForge.Genetic.Population.size.
Referenced by AForge.Genetic.Population.RunEpoch().
Mutate()
virtual void AForge.Genetic.Population.Mutate () inline virtual
Do mutation in the population.
The method walks through the population and performs mutation operator taking each chromosome one by one. The total amount of mutated chromosomes is determined by mutation rate.
References AForge.Genetic.Population.fitnessFunction, AForge.Genetic.Population.mutationRate, AForge.ThreadSafeRandom.NextDouble(), AForge.Genetic.Population.population, AForge.Genetic.Population.rand, and AForge.Genetic.Population.size.
Referenced by AForge.Genetic.Population.RunEpoch().
Selection()
virtual void AForge.Genetic.Population.Selection () inline virtual
Do selection.
The method applies selection operator to the current population. Using specified selection algorithm it selects members to the new generation from current generates and adds certain amount of random members, if is required (see RandomSelectionPortion).
References AForge.Genetic.ISelectionMethod.ApplySelection(), AForge.Genetic.IChromosome.CreateNew(), AForge.Genetic.Population.FindBestChromosome(), AForge.Genetic.Population.fitnessFunction, AForge.Genetic.Population.population, AForge.Genetic.Population.randomSelectionPortion, AForge.Genetic.Population.selectionMethod, and AForge.Genetic.Population.size.
Referenced by AForge.Genetic.Population.RunEpoch().
RunEpoch()
void AForge.Genetic.Population.RunEpoch () inline
Run one epoch of the population.
The method runs one epoch of the population, doing crossover, mutation and selection by calling Crossover, Mutate and Selection.
References AForge.Genetic.Population.autoShuffling, AForge.Genetic.Population.Crossover(), AForge.Genetic.Population.Mutate(), AForge.Genetic.Population.Selection(), and AForge.Genetic.Population.Shuffle().
Referenced by AForge.Neuro.Learning.EvolutionaryLearning.RunEpoch(), TSP.MainForm.SearchSolution(), Optimization1D.MainForm.SearchSolution(), Approximation.MainForm.SearchSolution(), and TimeSeries.MainForm.SearchSolution().
Shuffle()
void AForge.Genetic.Population.Shuffle () inline
Shuffle randomly current population.
Population shuffling may be useful in cases when selection operator results in not random order of chromosomes (for example, after elite selection population may be ordered in ascending/descending order).
References AForge.ThreadSafeRandom.Next(), AForge.Genetic.Population.population, AForge.Genetic.Population.rand, and AForge.Genetic.Population.size.
Referenced by AForge.Genetic.Population.RunEpoch().
AddChromosome()
void AForge.Genetic.Population.AddChromosome (IChromosome chromosome) inline
Add chromosome to the population.
Parameters
chromosome Chromosome to add to the population.
The method adds specified chromosome to the current population. Manual adding of chromosome maybe useful, when it is required to add some initialized chromosomes instead of random.
<note>Adding chromosome manually should be done very carefully, since it may break the population. The manually added chromosome must have the same type and initialization parameters as the ancestor passed to constructor.</note>
References AForge.Genetic.IChromosome.Evaluate(), AForge.Genetic.Population.fitnessFunction, and AForge.Genetic.Population.population.
Migrate()
void AForge.Genetic.Population.Migrate (Population anotherPopulation, int numberOfMigrants, ISelectionMethod migrantsSelector) inline
Perform migration between two populations.
Parameters
anotherPopulation Population to do migration with.
numberOfMigrants Number of chromosomes from each population to migrate.
migrantsSelector Selection algorithm used to select chromosomes to migrate.
The method performs migration between two populations - current and the anotherPopulation specified one. During migration numberOfMigrants specified number of chromosomes is choosen from each population using migrantsSelector specified selection algorithms and put into another population replacing worst members there.
References AForge.Genetic.ISelectionMethod.ApplySelection(), AForge.Genetic.Population.FindBestChromosome(), AForge.Genetic.Population.population, AForge.Genetic.Population.size, and AForge.Genetic.Population.Size.
Resize() [1/2]
void AForge.Genetic.Population.Resize (int newPopulationSize) inline
Resize population to the new specified size.
Parameters
newPopulationSize New size of population.
The method does resizing of population. In the case if population should grow, it just adds missing number of random members. In the case if population should get smaller, the population's selection method is used to reduce the population.
Exceptions
ArgumentException Too small population's size was specified. The exception is thrown in the case if newPopulationSize is smaller than 2.
References AForge.Genetic.Population.selectionMethod.
Resize() [2/2]
void AForge.Genetic.Population.Resize (int newPopulationSize, ISelectionMethod membersSelector) inline
Resize population to the new specified size.
Parameters
newPopulationSize New size of population.
membersSelector Selection algorithm to use in the case if population should get smaller.
The method does resizing of population. In the case if population should grow, it just adds missing number of random members. In the case if population should get smaller, the specified selection method is used to reduce the population.
Exceptions
ArgumentException Too small population's size was specified. The exception is thrown in the case if newPopulationSize is smaller than 2.
References AForge.Genetic.ISelectionMethod.ApplySelection(), AForge.Genetic.Population.fitnessFunction, AForge.Genetic.Population.population, and AForge.Genetic.Population.size.
FindBestChromosome()
void AForge.Genetic.Population.FindBestChromosome () inline private
References AForge.Genetic.Population.bestChromosome, AForge.Genetic.IChromosome.Fitness, AForge.Genetic.Population.fitnessAvg, AForge.Genetic.Population.fitnessMax, AForge.Genetic.Population.fitnessSum, AForge.Genetic.Population.population, and AForge.Genetic.Population.size.
Referenced by AForge.Genetic.Population.Migrate(), and AForge.Genetic.Population.Selection().
Member Data Documentation
fitnessFunction
IFitnessFunction AForge.Genetic.Population.fitnessFunction private
Referenced by AForge.Genetic.Population.AddChromosome(), AForge.Genetic.Population.Crossover(), AForge.Genetic.Population.Mutate(), AForge.Genetic.Population.Population(), AForge.Genetic.Population.Regenerate(), AForge.Genetic.Population.Resize(), and AForge.Genetic.Population.Selection().
selectionMethod
ISelectionMethod AForge.Genetic.Population.selectionMethod private
Referenced by AForge.Genetic.Population.Population(), AForge.Genetic.Population.Resize(), and AForge.Genetic.Population.Selection().
population
List<IChromosome> AForge.Genetic.Population.population = new List<IChromosome>() private
Referenced by AForge.Genetic.Population.AddChromosome(), AForge.Genetic.Population.Crossover(), AForge.Genetic.Population.FindBestChromosome(), AForge.Genetic.Population.Migrate(), AForge.Genetic.Population.Mutate(), AForge.Genetic.Population.Population(), AForge.Genetic.Population.Regenerate(), AForge.Genetic.Population.Resize(), AForge.Genetic.Population.Selection(), and AForge.Genetic.Population.Shuffle().
size
int AForge.Genetic.Population.size private
Referenced by AForge.Genetic.Population.Crossover(), AForge.Genetic.Population.FindBestChromosome(), AForge.Genetic.Population.Migrate(), AForge.Genetic.Population.Mutate(), AForge.Genetic.Population.Population(), AForge.Genetic.Population.Regenerate(), AForge.Genetic.Population.Resize(), AForge.Genetic.Population.Selection(), and AForge.Genetic.Population.Shuffle().
randomSelectionPortion
double AForge.Genetic.Population.randomSelectionPortion = 0.0 private
Referenced by AForge.Genetic.Population.Selection().
autoShuffling
bool AForge.Genetic.Population.autoShuffling = false private
Referenced by AForge.Genetic.Population.RunEpoch().
crossoverRate
double AForge.Genetic.Population.crossoverRate = 0.75 private
Referenced by AForge.Genetic.Population.Crossover().
mutationRate
double AForge.Genetic.Population.mutationRate = 0.10 private
Referenced by AForge.Genetic.Population.Mutate().
rand
ThreadSafeRandom AForge.Genetic.Population.rand = new ThreadSafeRandom() static private
Referenced by AForge.Genetic.Population.Crossover(), AForge.Genetic.Population.Mutate(), and AForge.Genetic.Population.Shuffle().
fitnessMax
double AForge.Genetic.Population.fitnessMax = 0 private
Referenced by AForge.Genetic.Population.FindBestChromosome().
fitnessSum
double AForge.Genetic.Population.fitnessSum = 0 private
Referenced by AForge.Genetic.Population.FindBestChromosome().
fitnessAvg
double AForge.Genetic.Population.fitnessAvg = 0 private
Referenced by AForge.Genetic.Population.FindBestChromosome().
bestChromosome
IChromosome AForge.Genetic.Population.bestChromosome = null private
Referenced by AForge.Genetic.Population.FindBestChromosome().
Property Documentation
CrossoverRate
double AForge.Genetic.Population.CrossoverRate get set
Crossover rate, [0.1, 1].
The value determines the amount of chromosomes which participate in crossover.
Default value is set to 0.75.
Referenced by AForge.Neuro.Learning.EvolutionaryLearning.RunEpoch().
MutationRate
double AForge.Genetic.Population.MutationRate get set
Mutation rate, [0.1, 1].
The value determines the amount of chromosomes which participate in mutation.
Defaul value is set to 0.1.
Referenced by AForge.Neuro.Learning.EvolutionaryLearning.RunEpoch().
RandomSelectionPortion
double AForge.Genetic.Population.RandomSelectionPortion get set
Random selection portion, [0, 0.9].
The value determines the amount of chromosomes which will be randomly generated for the new population. The property controls the amount of chromosomes, which are selected to a new population using selection operator, and amount of random chromosomes added to the new population.
Default value is set to 0.
Referenced by AForge.Neuro.Learning.EvolutionaryLearning.RunEpoch().
AutoShuffling
bool AForge.Genetic.Population.AutoShuffling get set
Determines of auto shuffling is on or off.
The property specifies if automatic shuffling needs to be done on each epoch by calling Shuffle method.
Default value is set to false.
SelectionMethod
ISelectionMethod AForge.Genetic.Population.SelectionMethod get set
Selection method to use with the population.
The property sets selection method which is used to select population members for a new population - filter population after reproduction was done with operators like crossover and mutations.
FitnessFunction
IFitnessFunction AForge.Genetic.Population.FitnessFunction get set
Fitness function to apply to the population.
The property sets fitness function, which is used to evaluate usefulness of population's chromosomes. Setting new fitness function causes recalculation of fitness values for all population's members and new best member will be found.
FitnessMax
double AForge.Genetic.Population.FitnessMax get
Maximum fitness of the population.
The property keeps maximum fitness of chromosomes currently existing in the population.
<note>The property is recalculate only after selection or migration was done.</note>
FitnessSum
double AForge.Genetic.Population.FitnessSum get
Summary fitness of the population.
The property keeps summary fitness of all chromosome existing in the population.
<note>The property is recalculate only after selection or migration was done.</note>
FitnessAvg
double AForge.Genetic.Population.FitnessAvg get
Average fitness of the population.
The property keeps average fitness of all chromosome existing in the population.
<note>The property is recalculate only after selection or migration was done.</note>
BestChromosome
IChromosome AForge.Genetic.Population.BestChromosome get
Best chromosome of the population.
The property keeps the best chromosome existing in the population or null if all chromosomes have 0 fitness.
<note>The property is recalculate only after selection or migration was done.</note>
Referenced by AForge.Neuro.Learning.EvolutionaryLearning.RunEpoch(), TSP.MainForm.SearchSolution(), Optimization1D.MainForm.SearchSolution(), Approximation.MainForm.SearchSolution(), and TimeSeries.MainForm.SearchSolution().
Size
int AForge.Genetic.Population.Size get
Size of the population.
The property keeps initial (minimal) size of population. Population always returns to this size after selection operator was applied, which happens after Selection or RunEpoch methods call.
Referenced by AForge.Genetic.Population.Migrate().
this[int index]
IChromosome AForge.Genetic.Population.this[int index] get
Get chromosome with specified index.
Parameters
index Chromosome's index to retrieve.
Allows to access individuals of the population.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Genetic/Population.cs