Doc: IGLib EXTENDED: IG.Forms.ConsoleForm Class Reference
IG.Forms.ConsoleForm Class Reference
Console replacement.
Public Types
enum Styles { Styles.Normal, Styles.Error, Styles.Mark }
Public Member Functions
void SetNormalStyle ()
Sets normal style for console output.
void SetErrorStyle ()
Sets Error Style for console output.
void SetMarkStyle ()
Sets marking (emphasis) style for console output.
ConsoleForm ()
Argument-less constructor, does not launch the window in a parallel thread.
ConsoleForm (string msgtext)
Shows a console consform in a new thread, with message text equal to mshtext and without a title;.
void HideForm ()
void CloseForm ()
Closes the consform by properly (i.e. thread-safe) calling the Close() and Dispose().
void Write (bool block, string str)
void Write (string str)
void WriteLine (bool block, string str)
Writes a string to the output console and appends a newline character.
void WriteLine (string str)
void Write (Char arg)
void Write (Boolean arg)
void Write (Char[] arg)
void Write (Decimal arg)
void Write (Double arg)
void Write (Int32 arg)
void Write (Int64 arg)
void Write (Object arg)
void Write (Single arg)
void Write (UInt32 arg)
void Write (UInt64 arg)
void Write (String arg, Object arg1)
void Write (String arg, Object[] arg1)
void Write (Char[] arg, Int32 arg1, Int32 arg2)
void Write (String arg, Object arg1, Object arg2)
void Write (String arg, Object arg1, Object arg2, Object arg3)
void WriteLine (Char arg)
void WriteLine (Boolean arg)
void WriteLine (Char[] arg)
void WriteLine (Decimal arg)
void WriteLine (Double arg)
void WriteLine (Int32 arg)
void WriteLine (Int64 arg)
void WriteLine (Object arg)
void WriteLine (Single arg)
void WriteLine (UInt32 arg)
void WriteLine (UInt64 arg)
void WriteLine (String arg, Object arg1)
void WriteLine (String arg, Object[] arg1)
void WriteLine (Char[] arg, Int32 arg1, Int32 arg2)
void WriteLine (String arg, Object arg1, Object arg2)
void WriteLine (String arg, Object arg1, Object arg2, Object arg3)
void ReportErrorBas (ReporterBase reporter, ReportType messagelevel, string errorlocation, string errormessage)
void ReserveReportErrorBas (ReporterBase reporter, ReportType messagelevel, string location, string message, Exception ex, Exception ex1)
void ReserveReportError (string errorstr)
virtual void Report (ReportType messagetype, string location, string message, Exception ex)
Basic reporting method (overloaded). Launches an error report, a warning report or s kind of report/message. Supplemental data (such as objects necessary to launch visualize the report or operation typeflags) are obtained from the class' instance.
void Report (ReportType messagetype, string message, Exception ex)
Launches a report. Predominantly for error and warning reports.
void Report (ReportType messagetype, Exception ex, string location)
Launches a report. Predominantly for error and warning reports.
void Report (ReportType messagetype, Exception ex)
Launches a report. Predominantly for error and warning reports.
void Report (ReportType messagetype, string location, string message)
Launches a report.
void Report (ReportType messagetype, string message)
Launches a report.
virtual void ReportError (string location, string message, Exception ex)
Basic error reporting method (overloaded). Supplemental data (such as objects necessary to launch visualize the report or operation typeflags) are obtained from the class' instance.
void ReportError (string message, Exception ex)
Launches an error report.
void ReportError (Exception ex, string location)
Launches an error report.
void ReportError (Exception ex)
Launches an error report. Predominantly for error and warning reports.
void ReportError (string location, string message)
Launches an error report.
void ReportError (string message)
Launches an error report.
virtual void ReportWarning (string location, string message, Exception ex)
Basic warning reporting method (overloaded). Supplemental data (such as objects necessary to launch visualize the report or operation typeflags) are obtained from the class' instance.
void ReportWarning (string message, Exception ex)
Launches a warning report.
void ReportWarning (Exception ex, string location)
Launches a warning report.
void ReportWarning (Exception ex)
Launches a warning report. Predominantly for error and warning reports.
void ReportWarning (string location, string message)
Launches a warning report.
void ReportWarning (string message)
Launches a warning report.
void ReportInfo (Exception ex)
Launches an info.
void ReportInfo (string location, string message)
Launches an info.
void ReportInfo (string message)
Launches an info.
void ReportError0 (string errorstr)
ConsoleForm utility for reporting errors (not global).
void ReportError0 (Exception e)
Reports an error (including logging, etc., dependent on the current settings).
void ReportError0 (Exception e, string additional)
void HideInput ()
void ShowInput ()
string ReadLine ()
Reads a single line string from the input console and returns it.
string ReadLine (string Message)
void ReadString (ref string str)
void ReadString (ref string str, string Message)
int Read ()
Reads a single character from the input console and returns it as integer.
int Read (string Message)
double ReadDouble (ref double Value)
double ReadDouble (ref double Value, string Message)
double ReadDouble ()
Reads a floating point number from the input console and returns it.
double ReadDouble (string Message)
long ReadLong (ref long Value)
long ReadLong (ref long Value, string Message)
long ReadLong ()
Reads a floating point number from the input console and returns it.
long ReadLong (string Message)
void ShowThread ()
Shows a fading message in a new thread.
void ShowThread (string title)
Shows a fading message in a new thread, with message text equal to mshtext and without a title;.
Static Public Member Functions
static void Example ()
Public Attributes
bool IsClosable = true
bool WriteInput = true
If false then the consform can not be closed or dispoded.
string Title = "Console"
Color NormalOutColor = Color.Blue
Protected Attributes
string OutBuf =null
bool OutputStarted =false
ReporterBase _Reporter = null
Properties
IG.Lib.IReporter Reporter [get]
bool IsBackground [get, set]
Color OutBackColor [get, set]
Output console background color.
Color OutForeColor [get, set]
Output console foreground color.
Color OutSelectionColor [get, set]
Output console foreground color.
Styles Style [get, set]
Defines the output style of the console.
Color InBackColor [get, set]
Input console background color.
Color InForeColor [get, set]
Input console foreground color.
ReporterBase Reporter11 [get]
Gets the reporter used by the current console consform for launching error and warning reports, notices, etc.
Private Member Functions
void UpdateOutSettings ()
void UpdateSettings ()
Updates all settings for the console consform on the consform'result thread.
void baseConsoleForm ()
Required designer variable.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void FormThreadFunc ()
Shows the window in a separate thread.
void ConsoleForm_Load (object sender, System.EventArgs args)
void ConsoleForm_Dispose (object sender, System.EventArgs e)
void ConsoleForm_FormClosing (object sender, FormClosingEventArgs e)
void CloseBtn_Click (object sender, EventArgs e)
void HideBtn_Click (object sender, EventArgs e)
void WriteOutput ()
Appends output buffer to the output console.
void ReserveReportError (Exception e, string additional)
void ReserveReportError0 (string errorstr)
void ReserveReportError0 (Exception e)
void ReserveReportError0 (Exception e, string additional)
void PrepareForReading ()
void FinalizeReading ()
void WaitResult ()
void RunInputConfirmationDelegate ()
void InputConfirm_Read ()
void InputConfirm_ReadDouble ()
void InputConfirm_ReadLong ()
void InputChk_CheckedChanged (object sender, EventArgs e)
void ConfirmInputBtn_Click (object sender, EventArgs e)
void InBox_PreviewKeyDown (object sender, PreviewKeyDownEventArgs e)
void InBox_KeyUp (object sender, KeyEventArgs e)
void InBox_KeyPress (object sender, KeyPressEventArgs e)
void chkWrap_CheckedChanged (object sender, EventArgs e)
Private Attributes
bool bgthread = true
If true then Input messages are repeated in the output console.
object InputLock = new object()
object OutputLock = new object()
Color OBg = Color.White
Color OFg = Color.Blue
Color OSelFg = Color.Blue
Color IBg = Color.White
Color IFg = Color.Violet
Color ILblNormalBg =Color.Gray
Color ILblNormalFg =Color.Black
Color ILblActiveBg =Color.Yellow
Color ILblActiveFg =Color.Blue
Color ILblErrorBg =Color.Red
Color ILblErrorFg =Color.Blue
Color ErrorOutColor = Color.Red
Color MarkOutColor = Color.Violet
CheckBox chkWrap
Styles OStyle = Styles.Normal
System.Windows.Forms.Button HideBtn
Panel TitlePanel
Panel OutputOuterPnl
Panel ControlPanel
Label TitleLbl
RichTextBox OutBox
Label OutputLbl
Panel InputPnl
RichTextBox InBox
Label InputLbl
Label InputMsgLbl
Button ConfirmInputBtn
CheckBox InputChk
Button button1
Label StatusLbl
Thread formthread = null
bool OutputEnded =false
int RecCountWrite = 0
object errorlock = new object()
int reccounterror = 0
int RecCountError = 0
object ErrorLock00 = new object()
string InputResultString =null
string InputMessage =null
bool ReadStarted =false
bool ReadFinished =false
bool MultiLineInput = false
bool SingleCharacterInput = false
bool DeleteLastNewline = false
bool SelectInput =false
int KeyValue = 0
Keys KeyData = Keys.None
Keys KeyCode =Keys.None
IFormatProvider FormatProvider = System.Globalization.CultureInfo.CreateSpecificCulture("")
VoidDelegate InputConfirmDelegate
Detailed Description
Console replacement.
WARNING: This class is not tested enough and contains a number of bugs. Avoid use until this changes.
Handles a consform that can be use as console output and input window, for logging messages, etc. Input and output window are separated. The window can be launched in a separate thread. /remarks>
Member Enumeration Documentation
Styles
enum IG.Forms.ConsoleForm.Styles strong
Enumerator
Normal
Error
Mark
Constructor & Destructor Documentation
ConsoleForm() [1/2]
IG.Forms.ConsoleForm.ConsoleForm () inline
Argument-less constructor, does not launch the window in a parallel thread.
References IG.Forms.ConsoleForm.baseConsoleForm().
Referenced by IG.Forms.ConsoleForm.Example(), and IG.Forms.ConsoleForm.ReportErrorBas().
ConsoleForm() [2/2]
IG.Forms.ConsoleForm.ConsoleForm (string msgtext) inline
Shows a console consform in a new thread, with message text equal to mshtext and without a title;.
References IG.Forms.ConsoleForm.baseConsoleForm(), and IG.Forms.ConsoleForm.ShowThread().
Member Function Documentation
SetNormalStyle()
void IG.Forms.ConsoleForm.SetNormalStyle () inline
Sets normal style for console output.
References IG.Forms.ConsoleForm.NormalOutColor, IG.Forms.ConsoleForm.OStyle, IG.Forms.ConsoleForm.OutSelectionColor, IG.Forms.ConsoleForm.Reporter, and IG.Lib.IReporterBase.ReportError().
SetErrorStyle()
void IG.Forms.ConsoleForm.SetErrorStyle () inline
Sets Error Style for console output.
References IG.Forms.ConsoleForm.ErrorOutColor, IG.Forms.ConsoleForm.OStyle, IG.Forms.ConsoleForm.OutSelectionColor, IG.Forms.ConsoleForm.Reporter, and IG.Lib.IReporterBase.ReportError().
SetMarkStyle()
void IG.Forms.ConsoleForm.SetMarkStyle () inline
Sets marking (emphasis) style for console output.
References IG.Forms.ConsoleForm.MarkOutColor, IG.Forms.ConsoleForm.OStyle, IG.Forms.ConsoleForm.OutSelectionColor, IG.Forms.ConsoleForm.Reporter, and IG.Lib.IReporterBase.ReportError().
Referenced by IG.Forms.ConsoleForm.Example().
UpdateOutSettings()
void IG.Forms.ConsoleForm.UpdateOutSettings () inline private
Updates only those settings of the console consform that influence output operation, in the consform'result thread. This is performed separately from UpdateSettings() to enable faster execution of this vital update.
References IG.Forms.ConsoleForm.OutBox, IG.Forms.ConsoleForm.OutSelectionColor, IG.Forms.ConsoleForm.ReserveReportError(), and IG.Forms.VoidDelegate().
Referenced by IG.Forms.ConsoleForm.UpdateSettings().
UpdateSettings()
void IG.Forms.ConsoleForm.UpdateSettings () inline private
Updates all settings for the console consform on the consform'result thread.
References IG.Forms.ConsoleForm.IBg, IG.Forms.ConsoleForm.IFg, IG.Forms.ConsoleForm.InBox, IG.Forms.ConsoleForm.OBg, IG.Forms.ConsoleForm.OFg, IG.Forms.ConsoleForm.OutBox, IG.Forms.ConsoleForm.ReserveReportError(), IG.Forms.ConsoleForm.UpdateOutSettings(), and IG.Forms.VoidDelegate().
Referenced by IG.Forms.ConsoleForm.ConsoleForm_Load().
baseConsoleForm()
void IG.Forms.ConsoleForm.baseConsoleForm () inline private
Required designer variable.
Common initialization part called from all constructors.
References IG.Forms.ConsoleForm.InitializeComponent().
Referenced by IG.Forms.ConsoleForm.ConsoleForm().
InitializeComponent()
void IG.Forms.ConsoleForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by IG.Forms.ConsoleForm.baseConsoleForm().
FormThreadFunc()
void IG.Forms.ConsoleForm.FormThreadFunc () inline private
Shows the window in a separate thread.
References IG.Forms.ConsoleForm.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Forms.ConsoleForm.Title.
Referenced by IG.Forms.ConsoleForm.ShowThread().
ConsoleForm_Load()
void IG.Forms.ConsoleForm.ConsoleForm_Load (object sender, System.EventArgs args) inline private
References IG.Forms.ConsoleForm.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Forms.ConsoleForm.Title, and IG.Forms.ConsoleForm.UpdateSettings().
ConsoleForm_Dispose()
void IG.Forms.ConsoleForm.ConsoleForm_Dispose (object sender, System.EventArgs e) inline private
References IG.Forms.ConsoleForm.Reporter, and IG.Lib.IReporterBase.ReportError().
ConsoleForm_FormClosing()
void IG.Forms.ConsoleForm.ConsoleForm_FormClosing (object sender, FormClosingEventArgs e) inline private
References IG.Forms.ConsoleForm.Reporter, and IG.Lib.IReporterBase.ReportError().
CloseBtn_Click()
void IG.Forms.ConsoleForm.CloseBtn_Click (object sender, EventArgs e) inline private
References IG.Forms.ConsoleForm.CloseForm(), IG.Forms.ConsoleForm.Reporter, and IG.Lib.IReporterBase.ReportError().
HideBtn_Click()
void IG.Forms.ConsoleForm.HideBtn_Click (object sender, EventArgs e) inline private
References IG.Forms.ConsoleForm.HideForm(), IG.Forms.ConsoleForm.Reporter, and IG.Lib.IReporterBase.ReportError().
HideForm()
void IG.Forms.ConsoleForm.HideForm () inline
References IG.Forms.ConsoleForm.Reporter, and IG.Lib.IReporterBase.ReportError().
Referenced by IG.Forms.ConsoleForm.HideBtn_Click().
CloseForm()
void IG.Forms.ConsoleForm.CloseForm () inline
Closes the consform by properly (i.e. thread-safe) calling the Close() and Dispose().
References IG.Forms.ConsoleForm.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Forms.VoidDelegate().
Referenced by IG.Forms.ConsoleForm.CloseBtn_Click(), and IG.Forms.TestTcpServer.StartServer().
WriteOutput()
void IG.Forms.ConsoleForm.WriteOutput () inline private
Appends output buffer to the output console.
References IG.Forms.ConsoleForm.OutBox, IG.Forms.ConsoleForm.OutBuf, IG.Forms.ConsoleForm.OutputEnded, IG.Forms.ConsoleForm.OutputStarted, IG.Forms.ConsoleForm.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Forms.VoidDelegate().
Referenced by IG.Forms.ConsoleForm.Write().
Write() [1/18]
void IG.Forms.ConsoleForm.Write (bool block, string str) inline
Writes a string to the output console. If block=true, then it blocks until the string is actually written.
References IG.Forms.ConsoleForm.OutBuf, IG.Forms.ConsoleForm.OutputEnded, IG.Forms.ConsoleForm.OutputLock, IG.Forms.ConsoleForm.OutputStarted, IG.Forms.ConsoleForm.RecCountWrite, IG.Forms.ConsoleForm.ReserveReportError(), and IG.Forms.ConsoleForm.WriteOutput().
Referenced by IG.Forms.ReporterForms.DefaultReserveReportErrorForms(), IG.Forms.ConsoleForm.FinalizeReading(), IG.Forms.ConsoleForm.ReportError0(), IG.Forms.ConsoleForm.ReportErrorBas(), IG.Forms.ConsoleForm.Write(), and IG.Forms.ConsoleForm.WriteLine().
Write() [2/18]
void IG.Forms.ConsoleForm.Write (string str) inline
References IG.Forms.ConsoleForm.Write().
Referenced by IG.Forms.ConsoleForm.Write().
WriteLine() [1/18]
void IG.Forms.ConsoleForm.WriteLine (bool block, string str) inline
Writes a string to the output console and appends a newline character.
References IG.Forms.ConsoleForm.Write().
Referenced by IG.Forms.UtilForms.ConsoleExample(), IG.Forms.UtilForms.ConsoleExample2(), IG.Crypt.Asym.CreateTestCertificate(), IG.Forms.ConsoleForm.Example(), IG.Forms.ConsoleForm.FinalizeReading(), IG.Forms.TestTcpMultiThreadedServer.ListenerLoop(), IG.Forms.TestTcpClient.Report(), IG.Forms.TestTcpServer.Report(), IG.Forms.TestTcpClient.ReportError(), IG.Forms.TestTcpServer.ReportError(), IG.Forms.TestTcpClient.ReportMarked(), IG.Forms.TestTcpServer.ReportMarked(), IG.Forms.TestTcpMultiThreadedServer.ServerThreadFunc(), and IG.Forms.ConsoleForm.WriteLine().
WriteLine() [2/18]
void IG.Forms.ConsoleForm.WriteLine (string str) inline
References IG.Forms.ConsoleForm.WriteLine().
Referenced by IG.Forms.ConsoleForm.WriteLine().
Write() [3/18]
void IG.Forms.ConsoleForm.Write (Char arg) inline
References IG.Forms.ConsoleForm.Write().
Write() [4/18]
void IG.Forms.ConsoleForm.Write (Boolean arg) inline
References IG.Forms.ConsoleForm.Write().
Write() [5/18]
void IG.Forms.ConsoleForm.Write (Char[] arg) inline
References IG.Forms.ConsoleForm.Write().
Write() [6/18]
void IG.Forms.ConsoleForm.Write (Decimal arg) inline
References IG.Forms.ConsoleForm.Write().
Write() [7/18]
void IG.Forms.ConsoleForm.Write (Double arg) inline
References IG.Forms.ConsoleForm.Write().
Write() [8/18]
void IG.Forms.ConsoleForm.Write (Int32 arg) inline
References IG.Forms.ConsoleForm.Write().
Write() [9/18]
void IG.Forms.ConsoleForm.Write (Int64 arg) inline
References IG.Forms.ConsoleForm.Write().
Write() [10/18]
void IG.Forms.ConsoleForm.Write (Object arg) inline
References IG.Forms.ConsoleForm.Write().
Write() [11/18]
void IG.Forms.ConsoleForm.Write (Single arg) inline
References IG.Forms.ConsoleForm.Write().
Write() [12/18]
void IG.Forms.ConsoleForm.Write (UInt32 arg) inline
References IG.Forms.ConsoleForm.Write().
Write() [13/18]
void IG.Forms.ConsoleForm.Write (UInt64 arg) inline
References IG.Forms.ConsoleForm.Write().
Write() [14/18]
void IG.Forms.ConsoleForm.Write (String arg, Object arg1) inline
References IG.Forms.ConsoleForm.Write().
Write() [15/18]
void IG.Forms.ConsoleForm.Write (String arg, Object[] arg1) inline
References IG.Forms.ConsoleForm.Write().
Write() [16/18]
void IG.Forms.ConsoleForm.Write (Char[] arg, Int32 arg1, Int32 arg2) inline
References IG.Forms.ConsoleForm.Write().
Write() [17/18]
void IG.Forms.ConsoleForm.Write (String arg, Object arg1, Object arg2) inline
References IG.Forms.ConsoleForm.Write().
Write() [18/18]
void IG.Forms.ConsoleForm.Write (String arg, Object arg1, Object arg2, Object arg3) inline
References IG.Forms.ConsoleForm.Write().
WriteLine() [3/18]
void IG.Forms.ConsoleForm.WriteLine (Char arg) inline
References IG.Forms.ConsoleForm.WriteLine().
WriteLine() [4/18]
void IG.Forms.ConsoleForm.WriteLine (Boolean arg) inline
References IG.Forms.ConsoleForm.WriteLine().
WriteLine() [5/18]
void IG.Forms.ConsoleForm.WriteLine (Char[] arg) inline
References IG.Forms.ConsoleForm.WriteLine().
WriteLine() [6/18]
void IG.Forms.ConsoleForm.WriteLine (Decimal arg) inline
References IG.Forms.ConsoleForm.WriteLine().
WriteLine() [7/18]
void IG.Forms.ConsoleForm.WriteLine (Double arg) inline
References IG.Forms.ConsoleForm.WriteLine().
WriteLine() [8/18]
void IG.Forms.ConsoleForm.WriteLine (Int32 arg) inline
References IG.Forms.ConsoleForm.WriteLine().
WriteLine() [9/18]
void IG.Forms.ConsoleForm.WriteLine (Int64 arg) inline
References IG.Forms.ConsoleForm.WriteLine().
WriteLine() [10/18]
void IG.Forms.ConsoleForm.WriteLine (Object arg) inline
References IG.Forms.ConsoleForm.WriteLine().
WriteLine() [11/18]
void IG.Forms.ConsoleForm.WriteLine (Single arg) inline
References IG.Forms.ConsoleForm.WriteLine().
WriteLine() [12/18]
void IG.Forms.ConsoleForm.WriteLine (UInt32 arg) inline
References IG.Forms.ConsoleForm.WriteLine().
WriteLine() [13/18]
void IG.Forms.ConsoleForm.WriteLine (UInt64 arg) inline
References IG.Forms.ConsoleForm.WriteLine().
WriteLine() [14/18]
void IG.Forms.ConsoleForm.WriteLine (String arg, Object arg1) inline
References IG.Forms.ConsoleForm.WriteLine().
WriteLine() [15/18]
void IG.Forms.ConsoleForm.WriteLine (String arg, Object[] arg1) inline
References IG.Forms.ConsoleForm.WriteLine().
WriteLine() [16/18]
void IG.Forms.ConsoleForm.WriteLine (Char[] arg, Int32 arg1, Int32 arg2) inline
References IG.Forms.ConsoleForm.WriteLine().
WriteLine() [17/18]
void IG.Forms.ConsoleForm.WriteLine (String arg, Object arg1, Object arg2) inline
References IG.Forms.ConsoleForm.WriteLine().
WriteLine() [18/18]
void IG.Forms.ConsoleForm.WriteLine (String arg, Object arg1, Object arg2, Object arg3) inline
References IG.Forms.ConsoleForm.WriteLine().
ReportErrorBas()
void IG.Forms.ConsoleForm.ReportErrorBas (ReporterBase reporter, ReportType messagelevel, string errorlocation, string errormessage) inline
References IG.Forms.ConsoleForm.ConsoleForm(), IG.Lib.ReporterBase.DefaultReportStringConsoleTimeStamp(), IG.Forms.ConsoleForm.errorlock, IG.Lib.ReporterBase.Obj, IG.Forms.ConsoleForm.reccounterror, IG.Forms.ConsoleForm.ReserveReportErrorBas(), IG.Forms.ConsoleForm.Style, and IG.Forms.ConsoleForm.Write().
ReserveReportErrorBas()
void IG.Forms.ConsoleForm.ReserveReportErrorBas (ReporterBase reporter, ReportType messagelevel, string location, string message, Exception ex, Exception ex1) inline
Referenced by IG.Forms.ConsoleForm.ReportErrorBas(), and IG.Forms.ConsoleForm.ReserveReportError().
ReserveReportError() [1/2]
void IG.Forms.ConsoleForm.ReserveReportError (Exception e, string additional) inline private
References IG.Forms.ConsoleForm.ReserveReportErrorBas().
Referenced by IG.Forms.ConsoleForm.ReportError0(), IG.Forms.ConsoleForm.ReserveReportError0(), IG.Forms.ConsoleForm.UpdateOutSettings(), IG.Forms.ConsoleForm.UpdateSettings(), and IG.Forms.ConsoleForm.Write().
ReserveReportError() [2/2]
void IG.Forms.ConsoleForm.ReserveReportError (string errorstr) inline
References IG.Forms.ConsoleForm.ReserveReportErrorBas().
Report() [1/6]
virtual void IG.Forms.ConsoleForm.Report (ReportType messagetype, string location, string message, Exception ex) inline virtual
Basic reporting method (overloaded). Launches an error report, a warning report or s kind of report/message. Supplemental data (such as objects necessary to launch visualize the report or operation typeflags) are obtained from the class' instance.
Parameters
messagetype The type of the report (e.g. Error, Warning, etc.).
location User-provided description of error location.
message User-provided description of error.
ex Exception thrown when error occurred.
References IG.Lib.IReporterBase.Report(), and IG.Forms.ConsoleForm.Reporter.
Referenced by IG.Forms.ReporterForms.DefaultReport_ConsoleForm(), IG.Forms.ConsoleForm.Report(), IG.Forms.ConsoleForm.ReportError(), IG.Forms.ConsoleForm.ReportInfo(), and IG.Forms.ConsoleForm.ReportWarning().
Report() [2/6]
void IG.Forms.ConsoleForm.Report (ReportType messagetype, string message, Exception ex) inline
Launches a report. Predominantly for error and warning reports.
Parameters
messagetype Level of the message (Error, Warnind, etc.).
message User-provided description of error.
ex Exception that is the cause for launching the report (and from which additional information is extracted).
References IG.Forms.ConsoleForm.Report().
Report() [3/6]
void IG.Forms.ConsoleForm.Report (ReportType messagetype, Exception ex, string location) inline
Launches a report. Predominantly for error and warning reports.
Parameters
messagetype Level of the message (Error, Warnind, etc.).
ex Exception that is the cause for launching the report (and from which additional information is extracted).
location User-provided description of error location.
References IG.Forms.ConsoleForm.Report().
Report() [4/6]
void IG.Forms.ConsoleForm.Report (ReportType messagetype, Exception ex) inline
Launches a report. Predominantly for error and warning reports.
Parameters
messagetype Level of the message (Error, Warnind, etc.).
ex Exception that is the cause for launching the report (and from which additional information is extracted).
References IG.Forms.ConsoleForm.Report().
Report() [5/6]
void IG.Forms.ConsoleForm.Report (ReportType messagetype, string location, string message) inline
Launches a report.
Parameters
messagetype Level of the message (Error, Warnind, etc.).
location User provided description of the location where report was triggered.
message User provided message included in the report.
References IG.Forms.ConsoleForm.Report().
Report() [6/6]
void IG.Forms.ConsoleForm.Report (ReportType messagetype, string message) inline
Launches a report.
Parameters
messagetype Level of the message (Error, Warnind, etc.).
message User provided message included in the report.
References IG.Forms.ConsoleForm.Report().
ReportError() [1/6]
virtual void IG.Forms.ConsoleForm.ReportError (string location, string message, Exception ex) inline virtual
Basic error reporting method (overloaded). Supplemental data (such as objects necessary to launch visualize the report or operation typeflags) are obtained from the class' instance.
Parameters
location User-provided description of error location.
message User-provided description of error.
ex Exception thrown when error occurred.
References IG.Forms.ConsoleForm.Report().
Referenced by IG.Forms.UtilForms.ConsoleExample2(), and IG.Forms.TestTcpServer.StartServer().
ReportError() [2/6]
void IG.Forms.ConsoleForm.ReportError (string message, Exception ex) inline
Launches an error report.
Parameters
message User-provided description of error.
ex Exception that is the cause for launching the report (and from which additional information is extracted).
References IG.Forms.ConsoleForm.Report().
ReportError() [3/6]
void IG.Forms.ConsoleForm.ReportError (Exception ex, string location) inline
Launches an error report.
Parameters
ex Exception that is the cause for launching the report (and from which additional information is extracted).
location User-provided description of error location.
References IG.Forms.ConsoleForm.Report().
ReportError() [4/6]
void IG.Forms.ConsoleForm.ReportError (Exception ex) inline
Launches an error report. Predominantly for error and warning reports.
Parameters
ex Exception that is the cause for launching the report (and from which additional information is extracted).
References IG.Forms.ConsoleForm.Report().
ReportError() [5/6]
void IG.Forms.ConsoleForm.ReportError (string location, string message) inline
Launches an error report.
Parameters
location User provided description of the location where report was triggered.
message User provided message included in the report.
References IG.Forms.ConsoleForm.Report().
ReportError() [6/6]
void IG.Forms.ConsoleForm.ReportError (string message) inline
Launches an error report.
Parameters
message User provided message included in the report.
References IG.Forms.ConsoleForm.Report().
ReportWarning() [1/6]
virtual void IG.Forms.ConsoleForm.ReportWarning (string location, string message, Exception ex) inline virtual
Basic warning reporting method (overloaded). Supplemental data (such as objects necessary to launch visualize the report or operation typeflags) are obtained from the class' instance.
Parameters
location User-provided description of error location.
message User-provided description of error.
ex Exception thrown when error occurred.
References IG.Forms.ConsoleForm.Report().
ReportWarning() [2/6]
void IG.Forms.ConsoleForm.ReportWarning (string message, Exception ex) inline
Launches a warning report.
Parameters
message User-provided description of error.
ex Exception that is the cause for launching the report (and from which additional information is extracted).
References IG.Forms.ConsoleForm.Report().
ReportWarning() [3/6]
void IG.Forms.ConsoleForm.ReportWarning (Exception ex, string location) inline
Launches a warning report.
Parameters
ex Exception that is the cause for launching the report (and from which additional information is extracted).
location User-provided description of error location.
References IG.Forms.ConsoleForm.Report().
ReportWarning() [4/6]
void IG.Forms.ConsoleForm.ReportWarning (Exception ex) inline
Launches a warning report. Predominantly for error and warning reports.
Parameters
ex Exception that is the cause for launching the report (and from which additional information is extracted).
References IG.Forms.ConsoleForm.Report().
ReportWarning() [5/6]
void IG.Forms.ConsoleForm.ReportWarning (string location, string message) inline
Launches a warning report.
Parameters
location User provided description of the location where report was triggered.
message User provided message included in the report.
References IG.Forms.ConsoleForm.Report().
ReportWarning() [6/6]
void IG.Forms.ConsoleForm.ReportWarning (string message) inline
Launches a warning report.
Parameters
message User provided message included in the report.
References IG.Forms.ConsoleForm.Report().
ReportInfo() [1/3]
void IG.Forms.ConsoleForm.ReportInfo (Exception ex) inline
Launches an info.
Parameters
ex Exception that is the cause for launching the report (and from which additional information is extracted).
References IG.Forms.ConsoleForm.Report().
ReportInfo() [2/3]
void IG.Forms.ConsoleForm.ReportInfo (string location, string message) inline
Launches an info.
Parameters
location User provided description of the location where report was triggered.
message User provided message included in the report.
References IG.Forms.ConsoleForm.Report().
ReportInfo() [3/3]
void IG.Forms.ConsoleForm.ReportInfo (string message) inline
Launches an info.
Parameters
message User provided message included in the report.
References IG.Forms.ConsoleForm.Report().
ReportError0() [1/3]
void IG.Forms.ConsoleForm.ReportError0 (string errorstr) inline
ConsoleForm utility for reporting errors (not global).
References IG.Forms.ConsoleForm.ErrorLock00, IG.Forms.ConsoleForm.RecCountError, IG.Forms.ConsoleForm.ReserveReportError(), IG.Forms.ConsoleForm.Style, and IG.Forms.ConsoleForm.Write().
Referenced by IG.Forms.ConsoleForm.ReportError0().
ReportError0() [2/3]
void IG.Forms.ConsoleForm.ReportError0 (Exception e) inline
Reports an error (including logging, etc., dependent on the current settings).
References IG.Lib.ReporterBase.GetErorString(), IG.Forms.ConsoleForm.ReportError0(), and IG.Forms.ConsoleForm.ReserveReportError().
ReportError0() [3/3]
void IG.Forms.ConsoleForm.ReportError0 (Exception e, string additional) inline
Reports an error (including logging, etc., dependent on the current settings). An additonal string is appended to error report.
References IG.Lib.ReporterBase.GetErorString(), IG.Forms.ConsoleForm.ReportError0(), and IG.Forms.ConsoleForm.ReserveReportError().
ReserveReportError0() [1/3]
void IG.Forms.ConsoleForm.ReserveReportError0 (string errorstr) inline private
References IG.Forms.FadingMessage.BackGroundColor, IG.Forms.FadingMessage.LaunchInNewThread(), IG.Forms.FadingMessage.MsgText, IG.Forms.FadingMessage.MsgTitle, and IG.Forms.FadingMessage.ShowTime.
Referenced by IG.Forms.ConsoleForm.ReserveReportError0().
ReserveReportError0() [2/3]
void IG.Forms.ConsoleForm.ReserveReportError0 (Exception e) inline private
References IG.Lib.ReporterBase.GetErorString(), and IG.Forms.ConsoleForm.ReserveReportError().
ReserveReportError0() [3/3]
void IG.Forms.ConsoleForm.ReserveReportError0 (Exception e, string additional) inline private
References IG.Lib.ReporterBase.GetErorString(), IG.Forms.ConsoleForm.ReserveReportError(), and IG.Forms.ConsoleForm.ReserveReportError0().
HideInput()
void IG.Forms.ConsoleForm.HideInput () inline
References IG.Forms.ConsoleForm.InputChk, IG.Forms.ConsoleForm.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Forms.VoidDelegate().
Referenced by IG.Forms.ConsoleForm.ShowInput().
ShowInput()
void IG.Forms.ConsoleForm.ShowInput () inline
References IG.Forms.ConsoleForm.HideInput(), IG.Forms.ConsoleForm.InputChk, IG.Forms.ConsoleForm.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Forms.VoidDelegate().
PrepareForReading()
void IG.Forms.ConsoleForm.PrepareForReading () inline private
References IG.Forms.ConsoleForm.DeleteLastNewline, IG.Forms.ConsoleForm.ILblActiveBg, IG.Forms.ConsoleForm.ILblActiveFg, IG.Forms.ConsoleForm.InBox, IG.Forms.ConsoleForm.InputChk, IG.Forms.ConsoleForm.InputMessage, IG.Forms.ConsoleForm.InputMsgLbl, IG.Forms.ConsoleForm.InputResultString, IG.Forms.ConsoleForm.ReadStarted, IG.Forms.ConsoleForm.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Forms.ConsoleForm.SelectInput, and IG.Forms.VoidDelegate().
Referenced by IG.Forms.ConsoleForm.Read(), IG.Forms.ConsoleForm.ReadDouble(), IG.Forms.ConsoleForm.ReadLine(), IG.Forms.ConsoleForm.ReadLong(), and IG.Forms.ConsoleForm.ReadString().
FinalizeReading()
void IG.Forms.ConsoleForm.FinalizeReading () inline private
References IG.Forms.ConsoleForm.ILblNormalBg, IG.Forms.ConsoleForm.ILblNormalFg, IG.Forms.ConsoleForm.InBox, IG.Forms.ConsoleForm.InputMessage, IG.Forms.ConsoleForm.InputMsgLbl, IG.Forms.ConsoleForm.InputResultString, IG.Forms.ConsoleForm.MultiLineInput, IG.Forms.ConsoleForm.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Forms.ConsoleForm.SingleCharacterInput, IG.Forms.ConsoleForm.Style, IG.Forms.VoidDelegate(), IG.Forms.ConsoleForm.Write(), IG.Forms.ConsoleForm.WriteInput, and IG.Forms.ConsoleForm.WriteLine().
Referenced by IG.Forms.ConsoleForm.Read(), IG.Forms.ConsoleForm.ReadDouble(), IG.Forms.ConsoleForm.ReadLine(), IG.Forms.ConsoleForm.ReadLong(), and IG.Forms.ConsoleForm.ReadString().
WaitResult()
void IG.Forms.ConsoleForm.WaitResult () inline private
Waits until result is available (indicating by the flag ReadFinished, which must be set by the ReadDelegate).
References IG.Forms.ConsoleForm.ReadFinished.
Referenced by IG.Forms.ConsoleForm.Read(), IG.Forms.ConsoleForm.ReadDouble(), IG.Forms.ConsoleForm.ReadLine(), IG.Forms.ConsoleForm.ReadLong(), and IG.Forms.ConsoleForm.ReadString().
RunInputConfirmationDelegate()
void IG.Forms.ConsoleForm.RunInputConfirmationDelegate () inline private
Runs specific function for handling user input consform input console, which grabs the input, eventually validates it, and notifies the caller that reading is finished when validation succeeds.
References IG.Forms.ConsoleForm.InputConfirmDelegate, IG.Forms.ConsoleForm.ReadFinished, IG.Forms.ConsoleForm.ReadStarted, IG.Forms.ConsoleForm.Reporter, and IG.Lib.IReporterBase.ReportError().
Referenced by IG.Forms.ConsoleForm.ConfirmInputBtn_Click(), IG.Forms.ConsoleForm.InBox_KeyPress(), and IG.Forms.ConsoleForm.InBox_KeyUp().
InputConfirm_Read()
void IG.Forms.ConsoleForm.InputConfirm_Read () inline private
This function should be called as event handler for input events (such as <Enter> pressed in the input console or button "Confirm Input" pressed).
References IG.Forms.ConsoleForm.DeleteLastNewline, IG.Forms.ConsoleForm.InBox, IG.Forms.ConsoleForm.InputResultString, IG.Forms.ConsoleForm.ReadFinished, IG.Forms.ConsoleForm.ReadStarted, IG.Forms.ConsoleForm.Reporter, and IG.Lib.IReporterBase.ReportError().
Referenced by IG.Forms.ConsoleForm.Read(), IG.Forms.ConsoleForm.ReadLine(), and IG.Forms.ConsoleForm.ReadString().
ReadLine() [1/2]
string IG.Forms.ConsoleForm.ReadLine () inline
Reads a single line string from the input console and returns it.
Referenced by IG.Forms.TestTcpClient.ClientExampleMain(), IG.Forms.TestTcpClient.ClientTest(), and IG.Forms.UtilForms.ConsoleExample2().
ReadLine() [2/2]
string IG.Forms.ConsoleForm.ReadLine (string Message) inline
Reads a single line string from the input console and returns it. If Message!=Null then Message is written above the input consform before reading.
References IG.Forms.ConsoleForm.FinalizeReading(), IG.Forms.ConsoleForm.InputConfirm_Read(), IG.Forms.ConsoleForm.InputConfirmDelegate, IG.Forms.ConsoleForm.InputLock, IG.Forms.ConsoleForm.InputMessage, IG.Forms.ConsoleForm.InputResultString, IG.Forms.ConsoleForm.MultiLineInput, IG.Forms.ConsoleForm.PrepareForReading(), IG.Forms.ConsoleForm.ReadFinished, IG.Forms.ConsoleForm.ReadStarted, IG.Forms.ConsoleForm.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Forms.ConsoleForm.SelectInput, IG.Forms.ConsoleForm.SingleCharacterInput, IG.Forms.VoidDelegate(), and IG.Forms.ConsoleForm.WaitResult().
ReadString() [1/2]
void IG.Forms.ConsoleForm.ReadString (ref string str) inline
ReadString() [2/2]
void IG.Forms.ConsoleForm.ReadString (ref string str, string Message) inline
Reads a multiple line string from the input console and returns it in OutStr. If Message!=Null then Message is written above the input consform before reading.
References IG.Forms.ConsoleForm.FinalizeReading(), IG.Forms.ConsoleForm.InputConfirm_Read(), IG.Forms.ConsoleForm.InputConfirmDelegate, IG.Forms.ConsoleForm.InputLock, IG.Forms.ConsoleForm.InputMessage, IG.Forms.ConsoleForm.InputResultString, IG.Forms.ConsoleForm.MultiLineInput, IG.Forms.ConsoleForm.PrepareForReading(), IG.Forms.ConsoleForm.ReadFinished, IG.Forms.ConsoleForm.ReadStarted, IG.Forms.ConsoleForm.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Forms.ConsoleForm.SelectInput, IG.Forms.ConsoleForm.SingleCharacterInput, IG.Forms.VoidDelegate(), and IG.Forms.ConsoleForm.WaitResult().
Read() [1/2]
int IG.Forms.ConsoleForm.Read () inline
Reads a single character from the input console and returns it as integer.
Read() [2/2]
int IG.Forms.ConsoleForm.Read (string Message) inline
Reads a single character from the input console and returns it as integer. If Message!=null then it is written above the input consform before reading starts.
References IG.Forms.ConsoleForm.FinalizeReading(), IG.Forms.ConsoleForm.InputConfirm_Read(), IG.Forms.ConsoleForm.InputConfirmDelegate, IG.Forms.ConsoleForm.InputLock, IG.Forms.ConsoleForm.InputMessage, IG.Forms.ConsoleForm.InputResultString, IG.Forms.ConsoleForm.KeyValue, IG.Forms.ConsoleForm.MultiLineInput, IG.Forms.ConsoleForm.PrepareForReading(), IG.Forms.ConsoleForm.ReadFinished, IG.Forms.ConsoleForm.ReadStarted, IG.Forms.ConsoleForm.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Forms.ConsoleForm.SelectInput, IG.Forms.ConsoleForm.SingleCharacterInput, IG.Forms.VoidDelegate(), and IG.Forms.ConsoleForm.WaitResult().
InputConfirm_ReadDouble()
void IG.Forms.ConsoleForm.InputConfirm_ReadDouble () inline private
References IG.Forms.ConsoleForm.DeleteLastNewline, IG.Forms.ConsoleForm.FormatProvider, IG.Forms.ConsoleForm.ILblErrorBg, IG.Forms.ConsoleForm.ILblErrorFg, IG.Forms.ConsoleForm.InBox, IG.Forms.ConsoleForm.InputMsgLbl, IG.Forms.ConsoleForm.InputResultString, IG.Forms.ConsoleForm.ReadFinished, IG.Forms.ConsoleForm.ReadStarted, IG.Forms.ConsoleForm.Reporter, and IG.Lib.IReporterBase.ReportError().
Referenced by IG.Forms.ConsoleForm.ReadDouble().
ReadDouble() [1/4]
double IG.Forms.ConsoleForm.ReadDouble (ref double Value) inline
Reads a floating point number from the input console and returns it in Value. Initial value of the number is set to Value prior to reading.
References IG.Forms.ConsoleForm.ReadDouble().
Referenced by IG.Forms.ConsoleForm.Example().
ReadDouble() [2/4]
double IG.Forms.ConsoleForm.ReadDouble (ref double Value, string Message) inline
Reads a floating point number from the input console and returns it in Value. If Message!=null then it is written above the input consform before reading starts. Initial value of the number is set to Value prior to reading.
References IG.Forms.ConsoleForm.FinalizeReading(), IG.Forms.ConsoleForm.FormatProvider, IG.Forms.ConsoleForm.InputConfirm_ReadDouble(), IG.Forms.ConsoleForm.InputConfirmDelegate, IG.Forms.ConsoleForm.InputLock, IG.Forms.ConsoleForm.InputMessage, IG.Forms.ConsoleForm.InputResultString, IG.Forms.ConsoleForm.MultiLineInput, IG.Forms.ConsoleForm.PrepareForReading(), IG.Forms.ConsoleForm.ReadFinished, IG.Forms.ConsoleForm.ReadStarted, IG.Forms.ConsoleForm.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Forms.ConsoleForm.SelectInput, IG.Forms.ConsoleForm.SingleCharacterInput, IG.Forms.VoidDelegate(), and IG.Forms.ConsoleForm.WaitResult().
ReadDouble() [3/4]
double IG.Forms.ConsoleForm.ReadDouble () inline
Reads a floating point number from the input console and returns it.
Referenced by IG.Forms.ConsoleForm.ReadDouble().
ReadDouble() [4/4]
double IG.Forms.ConsoleForm.ReadDouble (string Message) inline
Reads a floating point number from the input console and returns it. If Message!=null then it is written above the input consform before reading starts.
References IG.Forms.ConsoleForm.ReadDouble().
InputConfirm_ReadLong()
void IG.Forms.ConsoleForm.InputConfirm_ReadLong () inline private
This function should be called as event handler for input events (such as <Enter> pressed in the input console or button "Confirm Input" pressed), for confirmation of floating point numbers input.
References IG.Forms.ConsoleForm.DeleteLastNewline, IG.Forms.ConsoleForm.FormatProvider, IG.Forms.ConsoleForm.ILblErrorBg, IG.Forms.ConsoleForm.ILblErrorFg, IG.Forms.ConsoleForm.InBox, IG.Forms.ConsoleForm.InputMsgLbl, IG.Forms.ConsoleForm.InputResultString, IG.Forms.ConsoleForm.ReadFinished, IG.Forms.ConsoleForm.ReadStarted, IG.Forms.ConsoleForm.Reporter, and IG.Lib.IReporterBase.ReportError().
Referenced by IG.Forms.ConsoleForm.ReadLong().
ReadLong() [1/4]
long IG.Forms.ConsoleForm.ReadLong (ref long Value) inline
Reads a floating point number from the input console and returns it in Value. Initial value of the number is set to Value prior to reading.
References IG.Forms.ConsoleForm.ReadLong().
ReadLong() [2/4]
long IG.Forms.ConsoleForm.ReadLong (ref long Value, string Message) inline
Reads a floating point number from the input console and returns it in Value. If Message!=null then it is written above the input consform before reading starts. Initial value of the number is set to Value prior to reading.
References IG.Forms.ConsoleForm.FinalizeReading(), IG.Forms.ConsoleForm.FormatProvider, IG.Forms.ConsoleForm.InputConfirm_ReadLong(), IG.Forms.ConsoleForm.InputConfirmDelegate, IG.Forms.ConsoleForm.InputLock, IG.Forms.ConsoleForm.InputMessage, IG.Forms.ConsoleForm.InputResultString, IG.Forms.ConsoleForm.MultiLineInput, IG.Forms.ConsoleForm.PrepareForReading(), IG.Forms.ConsoleForm.ReadFinished, IG.Forms.ConsoleForm.ReadStarted, IG.Forms.ConsoleForm.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Forms.ConsoleForm.SelectInput, IG.Forms.ConsoleForm.SingleCharacterInput, IG.Forms.VoidDelegate(), and IG.Forms.ConsoleForm.WaitResult().
ReadLong() [3/4]
long IG.Forms.ConsoleForm.ReadLong () inline
Reads a floating point number from the input console and returns it.
Referenced by IG.Forms.ConsoleForm.ReadLong().
ReadLong() [4/4]
long IG.Forms.ConsoleForm.ReadLong (string Message) inline
Reads a floating point number from the input console and returns it. If Message!=null then it is written above the input consform before reading starts.
References IG.Forms.ConsoleForm.ReadLong().
ShowThread() [1/2]
void IG.Forms.ConsoleForm.ShowThread () inline
Shows a fading message in a new thread.
References IG.Forms.ConsoleForm.bgthread, IG.Forms.ConsoleForm.formthread, and IG.Forms.ConsoleForm.FormThreadFunc().
Referenced by IG.Forms.ConsoleForm.ConsoleForm(), and IG.Forms.ConsoleForm.ShowThread().
ShowThread() [2/2]
void IG.Forms.ConsoleForm.ShowThread (string title) inline
Shows a fading message in a new thread, with message text equal to mshtext and without a title;.
References IG.Forms.ConsoleForm.ShowThread(), and IG.Forms.ConsoleForm.Title.
InputChk_CheckedChanged()
void IG.Forms.ConsoleForm.InputChk_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.ConsoleForm.InputChk, IG.Forms.ConsoleForm.InputPnl, IG.Forms.ConsoleForm.Reporter, and IG.Lib.IReporterBase.ReportError().
ConfirmInputBtn_Click()
void IG.Forms.ConsoleForm.ConfirmInputBtn_Click (object sender, EventArgs e) inline private
References IG.Forms.ConsoleForm.DeleteLastNewline, IG.Forms.ConsoleForm.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Forms.ConsoleForm.RunInputConfirmationDelegate().
InBox_PreviewKeyDown()
void IG.Forms.ConsoleForm.InBox_PreviewKeyDown (object sender, PreviewKeyDownEventArgs e) inline private
References IG.Forms.ConsoleForm.Reporter, and IG.Lib.IReporterBase.ReportError().
InBox_KeyUp()
void IG.Forms.ConsoleForm.InBox_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Forms.ConsoleForm.DeleteLastNewline, IG.Forms.ConsoleForm.KeyCode, IG.Forms.ConsoleForm.KeyData, IG.Forms.ConsoleForm.KeyValue, IG.Forms.ConsoleForm.ReadFinished, IG.Forms.ConsoleForm.ReadStarted, IG.Forms.ConsoleForm.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Forms.ConsoleForm.RunInputConfirmationDelegate(), and IG.Forms.ConsoleForm.SingleCharacterInput.
InBox_KeyPress()
void IG.Forms.ConsoleForm.InBox_KeyPress (object sender, KeyPressEventArgs e) inline private
References IG.Forms.ConsoleForm.DeleteLastNewline, IG.Forms.ConsoleForm.MultiLineInput, IG.Forms.ConsoleForm.ReadFinished, IG.Forms.ConsoleForm.ReadStarted, IG.Forms.ConsoleForm.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Forms.ConsoleForm.RunInputConfirmationDelegate().
chkWrap_CheckedChanged()
void IG.Forms.ConsoleForm.chkWrap_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.ConsoleForm.chkWrap, and IG.Forms.ConsoleForm.OutBox.
Example()
static void IG.Forms.ConsoleForm.Example () inline static
References IG.Forms.ConsoleForm.ConsoleForm(), IG.Forms.ConsoleForm.OutSelectionColor, IG.Forms.ConsoleForm.ReadDouble(), IG.Forms.UtilForms.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Forms.ConsoleForm.SetMarkStyle(), IG.Forms.ConsoleForm.Style, and IG.Forms.ConsoleForm.WriteLine().
Referenced by igform_console_test.test_igform_console_program.Main().
Member Data Documentation
IsClosable
bool IG.Forms.ConsoleForm.IsClosable = true
WriteInput
bool IG.Forms.ConsoleForm.WriteInput = true
If false then the consform can not be closed or dispoded.
Referenced by IG.Forms.ConsoleForm.FinalizeReading().
bgthread
bool IG.Forms.ConsoleForm.bgthread = true private
If true then Input messages are repeated in the output console.
Referenced by IG.Forms.ConsoleForm.ShowThread().
InputLock
object IG.Forms.ConsoleForm.InputLock = new object() private
Referenced by IG.Forms.ConsoleForm.Read(), IG.Forms.ConsoleForm.ReadDouble(), IG.Forms.ConsoleForm.ReadLine(), IG.Forms.ConsoleForm.ReadLong(), and IG.Forms.ConsoleForm.ReadString().
OutputLock
object IG.Forms.ConsoleForm.OutputLock = new object() private
Referenced by IG.Forms.ConsoleForm.Write().
Title
string IG.Forms.ConsoleForm.Title = "Console"
Referenced by IG.Forms.ConsoleForm.ConsoleForm_Load(), IG.Forms.ConsoleForm.FormThreadFunc(), and IG.Forms.ConsoleForm.ShowThread().
OBg
Color IG.Forms.ConsoleForm.OBg = Color.White private
Referenced by IG.Forms.ConsoleForm.UpdateSettings().
OFg
Color IG.Forms.ConsoleForm.OFg = Color.Blue private
Referenced by IG.Forms.ConsoleForm.UpdateSettings().
OSelFg
Color IG.Forms.ConsoleForm.OSelFg = Color.Blue private
IBg
Color IG.Forms.ConsoleForm.IBg = Color.White private
Referenced by IG.Forms.ConsoleForm.UpdateSettings().
IFg
Color IG.Forms.ConsoleForm.IFg = Color.Violet private
Referenced by IG.Forms.ConsoleForm.UpdateSettings().
ILblNormalBg
Color IG.Forms.ConsoleForm.ILblNormalBg =Color.Gray private
Referenced by IG.Forms.ConsoleForm.FinalizeReading().
ILblNormalFg
Color IG.Forms.ConsoleForm.ILblNormalFg =Color.Black private
Referenced by IG.Forms.ConsoleForm.FinalizeReading().
ILblActiveBg
Color IG.Forms.ConsoleForm.ILblActiveBg =Color.Yellow private
Referenced by IG.Forms.ConsoleForm.PrepareForReading().
ILblActiveFg
Color IG.Forms.ConsoleForm.ILblActiveFg =Color.Blue private
Referenced by IG.Forms.ConsoleForm.PrepareForReading().
ILblErrorBg
Color IG.Forms.ConsoleForm.ILblErrorBg =Color.Red private
Referenced by IG.Forms.ConsoleForm.InputConfirm_ReadDouble(), and IG.Forms.ConsoleForm.InputConfirm_ReadLong().
ILblErrorFg
Color IG.Forms.ConsoleForm.ILblErrorFg =Color.Blue private
Referenced by IG.Forms.ConsoleForm.InputConfirm_ReadDouble(), and IG.Forms.ConsoleForm.InputConfirm_ReadLong().
NormalOutColor
Color IG.Forms.ConsoleForm.NormalOutColor = Color.Blue
Referenced by IG.Forms.ConsoleForm.SetNormalStyle().
ErrorOutColor
Color IG.Forms.ConsoleForm.ErrorOutColor = Color.Red private
Referenced by IG.Forms.ConsoleForm.SetErrorStyle().
MarkOutColor
Color IG.Forms.ConsoleForm.MarkOutColor = Color.Violet private
Referenced by IG.Forms.ConsoleForm.SetMarkStyle().
chkWrap
CheckBox IG.Forms.ConsoleForm.chkWrap private
Referenced by IG.Forms.ConsoleForm.chkWrap_CheckedChanged().
OStyle
Styles IG.Forms.ConsoleForm.OStyle = Styles.Normal private
Referenced by IG.Forms.ConsoleForm.SetErrorStyle(), IG.Forms.ConsoleForm.SetMarkStyle(), and IG.Forms.ConsoleForm.SetNormalStyle().
HideBtn
System.Windows.Forms.Button IG.Forms.ConsoleForm.HideBtn private
TitlePanel
Panel IG.Forms.ConsoleForm.TitlePanel private
OutputOuterPnl
Panel IG.Forms.ConsoleForm.OutputOuterPnl private
ControlPanel
Panel IG.Forms.ConsoleForm.ControlPanel private
TitleLbl
Label IG.Forms.ConsoleForm.TitleLbl private
OutBox
RichTextBox IG.Forms.ConsoleForm.OutBox private
Referenced by IG.Forms.ConsoleForm.chkWrap_CheckedChanged(), IG.Forms.ConsoleForm.UpdateOutSettings(), IG.Forms.ConsoleForm.UpdateSettings(), and IG.Forms.ConsoleForm.WriteOutput().
OutputLbl
Label IG.Forms.ConsoleForm.OutputLbl private
InputPnl
Panel IG.Forms.ConsoleForm.InputPnl private
Referenced by IG.Forms.ConsoleForm.InputChk_CheckedChanged().
InBox
RichTextBox IG.Forms.ConsoleForm.InBox private
Referenced by IG.Forms.ConsoleForm.FinalizeReading(), IG.Forms.ConsoleForm.InputConfirm_Read(), IG.Forms.ConsoleForm.InputConfirm_ReadDouble(), IG.Forms.ConsoleForm.InputConfirm_ReadLong(), IG.Forms.ConsoleForm.PrepareForReading(), and IG.Forms.ConsoleForm.UpdateSettings().
InputLbl
Label IG.Forms.ConsoleForm.InputLbl private
InputMsgLbl
Label IG.Forms.ConsoleForm.InputMsgLbl private
Referenced by IG.Forms.ConsoleForm.FinalizeReading(), IG.Forms.ConsoleForm.InputConfirm_ReadDouble(), IG.Forms.ConsoleForm.InputConfirm_ReadLong(), and IG.Forms.ConsoleForm.PrepareForReading().
ConfirmInputBtn
Button IG.Forms.ConsoleForm.ConfirmInputBtn private
InputChk
CheckBox IG.Forms.ConsoleForm.InputChk private
Referenced by IG.Forms.ConsoleForm.HideInput(), IG.Forms.ConsoleForm.InputChk_CheckedChanged(), IG.Forms.ConsoleForm.PrepareForReading(), and IG.Forms.ConsoleForm.ShowInput().
button1
Button IG.Forms.ConsoleForm.button1 private
StatusLbl
Label IG.Forms.ConsoleForm.StatusLbl private
formthread
Thread IG.Forms.ConsoleForm.formthread = null private
Referenced by IG.Forms.ConsoleForm.ShowThread().
OutBuf
string IG.Forms.ConsoleForm.OutBuf =null protected
Referenced by IG.Forms.ConsoleForm.Write(), and IG.Forms.ConsoleForm.WriteOutput().
OutputStarted
bool IG.Forms.ConsoleForm.OutputStarted =false protected
Referenced by IG.Forms.ConsoleForm.Write(), and IG.Forms.ConsoleForm.WriteOutput().
OutputEnded
bool IG.Forms.ConsoleForm.OutputEnded =false private
Referenced by IG.Forms.ConsoleForm.Write(), and IG.Forms.ConsoleForm.WriteOutput().
RecCountWrite
int IG.Forms.ConsoleForm.RecCountWrite = 0 private
Referenced by IG.Forms.ConsoleForm.Write().
errorlock
object IG.Forms.ConsoleForm.errorlock = new object() private
Referenced by IG.Forms.ConsoleForm.ReportErrorBas().
reccounterror
int IG.Forms.ConsoleForm.reccounterror = 0 private
Referenced by IG.Forms.ConsoleForm.ReportErrorBas().
_Reporter
ReporterBase IG.Forms.ConsoleForm._Reporter = null protected
RecCountError
int IG.Forms.ConsoleForm.RecCountError = 0 private
Referenced by IG.Forms.ConsoleForm.ReportError0().
ErrorLock00
object IG.Forms.ConsoleForm.ErrorLock00 = new object() private
Referenced by IG.Forms.ConsoleForm.ReportError0().
InputResultString
string IG.Forms.ConsoleForm.InputResultString =null private
Referenced by IG.Forms.ConsoleForm.FinalizeReading(), IG.Forms.ConsoleForm.InputConfirm_Read(), IG.Forms.ConsoleForm.InputConfirm_ReadDouble(), IG.Forms.ConsoleForm.InputConfirm_ReadLong(), IG.Forms.ConsoleForm.PrepareForReading(), IG.Forms.ConsoleForm.Read(), IG.Forms.ConsoleForm.ReadDouble(), IG.Forms.ConsoleForm.ReadLine(), IG.Forms.ConsoleForm.ReadLong(), and IG.Forms.ConsoleForm.ReadString().
InputMessage
string IG.Forms.ConsoleForm.InputMessage =null private
Referenced by IG.Forms.ConsoleForm.FinalizeReading(), IG.Forms.ConsoleForm.PrepareForReading(), IG.Forms.ConsoleForm.Read(), IG.Forms.ConsoleForm.ReadDouble(), IG.Forms.ConsoleForm.ReadLine(), IG.Forms.ConsoleForm.ReadLong(), and IG.Forms.ConsoleForm.ReadString().
ReadStarted
bool IG.Forms.ConsoleForm.ReadStarted =false private
Referenced by IG.Forms.ConsoleForm.InBox_KeyPress(), IG.Forms.ConsoleForm.InBox_KeyUp(), IG.Forms.ConsoleForm.InputConfirm_Read(), IG.Forms.ConsoleForm.InputConfirm_ReadDouble(), IG.Forms.ConsoleForm.InputConfirm_ReadLong(), IG.Forms.ConsoleForm.PrepareForReading(), IG.Forms.ConsoleForm.Read(), IG.Forms.ConsoleForm.ReadDouble(), IG.Forms.ConsoleForm.ReadLine(), IG.Forms.ConsoleForm.ReadLong(), IG.Forms.ConsoleForm.ReadString(), and IG.Forms.ConsoleForm.RunInputConfirmationDelegate().
ReadFinished
bool IG.Forms.ConsoleForm.ReadFinished =false private
Referenced by IG.Forms.ConsoleForm.InBox_KeyPress(), IG.Forms.ConsoleForm.InBox_KeyUp(), IG.Forms.ConsoleForm.InputConfirm_Read(), IG.Forms.ConsoleForm.InputConfirm_ReadDouble(), IG.Forms.ConsoleForm.InputConfirm_ReadLong(), IG.Forms.ConsoleForm.Read(), IG.Forms.ConsoleForm.ReadDouble(), IG.Forms.ConsoleForm.ReadLine(), IG.Forms.ConsoleForm.ReadLong(), IG.Forms.ConsoleForm.ReadString(), IG.Forms.ConsoleForm.RunInputConfirmationDelegate(), and IG.Forms.ConsoleForm.WaitResult().
MultiLineInput
bool IG.Forms.ConsoleForm.MultiLineInput = false private
Referenced by IG.Forms.ConsoleForm.FinalizeReading(), IG.Forms.ConsoleForm.InBox_KeyPress(), IG.Forms.ConsoleForm.Read(), IG.Forms.ConsoleForm.ReadDouble(), IG.Forms.ConsoleForm.ReadLine(), IG.Forms.ConsoleForm.ReadLong(), and IG.Forms.ConsoleForm.ReadString().
SingleCharacterInput
bool IG.Forms.ConsoleForm.SingleCharacterInput = false private
Referenced by IG.Forms.ConsoleForm.FinalizeReading(), IG.Forms.ConsoleForm.InBox_KeyUp(), IG.Forms.ConsoleForm.Read(), IG.Forms.ConsoleForm.ReadDouble(), IG.Forms.ConsoleForm.ReadLine(), IG.Forms.ConsoleForm.ReadLong(), and IG.Forms.ConsoleForm.ReadString().
DeleteLastNewline
bool IG.Forms.ConsoleForm.DeleteLastNewline = false private
Referenced by IG.Forms.ConsoleForm.ConfirmInputBtn_Click(), IG.Forms.ConsoleForm.InBox_KeyPress(), IG.Forms.ConsoleForm.InBox_KeyUp(), IG.Forms.ConsoleForm.InputConfirm_Read(), IG.Forms.ConsoleForm.InputConfirm_ReadDouble(), IG.Forms.ConsoleForm.InputConfirm_ReadLong(), and IG.Forms.ConsoleForm.PrepareForReading().
SelectInput
bool IG.Forms.ConsoleForm.SelectInput =false private
Referenced by IG.Forms.ConsoleForm.PrepareForReading(), IG.Forms.ConsoleForm.Read(), IG.Forms.ConsoleForm.ReadDouble(), IG.Forms.ConsoleForm.ReadLine(), IG.Forms.ConsoleForm.ReadLong(), and IG.Forms.ConsoleForm.ReadString().
KeyValue
int IG.Forms.ConsoleForm.KeyValue = 0 private
Referenced by IG.Forms.ConsoleForm.InBox_KeyUp(), and IG.Forms.ConsoleForm.Read().
KeyData
Keys IG.Forms.ConsoleForm.KeyData = Keys.None private
Referenced by IG.Forms.ConsoleForm.InBox_KeyUp().
KeyCode
Keys IG.Forms.ConsoleForm.KeyCode =Keys.None private
Referenced by IG.Forms.ConsoleForm.InBox_KeyUp().
FormatProvider
IFormatProvider IG.Forms.ConsoleForm.FormatProvider = System.Globalization.CultureInfo.CreateSpecificCulture("") private
Referenced by IG.Forms.ConsoleForm.InputConfirm_ReadDouble(), IG.Forms.ConsoleForm.InputConfirm_ReadLong(), IG.Forms.ConsoleForm.ReadDouble(), and IG.Forms.ConsoleForm.ReadLong().
InputConfirmDelegate
VoidDelegate IG.Forms.ConsoleForm.InputConfirmDelegate private
Referenced by IG.Forms.ConsoleForm.Read(), IG.Forms.ConsoleForm.ReadDouble(), IG.Forms.ConsoleForm.ReadLine(), IG.Forms.ConsoleForm.ReadLong(), IG.Forms.ConsoleForm.ReadString(), and IG.Forms.ConsoleForm.RunInputConfirmationDelegate().
Property Documentation
Reporter
IG.Lib.IReporter IG.Forms.ConsoleForm.Reporter get private
Referenced by IG.Forms.ConsoleForm.CloseBtn_Click(), IG.Forms.ConsoleForm.CloseForm(), IG.Forms.ConsoleForm.ConfirmInputBtn_Click(), IG.Forms.ConsoleForm.ConsoleForm_Dispose(), IG.Forms.ConsoleForm.ConsoleForm_FormClosing(), IG.Forms.ConsoleForm.ConsoleForm_Load(), IG.Forms.ConsoleForm.FinalizeReading(), IG.Forms.ConsoleForm.FormThreadFunc(), IG.Forms.ConsoleForm.HideBtn_Click(), IG.Forms.ConsoleForm.HideForm(), IG.Forms.ConsoleForm.HideInput(), IG.Forms.ConsoleForm.InBox_KeyPress(), IG.Forms.ConsoleForm.InBox_KeyUp(), IG.Forms.ConsoleForm.InBox_PreviewKeyDown(), IG.Forms.ConsoleForm.InputChk_CheckedChanged(), IG.Forms.ConsoleForm.InputConfirm_Read(), IG.Forms.ConsoleForm.InputConfirm_ReadDouble(), IG.Forms.ConsoleForm.InputConfirm_ReadLong(), IG.Forms.ConsoleForm.PrepareForReading(), IG.Forms.ConsoleForm.Read(), IG.Forms.ConsoleForm.ReadDouble(), IG.Forms.ConsoleForm.ReadLine(), IG.Forms.ConsoleForm.ReadLong(), IG.Forms.ConsoleForm.ReadString(), IG.Forms.ConsoleForm.Report(), IG.Forms.ConsoleForm.RunInputConfirmationDelegate(), IG.Forms.ConsoleForm.SetErrorStyle(), IG.Forms.ConsoleForm.SetMarkStyle(), IG.Forms.ConsoleForm.SetNormalStyle(), IG.Forms.ConsoleForm.ShowInput(), and IG.Forms.ConsoleForm.WriteOutput().
IsBackground
bool IG.Forms.ConsoleForm.IsBackground get set
OutBackColor
Color IG.Forms.ConsoleForm.OutBackColor get set
Output console background color.
OutForeColor
Color IG.Forms.ConsoleForm.OutForeColor get set
Output console foreground color.
OutSelectionColor
Color IG.Forms.ConsoleForm.OutSelectionColor get set
Output console foreground color.
Referenced by IG.Forms.ConsoleForm.Example(), IG.Forms.ConsoleForm.SetErrorStyle(), IG.Forms.ConsoleForm.SetMarkStyle(), IG.Forms.ConsoleForm.SetNormalStyle(), and IG.Forms.ConsoleForm.UpdateOutSettings().
Style
Styles IG.Forms.ConsoleForm.Style get set
Defines the output style of the console.
Referenced by IG.Forms.ConsoleForm.Example(), IG.Forms.ConsoleForm.FinalizeReading(), IG.Forms.TestTcpClient.Report(), IG.Forms.TestTcpServer.Report(), IG.Forms.TestTcpClient.ReportError(), IG.Forms.TestTcpServer.ReportError(), IG.Forms.ConsoleForm.ReportError0(), IG.Forms.ConsoleForm.ReportErrorBas(), IG.Forms.TestTcpClient.ReportMarked(), and IG.Forms.TestTcpServer.ReportMarked().
InBackColor
Color IG.Forms.ConsoleForm.InBackColor get set
Input console background color.
InForeColor
Color IG.Forms.ConsoleForm.InForeColor get set
Input console foreground color.
Reporter11
ReporterBase IG.Forms.ConsoleForm.Reporter11 get
Gets the reporter used by the current console consform for launching error and warning reports, notices, etc.
$A Igor Oct08;
The documentation for this class was generated from the following file:
iglib/igforms/Basic/ConsoleForm.cs