Doc: IGLib EXTENDED: NUnit.Samples.Money.Money Class Reference
NUnit.Samples.Money.Money Class Reference
A simple Money.
Public Member Functions
Money (int amount, String currency)
Constructs a money from the given amount and currency.
IMoney Add (IMoney m)
Adds a money to this money. Forwards the request to the AddMoney helper.
IMoney AddMoney (Money m)
Adds a simple Money to this money. This is a helper method for implementing double dispatch.
IMoney AddMoneyBag (MoneyBag s)
Adds a MoneyBag to this money. This is a helper method for implementing double dispatch.
override bool Equals (Object anObject)
override int GetHashCode ()
IMoney Multiply (int factor)
Multiplies a money by the given factor.
IMoney Negate ()
Negates this money.
IMoney Subtract (IMoney m)
Subtracts a money from this money.
override String ToString ()
Properties
int Amount [get]
String Currency [get]
bool IsZero [get]
Properties inherited from NUnit.Samples.Money.IMoney
bool IsZero [get]
True if this money is zero.
Private Attributes
int fAmount
String fCurrency
Detailed Description
A simple Money.
Constructor & Destructor Documentation
Money()
NUnit.Samples.Money.Money.Money (int amount, String currency) inline
Constructs a money from the given amount and currency.
References NUnit.Samples.Money.Money.fAmount, and NUnit.Samples.Money.Money.fCurrency.
Referenced by NUnit.Samples.Money.Money.AddMoney(), NUnit.Samples.Money.Money.Equals(), NUnit.Samples.Money.Money.Multiply(), and NUnit.Samples.Money.Money.Negate().
Member Function Documentation
Add()
IMoney NUnit.Samples.Money.Money.Add (IMoney m) inline
Adds a money to this money. Forwards the request to the AddMoney helper.
Implements NUnit.Samples.Money.IMoney.
Referenced by NUnit.Samples.Money.MoneyTest.MixedSimpleAdd(), NUnit.Samples.Money.MoneyTest.SimpleAdd(), NUnit.Samples.Money.MoneyTest.SimpleBagAdd(), and NUnit.Samples.Money.Money.Subtract().
AddMoney()
IMoney NUnit.Samples.Money.Money.AddMoney (Money m) inline
Adds a simple Money to this money. This is a helper method for implementing double dispatch.
Implements NUnit.Samples.Money.IMoney.
References NUnit.Samples.Money.Money.Amount, NUnit.Samples.Money.Money.Currency, and NUnit.Samples.Money.Money.Money().
AddMoneyBag()
IMoney NUnit.Samples.Money.Money.AddMoneyBag (MoneyBag s) inline
Adds a MoneyBag to this money. This is a helper method for implementing double dispatch.
Implements NUnit.Samples.Money.IMoney.
Equals()
override bool NUnit.Samples.Money.Money.Equals (Object anObject) inline
References NUnit.Samples.Money.Money.Amount, NUnit.Samples.Money.Money.Currency, NUnit.Samples.Money.Money.IsZero, and NUnit.Samples.Money.Money.Money().
Referenced by NUnit.Samples.Money.MoneyTest.MoneyBagEquals(), NUnit.Samples.Money.MoneyTest.MoneyEquals(), and NUnit.Samples.Money.MoneyTest.MoneyHash().
GetHashCode()
override int NUnit.Samples.Money.Money.GetHashCode () inline
References NUnit.Samples.Money.Money.fAmount, and NUnit.Samples.Money.Money.fCurrency.
Referenced by NUnit.Samples.Money.MoneyTest.MoneyHash().
Multiply()
IMoney NUnit.Samples.Money.Money.Multiply (int factor) inline
Multiplies a money by the given factor.
Implements NUnit.Samples.Money.IMoney.
References NUnit.Samples.Money.Money.Amount, NUnit.Samples.Money.Money.Currency, and NUnit.Samples.Money.Money.Money().
Referenced by NUnit.Samples.Money.MoneyTest.SimpleMultiply().
Negate()
IMoney NUnit.Samples.Money.Money.Negate () inline
Negates this money.
Implements NUnit.Samples.Money.IMoney.
References NUnit.Samples.Money.Money.Amount, NUnit.Samples.Money.Money.Currency, and NUnit.Samples.Money.Money.Money().
Referenced by NUnit.Samples.Money.MoneyTest.SimpleNegate().
Subtract()
IMoney NUnit.Samples.Money.Money.Subtract (IMoney m) inline
Subtracts a money from this money.
Implements NUnit.Samples.Money.IMoney.
References NUnit.Samples.Money.Money.Add().
Referenced by NUnit.Samples.Money.MoneyTest.Normalize4(), and NUnit.Samples.Money.MoneyTest.SimpleSubtract().
ToString()
override String NUnit.Samples.Money.Money.ToString () inline
References NUnit.Samples.Money.Money.Amount, and NUnit.Samples.Money.Money.Currency.
Referenced by NUnit.Samples.Money.MoneyTest.Print().
Member Data Documentation
fAmount
int NUnit.Samples.Money.Money.fAmount private
Referenced by NUnit.Samples.Money.Money.GetHashCode(), and NUnit.Samples.Money.Money.Money().
fCurrency
String NUnit.Samples.Money.Money.fCurrency private
Referenced by NUnit.Samples.Money.Money.GetHashCode(), and NUnit.Samples.Money.Money.Money().
Property Documentation
Amount
int NUnit.Samples.Money.Money.Amount get
Referenced by NUnit.Samples.Money.Money.AddMoney(), NUnit.Samples.Money.MoneyBag.Contains(), NUnit.Samples.Money.Money.Equals(), NUnit.Samples.Money.Money.Multiply(), NUnit.Samples.Money.Money.Negate(), and NUnit.Samples.Money.Money.ToString().
Currency
String NUnit.Samples.Money.Money.Currency get
Referenced by NUnit.Samples.Money.Money.AddMoney(), NUnit.Samples.Money.MoneyBag.AppendMoney(), NUnit.Samples.Money.MoneyBag.Contains(), NUnit.Samples.Money.Money.Equals(), NUnit.Samples.Money.Money.Multiply(), NUnit.Samples.Money.Money.Negate(), and NUnit.Samples.Money.Money.ToString().
IsZero
bool NUnit.Samples.Money.Money.IsZero get
Referenced by NUnit.Samples.Money.Money.Equals().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1/samples/csharp/money/Money.cs