Doc: IGLib EXTENDED: AForge.Imaging.Filters.ChannelFiltering Class Reference
AForge.Imaging.Filters.ChannelFiltering Class Reference
Channels filters.
Public Member Functions
ChannelFiltering ()
Initializes a new instance of the ChannelFiltering class.
ChannelFiltering (IntRange red, IntRange green, IntRange blue)
Initializes a new instance of the ChannelFiltering class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image, Rectangle rect)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
IntRange Red [get, set]
Red channel's range.
byte FillRed [get, set]
Red fill value.
IntRange Green [get, set]
Green channel's range.
byte FillGreen [get, set]
Green fill value.
IntRange Blue [get, set]
Blue channel's range.
byte FillBlue [get, set]
Blue fill value.
bool RedFillOutsideRange [get, set]
Determines, if red channel should be filled inside or outside filtering range.
bool GreenFillOutsideRange [get, set]
Determines, if green channel should be filled inside or outside filtering range.
bool BlueFillOutsideRange [get, set]
Determines, if blue channel should be filled inside or outside filtering range.
Properties inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Member Functions
void CalculateMap (IntRange range, byte fill, bool fillOutsideRange, byte[] map)
Calculate filtering map.
Private Attributes
IntRange red = new IntRange(0, 255)
IntRange green = new IntRange(0, 255)
IntRange blue = new IntRange(0, 255)
byte fillR = 0
byte fillG = 0
byte fillB = 0
bool redFillOutsideRange = true
bool greenFillOutsideRange = true
bool blueFillOutsideRange = true
byte[] mapRed = new byte[256]
byte[] mapGreen = new byte[256]
byte[] mapBlue = new byte[256]
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Channels filters.
The filter does color channels' filtering by clearing (filling with specified values) values, which are inside/outside of the specified value's range. The filter allows to fill certain ranges of RGB color channels with specified value.
The filter is similar to ColorFiltering, but operates with not entire pixels, but with their RGB values individually. This means that pixel itself may not be filtered (will be kept), but one of its RGB values may be filtered if they are inside/outside of specified range.
The filter accepts 24 and 32 bpp color images for processing.
Sample usage:
// create filter
ChannelFiltering filter = new ChannelFiltering();
// set channels' ranges to keep
filter.Red   = new IntRange(0, 255);
filter.Green = new IntRange(100, 255);
filter.Blue  = new IntRange(100, 255);
// apply the filter
filter.ApplyInPlace(image);
Initial image:
Result image:
See also
ColorFiltering
Constructor & Destructor Documentation
ChannelFiltering() [1/2]
AForge.Imaging.Filters.ChannelFiltering.ChannelFiltering () inline
Initializes a new instance of the ChannelFiltering class.
ChannelFiltering() [2/2]
AForge.Imaging.Filters.ChannelFiltering.ChannelFiltering (IntRange red, IntRange green, IntRange blue) inline
Initializes a new instance of the ChannelFiltering class.
Parameters
red Red channel's filtering range.
green Green channel's filtering range.
blue Blue channel's filtering range.
References AForge.Imaging.Filters.ChannelFiltering.blue, AForge.Imaging.Filters.ChannelFiltering.Blue, AForge.Imaging.Filters.ChannelFiltering.formatTranslations, AForge.Imaging.Filters.ChannelFiltering.green, AForge.Imaging.Filters.ChannelFiltering.Green, AForge.Imaging.Filters.ChannelFiltering.red, and AForge.Imaging.Filters.ChannelFiltering.Red.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.ChannelFiltering.ProcessFilter (UnmanagedImage image, Rectangle rect) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
rect Image rectangle for processing by the filter.
Implements AForge.Imaging.Filters.BaseInPlacePartialFilter.
References AForge.Imaging.RGB.B, AForge.Imaging.RGB.G, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.Filters.ChannelFiltering.mapBlue, AForge.Imaging.Filters.ChannelFiltering.mapGreen, AForge.Imaging.Filters.ChannelFiltering.mapRed, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, and AForge.Imaging.UnmanagedImage.Stride.
CalculateMap()
void AForge.Imaging.Filters.ChannelFiltering.CalculateMap (IntRange range, byte fill, bool fillOutsideRange, byte[] map) inline private
Calculate filtering map.
Parameters
range Filtering range.
fill Fillter value.
fillOutsideRange Fill outside or inside the range.
map Filtering map.
References AForge.IntRange.Max, and AForge.IntRange.Min.
Member Data Documentation
red
IntRange AForge.Imaging.Filters.ChannelFiltering.red = new IntRange(0, 255) private
Referenced by AForge.Imaging.Filters.ChannelFiltering.ChannelFiltering().
green
IntRange AForge.Imaging.Filters.ChannelFiltering.green = new IntRange(0, 255) private
Referenced by AForge.Imaging.Filters.ChannelFiltering.ChannelFiltering().
blue
IntRange AForge.Imaging.Filters.ChannelFiltering.blue = new IntRange(0, 255) private
Referenced by AForge.Imaging.Filters.ChannelFiltering.ChannelFiltering().
fillR
byte AForge.Imaging.Filters.ChannelFiltering.fillR = 0 private
fillG
byte AForge.Imaging.Filters.ChannelFiltering.fillG = 0 private
fillB
byte AForge.Imaging.Filters.ChannelFiltering.fillB = 0 private
redFillOutsideRange
bool AForge.Imaging.Filters.ChannelFiltering.redFillOutsideRange = true private
greenFillOutsideRange
bool AForge.Imaging.Filters.ChannelFiltering.greenFillOutsideRange = true private
blueFillOutsideRange
bool AForge.Imaging.Filters.ChannelFiltering.blueFillOutsideRange = true private
mapRed
byte [] AForge.Imaging.Filters.ChannelFiltering.mapRed = new byte[256] private
Referenced by AForge.Imaging.Filters.ChannelFiltering.ProcessFilter().
mapGreen
byte [] AForge.Imaging.Filters.ChannelFiltering.mapGreen = new byte[256] private
Referenced by AForge.Imaging.Filters.ChannelFiltering.ProcessFilter().
mapBlue
byte [] AForge.Imaging.Filters.ChannelFiltering.mapBlue = new byte[256] private
Referenced by AForge.Imaging.Filters.ChannelFiltering.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.ChannelFiltering.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.ChannelFiltering.ChannelFiltering().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.ChannelFiltering.FormatTranslations get
Format translations dictionary.
Red
IntRange AForge.Imaging.Filters.ChannelFiltering.Red get set
Red channel's range.
Referenced by AForge.Imaging.Filters.ChannelFiltering.ChannelFiltering().
FillRed
byte AForge.Imaging.Filters.ChannelFiltering.FillRed get set
Red fill value.
Green
IntRange AForge.Imaging.Filters.ChannelFiltering.Green get set
Green channel's range.
Referenced by AForge.Imaging.Filters.ChannelFiltering.ChannelFiltering().
FillGreen
byte AForge.Imaging.Filters.ChannelFiltering.FillGreen get set
Green fill value.
Blue
IntRange AForge.Imaging.Filters.ChannelFiltering.Blue get set
Blue channel's range.
Referenced by AForge.Imaging.Filters.ChannelFiltering.ChannelFiltering().
FillBlue
byte AForge.Imaging.Filters.ChannelFiltering.FillBlue get set
Blue fill value.
RedFillOutsideRange
bool AForge.Imaging.Filters.ChannelFiltering.RedFillOutsideRange get set
Determines, if red channel should be filled inside or outside filtering range.
Default value is set to true.
GreenFillOutsideRange
bool AForge.Imaging.Filters.ChannelFiltering.GreenFillOutsideRange get set
Determines, if green channel should be filled inside or outside filtering range.
Default value is set to true.
BlueFillOutsideRange
bool AForge.Imaging.Filters.ChannelFiltering.BlueFillOutsideRange get set
Determines, if blue channel should be filled inside or outside filtering range.
Default value is set to true.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Color Filters/ChannelFiltering.cs