Doc: IGLib EXTENDED: alglib.mincomp Class Reference
alglib.mincomp Class Reference
Classes
class minasareport
class minasastate
Static Public Member Functions
static void minlbfgssetdefaultpreconditioner (minlbfgs.minlbfgsstate state)
static void minlbfgssetcholeskypreconditioner (minlbfgs.minlbfgsstate state, double[,] p, bool isupper)
static void minbleicsetbarrierwidth (minbleic.minbleicstate state, double mu)
static void minbleicsetbarrierdecay (minbleic.minbleicstate state, double mudecay)
static void minasacreate (int n, double[] x, double[] bndl, double[] bndu, minasastate state)
static void minasasetcond (minasastate state, double epsg, double epsf, double epsx, int maxits)
static void minasasetxrep (minasastate state, bool needxrep)
static void minasasetalgorithm (minasastate state, int algotype)
static void minasasetstpmax (minasastate state, double stpmax)
static bool minasaiteration (minasastate state)
static void minasaresults (minasastate state, ref double[] x, minasareport rep)
static void minasaresultsbuf (minasastate state, ref double[] x, minasareport rep)
static void minasarestartfrom (minasastate state, double[] x, double[] bndl, double[] bndu)
static void minlbfgssetdefaultpreconditioner (minlbfgs.minlbfgsstate state)
static void minlbfgssetcholeskypreconditioner (minlbfgs.minlbfgsstate state, double[,] p, bool isupper)
static void minbleicsetbarrierwidth (minbleic.minbleicstate state, double mu)
static void minbleicsetbarrierdecay (minbleic.minbleicstate state, double mudecay)
static void minasacreate (int n, double[] x, double[] bndl, double[] bndu, minasastate state)
static void minasasetcond (minasastate state, double epsg, double epsf, double epsx, int maxits)
static void minasasetxrep (minasastate state, bool needxrep)
static void minasasetalgorithm (minasastate state, int algotype)
static void minasasetstpmax (minasastate state, double stpmax)
static bool minasaiteration (minasastate state)
static void minasaresults (minasastate state, ref double[] x, minasareport rep)
static void minasaresultsbuf (minasastate state, ref double[] x, minasareport rep)
static void minasarestartfrom (minasastate state, double[] x, double[] bndl, double[] bndu)
Static Public Attributes
const int n1 = 2
const int n2 = 2
const double stpmin = 1.0E-300
const double gtol = 0.3
const double gpaftol = 0.0001
const double gpadecay = 0.5
const double asarho = 0.5
Static Private Member Functions
static double asaboundedantigradnorm (minasastate state)
static double asaginorm (minasastate state)
static double asad1norm (minasastate state)
static bool asauisempty (minasastate state)
static void clearrequestfields (minasastate state)
static double asaboundedantigradnorm (minasastate state)
static double asaginorm (minasastate state)
static double asad1norm (minasastate state)
static bool asauisempty (minasastate state)
static void clearrequestfields (minasastate state)
Member Function Documentation
minlbfgssetdefaultpreconditioner() [1/2]
static void alglib.mincomp.minlbfgssetdefaultpreconditioner (minlbfgs.minlbfgsstate state) inline static
Referenced by alglib.minlbfgssetdefaultpreconditioner().
minlbfgssetcholeskypreconditioner() [1/2]
static void alglib.mincomp.minlbfgssetcholeskypreconditioner (minlbfgs.minlbfgsstate state, double p[,], bool isupper) inline static
Referenced by alglib.minlbfgssetcholeskypreconditioner().
minbleicsetbarrierwidth() [1/2]
static void alglib.mincomp.minbleicsetbarrierwidth (minbleic.minbleicstate state, double mu) inline static
Referenced by alglib.minbleicsetbarrierwidth().
minbleicsetbarrierdecay() [1/2]
static void alglib.mincomp.minbleicsetbarrierdecay (minbleic.minbleicstate state, double mudecay) inline static
Referenced by alglib.minbleicsetbarrierdecay().
minasacreate() [1/2]
static void alglib.mincomp.minasacreate (int n, double[] x, double[] bndl, double[] bndu, minasastate state) inline static
Referenced by alglib.minasacreate().
minasasetcond() [1/2]
static void alglib.mincomp.minasasetcond (minasastate state, double epsg, double epsf, double epsx, int maxits) inline static
Referenced by alglib.minasasetcond().
minasasetxrep() [1/2]
static void alglib.mincomp.minasasetxrep (minasastate state, bool needxrep) inline static
Referenced by alglib.minasasetxrep().
minasasetalgorithm() [1/2]
static void alglib.mincomp.minasasetalgorithm (minasastate state, int algotype) inline static
Referenced by alglib.minasasetalgorithm().
minasasetstpmax() [1/2]
static void alglib.mincomp.minasasetstpmax (minasastate state, double stpmax) inline static
Referenced by alglib.minasasetstpmax().
minasaiteration() [1/2]
static bool alglib.mincomp.minasaiteration (minasastate state) inline static
Referenced by alglib.minasaiteration().
minasaresults() [1/2]
static void alglib.mincomp.minasaresults (minasastate state, ref double[] x, minasareport rep) inline static
Referenced by alglib.minasaresults().
minasaresultsbuf() [1/2]
static void alglib.mincomp.minasaresultsbuf (minasastate state, ref double[] x, minasareport rep) inline static
Referenced by alglib.minasaresultsbuf().
minasarestartfrom() [1/2]
static void alglib.mincomp.minasarestartfrom (minasastate state, double[] x, double[] bndl, double[] bndu) inline static
Referenced by alglib.minasarestartfrom().
asaboundedantigradnorm() [1/2]
static double alglib.mincomp.asaboundedantigradnorm (minasastate state) inline static private
asaginorm() [1/2]
static double alglib.mincomp.asaginorm (minasastate state) inline static private
asad1norm() [1/2]
static double alglib.mincomp.asad1norm (minasastate state) inline static private
asauisempty() [1/2]
static bool alglib.mincomp.asauisempty (minasastate state) inline static private
clearrequestfields() [1/2]
static void alglib.mincomp.clearrequestfields (minasastate state) inline static private
minlbfgssetdefaultpreconditioner() [2/2]
static void alglib.mincomp.minlbfgssetdefaultpreconditioner (minlbfgs.minlbfgsstate state) inline static
minlbfgssetcholeskypreconditioner() [2/2]
static void alglib.mincomp.minlbfgssetcholeskypreconditioner (minlbfgs.minlbfgsstate state, double p[,], bool isupper) inline static
minbleicsetbarrierwidth() [2/2]
static void alglib.mincomp.minbleicsetbarrierwidth (minbleic.minbleicstate state, double mu) inline static
minbleicsetbarrierdecay() [2/2]
static void alglib.mincomp.minbleicsetbarrierdecay (minbleic.minbleicstate state, double mudecay) inline static
minasacreate() [2/2]
static void alglib.mincomp.minasacreate (int n, double[] x, double[] bndl, double[] bndu, minasastate state) inline static
minasasetcond() [2/2]
static void alglib.mincomp.minasasetcond (minasastate state, double epsg, double epsf, double epsx, int maxits) inline static
minasasetxrep() [2/2]
static void alglib.mincomp.minasasetxrep (minasastate state, bool needxrep) inline static
minasasetalgorithm() [2/2]
static void alglib.mincomp.minasasetalgorithm (minasastate state, int algotype) inline static
minasasetstpmax() [2/2]
static void alglib.mincomp.minasasetstpmax (minasastate state, double stpmax) inline static
minasaiteration() [2/2]
static bool alglib.mincomp.minasaiteration (minasastate state) inline static
minasaresults() [2/2]
static void alglib.mincomp.minasaresults (minasastate state, ref double[] x, minasareport rep) inline static
minasaresultsbuf() [2/2]
static void alglib.mincomp.minasaresultsbuf (minasastate state, ref double[] x, minasareport rep) inline static
minasarestartfrom() [2/2]
static void alglib.mincomp.minasarestartfrom (minasastate state, double[] x, double[] bndl, double[] bndu) inline static
asaboundedantigradnorm() [2/2]
static double alglib.mincomp.asaboundedantigradnorm (minasastate state) inline static private
asaginorm() [2/2]
static double alglib.mincomp.asaginorm (minasastate state) inline static private
asad1norm() [2/2]
static double alglib.mincomp.asad1norm (minasastate state) inline static private
asauisempty() [2/2]
static bool alglib.mincomp.asauisempty (minasastate state) inline static private
clearrequestfields() [2/2]
static void alglib.mincomp.clearrequestfields (minasastate state) inline static private
Member Data Documentation
n1
const int alglib.mincomp.n1 = 2 static
n2
const int alglib.mincomp.n2 = 2 static
stpmin
const double alglib.mincomp.stpmin = 1.0E-300 static
gtol
const double alglib.mincomp.gtol = 0.3 static
gpaftol
const double alglib.mincomp.gpaftol = 0.0001 static
gpadecay
const double alglib.mincomp.gpadecay = 0.5 static
asarho
const double alglib.mincomp.asarho = 0.5 static
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/optimization.cs