Doc: IGLib EXTENDED: AForge.Imaging.Filters.FlatFieldCorrection Class Reference
AForge.Imaging.Filters.FlatFieldCorrection Class Reference
Flat field correction filter.
Public Member Functions
FlatFieldCorrection ()
Initializes a new instance of the FlatFieldCorrection class.
FlatFieldCorrection (Bitmap backgroundImage)
Initializes a new instance of the FlatFieldCorrection class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlaceFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image)
Process the filter on the specified image.
Properties
Bitmap BackgoundImage [get, set]
Background image used for flat field correction.
UnmanagedImage UnmanagedBackgoundImage [get, set]
Background image used for flat field correction.
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.BaseInPlaceFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
Bitmap backgroundImage = null
UnmanagedImage unmanagedBackgroundImage = null
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Flat field correction filter.
The goal of flat-field correction is to remove artifacts from 2-D images that are caused by variations in the pixel-to-pixel sensitivity of the detector and/or by distortions in the optical path. The filter requires two images for the input - source image, which represents acquisition of some objects (using microscope, for example), and background image, which is taken without any objects presented. The source image is corrected using the formula: src = bgMean * src / bg, where src - source image's pixel value, bg - background image's pixel value, bgMean - mean value of background image.
<note>If background image is not provided, then it will be automatically generated on each filter run from source image. The automatically generated background image is produced running Gaussian Blur on the original image with (sigma value is set to 5, kernel size is set to 21). Before blurring the original image is resized to 1/3 of its original size and then the result of blurring is resized back to the original size. </note>
<note>The class processes only grayscale (8 bpp indexed) and color (24 bpp) images.</note>
Sample usage:
// create filter
FlatFieldCorrection filter = new FlatFieldCorrection(bgImage);
// process image
filter.ApplyInPlace(sourceImage);
Source image:
Background image:
Result image:
Constructor & Destructor Documentation
FlatFieldCorrection() [1/2]
AForge.Imaging.Filters.FlatFieldCorrection.FlatFieldCorrection () inline
Initializes a new instance of the FlatFieldCorrection class.
This constructor does not set background image, which means that background image will be generated on the fly on each filter run. The automatically generated background image is produced running Gaussian Blur on the original image with (sigma value is set to 5, kernel size is set to 21). Before blurring the original image is resized to 1/3 of its original size and then the result of blurring is resized back to the original size.
References AForge.Imaging.Filters.FlatFieldCorrection.formatTranslations.
FlatFieldCorrection() [2/2]
AForge.Imaging.Filters.FlatFieldCorrection.FlatFieldCorrection (Bitmap backgroundImage) inline
Initializes a new instance of the FlatFieldCorrection class.
Parameters
backgroundImage Background image used for flat field correction.
References AForge.Imaging.Filters.FlatFieldCorrection.backgroundImage.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.FlatFieldCorrection.ProcessFilter (UnmanagedImage image) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
Implements AForge.Imaging.Filters.BaseInPlaceFilter.
References AForge.Imaging.Filters.BaseTransformationFilter.Apply(), AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace(), AForge.Imaging.RGB.B, AForge.Imaging.Filters.FlatFieldCorrection.backgroundImage, AForge.Imaging.ImageStatistics.Blue, AForge.Imaging.UnmanagedImage.Dispose(), AForge.Imaging.RGB.G, AForge.Imaging.ImageStatistics.Gray, AForge.Imaging.ImageStatistics.Green, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Math.Histogram.Mean, AForge.Imaging.Filters.BaseResizeFilter.NewHeight, AForge.Imaging.Filters.BaseResizeFilter.NewWidth, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, AForge.Math.Geometry.Rectangle, AForge.Imaging.ImageStatistics.Red, AForge.Imaging.UnmanagedImage.Stride, AForge.Imaging.Filters.FlatFieldCorrection.unmanagedBackgroundImage, and AForge.Imaging.UnmanagedImage.Width.
Member Data Documentation
backgroundImage
Bitmap AForge.Imaging.Filters.FlatFieldCorrection.backgroundImage = null private
Referenced by AForge.Imaging.Filters.FlatFieldCorrection.FlatFieldCorrection(), and AForge.Imaging.Filters.FlatFieldCorrection.ProcessFilter().
unmanagedBackgroundImage
UnmanagedImage AForge.Imaging.Filters.FlatFieldCorrection.unmanagedBackgroundImage = null private
Referenced by AForge.Imaging.Filters.FlatFieldCorrection.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.FlatFieldCorrection.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.FlatFieldCorrection.FlatFieldCorrection().
Property Documentation
BackgoundImage
Bitmap AForge.Imaging.Filters.FlatFieldCorrection.BackgoundImage get set
Background image used for flat field correction.
The property sets the background image (without any objects), which will be used for illumination correction of an image passed to the filter.
<note>The background image must have the same size and pixel format as source image. Otherwise exception will be generated when filter is applied to source image.</note>
<note>Setting this property will clear the UnmanagedBackgoundImage property - only one background image is allowed: managed or unmanaged.</note>
UnmanagedBackgoundImage
UnmanagedImage AForge.Imaging.Filters.FlatFieldCorrection.UnmanagedBackgoundImage get set
Background image used for flat field correction.
The property sets the background image (without any objects), which will be used for illumination correction of an image passed to the filter.
<note>The background image must have the same size and pixel format as source image. Otherwise exception will be generated when filter is applied to source image.</note>
<note>Setting this property will clear the BackgoundImage property - only one background image is allowed: managed or unmanaged.</note>
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.FlatFieldCorrection.FormatTranslations get
Format translations dictionary.
See IFilterInformation.FormatTranslations for more information.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/IlluminationCorrection/FlatFieldCorrection.cs