Doc: IGLib EXTENDED: Test_Tadej.ProgramTestTadejApp Class Reference
Test_Tadej.ProgramTestTadejApp Class Reference
Static Public Member Functions
static void TestPrediction (string filePath)
static void TestPredictionFromCSV (string filePath)
static void ExamplePredictNetwork (INeuralApproximator approximator, IVector InputParameters, ref IVector predictedOutputValues)
static void ExampleLoadCastingNetwork (string directoryPath, string fileName, string internalStateFileName, ref INeuralApproximator approximator)
static void ExampleSaveCastingNetwork (string directoryPath, string fileName, string internalStateFileName, SampledDataSet trainingData, bool saveRestored)
Example of saving an entire trained neural network to a file, and then restoring it from a file. Network internal state is saved by the SaveNetwork() method that is specific to the type of the network, therefore it is saved to a separate file. The path of this file is savad with the network approximator object itself. If the saveRestored flag parameter is true then the restored file ia saved again for comparison.
static void ExampleSaveStoreNetwork (string directoryPath, string fileName, string internalStateFileName, SampledDataSet trainingData, bool saveRestored)
Static Private Member Functions
static void Main (string[] args)
Member Function Documentation
Main()
static void Test_Tadej.ProgramTestTadejApp.Main (string[] args) inline static private
References IG.Num.cd.
TestPrediction()
static void Test_Tadej.ProgramTestTadejApp.TestPrediction (string filePath) inline static
References IG.Num.NeuralApproximatorBase.LoadJson(), and IG.Num.IVector< T >.ToString().
Referenced by IG.App.TadejFormOldObsolete.btnPredictSave_Click().
TestPredictionFromCSV()
static void Test_Tadej.ProgramTestTadejApp.TestPredictionFromCSV (string filePath) inline static
References IG.Num.NeuralApproximatorBase.LoadJson(), IG.Neural.NeuralTadej.LoadTrainingDataCSV(), and IG.Num.IVector< T >.ToString().
ExamplePredictNetwork()
static void Test_Tadej.ProgramTestTadejApp.ExamplePredictNetwork (INeuralApproximator approximator, IVector InputParameters, ref IVector predictedOutputValues) inline static
References IG.Num.IVectorApproximator.CalculateOutput(), IG.Num.IVectorApproximator.InputLength, and IG.Num.IVector< T >.Length.
ExampleLoadCastingNetwork()
static void Test_Tadej.ProgramTestTadejApp.ExampleLoadCastingNetwork (string directoryPath, string fileName, string internalStateFileName, ref INeuralApproximator approximator) inline static
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyTo().
ExampleSaveCastingNetwork()
static void Test_Tadej.ProgramTestTadejApp.ExampleSaveCastingNetwork (string directoryPath, string fileName, string internalStateFileName, SampledDataSet trainingData, bool saveRestored) inline static
Example of saving an entire trained neural network to a file, and then restoring it from a file. Network internal state is saved by the SaveNetwork() method that is specific to the type of the network, therefore it is saved to a separate file. The path of this file is savad with the network approximator object itself. If the saveRestored flag parameter is true then the restored file ia saved again for comparison.
Parameters
directoryPath Directory where the neural network is saved.
fileName Name o the file into which the network is saved.
internalStateFileName Name of the file where the state of the trained network (internal representation) is stored.
saveRestored If true then the restored neural network is saved again for comparison with the file where original was saved.
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyFrom(), IG.Lib.SerializationDtoBase< Type, BaseType >.CopyTo(), IG.Neural.NeuralTadej.ExampleCasting(), IG.Num.INeuralApproximator.GetErrorsTrainingRms(), IG.Num.INeuralApproximator.GetErrorsVerificationRms(), IG.Num.SampledDataSet.InputLength, IG.Num.INeuralApproximator.NetworkStateFilePath, IG.Num.IVectorApproximator.OutputLength, IG.Num.SampledDataSet.OutputLength, IG.Num.NeuralApproximatorBase.SaveJson(), and IG.Num.INeuralApproximator.TrainNetwork().
ExampleSaveStoreNetwork()
static void Test_Tadej.ProgramTestTadejApp.ExampleSaveStoreNetwork (string directoryPath, string fileName, string internalStateFileName, SampledDataSet trainingData, bool saveRestored) inline static
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyFrom(), IG.Lib.SerializationDtoBase< Type, BaseType >.CopyTo(), IG.Neural.NeuralTadej.ExampleStore(), IG.Num.INeuralApproximator.GetErrorsTrainingRms(), IG.Num.INeuralApproximator.GetErrorsVerificationRms(), IG.Num.SampledDataSet.InputLength, IG.Num.INeuralApproximator.NetworkStateFilePath, IG.Num.IVectorApproximator.OutputLength, IG.Num.SampledDataSet.OutputLength, IG.Num.INeuralApproximator.SaveNetwork(), and IG.Num.INeuralApproximator.TrainNetwork().
The documentation for this class was generated from the following file:
shelldev/extensions_shell/shell/Test_Tadej/ProgramTestTadej.cs