Doc: IGLib EXTENDED: NUnit.Framework.Api.TestAssemblyRunnerTests Class Reference
NUnit.Framework.Api.TestAssemblyRunnerTests Class Reference
Public Member Functions
void CreateRunner ()
void Load_GoodFile_ReturnsRunnableSuite ()
void Load_FileNotFound_ReturnsNonRunnableSuite ()
void Load_BadFile_ReturnsNonRunnableSuite ()
void CountTestCases_AfterLoad_ReturnsCorrectCount ()
void CountTestCases_WithoutLoad_ThrowsInvalidOperation ()
void CountTestCases_FileNotFound_ReturnsZero ()
void CountTestCases_BadFile_ReturnsZero ()
void Run_AfterLoad_ReturnsRunnableSuite ()
void Run_AfterLoad_SendsExpectedEvents ()
void Run_WithoutLoad_ReturnsError ()
void Run_FileNotFound_ReturnsNonRunnableSuite ()
void Run_BadFile_ReturnsNonRunnableSuite ()
void RunAsync_AfterLoad_ReturnsRunnableSuite ()
void RunAsync_AfterLoad_SendsExpectedEvents ()
void RunAsync_WithoutLoad_ReturnsError ()
void RunAsync_FileNotFound_ReturnsNonRunnableSuite ()
void RunAsync_BadFile_ReturnsNonRunnableSuite ()
void StopRun_WhenNoTestIsRunning_Succeeds ()
void StopRun_WhenTestIsRunning_StopsTest ()
void CancelRun_WhenNoTestIsRunning_Succeeds ()
void CancelRun_WhenTestIsRunning_StopsTest ()
Private Member Functions
void ITestListener. TestStarted (ITest test)
Called when a test has just started
void ITestListener. TestFinished (ITestResult result)
Called when a test has finished
Private Attributes
IDictionary _settings = new Hashtable()
ITestAssemblyRunner _runner
string _mockAssemblyPath
string _slowTestsPath
int _testStartedCount
int _testFinishedCount
int _successCount
int _failCount
int _skipCount
int _inconclusiveCount
Static Private Attributes
const string MOCK_ASSEMBLY = "mock-nunit-assembly.exe"
const string BAD_FILE = "mock-nunit-assembly.pdb"
const string SLOW_TESTS = "slow-nunit-tests.dll"
const string MISSING_FILE = "junk.dll"
Member Function Documentation
CreateRunner()
void NUnit.Framework.Api.TestAssemblyRunnerTests.CreateRunner () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._failCount, NUnit.Framework.Api.TestAssemblyRunnerTests._inconclusiveCount, NUnit.Framework.Api.TestAssemblyRunnerTests._mockAssemblyPath, NUnit.Framework.Api.TestAssemblyRunnerTests._runner, NUnit.Framework.Api.TestAssemblyRunnerTests._skipCount, NUnit.Framework.Api.TestAssemblyRunnerTests._slowTestsPath, NUnit.Framework.Api.TestAssemblyRunnerTests._successCount, NUnit.Framework.Api.TestAssemblyRunnerTests._testFinishedCount, NUnit.Framework.Api.TestAssemblyRunnerTests._testStartedCount, NUnit.Framework.TestContext.CurrentContext, NUnit.Framework.Api.TestAssemblyRunnerTests.MOCK_ASSEMBLY, NUnit.Framework.Api.TestAssemblyRunnerTests.SLOW_TESTS, and NUnit.Framework.TestContext.TestDirectory.
Load_GoodFile_ReturnsRunnableSuite()
void NUnit.Framework.Api.TestAssemblyRunnerTests.Load_GoodFile_ReturnsRunnableSuite () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._mockAssemblyPath, NUnit.Framework.Api.TestAssemblyRunnerTests._runner, NUnit.Framework.Api.TestAssemblyRunnerTests._settings, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Api.ITestAssemblyRunner.Load(), NUnit.Framework.Api.TestAssemblyRunnerTests.MOCK_ASSEMBLY, NUnit.Tests.Assemblies.MockAssembly.Tests, NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
Load_FileNotFound_ReturnsNonRunnableSuite()
void NUnit.Framework.Api.TestAssemblyRunnerTests.Load_FileNotFound_ReturnsNonRunnableSuite () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._runner, NUnit.Framework.Api.TestAssemblyRunnerTests._settings, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Api.ITestAssemblyRunner.Load(), NUnit.Framework.Api.TestAssemblyRunnerTests.MISSING_FILE, NUnit.Framework.Internal.PropertyNames.SkipReason, NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
Load_BadFile_ReturnsNonRunnableSuite()
void NUnit.Framework.Api.TestAssemblyRunnerTests.Load_BadFile_ReturnsNonRunnableSuite () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._runner, NUnit.Framework.Api.TestAssemblyRunnerTests._settings, NUnit.Framework.Api.TestAssemblyRunnerTests.BAD_FILE, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Api.ITestAssemblyRunner.Load(), NUnit.Framework.Internal.PropertyNames.SkipReason, NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
CountTestCases_AfterLoad_ReturnsCorrectCount()
void NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_AfterLoad_ReturnsCorrectCount () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._mockAssemblyPath, NUnit.Framework.Api.TestAssemblyRunnerTests._runner, NUnit.Framework.Api.TestAssemblyRunnerTests._settings, NUnit.Framework.Api.ITestAssemblyRunner.CountTestCases(), NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Api.ITestAssemblyRunner.Load(), NUnit.Tests.Assemblies.MockAssembly.Tests, and NUnit.Framework.Assert.That().
CountTestCases_WithoutLoad_ThrowsInvalidOperation()
void NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_WithoutLoad_ThrowsInvalidOperation () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._runner, NUnit.Framework.Api.ITestAssemblyRunner.CountTestCases(), NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
CountTestCases_FileNotFound_ReturnsZero()
void NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_FileNotFound_ReturnsZero () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._runner, NUnit.Framework.Api.TestAssemblyRunnerTests._settings, NUnit.Framework.Api.ITestAssemblyRunner.CountTestCases(), NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Api.ITestAssemblyRunner.Load(), NUnit.Framework.Api.TestAssemblyRunnerTests.MISSING_FILE, and NUnit.Framework.Assert.That().
CountTestCases_BadFile_ReturnsZero()
void NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_BadFile_ReturnsZero () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._runner, NUnit.Framework.Api.TestAssemblyRunnerTests._settings, NUnit.Framework.Api.TestAssemblyRunnerTests.BAD_FILE, NUnit.Framework.Api.ITestAssemblyRunner.CountTestCases(), NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Api.ITestAssemblyRunner.Load(), and NUnit.Framework.Assert.That().
Run_AfterLoad_ReturnsRunnableSuite()
void NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_ReturnsRunnableSuite () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._mockAssemblyPath, NUnit.Framework.Api.TestAssemblyRunnerTests._runner, NUnit.Framework.Api.TestAssemblyRunnerTests._settings, NUnit.Framework.Interfaces.ResultState.ChildFailure, NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Tests.Assemblies.MockAssembly.ErrorsAndFailures, NUnit.Tests.Assemblies.MockAssembly.Inconclusive, NUnit.Framework.Api.ITestAssemblyRunner.Load(), NUnit.Framework.Internal.TestListener.NULL, NUnit.Framework.Api.ITestAssemblyRunner.Run(), NUnit.Tests.Assemblies.MockAssembly.Skipped, NUnit.Tests.Assemblies.MockAssembly.Success, NUnit.Tests.Assemblies.MockAssembly.Tests, NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
Run_AfterLoad_SendsExpectedEvents()
void NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_SendsExpectedEvents () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._failCount, NUnit.Framework.Api.TestAssemblyRunnerTests._inconclusiveCount, NUnit.Framework.Api.TestAssemblyRunnerTests._mockAssemblyPath, NUnit.Framework.Api.TestAssemblyRunnerTests._runner, NUnit.Framework.Api.TestAssemblyRunnerTests._settings, NUnit.Framework.Api.TestAssemblyRunnerTests._skipCount, NUnit.Framework.Api.TestAssemblyRunnerTests._successCount, NUnit.Framework.Api.TestAssemblyRunnerTests._testFinishedCount, NUnit.Framework.Api.TestAssemblyRunnerTests._testStartedCount, NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Tests.Assemblies.MockAssembly.ErrorsAndFailures, NUnit.Tests.Assemblies.MockAssembly.Inconclusive, NUnit.Framework.Api.ITestAssemblyRunner.Load(), NUnit.Framework.Api.ITestAssemblyRunner.Run(), NUnit.Tests.Assemblies.MockAssembly.Skipped, NUnit.Tests.Assemblies.MockAssembly.Success, NUnit.Tests.Assemblies.MockAssembly.Tests, NUnit.Tests.IgnoredFixture.Tests, NUnit.Tests.ExplicitFixture.Tests, NUnit.Tests.BadFixture.Tests, and NUnit.Framework.Assert.That().
Run_WithoutLoad_ReturnsError()
void NUnit.Framework.Api.TestAssemblyRunnerTests.Run_WithoutLoad_ReturnsError () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._runner, NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestListener.NULL, NUnit.Framework.Api.ITestAssemblyRunner.Run(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
Run_FileNotFound_ReturnsNonRunnableSuite()
void NUnit.Framework.Api.TestAssemblyRunnerTests.Run_FileNotFound_ReturnsNonRunnableSuite () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._runner, NUnit.Framework.Api.TestAssemblyRunnerTests._settings, NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Api.ITestAssemblyRunner.Load(), NUnit.Framework.Api.TestAssemblyRunnerTests.MISSING_FILE, NUnit.Framework.Interfaces.ResultState.NotRunnable, NUnit.Framework.Internal.TestListener.NULL, NUnit.Framework.Api.ITestAssemblyRunner.Run(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), NUnit.Framework.Is.TypeOf(), and NUnit.Framework.Interfaces.ResultState.WithSite().
Run_BadFile_ReturnsNonRunnableSuite()
void NUnit.Framework.Api.TestAssemblyRunnerTests.Run_BadFile_ReturnsNonRunnableSuite () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._runner, NUnit.Framework.Api.TestAssemblyRunnerTests._settings, NUnit.Framework.Api.TestAssemblyRunnerTests.BAD_FILE, NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Api.ITestAssemblyRunner.Load(), NUnit.Framework.Interfaces.ResultState.NotRunnable, NUnit.Framework.Internal.TestListener.NULL, NUnit.Framework.Api.ITestAssemblyRunner.Run(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), NUnit.Framework.Is.TypeOf(), and NUnit.Framework.Interfaces.ResultState.WithSite().
RunAsync_AfterLoad_ReturnsRunnableSuite()
void NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_ReturnsRunnableSuite () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._mockAssemblyPath, NUnit.Framework.Api.TestAssemblyRunnerTests._runner, NUnit.Framework.Api.TestAssemblyRunnerTests._settings, NUnit.Framework.Interfaces.ResultState.ChildFailure, NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Tests.Assemblies.MockAssembly.ErrorsAndFailures, NUnit.Framework.Interfaces.ITestResult.FailCount, NUnit.Tests.Assemblies.MockAssembly.Inconclusive, NUnit.Framework.Interfaces.ITestResult.InconclusiveCount, NUnit.Framework.Interfaces.ITest.IsSuite, NUnit.Framework.Api.ITestAssemblyRunner.Load(), NUnit.Framework.Assert.NotNull(), NUnit.Framework.Internal.TestListener.NULL, NUnit.Framework.Interfaces.ITestResult.PassCount, NUnit.Framework.Api.ITestAssemblyRunner.Result, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.Framework.Api.ITestAssemblyRunner.RunAsync(), NUnit.Framework.Interfaces.ITest.RunState, NUnit.Framework.Interfaces.ITestResult.SkipCount, NUnit.Tests.Assemblies.MockAssembly.Skipped, NUnit.Tests.Assemblies.MockAssembly.Success, NUnit.Framework.Interfaces.ITestResult.Test, NUnit.Framework.Interfaces.ITest.TestCaseCount, NUnit.Tests.Assemblies.MockAssembly.Tests, NUnit.Framework.Assert.That(), NUnit.Framework.Is.TypeOf(), and NUnit.Framework.Api.ITestAssemblyRunner.WaitForCompletion().
RunAsync_AfterLoad_SendsExpectedEvents()
void NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._failCount, NUnit.Framework.Api.TestAssemblyRunnerTests._inconclusiveCount, NUnit.Framework.Api.TestAssemblyRunnerTests._mockAssemblyPath, NUnit.Framework.Api.TestAssemblyRunnerTests._runner, NUnit.Framework.Api.TestAssemblyRunnerTests._settings, NUnit.Framework.Api.TestAssemblyRunnerTests._skipCount, NUnit.Framework.Api.TestAssemblyRunnerTests._successCount, NUnit.Framework.Api.TestAssemblyRunnerTests._testFinishedCount, NUnit.Framework.Api.TestAssemblyRunnerTests._testStartedCount, NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Tests.Assemblies.MockAssembly.ErrorsAndFailures, NUnit.Tests.Assemblies.MockAssembly.Inconclusive, NUnit.Framework.Api.ITestAssemblyRunner.Load(), NUnit.Framework.Api.ITestAssemblyRunner.RunAsync(), NUnit.Tests.Assemblies.MockAssembly.Skipped, NUnit.Tests.Assemblies.MockAssembly.Success, NUnit.Tests.Assemblies.MockAssembly.Tests, NUnit.Tests.IgnoredFixture.Tests, NUnit.Tests.ExplicitFixture.Tests, NUnit.Tests.BadFixture.Tests, NUnit.Framework.Assert.That(), and NUnit.Framework.Api.ITestAssemblyRunner.WaitForCompletion().
RunAsync_WithoutLoad_ReturnsError()
void NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_WithoutLoad_ReturnsError () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._runner, NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestListener.NULL, NUnit.Framework.Api.ITestAssemblyRunner.RunAsync(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
RunAsync_FileNotFound_ReturnsNonRunnableSuite()
void NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_FileNotFound_ReturnsNonRunnableSuite () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._runner, NUnit.Framework.Api.TestAssemblyRunnerTests._settings, NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ITest.IsSuite, NUnit.Framework.Api.ITestAssemblyRunner.Load(), NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Api.TestAssemblyRunnerTests.MISSING_FILE, NUnit.Framework.Assert.NotNull(), NUnit.Framework.Interfaces.ResultState.NotRunnable, NUnit.Framework.Internal.TestListener.NULL, NUnit.Framework.Api.ITestAssemblyRunner.Result, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.Framework.Api.ITestAssemblyRunner.RunAsync(), NUnit.Framework.Interfaces.ITest.RunState, NUnit.Framework.Does.StartWith(), NUnit.Framework.Interfaces.ITestResult.Test, NUnit.Framework.Interfaces.ITest.TestCaseCount, NUnit.Framework.Assert.That(), NUnit.Framework.Is.TypeOf(), NUnit.Framework.Api.ITestAssemblyRunner.WaitForCompletion(), and NUnit.Framework.Interfaces.ResultState.WithSite().
RunAsync_BadFile_ReturnsNonRunnableSuite()
void NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_BadFile_ReturnsNonRunnableSuite () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._runner, NUnit.Framework.Api.TestAssemblyRunnerTests._settings, NUnit.Framework.Api.TestAssemblyRunnerTests.BAD_FILE, NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ITest.IsSuite, NUnit.Framework.Api.ITestAssemblyRunner.Load(), NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Assert.NotNull(), NUnit.Framework.Interfaces.ResultState.NotRunnable, NUnit.Framework.Internal.TestListener.NULL, NUnit.Framework.Api.ITestAssemblyRunner.Result, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.Framework.Api.ITestAssemblyRunner.RunAsync(), NUnit.Framework.Interfaces.ITest.RunState, NUnit.Framework.Does.StartWith(), NUnit.Framework.Interfaces.ITestResult.Test, NUnit.Framework.Interfaces.ITest.TestCaseCount, NUnit.Framework.Assert.That(), NUnit.Framework.Is.TypeOf(), NUnit.Framework.Api.ITestAssemblyRunner.WaitForCompletion(), and NUnit.Framework.Interfaces.ResultState.WithSite().
StopRun_WhenNoTestIsRunning_Succeeds()
void NUnit.Framework.Api.TestAssemblyRunnerTests.StopRun_WhenNoTestIsRunning_Succeeds () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._runner, and NUnit.Framework.Api.ITestAssemblyRunner.StopRun().
StopRun_WhenTestIsRunning_StopsTest()
void NUnit.Framework.Api.TestAssemblyRunnerTests.StopRun_WhenTestIsRunning_StopsTest () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._runner, NUnit.Framework.Api.TestAssemblyRunnerTests._settings, NUnit.Framework.Api.TestAssemblyRunnerTests._slowTestsPath, NUnit.Framework.Interfaces.ResultState.Cancelled, NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Api.ITestAssemblyRunner.IsTestComplete, NUnit.Framework.Is.LessThan(), NUnit.Framework.Api.ITestAssemblyRunner.Load(), NUnit.Framework.Internal.TestListener.NULL, NUnit.Framework.Interfaces.ITestResult.PassCount, NUnit.Framework.Api.ITestAssemblyRunner.Result, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.Framework.Api.ITestAssemblyRunner.RunAsync(), NUnit.Framework.Api.ITestAssemblyRunner.StopRun(), NUnit.Framework.Interfaces.ResultState.Success, NUnit.Framework.Interfaces.ITest.TestCaseCount, NUnit.Framework.Assert.That(), NUnit.Framework.Assert.True(), and NUnit.Framework.Api.ITestAssemblyRunner.WaitForCompletion().
CancelRun_WhenNoTestIsRunning_Succeeds()
void NUnit.Framework.Api.TestAssemblyRunnerTests.CancelRun_WhenNoTestIsRunning_Succeeds () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._runner, and NUnit.Framework.Api.ITestAssemblyRunner.StopRun().
CancelRun_WhenTestIsRunning_StopsTest()
void NUnit.Framework.Api.TestAssemblyRunnerTests.CancelRun_WhenTestIsRunning_StopsTest () inline
References NUnit.Framework.Api.TestAssemblyRunnerTests._runner, NUnit.Framework.Api.TestAssemblyRunnerTests._settings, NUnit.Framework.Api.TestAssemblyRunnerTests._slowTestsPath, NUnit.Framework.Interfaces.ResultState.Cancelled, NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Api.ITestAssemblyRunner.IsTestComplete, NUnit.Framework.Is.LessThan(), NUnit.Framework.Api.ITestAssemblyRunner.Load(), NUnit.Framework.Internal.TestListener.NULL, NUnit.Framework.Interfaces.ITestResult.PassCount, NUnit.Framework.Api.ITestAssemblyRunner.Result, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.Framework.Api.ITestAssemblyRunner.RunAsync(), NUnit.Framework.Api.ITestAssemblyRunner.StopRun(), NUnit.Framework.Interfaces.ResultState.Success, NUnit.Framework.Interfaces.ITest.TestCaseCount, NUnit.Framework.Assert.That(), NUnit.Framework.Assert.True(), and NUnit.Framework.Api.ITestAssemblyRunner.WaitForCompletion().
TestStarted()
void ITestListener. NUnit.Framework.Api.TestAssemblyRunnerTests.TestStarted (ITest test) inline private
Called when a test has just started
Parameters
test The test that is starting
Implements NUnit.Framework.Interfaces.ITestListener.
References NUnit.Framework.Api.TestAssemblyRunnerTests._testStartedCount, and NUnit.Framework.Interfaces.ITest.IsSuite.
TestFinished()
void ITestListener. NUnit.Framework.Api.TestAssemblyRunnerTests.TestFinished (ITestResult result) inline private
Called when a test has finished
Parameters
result The result of the test
Implements NUnit.Framework.Interfaces.ITestListener.
References NUnit.Framework.Api.TestAssemblyRunnerTests._failCount, NUnit.Framework.Api.TestAssemblyRunnerTests._inconclusiveCount, NUnit.Framework.Api.TestAssemblyRunnerTests._skipCount, NUnit.Framework.Api.TestAssemblyRunnerTests._successCount, NUnit.Framework.Api.TestAssemblyRunnerTests._testFinishedCount, NUnit.Framework.Interfaces.ITest.IsSuite, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.Framework.Interfaces.ResultState.Status, and NUnit.Framework.Interfaces.ITestResult.Test.
Member Data Documentation
MOCK_ASSEMBLY
const string NUnit.Framework.Api.TestAssemblyRunnerTests.MOCK_ASSEMBLY = "mock-nunit-assembly.exe" static private
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CreateRunner(), and NUnit.Framework.Api.TestAssemblyRunnerTests.Load_GoodFile_ReturnsRunnableSuite().
BAD_FILE
const string NUnit.Framework.Api.TestAssemblyRunnerTests.BAD_FILE = "mock-nunit-assembly.pdb" static private
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_BadFile_ReturnsZero(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_BadFile_ReturnsNonRunnableSuite(), and NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_BadFile_ReturnsNonRunnableSuite().
SLOW_TESTS
const string NUnit.Framework.Api.TestAssemblyRunnerTests.SLOW_TESTS = "slow-nunit-tests.dll" static private
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CreateRunner().
MISSING_FILE
const string NUnit.Framework.Api.TestAssemblyRunnerTests.MISSING_FILE = "junk.dll" static private
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_FileNotFound_ReturnsZero(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_FileNotFound_ReturnsNonRunnableSuite(), and NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_FileNotFound_ReturnsNonRunnableSuite().
_settings
IDictionary NUnit.Framework.Api.TestAssemblyRunnerTests._settings = new Hashtable() private
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CancelRun_WhenTestIsRunning_StopsTest(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_AfterLoad_ReturnsCorrectCount(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_BadFile_ReturnsZero(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_FileNotFound_ReturnsZero(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_GoodFile_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_FileNotFound_ReturnsNonRunnableSuite(), and NUnit.Framework.Api.TestAssemblyRunnerTests.StopRun_WhenTestIsRunning_StopsTest().
_runner
ITestAssemblyRunner NUnit.Framework.Api.TestAssemblyRunnerTests._runner private
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CancelRun_WhenNoTestIsRunning_Succeeds(), NUnit.Framework.Api.TestAssemblyRunnerTests.CancelRun_WhenTestIsRunning_StopsTest(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_AfterLoad_ReturnsCorrectCount(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_BadFile_ReturnsZero(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_FileNotFound_ReturnsZero(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_WithoutLoad_ThrowsInvalidOperation(), NUnit.Framework.Api.TestAssemblyRunnerTests.CreateRunner(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_GoodFile_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_WithoutLoad_ReturnsError(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_WithoutLoad_ReturnsError(), NUnit.Framework.Api.TestAssemblyRunnerTests.StopRun_WhenNoTestIsRunning_Succeeds(), and NUnit.Framework.Api.TestAssemblyRunnerTests.StopRun_WhenTestIsRunning_StopsTest().
_mockAssemblyPath
string NUnit.Framework.Api.TestAssemblyRunnerTests._mockAssemblyPath private
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_AfterLoad_ReturnsCorrectCount(), NUnit.Framework.Api.TestAssemblyRunnerTests.CreateRunner(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_GoodFile_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_ReturnsRunnableSuite(), and NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents().
_slowTestsPath
string NUnit.Framework.Api.TestAssemblyRunnerTests._slowTestsPath private
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CancelRun_WhenTestIsRunning_StopsTest(), NUnit.Framework.Api.TestAssemblyRunnerTests.CreateRunner(), and NUnit.Framework.Api.TestAssemblyRunnerTests.StopRun_WhenTestIsRunning_StopsTest().
_testStartedCount
int NUnit.Framework.Api.TestAssemblyRunnerTests._testStartedCount private
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CreateRunner(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents(), and NUnit.Framework.Api.TestAssemblyRunnerTests.TestStarted().
_testFinishedCount
int NUnit.Framework.Api.TestAssemblyRunnerTests._testFinishedCount private
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CreateRunner(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents(), and NUnit.Framework.Api.TestAssemblyRunnerTests.TestFinished().
_successCount
int NUnit.Framework.Api.TestAssemblyRunnerTests._successCount private
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CreateRunner(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents(), and NUnit.Framework.Api.TestAssemblyRunnerTests.TestFinished().
_failCount
int NUnit.Framework.Api.TestAssemblyRunnerTests._failCount private
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CreateRunner(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents(), and NUnit.Framework.Api.TestAssemblyRunnerTests.TestFinished().
_skipCount
int NUnit.Framework.Api.TestAssemblyRunnerTests._skipCount private
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CreateRunner(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents(), and NUnit.Framework.Api.TestAssemblyRunnerTests.TestFinished().
_inconclusiveCount
int NUnit.Framework.Api.TestAssemblyRunnerTests._inconclusiveCount private
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CreateRunner(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents(), and NUnit.Framework.Api.TestAssemblyRunnerTests.TestFinished().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Api/TestAssemblyRunnerTests.cs