Doc: IGLib EXTENDED: NUnitLite.TeamCityEventListener Class Reference
NUnitLite.TeamCityEventListener Class Reference
TeamCityEventListener class handles ITestListener events by issuing TeamCity service messages on the Console.
Public Member Functions
TeamCityEventListener ()
Default constructor using Console.Out
TeamCityEventListener (TextWriter outWriter)
Construct a TeamCityEventListener specifying a TextWriter. Used for testing.
void TestStarted (ITest test)
Called when a test has just started
void TestFinished (ITestResult result)
Called when a test has finished
Private Member Functions
void TC_TestSuiteStarted (string name)
void TC_TestSuiteFinished (string name)
void TC_TestStarted (string name)
void TC_TestFinished (string name, double duration)
void TC_TestIgnored (string name, string reason)
void TC_TestFailed (string name, string message, string details)
Static Private Member Functions
static string Escape (string input)
Private Attributes
readonly TextWriter _outWriter
Detailed Description
TeamCityEventListener class handles ITestListener events by issuing TeamCity service messages on the Console.
Constructor & Destructor Documentation
TeamCityEventListener() [1/2]
NUnitLite.TeamCityEventListener.TeamCityEventListener () inline
Default constructor using Console.Out
This constructor must be called before Console.Out is redirected in order to work correctly under TeamCity.
TeamCityEventListener() [2/2]
NUnitLite.TeamCityEventListener.TeamCityEventListener (TextWriter outWriter) inline
Construct a TeamCityEventListener specifying a TextWriter. Used for testing.
Parameters
outWriter The TextWriter to receive normal messages.
References NUnitLite.TeamCityEventListener._outWriter.
Member Function Documentation
TestStarted()
void NUnitLite.TeamCityEventListener.TestStarted (ITest test) inline
Called when a test has just started
Parameters
test The test that is starting
Implements NUnit.Framework.Interfaces.ITestListener.
References NUnit.Framework.Interfaces.ITest.IsSuite, NUnit.Framework.Interfaces.ITest.Name, NUnitLite.TeamCityEventListener.TC_TestStarted(), and NUnitLite.TeamCityEventListener.TC_TestSuiteStarted().
Referenced by NUnitLite.Tests.TeamCityEventListenerTests.TestStarted(), NUnitLite.TextRunner.TestStarted(), and NUnitLite.Tests.TeamCityEventListenerTests.TestSuiteStarted().
TestFinished()
void NUnitLite.TeamCityEventListener.TestFinished (ITestResult result) inline
Called when a test has finished
Parameters
result The result of the test
Implements NUnit.Framework.Interfaces.ITestListener.
References NUnit.Framework.Interfaces.ITestResult.Duration, NUnit.Framework.Interfaces.ITest.IsSuite, NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITest.Name, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.Framework.Interfaces.ITestResult.StackTrace, NUnit.Framework.Interfaces.ResultState.Status, NUnitLite.TeamCityEventListener.TC_TestFailed(), NUnitLite.TeamCityEventListener.TC_TestFinished(), NUnitLite.TeamCityEventListener.TC_TestIgnored(), NUnitLite.TeamCityEventListener.TC_TestSuiteFinished(), and NUnit.Framework.Interfaces.ITestResult.Test.
Referenced by NUnitLite.TextRunner.TestFinished(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Failed(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Ignored(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Inconclusive(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Passed(), and NUnitLite.Tests.TeamCityEventListenerTests.TestSuiteFinished().
TC_TestSuiteStarted()
void NUnitLite.TeamCityEventListener.TC_TestSuiteStarted (string name) inline private
References NUnitLite.TeamCityEventListener._outWriter, and NUnitLite.TeamCityEventListener.Escape().
Referenced by NUnitLite.TeamCityEventListener.TestStarted().
TC_TestSuiteFinished()
void NUnitLite.TeamCityEventListener.TC_TestSuiteFinished (string name) inline private
References NUnitLite.TeamCityEventListener._outWriter, and NUnitLite.TeamCityEventListener.Escape().
Referenced by NUnitLite.TeamCityEventListener.TestFinished().
TC_TestStarted()
void NUnitLite.TeamCityEventListener.TC_TestStarted (string name) inline private
References NUnitLite.TeamCityEventListener._outWriter, and NUnitLite.TeamCityEventListener.Escape().
Referenced by NUnitLite.TeamCityEventListener.TestStarted().
TC_TestFinished()
void NUnitLite.TeamCityEventListener.TC_TestFinished (string name, double duration) inline private
References NUnitLite.TeamCityEventListener._outWriter, and NUnitLite.TeamCityEventListener.Escape().
Referenced by NUnitLite.TeamCityEventListener.TestFinished().
TC_TestIgnored()
void NUnitLite.TeamCityEventListener.TC_TestIgnored (string name, string reason) inline private
References NUnitLite.TeamCityEventListener._outWriter, and NUnitLite.TeamCityEventListener.Escape().
Referenced by NUnitLite.TeamCityEventListener.TestFinished().
TC_TestFailed()
void NUnitLite.TeamCityEventListener.TC_TestFailed (string name, string message, string details) inline private
References NUnitLite.TeamCityEventListener._outWriter, and NUnitLite.TeamCityEventListener.Escape().
Referenced by NUnitLite.TeamCityEventListener.TestFinished().
Escape()
static string NUnitLite.TeamCityEventListener.Escape (string input) inline static private
Referenced by NUnitLite.TeamCityEventListener.TC_TestFailed(), NUnitLite.TeamCityEventListener.TC_TestFinished(), NUnitLite.TeamCityEventListener.TC_TestIgnored(), NUnitLite.TeamCityEventListener.TC_TestStarted(), NUnitLite.TeamCityEventListener.TC_TestSuiteFinished(), and NUnitLite.TeamCityEventListener.TC_TestSuiteStarted().
Member Data Documentation
_outWriter
readonly TextWriter NUnitLite.TeamCityEventListener._outWriter private
Referenced by NUnitLite.TeamCityEventListener.TC_TestFailed(), NUnitLite.TeamCityEventListener.TC_TestFinished(), NUnitLite.TeamCityEventListener.TC_TestIgnored(), NUnitLite.TeamCityEventListener.TC_TestStarted(), NUnitLite.TeamCityEventListener.TC_TestSuiteFinished(), NUnitLite.TeamCityEventListener.TC_TestSuiteStarted(), and NUnitLite.TeamCityEventListener.TeamCityEventListener().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/nunitlite.runner/TeamCityEventListener.cs