Doc: IGLib EXTENDED: Meta.Numerics.Statistics.Histogram Class Reference
Meta.Numerics.Statistics.Histogram Class Reference
A histogram.
Public Member Functions
Histogram (int bins)
Creates a histogram with the given number of bins.
Histogram (IList< double > borders)
Create a histogram with the given bin borders.
void Add (double value)
Adds a new value to the histogram.
void Add (int k)
void Clear ()
TestResult ChiSquaredTest (DiscreteDistribution distribution)
Properties
HistogramBin this[int k] [get]
Gets the specified bin.
int TotalCounts [get]
Gets the total number of counts in the histogram.
int OutOfRangeCounts [get]
Gets the number of counts out of the range of the histogram.
int Count [get]
Interval Range [get]
The range of values in the histogram.
Private Member Functions
bool CheckBorders ()
int FindIndex (double value)
Private Attributes
int extraCounts
Detailed Description
A histogram.
Constructor & Destructor Documentation
Histogram() [1/2]
Meta.Numerics.Statistics.Histogram.Histogram (int bins) inline
Creates a histogram with the given number of bins.
Parameters
bins The number of bins.
Histogram() [2/2]
Meta.Numerics.Statistics.Histogram.Histogram (IList< double > borders) inline
Create a histogram with the given bin borders.
Parameters
borders A list of bin borders.
References Meta.Numerics.Statistics.Histogram.CheckBorders().
Member Function Documentation
CheckBorders()
bool Meta.Numerics.Statistics.Histogram.CheckBorders () inline private
Referenced by Meta.Numerics.Statistics.Histogram.Histogram().
FindIndex()
int Meta.Numerics.Statistics.Histogram.FindIndex (double value) inline private
Referenced by Meta.Numerics.Statistics.Histogram.Add().
Add() [1/2]
void Meta.Numerics.Statistics.Histogram.Add (double value) inline
Adds a new value to the histogram.
Parameters
value The value to add.
References Meta.Numerics.Statistics.Histogram.extraCounts, and Meta.Numerics.Statistics.Histogram.FindIndex().
Add() [2/2]
void Meta.Numerics.Statistics.Histogram.Add (int k) inline
References Meta.Numerics.Statistics.Histogram.extraCounts.
Clear()
void Meta.Numerics.Statistics.Histogram.Clear () inline
References Meta.Numerics.Statistics.Histogram.extraCounts.
ChiSquaredTest()
TestResult Meta.Numerics.Statistics.Histogram.ChiSquaredTest (DiscreteDistribution distribution) inline
References Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ProbabilityMass(), and Meta.Numerics.MoreMath.Sqr().
Referenced by Test.PermutationTest.PermutationDistribution().
Member Data Documentation
extraCounts
int Meta.Numerics.Statistics.Histogram.extraCounts private
Referenced by Meta.Numerics.Statistics.Histogram.Add(), and Meta.Numerics.Statistics.Histogram.Clear().
Property Documentation
this[int k]
HistogramBin Meta.Numerics.Statistics.Histogram.this[int k] get
Gets the specified bin.
Parameters
k The index of the bin.
Returns
The specified bin.
TotalCounts
int Meta.Numerics.Statistics.Histogram.TotalCounts get
Gets the total number of counts in the histogram.
OutOfRangeCounts
int Meta.Numerics.Statistics.Histogram.OutOfRangeCounts get
Gets the number of counts out of the range of the histogram.
Count
int Meta.Numerics.Statistics.Histogram.Count get
Range
Interval Meta.Numerics.Statistics.Histogram.Range get
The range of values in the histogram.
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/Histogram.cs