Doc: IGLib EXTENDED: SRVTest.MainForm Class Reference
SRVTest.MainForm Class Reference
Public Member Functions
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void MainForm_FormClosing (object sender, FormClosingEventArgs e)
void EnableContols (bool enable)
void connectButton_Click (object sender, EventArgs e)
void disconnectButton_Click (object sender, EventArgs e)
bool Connect (string host, int port)
void Disconnect ()
void timer_Tick (object sender, EventArgs e)
void qualityCombo_SelectedIndexChanged (object sender, EventArgs e)
void resolutionCombo_SelectedIndexChanged (object sender, EventArgs e)
void srvDriverControl_SrvDrivingCommand (object sender, SRV1.MotorCommand command)
void directControlRadio_CheckedChanged (object sender, EventArgs e)
void manipulatorControl_PositionChanged (object sender, ManipulatorControl.PositionEventArgs eventArgs)
void turnControl_PositionChanged (object sender, float x)
void DriveMotors (float leftMotor, float rightMotor)
void minPowerUpDown_ValueChanged (object sender, EventArgs e)
void maxPowerUpDown_ValueChanged (object sender, EventArgs e)
void aboutButton_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
SRV1 srv = new SRV1()
int statIndex = 0
int statReady = 0
int[] statCount = new int[statLength]
bool receivedFirstDrivingCommand = false
SRV1.MotorCommand lastMotorCommand
float[] maxPowers
int maxMotorPower = 90
int minMotorPower = 50
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.Button disconnectButton
System.Windows.Forms.Button connectButton
System.Windows.Forms.TextBox ipBox
System.Windows.Forms.Label label1
System.Windows.Forms.StatusStrip statusStrip
System.Windows.Forms.ToolStripStatusLabel statusLabel
System.Windows.Forms.ToolStripStatusLabel fpsLabel
System.Windows.Forms.GroupBox groupBox2
AForge.Controls.VideoSourcePlayer cameraPlayer
System.Windows.Forms.Timer timer
System.Windows.Forms.ToolStripStatusLabel versionLabel
System.Windows.Forms.GroupBox groupBox4
System.Windows.Forms.ComboBox resolutionCombo
System.Windows.Forms.Label label3
System.Windows.Forms.ComboBox qualityCombo
System.Windows.Forms.Label label2
System.Windows.Forms.GroupBox groupBox5
SrvDriverControl srvDriverControl
AForge.Controls.ManipulatorControl manipulatorControl
System.Windows.Forms.RadioButton directControlRadio
System.Windows.Forms.RadioButton predefinedCommandsRadio
AForge.Controls.SliderControl turnControl
System.Windows.Forms.NumericUpDown maxPowerUpDown
System.Windows.Forms.NumericUpDown minPowerUpDown
System.Windows.Forms.Label maxPowerLabel
System.Windows.Forms.Label minPowerLabel
System.Windows.Forms.Button aboutButton
System.Windows.Forms.Label label4
System.Windows.Forms.NumericUpDown portUpDown
Static Private Attributes
const int statLength = 15
Constructor & Destructor Documentation
MainForm()
SRVTest.MainForm.MainForm () inline
References SRVTest.MainForm.EnableContols(), SRVTest.MainForm.InitializeComponent(), SRVTest.MainForm.maxMotorPower, SRVTest.MainForm.maxPowerUpDown, SRVTest.MainForm.minMotorPower, and SRVTest.MainForm.minPowerUpDown.
Member Function Documentation
MainForm_FormClosing()
void SRVTest.MainForm.MainForm_FormClosing (object sender, FormClosingEventArgs e) inline private
References SRVTest.MainForm.Disconnect().
Referenced by SRVTest.MainForm.InitializeComponent().
EnableContols()
void SRVTest.MainForm.EnableContols (bool enable) inline private
References SRVTest.MainForm.connectButton, SRVTest.MainForm.disconnectButton, SRVTest.MainForm.ipBox, SRVTest.MainForm.manipulatorControl, SRVTest.MainForm.portUpDown, SRVTest.MainForm.qualityCombo, SRVTest.MainForm.resolutionCombo, SRVTest.MainForm.srvDriverControl, and SRVTest.MainForm.turnControl.
Referenced by SRVTest.MainForm.connectButton_Click(), SRVTest.MainForm.Disconnect(), and SRVTest.MainForm.MainForm().
connectButton_Click()
void SRVTest.MainForm.connectButton_Click (object sender, EventArgs e) inline private
References SRVTest.MainForm.Connect(), SRVTest.MainForm.EnableContols(), SRVTest.MainForm.ipBox, SRVTest.MainForm.portUpDown, SRVTest.MainForm.qualityCombo, SRVTest.MainForm.resolutionCombo, and SRVTest.MainForm.statusLabel.
Referenced by SRVTest.MainForm.InitializeComponent().
disconnectButton_Click()
void SRVTest.MainForm.disconnectButton_Click (object sender, EventArgs e) inline private
References SRVTest.MainForm.Disconnect(), SRVTest.MainForm.fpsLabel, SRVTest.MainForm.statusLabel, and SRVTest.MainForm.versionLabel.
Referenced by SRVTest.MainForm.InitializeComponent().
Connect()
bool SRVTest.MainForm.Connect (string host, int port) inline private
References SRVTest.MainForm.cameraPlayer, AForge.Robotics.Surveyor.SRV1.Connect(), SRVTest.MainForm.Disconnect(), AForge.Robotics.Surveyor.SRV1.EnableFailsafeMode(), AForge.Robotics.Surveyor.SRV1.FlipVideo(), AForge.Robotics.Surveyor.SRV1.GetCamera(), AForge.Robotics.Surveyor.SRV1.GetVersion(), SRVTest.MainForm.receivedFirstDrivingCommand, AForge.Robotics.Surveyor.SRV1.SetQuality(), AForge.Robotics.Surveyor.SRV1.SetResolution(), SRVTest.MainForm.srv, AForge.Controls.VideoSourcePlayer.Start(), SRVTest.MainForm.statIndex, SRVTest.MainForm.statReady, SRVTest.MainForm.timer, SRVTest.MainForm.versionLabel, and AForge.Controls.VideoSourcePlayer.VideoSource.
Referenced by SRVTest.MainForm.connectButton_Click().
Disconnect()
void SRVTest.MainForm.Disconnect () inline private
References SRVTest.MainForm.cameraPlayer, AForge.Robotics.Surveyor.SRV1.Disconnect(), SRVTest.MainForm.EnableContols(), AForge.Robotics.Surveyor.SRV1.IsConnected, AForge.Video.IVideoSource.SignalToStop(), SRVTest.MainForm.srv, AForge.Robotics.Surveyor.SRV1.StopMotors(), SRVTest.MainForm.timer, AForge.Controls.VideoSourcePlayer.VideoSource, and AForge.Video.IVideoSource.WaitForStop().
Referenced by SRVTest.MainForm.Connect(), SRVTest.MainForm.disconnectButton_Click(), and SRVTest.MainForm.MainForm_FormClosing().
timer_Tick()
void SRVTest.MainForm.timer_Tick (object sender, EventArgs e) inline private
References SRVTest.MainForm.cameraPlayer, SRVTest.MainForm.fpsLabel, AForge.Video.IVideoSource.FramesReceived, SRVTest.MainForm.statCount, SRVTest.MainForm.statIndex, SRVTest.MainForm.statLength, SRVTest.MainForm.statReady, and AForge.Controls.VideoSourcePlayer.VideoSource.
Referenced by SRVTest.MainForm.InitializeComponent().
qualityCombo_SelectedIndexChanged()
void SRVTest.MainForm.qualityCombo_SelectedIndexChanged (object sender, EventArgs e) inline private
References AForge.Robotics.Surveyor.SRV1.IsConnected, SRVTest.MainForm.qualityCombo, AForge.Robotics.Surveyor.SRV1.SetQuality(), SRVTest.MainForm.srv, SRVTest.MainForm.statIndex, and SRVTest.MainForm.statReady.
Referenced by SRVTest.MainForm.InitializeComponent().
resolutionCombo_SelectedIndexChanged()
void SRVTest.MainForm.resolutionCombo_SelectedIndexChanged (object sender, EventArgs e) inline private
References AForge.Robotics.Surveyor.SRV1.IsConnected, SRVTest.MainForm.resolutionCombo, AForge.Robotics.Surveyor.SRV1.SetResolution(), SRVTest.MainForm.srv, SRVTest.MainForm.statIndex, and SRVTest.MainForm.statReady.
Referenced by SRVTest.MainForm.InitializeComponent().
srvDriverControl_SrvDrivingCommand()
void SRVTest.MainForm.srvDriverControl_SrvDrivingCommand (object sender, SRV1.MotorCommand command) inline private
References AForge.Robotics.Surveyor.SRV1.ControlMotors(), AForge.Robotics.Surveyor.SRV1.IsConnected, SRVTest.MainForm.lastMotorCommand, SRVTest.MainForm.receivedFirstDrivingCommand, SRVTest.MainForm.srv, and AForge.Robotics.Surveyor.SRV1.StopMotors().
Referenced by SRVTest.MainForm.InitializeComponent().
directControlRadio_CheckedChanged()
void SRVTest.MainForm.directControlRadio_CheckedChanged (object sender, EventArgs e) inline private
References SRVTest.MainForm.directControlRadio, SRVTest.MainForm.manipulatorControl, SRVTest.MainForm.maxPowerLabel, SRVTest.MainForm.maxPowerUpDown, SRVTest.MainForm.minPowerLabel, SRVTest.MainForm.minPowerUpDown, SRVTest.MainForm.srvDriverControl, and SRVTest.MainForm.turnControl.
Referenced by SRVTest.MainForm.InitializeComponent().
manipulatorControl_PositionChanged()
void SRVTest.MainForm.manipulatorControl_PositionChanged (object sender, ManipulatorControl.PositionEventArgs eventArgs) inline private
References SRVTest.MainForm.DriveMotors(), and SRVTest.MainForm.maxPowers.
Referenced by SRVTest.MainForm.InitializeComponent().
turnControl_PositionChanged()
void SRVTest.MainForm.turnControl_PositionChanged (object sender, float x) inline private
References SRVTest.MainForm.DriveMotors().
Referenced by SRVTest.MainForm.InitializeComponent().
DriveMotors()
void SRVTest.MainForm.DriveMotors (float leftMotor, float rightMotor) inline private
References AForge.Robotics.Surveyor.SRV1.IsConnected, SRVTest.MainForm.maxMotorPower, SRVTest.MainForm.minMotorPower, AForge.Robotics.Surveyor.SRV1.RunMotors(), and SRVTest.MainForm.srv.
Referenced by SRVTest.MainForm.manipulatorControl_PositionChanged(), and SRVTest.MainForm.turnControl_PositionChanged().
minPowerUpDown_ValueChanged()
void SRVTest.MainForm.minPowerUpDown_ValueChanged (object sender, EventArgs e) inline private
References SRVTest.MainForm.minMotorPower, and SRVTest.MainForm.minPowerUpDown.
Referenced by SRVTest.MainForm.InitializeComponent().
maxPowerUpDown_ValueChanged()
void SRVTest.MainForm.maxPowerUpDown_ValueChanged (object sender, EventArgs e) inline private
References SRVTest.MainForm.maxMotorPower, and SRVTest.MainForm.maxPowerUpDown.
Referenced by SRVTest.MainForm.InitializeComponent().
aboutButton_Click()
void SRVTest.MainForm.aboutButton_Click (object sender, EventArgs e) inline private
Referenced by SRVTest.MainForm.InitializeComponent().
Dispose()
override void SRVTest.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References SRVTest.MainForm.components.
InitializeComponent()
void SRVTest.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References SRVTest.MainForm.aboutButton, SRVTest.MainForm.aboutButton_Click(), SRVTest.MainForm.cameraPlayer, SRVTest.MainForm.components, SRVTest.MainForm.connectButton, SRVTest.MainForm.connectButton_Click(), SRVTest.MainForm.directControlRadio, SRVTest.MainForm.directControlRadio_CheckedChanged(), SRVTest.MainForm.disconnectButton, SRVTest.MainForm.disconnectButton_Click(), SRVTest.MainForm.fpsLabel, SRVTest.MainForm.groupBox1, SRVTest.MainForm.groupBox2, SRVTest.MainForm.groupBox4, SRVTest.MainForm.groupBox5, SRVTest.MainForm.ipBox, SRVTest.MainForm.label1, SRVTest.MainForm.label2, SRVTest.MainForm.label3, SRVTest.MainForm.label4, SRVTest.MainForm.MainForm_FormClosing(), SRVTest.MainForm.manipulatorControl, SRVTest.MainForm.manipulatorControl_PositionChanged(), SRVTest.MainForm.maxPowerLabel, SRVTest.MainForm.maxPowerUpDown, SRVTest.MainForm.maxPowerUpDown_ValueChanged(), SRVTest.MainForm.minPowerLabel, SRVTest.MainForm.minPowerUpDown, SRVTest.MainForm.minPowerUpDown_ValueChanged(), SRVTest.MainForm.portUpDown, AForge.Controls.SliderControl.PositionChangedHandler(), AForge.Controls.ManipulatorControl.PositionChangedHandler(), SRVTest.MainForm.predefinedCommandsRadio, SRVTest.MainForm.qualityCombo, SRVTest.MainForm.qualityCombo_SelectedIndexChanged(), SRVTest.MainForm.resolutionCombo, SRVTest.MainForm.resolutionCombo_SelectedIndexChanged(), SRVTest.MainForm.srvDriverControl, SRVTest.MainForm.srvDriverControl_SrvDrivingCommand(), SRVTest.SrvDriverControl.SrvDrivingCommand, SRVTest.MainForm.statusLabel, SRVTest.MainForm.statusStrip, SRVTest.MainForm.timer, SRVTest.MainForm.timer_Tick(), SRVTest.MainForm.turnControl, SRVTest.MainForm.turnControl_PositionChanged(), and SRVTest.MainForm.versionLabel.
Referenced by SRVTest.MainForm.MainForm().
Member Data Documentation
srv
SRV1 SRVTest.MainForm.srv = new SRV1() private
Referenced by SRVTest.MainForm.Connect(), SRVTest.MainForm.Disconnect(), SRVTest.MainForm.DriveMotors(), SRVTest.MainForm.qualityCombo_SelectedIndexChanged(), SRVTest.MainForm.resolutionCombo_SelectedIndexChanged(), and SRVTest.MainForm.srvDriverControl_SrvDrivingCommand().
statLength
const int SRVTest.MainForm.statLength = 15 static private
Referenced by SRVTest.MainForm.timer_Tick().
statIndex
int SRVTest.MainForm.statIndex = 0 private
Referenced by SRVTest.MainForm.Connect(), SRVTest.MainForm.qualityCombo_SelectedIndexChanged(), SRVTest.MainForm.resolutionCombo_SelectedIndexChanged(), and SRVTest.MainForm.timer_Tick().
statReady
int SRVTest.MainForm.statReady = 0 private
Referenced by SRVTest.MainForm.Connect(), SRVTest.MainForm.qualityCombo_SelectedIndexChanged(), SRVTest.MainForm.resolutionCombo_SelectedIndexChanged(), and SRVTest.MainForm.timer_Tick().
statCount
int [] SRVTest.MainForm.statCount = new int[statLength] private
Referenced by SRVTest.MainForm.timer_Tick().
receivedFirstDrivingCommand
bool SRVTest.MainForm.receivedFirstDrivingCommand = false private
Referenced by SRVTest.MainForm.Connect(), and SRVTest.MainForm.srvDriverControl_SrvDrivingCommand().
lastMotorCommand
SRV1.MotorCommand SRVTest.MainForm.lastMotorCommand private
Referenced by SRVTest.MainForm.srvDriverControl_SrvDrivingCommand().
maxPowers
float [] SRVTest.MainForm.maxPowers private
Initial value:
= new float[] { 0.1f, 0.2f, 0.35f, 0.5f, 0.65f, 0.8f, 0.9f, 1.0f,
            1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f }
Referenced by SRVTest.MainForm.manipulatorControl_PositionChanged().
maxMotorPower
int SRVTest.MainForm.maxMotorPower = 90 private
Referenced by SRVTest.MainForm.DriveMotors(), SRVTest.MainForm.MainForm(), and SRVTest.MainForm.maxPowerUpDown_ValueChanged().
minMotorPower
int SRVTest.MainForm.minMotorPower = 50 private
Referenced by SRVTest.MainForm.DriveMotors(), SRVTest.MainForm.MainForm(), and SRVTest.MainForm.minPowerUpDown_ValueChanged().
components
System.ComponentModel.IContainer SRVTest.MainForm.components = null private
Required designer variable.
Referenced by SRVTest.MainForm.Dispose(), and SRVTest.MainForm.InitializeComponent().
groupBox1
System.Windows.Forms.GroupBox SRVTest.MainForm.groupBox1 private
Referenced by SRVTest.MainForm.InitializeComponent().
disconnectButton
System.Windows.Forms.Button SRVTest.MainForm.disconnectButton private
Referenced by SRVTest.MainForm.EnableContols(), and SRVTest.MainForm.InitializeComponent().
connectButton
System.Windows.Forms.Button SRVTest.MainForm.connectButton private
Referenced by SRVTest.MainForm.EnableContols(), and SRVTest.MainForm.InitializeComponent().
ipBox
System.Windows.Forms.TextBox SRVTest.MainForm.ipBox private
Referenced by SRVTest.MainForm.connectButton_Click(), SRVTest.MainForm.EnableContols(), and SRVTest.MainForm.InitializeComponent().
label1
System.Windows.Forms.Label SRVTest.MainForm.label1 private
Referenced by SRVTest.MainForm.InitializeComponent().
statusStrip
System.Windows.Forms.StatusStrip SRVTest.MainForm.statusStrip private
Referenced by SRVTest.MainForm.InitializeComponent().
statusLabel
System.Windows.Forms.ToolStripStatusLabel SRVTest.MainForm.statusLabel private
Referenced by SRVTest.MainForm.connectButton_Click(), SRVTest.MainForm.disconnectButton_Click(), and SRVTest.MainForm.InitializeComponent().
fpsLabel
System.Windows.Forms.ToolStripStatusLabel SRVTest.MainForm.fpsLabel private
Referenced by SRVTest.MainForm.disconnectButton_Click(), SRVTest.MainForm.InitializeComponent(), and SRVTest.MainForm.timer_Tick().
groupBox2
System.Windows.Forms.GroupBox SRVTest.MainForm.groupBox2 private
Referenced by SRVTest.MainForm.InitializeComponent().
cameraPlayer
AForge.Controls.VideoSourcePlayer SRVTest.MainForm.cameraPlayer private
Referenced by SRVTest.MainForm.Connect(), SRVTest.MainForm.Disconnect(), SRVTest.MainForm.InitializeComponent(), and SRVTest.MainForm.timer_Tick().
timer
System.Windows.Forms.Timer SRVTest.MainForm.timer private
Referenced by SRVTest.MainForm.Connect(), SRVTest.MainForm.Disconnect(), and SRVTest.MainForm.InitializeComponent().
versionLabel
System.Windows.Forms.ToolStripStatusLabel SRVTest.MainForm.versionLabel private
Referenced by SRVTest.MainForm.Connect(), SRVTest.MainForm.disconnectButton_Click(), and SRVTest.MainForm.InitializeComponent().
groupBox4
System.Windows.Forms.GroupBox SRVTest.MainForm.groupBox4 private
Referenced by SRVTest.MainForm.InitializeComponent().
resolutionCombo
System.Windows.Forms.ComboBox SRVTest.MainForm.resolutionCombo private
Referenced by SRVTest.MainForm.connectButton_Click(), SRVTest.MainForm.EnableContols(), SRVTest.MainForm.InitializeComponent(), and SRVTest.MainForm.resolutionCombo_SelectedIndexChanged().
label3
System.Windows.Forms.Label SRVTest.MainForm.label3 private
Referenced by SRVTest.MainForm.InitializeComponent().
qualityCombo
System.Windows.Forms.ComboBox SRVTest.MainForm.qualityCombo private
Referenced by SRVTest.MainForm.connectButton_Click(), SRVTest.MainForm.EnableContols(), SRVTest.MainForm.InitializeComponent(), and SRVTest.MainForm.qualityCombo_SelectedIndexChanged().
label2
System.Windows.Forms.Label SRVTest.MainForm.label2 private
Referenced by SRVTest.MainForm.InitializeComponent().
groupBox5
System.Windows.Forms.GroupBox SRVTest.MainForm.groupBox5 private
Referenced by SRVTest.MainForm.InitializeComponent().
srvDriverControl
SrvDriverControl SRVTest.MainForm.srvDriverControl private
Referenced by SRVTest.MainForm.directControlRadio_CheckedChanged(), SRVTest.MainForm.EnableContols(), and SRVTest.MainForm.InitializeComponent().
manipulatorControl
AForge.Controls.ManipulatorControl SRVTest.MainForm.manipulatorControl private
Referenced by SRVTest.MainForm.directControlRadio_CheckedChanged(), SRVTest.MainForm.EnableContols(), and SRVTest.MainForm.InitializeComponent().
directControlRadio
System.Windows.Forms.RadioButton SRVTest.MainForm.directControlRadio private
Referenced by SRVTest.MainForm.directControlRadio_CheckedChanged(), and SRVTest.MainForm.InitializeComponent().
predefinedCommandsRadio
System.Windows.Forms.RadioButton SRVTest.MainForm.predefinedCommandsRadio private
Referenced by SRVTest.MainForm.InitializeComponent().
turnControl
AForge.Controls.SliderControl SRVTest.MainForm.turnControl private
Referenced by SRVTest.MainForm.directControlRadio_CheckedChanged(), SRVTest.MainForm.EnableContols(), and SRVTest.MainForm.InitializeComponent().
maxPowerUpDown
System.Windows.Forms.NumericUpDown SRVTest.MainForm.maxPowerUpDown private
Referenced by SRVTest.MainForm.directControlRadio_CheckedChanged(), SRVTest.MainForm.InitializeComponent(), SRVTest.MainForm.MainForm(), and SRVTest.MainForm.maxPowerUpDown_ValueChanged().
minPowerUpDown
System.Windows.Forms.NumericUpDown SRVTest.MainForm.minPowerUpDown private
Referenced by SRVTest.MainForm.directControlRadio_CheckedChanged(), SRVTest.MainForm.InitializeComponent(), SRVTest.MainForm.MainForm(), and SRVTest.MainForm.minPowerUpDown_ValueChanged().
maxPowerLabel
System.Windows.Forms.Label SRVTest.MainForm.maxPowerLabel private
Referenced by SRVTest.MainForm.directControlRadio_CheckedChanged(), and SRVTest.MainForm.InitializeComponent().
minPowerLabel
System.Windows.Forms.Label SRVTest.MainForm.minPowerLabel private
Referenced by SRVTest.MainForm.directControlRadio_CheckedChanged(), and SRVTest.MainForm.InitializeComponent().
aboutButton
System.Windows.Forms.Button SRVTest.MainForm.aboutButton private
Referenced by SRVTest.MainForm.InitializeComponent().
label4
System.Windows.Forms.Label SRVTest.MainForm.label4 private
Referenced by SRVTest.MainForm.InitializeComponent().
portUpDown
System.Windows.Forms.NumericUpDown SRVTest.MainForm.portUpDown private
Referenced by SRVTest.MainForm.connectButton_Click(), SRVTest.MainForm.EnableContols(), and SRVTest.MainForm.InitializeComponent().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Robotics/Surveyor/SRVTest/MainForm.cs
shelldev/lib_ann/aforge.net/Samples/Robotics/Surveyor/SRVTest/MainForm.Designer.cs