Doc: IGLib EXTENDED: AForge.Video.Kinect.Kinect.DeviceContext Class Reference
AForge.Video.Kinect.Kinect.DeviceContext Class Reference
Public Member Functions
DeviceContext (IntPtr device)
void AddFailureHandler (DeviceFailureHandler handler)
void FireFailureHandlers ()
Public Attributes
IntPtr Device
int ReferenceCounter
bool DeviceFailed
KinectNative.TiltState TiltState
Private Attributes
object sync = new object()
List< DeviceFailureHandler > failureHanlders = new List<DeviceFailureHandler>()
Constructor & Destructor Documentation
DeviceContext()
AForge.Video.Kinect.Kinect.DeviceContext.DeviceContext (IntPtr device) inline
References AForge.Video.Kinect.Kinect.DeviceContext.Device, AForge.Video.Kinect.Kinect.DeviceContext.DeviceFailed, and AForge.Video.Kinect.Kinect.DeviceContext.ReferenceCounter.
Member Function Documentation
AddFailureHandler()
void AForge.Video.Kinect.Kinect.DeviceContext.AddFailureHandler (DeviceFailureHandler handler) inline
References AForge.Video.Kinect.Kinect.DeviceContext.failureHanlders, and AForge.Video.Kinect.Kinect.DeviceContext.sync.
FireFailureHandlers()
void AForge.Video.Kinect.Kinect.DeviceContext.FireFailureHandlers () inline
References AForge.Video.Kinect.Kinect.DeviceContext.failureHanlders, and AForge.Video.Kinect.Kinect.DeviceContext.sync.
Referenced by AForge.Video.Kinect.Kinect.KinectStatusThread().
Member Data Documentation
Device
IntPtr AForge.Video.Kinect.Kinect.DeviceContext.Device
Referenced by AForge.Video.Kinect.Kinect.DeviceContext.DeviceContext(), and AForge.Video.Kinect.Kinect.KinectStatusThread().
ReferenceCounter
int AForge.Video.Kinect.Kinect.DeviceContext.ReferenceCounter
Referenced by AForge.Video.Kinect.Kinect.DeviceContext.DeviceContext().
DeviceFailed
bool AForge.Video.Kinect.Kinect.DeviceContext.DeviceFailed
Referenced by AForge.Video.Kinect.Kinect.DeviceContext.DeviceContext(), and AForge.Video.Kinect.Kinect.KinectStatusThread().
TiltState
KinectNative.TiltState AForge.Video.Kinect.Kinect.DeviceContext.TiltState
Referenced by AForge.Video.Kinect.Kinect.KinectStatusThread().
sync
object AForge.Video.Kinect.Kinect.DeviceContext.sync = new object() private
Referenced by AForge.Video.Kinect.Kinect.DeviceContext.AddFailureHandler(), and AForge.Video.Kinect.Kinect.DeviceContext.FireFailureHandlers().
failureHanlders
List<DeviceFailureHandler> AForge.Video.Kinect.Kinect.DeviceContext.failureHanlders = new List<DeviceFailureHandler>() private
Referenced by AForge.Video.Kinect.Kinect.DeviceContext.AddFailureHandler(), and AForge.Video.Kinect.Kinect.DeviceContext.FireFailureHandlers().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Video.Kinect/Kinect.cs