Doc: IGLib EXTENDED: CShell.Modules.Workspace.ViewModels.WorkspaceViewModel Class Reference
CShell.Modules.Workspace.ViewModels.WorkspaceViewModel Class Reference
Public Member Functions
WorkspaceViewModel (IEventAggregator eventAggregator)
void Handle (WorkspaceOpenedEventArgs message)
void Handle (WorkspaceClosingEventArgs message)
IEnumerable< IResult > Open (object node)
IEnumerable< IResult > Selected (object node)
Properties
override PaneLocation PreferredLocation [get]
override Uri IconSource [get]
override Uri Uri [get]
CShellFileViewModel CShellFile [get, set]
TreeViewModel Tree [get]
Properties inherited from CShell.Framework.Tool
ICommand?? CloseCommand [get]
abstract PaneLocation PreferredLocation [get]
abstract Uri Uri [get]
virtual Uri IconSource [get]
bool IsVisible [get, set]
Properties inherited from CShell.Framework.ITool
Uri Uri [get]
ICommand CloseCommand [get]
PaneLocation PreferredLocation [get]
bool IsVisible [get, set]
Private Member Functions
void LoadWorkspace (CShell.Workspace workspace)
void UnloadWorkspace (CShell.Workspace workspace)
Private Attributes
CShellFileViewModel cShellFile
TreeViewModel tree
Additional Inherited Members
Protected Member Functions inherited from CShell.Framework.Tool
Tool ()
Constructor & Destructor Documentation
WorkspaceViewModel()
CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.WorkspaceViewModel (IEventAggregator eventAggregator) inline
References CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.LoadWorkspace(), and CShell.Shell.Workspace.
Member Function Documentation
LoadWorkspace()
void CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.LoadWorkspace (CShell.Workspace workspace) inline private
References CShell.Modules.Workspace.ViewModels.TreeViewModel.Children, CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.cShellFile, CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.CShellFile, CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.tree, and CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.Tree.
Referenced by CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.Handle(), and CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.WorkspaceViewModel().
UnloadWorkspace()
void CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.UnloadWorkspace (CShell.Workspace workspace) inline private
References CShell.Modules.Workspace.ViewModels.TreeViewModel.Dispose(), CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.tree, and CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.Tree.
Referenced by CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.Handle().
Handle() [1/2]
void CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.Handle (WorkspaceOpenedEventArgs message) inline
References CShell.Workspace.CShellFile, CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.LoadWorkspace(), and CShell.WorkspaceOpenedEventArgs.Workspace.
Handle() [2/2]
void CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.Handle (WorkspaceClosingEventArgs message) inline
References CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.UnloadWorkspace(), and CShell.WorkspaceClosingEventArgs.Workspace.
Open()
IEnumerable<IResult> CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.Open (object node) inline
References CShell.Framework.Results.Show.Document().
Selected()
IEnumerable<IResult> CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.Selected (object node) inline
Member Data Documentation
cShellFile
CShellFileViewModel CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.cShellFile private
Referenced by CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.LoadWorkspace().
tree
TreeViewModel CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.tree private
Referenced by CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.LoadWorkspace(), and CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.UnloadWorkspace().
Property Documentation
PreferredLocation
override PaneLocation CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.PreferredLocation get
IconSource
override Uri CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.IconSource get
Uri
override Uri CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.Uri get
CShellFile
CShellFileViewModel CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.CShellFile get set
Referenced by CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.LoadWorkspace().
Tree
TreeViewModel CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.Tree get
Referenced by CShell.Modules.Workspace.Module.GetSelectedFolder(), CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.LoadWorkspace(), and CShell.Modules.Workspace.ViewModels.WorkspaceViewModel.UnloadWorkspace().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Workspace/ViewModels/WorkspaceViewModel.cs