Doc: IGLib EXTENDED: alglib.testgkqunit Class Reference
alglib.testgkqunit Class Reference
Static Public Member Functions
static bool testgkq (bool silent)
static bool testgkq (bool silent)
static bool _pexec_testgkq (bool silent)
Static Private Member Functions
static double mapkind (int k)
static double mapkind (int k)
Member Function Documentation
testgkq() [1/2]
static bool alglib.testgkqunit.testgkq (bool silent) inline static
References alglib.gkq.gkqgenerategaussjacobi(), alglib.gkq.gkqgenerategausslegendre(), alglib.gkq.gkqlegendrecalc(), alglib.gkq.gkqlegendretbl(), alglib.gq.gqgenerategaussjacobi(), alglib.gq.gqgenerategausslegendre(), alglib.math.machineepsilon, and alglib.testgkqunit.mapkind().
Referenced by alglib.testgkqunit._pexec_testgkq(), and _Test.Main().
mapkind() [1/2]
static double alglib.testgkqunit.mapkind (int k) inline static private
Referenced by alglib.testgkqunit.testgkq().
testgkq() [2/2]
static bool alglib.testgkqunit.testgkq (bool silent) inline static
References alglib.gkq.gkqgenerategaussjacobi(), alglib.gkq.gkqgenerategausslegendre(), alglib.gkq.gkqlegendrecalc(), alglib.gkq.gkqlegendretbl(), alglib.gq.gqgenerategaussjacobi(), alglib.gq.gqgenerategausslegendre(), alglib.math.machineepsilon, and alglib.testgkqunit.mapkind().
_pexec_testgkq()
static bool alglib.testgkqunit._pexec_testgkq (bool silent) inline static
References alglib.testgkqunit.testgkq().
Referenced by _Test.Main().
mapkind() [2/2]
static double alglib.testgkqunit.mapkind (int k) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs