Doc: IGLib EXTENDED: IG.Test.ProgramTestIgorIT Class Reference
IG.Test.ProgramTestIgorIT Class Reference
Class containing main method for Igor Grešovnik's optimization shell.
Classes
class ExtShellApp
Application class for the current application.
Public Member Functions
ProgramTestIgorIT ()
override void AddDefaultAssemblies ()
Adds assemblies to be automatically referenced by loaded scripts.
override void AplicationMain (string[] args)
Default main method for the current application.
override void TestMain (string[] args)
Runs tests from scripts according to hard-coded settings.
Public Member Functions inherited from IG.Lib.ApplicationCommandlineBase
ApplicationCommandlineBase ()
Constructor.
Static Public Member Functions
static void Main (string[] args)
Entry point of the application.
Protected Member Functions
override CommandLineApplicationInterpreter CreateInterpreter ()
Creates and returns application's command-line interpreter.
Protected Member Functions inherited from IG.Lib.ApplicationCommandlineBase
virtual void SetUserName (string userName)
Sets name of the current user. This method is provided to enable testing code under another user name. Setting to null anihilates effect of previous calls.
int GetScriptNumArguments ()
Returns the number of script run method's arguments (i.e. arguments that are stored in DirectArguments and InterpreterArguments). If there are different numbers of
virtual void SetScriptNumArguments (int numArguments)
Sets the number of script run method's arguments to the specified number. Reallocates argument arrays if necessary.
virtual void SetScriptArgument (int whichArgument, string argumentValue)
Sets the specified script argument; updates array of arguments for running script directly as well as arguments for running script through interpreter.
virtual string GetScriptArgument (int whichArgument)
Gets the specified string arguments, as it is currently set.
Additional Inherited Members
Public Attributes inherited from IG.Lib.ApplicationCommandlineBase
string OptDir
Optimization directory that contains data and message files of optimization server.
Protected Attributes inherited from IG.Lib.ApplicationCommandlineBase
string ConstRunInteractive = "Interactive"
Interpreter command for running in interactive mode.
string ConstRunScript = "RunScript"
Interpreter command for running dynamic scripts.
string ScriptLocation = null
Location of the script to be loaded.
string ScriptGroupChoice
Main selector for script that is run.
string _scriptChoice
Type _scriptType
string ScriptAction
Selector for script action.
string[] DirectArguments = null
Script arguments used when script is run directly by creating a script object.
string[] InterpreterArguments = null
Interpreter arguments used when script is run through interpreter.
string DefaultActiveDir
Default active directory. The current directory will be set to this directory.
ILoadableScript _scriptToRun
bool RunThroughInterpreter = false
Whether script is loaded and run through interpreter (alternative is direct construction of script class).
string _userNameLowerCase = null
CommandLineApplicationInterpreter TestInterpreter
Application interpreter for running test scripts.
Static Protected Attributes inherited from IG.Lib.ApplicationCommandlineBase
const string ConstScriptTests = "ScriptTests"
Selecting constant fot TEST script.
const string ConstScriptCustomApp = "ScriptCustomApp"
Selecting constant fot CUSTOM script.
const string ConstInteractive = "Interactive"
Selecting constant for interactive run.
Properties inherited from IG.Lib.ApplicationCommandlineBase
string ScriptChoice [get, set]
Name of the selected script type that is run.
Type ScriptType [get, set]
Selected type of the script to be run.
ILoadableScript ScriptToRun [get, set]
Script to be run.
virtual string UserNameLowerCase [get]
Gets name of the current user with all letters converted to lower case (in order to avoid ambiguities).
virtual bool IsUserIgor [get]
Returns true if the current user logged on the computer is Igor, or false otherwise.
virtual bool IsUserTadej [get]
Returns true if the current user logged on the computer is Tadej, or false otherwise.
Detailed Description
Class containing main method for Igor Grešovnik's optimization shell.
Standard scheme for IGLib-based test applications has been adopted in December 2011.
$A Igor xx Nov09 Dec11;
Constructor & Destructor Documentation
ProgramTestIgorIT()
IG.Test.ProgramTestIgorIT.ProgramTestIgorIT () inline
References IG.Lib.ApplicationCommandlineBase.DefaultActiveDir, and IG.Lib.ApplicationCommandlineBase.OptDir.
Referenced by IG.Test.ProgramTestIgorIT.Main().
Member Function Documentation
Main()
static void IG.Test.ProgramTestIgorIT.Main (string[] args) inline static
Entry point of the application.
Parameters
AppArguments Application arguments.
References IG.Test.ProgramTestIgorIT.ExtShellApp.Init(), and IG.Test.ProgramTestIgorIT.ProgramTestIgorIT().
CreateInterpreter()
override CommandLineApplicationInterpreter IG.Test.ProgramTestIgorIT.CreateInterpreter () inline protected virtual
Creates and returns application's command-line interpreter.
Implements IG.Lib.ApplicationCommandlineBase.
References IG.Lib.CommandLineApplicationInterpreter.RegisterSystemPriorityUpdating().
AddDefaultAssemblies()
override void IG.Test.ProgramTestIgorIT.AddDefaultAssemblies () inline virtual
Adds assemblies to be automatically referenced by loaded scripts.
Reimplemented from IG.Lib.ApplicationCommandlineBase.
References IG.Lib.Module.AddDefaultAssembliesExtShellApp().
AplicationMain()
override void IG.Test.ProgramTestIgorIT.AplicationMain (string[] args) inline virtual
Default main method for the current application.
Parameters
AppArguments Command-line argumets passed when the application is run.
Standard scheme for IGLib-based test applications has been adopted in December 2011.
$A Igor xx Nov09 Dec11;
Reimplemented from IG.Lib.ApplicationCommandlineBase.
References IG.Lib.CommandLineApplicationInterpreter.AsyncIsAllCompleted(), IG.Lib.CommandLineApplicationInterpreter.AsyncWaitAll(), IG.Lib.Util.OutputLevel, and IG.Lib.ApplicationCommandlineBase.TestInterpreter.
TestMain()
override void IG.Test.ProgramTestIgorIT.TestMain (string[] args) inline virtual
Runs tests from scripts according to hard-coded settings.
Standard form of test applications for functionality based on IGLib.
Parameters
AppArguments Command-line argumets passed when the application is run.
Standard scheme for IGLib-based test applications has been adopted in December 2011.
$A Igor xx Nov09 Dec11;
Implements IG.Lib.ApplicationCommandlineBase.
References IG.Script.ScriptExtTemplate.ConstAnotherTest, IG.Script.LoadableScriptShellNeuralITOriginalBase.ConstCollectParallel, IG.Script.LoadableScriptShellNeuralITOriginalBase.ConstCustom, IG.Lib.LoadableScriptBase.ConstDefaultHelp, IG.Lib.LoadableScriptBase.ConstDefaultTestScrip, IG.Script.ScriptExtFormats.ConstFormat, IG.Script.ScriptExtExamples.ConstGraphics3d, IG.Lib.LoadableScriptBase.ConstHelpDefaultUniversal, IG.Lib.ApplicationCommandlineBase.ConstInteractive, IG.Script.ScriptExtFormats.ConstMyTest, IG.Script.ScriptExtTemplate.ConstMyTest, IG.Script.ScriptExtNumeric.ConstParallelJobs, IG.Script.ScriptGraphics3DBase.ConstPlot3d, IG.Script.LoadableScriptShellNeuralIT.ConstPlotNetworkCenteredPoint, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstPlotNetworkResponseOnLine, IG.Script.LoadableScriptShellNeuralIT.ConstPlotNetworkResponseOnLineAll, IG.Script.LoadableScriptShellNeuralIT.ConstPlotVerificationResponse, IG.Script.ScriptExtExamples.ConstPointClouds, IG.Script.S_13_5_Convection.ConstRunConvectionSimulator, IG.Script.LoadableScriptShellNeuralITOriginalBase.ConstRunParallel, IG.Lib.ApplicationCommandlineBase.ConstRunScript, IG.Lib.ApplicationCommandlineBase.ConstScriptCustomApp, IG.Lib.ApplicationCommandlineBase.ConstScriptTests, IG.Script.LoadableScriptShellNeuralIT.ConstSensitivity, IG.Script.ScriptGraphics3DBase.ConstSurface3d, IG.Script.LoadableScriptShellNeuralITOriginalBase.ConstTest, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstTestNetworkResponse, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstTestPlotNetworkResponse, IG.Script.S_12_03_paper_gk.ConstTestSimulator, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstTrainNetwork, IG.Script.ScriptGraphics3DBase.ConstVtkTest, IG.Lib.ApplicationCommandlineBase.DefaultActiveDir, IG.Lib.LoadableScriptBase.DefaultOutputLevel, IG.Lib.ApplicationCommandlineBase.DirectArguments, IG.Lib.RealFunctionLoader.Example(), IG.Lib.ApplicationCommandlineBase.GetScriptArgument(), IG.Lib.ILoadableScript.InitializationArguments, IG.Lib.ApplicationCommandlineBase.InterpreterArguments, IG.Lib.ApplicationCommandlineBase.IsUserIgor, IG.Lib.ApplicationCommandlineBase.IsUserTadej, IG.Lib.CommandLineApplicationInterpreter.MainThread, IG.Lib.ApplicationCommandlineBase.OptDir, IG.Script.ScriptGraphics3DBase.Plot3dContourPlot, IG.Lib.ILoadableScript.Run(), IG.Lib.CommandLineApplicationInterpreter.Run(), IG.Lib.ApplicationCommandlineBase.RunThroughInterpreter, IG.Lib.ApplicationCommandlineBase.ScriptAction, IG.Lib.ApplicationCommandlineBase.ScriptChoice, IG.Lib.ApplicationCommandlineBase.ScriptGroupChoice, IG.Lib.ApplicationCommandlineBase.ScriptLocation, IG.Lib.ApplicationCommandlineBase.ScriptToRun, IG.Lib.ApplicationCommandlineBase.ScriptType, IG.Lib.ApplicationCommandlineBase.SetScriptArgument(), IG.Lib.ApplicationCommandlineBase.SetScriptNumArguments(), IG.Lib.UtilSystem.StandardizeDirectoryPath(), IG.Script.ScriptGraphics3DBase.surfaceKleinBottle, IG.Script.ScriptGraphics3DBase.surfaceSnailShell, IG.Script.ScriptGraphics3DBase.surfaceTwoToruses, IG.Lib.ApplicationCommandlineBase.TestInterpreter, IG.Lib.ApplicationCommandlineBase.UserNameLowerCase, IG.Script.ScriptGraphics3DBase.VtkCellGridContours, and IG.Script.ScriptGraphics3DBase.VtkStructuredGrid.
The documentation for this class was generated from the following file:
shelldev/extensions/ExtShellIT/ProgramExtShellIT.cs