Doc: IGLib EXTENDED: NUnit.Framework.TestAttribute Class Reference
NUnit.Framework.TestAttribute Class Reference
Adding this attribute to a method within a
See also
TestFixtureAttribute
class makes the method callable from the NUnit test runner. There is a property called Description which is optional which you can provide a more detailed test description. This class cannot be inherited.
Public Member Functions
void ApplyToTest (Test test)
Modifies a test by adding a description, if not already set.
TestMethod BuildFrom (IMethodInfo method, Test suite)
Construct a TestMethod from a given method.
Public Member Functions inherited from NUnit.Framework.NUnitAttribute
NUnitAttribute ()
Default constructor
Properties
string Description [get, set]
Descriptive text for this test
string Author [get, set]
The author of this test
Type TestOf [get, set]
The type that this test is testing
object ExpectedResult [get, set]
Gets or sets the expected result.
bool HasExpectedResult [get, private set]
Returns true if an expected result has been set
Private Attributes
object _expectedResult
readonly NUnitTestCaseBuilder _builder = new NUnitTestCaseBuilder()
Detailed Description
Adding this attribute to a method within a
See also
TestFixtureAttribute
class makes the method callable from the NUnit test runner. There is a property called Description which is optional which you can provide a more detailed test description. This class cannot be inherited.
[TestFixture] public class Fixture { [Test] public void MethodToTest() {}
[Test(Description = "more detailed description")] public void TestDescriptionMethod() {} }
Member Function Documentation
ApplyToTest()
void NUnit.Framework.TestAttribute.ApplyToTest (Test test) inline
Modifies a test by adding a description, if not already set.
Parameters
test The test to modify
Implements NUnit.Framework.Interfaces.IApplyToTest.
References NUnit.Framework.TestAttribute.Author, NUnit.Framework.Internal.PropertyNames.Author, NUnit.Framework.Interfaces.IPropertyBag.ContainsKey(), NUnit.Framework.TestAttribute.Description, NUnit.Framework.Internal.PropertyNames.Description, NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Interfaces.IPropertyBag.Set(), NUnit.Framework.TestAttribute.TestOf, and NUnit.Framework.Internal.PropertyNames.TestOf.
BuildFrom()
TestMethod NUnit.Framework.TestAttribute.BuildFrom (IMethodInfo method, Test suite) inline
Construct a TestMethod from a given method.
Parameters
method The method for which a test is to be constructed.
suite The suite to which the test will be added.
Returns
A TestMethod
Implements NUnit.Framework.Interfaces.ISimpleTestBuilder.
References NUnit.Framework.Internal.TestCaseParameters.ExpectedResult, NUnit.Framework.TestAttribute.ExpectedResult, and NUnit.Framework.TestAttribute.HasExpectedResult.
Referenced by NUnit.Framework.Attributes.TestMethodBuilderTests.TestAttribute_NoArgs_Runnable(), and NUnit.Framework.Attributes.TestMethodBuilderTests.TestAttribute_WithArgs_NotRunnable().
Member Data Documentation
_expectedResult
object NUnit.Framework.TestAttribute._expectedResult private
_builder
readonly NUnitTestCaseBuilder NUnit.Framework.TestAttribute._builder = new NUnitTestCaseBuilder() private
Property Documentation
Description
string NUnit.Framework.TestAttribute.Description get set
Descriptive text for this test
Referenced by NUnit.Framework.TestAttribute.ApplyToTest().
Author
string NUnit.Framework.TestAttribute.Author get set
The author of this test
Referenced by NUnit.Framework.TestAttribute.ApplyToTest().
TestOf
Type NUnit.Framework.TestAttribute.TestOf get set
The type that this test is testing
Referenced by NUnit.Framework.TestAttribute.ApplyToTest().
ExpectedResult
object NUnit.Framework.TestAttribute.ExpectedResult get set
Gets or sets the expected result.
The result.
Referenced by NUnit.Framework.TestAttribute.BuildFrom().
HasExpectedResult
bool NUnit.Framework.TestAttribute.HasExpectedResult get private set
Returns true if an expected result has been set
Referenced by NUnit.Framework.TestAttribute.BuildFrom().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Attributes/TestAttribute.cs