Doc: IGLib EXTENDED: NUnit.Framework.Constraints.CollectionOrderedConstraint Class Reference
NUnit.Framework.Constraints.CollectionOrderedConstraint Class Reference
CollectionOrderedConstraint is used to test whether a collection is ordered.
Public Member Functions
CollectionOrderedConstraint Using (IComparer comparer)
Modifies the constraint to use an IComparer and returns self.
CollectionOrderedConstraint Using< T > (IComparer< T > comparer)
Modifies the constraint to use an IComparer<T> and returns self.
CollectionOrderedConstraint Using< T > (Comparison< T > comparer)
Modifies the constraint to use a Comparison<T> and returns self.
CollectionOrderedConstraint By (string propertyName)
Modifies the constraint to test ordering by the value of a specified property and returns self.
Public Member Functions inherited from NUnit.Framework.Constraints.CollectionConstraint
override ConstraintResult ApplyTo< TActual > (TActual actual)
Test whether the constraint is satisfied by a given value
Public Member Functions inherited from NUnit.Framework.Constraints.Constraint
virtual ConstraintResult ApplyTo< TActual > (ActualValueDelegate< TActual > del)
Applies the constraint to an ActualValueDelegate that returns the value to be tested. The default implementation simply evaluates the delegate but derived classes may override it to provide for delayed processing.
virtual ConstraintResult ApplyTo< TActual > (ref TActual actual)
Test whether the constraint is satisfied by a given reference. The default implementation simply dereferences the value but derived classes may override it to provide for delayed processing.
override string ToString ()
Default override of ToString returns the constraint DisplayName followed by any arguments within angle brackets.
DelayedConstraint After (int delayInMilliseconds)
Returns a DelayedConstraint with the specified delay time.
DelayedConstraint After (int delayInMilliseconds, int pollingInterval)
Returns a DelayedConstraint with the specified delay time and polling interval.
Protected Member Functions
override bool Matches (IEnumerable actual)
Test whether the collection is ordered
override string GetStringRepresentation ()
Returns the string representation of the constraint.
Protected Member Functions inherited from NUnit.Framework.Constraints.CollectionConstraint
CollectionConstraint ()
Construct an empty CollectionConstraint
CollectionConstraint (object arg)
Construct a CollectionConstraint
Protected Member Functions inherited from NUnit.Framework.Constraints.Constraint
Constraint (params object[] args)
Construct a constraint with optional arguments
Properties
CollectionOrderedConstraint Descending [get]
override string? Description [get]
The Description of what this constraint tests, for use in messages and in the ConstraintResult.
Properties inherited from NUnit.Framework.Constraints.Constraint
string DisplayName [get, protected set]
The display name of this Constraint for use by ToString(). The default value is the name of the constraint with trailing "Constraint" removed. Derived classes may set this to another name in their constructors.
virtual string Description [get, protected set]
The Description of what this constraint tests, for use in messages and in the ConstraintResult.
object[] Arguments [get, private set]
Arguments provided to this Constraint, for use in formatting the description.
ConstraintBuilder Builder [get, set]
The ConstraintBuilder holding this constraint
ConstraintExpression And [get]
Returns a ConstraintExpression by appending And to the current constraint.
ConstraintExpression With [get]
Returns a ConstraintExpression by appending And to the current constraint.
ConstraintExpression Or [get]
Returns a ConstraintExpression by appending Or to the current constraint.
Properties inherited from NUnit.Framework.Constraints.IConstraint
string DisplayName [get]
The display name of this Constraint for use by ToString().
string Description [get]
The Description of what this constraint tests, for use in messages and in the ConstraintResult.
object[] Arguments [get]
Arguments provided to this Constraint, for use in formatting the description.
ConstraintBuilder Builder [get, set]
The ConstraintBuilder holding this constraint
Private Attributes
ComparisonAdapter comparer = ComparisonAdapter.Default
string comparerName
string propertyName
bool descending
Additional Inherited Members
Static Public Member Functions inherited from NUnit.Framework.Constraints.Constraint
static Constraint operator& (Constraint left, Constraint right)
This operator creates a constraint that is satisfied only if both argument constraints are satisfied.
static Constraint operator| (Constraint left, Constraint right)
This operator creates a constraint that is satisfied if either of the argument constraints is satisfied.
static Constraint operator! (Constraint constraint)
This operator creates a constraint that is satisfied if the argument constraint is not satisfied.
Static Protected Member Functions inherited from NUnit.Framework.Constraints.CollectionConstraint
static bool IsEmpty (IEnumerable enumerable)
Determines whether the specified enumerable is empty.
Detailed Description
CollectionOrderedConstraint is used to test whether a collection is ordered.
Member Function Documentation
Using()
CollectionOrderedConstraint NUnit.Framework.Constraints.CollectionOrderedConstraint.Using (IComparer comparer) inline
Modifies the constraint to use an IComparer and returns self.
References NUnit.Framework.Constraints.CollectionOrderedConstraint.comparer, and NUnit.Framework.Constraints.ComparisonAdapter.For().
Referenced by NUnit.Framework.CollectionAssert.IsOrdered(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer_Descending.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer.SetUp(), and NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer_Descending.SetUp().
Using< T >() [1/2]
CollectionOrderedConstraint NUnit.Framework.Constraints.CollectionOrderedConstraint.Using< T > (IComparer< T > comparer) inline
Modifies the constraint to use an IComparer<T> and returns self.
References NUnit.Framework.Constraints.CollectionOrderedConstraint.comparer, and NUnit.Framework.Constraints.ComparisonAdapter.For().
Using< T >() [2/2]
CollectionOrderedConstraint NUnit.Framework.Constraints.CollectionOrderedConstraint.Using< T > (Comparison< T > comparer) inline
Modifies the constraint to use a Comparison<T> and returns self.
References NUnit.Framework.Constraints.CollectionOrderedConstraint.comparer, and NUnit.Framework.Constraints.ComparisonAdapter.For().
By()
CollectionOrderedConstraint NUnit.Framework.Constraints.CollectionOrderedConstraint.By (string propertyName) inline
Modifies the constraint to test ordering by the value of a specified property and returns self.
References NUnit.Framework.Constraints.CollectionOrderedConstraint.propertyName.
Referenced by NUnit.Framework.Syntax.CollectionOrderedByTest.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Descending.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer.SetUp(), and NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer_Descending.SetUp().
Matches()
override bool NUnit.Framework.Constraints.CollectionOrderedConstraint.Matches (IEnumerable actual) inline protected virtual
Test whether the collection is ordered
Parameters
actual
Returns
Implements NUnit.Framework.Constraints.CollectionConstraint.
References NUnit.Framework.Constraints.ComparisonAdapter.Compare(), NUnit.Framework.Constraints.CollectionOrderedConstraint.comparer, NUnit.Framework.Constraints.CollectionOrderedConstraint.descending, and NUnit.Framework.Constraints.CollectionOrderedConstraint.propertyName.
GetStringRepresentation()
override string NUnit.Framework.Constraints.CollectionOrderedConstraint.GetStringRepresentation () inline protected virtual
Returns the string representation of the constraint.
Returns
Reimplemented from NUnit.Framework.Constraints.Constraint.
References NUnit.Framework.Constraints.CollectionOrderedConstraint.comparerName, NUnit.Framework.Constraints.CollectionOrderedConstraint.descending, and NUnit.Framework.Constraints.CollectionOrderedConstraint.propertyName.
Member Data Documentation
comparer
ComparisonAdapter NUnit.Framework.Constraints.CollectionOrderedConstraint.comparer = ComparisonAdapter.Default private
Referenced by NUnit.Framework.Constraints.CollectionOrderedConstraint.Matches(), NUnit.Framework.Constraints.CollectionOrderedConstraint.Using(), and NUnit.Framework.Constraints.CollectionOrderedConstraint.Using< T >().
comparerName
string NUnit.Framework.Constraints.CollectionOrderedConstraint.comparerName private
Referenced by NUnit.Framework.Constraints.CollectionOrderedConstraint.GetStringRepresentation().
propertyName
string NUnit.Framework.Constraints.CollectionOrderedConstraint.propertyName private
Referenced by NUnit.Framework.Constraints.CollectionOrderedConstraint.By(), NUnit.Framework.Constraints.CollectionOrderedConstraint.GetStringRepresentation(), and NUnit.Framework.Constraints.CollectionOrderedConstraint.Matches().
descending
bool NUnit.Framework.Constraints.CollectionOrderedConstraint.descending private
Referenced by NUnit.Framework.Constraints.CollectionOrderedConstraint.GetStringRepresentation(), and NUnit.Framework.Constraints.CollectionOrderedConstraint.Matches().
Property Documentation
Descending
CollectionOrderedConstraint NUnit.Framework.Constraints.CollectionOrderedConstraint.Descending get
Referenced by NUnit.Framework.Syntax.CollectionOrderedTest_Descending.SetUp(), NUnit.Framework.Syntax.CollectionOrderedTest_Comparer_Descending.SetUp(), NUnit.Framework.Syntax.CollectionOrderedByTest_Descending.SetUp(), and NUnit.Framework.Syntax.CollectionOrderedByTest_Comparer_Descending.SetUp().
Description
override string? NUnit.Framework.Constraints.CollectionOrderedConstraint.Description get
The Description of what this constraint tests, for use in messages and in the ConstraintResult.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Constraints/CollectionOrderedConstraint.cs