Doc: IGLib EXTENDED: NUnitLite.Tests.TeamCityEventListenerTests Class Reference
NUnitLite.Tests.TeamCityEventListenerTests Class Reference
Public Member Functions
void CreateListener ()
void TestSuiteStarted ()
void TestSuiteFinished ()
void TestStarted ()
void TestFinished_Passed ()
void TestFinished_Inconclusive ()
void TestFinished_Ignored ()
void TestFinished_Failed ()
Private Member Functions
void FakeTestMethod ()
Private Attributes
TeamCityEventListener _teamCity
StringBuilder _output
Static Private Attributes
static readonly string NL = NUnit.Env.NewLine
Member Function Documentation
CreateListener()
void NUnitLite.Tests.TeamCityEventListenerTests.CreateListener () inline
References NUnitLite.Tests.TeamCityEventListenerTests._output, and NUnitLite.Tests.TeamCityEventListenerTests._teamCity.
TestSuiteStarted()
void NUnitLite.Tests.TeamCityEventListenerTests.TestSuiteStarted () inline
References NUnitLite.Tests.TeamCityEventListenerTests._output, NUnitLite.Tests.TeamCityEventListenerTests._teamCity, NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.TeamCityEventListenerTests.NL, NUnitLite.TeamCityEventListener.TestStarted(), and NUnit.Framework.Assert.That().
TestSuiteFinished()
void NUnitLite.Tests.TeamCityEventListenerTests.TestSuiteFinished () inline
References NUnitLite.Tests.TeamCityEventListenerTests._output, NUnitLite.Tests.TeamCityEventListenerTests._teamCity, NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.TeamCityEventListenerTests.NL, NUnitLite.TeamCityEventListener.TestFinished(), and NUnit.Framework.Assert.That().
TestStarted()
void NUnitLite.Tests.TeamCityEventListenerTests.TestStarted () inline
References NUnitLite.Tests.TeamCityEventListenerTests._output, NUnitLite.Tests.TeamCityEventListenerTests._teamCity, NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.Fakes.GetTestMethod(), NUnitLite.Tests.TeamCityEventListenerTests.NL, NUnitLite.TeamCityEventListener.TestStarted(), and NUnit.Framework.Assert.That().
TestFinished_Passed()
void NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Passed () inline
References NUnitLite.Tests.TeamCityEventListenerTests._output, NUnitLite.Tests.TeamCityEventListenerTests._teamCity, NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.Fakes.GetTestMethod(), NUnit.Framework.Internal.TestMethod.MakeTestResult(), NUnitLite.Tests.TeamCityEventListenerTests.NL, NUnit.Framework.Internal.TestResult.SetResult(), NUnit.Framework.Interfaces.ResultState.Success, NUnitLite.TeamCityEventListener.TestFinished(), and NUnit.Framework.Assert.That().
TestFinished_Inconclusive()
void NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Inconclusive () inline
References NUnitLite.Tests.TeamCityEventListenerTests._output, NUnitLite.Tests.TeamCityEventListenerTests._teamCity, NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.Fakes.GetTestMethod(), NUnit.Framework.Interfaces.ResultState.Inconclusive, NUnit.Framework.Internal.TestMethod.MakeTestResult(), NUnitLite.Tests.TeamCityEventListenerTests.NL, NUnit.Framework.Internal.TestResult.SetResult(), NUnitLite.TeamCityEventListener.TestFinished(), and NUnit.Framework.Assert.That().
TestFinished_Ignored()
void NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Ignored () inline
References NUnitLite.Tests.TeamCityEventListenerTests._output, NUnitLite.Tests.TeamCityEventListenerTests._teamCity, NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.Fakes.GetTestMethod(), NUnit.Framework.Interfaces.ResultState.Ignored, NUnit.Framework.Internal.TestMethod.MakeTestResult(), NUnitLite.Tests.TeamCityEventListenerTests.NL, NUnit.Framework.Internal.TestResult.SetResult(), NUnitLite.TeamCityEventListener.TestFinished(), and NUnit.Framework.Assert.That().
TestFinished_Failed()
void NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Failed () inline
References NUnitLite.Tests.TeamCityEventListenerTests._output, NUnitLite.Tests.TeamCityEventListenerTests._teamCity, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.Failure, NUnit.TestUtilities.Fakes.GetTestMethod(), NUnit.Framework.Internal.TestMethod.MakeTestResult(), NUnitLite.Tests.TeamCityEventListenerTests.NL, NUnit.Framework.Internal.TestResult.SetResult(), NUnitLite.TeamCityEventListener.TestFinished(), and NUnit.Framework.Assert.That().
FakeTestMethod()
void NUnitLite.Tests.TeamCityEventListenerTests.FakeTestMethod () inline private
Member Data Documentation
_teamCity
TeamCityEventListener NUnitLite.Tests.TeamCityEventListenerTests._teamCity private
Referenced by NUnitLite.Tests.TeamCityEventListenerTests.CreateListener(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Failed(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Ignored(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Inconclusive(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Passed(), NUnitLite.Tests.TeamCityEventListenerTests.TestStarted(), NUnitLite.Tests.TeamCityEventListenerTests.TestSuiteFinished(), and NUnitLite.Tests.TeamCityEventListenerTests.TestSuiteStarted().
_output
StringBuilder NUnitLite.Tests.TeamCityEventListenerTests._output private
Referenced by NUnitLite.Tests.TeamCityEventListenerTests.CreateListener(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Failed(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Ignored(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Inconclusive(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Passed(), NUnitLite.Tests.TeamCityEventListenerTests.TestStarted(), NUnitLite.Tests.TeamCityEventListenerTests.TestSuiteFinished(), and NUnitLite.Tests.TeamCityEventListenerTests.TestSuiteStarted().
NL
readonly string NUnitLite.Tests.TeamCityEventListenerTests.NL = NUnit.Env.NewLine static private
Referenced by NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Failed(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Ignored(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Inconclusive(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Passed(), NUnitLite.Tests.TeamCityEventListenerTests.TestStarted(), NUnitLite.Tests.TeamCityEventListenerTests.TestSuiteFinished(), and NUnitLite.Tests.TeamCityEventListenerTests.TestSuiteStarted().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/nunitlite.tests/TeamCityEventListenerTests.cs