Doc: IGLib EXTENDED: IG.Neural.NeuralNetworks Class Reference
IG.Neural.NeuralNetworks Class Reference
Static Public Member Functions
static INeuralApproximator TrainNetwork (SampledDataSet trainingData, SampledDataSet verificationData)
Training neural network in Aforge of NeuronDotNet
static INeuralApproximator Example3D (int inputLength, int outputLength, ref SampledDataSet trainingData, int nnType)
static void Approximate (INeuralApproximator Approximator, SampledDataSet verificationData, ref SampledDataSet approximationData)
Approximate data
static SampledDataSet GenerateSguareSet (int numTrainingSet)
static SampledDataSet CopyFromCordinates3D (IVector[][] functionCoordinates)
Copy data from NeuralTrainingSet to vector table
static IVector[][] CopyToCoordinates3D (int xNumSteps, int yNumSteps, SampledDataSet trainingData)
Properties
int MaxEpoch [get, set]
int EpochBundle [get, set]
double RMS [get, set]
double LearningRate [get, set]
double Momentum [get, set]
int HiddenNeuron1L [get, set]
int HiddenNeuron2L [get, set]
double InputSafetyFactor [get, set]
double OutputSafetyFactor [get, set]
bool BreakTraining [get, set]
Static Private Member Functions
static void CalculateError (IBoundingBox bounds, IVector[] exactOutputValues, IVector[] approximatedOutputValues, ref double maxError, ref double averageError)
Static Private Attributes
static int _maxEpoch
static int _epochBundle
static double _rms
static double _learningRate
static double _momentum
static int _hiddenNeuron1L
static int _hiddenNeuron2L
static double _inputSafetyFactor
static double _outputSafetyFactor
static bool _breakTraining = false
Member Function Documentation
TrainNetwork()
static INeuralApproximator IG.Neural.NeuralNetworks.TrainNetwork (SampledDataSet trainingData, SampledDataSet verificationData) inline static
Training neural network in Aforge of NeuronDotNet
Parameters
inputLength Number of input parameters.
outputLength Number of output parameters.
trainingData
nnType 1-NeuronDotNet; 2-Aforge
Returns
References IG.Neural.NeuralNetworks._epochBundle, IG.Neural.NeuralNetworks._hiddenNeuron1L, IG.Neural.NeuralNetworks._hiddenNeuron2L, IG.Neural.NeuralNetworks._inputSafetyFactor, IG.Neural.NeuralNetworks._learningRate, IG.Neural.NeuralNetworks._maxEpoch, IG.Neural.NeuralNetworks._momentum, IG.Neural.NeuralNetworks._outputSafetyFactor, IG.Neural.NeuralNetworks._rms, IG.Num.NeuralApproximatorBase.EpochsInBundle, IG.Num.NeuralApproximatorBase.InputBoundsSafetyFactor, IG.Num.SampledDataSet.InputLength, IG.Num.NeuralApproximatorBase.InputLength, IG.Num.NeuralApproximatorBase.InputNeuronsRange, IG.Num.NeuralApproximatorBase.LearningRate, IG.Num.SampledDataSet.Length, IG.Num.VectorApproximatorBase.Lock, IG.Num.NeuralApproximatorBase.MaxEpochs, IG.Num.NeuralApproximatorBase.Momentum, IG.Num.NeuralApproximatorBase.MultipleNetworks, IG.Num.NeuralApproximatorBase.OutputBoundsSafetyFactor, IG.Num.SampledDataSet.OutputLength, IG.Num.NeuralApproximatorBase.OutputLength, IG.Num.NeuralApproximatorBase.OutputLevel, IG.Num.NeuralApproximatorBase.OutputNeuronsRange, IG.Num.IBoundingBox.Reset(), IG.Num.NeuralApproximatorBase.SaveConvergenceRms, IG.Num.NeuralApproximatorBase.SetHiddenLayers(), IG.Num.NeuralApproximatorBase.SetTrainingAndVerificationData(), IG.Num.NeuralApproximatorBase.SigmoidAlphaValue, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Lib.StopWatch1.Time, IG.Num.NeuralApproximatorBase.ToleranceRms, IG.Num.NeuralApproximatorBase.ToString(), IG.Num.NeuralApproximatorBase.TrainingData, IG.Num.NeuralApproximatorBase.TrainNetwork(), and IG.Num.IBoundingBox.UpdateAll().
Referenced by IG.Neural.Applications.DemoNeuralOld.backgroundWorker1D_DoWork(), IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_DoWork(), IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_DoWork(), IG.Neural.Applications.DemoNeuralOld.backgroundWorker2D_DoWork(), and IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click().
Example3D()
static INeuralApproximator IG.Neural.NeuralNetworks.Example3D (int inputLength, int outputLength, ref SampledDataSet trainingData, int nnType) inline static
References IG.Num.NeuralApproximatorBase.CalculateOutput(), IG.Lib.SortedUniqueItemList< Type >.Contains(), IG.Lib.IndexList.CreateRandom(), IG.Num.NeuralApproximatorBase.EpochsInBundle, IG.Neural.NeuralNetworks.GenerateSguareSet(), IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.NeuralApproximatorBase.InputBoundsSafetyFactor, IG.Num.NeuralApproximatorBase.InputLength, IG.Num.NeuralApproximatorBase.InputNeuronsRange, IG.Num.NeuralApproximatorBase.LearningRate, IG.Num.VectorApproximatorBase.Lock, IG.Num.NeuralApproximatorBase.MaxEpochs, IG.Num.NeuralApproximatorBase.Momentum, IG.Num.NeuralApproximatorBase.MultipleNetworks, IG.Num.NeuralApproximatorBase.OutputBoundsSafetyFactor, IG.Num.NeuralApproximatorBase.OutputLength, IG.Num.NeuralApproximatorBase.OutputLevel, IG.Num.NeuralApproximatorBase.OutputNeuronsRange, IG.Num.IBoundingBox.Reset(), IG.Num.NeuralApproximatorBase.SetHiddenLayers(), IG.Num.NeuralApproximatorBase.SigmoidAlphaValue, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Num.VectorBase.Subtract(), IG.Lib.StopWatch1.Time, IG.Num.NeuralApproximatorBase.ToleranceRms, IG.Num.IVector< T >.ToString(), IG.Num.NeuralApproximatorBase.ToString(), IG.Num.NeuralApproximatorBase.TrainingData, IG.Num.NeuralApproximatorBase.TrainNetwork(), IG.Num.IBoundingBox.UpdateAll(), and IG.Num.NeuralApproximatorBase.VerificationIndices.
Referenced by IG.Gr3d.TestVtkGraphic.ExampleNeuralTadej(), and IG.Neural.Forms.Old.FormNeural2DOld.Start().
Approximate()
static void IG.Neural.NeuralNetworks.Approximate (INeuralApproximator Approximator, SampledDataSet verificationData, ref SampledDataSet approximationData) inline static
Approximate data
Parameters
Approximator
verificationData
approximatedOutputValues
References IG.Num.IVectorApproximator.CalculateOutput(), IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputRange(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.Length, IG.Num.IVectorApproximator.OutputLength, IG.Num.SampledDataSet.OutputLength, and IG.Num.INeuralApproximator.TrainingData.
CalculateError()
static void IG.Neural.NeuralNetworks.CalculateError (IBoundingBox bounds, IVector[] exactOutputValues, IVector[] approximatedOutputValues, ref double maxError, ref double averageError) inline static private
References IG.Num.IBoundingBox.GetMax(), IG.Num.IBoundingBox.GetMin(), and IG.Num.IVector< T >.Length.
GenerateSguareSet()
static SampledDataSet IG.Neural.NeuralNetworks.GenerateSguareSet (int numTrainingSet) inline static
References IG.Num.SampledDataSet.AddElement().
Referenced by IG.Neural.NeuralNetworks.Example3D().
CopyFromCordinates3D()
static SampledDataSet IG.Neural.NeuralNetworks.CopyFromCordinates3D (IVector functionCoordinates[][]) inline static
Copy data from NeuralTrainingSet to vector table
Parameters
functionCoordinates
Returns
References IG.Num.SampledDataSet.AddElement(), and IG.Num.IVector< T >.Length.
CopyToCoordinates3D()
static IVector [][] IG.Neural.NeuralNetworks.CopyToCoordinates3D (int xNumSteps, int yNumSteps, SampledDataSet trainingData) inline static
References IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.InputLength, and IG.Num.SampledDataSet.OutputLength.
Member Data Documentation
_maxEpoch
int IG.Neural.NeuralNetworks._maxEpoch static private
Referenced by IG.Neural.NeuralNetworks.TrainNetwork().
_epochBundle
int IG.Neural.NeuralNetworks._epochBundle static private
Referenced by IG.Neural.NeuralNetworks.TrainNetwork().
_rms
double IG.Neural.NeuralNetworks._rms static private
Referenced by IG.Neural.NeuralNetworks.TrainNetwork().
_learningRate
double IG.Neural.NeuralNetworks._learningRate static private
Referenced by IG.Neural.NeuralNetworks.TrainNetwork().
_momentum
double IG.Neural.NeuralNetworks._momentum static private
Referenced by IG.Neural.NeuralNetworks.TrainNetwork().
_hiddenNeuron1L
int IG.Neural.NeuralNetworks._hiddenNeuron1L static private
Referenced by IG.Neural.NeuralNetworks.TrainNetwork().
_hiddenNeuron2L
int IG.Neural.NeuralNetworks._hiddenNeuron2L static private
Referenced by IG.Neural.NeuralNetworks.TrainNetwork().
_inputSafetyFactor
double IG.Neural.NeuralNetworks._inputSafetyFactor static private
Referenced by IG.Neural.NeuralNetworks.TrainNetwork().
_outputSafetyFactor
double IG.Neural.NeuralNetworks._outputSafetyFactor static private
Referenced by IG.Neural.NeuralNetworks.TrainNetwork().
_breakTraining
bool IG.Neural.NeuralNetworks._breakTraining = false static private
Property Documentation
MaxEpoch
int IG.Neural.NeuralNetworks.MaxEpoch get set
Referenced by IG.Neural.Applications.DemoNeuralOld.btStart1D_Click(), IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Applications.DemoNeuralOld.btStart2D_Click(), and IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click().
EpochBundle
int IG.Neural.NeuralNetworks.EpochBundle get set
Referenced by IG.Neural.Applications.DemoNeuralOld.btStart1D_Click(), IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Applications.DemoNeuralOld.btStart2D_Click(), IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), and IG.Neural.Forms.Old.FormNeural2DOld.Start().
RMS
double IG.Neural.NeuralNetworks.RMS get set
Referenced by IG.Neural.Applications.DemoNeuralOld.btStart1D_Click(), IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Applications.DemoNeuralOld.btStart2D_Click(), IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), and IG.Neural.Forms.Old.FormNeural2DOld.Start().
LearningRate
double IG.Neural.NeuralNetworks.LearningRate get set
Referenced by IG.Neural.Applications.DemoNeuralOld.btStart1D_Click(), IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Applications.DemoNeuralOld.btStart2D_Click(), IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), and IG.Neural.Forms.Old.FormNeural2DOld.Start().
Momentum
double IG.Neural.NeuralNetworks.Momentum get set
Referenced by IG.Neural.Applications.DemoNeuralOld.btStart1D_Click(), IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Applications.DemoNeuralOld.btStart2D_Click(), IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), and IG.Neural.Forms.Old.FormNeural2DOld.Start().
HiddenNeuron1L
int IG.Neural.NeuralNetworks.HiddenNeuron1L get set
Referenced by IG.Neural.Applications.DemoNeuralOld.btStart1D_Click(), IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Applications.DemoNeuralOld.btStart2D_Click(), IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), and IG.Neural.Forms.Old.FormNeural2DOld.Start().
HiddenNeuron2L
int IG.Neural.NeuralNetworks.HiddenNeuron2L get set
Referenced by IG.Neural.Applications.DemoNeuralOld.btStart1D_Click(), IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), and IG.Neural.Applications.DemoNeuralOld.btStart2D_Click().
InputSafetyFactor
double IG.Neural.NeuralNetworks.InputSafetyFactor get set
Referenced by IG.Neural.Applications.DemoNeuralOld.btStart1D_Click(), IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Applications.DemoNeuralOld.btStart2D_Click(), IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), and IG.Neural.Forms.Old.FormNeural2DOld.Start().
OutputSafetyFactor
double IG.Neural.NeuralNetworks.OutputSafetyFactor get set
Referenced by IG.Neural.Applications.DemoNeuralOld.btStart1D_Click(), IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), IG.Neural.Forms.NeuralControl2D.btStart2D_Click(), IG.Neural.Applications.DemoNeuralOld.btStart2D_Click(), IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), and IG.Neural.Forms.Old.FormNeural2DOld.Start().
BreakTraining
bool IG.Neural.NeuralNetworks.BreakTraining get set
Referenced by IG.Neural.Applications.DemoNeuralOld.backgroundWorker1D_DoWork(), IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_DoWork(), IG.Neural.Forms.NeuralControl2D.backgroundWorker2D_DoWork(), IG.Neural.Applications.DemoNeuralOld.backgroundWorker2D_DoWork(), IG.Neural.Applications.DemoNeuralOld.btStop1D_Click(), IG.Neural.Forms.NeuralDemo1D.btStop1D_Click(), IG.Neural.Forms.NeuralControl2D.btStop2D_Click(), and IG.Neural.Applications.DemoNeuralOld.btStop2D_Click().
The documentation for this class was generated from the following file:
shelldev/lib/extended/LibShellExt/highlevel_and_testing/Testing_Development/NeuralNetworks.cs