Doc: IGLib EXTENDED: IG.Forms.InputDataDefinitionControl Class Reference
IG.Forms.InputDataDefinitionControl Class Reference
Control for editing input or output data definitions (only one of these two at a time).
Public Member Functions
InputDataDefinitionControl ()
void UpdateInputOrOutput (bool isInput)
Prepares control for processing either input or output data.
DataGridView GetGridControl ()
Returns the DataGridView control that is used for setting values of the input parameters.
string CreateInputElementName (int elementIndex)
Returns a suitable name for input data element with the specified index.
string CreateOutputElementName (int elementIndex)
Returns a suitable name for output data element with the specified index.
InputElementDefinition CreateInputElement (int elementIndex)
Creates and returns a new input data element definition.
OutputElementDefinition CreateOutputElement (int elementIndex)
Creates and returns a new output data element definition.
void CopyGridRowToData (int whichRow)
Copies data from the specified row of the data grid view to data definition object.
void CopyDataToGridRow (int whichRow)
Copies data to the specified row of the data grid view from data definition object DataDefinition.
void CopyDataToGrid ()
Copies data from the DataDefinition object to the internal data grid view control.
void ClearCells ()
Clears contents of all DataGridView cells.
void ClearDataGrid ()
Removes all the data from the DataGridView.
virtual string CreateSummary ()
void ShowContextMenuControl (object sender, MouseEventArgs e)
InputDataDefinitionControl ()
void UpdateInputOrOutput (bool isInput)
Prepares control for processing either input or output data.
DataGridView GetGridControl ()
Returns the DataGridView control that is used for setting values of the input parameters.
string CreateInputElementName (int elementIndex)
Returns a suitable name for input data element with the specified index.
string CreateOutputElementName (int elementIndex)
Returns a suitable name for output data element with the specified index.
InputElementDefinition CreateInputElement (int elementIndex)
Creates and returns a new input data element definition.
OutputElementDefinition CreateOutputElement (int elementIndex)
Creates and returns a new output data element definition.
void CopyGridRowToData (int whichRow)
Copies data from the specified row of the data grid view to data definition object.
void CopyDataToGridRow (int whichRow)
Copies data to the specified row of the data grid view from data definition object DataDefinition.
void CopyDataToGrid ()
Copies data from the DataDefinition object to the internal data grid view control.
void ClearCells ()
Clears contents of all DataGridView cells.
void ClearDataGrid ()
Removes all the data from the DataGridView.
virtual string CreateSummary ()
void ShowContextMenuControl (object sender, MouseEventArgs e)
Protected Member Functions
virtual void InitDataGridProperties ()
Initializes additional properties of the data grid view that were not set in designer.
void OnDefinitionObjectChanged (InputOutputDataDefiniton oldDataDefinition, InputOutputDataDefiniton newDataDefinition)
Raises the DefinitionObjectChanged event. This method should be called preferrably, rather than the event itself.
void OnNumElementsChanged (int oldLength, int newLength)
Raises the NumElementsChanged event. This method should be called preferrably, rather than the event itself.
override void Dispose (bool disposing)
Clean up any resources being used.
virtual void InitDataGridProperties ()
Initializes additional properties of the data grid view that were not set in designer.
void OnDefinitionObjectChanged (InputOutputDataDefiniton oldDataDefinition, InputOutputDataDefiniton newDataDefinition)
Raises the DefinitionObjectChanged event. This method should be called preferrably, rather than the event itself.
void OnNumElementsChanged (int oldLength, int newLength)
Raises the NumElementsChanged event. This method should be called preferrably, rather than the event itself.
void OnDataChanged ()
Raises the ElementDataChanged event. This method should be called preferrably, rather than the event itself.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
int _inputLength
int _outputLength
bool _isInputData = true
Vector _values
Properties
InputOutputDataDefiniton DataDefinition [get, set]
Data about input and output quantities of the manipulated functions or response.
int NumElements [get, protected set]
Number of the corresponding elements in the data definition.
virtual int InputLength [get, set]
Number of input parameters or data elements.
virtual int OutputLength [get, set]
Number of output parameters or data elements.
virtual string Title [get, set]
Text of the title label shown on top left of the form.
virtual bool IsInputData [get, set]
Indicates whether this form is used to edit input (when true) or output (when false) data elements.
bool IsOutputData [get, set]
Indicates whether this form is used to edit input (when false) or output (when true) data elements.
bool IsDimentionChangeAllowed [get, set]
Indicates whetherr user can change dimensions (number of input/output data elements).
bool GridChangeEventsDisabled [get, set]
Flag for disabling events raised when grid data is changed. Default is false.
int ColumnIndexId [get]
Returns column index of the ID field.
int ColumnIndexName [get]
Returns column index of the Name field.
int ColumnIndexMin [get]
Returns column index of the Min field.
int ColumnIndexMax [get]
Returns column index of the Max field.
int ColumnIndexDefault [get]
Returns column index of the Default field.
int ColumnIndexNumPoints [get]
Returns column index of the Num field.
int ColumnIndexTitle [get]
Returns column index of the Title field.
int ColumnIndexDescription [get]
Returns column index of the Description field.
bool UseLegalVariableNames [get, set]
Specifies whether legal variable names (according to rules in programming languages such as C++, C# or Java) should be enforced for naming input and utput elements.
int NumValues [get]
Current number of values, otained form the DataGridView.
string TitleInputData [get, set]
Control's title (displayed as group box text) in case of input data editing.
string TitleOutputData [get, set]
Control's title (displayed as group box text) in case of output data editing.
string TitleWithChangedSign [get]
Actual title that is shown on the top of control, in the lblMainTitle label, includes eventual marks for unsaved changes.
bool HasUnsavedChanges [get, set]
Whether the current function definition has unsaved changes.
Events
EventHandler< ValueChangeEventArgs< InputOutputDataDefiniton > > DefinitionObjectChanged
Occurs when data definition object is changed (i.e., when object reference changes), meaning that whole data definition object is replaced.
EventHandler< IndexChangeEventArgs > NumElementsChanged
Occurs when number of data elements (InputLength or OutputLength, dependent on IsInputData property) is changed.
EventHandler DataChanged
Occurs when some element property is changed.
Private Member Functions
void InputDataDefinitionControl_MouseClick (object sender, MouseEventArgs e)
void dGridInputParam_MouseClick (object sender, MouseEventArgs e)
void btnResetDefault_Click (object sender, EventArgs e)
void btnResetCenter_Click (object sender, EventArgs e)
void resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e)
void resetToCenterToolStripMenuItem_Click (object sender, EventArgs e)
void dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InputDataDefinitionControl_MouseClick (object sender, MouseEventArgs e)
void dGridInputParam_MouseClick (object sender, MouseEventArgs e)
void btnResetDefault_Click (object sender, EventArgs e)
void btnResetCenter_Click (object sender, EventArgs e)
void resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e)
void resetToCenterToolStripMenuItem_Click (object sender, EventArgs e)
void dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
InputOutputDataDefiniton _dataDefinition
string _title = "Input Data"
bool _isDimentionChangeAllowed = true
bool _gridChangeEventsDdisabled = false
int _columnIndexId = -1
int _columnIndexName = -1
int _columnIndexMin = -1
int _columnIndexMax = -1
int _columnIndexDefault = -1
int _columnIndexNumPoints = -1
int _columnIndexTitle = -1
int _columnIndexDescription = -1
bool _useLegalVariableNames = true
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.GroupBox grpOuter
System.Windows.Forms.DataGridView dataGridView1
System.Windows.Forms.Button btnResetDefault
System.Windows.Forms.Button btnResetCenter
System.Windows.Forms.ContextMenuStrip contextMenuControl
System.Windows.Forms.ToolStripMenuItem resetToDefaultToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem resetToCenterToolStripMenuItem
System.Windows.Forms.DataGridViewTextBoxColumn columnId
System.Windows.Forms.DataGridViewTextBoxColumn columnName
System.Windows.Forms.DataGridViewTextBoxColumn columnMin
System.Windows.Forms.DataGridViewTextBoxColumn columnMax
System.Windows.Forms.DataGridViewTextBoxColumn columnDefault
System.Windows.Forms.DataGridViewTextBoxColumn columnNumPoints
System.Windows.Forms.DataGridViewTextBoxColumn columnTitle
System.Windows.Forms.DataGridViewTextBoxColumn columnDescription
string _titleInputData = "Input Data"
string _titleOutputData = "Output Data"
bool _hasUnsavedChanges = false
Detailed Description
Control for editing input or output data definitions (only one of these two at a time).
$A Igor Apr13 Mar16;
Constructor & Destructor Documentation
InputDataDefinitionControl() [1/2]
IG.Forms.InputDataDefinitionControl.InputDataDefinitionControl () inline
References IG.Forms.InputDataDefinitionControl.GridChangeEventsDisabled, IG.Forms.InputDataDefinitionControl.grpOuter, IG.Forms.InputDataDefinitionControl.InitializeComponent(), IG.Forms.InputDataDefinitionControl.IsInputData, IG.Forms.InputDataDefinitionControl.Title, and IG.Forms.InputDataDefinitionControl.UpdateInputOrOutput().
InputDataDefinitionControl() [2/2]
IG.Forms.InputDataDefinitionControl.InputDataDefinitionControl () inline
References IG.Forms.InputDataDefinitionControl.GridChangeEventsDisabled, IG.Forms.InputDataDefinitionControl.grpOuter, IG.Forms.InputDataDefinitionControl.InitializeComponent(), IG.Forms.InputDataDefinitionControl.IsInputData, IG.Forms.InputDataDefinitionControl.Title, and IG.Forms.InputDataDefinitionControl.UpdateInputOrOutput().
Member Function Documentation
UpdateInputOrOutput() [1/2]
void IG.Forms.InputDataDefinitionControl.UpdateInputOrOutput (bool isInput) inline
Prepares control for processing either input or output data.
When calling this method, its body is executed regardles of whether it has been called with the same parameters before. This is different from IsInputData setter which has effect only when value is actually changed.
Parameters
isInput
References IG.Forms.InputDataDefinitionControl.columnDefault, IG.Forms.InputDataDefinitionControl.columnDescription, IG.Forms.InputDataDefinitionControl.columnId, IG.Forms.InputDataDefinitionControl.columnMax, IG.Forms.InputDataDefinitionControl.columnMin, IG.Forms.InputDataDefinitionControl.columnName, IG.Forms.InputDataDefinitionControl.columnNumPoints, IG.Forms.InputDataDefinitionControl.columnTitle, and IG.Forms.InputDataDefinitionControl.IsInputData.
Referenced by IG.Forms.InputDataDefinitionControl.InputDataDefinitionControl().
InitDataGridProperties() [1/2]
virtual void IG.Forms.InputDataDefinitionControl.InitDataGridProperties () inline protected virtual
Initializes additional properties of the data grid view that were not set in designer.
This is currently not used because the relevant proprties are set in the designer's code.
We will keep the method for the case it becomes useful (e.g. if EinForms GUI designer would tend to override property values when changing the form in the designer).
References IG.Forms.InputDataDefinitionControl.columnDefault, IG.Forms.InputDataDefinitionControl.columnDescription, IG.Forms.InputDataDefinitionControl.columnId, IG.Forms.InputDataDefinitionControl.columnMax, IG.Forms.InputDataDefinitionControl.columnMin, IG.Forms.InputDataDefinitionControl.columnName, IG.Forms.InputDataDefinitionControl.columnNumPoints, and IG.Forms.InputDataDefinitionControl.columnTitle.
GetGridControl() [1/2]
DataGridView IG.Forms.InputDataDefinitionControl.GetGridControl () inline
Returns the DataGridView control that is used for setting values of the input parameters.
Returns
References IG.Forms.InputDataDefinitionControl.dataGridView1.
CreateInputElementName() [1/2]
string IG.Forms.InputDataDefinitionControl.CreateInputElementName (int elementIndex) inline
Returns a suitable name for input data element with the specified index.
Parameters
elementIndex Index of the input data element whose name is generated.
References IG.Num.InputOutputDataDefiniton.CreateInputElementName(), IG.Forms.InputDataDefinitionControl.DataDefinition, and IG.Forms.InputDataDefinitionControl.UseLegalVariableNames.
Referenced by IG.Forms.InputDataDefinitionControl.CopyDataToGridRow(), IG.Forms.InputDataDefinitionControl.CopyGridRowToData(), and IG.Forms.InputDataDefinitionControl.CreateInputElement().
CreateOutputElementName() [1/2]
string IG.Forms.InputDataDefinitionControl.CreateOutputElementName (int elementIndex) inline
Returns a suitable name for output data element with the specified index.
Parameters
elementIndex Index of the output data element whose name is generated.
References IG.Num.InputOutputDataDefiniton.CreateOutputElementName(), IG.Forms.InputDataDefinitionControl.DataDefinition, and IG.Forms.InputDataDefinitionControl.UseLegalVariableNames.
Referenced by IG.Forms.InputDataDefinitionControl.CopyDataToGridRow(), IG.Forms.InputDataDefinitionControl.CopyGridRowToData(), and IG.Forms.InputDataDefinitionControl.CreateOutputElement().
CreateInputElement() [1/2]
InputElementDefinition IG.Forms.InputDataDefinitionControl.CreateInputElement (int elementIndex) inline
Creates and returns a new input data element definition.
Parameters
elementIndex Index of data elment.
References IG.Forms.InputDataDefinitionControl.CreateInputElementName(), IG.Num.InputOutputElementDefinition.Description, and IG.Num.InputOutputElementDefinition.Title.
CreateOutputElement() [1/2]
OutputElementDefinition IG.Forms.InputDataDefinitionControl.CreateOutputElement (int elementIndex) inline
Creates and returns a new output data element definition.
Parameters
elementIndex Index of data elment.
References IG.Forms.InputDataDefinitionControl.CreateOutputElementName(), IG.Num.InputOutputElementDefinition.Description, and IG.Num.InputOutputElementDefinition.Title.
CopyGridRowToData() [1/2]
void IG.Forms.InputDataDefinitionControl.CopyGridRowToData (int whichRow) inline
Copies data from the specified row of the data grid view to data definition object.
Parameters
whichRow Index of row that is copied.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Forms.InputDataDefinitionControl.ColumnIndexDefault, IG.Forms.InputDataDefinitionControl.ColumnIndexDescription, IG.Forms.InputDataDefinitionControl.ColumnIndexMax, IG.Forms.InputDataDefinitionControl.ColumnIndexMin, IG.Forms.InputDataDefinitionControl.ColumnIndexName, IG.Forms.InputDataDefinitionControl.ColumnIndexNumPoints, IG.Forms.InputDataDefinitionControl.ColumnIndexTitle, IG.Forms.InputDataDefinitionControl.CreateInputElementName(), IG.Forms.InputDataDefinitionControl.CreateOutputElementName(), IG.Forms.InputDataDefinitionControl.DataDefinition, IG.Forms.InputDataDefinitionControl.dataGridView1, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Num.InputOutputElementDefinition.Description, IG.Num.InputOutputElementDefinition.ElementIndex, IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Forms.InputDataDefinitionControl.IsInputData, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, IG.Num.InputOutputElementDefinition.Name, IG.Forms.InputDataDefinitionControl.NumElements, IG.Num.InputElementDefinition.NumSamplingPoints, and IG.Num.InputOutputElementDefinition.Title.
Referenced by IG.Forms.InputDataDefinitionControl.dGridInputParam_CellValueChanged().
CopyDataToGridRow() [1/2]
void IG.Forms.InputDataDefinitionControl.CopyDataToGridRow (int whichRow) inline
Copies data to the specified row of the data grid view from data definition object DataDefinition.
Parameters
whichRow Index of row that is copied.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Forms.InputDataDefinitionControl.ColumnIndexDefault, IG.Forms.InputDataDefinitionControl.ColumnIndexDescription, IG.Forms.InputDataDefinitionControl.ColumnIndexId, IG.Forms.InputDataDefinitionControl.ColumnIndexMax, IG.Forms.InputDataDefinitionControl.ColumnIndexMin, IG.Forms.InputDataDefinitionControl.ColumnIndexName, IG.Forms.InputDataDefinitionControl.ColumnIndexNumPoints, IG.Forms.InputDataDefinitionControl.ColumnIndexTitle, IG.Forms.InputDataDefinitionControl.CreateInputElementName(), IG.Forms.InputDataDefinitionControl.CreateOutputElementName(), IG.Forms.InputDataDefinitionControl.DataDefinition, IG.Forms.InputDataDefinitionControl.dataGridView1, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Num.InputOutputElementDefinition.Description, IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Forms.InputDataDefinitionControl.GridChangeEventsDisabled, IG.Forms.InputDataDefinitionControl.IsInputData, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, IG.Num.InputOutputElementDefinition.Name, IG.Forms.InputDataDefinitionControl.NumElements, IG.Num.InputElementDefinition.NumSamplingPoints, and IG.Num.InputOutputElementDefinition.Title.
Referenced by IG.Forms.InputDataDefinitionControl.CopyDataToGrid().
CopyDataToGrid() [1/2]
void IG.Forms.InputDataDefinitionControl.CopyDataToGrid () inline
Copies data from the DataDefinition object to the internal data grid view control.
References IG.Forms.InputDataDefinitionControl.CopyDataToGridRow(), IG.Forms.InputDataDefinitionControl.DataDefinition, IG.Forms.InputDataDefinitionControl.dataGridView1, IG.Forms.InputDataDefinitionControl.GridChangeEventsDisabled, and IG.Forms.InputDataDefinitionControl.NumElements.
ClearCells() [1/2]
void IG.Forms.InputDataDefinitionControl.ClearCells () inline
Clears contents of all DataGridView cells.
References IG.Forms.InputDataDefinitionControl.DataDefinition, IG.Forms.InputDataDefinitionControl.dataGridView1, and IG.Num.InputOutputDataDefiniton.InputLength.
ClearDataGrid() [1/2]
void IG.Forms.InputDataDefinitionControl.ClearDataGrid () inline
Removes all the data from the DataGridView.
References IG.Forms.InputDataDefinitionControl.dataGridView1.
OnDefinitionObjectChanged() [1/2]
void IG.Forms.InputDataDefinitionControl.OnDefinitionObjectChanged (InputOutputDataDefiniton oldDataDefinition, InputOutputDataDefiniton newDataDefinition) inline protected
Raises the DefinitionObjectChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldDataDefinition Old data definition object.
newDataDefinition New data definition object.
References IG.Forms.InputDataDefinitionControl.DefinitionObjectChanged.
OnNumElementsChanged() [1/2]
void IG.Forms.InputDataDefinitionControl.OnNumElementsChanged (int oldLength, int newLength) inline protected
Raises the NumElementsChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldLength Old length.
newLength New length.
References IG.Forms.InputDataDefinitionControl.NumElementsChanged.
CreateSummary() [1/2]
virtual string IG.Forms.InputDataDefinitionControl.CreateSummary () inline virtual
References IG.Forms.InputDataDefinitionControl.DefinitionObjectChanged, IG.Forms.InputDataDefinitionControl.InputLength, IG.Forms.InputDataDefinitionControl.IsInputData, IG.Forms.InputDataDefinitionControl.NumElements, IG.Forms.InputDataDefinitionControl.NumElementsChanged, and IG.Forms.InputDataDefinitionControl.OutputLength.
ShowContextMenuControl() [1/2]
void IG.Forms.InputDataDefinitionControl.ShowContextMenuControl (object sender, MouseEventArgs e) inline
References IG.Forms.InputDataDefinitionControl.contextMenuControl.
Referenced by IG.Forms.InputDataDefinitionControl.dGridInputParam_MouseClick(), and IG.Forms.InputDataDefinitionControl.InputDataDefinitionControl_MouseClick().
InputDataDefinitionControl_MouseClick() [1/2]
void IG.Forms.InputDataDefinitionControl.InputDataDefinitionControl_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Forms.InputDataDefinitionControl.ShowContextMenuControl().
dGridInputParam_MouseClick() [1/2]
void IG.Forms.InputDataDefinitionControl.dGridInputParam_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Forms.InputDataDefinitionControl.ShowContextMenuControl().
btnResetDefault_Click() [1/2]
void IG.Forms.InputDataDefinitionControl.btnResetDefault_Click (object sender, EventArgs e) inline private
Referenced by IG.Forms.InputDataDefinitionControl.InitializeComponent().
btnResetCenter_Click() [1/2]
void IG.Forms.InputDataDefinitionControl.btnResetCenter_Click (object sender, EventArgs e) inline private
Referenced by IG.Forms.InputDataDefinitionControl.InitializeComponent().
resetToDefaultToolStripMenuItem_Click() [1/2]
void IG.Forms.InputDataDefinitionControl.resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e) inline private
resetToCenterToolStripMenuItem_Click() [1/2]
void IG.Forms.InputDataDefinitionControl.resetToCenterToolStripMenuItem_Click (object sender, EventArgs e) inline private
dGridInputParam_CellValueChanged() [1/2]
void IG.Forms.InputDataDefinitionControl.dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e) inline private
References IG.Forms.InputDataDefinitionControl.btnResetDefault, IG.Forms.InputDataDefinitionControl.CopyGridRowToData(), IG.Forms.InputDataDefinitionControl.GridChangeEventsDisabled, and IG.Lib.Util.SleepSeconds().
Dispose() [1/2]
override void IG.Forms.InputDataDefinitionControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.InputDataDefinitionControl.components.
InitializeComponent() [1/2]
void IG.Forms.InputDataDefinitionControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.InputDataDefinitionControl.btnResetCenter, IG.Forms.InputDataDefinitionControl.btnResetCenter_Click(), IG.Forms.InputDataDefinitionControl.btnResetDefault, IG.Forms.InputDataDefinitionControl.btnResetDefault_Click(), IG.Forms.InputDataDefinitionControl.columnDefault, IG.Forms.InputDataDefinitionControl.columnDescription, IG.Forms.InputDataDefinitionControl.columnId, IG.Forms.InputDataDefinitionControl.columnMax, IG.Forms.InputDataDefinitionControl.columnMin, IG.Forms.InputDataDefinitionControl.columnName, IG.Forms.InputDataDefinitionControl.columnNumPoints, IG.Forms.InputDataDefinitionControl.columnTitle, IG.Forms.InputDataDefinitionControl.components, IG.Forms.InputDataDefinitionControl.contextMenuControl, IG.Forms.InputDataDefinitionControl.dataGridView1, IG.Forms.InputDataDefinitionControl.grpOuter, IG.Forms.InputDataDefinitionControl.resetToCenterToolStripMenuItem, and IG.Forms.InputDataDefinitionControl.resetToDefaultToolStripMenuItem.
Referenced by IG.Forms.InputDataDefinitionControl.InputDataDefinitionControl().
UpdateInputOrOutput() [2/2]
void IG.Forms.InputDataDefinitionControl.UpdateInputOrOutput (bool isInput) inline
Prepares control for processing either input or output data.
When calling this method, its body is executed regardles of whether it has been called with the same parameters before. This is different from IsInputData setter which has effect only when value is actually changed.
Parameters
isInput
References IG.Forms.InputDataDefinitionControl.columnDefault, IG.Forms.InputDataDefinitionControl.columnDescription, IG.Forms.InputDataDefinitionControl.columnId, IG.Forms.InputDataDefinitionControl.columnMax, IG.Forms.InputDataDefinitionControl.columnMin, IG.Forms.InputDataDefinitionControl.columnName, IG.Forms.InputDataDefinitionControl.columnNumPoints, IG.Forms.InputDataDefinitionControl.columnTitle, IG.Forms.InputDataDefinitionControl.grpOuter, IG.Forms.InputDataDefinitionControl.IsInputData, and IG.Forms.InputDataDefinitionControl.TitleWithChangedSign.
InitDataGridProperties() [2/2]
virtual void IG.Forms.InputDataDefinitionControl.InitDataGridProperties () inline protected virtual
Initializes additional properties of the data grid view that were not set in designer.
This is currently not used because the relevant proprties are set in the designer's code.
We will keep the method for the case it becomes useful (e.g. if EinForms GUI designer would tend to override property values when changing the form in the designer).
References IG.Forms.InputDataDefinitionControl.columnDefault, IG.Forms.InputDataDefinitionControl.columnDescription, IG.Forms.InputDataDefinitionControl.columnId, IG.Forms.InputDataDefinitionControl.columnMax, IG.Forms.InputDataDefinitionControl.columnMin, IG.Forms.InputDataDefinitionControl.columnName, IG.Forms.InputDataDefinitionControl.columnNumPoints, and IG.Forms.InputDataDefinitionControl.columnTitle.
GetGridControl() [2/2]
DataGridView IG.Forms.InputDataDefinitionControl.GetGridControl () inline
Returns the DataGridView control that is used for setting values of the input parameters.
Returns
References IG.Forms.InputDataDefinitionControl.dataGridView1.
CreateInputElementName() [2/2]
string IG.Forms.InputDataDefinitionControl.CreateInputElementName (int elementIndex) inline
Returns a suitable name for input data element with the specified index.
Parameters
elementIndex Index of the input data element whose name is generated.
References IG.Num.InputOutputDataDefiniton.CreateInputElementName(), IG.Forms.InputDataDefinitionControl.DataDefinition, and IG.Forms.InputDataDefinitionControl.UseLegalVariableNames.
CreateOutputElementName() [2/2]
string IG.Forms.InputDataDefinitionControl.CreateOutputElementName (int elementIndex) inline
Returns a suitable name for output data element with the specified index.
Parameters
elementIndex Index of the output data element whose name is generated.
References IG.Num.InputOutputDataDefiniton.CreateOutputElementName(), IG.Forms.InputDataDefinitionControl.DataDefinition, and IG.Forms.InputDataDefinitionControl.UseLegalVariableNames.
CreateInputElement() [2/2]
InputElementDefinition IG.Forms.InputDataDefinitionControl.CreateInputElement (int elementIndex) inline
Creates and returns a new input data element definition.
Parameters
elementIndex Index of data elment.
References IG.Forms.InputDataDefinitionControl.CreateInputElementName(), IG.Num.InputOutputElementDefinition.Description, and IG.Num.InputOutputElementDefinition.Title.
CreateOutputElement() [2/2]
OutputElementDefinition IG.Forms.InputDataDefinitionControl.CreateOutputElement (int elementIndex) inline
Creates and returns a new output data element definition.
Parameters
elementIndex Index of data elment.
References IG.Forms.InputDataDefinitionControl.CreateOutputElementName(), IG.Num.InputOutputElementDefinition.Description, and IG.Num.InputOutputElementDefinition.Title.
CopyGridRowToData() [2/2]
void IG.Forms.InputDataDefinitionControl.CopyGridRowToData (int whichRow) inline
Copies data from the specified row of the data grid view to data definition object.
Parameters
whichRow Index of row that is copied.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Forms.InputDataDefinitionControl.ColumnIndexDefault, IG.Forms.InputDataDefinitionControl.ColumnIndexDescription, IG.Forms.InputDataDefinitionControl.ColumnIndexMax, IG.Forms.InputDataDefinitionControl.ColumnIndexMin, IG.Forms.InputDataDefinitionControl.ColumnIndexName, IG.Forms.InputDataDefinitionControl.ColumnIndexNumPoints, IG.Forms.InputDataDefinitionControl.ColumnIndexTitle, IG.Forms.InputDataDefinitionControl.CreateInputElementName(), IG.Forms.InputDataDefinitionControl.CreateOutputElementName(), IG.Forms.InputDataDefinitionControl.DataDefinition, IG.Forms.InputDataDefinitionControl.dataGridView1, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Num.InputOutputElementDefinition.Description, IG.Num.InputOutputElementDefinition.ElementIndex, IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Forms.InputDataDefinitionControl.HasUnsavedChanges, IG.Forms.InputDataDefinitionControl.IsInputData, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, IG.Num.InputOutputElementDefinition.Name, IG.Forms.InputDataDefinitionControl.NumElements, IG.Num.InputElementDefinition.NumSamplingPoints, IG.Forms.InputDataDefinitionControl.OnDataChanged(), and IG.Num.InputOutputElementDefinition.Title.
CopyDataToGridRow() [2/2]
void IG.Forms.InputDataDefinitionControl.CopyDataToGridRow (int whichRow) inline
Copies data to the specified row of the data grid view from data definition object DataDefinition.
Parameters
whichRow Index of row that is copied.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Forms.InputDataDefinitionControl.ColumnIndexDefault, IG.Forms.InputDataDefinitionControl.ColumnIndexDescription, IG.Forms.InputDataDefinitionControl.ColumnIndexId, IG.Forms.InputDataDefinitionControl.ColumnIndexMax, IG.Forms.InputDataDefinitionControl.ColumnIndexMin, IG.Forms.InputDataDefinitionControl.ColumnIndexName, IG.Forms.InputDataDefinitionControl.ColumnIndexNumPoints, IG.Forms.InputDataDefinitionControl.ColumnIndexTitle, IG.Forms.InputDataDefinitionControl.CreateInputElementName(), IG.Forms.InputDataDefinitionControl.CreateOutputElementName(), IG.Forms.InputDataDefinitionControl.DataDefinition, IG.Forms.InputDataDefinitionControl.dataGridView1, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Num.InputOutputElementDefinition.Description, IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Forms.InputDataDefinitionControl.GridChangeEventsDisabled, IG.Forms.InputDataDefinitionControl.IsInputData, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, IG.Num.InputOutputElementDefinition.Name, IG.Forms.InputDataDefinitionControl.NumElements, IG.Num.InputElementDefinition.NumSamplingPoints, and IG.Num.InputOutputElementDefinition.Title.
CopyDataToGrid() [2/2]
void IG.Forms.InputDataDefinitionControl.CopyDataToGrid () inline
Copies data from the DataDefinition object to the internal data grid view control.
References IG.Forms.InputDataDefinitionControl.CopyDataToGridRow(), IG.Forms.InputDataDefinitionControl.DataDefinition, IG.Forms.InputDataDefinitionControl.dataGridView1, IG.Forms.InputDataDefinitionControl.GridChangeEventsDisabled, and IG.Forms.InputDataDefinitionControl.NumElements.
ClearCells() [2/2]
void IG.Forms.InputDataDefinitionControl.ClearCells () inline
Clears contents of all DataGridView cells.
References IG.Forms.InputDataDefinitionControl.DataDefinition, IG.Forms.InputDataDefinitionControl.dataGridView1, and IG.Num.InputOutputDataDefiniton.InputLength.
ClearDataGrid() [2/2]
void IG.Forms.InputDataDefinitionControl.ClearDataGrid () inline
Removes all the data from the DataGridView.
References IG.Forms.InputDataDefinitionControl.dataGridView1.
OnDefinitionObjectChanged() [2/2]
void IG.Forms.InputDataDefinitionControl.OnDefinitionObjectChanged (InputOutputDataDefiniton oldDataDefinition, InputOutputDataDefiniton newDataDefinition) inline protected
Raises the DefinitionObjectChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldDataDefinition Old data definition object.
newDataDefinition New data definition object.
References IG.Forms.InputDataDefinitionControl.DefinitionObjectChanged.
OnNumElementsChanged() [2/2]
void IG.Forms.InputDataDefinitionControl.OnNumElementsChanged (int oldLength, int newLength) inline protected
Raises the NumElementsChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldLength Old length.
newLength New length.
References IG.Forms.InputDataDefinitionControl.NumElementsChanged.
OnDataChanged()
void IG.Forms.InputDataDefinitionControl.OnDataChanged () inline protected
Raises the ElementDataChanged event. This method should be called preferrably, rather than the event itself.
References IG.Forms.InputDataDefinitionControl.DataChanged.
Referenced by IG.Forms.InputDataDefinitionControl.CopyGridRowToData().
CreateSummary() [2/2]
virtual string IG.Forms.InputDataDefinitionControl.CreateSummary () inline virtual
References IG.Forms.InputDataDefinitionControl.DataChanged, IG.Forms.InputDataDefinitionControl.DefinitionObjectChanged, IG.Forms.InputDataDefinitionControl.InputLength, IG.Forms.InputDataDefinitionControl.IsInputData, IG.Forms.InputDataDefinitionControl.NumElements, IG.Forms.InputDataDefinitionControl.NumElementsChanged, and IG.Forms.InputDataDefinitionControl.OutputLength.
ShowContextMenuControl() [2/2]
void IG.Forms.InputDataDefinitionControl.ShowContextMenuControl (object sender, MouseEventArgs e) inline
References IG.Forms.InputDataDefinitionControl.contextMenuControl.
InputDataDefinitionControl_MouseClick() [2/2]
void IG.Forms.InputDataDefinitionControl.InputDataDefinitionControl_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Forms.InputDataDefinitionControl.ShowContextMenuControl().
dGridInputParam_MouseClick() [2/2]
void IG.Forms.InputDataDefinitionControl.dGridInputParam_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Forms.InputDataDefinitionControl.ShowContextMenuControl().
btnResetDefault_Click() [2/2]
void IG.Forms.InputDataDefinitionControl.btnResetDefault_Click (object sender, EventArgs e) inline private
btnResetCenter_Click() [2/2]
void IG.Forms.InputDataDefinitionControl.btnResetCenter_Click (object sender, EventArgs e) inline private
resetToDefaultToolStripMenuItem_Click() [2/2]
void IG.Forms.InputDataDefinitionControl.resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e) inline private
resetToCenterToolStripMenuItem_Click() [2/2]
void IG.Forms.InputDataDefinitionControl.resetToCenterToolStripMenuItem_Click (object sender, EventArgs e) inline private
dGridInputParam_CellValueChanged() [2/2]
void IG.Forms.InputDataDefinitionControl.dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e) inline private
References IG.Forms.InputDataDefinitionControl.btnResetDefault, IG.Forms.InputDataDefinitionControl.CopyGridRowToData(), IG.Forms.InputDataDefinitionControl.GridChangeEventsDisabled, and IG.Lib.Util.SleepSeconds().
Dispose() [2/2]
override void IG.Forms.InputDataDefinitionControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.InputDataDefinitionControl.components.
InitializeComponent() [2/2]
void IG.Forms.InputDataDefinitionControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.InputDataDefinitionControl.btnResetCenter, IG.Forms.InputDataDefinitionControl.btnResetCenter_Click(), IG.Forms.InputDataDefinitionControl.btnResetDefault, IG.Forms.InputDataDefinitionControl.btnResetDefault_Click(), IG.Forms.InputDataDefinitionControl.columnDefault, IG.Forms.InputDataDefinitionControl.columnDescription, IG.Forms.InputDataDefinitionControl.columnId, IG.Forms.InputDataDefinitionControl.columnMax, IG.Forms.InputDataDefinitionControl.columnMin, IG.Forms.InputDataDefinitionControl.columnName, IG.Forms.InputDataDefinitionControl.columnNumPoints, IG.Forms.InputDataDefinitionControl.columnTitle, IG.Forms.InputDataDefinitionControl.components, IG.Forms.InputDataDefinitionControl.contextMenuControl, IG.Forms.InputDataDefinitionControl.dataGridView1, IG.Forms.InputDataDefinitionControl.grpOuter, IG.Forms.InputDataDefinitionControl.resetToCenterToolStripMenuItem, and IG.Forms.InputDataDefinitionControl.resetToDefaultToolStripMenuItem.
Member Data Documentation
_dataDefinition
InputOutputDataDefiniton IG.Forms.InputDataDefinitionControl._dataDefinition private
_inputLength
int IG.Forms.InputDataDefinitionControl._inputLength protected
_outputLength
int IG.Forms.InputDataDefinitionControl._outputLength protected
_title
string IG.Forms.InputDataDefinitionControl._title = "Input Data" private
_isInputData
bool IG.Forms.InputDataDefinitionControl._isInputData = true protected
_isDimentionChangeAllowed
bool IG.Forms.InputDataDefinitionControl._isDimentionChangeAllowed = true private
_gridChangeEventsDdisabled
bool IG.Forms.InputDataDefinitionControl._gridChangeEventsDdisabled = false private
_columnIndexId
int IG.Forms.InputDataDefinitionControl._columnIndexId = -1 private
_columnIndexName
int IG.Forms.InputDataDefinitionControl._columnIndexName = -1 private
_columnIndexMin
int IG.Forms.InputDataDefinitionControl._columnIndexMin = -1 private
_columnIndexMax
int IG.Forms.InputDataDefinitionControl._columnIndexMax = -1 private
_columnIndexDefault
int IG.Forms.InputDataDefinitionControl._columnIndexDefault = -1 private
_columnIndexNumPoints
int IG.Forms.InputDataDefinitionControl._columnIndexNumPoints = -1 private
_columnIndexTitle
int IG.Forms.InputDataDefinitionControl._columnIndexTitle = -1 private
_columnIndexDescription
int IG.Forms.InputDataDefinitionControl._columnIndexDescription = -1 private
_useLegalVariableNames
bool IG.Forms.InputDataDefinitionControl._useLegalVariableNames = true private
_values
Vector IG.Forms.InputDataDefinitionControl._values protected
components
System ComponentModel IContainer IG.Forms.InputDataDefinitionControl.components = null private
Required designer variable.
Referenced by IG.Forms.InputDataDefinitionControl.Dispose(), and IG.Forms.InputDataDefinitionControl.InitializeComponent().
grpOuter
System Windows Forms GroupBox IG.Forms.InputDataDefinitionControl.grpOuter private
Referenced by IG.Forms.InputDataDefinitionControl.InitializeComponent(), IG.Forms.InputDataDefinitionControl.InputDataDefinitionControl(), and IG.Forms.InputDataDefinitionControl.UpdateInputOrOutput().
dataGridView1
System Windows Forms DataGridView IG.Forms.InputDataDefinitionControl.dataGridView1 private
Referenced by IG.Forms.InputDataDefinitionControl.ClearCells(), IG.Forms.InputDataDefinitionControl.ClearDataGrid(), IG.Forms.InputDataDefinitionControl.CopyDataToGrid(), IG.Forms.InputDataDefinitionControl.CopyDataToGridRow(), IG.Forms.InputDataDefinitionControl.CopyGridRowToData(), IG.Forms.InputDataDefinitionControl.GetGridControl(), and IG.Forms.InputDataDefinitionControl.InitializeComponent().
btnResetDefault
System Windows Forms Button IG.Forms.InputDataDefinitionControl.btnResetDefault private
Referenced by IG.Forms.InputDataDefinitionControl.dGridInputParam_CellValueChanged(), and IG.Forms.InputDataDefinitionControl.InitializeComponent().
btnResetCenter
System Windows Forms Button IG.Forms.InputDataDefinitionControl.btnResetCenter private
Referenced by IG.Forms.InputDataDefinitionControl.InitializeComponent().
contextMenuControl
System Windows Forms ContextMenuStrip IG.Forms.InputDataDefinitionControl.contextMenuControl private
Referenced by IG.Forms.InputDataDefinitionControl.InitializeComponent(), and IG.Forms.InputDataDefinitionControl.ShowContextMenuControl().
resetToDefaultToolStripMenuItem
System Windows Forms ToolStripMenuItem IG.Forms.InputDataDefinitionControl.resetToDefaultToolStripMenuItem private
Referenced by IG.Forms.InputDataDefinitionControl.InitializeComponent().
resetToCenterToolStripMenuItem
System Windows Forms ToolStripMenuItem IG.Forms.InputDataDefinitionControl.resetToCenterToolStripMenuItem private
Referenced by IG.Forms.InputDataDefinitionControl.InitializeComponent().
columnId
System Windows Forms DataGridViewTextBoxColumn IG.Forms.InputDataDefinitionControl.columnId private
Referenced by IG.Forms.InputDataDefinitionControl.InitDataGridProperties(), IG.Forms.InputDataDefinitionControl.InitializeComponent(), and IG.Forms.InputDataDefinitionControl.UpdateInputOrOutput().
columnName
System Windows Forms DataGridViewTextBoxColumn IG.Forms.InputDataDefinitionControl.columnName private
Referenced by IG.Forms.InputDataDefinitionControl.InitDataGridProperties(), IG.Forms.InputDataDefinitionControl.InitializeComponent(), and IG.Forms.InputDataDefinitionControl.UpdateInputOrOutput().
columnMin
System Windows Forms DataGridViewTextBoxColumn IG.Forms.InputDataDefinitionControl.columnMin private
Referenced by IG.Forms.InputDataDefinitionControl.InitDataGridProperties(), IG.Forms.InputDataDefinitionControl.InitializeComponent(), and IG.Forms.InputDataDefinitionControl.UpdateInputOrOutput().
columnMax
System Windows Forms DataGridViewTextBoxColumn IG.Forms.InputDataDefinitionControl.columnMax private
Referenced by IG.Forms.InputDataDefinitionControl.InitDataGridProperties(), IG.Forms.InputDataDefinitionControl.InitializeComponent(), and IG.Forms.InputDataDefinitionControl.UpdateInputOrOutput().
columnDefault
System Windows Forms DataGridViewTextBoxColumn IG.Forms.InputDataDefinitionControl.columnDefault private
Referenced by IG.Forms.InputDataDefinitionControl.InitDataGridProperties(), IG.Forms.InputDataDefinitionControl.InitializeComponent(), and IG.Forms.InputDataDefinitionControl.UpdateInputOrOutput().
columnNumPoints
System Windows Forms DataGridViewTextBoxColumn IG.Forms.InputDataDefinitionControl.columnNumPoints private
Referenced by IG.Forms.InputDataDefinitionControl.InitDataGridProperties(), IG.Forms.InputDataDefinitionControl.InitializeComponent(), and IG.Forms.InputDataDefinitionControl.UpdateInputOrOutput().
columnTitle
System Windows Forms DataGridViewTextBoxColumn IG.Forms.InputDataDefinitionControl.columnTitle private
Referenced by IG.Forms.InputDataDefinitionControl.InitDataGridProperties(), IG.Forms.InputDataDefinitionControl.InitializeComponent(), and IG.Forms.InputDataDefinitionControl.UpdateInputOrOutput().
columnDescription
System Windows Forms DataGridViewTextBoxColumn IG.Forms.InputDataDefinitionControl.columnDescription private
Referenced by IG.Forms.InputDataDefinitionControl.InitDataGridProperties(), IG.Forms.InputDataDefinitionControl.InitializeComponent(), and IG.Forms.InputDataDefinitionControl.UpdateInputOrOutput().
_titleInputData
string IG.Forms.InputDataDefinitionControl._titleInputData = "Input Data" private
_titleOutputData
string IG.Forms.InputDataDefinitionControl._titleOutputData = "Output Data" private
_hasUnsavedChanges
bool IG.Forms.InputDataDefinitionControl._hasUnsavedChanges = false private
Property Documentation
DataDefinition
InputOutputDataDefiniton IG.Forms.InputDataDefinitionControl.DataDefinition get set
Data about input and output quantities of the manipulated functions or response.
Referenced by IG.Forms.InputDataDefinitionControl.ClearCells(), IG.Forms.InputDataDefinitionControl.CopyDataToGrid(), IG.Forms.InputDataDefinitionControl.CopyDataToGridRow(), IG.Forms.InputDataDefinitionControl.CopyGridRowToData(), IG.Forms.InputDataDefinitionControl.CreateInputElementName(), and IG.Forms.InputDataDefinitionControl.CreateOutputElementName().
NumElements
int IG.Forms.InputDataDefinitionControl.NumElements get protected set
Number of the corresponding elements in the data definition.
If IsInputData then this refers to the number of input elements, otherwise to the number o output elements.
Referenced by IG.Forms.InputDataDefinitionControl.CopyDataToGrid(), IG.Forms.InputDataDefinitionControl.CopyDataToGridRow(), IG.Forms.InputDataDefinitionControl.CopyGridRowToData(), and IG.Forms.InputDataDefinitionControl.CreateSummary().
InputLength
int IG.Forms.InputDataDefinitionControl.InputLength get set
Number of input parameters or data elements.
Referenced by IG.Forms.InputDataDefinitionControl.CreateSummary().
OutputLength
int IG.Forms.InputDataDefinitionControl.OutputLength get set
Number of output parameters or data elements.
Referenced by IG.Forms.InputDataDefinitionControl.CreateSummary().
Title
string IG.Forms.InputDataDefinitionControl.Title get set
Text of the title label shown on top left of the form.
Gets text of the title label shown on top left of the form.
Referenced by IG.Forms.InputDataDefinitionControl.InputDataDefinitionControl().
IsInputData
bool IG.Forms.InputDataDefinitionControl.IsInputData get set
Indicates whether this form is used to edit input (when true) or output (when false) data elements.
Setting the property will change behavior.
Referenced by IG.Forms.InputDataDefinitionControl.CopyDataToGridRow(), IG.Forms.InputDataDefinitionControl.CopyGridRowToData(), IG.Forms.InputDataDefinitionControl.CreateSummary(), IG.Forms.InputDataDefinitionControl.InputDataDefinitionControl(), and IG.Forms.InputDataDefinitionControl.UpdateInputOrOutput().
IsOutputData
bool IG.Forms.InputDataDefinitionControl.IsOutputData get set protected
Indicates whether this form is used to edit input (when false) or output (when true) data elements.
This property depends on IsInputData property and is just its negation.
IsDimentionChangeAllowed
bool IG.Forms.InputDataDefinitionControl.IsDimentionChangeAllowed get set
Indicates whetherr user can change dimensions (number of input/output data elements).
GridChangeEventsDisabled
bool IG.Forms.InputDataDefinitionControl.GridChangeEventsDisabled get set protected
Flag for disabling events raised when grid data is changed. Default is false.
This should be set to true in functions where grid data is changed programatically.
Referenced by IG.Forms.InputDataDefinitionControl.CopyDataToGrid(), IG.Forms.InputDataDefinitionControl.CopyDataToGridRow(), IG.Forms.InputDataDefinitionControl.dGridInputParam_CellValueChanged(), and IG.Forms.InputDataDefinitionControl.InputDataDefinitionControl().
ColumnIndexId
int IG.Forms.InputDataDefinitionControl.ColumnIndexId get
Returns column index of the ID field.
Referenced by IG.Forms.InputDataDefinitionControl.CopyDataToGridRow().
ColumnIndexName
int IG.Forms.InputDataDefinitionControl.ColumnIndexName get
Returns column index of the Name field.
Referenced by IG.Forms.InputDataDefinitionControl.CopyDataToGridRow(), and IG.Forms.InputDataDefinitionControl.CopyGridRowToData().
ColumnIndexMin
int IG.Forms.InputDataDefinitionControl.ColumnIndexMin get
Returns column index of the Min field.
Referenced by IG.Forms.InputDataDefinitionControl.CopyDataToGridRow(), and IG.Forms.InputDataDefinitionControl.CopyGridRowToData().
ColumnIndexMax
int IG.Forms.InputDataDefinitionControl.ColumnIndexMax get
Returns column index of the Max field.
Referenced by IG.Forms.InputDataDefinitionControl.CopyDataToGridRow(), and IG.Forms.InputDataDefinitionControl.CopyGridRowToData().
ColumnIndexDefault
int IG.Forms.InputDataDefinitionControl.ColumnIndexDefault get
Returns column index of the Default field.
Referenced by IG.Forms.InputDataDefinitionControl.CopyDataToGridRow(), and IG.Forms.InputDataDefinitionControl.CopyGridRowToData().
ColumnIndexNumPoints
int IG.Forms.InputDataDefinitionControl.ColumnIndexNumPoints get
Returns column index of the Num field.
Referenced by IG.Forms.InputDataDefinitionControl.CopyDataToGridRow(), and IG.Forms.InputDataDefinitionControl.CopyGridRowToData().
ColumnIndexTitle
int IG.Forms.InputDataDefinitionControl.ColumnIndexTitle get
Returns column index of the Title field.
Referenced by IG.Forms.InputDataDefinitionControl.CopyDataToGridRow(), and IG.Forms.InputDataDefinitionControl.CopyGridRowToData().
ColumnIndexDescription
int IG.Forms.InputDataDefinitionControl.ColumnIndexDescription get
Returns column index of the Description field.
Referenced by IG.Forms.InputDataDefinitionControl.CopyDataToGridRow(), and IG.Forms.InputDataDefinitionControl.CopyGridRowToData().
UseLegalVariableNames
bool IG.Forms.InputDataDefinitionControl.UseLegalVariableNames get set
Specifies whether legal variable names (according to rules in programming languages such as C++, C# or Java) should be enforced for naming input and utput elements.
Referenced by IG.Forms.InputDataDefinitionControl.CreateInputElementName(), and IG.Forms.InputDataDefinitionControl.CreateOutputElementName().
NumValues
int IG.Forms.InputDataDefinitionControl.NumValues get
Current number of values, otained form the DataGridView.
TitleInputData
string IG.Forms.InputDataDefinitionControl.TitleInputData get set
Control's title (displayed as group box text) in case of input data editing.
TitleOutputData
string IG.Forms.InputDataDefinitionControl.TitleOutputData get set
Control's title (displayed as group box text) in case of output data editing.
TitleWithChangedSign
string IG.Forms.InputDataDefinitionControl.TitleWithChangedSign get
Actual title that is shown on the top of control, in the lblMainTitle label, includes eventual marks for unsaved changes.
Referenced by IG.Forms.InputDataDefinitionControl.UpdateInputOrOutput().
HasUnsavedChanges
bool IG.Forms.InputDataDefinitionControl.HasUnsavedChanges get set
Whether the current function definition has unsaved changes.
Referenced by IG.Forms.InputDataDefinitionControl.CopyGridRowToData().
Event Documentation
DefinitionObjectChanged
EventHandler< ValueChangeEventArgs< InputOutputDataDefiniton > > IG.Forms.InputDataDefinitionControl.DefinitionObjectChanged
Occurs when data definition object is changed (i.e., when object reference changes), meaning that whole data definition object is replaced.
Referenced by IG.Forms.InputDataDefinitionControl.CreateSummary(), and IG.Forms.InputDataDefinitionControl.OnDefinitionObjectChanged().
NumElementsChanged
EventHandler< IndexChangeEventArgs > IG.Forms.InputDataDefinitionControl.NumElementsChanged
Occurs when number of data elements (InputLength or OutputLength, dependent on IsInputData property) is changed.
Referenced by IG.Forms.InputDataDefinitionControl.CreateSummary(), and IG.Forms.InputDataDefinitionControl.OnNumElementsChanged().
DataChanged
EventHandler IG.Forms.InputDataDefinitionControl.DataChanged
Occurs when some element property is changed.
Referenced by IG.Forms.InputDataDefinitionControl.CreateSummary(), and IG.Forms.InputDataDefinitionControl.OnDataChanged().
The documentation for this class was generated from the following files:
unittests/Guest_IGTestCopy/Copy_Functions/44_Functions/Numeric/FromNeural/Basic/InputDataDefinitionControl.cs
unittests/Guest_IGTestCopy/Copy_Functions/44_Functions/Numeric/FromNeural/Basic/InputDataDefinitionControl.Designer.cs