Doc: IGLib EXTENDED: AForge.Imaging.Filters.YCbCrLinear Class Reference
AForge.Imaging.Filters.YCbCrLinear Class Reference
Linear correction of YCbCr channels.
Public Member Functions
YCbCrLinear ()
Initializes a new instance of the YCbCrLinear class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image, Rectangle rect)
Process the filter on the specified image.
Properties
Range InY [get, set]
Y component's input range.
Range InCb [get, set]
Cb component's input range.
Range InCr [get, set]
Cr component's input range.
Range OutY [get, set]
Y component's output range.
Range OutCb [get, set]
Cb component's output range.
Range OutCr [get, set]
Cr component's output range.
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
Range inY = new Range(0.0f, 1.0f)
Range inCb = new Range(-0.5f, 0.5f)
Range inCr = new Range(-0.5f, 0.5f)
Range outY = new Range(0.0f, 1.0f)
Range outCb = new Range(-0.5f, 0.5f)
Range outCr = new Range(-0.5f, 0.5f)
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Linear correction of YCbCr channels.
The filter operates in YCbCr color space and provides with the facility of linear correction of its channels - mapping specified channels' input ranges to specified output ranges.
The filter accepts 24 and 32 bpp color images for processing.
Sample usage:
// create filter
YCbCrLinear filter = new YCbCrLinear();
// configure the filter
filter.InCb = new Range(-0.276f, 0.163f);
filter.InCr = new Range(-0.202f, 0.500f);
// apply the filter
filter.ApplyInPlace(image);
Initial image:
Result image:
See also
HSLLinear, YCbCrLinear
Constructor & Destructor Documentation
YCbCrLinear()
AForge.Imaging.Filters.YCbCrLinear.YCbCrLinear () inline
Initializes a new instance of the YCbCrLinear class.
References AForge.Imaging.Filters.YCbCrLinear.formatTranslations.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.YCbCrLinear.ProcessFilter (UnmanagedImage image, Rectangle rect) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
rect Image rectangle for processing by the filter.
Implements AForge.Imaging.Filters.BaseInPlacePartialFilter.
References AForge.Imaging.RGB.B, AForge.Imaging.RGB.Blue, AForge.Imaging.YCbCr.Cb, AForge.Imaging.YCbCr.Cr, AForge.Imaging.YCbCr.FromRGB(), AForge.Imaging.RGB.G, AForge.Imaging.RGB.Green, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.Filters.YCbCrLinear.inCb, AForge.Imaging.Filters.YCbCrLinear.inCr, AForge.Imaging.Filters.YCbCrLinear.inY, AForge.Range.Max, AForge.Range.Min, AForge.Imaging.Filters.YCbCrLinear.outCb, AForge.Imaging.Filters.YCbCrLinear.outCr, AForge.Imaging.Filters.YCbCrLinear.outY, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, AForge.Imaging.RGB.Red, AForge.Imaging.UnmanagedImage.Stride, AForge.Imaging.YCbCr.ToRGB(), and AForge.Imaging.YCbCr.Y.
Member Data Documentation
inY
Range AForge.Imaging.Filters.YCbCrLinear.inY = new Range(0.0f, 1.0f) private
Referenced by AForge.Imaging.Filters.YCbCrLinear.ProcessFilter().
inCb
Range AForge.Imaging.Filters.YCbCrLinear.inCb = new Range(-0.5f, 0.5f) private
Referenced by AForge.Imaging.Filters.YCbCrLinear.ProcessFilter().
inCr
Range AForge.Imaging.Filters.YCbCrLinear.inCr = new Range(-0.5f, 0.5f) private
Referenced by AForge.Imaging.Filters.YCbCrLinear.ProcessFilter().
outY
Range AForge.Imaging.Filters.YCbCrLinear.outY = new Range(0.0f, 1.0f) private
Referenced by AForge.Imaging.Filters.YCbCrLinear.ProcessFilter().
outCb
Range AForge.Imaging.Filters.YCbCrLinear.outCb = new Range(-0.5f, 0.5f) private
Referenced by AForge.Imaging.Filters.YCbCrLinear.ProcessFilter().
outCr
Range AForge.Imaging.Filters.YCbCrLinear.outCr = new Range(-0.5f, 0.5f) private
Referenced by AForge.Imaging.Filters.YCbCrLinear.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.YCbCrLinear.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.YCbCrLinear.YCbCrLinear().
Property Documentation
InY
Range AForge.Imaging.Filters.YCbCrLinear.InY get set
Y component's input range.
Y component is measured in the range of [0, 1].
InCb
Range AForge.Imaging.Filters.YCbCrLinear.InCb get set
Cb component's input range.
Cb component is measured in the range of [-0.5, 0.5].
Referenced by FiltersDemo.MainForm.yCbCrLinearFiltersItem_Click().
InCr
Range AForge.Imaging.Filters.YCbCrLinear.InCr get set
Cr component's input range.
Cr component is measured in the range of [-0.5, 0.5].
OutY
Range AForge.Imaging.Filters.YCbCrLinear.OutY get set
Y component's output range.
Y component is measured in the range of [0, 1].
OutCb
Range AForge.Imaging.Filters.YCbCrLinear.OutCb get set
Cb component's output range.
Cb component is measured in the range of [-0.5, 0.5].
OutCr
Range AForge.Imaging.Filters.YCbCrLinear.OutCr get set
Cr component's output range.
Cr component is measured in the range of [-0.5, 0.5].
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.YCbCrLinear.FormatTranslations get
Format translations dictionary.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/YCbCr Filters/YCbCrLinear.cs