Doc: IGLib EXTENDED: NUnitLite.Tests.NUnit2XmlOutputWriterTests Class Reference
NUnitLite.Tests.NUnit2XmlOutputWriterTests Class Reference
Public Member Functions
void RunMockAssemblyTests ()
void Document_HasThreeChildren ()
void Document_FirstChildIsXmlDeclaration ()
void Document_SecondChildIsComment ()
void Document_ThirdChildIsTestResults ()
void Document_HasTestResults ()
void TestResults_AssemblyPathIsCorrect ()
void TestResults_CounterIsCorrect (string name, int count)
void TestResults_HasValidDateAttribute ()
void TestResults_HasValidTimeAttribute ()
void Environment_HasEnvironmentElement ()
void Environment_HasRequiredAttribute (string name)
void CultureInfo_HasCultureInfoElement ()
void CultureInfo_HasRequiredAttribute (string name)
void TestSuite_HasTestSuiteElement ()
void TestSuite_ExpectedAttribute (string name, string value)
void TestSuite_HasValidTimeAttribute ()
void TestSuite_ResultIsFailure ()
Private Member Functions
string RequiredAttribute (XmlNode node, string name)
Private Attributes
XmlDocument doc
XmlNode topNode
XmlNode envNode
XmlNode cultureNode
XmlNode suiteNode
Member Function Documentation
RunMockAssemblyTests()
void NUnitLite.Tests.NUnit2XmlOutputWriterTests.RunMockAssemblyTests () inline
References NUnitLite.Tests.NUnit2XmlOutputWriterTests.cultureNode, NUnitLite.Tests.NUnit2XmlOutputWriterTests.doc, NUnitLite.Tests.NUnit2XmlOutputWriterTests.envNode, NUnit.Framework.Assert.NotNull(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.suiteNode, NUnitLite.Tests.NUnit2XmlOutputWriterTests.topNode, and NUnitLite.NUnit2XmlOutputWriter.WriteResultFile().
Document_HasThreeChildren()
void NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_HasThreeChildren () inline
References NUnitLite.Tests.NUnit2XmlOutputWriterTests.doc, NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
Document_FirstChildIsXmlDeclaration()
void NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_FirstChildIsXmlDeclaration () inline
References NUnitLite.Tests.NUnit2XmlOutputWriterTests.doc, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
Document_SecondChildIsComment()
void NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_SecondChildIsComment () inline
References NUnitLite.Tests.NUnit2XmlOutputWriterTests.doc, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
Document_ThirdChildIsTestResults()
void NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_ThirdChildIsTestResults () inline
References NUnitLite.Tests.NUnit2XmlOutputWriterTests.doc, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
Document_HasTestResults()
void NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_HasTestResults () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.Not, NUnit.Framework.Assert.That(), and NUnitLite.Tests.NUnit2XmlOutputWriterTests.topNode.
TestResults_AssemblyPathIsCorrect()
void NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestResults_AssemblyPathIsCorrect () inline
References NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.RequiredAttribute(), NUnit.Framework.Assert.That(), and NUnitLite.Tests.NUnit2XmlOutputWriterTests.topNode.
TestResults_CounterIsCorrect()
void NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestResults_CounterIsCorrect (string name, int count) inline
References NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.RequiredAttribute(), NUnit.Framework.Assert.That(), and NUnitLite.Tests.NUnit2XmlOutputWriterTests.topNode.
TestResults_HasValidDateAttribute()
void NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestResults_HasValidDateAttribute () inline
References NUnitLite.Tests.NUnit2XmlOutputWriterTests.RequiredAttribute(), NUnit.Framework.Assert.That(), and NUnitLite.Tests.NUnit2XmlOutputWriterTests.topNode.
TestResults_HasValidTimeAttribute()
void NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestResults_HasValidTimeAttribute () inline
References NUnitLite.Tests.NUnit2XmlOutputWriterTests.RequiredAttribute(), NUnit.Framework.Assert.That(), and NUnitLite.Tests.NUnit2XmlOutputWriterTests.topNode.
Environment_HasEnvironmentElement()
void NUnitLite.Tests.NUnit2XmlOutputWriterTests.Environment_HasEnvironmentElement () inline
References NUnitLite.Tests.NUnit2XmlOutputWriterTests.envNode, NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
Environment_HasRequiredAttribute()
void NUnitLite.Tests.NUnit2XmlOutputWriterTests.Environment_HasRequiredAttribute (string name) inline
References NUnitLite.Tests.NUnit2XmlOutputWriterTests.envNode, and NUnitLite.Tests.NUnit2XmlOutputWriterTests.RequiredAttribute().
CultureInfo_HasCultureInfoElement()
void NUnitLite.Tests.NUnit2XmlOutputWriterTests.CultureInfo_HasCultureInfoElement () inline
References NUnitLite.Tests.NUnit2XmlOutputWriterTests.cultureNode, NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
CultureInfo_HasRequiredAttribute()
void NUnitLite.Tests.NUnit2XmlOutputWriterTests.CultureInfo_HasRequiredAttribute (string name) inline
References NUnitLite.Tests.NUnit2XmlOutputWriterTests.cultureNode, NUnit.Framework.Is.Not, NUnitLite.Tests.NUnit2XmlOutputWriterTests.RequiredAttribute(), and NUnit.Framework.Assert.That().
TestSuite_HasTestSuiteElement()
void NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestSuite_HasTestSuiteElement () inline
References NUnit.Framework.Is.Not, NUnitLite.Tests.NUnit2XmlOutputWriterTests.suiteNode, and NUnit.Framework.Assert.That().
TestSuite_ExpectedAttribute()
void NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestSuite_ExpectedAttribute (string name, string value) inline
References NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.RequiredAttribute(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.suiteNode, and NUnit.Framework.Assert.That().
TestSuite_HasValidTimeAttribute()
void NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestSuite_HasValidTimeAttribute () inline
References NUnitLite.Tests.NUnit2XmlOutputWriterTests.RequiredAttribute(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.suiteNode, and NUnit.Framework.Assert.That().
TestSuite_ResultIsFailure()
void NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestSuite_ResultIsFailure () inline
RequiredAttribute()
string NUnitLite.Tests.NUnit2XmlOutputWriterTests.RequiredAttribute (XmlNode node, string name) inline private
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
Referenced by NUnitLite.Tests.NUnit2XmlOutputWriterTests.CultureInfo_HasRequiredAttribute(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Environment_HasRequiredAttribute(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestResults_AssemblyPathIsCorrect(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestResults_CounterIsCorrect(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestResults_HasValidDateAttribute(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestResults_HasValidTimeAttribute(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestSuite_ExpectedAttribute(), and NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestSuite_HasValidTimeAttribute().
Member Data Documentation
doc
XmlDocument NUnitLite.Tests.NUnit2XmlOutputWriterTests.doc private
Referenced by NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_FirstChildIsXmlDeclaration(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_HasThreeChildren(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_SecondChildIsComment(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_ThirdChildIsTestResults(), and NUnitLite.Tests.NUnit2XmlOutputWriterTests.RunMockAssemblyTests().
topNode
XmlNode NUnitLite.Tests.NUnit2XmlOutputWriterTests.topNode private
Referenced by NUnitLite.Tests.NUnit2XmlOutputWriterTests.Document_HasTestResults(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.RunMockAssemblyTests(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestResults_AssemblyPathIsCorrect(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestResults_CounterIsCorrect(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestResults_HasValidDateAttribute(), and NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestResults_HasValidTimeAttribute().
envNode
XmlNode NUnitLite.Tests.NUnit2XmlOutputWriterTests.envNode private
Referenced by NUnitLite.Tests.NUnit2XmlOutputWriterTests.Environment_HasEnvironmentElement(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.Environment_HasRequiredAttribute(), and NUnitLite.Tests.NUnit2XmlOutputWriterTests.RunMockAssemblyTests().
cultureNode
XmlNode NUnitLite.Tests.NUnit2XmlOutputWriterTests.cultureNode private
Referenced by NUnitLite.Tests.NUnit2XmlOutputWriterTests.CultureInfo_HasCultureInfoElement(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.CultureInfo_HasRequiredAttribute(), and NUnitLite.Tests.NUnit2XmlOutputWriterTests.RunMockAssemblyTests().
suiteNode
XmlNode NUnitLite.Tests.NUnit2XmlOutputWriterTests.suiteNode private
Referenced by NUnitLite.Tests.NUnit2XmlOutputWriterTests.RunMockAssemblyTests(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestSuite_ExpectedAttribute(), NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestSuite_HasTestSuiteElement(), and NUnitLite.Tests.NUnit2XmlOutputWriterTests.TestSuite_HasValidTimeAttribute().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/nunitlite.tests/NUnit2XmlOutputWriterTests.cs