Doc: IGLib EXTENDED: alglib.studenttdistr Class Reference
alglib.studenttdistr Class Reference
Static Public Member Functions
static double studenttdistribution (int k, double t)
static double invstudenttdistribution (int k, double p)
static double studenttdistribution (int k, double t)
static double invstudenttdistribution (int k, double p)
Member Function Documentation
studenttdistribution() [1/2]
static double alglib.studenttdistr.studenttdistribution (int k, double t) inline static
References alglib.ap.assert(), alglib.ibetaf.incompletebeta(), and alglib.math.machineepsilon.
Referenced by alglib.correlationtests.pearsoncorrelationsignificance(), alglib.correlationtests.spearmantail(), alglib.correlationtests.spearmantail5(), alglib.correlationtests.spearmantail6(), alglib.correlationtests.spearmantail7(), alglib.correlationtests.spearmantail8(), alglib.correlationtests.spearmantail9(), alglib.studenttdistribution(), alglib.studentttests.studentttest1(), and alglib.studentttests.studentttest2().
invstudenttdistribution() [1/2]
static double alglib.studenttdistr.invstudenttdistribution (int k, double p) inline static
References alglib.ap.assert(), alglib.ibetaf.invincompletebeta(), and alglib.math.maxrealnumber.
Referenced by alglib.invstudenttdistribution().
studenttdistribution() [2/2]
static double alglib.studenttdistr.studenttdistribution (int k, double t) inline static
References alglib.ap.assert(), alglib.ibetaf.incompletebeta(), and alglib.math.machineepsilon.
invstudenttdistribution() [2/2]
static double alglib.studenttdistr.invstudenttdistribution (int k, double p) inline static
References alglib.ap.assert(), alglib.ibetaf.invincompletebeta(), and alglib.math.maxrealnumber.
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/specialfunctions.cs