Doc: IGLib EXTENDED: IG.Lib.XmlUtilityBase Class Reference
IG.Lib.XmlUtilityBase Class Reference
Base class for various utilities operating on XmlDocumnt.
Public Member Functions
virtual void Load (string filename)
virtual void LoadXml (string docstr)
virtual void SetDocument (XmlDataDocument doc)
virtual void Load (string filename)
Loads an Xml document from a file.
virtual void LoadXml (string docstr)
Loads Xml document from a string.
virtual void LoadXml (XmlDocument doc)
Loads Xml document.
Static Public Member Functions
static string GetDefaultNameSpaceUri (XmlElement element)
Gets the default namespace URI if defined, for the specified Xml element.
static string GetDefaultNameSpaceUri (XmlDocument doc)
Gets the default namespace URI of teh Xml document.
static string GetDefaultNameSpaceUri (XmlNode node)
Returns the default namespace URI that applies to the specified Xml node.
static string GetNameSpaceUri (XmlDocument doc, string prefix)
Returns the namespace URI associated with a specific prefix that applies to the specified Xml document.
static string GetNameSpaceUri (XmlNode node, string prefix)
Returns the namespace URI associated with a specific prefix that applies to the specified Xml document.
static string GetDefaultNameSpaceUri (XmlElement element)
Gets the default namespace URI if defined, for the specified Xml element.
static string GetDefaultNameSpaceUri (XmlDocument doc)
Gets the default namespace URI of teh Xml document.
static string GetDefaultNameSpaceUri (XmlNode node)
Returns the default namespace URI that applies to the specified Xml node.
static string GetNameSpaceUri (XmlDocument doc, string prefix)
Returns the namespace URI associated with a specific prefix that applies to the specified Xml document.
static string GetNameSpaceUri (XmlNode node, string prefix)
Returns the namespace URI associated with a specific prefix that applies to the specified Xml document.
Public Attributes
string DefaultNameSpace = null
string DefaultNameSpacePrefix = "defaultnsprefix"
Protected Member Functions
bool ContainedInDocument (XmlNode node, XmlDocument doc)
Returns true if an Xml node is contained in the specified Xml document (false if any is null).
bool ContainedInNode (XmlNode node, XmlNode container)
Returns null if an XML node (first argument) is contained in the specified note (second argument). The node can be contained in another node at an arbitrary depth for the function to return true. If any of the _gridCoordinates is null then the function returns false.
bool ContainedInDocument (XmlNode node, XmlDocument doc)
Returns true if an Xml node is contained in the specified Xml document (false if any is null).
bool ContainedInNode (XmlNode node, XmlNode container)
Returns null if an XML node (first argument) is contained in the specified note (second argument). The node can be contained in another node at an arbitrary depth for the function to return true. If any of the nodes is null then the function returns false.
Properties
virtual IG.Lib.IReporter R [get]
Reporter for this class.
virtual bool HasDefaultNameSpace [get, protected set]
string FileName [get, protected set]
virtual XmlDocument Doc [get, set]
Xml document that represents the message.
XmlNode Root [get, private set]
Root node of the current document.
virtual IReporter R [get]
Reporter for this class.
Static Private Member Functions
static string GetNamespaceAttributeName (string prefix)
static string GetNameSpaceUri0 (XmlElement element, string NamespaceAttributeName)
Gets the namespace URI introduced by a particular attribute, if defined, for the specified Xml element.
static string GetNameSpaceUri (XmlElement element, string prefix)
Returns the namespace URI associated with a specific prefix that applies to the specified Xml element. URI information is obtained from the corresponding attribute of the specified node and eventually its parent _gridCoordinates.
static string GetNamespaceAttributeName (string prefix)
static string GetNameSpaceUri0 (XmlElement element, string NamespaceAttributeName)
Gets the namespace URI introduced by a particular attribute, if defined, for the specified Xml element.
static string GetNameSpaceUri (XmlElement element, string prefix)
Returns the namespace URI associated with a specific prefix that applies to the specified Xml element. URI information is obtained from the corresponding attribute of the specified node and eventually its parent nodes.
Private Attributes
bool _hasDefaultNameSpace = false
string _filename = null
XmlDocument _doc = null
XmlNode _root = null
IReporter _R = null
Static Private Attributes
const string XmlNsAttribute = "xmlns"
Detailed Description
Base class for various utilities operating on XmlDocumnt.
Member Function Documentation
GetDefaultNameSpaceUri() [1/6]
static string IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri (XmlElement element) inline static
Gets the default namespace URI if defined, for the specified Xml element.
Parameters
element
References IG.Lib.XmlUtilityBase.XmlNsAttribute.
Referenced by IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri(), and IG.Lib.XmlUtilityBase.GetNameSpaceUri().
GetDefaultNameSpaceUri() [2/6]
static string IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri (XmlDocument doc) inline static
Gets the default namespace URI of teh Xml document.
Parameters
doc Xml document to which the default namespace might apply.
Returns
Tha default namespace URI that applies to the document, or null if there is no such namespace.
References IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri().
GetDefaultNameSpaceUri() [3/6]
static string IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri (XmlNode node) inline static
Returns the default namespace URI that applies to the specified Xml node.
Parameters
node Xml node to which namespace URI applies.
Returns
The defaulut namespace URI atht applies to the node, or null if there is no default namespace.
References IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri().
GetNamespaceAttributeName() [1/2]
static string IG.Lib.XmlUtilityBase.GetNamespaceAttributeName (string prefix) inline static private
References IG.Lib.XmlUtilityBase.XmlNsAttribute.
Referenced by IG.Lib.XmlUtilityBase.GetNameSpaceUri().
GetNameSpaceUri0() [1/2]
static string IG.Lib.XmlUtilityBase.GetNameSpaceUri0 (XmlElement element, string NamespaceAttributeName) inline static private
Gets the namespace URI introduced by a particular attribute, if defined, for the specified Xml element.
Parameters
element Element for which rhe specific namespace URI is searched for.
NamespaceAttributeName Attribute name that introduces that namespace.
Referenced by IG.Lib.XmlUtilityBase.GetNameSpaceUri(), and IG.Lib.XmlUtilityBase.GetNameSpaceUri0().
GetNameSpaceUri() [1/6]
static string IG.Lib.XmlUtilityBase.GetNameSpaceUri (XmlElement element, string prefix) inline static private
Returns the namespace URI associated with a specific prefix that applies to the specified Xml element. URI information is obtained from the corresponding attribute of the specified node and eventually its parent _gridCoordinates.
Parameters
element Element for which namespace URI is searched for.
prefix Prefix for which teh namespace is searched for. If null or empty string then a default namespace URI is searched for.
Returns
The namespace URI corresponding to the specified prefix at the level of a specified element, or null if the particular namespace URI is not defined.
References IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri(), IG.Lib.XmlUtilityBase.GetNamespaceAttributeName(), and IG.Lib.XmlUtilityBase.GetNameSpaceUri0().
Referenced by IG.Lib.XmlUtilityBase.GetNameSpaceUri().
GetNameSpaceUri() [2/6]
static string IG.Lib.XmlUtilityBase.GetNameSpaceUri (XmlDocument doc, string prefix) inline static
Returns the namespace URI associated with a specific prefix that applies to the specified Xml document.
Parameters
doc Xml document to which namespace URI applies.
prefix Prefix.
Returns
The namespace URI if found, null otherwise.
References IG.Lib.XmlUtilityBase.GetNameSpaceUri().
GetNameSpaceUri() [3/6]
static string IG.Lib.XmlUtilityBase.GetNameSpaceUri (XmlNode node, string prefix) inline static
Returns the namespace URI associated with a specific prefix that applies to the specified Xml document.
Parameters
node Xml node to which namespace URI applies.
prefix Prefix.
Returns
The namespace URI if found, null otherwise.
References IG.Lib.XmlUtilityBase.GetNameSpaceUri().
Load() [1/2]
virtual void IG.Lib.XmlUtilityBase.Load (string filename) inline virtual
References IG.Lib.IReporterBase.Depth, IG.Lib.XmlUtilityBase.Doc, IG.Lib.XmlUtilityBase.FileName, IG.Lib.XmlUtilityBase.R, IG.Lib.IReporterBase.ReportInfo(), and IG.Lib.IReporterBase.TreatInfo.
Referenced by IG.Lib.ParsableXmlObject.Load().
LoadXml() [1/3]
virtual void IG.Lib.XmlUtilityBase.LoadXml (string docstr) inline virtual
References IG.Lib.IReporterBase.Depth, IG.Lib.XmlUtilityBase.Doc, IG.Lib.XmlUtilityBase.FileName, IG.Lib.XmlUtilityBase.R, IG.Lib.IReporterBase.ReportInfo(), and IG.Lib.IReporterBase.TreatInfo.
Referenced by IG.Lib.ParsableXmlObject.CreateXml(), IG.Lib.MsgBase.GetMessageType(), IG.Lib.ParsableXmlObject.LoadXml(), IG.Lib.MsgObervationOrder.PrepareOoNullify(), IG.Lib.MsgObervationOrder.PrepareOoResponse(), IG.Lib.MsgBase.SetMessageReceiver(), and IG.Lib.MsgObervationOrder.SetOoAction().
ContainedInDocument() [1/2]
bool IG.Lib.XmlUtilityBase.ContainedInDocument (XmlNode node, XmlDocument doc) inline protected
Returns true if an Xml node is contained in the specified Xml document (false if any is null).
Referenced by IG.Lib.XmlParser.MoveTo().
ContainedInNode() [1/2]
bool IG.Lib.XmlUtilityBase.ContainedInNode (XmlNode node, XmlNode container) inline protected
Returns null if an XML node (first argument) is contained in the specified note (second argument). The node can be contained in another node at an arbitrary depth for the function to return true. If any of the _gridCoordinates is null then the function returns false.
Parameters
node Node that might be contained in another node.
container The node that might contain another node.
Returns
true if container contains node, false othwrwise.
Referenced by IG.Lib.XmlBuilder.RemoveNode().
GetDefaultNameSpaceUri() [4/6]
static string IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri (XmlElement element) inline static
Gets the default namespace URI if defined, for the specified Xml element.
Parameters
element
References IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri(), and IG.Lib.XmlUtilityBase.XmlNsAttribute.
GetDefaultNameSpaceUri() [5/6]
static string IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri (XmlDocument doc) inline static
Gets the default namespace URI of teh Xml document.
Parameters
doc Xml document to which the default namespace might apply.
Returns
Tha default namespace URI that applies to the document, or null if there is no such namespace.
References IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri().
GetDefaultNameSpaceUri() [6/6]
static string IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri (XmlNode node) inline static
Returns the default namespace URI that applies to the specified Xml node.
Parameters
node Xml node to which namespace URI applies.
Returns
The defaulut namespace URI atht applies to the node, or null if there is no default namespace.
References IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri().
GetNamespaceAttributeName() [2/2]
static string IG.Lib.XmlUtilityBase.GetNamespaceAttributeName (string prefix) inline static private
References IG.Lib.XmlUtilityBase.XmlNsAttribute.
GetNameSpaceUri0() [2/2]
static string IG.Lib.XmlUtilityBase.GetNameSpaceUri0 (XmlElement element, string NamespaceAttributeName) inline static private
Gets the namespace URI introduced by a particular attribute, if defined, for the specified Xml element.
Parameters
element Element for which rhe specific namespace URI is searched for.
NamespaceAttributeName Attribute name that introduces that namespace.
References IG.Lib.XmlUtilityBase.GetNameSpaceUri0().
GetNameSpaceUri() [4/6]
static string IG.Lib.XmlUtilityBase.GetNameSpaceUri (XmlElement element, string prefix) inline static private
Returns the namespace URI associated with a specific prefix that applies to the specified Xml element. URI information is obtained from the corresponding attribute of the specified node and eventually its parent nodes.
Parameters
element Element for which namespace URI is searched for.
prefix Prefix for which teh namespace is searched for. If null or empty string then a default namespace URI is searched for.
Returns
The namespace URI corresponding to the specified prefix at the level of a specified element, or null if the particular namespace URI is not defined.
References IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri(), IG.Lib.XmlUtilityBase.GetNamespaceAttributeName(), and IG.Lib.XmlUtilityBase.GetNameSpaceUri0().
GetNameSpaceUri() [5/6]
static string IG.Lib.XmlUtilityBase.GetNameSpaceUri (XmlDocument doc, string prefix) inline static
Returns the namespace URI associated with a specific prefix that applies to the specified Xml document.
Parameters
doc Xml document to which namespace URI applies.
Returns
The namespace URI if found, null otherwise.
References IG.Lib.XmlUtilityBase.GetNameSpaceUri().
GetNameSpaceUri() [6/6]
static string IG.Lib.XmlUtilityBase.GetNameSpaceUri (XmlNode node, string prefix) inline static
Returns the namespace URI associated with a specific prefix that applies to the specified Xml document.
Parameters
node Xml node to which namespace URI applies.
Returns
The namespace URI if found, null otherwise.
References IG.Lib.XmlUtilityBase.GetNameSpaceUri().
SetDocument()
virtual void IG.Lib.XmlUtilityBase.SetDocument (XmlDataDocument doc) inline virtual
References IG.Lib.IReporterBase.Depth, IG.Lib.XmlUtilityBase.Doc, IG.Lib.XmlUtilityBase.FileName, IG.Lib.XmlUtilityBase.R, IG.Lib.IReporterBase.ReportInfo(), and IG.Lib.IReporterBase.TreatInfo.
Load() [2/2]
virtual void IG.Lib.XmlUtilityBase.Load (string filename) inline virtual
Loads an Xml document from a file.
Parameters
filename Name of the file from which XML document is loaded.
References IG.Lib.IReporterBase.Depth, IG.Lib.XmlUtilityBase.Doc, IG.Lib.XmlUtilityBase.FileName, IG.Lib.XmlUtilityBase.R, IG.Lib.IReporterBase.ReportInfo(), and IG.Lib.IReporterBase.TreatInfo.
LoadXml() [2/3]
virtual void IG.Lib.XmlUtilityBase.LoadXml (string docstr) inline virtual
Loads Xml document from a string.
Parameters
docstr String containing the XML document.
References IG.Lib.IReporterBase.Depth, IG.Lib.XmlUtilityBase.Doc, IG.Lib.XmlUtilityBase.FileName, IG.Lib.XmlUtilityBase.R, IG.Lib.IReporterBase.ReportInfo(), and IG.Lib.IReporterBase.TreatInfo.
LoadXml() [3/3]
virtual void IG.Lib.XmlUtilityBase.LoadXml (XmlDocument doc) inline virtual
Loads Xml document.
Parameters
doc XML document that is loaded.
References IG.Lib.IReporterBase.Depth, IG.Lib.XmlUtilityBase.Doc, IG.Lib.XmlUtilityBase.FileName, IG.Lib.XmlUtilityBase.R, IG.Lib.IReporterBase.ReportInfo(), and IG.Lib.IReporterBase.TreatInfo.
ContainedInDocument() [2/2]
bool IG.Lib.XmlUtilityBase.ContainedInDocument (XmlNode node, XmlDocument doc) inline protected
Returns true if an Xml node is contained in the specified Xml document (false if any is null).
ContainedInNode() [2/2]
bool IG.Lib.XmlUtilityBase.ContainedInNode (XmlNode node, XmlNode container) inline protected
Returns null if an XML node (first argument) is contained in the specified note (second argument). The node can be contained in another node at an arbitrary depth for the function to return true. If any of the nodes is null then the function returns false.
Parameters
node Node that might be contained in another node.
container The node that might contain another node.
Returns
true if container contains node, false othwrwise.
Member Data Documentation
_hasDefaultNameSpace
bool IG.Lib.XmlUtilityBase._hasDefaultNameSpace = false private
DefaultNameSpace
string IG.Lib.XmlUtilityBase.DefaultNameSpace = null
DefaultNameSpacePrefix
string IG.Lib.XmlUtilityBase.DefaultNameSpacePrefix = "defaultnsprefix"
XmlNsAttribute
const string IG.Lib.XmlUtilityBase.XmlNsAttribute = "xmlns" static private
Referenced by IG.Lib.XmlUtilityBase.GetDefaultNameSpaceUri(), and IG.Lib.XmlUtilityBase.GetNamespaceAttributeName().
_filename
string IG.Lib.XmlUtilityBase._filename = null private
_doc
XmlDocument IG.Lib.XmlUtilityBase._doc = null private
_root
XmlNode IG.Lib.XmlUtilityBase._root = null private
_R
IReporter IG.Lib.XmlUtilityBase._R = null private
Property Documentation
R [1/2]
virtual IG.Lib.IReporter IG.Lib.XmlUtilityBase.R get
Reporter for this class.
Referenced by IG.Lib.XmlBuilder.AppendChild(), IG.Lib.XmlBuilder.CreateClone(), IG.Lib.XmlBuilder.CreateNode(), IG.Lib.XmlBuilder.InsertAfter(), IG.Lib.XmlBuilder.InsertBefore(), IG.Lib.XmlUtilityBase.Load(), IG.Lib.XmlUtilityBase.LoadXml(), IG.Lib.XmlParser.MoveTo(), IG.Lib.XmlBuilder.MoveToNewest(), IG.Lib.XmlBuilder.PrependChild(), IG.Lib.XmlBuilder.RemoveNode(), IG.Lib.XmlBuilder.SetAttribute(), IG.Lib.XmlUtilityBase.SetDocument(), IG.Lib.XmlBuilder.SetInnerText(), IG.Lib.XmlBuilder.SetInnerXml(), IG.Lib.XmlParser.SetMark(), and IG.Lib.XmlBuilder.SetValue().
HasDefaultNameSpace
bool IG.Lib.XmlUtilityBase.HasDefaultNameSpace get protected set
FileName
string IG.Lib.XmlUtilityBase.FileName get protected set
Referenced by IG.Lib.XmlUtilityBase.Load(), IG.Lib.XmlUtilityBase.LoadXml(), and IG.Lib.XmlUtilityBase.SetDocument().
Doc
XmlDocument IG.Lib.XmlUtilityBase.Doc get set
Xml document that represents the message.
Xml document that represents the msg.
Referenced by IG.Lib.XmlUtilityBase.Load(), IG.Lib.XmlUtilityBase.LoadXml(), and IG.Lib.XmlUtilityBase.SetDocument().
Root
XmlNode IG.Lib.XmlUtilityBase.Root get private set
Root node of the current document.
Referenced by IG.Lib.XmlBuilder.AddProcessingInstruction(), IG.Lib.XmlParser.GetNode(), and IG.Lib.XmlParser.GoToRoot().
R [2/2]
virtual IReporter IG.Lib.XmlUtilityBase.R get
Reporter for this class.
The documentation for this class was generated from the following files:
iglib/igbase/0unsorted/XmlUtilities.cs
igtest/tmp_prem/prlab/LabexBis/MessagesBis.cs