Doc: IGLib EXTENDED: IG.Neural.Applications.ProgramNeurApp Class Reference
IG.Neural.Applications.ProgramNeurApp Class Reference
Properties
static NeurApp App [get]
Application driver.
Static Private Member Functions
static void Main (string[] args)
Member Function Documentation
Main()
static void IG.Neural.Applications.ProgramNeurApp.Main (string[] args) inline static private
References IG.Neural.Applications.ProgramNeurApp.App, IG.Lib.UtilConsole.HideConsoleWindow(), IG.Neural.Applications.NeurApp.Init(), IG.Neural.Applications.NeurApp.IsDevelopMode, IG.Neural.Applications.NeurApp.IsNormalMode, IG.Neural.Applications.NeurApp.IsOld1dMode, IG.Neural.Applications.NeurApp.IsOld2dMode, IG.Neural.Applications.NeurApp.IsOldMode, IG.Neural.Applications.NeurApp.IsVerbose, and IG.Neural.Applications.NeuralDemo.Run().
Property Documentation
App
NeurApp IG.Neural.Applications.ProgramNeurApp.App static get
Application driver.
Referenced by IG.Neural.Applications.ProgramNeurApp.Main().
The documentation for this class was generated from the following file:
shelldev/extensions/ExtAppNeurApp/ProgramNeurapp.cs