Doc: IGLib EXTENDED: NUnit.Engine.Api.Tests.ServiceLocatorTests Class Reference
NUnit.Engine.Api.Tests.ServiceLocatorTests Class Reference
Public Member Functions
void CreateEngine ()
void CanAccessService (Type serviceType)
Private Attributes
ITestEngine _testEngine
Member Function Documentation
CreateEngine()
void NUnit.Engine.Api.Tests.ServiceLocatorTests.CreateEngine () inline
References NUnit.Engine.Api.Tests.ServiceLocatorTests._testEngine, and NUnit.Engine.ITestEngine.InternalTraceLevel.
CanAccessService()
void NUnit.Engine.Api.Tests.ServiceLocatorTests.CanAccessService (Type serviceType) inline
References NUnit.Engine.Api.Tests.ServiceLocatorTests._testEngine, NUnit.Framework.Is.EqualTo(), NUnit.Engine.IServiceLocator.GetService(), NUnit.Framework.Is.InstanceOf(), NUnit.Framework.Assert.NotNull(), NUnit.Engine.ITestEngine.Services, NUnit.Engine.IService.Status, and NUnit.Framework.Assert.That().
Member Data Documentation
_testEngine
ITestEngine NUnit.Engine.Api.Tests.ServiceLocatorTests._testEngine private
Referenced by NUnit.Engine.Api.Tests.ServiceLocatorTests.CanAccessService(), and NUnit.Engine.Api.Tests.ServiceLocatorTests.CreateEngine().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Api/ServiceLocatorTests.cs