Doc: IGLib EXTENDED: CShell.Framework.Controls.AutoGreyableImage Class Reference
CShell.Framework.Controls.AutoGreyableImage Class Reference
Class used to have an image that is able to be gray when the control is not enabled. Author: Thomas LEBRUN (http://blogs.developpeur.org/tom)
Static Private Member Functions
static AutoGreyableImage ()
Initializes a new instance of the AutoGreyableImage class.
static void OnAutoGreyScaleImageIsEnabledPropertyChanged (DependencyObject source, DependencyPropertyChangedEventArgs args)
Called when [auto grey scale image is enabled property changed].
Detailed Description
Class used to have an image that is able to be gray when the control is not enabled. Author: Thomas LEBRUN (http://blogs.developpeur.org/tom)
Constructor & Destructor Documentation
AutoGreyableImage()
static CShell.Framework.Controls.AutoGreyableImage.AutoGreyableImage () inline static private
Initializes a new instance of the AutoGreyableImage class.
References CShell.Framework.Controls.AutoGreyableImage.OnAutoGreyScaleImageIsEnabledPropertyChanged().
Referenced by CShell.Framework.Controls.AutoGreyableImage.OnAutoGreyScaleImageIsEnabledPropertyChanged().
Member Function Documentation
OnAutoGreyScaleImageIsEnabledPropertyChanged()
static void CShell.Framework.Controls.AutoGreyableImage.OnAutoGreyScaleImageIsEnabledPropertyChanged (DependencyObject source, DependencyPropertyChangedEventArgs args) inline static private
Called when [auto grey scale image is enabled property changed].
Parameters
source The source.
args The System.Windows.DependencyPropertyChangedEventArgs instance containing the event data.
References CShell.Framework.Controls.AutoGreyableImage.AutoGreyableImage().
Referenced by CShell.Framework.Controls.AutoGreyableImage.AutoGreyableImage().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore/Framework/Controls/AutoGreyableImage.cs