Doc: IGLib EXTENDED: AForge.Video.Kinect.KinectDepthCamera Class Reference
AForge.Video.Kinect.KinectDepthCamera Class Reference
Video source for Microsoft Kinect's depth sensor.
Public Member Functions
KinectDepthCamera (int deviceID)
Initializes a new instance of the KinectDepthCamera class.
KinectDepthCamera (int deviceID, CameraResolution resolution)
Initializes a new instance of the KinectDepthCamera class.
KinectDepthCamera (int deviceID, CameraResolution resolution, bool provideOriginalDepthImage)
Initializes a new instance of the KinectDepthCamera class.
void Start ()
Start video source.
void SignalToStop ()
Signal video source to stop its work.
void WaitForStop ()
Wait for video source has stopped.
void Stop ()
Stop video source.
Properties
bool ProvideOriginalDepthImage [get, set]
Provide original depth image or colored depth map.
CameraResolution Resolution [get, set]
Resolution of depth sensor to set.
virtual string Source [get]
A string identifying the video source.
bool IsRunning [get]
State of the video source.
long BytesReceived [get]
Received bytes count.
int FramesReceived [get]
Received frames count.
Properties inherited from AForge.Video.IVideoSource
string Source [get]
Video source.
int FramesReceived [get]
Received frames count.
long BytesReceived [get]
Received bytes count.
bool IsRunning [get]
State of the video source.
Events
NewFrameEventHandler NewFrame
New frame event.
VideoSourceErrorEventHandler VideoSourceError
Video source error event.
PlayingFinishedEventHandler PlayingFinished
Video playing finished event.
Events inherited from AForge.Video.IVideoSource
NewFrameEventHandler NewFrame
New frame event.
VideoSourceErrorEventHandler VideoSourceError
Video source error event.
PlayingFinishedEventHandler PlayingFinished
Video playing finished event.
Private Member Functions
void HandleDataReceived (IntPtr device, IntPtr depthData, UInt32 timestamp)
Private Attributes
int deviceID
int framesReceived
long bytesReceived
bool provideOriginalDepthImage = false
ushort[] gamma = new ushort[2048]
CameraResolution resolution = CameraResolution.Medium
object sync = new object()
Kinect device = null
IntPtr imageBuffer = IntPtr.Zero
KinectNative.BitmapInfoHeader depthModeInfo
KinectNative.FreenectDepthDataCallback videoCallback = null
Static Private Attributes
static List< int > runningCameras = new List<int>()
Detailed Description
Video source for Microsoft Kinect's depth sensor.
The video source captures depth data from Microsoft Kinect depth sensor, which is aimed originally as a gaming device for XBox 360 platform.
<note>Prior to using the class, make sure you've installed Kinect's drivers as described on Open Kinect project's page.</note>
<note>In order to run correctly the class requires freenect.dll library to be put into solution's output folder. This can be found within the AForge.NET framework's distribution in Externals folder.</note>
Sample usage:
// create video source
KinectDepthCamera videoSource = new KinectDepthCamera(0);
// set NewFrame event handler
videoSource.NewFrame += new NewFrameEventHandler(video_NewFrame);
// start the video source
videoSource.Start();
// ...
private void video_NewFrame(object sender, NewFrameEventArgs eventArgs)
{
    // get new frame
    Bitmap bitmap = eventArgs.Frame;
    // process the frame
}
Constructor & Destructor Documentation
KinectDepthCamera() [1/3]
AForge.Video.Kinect.KinectDepthCamera.KinectDepthCamera (int deviceID) inline
Initializes a new instance of the KinectDepthCamera class.
Parameters
deviceID Kinect's device ID (index) to connect to.
References AForge.Video.Kinect.Medium.
KinectDepthCamera() [2/3]
AForge.Video.Kinect.KinectDepthCamera.KinectDepthCamera (int deviceID, CameraResolution resolution) inline
Initializes a new instance of the KinectDepthCamera class.
Parameters
deviceID Kinect's device ID (index) to connect to.
resolution Resolution of depth sensor to set.
KinectDepthCamera() [3/3]
AForge.Video.Kinect.KinectDepthCamera.KinectDepthCamera (int deviceID, CameraResolution resolution, bool provideOriginalDepthImage) inline
Initializes a new instance of the KinectDepthCamera class.
Parameters
deviceID Kinect's device ID (index) to connect to.
resolution Resolution of depth sensor to set.
provideOriginalDepthImage Provide original depth image or colored depth map (see ProvideOriginalDepthImage property).
References AForge.Video.Kinect.KinectDepthCamera.deviceID, AForge.Video.Kinect.KinectDepthCamera.gamma, AForge.Video.Kinect.KinectDepthCamera.provideOriginalDepthImage, and AForge.Video.Kinect.KinectDepthCamera.resolution.
Member Function Documentation
Start()
void AForge.Video.Kinect.KinectDepthCamera.Start () inline
Start video source.
Starts video source and returns execution to caller. Video camera will be started and will provide new video frames through the NewFrame event.
Exceptions
ArgumentException The specified resolution is not supported for the selected mode of the Kinect depth sensor.
ConnectionFailedException Could not connect to Kinect's depth sensor.
DeviceBusyException Another connection to the specified depth sensor is already running.
Implements AForge.Video.IVideoSource.
References AForge.Video.Kinect.KinectDepthCamera.depthModeInfo, AForge.Video.Kinect.KinectDepthCamera.device, AForge.Video.Kinect.KinectDepthCamera.deviceID, AForge.Video.Kinect.Kinect.Dispose(), AForge.Video.Kinect.Kinect.GetDevice(), AForge.Video.Kinect.KinectDepthCamera.HandleDataReceived(), AForge.Video.Kinect.KinectDepthCamera.imageBuffer, AForge.Video.Kinect.KinectDepthCamera.resolution, AForge.Video.Kinect.KinectDepthCamera.runningCameras, AForge.Video.Kinect.KinectDepthCamera.Stop(), AForge.Video.Kinect.KinectDepthCamera.sync, and AForge.Video.Kinect.KinectDepthCamera.videoCallback.
SignalToStop()
void AForge.Video.Kinect.KinectDepthCamera.SignalToStop () inline
Signal video source to stop its work.
<note>Calling this method is equivalent to calling Stop for Kinect video camera.</note>
Implements AForge.Video.IVideoSource.
References AForge.Video.Kinect.KinectDepthCamera.Stop().
WaitForStop()
void AForge.Video.Kinect.KinectDepthCamera.WaitForStop () inline
Wait for video source has stopped.
<note>Calling this method is equivalent to calling Stop for Kinect video camera.</note>
Implements AForge.Video.IVideoSource.
References AForge.Video.Kinect.KinectDepthCamera.Stop().
Stop()
void AForge.Video.Kinect.KinectDepthCamera.Stop () inline
Stop video source.
The method stop the video source, so it no longer provides new video frames and does not consume any resources.
Implements AForge.Video.IVideoSource.
References AForge.Video.Kinect.KinectDepthCamera.device, AForge.Video.Kinect.KinectDepthCamera.deviceID, AForge.Video.Kinect.Kinect.Dispose(), AForge.Video.Kinect.KinectDepthCamera.imageBuffer, AForge.Video.Kinect.KinectDepthCamera.PlayingFinished, AForge.Video.Kinect.KinectDepthCamera.runningCameras, AForge.Video.Kinect.KinectDepthCamera.sync, and AForge.Video.Kinect.KinectDepthCamera.videoCallback.
Referenced by KinectCapture.MainForm.Disconnect(), AForge.Video.Kinect.KinectDepthCamera.SignalToStop(), AForge.Video.Kinect.KinectDepthCamera.Start(), and AForge.Video.Kinect.KinectDepthCamera.WaitForStop().
HandleDataReceived()
void AForge.Video.Kinect.KinectDepthCamera.HandleDataReceived (IntPtr device, IntPtr depthData, UInt32 timestamp) inline private
References AForge.Video.Kinect.KinectDepthCamera.bytesReceived, AForge.SystemTools.CopyUnmanagedMemory(), AForge.Video.Kinect.KinectDepthCamera.depthModeInfo, AForge.Video.Kinect.KinectDepthCamera.framesReceived, AForge.Video.Kinect.KinectDepthCamera.gamma, AForge.Video.Kinect.KinectDepthCamera.imageBuffer, AForge.Video.Kinect.KinectDepthCamera.NewFrame, AForge.Video.Kinect.KinectDepthCamera.provideOriginalDepthImage, AForge.Math.Geometry.Rectangle, and AForge.Video.Kinect.KinectDepthCamera.VideoSourceError.
Referenced by AForge.Video.Kinect.KinectDepthCamera.Start().
Member Data Documentation
deviceID
int AForge.Video.Kinect.KinectDepthCamera.deviceID private
Referenced by AForge.Video.Kinect.KinectDepthCamera.KinectDepthCamera(), AForge.Video.Kinect.KinectDepthCamera.Start(), and AForge.Video.Kinect.KinectDepthCamera.Stop().
framesReceived
int AForge.Video.Kinect.KinectDepthCamera.framesReceived private
Referenced by AForge.Video.Kinect.KinectDepthCamera.HandleDataReceived().
bytesReceived
long AForge.Video.Kinect.KinectDepthCamera.bytesReceived private
Referenced by AForge.Video.Kinect.KinectDepthCamera.HandleDataReceived().
provideOriginalDepthImage
bool AForge.Video.Kinect.KinectDepthCamera.provideOriginalDepthImage = false private
Referenced by AForge.Video.Kinect.KinectDepthCamera.HandleDataReceived(), and AForge.Video.Kinect.KinectDepthCamera.KinectDepthCamera().
gamma
ushort [] AForge.Video.Kinect.KinectDepthCamera.gamma = new ushort[2048] private
Referenced by AForge.Video.Kinect.KinectDepthCamera.HandleDataReceived(), and AForge.Video.Kinect.KinectDepthCamera.KinectDepthCamera().
resolution
CameraResolution AForge.Video.Kinect.KinectDepthCamera.resolution = CameraResolution.Medium private
Referenced by AForge.Video.Kinect.KinectDepthCamera.KinectDepthCamera(), and AForge.Video.Kinect.KinectDepthCamera.Start().
runningCameras
List<int> AForge.Video.Kinect.KinectDepthCamera.runningCameras = new List<int>() static private
Referenced by AForge.Video.Kinect.KinectDepthCamera.Start(), and AForge.Video.Kinect.KinectDepthCamera.Stop().
sync
object AForge.Video.Kinect.KinectDepthCamera.sync = new object() private
Referenced by AForge.Video.Kinect.KinectDepthCamera.Start(), and AForge.Video.Kinect.KinectDepthCamera.Stop().
device
Kinect AForge.Video.Kinect.KinectDepthCamera.device = null private
Referenced by AForge.Video.Kinect.KinectDepthCamera.Start(), and AForge.Video.Kinect.KinectDepthCamera.Stop().
imageBuffer
IntPtr AForge.Video.Kinect.KinectDepthCamera.imageBuffer = IntPtr.Zero private
Referenced by AForge.Video.Kinect.KinectDepthCamera.HandleDataReceived(), AForge.Video.Kinect.KinectDepthCamera.Start(), and AForge.Video.Kinect.KinectDepthCamera.Stop().
depthModeInfo
KinectNative.BitmapInfoHeader AForge.Video.Kinect.KinectDepthCamera.depthModeInfo private
Referenced by AForge.Video.Kinect.KinectDepthCamera.HandleDataReceived(), and AForge.Video.Kinect.KinectDepthCamera.Start().
videoCallback
KinectNative.FreenectDepthDataCallback AForge.Video.Kinect.KinectDepthCamera.videoCallback = null private
Referenced by AForge.Video.Kinect.KinectDepthCamera.Start(), and AForge.Video.Kinect.KinectDepthCamera.Stop().
Property Documentation
ProvideOriginalDepthImage
bool AForge.Video.Kinect.KinectDepthCamera.ProvideOriginalDepthImage get set private
Provide original depth image or colored depth map.
The property specifies if the video source should provide original data provided by Kinect's depth sensor or provide colored depth map. If the property is set to true, then the video source will provide 16 bpp grayscale images, where 11 least significant bits represent data provided by the sensor. If the property is set to false, then the video source will provide 24 bpp color images, which represents depth map. In this case depth is encoded by color gradient: white->red->yellow->green->cyan->blue->black. So colors which are closer to white represent objects which are closer to the Kinect sensor, but colors which are closer to black represent objects which are further away from Kinect.
<note>The property must be set before running the video source to take effect.</note>
Default value is set to false.
Resolution
CameraResolution AForge.Video.Kinect.KinectDepthCamera.Resolution get set
Resolution of depth sensor to set.
<note>The property must be set before running the video source to take effect.</note>
Default value of the property is set to CameraResolution.Medium.
Source
virtual string AForge.Video.Kinect.KinectDepthCamera.Source get
A string identifying the video source.
IsRunning
bool AForge.Video.Kinect.KinectDepthCamera.IsRunning get
State of the video source.
Current state of video source object - running or not.
BytesReceived
long AForge.Video.Kinect.KinectDepthCamera.BytesReceived get
Received bytes count.
Number of bytes the video source provided from the moment of the last access to the property.
FramesReceived
int AForge.Video.Kinect.KinectDepthCamera.FramesReceived get
Received frames count.
Number of frames the video source provided from the moment of the last access to the property.
Event Documentation
NewFrame
NewFrameEventHandler AForge.Video.Kinect.KinectDepthCamera.NewFrame
New frame event.
Notifies clients about new available frames from the video source.
<note>Since video source may have multiple clients, each client is responsible for making a copy (cloning) of the passed video frame, because the video source disposes its own original copy after notifying of clients.</note>
Referenced by AForge.Video.Kinect.KinectDepthCamera.HandleDataReceived().
VideoSourceError
VideoSourceErrorEventHandler AForge.Video.Kinect.KinectDepthCamera.VideoSourceError
Video source error event.
This event is used to notify clients about any type of errors occurred in video source object, for example internal exceptions.
Referenced by AForge.Video.Kinect.KinectDepthCamera.HandleDataReceived().
PlayingFinished
PlayingFinishedEventHandler AForge.Video.Kinect.KinectDepthCamera.PlayingFinished
Video playing finished event.
This event is used to notify clients that the video playing has finished.
Referenced by AForge.Video.Kinect.KinectDepthCamera.Stop().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Video.Kinect/KinectDepthCamera.cs