Doc: IGLib EXTENDED: NUnit.Framework.Internal.Filters.TestFilterXmlTests Class Reference
NUnit.Framework.Internal.Filters.TestFilterXmlTests Class Reference
Public Member Functions
void ClassNameFilter_FromXml ()
void ClassNameFilter_ToXml ()
void ClassNameFilter_FromXml_Regex ()
void ClassNameFilter_ToXml_Regex ()
void MethodNameFilter_FromXml ()
void MethodNameFilter_ToXml ()
void BuildMethodNameFilter_FromXml_Regex ()
void MethodNameFilter_ToXml_Regex ()
void TestNameFilter_FromXml ()
void TestNameFilter_ToXml ()
void TestNameFilter_FromXml_Regex ()
void TestNameFilter_ToXml_Regex ()
void FullNameFilter_FromXml ()
void FullNameFilter_ToXml ()
void FullNameFilter_FromXml_Regex ()
void FullNameFilter_ToXml_Regex ()
void CategoryFilter_FromXml ()
void CategoryFilter_ToXml ()
void CategoryFilter_FromXml_Regex ()
void CategoryFilter_ToXml_Regex ()
void PropertyFilter_FromXml ()
void PropertyFilter_ToXml ()
void PropertyFilter_FromXml_Regex ()
void PropertyFilter_ToXml_Regex ()
void IdFilter_FromXml ()
void IdFilter_ToXml ()
Public Member Functions inherited from NUnit.Framework.Internal.Filters.TestFilterTests
void SetUpSuite ()
Additional Inherited Members
Static Public Attributes inherited from NUnit.Framework.Internal.Filters.TestFilterTests
const string DUMMY_CLASS = "NUnit.Framework.Internal.Filters.TestFilterTests+DummyFixture"
Protected Attributes inherited from NUnit.Framework.Internal.Filters.TestFilterTests
readonly TestSuite _dummyFixture = TestBuilder.MakeFixture(typeof(DummyFixture))
readonly TestSuite _anotherFixture = TestBuilder.MakeFixture(typeof(AnotherFixture))
readonly TestSuite _yetAnotherFixture = TestBuilder.MakeFixture(typeof(YetAnotherFixture))
readonly TestSuite _fixtureWithMultipleTests = TestBuilder.MakeFixture (typeof (FixtureWithMultipleTests))
readonly TestSuite _topLevelSuite = new TestSuite("MySuite")
Member Function Documentation
ClassNameFilter_FromXml()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_FromXml () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Internal.Filters.TestFilterTests.DUMMY_CLASS, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Internal.TestFilter.Match(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
ClassNameFilter_ToXml()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_ToXml () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.TNode.OuterXml, NUnit.Framework.Assert.That(), and NUnit.Framework.Internal.TestFilter.ToXml().
ClassNameFilter_FromXml_Regex()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_FromXml_Regex () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Internal.TestFilter.Match(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
ClassNameFilter_ToXml_Regex()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_ToXml_Regex () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.TNode.OuterXml, NUnit.Framework.Assert.That(), and NUnit.Framework.Internal.TestFilter.ToXml().
MethodNameFilter_FromXml()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.MethodNameFilter_FromXml () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Internal.Filters.TestFilterTests._fixtureWithMultipleTests, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Internal.TestFilter.Match(), NUnit.Framework.Internal.TestSuite.Tests, NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
MethodNameFilter_ToXml()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.MethodNameFilter_ToXml () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.TNode.OuterXml, NUnit.Framework.Assert.That(), and NUnit.Framework.Internal.TestFilter.ToXml().
BuildMethodNameFilter_FromXml_Regex()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.BuildMethodNameFilter_FromXml_Regex () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Internal.Filters.TestFilterTests._fixtureWithMultipleTests, NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Internal.TestFilter.Match(), NUnit.Framework.Internal.TestSuite.Tests, NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
MethodNameFilter_ToXml_Regex()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.MethodNameFilter_ToXml_Regex () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.TNode.OuterXml, NUnit.Framework.Assert.That(), and NUnit.Framework.Internal.TestFilter.ToXml().
TestNameFilter_FromXml()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_FromXml () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Internal.TestFilter.Match(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
TestNameFilter_ToXml()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_ToXml () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.TNode.OuterXml, NUnit.Framework.Assert.That(), and NUnit.Framework.Internal.TestFilter.ToXml().
TestNameFilter_FromXml_Regex()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_FromXml_Regex () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Internal.TestFilter.Match(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
TestNameFilter_ToXml_Regex()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_ToXml_Regex () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.TNode.OuterXml, NUnit.Framework.Assert.That(), and NUnit.Framework.Internal.TestFilter.ToXml().
FullNameFilter_FromXml()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_FromXml () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Internal.Filters.TestFilterTests.DUMMY_CLASS, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Internal.TestFilter.Match(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
FullNameFilter_ToXml()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_ToXml () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.TNode.OuterXml, NUnit.Framework.Assert.That(), and NUnit.Framework.Internal.TestFilter.ToXml().
FullNameFilter_FromXml_Regex()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_FromXml_Regex () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Internal.TestFilter.Match(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
FullNameFilter_ToXml_Regex()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_ToXml_Regex () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.TNode.OuterXml, NUnit.Framework.Assert.That(), and NUnit.Framework.Internal.TestFilter.ToXml().
CategoryFilter_FromXml()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_FromXml () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Internal.TestFilter.Match(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
CategoryFilter_ToXml()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_ToXml () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.TNode.OuterXml, NUnit.Framework.Assert.That(), and NUnit.Framework.Internal.TestFilter.ToXml().
CategoryFilter_FromXml_Regex()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_FromXml_Regex () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Internal.TestFilter.Match(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
CategoryFilter_ToXml_Regex()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_ToXml_Regex () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.TNode.OuterXml, NUnit.Framework.Assert.That(), and NUnit.Framework.Internal.TestFilter.ToXml().
PropertyFilter_FromXml()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_FromXml () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Internal.Filters.TestFilterTests._yetAnotherFixture, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Internal.TestFilter.Match(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
PropertyFilter_ToXml()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_ToXml () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.TNode.OuterXml, NUnit.Framework.Assert.That(), and NUnit.Framework.Internal.TestFilter.ToXml().
PropertyFilter_FromXml_Regex()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_FromXml_Regex () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Internal.Filters.TestFilterTests._yetAnotherFixture, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Internal.TestFilter.Match(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
PropertyFilter_ToXml_Regex()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_ToXml_Regex () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.TNode.OuterXml, NUnit.Framework.Assert.That(), and NUnit.Framework.Internal.TestFilter.ToXml().
IdFilter_FromXml()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.IdFilter_FromXml () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Internal.Test.Id, NUnit.Framework.Internal.TestFilter.Match(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
IdFilter_ToXml()
void NUnit.Framework.Internal.Filters.TestFilterXmlTests.IdFilter_ToXml () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.TNode.OuterXml, NUnit.Framework.Assert.That(), and NUnit.Framework.Internal.TestFilter.ToXml().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/Filters/TestFilterXmlTests.cs