Doc: IGLib EXTENDED: IG.Forms.ResourceViewerForm Class Reference
IG.Forms.ResourceViewerForm Class Reference
Public Member Functions
ResourceViewerForm ()
ResourceViewerForm ()
ResourceViewerForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
ResourceViewerControl resourceViewerControl1
Constructor & Destructor Documentation
ResourceViewerForm() [1/3]
IG.Forms.ResourceViewerForm.ResourceViewerForm () inline
References IG.Forms.ResourceViewerForm.InitializeComponent().
ResourceViewerForm() [2/3]
IG.Forms.ResourceViewerForm.ResourceViewerForm () inline
References IG.Forms.ResourceViewerForm.InitializeComponent().
ResourceViewerForm() [3/3]
IG.Forms.ResourceViewerForm.ResourceViewerForm () inline
References IG.Forms.ResourceViewerForm.InitializeComponent().
Member Function Documentation
Dispose() [1/3]
override void IG.Forms.ResourceViewerForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ResourceViewerForm.components.
InitializeComponent() [1/3]
void IG.Forms.ResourceViewerForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ResourceViewerForm.resourceViewerControl1.
Referenced by IG.Forms.ResourceViewerForm.ResourceViewerForm().
Dispose() [2/3]
override void IG.Forms.ResourceViewerForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ResourceViewerForm.components.
InitializeComponent() [2/3]
void IG.Forms.ResourceViewerForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ResourceViewerForm.resourceViewerControl1.
Dispose() [3/3]
override void IG.Forms.ResourceViewerForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ResourceViewerForm.components.
InitializeComponent() [3/3]
void IG.Forms.ResourceViewerForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ResourceViewerForm.resourceViewerControl1.
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.ResourceViewerForm.components = null private
Required designer variable.
Referenced by IG.Forms.ResourceViewerForm.Dispose().
resourceViewerControl1
ResourceViewerControl IG.Forms.ResourceViewerForm.resourceViewerControl1 private
Referenced by IG.Forms.ResourceViewerForm.InitializeComponent().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/Viewers/ResourceViewerForm.cs
iglib/igforms/Utilities/Viewers/ResourceViewerForm.Designer.cs