Doc: IGLib EXTENDED: AForge.Math.Geometry.CoplanarPosit Class Reference
AForge.Math.Geometry.CoplanarPosit Class Reference
3D pose estimation algorithm (coplanar case).
Public Member Functions
CoplanarPosit (Vector3[] model, float focalLength)
Initializes a new instance of the Posit class.
void EstimatePose (Point[] points, out Matrix3x3 rotation, out Vector3 translation)
Estimate pose of a model from it's projected 2D coordinates.
Properties
Matrix3x3 BestEstimatedRotation [get]
Best estimated pose recently found.
Vector3 BestEstimatedTranslation [get]
Best estimated translation recently found.
float BestEstimationError [get]
Error of the best pose estimation.
Matrix3x3 AlternateEstimatedRotation [get]
Alternate estimated pose recently found.
Vector3 AlternateEstimatedTranslation [get]
Alternated estimated translation recently found.
float AlternateEstimationError [get]
Error of the alternate pose estimation.
Vector3[] Model [get]
Coordinates of the model points which pose should be estimated.
float FocalLength [get, set]
Effective focal length of the camera used to capture the model.
Private Member Functions
float Iterate (Point[] points, ref Matrix3x3 rotation, ref Vector3 translation)
void POS (Point[] imagePoints, Vector3 eps, out Matrix3x3 rotation1, out Matrix3x3 rotation2, out Vector3 translation1, out Vector3 translation2)
float GetError (Point[] imagePoints, Matrix3x3 rotation, Vector3 translation)
Private Attributes
float focalLength
Vector3[] modelPoints
Matrix3x3 modelVectors
Matrix3x3 modelPseudoInverse
Vector3 modelNormal
Matrix3x3 alternateRotation = new Matrix3x3()
Vector3 alternateTranslation = new Vector3()
float alternatePoseError = 0
Matrix3x3 bestRotation = new Matrix3x3()
Vector3 bestTranslation = new Vector3()
float bestPoseError = 0
Static Private Attributes
const float ErrorLimit = 2
Detailed Description
3D pose estimation algorithm (coplanar case).
The class implements an algorithm for 3D object's pose estimation from it's 2D coordinates obtained by perspective projection, when the object is described coplanar points. The idea of the implemented math and algorithm is described in "Iterative Pose Estimation using Coplanar Feature Points" paper written by Oberkampf, Daniel DeMenthon and Larry Davis (the implementation of the algorithm is very close translation of the pseudo code given by the paper, so should be easy to follow).
<note>At this point the implementation works only with models described by 4 points, which is the minimum number of points enough for 3D pose estimation.</note>
<note>The 4 model's point are supposed to be coplanar, i.e. supposed to reside all within same planer. See Posit for none coplanar case.</note>
Read 3D Pose Estimation article for additional information and samples.
Sample usage:
// points of real object - model
Vector3[] copositObject = new Vector3[4]
{
    new Vector3( -56.5f, 0,  56.5f ),
    new Vector3(  56.5f, 0,  56.5f ),
    new Vector3(  56.5f, 0, -56.5f ),
    new Vector3( -56.5f, 0, -56.5f ),
};
// focal length of camera used to capture the object
float focalLength = 640; // depends on your camera or projection system
// initialize CoPOSIT object
CoplanarPosit coposit = new CoplanarPosit(copositObject, focalLength);
// 2D points of te object - projection
AForge.Point[] projectedPoints = new AForge.Point[4]
{
    new AForge.Point( -77,  48 ),
    new AForge.Point(  44,  66 ),
    new AForge.Point(  75, -36 ),
    new AForge.Point( -61, -58 ),
};
// estimate pose
Matrix3x3 rotationMatrix;
Vector3 translationVector;
coposit.EstimatePose(projectedPoints,
    out rotationMatrix, out translationVector );
See also
Posit
Constructor & Destructor Documentation
CoplanarPosit()
AForge.Math.Geometry.CoplanarPosit.CoplanarPosit (Vector3[] model, float focalLength) inline
Initializes a new instance of the Posit class.
Parameters
model Array of vectors containing coordinates of four real model's point.
focalLength Effective focal length of the camera used to capture the model.
Exceptions
ArgumentException The model must have 4 points.
References AForge.Math.Matrix3x3.CreateDiagonal(), AForge.Math.Matrix3x3.CreateFromRows(), AForge.Math.Geometry.CoplanarPosit.focalLength, AForge.Math.Geometry.CoplanarPosit.modelNormal, AForge.Math.Geometry.CoplanarPosit.modelPoints, AForge.Math.Geometry.CoplanarPosit.modelPseudoInverse, AForge.Math.Geometry.CoplanarPosit.modelVectors, AForge.Math.Matrix3x3.SVD(), and AForge.Math.Matrix3x3.Transpose().
Member Function Documentation
EstimatePose()
void AForge.Math.Geometry.CoplanarPosit.EstimatePose (Point[] points, out Matrix3x3 rotation, out Vector3 translation) inline
Estimate pose of a model from it's projected 2D coordinates.
Parameters
points 4 2D points of the model's projection.
rotation Gets best estimation of object's rotation.
translation Gets best estimation of object's translation.
Exceptions
ArgumentException 4 points must be be given for pose estimation.
Because of the Coplanar POSIT algorithm's nature, it provides two pose estimations, which are valid from the algorithm's math point of view. For each pose an error is calculated, which specifies how good estimation fits to the specified real 2D coordinated. The method provides the best estimation through its output parameters rotation and translation . This may be enough for many of the pose estimation application. For those, who require checking the alternate pose estimation, it can be obtained using AlternateEstimatedRotation and AlternateEstimatedTranslation properties. The calculated error is provided for both estimations through BestEstimationError and AlternateEstimationError properties.
References AForge.Math.Geometry.CoplanarPosit.alternatePoseError, AForge.Math.Geometry.CoplanarPosit.alternateRotation, AForge.Math.Geometry.CoplanarPosit.alternateTranslation, AForge.Math.Geometry.CoplanarPosit.bestPoseError, AForge.Math.Geometry.CoplanarPosit.bestRotation, AForge.Math.Geometry.CoplanarPosit.bestTranslation, AForge.Math.Geometry.CoplanarPosit.Iterate(), and AForge.Math.Geometry.CoplanarPosit.POS().
Referenced by PoseEstimation.MainForm.EstimatePose().
Iterate()
float AForge.Math.Geometry.CoplanarPosit.Iterate (Point[] points, ref Matrix3x3 rotation, ref Vector3 translation) inline private
References AForge.Math.Geometry.CoplanarPosit.ErrorLimit, AForge.Math.Geometry.CoplanarPosit.GetError(), AForge.Math.Matrix3x3.GetRow(), AForge.Math.Geometry.CoplanarPosit.modelVectors, AForge.Math.Geometry.CoplanarPosit.POS(), and AForge.Math.Vector3.Z.
Referenced by AForge.Math.Geometry.CoplanarPosit.EstimatePose().
POS()
void AForge.Math.Geometry.CoplanarPosit.POS (Point[] imagePoints, Vector3 eps, out Matrix3x3 rotation1, out Matrix3x3 rotation2, out Vector3 translation1, out Vector3 translation2) inline private
References AForge.Math.Matrix3x3.CreateFromRows(), AForge.Math.Vector3.Cross(), AForge.Math.Vector3.Dot(), AForge.Math.Geometry.CoplanarPosit.focalLength, AForge.Math.Geometry.CoplanarPosit.modelNormal, AForge.Math.Geometry.CoplanarPosit.modelPoints, AForge.Math.Geometry.CoplanarPosit.modelPseudoInverse, AForge.Math.Vector3.Normalize(), AForge.Math.Vector3.Square, AForge.Math.Vector3.X, AForge.Point.X, AForge.Math.Vector3.Y, and AForge.Point.Y.
Referenced by AForge.Math.Geometry.CoplanarPosit.EstimatePose(), and AForge.Math.Geometry.CoplanarPosit.Iterate().
GetError()
float AForge.Math.Geometry.CoplanarPosit.GetError (Point[] imagePoints, Matrix3x3 rotation, Vector3 translation) inline private
References AForge.Math.Geometry.CoplanarPosit.focalLength, AForge.Math.Geometry.GeometryTools.GetAngleBetweenVectors(), AForge.Math.Geometry.CoplanarPosit.modelPoints, AForge.Math.Vector3.X, AForge.Math.Vector3.Y, and AForge.Math.Vector3.Z.
Referenced by AForge.Math.Geometry.CoplanarPosit.Iterate().
Member Data Documentation
focalLength
float AForge.Math.Geometry.CoplanarPosit.focalLength private
Referenced by AForge.Math.Geometry.CoplanarPosit.CoplanarPosit(), AForge.Math.Geometry.CoplanarPosit.GetError(), and AForge.Math.Geometry.CoplanarPosit.POS().
modelPoints
Vector3 [] AForge.Math.Geometry.CoplanarPosit.modelPoints private
Referenced by AForge.Math.Geometry.CoplanarPosit.CoplanarPosit(), AForge.Math.Geometry.CoplanarPosit.GetError(), and AForge.Math.Geometry.CoplanarPosit.POS().
modelVectors
Matrix3x3 AForge.Math.Geometry.CoplanarPosit.modelVectors private
Referenced by AForge.Math.Geometry.CoplanarPosit.CoplanarPosit(), and AForge.Math.Geometry.CoplanarPosit.Iterate().
modelPseudoInverse
Matrix3x3 AForge.Math.Geometry.CoplanarPosit.modelPseudoInverse private
Referenced by AForge.Math.Geometry.CoplanarPosit.CoplanarPosit(), and AForge.Math.Geometry.CoplanarPosit.POS().
modelNormal
Vector3 AForge.Math.Geometry.CoplanarPosit.modelNormal private
Referenced by AForge.Math.Geometry.CoplanarPosit.CoplanarPosit(), and AForge.Math.Geometry.CoplanarPosit.POS().
alternateRotation
Matrix3x3 AForge.Math.Geometry.CoplanarPosit.alternateRotation = new Matrix3x3() private
Referenced by AForge.Math.Geometry.CoplanarPosit.EstimatePose().
alternateTranslation
Vector3 AForge.Math.Geometry.CoplanarPosit.alternateTranslation = new Vector3() private
Referenced by AForge.Math.Geometry.CoplanarPosit.EstimatePose().
alternatePoseError
float AForge.Math.Geometry.CoplanarPosit.alternatePoseError = 0 private
Referenced by AForge.Math.Geometry.CoplanarPosit.EstimatePose().
bestRotation
Matrix3x3 AForge.Math.Geometry.CoplanarPosit.bestRotation = new Matrix3x3() private
Referenced by AForge.Math.Geometry.CoplanarPosit.EstimatePose().
bestTranslation
Vector3 AForge.Math.Geometry.CoplanarPosit.bestTranslation = new Vector3() private
Referenced by AForge.Math.Geometry.CoplanarPosit.EstimatePose().
bestPoseError
float AForge.Math.Geometry.CoplanarPosit.bestPoseError = 0 private
Referenced by AForge.Math.Geometry.CoplanarPosit.EstimatePose().
ErrorLimit
const float AForge.Math.Geometry.CoplanarPosit.ErrorLimit = 2 static private
Referenced by AForge.Math.Geometry.CoplanarPosit.Iterate().
Property Documentation
BestEstimatedRotation
Matrix3x3 AForge.Math.Geometry.CoplanarPosit.BestEstimatedRotation get
Best estimated pose recently found.
The property keeps best estimated pose found by the latest call to EstimatePose. The same estimated pose is provided by that method also and can be accessed through this property for convenience.
See also BestEstimatedTranslation and BestEstimationError.
Referenced by PoseEstimation.MainForm.EstimatePose().
BestEstimatedTranslation
Vector3 AForge.Math.Geometry.CoplanarPosit.BestEstimatedTranslation get
Best estimated translation recently found.
The property keeps best estimated translation found by the latest call to EstimatePose. The same estimated translation is provided by that method also and can be accessed through this property for convenience.
See also BestEstimatedRotation and BestEstimationError.
Referenced by PoseEstimation.MainForm.EstimatePose().
BestEstimationError
float AForge.Math.Geometry.CoplanarPosit.BestEstimationError get
Error of the best pose estimation.
The property keeps error of the best pose estimation, which is calculated as average error between real angles of the specified quadrilateral and angles of the quadrilateral which is a projection of the best pose estimation. The error is measured degrees in (angle).
AlternateEstimatedRotation
Matrix3x3 AForge.Math.Geometry.CoplanarPosit.AlternateEstimatedRotation get
Alternate estimated pose recently found.
The property keeps alternate estimated pose found by the latest call to EstimatePose.
See also AlternateEstimatedTranslation and AlternateEstimationError.
Referenced by PoseEstimation.MainForm.EstimatePose().
AlternateEstimatedTranslation
Vector3 AForge.Math.Geometry.CoplanarPosit.AlternateEstimatedTranslation get
Alternated estimated translation recently found.
The property keeps alternate estimated translation found by the latest call to EstimatePose.
See also AlternateEstimatedRotation and AlternateEstimationError.
Referenced by PoseEstimation.MainForm.EstimatePose().
AlternateEstimationError
float AForge.Math.Geometry.CoplanarPosit.AlternateEstimationError get
Error of the alternate pose estimation.
The property keeps error of the alternate pose estimation, which is calculated as average error between real angles of the specified quadrilateral and angles of the quadrilateral which is a projection of the alternate pose estimation. The error is measured in degrees (angle).
Model
Vector3 [] AForge.Math.Geometry.CoplanarPosit.Model get
Coordinates of the model points which pose should be estimated.
FocalLength
float AForge.Math.Geometry.CoplanarPosit.FocalLength get set
Effective focal length of the camera used to capture the model.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Math/Geometry/CoplanarPosit.cs