Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLARFX Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLARFX Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLARFX (LSAME lsame, DGEMV dgemv, DGER dger)
DLARFX ()
void Run (string SIDE, int M, int N, double[] V, int offset_v, double TAU, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work)
Private Attributes
LSAME _lsame
DGEMV _dgemv
DGER _dger
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLARFX applies a real elementary reflector H to a real m by n matrix C, from either the left or the right. H is represented in the form
H = I - tau * v * v'
where tau is a real scalar and v is a real vector.
If tau = 0, then H is taken to be the unit matrix
This version uses inline code if H has order .LT. 11.
/summary>
Constructor & Destructor Documentation
DLARFX() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLARFX.DLARFX (LSAME lsame, DGEMV dgemv, DGER dger) inline
DLARFX() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLARFX.DLARFX () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLARFX.Run (string SIDE, int M, int N, double[] V, int offset_v, double TAU, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work) inline
Purpose
DLARFX applies a real elementary reflector H to a real m by n matrix C, from either the left or the right. H is represented in the form
H = I - tau * v * v'
where tau is a real scalar and v is a real vector.
If tau = 0, then H is taken to be the unit matrix
This version uses inline code if H has order .LT. 11.
/summary>
Parameters
SIDE (input) CHARACTER*1 = 'L': form H * C = 'R': form C * H /param>
Parameters
M (input) INTEGER The number of rows of the matrix C. /param>
Parameters
N (input) INTEGER The number of columns of the matrix C. /param>
Parameters
V (input) DOUBLE PRECISION array, dimension (M) if SIDE = 'L' or (N) if SIDE = 'R' The vector v in the representation of H. /param>
Parameters
TAU (input) DOUBLE PRECISION The value tau in the representation of H. /param>
Parameters
C (input/output) DOUBLE PRECISION array, dimension (LDC,N) On entry, the m by n matrix C. On exit, C is overwritten by the matrix H * C if SIDE = 'L', or C * H if SIDE = 'R'. /param>
Parameters
LDC (input) INTEGER The leading dimension of the array C. LDA .GE. (1,M). /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (N) if SIDE = 'L' or (M) if SIDE = 'R' WORK is not referenced if H has order .LT. 11. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLARFX.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.DGER.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLARFX.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAEXC.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLARFX._lsame private
_dgemv
DGEMV DotNumerics.LinearAlgebra.CSLapack.DLARFX._dgemv private
_dger
DGER DotNumerics.LinearAlgebra.CSLapack.DLARFX._dger private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLARFX.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLARFX.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLARFX.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLARFX.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlarfx.cs