Doc: IGLib EXTENDED: ChemicalElementPropertiesDto Class Reference
ChemicalElementPropertiesDto Class Reference
DTO (Data Transfer Objects) for chemical element properties (the ChemicalElementProperties class). Used to store a state of a chemical element properties object.
Public Member Functions
ChemicalElementPropertiesDto ()
Default constructor, sets IsNull to true.
ChemicalElementPropertiesDto (ChemicalElementProperties elementProperties)
Constructor, prepares the current DTO for storing a specific chemical element properties object (type ChemicalElementProperties).
override ChemicalElementProperties CreateObject ()
Creates and returns a new chemical element of the appropriate type.
Public Member Functions inherited from IG.Lib.SerializationDtoBase< ChemicalElementProperties, ChemicalElementProperties >
SerializationDtoBase ()
virtual bool GetNull ()
Returns a flag indicating whether the object represented by the current DTO is null.
virtual void SetNull (bool isNull)
Sets a flag indicating whether the object represented by the current DTO is null.
virtual void CopyFromBase (BaseType obj)
Copies data to the current DTO from an object of type BaseType.
virtual void CopyToBase (ref BaseType obj)
Copies data from the current DTO to an object of the base type. Object is created anew if necessary by using the CreateObject() method.
virtual void CopyFrom (Type obj)
Copies data to the current DTO from an object of type Type.
virtual void CopyTo (ref Type obj)
Copies data from the current DTO to an object of type Type. Object is created anew if necessary by using the CreateObject() method.
virtual void CopyFromObject (object obj)
Copies data to the current DTO from an object of type object. The necessary casts are performed.
virtual void CopyToObject (ref object obj)
Copies data from the current DTO to an object of type object. Object is created anew if necessary by using the CreateObject() method. The necessary casts are performed.
override string ToString ()
Creates and returns string representation of the current DTO (data transfer object).
Public Attributes
int AtomicNumber
double AtomicWeight
Protected Member Functions
override void CopyFromPlain (ChemicalElementProperties elementProperties)
Copies data to the current DTO from a chemical element properties object.
override void CopyToPlain (ref ChemicalElementProperties elementProperties)
Copies data from the current DTO to a chemical element properties object.
Protected Member Functions inherited from IG.Lib.SerializationDtoBase< ChemicalElementProperties, ChemicalElementProperties >
abstract void CopyFromPlain (BaseType obj)
Copies contents of the specified object to the current DTO (Data Transfer Object).
abstract void CopyToPlain (ref BaseType obj)
Copies contents of the current DTO (Data Transfer Object) to the specified object.
Private Attributes
string Symbol
Additional Inherited Members
Protected Attributes inherited from IG.Lib.SerializationDtoBase< ChemicalElementProperties, ChemicalElementProperties >
bool _isNull
Properties inherited from IG.Lib.SerializationDtoBase< ChemicalElementProperties, ChemicalElementProperties >
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Detailed Description
DTO (Data Transfer Objects) for chemical element properties (the ChemicalElementProperties class). Used to store a state of a chemical element properties object.
Template Parameters
ChemicalElementType Type parameter specifying the specific chemical element type for which concrete DTO is designed.
$A Igor Oct09;
Constructor & Destructor Documentation
ChemicalElementPropertiesDto() [1/2]
ChemicalElementPropertiesDto.ChemicalElementPropertiesDto () inline
Default constructor, sets IsNull to true.
References IG.Lib.SerializationDtoBase< ChemicalElementProperties, ChemicalElementProperties >.SetNull().
ChemicalElementPropertiesDto() [2/2]
ChemicalElementPropertiesDto.ChemicalElementPropertiesDto (ChemicalElementProperties elementProperties) inline
Constructor, prepares the current DTO for storing a specific chemical element properties object (type ChemicalElementProperties).
Parameters
length Element properties object whose data is stored in the current DTO.
References IG.Lib.SerializationDtoBase< ChemicalElementProperties, ChemicalElementProperties >.CopyFrom(), and IG.Lib.SerializationDtoBase< ChemicalElementProperties, ChemicalElementProperties >.SetNull().
Member Function Documentation
CreateObject()
override ChemicalElementProperties ChemicalElementPropertiesDto.CreateObject () inline virtual
Creates and returns a new chemical element of the appropriate type.
Implements IG.Lib.SerializationDtoBase< ChemicalElementProperties, ChemicalElementProperties >.
References AtomicNumber, AtomicWeight, and Symbol.
Referenced by CopyToPlain().
CopyFromPlain()
override void ChemicalElementPropertiesDto.CopyFromPlain (ChemicalElementProperties elementProperties) inline protected
Copies data to the current DTO from a chemical element properties object.
Parameters
elementProperties Chemical element object from which data is copied.
References IG.Physics.ChemicalElementProperties.AtomicNumber, IG.Physics.ChemicalElementProperties.AtomicWeight, IG.Lib.SerializationDtoBase< ChemicalElementProperties, ChemicalElementProperties >.SetNull(), and IG.Physics.ChemicalElementProperties.Symbol.
CopyToPlain()
override void ChemicalElementPropertiesDto.CopyToPlain (ref ChemicalElementProperties elementProperties) inline protected
Copies data from the current DTO to a chemical element properties object.
Parameters
elementProperties Chemical element properties object that data is copied to.
References AtomicNumber, AtomicWeight, CreateObject(), IG.Lib.SerializationDtoBase< ChemicalElementProperties, ChemicalElementProperties >.GetNull(), and Symbol.
Member Data Documentation
Symbol
string ChemicalElementPropertiesDto.Symbol private
Referenced by CopyToPlain(), and CreateObject().
AtomicNumber
int ChemicalElementPropertiesDto.AtomicNumber
Referenced by CopyToPlain(), and CreateObject().
AtomicWeight
double ChemicalElementPropertiesDto.AtomicWeight
Referenced by CopyToPlain(), and CreateObject().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/physics/chemistry/dtos/ChemicalElementPropertiesDto.cs