Doc: IGLib EXTENDED: AForge.Imaging.IPPrototyper.ImageProcessingLog Class Reference
AForge.Imaging.IPPrototyper.ImageProcessingLog Class Reference
Default implementation of IImageProcessingLog interface.
Public Member Functions
void Clear ()
Clear image processing log removing all images and messages from it.
void AddImage (string key, Bitmap image)
Add new image to the log.
void AddMessage (string message)
Add messafe to the log.
Properties
Dictionary< string, Bitmap > Images [get]
Collection of images representing image processing steps.
List< string > Messages [get]
List of messages stored in the log.
Private Attributes
Dictionary< string, Bitmap > images = new Dictionary<string,Bitmap>()
List< string > messages = new List<string>()
Detailed Description
Default implementation of IImageProcessingLog interface.
Member Function Documentation
Clear()
void AForge.Imaging.IPPrototyper.ImageProcessingLog.Clear () inline
Clear image processing log removing all images and messages from it.
Implements AForge.Imaging.IPPrototyper.IImageProcessingLog.
References AForge.Imaging.IPPrototyper.ImageProcessingLog.images, and AForge.Imaging.IPPrototyper.ImageProcessingLog.messages.
AddImage()
void AForge.Imaging.IPPrototyper.ImageProcessingLog.AddImage (string key, Bitmap image) inline
Add new image to the log.
Parameters
key Key/name of the image (image processing step).
image Image to add to the log.
Adds new image to the image processing log or replaces existing image if specified key already exists in the log.
Implements AForge.Imaging.IPPrototyper.IImageProcessingLog.
References AForge.Imaging.IPPrototyper.ImageProcessingLog.images.
AddMessage()
void AForge.Imaging.IPPrototyper.ImageProcessingLog.AddMessage (string message) inline
Add messafe to the log.
Parameters
message Message to add to the image processing log.
Implements AForge.Imaging.IPPrototyper.IImageProcessingLog.
References AForge.Imaging.IPPrototyper.ImageProcessingLog.messages.
Member Data Documentation
images
Dictionary<string, Bitmap> AForge.Imaging.IPPrototyper.ImageProcessingLog.images = new Dictionary<string,Bitmap>() private
Referenced by AForge.Imaging.IPPrototyper.ImageProcessingLog.AddImage(), and AForge.Imaging.IPPrototyper.ImageProcessingLog.Clear().
messages
List<string> AForge.Imaging.IPPrototyper.ImageProcessingLog.messages = new List<string>() private
Referenced by AForge.Imaging.IPPrototyper.ImageProcessingLog.AddMessage(), and AForge.Imaging.IPPrototyper.ImageProcessingLog.Clear().
Property Documentation
Images
Dictionary<string, Bitmap> AForge.Imaging.IPPrototyper.ImageProcessingLog.Images get
Collection of images representing image processing steps.
Messages
List<string> AForge.Imaging.IPPrototyper.ImageProcessingLog.Messages get
List of messages stored in the log.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Tools/IPPrototyper/Interfaces/ImageProcessingLog.cs