Doc: IGLib EXTENDED: NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources Class Reference
NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources Class Reference
Public Member Functions
ParameterizedTestFixtureWithDataSources (int val)
void CanAccessTestCaseSource (int x, int y)
void CanGenerateDataFromParameter (int x, int y)
void CanAccessValueSource ([ValueSource("intvals")] int x)
Private Member Functions
IEnumerable GenerateData ()
Private Attributes
int answer
Constructor & Destructor Documentation
ParameterizedTestFixtureWithDataSources()
NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources.ParameterizedTestFixtureWithDataSources (int val) inline
Member Function Documentation
CanAccessTestCaseSource()
void NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources.CanAccessTestCaseSource (int x, int y) inline
References NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources.answer, NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
GenerateData()
IEnumerable NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources.GenerateData () inline private
References NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources.answer.
CanGenerateDataFromParameter()
void NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources.CanGenerateDataFromParameter (int x, int y) inline
References NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources.answer, NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
CanAccessValueSource()
void NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources.CanAccessValueSource ([ValueSource("intvals")] int x) inline
References NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources.answer, and NUnit.Framework.Assert.That().
Member Data Documentation
answer
int NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources.answer private
Referenced by NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources.CanAccessTestCaseSource(), NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources.CanAccessValueSource(), NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources.CanGenerateDataFromParameter(), and NUnit.Core.Tests.ParameterizedTestFixtureWithDataSources.GenerateData().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/Addins/nunit.v2.driver.tests/ParameterizedTestFixtureTests.cs