Doc: IGLib EXTENDED: NUnit.Framework.PropertyAttribute Class Reference
NUnit.Framework.PropertyAttribute Class Reference
PropertyAttribute is used to attach information to a test as a name/value pair..
Public Member Functions
PropertyAttribute (string propertyName, string propertyValue)
Construct a PropertyAttribute with a name and string value
PropertyAttribute (string propertyName, int propertyValue)
Construct a PropertyAttribute with a name and int value
PropertyAttribute (string propertyName, double propertyValue)
Construct a PropertyAttribute with a name and double value
virtual void ApplyToTest (Test test)
Modifies a test by adding properties to it.
Public Member Functions inherited from NUnit.Framework.NUnitAttribute
NUnitAttribute ()
Default constructor
Protected Member Functions
PropertyAttribute ()
Constructor for derived classes that set the property dictionary directly.
PropertyAttribute (object propertyValue)
Constructor for use by derived classes that use the name of the type as the property name. Derived classes must ensure that the Type of the property value is a standard type supported by the BCL. Any custom types will cause a serialization Exception when in the client.
Properties
IPropertyBag Properties [get]
Gets the property dictionary for this attribute
Private Attributes
PropertyBag properties = new PropertyBag()
Detailed Description
PropertyAttribute is used to attach information to a test as a name/value pair..
Constructor & Destructor Documentation
PropertyAttribute() [1/5]
NUnit.Framework.PropertyAttribute.PropertyAttribute (string propertyName, string propertyValue) inline
Construct a PropertyAttribute with a name and string value
Parameters
propertyName The name of the property
propertyValue The property value
References NUnit.Framework.Internal.PropertyBag.Add().
PropertyAttribute() [2/5]
NUnit.Framework.PropertyAttribute.PropertyAttribute (string propertyName, int propertyValue) inline
Construct a PropertyAttribute with a name and int value
Parameters
propertyName The name of the property
propertyValue The property value
References NUnit.Framework.Internal.PropertyBag.Add().
PropertyAttribute() [3/5]
NUnit.Framework.PropertyAttribute.PropertyAttribute (string propertyName, double propertyValue) inline
Construct a PropertyAttribute with a name and double value
Parameters
propertyName The name of the property
propertyValue The property value
References NUnit.Framework.Internal.PropertyBag.Add().
PropertyAttribute() [4/5]
NUnit.Framework.PropertyAttribute.PropertyAttribute () inline protected
Constructor for derived classes that set the property dictionary directly.
PropertyAttribute() [5/5]
NUnit.Framework.PropertyAttribute.PropertyAttribute (object propertyValue) inline protected
Constructor for use by derived classes that use the name of the type as the property name. Derived classes must ensure that the Type of the property value is a standard type supported by the BCL. Any custom types will cause a serialization Exception when in the client.
References NUnit.Framework.Internal.PropertyBag.Add().
Member Function Documentation
ApplyToTest()
virtual void NUnit.Framework.PropertyAttribute.ApplyToTest (Test test) inline virtual
Modifies a test by adding properties to it.
Parameters
test The test to modify
Implements NUnit.Framework.Interfaces.IApplyToTest.
Reimplemented in NUnit.Framework.RequiresThreadAttribute.
References NUnit.Framework.Interfaces.IPropertyBag.Keys, and NUnit.Framework.PropertyAttribute.Properties.
Referenced by NUnit.Framework.Attributes.ApplyToTestTests.DescriptionAttributeSetsDescription(), NUnit.Framework.Attributes.ApplyToTestTests.DescriptionAttributeSetsDescriptionOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.MaxTimeAttributeSetsMaxTime(), NUnit.Framework.Attributes.ApplyToTestTests.MaxTimeAttributeSetsMaxTimeOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.RepeatAttributeSetsRepeatCount(), NUnit.Framework.Attributes.ApplyToTestTests.RepeatAttributeSetsRepeatCountOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresMTAAttributeSetsApartmentState(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresMTAAttributeSetsApartmentStateOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresSTAAttributeSetsApartmentState(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresSTAAttributeSetsApartmentStateOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.SetCultureAttributeSetsSetCultureProperty(), NUnit.Framework.Attributes.ApplyToTestTests.SetCultureAttributeSetsSetCulturePropertyOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.SetUICultureAttributeSetsSetUICultureProperty(), and NUnit.Framework.Attributes.ApplyToTestTests.SetUICultureAttributeSetsSetUICulturePropertyOnNonRunnableTest().
Member Data Documentation
properties
PropertyBag NUnit.Framework.PropertyAttribute.properties = new PropertyBag() private
Property Documentation
Properties
IPropertyBag NUnit.Framework.PropertyAttribute.Properties get
Gets the property dictionary for this attribute
Referenced by NUnit.Framework.ApartmentAttribute.ApartmentAttribute(), NUnit.Framework.PropertyAttribute.ApplyToTest(), NUnit.Framework.ParallelizableAttribute.ParallelizableAttribute(), NUnit.Framework.RequiresMTAAttribute.RequiresMTAAttribute(), NUnit.Framework.RequiresSTAAttribute.RequiresSTAAttribute(), and NUnit.Framework.RequiresThreadAttribute.RequiresThreadAttribute().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Attributes/PropertyAttribute.cs