Doc: IGLib EXTENDED: IG.Plot2d.NPlot_Demo Class Reference
IG.Plot2d.NPlot_Demo Class Reference
The main demo window. This is developed in such a way that IGLib's derived classes are gradually used in place of original ones.
Public Member Functions
void PlotCircular ()
void PlotWavelet ()
void PlotLogAxis ()
void PlotLogLog ()
void PlotGaussian ()
void PlotABC ()
void PlotLabelAxis ()
void PlotParticles ()
void PlotQE ()
void PlotImage ()
void PlotMarkers ()
void PlotTest ()
void PlotWave ()
void PlotMultiHistogram ()
void PlotCandleSimple ()
void PlotMockup ()
void PlotProfitLoss ()
NPlot_Demo ()
Static Public Member Functions
static void ExampleDemo ()
Runs this demonstration.
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
delegate void PlotDemoDelegate ()
delegate for plot demo functions.
float[] makeDaub (int len)
void PlotSincFunction ()
void TwissEllipse (float a, float b, float g, float e, ref float[] x, ref float[] y)
void Twiss (float[] x, float[] y, out float a, out float b, out float g, out float e)
void PlotDataSet ()
void PlotCandle ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void pd_PrintPage (object sender, PrintPageEventArgs ev)
void quitButton_Click (object sender, System.EventArgs e)
callback for quit button click
void btnEmf_Click (object sender, EventArgs e)
Creates an EMF from the plot and saves it into a file chosen by the user.
void ResizeHandler (object sender, System.EventArgs e)
callback for resize event.
void nextPlotButton_Click (object sender, System.EventArgs e)
callback for next button click
void nplotLinkLabel_LinkClicked (object sender, System.Windows.Forms.LinkLabelLinkClickedEventArgs e)
Callback for NPlot link label click
void printButton_Click (object sender, System.EventArgs e)
callback for print button click
void prevPlotButton_Click (object sender, System.EventArgs e)
Callback for prev button click.
void qeExampleTimer_Tick (object sender, System.EventArgs e)
Callback for QE example timer tick.
Private Attributes
int currentPlot = 0
used to keep track of the current demo plot being displayed.
PlotDemoDelegate[] PlotRoutines
list of the plot demos, initialized in the form constructor.
System.Windows.Forms.Button quitButton
System.Windows.Forms.Button nextPlotButton
System.Windows.Forms.Button printButton
System.ComponentModel.IContainer components
PrintDocument printDocument
System.Windows.Forms.Button prevPlotButton
NPlot.Windows.PlotSurface2D plotSurface
System.Windows.Forms.Timer qeExampleTimer
System.Windows.Forms.Label exampleNumberLabel
double[] PlotQEExampleValues
TextBox infoBox
Button btnEmf
string[] PlotQEExampleTextValues
string _fileName = Path.GetFullPath("../../graph.emf")
Current file name where the EMF is stored.
Detailed Description
The main demo window. This is developed in such a way that IGLib's derived classes are gradually used in place of original ones.
$A Igor Jan10;
Constructor & Destructor Documentation
NPlot_Demo()
IG.Plot2d.NPlot_Demo.NPlot_Demo () inline
References IG.Plot2d.NPlot_Demo.currentPlot, IG.Plot2d.NPlot_Demo.exampleNumberLabel, IG.Plot2d.NPlot_Demo.InitializeComponent(), IG.Plot2d.NPlot_Demo.pd_PrintPage(), IG.Plot2d.NPlot_Demo.PlotABC(), IG.Plot2d.NPlot_Demo.PlotCandleSimple(), IG.Plot2d.NPlot_Demo.PlotCircular(), IG.Plot2d.NPlot_Demo.PlotDataSet(), IG.Plot2d.NPlot_Demo.PlotDemoDelegate(), IG.Plot2d.NPlot_Demo.PlotGaussian(), IG.Plot2d.NPlot_Demo.PlotImage(), IG.Plot2d.NPlot_Demo.PlotLabelAxis(), IG.Plot2d.NPlot_Demo.PlotLogAxis(), IG.Plot2d.NPlot_Demo.PlotLogLog(), IG.Plot2d.NPlot_Demo.PlotMarkers(), IG.Plot2d.NPlot_Demo.PlotMockup(), IG.Plot2d.NPlot_Demo.PlotParticles(), IG.Plot2d.NPlot_Demo.PlotQE(), IG.Plot2d.NPlot_Demo.PlotRoutines, IG.Plot2d.NPlot_Demo.PlotSincFunction(), IG.Plot2d.NPlot_Demo.plotSurface, IG.Plot2d.NPlot_Demo.PlotWave(), IG.Plot2d.NPlot_Demo.PlotWavelet(), IG.Plot2d.NPlot_Demo.printDocument, and IG.Plot2d.NPlot_Demo.ResizeHandler().
Referenced by IG.Plot2d.NPlot_Demo.ExampleDemo().
Member Function Documentation
ExampleDemo()
static void IG.Plot2d.NPlot_Demo.ExampleDemo () inline static
Runs this demonstration.
References IG.Plot2d.NPlot_Demo.NPlot_Demo().
PlotDemoDelegate()
delegate void IG.Plot2d.NPlot_Demo.PlotDemoDelegate () private
delegate for plot demo functions.
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo().
PlotCircular()
void IG.Plot2d.NPlot_Demo.PlotCircular () inline
References IG.Plot2d.NPlot_Demo.infoBox, and IG.Plot2d.NPlot_Demo.plotSurface.
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo().
PlotWavelet()
void IG.Plot2d.NPlot_Demo.PlotWavelet () inline
References IG.Plot2d.NPlot_Demo.infoBox, IG.Plot2d.NPlot_Demo.makeDaub(), and IG.Plot2d.NPlot_Demo.plotSurface.
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo().
makeDaub()
float [] IG.Plot2d.NPlot_Demo.makeDaub (int len) inline private
Referenced by IG.Plot2d.NPlot_Demo.PlotWavelet().
PlotLogAxis()
void IG.Plot2d.NPlot_Demo.PlotLogAxis () inline
References IG.Plot2d.NPlot_Demo.infoBox, and IG.Plot2d.NPlot_Demo.plotSurface.
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo().
PlotLogLog()
void IG.Plot2d.NPlot_Demo.PlotLogLog () inline
References IG.Plot2d.NPlot_Demo.infoBox, and IG.Plot2d.NPlot_Demo.plotSurface.
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo().
PlotSincFunction()
void IG.Plot2d.NPlot_Demo.PlotSincFunction () inline private
References IG.Plot2d.NPlot_Demo.infoBox, and IG.Plot2d.NPlot_Demo.plotSurface.
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo().
PlotGaussian()
void IG.Plot2d.NPlot_Demo.PlotGaussian () inline
References IG.Plot2d.NPlot_Demo.infoBox, and IG.Plot2d.NPlot_Demo.plotSurface.
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo().
PlotABC()
void IG.Plot2d.NPlot_Demo.PlotABC () inline
References IG.Plot2d.NPlot_Demo.infoBox, and IG.Plot2d.NPlot_Demo.plotSurface.
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo().
PlotLabelAxis()
void IG.Plot2d.NPlot_Demo.PlotLabelAxis () inline
References IG.Plot2d.NPlot_Demo.infoBox, and IG.Plot2d.NPlot_Demo.plotSurface.
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo().
PlotParticles()
void IG.Plot2d.NPlot_Demo.PlotParticles () inline
References IG.Plot2d.NPlot_Demo.infoBox, IG.Plot2d.NPlot_Demo.plotSurface, IG.Plot2d.NPlot_Demo.Twiss(), and IG.Plot2d.NPlot_Demo.TwissEllipse().
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo().
TwissEllipse()
void IG.Plot2d.NPlot_Demo.TwissEllipse (float a, float b, float g, float e, ref float[] x, ref float[] y) inline private
Referenced by IG.Plot2d.NPlot_Demo.PlotParticles().
Twiss()
void IG.Plot2d.NPlot_Demo.Twiss (float[] x, float[] y, out float a, out float b, out float g, out float e) inline private
Referenced by IG.Plot2d.NPlot_Demo.PlotParticles().
PlotQE()
void IG.Plot2d.NPlot_Demo.PlotQE () inline
References IG.Plot2d.NPlot_Demo.infoBox, IG.Plot2d.NPlot_Demo.PlotQEExampleTextValues, IG.Plot2d.NPlot_Demo.PlotQEExampleValues, IG.Plot2d.NPlot_Demo.plotSurface, and IG.Plot2d.NPlot_Demo.qeExampleTimer.
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo().
PlotDataSet()
void IG.Plot2d.NPlot_Demo.PlotDataSet () inline private
References IG.Plot2d.NPlot_Demo.infoBox, and IG.Plot2d.NPlot_Demo.plotSurface.
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo().
PlotImage()
void IG.Plot2d.NPlot_Demo.PlotImage () inline
References IG.Plot2d.NPlot_Demo.infoBox, and IG.Plot2d.NPlot_Demo.plotSurface.
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo().
PlotMarkers()
void IG.Plot2d.NPlot_Demo.PlotMarkers () inline
References IG.Plot2d.NPlot_Demo.infoBox, and IG.Plot2d.NPlot_Demo.plotSurface.
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo().
PlotCandle()
void IG.Plot2d.NPlot_Demo.PlotCandle () inline private
References IG.Plot2d.NPlot_Demo.plotSurface.
PlotTest()
void IG.Plot2d.NPlot_Demo.PlotTest () inline
References IG.Plot2d.NPlot_Demo.plotSurface.
PlotWave()
void IG.Plot2d.NPlot_Demo.PlotWave () inline
References IG.Plot2d.NPlot_Demo.infoBox, and IG.Plot2d.NPlot_Demo.plotSurface.
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo().
PlotMultiHistogram()
void IG.Plot2d.NPlot_Demo.PlotMultiHistogram () inline
References IG.Plot2d.NPlot_Demo.plotSurface.
PlotCandleSimple()
void IG.Plot2d.NPlot_Demo.PlotCandleSimple () inline
References IG.Plot2d.NPlot_Demo.infoBox, and IG.Plot2d.NPlot_Demo.plotSurface.
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo().
PlotMockup()
void IG.Plot2d.NPlot_Demo.PlotMockup () inline
References IG.Plot2d.NPlot_Demo.infoBox, and IG.Plot2d.NPlot_Demo.plotSurface.
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo().
PlotProfitLoss()
void IG.Plot2d.NPlot_Demo.PlotProfitLoss () inline
References IG.Plot2d.NPlot_Demo.plotSurface.
Dispose()
override void IG.Plot2d.NPlot_Demo.Dispose (bool disposing) inline protected
Clean up any resources being used.
References IG.Plot2d.NPlot_Demo.components.
InitializeComponent()
void IG.Plot2d.NPlot_Demo.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo().
pd_PrintPage()
void IG.Plot2d.NPlot_Demo.pd_PrintPage (object sender, PrintPageEventArgs ev) inline private
References IG.Plot2d.NPlot_Demo.plotSurface.
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo().
quitButton_Click()
void IG.Plot2d.NPlot_Demo.quitButton_Click (object sender, System.EventArgs e) inline private
callback for quit button click
Parameters
sender unused
e unused
btnEmf_Click()
void IG.Plot2d.NPlot_Demo.btnEmf_Click (object sender, EventArgs e) inline private
Creates an EMF from the plot and saves it into a file chosen by the user.
References IG.Plot2d.NPlot_Demo._fileName, and IG.Plot2d.NPlot_Demo.plotSurface.
ResizeHandler()
void IG.Plot2d.NPlot_Demo.ResizeHandler (object sender, System.EventArgs e) inline private
callback for resize event.
Parameters
sender unused
e unused
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo().
nextPlotButton_Click()
void IG.Plot2d.NPlot_Demo.nextPlotButton_Click (object sender, System.EventArgs e) inline private
callback for next button click
Parameters
sender unused
e unused
References IG.Plot2d.NPlot_Demo.currentPlot, IG.Plot2d.NPlot_Demo.exampleNumberLabel, IG.Plot2d.NPlot_Demo.PlotRoutines, IG.Plot2d.NPlot_Demo.plotSurface, and IG.Plot2d.NPlot_Demo.qeExampleTimer.
nplotLinkLabel_LinkClicked()
void IG.Plot2d.NPlot_Demo.nplotLinkLabel_LinkClicked (object sender, System.Windows.Forms.LinkLabelLinkClickedEventArgs e) inline private
Callback for NPlot link label click
Parameters
sender unused
e unused
printButton_Click()
void IG.Plot2d.NPlot_Demo.printButton_Click (object sender, System.EventArgs e) inline private
callback for print button click
Parameters
sender unused
e unused
References IG.Plot2d.NPlot_Demo.printDocument.
prevPlotButton_Click()
void IG.Plot2d.NPlot_Demo.prevPlotButton_Click (object sender, System.EventArgs e) inline private
Callback for prev button click.
Parameters
sender unused
e unused
References IG.Plot2d.NPlot_Demo.currentPlot, IG.Plot2d.NPlot_Demo.exampleNumberLabel, and IG.Plot2d.NPlot_Demo.PlotRoutines.
qeExampleTimer_Tick()
void IG.Plot2d.NPlot_Demo.qeExampleTimer_Tick (object sender, System.EventArgs e) inline private
Callback for QE example timer tick.
Parameters
sender unused
e unused
References IG.Plot2d.NPlot_Demo.PlotQEExampleTextValues, IG.Plot2d.NPlot_Demo.PlotQEExampleValues, and IG.Plot2d.NPlot_Demo.plotSurface.
Member Data Documentation
currentPlot
int IG.Plot2d.NPlot_Demo.currentPlot = 0 private
used to keep track of the current demo plot being displayed.
Referenced by IG.Plot2d.NPlot_Demo.nextPlotButton_Click(), IG.Plot2d.NPlot_Demo.NPlot_Demo(), and IG.Plot2d.NPlot_Demo.prevPlotButton_Click().
PlotRoutines
PlotDemoDelegate [] IG.Plot2d.NPlot_Demo.PlotRoutines private
list of the plot demos, initialized in the form constructor.
Referenced by IG.Plot2d.NPlot_Demo.nextPlotButton_Click(), IG.Plot2d.NPlot_Demo.NPlot_Demo(), and IG.Plot2d.NPlot_Demo.prevPlotButton_Click().
quitButton
System.Windows.Forms.Button IG.Plot2d.NPlot_Demo.quitButton private
nextPlotButton
System.Windows.Forms.Button IG.Plot2d.NPlot_Demo.nextPlotButton private
printButton
System.Windows.Forms.Button IG.Plot2d.NPlot_Demo.printButton private
components
System.ComponentModel.IContainer IG.Plot2d.NPlot_Demo.components private
Referenced by IG.Plot2d.NPlot_Demo.Dispose().
printDocument
PrintDocument IG.Plot2d.NPlot_Demo.printDocument private
Referenced by IG.Plot2d.NPlot_Demo.NPlot_Demo(), and IG.Plot2d.NPlot_Demo.printButton_Click().
prevPlotButton
System.Windows.Forms.Button IG.Plot2d.NPlot_Demo.prevPlotButton private
plotSurface
NPlot.Windows.PlotSurface2D IG.Plot2d.NPlot_Demo.plotSurface private
Referenced by IG.Plot2d.NPlot_Demo.btnEmf_Click(), IG.Plot2d.NPlot_Demo.nextPlotButton_Click(), IG.Plot2d.NPlot_Demo.NPlot_Demo(), IG.Plot2d.NPlot_Demo.pd_PrintPage(), IG.Plot2d.NPlot_Demo.PlotABC(), IG.Plot2d.NPlot_Demo.PlotCandle(), IG.Plot2d.NPlot_Demo.PlotCandleSimple(), IG.Plot2d.NPlot_Demo.PlotCircular(), IG.Plot2d.NPlot_Demo.PlotDataSet(), IG.Plot2d.NPlot_Demo.PlotGaussian(), IG.Plot2d.NPlot_Demo.PlotImage(), IG.Plot2d.NPlot_Demo.PlotLabelAxis(), IG.Plot2d.NPlot_Demo.PlotLogAxis(), IG.Plot2d.NPlot_Demo.PlotLogLog(), IG.Plot2d.NPlot_Demo.PlotMarkers(), IG.Plot2d.NPlot_Demo.PlotMockup(), IG.Plot2d.NPlot_Demo.PlotMultiHistogram(), IG.Plot2d.NPlot_Demo.PlotParticles(), IG.Plot2d.NPlot_Demo.PlotProfitLoss(), IG.Plot2d.NPlot_Demo.PlotQE(), IG.Plot2d.NPlot_Demo.PlotSincFunction(), IG.Plot2d.NPlot_Demo.PlotTest(), IG.Plot2d.NPlot_Demo.PlotWave(), IG.Plot2d.NPlot_Demo.PlotWavelet(), and IG.Plot2d.NPlot_Demo.qeExampleTimer_Tick().
qeExampleTimer
System.Windows.Forms.Timer IG.Plot2d.NPlot_Demo.qeExampleTimer private
Referenced by IG.Plot2d.NPlot_Demo.nextPlotButton_Click(), and IG.Plot2d.NPlot_Demo.PlotQE().
exampleNumberLabel
System.Windows.Forms.Label IG.Plot2d.NPlot_Demo.exampleNumberLabel private
Referenced by IG.Plot2d.NPlot_Demo.nextPlotButton_Click(), IG.Plot2d.NPlot_Demo.NPlot_Demo(), and IG.Plot2d.NPlot_Demo.prevPlotButton_Click().
PlotQEExampleValues
double [] IG.Plot2d.NPlot_Demo.PlotQEExampleValues private
Referenced by IG.Plot2d.NPlot_Demo.PlotQE(), and IG.Plot2d.NPlot_Demo.qeExampleTimer_Tick().
infoBox
TextBox IG.Plot2d.NPlot_Demo.infoBox private
Referenced by IG.Plot2d.NPlot_Demo.PlotABC(), IG.Plot2d.NPlot_Demo.PlotCandleSimple(), IG.Plot2d.NPlot_Demo.PlotCircular(), IG.Plot2d.NPlot_Demo.PlotDataSet(), IG.Plot2d.NPlot_Demo.PlotGaussian(), IG.Plot2d.NPlot_Demo.PlotImage(), IG.Plot2d.NPlot_Demo.PlotLabelAxis(), IG.Plot2d.NPlot_Demo.PlotLogAxis(), IG.Plot2d.NPlot_Demo.PlotLogLog(), IG.Plot2d.NPlot_Demo.PlotMarkers(), IG.Plot2d.NPlot_Demo.PlotMockup(), IG.Plot2d.NPlot_Demo.PlotParticles(), IG.Plot2d.NPlot_Demo.PlotQE(), IG.Plot2d.NPlot_Demo.PlotSincFunction(), IG.Plot2d.NPlot_Demo.PlotWave(), and IG.Plot2d.NPlot_Demo.PlotWavelet().
btnEmf
Button IG.Plot2d.NPlot_Demo.btnEmf private
PlotQEExampleTextValues
string [] IG.Plot2d.NPlot_Demo.PlotQEExampleTextValues private
Referenced by IG.Plot2d.NPlot_Demo.PlotQE(), and IG.Plot2d.NPlot_Demo.qeExampleTimer_Tick().
_fileName
string IG.Plot2d.NPlot_Demo._fileName = Path.GetFullPath("../../graph.emf") private
Current file name where the EMF is stored.
Referenced by IG.Plot2d.NPlot_Demo.btnEmf_Click().
The documentation for this class was generated from the following file:
igtest/igplot_2d/demos/PlotSurface2DDemo.cs