Doc: IGLib EXTENDED: IG.Lib.DocFindings Class Reference
IG.Lib.DocFindings Class Reference
Class for holding and manipulating the data about observation order. Includes parsing an XML file, storing data internally, and transcription of read data to a PADO object that enables saving data to a database.
Public Member Functions
DocFindings ()
Default constructor, sets the type information.
override void Read ()
Reads msg data from the internal XML document containing the msg.
override void Read (XmlParser data)
Read msg data from an XML document containing the msg.
override void CheckConsistency (AccummulatedReport rep)
Check correctness and consistency of data and creates a report on this.
void EnsureCompatibilityBeforeXmlGeneration ()
Performs the necessary corrections such that other Labex tools will work with the generated XML. This is necessary e.g. to show findings, since methods for doing taht can not cope with absent XML fields.
override string ToString ()
Returns a string describing contents of the current object.
override XmlDocument ToXml ()
Converts a msg to Xml and returns it.
Public Member Functions inherited from IG.Lib.MsgBase
void SetSenderLabex ()
Sets msg data such that sender is Labex and receiver is Bis.
void SetSenderBis ()
Sets msg data such that sender is Bis and receiver is Labex.
Public Member Functions inherited from IG.Lib.ParsableXmlObject
virtual void Save (string filename)
Saves contents of the msg to an xml file.
virtual void CreateXml ()
Creates msg Xml from the current msg data and stores it in this object.
virtual void Load (string filename)
Loads msg data from a file containing the XML msg.
virtual void LoadXml (string doc)
Loads msg data from a string containing the XML msg.
virtual void LoadXml (XmlDocument doc)
Loads msg data from an XmlDocument containing XML msg.
virtual void WriteToConsole ()
Writes cntents of the msg in a human readable form to the system console.
virtual void Write (string filename, bool append)
Writes cntents of the msg in a human readable form to a file.
Static Public Member Functions
static bool IsRtf (string str)
Returns true if str is a valid rich text, or false otherwise.
static string ToRtf (string str)
Returns a rich text that corresponds to the string argument. If the argument is already a rich text then the unchanged argument is returned, otherwise it is wrapped in RTF markup.
static string ToText (string str)
Returns plain text that corresponds to the string argument. If the argument is a rich text then then text is extracted from it and returned, otherwise the unchanged argument is returned.
Static Public Member Functions inherited from IG.Lib.MsgBase
static void SetMessageReceiverOld (ref XmlDocument msg, string receiver, out bool changed)
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false. WARNING: searching for receiver element is done through an XPath expression, which may fail due to default namespaces that were not detected.
static void SetMessageReceiver (ref string message, string receiver, out bool changed)
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetMessageReceiver (ref XmlDocument msg, string receiver, out bool changed)
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetMessageReceiver (ref XmlBuilder data, string receiver, out bool changed)
Sets the receiver of the communication msg stored in an Xml builder to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetMessageSender (ref XmlBuilder data, string sender, out bool changed)
Sets the sender of the communication msg stored in an Xml builder to the specified sender, and indicates through an output argument whether the sender has been changed in msg. If the Sender stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetMessageResponder (ref XmlBuilder data, string responder, out bool changed)
Sets the responder of the communication msg stored in an Xml builder to the specified responder, and indicates through an output argument whether the responder has been changed in msg. If the responder stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static MessageType GetMessageType (string msgstring)
Infers the msg type from the XML string containing the msg, and returns it.
static MessageType GetMessageType (XmlDocument msg)
Infers the msg type from the XML document containing the msg, and returns it.
static MessageType GetMessageType (XmlParser data)
Infers the msg type from the XML parser containing the msg, and returns it.
Public Attributes
bool CompatibilityMode = false
When this flag is set, operations are performed in compatible mode, such that results and inputs are compatible with the current state (this mainly refers to what Mirjam produced)
bool UsePlainText = false
If true then plain text is used for fields that are otherwise in RTF.
ObservationType ObservationTypeFlag = ObservationType.Unknown
int? Id = null
Id of the Findings database rsr; this is null when Finding data is not read from the database.
bool XmlCreateInputFormat = false
If true then XML is created for data in input format, which means that all fields can be read back when parding that XML. Default is false, in this case the generated XML is in output format more suitable for printing and jviewing (i.e. better for human reading), but in this form some fields (data and gender fields) can not be interpreted correctly when such a file is parsed.
bool XmlAddStyleSheetInstruction = true
If true then processing instruction is added to the XML documents created from data that enables viewing in browser in a human readable form.
Public Attributes inherited from IG.Lib.MsgBase
MessageType Type = MessageType.Unknown
Message type. Helps with general methods that operate on any datatype of msg.
string MessageId = null
Message ID, obtained form the web service.
string MessageFile = null
Specifies the file where message has been backed up. Warning: this file may be deleted at any time!
string MessageNumber = null
Public Attributes inherited from IG.Lib.ParsableXmlObject
string XmlString = null
Properties
new FindingsConst Const [get]
string InnerDescription [get, set]
Inner description.
string OuterDescription [get, set]
Outer description.
string MacroDescription [get, set]
Macro description.
string MicroDescription [get, set]
Micro description.
string MacroDescription2 [get, set]
Macro description.
string MicroDescription2 [get, set]
Micro description.
string DiagnosisClinicalText [get, set]
Free text of clinical diagnosis.
string DiagnosisPatoHistologicalText [get, set]
Free text of patohistological diagnosis.
string TemporaryOpinion [get, set]
Temporary opinion.
string Appendix [get, set]
Appendix.
string Header [get, set]
Header.
string Footer [get, set]
Footer.
bool IsHistological [get]
bool IsCytological [get]
bool IsPatological [get]
string SignerPartString [get, private set]
string SignerFinishString [get, private set]
string SignerAdditionString [get, private set]
string SignTimePartString [get, private set]
string SignTimeFinishString [get, private set]
string SignTimeAdditionString [get, private set]
string SampleTimeOutputString [get]
string ReceptionTimeOutputString [get]
string CompletionTimeOutputString [get]
Properties inherited from IG.Lib.MsgBase
static MsgConst Const [get]
Gets objects that contains all constants related to communication messages.
string MessageXml [get, set]
Complete msg as obtained from the web service.
Properties inherited from IG.Lib.ParsableXmlObject
virtual IReporter R [get]
Reporter for this class.
XmlDocument Doc [get]
Returns the XML document representing the msg.
Private Member Functions
string ConvertRtfField (string str)
Aoutonomously converts text either to plain text or to RTF, dependent on the value of UsePlainText flag.
string ConvertRtfFieldSet (string str)
Aoutonomously converts text either to plain text or to RTF, dependent on the value of UsePlainText flag.
string DateString (DateTime t)
Converts date to a string for output.
string DateString (DateTime? t)
Converts date to a string for output.
Static Private Member Functions
static string ToRtfSet (string str)
Returns a rich text that corresponds to the string argument. If the argument is not a rich text then it is wrapped in RTF markup. If it is a rich text, the oridinal text is filtered through a rixh text box control in order to c correct eventual formatting errors.
Private Attributes
string _header = null
string _footer = null
string Heading = null
string OrderCode = null
string Orderer = null
string OrdererAddress = null
string SampleTimeString = null
string ReceptionTimeString = null
string CompletionTimeString = null
string _diagnosisClinicalText = null
string _innerDescription = null
string _outerDescription = null
string _macroDescription = null
string _microDescription = null
string _macroDescription2 = null
string _microDescription2 = null
string _temporaryOpinion = null
string _appendix = null
string _diagnosisPatoHistologicalText = null
string _signTimePart = null
string _signTimeFinish = null
string _signTimeAddition = null
FindingsPatient Patient = null
FindingsPhysician Physician = null
FindingsPhysician SignerPart = null
FindingsPhysician SignerFinish = null
FindingsPhysician SignerAddition = null
List< DiagnosisCodeClass > DiagnosesClinical = new List<DiagnosisCodeClass>()
List< DiagnosisCodeClass > DiagnosesPatoHistological = new List<DiagnosisCodeClass>()
List< RalatedObservation > FormerFindings = new List<RalatedObservation>()
List< RalatedObservation > ParentObservations = new List<RalatedObservation>()
List< RalatedObservation > ChildObservations = new List<RalatedObservation>()
DateTime CreationTime = DateTime.Now
DateTime? SampleTime = null
DateTime? ReceptionTime = null
DateTime? CompletionTime = null
int? MsgEventId = null
Static Private Attributes
static object LockRtb = new object()
static RichTextBox Rtb = null
Additional Inherited Members
Protected Attributes inherited from IG.Lib.ParsableXmlObject
XmlBuilder Data = new XmlBuilder()
Static Protected Attributes inherited from IG.Lib.MsgBase
static string LabexIdLowercase = null
Detailed Description
Class for holding and manipulating the data about observation order. Includes parsing an XML file, storing data internally, and transcription of read data to a PADO object that enables saving data to a database.
Constructor & Destructor Documentation
DocFindings()
IG.Lib.DocFindings.DocFindings () inline
Default constructor, sets the type information.
Member Function Documentation
Read() [1/2]
override void IG.Lib.DocFindings.Read () inline virtual
Reads msg data from the internal XML document containing the msg.
Implements IG.Lib.ParsableXmlObject.
References IG.Lib.ParsableXmlObject.Data.
Referenced by IGTest.FindingsRtfTest.btnImportInput_Click(), IGTest.FindingsRtfTest.btnImportInputRtf_Click(), IGTest.FindingsRtfTest.btnImportOutput_Click(), IGTest.FindingsRtfTest.btnImportOutputRtf_Click(), and IGTest.ProgramIGTest.TestFindings().
Read() [2/2]
override void IG.Lib.DocFindings.Read (XmlParser data) inline virtual
Read msg data from an XML document containing the msg.
Parameters
doc Document containing the msg.
Implements IG.Lib.ParsableXmlObject.
References IG.Lib.FindingsPhysician.Appellation, IG.Lib.DocFindings.Appendix, IG.Lib.FindingsConsttBase.AppendixElement, IG.Lib.XmlParser.Back(), IG.Lib.XmlParser.BackToMark(), IG.Lib.DocFindings.CheckConsistency(), IG.Lib.DiagnosisCodeClass.Code, IG.Lib.DiagnosisCodeClass.CodeSystem, IG.Lib.DocFindings.CompletionTime, IG.Lib.FindingsConsttBase.CompletionTimeElement, IG.Lib.DocFindings.CompletionTimeString, IG.Lib.DocFindings.Const, IG.Lib.MsgConst.Const, IG.Lib.MsgConst.ConvertTime(), IG.Lib.XmlParser.Current, IG.Lib.IReporterBase.Depth, IG.Lib.DiagnosisCodeClass.Description, IG.Lib.DocFindings.DiagnosesClinical, IG.Lib.DocFindings.DiagnosesPatoHistological, IG.Lib.FindingsConsttBase.DiagnosisClinicalContainter, IG.Lib.DocFindings.DiagnosisClinicalText, IG.Lib.FindingsConsttBase.DiagnosisCodeClassificationSystemElement, IG.Lib.FindingsConsttBase.DiagnosisCodeCodeElement, IG.Lib.FindingsConsttBase.DiagnosisCodeCollectionContainter, IG.Lib.FindingsConsttBase.DiagnosisCodeContainer, IG.Lib.FindingsConsttBase.DiagnosisCodeDescriptionElement, IG.Lib.FindingsConsttBase.DiagnosisPatoHistologicalContainer, IG.Lib.DocFindings.DiagnosisPatoHistologicalText, IG.Lib.FindingsConsttBase.DiagnosisTextElement, IG.Lib.XmlParser.Doc, IG.Lib.FindingsPhysician.FamilyName, IG.Lib.DocFindings.Footer, IG.Lib.FindingsConsttBase.Footerelement, IG.Lib.FindingsConsttBase.FormerFindingContainer, IG.Lib.FindingsConsttBase.FormerFindingReferenceElement, IG.Lib.DocFindings.FormerFindings, IG.Lib.FindingsConsttBase.FormerFindingsCollectionContainer, IG.Lib.FindingsConsttBase.FormerFinfingRemarkElement, IG.Lib.MsgConstCommon.GenderFemale, IG.Lib.MsgConstCommon.GenderMale, IG.Lib.XmlParser.GoToRoot(), IG.Lib.FindingsConsttBase.HeadContainer, IG.Lib.DocFindings.Header, IG.Lib.FindingsConsttBase.HeaderElement, IG.Lib.DocFindings.Heading, IG.Lib.FindingsConsttBase.HeadingElement, IG.Lib.DocFindings.Id, IG.Lib.Patient.IsMale, IG.Lib.DocFindings.MacroDescription, IG.Lib.FindingsConsttBase.MacroDescriptionElement, IG.Lib.DocFindings.MicroDescription, IG.Lib.FindingsConsttBase.MicroDescriptionElement, IG.Lib.FindingsPhysician.MiddleNames, IG.Lib.DocFindings.MsgEventId, IG.Lib.Patient.Name, IG.Lib.FindingsPhysician.Name, IG.Lib.XmlParser.Name, IG.Lib.XmlParser.NextElement(), IG.Lib.XmlParser.NextOrCurrentElement(), IG.Lib.RalatedObservation.ObservationReference, IG.Lib.DocFindings.OrderCode, IG.Lib.FindingsConsttBase.OrderCodeElement, IG.Lib.DocFindings.Orderer, IG.Lib.DocFindings.OrdererAddress, IG.Lib.FindingsConsttBase.OrdererAddresselement, IG.Lib.FindingsConsttBase.OrdererElement, IG.Lib.FindingsConsttBase.PatientAddressElement, IG.Lib.FindingsConsttBase.PatientAgeMonthsElement, IG.Lib.FindingsConsttBase.PatientContainer, IG.Lib.FindingsConsttBase.PatientDateOfBirthElement, IG.Lib.FindingsConsttBase.PatientFamilyNameElement, IG.Lib.FindingsConsttBase.PatientMiddleNamesElement, IG.Lib.FindingsConsttBase.PatientNameElement, IG.Lib.FindingsConsttBase.PatientPersonIdElement, IG.Lib.FindingsConsttBase.PatientSexElement, IG.Lib.DocFindings.Physician, IG.Lib.FindingsConsttBase.PhysicianAppellationElement, IG.Lib.FindingsConsttBase.PhysicianContainer, IG.Lib.FindingsConsttBase.PhysicianFamilyNameElement, IG.Lib.FindingsConsttBase.PhysicianMiddleNamesElement, IG.Lib.FindingsConsttBase.PhysicianNameElement, IG.Lib.FindingsConsttBase.PhysicianTitleElement, IG.Lib.FindingsConsttBase.PhysicianTitleRightElement, IG.Lib.ParsableXmlObject.R, IG.Lib.DocFindings.ReceptionTime, IG.Lib.FindingsConsttBase.ReceptionTimeElement, IG.Lib.DocFindings.ReceptionTimeString, IG.Lib.RalatedObservation.Remark, IG.Lib.ParsableXmlObject.AccummulatedReport.Report(), IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.ReporterBase.ReviseException(), IG.Lib.FindingsConsttBase.RootName, IG.Lib.DocFindings.SampleTime, IG.Lib.FindingsConsttBase.SampleTimeElement, IG.Lib.DocFindings.SampleTimeString, IG.Lib.XmlParser.SetMark(), IG.Lib.XmlParser.StepIn(), IG.Lib.DocFindings.TemporaryOpinion, IG.Lib.FindingsConsttBase.TemporaryOpinionElement, IG.Lib.FindingsPhysician.Title, IG.Lib.FindingsPhysician.TitleRight, IG.Lib.IReporterBase.TreatInfo, and IG.Lib.XmlParser.Value.
CheckConsistency()
override void IG.Lib.DocFindings.CheckConsistency (AccummulatedReport rep) inline virtual
Check correctness and consistency of data and creates a report on this.
Parameters
rep Object where error, warning and info reports are accumulated.
Reimplemented from IG.Lib.ParsableXmlObject.
References IG.Lib.ParsableXmlObject.AccummulatedReport.AddError(), and IG.Lib.ParsableXmlObject.AccummulatedReport.AddInfo().
Referenced by IG.Lib.DocFindings.Read().
EnsureCompatibilityBeforeXmlGeneration()
void IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration () inline
Performs the necessary corrections such that other Labex tools will work with the generated XML. This is necessary e.g. to show findings, since methods for doing taht can not cope with absent XML fields.
References IG.Lib.FindingsPhysician.Appellation, IG.Lib.DocFindings.Appendix, IG.Lib.DiagnosisCodeClass.Code, IG.Lib.DiagnosisCodeClass.CodeSystem, IG.Lib.DocFindings.CompatibilityMode, IG.Lib.DocFindings.CompletionTime, IG.Lib.DiagnosisCodeClass.Description, IG.Lib.DocFindings.DiagnosesClinical, IG.Lib.DocFindings.DiagnosesPatoHistological, IG.Lib.DocFindings.DiagnosisClinicalText, IG.Lib.DocFindings.DiagnosisPatoHistologicalText, IG.Lib.FindingsPhysician.FamilyName, IG.Lib.DocFindings.Footer, IG.Lib.DocFindings.FormerFindings, IG.Lib.DocFindings.Header, IG.Lib.DocFindings.Heading, IG.Lib.DocFindings.Id, IG.Lib.Patient.IsMale, IG.Lib.DocFindings.MacroDescription, IG.Lib.DocFindings.MicroDescription, IG.Lib.FindingsPhysician.MiddleNames, IG.Lib.DocFindings.MsgEventId, IG.Lib.Patient.Name, IG.Lib.FindingsPhysician.Name, IG.Lib.RalatedObservation.ObservationReference, IG.Lib.DocFindings.OrderCode, IG.Lib.DocFindings.Orderer, IG.Lib.DocFindings.OrdererAddress, IG.Lib.DocFindings.Physician, IG.Lib.DocFindings.ReceptionTime, IG.Lib.RalatedObservation.Remark, IG.Lib.DocFindings.SampleTime, IG.Lib.DocFindings.TemporaryOpinion, IG.Lib.FindingsPhysician.Title, and IG.Lib.FindingsPhysician.TitleRight.
Referenced by IG.Lib.DocFindings.ToXml().
IsRtf()
static bool IG.Lib.DocFindings.IsRtf (string str) inline static
Returns true if str is a valid rich text, or false otherwise.
References IG.Lib.DocFindings.LockRtb, and IG.Lib.DocFindings.Rtb.
Referenced by IG.Lib.DocFindings.ToRtf(), IG.Lib.DocFindings.ToRtfSet(), and IG.Lib.DocFindings.ToText().
ToRtf()
static string IG.Lib.DocFindings.ToRtf (string str) inline static
Returns a rich text that corresponds to the string argument. If the argument is already a rich text then the unchanged argument is returned, otherwise it is wrapped in RTF markup.
References IG.Lib.DocFindings.IsRtf(), IG.Lib.DocFindings.LockRtb, and IG.Lib.DocFindings.Rtb.
Referenced by IG.Lib.DocFindings.ConvertRtfField().
ToText()
static string IG.Lib.DocFindings.ToText (string str) inline static
Returns plain text that corresponds to the string argument. If the argument is a rich text then then text is extracted from it and returned, otherwise the unchanged argument is returned.
References IG.Lib.DocFindings.IsRtf(), IG.Lib.DocFindings.LockRtb, and IG.Lib.DocFindings.Rtb.
Referenced by IG.Lib.DocFindings.ConvertRtfField(), and IG.Lib.DocFindings.ConvertRtfFieldSet().
ConvertRtfField()
string IG.Lib.DocFindings.ConvertRtfField (string str) inline private
Aoutonomously converts text either to plain text or to RTF, dependent on the value of UsePlainText flag.
References IG.Lib.DocFindings.ToRtf(), IG.Lib.DocFindings.ToText(), and IG.Lib.DocFindings.UsePlainText.
ToRtfSet()
static string IG.Lib.DocFindings.ToRtfSet (string str) inline static private
Returns a rich text that corresponds to the string argument. If the argument is not a rich text then it is wrapped in RTF markup. If it is a rich text, the oridinal text is filtered through a rixh text box control in order to c correct eventual formatting errors.
References IG.Lib.DocFindings.IsRtf(), IG.Lib.DocFindings.LockRtb, and IG.Lib.DocFindings.Rtb.
Referenced by IG.Lib.DocFindings.ConvertRtfFieldSet().
ConvertRtfFieldSet()
string IG.Lib.DocFindings.ConvertRtfFieldSet (string str) inline private
Aoutonomously converts text either to plain text or to RTF, dependent on the value of UsePlainText flag.
References IG.Lib.DocFindings.ToRtfSet(), IG.Lib.DocFindings.ToText(), and IG.Lib.DocFindings.UsePlainText.
DateString() [1/2]
string IG.Lib.DocFindings.DateString (DateTime t) inline private
Converts date to a string for output.
Referenced by IG.Lib.DocFindings.DateString().
DateString() [2/2]
string IG.Lib.DocFindings.DateString (DateTime? t) inline private
Converts date to a string for output.
References IG.Lib.DocFindings.DateString().
ToString()
override string IG.Lib.DocFindings.ToString () inline
Returns a string describing contents of the current object.
References IG.Lib.DocFindings.Appendix, IG.Lib.DocFindings.CompletionTime, IG.Lib.DocFindings.CompletionTimeString, IG.Lib.IReporterBase.Depth, IG.Lib.DocFindings.DiagnosesClinical, IG.Lib.DocFindings.DiagnosesPatoHistological, IG.Lib.DocFindings.DiagnosisClinicalText, IG.Lib.DocFindings.DiagnosisPatoHistologicalText, IG.Lib.DocFindings.Footer, IG.Lib.DocFindings.FormerFindings, IG.Lib.DocFindings.Header, IG.Lib.DocFindings.Heading, IG.Lib.DocFindings.MacroDescription, IG.Lib.DocFindings.MacroDescription2, IG.Lib.MsgBase.MessageFile, IG.Lib.DocFindings.MicroDescription, IG.Lib.DocFindings.MicroDescription2, IG.Lib.DocFindings.OrderCode, IG.Lib.DocFindings.Orderer, IG.Lib.DocFindings.OrdererAddress, IG.Lib.DocFindings.Physician, IG.Lib.ParsableXmlObject.R, IG.Lib.DocFindings.ReceptionTime, IG.Lib.DocFindings.ReceptionTimeString, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.DocFindings.SampleTime, IG.Lib.DocFindings.SampleTimeString, IG.Lib.DocFindings.TemporaryOpinion, IG.Lib.Patient.ToString(), IG.Lib.FindingsPhysician.ToString(), and IG.Lib.IReporterBase.TreatInfo.
ToXml()
override XmlDocument IG.Lib.DocFindings.ToXml () inline virtual
Converts a msg to Xml and returns it.
Implements IG.Lib.ParsableXmlObject.
References IG.Lib.XmlBuilder.AddProcessingInstruction(), IG.Lib.FindingsPhysician.Appellation, IG.Lib.XmlBuilder.AppendChild(), IG.Lib.DocFindings.Appendix, IG.Lib.FindingsConsttBase.AppendixElement, IG.Lib.XmlParser.BackToMark(), IG.Lib.DiagnosisCodeClass.Code, IG.Lib.DiagnosisCodeClass.CodeSystem, IG.Lib.DocFindings.CompatibilityMode, IG.Lib.FindingsConsttBase.CompletionTimeElement, IG.Lib.DocFindings.CompletionTimeOutputString, IG.Lib.DocFindings.Const, IG.Lib.XmlBuilder.CreateElement(), IG.Lib.ParsableXmlObject.Data, IG.Lib.IReporterBase.Depth, IG.Lib.DiagnosisCodeClass.Description, IG.Lib.DocFindings.DiagnosesClinical, IG.Lib.DocFindings.DiagnosesPatoHistological, IG.Lib.FindingsConsttBase.DiagnosisClinicalContainter, IG.Lib.DocFindings.DiagnosisClinicalText, IG.Lib.FindingsConsttBase.DiagnosisCodeClassificationSystemElement, IG.Lib.FindingsConsttBase.DiagnosisCodeCodeElement, IG.Lib.FindingsConsttBase.DiagnosisCodeCollectionContainter, IG.Lib.FindingsConsttBase.DiagnosisCodeContainer, IG.Lib.FindingsConsttBase.DiagnosisCodeDescriptionElement, IG.Lib.FindingsConsttBase.DiagnosisPatoHistologicalContainer, IG.Lib.DocFindings.DiagnosisPatoHistologicalText, IG.Lib.FindingsConsttBase.DiagnosisTextElement, IG.Lib.ParsableXmlObject.Doc, IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), IG.Lib.FindingsPhysician.FamilyName, IG.Lib.DocFindings.Footer, IG.Lib.FindingsConsttBase.Footerelement, IG.Lib.FindingsConsttBase.FormerFindingContainer, IG.Lib.FindingsConsttBase.FormerFindingReferenceElement, IG.Lib.DocFindings.FormerFindings, IG.Lib.FindingsConsttBase.FormerFindingsCollectionContainer, IG.Lib.FindingsConsttBase.FormerFinfingRemarkElement, IG.Lib.XmlParser.GoToMark(), IG.Lib.FindingsConsttBase.HeadContainer, IG.Lib.DocFindings.Header, IG.Lib.FindingsConsttBase.HeaderElement, IG.Lib.DocFindings.Heading, IG.Lib.FindingsConsttBase.HeadingElement, IG.Lib.DocFindings.InnerDescription, IG.Lib.FindingsConsttBase.InnerDescriptionElement, IG.Lib.XmlBuilder.InsertAfter(), IG.Lib.DocFindings.MacroDescription, IG.Lib.DocFindings.MacroDescription2, IG.Lib.FindingsConsttBase.MacroDescriptionElement, IG.Lib.FindingsConsttBase.MacroDescriptionElement2, IG.Lib.DocFindings.MicroDescription, IG.Lib.DocFindings.MicroDescription2, IG.Lib.FindingsConsttBase.MicroDescriptionElement, IG.Lib.FindingsConsttBase.MicroDescriptionElement2, IG.Lib.FindingsPhysician.MiddleNames, IG.Lib.XmlBuilder.MoveToNewest(), IG.Lib.Patient.Name, IG.Lib.FindingsPhysician.Name, IG.Lib.XmlBuilder.NewDocument(), IG.Lib.RalatedObservation.ObservationReference, IG.Lib.DocFindings.OrderCode, IG.Lib.FindingsConsttBase.OrderCodeElement, IG.Lib.DocFindings.Orderer, IG.Lib.DocFindings.OrdererAddress, IG.Lib.FindingsConsttBase.OrdererAddresselement, IG.Lib.FindingsConsttBase.OrdererElement, IG.Lib.DocFindings.OuterDescription, IG.Lib.FindingsConsttBase.OuterDescriptionElement, IG.Lib.FindingsConsttBase.PatientAddressElement, IG.Lib.FindingsConsttBase.PatientAgeElement, IG.Lib.FindingsConsttBase.PatientAgeMonthsElement, IG.Lib.FindingsConsttBase.PatientContainer, IG.Lib.FindingsConsttBase.PatientDateOfBirthElement, IG.Lib.FindingsConsttBase.PatientFamilyNameElement, IG.Lib.FindingsConsttBase.PatientMiddleNamesElement, IG.Lib.FindingsConsttBase.PatientNameElement, IG.Lib.FindingsConsttBase.PatientPersonIdElement, IG.Lib.FindingsConsttBase.PatientSexElement, IG.Lib.DocFindings.Physician, IG.Lib.FindingsConsttBase.PhysicianAppellationElement, IG.Lib.FindingsConsttBase.PhysicianContainer, IG.Lib.FindingsConsttBase.PhysicianFamilyNameElement, IG.Lib.FindingsConsttBase.PhysicianMiddleNamesElement, IG.Lib.FindingsConsttBase.PhysicianNameElement, IG.Lib.FindingsConsttBase.PhysicianTitleElement, IG.Lib.FindingsConsttBase.PhysicianTitleRightElement, IG.Lib.ParsableXmlObject.R, IG.Lib.FindingsConsttBase.ReceptionTimeElement, IG.Lib.DocFindings.ReceptionTimeOutputString, IG.Lib.RalatedObservation.Remark, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.ReporterBase.ReviseException(), IG.Lib.FindingsConsttBase.RootName, IG.Lib.FindingsConsttBase.SampleTimeElement, IG.Lib.DocFindings.SampleTimeOutputString, IG.Lib.XmlBuilder.SetInnerText(), IG.Lib.XmlParser.SetMark(), IG.Lib.FindingsConsttBase.SignDateAdditionElement, IG.Lib.FindingsConsttBase.SignDateFinishElement, IG.Lib.FindingsConsttBase.SignDatePartElement, IG.Lib.FindingsConsttBase.SignerAdditionElement, IG.Lib.DocFindings.SignerAdditionString, IG.Lib.FindingsConsttBase.SignerFinishElement, IG.Lib.DocFindings.SignerFinishString, IG.Lib.FindingsConsttBase.SignerPartElement, IG.Lib.DocFindings.SignerPartString, IG.Lib.DocFindings.SignTimeAdditionString, IG.Lib.DocFindings.SignTimeFinishString, IG.Lib.DocFindings.SignTimePartString, IG.Lib.DocFindings.TemporaryOpinion, IG.Lib.FindingsConsttBase.TemporaryOpinionElement, IG.Lib.FindingsPhysician.Title, IG.Lib.FindingsPhysician.TitleRight, IG.Lib.Patient.ToString(), IG.Lib.IReporterBase.TreatInfo, IG.Lib.FindingsConsttBase.ViewInstructionData, IG.Lib.FindingsConsttBase.ViewInstructionTarget, IG.Lib.DocFindings.XmlAddStyleSheetInstruction, and IG.Lib.DocFindings.XmlCreateInputFormat.
Referenced by IGTest.FindingsRtfTest.btnSaveOutput_Click(), IGTest.FindingsRtfTest.btnSaveOutputRtf_Click(), and IGTest.ProgramIGTest.TestFindings().
Member Data Documentation
LockRtb
object IG.Lib.DocFindings.LockRtb = new object() static private
Referenced by IG.Lib.DocFindings.IsRtf(), IG.Lib.DocFindings.ToRtf(), IG.Lib.DocFindings.ToRtfSet(), and IG.Lib.DocFindings.ToText().
Rtb
RichTextBox IG.Lib.DocFindings.Rtb = null static private
Referenced by IG.Lib.DocFindings.IsRtf(), IG.Lib.DocFindings.ToRtf(), IG.Lib.DocFindings.ToRtfSet(), and IG.Lib.DocFindings.ToText().
CompatibilityMode
bool IG.Lib.DocFindings.CompatibilityMode = false
When this flag is set, operations are performed in compatible mode, such that results and inputs are compatible with the current state (this mainly refers to what Mirjam produced)
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), and IG.Lib.DocFindings.ToXml().
UsePlainText
bool IG.Lib.DocFindings.UsePlainText = false
If true then plain text is used for fields that are otherwise in RTF.
Referenced by IGTest.FindingsRtfTest.btnImportInput_Click(), IGTest.FindingsRtfTest.btnImportInputRtf_Click(), IGTest.FindingsRtfTest.btnImportOutput_Click(), IGTest.FindingsRtfTest.btnImportOutputRtf_Click(), IGTest.FindingsRtfTest.btnSaveOutput_Click(), IGTest.FindingsRtfTest.btnSaveOutputRtf_Click(), IG.Lib.DocFindings.ConvertRtfField(), and IG.Lib.DocFindings.ConvertRtfFieldSet().
ObservationTypeFlag
ObservationType IG.Lib.DocFindings.ObservationTypeFlag = ObservationType.Unknown
_header
string IG.Lib.DocFindings._header = null private
_footer
string IG.Lib.DocFindings._footer = null private
Heading
string IG.Lib.DocFindings.Heading = null private
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), IG.Lib.DocFindings.Read(), IG.Lib.DocFindings.ToString(), and IG.Lib.DocFindings.ToXml().
OrderCode
string IG.Lib.DocFindings.OrderCode = null private
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), IG.Lib.DocFindings.Read(), IG.Lib.DocFindings.ToString(), and IG.Lib.DocFindings.ToXml().
Orderer
string IG.Lib.DocFindings.Orderer = null private
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), IG.Lib.DocFindings.Read(), IG.Lib.DocFindings.ToString(), and IG.Lib.DocFindings.ToXml().
OrdererAddress
string IG.Lib.DocFindings.OrdererAddress = null private
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), IG.Lib.DocFindings.Read(), IG.Lib.DocFindings.ToString(), and IG.Lib.DocFindings.ToXml().
SampleTimeString
string IG.Lib.DocFindings.SampleTimeString = null private
Referenced by IG.Lib.DocFindings.Read(), and IG.Lib.DocFindings.ToString().
ReceptionTimeString
string IG.Lib.DocFindings.ReceptionTimeString = null private
Referenced by IG.Lib.DocFindings.Read(), and IG.Lib.DocFindings.ToString().
CompletionTimeString
string IG.Lib.DocFindings.CompletionTimeString = null private
Referenced by IG.Lib.DocFindings.Read(), and IG.Lib.DocFindings.ToString().
_diagnosisClinicalText
string IG.Lib.DocFindings._diagnosisClinicalText = null private
_innerDescription
string IG.Lib.DocFindings._innerDescription = null private
_outerDescription
string IG.Lib.DocFindings._outerDescription = null private
_macroDescription
string IG.Lib.DocFindings._macroDescription = null private
_microDescription
string IG.Lib.DocFindings._microDescription = null private
_macroDescription2
string IG.Lib.DocFindings._macroDescription2 = null private
_microDescription2
string IG.Lib.DocFindings._microDescription2 = null private
_temporaryOpinion
string IG.Lib.DocFindings._temporaryOpinion = null private
_appendix
string IG.Lib.DocFindings._appendix = null private
_diagnosisPatoHistologicalText
string IG.Lib.DocFindings._diagnosisPatoHistologicalText = null private
_signTimePart
string IG.Lib.DocFindings._signTimePart = null private
_signTimeFinish
string IG.Lib.DocFindings._signTimeFinish = null private
_signTimeAddition
string IG.Lib.DocFindings._signTimeAddition = null private
Patient
FindingsPatient IG.Lib.DocFindings.Patient = null private
Physician
FindingsPhysician IG.Lib.DocFindings.Physician = null private
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), IG.Lib.DocFindings.Read(), IG.Lib.DocFindings.ToString(), and IG.Lib.DocFindings.ToXml().
SignerPart
FindingsPhysician IG.Lib.DocFindings.SignerPart = null private
SignerFinish
FindingsPhysician IG.Lib.DocFindings.SignerFinish = null private
SignerAddition
FindingsPhysician IG.Lib.DocFindings.SignerAddition = null private
DiagnosesClinical
List<DiagnosisCodeClass> IG.Lib.DocFindings.DiagnosesClinical = new List<DiagnosisCodeClass>() private
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), IG.Lib.DocFindings.Read(), IG.Lib.DocFindings.ToString(), and IG.Lib.DocFindings.ToXml().
DiagnosesPatoHistological
List<DiagnosisCodeClass> IG.Lib.DocFindings.DiagnosesPatoHistological = new List<DiagnosisCodeClass>() private
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), IG.Lib.DocFindings.Read(), IG.Lib.DocFindings.ToString(), and IG.Lib.DocFindings.ToXml().
FormerFindings
List<RalatedObservation> IG.Lib.DocFindings.FormerFindings = new List<RalatedObservation>() private
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), IG.Lib.DocFindings.Read(), IG.Lib.DocFindings.ToString(), and IG.Lib.DocFindings.ToXml().
ParentObservations
List<RalatedObservation> IG.Lib.DocFindings.ParentObservations = new List<RalatedObservation>() private
ChildObservations
List<RalatedObservation> IG.Lib.DocFindings.ChildObservations = new List<RalatedObservation>() private
CreationTime
DateTime IG.Lib.DocFindings.CreationTime = DateTime.Now private
SampleTime
DateTime? IG.Lib.DocFindings.SampleTime = null private
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), IG.Lib.DocFindings.Read(), and IG.Lib.DocFindings.ToString().
ReceptionTime
DateTime? IG.Lib.DocFindings.ReceptionTime = null private
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), IG.Lib.DocFindings.Read(), and IG.Lib.DocFindings.ToString().
CompletionTime
DateTime? IG.Lib.DocFindings.CompletionTime = null private
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), IG.Lib.DocFindings.Read(), and IG.Lib.DocFindings.ToString().
Id
int? IG.Lib.DocFindings.Id = null
Id of the Findings database rsr; this is null when Finding data is not read from the database.
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), and IG.Lib.DocFindings.Read().
MsgEventId
int? IG.Lib.DocFindings.MsgEventId = null private
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), and IG.Lib.DocFindings.Read().
XmlCreateInputFormat
bool IG.Lib.DocFindings.XmlCreateInputFormat = false
If true then XML is created for data in input format, which means that all fields can be read back when parding that XML. Default is false, in this case the generated XML is in output format more suitable for printing and jviewing (i.e. better for human reading), but in this form some fields (data and gender fields) can not be interpreted correctly when such a file is parsed.
Referenced by IGTest.ProgramIGTest.TestFindings(), and IG.Lib.DocFindings.ToXml().
XmlAddStyleSheetInstruction
bool IG.Lib.DocFindings.XmlAddStyleSheetInstruction = true
If true then processing instruction is added to the XML documents created from data that enables viewing in browser in a human readable form.
Referenced by IG.Lib.DocFindings.ToXml().
Property Documentation
Const
new FindingsConst IG.Lib.DocFindings.Const get protected
Referenced by IG.Lib.DocFindings.Read(), and IG.Lib.DocFindings.ToXml().
InnerDescription
string IG.Lib.DocFindings.InnerDescription get set
Inner description.
Referenced by IG.Lib.DocFindings.ToXml().
OuterDescription
string IG.Lib.DocFindings.OuterDescription get set
Outer description.
Referenced by IG.Lib.DocFindings.ToXml().
MacroDescription
string IG.Lib.DocFindings.MacroDescription get set
Macro description.
Referenced by IGTest.FindingsRtfTest.btnImportInput_Click(), IGTest.FindingsRtfTest.btnImportInputRtf_Click(), IGTest.FindingsRtfTest.btnImportOutput_Click(), IGTest.FindingsRtfTest.btnImportOutputRtf_Click(), IGTest.FindingsRtfTest.btnSaveOutput_Click(), IGTest.FindingsRtfTest.btnSaveOutputRtf_Click(), IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), IG.Lib.DocFindings.Read(), IG.Lib.DocFindings.ToString(), and IG.Lib.DocFindings.ToXml().
MicroDescription
string IG.Lib.DocFindings.MicroDescription get set
Micro description.
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), IG.Lib.DocFindings.Read(), IG.Lib.DocFindings.ToString(), and IG.Lib.DocFindings.ToXml().
MacroDescription2
string IG.Lib.DocFindings.MacroDescription2 get set
Macro description.
Referenced by IG.Lib.DocFindings.ToString(), and IG.Lib.DocFindings.ToXml().
MicroDescription2
string IG.Lib.DocFindings.MicroDescription2 get set
Micro description.
Referenced by IG.Lib.DocFindings.ToString(), and IG.Lib.DocFindings.ToXml().
DiagnosisClinicalText
string IG.Lib.DocFindings.DiagnosisClinicalText get set
Free text of clinical diagnosis.
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), IG.Lib.DocFindings.Read(), IG.Lib.DocFindings.ToString(), and IG.Lib.DocFindings.ToXml().
DiagnosisPatoHistologicalText
string IG.Lib.DocFindings.DiagnosisPatoHistologicalText get set
Free text of patohistological diagnosis.
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), IG.Lib.DocFindings.Read(), IG.Lib.DocFindings.ToString(), and IG.Lib.DocFindings.ToXml().
TemporaryOpinion
string IG.Lib.DocFindings.TemporaryOpinion get set
Temporary opinion.
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), IG.Lib.DocFindings.Read(), IG.Lib.DocFindings.ToString(), and IG.Lib.DocFindings.ToXml().
Appendix
string IG.Lib.DocFindings.Appendix get set
Appendix.
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), IG.Lib.DocFindings.Read(), IG.Lib.DocFindings.ToString(), and IG.Lib.DocFindings.ToXml().
Header
string IG.Lib.DocFindings.Header get set
Header.
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), IG.Lib.DocFindings.Read(), IG.Lib.DocFindings.ToString(), and IG.Lib.DocFindings.ToXml().
Footer
string IG.Lib.DocFindings.Footer get set
Footer.
Referenced by IG.Lib.DocFindings.EnsureCompatibilityBeforeXmlGeneration(), IG.Lib.DocFindings.Read(), IG.Lib.DocFindings.ToString(), and IG.Lib.DocFindings.ToXml().
IsHistological
bool IG.Lib.DocFindings.IsHistological get
IsCytological
bool IG.Lib.DocFindings.IsCytological get
IsPatological
bool IG.Lib.DocFindings.IsPatological get
SignerPartString
string IG.Lib.DocFindings.SignerPartString get private set
Referenced by IG.Lib.DocFindings.ToXml().
SignerFinishString
string IG.Lib.DocFindings.SignerFinishString get private set
Referenced by IG.Lib.DocFindings.ToXml().
SignerAdditionString
string IG.Lib.DocFindings.SignerAdditionString get private set
Referenced by IG.Lib.DocFindings.ToXml().
SignTimePartString
string IG.Lib.DocFindings.SignTimePartString get private set
Referenced by IG.Lib.DocFindings.ToXml().
SignTimeFinishString
string IG.Lib.DocFindings.SignTimeFinishString get private set
Referenced by IG.Lib.DocFindings.ToXml().
SignTimeAdditionString
string IG.Lib.DocFindings.SignTimeAdditionString get private set
Referenced by IG.Lib.DocFindings.ToXml().
SampleTimeOutputString
string IG.Lib.DocFindings.SampleTimeOutputString get
Referenced by IG.Lib.DocFindings.ToXml().
ReceptionTimeOutputString
string IG.Lib.DocFindings.ReceptionTimeOutputString get
Referenced by IG.Lib.DocFindings.ToXml().
CompletionTimeOutputString
string IG.Lib.DocFindings.CompletionTimeOutputString get
Referenced by IG.Lib.DocFindings.ToXml().
The documentation for this class was generated from the following file:
igtest/tmp_prem/prlab/LabexBis/Findings.cs