Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGETF2 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGETF2 Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGETF2 (DLAMCH dlamch, IDAMAX idamax, DGER dger, DSCAL dscal, DSWAP dswap, XERBLA xerbla)
DGETF2 ()
void Run (int M, int N, ref double[] A, int offset_a, int LDA, ref int[] IPIV, int offset_ipiv, ref int INFO)
Private Attributes
DLAMCH _dlamch
IDAMAX _idamax
DGER _dger
DSCAL _dscal
DSWAP _dswap
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGETF2 computes an LU factorization of a general m-by-n matrix A using partial pivoting with row interchanges.
The factorization has the form A = P * L * U where P is a permutation matrix, L is lower triangular with unit diagonal elements (lower trapezoidal if m .GT. n), and U is upper triangular (upper trapezoidal if m .LT. n).
This is the right-looking Level 2 BLAS version of the algorithm.
/summary>
Constructor & Destructor Documentation
DGETF2() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGETF2.DGETF2 (DLAMCH dlamch, IDAMAX idamax, DGER dger, DSCAL dscal, DSWAP dswap, XERBLA xerbla) inline
DGETF2() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGETF2.DGETF2 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGETF2.Run (int M, int N, ref double[] A, int offset_a, int LDA, ref int[] IPIV, int offset_ipiv, ref int INFO) inline
Purpose
DGETF2 computes an LU factorization of a general m-by-n matrix A using partial pivoting with row interchanges.
The factorization has the form A = P * L * U where P is a permutation matrix, L is lower triangular with unit diagonal elements (lower trapezoidal if m .GT. n), and U is upper triangular (upper trapezoidal if m .LT. n).
This is the right-looking Level 2 BLAS version of the algorithm.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the m by n matrix to be factored. On exit, the factors L and U from the factorization A = P*L*U; the unit diagonal elements of L are not stored. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
IPIV (output) INTEGER array, dimension (min(M,N)) The pivot indices; for 1 .LE. i .LE. min(M,N), row i of the matrix was interchanged with row IPIV(i). /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -k, the k-th argument had an illegal value .GT. 0: if INFO = k, U(k,k) is exactly zero. The factorization has been completed, but the factor U is exactly singular, and division by zero will occur if it is used to solve a system of equations. /param>
References DotNumerics.LinearAlgebra.CSLapack.DGETF2.ONE, DotNumerics.LinearAlgebra.CSLapack.DSWAP.Run(), DotNumerics.LinearAlgebra.CSLapack.IDAMAX.Run(), DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DGER.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGETF2.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGETRF.Run().
Member Data Documentation
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DGETF2._dlamch private
_idamax
IDAMAX DotNumerics.LinearAlgebra.CSLapack.DGETF2._idamax private
_dger
DGER DotNumerics.LinearAlgebra.CSLapack.DGETF2._dger private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DGETF2._dscal private
_dswap
DSWAP DotNumerics.LinearAlgebra.CSLapack.DGETF2._dswap private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGETF2._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGETF2.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGETF2.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DGETF2.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGETF2.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgetf2.cs