Doc: IGLib EXTENDED: IG.Forms.AlignmentControl Class Reference
IG.Forms.AlignmentControl Class Reference
Control for setting horizontal and vertical alignment of items.
Public Member Functions
AlignmentControl ()
AlignmentControl ()
AlignmentControl ()
Protected Member Functions
void OnValueChanged (object sender, EventArgs eventArgs)
Triggers the ValueChanged event.
override void Dispose (bool disposing)
Clean up any resources being used.
void OnValueChanged (object sender, EventArgs eventArgs)
Triggers the ValueChanged event.
override void Dispose (bool disposing)
Clean up any resources being used.
void OnValueChanged (object sender, EventArgs eventArgs)
Triggers the ValueChanged event.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
Alignment _alignment = new Alignment()
Properties
string Title [get, set]
Text displayed in the title label of the control.
Alignment Alignment [get, set]
Events
EventHandler ValueChanged
Event that occurs when the value of alignment changes.
Private Member Functions
void AnyControl_CheckChanged (object sender, EventArgs e)
Common things for event handlers executing when any of the radio buttons changes checked status.
void rbHorizontalNone_CheckedChanged (object sender, EventArgs e)
void rbHorizontalLeft_CheckedChanged (object sender, EventArgs e)
void rbHorizontalCentered_CheckedChanged (object sender, EventArgs e)
void rbHorizontalRight_CheckedChanged (object sender, EventArgs e)
void rbVerticalNone_CheckedChanged (object sender, EventArgs e)
void rbVerticalTop_CheckedChanged (object sender, EventArgs e)
void rbVerticalCentered_CheckedChanged (object sender, EventArgs e)
void rbVerticalBottom_CheckedChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void AnyControl_CheckChanged (object sender, EventArgs e)
Common things for event handlers executing when any of the radio buttons changes checked status.
void rbHorizontalNone_CheckedChanged (object sender, EventArgs e)
void rbHorizontalLeft_CheckedChanged (object sender, EventArgs e)
void rbHorizontalCentered_CheckedChanged (object sender, EventArgs e)
void rbHorizontalRight_CheckedChanged (object sender, EventArgs e)
void rbVerticalNone_CheckedChanged (object sender, EventArgs e)
void rbVerticalTop_CheckedChanged (object sender, EventArgs e)
void rbVerticalCentered_CheckedChanged (object sender, EventArgs e)
void rbVerticalBottom_CheckedChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void AnyControl_CheckChanged (object sender, EventArgs e)
Common things for event handlers executing when any of the radio buttons changes checked status.
void rbHorizontalNone_CheckedChanged (object sender, EventArgs e)
void rbHorizontalLeft_CheckedChanged (object sender, EventArgs e)
void rbHorizontalCentered_CheckedChanged (object sender, EventArgs e)
void rbHorizontalRight_CheckedChanged (object sender, EventArgs e)
void rbVerticalNone_CheckedChanged (object sender, EventArgs e)
void rbVerticalTop_CheckedChanged (object sender, EventArgs e)
void rbVerticalCentered_CheckedChanged (object sender, EventArgs e)
void rbVerticalBottom_CheckedChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Label lblHorizontal
System.Windows.Forms.RadioButton rbHorizontalRight
System.Windows.Forms.RadioButton rbHorizontalCentered
System.Windows.Forms.RadioButton rbHorizontalLeft
System.Windows.Forms.RadioButton rbHorizontalNone
System.Windows.Forms.Label lblVertical
System.Windows.Forms.RadioButton rbVerticalBottom
System.Windows.Forms.RadioButton rbVerticalMiddle
System.Windows.Forms.RadioButton rbVerticalTop
System.Windows.Forms.RadioButton rbVerticalNone
System.Windows.Forms.GroupBox pnlOuter
System.Windows.Forms.Panel pnlHorizontal
System.Windows.Forms.Panel pnlVertical
Detailed Description
Control for setting horizontal and vertical alignment of items.
$A Igor Oct09;
Constructor & Destructor Documentation
AlignmentControl() [1/3]
IG.Forms.AlignmentControl.AlignmentControl () inline
References IG.Forms.AlignmentControl.InitializeComponent().
AlignmentControl() [2/3]
IG.Forms.AlignmentControl.AlignmentControl () inline
References IG.Forms.AlignmentControl.InitializeComponent().
AlignmentControl() [3/3]
IG.Forms.AlignmentControl.AlignmentControl () inline
References IG.Forms.AlignmentControl.InitializeComponent().
Member Function Documentation
OnValueChanged() [1/3]
void IG.Forms.AlignmentControl.OnValueChanged (object sender, EventArgs eventArgs) inline protected
Triggers the ValueChanged event.
References IG.Forms.AlignmentControl.Alignment, and IG.Forms.AlignmentControl.ValueChanged.
Referenced by IG.Forms.AlignmentControl.AnyControl_CheckChanged(), IG.Forms.AlignmentControl.rbHorizontalCentered_CheckedChanged(), IG.Forms.AlignmentControl.rbHorizontalLeft_CheckedChanged(), IG.Forms.AlignmentControl.rbHorizontalRight_CheckedChanged(), IG.Forms.AlignmentControl.rbVerticalBottom_CheckedChanged(), IG.Forms.AlignmentControl.rbVerticalCentered_CheckedChanged(), IG.Forms.AlignmentControl.rbVerticalNone_CheckedChanged(), and IG.Forms.AlignmentControl.rbVerticalTop_CheckedChanged().
AnyControl_CheckChanged() [1/3]
void IG.Forms.AlignmentControl.AnyControl_CheckChanged (object sender, EventArgs e) inline private
Common things for event handlers executing when any of the radio buttons changes checked status.
Parameters
sender
e
References IG.Forms.AlignmentControl.OnValueChanged().
Referenced by IG.Forms.AlignmentControl.rbHorizontalNone_CheckedChanged().
rbHorizontalNone_CheckedChanged() [1/3]
void IG.Forms.AlignmentControl.rbHorizontalNone_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.AnyControl_CheckChanged().
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
rbHorizontalLeft_CheckedChanged() [1/3]
void IG.Forms.AlignmentControl.rbHorizontalLeft_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
rbHorizontalCentered_CheckedChanged() [1/3]
void IG.Forms.AlignmentControl.rbHorizontalCentered_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
rbHorizontalRight_CheckedChanged() [1/3]
void IG.Forms.AlignmentControl.rbHorizontalRight_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
rbVerticalNone_CheckedChanged() [1/3]
void IG.Forms.AlignmentControl.rbVerticalNone_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
rbVerticalTop_CheckedChanged() [1/3]
void IG.Forms.AlignmentControl.rbVerticalTop_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
rbVerticalCentered_CheckedChanged() [1/3]
void IG.Forms.AlignmentControl.rbVerticalCentered_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
rbVerticalBottom_CheckedChanged() [1/3]
void IG.Forms.AlignmentControl.rbVerticalBottom_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
Dispose() [1/3]
override void IG.Forms.AlignmentControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.AlignmentControl.components.
InitializeComponent() [1/3]
void IG.Forms.AlignmentControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.AlignmentControl.lblHorizontal, IG.Forms.AlignmentControl.lblVertical, IG.Forms.AlignmentControl.pnlHorizontal, IG.Forms.AlignmentControl.pnlOuter, IG.Forms.AlignmentControl.pnlVertical, IG.Forms.AlignmentControl.rbHorizontalCentered, IG.Forms.AlignmentControl.rbHorizontalCentered_CheckedChanged(), IG.Forms.AlignmentControl.rbHorizontalLeft, IG.Forms.AlignmentControl.rbHorizontalLeft_CheckedChanged(), IG.Forms.AlignmentControl.rbHorizontalNone, IG.Forms.AlignmentControl.rbHorizontalNone_CheckedChanged(), IG.Forms.AlignmentControl.rbHorizontalRight, IG.Forms.AlignmentControl.rbHorizontalRight_CheckedChanged(), IG.Forms.AlignmentControl.rbVerticalBottom, IG.Forms.AlignmentControl.rbVerticalBottom_CheckedChanged(), IG.Forms.AlignmentControl.rbVerticalCentered_CheckedChanged(), IG.Forms.AlignmentControl.rbVerticalMiddle, IG.Forms.AlignmentControl.rbVerticalNone, IG.Forms.AlignmentControl.rbVerticalNone_CheckedChanged(), IG.Forms.AlignmentControl.rbVerticalTop, and IG.Forms.AlignmentControl.rbVerticalTop_CheckedChanged().
Referenced by IG.Forms.AlignmentControl.AlignmentControl().
OnValueChanged() [2/3]
void IG.Forms.AlignmentControl.OnValueChanged (object sender, EventArgs eventArgs) inline protected
Triggers the ValueChanged event.
References IG.Forms.AlignmentControl.Alignment, and IG.Forms.AlignmentControl.ValueChanged.
AnyControl_CheckChanged() [2/3]
void IG.Forms.AlignmentControl.AnyControl_CheckChanged (object sender, EventArgs e) inline private
Common things for event handlers executing when any of the radio buttons changes checked status.
Parameters
sender
e
References IG.Forms.AlignmentControl.OnValueChanged().
rbHorizontalNone_CheckedChanged() [2/3]
void IG.Forms.AlignmentControl.rbHorizontalNone_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.AnyControl_CheckChanged().
rbHorizontalLeft_CheckedChanged() [2/3]
void IG.Forms.AlignmentControl.rbHorizontalLeft_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
rbHorizontalCentered_CheckedChanged() [2/3]
void IG.Forms.AlignmentControl.rbHorizontalCentered_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
rbHorizontalRight_CheckedChanged() [2/3]
void IG.Forms.AlignmentControl.rbHorizontalRight_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
rbVerticalNone_CheckedChanged() [2/3]
void IG.Forms.AlignmentControl.rbVerticalNone_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
rbVerticalTop_CheckedChanged() [2/3]
void IG.Forms.AlignmentControl.rbVerticalTop_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
rbVerticalCentered_CheckedChanged() [2/3]
void IG.Forms.AlignmentControl.rbVerticalCentered_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
rbVerticalBottom_CheckedChanged() [2/3]
void IG.Forms.AlignmentControl.rbVerticalBottom_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
Dispose() [2/3]
override void IG.Forms.AlignmentControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.AlignmentControl.components.
InitializeComponent() [2/3]
void IG.Forms.AlignmentControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.AlignmentControl.lblHorizontal, IG.Forms.AlignmentControl.lblVertical, IG.Forms.AlignmentControl.pnlHorizontal, IG.Forms.AlignmentControl.pnlOuter, IG.Forms.AlignmentControl.pnlVertical, IG.Forms.AlignmentControl.rbHorizontalCentered, IG.Forms.AlignmentControl.rbHorizontalCentered_CheckedChanged(), IG.Forms.AlignmentControl.rbHorizontalLeft, IG.Forms.AlignmentControl.rbHorizontalLeft_CheckedChanged(), IG.Forms.AlignmentControl.rbHorizontalNone, IG.Forms.AlignmentControl.rbHorizontalNone_CheckedChanged(), IG.Forms.AlignmentControl.rbHorizontalRight, IG.Forms.AlignmentControl.rbHorizontalRight_CheckedChanged(), IG.Forms.AlignmentControl.rbVerticalBottom, IG.Forms.AlignmentControl.rbVerticalBottom_CheckedChanged(), IG.Forms.AlignmentControl.rbVerticalCentered_CheckedChanged(), IG.Forms.AlignmentControl.rbVerticalMiddle, IG.Forms.AlignmentControl.rbVerticalNone, IG.Forms.AlignmentControl.rbVerticalNone_CheckedChanged(), IG.Forms.AlignmentControl.rbVerticalTop, and IG.Forms.AlignmentControl.rbVerticalTop_CheckedChanged().
OnValueChanged() [3/3]
void IG.Forms.AlignmentControl.OnValueChanged (object sender, EventArgs eventArgs) inline protected
Triggers the ValueChanged event.
References IG.Forms.AlignmentControl.Alignment, and IG.Forms.AlignmentControl.ValueChanged.
AnyControl_CheckChanged() [3/3]
void IG.Forms.AlignmentControl.AnyControl_CheckChanged (object sender, EventArgs e) inline private
Common things for event handlers executing when any of the radio buttons changes checked status.
Parameters
sender
e
References IG.Forms.AlignmentControl.OnValueChanged().
rbHorizontalNone_CheckedChanged() [3/3]
void IG.Forms.AlignmentControl.rbHorizontalNone_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.AnyControl_CheckChanged().
rbHorizontalLeft_CheckedChanged() [3/3]
void IG.Forms.AlignmentControl.rbHorizontalLeft_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
rbHorizontalCentered_CheckedChanged() [3/3]
void IG.Forms.AlignmentControl.rbHorizontalCentered_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
rbHorizontalRight_CheckedChanged() [3/3]
void IG.Forms.AlignmentControl.rbHorizontalRight_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
rbVerticalNone_CheckedChanged() [3/3]
void IG.Forms.AlignmentControl.rbVerticalNone_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
rbVerticalTop_CheckedChanged() [3/3]
void IG.Forms.AlignmentControl.rbVerticalTop_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
rbVerticalCentered_CheckedChanged() [3/3]
void IG.Forms.AlignmentControl.rbVerticalCentered_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
rbVerticalBottom_CheckedChanged() [3/3]
void IG.Forms.AlignmentControl.rbVerticalBottom_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.AlignmentControl.OnValueChanged().
Dispose() [3/3]
override void IG.Forms.AlignmentControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.AlignmentControl.components.
InitializeComponent() [3/3]
void IG.Forms.AlignmentControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.AlignmentControl.lblHorizontal, IG.Forms.AlignmentControl.lblVertical, IG.Forms.AlignmentControl.pnlHorizontal, IG.Forms.AlignmentControl.pnlOuter, IG.Forms.AlignmentControl.pnlVertical, IG.Forms.AlignmentControl.rbHorizontalCentered, IG.Forms.AlignmentControl.rbHorizontalCentered_CheckedChanged(), IG.Forms.AlignmentControl.rbHorizontalLeft, IG.Forms.AlignmentControl.rbHorizontalLeft_CheckedChanged(), IG.Forms.AlignmentControl.rbHorizontalNone, IG.Forms.AlignmentControl.rbHorizontalNone_CheckedChanged(), IG.Forms.AlignmentControl.rbHorizontalRight, IG.Forms.AlignmentControl.rbHorizontalRight_CheckedChanged(), IG.Forms.AlignmentControl.rbVerticalBottom, IG.Forms.AlignmentControl.rbVerticalBottom_CheckedChanged(), IG.Forms.AlignmentControl.rbVerticalCentered_CheckedChanged(), IG.Forms.AlignmentControl.rbVerticalMiddle, IG.Forms.AlignmentControl.rbVerticalNone, IG.Forms.AlignmentControl.rbVerticalNone_CheckedChanged(), IG.Forms.AlignmentControl.rbVerticalTop, and IG.Forms.AlignmentControl.rbVerticalTop_CheckedChanged().
Member Data Documentation
_alignment
Alignment IG.Forms.AlignmentControl._alignment = new Alignment() protected
components
System ComponentModel IContainer IG.Forms.AlignmentControl.components = null private
Required designer variable.
Referenced by IG.Forms.AlignmentControl.Dispose().
lblHorizontal
System Windows Forms Label IG.Forms.AlignmentControl.lblHorizontal private
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
rbHorizontalRight
System Windows Forms RadioButton IG.Forms.AlignmentControl.rbHorizontalRight private
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
rbHorizontalCentered
System Windows Forms RadioButton IG.Forms.AlignmentControl.rbHorizontalCentered private
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
rbHorizontalLeft
System Windows Forms RadioButton IG.Forms.AlignmentControl.rbHorizontalLeft private
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
rbHorizontalNone
System Windows Forms RadioButton IG.Forms.AlignmentControl.rbHorizontalNone private
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
lblVertical
System Windows Forms Label IG.Forms.AlignmentControl.lblVertical private
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
rbVerticalBottom
System Windows Forms RadioButton IG.Forms.AlignmentControl.rbVerticalBottom private
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
rbVerticalMiddle
System Windows Forms RadioButton IG.Forms.AlignmentControl.rbVerticalMiddle private
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
rbVerticalTop
System Windows Forms RadioButton IG.Forms.AlignmentControl.rbVerticalTop private
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
rbVerticalNone
System Windows Forms RadioButton IG.Forms.AlignmentControl.rbVerticalNone private
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
pnlOuter
System Windows Forms GroupBox IG.Forms.AlignmentControl.pnlOuter private
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
pnlHorizontal
System Windows Forms Panel IG.Forms.AlignmentControl.pnlHorizontal private
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
pnlVertical
System Windows Forms Panel IG.Forms.AlignmentControl.pnlVertical private
Referenced by IG.Forms.AlignmentControl.InitializeComponent().
Property Documentation
Title
string IG.Forms.AlignmentControl.Title get set
Text displayed in the title label of the control.
Referenced by IG.Forms.AlignmentTestForm.InitializeComponent(), and IG.Forms.WindowPositionerControl.InitializeComponent().
Alignment
Alignment IG.Forms.AlignmentControl.Alignment get set
Referenced by IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.CopyDataToPositioner(), and IG.Forms.AlignmentControl.OnValueChanged().
Event Documentation
ValueChanged
EventHandler IG.Forms.AlignmentControl.ValueChanged
Event that occurs when the value of alignment changes.
Referenced by IG.Forms.AlignmentControl.OnValueChanged().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/WindowPositioner/AlignmentControl.cs
iglib/igforms/Utilities/WindowPositioner/AlignmentControl.Designer.cs