Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DSBTRD Class Reference
DotNumerics.LinearAlgebra.CSLapack.DSBTRD Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DSBTRD (DLAR2V dlar2v, DLARGV dlargv, DLARTG dlartg, DLARTV dlartv, DLASET dlaset, DROT drot, XERBLA xerbla, LSAME lsame)
DSBTRD ()
void Run (string VECT, string UPLO, int N, int KD, ref double[] AB, int offset_ab, int LDAB, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] Q, int offset_q, int LDQ, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
DLAR2V _dlar2v
DLARGV _dlargv
DLARTG _dlartg
DLARTV _dlartv
DLASET _dlaset
DROT _drot
XERBLA _xerbla
LSAME _lsame
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DSBTRD reduces a real symmetric band matrix A to symmetric tridiagonal form T by an orthogonal similarity transformation: Q**T * A * Q = T.
/summary>
Constructor & Destructor Documentation
DSBTRD() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DSBTRD.DSBTRD (DLAR2V dlar2v, DLARGV dlargv, DLARTG dlartg, DLARTV dlartv, DLASET dlaset, DROT drot, XERBLA xerbla, LSAME lsame) inline
DSBTRD() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DSBTRD.DSBTRD () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DSBTRD.Run (string VECT, string UPLO, int N, int KD, ref double[] AB, int offset_ab, int LDAB, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] Q, int offset_q, int LDQ, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
DSBTRD reduces a real symmetric band matrix A to symmetric tridiagonal form T by an orthogonal similarity transformation: Q**T * A * Q = T.
/summary>
Parameters
VECT (input) CHARACTER*1 = 'N': do not form Q; = 'V': form Q; = 'U': update a matrix X, by forming X*Q. /param>
Parameters
UPLO (input) CHARACTER*1 = 'U': Upper triangle of A is stored; = 'L': Lower triangle of A is stored. /param>
Parameters
N (input) INTEGER The order of the matrix A. N .GE. 0. /param>
Parameters
KD (input) INTEGER The number of superdiagonals of the matrix A if UPLO = 'U', or the number of subdiagonals if UPLO = 'L'. KD .GE. 0. /param>
Parameters
AB (input/output) DOUBLE PRECISION array, dimension (LDAB,N) On entry, the upper or lower triangle of the symmetric band matrix A, stored in the first KD+1 rows of the array. The j-th column of A is stored in the j-th column of the array AB as follows: if UPLO = 'U', AB(kd+1+i-j,j) = A(i,j) for max(1,j-kd).LE.i.LE.j; if UPLO = 'L', AB(1+i-j,j) = A(i,j) for j.LE.i.LE.min(n,j+kd). On exit, the diagonal elements of AB are overwritten by the diagonal elements of the tridiagonal matrix T; if KD .GT. 0, the elements on the first superdiagonal (if UPLO = 'U') or the first subdiagonal (if UPLO = 'L') are overwritten by the off-diagonal elements of T; the rest of AB is overwritten by values generated during the reduction. /param>
Parameters
LDAB (input) INTEGER The leading dimension of the array AB. LDAB .GE. KD+1. /param>
Parameters
D (output) DOUBLE PRECISION array, dimension (N) The diagonal elements of the tridiagonal matrix T. /param>
Parameters
E (output) DOUBLE PRECISION array, dimension (N-1) The off-diagonal elements of the tridiagonal matrix T: E(i) = T(i,i+1) if UPLO = 'U'; E(i) = T(i+1,i) if UPLO = 'L'. /param>
Parameters
Q (input/output) DOUBLE PRECISION array, dimension (LDQ,N) On entry, if VECT = 'U', then Q must contain an N-by-N matrix X; if VECT = 'N' or 'V', then Q need not be set.
On exit: if VECT = 'V', Q contains the N-by-N orthogonal matrix Q; if VECT = 'U', Q contains the product X*Q; if VECT = 'N', the array Q is not referenced. /param>
Parameters
LDQ (input) INTEGER The leading dimension of the array Q. LDQ .GE. 1, and LDQ .GE. N if VECT = 'V' or 'U'. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (N) /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.DSBTRD.ONE, DotNumerics.LinearAlgebra.CSLapack.DROT.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARTV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAR2V.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARGV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASET.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARTG.Run(), and DotNumerics.LinearAlgebra.CSLapack.DSBTRD.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSBEV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DSBEVD.Run().
Member Data Documentation
_dlar2v
DLAR2V DotNumerics.LinearAlgebra.CSLapack.DSBTRD._dlar2v private
_dlargv
DLARGV DotNumerics.LinearAlgebra.CSLapack.DSBTRD._dlargv private
_dlartg
DLARTG DotNumerics.LinearAlgebra.CSLapack.DSBTRD._dlartg private
_dlartv
DLARTV DotNumerics.LinearAlgebra.CSLapack.DSBTRD._dlartv private
_dlaset
DLASET DotNumerics.LinearAlgebra.CSLapack.DSBTRD._dlaset private
_drot
DROT DotNumerics.LinearAlgebra.CSLapack.DSBTRD._drot private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DSBTRD._xerbla private
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DSBTRD._lsame private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DSBTRD.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSBTRD.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DSBTRD.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSBTRD.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dsbtrd.cs