Doc: IGLib EXTENDED: alglib.nearunityunit Class Reference
alglib.nearunityunit Class Reference
Static Public Member Functions
static double nulog1p (double x)
static double nuexpm1 (double x)
static double nucosm1 (double x)
static double nulog1p (double x)
static double nuexpm1 (double x)
static double nucosm1 (double x)
Member Function Documentation
nulog1p() [1/2]
static double alglib.nearunityunit.nulog1p (double x) inline static
Referenced by alglib.binomialdistr.binomialcdistribution(), and alglib.binomialdistr.invbinomialdistribution().
nuexpm1() [1/2]
static double alglib.nearunityunit.nuexpm1 (double x) inline static
Referenced by alglib.binomialdistr.binomialcdistribution(), and alglib.binomialdistr.invbinomialdistribution().
nucosm1() [1/2]
static double alglib.nearunityunit.nucosm1 (double x) inline static
nulog1p() [2/2]
static double alglib.nearunityunit.nulog1p (double x) inline static
nuexpm1() [2/2]
static double alglib.nearunityunit.nuexpm1 (double x) inline static
nucosm1() [2/2]
static double alglib.nearunityunit.nucosm1 (double x) inline static
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/alglibinternal.cs