Doc: IGLib EXTENDED: IG.Neural.Applications.NeuralPredictionWindow Class Reference
IG.Neural.Applications.NeuralPredictionWindow Class Reference
Window for making predictions of output values based on ANN model.
Public Member Functions
NeuralPredictionWindow (INeuralModel model)
Construct a new window for ANN based predictions, with the model specified.
NeuralPredictionWindow (string neuralDirectoryPath)
NeuralPredictionWindow ()
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
void SetNeuralScriptShellPath (string path)
Sets the directory for
NeuralPredictionWindow (INeuralModel model)
Construct a new window for ANN based predictions, with the model specified.
NeuralPredictionWindow (string neuralDirectoryPath)
NeuralPredictionWindow ()
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
void SetNeuralScriptShellPath (string path)
Sets the directory for
NeuralPredictionWindow (INeuralModel model)
Construct a new window for ANN based predictions, with the model specified.
NeuralPredictionWindow (string neuralDirectoryPath)
NeuralPredictionWindow ()
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
void SetNeuralScriptShellPath (string path)
Sets the directory for
NeuralPredictionWindow (INeuralModel model)
Construct a new window for ANN based predictions, with the model specified.
NeuralPredictionWindow (string neuralDirectoryPath)
NeuralPredictionWindow ()
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
void SetNeuralScriptShellPath (string path)
Sets the directory for
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
string _neuralScriptShellPath = null
Properties
INeuralModel NeuralModel [get, protected set]
Neural network - based model.
string NeuralScriptShellPath [get, protected set]
Path of the working directory for the ANN-based approximation approximation scripts.
INeuralApproximator TrainedNetwork [get]
Traint artificial neural network.
InputOutputDataDefiniton NeuralDataDefinition [get]
Neural data definition.
Properties inherited from IG.Neural.INeuralModelContainer
INeuralModel NeuralModel [get]
Artificial neural network - based model.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
INeuralModel _neuralModel
System.ComponentModel.IContainer components = null
Required designer variable.
NeuralPredictionControl neuralPredictionControl1
Detailed Description
Window for making predictions of output values based on ANN model.
$A Igor Apr13;
Constructor & Destructor Documentation
NeuralPredictionWindow() [1/12]
IG.Neural.Applications.NeuralPredictionWindow.NeuralPredictionWindow (INeuralModel model) inline
Construct a new window for ANN based predictions, with the model specified.
Parameters
model ANN - base model, contains input and output data definitions and
References IG.Neural.Applications.NeuralPredictionWindow.NeuralModel.
NeuralPredictionWindow() [2/12]
IG.Neural.Applications.NeuralPredictionWindow.NeuralPredictionWindow (string neuralDirectoryPath) inline
References IG.Neural.Applications.NeuralPredictionWindow.NeuralScriptShellPath.
NeuralPredictionWindow() [3/12]
IG.Neural.Applications.NeuralPredictionWindow.NeuralPredictionWindow () inline
References IG.Neural.Applications.NeuralPredictionWindow.InitializeComponent().
NeuralPredictionWindow() [4/12]
IG.Neural.Applications.NeuralPredictionWindow.NeuralPredictionWindow (INeuralModel model) inline
Construct a new window for ANN based predictions, with the model specified.
Parameters
model ANN - base model, contains input and output data definitions and
References IG.Neural.Applications.NeuralPredictionWindow.NeuralModel.
NeuralPredictionWindow() [5/12]
IG.Neural.Applications.NeuralPredictionWindow.NeuralPredictionWindow (string neuralDirectoryPath) inline
References IG.Neural.Applications.NeuralPredictionWindow.NeuralScriptShellPath.
NeuralPredictionWindow() [6/12]
IG.Neural.Applications.NeuralPredictionWindow.NeuralPredictionWindow () inline
References IG.Neural.Applications.NeuralPredictionWindow.InitializeComponent().
NeuralPredictionWindow() [7/12]
IG.Neural.Applications.NeuralPredictionWindow.NeuralPredictionWindow (INeuralModel model) inline
Construct a new window for ANN based predictions, with the model specified.
Parameters
model ANN - base model, contains input and output data definitions and
References IG.Neural.Applications.NeuralPredictionWindow.NeuralModel.
NeuralPredictionWindow() [8/12]
IG.Neural.Applications.NeuralPredictionWindow.NeuralPredictionWindow (string neuralDirectoryPath) inline
References IG.Neural.Applications.NeuralPredictionWindow.NeuralScriptShellPath.
NeuralPredictionWindow() [9/12]
IG.Neural.Applications.NeuralPredictionWindow.NeuralPredictionWindow () inline
References IG.Neural.Applications.NeuralPredictionWindow.InitializeComponent().
NeuralPredictionWindow() [10/12]
IG.Neural.Applications.NeuralPredictionWindow.NeuralPredictionWindow (INeuralModel model) inline
Construct a new window for ANN based predictions, with the model specified.
Parameters
model ANN - base model, contains input and output data definitions and
References IG.Neural.Applications.NeuralPredictionWindow.NeuralModel.
NeuralPredictionWindow() [11/12]
IG.Neural.Applications.NeuralPredictionWindow.NeuralPredictionWindow (string neuralDirectoryPath) inline
References IG.Neural.Applications.NeuralPredictionWindow.NeuralScriptShellPath.
NeuralPredictionWindow() [12/12]
IG.Neural.Applications.NeuralPredictionWindow.NeuralPredictionWindow () inline
References IG.Neural.Applications.NeuralPredictionWindow.InitializeComponent().
Member Function Documentation
SetNeuralModel() [1/4]
void IG.Neural.Applications.NeuralPredictionWindow.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
Implements IG.Neural.INeuralModelContainer.
References IG.Neural.Applications.NeuralPredictionWindow.NeuralModel.
SetNeuralScriptShellPath() [1/4]
void IG.Neural.Applications.NeuralPredictionWindow.SetNeuralScriptShellPath (string path) inline
Sets the directory for
Parameters
path
References IG.Neural.Applications.NeuralPredictionWindow.NeuralScriptShellPath.
Dispose() [1/4]
override void IG.Neural.Applications.NeuralPredictionWindow.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralPredictionWindow.components.
InitializeComponent() [1/4]
void IG.Neural.Applications.NeuralPredictionWindow.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralPredictionWindow.neuralPredictionControl1.
Referenced by IG.Neural.Applications.NeuralPredictionWindow.NeuralPredictionWindow().
SetNeuralModel() [2/4]
void IG.Neural.Applications.NeuralPredictionWindow.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
Implements IG.Neural.INeuralModelContainer.
References IG.Neural.Applications.NeuralPredictionWindow.NeuralModel.
SetNeuralScriptShellPath() [2/4]
void IG.Neural.Applications.NeuralPredictionWindow.SetNeuralScriptShellPath (string path) inline
Sets the directory for
Parameters
path
References IG.Neural.Applications.NeuralPredictionWindow.NeuralScriptShellPath.
Dispose() [2/4]
override void IG.Neural.Applications.NeuralPredictionWindow.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralPredictionWindow.components.
InitializeComponent() [2/4]
void IG.Neural.Applications.NeuralPredictionWindow.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralPredictionWindow.neuralPredictionControl1.
SetNeuralModel() [3/4]
void IG.Neural.Applications.NeuralPredictionWindow.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
Implements IG.Neural.INeuralModelContainer.
References IG.Neural.Applications.NeuralPredictionWindow.NeuralModel.
SetNeuralScriptShellPath() [3/4]
void IG.Neural.Applications.NeuralPredictionWindow.SetNeuralScriptShellPath (string path) inline
Sets the directory for
Parameters
path
References IG.Neural.Applications.NeuralPredictionWindow.NeuralScriptShellPath.
Dispose() [3/4]
override void IG.Neural.Applications.NeuralPredictionWindow.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralPredictionWindow.components.
InitializeComponent() [3/4]
void IG.Neural.Applications.NeuralPredictionWindow.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralPredictionWindow.neuralPredictionControl1.
SetNeuralModel() [4/4]
void IG.Neural.Applications.NeuralPredictionWindow.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
Implements IG.Neural.INeuralModelContainer.
References IG.Neural.Applications.NeuralPredictionWindow.NeuralModel.
SetNeuralScriptShellPath() [4/4]
void IG.Neural.Applications.NeuralPredictionWindow.SetNeuralScriptShellPath (string path) inline
Sets the directory for
Parameters
path
References IG.Neural.Applications.NeuralPredictionWindow.NeuralScriptShellPath.
Dispose() [4/4]
override void IG.Neural.Applications.NeuralPredictionWindow.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralPredictionWindow.components.
InitializeComponent() [4/4]
void IG.Neural.Applications.NeuralPredictionWindow.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralPredictionWindow.neuralPredictionControl1.
Member Data Documentation
_neuralModel
INeuralModel IG.Neural.Applications.NeuralPredictionWindow._neuralModel private
_neuralScriptShellPath
string IG.Neural.Applications.NeuralPredictionWindow._neuralScriptShellPath = null protected
components
System ComponentModel IContainer IG.Neural.Applications.NeuralPredictionWindow.components = null private
Required designer variable.
Referenced by IG.Neural.Applications.NeuralPredictionWindow.Dispose().
neuralPredictionControl1
NeuralPredictionControl IG.Neural.Applications.NeuralPredictionWindow.neuralPredictionControl1 private
Referenced by IG.Neural.Applications.NeuralPredictionWindow.InitializeComponent().
Property Documentation
NeuralModel
INeuralModel IG.Neural.Applications.NeuralPredictionWindow.NeuralModel get protected set
Neural network - based model.
Contains data definition and trained neural network approximator.
Referenced by IG.Neural.Applications.NeuralPredictionWindow.NeuralPredictionWindow(), and IG.Neural.Applications.NeuralPredictionWindow.SetNeuralModel().
NeuralScriptShellPath
string IG.Neural.Applications.NeuralPredictionWindow.NeuralScriptShellPath get protected set
Path of the working directory for the ANN-based approximation approximation scripts.
Referenced by IG.Neural.Applications.NeuralPredictionWindow.NeuralPredictionWindow(), and IG.Neural.Applications.NeuralPredictionWindow.SetNeuralScriptShellPath().
TrainedNetwork
INeuralApproximator IG.Neural.Applications.NeuralPredictionWindow.TrainedNetwork get
Traint artificial neural network.
NeuralDataDefinition
InputOutputDataDefiniton IG.Neural.Applications.NeuralPredictionWindow.NeuralDataDefinition get
Neural data definition.
The documentation for this class was generated from the following files:
shelldev/extensions/ExtAppAnnApp/ResponseForms/NeuralPredictionWindow.cs
shelldev/extensions/ExtAppAnnApp/ResponseForms/NeuralPredictionWindow.Designer.cs