Doc: IGLib EXTENDED: AForge.Imaging.Formats.PNMImageInfo Class Reference
AForge.Imaging.Formats.PNMImageInfo Class Reference
Information about PNM image's frame.
Public Member Functions
PNMImageInfo ()
Initializes a new instance of the PNMImageInfo class.
PNMImageInfo (int width, int height, int bitsPerPixel, int frameIndex, int totalFrames)
Initializes a new instance of the PNMImageInfo class.
override object Clone ()
Creates a new object that is a copy of the current instance.
Public Member Functions inherited from AForge.Imaging.Formats.ImageInfo
ImageInfo ()
Initializes a new instance of the ImageInfo class.
ImageInfo (int width, int height, int bitsPerPixel, int frameIndex, int totalFrames)
Initializes a new instance of the ImageInfo class.
Properties
int Version [get, set]
PNM file version (format), [1, 6].
int MaxDataValue [get, set]
Maximum pixel's value in source PNM image.
Properties inherited from AForge.Imaging.Formats.ImageInfo
int Width [get, set]
Image's width.
int Height [get, set]
Image's height.
int BitsPerPixel [get, set]
Number of bits per image's pixel.
int FrameIndex [get, set]
Frame's index.
int TotalFrames [get, set]
Total frames in the image.
Private Attributes
int version
int maxDataValue
Additional Inherited Members
Protected Attributes inherited from AForge.Imaging.Formats.ImageInfo
int width
Image's width.
int height
Image's height.
int bitsPerPixel
Number of bits per image's pixel.
int frameIndex
Frame's index.
int totalFrames
Total frames in the image.
Detailed Description
Information about PNM image's frame.
Constructor & Destructor Documentation
PNMImageInfo() [1/2]
AForge.Imaging.Formats.PNMImageInfo.PNMImageInfo () inline
Initializes a new instance of the PNMImageInfo class.
Referenced by AForge.Imaging.Formats.PNMImageInfo.Clone().
PNMImageInfo() [2/2]
AForge.Imaging.Formats.PNMImageInfo.PNMImageInfo (int width, int height, int bitsPerPixel, int frameIndex, int totalFrames) inline
Initializes a new instance of the PNMImageInfo class.
Parameters
width Image's width.
height Image's height.
bitsPerPixel Number of bits per image's pixel.
frameIndex Frame's index.
totalFrames Total frames in the image.
Member Function Documentation
Clone()
override object AForge.Imaging.Formats.PNMImageInfo.Clone () inline virtual
Creates a new object that is a copy of the current instance.
Returns
A new object that is a copy of this instance.
Reimplemented from AForge.Imaging.Formats.ImageInfo.
References AForge.Imaging.Formats.ImageInfo.bitsPerPixel, AForge.Imaging.Formats.ImageInfo.frameIndex, AForge.Imaging.Formats.ImageInfo.height, AForge.Imaging.Formats.PNMImageInfo.maxDataValue, AForge.Imaging.Formats.PNMImageInfo.PNMImageInfo(), AForge.Imaging.Formats.ImageInfo.totalFrames, AForge.Imaging.Formats.PNMImageInfo.version, and AForge.Imaging.Formats.ImageInfo.width.
Referenced by AForge.Imaging.Formats.PNMCodec.DecodeFrame().
Member Data Documentation
version
int AForge.Imaging.Formats.PNMImageInfo.version private
Referenced by AForge.Imaging.Formats.PNMImageInfo.Clone().
maxDataValue
int AForge.Imaging.Formats.PNMImageInfo.maxDataValue private
Referenced by AForge.Imaging.Formats.PNMImageInfo.Clone().
Property Documentation
Version
int AForge.Imaging.Formats.PNMImageInfo.Version get set
PNM file version (format), [1, 6].
Referenced by AForge.Imaging.Formats.PNMCodec.ReadHeader(), and AForge.Imaging.Formats.PNMCodec.ReadImageFrame().
MaxDataValue
int AForge.Imaging.Formats.PNMImageInfo.MaxDataValue get set
Maximum pixel's value in source PNM image.
The value is used to scale image's data converting them from original data range to the range of supported bits per pixel format.
Referenced by AForge.Imaging.Formats.PNMCodec.ReadHeader(), and AForge.Imaging.Formats.PNMCodec.ReadImageFrame().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging.Formats/PNMCodec.cs