Doc: IGLib EXTENDED: NeuronDotNet.Core.Initializers.ConstantFunction Class Reference
NeuronDotNet.Core.Initializers.ConstantFunction Class Reference
An IInitializer using constant function
Public Member Functions
ConstantFunction (double constant)
Creates a new constant function
ConstantFunction (SerializationInfo info, StreamingContext context)
Deserialization Constructor
virtual void GetObjectData (SerializationInfo info, StreamingContext context)
Populates the serialization info with the data needed to serialize the initializer
void Initialize (ActivationLayer activationLayer)
Initializes bias values of activation neurons in the activation layer.
void Initialize (BackpropagationConnector connector)
Initializes weights of all backpropagation synapses in the backpropagation connector.
void Initialize (KohonenConnector connector)
Initializes weights of all spatial synapses in a Kohonen connector.
Properties
double Constant [get]
Gets the initializer Constant
Private Attributes
readonly double constant
Detailed Description
An IInitializer using constant function
Constructor & Destructor Documentation
ConstantFunction() [1/2]
NeuronDotNet.Core.Initializers.ConstantFunction.ConstantFunction (double constant) inline
Creates a new constant function
Parameters
constant The constant to use
References NeuronDotNet.Core.Initializers.ConstantFunction.constant.
ConstantFunction() [2/2]
NeuronDotNet.Core.Initializers.ConstantFunction.ConstantFunction (SerializationInfo info, StreamingContext context) inline
Deserialization Constructor
Parameters
info Serialization information to deserialize and obtain the data
context Serialization context to use
Exceptions
ArgumentNullException If info is null
References NeuronDotNet.Core.Initializers.ConstantFunction.constant, and NeuronDotNet.Core.Helper.ValidateNotNull().
Member Function Documentation
GetObjectData()
virtual void NeuronDotNet.Core.Initializers.ConstantFunction.GetObjectData (SerializationInfo info, StreamingContext context) inline virtual
Populates the serialization info with the data needed to serialize the initializer
Parameters
info The serialization info to populate the data with
context The serialization context to use
Exceptions
ArgumentNullException If info is null
References NeuronDotNet.Core.Initializers.ConstantFunction.constant, and NeuronDotNet.Core.Helper.ValidateNotNull().
Initialize() [1/3]
void NeuronDotNet.Core.Initializers.ConstantFunction.Initialize (ActivationLayer activationLayer) inline
Initializes bias values of activation neurons in the activation layer.
Parameters
activationLayer The activation layer to initialize
Exceptions
ArgumentNullException If activationLayer is null
Implements NeuronDotNet.Core.IInitializer.
References NeuronDotNet.Core.Initializers.ConstantFunction.constant, and NeuronDotNet.Core.Helper.ValidateNotNull().
Initialize() [2/3]
void NeuronDotNet.Core.Initializers.ConstantFunction.Initialize (BackpropagationConnector connector) inline
Initializes weights of all backpropagation synapses in the backpropagation connector.
Parameters
connector The backpropagation connector to initialize.
Exceptions
ArgumentNullException If connector is null
Implements NeuronDotNet.Core.IInitializer.
References NeuronDotNet.Core.Initializers.ConstantFunction.constant, NeuronDotNet.Core.Helper.ValidateNotNull(), and NeuronDotNet.Core.Backpropagation.BackpropagationSynapse.Weight.
Initialize() [3/3]
void NeuronDotNet.Core.Initializers.ConstantFunction.Initialize (KohonenConnector connector) inline
Initializes weights of all spatial synapses in a Kohonen connector.
Parameters
connector The Kohonen connector to initialize.
Exceptions
ArgumentNullException If connector is null
Implements NeuronDotNet.Core.IInitializer.
References NeuronDotNet.Core.Initializers.ConstantFunction.constant, NeuronDotNet.Core.Helper.ValidateNotNull(), and NeuronDotNet.Core.SOM.KohonenSynapse.Weight.
Member Data Documentation
constant
readonly double NeuronDotNet.Core.Initializers.ConstantFunction.constant private
Referenced by NeuronDotNet.Core.Initializers.ConstantFunction.ConstantFunction(), NeuronDotNet.Core.Initializers.ConstantFunction.GetObjectData(), and NeuronDotNet.Core.Initializers.ConstantFunction.Initialize().
Property Documentation
Constant
double NeuronDotNet.Core.Initializers.ConstantFunction.Constant get
Gets the initializer Constant
The constant with which each parameter (bias values and weights) is initialized
The documentation for this class was generated from the following file:
shelldev/lib/externalextended/NeuronDotNetGPL/source/Core/Initializers/ConstantFunction.cs