Doc: IGLib EXTENDED: NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown Class Reference
NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown Class Reference
Public Member Functions
void FailingTest ()
void PassingTest ()
void AnotherPassingTest ()
void IgnoredTest ()
void IgnoredTestTwo ()
void IgnoredTestThree ()
void AssumeSomething ()
void AssumeSomethingElse ()
void NeverAssume ()
void AssumeTheWorldIsFlat ()
void OneTimeTearDown ()
Properties
int PassCount [get, private set]
int FailCount [get, private set]
int SkipCount [get, private set]
int InconclusiveCount [get, private set]
string Message [get, private set]
string StackTrace [get, private set]
Member Function Documentation
FailingTest()
void NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.FailingTest () inline
References NUnit.Framework.Assert.Fail().
PassingTest()
void NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.PassingTest () inline
References NUnit.Framework.Assert.Pass().
AnotherPassingTest()
void NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.AnotherPassingTest () inline
References NUnit.Framework.Assert.Pass().
IgnoredTest()
void NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.IgnoredTest () inline
References NUnit.Framework.Assert.Ignore().
IgnoredTestTwo()
void NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.IgnoredTestTwo () inline
References NUnit.Framework.Assert.Ignore().
IgnoredTestThree()
void NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.IgnoredTestThree () inline
References NUnit.Framework.Assert.Ignore().
AssumeSomething()
void NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.AssumeSomething () inline
References NUnit.Framework.Assume.That().
AssumeSomethingElse()
void NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.AssumeSomethingElse () inline
References NUnit.Framework.Assume.That().
NeverAssume()
void NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.NeverAssume () inline
References NUnit.Framework.Assume.That().
AssumeTheWorldIsFlat()
void NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.AssumeTheWorldIsFlat () inline
References NUnit.Framework.Assume.That().
OneTimeTearDown()
void NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.OneTimeTearDown () inline
References NUnit.Framework.TestContext.CurrentContext, NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.FailCount, NUnit.Framework.TestContext.ResultAdapter.FailCount, NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.InconclusiveCount, NUnit.Framework.TestContext.ResultAdapter.InconclusiveCount, NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.Message, NUnit.Framework.TestContext.ResultAdapter.Message, NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.PassCount, NUnit.Framework.TestContext.ResultAdapter.PassCount, NUnit.Framework.TestContext.Result, NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.SkipCount, and NUnit.Framework.TestContext.ResultAdapter.SkipCount.
Property Documentation
PassCount
int NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.PassCount get private set
Referenced by NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.OneTimeTearDown().
FailCount
int NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.FailCount get private set
Referenced by NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.OneTimeTearDown().
SkipCount
int NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.SkipCount get private set
Referenced by NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.OneTimeTearDown().
InconclusiveCount
int NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.InconclusiveCount get private set
Referenced by NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.OneTimeTearDown().
Message
string NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.Message get private set
Referenced by NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.OneTimeTearDown().
StackTrace
string NUnit.TestData.TestContextData.TestTestContextInOneTimeTearDown.StackTrace get private set
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/testdata/TestContextData.cs