Doc: IGLib EXTENDED: AForge.Genetic.OptimizationFunction2D Class Reference
AForge.Genetic.OptimizationFunction2D Class Reference abstract
Base class for two dimenstional function optimization.
Public Types
enum Modes { Modes.Maximization, Modes.Minimization }
Optimization modes.
Public Member Functions
OptimizationFunction2D (Range rangeX, Range rangeY)
Initializes a new instance of the OptimizationFunction2D class.
double Evaluate (IChromosome chromosome)
Evaluates chromosome.
double[] Translate (IChromosome chromosome)
Translates genotype to phenotype
abstract double OptimizationFunction (double x, double y)
Function to optimize.
Properties
Range RangeX [get, set]
X variable's optimization range.
Range RangeY [get, set]
Y variable's optimization range.
Modes Mode [get, set]
Optimization mode.
Private Attributes
Range rangeX = new Range(0, 1)
Range rangeY = new Range(0, 1)
Modes mode = Modes.Maximization
Detailed Description
Base class for two dimenstional function optimization.
The class is aimed to be used for two dimensional function optimization problems. It implements all methods of IFitnessFunction interface and requires overriding only one method - OptimizationFunction, which represents the function to optimize.
<note>The optimization function should be greater than 0 on the specified optimization range.</note>
The class works only with binary chromosomes (BinaryChromosome).
Sample usage:
// define optimization function
public class UserFunction : OptimizationFunction2D
{
    public UserFunction( ) :
        base( new Range( -4, 4 ), new Range( -4, 4 ) ) { }
    public override double OptimizationFunction( double x, double y )
    {
        return ( Math.Cos( y ) * x * y ) / ( 2 - Math.Sin( x ) );
    }
}
...
// create genetic population
Population population = new Population(40,
    new BinaryChromosome( 32 ),
    new UserFunction( ),
    new EliteSelection( ) );
// run one epoch of the population
population.RunEpoch();
Member Enumeration Documentation
Modes
enum AForge.Genetic.OptimizationFunction2D.Modes strong
Optimization modes.
The enumeration defines optimization modes for the two dimensional function optimization.
Enumerator
Maximization
Search for function's maximum value.
Minimization
Search for function's minimum value.
Constructor & Destructor Documentation
OptimizationFunction2D()
AForge.Genetic.OptimizationFunction2D.OptimizationFunction2D (Range rangeX, Range rangeY) inline
Initializes a new instance of the OptimizationFunction2D class.
Parameters
rangeX Specifies X variable's range.
rangeY Specifies Y variable's range.
References AForge.Genetic.OptimizationFunction2D.rangeX, and AForge.Genetic.OptimizationFunction2D.rangeY.
Member Function Documentation
Evaluate()
double AForge.Genetic.OptimizationFunction2D.Evaluate (IChromosome chromosome) inline
Evaluates chromosome.
Parameters
chromosome Chromosome to evaluate.
Returns
Returns chromosome's fitness value.
The method calculates fitness value of the specified chromosome.
Implements AForge.Genetic.IFitnessFunction.
References AForge.Genetic.OptimizationFunction2D.mode, AForge.Genetic.OptimizationFunction2D.OptimizationFunction(), and AForge.Genetic.OptimizationFunction2D.Translate().
Translate()
double [] AForge.Genetic.OptimizationFunction2D.Translate (IChromosome chromosome) inline
Translates genotype to phenotype
Parameters
chromosome Chromosome, which genoteype should be translated to phenotype
Returns
Returns chromosome's fenotype - the actual solution encoded by the chromosome
The method returns array of two double values, which represent function's input point (X and Y) encoded by the specified chromosome.
References AForge.Range.Length, AForge.Range.Min, AForge.Genetic.OptimizationFunction2D.rangeX, and AForge.Genetic.OptimizationFunction2D.rangeY.
Referenced by AForge.Genetic.OptimizationFunction2D.Evaluate().
OptimizationFunction()
abstract double AForge.Genetic.OptimizationFunction2D.OptimizationFunction (double x, double y) pure virtual
Function to optimize.
Parameters
x Function X input value.
y Function Y input value.
Returns
Returns function output value.
The method should be overloaded by inherited class to specify the optimization function.
Referenced by AForge.Genetic.OptimizationFunction2D.Evaluate().
Member Data Documentation
rangeX
Range AForge.Genetic.OptimizationFunction2D.rangeX = new Range(0, 1) private
Referenced by AForge.Genetic.OptimizationFunction2D.OptimizationFunction2D(), and AForge.Genetic.OptimizationFunction2D.Translate().
rangeY
Range AForge.Genetic.OptimizationFunction2D.rangeY = new Range(0, 1) private
Referenced by AForge.Genetic.OptimizationFunction2D.OptimizationFunction2D(), and AForge.Genetic.OptimizationFunction2D.Translate().
mode
Modes AForge.Genetic.OptimizationFunction2D.mode = Modes.Maximization private
Referenced by AForge.Genetic.OptimizationFunction2D.Evaluate().
Property Documentation
RangeX
Range AForge.Genetic.OptimizationFunction2D.RangeX get set
X variable's optimization range.
Defines function's X range. The function's extreme will be searched in this range only.
RangeY
Range AForge.Genetic.OptimizationFunction2D.RangeY get set
Y variable's optimization range.
Defines function's Y range. The function's extreme will be searched in this range only.
Mode
Modes AForge.Genetic.OptimizationFunction2D.Mode get set
Optimization mode.
Defines optimization mode - what kind of extreme to search.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Genetic/Fitness Functions/OptimizationFunction2D.cs