Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAQPS Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAQPS Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAQPS (DGEMM dgemm, DGEMV dgemv, DLARFG dlarfg, DSWAP dswap, IDAMAX idamax, DLAMCH dlamch, DNRM2 dnrm2)
DLAQPS ()
void Run (int M, int N, int OFFSET, int NB, ref int KB, ref double[] A, int offset_a, int LDA, ref int[] JPVT, int offset_jpvt, ref double[] TAU, int offset_tau, ref double[] VN1, int offset_vn1, ref double[] VN2, int offset_vn2, ref double[] AUXV, int offset_auxv, ref double[] F, int offset_f, int LDF)
Private Attributes
DGEMM _dgemm
DGEMV _dgemv
DLARFG _dlarfg
DSWAP _dswap
IDAMAX _idamax
DLAMCH _dlamch
DNRM2 _dnrm2
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAQPS computes a step of QR factorization with column pivoting of a real M-by-N matrix A by using Blas-3. It tries to factorize NB columns from A starting from the row OFFSET+1, and updates all of the matrix with Blas-3 xGEMM.
In some cases, due to catastrophic cancellations, it cannot factorize NB columns. Hence, the actual number of factorized columns is returned in KB.
Block A(1:OFFSET,1:N) is accordingly pivoted, but not factorized.
/summary>
Constructor & Destructor Documentation
DLAQPS() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAQPS.DLAQPS (DGEMM dgemm, DGEMV dgemv, DLARFG dlarfg, DSWAP dswap, IDAMAX idamax, DLAMCH dlamch, DNRM2 dnrm2) inline
DLAQPS() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAQPS.DLAQPS () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAQPS.Run (int M, int N, int OFFSET, int NB, ref int KB, ref double[] A, int offset_a, int LDA, ref int[] JPVT, int offset_jpvt, ref double[] TAU, int offset_tau, ref double[] VN1, int offset_vn1, ref double[] VN2, int offset_vn2, ref double[] AUXV, int offset_auxv, ref double[] F, int offset_f, int LDF) inline
Purpose
DLAQPS computes a step of QR factorization with column pivoting of a real M-by-N matrix A by using Blas-3. It tries to factorize NB columns from A starting from the row OFFSET+1, and updates all of the matrix with Blas-3 xGEMM.
In some cases, due to catastrophic cancellations, it cannot factorize NB columns. Hence, the actual number of factorized columns is returned in KB.
Block A(1:OFFSET,1:N) is accordingly pivoted, but not factorized.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. 0 /param>
Parameters
OFFSET (input) INTEGER The number of rows of A that have been factorized in previous steps. /param>
Parameters
NB (input) INTEGER The number of columns to factorize. /param>
Parameters
KB (output) INTEGER The number of columns actually factorized. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the M-by-N matrix A. On exit, block A(OFFSET+1:M,1:KB) is the triangular factor obtained and block A(1:OFFSET,1:N) has been accordingly pivoted, but no factorized. The rest of the matrix, block A(OFFSET+1:M,KB+1:N) has been updated. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
JPVT (input/output) INTEGER array, dimension (N) JPVT(I) = K .LE.=.GT. Column K of the full matrix A has been permuted into position I in AP. /param>
Parameters
TAU (output) DOUBLE PRECISION array, dimension (KB) The scalar factors of the elementary reflectors. /param>
Parameters
VN1 (input/output) DOUBLE PRECISION array, dimension (N) The vector with the partial column norms. /param>
Parameters
VN2 (input/output) DOUBLE PRECISION array, dimension (N) The vector with the exact column norms. /param>
Parameters
AUXV (input/output) DOUBLE PRECISION array, dimension (NB) Auxiliar vector. /param>
Parameters
F (input/output) DOUBLE PRECISION array, dimension (LDF,NB) Matrix F' = L*Y'*A. /param>
Parameters
LDF (input) INTEGER The leading dimension of the array F. LDF .GE. max(1,N). /param>
References DotNumerics.LinearAlgebra.CSLapack.DLAQPS.ONE, DotNumerics.LinearAlgebra.CSLapack.DNRM2.Run(), DotNumerics.LinearAlgebra.CSLapack.IDAMAX.Run(), DotNumerics.LinearAlgebra.CSLapack.DSWAP.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAQPS.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEQP3.Run().
Member Data Documentation
_dgemm
DGEMM DotNumerics.LinearAlgebra.CSLapack.DLAQPS._dgemm private
_dgemv
DGEMV DotNumerics.LinearAlgebra.CSLapack.DLAQPS._dgemv private
_dlarfg
DLARFG DotNumerics.LinearAlgebra.CSLapack.DLAQPS._dlarfg private
_dswap
DSWAP DotNumerics.LinearAlgebra.CSLapack.DLAQPS._dswap private
_idamax
IDAMAX DotNumerics.LinearAlgebra.CSLapack.DLAQPS._idamax private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLAQPS._dlamch private
_dnrm2
DNRM2 DotNumerics.LinearAlgebra.CSLapack.DLAQPS._dnrm2 private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAQPS.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQPS.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAQPS.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQPS.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlaqps.cs