Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAHQR Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAHQR Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAHQR (DLAMCH dlamch, DCOPY dcopy, DLABAD dlabad, DLANV2 dlanv2, DLARFG dlarfg, DROT drot)
DLAHQR ()
void Run (bool WANTT, bool WANTZ, int N, int ILO, int IHI, ref double[] H, int offset_h, int LDH, ref double[] WR, int offset_wr, ref double[] WI, int offset_wi, int ILOZ, int IHIZ, ref double[] Z, int offset_z, int LDZ, ref int INFO)
Private Attributes
DLAMCH _dlamch
DCOPY _dcopy
DLABAD _dlabad
DLANV2 _dlanv2
DLARFG _dlarfg
DROT _drot
double[] V = new double[3]
Static Private Attributes
const int ITMAX = 30
const double ZERO = 0.0E0
const double ONE = 1.0E0
const double TWO = 2.0E0
const double DAT1 = 3.0E0 / 4.0E0
const double DAT2 = - 0.4375E0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAHQR is an auxiliary routine called by DHSEQR to update the eigenvalues and Schur decomposition already computed by DHSEQR, by dealing with the Hessenberg submatrix in rows and columns ILO to IHI.
/summary>
Constructor & Destructor Documentation
DLAHQR() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAHQR.DLAHQR (DLAMCH dlamch, DCOPY dcopy, DLABAD dlabad, DLANV2 dlanv2, DLARFG dlarfg, DROT drot) inline
DLAHQR() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAHQR.DLAHQR () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAHQR.Run (bool WANTT, bool WANTZ, int N, int ILO, int IHI, ref double[] H, int offset_h, int LDH, ref double[] WR, int offset_wr, ref double[] WI, int offset_wi, int ILOZ, int IHIZ, ref double[] Z, int offset_z, int LDZ, ref int INFO) inline
Purpose
DLAHQR is an auxiliary routine called by DHSEQR to update the eigenvalues and Schur decomposition already computed by DHSEQR, by dealing with the Hessenberg submatrix in rows and columns ILO to IHI.
/summary>
Parameters
WANTT (input) LOGICAL = .TRUE. : the full Schur form T is required; = .FALSE.: only eigenvalues are required. /param>
Parameters
WANTZ (input) LOGICAL = .TRUE. : the matrix of Schur vectors Z is required; = .FALSE.: Schur vectors are not required. /param>
Parameters
N (input) INTEGER The order of the matrix H. N .GE. 0. /param>
Parameters
ILO (input) INTEGER /param>
Parameters
IHI (input) INTEGER It is assumed that H is already upper quasi-triangular in rows and columns IHI+1:N, and that H(ILO,ILO-1) = 0 (unless ILO = 1). DLAHQR works primarily with the Hessenberg submatrix in rows and columns ILO to IHI, but applies transformations to all of H if WANTT is .TRUE.. 1 .LE. ILO .LE. max(1,IHI); IHI .LE. N. /param>
Parameters
H (input/output) DOUBLE PRECISION array, dimension (LDH,N) On entry, the upper Hessenberg matrix H. On exit, if INFO is zero and if WANTT is .TRUE., H is upper quasi-triangular in rows and columns ILO:IHI, with any 2-by-2 diagonal blocks in standard form. If INFO is zero and WANTT is .FALSE., the contents of H are unspecified on exit. The output state of H if INFO is nonzero is given below under the description of INFO. /param>
Parameters
LDH (input) INTEGER The leading dimension of the array H. LDH .GE. max(1,N). /param>
Parameters
WR (output) DOUBLE PRECISION array, dimension (N) /param>
Parameters
WI (output) DOUBLE PRECISION array, dimension (N) The real and imaginary parts, respectively, of the computed eigenvalues ILO to IHI are stored in the corresponding elements of WR and WI. If two eigenvalues are computed as a complex conjugate pair, they are stored in consecutive elements of WR and WI, say the i-th and (i+1)th, with WI(i) .GT. 0 and WI(i+1) .LT. 0. If WANTT is .TRUE., the eigenvalues are stored in the same order as on the diagonal of the Schur form returned in H, with WR(i) = H(i,i), and, if H(i:i+1,i:i+1) is a 2-by-2 diagonal block, WI(i) = sqrt(H(i+1,i)*H(i,i+1)) and WI(i+1) = -WI(i). /param>
Parameters
ILOZ (input) INTEGER /param>
Parameters
IHIZ (input) INTEGER Specify the rows of Z to which transformations must be applied if WANTZ is .TRUE.. 1 .LE. ILOZ .LE. ILO; IHI .LE. IHIZ .LE. N. /param>
Parameters
Z (input/output) DOUBLE PRECISION array, dimension (LDZ,N) If WANTZ is .TRUE., on entry Z must contain the current matrix Z of transformations accumulated by DHSEQR, and on exit Z has been updated; transformations are applied only to the submatrix Z(ILOZ:IHIZ,ILO:IHI). If WANTZ is .FALSE., Z is not referenced. /param>
Parameters
LDZ (input) INTEGER The leading dimension of the array Z. LDZ .GE. max(1,N). /param>
Parameters
INFO (output) INTEGER = 0: successful exit .GT. 0: If INFO = i, DLAHQR failed to compute all the eigenvalues ILO to IHI in a total of 30 iterations per eigenvalue; elements i+1:ihi of WR and WI contain those eigenvalues which have been successfully computed.
If INFO .GT. 0 and WANTT is .FALSE., then on exit, the remaining unconverged eigenvalues are the eigenvalues of the upper Hessenberg matrix rows and columns ILO thorugh INFO of the final, output value of H.
If INFO .GT. 0 and WANTT is .TRUE., then on exit (*) (initial value of H)*U = U*(final value of H) where U is an orthognal matrix. The final value of H is upper Hessenberg and triangular in rows and columns INFO+1 through IHI.
If INFO .GT. 0 and WANTZ is .TRUE., then on exit (final value of Z) = (initial value of Z)*U where U is the orthogonal matrix in (*) (regardless of the value of WANTT.) /param>
References DotNumerics.LinearAlgebra.CSLapack.DLAHQR.DAT1, DotNumerics.LinearAlgebra.CSLapack.DLAHQR.DAT2, DotNumerics.LinearAlgebra.CSLapack.DLAHQR.ITMAX, DotNumerics.LinearAlgebra.CSLapack.DLAHQR.ONE, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DROT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLABAD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANV2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAHQR.TWO, DotNumerics.LinearAlgebra.CSLapack.DLAHQR.V, and DotNumerics.LinearAlgebra.CSLapack.DLAHQR.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR3.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR4.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR0.Run(), and DotNumerics.LinearAlgebra.CSLapack.DHSEQR.Run().
Member Data Documentation
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLAHQR._dlamch private
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLAHQR._dcopy private
_dlabad
DLABAD DotNumerics.LinearAlgebra.CSLapack.DLAHQR._dlabad private
_dlanv2
DLANV2 DotNumerics.LinearAlgebra.CSLapack.DLAHQR._dlanv2 private
_dlarfg
DLARFG DotNumerics.LinearAlgebra.CSLapack.DLAHQR._dlarfg private
_drot
DROT DotNumerics.LinearAlgebra.CSLapack.DLAHQR._drot private
ITMAX
const int DotNumerics.LinearAlgebra.CSLapack.DLAHQR.ITMAX = 30 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAHQR.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAHQR.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAHQR.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAHQR.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAHQR.Run().
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DLAHQR.TWO = 2.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAHQR.Run().
DAT1
const double DotNumerics.LinearAlgebra.CSLapack.DLAHQR.DAT1 = 3.0E0 / 4.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAHQR.Run().
DAT2
const double DotNumerics.LinearAlgebra.CSLapack.DLAHQR.DAT2 = - 0.4375E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAHQR.Run().
V
double [] DotNumerics.LinearAlgebra.CSLapack.DLAHQR.V = new double[3] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAHQR.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlahqr.cs