Doc: IGLib EXTENDED: AForge.Imaging.HoughCircleTransformation Class Reference
AForge.Imaging.HoughCircleTransformation Class Reference
Hough circle transformation.
Public Member Functions
HoughCircleTransformation (int radiusToDetect)
Initializes a new instance of the HoughCircleTransformation class.
void ProcessImage (Bitmap image)
Process an image building Hough map.
void ProcessImage (BitmapData imageData)
Process an image building Hough map.
void ProcessImage (UnmanagedImage image)
Process an image building Hough map.
Bitmap ToBitmap ()
Ñonvert Hough map to bitmap.
HoughCircle[] GetMostIntensiveCircles (int count)
Get specified amount of circles with highest intensity.
HoughCircle[] GetCirclesByRelativeIntensity (double minRelativeIntensity)
Get circles with relative intensity higher then specified value.
Properties
short MinCircleIntensity [get, set]
Minimum circle's intensity in Hough map to recognize a circle.
int LocalPeakRadius [get, set]
Radius for searching local peak value.
short MaxIntensity [get]
Maximum found intensity in Hough map.
int CirclesCount [get]
Found circles count.
Private Member Functions
void CollectCircles ()
void DrawHoughCircle (int xCenter, int yCenter)
void SetHoughCirclePoints (int cx, int cy, int x, int y)
void SetHoughPoint (int x, int y)
Private Attributes
int radiusToDetect
short[,] houghMap
short maxMapIntensity = 0
int width
int height
int localPeakRadius = 4
short minCircleIntensity = 10
ArrayList circles = new ArrayList()
Detailed Description
Hough circle transformation.
The class implements Hough circle transformation, which allows to detect circles of specified radius in an image.
The class accepts binary images for processing, which are represented by 8 bpp grayscale images. All black pixels (0 pixel's value) are treated as background, but pixels with different value are treated as circles' pixels.
Sample usage:
HoughCircleTransformation circleTransform = new HoughCircleTransformation(35);
// apply Hough circle transform
circleTransform.ProcessImage(sourceImage);
Bitmap houghCirlceImage = circleTransform.ToBitmap();
// get circles using relative intensity
HoughCircle[] circles = circleTransform.GetCirclesByRelativeIntensity(0.5);
foreach (HoughCircle circle in circles)
{
    // ...
}
Initial image:
Hough circle transformation image:
See also
HoughLineTransformation
Constructor & Destructor Documentation
HoughCircleTransformation()
AForge.Imaging.HoughCircleTransformation.HoughCircleTransformation (int radiusToDetect) inline
Initializes a new instance of the HoughCircleTransformation class.
Parameters
radiusToDetect Circles' radius to detect.
References AForge.Imaging.HoughCircleTransformation.radiusToDetect.
Member Function Documentation
ProcessImage() [1/3]
void AForge.Imaging.HoughCircleTransformation.ProcessImage (Bitmap image) inline
Process an image building Hough map.
Parameters
image Source image to process.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Math.Geometry.Rectangle.
Referenced by HoughTransform.MainForm.openToolStripMenuItem_Click(), and AForge.Imaging.HoughCircleTransformation.ProcessImage().
ProcessImage() [2/3]
void AForge.Imaging.HoughCircleTransformation.ProcessImage (BitmapData imageData) inline
Process an image building Hough map.
Parameters
imageData Source image data to process.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Imaging.HoughCircleTransformation.ProcessImage().
ProcessImage() [3/3]
void AForge.Imaging.HoughCircleTransformation.ProcessImage (UnmanagedImage image) inline
Process an image building Hough map.
Parameters
image Source unmanaged image to process.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Imaging.HoughCircleTransformation.CollectCircles(), AForge.Imaging.HoughCircleTransformation.DrawHoughCircle(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.HoughCircleTransformation.height, AForge.Imaging.HoughCircleTransformation.houghMap, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.HoughCircleTransformation.maxMapIntensity, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.UnmanagedImage.Stride, AForge.Imaging.UnmanagedImage.Width, and AForge.Imaging.HoughCircleTransformation.width.
ToBitmap()
Bitmap AForge.Imaging.HoughCircleTransformation.ToBitmap () inline
Ñonvert Hough map to bitmap.
Returns
Returns 8 bppp grayscale bitmap, which shows Hough map.
Exceptions
ApplicationException Hough transformation was not yet done by calling ProcessImage() method.
References AForge.Imaging.Image.CreateGrayscaleImage(), AForge.Imaging.HoughCircleTransformation.height, AForge.Imaging.HoughCircleTransformation.houghMap, AForge.Imaging.HoughCircleTransformation.maxMapIntensity, AForge.Math.Geometry.Rectangle, and AForge.Imaging.HoughCircleTransformation.width.
Referenced by HoughTransform.MainForm.openToolStripMenuItem_Click().
GetMostIntensiveCircles()
HoughCircle [] AForge.Imaging.HoughCircleTransformation.GetMostIntensiveCircles (int count) inline
Get specified amount of circles with highest intensity.
Parameters
count Amount of circles to get.
Returns
Returns arrary of most intesive circles. If there are no circles detected, the returned array has zero length.
References AForge.Imaging.HoughCircleTransformation.circles.
Referenced by AForge.Imaging.HoughCircleTransformation.GetCirclesByRelativeIntensity().
GetCirclesByRelativeIntensity()
HoughCircle [] AForge.Imaging.HoughCircleTransformation.GetCirclesByRelativeIntensity (double minRelativeIntensity) inline
Get circles with relative intensity higher then specified value.
Parameters
minRelativeIntensity Minimum relative intesity of circles.
Returns
Returns arrary of most intesive circles. If there are no circles detected, the returned array has zero length.
References AForge.Imaging.HoughCircleTransformation.circles, and AForge.Imaging.HoughCircleTransformation.GetMostIntensiveCircles().
Referenced by HoughTransform.MainForm.openToolStripMenuItem_Click().
CollectCircles()
void AForge.Imaging.HoughCircleTransformation.CollectCircles () inline private
References AForge.Imaging.HoughCircleTransformation.circles, AForge.Imaging.HoughCircleTransformation.height, AForge.Imaging.HoughCircleTransformation.houghMap, AForge.Imaging.HoughCircleTransformation.localPeakRadius, AForge.Imaging.HoughCircleTransformation.maxMapIntensity, AForge.Imaging.HoughCircleTransformation.minCircleIntensity, AForge.Imaging.HoughCircleTransformation.radiusToDetect, and AForge.Imaging.HoughCircleTransformation.width.
Referenced by AForge.Imaging.HoughCircleTransformation.ProcessImage().
DrawHoughCircle()
void AForge.Imaging.HoughCircleTransformation.DrawHoughCircle (int xCenter, int yCenter) inline private
References AForge.Imaging.HoughCircleTransformation.radiusToDetect, and AForge.Imaging.HoughCircleTransformation.SetHoughCirclePoints().
Referenced by AForge.Imaging.HoughCircleTransformation.ProcessImage().
SetHoughCirclePoints()
void AForge.Imaging.HoughCircleTransformation.SetHoughCirclePoints (int cx, int cy, int x, int y) inline private
References AForge.Imaging.HoughCircleTransformation.SetHoughPoint().
Referenced by AForge.Imaging.HoughCircleTransformation.DrawHoughCircle().
SetHoughPoint()
void AForge.Imaging.HoughCircleTransformation.SetHoughPoint (int x, int y) inline private
References AForge.Imaging.HoughCircleTransformation.height, AForge.Imaging.HoughCircleTransformation.houghMap, and AForge.Imaging.HoughCircleTransformation.width.
Referenced by AForge.Imaging.HoughCircleTransformation.SetHoughCirclePoints().
Member Data Documentation
radiusToDetect
int AForge.Imaging.HoughCircleTransformation.radiusToDetect private
Referenced by AForge.Imaging.HoughCircleTransformation.CollectCircles(), AForge.Imaging.HoughCircleTransformation.DrawHoughCircle(), and AForge.Imaging.HoughCircleTransformation.HoughCircleTransformation().
houghMap
short [,] AForge.Imaging.HoughCircleTransformation.houghMap private
Referenced by AForge.Imaging.HoughCircleTransformation.CollectCircles(), AForge.Imaging.HoughCircleTransformation.ProcessImage(), AForge.Imaging.HoughCircleTransformation.SetHoughPoint(), and AForge.Imaging.HoughCircleTransformation.ToBitmap().
maxMapIntensity
short AForge.Imaging.HoughCircleTransformation.maxMapIntensity = 0 private
Referenced by AForge.Imaging.HoughCircleTransformation.CollectCircles(), AForge.Imaging.HoughCircleTransformation.ProcessImage(), and AForge.Imaging.HoughCircleTransformation.ToBitmap().
width
int AForge.Imaging.HoughCircleTransformation.width private
Referenced by AForge.Imaging.HoughCircleTransformation.CollectCircles(), AForge.Imaging.HoughCircleTransformation.ProcessImage(), AForge.Imaging.HoughCircleTransformation.SetHoughPoint(), and AForge.Imaging.HoughCircleTransformation.ToBitmap().
height
int AForge.Imaging.HoughCircleTransformation.height private
Referenced by AForge.Imaging.HoughCircleTransformation.CollectCircles(), AForge.Imaging.HoughCircleTransformation.ProcessImage(), AForge.Imaging.HoughCircleTransformation.SetHoughPoint(), and AForge.Imaging.HoughCircleTransformation.ToBitmap().
localPeakRadius
int AForge.Imaging.HoughCircleTransformation.localPeakRadius = 4 private
Referenced by AForge.Imaging.HoughCircleTransformation.CollectCircles().
minCircleIntensity
short AForge.Imaging.HoughCircleTransformation.minCircleIntensity = 10 private
Referenced by AForge.Imaging.HoughCircleTransformation.CollectCircles().
circles
ArrayList AForge.Imaging.HoughCircleTransformation.circles = new ArrayList() private
Referenced by AForge.Imaging.HoughCircleTransformation.CollectCircles(), AForge.Imaging.HoughCircleTransformation.GetCirclesByRelativeIntensity(), and AForge.Imaging.HoughCircleTransformation.GetMostIntensiveCircles().
Property Documentation
MinCircleIntensity
short AForge.Imaging.HoughCircleTransformation.MinCircleIntensity get set
Minimum circle's intensity in Hough map to recognize a circle.
The value sets minimum intensity level for a circle. If a value in Hough map has lower intensity, then it is not treated as a circle.
Default value is set to 10.
Referenced by HoughTransform.MainForm.MainForm().
LocalPeakRadius
int AForge.Imaging.HoughCircleTransformation.LocalPeakRadius get set
Radius for searching local peak value.
The value determines radius around a map's value, which is analyzed to determine if the map's value is a local maximum in specified area.
Default value is set to 4. Minimum value is 1. Maximum value is 10.
MaxIntensity
short AForge.Imaging.HoughCircleTransformation.MaxIntensity get
Maximum found intensity in Hough map.
The property provides maximum found circle's intensity.
Referenced by HoughTransform.MainForm.openToolStripMenuItem_Click().
CirclesCount
int AForge.Imaging.HoughCircleTransformation.CirclesCount get
Found circles count.
The property provides total number of found circles, which intensity is higher (or equal to), than the requested minimum intensity.
Referenced by HoughTransform.MainForm.openToolStripMenuItem_Click().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/HoughCircleTransformation.cs