Doc: IGLib EXTENDED: alglib.lincg.lincgreport Class Reference
alglib.lincg.lincgreport Class Reference
Public Member Functions
lincgreport ()
override void init ()
override alglib.apobject make_copy ()
Public Attributes
int iterationscount
int nmv
int terminationtype
double r2
Constructor & Destructor Documentation
lincgreport()
alglib.lincg.lincgreport.lincgreport () inline
References alglib.lincg.lincgreport.init().
Referenced by alglib.lincg.lincgreport.make_copy().
Member Function Documentation
init()
override void alglib.lincg.lincgreport.init () inline
Referenced by alglib.lincg.lincgreport.lincgreport().
make_copy()
override alglib.apobject alglib.lincg.lincgreport.make_copy () inline
References alglib.lincg.lincgreport.iterationscount, alglib.lincg.lincgreport.lincgreport(), alglib.lincg.lincgreport.nmv, alglib.lincg.lincgreport.r2, and alglib.lincg.lincgreport.terminationtype.
Member Data Documentation
iterationscount
int alglib.lincg.lincgreport.iterationscount
Referenced by alglib.lincg.lincgresults(), and alglib.lincg.lincgreport.make_copy().
nmv
int alglib.lincg.lincgreport.nmv
Referenced by alglib.lincg.lincgresults(), and alglib.lincg.lincgreport.make_copy().
terminationtype
int alglib.lincg.lincgreport.terminationtype
Referenced by alglib.lincg.lincgresults(), and alglib.lincg.lincgreport.make_copy().
r2
double alglib.lincg.lincgreport.r2
Referenced by alglib.lincg.lincgresults(), and alglib.lincg.lincgreport.make_copy().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/solvers.cs