Doc: IGLib EXTENDED: CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel Class Reference
CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel Class Reference
Public Member Functions
XhtmlSinkViewModel (Uri uri)
override void Dump (object o, string description)
void Dump (object o, string description, int depth)
override void Clear ()
override bool Equals (object obj)
Public Member Functions inherited from CShell.Framework.Sink
virtual void Dump (object o)
Public Member Functions inherited from CShell.Framework.Document
virtual void Save ()
virtual void SaveAs (string newFile)
Protected Member Functions
override void OnDeactivate (bool close)
Protected Member Functions inherited from CShell.Framework.Sink
Sink ()
string GetUriPathPart (Uri uri, int pathIndex)
Gets the display name from the uri, which is usually the second part of the absolute path.
string GetTitle (Uri uri, string defaultTitle)
Properties
override PaneLocation PreferredLocation [get]
string Text [get]
Properties inherited from CShell.Framework.Sink
virtual Uri IconSource [get]
bool IsVisible [get, set]
virtual PaneLocation PreferredLocation [get]
Properties inherited from CShell.Framework.Document
ICommand?? CloseCommand [get]
virtual Uri Uri [get, set]
virtual bool IsDirty [get, set]
Properties inherited from CShell.Framework.IDocument
ICommand CloseCommand [get]
Uri Uri [get]
bool IsDirty [get]
Properties inherited from CShell.Framework.ISink
PaneLocation PreferredLocation [get]
bool IsVisible [get, set]
Private Attributes
StringBuilder stringBuilder
StringWriter stringWriter
XhtmlDumper.XhtmlDumper xhtmlDumper
TextWriter linqPadWriter
string text = ""
Constructor & Destructor Documentation
XhtmlSinkViewModel()
CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.XhtmlSinkViewModel (Uri uri) inline
References CShell.Framework.Sink.GetTitle(), and CShell.Framework.Document.Uri.
Referenced by CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.Equals().
Member Function Documentation
Dump() [1/2]
override void CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.Dump (object o, string description) inline virtual
Implements CShell.Framework.Sink.
Dump() [2/2]
void CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.Dump (object o, string description, int depth) inline
Implements CShell.Sinks.IXhtmlSink.
References CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.stringBuilder, CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.stringWriter, CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.text, CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.Text, and CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.xhtmlDumper.
Clear()
override void CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.Clear () inline virtual
Implements CShell.Framework.Sink.
References CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.linqPadWriter, CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.text, and CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.Text.
Referenced by CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.OnDeactivate().
OnDeactivate()
override void CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.OnDeactivate (bool close) inline protected
References CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.Clear().
Equals()
override bool CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.Equals (object obj) inline
References CShell.Framework.Document.Uri, and CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.XhtmlSinkViewModel().
Member Data Documentation
stringBuilder
StringBuilder CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.stringBuilder private
Referenced by CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.Dump().
stringWriter
StringWriter CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.stringWriter private
Referenced by CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.Dump().
xhtmlDumper
XhtmlDumper.XhtmlDumper CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.xhtmlDumper private
Referenced by CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.Dump().
linqPadWriter
TextWriter CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.linqPadWriter private
Referenced by CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.Clear().
text
string CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.text = "" private
Referenced by CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.Clear(), and CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.Dump().
Property Documentation
PreferredLocation
override PaneLocation CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.PreferredLocation get
Text
string CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.Text get
Referenced by CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.Clear(), and CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.Dump().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Sink/ViewModels/XhtmlSinkViewModel.cs