Doc: IGLib EXTENDED: NUnit.Framework.Constraints.ExactCountConstraintTests Class Reference
NUnit.Framework.Constraints.ExactCountConstraintTests Class Reference
Public Member Functions
void ZeroItemsMatch ()
void ZeroItemsMatchFails ()
void ExactlyOneItemMatches ()
void ExactlyOneItemMatchFails ()
void ExactlyTwoItemsMatch ()
void ExactlyTwoItemsMatchFails ()
Static Private Attributes
static readonly string[] names = new string[] { "Charlie", "Fred", "Joe", "Charlie" }
Member Function Documentation
ZeroItemsMatch()
void NUnit.Framework.Constraints.ExactCountConstraintTests.ZeroItemsMatch () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Has.Exactly(), NUnit.Framework.Constraints.ExactCountConstraintTests.names, and NUnit.Framework.Assert.That().
ZeroItemsMatchFails()
void NUnit.Framework.Constraints.ExactCountConstraintTests.ZeroItemsMatchFails () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Constraints.ExactCountConstraintTests.names, NUnit.Env.NewLine, NUnit.Framework.Internal.TextMessageWriter.Pfx_Actual, NUnit.Framework.Internal.TextMessageWriter.Pfx_Expected, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
ExactlyOneItemMatches()
void NUnit.Framework.Constraints.ExactCountConstraintTests.ExactlyOneItemMatches () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Has.Exactly(), NUnit.Framework.Constraints.ExactCountConstraintTests.names, and NUnit.Framework.Assert.That().
ExactlyOneItemMatchFails()
void NUnit.Framework.Constraints.ExactCountConstraintTests.ExactlyOneItemMatchFails () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Constraints.ExactCountConstraintTests.names, NUnit.Env.NewLine, NUnit.Framework.Internal.TextMessageWriter.Pfx_Actual, NUnit.Framework.Internal.TextMessageWriter.Pfx_Expected, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
ExactlyTwoItemsMatch()
void NUnit.Framework.Constraints.ExactCountConstraintTests.ExactlyTwoItemsMatch () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Has.Exactly(), NUnit.Framework.Constraints.ExactCountConstraintTests.names, and NUnit.Framework.Assert.That().
ExactlyTwoItemsMatchFails()
void NUnit.Framework.Constraints.ExactCountConstraintTests.ExactlyTwoItemsMatchFails () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Constraints.ExactCountConstraintTests.names, NUnit.Env.NewLine, NUnit.Framework.Internal.TextMessageWriter.Pfx_Actual, NUnit.Framework.Internal.TextMessageWriter.Pfx_Expected, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
Member Data Documentation
names
readonly string [] NUnit.Framework.Constraints.ExactCountConstraintTests.names = new string[] { "Charlie", "Fred", "Joe", "Charlie" } static private
Referenced by NUnit.Framework.Constraints.ExactCountConstraintTests.ExactlyOneItemMatches(), NUnit.Framework.Constraints.ExactCountConstraintTests.ExactlyOneItemMatchFails(), NUnit.Framework.Constraints.ExactCountConstraintTests.ExactlyTwoItemsMatch(), NUnit.Framework.Constraints.ExactCountConstraintTests.ExactlyTwoItemsMatchFails(), NUnit.Framework.Constraints.ExactCountConstraintTests.ZeroItemsMatch(), and NUnit.Framework.Constraints.ExactCountConstraintTests.ZeroItemsMatchFails().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/ExactCountConstraintTests.cs