Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DSYMV Class Reference
DotNumerics.LinearAlgebra.CSLapack.DSYMV Class Reference
Public Member Functions
DSYMV (LSAME lsame, XERBLA xerbla)
DSYMV ()
void Run (string UPLO, int N, double ALPHA, double[] A, int offset_a, int LDA, double[] X, int offset_x, int INCX, double BETA, ref double[] Y, int offset_y, int INCY)
Private Attributes
LSAME _lsame
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
Purpose
DSYMV performs the matrix-vector operation
y := alpha*A*x + beta*y,
where alpha and beta are scalars, x and y are n element vectors and A is an n by n symmetric matrix.
/summary>
Constructor & Destructor Documentation
DSYMV() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DSYMV.DSYMV (LSAME lsame, XERBLA xerbla) inline
DSYMV() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DSYMV.DSYMV () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DSYMV.Run (string UPLO, int N, double ALPHA, double[] A, int offset_a, int LDA, double[] X, int offset_x, int INCX, double BETA, ref double[] Y, int offset_y, int INCY) inline
Purpose
DSYMV performs the matrix-vector operation
y := alpha*A*x + beta*y,
where alpha and beta are scalars, x and y are n element vectors and A is an n by n symmetric matrix.
/summary>
Parameters
UPLO
CHARACTER*1. On entry, UPLO specifies whether the upper or lower triangular part of the array A is to be referenced as follows:
UPLO = 'U' or 'u' Only the upper triangular part of A is to be referenced.
UPLO = 'L' or 'l' Only the lower triangular part of A is to be referenced.
Unchanged on exit. /param>
Parameters
N
INTEGER. On entry, N specifies the order of the matrix A. N must be at least zero. Unchanged on exit. /param>
Parameters
ALPHA
DOUBLE PRECISION. On entry, ALPHA specifies the scalar alpha. Unchanged on exit. /param>
Parameters
A
DOUBLE PRECISION array of DIMENSION (LDA, n). Before entry with UPLO = 'U' or 'u', the leading n by n upper triangular part of the array A must contain the upper triangular part of the symmetric matrix and the strictly lower triangular part of A is not referenced. Before entry with UPLO = 'L' or 'l', the leading n by n lower triangular part of the array A must contain the lower triangular part of the symmetric matrix and the strictly upper triangular part of A is not referenced. Unchanged on exit. /param>
Parameters
LDA
INTEGER. On entry, LDA specifies the first dimension of A as declared in the calling (sub) program. LDA must be at least max(1, n). Unchanged on exit. /param>
Parameters
X
DOUBLE PRECISION array of dimension at least (1 + (n - 1)*abs(INCX)). Before entry, the incremented array X must contain the n element vector x. Unchanged on exit. /param>
Parameters
INCX
INTEGER. On entry, INCX specifies the increment for the elements of X. INCX must not be zero. Unchanged on exit. /param>
Parameters
BETA
DOUBLE PRECISION. On entry, BETA specifies the scalar beta. When BETA is supplied as zero then Y need not be set on input. Unchanged on exit. /param>
Parameters
Y := alpha*A*x + beta*y, /param>
Parameters
INCY
INTEGER. On entry, INCY specifies the increment for the elements of Y. INCY must not be zero. Unchanged on exit.
/param>
References DotNumerics.LinearAlgebra.CSLapack.DSYMV.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), and DotNumerics.LinearAlgebra.CSLapack.DSYMV.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYTD2.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLATRD.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DSYMV._lsame private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DSYMV._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DSYMV.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYMV.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DSYMV.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYMV.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dsymv.cs