Doc: IGLib EXTENDED: AForge.Imaging.Textures.TextureTools Class Reference
AForge.Imaging.Textures.TextureTools Class Reference
Texture tools.
Static Public Member Functions
static Bitmap ToBitmap (float[,] texture)
Convert texture to grayscale bitmap.
static float[,] FromBitmap (Bitmap image)
Convert grayscale bitmap to texture.
static float[,] FromBitmap (BitmapData imageData)
Convert grayscale bitmap to texture
static float[,] FromBitmap (UnmanagedImage image)
Convert grayscale bitmap to texture.
Private Member Functions
TextureTools ()
Detailed Description
Texture tools.
The class represents collection of different texture tools, like converting a texture to/from grayscale image.
Sample usage:
// create texture generator
WoodTexture textureGenerator = new WoodTexture();
// generate new texture
float[,] texture = textureGenerator.Generate(320, 240);
// convert it to image to visualize
Bitmap textureImage = TextureTools.ToBitmap(texture);
Constructor & Destructor Documentation
TextureTools()
AForge.Imaging.Textures.TextureTools.TextureTools () inline private
Member Function Documentation
ToBitmap()
static Bitmap AForge.Imaging.Textures.TextureTools.ToBitmap (float texture[,]) inline static
Convert texture to grayscale bitmap.
Parameters
texture Texture to convert to bitmap.
Returns
Returns bitmap of the texture.
References AForge.Imaging.Image.CreateGrayscaleImage(), and AForge.Math.Geometry.Rectangle.
Referenced by TexturesDemo.MainForm.ShowTexture().
FromBitmap() [1/3]
static float [,] AForge.Imaging.Textures.TextureTools.FromBitmap (Bitmap image) inline static
Convert grayscale bitmap to texture.
Parameters
image Image to convert to texture.
Returns
Returns texture as 2D float array.
Exceptions
UnsupportedImageFormatException Only grayscale (8 bpp indexed images) are supported.
References AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.Textures.TextureTools.FromBitmap().
FromBitmap() [2/3]
static float [,] AForge.Imaging.Textures.TextureTools.FromBitmap (BitmapData imageData) inline static
Convert grayscale bitmap to texture
Parameters
imageData Image data to convert to texture
Returns
Returns texture as 2D float array.
Exceptions
UnsupportedImageFormatException Only grayscale (8 bpp indexed images) are supported.
References AForge.Imaging.Textures.TextureTools.FromBitmap().
FromBitmap() [3/3]
static float [,] AForge.Imaging.Textures.TextureTools.FromBitmap (UnmanagedImage image) inline static
Convert grayscale bitmap to texture.
Parameters
image Image data to convert to texture.
Returns
Returns texture as 2D float array.
Exceptions
UnsupportedImageFormatException Only grayscale (8 bpp indexed images) are supported.
References AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Textures/Texture.cs