Doc: IGLib EXTENDED: IG.Forms.MathematicaCalculatorApp Class Reference
IG.Forms.MathematicaCalculatorApp Class Reference
Public Member Functions
MathematicaCalculatorApp ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void mathematicaCalculatorControl1_Load (object sender, EventArgs e)
void btnClose_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
MathematicaCalculatorControl mathematicaCalculatorControl1
System.Windows.Forms.Button btnClose
Constructor & Destructor Documentation
MathematicaCalculatorApp()
IG.Forms.MathematicaCalculatorApp.MathematicaCalculatorApp () inline
References IG.Forms.MathematicaCalculatorApp.InitializeComponent().
Member Function Documentation
mathematicaCalculatorControl1_Load()
void IG.Forms.MathematicaCalculatorApp.mathematicaCalculatorControl1_Load (object sender, EventArgs e) inline private
Referenced by IG.Forms.MathematicaCalculatorApp.InitializeComponent().
btnClose_Click()
void IG.Forms.MathematicaCalculatorApp.btnClose_Click (object sender, EventArgs e) inline private
Referenced by IG.Forms.MathematicaCalculatorApp.InitializeComponent().
Dispose()
override void IG.Forms.MathematicaCalculatorApp.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.MathematicaCalculatorApp.components.
InitializeComponent()
void IG.Forms.MathematicaCalculatorApp.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.MathematicaCalculatorApp.btnClose, IG.Forms.MathematicaCalculatorApp.btnClose_Click(), IG.Forms.MathematicaCalculatorApp.mathematicaCalculatorControl1, and IG.Forms.MathematicaCalculatorApp.mathematicaCalculatorControl1_Load().
Referenced by IG.Forms.MathematicaCalculatorApp.MathematicaCalculatorApp().
Member Data Documentation
components
System.ComponentModel.IContainer IG.Forms.MathematicaCalculatorApp.components = null private
Required designer variable.
Referenced by IG.Forms.MathematicaCalculatorApp.Dispose().
mathematicaCalculatorControl1
MathematicaCalculatorControl IG.Forms.MathematicaCalculatorApp.mathematicaCalculatorControl1 private
Referenced by IG.Forms.MathematicaCalculatorApp.InitializeComponent().
btnClose
System.Windows.Forms.Button IG.Forms.MathematicaCalculatorApp.btnClose private
Referenced by IG.Forms.MathematicaCalculatorApp.InitializeComponent().
The documentation for this class was generated from the following files:
igtest/IGLibTestShellExt/mathematica/forms/MathematicaCalculatorApp.cs
igtest/IGLibTestShellExt/mathematica/forms/MathematicaCalculatorApp.Designer.cs