Doc: IGLib EXTENDED: AForge.MachineLearning.IExplorationPolicy Interface Reference
AForge.MachineLearning.IExplorationPolicy Interface Reference
Exploration policy interface.
Public Member Functions
int ChooseAction (double[] actionEstimates)
Choose an action.
Detailed Description
Exploration policy interface.
The interface describes exploration policies, which are used in Reinforcement Learning to explore state space.
Member Function Documentation
ChooseAction()
int AForge.MachineLearning.IExplorationPolicy.ChooseAction (double[] actionEstimates)
Choose an action.
Parameters
actionEstimates Action estimates.
Returns
Returns selected action.
The method chooses an action depending on the provided estimates. The estimates can be any sort of estimate, which values usefulness of the action (expected summary reward, discounted reward, etc).
Implemented in AForge.MachineLearning.BoltzmannExploration, AForge.MachineLearning.TabuSearchExploration, AForge.MachineLearning.EpsilonGreedyExploration, and AForge.MachineLearning.RouletteWheelExploration.
Referenced by AForge.MachineLearning.TabuSearchExploration.ChooseAction(), AForge.MachineLearning.Sarsa.GetAction(), and AForge.MachineLearning.QLearning.GetAction().
The documentation for this interface was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/MachineLearning/Exploration Policy/IExplorationPolicy.cs