Doc: IGLib EXTENDED: NUnit.Framework.Attributes.TheoryTests Class Reference
NUnit.Framework.Attributes.TheoryTests Class Reference
Classes
class SqrtTests
Public Member Functions
void TheoryWithNoArgumentsIsTreatedAsTest ()
void TheoryWithNoDatapointsIsNotRunnable ()
void TheoryWithDatapointsIsRunnable ()
void BooleanArgumentsAreSuppliedAutomatically ()
void DatapointAndAttributeDataMayBeCombined ()
void NullDatapointIsOK (object o)
void EnumArgumentsAreSuppliedAutomatically ()
void AllValuesMayBeSuppliedByAttributes ()
void SquareRootWithAllGoodValues ([Values(12.0, 4.0, 9.0)] double d)
void SquareRootWithOneBadValue ([Values(12.0, -4.0, 9.0)] double d)
void ArrayWithDatapointsAttributeIsUsed (string s)
void SimpleTestIgnoresDataPoints ()
void TheoryFailsIfAllTestsAreInconclusive ()
Static Private Member Functions
static void SquareRootTest (double d)
Private Attributes
object nullObj = null
string[] vals = new string[] { "xyz1", "xyz2", "xyz3" }
Static Private Attributes
static readonly Type fixtureType = typeof(TheoryFixture)
Member Function Documentation
TheoryWithNoArgumentsIsTreatedAsTest()
void NUnit.Framework.Attributes.TheoryTests.TheoryWithNoArgumentsIsTreatedAsTest () inline
References NUnit.Framework.Attributes.TheoryTests.fixtureType, and NUnit.TestUtilities.TestAssert.IsRunnable().
TheoryWithNoDatapointsIsNotRunnable()
void NUnit.Framework.Attributes.TheoryTests.TheoryWithNoDatapointsIsNotRunnable () inline
References NUnit.Framework.Attributes.TheoryTests.fixtureType, and NUnit.TestUtilities.TestAssert.IsNotRunnable().
TheoryWithDatapointsIsRunnable()
void NUnit.Framework.Attributes.TheoryTests.TheoryWithDatapointsIsRunnable () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TheoryTests.fixtureType, NUnit.TestUtilities.TestAssert.IsRunnable(), NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), NUnit.Framework.Internal.Test.TestCaseCount, and NUnit.Framework.Assert.That().
BooleanArgumentsAreSuppliedAutomatically()
void NUnit.Framework.Attributes.TheoryTests.BooleanArgumentsAreSuppliedAutomatically () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TheoryTests.fixtureType, NUnit.TestUtilities.TestAssert.IsRunnable(), NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), NUnit.Framework.Internal.Test.TestCaseCount, and NUnit.Framework.Assert.That().
DatapointAndAttributeDataMayBeCombined()
void NUnit.Framework.Attributes.TheoryTests.DatapointAndAttributeDataMayBeCombined () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TheoryTests.fixtureType, NUnit.TestUtilities.TestAssert.IsRunnable(), NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), NUnit.Framework.Internal.Test.TestCaseCount, and NUnit.Framework.Assert.That().
NullDatapointIsOK()
void NUnit.Framework.Attributes.TheoryTests.NullDatapointIsOK (object o) inline
References NUnit.Framework.Assert.Null(), and NUnit.Framework.Attributes.TheoryTests.nullObj.
EnumArgumentsAreSuppliedAutomatically()
void NUnit.Framework.Attributes.TheoryTests.EnumArgumentsAreSuppliedAutomatically () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TheoryTests.fixtureType, NUnit.TestUtilities.TestAssert.IsRunnable(), NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), NUnit.Framework.Internal.Test.TestCaseCount, and NUnit.Framework.Assert.That().
AllValuesMayBeSuppliedByAttributes()
void NUnit.Framework.Attributes.TheoryTests.AllValuesMayBeSuppliedByAttributes () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TheoryTests.fixtureType, NUnit.TestUtilities.TestAssert.IsRunnable(), NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), NUnit.Framework.Internal.Test.TestCaseCount, and NUnit.Framework.Assert.That().
SquareRootWithAllGoodValues()
void NUnit.Framework.Attributes.TheoryTests.SquareRootWithAllGoodValues ([Values(12.0, 4.0, 9.0)] double d) inline
References NUnit.Framework.Attributes.TheoryTests.SquareRootTest().
SquareRootWithOneBadValue()
void NUnit.Framework.Attributes.TheoryTests.SquareRootWithOneBadValue ([Values(12.0, -4.0, 9.0)] double d) inline
References NUnit.Framework.Attributes.TheoryTests.SquareRootTest().
ArrayWithDatapointsAttributeIsUsed()
void NUnit.Framework.Attributes.TheoryTests.ArrayWithDatapointsAttributeIsUsed (string s) inline
References NUnit.Framework.Assert.That().
SquareRootTest()
static void NUnit.Framework.Attributes.TheoryTests.SquareRootTest (double d) inline static private
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
Referenced by NUnit.Framework.Attributes.TheoryTests.SquareRootWithAllGoodValues(), and NUnit.Framework.Attributes.TheoryTests.SquareRootWithOneBadValue().
SimpleTestIgnoresDataPoints()
void NUnit.Framework.Attributes.TheoryTests.SimpleTestIgnoresDataPoints () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TheoryTests.fixtureType, NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), NUnit.Framework.Internal.Test.TestCaseCount, and NUnit.Framework.Assert.That().
TheoryFailsIfAllTestsAreInconclusive()
void NUnit.Framework.Attributes.TheoryTests.TheoryFailsIfAllTestsAreInconclusive () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.Failure, NUnit.Framework.Attributes.TheoryTests.fixtureType, NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunParameterizedMethodSuite(), and NUnit.Framework.Assert.That().
Member Data Documentation
fixtureType
readonly Type NUnit.Framework.Attributes.TheoryTests.fixtureType = typeof(TheoryFixture) static private
Referenced by NUnit.Framework.Attributes.TheoryTests.AllValuesMayBeSuppliedByAttributes(), NUnit.Framework.Attributes.TheoryTests.BooleanArgumentsAreSuppliedAutomatically(), NUnit.Framework.Attributes.TheoryTests.DatapointAndAttributeDataMayBeCombined(), NUnit.Framework.Attributes.TheoryTests.EnumArgumentsAreSuppliedAutomatically(), NUnit.Framework.Attributes.TheoryTests.SimpleTestIgnoresDataPoints(), NUnit.Framework.Attributes.TheoryTests.TheoryFailsIfAllTestsAreInconclusive(), NUnit.Framework.Attributes.TheoryTests.TheoryWithDatapointsIsRunnable(), NUnit.Framework.Attributes.TheoryTests.TheoryWithNoArgumentsIsTreatedAsTest(), and NUnit.Framework.Attributes.TheoryTests.TheoryWithNoDatapointsIsNotRunnable().
nullObj
object NUnit.Framework.Attributes.TheoryTests.nullObj = null private
Referenced by NUnit.Framework.Attributes.TheoryTests.NullDatapointIsOK().
vals
string [] NUnit.Framework.Attributes.TheoryTests.vals = new string[] { "xyz1", "xyz2", "xyz3" } private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/TheoryTests.cs