Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGETRI Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGETRI Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGETRI (ILAENV ilaenv, DGEMM dgemm, DGEMV dgemv, DSWAP dswap, DTRSM dtrsm, DTRTRI dtrtri, XERBLA xerbla)
DGETRI ()
void Run (int N, ref double[] A, int offset_a, int LDA, int[] IPIV, int offset_ipiv, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
ILAENV _ilaenv
DGEMM _dgemm
DGEMV _dgemv
DSWAP _dswap
DTRSM _dtrsm
DTRTRI _dtrtri
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGETRI computes the inverse of a matrix using the LU factorization computed by DGETRF.
This method inverts U and then computes inv(A) by solving the system inv(A)*L = inv(U) for inv(A).
/summary>
Constructor & Destructor Documentation
DGETRI() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGETRI.DGETRI (ILAENV ilaenv, DGEMM dgemm, DGEMV dgemv, DSWAP dswap, DTRSM dtrsm, DTRTRI dtrtri, XERBLA xerbla) inline
DGETRI() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGETRI.DGETRI () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGETRI.Run (int N, ref double[] A, int offset_a, int LDA, int[] IPIV, int offset_ipiv, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DGETRI computes the inverse of a matrix using the LU factorization computed by DGETRF.
This method inverts U and then computes inv(A) by solving the system inv(A)*L = inv(U) for inv(A).
/summary>
Parameters
N (input) INTEGER The order of the matrix A. N .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the factors L and U from the factorization A = P*L*U as computed by DGETRF. On exit, if INFO = 0, the inverse of the original matrix A. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,N). /param>
Parameters
IPIV (input) INTEGER array, dimension (N) The pivot indices from DGETRF; for 1.LE.i.LE.N, row i of the matrix was interchanged with row IPIV(i). /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO=0, then WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. max(1,N). For optimal performance LWORK .GE. N*NB, where NB is the optimal blocksize returned by ILAENV.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value .GT. 0: if INFO = i, U(i,i) is exactly zero; the matrix is singular and its inverse could not be computed. /param>
References DotNumerics.LinearAlgebra.CSLapack.DGETRI.ONE, DotNumerics.LinearAlgebra.CSLapack.DSWAP.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRTRI.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRSM.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGETRI.ZERO.
Member Data Documentation
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DGETRI._ilaenv private
_dgemm
DGEMM DotNumerics.LinearAlgebra.CSLapack.DGETRI._dgemm private
_dgemv
DGEMV DotNumerics.LinearAlgebra.CSLapack.DGETRI._dgemv private
_dswap
DSWAP DotNumerics.LinearAlgebra.CSLapack.DGETRI._dswap private
_dtrsm
DTRSM DotNumerics.LinearAlgebra.CSLapack.DGETRI._dtrsm private
_dtrtri
DTRTRI DotNumerics.LinearAlgebra.CSLapack.DGETRI._dtrtri private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGETRI._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DGETRI.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGETRI.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGETRI.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGETRI.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgetri.cs