Doc: IGLib EXTENDED: ADOGuy.Evaluator Class Reference
ADOGuy.Evaluator Class Reference
Summary description for Class1.
Public Member Functions
Evaluator (EvaluatorItem[] items)
Evaluator (Type returnType, string expression, string name)
Evaluator (EvaluatorItem item)
int EvaluateInt (string name)
string EvaluateString (string name)
bool EvaluateBool (string name)
object Evaluate (string name)
Evaluator (EvaluatorItem[] items)
Evaluator (Type returnType, string expression, string name)
Evaluator (EvaluatorItem item)
int EvaluateInt (string name)
string EvaluateString (string name)
bool EvaluateBool (string name)
object Evaluate (string name)
Static Public Member Functions
static int EvaluateToInteger (string code)
static string EvaluateToString (string code)
static bool EvaluateToBool (string code)
static object EvaluateToObject (string code)
static int EvaluateToInteger (string code)
static double EvaluateToDouble (string code)
static string EvaluateToString (string code)
static bool EvaluateToBool (string code)
static object EvaluateToObject (string code)
Private Member Functions
void ConstructEvaluator (EvaluatorItem[] items)
void ConstructEvaluator (EvaluatorItem[] items)
Private Attributes
Type _CompiledType = null
object _Compiled = null
Static Private Attributes
const string staticMethodName = "__foo"
Detailed Description
Summary description for Class1.
Constructor & Destructor Documentation
Evaluator() [1/6]
ADOGuy.Evaluator.Evaluator (EvaluatorItem[] items) inline
References ADOGuy.Evaluator.ConstructEvaluator().
Referenced by ADOGuy.Evaluator.EvaluateToBool(), ADOGuy.Evaluator.EvaluateToDouble(), ADOGuy.Evaluator.EvaluateToInteger(), ADOGuy.Evaluator.EvaluateToObject(), and ADOGuy.Evaluator.EvaluateToString().
Evaluator() [2/6]
ADOGuy.Evaluator.Evaluator (Type returnType, string expression, string name) inline
References ADOGuy.Evaluator.ConstructEvaluator().
Evaluator() [3/6]
ADOGuy.Evaluator.Evaluator (EvaluatorItem item) inline
References ADOGuy.Evaluator.ConstructEvaluator().
Evaluator() [4/6]
ADOGuy.Evaluator.Evaluator (EvaluatorItem[] items) inline
References ADOGuy.Evaluator.ConstructEvaluator().
Evaluator() [5/6]
ADOGuy.Evaluator.Evaluator (Type returnType, string expression, string name) inline
References ADOGuy.Evaluator.ConstructEvaluator().
Evaluator() [6/6]
ADOGuy.Evaluator.Evaluator (EvaluatorItem item) inline
References ADOGuy.Evaluator.ConstructEvaluator().
Member Function Documentation
ConstructEvaluator() [1/2]
void ADOGuy.Evaluator.ConstructEvaluator (EvaluatorItem[] items) inline private
References ADOGuy.Evaluator._Compiled, ADOGuy.EvaluatorItem.Expression, ADOGuy.EvaluatorItem.Name, and ADOGuy.EvaluatorItem.ReturnType.
Referenced by ADOGuy.Evaluator.Evaluator().
EvaluateInt() [1/2]
int ADOGuy.Evaluator.EvaluateInt (string name) inline
References ADOGuy.Evaluator.Evaluate().
Referenced by ADOGuy.Program.Main(), and TestEvaluator.Test.Main().
EvaluateString() [1/2]
string ADOGuy.Evaluator.EvaluateString (string name) inline
References ADOGuy.Evaluator.Evaluate().
Referenced by ADOGuy.Program.Main(), and TestEvaluator.Test.Main().
EvaluateBool() [1/2]
bool ADOGuy.Evaluator.EvaluateBool (string name) inline
References ADOGuy.Evaluator.Evaluate().
Referenced by ADOGuy.Program.Main(), and TestEvaluator.Test.Main().
Evaluate() [1/2]
object ADOGuy.Evaluator.Evaluate (string name) inline
References ADOGuy.Evaluator._Compiled.
Referenced by ADOGuy.Evaluator.EvaluateBool(), ADOGuy.Evaluator.EvaluateInt(), ADOGuy.Evaluator.EvaluateString(), ADOGuy.Evaluator.EvaluateToBool(), ADOGuy.Evaluator.EvaluateToInteger(), ADOGuy.Evaluator.EvaluateToObject(), ADOGuy.Evaluator.EvaluateToString(), ADOGuy.Program.Main(), and TestEvaluator.Test.Main().
EvaluateToInteger() [1/2]
static int ADOGuy.Evaluator.EvaluateToInteger (string code) inline static
References ADOGuy.Evaluator.Evaluate(), ADOGuy.Evaluator.Evaluator(), and ADOGuy.Evaluator.staticMethodName.
Referenced by ADOGuy.Program.Main(), and TestEvaluator.Test.Main().
EvaluateToString() [1/2]
static string ADOGuy.Evaluator.EvaluateToString (string code) inline static
References ADOGuy.Evaluator.Evaluate(), ADOGuy.Evaluator.Evaluator(), and ADOGuy.Evaluator.staticMethodName.
Referenced by ADOGuy.Program.Main(), and TestEvaluator.Test.Main().
EvaluateToBool() [1/2]
static bool ADOGuy.Evaluator.EvaluateToBool (string code) inline static
References ADOGuy.Evaluator.Evaluate(), ADOGuy.Evaluator.Evaluator(), and ADOGuy.Evaluator.staticMethodName.
Referenced by ADOGuy.Program.Main(), and TestEvaluator.Test.Main().
EvaluateToObject() [1/2]
static object ADOGuy.Evaluator.EvaluateToObject (string code) inline static
References ADOGuy.Evaluator.Evaluate(), ADOGuy.Evaluator.Evaluator(), and ADOGuy.Evaluator.staticMethodName.
Referenced by ADOGuy.Program.Main(), and TestEvaluator.Test.Main().
ConstructEvaluator() [2/2]
void ADOGuy.Evaluator.ConstructEvaluator (EvaluatorItem[] items) inline private
References ADOGuy.Evaluator._Compiled, ADOGuy.EvaluatorItem.Expression, ADOGuy.EvaluatorItem.Name, and ADOGuy.EvaluatorItem.ReturnType.
EvaluateInt() [2/2]
int ADOGuy.Evaluator.EvaluateInt (string name) inline
References ADOGuy.Evaluator.Evaluate().
EvaluateString() [2/2]
string ADOGuy.Evaluator.EvaluateString (string name) inline
References ADOGuy.Evaluator.Evaluate().
EvaluateBool() [2/2]
bool ADOGuy.Evaluator.EvaluateBool (string name) inline
References ADOGuy.Evaluator.Evaluate().
Evaluate() [2/2]
object ADOGuy.Evaluator.Evaluate (string name) inline
References ADOGuy.Evaluator._Compiled.
EvaluateToInteger() [2/2]
static int ADOGuy.Evaluator.EvaluateToInteger (string code) inline static
References ADOGuy.Evaluator.Evaluator(), and ADOGuy.Evaluator.staticMethodName.
EvaluateToDouble()
static double ADOGuy.Evaluator.EvaluateToDouble (string code) inline static
References ADOGuy.Evaluator.Evaluator(), and ADOGuy.Evaluator.staticMethodName.
Referenced by ADOGuy.Program.Main().
EvaluateToString() [2/2]
static string ADOGuy.Evaluator.EvaluateToString (string code) inline static
References ADOGuy.Evaluator.Evaluator(), and ADOGuy.Evaluator.staticMethodName.
EvaluateToBool() [2/2]
static bool ADOGuy.Evaluator.EvaluateToBool (string code) inline static
References ADOGuy.Evaluator.Evaluator(), and ADOGuy.Evaluator.staticMethodName.
EvaluateToObject() [2/2]
static object ADOGuy.Evaluator.EvaluateToObject (string code) inline static
References ADOGuy.Evaluator.Evaluator(), and ADOGuy.Evaluator.staticMethodName.
Member Data Documentation
staticMethodName
const string ADOGuy.Evaluator.staticMethodName = "__foo" static private
Referenced by ADOGuy.Evaluator.EvaluateToBool(), ADOGuy.Evaluator.EvaluateToDouble(), ADOGuy.Evaluator.EvaluateToInteger(), ADOGuy.Evaluator.EvaluateToObject(), and ADOGuy.Evaluator.EvaluateToString().
_CompiledType
Type ADOGuy.Evaluator._CompiledType = null private
_Compiled
object ADOGuy.Evaluator._Compiled = null private
Referenced by ADOGuy.Evaluator.ConstructEvaluator(), and ADOGuy.Evaluator.Evaluate().
The documentation for this class was generated from the following file:
igtest/tmp_CSharpEvaluator/Backup/Evaluator.cs