Doc: IGLib EXTENDED: NUnit.Common.Guard Class Reference
NUnit.Common.Guard Class Reference
Class used to guard against unexpected argument values or operations by throwing an appropriate exception.
Static Public Member Functions
static void ArgumentNotNull (object value, string name)
Throws an exception if an argument is null
static void ArgumentNotNullOrEmpty (string value, string name)
Throws an exception if a string argument is null or empty
static void ArgumentInRange (bool condition, string message, string paramName)
Throws an ArgumentOutOfRangeException if the specified condition is not met.
static void ArgumentValid (bool condition, string message, string paramName)
Throws an ArgumentException if the specified condition is not met.
static void OperationValid (bool condition, string message)
Throws an InvalidOperationException if the specified condition is not met.
Detailed Description
Class used to guard against unexpected argument values or operations by throwing an appropriate exception.
Member Function Documentation
ArgumentNotNull()
static void NUnit.Common.Guard.ArgumentNotNull (object value, string name) inline static
Throws an exception if an argument is null
Parameters
value The value to be tested
name The name of the argument
Referenced by NUnit.Framework.Api.FrameworkController.CountTests(), NUnit.Engine.Services.ProjectService.ExpandProjectPackage(), NUnit.Framework.Api.FrameworkController.ExploreTests(), NUnit.Engine.Services.DomainManager.GetApplicationBase(), NUnit.Engine.Services.DomainManager.GetConfigFile(), NUnit.Framework.Api.FrameworkController.RunAsync(), and NUnit.Framework.Api.FrameworkController.RunTests().
ArgumentNotNullOrEmpty()
static void NUnit.Common.Guard.ArgumentNotNullOrEmpty (string value, string name) inline static
Throws an exception if a string argument is null or empty
Parameters
value The value to be tested
name The name of the argument
Referenced by NUnit.Engine.Services.DomainManager.GetConfigFile().
ArgumentInRange()
static void NUnit.Common.Guard.ArgumentInRange (bool condition, string message, string paramName) inline static
Throws an ArgumentOutOfRangeException if the specified condition is not met.
Parameters
condition The condition that must be met
message The exception message to be used
paramName The name of the argument
ArgumentValid()
static void NUnit.Common.Guard.ArgumentValid (bool condition, string message, string paramName) inline static
Throws an ArgumentException if the specified condition is not met.
Parameters
condition The condition that must be met
message The exception message to be used
paramName The name of the argument
Referenced by NUnit.Engine.Services.ProjectService.ExpandProjectPackage().
OperationValid()
static void NUnit.Common.Guard.OperationValid (bool condition, string message) inline static
Throws an InvalidOperationException if the specified condition is not met.
Parameters
condition The condition that must be met
message The exception message to be used
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/nunit/Guard.cs