Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DRSCL Class Reference
DotNumerics.LinearAlgebra.CSLapack.DRSCL Class Reference
– LAPACK auxiliary routine (version 3.0) – Univ. of Tennessee, Univ. of California Berkeley, NAG Ltd., Courant Institute, Argonne National Lab, and Rice University September 30, 1994
Public Member Functions
DRSCL (DLAMCH dlamch, DSCAL dscal, DLABAD dlabad)
DRSCL ()
void Run (int N, double SA, ref double[] SX, int offset_sx, int INCX)
Private Attributes
DLAMCH _dlamch
DSCAL _dscal
DLABAD _dlabad
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.0) – Univ. of Tennessee, Univ. of California Berkeley, NAG Ltd., Courant Institute, Argonne National Lab, and Rice University September 30, 1994
Purpose
DRSCL multiplies an n-element real vector x by the real scalar 1/a. This is done without overflow or underflow as long as the final result x/a does not overflow or underflow.
/summary>
Constructor & Destructor Documentation
DRSCL() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DRSCL.DRSCL (DLAMCH dlamch, DSCAL dscal, DLABAD dlabad) inline
DRSCL() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DRSCL.DRSCL () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DRSCL.Run (int N, double SA, ref double[] SX, int offset_sx, int INCX) inline
Purpose
DRSCL multiplies an n-element real vector x by the real scalar 1/a. This is done without overflow or underflow as long as the final result x/a does not overflow or underflow.
/summary>
Parameters
N (input) INTEGER The number of components of the vector x. /param>
Parameters
SA (input) DOUBLE PRECISION The scalar a which is used to divide each component of x. SA must be .GE. 0, or the subroutine will divide by zero. /param>
Parameters
SX (input/output) DOUBLE PRECISION array, dimension (1+(N-1)*abs(INCX)) The n-element vector x. /param>
Parameters
INCX (input) INTEGER The increment between successive values of the vector SX. .GT. 0: SX(1) = X(1) and SX(1+(i-1)*INCX) = x(i), 1.LT. i.LE. n /param>
References DotNumerics.LinearAlgebra.CSLapack.DRSCL.ONE, DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLABAD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), and DotNumerics.LinearAlgebra.CSLapack.DRSCL.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTRCON.Run().
Member Data Documentation
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DRSCL._dlamch private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DRSCL._dscal private
_dlabad
DLABAD DotNumerics.LinearAlgebra.CSLapack.DRSCL._dlabad private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DRSCL.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DRSCL.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DRSCL.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DRSCL.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/drscl.cs