Doc: IGLib EXTENDED: XMLTree.Form1 Class Reference
XMLTree.Form1 Class Reference
Summary description for Form1.
Public Member Functions
Form1 ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Types
enum VIEW { VIEW.TREE_VIEW =0 }
Private Member Functions
delegate void MyDelegate ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void Form1_Load (object sender, System.EventArgs e)
void menuItem3_Click (object sender, System.EventArgs e)
void openFileDialog1_FileOk (object sender, System.ComponentModel.CancelEventArgs e)
void PopulateList ()
void PopulateTree ()
void ParseFile ()
void treeView1_Click (object sender, System.EventArgs e)
void treeView1_AfterSelect (object sender, System.Windows.Forms.TreeViewEventArgs e)
void menuItem2_Click (object sender, System.EventArgs e)
void AppExit ()
void LoadFileIntoListBox ()
void MoveToLine (int ln)
void AssociateTag (TreeNode t, int l)
void menuItem5_Click (object sender, System.EventArgs e)
void ShowAboutBox ()
void EnableDisableControls ()
void toolBar1_ButtonClick (object sender, System.Windows.Forms.ToolBarButtonClickEventArgs e)
void TExpandAll ()
void TE ()
void TCollapseAll ()
void Clear ()
void menuItem1_DrawItem (object sender, System.Windows.Forms.DrawItemEventArgs e)
void menuItem1_MeasureItem (object sender, System.Windows.Forms.MeasureItemEventArgs e)
void menuItem3_MeasureItem (object sender, System.Windows.Forms.MeasureItemEventArgs e)
void menuItem3_DrawItem (object sender, System.Windows.Forms.DrawItemEventArgs e)
void Form1_Resize (object sender, System.EventArgs e)
Static Private Member Functions
static void Main ()
The main entry point for the application.
Private Attributes
System.Windows.Forms.MainMenu mainMenu1
System.Windows.Forms.MenuItem menuItem1
System.Windows.Forms.MenuItem menuItem2
System.Windows.Forms.MenuItem menuItem3
System.Windows.Forms.OpenFileDialog openFileDialog1
IContainer components
string XMLInputFile = null
string FileSize = ""
string WorkingDir = Directory.GetCurrentDirectory()
string OrigFormTitle = ""
bool bFileLoaded = false
int CurrentView = (int)VIEW.TREE_VIEW
Object NodeTag = null
Thread t = null
TreeNode RootNode = null
Point ClickedPoint = new Point(0,0)
ArrayList TreeNodeArray = new ArrayList()
ImageList tr_il = new ImageList()
ImageList tb_il = new ImageList()
Bitmap img_fileopen
Bitmap img_exit
Bitmap img_collapse
Bitmap img_expand
Bitmap img_about
System.Windows.Forms.MenuItem menuItem4
System.Windows.Forms.MenuItem menuItem5
System.Windows.Forms.ToolBar toolBar1
System.Windows.Forms.TreeView treeView1
System.Windows.Forms.ToolBarButton Open
System.Windows.Forms.ToolBarButton Exit
System.Windows.Forms.ToolBarButton About
System.Windows.Forms.ToolBarButton SEPARATOR1
System.Windows.Forms.ToolBarButton ExpandAll
System.Windows.Forms.ToolBarButton CollapseAll
System.Windows.Forms.ToolBarButton Stop
System.Windows.Forms.ToolBarButton SEPARATOR2
System.Windows.Forms.ListBox listBox1
System.Windows.Forms.Splitter splitter1
System.Windows.Forms.ToolBarButton SEPARATOR3
Detailed Description
Summary description for Form1.
Member Enumeration Documentation
VIEW
enum XMLTree.Form1.VIEW strong private
Enumerator
TREE_VIEW
Constructor & Destructor Documentation
Form1()
XMLTree.Form1.Form1 () inline
References XMLTree.Form1.InitializeComponent().
Referenced by XMLTree.Form1.Main().
Member Function Documentation
MyDelegate()
delegate void XMLTree.Form1.MyDelegate () private
Referenced by XMLTree.Form1.PopulateTree().
Dispose()
override void XMLTree.Form1.Dispose (bool disposing) inline protected
Clean up any resources being used.
References XMLTree.Form1.components.
InitializeComponent()
void XMLTree.Form1.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by XMLTree.Form1.Form1().
Main()
static void XMLTree.Form1.Main () inline static private
The main entry point for the application.
References XMLTree.Form1.Form1().
Form1_Load()
void XMLTree.Form1.Form1_Load (object sender, System.EventArgs e) inline private
References XMLTree.Form1.img_about, XMLTree.Form1.img_collapse, XMLTree.Form1.img_exit, XMLTree.Form1.img_expand, XMLTree.Form1.img_fileopen, XMLTree.Form1.OrigFormTitle, XMLTree.Form1.tb_il, XMLTree.Form1.toolBar1, XMLTree.Form1.tr_il, XMLTree.Form1.treeView1, and XMLTree.Form1.WorkingDir.
menuItem3_Click()
void XMLTree.Form1.menuItem3_Click (object sender, System.EventArgs e) inline private
References XMLTree.Form1.openFileDialog1.
openFileDialog1_FileOk()
void XMLTree.Form1.openFileDialog1_FileOk (object sender, System.ComponentModel.CancelEventArgs e) inline private
References XMLTree.Form1.bFileLoaded, XMLTree.Form1.EnableDisableControls(), XMLTree.Form1.FileSize, XMLTree.Form1.listBox1, XMLTree.Form1.openFileDialog1, XMLTree.Form1.OrigFormTitle, XMLTree.Form1.PopulateList(), XMLTree.Form1.PopulateTree(), XMLTree.Form1.t, XMLTree.Form1.TreeNodeArray, XMLTree.Form1.treeView1, and XMLTree.Form1.XMLInputFile.
PopulateList()
void XMLTree.Form1.PopulateList () inline private
References XMLTree.Form1.LoadFileIntoListBox().
Referenced by XMLTree.Form1.openFileDialog1_FileOk().
PopulateTree()
void XMLTree.Form1.PopulateTree () inline private
References XMLTree.Form1.MyDelegate(), XMLTree.Form1.ParseFile(), and XMLTree.Form1.treeView1.
Referenced by XMLTree.Form1.openFileDialog1_FileOk().
ParseFile()
void XMLTree.Form1.ParseFile () inline private
References XMLTree.Form1.AssociateTag(), XMLTree.Form1.RootNode, XMLTree.Form1.treeView1, and XMLTree.Form1.XMLInputFile.
Referenced by XMLTree.Form1.PopulateTree().
treeView1_Click()
void XMLTree.Form1.treeView1_Click (object sender, System.EventArgs e) inline private
treeView1_AfterSelect()
void XMLTree.Form1.treeView1_AfterSelect (object sender, System.Windows.Forms.TreeViewEventArgs e) inline private
References XMLTree.Form1.bFileLoaded, and XMLTree.Form1.MoveToLine().
menuItem2_Click()
void XMLTree.Form1.menuItem2_Click (object sender, System.EventArgs e) inline private
References XMLTree.Form1.AppExit().
AppExit()
void XMLTree.Form1.AppExit () inline private
Referenced by XMLTree.Form1.menuItem2_Click(), and XMLTree.Form1.toolBar1_ButtonClick().
LoadFileIntoListBox()
void XMLTree.Form1.LoadFileIntoListBox () inline private
References XMLTree.Form1.bFileLoaded, XMLTree.Form1.listBox1, and XMLTree.Form1.XMLInputFile.
Referenced by XMLTree.Form1.PopulateList().
MoveToLine()
void XMLTree.Form1.MoveToLine (int ln) inline private
References XMLTree.Form1.listBox1.
Referenced by XMLTree.Form1.treeView1_AfterSelect().
AssociateTag()
void XMLTree.Form1.AssociateTag (TreeNode t, int l) inline private
References XMLTree.Form1.NodeTag, and XMLTree.Form1.t.
Referenced by XMLTree.Form1.ParseFile().
menuItem5_Click()
void XMLTree.Form1.menuItem5_Click (object sender, System.EventArgs e) inline private
References XMLTree.Form1.ShowAboutBox().
ShowAboutBox()
void XMLTree.Form1.ShowAboutBox () inline private
References XMLTree.Form1.About.
Referenced by XMLTree.Form1.menuItem5_Click(), and XMLTree.Form1.toolBar1_ButtonClick().
EnableDisableControls()
void XMLTree.Form1.EnableDisableControls () inline private
References XMLTree.Form1.CollapseAll, XMLTree.Form1.CurrentView, XMLTree.Form1.ExpandAll, XMLTree.Form1.Stop, and XMLTree.Form1.treeView1.
Referenced by XMLTree.Form1.openFileDialog1_FileOk(), and XMLTree.Form1.toolBar1_ButtonClick().
toolBar1_ButtonClick()
void XMLTree.Form1.toolBar1_ButtonClick (object sender, System.Windows.Forms.ToolBarButtonClickEventArgs e) inline private
References XMLTree.Form1.AppExit(), XMLTree.Form1.CurrentView, XMLTree.Form1.EnableDisableControls(), XMLTree.Form1.openFileDialog1, XMLTree.Form1.ShowAboutBox(), XMLTree.Form1.t, XMLTree.Form1.TCollapseAll(), XMLTree.Form1.TExpandAll(), and XMLTree.Form1.toolBar1.
TExpandAll()
void XMLTree.Form1.TExpandAll () inline private
References XMLTree.Form1.t, and XMLTree.Form1.TE().
Referenced by XMLTree.Form1.toolBar1_ButtonClick().
TE()
void XMLTree.Form1.TE () inline private
References XMLTree.Form1.treeView1.
Referenced by XMLTree.Form1.TExpandAll().
TCollapseAll()
void XMLTree.Form1.TCollapseAll () inline private
References XMLTree.Form1.treeView1.
Referenced by XMLTree.Form1.toolBar1_ButtonClick().
Clear()
void XMLTree.Form1.Clear () inline private
References XMLTree.Form1.TreeNodeArray.
menuItem1_DrawItem()
void XMLTree.Form1.menuItem1_DrawItem (object sender, System.Windows.Forms.DrawItemEventArgs e) inline private
menuItem1_MeasureItem()
void XMLTree.Form1.menuItem1_MeasureItem (object sender, System.Windows.Forms.MeasureItemEventArgs e) inline private
menuItem3_MeasureItem()
void XMLTree.Form1.menuItem3_MeasureItem (object sender, System.Windows.Forms.MeasureItemEventArgs e) inline private
menuItem3_DrawItem()
void XMLTree.Form1.menuItem3_DrawItem (object sender, System.Windows.Forms.DrawItemEventArgs e) inline private
References XMLTree.Form1.CurrentView, XMLTree.Form1.img_about, XMLTree.Form1.img_collapse, XMLTree.Form1.img_exit, XMLTree.Form1.img_expand, and XMLTree.Form1.img_fileopen.
Form1_Resize()
void XMLTree.Form1.Form1_Resize (object sender, System.EventArgs e) inline private
Member Data Documentation
mainMenu1
System.Windows.Forms.MainMenu XMLTree.Form1.mainMenu1 private
menuItem1
System.Windows.Forms.MenuItem XMLTree.Form1.menuItem1 private
menuItem2
System.Windows.Forms.MenuItem XMLTree.Form1.menuItem2 private
menuItem3
System.Windows.Forms.MenuItem XMLTree.Form1.menuItem3 private
openFileDialog1
System.Windows.Forms.OpenFileDialog XMLTree.Form1.openFileDialog1 private
Referenced by XMLTree.Form1.menuItem3_Click(), XMLTree.Form1.openFileDialog1_FileOk(), and XMLTree.Form1.toolBar1_ButtonClick().
components
IContainer XMLTree.Form1.components private
Referenced by XMLTree.Form1.Dispose().
XMLInputFile
string XMLTree.Form1.XMLInputFile = null private
Referenced by XMLTree.Form1.LoadFileIntoListBox(), XMLTree.Form1.openFileDialog1_FileOk(), and XMLTree.Form1.ParseFile().
FileSize
string XMLTree.Form1.FileSize = "" private
Referenced by XMLTree.Form1.openFileDialog1_FileOk().
WorkingDir
string XMLTree.Form1.WorkingDir = Directory.GetCurrentDirectory() private
Referenced by XMLTree.Form1.Form1_Load().
OrigFormTitle
string XMLTree.Form1.OrigFormTitle = "" private
Referenced by XMLTree.Form1.Form1_Load(), and XMLTree.Form1.openFileDialog1_FileOk().
bFileLoaded
bool XMLTree.Form1.bFileLoaded = false private
Referenced by XMLTree.Form1.LoadFileIntoListBox(), XMLTree.Form1.openFileDialog1_FileOk(), and XMLTree.Form1.treeView1_AfterSelect().
CurrentView
int XMLTree.Form1.CurrentView = (int)VIEW.TREE_VIEW private
Referenced by XMLTree.Form1.EnableDisableControls(), XMLTree.Form1.menuItem3_DrawItem(), and XMLTree.Form1.toolBar1_ButtonClick().
NodeTag
Object XMLTree.Form1.NodeTag = null private
Referenced by XMLTree.Form1.AssociateTag().
t
Thread XMLTree.Form1.t = null private
Referenced by XMLTree.Form1.AssociateTag(), XMLTree.Form1.openFileDialog1_FileOk(), XMLTree.Form1.TExpandAll(), and XMLTree.Form1.toolBar1_ButtonClick().
RootNode
TreeNode XMLTree.Form1.RootNode = null private
Referenced by XMLTree.Form1.ParseFile().
ClickedPoint
Point XMLTree.Form1.ClickedPoint = new Point(0,0) private
TreeNodeArray
ArrayList XMLTree.Form1.TreeNodeArray = new ArrayList() private
Referenced by XMLTree.Form1.Clear(), and XMLTree.Form1.openFileDialog1_FileOk().
tr_il
ImageList XMLTree.Form1.tr_il = new ImageList() private
Referenced by XMLTree.Form1.Form1_Load().
tb_il
ImageList XMLTree.Form1.tb_il = new ImageList() private
Referenced by XMLTree.Form1.Form1_Load().
img_fileopen
Bitmap XMLTree.Form1.img_fileopen private
Referenced by XMLTree.Form1.Form1_Load(), and XMLTree.Form1.menuItem3_DrawItem().
img_exit
Bitmap XMLTree.Form1.img_exit private
Referenced by XMLTree.Form1.Form1_Load(), and XMLTree.Form1.menuItem3_DrawItem().
img_collapse
Bitmap XMLTree.Form1.img_collapse private
Referenced by XMLTree.Form1.Form1_Load(), and XMLTree.Form1.menuItem3_DrawItem().
img_expand
Bitmap XMLTree.Form1.img_expand private
Referenced by XMLTree.Form1.Form1_Load(), and XMLTree.Form1.menuItem3_DrawItem().
img_about
Bitmap XMLTree.Form1.img_about private
Referenced by XMLTree.Form1.Form1_Load(), and XMLTree.Form1.menuItem3_DrawItem().
menuItem4
System.Windows.Forms.MenuItem XMLTree.Form1.menuItem4 private
menuItem5
System.Windows.Forms.MenuItem XMLTree.Form1.menuItem5 private
toolBar1
System.Windows.Forms.ToolBar XMLTree.Form1.toolBar1 private
Referenced by XMLTree.Form1.Form1_Load(), and XMLTree.Form1.toolBar1_ButtonClick().
treeView1
System.Windows.Forms.TreeView XMLTree.Form1.treeView1 private
Referenced by XMLTree.Form1.EnableDisableControls(), XMLTree.Form1.Form1_Load(), XMLTree.Form1.openFileDialog1_FileOk(), XMLTree.Form1.ParseFile(), XMLTree.Form1.PopulateTree(), XMLTree.Form1.TCollapseAll(), and XMLTree.Form1.TE().
Open
System.Windows.Forms.ToolBarButton XMLTree.Form1.Open private
Exit
System.Windows.Forms.ToolBarButton XMLTree.Form1.Exit private
About
System.Windows.Forms.ToolBarButton XMLTree.Form1.About private
Referenced by XMLTree.Form1.ShowAboutBox().
SEPARATOR1
System.Windows.Forms.ToolBarButton XMLTree.Form1.SEPARATOR1 private
ExpandAll
System.Windows.Forms.ToolBarButton XMLTree.Form1.ExpandAll private
Referenced by XMLTree.Form1.EnableDisableControls().
CollapseAll
System.Windows.Forms.ToolBarButton XMLTree.Form1.CollapseAll private
Referenced by XMLTree.Form1.EnableDisableControls().
Stop
System.Windows.Forms.ToolBarButton XMLTree.Form1.Stop private
Referenced by XMLTree.Form1.EnableDisableControls().
SEPARATOR2
System.Windows.Forms.ToolBarButton XMLTree.Form1.SEPARATOR2 private
listBox1
System.Windows.Forms.ListBox XMLTree.Form1.listBox1 private
Referenced by XMLTree.Form1.LoadFileIntoListBox(), XMLTree.Form1.MoveToLine(), and XMLTree.Form1.openFileDialog1_FileOk().
splitter1
System.Windows.Forms.Splitter XMLTree.Form1.splitter1 private
SEPARATOR3
System.Windows.Forms.ToolBarButton XMLTree.Form1.SEPARATOR3 private
The documentation for this class was generated from the following file:
igtest/iglib_sandbox/copy_to_delete/1/Form1.cs