Doc: IGLib EXTENDED: NUnit.Framework.Assertions.ArrayEqualsFixture Class Reference
NUnit.Framework.Assertions.ArrayEqualsFixture Class Reference
Summary description for ArrayEqualTests.
Public Member Functions
void ArrayIsEqualToItself ()
void ArraysOfString ()
void ArraysOfInt ()
void ArraysOfDouble ()
void ArraysOfDecimal ()
void ArrayOfIntAndArrayOfDouble ()
void ArraysDeclaredAsDifferentTypes ()
void ArraysOfMixedTypes ()
void DoubleDimensionedArrays ()
void TripleDimensionedArrays ()
void FiveDimensionedArrays ()
void ArraysOfArrays ()
void JaggedArrays ()
void ArraysPassedAsObjects ()
void ArrayAndCollection ()
void ArraysWithDifferentRanksComparedAsCollection ()
void ArraysWithDifferentDimensionsMatchedAsCollection ()
void ArraySegmentAndArray ()
void EmptyArraySegmentAndArray ()
void ArrayAndArraySegment ()
void ArrayAndEmptyArraySegment ()
void TwoArraySegments ()
void TwoEmptyArraySegments ()
Public Member Functions inherited from NUnit.Framework.AssertionHelper
void Expect (bool condition, string message, params object[] args)
Asserts that a condition is true. If the condition is false the method throws an AssertionException. Works Identically to Assert.That(bool, string, object[]).
void Expect (bool condition)
Asserts that a condition is true. If the condition is false the method throws an AssertionException. Works Identically to Assert.That(bool).
void Expect< TActual > (ActualValueDelegate< TActual > del, IResolveConstraint expr)
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure.
void Expect< TActual > (ActualValueDelegate< TActual > del, IResolveConstraint expr, string message, params object[] args)
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure.
void Expect (TestDelegate code, IResolveConstraint constraint)
Asserts that the code represented by a delegate throws an exception that satisfies the constraint provided.
ListMapper Map (ICollection original)
Returns a ListMapper based on a collection.
Public Member Functions inherited from NUnit.Framework.Constraints.ConstraintFactory
ResolvableConstraintExpression Property (string name)
Returns a new PropertyConstraintExpression, which will either test for the existence of the named property on the object being tested or apply any following constraint to that property.
ResolvableConstraintExpression Attribute (Type expectedType)
Returns a new AttributeConstraint checking for the presence of a particular attribute on an object.
ResolvableConstraintExpression Attribute< TExpected > ()
Returns a new AttributeConstraint checking for the presence of a particular attribute on an object.
EqualConstraint EqualTo (object expected)
Returns a constraint that tests two items for equality
SameAsConstraint SameAs (object expected)
Returns a constraint that tests that two references are the same object
GreaterThanConstraint GreaterThan (object expected)
Returns a constraint that tests whether the actual value is greater than the supplied argument
GreaterThanOrEqualConstraint GreaterThanOrEqualTo (object expected)
Returns a constraint that tests whether the actual value is greater than or equal to the supplied argument
GreaterThanOrEqualConstraint AtLeast (object expected)
Returns a constraint that tests whether the actual value is greater than or equal to the supplied argument
LessThanConstraint LessThan (object expected)
Returns a constraint that tests whether the actual value is less than the supplied argument
LessThanOrEqualConstraint LessThanOrEqualTo (object expected)
Returns a constraint that tests whether the actual value is less than or equal to the supplied argument
LessThanOrEqualConstraint AtMost (object expected)
Returns a constraint that tests whether the actual value is less than or equal to the supplied argument
ExactTypeConstraint TypeOf (Type expectedType)
Returns a constraint that tests whether the actual value is of the exact type supplied as an argument.
ExactTypeConstraint TypeOf< TExpected > ()
Returns a constraint that tests whether the actual value is of the exact type supplied as an argument.
InstanceOfTypeConstraint InstanceOf (Type expectedType)
Returns a constraint that tests whether the actual value is of the type supplied as an argument or a derived type.
InstanceOfTypeConstraint InstanceOf< TExpected > ()
Returns a constraint that tests whether the actual value is of the type supplied as an argument or a derived type.
AssignableFromConstraint AssignableFrom (Type expectedType)
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
AssignableFromConstraint AssignableFrom< TExpected > ()
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
AssignableToConstraint AssignableTo (Type expectedType)
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
AssignableToConstraint AssignableTo< TExpected > ()
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
CollectionEquivalentConstraint EquivalentTo (IEnumerable expected)
Returns a constraint that tests whether the actual value is a collection containing the same elements as the collection supplied as an argument.
CollectionSubsetConstraint SubsetOf (IEnumerable expected)
Returns a constraint that tests whether the actual value is a subset of the collection supplied as an argument.
CollectionSupersetConstraint SupersetOf (IEnumerable expected)
Returns a constraint that tests whether the actual value is a superset of the collection supplied as an argument.
CollectionContainsConstraint Member (object expected)
Returns a new CollectionContainsConstraint checking for the presence of a particular object in the collection.
CollectionContainsConstraint Contains (object expected)
Returns a new CollectionContainsConstraint checking for the presence of a particular object in the collection.
ContainsConstraint Contains (string expected)
Returns a new ContainsConstraint. This constraint will, in turn, make use of the appropriate second-level constraint, depending on the type of the actual argument. This overload is only used if the item sought is a string, since any other type implies that we are looking for a collection member.
SubstringConstraint StringContaining (string expected)
Returns a constraint that succeeds if the actual value contains the substring supplied as an argument.
SubstringConstraint ContainsSubstring (string expected)
Returns a constraint that succeeds if the actual value contains the substring supplied as an argument.
SubstringConstraint DoesNotContain (string expected)
Returns a constraint that fails if the actual value contains the substring supplied as an argument.
StartsWithConstraint StartWith (string expected)
Returns a constraint that succeeds if the actual value starts with the substring supplied as an argument.
StartsWithConstraint StartsWith (string expected)
Returns a constraint that succeeds if the actual value starts with the substring supplied as an argument.
StartsWithConstraint StringStarting (string expected)
Returns a constraint that succeeds if the actual value starts with the substring supplied as an argument.
StartsWithConstraint DoesNotStartWith (string expected)
Returns a constraint that fails if the actual value starts with the substring supplied as an argument.
EndsWithConstraint EndWith (string expected)
Returns a constraint that succeeds if the actual value ends with the substring supplied as an argument.
EndsWithConstraint EndsWith (string expected)
Returns a constraint that succeeds if the actual value ends with the substring supplied as an argument.
EndsWithConstraint StringEnding (string expected)
Returns a constraint that succeeds if the actual value ends with the substring supplied as an argument.
EndsWithConstraint DoesNotEndWith (string expected)
Returns a constraint that fails if the actual value ends with the substring supplied as an argument.
RegexConstraint Match (string pattern)
Returns a constraint that succeeds if the actual value matches the regular expression supplied as an argument.
RegexConstraint Matches (string pattern)
Returns a constraint that succeeds if the actual value matches the regular expression supplied as an argument.
RegexConstraint StringMatching (string pattern)
Returns a constraint that succeeds if the actual value matches the regular expression supplied as an argument.
RegexConstraint DoesNotMatch (string pattern)
Returns a constraint that fails if the actual value matches the pattern supplied as an argument.
SamePathConstraint SamePath (string expected)
Returns a constraint that tests whether the path provided is the same as an expected path after canonicalization.
SubPathConstraint SubPathOf (string expected)
Returns a constraint that tests whether the path provided is a subpath of the expected path after canonicalization.
SamePathOrUnderConstraint SamePathOrUnder (string expected)
Returns a constraint that tests whether the path provided is the same path or under an expected path after canonicalization.
RangeConstraint InRange (IComparable from, IComparable to)
Returns a constraint that tests whether the actual value falls within a specified range.
Static Private Attributes
static readonly bool ArraySegmentImplementsIEnumerable = new ArraySegment<int>() is IEnumerable
static int[] underlyingArray = new int[] { 1, 2, 3, 4, 5 }
Additional Inherited Members
Static Public Member Functions inherited from NUnit.Framework.AssertionHelper
static void Expect< TActual > (TActual actual, IResolveConstraint expression)
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure.
static void Expect< TActual > (TActual actual, IResolveConstraint expression, string message, params object[] args)
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure.
Static Public Member Functions inherited from NUnit.Framework.Constraints.ConstraintFactory
static ConstraintExpression Exactly (int expectedCount)
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding only if a specified number of them succeed.
Properties inherited from NUnit.Framework.Constraints.ConstraintFactory
ConstraintExpression Not [get]
Returns a ConstraintExpression that negates any following constraint.
ConstraintExpression No [get]
Returns a ConstraintExpression that negates any following constraint.
ConstraintExpression All [get]
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if all of them succeed.
ConstraintExpression Some [get]
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if at least one of them succeeds.
ConstraintExpression None [get]
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if all of them fail.
ResolvableConstraintExpression Length [get]
Returns a new ConstraintExpression, which will apply the following constraint to the Length property of the object being tested.
ResolvableConstraintExpression Count [get]
Returns a new ConstraintExpression, which will apply the following constraint to the Count property of the object being tested.
ResolvableConstraintExpression Message [get]
Returns a new ConstraintExpression, which will apply the following constraint to the Message property of the object being tested.
ResolvableConstraintExpression InnerException [get]
Returns a new ConstraintExpression, which will apply the following constraint to the InnerException property of the object being tested.
NullConstraint Null [get]
Returns a constraint that tests for null
TrueConstraint True [get]
Returns a constraint that tests for True
FalseConstraint False [get]
Returns a constraint that tests for False
GreaterThanConstraint Positive [get]
Returns a constraint that tests for a positive value
LessThanConstraint Negative [get]
Returns a constraint that tests for a negative value
NaNConstraint NaN [get]
Returns a constraint that tests for NaN
EmptyConstraint Empty [get]
Returns a constraint that tests for empty
UniqueItemsConstraint Unique [get]
Returns a constraint that tests whether a collection contains all unique items.
BinarySerializableConstraint BinarySerializable [get]
Returns a constraint that tests whether an object graph is serializable in binary format.
XmlSerializableConstraint XmlSerializable [get]
Returns a constraint that tests whether an object graph is serializable in xml format.
CollectionOrderedConstraint Ordered [get]
Returns a constraint that tests whether a collection is ordered
Detailed Description
Summary description for ArrayEqualTests.
Member Function Documentation
ArrayIsEqualToItself()
void NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayIsEqualToItself () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.ConstraintFactory.EqualTo(), NUnit.Framework.AssertionHelper.Expect(), NUnit.Framework.Is.SameAs(), and NUnit.Framework.Assert.That().
ArraysOfString()
void NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfString () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.ConstraintFactory.EqualTo(), NUnit.Framework.AssertionHelper.Expect(), and NUnit.Framework.Assert.IsFalse().
ArraysOfInt()
void NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfInt () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.ConstraintFactory.EqualTo(), and NUnit.Framework.AssertionHelper.Expect().
ArraysOfDouble()
void NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfDouble () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.ConstraintFactory.EqualTo(), and NUnit.Framework.AssertionHelper.Expect().
ArraysOfDecimal()
void NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfDecimal () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.ConstraintFactory.EqualTo(), and NUnit.Framework.AssertionHelper.Expect().
ArrayOfIntAndArrayOfDouble()
void NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayOfIntAndArrayOfDouble () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.ConstraintFactory.EqualTo(), and NUnit.Framework.AssertionHelper.Expect().
ArraysDeclaredAsDifferentTypes()
void NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysDeclaredAsDifferentTypes () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.ConstraintFactory.EqualTo(), and NUnit.Framework.AssertionHelper.Expect().
ArraysOfMixedTypes()
void NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfMixedTypes () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.ConstraintFactory.EqualTo(), and NUnit.Framework.AssertionHelper.Expect().
DoubleDimensionedArrays()
void NUnit.Framework.Assertions.ArrayEqualsFixture.DoubleDimensionedArrays () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.ConstraintFactory.EqualTo(), and NUnit.Framework.AssertionHelper.Expect().
TripleDimensionedArrays()
void NUnit.Framework.Assertions.ArrayEqualsFixture.TripleDimensionedArrays () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.ConstraintFactory.EqualTo(), and NUnit.Framework.AssertionHelper.Expect().
FiveDimensionedArrays()
void NUnit.Framework.Assertions.ArrayEqualsFixture.FiveDimensionedArrays () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.ConstraintFactory.EqualTo(), and NUnit.Framework.AssertionHelper.Expect().
ArraysOfArrays()
void NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfArrays () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.ConstraintFactory.EqualTo(), and NUnit.Framework.AssertionHelper.Expect().
JaggedArrays()
void NUnit.Framework.Assertions.ArrayEqualsFixture.JaggedArrays () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.ConstraintFactory.EqualTo(), and NUnit.Framework.AssertionHelper.Expect().
ArraysPassedAsObjects()
void NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysPassedAsObjects () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.ConstraintFactory.EqualTo(), and NUnit.Framework.AssertionHelper.Expect().
ArrayAndCollection()
void NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayAndCollection () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Constraints.ConstraintFactory.EqualTo(), and NUnit.Framework.AssertionHelper.Expect().
ArraysWithDifferentRanksComparedAsCollection()
void NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysWithDifferentRanksComparedAsCollection () inline
References NUnit.Framework.Assert.AreNotEqual(), NUnit.Framework.Constraints.ConstraintFactory.EqualTo(), NUnit.Framework.Constraints.ConstraintExpression.EqualTo(), NUnit.Framework.AssertionHelper.Expect(), and NUnit.Framework.Constraints.ConstraintFactory.Not.
ArraysWithDifferentDimensionsMatchedAsCollection()
void NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysWithDifferentDimensionsMatchedAsCollection () inline
References NUnit.Framework.Assert.AreNotEqual(), NUnit.Framework.Constraints.ConstraintFactory.EqualTo(), NUnit.Framework.Constraints.ConstraintExpression.EqualTo(), NUnit.Framework.AssertionHelper.Expect(), and NUnit.Framework.Constraints.ConstraintFactory.Not.
ArraySegmentAndArray()
void NUnit.Framework.Assertions.ArrayEqualsFixture.ArraySegmentAndArray () inline
References NUnit.Framework.Assertions.ArrayEqualsFixture.ArraySegmentImplementsIEnumerable, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), NUnit.Framework.Assume.That(), and NUnit.Framework.Assertions.ArrayEqualsFixture.underlyingArray.
EmptyArraySegmentAndArray()
void NUnit.Framework.Assertions.ArrayEqualsFixture.EmptyArraySegmentAndArray () inline
References NUnit.Framework.Assertions.ArrayEqualsFixture.ArraySegmentImplementsIEnumerable, NUnit.Framework.Is.Not, NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
ArrayAndArraySegment()
void NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayAndArraySegment () inline
References NUnit.Framework.Assertions.ArrayEqualsFixture.ArraySegmentImplementsIEnumerable, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), NUnit.Framework.Assume.That(), and NUnit.Framework.Assertions.ArrayEqualsFixture.underlyingArray.
ArrayAndEmptyArraySegment()
void NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayAndEmptyArraySegment () inline
References NUnit.Framework.Assertions.ArrayEqualsFixture.ArraySegmentImplementsIEnumerable, NUnit.Framework.Is.Not, NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
TwoArraySegments()
void NUnit.Framework.Assertions.ArrayEqualsFixture.TwoArraySegments () inline
References NUnit.Framework.Assertions.ArrayEqualsFixture.ArraySegmentImplementsIEnumerable, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), NUnit.Framework.Assume.That(), and NUnit.Framework.Assertions.ArrayEqualsFixture.underlyingArray.
TwoEmptyArraySegments()
void NUnit.Framework.Assertions.ArrayEqualsFixture.TwoEmptyArraySegments () inline
References NUnit.Framework.Assertions.ArrayEqualsFixture.ArraySegmentImplementsIEnumerable, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
Member Data Documentation
ArraySegmentImplementsIEnumerable
readonly bool NUnit.Framework.Assertions.ArrayEqualsFixture.ArraySegmentImplementsIEnumerable = new ArraySegment<int>() is IEnumerable static private
Referenced by NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayAndArraySegment(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayAndEmptyArraySegment(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraySegmentAndArray(), NUnit.Framework.Assertions.ArrayEqualsFixture.EmptyArraySegmentAndArray(), NUnit.Framework.Assertions.ArrayEqualsFixture.TwoArraySegments(), and NUnit.Framework.Assertions.ArrayEqualsFixture.TwoEmptyArraySegments().
underlyingArray
int [] NUnit.Framework.Assertions.ArrayEqualsFixture.underlyingArray = new int[] { 1, 2, 3, 4, 5 } static private
Referenced by NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayAndArraySegment(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraySegmentAndArray(), and NUnit.Framework.Assertions.ArrayEqualsFixture.TwoArraySegments().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/ArrayEqualsFixture.cs