Doc: IGLib EXTENDED: NUnitLite.Tests.TextUITests Class Reference
NUnitLite.Tests.TextUITests Class Reference
Public Member Functions
void CreateResult ()
void CreateTextUI ()
void DisplayWarning ()
void DisplayError ()
void DisplayErrors ()
void DisplayHeader ()
void DisplayTestFiles ()
void DisplayRuntimeEnvironment ()
void TestFinished_NoOutput ()
void TestFinished_WithOutput ()
void DisplayHelp ()
void DisplayRequestedOptions ()
void ReportSequenceTest ()
void TestsNotRunTest ()
void SummaryReportTest ()
void ErrorsAndFailuresReportTest ()
Properties
string Report [get]
Private Member Functions
void MyFakeMethod ()
IList< string > GetReportLines ()
Private Attributes
TextUI _textUI
StringBuilder _reportBuilder
TestResult _result
Static Private Attributes
static readonly string NL = NUnit.Env.NewLine
static readonly string[] REPORT_SEQUENCE
Member Function Documentation
CreateResult()
void NUnitLite.Tests.TextUITests.CreateResult () inline
References NUnitLite.Tests.TextUITests._result, NUnit.Framework.Internal.TestResult.Duration, NUnit.Framework.Internal.TestResult.EndTime, NUnit.Framework.Assert.NotNull(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), and NUnit.Framework.Internal.TestResult.StartTime.
CreateTextUI()
void NUnitLite.Tests.TextUITests.CreateTextUI () inline
References NUnitLite.Tests.TextUITests._reportBuilder, and NUnitLite.Tests.TextUITests._textUI.
DisplayWarning()
void NUnitLite.Tests.TextUITests.DisplayWarning () inline
References NUnitLite.Tests.TextUITests._textUI, NUnitLite.TextUI.DisplayWarning(), NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.TextUITests.NL, NUnitLite.Tests.TextUITests.Report, and NUnit.Framework.Assert.That().
DisplayError()
void NUnitLite.Tests.TextUITests.DisplayError () inline
References NUnitLite.Tests.TextUITests._textUI, NUnitLite.TextUI.DisplayError(), NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.TextUITests.NL, NUnitLite.Tests.TextUITests.Report, and NUnit.Framework.Assert.That().
DisplayErrors()
void NUnitLite.Tests.TextUITests.DisplayErrors () inline
References NUnitLite.Tests.TextUITests._textUI, NUnitLite.TextUI.DisplayErrors(), NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.TextUITests.NL, NUnitLite.Tests.TextUITests.Report, and NUnit.Framework.Assert.That().
DisplayHeader()
void NUnitLite.Tests.TextUITests.DisplayHeader () inline
References NUnitLite.Tests.TextUITests._textUI, NUnitLite.TextUI.DisplayHeader(), NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.TextUITests.GetReportLines(), NUnit.Framework.Does.StartWith(), and NUnit.Framework.Assert.That().
DisplayTestFiles()
void NUnitLite.Tests.TextUITests.DisplayTestFiles () inline
References NUnitLite.Tests.TextUITests._textUI, NUnitLite.TextUI.DisplayTestFiles(), NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.TextUITests.GetReportLines(), and NUnit.Framework.Assert.That().
DisplayRuntimeEnvironment()
void NUnitLite.Tests.TextUITests.DisplayRuntimeEnvironment () inline
References NUnitLite.Tests.TextUITests._textUI, NUnitLite.TextUI.DisplayRuntimeEnvironment(), NUnit.Framework.Is.Empty, NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.TextUITests.GetReportLines(), NUnit.Framework.Contains.Substring(), and NUnit.Framework.Assert.That().
TestFinished_NoOutput()
void NUnitLite.Tests.TextUITests.TestFinished_NoOutput () inline
References NUnitLite.Tests.TextUITests._textUI, NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.Fakes.GetTestMethod(), NUnitLite.Tests.TextUITests.Report, NUnitLite.TextUI.TestFinished(), and NUnit.Framework.Assert.That().
TestFinished_WithOutput()
void NUnitLite.Tests.TextUITests.TestFinished_WithOutput () inline
References NUnitLite.Tests.TextUITests._textUI, NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.TextUITests.GetReportLines(), NUnit.TestUtilities.Fakes.GetTestMethod(), NUnitLite.TextUI.TestFinished(), and NUnit.Framework.Assert.That().
MyFakeMethod()
void NUnitLite.Tests.TextUITests.MyFakeMethod () inline private
DisplayHelp()
void NUnitLite.Tests.TextUITests.DisplayHelp () inline
References NUnitLite.Tests.TextUITests._textUI, NUnitLite.TextUI.DisplayHelp(), NUnitLite.Tests.TextUITests.Report, NUnit.Framework.Does.StartWith(), and NUnit.Framework.Assert.That().
DisplayRequestedOptions()
void NUnitLite.Tests.TextUITests.DisplayRequestedOptions () inline
References NUnitLite.Tests.TextUITests._textUI, NUnitLite.TextUI.DisplayRequestedOptions(), NUnit.Framework.Is.Empty, NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.TextUITests.GetReportLines(), NUnit.Framework.Does.StartWith(), and NUnit.Framework.Assert.That().
ReportSequenceTest()
void NUnitLite.Tests.TextUITests.ReportSequenceTest () inline
References NUnitLite.Tests.TextUITests._result, NUnitLite.Tests.TextUITests._textUI, NUnitLite.Tests.TextUITests.Report, NUnitLite.Tests.TextUITests.REPORT_SEQUENCE, and NUnit.Framework.Assert.That().
TestsNotRunTest()
void NUnitLite.Tests.TextUITests.TestsNotRunTest () inline
References NUnitLite.Tests.TextUITests._result, NUnitLite.Tests.TextUITests._textUI, NUnitLite.TextUI.DisplayNotRunReport(), NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.TextUITests.GetReportLines(), and NUnit.Framework.Assert.That().
SummaryReportTest()
void NUnitLite.Tests.TextUITests.SummaryReportTest () inline
References NUnitLite.Tests.TextUITests._result, NUnitLite.Tests.TextUITests._textUI, NUnitLite.TextUI.DisplaySummaryReport(), NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.TextUITests.GetReportLines(), and NUnit.Framework.Assert.That().
ErrorsAndFailuresReportTest()
void NUnitLite.Tests.TextUITests.ErrorsAndFailuresReportTest () inline
References NUnitLite.Tests.TextUITests._result, NUnitLite.Tests.TextUITests._textUI, NUnitLite.TextUI.DisplayErrorsAndFailuresReport(), NUnit.Framework.Is.EqualTo(), NUnitLite.Tests.TextUITests.GetReportLines(), and NUnit.Framework.Assert.That().
GetReportLines()
IList<string> NUnitLite.Tests.TextUITests.GetReportLines () inline private
References NUnitLite.Tests.TextUITests.Report.
Referenced by NUnitLite.Tests.TextUITests.DisplayHeader(), NUnitLite.Tests.TextUITests.DisplayRequestedOptions(), NUnitLite.Tests.TextUITests.DisplayRuntimeEnvironment(), NUnitLite.Tests.TextUITests.DisplayTestFiles(), NUnitLite.Tests.TextUITests.ErrorsAndFailuresReportTest(), NUnitLite.Tests.TextUITests.SummaryReportTest(), NUnitLite.Tests.TextUITests.TestFinished_WithOutput(), and NUnitLite.Tests.TextUITests.TestsNotRunTest().
Member Data Documentation
NL
readonly string NUnitLite.Tests.TextUITests.NL = NUnit.Env.NewLine static private
Referenced by NUnitLite.Tests.TextUITests.DisplayError(), NUnitLite.Tests.TextUITests.DisplayErrors(), and NUnitLite.Tests.TextUITests.DisplayWarning().
_textUI
TextUI NUnitLite.Tests.TextUITests._textUI private
Referenced by NUnitLite.Tests.TextUITests.CreateTextUI(), NUnitLite.Tests.TextUITests.DisplayError(), NUnitLite.Tests.TextUITests.DisplayErrors(), NUnitLite.Tests.TextUITests.DisplayHeader(), NUnitLite.Tests.TextUITests.DisplayHelp(), NUnitLite.Tests.TextUITests.DisplayRequestedOptions(), NUnitLite.Tests.TextUITests.DisplayRuntimeEnvironment(), NUnitLite.Tests.TextUITests.DisplayTestFiles(), NUnitLite.Tests.TextUITests.DisplayWarning(), NUnitLite.Tests.TextUITests.ErrorsAndFailuresReportTest(), NUnitLite.Tests.TextUITests.ReportSequenceTest(), NUnitLite.Tests.TextUITests.SummaryReportTest(), NUnitLite.Tests.TextUITests.TestFinished_NoOutput(), NUnitLite.Tests.TextUITests.TestFinished_WithOutput(), and NUnitLite.Tests.TextUITests.TestsNotRunTest().
_reportBuilder
StringBuilder NUnitLite.Tests.TextUITests._reportBuilder private
Referenced by NUnitLite.Tests.TextUITests.CreateTextUI().
_result
TestResult NUnitLite.Tests.TextUITests._result private
Referenced by NUnitLite.Tests.TextUITests.CreateResult(), NUnitLite.Tests.TextUITests.ErrorsAndFailuresReportTest(), NUnitLite.Tests.TextUITests.ReportSequenceTest(), NUnitLite.Tests.TextUITests.SummaryReportTest(), and NUnitLite.Tests.TextUITests.TestsNotRunTest().
REPORT_SEQUENCE
readonly string [] NUnitLite.Tests.TextUITests.REPORT_SEQUENCE static private
Initial value:
= new string[] {
            "Test Run Summary",
            "Errors and Failures",
            "Tests Not Run"
        }
Referenced by NUnitLite.Tests.TextUITests.ReportSequenceTest().
Property Documentation
Report
string NUnitLite.Tests.TextUITests.Report get private
Referenced by NUnitLite.Tests.TextUITests.DisplayError(), NUnitLite.Tests.TextUITests.DisplayErrors(), NUnitLite.Tests.TextUITests.DisplayHelp(), NUnitLite.Tests.TextUITests.DisplayWarning(), NUnitLite.Tests.TextUITests.GetReportLines(), NUnitLite.Tests.TextUITests.ReportSequenceTest(), and NUnitLite.Tests.TextUITests.TestFinished_NoOutput().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/nunitlite.tests/TextUITests.cs