Doc: IGLib EXTENDED: WcfService_WebDev_FromTemplate.WSBaseRef.WSBase Class Reference
WcfService_WebDev_FromTemplate.WSBaseRef.WSBase Class Reference
Public Member Functions
WSBase ()
string TestCount ()
void TestCountAsync ()
void TestCountAsync (object userState)
string TestService ()
void TestServiceAsync ()
void TestServiceAsync (object userState)
string TestServiceArg (string commandlineArguments)
void TestServiceArgAsync (string commandlineArguments)
void TestServiceArgAsync (string commandlineArguments, object userState)
string TestServiceArgs (string[] commandlineArguments)
void TestServiceArgsAsync (string[] commandlineArguments)
void TestServiceArgsAsync (string[] commandlineArguments, object userState)
new void CancelAsync (object userState)
Properties
new string Url [get, set]
new bool UseDefaultCredentials [get, set]
Events
TestCountCompletedEventHandler TestCountCompleted
TestServiceCompletedEventHandler TestServiceCompleted
TestServiceArgCompletedEventHandler TestServiceArgCompleted
TestServiceArgsCompletedEventHandler TestServiceArgsCompleted
Private Member Functions
void OnTestCountOperationCompleted (object arg)
void OnTestServiceOperationCompleted (object arg)
void OnTestServiceArgOperationCompleted (object arg)
void OnTestServiceArgsOperationCompleted (object arg)
bool IsLocalFileSystemWebService (string url)
Private Attributes
System.Threading.SendOrPostCallback TestCountOperationCompleted
System.Threading.SendOrPostCallback TestServiceOperationCompleted
System.Threading.SendOrPostCallback TestServiceArgOperationCompleted
System.Threading.SendOrPostCallback TestServiceArgsOperationCompleted
bool useDefaultCredentialsSetExplicitly
Detailed Description
Constructor & Destructor Documentation
WSBase()
WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.WSBase () inline
References WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.IsLocalFileSystemWebService(), WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.Url, and WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.UseDefaultCredentials.
Member Function Documentation
TestCount()
string WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestCount () inline
TestCountAsync() [1/2]
void WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestCountAsync () inline
TestCountAsync() [2/2]
void WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestCountAsync (object userState) inline
References WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.OnTestCountOperationCompleted(), and WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestCountOperationCompleted.
OnTestCountOperationCompleted()
void WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.OnTestCountOperationCompleted (object arg) inline private
References WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestCountCompleted.
Referenced by WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestCountAsync().
TestService()
string WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestService () inline
TestServiceAsync() [1/2]
void WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceAsync () inline
TestServiceAsync() [2/2]
void WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceAsync (object userState) inline
References WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.OnTestServiceOperationCompleted(), and WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceOperationCompleted.
OnTestServiceOperationCompleted()
void WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.OnTestServiceOperationCompleted (object arg) inline private
References WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceCompleted.
Referenced by WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceAsync().
TestServiceArg()
string WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceArg (string commandlineArguments) inline
Referenced by IG.Web.WSBaseExamples.ExampleUseServiceWithSessions(), and IG.Web.WSBase.ExampleUseServiceWithSessions().
TestServiceArgAsync() [1/2]
void WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceArgAsync (string commandlineArguments) inline
TestServiceArgAsync() [2/2]
void WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceArgAsync (string commandlineArguments, object userState) inline
References WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.OnTestServiceArgOperationCompleted(), and WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceArgOperationCompleted.
OnTestServiceArgOperationCompleted()
void WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.OnTestServiceArgOperationCompleted (object arg) inline private
References WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceArgCompleted.
Referenced by WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceArgAsync().
TestServiceArgs()
string WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceArgs (string[] commandlineArguments) inline
TestServiceArgsAsync() [1/2]
void WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceArgsAsync (string[] commandlineArguments) inline
TestServiceArgsAsync() [2/2]
void WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceArgsAsync (string[] commandlineArguments, object userState) inline
References WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.OnTestServiceArgsOperationCompleted(), and WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceArgsOperationCompleted.
OnTestServiceArgsOperationCompleted()
void WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.OnTestServiceArgsOperationCompleted (object arg) inline private
References WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceArgsCompleted.
Referenced by WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceArgsAsync().
CancelAsync()
new void WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.CancelAsync (object userState) inline
IsLocalFileSystemWebService()
bool WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.IsLocalFileSystemWebService (string url) inline private
Referenced by WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.WSBase().
Member Data Documentation
TestCountOperationCompleted
System.Threading.SendOrPostCallback WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestCountOperationCompleted private
Referenced by WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestCountAsync().
TestServiceOperationCompleted
System.Threading.SendOrPostCallback WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceOperationCompleted private
Referenced by WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceAsync().
TestServiceArgOperationCompleted
System.Threading.SendOrPostCallback WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceArgOperationCompleted private
Referenced by WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceArgAsync().
TestServiceArgsOperationCompleted
System.Threading.SendOrPostCallback WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceArgsOperationCompleted private
Referenced by WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceArgsAsync().
useDefaultCredentialsSetExplicitly
bool WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.useDefaultCredentialsSetExplicitly private
Property Documentation
Url
new string WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.Url get set
Referenced by WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.WSBase().
UseDefaultCredentials
new bool WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.UseDefaultCredentials get set
Referenced by WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.WSBase().
Event Documentation
TestCountCompleted
TestCountCompletedEventHandler WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestCountCompleted
Referenced by WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.OnTestCountOperationCompleted().
TestServiceCompleted
TestServiceCompletedEventHandler WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceCompleted
Referenced by WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.OnTestServiceOperationCompleted().
TestServiceArgCompleted
TestServiceArgCompletedEventHandler WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceArgCompleted
Referenced by WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.OnTestServiceArgOperationCompleted().
TestServiceArgsCompleted
TestServiceArgsCompletedEventHandler WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceArgsCompleted
Referenced by WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.OnTestServiceArgsOperationCompleted().
The documentation for this class was generated from the following file:
igtest/ws_develop/Web References/WSBaseRef/Reference.cs