Doc: IGLib EXTENDED: IG.Forms.ScriptLoaderForm Class Reference
IG.Forms.ScriptLoaderForm Class Reference
Public Member Functions
ScriptLoaderForm ()
Initializes form components and internal variables.
Public Attributes
ReporterConsoleMsgbox Reporter = new ReporterConsoleMsgbox()
Protected Member Functions
void ReportError (string message, Exception ex)
Launches error report.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
ScriptLoaderIGLib.ScriptLoaderTest Compiler = new ScriptLoaderIGLib.ScriptLoaderTest()
Properties
Logger Logger [get]
Gets compiler's logger.
Private Member Functions
void btnLoad_Click (object sender, System.EventArgs e)
Loads code template into the rich textbox.
void ChooseFile ()
void btnLoadFromFile_Click (object sender, EventArgs e)
void btnCompile_Click (object sender, System.EventArgs e)
Compilation of code.
void btnRun_Click (object sender, System.EventArgs e)
void btnQuit_Click (object sender, System.EventArgs e)
void btnOther_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Logger _logger = null
string _filePath = "../../loadablescript/tests/data/"
bool _fileChosen = false
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.RichTextBox rtfCode
System.Windows.Forms.Button btnLoad
System.Windows.Forms.Button btnCompile
System.Windows.Forms.Button btnRun
System.Windows.Forms.Button btnQuit
System.Windows.Forms.Button btnLoadFromFile
System.Windows.Forms.Label lblInitArgs
System.Windows.Forms.TextBox txtInitArgs
System.Windows.Forms.Label lblRunArgs
System.Windows.Forms.TextBox txtRunArgs
System.Windows.Forms.Button btnOther
Constructor & Destructor Documentation
ScriptLoaderForm()
IG.Forms.ScriptLoaderForm.ScriptLoaderForm () inline
Initializes form components and internal variables.
References IG.Forms.ScriptLoaderForm.InitializeComponent(), and IG.Forms.ScriptLoaderForm.Reporter.
Member Function Documentation
ReportError()
void IG.Forms.ScriptLoaderForm.ReportError (string message, Exception ex) inline protected
Launches error report.
Parameters
message Custom part of the message shown in report.
ex Exception that was thrown.
btnLoad_Click()
void IG.Forms.ScriptLoaderForm.btnLoad_Click (object sender, System.EventArgs e) inline private
Loads code template into the rich textbox.
References IG.Lib.ScriptLoaderBase.Code, IG.Forms.ScriptLoaderForm.Compiler, and IG.Forms.ScriptLoaderForm.rtfCode.
Referenced by IG.Forms.ScriptLoaderForm.InitializeComponent().
ChooseFile()
void IG.Forms.ScriptLoaderForm.ChooseFile () inline private
References IG.Forms.ScriptLoaderForm._fileChosen, and IG.Forms.ScriptLoaderForm._filePath.
Referenced by IG.Forms.ScriptLoaderForm.btnLoadFromFile_Click().
btnLoadFromFile_Click()
void IG.Forms.ScriptLoaderForm.btnLoadFromFile_Click (object sender, EventArgs e) inline private
References IG.Forms.ScriptLoaderForm._fileChosen, IG.Forms.ScriptLoaderForm._filePath, IG.Forms.ScriptLoaderForm.ChooseFile(), and IG.Forms.ScriptLoaderForm.rtfCode.
Referenced by IG.Forms.ScriptLoaderForm.InitializeComponent().
btnCompile_Click()
void IG.Forms.ScriptLoaderForm.btnCompile_Click (object sender, System.EventArgs e) inline private
Compilation of code.
References IG.Lib.Logger.Clear(), IG.Lib.ScriptLoaderBase.ClearLogger(), IG.Lib.ScriptLoaderBase.Code, IG.Lib.ScriptLoaderBase.Compile(), IG.Forms.ScriptLoaderForm.Compiler, IG.Lib.Logger.GetErrorsReport(), IG.Lib.Logger.GetReport(), IG.Lib.Logger.GetWarningsReport(), IG.Lib.Logger.HasErrors(), IG.Lib.Logger.HasWarnings(), IG.Lib.Logger.Report(), IG.Forms.ScriptLoaderForm.Reporter, and IG.Forms.ScriptLoaderForm.rtfCode.
Referenced by IG.Forms.ScriptLoaderForm.InitializeComponent().
btnRun_Click()
void IG.Forms.ScriptLoaderForm.btnRun_Click (object sender, System.EventArgs e) inline private
References IG.Forms.ScriptLoaderForm.Compiler, IG.Lib.UtilStr.GetArgumentsArray(), IG.Lib.ScriptLoaderBase.Run(), IG.Forms.ScriptLoaderForm.txtInitArgs, and IG.Forms.ScriptLoaderForm.txtRunArgs.
Referenced by IG.Forms.ScriptLoaderForm.InitializeComponent().
btnQuit_Click()
void IG.Forms.ScriptLoaderForm.btnQuit_Click (object sender, System.EventArgs e) inline private
Referenced by IG.Forms.ScriptLoaderForm.InitializeComponent().
btnOther_Click()
void IG.Forms.ScriptLoaderForm.btnOther_Click (object sender, EventArgs e) inline private
References IG.Forms.TestLoadableScriptInterpreter.RunTest().
Referenced by IG.Forms.ScriptLoaderForm.InitializeComponent().
Dispose()
override void IG.Forms.ScriptLoaderForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ScriptLoaderForm.components.
InitializeComponent()
void IG.Forms.ScriptLoaderForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ScriptLoaderForm.btnCompile, IG.Forms.ScriptLoaderForm.btnCompile_Click(), IG.Forms.ScriptLoaderForm.btnLoad, IG.Forms.ScriptLoaderForm.btnLoad_Click(), IG.Forms.ScriptLoaderForm.btnLoadFromFile, IG.Forms.ScriptLoaderForm.btnLoadFromFile_Click(), IG.Forms.ScriptLoaderForm.btnOther, IG.Forms.ScriptLoaderForm.btnOther_Click(), IG.Forms.ScriptLoaderForm.btnQuit, IG.Forms.ScriptLoaderForm.btnQuit_Click(), IG.Forms.ScriptLoaderForm.btnRun, IG.Forms.ScriptLoaderForm.btnRun_Click(), IG.Forms.ScriptLoaderForm.lblInitArgs, IG.Forms.ScriptLoaderForm.lblRunArgs, IG.Forms.ScriptLoaderForm.rtfCode, IG.Forms.ScriptLoaderForm.txtInitArgs, and IG.Forms.ScriptLoaderForm.txtRunArgs.
Referenced by IG.Forms.ScriptLoaderForm.ScriptLoaderForm().
Member Data Documentation
Compiler
ScriptLoaderIGLib.ScriptLoaderTest IG.Forms.ScriptLoaderForm.Compiler = new ScriptLoaderIGLib.ScriptLoaderTest() protected
Referenced by IG.Forms.ScriptLoaderForm.btnCompile_Click(), IG.Forms.ScriptLoaderForm.btnLoad_Click(), and IG.Forms.ScriptLoaderForm.btnRun_Click().
Reporter
ReporterConsoleMsgbox IG.Forms.ScriptLoaderForm.Reporter = new ReporterConsoleMsgbox()
Referenced by IG.Forms.ScriptLoaderForm.btnCompile_Click(), IG.Test.RuntimeCompilerMain.Main(), and IG.Forms.ScriptLoaderForm.ScriptLoaderForm().
_logger
Logger IG.Forms.ScriptLoaderForm._logger = null private
_filePath
string IG.Forms.ScriptLoaderForm._filePath = "../../loadablescript/tests/data/" private
Referenced by IG.Forms.ScriptLoaderForm.btnLoadFromFile_Click(), and IG.Forms.ScriptLoaderForm.ChooseFile().
_fileChosen
bool IG.Forms.ScriptLoaderForm._fileChosen = false private
Referenced by IG.Forms.ScriptLoaderForm.btnLoadFromFile_Click(), and IG.Forms.ScriptLoaderForm.ChooseFile().
components
System.ComponentModel.IContainer IG.Forms.ScriptLoaderForm.components = null private
Required designer variable.
Referenced by IG.Forms.ScriptLoaderForm.Dispose().
rtfCode
System.Windows.Forms.RichTextBox IG.Forms.ScriptLoaderForm.rtfCode private
Referenced by IG.Forms.ScriptLoaderForm.btnCompile_Click(), IG.Forms.ScriptLoaderForm.btnLoad_Click(), IG.Forms.ScriptLoaderForm.btnLoadFromFile_Click(), and IG.Forms.ScriptLoaderForm.InitializeComponent().
btnLoad
System.Windows.Forms.Button IG.Forms.ScriptLoaderForm.btnLoad private
Referenced by IG.Forms.ScriptLoaderForm.InitializeComponent().
btnCompile
System.Windows.Forms.Button IG.Forms.ScriptLoaderForm.btnCompile private
Referenced by IG.Forms.ScriptLoaderForm.InitializeComponent().
btnRun
System.Windows.Forms.Button IG.Forms.ScriptLoaderForm.btnRun private
Referenced by IG.Forms.ScriptLoaderForm.InitializeComponent().
btnQuit
System.Windows.Forms.Button IG.Forms.ScriptLoaderForm.btnQuit private
Referenced by IG.Forms.ScriptLoaderForm.InitializeComponent().
btnLoadFromFile
System.Windows.Forms.Button IG.Forms.ScriptLoaderForm.btnLoadFromFile private
Referenced by IG.Forms.ScriptLoaderForm.InitializeComponent().
lblInitArgs
System.Windows.Forms.Label IG.Forms.ScriptLoaderForm.lblInitArgs private
Referenced by IG.Forms.ScriptLoaderForm.InitializeComponent().
txtInitArgs
System.Windows.Forms.TextBox IG.Forms.ScriptLoaderForm.txtInitArgs private
Referenced by IG.Forms.ScriptLoaderForm.btnRun_Click(), and IG.Forms.ScriptLoaderForm.InitializeComponent().
lblRunArgs
System.Windows.Forms.Label IG.Forms.ScriptLoaderForm.lblRunArgs private
Referenced by IG.Forms.ScriptLoaderForm.InitializeComponent().
txtRunArgs
System.Windows.Forms.TextBox IG.Forms.ScriptLoaderForm.txtRunArgs private
Referenced by IG.Forms.ScriptLoaderForm.btnRun_Click(), and IG.Forms.ScriptLoaderForm.InitializeComponent().
btnOther
System.Windows.Forms.Button IG.Forms.ScriptLoaderForm.btnOther private
Referenced by IG.Forms.ScriptLoaderForm.InitializeComponent().
Property Documentation
Logger
Logger IG.Forms.ScriptLoaderForm.Logger get protected
Gets compiler's logger.
The documentation for this class was generated from the following files:
igtest/test_iglib_tmp_CSharpScripter/loadablescript/tests/ScriptLoaderForm.cs
igtest/test_iglib_tmp_CSharpScripter/loadablescript/tests/ScriptLoaderForm.Designer.cs