Doc: IGLib EXTENDED: NUnit.Framework.Internal.CultureSettingAndDetectionTests Class Reference
NUnit.Framework.Internal.CultureSettingAndDetectionTests Class Reference
Summary description for CultureDetectionTests.
Classes
class NestedFixture
Public Member Functions
void CanMatchStrings ()
void CanMatchAttributeWithInclude ()
void CanMatchAttributeWithExclude ()
void CanMatchAttributeWithIncludeAndExclude ()
void LoadWithFrenchCulture ()
void LoadWithFrenchCanadianCulture ()
void LoadWithRussianCulture ()
Private Member Functions
void ExpectMatch (string culture)
void ExpectMatch (CultureAttribute attr)
void ExpectFailure (string culture)
void ExpectFailure (CultureAttribute attr, string msg)
Private Attributes
NUnit.Framework.Internal.CultureDetector detector = new NUnit.Framework.Internal.CultureDetector("fr-FR")
Detailed Description
Summary description for CultureDetectionTests.
Member Function Documentation
ExpectMatch() [1/2]
void NUnit.Framework.Internal.CultureSettingAndDetectionTests.ExpectMatch (string culture) inline private
References NUnit.Framework.Internal.CultureSettingAndDetectionTests.detector, NUnit.Framework.Assert.Fail(), and NUnit.Framework.Internal.CultureDetector.IsCultureSupported().
Referenced by NUnit.Framework.Internal.CultureSettingAndDetectionTests.CanMatchAttributeWithExclude(), NUnit.Framework.Internal.CultureSettingAndDetectionTests.CanMatchAttributeWithInclude(), NUnit.Framework.Internal.CultureSettingAndDetectionTests.CanMatchAttributeWithIncludeAndExclude(), and NUnit.Framework.Internal.CultureSettingAndDetectionTests.CanMatchStrings().
ExpectMatch() [2/2]
void NUnit.Framework.Internal.CultureSettingAndDetectionTests.ExpectMatch (CultureAttribute attr) inline private
References NUnit.Framework.Internal.CultureSettingAndDetectionTests.detector, NUnit.Framework.IncludeExcludeAttribute.Exclude, NUnit.Framework.Assert.Fail(), NUnit.Framework.IncludeExcludeAttribute.Include, and NUnit.Framework.Internal.CultureDetector.IsCultureSupported().
ExpectFailure() [1/2]
void NUnit.Framework.Internal.CultureSettingAndDetectionTests.ExpectFailure (string culture) inline private
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.CultureSettingAndDetectionTests.detector, NUnit.Framework.Assert.Fail(), NUnit.Framework.Internal.CultureDetector.IsCultureSupported(), and NUnit.Framework.Internal.CultureDetector.Reason.
Referenced by NUnit.Framework.Internal.CultureSettingAndDetectionTests.CanMatchAttributeWithExclude(), NUnit.Framework.Internal.CultureSettingAndDetectionTests.CanMatchAttributeWithInclude(), NUnit.Framework.Internal.CultureSettingAndDetectionTests.CanMatchAttributeWithIncludeAndExclude(), and NUnit.Framework.Internal.CultureSettingAndDetectionTests.CanMatchStrings().
ExpectFailure() [2/2]
void NUnit.Framework.Internal.CultureSettingAndDetectionTests.ExpectFailure (CultureAttribute attr, string msg) inline private
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.CultureSettingAndDetectionTests.detector, NUnit.Framework.IncludeExcludeAttribute.Exclude, NUnit.Framework.Assert.Fail(), NUnit.Framework.IncludeExcludeAttribute.Include, NUnit.Framework.Internal.CultureDetector.IsCultureSupported(), and NUnit.Framework.Internal.CultureDetector.Reason.
CanMatchStrings()
void NUnit.Framework.Internal.CultureSettingAndDetectionTests.CanMatchStrings () inline
References NUnit.Framework.Internal.CultureSettingAndDetectionTests.ExpectFailure(), and NUnit.Framework.Internal.CultureSettingAndDetectionTests.ExpectMatch().
CanMatchAttributeWithInclude()
void NUnit.Framework.Internal.CultureSettingAndDetectionTests.CanMatchAttributeWithInclude () inline
References NUnit.Framework.Internal.CultureSettingAndDetectionTests.ExpectFailure(), and NUnit.Framework.Internal.CultureSettingAndDetectionTests.ExpectMatch().
CanMatchAttributeWithExclude()
void NUnit.Framework.Internal.CultureSettingAndDetectionTests.CanMatchAttributeWithExclude () inline
References NUnit.Framework.IncludeExcludeAttribute.Exclude, NUnit.Framework.Internal.CultureSettingAndDetectionTests.ExpectFailure(), and NUnit.Framework.Internal.CultureSettingAndDetectionTests.ExpectMatch().
CanMatchAttributeWithIncludeAndExclude()
void NUnit.Framework.Internal.CultureSettingAndDetectionTests.CanMatchAttributeWithIncludeAndExclude () inline
References NUnit.Framework.IncludeExcludeAttribute.Exclude, NUnit.Framework.Internal.CultureSettingAndDetectionTests.ExpectFailure(), and NUnit.Framework.Internal.CultureSettingAndDetectionTests.ExpectMatch().
LoadWithFrenchCulture()
void NUnit.Framework.Internal.CultureSettingAndDetectionTests.LoadWithFrenchCulture () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestUtilities.TestBuilder.MakeFixture(), NUnit.Framework.Internal.Test.Name, and NUnit.Framework.Internal.Test.RunState.
LoadWithFrenchCanadianCulture()
void NUnit.Framework.Internal.CultureSettingAndDetectionTests.LoadWithFrenchCanadianCulture () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestUtilities.TestBuilder.MakeFixture(), NUnit.Framework.Internal.Test.Name, NUnit.Framework.Internal.Test.RunState, and NUnit.Framework.Internal.Test.Tests.
LoadWithRussianCulture()
void NUnit.Framework.Internal.CultureSettingAndDetectionTests.LoadWithRussianCulture () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestUtilities.TestBuilder.MakeFixture(), NUnit.Framework.Internal.Test.Name, NUnit.Framework.Internal.Test.RunState, and NUnit.Framework.Internal.Test.Tests.
Member Data Documentation
detector
NUnit.Framework.Internal.CultureDetector NUnit.Framework.Internal.CultureSettingAndDetectionTests.detector = new NUnit.Framework.Internal.CultureDetector("fr-FR") private
Referenced by NUnit.Framework.Internal.CultureSettingAndDetectionTests.ExpectFailure(), and NUnit.Framework.Internal.CultureSettingAndDetectionTests.ExpectMatch().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/CultureSettingAndDetectionTests.cs