Doc: IGLib EXTENDED: AForge.Genetic.OptimizationFunction1D Class Reference
AForge.Genetic.OptimizationFunction1D Class Reference abstract
Base class for one dimensional function optimizations.
Public Types
enum Modes { Modes.Maximization, Modes.Minimization }
Optimization modes.
Public Member Functions
OptimizationFunction1D (Range range)
Initializes a new instance of the OptimizationFunction1D class.
double Evaluate (IChromosome chromosome)
Evaluates chromosome.
double Translate (IChromosome chromosome)
Translates genotype to phenotype.
abstract double OptimizationFunction (double x)
Function to optimize.
Properties
Range Range [get, set]
Optimization range.
Modes Mode [get, set]
Optimization mode.
Private Attributes
Range range = new Range(0, 1)
Modes mode = Modes.Maximization
Detailed Description
Base class for one dimensional function optimizations.
The class is aimed to be used for one dimensional function optimization problems. It implements all methods of IFitnessFunction interface and requires overriding only one method - OptimizationFunction, which represents the function to optimize.
<note>The optimization function should be greater than 0 on the specified optimization range.</note>
The class works only with binary chromosomes (BinaryChromosome).
Sample usage:
// define optimization function
public class UserFunction : OptimizationFunction1D
{
    public UserFunction( ) :
        base( new Range( 0, 255 ) ) { }
    public override double OptimizationFunction( double x )
    {
        return Math.Cos( x / 23 ) * Math.Sin( x / 50 ) + 2;
    }
}
...
// create genetic population
Population population = new Population(40,
    new BinaryChromosome( 32 ),
    new UserFunction( ),
    new EliteSelection( ) );
while (true)
{
    // run one epoch of the population
    population.RunEpoch( );
    // ...
}
Member Enumeration Documentation
Modes
enum AForge.Genetic.OptimizationFunction1D.Modes strong
Optimization modes.
The enumeration defines optimization modes for the one dimensional function optimization.
Enumerator
Maximization
Search for function's maximum value.
Minimization
Search for function's minimum value.
Constructor & Destructor Documentation
OptimizationFunction1D()
AForge.Genetic.OptimizationFunction1D.OptimizationFunction1D (Range range) inline
Initializes a new instance of the OptimizationFunction1D class.
Parameters
range Specifies range for optimization.
References AForge.Genetic.OptimizationFunction1D.range.
Member Function Documentation
Evaluate()
double AForge.Genetic.OptimizationFunction1D.Evaluate (IChromosome chromosome) inline
Evaluates chromosome.
Parameters
chromosome Chromosome to evaluate.
Returns
Returns chromosome's fitness value.
The method calculates fitness value of the specified chromosome.
Implements AForge.Genetic.IFitnessFunction.
References AForge.Genetic.OptimizationFunction1D.mode, AForge.Genetic.OptimizationFunction1D.OptimizationFunction(), and AForge.Genetic.OptimizationFunction1D.Translate().
Translate()
double AForge.Genetic.OptimizationFunction1D.Translate (IChromosome chromosome) inline
Translates genotype to phenotype.
Parameters
chromosome Chromosome, which genoteype should be translated to phenotype.
Returns
Returns chromosome's fenotype - the actual solution encoded by the chromosome.
The method returns double value, which represents function's input point encoded by the specified chromosome.
References AForge.Range.Length, AForge.Range.Min, and AForge.Genetic.OptimizationFunction1D.range.
Referenced by AForge.Genetic.OptimizationFunction1D.Evaluate(), and Optimization1D.MainForm.SearchSolution().
OptimizationFunction()
abstract double AForge.Genetic.OptimizationFunction1D.OptimizationFunction (double x) pure virtual
Function to optimize.
Parameters
x Function's input value.
Returns
Returns function output value.
The method should be overloaded by inherited class to specify the optimization function.
Implemented in Optimization1D.UserFunction.
Referenced by AForge.Genetic.OptimizationFunction1D.Evaluate().
Member Data Documentation
range
Range AForge.Genetic.OptimizationFunction1D.range = new Range(0, 1) private
Referenced by AForge.Genetic.OptimizationFunction1D.OptimizationFunction1D(), and AForge.Genetic.OptimizationFunction1D.Translate().
mode
Modes AForge.Genetic.OptimizationFunction1D.mode = Modes.Maximization private
Referenced by AForge.Genetic.OptimizationFunction1D.Evaluate().
Property Documentation
Range
Range AForge.Genetic.OptimizationFunction1D.Range get set
Optimization range.
Defines function's input range. The function's extreme point will be searched in this range only.
Referenced by Optimization1D.MainForm.MainForm(), Optimization1D.MainForm.maxXBox_TextChanged(), Optimization1D.MainForm.minXBox_TextChanged(), and Optimization1D.MainForm.UpdateChart().
Mode
Modes AForge.Genetic.OptimizationFunction1D.Mode get set
Optimization mode.
Defines optimization mode - what kind of extreme point to search.
Referenced by Optimization1D.MainForm.SearchSolution().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Genetic/Fitness Functions/OptimizationFunction1D.cs