Doc: IGLib EXTENDED: AForge.Imaging.HSL Class Reference
AForge.Imaging.HSL Class Reference
HSL components.
Public Member Functions
HSL ()
Initializes a new instance of the HSL class.
HSL (int hue, float saturation, float luminance)
Initializes a new instance of the HSL class.
RGB ToRGB ()
Convert the color to RGB color space.
Static Public Member Functions
static void FromRGB (RGB rgb, HSL hsl)
Convert from RGB to HSL color space.
static HSL FromRGB (RGB rgb)
Convert from RGB to HSL color space.
static void ToRGB (HSL hsl, RGB rgb)
Convert from HSL to RGB color space.
Public Attributes
int Hue
Hue component.
float Saturation
Saturation component.
float Luminance
Luminance value.
Static Private Member Functions
static float Hue_2_RGB (float v1, float v2, float vH)
Detailed Description
HSL components.
The class encapsulates HSL color components.
Constructor & Destructor Documentation
HSL() [1/2]
AForge.Imaging.HSL.HSL () inline
Initializes a new instance of the HSL class.
Referenced by AForge.Imaging.HSL.FromRGB().
HSL() [2/2]
AForge.Imaging.HSL.HSL (int hue, float saturation, float luminance) inline
Initializes a new instance of the HSL class.
Parameters
hue Hue component.
saturation Saturation component.
luminance Luminance component.
Member Function Documentation
FromRGB() [1/2]
static void AForge.Imaging.HSL.FromRGB (RGB rgb, HSL hsl) inline static
Convert from RGB to HSL color space.
Parameters
rgb Source color in RGB color space.
hsl Destination color in HSL color space.
See HSL and HSV Wiki for information about the algorithm to convert from RGB to HSL.
References AForge.Imaging.RGB.Blue, AForge.Imaging.RGB.Green, AForge.Imaging.HSL.Hue, AForge.Imaging.HSL.Luminance, AForge.Imaging.RGB.Red, and AForge.Imaging.HSL.Saturation.
Referenced by AForge.Imaging.HSL.FromRGB(), AForge.Imaging.Filters.HueModifier.ProcessFilter(), AForge.Imaging.Filters.HSLLinear.ProcessFilter(), AForge.Imaging.Filters.HSLFiltering.ProcessFilter(), and AForge.Imaging.ImageStatisticsHSL.ProcessImage().
FromRGB() [2/2]
static HSL AForge.Imaging.HSL.FromRGB (RGB rgb) inline static
Convert from RGB to HSL color space.
Parameters
rgb Source color in RGB color space.
Returns
Returns HSL instance, which represents converted color value.
References AForge.Imaging.HSL.FromRGB(), and AForge.Imaging.HSL.HSL().
ToRGB() [1/2]
static void AForge.Imaging.HSL.ToRGB (HSL hsl, RGB rgb) inline static
Convert from HSL to RGB color space.
Parameters
hsl Source color in HSL color space.
rgb Destination color in RGB color space.
References AForge.Imaging.RGB.Alpha, AForge.Imaging.RGB.Blue, AForge.Imaging.RGB.Green, AForge.Imaging.HSL.Hue, AForge.Imaging.HSL.Hue_2_RGB(), AForge.Imaging.HSL.Luminance, AForge.Imaging.RGB.Red, and AForge.Imaging.HSL.Saturation.
Referenced by AForge.Controls.HuePicker.OnPaint(), AForge.Imaging.Filters.HueModifier.ProcessFilter(), AForge.Imaging.Filters.HSLLinear.ProcessFilter(), and AForge.Imaging.Filters.HSLFiltering.ProcessFilter().
ToRGB() [2/2]
RGB AForge.Imaging.HSL.ToRGB () inline
Convert the color to RGB color space.
Returns
Returns RGB instance, which represents converted color value.
Hue_2_RGB()
static float AForge.Imaging.HSL.Hue_2_RGB (float v1, float v2, float vH) inline static private
Referenced by AForge.Imaging.HSL.ToRGB().
Member Data Documentation
Hue
int AForge.Imaging.HSL.Hue
Hue component.
Hue is measured in the range of [0, 359].
Referenced by AForge.Imaging.HSL.FromRGB(), AForge.Controls.HuePicker.OnPaint(), AForge.Imaging.Filters.HueModifier.ProcessFilter(), AForge.Imaging.Filters.HSLFiltering.ProcessFilter(), and AForge.Imaging.HSL.ToRGB().
Saturation
float AForge.Imaging.HSL.Saturation
Saturation component.
Saturation is measured in the range of [0, 1].
Referenced by AForge.Imaging.HSL.FromRGB(), AForge.Controls.HuePicker.OnPaint(), AForge.Imaging.Filters.HSLLinear.ProcessFilter(), AForge.Imaging.Filters.HSLFiltering.ProcessFilter(), AForge.Imaging.ImageStatisticsHSL.ProcessImage(), and AForge.Imaging.HSL.ToRGB().
Luminance
float AForge.Imaging.HSL.Luminance
Luminance value.
Luminance is measured in the range of [0, 1].
Referenced by AForge.Imaging.HSL.FromRGB(), AForge.Controls.HuePicker.OnPaint(), AForge.Imaging.Filters.HSLLinear.ProcessFilter(), AForge.Imaging.Filters.HSLFiltering.ProcessFilter(), AForge.Imaging.ImageStatisticsHSL.ProcessImage(), and AForge.Imaging.HSL.ToRGB().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/ColorConverter.cs