Doc: IGLib EXTENDED: NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader Class Reference
NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader Class Reference
Summary description for VSProjectLoader.
Public Member Functions
bool CanLoadFrom (string path)
Returns true if the file indicated is one that this loader knows how to load.
IProject LoadFrom (string path)
Loads a project of a known format.
Detailed Description
Summary description for VSProjectLoader.
Member Function Documentation
CanLoadFrom()
bool NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader.CanLoadFrom (string path) inline
Returns true if the file indicated is one that this loader knows how to load.
Parameters
path The path of the project file
Returns
True if the loader knows how to load this file, otherwise false
Implements NUnit.Engine.Extensibility.IProjectLoader.
References NUnit.Engine.Services.ProjectLoaders.VSProject.IsProjectFile(), and NUnit.Engine.Services.ProjectLoaders.VSProject.IsSolutionFile().
Referenced by NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.CanLoadVsProject(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.CannotLoadWebProject(), and NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.ValidExtensions().
LoadFrom()
IProject NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader.LoadFrom (string path) inline
Loads a project of a known format.
Parameters
path The path of the project file
Returns
An IProject interface to the loaded project or null if the project cannot be loaded
Implements NUnit.Engine.Extensibility.IProjectLoader.
References NUnit.Engine.Services.ProjectLoaders.VSProject.IsProjectFile(), and NUnit.Engine.Services.ProjectLoaders.VSProject.IsSolutionFile().
Referenced by NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.CanLoadVsProject(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromSolutionWithDisabledProject(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromVSSolution2003(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromVSSolution2005(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromWebApplication(), and NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.WithUnmanagedCpp().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/Addins/vs-project-loader/VisualStudioProjectLoader.cs