Doc: IGLib EXTENDED: NUnit.Framework.Attributes.DescriptionTests Class Reference
NUnit.Framework.Attributes.DescriptionTests Class Reference
Public Member Functions
void ReflectionTest ()
void Description ()
void NoDescription ()
void FixtureDescription ()
void SeparateDescriptionAttribute ()
void DescriptionOnTestCase ()
Static Private Attributes
static readonly Type FixtureType = typeof(DescriptionFixture)
Member Function Documentation
ReflectionTest()
void NUnit.Framework.Attributes.DescriptionTests.ReflectionTest () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Attributes.DescriptionTests.FixtureType, NUnit.TestUtilities.TestBuilder.MakeTestCase(), and NUnit.Framework.Internal.Test.RunState.
Description()
void NUnit.Framework.Attributes.DescriptionTests.Description () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.PropertyNames.Description, NUnit.Framework.Attributes.DescriptionTests.FixtureType, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeTestCase(), and NUnit.Framework.Internal.Test.Properties.
NoDescription()
void NUnit.Framework.Attributes.DescriptionTests.NoDescription () inline
References NUnit.Framework.Internal.PropertyNames.Description, NUnit.Framework.Attributes.DescriptionTests.FixtureType, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Assert.IsNull(), NUnit.TestUtilities.TestBuilder.MakeTestCase(), and NUnit.Framework.Internal.Test.Properties.
FixtureDescription()
void NUnit.Framework.Attributes.DescriptionTests.FixtureDescription () inline
References NUnit.Framework.Internal.TestSuite.Add(), NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.PropertyNames.Description, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeFixture(), NUnit.Framework.Internal.Test.Properties, and NUnit.Framework.Internal.TestSuite.Tests.
SeparateDescriptionAttribute()
void NUnit.Framework.Attributes.DescriptionTests.SeparateDescriptionAttribute () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.PropertyNames.Description, NUnit.Framework.Attributes.DescriptionTests.FixtureType, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeTestCase(), and NUnit.Framework.Internal.Test.Properties.
DescriptionOnTestCase()
void NUnit.Framework.Attributes.DescriptionTests.DescriptionOnTestCase () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.PropertyNames.Description, NUnit.Framework.Attributes.DescriptionTests.FixtureType, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), NUnit.Framework.Internal.Test.Properties, and NUnit.Framework.Internal.TestSuite.Tests.
Member Data Documentation
FixtureType
readonly Type NUnit.Framework.Attributes.DescriptionTests.FixtureType = typeof(DescriptionFixture) static private
Referenced by NUnit.Framework.Attributes.DescriptionTests.Description(), NUnit.Framework.Attributes.DescriptionTests.DescriptionOnTestCase(), NUnit.Framework.Attributes.DescriptionTests.NoDescription(), NUnit.Framework.Attributes.DescriptionTests.ReflectionTest(), and NUnit.Framework.Attributes.DescriptionTests.SeparateDescriptionAttribute().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/DescriptionTests.cs