Doc: IGLib EXTENDED: NUnit.Framework.Constraints.AttributeExistsConstraintTests Class Reference
NUnit.Framework.Constraints.AttributeExistsConstraintTests Class Reference
Classes
class B
class D1
class D2
Public Member Functions
void SetUp ()
void NonAttributeThrowsException ()
void AttributeExistsOnMethodInfo ()
void AttributeTestPropertyValueOnMethodInfo ()
Public Member Functions inherited from NUnit.Framework.Constraints.ConstraintTestBase
void SucceedsWithGoodValues (object value)
void FailsWithBadValues (object badValue, string message)
Public Member Functions inherited from NUnit.Framework.Constraints.ConstraintTestBaseNoData
void ProvidesProperDescription ()
void ProvidesProperStringRepresentation ()
Static Private Attributes
static object[] SuccessData = new object[] { typeof(AttributeExistsConstraintTests) }
static object[] FailureData
Additional Inherited Members
Protected Attributes inherited from NUnit.Framework.Constraints.ConstraintTestBaseNoData
Constraint theConstraint
string expectedDescription = "<NOT SET>"
string stringRepresentation = "<NOT SET>"
Member Function Documentation
SetUp()
void NUnit.Framework.Constraints.AttributeExistsConstraintTests.SetUp () inline
References NUnit.Framework.Constraints.ConstraintTestBaseNoData.expectedDescription, NUnit.Framework.Constraints.ConstraintTestBaseNoData.stringRepresentation, and NUnit.Framework.Constraints.ConstraintTestBaseNoData.theConstraint.
NonAttributeThrowsException()
void NUnit.Framework.Constraints.AttributeExistsConstraintTests.NonAttributeThrowsException () inline
References NUnit.Framework.Assert.Throws().
AttributeExistsOnMethodInfo()
void NUnit.Framework.Constraints.AttributeExistsConstraintTests.AttributeExistsOnMethodInfo () inline
References NUnit.Framework.Assert.That().
AttributeTestPropertyValueOnMethodInfo()
void NUnit.Framework.Constraints.AttributeExistsConstraintTests.AttributeTestPropertyValueOnMethodInfo () inline
References NUnit.Framework.Has.Attribute(), and NUnit.Framework.Assert.That().
Member Data Documentation
SuccessData
object [] NUnit.Framework.Constraints.AttributeExistsConstraintTests.SuccessData = new object[] { typeof(AttributeExistsConstraintTests) } static private
FailureData
object [] NUnit.Framework.Constraints.AttributeExistsConstraintTests.FailureData static private
Initial value:
= new object[] {
            new TestCaseData( typeof(D2), "<" + typeof(D2).FullName + ">" ) }
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/AttributeExistsConstraintTests.cs