Doc: IGLib EXTENDED: AForge.Imaging.ColorReduction.MedianCutQuantizer Class Reference
AForge.Imaging.ColorReduction.MedianCutQuantizer Class Reference
Median cut color quantization algorithm.
Public Member Functions
void AddColor (Color color)
Add color to the list of processed colors.
Color[] GetPalette (int colorCount)
Get paletter of the specified size.
void Clear ()
Clear internal state of the color quantization algorithm by clearing the list of colors so far processed.
Private Member Functions
void SplitCubes (List< MedianCutCube > cubes, int count)
Private Attributes
List< Color > colors = new List<Color>()
Detailed Description
Median cut color quantization algorithm.
The class implements median cut color quantization algorithm.
See also ColorImageQuantizer class, which may simplify processing of images.
Sample usage:
// create the color quantization algorithm
IColorQuantizer quantizer = new MedianCutQuantizer();
// process colors (taken from image for example)
for (int i = 0; i < pixelsToProcess; i++)
{
    quantizer.AddColor( /* pixel color *&zwj;/ );
}
// get palette reduced to 16 colors
Color[] palette = quantizer.GetPalette(16);
See also
ColorImageQuantizer
Member Function Documentation
AddColor()
void AForge.Imaging.ColorReduction.MedianCutQuantizer.AddColor (Color color) inline
Add color to the list of processed colors.
Parameters
color Color to add to the internal list.
The method adds the specified color into internal list of processed colors. The list is used later by GetPalette method to build reduced color table of the specified size.
Implements AForge.Imaging.ColorReduction.IColorQuantizer.
References AForge.Imaging.ColorReduction.MedianCutQuantizer.colors.
GetPalette()
Color [] AForge.Imaging.ColorReduction.MedianCutQuantizer.GetPalette (int colorCount) inline
Get paletter of the specified size.
Parameters
colorCount Palette size to get.
Returns
Returns reduced palette of the specified size, which covers colors processed so far.
The method must be called after continuously calling AddColor method and returns reduced color palette for colors accumulated/processed so far.
Implements AForge.Imaging.ColorReduction.IColorQuantizer.
References AForge.Imaging.ColorReduction.MedianCutQuantizer.colors, and AForge.Imaging.ColorReduction.MedianCutQuantizer.SplitCubes().
Clear()
void AForge.Imaging.ColorReduction.MedianCutQuantizer.Clear () inline
Clear internal state of the color quantization algorithm by clearing the list of colors so far processed.
Implements AForge.Imaging.ColorReduction.IColorQuantizer.
References AForge.Imaging.ColorReduction.MedianCutQuantizer.colors.
SplitCubes()
void AForge.Imaging.ColorReduction.MedianCutQuantizer.SplitCubes (List< MedianCutCube > cubes, int count) inline private
References AForge.Imaging.RGB.B, AForge.Imaging.RGB.G, and AForge.Imaging.RGB.R.
Referenced by AForge.Imaging.ColorReduction.MedianCutQuantizer.GetPalette().
Member Data Documentation
colors
List<Color> AForge.Imaging.ColorReduction.MedianCutQuantizer.colors = new List<Color>() private
Referenced by AForge.Imaging.ColorReduction.MedianCutQuantizer.AddColor(), AForge.Imaging.ColorReduction.MedianCutQuantizer.Clear(), and AForge.Imaging.ColorReduction.MedianCutQuantizer.GetPalette().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Color Reduction/MedianCutQuantizer.cs