Doc: IGLib EXTENDED: NUnit.Framework.Assertions.ListContentsTests Class Reference
NUnit.Framework.Assertions.ListContentsTests Class Reference
Summary description for ListContentsTests.
Public Member Functions
void ArraySucceeds ()
void ArrayFails ()
void EmptyArrayFails ()
void NullArrayIsError ()
void ArrayListSucceeds ()
void ArrayListFails ()
void DifferentTypesMayBeEqual ()
Static Private Attributes
static readonly object[] testArray = { "abc", 123, "xyz" }
Detailed Description
Summary description for ListContentsTests.
Member Function Documentation
ArraySucceeds()
void NUnit.Framework.Assertions.ListContentsTests.ArraySucceeds () inline
References NUnit.Framework.Assert.Contains(), and NUnit.Framework.Assertions.ListContentsTests.testArray.
ArrayFails()
void NUnit.Framework.Assertions.ListContentsTests.ArrayFails () inline
References NUnit.Framework.Assert.Contains(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assertions.ListContentsTests.testArray, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
EmptyArrayFails()
void NUnit.Framework.Assertions.ListContentsTests.EmptyArrayFails () inline
References NUnit.Framework.Assert.Contains(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
NullArrayIsError()
void NUnit.Framework.Assertions.ListContentsTests.NullArrayIsError () inline
References NUnit.Framework.Assert.Contains(), and NUnit.Framework.Assert.Throws().
ArrayListSucceeds()
void NUnit.Framework.Assertions.ListContentsTests.ArrayListSucceeds () inline
References NUnit.Framework.Assert.Contains(), and NUnit.Framework.Assertions.ListContentsTests.testArray.
ArrayListFails()
void NUnit.Framework.Assertions.ListContentsTests.ArrayListFails () inline
References NUnit.Framework.Assert.Contains(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assertions.ListContentsTests.testArray, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
DifferentTypesMayBeEqual()
void NUnit.Framework.Assertions.ListContentsTests.DifferentTypesMayBeEqual () inline
References NUnit.Framework.Assert.Contains(), and NUnit.Framework.Assertions.ListContentsTests.testArray.
Member Data Documentation
testArray
readonly object [] NUnit.Framework.Assertions.ListContentsTests.testArray = { "abc", 123, "xyz" } static private
Referenced by NUnit.Framework.Assertions.ListContentsTests.ArrayFails(), NUnit.Framework.Assertions.ListContentsTests.ArrayListFails(), NUnit.Framework.Assertions.ListContentsTests.ArrayListSucceeds(), NUnit.Framework.Assertions.ListContentsTests.ArraySucceeds(), and NUnit.Framework.Assertions.ListContentsTests.DifferentTypesMayBeEqual().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/ListContentsTests.cs