Doc: IGLib EXTENDED: IG.Neural.NeuralTrainingResultsPlotter1 Class Reference
IG.Neural.NeuralTrainingResultsPlotter1 Class Reference
Public Member Functions
NeuralTrainingResultsPlotter1 (List< NeuralTrainingParameters > results)
virtual void ApplyPlotSettingsCurveRGB (PlotterZedGraph plotter, PlotZedgraphCurve plot, double r, double g, double b)
Applies basic plot settings for basic kinds of curve plots where groups of curves are plotted.
virtual void ApplyPlotVerticalCurve (PlotterZedGraph plotter, PlotZedgraphCurve plot)
virtual void ApplyPlotSettingsConvergence (PlotterZedGraph plotter, PlotZedgraphCurve plot, int whichOutput, int numOutputs)
Applies basic plot settings for basic kinds of curve plots.
virtual void ApplyPlotSettingsCurveBlueRed (PlotterZedGraph plotter, PlotZedgraphCurve plot, int i, int max)
Applies basic plot settings for basic kinds of curve plots where groups of curves are plotted.
virtual void ApplyPlotSettingsCurve (PlotterZedGraph plotter, PlotZedgraphCurve plot, int i, int max, System.Drawing.Color colorFrom, System.Drawing.Color colorTo)
Static Public Member Functions
static void PlotConvergenceTrainingRms (NeuralTrainingParameters results)
Plots convergence for Training Rms error.
static void PlotConvergenceTrainingRms (NeuralTrainingParameters results, int numBoundles)
Plots convergence for Training Rms error.
static void PlotConvergenceTrainingRms (List< NeuralTrainingParameters > results)
Plots convergence for Training Rms error.
static void PlotConvergenceTrainingRms (List< NeuralTrainingParameters > results, int numBoundles)
Plots convergence for Training Rms error.
static void PlotConvergenceTrainingMax (NeuralTrainingParameters results)
Plots convergence for Training Max error.
static void PlotConvergenceTrainingMax (NeuralTrainingParameters results, int numBoundles)
Plots convergence for Training Max error.
static void PlotConvergenceTrainingMax (List< NeuralTrainingParameters > results)
Plots convergence for Training Max error.
static void PlotConvergenceTrainingMax (List< NeuralTrainingParameters > results, int numBoundles)
Plots convergence for Training Max error.
static void PlotConvergenceVerificationRms (NeuralTrainingParameters results)
Plots convergence for Verification Rms error.
static void PlotConvergenceVerificationRms (NeuralTrainingParameters results, int numBoundles)
Plots convergence for Verification Rms error.
static void PlotConvergenceVerificationRms (List< NeuralTrainingParameters > results)
Plots convergence for Verification Rms error.
static void PlotConvergenceVerificationRms (List< NeuralTrainingParameters > results, int numBoundles)
Plots convergence for Verification Rms error.
static void PlotConvergenceVerificationMax (NeuralTrainingParameters results)
Plots convergence for Verification Max error.
static void PlotConvergenceVerificationMax (NeuralTrainingParameters results, int numBoundles)
Plots convergence for Verification Max error.
static void PlotConvergenceVerificationMax (List< NeuralTrainingParameters > results)
Plots convergence for Verification Max error.
static void PlotConvergenceVerificationMax (List< NeuralTrainingParameters > results, int numBoundles)
Plots convergence for Verification Max error.
static void PlotCompleteConvergence (NeuralTrainingParameters results)
Plots complete convergence for Max And rms error.
static void PlotCompleteConvergence (List< NeuralTrainingParameters > results)
Plots complete convergence for Max And rms error.
static void PlotTrainingTime (List< NeuralTrainingParameters > results)
Plots graph sorted on training time.
Static Public Attributes
static string _optimizationDirectory = ""
Protected Member Functions
virtual void PlotConvergenceTrainingRms (int whichOutput)
Plots a convergence plot for the specified list of errors of the current training results.
virtual void PlotConvergenceTrainingRms (int whichOutput, int numBoundles)
Plots a convergence plot for the specified list of errors of the current training results.
virtual void PlotConvergenceTrainingRms (int whichOutput, int numBoundles, string errorsName, string outputName)
Plots a convergence plot for the specified list of errors of the current training results.
virtual void PlotConvergenceTrainingMax (int whichOutput)
Plots a convergence plot for the specified list of errors of the current training results.
virtual void PlotConvergenceTrainingMax (int whichOutput, int numBoundles)
Plots a convergence plot for the specified list of errors of the current training results.
virtual void PlotConvergenceTrainingMax (int whichOutput, int numBoundles, string errorsName, string outputName)
Plots a convergence plot for the specified list of errors of the current training results.
virtual void PlotConvergenceVerificationRms (int whichOutput)
Parameters
whichOutput Specifies for which output errors are plotted.
virtual void PlotConvergenceVerificationRms (int whichOutput, int numBoundles)
Plots a convergence plot for the specified list of errors of the current training results.
virtual void PlotConvergenceVerificationRms (int whichOutput, int numBoundles, string errorsName, string outputName)
Plots a convergence plot for the specified list of errors of the current training results.
virtual void PlotConvergenceVerificationMax (int whichOutput)
Parameters
whichOutput Specifies for which output errors are plotted.
virtual void PlotConvergenceVerificationMax (int whichOutput, int numBoundles)
Plots a convergence plot for the specified list of errors of the current training results.
virtual void PlotConvergenceVerificationMax (int whichOutput, int numBoundles, string errorsName, string outputName)
Plots a convergence plot for the specified list of errors of the current training results.
virtual void PlotConvergence (List< IVector >[] errors, int whichOutput, string errorName, string outputName)
virtual void PlotConvergence (List< IVector >[] errors, int whichOutput, int numBoundles, string errorName, string outputName)
Plots a convergence plot for the specified list of errors of the current training results.
virtual void PlotTrainingTime ()
Plots a convergence plot all rms lists of errors of the current training results.
virtual void CreatePlots (PlotterZedGraph plotter, List< IVector > yValue, List< int > xValues, string errorName)
Creates plots for all list of errors.
virtual void CreatePlots (PlotterZedGraph plotter, List< IVector >[] yValues, List< int > xValues, int whichOutput, string[] errorNames, System.Drawing.Color colorFrom, System.Drawing.Color colorTo)
Creates plots for all list of errors.
virtual void CreateBoundlesLimitPlot (PlotterZedGraph plotter, List< IVector > numBoundlesPoints)
Create vertical line to define the error convergence sorting point.
virtual double GetMaximumValue (List< IVector > errors, int whichOutput)
Calculates maximum value for the selected item in the ivector and returns maximum value
virtual double GetMinimumValue (List< IVector > errors, int whichOutput)
Calculates minimum value for the selected item in the ivector and returns minimum value
Protected Attributes
List< NeuralTrainingParameters > _resultsList
Static Protected Attributes
static bool _saveGraphs = false
Properties
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
static InputOutputDataDefiniton DataDefinition [get, set]
Definitions of input and output data.
virtual List< NeuralTrainingParameters > ResultsList [get, protected set]
Training results that are used for plotting.
static bool SaveGraphs [get, set]
Save graphs.
static string OptimizationDirectory [get, set]
Optimization directory path.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Member Functions
NeuralTrainingResultsPlotter1 ()
Prevent argumentless constructor.
Private Attributes
object _mainLock = new object()
Static Private Attributes
static InputOutputDataDefiniton _dataDefinition = null
Constructor & Destructor Documentation
NeuralTrainingResultsPlotter1() [1/2]
IG.Neural.NeuralTrainingResultsPlotter1.NeuralTrainingResultsPlotter1 () inline private
Prevent argumentless constructor.
Referenced by IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingMax(), IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingRms(), IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationMax(), IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationRms(), and IG.Neural.NeuralTrainingResultsPlotter1.PlotTrainingTime().
NeuralTrainingResultsPlotter1() [2/2]
IG.Neural.NeuralTrainingResultsPlotter1.NeuralTrainingResultsPlotter1 (List< NeuralTrainingParameters > results) inline
References IG.Neural.NeuralTrainingResultsPlotter1.ResultsList.
Member Function Documentation
ApplyPlotSettingsCurveRGB()
virtual void IG.Neural.NeuralTrainingResultsPlotter1.ApplyPlotSettingsCurveRGB (PlotterZedGraph plotter, PlotZedgraphCurve plot, double r, double g, double b) inline virtual
Applies basic plot settings for basic kinds of curve plots where groups of curves are plotted.
Parameters
plotter Plotter used for plotting graphs for which settings are set.
plot Plot that contains graphic objects.
r Index for red collor.
g Index for green collor.
b Index for blue collor.
$A Tako78 Sep12;
References IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LineWidth, IG.Gr.PlotZedgraphCurve.PointColor, IG.Gr.PlotZedgraphCurve.PointSize, and IG.Gr.PlotZedgraphCurve.PointTypeSymbol.
ApplyPlotVerticalCurve()
virtual void IG.Neural.NeuralTrainingResultsPlotter1.ApplyPlotVerticalCurve (PlotterZedGraph plotter, PlotZedgraphCurve plot) inline virtual
References IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LineDashStyle, IG.Gr.PlotZedgraphCurve.LineWidth, IG.Gr.PlotZedgraphCurve.PointColor, and IG.Gr.PlotZedgraphCurve.PointSize.
Referenced by IG.Neural.NeuralTrainingResultsPlotter1.CreateBoundlesLimitPlot().
ApplyPlotSettingsConvergence()
virtual void IG.Neural.NeuralTrainingResultsPlotter1.ApplyPlotSettingsConvergence (PlotterZedGraph plotter, PlotZedgraphCurve plot, int whichOutput, int numOutputs) inline virtual
Applies basic plot settings for basic kinds of curve plots.
Parameters
plotter Plotter used for plotting graphs for which settings are set.
plot Curve plot that contains graphic objects.
References IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LineWidth, IG.Gr.PlotZedgraphCurve.PointColor, IG.Gr.PlotZedgraphCurve.PointSize, and IG.Gr.PlotZedgraphCurve.PointTypeSymbol.
ApplyPlotSettingsCurveBlueRed()
virtual void IG.Neural.NeuralTrainingResultsPlotter1.ApplyPlotSettingsCurveBlueRed (PlotterZedGraph plotter, PlotZedgraphCurve plot, int i, int max) inline virtual
Applies basic plot settings for basic kinds of curve plots where groups of curves are plotted.
Parameters
plotter Plotter used for plotting graphs for which settings are set.
plot Curve plot that contains graphic objects.
i Current index of the plot (running from 0) for which settings are applied.
max Maximal index of the plot for which settings are applied.
References IG.Lib.ColorScaleBase.Create(), IG.Lib.ColorScaleBase.GetColor(), IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LineWidth, IG.Gr.PlotZedgraphCurve.PointColor, and IG.Gr.PlotZedgraphCurve.PointSize.
ApplyPlotSettingsCurve()
virtual void IG.Neural.NeuralTrainingResultsPlotter1.ApplyPlotSettingsCurve (PlotterZedGraph plotter, PlotZedgraphCurve plot, int i, int max, System.Drawing.Color colorFrom, System.Drawing.Color colorTo) inline virtual
References IG.Lib.ColorScaleBase.Create(), IG.Lib.ColorScaleBase.GetColor(), IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LineWidth, IG.Gr.PlotZedgraphCurve.PointColor, and IG.Gr.PlotZedgraphCurve.PointSize.
Referenced by IG.Neural.NeuralTrainingResultsPlotter1.CreatePlots().
PlotConvergenceTrainingRms() [1/7]
virtual void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingRms (int whichOutput) inline protected virtual
Plots a convergence plot for the specified list of errors of the current training results.
Parameters
whichOutput Specifies for which output errors are plotted.
Referenced by IG.Neural.NeuralTrainingResultsPlotter1.PlotCompleteConvergence(), IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingRms(), and IG.Script.LoadableScriptShellNeuralIT.PlotTrainingRmsError().
PlotConvergenceTrainingRms() [2/7]
virtual void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingRms (int whichOutput, int numBoundles) inline protected virtual
Plots a convergence plot for the specified list of errors of the current training results.
Parameters
whichOutput Specifies for which output errors are plotted.
References IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingRms().
PlotConvergenceTrainingRms() [3/7]
virtual void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingRms (int whichOutput, int numBoundles, string errorsName, string outputName) inline protected virtual
Plots a convergence plot for the specified list of errors of the current training results.
Parameters
whichOutput Specifies for which output errors are plotted.
errorsName Name of errors used as label on the graph's vertical axis. If not specified then a default name is used.
References IG.Num.VectorBase.Copy(), IG.Neural.NeuralTrainingResultsPlotter1.DataDefinition, IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Num.IVector< T >.Length, IG.Num.InputOutputElementDefinition.Name, IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergence(), and IG.Neural.NeuralTrainingResultsPlotter1.ResultsList.
PlotConvergenceTrainingMax() [1/7]
virtual void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingMax (int whichOutput) inline protected virtual
Plots a convergence plot for the specified list of errors of the current training results.
Parameters
whichOutput Specifies for which output errors are plotted.
Referenced by IG.Neural.NeuralTrainingResultsPlotter1.PlotCompleteConvergence(), IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingMax(), and IG.Script.LoadableScriptShellNeuralIT.PlotTrainingMaxError().
PlotConvergenceTrainingMax() [2/7]
virtual void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingMax (int whichOutput, int numBoundles) inline protected virtual
Plots a convergence plot for the specified list of errors of the current training results.
Parameters
whichOutput Specifies for which output errors are plotted.
References IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingMax().
PlotConvergenceTrainingMax() [3/7]
virtual void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingMax (int whichOutput, int numBoundles, string errorsName, string outputName) inline protected virtual
Plots a convergence plot for the specified list of errors of the current training results.
Parameters
whichOutput Specifies for which output errors are plotted.
errorsName Name of errors used as label on the graph's vertical axis. If not specified then a default name is used./param>
References IG.Num.VectorBase.Copy(), IG.Neural.NeuralTrainingResultsPlotter1.DataDefinition, IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Num.IVector< T >.Length, IG.Num.InputOutputElementDefinition.Name, IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergence(), and IG.Neural.NeuralTrainingResultsPlotter1.ResultsList.
PlotConvergenceVerificationRms() [1/7]
virtual void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationRms (int whichOutput) inline protected virtual
Parameters
whichOutput Specifies for which output errors are plotted.
Referenced by IG.Neural.NeuralTrainingResultsPlotter1.PlotCompleteConvergence(), IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationRms(), and IG.Script.LoadableScriptShellNeuralIT.PlotVerificationRmsError().
PlotConvergenceVerificationRms() [2/7]
virtual void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationRms (int whichOutput, int numBoundles) inline protected virtual
Plots a convergence plot for the specified list of errors of the current training results.
Parameters
whichOutput Specifies for which output errors are plotted.
References IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationRms().
PlotConvergenceVerificationRms() [3/7]
virtual void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationRms (int whichOutput, int numBoundles, string errorsName, string outputName) inline protected virtual
Plots a convergence plot for the specified list of errors of the current training results.
Parameters
whichOutput Specifies for which output errors are plotted.
errorsName Name of errors used as label on the graph's vertical axis. If not specified then a default name is used./param>
References IG.Num.VectorBase.Copy(), IG.Neural.NeuralTrainingResultsPlotter1.DataDefinition, IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Num.IVector< T >.Length, IG.Num.InputOutputElementDefinition.Name, IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergence(), and IG.Neural.NeuralTrainingResultsPlotter1.ResultsList.
PlotConvergenceVerificationMax() [1/7]
virtual void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationMax (int whichOutput) inline protected virtual
Parameters
whichOutput Specifies for which output errors are plotted.
Referenced by IG.Neural.NeuralTrainingResultsPlotter1.PlotCompleteConvergence(), IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationMax(), and IG.Script.LoadableScriptShellNeuralIT.PlotVerificationMaxError().
PlotConvergenceVerificationMax() [2/7]
virtual void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationMax (int whichOutput, int numBoundles) inline protected virtual
Plots a convergence plot for the specified list of errors of the current training results.
Parameters
whichOutput Specifies for which output errors are plotted.
References IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationMax().
PlotConvergenceVerificationMax() [3/7]
virtual void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationMax (int whichOutput, int numBoundles, string errorsName, string outputName) inline protected virtual
Plots a convergence plot for the specified list of errors of the current training results.
Parameters
whichOutput Specifies for which output errors are plotted.
errorsName Name of errors used as label on the graph's vertical axis. If not specified then a default name is used./param>
References IG.Num.VectorBase.Copy(), IG.Neural.NeuralTrainingResultsPlotter1.DataDefinition, IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Num.IVector< T >.Length, IG.Num.InputOutputElementDefinition.Name, IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergence(), and IG.Neural.NeuralTrainingResultsPlotter1.ResultsList.
PlotConvergence() [1/2]
virtual void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergence (List< IVector >[] errors, int whichOutput, string errorName, string outputName) inline protected virtual
Referenced by IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingMax(), IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingRms(), IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationMax(), and IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationRms().
PlotConvergence() [2/2]
virtual void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergence (List< IVector >[] errors, int whichOutput, int numBoundles, string errorName, string outputName) inline protected virtual
Plots a convergence plot for the specified list of errors of the current training results.
Parameters
errors List of errors that are plotter, must be consistent with Results.
whichOutput Specifies for which output errors are plotted.
errorName Name of errors used as label on the graph's vertical axis.
Parameters
outputName Name of the output value in the ANN training set. If not specified then a default name is used.
References IG.Neural.NeuralTrainingResultsPlotter1.CreateBoundlesLimitPlot(), IG.Gr.PlotterZedGraph.CreateDefault(), IG.Neural.NeuralTrainingResultsPlotter1.CreatePlots(), IG.Neural.NeuralTrainingResultsPlotter1.GetMaximumValue(), IG.Neural.NeuralTrainingResultsPlotter1.GetMinimumValue(), IG.Gr.ZedGraphWindow.GraphControl, IG.Gr.PlotterZedGraph.GraphPane, IG.Neural.NeuralTrainingResultsPlotter1.OptimizationDirectory, IG.Neural.NeuralTrainingResultsPlotter1.ResultsList, IG.Neural.NeuralTrainingResultsPlotter1.SaveGraphs, IG.Gr.PlotterZedGraph.Title, IG.Gr.PlotterZedGraph.Update(), IG.Gr.PlotterZedGraph.XAxis, IG.Gr.PlotterZedGraph.XAxisLabel, IG.Gr.PlotterZedGraph.YAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabelFont.
PlotTrainingTime() [1/2]
virtual void IG.Neural.NeuralTrainingResultsPlotter1.PlotTrainingTime () inline protected virtual
Plots a convergence plot all rms lists of errors of the current training results.
If not specified then a default name is used.
$A Tako78 Sep12;
References IG.Gr.PlotterZedGraph.CreateDefault(), IG.Neural.NeuralTrainingResultsPlotter1.CreatePlots(), IG.Gr.ZedGraphWindow.GraphControl, IG.Neural.NeuralTrainingResultsPlotter1.ResultsList, IG.Gr.PlotterZedGraph.Title, IG.Gr.PlotterZedGraph.Update(), IG.Gr.PlotterZedGraph.XAxisLabel, IG.Gr.PlotterZedGraph.YAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabelFont.
Referenced by IG.Neural.NeuralTrainingResultsPlotter1.PlotTrainingTime(), and IG.Script.LoadableScriptShellNeuralIT.PlotTrainingTime().
CreatePlots() [1/2]
virtual void IG.Neural.NeuralTrainingResultsPlotter1.CreatePlots (PlotterZedGraph plotter, List< IVector > yValue, List< int > xValues, string errorName) inline protected virtual
Creates plots for all list of errors.
Parameters
plotter
yValue List of errors that are plotter, must be consistent with.
xValues
errorName
Referenced by IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergence(), and IG.Neural.NeuralTrainingResultsPlotter1.PlotTrainingTime().
CreatePlots() [2/2]
virtual void IG.Neural.NeuralTrainingResultsPlotter1.CreatePlots (PlotterZedGraph plotter, List< IVector >[] yValues, List< int > xValues, int whichOutput, string[] errorNames, System.Drawing.Color colorFrom, System.Drawing.Color colorTo) inline protected virtual
Creates plots for all list of errors.
Parameters
plotter
yValues List of errors that are plotter, must be consistent with.
whichOutput Specifies for which output errors are plotted.
errorNames Name of errors used as label on the graph's vertical axis.
colorFrom
colorTo
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Neural.NeuralTrainingResultsPlotter1.ApplyPlotSettingsCurve(), and IG.Neural.NeuralTrainingResultsPlotter1.ResultsList.
CreateBoundlesLimitPlot()
virtual void IG.Neural.NeuralTrainingResultsPlotter1.CreateBoundlesLimitPlot (PlotterZedGraph plotter, List< IVector > numBoundlesPoints) inline protected virtual
Create vertical line to define the error convergence sorting point.
Parameters
plotter
numBoundlesPoints
References IG.Gr.PlotZedgraphCurve.AddPoint(), and IG.Neural.NeuralTrainingResultsPlotter1.ApplyPlotVerticalCurve().
Referenced by IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergence().
GetMaximumValue()
virtual double IG.Neural.NeuralTrainingResultsPlotter1.GetMaximumValue (List< IVector > errors, int whichOutput) inline protected virtual
Calculates maximum value for the selected item in the ivector and returns maximum value
Parameters
errors List of parameters.
whichOutput Selected parameter to be checked.
Returns
Maximum parameter from the list of parameters.
Referenced by IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergence().
GetMinimumValue()
virtual double IG.Neural.NeuralTrainingResultsPlotter1.GetMinimumValue (List< IVector > errors, int whichOutput) inline protected virtual
Calculates minimum value for the selected item in the ivector and returns minimum value
Parameters
errors List of parameters.
whichOutput Selected parameter to be checked.
Returns
Minimum parameter from the list of parameters.
Referenced by IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergence().
PlotConvergenceTrainingRms() [4/7]
static void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingRms (NeuralTrainingParameters results) inline static
Plots convergence for Training Rms error.
Parameters
results Parameters of training procedures.
References IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingRms().
PlotConvergenceTrainingRms() [5/7]
static void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingRms (NeuralTrainingParameters results, int numBoundles) inline static
Plots convergence for Training Rms error.
Parameters
results Parameters of training procedures.
numBoundles Number of bundles where sorting of convergences stars.
References IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingRms().
PlotConvergenceTrainingRms() [6/7]
static void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingRms (List< NeuralTrainingParameters > results) inline static
Plots convergence for Training Rms error.
Parameters
results List of parameters of training procedures.
References IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingRms().
PlotConvergenceTrainingRms() [7/7]
static void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingRms (List< NeuralTrainingParameters > results, int numBoundles) inline static
Plots convergence for Training Rms error.
Parameters
results List of parameters of training procedures.
numBoundles Number of bundles where sorting of convergences stars.
References IG.Neural.NeuralTrainingResultsPlotter1.NeuralTrainingResultsPlotter1(), and IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingRms().
PlotConvergenceTrainingMax() [4/7]
static void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingMax (NeuralTrainingParameters results) inline static
Plots convergence for Training Max error.
Parameters
results Parameters of training procedures.
References IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingMax().
PlotConvergenceTrainingMax() [5/7]
static void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingMax (NeuralTrainingParameters results, int numBoundles) inline static
Plots convergence for Training Max error.
Parameters
results Parameters of training procedures.
numBoundles Number of bundles where sorting of convergences stars.
References IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingMax().
PlotConvergenceTrainingMax() [6/7]
static void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingMax (List< NeuralTrainingParameters > results) inline static
Plots convergence for Training Max error.
Parameters
results List of parameters of training procedures.
References IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingMax().
PlotConvergenceTrainingMax() [7/7]
static void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingMax (List< NeuralTrainingParameters > results, int numBoundles) inline static
Plots convergence for Training Max error.
Parameters
results List of parameters of training procedures.
numBoundles Number of bundles where sorting of convergences stars.
References IG.Neural.NeuralTrainingResultsPlotter1.NeuralTrainingResultsPlotter1(), and IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingMax().
PlotConvergenceVerificationRms() [4/7]
static void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationRms (NeuralTrainingParameters results) inline static
Plots convergence for Verification Rms error.
Parameters
results Parameters of training procedures.
References IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationRms().
PlotConvergenceVerificationRms() [5/7]
static void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationRms (NeuralTrainingParameters results, int numBoundles) inline static
Plots convergence for Verification Rms error.
Parameters
results Parameters of training procedures.
numBoundles Number of bundles where sorting of convergences stars.
References IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationRms().
PlotConvergenceVerificationRms() [6/7]
static void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationRms (List< NeuralTrainingParameters > results) inline static
Plots convergence for Verification Rms error.
Parameters
results List of parameters of training procedures.
References IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationRms().
PlotConvergenceVerificationRms() [7/7]
static void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationRms (List< NeuralTrainingParameters > results, int numBoundles) inline static
Plots convergence for Verification Rms error.
Parameters
results List of parameters of training procedures.
numBoundles Number of bundles where sorting of convergences stars.
References IG.Neural.NeuralTrainingResultsPlotter1.NeuralTrainingResultsPlotter1(), and IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationRms().
PlotConvergenceVerificationMax() [4/7]
static void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationMax (NeuralTrainingParameters results) inline static
Plots convergence for Verification Max error.
Parameters
results Parameters of training procedures.
References IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationMax().
PlotConvergenceVerificationMax() [5/7]
static void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationMax (NeuralTrainingParameters results, int numBoundles) inline static
Plots convergence for Verification Max error.
Parameters
results Parameters of training procedures.
numBoundles Number of bundles where sorting of convergences stars.
References IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationMax().
PlotConvergenceVerificationMax() [6/7]
static void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationMax (List< NeuralTrainingParameters > results) inline static
Plots convergence for Verification Max error.
Parameters
results List of parameters of training procedures.
References IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationMax().
PlotConvergenceVerificationMax() [7/7]
static void IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationMax (List< NeuralTrainingParameters > results, int numBoundles) inline static
Plots convergence for Verification Max error.
Parameters
results List of parameters of training procedures.
numBoundles Number of bundles where sorting of convergences stars.
References IG.Neural.NeuralTrainingResultsPlotter1.NeuralTrainingResultsPlotter1(), and IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationMax().
PlotCompleteConvergence() [1/2]
static void IG.Neural.NeuralTrainingResultsPlotter1.PlotCompleteConvergence (NeuralTrainingParameters results) inline static
Plots complete convergence for Max And rms error.
Parameters
results Parameters of training procedures.
PlotCompleteConvergence() [2/2]
static void IG.Neural.NeuralTrainingResultsPlotter1.PlotCompleteConvergence (List< NeuralTrainingParameters > results) inline static
Plots complete convergence for Max And rms error.
Parameters
results List of parameters of training procedures.
References IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingMax(), IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingRms(), IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationMax(), and IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationRms().
PlotTrainingTime() [2/2]
static void IG.Neural.NeuralTrainingResultsPlotter1.PlotTrainingTime (List< NeuralTrainingParameters > results) inline static
Plots graph sorted on training time.
Parameters
results List of parameters of training procedures.
References IG.Neural.NeuralTrainingResultsPlotter1.NeuralTrainingResultsPlotter1(), and IG.Neural.NeuralTrainingResultsPlotter1.PlotTrainingTime().
Member Data Documentation
_mainLock
object IG.Neural.NeuralTrainingResultsPlotter1._mainLock = new object() private
_dataDefinition
InputOutputDataDefiniton IG.Neural.NeuralTrainingResultsPlotter1._dataDefinition = null static private
_resultsList
List<NeuralTrainingParameters> IG.Neural.NeuralTrainingResultsPlotter1._resultsList protected
_saveGraphs
bool IG.Neural.NeuralTrainingResultsPlotter1._saveGraphs = false static protected
_optimizationDirectory
string IG.Neural.NeuralTrainingResultsPlotter1._optimizationDirectory = "" static
Property Documentation
Lock
object IG.Neural.NeuralTrainingResultsPlotter1.Lock get
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
DataDefinition
InputOutputDataDefiniton IG.Neural.NeuralTrainingResultsPlotter1.DataDefinition static get set
Definitions of input and output data.
$A Tako78 Sep12;
Referenced by IG.Script.LoadableScriptShellNeuralIT.PlotConvergence(), IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingMax(), IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingRms(), IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationMax(), IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationRms(), and IG.Script.LoadableScriptShellNeuralIT.PlotTrainingTime().
ResultsList
virtual List<NeuralTrainingParameters> IG.Neural.NeuralTrainingResultsPlotter1.ResultsList get protected set
Training results that are used for plotting.
Referenced by IG.Neural.NeuralTrainingResultsPlotter1.CreatePlots(), IG.Neural.NeuralTrainingResultsPlotter1.NeuralTrainingResultsPlotter1(), IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergence(), IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingMax(), IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceTrainingRms(), IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationMax(), IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergenceVerificationRms(), and IG.Neural.NeuralTrainingResultsPlotter1.PlotTrainingTime().
SaveGraphs
bool IG.Neural.NeuralTrainingResultsPlotter1.SaveGraphs static get set
Save graphs.
Referenced by IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergence(), and IG.Script.LoadableScriptShellNeuralIT.PlotConvergence().
OptimizationDirectory
string IG.Neural.NeuralTrainingResultsPlotter1.OptimizationDirectory static get set
Optimization directory path.
Referenced by IG.Neural.NeuralTrainingResultsPlotter1.PlotConvergence(), and IG.Script.LoadableScriptShellNeuralIT.PlotConvergence().
The documentation for this class was generated from the following file:
shelldev/lib/extended/LibNeuralExt/scripts_presentation/NeuralTrainingResultsPlotter.cs