Doc: IGLib EXTENDED: NUnit.TestData.AssertCountFixture Class Reference
NUnit.TestData.AssertCountFixture Class Reference
Public Member Functions
void BooleanAssert ()
void ConstraintAssert ()
void ThreeAsserts ()
Static Public Attributes
static readonly int ExpectedAssertCount = 5
Member Function Documentation
BooleanAssert()
void NUnit.TestData.AssertCountFixture.BooleanAssert () inline
References NUnit.Framework.Assert.That().
ConstraintAssert()
void NUnit.TestData.AssertCountFixture.ConstraintAssert () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
ThreeAsserts()
void NUnit.TestData.AssertCountFixture.ThreeAsserts () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
Member Data Documentation
ExpectedAssertCount
readonly int NUnit.TestData.AssertCountFixture.ExpectedAssertCount = 5 static
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/testdata/AssertCountFixture.cs