Doc: IGLib EXTENDED: NUnitLite.Tests.CommandLineTests Class Reference
NUnitLite.Tests.CommandLineTests Class Reference
Classes
class DefaultOptionsProviderStub
Public Member Functions
void NoInputFiles ()
void CanRecognizeBooleanOptions (string propertyName, string pattern)
void CanRecognizeStringOptions (string propertyName, string pattern, string[] goodValues, string[] badValues)
void CanRecognizeLowerCaseOptionValues (string propertyName, string optionName, string[] canonicalValues)
void CanRecognizeIntOptions (string propertyName, string pattern)
void MissingValuesAreReported (string option)
void AssemblyName ()
void AssemblyAloneIsValid ()
void InvalidOption ()
void InvalidCommandLineParms ()
void TimeoutIsMinusOneIfNoOptionIsProvided ()
void TimeoutThrowsExceptionIfOptionHasNoValue ()
void TimeoutParsesIntValueCorrectly ()
void TimeoutCausesErrorIfValueIsNotInteger ()
void FileNameWithoutResultOptionLooksLikeParameter ()
void ResultOptionWithFilePath ()
void ResultOptionWithFilePathAndFormat ()
void ResultOptionWithFilePathAndTransform ()
void ResultOptionWithoutFileNameIsInvalid ()
void ResultOptionMayBeRepeated ()
void DefaultResultSpecification ()
void NoResultSuppressesDefaultResultSpecification ()
void NoResultSuppressesAllResultSpecifications ()
void ExploreOptionWithoutPath ()
void ExploreOptionWithFilePath ()
void ExploreOptionWithFilePathAndFormat ()
void ExploreOptionWithFilePathAndTransform ()
void ExploreOptionWithFilePathUsingEqualSign ()
void ShouldSetTeamCityFlagAccordingToArgsAndDefauls (bool hasTeamcityInCmd, bool? defaultTeamcity, bool expectedTeamCity)
Static Private Member Functions
static PropertyInfo GetPropertyInfo (string propertyName)
Member Function Documentation
NoInputFiles()
void NUnitLite.Tests.CommandLineTests.NoInputFiles () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.True().
CanRecognizeBooleanOptions()
void NUnitLite.Tests.CommandLineTests.CanRecognizeBooleanOptions (string propertyName, string pattern) inline
References NUnit.Framework.Assert.AreEqual(), and NUnitLite.Tests.CommandLineTests.GetPropertyInfo().
CanRecognizeStringOptions()
void NUnitLite.Tests.CommandLineTests.CanRecognizeStringOptions (string propertyName, string pattern, string[] goodValues, string[] badValues) inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Assert.False(), NUnitLite.Tests.CommandLineTests.GetPropertyInfo(), and NUnit.Framework.Assert.True().
CanRecognizeLowerCaseOptionValues()
void NUnitLite.Tests.CommandLineTests.CanRecognizeLowerCaseOptionValues (string propertyName, string optionName, string[] canonicalValues) inline
References NUnit.Framework.Assert.AreEqual(), NUnitLite.Tests.CommandLineTests.GetPropertyInfo(), and NUnit.Framework.Assert.True().
CanRecognizeIntOptions()
void NUnitLite.Tests.CommandLineTests.CanRecognizeIntOptions (string propertyName, string pattern) inline
References NUnit.Framework.Assert.AreEqual(), and NUnitLite.Tests.CommandLineTests.GetPropertyInfo().
MissingValuesAreReported()
void NUnitLite.Tests.CommandLineTests.MissingValuesAreReported (string option) inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.False().
AssemblyName()
void NUnitLite.Tests.CommandLineTests.AssemblyName () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.True().
AssemblyAloneIsValid()
void NUnitLite.Tests.CommandLineTests.AssemblyAloneIsValid () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.True().
InvalidOption()
void NUnitLite.Tests.CommandLineTests.InvalidOption () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.False().
InvalidCommandLineParms()
void NUnitLite.Tests.CommandLineTests.InvalidCommandLineParms () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.False().
TimeoutIsMinusOneIfNoOptionIsProvided()
void NUnitLite.Tests.CommandLineTests.TimeoutIsMinusOneIfNoOptionIsProvided () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.True().
TimeoutThrowsExceptionIfOptionHasNoValue()
void NUnitLite.Tests.CommandLineTests.TimeoutThrowsExceptionIfOptionHasNoValue () inline
References NUnit.Framework.Assert.Throws().
TimeoutParsesIntValueCorrectly()
void NUnitLite.Tests.CommandLineTests.TimeoutParsesIntValueCorrectly () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.True().
TimeoutCausesErrorIfValueIsNotInteger()
void NUnitLite.Tests.CommandLineTests.TimeoutCausesErrorIfValueIsNotInteger () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.False().
FileNameWithoutResultOptionLooksLikeParameter()
void NUnitLite.Tests.CommandLineTests.FileNameWithoutResultOptionLooksLikeParameter () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.True().
ResultOptionWithFilePath()
void NUnitLite.Tests.CommandLineTests.ResultOptionWithFilePath () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.OutputSpecification.Format, NUnit.Framework.Assert.Null(), NUnit.Common.OutputSpecification.OutputPath, NUnit.Common.OutputSpecification.Transform, and NUnit.Framework.Assert.True().
ResultOptionWithFilePathAndFormat()
void NUnitLite.Tests.CommandLineTests.ResultOptionWithFilePathAndFormat () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.OutputSpecification.Format, NUnit.Framework.Assert.Null(), NUnit.Common.OutputSpecification.OutputPath, NUnit.Common.OutputSpecification.Transform, and NUnit.Framework.Assert.True().
ResultOptionWithFilePathAndTransform()
void NUnitLite.Tests.CommandLineTests.ResultOptionWithFilePathAndTransform () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.OutputSpecification.Format, NUnit.Common.OutputSpecification.OutputPath, NUnit.Common.OutputSpecification.Transform, and NUnit.Framework.Assert.True().
ResultOptionWithoutFileNameIsInvalid()
void NUnitLite.Tests.CommandLineTests.ResultOptionWithoutFileNameIsInvalid () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.False().
ResultOptionMayBeRepeated()
void NUnitLite.Tests.CommandLineTests.ResultOptionMayBeRepeated () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Assert.Null(), and NUnit.Framework.Assert.True().
DefaultResultSpecification()
void NUnitLite.Tests.CommandLineTests.DefaultResultSpecification () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.Null().
NoResultSuppressesDefaultResultSpecification()
void NUnitLite.Tests.CommandLineTests.NoResultSuppressesDefaultResultSpecification () inline
References NUnit.Framework.Assert.AreEqual().
NoResultSuppressesAllResultSpecifications()
void NUnitLite.Tests.CommandLineTests.NoResultSuppressesAllResultSpecifications () inline
References NUnit.Framework.Assert.AreEqual().
ExploreOptionWithoutPath()
void NUnitLite.Tests.CommandLineTests.ExploreOptionWithoutPath () inline
References NUnit.Framework.Assert.True().
ExploreOptionWithFilePath()
void NUnitLite.Tests.CommandLineTests.ExploreOptionWithFilePath () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.OutputSpecification.Format, NUnit.Framework.Assert.Null(), NUnit.Common.OutputSpecification.OutputPath, NUnit.Common.OutputSpecification.Transform, and NUnit.Framework.Assert.True().
ExploreOptionWithFilePathAndFormat()
void NUnitLite.Tests.CommandLineTests.ExploreOptionWithFilePathAndFormat () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.OutputSpecification.Format, NUnit.Framework.Assert.Null(), NUnit.Common.OutputSpecification.OutputPath, NUnit.Common.OutputSpecification.Transform, and NUnit.Framework.Assert.True().
ExploreOptionWithFilePathAndTransform()
void NUnitLite.Tests.CommandLineTests.ExploreOptionWithFilePathAndTransform () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Common.OutputSpecification.Format, NUnit.Common.OutputSpecification.OutputPath, NUnit.Common.OutputSpecification.Transform, and NUnit.Framework.Assert.True().
ExploreOptionWithFilePathUsingEqualSign()
void NUnitLite.Tests.CommandLineTests.ExploreOptionWithFilePathUsingEqualSign () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.True().
ShouldSetTeamCityFlagAccordingToArgsAndDefauls()
void NUnitLite.Tests.CommandLineTests.ShouldSetTeamCityFlagAccordingToArgsAndDefauls (bool hasTeamcityInCmd, bool? defaultTeamcity, bool expectedTeamCity) inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Common.CommandLineOptions.TeamCity.
GetPropertyInfo()
static PropertyInfo NUnitLite.Tests.CommandLineTests.GetPropertyInfo (string propertyName) inline static private
References NUnit.Framework.Assert.IsNotNull().
Referenced by NUnitLite.Tests.CommandLineTests.CanRecognizeBooleanOptions(), NUnitLite.Tests.CommandLineTests.CanRecognizeIntOptions(), NUnitLite.Tests.CommandLineTests.CanRecognizeLowerCaseOptionValues(), and NUnitLite.Tests.CommandLineTests.CanRecognizeStringOptions().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/nunitlite.tests/CommandLineTests.cs