Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAS2 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAS2 Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAS2 ()
void Run (double F, double G, double H, ref double SSMIN, ref double SSMAX)
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
const double TWO = 2.0E0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAS2 computes the singular values of the 2-by-2 matrix [ F G ] [ 0 H ]. On return, SSMIN is the smaller singular value and SSMAX is the larger singular value.
/summary>
Constructor & Destructor Documentation
DLAS2()
DotNumerics.LinearAlgebra.CSLapack.DLAS2.DLAS2 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAS2.Run (double F, double G, double H, ref double SSMIN, ref double SSMAX) inline
Purpose
DLAS2 computes the singular values of the 2-by-2 matrix [ F G ] [ 0 H ]. On return, SSMIN is the smaller singular value and SSMAX is the larger singular value.
/summary>
Parameters
F (input) DOUBLE PRECISION The (1,1) element of the 2-by-2 matrix. /param>
Parameters
G (input) DOUBLE PRECISION The (1,2) element of the 2-by-2 matrix. /param>
Parameters
H (input) DOUBLE PRECISION The (2,2) element of the 2-by-2 matrix. /param>
Parameters
SSMIN (output) DOUBLE PRECISION The smaller singular value. /param>
Parameters
SSMAX (output) DOUBLE PRECISION The larger singular value. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLAS2.ONE, DotNumerics.LinearAlgebra.CSLapack.DLAS2.TWO, and DotNumerics.LinearAlgebra.CSLapack.DLAS2.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAPLL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASQ1.Run(), and DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run().
Member Data Documentation
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAS2.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAS2.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAS2.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAS2.Run().
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DLAS2.TWO = 2.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAS2.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlas2.cs