Doc: IGLib EXTENDED: Test.UncertainMathTest Class Reference
Test.UncertainMathTest Class Reference
Public Member Functions
void UncertainMathValueAgreement ()
void UncertainMathSqrtSquare ()
void UncertainMathLogExp ()
void UncertainMathCosACos ()
Private Attributes
UncertainValue a = new UncertainValue(2.0, 0.5)
Member Function Documentation
UncertainMathValueAgreement()
void Test.UncertainMathTest.UncertainMathValueAgreement () inline
References Test.UncertainMathTest.a, Meta.Numerics.UncertainMath.Atan(), Meta.Numerics.UncertainMath.Cos(), Meta.Numerics.UncertainMath.Cosh(), Meta.Numerics.UncertainMath.Exp(), Meta.Numerics.UncertainMath.Log(), Meta.Numerics.UncertainMath.Sin(), Meta.Numerics.UncertainMath.Sinh(), Meta.Numerics.UncertainMath.Sqrt(), Meta.Numerics.UncertainMath.Tan(), Meta.Numerics.UncertainMath.Tanh(), and Meta.Numerics.UncertainValue.Value.
UncertainMathSqrtSquare()
void Test.UncertainMathTest.UncertainMathSqrtSquare () inline
References Test.UncertainMathTest.a, Meta.Numerics.UncertainMath.Pow(), Meta.Numerics.UncertainValue.RelativeUncertainty, Meta.Numerics.UncertainMath.Sqrt(), Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
UncertainMathLogExp()
void Test.UncertainMathTest.UncertainMathLogExp () inline
References Test.UncertainMathTest.a, Meta.Numerics.UncertainMath.Exp(), Meta.Numerics.UncertainMath.Log(), Meta.Numerics.UncertainValue.RelativeUncertainty, and Meta.Numerics.UncertainValue.Uncertainty.
UncertainMathCosACos()
void Test.UncertainMathTest.UncertainMathCosACos () inline
References Meta.Numerics.UncertainMath.Acos(), Meta.Numerics.UncertainMath.Cos(), Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
Member Data Documentation
a
UncertainValue Test.UncertainMathTest.a = new UncertainValue(2.0, 0.5) private
Referenced by Test.UncertainMathTest.UncertainMathLogExp(), Test.UncertainMathTest.UncertainMathSqrtSquare(), and Test.UncertainMathTest.UncertainMathValueAgreement().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/UncertainMathTest.cs