Doc: IGLib EXTENDED: NUnit.Framework.Attributes.ApplyToTestTests Class Reference
NUnit.Framework.Attributes.ApplyToTestTests Class Reference
Public Member Functions
void SetUp ()
void CategoryAttributeSetsCategory ()
void CategoryAttributeSetsCategoryOnNonRunnableTest ()
void CategoryAttributeSetsMultipleCategories ()
void DescriptionAttributeSetsDescription ()
void DescriptionAttributeSetsDescriptionOnNonRunnableTest ()
void IgnoreAttributeIgnoresTest ()
void IgnoreAttributeSetsIgnoreReason ()
void IgnoreAttributeDoesNotAffectNonRunnableTest ()
void IgnoreAttributeIgnoresTestUntilDateSpecified ()
void IgnoreAttributeIgnoresTestUntilDateTimeSpecified ()
void IgnoreAttributeMarksTestAsRunnableAfterUntilDatePasses ()
void IgnoreAttributeUntilSetsTheReason (string date)
void IgnoreAttributeWithInvalidDateThrowsException ()
void IgnoreAttributeWithUntilAddsIgnoreUntilDateProperty ()
void IgnoreAttributeWithUntilAddsIgnoreUntilDatePropertyPastUntilDate ()
void IgnoreAttributeWithExplicitIgnoresTest ()
void ExplicitAttributeMakesTestExplicit ()
void ExplicitAttributeSetsIgnoreReason ()
void ExplicitAttributeDoesNotAffectNonRunnableTest ()
void ExplicitAttributeWithIgnoreIgnoresTest ()
void CombinatorialAttributeSetsJoinType ()
void CombinatorialAttributeSetsJoinTypeOnNonRunnableTest ()
void CultureAttributeIncludingCurrentCultureRunsTest ()
void CultureAttributeDoesNotAffectNonRunnableTest ()
void CultureAttributeExcludingCurrentCultureSkipsTest ()
void CultureAttributeIncludingOtherCultureSkipsTest ()
void CultureAttributeExcludingOtherCultureRunsTest ()
void CultureAttributeWithMultipleCulturesIncluded ()
void MaxTimeAttributeSetsMaxTime ()
void MaxTimeAttributeSetsMaxTimeOnNonRunnableTest ()
void PairwiseAttributeSetsJoinType ()
void PairwiseAttributeSetsJoinTypeOnNonRunnableTest ()
void PlatformAttributeRunsTest ()
void PlatformAttributeSkipsTest ()
void PlatformAttributeDoesNotAffectNonRunnableTest ()
void RepeatAttributeSetsRepeatCount ()
void RepeatAttributeSetsRepeatCountOnNonRunnableTest ()
void RequiresMTAAttributeSetsApartmentState ()
void RequiresMTAAttributeSetsApartmentStateOnNonRunnableTest ()
void RequiresSTAAttributeSetsApartmentState ()
void RequiresSTAAttributeSetsApartmentStateOnNonRunnableTest ()
void RequiresThreadAttributeSetsRequiresThread ()
void RequiresThreadAttributeSetsRequiresThreadOnNonRunnableTest ()
void RequiresThreadAttributeMaySetApartmentState ()
void SequentialAttributeSetsJoinType ()
void SequentialAttributeSetsJoinTypeOnNonRunnableTest ()
void SetCultureAttributeSetsSetCultureProperty ()
void SetCultureAttributeSetsSetCulturePropertyOnNonRunnableTest ()
void SetUICultureAttributeSetsSetUICultureProperty ()
void SetUICultureAttributeSetsSetUICulturePropertyOnNonRunnableTest ()
Private Member Functions
string GetMyPlatform ()
Private Attributes
Test test
Member Function Documentation
SetUp()
void NUnit.Framework.Attributes.ApplyToTestTests.SetUp () inline
References NUnit.Framework.Internal.Test.RunState, and NUnit.Framework.Attributes.ApplyToTestTests.test.
CategoryAttributeSetsCategory()
void NUnit.Framework.Attributes.ApplyToTestTests.CategoryAttributeSetsCategory () inline
References NUnit.Framework.CategoryAttribute.ApplyToTest(), NUnit.Framework.Internal.PropertyNames.Category, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
CategoryAttributeSetsCategoryOnNonRunnableTest()
void NUnit.Framework.Attributes.ApplyToTestTests.CategoryAttributeSetsCategoryOnNonRunnableTest () inline
References NUnit.Framework.CategoryAttribute.ApplyToTest(), NUnit.Framework.Internal.PropertyNames.Category, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
CategoryAttributeSetsMultipleCategories()
void NUnit.Framework.Attributes.ApplyToTestTests.CategoryAttributeSetsMultipleCategories () inline
References NUnit.Framework.CategoryAttribute.ApplyToTest(), NUnit.Framework.Internal.PropertyNames.Category, NUnit.Framework.Is.EquivalentTo(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
DescriptionAttributeSetsDescription()
void NUnit.Framework.Attributes.ApplyToTestTests.DescriptionAttributeSetsDescription () inline
References NUnit.Framework.PropertyAttribute.ApplyToTest(), NUnit.Framework.Internal.PropertyNames.Description, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
DescriptionAttributeSetsDescriptionOnNonRunnableTest()
void NUnit.Framework.Attributes.ApplyToTestTests.DescriptionAttributeSetsDescriptionOnNonRunnableTest () inline
References NUnit.Framework.PropertyAttribute.ApplyToTest(), NUnit.Framework.Internal.PropertyNames.Description, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
IgnoreAttributeIgnoresTest()
void NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeIgnoresTest () inline
References NUnit.Framework.IgnoreAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
IgnoreAttributeSetsIgnoreReason()
void NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeSetsIgnoreReason () inline
References NUnit.Framework.IgnoreAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Internal.PropertyNames.SkipReason, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
IgnoreAttributeDoesNotAffectNonRunnableTest()
void NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeDoesNotAffectNonRunnableTest () inline
References NUnit.Framework.IgnoreAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Interfaces.IPropertyBag.Set(), NUnit.Framework.Internal.PropertyNames.SkipReason, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
IgnoreAttributeIgnoresTestUntilDateSpecified()
void NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeIgnoresTestUntilDateSpecified () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
IgnoreAttributeIgnoresTestUntilDateTimeSpecified()
void NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeIgnoresTestUntilDateTimeSpecified () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
IgnoreAttributeMarksTestAsRunnableAfterUntilDatePasses()
void NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeMarksTestAsRunnableAfterUntilDatePasses () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
IgnoreAttributeUntilSetsTheReason()
void NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeUntilSetsTheReason (string date) inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.PropertyNames.SkipReason, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
IgnoreAttributeWithInvalidDateThrowsException()
void NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeWithInvalidDateThrowsException () inline
References NUnit.Framework.Assert.Throws().
IgnoreAttributeWithUntilAddsIgnoreUntilDateProperty()
void NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeWithUntilAddsIgnoreUntilDateProperty () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.PropertyNames.IgnoreUntilDate, NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
IgnoreAttributeWithUntilAddsIgnoreUntilDatePropertyPastUntilDate()
void NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeWithUntilAddsIgnoreUntilDatePropertyPastUntilDate () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.PropertyNames.IgnoreUntilDate, NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
IgnoreAttributeWithExplicitIgnoresTest()
void NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeWithExplicitIgnoresTest () inline
References NUnit.Framework.ExplicitAttribute.ApplyToTest(), NUnit.Framework.IgnoreAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
ExplicitAttributeMakesTestExplicit()
void NUnit.Framework.Attributes.ApplyToTestTests.ExplicitAttributeMakesTestExplicit () inline
References NUnit.Framework.ExplicitAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
ExplicitAttributeSetsIgnoreReason()
void NUnit.Framework.Attributes.ApplyToTestTests.ExplicitAttributeSetsIgnoreReason () inline
References NUnit.Framework.ExplicitAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Internal.PropertyNames.SkipReason, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
ExplicitAttributeDoesNotAffectNonRunnableTest()
void NUnit.Framework.Attributes.ApplyToTestTests.ExplicitAttributeDoesNotAffectNonRunnableTest () inline
References NUnit.Framework.ExplicitAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Interfaces.IPropertyBag.Set(), NUnit.Framework.Internal.PropertyNames.SkipReason, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
ExplicitAttributeWithIgnoreIgnoresTest()
void NUnit.Framework.Attributes.ApplyToTestTests.ExplicitAttributeWithIgnoreIgnoresTest () inline
References NUnit.Framework.ExplicitAttribute.ApplyToTest(), NUnit.Framework.IgnoreAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
CombinatorialAttributeSetsJoinType()
void NUnit.Framework.Attributes.ApplyToTestTests.CombinatorialAttributeSetsJoinType () inline
References NUnit.Framework.CombiningStrategyAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.PropertyNames.JoinType, NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
CombinatorialAttributeSetsJoinTypeOnNonRunnableTest()
void NUnit.Framework.Attributes.ApplyToTestTests.CombinatorialAttributeSetsJoinTypeOnNonRunnableTest () inline
References NUnit.Framework.CombiningStrategyAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.PropertyNames.JoinType, NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
CultureAttributeIncludingCurrentCultureRunsTest()
void NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeIncludingCurrentCultureRunsTest () inline
References NUnit.Framework.CultureAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
CultureAttributeDoesNotAffectNonRunnableTest()
void NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeDoesNotAffectNonRunnableTest () inline
References NUnit.Framework.CultureAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
CultureAttributeExcludingCurrentCultureSkipsTest()
void NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeExcludingCurrentCultureSkipsTest () inline
References NUnit.Framework.CultureAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.IncludeExcludeAttribute.Exclude, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Internal.PropertyNames.SkipReason, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
CultureAttributeIncludingOtherCultureSkipsTest()
void NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeIncludingOtherCultureSkipsTest () inline
References NUnit.Framework.CultureAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Internal.PropertyNames.SkipReason, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
CultureAttributeExcludingOtherCultureRunsTest()
void NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeExcludingOtherCultureRunsTest () inline
References NUnit.Framework.CultureAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.IncludeExcludeAttribute.Exclude, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
CultureAttributeWithMultipleCulturesIncluded()
void NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeWithMultipleCulturesIncluded () inline
References NUnit.Framework.CultureAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
MaxTimeAttributeSetsMaxTime()
void NUnit.Framework.Attributes.ApplyToTestTests.MaxTimeAttributeSetsMaxTime () inline
References NUnit.Framework.PropertyAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.PropertyNames.MaxTime, NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
MaxTimeAttributeSetsMaxTimeOnNonRunnableTest()
void NUnit.Framework.Attributes.ApplyToTestTests.MaxTimeAttributeSetsMaxTimeOnNonRunnableTest () inline
References NUnit.Framework.PropertyAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.PropertyNames.MaxTime, NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
PairwiseAttributeSetsJoinType()
void NUnit.Framework.Attributes.ApplyToTestTests.PairwiseAttributeSetsJoinType () inline
References NUnit.Framework.CombiningStrategyAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.PropertyNames.JoinType, NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
PairwiseAttributeSetsJoinTypeOnNonRunnableTest()
void NUnit.Framework.Attributes.ApplyToTestTests.PairwiseAttributeSetsJoinTypeOnNonRunnableTest () inline
References NUnit.Framework.CombiningStrategyAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.PropertyNames.JoinType, NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
PlatformAttributeRunsTest()
void NUnit.Framework.Attributes.ApplyToTestTests.PlatformAttributeRunsTest () inline
References NUnit.Framework.PlatformAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.ApplyToTestTests.GetMyPlatform(), NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
PlatformAttributeSkipsTest()
void NUnit.Framework.Attributes.ApplyToTestTests.PlatformAttributeSkipsTest () inline
References NUnit.Framework.PlatformAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
PlatformAttributeDoesNotAffectNonRunnableTest()
void NUnit.Framework.Attributes.ApplyToTestTests.PlatformAttributeDoesNotAffectNonRunnableTest () inline
References NUnit.Framework.PlatformAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.ApplyToTestTests.GetMyPlatform(), NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
GetMyPlatform()
string NUnit.Framework.Attributes.ApplyToTestTests.GetMyPlatform () inline private
References NUnit.Framework.Internal.OSPlatform.CurrentPlatform, and NUnit.Framework.Internal.OSPlatform.IsMacOSX.
Referenced by NUnit.Framework.Attributes.ApplyToTestTests.PlatformAttributeDoesNotAffectNonRunnableTest(), and NUnit.Framework.Attributes.ApplyToTestTests.PlatformAttributeRunsTest().
RepeatAttributeSetsRepeatCount()
void NUnit.Framework.Attributes.ApplyToTestTests.RepeatAttributeSetsRepeatCount () inline
References NUnit.Framework.PropertyAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.PropertyNames.RepeatCount, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
RepeatAttributeSetsRepeatCountOnNonRunnableTest()
void NUnit.Framework.Attributes.ApplyToTestTests.RepeatAttributeSetsRepeatCountOnNonRunnableTest () inline
References NUnit.Framework.PropertyAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.PropertyNames.RepeatCount, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
RequiresMTAAttributeSetsApartmentState()
void NUnit.Framework.Attributes.ApplyToTestTests.RequiresMTAAttributeSetsApartmentState () inline
References NUnit.Framework.Internal.PropertyNames.ApartmentState, NUnit.Framework.PropertyAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
RequiresMTAAttributeSetsApartmentStateOnNonRunnableTest()
void NUnit.Framework.Attributes.ApplyToTestTests.RequiresMTAAttributeSetsApartmentStateOnNonRunnableTest () inline
References NUnit.Framework.Internal.PropertyNames.ApartmentState, NUnit.Framework.PropertyAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
RequiresSTAAttributeSetsApartmentState()
void NUnit.Framework.Attributes.ApplyToTestTests.RequiresSTAAttributeSetsApartmentState () inline
References NUnit.Framework.Internal.PropertyNames.ApartmentState, NUnit.Framework.PropertyAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
RequiresSTAAttributeSetsApartmentStateOnNonRunnableTest()
void NUnit.Framework.Attributes.ApplyToTestTests.RequiresSTAAttributeSetsApartmentStateOnNonRunnableTest () inline
References NUnit.Framework.Internal.PropertyNames.ApartmentState, NUnit.Framework.PropertyAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
RequiresThreadAttributeSetsRequiresThread()
void NUnit.Framework.Attributes.ApplyToTestTests.RequiresThreadAttributeSetsRequiresThread () inline
References NUnit.Framework.RequiresThreadAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.PropertyNames.RequiresThread, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
RequiresThreadAttributeSetsRequiresThreadOnNonRunnableTest()
void NUnit.Framework.Attributes.ApplyToTestTests.RequiresThreadAttributeSetsRequiresThreadOnNonRunnableTest () inline
References NUnit.Framework.RequiresThreadAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.PropertyNames.RequiresThread, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
RequiresThreadAttributeMaySetApartmentState()
void NUnit.Framework.Attributes.ApplyToTestTests.RequiresThreadAttributeMaySetApartmentState () inline
References NUnit.Framework.Internal.PropertyNames.ApartmentState, NUnit.Framework.RequiresThreadAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.PropertyNames.RequiresThread, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
SequentialAttributeSetsJoinType()
void NUnit.Framework.Attributes.ApplyToTestTests.SequentialAttributeSetsJoinType () inline
References NUnit.Framework.CombiningStrategyAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.PropertyNames.JoinType, NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
SequentialAttributeSetsJoinTypeOnNonRunnableTest()
void NUnit.Framework.Attributes.ApplyToTestTests.SequentialAttributeSetsJoinTypeOnNonRunnableTest () inline
References NUnit.Framework.CombiningStrategyAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.PropertyNames.JoinType, NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
SetCultureAttributeSetsSetCultureProperty()
void NUnit.Framework.Attributes.ApplyToTestTests.SetCultureAttributeSetsSetCultureProperty () inline
References NUnit.Framework.PropertyAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.PropertyNames.SetCulture, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
SetCultureAttributeSetsSetCulturePropertyOnNonRunnableTest()
void NUnit.Framework.Attributes.ApplyToTestTests.SetCultureAttributeSetsSetCulturePropertyOnNonRunnableTest () inline
References NUnit.Framework.PropertyAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Internal.PropertyNames.SetCulture, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
SetUICultureAttributeSetsSetUICultureProperty()
void NUnit.Framework.Attributes.ApplyToTestTests.SetUICultureAttributeSetsSetUICultureProperty () inline
References NUnit.Framework.PropertyAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.PropertyNames.SetUICulture, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
SetUICultureAttributeSetsSetUICulturePropertyOnNonRunnableTest()
void NUnit.Framework.Attributes.ApplyToTestTests.SetUICultureAttributeSetsSetUICulturePropertyOnNonRunnableTest () inline
References NUnit.Framework.PropertyAttribute.ApplyToTest(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Internal.PropertyNames.SetUICulture, NUnit.Framework.Attributes.ApplyToTestTests.test, and NUnit.Framework.Assert.That().
Member Data Documentation
test
Test NUnit.Framework.Attributes.ApplyToTestTests.test private
Referenced by NUnit.Framework.Attributes.ApplyToTestTests.CategoryAttributeSetsCategory(), NUnit.Framework.Attributes.ApplyToTestTests.CategoryAttributeSetsCategoryOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.CategoryAttributeSetsMultipleCategories(), NUnit.Framework.Attributes.ApplyToTestTests.CombinatorialAttributeSetsJoinType(), NUnit.Framework.Attributes.ApplyToTestTests.CombinatorialAttributeSetsJoinTypeOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeDoesNotAffectNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeExcludingCurrentCultureSkipsTest(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeExcludingOtherCultureRunsTest(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeIncludingCurrentCultureRunsTest(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeIncludingOtherCultureSkipsTest(), NUnit.Framework.Attributes.ApplyToTestTests.CultureAttributeWithMultipleCulturesIncluded(), NUnit.Framework.Attributes.ApplyToTestTests.DescriptionAttributeSetsDescription(), NUnit.Framework.Attributes.ApplyToTestTests.DescriptionAttributeSetsDescriptionOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.ExplicitAttributeDoesNotAffectNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.ExplicitAttributeMakesTestExplicit(), NUnit.Framework.Attributes.ApplyToTestTests.ExplicitAttributeSetsIgnoreReason(), NUnit.Framework.Attributes.ApplyToTestTests.ExplicitAttributeWithIgnoreIgnoresTest(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeDoesNotAffectNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeIgnoresTest(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeIgnoresTestUntilDateSpecified(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeIgnoresTestUntilDateTimeSpecified(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeMarksTestAsRunnableAfterUntilDatePasses(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeSetsIgnoreReason(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeUntilSetsTheReason(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeWithExplicitIgnoresTest(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeWithUntilAddsIgnoreUntilDateProperty(), NUnit.Framework.Attributes.ApplyToTestTests.IgnoreAttributeWithUntilAddsIgnoreUntilDatePropertyPastUntilDate(), NUnit.Framework.Attributes.ApplyToTestTests.MaxTimeAttributeSetsMaxTime(), NUnit.Framework.Attributes.ApplyToTestTests.MaxTimeAttributeSetsMaxTimeOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.PairwiseAttributeSetsJoinType(), NUnit.Framework.Attributes.ApplyToTestTests.PairwiseAttributeSetsJoinTypeOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.PlatformAttributeDoesNotAffectNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.PlatformAttributeRunsTest(), NUnit.Framework.Attributes.ApplyToTestTests.PlatformAttributeSkipsTest(), NUnit.Framework.Attributes.ApplyToTestTests.RepeatAttributeSetsRepeatCount(), NUnit.Framework.Attributes.ApplyToTestTests.RepeatAttributeSetsRepeatCountOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresMTAAttributeSetsApartmentState(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresMTAAttributeSetsApartmentStateOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresSTAAttributeSetsApartmentState(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresSTAAttributeSetsApartmentStateOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresThreadAttributeMaySetApartmentState(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresThreadAttributeSetsRequiresThread(), NUnit.Framework.Attributes.ApplyToTestTests.RequiresThreadAttributeSetsRequiresThreadOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.SequentialAttributeSetsJoinType(), NUnit.Framework.Attributes.ApplyToTestTests.SequentialAttributeSetsJoinTypeOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.SetCultureAttributeSetsSetCultureProperty(), NUnit.Framework.Attributes.ApplyToTestTests.SetCultureAttributeSetsSetCulturePropertyOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.SetUICultureAttributeSetsSetUICultureProperty(), NUnit.Framework.Attributes.ApplyToTestTests.SetUICultureAttributeSetsSetUICulturePropertyOnNonRunnableTest(), and NUnit.Framework.Attributes.ApplyToTestTests.SetUp().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/ApplyToTestTests.cs