Doc: IGLib EXTENDED: NUnit.Engine.ServiceContext Class Reference
NUnit.Engine.ServiceContext Class Reference
The ServiceContext is used by services, runners and external clients to locate the services they need through the IServiceLocator interface.
Public Member Functions
ServiceContext ()
void Add (IService service)
T GetService< T > ()
Return a specified type of service
object GetService (Type serviceType)
Return a specified type of service
Properties
ServiceManager ServiceManager [get, private set]
Detailed Description
The ServiceContext is used by services, runners and external clients to locate the services they need through the IServiceLocator interface.
Constructor & Destructor Documentation
ServiceContext()
NUnit.Engine.ServiceContext.ServiceContext () inline
References NUnit.Engine.ServiceContext.ServiceManager.
Member Function Documentation
Add()
void NUnit.Engine.ServiceContext.Add (IService service) inline
References NUnit.Engine.Services.ServiceManager.AddService(), and NUnit.Engine.IService.ServiceContext.
Referenced by NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.ConvertEngineResultToXml(), NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CreateServiceContext(), NUnit.Engine.Services.Tests.ServiceDependencyTests.DefaultTestRunnerFactory_ProjectServiceError(), NUnit.Engine.Services.Tests.ServiceDependencyTests.DefaultTestRunnerFactory_ProjectServiceMissing(), NUnit.Engine.TestEngine.Initialize(), NUnit.Agent.NUnitTestAgent.Main(), NUnit.Engine.Services.Tests.ServiceDependencyTests.RecentFilesService_SettingsServiceError(), NUnit.Engine.Services.Tests.ServiceDependencyTests.RecentFilesService_SettingsServiceMissing(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.runSchemaValidatorTest(), NUnit.Engine.Services.Tests.ServiceDependencyTests.TestAgency_RuntimeFrameworkServiceError(), and NUnit.Engine.Services.Tests.ServiceDependencyTests.TestAgency_RuntimeFrameworkServiceMissing().
GetService< T >()
T NUnit.Engine.ServiceContext.GetService< T > () inline
Return a specified type of service
Implements NUnit.Engine.IServiceLocator.
Type Constraints
T : class
References NUnit.Engine.Services.ServiceManager.GetService().
GetService()
object NUnit.Engine.ServiceContext.GetService (Type serviceType) inline
Return a specified type of service
Implements NUnit.Engine.IServiceLocator.
References NUnit.Engine.Services.ServiceManager.GetService().
Referenced by NUnit.Engine.Services.DefaultTestRunnerFactory.StartService(), NUnit.Engine.Services.DriverService.StartService(), NUnit.Engine.Services.ResultService.StartService(), NUnit.Engine.Services.ProjectService.StartService(), NUnit.Engine.Services.RecentFilesService.StartService(), NUnit.Engine.Services.TestAgency.StartService(), and NUnit.Engine.Services.DomainManager.StartService().
Property Documentation
ServiceManager
ServiceManager NUnit.Engine.ServiceContext.ServiceManager get private set
Referenced by NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.ConvertEngineResultToXml(), NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CreateServiceContext(), NUnit.Engine.TestEngine.Dispose(), NUnit.Engine.TestEngine.GetRunner(), NUnit.Engine.TestEngine.Initialize(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.runSchemaValidatorTest(), and NUnit.Engine.ServiceContext.ServiceContext().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/ServiceContext.cs