Doc: IGLib EXTENDED: MathKernelApp.Form1 Class Reference
MathKernelApp.Form1 Class Reference
Summary description for Form1.
Public Member Functions
Form1 (string[] args)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent (string[] args)
Required method for Designer support - do not modify the contents of this method with the code editor.
void computeButton_Click (object sender, System.EventArgs e)
Static Private Member Functions
static void Main (string[] args)
The main entry point for the application.
Private Attributes
System.Windows.Forms.Label label1
System.Windows.Forms.Label label2
System.Windows.Forms.Label label3
System.Windows.Forms.Label label4
System.Windows.Forms.Label label5
System.Windows.Forms.Button computeButton
System.Windows.Forms.TextBox inputBox
System.Windows.Forms.TextBox messagesBox
System.Windows.Forms.TextBox printBox
System.Windows.Forms.PictureBox graphicsBox
System.Windows.Forms.TextBox resultBox
System.Windows.Forms.PictureBox pictureBox2
Wolfram.NETLink.MathKernel mathKernel
System.ComponentModel.Container components = null
Required designer variable.
Detailed Description
Summary description for Form1.
Constructor & Destructor Documentation
Form1()
MathKernelApp.Form1.Form1 (string[] args) inline
References MathKernelApp.Form1.InitializeComponent().
Referenced by MathKernelApp.Form1.Main().
Member Function Documentation
Dispose()
override void MathKernelApp.Form1.Dispose (bool disposing) inline protected
Clean up any resources being used.
References MathKernelApp.Form1.components.
InitializeComponent()
void MathKernelApp.Form1.InitializeComponent (string[] args) inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by MathKernelApp.Form1.Form1().
Main()
static void MathKernelApp.Form1.Main (string[] args) inline static private
The main entry point for the application.
References MathKernelApp.Form1.Form1().
computeButton_Click()
void MathKernelApp.Form1.computeButton_Click (object sender, System.EventArgs e) inline private
References MathKernelApp.Form1.computeButton, MathKernelApp.Form1.graphicsBox, MathKernelApp.Form1.inputBox, MathKernelApp.Form1.mathKernel, MathKernelApp.Form1.messagesBox, MathKernelApp.Form1.printBox, and MathKernelApp.Form1.resultBox.
Member Data Documentation
label1
System.Windows.Forms.Label MathKernelApp.Form1.label1 private
label2
System.Windows.Forms.Label MathKernelApp.Form1.label2 private
label3
System.Windows.Forms.Label MathKernelApp.Form1.label3 private
label4
System.Windows.Forms.Label MathKernelApp.Form1.label4 private
label5
System.Windows.Forms.Label MathKernelApp.Form1.label5 private
computeButton
System.Windows.Forms.Button MathKernelApp.Form1.computeButton private
Referenced by MathKernelApp.Form1.computeButton_Click().
inputBox
System.Windows.Forms.TextBox MathKernelApp.Form1.inputBox private
Referenced by MathKernelApp.Form1.computeButton_Click().
messagesBox
System.Windows.Forms.TextBox MathKernelApp.Form1.messagesBox private
Referenced by MathKernelApp.Form1.computeButton_Click().
printBox
System.Windows.Forms.TextBox MathKernelApp.Form1.printBox private
Referenced by MathKernelApp.Form1.computeButton_Click().
graphicsBox
System.Windows.Forms.PictureBox MathKernelApp.Form1.graphicsBox private
Referenced by MathKernelApp.Form1.computeButton_Click().
resultBox
System.Windows.Forms.TextBox MathKernelApp.Form1.resultBox private
Referenced by MathKernelApp.Form1.computeButton_Click().
pictureBox2
System.Windows.Forms.PictureBox MathKernelApp.Form1.pictureBox2 private
mathKernel
Wolfram.NETLink.MathKernel MathKernelApp.Form1.mathKernel private
Referenced by MathKernelApp.Form1.computeButton_Click().
components
System.ComponentModel.Container MathKernelApp.Form1.components = null private
Required designer variable.
Referenced by MathKernelApp.Form1.Dispose().
The documentation for this class was generated from the following file:
igtest/IGLibTestShellExt/mathematica/examples/part2/MathKernelApp/Form1.cs