Doc: IGLib EXTENDED: Meta.Numerics.Statistics.Distributions.KolmogorovDistribution Class Reference
Meta.Numerics.Statistics.Distributions.KolmogorovDistribution Class Reference
Represents the distribution of the Kolmogorov-Smirnov D statistic.
Public Member Functions
KolmogorovDistribution ()
Initializes a new asymptotic Kolmogorov distribution.
override double ProbabilityDensity (double x)
Returns the probability density at the given point.
override double LeftProbability (double x)
Returns the cumulative probability to the left of (below) the given point.
override double RightProbability (double x)
Return the cumulative probability to the right of (above) the given point.
override double Moment (int r)
Computes a raw moment of the distribution.
override double MomentAboutMean (int r)
Computes a central moment of the distribution.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double InverseLeftProbability (double P)
Returns the point at which the cumulative distribution function attains a given value.
virtual double InverseRightProbability (double Q)
Returns the point at which the right probability function attains the given value.
virtual double ExpectationValue (Func< double, double > f)
Computes the expectation value of the given function.
virtual double GetRandomValue (Random rng)
Returns a random value.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Cumulant (int r)
Computes a cumulant of the distribution.
Properties
override double Mean [get]
override double Variance [get]
override double Median [get]
override Interval Support [get]
Properties inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double Median [get]
Gets the median of the distribution.
virtual Interval Support [get]
Gets the interval over which the distribution is nonvanishing.
Properties inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Mean [get]
Gets the mean of the distribution.
virtual double Variance [get]
Gets the variance of the distribution.
virtual double StandardDeviation [get]
Gets the standard deviation of the distribution.
virtual double Skewness [get]
Gets the skewness of the distribution.
virtual double ExcessKurtosis [get]
Gets the excess kurtosis of the distribution.
Static Private Member Functions
static double AsymptoticPPrime (double x)
static double AsymptoticQPrime (double x)
static double AsymptoticP (double x)
static double AsymptoticQ (double x)
Detailed Description
Represents the distribution of the Kolmogorov-Smirnov D statistic.
The D statistic in a Kolmogorov-Smirnov test is distributed (under the null hypothesis) according to a Kolmogorov disribution, in the limit of a large sample size.
<seealse cref="Sample.KolmogorovSmirnovTest(Meta.Numerics.Statistics.Distributions.Distribution)" >
Constructor & Destructor Documentation
KolmogorovDistribution()
Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.KolmogorovDistribution () inline
Initializes a new asymptotic Kolmogorov distribution.
Member Function Documentation
ProbabilityDensity()
override double Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.ProbabilityDensity (double x) inline virtual
Returns the probability density at the given point.
Implements Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.AsymptoticPPrime(), and Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.AsymptoticQPrime().
AsymptoticPPrime()
static double Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.AsymptoticPPrime (double x) inline static private
Referenced by Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.ProbabilityDensity().
AsymptoticQPrime()
static double Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.AsymptoticQPrime (double x) inline static private
Referenced by Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.ProbabilityDensity().
LeftProbability()
override double Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.LeftProbability (double x) inline virtual
Returns the cumulative probability to the left of (below) the given point.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.AsymptoticP(), and Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.AsymptoticQ().
RightProbability()
override double Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.RightProbability (double x) inline virtual
Return the cumulative probability to the right of (above) the given point.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.AsymptoticP(), and Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.AsymptoticQ().
AsymptoticP()
static double Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.AsymptoticP (double x) inline static private
Referenced by Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.LeftProbability(), and Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.RightProbability().
AsymptoticQ()
static double Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.AsymptoticQ (double x) inline static private
Referenced by Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.LeftProbability(), and Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.RightProbability().
Moment()
override double Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.Moment (int r) inline virtual
Computes a raw moment of the distribution.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Functions.AdvancedMath.DirichletEta(), Meta.Numerics.Functions.AdvancedMath.Gamma(), and Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.Mean.
MomentAboutMean()
override double Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.MomentAboutMean (int r) inline virtual
Computes a central moment of the distribution.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
Property Documentation
Mean
override double Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.Mean get
Referenced by Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.Moment().
Variance
override double Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.Variance get
Median
override double Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.Median get
Support
override Interval Meta.Numerics.Statistics.Distributions.KolmogorovDistribution.Support get
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/Distributions/KolmogorovDistribution.cs