Doc: IGLib EXTENDED: IG.Forms.MessageBoxLauncher Class Reference
IG.Forms.MessageBoxLauncher Class Reference
An exemple form that launches various message boxes.
Public Member Functions
MessageBoxLauncher ()
MessageBoxLauncher ()
MessageBoxLauncher ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void MessageBoxLauncher_Load (object sender, EventArgs e)
void lblTitle_Click (object sender, EventArgs e)
void btnLaunch_Click (object sender, EventArgs e)
void btnCurrentDirRefresh_Click (object sender, EventArgs e)
void btnFileOpenBrowse_Click (object sender, EventArgs e)
void txtFileOpen_TextChanged (object sender, EventArgs e)
void btnDirOpenBrowse_Click (object sender, EventArgs e)
void txtDirOpen_TextChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MessageBoxLauncher_Load (object sender, EventArgs e)
void lblTitle_Click (object sender, EventArgs e)
void btnLaunch_Click (object sender, EventArgs e)
void btnCurrentDirRefresh_Click (object sender, EventArgs e)
void btnFileOpenBrowse_Click (object sender, EventArgs e)
void txtFileOpen_TextChanged (object sender, EventArgs e)
void btnDirOpenBrowse_Click (object sender, EventArgs e)
void txtDirOpen_TextChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MessageBoxLauncher_Load (object sender, EventArgs e)
void lblTitle_Click (object sender, EventArgs e)
void btnLaunch_Click (object sender, EventArgs e)
void btnCurrentDirRefresh_Click (object sender, EventArgs e)
void btnFileOpenBrowse_Click (object sender, EventArgs e)
void txtFileOpen_TextChanged (object sender, EventArgs e)
void btnDirOpenBrowse_Click (object sender, EventArgs e)
void txtDirOpen_TextChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.GroupBox grpIcons
System.Windows.Forms.RadioButton rbQuestion
System.Windows.Forms.RadioButton rbInfo
System.Windows.Forms.RadioButton rbWarning
System.Windows.Forms.RadioButton rbError
System.Windows.Forms.Label lblTitle
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.RadioButton rbOKCancel
System.Windows.Forms.RadioButton rbOK
System.Windows.Forms.RadioButton rbYesNoCancel
System.Windows.Forms.RadioButton rbYesNo
System.Windows.Forms.RadioButton rbAbortRetryIgnore
System.Windows.Forms.GroupBox grTitleText
System.Windows.Forms.TextBox txtMessage
System.Windows.Forms.TextBox txtTitle
System.Windows.Forms.Label lblMsgText
System.Windows.Forms.Label lblMsgTitle
System.Windows.Forms.Button btnLaunch
System.Windows.Forms.GroupBox grpResult
System.Windows.Forms.Label lblButtonClicked
System.Windows.Forms.Label lblResultDescription
System.Windows.Forms.GroupBox grpFileOpen
System.Windows.Forms.Label lblCurrentDirTitle
System.Windows.Forms.Label lblCurrentDir
System.Windows.Forms.Button btnCurrentDirRefresh
System.Windows.Forms.Button btnFileOpenBrowse
System.Windows.Forms.TextBox txtFileOpen
System.Windows.Forms.Label lblFileSize
System.Windows.Forms.Label lblFileOpenSizeTitle
System.Windows.Forms.GroupBox grpDirOpen
System.Windows.Forms.Label lblDirNumFiles
System.Windows.Forms.Label lblDirNumFilesTitle
System.Windows.Forms.TextBox txtDirOpen
System.Windows.Forms.Button btnDirOpenBrowse
Detailed Description
An exemple form that launches various message boxes.
User can set all parameters that affect function and appearance, and launc the message boxes accordingly.
Constructor & Destructor Documentation
MessageBoxLauncher() [1/3]
IG.Forms.MessageBoxLauncher.MessageBoxLauncher () inline
References IG.Forms.MessageBoxLauncher.InitializeComponent().
MessageBoxLauncher() [2/3]
IG.Forms.MessageBoxLauncher.MessageBoxLauncher () inline
References IG.Forms.MessageBoxLauncher.InitializeComponent().
MessageBoxLauncher() [3/3]
IG.Forms.MessageBoxLauncher.MessageBoxLauncher () inline
References IG.Forms.MessageBoxLauncher.InitializeComponent().
Member Function Documentation
MessageBoxLauncher_Load() [1/3]
void IG.Forms.MessageBoxLauncher.MessageBoxLauncher_Load (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.lblCurrentDir, IG.Forms.MessageBoxLauncher.txtDirOpen, and IG.Forms.MessageBoxLauncher.txtFileOpen.
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
lblTitle_Click() [1/3]
void IG.Forms.MessageBoxLauncher.lblTitle_Click (object sender, EventArgs e) inline private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
btnLaunch_Click() [1/3]
void IG.Forms.MessageBoxLauncher.btnLaunch_Click (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.lblButtonClicked, IG.Forms.MessageBoxLauncher.rbAbortRetryIgnore, IG.Forms.MessageBoxLauncher.rbError, IG.Forms.MessageBoxLauncher.rbInfo, IG.Forms.MessageBoxLauncher.rbOK, IG.Forms.MessageBoxLauncher.rbOKCancel, IG.Forms.MessageBoxLauncher.rbWarning, IG.Forms.MessageBoxLauncher.rbYesNo, IG.Forms.MessageBoxLauncher.rbYesNoCancel, IG.Forms.MessageBoxLauncher.txtMessage, and IG.Forms.MessageBoxLauncher.txtTitle.
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
btnCurrentDirRefresh_Click() [1/3]
void IG.Forms.MessageBoxLauncher.btnCurrentDirRefresh_Click (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.lblCurrentDir.
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
btnFileOpenBrowse_Click() [1/3]
void IG.Forms.MessageBoxLauncher.btnFileOpenBrowse_Click (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.txtFileOpen.
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
txtFileOpen_TextChanged() [1/3]
void IG.Forms.MessageBoxLauncher.txtFileOpen_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.lblFileSize, and IG.Forms.MessageBoxLauncher.txtFileOpen.
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
btnDirOpenBrowse_Click() [1/3]
void IG.Forms.MessageBoxLauncher.btnDirOpenBrowse_Click (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.txtDirOpen.
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
txtDirOpen_TextChanged() [1/3]
void IG.Forms.MessageBoxLauncher.txtDirOpen_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.lblDirNumFiles, and IG.Forms.MessageBoxLauncher.txtDirOpen.
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
Dispose() [1/3]
override void IG.Forms.MessageBoxLauncher.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.MessageBoxLauncher.components.
InitializeComponent() [1/3]
void IG.Forms.MessageBoxLauncher.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.MessageBoxLauncher.btnCurrentDirRefresh, IG.Forms.MessageBoxLauncher.btnCurrentDirRefresh_Click(), IG.Forms.MessageBoxLauncher.btnDirOpenBrowse, IG.Forms.MessageBoxLauncher.btnDirOpenBrowse_Click(), IG.Forms.MessageBoxLauncher.btnFileOpenBrowse, IG.Forms.MessageBoxLauncher.btnFileOpenBrowse_Click(), IG.Forms.MessageBoxLauncher.btnLaunch, IG.Forms.MessageBoxLauncher.btnLaunch_Click(), IG.Forms.MessageBoxLauncher.groupBox1, IG.Forms.MessageBoxLauncher.grpDirOpen, IG.Forms.MessageBoxLauncher.grpFileOpen, IG.Forms.MessageBoxLauncher.grpIcons, IG.Forms.MessageBoxLauncher.grpResult, IG.Forms.MessageBoxLauncher.grTitleText, IG.Forms.MessageBoxLauncher.lblButtonClicked, IG.Forms.MessageBoxLauncher.lblCurrentDir, IG.Forms.MessageBoxLauncher.lblCurrentDirTitle, IG.Forms.MessageBoxLauncher.lblDirNumFiles, IG.Forms.MessageBoxLauncher.lblDirNumFilesTitle, IG.Forms.MessageBoxLauncher.lblFileOpenSizeTitle, IG.Forms.MessageBoxLauncher.lblFileSize, IG.Forms.MessageBoxLauncher.lblMsgText, IG.Forms.MessageBoxLauncher.lblMsgTitle, IG.Forms.MessageBoxLauncher.lblResultDescription, IG.Forms.MessageBoxLauncher.lblTitle, IG.Forms.MessageBoxLauncher.lblTitle_Click(), IG.Forms.MessageBoxLauncher.MessageBoxLauncher_Load(), IG.Forms.MessageBoxLauncher.rbAbortRetryIgnore, IG.Forms.MessageBoxLauncher.rbError, IG.Forms.MessageBoxLauncher.rbInfo, IG.Forms.MessageBoxLauncher.rbOK, IG.Forms.MessageBoxLauncher.rbOKCancel, IG.Forms.MessageBoxLauncher.rbQuestion, IG.Forms.MessageBoxLauncher.rbWarning, IG.Forms.MessageBoxLauncher.rbYesNo, IG.Forms.MessageBoxLauncher.rbYesNoCancel, IG.Forms.MessageBoxLauncher.txtDirOpen, IG.Forms.MessageBoxLauncher.txtDirOpen_TextChanged(), IG.Forms.MessageBoxLauncher.txtFileOpen, IG.Forms.MessageBoxLauncher.txtFileOpen_TextChanged(), IG.Forms.MessageBoxLauncher.txtMessage, and IG.Forms.MessageBoxLauncher.txtTitle.
Referenced by IG.Forms.MessageBoxLauncher.MessageBoxLauncher().
MessageBoxLauncher_Load() [2/3]
void IG.Forms.MessageBoxLauncher.MessageBoxLauncher_Load (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.lblCurrentDir, IG.Forms.MessageBoxLauncher.txtDirOpen, and IG.Forms.MessageBoxLauncher.txtFileOpen.
lblTitle_Click() [2/3]
void IG.Forms.MessageBoxLauncher.lblTitle_Click (object sender, EventArgs e) inline private
btnLaunch_Click() [2/3]
void IG.Forms.MessageBoxLauncher.btnLaunch_Click (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.lblButtonClicked, IG.Forms.MessageBoxLauncher.rbAbortRetryIgnore, IG.Forms.MessageBoxLauncher.rbError, IG.Forms.MessageBoxLauncher.rbInfo, IG.Forms.MessageBoxLauncher.rbOK, IG.Forms.MessageBoxLauncher.rbOKCancel, IG.Forms.MessageBoxLauncher.rbWarning, IG.Forms.MessageBoxLauncher.rbYesNo, IG.Forms.MessageBoxLauncher.rbYesNoCancel, IG.Forms.MessageBoxLauncher.txtMessage, and IG.Forms.MessageBoxLauncher.txtTitle.
btnCurrentDirRefresh_Click() [2/3]
void IG.Forms.MessageBoxLauncher.btnCurrentDirRefresh_Click (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.lblCurrentDir.
btnFileOpenBrowse_Click() [2/3]
void IG.Forms.MessageBoxLauncher.btnFileOpenBrowse_Click (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.txtFileOpen.
txtFileOpen_TextChanged() [2/3]
void IG.Forms.MessageBoxLauncher.txtFileOpen_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.lblFileSize, and IG.Forms.MessageBoxLauncher.txtFileOpen.
btnDirOpenBrowse_Click() [2/3]
void IG.Forms.MessageBoxLauncher.btnDirOpenBrowse_Click (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.txtDirOpen.
txtDirOpen_TextChanged() [2/3]
void IG.Forms.MessageBoxLauncher.txtDirOpen_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.lblDirNumFiles, and IG.Forms.MessageBoxLauncher.txtDirOpen.
Dispose() [2/3]
override void IG.Forms.MessageBoxLauncher.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.MessageBoxLauncher.components.
InitializeComponent() [2/3]
void IG.Forms.MessageBoxLauncher.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.MessageBoxLauncher.btnCurrentDirRefresh, IG.Forms.MessageBoxLauncher.btnCurrentDirRefresh_Click(), IG.Forms.MessageBoxLauncher.btnDirOpenBrowse, IG.Forms.MessageBoxLauncher.btnDirOpenBrowse_Click(), IG.Forms.MessageBoxLauncher.btnFileOpenBrowse, IG.Forms.MessageBoxLauncher.btnFileOpenBrowse_Click(), IG.Forms.MessageBoxLauncher.btnLaunch, IG.Forms.MessageBoxLauncher.btnLaunch_Click(), IG.Forms.MessageBoxLauncher.groupBox1, IG.Forms.MessageBoxLauncher.grpDirOpen, IG.Forms.MessageBoxLauncher.grpFileOpen, IG.Forms.MessageBoxLauncher.grpIcons, IG.Forms.MessageBoxLauncher.grpResult, IG.Forms.MessageBoxLauncher.grTitleText, IG.Forms.MessageBoxLauncher.lblButtonClicked, IG.Forms.MessageBoxLauncher.lblCurrentDir, IG.Forms.MessageBoxLauncher.lblCurrentDirTitle, IG.Forms.MessageBoxLauncher.lblDirNumFiles, IG.Forms.MessageBoxLauncher.lblDirNumFilesTitle, IG.Forms.MessageBoxLauncher.lblFileOpenSizeTitle, IG.Forms.MessageBoxLauncher.lblFileSize, IG.Forms.MessageBoxLauncher.lblMsgText, IG.Forms.MessageBoxLauncher.lblMsgTitle, IG.Forms.MessageBoxLauncher.lblResultDescription, IG.Forms.MessageBoxLauncher.lblTitle, IG.Forms.MessageBoxLauncher.lblTitle_Click(), IG.Forms.MessageBoxLauncher.MessageBoxLauncher_Load(), IG.Forms.MessageBoxLauncher.rbAbortRetryIgnore, IG.Forms.MessageBoxLauncher.rbError, IG.Forms.MessageBoxLauncher.rbInfo, IG.Forms.MessageBoxLauncher.rbOK, IG.Forms.MessageBoxLauncher.rbOKCancel, IG.Forms.MessageBoxLauncher.rbQuestion, IG.Forms.MessageBoxLauncher.rbWarning, IG.Forms.MessageBoxLauncher.rbYesNo, IG.Forms.MessageBoxLauncher.rbYesNoCancel, IG.Forms.MessageBoxLauncher.txtDirOpen, IG.Forms.MessageBoxLauncher.txtDirOpen_TextChanged(), IG.Forms.MessageBoxLauncher.txtFileOpen, IG.Forms.MessageBoxLauncher.txtFileOpen_TextChanged(), IG.Forms.MessageBoxLauncher.txtMessage, and IG.Forms.MessageBoxLauncher.txtTitle.
MessageBoxLauncher_Load() [3/3]
void IG.Forms.MessageBoxLauncher.MessageBoxLauncher_Load (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.lblCurrentDir, IG.Forms.MessageBoxLauncher.txtDirOpen, and IG.Forms.MessageBoxLauncher.txtFileOpen.
lblTitle_Click() [3/3]
void IG.Forms.MessageBoxLauncher.lblTitle_Click (object sender, EventArgs e) inline private
btnLaunch_Click() [3/3]
void IG.Forms.MessageBoxLauncher.btnLaunch_Click (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.lblButtonClicked, IG.Forms.MessageBoxLauncher.rbAbortRetryIgnore, IG.Forms.MessageBoxLauncher.rbError, IG.Forms.MessageBoxLauncher.rbInfo, IG.Forms.MessageBoxLauncher.rbOK, IG.Forms.MessageBoxLauncher.rbOKCancel, IG.Forms.MessageBoxLauncher.rbWarning, IG.Forms.MessageBoxLauncher.rbYesNo, IG.Forms.MessageBoxLauncher.rbYesNoCancel, IG.Forms.MessageBoxLauncher.txtMessage, and IG.Forms.MessageBoxLauncher.txtTitle.
btnCurrentDirRefresh_Click() [3/3]
void IG.Forms.MessageBoxLauncher.btnCurrentDirRefresh_Click (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.lblCurrentDir.
btnFileOpenBrowse_Click() [3/3]
void IG.Forms.MessageBoxLauncher.btnFileOpenBrowse_Click (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.txtFileOpen.
txtFileOpen_TextChanged() [3/3]
void IG.Forms.MessageBoxLauncher.txtFileOpen_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.lblFileSize, and IG.Forms.MessageBoxLauncher.txtFileOpen.
btnDirOpenBrowse_Click() [3/3]
void IG.Forms.MessageBoxLauncher.btnDirOpenBrowse_Click (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.txtDirOpen.
txtDirOpen_TextChanged() [3/3]
void IG.Forms.MessageBoxLauncher.txtDirOpen_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.MessageBoxLauncher.lblDirNumFiles, and IG.Forms.MessageBoxLauncher.txtDirOpen.
Dispose() [3/3]
override void IG.Forms.MessageBoxLauncher.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.MessageBoxLauncher.components.
InitializeComponent() [3/3]
void IG.Forms.MessageBoxLauncher.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.MessageBoxLauncher.btnCurrentDirRefresh, IG.Forms.MessageBoxLauncher.btnCurrentDirRefresh_Click(), IG.Forms.MessageBoxLauncher.btnDirOpenBrowse, IG.Forms.MessageBoxLauncher.btnDirOpenBrowse_Click(), IG.Forms.MessageBoxLauncher.btnFileOpenBrowse, IG.Forms.MessageBoxLauncher.btnFileOpenBrowse_Click(), IG.Forms.MessageBoxLauncher.btnLaunch, IG.Forms.MessageBoxLauncher.btnLaunch_Click(), IG.Forms.MessageBoxLauncher.groupBox1, IG.Forms.MessageBoxLauncher.grpDirOpen, IG.Forms.MessageBoxLauncher.grpFileOpen, IG.Forms.MessageBoxLauncher.grpIcons, IG.Forms.MessageBoxLauncher.grpResult, IG.Forms.MessageBoxLauncher.grTitleText, IG.Forms.MessageBoxLauncher.lblButtonClicked, IG.Forms.MessageBoxLauncher.lblCurrentDir, IG.Forms.MessageBoxLauncher.lblCurrentDirTitle, IG.Forms.MessageBoxLauncher.lblDirNumFiles, IG.Forms.MessageBoxLauncher.lblDirNumFilesTitle, IG.Forms.MessageBoxLauncher.lblFileOpenSizeTitle, IG.Forms.MessageBoxLauncher.lblFileSize, IG.Forms.MessageBoxLauncher.lblMsgText, IG.Forms.MessageBoxLauncher.lblMsgTitle, IG.Forms.MessageBoxLauncher.lblResultDescription, IG.Forms.MessageBoxLauncher.lblTitle, IG.Forms.MessageBoxLauncher.lblTitle_Click(), IG.Forms.MessageBoxLauncher.MessageBoxLauncher_Load(), IG.Forms.MessageBoxLauncher.rbAbortRetryIgnore, IG.Forms.MessageBoxLauncher.rbError, IG.Forms.MessageBoxLauncher.rbInfo, IG.Forms.MessageBoxLauncher.rbOK, IG.Forms.MessageBoxLauncher.rbOKCancel, IG.Forms.MessageBoxLauncher.rbQuestion, IG.Forms.MessageBoxLauncher.rbWarning, IG.Forms.MessageBoxLauncher.rbYesNo, IG.Forms.MessageBoxLauncher.rbYesNoCancel, IG.Forms.MessageBoxLauncher.txtDirOpen, IG.Forms.MessageBoxLauncher.txtDirOpen_TextChanged(), IG.Forms.MessageBoxLauncher.txtFileOpen, IG.Forms.MessageBoxLauncher.txtFileOpen_TextChanged(), IG.Forms.MessageBoxLauncher.txtMessage, and IG.Forms.MessageBoxLauncher.txtTitle.
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.MessageBoxLauncher.components = null private
Required designer variable.
Referenced by IG.Forms.MessageBoxLauncher.Dispose().
grpIcons
System Windows Forms GroupBox IG.Forms.MessageBoxLauncher.grpIcons private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
rbQuestion
System Windows Forms RadioButton IG.Forms.MessageBoxLauncher.rbQuestion private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
rbInfo
System Windows Forms RadioButton IG.Forms.MessageBoxLauncher.rbInfo private
Referenced by IG.Forms.MessageBoxLauncher.btnLaunch_Click(), and IG.Forms.MessageBoxLauncher.InitializeComponent().
rbWarning
System Windows Forms RadioButton IG.Forms.MessageBoxLauncher.rbWarning private
Referenced by IG.Forms.MessageBoxLauncher.btnLaunch_Click(), and IG.Forms.MessageBoxLauncher.InitializeComponent().
rbError
System Windows Forms RadioButton IG.Forms.MessageBoxLauncher.rbError private
Referenced by IG.Forms.MessageBoxLauncher.btnLaunch_Click(), and IG.Forms.MessageBoxLauncher.InitializeComponent().
lblTitle
System Windows Forms Label IG.Forms.MessageBoxLauncher.lblTitle private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
groupBox1
System Windows Forms GroupBox IG.Forms.MessageBoxLauncher.groupBox1 private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
rbOKCancel
System Windows Forms RadioButton IG.Forms.MessageBoxLauncher.rbOKCancel private
Referenced by IG.Forms.MessageBoxLauncher.btnLaunch_Click(), and IG.Forms.MessageBoxLauncher.InitializeComponent().
rbOK
System Windows Forms RadioButton IG.Forms.MessageBoxLauncher.rbOK private
Referenced by IG.Forms.MessageBoxLauncher.btnLaunch_Click(), and IG.Forms.MessageBoxLauncher.InitializeComponent().
rbYesNoCancel
System Windows Forms RadioButton IG.Forms.MessageBoxLauncher.rbYesNoCancel private
Referenced by IG.Forms.MessageBoxLauncher.btnLaunch_Click(), and IG.Forms.MessageBoxLauncher.InitializeComponent().
rbYesNo
System Windows Forms RadioButton IG.Forms.MessageBoxLauncher.rbYesNo private
Referenced by IG.Forms.MessageBoxLauncher.btnLaunch_Click(), and IG.Forms.MessageBoxLauncher.InitializeComponent().
rbAbortRetryIgnore
System Windows Forms RadioButton IG.Forms.MessageBoxLauncher.rbAbortRetryIgnore private
Referenced by IG.Forms.MessageBoxLauncher.btnLaunch_Click(), and IG.Forms.MessageBoxLauncher.InitializeComponent().
grTitleText
System Windows Forms GroupBox IG.Forms.MessageBoxLauncher.grTitleText private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
txtMessage
System Windows Forms TextBox IG.Forms.MessageBoxLauncher.txtMessage private
Referenced by IG.Forms.MessageBoxLauncher.btnLaunch_Click(), and IG.Forms.MessageBoxLauncher.InitializeComponent().
txtTitle
System Windows Forms TextBox IG.Forms.MessageBoxLauncher.txtTitle private
Referenced by IG.Forms.MessageBoxLauncher.btnLaunch_Click(), and IG.Forms.MessageBoxLauncher.InitializeComponent().
lblMsgText
System Windows Forms Label IG.Forms.MessageBoxLauncher.lblMsgText private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
lblMsgTitle
System Windows Forms Label IG.Forms.MessageBoxLauncher.lblMsgTitle private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
btnLaunch
System Windows Forms Button IG.Forms.MessageBoxLauncher.btnLaunch private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
grpResult
System Windows Forms GroupBox IG.Forms.MessageBoxLauncher.grpResult private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
lblButtonClicked
System Windows Forms Label IG.Forms.MessageBoxLauncher.lblButtonClicked private
Referenced by IG.Forms.MessageBoxLauncher.btnLaunch_Click(), and IG.Forms.MessageBoxLauncher.InitializeComponent().
lblResultDescription
System Windows Forms Label IG.Forms.MessageBoxLauncher.lblResultDescription private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
grpFileOpen
System Windows Forms GroupBox IG.Forms.MessageBoxLauncher.grpFileOpen private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
lblCurrentDirTitle
System Windows Forms Label IG.Forms.MessageBoxLauncher.lblCurrentDirTitle private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
lblCurrentDir
System Windows Forms Label IG.Forms.MessageBoxLauncher.lblCurrentDir private
Referenced by IG.Forms.MessageBoxLauncher.btnCurrentDirRefresh_Click(), IG.Forms.MessageBoxLauncher.InitializeComponent(), and IG.Forms.MessageBoxLauncher.MessageBoxLauncher_Load().
btnCurrentDirRefresh
System Windows Forms Button IG.Forms.MessageBoxLauncher.btnCurrentDirRefresh private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
btnFileOpenBrowse
System Windows Forms Button IG.Forms.MessageBoxLauncher.btnFileOpenBrowse private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
txtFileOpen
System Windows Forms TextBox IG.Forms.MessageBoxLauncher.txtFileOpen private
Referenced by IG.Forms.MessageBoxLauncher.btnFileOpenBrowse_Click(), IG.Forms.MessageBoxLauncher.InitializeComponent(), IG.Forms.MessageBoxLauncher.MessageBoxLauncher_Load(), and IG.Forms.MessageBoxLauncher.txtFileOpen_TextChanged().
lblFileSize
System Windows Forms Label IG.Forms.MessageBoxLauncher.lblFileSize private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent(), and IG.Forms.MessageBoxLauncher.txtFileOpen_TextChanged().
lblFileOpenSizeTitle
System Windows Forms Label IG.Forms.MessageBoxLauncher.lblFileOpenSizeTitle private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
grpDirOpen
System Windows Forms GroupBox IG.Forms.MessageBoxLauncher.grpDirOpen private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
lblDirNumFiles
System Windows Forms Label IG.Forms.MessageBoxLauncher.lblDirNumFiles private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent(), and IG.Forms.MessageBoxLauncher.txtDirOpen_TextChanged().
lblDirNumFilesTitle
System Windows Forms Label IG.Forms.MessageBoxLauncher.lblDirNumFilesTitle private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
txtDirOpen
System Windows Forms TextBox IG.Forms.MessageBoxLauncher.txtDirOpen private
Referenced by IG.Forms.MessageBoxLauncher.btnDirOpenBrowse_Click(), IG.Forms.MessageBoxLauncher.InitializeComponent(), IG.Forms.MessageBoxLauncher.MessageBoxLauncher_Load(), and IG.Forms.MessageBoxLauncher.txtDirOpen_TextChanged().
btnDirOpenBrowse
System Windows Forms Button IG.Forms.MessageBoxLauncher.btnDirOpenBrowse private
Referenced by IG.Forms.MessageBoxLauncher.InitializeComponent().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/MessageBoxLauncher.cs
iglib/igforms/Utilities/MessageBoxLauncher.Designer.cs