Doc: IGLib EXTENDED: NUnit.Framework.TestCaseData Class Reference
NUnit.Framework.TestCaseData Class Reference
The TestCaseData class represents a set of arguments and other parameter info to be used for a parameterized test case. It is derived from TestCaseParameters and adds a fluent syntax for use in initializing the test case.
Public Member Functions
TestCaseData (params object[] args)
Initializes a new instance of the TestCaseData class.
TestCaseData (object arg)
Initializes a new instance of the TestCaseData class.
TestCaseData (object arg1, object arg2)
Initializes a new instance of the TestCaseData class.
TestCaseData (object arg1, object arg2, object arg3)
Initializes a new instance of the TestCaseData class.
TestCaseData Returns (object result)
Sets the expected result for the test
TestCaseData SetName (string name)
Sets the name of the test case
TestCaseData SetDescription (string description)
Sets the description for the test case being constructed.
TestCaseData SetCategory (string category)
Applies a category to the test
TestCaseData SetProperty (string propName, string propValue)
Applies a named property to the test
TestCaseData SetProperty (string propName, int propValue)
Applies a named property to the test
TestCaseData SetProperty (string propName, double propValue)
Applies a named property to the test
TestCaseData Explicit ()
Marks the test case as explicit.
TestCaseData Explicit (string reason)
Marks the test case as explicit, specifying the reason.
TestCaseData Ignore (string reason)
Ignores this TestCase, specifying the reason.
Public Member Functions inherited from NUnit.Framework.Internal.TestCaseParameters
TestCaseParameters ()
Default Constructor creates an empty parameter set
TestCaseParameters (Exception exception)
Construct a non-runnable ParameterSet, specifying the provider exception that made it invalid.
TestCaseParameters (object[] args)
Construct a parameter set with a list of arguments
TestCaseParameters (ITestCaseData data)
Construct a ParameterSet from an object implementing ITestCaseData
Public Member Functions inherited from NUnit.Framework.Internal.TestParameters
TestParameters ()
Default Constructor creates an empty parameter set
TestParameters (object[] args)
Construct a parameter set with a list of arguments
TestParameters (Exception exception)
Construct a non-runnable ParameterSet, specifying the provider exception that made it invalid.
TestParameters (ITestData data)
Construct a ParameterSet from an object implementing ITestData
void ApplyToTest (Test test)
Applies ParameterSet _values to the test itself.
Additional Inherited Members
Properties inherited from NUnit.Framework.Internal.TestCaseParameters
object ExpectedResult [get, set]
The expected result of the test, which must match the method return type.
bool HasExpectedResult [get, set]
Gets a value indicating whether an expected result was specified.
Properties inherited from NUnit.Framework.Internal.TestParameters
RunState RunState [get, set]
The RunState for this set of parameters.
object[] Arguments [get, set]
The arguments to be used in running the test, which must match the method signature.
string TestName [get, set]
A name to be used for this test case in lieu of the standard generated name containing the argument list.
IPropertyBag Properties [get, private set]
Gets the property dictionary for this test
object[] OriginalArguments [get, private set]
The original arguments provided by the user, used for display purposes.
Properties inherited from NUnit.Framework.Interfaces.ITestData
string TestName [get]
Gets the name to be used for the test
RunState RunState [get]
Gets the RunState for this test case.
object[] Arguments [get]
Gets the argument list to be provided to the test
IPropertyBag Properties [get]
Gets the property dictionary for the test case
Properties inherited from NUnit.Framework.Interfaces.ITestCaseData
object ExpectedResult [get]
Gets the expected result of the test case
bool HasExpectedResult [get]
Returns true if an expected result has been set
Detailed Description
The TestCaseData class represents a set of arguments and other parameter info to be used for a parameterized test case. It is derived from TestCaseParameters and adds a fluent syntax for use in initializing the test case.
Constructor & Destructor Documentation
TestCaseData() [1/4]
NUnit.Framework.TestCaseData.TestCaseData (params object[] args) inline
Initializes a new instance of the TestCaseData class.
Parameters
args The arguments.
TestCaseData() [2/4]
NUnit.Framework.TestCaseData.TestCaseData (object arg) inline
Initializes a new instance of the TestCaseData class.
Parameters
arg The argument.
TestCaseData() [3/4]
NUnit.Framework.TestCaseData.TestCaseData (object arg1, object arg2) inline
Initializes a new instance of the TestCaseData class.
Parameters
arg1 The first argument.
arg2 The second argument.
TestCaseData() [4/4]
NUnit.Framework.TestCaseData.TestCaseData (object arg1, object arg2, object arg3) inline
Initializes a new instance of the TestCaseData class.
Parameters
arg1 The first argument.
arg2 The second argument.
arg3 The third argument.
Member Function Documentation
Returns()
TestCaseData NUnit.Framework.TestCaseData.Returns (object result) inline
Sets the expected result for the test
Parameters
result The expected result
Returns
A modified TestCaseData
References NUnit.Framework.Internal.TestCaseParameters.ExpectedResult.
SetName()
TestCaseData NUnit.Framework.TestCaseData.SetName (string name) inline
Sets the name of the test case
Returns
The modified TestCaseData instance
References NUnit.Framework.Internal.TestParameters.TestName.
Referenced by NUnit.Framework.Attributes.RandomAttributeTests.MethodNames.GetEnumerator().
SetDescription()
TestCaseData NUnit.Framework.TestCaseData.SetDescription (string description) inline
Sets the description for the test case being constructed.
Parameters
description The description.
Returns
The modified TestCaseData instance.
References NUnit.Framework.Internal.PropertyNames.Description, NUnit.Framework.Internal.TestParameters.Properties, and NUnit.Framework.Interfaces.IPropertyBag.Set().
SetCategory()
TestCaseData NUnit.Framework.TestCaseData.SetCategory (string category) inline
Applies a category to the test
Parameters
category
Returns
References NUnit.Framework.Interfaces.IPropertyBag.Add(), NUnit.Framework.Internal.PropertyNames.Category, and NUnit.Framework.Internal.TestParameters.Properties.
SetProperty() [1/3]
TestCaseData NUnit.Framework.TestCaseData.SetProperty (string propName, string propValue) inline
Applies a named property to the test
Parameters
propName
propValue
Returns
References NUnit.Framework.Interfaces.IPropertyBag.Add(), and NUnit.Framework.Internal.TestParameters.Properties.
SetProperty() [2/3]
TestCaseData NUnit.Framework.TestCaseData.SetProperty (string propName, int propValue) inline
Applies a named property to the test
Parameters
propName
propValue
Returns
References NUnit.Framework.Interfaces.IPropertyBag.Add(), and NUnit.Framework.Internal.TestParameters.Properties.
SetProperty() [3/3]
TestCaseData NUnit.Framework.TestCaseData.SetProperty (string propName, double propValue) inline
Applies a named property to the test
Parameters
propName
propValue
Returns
References NUnit.Framework.Interfaces.IPropertyBag.Add(), and NUnit.Framework.Internal.TestParameters.Properties.
Explicit() [1/2]
TestCaseData NUnit.Framework.TestCaseData.Explicit () inline
Marks the test case as explicit.
References NUnit.Framework.TestCaseData.Explicit().
Referenced by NUnit.Framework.TestCaseData.Explicit().
Explicit() [2/2]
TestCaseData NUnit.Framework.TestCaseData.Explicit (string reason) inline
Marks the test case as explicit, specifying the reason.
References NUnit.Framework.TestCaseData.Explicit(), NUnit.Framework.Internal.TestParameters.Properties, NUnit.Framework.Interfaces.IPropertyBag.Set(), and NUnit.Framework.Internal.PropertyNames.SkipReason.
Ignore()
TestCaseData NUnit.Framework.TestCaseData.Ignore (string reason) inline
Ignores this TestCase, specifying the reason.
Parameters
reason The reason.
Returns
References NUnit.Framework.Internal.TestParameters.Properties, NUnit.Framework.Interfaces.IPropertyBag.Set(), and NUnit.Framework.Internal.PropertyNames.SkipReason.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/TestCaseData.cs