Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLANTR Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLANTR Class Reference
– LAPACK auxiliary routine (version 3.0) – Univ. of Tennessee, Univ. of California Berkeley, NAG Ltd., Courant Institute, Argonne National Lab, and Rice University October 31, 1992
Public Member Functions
DLANTR (DLASSQ dlassq, LSAME lsame)
DLANTR ()
double Run (string NORM, string UPLO, string DIAG, int M, int N, double[] A, int offset_a, int LDA, ref double[] WORK, int offset_work)
Private Attributes
DLASSQ _dlassq
LSAME _lsame
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.0) – Univ. of Tennessee, Univ. of California Berkeley, NAG Ltd., Courant Institute, Argonne National Lab, and Rice University October 31, 1992
Purpose
DLANTR returns the value of the one norm, or the Frobenius norm, or the infinity norm, or the element of largest absolute value of a trapezoidal or triangular matrix A.
Description
DLANTR returns the value
DLANTR = (max(abs(A(i,j))), NORM = 'M' or 'm' ((norm1(A), NORM = '1', 'O' or 'o' ((normI(A), NORM = 'I' or 'i' ((normF(A), NORM = 'F', 'f', 'E' or 'e'
where norm1 denotes the one norm of a matrix (maximum column sum), normI denotes the infinity norm of a matrix (maximum row sum) and normF denotes the Frobenius norm of a matrix (square root of sum of squares). Note that max(abs(A(i,j))) is not a matrix norm.
/summary>
Constructor & Destructor Documentation
DLANTR() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLANTR.DLANTR (DLASSQ dlassq, LSAME lsame) inline
DLANTR() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLANTR.DLANTR () inline
Member Function Documentation
Run()
double DotNumerics.LinearAlgebra.CSLapack.DLANTR.Run (string NORM, string UPLO, string DIAG, int M, int N, double[] A, int offset_a, int LDA, ref double[] WORK, int offset_work) inline
Purpose
DLANTR returns the value of the one norm, or the Frobenius norm, or the infinity norm, or the element of largest absolute value of a trapezoidal or triangular matrix A.
Description
DLANTR returns the value
DLANTR = (max(abs(A(i,j))), NORM = 'M' or 'm' ((norm1(A), NORM = '1', 'O' or 'o' ((normI(A), NORM = 'I' or 'i' ((normF(A), NORM = 'F', 'f', 'E' or 'e'
where norm1 denotes the one norm of a matrix (maximum column sum), normI denotes the infinity norm of a matrix (maximum row sum) and normF denotes the Frobenius norm of a matrix (square root of sum of squares). Note that max(abs(A(i,j))) is not a matrix norm.
/summary>
Parameters
NORM (input) CHARACTER*1 Specifies the value to be returned in DLANTR as described above. /param>
Parameters
UPLO (input) CHARACTER*1 Specifies whether the matrix A is upper or lower trapezoidal. = 'U': Upper trapezoidal = 'L': Lower trapezoidal Note that A is triangular instead of trapezoidal if M = N. /param>
Parameters
DIAG (input) CHARACTER*1 Specifies whether or not the matrix A has unit diagonal. = 'N': Non-unit diagonal = 'U': Unit diagonal /param>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0, and if UPLO = 'U', M .LE. N. When M = 0, DLANTR is set to zero. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. 0, and if UPLO = 'L', N .LE. M. When N = 0, DLANTR is set to zero. /param>
Parameters
A (input) DOUBLE PRECISION array, dimension (LDA,N) The trapezoidal matrix A (A is triangular if M = N). If UPLO = 'U', the leading m by n upper trapezoidal part of the array A contains the upper trapezoidal matrix, and the strictly lower triangular part of A is not referenced. If UPLO = 'L', the leading m by n lower trapezoidal part of the array A contains the lower trapezoidal matrix, and the strictly upper triangular part of A is not referenced. Note that when DIAG = 'U', the diagonal elements of A are not referenced and are assumed to be one. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(M,1). /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (LWORK), where LWORK .GE. M when NORM = 'I'; otherwise, WORK is not referenced. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLANTR.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASSQ.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLANTR.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTRCON.Run().
Member Data Documentation
_dlassq
DLASSQ DotNumerics.LinearAlgebra.CSLapack.DLANTR._dlassq private
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLANTR._lsame private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLANTR.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLANTR.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLANTR.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLANTR.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlantr.cs