Doc: IGLib EXTENDED: NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests Class Reference
NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests Class Reference
Classes
class CallbackEventHandler
class NullListener
Public Member Functions
void CreateDriver ()
void ConstructController_MissingFile_ThrowsArgumentInvalid ()
void Load_GoodFile_ReturnsRunnableSuite ()
void Explore_AfterLoad_ReturnsRunnableSuite ()
void ExploreTestsAction_WithoutLoad_ThrowsInvalidOperationException ()
void CountTestsAction_AfterLoad_ReturnsCorrectCount ()
void CountTestsAction_WithoutLoad_ThrowsInvalidOperationException ()
void RunTestsAction_AfterLoad_ReturnsRunnableSuite ()
void RunTestsAction_WithoutLoad_ThrowsInvalidOperationException ()
Static Private Member Functions
static string GetSkipReason (XmlNode result)
Private Attributes
IDictionary< string, object > _settings = new Dictionary<string, object>()
NUnit3FrameworkDriver _driver
string _mockAssemblyPath
Static Private Attributes
const string MOCK_ASSEMBLY = "mock-nunit-assembly.exe"
const string MISSING_FILE = "junk.dll"
const string NUNIT_FRAMEWORK = "nunit.framework"
const string LOAD_MESSAGE = "Method called without calling Load first"
Member Function Documentation
CreateDriver()
void NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.CreateDriver () inline
References NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests._driver, NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests._mockAssemblyPath, NUnit.Framework.TestContext.CurrentContext, NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.MOCK_ASSEMBLY, and NUnit.Framework.TestContext.TestDirectory.
ConstructController_MissingFile_ThrowsArgumentInvalid()
void NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.ConstructController_MissingFile_ThrowsArgumentInvalid () inline
References NUnit.Framework.Throws.ArgumentException, and NUnit.Framework.Assert.That().
Load_GoodFile_ReturnsRunnableSuite()
void NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.Load_GoodFile_ReturnsRunnableSuite () inline
References NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests._driver, NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests._mockAssemblyPath, NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests._settings, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(), NUnit.Tests.Assemblies.MockAssembly.Tests, and NUnit.Framework.Assert.That().
Explore_AfterLoad_ReturnsRunnableSuite()
void NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.Explore_AfterLoad_ReturnsRunnableSuite () inline
References NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests._driver, NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests._mockAssemblyPath, NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests._settings, NUnit.Engine.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.Explore(), NUnit.Framework.Is.GreaterThan(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(), NUnit.Tests.Assemblies.MockAssembly.Tests, NUnit.Engine.TestFilter.Text, and NUnit.Framework.Assert.That().
ExploreTestsAction_WithoutLoad_ThrowsInvalidOperationException()
void NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.ExploreTestsAction_WithoutLoad_ThrowsInvalidOperationException () inline
References NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests._driver, NUnit.Framework.Assert.Catch(), NUnit.Engine.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.Explore(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.LOAD_MESSAGE, NUnit.Engine.TestFilter.Text, NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
CountTestsAction_AfterLoad_ReturnsCorrectCount()
void NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.CountTestsAction_AfterLoad_ReturnsCorrectCount () inline
References NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests._driver, NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests._mockAssemblyPath, NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests._settings, NUnit.Engine.Drivers.NUnit3FrameworkDriver.CountTestCases(), NUnit.Engine.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(), NUnit.Tests.Assemblies.MockAssembly.Tests, NUnit.Engine.TestFilter.Text, and NUnit.Framework.Assert.That().
CountTestsAction_WithoutLoad_ThrowsInvalidOperationException()
void NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.CountTestsAction_WithoutLoad_ThrowsInvalidOperationException () inline
References NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests._driver, NUnit.Framework.Assert.Catch(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.CountTestCases(), NUnit.Engine.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.LOAD_MESSAGE, NUnit.Engine.TestFilter.Text, NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
RunTestsAction_AfterLoad_ReturnsRunnableSuite()
void NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite () inline
References NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests._driver, NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests._mockAssemblyPath, NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests._settings, NUnit.Engine.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Tests.Assemblies.MockAssembly.ErrorsAndFailures, NUnit.Framework.Is.GreaterThan(), NUnit.Tests.Assemblies.MockAssembly.Inconclusive, NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.Run(), NUnit.Tests.Assemblies.MockAssembly.Skipped, NUnit.Tests.Assemblies.MockAssembly.Success, NUnit.Tests.Assemblies.MockAssembly.Tests, NUnit.Engine.TestFilter.Text, and NUnit.Framework.Assert.That().
RunTestsAction_WithoutLoad_ThrowsInvalidOperationException()
void NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.RunTestsAction_WithoutLoad_ThrowsInvalidOperationException () inline
References NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests._driver, NUnit.Framework.Assert.Catch(), NUnit.Engine.TestFilter.Empty, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.LOAD_MESSAGE, NUnit.Engine.Drivers.NUnit3FrameworkDriver.Run(), NUnit.Engine.TestFilter.Text, NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
GetSkipReason()
static string NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.GetSkipReason (XmlNode result) inline static private
References NUnit.Framework.Internal.PropertyNames.SkipReason.
Member Data Documentation
MOCK_ASSEMBLY
const string NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.MOCK_ASSEMBLY = "mock-nunit-assembly.exe" static private
Referenced by NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.CreateDriver().
MISSING_FILE
const string NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.MISSING_FILE = "junk.dll" static private
NUNIT_FRAMEWORK
const string NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.NUNIT_FRAMEWORK = "nunit.framework" static private
LOAD_MESSAGE
const string NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.LOAD_MESSAGE = "Method called without calling Load first" static private
Referenced by NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.CountTestsAction_WithoutLoad_ThrowsInvalidOperationException(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.ExploreTestsAction_WithoutLoad_ThrowsInvalidOperationException(), and NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.RunTestsAction_WithoutLoad_ThrowsInvalidOperationException().
_settings
IDictionary<string, object> NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests._settings = new Dictionary<string, object>() private
Referenced by NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.CountTestsAction_AfterLoad_ReturnsCorrectCount(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.Explore_AfterLoad_ReturnsRunnableSuite(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.Load_GoodFile_ReturnsRunnableSuite(), and NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite().
_driver
NUnit3FrameworkDriver NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests._driver private
Referenced by NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.CountTestsAction_AfterLoad_ReturnsCorrectCount(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.CountTestsAction_WithoutLoad_ThrowsInvalidOperationException(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.CreateDriver(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.Explore_AfterLoad_ReturnsRunnableSuite(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.ExploreTestsAction_WithoutLoad_ThrowsInvalidOperationException(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.Load_GoodFile_ReturnsRunnableSuite(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite(), and NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.RunTestsAction_WithoutLoad_ThrowsInvalidOperationException().
_mockAssemblyPath
string NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests._mockAssemblyPath private
Referenced by NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.CountTestsAction_AfterLoad_ReturnsCorrectCount(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.CreateDriver(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.Explore_AfterLoad_ReturnsRunnableSuite(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.Load_GoodFile_ReturnsRunnableSuite(), and NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Drivers/NUnit3FrameworkDriverTests.cs