Doc: IGLib EXTENDED: IG.Neural.Forms.Old.NeuralParametricTestOld Class Reference
IG.Neural.Forms.Old.NeuralParametricTestOld Class Reference
Torm for parametric tests. Obsolete!
Public Member Functions
NeuralParametricTestOld (INeuralModel neuralModel)
Constructs the control, with ANN-based model specified.
NeuralParametricTestOld ()
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
void ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void PlotParametricTest ()
plots the selected outpt dependend on the selected parameter.
NeuralParametricTestOld (INeuralModel neuralModel)
Constructs the control, with ANN-based model specified.
NeuralParametricTestOld ()
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
void ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void PlotParametricTest ()
plots the selected outpt dependend on the selected parameter.
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
INeuralModelContainer _neuralModelContainerControl
int _selectedParameterId = 0
int _selectedOutputId = 0
Properties
INeuralModel NeuralModel [get, protected set]
Neural network - based model.
INeuralApproximator TrainedNetwork [get]
Traint artificial neural network.
InputOutputDataDefiniton NeuralDataDefinition [get]
Neural data definition.
int NumInputParameters [get]
Gets number of input parameters.
int NumOutputValues [get]
Gets number of output values.
IVector ParameterValues [get]
Vector of current values of input parameters as defined by the DadaGridView.
double[] MinValues [get]
Minimal values of parameters.
double[] MaxValues [get]
Maximal values of parameters.
int SelectedParameterId [get, protected set]
Sequential number of the selected parameter as specified by the user.
double SelectedParameterMin [get]
Minimal value of the selected parameter.
double SelectedParameterMax [get]
Maximal value of the selected parameter as specified by the user.
int SelectedOutputId [get, protected set]
string SelectedParameterLabelText [get]
Gets axis label text for the currently selected parameter.
string SelectedOutputLabelText [get]
Gets axis label text for the currently selected output value.
PlotterZedGraph Plotter [get]
Plotter that is used for plotting the graphs.
Private Member Functions
void btnParmTestStart_Click (object sender, EventArgs e)
Plots the parametric test.
void neuralInputControl1_SelectedParameterIdChanged (int oldId, int newId)
Executes when ID of the selected input parameter changes; Plots the parametric test.
void neuralInputControl1_SelectedParameterMinChanged (double oldValue, double newValue)
Executes when minimal value of the selected parameter changes by user interaction; Plots the parametric test.
void neuralInputControl1_SelectedParameterMaxChanged (double oldValue, double newValue)
Executes when maximal value of the selected parameter changes by user interaction; Plots the parametric test.
void neuralOutputValueSelector1_SelectedOutputIdChanged (int oldId, int newId)
Executes when ID of the selected output value changes; Plots the parametric test.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void btnParmTestStart_Click (object sender, EventArgs e)
Plots the parametric test.
void neuralInputControl1_SelectedParameterIdChanged (int oldId, int newId)
Executes when ID of the selected input parameter changes; Plots the parametric test.
void neuralInputControl1_SelectedParameterMinChanged (double oldValue, double newValue)
Executes when minimal value of the selected parameter changes by user interaction; Plots the parametric test.
void neuralInputControl1_SelectedParameterMaxChanged (double oldValue, double newValue)
Executes when maximal value of the selected parameter changes by user interaction; Plots the parametric test.
void neuralOutputValueSelector1_SelectedOutputIdChanged (int oldId, int newId)
Executes when ID of the selected output value changes; Plots the parametric test.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
INeuralModel _neuralModel
PlotterZedGraph _plotter
System.ComponentModel.IContainer components = null
Required designer variable.
NeuralParametricTestSelection neuralInputControl1
System.Windows.Forms.Panel pnlGraph
System.Windows.Forms.NumericUpDown txtNumPointsLine
System.Windows.Forms.Label lblNumPointsLine
ZedGraph.ZedGraphControl ParmTestFGraph
System.Windows.Forms.Button btnParmTestStart
Forms.NeuralOutputValueSelector neuralOutputValueSelector1
System.Windows.Forms.Label lblInfoOld
Detailed Description
Torm for parametric tests. Obsolete!
This is developed form initial design of the form where NeuralParametricTestSelection is used for everything related to input parameters (to set central parameter values and to select the parameter that varies and bounds in which it varies).
Now this is used for demonstratin how further composed controls can be put on tab pages. Important aspect of this is how to handle the data definition and neural approximator.
$A Igor Aor13;
Constructor & Destructor Documentation
NeuralParametricTestOld() [1/4]
IG.Neural.Forms.Old.NeuralParametricTestOld.NeuralParametricTestOld (INeuralModel neuralModel) inline
Constructs the control, with ANN-based model specified.
Parameters
neuralModel ANN-based model, containing data definitions and trained neural network.
References IG.Neural.Forms.Old.NeuralParametricTestOld.NeuralModel.
NeuralParametricTestOld() [2/4]
IG.Neural.Forms.Old.NeuralParametricTestOld.NeuralParametricTestOld () inline
References IG.Neural.Forms.Old.NeuralParametricTestOld.InitializeComponent(), IG.Neural.Forms.NeuralParametricTestSelection.InputParameterSelector, IG.Neural.Forms.Old.NeuralParametricTestOld.neuralInputControl1, IG.Neural.Forms.Old.NeuralParametricTestOld.neuralInputControl1_SelectedParameterIdChanged(), IG.Neural.Forms.Old.NeuralParametricTestOld.neuralInputControl1_SelectedParameterMaxChanged(), IG.Neural.Forms.Old.NeuralParametricTestOld.neuralInputControl1_SelectedParameterMinChanged(), IG.Neural.Forms.NeuralInputParameterSelectorMinMax.SelectedParameterIdChanged, IG.Neural.Forms.NeuralInputParameterSelectorMinMax.SelectedParameterMaxChanged, and IG.Neural.Forms.NeuralInputParameterSelectorMinMax.SelectedParameterMinChanged.
NeuralParametricTestOld() [3/4]
IG.Neural.Forms.Old.NeuralParametricTestOld.NeuralParametricTestOld (INeuralModel neuralModel) inline
Constructs the control, with ANN-based model specified.
Parameters
neuralModel ANN-based model, containing data definitions and trained neural network.
References IG.Neural.Forms.Old.NeuralParametricTestOld.NeuralModel.
NeuralParametricTestOld() [4/4]
IG.Neural.Forms.Old.NeuralParametricTestOld.NeuralParametricTestOld () inline
References IG.Neural.Forms.Old.NeuralParametricTestOld.InitializeComponent(), IG.Neural.Forms.NeuralParametricTestSelection.InputParameterSelector, IG.Neural.Forms.Old.NeuralParametricTestOld.neuralInputControl1, IG.Neural.Forms.Old.NeuralParametricTestOld.neuralInputControl1_SelectedParameterIdChanged(), IG.Neural.Forms.Old.NeuralParametricTestOld.neuralInputControl1_SelectedParameterMaxChanged(), IG.Neural.Forms.Old.NeuralParametricTestOld.neuralInputControl1_SelectedParameterMinChanged(), IG.Neural.Forms.NeuralInputParameterSelectorMinMax.SelectedParameterIdChanged, IG.Neural.Forms.NeuralInputParameterSelectorMinMax.SelectedParameterMaxChanged, and IG.Neural.Forms.NeuralInputParameterSelectorMinMax.SelectedParameterMinChanged.
Member Function Documentation
SetNeuralModel() [1/2]
void IG.Neural.Forms.Old.NeuralParametricTestOld.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
References IG.Neural.Forms.Old.NeuralParametricTestOld.NeuralModel.
ApplyPlotterSettingsDefault() [1/2]
void IG.Neural.Forms.Old.NeuralParametricTestOld.ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Num.InputOutputDataDefiniton.InputElementList, IG.Gr.PlotterZedGraph.IsShowPointValues, IG.Neural.Forms.Old.NeuralParametricTestOld.NeuralDataDefinition, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Neural.Forms.Old.NeuralParametricTestOld.SelectedOutputLabelText, IG.Neural.Forms.Old.NeuralParametricTestOld.SelectedParameterLabelText, IG.Gr.PlotterZedGraph.XAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabel.
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
ApplyPlotCurveSettingsDefault() [1/2]
void IG.Neural.Forms.Old.NeuralParametricTestOld.ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LineWidth, IG.Gr.PlotZedgraphCurve.PointBorderColor, IG.Gr.PlotZedgraphCurve.PointFillColor, and IG.Gr.PlotZedgraphCurve.PointsVisible.
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
PlotParametricTest() [1/2]
void IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest () inline
plots the selected outpt dependend on the selected parameter.
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Neural.Forms.Old.NeuralParametricTestOld.ApplyPlotCurveSettingsDefault(), IG.Neural.Forms.Old.NeuralParametricTestOld.ApplyPlotterSettingsDefault(), IG.Num.IVectorApproximator.CalculateOutput(), IG.Num.VectorBase.CopyPlain(), IG.Neural.Forms.Old.NeuralParametricTestOld.NumInputParameters, IG.Neural.Forms.Old.NeuralParametricTestOld.NumOutputValues, IG.Neural.Forms.Old.NeuralParametricTestOld.ParameterValues, IG.Neural.Forms.Old.NeuralParametricTestOld.SelectedOutputId, IG.Neural.Forms.Old.NeuralParametricTestOld.SelectedParameterId, IG.Neural.Forms.Old.NeuralParametricTestOld.SelectedParameterMax, IG.Neural.Forms.Old.NeuralParametricTestOld.SelectedParameterMin, IG.Neural.Forms.Old.NeuralParametricTestOld.TrainedNetwork, and IG.Neural.Forms.Old.NeuralParametricTestOld.txtNumPointsLine.
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.btnParmTestStart_Click(), IG.Neural.Forms.Old.NeuralParametricTestOld.neuralInputControl1_SelectedParameterIdChanged(), IG.Neural.Forms.Old.NeuralParametricTestOld.neuralInputControl1_SelectedParameterMaxChanged(), IG.Neural.Forms.Old.NeuralParametricTestOld.neuralInputControl1_SelectedParameterMinChanged(), and IG.Neural.Forms.Old.NeuralParametricTestOld.neuralOutputValueSelector1_SelectedOutputIdChanged().
btnParmTestStart_Click() [1/2]
void IG.Neural.Forms.Old.NeuralParametricTestOld.btnParmTestStart_Click (object sender, EventArgs e) inline private
Plots the parametric test.
References IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.InitializeComponent().
neuralInputControl1_SelectedParameterIdChanged() [1/2]
void IG.Neural.Forms.Old.NeuralParametricTestOld.neuralInputControl1_SelectedParameterIdChanged (int oldId, int newId) inline private
Executes when ID of the selected input parameter changes; Plots the parametric test.
Parameters
oldId Old ID of the selected output value (after change).
newId New ID of the selected output value (after changed).
References IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.NeuralParametricTestOld().
neuralInputControl1_SelectedParameterMinChanged() [1/2]
void IG.Neural.Forms.Old.NeuralParametricTestOld.neuralInputControl1_SelectedParameterMinChanged (double oldValue, double newValue) inline private
Executes when minimal value of the selected parameter changes by user interaction; Plots the parametric test.
Parameters
oldValue Old value.
newValue New value.
References IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.NeuralParametricTestOld().
neuralInputControl1_SelectedParameterMaxChanged() [1/2]
void IG.Neural.Forms.Old.NeuralParametricTestOld.neuralInputControl1_SelectedParameterMaxChanged (double oldValue, double newValue) inline private
Executes when maximal value of the selected parameter changes by user interaction; Plots the parametric test.
Parameters
oldValue Old value.
newValue New value.
References IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.NeuralParametricTestOld().
neuralOutputValueSelector1_SelectedOutputIdChanged() [1/2]
void IG.Neural.Forms.Old.NeuralParametricTestOld.neuralOutputValueSelector1_SelectedOutputIdChanged (int oldId, int newId) inline private
Executes when ID of the selected output value changes; Plots the parametric test.
Parameters
oldId Old ID of the selected output value (after change).
newId New ID of the selected output value (after changed).
References IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.InitializeComponent().
Dispose() [1/2]
override void IG.Neural.Forms.Old.NeuralParametricTestOld.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.Old.NeuralParametricTestOld.components.
InitializeComponent() [1/2]
void IG.Neural.Forms.Old.NeuralParametricTestOld.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.Old.NeuralParametricTestOld.btnParmTestStart, IG.Neural.Forms.Old.NeuralParametricTestOld.btnParmTestStart_Click(), IG.Neural.Forms.Old.NeuralParametricTestOld.lblInfoOld, IG.Neural.Forms.Old.NeuralParametricTestOld.lblNumPointsLine, IG.Neural.Forms.Old.NeuralParametricTestOld.neuralInputControl1, IG.Neural.Forms.Old.NeuralParametricTestOld.neuralOutputValueSelector1, IG.Neural.Forms.Old.NeuralParametricTestOld.neuralOutputValueSelector1_SelectedOutputIdChanged(), IG.Neural.Forms.Old.NeuralParametricTestOld.ParmTestFGraph, IG.Neural.Forms.Old.NeuralParametricTestOld.pnlGraph, IG.Neural.Forms.NeuralOutputValueSelector.SelectedOutputIdChanged, and IG.Neural.Forms.Old.NeuralParametricTestOld.txtNumPointsLine.
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.NeuralParametricTestOld().
SetNeuralModel() [2/2]
void IG.Neural.Forms.Old.NeuralParametricTestOld.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
References IG.Neural.Forms.Old.NeuralParametricTestOld.NeuralModel.
ApplyPlotterSettingsDefault() [2/2]
void IG.Neural.Forms.Old.NeuralParametricTestOld.ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Num.InputOutputDataDefiniton.InputElementList, IG.Gr.PlotterZedGraph.IsShowPointValues, IG.Neural.Forms.Old.NeuralParametricTestOld.NeuralDataDefinition, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Neural.Forms.Old.NeuralParametricTestOld.SelectedOutputLabelText, IG.Neural.Forms.Old.NeuralParametricTestOld.SelectedParameterLabelText, IG.Gr.PlotterZedGraph.XAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabel.
ApplyPlotCurveSettingsDefault() [2/2]
void IG.Neural.Forms.Old.NeuralParametricTestOld.ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LineWidth, IG.Gr.PlotZedgraphCurve.PointBorderColor, IG.Gr.PlotZedgraphCurve.PointFillColor, and IG.Gr.PlotZedgraphCurve.PointsVisible.
PlotParametricTest() [2/2]
void IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest () inline
plots the selected outpt dependend on the selected parameter.
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Neural.Forms.Old.NeuralParametricTestOld.ApplyPlotCurveSettingsDefault(), IG.Neural.Forms.Old.NeuralParametricTestOld.ApplyPlotterSettingsDefault(), IG.Num.IVectorApproximator.CalculateOutput(), IG.Num.VectorBase.CopyPlain(), IG.Neural.Forms.Old.NeuralParametricTestOld.NumInputParameters, IG.Neural.Forms.Old.NeuralParametricTestOld.NumOutputValues, IG.Neural.Forms.Old.NeuralParametricTestOld.ParameterValues, IG.Neural.Forms.Old.NeuralParametricTestOld.SelectedOutputId, IG.Neural.Forms.Old.NeuralParametricTestOld.SelectedParameterId, IG.Neural.Forms.Old.NeuralParametricTestOld.SelectedParameterMax, IG.Neural.Forms.Old.NeuralParametricTestOld.SelectedParameterMin, IG.Neural.Forms.Old.NeuralParametricTestOld.TrainedNetwork, and IG.Neural.Forms.Old.NeuralParametricTestOld.txtNumPointsLine.
btnParmTestStart_Click() [2/2]
void IG.Neural.Forms.Old.NeuralParametricTestOld.btnParmTestStart_Click (object sender, EventArgs e) inline private
Plots the parametric test.
References IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
neuralInputControl1_SelectedParameterIdChanged() [2/2]
void IG.Neural.Forms.Old.NeuralParametricTestOld.neuralInputControl1_SelectedParameterIdChanged (int oldId, int newId) inline private
Executes when ID of the selected input parameter changes; Plots the parametric test.
Parameters
oldId Old ID of the selected output value (after change).
newId New ID of the selected output value (after changed).
References IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
neuralInputControl1_SelectedParameterMinChanged() [2/2]
void IG.Neural.Forms.Old.NeuralParametricTestOld.neuralInputControl1_SelectedParameterMinChanged (double oldValue, double newValue) inline private
Executes when minimal value of the selected parameter changes by user interaction; Plots the parametric test.
Parameters
oldValue Old value.
newValue New value.
References IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
neuralInputControl1_SelectedParameterMaxChanged() [2/2]
void IG.Neural.Forms.Old.NeuralParametricTestOld.neuralInputControl1_SelectedParameterMaxChanged (double oldValue, double newValue) inline private
Executes when maximal value of the selected parameter changes by user interaction; Plots the parametric test.
Parameters
oldValue Old value.
newValue New value.
References IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
neuralOutputValueSelector1_SelectedOutputIdChanged() [2/2]
void IG.Neural.Forms.Old.NeuralParametricTestOld.neuralOutputValueSelector1_SelectedOutputIdChanged (int oldId, int newId) inline private
Executes when ID of the selected output value changes; Plots the parametric test.
Parameters
oldId Old ID of the selected output value (after change).
newId New ID of the selected output value (after changed).
References IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
Dispose() [2/2]
override void IG.Neural.Forms.Old.NeuralParametricTestOld.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.Old.NeuralParametricTestOld.components.
InitializeComponent() [2/2]
void IG.Neural.Forms.Old.NeuralParametricTestOld.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.Old.NeuralParametricTestOld.btnParmTestStart, IG.Neural.Forms.Old.NeuralParametricTestOld.btnParmTestStart_Click(), IG.Neural.Forms.Old.NeuralParametricTestOld.lblInfoOld, IG.Neural.Forms.Old.NeuralParametricTestOld.lblNumPointsLine, IG.Neural.Forms.Old.NeuralParametricTestOld.neuralInputControl1, IG.Neural.Forms.Old.NeuralParametricTestOld.neuralOutputValueSelector1, IG.Neural.Forms.Old.NeuralParametricTestOld.neuralOutputValueSelector1_SelectedOutputIdChanged(), IG.Neural.Forms.Old.NeuralParametricTestOld.ParmTestFGraph, IG.Neural.Forms.Old.NeuralParametricTestOld.pnlGraph, IG.Neural.Forms.NeuralOutputValueSelector.SelectedOutputIdChanged, and IG.Neural.Forms.Old.NeuralParametricTestOld.txtNumPointsLine.
Member Data Documentation
_neuralModelContainerControl
INeuralModelContainer IG.Neural.Forms.Old.NeuralParametricTestOld._neuralModelContainerControl protected
_neuralModel
INeuralModel IG.Neural.Forms.Old.NeuralParametricTestOld._neuralModel private
_selectedParameterId
int IG.Neural.Forms.Old.NeuralParametricTestOld._selectedParameterId = 0 protected
_selectedOutputId
int IG.Neural.Forms.Old.NeuralParametricTestOld._selectedOutputId = 0 protected
_plotter
PlotterZedGraph IG.Neural.Forms.Old.NeuralParametricTestOld._plotter private
components
System ComponentModel IContainer IG.Neural.Forms.Old.NeuralParametricTestOld.components = null private
Required designer variable.
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.Dispose().
neuralInputControl1
NeuralParametricTestSelection IG.Neural.Forms.Old.NeuralParametricTestOld.neuralInputControl1 private
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.InitializeComponent(), and IG.Neural.Forms.Old.NeuralParametricTestOld.NeuralParametricTestOld().
pnlGraph
System Windows Forms Panel IG.Neural.Forms.Old.NeuralParametricTestOld.pnlGraph private
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.InitializeComponent().
txtNumPointsLine
System Windows Forms NumericUpDown IG.Neural.Forms.Old.NeuralParametricTestOld.txtNumPointsLine private
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.InitializeComponent(), and IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
lblNumPointsLine
System Windows Forms Label IG.Neural.Forms.Old.NeuralParametricTestOld.lblNumPointsLine private
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.InitializeComponent().
ParmTestFGraph
ZedGraph ZedGraphControl IG.Neural.Forms.Old.NeuralParametricTestOld.ParmTestFGraph private
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.InitializeComponent().
btnParmTestStart
System Windows Forms Button IG.Neural.Forms.Old.NeuralParametricTestOld.btnParmTestStart private
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.InitializeComponent().
neuralOutputValueSelector1
Forms NeuralOutputValueSelector IG.Neural.Forms.Old.NeuralParametricTestOld.neuralOutputValueSelector1 private
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.InitializeComponent().
lblInfoOld
System Windows Forms Label IG.Neural.Forms.Old.NeuralParametricTestOld.lblInfoOld private
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.InitializeComponent().
Property Documentation
NeuralModel
INeuralModel IG.Neural.Forms.Old.NeuralParametricTestOld.NeuralModel get protected set
Neural network - based model.
Contains data definition and trained neural network approximator.
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.NeuralParametricTestOld(), and IG.Neural.Forms.Old.NeuralParametricTestOld.SetNeuralModel().
TrainedNetwork
INeuralApproximator IG.Neural.Forms.Old.NeuralParametricTestOld.TrainedNetwork get
Traint artificial neural network.
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
NeuralDataDefinition
InputOutputDataDefiniton IG.Neural.Forms.Old.NeuralParametricTestOld.NeuralDataDefinition get
Neural data definition.
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.ApplyPlotterSettingsDefault().
NumInputParameters
int IG.Neural.Forms.Old.NeuralParametricTestOld.NumInputParameters get
Gets number of input parameters.
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
NumOutputValues
int IG.Neural.Forms.Old.NeuralParametricTestOld.NumOutputValues get
Gets number of output values.
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
ParameterValues
IVector IG.Neural.Forms.Old.NeuralParametricTestOld.ParameterValues get
Vector of current values of input parameters as defined by the DadaGridView.
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
MinValues
double [] IG.Neural.Forms.Old.NeuralParametricTestOld.MinValues get
Minimal values of parameters.
MaxValues
double [] IG.Neural.Forms.Old.NeuralParametricTestOld.MaxValues get
Maximal values of parameters.
SelectedParameterId
int IG.Neural.Forms.Old.NeuralParametricTestOld.SelectedParameterId get protected set
Sequential number of the selected parameter as specified by the user.
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
SelectedParameterMin
double IG.Neural.Forms.Old.NeuralParametricTestOld.SelectedParameterMin get
Minimal value of the selected parameter.
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
SelectedParameterMax
double IG.Neural.Forms.Old.NeuralParametricTestOld.SelectedParameterMax get
Maximal value of the selected parameter as specified by the user.
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
SelectedOutputId
int IG.Neural.Forms.Old.NeuralParametricTestOld.SelectedOutputId get protected set
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest().
SelectedParameterLabelText
string IG.Neural.Forms.Old.NeuralParametricTestOld.SelectedParameterLabelText get
Gets axis label text for the currently selected parameter.
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.ApplyPlotterSettingsDefault().
SelectedOutputLabelText
string IG.Neural.Forms.Old.NeuralParametricTestOld.SelectedOutputLabelText get
Gets axis label text for the currently selected output value.
Referenced by IG.Neural.Forms.Old.NeuralParametricTestOld.ApplyPlotterSettingsDefault().
Plotter
PlotterZedGraph IG.Neural.Forms.Old.NeuralParametricTestOld.Plotter get
Plotter that is used for plotting the graphs.
The documentation for this class was generated from the following files:
shelldev/extensions/ExtAppAnnApp/FormsOld/NeuralParametricTestOld.cs
shelldev/extensions/ExtAppAnnApp/FormsOld/NeuralParametricTestOld.Designer.cs