Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLANGE Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLANGE Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLANGE (DLASSQ dlassq, LSAME lsame)
DLANGE ()
double Run (string NORM, int M, int N, double[] A, int offset_a, int LDA, ref double[] WORK, int offset_work)
Private Attributes
DLASSQ _dlassq
LSAME _lsame
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLANGE returns the value of the one norm, or the Frobenius norm, or the infinity norm, or the element of largest absolute value of a real matrix A.
Description
DLANGE returns the value
DLANGE = (max(abs(A(i,j))), NORM = 'M' or 'm' ((norm1(A), NORM = '1', 'O' or 'o' ((normI(A), NORM = 'I' or 'i' ((normF(A), NORM = 'F', 'f', 'E' or 'e'
where norm1 denotes the one norm of a matrix (maximum column sum), normI denotes the infinity norm of a matrix (maximum row sum) and normF denotes the Frobenius norm of a matrix (square root of sum of squares). Note that max(abs(A(i,j))) is not a consistent matrix norm.
/summary>
Constructor & Destructor Documentation
DLANGE() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLANGE.DLANGE (DLASSQ dlassq, LSAME lsame) inline
DLANGE() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLANGE.DLANGE () inline
Member Function Documentation
Run()
double DotNumerics.LinearAlgebra.CSLapack.DLANGE.Run (string NORM, int M, int N, double[] A, int offset_a, int LDA, ref double[] WORK, int offset_work) inline
Purpose
DLANGE returns the value of the one norm, or the Frobenius norm, or the infinity norm, or the element of largest absolute value of a real matrix A.
Description
DLANGE returns the value
DLANGE = (max(abs(A(i,j))), NORM = 'M' or 'm' ((norm1(A), NORM = '1', 'O' or 'o' ((normI(A), NORM = 'I' or 'i' ((normF(A), NORM = 'F', 'f', 'E' or 'e'
where norm1 denotes the one norm of a matrix (maximum column sum), normI denotes the infinity norm of a matrix (maximum row sum) and normF denotes the Frobenius norm of a matrix (square root of sum of squares). Note that max(abs(A(i,j))) is not a consistent matrix norm.
/summary>
Parameters
NORM (input) CHARACTER*1 Specifies the value to be returned in DLANGE as described above. /param>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. When M = 0, DLANGE is set to zero. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. 0. When N = 0, DLANGE is set to zero. /param>
Parameters
A (input) DOUBLE PRECISION array, dimension (LDA,N) The m by n matrix A. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(M,1). /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (MAX(1,LWORK)), where LWORK .GE. M when NORM = 'I'; otherwise, WORK is not referenced. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLANGE.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASSQ.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLANGE.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAEXC.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELS.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELSY.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELSD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGGSVD.Run().
Member Data Documentation
_dlassq
DLASSQ DotNumerics.LinearAlgebra.CSLapack.DLANGE._dlassq private
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLANGE._lsame private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLANGE.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLANGE.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLANGE.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLANGE.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlange.cs