Doc: IGLib EXTENDED: AForge.Math.Geometry.LineSegment Class Reference
AForge.Math.Geometry.LineSegment Class Reference
The class encapsulates 2D line segment and provides some tool methods related to lines.
Public Member Functions
LineSegment (Point start, Point end)
Initializes a new instance of the LineSegment class.
float DistanceToPoint (Point point)
Calculate Euclidean distance between a point and a finite line segment.
Point? GetIntersectionWith (LineSegment other)
Finds, provided it exists, the intersection point with the specified LineSegment.
Point? GetIntersectionWith (Line other)
Finds, provided it exists, the intersection point with the specified Line.
override bool Equals (object obj)
Check if this instance of LineSegment equals to the specified one.
override int GetHashCode ()
Get hash code for this instance.
override string ToString ()
Get string representation of the class.
Static Public Member Functions
static operator Line (LineSegment segment)
Converts this LineSegment to a Line by discarding its endpoints and extending it infinitely in both directions.
static bool operator== (LineSegment line1, LineSegment line2)
Equality operator - checks if two line segments have equal parameters.
static bool operator!= (LineSegment line1, LineSegment line2)
Inequality operator - checks if two lines have different parameters.
Properties
Point Start [get]
Start point of the line segment.
Point End [get]
End point of the line segment.
float Length [get]
Get segment's length - Euclidean distance between its Start and End points.
Private Types
enum ProjectionLocation { ProjectionLocation.RayA, ProjectionLocation.SegmentAB, ProjectionLocation.RayB }
Private Member Functions
ProjectionLocation LocateProjection (Point point)
Private Attributes
readonly Point start
readonly Point end
readonly Line line
Detailed Description
The class encapsulates 2D line segment and provides some tool methods related to lines.
The class provides some methods which are related to line segments: distance to point, finding intersection point, etc.
A line segment may be converted to a Line.
Sample usage:
// create a segment
LineSegment segment = new LineSegment(new Point(0, 0), new Point(3, 4));
// get segment's length
float length = segment.Length;
// get intersection point with a line
Point? intersection = segment.GetIntersectionWith(
    new Line( new Point( -3, 8 ), new Point( 0, 4 ) ) );
Member Enumeration Documentation
ProjectionLocation
enum AForge.Math.Geometry.LineSegment.ProjectionLocation strong private
Enumerator
RayA
SegmentAB
RayB
Constructor & Destructor Documentation
LineSegment()
AForge.Math.Geometry.LineSegment.LineSegment (Point start, Point end) inline
Initializes a new instance of the LineSegment class.
Parameters
start Segment's start point.
end Segment's end point.
Exceptions
ArgumentException Thrown if the two points are the same.
References AForge.Math.Geometry.LineSegment.end, AForge.Math.Geometry.Line.FromPoints(), AForge.Math.Geometry.LineSegment.line, and AForge.Math.Geometry.LineSegment.start.
Referenced by AForge.Math.Geometry.LineSegment.Equals().
Member Function Documentation
operator Line()
static AForge.Math.Geometry.LineSegment.operator Line (LineSegment segment) inline explicit static
Converts this LineSegment to a Line by discarding its endpoints and extending it infinitely in both directions.
Parameters
segment The segment to convert to a Line.
Returns
Returns a Line that contains this segment .
References AForge.Math.Geometry.LineSegment.line.
DistanceToPoint()
float AForge.Math.Geometry.LineSegment.DistanceToPoint (Point point) inline
Calculate Euclidean distance between a point and a finite line segment.
Parameters
point The point to calculate the distance to.
Returns
Returns the Euclidean distance between this line segment and the specified point. Unlike Line.DistanceToPoint, this returns the distance from the finite segment. (0,0) is 5 units from the segment (0,5)-(0,8), but is 0 units from the line through those points.
References AForge.Point.DistanceTo(), AForge.Math.Geometry.Line.DistanceToPoint(), AForge.Math.Geometry.LineSegment.end, AForge.Math.Geometry.LineSegment.line, AForge.Math.Geometry.LineSegment.LocateProjection(), and AForge.Math.Geometry.LineSegment.start.
Referenced by AForge.Math.Geometry.Tests.LineSegmentTest.DistanceToPointTest().
GetIntersectionWith() [1/2]
Point? AForge.Math.Geometry.LineSegment.GetIntersectionWith (LineSegment other) inline
Finds, provided it exists, the intersection point with the specified LineSegment.
Parameters
other LineSegment to find intersection with.
Returns
Returns intersection point with the specified LineSegment, or null, if the two segments do not intersect.
If the two segments do not intersect, the method returns null. If the two segments share multiple points, this throws an InvalidOperationException.
Exceptions
InvalidOperationException Thrown if the segments overlap - if they have multiple points in common.
References AForge.Math.Geometry.LineSegment.end, AForge.Math.Geometry.Line.Intercept, AForge.Math.Geometry.Line.IsVertical, AForge.Math.Geometry.LineSegment.line, AForge.Math.Geometry.LineSegment.LocateProjection(), AForge.Math.Geometry.Line.Slope, and AForge.Math.Geometry.LineSegment.start.
Referenced by AForge.Math.Geometry.Tests.LineSegmentTest.CollinearIntersectionPointTest(), AForge.Math.Geometry.Tests.LineSegmentTest.CommonIntersectionPointTest(), AForge.Math.Geometry.Line.GetIntersectionWith(), AForge.Math.Geometry.Tests.LineSegmentTest.IntersectionPointTest(), and AForge.Math.Geometry.Tests.LineSegmentTest.OverlappingSegmentIntersectionPointTest().
GetIntersectionWith() [2/2]
Point? AForge.Math.Geometry.LineSegment.GetIntersectionWith (Line other) inline
Finds, provided it exists, the intersection point with the specified Line.
Parameters
other Line to find intersection with.
Returns
Returns intersection point with the specified Line, or null, if the line does not intersect with this segment.
If the line and the segment do not intersect, the method returns null. If the line and the segment share multiple points, the method throws an InvalidOperationException.
Exceptions
InvalidOperationException Thrown if this segment is a portion of other line.
References AForge.Math.Geometry.Line.GetIntersectionWith(), AForge.Math.Geometry.Line.Intercept, AForge.Math.Geometry.Line.IsVertical, AForge.Math.Geometry.LineSegment.line, AForge.Math.Geometry.LineSegment.LocateProjection(), and AForge.Math.Geometry.Line.Slope.
LocateProjection()
ProjectionLocation AForge.Math.Geometry.LineSegment.LocateProjection (Point point) inline private
References AForge.Math.Geometry.LineSegment.end, AForge.Math.Geometry.LineSegment.start, AForge.Point.X, and AForge.Point.Y.
Referenced by AForge.Math.Geometry.LineSegment.DistanceToPoint(), and AForge.Math.Geometry.LineSegment.GetIntersectionWith().
operator==()
static bool AForge.Math.Geometry.LineSegment.operator== (LineSegment line1, LineSegment line2) inline static
Equality operator - checks if two line segments have equal parameters.
Parameters
line1 First line segment to check.
line2 Second line segment to check.
Returns
Returns true if parameters of specified line segments are equal.
References AForge.Math.Geometry.LineSegment.end, and AForge.Math.Geometry.LineSegment.start.
operator!=()
static bool AForge.Math.Geometry.LineSegment.operator!= (LineSegment line1, LineSegment line2) inline static
Inequality operator - checks if two lines have different parameters.
Parameters
line1 First line segment to check.
line2 Second line segment to check.
Returns
Returns true if parameters of specified line segments are not equal.
Equals()
override bool AForge.Math.Geometry.LineSegment.Equals (object obj) inline
Check if this instance of LineSegment equals to the specified one.
Parameters
obj Another line segment to check equalty to.
Returns
Return true if objects are equal.
References AForge.Math.Geometry.LineSegment.LineSegment().
GetHashCode()
override int AForge.Math.Geometry.LineSegment.GetHashCode () inline
Get hash code for this instance.
Returns
Returns the hash code for this instance.
References AForge.Math.Geometry.LineSegment.end, AForge.Point.GetHashCode(), and AForge.Math.Geometry.LineSegment.start.
ToString()
override string AForge.Math.Geometry.LineSegment.ToString () inline
Get string representation of the class.
Returns
Returns string, which contains values of the like in readable form.
References AForge.Math.Geometry.LineSegment.end, and AForge.Math.Geometry.LineSegment.start.
Member Data Documentation
start
readonly Point AForge.Math.Geometry.LineSegment.start private
Referenced by AForge.Math.Geometry.LineSegment.DistanceToPoint(), AForge.Math.Geometry.LineSegment.GetHashCode(), AForge.Math.Geometry.LineSegment.GetIntersectionWith(), AForge.Math.Geometry.LineSegment.LineSegment(), AForge.Math.Geometry.LineSegment.LocateProjection(), AForge.Math.Geometry.LineSegment.operator==(), and AForge.Math.Geometry.LineSegment.ToString().
end
readonly Point AForge.Math.Geometry.LineSegment.end private
Referenced by AForge.Math.Geometry.LineSegment.DistanceToPoint(), AForge.Math.Geometry.LineSegment.GetHashCode(), AForge.Math.Geometry.LineSegment.GetIntersectionWith(), AForge.Math.Geometry.LineSegment.LineSegment(), AForge.Math.Geometry.LineSegment.LocateProjection(), AForge.Math.Geometry.LineSegment.operator==(), and AForge.Math.Geometry.LineSegment.ToString().
line
readonly Line AForge.Math.Geometry.LineSegment.line private
Referenced by AForge.Math.Geometry.LineSegment.DistanceToPoint(), AForge.Math.Geometry.LineSegment.GetIntersectionWith(), AForge.Math.Geometry.LineSegment.LineSegment(), and AForge.Math.Geometry.LineSegment.operator Line().
Property Documentation
Start
Point AForge.Math.Geometry.LineSegment.Start get
Start point of the line segment.
End
Point AForge.Math.Geometry.LineSegment.End get
End point of the line segment.
Length
float AForge.Math.Geometry.LineSegment.Length get
Get segment's length - Euclidean distance between its Start and End points.
Referenced by AForge.Math.Geometry.Tests.LineSegmentTest.LengthTest().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Math/Geometry/LineSegment.cs