Doc: IGLib EXTENDED: NUnit.Framework.Internal.TestResultOutputTests Class Reference
NUnit.Framework.Internal.TestResultOutputTests Class Reference
Public Member Functions
void SetUp ()
void IfNothingIsWritten_OutputIsEmpty ()
void CanWriteOutputToResult ()
void CanWriteOutputToResult_Multiple ()
void IfNothingIsWritten_XmlOutputIsEmpty ()
void CanWriteOutputToResult_XmlOutput ()
void CanWriteOutputToResult_Multiple_XmlOutput ()
void WriteToTestContext ()
Private Member Functions
void FakeMethod ()
Private Attributes
TestResult _result
Static Private Attributes
const string SOME_TEXT = "This text should be part of the result."
static readonly string NL = NUnit.Env.NewLine
Member Function Documentation
SetUp()
void NUnit.Framework.Internal.TestResultOutputTests.SetUp () inline
References NUnit.Framework.Internal.TestResultOutputTests._result.
IfNothingIsWritten_OutputIsEmpty()
void NUnit.Framework.Internal.TestResultOutputTests.IfNothingIsWritten_OutputIsEmpty () inline
References NUnit.Framework.Internal.TestResultOutputTests._result, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestResult.Output, and NUnit.Framework.Assert.That().
CanWriteOutputToResult()
void NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult () inline
References NUnit.Framework.Internal.TestResultOutputTests._result, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestResultOutputTests.NL, NUnit.Framework.Internal.TestResult.Output, NUnit.Framework.Internal.TestResult.OutWriter, NUnit.Framework.Internal.TestResultOutputTests.SOME_TEXT, and NUnit.Framework.Assert.That().
CanWriteOutputToResult_Multiple()
void NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_Multiple () inline
References NUnit.Framework.Internal.TestResultOutputTests._result, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestResultOutputTests.NL, NUnit.Framework.Internal.TestResult.Output, NUnit.Framework.Internal.TestResult.OutWriter, NUnit.Framework.Internal.TestResultOutputTests.SOME_TEXT, and NUnit.Framework.Assert.That().
IfNothingIsWritten_XmlOutputIsEmpty()
void NUnit.Framework.Internal.TestResultOutputTests.IfNothingIsWritten_XmlOutputIsEmpty () inline
References NUnit.Framework.Internal.TestResultOutputTests._result, NUnit.Framework.Is.Null, NUnit.Framework.Interfaces.TNode.SelectSingleNode(), NUnit.Framework.Assert.That(), and NUnit.Framework.Internal.TestResult.ToXml().
CanWriteOutputToResult_XmlOutput()
void NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_XmlOutput () inline
References NUnit.Framework.Internal.TestResultOutputTests._result, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestResultOutputTests.NL, NUnit.Framework.Assert.NotNull(), NUnit.Framework.Internal.TestResult.OutWriter, NUnit.Framework.Interfaces.TNode.SelectSingleNode(), NUnit.Framework.Internal.TestResultOutputTests.SOME_TEXT, NUnit.Framework.Assert.That(), and NUnit.Framework.Internal.TestResult.ToXml().
CanWriteOutputToResult_Multiple_XmlOutput()
void NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_Multiple_XmlOutput () inline
References NUnit.Framework.Internal.TestResultOutputTests._result, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestResultOutputTests.NL, NUnit.Framework.Assert.NotNull(), NUnit.Framework.Internal.TestResult.OutWriter, NUnit.Framework.Interfaces.TNode.SelectSingleNode(), NUnit.Framework.Internal.TestResultOutputTests.SOME_TEXT, NUnit.Framework.Assert.That(), and NUnit.Framework.Internal.TestResult.ToXml().
WriteToTestContext()
void NUnit.Framework.Internal.TestResultOutputTests.WriteToTestContext () inline
References NUnit.Framework.TestContext.WriteLine().
FakeMethod()
void NUnit.Framework.Internal.TestResultOutputTests.FakeMethod () inline private
Member Data Documentation
SOME_TEXT
const string NUnit.Framework.Internal.TestResultOutputTests.SOME_TEXT = "This text should be part of the result." static private
Referenced by NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_Multiple(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_Multiple_XmlOutput(), and NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_XmlOutput().
NL
readonly string NUnit.Framework.Internal.TestResultOutputTests.NL = NUnit.Env.NewLine static private
Referenced by NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_Multiple(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_Multiple_XmlOutput(), and NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_XmlOutput().
_result
TestResult NUnit.Framework.Internal.TestResultOutputTests._result private
Referenced by NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_Multiple(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_Multiple_XmlOutput(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_XmlOutput(), NUnit.Framework.Internal.TestResultOutputTests.IfNothingIsWritten_OutputIsEmpty(), NUnit.Framework.Internal.TestResultOutputTests.IfNothingIsWritten_XmlOutputIsEmpty(), and NUnit.Framework.Internal.TestResultOutputTests.SetUp().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/TestResultOutputTests.cs