Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGERQ2 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGERQ2 Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGERQ2 (DLARF dlarf, DLARFG dlarfg, XERBLA xerbla)
DGERQ2 ()
void Run (int M, int N, ref double[] A, int offset_a, int LDA, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
DLARF _dlarf
DLARFG _dlarfg
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGERQ2 computes an RQ factorization of a real m by n matrix A: A = R * Q.
/summary>
Constructor & Destructor Documentation
DGERQ2() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGERQ2.DGERQ2 (DLARF dlarf, DLARFG dlarfg, XERBLA xerbla) inline
DGERQ2() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGERQ2.DGERQ2 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGERQ2.Run (int M, int N, ref double[] A, int offset_a, int LDA, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
DGERQ2 computes an RQ factorization of a real m by n matrix A: A = R * Q.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the m by n matrix A. On exit, if m .LE. n, the upper triangle of the subarray A(1:m,n-m+1:n) contains the m by m upper triangular matrix R; if m .GE. n, the elements on and above the (m-n)-th subdiagonal contain the m by n upper trapezoidal matrix R; the remaining elements, with the array TAU, represent the orthogonal matrix Q as a product of elementary reflectors (see Further Details). /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
TAU (output) DOUBLE PRECISION array, dimension (min(M,N)) The scalar factors of the elementary reflectors (see Further Details). /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (M) /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.DGERQ2.ONE, DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARF.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGERQF.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGGSVP.Run().
Member Data Documentation
_dlarf
DLARF DotNumerics.LinearAlgebra.CSLapack.DGERQ2._dlarf private
_dlarfg
DLARFG DotNumerics.LinearAlgebra.CSLapack.DGERQ2._dlarfg private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGERQ2._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGERQ2.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGERQ2.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgerq2.cs