Doc: IGLib EXTENDED: Snapshot_Maker.MainForm Class Reference
Snapshot_Maker.MainForm Class Reference
Public Member Functions
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void MainForm_Load (object sender, EventArgs e)
void MainForm_FormClosing (object sender, FormClosingEventArgs e)
void EnableConnectionControls (bool enable)
void devicesCombo_SelectedIndexChanged (object sender, EventArgs e)
void EnumeratedSupportedFrameSizes (VideoCaptureDevice videoDevice)
void connectButton_Click (object sender, EventArgs e)
void disconnectButton_Click (object sender, EventArgs e)
void Disconnect ()
void triggerButton_Click (object sender, EventArgs e)
void videoDevice_SnapshotFrame (object sender, NewFrameEventArgs eventArgs)
void ShowSnapshot (Bitmap snapshot)
void snapshotForm_FormClosed (object sender, FormClosedEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
FilterInfoCollection videoDevices
VideoCaptureDevice videoDevice
VideoCapabilities[] videoCapabilities
VideoCapabilities[] snapshotCapabilities
SnapshotForm snapshotForm = null
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Label label1
System.Windows.Forms.ComboBox devicesCombo
System.Windows.Forms.Label label2
System.Windows.Forms.ComboBox videoResolutionsCombo
System.Windows.Forms.ComboBox snapshotResolutionsCombo
System.Windows.Forms.Label label3
System.Windows.Forms.Button connectButton
System.Windows.Forms.Button disconnectButton
System.Windows.Forms.Panel panel1
AForge.Controls.VideoSourcePlayer videoSourcePlayer
System.Windows.Forms.ToolTip toolTip
System.Windows.Forms.Button triggerButton
Constructor & Destructor Documentation
MainForm()
Snapshot_Maker.MainForm.MainForm () inline
References Snapshot_Maker.MainForm.InitializeComponent().
Member Function Documentation
MainForm_Load()
void Snapshot_Maker.MainForm.MainForm_Load (object sender, EventArgs e) inline private
References Snapshot_Maker.MainForm.devicesCombo, Snapshot_Maker.MainForm.EnableConnectionControls(), AForge.Video.DirectShow.FilterInfo.Name, Snapshot_Maker.MainForm.videoDevices, and AForge.Video.DirectShow.FilterCategory.VideoInputDevice.
Referenced by Snapshot_Maker.MainForm.InitializeComponent().
MainForm_FormClosing()
void Snapshot_Maker.MainForm.MainForm_FormClosing (object sender, FormClosingEventArgs e) inline private
References Snapshot_Maker.MainForm.Disconnect().
Referenced by Snapshot_Maker.MainForm.InitializeComponent().
EnableConnectionControls()
void Snapshot_Maker.MainForm.EnableConnectionControls (bool enable) inline private
References Snapshot_Maker.MainForm.connectButton, Snapshot_Maker.MainForm.devicesCombo, Snapshot_Maker.MainForm.disconnectButton, Snapshot_Maker.MainForm.snapshotCapabilities, Snapshot_Maker.MainForm.snapshotResolutionsCombo, Snapshot_Maker.MainForm.triggerButton, and Snapshot_Maker.MainForm.videoResolutionsCombo.
Referenced by Snapshot_Maker.MainForm.connectButton_Click(), Snapshot_Maker.MainForm.Disconnect(), and Snapshot_Maker.MainForm.MainForm_Load().
devicesCombo_SelectedIndexChanged()
void Snapshot_Maker.MainForm.devicesCombo_SelectedIndexChanged (object sender, EventArgs e) inline private
References Snapshot_Maker.MainForm.devicesCombo, Snapshot_Maker.MainForm.EnumeratedSupportedFrameSizes(), Snapshot_Maker.MainForm.videoDevice, and Snapshot_Maker.MainForm.videoDevices.
Referenced by Snapshot_Maker.MainForm.InitializeComponent().
EnumeratedSupportedFrameSizes()
void Snapshot_Maker.MainForm.EnumeratedSupportedFrameSizes (VideoCaptureDevice videoDevice) inline private
References AForge.Video.DirectShow.VideoCapabilities.FrameSize, Snapshot_Maker.MainForm.snapshotCapabilities, AForge.Video.DirectShow.VideoCaptureDevice.SnapshotCapabilities, Snapshot_Maker.MainForm.snapshotResolutionsCombo, Snapshot_Maker.MainForm.videoCapabilities, AForge.Video.DirectShow.VideoCaptureDevice.VideoCapabilities, Snapshot_Maker.MainForm.videoDevice, and Snapshot_Maker.MainForm.videoResolutionsCombo.
Referenced by Snapshot_Maker.MainForm.devicesCombo_SelectedIndexChanged().
connectButton_Click()
void Snapshot_Maker.MainForm.connectButton_Click (object sender, EventArgs e) inline private
References AForge.Video.DirectShow.VideoCaptureDevice.DesiredFrameSize, AForge.Video.DirectShow.VideoCaptureDevice.DesiredSnapshotSize, Snapshot_Maker.MainForm.EnableConnectionControls(), AForge.Video.NewFrameEventHandler(), AForge.Video.DirectShow.VideoCaptureDevice.ProvideSnapshots, Snapshot_Maker.MainForm.snapshotCapabilities, AForge.Video.DirectShow.VideoCaptureDevice.SnapshotFrame, Snapshot_Maker.MainForm.snapshotResolutionsCombo, Snapshot_Maker.MainForm.videoCapabilities, Snapshot_Maker.MainForm.videoDevice, Snapshot_Maker.MainForm.videoDevice_SnapshotFrame(), Snapshot_Maker.MainForm.videoResolutionsCombo, and Snapshot_Maker.MainForm.videoSourcePlayer.
Referenced by Snapshot_Maker.MainForm.InitializeComponent().
disconnectButton_Click()
void Snapshot_Maker.MainForm.disconnectButton_Click (object sender, EventArgs e) inline private
References Snapshot_Maker.MainForm.Disconnect().
Referenced by Snapshot_Maker.MainForm.InitializeComponent().
Disconnect()
void Snapshot_Maker.MainForm.Disconnect () inline private
References Snapshot_Maker.MainForm.EnableConnectionControls(), AForge.Video.NewFrameEventHandler(), AForge.Video.DirectShow.VideoCaptureDevice.ProvideSnapshots, AForge.Video.DirectShow.VideoCaptureDevice.SnapshotFrame, Snapshot_Maker.MainForm.videoDevice, Snapshot_Maker.MainForm.videoDevice_SnapshotFrame(), and Snapshot_Maker.MainForm.videoSourcePlayer.
Referenced by Snapshot_Maker.MainForm.disconnectButton_Click(), and Snapshot_Maker.MainForm.MainForm_FormClosing().
triggerButton_Click()
void Snapshot_Maker.MainForm.triggerButton_Click (object sender, EventArgs e) inline private
References AForge.Video.DirectShow.VideoCaptureDevice.ProvideSnapshots, AForge.Video.DirectShow.VideoCaptureDevice.SimulateTrigger(), and Snapshot_Maker.MainForm.videoDevice.
Referenced by Snapshot_Maker.MainForm.InitializeComponent().
videoDevice_SnapshotFrame()
void Snapshot_Maker.MainForm.videoDevice_SnapshotFrame (object sender, NewFrameEventArgs eventArgs) inline private
References AForge.Video.NewFrameEventArgs.Frame, and Snapshot_Maker.MainForm.ShowSnapshot().
Referenced by Snapshot_Maker.MainForm.connectButton_Click(), and Snapshot_Maker.MainForm.Disconnect().
ShowSnapshot()
void Snapshot_Maker.MainForm.ShowSnapshot (Bitmap snapshot) inline private
References Snapshot_Maker.SnapshotForm.SetImage(), Snapshot_Maker.MainForm.snapshotForm, and Snapshot_Maker.MainForm.snapshotForm_FormClosed().
Referenced by Snapshot_Maker.MainForm.videoDevice_SnapshotFrame().
snapshotForm_FormClosed()
void Snapshot_Maker.MainForm.snapshotForm_FormClosed (object sender, FormClosedEventArgs e) inline private
References Snapshot_Maker.MainForm.snapshotForm.
Referenced by Snapshot_Maker.MainForm.ShowSnapshot().
Dispose()
override void Snapshot_Maker.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References Snapshot_Maker.MainForm.components.
InitializeComponent()
void Snapshot_Maker.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References Snapshot_Maker.MainForm.components, Snapshot_Maker.MainForm.connectButton, Snapshot_Maker.MainForm.connectButton_Click(), Snapshot_Maker.MainForm.devicesCombo, Snapshot_Maker.MainForm.devicesCombo_SelectedIndexChanged(), Snapshot_Maker.MainForm.disconnectButton, Snapshot_Maker.MainForm.disconnectButton_Click(), Snapshot_Maker.MainForm.label1, Snapshot_Maker.MainForm.label2, Snapshot_Maker.MainForm.label3, Snapshot_Maker.MainForm.MainForm_FormClosing(), Snapshot_Maker.MainForm.MainForm_Load(), Snapshot_Maker.MainForm.panel1, Snapshot_Maker.MainForm.snapshotResolutionsCombo, Snapshot_Maker.MainForm.toolTip, Snapshot_Maker.MainForm.triggerButton, Snapshot_Maker.MainForm.triggerButton_Click(), Snapshot_Maker.MainForm.videoResolutionsCombo, and Snapshot_Maker.MainForm.videoSourcePlayer.
Referenced by Snapshot_Maker.MainForm.MainForm().
Member Data Documentation
videoDevices
FilterInfoCollection Snapshot_Maker.MainForm.videoDevices private
Referenced by Snapshot_Maker.MainForm.devicesCombo_SelectedIndexChanged(), and Snapshot_Maker.MainForm.MainForm_Load().
videoDevice
VideoCaptureDevice Snapshot_Maker.MainForm.videoDevice private
Referenced by Snapshot_Maker.MainForm.connectButton_Click(), Snapshot_Maker.MainForm.devicesCombo_SelectedIndexChanged(), Snapshot_Maker.MainForm.Disconnect(), Snapshot_Maker.MainForm.EnumeratedSupportedFrameSizes(), and Snapshot_Maker.MainForm.triggerButton_Click().
videoCapabilities
VideoCapabilities [] Snapshot_Maker.MainForm.videoCapabilities private
Referenced by Snapshot_Maker.MainForm.connectButton_Click(), and Snapshot_Maker.MainForm.EnumeratedSupportedFrameSizes().
snapshotCapabilities
VideoCapabilities [] Snapshot_Maker.MainForm.snapshotCapabilities private
Referenced by Snapshot_Maker.MainForm.connectButton_Click(), Snapshot_Maker.MainForm.EnableConnectionControls(), and Snapshot_Maker.MainForm.EnumeratedSupportedFrameSizes().
snapshotForm
SnapshotForm Snapshot_Maker.MainForm.snapshotForm = null private
Referenced by Snapshot_Maker.MainForm.ShowSnapshot(), and Snapshot_Maker.MainForm.snapshotForm_FormClosed().
components
System.ComponentModel.IContainer Snapshot_Maker.MainForm.components = null private
Required designer variable.
Referenced by Snapshot_Maker.MainForm.Dispose(), and Snapshot_Maker.MainForm.InitializeComponent().
label1
System.Windows.Forms.Label Snapshot_Maker.MainForm.label1 private
Referenced by Snapshot_Maker.MainForm.InitializeComponent().
devicesCombo
System.Windows.Forms.ComboBox Snapshot_Maker.MainForm.devicesCombo private
Referenced by Snapshot_Maker.MainForm.devicesCombo_SelectedIndexChanged(), Snapshot_Maker.MainForm.EnableConnectionControls(), Snapshot_Maker.MainForm.InitializeComponent(), and Snapshot_Maker.MainForm.MainForm_Load().
label2
System.Windows.Forms.Label Snapshot_Maker.MainForm.label2 private
Referenced by Snapshot_Maker.MainForm.InitializeComponent().
videoResolutionsCombo
System.Windows.Forms.ComboBox Snapshot_Maker.MainForm.videoResolutionsCombo private
Referenced by Snapshot_Maker.MainForm.connectButton_Click(), Snapshot_Maker.MainForm.EnableConnectionControls(), Snapshot_Maker.MainForm.EnumeratedSupportedFrameSizes(), and Snapshot_Maker.MainForm.InitializeComponent().
snapshotResolutionsCombo
System.Windows.Forms.ComboBox Snapshot_Maker.MainForm.snapshotResolutionsCombo private
Referenced by Snapshot_Maker.MainForm.connectButton_Click(), Snapshot_Maker.MainForm.EnableConnectionControls(), Snapshot_Maker.MainForm.EnumeratedSupportedFrameSizes(), and Snapshot_Maker.MainForm.InitializeComponent().
label3
System.Windows.Forms.Label Snapshot_Maker.MainForm.label3 private
Referenced by Snapshot_Maker.MainForm.InitializeComponent().
connectButton
System.Windows.Forms.Button Snapshot_Maker.MainForm.connectButton private
Referenced by Snapshot_Maker.MainForm.EnableConnectionControls(), and Snapshot_Maker.MainForm.InitializeComponent().
disconnectButton
System.Windows.Forms.Button Snapshot_Maker.MainForm.disconnectButton private
Referenced by Snapshot_Maker.MainForm.EnableConnectionControls(), and Snapshot_Maker.MainForm.InitializeComponent().
panel1
System.Windows.Forms.Panel Snapshot_Maker.MainForm.panel1 private
Referenced by Snapshot_Maker.MainForm.InitializeComponent().
videoSourcePlayer
AForge.Controls.VideoSourcePlayer Snapshot_Maker.MainForm.videoSourcePlayer private
Referenced by Snapshot_Maker.MainForm.connectButton_Click(), Snapshot_Maker.MainForm.Disconnect(), and Snapshot_Maker.MainForm.InitializeComponent().
toolTip
System.Windows.Forms.ToolTip Snapshot_Maker.MainForm.toolTip private
Referenced by Snapshot_Maker.MainForm.InitializeComponent().
triggerButton
System.Windows.Forms.Button Snapshot_Maker.MainForm.triggerButton private
Referenced by Snapshot_Maker.MainForm.EnableConnectionControls(), and Snapshot_Maker.MainForm.InitializeComponent().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Video/Snapshot Maker/MainForm.cs
shelldev/lib_ann/aforge.net/Samples/Video/Snapshot Maker/MainForm.Designer.cs