Doc: IGLib EXTENDED: alglib.elliptic Class Reference
alglib.elliptic Class Reference
Static Public Member Functions
static double ellipticintegralk (double m)
static double ellipticintegralkhighprecision (double m1)
static double incompleteellipticintegralk (double phi, double m)
static double ellipticintegrale (double m)
static double incompleteellipticintegrale (double phi, double m)
static double ellipticintegralk (double m)
static double ellipticintegralkhighprecision (double m1)
static double incompleteellipticintegralk (double phi, double m)
static double ellipticintegrale (double m)
static double incompleteellipticintegrale (double phi, double m)
Member Function Documentation
ellipticintegralk() [1/2]
static double alglib.elliptic.ellipticintegralk (double m) inline static
References alglib.elliptic.ellipticintegralkhighprecision().
Referenced by alglib.ellipticintegralk(), alglib.elliptic.incompleteellipticintegrale(), and alglib.elliptic.incompleteellipticintegralk().
ellipticintegralkhighprecision() [1/2]
static double alglib.elliptic.ellipticintegralkhighprecision (double m1) inline static
References alglib.math.machineepsilon.
Referenced by alglib.elliptic.ellipticintegralk(), and alglib.ellipticintegralkhighprecision().
incompleteellipticintegralk() [1/2]
static double alglib.elliptic.incompleteellipticintegralk (double phi, double m) inline static
References alglib.elliptic.ellipticintegralk(), and alglib.math.machineepsilon.
Referenced by alglib.incompleteellipticintegralk(), and alglib.elliptic.incompleteellipticintegralk().
ellipticintegrale() [1/2]
static double alglib.elliptic.ellipticintegrale (double m) inline static
References alglib.ap.assert().
Referenced by alglib.ellipticintegrale(), and alglib.elliptic.incompleteellipticintegrale().
incompleteellipticintegrale() [1/2]
static double alglib.elliptic.incompleteellipticintegrale (double phi, double m) inline static
References alglib.elliptic.ellipticintegrale(), alglib.elliptic.ellipticintegralk(), and alglib.math.machineepsilon.
Referenced by alglib.incompleteellipticintegrale(), and alglib.elliptic.incompleteellipticintegrale().
ellipticintegralk() [2/2]
static double alglib.elliptic.ellipticintegralk (double m) inline static
References alglib.elliptic.ellipticintegralkhighprecision().
ellipticintegralkhighprecision() [2/2]
static double alglib.elliptic.ellipticintegralkhighprecision (double m1) inline static
References alglib.math.machineepsilon.
incompleteellipticintegralk() [2/2]
static double alglib.elliptic.incompleteellipticintegralk (double phi, double m) inline static
References alglib.elliptic.ellipticintegralk(), alglib.elliptic.incompleteellipticintegralk(), and alglib.math.machineepsilon.
ellipticintegrale() [2/2]
static double alglib.elliptic.ellipticintegrale (double m) inline static
References alglib.ap.assert().
incompleteellipticintegrale() [2/2]
static double alglib.elliptic.incompleteellipticintegrale (double phi, double m) inline static
References alglib.elliptic.ellipticintegrale(), alglib.elliptic.ellipticintegralk(), alglib.elliptic.incompleteellipticintegrale(), and alglib.math.machineepsilon.
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/specialfunctions.cs