Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAPY2 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAPY2 Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAPY2 ()
double Run (double X, double Y)
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAPY2 returns sqrt(x**2+y**2), taking care not to cause unnecessary overflow.
/summary>
Constructor & Destructor Documentation
DLAPY2()
DotNumerics.LinearAlgebra.CSLapack.DLAPY2.DLAPY2 () inline
Member Function Documentation
Run()
double DotNumerics.LinearAlgebra.CSLapack.DLAPY2.Run (double X, double Y) inline
Purpose
DLAPY2 returns sqrt(x**2+y**2), taking care not to cause unnecessary overflow.
/summary>
Parameters
X (input) DOUBLE PRECISION /param>
Parameters
Y (input) DOUBLE PRECISION X and Y specify the values x and y. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLAPY2.ONE, and DotNumerics.LinearAlgebra.CSLapack.DLAPY2.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTERF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANV2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED8.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD7.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD2.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run().
Member Data Documentation
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAPY2.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAPY2.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAPY2.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAPY2.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlapy2.cs