Doc: IGLib EXTENDED: Meta.Numerics.Matrices.CholeskyDecomposition Class Reference
Meta.Numerics.Matrices.CholeskyDecomposition Class Reference
Represents the Cholesky Decomposition of a symmetric, positive definite matrix.
Public Member Functions
SquareMatrix SquareRootMatrix ()
Returns the Cholesky square root matrix.
ColumnVector Solve (IList< double > rhs)
Computes the solution vector that, when multiplied by the original matrix, produces the given left-hand side vector.
SymmetricMatrix Inverse ()
Computes the inverse of the original matrix.
double Determinant ()
Computes the determinant of the original matrix.
Properties
int Dimension [get]
Gets the dimension of the system.
Detailed Description
Represents the Cholesky Decomposition of a symmetric, positive definite matrix.
A Cholesky decomposition represents a matrix as the product of a lower-left triangular matrix and its transpose. For example:
The Choleksy decomposition of a symmetric, positive definite matrix can be obtained using the SymmetricMatrix.CholeskyDecomposition method of the SymmetricMatrix class.
Here is an example that uses a Cholesky decomposition to solve a linear algebra problem.
// Solve Ax = b via Cholesky decomposition
CholeskyDecomposition CD = A.CholsekyDecomposition();
ColumnVector b = new ColumnVector(1.0, 2.0, 3.0);
ColumnVector x CD.Solve(b);
See also
SymmetricMatrix.CholeskyDecomposition
Member Function Documentation
SquareRootMatrix()
SquareMatrix Meta.Numerics.Matrices.CholeskyDecomposition.SquareRootMatrix () inline
Returns the Cholesky square root matrix.
Returns
A lower-left triangular matrix A, such that A AT = M.
References Meta.Numerics.Matrices.CholeskyDecomposition.Dimension.
Solve()
ColumnVector Meta.Numerics.Matrices.CholeskyDecomposition.Solve (IList< double > rhs) inline
Computes the solution vector that, when multiplied by the original matrix, produces the given left-hand side vector.
Parameters
rhs The right-hand-side vector.
Returns
The left-hand-side (solution) vector.
References Meta.Numerics.Matrices.CholeskyDecomposition.Dimension.
Referenced by Meta.Numerics.Statistics.MultivariateSample.LinearRegression_Internal().
Inverse()
SymmetricMatrix Meta.Numerics.Matrices.CholeskyDecomposition.Inverse () inline
Computes the inverse of the original matrix.
Returns
M-1
References Meta.Numerics.Matrices.CholeskyDecomposition.Dimension.
Referenced by Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToFunction(), Meta.Numerics.Statistics.Distributions.BetaDistribution.FitToSample(), Meta.Numerics.Statistics.MultivariateSample.LinearRegression_Internal(), Meta.Numerics.Statistics.Sample.MaximumLikelihoodFit(), and Test.SymmetricMatrixTest.SymmetricMatrixDecomposition().
Determinant()
double Meta.Numerics.Matrices.CholeskyDecomposition.Determinant () inline
Computes the determinant of the original matrix.
Returns
det M
References Meta.Numerics.Matrices.CholeskyDecomposition.Dimension.
Referenced by Test.SymmetricMatrixTest.CatalanHankelMatrixDeterminant(), and Test.MultiIntegrateTest.GaussianIntegrals().
Property Documentation
Dimension
int Meta.Numerics.Matrices.CholeskyDecomposition.Dimension get
Gets the dimension of the system.
Referenced by Meta.Numerics.Matrices.CholeskyDecomposition.Determinant(), Meta.Numerics.Matrices.CholeskyDecomposition.Inverse(), Meta.Numerics.Matrices.CholeskyDecomposition.Solve(), Meta.Numerics.Matrices.CholeskyDecomposition.SquareRootMatrix(), and Test.SymmetricMatrixTest.SymmetricMatrixDecomposition().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Matrices/CholeskyDecomposition.cs