Doc: IGLib EXTENDED: alglib.jarquebera Class Reference
alglib.jarquebera Class Reference
Static Public Member Functions
static void jarqueberatest (double[] x, int n, ref double p)
static void jarqueberatest (double[] x, int n, ref double p)
Static Private Member Functions
static void jarqueberastatistic (double[] x, int n, ref double s)
static double jarqueberaapprox (int n, double s)
static double jbtbl5 (double s)
static double jbtbl6 (double s)
static double jbtbl7 (double s)
static double jbtbl8 (double s)
static double jbtbl9 (double s)
static double jbtbl10 (double s)
static double jbtbl11 (double s)
static double jbtbl12 (double s)
static double jbtbl13 (double s)
static double jbtbl14 (double s)
static double jbtbl15 (double s)
static double jbtbl16 (double s)
static double jbtbl17 (double s)
static double jbtbl18 (double s)
static double jbtbl19 (double s)
static double jbtbl20 (double s)
static double jbtbl30 (double s)
static double jbtbl50 (double s)
static double jbtbl65 (double s)
static double jbtbl100 (double s)
static double jbtbl130 (double s)
static double jbtbl200 (double s)
static double jbtbl301 (double s)
static double jbtbl501 (double s)
static double jbtbl701 (double s)
static double jbtbl1401 (double s)
static void jbcheb (double x, double c, ref double tj, ref double tj1, ref double r)
static void jarqueberastatistic (double[] x, int n, ref double s)
static double jarqueberaapprox (int n, double s)
static double jbtbl5 (double s)
static double jbtbl6 (double s)
static double jbtbl7 (double s)
static double jbtbl8 (double s)
static double jbtbl9 (double s)
static double jbtbl10 (double s)
static double jbtbl11 (double s)
static double jbtbl12 (double s)
static double jbtbl13 (double s)
static double jbtbl14 (double s)
static double jbtbl15 (double s)
static double jbtbl16 (double s)
static double jbtbl17 (double s)
static double jbtbl18 (double s)
static double jbtbl19 (double s)
static double jbtbl20 (double s)
static double jbtbl30 (double s)
static double jbtbl50 (double s)
static double jbtbl65 (double s)
static double jbtbl100 (double s)
static double jbtbl130 (double s)
static double jbtbl200 (double s)
static double jbtbl301 (double s)
static double jbtbl501 (double s)
static double jbtbl701 (double s)
static double jbtbl1401 (double s)
static void jbcheb (double x, double c, ref double tj, ref double tj1, ref double r)
Member Function Documentation
jarqueberatest() [1/2]
static void alglib.jarquebera.jarqueberatest (double[] x, int n, ref double p) inline static
References alglib.jarquebera.jarqueberaapprox(), and alglib.jarquebera.jarqueberastatistic().
Referenced by alglib.jarqueberatest().
jarqueberastatistic() [1/2]
static void alglib.jarquebera.jarqueberastatistic (double[] x, int n, ref double s) inline static private
References alglib.ap.assert(), and alglib.math.sqr().
Referenced by alglib.jarquebera.jarqueberatest().
jarqueberaapprox() [1/2]
static double alglib.jarquebera.jarqueberaapprox (int n, double s) inline static private
References alglib.jarquebera.jbtbl10(), alglib.jarquebera.jbtbl100(), alglib.jarquebera.jbtbl11(), alglib.jarquebera.jbtbl12(), alglib.jarquebera.jbtbl13(), alglib.jarquebera.jbtbl130(), alglib.jarquebera.jbtbl14(), alglib.jarquebera.jbtbl1401(), alglib.jarquebera.jbtbl15(), alglib.jarquebera.jbtbl16(), alglib.jarquebera.jbtbl17(), alglib.jarquebera.jbtbl18(), alglib.jarquebera.jbtbl19(), alglib.jarquebera.jbtbl20(), alglib.jarquebera.jbtbl200(), alglib.jarquebera.jbtbl30(), alglib.jarquebera.jbtbl301(), alglib.jarquebera.jbtbl5(), alglib.jarquebera.jbtbl50(), alglib.jarquebera.jbtbl501(), alglib.jarquebera.jbtbl6(), alglib.jarquebera.jbtbl65(), alglib.jarquebera.jbtbl7(), alglib.jarquebera.jbtbl701(), alglib.jarquebera.jbtbl8(), and alglib.jarquebera.jbtbl9().
Referenced by alglib.jarquebera.jarqueberatest().
jbtbl5() [1/2]
static double alglib.jarquebera.jbtbl5 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl6() [1/2]
static double alglib.jarquebera.jbtbl6 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl7() [1/2]
static double alglib.jarquebera.jbtbl7 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl8() [1/2]
static double alglib.jarquebera.jbtbl8 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl9() [1/2]
static double alglib.jarquebera.jbtbl9 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl10() [1/2]
static double alglib.jarquebera.jbtbl10 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl11() [1/2]
static double alglib.jarquebera.jbtbl11 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl12() [1/2]
static double alglib.jarquebera.jbtbl12 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl13() [1/2]
static double alglib.jarquebera.jbtbl13 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl14() [1/2]
static double alglib.jarquebera.jbtbl14 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl15() [1/2]
static double alglib.jarquebera.jbtbl15 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl16() [1/2]
static double alglib.jarquebera.jbtbl16 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl17() [1/2]
static double alglib.jarquebera.jbtbl17 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl18() [1/2]
static double alglib.jarquebera.jbtbl18 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl19() [1/2]
static double alglib.jarquebera.jbtbl19 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl20() [1/2]
static double alglib.jarquebera.jbtbl20 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl30() [1/2]
static double alglib.jarquebera.jbtbl30 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl50() [1/2]
static double alglib.jarquebera.jbtbl50 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl65() [1/2]
static double alglib.jarquebera.jbtbl65 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl100() [1/2]
static double alglib.jarquebera.jbtbl100 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl130() [1/2]
static double alglib.jarquebera.jbtbl130 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl200() [1/2]
static double alglib.jarquebera.jbtbl200 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl301() [1/2]
static double alglib.jarquebera.jbtbl301 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl501() [1/2]
static double alglib.jarquebera.jbtbl501 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl701() [1/2]
static double alglib.jarquebera.jbtbl701 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbtbl1401() [1/2]
static double alglib.jarquebera.jbtbl1401 (double s) inline static private
References alglib.jarquebera.jbcheb().
Referenced by alglib.jarquebera.jarqueberaapprox().
jbcheb() [1/2]
static void alglib.jarquebera.jbcheb (double x, double c, ref double tj, ref double tj1, ref double r) inline static private
Referenced by alglib.jarquebera.jbtbl10(), alglib.jarquebera.jbtbl100(), alglib.jarquebera.jbtbl11(), alglib.jarquebera.jbtbl12(), alglib.jarquebera.jbtbl13(), alglib.jarquebera.jbtbl130(), alglib.jarquebera.jbtbl14(), alglib.jarquebera.jbtbl1401(), alglib.jarquebera.jbtbl15(), alglib.jarquebera.jbtbl16(), alglib.jarquebera.jbtbl17(), alglib.jarquebera.jbtbl18(), alglib.jarquebera.jbtbl19(), alglib.jarquebera.jbtbl20(), alglib.jarquebera.jbtbl200(), alglib.jarquebera.jbtbl30(), alglib.jarquebera.jbtbl301(), alglib.jarquebera.jbtbl5(), alglib.jarquebera.jbtbl50(), alglib.jarquebera.jbtbl501(), alglib.jarquebera.jbtbl6(), alglib.jarquebera.jbtbl65(), alglib.jarquebera.jbtbl7(), alglib.jarquebera.jbtbl701(), alglib.jarquebera.jbtbl8(), and alglib.jarquebera.jbtbl9().
jarqueberatest() [2/2]
static void alglib.jarquebera.jarqueberatest (double[] x, int n, ref double p) inline static
References alglib.jarquebera.jarqueberaapprox(), and alglib.jarquebera.jarqueberastatistic().
jarqueberastatistic() [2/2]
static void alglib.jarquebera.jarqueberastatistic (double[] x, int n, ref double s) inline static private
References alglib.ap.assert(), and alglib.math.sqr().
jarqueberaapprox() [2/2]
static double alglib.jarquebera.jarqueberaapprox (int n, double s) inline static private
References alglib.jarquebera.jbtbl10(), alglib.jarquebera.jbtbl100(), alglib.jarquebera.jbtbl11(), alglib.jarquebera.jbtbl12(), alglib.jarquebera.jbtbl13(), alglib.jarquebera.jbtbl130(), alglib.jarquebera.jbtbl14(), alglib.jarquebera.jbtbl1401(), alglib.jarquebera.jbtbl15(), alglib.jarquebera.jbtbl16(), alglib.jarquebera.jbtbl17(), alglib.jarquebera.jbtbl18(), alglib.jarquebera.jbtbl19(), alglib.jarquebera.jbtbl20(), alglib.jarquebera.jbtbl200(), alglib.jarquebera.jbtbl30(), alglib.jarquebera.jbtbl301(), alglib.jarquebera.jbtbl5(), alglib.jarquebera.jbtbl50(), alglib.jarquebera.jbtbl501(), alglib.jarquebera.jbtbl6(), alglib.jarquebera.jbtbl65(), alglib.jarquebera.jbtbl7(), alglib.jarquebera.jbtbl701(), alglib.jarquebera.jbtbl8(), and alglib.jarquebera.jbtbl9().
jbtbl5() [2/2]
static double alglib.jarquebera.jbtbl5 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl6() [2/2]
static double alglib.jarquebera.jbtbl6 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl7() [2/2]
static double alglib.jarquebera.jbtbl7 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl8() [2/2]
static double alglib.jarquebera.jbtbl8 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl9() [2/2]
static double alglib.jarquebera.jbtbl9 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl10() [2/2]
static double alglib.jarquebera.jbtbl10 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl11() [2/2]
static double alglib.jarquebera.jbtbl11 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl12() [2/2]
static double alglib.jarquebera.jbtbl12 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl13() [2/2]
static double alglib.jarquebera.jbtbl13 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl14() [2/2]
static double alglib.jarquebera.jbtbl14 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl15() [2/2]
static double alglib.jarquebera.jbtbl15 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl16() [2/2]
static double alglib.jarquebera.jbtbl16 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl17() [2/2]
static double alglib.jarquebera.jbtbl17 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl18() [2/2]
static double alglib.jarquebera.jbtbl18 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl19() [2/2]
static double alglib.jarquebera.jbtbl19 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl20() [2/2]
static double alglib.jarquebera.jbtbl20 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl30() [2/2]
static double alglib.jarquebera.jbtbl30 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl50() [2/2]
static double alglib.jarquebera.jbtbl50 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl65() [2/2]
static double alglib.jarquebera.jbtbl65 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl100() [2/2]
static double alglib.jarquebera.jbtbl100 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl130() [2/2]
static double alglib.jarquebera.jbtbl130 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl200() [2/2]
static double alglib.jarquebera.jbtbl200 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl301() [2/2]
static double alglib.jarquebera.jbtbl301 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl501() [2/2]
static double alglib.jarquebera.jbtbl501 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl701() [2/2]
static double alglib.jarquebera.jbtbl701 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbtbl1401() [2/2]
static double alglib.jarquebera.jbtbl1401 (double s) inline static private
References alglib.jarquebera.jbcheb().
jbcheb() [2/2]
static void alglib.jarquebera.jbcheb (double x, double c, ref double tj, ref double tj1, ref double r) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/statistics.cs