Doc: IGLib EXTENDED: CShell.Modules.Repl.ViewModels.OutputViewModel Class Reference
CShell.Modules.Repl.ViewModels.OutputViewModel Class Reference
Public Member Functions
OutputViewModel (IEventAggregator eventAggregator)
void Clear ()
void Write (string format, params object[] arg)
void WriteLine (string format, params object[] arg)
void Handle (WorkspaceOpenedEventArgs message)
void Handle (WorkspaceClosingEventArgs message)
Protected Member Functions
override void OnViewLoaded (object view)
Protected Member Functions inherited from CShell.Framework.Tool
Tool ()
Properties
override PaneLocation PreferredLocation [get]
override Uri Uri [get]
override Uri IconSource [get]
string Text [get, set]
int BufferLength [get, set]
string Font [get, set]
double FontSize [get, set]
Color TextColor [get, set]
Brush TextBrush [get]
Color BackgroundColor [get, set]
Brush BackgroundBrush [get]
Properties inherited from CShell.Framework.Tool
ICommand?? CloseCommand [get]
abstract PaneLocation PreferredLocation [get]
abstract Uri Uri [get]
virtual Uri IconSource [get]
bool IsVisible [get, set]
Properties inherited from CShell.Framework.ITool
Uri Uri [get]
ICommand CloseCommand [get]
PaneLocation PreferredLocation [get]
bool IsVisible [get, set]
Properties inherited from CShell.Framework.Services.IOutput
int BufferLength [get, set]
string Font [get, set]
double FontSize [get, set]
Color TextColor [get, set]
Color BackgroundColor [get, set]
Private Member Functions
void ScriptingEngineOnConsoleOutput (object sender, ConsoleEventArgs consoleEventArgs)
Private Attributes
IOutputView _view
string _text = string.Empty
int bufferLength
string font
double fontSize
Color textColor
Color backgroundColor
Constructor & Destructor Documentation
OutputViewModel()
CShell.Modules.Repl.ViewModels.OutputViewModel.OutputViewModel (IEventAggregator eventAggregator) inline
References CShell.Modules.Repl.ViewModels.OutputViewModel.BackgroundColor, CShell.Modules.Repl.ViewModels.OutputViewModel.BufferLength, CShell.ScriptingEngine.ConsoleOutput, CShell.Modules.Repl.ViewModels.OutputViewModel.Font, CShell.Modules.Repl.ViewModels.OutputViewModel.FontSize, CShell.Workspace.ScriptingEngine, CShell.Modules.Repl.ViewModels.OutputViewModel.ScriptingEngineOnConsoleOutput(), CShell.Modules.Repl.ViewModels.OutputViewModel.TextColor, and CShell.Shell.Workspace.
Member Function Documentation
Clear()
void CShell.Modules.Repl.ViewModels.OutputViewModel.Clear () inline
Implements CShell.Framework.Services.IOutput.
References CShell.Modules.Repl.ViewModels.OutputViewModel.Text.
Write()
void CShell.Modules.Repl.ViewModels.OutputViewModel.Write (string format, params object[] arg) inline
Implements CShell.Framework.Services.IOutput.
References CShell.Modules.Repl.ViewModels.OutputViewModel.Text.
Referenced by CShell.Modules.Repl.ViewModels.OutputViewModel.ScriptingEngineOnConsoleOutput().
WriteLine()
void CShell.Modules.Repl.ViewModels.OutputViewModel.WriteLine (string format, params object[] arg) inline
Implements CShell.Framework.Services.IOutput.
References CShell.Modules.Repl.ViewModels.OutputViewModel.Text.
OnViewLoaded()
override void CShell.Modules.Repl.ViewModels.OutputViewModel.OnViewLoaded (object view) inline protected
References CShell.Modules.Repl.ViewModels.OutputViewModel._view, and CShell.Modules.Repl.Views.IOutputView.ScrollToEnd().
ScriptingEngineOnConsoleOutput()
void CShell.Modules.Repl.ViewModels.OutputViewModel.ScriptingEngineOnConsoleOutput (object sender, ConsoleEventArgs consoleEventArgs) inline private
References CShell.Code.ConsoleEventArgs.Text, and CShell.Modules.Repl.ViewModels.OutputViewModel.Write().
Referenced by CShell.Modules.Repl.ViewModels.OutputViewModel.Handle(), and CShell.Modules.Repl.ViewModels.OutputViewModel.OutputViewModel().
Handle() [1/2]
void CShell.Modules.Repl.ViewModels.OutputViewModel.Handle (WorkspaceOpenedEventArgs message) inline
References CShell.ScriptingEngine.ConsoleOutput, CShell.Workspace.ScriptingEngine, CShell.Modules.Repl.ViewModels.OutputViewModel.ScriptingEngineOnConsoleOutput(), and CShell.WorkspaceOpenedEventArgs.Workspace.
Handle() [2/2]
void CShell.Modules.Repl.ViewModels.OutputViewModel.Handle (WorkspaceClosingEventArgs message) inline
References CShell.ScriptingEngine.ConsoleOutput, CShell.Workspace.ScriptingEngine, CShell.Modules.Repl.ViewModels.OutputViewModel.ScriptingEngineOnConsoleOutput(), and CShell.WorkspaceClosingEventArgs.Workspace.
Member Data Documentation
_view
IOutputView CShell.Modules.Repl.ViewModels.OutputViewModel._view private
Referenced by CShell.Modules.Repl.ViewModels.OutputViewModel.OnViewLoaded().
_text
string CShell.Modules.Repl.ViewModels.OutputViewModel._text = string.Empty private
bufferLength
int CShell.Modules.Repl.ViewModels.OutputViewModel.bufferLength private
font
string CShell.Modules.Repl.ViewModels.OutputViewModel.font private
fontSize
double CShell.Modules.Repl.ViewModels.OutputViewModel.fontSize private
textColor
Color CShell.Modules.Repl.ViewModels.OutputViewModel.textColor private
backgroundColor
Color CShell.Modules.Repl.ViewModels.OutputViewModel.backgroundColor private
Property Documentation
PreferredLocation
override PaneLocation CShell.Modules.Repl.ViewModels.OutputViewModel.PreferredLocation get
Uri
override Uri CShell.Modules.Repl.ViewModels.OutputViewModel.Uri get
IconSource
override Uri CShell.Modules.Repl.ViewModels.OutputViewModel.IconSource get
Text
string CShell.Modules.Repl.ViewModels.OutputViewModel.Text get set
Referenced by CShell.Modules.Repl.ViewModels.OutputViewModel.Clear(), CShell.Modules.Repl.ViewModels.OutputViewModel.Write(), and CShell.Modules.Repl.ViewModels.OutputViewModel.WriteLine().
BufferLength
int CShell.Modules.Repl.ViewModels.OutputViewModel.BufferLength get set
Referenced by CShell.Modules.Repl.ViewModels.OutputViewModel.OutputViewModel().
Font
string CShell.Modules.Repl.ViewModels.OutputViewModel.Font get set
Referenced by CShell.Modules.Repl.ViewModels.OutputViewModel.OutputViewModel().
FontSize
double CShell.Modules.Repl.ViewModels.OutputViewModel.FontSize get set
Referenced by CShell.Modules.Repl.ViewModels.OutputViewModel.OutputViewModel().
TextColor
Color CShell.Modules.Repl.ViewModels.OutputViewModel.TextColor get set
Referenced by CShell.Modules.Repl.ViewModels.OutputViewModel.OutputViewModel().
TextBrush
Brush CShell.Modules.Repl.ViewModels.OutputViewModel.TextBrush get
BackgroundColor
Color CShell.Modules.Repl.ViewModels.OutputViewModel.BackgroundColor get set
Referenced by CShell.Modules.Repl.ViewModels.OutputViewModel.OutputViewModel().
BackgroundBrush
Brush CShell.Modules.Repl.ViewModels.OutputViewModel.BackgroundBrush get
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Repl/ViewModels/OutputViewModel.cs