Doc: IGLib EXTENDED: IG.Crypt.SymFileEncrypt Class Reference
IG.Crypt.SymFileEncrypt Class Reference
Public Member Functions
SymFileEncrypt (SymmetricAlgorithm algorithm, string fileName)
void SaveSensitiveData (string sensitiveData)
string ReadSensitiveData ()
Static Public Member Functions
static void Test ()
Properties
byte[] Key [get, set]
byte[] IV [get, set]
Private Member Functions
void GenerateSecretKey ()
void GenerateSecretInitVector ()
Private Attributes
byte[] savedKey = null
byte[] savedIV = null
SymmetricAlgorithm symmetricAlgorithm
string path
Constructor & Destructor Documentation
SymFileEncrypt()
IG.Crypt.SymFileEncrypt.SymFileEncrypt (SymmetricAlgorithm algorithm, string fileName) inline
References IG.Crypt.SymFileEncrypt.path, and IG.Crypt.SymFileEncrypt.symmetricAlgorithm.
Referenced by IG.Crypt.SymFileEncrypt.Test().
Member Function Documentation
SaveSensitiveData()
void IG.Crypt.SymFileEncrypt.SaveSensitiveData (string sensitiveData) inline
References IG.Crypt.SymFileEncrypt.GenerateSecretInitVector(), IG.Crypt.SymFileEncrypt.GenerateSecretKey(), IG.Crypt.SymFileEncrypt.path, IG.Crypt.SymFileEncrypt.savedIV, IG.Crypt.SymFileEncrypt.savedKey, and IG.Crypt.SymFileEncrypt.symmetricAlgorithm.
Referenced by IG.Crypt.SymFileEncrypt.Test().
ReadSensitiveData()
string IG.Crypt.SymFileEncrypt.ReadSensitiveData () inline
References IG.Crypt.SymFileEncrypt.path, IG.Crypt.SymFileEncrypt.savedIV, IG.Crypt.SymFileEncrypt.savedKey, and IG.Crypt.SymFileEncrypt.symmetricAlgorithm.
Referenced by IG.Crypt.SymFileEncrypt.Test().
GenerateSecretKey()
void IG.Crypt.SymFileEncrypt.GenerateSecretKey () inline private
References IG.Crypt.SymFileEncrypt.savedKey, and IG.Crypt.SymFileEncrypt.symmetricAlgorithm.
Referenced by IG.Crypt.SymFileEncrypt.SaveSensitiveData().
GenerateSecretInitVector()
void IG.Crypt.SymFileEncrypt.GenerateSecretInitVector () inline private
References IG.Crypt.SymFileEncrypt.savedIV, and IG.Crypt.SymFileEncrypt.symmetricAlgorithm.
Referenced by IG.Crypt.SymFileEncrypt.SaveSensitiveData().
Test()
static void IG.Crypt.SymFileEncrypt.Test () inline static
References IG.Crypt.SymFileEncrypt.IV, IG.Crypt.SymFileEncrypt.Key, IG.Crypt.SymFileEncrypt.ReadSensitiveData(), IG.Crypt.SymFileEncrypt.SaveSensitiveData(), and IG.Crypt.SymFileEncrypt.SymFileEncrypt().
Member Data Documentation
savedKey
byte [] IG.Crypt.SymFileEncrypt.savedKey = null private
Referenced by IG.Crypt.SymFileEncrypt.GenerateSecretKey(), IG.Crypt.SymFileEncrypt.ReadSensitiveData(), and IG.Crypt.SymFileEncrypt.SaveSensitiveData().
savedIV
byte [] IG.Crypt.SymFileEncrypt.savedIV = null private
Referenced by IG.Crypt.SymFileEncrypt.GenerateSecretInitVector(), IG.Crypt.SymFileEncrypt.ReadSensitiveData(), and IG.Crypt.SymFileEncrypt.SaveSensitiveData().
symmetricAlgorithm
SymmetricAlgorithm IG.Crypt.SymFileEncrypt.symmetricAlgorithm private
Referenced by IG.Crypt.SymFileEncrypt.GenerateSecretInitVector(), IG.Crypt.SymFileEncrypt.GenerateSecretKey(), IG.Crypt.SymFileEncrypt.ReadSensitiveData(), IG.Crypt.SymFileEncrypt.SaveSensitiveData(), and IG.Crypt.SymFileEncrypt.SymFileEncrypt().
path
string IG.Crypt.SymFileEncrypt.path private
Referenced by IG.Crypt.SymFileEncrypt.ReadSensitiveData(), IG.Crypt.SymFileEncrypt.SaveSensitiveData(), and IG.Crypt.SymFileEncrypt.SymFileEncrypt().
Property Documentation
Key
byte [] IG.Crypt.SymFileEncrypt.Key get set
Referenced by IG.Crypt.SymFileEncrypt.Test().
IV
byte [] IG.Crypt.SymFileEncrypt.IV get set
Referenced by IG.Crypt.SymFileEncrypt.Test().
The documentation for this class was generated from the following file:
igtest/iglib_sandbox/encryption/EncryptionLib.cs