Doc: IGLib EXTENDED: NUnit.Engine.Extensibility.IFrameworkDriver Interface Reference
NUnit.Engine.Extensibility.IFrameworkDriver Interface Reference
The IFrameworkDriver interface is implemented by a class that is able to use an external framework to explore or run tests under the engine.
Public Member Functions
string Load (string testAssemblyPath, IDictionary< string, object > settings)
Loads the tests in an assembly.
int CountTestCases (string filter)
Count the test cases that would be executed.
string Run (ITestEventListener listener, string filter)
Executes the tests in an assembly.
string Explore (string filter)
Returns information about the tests in an assembly.
void StopRun (bool force)
Cancel the ongoing test run. If no test is running, the call is ignored.
Properties
string ID [get, set]
Gets and sets the unique identifier for this driver, used to ensure that test ids are unique across drivers.
Detailed Description
The IFrameworkDriver interface is implemented by a class that is able to use an external framework to explore or run tests under the engine.
Member Function Documentation
Load()
string NUnit.Engine.Extensibility.IFrameworkDriver.Load (string testAssemblyPath, IDictionary< string, object > settings)
Loads the tests in an assembly.
Returns
An Xml string representing the loaded test
Implemented in NUnit.Engine.Drivers.NUnit2FrameworkDriver, NUnit.Engine.Drivers.NUnit3FrameworkDriver, and NUnit.Engine.Drivers.NotRunnableFrameworkDriver.
Referenced by NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Load_ReturnsNonRunnableSuite(), and NUnit.Engine.Runners.DirectTestRunner.LoadPackage().
CountTestCases()
int NUnit.Engine.Extensibility.IFrameworkDriver.CountTestCases (string filter)
Count the test cases that would be executed.
Parameters
filter An XML string representing the TestFilter to use in counting the tests
Returns
The number of test cases counted
Implemented in NUnit.Engine.Drivers.NUnit2FrameworkDriver, NUnit.Engine.Drivers.NUnit3FrameworkDriver, and NUnit.Engine.Drivers.NotRunnableFrameworkDriver.
Referenced by NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.CountTestCases_ReturnsZero(), and NUnit.Engine.Runners.DirectTestRunner.CountTests().
Run()
string NUnit.Engine.Extensibility.IFrameworkDriver.Run (ITestEventListener listener, string filter)
Executes the tests in an assembly.
Parameters
listener An ITestEventHandler that receives progress notices
filter A XML string representing the filter that controls which tests are executed
Returns
An Xml string representing the result
Implemented in NUnit.Engine.Drivers.NUnit3FrameworkDriver, NUnit.Engine.Drivers.NUnit2FrameworkDriver, and NUnit.Engine.Drivers.NotRunnableFrameworkDriver.
Referenced by NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Run_ReturnsNonRunnableSuite(), and NUnit.Engine.Runners.DirectTestRunner.RunTests().
Explore()
string NUnit.Engine.Extensibility.IFrameworkDriver.Explore (string filter)
Returns information about the tests in an assembly.
Parameters
filter An XML string representing the filter that controls which tests are included
Returns
An Xml string representing the tests
Implemented in NUnit.Engine.Drivers.NUnit3FrameworkDriver, NUnit.Engine.Drivers.NUnit2FrameworkDriver, and NUnit.Engine.Drivers.NotRunnableFrameworkDriver.
Referenced by NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.Explore_ReturnsNonRunnableSuite(), and NUnit.Engine.Runners.DirectTestRunner.ExploreTests().
StopRun()
void NUnit.Engine.Extensibility.IFrameworkDriver.StopRun (bool force)
Cancel the ongoing test run. If no test is running, the call is ignored.
Parameters
force If true, cancel any ongoing test threads, otherwise wait for them to complete.
Implemented in NUnit.Engine.Drivers.NUnit3FrameworkDriver, NUnit.Engine.Drivers.NUnit2FrameworkDriver, and NUnit.Engine.Drivers.NotRunnableFrameworkDriver.
Property Documentation
ID
string NUnit.Engine.Extensibility.IFrameworkDriver.ID get set
Gets and sets the unique identifier for this driver, used to ensure that test ids are unique across drivers.
Referenced by NUnit.Engine.Drivers.Tests.NotRunnableFrameworkDriverTests.CreateDriver(), and NUnit.Engine.Runners.DirectTestRunner.LoadPackage().
The documentation for this interface was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.api/Extensibility/IFrameworkDriver.cs