Doc: IGLib EXTENDED: Meta.Numerics.Matrices.SingularValueDecomposition Class Reference
Meta.Numerics.Matrices.SingularValueDecomposition Class Reference
Stores the singular value decomposition of a matrix.
Public Member Functions
SquareMatrix LeftTransformMatrix ()
Returns the left transform matrix.
SquareMatrix RightTransformMatrix ()
Returns the right transform matrix.
double SingularValue (int n)
Gets the specificed singular value.
ColumnVector LeftSingularVector (int n)
Returns the specified left singular vector.
ColumnVector RightSingularVector (int n)
Returns the specified right singular vector.
Properties
int RowCount [get]
Gets the number of rows in the original matrix.
int ColumnCount [get]
Gets the number of columns in the original matrix.
int Dimension [get]
Gets the number of singular values.
double ConditionNumber [get]
Returns the condition number of the matrix.
double Tolerance [get, set]
Gets or sets the tolerance with which singular values are distinguished from zero.
int Rank [get]
Computes the rank of the original matrix.
Private Attributes
readonly int rows
readonly int cols
readonly double[] utStore
readonly double[] wStore
readonly double[] vStore
double tolerance = Global.Accuracy
Detailed Description
Stores the singular value decomposition of a matrix.
The singular value decomposition of a matrix represents it as a product of a left orthogonal matrix, a diagonal matrix, and a right orthogonal matrix:
The elements of the diagonal matrix are called the singular values of the original matrix.
If the orginal matrix is viewed as a linear transform operator, the rows of the right orthogonal matrix matrix form an orthonormal basis for the domain of the operator, while the columns of the left orthogonal matrix form an orthonormal basis for the range of the operator. These rows and columns are called, respectively, the right and left singular vectors of the matrix.
The right singular vectors corresponding to zero singular values span the nullspace of the matrix, that is the set of all x for which Ax = 0.
The SVD can be used to approximate the action of a high-dimensional matrix by a lower-rank one.
Use the RectangularMatrix.SingularValueDecomposition of the RectangularMatrix class to obtain the SVD of an rectangular matrix, or the corresponding SquareMatrix.SingularValueDecomposition method of the SquareMatrix class to obtain the SVD of a square matrix.
Member Function Documentation
LeftTransformMatrix()
SquareMatrix Meta.Numerics.Matrices.SingularValueDecomposition.LeftTransformMatrix () inline
Returns the left transform matrix.
Returns
The matrix U, such that A = U S VT.
References Meta.Numerics.Matrices.SingularValueDecomposition.rows, Meta.Numerics.Matrices.SquareMatrix.Transpose(), and Meta.Numerics.Matrices.SingularValueDecomposition.utStore.
Referenced by Test.SquareMatrixTest.HilbertMatrixSVD(), Test.RectangularMatrixTest.PC(), Test.RectangularMatrixTest.RandomRectangularSVD(), and Test.RectangularMatrixTest.SmallSVD().
RightTransformMatrix()
SquareMatrix Meta.Numerics.Matrices.SingularValueDecomposition.RightTransformMatrix () inline
Returns the right transform matrix.
Returns
The matrix V, such that A = U S VT.
The returned matrix is read-only. If you need to make changes to it, you can call SquareMatrix.Copy to obtain a writable copy.
References Meta.Numerics.Matrices.SingularValueDecomposition.cols, and Meta.Numerics.Matrices.SingularValueDecomposition.vStore.
Referenced by Test.SquareMatrixTest.HilbertMatrixSVD(), Test.RectangularMatrixTest.PC(), Test.RectangularMatrixTest.RandomRectangularSVD(), and Test.RectangularMatrixTest.SmallSVD().
SingularValue()
double Meta.Numerics.Matrices.SingularValueDecomposition.SingularValue (int n) inline
Gets the specificed singular value.
Parameters
n The (zero-based) index.
Returns
The n th singular value.
Exceptions
ArgumentOutOfRangeException n lies outside the range [0, Dimension - 1].
References Meta.Numerics.Matrices.SingularValueDecomposition.wStore.
Referenced by Test.SquareMatrixTest.HilbertMatrixSVD(), Test.RectangularMatrixTest.PC(), Test.RectangularMatrixTest.RandomRectangularSVD(), Test.RectangularMatrixTest.SmallSVD(), and Test.SquareMatrixTest.SvdOfRankOneMatrix().
LeftSingularVector()
ColumnVector Meta.Numerics.Matrices.SingularValueDecomposition.LeftSingularVector (int n) inline
Returns the specified left singular vector.
Parameters
n The (zero-based) index.
Returns
The n th left singular vector.
Exceptions
ArgumentOutOfRangeException n lies outside the range [0, Dimension - 1].
The returned vector is read-only. If you need to make changes to it, you can call ColumnVector.Copy to obtain a writable copy.
References Meta.Numerics.Matrices.SingularValueDecomposition.rows, Meta.Numerics.Matrices.SingularValueDecomposition.utStore, and Meta.Numerics.Matrices.SingularValueDecomposition.wStore.
Referenced by Test.RectangularMatrixTest.RandomRectangularSVD().
RightSingularVector()
ColumnVector Meta.Numerics.Matrices.SingularValueDecomposition.RightSingularVector (int n) inline
Returns the specified right singular vector.
Parameters
n The (zero-based) index.
Returns
The n th right singular vector.
Exceptions
ArgumentOutOfRangeException n lies outside the range [0, Dimension - 1].
The returned vector is read-only. If you need to make changes to it, you can call ColumnVector.Copy to obtain a writable copy.
References Meta.Numerics.Matrices.SingularValueDecomposition.cols, Meta.Numerics.Matrices.SingularValueDecomposition.vStore, and Meta.Numerics.Matrices.SingularValueDecomposition.wStore.
Referenced by Test.RectangularMatrixTest.PC(), and Test.RectangularMatrixTest.RandomRectangularSVD().
Member Data Documentation
rows
readonly int Meta.Numerics.Matrices.SingularValueDecomposition.rows private
Referenced by Meta.Numerics.Matrices.SingularValueDecomposition.LeftSingularVector(), and Meta.Numerics.Matrices.SingularValueDecomposition.LeftTransformMatrix().
cols
readonly int Meta.Numerics.Matrices.SingularValueDecomposition.cols private
Referenced by Meta.Numerics.Matrices.SingularValueDecomposition.RightSingularVector(), and Meta.Numerics.Matrices.SingularValueDecomposition.RightTransformMatrix().
utStore
readonly double [] Meta.Numerics.Matrices.SingularValueDecomposition.utStore private
Referenced by Meta.Numerics.Matrices.SingularValueDecomposition.LeftSingularVector(), and Meta.Numerics.Matrices.SingularValueDecomposition.LeftTransformMatrix().
wStore
readonly double [] Meta.Numerics.Matrices.SingularValueDecomposition.wStore private
Referenced by Meta.Numerics.Matrices.SingularValueDecomposition.LeftSingularVector(), Meta.Numerics.Matrices.SingularValueDecomposition.RightSingularVector(), and Meta.Numerics.Matrices.SingularValueDecomposition.SingularValue().
vStore
readonly double [] Meta.Numerics.Matrices.SingularValueDecomposition.vStore private
Referenced by Meta.Numerics.Matrices.SingularValueDecomposition.RightSingularVector(), and Meta.Numerics.Matrices.SingularValueDecomposition.RightTransformMatrix().
tolerance
double Meta.Numerics.Matrices.SingularValueDecomposition.tolerance = Global.Accuracy private
Property Documentation
RowCount
int Meta.Numerics.Matrices.SingularValueDecomposition.RowCount get
Gets the number of rows in the original matrix.
Referenced by Test.RectangularMatrixTest.RandomRectangularSVD().
ColumnCount
int Meta.Numerics.Matrices.SingularValueDecomposition.ColumnCount get
Gets the number of columns in the original matrix.
Referenced by Test.RectangularMatrixTest.RandomRectangularSVD().
Dimension
int Meta.Numerics.Matrices.SingularValueDecomposition.Dimension get
Gets the number of singular values.
For a square matrix, the number of singular values is equal to the dimension of the matrix. For a rectangular matrix with more rows than columns, the number of singular values is equal to the number of columns.
Referenced by Test.SquareMatrixTest.HilbertMatrixSVD(), Test.RectangularMatrixTest.PC(), Test.RectangularMatrixTest.RandomRectangularSVD(), Test.RectangularMatrixTest.SmallSVD(), and Test.SquareMatrixTest.SvdOfRankOneMatrix().
ConditionNumber
double Meta.Numerics.Matrices.SingularValueDecomposition.ConditionNumber get
Returns the condition number of the matrix.
The conidition number is the ratio of the largest singular value to smallest singular value. It is therefore always larger than one.
Tolerance
double Meta.Numerics.Matrices.SingularValueDecomposition.Tolerance get set
Gets or sets the tolerance with which singular values are distinguished from zero.
Some operations offered by singular value decompositions, including rank determination and computation of the pseudo-inverse matrix, depend on determining whether or not a singular value is zero. Since floating point numbers are only approximate representations of real numbers, singular values will usually not be exactly zero even for matrices for which they should be, but will instead be very tiny numbers, on the order of floating point precision (about 10-16) as a fraction of the largest singular value. The value of this property is used to determine how small a singular value must be, as a fraction of the largest singular value, to be considered zero for these purposes. Usually you will want to maintain its default value.
Exceptions
ArgumentOutOfRangeException The assigned value is outside the range [0,1).
Rank
int Meta.Numerics.Matrices.SingularValueDecomposition.Rank get
Computes the rank of the original matrix.
The rank of a matrix is the dimension of the space of input vectors which produce non-zero output vectors upon multiplication by the original matrix.
Since this operation depends on identifying zero singular values, the result will depend on the value of the Tolerance property.
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Matrices/SingularValueDecomposition.cs