Doc: IGLib EXTENDED: NUnit.Framework.Assertions.NotSameFixture Class Reference
NUnit.Framework.Assertions.NotSameFixture Class Reference
Public Member Functions
void NotSame ()
void NotSameFails ()
Private Attributes
readonly string s1 = "S1"
readonly string s2 = "S2"
Member Function Documentation
NotSame()
void NUnit.Framework.Assertions.NotSameFixture.NotSame () inline
References NUnit.Framework.Assert.AreNotSame(), NUnit.Framework.Assertions.NotSameFixture.s1, and NUnit.Framework.Assertions.NotSameFixture.s2.
NotSameFails()
void NUnit.Framework.Assertions.NotSameFixture.NotSameFails () inline
References NUnit.Framework.Assert.AreNotSame(), NUnit.Framework.Is.EqualTo(), NUnit.Env.NewLine, NUnit.Framework.Assertions.NotSameFixture.s1, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
Member Data Documentation
s1
readonly string NUnit.Framework.Assertions.NotSameFixture.s1 = "S1" private
Referenced by NUnit.Framework.Assertions.NotSameFixture.NotSame(), and NUnit.Framework.Assertions.NotSameFixture.NotSameFails().
s2
readonly string NUnit.Framework.Assertions.NotSameFixture.s2 = "S2" private
Referenced by NUnit.Framework.Assertions.NotSameFixture.NotSame().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/NotSameFixture.cs