Doc: IGLib EXTENDED: IG.Lib.opt.opttest.ParticlePotentialProblem Class Reference
IG.Lib.opt.opttest.ParticlePotentialProblem Class Reference
Base class for the charged particle potential problem.
Classes
class ConstraintFunctionParticleConstraint
Class that returns the objective function (total potential energy) of the specified particle potential problem.
class ObjectiveFunctionPotentialEnergy
Class that returns the objective function (total potential energy) of the specified particle potential problem.
Public Member Functions
double GetPotentialFactorPhysical ()
void SetCharges (double charge)
Sets all particle charges to the specified value.
void SetStaticCharges (double charge)
Sets all static particle charges to the specified value.
int ParameterIndex (int particleIndex, int coordinateIndex)
Returns parameter index that corresponds to the specified particle index and to the specified particle coordinate.
int ParticleIndex (int parameterIndex)
Returns index of the particle to which the specified element of the global parameter vector belongs.
int CoordinateIndex (int parameterIndex)
Returns coordinate index of the corresponding particle that is equivalent to the specified element of the global parameter vector.
double ParticleCoordinate (int particleIndex, int coordinateIndex, IVector parameters)
Extracts and returns the specified coordinate of the specified particle from the specified parameter vector.
double ParticleDistance (int firstIndex, int secondIndex, IVector parameters)
Returns the Euclidean distance between the two particles with specified indices.
virtual double StaticParticleDistance (int staticParticleIndex, int particleIndex, IVector parameters, IVector[] staticCoordinates)
Calculates and returns the distance between the specified static particle and the specified free particle of the particle arrangement.
virtual double StaticPairwisePotentialEnergy (int staticParticleIndex, int particleIndex, double potentialFactor, double[] charges, IRealFunction potentialFunction, IVector parameters, double[] staticCharges, IVector[] staticCoordinates)
Calculates and returns pairwise electrical potential energy of the specified static and the specified free particle, providing the necessary coefficiets through parameters.
virtual double StaticPairwisePotentialEnergy (int staticParticleIndex, int particleIndex, IVector parameters)
Calculates and returns electrical potential energy of the specified static and free particle.
virtual double PairwisePotentialEnergy (int referenceIndex, int particleIndex, double potentialFactor, double[] charges, IRealFunction potentialFunction, IVector parameters)
Calculates and returns pairwise electrical potential energy of two particles, providing the necessary coefficiets through parameters.
virtual double PairwisePotentialEnergy (int referenceIndex, int particleIndex, IVector parameters)
Calculates and returns electrical potential energy of two particles.
virtual double PotentialEnergy (IVector parameters)
Calculates and returns the total potential energy of all particles in the formation.
void StaticParticleSingleForce (int staticParticleIndex, int particleIndex, double potentialFactor, double[] charges, IRealFunction potentialFunction, IVector parameters, double[] staticCharges, IVector[] staticCoordinates, ref IVector particleForce)
Calculates the electrostatic force acting on the specified free particle by a single specified statitc particle.
void StaticParticleSingleForce (int staticParticleIndex, int particleIndex, IVector parameters, ref IVector particleForce)
Calculates the electrostatic force acting on the specified free particle by a single specified static particle.
virtual void StaticParticleSingleForce (int particleIndex, IVector parameters, ref IVector particleForce)
Calculates the electrostatic force acting on the specified free particle by all static particles in the arrangement.
void ParticleSingleForce (int referenceIndex, int particleIndex, double potentialFactor, double[] charges, IRealFunction potentialFunction, IVector parameters, ref IVector particleForce)
Calculates the electrostatic force acting on the specified particle by a single specified another particle.
void ParticleSingleForce (int referenceIndex, int particleIndex, IVector parameters, ref IVector particleForce)
Calculates the electrostatic force acting on the specified particle by a single specified another free particle.
virtual void ParticleSingleForce (int particleIndex, IVector parameters, ref IVector particleForce)
Calculates the electrostatic force acting on the specified particle by all other free particles in the arrangement.
virtual void PotentialEnergyGradient (IVector parameters, ref IVector gradient)
Calculates gradient of total potential, which is effectively composed of forces acting on the individual particles by all other particles in the arrangement (and that equals to gradients of potential energy of individual particle in the field of other particles).
double ParticleConstraintValue (int particleIndex, IVector parameters)
Returns value of the constraint function for the specified particle in the arrangement.
void ParticleConstraintGradient (int particleIndex, IVector parameters, ref IVector partConstraintGrad)
Calculates and stores gradient of the constraint function related to the specified particle, in terms of particle coordinates.
double ConstraintFunction (int whichConstraint, IVector parameters)
Returns value of the specified constraint function related to specified particle in the arrangement.
void ConstraintGradient (int whichConstraint, IVector parameters, ref IVector constraintGradient)
Calculates and stores gradient of the specified constraint function that is related to the specified particle, in terms of global parameters (vector assembly of all particle coordinates).
Protected Attributes
int _numParticles = 8
int _spaceDimension = 2
double _potentialFactor = 1.0
IRealFunction _potentialFunction = Func.GetReciprocal()
IVector _auxParticleVector = null
Properties
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
int NumParticles [get, protected set]
Number of charged particles in the arrangement.
int SpaceDimension [get, protected set]
Dimension of space in which particles are positioned.
int ProblemDimension [get]
Dimension of the problem, product of the space dimension and the number of free particles.
double PotentialFactor [get, protected set]
double[] Charges [get, set]
Gets or sets the array of particle charges. Length of the array must be the same as the number of particles. If not set, getter will return the array in which all charges are equal to 1.
IRealFunction PotentialFunction [get, set]
The potential function.
int NumStaticParticles [get, private set]
Gets the number of static particles.
IVector[] StaticParticleCoordinates [get, set]
Array of coordinate vectors of staticle charges.
double[] StaticParticleCharges [get, set]
Gets or sets the array of static particle's charges. If not set, getter will return the array in which all charges are equal to 1.
ScalarFunctionBase ObjectiveFunction [get]
Returns the scalar function that represents the objective function of the current minimal particle potential energy problem.
ScalarFunctionBase[] ConstraintFunctions [get, protected set]
Returns an array of scalar functions that represent the constraint functions of the current minimal particle potential energy problem.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Member Functions
ParticlePotentialProblem ()
Prevent argument-less constructor.
Private Attributes
readonly object _mainLock = new object()
double[] _charges
int _numStaticParticles
IVector[] _staticParticleCoordinates
double[] _staticParticleCharges
ScalarFunctionBase _objectiveFunction
ScalarFunctionBase[] _constraintFunctions
Detailed Description
Base class for the charged particle potential problem.
Description of the problem:
This class represents the problem of minimal potential arrangement of a number of charged particles that are confined to the specified region of space (in the current case, this happens to be the hyperball with radius 1). The class represent methods for calculation of the total potential of particles and its gradienn with respect to parameters, as well as individual particle potentials and their gradients with respect to the particle coordinates.
Charges can be assigned to particles (by default, charges are eual to 1), as well as a factor in potential (that replaces 1/(4 Pi epsilon_0) in physical euation for charged particles potential; by default, this factor is also 1). By default, the potential funtion is equal to 1/r, but a customized potential function can also be provided.
<pare></pare>
Things to be done in the future:
Possibility of adding charged particles with fixed positions. These particles can contribute to the potential and thus influence the equilibrium positions of free particles, but can not change positions. Adding this possibility can be useful for calculating maximal distance arrangements of sampling points with a given number of already sampled points whose positions are fixed.
$A Igor xx Jul09 Apr10;
Constructor & Destructor Documentation
ParticlePotentialProblem()
IG.Lib.opt.opttest.ParticlePotentialProblem.ParticlePotentialProblem () inline private
Prevent argument-less constructor.
Member Function Documentation
GetPotentialFactorPhysical()
double IG.Lib.opt.opttest.ParticlePotentialProblem.GetPotentialFactorPhysical () inline
References IG.Num.ConstPhysical.ElectricConstant, and IG.Num.PhysicalConstant.Value.
SetCharges()
void IG.Lib.opt.opttest.ParticlePotentialProblem.SetCharges (double charge) inline
Sets all particle charges to the specified value.
Parameters
charge Charge assigned to all particles.
References IG.Lib.opt.opttest.ParticlePotentialProblem._numParticles, IG.Lib.opt.opttest.ParticlePotentialProblem.Charges, and IG.Lib.opt.opttest.ParticlePotentialProblem.Lock.
SetStaticCharges()
void IG.Lib.opt.opttest.ParticlePotentialProblem.SetStaticCharges (double charge) inline
Sets all static particle charges to the specified value.
Parameters
charge Charge assigned to all static particles.
References IG.Lib.opt.opttest.ParticlePotentialProblem.Lock, and IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleCharges.
ParameterIndex()
int IG.Lib.opt.opttest.ParticlePotentialProblem.ParameterIndex (int particleIndex, int coordinateIndex) inline
Returns parameter index that corresponds to the specified particle index and to the specified particle coordinate.
Parameters
particleIndex Particle index.
coordinateIndex Index of particle coordinate.
Coordinates of all particles are collected in a single parameter vector. Individual particle coordinates are elements of this vector, and there exist an unique transformation between the parameter index and the pair (particle index, particle coordinate).
References IG.Lib.opt.opttest.ParticlePotentialProblem._numParticles.
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.ConstraintGradient(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleCoordinate(), and IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergyGradient().
ParticleIndex()
int IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleIndex (int parameterIndex) inline
Returns index of the particle to which the specified element of the global parameter vector belongs.
Parameters
parameterIndex Index of the element of the global parameter vector.
Coordinates of all particles are collected in a single parameter vector. Individual particle coordinates are elements of this vector, and there exist an unique transformation between the parameter index and the pair (particle index, particle coordinate).
References IG.Lib.opt.opttest.ParticlePotentialProblem._numParticles.
CoordinateIndex()
int IG.Lib.opt.opttest.ParticlePotentialProblem.CoordinateIndex (int parameterIndex) inline
Returns coordinate index of the corresponding particle that is equivalent to the specified element of the global parameter vector.
Parameters
parameterIndex Index of the element of the global parameter vector.
Coordinates of all particles are collected in a single parameter vector. Individual particle coordinates are elements of this vector, and there exist an unique transformation between the parameter index and the pair (particle index, particle coordinate).
References IG.Lib.opt.opttest.ParticlePotentialProblem._numParticles.
ParticleCoordinate()
double IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleCoordinate (int particleIndex, int coordinateIndex, IVector parameters) inline
Extracts and returns the specified coordinate of the specified particle from the specified parameter vector.
Parameters
particleIndex Particle index.
coordinateIndex Index of particle coordinate.
parameters Vector of parameters where coordinates fo all particles are collected.
References IG.Lib.opt.opttest.ParticlePotentialProblem.ParameterIndex().
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleConstraintGradient(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleConstraintValue(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleDistance(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleSingleForce(), IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleDistance(), and IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleSingleForce().
ParticleDistance()
double IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleDistance (int firstIndex, int secondIndex, IVector parameters) inline
Returns the Euclidean distance between the two particles with specified indices.
Parameters
firstIndex Index of the first particle.
secondIndex Index of the second particle.
parameters Vector of parameters.
References IG.Lib.opt.opttest.ParticlePotentialProblem._spaceDimension, and IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleCoordinate().
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.PairwisePotentialEnergy(), and IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleSingleForce().
StaticParticleDistance()
virtual double IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleDistance (int staticParticleIndex, int particleIndex, IVector parameters, IVector[] staticCoordinates) inline virtual
Calculates and returns the distance between the specified static particle and the specified free particle of the particle arrangement.
Parameters
staticParticleIndex Index of the static particle.
particleIndex Index of free particle.
parameters Problem parameters, assembled vector of coordinated of all free particles.
staticCoordinates Array of coordinates of static particles.
References IG.Lib.opt.opttest.ParticlePotentialProblem._spaceDimension, and IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleCoordinate().
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.StaticPairwisePotentialEnergy(), and IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleSingleForce().
StaticPairwisePotentialEnergy() [1/2]
virtual double IG.Lib.opt.opttest.ParticlePotentialProblem.StaticPairwisePotentialEnergy (int staticParticleIndex, int particleIndex, double potentialFactor, double[] charges, IRealFunction potentialFunction, IVector parameters, double[] staticCharges, IVector[] staticCoordinates) inline virtual
Calculates and returns pairwise electrical potential energy of the specified static and the specified free particle, providing the necessary coefficiets through parameters.
Parameters
staticParticleIndex Index of the static particle.
particleIndex Index of the free particle.
potentialFactor Factor by which potential is multiplied.
charges Array of particle charges.
potentialFunction Function of distance between two particles that defines electrostatic potential energy contributed by these two particles when multiplied by a product of particle charges and a multiplicative constant.
parameters Vector of parameters that contains coordinates of all particles.
staticCharges Array of static particle's charges.
staticCoordinates Array of coordinate vectors of static particles.
References IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleDistance(), and IG.Num.IRealFunction.Value().
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergy(), and IG.Lib.opt.opttest.ParticlePotentialProblem.StaticPairwisePotentialEnergy().
StaticPairwisePotentialEnergy() [2/2]
virtual double IG.Lib.opt.opttest.ParticlePotentialProblem.StaticPairwisePotentialEnergy (int staticParticleIndex, int particleIndex, IVector parameters) inline virtual
Calculates and returns electrical potential energy of the specified static and free particle.
All the necessary parameters are obteined from the object.
Parameters
referenceIndex Indx of the static particle.
particleIndex Index of the free particle.
parameters Vector of parameters that contains coordinates of all particles.
References IG.Lib.opt.opttest.ParticlePotentialProblem.Charges, IG.Lib.opt.opttest.ParticlePotentialProblem.Lock, IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialFactor, IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialFunction, IG.Lib.opt.opttest.ParticlePotentialProblem.StaticPairwisePotentialEnergy(), IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleCharges, and IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleCoordinates.
PairwisePotentialEnergy() [1/2]
virtual double IG.Lib.opt.opttest.ParticlePotentialProblem.PairwisePotentialEnergy (int referenceIndex, int particleIndex, double potentialFactor, double[] charges, IRealFunction potentialFunction, IVector parameters) inline virtual
Calculates and returns pairwise electrical potential energy of two particles, providing the necessary coefficiets through parameters.
Parameters
referenceIndex Indx of the first particle.
particleIndex Index of the second particle.
potentialFactor Factor by which potential is multiplied.
charges Array of particle charges.
potentialFunction Function of distance between two particles that defines electrostatic potential energy contributed by these two particles when multiplied by a product of particle charges and a multiplicative consrant.
parameters Vector of parameters that contains coordinates of all particles.
References IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleDistance(), and IG.Num.IRealFunction.Value().
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.PairwisePotentialEnergy(), and IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergy().
PairwisePotentialEnergy() [2/2]
virtual double IG.Lib.opt.opttest.ParticlePotentialProblem.PairwisePotentialEnergy (int referenceIndex, int particleIndex, IVector parameters) inline virtual
Calculates and returns electrical potential energy of two particles.
Parameters
referenceIndex Indx of the first particle.
particleIndex Index of the second particle.
parameters Vector of parameters that contains coordinates of all particles.
References IG.Lib.opt.opttest.ParticlePotentialProblem.Charges, IG.Lib.opt.opttest.ParticlePotentialProblem.Lock, IG.Lib.opt.opttest.ParticlePotentialProblem.PairwisePotentialEnergy(), IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialFactor, and IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialFunction.
PotentialEnergy()
virtual double IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergy (IVector parameters) inline virtual
Calculates and returns the total potential energy of all particles in the formation.
Parameters
parameters Vector of parameters that contains coordinates of all particles.
References IG.Lib.opt.opttest.ParticlePotentialProblem._numParticles, IG.Lib.opt.opttest.ParticlePotentialProblem._numStaticParticles, IG.Lib.opt.opttest.ParticlePotentialProblem.Charges, IG.Lib.opt.opttest.ParticlePotentialProblem.Lock, IG.Lib.opt.opttest.ParticlePotentialProblem.PairwisePotentialEnergy(), IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialFactor, IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialFunction, IG.Lib.opt.opttest.ParticlePotentialProblem.StaticPairwisePotentialEnergy(), IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleCharges, and IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleCoordinates.
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.ObjectiveFunctionPotentialEnergy.ReferenceValue().
StaticParticleSingleForce() [1/3]
void IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleSingleForce (int staticParticleIndex, int particleIndex, double potentialFactor, double[] charges, IRealFunction potentialFunction, IVector parameters, double[] staticCharges, IVector[] staticCoordinates, ref IVector particleForce) inline
Calculates the electrostatic force acting on the specified free particle by a single specified statitc particle.
Parameters
staticParticleIndex Index of the particle that is a source of electrostatic force.
particleIndex Index of the particle on which the calculated force acts.
potentialFactor Factor by which potential is multiplied.
charges Array of particle charges.
parameters Vector of parameters that contains coordinates of all particles.
particleForce Vector where particle force is stored to.
References IG.Lib.opt.opttest.ParticlePotentialProblem._spaceDimension, IG.Num.IRealFunction.Derivative(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleCoordinate(), IG.Num.VectorBase.Resize(), and IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleDistance().
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergyGradient(), and IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleSingleForce().
StaticParticleSingleForce() [2/3]
void IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleSingleForce (int staticParticleIndex, int particleIndex, IVector parameters, ref IVector particleForce) inline
Calculates the electrostatic force acting on the specified free particle by a single specified static particle.
Parameters
staticParticleIndex Index of the particle that is a source of electrostatic force.
particleIndex Index of the particle on which the calculated force acts.
particleForce Vector where particle force is stored to.
Charges of other particles, potential factor and potential function are obtained
References IG.Lib.opt.opttest.ParticlePotentialProblem.Charges, IG.Lib.opt.opttest.ParticlePotentialProblem.Lock, IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialFactor, IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialFunction, IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleCharges, IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleCoordinates, and IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleSingleForce().
StaticParticleSingleForce() [3/3]
virtual void IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleSingleForce (int particleIndex, IVector parameters, ref IVector particleForce) inline virtual
Calculates the electrostatic force acting on the specified free particle by all static particles in the arrangement.
Parameters
particleIndex Index of the particle on which the calculated force acts.
parameters Vector of parameters that contains coordinates of all particles.
particleForce Vector where particle force is stored to.
References IG.Lib.opt.opttest.ParticlePotentialProblem._auxParticleVector, IG.Lib.opt.opttest.ParticlePotentialProblem._numParticles, IG.Lib.opt.opttest.ParticlePotentialProblem._spaceDimension, IG.Lib.opt.opttest.ParticlePotentialProblem.Charges, IG.Lib.opt.opttest.ParticlePotentialProblem.Lock, IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialFactor, IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialFunction, IG.Num.VectorBase.Resize(), IG.Num.VectorBase.SetZero(), IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleCharges, IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleCoordinates, and IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleSingleForce().
ParticleSingleForce() [1/3]
void IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleSingleForce (int referenceIndex, int particleIndex, double potentialFactor, double[] charges, IRealFunction potentialFunction, IVector parameters, ref IVector particleForce) inline
Calculates the electrostatic force acting on the specified particle by a single specified another particle.
Parameters
referenceIndex Index of the particle that is a source of electrostatic force.
particleIndex Index of the particle on which the calculated force acts.
potentialFactor Factor by which potential is multiplied.
charges Array of particle charges.
parameters Vector of parameters that contains coordinates of all particles.
particleForce Vector where particle force is stored to.
References IG.Lib.opt.opttest.ParticlePotentialProblem._spaceDimension, IG.Num.IRealFunction.Derivative(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleCoordinate(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleDistance(), and IG.Num.VectorBase.Resize().
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleSingleForce(), and IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergyGradient().
ParticleSingleForce() [2/3]
void IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleSingleForce (int referenceIndex, int particleIndex, IVector parameters, ref IVector particleForce) inline
Calculates the electrostatic force acting on the specified particle by a single specified another free particle.
Parameters
referenceIndex Index of the particle that is a source of electrostatic force.
particleIndex Index of the particle on which the calculated force acts.
particleForce Vector where particle force is stored to.
Charges of other particles, potential factor and potential function are obtained
References IG.Lib.opt.opttest.ParticlePotentialProblem.Charges, IG.Lib.opt.opttest.ParticlePotentialProblem.Lock, IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleSingleForce(), IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialFactor, and IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialFunction.
ParticleSingleForce() [3/3]
virtual void IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleSingleForce (int particleIndex, IVector parameters, ref IVector particleForce) inline virtual
Calculates the electrostatic force acting on the specified particle by all other free particles in the arrangement.
Parameters
particleIndex Index of the particle on which the calculated force acts.
parameters Vector of parameters that contains coordinates of all particles.
particleForce Vector where particle force is stored to.
References IG.Lib.opt.opttest.ParticlePotentialProblem._auxParticleVector, IG.Lib.opt.opttest.ParticlePotentialProblem._numParticles, IG.Lib.opt.opttest.ParticlePotentialProblem._spaceDimension, IG.Lib.opt.opttest.ParticlePotentialProblem.Charges, IG.Lib.opt.opttest.ParticlePotentialProblem.Lock, IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleSingleForce(), IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialFactor, IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialFunction, IG.Num.VectorBase.Resize(), and IG.Num.VectorBase.SetZero().
PotentialEnergyGradient()
virtual void IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergyGradient (IVector parameters, ref IVector gradient) inline virtual
Calculates gradient of total potential, which is effectively composed of forces acting on the individual particles by all other particles in the arrangement (and that equals to gradients of potential energy of individual particle in the field of other particles).
Parameters
parameters Vector of problem parameters where coordinates of all free particles are gathered.
gradient Vector where gradient of potential energy is stored.
References IG.Lib.opt.opttest.ParticlePotentialProblem._auxParticleVector, IG.Lib.opt.opttest.ParticlePotentialProblem._numParticles, IG.Lib.opt.opttest.ParticlePotentialProblem._numStaticParticles, IG.Lib.opt.opttest.ParticlePotentialProblem._spaceDimension, IG.Lib.opt.opttest.ParticlePotentialProblem.Charges, IG.Lib.opt.opttest.ParticlePotentialProblem.Lock, IG.Lib.opt.opttest.ParticlePotentialProblem.ParameterIndex(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleSingleForce(), IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialFactor, IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialFunction, IG.Lib.opt.opttest.ParticlePotentialProblem.ProblemDimension, IG.Num.VectorBase.Resize(), IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleCharges, IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleCoordinates, and IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleSingleForce().
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.ObjectiveFunctionPotentialEnergy.ReferenceGradientPlain().
ParticleConstraintValue()
double IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleConstraintValue (int particleIndex, IVector parameters) inline
Returns value of the constraint function for the specified particle in the arrangement.
Constraint is c_i(r_i) = ||r_i||-1 <= 0.
Parameters
particleIndex Index of the particle for which constraint function value is returned.
parameters Vector of parameters (global coordinates - assembly of coordinates of all free particles).
References IG.Lib.opt.opttest.ParticlePotentialProblem._spaceDimension, and IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleCoordinate().
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.ConstraintFunction().
ParticleConstraintGradient()
void IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleConstraintGradient (int particleIndex, IVector parameters, ref IVector partConstraintGrad) inline
Calculates and stores gradient of the constraint function related to the specified particle, in terms of particle coordinates.
Constraint gradient related to particle i is c_i(r_i) = r_i/||r_i||.
Parameters
particleIndex Index of the particle for which constraint gradient is calculated.
parameters Vector of parameters (global coordinates - assembly of coordinates of all free particles).
partConstraintGrad Vector of the space dimension where constraint gradient is stored.
References IG.Lib.opt.opttest.ParticlePotentialProblem._spaceDimension, IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleCoordinate(), and IG.Num.VectorBase.Resize().
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.ConstraintGradient().
ConstraintFunction()
double IG.Lib.opt.opttest.ParticlePotentialProblem.ConstraintFunction (int whichConstraint, IVector parameters) inline
Returns value of the specified constraint function related to specified particle in the arrangement.
Constraint is c_i(r_i) = ||r_i||-1 <= 0.
Parameters
whichConstraint Specifies Index of the constraint function (that corresponds the index of the related particle).
parameters Vector of parameters (global coordinates - assembly of coordinates of all free particles).
References IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleConstraintValue().
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.ConstraintFunctionParticleConstraint.ReferenceValue().
ConstraintGradient()
void IG.Lib.opt.opttest.ParticlePotentialProblem.ConstraintGradient (int whichConstraint, IVector parameters, ref IVector constraintGradient) inline
Calculates and stores gradient of the specified constraint function that is related to the specified particle, in terms of global parameters (vector assembly of all particle coordinates).
Constraint gradient related to particle i is c_i(r_i) = r_i/||r_i||.
Parameters
whichConstraint Specifies Index of the constraint function (that corresponds the index of the related particle).
parameters Vector of parameters (global coordinates - assembly of coordinates of all free particles).
constraintGradient Vector where constraint gradient is stored, dimension equals dimension of parameters .
References IG.Lib.opt.opttest.ParticlePotentialProblem._auxParticleVector, IG.Lib.opt.opttest.ParticlePotentialProblem._spaceDimension, IG.Lib.opt.opttest.ParticlePotentialProblem.Lock, IG.Lib.opt.opttest.ParticlePotentialProblem.ParameterIndex(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleConstraintGradient(), IG.Lib.opt.opttest.ParticlePotentialProblem.ProblemDimension, and IG.Num.VectorBase.Resize().
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.ConstraintFunctionParticleConstraint.ReferenceGradientPlain().
Member Data Documentation
_mainLock
readonly object IG.Lib.opt.opttest.ParticlePotentialProblem._mainLock = new object() private
_numParticles
int IG.Lib.opt.opttest.ParticlePotentialProblem._numParticles = 8 protected
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.CoordinateIndex(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParameterIndex(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleIndex(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleSingleForce(), IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergy(), IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergyGradient(), IG.Lib.opt.opttest.ParticlePotentialProblem.SetCharges(), and IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleSingleForce().
_spaceDimension
int IG.Lib.opt.opttest.ParticlePotentialProblem._spaceDimension = 2 protected
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.ConstraintGradient(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleConstraintGradient(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleConstraintValue(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleDistance(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleSingleForce(), IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergyGradient(), IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleDistance(), and IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleSingleForce().
_potentialFactor
double IG.Lib.opt.opttest.ParticlePotentialProblem._potentialFactor = 1.0 protected
_charges
double [] IG.Lib.opt.opttest.ParticlePotentialProblem._charges private
_potentialFunction
IRealFunction IG.Lib.opt.opttest.ParticlePotentialProblem._potentialFunction = Func.GetReciprocal() protected
_numStaticParticles
int IG.Lib.opt.opttest.ParticlePotentialProblem._numStaticParticles private
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergy(), and IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergyGradient().
_staticParticleCoordinates
IVector [] IG.Lib.opt.opttest.ParticlePotentialProblem._staticParticleCoordinates private
_staticParticleCharges
double [] IG.Lib.opt.opttest.ParticlePotentialProblem._staticParticleCharges private
_auxParticleVector
IVector IG.Lib.opt.opttest.ParticlePotentialProblem._auxParticleVector = null protected
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.ConstraintGradient(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleSingleForce(), IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergyGradient(), and IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleSingleForce().
_objectiveFunction
ScalarFunctionBase IG.Lib.opt.opttest.ParticlePotentialProblem._objectiveFunction private
_constraintFunctions
ScalarFunctionBase [] IG.Lib.opt.opttest.ParticlePotentialProblem._constraintFunctions private
Property Documentation
Lock
object IG.Lib.opt.opttest.ParticlePotentialProblem.Lock get
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.ConstraintGradient(), IG.Lib.opt.opttest.ParticlePotentialProblem.PairwisePotentialEnergy(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleSingleForce(), IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergy(), IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergyGradient(), IG.Lib.opt.opttest.ParticlePotentialProblem.SetCharges(), IG.Lib.opt.opttest.ParticlePotentialProblem.SetStaticCharges(), IG.Lib.opt.opttest.ParticlePotentialProblem.StaticPairwisePotentialEnergy(), and IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleSingleForce().
NumParticles
int IG.Lib.opt.opttest.ParticlePotentialProblem.NumParticles get protected set
Number of charged particles in the arrangement.
Once the object is created, this can not be changed.
SpaceDimension
int IG.Lib.opt.opttest.ParticlePotentialProblem.SpaceDimension get protected set
Dimension of space in which particles are positioned.
Once the object is created, this can not be changed.
ProblemDimension
int IG.Lib.opt.opttest.ParticlePotentialProblem.ProblemDimension get
Dimension of the problem, product of the space dimension and the number of free particles.
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.ConstraintGradient(), and IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergyGradient().
PotentialFactor
double IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialFactor get protected set
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.PairwisePotentialEnergy(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleSingleForce(), IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergy(), IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergyGradient(), IG.Lib.opt.opttest.ParticlePotentialProblem.StaticPairwisePotentialEnergy(), and IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleSingleForce().
Charges
double [] IG.Lib.opt.opttest.ParticlePotentialProblem.Charges get set
Gets or sets the array of particle charges. Length of the array must be the same as the number of particles. If not set, getter will return the array in which all charges are equal to 1.
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.PairwisePotentialEnergy(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleSingleForce(), IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergy(), IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergyGradient(), IG.Lib.opt.opttest.ParticlePotentialProblem.SetCharges(), IG.Lib.opt.opttest.ParticlePotentialProblem.StaticPairwisePotentialEnergy(), and IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleSingleForce().
PotentialFunction
IRealFunction IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialFunction get set
The potential function.
As function of distance between two particles, this function defines electrostatic potential energy contributed by these two particles when multiplied by a product of particle charges and a multiplicative consrant (defined by the property PotentialFactor).
Set to f(x)=1/x by default.
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.PairwisePotentialEnergy(), IG.Lib.opt.opttest.ParticlePotentialProblem.ParticleSingleForce(), IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergy(), IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergyGradient(), IG.Lib.opt.opttest.ParticlePotentialProblem.StaticPairwisePotentialEnergy(), and IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleSingleForce().
NumStaticParticles
int IG.Lib.opt.opttest.ParticlePotentialProblem.NumStaticParticles get private set
Gets the number of static particles.
StaticParticleCoordinates
IVector [] IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleCoordinates get set
Array of coordinate vectors of staticle charges.
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergy(), IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergyGradient(), IG.Lib.opt.opttest.ParticlePotentialProblem.StaticPairwisePotentialEnergy(), and IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleSingleForce().
StaticParticleCharges
double [] IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleCharges get set
Gets or sets the array of static particle's charges. If not set, getter will return the array in which all charges are equal to 1.
Referenced by IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergy(), IG.Lib.opt.opttest.ParticlePotentialProblem.PotentialEnergyGradient(), IG.Lib.opt.opttest.ParticlePotentialProblem.SetStaticCharges(), IG.Lib.opt.opttest.ParticlePotentialProblem.StaticPairwisePotentialEnergy(), and IG.Lib.opt.opttest.ParticlePotentialProblem.StaticParticleSingleForce().
ObjectiveFunction
ScalarFunctionBase IG.Lib.opt.opttest.ParticlePotentialProblem.ObjectiveFunction get
Returns the scalar function that represents the objective function of the current minimal particle potential energy problem.
ConstraintFunctions
ScalarFunctionBase [] IG.Lib.opt.opttest.ParticlePotentialProblem.ConstraintFunctions get protected set
Returns an array of scalar functions that represent the constraint functions of the current minimal particle potential energy problem.
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/opt/opttest/ParticlePotential.cs