Doc: IGLib EXTENDED: AForge.Imaging.Filters.FiltersSequence Class Reference
AForge.Imaging.Filters.FiltersSequence Class Reference
Filters' collection to apply to an image in sequence.
Public Member Functions
FiltersSequence ()
Initializes a new instance of the FiltersSequence class.
FiltersSequence (params IFilter[] filters)
Initializes a new instance of the FiltersSequence class.
void Add (IFilter filter)
Add new filter to the sequence.
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
Properties
IFilter this[int index] [get]
Get filter at the specified index.
Detailed Description
Filters' collection to apply to an image in sequence.
The class represents collection of filters, which need to be applied to an image in sequence. Using the class user may specify set of filters, which will be applied to source image one by one in the order user defines them.
The class itself does not define which pixel formats are accepted for the source image and which pixel formats may be produced by the filter. Format of acceptable source and possible output is defined by filters, which added to the sequence.
Sample usage:
// create filter, which is binarization sequence
FiltersSequence filter = new FiltersSequence(
    new GrayscaleBT709( ),
    new Threshold( )
);
// apply the filter
Bitmap newImage = filter.Apply(image);
Constructor & Destructor Documentation
FiltersSequence() [1/2]
AForge.Imaging.Filters.FiltersSequence.FiltersSequence () inline
Initializes a new instance of the FiltersSequence class.
FiltersSequence() [2/2]
AForge.Imaging.Filters.FiltersSequence.FiltersSequence (params IFilter[] filters) inline
Initializes a new instance of the FiltersSequence class.
Parameters
filters Sequence of filters to apply.
Member Function Documentation
Add()
void AForge.Imaging.Filters.FiltersSequence.Add (IFilter filter) inline
Add new filter to the sequence.
Parameters
filter Filter to add to the sequence.
Apply() [1/4]
Bitmap AForge.Imaging.Filters.FiltersSequence.Apply (Bitmap image) inline
Apply filter to an image.
Parameters
image Source image to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The method keeps the source image unchanged and returns the result of image processing filter as new image.
Exceptions
ApplicationException No filters were added into the filters' sequence.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.Filters.FiltersSequence.Apply(), and HoughTransform.MainForm.openToolStripMenuItem_Click().
Apply() [2/4]
Bitmap AForge.Imaging.Filters.FiltersSequence.Apply (BitmapData imageData) inline
Apply filter to an image.
Parameters
imageData Source image to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The filter accepts bitmap data as input and returns the result of image processing filter as new image. The source image data are kept unchanged.
Exceptions
ApplicationException No filters were added into the filters' sequence.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.FiltersSequence.Apply(), AForge.Imaging.UnmanagedImage.Dispose(), and AForge.Imaging.UnmanagedImage.ToManagedImage().
Apply() [3/4]
UnmanagedImage AForge.Imaging.Filters.FiltersSequence.Apply (UnmanagedImage image) inline
Apply filter to an image in unmanaged memory.
Parameters
image Source image in unmanaged memory to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The method keeps the source image unchanged and returns the result of image processing filter as new image.
Exceptions
ApplicationException No filters were added into the filters' sequence.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.UnmanagedImage.Dispose().
Apply() [4/4]
void AForge.Imaging.Filters.FiltersSequence.Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage) inline
Apply filter to an image in unmanaged memory.
Parameters
sourceImage Source image in unmanaged memory to apply filter to.
destinationImage Destination image in unmanaged memory to put result into.
The method keeps the source image unchanged and puts result of image processing into destination image.
<note>The destination image must have width, height and pixel format as it is expected by the final filter in the sequence.</note>
Exceptions
ApplicationException No filters were added into the filters' sequence.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.UnmanagedImage.Dispose().
Property Documentation
this[int index]
IFilter AForge.Imaging.Filters.FiltersSequence.this[int index] get
Get filter at the specified index.
Parameters
index Index of filter to get.
Returns
Returns filter at specified index.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/FiltersSequence.cs