Doc: IGLib EXTENDED: IG.Neural.NeuralParametricDemoOldAboutWindow Class Reference
IG.Neural.NeuralParametricDemoOldAboutWindow Class Reference
Public Member Functions
NeuralParametricDemoOldAboutWindow ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void btnAboutClose_Click (object sender, EventArgs e)
void NeuralParametricDemoOldAboutWindow_Click (object sender, EventArgs e)
void NeuralParametricDemoOldAboutWindow_MouseUp (object sender, MouseEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Label lblAboutSoftware
System.Windows.Forms.TextBox txtAboutAuthors
System.Windows.Forms.Button btnAboutClose
Constructor & Destructor Documentation
NeuralParametricDemoOldAboutWindow()
IG.Neural.NeuralParametricDemoOldAboutWindow.NeuralParametricDemoOldAboutWindow () inline
References IG.Neural.NeuralParametricDemoOldAboutWindow.InitializeComponent().
Member Function Documentation
btnAboutClose_Click()
void IG.Neural.NeuralParametricDemoOldAboutWindow.btnAboutClose_Click (object sender, EventArgs e) inline private
Referenced by IG.Neural.NeuralParametricDemoOldAboutWindow.InitializeComponent().
NeuralParametricDemoOldAboutWindow_Click()
void IG.Neural.NeuralParametricDemoOldAboutWindow.NeuralParametricDemoOldAboutWindow_Click (object sender, EventArgs e) inline private
Referenced by IG.Neural.NeuralParametricDemoOldAboutWindow.InitializeComponent().
NeuralParametricDemoOldAboutWindow_MouseUp()
void IG.Neural.NeuralParametricDemoOldAboutWindow.NeuralParametricDemoOldAboutWindow_MouseUp (object sender, MouseEventArgs e) inline private
Referenced by IG.Neural.NeuralParametricDemoOldAboutWindow.InitializeComponent().
Dispose()
override void IG.Neural.NeuralParametricDemoOldAboutWindow.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.NeuralParametricDemoOldAboutWindow.components.
InitializeComponent()
void IG.Neural.NeuralParametricDemoOldAboutWindow.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.NeuralParametricDemoOldAboutWindow.btnAboutClose, IG.Neural.NeuralParametricDemoOldAboutWindow.btnAboutClose_Click(), IG.Neural.NeuralParametricDemoOldAboutWindow.lblAboutSoftware, IG.Neural.NeuralParametricDemoOldAboutWindow.NeuralParametricDemoOldAboutWindow_Click(), IG.Neural.NeuralParametricDemoOldAboutWindow.NeuralParametricDemoOldAboutWindow_MouseUp(), and IG.Neural.NeuralParametricDemoOldAboutWindow.txtAboutAuthors.
Referenced by IG.Neural.NeuralParametricDemoOldAboutWindow.NeuralParametricDemoOldAboutWindow().
Member Data Documentation
components
System.ComponentModel.IContainer IG.Neural.NeuralParametricDemoOldAboutWindow.components = null private
Required designer variable.
Referenced by IG.Neural.NeuralParametricDemoOldAboutWindow.Dispose().
lblAboutSoftware
System.Windows.Forms.Label IG.Neural.NeuralParametricDemoOldAboutWindow.lblAboutSoftware private
Referenced by IG.Neural.NeuralParametricDemoOldAboutWindow.InitializeComponent().
txtAboutAuthors
System.Windows.Forms.TextBox IG.Neural.NeuralParametricDemoOldAboutWindow.txtAboutAuthors private
Referenced by IG.Neural.NeuralParametricDemoOldAboutWindow.InitializeComponent().
btnAboutClose
System.Windows.Forms.Button IG.Neural.NeuralParametricDemoOldAboutWindow.btnAboutClose private
Referenced by IG.Neural.NeuralParametricDemoOldAboutWindow.InitializeComponent().
The documentation for this class was generated from the following files:
shelldev/lib/extended/LibNeuralExtForms/NeuralParametricDemoOldAboutWindow.cs
shelldev/lib/extended/LibNeuralExtForms/NeuralParametricDemoOldAboutWindow.Designer.cs