Doc: IGLib EXTENDED: Meta.Numerics.Spin.SpinState Struct Reference
Meta.Numerics.Spin.SpinState Struct Reference
Represents the state of a spinor.
Public Member Functions
SpinState (double j, double m)
Instantiates a new SpinState with the given spin and magnetic quantum numbers.
SpinState (Spin s, double m)
Instantiates a new SpinState with the given spin and magnetic quantum number.
override bool Equals (object obj)
Determines whether the given object represents the same spin state.
override int GetHashCode ()
Computes a hash function for the spin state.
override string ToString ()
Produces a string representation of the spin state.
Static Public Member Functions
static bool operator== (SpinState s1, SpinState s2)
Determines whether two spin states are equal.
static bool operator!= (SpinState s1, SpinState s2)
Determines whether two spin states are unequal.
Properties
double J [get]
Gets the spin value of the spin state.
double M [get]
Gets the magnetic substate value of the spin state.
Spin Representation [get]
Gets the spinor representation to which the spin state belongs.
Static Private Member Functions
static bool Equals (SpinState s1, SpinState s2)
static string SpinString (int twoJ)
Private Attributes
Spin spin
int twoM
Detailed Description
Represents the state of a spinor.
Constructor & Destructor Documentation
SpinState() [1/2]
Meta.Numerics.Spin.SpinState.SpinState (double j, double m) inline
Instantiates a new SpinState with the given spin and magnetic quantum numbers.
Parameters
j The spin number.
m The magnetic number.
SpinState() [2/2]
Meta.Numerics.Spin.SpinState.SpinState (Spin s, double m) inline
Instantiates a new SpinState with the given spin and magnetic quantum number.
Parameters
s The spin.
m The magnetic quantum number.
References Meta.Numerics.Spin.SpinState.spin, and Meta.Numerics.Spin.SpinState.twoM.
Member Function Documentation
Equals() [1/2]
static bool Meta.Numerics.Spin.SpinState.Equals (SpinState s1, SpinState s2) inline static private
References Meta.Numerics.Spin.SpinState.spin, and Meta.Numerics.Spin.SpinState.twoM.
Referenced by Meta.Numerics.Spin.SpinState.Equals(), Meta.Numerics.Spin.SpinState.operator!=(), and Meta.Numerics.Spin.SpinState.operator==().
operator==()
static bool Meta.Numerics.Spin.SpinState.operator== (SpinState s1, SpinState s2) inline static
Determines whether two spin states are equal.
Parameters
s1 The first spin state.
s2 The second spin state.
Returns
True if s1 and s2 are equal, otherwise false.
References Meta.Numerics.Spin.SpinState.Equals().
operator!=()
static bool Meta.Numerics.Spin.SpinState.operator!= (SpinState s1, SpinState s2) inline static
Determines whether two spin states are unequal.
Parameters
s1 The first spin state.
s2 The second spin state.
Returns
False if s1 and s2 are equal, otherwise true.
References Meta.Numerics.Spin.SpinState.Equals().
Equals() [2/2]
override bool Meta.Numerics.Spin.SpinState.Equals (object obj) inline
Determines whether the given object represents the same spin state.
Parameters
obj The object to compare.
Returns
True if obj is an equal spin state, otherwise false.
References Meta.Numerics.Spin.SpinState.Equals().
GetHashCode()
override int Meta.Numerics.Spin.SpinState.GetHashCode () inline
Computes a hash function for the spin state.
Returns
An integer which is guaranteed equal for equal spin states, an unlikely to be equal for unequal spin states.
ToString()
override string Meta.Numerics.Spin.SpinState.ToString () inline
Produces a string representation of the spin state.
Returns
A string representation of the spin state.
References Meta.Numerics.Spin.SpinState.spin, Meta.Numerics.Spin.SpinState.SpinString(), Meta.Numerics.Spin.Spin.ToString(), and Meta.Numerics.Spin.SpinState.twoM.
Referenced by Meta.Numerics.Spin.SpinState.SpinString().
SpinString()
static string Meta.Numerics.Spin.SpinState.SpinString (int twoJ) inline static private
References Meta.Numerics.Spin.SpinState.ToString().
Referenced by Meta.Numerics.Spin.SpinState.ToString().
Member Data Documentation
spin
Spin Meta.Numerics.Spin.SpinState.spin private
Referenced by Meta.Numerics.Spin.SpinState.Equals(), Meta.Numerics.Spin.SpinState.SpinState(), and Meta.Numerics.Spin.SpinState.ToString().
twoM
int Meta.Numerics.Spin.SpinState.twoM private
Referenced by Meta.Numerics.Spin.SpinState.Equals(), Meta.Numerics.Spin.SpinState.SpinState(), and Meta.Numerics.Spin.SpinState.ToString().
Property Documentation
J
double Meta.Numerics.Spin.SpinState.J get
Gets the spin value of the spin state.
Referenced by Test.SpinTest.ClebschGordonOrthonormalityJM(), Test.SpinTest.SixJThreeJRelation(), Test.SpinTest.ThreeJExchangeSymmetry(), Test.SpinTest.ThreeJRacahSymmetry(), and Test.SpinTest.ThreeJRecursion().
M
double Meta.Numerics.Spin.SpinState.M get
Gets the magnetic substate value of the spin state.
Referenced by Test.SpinTest.ClebschGordonOrthonormalityJM(), Test.SpinTest.ClebschGordonOrthonormalityMM(), Test.SpinTest.SixJThreeJRelation(), Test.SpinTest.ThreeJExchangeSymmetry(), Test.SpinTest.ThreeJRacahSymmetry(), and Test.SpinTest.ThreeJRecursion().
Representation
Spin Meta.Numerics.Spin.SpinState.Representation get
Gets the spinor representation to which the spin state belongs.
The documentation for this struct was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Special/SpinState.cs