Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLASET Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLASET Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLASET (LSAME lsame)
DLASET ()
void Run (string UPLO, int M, int N, double ALPHA, double BETA, ref double[] A, int offset_a, int LDA)
Private Attributes
LSAME _lsame
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLASET initializes an m-by-n matrix A to BETA on the diagonal and ALPHA on the offdiagonals.
/summary>
Constructor & Destructor Documentation
DLASET() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLASET.DLASET (LSAME lsame) inline
DLASET() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLASET.DLASET () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLASET.Run (string UPLO, int M, int N, double ALPHA, double BETA, ref double[] A, int offset_a, int LDA) inline
Purpose
DLASET initializes an m-by-n matrix A to BETA on the diagonal and ALPHA on the offdiagonals.
/summary>
Parameters
UPLO (input) CHARACTER*1 Specifies the part of the matrix A to be set. = 'U': Upper triangular part is set; the strictly lower triangular part of A is not changed. = 'L': Lower triangular part is set; the strictly upper triangular part of A is not changed. Otherwise: All of the matrix A is set. /param>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. 0. /param>
Parameters
ALPHA (input) DOUBLE PRECISION The constant to which the offdiagonal elements are to be set. /param>
Parameters
BETA (input) DOUBLE PRECISION The constant to which the diagonal elements are to be set. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On exit, the leading m-by-n submatrix of A is set as follows:
if UPLO = 'U', A(i,j) = ALPHA, 1.LE.i.LE.j-1, 1.LE.j.LE.n, if UPLO = 'L', A(i,j) = ALPHA, j+1.LE.i.LE.m, 1.LE.j.LE.n, otherwise, A(i,j) = ALPHA, 1.LE.i.LE.m, 1.LE.j.LE.n, i.ne.j,
and, for all UPLO, A(i,i) = BETA, 1.LE.i.LE.min(m,n). /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
References DotNumerics.LinearAlgebra.CSLapack.LSAME.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DSBTRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD8.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED3.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR5.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALSD.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEDC.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELS.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD2.Run(), DotNumerics.LinearAlgebra.CSLapack.DBDSDC.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGSVP.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR3.Run(), DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELSY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASDA.Run(), DotNumerics.LinearAlgebra.CSLapack.DHSEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELSD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DTGSJA.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLASET._lsame private
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlaset.cs