Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGEMM Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGEMM Class Reference
Public Member Functions
DGEMM (LSAME lsame, XERBLA xerbla)
DGEMM ()
void Run (string TRANSA, string TRANSB, int M, int N, int K, double ALPHA, double[] A, int offset_a, int LDA, double[] B, int offset_b, int LDB, double BETA, ref double[] C, int offset_c, int LDC)
Private Attributes
LSAME _lsame
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
Purpose
DGEMM performs one of the matrix-matrix operations
C := alpha*op(A)*op(B) + beta*C,
where op(X) is one of
op(X) = X or op(X) = X',
alpha and beta are scalars, and A, B and C are matrices, with op(A) an m by k matrix, op(B) a k by n matrix and C an m by n matrix.
/summary>
Constructor & Destructor Documentation
DGEMM() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGEMM.DGEMM (LSAME lsame, XERBLA xerbla) inline
DGEMM() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGEMM.DGEMM () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run (string TRANSA, string TRANSB, int M, int N, int K, double ALPHA, double[] A, int offset_a, int LDA, double[] B, int offset_b, int LDB, double BETA, ref double[] C, int offset_c, int LDC) inline
Purpose
DGEMM performs one of the matrix-matrix operations
C := alpha*op(A)*op(B) + beta*C,
where op(X) is one of
op(X) = X or op(X) = X',
alpha and beta are scalars, and A, B and C are matrices, with op(A) an m by k matrix, op(B) a k by n matrix and C an m by n matrix.
/summary>
Parameters
TRANSA
CHARACTER*1. On entry, TRANSA specifies the form of op(A) to be used in the matrix multiplication as follows:
TRANSA = 'N' or 'n', op(A) = A.
TRANSA = 'T' or 't', op(A) = A'.
TRANSA = 'C' or 'c', op(A) = A'.
Unchanged on exit. /param>
Parameters
TRANSB
CHARACTER*1. On entry, TRANSB specifies the form of op(B) to be used in the matrix multiplication as follows:
TRANSB = 'N' or 'n', op(B) = B.
TRANSB = 'T' or 't', op(B) = B'.
TRANSB = 'C' or 'c', op(B) = B'.
Unchanged on exit. /param>
Parameters
M
INTEGER. On entry, M specifies the number of rows of the matrix op(A) and of the matrix C. M must be at least zero. Unchanged on exit. /param>
Parameters
N
INTEGER. On entry, N specifies the number of columns of the matrix op(B) and the number of columns of the matrix C. N must be at least zero. Unchanged on exit. /param>
Parameters
K
INTEGER. On entry, K specifies the number of columns of the matrix op(A) and the number of rows of the matrix op(B). K must be at least zero. Unchanged on exit. /param>
Parameters
ALPHA and beta are scalars, and A, B and C are matrices, with op(A) /param>
Parameters
A
DOUBLE PRECISION array of DIMENSION (LDA, ka), where ka is k when TRANSA = 'N' or 'n', and is m otherwise. Before entry with TRANSA = 'N' or 'n', the leading m by k part of the array A must contain the matrix A, otherwise the leading k by m part of the array A must contain the matrix A. Unchanged on exit. /param>
Parameters
LDA
INTEGER. On entry, LDA specifies the first dimension of A as declared in the calling (sub) program. When TRANSA = 'N' or 'n' then LDA must be at least max(1, m), otherwise LDA must be at least max(1, k). Unchanged on exit. /param>
Parameters
B
DOUBLE PRECISION array of DIMENSION (LDB, kb), where kb is n when TRANSB = 'N' or 'n', and is k otherwise. Before entry with TRANSB = 'N' or 'n', the leading k by n part of the array B must contain the matrix B, otherwise the leading n by k part of the array B must contain the matrix B. Unchanged on exit. /param>
Parameters
LDB
INTEGER. On entry, LDB specifies the first dimension of B as declared in the calling (sub) program. When TRANSB = 'N' or 'n' then LDB must be at least max(1, k), otherwise LDB must be at least max(1, n). Unchanged on exit. /param>
Parameters
BETA
DOUBLE PRECISION. On entry, BETA specifies the scalar beta. When BETA is supplied as zero then C need not be set on input. Unchanged on exit. /param>
Parameters
C := alpha*op(A)*op(B) + beta*C, /param>
Parameters
LDC
INTEGER. On entry, LDC specifies the first dimension of C as declared in the calling (sub) program. LDC must be at least max(1, m). Unchanged on exit.
/param>
References DotNumerics.LinearAlgebra.CSLapack.DGEMM.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGEMM.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGETRI.Run(), DotNumerics.LinearAlgebra.CSLapack.DGETRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGBTRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAHR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFB.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEHRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARZB.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQPS.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED3.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED0.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR5.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD3.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALSD.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEDC.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALSA.Run(), DotNumerics.LinearAlgebra.CSLapack.DSBEVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR3.Run(), DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED7.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DGEMM._lsame private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGEMM._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGEMM.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DGEMM.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgemm.cs