Doc: IGLib EXTENDED: NUnit.Framework.Tests.TestContextTests Class Reference
NUnit.Framework.Tests.TestContextTests Class Reference
Public Member Functions
TestContextTests ()
void ConstructorCanAccessTestDirectory ()
void ConstructorAccessWorkDirectory ()
void TestCanAccessItsOwnName ()
void ConstructorCanAccessFixtureName ()
void TestCaseCanAccessItsOwnName (int x)
void TestCanAccessItsOwnFullName ()
void TestCaseCanAccessItsOwnFullName (int x)
void TestCanAccessItsOwnMethodName ()
void TestCaseCanAccessItsOwnMethodName (int x)
void TestCanAccessItsOwnId ()
void TestCanAccessItsOwnProperties ()
void TestCanAccessWorkDirectory ()
void TestCanAccessTestState_PassingTest ()
void TestCanAccessTestState_FailureInSetUp ()
void TestCanAccessTestState_FailingTest ()
void TestCanAccessTestState_IgnoredInSetUp ()
void TestContextOut_WritesToResult ()
void TestContextWrite_WritesToResult ()
void TestContextWriteLine_WritesToResult ()
void TestContextStoresFailureInfoForTearDown ()
void TestContextStoresFailureInfoForOneTimeTearDown ()
Private Attributes
string _name
string _testDirectory
string _workDirectory
Static Private Attributes
const string SOME_TEXT = "Should go to the result"
static readonly string NL = NUnit.Env.NewLine
Constructor & Destructor Documentation
TestContextTests()
NUnit.Framework.Tests.TestContextTests.TestContextTests () inline
References NUnit.Framework.Tests.TestContextTests._name, NUnit.Framework.Tests.TestContextTests._testDirectory, NUnit.Framework.Tests.TestContextTests._workDirectory, NUnit.Framework.TestContext.CurrentContext, NUnit.Framework.TestContext.TestAdapter.Name, NUnit.Framework.TestContext.Test, NUnit.Framework.TestContext.TestDirectory, and NUnit.Framework.TestContext.WorkDirectory.
Member Function Documentation
ConstructorCanAccessTestDirectory()
void NUnit.Framework.Tests.TestContextTests.ConstructorCanAccessTestDirectory () inline
References NUnit.Framework.Tests.TestContextTests._testDirectory, NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
ConstructorAccessWorkDirectory()
void NUnit.Framework.Tests.TestContextTests.ConstructorAccessWorkDirectory () inline
References NUnit.Framework.Tests.TestContextTests._workDirectory, NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
TestCanAccessItsOwnName()
void NUnit.Framework.Tests.TestContextTests.TestCanAccessItsOwnName () inline
References NUnit.Framework.TestContext.CurrentContext, NUnit.Framework.Is.EqualTo(), NUnit.Framework.TestContext.TestAdapter.Name, NUnit.Framework.TestContext.Test, and NUnit.Framework.Assert.That().
ConstructorCanAccessFixtureName()
void NUnit.Framework.Tests.TestContextTests.ConstructorCanAccessFixtureName () inline
References NUnit.Framework.Tests.TestContextTests._name, NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
TestCaseCanAccessItsOwnName()
void NUnit.Framework.Tests.TestContextTests.TestCaseCanAccessItsOwnName (int x) inline
References NUnit.Framework.TestContext.CurrentContext, NUnit.Framework.Is.EqualTo(), NUnit.Framework.TestContext.TestAdapter.Name, NUnit.Framework.TestContext.Test, and NUnit.Framework.Assert.That().
TestCanAccessItsOwnFullName()
void NUnit.Framework.Tests.TestContextTests.TestCanAccessItsOwnFullName () inline
References NUnit.Framework.TestContext.CurrentContext, NUnit.Framework.Is.EqualTo(), NUnit.Framework.TestContext.TestAdapter.FullName, NUnit.Framework.TestContext.Test, and NUnit.Framework.Assert.That().
TestCaseCanAccessItsOwnFullName()
void NUnit.Framework.Tests.TestContextTests.TestCaseCanAccessItsOwnFullName (int x) inline
References NUnit.Framework.TestContext.CurrentContext, NUnit.Framework.Is.EqualTo(), NUnit.Framework.TestContext.TestAdapter.FullName, NUnit.Framework.TestContext.Test, and NUnit.Framework.Assert.That().
TestCanAccessItsOwnMethodName()
void NUnit.Framework.Tests.TestContextTests.TestCanAccessItsOwnMethodName () inline
References NUnit.Framework.TestContext.CurrentContext, NUnit.Framework.Is.EqualTo(), NUnit.Framework.TestContext.TestAdapter.MethodName, NUnit.Framework.TestContext.Test, and NUnit.Framework.Assert.That().
TestCaseCanAccessItsOwnMethodName()
void NUnit.Framework.Tests.TestContextTests.TestCaseCanAccessItsOwnMethodName (int x) inline
References NUnit.Framework.TestContext.CurrentContext, NUnit.Framework.Is.EqualTo(), NUnit.Framework.TestContext.TestAdapter.MethodName, NUnit.Framework.TestContext.Test, and NUnit.Framework.Assert.That().
TestCanAccessItsOwnId()
void NUnit.Framework.Tests.TestContextTests.TestCanAccessItsOwnId () inline
References NUnit.Framework.TestContext.CurrentContext, NUnit.Framework.TestContext.TestAdapter.ID, NUnit.Framework.Is.Not, NUnit.Framework.TestContext.Test, and NUnit.Framework.Assert.That().
TestCanAccessItsOwnProperties()
void NUnit.Framework.Tests.TestContextTests.TestCanAccessItsOwnProperties () inline
References NUnit.Framework.TestContext.CurrentContext, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.TestContext.TestAdapter.Properties, NUnit.Framework.TestContext.Test, and NUnit.Framework.Assert.That().
TestCanAccessWorkDirectory()
void NUnit.Framework.Tests.TestContextTests.TestCanAccessWorkDirectory () inline
References NUnit.Framework.TestContext.CurrentContext, NUnit.Framework.Assert.NotNull(), NUnit.Framework.Assert.That(), and NUnit.Framework.TestContext.WorkDirectory.
TestCanAccessTestState_PassingTest()
void NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_PassingTest () inline
References NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.TestContextData.TestStateRecordingFixture.stateList, and NUnit.Framework.Assert.That().
TestCanAccessTestState_FailureInSetUp()
void NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_FailureInSetUp () inline
References NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.TestContextData.TestStateRecordingFixture.setUpFailure, NUnit.TestData.TestContextData.TestStateRecordingFixture.stateList, and NUnit.Framework.Assert.That().
TestCanAccessTestState_FailingTest()
void NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_FailingTest () inline
References NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.TestContextData.TestStateRecordingFixture.stateList, NUnit.TestData.TestContextData.TestStateRecordingFixture.testFailure, and NUnit.Framework.Assert.That().
TestCanAccessTestState_IgnoredInSetUp()
void NUnit.Framework.Tests.TestContextTests.TestCanAccessTestState_IgnoredInSetUp () inline
References NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.TestContextData.TestStateRecordingFixture.setUpIgnore, NUnit.TestData.TestContextData.TestStateRecordingFixture.stateList, and NUnit.Framework.Assert.That().
TestContextOut_WritesToResult()
void NUnit.Framework.Tests.TestContextTests.TestContextOut_WritesToResult () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Tests.TestContextTests.NL, NUnit.Framework.TestContext.Out, NUnit.Framework.Tests.TestContextTests.SOME_TEXT, and NUnit.Framework.Assert.That().
TestContextWrite_WritesToResult()
void NUnit.Framework.Tests.TestContextTests.TestContextWrite_WritesToResult () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Tests.TestContextTests.SOME_TEXT, NUnit.Framework.Assert.That(), and NUnit.Framework.TestContext.Write().
TestContextWriteLine_WritesToResult()
void NUnit.Framework.Tests.TestContextTests.TestContextWriteLine_WritesToResult () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Tests.TestContextTests.NL, NUnit.Framework.Tests.TestContextTests.SOME_TEXT, NUnit.Framework.Assert.That(), and NUnit.Framework.TestContext.WriteLine().
TestContextStoresFailureInfoForTearDown()
void NUnit.Framework.Tests.TestContextTests.TestContextStoresFailureInfoForTearDown () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), and NUnit.Framework.Assert.That().
TestContextStoresFailureInfoForOneTimeTearDown()
void NUnit.Framework.Tests.TestContextTests.TestContextStoresFailureInfoForOneTimeTearDown () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.Null, NUnit.TestUtilities.TestBuilder.RunTestFixture(), and NUnit.Framework.Assert.That().
Member Data Documentation
_name
string NUnit.Framework.Tests.TestContextTests._name private
Referenced by NUnit.Framework.Tests.TestContextTests.ConstructorCanAccessFixtureName(), and NUnit.Framework.Tests.TestContextTests.TestContextTests().
_testDirectory
string NUnit.Framework.Tests.TestContextTests._testDirectory private
Referenced by NUnit.Framework.Tests.TestContextTests.ConstructorCanAccessTestDirectory(), and NUnit.Framework.Tests.TestContextTests.TestContextTests().
_workDirectory
string NUnit.Framework.Tests.TestContextTests._workDirectory private
Referenced by NUnit.Framework.Tests.TestContextTests.ConstructorAccessWorkDirectory(), and NUnit.Framework.Tests.TestContextTests.TestContextTests().
SOME_TEXT
const string NUnit.Framework.Tests.TestContextTests.SOME_TEXT = "Should go to the result" static private
Referenced by NUnit.Framework.Tests.TestContextTests.TestContextOut_WritesToResult(), NUnit.Framework.Tests.TestContextTests.TestContextWrite_WritesToResult(), and NUnit.Framework.Tests.TestContextTests.TestContextWriteLine_WritesToResult().
NL
readonly string NUnit.Framework.Tests.TestContextTests.NL = NUnit.Env.NewLine static private
Referenced by NUnit.Framework.Tests.TestContextTests.TestContextOut_WritesToResult(), and NUnit.Framework.Tests.TestContextTests.TestContextWriteLine_WritesToResult().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/TestContextTests.cs