Doc: IGLib EXTENDED: NUnit.Engine.Services.ResultService Class Reference
NUnit.Engine.Services.ResultService Class Reference
Public Member Functions
IResultWriter GetResultWriter (string format, object[] args)
Gets a ResultWriter for a given format and set of arguments.
override void StartService ()
Initialize the Service
Public Member Functions inherited from NUnit.Engine.Services.Service
virtual void StopService ()
Do any cleanup needed before terminating the service
void Dispose ()
Properties
string[] Formats [get]
Properties inherited from NUnit.Engine.Services.Service
IServiceLocator ServiceContext [get, set]
The ServiceContext
ServiceStatus Status [get, protected set]
Gets the ServiceStatus of this service
Properties inherited from NUnit.Engine.IService
IServiceLocator ServiceContext [get, set]
The ServiceContext
ServiceStatus Status [get]
Gets the ServiceStatus of this service
Properties inherited from NUnit.Engine.IResultService
string[] Formats [get]
Gets an array of the available formats
Private Attributes
readonly string[] BUILT_IN_FORMATS = new string[] { "nunit3", "cases", "user" }
IEnumerable< ExtensionNode > _extensionNodes
string[] _formats
Additional Inherited Members
Protected Member Functions inherited from NUnit.Engine.Services.Service
virtual void Dispose (bool disposing)
Protected Attributes inherited from NUnit.Engine.Services.Service
bool _disposed = false
Member Function Documentation
GetResultWriter()
IResultWriter NUnit.Engine.Services.ResultService.GetResultWriter (string format, object[] args) inline
Gets a ResultWriter for a given format and set of arguments.
Parameters
format The name of the format to be used
args A set of arguments to be used in constructing the writer or null if non arguments are needed
Returns
An IResultWriter
Implements NUnit.Engine.IResultService.
References NUnit.Engine.Services.ResultService._extensionNodes.
Referenced by NUnit.Engine.Services.Tests.ResultServiceTests.CanGetWriter(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.ConvertEngineResultToXml(), NUnit.Engine.Services.Tests.ResultServiceTests.NUnit3Format_NonExistentTransform_ThrowsArgumentException(), NUnit.Engine.Services.Tests.ResultServiceTests.NUnit3Format_NullArgument_ThrowsArgumentNullException(), and NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.runSchemaValidatorTest().
StartService()
override void NUnit.Engine.Services.ResultService.StartService () inline virtual
Initialize the Service
Reimplemented from NUnit.Engine.Services.Service.
References NUnit.Engine.Services.ResultService._extensionNodes, NUnit.Engine.ServiceContext.GetService(), and NUnit.Engine.Services.Service.Status.
Member Data Documentation
BUILT_IN_FORMATS
readonly string [] NUnit.Engine.Services.ResultService.BUILT_IN_FORMATS = new string[] { "nunit3", "cases", "user" } private
_extensionNodes
IEnumerable<ExtensionNode> NUnit.Engine.Services.ResultService._extensionNodes private
Referenced by NUnit.Engine.Services.ResultService.GetResultWriter(), and NUnit.Engine.Services.ResultService.StartService().
_formats
string [] NUnit.Engine.Services.ResultService._formats private
Property Documentation
Formats
string [] NUnit.Engine.Services.ResultService.Formats get
Referenced by NUnit.Engine.Services.Tests.ResultServiceTests.AvailableFormats().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Services/ResultService.cs