Doc: IGLib EXTENDED: NUnit.Framework.Api.FrameworkController Class Reference
NUnit.Framework.Api.FrameworkController Class Reference
FrameworkController provides a facade for use in loading, browsing and running tests without requiring a reference to the NUnit framework. All calls are encapsulated in constructors for this class and its nested classes, which only require the types of the Common Type System as arguments.
Classes
class CountTestsAction
CountTestsAction counts the number of test cases in the loaded TestSuite held by the FrameworkController.
class ExploreTestsAction
ExploreTestsAction returns info about the tests in an assembly
class FrameworkControllerAction
FrameworkControllerAction is the base class for all actions performed against a FrameworkController.
class LoadTestsAction
LoadTestsAction loads a test into the FrameworkController
class RunAsyncAction
RunAsyncAction initiates an asynchronous test run, returning immediately
class RunTestsAction
RunTestsAction runs the loaded TestSuite held by the FrameworkController.
class StopRunAction
StopRunAction stops an ongoing run.
Public Member Functions
FrameworkController (string assemblyNameOrPath, string idPrefix, IDictionary settings)
Construct a FrameworkController using the default builder and runner.
FrameworkController (Assembly assembly, string idPrefix, IDictionary settings)
Construct a FrameworkController using the default builder and runner.
FrameworkController (string assemblyNameOrPath, string idPrefix, IDictionary settings, string runnerType, string builderType)
Construct a FrameworkController, specifying the types to be used for the runner and builder. This constructor is provided for purposes of development.
FrameworkController (Assembly assembly, string idPrefix, IDictionary settings, string runnerType, string builderType)
Construct a FrameworkController, specifying the types to be used for the runner and builder. This constructor is provided for purposes of development.
Public Member Functions inherited from NUnit.Framework.Compatibility.LongLivedMarshalByRefObject
override object InitializeLifetimeService ()
Obtains a lifetime service object to control the lifetime policy for this instance.
Static Public Member Functions
static TNode InsertEnvironmentElement (TNode targetNode)
Inserts environment element
static TNode InsertSettingsElement (TNode targetNode, IDictionary settings)
Inserts settings element
Properties
ITestAssemblyBuilder Builder [get, private set]
Gets the ITestAssemblyBuilder used by this controller instance.
ITestAssemblyRunner Runner [get, private set]
Gets the ITestAssemblyRunner used by this controller instance.
string AssemblyNameOrPath [get, private set]
Gets the AssemblyName or the path for which this FrameworkController was created
Assembly Assembly [get, private set]
Gets the Assembly for which this
IDictionary Settings [get, private set]
Gets a dictionary of settings for the FrameworkController
Private Member Functions
void Initialize (string assemblyPath, IDictionary settings)
void LoadTests (ICallbackEventHandler handler)
void ExploreTests (ICallbackEventHandler handler, string filter)
void RunTests (ICallbackEventHandler handler, string filter)
void RunAsync (ICallbackEventHandler handler, string filter)
void StopRun (ICallbackEventHandler handler, bool force)
void CountTests (ICallbackEventHandler handler, string filter)
Static Private Member Functions
static string GetProcessorArchitecture ()
static void AddSetting (TNode settingsNode, string name, object value)
Private Attributes
Assembly _testAssembly
Static Private Attributes
const string LOG_FILE_FORMAT = "InternalTrace.{0}.{1}.log"
Detailed Description
FrameworkController provides a facade for use in loading, browsing and running tests without requiring a reference to the NUnit framework. All calls are encapsulated in constructors for this class and its nested classes, which only require the types of the Common Type System as arguments.
The controller supports four actions: Load, Explore, Count and Run. They are intended to be called by a driver, which should allow for proper sequencing of calls. Load must be called before any of the other actions. The driver may support other actions, such as reload on run, by combining these calls.
Constructor & Destructor Documentation
FrameworkController() [1/4]
NUnit.Framework.Api.FrameworkController.FrameworkController (string assemblyNameOrPath, string idPrefix, IDictionary settings) inline
Construct a FrameworkController using the default builder and runner.
Parameters
assemblyNameOrPath The AssemblyName or path to the test assembly
idPrefix A prefix used for all test ids created under this controller.
settings A Dictionary of settings to use in loading and running the tests
References NUnit.Framework.Api.FrameworkController.Builder, NUnit.Framework.Api.FrameworkController.Initialize(), and NUnit.Framework.Api.FrameworkController.Runner.
FrameworkController() [2/4]
NUnit.Framework.Api.FrameworkController.FrameworkController (Assembly assembly, string idPrefix, IDictionary settings) inline
Construct a FrameworkController using the default builder and runner.
Parameters
assembly The test assembly
idPrefix A prefix used for all test ids created under this controller.
settings A Dictionary of settings to use in loading and running the tests
References NUnit.Framework.Api.FrameworkController._testAssembly.
FrameworkController() [3/4]
NUnit.Framework.Api.FrameworkController.FrameworkController (string assemblyNameOrPath, string idPrefix, IDictionary settings, string runnerType, string builderType) inline
Construct a FrameworkController, specifying the types to be used for the runner and builder. This constructor is provided for purposes of development.
Parameters
assemblyNameOrPath The full AssemblyName or the path to the test assembly
idPrefix A prefix used for all test ids created under this controller.
settings A Dictionary of settings to use in loading and running the tests
runnerType The Type of the test runner
builderType The Type of the test builder
References NUnit.Framework.Api.FrameworkController.Builder, NUnit.Framework.Internal.Reflect.Construct(), NUnit.Framework.Api.FrameworkController.Initialize(), and NUnit.Framework.Api.FrameworkController.Runner.
FrameworkController() [4/4]
NUnit.Framework.Api.FrameworkController.FrameworkController (Assembly assembly, string idPrefix, IDictionary settings, string runnerType, string builderType) inline
Construct a FrameworkController, specifying the types to be used for the runner and builder. This constructor is provided for purposes of development.
Parameters
assembly The test assembly
idPrefix A prefix used for all test ids created under this controller.
settings A Dictionary of settings to use in loading and running the tests
runnerType The Type of the test runner
builderType The Type of the test builder
References NUnit.Framework.Api.FrameworkController._testAssembly.
Member Function Documentation
Initialize()
void NUnit.Framework.Api.FrameworkController.Initialize (string assemblyPath, IDictionary settings) inline private
References NUnit.Framework.Api.FrameworkController.AssemblyNameOrPath, NUnit.Env.DefaultWorkDirectory, NUnit.Common.InternalTrace.Initialize(), NUnit.Common.PackageSettings.InternalTraceLevel, NUnit.Common.PackageSettings.InternalTraceWriter, NUnit.Framework.Api.FrameworkController.LOG_FILE_FORMAT, NUnit.Framework.Api.FrameworkController.Settings, and NUnit.Common.PackageSettings.WorkDirectory.
Referenced by NUnit.Framework.Api.FrameworkController.FrameworkController().
LoadTests()
void NUnit.Framework.Api.FrameworkController.LoadTests (ICallbackEventHandler handler) inline private
References NUnit.Framework.Api.FrameworkController._testAssembly, NUnit.Framework.Api.FrameworkController.AssemblyNameOrPath, NUnit.Framework.Api.ITestAssemblyRunner.Load(), NUnit.Framework.Api.ITestAssemblyRunner.LoadedTest, NUnit.Framework.Interfaces.TNode.OuterXml, NUnit.Framework.Api.FrameworkController.Runner, NUnit.Framework.Api.FrameworkController.Settings, and NUnit.Framework.Interfaces.IXmlNodeBuilder.ToXml().
Referenced by NUnit.Framework.Api.FrameworkController.LoadTestsAction.LoadTestsAction().
ExploreTests()
void NUnit.Framework.Api.FrameworkController.ExploreTests (ICallbackEventHandler handler, string filter) inline private
References NUnit.Common.Guard.ArgumentNotNull(), NUnit.Framework.Api.ITestAssemblyRunner.LoadedTest, NUnit.Framework.Interfaces.TNode.OuterXml, NUnit.Framework.Api.FrameworkController.Runner, and NUnit.Framework.Interfaces.IXmlNodeBuilder.ToXml().
Referenced by NUnit.Framework.Api.FrameworkController.ExploreTestsAction.ExploreTestsAction().
RunTests()
void NUnit.Framework.Api.FrameworkController.RunTests (ICallbackEventHandler handler, string filter) inline private
References NUnit.Common.Guard.ArgumentNotNull(), NUnit.Framework.Internal.TestExecutionContext.ClearCurrentContext(), NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Api.FrameworkController.InsertEnvironmentElement(), NUnit.Framework.Api.FrameworkController.InsertSettingsElement(), NUnit.Framework.Interfaces.TNode.OuterXml, NUnit.Framework.Api.ITestAssemblyRunner.Run(), NUnit.Framework.Api.FrameworkController.Runner, NUnit.Framework.Api.FrameworkController.Settings, and NUnit.Framework.Interfaces.IXmlNodeBuilder.ToXml().
Referenced by NUnit.Framework.Api.FrameworkController.RunTestsAction.RunTestsAction().
RunAsync()
void NUnit.Framework.Api.FrameworkController.RunAsync (ICallbackEventHandler handler, string filter) inline private
References NUnit.Common.Guard.ArgumentNotNull(), NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Api.ITestAssemblyRunner.RunAsync(), and NUnit.Framework.Api.FrameworkController.Runner.
Referenced by NUnit.Framework.Api.FrameworkController.RunAsyncAction.RunAsyncAction().
StopRun()
void NUnit.Framework.Api.FrameworkController.StopRun (ICallbackEventHandler handler, bool force) inline private
References NUnit.Framework.Api.FrameworkController.Runner, and NUnit.Framework.Api.ITestAssemblyRunner.StopRun().
Referenced by NUnit.Framework.Api.FrameworkController.StopRunAction.StopRunAction().
CountTests()
void NUnit.Framework.Api.FrameworkController.CountTests (ICallbackEventHandler handler, string filter) inline private
References NUnit.Common.Guard.ArgumentNotNull(), NUnit.Framework.Api.ITestAssemblyRunner.CountTestCases(), NUnit.Framework.Internal.TestFilter.FromXml(), and NUnit.Framework.Api.FrameworkController.Runner.
Referenced by NUnit.Framework.Api.FrameworkController.CountTestsAction.CountTestsAction().
InsertEnvironmentElement()
static TNode NUnit.Framework.Api.FrameworkController.InsertEnvironmentElement (TNode targetNode) inline static
Inserts environment element
Parameters
targetNode Target node
Returns
The new node
Referenced by NUnit.Framework.Api.FrameworkController.RunTests(), and NUnitLite.NUnit3XmlOutputWriter.WriteXmlResultOutput().
GetProcessorArchitecture()
static string NUnit.Framework.Api.FrameworkController.GetProcessorArchitecture () inline static private
InsertSettingsElement()
static TNode NUnit.Framework.Api.FrameworkController.InsertSettingsElement (TNode targetNode, IDictionary settings) inline static
Inserts settings element
Parameters
targetNode Target node
settings Settings dictionary
Returns
The new node
References NUnit.Framework.Api.FrameworkController.AddSetting(), NUnit.Framework.Interfaces.TNode.ChildNodes, and NUnit.Common.PackageSettings.NumberOfTestWorkers.
Referenced by NUnit.Framework.Api.FrameworkController.RunTests(), and NUnitLite.NUnit3XmlOutputWriter.WriteXmlResultOutput().
AddSetting()
static void NUnit.Framework.Api.FrameworkController.AddSetting (TNode settingsNode, string name, object value) inline static private
References NUnit.Framework.Interfaces.TNode.AddAttribute(), and NUnit.Framework.Interfaces.TNode.ChildNodes.
Referenced by NUnit.Framework.Api.FrameworkController.InsertSettingsElement().
Member Data Documentation
LOG_FILE_FORMAT
const string NUnit.Framework.Api.FrameworkController.LOG_FILE_FORMAT = "InternalTrace.{0}.{1}.log" static private
Referenced by NUnit.Framework.Api.FrameworkController.Initialize().
_testAssembly
Assembly NUnit.Framework.Api.FrameworkController._testAssembly private
Referenced by NUnit.Framework.Api.FrameworkController.FrameworkController(), and NUnit.Framework.Api.FrameworkController.LoadTests().
Property Documentation
Builder
ITestAssemblyBuilder NUnit.Framework.Api.FrameworkController.Builder get private set
Gets the ITestAssemblyBuilder used by this controller instance.
The builder.
Referenced by NUnit.Framework.Api.FrameworkControllerTests.ConstructController(), and NUnit.Framework.Api.FrameworkController.FrameworkController().
Runner
ITestAssemblyRunner NUnit.Framework.Api.FrameworkController.Runner get private set
Gets the ITestAssemblyRunner used by this controller instance.
The runner.
Referenced by NUnit.Framework.Api.FrameworkControllerTests.ConstructController(), NUnit.Framework.Api.FrameworkController.CountTests(), NUnit.Framework.Api.FrameworkController.ExploreTests(), NUnit.Framework.Api.FrameworkController.FrameworkController(), NUnit.Framework.Api.FrameworkController.LoadTests(), NUnit.Framework.Api.FrameworkController.RunAsync(), NUnit.Framework.Api.FrameworkController.RunTests(), and NUnit.Framework.Api.FrameworkController.StopRun().
AssemblyNameOrPath
string NUnit.Framework.Api.FrameworkController.AssemblyNameOrPath get private set
Gets the AssemblyName or the path for which this FrameworkController was created
Referenced by NUnit.Framework.Api.FrameworkControllerTests.ConstructController(), NUnit.Framework.Api.FrameworkController.Initialize(), and NUnit.Framework.Api.FrameworkController.LoadTests().
Assembly
Assembly NUnit.Framework.Api.FrameworkController.Assembly get private set
Gets the Assembly for which this
Settings
IDictionary NUnit.Framework.Api.FrameworkController.Settings get private set
Gets a dictionary of settings for the FrameworkController
Referenced by NUnit.Framework.Api.FrameworkControllerTests.ConstructController(), NUnit.Framework.Api.FrameworkController.Initialize(), NUnit.Framework.Api.FrameworkController.LoadTests(), and NUnit.Framework.Api.FrameworkController.RunTests().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Api/FrameworkController.cs