Doc: IGLib EXTENDED: NUnit.Engine.Internal.SettingsStore Class Reference
NUnit.Engine.Internal.SettingsStore Class Reference
SettingsStore extends SettingsGroup to provide for loading and saving the settings from an XML file.
Public Member Functions
SettingsStore ()
Construct a SettingsStore without a backing file - used for testing.
SettingsStore (string settingsFile, bool writeable)
Construct a SettingsStore with a file name and indicate whether it is writeable
void LoadSettings ()
void SaveSettings ()
Public Member Functions inherited from NUnit.Engine.Internal.SettingsGroup
object GetSetting (string settingName)
Load the value of one of the group's settings
T GetSetting< T > (string settingName, T defaultValue)
Load the value of one of the group's settings or return a default value
void RemoveSetting (string settingName)
Remove a setting from the group
void RemoveGroup (string groupName)
Remove a group of settings
void SaveSetting (string settingName, object settingValue)
Save the value of one of the group's settings
Private Attributes
string _settingsFile
bool _writeable
Additional Inherited Members
Protected Attributes inherited from NUnit.Engine.Internal.SettingsGroup
Dictionary< string, object > _settings = new Dictionary<string, object>()
Events inherited from NUnit.Engine.Internal.SettingsGroup
SettingsEventHandler Changed
Events inherited from NUnit.Engine.ISettings
SettingsEventHandler Changed
Occurs when the settings are changed.
Detailed Description
SettingsStore extends SettingsGroup to provide for loading and saving the settings from an XML file.
Constructor & Destructor Documentation
SettingsStore() [1/2]
NUnit.Engine.Internal.SettingsStore.SettingsStore () inline
Construct a SettingsStore without a backing file - used for testing.
SettingsStore() [2/2]
NUnit.Engine.Internal.SettingsStore.SettingsStore (string settingsFile, bool writeable) inline
Construct a SettingsStore with a file name and indicate whether it is writeable
Parameters
settingsFile
writeable
References NUnit.Engine.Internal.SettingsStore._settingsFile, and NUnit.Engine.Internal.SettingsStore._writeable.
Member Function Documentation
LoadSettings()
void NUnit.Engine.Internal.SettingsStore.LoadSettings () inline
References NUnit.Engine.Internal.SettingsStore._settingsFile, and NUnit.Engine.Internal.SettingsGroup.SaveSetting().
Referenced by NUnit.Engine.Services.SettingsService.StartService().
SaveSettings()
void NUnit.Engine.Internal.SettingsStore.SaveSettings () inline
References NUnit.Engine.Internal.SettingsGroup._settings, NUnit.Engine.Internal.SettingsStore._settingsFile, NUnit.Engine.Internal.SettingsStore._writeable, and NUnit.Engine.Internal.SettingsGroup.GetSetting().
Referenced by NUnit.Engine.Services.SettingsService.StopService().
Member Data Documentation
_settingsFile
string NUnit.Engine.Internal.SettingsStore._settingsFile private
Referenced by NUnit.Engine.Internal.SettingsStore.LoadSettings(), NUnit.Engine.Internal.SettingsStore.SaveSettings(), and NUnit.Engine.Internal.SettingsStore.SettingsStore().
_writeable
bool NUnit.Engine.Internal.SettingsStore._writeable private
Referenced by NUnit.Engine.Internal.SettingsStore.SaveSettings(), and NUnit.Engine.Internal.SettingsStore.SettingsStore().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Internal/SettingsStore.cs