Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAED2 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAED2 Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAED2 (IDAMAX idamax, DLAMCH dlamch, DLAPY2 dlapy2, DCOPY dcopy, DLACPY dlacpy, DLAMRG dlamrg, DROT drot, DSCAL dscal, XERBLA xerbla)
DLAED2 ()
void Run (ref int K, int N, int N1, ref double[] D, int offset_d, ref double[] Q, int offset_q, int LDQ, ref int[] INDXQ, int offset_indxq, ref double RHO, ref double[] Z, int offset_z, ref double[] DLAMDA, int offset_dlamda, ref double[] W, int offset_w, ref double[] Q2, int offset_q2, ref int[] INDX, int offset_indx, ref int[] INDXC, int offset_indxc, ref int[] INDXP, int offset_indxp, ref int[] COLTYP, int offset_coltyp, ref int INFO)
Private Attributes
IDAMAX _idamax
DLAMCH _dlamch
DLAPY2 _dlapy2
DCOPY _dcopy
DLACPY _dlacpy
DLAMRG _dlamrg
DROT _drot
DSCAL _dscal
XERBLA _xerbla
int[] CTOT = new int[4]
int[] PSM = new int[4]
Static Private Attributes
const double MONE = - 1.0E0
const double ZERO = 0.0E0
const double ONE = 1.0E0
const double TWO = 2.0E0
const double EIGHT = 8.0E0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAED2 merges the two sets of eigenvalues together into a single sorted set. Then it tries to deflate the size of the problem. There are two ways in which deflation can occur: when two or more eigenvalues are close together or if there is a tiny entry in the Z vector. For each such occurrence the order of the related secular equation problem is reduced by one.
/summary>
Constructor & Destructor Documentation
DLAED2() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAED2.DLAED2 (IDAMAX idamax, DLAMCH dlamch, DLAPY2 dlapy2, DCOPY dcopy, DLACPY dlacpy, DLAMRG dlamrg, DROT drot, DSCAL dscal, XERBLA xerbla) inline
DLAED2() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAED2.DLAED2 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAED2.Run (ref int K, int N, int N1, ref double[] D, int offset_d, ref double[] Q, int offset_q, int LDQ, ref int[] INDXQ, int offset_indxq, ref double RHO, ref double[] Z, int offset_z, ref double[] DLAMDA, int offset_dlamda, ref double[] W, int offset_w, ref double[] Q2, int offset_q2, ref int[] INDX, int offset_indx, ref int[] INDXC, int offset_indxc, ref int[] INDXP, int offset_indxp, ref int[] COLTYP, int offset_coltyp, ref int INFO) inline
Purpose
DLAED2 merges the two sets of eigenvalues together into a single sorted set. Then it tries to deflate the size of the problem. There are two ways in which deflation can occur: when two or more eigenvalues are close together or if there is a tiny entry in the Z vector. For each such occurrence the order of the related secular equation problem is reduced by one.
/summary>
Parameters
K (output) INTEGER The number of non-deflated eigenvalues, and the order of the related secular equation. 0 .LE. K .LE.N. /param>
Parameters
N (input) INTEGER The dimension of the symmetric tridiagonal matrix. N .GE. 0. /param>
Parameters
N1 (input) INTEGER The location of the last eigenvalue in the leading sub-matrix. min(1,N) .LE. N1 .LE. N/2. /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension (N) On entry, D contains the eigenvalues of the two submatrices to be combined. On exit, D contains the trailing (N-K) updated eigenvalues (those which were deflated) sorted into increasing order. /param>
Parameters
Q (input/output) DOUBLE PRECISION array, dimension (LDQ, N) On entry, Q contains the eigenvectors of two submatrices in the two square blocks with corners at (1,1), (N1,N1) and (N1+1, N1+1), (N,N). On exit, Q contains the trailing (N-K) updated eigenvectors (those which were deflated) in its last N-K columns. /param>
Parameters
LDQ (input) INTEGER The leading dimension of the array Q. LDQ .GE. max(1,N). /param>
Parameters
INDXQ (input/output) INTEGER array, dimension (N) The permutation which separately sorts the two sub-problems in D into ascending order. Note that elements in the second half of this permutation must first have N1 added to their values. Destroyed on exit. /param>
Parameters
RHO (input/output) DOUBLE PRECISION On entry, the off-diagonal element associated with the rank-1 cut which originally split the two submatrices which are now being recombined. On exit, RHO has been modified to the value required by DLAED3. /param>
Parameters
Z (input) DOUBLE PRECISION array, dimension (N) On entry, Z contains the updating vector (the last row of the first sub-eigenvector matrix and the first row of the second sub-eigenvector matrix). On exit, the contents of Z have been destroyed by the updating process. /param>
Parameters
DLAMDA (output) DOUBLE PRECISION array, dimension (N) A copy of the first K eigenvalues which will be used by DLAED3 to form the secular equation. /param>
Parameters
W (output) DOUBLE PRECISION array, dimension (N) The first k values of the final deflation-altered z-vector which will be passed to DLAED3. /param>
Parameters
Q2 (output) DOUBLE PRECISION array, dimension (N1**2+(N-N1)**2) A copy of the first K eigenvectors which will be used by DLAED3 in a matrix multiply (DGEMM) to solve for the new eigenvectors. /param>
Parameters
INDX (workspace) INTEGER array, dimension (N) The permutation used to sort the contents of DLAMDA into ascending order. /param>
Parameters
INDXC (output) INTEGER array, dimension (N) The permutation used to arrange the columns of the deflated Q matrix into three groups: the first group contains non-zero elements only at and above N1, the second contains non-zero elements only below N1, and the third is dense. /param>
Parameters
INDXP (workspace) INTEGER array, dimension (N) The permutation used to place deflated values of D at the end of the array. INDXP(1:K) points to the nondeflated D-values and INDXP(K+1:N) points to the deflated eigenvalues. /param>
Parameters
COLTYP (workspace/output) INTEGER array, dimension (N) During execution, a label which will indicate which of the following types a column in the Q2 matrix is: 1 : non-zero in the upper half only; 2 : dense; 3 : non-zero in the lower half only; 4 : deflated. On exit, COLTYP(i) is the number of columns of type i, for i=1 to 4 only. /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLAED2.CTOT, DotNumerics.LinearAlgebra.CSLapack.DLAED2.EIGHT, DotNumerics.LinearAlgebra.CSLapack.DLAED2.MONE, DotNumerics.LinearAlgebra.CSLapack.DLAED2.ONE, DotNumerics.LinearAlgebra.CSLapack.DLAED2.PSM, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DROT.Run(), DotNumerics.LinearAlgebra.CSLapack.IDAMAX.Run(), DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAPY2.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMRG.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED2.TWO, and DotNumerics.LinearAlgebra.CSLapack.DLAED2.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED1.Run().
Member Data Documentation
_idamax
IDAMAX DotNumerics.LinearAlgebra.CSLapack.DLAED2._idamax private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLAED2._dlamch private
_dlapy2
DLAPY2 DotNumerics.LinearAlgebra.CSLapack.DLAED2._dlapy2 private
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLAED2._dcopy private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DLAED2._dlacpy private
_dlamrg
DLAMRG DotNumerics.LinearAlgebra.CSLapack.DLAED2._dlamrg private
_drot
DROT DotNumerics.LinearAlgebra.CSLapack.DLAED2._drot private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DLAED2._dscal private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLAED2._xerbla private
MONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAED2.MONE = - 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED2.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAED2.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED2.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAED2.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED2.Run().
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DLAED2.TWO = 2.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED2.Run().
EIGHT
const double DotNumerics.LinearAlgebra.CSLapack.DLAED2.EIGHT = 8.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED2.Run().
CTOT
int [] DotNumerics.LinearAlgebra.CSLapack.DLAED2.CTOT = new int[4] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED2.Run().
PSM
int [] DotNumerics.LinearAlgebra.CSLapack.DLAED2.PSM = new int[4] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED2.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlaed2.cs