Doc: IGLib EXTENDED: AForge.Imaging.Formats.PNMCodec Class Reference
AForge.Imaging.Formats.PNMCodec Class Reference
PNM image format decoder.
Public Member Functions
Bitmap DecodeSingleFrame (Stream stream)
Decode first frame of PNM image.
int Open (Stream stream)
Open specified stream.
Bitmap DecodeFrame (int frameIndex, out ImageInfo imageInfo)
Decode specified frame.
void Close ()
Close decoding of previously opened stream.
Private Member Functions
PNMImageInfo ReadHeader (Stream stream)
Bitmap ReadImageFrame (Stream stream, PNMImageInfo imageInfo)
unsafe Bitmap ReadP5Image (Stream stream, int width, int height, int maxValue)
unsafe Bitmap ReadP6Image (Stream stream, int width, int height, int maxValue)
int ReadIntegerValue (Stream stream)
byte SkipSpaces (Stream stream)
int ReadUntilSpace (Stream stream, byte[] buffer, int start)
Private Attributes
Stream stream = null
PNMImageInfo imageInfo = null
long dataPosition = 0
Detailed Description
PNM image format decoder.
The PNM (an acronym derived from "Portable Any Map") format is an abstraction of the PBM, PGM and PPM formats. I.e. the name "PNM" refers collectively to PBM (binary images), PGM (grayscale images) and PPM (color image) image formats.
Image in PNM format can be found in different scientific databases and laboratories, for example Yale Face Database and AT&T Face Database.
<note>Only PNM images of P5 (binary encoded PGM) and P6 (binary encoded PPM) formats are supported at this point.</note>
<note>The maximum supported pixel value is 255 at this point.</note>
<note>The class supports only one-frame PNM images. As it is specified in format specification, the multi-frame PNM images has appeared starting from 2000.</note>
Member Function Documentation
DecodeSingleFrame()
Bitmap AForge.Imaging.Formats.PNMCodec.DecodeSingleFrame (Stream stream) inline
Decode first frame of PNM image.
Parameters
stream Source stream, which contains encoded image.
Returns
Returns decoded image frame.
Exceptions
FormatException Not a PNM image format.
NotSupportedException Format of the PNM image is not supported.
ArgumentException The stream contains invalid (broken) PNM image.
Implements AForge.Imaging.Formats.IImageDecoder.
References AForge.Imaging.Formats.PNMCodec.imageInfo, AForge.Imaging.Formats.PNMCodec.ReadHeader(), AForge.Imaging.Formats.PNMCodec.ReadImageFrame(), and AForge.Imaging.Formats.PNMCodec.stream.
Open()
int AForge.Imaging.Formats.PNMCodec.Open (Stream stream) inline
Open specified stream.
Parameters
stream Stream to open.
Returns
Returns number of images found in the specified stream.
Exceptions
FormatException Not a PNM image format.
NotSupportedException Format of the PNM image is not supported.
ArgumentException The stream contains invalid (broken) PNM image.
Implements AForge.Imaging.Formats.IImageDecoder.
References AForge.Imaging.Formats.PNMCodec.Close(), AForge.Imaging.Formats.PNMCodec.imageInfo, AForge.Imaging.Formats.PNMCodec.ReadHeader(), AForge.Imaging.Formats.PNMCodec.stream, and AForge.Imaging.Formats.ImageInfo.TotalFrames.
DecodeFrame()
Bitmap AForge.Imaging.Formats.PNMCodec.DecodeFrame (int frameIndex, out ImageInfo imageInfo) inline
Decode specified frame.
Parameters
frameIndex Image frame to decode.
imageInfo Receives information about decoded frame.
Returns
Returns decoded frame.
Exceptions
NullReferenceException No image stream was opened previously.
ArgumentOutOfRangeException Stream does not contain frame with specified index.
ArgumentException The stream contains invalid (broken) PNM image.
Implements AForge.Imaging.Formats.IImageDecoder.
References AForge.Imaging.Formats.PNMImageInfo.Clone(), AForge.Imaging.Formats.PNMCodec.dataPosition, AForge.Imaging.Formats.PNMCodec.imageInfo, AForge.Imaging.Formats.PNMCodec.ReadImageFrame(), and AForge.Imaging.Formats.PNMCodec.stream.
Close()
void AForge.Imaging.Formats.PNMCodec.Close () inline
Close decoding of previously opened stream.
The method does not close stream itself, but just closes decoding cleaning all associated data with it.
Implements AForge.Imaging.Formats.IImageDecoder.
References AForge.Imaging.Formats.PNMCodec.imageInfo, and AForge.Imaging.Formats.PNMCodec.stream.
Referenced by AForge.Imaging.Formats.PNMCodec.Open().
ReadHeader()
PNMImageInfo AForge.Imaging.Formats.PNMCodec.ReadHeader (Stream stream) inline private
References AForge.Imaging.Formats.PNMCodec.imageInfo, AForge.Imaging.Formats.PNMImageInfo.MaxDataValue, AForge.Imaging.Formats.PNMCodec.ReadIntegerValue(), AForge.Imaging.Formats.PNMCodec.stream, and AForge.Imaging.Formats.PNMImageInfo.Version.
Referenced by AForge.Imaging.Formats.PNMCodec.DecodeSingleFrame(), and AForge.Imaging.Formats.PNMCodec.Open().
ReadImageFrame()
Bitmap AForge.Imaging.Formats.PNMCodec.ReadImageFrame (Stream stream, PNMImageInfo imageInfo) inline private
References AForge.Imaging.Formats.ImageInfo.Height, AForge.Imaging.Formats.PNMCodec.imageInfo, AForge.Imaging.Formats.PNMImageInfo.MaxDataValue, AForge.Imaging.Formats.PNMCodec.ReadP5Image(), AForge.Imaging.Formats.PNMCodec.ReadP6Image(), AForge.Imaging.Formats.PNMCodec.stream, AForge.Imaging.Formats.PNMImageInfo.Version, and AForge.Imaging.Formats.ImageInfo.Width.
Referenced by AForge.Imaging.Formats.PNMCodec.DecodeFrame(), and AForge.Imaging.Formats.PNMCodec.DecodeSingleFrame().
ReadP5Image()
unsafe Bitmap AForge.Imaging.Formats.PNMCodec.ReadP5Image (Stream stream, int width, int height, int maxValue) inline private
References AForge.Math.Geometry.Rectangle, and AForge.Imaging.Formats.PNMCodec.stream.
Referenced by AForge.Imaging.Formats.PNMCodec.ReadImageFrame().
ReadP6Image()
unsafe Bitmap AForge.Imaging.Formats.PNMCodec.ReadP6Image (Stream stream, int width, int height, int maxValue) inline private
References AForge.Math.Geometry.Rectangle, and AForge.Imaging.Formats.PNMCodec.stream.
Referenced by AForge.Imaging.Formats.PNMCodec.ReadImageFrame().
ReadIntegerValue()
int AForge.Imaging.Formats.PNMCodec.ReadIntegerValue (Stream stream) inline private
References AForge.Imaging.Formats.PNMCodec.ReadUntilSpace(), AForge.Imaging.Formats.PNMCodec.SkipSpaces(), and AForge.Imaging.Formats.PNMCodec.stream.
Referenced by AForge.Imaging.Formats.PNMCodec.ReadHeader().
SkipSpaces()
byte AForge.Imaging.Formats.PNMCodec.SkipSpaces (Stream stream) inline private
References AForge.Imaging.Formats.PNMCodec.stream.
Referenced by AForge.Imaging.Formats.PNMCodec.ReadIntegerValue().
ReadUntilSpace()
int AForge.Imaging.Formats.PNMCodec.ReadUntilSpace (Stream stream, byte[] buffer, int start) inline private
References AForge.Imaging.Formats.PNMCodec.stream.
Referenced by AForge.Imaging.Formats.PNMCodec.ReadIntegerValue().
Member Data Documentation
stream
Stream AForge.Imaging.Formats.PNMCodec.stream = null private
Referenced by AForge.Imaging.Formats.PNMCodec.Close(), AForge.Imaging.Formats.PNMCodec.DecodeFrame(), AForge.Imaging.Formats.PNMCodec.DecodeSingleFrame(), AForge.Imaging.Formats.PNMCodec.Open(), AForge.Imaging.Formats.PNMCodec.ReadHeader(), AForge.Imaging.Formats.PNMCodec.ReadImageFrame(), AForge.Imaging.Formats.PNMCodec.ReadIntegerValue(), AForge.Imaging.Formats.PNMCodec.ReadP5Image(), AForge.Imaging.Formats.PNMCodec.ReadP6Image(), AForge.Imaging.Formats.PNMCodec.ReadUntilSpace(), and AForge.Imaging.Formats.PNMCodec.SkipSpaces().
imageInfo
PNMImageInfo AForge.Imaging.Formats.PNMCodec.imageInfo = null private
Referenced by AForge.Imaging.Formats.PNMCodec.Close(), AForge.Imaging.Formats.PNMCodec.DecodeFrame(), AForge.Imaging.Formats.PNMCodec.DecodeSingleFrame(), AForge.Imaging.Formats.PNMCodec.Open(), AForge.Imaging.Formats.PNMCodec.ReadHeader(), and AForge.Imaging.Formats.PNMCodec.ReadImageFrame().
dataPosition
long AForge.Imaging.Formats.PNMCodec.dataPosition = 0 private
Referenced by AForge.Imaging.Formats.PNMCodec.DecodeFrame().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging.Formats/PNMCodec.cs