Doc: IGLib EXTENDED: AForge.Imaging.ColorReduction.IColorQuantizer Interface Reference
AForge.Imaging.ColorReduction.IColorQuantizer Interface Reference
Interface which is implemented by different color quantization algorithms.
Public Member Functions
void AddColor (Color color)
Process color by a color quantization algorithm.
Color[] GetPalette (int colorCount)
Get palette of the specified size.
void Clear ()
Clear internals of the algorithm, like accumulated color table, etc.
Detailed Description
Interface which is implemented by different color quantization algorithms.
The interface defines set of methods, which are to be implemented by different color quantization algorithms - algorithms which are aimed to provide reduced color table/palette for a color image.
See documentation to particular implementation of the interface for additional information about the algorithm.
Member Function Documentation
AddColor()
void AForge.Imaging.ColorReduction.IColorQuantizer.AddColor (Color color)
Process color by a color quantization algorithm.
Parameters
color Color to process.
Depending on particular implementation of IColorQuantizer interface, this method may simply process the specified color or store it in internal list for later color palette calculation.
Implemented in AForge.Imaging.ColorReduction.MedianCutQuantizer.
Referenced by AForge.Imaging.ColorReduction.ColorImageQuantizer.CalculatePalette().
GetPalette()
Color [] AForge.Imaging.ColorReduction.IColorQuantizer.GetPalette (int colorCount)
Get palette of the specified size.
Parameters
colorCount Palette size to return.
Returns
Returns reduced color palette for the accumulated/processed colors.
The method must be called after continuously calling AddColor method and returns reduced color palette for colors accumulated/processed so far.
Implemented in AForge.Imaging.ColorReduction.MedianCutQuantizer.
Referenced by AForge.Imaging.ColorReduction.ColorImageQuantizer.CalculatePalette().
Clear()
void AForge.Imaging.ColorReduction.IColorQuantizer.Clear ()
Clear internals of the algorithm, like accumulated color table, etc.
The methods resets internal state of a color quantization algorithm returning it to initial state.
Implemented in AForge.Imaging.ColorReduction.MedianCutQuantizer.
Referenced by AForge.Imaging.ColorReduction.ColorImageQuantizer.CalculatePalette().
The documentation for this interface was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Color Reduction/IColorQuantizer.cs