Doc: IGLib EXTENDED: NUnit.ConsoleRunner.Tests.DefaultOptionsProviderTests Class Reference
NUnit.ConsoleRunner.Tests.DefaultOptionsProviderTests Class Reference
Public Member Functions
void TearDown ()
void ShouldRetTeamCityAsTrueWhenHasEnvironmentVariable_TEAMCITY_PROJECT_NAME ()
void ShouldRetTeamCityAsFalseWhenHasNotEnvironmentVariable_TEAMCITY_PROJECT_NAME ()
Static Private Member Functions
static DefaultOptionsProvider CreateInstance ()
Static Private Attributes
const string EnvironmentVariableTeamcityProjectName = "TEAMCITY_PROJECT_NAME"
Member Function Documentation
TearDown()
void NUnit.ConsoleRunner.Tests.DefaultOptionsProviderTests.TearDown () inline
References NUnit.ConsoleRunner.Tests.DefaultOptionsProviderTests.EnvironmentVariableTeamcityProjectName.
ShouldRetTeamCityAsTrueWhenHasEnvironmentVariable_TEAMCITY_PROJECT_NAME()
void NUnit.ConsoleRunner.Tests.DefaultOptionsProviderTests.ShouldRetTeamCityAsTrueWhenHasEnvironmentVariable_TEAMCITY_PROJECT_NAME () inline
References NUnit.ConsoleRunner.Tests.DefaultOptionsProviderTests.CreateInstance(), NUnit.ConsoleRunner.Tests.DefaultOptionsProviderTests.EnvironmentVariableTeamcityProjectName, and NUnit.Framework.Assert.True().
ShouldRetTeamCityAsFalseWhenHasNotEnvironmentVariable_TEAMCITY_PROJECT_NAME()
void NUnit.ConsoleRunner.Tests.DefaultOptionsProviderTests.ShouldRetTeamCityAsFalseWhenHasNotEnvironmentVariable_TEAMCITY_PROJECT_NAME () inline
References NUnit.ConsoleRunner.Tests.DefaultOptionsProviderTests.CreateInstance(), NUnit.ConsoleRunner.Tests.DefaultOptionsProviderTests.EnvironmentVariableTeamcityProjectName, and NUnit.Framework.Assert.False().
CreateInstance()
static DefaultOptionsProvider NUnit.ConsoleRunner.Tests.DefaultOptionsProviderTests.CreateInstance () inline static private
Referenced by NUnit.ConsoleRunner.Tests.DefaultOptionsProviderTests.ShouldRetTeamCityAsFalseWhenHasNotEnvironmentVariable_TEAMCITY_PROJECT_NAME(), and NUnit.ConsoleRunner.Tests.DefaultOptionsProviderTests.ShouldRetTeamCityAsTrueWhenHasEnvironmentVariable_TEAMCITY_PROJECT_NAME().
Member Data Documentation
EnvironmentVariableTeamcityProjectName
const string NUnit.ConsoleRunner.Tests.DefaultOptionsProviderTests.EnvironmentVariableTeamcityProjectName = "TEAMCITY_PROJECT_NAME" static private
Referenced by NUnit.ConsoleRunner.Tests.DefaultOptionsProviderTests.ShouldRetTeamCityAsFalseWhenHasNotEnvironmentVariable_TEAMCITY_PROJECT_NAME(), NUnit.ConsoleRunner.Tests.DefaultOptionsProviderTests.ShouldRetTeamCityAsTrueWhenHasEnvironmentVariable_TEAMCITY_PROJECT_NAME(), and NUnit.ConsoleRunner.Tests.DefaultOptionsProviderTests.TearDown().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/tests/DefaultOptionsProviderTests.cs