Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLARF Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLARF Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLARF (DGEMV dgemv, DGER dger, LSAME lsame)
DLARF ()
void Run (string SIDE, int M, int N, double[] V, int offset_v, int INCV, double TAU, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work)
Private Attributes
DGEMV _dgemv
DGER _dger
LSAME _lsame
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLARF applies a real elementary reflector H to a real m by n matrix C, from either the left or the right. H is represented in the form
H = I - tau * v * v'
where tau is a real scalar and v is a real vector.
If tau = 0, then H is taken to be the unit matrix.
/summary>
Constructor & Destructor Documentation
DLARF() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLARF.DLARF (DGEMV dgemv, DGER dger, LSAME lsame) inline
DLARF() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLARF.DLARF () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLARF.Run (string SIDE, int M, int N, double[] V, int offset_v, int INCV, double TAU, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work) inline
Purpose
DLARF applies a real elementary reflector H to a real m by n matrix C, from either the left or the right. H is represented in the form
H = I - tau * v * v'
where tau is a real scalar and v is a real vector.
If tau = 0, then H is taken to be the unit matrix.
/summary>
Parameters
SIDE (input) CHARACTER*1 = 'L': form H * C = 'R': form C * H /param>
Parameters
M (input) INTEGER The number of rows of the matrix C. /param>
Parameters
N (input) INTEGER The number of columns of the matrix C. /param>
Parameters
V (input) DOUBLE PRECISION array, dimension (1 + (M-1)*abs(INCV)) if SIDE = 'L' or (1 + (N-1)*abs(INCV)) if SIDE = 'R' The vector v in the representation of H. V is not used if TAU = 0. /param>
Parameters
INCV (input) INTEGER The increment between elements of v. INCV .LT..GT. 0. /param>
Parameters
TAU (input) DOUBLE PRECISION The value tau in the representation of H. /param>
Parameters
C (input/output) DOUBLE PRECISION array, dimension (LDC,N) On entry, the m by n matrix C. On exit, C is overwritten by the matrix H * C if SIDE = 'L', or C * H if SIDE = 'R'. /param>
Parameters
LDC (input) INTEGER The leading dimension of the array C. LDC .GE. max(1,M). /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (N) if SIDE = 'L' or (M) if SIDE = 'R' /param>
References DotNumerics.LinearAlgebra.CSLapack.DLARF.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.DGER.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLARF.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGELQ2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGERQ2.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGL2.Run(), DotNumerics.LinearAlgebra.CSLapack.DORG2L.Run(), DotNumerics.LinearAlgebra.CSLapack.DORG2R.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEHD2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQPF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQP2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBD2.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DORM2L.Run(), DotNumerics.LinearAlgebra.CSLapack.DORML2.Run(), DotNumerics.LinearAlgebra.CSLapack.DORM2R.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR2.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAQR3.Run().
Member Data Documentation
_dgemv
DGEMV DotNumerics.LinearAlgebra.CSLapack.DLARF._dgemv private
_dger
DGER DotNumerics.LinearAlgebra.CSLapack.DLARF._dger private
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLARF._lsame private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLARF.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLARF.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLARF.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLARF.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlarf.cs