Doc: IGLib EXTENDED: AForge.Controls.SliderControl Class Reference
AForge.Controls.SliderControl Class Reference
Slider control.
Public Member Functions
delegate void PositionChangedHandler (object sender, float position)
Delegate used for notification about manipulator's position changes.
SliderControl ()
Initializes a new instance of the SliderControl class.
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
bool ResetPositionOnMouseRelease [get, set]
Determines behaviour of manipulator, when mouse button is released.
Color BorderColor [get, set]
Color used for drawing borders.
Color PositiveAreaBrush [get, set]
Background color used for filling area corresponding to positive values.
Color NegativeAreaBrush [get, set]
Background color used for filling area corresponding to negative values.
Color ManipulatorColor [get, set]
Color used for filling manipulator.
bool IsHorizontal [get, set]
Defines if control has horizontal or vertical look.
float ManipulatorPosition [get, set]
Current manipulator's position, [-1, 1].
Events
PositionChangedHandler PositionChanged
Event used for notification about manipulator's position changes.
Private Member Functions
void TurnControl_Paint (object sender, PaintEventArgs e)
void TurnControl_MouseDown (object sender, MouseEventArgs e)
void TurnControl_MouseUp (object sender, MouseEventArgs e)
void TurnControl_MouseMove (object sender, MouseEventArgs e)
void timer_Tick (object sender, EventArgs e)
void NotifyClients ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
bool isHorizontal = true
bool resetPositionOnMouseRelease = true
Pen borderPen = new Pen(Color.Black)
SolidBrush positiveAreaBrush = new SolidBrush(Color.White)
SolidBrush negativeAreaBrush = new SolidBrush(Color.LightGray)
SolidBrush manipulatorBrush = new SolidBrush(Color.LightSeaGreen)
SolidBrush disabledBrash = new SolidBrush(Color.FromArgb(240, 240, 240))
int leftMargin
int topMargin
float manipulatatorPosition = 0
bool tracking = false
int ticksBeforeNotificiation = -1
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Timer timer
Static Private Attributes
const int manipulatorWidth = 11
const int manipulatorHeight = 20
Detailed Description
Slider control.
The control represents a slider, which can be dragged in the [-1, 1] range. Default position of the slider is set 0, which corresponds to center of the control.
Constructor & Destructor Documentation
SliderControl()
AForge.Controls.SliderControl.SliderControl () inline
Initializes a new instance of the SliderControl class.
References AForge.Controls.SliderControl.InitializeComponent(), and AForge.Controls.SliderControl.IsHorizontal.
Member Function Documentation
PositionChangedHandler()
delegate void AForge.Controls.SliderControl.PositionChangedHandler (object sender, float position)
Delegate used for notification about manipulator's position changes.
Parameters
sender Event sender - object sending the event.
position Current position of manipulator.
Referenced by SRVTest.MainForm.InitializeComponent(), and SVSTest.MainForm.InitializeComponent().
TurnControl_Paint()
void AForge.Controls.SliderControl.TurnControl_Paint (object sender, PaintEventArgs e) inline private
References AForge.Controls.SliderControl.borderPen, AForge.Controls.SliderControl.disabledBrash, AForge.Controls.SliderControl.isHorizontal, AForge.Controls.SliderControl.leftMargin, AForge.Controls.SliderControl.manipulatatorPosition, AForge.Controls.SliderControl.manipulatorBrush, AForge.Controls.SliderControl.manipulatorHeight, AForge.Controls.SliderControl.manipulatorWidth, AForge.Controls.SliderControl.negativeAreaBrush, AForge.Controls.SliderControl.positiveAreaBrush, and AForge.Controls.SliderControl.topMargin.
Referenced by AForge.Controls.SliderControl.InitializeComponent().
TurnControl_MouseDown()
void AForge.Controls.SliderControl.TurnControl_MouseDown (object sender, MouseEventArgs e) inline private
References AForge.Controls.SliderControl.isHorizontal, AForge.Controls.SliderControl.leftMargin, AForge.Controls.SliderControl.manipulatatorPosition, AForge.Controls.SliderControl.NotifyClients(), AForge.Controls.SliderControl.ticksBeforeNotificiation, AForge.Controls.SliderControl.timer, AForge.Controls.SliderControl.topMargin, and AForge.Controls.SliderControl.tracking.
Referenced by AForge.Controls.SliderControl.InitializeComponent().
TurnControl_MouseUp()
void AForge.Controls.SliderControl.TurnControl_MouseUp (object sender, MouseEventArgs e) inline private
References AForge.Controls.SliderControl.manipulatatorPosition, AForge.Controls.SliderControl.NotifyClients(), AForge.Controls.SliderControl.resetPositionOnMouseRelease, AForge.Controls.SliderControl.timer, and AForge.Controls.SliderControl.tracking.
Referenced by AForge.Controls.SliderControl.InitializeComponent().
TurnControl_MouseMove()
void AForge.Controls.SliderControl.TurnControl_MouseMove (object sender, MouseEventArgs e) inline private
References AForge.Controls.SliderControl.isHorizontal, AForge.Controls.SliderControl.leftMargin, AForge.Controls.SliderControl.manipulatatorPosition, AForge.Controls.SliderControl.ticksBeforeNotificiation, AForge.Controls.SliderControl.topMargin, and AForge.Controls.SliderControl.tracking.
Referenced by AForge.Controls.SliderControl.InitializeComponent().
timer_Tick()
void AForge.Controls.SliderControl.timer_Tick (object sender, EventArgs e) inline private
References AForge.Controls.SliderControl.NotifyClients(), and AForge.Controls.SliderControl.ticksBeforeNotificiation.
Referenced by AForge.Controls.SliderControl.InitializeComponent().
NotifyClients()
void AForge.Controls.SliderControl.NotifyClients () inline private
References AForge.Controls.SliderControl.manipulatatorPosition, and AForge.Controls.SliderControl.PositionChanged.
Referenced by AForge.Controls.SliderControl.timer_Tick(), AForge.Controls.SliderControl.TurnControl_MouseDown(), and AForge.Controls.SliderControl.TurnControl_MouseUp().
Dispose()
override void AForge.Controls.SliderControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References AForge.Controls.SliderControl.components.
InitializeComponent()
void AForge.Controls.SliderControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References AForge.Controls.SliderControl.components, AForge.Controls.SliderControl.timer, AForge.Controls.SliderControl.timer_Tick(), AForge.Controls.SliderControl.TurnControl_MouseDown(), AForge.Controls.SliderControl.TurnControl_MouseMove(), AForge.Controls.SliderControl.TurnControl_MouseUp(), and AForge.Controls.SliderControl.TurnControl_Paint().
Referenced by AForge.Controls.SliderControl.SliderControl().
Member Data Documentation
isHorizontal
bool AForge.Controls.SliderControl.isHorizontal = true private
Referenced by AForge.Controls.SliderControl.TurnControl_MouseDown(), AForge.Controls.SliderControl.TurnControl_MouseMove(), and AForge.Controls.SliderControl.TurnControl_Paint().
resetPositionOnMouseRelease
bool AForge.Controls.SliderControl.resetPositionOnMouseRelease = true private
Referenced by AForge.Controls.SliderControl.TurnControl_MouseUp().
borderPen
Pen AForge.Controls.SliderControl.borderPen = new Pen(Color.Black) private
Referenced by AForge.Controls.SliderControl.TurnControl_Paint().
positiveAreaBrush
SolidBrush AForge.Controls.SliderControl.positiveAreaBrush = new SolidBrush(Color.White) private
Referenced by AForge.Controls.SliderControl.TurnControl_Paint().
negativeAreaBrush
SolidBrush AForge.Controls.SliderControl.negativeAreaBrush = new SolidBrush(Color.LightGray) private
Referenced by AForge.Controls.SliderControl.TurnControl_Paint().
manipulatorBrush
SolidBrush AForge.Controls.SliderControl.manipulatorBrush = new SolidBrush(Color.LightSeaGreen) private
Referenced by AForge.Controls.SliderControl.TurnControl_Paint().
disabledBrash
SolidBrush AForge.Controls.SliderControl.disabledBrash = new SolidBrush(Color.FromArgb(240, 240, 240)) private
Referenced by AForge.Controls.SliderControl.TurnControl_Paint().
manipulatorWidth
const int AForge.Controls.SliderControl.manipulatorWidth = 11 static private
Referenced by AForge.Controls.SliderControl.TurnControl_Paint().
manipulatorHeight
const int AForge.Controls.SliderControl.manipulatorHeight = 20 static private
Referenced by AForge.Controls.SliderControl.TurnControl_Paint().
leftMargin
int AForge.Controls.SliderControl.leftMargin private
Referenced by AForge.Controls.SliderControl.TurnControl_MouseDown(), AForge.Controls.SliderControl.TurnControl_MouseMove(), and AForge.Controls.SliderControl.TurnControl_Paint().
topMargin
int AForge.Controls.SliderControl.topMargin private
Referenced by AForge.Controls.SliderControl.TurnControl_MouseDown(), AForge.Controls.SliderControl.TurnControl_MouseMove(), and AForge.Controls.SliderControl.TurnControl_Paint().
manipulatatorPosition
float AForge.Controls.SliderControl.manipulatatorPosition = 0 private
Referenced by AForge.Controls.SliderControl.NotifyClients(), AForge.Controls.SliderControl.TurnControl_MouseDown(), AForge.Controls.SliderControl.TurnControl_MouseMove(), AForge.Controls.SliderControl.TurnControl_MouseUp(), and AForge.Controls.SliderControl.TurnControl_Paint().
tracking
bool AForge.Controls.SliderControl.tracking = false private
Referenced by AForge.Controls.SliderControl.TurnControl_MouseDown(), AForge.Controls.SliderControl.TurnControl_MouseMove(), and AForge.Controls.SliderControl.TurnControl_MouseUp().
ticksBeforeNotificiation
int AForge.Controls.SliderControl.ticksBeforeNotificiation = -1 private
Referenced by AForge.Controls.SliderControl.timer_Tick(), AForge.Controls.SliderControl.TurnControl_MouseDown(), and AForge.Controls.SliderControl.TurnControl_MouseMove().
components
System.ComponentModel.IContainer AForge.Controls.SliderControl.components = null private
Required designer variable.
Referenced by AForge.Controls.SliderControl.Dispose(), and AForge.Controls.SliderControl.InitializeComponent().
timer
System.Windows.Forms.Timer AForge.Controls.SliderControl.timer private
Referenced by AForge.Controls.SliderControl.InitializeComponent(), AForge.Controls.SliderControl.TurnControl_MouseDown(), and AForge.Controls.SliderControl.TurnControl_MouseUp().
Property Documentation
ResetPositionOnMouseRelease
bool AForge.Controls.SliderControl.ResetPositionOnMouseRelease get set
Determines behaviour of manipulator, when mouse button is released.
The property controls behaviour of manipulator on releasing mouse button. If the property is set to true, then position of manipulator is reset to 0, when mouse button is released. Otherwise manipulator stays on the place, where it was left.
Default value is set to true.
BorderColor
Color AForge.Controls.SliderControl.BorderColor get set
Color used for drawing borders.
Default value is set to Color.Black.
PositiveAreaBrush
Color AForge.Controls.SliderControl.PositiveAreaBrush get set
Background color used for filling area corresponding to positive values.
Default value is set to Color.White.
NegativeAreaBrush
Color AForge.Controls.SliderControl.NegativeAreaBrush get set
Background color used for filling area corresponding to negative values.
Default value is set to Color.LightGray.
ManipulatorColor
Color AForge.Controls.SliderControl.ManipulatorColor get set
Color used for filling manipulator.
Default value is set to Color.LightSeaGreen.
IsHorizontal
bool AForge.Controls.SliderControl.IsHorizontal get set
Defines if control has horizontal or vertical look.
Default value is set to true.
Referenced by AForge.Controls.SliderControl.SliderControl().
ManipulatorPosition
float AForge.Controls.SliderControl.ManipulatorPosition get set
Current manipulator's position, [-1, 1].
The property equals to current manipulator's position.
Event Documentation
PositionChanged
PositionChangedHandler AForge.Controls.SliderControl.PositionChanged
Event used for notification about manipulator's position changes.
Referenced by AForge.Controls.SliderControl.NotifyClients().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Sources/Controls/SliderControl.cs
shelldev/lib_ann/aforge.net/Sources/Controls/SliderControl.Designer.cs