Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLALS0 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLALS0 Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLALS0 (DCOPY dcopy, DGEMV dgemv, DLACPY dlacpy, DLASCL dlascl, DROT drot, DSCAL dscal, XERBLA xerbla, DLAMC3 dlamc3, DNRM2 dnrm2)
DLALS0 ()
void Run (int ICOMPQ, int NL, int NR, int SQRE, int NRHS, ref double[] B, int offset_b, int LDB, ref double[] BX, int offset_bx, int LDBX, int[] PERM, int offset_perm, int GIVPTR, int[] GIVCOL, int offset_givcol, int LDGCOL, double[] GIVNUM, int offset_givnum, int LDGNUM, double[] POLES, int offset_poles, double[] DIFL, int offset_difl, double[] DIFR, int offset_difr, double[] Z, int offset_z, int K, double C, double S, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
DCOPY _dcopy
DGEMV _dgemv
DLACPY _dlacpy
DLASCL _dlascl
DROT _drot
DSCAL _dscal
XERBLA _xerbla
DLAMC3 _dlamc3
DNRM2 _dnrm2
Static Private Attributes
const double ONE = 1.0E0
const double ZERO = 0.0E0
const double NEGONE = - 1.0E0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLALS0 applies back the multiplying factors of either the left or the right singular vector matrix of a diagonal matrix appended by a row to the right hand side matrix B in solving the least squares problem using the divide-and-conquer SVD approach.
For the left singular vector matrix, three types of orthogonal matrices are involved:
(1L) Givens rotations: the number of such rotations is GIVPTR; the pairs of columns/rows they were applied to are stored in GIVCOL; and the C- and S-values of these rotations are stored in GIVNUM.
(2L) Permutation. The (NL+1)-st row of B is to be moved to the first row, and for J=2:N, PERM(J)-th row of B is to be moved to the J-th row.
(3L) The left singular vector matrix of the remaining matrix.
For the right singular vector matrix, four types of orthogonal matrices are involved:
(1R) The right singular vector matrix of the remaining matrix.
(2R) If SQRE = 1, one extra Givens rotation to generate the right null space.
(3R) The inverse transformation of (2L).
(4R) The inverse transformation of (1L).
/summary>
Constructor & Destructor Documentation
DLALS0() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLALS0.DLALS0 (DCOPY dcopy, DGEMV dgemv, DLACPY dlacpy, DLASCL dlascl, DROT drot, DSCAL dscal, XERBLA xerbla, DLAMC3 dlamc3, DNRM2 dnrm2) inline
DLALS0() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLALS0.DLALS0 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLALS0.Run (int ICOMPQ, int NL, int NR, int SQRE, int NRHS, ref double[] B, int offset_b, int LDB, ref double[] BX, int offset_bx, int LDBX, int[] PERM, int offset_perm, int GIVPTR, int[] GIVCOL, int offset_givcol, int LDGCOL, double[] GIVNUM, int offset_givnum, int LDGNUM, double[] POLES, int offset_poles, double[] DIFL, int offset_difl, double[] DIFR, int offset_difr, double[] Z, int offset_z, int K, double C, double S, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
DLALS0 applies back the multiplying factors of either the left or the right singular vector matrix of a diagonal matrix appended by a row to the right hand side matrix B in solving the least squares problem using the divide-and-conquer SVD approach.
For the left singular vector matrix, three types of orthogonal matrices are involved:
(1L) Givens rotations: the number of such rotations is GIVPTR; the pairs of columns/rows they were applied to are stored in GIVCOL; and the C- and S-values of these rotations are stored in GIVNUM.
(2L) Permutation. The (NL+1)-st row of B is to be moved to the first row, and for J=2:N, PERM(J)-th row of B is to be moved to the J-th row.
(3L) The left singular vector matrix of the remaining matrix.
For the right singular vector matrix, four types of orthogonal matrices are involved:
(1R) The right singular vector matrix of the remaining matrix.
(2R) If SQRE = 1, one extra Givens rotation to generate the right null space.
(3R) The inverse transformation of (2L).
(4R) The inverse transformation of (1L).
/summary>
Parameters
ICOMPQ (input) INTEGER Specifies whether singular vectors are to be computed in factored form: = 0: Left singular vector matrix. = 1: Right singular vector matrix. /param>
Parameters
NL (input) INTEGER The row dimension of the upper block. NL .GE. 1. /param>
Parameters
NR (input) INTEGER The row dimension of the lower block. NR .GE. 1. /param>
Parameters
SQRE (input) INTEGER = 0: the lower block is an NR-by-NR square matrix. = 1: the lower block is an NR-by-(NR+1) rectangular matrix.
The bidiagonal matrix has row dimension N = NL + NR + 1, and column dimension M = N + SQRE. /param>
Parameters
NRHS (input) INTEGER The number of columns of B and BX. NRHS must be at least 1. /param>
Parameters
B (input/output) DOUBLE PRECISION array, dimension (LDB, NRHS) On input, B contains the right hand sides of the least squares problem in rows 1 through M. On output, B contains the solution X in rows 1 through N. /param>
Parameters
LDB (input) INTEGER The leading dimension of B. LDB must be at least max(1,MAX(M, N)). /param>
Parameters
BX (workspace) DOUBLE PRECISION array, dimension (LDBX, NRHS) /param>
Parameters
LDBX (input) INTEGER The leading dimension of BX. /param>
Parameters
PERM (input) INTEGER array, dimension (N) The permutations (from deflation and sorting) applied to the two blocks. /param>
Parameters
GIVPTR (input) INTEGER The number of Givens rotations which took place in this subproblem. /param>
Parameters
GIVCOL (input) INTEGER array, dimension (LDGCOL, 2) Each pair of numbers indicates a pair of rows/columns involved in a Givens rotation. /param>
Parameters
LDGCOL (input) INTEGER The leading dimension of GIVCOL, must be at least N. /param>
Parameters
GIVNUM (input) DOUBLE PRECISION array, dimension (LDGNUM, 2) Each number indicates the C or S value used in the corresponding Givens rotation. /param>
Parameters
LDGNUM (input) INTEGER The leading dimension of arrays DIFR, POLES and GIVNUM, must be at least K. /param>
Parameters
POLES (input) DOUBLE PRECISION array, dimension (LDGNUM, 2) On entry, POLES(1:K, 1) contains the new singular values obtained from solving the secular equation, and POLES(1:K, 2) is an array containing the poles in the secular equation. /param>
Parameters
DIFL (input) DOUBLE PRECISION array, dimension (K). On entry, DIFL(I) is the distance between I-th updated (undeflated) singular value and the I-th (undeflated) old singular value. /param>
Parameters
DIFR (input) DOUBLE PRECISION array, dimension (LDGNUM, 2). On entry, DIFR(I, 1) contains the distances between I-th updated (undeflated) singular value and the I+1-th (undeflated) old singular value. And DIFR(I, 2) is the normalizing factor for the I-th right singular vector. /param>
Parameters
Z (input) DOUBLE PRECISION array, dimension (K) Contain the components of the deflation-adjusted updating row vector. /param>
Parameters
K (input) INTEGER Contains the dimension of the non-deflated matrix, This is the order of the related secular equation. 1 .LE. K .LE.N. /param>
Parameters
C (input) DOUBLE PRECISION C contains garbage if SQRE =0 and the C-value of a Givens rotation related to the right null space if SQRE = 1. /param>
Parameters
S (input) DOUBLE PRECISION S contains garbage if SQRE =0 and the S-value of a Givens rotation related to the right null space if SQRE = 1. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (K) /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLALS0.NEGONE, DotNumerics.LinearAlgebra.CSLapack.DLALS0.ONE, DotNumerics.LinearAlgebra.CSLapack.DROT.Run(), DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DNRM2.Run(), DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMC3.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLALS0.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLALSA.Run().
Member Data Documentation
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLALS0._dcopy private
_dgemv
DGEMV DotNumerics.LinearAlgebra.CSLapack.DLALS0._dgemv private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DLALS0._dlacpy private
_dlascl
DLASCL DotNumerics.LinearAlgebra.CSLapack.DLALS0._dlascl private
_drot
DROT DotNumerics.LinearAlgebra.CSLapack.DLALS0._drot private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DLALS0._dscal private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLALS0._xerbla private
_dlamc3
DLAMC3 DotNumerics.LinearAlgebra.CSLapack.DLALS0._dlamc3 private
_dnrm2
DNRM2 DotNumerics.LinearAlgebra.CSLapack.DLALS0._dnrm2 private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLALS0.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLALS0.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLALS0.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLALS0.Run().
NEGONE
const double DotNumerics.LinearAlgebra.CSLapack.DLALS0.NEGONE = - 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLALS0.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlals0.cs