Doc: IGLib EXTENDED: IG.Neural.Applications.NeuralParametricDemoAbout Class Reference
IG.Neural.Applications.NeuralParametricDemoAbout Class Reference
Form containing information about neural demo software.
Public Member Functions
NeuralParametricDemoAbout ()
virtual string GetHelpLocationInExecutableDirectory ()
void ShowHelp ()
void ShowWebPage ()
NeuralParametricDemoAbout ()
virtual string GetHelpLocationInExecutableDirectory ()
void ShowHelp ()
void ShowWebPage ()
NeuralParametricDemoAbout ()
virtual string GetHelpLocationInExecutableDirectory ()
void ShowHelp ()
void ShowWebPage ()
NeuralParametricDemoAbout ()
virtual string GetHelpLocationInExecutableDirectory ()
void ShowHelp ()
void ShowWebPage ()
Public Attributes
string DefaultApplicationName = "NeuralParametric"
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
string _homePageShort
string _helpLocation
BrowserSimpleForm _browser
string _applicationName
BrowserSimpleWindow _browser
Properties
virtual string HomePageShort [get, protected set]
Short version of the application's home page.
virtual string HomePage [get]
virtual string HelpLocation [get]
Location of the help file that can be displayed in a web browser.
BrowserSimpleForm Browser [get]
string ApplicationName [get]
BrowserSimpleWindow Browser [get]
Private Member Functions
void lblAboutWeb_Click (object sender, EventArgs e)
void btnHelp_Click (object sender, EventArgs e)
void btnWeb_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void lblAboutWeb_Click (object sender, EventArgs e)
void btnHelp_Click (object sender, EventArgs e)
void btnWeb_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void lblAboutWeb_Click (object sender, EventArgs e)
void btnHelp_Click (object sender, EventArgs e)
void btnWeb_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void lblAboutWeb_Click (object sender, EventArgs e)
void btnHelp_Click (object sender, EventArgs e)
void btnWeb_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Label lblTitle
System.Windows.Forms.Button btnHelp
System.Windows.Forms.Panel pnlAbout
System.Windows.Forms.Label lblAboutAuthors
System.Windows.Forms.Label lblAboutAuthorsIntro
System.Windows.Forms.Label lblAboutTitle
System.Windows.Forms.Label lblAboutWeb
System.Windows.Forms.Label lblAboutContact
System.Windows.Forms.Label lblAbourContactIntro
System.Windows.Forms.PictureBox pbIGLib
System.Windows.Forms.Label lblPoweredIGLib
System.Windows.Forms.Panel pnlIGLib
System.Windows.Forms.Button btnWeb
System.Windows.Forms.Panel pnlCompany
System.Windows.Forms.PictureBox pbCompany
System.Windows.Forms.Panel pnlCobik
System.Windows.Forms.PictureBox pbCobik
Static Private Attributes
const string DefaultHomePageShort = "www2.arnes.si/~ljc3m2/igor/software/neural_parametric/"
const string DefaultHelpLocation = "http://www2.arnes.si/~ljc3m2/igor/software/neural_parametric/doc/help.html"
Detailed Description
Form containing information about neural demo software.
Help can also be triggered from here.
Constructor & Destructor Documentation
NeuralParametricDemoAbout() [1/4]
IG.Neural.Applications.NeuralParametricDemoAbout.NeuralParametricDemoAbout () inline
References IG.Neural.Applications.NeuralParametricDemoAbout.DefaultHomePageShort, IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent(), and IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb.
NeuralParametricDemoAbout() [2/4]
IG.Neural.Applications.NeuralParametricDemoAbout.NeuralParametricDemoAbout () inline
References IG.Neural.Applications.NeuralParametricDemoAbout.DefaultHomePageShort, IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent(), and IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb.
NeuralParametricDemoAbout() [3/4]
IG.Neural.Applications.NeuralParametricDemoAbout.NeuralParametricDemoAbout () inline
References IG.Neural.Applications.NeuralParametricDemoAbout.DefaultHomePageShort, IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent(), and IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb.
NeuralParametricDemoAbout() [4/4]
IG.Neural.Applications.NeuralParametricDemoAbout.NeuralParametricDemoAbout () inline
References IG.Neural.Applications.NeuralParametricDemoAbout.DefaultHomePageShort, IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent(), and IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb.
Member Function Documentation
GetHelpLocationInExecutableDirectory() [1/4]
virtual string IG.Neural.Applications.NeuralParametricDemoAbout.GetHelpLocationInExecutableDirectory () inline virtual
References IG.Neural.Applications.NeuralParametricDemoAbout.ApplicationName.
ShowHelp() [1/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.ShowHelp () inline
References IG.Neural.Applications.NeuralParametricDemoAbout.Browser, IG.Neural.Applications.NeuralParametricDemoAbout.HelpLocation, and IG.Forms.BrowserSimpleForm.OpenLocation().
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.btnHelp_Click(), and IG.Neural.Applications.NeuralParametricDemoAboutWindow.ShowHelp().
ShowWebPage() [1/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.ShowWebPage () inline
References IG.Neural.Applications.NeuralParametricDemoAbout.Browser, IG.Neural.Applications.NeuralParametricDemoAbout.HomePage, and IG.Forms.BrowserSimpleForm.OpenLocation().
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.btnWeb_Click(), and IG.Neural.Applications.NeuralParametricDemoAboutWindow.ShowWebPage().
lblAboutWeb_Click() [1/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb.
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent().
btnHelp_Click() [1/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.btnHelp_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralParametricDemoAbout.ShowHelp().
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent().
btnWeb_Click() [1/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.btnWeb_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralParametricDemoAbout.ShowWebPage().
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent().
Dispose() [1/4]
override void IG.Neural.Applications.NeuralParametricDemoAbout.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralParametricDemoAbout.components.
InitializeComponent() [1/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralParametricDemoAbout.btnHelp, IG.Neural.Applications.NeuralParametricDemoAbout.btnHelp_Click(), IG.Neural.Applications.NeuralParametricDemoAbout.btnWeb, IG.Neural.Applications.NeuralParametricDemoAbout.btnWeb_Click(), IG.Neural.Applications.NeuralParametricDemoAbout.lblAbourContactIntro, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutAuthors, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutAuthorsIntro, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutContact, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutTitle, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb_Click(), IG.Neural.Applications.NeuralParametricDemoAbout.lblPoweredIGLib, IG.Neural.Applications.NeuralParametricDemoAbout.lblTitle, IG.Neural.Applications.NeuralParametricDemoAbout.pbCompany, IG.Neural.Applications.NeuralParametricDemoAbout.pbIGLib, IG.Neural.Applications.NeuralParametricDemoAbout.pnlAbout, IG.Neural.Applications.NeuralParametricDemoAbout.pnlCompany, and IG.Neural.Applications.NeuralParametricDemoAbout.pnlIGLib.
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.NeuralParametricDemoAbout().
GetHelpLocationInExecutableDirectory() [2/4]
virtual string IG.Neural.Applications.NeuralParametricDemoAbout.GetHelpLocationInExecutableDirectory () inline virtual
References IG.Neural.Applications.NeuralParametricDemoAbout.ApplicationName.
ShowHelp() [2/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.ShowHelp () inline
References IG.Neural.Applications.NeuralParametricDemoAbout.Browser, IG.Neural.Applications.NeuralParametricDemoAbout.HelpLocation, and IG.Forms.BrowserSimpleForm.OpenLocation().
ShowWebPage() [2/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.ShowWebPage () inline
References IG.Neural.Applications.NeuralParametricDemoAbout.Browser, IG.Neural.Applications.NeuralParametricDemoAbout.HomePage, and IG.Forms.BrowserSimpleForm.OpenLocation().
lblAboutWeb_Click() [2/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb.
btnHelp_Click() [2/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.btnHelp_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralParametricDemoAbout.ShowHelp().
btnWeb_Click() [2/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.btnWeb_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralParametricDemoAbout.ShowWebPage().
Dispose() [2/4]
override void IG.Neural.Applications.NeuralParametricDemoAbout.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralParametricDemoAbout.components.
InitializeComponent() [2/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralParametricDemoAbout.btnHelp, IG.Neural.Applications.NeuralParametricDemoAbout.btnHelp_Click(), IG.Neural.Applications.NeuralParametricDemoAbout.btnWeb, IG.Neural.Applications.NeuralParametricDemoAbout.btnWeb_Click(), IG.Neural.Applications.NeuralParametricDemoAbout.lblAbourContactIntro, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutAuthors, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutAuthorsIntro, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutContact, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutTitle, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb_Click(), IG.Neural.Applications.NeuralParametricDemoAbout.lblPoweredIGLib, IG.Neural.Applications.NeuralParametricDemoAbout.lblTitle, IG.Neural.Applications.NeuralParametricDemoAbout.pbCobik, IG.Neural.Applications.NeuralParametricDemoAbout.pbIGLib, IG.Neural.Applications.NeuralParametricDemoAbout.pnlAbout, IG.Neural.Applications.NeuralParametricDemoAbout.pnlCobik, and IG.Neural.Applications.NeuralParametricDemoAbout.pnlIGLib.
GetHelpLocationInExecutableDirectory() [3/4]
virtual string IG.Neural.Applications.NeuralParametricDemoAbout.GetHelpLocationInExecutableDirectory () inline virtual
References IG.Neural.Applications.NeuralParametricDemoAbout.ApplicationName.
ShowHelp() [3/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.ShowHelp () inline
References IG.Neural.Applications.NeuralParametricDemoAbout.Browser, IG.Neural.Applications.NeuralParametricDemoAbout.HelpLocation, and IG.Forms.BrowserSimpleForm.OpenLocation().
ShowWebPage() [3/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.ShowWebPage () inline
References IG.Neural.Applications.NeuralParametricDemoAbout.Browser, IG.Neural.Applications.NeuralParametricDemoAbout.HomePage, and IG.Forms.BrowserSimpleForm.OpenLocation().
lblAboutWeb_Click() [3/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb.
btnHelp_Click() [3/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.btnHelp_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralParametricDemoAbout.ShowHelp().
btnWeb_Click() [3/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.btnWeb_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralParametricDemoAbout.ShowWebPage().
Dispose() [3/4]
override void IG.Neural.Applications.NeuralParametricDemoAbout.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralParametricDemoAbout.components.
InitializeComponent() [3/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralParametricDemoAbout.btnHelp, IG.Neural.Applications.NeuralParametricDemoAbout.btnHelp_Click(), IG.Neural.Applications.NeuralParametricDemoAbout.btnWeb, IG.Neural.Applications.NeuralParametricDemoAbout.btnWeb_Click(), IG.Neural.Applications.NeuralParametricDemoAbout.lblAbourContactIntro, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutAuthors, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutAuthorsIntro, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutContact, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutTitle, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb_Click(), IG.Neural.Applications.NeuralParametricDemoAbout.lblPoweredIGLib, IG.Neural.Applications.NeuralParametricDemoAbout.lblTitle, IG.Neural.Applications.NeuralParametricDemoAbout.pbCobik, IG.Neural.Applications.NeuralParametricDemoAbout.pbIGLib, IG.Neural.Applications.NeuralParametricDemoAbout.pnlAbout, IG.Neural.Applications.NeuralParametricDemoAbout.pnlCobik, and IG.Neural.Applications.NeuralParametricDemoAbout.pnlIGLib.
GetHelpLocationInExecutableDirectory() [4/4]
virtual string IG.Neural.Applications.NeuralParametricDemoAbout.GetHelpLocationInExecutableDirectory () inline virtual
References IG.Neural.Applications.NeuralParametricDemoAbout.ApplicationName.
ShowHelp() [4/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.ShowHelp () inline
References IG.Neural.Applications.NeuralParametricDemoAbout.Browser, IG.Neural.Applications.NeuralParametricDemoAbout.HelpLocation, and IG.Forms.BrowserSimpleForm.OpenLocation().
ShowWebPage() [4/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.ShowWebPage () inline
References IG.Neural.Applications.NeuralParametricDemoAbout.Browser, IG.Neural.Applications.NeuralParametricDemoAbout.HomePage, and IG.Forms.BrowserSimpleForm.OpenLocation().
lblAboutWeb_Click() [4/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb.
btnHelp_Click() [4/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.btnHelp_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralParametricDemoAbout.ShowHelp().
btnWeb_Click() [4/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.btnWeb_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.NeuralParametricDemoAbout.ShowWebPage().
Dispose() [4/4]
override void IG.Neural.Applications.NeuralParametricDemoAbout.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralParametricDemoAbout.components.
InitializeComponent() [4/4]
void IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralParametricDemoAbout.btnHelp, IG.Neural.Applications.NeuralParametricDemoAbout.btnHelp_Click(), IG.Neural.Applications.NeuralParametricDemoAbout.btnWeb, IG.Neural.Applications.NeuralParametricDemoAbout.btnWeb_Click(), IG.Neural.Applications.NeuralParametricDemoAbout.lblAbourContactIntro, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutAuthors, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutAuthorsIntro, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutContact, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutTitle, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb, IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb_Click(), IG.Neural.Applications.NeuralParametricDemoAbout.lblPoweredIGLib, IG.Neural.Applications.NeuralParametricDemoAbout.lblTitle, IG.Neural.Applications.NeuralParametricDemoAbout.pbCobik, IG.Neural.Applications.NeuralParametricDemoAbout.pbIGLib, IG.Neural.Applications.NeuralParametricDemoAbout.pnlAbout, IG.Neural.Applications.NeuralParametricDemoAbout.pnlCobik, and IG.Neural.Applications.NeuralParametricDemoAbout.pnlIGLib.
Member Data Documentation
DefaultHomePageShort
const string IG.Neural.Applications.NeuralParametricDemoAbout.DefaultHomePageShort = "www2.arnes.si/~ljc3m2/igor/software/neural_parametric/" static private
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.NeuralParametricDemoAbout().
_homePageShort
string IG.Neural.Applications.NeuralParametricDemoAbout._homePageShort protected
DefaultHelpLocation
const string IG.Neural.Applications.NeuralParametricDemoAbout.DefaultHelpLocation = "http://www2.arnes.si/~ljc3m2/igor/software/neural_parametric/doc/help.html" static private
_helpLocation
string IG.Neural.Applications.NeuralParametricDemoAbout._helpLocation protected
_browser [1/2]
BrowserSimpleWindow IG.Neural.Applications.NeuralParametricDemoAbout._browser protected
DefaultApplicationName
string IG.Neural.Applications.NeuralParametricDemoAbout.DefaultApplicationName = "NeuralParametric"
_applicationName
string IG.Neural.Applications.NeuralParametricDemoAbout._applicationName protected
components
System ComponentModel IContainer IG.Neural.Applications.NeuralParametricDemoAbout.components = null private
Required designer variable.
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.Dispose().
lblTitle
System Windows Forms Label IG.Neural.Applications.NeuralParametricDemoAbout.lblTitle private
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent().
btnHelp
System Windows Forms Button IG.Neural.Applications.NeuralParametricDemoAbout.btnHelp private
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent().
pnlAbout
System Windows Forms Panel IG.Neural.Applications.NeuralParametricDemoAbout.pnlAbout private
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent().
lblAboutAuthors
System Windows Forms Label IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutAuthors private
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent().
lblAboutAuthorsIntro
System Windows Forms Label IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutAuthorsIntro private
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent().
lblAboutTitle
System Windows Forms Label IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutTitle private
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent().
lblAboutWeb
System Windows Forms Label IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb private
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent(), IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutWeb_Click(), and IG.Neural.Applications.NeuralParametricDemoAbout.NeuralParametricDemoAbout().
lblAboutContact
System Windows Forms Label IG.Neural.Applications.NeuralParametricDemoAbout.lblAboutContact private
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent().
lblAbourContactIntro
System Windows Forms Label IG.Neural.Applications.NeuralParametricDemoAbout.lblAbourContactIntro private
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent().
pbIGLib
System Windows Forms PictureBox IG.Neural.Applications.NeuralParametricDemoAbout.pbIGLib private
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent().
lblPoweredIGLib
System Windows Forms Label IG.Neural.Applications.NeuralParametricDemoAbout.lblPoweredIGLib private
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent().
pnlIGLib
System Windows Forms Panel IG.Neural.Applications.NeuralParametricDemoAbout.pnlIGLib private
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent().
btnWeb
System Windows Forms Button IG.Neural.Applications.NeuralParametricDemoAbout.btnWeb private
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent().
pnlCompany
System.Windows.Forms.Panel IG.Neural.Applications.NeuralParametricDemoAbout.pnlCompany private
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent().
pbCompany
System.Windows.Forms.PictureBox IG.Neural.Applications.NeuralParametricDemoAbout.pbCompany private
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent().
_browser [2/2]
BrowserSimpleWindow IG.Neural.Applications.NeuralParametricDemoAbout._browser protected
pnlCobik
System Windows Forms Panel IG.Neural.Applications.NeuralParametricDemoAbout.pnlCobik private
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent().
pbCobik
System Windows Forms PictureBox IG.Neural.Applications.NeuralParametricDemoAbout.pbCobik private
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.InitializeComponent().
Property Documentation
HomePageShort
string IG.Neural.Applications.NeuralParametricDemoAbout.HomePageShort get protected set
Short version of the application's home page.
HomePage
string IG.Neural.Applications.NeuralParametricDemoAbout.HomePage get
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.ShowWebPage().
HelpLocation
string IG.Neural.Applications.NeuralParametricDemoAbout.HelpLocation get
Location of the help file that can be displayed in a web browser.
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.ShowHelp().
Browser [1/2]
BrowserSimpleWindow IG.Neural.Applications.NeuralParametricDemoAbout.Browser get protected
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.ShowHelp(), and IG.Neural.Applications.NeuralParametricDemoAbout.ShowWebPage().
ApplicationName
string IG.Neural.Applications.NeuralParametricDemoAbout.ApplicationName get
Referenced by IG.Neural.Applications.NeuralParametricDemoAbout.GetHelpLocationInExecutableDirectory().
Browser [2/2]
BrowserSimpleWindow IG.Neural.Applications.NeuralParametricDemoAbout.Browser get protected
The documentation for this class was generated from the following files:
shelldev/extensions/ExtAppAnnApp/ResponseForms/NeuralParametricDemoAbout.cs
shelldev/extensions/ExtAppAnnApp/ResponseForms/NeuralParametricDemoAbout.Designer.cs