Doc: IGLib EXTENDED: DotNumerics.FortranLibrary.FortranLib Class Reference
DotNumerics.FortranLibrary.FortranLib Class Reference
Public Member Functions
string ADJUSTR (string s)
ADJUSTR(STRING) Adjust to the right, removing trailing blanks and inserting leading blanks. Argument Type and Attributes STRING must be of type character. Class Elemental function Result Type and Attributes Character of the same length and kind type parameter as STRING. Result Value The value of the result is the same as STRING except that any trailing blanks have been deleted and the same number of leading blanks have been inserted. Examples ADJUSTR (’WORDb’) has the value ’bWORD’.
Static Public Member Functions
static int LEN_TRIM (string s)
LEN_TRIM Description: Returns the length of the character argument without counting trailing blank characters. Syntax: result = LEN_TRIM (string [, kind]) Class: Elemental function; Generic Arguments: string Must be of type character. kind (opt) Must be a scalar integer initialization expression. Examples LEN_TRIM (' C D ') has the value 7. LEN_TRIM (' ') has the value 0.
static int LEN_TRIM (Characters chars)
static string REPEAT (string s, int ncopies)
REPEAT Description: Concatenates several copies of a string. Syntax: result = REPEAT (string, ncopies) Class: Transformational function; Generic Arguments: string Must be scalar and of type character. ncopies Must be scalar and of type integer. It must not be negative. Results: The result is a scalar of type character and length ncopies x LEN(string). The kind parameter is the same as string. The value of the result is the concatenation of ncopies copies of string. Examples REPEAT ('S', 3) has the value SSS. REPEAT ('ABC', 0) has the value of a zero-length string.
static int Sign (int a1, int a2)
Transfer of sign Returns |a1| if a2>= 0 Returns -|a1| if a2< 0
static float Sign (float a1, float a2)
Transfer of sign Returns |a1| if a2>= 0 Returns -|a1| if a2< 0
static double Sign (double a1, double a2)
Transfer of sign Returns |a1| if a2>= 0 Returns -|a1| if a2< 0
static int Mod (int a1, int a2)
Summary: Returns the remainder resulting from the division of a specified number by another specified number.
static float AMod (float a1, float a2)
Summary: Returns the remainder resulting from the division of a specified number by another specified number.
static double DMod (double a1, double a2)
Summary: Returns the remainder resulting from the division of a specified number by another specified number.
static int SCAN (string s, string set, bool back)
SCAN(STRING, SET, BACK) Scan a string for any one of the characters in a set of characters. Argument Type and Attributes STRING must be of type character. SET must be of type character with the same kind type parameter as STRING. BACK (optional) must be of type logical. Class Elemental function Result Type and Attributes Default integer. Result Value v Case (i): If BACK is absent or is present with the value .FALSE. and if STRING contains at least one character that is in SET, the value of the result is the position of the leftmost character of STRING that is in SET. v Case (ii): If BACK is present with the value .TRUE. and if STRING contains at least one character that is in SET, the value of the result is the position of the rightmost character of STRING that is in SET. v Case (iii): The value of the result is zero if no character of STRING is in SET or if the length of STRING or SET is zero. Examples v Case (i): SCAN (’FORTRAN’, ’TR’) has the value 3. v Case (ii): SCAN (’FORTRAN’, ’TR’, BACK = .TRUE.) has the value 5. v Case (iii): SCAN (’FORTRAN’, ’BCD’) has the value 0.
static int SCAN (string s, string set)
static int SCAN (Characters charArray, string set, bool back)
static int SCAN (Characters charArray, string set)
static int INDEX (string s, string value, bool back)
INDEX INDEX(STRING, SUBSTRING, BACK) Returns the starting position of a substring within a string. Argument Type and Attributes STRING must be of type character. SUBSTRING must be of type character with the same kind type parameter as STRING. BACK (optional) must be of type logical. Class Elemental function Result Type and Attributes Default integer. Result Value v Case (i): If BACK is absent or present with the value .FALSE., the result is the minimum positive value of I such that STRING (I : I + LEN (SUBSTRING) - 1) = SUBSTRING or zero if there is no such value. Zero is returned if LEN (STRING) .LT. LEN (SUBSTRING). One is returned if LEN (SUBSTRING) = 0. v Case (ii): If BACK is present with the value .TRUE., the result is the maximum value of I less than or equal to LEN (STRING) - LEN (SUBSTRING) + 1, such that STRING (I : I + LEN (SUBSTRING) - 1) = SUBSTRING or zero if there is no such value. Zero is returned if LEN (STRING) .LT. LEN (SUBSTRING) and LEN (STRING) + 1 is returned if LEN (SUBSTRING) = 0. Examples INDEX (’FORTRAN’, ’R’) has the value 3. INDEX (’FORTRAN’, ’R’, BACK = .TRUE.) has the value 5.
static int INDEX (string s, string value)
static int INDEX (Characters chars, string value, bool back)
static int INDEX (Characters chars, string value)
static int INDEX (Characters chars, Characters value, bool back)
static int INDEX (Characters chars, Characters value)
static string ADJUSTL (string s)
ADJUSTL(STRING) Adjust to the left, removing leading blanks and inserting trailing blanks. Argument Type and Attributes STRING must be of type character. Class Elemental function Result Type and Attributes Character of the same length and kind type parameter as STRING. Result Value The value of the result is the same as STRING except that any leading blanks have been deleted and the same number of trailing blanks have been inserted. Examples ADJUSTL (’bWORD’) has the value ’WORDb’.
static string Substring (string s, int startIndex, int lastIndex)
static string Substring (string s, int startIndex)
static void Copy (ref string destinationString, int startIndex, int lastIndex, string sourceString)
static void Copy (ref string destinationString, int startIndex, int lastIndex, char source)
static void Copy (ref string destinationString, int startIndex, string sourceString)
static void Copy (ref string destinationString, string sourceString)
static char[] Substring (char[] s, int startIndex, int lastIndex)
Retrieves a substring . The substring starts at a specified character position and finisch a specified position.
static char[] Substring (char[] s, int startIndex)
Retrieves a substring . The substring starts at a specified character position.
static void Copy (char[] destinationArray, int startIndex, int lastIndex, char[] sourceArray)
static void Copy (char[] destinationArray, int startIndex, char[] sourceArray)
static void Copy (Characters destination, int startIndex, int lastIndex, Characters source)
static void Copy (Characters destination, int startIndex, Characters source)
static void Copy (Characters destination, Characters source)
static void Copy (Characters destination, int startIndex, int lastIndex, string source)
static void Copy (Characters destination, int startIndex, string source)
static void Copy (Characters destination, string source)
Member Function Documentation
LEN_TRIM() [1/2]
static int DotNumerics.FortranLibrary.FortranLib.LEN_TRIM (string s) inline static
LEN_TRIM Description: Returns the length of the character argument without counting trailing blank characters. Syntax: result = LEN_TRIM (string [, kind]) Class: Elemental function; Generic Arguments: string Must be of type character. kind (opt) Must be a scalar integer initialization expression. Examples LEN_TRIM (' C D ') has the value 7. LEN_TRIM (' ') has the value 0.
From Intel Fortran Language Reference
Parameters
s
Returns
LEN_TRIM() [2/2]
static int DotNumerics.FortranLibrary.FortranLib.LEN_TRIM (Characters chars) inline static
References DotNumerics.FortranLibrary.Characters.LenTrim().
REPEAT()
static string DotNumerics.FortranLibrary.FortranLib.REPEAT (string s, int ncopies) inline static
REPEAT Description: Concatenates several copies of a string. Syntax: result = REPEAT (string, ncopies) Class: Transformational function; Generic Arguments: string Must be scalar and of type character. ncopies Must be scalar and of type integer. It must not be negative. Results: The result is a scalar of type character and length ncopies x LEN(string). The kind parameter is the same as string. The value of the result is the concatenation of ncopies copies of string. Examples REPEAT ('S', 3) has the value SSS. REPEAT ('ABC', 0) has the value of a zero-length string.
From Intel Fortran Language Reference
Parameters
s
count
Returns
Sign() [1/3]
static int DotNumerics.FortranLibrary.FortranLib.Sign (int a1, int a2) inline static
Transfer of sign Returns |a1| if a2>= 0 Returns -|a1| if a2< 0
Returns
Returns |a1| if a2>= 0, Returns -|a1| if a2< 0
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLACON.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTERF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANV2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASV2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED9.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAIC1.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD8.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED3.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD3.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALSD.Run(), DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run(), and DotNumerics.LinearAlgebra.CSLapack.DBDSDC.Run().
Sign() [2/3]
static float DotNumerics.FortranLibrary.FortranLib.Sign (float a1, float a2) inline static
Transfer of sign Returns |a1| if a2>= 0 Returns -|a1| if a2< 0
Returns
Returns |a1| if a2>= 0, Returns -|a1| if a2< 0
Sign() [3/3]
static double DotNumerics.FortranLibrary.FortranLib.Sign (double a1, double a2) inline static
Transfer of sign Returns |a1| if a2>= 0 Returns -|a1| if a2< 0
Returns
Returns |a1| if a2>= 0, Returns -|a1| if a2< 0
Mod()
static int DotNumerics.FortranLibrary.FortranLib.Mod (int a1, int a2) inline static
Summary: Returns the remainder resulting from the division of a specified number by another specified number.
Parameters: y: A divisor.
x: A dividend.
Returns: A number equal to x - (y Q), where Q = Math.Truncate(x/y)
Parameters
a1 A divisor.
a2 A dividend.
Returns
A number equal to x - (y Q), where Q = Math.Truncate(x/y)
Referenced by DotNumerics.LinearAlgebra.CSLapack.DAXPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DDOT.Run(), DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DASUM.Run(), DotNumerics.LinearAlgebra.CSLapack.DSWAP.Run(), DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.IPARMQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR5.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEDC.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR4.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR0.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAMC5.Run().
AMod()
static float DotNumerics.FortranLibrary.FortranLib.AMod (float a1, float a2) inline static
Summary: Returns the remainder resulting from the division of a specified number by another specified number.
Parameters: y: A divisor.
x: A dividend.
Returns: A number equal to x - (y Q), where Q = Math.Truncate(x/y)
Parameters
a1 A divisor.
a2 A dividend.
Returns
A number equal to x - (y Q), where Q = Math.Truncate(x/y)
DMod()
static double DotNumerics.FortranLibrary.FortranLib.DMod (double a1, double a2) inline static
Summary: Returns the remainder resulting from the division of a specified number by another specified number.
Parameters: y: A divisor.
x: A dividend.
Returns: A number equal to x - (y Q), where Q = Math.Truncate(x/y)
Parameters
a1 A divisor.
a2 A dividend.
Returns
A number equal to x - (y Q), where Q = Math.Truncate(x/y)
SCAN() [1/4]
static int DotNumerics.FortranLibrary.FortranLib.SCAN (string s, string set, bool back) inline static
SCAN(STRING, SET, BACK) Scan a string for any one of the characters in a set of characters. Argument Type and Attributes STRING must be of type character. SET must be of type character with the same kind type parameter as STRING. BACK (optional) must be of type logical. Class Elemental function Result Type and Attributes Default integer. Result Value v Case (i): If BACK is absent or is present with the value .FALSE. and if STRING contains at least one character that is in SET, the value of the result is the position of the leftmost character of STRING that is in SET. v Case (ii): If BACK is present with the value .TRUE. and if STRING contains at least one character that is in SET, the value of the result is the position of the rightmost character of STRING that is in SET. v Case (iii): The value of the result is zero if no character of STRING is in SET or if the length of STRING or SET is zero. Examples v Case (i): SCAN (’FORTRAN’, ’TR’) has the value 3. v Case (ii): SCAN (’FORTRAN’, ’TR’, BACK = .TRUE.) has the value 5. v Case (iii): SCAN (’FORTRAN’, ’BCD’) has the value 0.
IBM XL Fortran for AIX
Parameters
s
value
back
Returns
Referenced by DotNumerics.FortranLibrary.FortranLib.SCAN().
SCAN() [2/4]
static int DotNumerics.FortranLibrary.FortranLib.SCAN (string s, string set) inline static
References DotNumerics.FortranLibrary.FortranLib.SCAN().
SCAN() [3/4]
static int DotNumerics.FortranLibrary.FortranLib.SCAN (Characters charArray, string set, bool back) inline static
References DotNumerics.FortranLibrary.FortranLib.SCAN(), and DotNumerics.FortranLibrary.Characters.ToString().
SCAN() [4/4]
static int DotNumerics.FortranLibrary.FortranLib.SCAN (Characters charArray, string set) inline static
References DotNumerics.FortranLibrary.FortranLib.SCAN(), and DotNumerics.FortranLibrary.Characters.ToString().
INDEX() [1/6]
static int DotNumerics.FortranLibrary.FortranLib.INDEX (string s, string value, bool back) inline static
INDEX INDEX(STRING, SUBSTRING, BACK) Returns the starting position of a substring within a string. Argument Type and Attributes STRING must be of type character. SUBSTRING must be of type character with the same kind type parameter as STRING. BACK (optional) must be of type logical. Class Elemental function Result Type and Attributes Default integer. Result Value v Case (i): If BACK is absent or present with the value .FALSE., the result is the minimum positive value of I such that STRING (I : I + LEN (SUBSTRING) - 1) = SUBSTRING or zero if there is no such value. Zero is returned if LEN (STRING) .LT. LEN (SUBSTRING). One is returned if LEN (SUBSTRING) = 0. v Case (ii): If BACK is present with the value .TRUE., the result is the maximum value of I less than or equal to LEN (STRING) - LEN (SUBSTRING) + 1, such that STRING (I : I + LEN (SUBSTRING) - 1) = SUBSTRING or zero if there is no such value. Zero is returned if LEN (STRING) .LT. LEN (SUBSTRING) and LEN (STRING) + 1 is returned if LEN (SUBSTRING) = 0. Examples INDEX (’FORTRAN’, ’R’) has the value 3. INDEX (’FORTRAN’, ’R’, BACK = .TRUE.) has the value 5.
IBM XL Fortran for AIX
Parameters
s
value
back
Returns
Referenced by DotNumerics.FortranLibrary.FortranLib.INDEX().
INDEX() [2/6]
static int DotNumerics.FortranLibrary.FortranLib.INDEX (string s, string value) inline static
References DotNumerics.FortranLibrary.FortranLib.INDEX().
INDEX() [3/6]
static int DotNumerics.FortranLibrary.FortranLib.INDEX (Characters chars, string value, bool back) inline static
References DotNumerics.FortranLibrary.FortranLib.INDEX(), and DotNumerics.FortranLibrary.Characters.ToString().
INDEX() [4/6]
static int DotNumerics.FortranLibrary.FortranLib.INDEX (Characters chars, string value) inline static
References DotNumerics.FortranLibrary.FortranLib.INDEX(), and DotNumerics.FortranLibrary.Characters.ToString().
INDEX() [5/6]
static int DotNumerics.FortranLibrary.FortranLib.INDEX (Characters chars, Characters value, bool back) inline static
References DotNumerics.FortranLibrary.FortranLib.INDEX(), and DotNumerics.FortranLibrary.Characters.ToString().
INDEX() [6/6]
static int DotNumerics.FortranLibrary.FortranLib.INDEX (Characters chars, Characters value) inline static
References DotNumerics.FortranLibrary.FortranLib.INDEX(), and DotNumerics.FortranLibrary.Characters.ToString().
ADJUSTL()
static string DotNumerics.FortranLibrary.FortranLib.ADJUSTL (string s) inline static
ADJUSTL(STRING) Adjust to the left, removing leading blanks and inserting trailing blanks. Argument Type and Attributes STRING must be of type character. Class Elemental function Result Type and Attributes Character of the same length and kind type parameter as STRING. Result Value The value of the result is the same as STRING except that any leading blanks have been deleted and the same number of trailing blanks have been inserted. Examples ADJUSTL (’bWORD’) has the value ’WORDb’.
IBM XL Fortran for AIX
Parameters
s
Returns
ADJUSTR()
string DotNumerics.FortranLibrary.FortranLib.ADJUSTR (string s) inline
ADJUSTR(STRING) Adjust to the right, removing trailing blanks and inserting leading blanks. Argument Type and Attributes STRING must be of type character. Class Elemental function Result Type and Attributes Character of the same length and kind type parameter as STRING. Result Value The value of the result is the same as STRING except that any trailing blanks have been deleted and the same number of leading blanks have been inserted. Examples ADJUSTR (’WORDb’) has the value ’bWORD’.
IBM XL Fortran for AIX
Parameters
s
Returns
Substring() [1/4]
static string DotNumerics.FortranLibrary.FortranLib.Substring (string s, int startIndex, int lastIndex) inline static
Referenced by DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DHSEQR.Run(), and DotNumerics.FortranLibrary.FortranLib.Substring().
Substring() [2/4]
static string DotNumerics.FortranLibrary.FortranLib.Substring (string s, int startIndex) inline static
References DotNumerics.FortranLibrary.FortranLib.Substring().
Copy() [1/12]
static void DotNumerics.FortranLibrary.FortranLib.Copy (ref string destinationString, int startIndex, int lastIndex, string sourceString) inline static
References DotNumerics.FortranLibrary.FortranLib.Copy().
Referenced by DotNumerics.FortranLibrary.FortranLib.Copy(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFB.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRCON.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARZB.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMRQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMLQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMRZ.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMBR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR4.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAQR0.Run().
Copy() [2/12]
static void DotNumerics.FortranLibrary.FortranLib.Copy (ref string destinationString, int startIndex, int lastIndex, char source) inline static
References DotNumerics.FortranLibrary.FortranLib.Copy().
Copy() [3/12]
static void DotNumerics.FortranLibrary.FortranLib.Copy (ref string destinationString, int startIndex, string sourceString) inline static
References DotNumerics.FortranLibrary.FortranLib.Copy().
Copy() [4/12]
static void DotNumerics.FortranLibrary.FortranLib.Copy (ref string destinationString, string sourceString) inline static
References DotNumerics.FortranLibrary.FortranLib.Copy().
Substring() [3/4]
static char [] DotNumerics.FortranLibrary.FortranLib.Substring (char[] s, int startIndex, int lastIndex) inline static
Retrieves a substring . The substring starts at a specified character position and finisch a specified position.
Parameters
s
startIndex
lastIndex
Returns
Substring() [4/4]
static char [] DotNumerics.FortranLibrary.FortranLib.Substring (char[] s, int startIndex) inline static
Retrieves a substring . The substring starts at a specified character position.
Parameters
s
startIndex
Returns
References DotNumerics.FortranLibrary.FortranLib.Substring().
Copy() [5/12]
static void DotNumerics.FortranLibrary.FortranLib.Copy (char[] destinationArray, int startIndex, int lastIndex, char[] sourceArray) inline static
Copy() [6/12]
static void DotNumerics.FortranLibrary.FortranLib.Copy (char[] destinationArray, int startIndex, char[] sourceArray) inline static
References DotNumerics.FortranLibrary.FortranLib.Copy().
Copy() [7/12]
static void DotNumerics.FortranLibrary.FortranLib.Copy (Characters destination, int startIndex, int lastIndex, Characters source) inline static
References DotNumerics.FortranLibrary.Characters.CharArray, and DotNumerics.FortranLibrary.FortranLib.Copy().
Copy() [8/12]
static void DotNumerics.FortranLibrary.FortranLib.Copy (Characters destination, int startIndex, Characters source) inline static
References DotNumerics.FortranLibrary.Characters.CharArray, and DotNumerics.FortranLibrary.FortranLib.Copy().
Copy() [9/12]
static void DotNumerics.FortranLibrary.FortranLib.Copy (Characters destination, Characters source) inline static
References DotNumerics.FortranLibrary.Characters.CharArray, and DotNumerics.FortranLibrary.FortranLib.Copy().
Copy() [10/12]
static void DotNumerics.FortranLibrary.FortranLib.Copy (Characters destination, int startIndex, int lastIndex, string source) inline static
References DotNumerics.FortranLibrary.Characters.CharArray, and DotNumerics.FortranLibrary.FortranLib.Copy().
Copy() [11/12]
static void DotNumerics.FortranLibrary.FortranLib.Copy (Characters destination, int startIndex, string source) inline static
References DotNumerics.FortranLibrary.Characters.CharArray, and DotNumerics.FortranLibrary.FortranLib.Copy().
Copy() [12/12]
static void DotNumerics.FortranLibrary.FortranLib.Copy (Characters destination, string source) inline static
References DotNumerics.FortranLibrary.Characters.CharArray, and DotNumerics.FortranLibrary.FortranLib.Copy().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/FortranLib.cs