Doc: IGLib EXTENDED: NUnit.Engine.Services.ResultWriters.Tests.XmlTransformResultWriterTests Class Reference
NUnit.Engine.Services.ResultWriters.Tests.XmlTransformResultWriterTests Class Reference
Public Member Functions
void SummaryTransformTest ()
Public Member Functions inherited from NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest
void InitializeTestEngineResult ()
Additional Inherited Members
Protected Member Functions inherited from NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest
string GetLocalPath (string fileName)
Static Protected Attributes inherited from NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest
const string AssemblyName = "mock-nunit-assembly.exe"
Properties inherited from NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest
TestEngineResult EngineResult [get, private set]
string AssemblyPath [get, private set]
Member Function Documentation
SummaryTransformTest()
void NUnit.Engine.Services.ResultWriters.Tests.XmlTransformResultWriterTests.SummaryTransformTest () inline
References NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.EngineResult, NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.GetLocalPath(), NUnit.Framework.Contains.Substring(), NUnit.Framework.Assert.That(), and NUnit.Engine.TestEngineResult.Xml.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Services/ResultWriters/XmlTransformResultWriterTests.cs