Doc: IGLib EXTENDED: AForge.Imaging.Filters.BottomHat Class Reference
AForge.Imaging.Filters.BottomHat Class Reference
Bottop-hat operator from Mathematical Morphology.
Public Member Functions
BottomHat ()
Initializes a new instance of the BottomHat class.
BottomHat (short[,] se)
Initializes a new instance of the BottomHat class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlaceFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.BaseInPlaceFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
Closing closing = new Closing()
Subtract subtract = new Subtract()
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Bottop-hat operator from Mathematical Morphology.
Bottom-hat morphological operator subtracts input image from the result of morphological closing on the the input image.
Applied to binary image, the filter allows to get all object parts, which were added by closing filter, but were not removed after that due to formed connections/fillings.
The filter accepts 8 and 16 bpp grayscale images and 24 and 48 bpp color images for processing.
Sample usage:
// create filter
BottomHat filter = new BottomHat();
// apply the filter
filter.Apply(image);
Initial image:
Result image:
See also
TopHat
Constructor & Destructor Documentation
BottomHat() [1/2]
AForge.Imaging.Filters.BottomHat.BottomHat () inline
Initializes a new instance of the BottomHat class.
References AForge.Imaging.Filters.BottomHat.formatTranslations.
BottomHat() [2/2]
AForge.Imaging.Filters.BottomHat.BottomHat (short se[,]) inline
Initializes a new instance of the BottomHat class.
Parameters
se Structuring element to pass to Closing operator.
References AForge.Imaging.Filters.BottomHat.closing.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.BottomHat.ProcessFilter (UnmanagedImage image) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
Implements AForge.Imaging.Filters.BaseInPlaceFilter.
References AForge.Imaging.Filters.Closing.ApplyInPlace(), AForge.Imaging.Filters.BaseInPlaceFilter.ApplyInPlace(), AForge.Imaging.UnmanagedImage.Clone(), AForge.Imaging.Filters.BottomHat.closing, AForge.Imaging.UnmanagedImage.Dispose(), AForge.Imaging.Filters.BottomHat.subtract, and AForge.Imaging.Filters.BaseInPlaceFilter2.UnmanagedOverlayImage.
Member Data Documentation
closing
Closing AForge.Imaging.Filters.BottomHat.closing = new Closing() private
Referenced by AForge.Imaging.Filters.BottomHat.BottomHat(), and AForge.Imaging.Filters.BottomHat.ProcessFilter().
subtract
Subtract AForge.Imaging.Filters.BottomHat.subtract = new Subtract() private
Referenced by AForge.Imaging.Filters.BottomHat.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.BottomHat.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.BottomHat.BottomHat().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.BottomHat.FormatTranslations get
Format translations dictionary.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Morphology/BottomHat.cs