Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLALSA Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLALSA Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLALSA (DCOPY dcopy, DGEMM dgemm, DLALS0 dlals0, DLASDT dlasdt, XERBLA xerbla)
DLALSA ()
void Run (int ICOMPQ, int SMLSIZ, int N, int NRHS, ref double[] B, int offset_b, int LDB, ref double[] BX, int offset_bx, int LDBX, double[] U, int offset_u, int LDU, double[] VT, int offset_vt, int[] K, int offset_k, double[] DIFL, int offset_difl, double[] DIFR, int offset_difr, double[] Z, int offset_z, double[] POLES, int offset_poles, int[] GIVPTR, int offset_givptr, int[] GIVCOL, int offset_givcol, int LDGCOL, int[] PERM, int offset_perm, double[] GIVNUM, int offset_givnum, double[] C, int offset_c, double[] S, int offset_s, ref double[] WORK, int offset_work, ref int[] IWORK, int offset_iwork, ref int INFO)
Private Attributes
DCOPY _dcopy
DGEMM _dgemm
DLALS0 _dlals0
DLASDT _dlasdt
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLALSA is an itermediate step in solving the least squares problem by computing the SVD of the coefficient matrix in compact form (The singular vectors are computed as products of simple orthorgonal matrices.).
If ICOMPQ = 0, DLALSA applies the inverse of the left singular vector matrix of an upper bidiagonal matrix to the right hand side; and if ICOMPQ = 1, DLALSA applies the right singular vector matrix to the right hand side. The singular vector matrices were generated in compact form by DLALSA.
/summary>
Constructor & Destructor Documentation
DLALSA() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLALSA.DLALSA (DCOPY dcopy, DGEMM dgemm, DLALS0 dlals0, DLASDT dlasdt, XERBLA xerbla) inline
DLALSA() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLALSA.DLALSA () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLALSA.Run (int ICOMPQ, int SMLSIZ, int N, int NRHS, ref double[] B, int offset_b, int LDB, ref double[] BX, int offset_bx, int LDBX, double[] U, int offset_u, int LDU, double[] VT, int offset_vt, int[] K, int offset_k, double[] DIFL, int offset_difl, double[] DIFR, int offset_difr, double[] Z, int offset_z, double[] POLES, int offset_poles, int[] GIVPTR, int offset_givptr, int[] GIVCOL, int offset_givcol, int LDGCOL, int[] PERM, int offset_perm, double[] GIVNUM, int offset_givnum, double[] C, int offset_c, double[] S, int offset_s, ref double[] WORK, int offset_work, ref int[] IWORK, int offset_iwork, ref int INFO) inline
Purpose
DLALSA is an itermediate step in solving the least squares problem by computing the SVD of the coefficient matrix in compact form (The singular vectors are computed as products of simple orthorgonal matrices.).
If ICOMPQ = 0, DLALSA applies the inverse of the left singular vector matrix of an upper bidiagonal matrix to the right hand side; and if ICOMPQ = 1, DLALSA applies the right singular vector matrix to the right hand side. The singular vector matrices were generated in compact form by DLALSA.
/summary>
Parameters
ICOMPQ (input) INTEGER Specifies whether the left or the right singular vector matrix is involved. = 0: Left singular vector matrix = 1: Right singular vector matrix /param>
Parameters
SMLSIZ (input) INTEGER The maximum size of the subproblems at the bottom of the computation tree. /param>
Parameters
N (input) INTEGER The row and column dimensions of the upper bidiagonal matrix. /param>
Parameters
NRHS (input) INTEGER The number of columns of B and BX. NRHS must be at least 1. /param>
Parameters
B (input/output) DOUBLE PRECISION array, dimension (LDB, NRHS) On input, B contains the right hand sides of the least squares problem in rows 1 through M. On output, B contains the solution X in rows 1 through N. /param>
Parameters
LDB (input) INTEGER The leading dimension of B in the calling subprogram. LDB must be at least max(1,MAX(M, N)). /param>
Parameters
BX (output) DOUBLE PRECISION array, dimension (LDBX, NRHS) On exit, the result of applying the left or right singular vector matrix to B. /param>
Parameters
LDBX (input) INTEGER The leading dimension of BX. /param>
Parameters
U (input) DOUBLE PRECISION array, dimension (LDU, SMLSIZ). On entry, U contains the left singular vector matrices of all subproblems at the bottom level. /param>
Parameters
LDU (input) INTEGER, LDU = .GT. N. The leading dimension of arrays U, VT, DIFL, DIFR, POLES, GIVNUM, and Z. /param>
Parameters
VT (input) DOUBLE PRECISION array, dimension (LDU, SMLSIZ+1). On entry, VT' contains the right singular vector matrices of all subproblems at the bottom level. /param>
Parameters
K (input) INTEGER array, dimension (N). /param>
Parameters
DIFL (input) DOUBLE PRECISION array, dimension (LDU, NLVL). where NLVL = INT(log_2 (N/(SMLSIZ+1))) + 1. /param>
Parameters
DIFR (input) DOUBLE PRECISION array, dimension (LDU, 2 * NLVL). On entry, DIFL(*, I) and DIFR(*, 2 * I -1) record distances between singular values on the I-th level and singular values on the (I -1)-th level, and DIFR(*, 2 * I) record the normalizing factors of the right singular vectors matrices of subproblems on I-th level. /param>
Parameters
Z (input) DOUBLE PRECISION array, dimension (LDU, NLVL). On entry, Z(1, I) contains the components of the deflation- adjusted updating row vector for subproblems on the I-th level. /param>
Parameters
POLES (input) DOUBLE PRECISION array, dimension (LDU, 2 * NLVL). On entry, POLES(*, 2 * I -1: 2 * I) contains the new and old singular values involved in the secular equations on the I-th level. /param>
Parameters
GIVPTR (input) INTEGER array, dimension (N). On entry, GIVPTR(I) records the number of Givens rotations performed on the I-th problem on the computation tree. /param>
Parameters
GIVCOL (input) INTEGER array, dimension (LDGCOL, 2 * NLVL). On entry, for each I, GIVCOL(*, 2 * I - 1: 2 * I) records the locations of Givens rotations performed on the I-th level on the computation tree. /param>
Parameters
LDGCOL (input) INTEGER, LDGCOL = .GT. N. The leading dimension of arrays GIVCOL and PERM. /param>
Parameters
PERM (input) INTEGER array, dimension (LDGCOL, NLVL). On entry, PERM(*, I) records permutations done on the I-th level of the computation tree. /param>
Parameters
GIVNUM (input) DOUBLE PRECISION array, dimension (LDU, 2 * NLVL). On entry, GIVNUM(*, 2 *I -1 : 2 * I) records the C- and S- values of Givens rotations performed on the I-th level on the computation tree. /param>
Parameters
C (input) DOUBLE PRECISION array, dimension (N). On entry, if the I-th subproblem is not square, C(I) contains the C-value of a Givens rotation related to the right null space of the I-th subproblem. /param>
Parameters
S (input) DOUBLE PRECISION array, dimension (N). On entry, if the I-th subproblem is not square, S(I) contains the S-value of a Givens rotation related to the right null space of the I-th subproblem. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array. The dimension must be at least N. /param>
Parameters
IWORK (workspace) INTEGER array. The dimension must be at least 3 * N /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLALSA.ONE, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASDT.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALS0.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLALSA.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLALSD.Run().
Member Data Documentation
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLALSA._dcopy private
_dgemm
DGEMM DotNumerics.LinearAlgebra.CSLapack.DLALSA._dgemm private
_dlals0
DLALS0 DotNumerics.LinearAlgebra.CSLapack.DLALSA._dlals0 private
_dlasdt
DLASDT DotNumerics.LinearAlgebra.CSLapack.DLALSA._dlasdt private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLALSA._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLALSA.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLALSA.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLALSA.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLALSA.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlalsa.cs