Doc: IGLib EXTENDED: AForge.Neuro.Network Class Reference
AForge.Neuro.Network Class Reference
Base neural network class
Public Member Functions
virtual double[] Compute (double[] input)
Compute output vector of the network
virtual void Randomize ()
Randomize layers of the network
virtual double[] Compute (double[] input)
Compute output vector of the network
virtual void Randomize ()
Randomize layers of the network
virtual double[] Compute (double[] input)
Compute output vector of the network.
virtual void Randomize ()
Randomize layers of the network.
void Save (string fileName)
Save network to specified file.
void Save (Stream stream)
Save network to specified file.
Static Public Member Functions
static Network Load (string fileName)
Load network from specified file.
static Network Load (Stream stream)
Load network from specified file.
Protected Member Functions
Network (int inputsCount, int layersCount)
Initializes a new instance of the Network class
Network (int inputsCount, int layersCount)
Initializes a new instance of the Network class
Network (int inputsCount, int layersCount)
Initializes a new instance of the Network class.
Protected Attributes
int inputsCount
Network's inputs count
int layersCount
Network's layers count
Layer[] layers
Network's layers
double[] output
Network's output vector
Properties
int InputsCount [get]
Network's inputs count
int LayersCount [get]
Network's layers count
double[] Output [get]
Network's output vector
Layer this[int index] [get]
Network's layers accessor
Layer[] Layers [get]
Network's layers.
Detailed Description
Base neural network class
Base neural network class.
This is a base neural netwok class, which represents collection of neuron's layers.
Constructor & Destructor Documentation
Network() [1/3]
AForge.Neuro.Network.Network (int inputsCount, int layersCount) inline protected
Initializes a new instance of the Network class
Parameters
inputsCount Network's inputs count
layersCount Network's layers count
Protected constructor, which initializes inputsCount, layersCount and layers members.
References AForge.Neuro.Network.inputsCount, AForge.Neuro.Network.layers, and AForge.Neuro.Network.layersCount.
Referenced by AForge.Neuro.Network.Load().
Network() [2/3]
AForge.Neuro.Network.Network (int inputsCount, int layersCount) inline protected
Initializes a new instance of the Network class
Parameters
inputsCount Network's inputs count
layersCount Network's layers count
Protected constructor, which initializes inputsCount, layersCount and layers members.
References AForge.Neuro.Network.inputsCount, AForge.Neuro.Network.layers, and AForge.Neuro.Network.layersCount.
Network() [3/3]
AForge.Neuro.Network.Network (int inputsCount, int layersCount) inline protected
Initializes a new instance of the Network class.
Parameters
inputsCount Network's inputs count.
layersCount Network's layers count.
Protected constructor, which initializes inputsCount, layersCount and layers members.
References AForge.Neuro.Network.inputsCount, and AForge.Neuro.Network.layersCount.
Member Function Documentation
Compute() [1/3]
virtual double [] AForge.Neuro.Network.Compute (double[] input) inline virtual
Compute output vector of the network
Parameters
input Input vector
Returns
Returns network's output vector
The actual network's output vecor is determined by inherited class and it represents an output vector of the last layer of the network. The output vector is also stored in Output property.
References AForge.Neuro.Layer.Compute(), AForge.Neuro.Network.layers, and AForge.Neuro.Network.output.
Referenced by IG.Neural.NeuralApproximatorAforge.CalculateOutput(), AForge.Neuro.Learning.DeltaRuleLearning.Run(), AForge.Neuro.Learning.PerceptronLearning.Run(), AForge.Neuro.Learning.ElasticNetworkLearning.Run(), AForge.Neuro.Learning.BackPropagationLearning.Run(), AForge.Neuro.Learning.SOMLearning.Run(), AForge.Neuro.Learning.ResilientBackpropagationLearning.Run(), AForge.Neuro.Learning.ResilientBackpropagationLearning.RunEpoch(), Approximation.MainForm.SearchSolution(), Approximation.MainFormNeuralApproximation.SearchSolution(), TimeSeries.MainForm.SearchSolution(), and SOMOrganizing.MainForm.UpdateMap().
Randomize() [1/3]
virtual void AForge.Neuro.Network.Randomize () inline virtual
Randomize layers of the network
Randomizes network's layers by calling Layer.Randomize method of each layer.
References AForge.Neuro.Network.layers, and AForge.Neuro.Layer.Randomize().
Referenced by IG.Neural.NeuralApproximatorAforge.CreateNetwork(), Color.MainForm.RandomizeNetwork(), and IG.Neural.NeuralApproximatorAforge.ResetNetwork().
Compute() [2/3]
virtual double [] AForge.Neuro.Network.Compute (double[] input) inline virtual
Compute output vector of the network
Parameters
input Input vector
Returns
Returns network's output vector
The actual network's output vecor is determined by inherited class and it represents an output vector of the last layer of the network. The output vector is also stored in Output property.
References AForge.Neuro.Layer.Compute(), AForge.Neuro.Network.layers, and AForge.Neuro.Network.output.
Randomize() [2/3]
virtual void AForge.Neuro.Network.Randomize () inline virtual
Randomize layers of the network
Randomizes network's layers by calling Layer.Randomize method of each layer.
References AForge.Neuro.Network.layers, and AForge.Neuro.Layer.Randomize().
Compute() [3/3]
virtual double [] AForge.Neuro.Network.Compute (double[] input) inline virtual
Compute output vector of the network.
Parameters
input Input vector.
Returns
Returns network's output vector.
The actual network's output vecor is determined by layers, which comprise the layer - represents an output vector of the last layer of the network. The output vector is also stored in Output property.
<note>The method may be called safely from multiple threads to compute network's output value for the specified input values. However, the value of Output property in multi-threaded environment is not predictable, since it may hold network's output computed from any of the caller threads. Multi-threaded access to the method is useful in those cases when it is required to improve performance by utilizing several threads and the computation is based on the immediate return value of the method, but not on network's output property.</note>
References AForge.Neuro.Layer.Compute(), AForge.Neuro.Network.layers, and AForge.Neuro.Network.output.
Randomize() [3/3]
virtual void AForge.Neuro.Network.Randomize () inline virtual
Randomize layers of the network.
Randomizes network's layers by calling Layer.Randomize method of each layer.
References AForge.Neuro.Network.layers, and AForge.Neuro.Layer.Randomize().
Save() [1/2]
void AForge.Neuro.Network.Save (string fileName) inline
Save network to specified file.
Parameters
fileName File name to save network into.
The neural network is saved using .NET serialization (binary formatter is used).
Referenced by IG.Neural.NeuralApproximatorAforge.SaveNetworkSpecific().
Save() [2/2]
void AForge.Neuro.Network.Save (Stream stream) inline
Save network to specified file.
Parameters
stream Stream to save network into.
The neural network is saved using .NET serialization (binary formatter is used).
Load() [1/2]
static Network AForge.Neuro.Network.Load (string fileName) inline static
Load network from specified file.
Parameters
fileName File name to load network from.
Returns
Returns instance of Network class with all properties initialized from file.
Neural network is loaded from file using .NET serialization (binary formater is used).
Referenced by IG.Neural.NeuralApproximatorAforge.LoadNetworkSpecific().
Load() [2/2]
static Network AForge.Neuro.Network.Load (Stream stream) inline static
Load network from specified file.
Parameters
stream Stream to load network from.
Returns
Returns instance of Network class with all properties initialized from file.
Neural network is loaded from file using .NET serialization (binary formater is used).
References AForge.Neuro.Network.Network().
Member Data Documentation
inputsCount
int AForge.Neuro.Network.inputsCount protected
Network's inputs count
Network's inputs count.
Referenced by AForge.Neuro.ActivationNetwork.ActivationNetwork(), AForge.Neuro.DistanceNetwork.DistanceNetwork(), and AForge.Neuro.Network.Network().
layersCount
int AForge.Neuro.Network.layersCount protected
Network's layers count
Network's layers count.
Referenced by AForge.Neuro.ActivationNetwork.ActivationNetwork(), and AForge.Neuro.Network.Network().
layers
Layer [] AForge.Neuro.Network.layers protected
Network's layers
Network's layers.
Referenced by AForge.Neuro.ActivationNetwork.ActivationNetwork(), AForge.Neuro.Network.Compute(), AForge.Neuro.DistanceNetwork.DistanceNetwork(), AForge.Neuro.Network.Network(), AForge.Neuro.Network.Randomize(), and AForge.Neuro.ActivationNetwork.SetActivationFunction().
output
double [] AForge.Neuro.Network.output protected
Network's output vector
Network's output vector.
Referenced by AForge.Neuro.Network.Compute(), and AForge.Neuro.DistanceNetwork.GetWinner().
Property Documentation
InputsCount
int AForge.Neuro.Network.InputsCount get
Network's inputs count
Network's inputs count.
Referenced by AForge.Neuro.Learning.EvolutionaryLearning.RunEpoch().
LayersCount
int AForge.Neuro.Network.LayersCount get
Network's layers count
Referenced by AForge.Neuro.Learning.BackPropagationLearning.BackPropagationLearning(), AForge.Neuro.Learning.BackPropagationLearning.CalculateError(), AForge.Neuro.Learning.BackPropagationLearning.CalculateUpdates(), AForge.Neuro.Learning.DeltaRuleLearning.DeltaRuleLearning(), AForge.Neuro.Learning.PerceptronLearning.PerceptronLearning(), and AForge.Neuro.Learning.BackPropagationLearning.UpdateNetwork().
Output
double [] AForge.Neuro.Network.Output get
Network's output vector
Network's output vector.
The calculation way of network's output vector is determined by inherited class.
The calculation way of network's output vector is determined by layers, which comprise the network.
<note>The property is not initialized (equals to null) until Compute method is called.</note>
this[int index]
Layer AForge.Neuro.Network.this[int index] get
Network's layers accessor
Parameters
index Layer index
Allows to access network's layer.
Layers
Layer [] AForge.Neuro.Network.Layers get
Network's layers.
Referenced by AForge.Neuro.Learning.BackPropagationLearning.BackPropagationLearning(), AForge.Neuro.Learning.BackPropagationLearning.CalculateError(), AForge.Neuro.Learning.ResilientBackpropagationLearning.CalculateError(), AForge.Neuro.Learning.ResilientBackpropagationLearning.CalculateGradient(), AForge.Neuro.Learning.EvolutionaryLearning.CalculateNetworkSize(), AForge.Neuro.Learning.BackPropagationLearning.CalculateUpdates(), AForge.Neuro.Learning.DeltaRuleLearning.DeltaRuleLearning(), AForge.Neuro.Learning.ElasticNetworkLearning.ElasticNetworkLearning(), AForge.Neuro.Learning.PerceptronLearning.PerceptronLearning(), AForge.Neuro.Learning.ResilientBackpropagationLearning.ResilientBackpropagationLearning(), AForge.Neuro.Learning.DeltaRuleLearning.Run(), AForge.Neuro.Learning.PerceptronLearning.Run(), AForge.Neuro.Learning.ElasticNetworkLearning.Run(), AForge.Neuro.Learning.SOMLearning.Run(), AForge.Neuro.Learning.EvolutionaryLearning.RunEpoch(), TSP.MainForm.SearchSolution(), Classifier.MainForm.SearchSolution(), AForge.Neuro.Learning.SOMLearning.SOMLearning(), Color.MainForm.UpdateMap(), SOMOrganizing.MainForm.UpdateMap(), AForge.Neuro.Learning.ResilientBackpropagationLearning.UpdateNetwork(), and AForge.Neuro.Learning.BackPropagationLearning.UpdateNetwork().
The documentation for this class was generated from the following file:
shelldev/lib/external/neuralnetworks/neuro_src/Sources/Backup/Neuro/Networks/Network.cs