Doc: IGLib EXTENDED: NeuronDotNet.Core.IInitializer Interface Reference
NeuronDotNet.Core.IInitializer Interface Reference
Initializer interface. An initializer should define initialization methods for all concrete initializable layers and connectors.
Public Member Functions
void Initialize (ActivationLayer activationLayer)
Initializes bias values of activation neurons in an activation layer.
void Initialize (BackpropagationConnector connector)
Initializes weights of all backpropagation synapses in a backpropagation connector.
void Initialize (KohonenConnector connector)
Initializes weights of all spatial synapses in a Kohonen connector.
Detailed Description
Initializer interface. An initializer should define initialization methods for all concrete initializable layers and connectors.
Member Function Documentation
Initialize() [1/3]
void NeuronDotNet.Core.IInitializer.Initialize (ActivationLayer activationLayer)
Initializes bias values of activation neurons in an activation layer.
Parameters
activationLayer The activation layer to initialize
Exceptions
System.ArgumentNullException If activationLayer is null
Implemented in NeuronDotNet.Core.Initializers.RandomFunction, NeuronDotNet.Core.Initializers.NguyenWidrowFunction, NeuronDotNet.Core.Initializers.ConstantFunction, and NeuronDotNet.Core.Initializers.NormalizedRandomFunction.
Referenced by NeuronDotNet.Core.Backpropagation.ActivationLayer.Initialize(), NeuronDotNet.Core.SOM.KohonenConnector.Initialize(), and NeuronDotNet.Core.Backpropagation.BackpropagationConnector.Initialize().
Initialize() [2/3]
void NeuronDotNet.Core.IInitializer.Initialize (BackpropagationConnector connector)
Initializes weights of all backpropagation synapses in a backpropagation connector.
Parameters
connector The backpropagation connector to initialize.
Exceptions
System.ArgumentNullException If connector is null
Implemented in NeuronDotNet.Core.Initializers.RandomFunction, NeuronDotNet.Core.Initializers.NguyenWidrowFunction, NeuronDotNet.Core.Initializers.ConstantFunction, and NeuronDotNet.Core.Initializers.NormalizedRandomFunction.
Initialize() [3/3]
void NeuronDotNet.Core.IInitializer.Initialize (KohonenConnector connector)
Initializes weights of all spatial synapses in a Kohonen connector.
Parameters
connector The Kohonen connector to initialize.
Exceptions
System.ArgumentNullException If connector is null
Implemented in NeuronDotNet.Core.Initializers.RandomFunction, NeuronDotNet.Core.Initializers.NguyenWidrowFunction, NeuronDotNet.Core.Initializers.ConstantFunction, and NeuronDotNet.Core.Initializers.NormalizedRandomFunction.
The documentation for this interface was generated from the following file:
shelldev/lib/externalextended/NeuronDotNetGPL/source/Core/IInitializer.cs