Doc: IGLib EXTENDED: AForge.Imaging.Filters.Shrink Class Reference
AForge.Imaging.Filters.Shrink Class Reference
Shrink an image by removing specified color from its boundaries.
Public Member Functions
Shrink ()
Initializes a new instance of the Shrink class.
Shrink (Color colorToRemove)
Initializes a new instance of the Shrink class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseTransformationFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
Protected Member Functions
override System.Drawing.Size CalculateNewImageSize (UnmanagedImage sourceData)
Calculates new image size.
override unsafe void ProcessFilter (UnmanagedImage sourceData, UnmanagedImage destinationData)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Color ColorToRemove [get, set]
Color to remove from boundaries.
Properties inherited from AForge.Imaging.Filters.BaseTransformationFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
Color colorToRemove = Color.FromArgb(0, 0, 0)
int minX
int minY
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Shrink an image by removing specified color from its boundaries.
Removes pixels with specified color from image boundaries making the image smaller in size.
The filter accepts 8 bpp grayscale and 24 bpp color images for processing.
Sample usage:
// create filter
Shrink filter = new Shrink(Color.Black);
// apply the filter
Bitmap newImage = filter.Apply(image);
Initial image:
Result image:
Constructor & Destructor Documentation
Shrink() [1/2]
AForge.Imaging.Filters.Shrink.Shrink () inline
Initializes a new instance of the Shrink class.
References AForge.Imaging.Filters.Shrink.formatTranslations.
Shrink() [2/2]
AForge.Imaging.Filters.Shrink.Shrink (Color colorToRemove) inline
Initializes a new instance of the Shrink class.
Parameters
colorToRemove Color to remove from boundaries.
References AForge.Imaging.Filters.Shrink.colorToRemove.
Member Function Documentation
CalculateNewImageSize()
override System.Drawing.Size AForge.Imaging.Filters.Shrink.CalculateNewImageSize (UnmanagedImage sourceData) inline protected virtual
Calculates new image size.
Parameters
sourceData Source image data.
Returns
New image size - size of the destination image.
Implements AForge.Imaging.Filters.BaseTransformationFilter.
References AForge.Imaging.RGB.B, AForge.Imaging.Filters.Shrink.colorToRemove, AForge.Imaging.RGB.G, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.Filters.Shrink.minX, AForge.Imaging.Filters.Shrink.minY, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, AForge.Imaging.Size, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
ProcessFilter()
override unsafe void AForge.Imaging.Filters.Shrink.ProcessFilter (UnmanagedImage sourceData, UnmanagedImage destinationData) inline protected virtual
Process the filter on the specified image.
Parameters
sourceData Source image data.
destinationData Destination image data.
Implements AForge.Imaging.Filters.BaseTransformationFilter.
References AForge.SystemTools.CopyUnmanagedMemory(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.Filters.Shrink.minX, AForge.Imaging.Filters.Shrink.minY, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
Member Data Documentation
colorToRemove
Color AForge.Imaging.Filters.Shrink.colorToRemove = Color.FromArgb(0, 0, 0) private
Referenced by AForge.Imaging.Filters.Shrink.CalculateNewImageSize(), and AForge.Imaging.Filters.Shrink.Shrink().
minX
int AForge.Imaging.Filters.Shrink.minX private
Referenced by AForge.Imaging.Filters.Shrink.CalculateNewImageSize(), and AForge.Imaging.Filters.Shrink.ProcessFilter().
minY
int AForge.Imaging.Filters.Shrink.minY private
Referenced by AForge.Imaging.Filters.Shrink.CalculateNewImageSize(), and AForge.Imaging.Filters.Shrink.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.Shrink.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.Shrink.Shrink().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.Shrink.FormatTranslations get
Format translations dictionary.
ColorToRemove
Color AForge.Imaging.Filters.Shrink.ColorToRemove get set
Color to remove from boundaries.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Transform/Shrink.cs