Doc: IGLib EXTENDED: Optimization1D.MainForm Class Reference
Optimization1D.MainForm Class Reference
Summary description for MainForm.
Public Member Functions
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
delegate void SetTextCallback (System.Windows.Forms.Control control, string text)
void SetText (System.Windows.Forms.Control control, string text)
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void UpdateChart ()
void minXBox_TextChanged (object sender, System.EventArgs e)
void maxXBox_TextChanged (object sender, System.EventArgs e)
delegate void EnableCallback (bool enable)
void EnableControls (bool enable)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
Static Private Member Functions
static void Main ()
The main entry point for the application.
Private Attributes
AForge.Controls.Chart chart
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.Label label1
System.Windows.Forms.TextBox minXBox
System.Windows.Forms.TextBox maxXBox
System.Windows.Forms.Label label2
System.ComponentModel.Container components = null
Required designer variable.
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.Label label3
System.Windows.Forms.TextBox populationSizeBox
System.Windows.Forms.Label label4
System.Windows.Forms.TextBox chromosomeLengthBox
System.Windows.Forms.CheckBox onlyBestCheck
System.Windows.Forms.Label label5
System.Windows.Forms.TextBox iterationsBox
System.Windows.Forms.Label label6
System.Windows.Forms.Button startButton
System.Windows.Forms.Button stopButton
System.Windows.Forms.Label label7
System.Windows.Forms.ComboBox selectionBox
System.Windows.Forms.Label label8
System.Windows.Forms.ComboBox modeBox
System.Windows.Forms.GroupBox groupBox3
System.Windows.Forms.Label label9
System.Windows.Forms.TextBox currentIterationBox
System.Windows.Forms.Label label10
System.Windows.Forms.TextBox currentValueBox
UserFunction userFunction = new UserFunction()
int populationSize = 40
int chromosomeLength = 32
int iterations = 100
int selectionMethod = 0
int optimizationMode = 0
bool showOnlyBest = false
Thread workerThread = null
volatile bool needToStop = false
Detailed Description
Summary description for MainForm.
Constructor & Destructor Documentation
MainForm()
Optimization1D.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), Optimization1D.MainForm.chart, Optimization1D.MainForm.InitializeComponent(), AForge.Range.Max, Optimization1D.MainForm.maxXBox, AForge.Range.Min, Optimization1D.MainForm.minXBox, Optimization1D.MainForm.modeBox, Optimization1D.MainForm.optimizationMode, AForge.Genetic.OptimizationFunction1D.Range, Optimization1D.MainForm.selectionBox, Optimization1D.MainForm.selectionMethod, Optimization1D.MainForm.UpdateChart(), Optimization1D.MainForm.UpdateSettings(), and Optimization1D.MainForm.userFunction.
Referenced by Optimization1D.MainForm.Main().
Member Function Documentation
Dispose()
override void Optimization1D.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References Optimization1D.MainForm.components.
InitializeComponent()
void Optimization1D.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by Optimization1D.MainForm.MainForm().
Main()
static void Optimization1D.MainForm.Main () inline static private
The main entry point for the application.
References Optimization1D.MainForm.MainForm().
SetTextCallback()
delegate void Optimization1D.MainForm.SetTextCallback (System.Windows.Forms.Control control, string text) private
Referenced by Optimization1D.MainForm.SetText().
SetText()
void Optimization1D.MainForm.SetText (System.Windows.Forms.Control control, string text) inline private
References Optimization1D.MainForm.SetTextCallback().
Referenced by Optimization1D.MainForm.SearchSolution().
MainForm_Closing()
void Optimization1D.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References Optimization1D.MainForm.needToStop, and Optimization1D.MainForm.workerThread.
UpdateSettings()
void Optimization1D.MainForm.UpdateSettings () inline private
References Optimization1D.MainForm.chromosomeLength, Optimization1D.MainForm.chromosomeLengthBox, Optimization1D.MainForm.iterations, Optimization1D.MainForm.iterationsBox, Optimization1D.MainForm.populationSize, and Optimization1D.MainForm.populationSizeBox.
Referenced by Optimization1D.MainForm.MainForm(), and Optimization1D.MainForm.startButton_Click().
UpdateChart()
void Optimization1D.MainForm.UpdateChart () inline private
References Optimization1D.MainForm.chart, AForge.DoubleRange.Length, AForge.Range.Length, AForge.Range.Min, Optimization1D.UserFunction.OptimizationFunction(), AForge.Genetic.OptimizationFunction1D.Range, AForge.Controls.Chart.RangeX, AForge.Controls.Chart.UpdateDataSeries(), and Optimization1D.MainForm.userFunction.
Referenced by Optimization1D.MainForm.MainForm(), Optimization1D.MainForm.maxXBox_TextChanged(), and Optimization1D.MainForm.minXBox_TextChanged().
minXBox_TextChanged()
void Optimization1D.MainForm.minXBox_TextChanged (object sender, System.EventArgs e) inline private
References AForge.Range.Max, Optimization1D.MainForm.minXBox, AForge.Genetic.OptimizationFunction1D.Range, Optimization1D.MainForm.UpdateChart(), and Optimization1D.MainForm.userFunction.
maxXBox_TextChanged()
void Optimization1D.MainForm.maxXBox_TextChanged (object sender, System.EventArgs e) inline private
References Optimization1D.MainForm.maxXBox, AForge.Range.Min, AForge.Genetic.OptimizationFunction1D.Range, Optimization1D.MainForm.UpdateChart(), and Optimization1D.MainForm.userFunction.
EnableCallback()
delegate void Optimization1D.MainForm.EnableCallback (bool enable) private
Referenced by Optimization1D.MainForm.EnableControls().
EnableControls()
void Optimization1D.MainForm.EnableControls (bool enable) inline private
References Optimization1D.MainForm.chromosomeLengthBox, Optimization1D.MainForm.EnableCallback(), Optimization1D.MainForm.iterationsBox, Optimization1D.MainForm.maxXBox, Optimization1D.MainForm.minXBox, Optimization1D.MainForm.modeBox, Optimization1D.MainForm.onlyBestCheck, Optimization1D.MainForm.populationSizeBox, Optimization1D.MainForm.selectionBox, Optimization1D.MainForm.startButton, and Optimization1D.MainForm.stopButton.
Referenced by Optimization1D.MainForm.SearchSolution(), and Optimization1D.MainForm.startButton_Click().
startButton_Click()
void Optimization1D.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References Optimization1D.MainForm.chromosomeLength, Optimization1D.MainForm.chromosomeLengthBox, Optimization1D.MainForm.EnableControls(), Optimization1D.MainForm.iterations, Optimization1D.MainForm.iterationsBox, Optimization1D.MainForm.modeBox, Optimization1D.MainForm.needToStop, Optimization1D.MainForm.onlyBestCheck, Optimization1D.MainForm.optimizationMode, Optimization1D.MainForm.populationSize, Optimization1D.MainForm.populationSizeBox, Optimization1D.MainForm.SearchSolution(), Optimization1D.MainForm.selectionBox, Optimization1D.MainForm.selectionMethod, Optimization1D.MainForm.showOnlyBest, Optimization1D.MainForm.UpdateSettings(), and Optimization1D.MainForm.workerThread.
stopButton_Click()
void Optimization1D.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References Optimization1D.MainForm.needToStop, and Optimization1D.MainForm.workerThread.
SearchSolution()
void Optimization1D.MainForm.SearchSolution () inline private
References AForge.Genetic.Population.BestChromosome, Optimization1D.MainForm.chart, Optimization1D.MainForm.chromosomeLength, Optimization1D.MainForm.currentIterationBox, Optimization1D.MainForm.currentValueBox, Optimization1D.MainForm.EnableControls(), Optimization1D.MainForm.iterations, AForge.Genetic.OptimizationFunction1D.Mode, Optimization1D.MainForm.needToStop, Optimization1D.UserFunction.OptimizationFunction(), Optimization1D.MainForm.optimizationMode, Optimization1D.MainForm.populationSize, AForge.Genetic.Population.RunEpoch(), Optimization1D.MainForm.selectionMethod, Optimization1D.MainForm.SetText(), Optimization1D.MainForm.showOnlyBest, AForge.Genetic.OptimizationFunction1D.Translate(), AForge.Controls.Chart.UpdateDataSeries(), and Optimization1D.MainForm.userFunction.
Referenced by Optimization1D.MainForm.startButton_Click().
Member Data Documentation
chart
AForge.Controls.Chart Optimization1D.MainForm.chart private
Referenced by Optimization1D.MainForm.MainForm(), Optimization1D.MainForm.SearchSolution(), and Optimization1D.MainForm.UpdateChart().
groupBox1
System.Windows.Forms.GroupBox Optimization1D.MainForm.groupBox1 private
label1
System.Windows.Forms.Label Optimization1D.MainForm.label1 private
minXBox
System.Windows.Forms.TextBox Optimization1D.MainForm.minXBox private
Referenced by Optimization1D.MainForm.EnableControls(), Optimization1D.MainForm.MainForm(), and Optimization1D.MainForm.minXBox_TextChanged().
maxXBox
System.Windows.Forms.TextBox Optimization1D.MainForm.maxXBox private
Referenced by Optimization1D.MainForm.EnableControls(), Optimization1D.MainForm.MainForm(), and Optimization1D.MainForm.maxXBox_TextChanged().
label2
System.Windows.Forms.Label Optimization1D.MainForm.label2 private
components
System.ComponentModel.Container Optimization1D.MainForm.components = null private
Required designer variable.
Referenced by Optimization1D.MainForm.Dispose().
groupBox2
System.Windows.Forms.GroupBox Optimization1D.MainForm.groupBox2 private
label3
System.Windows.Forms.Label Optimization1D.MainForm.label3 private
populationSizeBox
System.Windows.Forms.TextBox Optimization1D.MainForm.populationSizeBox private
Referenced by Optimization1D.MainForm.EnableControls(), Optimization1D.MainForm.startButton_Click(), and Optimization1D.MainForm.UpdateSettings().
label4
System.Windows.Forms.Label Optimization1D.MainForm.label4 private
chromosomeLengthBox
System.Windows.Forms.TextBox Optimization1D.MainForm.chromosomeLengthBox private
Referenced by Optimization1D.MainForm.EnableControls(), Optimization1D.MainForm.startButton_Click(), and Optimization1D.MainForm.UpdateSettings().
onlyBestCheck
System.Windows.Forms.CheckBox Optimization1D.MainForm.onlyBestCheck private
Referenced by Optimization1D.MainForm.EnableControls(), and Optimization1D.MainForm.startButton_Click().
label5
System.Windows.Forms.Label Optimization1D.MainForm.label5 private
iterationsBox
System.Windows.Forms.TextBox Optimization1D.MainForm.iterationsBox private
Referenced by Optimization1D.MainForm.EnableControls(), Optimization1D.MainForm.startButton_Click(), and Optimization1D.MainForm.UpdateSettings().
label6
System.Windows.Forms.Label Optimization1D.MainForm.label6 private
startButton
System.Windows.Forms.Button Optimization1D.MainForm.startButton private
Referenced by Optimization1D.MainForm.EnableControls().
stopButton
System.Windows.Forms.Button Optimization1D.MainForm.stopButton private
Referenced by Optimization1D.MainForm.EnableControls().
label7
System.Windows.Forms.Label Optimization1D.MainForm.label7 private
selectionBox
System.Windows.Forms.ComboBox Optimization1D.MainForm.selectionBox private
Referenced by Optimization1D.MainForm.EnableControls(), Optimization1D.MainForm.MainForm(), and Optimization1D.MainForm.startButton_Click().
label8
System.Windows.Forms.Label Optimization1D.MainForm.label8 private
modeBox
System.Windows.Forms.ComboBox Optimization1D.MainForm.modeBox private
Referenced by Optimization1D.MainForm.EnableControls(), Optimization1D.MainForm.MainForm(), and Optimization1D.MainForm.startButton_Click().
groupBox3
System.Windows.Forms.GroupBox Optimization1D.MainForm.groupBox3 private
label9
System.Windows.Forms.Label Optimization1D.MainForm.label9 private
currentIterationBox
System.Windows.Forms.TextBox Optimization1D.MainForm.currentIterationBox private
Referenced by Optimization1D.MainForm.SearchSolution().
label10
System.Windows.Forms.Label Optimization1D.MainForm.label10 private
currentValueBox
System.Windows.Forms.TextBox Optimization1D.MainForm.currentValueBox private
Referenced by Optimization1D.MainForm.SearchSolution().
userFunction
UserFunction Optimization1D.MainForm.userFunction = new UserFunction() private
Referenced by Optimization1D.MainForm.MainForm(), Optimization1D.MainForm.maxXBox_TextChanged(), Optimization1D.MainForm.minXBox_TextChanged(), Optimization1D.MainForm.SearchSolution(), and Optimization1D.MainForm.UpdateChart().
populationSize
int Optimization1D.MainForm.populationSize = 40 private
Referenced by Optimization1D.MainForm.SearchSolution(), Optimization1D.MainForm.startButton_Click(), and Optimization1D.MainForm.UpdateSettings().
chromosomeLength
int Optimization1D.MainForm.chromosomeLength = 32 private
Referenced by Optimization1D.MainForm.SearchSolution(), Optimization1D.MainForm.startButton_Click(), and Optimization1D.MainForm.UpdateSettings().
iterations
int Optimization1D.MainForm.iterations = 100 private
Referenced by Optimization1D.MainForm.SearchSolution(), Optimization1D.MainForm.startButton_Click(), and Optimization1D.MainForm.UpdateSettings().
selectionMethod
int Optimization1D.MainForm.selectionMethod = 0 private
Referenced by Optimization1D.MainForm.MainForm(), Optimization1D.MainForm.SearchSolution(), and Optimization1D.MainForm.startButton_Click().
optimizationMode
int Optimization1D.MainForm.optimizationMode = 0 private
Referenced by Optimization1D.MainForm.MainForm(), Optimization1D.MainForm.SearchSolution(), and Optimization1D.MainForm.startButton_Click().
showOnlyBest
bool Optimization1D.MainForm.showOnlyBest = false private
Referenced by Optimization1D.MainForm.SearchSolution(), and Optimization1D.MainForm.startButton_Click().
workerThread
Thread Optimization1D.MainForm.workerThread = null private
Referenced by Optimization1D.MainForm.MainForm_Closing(), Optimization1D.MainForm.startButton_Click(), and Optimization1D.MainForm.stopButton_Click().
needToStop
volatile bool Optimization1D.MainForm.needToStop = false private
Referenced by Optimization1D.MainForm.MainForm_Closing(), Optimization1D.MainForm.SearchSolution(), Optimization1D.MainForm.startButton_Click(), and Optimization1D.MainForm.stopButton_Click().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Samples/Genetic/Optimization1D/MainForm.cs