Doc: IGLib EXTENDED: alglib.fbls Class Reference
alglib.fbls Class Reference
Classes
class fblslincgstate
Static Public Member Functions
static void fblscholeskysolve (double[,] cha, double sqrtscalea, int n, bool isupper, ref double[] xb, ref double[] tmp)
static void fblssolvecgx (double[,] a, int m, int n, double alpha, double[] b, ref double[] x, ref double[] buf)
static void fblscgcreate (double[] x, double[] b, int n, fblslincgstate state)
static bool fblscgiteration (fblslincgstate state)
static void fblssolvels (ref double[,] a, ref double[] b, int m, int n, ref double[] tmp0, ref double[] tmp1, ref double[] tmp2)
static void fblscholeskysolve (double[,] cha, double sqrtscalea, int n, bool isupper, ref double[] xb, ref double[] tmp)
static void fblssolvecgx (double[,] a, int m, int n, double alpha, double[] b, ref double[] x, ref double[] buf)
static void fblscgcreate (double[] x, double[] b, int n, fblslincgstate state)
static bool fblscgiteration (fblslincgstate state)
static void fblssolvels (ref double[,] a, ref double[] b, int m, int n, ref double[] tmp0, ref double[] tmp1, ref double[] tmp2)
Member Function Documentation
fblscholeskysolve() [1/2]
static void alglib.fbls.fblscholeskysolve (double cha[,], double sqrtscalea, int n, bool isupper, ref double[] xb, ref double[] tmp) inline static
Referenced by alglib.cqmodels.cqmconstrainedoptimum(), and alglib.cqmodels.cqmsolveea().
fblssolvecgx() [1/2]
static void alglib.fbls.fblssolvecgx (double a[,], int m, int n, double alpha, double[] b, ref double[] x, ref double[] buf) inline static
Referenced by alglib.nleq.nleqiteration(), and alglib.testfblsunit.testfbls().
fblscgcreate() [1/2]
static void alglib.fbls.fblscgcreate (double[] x, double[] b, int n, fblslincgstate state) inline static
Referenced by alglib.testfblsunit.testfbls().
fblscgiteration() [1/2]
static bool alglib.fbls.fblscgiteration (fblslincgstate state) inline static
Referenced by alglib.testfblsunit.testfbls().
fblssolvels() [1/2]
static void alglib.fbls.fblssolvels (ref double a[,], ref double[] b, int m, int n, ref double[] tmp0, ref double[] tmp1, ref double[] tmp2) inline static
Referenced by alglib.rbf.buildrbfmodellsqr(), and alglib.testfblsunit.testfbls().
fblscholeskysolve() [2/2]
static void alglib.fbls.fblscholeskysolve (double cha[,], double sqrtscalea, int n, bool isupper, ref double[] xb, ref double[] tmp) inline static
fblssolvecgx() [2/2]
static void alglib.fbls.fblssolvecgx (double a[,], int m, int n, double alpha, double[] b, ref double[] x, ref double[] buf) inline static
fblscgcreate() [2/2]
static void alglib.fbls.fblscgcreate (double[] x, double[] b, int n, fblslincgstate state) inline static
fblscgiteration() [2/2]
static bool alglib.fbls.fblscgiteration (fblslincgstate state) inline static
fblssolvels() [2/2]
static void alglib.fbls.fblssolvels (ref double a[,], ref double[] b, int m, int n, ref double[] tmp0, ref double[] tmp1, ref double[] tmp2) inline static
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/linalg.cs