Doc: IGLib EXTENDED: alglib.gkq Class Reference
alglib.gkq Class Reference
Static Public Member Functions
static void gkqgeneraterec (double[] alpha, double[] beta, double mu0, int n, ref int info, ref double[] x, ref double[] wkronrod, ref double[] wgauss)
static void gkqgenerategausslegendre (int n, ref int info, ref double[] x, ref double[] wkronrod, ref double[] wgauss)
static void gkqgenerategaussjacobi (int n, double alpha, double beta, ref int info, ref double[] x, ref double[] wkronrod, ref double[] wgauss)
static void gkqlegendrecalc (int n, ref int info, ref double[] x, ref double[] wkronrod, ref double[] wgauss)
static void gkqlegendretbl (int n, ref double[] x, ref double[] wkronrod, ref double[] wgauss, ref double eps)
static void gkqgeneraterec (double[] alpha, double[] beta, double mu0, int n, ref int info, ref double[] x, ref double[] wkronrod, ref double[] wgauss)
static void gkqgenerategausslegendre (int n, ref int info, ref double[] x, ref double[] wkronrod, ref double[] wgauss)
static void gkqgenerategaussjacobi (int n, double alpha, double beta, ref int info, ref double[] x, ref double[] wkronrod, ref double[] wgauss)
static void gkqlegendrecalc (int n, ref int info, ref double[] x, ref double[] wkronrod, ref double[] wgauss)
static void gkqlegendretbl (int n, ref double[] x, ref double[] wkronrod, ref double[] wgauss, ref double eps)
Member Function Documentation
gkqgeneraterec() [1/2]
static void alglib.gkq.gkqgeneraterec (double[] alpha, double[] beta, double mu0, int n, ref int info, ref double[] x, ref double[] wkronrod, ref double[] wgauss) inline static
References alglib.beta(), and alglib.gq.gqgeneraterec().
Referenced by alglib.gkq.gkqgenerategaussjacobi(), alglib.gkqgeneraterec(), and alglib.gkq.gkqlegendrecalc().
gkqgenerategausslegendre() [1/2]
static void alglib.gkq.gkqgenerategausslegendre (int n, ref int info, ref double[] x, ref double[] wkronrod, ref double[] wgauss) inline static
References alglib.gkq.gkqlegendrecalc(), alglib.gkq.gkqlegendretbl(), and alglib.math.machineepsilon.
Referenced by alglib.autogk.autogkinternaliteration(), alglib.gkqgenerategausslegendre(), and alglib.testgkqunit.testgkq().
gkqgenerategaussjacobi() [1/2]
static void alglib.gkq.gkqgenerategaussjacobi (int n, double alpha, double beta, ref int info, ref double[] x, ref double[] wkronrod, ref double[] wgauss) inline static
References alglib.beta(), alglib.gkq.gkqgeneraterec(), alglib.gammafunc.lngamma(), alglib.math.maxrealnumber, and alglib.math.sqr().
Referenced by alglib.gkqgenerategaussjacobi(), and alglib.testgkqunit.testgkq().
gkqlegendrecalc() [1/2]
static void alglib.gkq.gkqlegendrecalc (int n, ref int info, ref double[] x, ref double[] wkronrod, ref double[] wgauss) inline static
References alglib.beta(), alglib.gkq.gkqgeneraterec(), and alglib.math.sqr().
Referenced by alglib.gkq.gkqgenerategausslegendre(), alglib.gkqlegendrecalc(), and alglib.testgkqunit.testgkq().
gkqlegendretbl() [1/2]
static void alglib.gkq.gkqlegendretbl (int n, ref double[] x, ref double[] wkronrod, ref double[] wgauss, ref double eps) inline static
References alglib.ap.assert(), alglib.math.machineepsilon, and alglib.tsort.tagsort().
Referenced by alglib.gkq.gkqgenerategausslegendre(), alglib.gkqlegendretbl(), and alglib.testgkqunit.testgkq().
gkqgeneraterec() [2/2]
static void alglib.gkq.gkqgeneraterec (double[] alpha, double[] beta, double mu0, int n, ref int info, ref double[] x, ref double[] wkronrod, ref double[] wgauss) inline static
References alglib.beta(), and alglib.gq.gqgeneraterec().
gkqgenerategausslegendre() [2/2]
static void alglib.gkq.gkqgenerategausslegendre (int n, ref int info, ref double[] x, ref double[] wkronrod, ref double[] wgauss) inline static
References alglib.gkq.gkqlegendrecalc(), alglib.gkq.gkqlegendretbl(), and alglib.math.machineepsilon.
gkqgenerategaussjacobi() [2/2]
static void alglib.gkq.gkqgenerategaussjacobi (int n, double alpha, double beta, ref int info, ref double[] x, ref double[] wkronrod, ref double[] wgauss) inline static
References alglib.beta(), alglib.gkq.gkqgeneraterec(), alglib.gammafunc.lngamma(), alglib.math.maxrealnumber, and alglib.math.sqr().
gkqlegendrecalc() [2/2]
static void alglib.gkq.gkqlegendrecalc (int n, ref int info, ref double[] x, ref double[] wkronrod, ref double[] wgauss) inline static
References alglib.beta(), alglib.gkq.gkqgeneraterec(), and alglib.math.sqr().
gkqlegendretbl() [2/2]
static void alglib.gkq.gkqlegendretbl (int n, ref double[] x, ref double[] wkronrod, ref double[] wgauss, ref double eps) inline static
References alglib.ap.assert(), alglib.math.machineepsilon, and alglib.tsort.tagsort().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/integration.cs