Doc: IGLib EXTENDED: Snapshot_Maker.SnapshotForm Class Reference
Snapshot_Maker.SnapshotForm Class Reference
Public Member Functions
SnapshotForm ()
void SetImage (Bitmap bitmap)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void saveButton_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.PictureBox pictureBox
System.Windows.Forms.Button saveButton
System.Windows.Forms.Label label1
System.Windows.Forms.TextBox timeBox
System.Windows.Forms.SaveFileDialog saveFileDialog
Constructor & Destructor Documentation
SnapshotForm()
Snapshot_Maker.SnapshotForm.SnapshotForm () inline
References Snapshot_Maker.SnapshotForm.InitializeComponent().
Member Function Documentation
SetImage()
void Snapshot_Maker.SnapshotForm.SetImage (Bitmap bitmap) inline
References Snapshot_Maker.SnapshotForm.pictureBox, and Snapshot_Maker.SnapshotForm.timeBox.
Referenced by Snapshot_Maker.MainForm.ShowSnapshot().
saveButton_Click()
void Snapshot_Maker.SnapshotForm.saveButton_Click (object sender, EventArgs e) inline private
References Snapshot_Maker.SnapshotForm.pictureBox, and Snapshot_Maker.SnapshotForm.saveFileDialog.
Referenced by Snapshot_Maker.SnapshotForm.InitializeComponent().
Dispose()
override void Snapshot_Maker.SnapshotForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References Snapshot_Maker.SnapshotForm.components.
InitializeComponent()
void Snapshot_Maker.SnapshotForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References Snapshot_Maker.SnapshotForm.label1, Snapshot_Maker.SnapshotForm.pictureBox, Snapshot_Maker.SnapshotForm.saveButton, Snapshot_Maker.SnapshotForm.saveButton_Click(), Snapshot_Maker.SnapshotForm.saveFileDialog, and Snapshot_Maker.SnapshotForm.timeBox.
Referenced by Snapshot_Maker.SnapshotForm.SnapshotForm().
Member Data Documentation
components
System.ComponentModel.IContainer Snapshot_Maker.SnapshotForm.components = null private
Required designer variable.
Referenced by Snapshot_Maker.SnapshotForm.Dispose().
pictureBox
System.Windows.Forms.PictureBox Snapshot_Maker.SnapshotForm.pictureBox private
Referenced by Snapshot_Maker.SnapshotForm.InitializeComponent(), Snapshot_Maker.SnapshotForm.saveButton_Click(), and Snapshot_Maker.SnapshotForm.SetImage().
saveButton
System.Windows.Forms.Button Snapshot_Maker.SnapshotForm.saveButton private
Referenced by Snapshot_Maker.SnapshotForm.InitializeComponent().
label1
System.Windows.Forms.Label Snapshot_Maker.SnapshotForm.label1 private
Referenced by Snapshot_Maker.SnapshotForm.InitializeComponent().
timeBox
System.Windows.Forms.TextBox Snapshot_Maker.SnapshotForm.timeBox private
Referenced by Snapshot_Maker.SnapshotForm.InitializeComponent(), and Snapshot_Maker.SnapshotForm.SetImage().
saveFileDialog
System.Windows.Forms.SaveFileDialog Snapshot_Maker.SnapshotForm.saveFileDialog private
Referenced by Snapshot_Maker.SnapshotForm.InitializeComponent(), and Snapshot_Maker.SnapshotForm.saveButton_Click().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Video/Snapshot Maker/SnapshotForm.cs
shelldev/lib_ann/aforge.net/Samples/Video/Snapshot Maker/SnapshotForm.Designer.cs