Doc: IGLib EXTENDED: NUnit.Engine.Drivers.TestEventAdapter Class Reference
NUnit.Engine.Drivers.TestEventAdapter Class Reference
The TestEventAdapter class receives NUnit v2 events and passes the equivalent v3 event to the engine.
Public Member Functions
TestEventAdapter (ITestEventListener listener)
override object InitializeLifetimeService ()
Private Member Functions
void EventListener. RunFinished (Exception exception)
void EventListener. RunFinished (TestResult result)
void EventListener. RunStarted (string name, int testCount)
void EventListener. SuiteFinished (TestResult result)
void EventListener. SuiteStarted (TestName testName)
void EventListener. TestFinished (TestResult result)
void EventListener. TestOutput (TestOutput testOutput)
void EventListener. TestStarted (TestName testName)
void EventListener. UnhandledException (Exception exception)
void OnTestStarted (TestName testName, bool isSuite)
void OnTestFinished (TestResult result)
Static Private Member Functions
static string FormatAttributeValue (string original)
Makes a string safe for use as an attribute, replacing characters characters that can't be used with their corresponding xml representations.
Private Attributes
ITestEventListener _listener
StringBuilder _testOutput = new StringBuilder()
Detailed Description
The TestEventAdapter class receives NUnit v2 events and passes the equivalent v3 event to the engine.
Constructor & Destructor Documentation
TestEventAdapter()
NUnit.Engine.Drivers.TestEventAdapter.TestEventAdapter (ITestEventListener listener) inline
References NUnit.Engine.Drivers.TestEventAdapter._listener.
Member Function Documentation
RunFinished() [1/2]
void EventListener. NUnit.Engine.Drivers.TestEventAdapter.RunFinished (Exception exception) inline private
RunFinished() [2/2]
void EventListener. NUnit.Engine.Drivers.TestEventAdapter.RunFinished (TestResult result) inline private
RunStarted()
void EventListener. NUnit.Engine.Drivers.TestEventAdapter.RunStarted (string name, int testCount) inline private
SuiteFinished()
void EventListener. NUnit.Engine.Drivers.TestEventAdapter.SuiteFinished (TestResult result) inline private
References NUnit.Engine.Drivers.TestEventAdapter.OnTestFinished().
SuiteStarted()
void EventListener. NUnit.Engine.Drivers.TestEventAdapter.SuiteStarted (TestName testName) inline private
References NUnit.Engine.Drivers.TestEventAdapter.OnTestStarted().
TestFinished()
void EventListener. NUnit.Engine.Drivers.TestEventAdapter.TestFinished (TestResult result) inline private
References NUnit.Engine.Drivers.TestEventAdapter.OnTestFinished().
TestOutput()
void EventListener. NUnit.Engine.Drivers.TestEventAdapter.TestOutput (TestOutput testOutput) inline private
References NUnit.Engine.Drivers.TestEventAdapter._testOutput.
TestStarted()
void EventListener. NUnit.Engine.Drivers.TestEventAdapter.TestStarted (TestName testName) inline private
References NUnit.Engine.Drivers.TestEventAdapter.OnTestStarted().
UnhandledException()
void EventListener. NUnit.Engine.Drivers.TestEventAdapter.UnhandledException (Exception exception) inline private
InitializeLifetimeService()
override object NUnit.Engine.Drivers.TestEventAdapter.InitializeLifetimeService () inline
FormatAttributeValue()
static string NUnit.Engine.Drivers.TestEventAdapter.FormatAttributeValue (string original) inline static private
Makes a string safe for use as an attribute, replacing characters characters that can't be used with their corresponding xml representations.
Parameters
original The string to be used
Returns
A new string with the _values replaced
Referenced by NUnit.Engine.Drivers.TestEventAdapter.OnTestStarted().
OnTestStarted()
void NUnit.Engine.Drivers.TestEventAdapter.OnTestStarted (TestName testName, bool isSuite) inline private
References NUnit.Engine.Drivers.TestEventAdapter._listener, NUnit.Engine.Drivers.TestEventAdapter.FormatAttributeValue(), and NUnit.Engine.ITestEventListener.OnTestEvent().
Referenced by NUnit.Engine.Drivers.TestEventAdapter.SuiteStarted(), and NUnit.Engine.Drivers.TestEventAdapter.TestStarted().
OnTestFinished()
void NUnit.Engine.Drivers.TestEventAdapter.OnTestFinished (TestResult result) inline private
References NUnit.Engine.Drivers.TestEventAdapter._listener, NUnit.Engine.Drivers.TestEventAdapter._testOutput, and NUnit.Engine.ITestEventListener.OnTestEvent().
Referenced by NUnit.Engine.Drivers.TestEventAdapter.SuiteFinished(), and NUnit.Engine.Drivers.TestEventAdapter.TestFinished().
Member Data Documentation
_listener
ITestEventListener NUnit.Engine.Drivers.TestEventAdapter._listener private
Referenced by NUnit.Engine.Drivers.TestEventAdapter.OnTestFinished(), NUnit.Engine.Drivers.TestEventAdapter.OnTestStarted(), and NUnit.Engine.Drivers.TestEventAdapter.TestEventAdapter().
_testOutput
StringBuilder NUnit.Engine.Drivers.TestEventAdapter._testOutput = new StringBuilder() private
Referenced by NUnit.Engine.Drivers.TestEventAdapter.OnTestFinished(), and NUnit.Engine.Drivers.TestEventAdapter.TestOutput().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/Addins/nunit.v2.driver/TestEventAdapter.cs