Doc: IGLib EXTENDED: NUnit.Framework.CombiningStrategyAttribute Class Reference
NUnit.Framework.CombiningStrategyAttribute Class Reference
Marks a test to use a particular CombiningStrategy to join any parameter data provided. Since this is the default, the attribute is optional.
Public Member Functions
IEnumerable< TestMethod > BuildFrom (IMethodInfo method, Test suite)
Construct one or more TestMethods from a given MethodInfo, using available parameter data.
void ApplyToTest (Test test)
Modify the test by adding the name of the combining strategy to the properties.
Public Member Functions inherited from NUnit.Framework.NUnitAttribute
NUnitAttribute ()
Default constructor
Protected Member Functions
CombiningStrategyAttribute (ICombiningStrategy strategy, IParameterDataProvider provider)
Construct a CombiningStrategyAttribute incorporating an ICombiningStrategy and an IParamterDataProvider.
CombiningStrategyAttribute (object strategy, object provider)
Construct a CombiningStrategyAttribute incorporating an object that implements ICombiningStrategy and an IParameterDataProvider. This constructor is provided for CLS compliance.
Private Attributes
NUnitTestCaseBuilder _builder = new NUnitTestCaseBuilder()
ICombiningStrategy _strategy
IParameterDataProvider _dataProvider
Detailed Description
Marks a test to use a particular CombiningStrategy to join any parameter data provided. Since this is the default, the attribute is optional.
Constructor & Destructor Documentation
CombiningStrategyAttribute() [1/2]
NUnit.Framework.CombiningStrategyAttribute.CombiningStrategyAttribute (ICombiningStrategy strategy, IParameterDataProvider provider) inline protected
Construct a CombiningStrategyAttribute incorporating an ICombiningStrategy and an IParamterDataProvider.
Parameters
strategy Combining strategy to be used in combining data
provider An IParameterDataProvider to supply data
References NUnit.Framework.CombiningStrategyAttribute._dataProvider, and NUnit.Framework.CombiningStrategyAttribute._strategy.
CombiningStrategyAttribute() [2/2]
NUnit.Framework.CombiningStrategyAttribute.CombiningStrategyAttribute (object strategy, object provider) inline protected
Construct a CombiningStrategyAttribute incorporating an object that implements ICombiningStrategy and an IParameterDataProvider. This constructor is provided for CLS compliance.
Parameters
strategy Combining strategy to be used in combining data
provider An IParameterDataProvider to supply data
Member Function Documentation
BuildFrom()
IEnumerable<TestMethod> NUnit.Framework.CombiningStrategyAttribute.BuildFrom (IMethodInfo method, Test suite) inline
Construct one or more TestMethods from a given MethodInfo, using available parameter data.
Parameters
method The MethodInfo for which tests are to be constructed.
suite The suite to which the tests will be added.
Returns
One or more TestMethods
Implements NUnit.Framework.Interfaces.ITestBuilder.
References NUnit.Framework.CombiningStrategyAttribute._builder, NUnit.Framework.CombiningStrategyAttribute._dataProvider, NUnit.Framework.CombiningStrategyAttribute._strategy, NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.BuildTestMethod(), NUnit.Framework.Interfaces.IMethodInfo.ContainsGenericParameters, NUnit.Framework.Interfaces.IParameterDataProvider.GetDataFor(), NUnit.Framework.Interfaces.IMethodInfo.GetGenericArguments(), NUnit.Framework.Interfaces.IMethodInfo.GetParameters(), NUnit.Framework.Interfaces.ICombiningStrategy.GetTestCases(), and NUnit.Framework.Internal.PropertyNames.SkipReason.
ApplyToTest()
void NUnit.Framework.CombiningStrategyAttribute.ApplyToTest (Test test) inline
Modify the test by adding the name of the combining strategy to the properties.
Parameters
test The test to modify
Implements NUnit.Framework.Interfaces.IApplyToTest.
References NUnit.Framework.CombiningStrategyAttribute._strategy, NUnit.Framework.Internal.PropertyNames.JoinType, NUnit.Framework.Internal.Test.Properties, and NUnit.Framework.Interfaces.IPropertyBag.Set().
Referenced by NUnit.Framework.Attributes.ApplyToTestTests.CombinatorialAttributeSetsJoinType(), NUnit.Framework.Attributes.ApplyToTestTests.CombinatorialAttributeSetsJoinTypeOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.PairwiseAttributeSetsJoinType(), NUnit.Framework.Attributes.ApplyToTestTests.PairwiseAttributeSetsJoinTypeOnNonRunnableTest(), NUnit.Framework.Attributes.ApplyToTestTests.SequentialAttributeSetsJoinType(), and NUnit.Framework.Attributes.ApplyToTestTests.SequentialAttributeSetsJoinTypeOnNonRunnableTest().
Member Data Documentation
_builder
NUnitTestCaseBuilder NUnit.Framework.CombiningStrategyAttribute._builder = new NUnitTestCaseBuilder() private
Referenced by NUnit.Framework.CombiningStrategyAttribute.BuildFrom().
_strategy
ICombiningStrategy NUnit.Framework.CombiningStrategyAttribute._strategy private
Referenced by NUnit.Framework.CombiningStrategyAttribute.ApplyToTest(), NUnit.Framework.CombiningStrategyAttribute.BuildFrom(), and NUnit.Framework.CombiningStrategyAttribute.CombiningStrategyAttribute().
_dataProvider
IParameterDataProvider NUnit.Framework.CombiningStrategyAttribute._dataProvider private
Referenced by NUnit.Framework.CombiningStrategyAttribute.BuildFrom(), and NUnit.Framework.CombiningStrategyAttribute.CombiningStrategyAttribute().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Attributes/CombiningStrategyAttribute.cs