Doc: IGLib EXTENDED: Meta.Numerics.Analysis.SpaceExtremum Class Reference
Meta.Numerics.Analysis.SpaceExtremum Class Reference
Represents a maximum or minimum of a function on a multi-dimensional space.
Public Member Functions
double[] Location ()
Gets the location of the extremum.
SymmetricMatrix Curvature ()
Gets the curvature matrix at the extremum.
Properties
double Value [get]
Gets the value of the function at the extremum.
int Dimension [get]
Gets the dimension of the space on which the function is defined.
Private Attributes
double[] x
double f
SymmetricMatrix f2
Detailed Description
Represents a maximum or minimum of a function on a multi-dimensional space.
Member Function Documentation
Location()
double [] Meta.Numerics.Analysis.SpaceExtremum.Location () inline
Gets the location of the extremum.
Returns
The coordinates of the extremum.
References Meta.Numerics.Analysis.SpaceExtremum.x.
Referenced by Test.ExtremaTest.FindMinimumOfGamma(), Test.ExtremaTest.FindSpaceMinimumOfRosenbock(), Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToFunction(), and Meta.Numerics.Statistics.Sample.MaximumLikelihoodFit().
Curvature()
SymmetricMatrix Meta.Numerics.Analysis.SpaceExtremum.Curvature () inline
Gets the curvature matrix at the extremum.
Returns
The curvature matrix.
References Meta.Numerics.Matrices.SymmetricMatrix.Copy(), and Meta.Numerics.Analysis.SpaceExtremum.f2.
Referenced by Test.ExtremaTest.FindMinimumOfGamma(), Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToFunction(), and Meta.Numerics.Statistics.Sample.MaximumLikelihoodFit().
Member Data Documentation
x
double [] Meta.Numerics.Analysis.SpaceExtremum.x private
Referenced by Meta.Numerics.Analysis.SpaceExtremum.Location().
f
double Meta.Numerics.Analysis.SpaceExtremum.f private
f2
SymmetricMatrix Meta.Numerics.Analysis.SpaceExtremum.f2 private
Referenced by Meta.Numerics.Analysis.SpaceExtremum.Curvature().
Property Documentation
Value
double Meta.Numerics.Analysis.SpaceExtremum.Value get
Gets the value of the function at the extremum.
Referenced by Test.ExtremaTest.FindMinimumOfGamma(), and Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToFunction().
Dimension
int Meta.Numerics.Analysis.SpaceExtremum.Dimension get
Gets the dimension of the space on which the function is defined.
Referenced by Test.ExtremaTest.FindMinimumOfGamma(), and Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToFunction().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Analysis/FunctionMath_MultiExtrema.cs