Doc: IGLib EXTENDED: IG.Forms.CookingTimerControl Class Reference
IG.Forms.CookingTimerControl Class Reference
Public Member Functions
CookingTimerControl ()
CookingTimerControl ()
CookingTimerControl ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void flowImage_Paint (object sender, PaintEventArgs e)
void comboTimes_Click (object sender, EventArgs e)
void comboTimes_Leave (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void flowImage_Paint (object sender, PaintEventArgs e)
void comboTimes_Click (object sender, EventArgs e)
void comboTimes_Leave (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void flowImage_Paint (object sender, PaintEventArgs e)
void comboTimes_Click (object sender, EventArgs e)
void comboTimes_Leave (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Button btnCookingSw
System.Windows.Forms.FlowLayoutPanel floTimer
System.Windows.Forms.Button btnTimerFlow
System.Windows.Forms.FlowLayoutPanel flowOuter
System.Windows.Forms.Button btnOuterFlow
System.Windows.Forms.FlowLayoutPanel flowImage
System.Windows.Forms.Button btnImageFlow
System.Windows.Forms.PictureBox pictureBox1
TimerControl timerControl1
System.Windows.Forms.Panel panel1
System.Windows.Forms.Button btnCookingControls
System.Windows.Forms.ComboBox comboTimes
Constructor & Destructor Documentation
CookingTimerControl() [1/3]
IG.Forms.CookingTimerControl.CookingTimerControl () inline
References IG.Forms.CookingTimerControl.InitializeComponent().
CookingTimerControl() [2/3]
IG.Forms.CookingTimerControl.CookingTimerControl () inline
References IG.Forms.CookingTimerControl.InitializeComponent().
CookingTimerControl() [3/3]
IG.Forms.CookingTimerControl.CookingTimerControl () inline
References IG.Forms.CookingTimerControl.InitializeComponent().
Member Function Documentation
flowImage_Paint() [1/3]
void IG.Forms.CookingTimerControl.flowImage_Paint (object sender, PaintEventArgs e) inline private
Referenced by IG.Forms.CookingTimerControl.InitializeComponent().
comboTimes_Click() [1/3]
void IG.Forms.CookingTimerControl.comboTimes_Click (object sender, EventArgs e) inline private
References IG.Forms.CookingTimerControl.comboTimes.
Referenced by IG.Forms.CookingTimerControl.InitializeComponent().
comboTimes_Leave() [1/3]
void IG.Forms.CookingTimerControl.comboTimes_Leave (object sender, EventArgs e) inline private
References IG.Forms.CookingTimerControl.comboTimes.
Referenced by IG.Forms.CookingTimerControl.InitializeComponent().
Dispose() [1/3]
override void IG.Forms.CookingTimerControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.CookingTimerControl.components.
InitializeComponent() [1/3]
void IG.Forms.CookingTimerControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.CookingTimerControl.btnCookingControls, IG.Forms.CookingTimerControl.btnCookingSw, IG.Forms.CookingTimerControl.btnImageFlow, IG.Forms.CookingTimerControl.btnOuterFlow, IG.Forms.CookingTimerControl.btnTimerFlow, IG.Forms.TimerControl.CdShowHoursWhenZero, IG.Forms.TimerControl.CdShowMilliSeconds, IG.Forms.TimerControl.CdStartText, IG.Forms.TimerControl.CdStopText, IG.Forms.TimerControl.ColorBgOk, IG.Forms.TimerControl.ColorBgTitle, IG.Forms.TimerControl.ColorBgTitleMain, IG.Forms.TimerControl.ColorBgWarning, IG.Forms.TimerControl.ColorFgTitle, IG.Forms.TimerControl.ColorFgTitleMain, IG.Forms.CookingTimerControl.comboTimes, IG.Forms.CookingTimerControl.comboTimes_Click(), IG.Forms.CookingTimerControl.comboTimes_Leave(), IG.Forms.CookingTimerControl.components, IG.Forms.CookingTimerControl.floTimer, IG.Forms.CookingTimerControl.flowImage, IG.Forms.CookingTimerControl.flowImage_Paint(), IG.Forms.CookingTimerControl.flowOuter, IG.Forms.TimerControl.IsCdSoundAlarm, IG.Forms.TimerControl.IsCdSoundButtons, IG.Forms.TimerControl.IsCdSoundHourBell, IG.Forms.TimerControl.IsCdSoundMinuteBell, IG.Forms.TimerControl.IsCdSoundSecondTick, IG.Forms.TimerControl.IsClockMain, IG.Forms.TimerControl.IsClockShown, IG.Forms.TimerControl.IsClockSoundHourBell, IG.Forms.TimerControl.IsClockSoundMinuteBell, IG.Forms.TimerControl.IsClockSoundSecondTick, IG.Forms.TimerControl.IsCountdownMain, IG.Forms.TimerControl.IsCountdownShown, IG.Forms.TimerControl.IsSilent, IG.Forms.TimerControl.IsStopwatchMain, IG.Forms.TimerControl.IsStopwatchShown, IG.Forms.TimerControl.IsSwSoundButtons, IG.Forms.TimerControl.IsSwSoundHourBell, IG.Forms.TimerControl.IsSwSoundMinuteBell, IG.Forms.TimerControl.IsSwSoundSecondTick, IG.Forms.TimerControl.MilliSecondsSizeRatio, IG.Forms.CookingTimerControl.panel1, IG.Forms.CookingTimerControl.pictureBox1, IG.Forms.TimerControl.SwShowHoursWhenZero, IG.Forms.TimerControl.SwShowMilliSeconds, IG.Forms.TimerControl.SwStartText, IG.Forms.TimerControl.SwStopText, and IG.Forms.CookingTimerControl.timerControl1.
Referenced by IG.Forms.CookingTimerControl.CookingTimerControl().
flowImage_Paint() [2/3]
void IG.Forms.CookingTimerControl.flowImage_Paint (object sender, PaintEventArgs e) inline private
comboTimes_Click() [2/3]
void IG.Forms.CookingTimerControl.comboTimes_Click (object sender, EventArgs e) inline private
References IG.Forms.CookingTimerControl.comboTimes.
comboTimes_Leave() [2/3]
void IG.Forms.CookingTimerControl.comboTimes_Leave (object sender, EventArgs e) inline private
References IG.Forms.CookingTimerControl.comboTimes.
Dispose() [2/3]
override void IG.Forms.CookingTimerControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.CookingTimerControl.components.
InitializeComponent() [2/3]
void IG.Forms.CookingTimerControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.CookingTimerControl.btnCookingControls, IG.Forms.CookingTimerControl.btnCookingSw, IG.Forms.CookingTimerControl.btnImageFlow, IG.Forms.CookingTimerControl.btnOuterFlow, IG.Forms.CookingTimerControl.btnTimerFlow, IG.Forms.TimerControl.CdShowHoursWhenZero, IG.Forms.TimerControl.CdShowMilliSeconds, IG.Forms.TimerControl.CdStartText, IG.Forms.TimerControl.CdStopText, IG.Forms.TimerControl.ColorBgOk, IG.Forms.TimerControl.ColorBgWarning, IG.Forms.CookingTimerControl.comboTimes, IG.Forms.CookingTimerControl.comboTimes_Click(), IG.Forms.CookingTimerControl.comboTimes_Leave(), IG.Forms.CookingTimerControl.floTimer, IG.Forms.CookingTimerControl.flowImage, IG.Forms.CookingTimerControl.flowImage_Paint(), IG.Forms.CookingTimerControl.flowOuter, IG.Forms.TimerControl.MilliSecondsSizeRatio, IG.Forms.CookingTimerControl.panel1, IG.Forms.CookingTimerControl.pictureBox1, IG.Forms.TimerControl.SwShowHoursWhenZero, IG.Forms.TimerControl.SwShowMilliSeconds, IG.Forms.TimerControl.SwStartText, IG.Forms.TimerControl.SwStopText, and IG.Forms.CookingTimerControl.timerControl1.
flowImage_Paint() [3/3]
void IG.Forms.CookingTimerControl.flowImage_Paint (object sender, PaintEventArgs e) inline private
comboTimes_Click() [3/3]
void IG.Forms.CookingTimerControl.comboTimes_Click (object sender, EventArgs e) inline private
References IG.Forms.CookingTimerControl.comboTimes.
comboTimes_Leave() [3/3]
void IG.Forms.CookingTimerControl.comboTimes_Leave (object sender, EventArgs e) inline private
References IG.Forms.CookingTimerControl.comboTimes.
Dispose() [3/3]
override void IG.Forms.CookingTimerControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.CookingTimerControl.components.
InitializeComponent() [3/3]
void IG.Forms.CookingTimerControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.CookingTimerControl.btnCookingControls, IG.Forms.CookingTimerControl.btnCookingSw, IG.Forms.CookingTimerControl.btnImageFlow, IG.Forms.CookingTimerControl.btnOuterFlow, IG.Forms.CookingTimerControl.btnTimerFlow, IG.Forms.TimerControl.CdShowHoursWhenZero, IG.Forms.TimerControl.CdShowMilliSeconds, IG.Forms.TimerControl.CdStartText, IG.Forms.TimerControl.CdStopText, IG.Forms.TimerControl.ColorBgOk, IG.Forms.TimerControl.ColorBgTitle, IG.Forms.TimerControl.ColorBgTitleMain, IG.Forms.TimerControl.ColorBgWarning, IG.Forms.TimerControl.ColorFgTitle, IG.Forms.TimerControl.ColorFgTitleMain, IG.Forms.CookingTimerControl.comboTimes, IG.Forms.CookingTimerControl.comboTimes_Click(), IG.Forms.CookingTimerControl.comboTimes_Leave(), IG.Forms.CookingTimerControl.components, IG.Forms.CookingTimerControl.floTimer, IG.Forms.CookingTimerControl.flowImage, IG.Forms.CookingTimerControl.flowImage_Paint(), IG.Forms.CookingTimerControl.flowOuter, IG.Forms.TimerControl.IsCdSoundAlarm, IG.Forms.TimerControl.IsCdSoundButtons, IG.Forms.TimerControl.IsCdSoundHourBell, IG.Forms.TimerControl.IsCdSoundMinuteBell, IG.Forms.TimerControl.IsCdSoundSecondTick, IG.Forms.TimerControl.IsClockMain, IG.Forms.TimerControl.IsClockShown, IG.Forms.TimerControl.IsClockSoundHourBell, IG.Forms.TimerControl.IsClockSoundMinuteBell, IG.Forms.TimerControl.IsClockSoundSecondTick, IG.Forms.TimerControl.IsCountdownMain, IG.Forms.TimerControl.IsCountdownShown, IG.Forms.TimerControl.IsSilent, IG.Forms.TimerControl.IsStopwatchMain, IG.Forms.TimerControl.IsStopwatchShown, IG.Forms.TimerControl.IsSwSoundButtons, IG.Forms.TimerControl.IsSwSoundHourBell, IG.Forms.TimerControl.IsSwSoundMinuteBell, IG.Forms.TimerControl.IsSwSoundSecondTick, IG.Forms.TimerControl.MilliSecondsSizeRatio, IG.Forms.CookingTimerControl.panel1, IG.Forms.CookingTimerControl.pictureBox1, IG.Forms.TimerControl.SwShowHoursWhenZero, IG.Forms.TimerControl.SwShowMilliSeconds, IG.Forms.TimerControl.SwStartText, IG.Forms.TimerControl.SwStopText, and IG.Forms.CookingTimerControl.timerControl1.
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.CookingTimerControl.components = null private
Required designer variable.
Referenced by IG.Forms.CookingTimerControl.Dispose(), and IG.Forms.CookingTimerControl.InitializeComponent().
btnCookingSw
System Windows Forms Button IG.Forms.CookingTimerControl.btnCookingSw private
Referenced by IG.Forms.CookingTimerControl.InitializeComponent().
floTimer
System Windows Forms FlowLayoutPanel IG.Forms.CookingTimerControl.floTimer private
Referenced by IG.Forms.CookingTimerControl.InitializeComponent().
btnTimerFlow
System Windows Forms Button IG.Forms.CookingTimerControl.btnTimerFlow private
Referenced by IG.Forms.CookingTimerControl.InitializeComponent().
flowOuter
System Windows Forms FlowLayoutPanel IG.Forms.CookingTimerControl.flowOuter private
Referenced by IG.Forms.CookingTimerControl.InitializeComponent().
btnOuterFlow
System Windows Forms Button IG.Forms.CookingTimerControl.btnOuterFlow private
Referenced by IG.Forms.CookingTimerControl.InitializeComponent().
flowImage
System Windows Forms FlowLayoutPanel IG.Forms.CookingTimerControl.flowImage private
Referenced by IG.Forms.CookingTimerControl.InitializeComponent().
btnImageFlow
System Windows Forms Button IG.Forms.CookingTimerControl.btnImageFlow private
Referenced by IG.Forms.CookingTimerControl.InitializeComponent().
pictureBox1
System Windows Forms PictureBox IG.Forms.CookingTimerControl.pictureBox1 private
Referenced by IG.Forms.CookingTimerControl.InitializeComponent().
timerControl1
TimerControl IG.Forms.CookingTimerControl.timerControl1 private
Referenced by IG.Forms.CookingTimerControl.InitializeComponent().
panel1
System Windows Forms Panel IG.Forms.CookingTimerControl.panel1 private
Referenced by IG.Forms.CookingTimerControl.InitializeComponent().
btnCookingControls
System Windows Forms Button IG.Forms.CookingTimerControl.btnCookingControls private
Referenced by IG.Forms.CookingTimerControl.InitializeComponent().
comboTimes
System Windows Forms ComboBox IG.Forms.CookingTimerControl.comboTimes private
Referenced by IG.Forms.CookingTimerControl.comboTimes_Click(), IG.Forms.CookingTimerControl.comboTimes_Leave(), and IG.Forms.CookingTimerControl.InitializeComponent().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/Timer/CookingTimerControl.cs
iglib/igforms/Utilities/Timer/CookingTimerControl.Designer.cs