Doc: IGLib EXTENDED: IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent Class Reference
IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent Class Reference
The generalized Rosenbrock's unconstrained optimization problem in arbitrary dimensions Dim >= 2.
Public Member Functions
override void Analyse (IAnalysisResults analysisData)
Performs the direct analysis, i.e. calculation of the response functions of the optimization problem.
Protected Attributes
ScalarFunctionBase _objectiveFunction
IVector _grad = null
IMatrix _hess = null
Protected Attributes inherited from IG.Num.AnalysisBase
int _numParameters = -1
int _numObjectives = -1
int _numConstraints = -1
int _numEqualityConstraints = -1
Properties
object Lock [get]
override int NumObjectives [get, set]
Number of objectives.
override int NumConstraints [get, set]
Number of constraints.
virtual ScalarFunctionBase ObjectiveFunction [get, protected set]
The scalar function object that can perform evaluation of the Rosenbrock function and eventually its derivatives.
Properties inherited from IG.Num.AnalysisBase
object Lock [get]
virtual int NumParameters [get, set]
Number of parameters.
virtual int NumObjectives [get, set]
Number of objective functions (normally 1 for this type, but can be 0).
virtual int NumConstraints [get, set]
Number of constraints.
virtual int NumEqualityConstraints [get, set]
Number of equality constraints.
Properties inherited from IG.Num.IAnalysis
int NumParameters [get, set]
Number of parameters.
int NumObjectives [get, set]
Number of objective functions (normally 1 for this type, but can be 0).
int NumConstraints [get, set]
Number of constraints.
int NumEqualityConstraints [get, set]
Number of equality constraints.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
object _lock = new object()
Detailed Description
The generalized Rosenbrock's unconstrained optimization problem in arbitrary dimensions Dim >= 2.
f(x,y) = Sum[i=0...N-2]{(1-x_{i})^2 + 100 * (x_{i+1}-x_{i}^2)^2}
This is one of the generalizations of the 2D Rosenbrock function.
Moved from stand-alone class, now nested in the ScalarFunctionExamples class.
See also:
I. Grešovnik: Test functions for Unconstrained Minimization, Igor's internal report.
Definition at AlgLib page: http://www.alglib.net/optimization/lbfgsandcg.php#header4
Definition at Wikipedia: http://en.wikipedia.org/wiki/Rosenbrock_function#Multidimensional_generalisations
Member Function Documentation
Analyse()
override void IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent.Analyse (IAnalysisResults analysisData) inline
Performs the direct analysis, i.e. calculation of the response functions of the optimization problem.
Parameters
analysisData Object that contains analysis request data and where analysis results are stored.
Implements IG.Num.IAnalysis.
References IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent._grad, IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent._hess, IG.Num.IAnalysisResults.CalculatedConstraintGradients, IG.Num.IAnalysisResults.CalculatedConstraintHessians, IG.Num.IAnalysisResults.CalculatedConstraints, IG.Num.IAnalysisResults.CalculatedObjective, IG.Num.IAnalysisResults.CalculatedObjectiveGradient, IG.Num.IAnalysisResults.CalculatedObjectiveHessian, IG.Num.IAnalysisResults.ErrorCode, IG.Num.IAnalysisResults.ErrorString, IG.Num.ScalarFunctionUntransformedBase.Gradient(), IG.Num.ScalarFunctionUntransformedBase.Hessian(), IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent.Lock, IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent.NumConstraints, IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent.NumObjectives, IG.Num.IAnalysis.NumParameters, IG.Num.IAnalysisResults.NumParameters, IG.Num.IAnalysisResults.Objective, IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent.ObjectiveFunction, IG.Num.IAnalysisResults.ObjectiveGradient, IG.Num.IAnalysisResults.ObjectiveHessian, IG.Num.IAnalysisResults.Parameters, IG.Num.IAnalysisResults.PrepareResultStorage(), IG.Num.IAnalysisResults.ReqConstraintGradients, IG.Num.IAnalysisResults.ReqConstraintHessians, IG.Num.IAnalysisResults.ReqConstraints, IG.Num.IAnalysisResults.ReqObjective, IG.Num.IAnalysisResults.ReqObjectiveGradient, IG.Num.IAnalysisResults.ReqObjectiveHessian, and IG.Num.ScalarFunctionBase.Value().
Member Data Documentation
_lock
object IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent._lock = new object() private
_objectiveFunction
ScalarFunctionBase IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent._objectiveFunction protected
_grad
IVector IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent._grad = null protected
Referenced by IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent.Analyse().
_hess
IMatrix IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent._hess = null protected
Referenced by IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent.Analyse().
Property Documentation
Lock
object IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent.Lock get
Referenced by IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent.Analyse().
NumObjectives
override int IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent.NumObjectives get set
Number of objectives.
Referenced by IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent.Analyse().
NumConstraints
override int IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent.NumConstraints get set
Number of constraints.
Referenced by IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent.Analyse().
ObjectiveFunction
virtual ScalarFunctionBase IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent.ObjectiveFunction get protected set
The scalar function object that can perform evaluation of the Rosenbrock function and eventually its derivatives.
Referenced by IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent.Analyse().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/opt/testcases/OptTest1.cs