Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DSYR2K Class Reference
DotNumerics.LinearAlgebra.CSLapack.DSYR2K Class Reference
Public Member Functions
DSYR2K (LSAME lsame, XERBLA xerbla)
DSYR2K ()
void Run (string UPLO, string TRANS, int N, int K, double ALPHA, double[] A, int offset_a, int LDA, double[] B, int offset_b, int LDB, double BETA, ref double[] C, int offset_c, int LDC)
Private Attributes
LSAME _lsame
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
Purpose
DSYR2K performs one of the symmetric rank 2k operations
C := alpha*A*B' + alpha*B*A' + beta*C,
or
C := alpha*A'*B + alpha*B'*A + beta*C,
where alpha and beta are scalars, C is an n by n symmetric matrix and A and B are n by k matrices in the first case and k by n matrices in the second case.
/summary>
Constructor & Destructor Documentation
DSYR2K() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DSYR2K.DSYR2K (LSAME lsame, XERBLA xerbla) inline
DSYR2K() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DSYR2K.DSYR2K () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DSYR2K.Run (string UPLO, string TRANS, int N, int K, double ALPHA, double[] A, int offset_a, int LDA, double[] B, int offset_b, int LDB, double BETA, ref double[] C, int offset_c, int LDC) inline
Purpose
DSYR2K performs one of the symmetric rank 2k operations
C := alpha*A*B' + alpha*B*A' + beta*C,
or
C := alpha*A'*B + alpha*B'*A + beta*C,
where alpha and beta are scalars, C is an n by n symmetric matrix and A and B are n by k matrices in the first case and k by n matrices in the second case.
/summary>
Parameters
UPLO
CHARACTER*1. On entry, UPLO specifies whether the upper or lower triangular part of the array C is to be referenced as follows:
UPLO = 'U' or 'u' Only the upper triangular part of C is to be referenced.
UPLO = 'L' or 'l' Only the lower triangular part of C is to be referenced.
Unchanged on exit. /param>
Parameters
TRANS
CHARACTER*1. On entry, TRANS specifies the operation to be performed as follows:
TRANS = 'N' or 'n' C := alpha*A*B' + alpha*B*A' + beta*C.
TRANS = 'T' or 't' C := alpha*A'*B + alpha*B'*A + beta*C.
TRANS = 'C' or 'c' C := alpha*A'*B + alpha*B'*A + beta*C.
Unchanged on exit. /param>
Parameters
N
INTEGER. On entry, N specifies the order of the matrix C. N must be at least zero. Unchanged on exit. /param>
Parameters
K
INTEGER. On entry with TRANS = 'N' or 'n', K specifies the number of columns of the matrices A and B, and on entry with TRANS = 'T' or 't' or 'C' or 'c', K specifies the number of rows of the matrices A and B. K must be at least zero. Unchanged on exit. /param>
Parameters
ALPHA
DOUBLE PRECISION. On entry, ALPHA specifies the scalar alpha. Unchanged on exit. /param>
Parameters
A
DOUBLE PRECISION array of DIMENSION (LDA, ka), where ka is k when TRANS = 'N' or 'n', and is n otherwise. Before entry with TRANS = 'N' or 'n', the leading n by k part of the array A must contain the matrix A, otherwise the leading k by n part of the array A must contain the matrix A. Unchanged on exit. /param>
Parameters
LDA
INTEGER. On entry, LDA specifies the first dimension of A as declared in the calling (sub) program. When TRANS = 'N' or 'n' then LDA must be at least max(1, n), otherwise LDA must be at least max(1, k). Unchanged on exit. /param>
Parameters
B
DOUBLE PRECISION array of DIMENSION (LDB, kb), where kb is k when TRANS = 'N' or 'n', and is n otherwise. Before entry with TRANS = 'N' or 'n', the leading n by k part of the array B must contain the matrix B, otherwise the leading k by n part of the array B must contain the matrix B. Unchanged on exit. /param>
Parameters
LDB
INTEGER. On entry, LDB specifies the first dimension of B as declared in the calling (sub) program. When TRANS = 'N' or 'n' then LDB must be at least max(1, n), otherwise LDB must be at least max(1, k). Unchanged on exit. /param>
Parameters
BETA
DOUBLE PRECISION. On entry, BETA specifies the scalar beta. Unchanged on exit. /param>
Parameters
C := alpha*A*B' + alpha*B*A' + beta*C, /param>
Parameters
LDC
INTEGER. On entry, LDC specifies the first dimension of C as declared in the calling (sub) program. LDC must be at least max(1, n). Unchanged on exit.
/param>
References DotNumerics.LinearAlgebra.CSLapack.DSYR2K.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), and DotNumerics.LinearAlgebra.CSLapack.DSYR2K.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYTRD.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DSYR2K._lsame private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DSYR2K._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DSYR2K.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYR2K.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DSYR2K.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYR2K.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dsyr2k.cs