Doc: IGLib EXTENDED: CShell.Framework.Services.Execute Class Reference
CShell.Framework.Services.Execute Class Reference
Static Public Member Functions
static void OnUIThread (this Action action)
static void OnUIThreadEx (this Action action)
Executes an action and marshals any exceptions that occur to the calling thread.
Member Function Documentation
OnUIThread()
static void CShell.Framework.Services.Execute.OnUIThread (this Action action) inline static
Referenced by CShell.Modules.Repl.ViewModels.ReplViewModel.Clear(), CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnConsoleOutput(), CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnEvaluateCompleted(), CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnEvaluateStarted(), and CShell.Modules.Shell.ViewModels.StatusBarViewModel.UpdateMessage().
OnUIThreadEx()
static void CShell.Framework.Services.Execute.OnUIThreadEx (this Action action) inline static
Executes an action and marshals any exceptions that occur to the calling thread.
Parameters
action The action.
Referenced by CShell.Modules.Editors.ViewModels.EditorViewModel.CanClose(), CShell.Modules.Editors.ViewModels.EditorViewModel.Comment(), CShell.Modules.Editors.ViewModels.EditorViewModel.Copy(), CShell.Modules.Editors.ViewModels.EditorViewModel.Cut(), CShell.Shell.Dump(), CShell.Modules.Shell.ViewModels.ShellViewModel.LoadLayout(), CShell.Modules.Editors.ViewModels.EditorViewModel.Paste(), CShell.Modules.Editors.ViewModels.EditorViewModel.Redo(), CShell.Modules.Editors.ViewModels.EditorViewModel.Save(), CShell.Modules.Editors.ViewModels.EditorViewModel.SaveAs(), CShell.Modules.Shell.ViewModels.ShellViewModel.SaveLayout(), CShell.Modules.Editors.ViewModels.EditorViewModel.Select(), CShell.Modules.Editors.ViewModels.EditorViewModel.SelectAll(), CShell.Modules.Editors.ViewModels.EditorViewModel.Uncomment(), and CShell.Modules.Editors.ViewModels.EditorViewModel.Undo().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore/Framework/Services/Execute.cs