Doc: IGLib EXTENDED: NUnit.Framework.Internal.TestResult Class Reference
NUnit.Framework.Internal.TestResult Class Reference
The TestResult class represents the result of a test.
Public Member Functions
TestResult (ITest test)
Construct a test result given a Test
TNode ToXml (bool recursive)
Returns the Xml representation of the result.
virtual TNode AddToXml (TNode parentNode, bool recursive)
Adds the XML representation of the result as a child of the supplied parent node..
virtual void AddResult (ITestResult result)
Adds a child result to this result, setting this result's ResultState to Failure if the child result failed.
void SetResult (ResultState resultState)
Set the result of the test
void SetResult (ResultState resultState, string message)
Set the result of the test
void SetResult (ResultState resultState, string message, string stackTrace)
Set the result of the test
void RecordException (Exception ex)
Set the test result based on the type of exception thrown
void RecordException (Exception ex, FailureSite site)
Set the test result based on the type of exception thrown
void RecordTearDownException (Exception ex)
RecordTearDownException appends the message and stacktrace from an exception arising during teardown of the test to any previously recorded information, so that any earlier failure information is not lost. Note that calling Assert.Ignore, Assert.Inconclusive, etc. during teardown is treated as an error. If the current result represents a suite, it may show a teardown error even though all contained tests passed.
Properties
ITest Test [get, private set]
Gets the test with which this result is associated.
ResultState ResultState [get, private set]
Gets the ResultState of the test result, which indicates the success or failure of the test.
virtual string Name [get]
Gets the name of the test result
virtual string FullName [get]
Gets the full name of the test result
double? Duration [get, set]
Gets or sets the elapsed time for running the test in seconds
DateTime StartTime [get, set]
Gets or sets the time the test started running.
DateTime EndTime [get, set]
Gets or sets the time the test finished running.
string Message [get, private set]
Gets the message associated with a test failure or with not running the test
virtual string StackTrace [get, private set]
Gets any stacktrace associated with an error or failure.
int AssertCount [get, set]
Gets or sets the count of asserts executed when running the test.
abstract int FailCount [get]
Gets the number of test cases that failed when running the test and all its children.
abstract int PassCount [get]
Gets the number of test cases that passed when running the test and all its children.
abstract int SkipCount [get]
Gets the number of test cases that were skipped when running the test and all its children.
abstract int InconclusiveCount [get]
Gets the number of test cases that were inconclusive when running the test and all its children.
bool HasChildren [get]
Indicates whether this result has any child results. Test HasChildren before accessing Children to avoid the creation of an empty collection.
System.Collections.Generic.IList< ITestResult > Children [get]
Gets the collection of child results.
StringWriter OutWriter [get]
Gets a TextWriter, which will write output to be included in the result.
string? Output [get]
Gets any text output written to this result.
Properties inherited from NUnit.Framework.Interfaces.ITestResult
ResultState ResultState [get]
Gets the ResultState of the test result, which indicates the success or failure of the test.
string Name [get]
Gets the name of the test result
string FullName [get]
Gets the full name of the test result
double Duration [get]
Gets the elapsed time for running the test in seconds
DateTime StartTime [get]
Gets or sets the time the test started running.
DateTime EndTime [get]
Gets or sets the time the test finished running.
string Message [get]
Gets the message associated with a test failure or with not running the test
string StackTrace [get]
Gets any stacktrace associated with an error or failure. Not available in the Compact Framework 1.0.
int AssertCount [get]
Gets the number of asserts executed when running the test and all its children.
int FailCount [get]
Gets the number of test cases that failed when running the test and all its children.
int PassCount [get]
Gets the number of test cases that passed when running the test and all its children.
int SkipCount [get]
Gets the number of test cases that were skipped when running the test and all its children.
int InconclusiveCount [get]
Gets the number of test cases that were inconclusive when running the test and all its children.
bool HasChildren [get]
Indicates whether this result has any child results. Accessing HasChildren should not force creation of the Children collection in classes implementing this interface.
System.Collections.Generic.IList< ITestResult > Children [get]
Gets the the collection of child results.
ITest Test [get]
Gets the Test to which this result applies.
string Output [get]
Gets any text output written to this result.
Private Member Functions
TNode AddReasonElement (TNode targetNode)
Adds a reason element to a node and returns it.
TNode AddFailureElement (TNode targetNode)
Adds a failure element to a node and returns it.
TNode AddOutputElement (TNode targetNode)
Private Attributes
System.Collections.Generic.List< ITestResult > _children
List of child results
StringWriter _outWriter
double _duration
Detailed Description
The TestResult class represents the result of a test.
Constructor & Destructor Documentation
TestResult()
NUnit.Framework.Internal.TestResult.TestResult (ITest test) inline
Construct a test result given a Test
Parameters
test The test to be used
References NUnit.Framework.Interfaces.ResultState.Inconclusive.
Member Function Documentation
ToXml()
TNode NUnit.Framework.Internal.TestResult.ToXml (bool recursive) inline
Returns the Xml representation of the result.
Parameters
recursive If true, descendant results are included
Returns
An XmlNode representing the result
Implements NUnit.Framework.Interfaces.IXmlNodeBuilder.
References NUnit.Framework.Internal.TestResult.AddToXml().
Referenced by NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_Multiple_XmlOutput(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_XmlOutput(), NUnit.Framework.Internal.TestResultOutputTests.IfNothingIsWritten_XmlOutputIsEmpty(), NUnit.Framework.Internal.TestResultTests.SuiteResultXmlNodeBasicInfo(), NUnit.Framework.Internal.MixedResultTests.SuiteResultXmlNodeHasFourChildTests(), NUnit.Framework.Internal.DefaultResultTests.SuiteResultXmlNodeHasOneChildTest(), NUnit.Framework.Internal.SuccessResultTests.SuiteResultXmlNodeHasOneChildTest(), NUnit.Framework.Internal.IgnoredResultTests.SuiteResultXmlNodeHasOneChildTest(), NUnit.Framework.Internal.NotRunnableResultTests.SuiteResultXmlNodeHasOneChildTest(), NUnit.Framework.Internal.FailedResultTests.SuiteResultXmlNodeHasOneChildTest(), NUnit.Framework.Internal.InconclusiveResultTests.SuiteResultXmlNodeHasOneChildTest(), NUnit.Framework.Internal.NotRunnableResultTests.SuiteResultXmlNodeIsFailure(), NUnit.Framework.Internal.FailedResultTests.SuiteResultXmlNodeIsFailure(), NUnit.Framework.Internal.MixedResultTests.SuiteResultXmlNodeIsFailure(), NUnit.Framework.Internal.IgnoredResultTests.SuiteResultXmlNodeIsIgnored(), NUnit.Framework.Internal.DefaultResultTests.SuiteResultXmlNodeIsInconclusive(), NUnit.Framework.Internal.InconclusiveResultTests.SuiteResultXmlNodeIsInconclusive(), NUnit.Framework.Internal.SuccessResultTests.SuiteResultXmlNodeIsSuccess(), NUnit.Framework.Internal.TestResultTests.TestResultXmlNodeBasicInfo(), NUnit.Framework.Internal.FailedResultTests.TestResultXmlNodeEscapesInvalidXmlCharacters(), NUnit.Framework.Internal.FailedResultTests.TestResultXmlNodeIsFailure(), NUnit.Framework.Internal.IgnoredResultTests.TestResultXmlNodeIsIgnored(), NUnit.Framework.Internal.DefaultResultTests.TestResultXmlNodeIsInconclusive(), NUnit.Framework.Internal.InconclusiveResultTests.TestResultXmlNodeIsInconclusive(), NUnit.Framework.Internal.NotRunnableResultTests.TestResultXmlNodeIsNotRunnable(), and NUnit.Framework.Internal.SuccessResultTests.TestResultXmlNodeIsSuccess().
AddToXml()
virtual TNode NUnit.Framework.Internal.TestResult.AddToXml (TNode parentNode, bool recursive) inline virtual
Adds the XML representation of the result as a child of the supplied parent node..
Parameters
parentNode The parent node.
recursive If true, descendant results are included
Returns
Implements NUnit.Framework.Interfaces.IXmlNodeBuilder.
References NUnit.Framework.Interfaces.TNode.AddAttribute(), NUnit.Framework.Internal.TestResult.AddFailureElement(), NUnit.Framework.Internal.TestResult.AddOutputElement(), NUnit.Framework.Internal.TestResult.AddReasonElement(), NUnit.Framework.Internal.TestResult.AddToXml(), NUnit.Framework.Internal.TestResult.AssertCount, NUnit.Framework.Internal.TestResult.Children, NUnit.Framework.Internal.TestResult.Duration, NUnit.Framework.Internal.TestResult.EndTime, NUnit.Framework.Internal.TestResult.FailCount, NUnit.Framework.Internal.TestResult.HasChildren, NUnit.Framework.Internal.TestResult.InconclusiveCount, NUnit.Framework.Interfaces.ResultState.Label, NUnit.Framework.Internal.TestResult.Message, NUnit.Framework.Internal.TestResult.Output, NUnit.Framework.Internal.TestResult.PassCount, NUnit.Framework.Interfaces.ResultState.Site, NUnit.Framework.Internal.TestResult.SkipCount, NUnit.Framework.Internal.TestResult.StartTime, and NUnit.Framework.Interfaces.ResultState.Status.
Referenced by NUnit.Framework.Internal.TestResult.AddToXml(), and NUnit.Framework.Internal.TestResult.ToXml().
AddResult()
virtual void NUnit.Framework.Internal.TestResult.AddResult (ITestResult result) inline virtual
Adds a child result to this result, setting this result's ResultState to Failure if the child result failed.
Parameters
result The result to be added
Reimplemented in NUnit.Framework.Internal.TestSuiteResult.
References NUnit.Framework.Interfaces.ResultState.Cancelled, NUnit.Framework.Interfaces.ResultState.ChildFailure, NUnit.Framework.Internal.TestResult.Children, NUnit.Framework.Interfaces.ResultState.Ignored, NUnit.Framework.Interfaces.ResultState.Label, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.Framework.Internal.TestResult.SetResult(), NUnit.Framework.Interfaces.ResultState.Status, and NUnit.Framework.Interfaces.ResultState.Success.
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.OnChildCompleted(), NUnit.Framework.Internal.DefaultResultTests.SimulateTestRun(), NUnit.Framework.Internal.SuccessResultTests.SimulateTestRun(), NUnit.Framework.Internal.IgnoredResultTests.SimulateTestRun(), NUnit.Framework.Internal.NotRunnableResultTests.SimulateTestRun(), NUnit.Framework.Internal.FailedResultTests.SimulateTestRun(), NUnit.Framework.Internal.InconclusiveResultTests.SimulateTestRun(), NUnit.Framework.Internal.MixedResultTests.SimulateTestRun(), NUnit.Framework.Internal.MinimumDurationResultTests.SimulateTestRun(), and NUnit.Framework.Internal.Execution.CompositeWorkItem.SkipChildren().
SetResult() [1/3]
void NUnit.Framework.Internal.TestResult.SetResult (ResultState resultState) inline
Set the result of the test
Parameters
resultState The ResultState to use in the result
Referenced by NUnit.Framework.Internal.TestResult.AddResult(), NUnit.Framework.Internal.Execution.CompositeWorkItem.CheckForCancellation(), NUnit.Framework.Internal.Execution.CompositeWorkItem.CountDownChildTest(), NUnit.Framework.Internal.Commands.TheoryResultCommand.Execute(), NUnit.Framework.Internal.Commands.SkipCommand.Execute(), NUnit.Framework.Internal.Commands.MaxTimeCommand.Execute(), NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(), NUnit.Framework.Attributes.Tests.CommandWrapperTests.ExpectedExceptionAttribute.ExpectedExceptionCommand.Execute(), NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork(), NUnit.Framework.Internal.TestResult.RecordException(), NUnit.Framework.Internal.TestResult.RecordTearDownException(), NUnit.Framework.Internal.Execution.WorkItem.RunTestOnOwnThread(), NUnit.Framework.Internal.TestResult.SetResult(), NUnit.Framework.Internal.SuccessResultTests.SimulateTestRun(), NUnit.Framework.Internal.IgnoredResultTests.SimulateTestRun(), NUnit.Framework.Internal.NotRunnableResultTests.SimulateTestRun(), NUnit.Framework.Internal.FailedResultTests.SimulateTestRun(), NUnit.Framework.Internal.InconclusiveResultTests.SimulateTestRun(), NUnit.Framework.Internal.MixedResultTests.SimulateTestRun(), NUnit.Framework.Internal.MinimumDurationResultTests.SimulateTestRun(), NUnit.Framework.Internal.Execution.CompositeWorkItem.SkipChildren(), NUnit.Framework.Internal.Execution.CompositeWorkItem.SkipFixture(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Failed(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Ignored(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Inconclusive(), NUnitLite.Tests.TeamCityEventListenerTests.TestFinished_Passed(), and NUnit.Framework.Internal.FailedResultTests.TestResultXmlNodeEscapesInvalidXmlCharacters().
SetResult() [2/3]
void NUnit.Framework.Internal.TestResult.SetResult (ResultState resultState, string message) inline
Set the result of the test
Parameters
resultState The ResultState to use in the result
message A message associated with the result state
References NUnit.Framework.Internal.TestResult.SetResult().
SetResult() [3/3]
void NUnit.Framework.Internal.TestResult.SetResult (ResultState resultState, string message, string stackTrace) inline
Set the result of the test
Parameters
resultState The ResultState to use in the result
message A message associated with the result state
stackTrace Stack trace giving the location of the command
References NUnit.Framework.Internal.TestResult.Message, and NUnit.Framework.Internal.TestResult.StackTrace.
RecordException() [1/2]
void NUnit.Framework.Internal.TestResult.RecordException (Exception ex) inline
Set the test result based on the type of exception thrown
Parameters
ex The exception that was thrown
References NUnit.Framework.Internal.ExceptionHelper.BuildMessage(), NUnit.Framework.Internal.ExceptionHelper.BuildStackTrace(), NUnit.Framework.Interfaces.ResultState.Cancelled, NUnit.Framework.Interfaces.ResultState.Error, NUnit.Framework.Internal.StackFilter.Filter(), and NUnit.Framework.Internal.TestResult.SetResult().
Referenced by NUnit.Framework.Internal.Commands.ApplyChangesToContextCommand.Execute(), NUnit.Framework.Internal.Commands.TestActionCommand.Execute(), NUnit.Framework.Internal.Commands.SetUpTearDownCommand.Execute(), and NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeSetUp().
RecordException() [2/2]
void NUnit.Framework.Internal.TestResult.RecordException (Exception ex, FailureSite site) inline
Set the test result based on the type of exception thrown
Parameters
ex The exception that was thrown
site THe FailureSite to use in the result
References NUnit.Framework.Internal.ExceptionHelper.BuildMessage(), NUnit.Framework.Internal.ExceptionHelper.BuildStackTrace(), NUnit.Framework.Interfaces.ResultState.Cancelled, NUnit.Framework.Interfaces.ResultState.Error, NUnit.Framework.Internal.StackFilter.Filter(), NUnit.Framework.Internal.TestResult.SetResult(), and NUnit.Framework.Interfaces.ResultState.WithSite().
RecordTearDownException()
void NUnit.Framework.Internal.TestResult.RecordTearDownException (Exception ex) inline
RecordTearDownException appends the message and stacktrace from an exception arising during teardown of the test to any previously recorded information, so that any earlier failure information is not lost. Note that calling Assert.Ignore, Assert.Inconclusive, etc. during teardown is treated as an error. If the current result represents a suite, it may show a teardown error even though all contained tests passed.
Parameters
ex The Exception to be recorded
References NUnit.Framework.Internal.ExceptionHelper.BuildMessage(), NUnit.Framework.Internal.ExceptionHelper.BuildStackTrace(), NUnit.Framework.Interfaces.ResultState.Cancelled, NUnit.Framework.Interfaces.ResultState.Error, NUnit.Framework.Internal.TestResult.Message, NUnit.Env.NewLine, NUnit.Framework.Internal.TestResult.SetResult(), NUnit.Framework.Internal.TestResult.StackTrace, and NUnit.Framework.Interfaces.ResultState.WithSite().
Referenced by NUnit.Framework.Internal.Commands.OneTimeTearDownCommand.Execute(), and NUnit.Framework.Internal.Commands.SetUpTearDownItem.RunTearDown().
AddReasonElement()
TNode NUnit.Framework.Internal.TestResult.AddReasonElement (TNode targetNode) inline private
Adds a reason element to a node and returns it.
Parameters
targetNode The target node.
Returns
The new reason element.
References NUnit.Framework.Interfaces.TNode.AddElement(), NUnit.Framework.Interfaces.TNode.AddElementWithCDATA(), and NUnit.Framework.Internal.TestResult.Message.
Referenced by NUnit.Framework.Internal.TestResult.AddToXml().
AddFailureElement()
TNode NUnit.Framework.Internal.TestResult.AddFailureElement (TNode targetNode) inline private
Adds a failure element to a node and returns it.
Parameters
targetNode The target node.
Returns
The new failure element.
References NUnit.Framework.Interfaces.TNode.AddElement(), NUnit.Framework.Interfaces.TNode.AddElementWithCDATA(), NUnit.Framework.Internal.TestResult.Message, and NUnit.Framework.Internal.TestResult.StackTrace.
Referenced by NUnit.Framework.Internal.TestResult.AddToXml().
AddOutputElement()
TNode NUnit.Framework.Internal.TestResult.AddOutputElement (TNode targetNode) inline private
References NUnit.Framework.Interfaces.TNode.AddElementWithCDATA(), and NUnit.Framework.Internal.TestResult.Output.
Referenced by NUnit.Framework.Internal.TestResult.AddToXml().
Member Data Documentation
_children
System.Collections.Generic.List<ITestResult> NUnit.Framework.Internal.TestResult._children private
List of child results
_outWriter
StringWriter NUnit.Framework.Internal.TestResult._outWriter private
_duration
double NUnit.Framework.Internal.TestResult._duration private
Property Documentation
Test
ITest NUnit.Framework.Internal.TestResult.Test get private set
Gets the test with which this result is associated.
ResultState
ResultState NUnit.Framework.Internal.TestResult.ResultState get private set
Gets the ResultState of the test result, which indicates the success or failure of the test.
Referenced by NUnit.Framework.Internal.Commands.TheoryResultCommand.Execute(), NUnit.Framework.Internal.Commands.MaxTimeCommand.Execute(), NUnit.Framework.RetryAttribute.RetryCommand.Execute(), NUnit.Framework.RepeatAttribute.RepeatedTestCommand.Execute(), NUnit.Framework.Internal.SetUpTearDownTests.HandleExceptionInSetUp(), NUnit.Framework.Assertions.AssertIgnoreTests.IgnoreWorksFromSetUp(), NUnit.Framework.Internal.Execution.CompositeWorkItem.OnChildCompleted(), NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork(), NUnit.Framework.Internal.Execution.WorkItem.RunTestOnOwnThread(), NUnit.Framework.Internal.NotRunnableResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.FailedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.MixedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.IgnoredResultTests.SuiteResultIsIgnored(), NUnit.Framework.Internal.DefaultResultTests.SuiteResultIsInconclusive(), NUnit.Framework.Internal.InconclusiveResultTests.SuiteResultIsInconclusive(), NUnit.Framework.Internal.SuccessResultTests.SuiteResultIsSuccess(), NUnit.Framework.Internal.FailedResultTests.TestResultIsFailure(), NUnit.Framework.Internal.IgnoredResultTests.TestResultIsIgnored(), NUnit.Framework.Internal.DefaultResultTests.TestResultIsInconclusive(), NUnit.Framework.Internal.InconclusiveResultTests.TestResultIsInconclusive(), NUnit.Framework.Internal.NotRunnableResultTests.TestResultIsNotRunnable(), and NUnit.Framework.Internal.SuccessResultTests.TestResultIsSuccess().
Name
virtual string NUnit.Framework.Internal.TestResult.Name get
Gets the name of the test result
Referenced by NUnit.Framework.Assertions.AssertThatTests.AssertionsAreCountedCorrectly(), NUnit.TestUtilities.TestFinder.Find(), NUnit.Framework.Internal.TestResultTests.SuiteResultBasicInfo(), and NUnit.Framework.Internal.TestResultTests.TestResultBasicInfo().
FullName
virtual string NUnit.Framework.Internal.TestResult.FullName get
Gets the full name of the test result
Referenced by NUnit.Framework.Internal.TestResultTests.SuiteResultBasicInfo(), and NUnit.Framework.Internal.TestResultTests.TestResultBasicInfo().
Duration
double? NUnit.Framework.Internal.TestResult.Duration get set
Gets or sets the elapsed time for running the test in seconds
Referenced by NUnit.Framework.Internal.TestResult.AddToXml(), NUnitLite.Tests.TextUITests.CreateResult(), NUnit.Framework.Internal.Commands.MaxTimeCommand.Execute(), NUnit.Framework.Internal.SuccessResultTests.SimulateTestRun(), NUnit.Framework.Internal.FailedResultTests.SimulateTestRun(), NUnit.Framework.Internal.MinimumDurationResultTests.SimulateTestRun(), NUnit.Framework.Internal.MinimumDurationResultTests.TestResultHasMinimumDuration(), NUnit.Framework.Internal.FailedResultTests.TestResultIsFailure(), NUnit.Framework.Internal.DefaultResultTests.TestResultIsInconclusive(), NUnit.Framework.Internal.SuccessResultTests.TestResultIsSuccess(), and NUnit.Framework.Internal.Execution.WorkItem.WorkItemComplete().
StartTime
DateTime NUnit.Framework.Internal.TestResult.StartTime get set
Gets or sets the time the test started running.
Referenced by NUnit.Framework.Internal.TestResult.AddToXml(), NUnitLite.Tests.TextUITests.CreateResult(), NUnit.Framework.Internal.SuccessResultTests.SimulateTestRun(), NUnit.Framework.Internal.FailedResultTests.SimulateTestRun(), NUnit.Framework.Internal.MinimumDurationResultTests.SimulateTestRun(), NUnit.Framework.Internal.FailedResultTests.TestResultIsFailure(), NUnit.Framework.Internal.SuccessResultTests.TestResultIsSuccess(), and NUnit.Framework.Internal.Execution.WorkItem.WorkItemComplete().
EndTime
DateTime NUnit.Framework.Internal.TestResult.EndTime get set
Gets or sets the time the test finished running.
Referenced by NUnit.Framework.Internal.TestResult.AddToXml(), NUnitLite.Tests.TextUITests.CreateResult(), NUnit.Framework.Internal.SuccessResultTests.SimulateTestRun(), NUnit.Framework.Internal.FailedResultTests.SimulateTestRun(), NUnit.Framework.Internal.MinimumDurationResultTests.SimulateTestRun(), NUnit.Framework.Internal.FailedResultTests.TestResultIsFailure(), NUnit.Framework.Internal.SuccessResultTests.TestResultIsSuccess(), and NUnit.Framework.Internal.Execution.WorkItem.WorkItemComplete().
Message
string NUnit.Framework.Internal.TestResult.Message get private set
Gets the message associated with a test failure or with not running the test
Referenced by NUnit.Framework.Internal.TestResult.AddFailureElement(), NUnit.Framework.Internal.TestResult.AddReasonElement(), NUnit.Framework.Internal.TestResult.AddToXml(), NUnit.Framework.Internal.SetUpTearDownTests.HandleExceptionInSetUp(), NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork(), NUnit.Framework.Internal.TestResult.RecordTearDownException(), NUnit.Framework.Internal.TestResult.SetResult(), NUnit.Framework.Internal.NotRunnableResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.FailedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.MixedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.IgnoredResultTests.SuiteResultIsIgnored(), NUnit.Framework.Internal.InconclusiveResultTests.SuiteResultIsInconclusive(), NUnit.Framework.Internal.FailedResultTests.TestResultIsFailure(), NUnit.Framework.Internal.IgnoredResultTests.TestResultIsIgnored(), NUnit.Framework.Internal.InconclusiveResultTests.TestResultIsInconclusive(), NUnit.Framework.Internal.NotRunnableResultTests.TestResultIsNotRunnable(), and NUnit.Framework.Internal.SuccessResultTests.TestResultIsSuccess().
StackTrace
virtual string NUnit.Framework.Internal.TestResult.StackTrace get private set
Gets any stacktrace associated with an error or failure.
Referenced by NUnit.Framework.Internal.TestResult.AddFailureElement(), NUnit.Framework.Internal.SetUpTearDownTests.HandleExceptionInSetUp(), NUnit.Framework.Internal.TestResult.RecordTearDownException(), NUnit.Framework.Internal.TestResult.SetResult(), NUnit.Framework.Internal.FailedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.MixedResultTests.SuiteResultIsFailure(), and NUnit.Framework.Internal.FailedResultTests.TestResultIsFailure().
AssertCount
int NUnit.Framework.Internal.TestResult.AssertCount get set
Gets or sets the count of asserts executed when running the test.
Referenced by NUnit.Framework.Internal.TestSuiteResult.AddResult(), NUnit.Framework.Internal.TestResult.AddToXml(), NUnit.Framework.Assertions.AssertThatTests.AssertionsAreCountedCorrectly(), NUnit.Framework.Internal.SuccessResultTests.SimulateTestRun(), NUnit.Framework.Internal.FailedResultTests.SimulateTestRun(), NUnit.Framework.Internal.MixedResultTests.SimulateTestRun(), NUnit.Framework.Internal.MinimumDurationResultTests.SimulateTestRun(), NUnit.Framework.Internal.NotRunnableResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.FailedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.MixedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.IgnoredResultTests.SuiteResultIsIgnored(), NUnit.Framework.Internal.DefaultResultTests.SuiteResultIsInconclusive(), NUnit.Framework.Internal.InconclusiveResultTests.SuiteResultIsInconclusive(), NUnit.Framework.Internal.SuccessResultTests.SuiteResultIsSuccess(), and NUnit.Framework.Internal.Execution.WorkItem.WorkItemComplete().
FailCount
abstract int NUnit.Framework.Internal.TestResult.FailCount get
Gets the number of test cases that failed when running the test and all its children.
Referenced by NUnit.Framework.Internal.TestResult.AddToXml(), NUnit.Framework.Internal.NotRunnableResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.FailedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.MixedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.IgnoredResultTests.SuiteResultIsIgnored(), NUnit.Framework.Internal.InconclusiveResultTests.SuiteResultIsInconclusive(), and NUnit.Framework.Internal.SuccessResultTests.SuiteResultIsSuccess().
PassCount
abstract int NUnit.Framework.Internal.TestResult.PassCount get
Gets the number of test cases that passed when running the test and all its children.
Referenced by NUnit.Framework.Internal.TestResult.AddToXml(), NUnit.Framework.Internal.NotRunnableResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.FailedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.MixedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.IgnoredResultTests.SuiteResultIsIgnored(), NUnit.Framework.Internal.InconclusiveResultTests.SuiteResultIsInconclusive(), and NUnit.Framework.Internal.SuccessResultTests.SuiteResultIsSuccess().
SkipCount
abstract int NUnit.Framework.Internal.TestResult.SkipCount get
Gets the number of test cases that were skipped when running the test and all its children.
Referenced by NUnit.Framework.Internal.TestResult.AddToXml(), NUnit.Framework.Internal.NotRunnableResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.FailedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.MixedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.IgnoredResultTests.SuiteResultIsIgnored(), NUnit.Framework.Internal.InconclusiveResultTests.SuiteResultIsInconclusive(), and NUnit.Framework.Internal.SuccessResultTests.SuiteResultIsSuccess().
InconclusiveCount
abstract int NUnit.Framework.Internal.TestResult.InconclusiveCount get
Gets the number of test cases that were inconclusive when running the test and all its children.
Referenced by NUnit.Framework.Internal.TestResult.AddToXml(), NUnit.Framework.Internal.NotRunnableResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.FailedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.MixedResultTests.SuiteResultIsFailure(), NUnit.Framework.Internal.IgnoredResultTests.SuiteResultIsIgnored(), NUnit.Framework.Internal.InconclusiveResultTests.SuiteResultIsInconclusive(), and NUnit.Framework.Internal.SuccessResultTests.SuiteResultIsSuccess().
HasChildren
bool NUnit.Framework.Internal.TestResult.HasChildren get
Indicates whether this result has any child results. Test HasChildren before accessing Children to avoid the creation of an empty collection.
Referenced by NUnit.Framework.Internal.TestResult.AddToXml(), NUnit.Framework.Internal.Commands.TheoryResultCommand.Execute(), and NUnit.TestUtilities.TestFinder.Find().
Children
System.Collections.Generic.IList<ITestResult> NUnit.Framework.Internal.TestResult.Children get
Gets the collection of child results.
Referenced by NUnit.Framework.Internal.TestResult.AddResult(), NUnit.Framework.Internal.TestResult.AddToXml(), NUnit.Framework.Assertions.AssertThatTests.AssertionsAreCountedCorrectly(), NUnit.Framework.Internal.Execution.CompositeWorkItem.CountDownChildTest(), and NUnit.Framework.Internal.Commands.TheoryResultCommand.Execute().
OutWriter
StringWriter NUnit.Framework.Internal.TestResult.OutWriter get
Gets a TextWriter, which will write output to be included in the result.
Referenced by NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_Multiple(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_Multiple_XmlOutput(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_XmlOutput(), NUnit.Framework.Internal.Execution.TextCapture.Write(), and NUnit.Framework.Internal.Execution.TextCapture.WriteLine().
Output
string? NUnit.Framework.Internal.TestResult.Output get
Gets any text output written to this result.
Referenced by NUnit.Framework.Internal.TestResult.AddOutputElement(), NUnit.Framework.Internal.TestResult.AddToXml(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult(), NUnit.Framework.Internal.TestResultOutputTests.CanWriteOutputToResult_Multiple(), and NUnit.Framework.Internal.TestResultOutputTests.IfNothingIsWritten_OutputIsEmpty().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/Results/TestResult.cs