Doc: IGLib EXTENDED: Meta.Numerics.Functions.OrthogonalPolynomials Class Reference
Meta.Numerics.Functions.OrthogonalPolynomials Class Reference
Contains methods that compute the values of orthogonal polynomials.
Static Public Member Functions
static double HermiteH (int n, double x)
Computes the value of a (physicists') Hermite polynomial.
static double HermiteHe (int n, double x)
Computes the value of a (statisticians') Hermite polynomial.
static double LaguerreL (int n, double x)
Computes the value of a Laguerre polynomial.
static double LaguerreL (int n, double a, double x)
Computes the value of an associated Laguerre polynomial.
static double LegendreP (int l, double x)
Computes the value of a Legendre polynomial.
static double LegendreP (int l, int m, double x)
Computes the value of an associated Legendre polynomial.
static double ChebyshevT (int n, double x)
Computes the value of a Cebyshev polynomial.
static double ZernikeR (int n, int m, double rho)
Computes the value of a Zernike polynomial.
Static Private Member Functions
static double ChebyshevT_Series1 (int n, double x)
Detailed Description
Contains methods that compute the values of orthogonal polynomials.
Orthogonal polynomials are complete families of polynomials that are orthogonal on a given interval with a given integration weight. Because of this property, any function on the interval can be expanded in the polynomials in a unique way.
Member Function Documentation
HermiteH()
static double Meta.Numerics.Functions.OrthogonalPolynomials.HermiteH (int n, double x) inline static
Computes the value of a (physicists') Hermite polynomial.
Parameters
n The order, which must be non-negative.
x The argument.
Returns
The value Hn(x).
Hermite polynomials are orthogonal on the interval (-&#8734;,+&#8734;) with the weight e-x2.
They appear in the solution of the one-dimensional, quantum mehanical, harmonic oscilator.
Statisticans' Hermite polynomials (see HermiteHe) are related to physicists' Hermite polynomials via Hn(x) = 2nHn(x &#x221A;2). Staticians' Hermite polynomials do not grow as quickly as physicists', and may therefore be preferable for large values of n and x which could overflow System.Double.
Exceptions
ArgumentOutOfRangeException n is negative.
See also
HermiteHe
Referenced by Test.OrthogonalPolynomialsTest.HermiteAddition(), Test.OrthogonalPolynomialsTest.HermiteInvalidOrder(), Test.OrthogonalPolynomialsTest.HermiteOrthonormality(), Test.OrthogonalPolynomialsTest.HermiteRecurrence(), Test.OrthogonalPolynomialsTest.HermiteReflection(), Test.OrthogonalPolynomialsTest.HermiteSpecialCases(), and Test.OrthogonalPolynomialsTest.HermiteSum().
HermiteHe()
static double Meta.Numerics.Functions.OrthogonalPolynomials.HermiteHe (int n, double x) inline static
Computes the value of a (statisticians') Hermite polynomial.
Parameters
n The order, which must be non-negative.
x The argument.
Returns
The value Hen(x).
Hermite polynomials are orthogonal on the interval (-&#8734;,+&#8734;) with a weight function equal to the standard normal probability distribution.
Their orthonormality relation makes them a useful basis for expressing pertubations arround a normal distribution.
Physicists' Hermite polynomials (see HermiteH) are related to statisticians' Hermite polynomials via Hn(x) = 2nHn(x &#x221A;2).
Exceptions
ArgumentOutOfRangeException n is negative.
See also
HermiteH
LaguerreL() [1/2]
static double Meta.Numerics.Functions.OrthogonalPolynomials.LaguerreL (int n, double x) inline static
Computes the value of a Laguerre polynomial.
Parameters
n The order, which must be non-negative.
x The argument, which must be non-negative.
Returns
The value Ln(x).
Laguerre functions are orthogonal on the interval [0,+&#8734;) with the weight e-x.
Exceptions
ArgumentOutOfRangeException n or x is negative.
See also
LaguerreL(int,double,double)
Referenced by Test.OrthogonalPolynomialsTest.AssociatedLaguerreAlphaRecurrence(), Test.OrthogonalPolynomialsTest.AssociatedLaguerreOrthonormality(), Test.OrthogonalPolynomialsTest.AssociatedLaguerreSpecialCases(), Test.OrthogonalPolynomialsTest.AssociatedLaguerreSum(), Test.OrthogonalPolynomialsTest.LaguerreInequality(), Test.OrthogonalPolynomialsTest.LaguerreInvalidArgument(), Test.OrthogonalPolynomialsTest.LaguerreInvalidOrder(), Test.OrthogonalPolynomialsTest.LaguerreOrthonormality(), Test.OrthogonalPolynomialsTest.LaguerreRecurrence(), and Test.OrthogonalPolynomialsTest.LaguerreSpecialCases().
LaguerreL() [2/2]
static double Meta.Numerics.Functions.OrthogonalPolynomials.LaguerreL (int n, double a, double x) inline static
Computes the value of an associated Laguerre polynomial.
Parameters
n The order, which must be non-negative.
a The associated order, which must be greater than -1.
x The argument.
Returns
The value Lna(x).
The associated Laguerre polynomials are orthonogal on the interval [0,+&#8734;) with the weight xa e-x.
LegendreP() [1/2]
static double Meta.Numerics.Functions.OrthogonalPolynomials.LegendreP (int l, double x) inline static
Computes the value of a Legendre polynomial.
Parameters
l The order, which must be non-negative.
x The argument, which must lie on the closed interval between -1 and +1.
Returns
The value of Pl(x).
Legendre polynomials are orthogonal on the interval [-1,1].
Exceptions
ArgumentOutOfRangeException x lies outside [-1,+1].
Referenced by Test.OrthogonalPolynomialsTest.AssociatedLegendreAgreement(), Test.OrthogonalPolynomialsTest.AssociatedLegendreLowOrders(), Test.OrthogonalPolynomialsTest.AssociatedLegendreOrthonormalityL(), Test.OrthogonalPolynomialsTest.AssociatedLegendreRecurrenceL(), Test.OrthogonalPolynomialsTest.AssociatedLegendreRecurrenceM(), Test.OrthogonalPolynomialsTest.LegendreInequality(), Test.OrthogonalPolynomialsTest.LegendreInvalidArgument(), Test.OrthogonalPolynomialsTest.LegendreNegativeOrder(), Test.OrthogonalPolynomialsTest.LegendreOrthonormality(), Test.OrthogonalPolynomialsTest.LegendreRecurrence(), Test.OrthogonalPolynomialsTest.LegendreReflection(), Test.OrthogonalPolynomialsTest.LegendreSpecialCases(), Test.OrthogonalPolynomialsTest.LegendreTuronInequality(), Test.OrthogonalPolynomialsTest.SphericalHarmonicAddition(), Test.OrthogonalPolynomialsTest.SphericalHarmonicLegendre(), and Test.SpinTest.ThreeJLegendreIntegral().
LegendreP() [2/2]
static double Meta.Numerics.Functions.OrthogonalPolynomials.LegendreP (int l, int m, double x) inline static
Computes the value of an associated Legendre polynomial.
Parameters
l The order, which must be non-negative.
m The associated order, which must lie between -l and l inclusive.
x The argument, which must lie on the closed interval betwen -1 and +1.
Returns
The value of Pl,m(x).
Associated Legendre polynomials appear in the definition of the AdvancedMath.SphericalHarmonic functions.
For values of l and m over about 150, values of this polynomial can exceed the capacity of double-wide floating point numbers.
References Meta.Numerics.Functions.AdvancedIntegerMath.Factorial(), and Meta.Numerics.Functions.AdvancedIntegerMath.LogFactorial().
ChebyshevT()
static double Meta.Numerics.Functions.OrthogonalPolynomials.ChebyshevT (int n, double x) inline static
Computes the value of a Cebyshev polynomial.
Parameters
n The order, which must be non-negative.
x The argument, which must lie in the closed interval between -1 and +1.
Returns
The value of Tn(x).
Chebyshev polynomials are orthogonal on the interval [-1,1] with the weight (1-x2)-1/2.
Exceptions
ArgumentOutOfRangeException n is negative, or x lies outside [-1,+1].
References Meta.Numerics.Functions.OrthogonalPolynomials.ChebyshevT_Series1().
Referenced by Test.OrthogonalPolynomialsTest.ChebyshevCosine(), Test.OrthogonalPolynomialsTest.ChebyshevDoubling(), Test.OrthogonalPolynomialsTest.ChebyshevInequality(), Test.OrthogonalPolynomialsTest.ChebyshevInvalidArgument(), Test.OrthogonalPolynomialsTest.ChebyshevMultiplication(), Test.OrthogonalPolynomialsTest.ChebyshevRecurrence(), Test.OrthogonalPolynomialsTest.ChebyshevReflection(), and Test.OrthogonalPolynomialsTest.ChebyshevSpecialCases().
ChebyshevT_Series1()
static double Meta.Numerics.Functions.OrthogonalPolynomials.ChebyshevT_Series1 (int n, double x) inline static private
Referenced by Meta.Numerics.Functions.OrthogonalPolynomials.ChebyshevT().
ZernikeR()
static double Meta.Numerics.Functions.OrthogonalPolynomials.ZernikeR (int n, int m, double rho) inline static
Computes the value of a Zernike polynomial.
Parameters
n The order paramter, which must be non-negative.
m The index parameter, which must lie between 0 and n.
rho The argument, which must lie between 0 and 1.
Returns
The value of Rnm(&#x3C1;).
Zernike polynomials are orthononal on the interval [0,1] with the weight &#x3C1;.
They are often used in optics to characterize the imperfections in a lens. In this context, the amplitude of each is associated with a name given in the following table.
n m name
1 1 tilt
2 0 defocus
2 2 astigmatism
3 1 coma
3 3 trefoil
Referenced by Test.OrthogonalPolynomialsTest.ZernikeBessel(), Test.OrthogonalPolynomialsTest.ZernikeOrthonormality(), and Test.OrthogonalPolynomialsTest.ZernikeSpecialCases().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Functions/OrthogonalPolynomials.cs