Doc: IGLib EXTENDED: IG.Test.TestCryptoIGLib Class Reference
IG.Test.TestCryptoIGLib Class Reference
Unit tests for matrix operations.
Public Member Functions
void IGLibSaltOutOfRange1 ()
void IGLibSaltOutOfRange2 ()
void IGLibSaltOutOfRange3 ()
void IGLibSaltOutOfRange1 ()
void IGLibSaltOutOfRange2 ()
void IGLibSaltOutOfRange3 ()
Detailed Description
Unit tests for matrix operations.
$A Igor Jun15;
Member Function Documentation
IGLibSaltOutOfRange1() [1/2]
void IG.Test.TestCryptoIGLib.IGLibSaltOutOfRange1 () inline
References IG.Crypto.UtilCrypto.IgGetSaltSuffix().
IGLibSaltOutOfRange2() [1/2]
void IG.Test.TestCryptoIGLib.IGLibSaltOutOfRange2 () inline
References IG.Crypto.UtilCrypto.IgGetNumSaltSuffices(), and IG.Crypto.UtilCrypto.IgGetSaltSuffix().
IGLibSaltOutOfRange3() [1/2]
void IG.Test.TestCryptoIGLib.IGLibSaltOutOfRange3 () inline
References IG.Crypto.UtilCrypto.IgGetSaltSuffix().
IGLibSaltOutOfRange1() [2/2]
void IG.Test.TestCryptoIGLib.IGLibSaltOutOfRange1 () inline
References IG.Crypto.UtilCrypto.IgGetSaltSuffix(), and NUnit.Framework.Assert.Throws().
IGLibSaltOutOfRange2() [2/2]
void IG.Test.TestCryptoIGLib.IGLibSaltOutOfRange2 () inline
References IG.Crypto.UtilCrypto.IgGetNumSaltSuffices(), IG.Crypto.UtilCrypto.IgGetSaltSuffix(), and NUnit.Framework.Assert.Throws().
IGLibSaltOutOfRange3() [2/2]
void IG.Test.TestCryptoIGLib.IGLibSaltOutOfRange3 () inline
References IG.Crypto.UtilCrypto.IgGetSaltSuffix(), and NUnit.Framework.Assert.Throws().
The documentation for this class was generated from the following file:
unittests/MSTests/TestUtil/TstCryptoIGLib.cs