Doc: IGLib EXTENDED: IG.Test.TestMatrixDecomposition Class Reference
IG.Test.TestMatrixDecomposition Class Reference
Unit tests for matrix decompositions.
Public Member Functions
void LU_MatrixBase ()
Unit test for testing correctness of the LU decomposition of an invertible matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
void LDLT_MatrixBase ()
Unit test for testing correctness of the LDLT decomposition of a symmetric matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
void LDLT_Indefinite_MatrixBase ()
Unit test for testing correctness of the LDLT decomposition of a symmetric matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
void Cholesky_MatrixBase ()
Unit test for testing correctness of the Cholesky (LLT) decomposition of a symmetric positive definite matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
void Cholesky_PositiveSemidefinite_MatrixBase ()
Unit test for testing correctness of the Cholesky (LLT) decomposition of a symmetric positive SEMIdefinite matrix. Decomposition in this case must throw an exception of type InvalidOperationException.
void QrGrammSchmidt_MatrixBase ()
Verifies correctness of the QR decomposition performed by the Gramm-Schmidt method, on a 6 by 6 randomly generated matrix. The product and orthonormality of the Q factor are verified.
void Qr_MatrixBase ()
Verifies correctness of the QR decomposition performed by the Gramm-Schmidt method, on a 6 by 6 randomly generated matrix. The product and orthonormality of the Q factor are verified.
void LU_MatrixBase ()
Unit test for testing correctness of the LU decomposition of an invertible matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
void LDLT_MatrixBase ()
Unit test for testing correctness of the LDLT decomposition of a symmetric matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
void LDLT_Indefinite_MatrixBase ()
Unit test for testing correctness of the LDLT decomposition of a symmetric matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
void Cholesky_MatrixBase ()
Unit test for testing correctness of the Cholesky (LLT) decomposition of a symmetric positive definite matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
void Cholesky_PositiveSemidefinite_MatrixBase ()
Unit test for testing correctness of the Cholesky (LLT) decomposition of a symmetric positive SEMIdefinite matrix. Decomposition in this case must throw an exception of type InvalidOperationException.
void QrGrammSchmidt_MatrixBase ()
Verifies correctness of the QR decomposition performed by the Gramm-Schmidt method, on a 6 by 6 randomly generated matrix. The product and orthonormality of the Q factor are verified.
void Qr_MatrixBase ()
Verifies correctness of the QR decomposition performed by the Gramm-Schmidt method, on a 6 by 6 randomly generated matrix. The product and orthonormality of the Q factor are verified.
Detailed Description
Unit tests for matrix decompositions.
$A Igor Dec14 Mar15;
Member Function Documentation
LU_MatrixBase() [1/2]
void IG.Test.TestMatrixDecomposition.LU_MatrixBase () inline
Unit test for testing correctness of the LU decomposition of an invertible matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
References IG.Num.A, IG.Num.Matrix.Identity(), IG.Num.MatrixBase.LuDecompose(), IG.Num.MatrixBase.LuDeterminant(), IG.Num.MatrixBase.LuExtractLower(), IG.Num.MatrixBase.LuExtractUpper(), IG.Num.MatrixBase.LuInverse(), IG.Num.MatrixBase.LuSolve(), IG.Num.MatrixBase.Multiply(), IG.Num.IVector< T >.Norm, IG.Num.VectorBase.SetRandom(), IG.Num.MatrixBase.SetRandomInvertible(), IG.Num.MatrixBase.SetZero(), IG.Num.VectorBase.Subtract(), IG.Num.MatrixBase.Subtract(), and IG.Num.MatrixBase.UnPermute().
LDLT_MatrixBase() [1/2]
void IG.Test.TestMatrixDecomposition.LDLT_MatrixBase () inline
Unit test for testing correctness of the LDLT decomposition of a symmetric matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
References IG.Num.A, IG.Num.MatrixBase.IsSymmetric(), IG.Num.MatrixBase.LdltDecompose(), IG.Num.MatrixBase.LdltDeterminant(), IG.Num.MatrixBase.LdltExtractDiagonal(), IG.Num.MatrixBase.LdltExtractLower(), IG.Num.MatrixBase.LdltExtractUpper(), IG.Num.MatrixBase.LdltInverse(), IG.Num.MatrixBase.LdltSolve(), IG.Num.MatrixBase.Multiply(), IG.Num.IVector< T >.Norm, IG.Num.MatrixBase.SetIdentity(), IG.Num.VectorBase.SetRandom(), IG.Num.MatrixBase.SetRandomPositiveDefiniteSymmetric(), IG.Num.MatrixBase.SetZero(), IG.Num.VectorBase.Subtract(), and IG.Num.MatrixBase.Subtract().
LDLT_Indefinite_MatrixBase() [1/2]
void IG.Test.TestMatrixDecomposition.LDLT_Indefinite_MatrixBase () inline
Unit test for testing correctness of the LDLT decomposition of a symmetric matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
References IG.Num.A, IG.Num.MatrixBase.IsSymmetric(), IG.Num.MatrixBase.LdltDecompose(), IG.Num.MatrixBase.LdltDeterminant(), IG.Num.MatrixBase.LdltExtractDiagonal(), IG.Num.MatrixBase.LdltExtractLower(), IG.Num.MatrixBase.LdltExtractUpper(), IG.Num.MatrixBase.LdltInverse(), IG.Num.MatrixBase.LdltSolve(), IG.Num.MatrixBase.Multiply(), IG.Num.MatrixBase.MultiplyMatMatTranspPlain(), IG.Num.IRandomGenerator.NextDouble(), IG.Num.IVector< T >.Norm, IG.Num.MatrixBase.SetIdentity(), IG.Num.VectorBase.SetRandom(), IG.Num.MatrixBase.SetRandom(), IG.Num.MatrixBase.SetZero(), IG.Num.VectorBase.Subtract(), and IG.Num.MatrixBase.Subtract().
Cholesky_MatrixBase() [1/2]
void IG.Test.TestMatrixDecomposition.Cholesky_MatrixBase () inline
Unit test for testing correctness of the Cholesky (LLT) decomposition of a symmetric positive definite matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
References IG.Num.A, IG.Num.MatrixBase.CholeskyDecompose(), IG.Num.MatrixBase.CholeskyDeterminant(), IG.Num.MatrixBase.CholeskyExtractLower(), IG.Num.MatrixBase.CholeskyExtractUpper(), IG.Num.MatrixBase.CholeskyInverse(), IG.Num.MatrixBase.CholeskySolve(), IG.Num.MatrixBase.IsSymmetric(), IG.Num.MatrixBase.Multiply(), IG.Num.IVector< T >.Norm, IG.Num.MatrixBase.SetIdentity(), IG.Num.VectorBase.SetRandom(), IG.Num.MatrixBase.SetRandomPositiveDefiniteSymmetric(), IG.Num.MatrixBase.SetZero(), IG.Num.VectorBase.Subtract(), and IG.Num.MatrixBase.Subtract().
Cholesky_PositiveSemidefinite_MatrixBase() [1/2]
void IG.Test.TestMatrixDecomposition.Cholesky_PositiveSemidefinite_MatrixBase () inline
Unit test for testing correctness of the Cholesky (LLT) decomposition of a symmetric positive SEMIdefinite matrix. Decomposition in this case must throw an exception of type InvalidOperationException.
References IG.Num.A, IG.Num.MatrixBase.CholeskyDecompose(), IG.Num.MatrixBase.CholeskyExtractLower(), IG.Num.MatrixBase.CholeskyExtractUpper(), IG.Num.MatrixBase.IsSymmetric(), IG.Num.MatrixBase.Multiply(), IG.Num.MatrixBase.MultiplyMatTranspPlain(), IG.Num.IRandomGenerator.NextInclusive(), IG.Num.VectorBase.SetRandom(), IG.Num.MatrixBase.SetRandom(), and IG.Num.MatrixBase.Subtract().
QrGrammSchmidt_MatrixBase() [1/2]
void IG.Test.TestMatrixDecomposition.QrGrammSchmidt_MatrixBase () inline
Verifies correctness of the QR decomposition performed by the Gramm-Schmidt method, on a 6 by 6 randomly generated matrix. The product and orthonormality of the Q factor are verified.
References IG.Num.A, IG.Num.MatrixBase.Multiply(), IG.Num.VectorBase.Norm2Static(), IG.Num.MatrixBase.QrDecomposeGrammSchmidt(), IG.Num.MatrixBase.QrInverse(), IG.Num.MatrixBase.QrSolve(), IG.Num.MatrixBase.SetIdentity(), IG.Num.IVector< T >.SetRandom(), IG.Num.MatrixBase.SetRandom(), IG.Num.MatrixBase.SetZero(), IG.Num.VectorBase.Subtract(), and IG.Num.MatrixBase.Subtract().
Qr_MatrixBase() [1/2]
void IG.Test.TestMatrixDecomposition.Qr_MatrixBase () inline
Verifies correctness of the QR decomposition performed by the Gramm-Schmidt method, on a 6 by 6 randomly generated matrix. The product and orthonormality of the Q factor are verified.
References IG.Num.A, IG.Num.MatrixBase.Multiply(), IG.Num.VectorBase.Norm2Static(), IG.Num.MatrixBase.QrDecompose(), IG.Num.MatrixBase.QrInverse(), IG.Num.MatrixBase.QrSolve(), IG.Num.MatrixBase.SetIdentity(), IG.Num.IVector< T >.SetRandom(), IG.Num.MatrixBase.SetRandom(), IG.Num.MatrixBase.SetZero(), IG.Num.VectorBase.Subtract(), and IG.Num.MatrixBase.Subtract().
LU_MatrixBase() [2/2]
void IG.Test.TestMatrixDecomposition.LU_MatrixBase () inline
Unit test for testing correctness of the LU decomposition of an invertible matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
References IG.Num.A, NUnit.Framework.Assert.AreEqual(), IG.Num.Matrix.Identity(), NUnit.Framework.Assert.IsTrue(), IG.Num.MatrixBase.LuDecompose(), IG.Num.MatrixBase.LuDeterminant(), IG.Num.MatrixBase.LuExtractLower(), IG.Num.MatrixBase.LuExtractUpper(), IG.Num.MatrixBase.LuInverse(), IG.Num.MatrixBase.LuSolve(), IG.Num.MatrixBase.Multiply(), IG.Num.IVector< T >.Norm, IG.Num.VectorBase.SetRandom(), IG.Num.MatrixBase.SetRandomInvertible(), IG.Num.MatrixBase.SetZero(), IG.Num.VectorBase.Subtract(), IG.Num.MatrixBase.Subtract(), and IG.Num.MatrixBase.UnPermute().
LDLT_MatrixBase() [2/2]
void IG.Test.TestMatrixDecomposition.LDLT_MatrixBase () inline
Unit test for testing correctness of the LDLT decomposition of a symmetric matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
References IG.Num.A, NUnit.Framework.Assert.AreEqual(), IG.Num.MatrixBase.IsSymmetric(), NUnit.Framework.Assert.IsTrue(), IG.Num.MatrixBase.LdltDecompose(), IG.Num.MatrixBase.LdltDeterminant(), IG.Num.MatrixBase.LdltExtractDiagonal(), IG.Num.MatrixBase.LdltExtractLower(), IG.Num.MatrixBase.LdltExtractUpper(), IG.Num.MatrixBase.LdltInverse(), IG.Num.MatrixBase.LdltSolve(), IG.Num.MatrixBase.Multiply(), IG.Num.IVector< T >.Norm, IG.Num.MatrixBase.SetIdentity(), IG.Num.VectorBase.SetRandom(), IG.Num.MatrixBase.SetRandomPositiveDefiniteSymmetric(), IG.Num.MatrixBase.SetZero(), IG.Num.VectorBase.Subtract(), and IG.Num.MatrixBase.Subtract().
LDLT_Indefinite_MatrixBase() [2/2]
void IG.Test.TestMatrixDecomposition.LDLT_Indefinite_MatrixBase () inline
Unit test for testing correctness of the LDLT decomposition of a symmetric matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
References IG.Num.A, NUnit.Framework.Assert.AreEqual(), IG.Num.MatrixBase.IsSymmetric(), NUnit.Framework.Assert.IsTrue(), IG.Num.MatrixBase.LdltDecompose(), IG.Num.MatrixBase.LdltDeterminant(), IG.Num.MatrixBase.LdltExtractDiagonal(), IG.Num.MatrixBase.LdltExtractLower(), IG.Num.MatrixBase.LdltExtractUpper(), IG.Num.MatrixBase.LdltInverse(), IG.Num.MatrixBase.LdltSolve(), IG.Num.MatrixBase.Multiply(), IG.Num.MatrixBase.MultiplyMatMatTranspPlain(), IG.Num.IRandomGenerator.NextDouble(), IG.Num.IVector< T >.Norm, IG.Num.MatrixBase.SetIdentity(), IG.Num.VectorBase.SetRandom(), IG.Num.MatrixBase.SetRandom(), IG.Num.MatrixBase.SetZero(), IG.Num.VectorBase.Subtract(), and IG.Num.MatrixBase.Subtract().
Cholesky_MatrixBase() [2/2]
void IG.Test.TestMatrixDecomposition.Cholesky_MatrixBase () inline
Unit test for testing correctness of the Cholesky (LLT) decomposition of a symmetric positive definite matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
References IG.Num.A, NUnit.Framework.Assert.AreEqual(), IG.Num.MatrixBase.CholeskyDecompose(), IG.Num.MatrixBase.CholeskyDeterminant(), IG.Num.MatrixBase.CholeskyExtractLower(), IG.Num.MatrixBase.CholeskyExtractUpper(), IG.Num.MatrixBase.CholeskyInverse(), IG.Num.MatrixBase.CholeskySolve(), IG.Num.MatrixBase.IsSymmetric(), NUnit.Framework.Assert.IsTrue(), IG.Num.MatrixBase.Multiply(), IG.Num.IVector< T >.Norm, IG.Num.MatrixBase.SetIdentity(), IG.Num.VectorBase.SetRandom(), IG.Num.MatrixBase.SetRandomPositiveDefiniteSymmetric(), IG.Num.MatrixBase.SetZero(), IG.Num.VectorBase.Subtract(), and IG.Num.MatrixBase.Subtract().
Cholesky_PositiveSemidefinite_MatrixBase() [2/2]
void IG.Test.TestMatrixDecomposition.Cholesky_PositiveSemidefinite_MatrixBase () inline
Unit test for testing correctness of the Cholesky (LLT) decomposition of a symmetric positive SEMIdefinite matrix. Decomposition in this case must throw an exception of type InvalidOperationException.
References IG.Num.A, NUnit.Framework.Assert.AreEqual(), IG.Num.MatrixBase.CholeskyDecompose(), IG.Num.MatrixBase.CholeskyExtractLower(), IG.Num.MatrixBase.CholeskyExtractUpper(), IG.Num.MatrixBase.IsSymmetric(), NUnit.Framework.Assert.IsTrue(), IG.Num.MatrixBase.Multiply(), IG.Num.MatrixBase.MultiplyMatTranspPlain(), IG.Num.IRandomGenerator.NextInclusive(), IG.Num.VectorBase.SetRandom(), IG.Num.MatrixBase.SetRandom(), IG.Num.MatrixBase.Subtract(), and NUnit.Framework.Assert.Throws().
QrGrammSchmidt_MatrixBase() [2/2]
void IG.Test.TestMatrixDecomposition.QrGrammSchmidt_MatrixBase () inline
Verifies correctness of the QR decomposition performed by the Gramm-Schmidt method, on a 6 by 6 randomly generated matrix. The product and orthonormality of the Q factor are verified.
References IG.Num.A, NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Assert.IsTrue(), IG.Num.MatrixBase.Multiply(), IG.Num.VectorBase.Norm2Static(), IG.Num.MatrixBase.QrDecomposeGrammSchmidt(), IG.Num.MatrixBase.QrInverse(), IG.Num.MatrixBase.QrSolve(), IG.Num.MatrixBase.SetIdentity(), IG.Num.IVector< T >.SetRandom(), IG.Num.MatrixBase.SetRandom(), IG.Num.MatrixBase.SetZero(), IG.Num.VectorBase.Subtract(), and IG.Num.MatrixBase.Subtract().
Qr_MatrixBase() [2/2]
void IG.Test.TestMatrixDecomposition.Qr_MatrixBase () inline
Verifies correctness of the QR decomposition performed by the Gramm-Schmidt method, on a 6 by 6 randomly generated matrix. The product and orthonormality of the Q factor are verified.
References IG.Num.A, NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Assert.IsTrue(), IG.Num.MatrixBase.Multiply(), IG.Num.VectorBase.Norm2Static(), IG.Num.MatrixBase.QrDecompose(), IG.Num.MatrixBase.QrInverse(), IG.Num.MatrixBase.QrSolve(), IG.Num.MatrixBase.SetIdentity(), IG.Num.IVector< T >.SetRandom(), IG.Num.MatrixBase.SetRandom(), IG.Num.MatrixBase.SetZero(), IG.Num.VectorBase.Subtract(), and IG.Num.MatrixBase.Subtract().
The documentation for this class was generated from the following file:
unittests/MSTests/TestNumeric/TstMatrixDecomposition.cs