Doc: IGLib EXTENDED: NUnitLite.TextRunner Class Reference
NUnitLite.TextRunner Class Reference
TextRunner is a general purpose class that runs tests and outputs to a text-based user interface (TextUI).
Public Member Functions
TextRunner (TextUI textUI, NUnitLiteOptions options)
Initializes a new instance of the TextRunner class.
int Execute ()
int Execute (Assembly callingAssembly)
Execute a test run
void ReportResults (ITestResult result)
void TestStarted (ITest test)
Called when a test or suite has just started
void TestFinished (ITestResult result)
Called when a test has finished
Static Public Member Functions
static Dictionary< string, object > MakeRunSettings (NUnitLiteOptions options)
Make the settings for this run - this is public for testing
static TestFilter CreateTestFilter (NUnitLiteOptions options)
Create the test filter for this run - public for testing
Static Public Attributes
const int OK = 0
OK
const int INVALID_ARG = -1
Invalid Arguments
const int FILE_NOT_FOUND = -2
File not found
const int FIXTURE_NOT_FOUND = -3
Test fixture not found
const int UNEXPECTED_ERROR = -100
Unexpected error occurred
Properties
ResultSummary Summary [get, private set]
Private Member Functions
int RunTests (TestFilter filter, IDictionary runSettings)
int ExploreTests ()
Private Attributes
readonly List< Assembly > _assemblies = new List<Assembly>()
ITestAssemblyRunner _runner
NUnitLiteOptions _options
TeamCityEventListener _teamCity
TextUI _textUI
Detailed Description
TextRunner is a general purpose class that runs tests and outputs to a text-based user interface (TextUI).
Call it from your Main like this: new TextRunner(textWriter).Execute(args); OR new TextUI().Execute(args); The provided TextWriter is used by default, unless the arguments to Execute override it using -out. The second form uses the Console, provided it exists on the platform.
NOTE: When running on a platform without a Console, such as Windows Phone, the results will simply not appear if you fail to specify a file in the call itself or as an option.
Constructor & Destructor Documentation
TextRunner()
NUnitLite.TextRunner.TextRunner (TextUI textUI, NUnitLiteOptions options) inline
Initializes a new instance of the TextRunner class.
Parameters
textUI The text-based user interface to output results of the run
options The options to use when running the test
Member Function Documentation
Execute() [1/2]
int NUnitLite.TextRunner.Execute () inline
Referenced by NUnitLite.AutoRun.Execute().
Execute() [2/2]
int NUnitLite.TextRunner.Execute (Assembly callingAssembly) inline
Execute a test run
Parameters
callingAssembly The assembly from which tests are loaded
References NUnitLite.TextRunner._assemblies, NUnitLite.TextRunner._options, NUnitLite.TextRunner._runner, NUnitLite.TextRunner._textUI, NUnitLite.TextRunner.CreateTestFilter(), NUnitLite.TextUI.DisplayError(), NUnitLite.TextUI.DisplayTestFilters(), NUnit.Framework.Internal.TestFilter.Empty, NUnit.Common.CommandLineOptions.Explore, NUnitLite.TextRunner.ExploreTests(), NUnitLite.TextRunner.FILE_NOT_FOUND, NUnit.Common.AssemblyHelper.GetAssemblyName(), NUnit.Common.CommandLineOptions.InputFiles, NUnit.Framework.Api.ITestAssemblyRunner.Load(), NUnit.Common.AssemblyHelper.Load(), NUnitLite.TextRunner.MakeRunSettings(), NUnitLite.TextRunner.OK, NUnitLite.TextRunner.RunTests(), and NUnitLite.TextRunner.UNEXPECTED_ERROR.
RunTests()
int NUnitLite.TextRunner.RunTests (TestFilter filter, IDictionary runSettings) inline private
References NUnitLite.TextRunner._options, NUnitLite.TextRunner._runner, NUnitLite.TextRunner._textUI, NUnitLite.ResultSummary.ErrorCount, NUnitLite.ResultSummary.FailureCount, NUnitLite.ResultSummary.InvalidCount, NUnitLite.TextRunner.ReportResults(), NUnit.Common.CommandLineOptions.ResultOutputSpecifications, NUnit.Framework.Api.ITestAssemblyRunner.Run(), NUnitLite.TextRunner.Summary, NUnitLite.TextUI.TestFinished(), and NUnit.Common.CommandLineOptions.WorkDirectory.
Referenced by NUnitLite.TextRunner.Execute().
ReportResults()
void NUnitLite.TextRunner.ReportResults (ITestResult result) inline
References NUnitLite.TextRunner._options, NUnitLite.TextRunner._textUI, NUnitLite.TextUI.DisplayErrorsAndFailuresReport(), NUnitLite.TextUI.DisplayNotRunReport(), NUnitLite.TextUI.DisplayRunSettings(), NUnitLite.TextUI.DisplaySummaryReport(), NUnitLite.ResultSummary.ExplicitCount, NUnit.Common.CommandLineOptions.Full, NUnitLite.ResultSummary.IgnoreCount, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnitLite.ResultSummary.SkipCount, NUnit.Framework.Interfaces.ResultState.Status, and NUnitLite.TextRunner.Summary.
Referenced by NUnitLite.TextRunner.RunTests().
ExploreTests()
int NUnitLite.TextRunner.ExploreTests () inline private
References NUnitLite.TextRunner._options, NUnitLite.TextRunner._runner, NUnit.Common.CommandLineOptions.ExploreOutputSpecifications, NUnit.Framework.Api.ITestAssemblyRunner.LoadedTest, NUnitLite.TextRunner.OK, NUnit.Common.CommandLineOptions.WorkDirectory, and NUnitLite.TestCaseOutputWriter.WriteTestFile().
Referenced by NUnitLite.TextRunner.Execute().
MakeRunSettings()
static Dictionary<string, object> NUnitLite.TextRunner.MakeRunSettings (NUnitLiteOptions options) inline static
Make the settings for this run - this is public for testing
References NUnit.Common.CommandLineOptions.DefaultTimeout, NUnit.Common.PackageSettings.DefaultTimeout, NUnit.Common.CommandLineOptions.RandomSeed, NUnit.Common.PackageSettings.RandomSeed, NUnit.Common.CommandLineOptions.StopOnError, NUnit.Common.PackageSettings.StopOnError, NUnit.Common.PackageSettings.WorkDirectory, and NUnit.Common.CommandLineOptions.WorkDirectory.
Referenced by NUnitLite.TextRunner.Execute(), NUnitLite.Tests.MakeRunSettingsTests.WhenSeedIsSpecified_RunSettingsIncludeIt(), NUnitLite.Tests.MakeRunSettingsTests.WhenTimeoutIsSpecified_RunSettingsIncludeIt(), and NUnitLite.Tests.MakeRunSettingsTests.WhenWorkDirectoryIsSpecified_RunSettingsIncludeIt().
CreateTestFilter()
static TestFilter NUnitLite.TextRunner.CreateTestFilter (NUnitLiteOptions options) inline static
Create the test filter for this run - public for testing
Parameters
options
Returns
References NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Interfaces.TNode.FromXml(), NUnit.Framework.Internal.TestFilter.IsEmpty, NUnit.Common.TestSelectionParser.Parse(), NUnit.Common.CommandLineOptions.TestList, NUnit.Common.CommandLineOptions.WhereClause, and NUnit.Common.CommandLineOptions.WhereClauseSpecified.
Referenced by NUnitLite.TextRunner.Execute(), NUnitLite.Tests.CreateTestFilterTests.GetFilter(), and NUnitLite.Tests.CreateTestFilterTests.TestListFileMissing().
TestStarted()
void NUnitLite.TextRunner.TestStarted (ITest test) inline
Called when a test or suite has just started
Parameters
test The test that is starting
Implements NUnit.Framework.Interfaces.ITestListener.
References NUnitLite.TextRunner._teamCity, and NUnitLite.TeamCityEventListener.TestStarted().
TestFinished()
void NUnitLite.TextRunner.TestFinished (ITestResult result) inline
Called when a test has finished
Parameters
result The result of the test
Implements NUnit.Framework.Interfaces.ITestListener.
References NUnitLite.TextRunner._teamCity, NUnitLite.TextRunner._textUI, NUnit.Framework.Interfaces.ITestResult.Output, NUnitLite.TeamCityEventListener.TestFinished(), and NUnitLite.TextUI.TestFinished().
Member Data Documentation
OK
const int NUnitLite.TextRunner.OK = 0 static
OK
Referenced by NUnitLite.AutoRun.Execute(), NUnitLite.TextRunner.Execute(), and NUnitLite.TextRunner.ExploreTests().
INVALID_ARG
const int NUnitLite.TextRunner.INVALID_ARG = -1 static
Invalid Arguments
Referenced by NUnitLite.AutoRun.Execute().
FILE_NOT_FOUND
const int NUnitLite.TextRunner.FILE_NOT_FOUND = -2 static
File not found
Referenced by NUnitLite.TextRunner.Execute().
FIXTURE_NOT_FOUND
const int NUnitLite.TextRunner.FIXTURE_NOT_FOUND = -3 static
Test fixture not found
UNEXPECTED_ERROR
const int NUnitLite.TextRunner.UNEXPECTED_ERROR = -100 static
Unexpected error occurred
Referenced by NUnitLite.TextRunner.Execute().
_assemblies
readonly List<Assembly> NUnitLite.TextRunner._assemblies = new List<Assembly>() private
Referenced by NUnitLite.TextRunner.Execute().
_runner
ITestAssemblyRunner NUnitLite.TextRunner._runner private
Referenced by NUnitLite.TextRunner.Execute(), NUnitLite.TextRunner.ExploreTests(), and NUnitLite.TextRunner.RunTests().
_options
NUnitLiteOptions NUnitLite.TextRunner._options private
Referenced by NUnitLite.TextRunner.Execute(), NUnitLite.TextRunner.ExploreTests(), NUnitLite.TextRunner.ReportResults(), and NUnitLite.TextRunner.RunTests().
_teamCity
TeamCityEventListener NUnitLite.TextRunner._teamCity private
Referenced by NUnitLite.TextRunner.TestFinished(), and NUnitLite.TextRunner.TestStarted().
_textUI
TextUI NUnitLite.TextRunner._textUI private
Referenced by NUnitLite.TextRunner.Execute(), NUnitLite.TextRunner.ReportResults(), NUnitLite.TextRunner.RunTests(), and NUnitLite.TextRunner.TestFinished().
Property Documentation
Summary
ResultSummary NUnitLite.TextRunner.Summary get private set
Referenced by NUnitLite.TextRunner.ReportResults(), and NUnitLite.TextRunner.RunTests().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/nunitlite.runner/TextRunner.cs