Doc: IGLib EXTENDED: NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests Class Reference
NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests Class Reference
Public Member Functions
void MakeFixture ()
void TopLevelSuiteIsNamedCorrectly ()
void SuiteHasCorrectNumberOfInstances ()
void FixtureInstancesAreNamedCorrectly ()
void MethodWithoutParamsIsNamedCorrectly ()
void MethodWithParamsIsNamedCorrectly ()
Private Attributes
TestSuite fixture
Member Function Documentation
MakeFixture()
void NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.MakeFixture () inline
References NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.fixture, and NUnit.TestUtilities.TestBuilder.MakeFixture().
TopLevelSuiteIsNamedCorrectly()
void NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.TopLevelSuiteIsNamedCorrectly () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.fixture, NUnit.Framework.Internal.Test.FullName, NUnit.Framework.Internal.Test.Name, and NUnit.Framework.Assert.That().
SuiteHasCorrectNumberOfInstances()
void NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.SuiteHasCorrectNumberOfInstances () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.fixture, NUnit.Framework.Internal.TestSuite.Tests, and NUnit.Framework.Assert.That().
FixtureInstancesAreNamedCorrectly()
void NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.FixtureInstancesAreNamedCorrectly () inline
References NUnit.Framework.Is.EquivalentTo(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.fixture, NUnit.Framework.Internal.Test.FullName, NUnit.Framework.Internal.Test.Name, NUnit.Framework.Internal.TestSuite.Tests, and NUnit.Framework.Assert.That().
MethodWithoutParamsIsNamedCorrectly()
void NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.MethodWithoutParamsIsNamedCorrectly () inline
References NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestFinder.Find(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.fixture, NUnit.Framework.Internal.Test.FullName, NUnit.Framework.Is.Not, NUnit.Framework.Internal.TestSuite.Tests, and NUnit.Framework.Assert.That().
MethodWithParamsIsNamedCorrectly()
void NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.MethodWithParamsIsNamedCorrectly () inline
References NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestFinder.Find(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.fixture, NUnit.Framework.Internal.Test.FullName, NUnit.Framework.Internal.Test.Name, NUnit.Framework.Is.Not, NUnit.Framework.Internal.TestSuite.Tests, and NUnit.Framework.Assert.That().
Member Data Documentation
fixture
TestSuite NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.fixture private
Referenced by NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.FixtureInstancesAreNamedCorrectly(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.MakeFixture(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.MethodWithoutParamsIsNamedCorrectly(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.MethodWithParamsIsNamedCorrectly(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.SuiteHasCorrectNumberOfInstances(), and NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.TopLevelSuiteIsNamedCorrectly().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/ParameterizedTestFixtureTests.cs