Doc: IGLib EXTENDED: CShellCore.CodeCompletion.CSharpCompletion Class Reference
CShellCore.CodeCompletion.CSharpCompletion Class Reference
Public Member Functions
CSharpCompletion ()
CSharpCompletion (ICSharpScriptProvider scriptProvider)
void AddAssembly (string file)
void ProcessInput (string input, string sourceFile)
CodeCompletionResult GetCompletions (IDocument document, int offset)
CodeCompletionResult GetCompletions (IDocument document, int offset, bool controlSpace)
CodeCompletionResult GetCompletions (IDocument document, int offset, bool controlSpace, string usings)
Properties
ICSharpScriptProvider ScriptProvider [get, set]
Private Member Functions
XmlDocumentationProvider GetXmlDocumentation (string dllPath)
Private Attributes
IProjectContent projectContent
Constructor & Destructor Documentation
CSharpCompletion() [1/2]
CShellCore.CodeCompletion.CSharpCompletion.CSharpCompletion () inline
References CShellCore.CodeCompletion.CSharpCompletion.GetXmlDocumentation(), and CShellCore.CodeCompletion.CSharpCompletion.projectContent.
CSharpCompletion() [2/2]
CShellCore.CodeCompletion.CSharpCompletion.CSharpCompletion (ICSharpScriptProvider scriptProvider) inline
References CShellCore.CodeCompletion.CSharpCompletion.ScriptProvider.
Member Function Documentation
GetXmlDocumentation()
XmlDocumentationProvider CShellCore.CodeCompletion.CSharpCompletion.GetXmlDocumentation (string dllPath) inline private
Referenced by CShellCore.CodeCompletion.CSharpCompletion.AddAssembly(), and CShellCore.CodeCompletion.CSharpCompletion.CSharpCompletion().
AddAssembly()
void CShellCore.CodeCompletion.CSharpCompletion.AddAssembly (string file) inline
References CShellCore.CodeCompletion.CSharpCompletion.GetXmlDocumentation(), and CShellCore.CodeCompletion.CSharpCompletion.projectContent.
Referenced by CShell.ScriptingEngine.ReferenceAssembly().
ProcessInput()
void CShellCore.CodeCompletion.CSharpCompletion.ProcessInput (string input, string sourceFile) inline
References CShellCore.CodeCompletion.CSharpCompletion.projectContent.
Referenced by CShell.ScriptingEngine.Evaluate().
GetCompletions() [1/3]
CodeCompletionResult CShellCore.CodeCompletion.CSharpCompletion.GetCompletions (IDocument document, int offset) inline
Referenced by CShellCore.CodeCompletion.CSharpCompletion.GetCompletions(), and CShellCore.CodeCompletion.CodeTextEditor.ShowCompletion().
GetCompletions() [2/3]
CodeCompletionResult CShellCore.CodeCompletion.CSharpCompletion.GetCompletions (IDocument document, int offset, bool controlSpace) inline
References CShellCore.CodeCompletion.CSharpCompletion.GetCompletions(), CShellCore.CodeCompletion.ICSharpScriptProvider.GetUsing(), and CShellCore.CodeCompletion.CSharpCompletion.ScriptProvider.
GetCompletions() [3/3]
CodeCompletionResult CShellCore.CodeCompletion.CSharpCompletion.GetCompletions (IDocument document, int offset, bool controlSpace, string usings) inline
References CShellCore.CodeCompletion.CSharpCompletion.projectContent, and CShellCore.CodeCompletion.DataItems.CompletionData.TriggerWord.
Member Data Documentation
projectContent
IProjectContent CShellCore.CodeCompletion.CSharpCompletion.projectContent private
Referenced by CShellCore.CodeCompletion.CSharpCompletion.AddAssembly(), CShellCore.CodeCompletion.CSharpCompletion.CSharpCompletion(), CShellCore.CodeCompletion.CSharpCompletion.GetCompletions(), and CShellCore.CodeCompletion.CSharpCompletion.ProcessInput().
Property Documentation
ScriptProvider
ICSharpScriptProvider CShellCore.CodeCompletion.CSharpCompletion.ScriptProvider get set
Referenced by CShellCore.CodeCompletion.CSharpCompletion.CSharpCompletion(), and CShellCore.CodeCompletion.CSharpCompletion.GetCompletions().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore.CodeCompletion/CSharpCompletion.cs