Doc: IGLib EXTENDED: NUnit.Engine.Runners.Tests.ParallelTaskWorkerPoolTests Class Reference
NUnit.Engine.Runners.Tests.ParallelTaskWorkerPoolTests Class Reference
Classes
class BusyTask
class NoOpTask
Public Member Functions
void RequiresAtLeastOneThread (int numThreads)
void EnqueueCannotBeCalledAfterWorkHasStarted ()
void WaitAll_SingleTask ()
void WaitAll_SingleThread_MultipleTasks ()
void WaitAll_TwoThreads_MultipleTasks ()
Private Types
enum BusyTaskState { BusyTaskState.Queued, BusyTaskState.Executing, BusyTaskState.Completed }
Member Enumeration Documentation
BusyTaskState
enum NUnit.Engine.Runners.Tests.ParallelTaskWorkerPoolTests.BusyTaskState strong private
Enumerator
Queued
Executing
Completed
Member Function Documentation
RequiresAtLeastOneThread()
void NUnit.Engine.Runners.Tests.ParallelTaskWorkerPoolTests.RequiresAtLeastOneThread (int numThreads) inline
References NUnit.Framework.Assert.Throws().
EnqueueCannotBeCalledAfterWorkHasStarted()
void NUnit.Engine.Runners.Tests.ParallelTaskWorkerPoolTests.EnqueueCannotBeCalledAfterWorkHasStarted () inline
References NUnit.Framework.Assert.Throws().
WaitAll_SingleTask()
void NUnit.Engine.Runners.Tests.ParallelTaskWorkerPoolTests.WaitAll_SingleTask () inline
References NUnit.Framework.Assert.IsFalse(), and NUnit.Framework.Assert.IsTrue().
WaitAll_SingleThread_MultipleTasks()
void NUnit.Engine.Runners.Tests.ParallelTaskWorkerPoolTests.WaitAll_SingleThread_MultipleTasks () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Assert.IsFalse(), and NUnit.Framework.Assert.IsTrue().
WaitAll_TwoThreads_MultipleTasks()
void NUnit.Engine.Runners.Tests.ParallelTaskWorkerPoolTests.WaitAll_TwoThreads_MultipleTasks () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Assert.IsFalse(), and NUnit.Framework.Assert.IsTrue().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Runners/ParallelTaskWorkerPoolTests.cs