Doc: IGLib EXTENDED: AForge.Video.Kinect.KinectVideoCamera Class Reference
AForge.Video.Kinect.KinectVideoCamera Class Reference
Video source for Microsoft Kinect's video camera.
Public Member Functions
KinectVideoCamera (int deviceID)
Initializes a new instance of the KinectVideoCamera class.
KinectVideoCamera (int deviceID, CameraResolution resolution)
Initializes a new instance of the KinectVideoCamera class.
KinectVideoCamera (int deviceID, CameraResolution resolution, VideoCameraMode cameraMode)
Initializes a new instance of the KinectVideoCamera class.
void Start ()
Start video source.
void SignalToStop ()
Signal video source to stop its work.
void WaitForStop ()
Wait for video source has stopped.
void Stop ()
Stop video source.
Properties
VideoCameraMode CameraMode [get, set]
Specifies video mode for the camera.
CameraResolution Resolution [get, set]
Resolution of video camera to set.
virtual string Source [get]
A string identifying the video source.
bool IsRunning [get]
State of the video source.
long BytesReceived [get]
Received bytes count.
int FramesReceived [get]
Received frames count.
Properties inherited from AForge.Video.IVideoSource
string Source [get]
Video source.
int FramesReceived [get]
Received frames count.
long BytesReceived [get]
Received bytes count.
bool IsRunning [get]
State of the video source.
Events
NewFrameEventHandler NewFrame
New frame event.
VideoSourceErrorEventHandler VideoSourceError
Video source error event.
PlayingFinishedEventHandler PlayingFinished
Video playing finished event.
Events inherited from AForge.Video.IVideoSource
NewFrameEventHandler NewFrame
New frame event.
VideoSourceErrorEventHandler VideoSourceError
Video source error event.
PlayingFinishedEventHandler PlayingFinished
Video playing finished event.
Private Member Functions
void HandleDataReceived (IntPtr device, IntPtr imageData, UInt32 timeStamp)
Private Attributes
int deviceID
int framesReceived
long bytesReceived
VideoCameraMode cameraMode = VideoCameraMode.Color
CameraResolution resolution = CameraResolution.Medium
object sync = new object()
Kinect device = null
IntPtr imageBuffer = IntPtr.Zero
KinectNative.BitmapInfoHeader videoModeInfo
KinectNative.FreenectVideoDataCallback videoCallback = null
Static Private Attributes
static List< int > runningCameras = new List<int>()
Detailed Description
Video source for Microsoft Kinect's video camera.
The video source captures video data from Microsoft Kinect video camera, which is aimed originally as a gaming device for XBox 360 platform.
<note>Prior to using the class, make sure you've installed Kinect's drivers as described on Open Kinect project's page.</note>
<note>In order to run correctly the class requires freenect.dll library to be put into solution's output folder. This can be found within the AForge.NET framework's distribution in Externals folder.</note>
Sample usage:
// create video source
KinectVideoCamera videoSource = new KinectVideoCamera(0);
// set NewFrame event handler
videoSource.NewFrame += new NewFrameEventHandler(video_NewFrame);
// start the video source
videoSource.Start();
// ...
private void video_NewFrame(object sender, NewFrameEventArgs eventArgs)
{
    // get new frame
    Bitmap bitmap = eventArgs.Frame;
    // process the frame
}
Constructor & Destructor Documentation
KinectVideoCamera() [1/3]
AForge.Video.Kinect.KinectVideoCamera.KinectVideoCamera (int deviceID) inline
Initializes a new instance of the KinectVideoCamera class.
Parameters
deviceID Kinect's device ID (index) to connect to.
References AForge.Video.Kinect.KinectVideoCamera.deviceID.
KinectVideoCamera() [2/3]
AForge.Video.Kinect.KinectVideoCamera.KinectVideoCamera (int deviceID, CameraResolution resolution) inline
Initializes a new instance of the KinectVideoCamera class.
Parameters
deviceID Kinect's device ID (index) to connect to.
resolution Resolution of video camera to set.
References AForge.Video.Kinect.KinectVideoCamera.deviceID, and AForge.Video.Kinect.KinectVideoCamera.resolution.
KinectVideoCamera() [3/3]
AForge.Video.Kinect.KinectVideoCamera.KinectVideoCamera (int deviceID, CameraResolution resolution, VideoCameraMode cameraMode) inline
Initializes a new instance of the KinectVideoCamera class.
Parameters
deviceID Kinect's device ID (index) to connect to.
resolution Resolution of video camera to set.
cameraMode Sets video camera mode.
References AForge.Video.Kinect.KinectVideoCamera.cameraMode, AForge.Video.Kinect.KinectVideoCamera.deviceID, and AForge.Video.Kinect.KinectVideoCamera.resolution.
Member Function Documentation
Start()
void AForge.Video.Kinect.KinectVideoCamera.Start () inline
Start video source.
Starts video source and returns execution to caller. Video camera will be started and will provide new video frames through the NewFrame event.
Exceptions
ArgumentException The specified resolution is not supported for the selected mode of the Kinect video camera.
ConnectionFailedException Could not connect to Kinect's video camera.
DeviceBusyException Another connection to the specified video camera is already running.
Implements AForge.Video.IVideoSource.
References AForge.Video.Kinect.KinectVideoCamera.cameraMode, AForge.Video.Kinect.KinectVideoCamera.device, AForge.Video.Kinect.KinectVideoCamera.deviceID, AForge.Video.Kinect.Kinect.Dispose(), AForge.Video.Kinect.Kinect.GetDevice(), AForge.Video.Kinect.KinectVideoCamera.HandleDataReceived(), AForge.Video.Kinect.KinectVideoCamera.imageBuffer, AForge.Video.Kinect.KinectVideoCamera.resolution, AForge.Video.Kinect.KinectVideoCamera.runningCameras, AForge.Video.Kinect.KinectVideoCamera.Stop(), AForge.Video.Kinect.KinectVideoCamera.sync, AForge.Video.Kinect.KinectVideoCamera.videoCallback, and AForge.Video.Kinect.KinectVideoCamera.videoModeInfo.
SignalToStop()
void AForge.Video.Kinect.KinectVideoCamera.SignalToStop () inline
Signal video source to stop its work.
<note>Calling this method is equivalent to calling Stop for Kinect video camera.</note>
Implements AForge.Video.IVideoSource.
References AForge.Video.Kinect.KinectVideoCamera.Stop().
WaitForStop()
void AForge.Video.Kinect.KinectVideoCamera.WaitForStop () inline
Wait for video source has stopped.
<note>Calling this method is equivalent to calling Stop for Kinect video camera.</note>
Implements AForge.Video.IVideoSource.
References AForge.Video.Kinect.KinectVideoCamera.Stop().
Stop()
void AForge.Video.Kinect.KinectVideoCamera.Stop () inline
Stop video source.
The method stops the video source, so it no longer provides new video frames and does not consume any resources.
Implements AForge.Video.IVideoSource.
References AForge.Video.Kinect.KinectVideoCamera.device, AForge.Video.Kinect.KinectVideoCamera.deviceID, AForge.Video.Kinect.Kinect.Dispose(), AForge.Video.Kinect.KinectVideoCamera.imageBuffer, AForge.Video.Kinect.KinectVideoCamera.PlayingFinished, AForge.Video.Kinect.KinectVideoCamera.runningCameras, AForge.Video.Kinect.KinectVideoCamera.sync, and AForge.Video.Kinect.KinectVideoCamera.videoCallback.
Referenced by KinectCapture.MainForm.Disconnect(), AForge.Video.Kinect.KinectVideoCamera.SignalToStop(), AForge.Video.Kinect.KinectVideoCamera.Start(), and AForge.Video.Kinect.KinectVideoCamera.WaitForStop().
HandleDataReceived()
void AForge.Video.Kinect.KinectVideoCamera.HandleDataReceived (IntPtr device, IntPtr imageData, UInt32 timeStamp) inline private
References AForge.Video.Kinect.KinectVideoCamera.bytesReceived, AForge.Video.Kinect.KinectVideoCamera.cameraMode, AForge.SystemTools.CopyUnmanagedMemory(), AForge.Imaging.Image.CreateGrayscaleImage(), AForge.Video.Kinect.KinectVideoCamera.framesReceived, AForge.Video.Kinect.KinectVideoCamera.imageBuffer, AForge.Video.Kinect.KinectVideoCamera.NewFrame, AForge.Math.Geometry.Rectangle, AForge.Video.Kinect.KinectVideoCamera.videoModeInfo, and AForge.Video.Kinect.KinectVideoCamera.VideoSourceError.
Referenced by AForge.Video.Kinect.KinectVideoCamera.Start().
Member Data Documentation
deviceID
int AForge.Video.Kinect.KinectVideoCamera.deviceID private
Referenced by AForge.Video.Kinect.KinectVideoCamera.KinectVideoCamera(), AForge.Video.Kinect.KinectVideoCamera.Start(), and AForge.Video.Kinect.KinectVideoCamera.Stop().
framesReceived
int AForge.Video.Kinect.KinectVideoCamera.framesReceived private
Referenced by AForge.Video.Kinect.KinectVideoCamera.HandleDataReceived().
bytesReceived
long AForge.Video.Kinect.KinectVideoCamera.bytesReceived private
Referenced by AForge.Video.Kinect.KinectVideoCamera.HandleDataReceived().
cameraMode
VideoCameraMode AForge.Video.Kinect.KinectVideoCamera.cameraMode = VideoCameraMode.Color private
Referenced by AForge.Video.Kinect.KinectVideoCamera.HandleDataReceived(), AForge.Video.Kinect.KinectVideoCamera.KinectVideoCamera(), and AForge.Video.Kinect.KinectVideoCamera.Start().
resolution
CameraResolution AForge.Video.Kinect.KinectVideoCamera.resolution = CameraResolution.Medium private
Referenced by AForge.Video.Kinect.KinectVideoCamera.KinectVideoCamera(), and AForge.Video.Kinect.KinectVideoCamera.Start().
runningCameras
List<int> AForge.Video.Kinect.KinectVideoCamera.runningCameras = new List<int>() static private
Referenced by AForge.Video.Kinect.KinectVideoCamera.Start(), and AForge.Video.Kinect.KinectVideoCamera.Stop().
sync
object AForge.Video.Kinect.KinectVideoCamera.sync = new object() private
Referenced by AForge.Video.Kinect.KinectVideoCamera.Start(), and AForge.Video.Kinect.KinectVideoCamera.Stop().
device
Kinect AForge.Video.Kinect.KinectVideoCamera.device = null private
Referenced by AForge.Video.Kinect.KinectVideoCamera.Start(), and AForge.Video.Kinect.KinectVideoCamera.Stop().
imageBuffer
IntPtr AForge.Video.Kinect.KinectVideoCamera.imageBuffer = IntPtr.Zero private
Referenced by AForge.Video.Kinect.KinectVideoCamera.HandleDataReceived(), AForge.Video.Kinect.KinectVideoCamera.Start(), and AForge.Video.Kinect.KinectVideoCamera.Stop().
videoModeInfo
KinectNative.BitmapInfoHeader AForge.Video.Kinect.KinectVideoCamera.videoModeInfo private
Referenced by AForge.Video.Kinect.KinectVideoCamera.HandleDataReceived(), and AForge.Video.Kinect.KinectVideoCamera.Start().
videoCallback
KinectNative.FreenectVideoDataCallback AForge.Video.Kinect.KinectVideoCamera.videoCallback = null private
Referenced by AForge.Video.Kinect.KinectVideoCamera.Start(), and AForge.Video.Kinect.KinectVideoCamera.Stop().
Property Documentation
CameraMode
VideoCameraMode AForge.Video.Kinect.KinectVideoCamera.CameraMode get set
Specifies video mode for the camera.
<note>The property must be set before running the video source to take effect.</note>
Default value of the property is set to VideoCameraMode.Color.
Referenced by KinectCapture.MainForm.Connect().
Resolution
CameraResolution AForge.Video.Kinect.KinectVideoCamera.Resolution get set
Resolution of video camera to set.
<note>The property must be set before running the video source to take effect.</note>
Default value of the property is set to CameraResolution.Medium.
Source
virtual string AForge.Video.Kinect.KinectVideoCamera.Source get
A string identifying the video source.
IsRunning
bool AForge.Video.Kinect.KinectVideoCamera.IsRunning get
State of the video source.
Current state of video source object - running or not.
BytesReceived
long AForge.Video.Kinect.KinectVideoCamera.BytesReceived get
Received bytes count.
Number of bytes the video source provided from the moment of the last access to the property.
FramesReceived
int AForge.Video.Kinect.KinectVideoCamera.FramesReceived get
Received frames count.
Number of frames the video source provided from the moment of the last access to the property.
Event Documentation
NewFrame
NewFrameEventHandler AForge.Video.Kinect.KinectVideoCamera.NewFrame
New frame event.
Notifies clients about new available frames from the video source.
<note>Since video source may have multiple clients, each client is responsible for making a copy (cloning) of the passed video frame, because the video source disposes its own original copy after notifying of clients.</note>
Referenced by AForge.Video.Kinect.KinectVideoCamera.HandleDataReceived().
VideoSourceError
VideoSourceErrorEventHandler AForge.Video.Kinect.KinectVideoCamera.VideoSourceError
Video source error event.
This event is used to notify clients about any type of errors occurred in video source object, for example internal exceptions.
Referenced by AForge.Video.Kinect.KinectVideoCamera.HandleDataReceived().
PlayingFinished
PlayingFinishedEventHandler AForge.Video.Kinect.KinectVideoCamera.PlayingFinished
Video playing finished event.
This event is used to notify clients that the video playing has finished.
Referenced by AForge.Video.Kinect.KinectVideoCamera.Stop().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Video.Kinect/KinectVideoCamera.cs