Doc: IGLib EXTENDED: CShellCore.CodeCompletion.SegmentTrackingOutputFormatter Class Reference
CShellCore.CodeCompletion.SegmentTrackingOutputFormatter Class Reference
Output formatter that creates a dictionary from AST nodes to segments in the output text.
Public Member Functions
SegmentTrackingOutputFormatter (StringWriter stringWriter)
override void StartNode (AstNode node)
override void EndNode (AstNode node)
Static Public Member Functions
static IDictionary< AstNode, ICSharpCode.AvalonEdit.Document.ISegment > WriteNode (StringWriter writer, AstNode node, CSharpFormattingOptions policy, ICSharpCode.AvalonEdit.TextEditorOptions options)
Properties
IDictionary< AstNode, ICSharpCode.AvalonEdit.Document.ISegment > Segments [get]
Private Attributes
Dictionary< AstNode, ICSharpCode.AvalonEdit.Document.ISegment > segments = new Dictionary<AstNode, ICSharpCode.AvalonEdit.Document.ISegment>()
Stack< int > startOffsets = new Stack<int>()
readonly StringWriter stringWriter
Detailed Description
Output formatter that creates a dictionary from AST nodes to segments in the output text.
Constructor & Destructor Documentation
SegmentTrackingOutputFormatter()
CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.SegmentTrackingOutputFormatter (StringWriter stringWriter) inline
References CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.stringWriter.
Referenced by CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.WriteNode().
Member Function Documentation
WriteNode()
static IDictionary<AstNode, ICSharpCode.AvalonEdit.Document.ISegment> CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.WriteNode (StringWriter writer, AstNode node, CSharpFormattingOptions policy, ICSharpCode.AvalonEdit.TextEditorOptions options) inline static
References CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.SegmentTrackingOutputFormatter().
StartNode()
override void CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.StartNode (AstNode node) inline
References CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.startOffsets, and CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.stringWriter.
EndNode()
override void CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.EndNode (AstNode node) inline
References CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.segments, CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.startOffsets, and CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.stringWriter.
Member Data Documentation
segments
Dictionary<AstNode, ICSharpCode.AvalonEdit.Document.ISegment> CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.segments = new Dictionary<AstNode, ICSharpCode.AvalonEdit.Document.ISegment>() private
Referenced by CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.EndNode().
startOffsets
Stack<int> CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.startOffsets = new Stack<int>() private
Referenced by CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.EndNode(), and CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.StartNode().
stringWriter
readonly StringWriter CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.stringWriter private
Referenced by CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.EndNode(), CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.SegmentTrackingOutputFormatter(), and CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.StartNode().
Property Documentation
Segments
IDictionary<AstNode, ICSharpCode.AvalonEdit.Document.ISegment> CShellCore.CodeCompletion.SegmentTrackingOutputFormatter.Segments get
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore.CodeCompletion/SegmentTrackingOutputFormatter.cs