Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLASDQ Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLASDQ Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLASDQ (DBDSQR dbdsqr, DLARTG dlartg, DLASR dlasr, DSWAP dswap, XERBLA xerbla, LSAME lsame)
DLASDQ ()
void Run (string UPLO, int SQRE, int N, int NCVT, int NRU, int NCC, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] VT, int offset_vt, int LDVT, ref double[] U, int offset_u, int LDU, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
DBDSQR _dbdsqr
DLARTG _dlartg
DLASR _dlasr
DSWAP _dswap
XERBLA _xerbla
LSAME _lsame
Static Private Attributes
const double ZERO = 0.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLASDQ computes the singular value decomposition (SVD) of a real (upper or lower) bidiagonal matrix with diagonal D and offdiagonal E, accumulating the transformations if desired. Letting B denote the input bidiagonal matrix, the algorithm computes orthogonal matrices Q and P such that B = Q * S * P' (P' denotes the transpose of P). The singular values S are overwritten on D.
The input matrix U is changed to U * Q if desired. The input matrix VT is changed to P' * VT if desired. The input matrix C is changed to Q' * C if desired.
See "Computing Small Singular Values of Bidiagonal Matrices With Guaranteed High Relative Accuracy," by J. Demmel and W. Kahan, LAPACK Working Note #3, for a detailed description of the algorithm.
/summary>
Constructor & Destructor Documentation
DLASDQ() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLASDQ.DLASDQ (DBDSQR dbdsqr, DLARTG dlartg, DLASR dlasr, DSWAP dswap, XERBLA xerbla, LSAME lsame) inline
DLASDQ() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLASDQ.DLASDQ () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLASDQ.Run (string UPLO, int SQRE, int N, int NCVT, int NRU, int NCC, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] VT, int offset_vt, int LDVT, ref double[] U, int offset_u, int LDU, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
DLASDQ computes the singular value decomposition (SVD) of a real (upper or lower) bidiagonal matrix with diagonal D and offdiagonal E, accumulating the transformations if desired. Letting B denote the input bidiagonal matrix, the algorithm computes orthogonal matrices Q and P such that B = Q * S * P' (P' denotes the transpose of P). The singular values S are overwritten on D.
The input matrix U is changed to U * Q if desired. The input matrix VT is changed to P' * VT if desired. The input matrix C is changed to Q' * C if desired.
See "Computing Small Singular Values of Bidiagonal Matrices With Guaranteed High Relative Accuracy," by J. Demmel and W. Kahan, LAPACK Working Note #3, for a detailed description of the algorithm.
/summary>
Parameters
UPLO (input) CHARACTER*1 On entry, UPLO specifies whether the input bidiagonal matrix is upper or lower bidiagonal, and wether it is square are not. UPLO = 'U' or 'u' B is upper bidiagonal. UPLO = 'L' or 'l' B is lower bidiagonal. /param>
Parameters
SQRE (input) INTEGER = 0: then the input matrix is N-by-N. = 1: then the input matrix is N-by-(N+1) if UPLU = 'U' and (N+1)-by-N if UPLU = 'L'.
The bidiagonal matrix has N = NL + NR + 1 rows and M = N + SQRE .GE. N columns. /param>
Parameters
N (input) INTEGER On entry, N specifies the number of rows and columns in the matrix. N must be at least 0. /param>
Parameters
NCVT (input) INTEGER On entry, NCVT specifies the number of columns of the matrix VT. NCVT must be at least 0. /param>
Parameters
NRU (input) INTEGER On entry, NRU specifies the number of rows of the matrix U. NRU must be at least 0. /param>
Parameters
NCC (input) INTEGER On entry, NCC specifies the number of columns of the matrix C. NCC must be at least 0. /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension (N) On entry, D contains the diagonal entries of the bidiagonal matrix whose SVD is desired. On normal exit, D contains the singular values in ascending order. /param>
Parameters
E (input/output) DOUBLE PRECISION array. dimension is (N-1) if SQRE = 0 and N if SQRE = 1. On entry, the entries of E contain the offdiagonal entries of the bidiagonal matrix whose SVD is desired. On normal exit, E will contain 0. If the algorithm does not converge, D and E will contain the diagonal and superdiagonal entries of a bidiagonal matrix orthogonally equivalent to the one given as input. /param>
Parameters
VT (input/output) DOUBLE PRECISION array, dimension (LDVT, NCVT) On entry, contains a matrix which on exit has been premultiplied by P', dimension N-by-NCVT if SQRE = 0 and (N+1)-by-NCVT if SQRE = 1 (not referenced if NCVT=0). /param>
Parameters
LDVT (input) INTEGER On entry, LDVT specifies the leading dimension of VT as declared in the calling (sub) program. LDVT must be at least 1. If NCVT is nonzero LDVT must also be at least N. /param>
Parameters
U (input/output) DOUBLE PRECISION array, dimension (LDU, N) On entry, contains a matrix which on exit has been postmultiplied by Q, dimension NRU-by-N if SQRE = 0 and NRU-by-(N+1) if SQRE = 1 (not referenced if NRU=0). /param>
Parameters
LDU (input) INTEGER On entry, LDU specifies the leading dimension of U as declared in the calling (sub) program. LDU must be at least max(1, NRU) . /param>
Parameters
C (input/output) DOUBLE PRECISION array, dimension (LDC, NCC) On entry, contains an N-by-NCC matrix which on exit has been premultiplied by Q' dimension N-by-NCC if SQRE = 0 and (N+1)-by-NCC if SQRE = 1 (not referenced if NCC=0). /param>
Parameters
LDC (input) INTEGER On entry, LDC specifies the leading dimension of C as declared in the calling (sub) program. LDC must be at least 1. If NCC is nonzero, LDC must also be at least N. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (4*N) Workspace. Only referenced if one of NCVT, NRU, or NCC is nonzero, and if N is at least 2. /param>
Parameters
INFO (output) INTEGER On exit, a value of 0 indicates a successful exit. If INFO .LT. 0, argument number -INFO is illegal. If INFO .GT. 0, the algorithm did not converge, and INFO specifies how many superdiagonals did not converge. /param>
References DotNumerics.LinearAlgebra.CSLapack.DSWAP.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARTG.Run(), DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASR.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLASDQ.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD0.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALSD.Run(), DotNumerics.LinearAlgebra.CSLapack.DBDSDC.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLASDA.Run().
Member Data Documentation
_dbdsqr
DBDSQR DotNumerics.LinearAlgebra.CSLapack.DLASDQ._dbdsqr private
_dlartg
DLARTG DotNumerics.LinearAlgebra.CSLapack.DLASDQ._dlartg private
_dlasr
DLASR DotNumerics.LinearAlgebra.CSLapack.DLASDQ._dlasr private
_dswap
DSWAP DotNumerics.LinearAlgebra.CSLapack.DLASDQ._dswap private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLASDQ._xerbla private
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLASDQ._lsame private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLASDQ.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASDQ.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlasdq.cs