Doc: IGLib EXTENDED: Meta.Numerics.Statistics.Distributions.LogisticDistribution Class Reference
Meta.Numerics.Statistics.Distributions.LogisticDistribution Class Reference
Represents a logistic distribution.
Public Member Functions
LogisticDistribution ()
Initializes a new standard logistic distribution.
LogisticDistribution (double m, double s)
Initializes a new logistic distribution with the given mean and width parameters.
override double ProbabilityDensity (double x)
Returns the probability density at the given point.
override double LeftProbability (double x)
Returns the cumulative probability to the left of (below) the given point.
override double RightProbability (double x)
Return the cumulative probability to the right of (above) the given point.
override double InverseLeftProbability (double P)
Returns the point at which the cumulative distribution function attains a given value.
override double InverseRightProbability (double Q)
Returns the point at which the right probability function attains the given value.
override double Moment (int r)
Computes a raw moment of the distribution.
override double MomentAboutMean (int r)
Computes a central moment of the distribution.
override double Cumulant (int r)
Computes a cumulant of the distribution.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double ExpectationValue (Func< double, double > f)
Computes the expectation value of the given function.
virtual double GetRandomValue (Random rng)
Returns a random value.
Properties
override double Mean [get]
override double Median [get]
override double StandardDeviation [get]
override double Variance [get]
override double Skewness [get]
override double ExcessKurtosis [get]
Properties inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double Median [get]
Gets the median of the distribution.
virtual Interval Support [get]
Gets the interval over which the distribution is nonvanishing.
Properties inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Mean [get]
Gets the mean of the distribution.
virtual double Variance [get]
Gets the variance of the distribution.
virtual double StandardDeviation [get]
Gets the standard deviation of the distribution.
virtual double Skewness [get]
Gets the skewness of the distribution.
virtual double ExcessKurtosis [get]
Gets the excess kurtosis of the distribution.
Private Member Functions
double InverseProbability (double P, double Q)
double[] IParameterizedDistribution. GetParameters ()
Gets the parameter values of the distribution.
void IParameterizedDistribution. SetParameters (IList< double > parameters)
Sets the parameter values of the distribution.
double IParameterizedDistribution. Likelihood (double x)
Gets the likelihood of a value, given the current parameters.
Private Attributes
double m
double s
Detailed Description
Represents a logistic distribution.
Like the normal distribution, the logistic distribution is a symmetric, unimodal distribution distribution with exponentially supressed tails.
A logistic distribution with mean zero and standard deviation one is called a standard logistic distribution. Any logistic distribution can be converted to a standard logistic distribution by reparameterzing into z = (x-m)/s.
Constructor & Destructor Documentation
LogisticDistribution() [1/2]
Meta.Numerics.Statistics.Distributions.LogisticDistribution.LogisticDistribution () inline
Initializes a new standard logistic distribution.
The standard logistic distribution has zero mean and a unit width parameter.
References Meta.Numerics.Statistics.Distributions.LogisticDistribution.m, and Meta.Numerics.Statistics.Distributions.LogisticDistribution.s.
LogisticDistribution() [2/2]
Meta.Numerics.Statistics.Distributions.LogisticDistribution.LogisticDistribution (double m, double s) inline
Initializes a new logistic distribution with the given mean and width parameters.
Parameters
m The mean.
s The width parameter.
References Meta.Numerics.Statistics.Distributions.LogisticDistribution.m, and Meta.Numerics.Statistics.Distributions.LogisticDistribution.s.
Member Function Documentation
ProbabilityDensity()
override double Meta.Numerics.Statistics.Distributions.LogisticDistribution.ProbabilityDensity (double x) inline virtual
Returns the probability density at the given point.
Implements Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.LogisticDistribution.m, and Meta.Numerics.Statistics.Distributions.LogisticDistribution.s.
Referenced by Meta.Numerics.Statistics.Distributions.LogisticDistribution.Likelihood().
LeftProbability()
override double Meta.Numerics.Statistics.Distributions.LogisticDistribution.LeftProbability (double x) inline virtual
Returns the cumulative probability to the left of (below) the given point.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.LogisticDistribution.m, and Meta.Numerics.Statistics.Distributions.LogisticDistribution.s.
RightProbability()
override double Meta.Numerics.Statistics.Distributions.LogisticDistribution.RightProbability (double x) inline virtual
Return the cumulative probability to the right of (above) the given point.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.LogisticDistribution.m, and Meta.Numerics.Statistics.Distributions.LogisticDistribution.s.
InverseLeftProbability()
override double Meta.Numerics.Statistics.Distributions.LogisticDistribution.InverseLeftProbability (double P) inline virtual
Returns the point at which the cumulative distribution function attains a given value.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.LogisticDistribution.InverseProbability().
InverseRightProbability()
override double Meta.Numerics.Statistics.Distributions.LogisticDistribution.InverseRightProbability (double Q) inline virtual
Returns the point at which the right probability function attains the given value.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.LogisticDistribution.InverseProbability().
InverseProbability()
double Meta.Numerics.Statistics.Distributions.LogisticDistribution.InverseProbability (double P, double Q) inline private
References Meta.Numerics.Statistics.Distributions.LogisticDistribution.m, and Meta.Numerics.Statistics.Distributions.LogisticDistribution.s.
Referenced by Meta.Numerics.Statistics.Distributions.LogisticDistribution.InverseLeftProbability(), and Meta.Numerics.Statistics.Distributions.LogisticDistribution.InverseRightProbability().
Moment()
override double Meta.Numerics.Statistics.Distributions.LogisticDistribution.Moment (int r) inline virtual
Computes a raw moment of the distribution.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.MomentMath.CentralToRaw(), and Meta.Numerics.Statistics.Distributions.LogisticDistribution.Mean.
MomentAboutMean()
override double Meta.Numerics.Statistics.Distributions.LogisticDistribution.MomentAboutMean (int r) inline virtual
Computes a central moment of the distribution.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Functions.AdvancedMath.DirichletEta(), Meta.Numerics.Functions.AdvancedIntegerMath.Factorial(), Meta.Numerics.MoreMath.Pow(), and Meta.Numerics.Statistics.Distributions.LogisticDistribution.s.
Cumulant()
override double Meta.Numerics.Statistics.Distributions.LogisticDistribution.Cumulant (int r) inline virtual
Computes a cumulant of the distribution.
Reimplemented from Meta.Numerics.Statistics.Distributions.UnivariateDistribution.
References Meta.Numerics.Functions.AdvancedIntegerMath.Factorial(), Meta.Numerics.Statistics.Distributions.LogisticDistribution.m, Meta.Numerics.MoreMath.Pow(), Meta.Numerics.Functions.AdvancedMath.RiemannZeta(), and Meta.Numerics.Statistics.Distributions.LogisticDistribution.s.
GetParameters()
double [] IParameterizedDistribution. Meta.Numerics.Statistics.Distributions.LogisticDistribution.GetParameters () inline private
Gets the parameter values of the distribution.
Returns
The parameter values characterizing the distribution.
Implements Meta.Numerics.Statistics.Distributions.IParameterizedDistribution.
References Meta.Numerics.Statistics.Distributions.LogisticDistribution.m, and Meta.Numerics.Statistics.Distributions.LogisticDistribution.s.
SetParameters()
void IParameterizedDistribution. Meta.Numerics.Statistics.Distributions.LogisticDistribution.SetParameters (IList< double > parameters) inline private
Sets the parameter values of the distribution.
Parameters
parameters A list of parameter values.
Implements Meta.Numerics.Statistics.Distributions.IParameterizedDistribution.
References Meta.Numerics.Statistics.Distributions.LogisticDistribution.m, and Meta.Numerics.Statistics.Distributions.LogisticDistribution.s.
Likelihood()
double IParameterizedDistribution. Meta.Numerics.Statistics.Distributions.LogisticDistribution.Likelihood (double x) inline private
Gets the likelihood of a value, given the current parameters.
Parameters
x The value.
Returns
The likelihood of the value.
Implements Meta.Numerics.Statistics.Distributions.IParameterizedDistribution.
References Meta.Numerics.Statistics.Distributions.LogisticDistribution.ProbabilityDensity().
Member Data Documentation
m
double Meta.Numerics.Statistics.Distributions.LogisticDistribution.m private
Referenced by Meta.Numerics.Statistics.Distributions.LogisticDistribution.Cumulant(), Meta.Numerics.Statistics.Distributions.LogisticDistribution.GetParameters(), Meta.Numerics.Statistics.Distributions.LogisticDistribution.InverseProbability(), Meta.Numerics.Statistics.Distributions.LogisticDistribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.LogisticDistribution.LogisticDistribution(), Meta.Numerics.Statistics.Distributions.LogisticDistribution.ProbabilityDensity(), Meta.Numerics.Statistics.Distributions.LogisticDistribution.RightProbability(), and Meta.Numerics.Statistics.Distributions.LogisticDistribution.SetParameters().
s
double Meta.Numerics.Statistics.Distributions.LogisticDistribution.s private
Referenced by Meta.Numerics.Statistics.Distributions.LogisticDistribution.Cumulant(), Meta.Numerics.Statistics.Distributions.LogisticDistribution.GetParameters(), Meta.Numerics.Statistics.Distributions.LogisticDistribution.InverseProbability(), Meta.Numerics.Statistics.Distributions.LogisticDistribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.LogisticDistribution.LogisticDistribution(), Meta.Numerics.Statistics.Distributions.LogisticDistribution.MomentAboutMean(), Meta.Numerics.Statistics.Distributions.LogisticDistribution.ProbabilityDensity(), Meta.Numerics.Statistics.Distributions.LogisticDistribution.RightProbability(), and Meta.Numerics.Statistics.Distributions.LogisticDistribution.SetParameters().
Property Documentation
Mean
override double Meta.Numerics.Statistics.Distributions.LogisticDistribution.Mean get
Referenced by Meta.Numerics.Statistics.Distributions.LogisticDistribution.Moment().
Median
override double Meta.Numerics.Statistics.Distributions.LogisticDistribution.Median get
StandardDeviation
override double Meta.Numerics.Statistics.Distributions.LogisticDistribution.StandardDeviation get
Variance
override double Meta.Numerics.Statistics.Distributions.LogisticDistribution.Variance get
Skewness
override double Meta.Numerics.Statistics.Distributions.LogisticDistribution.Skewness get
ExcessKurtosis
override double Meta.Numerics.Statistics.Distributions.LogisticDistribution.ExcessKurtosis get
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/Distributions/LogisticDistribution.cs