Doc: IGLib EXTENDED: NUnit.Common.InternalTrace Class Reference
NUnit.Common.InternalTrace Class Reference
InternalTrace provides facilities for tracing the execution of the NUnit framework. Tests and classes under test may make use of Console writes, System.Diagnostics.Trace or various loggers and NUnit itself traps and processes each of them. For that reason, a separate internal trace is needed.
Static Public Member Functions
static void Initialize (string logName, InternalTraceLevel level)
Initialize the internal trace facility using the name of the log to be written to and the trace level.
static void Initialize (TextWriter writer, InternalTraceLevel level)
Initialize the internal trace using a provided TextWriter and level
static Logger GetLogger (string name)
Get a named Logger
static Logger GetLogger (Type type)
Get a logger named for a particular Type.
Properties
static bool Initialized [get, private set]
Gets a flag indicating whether the InternalTrace is initialized
Static Private Attributes
static InternalTraceLevel traceLevel
static InternalTraceWriter traceWriter
Detailed Description
InternalTrace provides facilities for tracing the execution of the NUnit framework. Tests and classes under test may make use of Console writes, System.Diagnostics.Trace or various loggers and NUnit itself traps and processes each of them. For that reason, a separate internal trace is needed.
Note: InternalTrace uses a global lock to allow multiple threads to write trace messages. This can easily make it a bottleneck so it must be used sparingly. Keep the trace Level as low as possible and only insert InternalTrace writes where they are needed. TODO: add some buffering and a separate writer thread as an option. TODO: figure out a way to turn on trace in specific classes only.
Member Function Documentation
Initialize() [1/2]
static void NUnit.Common.InternalTrace.Initialize (string logName, InternalTraceLevel level) inline static
Initialize the internal trace facility using the name of the log to be written to and the trace level.
Parameters
logName The log name
level The trace level
Referenced by NUnit.Framework.Api.FrameworkController.Initialize(), and NUnitLite.AutoRun.InitializeInternalTrace().
Initialize() [2/2]
static void NUnit.Common.InternalTrace.Initialize (TextWriter writer, InternalTraceLevel level) inline static
Initialize the internal trace using a provided TextWriter and level
Parameters
writer A TextWriter
level The InternalTraceLevel
References NUnit.Common.InternalTraceWriter.WriteLine().
GetLogger() [1/2]
static Logger NUnit.Common.InternalTrace.GetLogger (string name) inline static
Get a named Logger
Returns
GetLogger() [2/2]
static Logger NUnit.Common.InternalTrace.GetLogger (Type type) inline static
Get a logger named for a particular Type.
Member Data Documentation
traceLevel
InternalTraceLevel NUnit.Common.InternalTrace.traceLevel static private
traceWriter
InternalTraceWriter NUnit.Common.InternalTrace.traceWriter static private
Property Documentation
Initialized
bool NUnit.Common.InternalTrace.Initialized static get private set
Gets a flag indicating whether the InternalTrace is initialized
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/nunit/Logging/InternalTrace.cs