Doc: IGLib EXTENDED: alglib.testortfacunit Class Reference
alglib.testortfacunit Class Reference
Static Public Member Functions
static bool testortfac (bool silent)
static bool testortfac (bool silent)
static bool _pexec_testortfac (bool silent)
Static Private Member Functions
static double rmatrixdiff (double[,] a, double[,] b, int m, int n)
static void rmatrixmakeacopy (double[,] a, int m, int n, ref double[,] b)
static void cmatrixmakeacopy (complex[,] a, int m, int n, ref complex[,] b)
static void rmatrixfillsparsea (ref double[,] a, int m, int n, double sparcity)
static void cmatrixfillsparsea (ref complex[,] a, int m, int n, double sparcity)
static void internalmatrixmatrixmultiply (double[,] a, int ai1, int ai2, int aj1, int aj2, bool transa, double[,] b, int bi1, int bi2, int bj1, int bj2, bool transb, ref double[,] c, int ci1, int ci2, int cj1, int cj2)
static void testrqrproblem (double[,] a, int m, int n, double threshold, ref bool qrerrors)
static void testcqrproblem (complex[,] a, int m, int n, double threshold, ref bool qrerrors)
static void testrlqproblem (double[,] a, int m, int n, double threshold, ref bool lqerrors)
static void testclqproblem (complex[,] a, int m, int n, double threshold, ref bool lqerrors)
static void testrbdproblem (double[,] a, int m, int n, double threshold, ref bool bderrors)
static void testrhessproblem (double[,] a, int n, double threshold, ref bool hesserrors)
static void testrtdproblem (double[,] a, int n, double threshold, ref bool tderrors)
static void testctdproblem (complex[,] a, int n, double threshold, ref bool tderrors)
static double rmatrixdiff (double[,] a, double[,] b, int m, int n)
static void rmatrixmakeacopy (double[,] a, int m, int n, ref double[,] b)
static void cmatrixmakeacopy (complex[,] a, int m, int n, ref complex[,] b)
static void rmatrixfillsparsea (ref double[,] a, int m, int n, double sparcity)
static void cmatrixfillsparsea (ref complex[,] a, int m, int n, double sparcity)
static void internalmatrixmatrixmultiply (double[,] a, int ai1, int ai2, int aj1, int aj2, bool transa, double[,] b, int bi1, int bi2, int bj1, int bj2, bool transb, ref double[,] c, int ci1, int ci2, int cj1, int cj2)
static void testrqrproblem (double[,] a, int m, int n, double threshold, ref bool qrerrors)
static void testcqrproblem (complex[,] a, int m, int n, double threshold, ref bool qrerrors)
static void testrlqproblem (double[,] a, int m, int n, double threshold, ref bool lqerrors)
static void testclqproblem (complex[,] a, int m, int n, double threshold, ref bool lqerrors)
static void testrbdproblem (double[,] a, int m, int n, double threshold, ref bool bderrors)
static void testrhessproblem (double[,] a, int n, double threshold, ref bool hesserrors)
static void testrtdproblem (double[,] a, int n, double threshold, ref bool tderrors)
static void testctdproblem (complex[,] a, int n, double threshold, ref bool tderrors)
Member Function Documentation
testortfac() [1/2]
static bool alglib.testortfacunit.testortfac (bool silent) inline static
References alglib.ablas.ablasblocksize(), alglib.testortfacunit.cmatrixfillsparsea(), alglib.math.conj(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testortfacunit.rmatrixfillsparsea(), alglib.testortfacunit.testclqproblem(), alglib.testortfacunit.testcqrproblem(), alglib.testortfacunit.testctdproblem(), alglib.testortfacunit.testrbdproblem(), alglib.testortfacunit.testrhessproblem(), alglib.testortfacunit.testrlqproblem(), alglib.testortfacunit.testrqrproblem(), alglib.testortfacunit.testrtdproblem(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.testortfacunit._pexec_testortfac(), and _Test.Main().
rmatrixdiff() [1/2]
static double alglib.testortfacunit.rmatrixdiff (double a[,], double b[,], int m, int n) inline static private
Referenced by alglib.testortfacunit.testrbdproblem(), and alglib.testortfacunit.testrhessproblem().
rmatrixmakeacopy() [1/2]
static void alglib.testortfacunit.rmatrixmakeacopy (double a[,], int m, int n, ref double b[,]) inline static private
Referenced by alglib.testortfacunit.testrbdproblem(), alglib.testortfacunit.testrhessproblem(), alglib.testortfacunit.testrlqproblem(), and alglib.testortfacunit.testrqrproblem().
cmatrixmakeacopy() [1/2]
static void alglib.testortfacunit.cmatrixmakeacopy (complex a[,], int m, int n, ref complex b[,]) inline static private
Referenced by alglib.testortfacunit.testclqproblem(), and alglib.testortfacunit.testcqrproblem().
rmatrixfillsparsea() [1/2]
static void alglib.testortfacunit.rmatrixfillsparsea (ref double a[,], int m, int n, double sparcity) inline static private
References alglib.math.randomreal().
Referenced by alglib.testortfacunit.testortfac().
cmatrixfillsparsea() [1/2]
static void alglib.testortfacunit.cmatrixfillsparsea (ref complex a[,], int m, int n, double sparcity) inline static private
References alglib.math.randomreal().
Referenced by alglib.testortfacunit.testortfac().
internalmatrixmatrixmultiply() [1/2]
static void alglib.testortfacunit.internalmatrixmatrixmultiply (double a[,], int ai1, int ai2, int aj1, int aj2, bool transa, double b[,], int bi1, int bi2, int bj1, int bj2, bool transb, ref double c[,], int ci1, int ci2, int cj1, int cj2) inline static private
References alglib.ap.assert(), and alglib.beta().
Referenced by alglib.testortfacunit.testrbdproblem(), and alglib.testortfacunit.testrhessproblem().
testrqrproblem() [1/2]
static void alglib.testortfacunit.testrqrproblem (double a[,], int m, int n, double threshold, ref bool qrerrors) inline static private
References alglib.math.machineepsilon, alglib.math.randominteger(), alglib.testortfacunit.rmatrixmakeacopy(), alglib.ortfac.rmatrixqr(), alglib.ortfac.rmatrixqrunpackq(), and alglib.ortfac.rmatrixqrunpackr().
Referenced by alglib.testortfacunit.testortfac().
testcqrproblem() [1/2]
static void alglib.testortfacunit.testcqrproblem (complex a[,], int m, int n, double threshold, ref bool qrerrors) inline static private
References alglib.math.abscomplex(), alglib.testortfacunit.cmatrixmakeacopy(), alglib.ortfac.cmatrixqr(), alglib.ortfac.cmatrixqrunpackq(), alglib.ortfac.cmatrixqrunpackr(), alglib.math.conj(), alglib.math.machineepsilon, and alglib.math.randominteger().
Referenced by alglib.testortfacunit.testortfac().
testrlqproblem() [1/2]
static void alglib.testortfacunit.testrlqproblem (double a[,], int m, int n, double threshold, ref bool lqerrors) inline static private
References alglib.math.machineepsilon, alglib.math.randominteger(), alglib.ortfac.rmatrixlq(), alglib.ortfac.rmatrixlqunpackl(), alglib.ortfac.rmatrixlqunpackq(), and alglib.testortfacunit.rmatrixmakeacopy().
Referenced by alglib.testortfacunit.testortfac().
testclqproblem() [1/2]
static void alglib.testortfacunit.testclqproblem (complex a[,], int m, int n, double threshold, ref bool lqerrors) inline static private
References alglib.math.abscomplex(), alglib.ortfac.cmatrixlq(), alglib.ortfac.cmatrixlqunpackl(), alglib.ortfac.cmatrixlqunpackq(), alglib.testortfacunit.cmatrixmakeacopy(), alglib.math.conj(), alglib.math.machineepsilon, and alglib.math.randominteger().
Referenced by alglib.testortfacunit.testortfac().
testrbdproblem() [1/2]
static void alglib.testortfacunit.testrbdproblem (double a[,], int m, int n, double threshold, ref bool bderrors) inline static private
References alglib.testortfacunit.internalmatrixmatrixmultiply(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.ortfac.rmatrixbd(), alglib.ortfac.rmatrixbdmultiplybyp(), alglib.ortfac.rmatrixbdmultiplybyq(), alglib.ortfac.rmatrixbdunpackdiagonals(), alglib.ortfac.rmatrixbdunpackpt(), alglib.ortfac.rmatrixbdunpackq(), alglib.testortfacunit.rmatrixdiff(), and alglib.testortfacunit.rmatrixmakeacopy().
Referenced by alglib.testortfacunit.testortfac().
testrhessproblem() [1/2]
static void alglib.testortfacunit.testrhessproblem (double a[,], int n, double threshold, ref bool hesserrors) inline static private
References alglib.testortfacunit.internalmatrixmatrixmultiply(), alglib.testortfacunit.rmatrixdiff(), alglib.ortfac.rmatrixhessenberg(), alglib.ortfac.rmatrixhessenbergunpackh(), alglib.ortfac.rmatrixhessenbergunpackq(), and alglib.testortfacunit.rmatrixmakeacopy().
Referenced by alglib.testortfacunit.testortfac().
testrtdproblem() [1/2]
static void alglib.testortfacunit.testrtdproblem (double a[,], int n, double threshold, ref bool tderrors) inline static private
References alglib.ortfac.smatrixtd(), and alglib.ortfac.smatrixtdunpackq().
Referenced by alglib.testortfacunit.testortfac().
testctdproblem() [1/2]
static void alglib.testortfacunit.testctdproblem (complex a[,], int n, double threshold, ref bool tderrors) inline static private
References alglib.math.abscomplex(), alglib.math.conj(), alglib.ortfac.hmatrixtd(), and alglib.ortfac.hmatrixtdunpackq().
Referenced by alglib.testortfacunit.testortfac().
testortfac() [2/2]
static bool alglib.testortfacunit.testortfac (bool silent) inline static
References alglib.ablas.ablasblocksize(), alglib.testortfacunit.cmatrixfillsparsea(), alglib.math.conj(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testortfacunit.rmatrixfillsparsea(), alglib.testortfacunit.testclqproblem(), alglib.testortfacunit.testcqrproblem(), alglib.testortfacunit.testctdproblem(), alglib.testortfacunit.testrbdproblem(), alglib.testortfacunit.testrhessproblem(), alglib.testortfacunit.testrlqproblem(), alglib.testortfacunit.testrqrproblem(), alglib.testortfacunit.testrtdproblem(), alglib.complex.x, and alglib.complex.y.
_pexec_testortfac()
static bool alglib.testortfacunit._pexec_testortfac (bool silent) inline static
References alglib.testortfacunit.testortfac().
Referenced by _Test.Main().
rmatrixdiff() [2/2]
static double alglib.testortfacunit.rmatrixdiff (double a[,], double b[,], int m, int n) inline static private
rmatrixmakeacopy() [2/2]
static void alglib.testortfacunit.rmatrixmakeacopy (double a[,], int m, int n, ref double b[,]) inline static private
cmatrixmakeacopy() [2/2]
static void alglib.testortfacunit.cmatrixmakeacopy (complex a[,], int m, int n, ref complex b[,]) inline static private
rmatrixfillsparsea() [2/2]
static void alglib.testortfacunit.rmatrixfillsparsea (ref double a[,], int m, int n, double sparcity) inline static private
References alglib.math.randomreal().
cmatrixfillsparsea() [2/2]
static void alglib.testortfacunit.cmatrixfillsparsea (ref complex a[,], int m, int n, double sparcity) inline static private
References alglib.math.randomreal().
internalmatrixmatrixmultiply() [2/2]
static void alglib.testortfacunit.internalmatrixmatrixmultiply (double a[,], int ai1, int ai2, int aj1, int aj2, bool transa, double b[,], int bi1, int bi2, int bj1, int bj2, bool transb, ref double c[,], int ci1, int ci2, int cj1, int cj2) inline static private
References alglib.ap.assert(), and alglib.beta().
testrqrproblem() [2/2]
static void alglib.testortfacunit.testrqrproblem (double a[,], int m, int n, double threshold, ref bool qrerrors) inline static private
References alglib.math.machineepsilon, alglib.math.randominteger(), alglib.testortfacunit.rmatrixmakeacopy(), alglib.ortfac.rmatrixqr(), alglib.ortfac.rmatrixqrunpackq(), and alglib.ortfac.rmatrixqrunpackr().
testcqrproblem() [2/2]
static void alglib.testortfacunit.testcqrproblem (complex a[,], int m, int n, double threshold, ref bool qrerrors) inline static private
References alglib.math.abscomplex(), alglib.testortfacunit.cmatrixmakeacopy(), alglib.ortfac.cmatrixqr(), alglib.ortfac.cmatrixqrunpackq(), alglib.ortfac.cmatrixqrunpackr(), alglib.math.conj(), alglib.math.machineepsilon, and alglib.math.randominteger().
testrlqproblem() [2/2]
static void alglib.testortfacunit.testrlqproblem (double a[,], int m, int n, double threshold, ref bool lqerrors) inline static private
References alglib.math.machineepsilon, alglib.math.randominteger(), alglib.ortfac.rmatrixlq(), alglib.ortfac.rmatrixlqunpackl(), alglib.ortfac.rmatrixlqunpackq(), and alglib.testortfacunit.rmatrixmakeacopy().
testclqproblem() [2/2]
static void alglib.testortfacunit.testclqproblem (complex a[,], int m, int n, double threshold, ref bool lqerrors) inline static private
References alglib.math.abscomplex(), alglib.ortfac.cmatrixlq(), alglib.ortfac.cmatrixlqunpackl(), alglib.ortfac.cmatrixlqunpackq(), alglib.testortfacunit.cmatrixmakeacopy(), alglib.math.conj(), alglib.math.machineepsilon, and alglib.math.randominteger().
testrbdproblem() [2/2]
static void alglib.testortfacunit.testrbdproblem (double a[,], int m, int n, double threshold, ref bool bderrors) inline static private
References alglib.testortfacunit.internalmatrixmatrixmultiply(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.ortfac.rmatrixbd(), alglib.ortfac.rmatrixbdmultiplybyp(), alglib.ortfac.rmatrixbdmultiplybyq(), alglib.ortfac.rmatrixbdunpackdiagonals(), alglib.ortfac.rmatrixbdunpackpt(), alglib.ortfac.rmatrixbdunpackq(), alglib.testortfacunit.rmatrixdiff(), and alglib.testortfacunit.rmatrixmakeacopy().
testrhessproblem() [2/2]
static void alglib.testortfacunit.testrhessproblem (double a[,], int n, double threshold, ref bool hesserrors) inline static private
References alglib.testortfacunit.internalmatrixmatrixmultiply(), alglib.testortfacunit.rmatrixdiff(), alglib.ortfac.rmatrixhessenberg(), alglib.ortfac.rmatrixhessenbergunpackh(), alglib.ortfac.rmatrixhessenbergunpackq(), and alglib.testortfacunit.rmatrixmakeacopy().
testrtdproblem() [2/2]
static void alglib.testortfacunit.testrtdproblem (double a[,], int n, double threshold, ref bool tderrors) inline static private
References alglib.ortfac.smatrixtd(), and alglib.ortfac.smatrixtdunpackq().
testctdproblem() [2/2]
static void alglib.testortfacunit.testctdproblem (complex a[,], int n, double threshold, ref bool tderrors) inline static private
References alglib.math.abscomplex(), alglib.math.conj(), alglib.ortfac.hmatrixtd(), and alglib.ortfac.hmatrixtdunpackq().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs