Doc: IGLib EXTENDED: NUnit.Framework.Internal.RuntimeFrameworkTests Class Reference
NUnit.Framework.Internal.RuntimeFrameworkTests Class Reference
Classes
struct FrameworkData
Public Member Functions
void CanGetCurrentFramework ()
void CurrentFrameworkHasBuildSpecified ()
void CanCreateUsingFrameworkVersion (FrameworkData data)
void CanCreateUsingClrVersion (FrameworkData data)
void CanParseRuntimeFramework (FrameworkData data)
void CanDisplayFrameworkAsString (FrameworkData data)
bool CanMatchRuntimes (RuntimeFramework f1, RuntimeFramework f2)
Static Private Attributes
static RuntimeType currentRuntime
Member Function Documentation
CanGetCurrentFramework()
void NUnit.Framework.Internal.RuntimeFrameworkTests.CanGetCurrentFramework () inline
References NUnit.Framework.Internal.RuntimeFramework.ClrVersion, NUnit.Framework.Internal.RuntimeFramework.CurrentFramework, NUnit.Framework.Internal.RuntimeFrameworkTests.currentRuntime, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.RuntimeFramework.FrameworkVersion, NUnit.Framework.Internal.RuntimeFramework.Runtime, and NUnit.Framework.Assert.That().
CurrentFrameworkHasBuildSpecified()
void NUnit.Framework.Internal.RuntimeFrameworkTests.CurrentFrameworkHasBuildSpecified () inline
References NUnit.Framework.Internal.RuntimeFramework.ClrVersion, NUnit.Framework.Internal.RuntimeFramework.CurrentFramework, NUnit.Framework.Is.GreaterThan(), and NUnit.Framework.Assert.That().
CanCreateUsingFrameworkVersion()
void NUnit.Framework.Internal.RuntimeFrameworkTests.CanCreateUsingFrameworkVersion (FrameworkData data) inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.RuntimeFrameworkTests.FrameworkData.clrVersion, NUnit.Framework.Internal.RuntimeFramework.ClrVersion, NUnit.Framework.Internal.RuntimeFrameworkTests.FrameworkData.frameworkVersion, NUnit.Framework.Internal.RuntimeFramework.FrameworkVersion, NUnit.Framework.Internal.RuntimeFrameworkTests.FrameworkData.runtime, and NUnit.Framework.Internal.RuntimeFramework.Runtime.
CanCreateUsingClrVersion()
void NUnit.Framework.Internal.RuntimeFrameworkTests.CanCreateUsingClrVersion (FrameworkData data) inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.RuntimeFrameworkTests.FrameworkData.clrVersion, NUnit.Framework.Internal.RuntimeFramework.ClrVersion, NUnit.Framework.Internal.RuntimeFrameworkTests.FrameworkData.frameworkVersion, NUnit.Framework.Internal.RuntimeFramework.FrameworkVersion, NUnit.Framework.Internal.RuntimeFrameworkTests.FrameworkData.runtime, NUnit.Framework.Internal.RuntimeFramework.Runtime, and NUnit.Framework.Assume.That().
CanParseRuntimeFramework()
void NUnit.Framework.Internal.RuntimeFrameworkTests.CanParseRuntimeFramework (FrameworkData data) inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.RuntimeFrameworkTests.FrameworkData.clrVersion, NUnit.Framework.Internal.RuntimeFramework.ClrVersion, NUnit.Framework.Internal.RuntimeFramework.Parse(), NUnit.Framework.Internal.RuntimeFrameworkTests.FrameworkData.representation, NUnit.Framework.Internal.RuntimeFrameworkTests.FrameworkData.runtime, and NUnit.Framework.Internal.RuntimeFramework.Runtime.
CanDisplayFrameworkAsString()
void NUnit.Framework.Internal.RuntimeFrameworkTests.CanDisplayFrameworkAsString (FrameworkData data) inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.RuntimeFrameworkTests.FrameworkData.displayName, NUnit.Framework.Internal.RuntimeFramework.DisplayName, NUnit.Framework.Internal.RuntimeFrameworkTests.FrameworkData.frameworkVersion, NUnit.Framework.Internal.RuntimeFrameworkTests.FrameworkData.representation, NUnit.Framework.Internal.RuntimeFrameworkTests.FrameworkData.runtime, and NUnit.Framework.Internal.RuntimeFramework.ToString().
CanMatchRuntimes()
bool NUnit.Framework.Internal.RuntimeFrameworkTests.CanMatchRuntimes (RuntimeFramework f1, RuntimeFramework f2) inline
References NUnit.Framework.Internal.RuntimeFramework.Supports().
Member Data Documentation
currentRuntime
RuntimeType NUnit.Framework.Internal.RuntimeFrameworkTests.currentRuntime static private
Initial value:
=
            Type.GetType("Mono.Runtime", false) != null
                ? RuntimeType.Mono
                : Environment.OSVersion.Platform == PlatformID.WinCE
                    ? RuntimeType.NetCF
                    : RuntimeType.Net
Referenced by NUnit.Framework.Internal.RuntimeFrameworkTests.CanGetCurrentFramework().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/RuntimeFrameworkTests.cs