Doc: IGLib EXTENDED: CShell.Modules.Sink.Views.GridSinkView Class Reference
CShell.Modules.Sink.Views.GridSinkView Class Reference
Interaction logic for DataView.xaml
Public Member Functions
GridSinkView ()
void AddColumn (PropertyInfo propertyInfo)
Private Member Functions
void Data_DataContextChanged (object sender, DependencyPropertyChangedEventArgs e)
Generates the colums for the data grid depending on the time series data.
void vm_PropertyChanged (object sender, System.ComponentModel.PropertyChangedEventArgs e)
void CheckComboBox_ItemSelectionChanged (object sender, ItemSelectionChangedEventArgs e)
void InitializeColumns ()
int GetColumnIndex (PropertyInfo propertyInfo)
void RemoveColumn (PropertyInfo propertyInfo)
Private Attributes
Style rightAlignStyle
GridSinkViewModel gridSink
Type itemType
Detailed Description
Interaction logic for DataView.xaml
Constructor & Destructor Documentation
GridSinkView()
CShell.Modules.Sink.Views.GridSinkView.GridSinkView () inline
References CShell.Modules.Sink.Views.GridSinkView.rightAlignStyle.
Member Function Documentation
Data_DataContextChanged()
void CShell.Modules.Sink.Views.GridSinkView.Data_DataContextChanged (object sender, DependencyPropertyChangedEventArgs e) inline private
Generates the colums for the data grid depending on the time series data.
Parameters
sender The source of the event.
e The System.Windows.DependencyPropertyChangedEventArgs instance containing the event data.
References CShell.Modules.Sink.ViewModels.GridSinkViewModel.Data, CShell.Modules.Sink.Views.GridSinkView.gridSink, CShell.Modules.Sink.Views.GridSinkView.InitializeColumns(), and CShell.Modules.Sink.Views.GridSinkView.vm_PropertyChanged().
vm_PropertyChanged()
void CShell.Modules.Sink.Views.GridSinkView.vm_PropertyChanged (object sender, System.ComponentModel.PropertyChangedEventArgs e) inline private
References CShell.Modules.Sink.Views.GridSinkView.gridSink, CShell.Modules.Sink.Views.GridSinkView.InitializeColumns(), CShell.Modules.Sink.Views.GridSinkView.itemType, and CShell.Modules.Sink.ViewModels.GridSinkViewModel.ItemType.
Referenced by CShell.Modules.Sink.Views.GridSinkView.Data_DataContextChanged().
CheckComboBox_ItemSelectionChanged()
void CShell.Modules.Sink.Views.GridSinkView.CheckComboBox_ItemSelectionChanged (object sender, ItemSelectionChangedEventArgs e) inline private
References CShell.Modules.Sink.Views.GridSinkView.AddColumn(), and CShell.Modules.Sink.Views.GridSinkView.RemoveColumn().
InitializeColumns()
void CShell.Modules.Sink.Views.GridSinkView.InitializeColumns () inline private
References CShell.Modules.Sink.Views.GridSinkView.AddColumn(), CShell.Modules.Sink.Views.GridSinkView.gridSink, CShell.Modules.Sink.Views.GridSinkView.itemType, CShell.Modules.Sink.ViewModels.GridSinkViewModel.ItemType, and CShell.Modules.Sink.ViewModels.GridSinkViewModel.SelectedProperties.
Referenced by CShell.Modules.Sink.Views.GridSinkView.Data_DataContextChanged(), and CShell.Modules.Sink.Views.GridSinkView.vm_PropertyChanged().
AddColumn()
void CShell.Modules.Sink.Views.GridSinkView.AddColumn (PropertyInfo propertyInfo) inline
References CShell.Modules.Sink.Views.GridSinkView.GetColumnIndex(), and CShell.Modules.Sink.Views.GridSinkView.rightAlignStyle.
Referenced by CShell.Modules.Sink.Views.GridSinkView.CheckComboBox_ItemSelectionChanged(), and CShell.Modules.Sink.Views.GridSinkView.InitializeColumns().
GetColumnIndex()
int CShell.Modules.Sink.Views.GridSinkView.GetColumnIndex (PropertyInfo propertyInfo) inline private
References CShell.Modules.Sink.Views.GridSinkView.gridSink, CShell.Modules.Sink.ViewModels.GridSinkViewModel.Properties, and CShell.Modules.Sink.ViewModels.GridSinkViewModel.SelectedProperties.
Referenced by CShell.Modules.Sink.Views.GridSinkView.AddColumn().
RemoveColumn()
void CShell.Modules.Sink.Views.GridSinkView.RemoveColumn (PropertyInfo propertyInfo) inline private
Referenced by CShell.Modules.Sink.Views.GridSinkView.CheckComboBox_ItemSelectionChanged().
Member Data Documentation
rightAlignStyle
Style CShell.Modules.Sink.Views.GridSinkView.rightAlignStyle private
Referenced by CShell.Modules.Sink.Views.GridSinkView.AddColumn(), and CShell.Modules.Sink.Views.GridSinkView.GridSinkView().
gridSink
GridSinkViewModel CShell.Modules.Sink.Views.GridSinkView.gridSink private
Referenced by CShell.Modules.Sink.Views.GridSinkView.Data_DataContextChanged(), CShell.Modules.Sink.Views.GridSinkView.GetColumnIndex(), CShell.Modules.Sink.Views.GridSinkView.InitializeColumns(), and CShell.Modules.Sink.Views.GridSinkView.vm_PropertyChanged().
itemType
Type CShell.Modules.Sink.Views.GridSinkView.itemType private
Referenced by CShell.Modules.Sink.Views.GridSinkView.InitializeColumns(), and CShell.Modules.Sink.Views.GridSinkView.vm_PropertyChanged().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Sink/Views/GridSinkView.xaml.cs