Doc: IGLib EXTENDED: NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests Class Reference
NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests Class Reference
Public Member Functions
void SucceedsWhenValueIsPresent ()
void FailsWhenValueIsMissing ()
void FailsWhenNotUsedAgainstADictionary ()
void WorksWithNonGenericDictionary ()
void IgnoreCaseIsHonored ()
void UsingIsHonored ()
Member Function Documentation
SucceedsWhenValueIsPresent()
void NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests.SucceedsWhenValueIsPresent () inline
References NUnit.Framework.Assert.That().
FailsWhenValueIsMissing()
void NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests.FailsWhenValueIsMissing () inline
References NUnit.Framework.Throws.Exception, NUnit.Framework.TestDelegate(), NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.ConstraintExpression.TypeOf().
FailsWhenNotUsedAgainstADictionary()
void NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests.FailsWhenNotUsedAgainstADictionary () inline
References NUnit.Framework.Throws.ArgumentException, NUnit.Framework.Constraints.ConstraintExpression.Contains(), NUnit.Framework.Constraints.ConstraintExpression.Message, NUnit.Framework.TestDelegate(), NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.Constraint.With.
WorksWithNonGenericDictionary()
void NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests.WorksWithNonGenericDictionary () inline
References NUnit.Framework.Assert.That().
IgnoreCaseIsHonored()
void NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests.IgnoreCaseIsHonored () inline
References NUnit.Framework.Assert.That().
UsingIsHonored()
void NUnit.Framework.Tests.Constraints.DictionaryContainsValueConstraintTests.UsingIsHonored () inline
References NUnit.Framework.Internal.StringUtil.Compare(), and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/DictionaryContainsValueConstraintTests.cs