Doc: IGLib EXTENDED: NUnit.Framework.Constraints.ToStringTests Class Reference
NUnit.Framework.Constraints.ToStringTests Class Reference
Public Member Functions
void CanDisplaySimpleConstraints_Unresolved ()
void CanDisplaySimpleConstraints_Resolved ()
void DisplayPrefixConstraints_Unresolved ()
void CanDisplayPrefixConstraints_Resolved ()
void DisplayBinaryConstraints_Resolved ()
void DisplayBinaryConstraints_UnResolved ()
Member Function Documentation
CanDisplaySimpleConstraints_Unresolved()
void NUnit.Framework.Constraints.ToStringTests.CanDisplaySimpleConstraints_Unresolved () inline
References NUnit.Framework.Has.Attribute(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Has.Property(), and NUnit.Framework.Assert.That().
CanDisplaySimpleConstraints_Resolved()
void NUnit.Framework.Constraints.ToStringTests.CanDisplaySimpleConstraints_Resolved () inline
References NUnit.Framework.Has.Attribute(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Has.Property(), NUnit.Framework.Constraints.IResolveConstraint.Resolve(), and NUnit.Framework.Assert.That().
DisplayPrefixConstraints_Unresolved()
void NUnit.Framework.Constraints.ToStringTests.DisplayPrefixConstraints_Unresolved () inline
References NUnit.Framework.Has.Attribute(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.Not, NUnit.Framework.Has.Property(), and NUnit.Framework.Assert.That().
CanDisplayPrefixConstraints_Resolved()
void NUnit.Framework.Constraints.ToStringTests.CanDisplayPrefixConstraints_Resolved () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.Not, NUnit.Framework.Has.Property(), NUnit.Framework.Constraints.IResolveConstraint.Resolve(), and NUnit.Framework.Assert.That().
DisplayBinaryConstraints_Resolved()
void NUnit.Framework.Constraints.ToStringTests.DisplayBinaryConstraints_Resolved () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.GreaterThan(), NUnit.Framework.Constraints.IResolveConstraint.Resolve(), and NUnit.Framework.Assert.That().
DisplayBinaryConstraints_UnResolved()
void NUnit.Framework.Constraints.ToStringTests.DisplayBinaryConstraints_UnResolved () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.GreaterThan(), and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/ToStringTests.cs