Doc: IGLib EXTENDED: Meta.Numerics.Statistics.Distributions.NormalDistribution Class Reference
Meta.Numerics.Statistics.Distributions.NormalDistribution Class Reference
Represents a normal (Gaussian) distribution.
Public Member Functions
NormalDistribution (double mu, double sigma)
Initializes a new normal distribution with the given mean and standard deviation.
NormalDistribution ()
Initializes a new standard normal distribution.
override double ProbabilityDensity (double x)
Returns the probability density at the given point.
override double LeftProbability (double x)
Returns the cumulative probability to the left of (below) the given point.
override double RightProbability (double x)
Return the cumulative probability to the right of (above) the given point.
override double Moment (int r)
Computes a raw moment of the distribution.
override double MomentAboutMean (int r)
Computes a central moment of the distribution.
override double Cumulant (int r)
Computes a cumulant of the distribution.
override double InverseLeftProbability (double P)
Returns the point at which the cumulative distribution function attains a given value.
override double InverseRightProbability (double Q)
Returns the point at which the right probability function attains the given value.
override double GetRandomValue (Random rng)
Returns a random value.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double ExpectationValue (Func< double, double > f)
Computes the expectation value of the given function.
Static Public Member Functions
static FitResult FitToSample (Sample sample)
Computes the normal distribution that best fits the given sample.
Properties
override double Mean [get]
override double StandardDeviation [get]
override double Skewness [get]
override double ExcessKurtosis [get]
override double Median [get]
Properties inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double Median [get]
Gets the median of the distribution.
virtual Interval Support [get]
Gets the interval over which the distribution is nonvanishing.
Properties inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Mean [get]
Gets the mean of the distribution.
virtual double Variance [get]
Gets the variance of the distribution.
virtual double StandardDeviation [get]
Gets the standard deviation of the distribution.
virtual double Skewness [get]
Gets the skewness of the distribution.
virtual double ExcessKurtosis [get]
Gets the excess kurtosis of the distribution.
Private Member Functions
double[] IParameterizedDistribution. GetParameters ()
Gets the parameter values of the distribution.
void IParameterizedDistribution. SetParameters (IList< double > parameters)
Sets the parameter values of the distribution.
double IParameterizedDistribution. Likelihood (double x)
Gets the likelihood of a value, given the current parameters.
Private Attributes
double mu
double sigma
readonly IDeviateGenerator normalRng
Detailed Description
Represents a normal (Gaussian) distribution.
A normal distribution is a bell-shaped curve centered at its mean and falling off symmetrically on each side. It is a two-parameter distribution determined by giving its mean and standard deviation, i.e. its center and width. Its range is the entire real number line, but the tails, i.e. points more than a few standard deviations from the means, fall off extremely rapidly.
A normal distribution with mean zero and standard deviation one is called a standard normal distribution. Any normal distribution can be converted to a standard normal distribution by reparameterzing the data in terms of "standard deviations from the mean", i.e. z = (x - &#x3BC;) / &#x3C3;.
Normal distribution appear in many contexts. In practical work, the normal distribution is often used as a crude model for the distribution of any continuous parameter that tends to cluster near its average, for example human height and weight. In more refined theoretical work, the normal distribution often emerges as a limiting distribution. For example, it can be shown that, if a large number of errors affect a measurement, then for nearly any underlying distribution of error terms, the distribution of total error tends to a normal distribution.
The normal distribution is sometimes called a Gaussian distribtuion, after the mathematician Friedrich Gauss.
Constructor & Destructor Documentation
NormalDistribution() [1/2]
Meta.Numerics.Statistics.Distributions.NormalDistribution.NormalDistribution (double mu, double sigma) inline
Initializes a new normal distribution with the given mean and standard deviation.
Parameters
mu The mean.
sigma The standard deviation, which must be positive.
Exceptions
ArgumentOutOfRangeException sigma is less than or equal to zero.
References Meta.Numerics.Statistics.Distributions.NormalDistribution.mu, and Meta.Numerics.Statistics.Distributions.NormalDistribution.sigma.
NormalDistribution() [2/2]
Meta.Numerics.Statistics.Distributions.NormalDistribution.NormalDistribution () inline
Initializes a new standard normal distribution.
The standard normal distribution has mean zero and standard deviation one.
Referenced by Meta.Numerics.Statistics.Distributions.NormalDistribution.FitToSample().
Member Function Documentation
ProbabilityDensity()
override double Meta.Numerics.Statistics.Distributions.NormalDistribution.ProbabilityDensity (double x) inline virtual
Returns the probability density at the given point.
Implements Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.NormalDistribution.mu, and Meta.Numerics.Statistics.Distributions.NormalDistribution.sigma.
Referenced by Meta.Numerics.Statistics.Distributions.NormalDistribution.Likelihood().
LeftProbability()
override double Meta.Numerics.Statistics.Distributions.NormalDistribution.LeftProbability (double x) inline virtual
Returns the cumulative probability to the left of (below) the given point.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.NormalDistribution.mu, and Meta.Numerics.Statistics.Distributions.NormalDistribution.sigma.
Referenced by Meta.Numerics.Statistics.Distributions.LognormalDistribution.LeftProbability().
RightProbability()
override double Meta.Numerics.Statistics.Distributions.NormalDistribution.RightProbability (double x) inline virtual
Return the cumulative probability to the right of (above) the given point.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.NormalDistribution.mu, and Meta.Numerics.Statistics.Distributions.NormalDistribution.sigma.
Referenced by Meta.Numerics.Statistics.Distributions.LognormalDistribution.RightProbability().
Moment()
override double Meta.Numerics.Statistics.Distributions.NormalDistribution.Moment (int r) inline virtual
Computes a raw moment of the distribution.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.MomentMath.CentralToRaw(), and Meta.Numerics.Statistics.Distributions.NormalDistribution.Mean.
MomentAboutMean()
override double Meta.Numerics.Statistics.Distributions.NormalDistribution.MomentAboutMean (int r) inline virtual
Computes a central moment of the distribution.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Functions.AdvancedIntegerMath.DoubleFactorial(), Meta.Numerics.MoreMath.Pow(), and Meta.Numerics.Statistics.Distributions.NormalDistribution.sigma.
Cumulant()
override double Meta.Numerics.Statistics.Distributions.NormalDistribution.Cumulant (int r) inline virtual
Computes a cumulant of the distribution.
Reimplemented from Meta.Numerics.Statistics.Distributions.UnivariateDistribution.
References Meta.Numerics.Statistics.Distributions.NormalDistribution.mu, and Meta.Numerics.Statistics.Distributions.NormalDistribution.sigma.
InverseLeftProbability()
override double Meta.Numerics.Statistics.Distributions.NormalDistribution.InverseLeftProbability (double P) inline virtual
Returns the point at which the cumulative distribution function attains a given value.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.NormalDistribution.mu, and Meta.Numerics.Statistics.Distributions.NormalDistribution.sigma.
Referenced by Test.DataSetTest.CreateDataSet(), and Meta.Numerics.Statistics.Distributions.LognormalDistribution.InverseLeftProbability().
InverseRightProbability()
override double Meta.Numerics.Statistics.Distributions.NormalDistribution.InverseRightProbability (double Q) inline virtual
Returns the point at which the right probability function attains the given value.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.NormalDistribution.mu, and Meta.Numerics.Statistics.Distributions.NormalDistribution.sigma.
Referenced by Meta.Numerics.Statistics.Distributions.LognormalDistribution.InverseRightProbability().
GetRandomValue()
override double Meta.Numerics.Statistics.Distributions.NormalDistribution.GetRandomValue (Random rng) inline virtual
Returns a random value.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.NormalDistribution.mu, Meta.Numerics.Statistics.Distributions.NormalDistribution.normalRng, and Meta.Numerics.Statistics.Distributions.NormalDistribution.sigma.
Referenced by Test.BivariateSampleTest.BivariateLinearRegressionGoodnessOfFitDistribution(), and Meta.Numerics.Statistics.Distributions.LognormalDistribution.GetRandomValue().
GetParameters()
double [] IParameterizedDistribution. Meta.Numerics.Statistics.Distributions.NormalDistribution.GetParameters () inline private
Gets the parameter values of the distribution.
Returns
The parameter values characterizing the distribution.
Implements Meta.Numerics.Statistics.Distributions.IParameterizedDistribution.
References Meta.Numerics.Statistics.Distributions.NormalDistribution.mu, and Meta.Numerics.Statistics.Distributions.NormalDistribution.sigma.
SetParameters()
void IParameterizedDistribution. Meta.Numerics.Statistics.Distributions.NormalDistribution.SetParameters (IList< double > parameters) inline private
Sets the parameter values of the distribution.
Parameters
parameters A list of parameter values.
Implements Meta.Numerics.Statistics.Distributions.IParameterizedDistribution.
References Meta.Numerics.Statistics.Distributions.NormalDistribution.mu, and Meta.Numerics.Statistics.Distributions.NormalDistribution.sigma.
Likelihood()
double IParameterizedDistribution. Meta.Numerics.Statistics.Distributions.NormalDistribution.Likelihood (double x) inline private
Gets the likelihood of a value, given the current parameters.
Parameters
x The value.
Returns
The likelihood of the value.
Implements Meta.Numerics.Statistics.Distributions.IParameterizedDistribution.
References Meta.Numerics.Statistics.Distributions.NormalDistribution.ProbabilityDensity().
FitToSample()
static FitResult Meta.Numerics.Statistics.Distributions.NormalDistribution.FitToSample (Sample sample) inline static
Computes the normal distribution that best fits the given sample.
Parameters
sample The sample to fit.
Returns
The best fit parameters.
The returned fit parameters are the &#x3BC; (Mean) and &#x3C3; (StandardDeviation) parameters, in that order. These are the same parameters, in the same order, that are required by the NormalDistribution(double,double) constructor to specify a new normal distribution.
Exceptions
ArgumentNullException sample is null.
InsufficientDataException sample contains fewer than three values.
References Meta.Numerics.Statistics.Sample.Count, Meta.Numerics.Statistics.Sample.KolmogorovSmirnovTest(), Meta.Numerics.Statistics.Distributions.NormalDistribution.mu, Meta.Numerics.Statistics.Distributions.NormalDistribution.NormalDistribution(), Meta.Numerics.Statistics.Sample.PopulationMean, Meta.Numerics.Statistics.Sample.PopulationStandardDeviation, and Meta.Numerics.Statistics.Distributions.NormalDistribution.sigma.
Referenced by Test.SampleTest.BetaFit(), Test.SampleTest.ExponentialFit(), Test.SampleTest.LognormalFit(), Test.SampleTest.NormalFit(), Test.SampleTest.NormalFitUncertainties(), and Test.SampleTest.SampleFitChiSquaredTest().
Member Data Documentation
mu
double Meta.Numerics.Statistics.Distributions.NormalDistribution.mu private
Referenced by Meta.Numerics.Statistics.Distributions.NormalDistribution.Cumulant(), Meta.Numerics.Statistics.Distributions.NormalDistribution.FitToSample(), Meta.Numerics.Statistics.Distributions.NormalDistribution.GetParameters(), Meta.Numerics.Statistics.Distributions.NormalDistribution.GetRandomValue(), Meta.Numerics.Statistics.Distributions.NormalDistribution.InverseLeftProbability(), Meta.Numerics.Statistics.Distributions.NormalDistribution.InverseRightProbability(), Meta.Numerics.Statistics.Distributions.NormalDistribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.NormalDistribution.NormalDistribution(), Meta.Numerics.Statistics.Distributions.NormalDistribution.ProbabilityDensity(), Meta.Numerics.Statistics.Distributions.NormalDistribution.RightProbability(), and Meta.Numerics.Statistics.Distributions.NormalDistribution.SetParameters().
sigma
double Meta.Numerics.Statistics.Distributions.NormalDistribution.sigma private
Referenced by Meta.Numerics.Statistics.Distributions.NormalDistribution.Cumulant(), Meta.Numerics.Statistics.Distributions.NormalDistribution.FitToSample(), Meta.Numerics.Statistics.Distributions.NormalDistribution.GetParameters(), Meta.Numerics.Statistics.Distributions.NormalDistribution.GetRandomValue(), Meta.Numerics.Statistics.Distributions.NormalDistribution.InverseLeftProbability(), Meta.Numerics.Statistics.Distributions.NormalDistribution.InverseRightProbability(), Meta.Numerics.Statistics.Distributions.NormalDistribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.NormalDistribution.MomentAboutMean(), Meta.Numerics.Statistics.Distributions.NormalDistribution.NormalDistribution(), Meta.Numerics.Statistics.Distributions.NormalDistribution.ProbabilityDensity(), Meta.Numerics.Statistics.Distributions.NormalDistribution.RightProbability(), and Meta.Numerics.Statistics.Distributions.NormalDistribution.SetParameters().
normalRng
readonly IDeviateGenerator Meta.Numerics.Statistics.Distributions.NormalDistribution.normalRng private
Referenced by Meta.Numerics.Statistics.Distributions.NormalDistribution.GetRandomValue().
Property Documentation
Mean
override double Meta.Numerics.Statistics.Distributions.NormalDistribution.Mean get
Referenced by Meta.Numerics.Statistics.Distributions.NormalDistribution.Moment().
StandardDeviation
override double Meta.Numerics.Statistics.Distributions.NormalDistribution.StandardDeviation get
Skewness
override double Meta.Numerics.Statistics.Distributions.NormalDistribution.Skewness get
ExcessKurtosis
override double Meta.Numerics.Statistics.Distributions.NormalDistribution.ExcessKurtosis get
Median
override double Meta.Numerics.Statistics.Distributions.NormalDistribution.Median get
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/Distributions/NormalDistribution.cs