Doc: IGLib EXTENDED: NUnit.Core.Tests.Generic.SimpleGenericMethods Class Reference
NUnit.Core.Tests.Generic.SimpleGenericMethods Class Reference
Public Member Functions
void GenericTestMethodWithOneTypeParameter< T > (T x, T y, string label)
void GenericTestMethodWithTwoTypeParameters< T1, T2 > (T1 x, T2 y, string label)
void GenericTestMethodWithTwoTypeParameters_Reversed< T1, T2 > (T2 x, T1 y, string label)
Member Function Documentation
GenericTestMethodWithOneTypeParameter< T >()
void NUnit.Core.Tests.Generic.SimpleGenericMethods.GenericTestMethodWithOneTypeParameter< T > (T x, T y, string label) inline
References NUnit.Framework.Assert.AreEqual().
GenericTestMethodWithTwoTypeParameters< T1, T2 >()
void NUnit.Core.Tests.Generic.SimpleGenericMethods.GenericTestMethodWithTwoTypeParameters< T1, T2 > (T1 x, T2 y, string label) inline
References NUnit.Framework.Assert.AreEqual().
GenericTestMethodWithTwoTypeParameters_Reversed< T1, T2 >()
void NUnit.Core.Tests.Generic.SimpleGenericMethods.GenericTestMethodWithTwoTypeParameters_Reversed< T1, T2 > (T2 x, T1 y, string label) inline
References NUnit.Framework.Assert.AreEqual().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/Addins/nunit.v2.driver.tests/SimpleGenericMethods.cs