Doc: IGLib EXTENDED: NUnit.Framework.Constraints.DelayedConstraintTests Class Reference
NUnit.Framework.Constraints.DelayedConstraintTests Class Reference
Public Member Functions
void SetUp ()
void SucceedsWithGoodDelegates (ActualValueDelegate< object > del)
void FailsWithBadDelegates (ActualValueDelegate< object > del)
void SimpleTest ()
void SimpleTestUsingBoolean ()
void ThatOverload_ZeroDelayIsAllowed ()
void ThatOverload_DoesNotAcceptNegativeDelayValues ()
void CanTestContentsOfList ()
void CanTestContentsOfDelegateReturningList ()
void CanTestInitiallyNullDelegate ()
void ThatBlockingDelegateWhichSucceedsWithoutPolling_ReturnsAfterDelay ()
void ThatBlockingDelegateWhichSucceedsWithPolling_ReturnsEarly ()
void ThatBlockingDelegateWhichFailsWithoutPolling_FailsAfterDelay ()
void ThatBlockingDelegateWhichFailsWithPolling_FailsAfterDelay ()
void ThatBlockingDelegateWhichThrowsWithoutPolling_FailsAfterDelay ()
void ThatBlockingDelegateWhichThrowsWithPolling_FailsAfterDelay ()
Public Member Functions inherited from NUnit.Framework.Constraints.ConstraintTestBase
void SucceedsWithGoodValues (object value)
void FailsWithBadValues (object badValue, string message)
Public Member Functions inherited from NUnit.Framework.Constraints.ConstraintTestBaseNoData
void ProvidesProperDescription ()
void ProvidesProperStringRepresentation ()
Private Member Functions
void SetValuesAfterDelay (int delay)
Static Private Member Functions
static DelayedConstraintTests ()
static void MethodReturningVoid ()
static object MethodReturningValue ()
static object MethodReturningFalse ()
static object MethodReturningZero ()
static void Delay (int delay)
static void MethodSetsValues ()
Static Private Attributes
const int DELAY = 100
const int AFTER = 300
const int POLLING = 50
const int MIN = AFTER - 10
static bool boolValue
static List< int > list
static string statusString
static object[] SuccessData = new object[] { true }
static object[] FailureData
static ActualValueDelegate DelegateReturningValue
static ActualValueDelegate DelegateReturningFalse
static ActualValueDelegate DelegateReturningZero
static ActualValueDelegate< object >[] SuccessDelegates
static ActualValueDelegate< object >[] FailureDelegates
static int setValuesDelay
static AutoResetEvent waitEvent = new AutoResetEvent(false)
Additional Inherited Members
Protected Attributes inherited from NUnit.Framework.Constraints.ConstraintTestBaseNoData
Constraint theConstraint
string expectedDescription = "<NOT SET>"
string stringRepresentation = "<NOT SET>"
Constructor & Destructor Documentation
DelayedConstraintTests()
static NUnit.Framework.Constraints.DelayedConstraintTests.DelayedConstraintTests () inline static private
References NUnit.Framework.Constraints.DelayedConstraintTests.DelegateReturningFalse, NUnit.Framework.Constraints.DelayedConstraintTests.DelegateReturningValue, NUnit.Framework.Constraints.DelayedConstraintTests.DelegateReturningZero, NUnit.Framework.Constraints.DelayedConstraintTests.FailureDelegates, NUnit.Framework.Constraints.DelayedConstraintTests.MethodReturningFalse(), NUnit.Framework.Constraints.DelayedConstraintTests.MethodReturningValue(), NUnit.Framework.Constraints.DelayedConstraintTests.MethodReturningZero(), and NUnit.Framework.Constraints.DelayedConstraintTests.SuccessDelegates.
Member Function Documentation
SetUp()
void NUnit.Framework.Constraints.DelayedConstraintTests.SetUp () inline
References NUnit.Framework.Constraints.DelayedConstraintTests.boolValue, NUnit.Framework.Constraints.ConstraintTestBaseNoData.expectedDescription, NUnit.Framework.Constraints.DelayedConstraintTests.list, NUnit.Framework.Constraints.DelayedConstraintTests.statusString, NUnit.Framework.Constraints.ConstraintTestBaseNoData.stringRepresentation, and NUnit.Framework.Constraints.ConstraintTestBaseNoData.theConstraint.
SucceedsWithGoodDelegates()
void NUnit.Framework.Constraints.DelayedConstraintTests.SucceedsWithGoodDelegates (ActualValueDelegate< object > del) inline
References NUnit.Framework.Constraints.DelayedConstraintTests.DELAY, NUnit.Framework.Constraints.DelayedConstraintTests.SetValuesAfterDelay(), NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.ConstraintTestBaseNoData.theConstraint.
FailsWithBadDelegates()
void NUnit.Framework.Constraints.DelayedConstraintTests.FailsWithBadDelegates (ActualValueDelegate< object > del) inline
References NUnit.Framework.Assert.IsFalse(), and NUnit.Framework.Constraints.ConstraintTestBaseNoData.theConstraint.
SimpleTest()
void NUnit.Framework.Constraints.DelayedConstraintTests.SimpleTest () inline
References NUnit.Framework.Constraints.DelayedConstraintTests.AFTER, NUnit.Framework.Constraints.DelayedConstraintTests.DELAY, NUnit.Framework.Constraints.DelayedConstraintTests.DelegateReturningValue, NUnit.Framework.Constraints.DelayedConstraintTests.POLLING, NUnit.Framework.Constraints.DelayedConstraintTests.SetValuesAfterDelay(), and NUnit.Framework.Assert.That().
SimpleTestUsingBoolean()
void NUnit.Framework.Constraints.DelayedConstraintTests.SimpleTestUsingBoolean () inline
References NUnit.Framework.Constraints.DelayedConstraintTests.AFTER, NUnit.Framework.Constraints.DelayedConstraintTests.boolValue, NUnit.Framework.Constraints.DelayedConstraintTests.DELAY, NUnit.Framework.Constraints.DelayedConstraintTests.POLLING, NUnit.Framework.Constraints.DelayedConstraintTests.SetValuesAfterDelay(), and NUnit.Framework.Assert.That().
ThatOverload_ZeroDelayIsAllowed()
void NUnit.Framework.Constraints.DelayedConstraintTests.ThatOverload_ZeroDelayIsAllowed () inline
References NUnit.Framework.Constraints.DelayedConstraintTests.DelegateReturningZero, and NUnit.Framework.Assert.That().
ThatOverload_DoesNotAcceptNegativeDelayValues()
void NUnit.Framework.Constraints.DelayedConstraintTests.ThatOverload_DoesNotAcceptNegativeDelayValues () inline
References NUnit.Framework.Constraints.DelayedConstraintTests.DelegateReturningZero, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
CanTestContentsOfList()
void NUnit.Framework.Constraints.DelayedConstraintTests.CanTestContentsOfList () inline
References NUnit.Framework.Constraints.DelayedConstraintTests.AFTER, NUnit.Framework.Has.Count, NUnit.Framework.Constraints.DelayedConstraintTests.list, NUnit.Framework.Constraints.DelayedConstraintTests.POLLING, NUnit.Framework.Constraints.DelayedConstraintTests.SetValuesAfterDelay(), and NUnit.Framework.Assert.That().
CanTestContentsOfDelegateReturningList()
void NUnit.Framework.Constraints.DelayedConstraintTests.CanTestContentsOfDelegateReturningList () inline
References NUnit.Framework.Constraints.DelayedConstraintTests.AFTER, NUnit.Framework.Has.Count, NUnit.Framework.Constraints.DelayedConstraintTests.list, NUnit.Framework.Constraints.DelayedConstraintTests.POLLING, NUnit.Framework.Constraints.DelayedConstraintTests.SetValuesAfterDelay(), and NUnit.Framework.Assert.That().
CanTestInitiallyNullDelegate()
void NUnit.Framework.Constraints.DelayedConstraintTests.CanTestInitiallyNullDelegate () inline
References NUnit.Framework.Constraints.DelayedConstraintTests.AFTER, NUnit.Framework.Constraints.DelayedConstraintTests.DELAY, NUnit.Framework.Is.Not, NUnit.Framework.Constraints.DelayedConstraintTests.POLLING, NUnit.Framework.Constraints.DelayedConstraintTests.SetValuesAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.statusString, and NUnit.Framework.Assert.That().
ThatBlockingDelegateWhichSucceedsWithoutPolling_ReturnsAfterDelay()
void NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichSucceedsWithoutPolling_ReturnsAfterDelay () inline
References NUnit.Framework.Constraints.DelayedConstraintTests.AFTER, NUnit.Framework.Constraints.DelayedConstraintTests.DELAY, NUnit.Framework.Constraints.DelayedConstraintTests.Delay(), NUnit.Framework.Is.GreaterThanOrEqualTo(), NUnit.Framework.Constraints.DelayedConstraintTests.MIN, NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
ThatBlockingDelegateWhichSucceedsWithPolling_ReturnsEarly()
void NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichSucceedsWithPolling_ReturnsEarly () inline
References NUnit.Framework.Constraints.DelayedConstraintTests.AFTER, NUnit.Framework.Constraints.DelayedConstraintTests.DELAY, NUnit.Framework.Constraints.DelayedConstraintTests.Delay(), NUnit.Framework.Constraints.DelayedConstraintTests.POLLING, NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
ThatBlockingDelegateWhichFailsWithoutPolling_FailsAfterDelay()
void NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichFailsWithoutPolling_FailsAfterDelay () inline
References NUnit.Framework.Constraints.DelayedConstraintTests.AFTER, NUnit.Framework.Constraints.DelayedConstraintTests.DELAY, NUnit.Framework.Constraints.DelayedConstraintTests.Delay(), NUnit.Framework.Is.GreaterThanOrEqualTo(), NUnit.Framework.Constraints.DelayedConstraintTests.MIN, NUnit.Framework.Assert.That(), NUnit.Framework.Assert.Throws(), and NUnit.Framework.Is.True.
ThatBlockingDelegateWhichFailsWithPolling_FailsAfterDelay()
void NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichFailsWithPolling_FailsAfterDelay () inline
References NUnit.Framework.Constraints.DelayedConstraintTests.AFTER, NUnit.Framework.Constraints.DelayedConstraintTests.DELAY, NUnit.Framework.Constraints.DelayedConstraintTests.Delay(), NUnit.Framework.Is.GreaterThanOrEqualTo(), NUnit.Framework.Constraints.DelayedConstraintTests.MIN, NUnit.Framework.Constraints.DelayedConstraintTests.POLLING, NUnit.Framework.Assert.That(), NUnit.Framework.Assert.Throws(), and NUnit.Framework.Is.True.
ThatBlockingDelegateWhichThrowsWithoutPolling_FailsAfterDelay()
void NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichThrowsWithoutPolling_FailsAfterDelay () inline
References NUnit.Framework.Constraints.DelayedConstraintTests.AFTER, NUnit.Framework.Constraints.DelayedConstraintTests.DELAY, NUnit.Framework.Constraints.DelayedConstraintTests.Delay(), NUnit.Framework.Is.GreaterThanOrEqualTo(), NUnit.Framework.Constraints.DelayedConstraintTests.MIN, NUnit.Framework.Assert.That(), NUnit.Framework.Assert.Throws(), and NUnit.Framework.Is.True.
ThatBlockingDelegateWhichThrowsWithPolling_FailsAfterDelay()
void NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichThrowsWithPolling_FailsAfterDelay () inline
References NUnit.Framework.Constraints.DelayedConstraintTests.AFTER, NUnit.Framework.Constraints.DelayedConstraintTests.DELAY, NUnit.Framework.Constraints.DelayedConstraintTests.Delay(), NUnit.Framework.Is.GreaterThanOrEqualTo(), NUnit.Framework.Constraints.DelayedConstraintTests.POLLING, NUnit.Framework.Assert.That(), NUnit.Framework.Assert.Throws(), and NUnit.Framework.Is.True.
MethodReturningVoid()
static void NUnit.Framework.Constraints.DelayedConstraintTests.MethodReturningVoid () inline static private
MethodReturningValue()
static object NUnit.Framework.Constraints.DelayedConstraintTests.MethodReturningValue () inline static private
References NUnit.Framework.Constraints.DelayedConstraintTests.boolValue.
Referenced by NUnit.Framework.Constraints.DelayedConstraintTests.DelayedConstraintTests().
MethodReturningFalse()
static object NUnit.Framework.Constraints.DelayedConstraintTests.MethodReturningFalse () inline static private
Referenced by NUnit.Framework.Constraints.DelayedConstraintTests.DelayedConstraintTests().
MethodReturningZero()
static object NUnit.Framework.Constraints.DelayedConstraintTests.MethodReturningZero () inline static private
Referenced by NUnit.Framework.Constraints.DelayedConstraintTests.DelayedConstraintTests().
Delay()
static void NUnit.Framework.Constraints.DelayedConstraintTests.Delay (int delay) inline static private
References NUnit.Framework.Constraints.DelayedConstraintTests.waitEvent.
Referenced by NUnit.Framework.Constraints.DelayedConstraintTests.MethodSetsValues(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichFailsWithoutPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichFailsWithPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichSucceedsWithoutPolling_ReturnsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichSucceedsWithPolling_ReturnsEarly(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichThrowsWithoutPolling_FailsAfterDelay(), and NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichThrowsWithPolling_FailsAfterDelay().
MethodSetsValues()
static void NUnit.Framework.Constraints.DelayedConstraintTests.MethodSetsValues () inline static private
References NUnit.Framework.Constraints.DelayedConstraintTests.boolValue, NUnit.Framework.Constraints.DelayedConstraintTests.Delay(), NUnit.Framework.Constraints.DelayedConstraintTests.list, NUnit.Framework.Constraints.DelayedConstraintTests.setValuesDelay, and NUnit.Framework.Constraints.DelayedConstraintTests.statusString.
Referenced by NUnit.Framework.Constraints.DelayedConstraintTests.SetValuesAfterDelay().
SetValuesAfterDelay()
void NUnit.Framework.Constraints.DelayedConstraintTests.SetValuesAfterDelay (int delay) inline private
References NUnit.Framework.Constraints.DelayedConstraintTests.MethodSetsValues(), and NUnit.Framework.Constraints.DelayedConstraintTests.setValuesDelay.
Referenced by NUnit.Framework.Constraints.DelayedConstraintTests.CanTestContentsOfDelegateReturningList(), NUnit.Framework.Constraints.DelayedConstraintTests.CanTestContentsOfList(), NUnit.Framework.Constraints.DelayedConstraintTests.CanTestInitiallyNullDelegate(), NUnit.Framework.Constraints.DelayedConstraintTests.SimpleTest(), NUnit.Framework.Constraints.DelayedConstraintTests.SimpleTestUsingBoolean(), and NUnit.Framework.Constraints.DelayedConstraintTests.SucceedsWithGoodDelegates().
Member Data Documentation
DELAY
const int NUnit.Framework.Constraints.DelayedConstraintTests.DELAY = 100 static private
Referenced by NUnit.Framework.Constraints.DelayedConstraintTests.CanTestInitiallyNullDelegate(), NUnit.Framework.Constraints.DelayedConstraintTests.SimpleTest(), NUnit.Framework.Constraints.DelayedConstraintTests.SimpleTestUsingBoolean(), NUnit.Framework.Constraints.DelayedConstraintTests.SucceedsWithGoodDelegates(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichFailsWithoutPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichFailsWithPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichSucceedsWithoutPolling_ReturnsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichSucceedsWithPolling_ReturnsEarly(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichThrowsWithoutPolling_FailsAfterDelay(), and NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichThrowsWithPolling_FailsAfterDelay().
AFTER
const int NUnit.Framework.Constraints.DelayedConstraintTests.AFTER = 300 static private
Referenced by NUnit.Framework.Constraints.DelayedConstraintTests.CanTestContentsOfDelegateReturningList(), NUnit.Framework.Constraints.DelayedConstraintTests.CanTestContentsOfList(), NUnit.Framework.Constraints.DelayedConstraintTests.CanTestInitiallyNullDelegate(), NUnit.Framework.Constraints.DelayedConstraintTests.SimpleTest(), NUnit.Framework.Constraints.DelayedConstraintTests.SimpleTestUsingBoolean(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichFailsWithoutPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichFailsWithPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichSucceedsWithoutPolling_ReturnsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichSucceedsWithPolling_ReturnsEarly(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichThrowsWithoutPolling_FailsAfterDelay(), and NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichThrowsWithPolling_FailsAfterDelay().
POLLING
const int NUnit.Framework.Constraints.DelayedConstraintTests.POLLING = 50 static private
Referenced by NUnit.Framework.Constraints.DelayedConstraintTests.CanTestContentsOfDelegateReturningList(), NUnit.Framework.Constraints.DelayedConstraintTests.CanTestContentsOfList(), NUnit.Framework.Constraints.DelayedConstraintTests.CanTestInitiallyNullDelegate(), NUnit.Framework.Constraints.DelayedConstraintTests.SimpleTest(), NUnit.Framework.Constraints.DelayedConstraintTests.SimpleTestUsingBoolean(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichFailsWithPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichSucceedsWithPolling_ReturnsEarly(), and NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichThrowsWithPolling_FailsAfterDelay().
MIN
const int NUnit.Framework.Constraints.DelayedConstraintTests.MIN = AFTER - 10 static private
Referenced by NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichFailsWithoutPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichFailsWithPolling_FailsAfterDelay(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichSucceedsWithoutPolling_ReturnsAfterDelay(), and NUnit.Framework.Constraints.DelayedConstraintTests.ThatBlockingDelegateWhichThrowsWithoutPolling_FailsAfterDelay().
boolValue
bool NUnit.Framework.Constraints.DelayedConstraintTests.boolValue static private
Referenced by NUnit.Framework.Constraints.DelayedConstraintTests.MethodReturningValue(), NUnit.Framework.Constraints.DelayedConstraintTests.MethodSetsValues(), NUnit.Framework.Constraints.DelayedConstraintTests.SetUp(), and NUnit.Framework.Constraints.DelayedConstraintTests.SimpleTestUsingBoolean().
list
List<int> NUnit.Framework.Constraints.DelayedConstraintTests.list static private
Referenced by NUnit.Framework.Constraints.DelayedConstraintTests.CanTestContentsOfDelegateReturningList(), NUnit.Framework.Constraints.DelayedConstraintTests.CanTestContentsOfList(), NUnit.Framework.Constraints.DelayedConstraintTests.MethodSetsValues(), and NUnit.Framework.Constraints.DelayedConstraintTests.SetUp().
statusString
string NUnit.Framework.Constraints.DelayedConstraintTests.statusString static private
Referenced by NUnit.Framework.Constraints.DelayedConstraintTests.CanTestInitiallyNullDelegate(), NUnit.Framework.Constraints.DelayedConstraintTests.MethodSetsValues(), and NUnit.Framework.Constraints.DelayedConstraintTests.SetUp().
SuccessData
object [] NUnit.Framework.Constraints.DelayedConstraintTests.SuccessData = new object[] { true } static private
FailureData
object [] NUnit.Framework.Constraints.DelayedConstraintTests.FailureData static private
Initial value:
= new object[] {
            new TestCaseData( false, "False" ),
            new TestCaseData( 0, "0" ),
            new TestCaseData( null, "null" ) }
DelegateReturningValue
ActualValueDelegate NUnit.Framework.Constraints.DelayedConstraintTests.DelegateReturningValue static private
Referenced by NUnit.Framework.Constraints.DelayedConstraintTests.DelayedConstraintTests(), and NUnit.Framework.Constraints.DelayedConstraintTests.SimpleTest().
DelegateReturningFalse
ActualValueDelegate NUnit.Framework.Constraints.DelayedConstraintTests.DelegateReturningFalse static private
Referenced by NUnit.Framework.Constraints.DelayedConstraintTests.DelayedConstraintTests().
DelegateReturningZero
ActualValueDelegate NUnit.Framework.Constraints.DelayedConstraintTests.DelegateReturningZero static private
Referenced by NUnit.Framework.Constraints.DelayedConstraintTests.DelayedConstraintTests(), NUnit.Framework.Constraints.DelayedConstraintTests.ThatOverload_DoesNotAcceptNegativeDelayValues(), and NUnit.Framework.Constraints.DelayedConstraintTests.ThatOverload_ZeroDelayIsAllowed().
SuccessDelegates
ActualValueDelegate<object> [] NUnit.Framework.Constraints.DelayedConstraintTests.SuccessDelegates static private
Referenced by NUnit.Framework.Constraints.DelayedConstraintTests.DelayedConstraintTests().
FailureDelegates
ActualValueDelegate<object> [] NUnit.Framework.Constraints.DelayedConstraintTests.FailureDelegates static private
Referenced by NUnit.Framework.Constraints.DelayedConstraintTests.DelayedConstraintTests().
setValuesDelay
int NUnit.Framework.Constraints.DelayedConstraintTests.setValuesDelay static private
Referenced by NUnit.Framework.Constraints.DelayedConstraintTests.MethodSetsValues(), and NUnit.Framework.Constraints.DelayedConstraintTests.SetValuesAfterDelay().
waitEvent
AutoResetEvent NUnit.Framework.Constraints.DelayedConstraintTests.waitEvent = new AutoResetEvent(false) static private
Referenced by NUnit.Framework.Constraints.DelayedConstraintTests.Delay().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/DelayedConstraintTests.cs