Doc: IGLib EXTENDED: NUnit.Framework.Internal.Filters.ClassNameFilterTests Class Reference
NUnit.Framework.Internal.Filters.ClassNameFilterTests Class Reference
Public Member Functions
ClassNameFilterTests (string value, bool isRegex)
void IsNotEmpty ()
void MatchTest ()
void PassTest ()
void ExplicitMatchTest ()
Public Member Functions inherited from NUnit.Framework.Internal.Filters.TestFilterTests
void SetUpSuite ()
Private Attributes
TestFilter _filter
Additional Inherited Members
Static Public Attributes inherited from NUnit.Framework.Internal.Filters.TestFilterTests
const string DUMMY_CLASS = "NUnit.Framework.Internal.Filters.TestFilterTests+DummyFixture"
Protected Attributes inherited from NUnit.Framework.Internal.Filters.TestFilterTests
readonly TestSuite _dummyFixture = TestBuilder.MakeFixture(typeof(DummyFixture))
readonly TestSuite _anotherFixture = TestBuilder.MakeFixture(typeof(AnotherFixture))
readonly TestSuite _yetAnotherFixture = TestBuilder.MakeFixture(typeof(YetAnotherFixture))
readonly TestSuite _fixtureWithMultipleTests = TestBuilder.MakeFixture (typeof (FixtureWithMultipleTests))
readonly TestSuite _topLevelSuite = new TestSuite("MySuite")
Constructor & Destructor Documentation
ClassNameFilterTests()
NUnit.Framework.Internal.Filters.ClassNameFilterTests.ClassNameFilterTests (string value, bool isRegex) inline
References NUnit.Framework.Internal.Filters.ClassNameFilterTests._filter.
Member Function Documentation
IsNotEmpty()
void NUnit.Framework.Internal.Filters.ClassNameFilterTests.IsNotEmpty () inline
References NUnit.Framework.Internal.Filters.ClassNameFilterTests._filter, NUnit.Framework.Assert.False(), and NUnit.Framework.Internal.TestFilter.IsEmpty.
MatchTest()
void NUnit.Framework.Internal.Filters.ClassNameFilterTests.MatchTest () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Internal.Filters.ClassNameFilterTests._filter, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.Match(), and NUnit.Framework.Assert.That().
PassTest()
void NUnit.Framework.Internal.Filters.ClassNameFilterTests.PassTest () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Internal.Filters.ClassNameFilterTests._filter, NUnit.Framework.Internal.Filters.TestFilterTests._topLevelSuite, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.Pass(), NUnit.Framework.Internal.TestSuite.Tests, and NUnit.Framework.Assert.That().
ExplicitMatchTest()
void NUnit.Framework.Internal.Filters.ClassNameFilterTests.ExplicitMatchTest () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Internal.Filters.ClassNameFilterTests._filter, NUnit.Framework.Internal.Filters.TestFilterTests._topLevelSuite, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.IsExplicitMatch(), NUnit.Framework.Internal.TestSuite.Tests, and NUnit.Framework.Assert.That().
Member Data Documentation
_filter
TestFilter NUnit.Framework.Internal.Filters.ClassNameFilterTests._filter private
Referenced by NUnit.Framework.Internal.Filters.ClassNameFilterTests.ClassNameFilterTests(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.IsNotEmpty(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.MatchTest(), and NUnit.Framework.Internal.Filters.ClassNameFilterTests.PassTest().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/Filters/ClassNameFilterTests.cs