Doc: IGLib EXTENDED: NUnit.ConsoleRunner.Tests.ResultReporterTests Class Reference
NUnit.ConsoleRunner.Tests.ResultReporterTests Class Reference
Public Member Functions
void CreateResult ()
void CreateReporter ()
void ReportSequenceTest ()
void SummaryReportTest ()
void ErrorsAndFailuresReportTest ()
void TestsNotRunTest ()
Private Member Functions
string GetReport (TestDelegate del)
IList< string > GetReportLines (TestDelegate del)
Private Attributes
XmlNode _result
ResultReporter _reporter
StringBuilder _report
Static Private Attributes
const string MOCK_TEST_RESULT = "NUnit.ConsoleRunner.Tests.MockTestResult.xml"
static readonly string[] REPORT_SEQUENCE
Member Function Documentation
CreateResult()
void NUnit.ConsoleRunner.Tests.ResultReporterTests.CreateResult () inline
References NUnit.ConsoleRunner.Tests.ResultReporterTests._result, NUnit.ConsoleRunner.Tests.ResultReporterTests.MOCK_TEST_RESULT, NUnit.Framework.Assert.NotNull(), and NUnit.Framework.Assert.That().
CreateReporter()
void NUnit.ConsoleRunner.Tests.ResultReporterTests.CreateReporter () inline
References NUnit.ConsoleRunner.Tests.ResultReporterTests._report, NUnit.ConsoleRunner.Tests.ResultReporterTests._reporter, and NUnit.ConsoleRunner.Tests.ResultReporterTests._result.
ReportSequenceTest()
void NUnit.ConsoleRunner.Tests.ResultReporterTests.ReportSequenceTest () inline
References NUnit.ConsoleRunner.Tests.ResultReporterTests._reporter, NUnit.ConsoleRunner.Tests.ResultReporterTests.GetReport(), NUnit.ConsoleRunner.Tests.ResultReporterTests.REPORT_SEQUENCE, NUnit.ConsoleRunner.ResultReporter.ReportResults(), and NUnit.Framework.Assert.That().
SummaryReportTest()
void NUnit.ConsoleRunner.Tests.ResultReporterTests.SummaryReportTest () inline
References NUnit.ConsoleRunner.Tests.ResultReporterTests._reporter, NUnit.Framework.Is.EqualTo(), NUnit.ConsoleRunner.Tests.ResultReporterTests.GetReportLines(), NUnit.Framework.Assert.That(), and NUnit.ConsoleRunner.ResultReporter.WriteSummaryReport().
ErrorsAndFailuresReportTest()
void NUnit.ConsoleRunner.Tests.ResultReporterTests.ErrorsAndFailuresReportTest () inline
References NUnit.ConsoleRunner.Tests.ResultReporterTests._reporter, NUnit.Framework.Is.EqualTo(), NUnit.ConsoleRunner.Tests.ResultReporterTests.GetReportLines(), NUnit.Framework.Assert.That(), and NUnit.ConsoleRunner.ResultReporter.WriteErrorsAndFailuresReport().
TestsNotRunTest()
void NUnit.ConsoleRunner.Tests.ResultReporterTests.TestsNotRunTest () inline
References NUnit.ConsoleRunner.Tests.ResultReporterTests._reporter, NUnit.Framework.Is.EqualTo(), NUnit.ConsoleRunner.Tests.ResultReporterTests.GetReportLines(), NUnit.Framework.Assert.That(), and NUnit.ConsoleRunner.ResultReporter.WriteNotRunReport().
GetReport()
string NUnit.ConsoleRunner.Tests.ResultReporterTests.GetReport (TestDelegate del) inline private
References NUnit.ConsoleRunner.Tests.ResultReporterTests._report.
Referenced by NUnit.ConsoleRunner.Tests.ResultReporterTests.GetReportLines(), and NUnit.ConsoleRunner.Tests.ResultReporterTests.ReportSequenceTest().
GetReportLines()
IList<string> NUnit.ConsoleRunner.Tests.ResultReporterTests.GetReportLines (TestDelegate del) inline private
References NUnit.ConsoleRunner.Tests.ResultReporterTests.GetReport().
Referenced by NUnit.ConsoleRunner.Tests.ResultReporterTests.ErrorsAndFailuresReportTest(), NUnit.ConsoleRunner.Tests.ResultReporterTests.SummaryReportTest(), and NUnit.ConsoleRunner.Tests.ResultReporterTests.TestsNotRunTest().
Member Data Documentation
MOCK_TEST_RESULT
const string NUnit.ConsoleRunner.Tests.ResultReporterTests.MOCK_TEST_RESULT = "NUnit.ConsoleRunner.Tests.MockTestResult.xml" static private
Referenced by NUnit.ConsoleRunner.Tests.ResultReporterTests.CreateResult().
REPORT_SEQUENCE
readonly string [] NUnit.ConsoleRunner.Tests.ResultReporterTests.REPORT_SEQUENCE static private
Initial value:
= new string[] {
            "Tests Not Run",
            "Errors and Failures",
            "Test Run Summary"
        }
Referenced by NUnit.ConsoleRunner.Tests.ResultReporterTests.ReportSequenceTest().
_result
XmlNode NUnit.ConsoleRunner.Tests.ResultReporterTests._result private
Referenced by NUnit.ConsoleRunner.Tests.ResultReporterTests.CreateReporter(), and NUnit.ConsoleRunner.Tests.ResultReporterTests.CreateResult().
_reporter
ResultReporter NUnit.ConsoleRunner.Tests.ResultReporterTests._reporter private
Referenced by NUnit.ConsoleRunner.Tests.ResultReporterTests.CreateReporter(), NUnit.ConsoleRunner.Tests.ResultReporterTests.ErrorsAndFailuresReportTest(), NUnit.ConsoleRunner.Tests.ResultReporterTests.ReportSequenceTest(), NUnit.ConsoleRunner.Tests.ResultReporterTests.SummaryReportTest(), and NUnit.ConsoleRunner.Tests.ResultReporterTests.TestsNotRunTest().
_report
StringBuilder NUnit.ConsoleRunner.Tests.ResultReporterTests._report private
Referenced by NUnit.ConsoleRunner.Tests.ResultReporterTests.CreateReporter(), and NUnit.ConsoleRunner.Tests.ResultReporterTests.GetReport().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitConsole/nunit3-console.tests/ResultReporterTests.cs