Doc: IGLib EXTENDED: NUnit.Framework.Tests.Attributes.TestExpectedResult Class Reference
NUnit.Framework.Tests.Attributes.TestExpectedResult Class Reference
Public Member Functions
int CanExpectInt ()
double CanExpectDouble ()
string CanExpectString ()
object ResultCanBeNull ()
int TestAttributeExpectedResultDoesNotOverrideTestCaseExpectedResult (int x, int y)
int ExpectedResultDoesNotBlockApplyToTestAttributes ()
Member Function Documentation
CanExpectInt()
int NUnit.Framework.Tests.Attributes.TestExpectedResult.CanExpectInt () inline
CanExpectDouble()
double NUnit.Framework.Tests.Attributes.TestExpectedResult.CanExpectDouble () inline
CanExpectString()
string NUnit.Framework.Tests.Attributes.TestExpectedResult.CanExpectString () inline
ResultCanBeNull()
object NUnit.Framework.Tests.Attributes.TestExpectedResult.ResultCanBeNull () inline
TestAttributeExpectedResultDoesNotOverrideTestCaseExpectedResult()
int NUnit.Framework.Tests.Attributes.TestExpectedResult.TestAttributeExpectedResultDoesNotOverrideTestCaseExpectedResult (int x, int y) inline
ExpectedResultDoesNotBlockApplyToTestAttributes()
int NUnit.Framework.Tests.Attributes.TestExpectedResult.ExpectedResultDoesNotBlockApplyToTestAttributes () inline
References NUnit.Framework.TestContext.CurrentContext, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.TestContext.TestAdapter.Properties, NUnit.Framework.TestContext.Test, and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/TestExpectedResult.cs