Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLARZT Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLARZT Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLARZT (DGEMV dgemv, DTRMV dtrmv, XERBLA xerbla, LSAME lsame)
DLARZT ()
void Run (string DIRECT, string STOREV, int N, int K, double[] V, int offset_v, int LDV, double[] TAU, int offset_tau, ref double[] T, int offset_t, int LDT)
Private Attributes
DGEMV _dgemv
DTRMV _dtrmv
XERBLA _xerbla
LSAME _lsame
Static Private Attributes
const double ZERO = 0.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLARZT forms the triangular factor T of a real block reflector H of order .GT. n, which is defined as a product of k elementary reflectors.
If DIRECT = 'F', H = H(1) H(2) . . . H(k) and T is upper triangular;
If DIRECT = 'B', H = H(k) . . . H(2) H(1) and T is lower triangular.
If STOREV = 'C', the vector which defines the elementary reflector H(i) is stored in the i-th column of the array V, and
H = I - V * T * V'
If STOREV = 'R', the vector which defines the elementary reflector H(i) is stored in the i-th row of the array V, and
H = I - V' * T * V
Currently, only STOREV = 'R' and DIRECT = 'B' are supported.
/summary>
Constructor & Destructor Documentation
DLARZT() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLARZT.DLARZT (DGEMV dgemv, DTRMV dtrmv, XERBLA xerbla, LSAME lsame) inline
DLARZT() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLARZT.DLARZT () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLARZT.Run (string DIRECT, string STOREV, int N, int K, double[] V, int offset_v, int LDV, double[] TAU, int offset_tau, ref double[] T, int offset_t, int LDT) inline
Purpose
DLARZT forms the triangular factor T of a real block reflector H of order .GT. n, which is defined as a product of k elementary reflectors.
If DIRECT = 'F', H = H(1) H(2) . . . H(k) and T is upper triangular;
If DIRECT = 'B', H = H(k) . . . H(2) H(1) and T is lower triangular.
If STOREV = 'C', the vector which defines the elementary reflector H(i) is stored in the i-th column of the array V, and
H = I - V * T * V'
If STOREV = 'R', the vector which defines the elementary reflector H(i) is stored in the i-th row of the array V, and
H = I - V' * T * V
Currently, only STOREV = 'R' and DIRECT = 'B' are supported.
/summary>
Parameters
DIRECT (input) CHARACTER*1 Specifies the order in which the elementary reflectors are multiplied to form the block reflector: = 'F': H = H(1) H(2) . . . H(k) (Forward, not supported yet) = 'B': H = H(k) . . . H(2) H(1) (Backward) /param>
Parameters
STOREV (input) CHARACTER*1 Specifies how the vectors which define the elementary reflectors are stored (see also Further Details): = 'C': columnwise (not supported yet) = 'R': rowwise /param>
Parameters
N (input) INTEGER The order of the block reflector H. N .GE. 0. /param>
Parameters
K (input) INTEGER The order of the triangular factor T (= the number of elementary reflectors). K .GE. 1. /param>
Parameters
V (input/output) DOUBLE PRECISION array, dimension (LDV,K) if STOREV = 'C' (LDV,N) if STOREV = 'R' The matrix V. See further details. /param>
Parameters
LDV (input) INTEGER The leading dimension of the array V. If STOREV = 'C', LDV .GE. max(1,N); if STOREV = 'R', LDV .GE. K. /param>
Parameters
TAU (input) DOUBLE PRECISION array, dimension (K) TAU(i) must contain the scalar factor of the elementary reflector H(i). /param>
Parameters
T (output) DOUBLE PRECISION array, dimension (LDT,K) The k by k triangular factor T of the block reflector. If DIRECT = 'F', T is upper triangular; if DIRECT = 'B', T is lower triangular. The rest of the array is not used. /param>
Parameters
LDT (input) INTEGER The leading dimension of the array T. LDT .GE. K. /param>
References DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRMV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLARZT.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTZRZF.Run(), and DotNumerics.LinearAlgebra.CSLapack.DORMRZ.Run().
Member Data Documentation
_dgemv
DGEMV DotNumerics.LinearAlgebra.CSLapack.DLARZT._dgemv private
_dtrmv
DTRMV DotNumerics.LinearAlgebra.CSLapack.DLARZT._dtrmv private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLARZT._xerbla private
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLARZT._lsame private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLARZT.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLARZT.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlarzt.cs