Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DASUM Class Reference
DotNumerics.LinearAlgebra.CSLapack.DASUM Class Reference
Public Member Functions
DASUM ()
double Run (int N, double[] DX, int offset_dx, int INCX)
Detailed Description
Purpose
takes the sum of the absolute values. jack dongarra, linpack, 3/11/78. modified 3/93 to return if incx .le. 0. modified 12/3/93, array(1) declarations changed to array(*) /summary>
Constructor & Destructor Documentation
DASUM()
DotNumerics.LinearAlgebra.CSLapack.DASUM.DASUM () inline
Member Function Documentation
Run()
double DotNumerics.LinearAlgebra.CSLapack.DASUM.Run (int N, double[] DX, int offset_dx, int INCX) inline
Purpose
takes the sum of the absolute values. jack dongarra, linpack, 3/11/78. modified 3/93 to return if incx .le. 0. modified 12/3/93, array(1) declarations changed to array(*) /summary>
References DotNumerics.FortranLibrary.FortranLib.Mod().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLACON.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLATRS.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dasum.cs