Doc: IGLib EXTENDED: AForge.Video.AsyncVideoSource Class Reference
AForge.Video.AsyncVideoSource Class Reference
Proxy video source for asynchronous processing of another nested video source.
Public Member Functions
AsyncVideoSource (IVideoSource nestedVideoSource)
Initializes a new instance of the AsyncVideoSource class.
AsyncVideoSource (IVideoSource nestedVideoSource, bool skipFramesIfBusy)
Initializes a new instance of the AsyncVideoSource class.
void Start ()
Start video source.
void SignalToStop ()
Signal video source to stop its work.
void WaitForStop ()
Wait for video source has stopped.
void Stop ()
Stop video source.
Properties
VideoSourceErrorEventHandler VideoSourceError
Video source error event.
PlayingFinishedEventHandler PlayingFinished
Video playing finished event.
IVideoSource NestedVideoSource [get]
Nested video source which is the target for asynchronous processing.
bool SkipFramesIfBusy [get, set]
Specifies if the object should skip frames from the nested video source when it is busy.
string Source [get]
Video source string.
int FramesReceived [get]
Received frames count.
long BytesReceived [get]
Received bytes count.
int FramesProcessed [get]
Processed frames count.
bool IsRunning [get]
State of the video source.
Properties inherited from AForge.Video.IVideoSource
string Source [get]
Video source.
int FramesReceived [get]
Received frames count.
long BytesReceived [get]
Received bytes count.
bool IsRunning [get]
State of the video source.
Events
NewFrameEventHandler NewFrame
New frame event.
Events inherited from AForge.Video.IVideoSource
NewFrameEventHandler NewFrame
New frame event.
VideoSourceErrorEventHandler VideoSourceError
Video source error event.
PlayingFinishedEventHandler PlayingFinished
Video playing finished event.
Private Member Functions
void Free ()
void nestedVideoSource_NewFrame (object sender, NewFrameEventArgs eventArgs)
void imageProcessingThread_Worker ()
Static Private Member Functions
static Bitmap CloneImage (Bitmap source)
static Bitmap CloneImage (BitmapData sourceData)
Private Attributes
readonly IVideoSource nestedVideoSource = null
Bitmap lastVideoFrame = null
Thread imageProcessingThread = null
AutoResetEvent isNewFrameAvailable = null
AutoResetEvent isProcessingThreadAvailable = null
bool skipFramesIfBusy = false
int framesProcessed
Detailed Description
Proxy video source for asynchronous processing of another nested video source.
The class represents a simple proxy, which wraps the specified NestedVideoSource with the aim of asynchronous processing of received video frames. The class intercepts NewFrame event from the nested video source and fires it to clients from its own thread, which is different from the thread used by nested video source for video acquisition. This allows clients to perform processing of video frames without blocking video acquisition thread, which continue to run and acquire next video frame while current is still processed.
For example, let’s suppose that it takes 100 ms for the nested video source to acquire single frame, so the original frame rate is 10 frames per second. Also let’s assume that we have an image processing routine, which also takes 100 ms to process a single frame. If the acquisition and processing are done sequentially, then resulting frame rate will drop to 5 frames per second. However, if doing both in parallel, then there is a good chance to keep resulting frame rate equal (or close) to the original frame rate.
The class provides a bonus side effect - easer debugging of image processing routines, which are put into NewFrame event handler. In many cases video source classes fire their IVideoSource.NewFrame event from a try/catch block, which makes it very hard to spot error made in user's code - the catch block simply hides exception raised in user’s code. The AsyncVideoSource does not have any try/catch blocks around firing of NewFrame event, so always user gets exception in the case it comes from his code. At the same time nested video source is not affected by the user's exception, since it runs in different thread.
Sample usage:
// usage of AsyncVideoSource is the same as usage of any
// other video source class, so code change is very little
// create nested video source, for example JPEGStream
JPEGStream stream = new JPEGStream("some url");
// create async video source
AsyncVideoSource asyncSource = new AsyncVideoSource(stream);
// set NewFrame event handler
asyncSource.NewFrame += new NewFrameEventHandler(video_NewFrame);
// start the video source
asyncSource.Start();
// ...
private void video_NewFrame(object sender, NewFrameEventArgs eventArgs)
{
    // get new frame
    Bitmap bitmap = eventArgs.Frame;
    // process the frame
}
Constructor & Destructor Documentation
AsyncVideoSource() [1/2]
AForge.Video.AsyncVideoSource.AsyncVideoSource (IVideoSource nestedVideoSource) inline
Initializes a new instance of the AsyncVideoSource class.
Parameters
nestedVideoSource Nested video source which is the target for asynchronous processing.
References AForge.Video.AsyncVideoSource.nestedVideoSource.
AsyncVideoSource() [2/2]
AForge.Video.AsyncVideoSource.AsyncVideoSource (IVideoSource nestedVideoSource, bool skipFramesIfBusy) inline
Initializes a new instance of the AsyncVideoSource class.
Parameters
nestedVideoSource Nested video source which is the target for asynchronous processing.
skipFramesIfBusy Specifies if the object should skip frames from the nested video source in the case if it is still busy processing the previous video frame.
References AForge.Video.AsyncVideoSource.nestedVideoSource, and AForge.Video.AsyncVideoSource.skipFramesIfBusy.
Member Function Documentation
Start()
void AForge.Video.AsyncVideoSource.Start () inline
Start video source.
Starts the nested video source and returns execution to caller. This object creates an extra thread which is used to fire NewFrame events, so the image processing could be done on another thread without blocking video acquisition thread.
Implements AForge.Video.IVideoSource.
References AForge.Video.AsyncVideoSource.framesProcessed, AForge.Video.AsyncVideoSource.imageProcessingThread, AForge.Video.AsyncVideoSource.imageProcessingThread_Worker(), AForge.Video.AsyncVideoSource.isNewFrameAvailable, AForge.Video.AsyncVideoSource.isProcessingThreadAvailable, AForge.Video.AsyncVideoSource.IsRunning, AForge.Video.AsyncVideoSource.nestedVideoSource, AForge.Video.AsyncVideoSource.nestedVideoSource_NewFrame(), AForge.Video.IVideoSource.NewFrame, AForge.Video.NewFrameEventHandler(), and AForge.Video.IVideoSource.Start().
SignalToStop()
void AForge.Video.AsyncVideoSource.SignalToStop () inline
Signal video source to stop its work.
Signals video source to stop its background thread, stop to provide new frames and free resources.
Implements AForge.Video.IVideoSource.
References AForge.Video.AsyncVideoSource.nestedVideoSource, and AForge.Video.IVideoSource.SignalToStop().
WaitForStop()
void AForge.Video.AsyncVideoSource.WaitForStop () inline
Wait for video source has stopped.
Waits for video source stopping after it was signalled to stop using SignalToStop method.
Implements AForge.Video.IVideoSource.
References AForge.Video.AsyncVideoSource.Free(), AForge.Video.AsyncVideoSource.nestedVideoSource, and AForge.Video.IVideoSource.WaitForStop().
Stop()
void AForge.Video.AsyncVideoSource.Stop () inline
Stop video source.
Stops nested video source by calling its IVideoSource.Stop method. See documentation of the particular video source for additional details.
Implements AForge.Video.IVideoSource.
References AForge.Video.AsyncVideoSource.Free(), AForge.Video.AsyncVideoSource.nestedVideoSource, and AForge.Video.IVideoSource.Stop().
Free()
void AForge.Video.AsyncVideoSource.Free () inline private
References AForge.Video.AsyncVideoSource.imageProcessingThread, AForge.Video.AsyncVideoSource.isNewFrameAvailable, AForge.Video.AsyncVideoSource.isProcessingThreadAvailable, AForge.Video.AsyncVideoSource.lastVideoFrame, AForge.Video.AsyncVideoSource.nestedVideoSource, AForge.Video.AsyncVideoSource.nestedVideoSource_NewFrame(), AForge.Video.IVideoSource.NewFrame, and AForge.Video.NewFrameEventHandler().
Referenced by AForge.Video.AsyncVideoSource.Stop(), and AForge.Video.AsyncVideoSource.WaitForStop().
nestedVideoSource_NewFrame()
void AForge.Video.AsyncVideoSource.nestedVideoSource_NewFrame (object sender, NewFrameEventArgs eventArgs) inline private
References AForge.Video.AsyncVideoSource.CloneImage(), AForge.Video.NewFrameEventArgs.Frame, AForge.Video.AsyncVideoSource.isNewFrameAvailable, AForge.Video.AsyncVideoSource.isProcessingThreadAvailable, AForge.Video.AsyncVideoSource.lastVideoFrame, AForge.Video.AsyncVideoSource.NewFrame, and AForge.Video.AsyncVideoSource.skipFramesIfBusy.
Referenced by AForge.Video.AsyncVideoSource.Free(), and AForge.Video.AsyncVideoSource.Start().
imageProcessingThread_Worker()
void AForge.Video.AsyncVideoSource.imageProcessingThread_Worker () inline private
References AForge.Video.AsyncVideoSource.framesProcessed, AForge.Video.AsyncVideoSource.isNewFrameAvailable, AForge.Video.AsyncVideoSource.isProcessingThreadAvailable, AForge.Video.AsyncVideoSource.lastVideoFrame, and AForge.Video.AsyncVideoSource.NewFrame.
Referenced by AForge.Video.AsyncVideoSource.Start().
CloneImage() [1/2]
static Bitmap AForge.Video.AsyncVideoSource.CloneImage (Bitmap source) inline static private
Referenced by AForge.Video.AsyncVideoSource.nestedVideoSource_NewFrame().
CloneImage() [2/2]
static Bitmap AForge.Video.AsyncVideoSource.CloneImage (BitmapData sourceData) inline static private
References AForge.SystemTools.CopyUnmanagedMemory().
Member Data Documentation
nestedVideoSource
readonly IVideoSource AForge.Video.AsyncVideoSource.nestedVideoSource = null private
Referenced by AForge.Video.AsyncVideoSource.AsyncVideoSource(), AForge.Video.AsyncVideoSource.Free(), AForge.Video.AsyncVideoSource.SignalToStop(), AForge.Video.AsyncVideoSource.Start(), AForge.Video.AsyncVideoSource.Stop(), and AForge.Video.AsyncVideoSource.WaitForStop().
lastVideoFrame
Bitmap AForge.Video.AsyncVideoSource.lastVideoFrame = null private
Referenced by AForge.Video.AsyncVideoSource.Free(), AForge.Video.AsyncVideoSource.imageProcessingThread_Worker(), and AForge.Video.AsyncVideoSource.nestedVideoSource_NewFrame().
imageProcessingThread
Thread AForge.Video.AsyncVideoSource.imageProcessingThread = null private
Referenced by AForge.Video.AsyncVideoSource.Free(), and AForge.Video.AsyncVideoSource.Start().
isNewFrameAvailable
AutoResetEvent AForge.Video.AsyncVideoSource.isNewFrameAvailable = null private
Referenced by AForge.Video.AsyncVideoSource.Free(), AForge.Video.AsyncVideoSource.imageProcessingThread_Worker(), AForge.Video.AsyncVideoSource.nestedVideoSource_NewFrame(), and AForge.Video.AsyncVideoSource.Start().
isProcessingThreadAvailable
AutoResetEvent AForge.Video.AsyncVideoSource.isProcessingThreadAvailable = null private
Referenced by AForge.Video.AsyncVideoSource.Free(), AForge.Video.AsyncVideoSource.imageProcessingThread_Worker(), AForge.Video.AsyncVideoSource.nestedVideoSource_NewFrame(), and AForge.Video.AsyncVideoSource.Start().
skipFramesIfBusy
bool AForge.Video.AsyncVideoSource.skipFramesIfBusy = false private
Referenced by AForge.Video.AsyncVideoSource.AsyncVideoSource(), and AForge.Video.AsyncVideoSource.nestedVideoSource_NewFrame().
framesProcessed
int AForge.Video.AsyncVideoSource.framesProcessed private
Referenced by AForge.Video.AsyncVideoSource.imageProcessingThread_Worker(), and AForge.Video.AsyncVideoSource.Start().
Property Documentation
VideoSourceError
VideoSourceErrorEventHandler AForge.Video.AsyncVideoSource.VideoSourceError add remove
Video source error event.
This event is used to notify clients about any type of errors occurred in video source object, for example internal exceptions.
<note>Unlike NewFrame event, this event is simply redirected to the corresponding event of the NestedVideoSource, so it is fired from the thread of the nested video source.</note>
PlayingFinished
PlayingFinishedEventHandler AForge.Video.AsyncVideoSource.PlayingFinished add remove
Video playing finished event.
This event is used to notify clients that the video playing has finished.
<note>Unlike NewFrame event, this event is simply redirected to the corresponding event of the NestedVideoSource, so it is fired from the thread of the nested video source.</note>
NestedVideoSource
IVideoSource AForge.Video.AsyncVideoSource.NestedVideoSource get
Nested video source which is the target for asynchronous processing.
The property is set through the class constructor.
All calls to this object are actually redirected to the nested video source. The only exception is the NewFrame event, which is handled differently. This object gets IVideoSource.NewFrame event from the nested class and then fires another NewFrame event, but from a different thread.
SkipFramesIfBusy
bool AForge.Video.AsyncVideoSource.SkipFramesIfBusy get set
Specifies if the object should skip frames from the nested video source when it is busy.
Specifies if the object should skip frames from the nested video source in the case if it is still busy processing the previous video frame in its own thread.
Default value is set to false.
Source
string AForge.Video.AsyncVideoSource.Source get
Video source string.
The property is redirected to the corresponding property of NestedVideoSource, so check its documentation to find what it means.
FramesReceived
int AForge.Video.AsyncVideoSource.FramesReceived get
Received frames count.
Number of frames the nested video source received from the moment of the last access to the property.
BytesReceived
long AForge.Video.AsyncVideoSource.BytesReceived get
Received bytes count.
Number of bytes the nested video source received from the moment of the last access to the property.
FramesProcessed
int AForge.Video.AsyncVideoSource.FramesProcessed get
Processed frames count.
The property keeps the number of processed video frames since the last access to this property.
The value of this property equals to FramesReceived in most cases if the SkipFramesIfBusy property is set to false - every received frame gets processed sooner or later. However, if the SkipFramesIfBusy property is set to true, then value of this property may be lower than the value of the FramesReceived property, which means that nested video source performs acquisition faster than client perform processing of the received frame and some frame are skipped from processing.
IsRunning
bool AForge.Video.AsyncVideoSource.IsRunning get
State of the video source.
Current state of the video source object - running or not.
Referenced by AForge.Video.AsyncVideoSource.Start().
Event Documentation
NewFrame
NewFrameEventHandler AForge.Video.AsyncVideoSource.NewFrame
New frame event.
Notifies clients about new available frame from video source.
<note>This event is fired from a different thread other than the video acquisition thread created by NestedVideoSource. This allows nested video frame to continue acquisition of the next video frame while clients perform processing of the current video frame.</note>
<note>Since video source may have multiple clients, each client is responsible for making a copy (cloning) of the passed video frame, because the video source disposes its own original copy after notifying of clients.</note>
Referenced by AForge.Video.AsyncVideoSource.imageProcessingThread_Worker(), and AForge.Video.AsyncVideoSource.nestedVideoSource_NewFrame().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Video/AsyncVideoSource.cs