Doc: IGLib EXTENDED: NUnit.TestData.ActionAttributeTests.TaggedActionAttribute Class Reference
NUnit.TestData.ActionAttributeTests.TaggedActionAttribute Class Reference
Public Member Functions
TaggedActionAttribute (string tag)
TaggedActionAttribute (string tag, ActionTargets targets)
override void BeforeTest (ITest test)
Executed before each test is run
override void AfterTest (ITest test)
Executed after each test is run
Properties
override ActionTargets Targets [get]
Properties inherited from NUnit.Framework.TestActionAttribute
virtual ActionTargets Targets [get]
Provides the target for the action attribute
Properties inherited from NUnit.Framework.ITestAction
ActionTargets Targets [get]
Provides the target for the action attribute
Private Member Functions
void AddResult (string phase, ITest test)
Private Attributes
readonly string _tag = null
readonly ActionTargets _targets = ActionTargets.Default
Constructor & Destructor Documentation
TaggedActionAttribute() [1/2]
NUnit.TestData.ActionAttributeTests.TaggedActionAttribute.TaggedActionAttribute (string tag) inline
References NUnit.TestData.ActionAttributeTests.TaggedActionAttribute._tag.
TaggedActionAttribute() [2/2]
NUnit.TestData.ActionAttributeTests.TaggedActionAttribute.TaggedActionAttribute (string tag, ActionTargets targets) inline
References NUnit.TestData.ActionAttributeTests.TaggedActionAttribute._tag, and NUnit.TestData.ActionAttributeTests.TaggedActionAttribute._targets.
Member Function Documentation
BeforeTest()
override void NUnit.TestData.ActionAttributeTests.TaggedActionAttribute.BeforeTest (ITest test) inline virtual
Executed before each test is run
Parameters
test The test that is going to be run.
Reimplemented from NUnit.Framework.TestActionAttribute.
References NUnit.TestData.ActionAttributeTests.TaggedActionAttribute.AddResult().
AfterTest()
override void NUnit.TestData.ActionAttributeTests.TaggedActionAttribute.AfterTest (ITest test) inline virtual
Executed after each test is run
Parameters
test The test that has just been run.
Reimplemented from NUnit.Framework.TestActionAttribute.
References NUnit.TestData.ActionAttributeTests.TaggedActionAttribute.AddResult().
AddResult()
void NUnit.TestData.ActionAttributeTests.TaggedActionAttribute.AddResult (string phase, ITest test) inline private
References NUnit.TestData.ActionAttributeTests.TaggedActionAttribute._tag, NUnit.TestData.ActionAttributeTests.TaggedActionAttribute._targets, NUnit.TestData.ActionAttributeTests.ActionAttributeFixture.Events, and NUnit.Framework.Interfaces.ITest.Name.
Referenced by NUnit.TestData.ActionAttributeTests.TaggedActionAttribute.AfterTest(), and NUnit.TestData.ActionAttributeTests.TaggedActionAttribute.BeforeTest().
Member Data Documentation
_tag
readonly string NUnit.TestData.ActionAttributeTests.TaggedActionAttribute._tag = null private
Referenced by NUnit.TestData.ActionAttributeTests.TaggedActionAttribute.AddResult(), and NUnit.TestData.ActionAttributeTests.TaggedActionAttribute.TaggedActionAttribute().
_targets
readonly ActionTargets NUnit.TestData.ActionAttributeTests.TaggedActionAttribute._targets = ActionTargets.Default private
Referenced by NUnit.TestData.ActionAttributeTests.TaggedActionAttribute.AddResult(), and NUnit.TestData.ActionAttributeTests.TaggedActionAttribute.TaggedActionAttribute().
Property Documentation
Targets
override ActionTargets NUnit.TestData.ActionAttributeTests.TaggedActionAttribute.Targets get
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/testdata/ActionAttributeFixture.cs