Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAMC5 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAMC5 Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAMC5 (DLAMC3 dlamc3)
DLAMC5 ()
void Run (int BETA, int P, int EMIN, bool IEEE, ref int EMAX, ref double RMAX)
Private Attributes
DLAMC3 _dlamc3
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAMC5 attempts to compute RMAX, the largest machine floating-point number, without overflow. It assumes that EMAX + abs(EMIN) sum approximately to a power of 2. It will fail on machines where this assumption does not hold, for example, the Cyber 205 (EMIN = -28625, EMAX = 28718). It will also fail if the value supplied for EMIN is too large (i.e. too close to zero), probably with overflow.
/summary>
Constructor & Destructor Documentation
DLAMC5() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAMC5.DLAMC5 (DLAMC3 dlamc3) inline
DLAMC5() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAMC5.DLAMC5 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAMC5.Run (int BETA, int P, int EMIN, bool IEEE, ref int EMAX, ref double RMAX) inline
Purpose
DLAMC5 attempts to compute RMAX, the largest machine floating-point number, without overflow. It assumes that EMAX + abs(EMIN) sum approximately to a power of 2. It will fail on machines where this assumption does not hold, for example, the Cyber 205 (EMIN = -28625, EMAX = 28718). It will also fail if the value supplied for EMIN is too large (i.e. too close to zero), probably with overflow.
/summary>
Parameters
BETA (input) INTEGER The base of floating-point arithmetic. /param>
Parameters
P (input) INTEGER The number of base BETA digits in the mantissa of a floating-point value. /param>
Parameters
EMIN (input) INTEGER The minimum exponent before (gradual) underflow. /param>
Parameters
IEEE (input) LOGICAL A logical flag specifying whether or not the arithmetic system is thought to comply with the IEEE standard. /param>
Parameters
EMAX (output) INTEGER The largest exponent before overflow /param>
Parameters
RMAX (output) DOUBLE PRECISION The largest machine floating-point number. /param>
References DotNumerics.FortranLibrary.FortranLib.Mod(), DotNumerics.LinearAlgebra.CSLapack.DLAMC5.ONE, DotNumerics.LinearAlgebra.CSLapack.DLAMC3.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAMC5.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAMC2.Run().
Member Data Documentation
_dlamc3
DLAMC3 DotNumerics.LinearAlgebra.CSLapack.DLAMC5._dlamc3 private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAMC5.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAMC5.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAMC5.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAMC5.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlamch.cs