Doc: IGLib EXTENDED: NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack Class Reference
NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack Class Reference
OperatorStack is a type-safe stack for holding ConstraintOperators
Public Member Functions
OperatorStack (ConstraintBuilder builder)
Initializes a new instance of the OperatorStack class.
void Push (ConstraintOperator op)
Pushes the specified operator onto the stack.
ConstraintOperator Pop ()
Pops the topmost operator from the stack.
Properties
bool Empty [get]
Gets a value indicating whether this OperatorStack is empty.
ConstraintOperator Top [get]
Gets the topmost operator without modifying the stack.
Private Attributes
readonly Stack< ConstraintOperator > stack = new Stack<ConstraintOperator>()
Detailed Description
OperatorStack is a type-safe stack for holding ConstraintOperators
Constructor & Destructor Documentation
OperatorStack()
NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack.OperatorStack (ConstraintBuilder builder) inline
Initializes a new instance of the OperatorStack class.
Parameters
builder The ConstraintBuilder using this stack.
Member Function Documentation
Push()
void NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack.Push (ConstraintOperator op) inline
Pushes the specified operator onto the stack.
Parameters
op The operator to put onto the stack.
References NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack.stack.
Referenced by NUnit.Framework.Constraints.ConstraintBuilder.Append(), and NUnit.Framework.Constraints.ConstraintBuilder.SetTopOperatorRightContext().
Pop()
ConstraintOperator NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack.Pop () inline
Pops the topmost operator from the stack.
Returns
The topmost operator on the stack
References NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack.stack.
Referenced by NUnit.Framework.Constraints.ConstraintBuilder.ReduceOperatorStack(), NUnit.Framework.Constraints.ConstraintBuilder.Resolve(), and NUnit.Framework.Constraints.ConstraintBuilder.SetTopOperatorRightContext().
Member Data Documentation
stack
readonly Stack<ConstraintOperator> NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack.stack = new Stack<ConstraintOperator>() private
Referenced by NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack.Pop(), and NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack.Push().
Property Documentation
Empty
bool NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack.Empty get
Gets a value indicating whether this OperatorStack is empty.
true if empty; otherwise, false.
Referenced by NUnit.Framework.Constraints.ConstraintBuilder.ReduceOperatorStack(), and NUnit.Framework.Constraints.ConstraintBuilder.Resolve().
Top
ConstraintOperator NUnit.Framework.Constraints.ConstraintBuilder.OperatorStack.Top get
Gets the topmost operator without modifying the stack.
Referenced by NUnit.Framework.Constraints.ConstraintBuilder.ReduceOperatorStack(), and NUnit.Framework.Constraints.ConstraintBuilder.SetTopOperatorRightContext().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Constraints/ConstraintBuilder.cs