Doc: IGLib EXTENDED: IG.Script.ScriptExtExamples Class Reference
IG.Script.ScriptExtExamples Class Reference
Classes
class ProgramPipeTest
Public Member Functions
ScriptExtExamples ()
override void Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings)
Adds commands to the internal interpreter.
virtual string Custom (string[] arguments)
Custom command.
string PointClouds (string[] arguments)
Test action - to see that script is alive.
string Graphics3d (string[] arguments)
Test action - to see that script is alive.
string NamedPipes (string[] arguments)
Test action - named pipes.
string NamedPipeClient (string[] arguments)
Test action - named pipe client.
string NamedPipeServer (string[] arguments)
Test action - named pipe server.
ScriptExtExamples ()
override void Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings)
Adds commands to the internal interpreter.
virtual string Custom (string[] arguments)
Custom command.
string PointClouds (string[] arguments)
Test action - to see that script is alive.
string Graphics3d (string[] arguments)
Test action - to see that script is alive.
Public Member Functions inherited from IG.Lib.LoadableScriptBase
LoadableScriptBase ()
Argument-less constructor. If argument-less constructor is called then initialization is not performed and will be performed later.
string Run (string[] arguments)
Performs the action of this object. Override this in derived classes!
void Initialize (string[] arguments)
Initializes the object. If not called explicitly, this method is automatically called at the first call to the Run method.
virtual string Script_DefaultInitialize (string[] arguments)
Default initialization method for scripts.
virtual string Script_DefaultRun (string[] arguments)
Default run method for the script. Can be used when only installed commands are run by hte script.
virtual ICommandLineApplicationInterpreter Script_CreateInterpreterWithoutCommands ()
Creates and returns an interpreter that can be used as script's internal interpreter for running script's commands.
delegate string Script_CommandDelegate (string[] args)
Delegate for commands that are installed on script's internal interpreter (property Script_Interpreter).
void Script_AddCommand (string commandName, Script_CommandDelegate command, string helpString)
Adds a new internal script command under specified name to the internal interpreter of the current script object.
virtual void Script_AddCommand (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings, string commandName, Script_CommandDelegate command, string helpString)
Adds a new internal script command under specified name to the internal interpreter of the current script object.
string Script_GetHelpString (string scriptCommandName)
Returns help string for internal script command with specified name, or null if help string is not installed for such a command.
void Script_PrintCommandsHelp ()
Prits help for the installed internal commands of the script.
virtual bool Script_ContainsCommand (string commandName)
Returns true if the internal script's interpreter contains a command with specified name, false otherwise.
virtual bool Script_ContainsScriptCommand (string commandName)
Returns true if the specified command is script command (i.e. its first argument is command-name and it is run through the Script_CommandAdapter object).
virtual void Script_RemoveCommand (string commandName)
Removes the specified internal script command from the internal interpreter of the current scripting object.
virtual void Script_RemoveAllCommands ()
Removes ALL internal script commands from the internal interpreter of the current scripting object.
string Script_Run (string[] arguments)
Runs internal script command.
string Script_Run (string commandName, params string[] otherArguments)
Runs internal script command.
virtual void Script_PrintArguments (string messageString, string[] arguments)
Prints the specified array of string arguments (usually passed as command-line arguments).
Static Public Attributes
const string ConstCustom = "custom"
Name of the command for custom test.
const string ConstHelpCustom = "Performs a set of custom tests."
const string ConstPointClouds = "pointclouds"
Name of the command for testing point clouds utilities.
const string ConstHelpPointClouts = "Test of utilities for manipulating clouds of points."
const string ConstGraphics3d = "graphics3d"
Name of the command for testing 3D graphics.
const string consthelpGraphics3d = "Tests of 3D graphics."
Static Public Attributes inherited from IG.Lib.LoadableScriptBase
const string ConstDefaultHelp = "Help"
Default command name for help.
const string ConstHelpDefaultUniversal = "?"
Universal name of the help command.
const string ConstDefaultTestScrip = "TestScript"
Default command name for test method.
Protected Member Functions
override void InitializeThis (string[] arguments)
Initializes the current object.
override string RunThis (string[] arguments)
Runs action of the current object.
override void InitializeThis (string[] arguments)
Initializes the current object.
override string RunThis (string[] arguments)
Runs action of the current object.
Protected Member Functions inherited from IG.Lib.LoadableScriptBase
delegate string CommandMethod (string commandName, string[] args)
Delegate for internal command methods.
ICommandLineApplicationInterpreter Script_CreateInterpreter ()
Creates and returns an interpreter that can be used as script's internal interpreter for running script's commands.
virtual string Script_CommandHelp (string[] arguments)
Prints help.
virtual string Script_CommandTestScript (string[] arguments)
Prints help.
Additional Inherited Members
Protected Attributes inherited from IG.Lib.LoadableScriptBase
string _embeddedCommandName = null
int _outputLevel = DefaultOutputLevel
ICommandLineApplicationInterpreter _script_interpreter
Properties inherited from IG.Lib.LoadableScriptBase
string EmbeddedCommandName [get, set]
Command that was used to launch the current embedded application script.
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
string[] InitializationArguments [get, set]
Arguments used by the initialization method. WARNING: arguments can only be set before initialization is performed. Initialization is performed either implicitly at the first call to the Run method or explicitly by calling the Initialize method.
virtual bool IsInitialized [get, protected set]
Whether the object has been initialized or not.
static int DefaultOutputLevel [get, set]
int OutputLevel [get, set]
Level of output to console produced by some operations of the current object.
virtual ICommandLineApplicationInterpreter Script_Interpreter [get, protected set]
Script's internal interpreter that takes care for execution of installed internal commands.
SortedList< string, string > Script_CommandHelpStrings [get]
Contains help strings associated with script commands installed on interpreter.
Properties inherited from IG.Lib.ILoadableScript
string EmbeddedCommandName [get, set]
Command that was used to launch the current embedded application script.
string[] InitializationArguments [get, set]
Arguments used by the initialization method.
bool IsInitialized [get]
Whether the object has been initialized or not.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Constructor & Destructor Documentation
ScriptExtExamples() [1/2]
IG.Script.ScriptExtExamples.ScriptExtExamples () inline
ScriptExtExamples() [2/2]
IG.Script.ScriptExtExamples.ScriptExtExamples () inline
Member Function Documentation
InitializeThis() [1/2]
override void IG.Script.ScriptExtExamples.InitializeThis (string[] arguments) inline protected virtual
Initializes the current object.
Implements IG.Lib.LoadableScriptBase.
Reimplemented in IG.Script.ScriptExtExamplesExt.
References IG.Lib.LoadableScriptBase.Script_DefaultInitialize().
RunThis() [1/2]
override string IG.Script.ScriptExtExamples.RunThis (string[] arguments) inline protected virtual
Runs action of the current object.
Parameters
arguments Command-line arguments of the action.
Implements IG.Lib.LoadableScriptBase.
Reimplemented in IG.Script.ScriptExtExamplesExt.
References IG.Lib.LoadableScriptBase.Script_DefaultRun().
Script_AddCommands() [1/2]
override void IG.Script.ScriptExtExamples.Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings) inline virtual
Adds commands to the internal interpreter.
Parameters
interpreter Interpreter where commands are executed.
helpStrings List containg help strings.
Reimplemented from IG.Lib.LoadableScriptBase.
Reimplemented in IG.Script.ScriptExtExamplesExt.
References IG.Script.ScriptExtExamples.ConstCustom, IG.Script.ScriptExtExamples.ConstGraphics3d, IG.Script.ScriptExtExamples.ConstHelpCustom, IG.Script.ScriptExtExamples.consthelpGraphics3d, IG.Script.ScriptExtExamples.ConstHelpPointClouts, IG.Script.ScriptExtExamples.ConstPointClouds, IG.Script.ScriptExtExamples.Custom(), IG.Script.ScriptExtExamples.Graphics3d(), IG.Script.ScriptExtExamples.NamedPipeClient(), IG.Script.ScriptExtExamples.NamedPipes(), IG.Script.ScriptExtExamples.NamedPipeServer(), IG.Script.ScriptExtExamples.PointClouds(), and IG.Lib.LoadableScriptBase.Script_AddCommand().
Custom() [1/2]
virtual string IG.Script.ScriptExtExamples.Custom (string[] arguments) inline virtual
Custom command.
Parameters
interpreter Interpreter where commands are executed.
helpStrings List containg help strings.
Reimplemented in IG.Script.ScriptExtExamplesExt.
Referenced by IG.Script.ScriptExtExamples.Script_AddCommands().
PointClouds() [1/2]
string IG.Script.ScriptExtExamples.PointClouds (string[] arguments) inline
Test action - to see that script is alive.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Lib.LoadableScriptBase.Script_PrintArguments().
Referenced by IG.Script.ScriptExtExamples.Script_AddCommands().
Graphics3d() [1/2]
string IG.Script.ScriptExtExamples.Graphics3d (string[] arguments) inline
Test action - to see that script is alive.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Gr3d.VtkPlotBase.ExampleCurvePlotTorusKnot(), and IG.Lib.LoadableScriptBase.Script_PrintArguments().
Referenced by IG.Script.ScriptExtExamples.Script_AddCommands().
NamedPipes()
string IG.Script.ScriptExtExamples.NamedPipes (string[] arguments) inline
Test action - named pipes.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Lib.Client, IG.Lib.LoadableScriptBase.Script_PrintArguments(), IG.Lib.Server, and IG.Lib.Util.SleepSeconds().
Referenced by IG.Script.ScriptExtExamples.Script_AddCommands().
NamedPipeClient()
string IG.Script.ScriptExtExamples.NamedPipeClient (string[] arguments) inline
Test action - named pipe client.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Lib.Client, and IG.Lib.LoadableScriptBase.Script_PrintArguments().
Referenced by IG.Script.ScriptExtExamples.Script_AddCommands().
NamedPipeServer()
string IG.Script.ScriptExtExamples.NamedPipeServer (string[] arguments) inline
Test action - named pipe server.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Lib.LoadableScriptBase.Script_PrintArguments(), and IG.Lib.Server.
Referenced by IG.Script.ScriptExtExamples.Script_AddCommands().
InitializeThis() [2/2]
override void IG.Script.ScriptExtExamples.InitializeThis (string[] arguments) inline protected virtual
Initializes the current object.
Implements IG.Lib.LoadableScriptBase.
Reimplemented in IG.Script.ScriptExtExamplesExt.
References IG.Lib.LoadableScriptBase.Script_DefaultInitialize().
RunThis() [2/2]
override string IG.Script.ScriptExtExamples.RunThis (string[] arguments) inline protected virtual
Runs action of the current object.
Parameters
arguments Command-line arguments of the action.
Implements IG.Lib.LoadableScriptBase.
Reimplemented in IG.Script.ScriptExtExamplesExt.
References IG.Lib.LoadableScriptBase.Script_DefaultRun().
Script_AddCommands() [2/2]
override void IG.Script.ScriptExtExamples.Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings) inline virtual
Adds commands to the internal interpreter.
Parameters
interpreter Interpreter where commands are executed.
helpStrings List containg help strings.
Reimplemented from IG.Lib.LoadableScriptBase.
Reimplemented in IG.Script.ScriptExtExamplesExt.
References IG.Script.ScriptExtExamples.ConstCustom, IG.Script.ScriptExtExamples.ConstGraphics3d, IG.Script.ScriptExtExamples.ConstHelpCustom, IG.Script.ScriptExtExamples.consthelpGraphics3d, IG.Script.ScriptExtExamples.ConstHelpPointClouts, IG.Script.ScriptExtExamples.ConstPointClouds, IG.Script.ScriptExtExamples.Custom(), IG.Script.ScriptExtExamples.Graphics3d(), IG.Script.ScriptExtExamples.PointClouds(), and IG.Lib.LoadableScriptBase.Script_AddCommand().
Custom() [2/2]
virtual string IG.Script.ScriptExtExamples.Custom (string[] arguments) inline virtual
Custom command.
Parameters
interpreter Interpreter where commands are executed.
helpStrings List containg help strings.
Reimplemented in IG.Script.ScriptExtExamplesExt.
PointClouds() [2/2]
string IG.Script.ScriptExtExamples.PointClouds (string[] arguments) inline
Test action - to see that script is alive.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Lib.LoadableScriptBase.Script_PrintArguments().
Graphics3d() [2/2]
string IG.Script.ScriptExtExamples.Graphics3d (string[] arguments) inline
Test action - to see that script is alive.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Gr3d.VtkPlotBase.ExampleCurvePlotTorusKnot(), and IG.Lib.LoadableScriptBase.Script_PrintArguments().
Member Data Documentation
ConstCustom
const string IG.Script.ScriptExtExamples.ConstCustom = "custom" static
Name of the command for custom test.
Referenced by IG.Script.ScriptExtExamples.Script_AddCommands().
ConstHelpCustom
const string IG.Script.ScriptExtExamples.ConstHelpCustom = "Performs a set of custom tests." static
Referenced by IG.Script.ScriptExtExamples.Script_AddCommands().
ConstPointClouds
const string IG.Script.ScriptExtExamples.ConstPointClouds = "pointclouds" static
Name of the command for testing point clouds utilities.
Referenced by IG.Script.ScriptExtExamples.Script_AddCommands(), IG.Test.ProgramTestIgor.TestMain(), and IG.Test.ProgramTestIgorIT.TestMain().
ConstHelpPointClouts
const string IG.Script.ScriptExtExamples.ConstHelpPointClouts = "Test of utilities for manipulating clouds of points." static
Referenced by IG.Script.ScriptExtExamples.Script_AddCommands().
ConstGraphics3d
const string IG.Script.ScriptExtExamples.ConstGraphics3d = "graphics3d" static
Name of the command for testing 3D graphics.
Referenced by IG.Script.ScriptExtExamples.Script_AddCommands(), IG.Test.ProgramTestIgor.TestMain(), and IG.Test.ProgramTestIgorIT.TestMain().
consthelpGraphics3d
const string IG.Script.ScriptExtExamples.consthelpGraphics3d = "Tests of 3D graphics." static
Referenced by IG.Script.ScriptExtExamples.Script_AddCommands().
The documentation for this class was generated from the following file:
shelldev/extensions/ExtShellIT/00testscriptsext/tests/ScriptExtExamples.cs