Doc: IGLib EXTENDED: alglib.linreg Class Reference
alglib.linreg Class Reference
Classes
class linearmodel
class lrreport
Static Public Member Functions
static void lrbuild (double[,] xy, int npoints, int nvars, ref int info, linearmodel lm, lrreport ar)
static void lrbuilds (double[,] xy, double[] s, int npoints, int nvars, ref int info, linearmodel lm, lrreport ar)
static void lrbuildzs (double[,] xy, double[] s, int npoints, int nvars, ref int info, linearmodel lm, lrreport ar)
static void lrbuildz (double[,] xy, int npoints, int nvars, ref int info, linearmodel lm, lrreport ar)
static void lrunpack (linearmodel lm, ref double[] v, ref int nvars)
static void lrpack (double[] v, int nvars, linearmodel lm)
static double lrprocess (linearmodel lm, double[] x)
static double lrrmserror (linearmodel lm, double[,] xy, int npoints)
static double lravgerror (linearmodel lm, double[,] xy, int npoints)
static double lravgrelerror (linearmodel lm, double[,] xy, int npoints)
static void lrcopy (linearmodel lm1, linearmodel lm2)
static void lrlines (double[,] xy, double[] s, int n, ref int info, ref double a, ref double b, ref double vara, ref double varb, ref double covab, ref double corrab, ref double p)
static void lrline (double[,] xy, int n, ref int info, ref double a, ref double b)
static void lrbuild (double[,] xy, int npoints, int nvars, ref int info, linearmodel lm, lrreport ar)
static void lrbuilds (double[,] xy, double[] s, int npoints, int nvars, ref int info, linearmodel lm, lrreport ar)
static void lrbuildzs (double[,] xy, double[] s, int npoints, int nvars, ref int info, linearmodel lm, lrreport ar)
static void lrbuildz (double[,] xy, int npoints, int nvars, ref int info, linearmodel lm, lrreport ar)
static void lrunpack (linearmodel lm, ref double[] v, ref int nvars)
static void lrpack (double[] v, int nvars, linearmodel lm)
static double lrprocess (linearmodel lm, double[] x)
static double lrrmserror (linearmodel lm, double[,] xy, int npoints)
static double lravgerror (linearmodel lm, double[,] xy, int npoints)
static double lravgrelerror (linearmodel lm, double[,] xy, int npoints)
static void lrcopy (linearmodel lm1, linearmodel lm2)
static void lrlines (double[,] xy, double[] s, int n, ref int info, ref double a, ref double b, ref double vara, ref double varb, ref double covab, ref double corrab, ref double p)
static void lrline (double[,] xy, int n, ref int info, ref double a, ref double b)
Static Public Attributes
const int lrvnum = 5
Static Private Member Functions
static void lrinternal (double[,] xy, double[] s, int npoints, int nvars, ref int info, linearmodel lm, lrreport ar)
static void lrinternal (double[,] xy, double[] s, int npoints, int nvars, ref int info, linearmodel lm, lrreport ar)
Member Function Documentation
lrbuild() [1/2]
static void alglib.linreg.lrbuild (double xy[,], int npoints, int nvars, ref int info, linearmodel lm, lrreport ar) inline static
References alglib.linreg.lrreport.c, alglib.linreg.lrbuilds(), alglib.linreg.lrreport.rmserror, and alglib.math.sqr().
Referenced by alglib.lrbuild(), alglib.testlinregunit.testlinreg(), and alglib.testlinregunit.unsetlr().
lrbuilds() [1/2]
static void alglib.linreg.lrbuilds (double xy[,], double[] s, int npoints, int nvars, ref int info, linearmodel lm, lrreport ar) inline static
References alglib.linreg.lrreport.c, alglib.linreg.lrinternal(), and alglib.basestat.samplemoments().
Referenced by alglib.linreg.lrbuild(), alglib.lrbuilds(), and alglib.testlinregunit.testlinreg().
lrbuildzs() [1/2]
static void alglib.linreg.lrbuildzs (double xy[,], double[] s, int npoints, int nvars, ref int info, linearmodel lm, lrreport ar) inline static
References alglib.linreg.lrreport.c, alglib.linreg.lrinternal(), and alglib.basestat.samplemoments().
Referenced by alglib.linreg.lrbuildz(), alglib.lrbuildzs(), and alglib.testlinregunit.testlinreg().
lrbuildz() [1/2]
static void alglib.linreg.lrbuildz (double xy[,], int npoints, int nvars, ref int info, linearmodel lm, lrreport ar) inline static
References alglib.linreg.lrreport.c, alglib.linreg.lrbuildzs(), alglib.linreg.lrreport.rmserror, and alglib.math.sqr().
Referenced by alglib.lrbuildz().
lrunpack() [1/2]
static void alglib.linreg.lrunpack (linearmodel lm, ref double[] v, ref int nvars) inline static
References alglib.ap.assert(), and alglib.linreg.lrvnum.
Referenced by alglib.lrunpack(), and alglib.testlinregunit.testlinreg().
lrpack() [1/2]
static void alglib.linreg.lrpack (double[] v, int nvars, linearmodel lm) inline static
References alglib.linreg.lrvnum.
Referenced by alglib.lrpack(), and alglib.testlinregunit.testlinreg().
lrprocess() [1/2]
static double alglib.linreg.lrprocess (linearmodel lm, double[] x) inline static
References alglib.ap.assert(), and alglib.linreg.lrvnum.
Referenced by alglib.lrprocess(), and alglib.testlinregunit.testlinreg().
lrrmserror() [1/2]
static double alglib.linreg.lrrmserror (linearmodel lm, double xy[,], int npoints) inline static
References alglib.ap.assert(), alglib.linreg.lrvnum, and alglib.math.sqr().
Referenced by alglib.linreg.lrinternal(), alglib.lrrmserror(), and alglib.testlinregunit.testlinreg().
lravgerror() [1/2]
static double alglib.linreg.lravgerror (linearmodel lm, double xy[,], int npoints) inline static
References alglib.ap.assert(), and alglib.linreg.lrvnum.
Referenced by alglib.lravgerror(), alglib.linreg.lrinternal(), and alglib.testlinregunit.testlinreg().
lravgrelerror() [1/2]
static double alglib.linreg.lravgrelerror (linearmodel lm, double xy[,], int npoints) inline static
References alglib.ap.assert(), and alglib.linreg.lrvnum.
Referenced by alglib.lravgrelerror(), alglib.linreg.lrinternal(), and alglib.testlinregunit.testlinreg().
lrcopy() [1/2]
static void alglib.linreg.lrcopy (linearmodel lm1, linearmodel lm2) inline static
References alglib.linreg.linearmodel.w.
Referenced by alglib.testlinregunit.testlinreg().
lrlines() [1/2]
static void alglib.linreg.lrlines (double xy[,], double[] s, int n, ref int info, ref double a, ref double b, ref double vara, ref double varb, ref double covab, ref double corrab, ref double p) inline static
References alglib.igammaf.incompletegammac(), alglib.math.machineepsilon, and alglib.math.sqr().
Referenced by alglib.filters.filterlrma(), alglib.linreg.lrline(), and alglib.testlinregunit.testlinreg().
lrline() [1/2]
static void alglib.linreg.lrline (double xy[,], int n, ref int info, ref double a, ref double b) inline static
References alglib.linreg.lrlines().
Referenced by alglib.testlinregunit.testlinreg().
lrinternal() [1/2]
static void alglib.linreg.lrinternal (double xy[,], double[] s, int npoints, int nvars, ref int info, linearmodel lm, lrreport ar) inline static private
References alglib.linreg.lrreport.avgerror, alglib.linreg.lrreport.avgrelerror, alglib.linreg.lrreport.c, alglib.linreg.lrreport.cvavgerror, alglib.linreg.lrreport.cvavgrelerror, alglib.linreg.lrreport.cvdefects, alglib.linreg.lrreport.cvrmserror, alglib.linreg.lravgerror(), alglib.linreg.lravgrelerror(), alglib.linreg.lrrmserror(), alglib.linreg.lrvnum, alglib.math.machineepsilon, alglib.blas.matrixmatrixmultiply(), alglib.linreg.lrreport.ncvdefects, alglib.svd.rmatrixsvd(), alglib.linreg.lrreport.rmserror, alglib.math.sqr(), and alglib.linreg.linearmodel.w.
Referenced by alglib.linreg.lrbuilds(), and alglib.linreg.lrbuildzs().
lrbuild() [2/2]
static void alglib.linreg.lrbuild (double xy[,], int npoints, int nvars, ref int info, linearmodel lm, lrreport ar) inline static
lrbuilds() [2/2]
static void alglib.linreg.lrbuilds (double xy[,], double[] s, int npoints, int nvars, ref int info, linearmodel lm, lrreport ar) inline static
lrbuildzs() [2/2]
static void alglib.linreg.lrbuildzs (double xy[,], double[] s, int npoints, int nvars, ref int info, linearmodel lm, lrreport ar) inline static
lrbuildz() [2/2]
static void alglib.linreg.lrbuildz (double xy[,], int npoints, int nvars, ref int info, linearmodel lm, lrreport ar) inline static
lrunpack() [2/2]
static void alglib.linreg.lrunpack (linearmodel lm, ref double[] v, ref int nvars) inline static
lrpack() [2/2]
static void alglib.linreg.lrpack (double[] v, int nvars, linearmodel lm) inline static
lrprocess() [2/2]
static double alglib.linreg.lrprocess (linearmodel lm, double[] x) inline static
lrrmserror() [2/2]
static double alglib.linreg.lrrmserror (linearmodel lm, double xy[,], int npoints) inline static
lravgerror() [2/2]
static double alglib.linreg.lravgerror (linearmodel lm, double xy[,], int npoints) inline static
lravgrelerror() [2/2]
static double alglib.linreg.lravgrelerror (linearmodel lm, double xy[,], int npoints) inline static
lrcopy() [2/2]
static void alglib.linreg.lrcopy (linearmodel lm1, linearmodel lm2) inline static
lrlines() [2/2]
static void alglib.linreg.lrlines (double xy[,], double[] s, int n, ref int info, ref double a, ref double b, ref double vara, ref double varb, ref double covab, ref double corrab, ref double p) inline static
lrline() [2/2]
static void alglib.linreg.lrline (double xy[,], int n, ref int info, ref double a, ref double b) inline static
lrinternal() [2/2]
static void alglib.linreg.lrinternal (double xy[,], double[] s, int npoints, int nvars, ref int info, linearmodel lm, lrreport ar) inline static private
Member Data Documentation
lrvnum
const int alglib.linreg.lrvnum = 5 static
Referenced by alglib.linreg.lravgerror(), alglib.linreg.lravgrelerror(), alglib.linreg.lrinternal(), alglib.linreg.lrpack(), alglib.linreg.lrprocess(), alglib.linreg.lrrmserror(), and alglib.linreg.lrunpack().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/dataanalysis.cs