Doc: IGLib EXTENDED: NUnit.Framework.Internal.Tests.StackFilterTests Class Reference
NUnit.Framework.Internal.Tests.StackFilterTests Class Reference
Public Member Functions
void FilterShortTraceWithAssert ()
void FilterShortTraceWithAssume_Trace1 ()
void FilterLongTrace ()
Static Private Attributes
static readonly string NL = NUnit.Env.NewLine
static readonly string shortTrace_Assert
static readonly string shortTrace_Assume
static readonly string shortTrace_Result
static readonly string longTrace
static readonly string longTrace_Result
Member Function Documentation
FilterShortTraceWithAssert()
void NUnit.Framework.Internal.Tests.StackFilterTests.FilterShortTraceWithAssert () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.StackFilter.Filter(), NUnit.Framework.Internal.Tests.StackFilterTests.shortTrace_Assert, NUnit.Framework.Internal.Tests.StackFilterTests.shortTrace_Result, and NUnit.Framework.Assert.That().
FilterShortTraceWithAssume_Trace1()
void NUnit.Framework.Internal.Tests.StackFilterTests.FilterShortTraceWithAssume_Trace1 () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.StackFilter.Filter(), NUnit.Framework.Internal.Tests.StackFilterTests.shortTrace_Assume, NUnit.Framework.Internal.Tests.StackFilterTests.shortTrace_Result, and NUnit.Framework.Assert.That().
FilterLongTrace()
void NUnit.Framework.Internal.Tests.StackFilterTests.FilterLongTrace () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.StackFilter.Filter(), NUnit.Framework.Internal.Tests.StackFilterTests.longTrace, NUnit.Framework.Internal.Tests.StackFilterTests.longTrace_Result, and NUnit.Framework.Assert.That().
Member Data Documentation
NL
readonly string NUnit.Framework.Internal.Tests.StackFilterTests.NL = NUnit.Env.NewLine static private
shortTrace_Assert
readonly string NUnit.Framework.Internal.Tests.StackFilterTests.shortTrace_Assert static private
Initial value:
=
    @"   at NUnit.Framework.Assert.Fail(String message) in D:\Dev\NUnitLite\NUnitLite\Framework\Assert.cs:line 56" + NL +
    @"   at NUnit.Framework.Assert.That(String label, Object actual, Matcher expectation, String message) in D:\Dev\NUnitLite\NUnitLite\Framework\Assert.cs:line 50" + NL +
    @"   at NUnit.Framework.Assert.That(Object actual, Matcher expectation) in D:\Dev\NUnitLite\NUnitLite\Framework\Assert.cs:line 19" + NL +
    @"   at NUnit.Tests.GreaterThanMatcherTest.MatchesGoodValue() in D:\Dev\NUnitLite\NUnitLiteTests\GreaterThanMatcherTest.cs:line 12" + NL
Referenced by NUnit.Framework.Internal.Tests.StackFilterTests.FilterShortTraceWithAssert().
shortTrace_Assume
readonly string NUnit.Framework.Internal.Tests.StackFilterTests.shortTrace_Assume static private
Initial value:
=
    @"   at NUnit.Framework.Assert.Fail(String message) in D:\Dev\NUnitLite\NUnitLite\Framework\Assert.cs:line 56" + NL +
    @"   at NUnit.Framework.Assume.That(String label, Object actual, Matcher expectation, String message) in D:\Dev\NUnitLite\NUnitLite\Framework\Assert.cs:line 50" + NL +
    @"   at NUnit.Framework.Assume.That(Object actual, Matcher expectation) in D:\Dev\NUnitLite\NUnitLite\Framework\Assert.cs:line 19" + NL +
    @"   at NUnit.Tests.GreaterThanMatcherTest.MatchesGoodValue() in D:\Dev\NUnitLite\NUnitLiteTests\GreaterThanMatcherTest.cs:line 12" + NL
Referenced by NUnit.Framework.Internal.Tests.StackFilterTests.FilterShortTraceWithAssume_Trace1().
shortTrace_Result
readonly string NUnit.Framework.Internal.Tests.StackFilterTests.shortTrace_Result static private
Initial value:
=
    @"at NUnit.Tests.GreaterThanMatcherTest.MatchesGoodValue() in D:\Dev\NUnitLite\NUnitLiteTests\GreaterThanMatcherTest.cs:line 12" + NL
Referenced by NUnit.Framework.Internal.Tests.StackFilterTests.FilterShortTraceWithAssert(), and NUnit.Framework.Internal.Tests.StackFilterTests.FilterShortTraceWithAssume_Trace1().
longTrace
readonly string NUnit.Framework.Internal.Tests.StackFilterTests.longTrace static private
Initial value:
=
    @"  at NUnit.Framework.Assert.Fail(String message, Object[] args)" + NL +
    @"  at MyNamespace.MyAppsTests.AssertFailTest()" + NL +
    @"  at System.Reflection.RuntimeMethodInfo.InternalInvoke(RuntimeMethodInfo rtmi, Object obj, BindingFlags invokeAttr, Binder binder, Object parameters, CultureInfo culture, Boolean isBinderDefault, Assembly caller, Boolean verifyAccess, StackCrawlMark& stackMark)" + NL +
    @"  at System.Reflection.RuntimeMethodInfo.InternalInvoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean verifyAccess, StackCrawlMark& stackMark)" + NL +
    @"  at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)" + NL +
    @"  at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)" + NL +
    @"  at NUnitLite.ProxyTestCase.InvokeMethod(MethodInfo method, Object[] args)" + NL +
    @"  at NUnit.Framework.TestCase.RunTest()" + NL +
    @"  at NUnit.Framework.TestCase.RunBare()" + NL +
    @"  at NUnit.Framework.TestCase.Run(TestResult result, TestListener listener)" + NL +
    @"  at NUnit.Framework.TestCase.Run(TestListener listener)" + NL +
    @"  at NUnit.Framework.TestSuite.Run(TestListener listener)" + NL +
    @"  at NUnit.Framework.TestSuite.Run(TestListener listener)" + NL +
    @"  at NUnitLite.Runner.TestRunner.Run(ITest test)" + NL +
    @"  at NUnitLite.Runner.ConsoleUI.Run(ITest test)" + NL +
    @"  at NUnitLite.Runner.TestRunner.Run(Assembly assembly)" + NL +
    @"  at NUnitLite.Runner.ConsoleUI.Run()" + NL +
    @"  at NUnitLite.Runner.ConsoleUI.Main(String[] args)" + NL +
    @"  at OpenNETCF.Linq.Demo.Program.Main(String[] args)" + NL
Referenced by NUnit.Framework.Internal.Tests.StackFilterTests.FilterLongTrace().
longTrace_Result
readonly string NUnit.Framework.Internal.Tests.StackFilterTests.longTrace_Result static private
Initial value:
=
    @"at MyNamespace.MyAppsTests.AssertFailTest()" + NL
Referenced by NUnit.Framework.Internal.Tests.StackFilterTests.FilterLongTrace().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/StackFilterTests.cs