Doc: IGLib EXTENDED: IG.Forms.SoundPlayerFormSimple Class Reference
IG.Forms.SoundPlayerFormSimple Class Reference
Public Member Functions
SoundPlayerFormSimple ()
SoundPlayerFormSimple ()
SoundPlayerFormSimple ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
SoundPlayerControlSimple soundPlayerControl
Constructor & Destructor Documentation
SoundPlayerFormSimple() [1/3]
IG.Forms.SoundPlayerFormSimple.SoundPlayerFormSimple () inline
References IG.Forms.SoundPlayerFormSimple.InitializeComponent().
SoundPlayerFormSimple() [2/3]
IG.Forms.SoundPlayerFormSimple.SoundPlayerFormSimple () inline
References IG.Forms.SoundPlayerFormSimple.InitializeComponent().
SoundPlayerFormSimple() [3/3]
IG.Forms.SoundPlayerFormSimple.SoundPlayerFormSimple () inline
References IG.Forms.SoundPlayerFormSimple.InitializeComponent().
Member Function Documentation
Dispose() [1/3]
override void IG.Forms.SoundPlayerFormSimple.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.SoundPlayerFormSimple.components.
InitializeComponent() [1/3]
void IG.Forms.SoundPlayerFormSimple.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.SoundPlayerFormSimple.soundPlayerControl.
Referenced by IG.Forms.SoundPlayerFormSimple.SoundPlayerFormSimple().
Dispose() [2/3]
override void IG.Forms.SoundPlayerFormSimple.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.SoundPlayerFormSimple.components.
InitializeComponent() [2/3]
void IG.Forms.SoundPlayerFormSimple.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.SoundPlayerFormSimple.soundPlayerControl.
Dispose() [3/3]
override void IG.Forms.SoundPlayerFormSimple.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.SoundPlayerFormSimple.components.
InitializeComponent() [3/3]
void IG.Forms.SoundPlayerFormSimple.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.SoundPlayerFormSimple.soundPlayerControl.
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.SoundPlayerFormSimple.components = null private
Required designer variable.
Referenced by IG.Forms.SoundPlayerFormSimple.Dispose().
soundPlayerControl
SoundPlayerControlSimple IG.Forms.SoundPlayerFormSimple.soundPlayerControl private
Referenced by IG.Forms.SoundPlayerFormSimple.InitializeComponent().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/Viewers/SoundPlayerFormSimple.cs
iglib/igforms/Utilities/Viewers/SoundPlayerFormSimple.Designer.cs