Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAIC1 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAIC1 Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAIC1 (DDOT ddot, DLAMCH dlamch)
DLAIC1 ()
void Run (int JOB, int J, double[] X, int offset_x, double SEST, double[] W, int offset_w, double GAMMA, ref double SESTPR, ref double S, ref double C)
Private Attributes
DDOT _ddot
DLAMCH _dlamch
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
const double TWO = 2.0E0
const double HALF = 0.5E0
const double FOUR = 4.0E0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAIC1 applies one step of incremental condition estimation in its simplest version:
Let x, twonorm(x) = 1, be an approximate singular vector of an j-by-j lower triangular matrix L, such that twonorm(L*x) = sest Then DLAIC1 computes sestpr, s, c such that the vector [ s*x ] xhat = [ c ] is an approximate singular vector of [ L 0 ] Lhat = [ w' gamma ] in the sense that twonorm(Lhat*xhat) = sestpr.
Depending on JOB, an estimate for the largest or smallest singular value is computed.
Note that [s c]' and sestpr**2 is an eigenpair of the system
diag(sest*sest, 0) + [alpha gamma] * [ alpha ] [ gamma ]
where alpha = x'*w.
/summary>
Constructor & Destructor Documentation
DLAIC1() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAIC1.DLAIC1 (DDOT ddot, DLAMCH dlamch) inline
DLAIC1() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAIC1.DLAIC1 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAIC1.Run (int JOB, int J, double[] X, int offset_x, double SEST, double[] W, int offset_w, double GAMMA, ref double SESTPR, ref double S, ref double C) inline
Purpose
DLAIC1 applies one step of incremental condition estimation in its simplest version:
Let x, twonorm(x) = 1, be an approximate singular vector of an j-by-j lower triangular matrix L, such that twonorm(L*x) = sest Then DLAIC1 computes sestpr, s, c such that the vector [ s*x ] xhat = [ c ] is an approximate singular vector of [ L 0 ] Lhat = [ w' gamma ] in the sense that twonorm(Lhat*xhat) = sestpr.
Depending on JOB, an estimate for the largest or smallest singular value is computed.
Note that [s c]' and sestpr**2 is an eigenpair of the system
diag(sest*sest, 0) + [alpha gamma] * [ alpha ] [ gamma ]
where alpha = x'*w.
/summary>
Parameters
JOB (input) INTEGER = 1: an estimate for the largest singular value is computed. = 2: an estimate for the smallest singular value is computed. /param>
Parameters
J (input) INTEGER Length of X and W /param>
Parameters
X (input) DOUBLE PRECISION array, dimension (J) The j-vector x. /param>
Parameters
SEST (input) DOUBLE PRECISION Estimated singular value of j by j matrix L /param>
Parameters
W (input) DOUBLE PRECISION array, dimension (J) The j-vector w. /param>
Parameters
GAMMA (input) DOUBLE PRECISION The diagonal element gamma. /param>
Parameters
SESTPR (output) DOUBLE PRECISION Estimated singular value of (j+1) by (j+1) matrix Lhat. /param>
Parameters
S (output) DOUBLE PRECISION Sine needed in forming xhat. /param>
Parameters
C (output) DOUBLE PRECISION Cosine needed in forming xhat. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLAIC1.FOUR, DotNumerics.LinearAlgebra.CSLapack.DLAIC1.HALF, DotNumerics.LinearAlgebra.CSLapack.DLAIC1.ONE, DotNumerics.LinearAlgebra.CSLapack.DDOT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.FortranLibrary.FortranLib.Sign(), TEST, DotNumerics.LinearAlgebra.CSLapack.DLAIC1.TWO, and DotNumerics.LinearAlgebra.CSLapack.DLAIC1.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGELSY.Run().
Member Data Documentation
_ddot
DDOT DotNumerics.LinearAlgebra.CSLapack.DLAIC1._ddot private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLAIC1._dlamch private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAIC1.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAIC1.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAIC1.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAIC1.Run().
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DLAIC1.TWO = 2.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAIC1.Run().
HALF
const double DotNumerics.LinearAlgebra.CSLapack.DLAIC1.HALF = 0.5E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAIC1.Run().
FOUR
const double DotNumerics.LinearAlgebra.CSLapack.DLAIC1.FOUR = 4.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAIC1.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlaic1.cs