Doc: IGLib EXTENDED: AForge.Neuro.Learning.BackPropagationLearning Class Reference
AForge.Neuro.Learning.BackPropagationLearning Class Reference
Back propagation learning algorithm
Public Member Functions
BackPropagationLearning (ActivationNetwork network)
Initializes a new instance of the BackPropagationLearning class
double Run (double[] input, double[] output)
Runs learning iteration
double RunEpoch (double[][] input, double[][] output)
Runs learning epoch
BackPropagationLearning (ActivationNetwork network)
Initializes a new instance of the BackPropagationLearning class
double Run (double[] input, double[] output)
Runs learning iteration
double RunEpoch (double[][] input, double[][] output)
Runs learning epoch
BackPropagationLearning (ActivationNetwork network)
Initializes a new instance of the BackPropagationLearning class.
double Run (double[] input, double[] output)
Runs learning iteration.
double RunEpoch (double[][] input, double[][] output)
Runs learning epoch.
Properties
double LearningRate [get, set]
Learning rate
double Momentum [get, set]
Momentum
Private Member Functions
double CalculateError (double[] desiredOutput)
Calculates error values for all neurons of the network
void CalculateUpdates (double[] input)
Calculate weights updates
void UpdateNetwork ()
Update network'sweights
double CalculateError (double[] desiredOutput)
Calculates error values for all neurons of the network
void CalculateUpdates (double[] input)
Calculate weights updates
void UpdateNetwork ()
Update network'sweights
double CalculateError (double[] desiredOutput)
Calculates error values for all neurons of the network.
void CalculateUpdates (double[] input)
Calculate weights updates.
void UpdateNetwork ()
Update network'sweights.
Private Attributes
ActivationNetwork network
double learningRate = 0.1
double momentum = 0.0
double[][] neuronErrors = null
double[][][] weightsUpdates = null
double[][] thresholdsUpdates = null
Detailed Description
Back propagation learning algorithm
Back propagation learning algorithm.
The class implements back propagation learning algorithm, which is widely used for training multi-layer neural networks with continuous activation functions.
The class implements back propagation learning algorithm, which is widely used for training multi-layer neural networks with continuous activation functions.
Sample usage (training network to calculate XOR function):
// initialize input and output values
double[][] input = new double[4][] {
    new double[] {0, 0}, new double[] {0, 1},
    new double[] {1, 0}, new double[] {1, 1}
};
double[][] output = new double[4][] {
    new double[] {0}, new double[] {1},
    new double[] {1}, new double[] {0}
};
// create neural network
ActivationNetwork   network = new ActivationNetwork(
    SigmoidFunction( 2 ),
    2, // two inputs in the network
    2, // two neurons in the first layer
    1 ); // one neuron in the second layer
// create teacher
BackPropagationLearning teacher = new BackPropagationLearning(network);
// loop
while (!needToStop)
{
    // run epoch of learning procedure
    double error = teacher.RunEpoch( input, output );
    // check error value to see if we need to stop
    // ...
}
See also
EvolutionaryLearning
Constructor & Destructor Documentation
BackPropagationLearning() [1/3]
AForge.Neuro.Learning.BackPropagationLearning.BackPropagationLearning (ActivationNetwork network) inline
Initializes a new instance of the BackPropagationLearning class
Parameters
network Network to teach
References AForge.Neuro.Layer.InputsCount, AForge.Neuro.Network.LayersCount, AForge.Neuro.Learning.BackPropagationLearning.network, AForge.Neuro.Learning.BackPropagationLearning.neuronErrors, AForge.Neuro.Layer.NeuronsCount, AForge.Neuro.Learning.BackPropagationLearning.thresholdsUpdates, and AForge.Neuro.Learning.BackPropagationLearning.weightsUpdates.
BackPropagationLearning() [2/3]
AForge.Neuro.Learning.BackPropagationLearning.BackPropagationLearning (ActivationNetwork network) inline
Initializes a new instance of the BackPropagationLearning class
Parameters
network Network to teach
References AForge.Neuro.Layer.InputsCount, AForge.Neuro.Network.LayersCount, AForge.Neuro.Learning.BackPropagationLearning.network, AForge.Neuro.Learning.BackPropagationLearning.neuronErrors, AForge.Neuro.Layer.NeuronsCount, AForge.Neuro.Learning.BackPropagationLearning.thresholdsUpdates, and AForge.Neuro.Learning.BackPropagationLearning.weightsUpdates.
BackPropagationLearning() [3/3]
AForge.Neuro.Learning.BackPropagationLearning.BackPropagationLearning (ActivationNetwork network) inline
Initializes a new instance of the BackPropagationLearning class.
Parameters
network Network to teach.
References AForge.Neuro.Layer.InputsCount, AForge.Neuro.Network.Layers, AForge.Neuro.Learning.BackPropagationLearning.network, AForge.Neuro.Learning.BackPropagationLearning.neuronErrors, AForge.Neuro.Layer.Neurons, AForge.Neuro.Learning.BackPropagationLearning.thresholdsUpdates, and AForge.Neuro.Learning.BackPropagationLearning.weightsUpdates.
Member Function Documentation
Run() [1/3]
double AForge.Neuro.Learning.BackPropagationLearning.Run (double[] input, double[] output) inline
Runs learning iteration
Parameters
input input vector
output desired output vector
Returns
Returns squared error of the last layer divided by 2
Runs one learning iteration and updates neuron's weights.
Implements AForge.Neuro.Learning.ISupervisedLearning.
References AForge.Neuro.Learning.BackPropagationLearning.CalculateError(), AForge.Neuro.Learning.BackPropagationLearning.CalculateUpdates(), AForge.Neuro.Network.Compute(), AForge.Neuro.Learning.BackPropagationLearning.network, and AForge.Neuro.Learning.BackPropagationLearning.UpdateNetwork().
Referenced by AForge.Neuro.Learning.BackPropagationLearning.RunEpoch().
RunEpoch() [1/3]
double AForge.Neuro.Learning.BackPropagationLearning.RunEpoch (double input[][], double output[][]) inline
Runs learning epoch
Parameters
input array of input vectors
output array of output vectors
Returns
Returns sum of squared errors of the last layer divided by 2
Runs series of learning iterations - one iteration for each input sample. Updates neuron's weights after each sample presented.
Implements AForge.Neuro.Learning.ISupervisedLearning.
References AForge.Neuro.Learning.BackPropagationLearning.Run().
Referenced by XORProblem.MainForm.SearchSolution(), Approximation.MainForm.SearchSolution(), Approximation.MainFormNeuralApproximation.SearchSolution(), TimeSeries.MainForm.SearchSolution(), and IG.Neural.NeuralApproximatorAforge.TrainNetworkSpecific().
CalculateError() [1/3]
double AForge.Neuro.Learning.BackPropagationLearning.CalculateError (double[] desiredOutput) inline private
Calculates error values for all neurons of the network
Parameters
desiredOutput Desired output vector
Returns
Returns summary squared error of the last layer divided by 2
References AForge.Neuro.Network.LayersCount, AForge.Neuro.Learning.BackPropagationLearning.network, AForge.Neuro.Learning.BackPropagationLearning.neuronErrors, AForge.Neuro.Layer.NeuronsCount, and AForge.Neuro.Layer.Output.
Referenced by AForge.Neuro.Learning.BackPropagationLearning.Run().
CalculateUpdates() [1/3]
void AForge.Neuro.Learning.BackPropagationLearning.CalculateUpdates (double[] input) inline private
Calculate weights updates
Parameters
input Network's input vector
References AForge.Neuro.Neuron.InputsCount, AForge.Neuro.Network.LayersCount, AForge.Neuro.Learning.BackPropagationLearning.learningRate, AForge.Neuro.Learning.BackPropagationLearning.momentum, AForge.Neuro.Learning.BackPropagationLearning.network, AForge.Neuro.Learning.BackPropagationLearning.neuronErrors, AForge.Neuro.Layer.NeuronsCount, AForge.Neuro.Learning.BackPropagationLearning.thresholdsUpdates, and AForge.Neuro.Learning.BackPropagationLearning.weightsUpdates.
Referenced by AForge.Neuro.Learning.BackPropagationLearning.Run().
UpdateNetwork() [1/3]
void AForge.Neuro.Learning.BackPropagationLearning.UpdateNetwork () inline private
Update network'sweights
References AForge.Neuro.Neuron.InputsCount, AForge.Neuro.Network.LayersCount, AForge.Neuro.Learning.BackPropagationLearning.network, AForge.Neuro.Layer.NeuronsCount, AForge.Neuro.ActivationNeuron.Threshold, AForge.Neuro.Learning.BackPropagationLearning.thresholdsUpdates, and AForge.Neuro.Learning.BackPropagationLearning.weightsUpdates.
Referenced by AForge.Neuro.Learning.BackPropagationLearning.Run().
Run() [2/3]
double AForge.Neuro.Learning.BackPropagationLearning.Run (double[] input, double[] output) inline
Runs learning iteration
Parameters
input input vector
output desired output vector
Returns
Returns squared error of the last layer divided by 2
Runs one learning iteration and updates neuron's weights.
Implements AForge.Neuro.Learning.ISupervisedLearning.
References AForge.Neuro.Learning.BackPropagationLearning.CalculateError(), AForge.Neuro.Learning.BackPropagationLearning.CalculateUpdates(), AForge.Neuro.Network.Compute(), AForge.Neuro.Learning.BackPropagationLearning.network, and AForge.Neuro.Learning.BackPropagationLearning.UpdateNetwork().
RunEpoch() [2/3]
double AForge.Neuro.Learning.BackPropagationLearning.RunEpoch (double input[][], double output[][]) inline
Runs learning epoch
Parameters
input array of input vectors
output array of output vectors
Returns
Returns sum of squared errors of the last layer divided by 2
Runs series of learning iterations - one iteration for each input sample. Updates neuron's weights after each sample presented.
Implements AForge.Neuro.Learning.ISupervisedLearning.
References AForge.Neuro.Learning.BackPropagationLearning.Run().
CalculateError() [2/3]
double AForge.Neuro.Learning.BackPropagationLearning.CalculateError (double[] desiredOutput) inline private
Calculates error values for all neurons of the network
Parameters
desiredOutput Desired output vector
Returns
Returns summary squared error of the last layer divided by 2
References AForge.Neuro.Network.LayersCount, AForge.Neuro.Learning.BackPropagationLearning.network, AForge.Neuro.Learning.BackPropagationLearning.neuronErrors, AForge.Neuro.Layer.NeuronsCount, and AForge.Neuro.Layer.Output.
CalculateUpdates() [2/3]
void AForge.Neuro.Learning.BackPropagationLearning.CalculateUpdates (double[] input) inline private
Calculate weights updates
Parameters
input Network's input vector
References AForge.Neuro.Neuron.InputsCount, AForge.Neuro.Network.LayersCount, AForge.Neuro.Learning.BackPropagationLearning.learningRate, AForge.Neuro.Learning.BackPropagationLearning.momentum, AForge.Neuro.Learning.BackPropagationLearning.network, AForge.Neuro.Learning.BackPropagationLearning.neuronErrors, AForge.Neuro.Layer.NeuronsCount, AForge.Neuro.Learning.BackPropagationLearning.thresholdsUpdates, and AForge.Neuro.Learning.BackPropagationLearning.weightsUpdates.
UpdateNetwork() [2/3]
void AForge.Neuro.Learning.BackPropagationLearning.UpdateNetwork () inline private
Update network'sweights
References AForge.Neuro.Neuron.InputsCount, AForge.Neuro.Network.LayersCount, AForge.Neuro.Learning.BackPropagationLearning.network, AForge.Neuro.Layer.NeuronsCount, AForge.Neuro.ActivationNeuron.Threshold, AForge.Neuro.Learning.BackPropagationLearning.thresholdsUpdates, and AForge.Neuro.Learning.BackPropagationLearning.weightsUpdates.
Run() [3/3]
double AForge.Neuro.Learning.BackPropagationLearning.Run (double[] input, double[] output) inline
Runs learning iteration.
Parameters
input Input vector.
output Desired output vector.
Returns
Returns squared error (difference between current network's output and desired output) divided by 2.
Runs one learning iteration and updates neuron's weights.
Implements AForge.Neuro.Learning.ISupervisedLearning.
References AForge.Neuro.Learning.BackPropagationLearning.CalculateError(), AForge.Neuro.Learning.BackPropagationLearning.CalculateUpdates(), AForge.Neuro.Network.Compute(), AForge.Neuro.Learning.BackPropagationLearning.network, and AForge.Neuro.Learning.BackPropagationLearning.UpdateNetwork().
RunEpoch() [3/3]
double AForge.Neuro.Learning.BackPropagationLearning.RunEpoch (double input[][], double output[][]) inline
Runs learning epoch.
Parameters
input Array of input vectors.
output Array of output vectors.
Returns
Returns summary learning error for the epoch. See Run method for details about learning error calculation.
The method runs one learning epoch, by calling Run method for each vector provided in the input array.
Implements AForge.Neuro.Learning.ISupervisedLearning.
References AForge.Neuro.Learning.BackPropagationLearning.Run().
CalculateError() [3/3]
double AForge.Neuro.Learning.BackPropagationLearning.CalculateError (double[] desiredOutput) inline private
Calculates error values for all neurons of the network.
Parameters
desiredOutput Desired output vector.
Returns
Returns summary squared error of the last layer divided by 2.
References AForge.Neuro.Network.Layers, AForge.Neuro.Learning.BackPropagationLearning.network, AForge.Neuro.Learning.BackPropagationLearning.neuronErrors, AForge.Neuro.Layer.Neurons, AForge.Neuro.Neuron.Output, and AForge.Neuro.Neuron.Weights.
CalculateUpdates() [3/3]
void AForge.Neuro.Learning.BackPropagationLearning.CalculateUpdates (double[] input) inline private
Calculate weights updates.
Parameters
input Network's input vector.
References AForge.Neuro.Network.Layers, AForge.Neuro.Learning.BackPropagationLearning.learningRate, AForge.Neuro.Learning.BackPropagationLearning.momentum, AForge.Neuro.Learning.BackPropagationLearning.network, AForge.Neuro.Learning.BackPropagationLearning.neuronErrors, AForge.Neuro.Layer.Neurons, AForge.Neuro.Neuron.Output, AForge.Neuro.Learning.BackPropagationLearning.thresholdsUpdates, and AForge.Neuro.Learning.BackPropagationLearning.weightsUpdates.
UpdateNetwork() [3/3]
void AForge.Neuro.Learning.BackPropagationLearning.UpdateNetwork () inline private
Update network'sweights.
References AForge.Neuro.Network.Layers, AForge.Neuro.Learning.BackPropagationLearning.network, AForge.Neuro.Layer.Neurons, AForge.Neuro.ActivationNeuron.Threshold, AForge.Neuro.Learning.BackPropagationLearning.thresholdsUpdates, AForge.Neuro.Neuron.Weights, and AForge.Neuro.Learning.BackPropagationLearning.weightsUpdates.
Member Data Documentation
network
ActivationNetwork AForge.Neuro.Learning.BackPropagationLearning.network private
Referenced by AForge.Neuro.Learning.BackPropagationLearning.BackPropagationLearning(), AForge.Neuro.Learning.BackPropagationLearning.CalculateError(), AForge.Neuro.Learning.BackPropagationLearning.CalculateUpdates(), AForge.Neuro.Learning.BackPropagationLearning.Run(), and AForge.Neuro.Learning.BackPropagationLearning.UpdateNetwork().
learningRate
double AForge.Neuro.Learning.BackPropagationLearning.learningRate = 0.1 private
Referenced by AForge.Neuro.Learning.BackPropagationLearning.CalculateUpdates().
momentum
double AForge.Neuro.Learning.BackPropagationLearning.momentum = 0.0 private
Referenced by AForge.Neuro.Learning.BackPropagationLearning.CalculateUpdates().
neuronErrors
double [][] AForge.Neuro.Learning.BackPropagationLearning.neuronErrors = null private
Referenced by AForge.Neuro.Learning.BackPropagationLearning.BackPropagationLearning(), AForge.Neuro.Learning.BackPropagationLearning.CalculateError(), and AForge.Neuro.Learning.BackPropagationLearning.CalculateUpdates().
weightsUpdates
double [][][] AForge.Neuro.Learning.BackPropagationLearning.weightsUpdates = null private
Referenced by AForge.Neuro.Learning.BackPropagationLearning.BackPropagationLearning(), AForge.Neuro.Learning.BackPropagationLearning.CalculateUpdates(), and AForge.Neuro.Learning.BackPropagationLearning.UpdateNetwork().
thresholdsUpdates
double [][] AForge.Neuro.Learning.BackPropagationLearning.thresholdsUpdates = null private
Referenced by AForge.Neuro.Learning.BackPropagationLearning.BackPropagationLearning(), AForge.Neuro.Learning.BackPropagationLearning.CalculateUpdates(), and AForge.Neuro.Learning.BackPropagationLearning.UpdateNetwork().
Property Documentation
LearningRate
double AForge.Neuro.Learning.BackPropagationLearning.LearningRate get set
Learning rate
Learning rate, [0, 1].
The value determines speed of learning. Default value equals to 0.1.
The value determines speed of learning.
Default value equals to 0.1.
Referenced by IG.Neural.NeuralApproximatorAforge.CreateNetwork(), XORProblem.MainForm.SearchSolution(), Approximation.MainForm.SearchSolution(), Approximation.MainFormNeuralApproximation.SearchSolution(), and TimeSeries.MainForm.SearchSolution().
Momentum
double AForge.Neuro.Learning.BackPropagationLearning.Momentum get set
Momentum
Momentum, [0, 1].
The value determines the portion of previous weight's update to use on current iteration. Weight's update values are calculated on each iteration depending on neuron's error. The momentum specifies the amount of update to use from previous iteration and the amount of update to use from current iteration. If the value is equal to 0.1, for example, then 0.1 portion of previous update and 0.9 portion of current update are used to update weight's value.
Default value equals to 0.0.
The value determines the portion of previous weight's update to use on current iteration. Weight's update values are calculated on each iteration depending on neuron's error. The momentum specifies the amount of update to use from previous iteration and the amount of update to use from current iteration. If the value is equal to 0.1, for example, then 0.1 portion of previous update and 0.9 portion of current update are used to update weight's value.
Default value equals to 0.0.
Referenced by IG.Neural.NeuralApproximatorAforge.CreateNetwork(), XORProblem.MainForm.SearchSolution(), Approximation.MainForm.SearchSolution(), Approximation.MainFormNeuralApproximation.SearchSolution(), and TimeSeries.MainForm.SearchSolution().
The documentation for this class was generated from the following file:
shelldev/lib/external/neuralnetworks/neuro_src/Sources/Backup/Neuro/Learning/BackPropagationLearning.cs