Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLASD8 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLASD8 Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLASD8 (DCOPY dcopy, DLASCL dlascl, DLASD4 dlasd4, DLASET dlaset, XERBLA xerbla, DDOT ddot, DLAMC3 dlamc3, DNRM2 dnrm2)
DLASD8 ()
void Run (int ICOMPQ, int K, ref double[] D, int offset_d, ref double[] Z, int offset_z, ref double[] VF, int offset_vf, ref double[] VL, int offset_vl, ref double[] DIFL, int offset_difl, ref double[] DIFR, int offset_difr, int LDDIFR, ref double[] DSIGMA, int offset_dsigma, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
DCOPY _dcopy
DLASCL _dlascl
DLASD4 _dlasd4
DLASET _dlaset
XERBLA _xerbla
DDOT _ddot
DLAMC3 _dlamc3
DNRM2 _dnrm2
Static Private Attributes
const double ONE = 1.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLASD8 finds the square roots of the roots of the secular equation, as defined by the values in DSIGMA and Z. It makes the appropriate calls to DLASD4, and stores, for each element in D, the distance to its two nearest poles (elements in DSIGMA). It also updates the arrays VF and VL, the first and last components of all the right singular vectors of the original bidiagonal matrix.
DLASD8 is called from DLASD6.
/summary>
Constructor & Destructor Documentation
DLASD8() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLASD8.DLASD8 (DCOPY dcopy, DLASCL dlascl, DLASD4 dlasd4, DLASET dlaset, XERBLA xerbla, DDOT ddot, DLAMC3 dlamc3, DNRM2 dnrm2) inline
DLASD8() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLASD8.DLASD8 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLASD8.Run (int ICOMPQ, int K, ref double[] D, int offset_d, ref double[] Z, int offset_z, ref double[] VF, int offset_vf, ref double[] VL, int offset_vl, ref double[] DIFL, int offset_difl, ref double[] DIFR, int offset_difr, int LDDIFR, ref double[] DSIGMA, int offset_dsigma, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
DLASD8 finds the square roots of the roots of the secular equation, as defined by the values in DSIGMA and Z. It makes the appropriate calls to DLASD4, and stores, for each element in D, the distance to its two nearest poles (elements in DSIGMA). It also updates the arrays VF and VL, the first and last components of all the right singular vectors of the original bidiagonal matrix.
DLASD8 is called from DLASD6.
/summary>
Parameters
ICOMPQ (input) INTEGER Specifies whether singular vectors are to be computed in factored form in the calling routine: = 0: Compute singular values only. = 1: Compute singular vectors in factored form as well. /param>
Parameters
K (input) INTEGER The number of terms in the rational function to be solved by DLASD4. K .GE. 1. /param>
Parameters
D (output) DOUBLE PRECISION array, dimension (K) On output, D contains the updated singular values. /param>
Parameters
Z (input) DOUBLE PRECISION array, dimension (K) The first K elements of this array contain the components of the deflation-adjusted updating row vector. /param>
Parameters
VF (input/output) DOUBLE PRECISION array, dimension (K) On entry, VF contains information passed through DBEDE8. On exit, VF contains the first K components of the first components of all right singular vectors of the bidiagonal matrix. /param>
Parameters
VL (input/output) DOUBLE PRECISION array, dimension (K) On entry, VL contains information passed through DBEDE8. On exit, VL contains the first K components of the last components of all right singular vectors of the bidiagonal matrix. /param>
Parameters
DIFL (output) DOUBLE PRECISION array, dimension (K) On exit, DIFL(I) = D(I) - DSIGMA(I). /param>
Parameters
DIFR (output) DOUBLE PRECISION array, dimension (LDDIFR, 2) if ICOMPQ = 1 and dimension (K) if ICOMPQ = 0. On exit, DIFR(I,1) = D(I) - DSIGMA(I+1), DIFR(K,1) is not defined and will not be referenced.
If ICOMPQ = 1, DIFR(1:K,2) is an array containing the normalizing factors for the right singular vector matrix. /param>
Parameters
LDDIFR (input) INTEGER The leading dimension of DIFR, must be at least K. /param>
Parameters
DSIGMA (input) DOUBLE PRECISION array, dimension (K) The first K elements of this array contain the old roots of the deflated updating problem. These are the poles of the secular equation. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension at least 3 * K /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. .GT. 0: if INFO = 1, an singular value did not converge /param>
References DotNumerics.LinearAlgebra.CSLapack.DLASD8.ONE, DotNumerics.LinearAlgebra.CSLapack.DDOT.Run(), DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DNRM2.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASET.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD4.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMC3.Run(), and DotNumerics.FortranLibrary.FortranLib.Sign().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD6.Run().
Member Data Documentation
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLASD8._dcopy private
_dlascl
DLASCL DotNumerics.LinearAlgebra.CSLapack.DLASD8._dlascl private
_dlasd4
DLASD4 DotNumerics.LinearAlgebra.CSLapack.DLASD8._dlasd4 private
_dlaset
DLASET DotNumerics.LinearAlgebra.CSLapack.DLASD8._dlaset private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLASD8._xerbla private
_ddot
DDOT DotNumerics.LinearAlgebra.CSLapack.DLASD8._ddot private
_dlamc3
DLAMC3 DotNumerics.LinearAlgebra.CSLapack.DLASD8._dlamc3 private
_dnrm2
DNRM2 DotNumerics.LinearAlgebra.CSLapack.DLASD8._dnrm2 private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLASD8.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD8.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlasd8.cs