Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DSYR2 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DSYR2 Class Reference
Public Member Functions
DSYR2 (LSAME lsame, XERBLA xerbla)
DSYR2 ()
void Run (string UPLO, int N, double ALPHA, double[] X, int offset_x, int INCX, double[] Y, int offset_y, int INCY, ref double[] A, int offset_a, int LDA)
Private Attributes
LSAME _lsame
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E+0
Detailed Description
Purpose
DSYR2 performs the symmetric rank 2 operation
A := alpha*x*y' + alpha*y*x' + A,
where alpha is a scalar, x and y are n element vectors and A is an n by n symmetric matrix.
/summary>
Constructor & Destructor Documentation
DSYR2() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DSYR2.DSYR2 (LSAME lsame, XERBLA xerbla) inline
DSYR2() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DSYR2.DSYR2 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DSYR2.Run (string UPLO, int N, double ALPHA, double[] X, int offset_x, int INCX, double[] Y, int offset_y, int INCY, ref double[] A, int offset_a, int LDA) inline
Purpose
DSYR2 performs the symmetric rank 2 operation
A := alpha*x*y' + alpha*y*x' + A,
where alpha is a scalar, x and y are n element vectors and A is an n by n symmetric matrix.
/summary>
Parameters
UPLO
CHARACTER*1. On entry, UPLO specifies whether the upper or lower triangular part of the array A is to be referenced as follows:
UPLO = 'U' or 'u' Only the upper triangular part of A is to be referenced.
UPLO = 'L' or 'l' Only the lower triangular part of A is to be referenced.
Unchanged on exit. /param>
Parameters
N
INTEGER. On entry, N specifies the order of the matrix A. N must be at least zero. Unchanged on exit. /param>
Parameters
ALPHA
DOUBLE PRECISION. On entry, ALPHA specifies the scalar alpha. Unchanged on exit. /param>
Parameters
X
DOUBLE PRECISION array of dimension at least (1 + (n - 1)*abs(INCX)). Before entry, the incremented array X must contain the n element vector x. Unchanged on exit. /param>
Parameters
INCX
INTEGER. On entry, INCX specifies the increment for the elements of X. INCX must not be zero. Unchanged on exit. /param>
Parameters
Y
DOUBLE PRECISION array of dimension at least (1 + (n - 1)*abs(INCY)). Before entry, the incremented array Y must contain the n element vector y. Unchanged on exit. /param>
Parameters
INCY
INTEGER. On entry, INCY specifies the increment for the elements of Y. INCY must not be zero. Unchanged on exit. /param>
Parameters
A := alpha*x*y' + alpha*y*x' + A, /param>
Parameters
LDA
INTEGER. On entry, LDA specifies the first dimension of A as declared in the calling (sub) program. LDA must be at least max(1, n). Unchanged on exit.
/param>
References DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), and DotNumerics.LinearAlgebra.CSLapack.DSYR2.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYTD2.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DSYR2._lsame private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DSYR2._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DSYR2.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYR2.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dsyr2.cs