Doc: IGLib EXTENDED: alglib.fft Class Reference
alglib.fft Class Reference
Static Public Member Functions
static void fftc1d (ref complex[] a, int n)
static void fftc1dinv (ref complex[] a, int n)
static void fftr1d (double[] a, int n, ref complex[] f)
static void fftr1dinv (complex[] f, int n, ref double[] a)
static void fftr1dinternaleven (ref double[] a, int n, ref double[] buf, ftbase.ftplan plan)
static void fftr1dinvinternaleven (ref double[] a, int n, ref double[] buf, ftbase.ftplan plan)
static void fftc1d (ref complex[] a, int n)
static void fftc1dinv (ref complex[] a, int n)
static void fftr1d (double[] a, int n, ref complex[] f)
static void fftr1dinv (complex[] f, int n, ref double[] a)
static void fftr1dinternaleven (ref double[] a, int n, ref double[] buf, ftbase.fasttransformplan plan)
static void fftr1dinvinternaleven (ref double[] a, int n, ref double[] buf, ftbase.fasttransformplan plan)
Member Function Documentation
fftc1d() [1/2]
static void alglib.fft.fftc1d (ref complex[] a, int n) inline static
References alglib.ap.assert(), alglib.ftbase.ftbaseexecuteplan(), alglib.ftbase.ftbasegeneratecomplexfftplan(), and alglib.apserv.isfinitecvector().
Referenced by alglib.conv.convc1dx(), alglib.fftc1d(), alglib.fft.fftc1dinv(), alglib.fft.fftr1d(), alglib.testfftunit.quicktest(), and alglib.testfftunit.testfft().
fftc1dinv() [1/2]
static void alglib.fft.fftc1dinv (ref complex[] a, int n) inline static
References alglib.ap.assert(), alglib.fft.fftc1d(), and alglib.apserv.isfinitecvector().
Referenced by alglib.fftc1dinv(), alglib.testfftunit.quicktest(), and alglib.testfftunit.testfft().
fftr1d() [1/2]
static void alglib.fft.fftr1d (double[] a, int n, ref complex[] f) inline static
References alglib.ap.assert(), alglib.math.conj(), alglib.fft.fftc1d(), alglib.ftbase.ftbaseexecuteplan(), alglib.ftbase.ftbasegeneratecomplexfftplan(), alglib.apserv.isfinitevector(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.conv.convr1dcircularinv(), alglib.fftr1d(), alglib.fft.fftr1dinv(), alglib.fht.fhtr1d(), and alglib.testfftunit.testfft().
fftr1dinv() [1/2]
static void alglib.fft.fftr1dinv (complex[] f, int n, ref double[] a) inline static
References alglib.ap.assert(), alglib.fft.fftr1d(), and alglib.math.isfinite().
Referenced by alglib.conv.convr1dcircularinv(), alglib.fftr1dinv(), and alglib.testfftunit.testfft().
fftr1dinternaleven() [1/2]
static void alglib.fft.fftr1dinternaleven (ref double[] a, int n, ref double[] buf, ftbase.ftplan plan) inline static
References alglib.ap.assert(), alglib.ftbase.ftbaseexecuteplan(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.conv.convr1dcircularinv(), alglib.conv.convr1dinv(), alglib.conv.convr1dx(), alglib.fft.fftr1dinvinternaleven(), and alglib.testfftunit.testfft().
fftr1dinvinternaleven() [1/2]
static void alglib.fft.fftr1dinvinternaleven (ref double[] a, int n, ref double[] buf, ftbase.ftplan plan) inline static
References alglib.ap.assert(), and alglib.fft.fftr1dinternaleven().
Referenced by alglib.conv.convr1dcircularinv(), alglib.conv.convr1dinv(), alglib.conv.convr1dx(), and alglib.testfftunit.testfft().
fftc1d() [2/2]
static void alglib.fft.fftc1d (ref complex[] a, int n) inline static
References alglib.ap.assert(), alglib.ftbase.ftapplyplan(), alglib.ftbase.ftcomplexfftplan(), and alglib.apserv.isfinitecvector().
fftc1dinv() [2/2]
static void alglib.fft.fftc1dinv (ref complex[] a, int n) inline static
References alglib.ap.assert(), alglib.fft.fftc1d(), and alglib.apserv.isfinitecvector().
fftr1d() [2/2]
static void alglib.fft.fftr1d (double[] a, int n, ref complex[] f) inline static
References alglib.ap.assert(), alglib.math.conj(), alglib.fft.fftc1d(), alglib.ftbase.ftapplyplan(), alglib.ftbase.ftcomplexfftplan(), alglib.apserv.isfinitevector(), alglib.complex.x, and alglib.complex.y.
fftr1dinv() [2/2]
static void alglib.fft.fftr1dinv (complex[] f, int n, ref double[] a) inline static
References alglib.ap.assert(), alglib.fft.fftr1d(), and alglib.math.isfinite().
fftr1dinternaleven() [2/2]
static void alglib.fft.fftr1dinternaleven (ref double[] a, int n, ref double[] buf, ftbase.fasttransformplan plan) inline static
References alglib.ap.assert(), alglib.ftbase.ftapplyplan(), alglib.complex.x, and alglib.complex.y.
fftr1dinvinternaleven() [2/2]
static void alglib.fft.fftr1dinvinternaleven (ref double[] a, int n, ref double[] buf, ftbase.fasttransformplan plan) inline static
References alglib.ap.assert(), and alglib.fft.fftr1dinternaleven().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/fasttransforms.cs