Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DAXPY Class Reference
DotNumerics.LinearAlgebra.CSLapack.DAXPY Class Reference
Public Member Functions
DAXPY ()
void Run (int N, double DA, double[] DX, int offset_dx, int INCX, ref double[] DY, int offset_dy, int INCY)
Constructor & Destructor Documentation
DAXPY()
DotNumerics.LinearAlgebra.CSLapack.DAXPY.DAXPY () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DAXPY.Run (int N, double DA, double[] DX, int offset_dx, int INCX, ref double[] DY, int offset_dy, int INCY) inline
References DotNumerics.FortranLibrary.FortranLib.Mod().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAPLL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARZ.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYTD2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAHR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEHRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLATRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLATRS.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGLSE.Run(), and DotNumerics.LinearAlgebra.CSLapack.DTREVC.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/daxpy.cs