Doc: IGLib EXTENDED: IG.Web.WSBase Class Reference
IG.Web.WSBase Class Reference
Base class for IGLib webservices.
Public Member Functions
string TestService ()
Tests whether the web service is alive.
string TestServiceArg (string commandlineArguments)
Tests whether the web service is alive.
string TestServiceArgs (string[] commandlineArguments)
Tests whether the web service is alive.
string TestCount ()
Web service method example. Increments a static counter.
string TestCount ()
Web service method example. Increments a static counter.
Static Public Member Functions
static void ExampleUseServiceWithSessions (object sender, EventArgs e)
Static Public Attributes
const string DefaultNamespace = "http://www2.arnes.si/~ljc3m2/igor/iglib/"
Static Protected Member Functions
static int GetNextId ()
Returns a new ID for a web service object.
Protected Attributes
int _id = GetNextId()
Static Protected Attributes
static string _namespace = DefaultNamespace
const int CacheHelloWorldTime = 10
static int _nextId = 0
const string VarNumTestCalls = "NumTestCalls__IGLib_Service_Base"
static int _testCount
Properties
static string NameSpace [get, set]
static int NextIdToBeAssigned [get]
Returns the next service object ID to be assigned.
virtual int Id [get, protected set]
object Lock [get]
Object used for locking of the current object.
Properties inherited from IG.Lib.IIdentifiable
int Id [get]
Returns unique ID (in the scope of a given type) of the current object.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
readonly object _lock = new object()
Detailed Description
Base class for IGLib webservices.
Base class for webservices.
Member Function Documentation
GetNextId()
static int IG.Web.WSBase.GetNextId () inline static protected
Returns a new ID for a web service object.
References IG.Web.WSBase._nextId, and IG.Lib.Util.LockGlobal.
TestService()
string IG.Web.WSBase.TestService () inline
Tests whether the web service is alive.
Returns a string identifying web service' class and object ID.
To test, right-click the Web Service's .asmx file and select View in a browser.
Returns
References IG.Web.WSBase.TestServiceArgs().
TestServiceArg()
string IG.Web.WSBase.TestServiceArg (string commandlineArguments) inline
Tests whether the web service is alive.
Returns a string identifying web service' class and object ID.
To test, right-click the Web Service's .asmx file and select View in a browser.
Returns
References IG.Lib.UtilStr.GetArgumentsArray(), and IG.Web.WSBase.TestServiceArgs().
TestServiceArgs()
string IG.Web.WSBase.TestServiceArgs (string[] commandlineArguments) inline
Tests whether the web service is alive.
Returns a string identifying web service' class and object ID.
To test, right-click the Web Service's .asmx file and select View in a browser.
Returns
References IG.Web.WSBase.Id, and IG.Web.WSBase.VarNumTestCalls.
Referenced by IG.Web.WSBase.TestService(), and IG.Web.WSBase.TestServiceArg().
TestCount() [1/2]
string IG.Web.WSBase.TestCount () inline
Web service method example. Increments a static counter.
To test, right-click the Web Service's .asmx file and select View in Browser
Returns
References IG.Web.WSBase._testCount.
ExampleUseServiceWithSessions()
static void IG.Web.WSBase.ExampleUseServiceWithSessions (object sender, EventArgs e) inline static
References WcfService_WebDev_FromTemplate.WSBaseRef.WSBase.TestServiceArg().
TestCount() [2/2]
string IG.Web.WSBase.TestCount () inline
Web service method example. Increments a static counter.
To test, right-click the Web Service's .asmx file and select View in Browser
Returns
References IG.Web.WSBase._testCount.
Member Data Documentation
DefaultNamespace
const string IG.Web.WSBase.DefaultNamespace = "http://www2.arnes.si/~ljc3m2/igor/iglib/" static
_namespace
string IG.Web.WSBase._namespace = DefaultNamespace static protected
CacheHelloWorldTime
const int IG.Web.WSBase.CacheHelloWorldTime = 10 static protected
_nextId
int IG.Web.WSBase._nextId = 0 static protected
Referenced by IG.Web.WSBase.GetNextId().
_id
int IG.Web.WSBase._id = GetNextId() protected
_lock
readonly object IG.Web.WSBase._lock = new object() private
VarNumTestCalls
const string IG.Web.WSBase.VarNumTestCalls = "NumTestCalls__IGLib_Service_Base" static protected
Referenced by IG.Web.WSBase.TestServiceArgs().
_testCount
static int IG.Web.WSBase._testCount static protected
Referenced by IG.Web.WSBase.TestCount().
Property Documentation
NameSpace
string IG.Web.WSBase.NameSpace static get set
NextIdToBeAssigned
int IG.Web.WSBase.NextIdToBeAssigned static get
Returns the next service object ID to be assigned.
Id
virtual int IG.Web.WSBase.Id get protected set
Referenced by IG.Web.WSBase.TestServiceArgs().
Lock
object IG.Web.WSBase.Lock get
Object used for locking of the current object.
The documentation for this class was generated from the following files:
igtest/ws_develop/Classes/WSBase.cs
igtest/ws_develop/Copy of WSBase.cs