Doc: IGLib EXTENDED: NUnit.Engine.TestEngine Class Reference
NUnit.Engine.TestEngine Class Reference
The TestEngine provides services that allow a client program to interact with NUnit in order to explore, load and run tests.
Public Member Functions
TestEngine ()
void Initialize ()
Initialize the engine. This includes initializing mono addins, setting the trace level and creating the standard set of services used in the Engine.
ITestRunner GetRunner (TestPackage package)
Returns a test runner for use by clients that need to load the tests once and run them multiple times. If necessary, the services are initialized first.
void Dispose ()
Protected Member Functions
virtual void Dispose (bool disposing)
Properties
ServiceContext Services [get, private set]
string WorkDirectory [get, set]
InternalTraceLevel InternalTraceLevel [get, set]
IServiceLocator ITestEngine. Services [get]
Access the public IServiceLocator, first initializing the services if that has not already been done.
Properties inherited from NUnit.Engine.ITestEngine
IServiceLocator Services [get]
Gets the IServiceLocator interface, which gives access to certain services provided by the engine.
string WorkDirectory [get, set]
Gets and sets the directory path used by the engine for saving files. Some services may ignore changes to this path made after initialization. The default value is the current directory.
InternalTraceLevel InternalTraceLevel [get, set]
Gets and sets the InternalTraceLevel used by the engine. Changing this setting after initialization will have no effect. The default value is the value saved in the NUnit settings.
Private Attributes
bool _disposed = false
Detailed Description
The TestEngine provides services that allow a client program to interact with NUnit in order to explore, load and run tests.
Constructor & Destructor Documentation
TestEngine()
NUnit.Engine.TestEngine.TestEngine () inline
References NUnit.Engine.TestEngine.InternalTraceLevel, NUnit.Engine.TestEngine.Services, and NUnit.Engine.TestEngine.WorkDirectory.
Member Function Documentation
Initialize()
void NUnit.Engine.TestEngine.Initialize () inline
Initialize the engine. This includes initializing mono addins, setting the trace level and creating the standard set of services used in the Engine.
This interface is not normally called by user code. Programs linking only to the nunit.engine.api assembly are given a pre-initialized instance of TestEngine. Programs that link directly to nunit.engine usually do so in order to perform custom initialization.
Implements NUnit.Engine.ITestEngine.
References NUnit.Engine.ServiceContext.Add(), NUnit.Engine.Internal.SettingsGroup.GetSetting(), NUnit.Engine.TestEngine.InternalTraceLevel, NUnit.Engine.ServiceContext.ServiceManager, NUnit.Engine.TestEngine.Services, NUnit.Engine.Services.ServiceManager.StartServices(), and NUnit.Engine.TestEngine.WorkDirectory.
Referenced by NUnit.Engine.TestEngine.GetRunner(), and NUnit.Agent.NUnitTestAgent.Main().
GetRunner()
ITestRunner NUnit.Engine.TestEngine.GetRunner (TestPackage package) inline
Returns a test runner for use by clients that need to load the tests once and run them multiple times. If necessary, the services are initialized first.
Returns
An ITestRunner.
Implements NUnit.Engine.ITestEngine.
References NUnit.Engine.TestEngine.Initialize(), NUnit.Engine.ServiceContext.ServiceManager, NUnit.Engine.TestEngine.Services, and NUnit.Engine.Services.ServiceManager.ServicesInitialized.
Dispose() [1/2]
void NUnit.Engine.TestEngine.Dispose () inline
References NUnit.Engine.ServiceContext.ServiceManager, NUnit.Engine.TestEngine.Services, and NUnit.Engine.Services.ServiceManager.StopServices().
Dispose() [2/2]
virtual void NUnit.Engine.TestEngine.Dispose (bool disposing) inline protected virtual
References NUnit.Engine.TestEngine._disposed, NUnit.Engine.Services.ServiceManager.Dispose(), NUnit.Engine.ServiceContext.ServiceManager, and NUnit.Engine.TestEngine.Services.
Member Data Documentation
_disposed
bool NUnit.Engine.TestEngine._disposed = false private
Referenced by NUnit.Engine.TestEngine.Dispose().
Property Documentation
Services [1/2]
ServiceContext NUnit.Engine.TestEngine.Services get private set
Referenced by NUnit.Engine.TestEngine.Dispose(), NUnit.Engine.TestEngine.GetRunner(), NUnit.Engine.TestEngine.Initialize(), NUnit.Agent.NUnitTestAgent.Main(), and NUnit.Engine.TestEngine.TestEngine().
WorkDirectory
string NUnit.Engine.TestEngine.WorkDirectory get set
Referenced by NUnit.Engine.TestEngine.Initialize(), and NUnit.Engine.TestEngine.TestEngine().
InternalTraceLevel
InternalTraceLevel NUnit.Engine.TestEngine.InternalTraceLevel get set
Referenced by NUnit.Engine.TestEngine.Initialize(), and NUnit.Engine.TestEngine.TestEngine().
Services [2/2]
IServiceLocator ITestEngine. NUnit.Engine.TestEngine.Services get private
Access the public IServiceLocator, first initializing the services if that has not already been done.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/TestEngine.cs