Doc: IGLib EXTENDED: NUnit.TestData.RandomAttributeTests.RandomAttributeFixture Class Reference
NUnit.TestData.RandomAttributeTests.RandomAttributeFixture Class Reference
Public Types
enum TestEnum { TestEnum.A, TestEnum.B, TestEnum.C }
Public Member Functions
void RandomInt ([Random(COUNT)] int x)
void RandomInt_IntRange ([Random(7, 47, COUNT)] int x)
void RandomUInt ([Random(COUNT)] uint x)
void RandomUInt_UIntRange ([Random(7u, 47u, COUNT)] uint x)
void RandomShort ([Random(COUNT)] short x)
void RandomShort_ShortRange ([Random((short) 7,(short) 47, COUNT)] short x)
void RandomShort_IntRange ([Random(7, 47, COUNT)] short x)
void RandomUShort ([Random(COUNT)] ushort x)
void RandomUShort_UShortRange ([Random((ushort) 7,(ushort) 47, COUNT)] ushort x)
void RandomUShort_IntRange ([Random(7, 47, COUNT)] ushort x)
void RandomLong ([Random(COUNT)] long x)
void RandomLong_LongRange ([Random(7L, 47L, COUNT)] long x)
void RandomULong ([Random(COUNT)] ulong x)
void RandomULong_ULongRange ([Random(7ul, 47ul, COUNT)] ulong x)
void RandomDouble ([Random(COUNT)] double x)
void RandomDouble_DoubleRange ([Random(7.0d, 47.0d, COUNT)] double x)
void RandomFloat ([Random(COUNT)] float x)
void RandomFloat_FloatRange ([Random(7.0f, 47.0f, COUNT)] float x)
void RandomEnum ([Random(COUNT)] TestEnum x)
void RandomDecimal ([Random(COUNT)] decimal x)
void RandomDecimal_IntRange ([Random(7, 47, COUNT)] decimal x)
void RandomDecimal_DoubleRange ([Random(7.0, 47.0, COUNT)] decimal x)
void RandomByte ([Random(COUNT)] byte x)
void RandomByte_ByteRange ([Random((byte) 7,(byte) 47, COUNT)] byte x)
void RandomByte_IntRange ([Random(7, 47, COUNT)] byte x)
void RandomSByte ([Random(COUNT)] sbyte x)
void RandomSByte_SByteRange ([Random((sbyte) 7,(sbyte) 47, COUNT)] sbyte x)
void RandomSByte_IntRange ([Random(7, 47, COUNT)] sbyte x)
Static Public Attributes
const int COUNT = 3
Member Enumeration Documentation
TestEnum
enum NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.TestEnum strong
Enumerator
A
B
C
Member Function Documentation
RandomInt()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomInt ([Random(COUNT)] int x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomInt_IntRange()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomInt_IntRange ([Random(7, 47, COUNT)] int x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomUInt()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomUInt ([Random(COUNT)] uint x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomUInt_UIntRange()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomUInt_UIntRange ([Random(7u, 47u, COUNT)] uint x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomShort()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomShort ([Random(COUNT)] short x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomShort_ShortRange()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomShort_ShortRange ([Random((short)7, (short)47, COUNT)] short x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomShort_IntRange()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomShort_IntRange ([Random(7, 47, COUNT)] short x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomUShort()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomUShort ([Random(COUNT)] ushort x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomUShort_UShortRange()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomUShort_UShortRange ([Random((ushort)7, (ushort)47, COUNT)] ushort x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomUShort_IntRange()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomUShort_IntRange ([Random(7, 47, COUNT)] ushort x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomLong()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomLong ([Random(COUNT)] long x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomLong_LongRange()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomLong_LongRange ([Random(7L, 47L, COUNT)] long x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomULong()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomULong ([Random(COUNT)] ulong x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomULong_ULongRange()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomULong_ULongRange ([Random(7ul, 47ul, COUNT)] ulong x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomDouble()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomDouble ([Random(COUNT)] double x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomDouble_DoubleRange()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomDouble_DoubleRange ([Random(7.0d, 47.0d, COUNT)] double x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomFloat()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomFloat ([Random(COUNT)] float x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomFloat_FloatRange()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomFloat_FloatRange ([Random(7.0f, 47.0f, COUNT)] float x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomEnum()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomEnum ([Random(COUNT)] TestEnum x) inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
RandomDecimal()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomDecimal ([Random(COUNT)] decimal x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomDecimal_IntRange()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomDecimal_IntRange ([Random(7, 47, COUNT)] decimal x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomDecimal_DoubleRange()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomDecimal_DoubleRange ([Random(7.0, 47.0, COUNT)] decimal x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomByte()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomByte ([Random(COUNT)] byte x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomByte_ByteRange()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomByte_ByteRange ([Random((byte)7, (byte)47, COUNT)] byte x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomByte_IntRange()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomByte_IntRange ([Random(7, 47, COUNT)] byte x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomSByte()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomSByte ([Random(COUNT)] sbyte x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomSByte_SByteRange()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomSByte_SByteRange ([Random((sbyte)7, (sbyte)47, COUNT)] sbyte x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RandomSByte_IntRange()
void NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.RandomSByte_IntRange ([Random(7, 47, COUNT)] sbyte x) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
Member Data Documentation
COUNT
const int NUnit.TestData.RandomAttributeTests.RandomAttributeFixture.COUNT = 3 static
Referenced by NUnit.Framework.Attributes.RandomAttributeTests.CheckRandomResult().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/testdata/RandomAttributeFixture.cs