Doc: IGLib EXTENDED: Meta.Numerics.Statistics.Distributions.WeibullDistribution Class Reference
Meta.Numerics.Statistics.Distributions.WeibullDistribution Class Reference
Represents a Weibull distribution.
Public Member Functions
WeibullDistribution (double scale, double shape)
Initializes a new Weibull distribution.
override double ProbabilityDensity (double x)
Returns the probability density at the given point.
override double LeftProbability (double x)
Returns the cumulative probability to the left of (below) the given point.
override double RightProbability (double x)
Return the cumulative probability to the right of (above) the given point.
override double InverseLeftProbability (double P)
Returns the point at which the cumulative distribution function attains a given value.
override double InverseRightProbability (double Q)
Returns the point at which the right probability function attains the given value.
override double Moment (int r)
Computes a raw moment of the distribution.
override double MomentAboutMean (int r)
Computes a central moment of the distribution.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double ExpectationValue (Func< double, double > f)
Computes the expectation value of the given function.
virtual double GetRandomValue (Random rng)
Returns a random value.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Cumulant (int r)
Computes a cumulant of the distribution.
Static Public Member Functions
static FitResult FitToSample (Sample sample)
Computes the Weibull distribution that best fits the given sample.
Properties
double ScaleParameter [get]
Gets the scale parameter of the distribution.
double ShapeParameter [get]
Gets the shape parameter of the distribution.
override Interval Support [get]
override double Mean [get]
override double Median [get]
override double Variance [get]
Properties inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double Median [get]
Gets the median of the distribution.
virtual Interval Support [get]
Gets the interval over which the distribution is nonvanishing.
Properties inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Mean [get]
Gets the mean of the distribution.
virtual double Variance [get]
Gets the variance of the distribution.
virtual double StandardDeviation [get]
Gets the standard deviation of the distribution.
virtual double Skewness [get]
Gets the skewness of the distribution.
virtual double ExcessKurtosis [get]
Gets the excess kurtosis of the distribution.
Private Member Functions
double[] IParameterizedDistribution. GetParameters ()
Gets the parameter values of the distribution.
void IParameterizedDistribution. SetParameters (IList< double > parameters)
Sets the parameter values of the distribution.
double IParameterizedDistribution. Likelihood (double x)
Gets the likelihood of a value, given the current parameters.
Private Attributes
double scale
double shape
Detailed Description
Represents a Weibull distribution.
The Weibull distribution is a generalized form of the exponential distriubtion for which the decay probability is not constant, but instead increases with time (for shape parameters greater than one) or, less commonly, decreases with time (for shape parameters less than one). When the shape parameter is one, the Weibull distribution reduces to the exponential distribution.
The Weibull distribution is commonly used in engineering applications to model the time-to-failure of industrial componets.
Constructor & Destructor Documentation
WeibullDistribution()
Meta.Numerics.Statistics.Distributions.WeibullDistribution.WeibullDistribution (double scale, double shape) inline
Initializes a new Weibull distribution.
Parameters
scale The scale parameter, which must be positive.
shape The shape parameter, which must be positive.
References Meta.Numerics.Statistics.Distributions.WeibullDistribution.scale, and Meta.Numerics.Statistics.Distributions.WeibullDistribution.shape.
Referenced by Meta.Numerics.Statistics.Distributions.WeibullDistribution.FitToSample().
Member Function Documentation
ProbabilityDensity()
override double Meta.Numerics.Statistics.Distributions.WeibullDistribution.ProbabilityDensity (double x) inline virtual
Returns the probability density at the given point.
Implements Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.WeibullDistribution.scale, and Meta.Numerics.Statistics.Distributions.WeibullDistribution.shape.
Referenced by Meta.Numerics.Statistics.Distributions.WeibullDistribution.Likelihood().
LeftProbability()
override double Meta.Numerics.Statistics.Distributions.WeibullDistribution.LeftProbability (double x) inline virtual
Returns the cumulative probability to the left of (below) the given point.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.MoreMath.ExpMinusOne(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.scale, and Meta.Numerics.Statistics.Distributions.WeibullDistribution.shape.
RightProbability()
override double Meta.Numerics.Statistics.Distributions.WeibullDistribution.RightProbability (double x) inline virtual
Return the cumulative probability to the right of (above) the given point.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.WeibullDistribution.scale, and Meta.Numerics.Statistics.Distributions.WeibullDistribution.shape.
InverseLeftProbability()
override double Meta.Numerics.Statistics.Distributions.WeibullDistribution.InverseLeftProbability (double P) inline virtual
Returns the point at which the cumulative distribution function attains a given value.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.MoreMath.LogOnePlus(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.scale, and Meta.Numerics.Statistics.Distributions.WeibullDistribution.shape.
InverseRightProbability()
override double Meta.Numerics.Statistics.Distributions.WeibullDistribution.InverseRightProbability (double Q) inline virtual
Returns the point at which the right probability function attains the given value.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.WeibullDistribution.scale, and Meta.Numerics.Statistics.Distributions.WeibullDistribution.shape.
Moment()
override double Meta.Numerics.Statistics.Distributions.WeibullDistribution.Moment (int r) inline virtual
Computes a raw moment of the distribution.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Functions.AdvancedMath.Gamma(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.scale, and Meta.Numerics.Statistics.Distributions.WeibullDistribution.shape.
MomentAboutMean()
override double Meta.Numerics.Statistics.Distributions.WeibullDistribution.MomentAboutMean (int r) inline virtual
Computes a central moment of the distribution.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.WeibullDistribution.shape.
FitToSample()
static FitResult Meta.Numerics.Statistics.Distributions.WeibullDistribution.FitToSample (Sample sample) inline static
Computes the Weibull distribution that best fits the given sample.
Parameters
sample The sample to fit.
Returns
The best fit parameters.
The returned fit parameters are the ShapeParameter and ScaleParameter, in that order. These are the same parameters, in the same order, that are required by the WeibullDistribution(double,double) constructor to specify a new Weibull distribution.
Exceptions
ArgumentNullException sample is null.
InvalidOperationException sample contains non-positive values.
InsufficientDataException sample contains fewer than three values.
References Meta.Numerics.Statistics.Sample.Count, Meta.Numerics.Analysis.FunctionMath.FindZero(), Meta.Numerics.Statistics.Sample.InverseLeftProbability(), Meta.Numerics.Statistics.Sample.Minimum, and Meta.Numerics.Statistics.Distributions.WeibullDistribution.WeibullDistribution().
Referenced by Test.BugTests.Bug7213(), Test.SampleTest.WeibullFit(), and Test.SampleTest.WeibullFitUncertainties().
GetParameters()
double [] IParameterizedDistribution. Meta.Numerics.Statistics.Distributions.WeibullDistribution.GetParameters () inline private
Gets the parameter values of the distribution.
Returns
The parameter values characterizing the distribution.
Implements Meta.Numerics.Statistics.Distributions.IParameterizedDistribution.
References Meta.Numerics.Statistics.Distributions.WeibullDistribution.scale, and Meta.Numerics.Statistics.Distributions.WeibullDistribution.shape.
SetParameters()
void IParameterizedDistribution. Meta.Numerics.Statistics.Distributions.WeibullDistribution.SetParameters (IList< double > parameters) inline private
Sets the parameter values of the distribution.
Parameters
parameters A list of parameter values.
Implements Meta.Numerics.Statistics.Distributions.IParameterizedDistribution.
References Meta.Numerics.Statistics.Distributions.WeibullDistribution.scale, and Meta.Numerics.Statistics.Distributions.WeibullDistribution.shape.
Likelihood()
double IParameterizedDistribution. Meta.Numerics.Statistics.Distributions.WeibullDistribution.Likelihood (double x) inline private
Gets the likelihood of a value, given the current parameters.
Parameters
x The value.
Returns
The likelihood of the value.
Implements Meta.Numerics.Statistics.Distributions.IParameterizedDistribution.
References Meta.Numerics.Statistics.Distributions.WeibullDistribution.ProbabilityDensity().
Member Data Documentation
scale
double Meta.Numerics.Statistics.Distributions.WeibullDistribution.scale private
Referenced by Meta.Numerics.Statistics.Distributions.WeibullDistribution.GetParameters(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.InverseLeftProbability(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.InverseRightProbability(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.Moment(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.ProbabilityDensity(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.RightProbability(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.SetParameters(), and Meta.Numerics.Statistics.Distributions.WeibullDistribution.WeibullDistribution().
shape
double Meta.Numerics.Statistics.Distributions.WeibullDistribution.shape private
Referenced by Meta.Numerics.Statistics.Distributions.WeibullDistribution.GetParameters(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.InverseLeftProbability(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.InverseRightProbability(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.Moment(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.MomentAboutMean(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.ProbabilityDensity(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.RightProbability(), Meta.Numerics.Statistics.Distributions.WeibullDistribution.SetParameters(), and Meta.Numerics.Statistics.Distributions.WeibullDistribution.WeibullDistribution().
Property Documentation
ScaleParameter
double Meta.Numerics.Statistics.Distributions.WeibullDistribution.ScaleParameter get
Gets the scale parameter of the distribution.
ShapeParameter
double Meta.Numerics.Statistics.Distributions.WeibullDistribution.ShapeParameter get
Gets the shape parameter of the distribution.
Support
override Interval Meta.Numerics.Statistics.Distributions.WeibullDistribution.Support get
Mean
override double Meta.Numerics.Statistics.Distributions.WeibullDistribution.Mean get
Median
override double Meta.Numerics.Statistics.Distributions.WeibullDistribution.Median get
Variance
override double Meta.Numerics.Statistics.Distributions.WeibullDistribution.Variance get
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/Distributions/WeibullDistribution.cs