Doc: IGLib EXTENDED: IG.Script.NeuralTestScriptShellExt Class Reference
IG.Script.NeuralTestScriptShellExt Class Reference
Public Member Functions
NeuralTestScriptShellExt ()
override void Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings)
Adds commands to the internal interpreter.
Public Member Functions inherited from IG.Script.LoadableScriptShellNeural
LoadableScriptShellNeural ()
override void Analyse (Num.IAnalysisResults anRes)
Dummy analysis, jsut throws the exception.
override void TransfSimulationToNeuralInput (IVector original, ref IVector result)
Transforms the specified vector of simulation input parameters to the vector of neural input parameters and stores the vector to the specified variable.
override void TransfNeuralToSimulationInput (IVector original, ref IVector result)
Transforms the specified vector of neural input parameters to the vector of simulation input parameters and stores the vector to the specified variable.
override void TransfSimulationToNeuralOutput (IVector original, ref IVector result)
Transforms the specified vector of simulation output values (results) to the vector of neural output values and stores the vector to the specified variable.
override void TransfNeuralToSimulationOutput (IVector original, ref IVector result)
Transforms the specified vector of neural output values to the vector of simulation output values (results) and stores the vector to the specified variable.
Public Member Functions inherited from IG.Script.LoadableScriptShellNeuralBase
LoadableScriptShellNeuralBase ()
override void Analyse (Num.IAnalysisResults anRes)
Dummy analysis, jsut throws the exception.
virtual string Test (string[] arguments)
Runs a custom basic test.
virtual string Custom (string[] arguments)
Runs a custom test.
virtual string RunParallelSimulations (string[] arguments)
Runs multiple simulations in parallel threads and saves results in each parallel thread.
virtual string CollectParallelSimulationResults (string[] arguments)
Collects results of simulations run in parallel threads, joins them into a single object and saves them.
virtual IVector TestApproximation (IVector parameters)
Performs a test approximation at the specified vector of parameters and outputs and returns results.
virtual IVector[][] TestApproximationTable (int numPoints)
Calculates a table of specified number of approximations, with parameters running between two points that are chosen by the algorithm.
virtual IVector[][] TestApproximationTable (IVector param1, IVector param2, int numPoints)
Performs a table of approximatinos between two specified vectors of approximation input parameters, and outputs results. It also returns the table of results (approximated output values in form of vectors).
virtual AnalysisResults TestAnalysis (IVector parameters)
Performs test analysis at the specified optimization parameters and outputs results.
virtual AnalysisResults[] TestAnalysisTable (int numPoints)
Calculates a table of specified number of analyses, with parameters running between two points that are chosen by the algorithm.
virtual AnalysisResults[] TestAnalysisTable (IVector param1, IVector param2, int numPoints)
Performs a table of direct analyses between two specified vectors of optimization parameters, and outputs results. It also returns the table of analysis results.
virtual void OptimizeSimplex ()
virtual void TransfNeuralToOptimizationParameters (IVector neuralParameters, ref IVector optimizationParameters)
Maps input parameters for neural network to optimization input parameters.
virtual void TransfOptimizationToNeuralParameters (IVector optimizationParameters, ref IVector neuralParameters)
Maps optimization input parameters to neural network input parameters.
delegate string ParallelRunDelegate (int threadIndex)
virtual void ParSimBegin (int numThreads)
Launches parallel jobs.
virtual void GatherParallelResults (int numThreads)
Reads results form all parallel threads, gathers them in a single training set, and saves them in the template optimiation directory.
virtual string ParSimGetOptimizationDirectoryPath (int threadIndex)
Returns path to the directory containing optimization data for the specified parallel thread.
virtual string ParSimGetMutexName (int threadIndex)
Returns name of the mutex for locking data on disk that is used by the specified parallel thread.
virtual string ParSimGetParallelResultsFilePath (int threadIndex)
Returns path of the file where resuls of calculation in the specified parallel thread are stored.
virtual string GetParallelResultFilePath ()
Returns path of the file where resuls of calculation in the specified parallel thread are stored.
virtual void ParSimPreparelDirectory (int threadIndex)
Prepares data for running calculations in the parallel thread with the specified index.
void ParSimAddResults (int threadIndex, SampledDataSet results)
Reads results of the specified thread and adds them to the existing training set.
string ParSimRunJob (int threadIndex)
Runs the job in the specified parallel thread.
virtual void ParSimGetNextInput (ref IVector simInput)
Generates the next vector of simulation input parameters that will be used for calculation of a new parallel simulation.
virtual void ParSimGetNextNeuralInput (ref IVector simInput)
Generates the next vector of neural input parameters that will be used for calculation of a new training element.
virtual string ParSimGetSimulationDirectoryPath (int threadIndex)
Returns the simulation directory for the specified parallel calculation thread.
virtual IResponseEvaluatorVectorSimple ParSimGetSimulator (int threadIndex)
Creates simulator file manager for the simulator that will the specified parallel task.
virtual SampledDataElement GetTrainingElement (int i)
Gets the training element with the specified index (chosen out of al training points, including verificaion points).
virtual bool IsVerificationPoint (int trainingPointIndex)
Whether the training point with the specified index is a verification points and has not been used in training.
List< SampledDataElement > GetTrainingElements (bool includeVerificationPoints)
Returns a list of all neural training elements.
List< SampledDataElement > GetTrainingElements (bool includeVerificationPoints, bool includeNonVerificationPoints)
Returns a list of all neural training elements.
virtual void GetNeuralInputPerturbance (double ratio, ref IVector perturbance)
Returns a perturbance vector whose componenets represent magnitudes of perturbances of neural input parameters with the specified relative ratio with corresponding parameters' scaling lengths.
virtual void GetNeuralOutputPerturbance (double ratio, ref IVector perturbance)
Returns a perturbance vector whose componenets represent magnitudes of perturbances of neural output values with the specified relative ratio with corresponding values' scaling lengths.
virtual void GetNeuralInputVector (double relativeComponents, ref IVector inputVector)
Returns an input vector whose components are at specified relative distances (with respect to full range) from lower bounds on componens of input vectors.
virtual void GetNeuralOutputVector (double relativeComponents, ref IVector outputVector)
Returns an output vector whose components are at specified relative distances (with respect to full range) from lower bounds on componens of input vectors.
virtual void GetNeuralInputVector (IVector relativeComponents, ref IVector inputVector)
Returns an input vector whose components are at specified relative distances (with respect to full range) from lower bounds on componens of input vectors.
virtual void GetNeuralOutputVector (IVector relativeComponents, ref IVector outputVector)
Returns an output vector whose components are at specified relative distances (with respect to full range) from lower bounds on componens of input vectors.
virtual void GetNeuralInputRelative (IVector inputVector, ref IVector relativeComponents)
Calculates relative components (running from 0 to 1 within bounds for specified vector component) for the specified vector of neural input parameters.
virtual void GetNeuralOutputRelative (IVector outputVector, ref IVector relativeComponents)
Calculates relative components (running from 0 to 1 within bounds for specified vector component) for the specified vector of neural output values.
virtual double InputDistance (IVector v1, IVector v2)
Returns measure of distance between two vectors in the space of input parameters. Euclidean norm scaled accorging to individual parameter ranges is returned.
virtual double OutputDistance (IVector v1, IVector v2)
Returns measure of distance between two vectors in the space of output parameters. Euclidean norm scaled accorging to individual parameter ranges is returned.
virtual double InputDistance (IVector v1, int trainingPointIndex)
Returns measure of distance between the specified neural input vector and vector of input parameters of the training point with the specified index.
virtual double OutputDistance (IVector v1, int trainingPointIndex)
Returns measure of distance between the specified neural output values vector and vector of output values of the training point with the specified index.
virtual int GetClosestInputIndex (IVector v1, bool includeVerificationPoints)
Returns index of training element with the shortest distance of its input parameters to the specified vector.
virtual int GetClosestOutputIndex (IVector v1, bool includeVerificationPoints)
Returns index of training element with the shortest distance of its output values to the specified vector of output values.
void TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, params IVector[] points)
For each point in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
void TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, bool printIndividualPointsComp, params IVector[] points)
For each point in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
void TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, params SampledDataElement[] points)
For each point (training element) in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
void TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, bool printIndividualPointsComp, params SampledDataElement[] points)
For each point (training element) in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
virtual void NeuralCalculate (params double[] inputParameters)
Calculates approximation at specified input parameters.
virtual void NeuralCalculate (IVector inputParameters)
Calculates approximation at specified input parameters.
virtual void NeuralCalculate (IVector inputParameters, ref IVector outputValues)
Calculates approximation at specified input parameters.
virtual List< SampledDataElement > GetRandomTrainingElements (int numElements, bool includeVerificationPoints)
Creates and returns a list of training elements that are randomly chosen from the current training set. Trainingpoints that are not verification points are always included in the set of points for selection.
virtual List< SampledDataElement > GetRandomTrainingElements (int numElements, bool includeVerificationPoints, bool includeNonVerificationPoints)
Creates and returns a list of training elements that are randomly chosen from the current training set.
virtual List< SampledDataElement > GetRandomTrainingElements (IRandomGenerator rand, int numElements, bool includeVerificationPoints)
Creates and returns a list of training elements that are randomly chosen from the current training set. Trainingpoints that are not verification points are always included in the set of points for selection.
virtual List< SampledDataElement > GetRandomTrainingElements (IRandomGenerator rand, int numElements, bool includeVerificationPoints, bool includeNonVerificationPoints)
Creates and returns a list of training elements that are randomly chosen from the current training set.
virtual IVector GetRandomNeuralInput ()
Creates and returns a random vector of neural input parameters whose elements (components) lie within the lower and upper bounds on parameters.
virtual void GetRandomNeuralInput (IRandomGenerator rand, ref IVector result)
Generates a random vector of neural input parameters whose elements (components) lie within the lower and upper bounds on parameters, and stores it to the specified vector.
virtual IVector GetRandomNeuralInput (IRandomGenerator rand)
Creates and returns a random vector of neural input parameters whose elements (components) lie within the lower and upper bounds on parameters.
virtual void GetRandomNeuralInput (ref IVector result)
Generates a random vector of neural input parameters whose elements (components) lie within the lower and upper bounds on parameters.
virtual IVector GetRandomNeuralOutput ()
Creates and returns a random vector of neural output values whose elements (components) lie within the lower and upper bounds on values.
virtual IVector GetRandomNeuralOutput (IRandomGenerator rand)
Creates and returns a random vector of neural output values whose elements (components) lie within the lower and upper bounds on values.
virtual void GetRandomNeuralOutput (ref IVector result)
Generates a random vector of neural output values whose elements (components) lie within the lower and upper bounds on values.
virtual void GetRandomNeuralOutput (IRandomGenerator rand, ref IVector result)
Generates a random vector of neural output values whose elements (components) lie within the lower and upper bounds on neural output values, and stores it to the specified vector.
virtual void PrepareNeuronsTable (int minNeurons, int maxNeurons, int numNeurons, ref int[] neurpnsTable)
Prepares table of neurons in geometric sequence.
void TrainANN (int annType, int NumNeurons, int MaxEpochs, int EpochsInBundle, double LearnignRate, double Momentum, double InputSafetyFactor, double OutputSafetyFactor, double PercentVerificationPoints)
Train the artificial neural network.
virtual string CreateDistortedModelData (string[] arguments)
Creates data for distorted model and stores the data in the specified directory.
virtual void TestDistances (int referencePointIndex, int maxNumPoints)
Test of distances of a specified number of training points with respect to the training point with specified index, in the input parameters space as well as in the output parameter space.
virtual void TestNeuralSpeed (int numEvaluations)
Performs test of speed of calculation of neural network.
virtual void PrintNeuralData ()
This example demonstrates how to extract data necessary for definition of optimization problems.
void SaveSensitivityCSV ()
Saves sensitivity test in csv file.
Public Member Functions inherited from IG.Lib.LoadableScriptShellBase
LoadableScriptShellBase ()
Constructor.
virtual bool RepairSimulationParameters (IVector parameters)
Repairs simulation parameters, if necessary, in such a way that values are consistent with simuation data (e.g. spacing of nodes).
virtual void SimulatorCalculateResponse (IResponseEvaluatorVectorSimple simulator, IVector inputParameters, ref IVector outputValues)
Calculates vector response by the specified simulator, and stores output values to the specified vector variable.
void SimulatorCalculateResponse (IVector parameters, ref IVector outputValues)
Calculates vector response by the main simulator of the script, and stores output values to the specified vector variable.
LoadableScriptShellBase ()
Public Member Functions inherited from IG.Lib.LoadableScriptOptShellBaseControllable
LoadableScriptOptShellBaseControllable ()
Creates a LoadableScriptOptBase object.
Public Member Functions inherited from IG.Lib.LoadableScriptOptBase
LoadableScriptOptBase ()
Creates the LoadableScriptOptBase object.
abstract void Analyse (IAnalysisResults anRes)
Performs direct analysis for optimization problems. This method must be overridden in derived classes where one wants to have direct analysis defined.
Public Member Functions inherited from IG.Lib.LoadableScriptBase
LoadableScriptBase ()
Argument-less constructor. If argument-less constructor is called then initialization is not performed and will be performed later.
string Run (string[] arguments)
Performs the action of this object. Override this in derived classes!
void Initialize (string[] arguments)
Initializes the object. If not called explicitly, this method is automatically called at the first call to the Run method.
virtual string Script_DefaultInitialize (string[] arguments)
Default initialization method for scripts.
virtual string Script_DefaultRun (string[] arguments)
Default run method for the script. Can be used when only installed commands are run by hte script.
virtual ICommandLineApplicationInterpreter Script_CreateInterpreterWithoutCommands ()
Creates and returns an interpreter that can be used as script's internal interpreter for running script's commands.
delegate string Script_CommandDelegate (string[] args)
Delegate for commands that are installed on script's internal interpreter (property Script_Interpreter).
void Script_AddCommand (string commandName, Script_CommandDelegate command, string helpString)
Adds a new internal script command under specified name to the internal interpreter of the current script object.
virtual void Script_AddCommand (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings, string commandName, Script_CommandDelegate command, string helpString)
Adds a new internal script command under specified name to the internal interpreter of the current script object.
string Script_GetHelpString (string scriptCommandName)
Returns help string for internal script command with specified name, or null if help string is not installed for such a command.
void Script_PrintCommandsHelp ()
Prits help for the installed internal commands of the script.
virtual bool Script_ContainsCommand (string commandName)
Returns true if the internal script's interpreter contains a command with specified name, false otherwise.
virtual bool Script_ContainsScriptCommand (string commandName)
Returns true if the specified command is script command (i.e. its first argument is command-name and it is run through the Script_CommandAdapter object).
virtual void Script_RemoveCommand (string commandName)
Removes the specified internal script command from the internal interpreter of the current scripting object.
virtual void Script_RemoveAllCommands ()
Removes ALL internal script commands from the internal interpreter of the current scripting object.
string Script_Run (string[] arguments)
Runs internal script command.
string Script_Run (string commandName, params string[] otherArguments)
Runs internal script command.
virtual void Script_PrintArguments (string messageString, string[] arguments)
Prints the specified array of string arguments (usually passed as command-line arguments).
Protected Member Functions
override string RunThis (string[] arguments)
Runs action of the current object.
Protected Member Functions inherited from IG.Script.LoadableScriptShellNeural
override void InitializeThis (string[] arguments)
Inializes the current script object.
Protected Member Functions inherited from IG.Script.LoadableScriptShellNeuralBase
override void InitializeThis (string[] arguments)
Inializes the current script object.
virtual void LoadJson (string path, ref INeuralApproximator network)
Loads the neural network approximator from the specified file.
virtual void SaveJson (INeuralApproximator approximator, string trainedNetworkFilePath)
Saves the specified trained network to a file.
virtual INeuralApproximator CreateApproximator (int annType=2)
Creates and returns a new neural network approximator, with the basic properties pre-set to default values, dependent on the type of the requires approximator.
virtual void PrintInternalCommandAndArguments (string[] arguments)
Prints internal command being executed and its actual arguments
virtual void GetSimulationInputDefault (ref IVector result)
Gets the vector of default values of simulation parameters and stores it in the specified vector.
virtual void GetSimulationInputMin (ref IVector result)
Gets the vector of lower bounds on simulation parameters and stores it in the specified vector.
virtual void GetSimulationInputMax (ref IVector result)
Gets the vector of upper bounds on simulation parameters and stores it in the specified vector.
virtual void ParSimPrepareDirectories (int numThreads)
Prepares data for the specified number of parallel execution threads.
virtual void ParSimWaitAllCompletion ()
Waits until all parallel jobs complete.
virtual void ParSimAsyncCallback (IAsyncResult ar)
Callback method for asynchronous runs.
virtual string ParSimGetDirectoryExtension (int threadIndex)
Returns directory extension for data directory used in the specified parallel calculation thread.
virtual void GetNeuralInputDefault (ref IVector result)
Gets the vector of default values of neural parameters and stores it in the specified vector.
virtual void GetNeuralInputMin (ref IVector result)
Gets the vector of lower bounds on neural parameters and stores it in the specified vector.
virtual void GetNeuralInputMax (ref IVector result)
Gets the vector of upper bounds on neural parameters and stores it in the specified vector.
virtual void GetRandomNeuralInputFromDataDefinition (IRandomGenerator rand, ref IVector result)
Generates a random vector of neural input parameters whose elements (components) lie within the lower and upper bounds on parameters, and stores it to the specified vector.
Protected Member Functions inherited from IG.Lib.LoadableScriptShellBase
virtual void CreateNewSimulator (string simulatorPath, ref IResponseEvaluatorVectorSimple simulator)
Creates a new simulator that uses the specified simulator directory, and stores it to the specified variable.
override void InitializeThis (string[] arguments)
Inializes the current script object.
Protected Member Functions inherited from IG.Lib.LoadableScriptBase
delegate string CommandMethod (string commandName, string[] args)
Delegate for internal command methods.
ICommandLineApplicationInterpreter Script_CreateInterpreter ()
Creates and returns an interpreter that can be used as script's internal interpreter for running script's commands.
virtual string Script_CommandHelp (string[] arguments)
Prints help.
virtual string Script_CommandTestScript (string[] arguments)
Prints help.
Additional Inherited Members
Public Attributes inherited from IG.Script.LoadableScriptShellNeuralBase
string ParallelResultsFilename = "ParallelResults"
int ParSimNumRuns = 2
Number of runs of simulator in each parallel thread.
int ParSimNumThreads = 2
Number of jobs that can be executed in parallel.
int ParSimSavingFrequency = 4
Specifies how often the results are saved.
string ParSimResultFilename = "GatheredNeuralTrainingData.json"
bool saveGraphs = false
Static Public Attributes inherited from IG.Script.LoadableScriptShellNeuralBase
const string ConstTest = "Test"
Comamnd name for test.
const string ConstHelpTest = "Test of functionality."
const string ConstCustom = "Custom"
Comamnd name for test.
const string ConstHelpCustom = "Custom command that can be quickly modified as needed, for performing."
const string ConstRunParallel = "RunParallel"
Comamnd name for running parallel simulations.
const string ConstHelpRunParallel = "Runs parallel simulations. Args: numThreads numRunsPerThread"
const string ConstCollectParallel = "collectparallel"
Comamnd name for running parallel simulations.
const string ConstHelpCollectParallel = "Collects results of parallel simulations. Args: numThreads"
const string ConstCreateDistortedModelData = "CreateDistortedModelData"
Comamnd name for testing network response for centered point from verification or training points for all Inputs/outputs.
const string ConstHelpCreateDistortedModelData
static string TrainedNetworkAlternativeLovation = null
If different than null, this static property provides alternative location of the file which neural network approximator is resd from, in terms of path relative to optimization directory.
Static Public Attributes inherited from IG.Lib.LoadableScriptBase
const string ConstDefaultHelp = "Help"
Default command name for help.
const string ConstHelpDefaultUniversal = "?"
Universal name of the help command.
const string ConstDefaultTestScrip = "TestScript"
Default command name for test method.
Protected Attributes inherited from IG.Script.LoadableScriptShellNeuralBase
IVector _simulationInputDefault
IVector _simulationInputMin
IVector _simulationInputMax
IBoundingBox _simulationInputBounds
string _parallelResultsFilename = "ParallelResults"
string _parallelResultsFileExtension = ".json"
List< IAsyncResult > ParallelResults
object ParSimProcessDelayLock = new object()
int ParSimProcessDelayMilliseconds = 500
Minimal delay between two successive launches of simulator processes, in milliseconds. This delay is introduced in order to prevent unusual errors that occur when running two simulator processes at approcimately the same time (although they use completely separate data directory structures).
List< IVector > _sensitivityResultsVerification
List< IVector > _sensitivityResultsTraining
INeuralApproximator _trainedNetwork
SampledDataSet _trainingData
SampledDataSet _verificationData
IVector _neuralInputDefault
IVector _neuralInputMin
IVector _neuralInputMax
IBoundingBox _neuralInputBounds
Protected Attributes inherited from IG.Lib.LoadableScriptShellBase
IResponseEvaluatorVectorSimple _simulator
string _projectName
string _simulationName
Protected Attributes inherited from IG.Lib.LoadableScriptOptBase
StopWatch1 _timer = null
bool _checkOptimizationDirectoryExistence = true
Whether to check existence of optimization directory when set. Also applies to working directory.
Protected Attributes inherited from IG.Lib.LoadableScriptBase
string _embeddedCommandName = null
int _outputLevel = DefaultOutputLevel
ICommandLineApplicationInterpreter _script_interpreter
Properties inherited from IG.Script.LoadableScriptShellNeural
override IResponseEvaluatorVectorSimple Simulator [get, protected set]
override int NumOptimizationParameters [get, protected set]
Throws NotImplementedException.
override int NumOptimizationConstraints [get, protected set]
Throws NotImplementedException.
Properties inherited from IG.Script.LoadableScriptShellNeuralBase
abstract int NumOptimizationParameters [get, protected set]
Number of optimization parameters.
abstract int NumOptimizationConstraints [get, protected set]
Number of optimization constraints.
virtual InputOutputDataDefiniton SimulationDataDefinition [get]
Simulation data definition (input and output used by simulator).
virtual int NumSimulationParameters [get, protected set]
Number of simulation input parameters.
virtual int NumSimulationOutputs [get, protected set]
Number of simulation output values.
virtual IBoundingBox SimulationInputBounds [get, protected set]
Bounds on simulation input parameters.
string ParallelResultsFileExtension [get, protected set]
virtual NeuraApproximationFileManager NeuralFM [get]
File manager that provides access to trained neural network and related data.
virtual INeuralApproximator TrainedNetwork [get, protected set]
Trained neural network.
virtual List< IVector > SensitivityVerificationResults [get, protected set]
virtual List< IVector > SensitivityTrainingResults [get, protected set]
virtual INeuralApproximator XXX_TrainedNetwork [get, protected set]
Trained neural network.
virtual InputOutputDataDefiniton NeuralDataDefinition [get, protected set]
Neural data definition.
virtual SampledDataSet TrainingData [get, set]
virtual SampledDataSet VerificationData [get, set]
virtual int NumNeuralParameters [get, protected set]
Number of neural network input parameters.
virtual int NumNeuralOutputs [get, protected set]
Number of neural network output values.
virtual IBoundingBox NeuralInputBounds [get, protected set]
Bounds on neural input parameters.
virtual SampledDataSet NeuralTrainingData [get]
Gets the training data.
virtual int NumAllTrainingPoints [get]
Gets number of all training points, including verification points.
virtual IVector SomeNeuralInput [get]
Returns some vector of input parameters that is within the range.
virtual IVector NeuralInputFromFile [get]
Vector of input parameters read form the file.
Properties inherited from IG.Lib.LoadableScriptShellBase
abstract IResponseEvaluatorVectorSimple Simulator [get, protected set]
Simulator that is used to calculate vector response.
virtual bool SimulatorSuppressOutput [get, set]
A flag indicating whether simulators should suppress output or not, default is false.
virtual string ProjectName [get, set, protected set]
Name of the current project, used in some simulation and other interfaces.
virtual string SimulationName [get, set, protected set]
Name of the current simulation, used in some simulation and other interfaces.
string CastingRobertProjectName [get, set]
Project name for interfacing Robert Vertnik's casting simulator.
string CastingRobertSimulationName [get, set]
Simulation name for interfacing Robert Vertnik's casting simulator.
string CastingRobertRootDirectory [get, set]
Root directory for casting simulator.
SimCastingRobertFileManager CastingRobertFileManager [get, set]
File manager for interfacing Robert Vertnik's casting simulator. Lazy evaluation: The object is created when first accessed, if possible. For this, ProjectName, SimulationName and CastingRobertRootDirectory must be defined.
Properties inherited from IG.Lib.LoadableScriptOptShellBaseControllable
bool IsLoadable [get, set]
Either or not the script can be dynamically loaded.
bool IsRunnable [get, set]
Either or not the script can be run (some scripts only support other tasks).
Properties inherited from IG.Lib.LoadableScriptOptBase
StopWatch1 Timer [get]
virtual IRandomGenerator Random [get, protected set]
Random generator used by the current object.
virtual string OptimizationDirectory [get, set]
Optimization directory. This directory is a base directory for data used optimization and neural network - based approximation servers and for other directories that contain data for specific tasks.
virtual string WorkingDirectory [get, set]
Working directory. This directory is a base directory for data used by the script. It is usually obtained as parent directory of the optimization directory.
virtual IAnalysis Analysis [get, protected set]
Direct analysis object used in optimization. Initialized when first accessed with the embedded class, whose analysis function calls Analyse(...).
Properties inherited from IG.Lib.LoadableScriptBase
string EmbeddedCommandName [get, set]
Command that was used to launch the current embedded application script.
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
string[] InitializationArguments [get, set]
Arguments used by the initialization method. WARNING: arguments can only be set before initialization is performed. Initialization is performed either implicitly at the first call to the Run method or explicitly by calling the Initialize method.
virtual bool IsInitialized [get, protected set]
Whether the object has been initialized or not.
static int DefaultOutputLevel [get, set]
int OutputLevel [get, set]
Level of output to console produced by some operations of the current object.
virtual ICommandLineApplicationInterpreter Script_Interpreter [get, protected set]
Script's internal interpreter that takes care for execution of installed internal commands.
SortedList< string, string > Script_CommandHelpStrings [get]
Contains help strings associated with script commands installed on interpreter.
Properties inherited from IG.Lib.ILoadableScript
string EmbeddedCommandName [get, set]
Command that was used to launch the current embedded application script.
string[] InitializationArguments [get, set]
Arguments used by the initialization method.
bool IsInitialized [get]
Whether the object has been initialized or not.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Properties inherited from IG.Lib.ILoadableScriptC
bool IsLoadable [get, set]
Either or not the script can be dynamically loaded.
bool IsRunnable [get, set]
Either or not the script can be run (some scripts only support other tasks).
Properties inherited from IG.Num.INeuralModel
INeuralApproximator TrainedNetwork [get]
Traint artificial neural network.
InputOutputDataDefiniton NeuralDataDefinition [get]
Neural data definition.
Constructor & Destructor Documentation
NeuralTestScriptShellExt()
IG.Script.NeuralTestScriptShellExt.NeuralTestScriptShellExt () inline
Member Function Documentation
RunThis()
override string IG.Script.NeuralTestScriptShellExt.RunThis (string[] arguments) inline protected virtual
Runs action of the current object.
Parameters
arguments Command-line arguments of the action.
Reimplemented from IG.Script.LoadableScriptShellNeural.
References IG.Lib.LoadableScriptBase.Script_CommandHelp(), IG.Lib.LoadableScriptBase.Script_ContainsCommand(), IG.Lib.LoadableScriptBase.Script_PrintArguments(), and IG.Lib.LoadableScriptBase.Script_Run().
Script_AddCommands()
override void IG.Script.NeuralTestScriptShellExt.Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings) inline virtual
Adds commands to the internal interpreter.
Parameters
interpreter Interpreter where commands are executed.
helpStrings List containg help strings.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
The documentation for this class was generated from the following file:
shelldev/extensions_shell/ExtShellApp/00testscriptsext/tmp/NeuralTestScriptShellExt.cs