Doc: IGLib EXTENDED: NUnit.Framework.Api.FrameworkControllerTests Class Reference
NUnit.Framework.Api.FrameworkControllerTests Class Reference
Classes
class CallbackEventHandler
Public Member Functions
void CreateController ()
void ConstructController ()
void LoadTestsAction_GoodFile_ReturnsRunnableSuite ()
void LoadTestsAction_Assembly_ReturnsRunnableSuite ()
void LoadTestsAction_FileNotFound_ReturnsNonRunnableSuite ()
void LoadTestsAction_BadFile_ReturnsNonRunnableSuite ()
void ExploreTestsAction_AfterLoad_ReturnsRunnableSuite ()
void ExploreTestsAction_WithoutLoad_ThrowsInvalidOperationException ()
void ExploreTestsAction_FileNotFound_ReturnsNonRunnableSuite ()
void ExploreTestsAction_BadFile_ReturnsNonRunnableSuite ()
void CountTestsAction_AfterLoad_ReturnsCorrectCount ()
void CountTestsAction_WithoutLoad_ThrowsInvalidOperation ()
void CountTestsAction_FileNotFound_ReturnsZero ()
void CountTestsAction_BadFile_ReturnsZero ()
void RunTestsAction_AfterLoad_ReturnsRunnableSuite ()
void RunTestsAction_WithoutLoad_ReturnsError ()
void RunTestsAction_FileNotFound_ReturnsNonRunnableSuite ()
void RunTestsAction_BadFile_ReturnsNonRunnableSuite ()
void RunAsyncAction_AfterLoad_ReturnsRunnableSuite ()
void RunAsyncAction_WithoutLoad_ReturnsError ()
void RunAsyncAction_FileNotFound_ReturnsNonRunnableSuite ()
void RunAsyncAction_BadFile_ReturnsNonRunnableSuite ()
Static Private Member Functions
static string GetSkipReason (TNode result)
Private Attributes
IDictionary _settings = new Dictionary<string, object>()
FrameworkController _controller
ICallbackEventHandler _handler
Static Private Attributes
const string MOCK_ASSEMBLY_FILE = "mock-nunit-assembly.exe"
const string BAD_FILE = "mock-nunit-assembly.pdb"
const string MISSING_FILE = "junk.dll"
const string EMPTY_FILTER = "<filter/>"
static readonly string MOCK_ASSEMBLY_NAME = typeof(MockAssembly).GetTypeInfo().Assembly.FullName
static readonly string EXPECTED_NAME = MOCK_ASSEMBLY_FILE
static readonly string MOCK_ASSEMBLY_PATH = Path.Combine(TestContext.CurrentContext.TestDirectory, MOCK_ASSEMBLY_FILE)
Member Function Documentation
CreateController()
void NUnit.Framework.Api.FrameworkControllerTests.CreateController () inline
References NUnit.Framework.Api.FrameworkControllerTests._controller, NUnit.Framework.Api.FrameworkControllerTests._handler, NUnit.Framework.Api.FrameworkControllerTests._settings, NUnit.Framework.Api.FrameworkControllerTests.MOCK_ASSEMBLY_NAME, and NUnit.Framework.Api.FrameworkControllerTests.MOCK_ASSEMBLY_PATH.
ConstructController()
void NUnit.Framework.Api.FrameworkControllerTests.ConstructController () inline
References NUnit.Framework.Api.FrameworkControllerTests._controller, NUnit.Framework.Api.FrameworkControllerTests._settings, NUnit.Framework.Api.FrameworkController.AssemblyNameOrPath, NUnit.Framework.Api.FrameworkController.Builder, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Api.FrameworkControllerTests.MOCK_ASSEMBLY_NAME, NUnit.Framework.Api.FrameworkControllerTests.MOCK_ASSEMBLY_PATH, NUnit.Framework.Api.FrameworkController.Runner, NUnit.Framework.Is.SameAs(), NUnit.Framework.Api.FrameworkController.Settings, NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
LoadTestsAction_GoodFile_ReturnsRunnableSuite()
void NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_GoodFile_ReturnsRunnableSuite () inline
References NUnit.Framework.Api.FrameworkControllerTests._controller, NUnit.Framework.Api.FrameworkControllerTests._handler, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Api.FrameworkControllerTests.EXPECTED_NAME, NUnit.Framework.Interfaces.TNode.FromXml(), NUnit.Framework.Is.Not, NUnit.Tests.Assemblies.MockAssembly.Tests, and NUnit.Framework.Assert.That().
LoadTestsAction_Assembly_ReturnsRunnableSuite()
void NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_Assembly_ReturnsRunnableSuite () inline
References NUnit.Framework.Api.FrameworkControllerTests._controller, NUnit.Framework.Api.FrameworkControllerTests._handler, NUnit.Framework.Api.FrameworkControllerTests._settings, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Api.FrameworkControllerTests.EXPECTED_NAME, NUnit.Framework.Interfaces.TNode.FromXml(), NUnit.Framework.Is.Not, NUnit.Tests.Assemblies.MockAssembly.Tests, and NUnit.Framework.Assert.That().
LoadTestsAction_FileNotFound_ReturnsNonRunnableSuite()
void NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_FileNotFound_ReturnsNonRunnableSuite () inline
References NUnit.Framework.Api.FrameworkControllerTests._handler, NUnit.Framework.Api.FrameworkControllerTests._settings, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.TNode.FromXml(), NUnit.Framework.Api.FrameworkControllerTests.GetSkipReason(), NUnit.Framework.Api.FrameworkControllerTests.MISSING_FILE, NUnit.Framework.Contains.Substring(), and NUnit.Framework.Assert.That().
LoadTestsAction_BadFile_ReturnsNonRunnableSuite()
void NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_BadFile_ReturnsNonRunnableSuite () inline
References NUnit.Framework.Api.FrameworkControllerTests._handler, NUnit.Framework.Api.FrameworkControllerTests._settings, NUnit.Framework.Api.FrameworkControllerTests.BAD_FILE, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.TNode.FromXml(), NUnit.Framework.Api.FrameworkControllerTests.GetSkipReason(), NUnit.Framework.Contains.Substring(), and NUnit.Framework.Assert.That().
ExploreTestsAction_AfterLoad_ReturnsRunnableSuite()
void NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_AfterLoad_ReturnsRunnableSuite () inline
References NUnit.Framework.Api.FrameworkControllerTests._controller, NUnit.Framework.Api.FrameworkControllerTests._handler, NUnit.Framework.Api.FrameworkControllerTests.EMPTY_FILTER, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Api.FrameworkControllerTests.EXPECTED_NAME, NUnit.Framework.Interfaces.TNode.FromXml(), NUnit.Framework.Is.GreaterThan(), NUnit.Framework.Is.Not, NUnit.Tests.Assemblies.MockAssembly.Tests, and NUnit.Framework.Assert.That().
ExploreTestsAction_WithoutLoad_ThrowsInvalidOperationException()
void NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_WithoutLoad_ThrowsInvalidOperationException () inline
References NUnit.Framework.Api.FrameworkControllerTests._controller, NUnit.Framework.Api.FrameworkControllerTests._handler, NUnit.Framework.Api.FrameworkControllerTests.EMPTY_FILTER, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
ExploreTestsAction_FileNotFound_ReturnsNonRunnableSuite()
void NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_FileNotFound_ReturnsNonRunnableSuite () inline
References NUnit.Framework.Api.FrameworkControllerTests._handler, NUnit.Framework.Api.FrameworkControllerTests._settings, NUnit.Framework.Api.FrameworkControllerTests.EMPTY_FILTER, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.TNode.FromXml(), NUnit.Framework.Api.FrameworkControllerTests.GetSkipReason(), NUnit.Framework.Api.FrameworkControllerTests.MISSING_FILE, NUnit.Framework.Contains.Substring(), and NUnit.Framework.Assert.That().
ExploreTestsAction_BadFile_ReturnsNonRunnableSuite()
void NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_BadFile_ReturnsNonRunnableSuite () inline
References NUnit.Framework.Api.FrameworkControllerTests._handler, NUnit.Framework.Api.FrameworkControllerTests._settings, NUnit.Framework.Api.FrameworkControllerTests.BAD_FILE, NUnit.Framework.Api.FrameworkControllerTests.EMPTY_FILTER, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.TNode.FromXml(), NUnit.Framework.Api.FrameworkControllerTests.GetSkipReason(), NUnit.Framework.Contains.Substring(), and NUnit.Framework.Assert.That().
CountTestsAction_AfterLoad_ReturnsCorrectCount()
void NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_AfterLoad_ReturnsCorrectCount () inline
References NUnit.Framework.Api.FrameworkControllerTests._controller, NUnit.Framework.Api.FrameworkControllerTests._handler, NUnit.Framework.Api.FrameworkControllerTests.EMPTY_FILTER, NUnit.Framework.Is.EqualTo(), NUnit.Tests.Assemblies.MockAssembly.Tests, and NUnit.Framework.Assert.That().
CountTestsAction_WithoutLoad_ThrowsInvalidOperation()
void NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_WithoutLoad_ThrowsInvalidOperation () inline
References NUnit.Framework.Api.FrameworkControllerTests._controller, NUnit.Framework.Api.FrameworkControllerTests._handler, NUnit.Framework.Api.FrameworkControllerTests.EMPTY_FILTER, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
CountTestsAction_FileNotFound_ReturnsZero()
void NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_FileNotFound_ReturnsZero () inline
References NUnit.Framework.Api.FrameworkControllerTests._handler, NUnit.Framework.Api.FrameworkControllerTests._settings, NUnit.Framework.Api.FrameworkControllerTests.EMPTY_FILTER, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Api.FrameworkControllerTests.MISSING_FILE, and NUnit.Framework.Assert.That().
CountTestsAction_BadFile_ReturnsZero()
void NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_BadFile_ReturnsZero () inline
References NUnit.Framework.Api.FrameworkControllerTests._handler, NUnit.Framework.Api.FrameworkControllerTests._settings, NUnit.Framework.Api.FrameworkControllerTests.BAD_FILE, NUnit.Framework.Api.FrameworkControllerTests.EMPTY_FILTER, NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
RunTestsAction_AfterLoad_ReturnsRunnableSuite()
void NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite () inline
References NUnit.Framework.Api.FrameworkControllerTests._controller, NUnit.Framework.Api.FrameworkControllerTests._handler, NUnit.Framework.Api.FrameworkControllerTests.EMPTY_FILTER, NUnit.Framework.Is.EqualTo(), NUnit.Tests.Assemblies.MockAssembly.ErrorsAndFailures, NUnit.Framework.Api.FrameworkControllerTests.EXPECTED_NAME, NUnit.Framework.Interfaces.TNode.FromXml(), NUnit.Framework.Is.GreaterThan(), NUnit.Tests.Assemblies.MockAssembly.Inconclusive, NUnit.Framework.Is.Not, NUnit.Tests.Assemblies.MockAssembly.Skipped, NUnit.Tests.Assemblies.MockAssembly.Success, NUnit.Tests.Assemblies.MockAssembly.Tests, and NUnit.Framework.Assert.That().
RunTestsAction_WithoutLoad_ReturnsError()
void NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_WithoutLoad_ReturnsError () inline
References NUnit.Framework.Api.FrameworkControllerTests._controller, NUnit.Framework.Api.FrameworkControllerTests._handler, NUnit.Framework.Api.FrameworkControllerTests.EMPTY_FILTER, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
RunTestsAction_FileNotFound_ReturnsNonRunnableSuite()
void NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_FileNotFound_ReturnsNonRunnableSuite () inline
References NUnit.Framework.Api.FrameworkControllerTests._handler, NUnit.Framework.Api.FrameworkControllerTests._settings, NUnit.Framework.Api.FrameworkControllerTests.EMPTY_FILTER, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.TNode.FromXml(), NUnit.Framework.Api.FrameworkControllerTests.GetSkipReason(), NUnit.Framework.Api.FrameworkControllerTests.MISSING_FILE, NUnit.Framework.Contains.Substring(), and NUnit.Framework.Assert.That().
RunTestsAction_BadFile_ReturnsNonRunnableSuite()
void NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_BadFile_ReturnsNonRunnableSuite () inline
References NUnit.Framework.Api.FrameworkControllerTests._handler, NUnit.Framework.Api.FrameworkControllerTests._settings, NUnit.Framework.Api.FrameworkControllerTests.BAD_FILE, NUnit.Framework.Api.FrameworkControllerTests.EMPTY_FILTER, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.TNode.FromXml(), NUnit.Framework.Api.FrameworkControllerTests.GetSkipReason(), NUnit.Framework.Contains.Substring(), and NUnit.Framework.Assert.That().
RunAsyncAction_AfterLoad_ReturnsRunnableSuite()
void NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_AfterLoad_ReturnsRunnableSuite () inline
References NUnit.Framework.Api.FrameworkControllerTests._controller, NUnit.Framework.Api.FrameworkControllerTests._handler, and NUnit.Framework.Api.FrameworkControllerTests.EMPTY_FILTER.
RunAsyncAction_WithoutLoad_ReturnsError()
void NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_WithoutLoad_ReturnsError () inline
References NUnit.Framework.Api.FrameworkControllerTests._controller, NUnit.Framework.Api.FrameworkControllerTests._handler, NUnit.Framework.Api.FrameworkControllerTests.EMPTY_FILTER, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
RunAsyncAction_FileNotFound_ReturnsNonRunnableSuite()
void NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_FileNotFound_ReturnsNonRunnableSuite () inline
References NUnit.Framework.Api.FrameworkControllerTests._handler, NUnit.Framework.Api.FrameworkControllerTests._settings, NUnit.Framework.Api.FrameworkControllerTests.EMPTY_FILTER, and NUnit.Framework.Api.FrameworkControllerTests.MISSING_FILE.
RunAsyncAction_BadFile_ReturnsNonRunnableSuite()
void NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_BadFile_ReturnsNonRunnableSuite () inline
References NUnit.Framework.Api.FrameworkControllerTests._handler, NUnit.Framework.Api.FrameworkControllerTests._settings, NUnit.Framework.Api.FrameworkControllerTests.BAD_FILE, and NUnit.Framework.Api.FrameworkControllerTests.EMPTY_FILTER.
GetSkipReason()
static string NUnit.Framework.Api.FrameworkControllerTests.GetSkipReason (TNode result) inline static private
References NUnit.Framework.Interfaces.TNode.Attributes, NUnit.Framework.Interfaces.TNode.SelectSingleNode(), and NUnit.Framework.Internal.PropertyNames.SkipReason.
Referenced by NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_BadFile_ReturnsNonRunnableSuite(), and NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_FileNotFound_ReturnsNonRunnableSuite().
Member Data Documentation
MOCK_ASSEMBLY_FILE
const string NUnit.Framework.Api.FrameworkControllerTests.MOCK_ASSEMBLY_FILE = "mock-nunit-assembly.exe" static private
BAD_FILE
const string NUnit.Framework.Api.FrameworkControllerTests.BAD_FILE = "mock-nunit-assembly.pdb" static private
Referenced by NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_BadFile_ReturnsZero(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_BadFile_ReturnsNonRunnableSuite(), and NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_BadFile_ReturnsNonRunnableSuite().
MISSING_FILE
const string NUnit.Framework.Api.FrameworkControllerTests.MISSING_FILE = "junk.dll" static private
Referenced by NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_FileNotFound_ReturnsZero(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_FileNotFound_ReturnsNonRunnableSuite(), and NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_FileNotFound_ReturnsNonRunnableSuite().
EMPTY_FILTER
const string NUnit.Framework.Api.FrameworkControllerTests.EMPTY_FILTER = "<filter/>" static private
Referenced by NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_AfterLoad_ReturnsCorrectCount(), NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_BadFile_ReturnsZero(), NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_FileNotFound_ReturnsZero(), NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_WithoutLoad_ThrowsInvalidOperation(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_WithoutLoad_ThrowsInvalidOperationException(), NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_WithoutLoad_ReturnsError(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_FileNotFound_ReturnsNonRunnableSuite(), and NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_WithoutLoad_ReturnsError().
MOCK_ASSEMBLY_NAME
readonly string NUnit.Framework.Api.FrameworkControllerTests.MOCK_ASSEMBLY_NAME = typeof(MockAssembly).GetTypeInfo().Assembly.FullName static private
Referenced by NUnit.Framework.Api.FrameworkControllerTests.ConstructController(), and NUnit.Framework.Api.FrameworkControllerTests.CreateController().
EXPECTED_NAME
readonly string NUnit.Framework.Api.FrameworkControllerTests.EXPECTED_NAME = MOCK_ASSEMBLY_FILE static private
Referenced by NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_Assembly_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_GoodFile_ReturnsRunnableSuite(), and NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite().
MOCK_ASSEMBLY_PATH
readonly string NUnit.Framework.Api.FrameworkControllerTests.MOCK_ASSEMBLY_PATH = Path.Combine(TestContext.CurrentContext.TestDirectory, MOCK_ASSEMBLY_FILE) static private
Referenced by NUnit.Framework.Api.FrameworkControllerTests.ConstructController(), and NUnit.Framework.Api.FrameworkControllerTests.CreateController().
_settings
IDictionary NUnit.Framework.Api.FrameworkControllerTests._settings = new Dictionary<string, object>() private
Referenced by NUnit.Framework.Api.FrameworkControllerTests.ConstructController(), NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_BadFile_ReturnsZero(), NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_FileNotFound_ReturnsZero(), NUnit.Framework.Api.FrameworkControllerTests.CreateController(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_Assembly_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_BadFile_ReturnsNonRunnableSuite(), and NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_FileNotFound_ReturnsNonRunnableSuite().
_controller
FrameworkController NUnit.Framework.Api.FrameworkControllerTests._controller private
Referenced by NUnit.Framework.Api.FrameworkControllerTests.ConstructController(), NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_AfterLoad_ReturnsCorrectCount(), NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_WithoutLoad_ThrowsInvalidOperation(), NUnit.Framework.Api.FrameworkControllerTests.CreateController(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_WithoutLoad_ThrowsInvalidOperationException(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_Assembly_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_GoodFile_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_WithoutLoad_ReturnsError(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite(), and NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_WithoutLoad_ReturnsError().
_handler
ICallbackEventHandler NUnit.Framework.Api.FrameworkControllerTests._handler private
Referenced by NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_AfterLoad_ReturnsCorrectCount(), NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_BadFile_ReturnsZero(), NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_FileNotFound_ReturnsZero(), NUnit.Framework.Api.FrameworkControllerTests.CountTestsAction_WithoutLoad_ThrowsInvalidOperation(), NUnit.Framework.Api.FrameworkControllerTests.CreateController(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_WithoutLoad_ThrowsInvalidOperationException(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_Assembly_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_GoodFile_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunAsyncAction_WithoutLoad_ReturnsError(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_FileNotFound_ReturnsNonRunnableSuite(), and NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_WithoutLoad_ReturnsError().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Api/FrameworkControllerTests.cs