Doc: IGLib EXTENDED: NeuronDotNet.Core.SOM.NeighborhoodFunctions.MexicanHatFunction Class Reference
NeuronDotNet.Core.SOM.NeighborhoodFunctions.MexicanHatFunction Class Reference
Mexican Hat Neighborhood Function is the normalized second derivative of a Gaussian function. It is a continuous function with neighborhood value decreasing from unity at the winner to a negative value at a certain point (forming an inhibitory influence) and then gradually increasing to zero.
Public Member Functions
MexicanHatFunction (int learningRadius)
Creates a new Mexican Hat Neighborhood Function
MexicanHatFunction (SerializationInfo info, StreamingContext context)
Deserialization Constructor
void GetObjectData (SerializationInfo info, StreamingContext context)
Populates the serialization info with the data needed to serialize the neighborhood function
void EvaluateNeighborhood (KohonenLayer layer, int currentIteration, int trainingEpochs)
Determines the neighborhood of every neuron in the given Kohonen layer with respect to winner neuron using Mexican Hat function
Properties
double Sigma [get]
Gets the value of sigma
Private Attributes
readonly double sigma = 0d
Detailed Description
Mexican Hat Neighborhood Function is the normalized second derivative of a Gaussian function. It is a continuous function with neighborhood value decreasing from unity at the winner to a negative value at a certain point (forming an inhibitory influence) and then gradually increasing to zero.
Constructor & Destructor Documentation
MexicanHatFunction() [1/2]
NeuronDotNet.Core.SOM.NeighborhoodFunctions.MexicanHatFunction.MexicanHatFunction (int learningRadius) inline
Creates a new Mexican Hat Neighborhood Function
Parameters
learningRadius Initial Learning Radius
MexicanHatFunction() [2/2]
NeuronDotNet.Core.SOM.NeighborhoodFunctions.MexicanHatFunction.MexicanHatFunction (SerializationInfo info, StreamingContext context) inline
Deserialization Constructor
Parameters
info Serialization information to deserialize and obtain the data
context Serialization context to use
Exceptions
ArgumentNullException If info is null
References NeuronDotNet.Core.Helper.ValidateNotNull().
Member Function Documentation
GetObjectData()
void NeuronDotNet.Core.SOM.NeighborhoodFunctions.MexicanHatFunction.GetObjectData (SerializationInfo info, StreamingContext context) inline
Populates the serialization info with the data needed to serialize the neighborhood function
Parameters
info The serialization info to populate the data with
context The serialization context to use
Exceptions
ArgumentNullException If info is null
References NeuronDotNet.Core.SOM.NeighborhoodFunctions.MexicanHatFunction.sigma, and NeuronDotNet.Core.Helper.ValidateNotNull().
EvaluateNeighborhood()
void NeuronDotNet.Core.SOM.NeighborhoodFunctions.MexicanHatFunction.EvaluateNeighborhood (KohonenLayer layer, int currentIteration, int trainingEpochs) inline
Determines the neighborhood of every neuron in the given Kohonen layer with respect to winner neuron using Mexican Hat function
Parameters
layer The Kohonen Layer containing neurons
currentIteration Current training iteration
trainingEpochs Total number of training epochs
Exceptions
ArgumentNullException If layer is null
ArgumentException If trainingEpochs is zero or negative
ArgumentOutOfRangeException If currentIteration is negative or, if it is not less than trainingEpochs
Implements NeuronDotNet.Core.SOM.INeighborhoodFunction.
References NeuronDotNet.Core.SOM.PositionNeuron.Coordinate, NeuronDotNet.Core.SOM.NeighborhoodFunctions.MexicanHatFunction.sigma, NeuronDotNet.Core.SOM.KohonenLayer.Size, NeuronDotNet.Core.Helper.ValidateNotNull(), NeuronDotNet.Core.Helper.ValidatePositive(), and NeuronDotNet.Core.SOM.KohonenLayer.Winner.
Member Data Documentation
sigma
readonly double NeuronDotNet.Core.SOM.NeighborhoodFunctions.MexicanHatFunction.sigma = 0d private
Referenced by NeuronDotNet.Core.SOM.NeighborhoodFunctions.MexicanHatFunction.EvaluateNeighborhood(), and NeuronDotNet.Core.SOM.NeighborhoodFunctions.MexicanHatFunction.GetObjectData().
Property Documentation
Sigma
double NeuronDotNet.Core.SOM.NeighborhoodFunctions.MexicanHatFunction.Sigma get
Gets the value of sigma
Initial value of sigma
The documentation for this class was generated from the following file:
shelldev/lib/externalextended/NeuronDotNetGPL/source/Core/SOM/NeighborhoodFunctions/MexicanHatFunction.cs