Doc: IGLib EXTENDED: AForge.Video.VFW.AVIReader Class Reference
AForge.Video.VFW.AVIReader Class Reference
AVI files reading using Video for Windows.
Public Member Functions
AVIReader ()
Initializes a new instance of the AVIReader class.
void Dispose ()
Dispose the object.
void Open (string fileName)
Open AVI file.
void Close ()
Close video file.
Bitmap GetNextFrame ()
Get next frame of opened video stream.
Protected Member Functions
virtual void Dispose (bool disposing)
Dispose the object.
Properties
int Width [get]
Width of video frames.
int Height [get]
Height of video frames.
int? Position [get, set]
Current position in video stream.
int Start [get]
Starting position of video stream.
int Length [get]
Video stream length.
float FrameRate [get]
Desired playing frame rate.
string Codec [get]
Codec used for video compression.
Private Member Functions
~AVIReader ()
Destroys the instance of the AVIReader class.
Private Attributes
IntPtr file
IntPtr stream
IntPtr getFrame
int width
int height
int position
int start
int length
float rate
string codec
object sync = new object()
Detailed Description
AVI files reading using Video for Windows.
The class allows to read AVI files using Video for Windows API.
Sample usage:
// instantiate AVI reader
AVIReader reader = new AVIReader();
// open video file
reader.Open("test.avi");
// read the video file
while (reader.Position - reader.Start < reader.Length)
{
    // get next frame
    Bitmap image = reader.GetNextFrame( );
    // .. process the frame somehow or display it
}
reader.Close();
Constructor & Destructor Documentation
AVIReader()
AForge.Video.VFW.AVIReader.AVIReader () inline
Initializes a new instance of the AVIReader class.
Initializes Video for Windows library.
~AVIReader()
AForge.Video.VFW.AVIReader.~AVIReader () inline private
Destroys the instance of the AVIReader class.
References AForge.Video.VFW.AVIReader.Dispose().
Member Function Documentation
Dispose() [1/2]
void AForge.Video.VFW.AVIReader.Dispose () inline
Dispose the object.
Frees unmanaged resources used by the object. The object becomes unusable after that.
Referenced by AForge.Video.VFW.AVIFileVideoSource.WorkerThread(), and AForge.Video.VFW.AVIReader.~AVIReader().
Dispose() [2/2]
virtual void AForge.Video.VFW.AVIReader.Dispose (bool disposing) inline protected virtual
Dispose the object.
Parameters
disposing Indicates if disposing was initiated manually.
References AForge.Video.VFW.AVIReader.Close().
Open()
void AForge.Video.VFW.AVIReader.Open (string fileName) inline
Open AVI file.
Parameters
fileName AVI file name to open.
The method opens a video file and prepares the stream and decoder for reading video frames with the help of GetNextFrame method.
Exceptions
System.IO.IOException Failed opening the specified file.
VideoException A error occurred while opening the video file. See exception message.
References AForge.Video.VFW.AVIReader.Close(), AForge.Video.VFW.AVIReader.codec, AForge.Video.VFW.AVIReader.file, AForge.Video.VFW.AVIReader.getFrame, AForge.Video.VFW.AVIReader.height, AForge.Video.VFW.AVIReader.length, AForge.Video.VFW.AVIReader.position, AForge.Video.VFW.AVIReader.rate, AForge.Video.VFW.AVIReader.start, AForge.Video.VFW.AVIReader.stream, AForge.Video.VFW.AVIReader.sync, and AForge.Video.VFW.AVIReader.width.
Referenced by AForge.Video.VFW.AVIFileVideoSource.WorkerThread().
Close()
void AForge.Video.VFW.AVIReader.Close () inline
Close video file.
References AForge.Video.VFW.AVIReader.file, AForge.Video.VFW.AVIReader.getFrame, AForge.Video.VFW.AVIReader.stream, and AForge.Video.VFW.AVIReader.sync.
Referenced by AForge.Video.VFW.AVIReader.Dispose(), and AForge.Video.VFW.AVIReader.Open().
GetNextFrame()
Bitmap AForge.Video.VFW.AVIReader.GetNextFrame () inline
Get next frame of opened video stream.
Returns
Returns next frame as a bitmap.
The method reads and returns the next video frame in the opened video stream at the position, which is set in Position property.
Exceptions
System.IO.IOException Thrown if no video file was open.
VideoException A error occurred while reading next video frame. See exception message.
References AForge.Video.VFW.AVIReader.file, AForge.Video.VFW.AVIReader.getFrame, AForge.Video.VFW.AVIReader.height, AForge.Video.VFW.AVIReader.position, AForge.Video.VFW.AVIReader.sync, and AForge.Video.VFW.AVIReader.width.
Referenced by AForge.Video.VFW.AVIFileVideoSource.WorkerThread().
Member Data Documentation
file
IntPtr AForge.Video.VFW.AVIReader.file private
Referenced by AForge.Video.VFW.AVIReader.Close(), AForge.Video.VFW.AVIReader.GetNextFrame(), and AForge.Video.VFW.AVIReader.Open().
stream
IntPtr AForge.Video.VFW.AVIReader.stream private
Referenced by AForge.Video.VFW.AVIReader.Close(), and AForge.Video.VFW.AVIReader.Open().
getFrame
IntPtr AForge.Video.VFW.AVIReader.getFrame private
Referenced by AForge.Video.VFW.AVIReader.Close(), AForge.Video.VFW.AVIReader.GetNextFrame(), and AForge.Video.VFW.AVIReader.Open().
width
int AForge.Video.VFW.AVIReader.width private
Referenced by AForge.Video.VFW.AVIReader.GetNextFrame(), and AForge.Video.VFW.AVIReader.Open().
height
int AForge.Video.VFW.AVIReader.height private
Referenced by AForge.Video.VFW.AVIReader.GetNextFrame(), and AForge.Video.VFW.AVIReader.Open().
position
int AForge.Video.VFW.AVIReader.position private
Referenced by AForge.Video.VFW.AVIReader.GetNextFrame(), and AForge.Video.VFW.AVIReader.Open().
start
int AForge.Video.VFW.AVIReader.start private
Referenced by AForge.Video.VFW.AVIReader.Open().
length
int AForge.Video.VFW.AVIReader.length private
Referenced by AForge.Video.VFW.AVIReader.Open().
rate
float AForge.Video.VFW.AVIReader.rate private
Referenced by AForge.Video.VFW.AVIReader.Open().
codec
string AForge.Video.VFW.AVIReader.codec private
Referenced by AForge.Video.VFW.AVIReader.Open().
sync
object AForge.Video.VFW.AVIReader.sync = new object() private
Referenced by AForge.Video.VFW.AVIReader.Close(), AForge.Video.VFW.AVIReader.GetNextFrame(), and AForge.Video.VFW.AVIReader.Open().
Property Documentation
Width
int AForge.Video.VFW.AVIReader.Width get
Width of video frames.
The property specifies the width of video frames within the opened video file.
Height
int AForge.Video.VFW.AVIReader.Height get
Height of video frames.
The property specifies the height of video frames within the opened video file.
Position
int? AForge.Video.VFW.AVIReader.Position get set
Current position in video stream.
Setting position outside of video range, will lead to reseting position to the start.
Referenced by AForge.Video.VFW.AVIFileVideoSource.WorkerThread().
Start
int AForge.Video.VFW.AVIReader.Start get
Starting position of video stream.
Referenced by AForge.Video.VFW.AVIFileVideoSource.WorkerThread().
Length
int AForge.Video.VFW.AVIReader.Length get
Video stream length.
Referenced by AForge.Video.VFW.AVIFileVideoSource.WorkerThread().
FrameRate
float AForge.Video.VFW.AVIReader.FrameRate get
Desired playing frame rate.
The property specifies the frame rate, which should be used to play the opened video file.
Referenced by AForge.Video.VFW.AVIFileVideoSource.WorkerThread().
Codec
string AForge.Video.VFW.AVIReader.Codec get
Codec used for video compression.
The property tells about which codec was used to encode the opened video file.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Video.VFW/AVIReader.cs