Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGELQF Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGELQF Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGELQF (DGELQ2 dgelq2, DLARFB dlarfb, DLARFT dlarft, XERBLA xerbla, ILAENV ilaenv)
DGELQF ()
void Run (int M, int N, ref double[] A, int offset_a, int LDA, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
DGELQ2 _dgelq2
DLARFB _dlarfb
DLARFT _dlarft
XERBLA _xerbla
ILAENV _ilaenv
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGELQF computes an LQ factorization of a real M-by-N matrix A: A = L * Q.
/summary>
Constructor & Destructor Documentation
DGELQF() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGELQF.DGELQF (DGELQ2 dgelq2, DLARFB dlarfb, DLARFT dlarft, XERBLA xerbla, ILAENV ilaenv) inline
DGELQF() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGELQF.DGELQF () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGELQF.Run (int M, int N, ref double[] A, int offset_a, int LDA, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DGELQF computes an LQ factorization of a real M-by-N matrix A: A = L * Q.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the M-by-N matrix A. On exit, the elements on and below the diagonal of the array contain the m-by-min(m,n) lower trapezoidal matrix L (L is lower triangular if m .LE. n); the elements above the diagonal, with the array TAU, represent the orthogonal matrix Q as a product of elementary reflectors (see Further Details). /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
TAU (output) DOUBLE PRECISION array, dimension (min(M,N)) The scalar factors of the elementary reflectors (see Further Details). /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. max(1,M). For optimum performance LWORK .GE. M*NB, where NB is the optimal blocksize.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELQ2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFT.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLARFB.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGELS.Run(), DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELSD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run().
Member Data Documentation
_dgelq2
DGELQ2 DotNumerics.LinearAlgebra.CSLapack.DGELQF._dgelq2 private
_dlarfb
DLARFB DotNumerics.LinearAlgebra.CSLapack.DGELQF._dlarfb private
_dlarft
DLARFT DotNumerics.LinearAlgebra.CSLapack.DGELQF._dlarft private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGELQF._xerbla private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DGELQF._ilaenv private
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgelqf.cs