Doc: IGLib EXTENDED: IG.Lib.ILoadableScript Interface Reference
IG.Lib.ILoadableScript Interface Reference
Interface for classes that can be dynamically loadeded from scripts and run, which provides functionality of dynamic scripting. It is recommendable to derive all such classes from the LoadableScriptBase base class.
Inherited by IG.App.AppHashShell, IG.Lib.ILoadableScriptC, IG.Lib.LoadableScriptBase, IG.Lib.LoadableScriptOptBase, IG.Script.AppBase, IG.Script.AppEmbeddedCryptoIGShell, IG.Script.AppExtBase, IG.Script.AppFerdo, IG.Script.AppIgorForFerdo, IG.Script.AppIgorGresovnik, IG.Script.AppIGShell, IG.Script.AppMarkoEmbeddedTest, IG.Script.AppMarkoPetek, IG.Script.AppMarkoPetekDerivedScript, IG.Script.AppMarkoPetekDerivedScriptExt, IG.Script.AppMarkoPetekExt, IG.Script.AppShellExt, IG.Script.AppShellExtExt, IG.Script.AppTestShell, IG.Script.AppTestShellExt, IG.Script.LoadableScriptExample, IG.Script.LoadableScriptScalarFunctionCreator, IG.Script.LoadableScriptShellNeural, IG.Script.LoadableScriptShellNeuralBase, IG.Script.LoadableScriptShellNeuralIT, IG.Script.LoadableScriptShellNeuralITOriginalBase, IG.Script.LoadableScriptSpecialFunctionBase, IG.Script.NeuralTestScript, IG.Script.NeuralTestScriptShellExt, IG.Script.S_11_10_clanek_neural_00, IG.Script.S_11_10_Clanek_Neural_Base, IG.Script.S_12_01_Paper_NeuralOptCasting_00, IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00, IG.Script.S_12_02_paper_neural_process_chain_model, IG.Script.S_12_03_paper_gk, IG.Script.S_12_09_jmatpro, IG.Script.S_13_5_Convection, IG.Script.S_TestExt1, IG.Script.S_TestExt2, IG.Script.S_TestExt3, IG.Script.S_TestNeural1, IG.Script.S_TestNeural2, IG.Script.S_TestNeural3, IG.Script.S_TestOpt1, IG.Script.S_TestOpt2, IG.Script.S_TestOpt3, IG.Script.S_TestShellExt1, IG.Script.Scrip_OdeChem, IG.Script.Script2, IG.Script.Script_11_10_clanek_neural_01, IG.Script.Script_Examples, IG.Script.Script_Misc, IG.Script.Script_Numeric, IG.Script.Script_Optimization, IG.Script.ScriptAppIgBaseExt, IG.Script.ScriptAppIGShell, IG.Script.ScriptExtExamples, IG.Script.ScriptExtExamplesExt, IG.Script.ScriptExtFormats, IG.Script.ScriptExtGraphics3d, IG.Script.ScriptExtNumeric, IG.Script.ScriptExtTemplate, IG.Script.ScriptGraphics2dBase, IG.Script.ScriptGraphics3DBase, IG.Script.ScriptNeuralExamples, IG.Script.ScriptNeuralTemplate, IG.Script.ScriptOptTemplate, IG.Script.ScriptOptTemplateExt, IG.Script.ScriptShellNeuralWithSimulatorManagers, IG.Script.ScritpRealFunctionExample, IG.Script.ScritpScalarFunctionExample, IG.Script.TestClass1, and IG.Script.TestIglibExt_ToDelete.
Public Member Functions
string Run (string[] arguments)
Runs the executable method of the object.
void Initialize (string[] arguments)
Initializes the current object.
Properties
string EmbeddedCommandName [get, set]
Command that was used to launch the current embedded application script.
string[] InitializationArguments [get, set]
Arguments used by the initialization method.
bool IsInitialized [get]
Whether the object has been initialized or not.
Detailed Description
Interface for classes that can be dynamically loadeded from scripts and run, which provides functionality of dynamic scripting. It is recommendable to derive all such classes from the LoadableScriptBase base class.
$A Igor Jul09 May10;
Member Function Documentation
Run()
string IG.Lib.ILoadableScript.Run (string[] arguments)
Runs the executable method of the object.
Parameters
arguments String arguments to the executable method.
Returns
Implemented in IG.Lib.LoadableScriptBase.
Referenced by IG.Script.AppIGShell.AppEmbeddedCryptoIGS(), IG.Script.ScriptAppIgBaseExt.AppEmbeddedCryptoIGS(), IG.Script.AppIGShell.AppEmbeddedFerdo(), IG.Script.ScriptAppIGShell.AppEmbeddedFerdo(), IG.Script.AppMarkoPetek.AppEmbeddedTest(), IG.App.AppHashShell.AppEmbeddedTest(), IG.Lib.CommandLineApplicationInterpreter.CmdRunInternalScriptClass(), IG.Test.Program_Marko_Diploma.Main(), IG.Test.Program_Marko_Ext.Main(), IG.App.ProgramHashShell.MainHashShell(), IG.App.ApplicationIgShellBase.Run(), IG.App.ApplicationIgShell.Run(), IG.Lib.ScriptLoaderBase.Run(), IG.Lib.ScriptLoaderBase.RunCode(), IG.Lib.LoadableScriptInterpreterBase.RunCommand(), IG.Lib.ScriptLoaderBase.RunFile(), IG.Test.ProgramTestIgor.TestMain(), TestOpt.IGLibShellExtMainProgram.TestMain(), TestOpt.IGLibShellMainProgram.TestMain(), IG.Test.ProgramTestIgorIT.TestMain(), and IG.Script.AppEmbeddedCryptoIGShell.WrappedScriptAppBase().
Initialize()
void IG.Lib.ILoadableScript.Initialize (string[] arguments)
Initializes the current object.
Parameters
arguments Arguments of initialization.
Implemented in IG.Lib.LoadableScriptBase.
Property Documentation
EmbeddedCommandName
string IG.Lib.ILoadableScript.EmbeddedCommandName get set
Command that was used to launch the current embedded application script.
Referenced by IG.Script.AppIGShell.AppEmbeddedCryptoIGS(), IG.Script.ScriptAppIgBaseExt.AppEmbeddedCryptoIGS(), IG.Script.AppEmbeddedCryptoIGShell.AppEmbeddedCryptoIGShell(), IG.Script.AppIGShell.AppEmbeddedFerdo(), IG.Script.ScriptAppIGShell.AppEmbeddedFerdo(), IG.Script.AppMarkoPetek.AppEmbeddedTest(), IG.App.AppHashShell.AppEmbeddedTest(), IG.Script.AppFerdo.AppFerdo(), IG.Script.AppMarkoEmbeddedTest.AppMarkoEmbeddedTest(), IG.Script.AppMarkoEmbeddedTest.AppPrintArguments(), IG.Script.AppEmbeddedCryptoIGShell.AppTestCrypto(), IG.Script.AppMarkoEmbeddedTest.AppTestExample(), and IG.Script.AppEmbeddedCryptoIGShell.WrappedScriptAppBase().
InitializationArguments
string [] IG.Lib.ILoadableScript.InitializationArguments get set
Arguments used by the initialization method.
Referenced by IG.Lib.CommandLineApplicationInterpreter.CmdRunInternalScriptClass(), IG.Lib.ScriptLoaderBase.CreateLoadableObject(), IG.Test.ProgramTestIgor.TestMain(), TestOpt.IGLibShellExtMainProgram.TestMain(), TestOpt.IGLibShellMainProgram.TestMain(), and IG.Test.ProgramTestIgorIT.TestMain().
IsInitialized
bool IG.Lib.ILoadableScript.IsInitialized get
Whether the object has been initialized or not.
The documentation for this interface was generated from the following file:
iglib/igbase/interpreters/scriptloader/LoadableScriptBase.cs