Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGEHD2 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGEHD2 Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGEHD2 (DLARF dlarf, DLARFG dlarfg, XERBLA xerbla)
DGEHD2 ()
void Run (int N, int ILO, int IHI, ref double[] A, int offset_a, int LDA, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
DLARF _dlarf
DLARFG _dlarfg
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGEHD2 reduces a real general matrix A to upper Hessenberg form H by an orthogonal similarity transformation: Q' * A * Q = H .
/summary>
Constructor & Destructor Documentation
DGEHD2() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGEHD2.DGEHD2 (DLARF dlarf, DLARFG dlarfg, XERBLA xerbla) inline
DGEHD2() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGEHD2.DGEHD2 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGEHD2.Run (int N, int ILO, int IHI, ref double[] A, int offset_a, int LDA, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
DGEHD2 reduces a real general matrix A to upper Hessenberg form H by an orthogonal similarity transformation: Q' * A * Q = H .
/summary>
Parameters
N (input) INTEGER The order of the matrix A. N .GE. 0. /param>
Parameters
ILO (input) INTEGER /param>
Parameters
IHI (input) INTEGER It is assumed that A is already upper triangular in rows and columns 1:ILO-1 and IHI+1:N. ILO and IHI are normally set by a previous call to DGEBAL; otherwise they should be set to 1 and N respectively. See Further Details. 1 .LE. ILO .LE. IHI .LE. max(1,N). /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the n by n general matrix to be reduced. On exit, the upper triangle and the first subdiagonal of A are overwritten with the upper Hessenberg matrix H, and the elements below the first subdiagonal, with the array TAU, represent the orthogonal matrix Q as a product of elementary reflectors. See Further Details. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,N). /param>
Parameters
TAU (output) DOUBLE PRECISION array, dimension (N-1) The scalar factors of the elementary reflectors (see Further Details). /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (N) /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. /param>
References DotNumerics.LinearAlgebra.CSLapack.DGEHD2.ONE, DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARF.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEHRD.Run().
Member Data Documentation
_dlarf
DLARF DotNumerics.LinearAlgebra.CSLapack.DGEHD2._dlarf private
_dlarfg
DLARFG DotNumerics.LinearAlgebra.CSLapack.DGEHD2._dlarfg private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGEHD2._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGEHD2.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEHD2.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgehd2.cs