Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGEQRF Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGEQRF Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGEQRF (DGEQR2 dgeqr2, DLARFB dlarfb, DLARFT dlarft, XERBLA xerbla, ILAENV ilaenv)
DGEQRF ()
void Run (int M, int N, ref double[] A, int offset_a, int LDA, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
DGEQR2 _dgeqr2
DLARFB _dlarfb
DLARFT _dlarft
XERBLA _xerbla
ILAENV _ilaenv
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGEQRF computes a QR factorization of a real M-by-N matrix A: A = Q * R.
/summary>
Constructor & Destructor Documentation
DGEQRF() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGEQRF.DGEQRF (DGEQR2 dgeqr2, DLARFB dlarfb, DLARFT dlarft, XERBLA xerbla, ILAENV ilaenv) inline
DGEQRF() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGEQRF.DGEQRF () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGEQRF.Run (int M, int N, ref double[] A, int offset_a, int LDA, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DGEQRF computes a QR factorization of a real M-by-N matrix A: A = Q * R.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the M-by-N matrix A. On exit, the elements on and above the diagonal of the array contain the min(M,N)-by-N upper trapezoidal matrix R (R is upper triangular if m .GE. n); the elements below the diagonal, with the array TAU, represent the orthogonal matrix Q as a product of min(m,n) elementary reflectors (see Further Details). /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
TAU (output) DOUBLE PRECISION array, dimension (min(M,N)) The scalar factors of the elementary reflectors (see Further Details). /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. max(1,N). For optimum performance LWORK .GE. N*NB, where NB is the optimal blocksize.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFT.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLARFB.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEQP3.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGRQF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGQRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELS.Run(), DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELSD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run().
Member Data Documentation
_dgeqr2
DGEQR2 DotNumerics.LinearAlgebra.CSLapack.DGEQRF._dgeqr2 private
_dlarfb
DLARFB DotNumerics.LinearAlgebra.CSLapack.DGEQRF._dlarfb private
_dlarft
DLARFT DotNumerics.LinearAlgebra.CSLapack.DGEQRF._dlarft private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGEQRF._xerbla private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DGEQRF._ilaenv private
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgeqrf.cs