Doc: IGLib EXTENDED: IG.Gr3d.VtkControlWin Class Reference
IG.Gr3d.VtkControlWin Class Reference
Control for presenting VTK graphics, intended for use in stand-alone windows.
Public Member Functions
VtkControlWin ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
VtkControlBase VtkControl [get]
Gets the control of type VtkControlBase through which VTK functionality is controlled.
Kitware.VTK.RenderWindowControl VtkRenderWindowControl [get]
VTK's control that is actually used for rendering graphics and through which VTK can be interacted directly.
Properties inherited from IG.Gr3d.IVtkFormContainerGen< Kitware.VTK.RenderWindowControl >
VtkControlBase VtkControl [get]
Base windows forms control through which the basic VTK functionality and all additional features can be accessed.
VtkControlType VtkRenderWindowControl [get]
VTK's control that is actually used for rendering graphics and through which VTK can be interacted directly.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
VtkControlBase _vtkControl
Kitware.VTK.RenderWindowControl _vtkRenderWindowControl
System.ComponentModel.IContainer components = null
Required designer variable.
IG.Gr3d.VtkControlBase vtkControlBase1
Graph3dManipulatorBasic graph3dManipulatorBasic1
Detailed Description
Control for presenting VTK graphics, intended for use in stand-alone windows.
This control contains the VtkControlBase control with sme additional controls, e.g. for closing the containing toplevel window.
$A Igor xx May13;
Constructor & Destructor Documentation
VtkControlWin()
IG.Gr3d.VtkControlWin.VtkControlWin () inline
References IG.Gr3d.VtkControlWin.graph3dManipulatorBasic1, IG.Gr3d.VtkControlWin.InitializeComponent(), IG.Gr3d.VtkControlBase.InitializeState(), IG.Gr3d.Graph3dManipulatorBasic.VtkContainer, and IG.Gr3d.VtkControlWin.VtkControl.
Member Function Documentation
Dispose()
override void IG.Gr3d.VtkControlWin.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Gr3d.VtkControlWin.components.
InitializeComponent()
void IG.Gr3d.VtkControlWin.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Gr3d.VtkControlBase.CameraRoll, IG.Gr3d.VtkControlBase.CameraViewAngle, IG.Gr3d.VtkControlWin.graph3dManipulatorBasic1, IG.Gr3d.VtkControlBase.IsActorsMode, IG.Gr3d.VtkControlBase.IsCameraMode, IG.Gr3d.Graph3dManipulatorBasic.IsCloseWindoButtonVisible, IG.Gr3d.VtkControlBase.IsJoystickMode, IG.Gr3d.Graph3dManipulatorBasic.IsManipulateButtonVisible, IG.Gr3d.VtkControlBase.IsSurfaceMode, IG.Gr3d.VtkControlBase.IsTrackballMode, IG.Gr3d.VtkControlBase.IsWireframeMode, IG.Gr3d.VtkControlBase.RotationStep, IG.Gr3d.VtkControlBase.VtkAddTestActors, IG.Gr3d.VtkControlBase.VtkAddTestActorsIGLib, IG.Gr3d.Graph3dManipulatorBasic.VtkContainer, IG.Gr3d.Graph3dManipulatorBasic.VtkControl, IG.Gr3d.VtkControlWin.vtkControlBase1, and IG.Gr3d.VtkControlBase.ZoomFactor.
Referenced by IG.Gr3d.VtkControlWin.VtkControlWin().
Member Data Documentation
_vtkControl
VtkControlBase IG.Gr3d.VtkControlWin._vtkControl private
_vtkRenderWindowControl
Kitware.VTK.RenderWindowControl IG.Gr3d.VtkControlWin._vtkRenderWindowControl private
components
System.ComponentModel.IContainer IG.Gr3d.VtkControlWin.components = null private
Required designer variable.
Referenced by IG.Gr3d.VtkControlWin.Dispose().
vtkControlBase1
IG.Gr3d.VtkControlBase IG.Gr3d.VtkControlWin.vtkControlBase1 private
Referenced by IG.Gr3d.VtkControlWin.InitializeComponent().
graph3dManipulatorBasic1
Graph3dManipulatorBasic IG.Gr3d.VtkControlWin.graph3dManipulatorBasic1 private
Referenced by IG.Gr3d.VtkControlWin.InitializeComponent(), and IG.Gr3d.VtkControlWin.VtkControlWin().
Property Documentation
VtkControl
VtkControlBase IG.Gr3d.VtkControlWin.VtkControl get
Gets the control of type VtkControlBase through which VTK functionality is controlled.
Referenced by IG.Gr3d.VtkControlWin.VtkControlWin().
VtkRenderWindowControl
Kitware.VTK.RenderWindowControl IG.Gr3d.VtkControlWin.VtkRenderWindowControl get
VTK's control that is actually used for rendering graphics and through which VTK can be interacted directly.
Instead of accessing this control directly, you should normally access it through the VtkControlBase.VtkControl property of the VtkControl property.
The documentation for this class was generated from the following files:
iglib/extensions/igplot3d/plot3d/vtkbased/Forms/VtkControlWin.cs
iglib/extensions/igplot3d/plot3d/vtkbased/Forms/VtkControlWin.Designer.cs