Doc: IGLib EXTENDED: IG.Lib.WsBaseRef.WSBase Class Reference
IG.Lib.WsBaseRef.WSBase Class Reference
Public Member Functions
WSBase ()
string GetServiceName ()
void GetServiceNameAsync ()
void GetServiceNameAsync (object userState)
void SetServiceName (string name)
void SetServiceNameAsync (string name)
void SetServiceNameAsync (string name, object userState)
string TestService ()
void TestServiceAsync ()
void TestServiceAsync (object userState)
string TestServiceCmd (string commandlineArguments)
void TestServiceCmdAsync (string commandlineArguments)
void TestServiceCmdAsync (string commandlineArguments, object userState)
string TestServiceArgs (string[] commandlineArguments)
void TestServiceArgsAsync (string[] commandlineArguments)
void TestServiceArgsAsync (string[] commandlineArguments, object userState)
string TestCount ()
void TestCountAsync ()
void TestCountAsync (object userState)
new void CancelAsync (object userState)
Properties
new string Url [get, set]
new bool UseDefaultCredentials [get, set]
Events
GetServiceNameCompletedEventHandler GetServiceNameCompleted
SetServiceNameCompletedEventHandler SetServiceNameCompleted
TestServiceCompletedEventHandler TestServiceCompleted
TestServiceCmdCompletedEventHandler TestServiceCmdCompleted
TestServiceArgsCompletedEventHandler TestServiceArgsCompleted
TestCountCompletedEventHandler TestCountCompleted
Private Member Functions
void OnGetServiceNameOperationCompleted (object arg)
void OnSetServiceNameOperationCompleted (object arg)
void OnTestServiceOperationCompleted (object arg)
void OnTestServiceCmdOperationCompleted (object arg)
void OnTestServiceArgsOperationCompleted (object arg)
void OnTestCountOperationCompleted (object arg)
bool IsLocalFileSystemWebService (string url)
Private Attributes
System.Threading.SendOrPostCallback GetServiceNameOperationCompleted
System.Threading.SendOrPostCallback SetServiceNameOperationCompleted
System.Threading.SendOrPostCallback TestServiceOperationCompleted
System.Threading.SendOrPostCallback TestServiceCmdOperationCompleted
System.Threading.SendOrPostCallback TestServiceArgsOperationCompleted
System.Threading.SendOrPostCallback TestCountOperationCompleted
bool useDefaultCredentialsSetExplicitly
Detailed Description
Constructor & Destructor Documentation
WSBase()
IG.Lib.WsBaseRef.WSBase.WSBase () inline
References IG.Lib.WsBaseRef.WSBase.IsLocalFileSystemWebService(), IG.Lib.WsBaseRef.WSBase.Url, and IG.Lib.WsBaseRef.WSBase.UseDefaultCredentials.
Member Function Documentation
GetServiceName()
string IG.Lib.WsBaseRef.WSBase.GetServiceName () inline
GetServiceNameAsync() [1/2]
void IG.Lib.WsBaseRef.WSBase.GetServiceNameAsync () inline
GetServiceNameAsync() [2/2]
void IG.Lib.WsBaseRef.WSBase.GetServiceNameAsync (object userState) inline
References IG.Lib.WsBaseRef.WSBase.GetServiceNameOperationCompleted, and IG.Lib.WsBaseRef.WSBase.OnGetServiceNameOperationCompleted().
OnGetServiceNameOperationCompleted()
void IG.Lib.WsBaseRef.WSBase.OnGetServiceNameOperationCompleted (object arg) inline private
References IG.Lib.WsBaseRef.WSBase.GetServiceNameCompleted.
Referenced by IG.Lib.WsBaseRef.WSBase.GetServiceNameAsync().
SetServiceName()
void IG.Lib.WsBaseRef.WSBase.SetServiceName (string name) inline
SetServiceNameAsync() [1/2]
void IG.Lib.WsBaseRef.WSBase.SetServiceNameAsync (string name) inline
SetServiceNameAsync() [2/2]
void IG.Lib.WsBaseRef.WSBase.SetServiceNameAsync (string name, object userState) inline
References IG.Lib.WsBaseRef.WSBase.OnSetServiceNameOperationCompleted(), and IG.Lib.WsBaseRef.WSBase.SetServiceNameOperationCompleted.
OnSetServiceNameOperationCompleted()
void IG.Lib.WsBaseRef.WSBase.OnSetServiceNameOperationCompleted (object arg) inline private
References IG.Lib.WsBaseRef.WSBase.SetServiceNameCompleted.
Referenced by IG.Lib.WsBaseRef.WSBase.SetServiceNameAsync().
TestService()
string IG.Lib.WsBaseRef.WSBase.TestService () inline
TestServiceAsync() [1/2]
void IG.Lib.WsBaseRef.WSBase.TestServiceAsync () inline
TestServiceAsync() [2/2]
void IG.Lib.WsBaseRef.WSBase.TestServiceAsync (object userState) inline
References IG.Lib.WsBaseRef.WSBase.OnTestServiceOperationCompleted(), and IG.Lib.WsBaseRef.WSBase.TestServiceOperationCompleted.
OnTestServiceOperationCompleted()
void IG.Lib.WsBaseRef.WSBase.OnTestServiceOperationCompleted (object arg) inline private
References IG.Lib.WsBaseRef.WSBase.TestServiceCompleted.
Referenced by IG.Lib.WsBaseRef.WSBase.TestServiceAsync().
TestServiceCmd()
string IG.Lib.WsBaseRef.WSBase.TestServiceCmd (string commandlineArguments) inline
TestServiceCmdAsync() [1/2]
void IG.Lib.WsBaseRef.WSBase.TestServiceCmdAsync (string commandlineArguments) inline
TestServiceCmdAsync() [2/2]
void IG.Lib.WsBaseRef.WSBase.TestServiceCmdAsync (string commandlineArguments, object userState) inline
References IG.Lib.WsBaseRef.WSBase.OnTestServiceCmdOperationCompleted(), and IG.Lib.WsBaseRef.WSBase.TestServiceCmdOperationCompleted.
OnTestServiceCmdOperationCompleted()
void IG.Lib.WsBaseRef.WSBase.OnTestServiceCmdOperationCompleted (object arg) inline private
References IG.Lib.WsBaseRef.WSBase.TestServiceCmdCompleted.
Referenced by IG.Lib.WsBaseRef.WSBase.TestServiceCmdAsync().
TestServiceArgs()
string IG.Lib.WsBaseRef.WSBase.TestServiceArgs (string[] commandlineArguments) inline
TestServiceArgsAsync() [1/2]
void IG.Lib.WsBaseRef.WSBase.TestServiceArgsAsync (string[] commandlineArguments) inline
TestServiceArgsAsync() [2/2]
void IG.Lib.WsBaseRef.WSBase.TestServiceArgsAsync (string[] commandlineArguments, object userState) inline
References IG.Lib.WsBaseRef.WSBase.OnTestServiceArgsOperationCompleted(), and IG.Lib.WsBaseRef.WSBase.TestServiceArgsOperationCompleted.
OnTestServiceArgsOperationCompleted()
void IG.Lib.WsBaseRef.WSBase.OnTestServiceArgsOperationCompleted (object arg) inline private
References IG.Lib.WsBaseRef.WSBase.TestServiceArgsCompleted.
Referenced by IG.Lib.WsBaseRef.WSBase.TestServiceArgsAsync().
TestCount()
string IG.Lib.WsBaseRef.WSBase.TestCount () inline
TestCountAsync() [1/2]
void IG.Lib.WsBaseRef.WSBase.TestCountAsync () inline
TestCountAsync() [2/2]
void IG.Lib.WsBaseRef.WSBase.TestCountAsync (object userState) inline
References IG.Lib.WsBaseRef.WSBase.OnTestCountOperationCompleted(), and IG.Lib.WsBaseRef.WSBase.TestCountOperationCompleted.
OnTestCountOperationCompleted()
void IG.Lib.WsBaseRef.WSBase.OnTestCountOperationCompleted (object arg) inline private
References IG.Lib.WsBaseRef.WSBase.TestCountCompleted.
Referenced by IG.Lib.WsBaseRef.WSBase.TestCountAsync().
CancelAsync()
new void IG.Lib.WsBaseRef.WSBase.CancelAsync (object userState) inline
IsLocalFileSystemWebService()
bool IG.Lib.WsBaseRef.WSBase.IsLocalFileSystemWebService (string url) inline private
Referenced by IG.Lib.WsBaseRef.WSBase.WSBase().
Member Data Documentation
GetServiceNameOperationCompleted
System.Threading.SendOrPostCallback IG.Lib.WsBaseRef.WSBase.GetServiceNameOperationCompleted private
Referenced by IG.Lib.WsBaseRef.WSBase.GetServiceNameAsync().
SetServiceNameOperationCompleted
System.Threading.SendOrPostCallback IG.Lib.WsBaseRef.WSBase.SetServiceNameOperationCompleted private
Referenced by IG.Lib.WsBaseRef.WSBase.SetServiceNameAsync().
TestServiceOperationCompleted
System.Threading.SendOrPostCallback IG.Lib.WsBaseRef.WSBase.TestServiceOperationCompleted private
Referenced by IG.Lib.WsBaseRef.WSBase.TestServiceAsync().
TestServiceCmdOperationCompleted
System.Threading.SendOrPostCallback IG.Lib.WsBaseRef.WSBase.TestServiceCmdOperationCompleted private
Referenced by IG.Lib.WsBaseRef.WSBase.TestServiceCmdAsync().
TestServiceArgsOperationCompleted
System.Threading.SendOrPostCallback IG.Lib.WsBaseRef.WSBase.TestServiceArgsOperationCompleted private
Referenced by IG.Lib.WsBaseRef.WSBase.TestServiceArgsAsync().
TestCountOperationCompleted
System.Threading.SendOrPostCallback IG.Lib.WsBaseRef.WSBase.TestCountOperationCompleted private
Referenced by IG.Lib.WsBaseRef.WSBase.TestCountAsync().
useDefaultCredentialsSetExplicitly
bool IG.Lib.WsBaseRef.WSBase.useDefaultCredentialsSetExplicitly private
Property Documentation
Url
new string IG.Lib.WsBaseRef.WSBase.Url get set
Referenced by IG.Lib.WsBaseRef.WSBase.WSBase().
UseDefaultCredentials
new bool IG.Lib.WsBaseRef.WSBase.UseDefaultCredentials get set
Referenced by IG.Lib.WsBaseRef.WSBase.WSBase().
Event Documentation
GetServiceNameCompleted
GetServiceNameCompletedEventHandler IG.Lib.WsBaseRef.WSBase.GetServiceNameCompleted
Referenced by IG.Lib.WsBaseRef.WSBase.OnGetServiceNameOperationCompleted().
SetServiceNameCompleted
SetServiceNameCompletedEventHandler IG.Lib.WsBaseRef.WSBase.SetServiceNameCompleted
Referenced by IG.Lib.WsBaseRef.WSBase.OnSetServiceNameOperationCompleted().
TestServiceCompleted
TestServiceCompletedEventHandler IG.Lib.WsBaseRef.WSBase.TestServiceCompleted
Referenced by IG.Lib.WsBaseRef.WSBase.OnTestServiceOperationCompleted().
TestServiceCmdCompleted
TestServiceCmdCompletedEventHandler IG.Lib.WsBaseRef.WSBase.TestServiceCmdCompleted
Referenced by IG.Lib.WsBaseRef.WSBase.OnTestServiceCmdOperationCompleted().
TestServiceArgsCompleted
TestServiceArgsCompletedEventHandler IG.Lib.WsBaseRef.WSBase.TestServiceArgsCompleted
Referenced by IG.Lib.WsBaseRef.WSBase.OnTestServiceArgsOperationCompleted().
TestCountCompleted
TestCountCompletedEventHandler IG.Lib.WsBaseRef.WSBase.TestCountCompleted
Referenced by IG.Lib.WsBaseRef.WSBase.OnTestCountOperationCompleted().
The documentation for this class was generated from the following file:
igtest/IGLibTestShell/Web References/WsBaseRef/Reference.cs