Doc: IGLib EXTENDED: AForge.DoublePoint Struct Reference
AForge.DoublePoint Struct Reference
Structure for representing a pair of coordinates of double type.
Public Member Functions
DoublePoint (double x, double y)
Initializes a new instance of the DoublePoint structure.
double DistanceTo (DoublePoint anotherPoint)
Calculate Euclidean distance between two points.
override bool Equals (object obj)
Check if this instance of DoublePoint equal to the specified one.
override int GetHashCode ()
Get hash code for this instance.
IntPoint Round ()
Rounds the double precision point.
override string ToString ()
Get string representation of the class.
double EuclideanNorm ()
Calculate Euclidean norm of the vector comprised of the point's coordinates - distance from (0, 0) in other words.
Static Public Member Functions
static DoublePoint operator+ (DoublePoint point1, DoublePoint point2)
Addition operator - adds values of two points.
static DoublePoint Add (DoublePoint point1, DoublePoint point2)
Addition operator - adds values of two points.
static DoublePoint operator- (DoublePoint point1, DoublePoint point2)
Subtraction operator - subtracts values of two points.
static DoublePoint Subtract (DoublePoint point1, DoublePoint point2)
Subtraction operator - subtracts values of two points.
static DoublePoint operator+ (DoublePoint point, double valueToAdd)
Addition operator - adds scalar to the specified point.
static DoublePoint Add (DoublePoint point, double valueToAdd)
Addition operator - adds scalar to the specified point.
static DoublePoint operator- (DoublePoint point, double valueToSubtract)
Subtraction operator - subtracts scalar from the specified point.
static DoublePoint Subtract (DoublePoint point, double valueToSubtract)
Subtraction operator - subtracts scalar from the specified point.
static DoublePoint operator* (DoublePoint point, double factor)
Multiplication operator - multiplies coordinates of the specified point by scalar value.
static DoublePoint Multiply (DoublePoint point, double factor)
Multiplication operator - multiplies coordinates of the specified point by scalar value.
static DoublePoint operator/ (DoublePoint point, double factor)
Division operator - divides coordinates of the specified point by scalar value.
static DoublePoint Divide (DoublePoint point, double factor)
Division operator - divides coordinates of the specified point by scalar value.
static bool operator== (DoublePoint point1, DoublePoint point2)
Equality operator - checks if two points have equal coordinates.
static bool operator!= (DoublePoint point1, DoublePoint point2)
Inequality operator - checks if two points have different coordinates.
static operator IntPoint (DoublePoint point)
Explicit conversion to IntPoint.
static operator Point (DoublePoint point)
Explicit conversion to Point.
Public Attributes
double X
X coordinate.
double Y
Y coordinate.
Detailed Description
Structure for representing a pair of coordinates of double type.
The structure is used to store a pair of floating point coordinates with double precision.
Sample usage:
// assigning coordinates in the constructor
DoublePoint p1 = new DoublePoint(10, 20);
// creating a point and assigning coordinates later
DoublePoint p2;
p2.X = 30;
p2.Y = 40;
// calculating distance between two points
double distance = p1.DistanceTo(p2);
Constructor & Destructor Documentation
DoublePoint()
AForge.DoublePoint.DoublePoint (double x, double y) inline
Initializes a new instance of the DoublePoint structure.
Parameters
x X axis coordinate.
y Y axis coordinate.
Referenced by AForge.DoublePoint.Add(), AForge.DoublePoint.Divide(), AForge.DoublePoint.Equals(), AForge.DoublePoint.Multiply(), AForge.DoublePoint.operator*(), AForge.DoublePoint.operator+(), AForge.DoublePoint.operator-(), AForge.DoublePoint.operator/(), and AForge.DoublePoint.Subtract().
Member Function Documentation
DistanceTo()
double AForge.DoublePoint.DistanceTo (DoublePoint anotherPoint) inline
Calculate Euclidean distance between two points.
Parameters
anotherPoint Point to calculate distance to.
Returns
Returns Euclidean distance between this point and anotherPoint points.
References AForge.DoublePoint.X, and AForge.DoublePoint.Y.
operator+() [1/2]
static DoublePoint AForge.DoublePoint.operator+ (DoublePoint point1, DoublePoint point2) inline static
Addition operator - adds values of two points.
Parameters
point1 First point for addition.
point2 Second point for addition.
Returns
Returns new point which coordinates equal to sum of corresponding coordinates of specified points.
References AForge.DoublePoint.DoublePoint(), AForge.DoublePoint.X, and AForge.DoublePoint.Y.
Add() [1/2]
static DoublePoint AForge.DoublePoint.Add (DoublePoint point1, DoublePoint point2) inline static
Addition operator - adds values of two points.
Parameters
point1 First point for addition.
point2 Second point for addition.
Returns
Returns new point which coordinates equal to sum of corresponding coordinates of specified points.
References AForge.DoublePoint.DoublePoint(), AForge.DoublePoint.X, and AForge.DoublePoint.Y.
operator-() [1/2]
static DoublePoint AForge.DoublePoint.operator- (DoublePoint point1, DoublePoint point2) inline static
Subtraction operator - subtracts values of two points.
Parameters
point1 Point to subtract from.
point2 Point to subtract.
Returns
Returns new point which coordinates equal to difference of corresponding coordinates of specified points.
References AForge.DoublePoint.DoublePoint(), AForge.DoublePoint.X, and AForge.DoublePoint.Y.
Subtract() [1/2]
static DoublePoint AForge.DoublePoint.Subtract (DoublePoint point1, DoublePoint point2) inline static
Subtraction operator - subtracts values of two points.
Parameters
point1 Point to subtract from.
point2 Point to subtract.
Returns
Returns new point which coordinates equal to difference of corresponding coordinates of specified points.
References AForge.DoublePoint.DoublePoint(), AForge.DoublePoint.X, and AForge.DoublePoint.Y.
operator+() [2/2]
static DoublePoint AForge.DoublePoint.operator+ (DoublePoint point, double valueToAdd) inline static
Addition operator - adds scalar to the specified point.
Parameters
point Point to increase coordinates of.
valueToAdd Value to add to coordinates of the specified point.
Returns
Returns new point which coordinates equal to coordinates of the specified point increased by specified value.
References AForge.DoublePoint.DoublePoint(), AForge.DoublePoint.X, and AForge.DoublePoint.Y.
Add() [2/2]
static DoublePoint AForge.DoublePoint.Add (DoublePoint point, double valueToAdd) inline static
Addition operator - adds scalar to the specified point.
Parameters
point Point to increase coordinates of.
valueToAdd Value to add to coordinates of the specified point.
Returns
Returns new point which coordinates equal to coordinates of the specified point increased by specified value.
References AForge.DoublePoint.DoublePoint(), AForge.DoublePoint.X, and AForge.DoublePoint.Y.
operator-() [2/2]
static DoublePoint AForge.DoublePoint.operator- (DoublePoint point, double valueToSubtract) inline static
Subtraction operator - subtracts scalar from the specified point.
Parameters
point Point to decrease coordinates of.
valueToSubtract Value to subtract from coordinates of the specified point.
Returns
Returns new point which coordinates equal to coordinates of the specified point decreased by specified value.
References AForge.DoublePoint.DoublePoint(), AForge.DoublePoint.X, and AForge.DoublePoint.Y.
Subtract() [2/2]
static DoublePoint AForge.DoublePoint.Subtract (DoublePoint point, double valueToSubtract) inline static
Subtraction operator - subtracts scalar from the specified point.
Parameters
point Point to decrease coordinates of.
valueToSubtract Value to subtract from coordinates of the specified point.
Returns
Returns new point which coordinates equal to coordinates of the specified point decreased by specified value.
References AForge.DoublePoint.DoublePoint(), AForge.DoublePoint.X, and AForge.DoublePoint.Y.
operator*()
static DoublePoint AForge.DoublePoint.operator* (DoublePoint point, double factor) inline static
Multiplication operator - multiplies coordinates of the specified point by scalar value.
Parameters
point Point to multiply coordinates of.
factor Multiplication factor.
Returns
Returns new point which coordinates equal to coordinates of the specified point multiplied by specified value.
References AForge.DoublePoint.DoublePoint(), AForge.DoublePoint.X, and AForge.DoublePoint.Y.
Multiply()
static DoublePoint AForge.DoublePoint.Multiply (DoublePoint point, double factor) inline static
Multiplication operator - multiplies coordinates of the specified point by scalar value.
Parameters
point Point to multiply coordinates of.
factor Multiplication factor.
Returns
Returns new point which coordinates equal to coordinates of the specified point multiplied by specified value.
References AForge.DoublePoint.DoublePoint(), AForge.DoublePoint.X, and AForge.DoublePoint.Y.
operator/()
static DoublePoint AForge.DoublePoint.operator/ (DoublePoint point, double factor) inline static
Division operator - divides coordinates of the specified point by scalar value.
Parameters
point Point to divide coordinates of.
factor Division factor.
Returns
Returns new point which coordinates equal to coordinates of the specified point divided by specified value.
References AForge.DoublePoint.DoublePoint(), AForge.DoublePoint.X, and AForge.DoublePoint.Y.
Divide()
static DoublePoint AForge.DoublePoint.Divide (DoublePoint point, double factor) inline static
Division operator - divides coordinates of the specified point by scalar value.
Parameters
point Point to divide coordinates of.
factor Division factor.
Returns
Returns new point which coordinates equal to coordinates of the specified point divided by specified value.
References AForge.DoublePoint.DoublePoint(), AForge.DoublePoint.X, and AForge.DoublePoint.Y.
operator==()
static bool AForge.DoublePoint.operator== (DoublePoint point1, DoublePoint point2) inline static
Equality operator - checks if two points have equal coordinates.
Parameters
point1 First point to check.
point2 Second point to check.
Returns
Returns true if coordinates of specified points are equal.
References AForge.DoublePoint.X, and AForge.DoublePoint.Y.
operator!=()
static bool AForge.DoublePoint.operator!= (DoublePoint point1, DoublePoint point2) inline static
Inequality operator - checks if two points have different coordinates.
Parameters
point1 First point to check.
point2 Second point to check.
Returns
Returns true if coordinates of specified points are not equal.
References AForge.DoublePoint.X, and AForge.DoublePoint.Y.
Equals()
override bool AForge.DoublePoint.Equals (object obj) inline
Check if this instance of DoublePoint equal to the specified one.
Parameters
obj Another point to check equalty to.
Returns
Return true if objects are equal.
References AForge.DoublePoint.DoublePoint().
GetHashCode()
override int AForge.DoublePoint.GetHashCode () inline
Get hash code for this instance.
Returns
Returns the hash code for this instance.
References AForge.DoublePoint.X, and AForge.DoublePoint.Y.
operator IntPoint()
static AForge.DoublePoint.operator IntPoint (DoublePoint point) inline explicit static
Explicit conversion to IntPoint.
Parameters
point Double precision point to convert to integer point.
Returns
Returns new integer point which coordinates are explicitly converted to integers from coordinates of the specified double precision point by casting double values to integers value.
References AForge.DoublePoint.X, and AForge.DoublePoint.Y.
operator Point()
static AForge.DoublePoint.operator Point (DoublePoint point) inline explicit static
Explicit conversion to Point.
Parameters
point Double precision point to convert to single precision point.
Returns
Returns new single precision point which coordinates are explicitly converted to floats from coordinates of the specified double precision point by casting double values to float value.
References AForge.DoublePoint.X, and AForge.DoublePoint.Y.
Round()
IntPoint AForge.DoublePoint.Round () inline
Rounds the double precision point.
Returns
Returns new integer point, which coordinates equal to whole numbers nearest to the corresponding coordinates of the double precision point.
References AForge.DoublePoint.X, and AForge.DoublePoint.Y.
ToString()
override string AForge.DoublePoint.ToString () inline
Get string representation of the class.
Returns
Returns string, which contains values of the point in readable form.
References AForge.DoublePoint.X, and AForge.DoublePoint.Y.
EuclideanNorm()
double AForge.DoublePoint.EuclideanNorm () inline
Calculate Euclidean norm of the vector comprised of the point's coordinates - distance from (0, 0) in other words.
Returns
Returns point's distance from (0, 0) point.
References AForge.DoublePoint.X, and AForge.DoublePoint.Y.
Member Data Documentation
X
double AForge.DoublePoint.X
X coordinate.
Referenced by AForge.DoublePoint.Add(), AForge.DoublePoint.DistanceTo(), AForge.DoublePoint.Divide(), AForge.DoublePoint.EuclideanNorm(), AForge.DoublePoint.GetHashCode(), AForge.DoublePoint.Multiply(), AForge.DoublePoint.operator IntPoint(), AForge.DoublePoint.operator Point(), AForge.DoublePoint.operator!=(), AForge.DoublePoint.operator*(), AForge.DoublePoint.operator+(), AForge.DoublePoint.operator-(), AForge.DoublePoint.operator/(), AForge.DoublePoint.operator==(), AForge.DoublePoint.Round(), AForge.DoublePoint.Subtract(), and AForge.DoublePoint.ToString().
Y
double AForge.DoublePoint.Y
Y coordinate.
Referenced by AForge.DoublePoint.Add(), AForge.DoublePoint.DistanceTo(), AForge.DoublePoint.Divide(), AForge.DoublePoint.EuclideanNorm(), AForge.DoublePoint.GetHashCode(), AForge.DoublePoint.Multiply(), AForge.DoublePoint.operator IntPoint(), AForge.DoublePoint.operator Point(), AForge.DoublePoint.operator!=(), AForge.DoublePoint.operator*(), AForge.DoublePoint.operator+(), AForge.DoublePoint.operator-(), AForge.DoublePoint.operator/(), AForge.DoublePoint.operator==(), AForge.DoublePoint.Round(), AForge.DoublePoint.Subtract(), and AForge.DoublePoint.ToString().
The documentation for this struct was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Core/DoublePoint.cs