Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGGLSE Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGGLSE Class Reference
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGGLSE (DAXPY daxpy, DCOPY dcopy, DGEMV dgemv, DGGRQF dggrqf, DORMQR dormqr, DORMRQ dormrq, DTRMV dtrmv, DTRTRS dtrtrs, XERBLA xerbla, ILAENV ilaenv)
DGGLSE ()
void Run (int M, int N, int P, ref double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB, ref double[] C, int offset_c, ref double[] D, int offset_d, ref double[] X, int offset_x, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
DAXPY _daxpy
DCOPY _dcopy
DGEMV _dgemv
DGGRQF _dggrqf
DORMQR _dormqr
DORMRQ _dormrq
DTRMV _dtrmv
DTRTRS _dtrtrs
XERBLA _xerbla
ILAENV _ilaenv
Static Private Attributes
const double ONE = 1.0E+0
Detailed Description
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGGLSE solves the linear equality-constrained least squares (LSE) problem:
minimize || c - A*x ||_2 subject to B*x = d
where A is an M-by-N matrix, B is a P-by-N matrix, c is a given M-vector, and d is a given P-vector. It is assumed that P .LE. N .LE. M+P, and
rank(B) = P and rank((A)) = N. ((B))
These conditions ensure that the LSE problem has a unique solution, which is obtained using a generalized RQ factorization of the matrices (B, A) given by
B = (0 R)*Q, A = Z*T*Q.
/summary>
Constructor & Destructor Documentation
DGGLSE() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGGLSE.DGGLSE (DAXPY daxpy, DCOPY dcopy, DGEMV dgemv, DGGRQF dggrqf, DORMQR dormqr, DORMRQ dormrq, DTRMV dtrmv, DTRTRS dtrtrs, XERBLA xerbla, ILAENV ilaenv) inline
DGGLSE() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGGLSE.DGGLSE () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGGLSE.Run (int M, int N, int P, ref double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB, ref double[] C, int offset_c, ref double[] D, int offset_d, ref double[] X, int offset_x, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DGGLSE solves the linear equality-constrained least squares (LSE) problem:
minimize || c - A*x ||_2 subject to B*x = d
where A is an M-by-N matrix, B is a P-by-N matrix, c is a given M-vector, and d is a given P-vector. It is assumed that P .LE. N .LE. M+P, and
rank(B) = P and rank((A)) = N. ((B))
These conditions ensure that the LSE problem has a unique solution, which is obtained using a generalized RQ factorization of the matrices (B, A) given by
B = (0 R)*Q, A = Z*T*Q.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrices A and B. N .GE. 0. /param>
Parameters
P (input) INTEGER The number of rows of the matrix B. 0 .LE. P .LE. N .LE. M+P. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the M-by-N matrix A. On exit, the elements on and above the diagonal of the array contain the min(M,N)-by-N upper trapezoidal matrix T. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
B = (0 R)*Q, A = Z*T*Q. /param>
Parameters
LDB (input) INTEGER The leading dimension of the array B. LDB .GE. max(1,P). /param>
Parameters
C (input/output) DOUBLE PRECISION array, dimension (M) On entry, C contains the right hand side vector for the least squares part of the LSE problem. On exit, the residual sum of squares for the solution is given by the sum of squares of elements N-P+1 to M of vector C. /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension (P) On entry, D contains the right hand side vector for the constrained equation. On exit, D is destroyed. /param>
Parameters
X (output) DOUBLE PRECISION array, dimension (N) On exit, X is the solution of the LSE problem. /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. max(1,M+N+P). For optimum performance LWORK .GE. P+min(M,N)+max(M,N)*NB, where NB is an upper bound for the optimal blocksizes for DGEQRF, SGERQF, DORMQR and SORMRQ.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. = 1: the upper triangular factor R associated with B in the generalized RQ factorization of the pair (B, A) is singular, so that rank(B) .LT. P; the least squares solution could not be computed. = 2: the (N-P) by (N-P) part of the upper trapezoidal factor T associated with A in the generalized RQ factorization of the pair (B, A) is singular, so that rank((A)) .LT. N; the least squares solution could not ((B)) be computed. /param>
References DotNumerics.LinearAlgebra.CSLapack.DGGLSE.ONE, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DAXPY.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRTRS.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMRQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGRQF.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRMV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run().
Member Data Documentation
_daxpy
DAXPY DotNumerics.LinearAlgebra.CSLapack.DGGLSE._daxpy private
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DGGLSE._dcopy private
_dgemv
DGEMV DotNumerics.LinearAlgebra.CSLapack.DGGLSE._dgemv private
_dggrqf
DGGRQF DotNumerics.LinearAlgebra.CSLapack.DGGLSE._dggrqf private
_dormqr
DORMQR DotNumerics.LinearAlgebra.CSLapack.DGGLSE._dormqr private
_dormrq
DORMRQ DotNumerics.LinearAlgebra.CSLapack.DGGLSE._dormrq private
_dtrmv
DTRMV DotNumerics.LinearAlgebra.CSLapack.DGGLSE._dtrmv private
_dtrtrs
DTRTRS DotNumerics.LinearAlgebra.CSLapack.DGGLSE._dtrtrs private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGGLSE._xerbla private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DGGLSE._ilaenv private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGGLSE.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGGLSE.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgglse.cs