Doc: IGLib EXTENDED: NUnit.Engine.Extensibility.IProject Interface Reference
NUnit.Engine.Extensibility.IProject Interface Reference
Interface for the various project types that the engine can load.
Public Member Functions
TestPackage GetTestPackage ()
Gets a test package for the primary or active configuration within the project. The package includes all the assemblies and any settings specified in the project format.
TestPackage GetTestPackage (string configName)
Gets a TestPackage for a specific configuration within the project. The package includes all the assemblies and any settings specified in the project format.
Properties
string ProjectPath [get]
Gets the path to the file storing this project, if any. If the project has not been saved, this is null.
string ActiveConfigName [get]
Gets the active configuration, as defined by the particular project.
IList< string > ConfigNames [get]
Gets a list of the configs for this project
Detailed Description
Interface for the various project types that the engine can load.
Member Function Documentation
GetTestPackage() [1/2]
TestPackage NUnit.Engine.Extensibility.IProject.GetTestPackage ()
Gets a test package for the primary or active configuration within the project. The package includes all the assemblies and any settings specified in the project format.
Returns
A TestPackage
Implemented in NUnit.Engine.Services.ProjectLoaders.VSProject, NUnit.Engine.Services.ProjectLoaders.NUnitProject, and NUnit.Engine.Services.ProjectLoaders.VSSolution.
Referenced by NUnit.Engine.Services.ProjectService.ExpandProjectPackage(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromSolutionWithDisabledProject(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromVSSolution2003(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromVSSolution2005(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromWebApplication(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadEmptyConfigs(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadNormalProject(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadProjectWithComplexSettings(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadProjectWithManualBinPath(), and NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.WithUnmanagedCpp().
GetTestPackage() [2/2]
TestPackage NUnit.Engine.Extensibility.IProject.GetTestPackage (string configName)
Gets a TestPackage for a specific configuration within the project. The package includes all the assemblies and any settings specified in the project format.
Parameters
configName The name of the config to use
Returns
A TestPackage for the named configuration.
Implemented in NUnit.Engine.Services.ProjectLoaders.VSProject, NUnit.Engine.Services.ProjectLoaders.NUnitProject, and NUnit.Engine.Services.ProjectLoaders.VSSolution.
Property Documentation
ProjectPath
string NUnit.Engine.Extensibility.IProject.ProjectPath get
Gets the path to the file storing this project, if any. If the project has not been saved, this is null.
Referenced by NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.CanLoadEmptyProject().
ActiveConfigName
string NUnit.Engine.Extensibility.IProject.ActiveConfigName get
Gets the active configuration, as defined by the particular project.
Referenced by NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.CanLoadEmptyProject(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadEmptyConfigs(), and NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadNormalProject().
ConfigNames
IList<string> NUnit.Engine.Extensibility.IProject.ConfigNames get
Gets a list of the configs for this project
Referenced by NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.CanLoadEmptyProject(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.CanLoadVsProject(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromSolutionWithDisabledProject(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromVSSolution2003(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromVSSolution2005(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromWebApplication(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadEmptyConfigs(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadNormalProject(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadProjectWithComplexSettings(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadProjectWithManualBinPath(), and NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.WithUnmanagedCpp().
The documentation for this interface was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.api/Extensibility/IProject.cs