Doc: IGLib EXTENDED: CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel Class Reference
CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel Class Reference
Public Member Functions
AssemblyReferencesViewModel (AssemblyReferences assemblyReferences)
IEnumerable< IResult > AddReferenceFromFile ()
IEnumerable< IResult > AddReferenceFromGac ()
Public Member Functions inherited from CShell.Modules.Workspace.ViewModels.TreeViewModel
IEnumerable< TreeViewModel > GetAllChildren ()
Recursively returns all children in the tree.
void Dispose ()
Protected Member Functions
override void Dispose (bool disposing)
Protected Member Functions inherited from CShell.Modules.Workspace.ViewModels.TreeViewModel
virtual void EditModeFinished ()
Properties
override Uri IconSource [get]
Properties inherited from CShell.Modules.Workspace.ViewModels.TreeViewModel
virtual string DisplayName [get, set]
virtual Uri IconSource [get]
virtual IObservableCollection< TreeViewModel > Children [get]
bool IsSelected [get, set]
bool IsExpanded [get, set]
bool IsEditable [get, set]
virtual bool IsInEditMode [get, set]
Private Member Functions
void Reload ()
void AssemblyReferencesOnCollectionChanged (object sender, NotifyCollectionChangedEventArgs notifyCollectionChangedEventArgs)
Private Attributes
readonly AssemblyReferences assemblyReferences
Constructor & Destructor Documentation
AssemblyReferencesViewModel()
CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.AssemblyReferencesViewModel (AssemblyReferences assemblyReferences) inline
References CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.assemblyReferences, CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.AssemblyReferencesOnCollectionChanged(), CShell.Util.ObservableKeyedCollection< TKey, TItem >.CollectionChanged, CShell.Modules.Workspace.ViewModels.TreeViewModel.DisplayName, and CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.Reload().
Member Function Documentation
Reload()
void CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.Reload () inline private
References CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.assemblyReferences, and CShell.Modules.Workspace.ViewModels.TreeViewModel.Children.
Referenced by CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.AssemblyReferencesOnCollectionChanged(), and CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.AssemblyReferencesViewModel().
AssemblyReferencesOnCollectionChanged()
void CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.AssemblyReferencesOnCollectionChanged (object sender, NotifyCollectionChangedEventArgs notifyCollectionChangedEventArgs) inline private
References CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.Reload().
Referenced by CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.AssemblyReferencesViewModel(), and CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.Dispose().
Dispose()
override void CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.Dispose (bool disposing) inline protected virtual
Reimplemented from CShell.Modules.Workspace.ViewModels.TreeViewModel.
References CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.assemblyReferences, CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.AssemblyReferencesOnCollectionChanged(), and CShell.Util.ObservableKeyedCollection< TKey, TItem >.CollectionChanged.
AddReferenceFromFile()
IEnumerable<IResult> CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.AddReferenceFromFile () inline
References CShell.Constants.AssemblyFileFilter, CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.assemblyReferences, and CShell.Framework.Results.Show.Dialog().
AddReferenceFromGac()
IEnumerable<IResult> CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.AddReferenceFromGac () inline
References CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.assemblyReferences, and CShell.Framework.Results.Show.Dialog().
Member Data Documentation
assemblyReferences
readonly AssemblyReferences CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.assemblyReferences private
Referenced by CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.AddReferenceFromFile(), CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.AddReferenceFromGac(), CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.AssemblyReferencesViewModel(), CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.Dispose(), and CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.Reload().
Property Documentation
IconSource
override Uri CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.IconSource get
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Workspace/ViewModels/AssemblyReferencesViewModel.cs