Doc: IGLib EXTENDED: AForge.Imaging.ImageStatisticsHSL Class Reference
AForge.Imaging.ImageStatisticsHSL Class Reference
Gather statistics about image in HSL color space.
Public Member Functions
ImageStatisticsHSL (Bitmap image)
Initializes a new instance of the ImageStatisticsHSL class.
ImageStatisticsHSL (Bitmap image, Bitmap mask)
Initializes a new instance of the ImageStatisticsHSL class.
ImageStatisticsHSL (Bitmap image, byte[,] mask)
Initializes a new instance of the ImageStatisticsHSL class.
ImageStatisticsHSL (UnmanagedImage image)
Initializes a new instance of the ImageStatisticsHSL class.
ImageStatisticsHSL (UnmanagedImage image, UnmanagedImage mask)
Initializes a new instance of the ImageStatisticsHSL class.
ImageStatisticsHSL (UnmanagedImage image, byte[,] mask)
Initializes a new instance of the ImageStatisticsHSL class.
Properties
ContinuousHistogram Saturation [get]
Histogram of saturation channel.
ContinuousHistogram Luminance [get]
Histogram of luminance channel.
ContinuousHistogram SaturationWithoutBlack [get]
Histogram of saturation channel excluding black pixels.
ContinuousHistogram LuminanceWithoutBlack [get]
Histogram of luminance channel excluding black pixels.
int PixelsCount [get]
Total pixels count in the processed image.
int PixelsCountWithoutBlack [get]
Total pixels count in the processed image excluding black pixels.
Private Member Functions
unsafe void ProcessImage (UnmanagedImage image, byte *mask, int maskLineSize)
void CheckSourceFormat (PixelFormat pixelFormat)
void CheckMaskProperties (PixelFormat maskFormat, Size maskSize, Size sourceImageSize)
Private Attributes
ContinuousHistogram luminance
ContinuousHistogram saturation
ContinuousHistogram luminanceWithoutBlack
ContinuousHistogram saturationWithoutBlack
int pixels
int pixelsWithoutBlack
Detailed Description
Gather statistics about image in HSL color space.
The class is used to accumulate statistical values about images, like histogram, mean, standard deviation, etc. for each HSL color channel.
The class accepts 24 and 32 bpp color images for processing.
Sample usage:
// gather statistics
ImageStatisticsHSL stat = new ImageStatisticsHSL(image);
// get saturation channel's histogram
ContinuousHistogram saturation = stat.Saturation;
// check mean value of saturation channel
if (saturation.Mean > 0.5)
{
    // do further processing
}
See also
AForge.Math.ContinuousHistogram
Constructor & Destructor Documentation
ImageStatisticsHSL() [1/6]
AForge.Imaging.ImageStatisticsHSL.ImageStatisticsHSL (Bitmap image) inline
Initializes a new instance of the ImageStatisticsHSL class.
Parameters
image Image to gather statistics about.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported.
References AForge.Imaging.ImageStatisticsHSL.CheckSourceFormat(), AForge.Imaging.ImageStatisticsHSL.ProcessImage(), and AForge.Math.Geometry.Rectangle.
ImageStatisticsHSL() [2/6]
AForge.Imaging.ImageStatisticsHSL.ImageStatisticsHSL (Bitmap image, Bitmap mask) inline
Initializes a new instance of the ImageStatisticsHSL class.
Parameters
image Image to gather statistics about.
mask Mask image which specifies areas to collect statistics for.
The mask image must be a grayscale/binary (8bpp) image of the same size as the specified source image, where black pixels (value 0) correspond to areas which should be excluded from processing. So statistics is calculated only for pixels, which are none black in the mask image.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported.
ArgumentException Mask image must be 8 bpp grayscale image.
ArgumentException Mask must have the same size as the source image to get statistics for.
References AForge.Imaging.ImageStatisticsHSL.CheckMaskProperties(), AForge.Imaging.ImageStatisticsHSL.CheckSourceFormat(), AForge.Imaging.ImageStatisticsHSL.ProcessImage(), AForge.Math.Geometry.Rectangle, AForge.Imaging.Size, and AForge.Imaging.UnmanagedImage.Stride.
ImageStatisticsHSL() [3/6]
AForge.Imaging.ImageStatisticsHSL.ImageStatisticsHSL (Bitmap image, byte mask[,]) inline
Initializes a new instance of the ImageStatisticsHSL class.
Parameters
image Image to gather statistics about.
mask Mask array which specifies areas to collect statistics for.
The mask array must be of the same size as the specified source image, where 0 values correspond to areas which should be excluded from processing. So statistics is calculated only for pixels, which have none zero corresponding value in the mask.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported.
ArgumentException Mask must have the same size as the source image to get statistics for.
References AForge.Imaging.ImageStatisticsHSL.CheckMaskProperties(), AForge.Imaging.ImageStatisticsHSL.CheckSourceFormat(), AForge.Imaging.ImageStatisticsHSL.ProcessImage(), AForge.Math.Geometry.Rectangle, and AForge.Imaging.Size.
ImageStatisticsHSL() [4/6]
AForge.Imaging.ImageStatisticsHSL.ImageStatisticsHSL (UnmanagedImage image) inline
Initializes a new instance of the ImageStatisticsHSL class.
Parameters
image Unmanaged image to gather statistics about.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported.
References AForge.Imaging.ImageStatisticsHSL.CheckSourceFormat(), AForge.Imaging.UnmanagedImage.PixelFormat, and AForge.Imaging.ImageStatisticsHSL.ProcessImage().
ImageStatisticsHSL() [5/6]
AForge.Imaging.ImageStatisticsHSL.ImageStatisticsHSL (UnmanagedImage image, UnmanagedImage mask) inline
Initializes a new instance of the ImageStatisticsHSL class.
Parameters
image Image to gather statistics about.
mask Mask image which specifies areas to collect statistics for.
The mask image must be a grayscale/binary (8bpp) image of the same size as the specified source image, where black pixels (value 0) correspond to areas which should be excluded from processing. So statistics is calculated only for pixels, which are none black in the mask image.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported.
ArgumentException Mask image must be 8 bpp grayscale image.
ArgumentException Mask must have the same size as the source image to get statistics for.
References AForge.Imaging.ImageStatisticsHSL.CheckMaskProperties(), AForge.Imaging.ImageStatisticsHSL.CheckSourceFormat(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.ImageStatisticsHSL.ProcessImage(), AForge.Imaging.Size, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
ImageStatisticsHSL() [6/6]
AForge.Imaging.ImageStatisticsHSL.ImageStatisticsHSL (UnmanagedImage image, byte mask[,]) inline
Initializes a new instance of the ImageStatisticsHSL class.
Parameters
image Image to gather statistics about.
mask Mask array which specifies areas to collect statistics for.
The mask array must be of the same size as the specified source image, where 0 values correspond to areas which should be excluded from processing. So statistics is calculated only for pixels, which have none zero corresponding value in the mask.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported.
ArgumentException Mask must have the same size as the source image to get statistics for.
References AForge.Imaging.ImageStatisticsHSL.CheckMaskProperties(), AForge.Imaging.ImageStatisticsHSL.CheckSourceFormat(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.ImageStatisticsHSL.ProcessImage(), AForge.Imaging.Size, and AForge.Imaging.UnmanagedImage.Width.
Member Function Documentation
ProcessImage()
unsafe void AForge.Imaging.ImageStatisticsHSL.ProcessImage (UnmanagedImage image, byte * mask, int maskLineSize) inline private
References AForge.Imaging.RGB.B, AForge.Imaging.RGB.Blue, AForge.Imaging.HSL.FromRGB(), AForge.Imaging.RGB.G, AForge.Imaging.RGB.Green, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.ImageStatisticsHSL.luminance, AForge.Imaging.HSL.Luminance, AForge.Imaging.ImageStatisticsHSL.luminanceWithoutBlack, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.ImageStatisticsHSL.pixels, AForge.Imaging.ImageStatisticsHSL.pixelsWithoutBlack, AForge.Imaging.RGB.R, AForge.Imaging.RGB.Red, AForge.Imaging.ImageStatisticsHSL.saturation, AForge.Imaging.HSL.Saturation, AForge.Imaging.ImageStatisticsHSL.saturationWithoutBlack, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
Referenced by AForge.Imaging.ImageStatisticsHSL.ImageStatisticsHSL().
CheckSourceFormat()
void AForge.Imaging.ImageStatisticsHSL.CheckSourceFormat (PixelFormat pixelFormat) inline private
Referenced by AForge.Imaging.ImageStatisticsHSL.ImageStatisticsHSL().
CheckMaskProperties()
void AForge.Imaging.ImageStatisticsHSL.CheckMaskProperties (PixelFormat maskFormat, Size maskSize, Size sourceImageSize) inline private
Referenced by AForge.Imaging.ImageStatisticsHSL.ImageStatisticsHSL().
Member Data Documentation
luminance
ContinuousHistogram AForge.Imaging.ImageStatisticsHSL.luminance private
Referenced by AForge.Imaging.ImageStatisticsHSL.ProcessImage().
saturation
ContinuousHistogram AForge.Imaging.ImageStatisticsHSL.saturation private
Referenced by AForge.Imaging.ImageStatisticsHSL.ProcessImage().
luminanceWithoutBlack
ContinuousHistogram AForge.Imaging.ImageStatisticsHSL.luminanceWithoutBlack private
Referenced by AForge.Imaging.ImageStatisticsHSL.ProcessImage().
saturationWithoutBlack
ContinuousHistogram AForge.Imaging.ImageStatisticsHSL.saturationWithoutBlack private
Referenced by AForge.Imaging.ImageStatisticsHSL.ProcessImage().
pixels
int AForge.Imaging.ImageStatisticsHSL.pixels private
Referenced by AForge.Imaging.ImageStatisticsHSL.ProcessImage().
pixelsWithoutBlack
int AForge.Imaging.ImageStatisticsHSL.pixelsWithoutBlack private
Referenced by AForge.Imaging.ImageStatisticsHSL.ProcessImage().
Property Documentation
Saturation
ContinuousHistogram AForge.Imaging.ImageStatisticsHSL.Saturation get
Histogram of saturation channel.
Luminance
ContinuousHistogram AForge.Imaging.ImageStatisticsHSL.Luminance get
Histogram of luminance channel.
SaturationWithoutBlack
ContinuousHistogram AForge.Imaging.ImageStatisticsHSL.SaturationWithoutBlack get
Histogram of saturation channel excluding black pixels.
The property keeps statistics about saturation channel, which excludes all black pixels, what affects mean, standard deviation, etc.
LuminanceWithoutBlack
ContinuousHistogram AForge.Imaging.ImageStatisticsHSL.LuminanceWithoutBlack get
Histogram of luminance channel excluding black pixels.
The property keeps statistics about luminance channel, which excludes all black pixels, what affects mean, standard deviation, etc.
PixelsCount
int AForge.Imaging.ImageStatisticsHSL.PixelsCount get
Total pixels count in the processed image.
PixelsCountWithoutBlack
int AForge.Imaging.ImageStatisticsHSL.PixelsCountWithoutBlack get
Total pixels count in the processed image excluding black pixels.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/ImageStatisticsHSL.cs