Doc: IGLib EXTENDED: IG.Web.IWSBase Interface Reference
IG.Web.IWSBase Interface Reference
Interface for basic web service.
Public Member Functions
string GetServiceName ()
Returns the name of the web service.
void SetServiceName (string name)
Sets the name of the web service.
string TestService ()
Tests whether the web service is alive.
string TestServiceCmd (string commandlineArguments)
Tests whether the web service is alive.
string TestServiceArgs (string[] commandlineArguments)
Tests whether the web service is alive.
string TestCount ()
Web service method example. Increments a static counter.
Properties
string Url [get, set]
URL of the web service.
System.Net.CookieContainer CookieContainer [get, set]
Cookie container, for compatibility with proxy classes that are derived from the System.Web.Services.Protocols.HttpWebClientProtocol class.
Detailed Description
Interface for basic web service.
Member Function Documentation
GetServiceName()
string IG.Web.IWSBase.GetServiceName ()
Returns the name of the web service.
Usually, address (URL) of the web service will consists of some base address and service name.
Implemented in IG.Web.WSBaseClass.
Referenced by IG.Script.AppTestShell.WebServiceFunctionCustomTest().
SetServiceName()
void IG.Web.IWSBase.SetServiceName (string name)
Sets the name of the web service.
Usually, address (URL) of the web service will consists of some base address and service name.
Implemented in IG.Web.WSBaseClass.
TestService()
string IG.Web.IWSBase.TestService ()
Tests whether the web service is alive.
Returns a string identifying web service' class and object ID.
To test, right-click the Web Service's .asmx file and select View in a browser.
Returns
Implemented in IG.Web.WSBaseClass.
Referenced by IG.Web.Forms.WSClient1Control.btnRunServiceMethod_Click().
TestServiceCmd()
string IG.Web.IWSBase.TestServiceCmd (string commandlineArguments)
Tests whether the web service is alive.
Returns a string identifying web service' class and object ID.
To test, right-click the Web Service's .asmx file and select View in a browser.
Returns
Implemented in IG.Web.WSBaseClass.
Referenced by IG.Web.Forms.WSClient1Control.btnRunServiceMethod_Click(), and IG.Script.AppTestShell.WebServiceFunctionCustomTest().
TestServiceArgs()
string IG.Web.IWSBase.TestServiceArgs (string[] commandlineArguments)
Tests whether the web service is alive.
Returns a string identifying web service' class and object ID.
To test, right-click the Web Service's .asmx file and select View in a browser.
Returns
Implemented in IG.Web.WSBaseClass.
Referenced by IG.Web.Forms.WSClient1Control.btnRunServiceMethod_Click(), and IG.Script.AppTestShell.WebServiceFunctionCustomTest().
TestCount()
string IG.Web.IWSBase.TestCount ()
Web service method example. Increments a static counter.
To test, right-click the Web Service's .asmx file and select View in Browser
Returns
Implemented in IG.Web.WSBaseClass.
Property Documentation
Url
string IG.Web.IWSBase.Url get set
URL of the web service.
This is put into Web service such that base service classes can be used instead of proxy classes, which may be useful when the appropriate service references are not available to generate the proxy classes.
Referenced by IG.Script.AppTestShell.WebServiceFunctionCustomTest().
CookieContainer
System.Net.CookieContainer IG.Web.IWSBase.CookieContainer get set
Cookie container, for compatibility with proxy classes that are derived from the System.Web.Services.Protocols.HttpWebClientProtocol class.
Referenced by IG.Script.AppTestShell.WebServiceFunctionCustomTest().
The documentation for this interface was generated from the following file:
igtest/IGLibTestDev_Copy/WebServiceBase/IWSBase.cs