Doc: IGLib EXTENDED: Meta.Numerics.Statistics.UncertainMeasurement< T > Class Template Reference
Meta.Numerics.Statistics.UncertainMeasurement< T > Class Template Reference
Represents an experimental data point that is a function of an arbitrary variable.
Public Member Functions
UncertainMeasurement (T x, UncertainValue y)
Initializes a new data point with the given values for the ordinate and uncertain abcissa.
UncertainMeasurement (T x, double y, double dy)
Initializes a new data point with the given values for the ordinate, abcissa, and uncertainty.
override bool Equals (object obj)
Determines whether the object represents the same data point.
override int GetHashCode ()
Gets a hash code for the data point.
Static Public Member Functions
static bool operator== (UncertainMeasurement< T > d1, UncertainMeasurement< T > d2)
Determines whether two data points are equal.
static bool operator!= (UncertainMeasurement< T > d1, UncertainMeasurement< T > d2)
Determines whether two data points are not equal.
Properties
T X [get]
Gets or sets the value of the ordinate (independent variable).
UncertainValue Y [get]
Gets or sets the uncertain value of the abcissa (the depdent variable).
Static Private Member Functions
static bool Equals (UncertainMeasurement< T > d1, UncertainMeasurement< T > d2)
Private Attributes
T x
UncertainValue y
Detailed Description
Represents an experimental data point that is a function of an arbitrary variable.
Template Parameters
T The type of the ordinate (independent variable) characterizing the data point.
Constructor & Destructor Documentation
UncertainMeasurement() [1/2]
Meta.Numerics.Statistics.UncertainMeasurement< T >.UncertainMeasurement (T x, UncertainValue y) inline
Initializes a new data point with the given values for the ordinate and uncertain abcissa.
Parameters
x The ordinate.
y The abcissa.
References Meta.Numerics.Statistics.UncertainMeasurement< T >.x, and Meta.Numerics.Statistics.UncertainMeasurement< T >.y.
UncertainMeasurement() [2/2]
Meta.Numerics.Statistics.UncertainMeasurement< T >.UncertainMeasurement (T x, double y, double dy) inline
Initializes a new data point with the given values for the ordinate, abcissa, and uncertainty.
Parameters
x The ordinate.
y The best estimate of the abcissa.
dy The uncertainty in the abcissa.
References Meta.Numerics.Statistics.UncertainMeasurement< T >.x, and Meta.Numerics.Statistics.UncertainMeasurement< T >.y.
Member Function Documentation
Equals() [1/2]
static bool Meta.Numerics.Statistics.UncertainMeasurement< T >.Equals (UncertainMeasurement< T > d1, UncertainMeasurement< T > d2) inline static private
References Meta.Numerics.Statistics.UncertainMeasurement< T >.X, and Meta.Numerics.Statistics.UncertainMeasurement< T >.Y.
Referenced by Meta.Numerics.Statistics.UncertainMeasurement< T >.Equals(), Meta.Numerics.Statistics.UncertainMeasurement< T >.operator!=(), and Meta.Numerics.Statistics.UncertainMeasurement< T >.operator==().
operator==()
static bool Meta.Numerics.Statistics.UncertainMeasurement< T >.operator== (UncertainMeasurement< T > d1, UncertainMeasurement< T > d2) inline static
Determines whether two data points are equal.
Parameters
d1 The first data point.
d2 The second data point.
Returns
True if the data points are equal, otherwise false.
References Meta.Numerics.Statistics.UncertainMeasurement< T >.Equals().
operator!=()
static bool Meta.Numerics.Statistics.UncertainMeasurement< T >.operator!= (UncertainMeasurement< T > d1, UncertainMeasurement< T > d2) inline static
Determines whether two data points are not equal.
Parameters
d1 The first data point.
d2 The second data point.
Returns
True if the data points are not equal, otherwise false.
References Meta.Numerics.Statistics.UncertainMeasurement< T >.Equals().
Equals() [2/2]
override bool Meta.Numerics.Statistics.UncertainMeasurement< T >.Equals (object obj) inline
Determines whether the object represents the same data point.
Parameters
obj The object.
Returns
True if the object represents the same data point, otherwise false.
References Meta.Numerics.Statistics.UncertainMeasurement< T >.Equals().
GetHashCode()
override int Meta.Numerics.Statistics.UncertainMeasurement< T >.GetHashCode () inline
Gets a hash code for the data point.
Returns
A hash code for the data point.
References Meta.Numerics.UncertainValue.GetHashCode(), Meta.Numerics.Statistics.UncertainMeasurement< T >.x, and Meta.Numerics.Statistics.UncertainMeasurement< T >.y.
Member Data Documentation
x
T Meta.Numerics.Statistics.UncertainMeasurement< T >.x private
Referenced by Meta.Numerics.Statistics.UncertainMeasurement< T >.GetHashCode(), and Meta.Numerics.Statistics.UncertainMeasurement< T >.UncertainMeasurement().
y
UncertainValue Meta.Numerics.Statistics.UncertainMeasurement< T >.y private
Referenced by Meta.Numerics.Statistics.UncertainMeasurement< T >.GetHashCode(), and Meta.Numerics.Statistics.UncertainMeasurement< T >.UncertainMeasurement().
Property Documentation
X
T Meta.Numerics.Statistics.UncertainMeasurement< T >.X get
Gets or sets the value of the ordinate (independent variable).
Referenced by Meta.Numerics.Statistics.UncertainMeasurement< T >.Equals(), Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToLine(), and Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToProportionality().
Y
UncertainValue Meta.Numerics.Statistics.UncertainMeasurement< T >.Y get
Gets or sets the uncertain value of the abcissa (the depdent variable).
Referenced by Meta.Numerics.Statistics.UncertainMeasurement< T >.Equals(), Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToConstant(), Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToLine(), and Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToProportionality().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/UncertainMeasurement.cs