Doc: IGLib EXTENDED: NUnit.Common.Tests.OutputSpecificationTests Class Reference
NUnit.Common.Tests.OutputSpecificationTests Class Reference
Public Member Functions
void SpecMayNotBeNull ()
void SpecOptionMustContainEqualSign ()
void SpecOptionMustContainJustOneEqualSign ()
void FileNameOnly ()
void FileNamePlusFormat ()
void FileNamePlusTransform ()
void UserFormatMayBeIndicatedExplicitlyAfterTransform ()
void UserFormatMayBeIndicatedExplicitlyBeforeTransform ()
void MultipleFormatSpecifiersNotAllowed ()
void MultipleTransformSpecifiersNotAllowed ()
void TransformWithNonUserFormatNotAllowed ()
Member Function Documentation
SpecMayNotBeNull()
void NUnit.Common.Tests.OutputSpecificationTests.SpecMayNotBeNull () inline
References NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
SpecOptionMustContainEqualSign()
void NUnit.Common.Tests.OutputSpecificationTests.SpecOptionMustContainEqualSign () inline
References NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
SpecOptionMustContainJustOneEqualSign()
void NUnit.Common.Tests.OutputSpecificationTests.SpecOptionMustContainJustOneEqualSign () inline
References NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
FileNameOnly()
void NUnit.Common.Tests.OutputSpecificationTests.FileNameOnly () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.Null(), and NUnit.Framework.Assert.That().
FileNamePlusFormat()
void NUnit.Common.Tests.OutputSpecificationTests.FileNamePlusFormat () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.Null(), and NUnit.Framework.Assert.That().
FileNamePlusTransform()
void NUnit.Common.Tests.OutputSpecificationTests.FileNamePlusTransform () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
UserFormatMayBeIndicatedExplicitlyAfterTransform()
void NUnit.Common.Tests.OutputSpecificationTests.UserFormatMayBeIndicatedExplicitlyAfterTransform () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
UserFormatMayBeIndicatedExplicitlyBeforeTransform()
void NUnit.Common.Tests.OutputSpecificationTests.UserFormatMayBeIndicatedExplicitlyBeforeTransform () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
MultipleFormatSpecifiersNotAllowed()
void NUnit.Common.Tests.OutputSpecificationTests.MultipleFormatSpecifiersNotAllowed () inline
References NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
MultipleTransformSpecifiersNotAllowed()
void NUnit.Common.Tests.OutputSpecificationTests.MultipleTransformSpecifiersNotAllowed () inline
References NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
TransformWithNonUserFormatNotAllowed()
void NUnit.Common.Tests.OutputSpecificationTests.TransformWithNonUserFormatNotAllowed () inline
References NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/tests/OutputSpecificationTests.cs