Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DTREVC Class Reference
DotNumerics.LinearAlgebra.CSLapack.DTREVC Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DTREVC (LSAME lsame, IDAMAX idamax, DDOT ddot, DLAMCH dlamch, DAXPY daxpy, DCOPY dcopy, DGEMV dgemv, DLALN2 dlaln2, DSCAL dscal, XERBLA xerbla, DLABAD dlabad)
DTREVC ()
void Run (string SIDE, string HOWMNY, ref bool[] SELECT, int offset_select, int N, double[] T, int offset_t, int LDT, ref double[] VL, int offset_vl, int LDVL, ref double[] VR, int offset_vr, int LDVR, int MM, ref int M, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
LSAME _lsame
IDAMAX _idamax
DDOT _ddot
DLAMCH _dlamch
DAXPY _daxpy
DCOPY _dcopy
DGEMV _dgemv
DLALN2 _dlaln2
DSCAL _dscal
XERBLA _xerbla
DLABAD _dlabad
double[] X = new double[2 * 2]
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DTREVC computes some or all of the right and/or left eigenvectors of a real upper quasi-triangular matrix T. Matrices of this type are produced by the Schur factorization of a real general matrix: A = Q*T*Q**T, as computed by DHSEQR.
The right eigenvector x and the left eigenvector y of T corresponding to an eigenvalue w are defined by:
T*x = w*x, (y**H)*T = w*(y**H)
where y**H denotes the conjugate transpose of y. The eigenvalues are not input to this routine, but are read directly from the diagonal blocks of T.
This routine returns the matrices X and/or Y of right and left eigenvectors of T, or the products Q*X and/or Q*Y, where Q is an input matrix. If Q is the orthogonal factor that reduces a matrix A to Schur form T, then Q*X and Q*Y are the matrices of right and left eigenvectors of A.
/summary>
Constructor & Destructor Documentation
DTREVC() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DTREVC.DTREVC (LSAME lsame, IDAMAX idamax, DDOT ddot, DLAMCH dlamch, DAXPY daxpy, DCOPY dcopy, DGEMV dgemv, DLALN2 dlaln2, DSCAL dscal, XERBLA xerbla, DLABAD dlabad) inline
DTREVC() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DTREVC.DTREVC () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DTREVC.Run (string SIDE, string HOWMNY, ref bool[] SELECT, int offset_select, int N, double[] T, int offset_t, int LDT, ref double[] VL, int offset_vl, int LDVL, ref double[] VR, int offset_vr, int LDVR, int MM, ref int M, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
DTREVC computes some or all of the right and/or left eigenvectors of a real upper quasi-triangular matrix T. Matrices of this type are produced by the Schur factorization of a real general matrix: A = Q*T*Q**T, as computed by DHSEQR.
The right eigenvector x and the left eigenvector y of T corresponding to an eigenvalue w are defined by:
T*x = w*x, (y**H)*T = w*(y**H)
where y**H denotes the conjugate transpose of y. The eigenvalues are not input to this routine, but are read directly from the diagonal blocks of T.
This routine returns the matrices X and/or Y of right and left eigenvectors of T, or the products Q*X and/or Q*Y, where Q is an input matrix. If Q is the orthogonal factor that reduces a matrix A to Schur form T, then Q*X and Q*Y are the matrices of right and left eigenvectors of A.
/summary>
Parameters
SIDE (input) CHARACTER*1 = 'R': compute right eigenvectors only; = 'L': compute left eigenvectors only; = 'B': compute both right and left eigenvectors. /param>
Parameters
HOWMNY (input) CHARACTER*1 = 'A': compute all right and/or left eigenvectors; = 'B': compute all right and/or left eigenvectors, backtransformed by the matrices in VR and/or VL; = 'S': compute selected right and/or left eigenvectors, as indicated by the logical array SELECT. /param>
Parameters
SELECT (input/output) LOGICAL array, dimension (N) If HOWMNY = 'S', SELECT specifies the eigenvectors to be computed. If w(j) is a real eigenvalue, the corresponding real eigenvector is computed if SELECT(j) is .TRUE.. If w(j) and w(j+1) are the real and imaginary parts of a complex eigenvalue, the corresponding complex eigenvector is computed if either SELECT(j) or SELECT(j+1) is .TRUE., and on exit SELECT(j) is set to .TRUE. and SELECT(j+1) is set to .FALSE.. Not referenced if HOWMNY = 'A' or 'B'. /param>
Parameters
N (input) INTEGER The order of the matrix T. N .GE. 0. /param>
Parameters
T (input) DOUBLE PRECISION array, dimension (LDT,N) The upper quasi-triangular matrix T in Schur canonical form. /param>
Parameters
LDT (input) INTEGER The leading dimension of the array T. LDT .GE. max(1,N). /param>
Parameters
VL (input/output) DOUBLE PRECISION array, dimension (LDVL,MM) On entry, if SIDE = 'L' or 'B' and HOWMNY = 'B', VL must contain an N-by-N matrix Q (usually the orthogonal matrix Q of Schur vectors returned by DHSEQR). On exit, if SIDE = 'L' or 'B', VL contains: if HOWMNY = 'A', the matrix Y of left eigenvectors of T; if HOWMNY = 'B', the matrix Q*Y; if HOWMNY = 'S', the left eigenvectors of T specified by SELECT, stored consecutively in the columns of VL, in the same order as their eigenvalues. A complex eigenvector corresponding to a complex eigenvalue is stored in two consecutive columns, the first holding the real part, and the second the imaginary part. Not referenced if SIDE = 'R'. /param>
Parameters
LDVL (input) INTEGER The leading dimension of the array VL. LDVL .GE. 1, and if SIDE = 'L' or 'B', LDVL .GE. N. /param>
Parameters
VR (input/output) DOUBLE PRECISION array, dimension (LDVR,MM) On entry, if SIDE = 'R' or 'B' and HOWMNY = 'B', VR must contain an N-by-N matrix Q (usually the orthogonal matrix Q of Schur vectors returned by DHSEQR). On exit, if SIDE = 'R' or 'B', VR contains: if HOWMNY = 'A', the matrix X of right eigenvectors of T; if HOWMNY = 'B', the matrix Q*X; if HOWMNY = 'S', the right eigenvectors of T specified by SELECT, stored consecutively in the columns of VR, in the same order as their eigenvalues. A complex eigenvector corresponding to a complex eigenvalue is stored in two consecutive columns, the first holding the real part and the second the imaginary part. Not referenced if SIDE = 'L'. /param>
Parameters
LDVR (input) INTEGER The leading dimension of the array VR. LDVR .GE. 1, and if SIDE = 'R' or 'B', LDVR .GE. N. /param>
Parameters
MM (input) INTEGER The number of columns in the arrays VL and/or VR. MM .GE. M. /param>
Parameters
M (output) INTEGER The number of columns in the arrays VL and/or VR actually used to store the eigenvectors. If HOWMNY = 'A' or 'B', M is set to N. Each selected real eigenvector occupies one column and each selected complex eigenvector occupies two columns. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (3*N) /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.DTREVC.ONE, DotNumerics.LinearAlgebra.CSLapack.DAXPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DDOT.Run(), DotNumerics.LinearAlgebra.CSLapack.IDAMAX.Run(), DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLABAD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALN2.Run(), DotNumerics.LinearAlgebra.CSLapack.DTREVC.X, and DotNumerics.LinearAlgebra.CSLapack.DTREVC.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DTREVC._lsame private
_idamax
IDAMAX DotNumerics.LinearAlgebra.CSLapack.DTREVC._idamax private
_ddot
DDOT DotNumerics.LinearAlgebra.CSLapack.DTREVC._ddot private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DTREVC._dlamch private
_daxpy
DAXPY DotNumerics.LinearAlgebra.CSLapack.DTREVC._daxpy private
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DTREVC._dcopy private
_dgemv
DGEMV DotNumerics.LinearAlgebra.CSLapack.DTREVC._dgemv private
_dlaln2
DLALN2 DotNumerics.LinearAlgebra.CSLapack.DTREVC._dlaln2 private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DTREVC._dscal private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DTREVC._xerbla private
_dlabad
DLABAD DotNumerics.LinearAlgebra.CSLapack.DTREVC._dlabad private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DTREVC.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTREVC.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DTREVC.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTREVC.Run().
X
double [] DotNumerics.LinearAlgebra.CSLapack.DTREVC.X = new double[2 * 2] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTREVC.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dtrevc.cs