Doc: IGLib EXTENDED: NUnit.Framework.Internal.RandomizerTests.Repeatability Class Reference
NUnit.Framework.Internal.RandomizerTests.Repeatability Class Reference
Static Public Member Functions
static void RandomizersWithSameSeedsReturnSameValues ()
static void RandomizersWithDifferentSeedsReturnDifferentValues ()
static void ReturnsSameRandomizerForSameParameter ()
static void ReturnsSameRandomizerForDifferentParametersOfSameMethod ()
static void ReturnsSameRandomizerForSameMethod ()
static void ReturnsDifferentRandomizersForDifferentMethods ()
Static Private Member Functions
static void TestMethod1 (int x, int y)
static void TestMethod2 (int x, int y)
Static Private Attributes
static readonly MethodInfo testMethod1
static readonly MethodInfo testMethod2
Member Function Documentation
RandomizersWithSameSeedsReturnSameValues()
static void NUnit.Framework.Internal.RandomizerTests.Repeatability.RandomizersWithSameSeedsReturnSameValues () inline static
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
RandomizersWithDifferentSeedsReturnDifferentValues()
static void NUnit.Framework.Internal.RandomizerTests.Repeatability.RandomizersWithDifferentSeedsReturnDifferentValues () inline static
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
ReturnsSameRandomizerForSameParameter()
static void NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsSameRandomizerForSameParameter () inline static
References NUnit.Framework.Internal.Randomizer.GetRandomizer(), NUnit.Framework.Is.SameAs(), NUnit.Framework.Internal.RandomizerTests.Repeatability.testMethod1, and NUnit.Framework.Assert.That().
ReturnsSameRandomizerForDifferentParametersOfSameMethod()
static void NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsSameRandomizerForDifferentParametersOfSameMethod () inline static
References NUnit.Framework.Internal.Randomizer.GetRandomizer(), NUnit.Framework.Is.SameAs(), NUnit.Framework.Internal.RandomizerTests.Repeatability.testMethod1, and NUnit.Framework.Assert.That().
ReturnsSameRandomizerForSameMethod()
static void NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsSameRandomizerForSameMethod () inline static
References NUnit.Framework.Internal.Randomizer.GetRandomizer(), NUnit.Framework.Is.SameAs(), NUnit.Framework.Internal.RandomizerTests.Repeatability.testMethod1, and NUnit.Framework.Assert.That().
ReturnsDifferentRandomizersForDifferentMethods()
static void NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsDifferentRandomizersForDifferentMethods () inline static
References NUnit.Framework.Internal.Randomizer.GetRandomizer(), NUnit.Framework.Is.Not, NUnit.Framework.Internal.RandomizerTests.Repeatability.testMethod1, NUnit.Framework.Internal.RandomizerTests.Repeatability.testMethod2, and NUnit.Framework.Assert.That().
TestMethod1()
static void NUnit.Framework.Internal.RandomizerTests.Repeatability.TestMethod1 (int x, int y) inline static private
TestMethod2()
static void NUnit.Framework.Internal.RandomizerTests.Repeatability.TestMethod2 (int x, int y) inline static private
Member Data Documentation
testMethod1
readonly MethodInfo NUnit.Framework.Internal.RandomizerTests.Repeatability.testMethod1 static private
Initial value:
=
                typeof(Repeatability).GetMethod("TestMethod1", BindingFlags.NonPublic | BindingFlags.Static)
Referenced by NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsDifferentRandomizersForDifferentMethods(), NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsSameRandomizerForDifferentParametersOfSameMethod(), NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsSameRandomizerForSameMethod(), and NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsSameRandomizerForSameParameter().
testMethod2
readonly MethodInfo NUnit.Framework.Internal.RandomizerTests.Repeatability.testMethod2 static private
Initial value:
=
                typeof(Repeatability).GetMethod("TestMethod2", BindingFlags.NonPublic | BindingFlags.Static)
Referenced by NUnit.Framework.Internal.RandomizerTests.Repeatability.ReturnsDifferentRandomizersForDifferentMethods().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/RandomizerTests.cs