Doc: IGLib EXTENDED: lbfgs Class Reference
lbfgs Class Reference
Classes
struct lbfgsreport
struct lbfgsstate
Static Public Member Functions
static void minlbfgs (int n, int m, ref double[] x, double epsg, double epsf, double epsx, int maxits, int flags, ref lbfgsstate state)
static bool minlbfgsiteration (ref lbfgsstate state)
static void minlbfgsresults (ref lbfgsstate state, ref double[] x, ref lbfgsreport rep)
Static Public Attributes
const double ftol = 0.0001
const double xtol = 100*AP.Math.MachineEpsilon
const double gtol = 0.9
const int maxfev = 20
const double stpmin = 1.0E-20
const double stpmax = 1.0E20
Static Private Member Functions
static void mcsrch (int n, ref double[] x, ref double f, ref double[] g, ref double[] s, ref double stp, ref int info, ref int nfev, ref double[] wa, ref lbfgsstate state, ref int stage)
static void mcstep (ref double stx, ref double fx, ref double dx, ref double sty, ref double fy, ref double dy, ref double stp, double fp, double dp, ref bool brackt, double stmin, double stmax, ref int info)
Member Function Documentation
minlbfgs()
static void lbfgs.minlbfgs (int n, int m, ref double[] x, double epsg, double epsf, double epsx, int maxits, int flags, ref lbfgsstate state) inline static
minlbfgsiteration()
static bool lbfgs.minlbfgsiteration (ref lbfgsstate state) inline static
References mcsrch().
minlbfgsresults()
static void lbfgs.minlbfgsresults (ref lbfgsstate state, ref double[] x, ref lbfgsreport rep) inline static
mcsrch()
static void lbfgs.mcsrch (int n, ref double[] x, ref double f, ref double[] g, ref double[] s, ref double stp, ref int info, ref int nfev, ref double[] wa, ref lbfgsstate state, ref int stage) inline static private
References ftol, gtol, maxfev, mcstep(), stpmax, stpmin, and xtol.
Referenced by minlbfgsiteration().
mcstep()
static void lbfgs.mcstep (ref double stx, ref double fx, ref double dx, ref double sty, ref double fy, ref double dy, ref double stp, double fp, double dp, ref bool brackt, double stmin, double stmax, ref int info) inline static private
References AP.Math.Sqr().
Referenced by mcsrch().
Member Data Documentation
ftol
const double lbfgs.ftol = 0.0001 static
Referenced by mcsrch().
xtol
const double lbfgs.xtol = 100*AP.Math.MachineEpsilon static
Referenced by mcsrch().
gtol
const double lbfgs.gtol = 0.9 static
Referenced by mcsrch().
maxfev
const int lbfgs.maxfev = 20 static
Referenced by mcsrch().
stpmin
const double lbfgs.stpmin = 1.0E-20 static
Referenced by mcsrch().
stpmax
const double lbfgs.stpmax = 1.0E20 static
Referenced by mcsrch().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/lbfgs.cs