Doc: IGLib EXTENDED: Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution Class Reference
Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution Class Reference
Represents a discrete distribution as a continous distribution.
Public Member Functions
DiscreteAsContinuousDistribution (DiscreteDistribution distribution)
Initializes a new shim that represents a discrete distribution as a continuous distribution.
DiscreteAsContinuousDistribution (DiscreteDistribution distribution, Interval support)
Initializes a new shim that represents a discrete distribution as a continuous distribution.
override double LeftProbability (double x)
Returns the cumulative probability to the left of (below) the given point.
override double RightProbability (double x)
Return the cumulative probability to the right of (above) the given point.
override double ProbabilityDensity (double x)
Not valid for discrete distributions.
override double Moment (int n)
Computes a raw moment of the distribution.
override double MomentAboutMean (int n)
Computes a central moment of the distribution.
override double InverseLeftProbability (double P)
Returns the point at which the cumulative distribution function attains a given value.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double InverseRightProbability (double Q)
Returns the point at which the right probability function attains the given value.
override double Moment (int r)
Computes a raw moment of the distribution.
override double MomentAboutMean (int r)
Computes a central moment of the distribution.
virtual double ExpectationValue (Func< double, double > f)
Computes the expectation value of the given function.
virtual double GetRandomValue (Random rng)
Returns a random value.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Cumulant (int r)
Computes a cumulant of the distribution.
Properties
override double Mean [get]
override double Variance [get]
override double Skewness [get]
override Interval Support [get]
Properties inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double Median [get]
Gets the median of the distribution.
virtual Interval Support [get]
Gets the interval over which the distribution is nonvanishing.
Properties inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Mean [get]
Gets the mean of the distribution.
virtual double Variance [get]
Gets the variance of the distribution.
virtual double StandardDeviation [get]
Gets the standard deviation of the distribution.
virtual double Skewness [get]
Gets the skewness of the distribution.
virtual double ExcessKurtosis [get]
Gets the excess kurtosis of the distribution.
Private Member Functions
void ComputeEffectiveBin (double x, out int ki, out double kf)
Private Attributes
DiscreteDistribution d
Interval xSupport
Detailed Description
Represents a discrete distribution as a continous distribution.
Constructor & Destructor Documentation
DiscreteAsContinuousDistribution() [1/2]
Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.DiscreteAsContinuousDistribution (DiscreteDistribution distribution) inline
Initializes a new shim that represents a discrete distribution as a continuous distribution.
Parameters
distribution The discrete distiribution to represent.
References Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.d, Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Maximum, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Minimum, and Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.xSupport.
DiscreteAsContinuousDistribution() [2/2]
Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.DiscreteAsContinuousDistribution (DiscreteDistribution distribution, Interval support) inline
Initializes a new shim that represents a discrete distribution as a continuous distribution.
Parameters
distribution The discrete distiribution to represent.
support The continuous support interval into which the discrete support interval is to be mapped.
References Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.d, and Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.xSupport.
Member Function Documentation
ComputeEffectiveBin()
void Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.ComputeEffectiveBin (double x, out int ki, out double kf) inline private
References Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.d, Meta.Numerics.Interval.LeftEndpoint, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Maximum, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Minimum, Meta.Numerics.Interval.Width, and Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.xSupport.
Referenced by Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.ProbabilityDensity(), and Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.RightProbability().
LeftProbability()
override double Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.LeftProbability (double x) inline virtual
Returns the cumulative probability to the left of (below) the given point.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.ComputeEffectiveBin(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.d, Meta.Numerics.Interval.LeftEndpoint, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.LeftExclusiveProbability(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ProbabilityMass(), Meta.Numerics.Interval.RightEndpoint, and Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.xSupport.
RightProbability()
override double Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.RightProbability (double x) inline virtual
Return the cumulative probability to the right of (above) the given point.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.ComputeEffectiveBin(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.d, Meta.Numerics.Interval.LeftEndpoint, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ProbabilityMass(), Meta.Numerics.Interval.RightEndpoint, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.RightExclusiveProbability(), and Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.xSupport.
ProbabilityDensity()
override double Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.ProbabilityDensity (double x) inline virtual
Not valid for discrete distributions.
Parameters
x The argument.
Returns
Throws an exception.
Technically, the PDF of a discrete probability distribution consists of delta functions at the integers, each with a weight equal to the PMF at that integer. Since this is not representable in floating point arithmetic, calling this method is an invalid operation.
Implements Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.ComputeEffectiveBin(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.d, Meta.Numerics.Interval.LeftEndpoint, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Maximum, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Minimum, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ProbabilityMass(), Meta.Numerics.Interval.RightEndpoint, Meta.Numerics.Interval.Width, and Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.xSupport.
Moment()
override double Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.Moment (int n) inline virtual
Computes a raw moment of the distribution.
Implements Meta.Numerics.Statistics.Distributions.UnivariateDistribution.
References Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.d, and Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Moment().
MomentAboutMean()
override double Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.MomentAboutMean (int n) inline virtual
Computes a central moment of the distribution.
Reimplemented from Meta.Numerics.Statistics.Distributions.UnivariateDistribution.
References Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.d, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Maximum, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Minimum, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.MomentAboutMean(), Meta.Numerics.MoreMath.Pow(), Meta.Numerics.Interval.Width, and Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.xSupport.
InverseLeftProbability()
override double Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.InverseLeftProbability (double P) inline virtual
Returns the point at which the cumulative distribution function attains a given value.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.d, and Meta.Numerics.Statistics.Distributions.DiscreteDistribution.InverseLeftProbability().
Member Data Documentation
d
DiscreteDistribution Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.d private
Referenced by Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.ComputeEffectiveBin(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.DiscreteAsContinuousDistribution(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.InverseLeftProbability(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.Moment(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.MomentAboutMean(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.ProbabilityDensity(), and Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.RightProbability().
xSupport
Interval Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.xSupport private
Referenced by Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.ComputeEffectiveBin(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.DiscreteAsContinuousDistribution(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.MomentAboutMean(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.ProbabilityDensity(), and Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.RightProbability().
Property Documentation
Mean
override double Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.Mean get
Variance
override double Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.Variance get
Skewness
override double Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.Skewness get
Support
override Interval Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.Support get
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/Distributions/DiscreteAsContinuousDistribution.cs