Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DORGLQ Class Reference
DotNumerics.LinearAlgebra.CSLapack.DORGLQ Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DORGLQ (DLARFB dlarfb, DLARFT dlarft, DORGL2 dorgl2, XERBLA xerbla, ILAENV ilaenv)
DORGLQ ()
void Run (int M, int N, int K, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
DLARFB _dlarfb
DLARFT _dlarft
DORGL2 _dorgl2
XERBLA _xerbla
ILAENV _ilaenv
Static Private Attributes
const double ZERO = 0.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DORGLQ generates an M-by-N real matrix Q with orthonormal rows, which is defined as the first M rows of a product of K elementary reflectors of order N
Q = H(k) . . . H(2) H(1)
as returned by DGELQF.
/summary>
Constructor & Destructor Documentation
DORGLQ() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DORGLQ.DORGLQ (DLARFB dlarfb, DLARFT dlarft, DORGL2 dorgl2, XERBLA xerbla, ILAENV ilaenv) inline
DORGLQ() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DORGLQ.DORGLQ () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DORGLQ.Run (int M, int N, int K, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DORGLQ generates an M-by-N real matrix Q with orthonormal rows, which is defined as the first M rows of a product of K elementary reflectors of order N
Q = H(k) . . . H(2) H(1)
as returned by DGELQF.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix Q. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix Q. N .GE. M. /param>
Parameters
K (input) INTEGER The number of elementary reflectors whose product defines the matrix Q. M .GE. K .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the i-th row must contain the vector which defines the elementary reflector H(i), for i = 1,2,...,k, as returned by DGELQF in the first k rows of its array argument A. On exit, the M-by-N matrix Q. /param>
Parameters
LDA (input) INTEGER The first dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
TAU (input) DOUBLE PRECISION array, dimension (K) TAU(i) must contain the scalar factor of the elementary reflector H(i), as returned by DGELQF. /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. max(1,M). For optimum performance LWORK .GE. M*NB, where NB is the optimal blocksize.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument has an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGL2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFT.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFB.Run(), and DotNumerics.LinearAlgebra.CSLapack.DORGLQ.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORGBR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run().
Member Data Documentation
_dlarfb
DLARFB DotNumerics.LinearAlgebra.CSLapack.DORGLQ._dlarfb private
_dlarft
DLARFT DotNumerics.LinearAlgebra.CSLapack.DORGLQ._dlarft private
_dorgl2
DORGL2 DotNumerics.LinearAlgebra.CSLapack.DORGLQ._dorgl2 private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DORGLQ._xerbla private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DORGLQ._ilaenv private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DORGLQ.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORGLQ.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dorglq.cs