Doc: IGLib EXTENDED: alglib.testbasestatunit Class Reference
alglib.testbasestatunit Class Reference
Static Public Member Functions
static bool testbasestat (bool silent)
static bool testbasestat (bool silent)
static bool _pexec_testbasestat (bool silent)
Static Private Member Functions
static void testranking (ref bool err)
Member Function Documentation
testbasestat() [1/2]
static bool alglib.testbasestatunit.testbasestat (bool silent) inline static
References alglib.basestat.cov2(), alglib.basestat.covm(), alglib.basestat.covm2(), alglib.math.machineepsilon, alglib.basestat.pearsoncorr2(), alglib.basestat.pearsoncorrm(), alglib.basestat.pearsoncorrm2(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.basestat.sampleadev(), alglib.basestat.samplekurtosis(), alglib.basestat.samplemean(), alglib.basestat.samplemedian(), alglib.basestat.samplemoments(), alglib.basestat.samplepercentile(), alglib.basestat.sampleskewness(), alglib.basestat.samplevariance(), alglib.basestat.spearmancorr2(), alglib.basestat.spearmancorrm(), alglib.basestat.spearmancorrm2(), and alglib.math.sqr().
Referenced by alglib.testbasestatunit._pexec_testbasestat(), and _Test.Main().
testbasestat() [2/2]
static bool alglib.testbasestatunit.testbasestat (bool silent) inline static
References alglib.basestat.cov2(), alglib.basestat.covm(), alglib.basestat.covm2(), alglib.math.machineepsilon, alglib.basestat.pearsoncorr2(), alglib.basestat.pearsoncorrm(), alglib.basestat.pearsoncorrm2(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.basestat.sampleadev(), alglib.basestat.samplekurtosis(), alglib.basestat.samplemean(), alglib.basestat.samplemedian(), alglib.basestat.samplemoments(), alglib.basestat.samplepercentile(), alglib.basestat.sampleskewness(), alglib.basestat.samplevariance(), alglib.basestat.spearmancorr2(), alglib.basestat.spearmancorrm(), alglib.basestat.spearmancorrm2(), alglib.math.sqr(), and alglib.testbasestatunit.testranking().
_pexec_testbasestat()
static bool alglib.testbasestatunit._pexec_testbasestat (bool silent) inline static
References alglib.testbasestatunit.testbasestat().
Referenced by _Test.Main().
testranking()
static void alglib.testbasestatunit.testranking (ref bool err) inline static private
References alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.basestat.rankdata(), and alglib.basestat.rankdatacentered().
Referenced by alglib.testbasestatunit.testbasestat().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs