Doc: IGLib EXTENDED: NUnit.Framework.Constraints.RangeConstraintTest Class Reference
NUnit.Framework.Constraints.RangeConstraintTest Class Reference
Public Member Functions
void SetUp ()
void InvalidDataThrowsArgumentException (object data)
void UsesProvidedIComparer ()
void UsesProvidedGenericComparer ()
void UsesProvidedGenericComparison ()
void UsesProvidedLambda ()
void ShouldThrowExceptionIfFromIsLessThanTo ()
Public Member Functions inherited from NUnit.Framework.Constraints.ConstraintTestBase
void SucceedsWithGoodValues (object value)
void FailsWithBadValues (object badValue, string message)
Public Member Functions inherited from NUnit.Framework.Constraints.ConstraintTestBaseNoData
void ProvidesProperDescription ()
void ProvidesProperStringRepresentation ()
Private Attributes
RangeConstraint rangeConstraint
Static Private Attributes
static object[] SuccessData = new object[] { 5, 23, 42 }
static object[] FailureData = new object[] { new object[] { 4, "4" }, new object[] { 43, "43" } }
Additional Inherited Members
Protected Attributes inherited from NUnit.Framework.Constraints.ConstraintTestBaseNoData
Constraint theConstraint
string expectedDescription = "<NOT SET>"
string stringRepresentation = "<NOT SET>"
Member Function Documentation
SetUp()
void NUnit.Framework.Constraints.RangeConstraintTest.SetUp () inline
References NUnit.Framework.Constraints.ConstraintTestBaseNoData.expectedDescription, NUnit.Framework.Constraints.RangeConstraintTest.rangeConstraint, NUnit.Framework.Constraints.ConstraintTestBaseNoData.stringRepresentation, and NUnit.Framework.Constraints.ConstraintTestBaseNoData.theConstraint.
InvalidDataThrowsArgumentException()
void NUnit.Framework.Constraints.RangeConstraintTest.InvalidDataThrowsArgumentException (object data) inline
References NUnit.Framework.Constraints.ConstraintTestBaseNoData.theConstraint, and NUnit.Framework.Assert.Throws().
UsesProvidedIComparer()
void NUnit.Framework.Constraints.RangeConstraintTest.UsesProvidedIComparer () inline
References NUnit.Framework.Constraints.RangeConstraintTest.rangeConstraint, NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.RangeConstraint.Using().
UsesProvidedGenericComparer()
void NUnit.Framework.Constraints.RangeConstraintTest.UsesProvidedGenericComparer () inline
References NUnit.Framework.Constraints.RangeConstraintTest.rangeConstraint, NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.RangeConstraint.Using().
UsesProvidedGenericComparison()
void NUnit.Framework.Constraints.RangeConstraintTest.UsesProvidedGenericComparison () inline
References NUnit.Framework.Constraints.RangeConstraintTest.rangeConstraint, NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.RangeConstraint.Using().
UsesProvidedLambda()
void NUnit.Framework.Constraints.RangeConstraintTest.UsesProvidedLambda () inline
References NUnit.Framework.Constraints.RangeConstraintTest.rangeConstraint, NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.RangeConstraint.Using().
ShouldThrowExceptionIfFromIsLessThanTo()
void NUnit.Framework.Constraints.RangeConstraintTest.ShouldThrowExceptionIfFromIsLessThanTo () inline
References NUnit.Framework.Assert.Throws().
Member Data Documentation
rangeConstraint
RangeConstraint NUnit.Framework.Constraints.RangeConstraintTest.rangeConstraint private
Referenced by NUnit.Framework.Constraints.RangeConstraintTest.SetUp(), NUnit.Framework.Constraints.RangeConstraintTest.UsesProvidedGenericComparer(), NUnit.Framework.Constraints.RangeConstraintTest.UsesProvidedGenericComparison(), NUnit.Framework.Constraints.RangeConstraintTest.UsesProvidedIComparer(), and NUnit.Framework.Constraints.RangeConstraintTest.UsesProvidedLambda().
SuccessData
object [] NUnit.Framework.Constraints.RangeConstraintTest.SuccessData = new object[] { 5, 23, 42 } static private
FailureData
object [] NUnit.Framework.Constraints.RangeConstraintTest.FailureData = new object[] { new object[] { 4, "4" }, new object[] { 43, "43" } } static private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/RangeConstraintTests.cs