Doc: IGLib EXTENDED: NUnit.Engine.Addins.NUnit2XmlResultWriter Class Reference
NUnit.Engine.Addins.NUnit2XmlResultWriter Class Reference
Public Member Functions
void CheckWritability (string outputPath)
Checks if the output is writable. If the output is not writable, this method should throw an exception.
void WriteResultFile (XmlNode result, string outputPath)
Writes result to the specified output path.
void WriteResultFile (XmlNode result, TextWriter writer)
Writes result to a TextWriter.
Private Member Functions
void WriteXmlOutput (XmlNode result, XmlWriter xmlWriter)
void InitializeXmlFile (XmlNode result)
void WriteCultureInfo ()
void WriteEnvironment ()
string TranslateResult (string resultState, string label)
void WriteResultElement (XmlNode result)
void TerminateXmlFile ()
void StartTestElement (XmlNode result)
void WriteCategoriesElement (XmlNode properties)
void WritePropertiesElement (XmlNode properties)
void WriteReasonElement (string message)
void WriteFailureElement (string message, string stackTrace)
void WriteChildResults (XmlNode result)
void WriteCData (string text)
Static Private Member Functions
static string CharacterSafeString (string encodedString)
Makes string safe for xml parsing, replacing control chars with '?'
Private Attributes
XmlWriter xmlWriter
Member Function Documentation
CheckWritability()
void NUnit.Engine.Addins.NUnit2XmlResultWriter.CheckWritability (string outputPath) inline
Checks if the output is writable. If the output is not writable, this method should throw an exception.
Parameters
outputPath
Implements NUnit.Engine.Extensibility.IResultWriter.
WriteResultFile() [1/2]
void NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteResultFile (XmlNode resultNode, string outputPath) inline
Writes result to the specified output path.
Parameters
resultNode XmlNode for the result
outputPath Path to which it should be written
Implements NUnit.Engine.Extensibility.IResultWriter.
WriteResultFile() [2/2]
void NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteResultFile (XmlNode resultNode, TextWriter writer) inline
Writes result to a TextWriter.
Parameters
resultNode XmlNode for the result
writer TextWriter to which it should be written
Implements NUnit.Engine.Extensibility.IResultWriter.
References NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteXmlOutput(), and NUnit.Engine.Addins.NUnit2XmlResultWriter.xmlWriter.
WriteXmlOutput()
void NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteXmlOutput (XmlNode result, XmlWriter xmlWriter) inline private
References NUnit.Engine.Addins.NUnit2XmlResultWriter.InitializeXmlFile(), NUnit.Engine.Addins.NUnit2XmlResultWriter.TerminateXmlFile(), NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteResultElement(), and NUnit.Engine.Addins.NUnit2XmlResultWriter.xmlWriter.
Referenced by NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteResultFile().
InitializeXmlFile()
void NUnit.Engine.Addins.NUnit2XmlResultWriter.InitializeXmlFile (XmlNode result) inline private
References NUnit.Engine.Addins.NUnit2ResultSummary.Errors, NUnit.Engine.Addins.NUnit2ResultSummary.Failures, NUnit.Engine.Addins.NUnit2ResultSummary.Ignored, NUnit.Engine.Addins.NUnit2ResultSummary.Inconclusive, NUnit.Engine.Addins.NUnit2ResultSummary.NotRunnable, NUnit.Engine.Addins.NUnit2ResultSummary.ResultCount, NUnit.Engine.Addins.NUnit2ResultSummary.Skipped, NUnit.Engine.Addins.NUnit2ResultSummary.TestsNotRun, NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteCultureInfo(), NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteEnvironment(), and NUnit.Engine.Addins.NUnit2XmlResultWriter.xmlWriter.
Referenced by NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteXmlOutput().
WriteCultureInfo()
void NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteCultureInfo () inline private
References NUnit.Engine.Addins.NUnit2XmlResultWriter.xmlWriter.
Referenced by NUnit.Engine.Addins.NUnit2XmlResultWriter.InitializeXmlFile().
WriteEnvironment()
void NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteEnvironment () inline private
References NUnit.Engine.Addins.NUnit2XmlResultWriter.xmlWriter.
Referenced by NUnit.Engine.Addins.NUnit2XmlResultWriter.InitializeXmlFile().
TranslateResult()
string NUnit.Engine.Addins.NUnit2XmlResultWriter.TranslateResult (string resultState, string label) inline private
Referenced by NUnit.Engine.Addins.NUnit2XmlResultWriter.StartTestElement().
WriteResultElement()
void NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteResultElement (XmlNode result) inline private
References NUnit.Engine.Addins.NUnit2XmlResultWriter.StartTestElement(), NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteCategoriesElement(), NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteChildResults(), NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteFailureElement(), NUnit.Engine.Addins.NUnit2XmlResultWriter.WritePropertiesElement(), NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteReasonElement(), and NUnit.Engine.Addins.NUnit2XmlResultWriter.xmlWriter.
Referenced by NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteChildResults(), and NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteXmlOutput().
TerminateXmlFile()
void NUnit.Engine.Addins.NUnit2XmlResultWriter.TerminateXmlFile () inline private
References NUnit.Engine.Addins.NUnit2XmlResultWriter.xmlWriter.
Referenced by NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteXmlOutput().
StartTestElement()
void NUnit.Engine.Addins.NUnit2XmlResultWriter.StartTestElement (XmlNode result) inline private
References NUnit.Engine.Addins.NUnit2XmlResultWriter.TranslateResult(), and NUnit.Engine.Addins.NUnit2XmlResultWriter.xmlWriter.
Referenced by NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteResultElement().
WriteCategoriesElement()
void NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteCategoriesElement (XmlNode properties) inline private
References NUnit.Engine.Addins.NUnit2XmlResultWriter.xmlWriter.
Referenced by NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteResultElement().
WritePropertiesElement()
void NUnit.Engine.Addins.NUnit2XmlResultWriter.WritePropertiesElement (XmlNode properties) inline private
References NUnit.Engine.Addins.NUnit2XmlResultWriter.xmlWriter.
Referenced by NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteResultElement().
WriteReasonElement()
void NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteReasonElement (string message) inline private
References NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteCData(), and NUnit.Engine.Addins.NUnit2XmlResultWriter.xmlWriter.
Referenced by NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteResultElement().
WriteFailureElement()
void NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteFailureElement (string message, string stackTrace) inline private
References NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteCData(), and NUnit.Engine.Addins.NUnit2XmlResultWriter.xmlWriter.
Referenced by NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteResultElement().
WriteChildResults()
void NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteChildResults (XmlNode result) inline private
References NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteResultElement(), and NUnit.Engine.Addins.NUnit2XmlResultWriter.xmlWriter.
Referenced by NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteResultElement().
CharacterSafeString()
static string NUnit.Engine.Addins.NUnit2XmlResultWriter.CharacterSafeString (string encodedString) inline static private
Makes string safe for xml parsing, replacing control chars with '?'
Parameters
encodedString string to make safe
Returns
xml safe string
WriteCData()
void NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteCData (string text) inline private
References NUnit.Engine.Addins.NUnit2XmlResultWriter.xmlWriter.
Referenced by NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteFailureElement(), and NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteReasonElement().
Member Data Documentation
xmlWriter
XmlWriter NUnit.Engine.Addins.NUnit2XmlResultWriter.xmlWriter private
Referenced by NUnit.Engine.Addins.NUnit2XmlResultWriter.InitializeXmlFile(), NUnit.Engine.Addins.NUnit2XmlResultWriter.StartTestElement(), NUnit.Engine.Addins.NUnit2XmlResultWriter.TerminateXmlFile(), NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteCategoriesElement(), NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteCData(), NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteChildResults(), NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteCultureInfo(), NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteEnvironment(), NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteFailureElement(), NUnit.Engine.Addins.NUnit2XmlResultWriter.WritePropertiesElement(), NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteReasonElement(), NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteResultElement(), NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteResultFile(), and NUnit.Engine.Addins.NUnit2XmlResultWriter.WriteXmlOutput().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/Addins/nunit-v2-result-writer/NUnit2XmlResultWriter.cs