Doc: IGLib EXTENDED: alglib.lda Class Reference
alglib.lda Class Reference
Static Public Member Functions
static void fisherlda (double[,] xy, int npoints, int nvars, int nclasses, ref int info, ref double[] w)
static void fisherldan (double[,] xy, int npoints, int nvars, int nclasses, ref int info, ref double[,] w)
static void fisherlda (double[,] xy, int npoints, int nvars, int nclasses, ref int info, ref double[] w)
static void fisherldan (double[,] xy, int npoints, int nvars, int nclasses, ref int info, ref double[,] w)
Member Function Documentation
fisherlda() [1/2]
static void alglib.lda.fisherlda (double xy[,], int npoints, int nvars, int nclasses, ref int info, ref double[] w) inline static
References alglib.lda.fisherldan().
Referenced by alglib.fisherlda(), and alglib.testldaunit.testlda().
fisherldan() [1/2]
static void alglib.lda.fisherldan (double xy[,], int npoints, int nvars, int nclasses, ref int info, ref double w[,]) inline static
References alglib.ap.assert(), alglib.math.machineepsilon, alglib.blas.matrixmatrixmultiply(), and alglib.evd.smatrixevd().
Referenced by alglib.lda.fisherlda(), alglib.fisherldan(), and alglib.testldaunit.testlda().
fisherlda() [2/2]
static void alglib.lda.fisherlda (double xy[,], int npoints, int nvars, int nclasses, ref int info, ref double[] w) inline static
fisherldan() [2/2]
static void alglib.lda.fisherldan (double xy[,], int npoints, int nvars, int nclasses, ref int info, ref double w[,]) inline static
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/dataanalysis.cs