Doc: IGLib EXTENDED: TestWS_Console.Test_Console Class Reference
TestWS_Console.Test_Console Class Reference
Static Private Member Functions
static void Main (string[] args)
static bool run (string[] args)
static void compareXmls (String currentScenario)
static void writeXml (String logPath)
static void writeLog (String logPath, String result)
static String displayResults (TestWS_Lib.TestWS_Lib lib)
static List< ThreadData > xmlToThreadData (String dirPath, String xmlPath)
Static Private Attributes
static StreamReader sr
static TestWS_Lib.TestWS_Lib lib
static String expectedResult
static bool resultOK
static String resultMessage
Member Function Documentation
Main()
static void TestWS_Console.Test_Console.Main (string[] args) inline static private
References TestWS_Console.Test_Console.run().
run()
static bool TestWS_Console.Test_Console.run (string[] args) inline static private
References TestWS_Console.Test_Console.compareXmls(), TestWS_Console.Test_Console.displayResults(), TestWS_Console.Test_Console.lib, TestWS_Console.Test_Console.resultMessage, TestWS_Console.Test_Console.resultOK, TestWS_Console.Test_Console.sr, TestWS_Lib.TestWS_Lib.startTesting(), TestWS_Console.Test_Console.writeLog(), TestWS_Console.Test_Console.writeXml(), and TestWS_Console.Test_Console.xmlToThreadData().
Referenced by TestWS_Console.Test_Console.Main().
compareXmls()
static void TestWS_Console.Test_Console.compareXmls (String currentScenario) inline static private
References TestWS_Console.Test_Console.expectedResult, TestWS_Console.Test_Console.lib, TestWS_Lib.TestWS_Lib.ResultDocument, TestWS_Console.Test_Console.resultMessage, TestWS_Console.Test_Console.resultOK, and TestWS_Console.Test_Console.sr.
Referenced by TestWS_Console.Test_Console.run().
writeXml()
static void TestWS_Console.Test_Console.writeXml (String logPath) inline static private
References TestWS_Console.Test_Console.lib, and TestWS_Lib.TestWS_Lib.ResultDocument.
Referenced by TestWS_Console.Test_Console.run().
writeLog()
static void TestWS_Console.Test_Console.writeLog (String logPath, String result) inline static private
Referenced by TestWS_Console.Test_Console.run().
displayResults()
static String TestWS_Console.Test_Console.displayResults (TestWS_Lib.TestWS_Lib lib) inline static private
References TestWS_Console.Test_Console.lib, TestWS_Lib.TestWS_Lib.ProgressValue, TestWS_Lib.TestWS_Lib.Result, and TestWS_Lib.TestWS_Lib.threadsRunning().
Referenced by TestWS_Console.Test_Console.run().
xmlToThreadData()
static List<ThreadData> TestWS_Console.Test_Console.xmlToThreadData (String dirPath, String xmlPath) inline static private
References TestWS_Console.Test_Console.expectedResult, and TestWS_Console.Test_Console.sr.
Referenced by TestWS_Console.Test_Console.run().
Member Data Documentation
sr
StreamReader TestWS_Console.Test_Console.sr static private
Referenced by TestWS_Console.Test_Console.compareXmls(), TestWS_Console.Test_Console.run(), and TestWS_Console.Test_Console.xmlToThreadData().
lib
TestWS_Lib.TestWS_Lib TestWS_Console.Test_Console.lib static private
Referenced by TestWS_Console.Test_Console.compareXmls(), TestWS_Console.Test_Console.displayResults(), TestWS_Console.Test_Console.run(), and TestWS_Console.Test_Console.writeXml().
expectedResult
String TestWS_Console.Test_Console.expectedResult static private
Referenced by TestWS_Console.Test_Console.compareXmls(), and TestWS_Console.Test_Console.xmlToThreadData().
resultOK
bool TestWS_Console.Test_Console.resultOK static private
Referenced by TestWS_Console.Test_Console.compareXmls(), and TestWS_Console.Test_Console.run().
resultMessage
String TestWS_Console.Test_Console.resultMessage static private
Referenced by TestWS_Console.Test_Console.compareXmls(), and TestWS_Console.Test_Console.run().
The documentation for this class was generated from the following file:
igtest/tmp_prem/prefa/95_Test/TestWS_Console/Test_Console.cs