Doc: IGLib EXTENDED: Test.UncertainValueTest Class Reference
Test.UncertainValueTest Class Reference
This is a test class for UncertainValueTest and is intended to contain all UncertainValueTest Unit Tests /summary>
Public Member Functions
void UncertainValueConstructorTest ()
void UncertainValueArithmeticValuesTest ()
void UncertainValueAdditionTriangleTest ()
void UncertainValueSubtractionTriangleTest ()
void UncertainValueMixedArithmeticTest ()
void UncertainValueZeroUncertaintiesTest ()
Properties
TestContext TestContext [get, set]
Gets or sets the test context which provides information about and functionality for the current test run. /summary>
Private Attributes
TestContext testContextInstance
UncertainValue a = new UncertainValue(1.0, 0.5)
UncertainValue b = new UncertainValue(-2.0, 3.0)
Detailed Description
This is a test class for UncertainValueTest and is intended to contain all UncertainValueTest Unit Tests /summary>
Member Function Documentation
UncertainValueConstructorTest()
void Test.UncertainValueTest.UncertainValueConstructorTest () inline
UncertainValueArithmeticValuesTest()
void Test.UncertainValueTest.UncertainValueArithmeticValuesTest () inline
References Test.UncertainValueTest.a, Test.UncertainValueTest.b, and Meta.Numerics.UncertainValue.Value.
UncertainValueAdditionTriangleTest()
void Test.UncertainValueTest.UncertainValueAdditionTriangleTest () inline
References Test.UncertainValueTest.a, Test.UncertainValueTest.b, and Meta.Numerics.UncertainValue.Uncertainty.
UncertainValueSubtractionTriangleTest()
void Test.UncertainValueTest.UncertainValueSubtractionTriangleTest () inline
References Test.UncertainValueTest.a, Test.UncertainValueTest.b, and Meta.Numerics.UncertainValue.Uncertainty.
UncertainValueMixedArithmeticTest()
void Test.UncertainValueTest.UncertainValueMixedArithmeticTest () inline
References Test.UncertainValueTest.a, Test.UncertainValueTest.b, Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
UncertainValueZeroUncertaintiesTest()
void Test.UncertainValueTest.UncertainValueZeroUncertaintiesTest () inline
References Meta.Numerics.UncertainMath.Atan(), Meta.Numerics.UncertainMath.Exp(), Meta.Numerics.UncertainMath.Log(), Meta.Numerics.UncertainMath.Tan(), Meta.Numerics.UncertainValue.Uncertainty, and Meta.Numerics.UncertainValue.Value.
Member Data Documentation
testContextInstance
TestContext Test.UncertainValueTest.testContextInstance private
a
UncertainValue Test.UncertainValueTest.a = new UncertainValue(1.0, 0.5) private
Referenced by Test.UncertainValueTest.UncertainValueAdditionTriangleTest(), Test.UncertainValueTest.UncertainValueArithmeticValuesTest(), Test.UncertainValueTest.UncertainValueMixedArithmeticTest(), and Test.UncertainValueTest.UncertainValueSubtractionTriangleTest().
b
UncertainValue Test.UncertainValueTest.b = new UncertainValue(-2.0, 3.0) private
Referenced by Test.UncertainValueTest.UncertainValueAdditionTriangleTest(), Test.UncertainValueTest.UncertainValueArithmeticValuesTest(), Test.UncertainValueTest.UncertainValueMixedArithmeticTest(), and Test.UncertainValueTest.UncertainValueSubtractionTriangleTest().
Property Documentation
TestContext
TestContext Test.UncertainValueTest.TestContext get set
Gets or sets the test context which provides information about and functionality for the current test run. /summary>
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/UncertainValueTest.cs