Doc: IGLib EXTENDED: NUnit.Framework.Attributes.ValuesAttributeTests Class Reference
NUnit.Framework.Attributes.ValuesAttributeTests Class Reference
Public Member Functions
void ValuesAttributeProvidesSpecifiedValues ()
void CanConvertSmallIntsToShort ([Values(5)]short x)
void CanConvertSmallIntsToByte ([Values(5)]byte x)
void CanConvertSmallIntsToSByte ([Values(5)]sbyte x)
void CanConvertIntToDecimal ([Values(12)]decimal x)
void CanConvertDoubleToDecimal ([Values(12.5)]decimal x)
void CanConvertStringToDecimal ([Values("12.5")]decimal x)
Private Member Functions
void MethodWithValues ([Values(1, 2, 3)] int x)
void CheckValues (string methodName, params object[] expected)
Member Function Documentation
ValuesAttributeProvidesSpecifiedValues()
void NUnit.Framework.Attributes.ValuesAttributeTests.ValuesAttributeProvidesSpecifiedValues () inline
References NUnit.Framework.Attributes.ValuesAttributeTests.CheckValues().
MethodWithValues()
void NUnit.Framework.Attributes.ValuesAttributeTests.MethodWithValues ([Values(1, 2, 3)] int x) inline private
CanConvertSmallIntsToShort()
void NUnit.Framework.Attributes.ValuesAttributeTests.CanConvertSmallIntsToShort ([Values(5)] short x) inline
CanConvertSmallIntsToByte()
void NUnit.Framework.Attributes.ValuesAttributeTests.CanConvertSmallIntsToByte ([Values(5)] byte x) inline
CanConvertSmallIntsToSByte()
void NUnit.Framework.Attributes.ValuesAttributeTests.CanConvertSmallIntsToSByte ([Values(5)] sbyte x) inline
CanConvertIntToDecimal()
void NUnit.Framework.Attributes.ValuesAttributeTests.CanConvertIntToDecimal ([Values(12)] decimal x) inline
CanConvertDoubleToDecimal()
void NUnit.Framework.Attributes.ValuesAttributeTests.CanConvertDoubleToDecimal ([Values(12.5)] decimal x) inline
CanConvertStringToDecimal()
void NUnit.Framework.Attributes.ValuesAttributeTests.CanConvertStringToDecimal ([Values("12.5")] decimal x) inline
CheckValues()
void NUnit.Framework.Attributes.ValuesAttributeTests.CheckValues (string methodName, params object[] expected) inline private
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Attributes.ValuesAttributeTests.ValuesAttributeProvidesSpecifiedValues().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/ValuesAttributeTests.cs