Doc: IGLib EXTENDED: NUnit.Tests.CDataTestFixure Class Reference
NUnit.Tests.CDataTestFixure Class Reference
Public Member Functions
void DemonstrateIllegalSequenceInSuccessMessage ()
void DemonstrateIllegalSequenceAtEndOfSuccessMessage ()
void DemonstrateIllegalSequenceInFailureMessage ()
void DemonstrateIllegalSequenceAtEndOfFailureMessage ()
Static Public Attributes
const int Tests = 4
const int Suites = 1
const int Failures = 2
Member Function Documentation
DemonstrateIllegalSequenceInSuccessMessage()
void NUnit.Tests.CDataTestFixure.DemonstrateIllegalSequenceInSuccessMessage () inline
References NUnit.Framework.Assert.Pass().
DemonstrateIllegalSequenceAtEndOfSuccessMessage()
void NUnit.Tests.CDataTestFixure.DemonstrateIllegalSequenceAtEndOfSuccessMessage () inline
References NUnit.Framework.Assert.Pass().
DemonstrateIllegalSequenceInFailureMessage()
void NUnit.Tests.CDataTestFixure.DemonstrateIllegalSequenceInFailureMessage () inline
References NUnit.Framework.Assert.Fail().
DemonstrateIllegalSequenceAtEndOfFailureMessage()
void NUnit.Tests.CDataTestFixure.DemonstrateIllegalSequenceAtEndOfFailureMessage () inline
References NUnit.Framework.Assert.Fail().
Member Data Documentation
Tests
const int NUnit.Tests.CDataTestFixure.Tests = 4 static
Suites
const int NUnit.Tests.CDataTestFixure.Suites = 1 static
Failures
const int NUnit.Tests.CDataTestFixure.Failures = 2 static
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/mock-assembly/MockAssembly.cs