Doc: IGLib EXTENDED: NUnit.Framework.Assertions.TypeAssertTests Class Reference
NUnit.Framework.Assertions.TypeAssertTests Class Reference
Public Member Functions
void ExactType ()
void ExactTypeFails ()
void IsInstanceOf ()
void IsInstanceOfFails ()
void IsNotInstanceOf ()
void IsNotInstanceOfFails ()
void IsAssignableFrom ()
void IsAssignableFromFails ()
void IsNotAssignableFrom ()
void IsNotAssignableFromFails ()
Member Function Documentation
ExactType()
void NUnit.Framework.Assertions.TypeAssertTests.ExactType () inline
References NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
ExactTypeFails()
void NUnit.Framework.Assertions.TypeAssertTests.ExactTypeFails () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), NUnit.Framework.Assert.Throws(), and NUnit.Framework.Is.TypeOf().
IsInstanceOf()
void NUnit.Framework.Assertions.TypeAssertTests.IsInstanceOf () inline
References NUnit.Framework.Is.InstanceOf(), NUnit.Framework.Assert.IsInstanceOf(), and NUnit.Framework.Assert.That().
IsInstanceOfFails()
void NUnit.Framework.Assertions.TypeAssertTests.IsInstanceOfFails () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.InstanceOf(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
IsNotInstanceOf()
void NUnit.Framework.Assertions.TypeAssertTests.IsNotInstanceOf () inline
References NUnit.Framework.Assert.IsNotInstanceOf(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
IsNotInstanceOfFails()
void NUnit.Framework.Assertions.TypeAssertTests.IsNotInstanceOfFails () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.IsNotInstanceOf(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
IsAssignableFrom()
void NUnit.Framework.Assertions.TypeAssertTests.IsAssignableFrom () inline
References NUnit.Framework.Is.AssignableFrom(), NUnit.Framework.Assert.IsAssignableFrom(), and NUnit.Framework.Assert.That().
IsAssignableFromFails()
void NUnit.Framework.Assertions.TypeAssertTests.IsAssignableFromFails () inline
References NUnit.Framework.Is.AssignableFrom(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
IsNotAssignableFrom()
void NUnit.Framework.Assertions.TypeAssertTests.IsNotAssignableFrom () inline
References NUnit.Framework.Assert.IsNotAssignableFrom(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
IsNotAssignableFromFails()
void NUnit.Framework.Assertions.TypeAssertTests.IsNotAssignableFromFails () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.Not, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/TypeAssertTest.cs