Doc: IGLib EXTENDED: IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere Class Reference
IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere Class Reference
A sphere in which gamma rays are created at random spots, flying off in random directions.
Public Member Functions
double CalcFractionOfEscapedRays ()
Performs a Monte-Carlo simulation and calculates the fraction of rays that escaped from the sphere.
void CalcFracOfEscRaysVsMFPToRadius (double initMFPToRad, double finalMFPToRad)
Calculates the data for the graph of the fraction of escaped rays vs. the MFPToRadiusRatio.
void PrintResults (TextWriter writer)
Prints the solution to the specified text writer.
void PrintResults (string filePath)
Prints the solution to the specified file.
Public Attributes
int NRays = 2000000
The number of rays that are created in the sphere.
double Radius = 1.0
The sphere radius.
double MeanFreePath = 1.0
The mean free path of gamma rays in the sphere.
List< double[]> FracOfEscRaysVsMFPToRadius = new List<double[]>(100)
The data for the graph of the fraction of escaped rays vs. the MFPToRadiusRatio.
int NSamples = 100
The number of samples for the CalcFracOfEscRaysVsMFPToRadius() method.
Properties
double MFPToRadius [get, set]
The ratio of the mean free path vs. the sphere's radius.
Private Attributes
Random RNG = new Random()
A random number generator.
Detailed Description
A sphere in which gamma rays are created at random spots, flying off in random directions.
Member Function Documentation
CalcFractionOfEscapedRays()
double IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.CalcFractionOfEscapedRays () inline
Performs a Monte-Carlo simulation and calculates the fraction of rays that escaped from the sphere.
Returns
The fraction of escaped rays.
References IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.MeanFreePath, IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.NRays, IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.Radius, and IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.RNG.
Referenced by IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.CalcFracOfEscRaysVsMFPToRadius(), and IG.MPetekLib.Application.Scripts.CompPhys._07MCNumberOfEscapedRays.Run().
CalcFracOfEscRaysVsMFPToRadius()
void IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.CalcFracOfEscRaysVsMFPToRadius (double initMFPToRad, double finalMFPToRad) inline
Calculates the data for the graph of the fraction of escaped rays vs. the MFPToRadiusRatio.
Parameters
initMFPToRad Initial MFPToRadiusRatio.
finalMFPToRad Final MFPToRadiusRatio.
References IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.CalcFractionOfEscapedRays(), IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.FracOfEscRaysVsMFPToRadius, IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.MFPToRadius, and IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.NSamples.
PrintResults() [1/2]
void IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.PrintResults (TextWriter writer) inline
Prints the solution to the specified text writer.
Parameters
writer
References IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.FracOfEscRaysVsMFPToRadius, and IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.NSamples.
Referenced by IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.PrintResults().
PrintResults() [2/2]
void IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.PrintResults (string filePath) inline
Prints the solution to the specified file.
If the file exists then it is overwritten.
Parameters
inputFilePath Path of the file where solution is written.
References IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.PrintResults().
Member Data Documentation
NRays
int IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.NRays = 2000000
The number of rays that are created in the sphere.
Referenced by IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.CalcFractionOfEscapedRays().
Radius
double IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.Radius = 1.0
The sphere radius.
Referenced by IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.CalcFractionOfEscapedRays().
MeanFreePath
double IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.MeanFreePath = 1.0
The mean free path of gamma rays in the sphere.
Referenced by IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.CalcFractionOfEscapedRays().
RNG
Random IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.RNG = new Random() private
A random number generator.
Referenced by IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.CalcFractionOfEscapedRays().
FracOfEscRaysVsMFPToRadius
List<double[]> IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.FracOfEscRaysVsMFPToRadius = new List<double[]>(100)
The data for the graph of the fraction of escaped rays vs. the MFPToRadiusRatio.
Referenced by IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.CalcFracOfEscRaysVsMFPToRadius(), and IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.PrintResults().
NSamples
int IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.NSamples = 100
The number of samples for the CalcFracOfEscRaysVsMFPToRadius() method.
Referenced by IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.CalcFracOfEscRaysVsMFPToRadius(), and IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.PrintResults().
Property Documentation
MFPToRadius
double IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.MFPToRadius get set
The ratio of the mean free path vs. the sphere's radius.
Referenced by IG.MPetekLib.Algorithms.Models.CompPhys.MCRadioactiveSphere.CalcFracOfEscRaysVsMFPToRadius().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/Guest_Marko_Petek_Lib/algorithms/Models/CompPhys/01MCRadioactiveSphere.cs