Doc: IGLib EXTENDED: NUnit.Framework.Assertions.AssertPassTests Class Reference
NUnit.Framework.Assertions.AssertPassTests Class Reference
Public Member Functions
void ThrowsSuccessException ()
void ThrowsSuccessExceptionWithMessage ()
void ThrowsSuccessExceptionWithMessageAndArgs ()
void AssertPassReturnsSuccess ()
void SubsequentFailureIsIrrelevant ()
Member Function Documentation
ThrowsSuccessException()
void NUnit.Framework.Assertions.AssertPassTests.ThrowsSuccessException () inline
References NUnit.Framework.Assert.Pass(), NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
ThrowsSuccessExceptionWithMessage()
void NUnit.Framework.Assertions.AssertPassTests.ThrowsSuccessExceptionWithMessage () inline
References NUnit.Framework.Assert.Pass(), NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
ThrowsSuccessExceptionWithMessageAndArgs()
void NUnit.Framework.Assertions.AssertPassTests.ThrowsSuccessExceptionWithMessageAndArgs () inline
References NUnit.Framework.Assert.Pass(), NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
AssertPassReturnsSuccess()
void NUnit.Framework.Assertions.AssertPassTests.AssertPassReturnsSuccess () inline
References NUnit.Framework.Assert.Pass().
SubsequentFailureIsIrrelevant()
void NUnit.Framework.Assertions.AssertPassTests.SubsequentFailureIsIrrelevant () inline
References NUnit.Framework.Assert.Fail(), and NUnit.Framework.Assert.Pass().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/AssertPassTests.cs