Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLATRZ Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLATRZ Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLATRZ (DLARFG dlarfg, DLARZ dlarz)
DLATRZ ()
void Run (int M, int N, int L, ref double[] A, int offset_a, int LDA, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work)
Private Attributes
DLARFG _dlarfg
DLARZ _dlarz
Static Private Attributes
const double ZERO = 0.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLATRZ factors the M-by-(M+L) real upper trapezoidal matrix [ A1 A2 ] = [ A(1:M,1:M) A(1:M,N-L+1:N) ] as (R 0) * Z, by means of orthogonal transformations. Z is an (M+L)-by-(M+L) orthogonal matrix and, R and A1 are M-by-M upper triangular matrices.
/summary>
Constructor & Destructor Documentation
DLATRZ() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLATRZ.DLATRZ (DLARFG dlarfg, DLARZ dlarz) inline
DLATRZ() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLATRZ.DLATRZ () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLATRZ.Run (int M, int N, int L, ref double[] A, int offset_a, int LDA, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work) inline
Purpose
DLATRZ factors the M-by-(M+L) real upper trapezoidal matrix [ A1 A2 ] = [ A(1:M,1:M) A(1:M,N-L+1:N) ] as (R 0) * Z, by means of orthogonal transformations. Z is an (M+L)-by-(M+L) orthogonal matrix and, R and A1 are M-by-M upper triangular matrices.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. 0. /param>
Parameters
L (input) INTEGER The number of columns of the matrix A containing the meaningful part of the Householder vectors. N-M .GE. L .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the leading M-by-N upper trapezoidal part of the array A must contain the matrix to be factorized. On exit, the leading M-by-M upper triangular part of A contains the upper triangular matrix R, and elements N-L+1 to N of the first M rows of A, with the array TAU, represent the orthogonal matrix Z as a product of M elementary reflectors. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
TAU (output) DOUBLE PRECISION array, dimension (M) The scalar factors of the elementary reflectors. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (M) /param>
References DotNumerics.LinearAlgebra.CSLapack.DLARZ.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLATRZ.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTZRZF.Run().
Member Data Documentation
_dlarfg
DLARFG DotNumerics.LinearAlgebra.CSLapack.DLATRZ._dlarfg private
_dlarz
DLARZ DotNumerics.LinearAlgebra.CSLapack.DLATRZ._dlarz private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLATRZ.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLATRZ.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlatrz.cs