Doc: IGLib EXTENDED: IG.Neural.Forms.Old.FormNeural2DOld Class Reference
IG.Neural.Forms.Old.FormNeural2DOld Class Reference
Public Member Functions
FormNeural2DOld ()
void Update ()
void Start ()
void DefaultPlot ()
void TrainingPointsPlot ()
void ApproximationPlot ()
void DefaultContourPlot ()
void ApproximationContourPlot ()
void Bounds ()
void GeneratePlotter ()
void SclarBar (double minRange, double maxRange, ColorScale Color)
void LegendBox ()
void DecorHandler ()
Static Public Member Functions
static ColorScale CreateGreenRedYellow (double minValue, double maxValue)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void VTKGraphics_Load (object sender, EventArgs e)
void cbDefaultSurface_CheckedChanged (object sender, EventArgs e)
void cbDefaultGreed_CheckedChanged (object sender, EventArgs e)
void cbTrainingPoints_CheckedChanged (object sender, EventArgs e)
void cbApproximationSurface_CheckedChanged (object sender, EventArgs e)
void cbApproximationGreed_CheckedChanged (object sender, EventArgs e)
void cbContourDefault_CheckedChanged (object sender, EventArgs e)
void cbContourApproximation_CheckedChanged (object sender, EventArgs e)
void cbSelfMade_CheckedChanged (object sender, EventArgs e)
void cbxAforge_CheckedChanged (object sender, EventArgs e)
void cbxNeuron_CheckedChanged (object sender, EventArgs e)
void numBoundMaxY_ValueChanged (object sender, EventArgs e)
void numBoundMaxX_ValueChanged (object sender, EventArgs e)
void numBoundMinX_ValueChanged (object sender, EventArgs e)
void numBoundMinY_ValueChanged (object sender, EventArgs e)
void numTrainSampleX_ValueChanged (object sender, EventArgs e)
void numTrainSampleY_ValueChanged (object sender, EventArgs e)
void numHiddenNeuron_ValueChanged (object sender, EventArgs e)
void numMaxEpoch_ValueChanged (object sender, EventArgs e)
void numEpochBundle_ValueChanged (object sender, EventArgs e)
void numRMS_ValueChanged (object sender, EventArgs e)
void numLearningRate_ValueChanged (object sender, EventArgs e)
void numMomentum_ValueChanged (object sender, EventArgs e)
void numInputSafety_ValueChanged (object sender, EventArgs e)
void numOutputSafety_ValueChanged (object sender, EventArgs e)
void btnStartTraining_Click (object sender, EventArgs e)
void btnShowGraph_Click (object sender, EventArgs e)
void cbEquation_SelectedIndexChanged (object sender, EventArgs e)
void tbSelfMadeEquation_TextChanged (object sender, EventArgs e)
void trackbDefaultGraph_Scroll (object sender, EventArgs e)
void trackbApproxGraph_Scroll (object sender, EventArgs e)
void trackbContourGraph_Scroll (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
INeuralApproximator Approximator3D
VtkPlotter plotter
BoundingBox2d paramBounds
Func2dFromScalarFunction iFunctionDefault
VtkSurfacePlot plotDefault
Func2dFromScalarFunction iFunctionTraining
Func2dFromApproximator iFunctionApproximator
ExampleValueFunctionDiff3D iFunctionDifference
VtkContourPlot plotContour
bool flagDefaultSurface = false
bool flagDefaultGreed = true
bool flagTrainingPoints = true
bool flagApproximationSurface = true
bool flagApproximationGreed = false
bool flagContourDafault = false
bool flagContourApproximation = false
bool selfMadeEquation = false
bool flagExceptionEquation = false
double boundMaxY = 1.0
double boundMinY = -1.0
double boundMaxX = 1.0
double boundMinX = -1.0
int numAllXPoints = 100
int numAllYPoints = 100
int trainingSampleX = 5
int trainingSampleY = 5
int nnType = 1
string equation = "x*x + y*y"
string[] variableNames = { "x", "y" }
int hiddenNeurons = 5
int maxEpochs = 5000
int epochsInBundle = 500
double learningRate = 0.3
double momentum = 0.6
double errorRMS = 0.001
double inputSafetyFactor = 1.3
double outputSafetyFactor = 1.3
double opacityDefaultGraph = 0.5
double opacityApproxGraph = 0.7
double opacityContourGraph = 1.0
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.NumericUpDown numBoundMaxY
System.Windows.Forms.NumericUpDown numBoundMinY
System.Windows.Forms.NumericUpDown numBoundMaxX
System.Windows.Forms.NumericUpDown numBoundMinX
System.Windows.Forms.Label label1
System.Windows.Forms.Label label2
System.Windows.Forms.Label label3
System.Windows.Forms.Label label4
System.Windows.Forms.Label label5
System.Windows.Forms.Label label6
System.Windows.Forms.CheckBox cbDefaultSurface
System.Windows.Forms.CheckBox cbDefaultGreed
System.Windows.Forms.CheckBox cbTrainingPoints
System.Windows.Forms.Label label7
System.Windows.Forms.CheckBox cbApproximationGreed
System.Windows.Forms.CheckBox cbApproximationSurface
System.Windows.Forms.Label label8
System.Windows.Forms.CheckBox cbContourApproximation
System.Windows.Forms.CheckBox cbContourDefault
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.GroupBox groupBox3
System.Windows.Forms.Button btnShowGraph
System.Windows.Forms.Button btnStartTraining
System.Windows.Forms.GroupBox groupBox4
System.Windows.Forms.Label label9
System.Windows.Forms.TextBox tbSelfMadeEquation
System.Windows.Forms.ComboBox cbEquation
System.Windows.Forms.CheckBox cbSelfMade
System.Windows.Forms.GroupBox groupBox5
System.Windows.Forms.NumericUpDown numTrainSampleY
System.Windows.Forms.Label label11
System.Windows.Forms.NumericUpDown numTrainSampleX
System.Windows.Forms.Label label10
System.Windows.Forms.GroupBox groupBox6
System.Windows.Forms.CheckBox cbxNeuron
System.Windows.Forms.CheckBox cbxAforge
System.Windows.Forms.GroupBox groupBox7
System.Windows.Forms.NumericUpDown numHiddenNeuron
System.Windows.Forms.Label label12
System.Windows.Forms.Label label17
System.Windows.Forms.NumericUpDown numMomentum
System.Windows.Forms.Label label16
System.Windows.Forms.NumericUpDown numLearningRate
System.Windows.Forms.Label label15
System.Windows.Forms.NumericUpDown numRMS
System.Windows.Forms.Label label14
System.Windows.Forms.NumericUpDown numEpochBundle
System.Windows.Forms.Label label13
System.Windows.Forms.NumericUpDown numMaxEpoch
System.Windows.Forms.NumericUpDown numOutputSafety
System.Windows.Forms.Label label18
System.Windows.Forms.NumericUpDown numInputSafety
System.Windows.Forms.Label label19
System.Windows.Forms.TextBox tbEquationError
System.Windows.Forms.TrackBar trackbDefaultGraph
System.Windows.Forms.Label label21
System.Windows.Forms.Label label20
System.Windows.Forms.TrackBar trackbApproxGraph
System.Windows.Forms.Label label22
System.Windows.Forms.TrackBar trackbContourGraph
Constructor & Destructor Documentation
FormNeural2DOld()
IG.Neural.Forms.Old.FormNeural2DOld.FormNeural2DOld () inline
References IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
Member Function Documentation
VTKGraphics_Load()
void IG.Neural.Forms.Old.FormNeural2DOld.VTKGraphics_Load (object sender, EventArgs e) inline private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbDefaultSurface_CheckedChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.cbDefaultSurface_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.cbDefaultSurface, and IG.Neural.Forms.Old.FormNeural2DOld.flagDefaultSurface.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbDefaultGreed_CheckedChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.cbDefaultGreed_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.cbDefaultGreed, and IG.Neural.Forms.Old.FormNeural2DOld.flagDefaultGreed.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbTrainingPoints_CheckedChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.cbTrainingPoints_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.cbTrainingPoints, and IG.Neural.Forms.Old.FormNeural2DOld.flagTrainingPoints.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbApproximationSurface_CheckedChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.cbApproximationSurface_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.cbApproximationSurface, and IG.Neural.Forms.Old.FormNeural2DOld.flagApproximationSurface.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbApproximationGreed_CheckedChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.cbApproximationGreed_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.cbApproximationGreed, and IG.Neural.Forms.Old.FormNeural2DOld.flagApproximationGreed.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbContourDefault_CheckedChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.cbContourDefault_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.cbContourDefault, and IG.Neural.Forms.Old.FormNeural2DOld.flagContourDafault.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbContourApproximation_CheckedChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.cbContourApproximation_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.cbContourApproximation, and IG.Neural.Forms.Old.FormNeural2DOld.flagContourApproximation.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbSelfMade_CheckedChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.cbSelfMade_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.cbEquation, IG.Neural.Forms.Old.FormNeural2DOld.cbSelfMade, IG.Neural.Forms.Old.FormNeural2DOld.selfMadeEquation, and IG.Neural.Forms.Old.FormNeural2DOld.tbSelfMadeEquation.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbxAforge_CheckedChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.cbxAforge_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.cbxAforge, IG.Neural.Forms.Old.FormNeural2DOld.cbxNeuron, and IG.Neural.Forms.Old.FormNeural2DOld.nnType.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbxNeuron_CheckedChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.cbxNeuron_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.cbxAforge, IG.Neural.Forms.Old.FormNeural2DOld.cbxNeuron, and IG.Neural.Forms.Old.FormNeural2DOld.nnType.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numBoundMaxY_ValueChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.numBoundMaxY_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.boundMaxY, IG.Neural.Forms.Old.FormNeural2DOld.Bounds(), and IG.Neural.Forms.Old.FormNeural2DOld.numBoundMaxY.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numBoundMaxX_ValueChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.numBoundMaxX_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.boundMaxX, IG.Neural.Forms.Old.FormNeural2DOld.Bounds(), and IG.Neural.Forms.Old.FormNeural2DOld.numBoundMaxX.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numBoundMinX_ValueChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.numBoundMinX_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.boundMinX, IG.Neural.Forms.Old.FormNeural2DOld.Bounds(), and IG.Neural.Forms.Old.FormNeural2DOld.numBoundMinX.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numBoundMinY_ValueChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.numBoundMinY_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.boundMinY, IG.Neural.Forms.Old.FormNeural2DOld.Bounds(), and IG.Neural.Forms.Old.FormNeural2DOld.numBoundMinY.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numTrainSampleX_ValueChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.numTrainSampleX_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.numTrainSampleX, and IG.Neural.Forms.Old.FormNeural2DOld.trainingSampleX.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numTrainSampleY_ValueChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.numTrainSampleY_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.numTrainSampleY, and IG.Neural.Forms.Old.FormNeural2DOld.trainingSampleY.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numHiddenNeuron_ValueChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.numHiddenNeuron_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.hiddenNeurons, and IG.Neural.Forms.Old.FormNeural2DOld.numHiddenNeuron.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numMaxEpoch_ValueChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.numMaxEpoch_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.maxEpochs, and IG.Neural.Forms.Old.FormNeural2DOld.numMaxEpoch.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numEpochBundle_ValueChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.numEpochBundle_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.epochsInBundle, and IG.Neural.Forms.Old.FormNeural2DOld.numEpochBundle.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numRMS_ValueChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.numRMS_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.errorRMS, and IG.Neural.Forms.Old.FormNeural2DOld.numRMS.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numLearningRate_ValueChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.numLearningRate_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.learningRate, and IG.Neural.Forms.Old.FormNeural2DOld.numLearningRate.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numMomentum_ValueChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.numMomentum_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.momentum, and IG.Neural.Forms.Old.FormNeural2DOld.numMomentum.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numInputSafety_ValueChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.numInputSafety_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.inputSafetyFactor, and IG.Neural.Forms.Old.FormNeural2DOld.numInputSafety.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numOutputSafety_ValueChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.numOutputSafety_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.numOutputSafety, and IG.Neural.Forms.Old.FormNeural2DOld.outputSafetyFactor.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
btnStartTraining_Click()
void IG.Neural.Forms.Old.FormNeural2DOld.btnStartTraining_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.Start().
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
btnShowGraph_Click()
void IG.Neural.Forms.Old.FormNeural2DOld.btnShowGraph_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.Update().
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbEquation_SelectedIndexChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.cbEquation_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.Approximator3D, IG.Neural.Forms.Old.FormNeural2DOld.cbEquation, and IG.Neural.Forms.Old.FormNeural2DOld.equation.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
tbSelfMadeEquation_TextChanged()
void IG.Neural.Forms.Old.FormNeural2DOld.tbSelfMadeEquation_TextChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.Approximator3D, IG.Neural.Forms.Old.FormNeural2DOld.equation, and IG.Neural.Forms.Old.FormNeural2DOld.tbSelfMadeEquation.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
Update()
void IG.Neural.Forms.Old.FormNeural2DOld.Update () inline
References IG.Neural.Forms.Old.FormNeural2DOld.ApproximationContourPlot(), IG.Neural.Forms.Old.FormNeural2DOld.ApproximationPlot(), IG.Neural.Forms.Old.FormNeural2DOld.Approximator3D, IG.Gr3d.VtkPlotBase.CreateAndShow(), IG.Neural.Forms.Old.FormNeural2DOld.DefaultContourPlot(), IG.Neural.Forms.Old.FormNeural2DOld.DefaultPlot(), IG.Neural.Forms.Old.FormNeural2DOld.flagContourApproximation, IG.Neural.Forms.Old.FormNeural2DOld.flagContourDafault, IG.Neural.Forms.Old.FormNeural2DOld.flagExceptionEquation, IG.Neural.Forms.Old.FormNeural2DOld.GeneratePlotter(), IG.Neural.Forms.Old.FormNeural2DOld.plotDefault, IG.Neural.Forms.Old.FormNeural2DOld.plotter, IG.Gr3d.VtkPlotter.ResetCamera(), and IG.Neural.Forms.Old.FormNeural2DOld.TrainingPointsPlot().
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.btnShowGraph_Click().
Start()
void IG.Neural.Forms.Old.FormNeural2DOld.Start () inline
References IG.Num.SampledDataSet.AddElement(), IG.Neural.Forms.Old.FormNeural2DOld.ApproximationContourPlot(), IG.Neural.Forms.Old.FormNeural2DOld.ApproximationPlot(), IG.Neural.Forms.Old.FormNeural2DOld.Approximator3D, IG.Gr3d.VtkPlotBase.CreateAndShow(), IG.Neural.Forms.Old.FormNeural2DOld.DefaultContourPlot(), IG.Neural.Forms.Old.FormNeural2DOld.DefaultPlot(), IG.Neural.NeuralNetworks.EpochBundle, IG.Neural.Forms.Old.FormNeural2DOld.epochsInBundle, IG.Neural.Forms.Old.FormNeural2DOld.errorRMS, IG.Neural.NeuralNetworks.Example3D(), IG.Neural.Forms.Old.FormNeural2DOld.flagContourApproximation, IG.Neural.Forms.Old.FormNeural2DOld.flagContourDafault, IG.Neural.Forms.Old.FormNeural2DOld.flagExceptionEquation, IG.Neural.Forms.Old.FormNeural2DOld.GeneratePlotter(), IG.Neural.NeuralNetworks.HiddenNeuron1L, IG.Neural.Forms.Old.FormNeural2DOld.hiddenNeurons, IG.Num.SampledDataSet.InputLength, IG.Neural.Forms.Old.FormNeural2DOld.inputSafetyFactor, IG.Neural.NeuralNetworks.InputSafetyFactor, IG.Neural.Forms.Old.FormNeural2DOld.learningRate, IG.Neural.NeuralNetworks.LearningRate, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Neural.Forms.Old.FormNeural2DOld.momentum, IG.Neural.NeuralNetworks.Momentum, IG.Neural.Forms.Old.FormNeural2DOld.nnType, IG.Neural.Forms.Old.FormNeural2DOld.numAllXPoints, IG.Neural.Forms.Old.FormNeural2DOld.numAllYPoints, IG.Num.SampledDataSet.OutputLength, IG.Neural.Forms.Old.FormNeural2DOld.outputSafetyFactor, IG.Neural.NeuralNetworks.OutputSafetyFactor, IG.Neural.Forms.Old.FormNeural2DOld.plotDefault, IG.Neural.Forms.Old.FormNeural2DOld.plotter, IG.Gr3d.VtkPlotter.ResetCamera(), IG.Neural.NeuralNetworks.RMS, IG.Neural.Forms.Old.FormNeural2DOld.TrainingPointsPlot(), IG.Neural.Forms.Old.FormNeural2DOld.trainingSampleX, and IG.Neural.Forms.Old.FormNeural2DOld.trainingSampleY.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.btnStartTraining_Click().
DefaultPlot()
void IG.Neural.Forms.Old.FormNeural2DOld.DefaultPlot () inline
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Num.Func2dFromScalarScript.CreateScalarFunction(), IG.Neural.Forms.Old.FormNeural2DOld.equation, IG.Neural.Forms.Old.FormNeural2DOld.flagContourApproximation, IG.Neural.Forms.Old.FormNeural2DOld.flagContourDafault, IG.Neural.Forms.Old.FormNeural2DOld.flagDefaultGreed, IG.Neural.Forms.Old.FormNeural2DOld.flagDefaultSurface, IG.Neural.Forms.Old.FormNeural2DOld.flagExceptionEquation, IG.Neural.Forms.Old.FormNeural2DOld.iFunctionDefault, IG.Gr3d.VtkSurfacePlotBase.LineColor, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Neural.Forms.Old.FormNeural2DOld.numAllXPoints, IG.Neural.Forms.Old.FormNeural2DOld.numAllYPoints, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Neural.Forms.Old.FormNeural2DOld.opacityDefaultGraph, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.Old.FormNeural2DOld.paramBounds, IG.Neural.Forms.Old.FormNeural2DOld.plotContour, IG.Neural.Forms.Old.FormNeural2DOld.plotDefault, IG.Neural.Forms.Old.FormNeural2DOld.plotter, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible, IG.Neural.Forms.Old.FormNeural2DOld.tbEquationError, and IG.Neural.Forms.Old.FormNeural2DOld.variableNames.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.Start(), and IG.Neural.Forms.Old.FormNeural2DOld.Update().
TrainingPointsPlot()
void IG.Neural.Forms.Old.FormNeural2DOld.TrainingPointsPlot () inline
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Num.Func2dFromScalarScript.CreateScalarFunction(), IG.Neural.Forms.Old.FormNeural2DOld.equation, IG.Neural.Forms.Old.FormNeural2DOld.flagTrainingPoints, IG.Neural.Forms.Old.FormNeural2DOld.iFunctionTraining, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.Old.FormNeural2DOld.plotDefault, IG.Gr3d.VtkSurfacePlotBase.PointColor, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible, IG.Neural.Forms.Old.FormNeural2DOld.trainingSampleX, IG.Neural.Forms.Old.FormNeural2DOld.trainingSampleY, and IG.Neural.Forms.Old.FormNeural2DOld.variableNames.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.Start(), and IG.Neural.Forms.Old.FormNeural2DOld.Update().
ApproximationPlot()
void IG.Neural.Forms.Old.FormNeural2DOld.ApproximationPlot () inline
References IG.Neural.Forms.Old.FormNeural2DOld.Approximator3D, IG.Gr3d.VtkSurfacePlot.Create(), IG.Neural.Forms.Old.FormNeural2DOld.CreateGreenRedYellow(), IG.Neural.Forms.Old.FormNeural2DOld.flagApproximationGreed, IG.Neural.Forms.Old.FormNeural2DOld.flagApproximationSurface, IG.Neural.Forms.Old.FormNeural2DOld.iFunctionApproximator, IG.Neural.Forms.Old.FormNeural2DOld.iFunctionDefault, IG.Neural.Forms.Old.FormNeural2DOld.iFunctionDifference, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LineColorScale, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Neural.Forms.Old.FormNeural2DOld.numAllXPoints, IG.Neural.Forms.Old.FormNeural2DOld.numAllYPoints, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Neural.Forms.Old.FormNeural2DOld.opacityApproxGraph, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.Old.FormNeural2DOld.paramBounds, IG.Neural.Forms.Old.FormNeural2DOld.plotDefault, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Neural.Forms.Old.FormNeural2DOld.SclarBar(), IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible, and IG.Gr3d.VtkSurfacePlot.ValueFunctionOfCoordinates.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.Start(), and IG.Neural.Forms.Old.FormNeural2DOld.Update().
DefaultContourPlot()
void IG.Neural.Forms.Old.FormNeural2DOld.DefaultContourPlot () inline
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Lib.ColorScaleBase.CreateRainbow(), IG.Neural.Forms.Old.FormNeural2DOld.iFunctionDefault, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Neural.Forms.Old.FormNeural2DOld.numAllXPoints, IG.Neural.Forms.Old.FormNeural2DOld.numAllYPoints, IG.Gr3d.VtkContourPlot.NumContours, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Neural.Forms.Old.FormNeural2DOld.opacityContourGraph, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.Old.FormNeural2DOld.paramBounds, IG.Neural.Forms.Old.FormNeural2DOld.plotContour, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.Start(), and IG.Neural.Forms.Old.FormNeural2DOld.Update().
ApproximationContourPlot()
void IG.Neural.Forms.Old.FormNeural2DOld.ApproximationContourPlot () inline
References IG.Gr3d.VtkSurfacePlot.Create(), IG.Lib.ColorScaleBase.CreateRainbow(), IG.Neural.Forms.Old.FormNeural2DOld.iFunctionApproximator, IG.Gr3d.VtkSurfacePlotBase.LineColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.LineColorOpacity, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Neural.Forms.Old.FormNeural2DOld.numAllXPoints, IG.Neural.Forms.Old.FormNeural2DOld.numAllYPoints, IG.Gr3d.VtkContourPlot.NumContours, IG.Gr3d.VtkSurfacePlot.NumX, IG.Gr3d.VtkSurfacePlot.NumY, IG.Neural.Forms.Old.FormNeural2DOld.opacityContourGraph, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.Old.FormNeural2DOld.paramBounds, IG.Neural.Forms.Old.FormNeural2DOld.plotContour, IG.Gr3d.VtkSurfacePlotBase.PointSize, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlot.SetBoundsParameters(), IG.Gr3d.VtkSurfacePlot.SetSurfaceDefinition(), IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.Start(), and IG.Neural.Forms.Old.FormNeural2DOld.Update().
Bounds()
void IG.Neural.Forms.Old.FormNeural2DOld.Bounds () inline
References IG.Neural.Forms.Old.FormNeural2DOld.boundMaxX, IG.Neural.Forms.Old.FormNeural2DOld.boundMaxY, IG.Neural.Forms.Old.FormNeural2DOld.boundMinX, IG.Neural.Forms.Old.FormNeural2DOld.boundMinY, and IG.Neural.Forms.Old.FormNeural2DOld.paramBounds.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.numBoundMaxX_ValueChanged(), IG.Neural.Forms.Old.FormNeural2DOld.numBoundMaxY_ValueChanged(), IG.Neural.Forms.Old.FormNeural2DOld.numBoundMinX_ValueChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.numBoundMinY_ValueChanged().
GeneratePlotter()
void IG.Neural.Forms.Old.FormNeural2DOld.GeneratePlotter () inline
References IG.Neural.Forms.Old.FormNeural2DOld.DecorHandler(), IG.Neural.Forms.Old.FormNeural2DOld.plotDefault, and IG.Neural.Forms.Old.FormNeural2DOld.plotter.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.Start(), and IG.Neural.Forms.Old.FormNeural2DOld.Update().
SclarBar()
void IG.Neural.Forms.Old.FormNeural2DOld.SclarBar (double minRange, double maxRange, ColorScale Color) inline
References IG.Gr3d.VtkPlotter.DecorationHandler, IG.Gr3d.VtkDecorationHandler.LookUpTableColorScale, IG.Gr3d.VtkDecorationHandler.LookUpTableMaxRange, IG.Gr3d.VtkDecorationHandler.LookUpTableMinRange, IG.Neural.Forms.Old.FormNeural2DOld.plotter, IG.Gr3d.VtkDecorationHandler.ScalarBarNumberOfLabels, IG.Gr3d.VtkDecorationHandler.ScalarBarTitle, and IG.Gr3d.VtkDecorationHandler.ShowScalarBar.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.ApproximationPlot().
LegendBox()
void IG.Neural.Forms.Old.FormNeural2DOld.LegendBox () inline
References IG.Gr3d.VtkPlotter.DecorationHandler, IG.Gr3d.VtkDecorationHandler.LegendBoxNumEntries, IG.Gr3d.VtkDecorationHandler.LegendBoxTitles, and IG.Neural.Forms.Old.FormNeural2DOld.plotter.
DecorHandler()
void IG.Neural.Forms.Old.FormNeural2DOld.DecorHandler () inline
References IG.Gr3d.VtkPlotter.BackGround, IG.Gr3d.VtkDecorationHandler.CubeAxesFlyMode, IG.Gr3d.VtkDecorationHandler.CubeAxesXLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesYLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesZLabel, IG.Gr3d.VtkPlotter.DecorationHandler, IG.Neural.Forms.Old.FormNeural2DOld.plotter, IG.Gr3d.VtkPlotter.WindowSizeX, and IG.Gr3d.VtkPlotter.WindowSizeY.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.GeneratePlotter().
CreateGreenRedYellow()
static ColorScale IG.Neural.Forms.Old.FormNeural2DOld.CreateGreenRedYellow (double minValue, double maxValue) inline static
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.ApproximationPlot().
trackbDefaultGraph_Scroll()
void IG.Neural.Forms.Old.FormNeural2DOld.trackbDefaultGraph_Scroll (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.opacityDefaultGraph, and IG.Neural.Forms.Old.FormNeural2DOld.trackbDefaultGraph.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
trackbApproxGraph_Scroll()
void IG.Neural.Forms.Old.FormNeural2DOld.trackbApproxGraph_Scroll (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.opacityApproxGraph, and IG.Neural.Forms.Old.FormNeural2DOld.trackbApproxGraph.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
trackbContourGraph_Scroll()
void IG.Neural.Forms.Old.FormNeural2DOld.trackbContourGraph_Scroll (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural2DOld.opacityContourGraph, and IG.Neural.Forms.Old.FormNeural2DOld.trackbContourGraph.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
Dispose()
override void IG.Neural.Forms.Old.FormNeural2DOld.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.Old.FormNeural2DOld.components.
InitializeComponent()
void IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.Old.FormNeural2DOld.btnShowGraph, IG.Neural.Forms.Old.FormNeural2DOld.btnShowGraph_Click(), IG.Neural.Forms.Old.FormNeural2DOld.btnStartTraining, IG.Neural.Forms.Old.FormNeural2DOld.btnStartTraining_Click(), IG.Neural.Forms.Old.FormNeural2DOld.cbApproximationGreed, IG.Neural.Forms.Old.FormNeural2DOld.cbApproximationGreed_CheckedChanged(), IG.Neural.Forms.Old.FormNeural2DOld.cbApproximationSurface, IG.Neural.Forms.Old.FormNeural2DOld.cbApproximationSurface_CheckedChanged(), IG.Neural.Forms.Old.FormNeural2DOld.cbContourApproximation, IG.Neural.Forms.Old.FormNeural2DOld.cbContourApproximation_CheckedChanged(), IG.Neural.Forms.Old.FormNeural2DOld.cbContourDefault, IG.Neural.Forms.Old.FormNeural2DOld.cbContourDefault_CheckedChanged(), IG.Neural.Forms.Old.FormNeural2DOld.cbDefaultGreed, IG.Neural.Forms.Old.FormNeural2DOld.cbDefaultGreed_CheckedChanged(), IG.Neural.Forms.Old.FormNeural2DOld.cbDefaultSurface, IG.Neural.Forms.Old.FormNeural2DOld.cbDefaultSurface_CheckedChanged(), IG.Neural.Forms.Old.FormNeural2DOld.cbEquation, IG.Neural.Forms.Old.FormNeural2DOld.cbEquation_SelectedIndexChanged(), IG.Neural.Forms.Old.FormNeural2DOld.cbSelfMade, IG.Neural.Forms.Old.FormNeural2DOld.cbSelfMade_CheckedChanged(), IG.Neural.Forms.Old.FormNeural2DOld.cbTrainingPoints, IG.Neural.Forms.Old.FormNeural2DOld.cbTrainingPoints_CheckedChanged(), IG.Neural.Forms.Old.FormNeural2DOld.cbxAforge, IG.Neural.Forms.Old.FormNeural2DOld.cbxAforge_CheckedChanged(), IG.Neural.Forms.Old.FormNeural2DOld.cbxNeuron, IG.Neural.Forms.Old.FormNeural2DOld.cbxNeuron_CheckedChanged(), IG.Neural.Forms.Old.FormNeural2DOld.groupBox1, IG.Neural.Forms.Old.FormNeural2DOld.groupBox2, IG.Neural.Forms.Old.FormNeural2DOld.groupBox3, IG.Neural.Forms.Old.FormNeural2DOld.groupBox4, IG.Neural.Forms.Old.FormNeural2DOld.groupBox5, IG.Neural.Forms.Old.FormNeural2DOld.groupBox6, IG.Neural.Forms.Old.FormNeural2DOld.groupBox7, IG.Neural.Forms.Old.FormNeural2DOld.label1, IG.Neural.Forms.Old.FormNeural2DOld.label10, IG.Neural.Forms.Old.FormNeural2DOld.label11, IG.Neural.Forms.Old.FormNeural2DOld.label12, IG.Neural.Forms.Old.FormNeural2DOld.label13, IG.Neural.Forms.Old.FormNeural2DOld.label14, IG.Neural.Forms.Old.FormNeural2DOld.label15, IG.Neural.Forms.Old.FormNeural2DOld.label16, IG.Neural.Forms.Old.FormNeural2DOld.label17, IG.Neural.Forms.Old.FormNeural2DOld.label18, IG.Neural.Forms.Old.FormNeural2DOld.label19, IG.Neural.Forms.Old.FormNeural2DOld.label2, IG.Neural.Forms.Old.FormNeural2DOld.label20, IG.Neural.Forms.Old.FormNeural2DOld.label21, IG.Neural.Forms.Old.FormNeural2DOld.label22, IG.Neural.Forms.Old.FormNeural2DOld.label3, IG.Neural.Forms.Old.FormNeural2DOld.label4, IG.Neural.Forms.Old.FormNeural2DOld.label5, IG.Neural.Forms.Old.FormNeural2DOld.label6, IG.Neural.Forms.Old.FormNeural2DOld.label7, IG.Neural.Forms.Old.FormNeural2DOld.label8, IG.Neural.Forms.Old.FormNeural2DOld.label9, IG.Neural.Forms.Old.FormNeural2DOld.numBoundMaxX, IG.Neural.Forms.Old.FormNeural2DOld.numBoundMaxX_ValueChanged(), IG.Neural.Forms.Old.FormNeural2DOld.numBoundMaxY, IG.Neural.Forms.Old.FormNeural2DOld.numBoundMaxY_ValueChanged(), IG.Neural.Forms.Old.FormNeural2DOld.numBoundMinX, IG.Neural.Forms.Old.FormNeural2DOld.numBoundMinX_ValueChanged(), IG.Neural.Forms.Old.FormNeural2DOld.numBoundMinY, IG.Neural.Forms.Old.FormNeural2DOld.numBoundMinY_ValueChanged(), IG.Neural.Forms.Old.FormNeural2DOld.numEpochBundle, IG.Neural.Forms.Old.FormNeural2DOld.numEpochBundle_ValueChanged(), IG.Neural.Forms.Old.FormNeural2DOld.numHiddenNeuron, IG.Neural.Forms.Old.FormNeural2DOld.numHiddenNeuron_ValueChanged(), IG.Neural.Forms.Old.FormNeural2DOld.numInputSafety, IG.Neural.Forms.Old.FormNeural2DOld.numInputSafety_ValueChanged(), IG.Neural.Forms.Old.FormNeural2DOld.numLearningRate, IG.Neural.Forms.Old.FormNeural2DOld.numLearningRate_ValueChanged(), IG.Neural.Forms.Old.FormNeural2DOld.numMaxEpoch, IG.Neural.Forms.Old.FormNeural2DOld.numMaxEpoch_ValueChanged(), IG.Neural.Forms.Old.FormNeural2DOld.numMomentum, IG.Neural.Forms.Old.FormNeural2DOld.numMomentum_ValueChanged(), IG.Neural.Forms.Old.FormNeural2DOld.numOutputSafety, IG.Neural.Forms.Old.FormNeural2DOld.numOutputSafety_ValueChanged(), IG.Neural.Forms.Old.FormNeural2DOld.numRMS, IG.Neural.Forms.Old.FormNeural2DOld.numRMS_ValueChanged(), IG.Neural.Forms.Old.FormNeural2DOld.numTrainSampleX, IG.Neural.Forms.Old.FormNeural2DOld.numTrainSampleX_ValueChanged(), IG.Neural.Forms.Old.FormNeural2DOld.numTrainSampleY, IG.Neural.Forms.Old.FormNeural2DOld.numTrainSampleY_ValueChanged(), IG.Neural.Forms.Old.FormNeural2DOld.tbEquationError, IG.Neural.Forms.Old.FormNeural2DOld.tbSelfMadeEquation, IG.Neural.Forms.Old.FormNeural2DOld.tbSelfMadeEquation_TextChanged(), IG.Neural.Forms.Old.FormNeural2DOld.trackbApproxGraph, IG.Neural.Forms.Old.FormNeural2DOld.trackbApproxGraph_Scroll(), IG.Neural.Forms.Old.FormNeural2DOld.trackbContourGraph, IG.Neural.Forms.Old.FormNeural2DOld.trackbContourGraph_Scroll(), IG.Neural.Forms.Old.FormNeural2DOld.trackbDefaultGraph, IG.Neural.Forms.Old.FormNeural2DOld.trackbDefaultGraph_Scroll(), and IG.Neural.Forms.Old.FormNeural2DOld.VTKGraphics_Load().
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.FormNeural2DOld().
Member Data Documentation
Approximator3D
INeuralApproximator IG.Neural.Forms.Old.FormNeural2DOld.Approximator3D private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.ApproximationPlot(), IG.Neural.Forms.Old.FormNeural2DOld.cbEquation_SelectedIndexChanged(), IG.Neural.Forms.Old.FormNeural2DOld.Start(), IG.Neural.Forms.Old.FormNeural2DOld.tbSelfMadeEquation_TextChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.Update().
plotter
VtkPlotter IG.Neural.Forms.Old.FormNeural2DOld.plotter private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.DecorHandler(), IG.Neural.Forms.Old.FormNeural2DOld.DefaultPlot(), IG.Neural.Forms.Old.FormNeural2DOld.GeneratePlotter(), IG.Neural.Forms.Old.FormNeural2DOld.LegendBox(), IG.Neural.Forms.Old.FormNeural2DOld.SclarBar(), IG.Neural.Forms.Old.FormNeural2DOld.Start(), and IG.Neural.Forms.Old.FormNeural2DOld.Update().
paramBounds
BoundingBox2d IG.Neural.Forms.Old.FormNeural2DOld.paramBounds private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.ApproximationContourPlot(), IG.Neural.Forms.Old.FormNeural2DOld.ApproximationPlot(), IG.Neural.Forms.Old.FormNeural2DOld.Bounds(), IG.Neural.Forms.Old.FormNeural2DOld.DefaultContourPlot(), and IG.Neural.Forms.Old.FormNeural2DOld.DefaultPlot().
iFunctionDefault
Func2dFromScalarFunction IG.Neural.Forms.Old.FormNeural2DOld.iFunctionDefault private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.ApproximationPlot(), IG.Neural.Forms.Old.FormNeural2DOld.DefaultContourPlot(), and IG.Neural.Forms.Old.FormNeural2DOld.DefaultPlot().
plotDefault
VtkSurfacePlot IG.Neural.Forms.Old.FormNeural2DOld.plotDefault private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.ApproximationPlot(), IG.Neural.Forms.Old.FormNeural2DOld.DefaultPlot(), IG.Neural.Forms.Old.FormNeural2DOld.GeneratePlotter(), IG.Neural.Forms.Old.FormNeural2DOld.Start(), IG.Neural.Forms.Old.FormNeural2DOld.TrainingPointsPlot(), and IG.Neural.Forms.Old.FormNeural2DOld.Update().
iFunctionTraining
Func2dFromScalarFunction IG.Neural.Forms.Old.FormNeural2DOld.iFunctionTraining private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.TrainingPointsPlot().
iFunctionApproximator
Func2dFromApproximator IG.Neural.Forms.Old.FormNeural2DOld.iFunctionApproximator private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.ApproximationContourPlot(), and IG.Neural.Forms.Old.FormNeural2DOld.ApproximationPlot().
iFunctionDifference
ExampleValueFunctionDiff3D IG.Neural.Forms.Old.FormNeural2DOld.iFunctionDifference private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.ApproximationPlot().
plotContour
VtkContourPlot IG.Neural.Forms.Old.FormNeural2DOld.plotContour private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.ApproximationContourPlot(), IG.Neural.Forms.Old.FormNeural2DOld.DefaultContourPlot(), and IG.Neural.Forms.Old.FormNeural2DOld.DefaultPlot().
flagDefaultSurface
bool IG.Neural.Forms.Old.FormNeural2DOld.flagDefaultSurface = false private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.cbDefaultSurface_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.DefaultPlot().
flagDefaultGreed
bool IG.Neural.Forms.Old.FormNeural2DOld.flagDefaultGreed = true private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.cbDefaultGreed_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.DefaultPlot().
flagTrainingPoints
bool IG.Neural.Forms.Old.FormNeural2DOld.flagTrainingPoints = true private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.cbTrainingPoints_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.TrainingPointsPlot().
flagApproximationSurface
bool IG.Neural.Forms.Old.FormNeural2DOld.flagApproximationSurface = true private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.ApproximationPlot(), and IG.Neural.Forms.Old.FormNeural2DOld.cbApproximationSurface_CheckedChanged().
flagApproximationGreed
bool IG.Neural.Forms.Old.FormNeural2DOld.flagApproximationGreed = false private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.ApproximationPlot(), and IG.Neural.Forms.Old.FormNeural2DOld.cbApproximationGreed_CheckedChanged().
flagContourDafault
bool IG.Neural.Forms.Old.FormNeural2DOld.flagContourDafault = false private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.cbContourDefault_CheckedChanged(), IG.Neural.Forms.Old.FormNeural2DOld.DefaultPlot(), IG.Neural.Forms.Old.FormNeural2DOld.Start(), and IG.Neural.Forms.Old.FormNeural2DOld.Update().
flagContourApproximation
bool IG.Neural.Forms.Old.FormNeural2DOld.flagContourApproximation = false private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.cbContourApproximation_CheckedChanged(), IG.Neural.Forms.Old.FormNeural2DOld.DefaultPlot(), IG.Neural.Forms.Old.FormNeural2DOld.Start(), and IG.Neural.Forms.Old.FormNeural2DOld.Update().
selfMadeEquation
bool IG.Neural.Forms.Old.FormNeural2DOld.selfMadeEquation = false private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.cbSelfMade_CheckedChanged().
flagExceptionEquation
bool IG.Neural.Forms.Old.FormNeural2DOld.flagExceptionEquation = false private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.DefaultPlot(), IG.Neural.Forms.Old.FormNeural2DOld.Start(), and IG.Neural.Forms.Old.FormNeural2DOld.Update().
boundMaxY
double IG.Neural.Forms.Old.FormNeural2DOld.boundMaxY = 1.0 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.Bounds(), and IG.Neural.Forms.Old.FormNeural2DOld.numBoundMaxY_ValueChanged().
boundMinY
double IG.Neural.Forms.Old.FormNeural2DOld.boundMinY = -1.0 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.Bounds(), and IG.Neural.Forms.Old.FormNeural2DOld.numBoundMinY_ValueChanged().
boundMaxX
double IG.Neural.Forms.Old.FormNeural2DOld.boundMaxX = 1.0 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.Bounds(), and IG.Neural.Forms.Old.FormNeural2DOld.numBoundMaxX_ValueChanged().
boundMinX
double IG.Neural.Forms.Old.FormNeural2DOld.boundMinX = -1.0 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.Bounds(), and IG.Neural.Forms.Old.FormNeural2DOld.numBoundMinX_ValueChanged().
numAllXPoints
int IG.Neural.Forms.Old.FormNeural2DOld.numAllXPoints = 100 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.ApproximationContourPlot(), IG.Neural.Forms.Old.FormNeural2DOld.ApproximationPlot(), IG.Neural.Forms.Old.FormNeural2DOld.DefaultContourPlot(), IG.Neural.Forms.Old.FormNeural2DOld.DefaultPlot(), and IG.Neural.Forms.Old.FormNeural2DOld.Start().
numAllYPoints
int IG.Neural.Forms.Old.FormNeural2DOld.numAllYPoints = 100 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.ApproximationContourPlot(), IG.Neural.Forms.Old.FormNeural2DOld.ApproximationPlot(), IG.Neural.Forms.Old.FormNeural2DOld.DefaultContourPlot(), IG.Neural.Forms.Old.FormNeural2DOld.DefaultPlot(), and IG.Neural.Forms.Old.FormNeural2DOld.Start().
trainingSampleX
int IG.Neural.Forms.Old.FormNeural2DOld.trainingSampleX = 5 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.numTrainSampleX_ValueChanged(), IG.Neural.Forms.Old.FormNeural2DOld.Start(), and IG.Neural.Forms.Old.FormNeural2DOld.TrainingPointsPlot().
trainingSampleY
int IG.Neural.Forms.Old.FormNeural2DOld.trainingSampleY = 5 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.numTrainSampleY_ValueChanged(), IG.Neural.Forms.Old.FormNeural2DOld.Start(), and IG.Neural.Forms.Old.FormNeural2DOld.TrainingPointsPlot().
nnType
int IG.Neural.Forms.Old.FormNeural2DOld.nnType = 1 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.cbxAforge_CheckedChanged(), IG.Neural.Forms.Old.FormNeural2DOld.cbxNeuron_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.Start().
equation
string IG.Neural.Forms.Old.FormNeural2DOld.equation = "x*x + y*y" private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.cbEquation_SelectedIndexChanged(), IG.Neural.Forms.Old.FormNeural2DOld.DefaultPlot(), IG.Neural.Forms.Old.FormNeural2DOld.tbSelfMadeEquation_TextChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.TrainingPointsPlot().
variableNames
string [] IG.Neural.Forms.Old.FormNeural2DOld.variableNames = { "x", "y" } private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.DefaultPlot(), and IG.Neural.Forms.Old.FormNeural2DOld.TrainingPointsPlot().
hiddenNeurons
int IG.Neural.Forms.Old.FormNeural2DOld.hiddenNeurons = 5 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.numHiddenNeuron_ValueChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.Start().
maxEpochs
int IG.Neural.Forms.Old.FormNeural2DOld.maxEpochs = 5000 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.numMaxEpoch_ValueChanged().
epochsInBundle
int IG.Neural.Forms.Old.FormNeural2DOld.epochsInBundle = 500 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.numEpochBundle_ValueChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.Start().
learningRate
double IG.Neural.Forms.Old.FormNeural2DOld.learningRate = 0.3 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.numLearningRate_ValueChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.Start().
momentum
double IG.Neural.Forms.Old.FormNeural2DOld.momentum = 0.6 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.numMomentum_ValueChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.Start().
errorRMS
double IG.Neural.Forms.Old.FormNeural2DOld.errorRMS = 0.001 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.numRMS_ValueChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.Start().
inputSafetyFactor
double IG.Neural.Forms.Old.FormNeural2DOld.inputSafetyFactor = 1.3 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.numInputSafety_ValueChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.Start().
outputSafetyFactor
double IG.Neural.Forms.Old.FormNeural2DOld.outputSafetyFactor = 1.3 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.numOutputSafety_ValueChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.Start().
opacityDefaultGraph
double IG.Neural.Forms.Old.FormNeural2DOld.opacityDefaultGraph = 0.5 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.DefaultPlot(), and IG.Neural.Forms.Old.FormNeural2DOld.trackbDefaultGraph_Scroll().
opacityApproxGraph
double IG.Neural.Forms.Old.FormNeural2DOld.opacityApproxGraph = 0.7 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.ApproximationPlot(), and IG.Neural.Forms.Old.FormNeural2DOld.trackbApproxGraph_Scroll().
opacityContourGraph
double IG.Neural.Forms.Old.FormNeural2DOld.opacityContourGraph = 1.0 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.ApproximationContourPlot(), IG.Neural.Forms.Old.FormNeural2DOld.DefaultContourPlot(), and IG.Neural.Forms.Old.FormNeural2DOld.trackbContourGraph_Scroll().
components
System.ComponentModel.IContainer IG.Neural.Forms.Old.FormNeural2DOld.components = null private
Required designer variable.
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.Dispose().
numBoundMaxY
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural2DOld.numBoundMaxY private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural2DOld.numBoundMaxY_ValueChanged().
numBoundMinY
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural2DOld.numBoundMinY private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural2DOld.numBoundMinY_ValueChanged().
numBoundMaxX
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural2DOld.numBoundMaxX private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural2DOld.numBoundMaxX_ValueChanged().
numBoundMinX
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural2DOld.numBoundMinX private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural2DOld.numBoundMinX_ValueChanged().
label1
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label1 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
label2
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label2 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
label3
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label3 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
label4
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label4 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
label5
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label5 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
label6
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label6 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbDefaultSurface
System.Windows.Forms.CheckBox IG.Neural.Forms.Old.FormNeural2DOld.cbDefaultSurface private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.cbDefaultSurface_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbDefaultGreed
System.Windows.Forms.CheckBox IG.Neural.Forms.Old.FormNeural2DOld.cbDefaultGreed private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.cbDefaultGreed_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbTrainingPoints
System.Windows.Forms.CheckBox IG.Neural.Forms.Old.FormNeural2DOld.cbTrainingPoints private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.cbTrainingPoints_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
label7
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label7 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbApproximationGreed
System.Windows.Forms.CheckBox IG.Neural.Forms.Old.FormNeural2DOld.cbApproximationGreed private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.cbApproximationGreed_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbApproximationSurface
System.Windows.Forms.CheckBox IG.Neural.Forms.Old.FormNeural2DOld.cbApproximationSurface private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.cbApproximationSurface_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
label8
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label8 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbContourApproximation
System.Windows.Forms.CheckBox IG.Neural.Forms.Old.FormNeural2DOld.cbContourApproximation private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.cbContourApproximation_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbContourDefault
System.Windows.Forms.CheckBox IG.Neural.Forms.Old.FormNeural2DOld.cbContourDefault private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.cbContourDefault_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
groupBox1
System.Windows.Forms.GroupBox IG.Neural.Forms.Old.FormNeural2DOld.groupBox1 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
groupBox2
System.Windows.Forms.GroupBox IG.Neural.Forms.Old.FormNeural2DOld.groupBox2 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
groupBox3
System.Windows.Forms.GroupBox IG.Neural.Forms.Old.FormNeural2DOld.groupBox3 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
btnShowGraph
System.Windows.Forms.Button IG.Neural.Forms.Old.FormNeural2DOld.btnShowGraph private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
btnStartTraining
System.Windows.Forms.Button IG.Neural.Forms.Old.FormNeural2DOld.btnStartTraining private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
groupBox4
System.Windows.Forms.GroupBox IG.Neural.Forms.Old.FormNeural2DOld.groupBox4 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
label9
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label9 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
tbSelfMadeEquation
System.Windows.Forms.TextBox IG.Neural.Forms.Old.FormNeural2DOld.tbSelfMadeEquation private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.cbSelfMade_CheckedChanged(), IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural2DOld.tbSelfMadeEquation_TextChanged().
cbEquation
System.Windows.Forms.ComboBox IG.Neural.Forms.Old.FormNeural2DOld.cbEquation private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.cbEquation_SelectedIndexChanged(), IG.Neural.Forms.Old.FormNeural2DOld.cbSelfMade_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbSelfMade
System.Windows.Forms.CheckBox IG.Neural.Forms.Old.FormNeural2DOld.cbSelfMade private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.cbSelfMade_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
groupBox5
System.Windows.Forms.GroupBox IG.Neural.Forms.Old.FormNeural2DOld.groupBox5 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numTrainSampleY
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural2DOld.numTrainSampleY private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural2DOld.numTrainSampleY_ValueChanged().
label11
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label11 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numTrainSampleX
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural2DOld.numTrainSampleX private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural2DOld.numTrainSampleX_ValueChanged().
label10
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label10 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
groupBox6
System.Windows.Forms.GroupBox IG.Neural.Forms.Old.FormNeural2DOld.groupBox6 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbxNeuron
System.Windows.Forms.CheckBox IG.Neural.Forms.Old.FormNeural2DOld.cbxNeuron private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.cbxAforge_CheckedChanged(), IG.Neural.Forms.Old.FormNeural2DOld.cbxNeuron_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
cbxAforge
System.Windows.Forms.CheckBox IG.Neural.Forms.Old.FormNeural2DOld.cbxAforge private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.cbxAforge_CheckedChanged(), IG.Neural.Forms.Old.FormNeural2DOld.cbxNeuron_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
groupBox7
System.Windows.Forms.GroupBox IG.Neural.Forms.Old.FormNeural2DOld.groupBox7 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numHiddenNeuron
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural2DOld.numHiddenNeuron private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural2DOld.numHiddenNeuron_ValueChanged().
label12
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label12 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
label17
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label17 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numMomentum
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural2DOld.numMomentum private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural2DOld.numMomentum_ValueChanged().
label16
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label16 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numLearningRate
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural2DOld.numLearningRate private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural2DOld.numLearningRate_ValueChanged().
label15
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label15 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numRMS
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural2DOld.numRMS private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural2DOld.numRMS_ValueChanged().
label14
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label14 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numEpochBundle
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural2DOld.numEpochBundle private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural2DOld.numEpochBundle_ValueChanged().
label13
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label13 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numMaxEpoch
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural2DOld.numMaxEpoch private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural2DOld.numMaxEpoch_ValueChanged().
numOutputSafety
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural2DOld.numOutputSafety private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural2DOld.numOutputSafety_ValueChanged().
label18
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label18 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
numInputSafety
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural2DOld.numInputSafety private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural2DOld.numInputSafety_ValueChanged().
label19
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label19 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
tbEquationError
System.Windows.Forms.TextBox IG.Neural.Forms.Old.FormNeural2DOld.tbEquationError private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.DefaultPlot(), and IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
trackbDefaultGraph
System.Windows.Forms.TrackBar IG.Neural.Forms.Old.FormNeural2DOld.trackbDefaultGraph private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural2DOld.trackbDefaultGraph_Scroll().
label21
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label21 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
label20
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label20 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
trackbApproxGraph
System.Windows.Forms.TrackBar IG.Neural.Forms.Old.FormNeural2DOld.trackbApproxGraph private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural2DOld.trackbApproxGraph_Scroll().
label22
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural2DOld.label22 private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent().
trackbContourGraph
System.Windows.Forms.TrackBar IG.Neural.Forms.Old.FormNeural2DOld.trackbContourGraph private
Referenced by IG.Neural.Forms.Old.FormNeural2DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural2DOld.trackbContourGraph_Scroll().
The documentation for this class was generated from the following files:
shelldev/lib/extended/LibNeuralExtForms/FormsOld/Old/FormNeural2DOld.cs
shelldev/lib/extended/LibNeuralExtForms/FormsOld/Old/FormNeural2DOld.Designer.cs