Doc: IGLib EXTENDED: CShell.Util.ObservableKeyedCollection< TKey, TItem > Class Template Reference
CShell.Util.ObservableKeyedCollection< TKey, TItem > Class Template Reference
Protected Member Functions
ObservableKeyedCollection ()
ObservableKeyedCollection (IEqualityComparer< TKey > comparer)
void OnCollectionChanged (NotifyCollectionChangedEventArgs e)
override void InsertItem (int index, TItem item)
override void SetItem (int index, TItem item)
override void RemoveItem (int index)
override void ClearItems ()
Events
NotifyCollectionChangedEventHandler CollectionChanged
Constructor & Destructor Documentation
ObservableKeyedCollection() [1/2]
CShell.Util.ObservableKeyedCollection< TKey, TItem >.ObservableKeyedCollection () inline protected
ObservableKeyedCollection() [2/2]
CShell.Util.ObservableKeyedCollection< TKey, TItem >.ObservableKeyedCollection (IEqualityComparer< TKey > comparer) inline protected
Member Function Documentation
OnCollectionChanged()
void CShell.Util.ObservableKeyedCollection< TKey, TItem >.OnCollectionChanged (NotifyCollectionChangedEventArgs e) inline protected
Referenced by CShell.Util.ObservableKeyedCollection< string, AssemblyReference >.ClearItems(), CShell.Util.ObservableKeyedCollection< string, AssemblyReference >.InsertItem(), CShell.Util.ObservableKeyedCollection< string, AssemblyReference >.RemoveItem(), and CShell.Util.ObservableKeyedCollection< string, AssemblyReference >.SetItem().
InsertItem()
override void CShell.Util.ObservableKeyedCollection< TKey, TItem >.InsertItem (int index, TItem item) inline protected
SetItem()
override void CShell.Util.ObservableKeyedCollection< TKey, TItem >.SetItem (int index, TItem item) inline protected
RemoveItem()
override void CShell.Util.ObservableKeyedCollection< TKey, TItem >.RemoveItem (int index) inline protected
ClearItems()
override void CShell.Util.ObservableKeyedCollection< TKey, TItem >.ClearItems () inline protected
Event Documentation
CollectionChanged
NotifyCollectionChangedEventHandler CShell.Util.ObservableKeyedCollection< TKey, TItem >.CollectionChanged
Referenced by CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.AssemblyReferencesViewModel(), CShell.Modules.Workspace.ViewModels.AssemblyReferencesViewModel.Dispose(), CShell.AssemblyLoader.Handle(), and CShell.Util.ObservableKeyedCollection< string, AssemblyReference >.OnCollectionChanged().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore/Util/ObservableKeyedCollection.cs