Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DSYEV Class Reference
DotNumerics.LinearAlgebra.CSLapack.DSYEV Class Reference
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DSYEV (LSAME lsame, ILAENV ilaenv, DLAMCH dlamch, DLANSY dlansy, DLASCL dlascl, DORGTR dorgtr, DSCAL dscal, DSTEQR dsteqr, DSTERF dsterf, DSYTRD dsytrd, XERBLA xerbla)
DSYEV ()
void Run (string JOBZ, string UPLO, int N, ref double[] A, int offset_a, int LDA, ref double[] W, int offset_w, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
LSAME _lsame
ILAENV _ilaenv
DLAMCH _dlamch
DLANSY _dlansy
DLASCL _dlascl
DORGTR _dorgtr
DSCAL _dscal
DSTEQR _dsteqr
DSTERF _dsterf
DSYTRD _dsytrd
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
Detailed Description
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DSYEV computes all eigenvalues and, optionally, eigenvectors of a real symmetric matrix A.
/summary>
Constructor & Destructor Documentation
DSYEV() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DSYEV.DSYEV (LSAME lsame, ILAENV ilaenv, DLAMCH dlamch, DLANSY dlansy, DLASCL dlascl, DORGTR dorgtr, DSCAL dscal, DSTEQR dsteqr, DSTERF dsterf, DSYTRD dsytrd, XERBLA xerbla) inline
DSYEV() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DSYEV.DSYEV () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DSYEV.Run (string JOBZ, string UPLO, int N, ref double[] A, int offset_a, int LDA, ref double[] W, int offset_w, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DSYEV computes all eigenvalues and, optionally, eigenvectors of a real symmetric matrix A.
/summary>
Parameters
JOBZ (input) CHARACTER*1 = 'N': Compute eigenvalues only; = 'V': Compute eigenvalues and eigenvectors. /param>
Parameters
UPLO (input) CHARACTER*1 = 'U': Upper triangle of A is stored; = 'L': Lower triangle of A is stored. /param>
Parameters
N (input) INTEGER The order of the matrix A. N .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA, N) On entry, the symmetric matrix A. If UPLO = 'U', the leading N-by-N upper triangular part of A contains the upper triangular part of the matrix A. If UPLO = 'L', the leading N-by-N lower triangular part of A contains the lower triangular part of the matrix A. On exit, if JOBZ = 'V', then if INFO = 0, A contains the orthonormal eigenvectors of the matrix A. If JOBZ = 'N', then on exit the lower triangle (if UPLO='L') or the upper triangle (if UPLO='U') of A, including the diagonal, is destroyed. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,N). /param>
Parameters
W (output) DOUBLE PRECISION array, dimension (N) If INFO = 0, the eigenvalues in ascending order. /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The length of the array WORK. LWORK .GE. max(1,3*N-1). For optimal efficiency, LWORK .GE. (NB+2)*N, where NB is the blocksize for DSYTRD returned by ILAENV.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value .GT. 0: if INFO = i, the algorithm failed to converge; i off-diagonal elements of an intermediate tridiagonal form did not converge to zero. /param>
References DotNumerics.LinearAlgebra.CSLapack.DSYEV.ONE, DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTERF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGTR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANSY.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYTRD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DSYEV.ZERO.
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DSYEV._lsame private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DSYEV._ilaenv private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DSYEV._dlamch private
_dlansy
DLANSY DotNumerics.LinearAlgebra.CSLapack.DSYEV._dlansy private
_dlascl
DLASCL DotNumerics.LinearAlgebra.CSLapack.DSYEV._dlascl private
_dorgtr
DORGTR DotNumerics.LinearAlgebra.CSLapack.DSYEV._dorgtr private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DSYEV._dscal private
_dsteqr
DSTEQR DotNumerics.LinearAlgebra.CSLapack.DSYEV._dsteqr private
_dsterf
DSTERF DotNumerics.LinearAlgebra.CSLapack.DSYEV._dsterf private
_dsytrd
DSYTRD DotNumerics.LinearAlgebra.CSLapack.DSYEV._dsytrd private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DSYEV._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DSYEV.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYEV.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DSYEV.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYEV.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dsyev.cs