Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGGQRF Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGGQRF Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGGQRF (DGEQRF dgeqrf, DGERQF dgerqf, DORMQR dormqr, XERBLA xerbla, ILAENV ilaenv)
DGGQRF ()
void Run (int N, int M, int P, ref double[] A, int offset_a, int LDA, ref double[] TAUA, int offset_taua, ref double[] B, int offset_b, int LDB, ref double[] TAUB, int offset_taub, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
DGEQRF _dgeqrf
DGERQF _dgerqf
DORMQR _dormqr
XERBLA _xerbla
ILAENV _ilaenv
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGGQRF computes a generalized QR factorization of an N-by-M matrix A and an N-by-P matrix B:
A = Q*R, B = Q*T*Z,
where Q is an N-by-N orthogonal matrix, Z is a P-by-P orthogonal matrix, and R and T assume one of the forms:
if N .GE. M, R = (R11) M , or if N .LT. M, R = (R11 R12) N, (0) N-M N M-N M
where R11 is upper triangular, and
if N .LE. P, T = (0 T12) N, or if N .GT. P, T = (T11) N-P, P-N N (T21) P P
where T12 or T21 is upper triangular.
In particular, if B is square and nonsingular, the GQR factorization of A and B implicitly gives the QR factorization of inv(B)*A:
inv(B)*A = Z'*(inv(T)*R)
where inv(B) denotes the inverse of the matrix B, and Z' denotes the transpose of the matrix Z.
/summary>
Constructor & Destructor Documentation
DGGQRF() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGGQRF.DGGQRF (DGEQRF dgeqrf, DGERQF dgerqf, DORMQR dormqr, XERBLA xerbla, ILAENV ilaenv) inline
DGGQRF() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGGQRF.DGGQRF () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGGQRF.Run (int N, int M, int P, ref double[] A, int offset_a, int LDA, ref double[] TAUA, int offset_taua, ref double[] B, int offset_b, int LDB, ref double[] TAUB, int offset_taub, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DGGQRF computes a generalized QR factorization of an N-by-M matrix A and an N-by-P matrix B:
A = Q*R, B = Q*T*Z,
where Q is an N-by-N orthogonal matrix, Z is a P-by-P orthogonal matrix, and R and T assume one of the forms:
if N .GE. M, R = (R11) M , or if N .LT. M, R = (R11 R12) N, (0) N-M N M-N M
where R11 is upper triangular, and
if N .LE. P, T = (0 T12) N, or if N .GT. P, T = (T11) N-P, P-N N (T21) P P
where T12 or T21 is upper triangular.
In particular, if B is square and nonsingular, the GQR factorization of A and B implicitly gives the QR factorization of inv(B)*A:
inv(B)*A = Z'*(inv(T)*R)
where inv(B) denotes the inverse of the matrix B, and Z' denotes the transpose of the matrix Z.
/summary>
Parameters
N (input) INTEGER The number of rows of the matrices A and B. N .GE. 0. /param>
Parameters
M (input) INTEGER The number of columns of the matrix A. M .GE. 0. /param>
Parameters
P (input) INTEGER The number of columns of the matrix B. P .GE. 0. /param>
Parameters
A = Q*R, B = Q*T*Z, /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,N). /param>
Parameters
TAUA (output) DOUBLE PRECISION array, dimension (min(N,M)) The scalar factors of the elementary reflectors which represent the orthogonal matrix Q (see Further Details). /param>
Parameters
B (input/output) DOUBLE PRECISION array, dimension (LDB,P) On entry, the N-by-P matrix B. On exit, if N .LE. P, the upper triangle of the subarray B(1:N,P-N+1:P) contains the N-by-N upper triangular matrix T; if N .GT. P, the elements on and above the (N-P)-th subdiagonal contain the N-by-P upper trapezoidal matrix T; the remaining elements, with the array TAUB, represent the orthogonal matrix Z as a product of elementary reflectors (see Further Details). /param>
Parameters
LDB (input) INTEGER The leading dimension of the array B. LDB .GE. max(1,N). /param>
Parameters
TAUB (output) DOUBLE PRECISION array, dimension (min(N,P)) The scalar factors of the elementary reflectors which represent the orthogonal matrix Z (see Further Details). /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. max(1,N,M,P). For optimum performance LWORK .GE. max(N,M,P)*max(NB1,NB2,NB3), where NB1 is the optimal blocksize for the QR factorization of an N-by-M matrix, NB2 is the optimal blocksize for the RQ factorization of an N-by-P matrix, and NB3 is the optimal blocksize for a call of DORMQR.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value. /param>
References DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGERQF.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DORMQR.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGGGLM.Run().
Member Data Documentation
_dgeqrf
DGEQRF DotNumerics.LinearAlgebra.CSLapack.DGGQRF._dgeqrf private
_dgerqf
DGERQF DotNumerics.LinearAlgebra.CSLapack.DGGQRF._dgerqf private
_dormqr
DORMQR DotNumerics.LinearAlgebra.CSLapack.DGGQRF._dormqr private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGGQRF._xerbla private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DGGQRF._ilaenv private
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dggqrf.cs