Doc: IGLib EXTENDED: NUnit.Framework.Api.ITestAssemblyRunner Interface Reference
NUnit.Framework.Api.ITestAssemblyRunner Interface Reference
The ITestAssemblyRunner interface is implemented by classes that are able to execute a suite of tests loaded from an assembly.
Public Member Functions
ITest Load (string assemblyName, System.Collections.IDictionary settings)
Loads the tests found in an Assembly, returning an indication of whether or not the load succeeded.
ITest Load (Assembly assembly, System.Collections.IDictionary settings)
Loads the tests found in an Assembly, returning an indication of whether or not the load succeeded.
int CountTestCases (ITestFilter filter)
Count Test Cases using a filter
ITestResult Run (ITestListener listener, ITestFilter filter)
Run selected tests and return a test result. The test is run synchronously, and the listener interface is notified as it progresses.
void RunAsync (ITestListener listener, ITestFilter filter)
Run selected tests asynchronously, notifying the listener interface as it progresses.
bool WaitForCompletion (int timeout)
Wait for the ongoing run to complete.
void StopRun (bool force)
Signal any test run that is in process to stop. Return without error if no test is running.
Properties
ITest LoadedTest [get]
Gets the tree of loaded tests, or null if no tests have been loaded.
ITestResult Result [get]
Gets the tree of test results, if the test run is completed, otherwise null.
bool IsTestLoaded [get]
Indicates whether a test has been loaded
bool IsTestRunning [get]
Indicates whether a test is currently running
bool IsTestComplete [get]
Indicates whether a test run is complete
Detailed Description
The ITestAssemblyRunner interface is implemented by classes that are able to execute a suite of tests loaded from an assembly.
Member Function Documentation
Load() [1/2]
ITest NUnit.Framework.Api.ITestAssemblyRunner.Load (string assemblyName, System.Collections.IDictionary settings)
Loads the tests found in an Assembly, returning an indication of whether or not the load succeeded.
Parameters
assemblyName File name of the assembly to load
settings Dictionary of options to use in loading the test
Returns
An ITest representing the loaded tests
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CancelRun_WhenTestIsRunning_StopsTest(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_AfterLoad_ReturnsCorrectCount(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_BadFile_ReturnsZero(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_FileNotFound_ReturnsZero(), NUnitLite.TextRunner.Execute(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Load_GoodFile_ReturnsRunnableSuite(), NUnit.Framework.Api.FrameworkController.LoadTests(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Internal.SetUpFixtureTests.runTests(), and NUnit.Framework.Api.TestAssemblyRunnerTests.StopRun_WhenTestIsRunning_StopsTest().
Load() [2/2]
ITest NUnit.Framework.Api.ITestAssemblyRunner.Load (Assembly assembly, System.Collections.IDictionary settings)
Loads the tests found in an Assembly, returning an indication of whether or not the load succeeded.
Parameters
assembly The assembly to load
settings Dictionary of options to use in loading the test
Returns
An ITest representing the loaded tests
CountTestCases()
int NUnit.Framework.Api.ITestAssemblyRunner.CountTestCases (ITestFilter filter)
Count Test Cases using a filter
Parameters
filter The filter to apply
Returns
The number of test cases found
Implemented in NUnit.Framework.Api.NUnitTestAssemblyRunner.
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_AfterLoad_ReturnsCorrectCount(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_BadFile_ReturnsZero(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_FileNotFound_ReturnsZero(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_WithoutLoad_ThrowsInvalidOperation(), and NUnit.Framework.Api.FrameworkController.CountTests().
Run()
ITestResult NUnit.Framework.Api.ITestAssemblyRunner.Run (ITestListener listener, ITestFilter filter)
Run selected tests and return a test result. The test is run synchronously, and the listener interface is notified as it progresses.
Parameters
listener Interface to receive ITestListener notifications.
filter A test filter used to select tests to be run
Implemented in NUnit.Framework.Api.NUnitTestAssemblyRunner.
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_WithoutLoad_ReturnsError(), NUnit.Framework.Internal.SetUpFixtureTests.runTests(), NUnitLite.TextRunner.RunTests(), and NUnit.Framework.Api.FrameworkController.RunTests().
RunAsync()
void NUnit.Framework.Api.ITestAssemblyRunner.RunAsync (ITestListener listener, ITestFilter filter)
Run selected tests asynchronously, notifying the listener interface as it progresses.
Parameters
listener Interface to receive EventListener notifications.
filter A test filter used to select tests to be run
Implemented in NUnit.Framework.Api.NUnitTestAssemblyRunner.
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CancelRun_WhenTestIsRunning_StopsTest(), NUnit.Framework.Api.FrameworkController.RunAsync(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_WithoutLoad_ReturnsError(), and NUnit.Framework.Api.TestAssemblyRunnerTests.StopRun_WhenTestIsRunning_StopsTest().
WaitForCompletion()
bool NUnit.Framework.Api.ITestAssemblyRunner.WaitForCompletion (int timeout)
Wait for the ongoing run to complete.
Parameters
timeout Time to wait in milliseconds
Returns
True if the run completed, otherwise false
Implemented in NUnit.Framework.Api.NUnitTestAssemblyRunner.
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CancelRun_WhenTestIsRunning_StopsTest(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_FileNotFound_ReturnsNonRunnableSuite(), and NUnit.Framework.Api.TestAssemblyRunnerTests.StopRun_WhenTestIsRunning_StopsTest().
StopRun()
void NUnit.Framework.Api.ITestAssemblyRunner.StopRun (bool force)
Signal any test run that is in process to stop. Return without error if no test is running.
Parameters
force If true, kill any test-running threads
Implemented in NUnit.Framework.Api.NUnitTestAssemblyRunner.
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CancelRun_WhenNoTestIsRunning_Succeeds(), NUnit.Framework.Api.TestAssemblyRunnerTests.CancelRun_WhenTestIsRunning_StopsTest(), NUnit.Framework.Api.FrameworkController.StopRun(), NUnit.Framework.Api.TestAssemblyRunnerTests.StopRun_WhenNoTestIsRunning_Succeeds(), and NUnit.Framework.Api.TestAssemblyRunnerTests.StopRun_WhenTestIsRunning_StopsTest().
Property Documentation
LoadedTest
ITest NUnit.Framework.Api.ITestAssemblyRunner.LoadedTest get
Gets the tree of loaded tests, or null if no tests have been loaded.
Referenced by NUnit.Framework.Api.FrameworkController.ExploreTests(), NUnitLite.TextRunner.ExploreTests(), and NUnit.Framework.Api.FrameworkController.LoadTests().
Result
ITestResult NUnit.Framework.Api.ITestAssemblyRunner.Result get
Gets the tree of test results, if the test run is completed, otherwise null.
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CancelRun_WhenTestIsRunning_StopsTest(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_FileNotFound_ReturnsNonRunnableSuite(), and NUnit.Framework.Api.TestAssemblyRunnerTests.StopRun_WhenTestIsRunning_StopsTest().
IsTestLoaded
bool NUnit.Framework.Api.ITestAssemblyRunner.IsTestLoaded get
Indicates whether a test has been loaded
IsTestRunning
bool NUnit.Framework.Api.ITestAssemblyRunner.IsTestRunning get
Indicates whether a test is currently running
IsTestComplete
bool NUnit.Framework.Api.ITestAssemblyRunner.IsTestComplete get
Indicates whether a test run is complete
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CancelRun_WhenTestIsRunning_StopsTest(), and NUnit.Framework.Api.TestAssemblyRunnerTests.StopRun_WhenTestIsRunning_StopsTest().
The documentation for this interface was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Api/ITestAssemblyRunner.cs