Doc: IGLib EXTENDED: IG.Lib.MathematicaInterface Class Reference
IG.Lib.MathematicaInterface Class Reference
Interface with Mathematica.
Public Member Functions
MathematicaInterface ()
Constructs a new Mathematica interface object, without initializing a Mathematica link.
MathematicaInterface (IKernelLink ml)
Constructs a new Mathematica interface object, initialized with the specified Mathematica link.
MathematicaInterface (MathKernel kernel)
Constructs a new Mathematica interface object, initialized with the specified Mathematica link.
virtual void Init (MathKernel kernel)
Initializes the current Mathematica interface object.
double EvaluateScalarFunction (string functionName, double functionArgument)
Evaluates mathematica function that takes one numerical argument and returns a number.
double EvaluateScalarFunction (string functionName, double[] functionArguments)
Evaluates mathematica function that takes one array argument and returns a number.
double EvaluateScalarFunction (string functionName, IVector functionArguments)
Evaluates mathematica function that takes one array argument and returns a number.
string EvaluateExpression (string expression)
Evaluates the specified expression in Mathematica and returns the result in output form as string.
int EvaluateIntegerExpression (string expression)
Evaluates an integer-valued expression in Mathematica and returns its value.
double EvaluateDoubleExpression (string expression)
Evaluates an real (double)-valued expression in Mathematica and returns its value.
Static Public Member Functions
static void ExampleCalculator ()
Example use of Mathematica interface - a simple calculator.
static void ExampleCalculator (bool wrapNumerical)
Example use of Mathematica interface - a simple calculator.
Protected Member Functions
virtual void Init ()
Initializes the current Mathematica interface object.
virtual void Init (IKernelLink ml)
Initializes the current Mathematica interface object.
Protected Attributes
IKernelLink _mathLink
Wolfram.NETLink.MathKernel _mathKernel
Static Protected Attributes
static MathematicaInterface _global
Properties
object Lock [get]
Object's lock
static MathematicaInterface Global [get]
Gets the global Mathematica interface.
IKernelLink MathLink [get, protected set]
Mathematica's link object.
MathKernel MathKernel [get, protected set]
Mathematica kernel.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
readonly object _lock = new object()
Detailed Description
Interface with Mathematica.
Constructor & Destructor Documentation
MathematicaInterface() [1/3]
IG.Lib.MathematicaInterface.MathematicaInterface () inline
Constructs a new Mathematica interface object, without initializing a Mathematica link.
Link is initialized the first time it is used.
References IG.Lib.MathematicaInterface.Init().
MathematicaInterface() [2/3]
IG.Lib.MathematicaInterface.MathematicaInterface (IKernelLink ml) inline
Constructs a new Mathematica interface object, initialized with the specified Mathematica link.
Parameters
ml The Mathematica link which is assigned to the object for communication with Mathematica. If null then no link is assigned and a link will be created the first time it is used.
References IG.Lib.MathematicaInterface.Init().
MathematicaInterface() [3/3]
IG.Lib.MathematicaInterface.MathematicaInterface (MathKernel kernel) inline
Constructs a new Mathematica interface object, initialized with the specified Mathematica link.
Parameters
kernel The Mathematica kernel which is assigned to the object for communication with Mathematica.
References IG.Lib.MathematicaInterface.Init().
Member Function Documentation
Init() [1/3]
virtual void IG.Lib.MathematicaInterface.Init () inline protected virtual
Initializes the current Mathematica interface object.
References IG.Lib.MathematicaInterface.MathKernel.
Referenced by IG.Lib.MathematicaInterface.MathematicaInterface().
Init() [2/3]
virtual void IG.Lib.MathematicaInterface.Init (IKernelLink ml) inline protected virtual
Initializes the current Mathematica interface object.
This sets the mathematica link if the specified link (argument ml) is not null.
Parameters
ml The Mathematica link which is assigned to the object for communication with Mathematica.
References IG.Lib.MathematicaInterface.MathLink.
Init() [3/3]
virtual void IG.Lib.MathematicaInterface.Init (MathKernel kernel) inline virtual
Initializes the current Mathematica interface object.
This sets the mathematica kernel if the specified kernel (argument ml) is not null.
Parameters
kernel The Mathematica kernel which is assigned to the object for communication with Mathematica.
References IG.Lib.MathematicaInterface.MathKernel.
EvaluateScalarFunction() [1/3]
double IG.Lib.MathematicaInterface.EvaluateScalarFunction (string functionName, double functionArgument) inline
Evaluates mathematica function that takes one numerical argument and returns a number.
Example: double res = EvaluateDoubleFunction("Sin",0.5);
Parameters
functionName Name of the function.
functionArgument Argument of function.
Returns
Function value.
References IG.Lib.MathematicaInterface.MathLink.
EvaluateScalarFunction() [2/3]
double IG.Lib.MathematicaInterface.EvaluateScalarFunction (string functionName, double[] functionArguments) inline
Evaluates mathematica function that takes one array argument and returns a number.
Example: double res = EvaluateDoubleFunction("Plus",0.5,0.2);
Parameters
functionName Name of the function.
functionArguments Arguments of function.
Returns
Function value.
References IG.Lib.MathematicaInterface.MathLink.
EvaluateScalarFunction() [3/3]
double IG.Lib.MathematicaInterface.EvaluateScalarFunction (string functionName, IVector functionArguments) inline
Evaluates mathematica function that takes one array argument and returns a number.
Example: double res = EvaluateDoubleFunction("Plus",0.5,0.2);
Parameters
functionName Name of the function.
functionArguments Arguments of function.
Returns
Function value.
References IG.Lib.MathematicaInterface.MathLink, and IG.Num.IVector< T >.ToArray().
EvaluateExpression()
string IG.Lib.MathematicaInterface.EvaluateExpression (string expression) inline
Evaluates the specified expression in Mathematica and returns the result in output form as string.
Parameters
expression Mathematical expression to be evaluated.
Returns
Result of evaluation in string form.
References IG.Lib.MathematicaInterface.MathLink.
Referenced by IG.Lib.MathematicaInterface.ExampleCalculator().
EvaluateIntegerExpression()
int IG.Lib.MathematicaInterface.EvaluateIntegerExpression (string expression) inline
Evaluates an integer-valued expression in Mathematica and returns its value.
Parameters
expression Integer-valued expression to be evaluated.
Returns
V of the expression.
References IG.Lib.MathematicaInterface.MathLink.
EvaluateDoubleExpression()
double IG.Lib.MathematicaInterface.EvaluateDoubleExpression (string expression) inline
Evaluates an real (double)-valued expression in Mathematica and returns its value.
Parameters
expression Expression to be evaluated.
Returns
Value of the expression.
References IG.Lib.MathematicaInterface.MathLink.
ExampleCalculator() [1/2]
static void IG.Lib.MathematicaInterface.ExampleCalculator () inline static
Example use of Mathematica interface - a simple calculator.
Expressions are evaluated to rounded numerical values when possible (i.e. they are wrapped in 'N[...]' before sent to evaluation.
Referenced by IG.Script.AppTestShellExt.MathematicaFunctionTestApp().
ExampleCalculator() [2/2]
static void IG.Lib.MathematicaInterface.ExampleCalculator (bool wrapNumerical) inline static
Example use of Mathematica interface - a simple calculator.
Parameters
wrapNumerical Specifies whether expressions should return rounded numerical values when possible (i.e. they are wrapped in 'N[...]' before sent to evaluation).
References IG.Lib.MathematicaInterface.EvaluateExpression(), IG.Lib.MathematicaInterface.Global, and IG.Lib.UtilConsole.Read().
Member Data Documentation
_lock
readonly object IG.Lib.MathematicaInterface._lock = new object() private
_global
MathematicaInterface IG.Lib.MathematicaInterface._global static protected
_mathLink
IKernelLink IG.Lib.MathematicaInterface._mathLink protected
_mathKernel
Wolfram.NETLink.MathKernel IG.Lib.MathematicaInterface._mathKernel protected
Property Documentation
Lock
object IG.Lib.MathematicaInterface.Lock get
Object's lock
Global
MathematicaInterface IG.Lib.MathematicaInterface.Global static get
Gets the global Mathematica interface.
Referenced by IG.Lib.MathematicaInterface.ExampleCalculator().
MathLink
IKernelLink IG.Lib.MathematicaInterface.MathLink get protected set
Mathematica's link object.
Getter always returns a valid link object, creating a new one if not yet created.
Referenced by IG.Lib.MathematicaInterface.EvaluateDoubleExpression(), IG.Lib.MathematicaInterface.EvaluateExpression(), IG.Lib.MathematicaInterface.EvaluateIntegerExpression(), IG.Lib.MathematicaInterface.EvaluateScalarFunction(), and IG.Lib.MathematicaInterface.Init().
MathKernel
MathKernel IG.Lib.MathematicaInterface.MathKernel get protected set
Mathematica kernel.
Referenced by IG.Lib.MathematicaInterface.Init().
The documentation for this class was generated from the following file:
igtest/IGLibTestShellExt/mathematica/MathInt.cs