Doc: IGLib EXTENDED: IG.MsOffice.ExcelExample Class Reference
IG.MsOffice.ExcelExample Class Reference
Public Member Functions
void ExampleUsage ()
void CreateExcelFile (string filePath)
Creates an example Excel file and saves it ath the specified path.
void OpenExcelFile (string filePath)
Opens the Excel file at the specified path.
void TestFillRange ()
Test where range of Excel cells is filled.
Protected Member Functions
void TestFillRangePart1 ()
void TestFillRangePart2 ()
Private Member Functions
void releaseObject (object obj)
Private Attributes
Excel.Application objApp
Excel._Workbook objBook
bool FillWithStrings = false
Member Function Documentation
ExampleUsage()
void IG.MsOffice.ExcelExample.ExampleUsage () inline
CreateExcelFile()
void IG.MsOffice.ExcelExample.CreateExcelFile (string filePath) inline
Creates an example Excel file and saves it ath the specified path.
Parameters
filePath Path where the file is saved.
References IG.MsOffice.ExcelExample.releaseObject().
Referenced by IG.Script.ScriptExtExamplesExt.Custom().
OpenExcelFile()
void IG.MsOffice.ExcelExample.OpenExcelFile (string filePath) inline
Opens the Excel file at the specified path.
Parameters
filePath Psth to the Excel file to be opened.
References IG.MsOffice.ExcelExample.releaseObject().
Referenced by IG.Script.ScriptExtExamplesExt.Custom().
TestFillRange()
void IG.MsOffice.ExcelExample.TestFillRange () inline
Test where range of Excel cells is filled.
References IG.MsOffice.ExcelExample.TestFillRangePart1(), and IG.MsOffice.ExcelExample.TestFillRangePart2().
Referenced by IG.Script.ScriptExtExamplesExt.Custom().
TestFillRangePart1()
void IG.MsOffice.ExcelExample.TestFillRangePart1 () inline protected
References IG.MsOffice.ExcelExample.objApp, and IG.MsOffice.ExcelExample.objBook.
Referenced by IG.MsOffice.ExcelExample.TestFillRange().
TestFillRangePart2()
void IG.MsOffice.ExcelExample.TestFillRangePart2 () inline protected
References IG.MsOffice.ExcelExample.objBook.
Referenced by IG.MsOffice.ExcelExample.TestFillRange().
releaseObject()
void IG.MsOffice.ExcelExample.releaseObject (object obj) inline private
Referenced by IG.MsOffice.ExcelExample.CreateExcelFile(), and IG.MsOffice.ExcelExample.OpenExcelFile().
Member Data Documentation
objApp
Excel.Application IG.MsOffice.ExcelExample.objApp private
Referenced by IG.MsOffice.ExcelExample.TestFillRangePart1().
objBook
Excel._Workbook IG.MsOffice.ExcelExample.objBook private
Referenced by IG.MsOffice.ExcelExample.TestFillRangePart1(), and IG.MsOffice.ExcelExample.TestFillRangePart2().
FillWithStrings
bool IG.MsOffice.ExcelExample.FillWithStrings = false private
The documentation for this class was generated from the following file:
shelldev/extensions_shell/ExtShellAppExt/excel/ExcelExample.cs