Doc: IGLib EXTENDED: NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests Class Reference
NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests Class Reference
Public Member Functions
void CreateServiceContext ()
void ServiceIsStarted ()
void CorrectRunnerIsUsed (string files, string processModel, Type expectedType)
void CorrectRunnerIsUsed_InvalidExtension (string files, Type expectedType)
Private Attributes
ServiceContext _services
DefaultTestRunnerFactory _factory
Member Function Documentation
CreateServiceContext()
void NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CreateServiceContext () inline
References NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests._factory, NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests._services, NUnit.Engine.ServiceContext.Add(), and NUnit.Engine.ServiceContext.ServiceManager.
ServiceIsStarted()
void NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.ServiceIsStarted () inline
References NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests._factory, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Services.Service.Status, and NUnit.Framework.Assert.That().
CorrectRunnerIsUsed()
void NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CorrectRunnerIsUsed (string files, string processModel, Type expectedType) inline
References NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests._factory, NUnit.Engine.Services.DefaultTestRunnerFactory.MakeTestRunner(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
CorrectRunnerIsUsed_InvalidExtension()
void NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CorrectRunnerIsUsed_InvalidExtension (string files, Type expectedType) inline
References NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests._factory, NUnit.Engine.Services.DefaultTestRunnerFactory.MakeTestRunner(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
Member Data Documentation
_services
ServiceContext NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests._services private
Referenced by NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CreateServiceContext().
_factory
DefaultTestRunnerFactory NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests._factory private
Referenced by NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CorrectRunnerIsUsed(), NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CorrectRunnerIsUsed_InvalidExtension(), NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.CreateServiceContext(), and NUnit.Engine.Services.Tests.DefaultTestRunnerFactoryTests.ServiceIsStarted().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Services/DefaultTestRunnerFactoryTests.cs