Doc: IGLib EXTENDED: TSP.MainForm Class Reference
TSP.MainForm Class Reference
Summary description for Form1.
Public Member Functions
MainForm ()
MainForm ()
MainForm ()
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void GenerateMap ()
void generateMapButton_Click (object sender, System.EventArgs e)
void EnableControls (bool enable)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void GenerateMap ()
void generateMapButton_Click (object sender, System.EventArgs e)
void EnableControls (bool enable)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
delegate void SetTextCallback (System.Windows.Forms.Control control, string text)
void SetText (System.Windows.Forms.Control control, string text)
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
delegate void EnableCallback (bool enable)
void EnableControls (bool enable)
void GenerateMap ()
void generateMapButton_Click (object sender, System.EventArgs e)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
delegate void SetTextCallback (System.Windows.Forms.Control control, string text)
void SetText (System.Windows.Forms.Control control, string text)
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void GenerateMap ()
void generateMapButton_Click (object sender, System.EventArgs e)
delegate void EnableCallback (bool enable)
void EnableControls (bool enable)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
Static Private Member Functions
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
Private Attributes
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.Button generateMapButton
System.Windows.Forms.TextBox citiesCountBox
System.Windows.Forms.Label label1
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.Label label2
System.Windows.Forms.TextBox neuronsBox
System.Windows.Forms.Label label3
System.Windows.Forms.TextBox currentIterationBox
System.Windows.Forms.Label label8
System.Windows.Forms.Label label7
System.Windows.Forms.TextBox rateBox
System.Windows.Forms.Label label5
System.Windows.Forms.TextBox iterationsBox
System.Windows.Forms.Label label6
System.Windows.Forms.Button stopButton
System.Windows.Forms.Button startButton
AForge.Controls.Chart chart
System.Windows.Forms.Label label4
System.Windows.Forms.TextBox radiusBox
System.ComponentModel.Container components = null
Required designer variable.
int citiesCount = 10
int neurons = 20
int iterations = 500
double learningRate = 0.5
double learningRadius = 0.5
double[,] map = null
Random rand = new Random()
Thread workerThread = null
bool needToStop = false
AForge.Controls.Chart mapControl
System.Windows.Forms.TextBox populationSizeBox
System.Windows.Forms.ComboBox selectionBox
System.Windows.Forms.GroupBox groupBox3
System.Windows.Forms.TextBox pathLengthBox
System.Windows.Forms.CheckBox greedyCrossoverBox
int populationSize = 40
int selectionMethod = 0
bool greedyCrossover = true
volatile bool needToStop = false
Detailed Description
Summary description for Form1.
Summary description for MainForm.
Constructor & Destructor Documentation
MainForm() [1/4]
TSP.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), TSP.MainForm.chart, TSP.MainForm.GenerateMap(), TSP.MainForm.InitializeComponent(), AForge.Controls.Chart.RangeX, AForge.Controls.Chart.RangeY, and TSP.MainForm.UpdateSettings().
Referenced by TSP.MainForm.Main().
MainForm() [2/4]
TSP.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), TSP.MainForm.chart, TSP.MainForm.GenerateMap(), TSP.MainForm.InitializeComponent(), AForge.Controls.Chart.RangeX, AForge.Controls.Chart.RangeY, and TSP.MainForm.UpdateSettings().
MainForm() [3/4]
TSP.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), TSP.MainForm.GenerateMap(), TSP.MainForm.greedyCrossover, TSP.MainForm.greedyCrossoverBox, TSP.MainForm.InitializeComponent(), TSP.MainForm.mapControl, AForge.Controls.Chart.RangeX, AForge.Controls.Chart.RangeY, TSP.MainForm.selectionBox, TSP.MainForm.selectionMethod, and TSP.MainForm.UpdateSettings().
MainForm() [4/4]
TSP.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), TSP.MainForm.chart, TSP.MainForm.GenerateMap(), TSP.MainForm.InitializeComponent(), AForge.Controls.Chart.RangeX, AForge.Controls.Chart.RangeY, and TSP.MainForm.UpdateSettings().
Member Function Documentation
Dispose() [1/4]
override void TSP.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References TSP.MainForm.components.
InitializeComponent() [1/4]
void TSP.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by TSP.MainForm.MainForm().
Main() [1/4]
static void TSP.MainForm.Main () inline static private
The main entry point for the application.
References TSP.MainForm.MainForm().
MainForm_Closing() [1/4]
void TSP.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References TSP.MainForm.needToStop, and TSP.MainForm.workerThread.
UpdateSettings() [1/4]
void TSP.MainForm.UpdateSettings () inline private
References TSP.MainForm.citiesCount, TSP.MainForm.citiesCountBox, TSP.MainForm.iterations, TSP.MainForm.iterationsBox, TSP.MainForm.learningRadius, TSP.MainForm.learningRate, TSP.MainForm.neurons, TSP.MainForm.neuronsBox, TSP.MainForm.radiusBox, and TSP.MainForm.rateBox.
Referenced by TSP.MainForm.MainForm(), and TSP.MainForm.startButton_Click().
GenerateMap() [1/4]
void TSP.MainForm.GenerateMap () inline private
References TSP.MainForm.chart, TSP.MainForm.citiesCount, TSP.MainForm.map, TSP.MainForm.rand, and AForge.Controls.Chart.UpdateDataSeries().
Referenced by TSP.MainForm.generateMapButton_Click(), and TSP.MainForm.MainForm().
generateMapButton_Click() [1/4]
void TSP.MainForm.generateMapButton_Click (object sender, System.EventArgs e) inline private
References TSP.MainForm.citiesCount, TSP.MainForm.citiesCountBox, and TSP.MainForm.GenerateMap().
EnableControls() [1/4]
void TSP.MainForm.EnableControls (bool enable) inline private
References TSP.MainForm.generateMapButton, TSP.MainForm.iterationsBox, TSP.MainForm.neuronsBox, TSP.MainForm.radiusBox, TSP.MainForm.rateBox, TSP.MainForm.startButton, and TSP.MainForm.stopButton.
Referenced by TSP.MainForm.EnableControls(), TSP.MainForm.SearchSolution(), and TSP.MainForm.startButton_Click().
startButton_Click() [1/4]
void TSP.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References TSP.MainForm.EnableControls(), TSP.MainForm.iterations, TSP.MainForm.iterationsBox, TSP.MainForm.learningRadius, TSP.MainForm.learningRate, TSP.MainForm.needToStop, TSP.MainForm.neurons, TSP.MainForm.neuronsBox, TSP.MainForm.radiusBox, TSP.MainForm.rateBox, TSP.MainForm.SearchSolution(), TSP.MainForm.UpdateSettings(), and TSP.MainForm.workerThread.
stopButton_Click() [1/4]
void TSP.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References TSP.MainForm.needToStop, and TSP.MainForm.workerThread.
SearchSolution() [1/4]
void TSP.MainForm.SearchSolution () inline private
References TSP.MainForm.chart, TSP.MainForm.citiesCount, TSP.MainForm.currentIterationBox, TSP.MainForm.EnableControls(), TSP.MainForm.iterations, TSP.MainForm.learningRadius, AForge.Neuro.Learning.ElasticNetworkLearning.LearningRadius, AForge.Neuro.Learning.ElasticNetworkLearning.LearningRate, TSP.MainForm.learningRate, TSP.MainForm.map, TSP.MainForm.needToStop, TSP.MainForm.neurons, TSP.MainForm.rand, AForge.Neuro.Neuron.RandRange, AForge.Neuro.Learning.ElasticNetworkLearning.Run(), and AForge.Controls.Chart.UpdateDataSeries().
Referenced by TSP.MainForm.startButton_Click().
Dispose() [2/4]
override void TSP.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References TSP.MainForm.components.
InitializeComponent() [2/4]
void TSP.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [2/4]
static void TSP.MainForm.Main () inline static private
The main entry point for the application.
References TSP.MainForm.MainForm().
MainForm_Closing() [2/4]
void TSP.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References TSP.MainForm.needToStop, and TSP.MainForm.workerThread.
UpdateSettings() [2/4]
void TSP.MainForm.UpdateSettings () inline private
References TSP.MainForm.citiesCount, TSP.MainForm.citiesCountBox, TSP.MainForm.iterations, TSP.MainForm.iterationsBox, TSP.MainForm.learningRadius, TSP.MainForm.learningRate, TSP.MainForm.neurons, TSP.MainForm.neuronsBox, TSP.MainForm.radiusBox, and TSP.MainForm.rateBox.
GenerateMap() [2/4]
void TSP.MainForm.GenerateMap () inline private
References TSP.MainForm.chart, TSP.MainForm.citiesCount, TSP.MainForm.map, TSP.MainForm.rand, and AForge.Controls.Chart.UpdateDataSeries().
generateMapButton_Click() [2/4]
void TSP.MainForm.generateMapButton_Click (object sender, System.EventArgs e) inline private
References TSP.MainForm.citiesCount, TSP.MainForm.citiesCountBox, and TSP.MainForm.GenerateMap().
EnableControls() [2/4]
void TSP.MainForm.EnableControls (bool enable) inline private
References TSP.MainForm.generateMapButton, TSP.MainForm.iterationsBox, TSP.MainForm.neuronsBox, TSP.MainForm.radiusBox, TSP.MainForm.rateBox, TSP.MainForm.startButton, and TSP.MainForm.stopButton.
startButton_Click() [2/4]
void TSP.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References TSP.MainForm.EnableControls(), TSP.MainForm.iterations, TSP.MainForm.iterationsBox, TSP.MainForm.learningRadius, TSP.MainForm.learningRate, TSP.MainForm.needToStop, TSP.MainForm.neurons, TSP.MainForm.neuronsBox, TSP.MainForm.radiusBox, TSP.MainForm.rateBox, TSP.MainForm.SearchSolution(), TSP.MainForm.UpdateSettings(), and TSP.MainForm.workerThread.
stopButton_Click() [2/4]
void TSP.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References TSP.MainForm.needToStop, and TSP.MainForm.workerThread.
SearchSolution() [2/4]
void TSP.MainForm.SearchSolution () inline private
References TSP.MainForm.chart, TSP.MainForm.citiesCount, TSP.MainForm.currentIterationBox, TSP.MainForm.EnableControls(), TSP.MainForm.iterations, TSP.MainForm.learningRadius, AForge.Neuro.Learning.ElasticNetworkLearning.LearningRadius, AForge.Neuro.Learning.ElasticNetworkLearning.LearningRate, TSP.MainForm.learningRate, TSP.MainForm.map, TSP.MainForm.needToStop, TSP.MainForm.neurons, TSP.MainForm.rand, AForge.Neuro.Neuron.RandRange, AForge.Neuro.Learning.ElasticNetworkLearning.Run(), and AForge.Controls.Chart.UpdateDataSeries().
Dispose() [3/4]
override void TSP.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References TSP.MainForm.components.
InitializeComponent() [3/4]
void TSP.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [3/4]
static void TSP.MainForm.Main () inline static private
The main entry point for the application.
References TSP.MainForm.MainForm().
SetTextCallback() [1/2]
delegate void TSP.MainForm.SetTextCallback (System.Windows.Forms.Control control, string text) private
Referenced by TSP.MainForm.SetText().
SetText() [1/2]
void TSP.MainForm.SetText (System.Windows.Forms.Control control, string text) inline private
References TSP.MainForm.SetTextCallback().
Referenced by TSP.MainForm.SearchSolution(), and TSP.MainForm.SetText().
MainForm_Closing() [3/4]
void TSP.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References TSP.MainForm.needToStop, and TSP.MainForm.workerThread.
UpdateSettings() [3/4]
void TSP.MainForm.UpdateSettings () inline private
References TSP.MainForm.citiesCount, TSP.MainForm.citiesCountBox, TSP.MainForm.iterations, TSP.MainForm.iterationsBox, TSP.MainForm.populationSize, and TSP.MainForm.populationSizeBox.
EnableCallback() [1/2]
delegate void TSP.MainForm.EnableCallback (bool enable) private
Referenced by TSP.MainForm.EnableControls().
EnableControls() [3/4]
void TSP.MainForm.EnableControls (bool enable) inline private
References TSP.MainForm.citiesCountBox, TSP.MainForm.EnableCallback(), TSP.MainForm.EnableControls(), TSP.MainForm.generateMapButton, TSP.MainForm.iterationsBox, TSP.MainForm.populationSizeBox, TSP.MainForm.selectionBox, TSP.MainForm.startButton, and TSP.MainForm.stopButton.
GenerateMap() [3/4]
void TSP.MainForm.GenerateMap () inline private
References TSP.MainForm.citiesCount, TSP.MainForm.map, TSP.MainForm.mapControl, TSP.MainForm.rand, and AForge.Controls.Chart.UpdateDataSeries().
generateMapButton_Click() [3/4]
void TSP.MainForm.generateMapButton_Click (object sender, System.EventArgs e) inline private
References TSP.MainForm.citiesCount, TSP.MainForm.citiesCountBox, and TSP.MainForm.GenerateMap().
startButton_Click() [3/4]
void TSP.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References TSP.MainForm.EnableControls(), TSP.MainForm.greedyCrossover, TSP.MainForm.greedyCrossoverBox, TSP.MainForm.iterations, TSP.MainForm.iterationsBox, TSP.MainForm.needToStop, TSP.MainForm.populationSize, TSP.MainForm.populationSizeBox, TSP.MainForm.SearchSolution(), TSP.MainForm.selectionBox, TSP.MainForm.selectionMethod, TSP.MainForm.UpdateSettings(), and TSP.MainForm.workerThread.
stopButton_Click() [3/4]
void TSP.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References TSP.MainForm.needToStop, and TSP.MainForm.workerThread.
SearchSolution() [3/4]
void TSP.MainForm.SearchSolution () inline private
References AForge.Genetic.Population.BestChromosome, TSP.MainForm.citiesCount, TSP.MainForm.currentIterationBox, TSP.MainForm.EnableControls(), TSP.MainForm.greedyCrossover, TSP.MainForm.iterations, TSP.MainForm.map, TSP.MainForm.mapControl, TSP.MainForm.needToStop, TSP.TSPFitnessFunction.PathLength(), TSP.MainForm.pathLengthBox, TSP.MainForm.populationSize, AForge.Genetic.Population.RunEpoch(), TSP.MainForm.selectionMethod, TSP.MainForm.SetText(), and AForge.Controls.Chart.UpdateDataSeries().
Dispose() [4/4]
override void TSP.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References TSP.MainForm.components.
InitializeComponent() [4/4]
void TSP.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [4/4]
static void TSP.MainForm.Main () inline static private
The main entry point for the application.
References TSP.MainForm.MainForm().
SetTextCallback() [2/2]
delegate void TSP.MainForm.SetTextCallback (System.Windows.Forms.Control control, string text) private
SetText() [2/2]
void TSP.MainForm.SetText (System.Windows.Forms.Control control, string text) inline private
References TSP.MainForm.SetText(), and TSP.MainForm.SetTextCallback().
MainForm_Closing() [4/4]
void TSP.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References TSP.MainForm.needToStop, and TSP.MainForm.workerThread.
UpdateSettings() [4/4]
void TSP.MainForm.UpdateSettings () inline private
References TSP.MainForm.citiesCount, TSP.MainForm.citiesCountBox, TSP.MainForm.iterations, TSP.MainForm.iterationsBox, TSP.MainForm.learningRadius, TSP.MainForm.learningRate, TSP.MainForm.neurons, TSP.MainForm.neuronsBox, TSP.MainForm.radiusBox, and TSP.MainForm.rateBox.
GenerateMap() [4/4]
void TSP.MainForm.GenerateMap () inline private
References TSP.MainForm.chart, TSP.MainForm.citiesCount, TSP.MainForm.map, TSP.MainForm.rand, and AForge.Controls.Chart.UpdateDataSeries().
generateMapButton_Click() [4/4]
void TSP.MainForm.generateMapButton_Click (object sender, System.EventArgs e) inline private
References TSP.MainForm.citiesCount, TSP.MainForm.citiesCountBox, and TSP.MainForm.GenerateMap().
EnableCallback() [2/2]
delegate void TSP.MainForm.EnableCallback (bool enable) private
EnableControls() [4/4]
void TSP.MainForm.EnableControls (bool enable) inline private
References TSP.MainForm.EnableCallback(), TSP.MainForm.EnableControls(), TSP.MainForm.generateMapButton, TSP.MainForm.iterationsBox, TSP.MainForm.neuronsBox, TSP.MainForm.radiusBox, TSP.MainForm.rateBox, TSP.MainForm.startButton, and TSP.MainForm.stopButton.
startButton_Click() [4/4]
void TSP.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References TSP.MainForm.EnableControls(), TSP.MainForm.iterations, TSP.MainForm.iterationsBox, TSP.MainForm.learningRadius, TSP.MainForm.learningRate, TSP.MainForm.needToStop, TSP.MainForm.neurons, TSP.MainForm.neuronsBox, TSP.MainForm.radiusBox, TSP.MainForm.rateBox, TSP.MainForm.SearchSolution(), TSP.MainForm.UpdateSettings(), and TSP.MainForm.workerThread.
stopButton_Click() [4/4]
void TSP.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References TSP.MainForm.needToStop, and TSP.MainForm.workerThread.
SearchSolution() [4/4]
void TSP.MainForm.SearchSolution () inline private
References TSP.MainForm.chart, TSP.MainForm.citiesCount, TSP.MainForm.currentIterationBox, TSP.MainForm.EnableControls(), TSP.MainForm.iterations, AForge.Neuro.Network.Layers, TSP.MainForm.learningRadius, AForge.Neuro.Learning.ElasticNetworkLearning.LearningRadius, AForge.Neuro.Learning.ElasticNetworkLearning.LearningRate, TSP.MainForm.learningRate, TSP.MainForm.map, TSP.MainForm.needToStop, TSP.MainForm.neurons, AForge.Neuro.Layer.Neurons, TSP.MainForm.rand, AForge.Neuro.Neuron.RandRange, AForge.Neuro.Learning.ElasticNetworkLearning.Run(), TSP.MainForm.SetText(), AForge.Controls.Chart.UpdateDataSeries(), and AForge.Neuro.Neuron.Weights.
Member Data Documentation
groupBox1
System Windows Forms GroupBox TSP.MainForm.groupBox1 private
generateMapButton
System Windows Forms Button TSP.MainForm.generateMapButton private
Referenced by TSP.MainForm.EnableControls().
citiesCountBox
System Windows Forms TextBox TSP.MainForm.citiesCountBox private
Referenced by TSP.MainForm.EnableControls(), TSP.MainForm.generateMapButton_Click(), and TSP.MainForm.UpdateSettings().
label1
System Windows Forms Label TSP.MainForm.label1 private
groupBox2
System Windows Forms GroupBox TSP.MainForm.groupBox2 private
label2
System Windows Forms Label TSP.MainForm.label2 private
neuronsBox
System Windows Forms TextBox TSP.MainForm.neuronsBox private
Referenced by TSP.MainForm.EnableControls(), TSP.MainForm.startButton_Click(), and TSP.MainForm.UpdateSettings().
label3
System Windows Forms Label TSP.MainForm.label3 private
currentIterationBox
System Windows Forms TextBox TSP.MainForm.currentIterationBox private
Referenced by TSP.MainForm.SearchSolution().
label8
System Windows Forms Label TSP.MainForm.label8 private
label7
System Windows Forms Label TSP.MainForm.label7 private
rateBox
System Windows Forms TextBox TSP.MainForm.rateBox private
Referenced by TSP.MainForm.EnableControls(), TSP.MainForm.startButton_Click(), and TSP.MainForm.UpdateSettings().
label5
System Windows Forms Label TSP.MainForm.label5 private
iterationsBox
System Windows Forms TextBox TSP.MainForm.iterationsBox private
Referenced by TSP.MainForm.EnableControls(), TSP.MainForm.startButton_Click(), and TSP.MainForm.UpdateSettings().
label6
System Windows Forms Label TSP.MainForm.label6 private
stopButton
System Windows Forms Button TSP.MainForm.stopButton private
Referenced by TSP.MainForm.EnableControls().
startButton
System Windows Forms Button TSP.MainForm.startButton private
Referenced by TSP.MainForm.EnableControls().
chart
AForge Controls Chart TSP.MainForm.chart private
Referenced by TSP.MainForm.GenerateMap(), TSP.MainForm.MainForm(), and TSP.MainForm.SearchSolution().
label4
System Windows Forms Label TSP.MainForm.label4 private
radiusBox
System Windows Forms TextBox TSP.MainForm.radiusBox private
Referenced by TSP.MainForm.EnableControls(), TSP.MainForm.startButton_Click(), and TSP.MainForm.UpdateSettings().
components
System ComponentModel Container TSP.MainForm.components = null private
Required designer variable.
Referenced by TSP.MainForm.Dispose().
citiesCount
int TSP.MainForm.citiesCount = 10 private
Referenced by TSP.MainForm.GenerateMap(), TSP.MainForm.generateMapButton_Click(), TSP.MainForm.SearchSolution(), and TSP.MainForm.UpdateSettings().
neurons
int TSP.MainForm.neurons = 20 private
Referenced by TSP.MainForm.SearchSolution(), TSP.MainForm.startButton_Click(), and TSP.MainForm.UpdateSettings().
iterations
int TSP.MainForm.iterations = 500 private
Referenced by TSP.MainForm.SearchSolution(), TSP.MainForm.startButton_Click(), and TSP.MainForm.UpdateSettings().
learningRate
double TSP.MainForm.learningRate = 0.5 private
Referenced by TSP.MainForm.SearchSolution(), TSP.MainForm.startButton_Click(), and TSP.MainForm.UpdateSettings().
learningRadius
double TSP.MainForm.learningRadius = 0.5 private
Referenced by TSP.MainForm.SearchSolution(), TSP.MainForm.startButton_Click(), and TSP.MainForm.UpdateSettings().
map
double [,] TSP.MainForm.map = null private
Referenced by TSP.MainForm.GenerateMap(), and TSP.MainForm.SearchSolution().
rand
Random TSP.MainForm.rand = new Random() private
Referenced by TSP.MainForm.GenerateMap(), and TSP.MainForm.SearchSolution().
workerThread
Thread TSP.MainForm.workerThread = null private
Referenced by TSP.MainForm.MainForm_Closing(), TSP.MainForm.startButton_Click(), and TSP.MainForm.stopButton_Click().
needToStop [1/2]
volatile bool TSP.MainForm.needToStop = false private
Referenced by TSP.MainForm.MainForm_Closing(), TSP.MainForm.SearchSolution(), TSP.MainForm.startButton_Click(), and TSP.MainForm.stopButton_Click().
mapControl
AForge.Controls.Chart TSP.MainForm.mapControl private
Referenced by TSP.MainForm.GenerateMap(), TSP.MainForm.MainForm(), and TSP.MainForm.SearchSolution().
populationSizeBox
System.Windows.Forms.TextBox TSP.MainForm.populationSizeBox private
Referenced by TSP.MainForm.EnableControls(), TSP.MainForm.startButton_Click(), and TSP.MainForm.UpdateSettings().
selectionBox
System.Windows.Forms.ComboBox TSP.MainForm.selectionBox private
Referenced by TSP.MainForm.EnableControls(), TSP.MainForm.MainForm(), and TSP.MainForm.startButton_Click().
groupBox3
System.Windows.Forms.GroupBox TSP.MainForm.groupBox3 private
pathLengthBox
System.Windows.Forms.TextBox TSP.MainForm.pathLengthBox private
Referenced by TSP.MainForm.SearchSolution().
greedyCrossoverBox
System.Windows.Forms.CheckBox TSP.MainForm.greedyCrossoverBox private
Referenced by TSP.MainForm.MainForm(), and TSP.MainForm.startButton_Click().
populationSize
int TSP.MainForm.populationSize = 40 private
Referenced by TSP.MainForm.SearchSolution(), TSP.MainForm.startButton_Click(), and TSP.MainForm.UpdateSettings().
selectionMethod
int TSP.MainForm.selectionMethod = 0 private
Referenced by TSP.MainForm.MainForm(), TSP.MainForm.SearchSolution(), and TSP.MainForm.startButton_Click().
greedyCrossover
bool TSP.MainForm.greedyCrossover = true private
Referenced by TSP.MainForm.MainForm(), TSP.MainForm.SearchSolution(), and TSP.MainForm.startButton_Click().
needToStop [2/2]
volatile bool TSP.MainForm.needToStop = false private
The documentation for this class was generated from the following file:
shelldev/lib/external/neuralnetworks/neuro_src/Samples/Neuro/SOM/TSP/Backup/MainForm.cs