Doc: IGLib EXTENDED: IG.Num.Geometry Class Reference
IG.Num.Geometry Class Reference
Analytical Geometry in 3D.
Static Public Member Functions
static double distpt3d (vec3 p1, vec3 p2)
static double directioncos3d (vec3 s1, vec3 s2)
static double ortprojptline3d (vec3 pt, vec3 r, vec3 s, vec3 proj)
static double distptline3d (vec3 pt, vec3 r, vec3 s)
static double nearestptlines3d (vec3 r1, vec3 s1, vec3 r2, vec3 s2, ref vec3 pt1, ref vec3 pt2)
static double nearestptlinescoef3d (vec3 r1, vec3 s1, vec3 r2, vec3 s2, ref vec3 pt1, ref double c1, ref vec3 pt2, ref double c2)
static void ortprojptplane3d (vec3 pt, vec3 r, vec3 n, ref vec3 proj)
static void ortprojlineplane3d (vec3 r1, vec3 s1, vec3 r2, vec3 n2, ref vec3 rpr, ref vec3 spr)
static double signdistptplane3d (vec3 pt, vec3 r, vec3 n)
static double distptplane3d (vec3 pt, vec3 r, vec3 n)
static double intsectlineplane3d (vec3 r1, vec3 s1, vec3 r2, vec3 n2, ref vec3 sect)
static double intsectplanes3d (vec3 r1, vec3 n1, vec3 r2, vec3 n2, ref vec3 r, ref vec3 s)
Static Private Member Functions
static double m_sqr (double x)
Square of double argument.
static double sqrt (double x)
Square root of double argument.
static double vecnorm3d (vec3 v)
Vector norm.
static double fabs (double x)
static void zerovec3d (ref vec3 v)
Sets all components of the vector to 0.
static double scalprod3d (vec3 v1, vec3 v2)
Scalar product of two 3D vectors.
static void vecprod3d (vec3 v1, vec3 v2, ref vec3 res)
Vector product of two 3D vectors.
static void vecdif3d (vec3 v1, vec3 v2, ref vec3 v3)
Difference of two 3D vectors.
static void vecsum3d (vec3 v1, vec3 v2, ref vec3 v3)
Sum of two 3D vectors.
static void multscalvec3d (vec3 v1, double s, ref vec3 prod)
Product of vector with a scalar.
static void zeromat3d (ref mat3 a)
Sets all components of the matrix to 0.
static void solve2d (mat3 A, vec3 b, out vec3 x)
V x zapise resitev sistema dveh enacb z dvema neznankama, kjer so
Detailed Description
Analytical Geometry in 3D.
$A Igor Jul08;
This class was developed by transcribing the C library IOptLib's geometry related functions and rearranging and packing them into a C# class.
Member Function Documentation
m_sqr()
static double IG.Num.Geometry.m_sqr (double x) inline static private
Square of double argument.
Referenced by IG.Num.Geometry.distpt3d().
sqrt()
static double IG.Num.Geometry.sqrt (double x) inline static private
Square root of double argument.
Referenced by IG.Num.Geometry.distpt3d().
vecnorm3d()
static double IG.Num.Geometry.vecnorm3d (vec3 v) inline static private
Vector norm.
References IG.Num.vec3.Norm.
Referenced by IG.Num.Geometry.distptline3d(), and IG.Num.Geometry.signdistptplane3d().
fabs()
static double IG.Num.Geometry.fabs (double x) inline static private
Referenced by IG.Num.Geometry.distptplane3d(), IG.Num.Geometry.intsectplanes3d(), IG.Num.Geometry.nearestptlines3d(), and IG.Num.Geometry.nearestptlinescoef3d().
zerovec3d()
static void IG.Num.Geometry.zerovec3d (ref vec3 v) inline static private
Sets all components of the vector to 0.
Referenced by IG.Num.Geometry.nearestptlines3d(), and IG.Num.Geometry.nearestptlinescoef3d().
scalprod3d()
static double IG.Num.Geometry.scalprod3d (vec3 v1, vec3 v2) inline static private
Scalar product of two 3D vectors.
References IG.Num.vec3.ScalarProduct().
Referenced by IG.Num.Geometry.directioncos3d(), IG.Num.Geometry.intsectlineplane3d(), IG.Num.Geometry.nearestptlines3d(), IG.Num.Geometry.nearestptlinescoef3d(), IG.Num.Geometry.ortprojptline3d(), IG.Num.Geometry.ortprojptplane3d(), and IG.Num.Geometry.signdistptplane3d().
vecprod3d()
static void IG.Num.Geometry.vecprod3d (vec3 v1, vec3 v2, ref vec3 res) inline static private
Vector product of two 3D vectors.
References IG.Num.vec3.VectorProduct().
Referenced by IG.Num.Geometry.distptline3d(), and IG.Num.Geometry.intsectplanes3d().
vecdif3d()
static void IG.Num.Geometry.vecdif3d (vec3 v1, vec3 v2, ref vec3 v3) inline static private
Difference of two 3D vectors.
References IG.Num.vec3.Subtract().
Referenced by IG.Num.Geometry.distptline3d(), IG.Num.Geometry.ortprojptline3d(), IG.Num.Geometry.ortprojptplane3d(), and IG.Num.Geometry.signdistptplane3d().
vecsum3d()
static void IG.Num.Geometry.vecsum3d (vec3 v1, vec3 v2, ref vec3 v3) inline static private
Sum of two 3D vectors.
References IG.Num.vec3.Add().
Referenced by IG.Num.Geometry.intsectlineplane3d(), IG.Num.Geometry.nearestptlines3d(), IG.Num.Geometry.nearestptlinescoef3d(), IG.Num.Geometry.ortprojptline3d(), and IG.Num.Geometry.ortprojptplane3d().
multscalvec3d()
static void IG.Num.Geometry.multscalvec3d (vec3 v1, double s, ref vec3 prod) inline static private
Product of vector with a scalar.
References IG.Num.vec3.Multiply(), and IG.Num.s.
Referenced by IG.Num.Geometry.intsectlineplane3d(), IG.Num.Geometry.nearestptlines3d(), IG.Num.Geometry.nearestptlinescoef3d(), IG.Num.Geometry.ortprojptline3d(), and IG.Num.Geometry.ortprojptplane3d().
zeromat3d()
static void IG.Num.Geometry.zeromat3d (ref mat3 a) inline static private
Sets all components of the matrix to 0.
Referenced by IG.Num.Geometry.nearestptlines3d(), and IG.Num.Geometry.nearestptlinescoef3d().
solve2d()
static void IG.Num.Geometry.solve2d (mat3 A, vec3 b, out vec3 x) inline static private
V x zapise resitev sistema dveh enacb z dvema neznankama, kjer so
Referenced by IG.Num.Geometry.nearestptlines3d(), and IG.Num.Geometry.nearestptlinescoef3d().
distpt3d()
static double IG.Num.Geometry.distpt3d (vec3 p1, vec3 p2) inline static
References IG.Num.Geometry.m_sqr(), IG.Num.Geometry.sqrt(), IG.Num.vec3.x, IG.Num.vec3.y, and IG.Num.vec3.z.
Referenced by IG.Num.Geometry.nearestptlines3d(), and IG.Num.Geometry.nearestptlinescoef3d().
directioncos3d()
static double IG.Num.Geometry.directioncos3d (vec3 s1, vec3 s2) inline static
References IG.Num.Geometry.scalprod3d().
Referenced by IG.Num.Geometry.intsectplanes3d(), IG.Num.Geometry.nearestptlines3d(), and IG.Num.Geometry.nearestptlinescoef3d().
ortprojptline3d()
static double IG.Num.Geometry.ortprojptline3d (vec3 pt, vec3 r, vec3 s, vec3 proj) inline static
References IG.Num.Geometry.multscalvec3d(), IG.Num.s, IG.Num.Geometry.scalprod3d(), IG.Num.Geometry.vecdif3d(), and IG.Num.Geometry.vecsum3d().
Referenced by IG.Num.Geometry.nearestptlines3d(), and IG.Num.Geometry.nearestptlinescoef3d().
distptline3d()
static double IG.Num.Geometry.distptline3d (vec3 pt, vec3 r, vec3 s) inline static
References IG.Num.s, IG.Num.Geometry.vecdif3d(), IG.Num.Geometry.vecnorm3d(), and IG.Num.Geometry.vecprod3d().
Referenced by IG.Num.Geometry.nearestptlines3d(), and IG.Num.Geometry.nearestptlinescoef3d().
nearestptlines3d()
static double IG.Num.Geometry.nearestptlines3d (vec3 r1, vec3 s1, vec3 r2, vec3 s2, ref vec3 pt1, ref vec3 pt2) inline static
References IG.Num.A, IG.Num.Geometry.directioncos3d(), IG.Num.Geometry.distpt3d(), IG.Num.Geometry.distptline3d(), IG.Num.Geometry.fabs(), IG.Num.Geometry.multscalvec3d(), IG.Num.Geometry.ortprojptline3d(), IG.Num.Geometry.scalprod3d(), IG.Num.Geometry.solve2d(), IG.Num.Geometry.vecsum3d(), IG.Num.Geometry.zeromat3d(), and IG.Num.Geometry.zerovec3d().
nearestptlinescoef3d()
static double IG.Num.Geometry.nearestptlinescoef3d (vec3 r1, vec3 s1, vec3 r2, vec3 s2, ref vec3 pt1, ref double c1, ref vec3 pt2, ref double c2) inline static
References IG.Num.A, IG.Num.Geometry.directioncos3d(), IG.Num.Geometry.distpt3d(), IG.Num.Geometry.distptline3d(), IG.Num.Geometry.fabs(), IG.Num.Geometry.multscalvec3d(), IG.Num.Geometry.ortprojptline3d(), IG.Num.Geometry.scalprod3d(), IG.Num.Geometry.solve2d(), IG.Num.Geometry.vecsum3d(), IG.Num.Geometry.zeromat3d(), and IG.Num.Geometry.zerovec3d().
ortprojptplane3d()
static void IG.Num.Geometry.ortprojptplane3d (vec3 pt, vec3 r, vec3 n, ref vec3 proj) inline static
References IG.Num.Geometry.multscalvec3d(), IG.Num.Geometry.scalprod3d(), IG.Num.Geometry.vecdif3d(), and IG.Num.Geometry.vecsum3d().
Referenced by IG.Num.Geometry.ortprojlineplane3d().
ortprojlineplane3d()
static void IG.Num.Geometry.ortprojlineplane3d (vec3 r1, vec3 s1, vec3 r2, vec3 n2, ref vec3 rpr, ref vec3 spr) inline static
References IG.Num.Geometry.ortprojptplane3d().
signdistptplane3d()
static double IG.Num.Geometry.signdistptplane3d (vec3 pt, vec3 r, vec3 n) inline static
References IG.Num.Geometry.scalprod3d(), IG.Num.Geometry.vecdif3d(), and IG.Num.Geometry.vecnorm3d().
Referenced by IG.Num.Geometry.distptplane3d(), and IG.Num.Geometry.intsectlineplane3d().
distptplane3d()
static double IG.Num.Geometry.distptplane3d (vec3 pt, vec3 r, vec3 n) inline static
References IG.Num.Geometry.fabs(), and IG.Num.Geometry.signdistptplane3d().
Referenced by IG.Num.Geometry.intsectplanes3d().
intsectlineplane3d()
static double IG.Num.Geometry.intsectlineplane3d (vec3 r1, vec3 s1, vec3 r2, vec3 n2, ref vec3 sect) inline static
References IG.Num.Geometry.multscalvec3d(), IG.Num.Geometry.scalprod3d(), IG.Num.Geometry.signdistptplane3d(), and IG.Num.Geometry.vecsum3d().
Referenced by IG.Num.Geometry.intsectplanes3d().
intsectplanes3d()
static double IG.Num.Geometry.intsectplanes3d (vec3 r1, vec3 n1, vec3 r2, vec3 n2, ref vec3 r, ref vec3 s) inline static
References IG.Num.Geometry.directioncos3d(), IG.Num.Geometry.distptplane3d(), IG.Num.Geometry.fabs(), IG.Num.Geometry.intsectlineplane3d(), IG.Num.s, and IG.Num.Geometry.vecprod3d().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/0develop/geometry/Geometry3D.cs