Doc: IGLib EXTENDED: IG.Neural.Applications.NeuralParametricDemoAboutWindowOld Class Reference
IG.Neural.Applications.NeuralParametricDemoAboutWindowOld Class Reference
Window that displays information about Demo application for performing parametric studies on ANN models.
Public Member Functions
NeuralParametricDemoAboutWindowOld ()
void ShowHelp ()
void ShowWebPage ()
NeuralParametricDemoAboutWindowOld ()
void ShowHelp ()
void ShowWebPage ()
NeuralParametricDemoAboutWindowOld ()
void ShowHelp ()
void ShowWebPage ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
Applications.NeuralParametricDemoAboutOld neuralParametricDemoAbout1
Detailed Description
Window that displays information about Demo application for performing parametric studies on ANN models.
$A Igor Apr13;
Constructor & Destructor Documentation
NeuralParametricDemoAboutWindowOld() [1/3]
IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.NeuralParametricDemoAboutWindowOld () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.InitializeComponent().
NeuralParametricDemoAboutWindowOld() [2/3]
IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.NeuralParametricDemoAboutWindowOld () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.InitializeComponent().
NeuralParametricDemoAboutWindowOld() [3/3]
IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.NeuralParametricDemoAboutWindowOld () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.InitializeComponent().
Member Function Documentation
ShowHelp() [1/3]
void IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.ShowHelp () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.neuralParametricDemoAbout1, and IG.Neural.Applications.NeuralParametricDemoAboutOld.ShowHelp().
Referenced by IG.Neural.Forms.Old.NeuralParametricDemoOldCopy.NeuralParametricDemo_HelpEventHandlers(), IG.Neural.Forms.Old.NeuralParametricDemoOld.NeuralParametricDemo_HelpEventHandlers(), IG.Neural.Forms.Old.NeuralParametricDemoOldCopy.showManualToolStripMenuItem_Click(), and IG.Neural.Forms.Old.NeuralParametricDemoOld.showManualToolStripMenuItem_Click().
ShowWebPage() [1/3]
void IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.ShowWebPage () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.neuralParametricDemoAbout1, and IG.Neural.Applications.NeuralParametricDemoAboutOld.ShowWebPage().
Referenced by IG.Neural.Forms.Old.NeuralParametricDemoOldCopy.aboutStoreSW_Click(), and IG.Neural.Forms.Old.NeuralParametricDemoOld.aboutStoreSW_Click().
Dispose() [1/3]
override void IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.components.
InitializeComponent() [1/3]
void IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.neuralParametricDemoAbout1.
Referenced by IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.NeuralParametricDemoAboutWindowOld().
ShowHelp() [2/3]
void IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.ShowHelp () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.neuralParametricDemoAbout1, and IG.Neural.Applications.NeuralParametricDemoAboutOld.ShowHelp().
ShowWebPage() [2/3]
void IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.ShowWebPage () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.neuralParametricDemoAbout1, and IG.Neural.Applications.NeuralParametricDemoAboutOld.ShowWebPage().
Dispose() [2/3]
override void IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.components.
InitializeComponent() [2/3]
void IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.neuralParametricDemoAbout1.
ShowHelp() [3/3]
void IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.ShowHelp () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.neuralParametricDemoAbout1, and IG.Neural.Applications.NeuralParametricDemoAboutOld.ShowHelp().
ShowWebPage() [3/3]
void IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.ShowWebPage () inline
References IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.neuralParametricDemoAbout1, and IG.Neural.Applications.NeuralParametricDemoAboutOld.ShowWebPage().
Dispose() [3/3]
override void IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.components.
InitializeComponent() [3/3]
void IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.neuralParametricDemoAbout1.
Member Data Documentation
components
System ComponentModel IContainer IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.components = null private
Required designer variable.
Referenced by IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.Dispose().
neuralParametricDemoAbout1
Applications NeuralParametricDemoAboutOld IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.neuralParametricDemoAbout1 private
Referenced by IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.InitializeComponent(), IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.ShowHelp(), and IG.Neural.Applications.NeuralParametricDemoAboutWindowOld.ShowWebPage().
The documentation for this class was generated from the following files:
shelldev/lib/extended/LibNeuralExtForms/FormsExperimental/ResponseForms/Old/NeuralParametricDemoAboutWindowOld.cs
shelldev/lib/extended/LibNeuralExtForms/FormsExperimental/ResponseForms/Old/NeuralParametricDemoAboutWindowOld.Designer.cs