Doc: IGLib EXTENDED: AForge.Math.FourierTransform Class Reference
AForge.Math.FourierTransform Class Reference
Fourier transformation.
Public Types
enum Direction { Direction.Forward = 1, Direction.Backward = -1 }
Fourier transformation direction.
Static Public Member Functions
static void DFT (Complex[] data, Direction direction)
One dimensional Discrete Fourier Transform.
static void DFT2 (Complex[,] data, Direction direction)
Two dimensional Discrete Fourier Transform.
static void FFT (Complex[] data, Direction direction)
One dimensional Fast Fourier Transform.
static void FFT2 (Complex[,] data, Direction direction)
Two dimensional Fast Fourier Transform.
Static Private Member Functions
static int[] GetReversedBits (int numberOfBits)
static Complex[] GetComplexRotation (int numberOfBits, Direction direction)
static void ReorderData (Complex[] data)
Static Private Attributes
const int minLength = 2
const int maxLength = 16384
const int minBits = 1
const int maxBits = 14
static int[][] reversedBits = new int[maxBits][]
static Complex[,][] complexRotation = new Complex[maxBits, 2][]
Detailed Description
Fourier transformation.
The class implements one dimensional and two dimensional Discrete and Fast Fourier Transformation.
Member Enumeration Documentation
Direction
enum AForge.Math.FourierTransform.Direction strong
Fourier transformation direction.
Enumerator
Forward
Forward direction of Fourier transformation.
Backward
Backward direction of Fourier transformation.
Member Function Documentation
DFT()
static void AForge.Math.FourierTransform.DFT (Complex[] data, Direction direction) inline static
One dimensional Discrete Fourier Transform.
Parameters
data Data to transform.
direction Transformation direction.
References AForge.Math.Complex.Im, AForge.Math.Complex.Re, and AForge.Math.Complex.Zero.
DFT2()
static void AForge.Math.FourierTransform.DFT2 (Complex data[,], Direction direction) inline static
Two dimensional Discrete Fourier Transform.
Parameters
data Data to transform.
direction Transformation direction.
References AForge.Math.Complex.Im, AForge.Math.Complex.Re, and AForge.Math.Complex.Zero.
FFT()
static void AForge.Math.FourierTransform.FFT (Complex[] data, Direction direction) inline static
One dimensional Fast Fourier Transform.
Parameters
data Data to transform.
direction Transformation direction.
<note>The method accepts data array of 2n size only, where n may vary in the [1, 14] range.</note>
Exceptions
ArgumentException Incorrect data length.
References AForge.Math.FourierTransform.GetComplexRotation(), AForge.Math.Complex.Im, AForge.Math.Tools.Log2(), AForge.Math.Complex.Re, and AForge.Math.FourierTransform.ReorderData().
Referenced by AForge.Math.FourierTransform.FFT2().
FFT2()
static void AForge.Math.FourierTransform.FFT2 (Complex data[,], Direction direction) inline static
Two dimensional Fast Fourier Transform.
Parameters
data Data to transform.
direction Transformation direction.
<note>The method accepts data array of 2n size only in each dimension, where n may vary in the [1, 14] range. For example, 16x16 array is valid, but 15x15 is not.</note>
Exceptions
ArgumentException Incorrect data length.
References AForge.Math.FourierTransform.FFT(), AForge.Math.Tools.IsPowerOf2(), AForge.Math.FourierTransform.maxLength, and AForge.Math.FourierTransform.minLength.
Referenced by AForge.Imaging.ComplexImage.BackwardFourierTransform(), and AForge.Imaging.ComplexImage.ForwardFourierTransform().
GetReversedBits()
static int [] AForge.Math.FourierTransform.GetReversedBits (int numberOfBits) inline static private
References AForge.Math.FourierTransform.maxBits, AForge.Math.FourierTransform.minBits, AForge.Math.Tools.Pow2(), and AForge.Math.FourierTransform.reversedBits.
Referenced by AForge.Math.FourierTransform.ReorderData().
GetComplexRotation()
static Complex [] AForge.Math.FourierTransform.GetComplexRotation (int numberOfBits, Direction direction) inline static private
References AForge.Math.FourierTransform.complexRotation.
Referenced by AForge.Math.FourierTransform.FFT().
ReorderData()
static void AForge.Math.FourierTransform.ReorderData (Complex[] data) inline static private
References AForge.Math.FourierTransform.GetReversedBits(), AForge.Math.Tools.IsPowerOf2(), AForge.Math.Tools.Log2(), AForge.Math.FourierTransform.maxLength, and AForge.Math.FourierTransform.minLength.
Referenced by AForge.Math.FourierTransform.FFT().
Member Data Documentation
minLength
const int AForge.Math.FourierTransform.minLength = 2 static private
Referenced by AForge.Math.FourierTransform.FFT2(), and AForge.Math.FourierTransform.ReorderData().
maxLength
const int AForge.Math.FourierTransform.maxLength = 16384 static private
Referenced by AForge.Math.FourierTransform.FFT2(), and AForge.Math.FourierTransform.ReorderData().
minBits
const int AForge.Math.FourierTransform.minBits = 1 static private
Referenced by AForge.Math.FourierTransform.GetReversedBits().
maxBits
const int AForge.Math.FourierTransform.maxBits = 14 static private
Referenced by AForge.Math.FourierTransform.GetReversedBits().
reversedBits
int [][] AForge.Math.FourierTransform.reversedBits = new int[maxBits][] static private
Referenced by AForge.Math.FourierTransform.GetReversedBits().
complexRotation
Complex [,][] AForge.Math.FourierTransform.complexRotation = new Complex[maxBits, 2][] static private
Referenced by AForge.Math.FourierTransform.GetComplexRotation().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Math/FourierTransform.cs