Doc: IGLib EXTENDED: IG.Neural.Applications.NeuralDemo Class Reference
IG.Neural.Applications.NeuralDemo Class Reference
Public Member Functions
NeuralDemo ()
NeuralDemo ()
NeuralDemo ()
Static Public Member Functions
static void Run ()
static void Run ()
static void Run ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
NeuralDemoAbout AboutControl [get]
Returns the control that contains the "About" page.
Private Member Functions
void tabControl1_KeyUp (object sender, KeyEventArgs e)
void HelpEventHandlers (object sender, KeyEventArgs e)
void neuralControl2D1_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void tabControl1_KeyUp (object sender, KeyEventArgs e)
void HelpEventHandlers (object sender, KeyEventArgs e)
void neuralControl2D1_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void tabControl1_KeyUp (object sender, KeyEventArgs e)
void HelpEventHandlers (object sender, KeyEventArgs e)
void neuralControl2D1_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.TabControl tabControl1
System.Windows.Forms.TabPage tabPage1D
System.Windows.Forms.TabPage tabPage2D
System.Windows.Forms.TabPage tabPageAbout
Forms.NeuralDemo1D neuralDemo1D1
Forms.NeuralControl2D neuralControl2D1
NeuralDemoAbout neuralDemoAbout1
Constructor & Destructor Documentation
NeuralDemo() [1/3]
IG.Neural.Applications.NeuralDemo.NeuralDemo () inline
References IG.Gr3d.VtkPlotter.DefaultIsAllowedAnyVtkForm, and IG.Neural.Applications.NeuralDemo.InitializeComponent().
NeuralDemo() [2/3]
IG.Neural.Applications.NeuralDemo.NeuralDemo () inline
References IG.Gr3d.VtkPlotter.DefaultIsAllowedAnyVtkForm, and IG.Neural.Applications.NeuralDemo.InitializeComponent().
NeuralDemo() [3/3]
IG.Neural.Applications.NeuralDemo.NeuralDemo () inline
References IG.Gr3d.VtkPlotter.DefaultIsAllowedAnyVtkForm, and IG.Neural.Applications.NeuralDemo.InitializeComponent().
Member Function Documentation
Run() [1/3]
static void IG.Neural.Applications.NeuralDemo.Run () inline static
Referenced by IG.Neural.Applications.ProgramNeurApp.Main().
tabControl1_KeyUp() [1/3]
void IG.Neural.Applications.NeuralDemo.tabControl1_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Neural.Applications.NeuralDemo.HelpEventHandlers().
Referenced by IG.Neural.Applications.NeuralDemo.InitializeComponent().
HelpEventHandlers() [1/3]
void IG.Neural.Applications.NeuralDemo.HelpEventHandlers (object sender, KeyEventArgs e) inline private
References IG.Neural.Applications.NeuralDemo.AboutControl, IG.Neural.Applications.NeuralDemoAbout.HelpShow(), IG.Neural.Applications.NeuralDemo.tabControl1, and IG.Neural.Applications.NeuralDemo.tabPageAbout.
Referenced by IG.Neural.Applications.NeuralDemo.tabControl1_KeyUp().
neuralControl2D1_Load() [1/3]
void IG.Neural.Applications.NeuralDemo.neuralControl2D1_Load (object sender, EventArgs e) inline private
Referenced by IG.Neural.Applications.NeuralDemo.InitializeComponent().
Dispose() [1/3]
override void IG.Neural.Applications.NeuralDemo.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralDemo.components.
InitializeComponent() [1/3]
void IG.Neural.Applications.NeuralDemo.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralDemo.components, IG.Neural.Applications.NeuralDemo.neuralControl2D1, IG.Neural.Applications.NeuralDemo.neuralControl2D1_Load(), IG.Neural.Applications.NeuralDemo.neuralDemo1D1, IG.Neural.Applications.NeuralDemo.neuralDemoAbout1, IG.Neural.Applications.NeuralDemo.tabControl1, IG.Neural.Applications.NeuralDemo.tabControl1_KeyUp(), IG.Neural.Applications.NeuralDemo.tabPage1D, IG.Neural.Applications.NeuralDemo.tabPage2D, and IG.Neural.Applications.NeuralDemo.tabPageAbout.
Referenced by IG.Neural.Applications.NeuralDemo.NeuralDemo().
Run() [2/3]
static void IG.Neural.Applications.NeuralDemo.Run () inline static
tabControl1_KeyUp() [2/3]
void IG.Neural.Applications.NeuralDemo.tabControl1_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Neural.Applications.NeuralDemo.HelpEventHandlers().
HelpEventHandlers() [2/3]
void IG.Neural.Applications.NeuralDemo.HelpEventHandlers (object sender, KeyEventArgs e) inline private
References IG.Neural.Applications.NeuralDemo.AboutControl, IG.Neural.Applications.NeuralDemoAbout.ShowHelp(), IG.Neural.Applications.NeuralDemo.tabControl1, and IG.Neural.Applications.NeuralDemo.tabPageAbout.
neuralControl2D1_Load() [2/3]
void IG.Neural.Applications.NeuralDemo.neuralControl2D1_Load (object sender, EventArgs e) inline private
Dispose() [2/3]
override void IG.Neural.Applications.NeuralDemo.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralDemo.components.
InitializeComponent() [2/3]
void IG.Neural.Applications.NeuralDemo.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralDemo.neuralControl2D1, IG.Neural.Applications.NeuralDemo.neuralControl2D1_Load(), IG.Neural.Applications.NeuralDemo.neuralDemo1D1, IG.Neural.Applications.NeuralDemo.neuralDemoAbout1, IG.Neural.Applications.NeuralDemo.tabControl1, IG.Neural.Applications.NeuralDemo.tabControl1_KeyUp(), IG.Neural.Applications.NeuralDemo.tabPage1D, IG.Neural.Applications.NeuralDemo.tabPage2D, and IG.Neural.Applications.NeuralDemo.tabPageAbout.
Run() [3/3]
static void IG.Neural.Applications.NeuralDemo.Run () inline static
tabControl1_KeyUp() [3/3]
void IG.Neural.Applications.NeuralDemo.tabControl1_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Neural.Applications.NeuralDemo.HelpEventHandlers().
HelpEventHandlers() [3/3]
void IG.Neural.Applications.NeuralDemo.HelpEventHandlers (object sender, KeyEventArgs e) inline private
References IG.Neural.Applications.NeuralDemo.AboutControl, IG.Neural.Applications.NeuralDemoAbout.ShowHelp(), IG.Neural.Applications.NeuralDemo.tabControl1, and IG.Neural.Applications.NeuralDemo.tabPageAbout.
neuralControl2D1_Load() [3/3]
void IG.Neural.Applications.NeuralDemo.neuralControl2D1_Load (object sender, EventArgs e) inline private
Dispose() [3/3]
override void IG.Neural.Applications.NeuralDemo.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.NeuralDemo.components.
InitializeComponent() [3/3]
void IG.Neural.Applications.NeuralDemo.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.NeuralDemo.neuralControl2D1, IG.Neural.Applications.NeuralDemo.neuralControl2D1_Load(), IG.Neural.Applications.NeuralDemo.neuralDemo1D1, IG.Neural.Applications.NeuralDemo.neuralDemoAbout1, IG.Neural.Applications.NeuralDemo.tabControl1, IG.Neural.Applications.NeuralDemo.tabControl1_KeyUp(), IG.Neural.Applications.NeuralDemo.tabPage1D, IG.Neural.Applications.NeuralDemo.tabPage2D, and IG.Neural.Applications.NeuralDemo.tabPageAbout.
Member Data Documentation
components
System ComponentModel IContainer IG.Neural.Applications.NeuralDemo.components = null private
Required designer variable.
Referenced by IG.Neural.Applications.NeuralDemo.Dispose(), and IG.Neural.Applications.NeuralDemo.InitializeComponent().
tabControl1
System Windows Forms TabControl IG.Neural.Applications.NeuralDemo.tabControl1 private
Referenced by IG.Neural.Applications.NeuralDemo.HelpEventHandlers(), and IG.Neural.Applications.NeuralDemo.InitializeComponent().
tabPage1D
System Windows Forms TabPage IG.Neural.Applications.NeuralDemo.tabPage1D private
Referenced by IG.Neural.Applications.NeuralDemo.InitializeComponent().
tabPage2D
System Windows Forms TabPage IG.Neural.Applications.NeuralDemo.tabPage2D private
Referenced by IG.Neural.Applications.NeuralDemo.InitializeComponent().
tabPageAbout
System Windows Forms TabPage IG.Neural.Applications.NeuralDemo.tabPageAbout private
Referenced by IG.Neural.Applications.NeuralDemo.HelpEventHandlers(), and IG.Neural.Applications.NeuralDemo.InitializeComponent().
neuralDemo1D1
Forms NeuralDemo1D IG.Neural.Applications.NeuralDemo.neuralDemo1D1 private
Referenced by IG.Neural.Applications.NeuralDemo.InitializeComponent().
neuralControl2D1
Forms NeuralControl2D IG.Neural.Applications.NeuralDemo.neuralControl2D1 private
Referenced by IG.Neural.Applications.NeuralDemo.InitializeComponent().
neuralDemoAbout1
NeuralDemoAbout IG.Neural.Applications.NeuralDemo.neuralDemoAbout1 private
Referenced by IG.Neural.Applications.NeuralDemo.InitializeComponent().
Property Documentation
AboutControl
NeuralDemoAbout IG.Neural.Applications.NeuralDemo.AboutControl get
Returns the control that contains the "About" page.
This control contains the ShowHelp and ShowWebPage methods, which display information about the application.
Referenced by IG.Neural.Applications.NeuralDemo.HelpEventHandlers().
The documentation for this class was generated from the following files:
shelldev/lib/extended/LibNeuralExtForms/FormsExperimental/NeuralApplications/NeuralDemo.cs
shelldev/lib/extended/LibNeuralExtForms/FormsExperimental/NeuralApplications/NeuralDemo.Designer.cs