Doc: IGLib EXTENDED: IG.Neural.Forms.NeuralParametricTestMultiple Class Reference
IG.Neural.Forms.NeuralParametricTestMultiple Class Reference
Form for training artificial neural networks.
Public Member Functions
NeuralParametricTestMultiple (INeuralModel neuralModel)
Constructs the control, with ANN-based model specified.
NeuralParametricTestMultiple ()
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
void ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void PlotParametricTest ()
plots the selected outpt dependend on the selected parameter.
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
INeuralModelContainer _neuralModelContainerControl
int _selectedParameterId = 0
int _selectedOutputId = 0
Properties
INeuralModel NeuralModel [get, protected set]
Neural network - based model.
INeuralApproximator TrainedNetwork [get]
Traint artificial neural network.
InputOutputDataDefiniton NeuralDataDefinition [get]
Neural data definition.
int NumInputParameters [get]
Gets number of input parameters.
int NumOutputValues [get]
Gets number of output values.
IVector ParameterValues [get]
Vector of current values of input parameters as defined by the DadaGridView.
double[] MinValues [get]
Minimal values of parameters.
double[] MaxValues [get]
Maximal values of parameters.
int SelectedParameterId [get, protected set]
Sequential number of the selected parameter as specified by the user.
double SelectedParameterMin [get]
Minimal value of the selected parameter.
double SelectedParameterMax [get]
Maximal value of the selected parameter as specified by the user.
int SelectedOutputId [get, protected set]
string SelectedParameterLabelText [get]
Gets axis label text for the currently selected parameter.
string SelectedOutputLabelText [get]
Gets axis label text for the currently selected output value.
PlotterZedGraph Plotter [get]
Plotter that is used for plotting the graphs.
Private Member Functions
void btnParmTestStart_Click (object sender, EventArgs e)
Plots the parametric test.
void neuralInputParameterSelector1_SelectedParameterIdChanged (int oldId, int newId)
Executes when ID of the selected input parameter changes; Plots the parametric test.
void neuralInputParameterSelector1_SelectedParameterMinChanged (double oldValue, double newValue)
Executes when minimal value of the selected parameter changes by user interaction; Plots the parametric test.
void neuralInputParameterSelector1_SelectedParameterMaxChanged (double oldValue, double newValue)
Executes when maximal value of the selected parameter changes by user interaction; Plots the parametric test.
void neuralOutputValueSelector1_SelectedOutputIdChanged (int oldId, int newId)
Executes when ID of the selected output value changes; Plots the parametric test.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
INeuralModel _neuralModel
PlotterZedGraph _plotter
System.ComponentModel.IContainer components = null
Required designer variable.
NeuralInputControl neuralInputControl1
System.Windows.Forms.Panel pnlGraph
System.Windows.Forms.NumericUpDown txtNumPointsLine
System.Windows.Forms.Label lblNumPointsLine
ZedGraph.ZedGraphControl ParmTestFGraph
System.Windows.Forms.Button btnParmTestStart
Forms.NeuralOutputValueSelector neuralOutputValueSelector1
NeuralInputParameterSelectorMinMax neuralInputParameterSelector1
System.Windows.Forms.Label lblTitleParametricMultiple
Detailed Description
Form for training artificial neural networks.
$A Igor Jul13;
Constructor & Destructor Documentation
NeuralParametricTestMultiple() [1/2]
IG.Neural.Forms.NeuralParametricTestMultiple.NeuralParametricTestMultiple (INeuralModel neuralModel) inline
Constructs the control, with ANN-based model specified.
Parameters
neuralModel ANN-based model, containing data definitions and trained neural network.
References IG.Neural.Forms.NeuralParametricTestMultiple.NeuralModel.
NeuralParametricTestMultiple() [2/2]
IG.Neural.Forms.NeuralParametricTestMultiple.NeuralParametricTestMultiple () inline
References IG.Neural.Forms.NeuralParametricTestMultiple.InitializeComponent().
Member Function Documentation
SetNeuralModel()
void IG.Neural.Forms.NeuralParametricTestMultiple.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
References IG.Neural.Forms.NeuralParametricTestMultiple.NeuralModel.
ApplyPlotterSettingsDefault()
void IG.Neural.Forms.NeuralParametricTestMultiple.ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Num.InputOutputDataDefiniton.InputElementList, IG.Gr.PlotterZedGraph.IsShowPointValues, IG.Neural.Forms.NeuralParametricTestMultiple.NeuralDataDefinition, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Neural.Forms.NeuralParametricTestMultiple.SelectedOutputLabelText, IG.Neural.Forms.NeuralParametricTestMultiple.SelectedParameterLabelText, IG.Gr.PlotterZedGraph.XAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabel.
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.PlotParametricTest().
ApplyPlotCurveSettingsDefault()
void IG.Neural.Forms.NeuralParametricTestMultiple.ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LineWidth, IG.Gr.PlotZedgraphCurve.PointBorderColor, IG.Gr.PlotZedgraphCurve.PointFillColor, and IG.Gr.PlotZedgraphCurve.PointsVisible.
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.PlotParametricTest().
PlotParametricTest()
void IG.Neural.Forms.NeuralParametricTestMultiple.PlotParametricTest () inline
plots the selected outpt dependend on the selected parameter.
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Neural.Forms.NeuralParametricTestMultiple.ApplyPlotCurveSettingsDefault(), IG.Neural.Forms.NeuralParametricTestMultiple.ApplyPlotterSettingsDefault(), IG.Num.IVectorApproximator.CalculateOutput(), IG.Num.VectorBase.CopyPlain(), IG.Neural.Forms.NeuralParametricTestMultiple.NumInputParameters, IG.Neural.Forms.NeuralParametricTestMultiple.NumOutputValues, IG.Neural.Forms.NeuralParametricTestMultiple.ParameterValues, IG.Neural.Forms.NeuralParametricTestMultiple.SelectedOutputId, IG.Neural.Forms.NeuralParametricTestMultiple.SelectedParameterId, IG.Neural.Forms.NeuralParametricTestMultiple.SelectedParameterMax, IG.Neural.Forms.NeuralParametricTestMultiple.SelectedParameterMin, IG.Neural.Forms.NeuralParametricTestMultiple.TrainedNetwork, and IG.Neural.Forms.NeuralParametricTestMultiple.txtNumPointsLine.
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.btnParmTestStart_Click(), IG.Neural.Forms.NeuralParametricTestMultiple.neuralInputParameterSelector1_SelectedParameterIdChanged(), IG.Neural.Forms.NeuralParametricTestMultiple.neuralInputParameterSelector1_SelectedParameterMaxChanged(), IG.Neural.Forms.NeuralParametricTestMultiple.neuralInputParameterSelector1_SelectedParameterMinChanged(), and IG.Neural.Forms.NeuralParametricTestMultiple.neuralOutputValueSelector1_SelectedOutputIdChanged().
btnParmTestStart_Click()
void IG.Neural.Forms.NeuralParametricTestMultiple.btnParmTestStart_Click (object sender, EventArgs e) inline private
Plots the parametric test.
References IG.Neural.Forms.NeuralParametricTestMultiple.PlotParametricTest().
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.InitializeComponent().
neuralInputParameterSelector1_SelectedParameterIdChanged()
void IG.Neural.Forms.NeuralParametricTestMultiple.neuralInputParameterSelector1_SelectedParameterIdChanged (int oldId, int newId) inline private
Executes when ID of the selected input parameter changes; Plots the parametric test.
Parameters
oldId Old ID of the selected output value (after change).
newId New ID of the selected output value (after changed).
References IG.Neural.Forms.NeuralParametricTestMultiple.PlotParametricTest().
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.InitializeComponent().
neuralInputParameterSelector1_SelectedParameterMinChanged()
void IG.Neural.Forms.NeuralParametricTestMultiple.neuralInputParameterSelector1_SelectedParameterMinChanged (double oldValue, double newValue) inline private
Executes when minimal value of the selected parameter changes by user interaction; Plots the parametric test.
Parameters
oldValue Old value.
newValue New value.
References IG.Neural.Forms.NeuralParametricTestMultiple.PlotParametricTest().
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.InitializeComponent().
neuralInputParameterSelector1_SelectedParameterMaxChanged()
void IG.Neural.Forms.NeuralParametricTestMultiple.neuralInputParameterSelector1_SelectedParameterMaxChanged (double oldValue, double newValue) inline private
Executes when maximal value of the selected parameter changes by user interaction; Plots the parametric test.
Parameters
oldValue Old value.
newValue New value.
References IG.Neural.Forms.NeuralParametricTestMultiple.PlotParametricTest().
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.InitializeComponent().
neuralOutputValueSelector1_SelectedOutputIdChanged()
void IG.Neural.Forms.NeuralParametricTestMultiple.neuralOutputValueSelector1_SelectedOutputIdChanged (int oldId, int newId) inline private
Executes when ID of the selected output value changes; Plots the parametric test.
Parameters
oldId Old ID of the selected output value (after change).
newId New ID of the selected output value (after changed).
References IG.Neural.Forms.NeuralParametricTestMultiple.PlotParametricTest().
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.InitializeComponent().
Dispose()
override void IG.Neural.Forms.NeuralParametricTestMultiple.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralParametricTestMultiple.components.
InitializeComponent()
void IG.Neural.Forms.NeuralParametricTestMultiple.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralParametricTestMultiple.btnParmTestStart, IG.Neural.Forms.NeuralParametricTestMultiple.btnParmTestStart_Click(), IG.Neural.Forms.NeuralParametricTestMultiple.lblNumPointsLine, IG.Neural.Forms.NeuralParametricTestMultiple.lblTitleParametricMultiple, IG.Neural.Forms.NeuralParametricTestMultiple.neuralInputControl1, IG.Neural.Forms.NeuralParametricTestMultiple.neuralInputParameterSelector1, IG.Neural.Forms.NeuralParametricTestMultiple.neuralInputParameterSelector1_SelectedParameterIdChanged(), IG.Neural.Forms.NeuralParametricTestMultiple.neuralInputParameterSelector1_SelectedParameterMaxChanged(), IG.Neural.Forms.NeuralParametricTestMultiple.neuralInputParameterSelector1_SelectedParameterMinChanged(), IG.Neural.Forms.NeuralParametricTestMultiple.neuralOutputValueSelector1, IG.Neural.Forms.NeuralParametricTestMultiple.neuralOutputValueSelector1_SelectedOutputIdChanged(), IG.Neural.Forms.NeuralParametricTestMultiple.ParmTestFGraph, IG.Neural.Forms.NeuralParametricTestMultiple.pnlGraph, IG.Neural.Forms.NeuralOutputValueSelector.SelectedOutputIdChanged, IG.Neural.Forms.NeuralInputParameterSelectorMinMax.SelectedParameterIdChanged, IG.Neural.Forms.NeuralInputParameterSelectorMinMax.SelectedParameterMaxChanged, IG.Neural.Forms.NeuralInputParameterSelectorMinMax.SelectedParameterMinChanged, IG.Neural.Forms.NeuralInputParameterSelectorMinMax.TitleParameterSelection, and IG.Neural.Forms.NeuralParametricTestMultiple.txtNumPointsLine.
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.NeuralParametricTestMultiple().
Member Data Documentation
_neuralModelContainerControl
INeuralModelContainer IG.Neural.Forms.NeuralParametricTestMultiple._neuralModelContainerControl protected
_neuralModel
INeuralModel IG.Neural.Forms.NeuralParametricTestMultiple._neuralModel private
_selectedParameterId
int IG.Neural.Forms.NeuralParametricTestMultiple._selectedParameterId = 0 protected
_selectedOutputId
int IG.Neural.Forms.NeuralParametricTestMultiple._selectedOutputId = 0 protected
_plotter
PlotterZedGraph IG.Neural.Forms.NeuralParametricTestMultiple._plotter private
components
System.ComponentModel.IContainer IG.Neural.Forms.NeuralParametricTestMultiple.components = null private
Required designer variable.
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.Dispose().
neuralInputControl1
NeuralInputControl IG.Neural.Forms.NeuralParametricTestMultiple.neuralInputControl1 private
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.InitializeComponent().
pnlGraph
System.Windows.Forms.Panel IG.Neural.Forms.NeuralParametricTestMultiple.pnlGraph private
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.InitializeComponent().
txtNumPointsLine
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralParametricTestMultiple.txtNumPointsLine private
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.InitializeComponent(), and IG.Neural.Forms.NeuralParametricTestMultiple.PlotParametricTest().
lblNumPointsLine
System.Windows.Forms.Label IG.Neural.Forms.NeuralParametricTestMultiple.lblNumPointsLine private
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.InitializeComponent().
ParmTestFGraph
ZedGraph.ZedGraphControl IG.Neural.Forms.NeuralParametricTestMultiple.ParmTestFGraph private
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.InitializeComponent().
btnParmTestStart
System.Windows.Forms.Button IG.Neural.Forms.NeuralParametricTestMultiple.btnParmTestStart private
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.InitializeComponent().
neuralOutputValueSelector1
Forms.NeuralOutputValueSelector IG.Neural.Forms.NeuralParametricTestMultiple.neuralOutputValueSelector1 private
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.InitializeComponent().
neuralInputParameterSelector1
NeuralInputParameterSelectorMinMax IG.Neural.Forms.NeuralParametricTestMultiple.neuralInputParameterSelector1 private
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.InitializeComponent().
lblTitleParametricMultiple
System.Windows.Forms.Label IG.Neural.Forms.NeuralParametricTestMultiple.lblTitleParametricMultiple private
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.InitializeComponent().
Property Documentation
NeuralModel
INeuralModel IG.Neural.Forms.NeuralParametricTestMultiple.NeuralModel get protected set
Neural network - based model.
Contains data definition and trained neural network approximator.
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.NeuralParametricTestMultiple(), and IG.Neural.Forms.NeuralParametricTestMultiple.SetNeuralModel().
TrainedNetwork
INeuralApproximator IG.Neural.Forms.NeuralParametricTestMultiple.TrainedNetwork get
Traint artificial neural network.
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.PlotParametricTest().
NeuralDataDefinition
InputOutputDataDefiniton IG.Neural.Forms.NeuralParametricTestMultiple.NeuralDataDefinition get
Neural data definition.
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.ApplyPlotterSettingsDefault().
NumInputParameters
int IG.Neural.Forms.NeuralParametricTestMultiple.NumInputParameters get
Gets number of input parameters.
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.PlotParametricTest().
NumOutputValues
int IG.Neural.Forms.NeuralParametricTestMultiple.NumOutputValues get
Gets number of output values.
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.PlotParametricTest().
ParameterValues
IVector IG.Neural.Forms.NeuralParametricTestMultiple.ParameterValues get
Vector of current values of input parameters as defined by the DadaGridView.
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.PlotParametricTest().
MinValues
double [] IG.Neural.Forms.NeuralParametricTestMultiple.MinValues get
Minimal values of parameters.
MaxValues
double [] IG.Neural.Forms.NeuralParametricTestMultiple.MaxValues get
Maximal values of parameters.
SelectedParameterId
int IG.Neural.Forms.NeuralParametricTestMultiple.SelectedParameterId get protected set
Sequential number of the selected parameter as specified by the user.
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.PlotParametricTest().
SelectedParameterMin
double IG.Neural.Forms.NeuralParametricTestMultiple.SelectedParameterMin get
Minimal value of the selected parameter.
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.PlotParametricTest().
SelectedParameterMax
double IG.Neural.Forms.NeuralParametricTestMultiple.SelectedParameterMax get
Maximal value of the selected parameter as specified by the user.
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.PlotParametricTest().
SelectedOutputId
int IG.Neural.Forms.NeuralParametricTestMultiple.SelectedOutputId get protected set
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.PlotParametricTest().
SelectedParameterLabelText
string IG.Neural.Forms.NeuralParametricTestMultiple.SelectedParameterLabelText get
Gets axis label text for the currently selected parameter.
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.ApplyPlotterSettingsDefault().
SelectedOutputLabelText
string IG.Neural.Forms.NeuralParametricTestMultiple.SelectedOutputLabelText get
Gets axis label text for the currently selected output value.
Referenced by IG.Neural.Forms.NeuralParametricTestMultiple.ApplyPlotterSettingsDefault().
Plotter
PlotterZedGraph IG.Neural.Forms.NeuralParametricTestMultiple.Plotter get
Plotter that is used for plotting the graphs.
The documentation for this class was generated from the following files:
shelldev/extensions/ExtAppAnnApp/ResponseForms/TestingStage/NeuralParametricTestMultiple.cs
shelldev/extensions/ExtAppAnnApp/ResponseForms/TestingStage/NeuralParametricTestMultiple.Designer.cs