Doc: IGLib EXTENDED: NUnit.Framework.Constraints.NUnitComparerTests Class Reference
NUnit.Framework.Constraints.NUnitComparerTests Class Reference
Public Member Functions
void SetUp ()
void EqualItems (object x, object y)
void UnequalItems (object greater, object lesser)
Private Attributes
NUnitComparer comparer
Member Function Documentation
SetUp()
void NUnit.Framework.Constraints.NUnitComparerTests.SetUp () inline
References NUnit.Framework.Constraints.NUnitComparerTests.comparer.
EqualItems()
void NUnit.Framework.Constraints.NUnitComparerTests.EqualItems (object x, object y) inline
References NUnit.Framework.Constraints.NUnitComparer.Compare(), NUnit.Framework.Constraints.NUnitComparerTests.comparer, and NUnit.Framework.Assert.That().
UnequalItems()
void NUnit.Framework.Constraints.NUnitComparerTests.UnequalItems (object greater, object lesser) inline
References NUnit.Framework.Constraints.NUnitComparer.Compare(), NUnit.Framework.Constraints.NUnitComparerTests.comparer, and NUnit.Framework.Assert.That().
Member Data Documentation
comparer
NUnitComparer NUnit.Framework.Constraints.NUnitComparerTests.comparer private
Referenced by NUnit.Framework.Constraints.NUnitComparerTests.EqualItems(), NUnit.Framework.Constraints.NUnitComparerTests.SetUp(), and NUnit.Framework.Constraints.NUnitComparerTests.UnequalItems().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/NUnitComparerTests.cs