Doc: IGLib EXTENDED: IG.Forms.TestLoadableScriptInterpreter Class Reference
IG.Forms.TestLoadableScriptInterpreter Class Reference
Static Public Member Functions
static void RunTest ()
Member Function Documentation
RunTest()
static void IG.Forms.TestLoadableScriptInterpreter.RunTest () inline static
References IG.Lib.ScriptLoaderBase.AddReferencedAssemblies(), IG.Lib.ScriptLoaderBase.RunFile(), and IG.Lib.LoadableScriptInterpreterBase.ScriptLoader.
Referenced by IG.Forms.ScriptLoaderForm.btnOther_Click().
The documentation for this class was generated from the following file:
igtest/test_iglib_tmp_CSharpScripter/loadablescript/tests/OtherTests.cs