Doc: IGLib EXTENDED: IG.Lib.SettingsReaderBase Class Reference
IG.Lib.SettingsReaderBase Class Reference abstract
Public Member Functions
abstract string GetSetting (string settingname)
Retrieves the specified setting from the current settings source.
virtual bool GetBooleanSetting (string settingname)
Retrieves the specified boolean setting from the current settings source.
virtual long GetIntegerSetting (string settingname)
Retrieves the specified integer setting from the current settings source. If the specific setting is not specified in the configuration then 0 is returned.
virtual long GetIntegerSetting (string settingname, long defaultvalue)
Retrieves the specified integer setting from the current settings source.
abstract string GetSetting (string settingname)
Retrieves the specified setting from the current settings source.
virtual bool GetBooleanSetting (string settingname)
Retrieves the specified boolean setting from the current settings source.
virtual long GetIntegerSetting (string settingname)
Retrieves the specified integer setting from the current settings source. If the specific setting is not specified in the configuration then 0 is returned.
virtual long GetIntegerSetting (string settingname, long defaultvalue)
Retrieves the specified integer setting from the current settings source.
Protected Member Functions
bool ToBoolean (string strsetting)
Converts a string representation of a boolean setting to boolean. Strings "true", "yes" and "on" (regardless of capitalization) or non-zero integer representations result to true, anything else (including null or empty string) result in false.
long ToInt (string strsetting)
Converts a string representation of an integer setting to an integer value. If the setting is not defined then 0 is returned.
long ToInt (string strsetting, long defaultvalue)
Converts a string representation of an integer setting to an integer value.
Protected Attributes
bool _expandEnv = true
Properties
object Lock [get]
ILockable.Lock, gets a public lock for the current object.
virtual bool ExpandEnvironmentVariables [get, set]
Properties inherited from IG.Lib.ILockable
object Lock [get]
Static Private Member Functions
static ISettingsRreader FromAppConfig ()
static ISettingsRreader FromAppConfig ()
Private Attributes
object lockobj = new object()
Member Function Documentation
GetSetting() [1/2]
abstract string IG.Lib.SettingsReaderBase.GetSetting (string settingname) pure virtual
Retrieves the specified setting from the current settings source.
Parameters
settingname Setting name.
Implemented in IG.Lib.SettingsReaderAppConfig, and IG.Lib.SettingsReaderAppConfig.
Referenced by IG.Lib.SettingsReaderBase.GetBooleanSetting(), and IG.Lib.SettingsReaderBase.GetIntegerSetting().
GetBooleanSetting() [1/2]
virtual bool IG.Lib.SettingsReaderBase.GetBooleanSetting (string settingname) inline virtual
Retrieves the specified boolean setting from the current settings source.
Parameters
settingname Setting name.
References IG.Lib.SettingsReaderBase.GetSetting(), and IG.Lib.UtilStr.ToBoolean().
Referenced by LabexBis.BisCommunicationSettings.getsettings().
GetIntegerSetting() [1/4]
virtual long IG.Lib.SettingsReaderBase.GetIntegerSetting (string settingname) inline virtual
Retrieves the specified integer setting from the current settings source. If the specific setting is not specified in the configuration then 0 is returned.
Parameters
settingname Setting name.
References IG.Lib.SettingsReaderBase.GetSetting(), and IG.Lib.UtilStr.ToInt().
Referenced by LabexBis.BisCommunicationSettings.getsettings().
GetIntegerSetting() [2/4]
virtual long IG.Lib.SettingsReaderBase.GetIntegerSetting (string settingname, long defaultvalue) inline virtual
Retrieves the specified integer setting from the current settings source.
Parameters
settingname Setting name.
defaultvalue Value returned in the case that the correspondig setting is not defined.
References IG.Lib.SettingsReaderBase.GetSetting(), and IG.Lib.UtilStr.ToInt().
FromAppConfig() [1/2]
static ISettingsRreader IG.Lib.SettingsReaderBase.FromAppConfig () inline static private
GetSetting() [2/2]
abstract string IG.Lib.SettingsReaderBase.GetSetting (string settingname) pure virtual
Retrieves the specified setting from the current settings source.
Parameters
settingname Setting name.
Implemented in IG.Lib.SettingsReaderAppConfig, and IG.Lib.SettingsReaderAppConfig.
GetBooleanSetting() [2/2]
virtual bool IG.Lib.SettingsReaderBase.GetBooleanSetting (string settingname) inline virtual
Retrieves the specified boolean setting from the current settings source.
Parameters
settingname Setting name.
References IG.Lib.SettingsReaderBase.GetSetting(), and IG.Lib.SettingsReaderBase.ToBoolean().
GetIntegerSetting() [3/4]
virtual long IG.Lib.SettingsReaderBase.GetIntegerSetting (string settingname) inline virtual
Retrieves the specified integer setting from the current settings source. If the specific setting is not specified in the configuration then 0 is returned.
Parameters
settingname Setting name.
References IG.Lib.SettingsReaderBase.GetSetting(), and IG.Lib.SettingsReaderBase.ToInt().
GetIntegerSetting() [4/4]
virtual long IG.Lib.SettingsReaderBase.GetIntegerSetting (string settingname, long defaultvalue) inline virtual
Retrieves the specified integer setting from the current settings source.
Parameters
settingname Setting name.
defaultvalue Value returned in the case that the correspondig setting is not defined.
References IG.Lib.SettingsReaderBase.GetSetting(), and IG.Lib.SettingsReaderBase.ToInt().
ToBoolean()
bool IG.Lib.SettingsReaderBase.ToBoolean (string strsetting) inline protected
Converts a string representation of a boolean setting to boolean. Strings "true", "yes" and "on" (regardless of capitalization) or non-zero integer representations result to true, anything else (including null or empty string) result in false.
Parameters
strsetting String representation of the specific setting.
Returns
Boolean value corresponding to the setting.
Referenced by IG.Lib.SettingsReaderBase.GetBooleanSetting().
ToInt() [1/2]
long IG.Lib.SettingsReaderBase.ToInt (string strsetting) inline protected
Converts a string representation of an integer setting to an integer value. If the setting is not defined then 0 is returned.
Parameters
strsetting String representation of the specific setting.
Returns
Long integer value corresponding to the setting.
Referenced by IG.Lib.SettingsReaderBase.GetIntegerSetting().
ToInt() [2/2]
long IG.Lib.SettingsReaderBase.ToInt (string strsetting, long defaultvalue) inline protected
Converts a string representation of an integer setting to an integer value.
Parameters
strsetting String representation of the specific setting.
defaultvalue Default value returned in the case that the setting is not defined.
Returns
Long integer value corresponding to the setting.
FromAppConfig() [2/2]
static ISettingsRreader IG.Lib.SettingsReaderBase.FromAppConfig () inline static private
Member Data Documentation
lockobj
object IG.Lib.SettingsReaderBase.lockobj = new object() private
Referenced by LabexBis.BisCommunicationSettings.ReadSettingsAppConfig().
_expandEnv
bool IG.Lib.SettingsReaderBase._expandEnv = true protected
Property Documentation
Lock
object IG.Lib.SettingsReaderBase.Lock get
ILockable.Lock, gets a public lock for the current object.
ExpandEnvironmentVariables
bool IG.Lib.SettingsReaderBase.ExpandEnvironmentVariables get set
The documentation for this class was generated from the following file:
iglib/igbase/application/SettingsRreader.cs