Doc: IGLib EXTENDED: IG.Gr3d.Graph3dManipulatorWindow Class Reference
IG.Gr3d.Graph3dManipulatorWindow Class Reference
A form for manipulation of 3D graphics.
Public Member Functions
Graph3dManipulatorWindow ()
Graph3dManipulatorWindow (IVtkFormContainer vtkContainer)
Public Member Functions inherited from IG.Forms.IClosableFromContainedForm
void Close ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
IVtkFormContainer VtkContainer [get, set]
Gets the control of type VtkControlBase through which VTK functionality is controlled.
VtkControlBase VtkControl [get, set]
Gets the control of type VtkControlBase through which VTK functionality is controlled.
I3dGraphicsControl GraphControl [get]
Graph control that is manipulated by the current control.
Private Member Functions
void graph3DManipulator1_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
IVtkFormContainer _vtkContainer
VtkControlBase _vtkControl
System.ComponentModel.IContainer components = null
Required designer variable.
Graph3dManipulator graph3DManipulator1
Detailed Description
A form for manipulation of 3D graphics.
$A Igor xx;
Constructor & Destructor Documentation
Graph3dManipulatorWindow() [1/2]
IG.Gr3d.Graph3dManipulatorWindow.Graph3dManipulatorWindow () inline
References IG.Gr3d.Graph3dManipulatorWindow.InitializeComponent().
Graph3dManipulatorWindow() [2/2]
IG.Gr3d.Graph3dManipulatorWindow.Graph3dManipulatorWindow (IVtkFormContainer vtkContainer) inline
References IG.Gr3d.Graph3dManipulatorWindow.VtkContainer.
Member Function Documentation
graph3DManipulator1_Load()
void IG.Gr3d.Graph3dManipulatorWindow.graph3DManipulator1_Load (object sender, EventArgs e) inline private
Referenced by IG.Gr3d.Graph3dManipulatorWindow.InitializeComponent().
Dispose()
override void IG.Gr3d.Graph3dManipulatorWindow.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Gr3d.Graph3dManipulatorWindow.components.
InitializeComponent()
void IG.Gr3d.Graph3dManipulatorWindow.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Gr3d.Graph3dManipulatorWindow.graph3DManipulator1, IG.Gr3d.Graph3dManipulatorWindow.graph3DManipulator1_Load(), IG.Gr3d.Graph3dManipulator.IsCloseWindoButtonVisible, IG.Gr3d.Graph3dManipulator.VtkContainer, and IG.Gr3d.Graph3dManipulator.VtkControl.
Referenced by IG.Gr3d.Graph3dManipulatorWindow.Graph3dManipulatorWindow().
Member Data Documentation
_vtkContainer
IVtkFormContainer IG.Gr3d.Graph3dManipulatorWindow._vtkContainer private
_vtkControl
VtkControlBase IG.Gr3d.Graph3dManipulatorWindow._vtkControl private
components
System.ComponentModel.IContainer IG.Gr3d.Graph3dManipulatorWindow.components = null private
Required designer variable.
Referenced by IG.Gr3d.Graph3dManipulatorWindow.Dispose().
graph3DManipulator1
Graph3dManipulator IG.Gr3d.Graph3dManipulatorWindow.graph3DManipulator1 private
Referenced by IG.Gr3d.Graph3dManipulatorWindow.InitializeComponent().
Property Documentation
VtkContainer
IVtkFormContainer IG.Gr3d.Graph3dManipulatorWindow.VtkContainer get set
Gets the control of type VtkControlBase through which VTK functionality is controlled.
Referenced by IG.Gr3d.Graph3dManipulatorWindow.Graph3dManipulatorWindow().
VtkControl
VtkControlBase IG.Gr3d.Graph3dManipulatorWindow.VtkControl get set
Gets the control of type VtkControlBase through which VTK functionality is controlled.
GraphControl
I3dGraphicsControl IG.Gr3d.Graph3dManipulatorWindow.GraphControl get
Graph control that is manipulated by the current control.
The documentation for this class was generated from the following files:
iglib/extensions/igplot3d/plot3d/vtkbased/Forms/testforms/Graph3dManipulatorWindow.cs
iglib/extensions/igplot3d/plot3d/vtkbased/Forms/testforms/Graph3dManipulatorWindow.Designer.cs