Doc: IGLib EXTENDED: AForge.Imaging.Filters.SaturationCorrection Class Reference
AForge.Imaging.Filters.SaturationCorrection Class Reference
Saturation adjusting in HSL color space.
Public Member Functions
SaturationCorrection ()
Initializes a new instance of the SaturationCorrection class.
SaturationCorrection (float adjustValue)
Initializes a new instance of the SaturationCorrection class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image, Rectangle rect)
Process the filter on the specified image.
Properties
float AdjustValue [get, set]
Saturation adjust value, [-1, 1].
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
HSLLinear baseFilter = new HSLLinear()
float adjustValue
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Saturation adjusting in HSL color space.
The filter operates in HSL color space and adjusts pixels' saturation value, increasing it or decreasing by specified percentage. The filters is based on HSLLinear filter, passing work to it after recalculating saturation adjust value to input/output ranges of the HSLLinear filter.
The filter accepts 24 and 32 bpp color images for processing.
Sample usage:
// create filter
SaturationCorrection filter = new SaturationCorrection(-0.5f);
// apply the filter
filter.ApplyInPlace(image);
Initial image:
Result image:
Constructor & Destructor Documentation
SaturationCorrection() [1/2]
AForge.Imaging.Filters.SaturationCorrection.SaturationCorrection () inline
Initializes a new instance of the SaturationCorrection class.
SaturationCorrection() [2/2]
AForge.Imaging.Filters.SaturationCorrection.SaturationCorrection (float adjustValue) inline
Initializes a new instance of the SaturationCorrection class.
Parameters
adjustValue Saturation adjust value.
References AForge.Imaging.Filters.SaturationCorrection.adjustValue, AForge.Imaging.Filters.SaturationCorrection.AdjustValue, and AForge.Imaging.Filters.SaturationCorrection.formatTranslations.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.SaturationCorrection.ProcessFilter (UnmanagedImage image, Rectangle rect) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
rect Image rectangle for processing by the filter.
Implements AForge.Imaging.Filters.BaseInPlacePartialFilter.
References AForge.Imaging.Filters.BaseInPlacePartialFilter.ApplyInPlace(), and AForge.Imaging.Filters.SaturationCorrection.baseFilter.
Member Data Documentation
baseFilter
HSLLinear AForge.Imaging.Filters.SaturationCorrection.baseFilter = new HSLLinear() private
Referenced by AForge.Imaging.Filters.SaturationCorrection.ProcessFilter().
adjustValue
float AForge.Imaging.Filters.SaturationCorrection.adjustValue private
Referenced by AForge.Imaging.Filters.SaturationCorrection.SaturationCorrection().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.SaturationCorrection.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.SaturationCorrection.SaturationCorrection().
Property Documentation
AdjustValue
float AForge.Imaging.Filters.SaturationCorrection.AdjustValue get set
Saturation adjust value, [-1, 1].
Default value is set to 0.1, which corresponds to increasing saturation by 10%.
Referenced by AForge.Imaging.Filters.SaturationCorrection.SaturationCorrection().
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.SaturationCorrection.FormatTranslations get
Format translations dictionary.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/HSL Filters/SaturationCorrection.cs