Doc: IGLib EXTENDED: NUnit.Framework.Attributes.DerivedPropertyAttributeTests Class Reference
NUnit.Framework.Attributes.DerivedPropertyAttributeTests Class Reference
Public Member Functions
void ConstructWithOneArg< T > (Type attrType, string propName, T propValue)
void ConstructWithNoArgs< T > (Type attrType, string propName, T propValue)
Member Function Documentation
ConstructWithOneArg< T >()
void NUnit.Framework.Attributes.DerivedPropertyAttributeTests.ConstructWithOneArg< T > (Type attrType, string propName, T propValue) inline
References NUnit.Framework.Internal.Reflect.Construct(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.NotNull(), and NUnit.Framework.Assert.That().
ConstructWithNoArgs< T >()
void NUnit.Framework.Attributes.DerivedPropertyAttributeTests.ConstructWithNoArgs< T > (Type attrType, string propName, T propValue) inline
References NUnit.Framework.Internal.Reflect.Construct(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.NotNull(), and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/DerivedPropertyAttributeTests.cs