Doc: IGLib EXTENDED: alglib.mlpe Class Reference
alglib.mlpe Class Reference
Classes
class mlpensemble
Static Public Member Functions
static void mlpecreate0 (int nin, int nout, int ensemblesize, mlpensemble ensemble)
static void mlpecreate1 (int nin, int nhid, int nout, int ensemblesize, mlpensemble ensemble)
static void mlpecreate2 (int nin, int nhid1, int nhid2, int nout, int ensemblesize, mlpensemble ensemble)
static void mlpecreateb0 (int nin, int nout, double b, double d, int ensemblesize, mlpensemble ensemble)
static void mlpecreateb1 (int nin, int nhid, int nout, double b, double d, int ensemblesize, mlpensemble ensemble)
static void mlpecreateb2 (int nin, int nhid1, int nhid2, int nout, double b, double d, int ensemblesize, mlpensemble ensemble)
static void mlpecreater0 (int nin, int nout, double a, double b, int ensemblesize, mlpensemble ensemble)
static void mlpecreater1 (int nin, int nhid, int nout, double a, double b, int ensemblesize, mlpensemble ensemble)
static void mlpecreater2 (int nin, int nhid1, int nhid2, int nout, double a, double b, int ensemblesize, mlpensemble ensemble)
static void mlpecreatec0 (int nin, int nout, int ensemblesize, mlpensemble ensemble)
static void mlpecreatec1 (int nin, int nhid, int nout, int ensemblesize, mlpensemble ensemble)
static void mlpecreatec2 (int nin, int nhid1, int nhid2, int nout, int ensemblesize, mlpensemble ensemble)
static void mlpecreatefromnetwork (mlpbase.multilayerperceptron network, int ensemblesize, mlpensemble ensemble)
static void mlpecopy (mlpensemble ensemble1, mlpensemble ensemble2)
static void mlperandomize (mlpensemble ensemble)
static void mlpeproperties (mlpensemble ensemble, ref int nin, ref int nout)
static bool mlpeissoftmax (mlpensemble ensemble)
static void mlpeprocess (mlpensemble ensemble, double[] x, ref double[] y)
static void mlpeprocessi (mlpensemble ensemble, double[] x, ref double[] y)
static double mlperelclserror (mlpensemble ensemble, double[,] xy, int npoints)
static double mlpeavgce (mlpensemble ensemble, double[,] xy, int npoints)
static double mlpermserror (mlpensemble ensemble, double[,] xy, int npoints)
static double mlpeavgerror (mlpensemble ensemble, double[,] xy, int npoints)
static double mlpeavgrelerror (mlpensemble ensemble, double[,] xy, int npoints)
static void mlpebagginglm (mlpensemble ensemble, double[,] xy, int npoints, double decay, int restarts, ref int info, mlptrain.mlpreport rep, mlptrain.mlpcvreport ooberrors)
static void mlpebagginglbfgs (mlpensemble ensemble, double[,] xy, int npoints, double decay, int restarts, double wstep, int maxits, ref int info, mlptrain.mlpreport rep, mlptrain.mlpcvreport ooberrors)
static void mlpetraines (mlpensemble ensemble, double[,] xy, int npoints, double decay, int restarts, ref int info, mlptrain.mlpreport rep)
static void mlpealloc (alglib.serializer s, mlpensemble ensemble)
static void mlpeserialize (alglib.serializer s, mlpensemble ensemble)
static void mlpeunserialize (alglib.serializer s, mlpensemble ensemble)
static void mlpecreate0 (int nin, int nout, int ensemblesize, mlpensemble ensemble)
static void mlpecreate1 (int nin, int nhid, int nout, int ensemblesize, mlpensemble ensemble)
static void mlpecreate2 (int nin, int nhid1, int nhid2, int nout, int ensemblesize, mlpensemble ensemble)
static void mlpecreateb0 (int nin, int nout, double b, double d, int ensemblesize, mlpensemble ensemble)
static void mlpecreateb1 (int nin, int nhid, int nout, double b, double d, int ensemblesize, mlpensemble ensemble)
static void mlpecreateb2 (int nin, int nhid1, int nhid2, int nout, double b, double d, int ensemblesize, mlpensemble ensemble)
static void mlpecreater0 (int nin, int nout, double a, double b, int ensemblesize, mlpensemble ensemble)
static void mlpecreater1 (int nin, int nhid, int nout, double a, double b, int ensemblesize, mlpensemble ensemble)
static void mlpecreater2 (int nin, int nhid1, int nhid2, int nout, double a, double b, int ensemblesize, mlpensemble ensemble)
static void mlpecreatec0 (int nin, int nout, int ensemblesize, mlpensemble ensemble)
static void mlpecreatec1 (int nin, int nhid, int nout, int ensemblesize, mlpensemble ensemble)
static void mlpecreatec2 (int nin, int nhid1, int nhid2, int nout, int ensemblesize, mlpensemble ensemble)
static void mlpecreatefromnetwork (mlpbase.multilayerperceptron network, int ensemblesize, mlpensemble ensemble)
static void mlpecopy (mlpensemble ensemble1, mlpensemble ensemble2)
static void mlperandomize (mlpensemble ensemble)
static void mlpeproperties (mlpensemble ensemble, ref int nin, ref int nout)
static bool mlpeissoftmax (mlpensemble ensemble)
static void mlpeprocess (mlpensemble ensemble, double[] x, ref double[] y)
static void mlpeprocessi (mlpensemble ensemble, double[] x, ref double[] y)
static void mlpeallerrorsx (mlpensemble ensemble, double[,] densexy, sparse.sparsematrix sparsexy, int datasetsize, int datasettype, int[] idx, int subset0, int subset1, int subsettype, alglib.smp.shared_pool buf, mlpbase.modelerrors rep)
static void mlpeallerrorssparse (mlpensemble ensemble, sparse.sparsematrix xy, int npoints, ref double relcls, ref double avgce, ref double rms, ref double avg, ref double avgrel)
static double mlperelclserror (mlpensemble ensemble, double[,] xy, int npoints)
static double mlpeavgce (mlpensemble ensemble, double[,] xy, int npoints)
static double mlpermserror (mlpensemble ensemble, double[,] xy, int npoints)
static double mlpeavgerror (mlpensemble ensemble, double[,] xy, int npoints)
static double mlpeavgrelerror (mlpensemble ensemble, double[,] xy, int npoints)
static void mlpealloc (alglib.serializer s, mlpensemble ensemble)
static void mlpeserialize (alglib.serializer s, mlpensemble ensemble)
static void mlpeunserialize (alglib.serializer s, mlpensemble ensemble)
Static Public Attributes
const int mlpntotaloffset = 3
const int mlpevnum = 9
const int mlpefirstversion = 1
Static Private Member Functions
static void mlpeallerrors (mlpensemble ensemble, double[,] xy, int npoints, ref double relcls, ref double avgce, ref double rms, ref double avg, ref double avgrel)
static void mlpebagginginternal (mlpensemble ensemble, double[,] xy, int npoints, double decay, int restarts, double wstep, int maxits, bool lmalgorithm, ref int info, mlptrain.mlpreport rep, mlptrain.mlpcvreport ooberrors)
Member Function Documentation
mlpecreate0() [1/2]
static void alglib.mlpe.mlpecreate0 (int nin, int nout, int ensemblesize, mlpensemble ensemble) inline static
Referenced by alglib.testmlpeunit.createensemble(), alglib.mlpecreate0(), and alglib.testmlpeunit.unsetensemble().
mlpecreate1() [1/2]
static void alglib.mlpe.mlpecreate1 (int nin, int nhid, int nout, int ensemblesize, mlpensemble ensemble) inline static
Referenced by alglib.testmlpeunit.createensemble(), alglib.mlpecreate1(), alglib.testmlpeunit.testmlpe(), alglib.testmlptrainunit.testmlptrainens(), and alglib.testmlptrainunit.testmlptrainensregr().
mlpecreate2() [1/2]
static void alglib.mlpe.mlpecreate2 (int nin, int nhid1, int nhid2, int nout, int ensemblesize, mlpensemble ensemble) inline static
Referenced by alglib.testmlpeunit.createensemble(), and alglib.mlpecreate2().
mlpecreateb0() [1/2]
static void alglib.mlpe.mlpecreateb0 (int nin, int nout, double b, double d, int ensemblesize, mlpensemble ensemble) inline static
Referenced by alglib.testmlpeunit.createensemble(), and alglib.mlpecreateb0().
mlpecreateb1() [1/2]
static void alglib.mlpe.mlpecreateb1 (int nin, int nhid, int nout, double b, double d, int ensemblesize, mlpensemble ensemble) inline static
Referenced by alglib.testmlpeunit.createensemble(), and alglib.mlpecreateb1().
mlpecreateb2() [1/2]
static void alglib.mlpe.mlpecreateb2 (int nin, int nhid1, int nhid2, int nout, double b, double d, int ensemblesize, mlpensemble ensemble) inline static
Referenced by alglib.testmlpeunit.createensemble(), and alglib.mlpecreateb2().
mlpecreater0() [1/2]
static void alglib.mlpe.mlpecreater0 (int nin, int nout, double a, double b, int ensemblesize, mlpensemble ensemble) inline static
Referenced by alglib.testmlpeunit.createensemble(), and alglib.mlpecreater0().
mlpecreater1() [1/2]
static void alglib.mlpe.mlpecreater1 (int nin, int nhid, int nout, double a, double b, int ensemblesize, mlpensemble ensemble) inline static
Referenced by alglib.testmlpeunit.createensemble(), and alglib.mlpecreater1().
mlpecreater2() [1/2]
static void alglib.mlpe.mlpecreater2 (int nin, int nhid1, int nhid2, int nout, double a, double b, int ensemblesize, mlpensemble ensemble) inline static
Referenced by alglib.testmlpeunit.createensemble(), and alglib.mlpecreater2().
mlpecreatec0() [1/2]
static void alglib.mlpe.mlpecreatec0 (int nin, int nout, int ensemblesize, mlpensemble ensemble) inline static
Referenced by alglib.testmlpeunit.createensemble(), alglib.mlpecreatec0(), and alglib.testmlptrainunit.testmlptrainenscls().
mlpecreatec1() [1/2]
static void alglib.mlpe.mlpecreatec1 (int nin, int nhid, int nout, int ensemblesize, mlpensemble ensemble) inline static
Referenced by alglib.testmlpeunit.createensemble(), alglib.mlpecreatec1(), alglib.testmlpeunit.testmlpe(), and alglib.testmlptrainunit.testmlptrainens().
mlpecreatec2() [1/2]
static void alglib.mlpe.mlpecreatec2 (int nin, int nhid1, int nhid2, int nout, int ensemblesize, mlpensemble ensemble) inline static
Referenced by alglib.testmlpeunit.createensemble(), and alglib.mlpecreatec2().
mlpecreatefromnetwork() [1/2]
static void alglib.mlpe.mlpecreatefromnetwork (mlpbase.multilayerperceptron network, int ensemblesize, mlpensemble ensemble) inline static
Referenced by alglib.mlpecreatefromnetwork().
mlpecopy() [1/2]
static void alglib.mlpe.mlpecopy (mlpensemble ensemble1, mlpensemble ensemble2) inline static
Referenced by alglib.testmlpeunit.testprocessing().
mlperandomize() [1/2]
static void alglib.mlpe.mlperandomize (mlpensemble ensemble) inline static
Referenced by alglib.mlperandomize(), alglib.testmlpeunit.testerr(), and alglib.testmlpeunit.testprocessing().
mlpeproperties() [1/2]
static void alglib.mlpe.mlpeproperties (mlpensemble ensemble, ref int nin, ref int nout) inline static
Referenced by alglib.mlpeproperties(), and alglib.testmlpeunit.testinformational().
mlpeissoftmax() [1/2]
static bool alglib.mlpe.mlpeissoftmax (mlpensemble ensemble) inline static
Referenced by alglib.mlpeissoftmax(), and alglib.testmlpeunit.testerr().
mlpeprocess() [1/2]
static void alglib.mlpe.mlpeprocess (mlpensemble ensemble, double[] x, ref double[] y) inline static
Referenced by alglib.mlpeprocess(), alglib.testmlpeunit.testerr(), alglib.testmlptrainunit.testmlptrainenscls(), alglib.testmlptrainunit.testmlptrainensregr(), and alglib.testmlpeunit.testprocessing().
mlpeprocessi() [1/2]
static void alglib.mlpe.mlpeprocessi (mlpensemble ensemble, double[] x, ref double[] y) inline static
Referenced by alglib.mlpeprocessi().
mlperelclserror() [1/2]
static double alglib.mlpe.mlperelclserror (mlpensemble ensemble, double xy[,], int npoints) inline static
Referenced by alglib.mlperelclserror().
mlpeavgce() [1/2]
static double alglib.mlpe.mlpeavgce (mlpensemble ensemble, double xy[,], int npoints) inline static
Referenced by alglib.mlpeavgce(), and alglib.testmlpeunit.testerr().
mlpermserror() [1/2]
static double alglib.mlpe.mlpermserror (mlpensemble ensemble, double xy[,], int npoints) inline static
Referenced by alglib.mlpermserror(), alglib.testmlpeunit.testerr(), alglib.testmlpeunit.testmlpe(), and alglib.testmlptrainunit.testmlptrainens().
mlpeavgerror() [1/2]
static double alglib.mlpe.mlpeavgerror (mlpensemble ensemble, double xy[,], int npoints) inline static
Referenced by alglib.mlpeavgerror(), and alglib.testmlpeunit.testerr().
mlpeavgrelerror() [1/2]
static double alglib.mlpe.mlpeavgrelerror (mlpensemble ensemble, double xy[,], int npoints) inline static
Referenced by alglib.mlpeavgrelerror(), and alglib.testmlpeunit.testerr().
mlpebagginglm()
static void alglib.mlpe.mlpebagginglm (mlpensemble ensemble, double xy[,], int npoints, double decay, int restarts, ref int info, mlptrain.mlpreport rep, mlptrain.mlpcvreport ooberrors) inline static
Referenced by alglib.mlpebagginglm(), and alglib.testmlpeunit.testmlpe().
mlpebagginglbfgs()
static void alglib.mlpe.mlpebagginglbfgs (mlpensemble ensemble, double xy[,], int npoints, double decay, int restarts, double wstep, int maxits, ref int info, mlptrain.mlpreport rep, mlptrain.mlpcvreport ooberrors) inline static
Referenced by alglib.mlpebagginglbfgs(), and alglib.testmlpeunit.testmlpe().
mlpetraines()
static void alglib.mlpe.mlpetraines (mlpensemble ensemble, double xy[,], int npoints, double decay, int restarts, ref int info, mlptrain.mlpreport rep) inline static
Referenced by alglib.mlpetraines().
mlpealloc() [1/2]
static void alglib.mlpe.mlpealloc (alglib.serializer s, mlpensemble ensemble) inline static
Referenced by alglib.mlpeserialize(), and alglib.testmlpeunit.testprocessing().
mlpeserialize() [1/2]
static void alglib.mlpe.mlpeserialize (alglib.serializer s, mlpensemble ensemble) inline static
Referenced by alglib.mlpeserialize(), and alglib.testmlpeunit.testprocessing().
mlpeunserialize() [1/2]
static void alglib.mlpe.mlpeunserialize (alglib.serializer s, mlpensemble ensemble) inline static
Referenced by alglib.mlpeunserialize(), and alglib.testmlpeunit.testprocessing().
mlpeallerrors()
static void alglib.mlpe.mlpeallerrors (mlpensemble ensemble, double xy[,], int npoints, ref double relcls, ref double avgce, ref double rms, ref double avg, ref double avgrel) inline static private
mlpebagginginternal()
static void alglib.mlpe.mlpebagginginternal (mlpensemble ensemble, double xy[,], int npoints, double decay, int restarts, double wstep, int maxits, bool lmalgorithm, ref int info, mlptrain.mlpreport rep, mlptrain.mlpcvreport ooberrors) inline static private
mlpecreate0() [2/2]
static void alglib.mlpe.mlpecreate0 (int nin, int nout, int ensemblesize, mlpensemble ensemble) inline static
mlpecreate1() [2/2]
static void alglib.mlpe.mlpecreate1 (int nin, int nhid, int nout, int ensemblesize, mlpensemble ensemble) inline static
mlpecreate2() [2/2]
static void alglib.mlpe.mlpecreate2 (int nin, int nhid1, int nhid2, int nout, int ensemblesize, mlpensemble ensemble) inline static
mlpecreateb0() [2/2]
static void alglib.mlpe.mlpecreateb0 (int nin, int nout, double b, double d, int ensemblesize, mlpensemble ensemble) inline static
mlpecreateb1() [2/2]
static void alglib.mlpe.mlpecreateb1 (int nin, int nhid, int nout, double b, double d, int ensemblesize, mlpensemble ensemble) inline static
mlpecreateb2() [2/2]
static void alglib.mlpe.mlpecreateb2 (int nin, int nhid1, int nhid2, int nout, double b, double d, int ensemblesize, mlpensemble ensemble) inline static
mlpecreater0() [2/2]
static void alglib.mlpe.mlpecreater0 (int nin, int nout, double a, double b, int ensemblesize, mlpensemble ensemble) inline static
mlpecreater1() [2/2]
static void alglib.mlpe.mlpecreater1 (int nin, int nhid, int nout, double a, double b, int ensemblesize, mlpensemble ensemble) inline static
mlpecreater2() [2/2]
static void alglib.mlpe.mlpecreater2 (int nin, int nhid1, int nhid2, int nout, double a, double b, int ensemblesize, mlpensemble ensemble) inline static
mlpecreatec0() [2/2]
static void alglib.mlpe.mlpecreatec0 (int nin, int nout, int ensemblesize, mlpensemble ensemble) inline static
mlpecreatec1() [2/2]
static void alglib.mlpe.mlpecreatec1 (int nin, int nhid, int nout, int ensemblesize, mlpensemble ensemble) inline static
mlpecreatec2() [2/2]
static void alglib.mlpe.mlpecreatec2 (int nin, int nhid1, int nhid2, int nout, int ensemblesize, mlpensemble ensemble) inline static
mlpecreatefromnetwork() [2/2]
static void alglib.mlpe.mlpecreatefromnetwork (mlpbase.multilayerperceptron network, int ensemblesize, mlpensemble ensemble) inline static
mlpecopy() [2/2]
static void alglib.mlpe.mlpecopy (mlpensemble ensemble1, mlpensemble ensemble2) inline static
mlperandomize() [2/2]
static void alglib.mlpe.mlperandomize (mlpensemble ensemble) inline static
mlpeproperties() [2/2]
static void alglib.mlpe.mlpeproperties (mlpensemble ensemble, ref int nin, ref int nout) inline static
mlpeissoftmax() [2/2]
static bool alglib.mlpe.mlpeissoftmax (mlpensemble ensemble) inline static
mlpeprocess() [2/2]
static void alglib.mlpe.mlpeprocess (mlpensemble ensemble, double[] x, ref double[] y) inline static
mlpeprocessi() [2/2]
static void alglib.mlpe.mlpeprocessi (mlpensemble ensemble, double[] x, ref double[] y) inline static
mlpeallerrorsx()
static void alglib.mlpe.mlpeallerrorsx (mlpensemble ensemble, double densexy[,], sparse.sparsematrix sparsexy, int datasetsize, int datasettype, int[] idx, int subset0, int subset1, int subsettype, alglib.smp.shared_pool buf, mlpbase.modelerrors rep) inline static
Referenced by alglib.testmlptrainunit.testmlptrainensregr().
mlpeallerrorssparse()
static void alglib.mlpe.mlpeallerrorssparse (mlpensemble ensemble, sparse.sparsematrix xy, int npoints, ref double relcls, ref double avgce, ref double rms, ref double avg, ref double avgrel) inline static
mlperelclserror() [2/2]
static double alglib.mlpe.mlperelclserror (mlpensemble ensemble, double xy[,], int npoints) inline static
mlpeavgce() [2/2]
static double alglib.mlpe.mlpeavgce (mlpensemble ensemble, double xy[,], int npoints) inline static
mlpermserror() [2/2]
static double alglib.mlpe.mlpermserror (mlpensemble ensemble, double xy[,], int npoints) inline static
mlpeavgerror() [2/2]
static double alglib.mlpe.mlpeavgerror (mlpensemble ensemble, double xy[,], int npoints) inline static
mlpeavgrelerror() [2/2]
static double alglib.mlpe.mlpeavgrelerror (mlpensemble ensemble, double xy[,], int npoints) inline static
mlpealloc() [2/2]
static void alglib.mlpe.mlpealloc (alglib.serializer s, mlpensemble ensemble) inline static
mlpeserialize() [2/2]
static void alglib.mlpe.mlpeserialize (alglib.serializer s, mlpensemble ensemble) inline static
mlpeunserialize() [2/2]
static void alglib.mlpe.mlpeunserialize (alglib.serializer s, mlpensemble ensemble) inline static
Member Data Documentation
mlpntotaloffset
const int alglib.mlpe.mlpntotaloffset = 3 static
mlpevnum
const int alglib.mlpe.mlpevnum = 9 static
mlpefirstversion
const int alglib.mlpe.mlpefirstversion = 1 static
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/dataanalysis.cs