Doc: IGLib EXTENDED: alglib.testspline3dunit Class Reference
alglib.testspline3dunit Class Reference
Static Public Member Functions
static bool testspline3d (bool silence)
static bool testspline3d (bool silence)
static bool _pexec_testspline3d (bool silence)
Static Private Member Functions
static bool basictest ()
static bool testunpack ()
static bool testlintrans ()
static bool testtrilinearresample ()
static void buildrndgrid (bool isvect, bool reorder, ref int n, ref int m, ref int l, ref int d, ref double[] x, ref double[] y, ref double[] z, ref double[] f)
static bool basictest ()
static bool testunpack ()
static bool testlintrans ()
static bool testtrilinearresample ()
static void buildrndgrid (bool isvect, bool reorder, ref int n, ref int m, ref int l, ref int d, ref double[] x, ref double[] y, ref double[] z, ref double[] f)
Member Function Documentation
testspline3d() [1/2]
static bool alglib.testspline3dunit.testspline3d (bool silence) inline static
References alglib.testspline3dunit.basictest(), alglib.testspline3dunit.testlintrans(), alglib.testspline3dunit.testtrilinearresample(), and alglib.testspline3dunit.testunpack().
Referenced by alglib.testspline3dunit._pexec_testspline3d(), and _Test.Main().
basictest() [1/2]
static bool alglib.testspline3dunit.basictest () inline static private
References alglib.testspline3dunit.buildrndgrid(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.apserv.rvectorsetlengthatleast(), alglib.spline3d.spline3dbuildtrilinearv(), alglib.spline3d.spline3dcalc(), and alglib.spline3d.spline3dcalcv().
Referenced by alglib.testspline3dunit.testspline3d().
testunpack() [1/2]
static bool alglib.testspline3dunit.testunpack () inline static private
References alglib.testspline3dunit.buildrndgrid(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.apserv.rvectorsetlengthatleast(), alglib.spline3d.spline3dbuildtrilinearv(), alglib.spline3d.spline3dcalc(), and alglib.spline3d.spline3dunpackv().
Referenced by alglib.testspline3dunit.testspline3d().
testlintrans() [1/2]
static bool alglib.testspline3dunit.testlintrans () inline static private
References alglib.testspline3dunit.buildrndgrid(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.spline3d.spline3dbuildtrilinearv(), alglib.spline3d.spline3dcalcv(), alglib.spline3d.spline3dcopy(), alglib.spline3d.spline3dlintransf(), and alglib.spline3d.spline3dlintransxyz().
Referenced by alglib.testspline3dunit.testspline3d().
testtrilinearresample() [1/2]
static bool alglib.testspline3dunit.testtrilinearresample () inline static private
References alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.apserv.rvectorsetlengthatleast(), alglib.spline3d.spline3dbuildtrilinearv(), alglib.spline3d.spline3dcalc(), and alglib.spline3d.spline3dresampletrilinear().
Referenced by alglib.testspline3dunit.testspline3d().
buildrndgrid() [1/2]
static void alglib.testspline3dunit.buildrndgrid (bool isvect, bool reorder, ref int n, ref int m, ref int l, ref int d, ref double[] x, ref double[] y, ref double[] z, ref double[] f) inline static private
References alglib.math.randominteger(), alglib.math.randomreal(), and alglib.apserv.rvectorsetlengthatleast().
Referenced by alglib.testspline3dunit.basictest(), alglib.testspline3dunit.testlintrans(), and alglib.testspline3dunit.testunpack().
testspline3d() [2/2]
static bool alglib.testspline3dunit.testspline3d (bool silence) inline static
References alglib.testspline3dunit.basictest(), alglib.testspline3dunit.testlintrans(), alglib.testspline3dunit.testtrilinearresample(), and alglib.testspline3dunit.testunpack().
_pexec_testspline3d()
static bool alglib.testspline3dunit._pexec_testspline3d (bool silence) inline static
References alglib.testspline3dunit.testspline3d().
Referenced by _Test.Main().
basictest() [2/2]
static bool alglib.testspline3dunit.basictest () inline static private
References alglib.testspline3dunit.buildrndgrid(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.apserv.rvectorsetlengthatleast(), alglib.spline3d.spline3dbuildtrilinearv(), alglib.spline3d.spline3dcalc(), and alglib.spline3d.spline3dcalcv().
testunpack() [2/2]
static bool alglib.testspline3dunit.testunpack () inline static private
References alglib.testspline3dunit.buildrndgrid(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.apserv.rvectorsetlengthatleast(), alglib.spline3d.spline3dbuildtrilinearv(), alglib.spline3d.spline3dcalc(), and alglib.spline3d.spline3dunpackv().
testlintrans() [2/2]
static bool alglib.testspline3dunit.testlintrans () inline static private
References alglib.testspline3dunit.buildrndgrid(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.spline3d.spline3dbuildtrilinearv(), alglib.spline3d.spline3dcalcv(), alglib.spline3d.spline3dcopy(), alglib.spline3d.spline3dlintransf(), and alglib.spline3d.spline3dlintransxyz().
testtrilinearresample() [2/2]
static bool alglib.testspline3dunit.testtrilinearresample () inline static private
References alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.apserv.rvectorsetlengthatleast(), alglib.spline3d.spline3dbuildtrilinearv(), alglib.spline3d.spline3dcalc(), and alglib.spline3d.spline3dresampletrilinear().
buildrndgrid() [2/2]
static void alglib.testspline3dunit.buildrndgrid (bool isvect, bool reorder, ref int n, ref int m, ref int l, ref int d, ref double[] x, ref double[] y, ref double[] z, ref double[] f) inline static private
References alglib.math.randominteger(), alglib.math.randomreal(), and alglib.apserv.rvectorsetlengthatleast().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs