Doc: IGLib EXTENDED: alglib.pspline Class Reference
alglib.pspline Class Reference
Classes
class pspline2interpolant
class pspline3interpolant
Static Public Member Functions
static void pspline2build (double[,] xy, int n, int st, int pt, pspline2interpolant p)
static void pspline3build (double[,] xy, int n, int st, int pt, pspline3interpolant p)
static void pspline2buildperiodic (double[,] xy, int n, int st, int pt, pspline2interpolant p)
static void pspline3buildperiodic (double[,] xy, int n, int st, int pt, pspline3interpolant p)
static void pspline2parametervalues (pspline2interpolant p, ref int n, ref double[] t)
static void pspline3parametervalues (pspline3interpolant p, ref int n, ref double[] t)
static void pspline2calc (pspline2interpolant p, double t, ref double x, ref double y)
static void pspline3calc (pspline3interpolant p, double t, ref double x, ref double y, ref double z)
static void pspline2tangent (pspline2interpolant p, double t, ref double x, ref double y)
static void pspline3tangent (pspline3interpolant p, double t, ref double x, ref double y, ref double z)
static void pspline2diff (pspline2interpolant p, double t, ref double x, ref double dx, ref double y, ref double dy)
static void pspline3diff (pspline3interpolant p, double t, ref double x, ref double dx, ref double y, ref double dy, ref double z, ref double dz)
static void pspline2diff2 (pspline2interpolant p, double t, ref double x, ref double dx, ref double d2x, ref double y, ref double dy, ref double d2y)
static void pspline3diff2 (pspline3interpolant p, double t, ref double x, ref double dx, ref double d2x, ref double y, ref double dy, ref double d2y, ref double z, ref double dz, ref double d2z)
static double pspline2arclength (pspline2interpolant p, double a, double b)
static double pspline3arclength (pspline3interpolant p, double a, double b)
static void pspline2build (double[,] xy, int n, int st, int pt, pspline2interpolant p)
static void pspline3build (double[,] xy, int n, int st, int pt, pspline3interpolant p)
static void pspline2buildperiodic (double[,] xy, int n, int st, int pt, pspline2interpolant p)
static void pspline3buildperiodic (double[,] xy, int n, int st, int pt, pspline3interpolant p)
static void pspline2parametervalues (pspline2interpolant p, ref int n, ref double[] t)
static void pspline3parametervalues (pspline3interpolant p, ref int n, ref double[] t)
static void pspline2calc (pspline2interpolant p, double t, ref double x, ref double y)
static void pspline3calc (pspline3interpolant p, double t, ref double x, ref double y, ref double z)
static void pspline2tangent (pspline2interpolant p, double t, ref double x, ref double y)
static void pspline3tangent (pspline3interpolant p, double t, ref double x, ref double y, ref double z)
static void pspline2diff (pspline2interpolant p, double t, ref double x, ref double dx, ref double y, ref double dy)
static void pspline3diff (pspline3interpolant p, double t, ref double x, ref double dx, ref double y, ref double dy, ref double z, ref double dz)
static void pspline2diff2 (pspline2interpolant p, double t, ref double x, ref double dx, ref double d2x, ref double y, ref double dy, ref double d2y)
static void pspline3diff2 (pspline3interpolant p, double t, ref double x, ref double dx, ref double d2x, ref double y, ref double dy, ref double d2y, ref double z, ref double dz, ref double d2z)
static double pspline2arclength (pspline2interpolant p, double a, double b)
static double pspline3arclength (pspline3interpolant p, double a, double b)
Static Private Member Functions
static void pspline2par (double[,] xy, int n, int pt, ref double[] p)
static void pspline3par (double[,] xy, int n, int pt, ref double[] p)
static void pspline2par (double[,] xy, int n, int pt, ref double[] p)
static void pspline3par (double[,] xy, int n, int pt, ref double[] p)
Member Function Documentation
pspline2build() [1/2]
static void alglib.pspline.pspline2build (double xy[,], int n, int st, int pt, pspline2interpolant p) inline static
Referenced by alglib.pspline2build(), alglib.testpsplineunit.testpspline(), and alglib.testpsplineunit.unsetp2().
pspline3build() [1/2]
static void alglib.pspline.pspline3build (double xy[,], int n, int st, int pt, pspline3interpolant p) inline static
Referenced by alglib.pspline3build(), alglib.testpsplineunit.testpspline(), and alglib.testpsplineunit.unsetp3().
pspline2buildperiodic() [1/2]
static void alglib.pspline.pspline2buildperiodic (double xy[,], int n, int st, int pt, pspline2interpolant p) inline static
Referenced by alglib.pspline2buildperiodic(), and alglib.testpsplineunit.testpspline().
pspline3buildperiodic() [1/2]
static void alglib.pspline.pspline3buildperiodic (double xy[,], int n, int st, int pt, pspline3interpolant p) inline static
Referenced by alglib.pspline3buildperiodic(), and alglib.testpsplineunit.testpspline().
pspline2parametervalues() [1/2]
static void alglib.pspline.pspline2parametervalues (pspline2interpolant p, ref int n, ref double[] t) inline static
Referenced by alglib.pspline2parametervalues(), and alglib.testpsplineunit.testpspline().
pspline3parametervalues() [1/2]
static void alglib.pspline.pspline3parametervalues (pspline3interpolant p, ref int n, ref double[] t) inline static
Referenced by alglib.pspline3parametervalues(), and alglib.testpsplineunit.testpspline().
pspline2calc() [1/2]
static void alglib.pspline.pspline2calc (pspline2interpolant p, double t, ref double x, ref double y) inline static
Referenced by alglib.pspline2calc(), and alglib.testpsplineunit.testpspline().
pspline3calc() [1/2]
static void alglib.pspline.pspline3calc (pspline3interpolant p, double t, ref double x, ref double y, ref double z) inline static
Referenced by alglib.pspline3calc(), and alglib.testpsplineunit.testpspline().
pspline2tangent() [1/2]
static void alglib.pspline.pspline2tangent (pspline2interpolant p, double t, ref double x, ref double y) inline static
Referenced by alglib.pspline2tangent(), and alglib.testpsplineunit.testpspline().
pspline3tangent() [1/2]
static void alglib.pspline.pspline3tangent (pspline3interpolant p, double t, ref double x, ref double y, ref double z) inline static
Referenced by alglib.pspline3tangent(), and alglib.testpsplineunit.testpspline().
pspline2diff() [1/2]
static void alglib.pspline.pspline2diff (pspline2interpolant p, double t, ref double x, ref double dx, ref double y, ref double dy) inline static
Referenced by alglib.pspline2diff(), and alglib.testpsplineunit.testpspline().
pspline3diff() [1/2]
static void alglib.pspline.pspline3diff (pspline3interpolant p, double t, ref double x, ref double dx, ref double y, ref double dy, ref double z, ref double dz) inline static
Referenced by alglib.pspline3diff(), and alglib.testpsplineunit.testpspline().
pspline2diff2() [1/2]
static void alglib.pspline.pspline2diff2 (pspline2interpolant p, double t, ref double x, ref double dx, ref double d2x, ref double y, ref double dy, ref double d2y) inline static
Referenced by alglib.pspline2diff2(), and alglib.testpsplineunit.testpspline().
pspline3diff2() [1/2]
static void alglib.pspline.pspline3diff2 (pspline3interpolant p, double t, ref double x, ref double dx, ref double d2x, ref double y, ref double dy, ref double d2y, ref double z, ref double dz, ref double d2z) inline static
Referenced by alglib.pspline3diff2(), and alglib.testpsplineunit.testpspline().
pspline2arclength() [1/2]
static double alglib.pspline.pspline2arclength (pspline2interpolant p, double a, double b) inline static
Referenced by alglib.pspline2arclength(), and alglib.testpsplineunit.testpspline().
pspline3arclength() [1/2]
static double alglib.pspline.pspline3arclength (pspline3interpolant p, double a, double b) inline static
Referenced by alglib.pspline3arclength(), and alglib.testpsplineunit.testpspline().
pspline2par() [1/2]
static void alglib.pspline.pspline2par (double xy[,], int n, int pt, ref double[] p) inline static private
pspline3par() [1/2]
static void alglib.pspline.pspline3par (double xy[,], int n, int pt, ref double[] p) inline static private
pspline2build() [2/2]
static void alglib.pspline.pspline2build (double xy[,], int n, int st, int pt, pspline2interpolant p) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.spline1dbuildakima(), alglib.spline1d.spline1dbuildcatmullrom(), and alglib.spline1d.spline1dbuildcubic().
pspline3build() [2/2]
static void alglib.pspline.pspline3build (double xy[,], int n, int st, int pt, pspline3interpolant p) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.spline1dbuildakima(), alglib.spline1d.spline1dbuildcatmullrom(), and alglib.spline1d.spline1dbuildcubic().
pspline2buildperiodic() [2/2]
static void alglib.pspline.pspline2buildperiodic (double xy[,], int n, int st, int pt, pspline2interpolant p) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.spline1dbuildcatmullrom(), and alglib.spline1d.spline1dbuildcubic().
pspline3buildperiodic() [2/2]
static void alglib.pspline.pspline3buildperiodic (double xy[,], int n, int st, int pt, pspline3interpolant p) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.spline1d.spline1dbuildcatmullrom(), and alglib.spline1d.spline1dbuildcubic().
pspline2parametervalues() [2/2]
static void alglib.pspline.pspline2parametervalues (pspline2interpolant p, ref int n, ref double[] t) inline static
References alglib.ap.assert().
pspline3parametervalues() [2/2]
static void alglib.pspline.pspline3parametervalues (pspline3interpolant p, ref int n, ref double[] t) inline static
References alglib.ap.assert().
pspline2calc() [2/2]
static void alglib.pspline.pspline2calc (pspline2interpolant p, double t, ref double x, ref double y) inline static
References alglib.spline1d.spline1dcalc().
pspline3calc() [2/2]
static void alglib.pspline.pspline3calc (pspline3interpolant p, double t, ref double x, ref double y, ref double z) inline static
References alglib.spline1d.spline1dcalc().
pspline2tangent() [2/2]
static void alglib.pspline.pspline2tangent (pspline2interpolant p, double t, ref double x, ref double y) inline static
References alglib.apserv.safepythag2().
pspline3tangent() [2/2]
static void alglib.pspline.pspline3tangent (pspline3interpolant p, double t, ref double x, ref double y, ref double z) inline static
References alglib.apserv.safepythag3().
pspline2diff() [2/2]
static void alglib.pspline.pspline2diff (pspline2interpolant p, double t, ref double x, ref double dx, ref double y, ref double dy) inline static
References alglib.spline1d.spline1ddiff().
pspline3diff() [2/2]
static void alglib.pspline.pspline3diff (pspline3interpolant p, double t, ref double x, ref double dx, ref double y, ref double dy, ref double z, ref double dz) inline static
References alglib.spline1d.spline1ddiff().
pspline2diff2() [2/2]
static void alglib.pspline.pspline2diff2 (pspline2interpolant p, double t, ref double x, ref double dx, ref double d2x, ref double y, ref double dy, ref double d2y) inline static
References alglib.spline1d.spline1ddiff().
pspline3diff2() [2/2]
static void alglib.pspline.pspline3diff2 (pspline3interpolant p, double t, ref double x, ref double dx, ref double d2x, ref double y, ref double dy, ref double d2y, ref double z, ref double dz, ref double d2z) inline static
References alglib.spline1d.spline1ddiff().
pspline2arclength() [2/2]
static double alglib.pspline.pspline2arclength (pspline2interpolant p, double a, double b) inline static
References alglib.ap.assert(), alglib.autogk.autogkiteration(), alglib.autogk.autogkresults(), alglib.autogk.autogksmooth(), alglib.apserv.safepythag2(), and alglib.spline1d.spline1ddiff().
pspline3arclength() [2/2]
static double alglib.pspline.pspline3arclength (pspline3interpolant p, double a, double b) inline static
References alglib.ap.assert(), alglib.autogk.autogkiteration(), alglib.autogk.autogkresults(), alglib.autogk.autogksmooth(), alglib.apserv.safepythag3(), and alglib.spline1d.spline1ddiff().
pspline2par() [2/2]
static void alglib.pspline.pspline2par (double xy[,], int n, int pt, ref double[] p) inline static private
References alglib.ap.assert(), and alglib.apserv.safepythag2().
pspline3par() [2/2]
static void alglib.pspline.pspline3par (double xy[,], int n, int pt, ref double[] p) inline static private
References alglib.ap.assert(), and alglib.apserv.safepythag3().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/interpolation.cs