Doc: IGLib EXTENDED: NUnit.Framework.Constraints.ComparisonConstraint Class Reference
NUnit.Framework.Constraints.ComparisonConstraint Class Reference
Abstract base class for constraints that compare _values to determine if one is greater than, equal to or less than the other.
Public Member Functions
override ConstraintResult ApplyTo< TActual > (TActual actual)
Test whether the constraint is satisfied by a given value
ComparisonConstraint Using (IComparer comparer)
Modifies the constraint to use an IComparer and returns self
ComparisonConstraint Using< T > (IComparer< T > comparer)
Modifies the constraint to use an IComparer<T> and returns self
ComparisonConstraint Using< T > (Comparison< T > comparer)
Modifies the constraint to use a Comparison<T> and returns self
Public Member Functions inherited from NUnit.Framework.Constraints.Constraint
virtual ConstraintResult ApplyTo< TActual > (ActualValueDelegate< TActual > del)
Applies the constraint to an ActualValueDelegate that returns the value to be tested. The default implementation simply evaluates the delegate but derived classes may override it to provide for delayed processing.
virtual ConstraintResult ApplyTo< TActual > (ref TActual actual)
Test whether the constraint is satisfied by a given reference. The default implementation simply dereferences the value but derived classes may override it to provide for delayed processing.
override string ToString ()
Default override of ToString returns the constraint DisplayName followed by any arguments within angle brackets.
DelayedConstraint After (int delayInMilliseconds)
Returns a DelayedConstraint with the specified delay time.
DelayedConstraint After (int delayInMilliseconds, int pollingInterval)
Returns a DelayedConstraint with the specified delay time and polling interval.
Protected Member Functions
ComparisonConstraint (object value, bool lessComparisonResult, bool equalComparisonResult, bool greaterComparisonResult, string predicate)
Initializes a new instance of the ComparisonConstraint class.
Protected Member Functions inherited from NUnit.Framework.Constraints.Constraint
Constraint (params object[] args)
Construct a constraint with optional arguments
virtual string GetStringRepresentation ()
Returns the string representation of this constraint
Protected Attributes
object expected
The value against which a comparison is to be made
bool lessComparisonResult = false
If true, less than returns success
bool equalComparisonResult = false
if true, equal returns success
bool greaterComparisonResult = false
if true, greater than returns success
Private Attributes
ComparisonAdapter comparer = ComparisonAdapter.Default
ComparisonAdapter to be used in making the comparison
Additional Inherited Members
Static Public Member Functions inherited from NUnit.Framework.Constraints.Constraint
static Constraint operator& (Constraint left, Constraint right)
This operator creates a constraint that is satisfied only if both argument constraints are satisfied.
static Constraint operator| (Constraint left, Constraint right)
This operator creates a constraint that is satisfied if either of the argument constraints is satisfied.
static Constraint operator! (Constraint constraint)
This operator creates a constraint that is satisfied if the argument constraint is not satisfied.
Properties inherited from NUnit.Framework.Constraints.Constraint
string DisplayName [get, protected set]
The display name of this Constraint for use by ToString(). The default value is the name of the constraint with trailing "Constraint" removed. Derived classes may set this to another name in their constructors.
virtual string Description [get, protected set]
The Description of what this constraint tests, for use in messages and in the ConstraintResult.
object[] Arguments [get, private set]
Arguments provided to this Constraint, for use in formatting the description.
ConstraintBuilder Builder [get, set]
The ConstraintBuilder holding this constraint
ConstraintExpression And [get]
Returns a ConstraintExpression by appending And to the current constraint.
ConstraintExpression With [get]
Returns a ConstraintExpression by appending And to the current constraint.
ConstraintExpression Or [get]
Returns a ConstraintExpression by appending Or to the current constraint.
Properties inherited from NUnit.Framework.Constraints.IConstraint
string DisplayName [get]
The display name of this Constraint for use by ToString().
string Description [get]
The Description of what this constraint tests, for use in messages and in the ConstraintResult.
object[] Arguments [get]
Arguments provided to this Constraint, for use in formatting the description.
ConstraintBuilder Builder [get, set]
The ConstraintBuilder holding this constraint
Detailed Description
Abstract base class for constraints that compare _values to determine if one is greater than, equal to or less than the other.
Constructor & Destructor Documentation
ComparisonConstraint()
NUnit.Framework.Constraints.ComparisonConstraint.ComparisonConstraint (object value, bool lessComparisonResult, bool equalComparisonResult, bool greaterComparisonResult, string predicate) inline protected
Initializes a new instance of the ComparisonConstraint class.
Parameters
value The value against which to make a comparison.
lessComparisonResult if set to true less succeeds.
equalComparisonResult if set to true equal succeeds.
greaterComparisonResult if set to true greater succeeds.
predicate String used in describing the constraint.
References NUnit.Framework.Constraints.Constraint.Description, NUnit.Framework.Constraints.ComparisonConstraint.equalComparisonResult, NUnit.Framework.Constraints.ComparisonConstraint.expected, NUnit.Framework.Constraints.ComparisonConstraint.greaterComparisonResult, and NUnit.Framework.Constraints.ComparisonConstraint.lessComparisonResult.
Member Function Documentation
ApplyTo< TActual >()
override ConstraintResult NUnit.Framework.Constraints.ComparisonConstraint.ApplyTo< TActual > (TActual actual) inline virtual
Test whether the constraint is satisfied by a given value
Parameters
actual The value to be tested
Returns
True for success, false for failure
Implements NUnit.Framework.Constraints.Constraint.
References NUnit.Framework.Constraints.ComparisonAdapter.Compare(), NUnit.Framework.Constraints.ComparisonConstraint.comparer, NUnit.Framework.Constraints.ComparisonConstraint.expected, and NUnit.Framework.Constraints.ComparisonConstraint.lessComparisonResult.
Using()
ComparisonConstraint NUnit.Framework.Constraints.ComparisonConstraint.Using (IComparer comparer) inline
Modifies the constraint to use an IComparer and returns self
Parameters
comparer The comparer used for comparison tests
Returns
A constraint modified to use the given comparer
References NUnit.Framework.Constraints.ComparisonConstraint.comparer, and NUnit.Framework.Constraints.ComparisonAdapter.For().
Referenced by NUnit.Framework.Constraints.ComparisonConstraintTestBase.UsesProvidedGenericComparer(), NUnit.Framework.Constraints.ComparisonConstraintTestBase.UsesProvidedGenericComparison(), NUnit.Framework.Constraints.ComparisonConstraintTestBase.UsesProvidedIComparer(), and NUnit.Framework.Constraints.ComparisonConstraintTestBase.UsesProvidedLambda().
Using< T >() [1/2]
ComparisonConstraint NUnit.Framework.Constraints.ComparisonConstraint.Using< T > (IComparer< T > comparer) inline
Modifies the constraint to use an IComparer<T> and returns self
Parameters
comparer The comparer used for comparison tests
Returns
A constraint modified to use the given comparer
References NUnit.Framework.Constraints.ComparisonConstraint.comparer, and NUnit.Framework.Constraints.ComparisonAdapter.For().
Using< T >() [2/2]
ComparisonConstraint NUnit.Framework.Constraints.ComparisonConstraint.Using< T > (Comparison< T > comparer) inline
Modifies the constraint to use a Comparison<T> and returns self
Parameters
comparer The comparer used for comparison tests
Returns
A constraint modified to use the given comparer
References NUnit.Framework.Constraints.ComparisonConstraint.comparer, and NUnit.Framework.Constraints.ComparisonAdapter.For().
Member Data Documentation
expected
object NUnit.Framework.Constraints.ComparisonConstraint.expected protected
The value against which a comparison is to be made
Referenced by NUnit.Framework.Constraints.ComparisonConstraint.ApplyTo< TActual >(), and NUnit.Framework.Constraints.ComparisonConstraint.ComparisonConstraint().
lessComparisonResult
bool NUnit.Framework.Constraints.ComparisonConstraint.lessComparisonResult = false protected
If true, less than returns success
Referenced by NUnit.Framework.Constraints.ComparisonConstraint.ApplyTo< TActual >(), and NUnit.Framework.Constraints.ComparisonConstraint.ComparisonConstraint().
equalComparisonResult
bool NUnit.Framework.Constraints.ComparisonConstraint.equalComparisonResult = false protected
if true, equal returns success
Referenced by NUnit.Framework.Constraints.ComparisonConstraint.ComparisonConstraint().
greaterComparisonResult
bool NUnit.Framework.Constraints.ComparisonConstraint.greaterComparisonResult = false protected
if true, greater than returns success
Referenced by NUnit.Framework.Constraints.ComparisonConstraint.ComparisonConstraint().
comparer
ComparisonAdapter NUnit.Framework.Constraints.ComparisonConstraint.comparer = ComparisonAdapter.Default private
ComparisonAdapter to be used in making the comparison
Referenced by NUnit.Framework.Constraints.ComparisonConstraint.ApplyTo< TActual >(), NUnit.Framework.Constraints.ComparisonConstraint.Using(), and NUnit.Framework.Constraints.ComparisonConstraint.Using< T >().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Constraints/ComparisonConstraint.cs