Doc: IGLib EXTENDED: TestOpt.IGLibShellExtMainProgram Class Reference
TestOpt.IGLibShellExtMainProgram Class Reference
Class containing the main method of application.
Classes
class IGLibShellExtApp
Application class for the current application (IGLib Extended Shell Application, igsx).
Public Member Functions
IGLibShellExtMainProgram ()
override void AddDefaultAssemblies ()
Adds assemblies to be automatically referenced by loaded scripts.
override void AplicationMain (string[] args)
Default main method for the current application.
override void TestMain (string[] args)
Runs tests from scripts according to hard-coded settings.
Public Member Functions inherited from IG.Lib.ApplicationCommandlineBase
ApplicationCommandlineBase ()
Constructor.
Public Attributes
string OptDir
Optimization directory that contains data and message files of optimization server.
Public Attributes inherited from IG.Lib.ApplicationCommandlineBase
string OptDir
Optimization directory that contains data and message files of optimization server.
Protected Member Functions
override CommandLineApplicationInterpreter CreateInterpreter ()
Creates and returns application's command-line interpreter.
Protected Member Functions inherited from IG.Lib.ApplicationCommandlineBase
virtual void SetUserName (string userName)
Sets name of the current user. This method is provided to enable testing code under another user name. Setting to null anihilates effect of previous calls.
int GetScriptNumArguments ()
Returns the number of script run method's arguments (i.e. arguments that are stored in DirectArguments and InterpreterArguments). If there are different numbers of
virtual void SetScriptNumArguments (int numArguments)
Sets the number of script run method's arguments to the specified number. Reallocates argument arrays if necessary.
virtual void SetScriptArgument (int whichArgument, string argumentValue)
Sets the specified script argument; updates array of arguments for running script directly as well as arguments for running script through interpreter.
virtual string GetScriptArgument (int whichArgument)
Gets the specified string arguments, as it is currently set.
Static Private Member Functions
static void Main (string[] args)
Entry point of the application.
Additional Inherited Members
Protected Attributes inherited from IG.Lib.ApplicationCommandlineBase
string ConstRunInteractive = "Interactive"
Interpreter command for running in interactive mode.
string ConstRunScript = "RunScript"
Interpreter command for running dynamic scripts.
string ScriptLocation = null
Location of the script to be loaded.
string ScriptGroupChoice
Main selector for script that is run.
string _scriptChoice
Type _scriptType
string ScriptAction
Selector for script action.
string[] DirectArguments = null
Script arguments used when script is run directly by creating a script object.
string[] InterpreterArguments = null
Interpreter arguments used when script is run through interpreter.
string DefaultActiveDir
Default active directory. The current directory will be set to this directory.
ILoadableScript _scriptToRun
bool RunThroughInterpreter = false
Whether script is loaded and run through interpreter (alternative is direct construction of script class).
string _userNameLowerCase = null
CommandLineApplicationInterpreter TestInterpreter
Application interpreter for running test scripts.
Static Protected Attributes inherited from IG.Lib.ApplicationCommandlineBase
const string ConstScriptTests = "ScriptTests"
Selecting constant fot TEST script.
const string ConstScriptCustomApp = "ScriptCustomApp"
Selecting constant fot CUSTOM script.
const string ConstInteractive = "Interactive"
Selecting constant for interactive run.
Properties inherited from IG.Lib.ApplicationCommandlineBase
string ScriptChoice [get, set]
Name of the selected script type that is run.
Type ScriptType [get, set]
Selected type of the script to be run.
ILoadableScript ScriptToRun [get, set]
Script to be run.
virtual string UserNameLowerCase [get]
Gets name of the current user with all letters converted to lower case (in order to avoid ambiguities).
virtual bool IsUserIgor [get]
Returns true if the current user logged on the computer is Igor, or false otherwise.
virtual bool IsUserTadej [get]
Returns true if the current user logged on the computer is Tadej, or false otherwise.
Detailed Description
Class containing the main method of application.
Standard scheme for IGLib-based test applications has been adopted in December 2011.
$A Igor xx Nov09 Dec11;
Constructor & Destructor Documentation
IGLibShellExtMainProgram()
TestOpt.IGLibShellExtMainProgram.IGLibShellExtMainProgram () inline
References IG.Lib.ApplicationCommandlineBase.DefaultActiveDir, and TestOpt.IGLibShellExtMainProgram.OptDir.
Referenced by TestOpt.IGLibShellExtMainProgram.Main().
Member Function Documentation
Main()
static void TestOpt.IGLibShellExtMainProgram.Main (string[] args) inline static private
Entry point of the application.
Parameters
args Application arguments.
References TestOpt.IGLibShellExtMainProgram.IGLibShellExtMainProgram().
CreateInterpreter()
override CommandLineApplicationInterpreter TestOpt.IGLibShellExtMainProgram.CreateInterpreter () inline protected virtual
Creates and returns application's command-line interpreter.
Implements IG.Lib.ApplicationCommandlineBase.
References IG.Lib.CommandLineApplicationInterpreter.RegisterSystemPriorityUpdating().
AddDefaultAssemblies()
override void TestOpt.IGLibShellExtMainProgram.AddDefaultAssemblies () inline virtual
Adds assemblies to be automatically referenced by loaded scripts.
Reimplemented from IG.Lib.ApplicationCommandlineBase.
References IG.Lib.ScriptLoaderBase.AddDefaultAssemblies().
AplicationMain()
override void TestOpt.IGLibShellExtMainProgram.AplicationMain (string[] args) inline virtual
Default main method for the current application.
Parameters
args Command-line argumets passed when the application is run.
Standard scheme for IGLib-based test applications has been adopted in December 2011.
$A Igor xx Nov09 Dec11;
Reimplemented from IG.Lib.ApplicationCommandlineBase.
References TestOpt.IGLibShellExtMainProgram.IGLibShellExtApp.Init(), and IG.Lib.Util.OutputLevel.
TestMain()
override void TestOpt.IGLibShellExtMainProgram.TestMain (string[] args) inline virtual
Runs tests from scripts according to hard-coded settings.
Standard form of test applications for functionality based on IGLib.
Parameters
args Command-line argumets passed when the application is run.
Standard scheme for IGLib-based test applications has been adopted in December 2011.
$A Igor xx Nov09 Dec11;
Implements IG.Lib.ApplicationCommandlineBase.
References IG.Script.ScriptOptTemplate.ConstAnotherTest, IG.Script.Scrip_OdeChem.ConstChemicalReactions, IG.Script.Script_Misc.ConstConsoleUtilities, IG.Script.Script_Examples.ConstCopyDir, IG.Script.Script_Numeric.ConstCustom, IG.Lib.LoadableScriptBase.ConstDefaultHelp, IG.Lib.LoadableScriptBase.ConstDefaultTestScrip, IG.Script.Script_Numeric.ConstDifferentiation, IG.Script.Script_Misc.ConstExpressionEvaluatorJavaScript, IG.Script.Script_Misc.ConstFileOperations, IG.Script.Script_Examples.ConstFunctionLoader, IG.Script.Script_Examples.ConstGraphics3d, IG.Lib.LoadableScriptBase.ConstHelpDefaultUniversal, IG.Lib.ApplicationCommandlineBase.ConstInteractive, IG.Script.Script_Numeric.ConstLinearApproximation, IG.Script.Script_Misc.ConstListOperations, IG.Script.Script_Numeric.ConstMatrixOperations, IG.Script.Script_Numeric.ConstMovingLeastSquares, IG.Script.ScriptOptTemplate.ConstMyTest, IG.Script.Script_Numeric.ConstOptAlgLib, IG.Script.Scrip_OdeChem.ConstOrdinaryDifferentialEquations, IG.Script.Script_Numeric.ConstParallelJobs, IG.Script.Script_Numeric.ConstPerformanceTests, IG.Script.Script_Examples.ConstPointClouds, IG.Script.Script_Numeric.ConstRealFunction, IG.Script.Script_Misc.ConstRegisterable_IdGenerator, IG.Lib.ApplicationCommandlineBase.ConstRunScript, IG.Script.Script_Numeric.ConstSampling, IG.Lib.ApplicationCommandlineBase.ConstScriptCustomApp, IG.Lib.ApplicationCommandlineBase.ConstScriptTests, IG.Script.Script_Misc.ConstSerializerJson, IG.Script.Script_Misc.ConstStringParser, IG.Script.Script_Numeric.ConstTabResults, IG.Script.Script_Numeric.ConstTestScriptArguments, IG.Script.Script_Optimization.ConstTestScriptArguments, IG.Script.Script_Examples.ConstWaitFileEvents, IG.Lib.ApplicationCommandlineBase.DefaultActiveDir, IG.Lib.LoadableScriptBase.DefaultOutputLevel, IG.Lib.ApplicationCommandlineBase.DirectArguments, IG.Lib.RealFunctionLoader.Example(), IG.Lib.ILoadableScript.InitializationArguments, IG.Lib.ApplicationCommandlineBase.InterpreterArguments, IG.Lib.CommandLineApplicationInterpreter.MainThread, TestOpt.IGLibShellExtMainProgram.OptDir, IG.Lib.ILoadableScript.Run(), IG.Lib.CommandLineApplicationInterpreter.Run(), IG.Lib.ApplicationCommandlineBase.RunThroughInterpreter, IG.Lib.ApplicationCommandlineBase.ScriptAction, IG.Lib.ApplicationCommandlineBase.ScriptChoice, IG.Lib.ApplicationCommandlineBase.ScriptGroupChoice, IG.Lib.ApplicationCommandlineBase.ScriptLocation, IG.Lib.ApplicationCommandlineBase.ScriptToRun, IG.Lib.ApplicationCommandlineBase.ScriptType, IG.Lib.ApplicationCommandlineBase.SetScriptArgument(), IG.Lib.ApplicationCommandlineBase.SetScriptNumArguments(), and IG.Lib.ApplicationCommandlineBase.TestInterpreter.
Member Data Documentation
OptDir
string TestOpt.IGLibShellExtMainProgram.OptDir
Optimization directory that contains data and message files of optimization server.
Referenced by TestOpt.IGLibShellExtMainProgram.IGLibShellExtMainProgram(), and TestOpt.IGLibShellExtMainProgram.TestMain().
The documentation for this class was generated from the following file:
igtest/IGLibTestShellExt/ProgIgLibShellExt.cs