Doc: IGLib EXTENDED: NeuronDotNet.Core.ILayer Interface Reference
NeuronDotNet.Core.ILayer Interface Reference
This interface represents a Layer in a neural network. A layer is a container for similar neurons. No two neurons within a layer can be connected to each other.
Public Member Functions
void Initialize ()
Initializes all neurons and makes them ready to undergo training freshly.
void SetLearningRate (double learningRate)
Sets the learning rate to the given value. The layer will use this constant value as learning rate throughout the learning process
void SetLearningRate (double initialLearningRate, double finalLearningRate)
Sets the initial and final values for learning rate. During the learning process, the effective learning rate uniformly changes from its initial value to final value
void SetLearningRate (ILearningRateFunction learningRateFunction)
Sets the learning rate function.
void SetInput (double[] input)
Sets neuron inputs to the values specified by the given array
double[] GetOutput ()
Gets the neuron outputs as an array
void Run ()
Runs all neurons in the layer.
void Learn (int currentIteration, int trainingEpochs)
All neurons and their are source connectors are allowed to learn. This method assumes a learning environment where inputs, outputs and other parameters (if any) are appropriate.
Properties
int NeuronCount [get]
Gets the neuron count
IEnumerable< INeuron > Neurons [get]
Exposes an enumerator to iterate over all neurons in the layer
INeuron this[int index] [get]
Neuron Indexer
IList< IConnector > SourceConnectors [get]
Gets the list of source connectors
IList< IConnector > TargetConnectors [get]
Gets the list of target connectors
IInitializer Initializer [get, set]
Gets or sets the Initializer used to initialize the layer
double LearningRate [get]
Gets the initial value of learning rate
ILearningRateFunction LearningRateFunction [get]
Gets the learning rate function
Detailed Description
This interface represents a Layer in a neural network. A layer is a container for similar neurons. No two neurons within a layer can be connected to each other.
Member Function Documentation
Initialize()
void NeuronDotNet.Core.ILayer.Initialize ()
Initializes all neurons and makes them ready to undergo training freshly.
Implemented in NeuronDotNet.Core.Layer< TNeuron >.
SetLearningRate() [1/3]
void NeuronDotNet.Core.ILayer.SetLearningRate (double learningRate)
Sets the learning rate to the given value. The layer will use this constant value as learning rate throughout the learning process
Parameters
learningRate The learning rate
Implemented in NeuronDotNet.Core.Layer< TNeuron >.
SetLearningRate() [2/3]
void NeuronDotNet.Core.ILayer.SetLearningRate (double initialLearningRate, double finalLearningRate)
Sets the initial and final values for learning rate. During the learning process, the effective learning rate uniformly changes from its initial value to final value
Parameters
initialLearningRate Initial value of learning rate
finalLearningRate Final value of learning rate
Implemented in NeuronDotNet.Core.Layer< TNeuron >.
SetLearningRate() [3/3]
void NeuronDotNet.Core.ILayer.SetLearningRate (ILearningRateFunction learningRateFunction)
Sets the learning rate function.
Parameters
learningRateFunction Learning rate function to use.
Exceptions
System.ArgumentNullException If learningRateFunction is null
Implemented in NeuronDotNet.Core.Layer< TNeuron >.
SetInput()
void NeuronDotNet.Core.ILayer.SetInput (double[] input)
Sets neuron inputs to the values specified by the given array
Parameters
input The input array
Exceptions
System.ArgumentNullException If input is null
System.ArgumentException If length of input array is different from number of neurons
Implemented in NeuronDotNet.Core.Layer< TNeuron >.
Referenced by NeuronDotNet.Core.SOM.KohonenNetwork.LearnSample(), NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.LearnSample(), and NeuronDotNet.Core.Network.Run().
GetOutput()
double [] NeuronDotNet.Core.ILayer.GetOutput ()
Gets the neuron outputs as an array
Returns
Array of double values representing neuron outputs
Implemented in NeuronDotNet.Core.Layer< TNeuron >.
Referenced by NeuronDotNet.Core.Network.Run().
Run()
void NeuronDotNet.Core.ILayer.Run ()
Runs all neurons in the layer.
Implemented in NeuronDotNet.Core.Layer< TNeuron >.
Referenced by NeuronDotNet.Core.SOM.KohonenNetwork.LearnSample().
Learn()
void NeuronDotNet.Core.ILayer.Learn (int currentIteration, int trainingEpochs)
All neurons and their are source connectors are allowed to learn. This method assumes a learning environment where inputs, outputs and other parameters (if any) are appropriate.
Parameters
currentIteration Current learning iteration
trainingEpochs Total number of training epochs
Exceptions
System.ArgumentException If trainingEpochs is zero or negative
System.ArgumentOutOfRangeException If currentIteration is negative or, if it is greater than trainingEpochs
Implemented in NeuronDotNet.Core.Layer< TNeuron >.
Referenced by NeuronDotNet.Core.SOM.KohonenNetwork.LearnSample().
Property Documentation
NeuronCount
int NeuronDotNet.Core.ILayer.NeuronCount get
Gets the neuron count
Number of neurons in the layer. It is always positive.
Referenced by NeuronDotNet.Core.Initializers.NguyenWidrowFunction.Initialize(), NeuronDotNet.Core.Network.Learn(), IG.Neural.NeuralApproximatorNeuron.MyNeuronBackPropagation.Learn(), and IG.Neural.NeuronBackPropagationLEarning.Learn().
Neurons
IEnumerable<INeuron> NeuronDotNet.Core.ILayer.Neurons get
Exposes an enumerator to iterate over all neurons in the layer
Neurons Enumerator. No neuron enumerated can be null.
this[int index]
INeuron NeuronDotNet.Core.ILayer.this[int index] get
Neuron Indexer
Parameters
index Index
Returns
Neuron at the given index
Exceptions
System.IndexOutOfRangeException If index is out of range
SourceConnectors
IList<IConnector> NeuronDotNet.Core.ILayer.SourceConnectors get
Gets the list of source connectors
The list of source connectors associated with this layer. It is neither null, nor contains null elements.
Referenced by NeuronDotNet.Core.Network.Network().
TargetConnectors
IList<IConnector> NeuronDotNet.Core.ILayer.TargetConnectors get
Gets the list of target connectors
The list of target connectors associated with this layer. It is neither null, nor contains null elements.
Referenced by NeuronDotNet.Core.Network.Network().
Initializer
IInitializer NeuronDotNet.Core.ILayer.Initializer get set
Gets or sets the Initializer used to initialize the layer
Initializer used to initialize the layer. If this value is null, initialization is NOT performed.
LearningRate
double NeuronDotNet.Core.ILayer.LearningRate get
Gets the initial value of learning rate
Initial value of learning rate.
LearningRateFunction
ILearningRateFunction NeuronDotNet.Core.ILayer.LearningRateFunction get
Gets the learning rate function
Learning Rate Function used while training. It is never null
The documentation for this interface was generated from the following file:
shelldev/lib/externalextended/NeuronDotNetGPL/source/Core/ILayer.cs