Doc: IGLib EXTENDED: Meta.Numerics.Statistics.PrincipalComponent Class Reference
Meta.Numerics.Statistics.PrincipalComponent Class Reference
Represents a component of a principal component analysis.
Public Member Functions
RowVector NormalizedVector ()
Gets the normalized component vector.
RowVector ScaledVector ()
Gets the scaled component vector.
Properties
int Index [get]
Gets the index of the principal component.
PrincipalComponentAnalysis Analysis [get]
Gets the principal component analysis to which the component belongs.
double Weight [get]
Gets the weight of the component.
double VarianceFraction [get]
Gets the fraction of the total variance accounted for by the principal component.
double CumulativeVarianceFraction [get]
Gets the fraction of the total variance accounted for by the principal component and all strong principal components.
Private Attributes
int index
PrincipalComponentAnalysis analysis
Detailed Description
Represents a component of a principal component analysis.
See also
PrincipalComponentAnalysis
Member Function Documentation
NormalizedVector()
RowVector Meta.Numerics.Statistics.PrincipalComponent.NormalizedVector () inline
Gets the normalized component vector.
References Meta.Numerics.Statistics.PrincipalComponent.analysis, Meta.Numerics.Statistics.PrincipalComponentAnalysis.cols, Meta.Numerics.Statistics.PrincipalComponent.index, and Meta.Numerics.Statistics.PrincipalComponentAnalysis.vStore.
Referenced by Test.MultivariateSampleTest.PrincipalComponentAnalysis(), and Meta.Numerics.Statistics.PrincipalComponent.ScaledVector().
ScaledVector()
RowVector Meta.Numerics.Statistics.PrincipalComponent.ScaledVector () inline
Gets the scaled component vector.
References Meta.Numerics.Statistics.PrincipalComponent.analysis, Meta.Numerics.Statistics.PrincipalComponent.index, Meta.Numerics.Statistics.PrincipalComponent.NormalizedVector(), and Meta.Numerics.Statistics.PrincipalComponentAnalysis.wStore.
Referenced by Test.MultivariateSampleTest.PrincipalComponentAnalysis().
Member Data Documentation
index
int Meta.Numerics.Statistics.PrincipalComponent.index private
Referenced by Meta.Numerics.Statistics.PrincipalComponent.NormalizedVector(), and Meta.Numerics.Statistics.PrincipalComponent.ScaledVector().
analysis
PrincipalComponentAnalysis Meta.Numerics.Statistics.PrincipalComponent.analysis private
Referenced by Meta.Numerics.Statistics.PrincipalComponent.NormalizedVector(), and Meta.Numerics.Statistics.PrincipalComponent.ScaledVector().
Property Documentation
Index
int Meta.Numerics.Statistics.PrincipalComponent.Index get
Gets the index of the principal component.
Referenced by Test.MultivariateSampleTest.PrincipalComponentAnalysis().
Analysis
PrincipalComponentAnalysis Meta.Numerics.Statistics.PrincipalComponent.Analysis get
Gets the principal component analysis to which the component belongs.
Weight
double Meta.Numerics.Statistics.PrincipalComponent.Weight get
Gets the weight of the component.
Referenced by Test.MultivariateSampleTest.PrincipalComponentAnalysis().
VarianceFraction
double Meta.Numerics.Statistics.PrincipalComponent.VarianceFraction get
Gets the fraction of the total variance accounted for by the principal component.
Referenced by Test.MultivariateSampleTest.PrincipalComponentAnalysis().
CumulativeVarianceFraction
double Meta.Numerics.Statistics.PrincipalComponent.CumulativeVarianceFraction get
Gets the fraction of the total variance accounted for by the principal component and all strong principal components.
Referenced by Test.MultivariateSampleTest.PrincipalComponentAnalysis().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/PrincipalComponentAnalysis.cs