Doc: IGLib EXTENDED: AForge.Imaging.SusanCornersDetector Class Reference
AForge.Imaging.SusanCornersDetector Class Reference
Susan corners detector.
Public Member Functions
SusanCornersDetector ()
Initializes a new instance of the SusanCornersDetector class.
SusanCornersDetector (int differenceThreshold, int geometricalThreshold)
Initializes a new instance of the SusanCornersDetector class.
List< IntPoint > ProcessImage (Bitmap image)
Process image looking for corners.
List< IntPoint > ProcessImage (BitmapData imageData)
Process image looking for corners.
List< IntPoint > ProcessImage (UnmanagedImage image)
Process image looking for corners.
Properties
int DifferenceThreshold [get, set]
Brightness difference threshold.
int GeometricalThreshold [get, set]
Geometrical threshold.
Private Attributes
int differenceThreshold = 25
int geometricalThreshold = 18
Static Private Attributes
static int[] rowRadius = new int[7] { 1, 2, 3, 3, 3, 2, 1 }
Detailed Description
Susan corners detector.
The class implements Susan corners detector, which is described by S.M. Smith in: S.M. Smith, "SUSAN - a new approach to low level image processing", Internal Technical Report TR95SMS1, Defense Research Agency, Chobham Lane, Chertsey, Surrey, UK, 1995.
<note>Some implementation notes:
Analyzing each pixel and searching for its USAN area, the 7x7 mask is used, which is comprised of 37 pixels. The mask has circle shape:
  xxx
 xxxxx
xxxxxxx
xxxxxxx
xxxxxxx
 xxxxx
  xxx
In the case if USAN's center of mass has the same coordinates as nucleus (central point), the pixel is not a corner.
For noise suppression the 5x5 square window is used.
</note>
The class processes only grayscale 8 bpp and color 24/32 bpp images. In the case of color image, it is converted to grayscale internally using GrayscaleBT709 filter.
Sample usage:
// create corners detector's instance
SusanCornersDetector scd = new SusanCornersDetector();
// process image searching for corners
List<IntPoint> corners = scd.ProcessImage(image);
// process points
foreach (IntPoint corner in corners)
{
    // ...
}
See also
MoravecCornersDetector
Constructor & Destructor Documentation
SusanCornersDetector() [1/2]
AForge.Imaging.SusanCornersDetector.SusanCornersDetector () inline
Initializes a new instance of the SusanCornersDetector class.
SusanCornersDetector() [2/2]
AForge.Imaging.SusanCornersDetector.SusanCornersDetector (int differenceThreshold, int geometricalThreshold) inline
Initializes a new instance of the SusanCornersDetector class.
Parameters
differenceThreshold Brightness difference threshold.
geometricalThreshold Geometrical threshold.
References AForge.Imaging.SusanCornersDetector.differenceThreshold, and AForge.Imaging.SusanCornersDetector.geometricalThreshold.
Member Function Documentation
ProcessImage() [1/3]
List<IntPoint> AForge.Imaging.SusanCornersDetector.ProcessImage (Bitmap image) inline
Process image looking for corners.
Parameters
image Source image to process.
Returns
Returns list of found corners (X-Y coordinates).
Exceptions
UnsupportedImageFormatException The source image has incorrect pixel format.
Implements AForge.Imaging.ICornersDetector.
References AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.SusanCornersDetector.ProcessImage().
ProcessImage() [2/3]
List<IntPoint> AForge.Imaging.SusanCornersDetector.ProcessImage (BitmapData imageData) inline
Process image looking for corners.
Parameters
imageData Source image data to process.
Returns
Returns list of found corners (X-Y coordinates).
Exceptions
UnsupportedImageFormatException The source image has incorrect pixel format.
Implements AForge.Imaging.ICornersDetector.
References AForge.Imaging.SusanCornersDetector.ProcessImage().
ProcessImage() [3/3]
List<IntPoint> AForge.Imaging.SusanCornersDetector.ProcessImage (UnmanagedImage image) inline
Process image looking for corners.
Parameters
image Unmanaged source image to process.
Returns
Returns array of found corners (X-Y coordinates).
Exceptions
UnsupportedImageFormatException The source image has incorrect pixel format.
Implements AForge.Imaging.ICornersDetector.
References AForge.Imaging.Filters.BaseFilter.Apply(), AForge.Imaging.Filters.Grayscale.CommonAlgorithms.BT709, AForge.Imaging.SusanCornersDetector.differenceThreshold, AForge.Imaging.UnmanagedImage.Dispose(), AForge.Imaging.SusanCornersDetector.geometricalThreshold, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.SusanCornersDetector.rowRadius, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
Member Data Documentation
differenceThreshold
int AForge.Imaging.SusanCornersDetector.differenceThreshold = 25 private
Referenced by AForge.Imaging.SusanCornersDetector.ProcessImage(), and AForge.Imaging.SusanCornersDetector.SusanCornersDetector().
geometricalThreshold
int AForge.Imaging.SusanCornersDetector.geometricalThreshold = 18 private
Referenced by AForge.Imaging.SusanCornersDetector.ProcessImage(), and AForge.Imaging.SusanCornersDetector.SusanCornersDetector().
rowRadius
int [] AForge.Imaging.SusanCornersDetector.rowRadius = new int[7] { 1, 2, 3, 3, 3, 2, 1 } static private
Referenced by AForge.Imaging.SusanCornersDetector.ProcessImage().
Property Documentation
DifferenceThreshold
int AForge.Imaging.SusanCornersDetector.DifferenceThreshold get set
Brightness difference threshold.
The brightness difference threshold controls the amount of pixels, which become part of USAN area. If difference between central pixel (nucleus) and surrounding pixel is not higher than difference threshold, then that pixel becomes part of USAN.
Increasing this value decreases the amount of detected corners.
Default value is set to 25.
GeometricalThreshold
int AForge.Imaging.SusanCornersDetector.GeometricalThreshold get set
Geometrical threshold.
The geometrical threshold sets the maximum number of pixels in USAN area around corner. If potential corner has USAN with more pixels, than it is not a corner.
Decreasing this value decreases the amount of detected corners - only sharp corners are detected. Increasing this value increases the amount of detected corners, but also increases amount of flat corners, which may be not corners at all.
Default value is set to 18, which is half of maximum amount of pixels in USAN.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/SusanCornersDetector.cs