Doc: IGLib EXTENDED: NUnit.Engine.Internal.Tests.ResultHelperTests Class Reference
NUnit.Engine.Internal.Tests.ResultHelperTests Class Reference
Public Member Functions
void SetUp ()
void MergeTestResults ()
void AggregateTestResult ()
void MergeAndAggregateTestResults ()
void AggregateXmlNodes ()
Private Attributes
TestEngineResult result1
TestEngineResult result2
TestEngineResult[] twoResults
XmlNode[] twoNodes
Static Private Attributes
const string resultText1 = "<test-assembly result=\"Passed\" total=\"23\" passed=\"23\" failed=\"0\" inconclusive=\"0\" skipped=\"0\" asserts=\"40\" />"
const string resultText2 = "<test-assembly result=\"Failed\" total=\"42\" passed=\"31\" failed=\"4\" inconclusive=\"5\" skipped=\"2\" asserts=\"53\" />"
Member Function Documentation
SetUp()
void NUnit.Engine.Internal.Tests.ResultHelperTests.SetUp () inline
References NUnit.Engine.Internal.Tests.ResultHelperTests.result1, NUnit.Engine.Internal.Tests.ResultHelperTests.result2, NUnit.Engine.Internal.Tests.ResultHelperTests.resultText1, NUnit.Engine.Internal.Tests.ResultHelperTests.resultText2, NUnit.Engine.Internal.Tests.ResultHelperTests.twoNodes, NUnit.Engine.Internal.Tests.ResultHelperTests.twoResults, and NUnit.Engine.TestEngineResult.Xml.
MergeTestResults()
void NUnit.Engine.Internal.Tests.ResultHelperTests.MergeTestResults () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Engine.Internal.ResultHelper.Merge(), NUnit.Engine.Internal.Tests.ResultHelperTests.resultText1, NUnit.Engine.Internal.Tests.ResultHelperTests.resultText2, NUnit.Engine.Internal.Tests.ResultHelperTests.twoResults, and NUnit.Engine.TestEngineResult.XmlNodes.
AggregateTestResult()
void NUnit.Engine.Internal.Tests.ResultHelperTests.AggregateTestResult () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Engine.TestEngineResult.IsSingle, NUnit.Engine.Internal.Tests.ResultHelperTests.result2, and NUnit.Engine.TestEngineResult.Xml.
MergeAndAggregateTestResults()
void NUnit.Engine.Internal.Tests.ResultHelperTests.MergeAndAggregateTestResults () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Engine.TestEngineResult.IsSingle, NUnit.Engine.Internal.ResultHelper.Merge(), NUnit.Engine.Internal.Tests.ResultHelperTests.twoResults, and NUnit.Engine.TestEngineResult.Xml.
AggregateXmlNodes()
void NUnit.Engine.Internal.Tests.ResultHelperTests.AggregateXmlNodes () inline
References NUnit.Engine.Internal.ResultHelper.Aggregate(), NUnit.Framework.Is.EqualTo(), and NUnit.Engine.Internal.Tests.ResultHelperTests.twoNodes.
Member Data Documentation
resultText1
const string NUnit.Engine.Internal.Tests.ResultHelperTests.resultText1 = "<test-assembly result=\"Passed\" total=\"23\" passed=\"23\" failed=\"0\" inconclusive=\"0\" skipped=\"0\" asserts=\"40\" />" static private
Referenced by NUnit.Engine.Internal.Tests.ResultHelperTests.MergeTestResults(), and NUnit.Engine.Internal.Tests.ResultHelperTests.SetUp().
resultText2
const string NUnit.Engine.Internal.Tests.ResultHelperTests.resultText2 = "<test-assembly result=\"Failed\" total=\"42\" passed=\"31\" failed=\"4\" inconclusive=\"5\" skipped=\"2\" asserts=\"53\" />" static private
Referenced by NUnit.Engine.Internal.Tests.ResultHelperTests.MergeTestResults(), and NUnit.Engine.Internal.Tests.ResultHelperTests.SetUp().
result1
TestEngineResult NUnit.Engine.Internal.Tests.ResultHelperTests.result1 private
Referenced by NUnit.Engine.Internal.Tests.ResultHelperTests.SetUp().
result2
TestEngineResult NUnit.Engine.Internal.Tests.ResultHelperTests.result2 private
Referenced by NUnit.Engine.Internal.Tests.ResultHelperTests.AggregateTestResult(), and NUnit.Engine.Internal.Tests.ResultHelperTests.SetUp().
twoResults
TestEngineResult [] NUnit.Engine.Internal.Tests.ResultHelperTests.twoResults private
Referenced by NUnit.Engine.Internal.Tests.ResultHelperTests.MergeAndAggregateTestResults(), NUnit.Engine.Internal.Tests.ResultHelperTests.MergeTestResults(), and NUnit.Engine.Internal.Tests.ResultHelperTests.SetUp().
twoNodes
XmlNode [] NUnit.Engine.Internal.Tests.ResultHelperTests.twoNodes private
Referenced by NUnit.Engine.Internal.Tests.ResultHelperTests.AggregateXmlNodes(), and NUnit.Engine.Internal.Tests.ResultHelperTests.SetUp().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/ResultHelperTests.cs