Doc: IGLib EXTENDED: NUnit.Framework.Assertions.FileAssertTests Class Reference
NUnit.Framework.Assertions.FileAssertTests Class Reference
Summary description for FileAssertTests.
Classes
class FakeStream
Public Member Functions
void AreEqualPassesWhenBothAreNull ()
void AreEqualPassesWithSameStream ()
void AreEqualPassesWithEqualStreams ()
void NonReadableStreamGivesException ()
void NonSeekableStreamGivesException ()
void AreEqualPassesWithFiles ()
void AreEqualPassesUsingSameFileTwice ()
void AreEqualPassesWithFileInfos ()
void AreEqualPassesWithTextFiles ()
void AreEqualFailsWhenOneIsNull ()
void AreEqualFailsWithStreams ()
void AreEqualFailsWithFileInfos ()
void AreEqualFailsWithFiles ()
void AreEqualFailsWithTextFilesAfterReadingBothFiles ()
void AreNotEqualPassesIfOneIsNull ()
void AreNotEqualPassesWithStreams ()
void AreNotEqualPassesWithFiles ()
void AreNotEqualPassesWithFileInfos ()
void AreNotEqualIteratesOverTheEntireFile ()
void AreNotEqualFailsWhenBothAreNull ()
void AreNotEqualFailsWithStreams ()
void AreNotEqualFailsWithFileInfos ()
void AreNotEqualFailsWithFiles ()
void AreNotEqualIteratesOverTheEntireFileAndFails ()
void ExistsPassesWhenFileInfoExists ()
void ExistsPassesWhenStringExists ()
void ExistsFailsWhenFileInfoDoesNotExist ()
void ExistsFailsWhenStringDoesNotExist ()
void ExistsFailsWhenFileInfoIsNull ()
void ExistsFailsWhenStringIsNull ()
void ExistsFailsWhenStringIsEmpty ()
void DoesNotExistFailsWhenFileInfoExists ()
void DoesNotExistFailsWhenStringExists ()
void DoesNotExistPassesWhenFileInfoDoesNotExist ()
void DoesNotExistPassesWhenStringDoesNotExist ()
void DoesNotExistFailsWhenFileInfoIsNull ()
void DoesNotExistFailsWhenStringIsNull ()
void DoesNotExistFailsWhenStringIsEmpty ()
Static Private Attributes
static readonly string BAD_FILE = Path.Combine(Path.GetTempPath(), "garbage.txt")
Detailed Description
Summary description for FileAssertTests.
Member Function Documentation
AreEqualPassesWhenBothAreNull()
void NUnit.Framework.Assertions.FileAssertTests.AreEqualPassesWhenBothAreNull () inline
References NUnit.Framework.FileAssert.AreEqual().
AreEqualPassesWithSameStream()
void NUnit.Framework.Assertions.FileAssertTests.AreEqualPassesWithSameStream () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
AreEqualPassesWithEqualStreams()
void NUnit.Framework.Assertions.FileAssertTests.AreEqualPassesWithEqualStreams () inline
References NUnit.Framework.FileAssert.AreEqual().
NonReadableStreamGivesException()
void NUnit.Framework.Assertions.FileAssertTests.NonReadableStreamGivesException () inline
References NUnit.Framework.FileAssert.AreEqual(), NUnit.Framework.Does.Contain(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
NonSeekableStreamGivesException()
void NUnit.Framework.Assertions.FileAssertTests.NonSeekableStreamGivesException () inline
References NUnit.Framework.FileAssert.AreEqual(), NUnit.Framework.Does.Contain(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
AreEqualPassesWithFiles()
void NUnit.Framework.Assertions.FileAssertTests.AreEqualPassesWithFiles () inline
References NUnit.Framework.FileAssert.AreEqual().
AreEqualPassesUsingSameFileTwice()
void NUnit.Framework.Assertions.FileAssertTests.AreEqualPassesUsingSameFileTwice () inline
References NUnit.Framework.FileAssert.AreEqual().
AreEqualPassesWithFileInfos()
void NUnit.Framework.Assertions.FileAssertTests.AreEqualPassesWithFileInfos () inline
References NUnit.Framework.FileAssert.AreEqual().
AreEqualPassesWithTextFiles()
void NUnit.Framework.Assertions.FileAssertTests.AreEqualPassesWithTextFiles () inline
References NUnit.Framework.FileAssert.AreEqual().
AreEqualFailsWhenOneIsNull()
void NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWhenOneIsNull () inline
References NUnit.Framework.FileAssert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
AreEqualFailsWithStreams()
void NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWithStreams () inline
References NUnit.Framework.FileAssert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
AreEqualFailsWithFileInfos()
void NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWithFileInfos () inline
References NUnit.Framework.FileAssert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
AreEqualFailsWithFiles()
void NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWithFiles () inline
References NUnit.Framework.FileAssert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
AreEqualFailsWithTextFilesAfterReadingBothFiles()
void NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWithTextFilesAfterReadingBothFiles () inline
References NUnit.Framework.FileAssert.AreEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
AreNotEqualPassesIfOneIsNull()
void NUnit.Framework.Assertions.FileAssertTests.AreNotEqualPassesIfOneIsNull () inline
References NUnit.Framework.FileAssert.AreNotEqual().
AreNotEqualPassesWithStreams()
void NUnit.Framework.Assertions.FileAssertTests.AreNotEqualPassesWithStreams () inline
References NUnit.Framework.FileAssert.AreNotEqual().
AreNotEqualPassesWithFiles()
void NUnit.Framework.Assertions.FileAssertTests.AreNotEqualPassesWithFiles () inline
References NUnit.Framework.FileAssert.AreNotEqual().
AreNotEqualPassesWithFileInfos()
void NUnit.Framework.Assertions.FileAssertTests.AreNotEqualPassesWithFileInfos () inline
References NUnit.Framework.FileAssert.AreNotEqual().
AreNotEqualIteratesOverTheEntireFile()
void NUnit.Framework.Assertions.FileAssertTests.AreNotEqualIteratesOverTheEntireFile () inline
References NUnit.Framework.FileAssert.AreNotEqual().
AreNotEqualFailsWhenBothAreNull()
void NUnit.Framework.Assertions.FileAssertTests.AreNotEqualFailsWhenBothAreNull () inline
References NUnit.Framework.FileAssert.AreNotEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
AreNotEqualFailsWithStreams()
void NUnit.Framework.Assertions.FileAssertTests.AreNotEqualFailsWithStreams () inline
References NUnit.Framework.FileAssert.AreNotEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
AreNotEqualFailsWithFileInfos()
void NUnit.Framework.Assertions.FileAssertTests.AreNotEqualFailsWithFileInfos () inline
References NUnit.Framework.FileAssert.AreNotEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
AreNotEqualFailsWithFiles()
void NUnit.Framework.Assertions.FileAssertTests.AreNotEqualFailsWithFiles () inline
References NUnit.Framework.FileAssert.AreNotEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
AreNotEqualIteratesOverTheEntireFileAndFails()
void NUnit.Framework.Assertions.FileAssertTests.AreNotEqualIteratesOverTheEntireFileAndFails () inline
References NUnit.Framework.FileAssert.AreNotEqual(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
ExistsPassesWhenFileInfoExists()
void NUnit.Framework.Assertions.FileAssertTests.ExistsPassesWhenFileInfoExists () inline
References NUnit.Framework.FileAssert.Exists().
ExistsPassesWhenStringExists()
void NUnit.Framework.Assertions.FileAssertTests.ExistsPassesWhenStringExists () inline
References NUnit.Framework.FileAssert.Exists().
ExistsFailsWhenFileInfoDoesNotExist()
void NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenFileInfoDoesNotExist () inline
References NUnit.Framework.Assertions.FileAssertTests.BAD_FILE, NUnit.Framework.FileAssert.Exists(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
ExistsFailsWhenStringDoesNotExist()
void NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenStringDoesNotExist () inline
References NUnit.Framework.Assertions.FileAssertTests.BAD_FILE, NUnit.Framework.FileAssert.Exists(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
ExistsFailsWhenFileInfoIsNull()
void NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenFileInfoIsNull () inline
References NUnit.Framework.FileAssert.Exists(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
ExistsFailsWhenStringIsNull()
void NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenStringIsNull () inline
References NUnit.Framework.FileAssert.Exists(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
ExistsFailsWhenStringIsEmpty()
void NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenStringIsEmpty () inline
References NUnit.Framework.FileAssert.Exists(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
DoesNotExistFailsWhenFileInfoExists()
void NUnit.Framework.Assertions.FileAssertTests.DoesNotExistFailsWhenFileInfoExists () inline
References NUnit.Framework.FileAssert.DoesNotExist(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
DoesNotExistFailsWhenStringExists()
void NUnit.Framework.Assertions.FileAssertTests.DoesNotExistFailsWhenStringExists () inline
References NUnit.Framework.FileAssert.DoesNotExist(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
DoesNotExistPassesWhenFileInfoDoesNotExist()
void NUnit.Framework.Assertions.FileAssertTests.DoesNotExistPassesWhenFileInfoDoesNotExist () inline
References NUnit.Framework.Assertions.FileAssertTests.BAD_FILE, and NUnit.Framework.FileAssert.DoesNotExist().
DoesNotExistPassesWhenStringDoesNotExist()
void NUnit.Framework.Assertions.FileAssertTests.DoesNotExistPassesWhenStringDoesNotExist () inline
References NUnit.Framework.Assertions.FileAssertTests.BAD_FILE, and NUnit.Framework.FileAssert.DoesNotExist().
DoesNotExistFailsWhenFileInfoIsNull()
void NUnit.Framework.Assertions.FileAssertTests.DoesNotExistFailsWhenFileInfoIsNull () inline
References NUnit.Framework.FileAssert.DoesNotExist(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
DoesNotExistFailsWhenStringIsNull()
void NUnit.Framework.Assertions.FileAssertTests.DoesNotExistFailsWhenStringIsNull () inline
References NUnit.Framework.FileAssert.DoesNotExist(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
DoesNotExistFailsWhenStringIsEmpty()
void NUnit.Framework.Assertions.FileAssertTests.DoesNotExistFailsWhenStringIsEmpty () inline
References NUnit.Framework.FileAssert.DoesNotExist(), NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
Member Data Documentation
BAD_FILE
readonly string NUnit.Framework.Assertions.FileAssertTests.BAD_FILE = Path.Combine(Path.GetTempPath(), "garbage.txt") static private
Referenced by NUnit.Framework.Assertions.FileAssertTests.DoesNotExistPassesWhenFileInfoDoesNotExist(), NUnit.Framework.Assertions.FileAssertTests.DoesNotExistPassesWhenStringDoesNotExist(), NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenFileInfoDoesNotExist(), and NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenStringDoesNotExist().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/FileAssertTests.cs