Doc: IGLib EXTENDED: alglib.testspline1dunit Class Reference
alglib.testspline1dunit Class Reference
Static Public Member Functions
static bool testspline1d (bool silent)
static bool testspline1d (bool silent)
static bool _pexec_testspline1d (bool silent)
Static Private Member Functions
static void lconst (double a, double b, spline1d.spline1dinterpolant c, double lstep, ref double l0, ref double l1, ref double l2)
static bool enumerateallsplines (double[] x, double[] y, int n, ref int splineindex, spline1d.spline1dinterpolant s)
static bool testunpack (spline1d.spline1dinterpolant c, double[] x)
static void unsetspline1d (spline1d.spline1dinterpolant c)
static void unset1d (ref double[] x)
static bool is1dsolution (int n, double[] y, double[] w, double c)
static bool testmonotonespline ()
static void lconst (double a, double b, spline1d.spline1dinterpolant c, double lstep, ref double l0, ref double l1, ref double l2)
static bool enumerateallsplines (double[] x, double[] y, int n, ref int splineindex, spline1d.spline1dinterpolant s)
static bool testunpack (spline1d.spline1dinterpolant c, double[] x)
static void unsetspline1d (spline1d.spline1dinterpolant c)
static void unset1d (ref double[] x)
static bool is1dsolution (int n, double[] y, double[] w, double c)
static bool testmonotonespline ()
Member Function Documentation
testspline1d() [1/2]
static bool alglib.testspline1dunit.testspline1d (bool silent) inline static
References alglib.ap.assert(), alglib.testspline1dunit.enumerateallsplines(), alglib.testspline1dunit.lconst(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.spline1d.spline1dbuildakima(), alglib.spline1d.spline1dbuildcatmullrom(), alglib.spline1d.spline1dbuildcubic(), alglib.spline1d.spline1dbuildhermite(), alglib.spline1d.spline1dbuildlinear(), alglib.spline1d.spline1dcalc(), alglib.spline1d.spline1dconvcubic(), alglib.spline1d.spline1dconvdiff2cubic(), alglib.spline1d.spline1dconvdiffcubic(), alglib.spline1d.spline1dcopy(), alglib.spline1d.spline1ddiff(), alglib.spline1d.spline1dgriddiff2cubic(), alglib.spline1d.spline1dgriddiffcubic(), alglib.spline1d.spline1dintegrate(), alglib.spline1d.spline1dlintransx(), alglib.spline1d.spline1dlintransy(), alglib.math.sqr(), alglib.testspline1dunit.testmonotonespline(), alglib.testspline1dunit.testunpack(), and alglib.testspline1dunit.unsetspline1d().
Referenced by alglib.testspline1dunit._pexec_testspline1d(), and _Test.Main().
lconst() [1/2]
static void alglib.testspline1dunit.lconst (double a, double b, spline1d.spline1dinterpolant c, double lstep, ref double l0, ref double l1, ref double l2) inline static private
References alglib.spline1d.spline1dcalc(), and alglib.math.sqr().
Referenced by alglib.testspline1dunit.testspline1d().
enumerateallsplines() [1/2]
static bool alglib.testspline1dunit.enumerateallsplines (double[] x, double[] y, int n, ref int splineindex, spline1d.spline1dinterpolant s) inline static private
References alglib.ap.assert(), alglib.math.randomreal(), alglib.spline1d.spline1dbuildcubic(), and alglib.spline1d.spline1dbuildlinear().
Referenced by alglib.testspline1dunit.testspline1d().
testunpack() [1/2]
static bool alglib.testspline1dunit.testunpack (spline1d.spline1dinterpolant c, double[] x) inline static private
References alglib.math.machineepsilon, alglib.math.randomreal(), alglib.spline1d.spline1dcalc(), alglib.spline1d.spline1dunpack(), and alglib.math.sqr().
Referenced by alglib.testspline1dunit.testspline1d().
unsetspline1d() [1/2]
static void alglib.testspline1dunit.unsetspline1d (spline1d.spline1dinterpolant c) inline static private
References alglib.math.randomreal(), and alglib.spline1d.spline1dbuildhermite().
Referenced by alglib.testspline1dunit.testspline1d().
unset1d() [1/2]
static void alglib.testspline1dunit.unset1d (ref double[] x) inline static private
References alglib.math.randomreal().
is1dsolution() [1/2]
static bool alglib.testspline1dunit.is1dsolution (int n, double[] y, double[] w, double c) inline static private
References alglib.math.sqr().
testmonotonespline() [1/2]
static bool alglib.testspline1dunit.testmonotonespline () inline static private
References alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.spline1d.spline1dbuildhermite(), alglib.spline1d.spline1dbuildmonotone(), alglib.spline1d.spline1dcalc(), and alglib.spline1d.spline1ddiff().
Referenced by alglib.testspline1dunit.testspline1d().
testspline1d() [2/2]
static bool alglib.testspline1dunit.testspline1d (bool silent) inline static
References alglib.ap.assert(), alglib.testspline1dunit.enumerateallsplines(), alglib.testspline1dunit.lconst(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.spline1d.spline1dbuildakima(), alglib.spline1d.spline1dbuildcatmullrom(), alglib.spline1d.spline1dbuildcubic(), alglib.spline1d.spline1dbuildhermite(), alglib.spline1d.spline1dbuildlinear(), alglib.spline1d.spline1dcalc(), alglib.spline1d.spline1dconvcubic(), alglib.spline1d.spline1dconvdiff2cubic(), alglib.spline1d.spline1dconvdiffcubic(), alglib.spline1d.spline1dcopy(), alglib.spline1d.spline1ddiff(), alglib.spline1d.spline1dgriddiff2cubic(), alglib.spline1d.spline1dgriddiffcubic(), alglib.spline1d.spline1dintegrate(), alglib.spline1d.spline1dlintransx(), alglib.spline1d.spline1dlintransy(), alglib.math.sqr(), alglib.testspline1dunit.testmonotonespline(), alglib.testspline1dunit.testunpack(), and alglib.testspline1dunit.unsetspline1d().
_pexec_testspline1d()
static bool alglib.testspline1dunit._pexec_testspline1d (bool silent) inline static
References alglib.testspline1dunit.testspline1d().
Referenced by _Test.Main().
lconst() [2/2]
static void alglib.testspline1dunit.lconst (double a, double b, spline1d.spline1dinterpolant c, double lstep, ref double l0, ref double l1, ref double l2) inline static private
References alglib.spline1d.spline1dcalc(), and alglib.math.sqr().
enumerateallsplines() [2/2]
static bool alglib.testspline1dunit.enumerateallsplines (double[] x, double[] y, int n, ref int splineindex, spline1d.spline1dinterpolant s) inline static private
References alglib.ap.assert(), alglib.math.randomreal(), alglib.spline1d.spline1dbuildcubic(), and alglib.spline1d.spline1dbuildlinear().
testunpack() [2/2]
static bool alglib.testspline1dunit.testunpack (spline1d.spline1dinterpolant c, double[] x) inline static private
References alglib.math.machineepsilon, alglib.math.randomreal(), alglib.spline1d.spline1dcalc(), alglib.spline1d.spline1dunpack(), and alglib.math.sqr().
unsetspline1d() [2/2]
static void alglib.testspline1dunit.unsetspline1d (spline1d.spline1dinterpolant c) inline static private
References alglib.math.randomreal(), and alglib.spline1d.spline1dbuildhermite().
unset1d() [2/2]
static void alglib.testspline1dunit.unset1d (ref double[] x) inline static private
References alglib.math.randomreal().
is1dsolution() [2/2]
static bool alglib.testspline1dunit.is1dsolution (int n, double[] y, double[] w, double c) inline static private
References alglib.math.sqr().
testmonotonespline() [2/2]
static bool alglib.testspline1dunit.testmonotonespline () inline static private
References alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.spline1d.spline1dbuildhermite(), alglib.spline1d.spline1dbuildmonotone(), alglib.spline1d.spline1dcalc(), and alglib.spline1d.spline1ddiff().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs