Doc: IGLib EXTENDED: alglib.gammafunc Class Reference
alglib.gammafunc Class Reference
Static Public Member Functions
static double gammafunction (double x)
static double lngamma (double x, ref double sgngam)
static double gammafunction (double x)
static double lngamma (double x, ref double sgngam)
Static Private Member Functions
static double gammastirf (double x)
static double gammastirf (double x)
Member Function Documentation
gammafunction() [1/2]
static double alglib.gammafunc.gammafunction (double x) inline static
References alglib.gammafunc.gammastirf().
Referenced by alglib.betaf.beta(), alglib.gammafunction(), alglib.ibetaf.incompletebeta(), alglib.ibetaf.incompletebetaps(), and alglib.testgammafuncunit.testgammafunc().
lngamma() [1/2]
static double alglib.gammafunc.lngamma (double x, ref double sgngam) inline static
Referenced by alglib.betaf.beta(), alglib.testgqunit.buildgaussjacobiquadrature(), alglib.testgqunit.buildgausslaguerrequadrature(), alglib.gkq.gkqgenerategaussjacobi(), alglib.gq.gqgenerategaussjacobi(), alglib.gq.gqgenerategausslaguerre(), alglib.ibetaf.incompletebeta(), alglib.ibetaf.incompletebetaps(), alglib.igammaf.incompletegamma(), alglib.igammaf.incompletegammac(), alglib.ibetaf.invincompletebeta(), alglib.igammaf.invincompletegammac(), alglib.lngamma(), alglib.gammafunc.lngamma(), and alglib.testgammafuncunit.testgammafunc().
gammastirf() [1/2]
static double alglib.gammafunc.gammastirf (double x) inline static private
Referenced by alglib.gammafunc.gammafunction().
gammafunction() [2/2]
static double alglib.gammafunc.gammafunction (double x) inline static
References alglib.gammafunc.gammastirf().
lngamma() [2/2]
static double alglib.gammafunc.lngamma (double x, ref double sgngam) inline static
References alglib.gammafunc.lngamma().
gammastirf() [2/2]
static double alglib.gammafunc.gammastirf (double x) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/specialfunctions.cs