Doc: IGLib EXTENDED: NUnit.ConsoleRunner.ResultReporter Class Reference
NUnit.ConsoleRunner.ResultReporter Class Reference
Public Member Functions
ResultReporter (XmlNode result, ExtendedTextWriter writer, ConsoleOptions options)
void ReportResults ()
Reports the results to the console
void WriteSummaryReport ()
void WriteErrorsAndFailuresReport ()
void WriteNotRunReport ()
Properties
ResultSummary Summary [get, private set]
Private Member Functions
void WriteRunSettingsReport ()
void WriteErrorsAndFailures (XmlNode result)
void WriteNotRunResults (XmlNode result)
void WriteSummaryCount (string label, int count)
void WriteSummaryCount (string label, int count, ColorStyle color)
void WriteSingleResult (XmlNode result, ColorStyle colorStyle)
Private Attributes
ExtendedTextWriter _writer
XmlNode _result
string _overallResult
ConsoleOptions _options
int _reportIndex = 0
Static Private Attributes
static readonly char[] EOL_CHARS = new char[] { '\r', '\n' }
Constructor & Destructor Documentation
ResultReporter()
NUnit.ConsoleRunner.ResultReporter.ResultReporter (XmlNode result, ExtendedTextWriter writer, ConsoleOptions options) inline
References NUnit.ConsoleRunner.ResultReporter._options, NUnit.ConsoleRunner.ResultReporter._overallResult, NUnit.ConsoleRunner.ResultReporter._result, NUnit.ConsoleRunner.ResultReporter._writer, and NUnit.ConsoleRunner.ResultReporter.Summary.
Member Function Documentation
ReportResults()
void NUnit.ConsoleRunner.ResultReporter.ReportResults () inline
Reports the results to the console
References NUnit.ConsoleRunner.ResultReporter._overallResult, NUnit.ConsoleRunner.ResultReporter._writer, NUnit.ConsoleRunner.ResultSummary.ExplicitCount, NUnit.ConsoleRunner.ResultSummary.IgnoreCount, NUnit.ConsoleRunner.ResultSummary.SkipCount, NUnit.ConsoleRunner.ResultReporter.Summary, NUnit.ConsoleRunner.ResultReporter.WriteErrorsAndFailuresReport(), NUnit.Common.ExtendedTextWriter.WriteLine(), NUnit.ConsoleRunner.ResultReporter.WriteNotRunReport(), NUnit.ConsoleRunner.ResultReporter.WriteRunSettingsReport(), and NUnit.ConsoleRunner.ResultReporter.WriteSummaryReport().
Referenced by NUnit.ConsoleRunner.Tests.ResultReporterTests.ReportSequenceTest().
WriteRunSettingsReport()
void NUnit.ConsoleRunner.ResultReporter.WriteRunSettingsReport () inline private
References NUnit.ConsoleRunner.ResultReporter._result, NUnit.ConsoleRunner.ResultReporter._writer, NUnit.Common.ExtendedTextWriter.WriteLabelLine(), and NUnit.Common.ExtendedTextWriter.WriteLine().
Referenced by NUnit.ConsoleRunner.ResultReporter.ReportResults().
WriteSummaryReport()
void NUnit.ConsoleRunner.ResultReporter.WriteSummaryReport () inline
References NUnit.ConsoleRunner.ResultReporter._overallResult, NUnit.ConsoleRunner.ResultReporter._result, NUnit.ConsoleRunner.ResultReporter._writer, NUnit.ConsoleRunner.ResultSummary.ErrorCount, NUnit.ConsoleRunner.ResultSummary.ExplicitCount, NUnit.ConsoleRunner.ResultSummary.FailureCount, NUnit.ConsoleRunner.ResultSummary.IgnoreCount, NUnit.ConsoleRunner.ResultSummary.InconclusiveCount, NUnit.ConsoleRunner.ResultSummary.InvalidCount, NUnit.ConsoleRunner.ResultSummary.NotRunCount, NUnit.ConsoleRunner.ResultSummary.PassCount, NUnit.ConsoleRunner.ResultSummary.RunCount, NUnit.ConsoleRunner.ResultSummary.SkipCount, NUnit.ConsoleRunner.ResultReporter.Summary, NUnit.Common.ExtendedTextWriter.WriteLabelLine(), NUnit.Common.ExtendedTextWriter.WriteLine(), and NUnit.ConsoleRunner.ResultReporter.WriteSummaryCount().
Referenced by NUnit.ConsoleRunner.ResultReporter.ReportResults(), and NUnit.ConsoleRunner.Tests.ResultReporterTests.SummaryReportTest().
WriteErrorsAndFailuresReport()
void NUnit.ConsoleRunner.ResultReporter.WriteErrorsAndFailuresReport () inline
References NUnit.ConsoleRunner.ResultReporter._options, NUnit.ConsoleRunner.ResultReporter._reportIndex, NUnit.ConsoleRunner.ResultReporter._result, NUnit.ConsoleRunner.ResultReporter._writer, NUnit.Common.CommandLineOptions.StopOnError, NUnit.ConsoleRunner.ResultReporter.WriteErrorsAndFailures(), and NUnit.Common.ExtendedTextWriter.WriteLine().
Referenced by NUnit.ConsoleRunner.Tests.ResultReporterTests.ErrorsAndFailuresReportTest(), and NUnit.ConsoleRunner.ResultReporter.ReportResults().
WriteErrorsAndFailures()
void NUnit.ConsoleRunner.ResultReporter.WriteErrorsAndFailures (XmlNode result) inline private
References NUnit.ConsoleRunner.ResultReporter.WriteSingleResult().
Referenced by NUnit.ConsoleRunner.ResultReporter.WriteErrorsAndFailuresReport().
WriteNotRunReport()
void NUnit.ConsoleRunner.ResultReporter.WriteNotRunReport () inline
References NUnit.ConsoleRunner.ResultReporter._reportIndex, NUnit.ConsoleRunner.ResultReporter._result, NUnit.ConsoleRunner.ResultReporter._writer, NUnit.Common.ExtendedTextWriter.WriteLine(), and NUnit.ConsoleRunner.ResultReporter.WriteNotRunResults().
Referenced by NUnit.ConsoleRunner.ResultReporter.ReportResults(), and NUnit.ConsoleRunner.Tests.ResultReporterTests.TestsNotRunTest().
WriteNotRunResults()
void NUnit.ConsoleRunner.ResultReporter.WriteNotRunResults (XmlNode result) inline private
References NUnit.ConsoleRunner.ResultReporter.WriteSingleResult().
Referenced by NUnit.ConsoleRunner.ResultReporter.WriteNotRunReport().
WriteSummaryCount() [1/2]
void NUnit.ConsoleRunner.ResultReporter.WriteSummaryCount (string label, int count) inline private
References NUnit.ConsoleRunner.ResultReporter._writer, and NUnit.Common.ExtendedTextWriter.WriteLabel().
Referenced by NUnit.ConsoleRunner.ResultReporter.WriteSummaryReport().
WriteSummaryCount() [2/2]
void NUnit.ConsoleRunner.ResultReporter.WriteSummaryCount (string label, int count, ColorStyle color) inline private
References NUnit.ConsoleRunner.ResultReporter._writer, and NUnit.Common.ExtendedTextWriter.WriteLabel().
WriteSingleResult()
void NUnit.ConsoleRunner.ResultReporter.WriteSingleResult (XmlNode result, ColorStyle colorStyle) inline private
References NUnit.ConsoleRunner.ResultReporter._reportIndex, NUnit.ConsoleRunner.ResultReporter._writer, NUnit.ConsoleRunner.ResultReporter.EOL_CHARS, and NUnit.Common.ExtendedTextWriter.WriteLine().
Referenced by NUnit.ConsoleRunner.ResultReporter.WriteErrorsAndFailures(), and NUnit.ConsoleRunner.ResultReporter.WriteNotRunResults().
Member Data Documentation
_writer
ExtendedTextWriter NUnit.ConsoleRunner.ResultReporter._writer private
Referenced by NUnit.ConsoleRunner.ResultReporter.ReportResults(), NUnit.ConsoleRunner.ResultReporter.ResultReporter(), NUnit.ConsoleRunner.ResultReporter.WriteErrorsAndFailuresReport(), NUnit.ConsoleRunner.ResultReporter.WriteNotRunReport(), NUnit.ConsoleRunner.ResultReporter.WriteRunSettingsReport(), NUnit.ConsoleRunner.ResultReporter.WriteSingleResult(), NUnit.ConsoleRunner.ResultReporter.WriteSummaryCount(), and NUnit.ConsoleRunner.ResultReporter.WriteSummaryReport().
_result
XmlNode NUnit.ConsoleRunner.ResultReporter._result private
Referenced by NUnit.ConsoleRunner.ResultReporter.ResultReporter(), NUnit.ConsoleRunner.ResultReporter.WriteErrorsAndFailuresReport(), NUnit.ConsoleRunner.ResultReporter.WriteNotRunReport(), NUnit.ConsoleRunner.ResultReporter.WriteRunSettingsReport(), and NUnit.ConsoleRunner.ResultReporter.WriteSummaryReport().
_overallResult
string NUnit.ConsoleRunner.ResultReporter._overallResult private
Referenced by NUnit.ConsoleRunner.ResultReporter.ReportResults(), NUnit.ConsoleRunner.ResultReporter.ResultReporter(), and NUnit.ConsoleRunner.ResultReporter.WriteSummaryReport().
_options
ConsoleOptions NUnit.ConsoleRunner.ResultReporter._options private
Referenced by NUnit.ConsoleRunner.ResultReporter.ResultReporter(), and NUnit.ConsoleRunner.ResultReporter.WriteErrorsAndFailuresReport().
_reportIndex
int NUnit.ConsoleRunner.ResultReporter._reportIndex = 0 private
Referenced by NUnit.ConsoleRunner.ResultReporter.WriteErrorsAndFailuresReport(), NUnit.ConsoleRunner.ResultReporter.WriteNotRunReport(), and NUnit.ConsoleRunner.ResultReporter.WriteSingleResult().
EOL_CHARS
readonly char [] NUnit.ConsoleRunner.ResultReporter.EOL_CHARS = new char[] { '\r', '\n' } static private
Referenced by NUnit.ConsoleRunner.ResultReporter.WriteSingleResult().
Property Documentation
Summary
ResultSummary NUnit.ConsoleRunner.ResultReporter.Summary get private set
Referenced by NUnit.ConsoleRunner.ResultReporter.ReportResults(), NUnit.ConsoleRunner.ResultReporter.ResultReporter(), and NUnit.ConsoleRunner.ResultReporter.WriteSummaryReport().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitConsole/nunit3-console/ResultReporter.cs