Doc: IGLib EXTENDED: AForge.Math.Geometry.Tests.GrahamConvexHullTest Class Reference
AForge.Math.Geometry.Tests.GrahamConvexHullTest Class Reference
Public Member Functions
GrahamConvexHullTest ()
void FindHullTest ()
Private Member Functions
void ComparePointsLists (List< IntPoint > list1, List< IntPoint > list2)
Private Attributes
List< IntPoint > pointsList1 = new List<IntPoint>()
List< IntPoint > pointsList2 = new List<IntPoint>()
List< IntPoint > pointsList3 = new List<IntPoint>()
List< IntPoint > pointsList4 = new List<IntPoint>()
List< IntPoint > pointsList5 = new List<IntPoint>()
List< IntPoint > pointsList6 = new List<IntPoint>()
List< IntPoint > pointsList7 = new List<IntPoint>()
List< IntPoint > pointsList8 = new List<IntPoint>()
List< IntPoint > pointsList9 = new List<IntPoint>()
List< IntPoint > expectedHull8 = new List<IntPoint>()
List< List< IntPoint > > pointsLists = new List<List<IntPoint>>()
List< List< IntPoint > > expectedHulls = new List<List<IntPoint>>()
Constructor & Destructor Documentation
GrahamConvexHullTest()
AForge.Math.Geometry.Tests.GrahamConvexHullTest.GrahamConvexHullTest () inline
References AForge.Math.Geometry.Tests.GrahamConvexHullTest.expectedHull8, AForge.Math.Geometry.Tests.GrahamConvexHullTest.expectedHulls, AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsList1, AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsList2, AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsList3, AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsList4, AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsList5, AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsList6, AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsList7, AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsList8, AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsList9, and AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsLists.
Member Function Documentation
FindHullTest()
void AForge.Math.Geometry.Tests.GrahamConvexHullTest.FindHullTest () inline
References AForge.Math.Geometry.Tests.GrahamConvexHullTest.ComparePointsLists(), AForge.Math.Geometry.Tests.GrahamConvexHullTest.expectedHulls, AForge.Math.Geometry.GrahamConvexHull.FindHull(), and AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsLists.
ComparePointsLists()
void AForge.Math.Geometry.Tests.GrahamConvexHullTest.ComparePointsLists (List< IntPoint > list1, List< IntPoint > list2) inline private
Referenced by AForge.Math.Geometry.Tests.GrahamConvexHullTest.FindHullTest().
Member Data Documentation
pointsList1
List<IntPoint> AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsList1 = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.GrahamConvexHullTest.GrahamConvexHullTest().
pointsList2
List<IntPoint> AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsList2 = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.GrahamConvexHullTest.GrahamConvexHullTest().
pointsList3
List<IntPoint> AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsList3 = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.GrahamConvexHullTest.GrahamConvexHullTest().
pointsList4
List<IntPoint> AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsList4 = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.GrahamConvexHullTest.GrahamConvexHullTest().
pointsList5
List<IntPoint> AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsList5 = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.GrahamConvexHullTest.GrahamConvexHullTest().
pointsList6
List<IntPoint> AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsList6 = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.GrahamConvexHullTest.GrahamConvexHullTest().
pointsList7
List<IntPoint> AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsList7 = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.GrahamConvexHullTest.GrahamConvexHullTest().
pointsList8
List<IntPoint> AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsList8 = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.GrahamConvexHullTest.GrahamConvexHullTest().
pointsList9
List<IntPoint> AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsList9 = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.GrahamConvexHullTest.GrahamConvexHullTest().
expectedHull8
List<IntPoint> AForge.Math.Geometry.Tests.GrahamConvexHullTest.expectedHull8 = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.GrahamConvexHullTest.GrahamConvexHullTest().
pointsLists
List<List<IntPoint> > AForge.Math.Geometry.Tests.GrahamConvexHullTest.pointsLists = new List<List<IntPoint>>() private
Referenced by AForge.Math.Geometry.Tests.GrahamConvexHullTest.FindHullTest(), and AForge.Math.Geometry.Tests.GrahamConvexHullTest.GrahamConvexHullTest().
expectedHulls
List<List<IntPoint> > AForge.Math.Geometry.Tests.GrahamConvexHullTest.expectedHulls = new List<List<IntPoint>>() private
Referenced by AForge.Math.Geometry.Tests.GrahamConvexHullTest.FindHullTest(), and AForge.Math.Geometry.Tests.GrahamConvexHullTest.GrahamConvexHullTest().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Unit Tests/AForge.Math.Tests/Geometry/GrahamConvexHullTest.cs