Doc: IGLib EXTENDED: AForge.Imaging.Tests.UnmanagedImageTest Class Reference
AForge.Imaging.Tests.UnmanagedImageTest Class Reference
Public Member Functions
void Collect8bppPixelValuesTest_Grayscale ()
void Collect8bppPixelValuesTest_RGB ()
void CollectActivePixelsTest ()
void SetPixelTest (PixelFormat pixelFormat)
void SetGetPixelGrayscale ()
void SetGetPixelColor (PixelFormat pixelFormat)
void SetPixelsTest (PixelFormat pixelFormat)
void ToManagedImageTest (PixelFormat pixelFormat, int x, int y, byte red, byte green, byte blue)
Member Function Documentation
Collect8bppPixelValuesTest_Grayscale()
void AForge.Imaging.Tests.UnmanagedImageTest.Collect8bppPixelValuesTest_Grayscale () inline
References AForge.Imaging.UnmanagedImage.Collect8bppPixelValues(), AForge.Imaging.UnmanagedImage.Create(), and AForge.Imaging.Drawing.Line().
Collect8bppPixelValuesTest_RGB()
void AForge.Imaging.Tests.UnmanagedImageTest.Collect8bppPixelValuesTest_RGB () inline
References AForge.Imaging.UnmanagedImage.Collect8bppPixelValues(), AForge.Imaging.UnmanagedImage.Create(), and AForge.Imaging.Drawing.Line().
CollectActivePixelsTest()
void AForge.Imaging.Tests.UnmanagedImageTest.CollectActivePixelsTest () inline
References AForge.Imaging.UnmanagedImage.CollectActivePixels(), AForge.Imaging.UnmanagedImage.Create(), AForge.Imaging.Drawing.FillRectangle(), and AForge.Math.Geometry.Rectangle.
SetPixelTest()
void AForge.Imaging.Tests.UnmanagedImageTest.SetPixelTest (PixelFormat pixelFormat) inline
References AForge.Imaging.UnmanagedImage.CollectActivePixels(), AForge.Imaging.UnmanagedImage.Create(), and AForge.Imaging.UnmanagedImage.SetPixel().
SetGetPixelGrayscale()
void AForge.Imaging.Tests.UnmanagedImageTest.SetGetPixelGrayscale () inline
References AForge.Imaging.UnmanagedImage.Create(), AForge.Imaging.UnmanagedImage.GetPixel(), and AForge.Imaging.UnmanagedImage.SetPixel().
SetGetPixelColor()
void AForge.Imaging.Tests.UnmanagedImageTest.SetGetPixelColor (PixelFormat pixelFormat) inline
References AForge.Imaging.UnmanagedImage.Create(), AForge.Imaging.UnmanagedImage.GetPixel(), and AForge.Imaging.UnmanagedImage.SetPixel().
SetPixelsTest()
void AForge.Imaging.Tests.UnmanagedImageTest.SetPixelsTest (PixelFormat pixelFormat) inline
References AForge.Imaging.UnmanagedImage.CollectActivePixels(), AForge.Imaging.UnmanagedImage.Create(), and AForge.Imaging.UnmanagedImage.SetPixels().
ToManagedImageTest()
void AForge.Imaging.Tests.UnmanagedImageTest.ToManagedImageTest (PixelFormat pixelFormat, int x, int y, byte red, byte green, byte blue) inline
References AForge.Imaging.UnmanagedImage.CollectActivePixels(), AForge.Imaging.UnmanagedImage.Create(), AForge.Imaging.UnmanagedImage.Dispose(), AForge.Imaging.UnmanagedImage.FromManagedImage(), AForge.Imaging.UnmanagedImage.SetPixel(), and AForge.Imaging.UnmanagedImage.ToManagedImage().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Unit Tests/AForge.Imaging.Tests/UnmanagedImageTest.cs