Doc: IGLib EXTENDED: IG.Neural.Forms.NeuralInputControl Class Reference
IG.Neural.Forms.NeuralInputControl Class Reference
Control for editing input parameter values.
Public Member Functions
NeuralInputControl (INeuralModel neuralModel)
Constructs the control, with ANN-based model specified.
NeuralInputControl ()
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
DataGridView GetGridControl ()
Returns the DataGridView control that is used for setting values of the input parameters.
void InitializeCells ()
Initializes contents of the DataGridView.
void ClearCells ()
Clears contents of all DataGridView cells.
void ClearDataGrid ()
Removes all the data from the DataGridView.
void ResetToDefault ()
void ResetToCenter ()
void SetValues (IVector values)
Sets the values of input parameters on the DataViewGrid to the elements of the specified vector.
void ShowContextMenuControl (object sender, MouseEventArgs e)
NeuralInputControl (INeuralModel neuralModel)
Constructs the control, with ANN-based model specified.
NeuralInputControl ()
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
DataGridView GetGridControl ()
Returns the DataGridView control that is used for setting values of the input parameters.
void InitializeCells ()
Initializes contents of the DataGridView.
void ClearCells ()
Clears contents of all DataGridView cells.
void ClearDataGrid ()
Removes all the data from the DataGridView.
void ResetToDefault ()
void ResetToCenter ()
void SetValues (IVector values)
Sets the values of input parameters on the DataViewGrid to the elements of the specified vector.
void ShowContextMenuControl (object sender, MouseEventArgs e)
NeuralInputControl (INeuralModel neuralModel)
Constructs the control, with ANN-based model specified.
NeuralInputControl ()
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
DataGridView GetGridControl ()
Returns the DataGridView control that is used for setting values of the input parameters.
void InitializeCells ()
Initializes contents of the DataGridView.
void ClearCells ()
Clears contents of all DataGridView cells.
void ClearDataGrid ()
Removes all the data from the DataGridView.
void ResetToDefault ()
void ResetToCenter ()
void SetValues (IVector values)
Sets the values of input parameters on the DataViewGrid to the elements of the specified vector.
void ShowContextMenuControl (object sender, MouseEventArgs e)
NeuralInputControl (INeuralModel neuralModel)
Constructs the control, with ANN-based model specified.
NeuralInputControl ()
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
DataGridView GetGridControl ()
Returns the DataGridView control that is used for setting values of the input parameters.
void InitializeCells ()
Initializes contents of the DataGridView.
void ClearCells ()
Clears contents of all DataGridView cells.
void ClearDataGrid ()
Removes all the data from the DataGridView.
void ResetToDefault ()
void ResetToCenter ()
void SetValues (IVector values)
Sets the values of input parameters on the DataViewGrid to the elements of the specified vector.
void ShowContextMenuControl (object sender, MouseEventArgs e)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
INeuralModelContainer _neuralModelContainerControl
int _colNumValue = 2
Vector _values
Properties
INeuralModel NeuralModel [get, protected set]
Neural network - based model.
INeuralApproximator TrainedNetwork [get]
Traint artificial neural network.
InputOutputDataDefiniton NeuralDataDefinition [get]
Neural data definition.
int ColNumValue [get, protected set]
Number of DataGrid Column that contains the value.
int NumValues [get]
Current number of values, otained form the DataGridView.
IVector Values [get, protected set]
Vector of current values of input parameters as defined by the DadaGridView.
Properties inherited from IG.Neural.INeuralModelContainer
INeuralModel NeuralModel [get]
Artificial neural network - based model.
Private Member Functions
void NeuralInputControl_MouseClick (object sender, MouseEventArgs e)
void dGridInputParam_MouseClick (object sender, MouseEventArgs e)
void btnResetDefault_Click (object sender, EventArgs e)
void btnResetCenter_Click (object sender, EventArgs e)
void resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e)
void resetToCenterToolStripMenuItem_Click (object sender, EventArgs e)
void dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e)
void btnIdentifyThread_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void NeuralInputControl_MouseClick (object sender, MouseEventArgs e)
void dGridInputParam_MouseClick (object sender, MouseEventArgs e)
void btnResetDefault_Click (object sender, EventArgs e)
void btnResetCenter_Click (object sender, EventArgs e)
void resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e)
void resetToCenterToolStripMenuItem_Click (object sender, EventArgs e)
void dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void NeuralInputControl_MouseClick (object sender, MouseEventArgs e)
void dGridInputParam_MouseClick (object sender, MouseEventArgs e)
void btnResetDefault_Click (object sender, EventArgs e)
void btnResetCenter_Click (object sender, EventArgs e)
void resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e)
void resetToCenterToolStripMenuItem_Click (object sender, EventArgs e)
void dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void NeuralInputControl_MouseClick (object sender, MouseEventArgs e)
void dGridInputParam_MouseClick (object sender, MouseEventArgs e)
void btnResetDefault_Click (object sender, EventArgs e)
void btnResetCenter_Click (object sender, EventArgs e)
void resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e)
void resetToCenterToolStripMenuItem_Click (object sender, EventArgs e)
void dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
INeuralModel _neuralModel
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.DataGridView dGridInputParam
System.Windows.Forms.DataGridViewTextBoxColumn columnID
System.Windows.Forms.DataGridViewTextBoxColumn columnName
System.Windows.Forms.DataGridViewTextBoxColumn columnValue
System.Windows.Forms.Button btnResetDefault
System.Windows.Forms.Button btnResetCenter
System.Windows.Forms.ContextMenuStrip contextMenuControl
System.Windows.Forms.ToolStripMenuItem resetToDefaultToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem resetToCenterToolStripMenuItem
System.Windows.Forms.Button btnIdentifyThread
Detailed Description
Control for editing input parameter values.
$A Igor Apr13;
Constructor & Destructor Documentation
NeuralInputControl() [1/8]
IG.Neural.Forms.NeuralInputControl.NeuralInputControl (INeuralModel neuralModel) inline
Constructs the control, with ANN-based model specified.
Parameters
neuralModel ANN-based model, containing data definitions and trained neural network.
References IG.Neural.Forms.NeuralInputControl.NeuralModel.
NeuralInputControl() [2/8]
IG.Neural.Forms.NeuralInputControl.NeuralInputControl () inline
References IG.Neural.Forms.NeuralInputControl.InitializeComponent().
NeuralInputControl() [3/8]
IG.Neural.Forms.NeuralInputControl.NeuralInputControl (INeuralModel neuralModel) inline
Constructs the control, with ANN-based model specified.
Parameters
neuralModel ANN-based model, containing data definitions and trained neural network.
References IG.Neural.Forms.NeuralInputControl.NeuralModel.
NeuralInputControl() [4/8]
IG.Neural.Forms.NeuralInputControl.NeuralInputControl () inline
References IG.Neural.Forms.NeuralInputControl.InitializeComponent().
NeuralInputControl() [5/8]
IG.Neural.Forms.NeuralInputControl.NeuralInputControl (INeuralModel neuralModel) inline
Constructs the control, with ANN-based model specified.
Parameters
neuralModel ANN-based model, containing data definitions and trained neural network.
References IG.Neural.Forms.NeuralInputControl.NeuralModel.
NeuralInputControl() [6/8]
IG.Neural.Forms.NeuralInputControl.NeuralInputControl () inline
References IG.Neural.Forms.NeuralInputControl.InitializeComponent().
NeuralInputControl() [7/8]
IG.Neural.Forms.NeuralInputControl.NeuralInputControl (INeuralModel neuralModel) inline
Constructs the control, with ANN-based model specified.
Parameters
neuralModel ANN-based model, containing data definitions and trained neural network.
References IG.Neural.Forms.NeuralInputControl.NeuralModel.
NeuralInputControl() [8/8]
IG.Neural.Forms.NeuralInputControl.NeuralInputControl () inline
References IG.Neural.Forms.NeuralInputControl.InitializeComponent().
Member Function Documentation
SetNeuralModel() [1/4]
void IG.Neural.Forms.NeuralInputControl.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
Implements IG.Neural.INeuralModelContainer.
References IG.Neural.Forms.NeuralInputControl.NeuralModel.
GetGridControl() [1/4]
DataGridView IG.Neural.Forms.NeuralInputControl.GetGridControl () inline
Returns the DataGridView control that is used for setting values of the input parameters.
Returns
References IG.Neural.Forms.NeuralInputControl.dGridInputParam.
Referenced by IG.Neural.Forms.NeuralPredictionControl.NeuralPredictionControl().
InitializeCells() [1/4]
void IG.Neural.Forms.NeuralInputControl.InitializeCells () inline
Initializes contents of the DataGridView.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Neural.Forms.NeuralInputControl.dGridInputParam, IG.Num.InputOutputElementDefinition.ElementIndex, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, IG.Neural.Forms.NeuralInputControl.NeuralDataDefinition, and IG.Num.InputOutputElementDefinition.Title.
Referenced by IG.Neural.Forms.NeuralParametricTestSelection.InitializeData(), IG.Neural.Forms.NeuralInputControl.ResetToCenter(), and IG.Neural.Forms.NeuralInputControl.ResetToDefault().
ClearCells() [1/4]
void IG.Neural.Forms.NeuralInputControl.ClearCells () inline
Clears contents of all DataGridView cells.
References IG.Neural.Forms.NeuralInputControl.dGridInputParam, IG.Num.InputOutputDataDefiniton.InputLength, and IG.Neural.Forms.NeuralInputControl.NeuralDataDefinition.
ClearDataGrid() [1/4]
void IG.Neural.Forms.NeuralInputControl.ClearDataGrid () inline
Removes all the data from the DataGridView.
References IG.Neural.Forms.NeuralInputControl.dGridInputParam.
ResetToDefault() [1/4]
void IG.Neural.Forms.NeuralInputControl.ResetToDefault () inline
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Neural.Forms.NeuralInputControl.ColNumValue, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Neural.Forms.NeuralInputControl.dGridInputParam, IG.Neural.Forms.NeuralInputControl.InitializeCells(), IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, and IG.Neural.Forms.NeuralInputControl.NeuralDataDefinition.
Referenced by IG.Neural.Forms.NeuralInputControl.btnResetDefault_Click(), and IG.Neural.Forms.NeuralInputControl.resetToDefaultToolStripMenuItem_Click().
ResetToCenter() [1/4]
void IG.Neural.Forms.NeuralInputControl.ResetToCenter () inline
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Neural.Forms.NeuralInputControl.ColNumValue, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Neural.Forms.NeuralInputControl.dGridInputParam, IG.Neural.Forms.NeuralInputControl.InitializeCells(), IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, and IG.Neural.Forms.NeuralInputControl.NeuralDataDefinition.
Referenced by IG.Neural.Forms.NeuralInputControl.btnResetCenter_Click(), and IG.Neural.Forms.NeuralInputControl.resetToCenterToolStripMenuItem_Click().
SetValues() [1/4]
void IG.Neural.Forms.NeuralInputControl.SetValues (IVector values) inline
Sets the values of input parameters on the DataViewGrid to the elements of the specified vector.
Parameters
values Vectors defining the values to be set.
References IG.Neural.Forms.NeuralInputControl.Values.
ShowContextMenuControl() [1/4]
void IG.Neural.Forms.NeuralInputControl.ShowContextMenuControl (object sender, MouseEventArgs e) inline
References IG.Neural.Forms.NeuralInputControl.contextMenuControl.
Referenced by IG.Neural.Forms.NeuralInputControl.dGridInputParam_MouseClick(), and IG.Neural.Forms.NeuralInputControl.NeuralInputControl_MouseClick().
NeuralInputControl_MouseClick() [1/4]
void IG.Neural.Forms.NeuralInputControl.NeuralInputControl_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ShowContextMenuControl().
dGridInputParam_MouseClick() [1/4]
void IG.Neural.Forms.NeuralInputControl.dGridInputParam_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ShowContextMenuControl().
btnResetDefault_Click() [1/4]
void IG.Neural.Forms.NeuralInputControl.btnResetDefault_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ResetToDefault().
Referenced by IG.Neural.Forms.NeuralInputControl.InitializeComponent().
btnResetCenter_Click() [1/4]
void IG.Neural.Forms.NeuralInputControl.btnResetCenter_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ResetToCenter().
Referenced by IG.Neural.Forms.NeuralInputControl.InitializeComponent().
resetToDefaultToolStripMenuItem_Click() [1/4]
void IG.Neural.Forms.NeuralInputControl.resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ResetToDefault().
resetToCenterToolStripMenuItem_Click() [1/4]
void IG.Neural.Forms.NeuralInputControl.resetToCenterToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ResetToCenter().
dGridInputParam_CellValueChanged() [1/4]
void IG.Neural.Forms.NeuralInputControl.dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.btnResetDefault, and IG.Lib.Util.SleepSeconds().
btnIdentifyThread_Click()
void IG.Neural.Forms.NeuralInputControl.btnIdentifyThread_Click (object sender, EventArgs e) inline private
References IG.Forms.UtilForms.GetCurrentThreadInfo(), and IG.Forms.FadingMessage.Launch().
Dispose() [1/4]
override void IG.Neural.Forms.NeuralInputControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralInputControl.components.
InitializeComponent() [1/4]
void IG.Neural.Forms.NeuralInputControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralInputControl.btnIdentifyThread, IG.Neural.Forms.NeuralInputControl.btnResetCenter, IG.Neural.Forms.NeuralInputControl.btnResetCenter_Click(), IG.Neural.Forms.NeuralInputControl.btnResetDefault, IG.Neural.Forms.NeuralInputControl.btnResetDefault_Click(), IG.Neural.Forms.NeuralInputControl.columnID, IG.Neural.Forms.NeuralInputControl.columnName, IG.Neural.Forms.NeuralInputControl.columnValue, IG.Neural.Forms.NeuralInputControl.components, IG.Neural.Forms.NeuralInputControl.contextMenuControl, IG.Neural.Forms.NeuralInputControl.dGridInputParam, IG.Neural.Forms.NeuralInputControl.groupBox1, IG.Neural.Forms.NeuralInputControl.resetToCenterToolStripMenuItem, and IG.Neural.Forms.NeuralInputControl.resetToDefaultToolStripMenuItem.
Referenced by IG.Neural.Forms.NeuralInputControl.NeuralInputControl().
SetNeuralModel() [2/4]
void IG.Neural.Forms.NeuralInputControl.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
Implements IG.Neural.INeuralModelContainer.
References IG.Neural.Forms.NeuralInputControl.NeuralModel.
GetGridControl() [2/4]
DataGridView IG.Neural.Forms.NeuralInputControl.GetGridControl () inline
Returns the DataGridView control that is used for setting values of the input parameters.
Returns
References IG.Neural.Forms.NeuralInputControl.dGridInputParam.
InitializeCells() [2/4]
void IG.Neural.Forms.NeuralInputControl.InitializeCells () inline
Initializes contents of the DataGridView.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Neural.Forms.NeuralInputControl.dGridInputParam, IG.Num.InputOutputElementDefinition.ElementIndex, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, IG.Neural.Forms.NeuralInputControl.NeuralDataDefinition, and IG.Num.InputOutputElementDefinition.Title.
ClearCells() [2/4]
void IG.Neural.Forms.NeuralInputControl.ClearCells () inline
Clears contents of all DataGridView cells.
References IG.Neural.Forms.NeuralInputControl.dGridInputParam, IG.Num.InputOutputDataDefiniton.InputLength, and IG.Neural.Forms.NeuralInputControl.NeuralDataDefinition.
ClearDataGrid() [2/4]
void IG.Neural.Forms.NeuralInputControl.ClearDataGrid () inline
Removes all the data from the DataGridView.
References IG.Neural.Forms.NeuralInputControl.dGridInputParam.
ResetToDefault() [2/4]
void IG.Neural.Forms.NeuralInputControl.ResetToDefault () inline
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Neural.Forms.NeuralInputControl.ColNumValue, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Neural.Forms.NeuralInputControl.dGridInputParam, IG.Neural.Forms.NeuralInputControl.InitializeCells(), IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, and IG.Neural.Forms.NeuralInputControl.NeuralDataDefinition.
ResetToCenter() [2/4]
void IG.Neural.Forms.NeuralInputControl.ResetToCenter () inline
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Neural.Forms.NeuralInputControl.ColNumValue, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Neural.Forms.NeuralInputControl.dGridInputParam, IG.Neural.Forms.NeuralInputControl.InitializeCells(), IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, and IG.Neural.Forms.NeuralInputControl.NeuralDataDefinition.
SetValues() [2/4]
void IG.Neural.Forms.NeuralInputControl.SetValues (IVector values) inline
Sets the values of input parameters on the DataViewGrid to the elements of the specified vector.
Parameters
values Vectors defining the values to be set.
References IG.Neural.Forms.NeuralInputControl.Values.
ShowContextMenuControl() [2/4]
void IG.Neural.Forms.NeuralInputControl.ShowContextMenuControl (object sender, MouseEventArgs e) inline
References IG.Neural.Forms.NeuralInputControl.contextMenuControl.
NeuralInputControl_MouseClick() [2/4]
void IG.Neural.Forms.NeuralInputControl.NeuralInputControl_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ShowContextMenuControl().
dGridInputParam_MouseClick() [2/4]
void IG.Neural.Forms.NeuralInputControl.dGridInputParam_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ShowContextMenuControl().
btnResetDefault_Click() [2/4]
void IG.Neural.Forms.NeuralInputControl.btnResetDefault_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ResetToDefault().
btnResetCenter_Click() [2/4]
void IG.Neural.Forms.NeuralInputControl.btnResetCenter_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ResetToCenter().
resetToDefaultToolStripMenuItem_Click() [2/4]
void IG.Neural.Forms.NeuralInputControl.resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ResetToDefault().
resetToCenterToolStripMenuItem_Click() [2/4]
void IG.Neural.Forms.NeuralInputControl.resetToCenterToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ResetToCenter().
dGridInputParam_CellValueChanged() [2/4]
void IG.Neural.Forms.NeuralInputControl.dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.btnResetDefault, and IG.Lib.Util.SleepSeconds().
Dispose() [2/4]
override void IG.Neural.Forms.NeuralInputControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralInputControl.components.
InitializeComponent() [2/4]
void IG.Neural.Forms.NeuralInputControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralInputControl.btnResetCenter, IG.Neural.Forms.NeuralInputControl.btnResetCenter_Click(), IG.Neural.Forms.NeuralInputControl.btnResetDefault, IG.Neural.Forms.NeuralInputControl.btnResetDefault_Click(), IG.Neural.Forms.NeuralInputControl.columnID, IG.Neural.Forms.NeuralInputControl.columnName, IG.Neural.Forms.NeuralInputControl.columnValue, IG.Neural.Forms.NeuralInputControl.components, IG.Neural.Forms.NeuralInputControl.contextMenuControl, IG.Neural.Forms.NeuralInputControl.dGridInputParam, IG.Neural.Forms.NeuralInputControl.groupBox1, IG.Neural.Forms.NeuralInputControl.resetToCenterToolStripMenuItem, and IG.Neural.Forms.NeuralInputControl.resetToDefaultToolStripMenuItem.
SetNeuralModel() [3/4]
void IG.Neural.Forms.NeuralInputControl.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
Implements IG.Neural.INeuralModelContainer.
References IG.Neural.Forms.NeuralInputControl.NeuralModel.
GetGridControl() [3/4]
DataGridView IG.Neural.Forms.NeuralInputControl.GetGridControl () inline
Returns the DataGridView control that is used for setting values of the input parameters.
Returns
References IG.Neural.Forms.NeuralInputControl.dGridInputParam.
InitializeCells() [3/4]
void IG.Neural.Forms.NeuralInputControl.InitializeCells () inline
Initializes contents of the DataGridView.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Neural.Forms.NeuralInputControl.dGridInputParam, IG.Num.InputOutputElementDefinition.ElementIndex, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, IG.Neural.Forms.NeuralInputControl.NeuralDataDefinition, and IG.Num.InputOutputElementDefinition.Title.
ClearCells() [3/4]
void IG.Neural.Forms.NeuralInputControl.ClearCells () inline
Clears contents of all DataGridView cells.
References IG.Neural.Forms.NeuralInputControl.dGridInputParam, IG.Num.InputOutputDataDefiniton.InputLength, and IG.Neural.Forms.NeuralInputControl.NeuralDataDefinition.
ClearDataGrid() [3/4]
void IG.Neural.Forms.NeuralInputControl.ClearDataGrid () inline
Removes all the data from the DataGridView.
References IG.Neural.Forms.NeuralInputControl.dGridInputParam.
ResetToDefault() [3/4]
void IG.Neural.Forms.NeuralInputControl.ResetToDefault () inline
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Neural.Forms.NeuralInputControl.ColNumValue, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Neural.Forms.NeuralInputControl.dGridInputParam, IG.Neural.Forms.NeuralInputControl.InitializeCells(), IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, and IG.Neural.Forms.NeuralInputControl.NeuralDataDefinition.
ResetToCenter() [3/4]
void IG.Neural.Forms.NeuralInputControl.ResetToCenter () inline
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Neural.Forms.NeuralInputControl.ColNumValue, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Neural.Forms.NeuralInputControl.dGridInputParam, IG.Neural.Forms.NeuralInputControl.InitializeCells(), IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, and IG.Neural.Forms.NeuralInputControl.NeuralDataDefinition.
SetValues() [3/4]
void IG.Neural.Forms.NeuralInputControl.SetValues (IVector values) inline
Sets the values of input parameters on the DataViewGrid to the elements of the specified vector.
Parameters
values Vectors defining the values to be set.
References IG.Neural.Forms.NeuralInputControl.Values.
ShowContextMenuControl() [3/4]
void IG.Neural.Forms.NeuralInputControl.ShowContextMenuControl (object sender, MouseEventArgs e) inline
References IG.Neural.Forms.NeuralInputControl.contextMenuControl.
NeuralInputControl_MouseClick() [3/4]
void IG.Neural.Forms.NeuralInputControl.NeuralInputControl_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ShowContextMenuControl().
dGridInputParam_MouseClick() [3/4]
void IG.Neural.Forms.NeuralInputControl.dGridInputParam_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ShowContextMenuControl().
btnResetDefault_Click() [3/4]
void IG.Neural.Forms.NeuralInputControl.btnResetDefault_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ResetToDefault().
btnResetCenter_Click() [3/4]
void IG.Neural.Forms.NeuralInputControl.btnResetCenter_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ResetToCenter().
resetToDefaultToolStripMenuItem_Click() [3/4]
void IG.Neural.Forms.NeuralInputControl.resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ResetToDefault().
resetToCenterToolStripMenuItem_Click() [3/4]
void IG.Neural.Forms.NeuralInputControl.resetToCenterToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ResetToCenter().
dGridInputParam_CellValueChanged() [3/4]
void IG.Neural.Forms.NeuralInputControl.dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.btnResetDefault, and IG.Lib.Util.SleepSeconds().
Dispose() [3/4]
override void IG.Neural.Forms.NeuralInputControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralInputControl.components.
InitializeComponent() [3/4]
void IG.Neural.Forms.NeuralInputControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralInputControl.btnResetCenter, IG.Neural.Forms.NeuralInputControl.btnResetCenter_Click(), IG.Neural.Forms.NeuralInputControl.btnResetDefault, IG.Neural.Forms.NeuralInputControl.btnResetDefault_Click(), IG.Neural.Forms.NeuralInputControl.columnID, IG.Neural.Forms.NeuralInputControl.columnName, IG.Neural.Forms.NeuralInputControl.columnValue, IG.Neural.Forms.NeuralInputControl.components, IG.Neural.Forms.NeuralInputControl.contextMenuControl, IG.Neural.Forms.NeuralInputControl.dGridInputParam, IG.Neural.Forms.NeuralInputControl.groupBox1, IG.Neural.Forms.NeuralInputControl.resetToCenterToolStripMenuItem, and IG.Neural.Forms.NeuralInputControl.resetToDefaultToolStripMenuItem.
SetNeuralModel() [4/4]
void IG.Neural.Forms.NeuralInputControl.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
Implements IG.Neural.INeuralModelContainer.
References IG.Neural.Forms.NeuralInputControl.NeuralModel.
GetGridControl() [4/4]
DataGridView IG.Neural.Forms.NeuralInputControl.GetGridControl () inline
Returns the DataGridView control that is used for setting values of the input parameters.
Returns
References IG.Neural.Forms.NeuralInputControl.dGridInputParam.
InitializeCells() [4/4]
void IG.Neural.Forms.NeuralInputControl.InitializeCells () inline
Initializes contents of the DataGridView.
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Neural.Forms.NeuralInputControl.dGridInputParam, IG.Num.InputOutputElementDefinition.ElementIndex, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, IG.Neural.Forms.NeuralInputControl.NeuralDataDefinition, and IG.Num.InputOutputElementDefinition.Title.
ClearCells() [4/4]
void IG.Neural.Forms.NeuralInputControl.ClearCells () inline
Clears contents of all DataGridView cells.
References IG.Neural.Forms.NeuralInputControl.dGridInputParam, IG.Num.InputOutputDataDefiniton.InputLength, and IG.Neural.Forms.NeuralInputControl.NeuralDataDefinition.
ClearDataGrid() [4/4]
void IG.Neural.Forms.NeuralInputControl.ClearDataGrid () inline
Removes all the data from the DataGridView.
References IG.Neural.Forms.NeuralInputControl.dGridInputParam.
ResetToDefault() [4/4]
void IG.Neural.Forms.NeuralInputControl.ResetToDefault () inline
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Neural.Forms.NeuralInputControl.ColNumValue, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Neural.Forms.NeuralInputControl.dGridInputParam, IG.Neural.Forms.NeuralInputControl.InitializeCells(), IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, and IG.Neural.Forms.NeuralInputControl.NeuralDataDefinition.
ResetToCenter() [4/4]
void IG.Neural.Forms.NeuralInputControl.ResetToCenter () inline
References IG.Num.InputOutputElementDefinition.BoundsDefined, IG.Neural.Forms.NeuralInputControl.ColNumValue, IG.Num.InputElementDefinition.DefaultValue, IG.Num.InputElementDefinition.DefaultValueDefined, IG.Neural.Forms.NeuralInputControl.dGridInputParam, IG.Neural.Forms.NeuralInputControl.InitializeCells(), IG.Num.InputOutputDataDefiniton.InputElementList, IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.MaximalValue, IG.Num.InputOutputElementDefinition.MinimalValue, and IG.Neural.Forms.NeuralInputControl.NeuralDataDefinition.
SetValues() [4/4]
void IG.Neural.Forms.NeuralInputControl.SetValues (IVector values) inline
Sets the values of input parameters on the DataViewGrid to the elements of the specified vector.
Parameters
values Vectors defining the values to be set.
References IG.Neural.Forms.NeuralInputControl.Values.
ShowContextMenuControl() [4/4]
void IG.Neural.Forms.NeuralInputControl.ShowContextMenuControl (object sender, MouseEventArgs e) inline
References IG.Neural.Forms.NeuralInputControl.contextMenuControl.
NeuralInputControl_MouseClick() [4/4]
void IG.Neural.Forms.NeuralInputControl.NeuralInputControl_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ShowContextMenuControl().
dGridInputParam_MouseClick() [4/4]
void IG.Neural.Forms.NeuralInputControl.dGridInputParam_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ShowContextMenuControl().
btnResetDefault_Click() [4/4]
void IG.Neural.Forms.NeuralInputControl.btnResetDefault_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ResetToDefault().
btnResetCenter_Click() [4/4]
void IG.Neural.Forms.NeuralInputControl.btnResetCenter_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ResetToCenter().
resetToDefaultToolStripMenuItem_Click() [4/4]
void IG.Neural.Forms.NeuralInputControl.resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ResetToDefault().
resetToCenterToolStripMenuItem_Click() [4/4]
void IG.Neural.Forms.NeuralInputControl.resetToCenterToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.ResetToCenter().
dGridInputParam_CellValueChanged() [4/4]
void IG.Neural.Forms.NeuralInputControl.dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e) inline private
References IG.Neural.Forms.NeuralInputControl.btnResetDefault, and IG.Lib.Util.SleepSeconds().
Dispose() [4/4]
override void IG.Neural.Forms.NeuralInputControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralInputControl.components.
InitializeComponent() [4/4]
void IG.Neural.Forms.NeuralInputControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralInputControl.btnResetCenter, IG.Neural.Forms.NeuralInputControl.btnResetCenter_Click(), IG.Neural.Forms.NeuralInputControl.btnResetDefault, IG.Neural.Forms.NeuralInputControl.btnResetDefault_Click(), IG.Neural.Forms.NeuralInputControl.columnID, IG.Neural.Forms.NeuralInputControl.columnName, IG.Neural.Forms.NeuralInputControl.columnValue, IG.Neural.Forms.NeuralInputControl.components, IG.Neural.Forms.NeuralInputControl.contextMenuControl, IG.Neural.Forms.NeuralInputControl.dGridInputParam, IG.Neural.Forms.NeuralInputControl.groupBox1, IG.Neural.Forms.NeuralInputControl.resetToCenterToolStripMenuItem, and IG.Neural.Forms.NeuralInputControl.resetToDefaultToolStripMenuItem.
Member Data Documentation
_neuralModelContainerControl
INeuralModelContainer IG.Neural.Forms.NeuralInputControl._neuralModelContainerControl protected
_neuralModel
INeuralModel IG.Neural.Forms.NeuralInputControl._neuralModel private
_colNumValue
int IG.Neural.Forms.NeuralInputControl._colNumValue = 2 protected
_values
Vector IG.Neural.Forms.NeuralInputControl._values protected
components
System ComponentModel IContainer IG.Neural.Forms.NeuralInputControl.components = null private
Required designer variable.
Referenced by IG.Neural.Forms.NeuralInputControl.Dispose(), and IG.Neural.Forms.NeuralInputControl.InitializeComponent().
groupBox1
System Windows Forms GroupBox IG.Neural.Forms.NeuralInputControl.groupBox1 private
Referenced by IG.Neural.Forms.NeuralInputControl.InitializeComponent().
dGridInputParam
System Windows Forms DataGridView IG.Neural.Forms.NeuralInputControl.dGridInputParam private
Referenced by IG.Neural.Forms.NeuralInputControl.ClearCells(), IG.Neural.Forms.NeuralInputControl.ClearDataGrid(), IG.Neural.Forms.NeuralInputControl.GetGridControl(), IG.Neural.Forms.NeuralInputControl.InitializeCells(), IG.Neural.Forms.NeuralInputControl.InitializeComponent(), IG.Neural.Forms.NeuralInputControl.ResetToCenter(), and IG.Neural.Forms.NeuralInputControl.ResetToDefault().
columnID
System Windows Forms DataGridViewTextBoxColumn IG.Neural.Forms.NeuralInputControl.columnID private
Referenced by IG.Neural.Forms.NeuralInputControl.InitializeComponent().
columnName
System Windows Forms DataGridViewTextBoxColumn IG.Neural.Forms.NeuralInputControl.columnName private
Referenced by IG.Neural.Forms.NeuralInputControl.InitializeComponent().
columnValue
System Windows Forms DataGridViewTextBoxColumn IG.Neural.Forms.NeuralInputControl.columnValue private
Referenced by IG.Neural.Forms.NeuralInputControl.InitializeComponent().
btnResetDefault
System Windows Forms Button IG.Neural.Forms.NeuralInputControl.btnResetDefault private
Referenced by IG.Neural.Forms.NeuralInputControl.dGridInputParam_CellValueChanged(), and IG.Neural.Forms.NeuralInputControl.InitializeComponent().
btnResetCenter
System Windows Forms Button IG.Neural.Forms.NeuralInputControl.btnResetCenter private
Referenced by IG.Neural.Forms.NeuralInputControl.InitializeComponent().
contextMenuControl
System Windows Forms ContextMenuStrip IG.Neural.Forms.NeuralInputControl.contextMenuControl private
Referenced by IG.Neural.Forms.NeuralInputControl.InitializeComponent(), and IG.Neural.Forms.NeuralInputControl.ShowContextMenuControl().
resetToDefaultToolStripMenuItem
System Windows Forms ToolStripMenuItem IG.Neural.Forms.NeuralInputControl.resetToDefaultToolStripMenuItem private
Referenced by IG.Neural.Forms.NeuralInputControl.InitializeComponent().
resetToCenterToolStripMenuItem
System Windows Forms ToolStripMenuItem IG.Neural.Forms.NeuralInputControl.resetToCenterToolStripMenuItem private
Referenced by IG.Neural.Forms.NeuralInputControl.InitializeComponent().
btnIdentifyThread
System.Windows.Forms.Button IG.Neural.Forms.NeuralInputControl.btnIdentifyThread private
Referenced by IG.Neural.Forms.NeuralInputControl.InitializeComponent().
Property Documentation
NeuralModel
INeuralModel IG.Neural.Forms.NeuralInputControl.NeuralModel get protected set
Neural network - based model.
Contains data definition and trained neural network approximator.
Referenced by IG.Neural.Forms.NeuralInputControl.NeuralInputControl(), and IG.Neural.Forms.NeuralInputControl.SetNeuralModel().
TrainedNetwork
INeuralApproximator IG.Neural.Forms.NeuralInputControl.TrainedNetwork get
Traint artificial neural network.
NeuralDataDefinition
InputOutputDataDefiniton IG.Neural.Forms.NeuralInputControl.NeuralDataDefinition get
Neural data definition.
Referenced by IG.Neural.Forms.NeuralInputControl.ClearCells(), IG.Neural.Forms.NeuralInputControl.InitializeCells(), IG.Neural.Forms.NeuralInputControl.ResetToCenter(), and IG.Neural.Forms.NeuralInputControl.ResetToDefault().
ColNumValue
int IG.Neural.Forms.NeuralInputControl.ColNumValue get protected set
Number of DataGrid Column that contains the value.
Referenced by IG.Neural.Forms.NeuralInputControl.ResetToCenter(), and IG.Neural.Forms.NeuralInputControl.ResetToDefault().
NumValues
int IG.Neural.Forms.NeuralInputControl.NumValues get
Current number of values, otained form the DataGridView.
Values
IVector IG.Neural.Forms.NeuralInputControl.Values get protected set
Vector of current values of input parameters as defined by the DadaGridView.
Referenced by IG.Neural.Forms.NeuralPredictionControl.btnPredict_Click(), and IG.Neural.Forms.NeuralInputControl.SetValues().
The documentation for this class was generated from the following files:
shelldev/extensions/ExtAppAnnApp/ResponseForms/NeuralInputControl.cs
shelldev/extensions/ExtAppAnnApp/ResponseForms/NeuralInputControl.Designer.cs