Doc: IGLib EXTENDED: NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates Class Reference
NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates Class Reference
Public Member Functions
void TrueTest ()
void EqualToTest ()
void SameAsTest ()
void GreaterTest ()
void HasMemberTest ()
void NullTest ()
void TextTest ()
Public Member Functions inherited from NUnit.Framework.Syntax.AfterSyntaxTests
void InitializeValues ()
Additional Inherited Members
Protected Attributes inherited from NUnit.Framework.Syntax.AfterSyntaxTests
bool flag
int num
object ob1
List< object > list
string greeting
Member Function Documentation
TrueTest()
void NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates.TrueTest () inline
References NUnit.Framework.Syntax.AfterSyntaxTests.flag, NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
EqualToTest()
void NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates.EqualToTest () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Syntax.AfterSyntaxTests.num, and NUnit.Framework.Assert.That().
SameAsTest()
void NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates.SameAsTest () inline
References NUnit.Framework.Syntax.AfterSyntaxTests.ob1, NUnit.Framework.Syntax.AfterSyntaxTests.ob2, NUnit.Framework.Is.SameAs(), and NUnit.Framework.Assert.That().
GreaterTest()
void NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates.GreaterTest () inline
References NUnit.Framework.Is.GreaterThan(), NUnit.Framework.Syntax.AfterSyntaxTests.num, and NUnit.Framework.Assert.That().
HasMemberTest()
void NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates.HasMemberTest () inline
References NUnit.Framework.Syntax.AfterSyntaxTests.list, NUnit.Framework.Has.Member(), and NUnit.Framework.Assert.That().
NullTest()
void NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates.NullTest () inline
References NUnit.Framework.Is.Null, NUnit.Framework.Syntax.AfterSyntaxTests.ob3, and NUnit.Framework.Assert.That().
TextTest()
void NUnit.Framework.Syntax.AfterSyntaxUsingAnonymousDelegates.TextTest () inline
References NUnit.Framework.Does.EndWith(), NUnit.Framework.Syntax.AfterSyntaxTests.greeting, and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Syntax/AfterTests.cs