Doc: IGLib EXTENDED: AForge.Imaging.Filters.FilterIterator Class Reference
AForge.Imaging.Filters.FilterIterator Class Reference
Filter iterator.
Public Member Functions
FilterIterator (IFilter baseFilter)
Initializes a new instance of the FilterIterator class.
FilterIterator (IFilter baseFilter, int iterations)
Initializes a new instance of the FilterIterator class.
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
Properties
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
IFilter BaseFilter [get, set]
Base filter.
int Iterations [get, set]
Iterations amount, [1, 255].
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
IFilter baseFilter
int iterations = 1
Detailed Description
Filter iterator.
Filter iterator performs specified amount of filter's iterations. The filter take the specified base filter and applies it to source image specified amount of times.
<note>The filter itself does not have any restrictions to pixel format of source image. This is set by base filter.</note>
<note>The filter does image processing using only IFilter interface of the specified base filter. This means that this filter may not utilize all potential features of the base filter, like in-place processing (see IInPlaceFilter) and region based processing (see IInPlacePartialFilter). To utilize those features, it is required to do filter's iteration manually.</note>
Sample usage (morphological thinning):
// create filter sequence
FiltersSequence filterSequence = new FiltersSequence();
// add 8 thinning filters with different structuring elements
filterSequence.Add(new HitAndMiss(
    new short [,] { { 0, 0, 0 }, { -1, 1, -1 }, { 1, 1, 1 } },
    HitAndMiss.Modes.Thinning ) );
filterSequence.Add(new HitAndMiss(
    new short [,] { { -1, 0, 0 }, { 1, 1, 0 }, { -1, 1, -1 } },
    HitAndMiss.Modes.Thinning ) );
filterSequence.Add(new HitAndMiss(
    new short [,] { { 1, -1, 0 }, { 1, 1, 0 }, { 1, -1, 0 } },
    HitAndMiss.Modes.Thinning ) );
filterSequence.Add(new HitAndMiss(
    new short [,] { { -1, 1, -1 }, { 1, 1, 0 }, { -1, 0, 0 } },
    HitAndMiss.Modes.Thinning ) );
filterSequence.Add(new HitAndMiss(
    new short [,] { { 1, 1, 1 }, { -1, 1, -1 }, { 0, 0, 0 } },
    HitAndMiss.Modes.Thinning ) );
filterSequence.Add(new HitAndMiss(
    new short [,] { { -1, 1, -1 }, { 0, 1, 1 }, { 0, 0, -1 } },
    HitAndMiss.Modes.Thinning ) );
filterSequence.Add(new HitAndMiss(
    new short [,] { { 0, -1, 1 }, { 0, 1, 1 }, { 0, -1, 1 } },
    HitAndMiss.Modes.Thinning ) );
filterSequence.Add(new HitAndMiss(
    new short [,] { { 0, 0, -1 }, { 0, 1, 1 }, { -1, 1, -1 } },
    HitAndMiss.Modes.Thinning ) );
// create filter iterator for 10 iterations
FilterIterator filter = new FilterIterator(filterSequence, 10);
// apply the filter
Bitmap newImage = filter.Apply(image);
Initial image:
Result image:
Constructor & Destructor Documentation
FilterIterator() [1/2]
AForge.Imaging.Filters.FilterIterator.FilterIterator (IFilter baseFilter) inline
Initializes a new instance of the FilterIterator class.
Parameters
baseFilter Filter to iterate.
References AForge.Imaging.Filters.FilterIterator.baseFilter.
FilterIterator() [2/2]
AForge.Imaging.Filters.FilterIterator.FilterIterator (IFilter baseFilter, int iterations) inline
Initializes a new instance of the FilterIterator class.
Parameters
baseFilter Filter to iterate.
iterations Iterations amount.
References AForge.Imaging.Filters.FilterIterator.baseFilter, and AForge.Imaging.Filters.FilterIterator.iterations.
Member Function Documentation
Apply() [1/4]
Bitmap AForge.Imaging.Filters.FilterIterator.Apply (Bitmap image) inline
Apply filter to an image.
Parameters
image Source image to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The method keeps the source image unchanged and returns the result of image processing filter as new image.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Math.Geometry.Rectangle.
Apply() [2/4]
Bitmap AForge.Imaging.Filters.FilterIterator.Apply (BitmapData imageData) inline
Apply filter to an image.
Parameters
imageData Source image to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The filter accepts bitmap data as input and returns the result of image processing filter as new image. The source image data are kept unchanged.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.IFilter.Apply(), AForge.Imaging.Filters.FilterIterator.baseFilter, and AForge.Imaging.Filters.FilterIterator.iterations.
Apply() [3/4]
UnmanagedImage AForge.Imaging.Filters.FilterIterator.Apply (UnmanagedImage image) inline
Apply filter to an image in unmanaged memory.
Parameters
image Source image in unmanaged memory to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The method keeps the source image unchanged and returns the result of image processing filter as new image.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.IFilter.Apply(), AForge.Imaging.Filters.FilterIterator.baseFilter, AForge.Imaging.UnmanagedImage.Dispose(), and AForge.Imaging.Filters.FilterIterator.iterations.
Apply() [4/4]
void AForge.Imaging.Filters.FilterIterator.Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage) inline
Apply filter to an image in unmanaged memory.
Parameters
sourceImage Source image in unmanaged memory to apply filter to.
destinationImage Destination image in unmanaged memory to put result into.
The method keeps the source image unchanged and puts result of image processing into destination image.
<note>The destination image must have the same width and height as source image. Also destination image must have pixel format, which is expected by particular filter (see FormatTranslations property for information about pixel format conversions).</note>
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.IFilter.Apply(), AForge.Imaging.Filters.FilterIterator.baseFilter, AForge.Imaging.UnmanagedImage.Dispose(), and AForge.Imaging.Filters.FilterIterator.iterations.
Member Data Documentation
baseFilter
IFilter AForge.Imaging.Filters.FilterIterator.baseFilter private
Referenced by AForge.Imaging.Filters.FilterIterator.Apply(), and AForge.Imaging.Filters.FilterIterator.FilterIterator().
iterations
int AForge.Imaging.Filters.FilterIterator.iterations = 1 private
Referenced by AForge.Imaging.Filters.FilterIterator.Apply(), and AForge.Imaging.Filters.FilterIterator.FilterIterator().
Property Documentation
FormatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.FilterIterator.FormatTranslations get
Format translations dictionary.
See IFilterInformation.FormatTranslations documentation for additional information.
<note>The filter provides format translation dictionary taken from BaseFilter filter.</note>
BaseFilter
IFilter AForge.Imaging.Filters.FilterIterator.BaseFilter get set
Base filter.
The base filter is the filter to be applied specified amount of iterations to a specified image.
Iterations
int AForge.Imaging.Filters.FilterIterator.Iterations get set
Iterations amount, [1, 255].
The amount of times to apply specified filter to a specified image.
Default value is set to 1.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/FilterIterator.cs