Doc: IGLib EXTENDED: IG.Test.Program_IGTestQuick.Form1 Class Reference
IG.Test.Program_IGTestQuick.Form1 Class Reference
TEST Class: This class demonstrates how async / await patterns can be used on custom Forms. It needs at least .NET 4.5 to run!!
Public Member Functions
Form1 ()
Private Member Functions
async void button1_Click (object sender, EventArgs e)
async Task ExampleMethodAsync ()
Private Attributes
System.Windows.Forms.TextBox textBox1 = new System.Windows.Forms.TextBox()
Detailed Description
TEST Class: This class demonstrates how async / await patterns can be used on custom Forms. It needs at least .NET 4.5 to run!!
Constructor & Destructor Documentation
Form1()
IG.Test.Program_IGTestQuick.Form1.Form1 () inline
Member Function Documentation
button1_Click()
async void IG.Test.Program_IGTestQuick.Form1.button1_Click (object sender, EventArgs e) inline private
References IG.Test.Program_IGTestQuick.Form1.ExampleMethodAsync(), and IG.Test.Program_IGTestQuick.Form1.textBox1.
ExampleMethodAsync()
async Task IG.Test.Program_IGTestQuick.Form1.ExampleMethodAsync () inline private
Referenced by IG.Test.Program_IGTestQuick.Form1.button1_Click().
Member Data Documentation
textBox1
System.Windows.Forms.TextBox IG.Test.Program_IGTestQuick.Form1.textBox1 = new System.Windows.Forms.TextBox() private
Referenced by IG.Test.Program_IGTestQuick.Form1.button1_Click().
The documentation for this class was generated from the following file:
unittests/Guest_IGTestQuick/Program_IGTestQuick.cs