Doc: IGLib EXTENDED: NUnit.Framework.Internal.Filters.NotFilterTests Class Reference
NUnit.Framework.Internal.Filters.NotFilterTests Class Reference
Public Member Functions
void IsNotEmpty ()
void MatchTest ()
void PassTest ()
void ExplicitMatchTest ()
void BuildFromXml ()
Public Member Functions inherited from NUnit.Framework.Internal.Filters.TestFilterTests
void SetUpSuite ()
Additional Inherited Members
Static Public Attributes inherited from NUnit.Framework.Internal.Filters.TestFilterTests
const string DUMMY_CLASS = "NUnit.Framework.Internal.Filters.TestFilterTests+DummyFixture"
Protected Attributes inherited from NUnit.Framework.Internal.Filters.TestFilterTests
readonly TestSuite _dummyFixture = TestBuilder.MakeFixture(typeof(DummyFixture))
readonly TestSuite _anotherFixture = TestBuilder.MakeFixture(typeof(AnotherFixture))
readonly TestSuite _yetAnotherFixture = TestBuilder.MakeFixture(typeof(YetAnotherFixture))
readonly TestSuite _fixtureWithMultipleTests = TestBuilder.MakeFixture (typeof (FixtureWithMultipleTests))
readonly TestSuite _topLevelSuite = new TestSuite("MySuite")
Member Function Documentation
IsNotEmpty()
void NUnit.Framework.Internal.Filters.NotFilterTests.IsNotEmpty () inline
References NUnit.Framework.Assert.False().
MatchTest()
void NUnit.Framework.Internal.Filters.NotFilterTests.MatchTest () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Internal.Filters.TestFilterTests._fixtureWithMultipleTests, NUnit.Framework.Internal.Filters.TestFilterTests._topLevelSuite, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestSuite.Tests, and NUnit.Framework.Assert.True().
PassTest()
void NUnit.Framework.Internal.Filters.NotFilterTests.PassTest () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Internal.Filters.TestFilterTests._fixtureWithMultipleTests, NUnit.Framework.Internal.Filters.TestFilterTests._topLevelSuite, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestSuite.Tests, and NUnit.Framework.Assert.True().
ExplicitMatchTest()
void NUnit.Framework.Internal.Filters.NotFilterTests.ExplicitMatchTest () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Internal.Filters.TestFilterTests._topLevelSuite, NUnit.Framework.Assert.False(), and NUnit.Framework.Internal.TestSuite.Tests.
BuildFromXml()
void NUnit.Framework.Internal.Filters.NotFilterTests.BuildFromXml () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Internal.TestFilter.Match(), NUnit.Framework.Has.Property(), NUnit.Framework.Assert.That(), NUnit.Framework.Assert.True(), and NUnit.Framework.Is.TypeOf().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/Filters/NotFilterTests.cs