Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DROT Class Reference
DotNumerics.LinearAlgebra.CSLapack.DROT Class Reference
Public Member Functions
DROT ()
void Run (int N, ref double[] DX, int offset_dx, int INCX, ref double[] DY, int offset_dy, int INCY, double C, double S)
Constructor & Destructor Documentation
DROT()
DotNumerics.LinearAlgebra.CSLapack.DROT.DROT () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DROT.Run (int N, ref double[] DX, int offset_dx, int INCX, ref double[] DY, int offset_dy, int INCY, double C, double S) inline
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAEDA.Run(), DotNumerics.LinearAlgebra.CSLapack.DSBTRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAEXC.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAHQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED8.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALSD.Run(), DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD7.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALS0.Run(), and DotNumerics.LinearAlgebra.CSLapack.DTGSJA.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/drot.cs