Doc: IGLib EXTENDED: AForge.Imaging.ImageStatisticsYCbCr Class Reference
AForge.Imaging.ImageStatisticsYCbCr Class Reference
Gather statistics about image in YCbCr color space.
Public Member Functions
ImageStatisticsYCbCr (Bitmap image)
Initializes a new instance of the ImageStatisticsYCbCr class.
ImageStatisticsYCbCr (Bitmap image, Bitmap mask)
Initializes a new instance of the ImageStatisticsYCbCr class.
ImageStatisticsYCbCr (Bitmap image, byte[,] mask)
Initializes a new instance of the ImageStatisticsYCbCr class.
ImageStatisticsYCbCr (UnmanagedImage image)
Initializes a new instance of the ImageStatisticsYCbCr class.
ImageStatisticsYCbCr (UnmanagedImage image, UnmanagedImage mask)
Initializes a new instance of the ImageStatisticsYCbCr class.
ImageStatisticsYCbCr (UnmanagedImage image, byte[,] mask)
Initializes a new instance of the ImageStatisticsYCbCr class.
Properties
ContinuousHistogram Y [get]
Histogram of Y channel.
ContinuousHistogram Cb [get]
Histogram of Cb channel.
ContinuousHistogram Cr [get]
Histogram of Cr channel.
ContinuousHistogram YWithoutBlack [get]
Histogram of Y channel excluding black pixels.
ContinuousHistogram CbWithoutBlack [get]
Histogram of Cb channel excluding black pixels
ContinuousHistogram CrWithoutBlack [get]
Histogram of Cr channel excluding black pixels
int PixelsCount [get]
Total pixels count in the processed image.
int PixelsCountWithoutBlack [get]
Total pixels count in the processed image excluding black pixels.
Private Member Functions
unsafe void ProcessImage (UnmanagedImage image, byte *mask, int maskLineSize)
void CheckSourceFormat (PixelFormat pixelFormat)
void CheckMaskProperties (PixelFormat maskFormat, Size maskSize, Size sourceImageSize)
Private Attributes
ContinuousHistogram yHistogram
ContinuousHistogram cbHistogram
ContinuousHistogram crHistogram
ContinuousHistogram yHistogramWithoutBlack
ContinuousHistogram cbHistogramWithoutBlack
ContinuousHistogram crHistogramWithoutBlack
int pixels
int pixelsWithoutBlack
Detailed Description
Gather statistics about image in YCbCr color space.
The class is used to accumulate statistical values about images, like histogram, mean, standard deviation, etc. for each YCbCr color channel.
The class accepts 24 and 32 bpp color images for processing.
Sample usage:
// gather statistics
ImageStatisticsYCbCr stat = new ImageStatisticsYCbCr(image);
// get Y channel's histogram
ContinuousHistogram y = stat.Y;
// check mean value of Y channel
if (y.Mean > 0.5)
{
    // do further processing
}
See also
AForge.Math.ContinuousHistogram
Constructor & Destructor Documentation
ImageStatisticsYCbCr() [1/6]
AForge.Imaging.ImageStatisticsYCbCr.ImageStatisticsYCbCr (Bitmap image) inline
Initializes a new instance of the ImageStatisticsYCbCr class.
Parameters
image Image to gather statistics about.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported.
References AForge.Imaging.ImageStatisticsYCbCr.CheckSourceFormat(), AForge.Imaging.ImageStatisticsYCbCr.ProcessImage(), and AForge.Math.Geometry.Rectangle.
ImageStatisticsYCbCr() [2/6]
AForge.Imaging.ImageStatisticsYCbCr.ImageStatisticsYCbCr (Bitmap image, Bitmap mask) inline
Initializes a new instance of the ImageStatisticsYCbCr class.
Parameters
image Image to gather statistics about.
mask Mask image which specifies areas to collect statistics for.
The mask image must be a grayscale/binary (8bpp) image of the same size as the specified source image, where black pixels (value 0) correspond to areas which should be excluded from processing. So statistics is calculated only for pixels, which are none black in the mask image.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported.
ArgumentException Mask image must be 8 bpp grayscale image.
ArgumentException Mask must have the same size as the source image to get statistics for.
References AForge.Imaging.ImageStatisticsYCbCr.CheckMaskProperties(), AForge.Imaging.ImageStatisticsYCbCr.CheckSourceFormat(), AForge.Imaging.ImageStatisticsYCbCr.ProcessImage(), AForge.Math.Geometry.Rectangle, AForge.Imaging.Size, and AForge.Imaging.UnmanagedImage.Stride.
ImageStatisticsYCbCr() [3/6]
AForge.Imaging.ImageStatisticsYCbCr.ImageStatisticsYCbCr (Bitmap image, byte mask[,]) inline
Initializes a new instance of the ImageStatisticsYCbCr class.
Parameters
image Image to gather statistics about.
mask Mask array which specifies areas to collect statistics for.
The mask array must be of the same size as the specified source image, where 0 values correspond to areas which should be excluded from processing. So statistics is calculated only for pixels, which have none zero corresponding value in the mask.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported.
ArgumentException Mask must have the same size as the source image to get statistics for.
References AForge.Imaging.ImageStatisticsYCbCr.CheckMaskProperties(), AForge.Imaging.ImageStatisticsYCbCr.CheckSourceFormat(), AForge.Imaging.ImageStatisticsYCbCr.ProcessImage(), AForge.Math.Geometry.Rectangle, and AForge.Imaging.Size.
ImageStatisticsYCbCr() [4/6]
AForge.Imaging.ImageStatisticsYCbCr.ImageStatisticsYCbCr (UnmanagedImage image) inline
Initializes a new instance of the ImageStatisticsYCbCr class.
Parameters
image Unmanaged image to gather statistics about.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported.
References AForge.Imaging.ImageStatisticsYCbCr.CheckSourceFormat(), AForge.Imaging.UnmanagedImage.PixelFormat, and AForge.Imaging.ImageStatisticsYCbCr.ProcessImage().
ImageStatisticsYCbCr() [5/6]
AForge.Imaging.ImageStatisticsYCbCr.ImageStatisticsYCbCr (UnmanagedImage image, UnmanagedImage mask) inline
Initializes a new instance of the ImageStatisticsYCbCr class.
Parameters
image Image to gather statistics about.
mask Mask image which specifies areas to collect statistics for.
The mask image must be a grayscale/binary (8bpp) image of the same size as the specified source image, where black pixels (value 0) correspond to areas which should be excluded from processing. So statistics is calculated only for pixels, which are none black in the mask image.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported.
ArgumentException Mask image must be 8 bpp grayscale image.
ArgumentException Mask must have the same size as the source image to get statistics for.
References AForge.Imaging.ImageStatisticsYCbCr.CheckMaskProperties(), AForge.Imaging.ImageStatisticsYCbCr.CheckSourceFormat(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.ImageStatisticsYCbCr.ProcessImage(), AForge.Imaging.Size, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
ImageStatisticsYCbCr() [6/6]
AForge.Imaging.ImageStatisticsYCbCr.ImageStatisticsYCbCr (UnmanagedImage image, byte mask[,]) inline
Initializes a new instance of the ImageStatisticsYCbCr class.
Parameters
image Image to gather statistics about.
mask Mask array which specifies areas to collect statistics for.
The mask array must be of the same size as the specified source image, where 0 values correspond to areas which should be excluded from processing. So statistics is calculated only for pixels, which have none zero corresponding value in the mask.
Exceptions
UnsupportedImageFormatException Source pixel format is not supported.
ArgumentException Mask must have the same size as the source image to get statistics for.
References AForge.Imaging.ImageStatisticsYCbCr.CheckMaskProperties(), AForge.Imaging.ImageStatisticsYCbCr.CheckSourceFormat(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.ImageStatisticsYCbCr.ProcessImage(), AForge.Imaging.Size, and AForge.Imaging.UnmanagedImage.Width.
Member Function Documentation
ProcessImage()
unsafe void AForge.Imaging.ImageStatisticsYCbCr.ProcessImage (UnmanagedImage image, byte * mask, int maskLineSize) inline private
References AForge.Imaging.RGB.B, AForge.Imaging.RGB.Blue, AForge.Imaging.YCbCr.Cb, AForge.Imaging.ImageStatisticsYCbCr.cbHistogram, AForge.Imaging.ImageStatisticsYCbCr.cbHistogramWithoutBlack, AForge.Imaging.YCbCr.Cr, AForge.Imaging.ImageStatisticsYCbCr.crHistogram, AForge.Imaging.ImageStatisticsYCbCr.crHistogramWithoutBlack, AForge.Imaging.YCbCr.FromRGB(), AForge.Imaging.RGB.G, AForge.Imaging.RGB.Green, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.ImageStatisticsYCbCr.pixels, AForge.Imaging.ImageStatisticsYCbCr.pixelsWithoutBlack, AForge.Imaging.RGB.R, AForge.Imaging.RGB.Red, AForge.Imaging.UnmanagedImage.Stride, AForge.Imaging.UnmanagedImage.Width, AForge.Imaging.YCbCr.Y, AForge.Imaging.ImageStatisticsYCbCr.yHistogram, and AForge.Imaging.ImageStatisticsYCbCr.yHistogramWithoutBlack.
Referenced by AForge.Imaging.ImageStatisticsYCbCr.ImageStatisticsYCbCr().
CheckSourceFormat()
void AForge.Imaging.ImageStatisticsYCbCr.CheckSourceFormat (PixelFormat pixelFormat) inline private
Referenced by AForge.Imaging.ImageStatisticsYCbCr.ImageStatisticsYCbCr().
CheckMaskProperties()
void AForge.Imaging.ImageStatisticsYCbCr.CheckMaskProperties (PixelFormat maskFormat, Size maskSize, Size sourceImageSize) inline private
Referenced by AForge.Imaging.ImageStatisticsYCbCr.ImageStatisticsYCbCr().
Member Data Documentation
yHistogram
ContinuousHistogram AForge.Imaging.ImageStatisticsYCbCr.yHistogram private
Referenced by AForge.Imaging.ImageStatisticsYCbCr.ProcessImage().
cbHistogram
ContinuousHistogram AForge.Imaging.ImageStatisticsYCbCr.cbHistogram private
Referenced by AForge.Imaging.ImageStatisticsYCbCr.ProcessImage().
crHistogram
ContinuousHistogram AForge.Imaging.ImageStatisticsYCbCr.crHistogram private
Referenced by AForge.Imaging.ImageStatisticsYCbCr.ProcessImage().
yHistogramWithoutBlack
ContinuousHistogram AForge.Imaging.ImageStatisticsYCbCr.yHistogramWithoutBlack private
Referenced by AForge.Imaging.ImageStatisticsYCbCr.ProcessImage().
cbHistogramWithoutBlack
ContinuousHistogram AForge.Imaging.ImageStatisticsYCbCr.cbHistogramWithoutBlack private
Referenced by AForge.Imaging.ImageStatisticsYCbCr.ProcessImage().
crHistogramWithoutBlack
ContinuousHistogram AForge.Imaging.ImageStatisticsYCbCr.crHistogramWithoutBlack private
Referenced by AForge.Imaging.ImageStatisticsYCbCr.ProcessImage().
pixels
int AForge.Imaging.ImageStatisticsYCbCr.pixels private
Referenced by AForge.Imaging.ImageStatisticsYCbCr.ProcessImage().
pixelsWithoutBlack
int AForge.Imaging.ImageStatisticsYCbCr.pixelsWithoutBlack private
Referenced by AForge.Imaging.ImageStatisticsYCbCr.ProcessImage().
Property Documentation
Y
ContinuousHistogram AForge.Imaging.ImageStatisticsYCbCr.Y get
Histogram of Y channel.
Cb
ContinuousHistogram AForge.Imaging.ImageStatisticsYCbCr.Cb get
Histogram of Cb channel.
Cr
ContinuousHistogram AForge.Imaging.ImageStatisticsYCbCr.Cr get
Histogram of Cr channel.
YWithoutBlack
ContinuousHistogram AForge.Imaging.ImageStatisticsYCbCr.YWithoutBlack get
Histogram of Y channel excluding black pixels.
The property keeps statistics about Y channel, which excludes all black pixels, what affects mean, standard deviation, etc.
CbWithoutBlack
ContinuousHistogram AForge.Imaging.ImageStatisticsYCbCr.CbWithoutBlack get
Histogram of Cb channel excluding black pixels
The property keeps statistics about Cb channel, which excludes all black pixels, what affects mean, standard deviation, etc.
CrWithoutBlack
ContinuousHistogram AForge.Imaging.ImageStatisticsYCbCr.CrWithoutBlack get
Histogram of Cr channel excluding black pixels
The property keeps statistics about Cr channel, which excludes all black pixels, what affects mean, standard deviation, etc.
PixelsCount
int AForge.Imaging.ImageStatisticsYCbCr.PixelsCount get
Total pixels count in the processed image.
PixelsCountWithoutBlack
int AForge.Imaging.ImageStatisticsYCbCr.PixelsCountWithoutBlack get
Total pixels count in the processed image excluding black pixels.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/ImageStatisticsYCbCr.cs