Doc: IGLib EXTENDED: alglib.testlegendreunit Class Reference
alglib.testlegendreunit Class Reference
Static Public Member Functions
static bool testlegendre (bool silent)
static bool testlegendre (bool silent)
static bool _pexec_testlegendre (bool silent)
Member Function Documentation
testlegendre() [1/2]
static bool alglib.testlegendreunit.testlegendre (bool silent) inline static
References alglib.legendre.legendrecalculate(), alglib.legendre.legendrecoefficients(), alglib.legendre.legendresum(), and alglib.math.randomreal().
Referenced by alglib.testlegendreunit._pexec_testlegendre(), and _Test.Main().
testlegendre() [2/2]
static bool alglib.testlegendreunit.testlegendre (bool silent) inline static
References alglib.legendre.legendrecalculate(), alglib.legendre.legendrecoefficients(), alglib.legendre.legendresum(), and alglib.math.randomreal().
_pexec_testlegendre()
static bool alglib.testlegendreunit._pexec_testlegendre (bool silent) inline static
References alglib.testlegendreunit.testlegendre().
Referenced by _Test.Main().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs