Doc: IGLib EXTENDED: AForge.Controls.HuePicker Class Reference
AForge.Controls.HuePicker Class Reference
Hue picker control.
Public Types
enum HuePickerType { HuePickerType.Value, HuePickerType.Range }
Enumeration of hue picker types.
Public Member Functions
HuePicker ()
Initializes a new instance of the HuePicker class.
Protected Member Functions
override void Dispose (bool disposing)
Dispose the object.
override void OnPaint (PaintEventArgs pe)
Paint the controls.
Properties
int Value [get, set]
Selected value of the hue picker control in HuePickerType.Value mode.
int Min [get, set]
Minimum selected value of the hue picker control in HuePickerType.Range mode.
int Max [get, set]
Maximum selected value of the hue picker control in HuePickerType.Range mode.
HuePickerType Type [get, set]
Current type of the hue picker control.
Events
EventHandler ValuesChanged
An event, to notify about changes of Min or Max properties.
Private Member Functions
void InitializeComponent ()
void HSLPicker_MouseDown (object sender, System.Windows.Forms.MouseEventArgs e)
void HSLPicker_MouseUp (object sender, System.Windows.Forms.MouseEventArgs e)
void HSLPicker_MouseMove (object sender, System.Windows.Forms.MouseEventArgs e)
Private Attributes
HuePickerType type = HuePickerType.Value
Pen blackPen
Brush blackBrush
Pen whitePen
Brush whiteBrush
System.Drawing.Point ptCenter = new System.Drawing.Point(0, 0)
System.Drawing.Point ptMin = new System.Drawing.Point(0, 0)
System.Drawing.Point ptMax = new System.Drawing.Point(0, 0)
int trackMode = 0
int min = 0
int max = 359
Detailed Description
Hue picker control.
The control allows selecting hue value (or range) from HSL color space. Hue values are integer values in the [0, 359] range.
If control's type is set to HuePickerType.Value, then it allows selecting single hue value and looks like this:
If control's type is set to HuePickerType.Range, then it allows selecting range of hue values and looks like this:
Member Enumeration Documentation
HuePickerType
enum AForge.Controls.HuePicker.HuePickerType strong
Enumeration of hue picker types.
The HuePickerType.Value type provides single bullet to drag, which allows selecting single hue value. The value is accessible through Value property.
The HuePickerType.Range type provides two bullets to drag, which correspond to minimum and maximum values of the hue range. These values are accessible through Min and Max properties.
Enumerator
Value
Selecting single hue value.
Range
Selecting hue values range.
Constructor & Destructor Documentation
HuePicker()
AForge.Controls.HuePicker.HuePicker () inline
Initializes a new instance of the HuePicker class.
References AForge.Controls.HuePicker.blackBrush, AForge.Controls.HuePicker.blackPen, AForge.Controls.HuePicker.InitializeComponent(), AForge.Controls.HuePicker.whiteBrush, and AForge.Controls.HuePicker.whitePen.
Member Function Documentation
Dispose()
override void AForge.Controls.HuePicker.Dispose (bool disposing) inline protected
Dispose the object.
Parameters
disposing Specifies if disposing was invoked by user's code.
References AForge.Controls.HuePicker.blackBrush, AForge.Controls.HuePicker.blackPen, AForge.Controls.HuePicker.whiteBrush, and AForge.Controls.HuePicker.whitePen.
InitializeComponent()
void AForge.Controls.HuePicker.InitializeComponent () inline private
References AForge.Controls.HuePicker.HSLPicker_MouseDown(), AForge.Controls.HuePicker.HSLPicker_MouseMove(), and AForge.Controls.HuePicker.HSLPicker_MouseUp().
Referenced by AForge.Controls.HuePicker.HuePicker().
OnPaint()
override void AForge.Controls.HuePicker.OnPaint (PaintEventArgs pe) inline protected
Paint the controls.
Parameters
pe Paint event arguments.
References AForge.Controls.HuePicker.blackBrush, AForge.Controls.HuePicker.blackPen, AForge.Imaging.RGB.Color, AForge.Imaging.HSL.Hue, AForge.Imaging.HSL.Luminance, AForge.Controls.HuePicker.max, AForge.Controls.HuePicker.min, AForge.Controls.HuePicker.ptCenter, AForge.Controls.HuePicker.ptMax, AForge.Controls.HuePicker.ptMin, AForge.Math.Geometry.Rectangle, AForge.Imaging.HSL.Saturation, AForge.Imaging.HSL.ToRGB(), AForge.Controls.HuePicker.type, AForge.Controls.HuePicker.whiteBrush, AForge.Controls.HuePicker.whitePen, AForge.Point.X, and AForge.Point.Y.
HSLPicker_MouseDown()
void AForge.Controls.HuePicker.HSLPicker_MouseDown (object sender, System.Windows.Forms.MouseEventArgs e) inline private
References AForge.Controls.HuePicker.ptMax, AForge.Controls.HuePicker.ptMin, AForge.Controls.HuePicker.trackMode, AForge.Controls.HuePicker.type, AForge.Point.X, and AForge.Point.Y.
Referenced by AForge.Controls.HuePicker.InitializeComponent().
HSLPicker_MouseUp()
void AForge.Controls.HuePicker.HSLPicker_MouseUp (object sender, System.Windows.Forms.MouseEventArgs e) inline private
References AForge.Controls.HuePicker.trackMode, and AForge.Controls.HuePicker.ValuesChanged.
Referenced by AForge.Controls.HuePicker.InitializeComponent().
HSLPicker_MouseMove()
void AForge.Controls.HuePicker.HSLPicker_MouseMove (object sender, System.Windows.Forms.MouseEventArgs e) inline private
References AForge.Controls.HuePicker.max, AForge.Controls.HuePicker.min, AForge.Controls.HuePicker.ptCenter, AForge.Controls.HuePicker.ptMax, AForge.Controls.HuePicker.ptMin, AForge.Controls.HuePicker.trackMode, AForge.Controls.HuePicker.type, AForge.Point.X, and AForge.Point.Y.
Referenced by AForge.Controls.HuePicker.InitializeComponent().
Member Data Documentation
type
HuePickerType AForge.Controls.HuePicker.type = HuePickerType.Value private
Referenced by AForge.Controls.HuePicker.HSLPicker_MouseDown(), AForge.Controls.HuePicker.HSLPicker_MouseMove(), and AForge.Controls.HuePicker.OnPaint().
blackPen
Pen AForge.Controls.HuePicker.blackPen private
Referenced by AForge.Controls.HuePicker.Dispose(), AForge.Controls.HuePicker.HuePicker(), and AForge.Controls.HuePicker.OnPaint().
blackBrush
Brush AForge.Controls.HuePicker.blackBrush private
Referenced by AForge.Controls.HuePicker.Dispose(), AForge.Controls.HuePicker.HuePicker(), and AForge.Controls.HuePicker.OnPaint().
whitePen
Pen AForge.Controls.HuePicker.whitePen private
Referenced by AForge.Controls.HuePicker.Dispose(), AForge.Controls.HuePicker.HuePicker(), and AForge.Controls.HuePicker.OnPaint().
whiteBrush
Brush AForge.Controls.HuePicker.whiteBrush private
Referenced by AForge.Controls.HuePicker.Dispose(), AForge.Controls.HuePicker.HuePicker(), and AForge.Controls.HuePicker.OnPaint().
ptCenter
System.Drawing.Point AForge.Controls.HuePicker.ptCenter = new System.Drawing.Point(0, 0) private
Referenced by AForge.Controls.HuePicker.HSLPicker_MouseMove(), and AForge.Controls.HuePicker.OnPaint().
ptMin
System.Drawing.Point AForge.Controls.HuePicker.ptMin = new System.Drawing.Point(0, 0) private
Referenced by AForge.Controls.HuePicker.HSLPicker_MouseDown(), AForge.Controls.HuePicker.HSLPicker_MouseMove(), and AForge.Controls.HuePicker.OnPaint().
ptMax
System.Drawing.Point AForge.Controls.HuePicker.ptMax = new System.Drawing.Point(0, 0) private
Referenced by AForge.Controls.HuePicker.HSLPicker_MouseDown(), AForge.Controls.HuePicker.HSLPicker_MouseMove(), and AForge.Controls.HuePicker.OnPaint().
trackMode
int AForge.Controls.HuePicker.trackMode = 0 private
Referenced by AForge.Controls.HuePicker.HSLPicker_MouseDown(), AForge.Controls.HuePicker.HSLPicker_MouseMove(), and AForge.Controls.HuePicker.HSLPicker_MouseUp().
min
int AForge.Controls.HuePicker.min = 0 private
Referenced by AForge.Controls.HuePicker.HSLPicker_MouseMove(), and AForge.Controls.HuePicker.OnPaint().
max
int AForge.Controls.HuePicker.max = 359 private
Referenced by AForge.Controls.HuePicker.HSLPicker_MouseMove(), and AForge.Controls.HuePicker.OnPaint().
Property Documentation
Value
int AForge.Controls.HuePicker.Value get set
Selected value of the hue picker control in HuePickerType.Value mode.
Min
int AForge.Controls.HuePicker.Min get set
Minimum selected value of the hue picker control in HuePickerType.Range mode.
Max
int AForge.Controls.HuePicker.Max get set
Maximum selected value of the hue picker control in HuePickerType.Range mode.
Type
HuePickerType AForge.Controls.HuePicker.Type get set
Current type of the hue picker control.
See HuePickerType enumeration for description of the available types.
Event Documentation
ValuesChanged
EventHandler AForge.Controls.HuePicker.ValuesChanged
An event, to notify about changes of Min or Max properties.
The event is fired after changes of its Value, Min or Max properties, which is caused by user dragging the corresponding hue picker's bullets.
Referenced by AForge.Controls.HuePicker.HSLPicker_MouseUp().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Controls/HuePicker.cs