Doc: IGLib EXTENDED: NUnit.Framework.TestCaseAttribute Class Reference
NUnit.Framework.TestCaseAttribute Class Reference
TestCaseAttribute is used to mark parameterized test cases and provide them with their arguments.
Public Member Functions
TestCaseAttribute (params object[] arguments)
Construct a TestCaseAttribute with a list of arguments. This constructor is not CLS-Compliant
TestCaseAttribute (object arg)
Construct a TestCaseAttribute with a single argument
TestCaseAttribute (object arg1, object arg2)
Construct a TestCaseAttribute with a two arguments
TestCaseAttribute (object arg1, object arg2, object arg3)
Construct a TestCaseAttribute with a three arguments
IEnumerable< TestMethod > BuildFrom (IMethodInfo method, Test suite)
Construct one or more TestMethods from a given MethodInfo, using available parameter data.
Public Member Functions inherited from NUnit.Framework.NUnitAttribute
NUnitAttribute ()
Default constructor
Properties
string TestName [get, set]
Gets or sets the name of the test.
RunState RunState [get, private set]
Gets or sets the RunState of this test case.
object[] Arguments [get, private set]
Gets the list of arguments to a test case
IPropertyBag Properties [get, private set]
Gets the properties of the test case
object ExpectedResult [get, set]
Gets or sets the expected result.
bool HasExpectedResult [get, private set]
Returns true if the expected result has been set
string Description [get, set]
Gets or sets the description.
string Author [get, set]
The author of this test
Type TestOf [get, set]
The type that this test is testing
string Ignore [get, set]
Gets or sets the reason for ignoring the test
bool? Explicit [get, set]
Gets or sets a value indicating whether this NUnit.Framework.TestCaseAttribute is explicit.
string Reason [get, set]
Gets or sets the reason for not running the test.
string IgnoreReason [get, set]
Gets or sets the ignore reason. When set to a non-null non-empty value, the test is marked as ignored.
string IncludePlatform [get, set]
Comma-delimited list of platforms to run the test for
string ExcludePlatform [get, set]
Comma-delimited list of platforms to not run the test for
string Category [get, set]
Gets and sets the category for this test case. May be a comma-separated list of categories.
Properties inherited from NUnit.Framework.Interfaces.ITestCaseData
object ExpectedResult [get]
Gets the expected result of the test case
bool HasExpectedResult [get]
Returns true if an expected result has been set
Properties inherited from NUnit.Framework.Interfaces.ITestData
string TestName [get]
Gets the name to be used for the test
RunState RunState [get]
Gets the RunState for this test case.
object[] Arguments [get]
Gets the argument list to be provided to the test
IPropertyBag Properties [get]
Gets the property dictionary for the test case
Private Member Functions
TestCaseParameters GetParametersForTestCase (IMethodInfo method)
Static Private Member Functions
static void PerformSpecialConversions (object[] arglist, IParameterInfo[] parameters)
Performs several special conversions allowed by NUnit in order to permit arguments with types that cannot be used in the constructor of an Attribute such as TestCaseAttribute or to simplify their use.
Private Attributes
object _expectedResult
Type _testOf
Detailed Description
TestCaseAttribute is used to mark parameterized test cases and provide them with their arguments.
Constructor & Destructor Documentation
TestCaseAttribute() [1/4]
NUnit.Framework.TestCaseAttribute.TestCaseAttribute (params object[] arguments) inline
Construct a TestCaseAttribute with a list of arguments. This constructor is not CLS-Compliant
Parameters
arguments
References NUnit.Framework.TestCaseAttribute.Arguments, and NUnit.Framework.TestCaseAttribute.Properties.
TestCaseAttribute() [2/4]
NUnit.Framework.TestCaseAttribute.TestCaseAttribute (object arg) inline
Construct a TestCaseAttribute with a single argument
Parameters
arg
References NUnit.Framework.TestCaseAttribute.Arguments, and NUnit.Framework.TestCaseAttribute.Properties.
TestCaseAttribute() [3/4]
NUnit.Framework.TestCaseAttribute.TestCaseAttribute (object arg1, object arg2) inline
Construct a TestCaseAttribute with a two arguments
Parameters
arg1
arg2
References NUnit.Framework.TestCaseAttribute.Arguments, and NUnit.Framework.TestCaseAttribute.Properties.
TestCaseAttribute() [4/4]
NUnit.Framework.TestCaseAttribute.TestCaseAttribute (object arg1, object arg2, object arg3) inline
Construct a TestCaseAttribute with a three arguments
Parameters
arg1
arg2
arg3
References NUnit.Framework.TestCaseAttribute.Arguments, and NUnit.Framework.TestCaseAttribute.Properties.
Member Function Documentation
GetParametersForTestCase()
TestCaseParameters NUnit.Framework.TestCaseAttribute.GetParametersForTestCase (IMethodInfo method) inline private
References NUnit.Framework.Internal.TestParameters.Arguments, NUnit.Framework.TestCaseAttribute.Arguments, NUnit.Framework.Interfaces.IMethodInfo.GetParameters(), NUnit.Framework.Interfaces.IParameterInfo.ParameterType, and NUnit.Framework.TestCaseAttribute.PerformSpecialConversions().
Referenced by NUnit.Framework.TestCaseAttribute.BuildFrom().
PerformSpecialConversions()
static void NUnit.Framework.TestCaseAttribute.PerformSpecialConversions (object[] arglist, IParameterInfo[] parameters) inline static private
Performs several special conversions allowed by NUnit in order to permit arguments with types that cannot be used in the constructor of an Attribute such as TestCaseAttribute or to simplify their use.
Parameters
arglist The arguments to be converted
parameters The ParameterInfo array for the method
References NUnit.Framework.Interfaces.IParameterInfo.ParameterType.
Referenced by NUnit.Framework.TestCaseAttribute.GetParametersForTestCase().
BuildFrom()
IEnumerable<TestMethod> NUnit.Framework.TestCaseAttribute.BuildFrom (IMethodInfo method, Test suite) inline
Construct one or more TestMethods from a given MethodInfo, using available parameter data.
Parameters
method The MethodInfo for which tests are to be constructed.
suite The suite to which the tests will be added.
Returns
One or more TestMethods
Implements NUnit.Framework.Interfaces.ITestBuilder.
References NUnit.Framework.Interfaces.IPropertyBag.Add(), NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.BuildTestMethod(), NUnit.Framework.TestCaseAttribute.GetParametersForTestCase(), NUnit.Framework.Internal.PlatformHelper.IsPlatformSupported(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.PlatformHelper.Reason, NUnit.Framework.Internal.Test.RunState, and NUnit.Framework.Internal.PropertyNames.SkipReason.
Member Data Documentation
_expectedResult
object NUnit.Framework.TestCaseAttribute._expectedResult private
_testOf
Type NUnit.Framework.TestCaseAttribute._testOf private
Property Documentation
TestName
string NUnit.Framework.TestCaseAttribute.TestName get set
Gets or sets the name of the test.
The name of the test.
RunState
RunState NUnit.Framework.TestCaseAttribute.RunState get private set
Gets or sets the RunState of this test case.
Arguments
object [] NUnit.Framework.TestCaseAttribute.Arguments get private set
Gets the list of arguments to a test case
Referenced by NUnit.Framework.TestCaseAttribute.GetParametersForTestCase(), and NUnit.Framework.TestCaseAttribute.TestCaseAttribute().
Properties
IPropertyBag NUnit.Framework.TestCaseAttribute.Properties get private set
Gets the properties of the test case
Referenced by NUnit.Framework.TestCaseAttribute.TestCaseAttribute().
ExpectedResult
object NUnit.Framework.TestCaseAttribute.ExpectedResult get set
Gets or sets the expected result.
The result.
HasExpectedResult
bool NUnit.Framework.TestCaseAttribute.HasExpectedResult get private set
Returns true if the expected result has been set
Description
string NUnit.Framework.TestCaseAttribute.Description get set
Gets or sets the description.
The description.
Author
string NUnit.Framework.TestCaseAttribute.Author get set
The author of this test
TestOf
Type NUnit.Framework.TestCaseAttribute.TestOf get set
The type that this test is testing
Ignore
string NUnit.Framework.TestCaseAttribute.Ignore get set
Gets or sets the reason for ignoring the test
Explicit
bool? NUnit.Framework.TestCaseAttribute.Explicit get set
Gets or sets a value indicating whether this NUnit.Framework.TestCaseAttribute is explicit.
true if explicit; otherwise, false.
Reason
string NUnit.Framework.TestCaseAttribute.Reason get set
Gets or sets the reason for not running the test.
The reason.
IgnoreReason
string NUnit.Framework.TestCaseAttribute.IgnoreReason get set
Gets or sets the ignore reason. When set to a non-null non-empty value, the test is marked as ignored.
The ignore reason.
IncludePlatform
string NUnit.Framework.TestCaseAttribute.IncludePlatform get set
Comma-delimited list of platforms to run the test for
Referenced by NUnit.Framework.Internal.PlatformHelper.IsPlatformSupported().
ExcludePlatform
string NUnit.Framework.TestCaseAttribute.ExcludePlatform get set
Comma-delimited list of platforms to not run the test for
Referenced by NUnit.Framework.Internal.PlatformHelper.IsPlatformSupported().
Category
string NUnit.Framework.TestCaseAttribute.Category get set
Gets and sets the category for this test case. May be a comma-separated list of categories.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Attributes/TestCaseAttribute.cs