Doc: IGLib EXTENDED: NUnit.Engine.Services.Tests.ExtensionServiceTests Class Reference
NUnit.Engine.Services.Tests.ExtensionServiceTests Class Reference
Public Member Functions
void CreateService ()
void CanListExtensionPoints (string path)
void CanGetExtensionPointByPath ([ValueSource("KNOWN_EXTENSION_POINT_PATHS")] string path, [ValueSource("KNOWN_EXTENSION_POINT_TYPES")] Type type)
void CanGetExtensionPointByType ([ValueSource("KNOWN_EXTENSION_POINT_PATHS")] string path, [ValueSource("KNOWN_EXTENSION_POINT_TYPES")] Type type)
void CanListExtensions (string typeName)
void ExtensionsAreAddedToExtensionPoint ([ValueSource("KNOWN_EXTENSION_POINT_PATHS")] string path, [Values(0, 2, 1, 1)] int expectedExtensionCount)
Private Attributes
ExtensionService _extensionService
Static Private Attributes
static readonly string[] KNOWN_EXTENSION_POINT_PATHS
static readonly Type[] KNOWN_EXTENSION_POINT_TYPES
static readonly string[] KNOWN_EXTENSIONS
Member Function Documentation
CreateService()
void NUnit.Engine.Services.Tests.ExtensionServiceTests.CreateService () inline
References NUnit.Engine.Services.Tests.ExtensionServiceTests._extensionService, and NUnit.Engine.Services.ExtensionService.StartService().
CanListExtensionPoints()
void NUnit.Engine.Services.Tests.ExtensionServiceTests.CanListExtensionPoints (string path) inline
References NUnit.Engine.Services.Tests.ExtensionServiceTests._extensionService, NUnit.Engine.Services.ExtensionService.ExtensionPoints, and NUnit.Framework.Assert.Fail().
CanGetExtensionPointByPath()
void NUnit.Engine.Services.Tests.ExtensionServiceTests.CanGetExtensionPointByPath ([ValueSource("KNOWN_EXTENSION_POINT_PATHS")] string path, [ValueSource("KNOWN_EXTENSION_POINT_TYPES")] Type type) inline
References NUnit.Engine.Services.Tests.ExtensionServiceTests._extensionService, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Services.ExtensionService.GetExtensionPoint(), NUnit.Framework.Assert.NotNull(), and NUnit.Framework.Assert.That().
CanGetExtensionPointByType()
void NUnit.Engine.Services.Tests.ExtensionServiceTests.CanGetExtensionPointByType ([ValueSource("KNOWN_EXTENSION_POINT_PATHS")] string path, [ValueSource("KNOWN_EXTENSION_POINT_TYPES")] Type type) inline
References NUnit.Engine.Services.Tests.ExtensionServiceTests._extensionService, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Services.ExtensionService.GetExtensionPoint(), NUnit.Framework.Assert.NotNull(), and NUnit.Framework.Assert.That().
CanListExtensions()
void NUnit.Engine.Services.Tests.ExtensionServiceTests.CanListExtensions (string typeName) inline
References NUnit.Engine.Services.Tests.ExtensionServiceTests._extensionService, NUnit.Engine.Services.ExtensionService.Extensions, NUnit.Framework.Assert.Fail(), and NUnit.Engine.Extensibility.ExtensionNode.TypeName.
ExtensionsAreAddedToExtensionPoint()
void NUnit.Engine.Services.Tests.ExtensionServiceTests.ExtensionsAreAddedToExtensionPoint ([ValueSource("KNOWN_EXTENSION_POINT_PATHS")] string path, [Values(0, 2, 1, 1)] int expectedExtensionCount) inline
References NUnit.Engine.Services.Tests.ExtensionServiceTests._extensionService, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Services.ExtensionService.GetExtensionPoint(), NUnit.Framework.Is.Not, NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
Member Data Documentation
_extensionService
ExtensionService NUnit.Engine.Services.Tests.ExtensionServiceTests._extensionService private
Referenced by NUnit.Engine.Services.Tests.ExtensionServiceTests.CanGetExtensionPointByPath(), NUnit.Engine.Services.Tests.ExtensionServiceTests.CanGetExtensionPointByType(), NUnit.Engine.Services.Tests.ExtensionServiceTests.CanListExtensionPoints(), NUnit.Engine.Services.Tests.ExtensionServiceTests.CanListExtensions(), NUnit.Engine.Services.Tests.ExtensionServiceTests.CreateService(), and NUnit.Engine.Services.Tests.ExtensionServiceTests.ExtensionsAreAddedToExtensionPoint().
KNOWN_EXTENSION_POINT_PATHS
readonly string [] NUnit.Engine.Services.Tests.ExtensionServiceTests.KNOWN_EXTENSION_POINT_PATHS static private
Initial value:
= new string[] {
            "/NUnit/Engine/TypeExtensions/IDriverFactory",
            "/NUnit/Engine/TypeExtensions/IProjectLoader",
            "/NUnit/Engine/TypeExtensions/IResultWriter",
            "/NUnit/Engine/NUnitV2Driver"
        }
KNOWN_EXTENSION_POINT_TYPES
readonly Type [] NUnit.Engine.Services.Tests.ExtensionServiceTests.KNOWN_EXTENSION_POINT_TYPES static private
Initial value:
= new Type[] {
            typeof(IDriverFactory),
            typeof(IProjectLoader),
            typeof(IResultWriter),
            typeof(IFrameworkDriver)
        }
KNOWN_EXTENSIONS
readonly string [] NUnit.Engine.Services.Tests.ExtensionServiceTests.KNOWN_EXTENSIONS static private
Initial value:
= new string[] {
            "NUnit.Engine.Services.ProjectLoaders.NUnitProjectLoader",
            "NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader",
            "NUnit.Engine.Addins.NUnit2XmlResultWriter",
            "NUnit.Engine.Drivers.NUnit2FrameworkDriver"
        }
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Services/ExtensionServiceTests.cs