Doc: IGLib EXTENDED: IG.Lib.ParsableXmlObject Class Reference
IG.Lib.ParsableXmlObject Class Reference abstract
Base class for data classes that support writing data to / reading from custom XML files, writing from / to database objects, etc.
Classes
class AccummulatedReport
Class used for accummulated error and warning reports for task composed of several steps. This is used when we want to perform the whole task even if some errors occur, and treat all errors and messages after the task is completed.
Public Member Functions
virtual void Save (string filename)
Saves contents of the msg to an xml file.
virtual void CreateXml ()
Creates msg Xml from the current msg data and stores it in this object.
virtual void Load (string filename)
Loads msg data from a file containing the XML msg.
virtual void LoadXml (string doc)
Loads msg data from a string containing the XML msg.
virtual void LoadXml (XmlDocument doc)
Loads msg data from an XmlDocument containing XML msg.
abstract void Read ()
Reads msg data from the internal XML document containing the msg.
abstract void Read (XmlParser data)
Read msg data from an XML document containing the msg.
virtual void CheckConsistency (AccummulatedReport rep)
Empty data consistency check, intended to be overridden in derived classes.
virtual void WriteToConsole ()
Writes cntents of the msg in a human readable form to the system console.
virtual void Write (string filename, bool append)
Writes cntents of the msg in a human readable form to a file.
abstract XmlDocument ToXml ()
Converts a msg to Xml and returns it.
Public Attributes
string XmlString = null
Protected Attributes
XmlBuilder Data = new XmlBuilder()
Properties
virtual IReporter R [get]
Reporter for this class.
XmlDocument Doc [get]
Returns the XML document representing the msg.
Private Member Functions
void Write (TextWriter tw)
Writes contents of the msg in a human readable form to a textwriter.
Private Attributes
IReporter _R = null
Detailed Description
Base class for data classes that support writing data to / reading from custom XML files, writing from / to database objects, etc.
Member Function Documentation
Save()
virtual void IG.Lib.ParsableXmlObject.Save (string filename) inline virtual
Saves contents of the msg to an xml file.
Parameters
filename Name of the file that the msg is saved to.
References IG.Lib.ParsableXmlObject.Doc.
Referenced by IGTest.FindingsRtfTest.btnSaveOutput_Click(), IGTest.FindingsRtfTest.btnSaveOutputRtf_Click(), IGTest.ProgramIGTest.TestFindings(), IGTest.ProgramIGTest.TestMsgFinancialTransaction(), and IGTest.ProgramIGTest.TestMsgObservationEvent().
CreateXml()
virtual void IG.Lib.ParsableXmlObject.CreateXml () inline virtual
Creates msg Xml from the current msg data and stores it in this object.
References IG.Lib.ParsableXmlObject.Data, IG.Lib.IReporterBase.Depth, IG.Lib.XmlUtilityBase.LoadXml(), IG.Lib.ParsableXmlObject.R, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.ParsableXmlObject.ToXml(), and IG.Lib.IReporterBase.TreatInfo.
Load()
virtual void IG.Lib.ParsableXmlObject.Load (string filename) inline virtual
Loads msg data from a file containing the XML msg.
Parameters
filename Name of the file from which tata is read.
References IG.Lib.ParsableXmlObject.Data, IG.Lib.IReporterBase.Depth, IG.Lib.XmlUtilityBase.Load(), IG.Lib.ParsableXmlObject.R, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), and IG.Lib.IReporterBase.TreatInfo.
Referenced by IGTest.FindingsRtfTest.btnImportInput_Click(), IGTest.FindingsRtfTest.btnImportInputRtf_Click(), IGTest.FindingsRtfTest.btnImportOutput_Click(), IGTest.FindingsRtfTest.btnImportOutputRtf_Click(), IGTest.ProgramIGTest.TestFindings(), IGTest.ProgramIGTest.TestMsgFinancialTransaction(), IGTest.ProgramIGTest.TestMsgObservationEvent(), IGTest.ProgramIGTest.TestMsgObservationOrder(), IGTest.ProgramIGTest.TestMsgObservationOrderNullify(), and IGTest.ProgramIGTest.TestMsgObservationOrderNullifySend().
LoadXml() [1/2]
virtual void IG.Lib.ParsableXmlObject.LoadXml (string doc) inline virtual
Loads msg data from a string containing the XML msg.
Parameters
doc String containing the msg in XML format.
References IG.Lib.ParsableXmlObject.Data, IG.Lib.IReporterBase.Depth, IG.Lib.XmlUtilityBase.LoadXml(), IG.Lib.ParsableXmlObject.R, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), and IG.Lib.IReporterBase.TreatInfo.
Referenced by IGTest.ProgramIGTest.ReceiveSpecimenObservationOrder(), and IGTest.ProgramIGTest.TestCalypsoWs().
LoadXml() [2/2]
virtual void IG.Lib.ParsableXmlObject.LoadXml (XmlDocument doc) inline virtual
Loads msg data from an XmlDocument containing XML msg.
Parameters
filename XMLDocument containing the msg.
References IG.Lib.ParsableXmlObject.Data, IG.Lib.IReporterBase.Depth, IG.Lib.XmlUtilityBase.LoadXml(), IG.Lib.ParsableXmlObject.R, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), and IG.Lib.IReporterBase.TreatInfo.
Read() [1/2]
abstract void IG.Lib.ParsableXmlObject.Read () pure virtual
Reads msg data from the internal XML document containing the msg.
Implemented in IG.Lib.MsgObervationOrder, IG.Lib.DocFindings, IG.Lib.MsgFinancialTransaction, and IG.Lib.MsgObservationEvent.
Referenced by IGTest.ProgramIGTest.ReceiveSpecimenObservationOrder().
Read() [2/2]
abstract void IG.Lib.ParsableXmlObject.Read (XmlParser data) pure virtual
Read msg data from an XML document containing the msg.
Parameters
doc Document containing the msg.
Implemented in IG.Lib.MsgObervationOrder, IG.Lib.DocFindings, IG.Lib.MsgFinancialTransaction, and IG.Lib.MsgObservationEvent.
CheckConsistency()
virtual void IG.Lib.ParsableXmlObject.CheckConsistency (AccummulatedReport rep) inline virtual
Empty data consistency check, intended to be overridden in derived classes.
Parameters
rep Object where error, warning and info reports are accumulated.
Reimplemented in IG.Lib.MsgObervationOrder, IG.Lib.DocFindings, IG.Lib.MsgFinancialTransaction, and IG.Lib.MsgObservationEvent.
References IG.Lib.ParsableXmlObject.AccummulatedReport.AddInfo().
Write() [1/2]
void IG.Lib.ParsableXmlObject.Write (TextWriter tw) inline private
Writes contents of the msg in a human readable form to a textwriter.
References IG.Lib.IReporterBase.Depth, IG.Lib.ParsableXmlObject.R, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), and IG.Lib.IReporterBase.TreatInfo.
Referenced by IG.Lib.ParsableXmlObject.Write(), and IG.Lib.ParsableXmlObject.WriteToConsole().
WriteToConsole()
virtual void IG.Lib.ParsableXmlObject.WriteToConsole () inline virtual
Writes cntents of the msg in a human readable form to the system console.
References IG.Lib.IReporterBase.Depth, IG.Lib.ParsableXmlObject.R, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.IReporterBase.TreatInfo, and IG.Lib.ParsableXmlObject.Write().
Referenced by IGTest.ProgramIGTest.ReceiveSpecimenObservationOrder(), IGTest.ProgramIGTest.TestCalypsoWs(), IGTest.ProgramIGTest.TestFindings(), IGTest.ProgramIGTest.TestMsgFinancialTransaction(), IGTest.ProgramIGTest.TestMsgObservationEvent(), IGTest.ProgramIGTest.TestMsgObservationOrder(), and IGTest.ProgramIGTest.TestMsgObservationOrderNullify().
Write() [2/2]
virtual void IG.Lib.ParsableXmlObject.Write (string filename, bool append) inline virtual
Writes cntents of the msg in a human readable form to a file.
Parameters
filename File to which msg contents is written.
append If true then fle is appended, otherwise it is overwritten.
References IG.Lib.IReporterBase.Depth, IG.Lib.ParsableXmlObject.R, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.IReporterBase.TreatInfo, and IG.Lib.ParsableXmlObject.Write().
ToXml()
abstract XmlDocument IG.Lib.ParsableXmlObject.ToXml () pure virtual
Converts a msg to Xml and returns it.
Implemented in IG.Lib.MsgObervationOrder, IG.Lib.DocFindings, IG.Lib.MsgObservationEvent, and IG.Lib.MsgFinancialTransaction.
Referenced by IG.Lib.ParsableXmlObject.CreateXml().
Member Data Documentation
XmlString
string IG.Lib.ParsableXmlObject.XmlString = null
Referenced by IG.Lib.MsgBaseWithModel.SetModelString().
_R
IReporter IG.Lib.ParsableXmlObject._R = null private
Data
XmlBuilder IG.Lib.ParsableXmlObject.Data = new XmlBuilder() protected
Referenced by IG.Lib.ParsableXmlObject.CreateXml(), IG.Lib.ParsableXmlObject.Load(), IG.Lib.ParsableXmlObject.LoadXml(), IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgFinancialTransaction.Read(), IG.Lib.DocFindings.Read(), IG.Lib.MsgObervationOrder.Read(), IG.Lib.MsgFinancialTransaction.ToXml(), IG.Lib.MsgObservationEvent.ToXml(), IG.Lib.DocFindings.ToXml(), and IG.Lib.MsgObervationOrder.ToXml().
Property Documentation
R
virtual IReporter IG.Lib.ParsableXmlObject.R get
Reporter for this class.
Referenced by IG.Lib.ParsableXmlObject.CreateXml(), IG.Lib.ParsableXmlObject.Load(), IG.Lib.ParsableXmlObject.LoadXml(), IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgFinancialTransaction.Read(), IG.Lib.DocFindings.Read(), IG.Lib.MsgObervationOrder.Read(), IG.Lib.MsgObservationEvent.SetVerifierId(), IG.Lib.MsgFinancialTransaction.ToString(), IG.Lib.MsgObservationEvent.ToString(), IG.Lib.DocFindings.ToString(), IG.Lib.MsgObervationOrder.ToString(), IG.Lib.MsgFinancialTransaction.ToXml(), IG.Lib.MsgObservationEvent.ToXml(), IG.Lib.DocFindings.ToXml(), IG.Lib.MsgObervationOrder.ToXml(), IG.Lib.ParsableXmlObject.Write(), and IG.Lib.ParsableXmlObject.WriteToConsole().
Doc
XmlDocument IG.Lib.ParsableXmlObject.Doc get
Returns the XML document representing the msg.
Referenced by IG.Lib.ParsableXmlObject.Save(), LabexBis.Calypso.SendOoNullifyToBis(), IGTest.ProgramIGTest.TestFindings(), IGTest.ProgramIGTest.TestMsgFinancialTransaction(), IGTest.ProgramIGTest.TestMsgObservationEvent(), IGTest.ProgramIGTest.TestMsgObservationOrderNullify(), IG.Lib.MsgFinancialTransaction.ToXml(), IG.Lib.MsgObservationEvent.ToXml(), and IG.Lib.DocFindings.ToXml().
The documentation for this class was generated from the following file:
igtest/tmp_prem/prlab/LabexBis/MessagesBis.cs