Doc: IGLib EXTENDED: IG.App.ProgramExampleIJS Class Reference
IG.App.ProgramExampleIJS Class Reference
Neural networks application.
Static Public Member Functions
static void Main (string[] args)
Entry point.
static void ExampleUsingScriptIJS (string optimizationDirectory)
Runs example of how to use the script.
Detailed Description
Neural networks application.
Member Function Documentation
Main()
static void IG.App.ProgramExampleIJS.Main (string[] args) inline static
Entry point.
Parameters
args The only argument shoult be working directory that contains all the data necessary to perform the intended tasks (such as trained neural networks).
References IG.App.ProgramExampleIJS.ExampleUsingScriptIJS().
ExampleUsingScriptIJS()
static void IG.App.ProgramExampleIJS.ExampleUsingScriptIJS (string optimizationDirectory) inline static
Runs example of how to use the script.
This code is copied form the script!
Parameters
optimizationDirectory Working directoy that contains all the data needed by the script!
References IG.Script.LoadableScriptShellNeuralITOriginalBase.ConstCustom, IG.Lib.LoadableScriptBase.Initialize(), IG.Lib.LoadableScriptBase.Run(), and IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00.TestMethod().
Referenced by IG.App.ProgramExampleIJS.Main().
The documentation for this class was generated from the following file:
shelldev/extensions_shell/ExtAppIJS/ProgramExampleIJS.cs