Doc: IGLib EXTENDED: NUnit.Engine.Internal.ServerBase Class Reference
NUnit.Engine.Internal.ServerBase Class Reference
Summary description for ServerBase.
Public Member Functions
virtual void Start ()
virtual void Stop ()
void WaitForStop ()
void Dispose ()
override object InitializeLifetimeService ()
Protected Member Functions
ServerBase ()
ServerBase (string uri, int port)
Constructor used to provide
virtual void Dispose (bool disposing)
Protected Attributes
string uri
int port
Properties
string ServerUrl [get]
Private Attributes
TcpChannel channel
bool isMarshalled
object theLock = new object()
bool _disposed = false
Detailed Description
Summary description for ServerBase.
Constructor & Destructor Documentation
ServerBase() [1/2]
NUnit.Engine.Internal.ServerBase.ServerBase () inline protected
ServerBase() [2/2]
NUnit.Engine.Internal.ServerBase.ServerBase (string uri, int port) inline protected
Constructor used to provide
Parameters
uri
port
References NUnit.Engine.Internal.ServerBase.port, and NUnit.Engine.Internal.ServerBase.uri.
Member Function Documentation
Start()
virtual void NUnit.Engine.Internal.ServerBase.Start () inline virtual
References NUnit.Engine.Internal.ServerUtilities.GetTcpChannel(), NUnit.Engine.Internal.ServerBase.port, NUnit.Engine.Internal.ServerBase.theLock, and NUnit.Engine.Internal.ServerBase.uri.
Referenced by NUnit.Engine.Services.TestAgency.StartService().
Stop()
virtual void NUnit.Engine.Internal.ServerBase.Stop () inline virtual
References NUnit.Engine.Internal.ServerBase.theLock.
Referenced by NUnit.Engine.Internal.ServerBase.Dispose(), and NUnit.Engine.Services.TestAgency.StopService().
WaitForStop()
void NUnit.Engine.Internal.ServerBase.WaitForStop () inline
References NUnit.Engine.Internal.ServerBase.theLock.
Dispose() [1/2]
void NUnit.Engine.Internal.ServerBase.Dispose () inline
Dispose() [2/2]
virtual void NUnit.Engine.Internal.ServerBase.Dispose (bool disposing) inline protected virtual
References NUnit.Engine.Internal.ServerBase._disposed, and NUnit.Engine.Internal.ServerBase.Stop().
InitializeLifetimeService()
override object NUnit.Engine.Internal.ServerBase.InitializeLifetimeService () inline
Member Data Documentation
uri
string NUnit.Engine.Internal.ServerBase.uri protected
Referenced by NUnit.Engine.Internal.ServerBase.ServerBase(), and NUnit.Engine.Internal.ServerBase.Start().
port
int NUnit.Engine.Internal.ServerBase.port protected
Referenced by NUnit.Engine.Internal.ServerBase.ServerBase(), and NUnit.Engine.Internal.ServerBase.Start().
channel
TcpChannel NUnit.Engine.Internal.ServerBase.channel private
isMarshalled
bool NUnit.Engine.Internal.ServerBase.isMarshalled private
theLock
object NUnit.Engine.Internal.ServerBase.theLock = new object() private
Referenced by NUnit.Engine.Internal.ServerBase.Start(), NUnit.Engine.Internal.ServerBase.Stop(), and NUnit.Engine.Internal.ServerBase.WaitForStop().
_disposed
bool NUnit.Engine.Internal.ServerBase._disposed = false private
Referenced by NUnit.Engine.Internal.ServerBase.Dispose().
Property Documentation
ServerUrl
string NUnit.Engine.Internal.ServerBase.ServerUrl get
Referenced by NUnit.Engine.Services.TestAgency.LaunchAgentProcess().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Internal/ServerBase.cs