Doc: IGLib EXTENDED: AForge.Math.Geometry.PointsCloud Class Reference
AForge.Math.Geometry.PointsCloud Class Reference
Set of tools for processing collection of points in 2D space.
Static Public Member Functions
static void Shift (IList< IntPoint > cloud, IntPoint shift)
Shift cloud by adding specified value to all points in the collection.
static void GetBoundingRectangle (IEnumerable< IntPoint > cloud, out IntPoint minXY, out IntPoint maxXY)
Get bounding rectangle of the specified list of points.
static Point GetCenterOfGravity (IEnumerable< IntPoint > cloud)
Get center of gravity for the specified list of points.
static IntPoint GetFurthestPoint (IEnumerable< IntPoint > cloud, IntPoint referencePoint)
Find furthest point from the specified point.
static void GetFurthestPointsFromLine (IEnumerable< IntPoint > cloud, IntPoint linePoint1, IntPoint linePoint2, out IntPoint furthestPoint1, out IntPoint furthestPoint2)
Find two furthest points from the specified line.
static void GetFurthestPointsFromLine (IEnumerable< IntPoint > cloud, IntPoint linePoint1, IntPoint linePoint2, out IntPoint furthestPoint1, out float distance1, out IntPoint furthestPoint2, out float distance2)
Find two furthest points from the specified line.
static IntPoint GetFurthestPointFromLine (IEnumerable< IntPoint > cloud, IntPoint linePoint1, IntPoint linePoint2)
Find the furthest point from the specified line.
static IntPoint GetFurthestPointFromLine (IEnumerable< IntPoint > cloud, IntPoint linePoint1, IntPoint linePoint2, out float distance)
Find the furthest point from the specified line.
static List< IntPoint > FindQuadrilateralCorners (IEnumerable< IntPoint > cloud)
Find corners of quadrilateral or triangular area, which contains the specified collection of points.
Properties
static float QuadrilateralRelativeDistortionLimit [get, set]
Relative distortion limit allowed for quadrilaterals, [0.0, 0.25].
Static Private Attributes
static float quadrilateralRelativeDistortionLimit = 0.1f
Detailed Description
Set of tools for processing collection of points in 2D space.
The static class contains set of routines, which provide different operations with collection of points in 2D space. For example, finding the furthest point from a specified point or line.
Sample usage:
// create points' list
List<IntPoint> points = new List<IntPoint>();
points.Add(new IntPoint(10, 10));
points.Add(new IntPoint(20, 15));
points.Add(new IntPoint(15, 30));
points.Add(new IntPoint(40, 12));
points.Add(new IntPoint(30, 20));
// get furthest point from the specified point
IntPoint p1 = PointsCloud.GetFurthestPoint(points, new IntPoint(15, 15));
Console.WriteLine(p1.X + ", " + p1.Y);
// get furthest point from line
IntPoint p2 = PointsCloud.GetFurthestPointFromLine(points,
    new IntPoint( 50, 0 ), new IntPoint( 0, 50 ) );
Console.WriteLine(p2.X + ", " + p2.Y);
Member Function Documentation
Shift()
static void AForge.Math.Geometry.PointsCloud.Shift (IList< IntPoint > cloud, IntPoint shift) inline static
Shift cloud by adding specified value to all points in the collection.
Parameters
cloud Collection of points to shift their coordinates.
shift Point to shift by.
Referenced by BlobsExplorer.BlobsBrowser.SetImage().
GetBoundingRectangle()
static void AForge.Math.Geometry.PointsCloud.GetBoundingRectangle (IEnumerable< IntPoint > cloud, out IntPoint minXY, out IntPoint maxXY) inline static
Get bounding rectangle of the specified list of points.
Parameters
cloud Collection of points to get bounding rectangle for.
minXY Point comprised of smallest X and Y coordinates.
maxXY Point comprised of biggest X and Y coordinates.
References AForge.IntPoint.X, and AForge.IntPoint.Y.
Referenced by AForge.Math.Geometry.SimpleShapeChecker.CheckIfPointsFitShape(), AForge.Math.Geometry.SimpleShapeChecker.CheckPolygonSubType(), AForge.Math.Geometry.PointsCloud.FindQuadrilateralCorners(), AForge.Math.Geometry.SimpleShapeChecker.IsCircle(), and AForge.Imaging.Filters.BackwardQuadrilateralTransformation.ProcessFilter().
GetCenterOfGravity()
static Point AForge.Math.Geometry.PointsCloud.GetCenterOfGravity (IEnumerable< IntPoint > cloud) inline static
Get center of gravity for the specified list of points.
Parameters
cloud List of points to calculate center of gravity for.
Returns
Returns center of gravity (mean X-Y values) for the specified list of points.
References AForge.IntPoint.X, and AForge.IntPoint.Y.
GetFurthestPoint()
static IntPoint AForge.Math.Geometry.PointsCloud.GetFurthestPoint (IEnumerable< IntPoint > cloud, IntPoint referencePoint) inline static
Find furthest point from the specified point.
Parameters
cloud Collection of points to search furthest point in.
referencePoint The point to search furthest point from.
Returns
Returns a point, which is the furthest away from the referencePoint .
References AForge.IntPoint.X, and AForge.IntPoint.Y.
Referenced by AForge.Math.Geometry.PointsCloud.FindQuadrilateralCorners().
GetFurthestPointsFromLine() [1/2]
static void AForge.Math.Geometry.PointsCloud.GetFurthestPointsFromLine (IEnumerable< IntPoint > cloud, IntPoint linePoint1, IntPoint linePoint2, out IntPoint furthestPoint1, out IntPoint furthestPoint2) inline static
Find two furthest points from the specified line.
Parameters
cloud Collection of points to search furthest points in.
linePoint1 First point forming the line.
linePoint2 Second point forming the line.
furthestPoint1 First found furthest point.
furthestPoint2 Second found furthest point (which is on the opposite side from the line compared to the furthestPoint1);
The method finds two furthest points from the specified line, where one point is on one side from the line and the second point is on another side from the line.
Referenced by AForge.Math.Geometry.PointsCloud.FindQuadrilateralCorners().
GetFurthestPointsFromLine() [2/2]
static void AForge.Math.Geometry.PointsCloud.GetFurthestPointsFromLine (IEnumerable< IntPoint > cloud, IntPoint linePoint1, IntPoint linePoint2, out IntPoint furthestPoint1, out float distance1, out IntPoint furthestPoint2, out float distance2) inline static
Find two furthest points from the specified line.
Parameters
cloud Collection of points to search furthest points in.
linePoint1 First point forming the line.
linePoint2 Second point forming the line.
furthestPoint1 First found furthest point.
distance1 Distance between the first found point and the given line.
furthestPoint2 Second found furthest point (which is on the opposite side from the line compared to the furthestPoint1);
distance2 Distance between the second found point and the given line.
The method finds two furthest points from the specified line, where one point is on one side from the line and the second point is on another side from the line.
References AForge.IntPoint.X, and AForge.IntPoint.Y.
GetFurthestPointFromLine() [1/2]
static IntPoint AForge.Math.Geometry.PointsCloud.GetFurthestPointFromLine (IEnumerable< IntPoint > cloud, IntPoint linePoint1, IntPoint linePoint2) inline static
Find the furthest point from the specified line.
Parameters
cloud Collection of points to search furthest point in.
linePoint1 First point forming the line.
linePoint2 Second point forming the line.
Returns
Returns a point, which is the furthest away from the specified line.
The method finds the furthest point from the specified line. Unlike the GetFurthestPointsFromLine(IEnumerable<IntPoint>, IntPoint, IntPoint, out IntPoint, out IntPoint) method, this method find only one point, which is the furthest away from the line regardless of side from the line.
Referenced by AForge.Math.Geometry.LineStraighteningOptimizer.OptimizeShape().
GetFurthestPointFromLine() [2/2]
static IntPoint AForge.Math.Geometry.PointsCloud.GetFurthestPointFromLine (IEnumerable< IntPoint > cloud, IntPoint linePoint1, IntPoint linePoint2, out float distance) inline static
Find the furthest point from the specified line.
Parameters
cloud Collection of points to search furthest points in.
linePoint1 First point forming the line.
linePoint2 Second point forming the line.
distance Distance between the furthest found point and the given line.
Returns
Returns a point, which is the furthest away from the specified line.
The method finds the furthest point from the specified line. Unlike the GetFurthestPointsFromLine(IEnumerable<IntPoint>, IntPoint, IntPoint, out IntPoint, out float, out IntPoint, out float) method, this method find only one point, which is the furthest away from the line regardless of side from the line.
References AForge.IntPoint.X, and AForge.IntPoint.Y.
FindQuadrilateralCorners()
static List<IntPoint> AForge.Math.Geometry.PointsCloud.FindQuadrilateralCorners (IEnumerable< IntPoint > cloud) inline static
Find corners of quadrilateral or triangular area, which contains the specified collection of points.
Parameters
cloud Collection of points to search quadrilateral for.
Returns
Returns a list of 3 or 4 points, which are corners of the quadrilateral or triangular area filled by specified collection of point. The first point in the list is the point with lowest X coordinate (and with lowest Y if there are several points with the same X value). The corners are provided in counter clockwise order (Cartesian coordinate system).
The method makes an assumption that the specified collection of points form some sort of quadrilateral/triangular area. With this assumption it tries to find corners of the area.
<note>The method does not search for bounding quadrilateral/triangular area, where all specified points are inside of the found quadrilateral/triangle. Some of the specified points potentially may be outside of the found quadrilateral/triangle, since the method takes corners only from the specified collection of points, but does not calculate such to form true bounding quadrilateral/triangle.</note>
See QuadrilateralRelativeDistortionLimit property for additional information.
References AForge.IntPoint.Add(), AForge.Math.Geometry.PointsCloud.GetBoundingRectangle(), AForge.Math.Geometry.PointsCloud.GetFurthestPoint(), AForge.Math.Geometry.PointsCloud.GetFurthestPointsFromLine(), AForge.Math.Geometry.PointsCloud.quadrilateralRelativeDistortionLimit, AForge.IntPoint.X, and AForge.IntPoint.Y.
Referenced by AForge.Math.Geometry.SimpleShapeChecker.GetShapeCorners(), AForge.Imaging.QuadrilateralFinder.ProcessImage(), and BlobsExplorer.BlobsBrowser.SetImage().
Member Data Documentation
quadrilateralRelativeDistortionLimit
float AForge.Math.Geometry.PointsCloud.quadrilateralRelativeDistortionLimit = 0.1f static private
Referenced by AForge.Math.Geometry.PointsCloud.FindQuadrilateralCorners().
Property Documentation
QuadrilateralRelativeDistortionLimit
float AForge.Math.Geometry.PointsCloud.QuadrilateralRelativeDistortionLimit static get set
Relative distortion limit allowed for quadrilaterals, [0.0, 0.25].
The value of this property is used to calculate distortion limit used by FindQuadrilateralCorners, when processing potential corners and making decision if the provided points form a quadrilateral or a triangle. The distortion limit is calculated as:
distrtionLimit = RelativeDistortionLimit * (W * H) / 2,
where W and H are width and height of the "points cloud" passed to the FindQuadrilateralCorners.
To explain the idea behind distortion limit, let’s suppose that quadrilateral finder routine found the next candidates for corners:
As we can see on the above picture, the shape there potentially can be a triangle, but not quadrilateral (suppose that points list comes from a hand drawn picture or acquired from camera, so some inaccuracy may exist). It may happen that the D point is just a distortion (noise, etc). So the FindQuadrilateralCorners check what is the distance between a potential corner (D in this case) and a line connecting two adjacent points (AB in this case). If the distance is smaller then the distortion limit, then the point may be rejected, so the shape turns into triangle.
An exception is the case when both C and D points are very close to the AB line, so both their distances are less than distortion limit. In this case both points will be accepted as corners - the shape is just a flat quadrilateral.
Default value is set to 0.1.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Math/Geometry/PointsCloud.cs