Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DTREXC Class Reference
DotNumerics.LinearAlgebra.CSLapack.DTREXC Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DTREXC (LSAME lsame, DLAEXC dlaexc, XERBLA xerbla)
DTREXC ()
void Run (string COMPQ, int N, ref double[] T, int offset_t, int LDT, ref double[] Q, int offset_q, int LDQ, ref int IFST, ref int ILST, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
LSAME _lsame
DLAEXC _dlaexc
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DTREXC reorders the real Schur factorization of a real matrix A = Q*T*Q**T, so that the diagonal block of T with row index IFST is moved to row ILST.
The real Schur form T is reordered by an orthogonal similarity transformation Z**T*T*Z, and optionally the matrix Q of Schur vectors is updated by postmultiplying it with Z.
T must be in Schur canonical form (as returned by DHSEQR), that is, block upper triangular with 1-by-1 and 2-by-2 diagonal blocks; each 2-by-2 diagonal block has its diagonal elements equal and its off-diagonal elements of opposite sign.
/summary>
Constructor & Destructor Documentation
DTREXC() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DTREXC.DTREXC (LSAME lsame, DLAEXC dlaexc, XERBLA xerbla) inline
DTREXC() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DTREXC.DTREXC () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DTREXC.Run (string COMPQ, int N, ref double[] T, int offset_t, int LDT, ref double[] Q, int offset_q, int LDQ, ref int IFST, ref int ILST, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
DTREXC reorders the real Schur factorization of a real matrix A = Q*T*Q**T, so that the diagonal block of T with row index IFST is moved to row ILST.
The real Schur form T is reordered by an orthogonal similarity transformation Z**T*T*Z, and optionally the matrix Q of Schur vectors is updated by postmultiplying it with Z.
T must be in Schur canonical form (as returned by DHSEQR), that is, block upper triangular with 1-by-1 and 2-by-2 diagonal blocks; each 2-by-2 diagonal block has its diagonal elements equal and its off-diagonal elements of opposite sign.
/summary>
Parameters
COMPQ (input) CHARACTER*1 = 'V': update the matrix Q of Schur vectors; = 'N': do not update Q. /param>
Parameters
N (input) INTEGER The order of the matrix T. N .GE. 0. /param>
Parameters
T must be in Schur canonical form (as returned by DHSEQR), that is, /param>
Parameters
LDT (input) INTEGER The leading dimension of the array T. LDT .GE. max(1,N). /param>
Parameters
Q (input/output) DOUBLE PRECISION array, dimension (LDQ,N) On entry, if COMPQ = 'V', the matrix Q of Schur vectors. On exit, if COMPQ = 'V', Q has been postmultiplied by the orthogonal transformation matrix Z which reorders T. If COMPQ = 'N', Q is not referenced. /param>
Parameters
LDQ (input) INTEGER The leading dimension of the array Q. LDQ .GE. max(1,N). /param>
Parameters
IFST (input/output) INTEGER /param>
Parameters
ILST (input/output) INTEGER Specify the reordering of the diagonal blocks of T. The block with row index IFST is moved to row ILST, by a sequence of transpositions between adjacent blocks. On exit, if IFST pointed on entry to the second row of a 2-by-2 block, it is changed to point to the first row; ILST always points to the first row of the block in its final position (which may differ from its input value by +1 or -1). 1 .LE. IFST .LE. N; 1 .LE. ILST .LE. N. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (N) /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value = 1: two adjacent blocks were too close to swap (the problem is very ill-conditioned); T may have been partially reordered, and ILST points to the first row of the current position of the block being moved. /param>
References DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAEXC.Run(), and DotNumerics.LinearAlgebra.CSLapack.DTREXC.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQR2.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAQR3.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DTREXC._lsame private
_dlaexc
DLAEXC DotNumerics.LinearAlgebra.CSLapack.DTREXC._dlaexc private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DTREXC._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DTREXC.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTREXC.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dtrexc.cs