Doc: IGLib EXTENDED: AForge.Imaging.QuadrilateralFinder Class Reference
AForge.Imaging.QuadrilateralFinder Class Reference
Searching of quadrilateral/triangle corners.
Public Member Functions
List< IntPoint > ProcessImage (Bitmap image)
Find corners of quadrilateral/triangular area in the specified image.
List< IntPoint > ProcessImage (BitmapData imageData)
Find corners of quadrilateral/triangular area in the specified image.
List< IntPoint > ProcessImage (UnmanagedImage image)
Find corners of quadrilateral/triangular area in the specified image.
Private Member Functions
void CheckPixelFormat (PixelFormat format)
Detailed Description
Searching of quadrilateral/triangle corners.
The class searches for quadrilateral's/triangle's corners on the specified image. It first collects edge points of the object and then uses AForge.Math.Geometry.PointsCloud.FindQuadrilateralCorners to find corners the quadrilateral/triangle.
<note>The class treats all black pixels as background (none-object) and all none-black pixels as object.</note>
The class processes grayscale 8 bpp and color 24/32 bpp images.
Sample usage:
// get corners of the quadrilateral
QuadrilateralFinder qf = new QuadrilateralFinder();
List<IntPoint> corners = qf.ProcessImage(image);
// lock image to draw on it with AForge.NET's methods
// (or draw directly on image without locking if it is unmanaged image)
BitmapData data = image.LockBits(new Rectangle(0, 0, image.Width, image.Height),
    ImageLockMode.ReadWrite, image.PixelFormat );
Drawing.Polygon(data, corners, Color.Red);
for (int i = 0; i < corners.Count; i++)
{
    Drawing.FillRectangle( data,
        new Rectangle( corners[i].X - 2, corners[i].Y - 2, 5, 5 ),
        Color.FromArgb( i * 32 + 127 + 32, i * 64, i * 64 ) );
}
image.UnlockBits(data);
Source image:
Result image:
Member Function Documentation
ProcessImage() [1/3]
List<IntPoint> AForge.Imaging.QuadrilateralFinder.ProcessImage (Bitmap image) inline
Find corners of quadrilateral/triangular area in the specified image.
Parameters
image Source image to search quadrilateral for.
Returns
Returns a list of points, which are corners of the quadrilateral/triangular area found in the specified image. The first point in the list is the point with lowest X coordinate (and with lowest Y if there are several points with the same X value). Points are in clockwise order (screen coordinates system).
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Imaging.QuadrilateralFinder.CheckPixelFormat(), and AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.QuadrilateralFinder.ProcessImage().
ProcessImage() [2/3]
List<IntPoint> AForge.Imaging.QuadrilateralFinder.ProcessImage (BitmapData imageData) inline
Find corners of quadrilateral/triangular area in the specified image.
Parameters
imageData Source image data to search quadrilateral for.
Returns
Returns a list of points, which are corners of the quadrilateral/triangular area found in the specified image. The first point in the list is the point with lowest X coordinate (and with lowest Y if there are several points with the same X value). Points are in clockwise order (screen coordinates system).
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Imaging.QuadrilateralFinder.ProcessImage().
ProcessImage() [3/3]
List<IntPoint> AForge.Imaging.QuadrilateralFinder.ProcessImage (UnmanagedImage image) inline
Find corners of quadrilateral/triangular area in the specified image.
Parameters
image Source image to search quadrilateral for.
Returns
Returns a list of points, which are corners of the quadrilateral/triangular area found in the specified image. The first point in the list is the point with lowest X coordinate (and with lowest Y if there are several points with the same X value). Points are in clockwise order (screen coordinates system).
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Imaging.RGB.B, AForge.Imaging.QuadrilateralFinder.CheckPixelFormat(), AForge.Math.Geometry.PointsCloud.FindQuadrilateralCorners(), AForge.Imaging.RGB.G, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
CheckPixelFormat()
void AForge.Imaging.QuadrilateralFinder.CheckPixelFormat (PixelFormat format) inline private
Referenced by AForge.Imaging.QuadrilateralFinder.ProcessImage().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/QuadrilateralFinder.cs