Doc: IGLib EXTENDED: alglib.rbf Class Reference
alglib.rbf Class Reference
Classes
class rbfmodel
class rbfreport
Static Public Member Functions
static void rbfcreate (int nx, int ny, rbfmodel s)
static void rbfsetpoints (rbfmodel s, double[,] xy, int n)
static void rbfsetalgoqnn (rbfmodel s, double q, double z)
static void rbfsetalgomultilayer (rbfmodel s, double rbase, int nlayers, double lambdav)
static void rbfsetlinterm (rbfmodel s)
static void rbfsetconstterm (rbfmodel s)
static void rbfsetzeroterm (rbfmodel s)
static void rbfsetcond (rbfmodel s, double epsort, double epserr, int maxits)
static void rbfbuildmodel (rbfmodel s, rbfreport rep)
static double rbfcalc2 (rbfmodel s, double x0, double x1)
static double rbfcalc3 (rbfmodel s, double x0, double x1, double x2)
static void rbfcalc (rbfmodel s, double[] x, ref double[] y)
static void rbfcalcbuf (rbfmodel s, double[] x, ref double[] y)
static void rbfgridcalc2 (rbfmodel s, double[] x0, int n0, double[] x1, int n1, ref double[,] y)
static void rbfunpack (rbfmodel s, ref int nx, ref int ny, ref double[,] xwr, ref int nc, ref double[,] v)
static void rbfalloc (alglib.serializer s, rbfmodel model)
static void rbfserialize (alglib.serializer s, rbfmodel model)
static void rbfunserialize (alglib.serializer s, rbfmodel model)
static void rbfcreate (int nx, int ny, rbfmodel s)
static void rbfsetpoints (rbfmodel s, double[,] xy, int n)
static void rbfsetalgoqnn (rbfmodel s, double q, double z)
static void rbfsetalgomultilayer (rbfmodel s, double rbase, int nlayers, double lambdav)
static void rbfsetlinterm (rbfmodel s)
static void rbfsetconstterm (rbfmodel s)
static void rbfsetzeroterm (rbfmodel s)
static void rbfsetcond (rbfmodel s, double epsort, double epserr, int maxits)
static void rbfbuildmodel (rbfmodel s, rbfreport rep)
static double rbfcalc2 (rbfmodel s, double x0, double x1)
static double rbfcalc3 (rbfmodel s, double x0, double x1, double x2)
static void rbfcalc (rbfmodel s, double[] x, ref double[] y)
static void rbfcalcbuf (rbfmodel s, double[] x, ref double[] y)
static void rbfgridcalc2 (rbfmodel s, double[] x0, int n0, double[] x1, int n1, ref double[,] y)
static void rbfunpack (rbfmodel s, ref int nx, ref int ny, ref double[,] xwr, ref int nc, ref double[,] v)
static void rbfalloc (alglib.serializer s, rbfmodel model)
static void rbfserialize (alglib.serializer s, rbfmodel model)
static void rbfunserialize (alglib.serializer s, rbfmodel model)
Static Public Attributes
const double eps = 1.0E-6
const int mxnx = 3
const double rbffarradius = 6
const double rbfnearradius = 2.1
const double rbfmlradius = 3
const int rbffirstversion = 0
Static Private Member Functions
static void rbfgridregular (rbfmodel s, double h)
static void rbfgridpoints (rbfmodel s)
static void rbfgridspecial (rbfmodel s, double[,] cxy, int nc)
static void rbfradfixed (rbfmodel s, double r)
static void rbfradnn (rbfmodel s, double q, double z)
static bool buildlinearmodel (double[,] x, ref double[,] y, int n, int ny, int modeltype, ref double[,] v)
static void buildrbfmodellsqr (double[,] x, ref double[,] y, double[,] xc, double[] r, int n, int nc, int ny, nearestneighbor.kdtree pointstree, nearestneighbor.kdtree centerstree, double epsort, double epserr, int maxits, ref int gnnz, ref int snnz, ref double[,] w, ref int info, ref int iterationscount, ref int nmv)
static void buildrbfmlayersmodellsqr (double[,] x, ref double[,] y, ref double[,] xc, double rval, ref double[] r, int n, ref int nc, int ny, int nlayers, nearestneighbor.kdtree centerstree, double epsort, double epserr, int maxits, double lambdav, ref int annz, ref double[,] w, ref int info, ref int iterationscount, ref int nmv)
static void rbfgridpoints (rbfmodel s)
static void rbfradnn (rbfmodel s, double q, double z)
static bool buildlinearmodel (double[,] x, ref double[,] y, int n, int ny, int modeltype, ref double[,] v)
static void buildrbfmodellsqr (double[,] x, ref double[,] y, double[,] xc, double[] r, int n, int nc, int ny, nearestneighbor.kdtree pointstree, nearestneighbor.kdtree centerstree, double epsort, double epserr, int maxits, ref int gnnz, ref int snnz, ref double[,] w, ref int info, ref int iterationscount, ref int nmv)
static void buildrbfmlayersmodellsqr (double[,] x, ref double[,] y, ref double[,] xc, double rval, ref double[] r, int n, ref int nc, int ny, int nlayers, nearestneighbor.kdtree centerstree, double epsort, double epserr, int maxits, double lambdav, ref int annz, ref double[,] w, ref int info, ref int iterationscount, ref int nmv)
Member Function Documentation
rbfcreate() [1/2]
static void alglib.rbf.rbfcreate (int nx, int ny, rbfmodel s) inline static
Referenced by alglib.testrbfunit.basicmultilayerrbf1dtest(), alglib.testrbfunit.basicmultilayerrbftest(), alglib.testrbfunit.basicrbftest(), alglib.testrbfunit.irregularrbftest(), alglib.testrbfunit.linearitymodelrbftest(), alglib.rbfcreate(), alglib.testrbfunit.serializationtest(), alglib.testrbfunit.specialtest(), and alglib.testrbfunit.sqrdegmatrixrbftest().
rbfsetpoints() [1/2]
static void alglib.rbf.rbfsetpoints (rbfmodel s, double xy[,], int n) inline static
Referenced by alglib.testrbfunit.basicmultilayerrbf1dtest(), alglib.testrbfunit.basicmultilayerrbftest(), alglib.testrbfunit.basicrbftest(), alglib.testrbfunit.irregularrbftest(), alglib.testrbfunit.linearitymodelrbftest(), alglib.rbfsetpoints(), alglib.testrbfunit.serializationtest(), alglib.testrbfunit.specialtest(), and alglib.testrbfunit.sqrdegmatrixrbftest().
rbfsetalgoqnn() [1/2]
static void alglib.rbf.rbfsetalgoqnn (rbfmodel s, double q, double z) inline static
Referenced by alglib.testrbfunit.basicrbftest(), alglib.testrbfunit.irregularrbftest(), alglib.testrbfunit.linearitymodelrbftest(), alglib.rbfsetalgoqnn(), alglib.testrbfunit.serializationtest(), alglib.testrbfunit.specialtest(), and alglib.testrbfunit.sqrdegmatrixrbftest().
rbfsetalgomultilayer() [1/2]
static void alglib.rbf.rbfsetalgomultilayer (rbfmodel s, double rbase, int nlayers, double lambdav) inline static
Referenced by alglib.testrbfunit.basicmultilayerrbf1dtest(), alglib.testrbfunit.basicmultilayerrbftest(), alglib.rbfsetalgomultilayer(), alglib.testrbfunit.serializationtest(), and alglib.testrbfunit.specialtest().
rbfsetlinterm() [1/2]
static void alglib.rbf.rbfsetlinterm (rbfmodel s) inline static
Referenced by alglib.testrbfunit.basicmultilayerrbf1dtest(), alglib.testrbfunit.basicmultilayerrbftest(), alglib.testrbfunit.basicrbftest(), alglib.testrbfunit.irregularrbftest(), alglib.testrbfunit.linearitymodelrbftest(), alglib.rbfsetlinterm(), alglib.testrbfunit.serializationtest(), and alglib.testrbfunit.specialtest().
rbfsetconstterm() [1/2]
static void alglib.rbf.rbfsetconstterm (rbfmodel s) inline static
Referenced by alglib.testrbfunit.basicmultilayerrbf1dtest(), alglib.testrbfunit.basicmultilayerrbftest(), alglib.testrbfunit.basicrbftest(), alglib.testrbfunit.irregularrbftest(), alglib.testrbfunit.linearitymodelrbftest(), alglib.rbfsetconstterm(), and alglib.testrbfunit.specialtest().
rbfsetzeroterm() [1/2]
static void alglib.rbf.rbfsetzeroterm (rbfmodel s) inline static
Referenced by alglib.testrbfunit.basicmultilayerrbf1dtest(), alglib.testrbfunit.basicmultilayerrbftest(), alglib.testrbfunit.basicrbftest(), alglib.testrbfunit.irregularrbftest(), alglib.testrbfunit.linearitymodelrbftest(), alglib.rbfsetzeroterm(), and alglib.testrbfunit.specialtest().
rbfsetcond() [1/2]
static void alglib.rbf.rbfsetcond (rbfmodel s, double epsort, double epserr, int maxits) inline static
Referenced by alglib.testrbfunit.basicrbftest(), alglib.testrbfunit.irregularrbftest(), and alglib.testrbfunit.sqrdegmatrixrbftest().
rbfbuildmodel() [1/2]
static void alglib.rbf.rbfbuildmodel (rbfmodel s, rbfreport rep) inline static
Referenced by alglib.testrbfunit.basicmultilayerrbf1dtest(), alglib.testrbfunit.basicmultilayerrbftest(), alglib.testrbfunit.basicrbftest(), alglib.testrbfunit.irregularrbftest(), alglib.testrbfunit.linearitymodelrbftest(), alglib.rbfbuildmodel(), alglib.testrbfunit.serializationtest(), alglib.testrbfunit.specialtest(), and alglib.testrbfunit.sqrdegmatrixrbftest().
rbfcalc2() [1/2]
static double alglib.rbf.rbfcalc2 (rbfmodel s, double x0, double x1) inline static
Referenced by alglib.testrbfunit.basicmultilayerrbf1dtest(), alglib.testrbfunit.basicmultilayerrbftest(), alglib.testrbfunit.basicrbftest(), alglib.testrbfunit.irregularrbftest(), alglib.rbfcalc2(), and alglib.testrbfunit.specialtest().
rbfcalc3() [1/2]
static double alglib.rbf.rbfcalc3 (rbfmodel s, double x0, double x1, double x2) inline static
Referenced by alglib.testrbfunit.basicmultilayerrbf1dtest(), alglib.testrbfunit.basicmultilayerrbftest(), alglib.testrbfunit.basicrbftest(), alglib.testrbfunit.irregularrbftest(), alglib.rbfcalc3(), and alglib.testrbfunit.specialtest().
rbfcalc() [1/2]
static void alglib.rbf.rbfcalc (rbfmodel s, double[] x, ref double[] y) inline static
Referenced by alglib.testrbfunit.basicmultilayerrbf1dtest(), alglib.testrbfunit.basicmultilayerrbftest(), alglib.testrbfunit.basicrbftest(), alglib.testrbfunit.irregularrbftest(), alglib.rbfcalc(), alglib.testrbfunit.serializationtest(), alglib.testrbfunit.specialtest(), and alglib.testrbfunit.sqrdegmatrixrbftest().
rbfcalcbuf() [1/2]
static void alglib.rbf.rbfcalcbuf (rbfmodel s, double[] x, ref double[] y) inline static
Referenced by alglib.testrbfunit.basicmultilayerrbf1dtest(), alglib.testrbfunit.basicmultilayerrbftest(), alglib.testrbfunit.basicrbftest(), alglib.testrbfunit.irregularrbftest(), and alglib.rbfcalcbuf().
rbfgridcalc2() [1/2]
static void alglib.rbf.rbfgridcalc2 (rbfmodel s, double[] x0, int n0, double[] x1, int n1, ref double y[,]) inline static
Referenced by alglib.testrbfunit.basicmultilayerrbf1dtest(), alglib.testrbfunit.basicmultilayerrbftest(), alglib.testrbfunit.basicrbftest(), and alglib.rbfgridcalc2().
rbfunpack() [1/2]
static void alglib.rbf.rbfunpack (rbfmodel s, ref int nx, ref int ny, ref double xwr[,], ref int nc, ref double v[,]) inline static
Referenced by alglib.testrbfunit.basicrbftest(), alglib.testrbfunit.linearitymodelrbftest(), alglib.rbfunpack(), alglib.testrbfunit.specialtest(), and alglib.testrbfunit.sqrdegmatrixrbftest().
rbfalloc() [1/2]
static void alglib.rbf.rbfalloc (alglib.serializer s, rbfmodel model) inline static
Referenced by alglib.rbfserialize(), and alglib.testrbfunit.serializationtest().
rbfserialize() [1/2]
static void alglib.rbf.rbfserialize (alglib.serializer s, rbfmodel model) inline static
Referenced by alglib.rbfserialize(), and alglib.testrbfunit.serializationtest().
rbfunserialize() [1/2]
static void alglib.rbf.rbfunserialize (alglib.serializer s, rbfmodel model) inline static
Referenced by alglib.rbfunserialize(), and alglib.testrbfunit.serializationtest().
rbfgridregular()
static void alglib.rbf.rbfgridregular (rbfmodel s, double h) inline static private
rbfgridpoints() [1/2]
static void alglib.rbf.rbfgridpoints (rbfmodel s) inline static private
rbfgridspecial()
static void alglib.rbf.rbfgridspecial (rbfmodel s, double cxy[,], int nc) inline static private
rbfradfixed()
static void alglib.rbf.rbfradfixed (rbfmodel s, double r) inline static private
rbfradnn() [1/2]
static void alglib.rbf.rbfradnn (rbfmodel s, double q, double z) inline static private
buildlinearmodel() [1/2]
static bool alglib.rbf.buildlinearmodel (double x[,], ref double y[,], int n, int ny, int modeltype, ref double v[,]) inline static private
buildrbfmodellsqr() [1/2]
static void alglib.rbf.buildrbfmodellsqr (double x[,], ref double y[,], double xc[,], double[] r, int n, int nc, int ny, nearestneighbor.kdtree pointstree, nearestneighbor.kdtree centerstree, double epsort, double epserr, int maxits, ref int gnnz, ref int snnz, ref double w[,], ref int info, ref int iterationscount, ref int nmv) inline static private
buildrbfmlayersmodellsqr() [1/2]
static void alglib.rbf.buildrbfmlayersmodellsqr (double x[,], ref double y[,], ref double xc[,], double rval, ref double[] r, int n, ref int nc, int ny, int nlayers, nearestneighbor.kdtree centerstree, double epsort, double epserr, int maxits, double lambdav, ref int annz, ref double w[,], ref int info, ref int iterationscount, ref int nmv) inline static private
rbfcreate() [2/2]
static void alglib.rbf.rbfcreate (int nx, int ny, rbfmodel s) inline static
References alglib.ap.assert().
rbfsetpoints() [2/2]
static void alglib.rbf.rbfsetpoints (rbfmodel s, double xy[,], int n) inline static
References alglib.ap.assert().
rbfsetalgoqnn() [2/2]
static void alglib.rbf.rbfsetalgoqnn (rbfmodel s, double q, double z) inline static
References alglib.ap.assert(), and alglib.math.isfinite().
rbfsetalgomultilayer() [2/2]
static void alglib.rbf.rbfsetalgomultilayer (rbfmodel s, double rbase, int nlayers, double lambdav) inline static
References alglib.ap.assert(), and alglib.math.isfinite().
rbfsetlinterm() [2/2]
static void alglib.rbf.rbfsetlinterm (rbfmodel s) inline static
rbfsetconstterm() [2/2]
static void alglib.rbf.rbfsetconstterm (rbfmodel s) inline static
rbfsetzeroterm() [2/2]
static void alglib.rbf.rbfsetzeroterm (rbfmodel s) inline static
rbfsetcond() [2/2]
static void alglib.rbf.rbfsetcond (rbfmodel s, double epsort, double epserr, int maxits) inline static
References alglib.ap.assert(), and alglib.math.isfinite().
rbfbuildmodel() [2/2]
static void alglib.rbf.rbfbuildmodel (rbfmodel s, rbfreport rep) inline static
References alglib.rbf.rbfreport.acols, alglib.rbf.rbfreport.annz, alglib.rbf.rbfreport.arows, alglib.ap.assert(), alglib.rbf.rbfreport.iterationscount, alglib.apserv.ivectorsetlengthatleast(), alglib.nearestneighbor.kdtreebuildtagged(), alglib.nearestneighbor.kdtreequeryknn(), alglib.nearestneighbor.kdtreequeryresultsdistances(), alglib.rbf.rbfreport.nmv, alglib.apserv.rvectorsetlengthatleast(), alglib.tsort.tagsortfast(), and alglib.rbf.rbfreport.terminationtype.
rbfcalc2() [2/2]
static double alglib.rbf.rbfcalc2 (rbfmodel s, double x0, double x1) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.nearestneighbor.kdtreequeryresultstags(), alglib.nearestneighbor.kdtreequeryresultsx(), alglib.nearestneighbor.kdtreequeryrnn(), alglib.apserv.rvectorsetlengthatleast(), and alglib.math.sqr().
rbfcalc3() [2/2]
static double alglib.rbf.rbfcalc3 (rbfmodel s, double x0, double x1, double x2) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.nearestneighbor.kdtreequeryresultstags(), alglib.nearestneighbor.kdtreequeryresultsx(), alglib.nearestneighbor.kdtreequeryrnn(), alglib.apserv.rvectorsetlengthatleast(), and alglib.math.sqr().
rbfcalc() [2/2]
static void alglib.rbf.rbfcalc (rbfmodel s, double[] x, ref double[] y) inline static
References alglib.ap.assert(), and alglib.apserv.isfinitevector().
rbfcalcbuf() [2/2]
static void alglib.rbf.rbfcalcbuf (rbfmodel s, double[] x, ref double[] y) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), alglib.nearestneighbor.kdtreequeryresultstags(), alglib.nearestneighbor.kdtreequeryresultsx(), alglib.nearestneighbor.kdtreequeryrnn(), alglib.apserv.rvectorsetlengthatleast(), and alglib.math.sqr().
rbfgridcalc2() [2/2]
static void alglib.rbf.rbfgridcalc2 (rbfmodel s, double[] x0, int n0, double[] x1, int n1, ref double y[,]) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), alglib.tsort.lowerbound(), alglib.math.sqr(), alglib.tsort.tagsort(), and alglib.tsort.upperbound().
rbfunpack() [2/2]
static void alglib.rbf.rbfunpack (rbfmodel s, ref int nx, ref int ny, ref double xwr[,], ref int nc, ref double v[,]) inline static
rbfalloc() [2/2]
static void alglib.rbf.rbfalloc (alglib.serializer s, rbfmodel model) inline static
References alglib.apserv.allocrealmatrix(), and alglib.nearestneighbor.kdtreealloc().
rbfserialize() [2/2]
static void alglib.rbf.rbfserialize (alglib.serializer s, rbfmodel model) inline static
References alglib.scodes.getrbfserializationcode(), alglib.nearestneighbor.kdtreeserialize(), and alglib.apserv.serializerealmatrix().
rbfunserialize() [2/2]
static void alglib.rbf.rbfunserialize (alglib.serializer s, rbfmodel model) inline static
References alglib.ap.assert(), alglib.scodes.getrbfserializationcode(), alglib.nearestneighbor.kdtreeunserialize(), and alglib.apserv.unserializerealmatrix().
rbfgridpoints() [2/2]
static void alglib.rbf.rbfgridpoints (rbfmodel s) inline static private
rbfradnn() [2/2]
static void alglib.rbf.rbfradnn (rbfmodel s, double q, double z) inline static private
References alglib.ap.assert(), and alglib.math.isfinite().
buildlinearmodel() [2/2]
static bool alglib.rbf.buildlinearmodel (double x[,], ref double y[,], int n, int ny, int modeltype, ref double v[,]) inline static private
References alglib.ap.assert(), and alglib.lsfit.lsfitlinear().
buildrbfmodellsqr() [2/2]
static void alglib.rbf.buildrbfmodellsqr (double x[,], ref double y[,], double xc[,], double[] r, int n, int nc, int ny, nearestneighbor.kdtree pointstree, nearestneighbor.kdtree centerstree, double epsort, double epserr, int maxits, ref int gnnz, ref int snnz, ref double w[,], ref int info, ref int iterationscount, ref int nmv) inline static private
References alglib.ap.assert(), alglib.fbls.fblssolvels(), alglib.nearestneighbor.kdtreequeryknn(), alglib.nearestneighbor.kdtreequeryresultstags(), alglib.nearestneighbor.kdtreequeryresultsx(), alglib.nearestneighbor.kdtreequeryrnn(), alglib.linlsqr.linlsqrcreate(), alglib.linlsqr.linlsqrresults(), alglib.linlsqr.linlsqrsetcond(), alglib.linlsqr.linlsqrsolvesparse(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparsemtv(), alglib.sparse.sparseset(), and alglib.math.sqr().
buildrbfmlayersmodellsqr() [2/2]
static void alglib.rbf.buildrbfmlayersmodellsqr (double x[,], ref double y[,], ref double xc[,], double rval, ref double[] r, int n, ref int nc, int ny, int nlayers, nearestneighbor.kdtree centerstree, double epsort, double epserr, int maxits, double lambdav, ref int annz, ref double w[,], ref int info, ref int iterationscount, ref int nmv) inline static private
References alglib.ap.assert(), alglib.nearestneighbor.kdtreebuildtagged(), alglib.nearestneighbor.kdtreequeryresultstags(), alglib.nearestneighbor.kdtreequeryresultsx(), alglib.nearestneighbor.kdtreequeryrnn(), alglib.linlsqr.linlsqrcreate(), alglib.linlsqr.linlsqrresults(), alglib.linlsqr.linlsqrsetcond(), alglib.linlsqr.linlsqrsetlambdai(), alglib.linlsqr.linlsqrsolvesparse(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparseset(), and alglib.math.sqr().
Member Data Documentation
eps
const double alglib.rbf.eps = 1.0E-6 static
mxnx
const int alglib.rbf.mxnx = 3 static
rbffarradius
const double alglib.rbf.rbffarradius = 6 static
rbfnearradius
const double alglib.rbf.rbfnearradius = 2.1 static
rbfmlradius
const double alglib.rbf.rbfmlradius = 3 static
rbffirstversion
const int alglib.rbf.rbffirstversion = 0 static
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/interpolation.cs