Doc: IGLib EXTENDED: NUnit.Framework.Api.NUnitTestAssemblyRunner Class Reference
NUnit.Framework.Api.NUnitTestAssemblyRunner Class Reference
Implementation of ITestAssemblyRunner
Public Member Functions
NUnitTestAssemblyRunner (ITestAssemblyBuilder builder)
Initializes a new instance of the NUnitTestAssemblyRunner class.
ITest Load (string assemblyName, IDictionary settings)
Loads the tests found in an Assembly
ITest Load (Assembly assembly, IDictionary settings)
Loads the tests found in an Assembly
int CountTestCases (ITestFilter filter)
Count Test Cases using a filter
ITestResult Run (ITestListener listener, ITestFilter filter)
Run selected tests and return a test result. The test is run synchronously, and the listener interface is notified as it progresses.
void RunAsync (ITestListener listener, ITestFilter filter)
Run selected tests asynchronously, notifying the listener interface as it progresses.
bool WaitForCompletion (int timeout)
Wait for the ongoing run to complete.
void StartRun (ITestListener listener)
Initiate the test run.
void StopRun (bool force)
Signal any test run that is in process to stop. Return without error if no test is running.
Public Member Functions inherited from NUnit.Framework.Api.ITestAssemblyRunner
ITest Load (string assemblyName, System.Collections.IDictionary settings)
Loads the tests found in an Assembly, returning an indication of whether or not the load succeeded.
ITest Load (Assembly assembly, System.Collections.IDictionary settings)
Loads the tests found in an Assembly, returning an indication of whether or not the load succeeded.
Properties
ITest LoadedTest [get, private set]
The tree of tests that was loaded by the builder
ITestResult? Result [get]
The test result, if a run has completed
bool IsTestLoaded [get]
Indicates whether a test is loaded
bool IsTestRunning [get]
Indicates whether a test is running
bool IsTestComplete [get]
Indicates whether a test run is complete
IDictionary Settings [get, set]
Our settings, specified when loading the assembly
WorkItem TopLevelWorkItem [get, set]
The top level WorkItem created for the assembly as a whole
TestExecutionContext Context [get, set]
The TestExecutionContext for the top level WorkItem
Properties inherited from NUnit.Framework.Api.ITestAssemblyRunner
ITest LoadedTest [get]
Gets the tree of loaded tests, or null if no tests have been loaded.
ITestResult Result [get]
Gets the tree of test results, if the test run is completed, otherwise null.
bool IsTestLoaded [get]
Indicates whether a test has been loaded
bool IsTestRunning [get]
Indicates whether a test is currently running
bool IsTestComplete [get]
Indicates whether a test run is complete
Private Member Functions
void CreateTestExecutionContext (ITestListener listener)
Create the initial TestExecutionContext used to run tests
void OnRunCompleted (object sender, EventArgs e)
Handle the the Completed event for the top level work item
int CountTestCases (ITest test, ITestFilter filter)
Static Private Member Functions
static int GetInitialSeed (IDictionary settings)
static void PauseBeforeRun ()
Private Attributes
ITestAssemblyBuilder _builder
AutoResetEvent _runComplete = new AutoResetEvent(false)
TextWriter _savedOut
TextWriter _savedErr
Static Private Attributes
static Logger log = InternalTrace.GetLogger("DefaultTestAssemblyRunner")
Detailed Description
Implementation of ITestAssemblyRunner
Constructor & Destructor Documentation
NUnitTestAssemblyRunner()
NUnit.Framework.Api.NUnitTestAssemblyRunner.NUnitTestAssemblyRunner (ITestAssemblyBuilder builder) inline
Initializes a new instance of the NUnitTestAssemblyRunner class.
Parameters
builder The builder.
References NUnit.Framework.Api.NUnitTestAssemblyRunner._builder.
Member Function Documentation
Load() [1/2]
ITest NUnit.Framework.Api.NUnitTestAssemblyRunner.Load (string assemblyName, IDictionary settings) inline
Loads the tests found in an Assembly
Parameters
assemblyName File name of the assembly to load
settings Dictionary of option settings for loading the assembly
Returns
True if the load was successful
References NUnit.Framework.Api.NUnitTestAssemblyRunner._builder, NUnit.Framework.Api.ITestAssemblyBuilder.Build(), NUnit.Framework.Api.NUnitTestAssemblyRunner.GetInitialSeed(), NUnit.Framework.Internal.Randomizer.InitialSeed, NUnit.Framework.Api.NUnitTestAssemblyRunner.LoadedTest, and NUnit.Framework.Api.NUnitTestAssemblyRunner.Settings.
Load() [2/2]
ITest NUnit.Framework.Api.NUnitTestAssemblyRunner.Load (Assembly assembly, IDictionary settings) inline
Loads the tests found in an Assembly
Parameters
assembly The assembly to load
settings Dictionary of option settings for loading the assembly
Returns
True if the load was successful
References NUnit.Framework.Api.NUnitTestAssemblyRunner._builder, NUnit.Framework.Api.ITestAssemblyBuilder.Build(), NUnit.Framework.Api.NUnitTestAssemblyRunner.GetInitialSeed(), NUnit.Framework.Internal.Randomizer.InitialSeed, NUnit.Framework.Api.NUnitTestAssemblyRunner.LoadedTest, and NUnit.Framework.Api.NUnitTestAssemblyRunner.Settings.
CountTestCases() [1/2]
int NUnit.Framework.Api.NUnitTestAssemblyRunner.CountTestCases (ITestFilter filter) inline
Count Test Cases using a filter
Parameters
filter The filter to apply
Returns
The number of test cases found
Implements NUnit.Framework.Api.ITestAssemblyRunner.
References NUnit.Framework.Api.NUnitTestAssemblyRunner.LoadedTest.
Referenced by NUnit.Framework.Api.NUnitTestAssemblyRunner.CountTestCases().
Run()
ITestResult NUnit.Framework.Api.NUnitTestAssemblyRunner.Run (ITestListener listener, ITestFilter filter) inline
Run selected tests and return a test result. The test is run synchronously, and the listener interface is notified as it progresses.
Parameters
listener Interface to receive EventListener notifications.
filter A test filter used to select tests to be run
Returns
Implements NUnit.Framework.Api.ITestAssemblyRunner.
References NUnit.Framework.Api.NUnitTestAssemblyRunner.Result, NUnit.Framework.Api.NUnitTestAssemblyRunner.RunAsync(), and NUnit.Framework.Api.NUnitTestAssemblyRunner.WaitForCompletion().
RunAsync()
void NUnit.Framework.Api.NUnitTestAssemblyRunner.RunAsync (ITestListener listener, ITestFilter filter) inline
Run selected tests asynchronously, notifying the listener interface as it progresses.
Parameters
listener Interface to receive EventListener notifications.
filter A test filter used to select tests to be run
RunAsync is a template method, calling various abstract and virtual methods to be overridden by derived classes.
Implements NUnit.Framework.Api.ITestAssemblyRunner.
References NUnit.Framework.Internal.Execution.WorkItem.Completed, NUnit.Framework.Api.NUnitTestAssemblyRunner.Context, NUnit.Framework.Api.NUnitTestAssemblyRunner.CreateTestExecutionContext(), NUnit.Framework.Internal.Execution.WorkItem.CreateWorkItem(), NUnit.Common.Logger.Info(), NUnit.Framework.Internal.Execution.WorkItem.InitializeContext(), NUnit.Framework.Api.NUnitTestAssemblyRunner.LoadedTest, NUnit.Framework.Api.NUnitTestAssemblyRunner.log, NUnit.Framework.Api.NUnitTestAssemblyRunner.OnRunCompleted(), NUnit.Framework.Api.NUnitTestAssemblyRunner.StartRun(), and NUnit.Framework.Api.NUnitTestAssemblyRunner.TopLevelWorkItem.
Referenced by NUnit.Framework.Api.NUnitTestAssemblyRunner.Run().
WaitForCompletion()
bool NUnit.Framework.Api.NUnitTestAssemblyRunner.WaitForCompletion (int timeout) inline
Wait for the ongoing run to complete.
Parameters
timeout Time to wait in milliseconds
Returns
True if the run completed, otherwise false
Implements NUnit.Framework.Api.ITestAssemblyRunner.
References NUnit.Framework.Api.NUnitTestAssemblyRunner._runComplete.
Referenced by NUnit.Framework.Api.NUnitTestAssemblyRunner.Run().
StartRun()
void NUnit.Framework.Api.NUnitTestAssemblyRunner.StartRun (ITestListener listener) inline
Initiate the test run.
References NUnit.Framework.Api.NUnitTestAssemblyRunner._savedErr, NUnit.Framework.Api.NUnitTestAssemblyRunner._savedOut, NUnit.Framework.Api.NUnitTestAssemblyRunner.Context, NUnit.Common.PackageSettings.DebugTests, NUnit.Framework.Internal.Execution.IWorkItemDispatcher.Dispatch(), NUnit.Common.PackageSettings.PauseBeforeRun, NUnit.Framework.Api.NUnitTestAssemblyRunner.PauseBeforeRun(), NUnit.Framework.Api.NUnitTestAssemblyRunner.Settings, NUnit.Common.PackageSettings.SynchronousEvents, and NUnit.Framework.Api.NUnitTestAssemblyRunner.TopLevelWorkItem.
Referenced by NUnit.Framework.Api.NUnitTestAssemblyRunner.RunAsync().
StopRun()
void NUnit.Framework.Api.NUnitTestAssemblyRunner.StopRun (bool force) inline
Signal any test run that is in process to stop. Return without error if no test is running.
Parameters
force If true, kill any test-running threads
Implements NUnit.Framework.Api.ITestAssemblyRunner.
References NUnit.Framework.Internal.Execution.IWorkItemDispatcher.CancelRun(), NUnit.Framework.Api.NUnitTestAssemblyRunner.Context, NUnit.Framework.Internal.TestExecutionContext.ExecutionStatus, and NUnit.Framework.Api.NUnitTestAssemblyRunner.IsTestRunning.
CreateTestExecutionContext()
void NUnit.Framework.Api.NUnitTestAssemblyRunner.CreateTestExecutionContext (ITestListener listener) inline private
Create the initial TestExecutionContext used to run tests
Parameters
listener The ITestListener specified in the RunAsync call
References NUnit.Framework.Interfaces.IPropertyBag.ContainsKey(), NUnit.Framework.Api.NUnitTestAssemblyRunner.Context, NUnit.Common.PackageSettings.DefaultTimeout, NUnit.Env.DefaultWorkDirectory, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Api.NUnitTestAssemblyRunner.LoadedTest, NUnit.Framework.Internal.PropertyNames.ParallelScope, NUnit.Framework.Internal.TestExecutionContext.ParallelScope, NUnit.Framework.Interfaces.ITest.Properties, NUnit.Framework.Api.NUnitTestAssemblyRunner.Settings, NUnit.Common.PackageSettings.StopOnError, NUnit.Framework.Internal.TestExecutionContext.StopOnError, NUnit.Framework.Internal.TestExecutionContext.TestCaseTimeout, NUnit.Common.PackageSettings.WorkDirectory, and NUnit.Framework.Internal.TestExecutionContext.WorkDirectory.
Referenced by NUnit.Framework.Api.NUnitTestAssemblyRunner.RunAsync().
OnRunCompleted()
void NUnit.Framework.Api.NUnitTestAssemblyRunner.OnRunCompleted (object sender, EventArgs e) inline private
Handle the the Completed event for the top level work item
References NUnit.Framework.Api.NUnitTestAssemblyRunner._runComplete, NUnit.Framework.Api.NUnitTestAssemblyRunner._savedErr, and NUnit.Framework.Api.NUnitTestAssemblyRunner._savedOut.
Referenced by NUnit.Framework.Api.NUnitTestAssemblyRunner.RunAsync().
CountTestCases() [2/2]
int NUnit.Framework.Api.NUnitTestAssemblyRunner.CountTestCases (ITest test, ITestFilter filter) inline private
References NUnit.Framework.Api.NUnitTestAssemblyRunner.CountTestCases(), NUnit.Framework.Interfaces.ITest.IsSuite, and NUnit.Framework.Interfaces.ITest.Tests.
GetInitialSeed()
static int NUnit.Framework.Api.NUnitTestAssemblyRunner.GetInitialSeed (IDictionary settings) inline static private
References NUnit.Common.PackageSettings.RandomSeed.
Referenced by NUnit.Framework.Api.NUnitTestAssemblyRunner.Load().
PauseBeforeRun()
static void NUnit.Framework.Api.NUnitTestAssemblyRunner.PauseBeforeRun () inline static private
Referenced by NUnit.Framework.Api.NUnitTestAssemblyRunner.StartRun().
Member Data Documentation
log
Logger NUnit.Framework.Api.NUnitTestAssemblyRunner.log = InternalTrace.GetLogger("DefaultTestAssemblyRunner") static private
Referenced by NUnit.Framework.Api.NUnitTestAssemblyRunner.RunAsync().
_builder
ITestAssemblyBuilder NUnit.Framework.Api.NUnitTestAssemblyRunner._builder private
Referenced by NUnit.Framework.Api.NUnitTestAssemblyRunner.Load(), and NUnit.Framework.Api.NUnitTestAssemblyRunner.NUnitTestAssemblyRunner().
_runComplete
AutoResetEvent NUnit.Framework.Api.NUnitTestAssemblyRunner._runComplete = new AutoResetEvent(false) private
Referenced by NUnit.Framework.Api.NUnitTestAssemblyRunner.OnRunCompleted(), and NUnit.Framework.Api.NUnitTestAssemblyRunner.WaitForCompletion().
_savedOut
TextWriter NUnit.Framework.Api.NUnitTestAssemblyRunner._savedOut private
Referenced by NUnit.Framework.Api.NUnitTestAssemblyRunner.OnRunCompleted(), and NUnit.Framework.Api.NUnitTestAssemblyRunner.StartRun().
_savedErr
TextWriter NUnit.Framework.Api.NUnitTestAssemblyRunner._savedErr private
Referenced by NUnit.Framework.Api.NUnitTestAssemblyRunner.OnRunCompleted(), and NUnit.Framework.Api.NUnitTestAssemblyRunner.StartRun().
Property Documentation
LoadedTest
ITest NUnit.Framework.Api.NUnitTestAssemblyRunner.LoadedTest get private set
The tree of tests that was loaded by the builder
Referenced by NUnit.Framework.Api.NUnitTestAssemblyRunner.CountTestCases(), NUnit.Framework.Api.NUnitTestAssemblyRunner.CreateTestExecutionContext(), NUnit.Framework.Api.NUnitTestAssemblyRunner.Load(), and NUnit.Framework.Api.NUnitTestAssemblyRunner.RunAsync().
Result
ITestResult? NUnit.Framework.Api.NUnitTestAssemblyRunner.Result get
The test result, if a run has completed
Referenced by NUnit.Framework.Api.NUnitTestAssemblyRunner.Run().
IsTestLoaded
bool NUnit.Framework.Api.NUnitTestAssemblyRunner.IsTestLoaded get
Indicates whether a test is loaded
IsTestRunning
bool NUnit.Framework.Api.NUnitTestAssemblyRunner.IsTestRunning get
Indicates whether a test is running
Referenced by NUnit.Framework.Api.NUnitTestAssemblyRunner.StopRun().
IsTestComplete
bool NUnit.Framework.Api.NUnitTestAssemblyRunner.IsTestComplete get
Indicates whether a test run is complete
Settings
IDictionary NUnit.Framework.Api.NUnitTestAssemblyRunner.Settings get set private
Our settings, specified when loading the assembly
Referenced by NUnit.Framework.Api.NUnitTestAssemblyRunner.CreateTestExecutionContext(), NUnit.Framework.Api.NUnitTestAssemblyRunner.Load(), and NUnit.Framework.Api.NUnitTestAssemblyRunner.StartRun().
TopLevelWorkItem
WorkItem NUnit.Framework.Api.NUnitTestAssemblyRunner.TopLevelWorkItem get set private
The top level WorkItem created for the assembly as a whole
Referenced by NUnit.Framework.Api.NUnitTestAssemblyRunner.RunAsync(), and NUnit.Framework.Api.NUnitTestAssemblyRunner.StartRun().
Context
TestExecutionContext NUnit.Framework.Api.NUnitTestAssemblyRunner.Context get set private
The TestExecutionContext for the top level WorkItem
Referenced by NUnit.Framework.Api.NUnitTestAssemblyRunner.CreateTestExecutionContext(), NUnit.Framework.Api.NUnitTestAssemblyRunner.RunAsync(), NUnit.Framework.Api.NUnitTestAssemblyRunner.StartRun(), and NUnit.Framework.Api.NUnitTestAssemblyRunner.StopRun().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Api/NUnitTestAssemblyRunner.cs