Doc: IGLib EXTENDED: NUnit.Framework.Internal.UnexpectedExceptionTests Class Reference
NUnit.Framework.Internal.UnexpectedExceptionTests Class Reference
Public Member Functions
void FailRecordsInnerException ()
void FailRecordsNestedInnerException ()
void BadStackTraceIsHandled ()
void CustomExceptionIsHandled ()
Member Function Documentation
FailRecordsInnerException()
void NUnit.Framework.Internal.UnexpectedExceptionTests.FailRecordsInnerException () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.Error, NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, and NUnit.TestUtilities.TestBuilder.RunTestCase().
FailRecordsNestedInnerException()
void NUnit.Framework.Internal.UnexpectedExceptionTests.FailRecordsNestedInnerException () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.Error, NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, and NUnit.TestUtilities.TestBuilder.RunTestCase().
BadStackTraceIsHandled()
void NUnit.Framework.Internal.UnexpectedExceptionTests.BadStackTraceIsHandled () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.Error, NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTestCase(), and NUnit.Framework.Interfaces.ITestResult.StackTrace.
CustomExceptionIsHandled()
void NUnit.Framework.Internal.UnexpectedExceptionTests.CustomExceptionIsHandled () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.Error, NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, and NUnit.TestUtilities.TestBuilder.RunTestCase().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/UnexpectedExceptionTests.cs