Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLASV2 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLASV2 Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLASV2 (DLAMCH dlamch)
DLASV2 ()
void Run (double F, double G, double H, ref double SSMIN, ref double SSMAX, ref double SNR, ref double CSR, ref double SNL, ref double CSL)
Private Attributes
DLAMCH _dlamch
Static Private Attributes
const double ZERO = 0.0E0
const double HALF = 0.5E0
const double ONE = 1.0E0
const double TWO = 2.0E0
const double FOUR = 4.0E0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLASV2 computes the singular value decomposition of a 2-by-2 triangular matrix [ F G ] [ 0 H ]. On return, abs(SSMAX) is the larger singular value, abs(SSMIN) is the smaller singular value, and (CSL,SNL) and (CSR,SNR) are the left and right singular vectors for abs(SSMAX), giving the decomposition
[ CSL SNL ] [ F G ] [ CSR -SNR ] = [ SSMAX 0 ] [-SNL CSL ] [ 0 H ] [ SNR CSR ] [ 0 SSMIN ].
/summary>
Constructor & Destructor Documentation
DLASV2() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLASV2.DLASV2 (DLAMCH dlamch) inline
DLASV2() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLASV2.DLASV2 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLASV2.Run (double F, double G, double H, ref double SSMIN, ref double SSMAX, ref double SNR, ref double CSR, ref double SNL, ref double CSL) inline
Purpose
DLASV2 computes the singular value decomposition of a 2-by-2 triangular matrix [ F G ] [ 0 H ]. On return, abs(SSMAX) is the larger singular value, abs(SSMIN) is the smaller singular value, and (CSL,SNL) and (CSR,SNR) are the left and right singular vectors for abs(SSMAX), giving the decomposition
[ CSL SNL ] [ F G ] [ CSR -SNR ] = [ SSMAX 0 ] [-SNL CSL ] [ 0 H ] [ SNR CSR ] [ 0 SSMIN ].
/summary>
Parameters
F (input) DOUBLE PRECISION The (1,1) element of the 2-by-2 matrix. /param>
Parameters
G (input) DOUBLE PRECISION The (1,2) element of the 2-by-2 matrix. /param>
Parameters
H (input) DOUBLE PRECISION The (2,2) element of the 2-by-2 matrix. /param>
Parameters
SSMIN (output) DOUBLE PRECISION abs(SSMIN) is the smaller singular value. /param>
Parameters
SSMAX (output) DOUBLE PRECISION abs(SSMAX) is the larger singular value. /param>
Parameters
SNR (output) DOUBLE PRECISION /param>
Parameters
CSR (output) DOUBLE PRECISION The vector (CSR, SNR) is a unit right singular vector for the singular value abs(SSMAX). /param>
Parameters
SNL (output) DOUBLE PRECISION /param>
Parameters
CSL (output) DOUBLE PRECISION The vector (CSL, SNL) is a unit left singular vector for the singular value abs(SSMAX). /param>
References DotNumerics.LinearAlgebra.CSLapack.DLASV2.FOUR, DotNumerics.LinearAlgebra.CSLapack.DLASV2.HALF, DotNumerics.LinearAlgebra.CSLapack.DLASV2.ONE, DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.FortranLibrary.FortranLib.Sign(), DotNumerics.LinearAlgebra.CSLapack.DLASV2.TWO, and DotNumerics.LinearAlgebra.CSLapack.DLASV2.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAGS2.Run(), and DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run().
Member Data Documentation
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLASV2._dlamch private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLASV2.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASV2.Run().
HALF
const double DotNumerics.LinearAlgebra.CSLapack.DLASV2.HALF = 0.5E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASV2.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLASV2.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASV2.Run().
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DLASV2.TWO = 2.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASV2.Run().
FOUR
const double DotNumerics.LinearAlgebra.CSLapack.DLASV2.FOUR = 4.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASV2.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlasv2.cs