Doc: IGLib EXTENDED: IG.Forms.CompilerFormOld Class Reference
IG.Forms.CompilerFormOld Class Reference
Public Member Functions
CompilerFormOld ()
Initializes form components and internal variables.
Public Attributes
ReporterConsoleMsgbox Reporter = new ReporterConsoleMsgbox()
Protected Member Functions
void ReportError (string message, Exception ex)
Launches error report.
void CheckReadyToRun ()
Checks whether the compiled code is ready to run, and enables the Run button accordingly.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
RuntimeCompilerOld Compiler = new RuntimeCompilerOld()
Properties
Logger Logger [get]
Gets compiler's logger.
Private Member Functions
void btnQuit_Click (object sender, System.EventArgs e)
void btnLoad_Click (object sender, System.EventArgs e)
Loads code template into the rich textbox.
void btnCompile_Click (object sender, System.EventArgs e)
Compilation of code.
void btnExecute_Click (object sender, System.EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Logger _logger = null
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.RichTextBox rtfCode
System.Windows.Forms.Button btnLoad
System.Windows.Forms.Button btnCompile
System.Windows.Forms.Button btnExecute
System.Windows.Forms.Button btnQuit
Constructor & Destructor Documentation
CompilerFormOld()
IG.Forms.CompilerFormOld.CompilerFormOld () inline
Initializes form components and internal variables.
References IG.Forms.CompilerFormOld.InitializeComponent(), and IG.Forms.CompilerFormOld.Reporter.
Member Function Documentation
btnQuit_Click()
void IG.Forms.CompilerFormOld.btnQuit_Click (object sender, System.EventArgs e) inline private
Referenced by IG.Forms.CompilerFormOld.InitializeComponent().
btnLoad_Click()
void IG.Forms.CompilerFormOld.btnLoad_Click (object sender, System.EventArgs e) inline private
Loads code template into the rich textbox.
References IG.Lib.RuntimeCompilerOld.CodeBase, and IG.Forms.CompilerFormOld.rtfCode.
Referenced by IG.Forms.CompilerFormOld.InitializeComponent().
ReportError()
void IG.Forms.CompilerFormOld.ReportError (string message, Exception ex) inline protected
Launches error report.
Parameters
message Custom part of the message shown in report.
ex Exception that was thrown.
Referenced by IG.Forms.CompilerFormOld.btnCompile_Click().
CheckReadyToRun()
void IG.Forms.CompilerFormOld.CheckReadyToRun () inline protected
Checks whether the compiled code is ready to run, and enables the Run button accordingly.
References IG.Forms.CompilerFormOld.btnExecute, IG.Forms.CompilerFormOld.Compiler, and IG.Lib.RuntimeCompilerOld.ReadyToRun.
Referenced by IG.Forms.CompilerFormOld.btnCompile_Click().
btnCompile_Click()
void IG.Forms.CompilerFormOld.btnCompile_Click (object sender, System.EventArgs e) inline private
Compilation of code.
References IG.Forms.CompilerFormOld.CheckReadyToRun(), IG.Lib.Logger.Clear(), IG.Lib.RuntimeCompilerOld.Code, IG.Lib.RuntimeCompilerOld.Compile(), IG.Forms.CompilerFormOld.Compiler, IG.Lib.Logger.GetErrorsReport(), IG.Lib.Logger.GetReport(), IG.Lib.Logger.GetWarningsReport(), IG.Lib.Logger.HasErrors(), IG.Lib.Logger.HasWarnings(), IG.Lib.RuntimeCompilerOld.ReadyToRun, IG.Lib.Logger.Report(), IG.Forms.CompilerFormOld.Reporter, IG.Forms.CompilerFormOld.ReportError(), and IG.Forms.CompilerFormOld.rtfCode.
Referenced by IG.Forms.CompilerFormOld.InitializeComponent().
btnExecute_Click()
void IG.Forms.CompilerFormOld.btnExecute_Click (object sender, System.EventArgs e) inline private
References IG.Forms.CompilerFormOld.Compiler, IG.Lib.RuntimeCompilerOld.LibraryPath, IG.Lib.RuntimeCompilerOld.LoadFile(), IG.Lib.IRunnableOld.Run(), and IG.Lib.RuntimeCompilerOld.RunnableFullClass.
Referenced by IG.Forms.CompilerFormOld.InitializeComponent().
Dispose()
override void IG.Forms.CompilerFormOld.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.CompilerFormOld.components.
InitializeComponent()
void IG.Forms.CompilerFormOld.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.CompilerFormOld.btnCompile, IG.Forms.CompilerFormOld.btnCompile_Click(), IG.Forms.CompilerFormOld.btnExecute, IG.Forms.CompilerFormOld.btnExecute_Click(), IG.Forms.CompilerFormOld.btnLoad, IG.Forms.CompilerFormOld.btnLoad_Click(), IG.Forms.CompilerFormOld.btnQuit, IG.Forms.CompilerFormOld.btnQuit_Click(), and IG.Forms.CompilerFormOld.rtfCode.
Referenced by IG.Forms.CompilerFormOld.CompilerFormOld().
Member Data Documentation
Compiler
RuntimeCompilerOld IG.Forms.CompilerFormOld.Compiler = new RuntimeCompilerOld() protected
Referenced by IG.Forms.CompilerFormOld.btnCompile_Click(), IG.Forms.CompilerFormOld.btnExecute_Click(), and IG.Forms.CompilerFormOld.CheckReadyToRun().
Reporter
ReporterConsoleMsgbox IG.Forms.CompilerFormOld.Reporter = new ReporterConsoleMsgbox()
Referenced by IG.Forms.CompilerFormOld.btnCompile_Click(), IG.Forms.CompilerFormOld.CompilerFormOld(), and IG.Test.RuntimeCompilerMain.Main().
_logger
Logger IG.Forms.CompilerFormOld._logger = null private
components
System.ComponentModel.IContainer IG.Forms.CompilerFormOld.components = null private
Required designer variable.
Referenced by IG.Forms.CompilerFormOld.Dispose().
rtfCode
System.Windows.Forms.RichTextBox IG.Forms.CompilerFormOld.rtfCode private
Referenced by IG.Forms.CompilerFormOld.btnCompile_Click(), IG.Forms.CompilerFormOld.btnLoad_Click(), and IG.Forms.CompilerFormOld.InitializeComponent().
btnLoad
System.Windows.Forms.Button IG.Forms.CompilerFormOld.btnLoad private
Referenced by IG.Forms.CompilerFormOld.InitializeComponent().
btnCompile
System.Windows.Forms.Button IG.Forms.CompilerFormOld.btnCompile private
Referenced by IG.Forms.CompilerFormOld.InitializeComponent().
btnExecute
System.Windows.Forms.Button IG.Forms.CompilerFormOld.btnExecute private
Referenced by IG.Forms.CompilerFormOld.CheckReadyToRun(), and IG.Forms.CompilerFormOld.InitializeComponent().
btnQuit
System.Windows.Forms.Button IG.Forms.CompilerFormOld.btnQuit private
Referenced by IG.Forms.CompilerFormOld.InitializeComponent().
Property Documentation
Logger
Logger IG.Forms.CompilerFormOld.Logger get protected
Gets compiler's logger.
The documentation for this class was generated from the following files:
igtest/test_iglib_tmp_CSharpScripter/old_csharpscripter/OldCompilerForm.cs
igtest/test_iglib_tmp_CSharpScripter/old_csharpscripter/OldCompilerForm.Designer.cs