Doc: IGLib EXTENDED: Test.MultiExtremumTest Class Reference
Test.MultiExtremumTest Class Reference
Public Member Functions
void Quadratic ()
void PerturbedQuadratic ()
void Vardim ()
void GoldsteinPrice ()
void Beale ()
void StylblinskiTang ()
void ThreeHumpCamel ()
void McCormick ()
void Rosenbrock ()
void SmoothedEasom ()
void Perm ()
void SumOfPowers ()
void Ackley ()
void Schwefel ()
void Griewank ()
void Bukin ()
void Easom ()
void PackCirclesInSquare ()
void PackCirclesInCircle ()
void PackSpheresInCube ()
void ThompsonProblem ()
void LocalThomson ()
Member Function Documentation
Quadratic()
void Test.MultiExtremumTest.Quadratic () inline
References Meta.Numerics.Analysis.MultiFunctionMath.FindMinimum(), Meta.Numerics.Analysis.FunctionMath.FindMinimum(), and Meta.Numerics.MoreMath.Sqr().
PerturbedQuadratic()
void Test.MultiExtremumTest.PerturbedQuadratic () inline
References Meta.Numerics.Analysis.MultiFunctionMath.FindMinimum(), Meta.Numerics.MoreMath.Pow(), and Meta.Numerics.MoreMath.Sqr().
Vardim()
void Test.MultiExtremumTest.Vardim () inline
References Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Matrices.AnyMatrix< T >.Fill(), Meta.Numerics.Analysis.MultiFunctionMath.FindMinimum(), Meta.Numerics.Analysis.MultiExtremum.Location, Meta.Numerics.MoreMath.Sqr(), and Meta.Numerics.Analysis.MultiExtremum.Value.
GoldsteinPrice()
void Test.MultiExtremumTest.GoldsteinPrice () inline
References Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Analysis.MultiFunctionMath.FindGlobalMinimum(), Meta.Numerics.Analysis.MultiFunctionMath.FindMinimum(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.MultiExtremum.Location, Meta.Numerics.MoreMath.Pow(), and Meta.Numerics.Analysis.MultiExtremum.Value.
Beale()
void Test.MultiExtremumTest.Beale () inline
References Meta.Numerics.Analysis.MultiExtremum.Dimension, Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Analysis.MultiFunctionMath.FindMinimum(), Meta.Numerics.Analysis.MultiExtremum.Location, Meta.Numerics.MoreMath.Sqr(), and Meta.Numerics.Analysis.MultiExtremum.Value.
StylblinskiTang()
void Test.MultiExtremumTest.StylblinskiTang () inline
References Meta.Numerics.Analysis.MultiExtremum.Dimension, Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Analysis.MultiFunctionMath.FindMinimum(), Meta.Numerics.Analysis.MultiExtremum.Location, Meta.Numerics.MoreMath.Sqr(), and Meta.Numerics.Analysis.MultiExtremum.Value.
ThreeHumpCamel()
void Test.MultiExtremumTest.ThreeHumpCamel () inline
References Meta.Numerics.Analysis.MultiFunctionMath.FindMinimum(), Meta.Numerics.Analysis.MultiExtremum.Location, Meta.Numerics.MoreMath.Pow(), and Meta.Numerics.Analysis.MultiExtremum.Value.
McCormick()
void Test.MultiExtremumTest.McCormick () inline
References Meta.Numerics.MoreMath.Sqr().
Rosenbrock()
void Test.MultiExtremumTest.Rosenbrock () inline
References Meta.Numerics.Matrices.VectorBase.Dimension, Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Analysis.MultiFunctionMath.FindMinimum(), Meta.Numerics.Analysis.MultiExtremum.Location, Meta.Numerics.MoreMath.Pow(), and Meta.Numerics.Analysis.MultiExtremum.Value.
SmoothedEasom()
void Test.MultiExtremumTest.SmoothedEasom () inline
References Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Analysis.MultiFunctionMath.FindMinimum(), Meta.Numerics.Analysis.MultiExtremum.Location, Meta.Numerics.MoreMath.Sqr(), and Meta.Numerics.Analysis.MultiExtremum.Value.
Perm()
void Test.MultiExtremumTest.Perm () inline
References Meta.Numerics.Analysis.MultiExtremum.Dimension, Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Analysis.MultiFunctionMath.FindMinimum(), Meta.Numerics.Analysis.MultiExtremum.Location, Meta.Numerics.MoreMath.Pow(), Meta.Numerics.MoreMath.Sqr(), and Meta.Numerics.Analysis.MultiExtremum.Value.
SumOfPowers()
void Test.MultiExtremumTest.SumOfPowers () inline
References Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Analysis.MultiFunctionMath.FindMinimum(), Meta.Numerics.MoreMath.Pow(), and Meta.Numerics.Analysis.MultiExtremum.Value.
Ackley()
void Test.MultiExtremumTest.Ackley () inline
References Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Analysis.MultiFunctionMath.FindGlobalMinimum(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Functions.AdvancedMath.GoldenRatio, and Meta.Numerics.Analysis.MultiExtremum.Value.
Schwefel()
void Test.MultiExtremumTest.Schwefel () inline
References Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Analysis.MultiFunctionMath.FindGlobalMinimum(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Functions.AdvancedMath.GoldenRatio, Meta.Numerics.Analysis.EvaluationSettings.RelativePrecision, and Meta.Numerics.Analysis.MultiExtremum.Value.
Griewank()
void Test.MultiExtremumTest.Griewank () inline
References Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Analysis.MultiFunctionMath.FindGlobalMinimum(), Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Analysis.MultiExtremum.Value.
Bukin()
void Test.MultiExtremumTest.Bukin () inline
References Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Analysis.MultiFunctionMath.FindGlobalMinimum(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.MultiExtremum.Location, Meta.Numerics.Analysis.EvaluationSettings.Update, and Meta.Numerics.Analysis.MultiExtremum.Value.
Easom()
void Test.MultiExtremumTest.Easom () inline
References Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Analysis.MultiFunctionMath.FindGlobalMinimum(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.MoreMath.Sqr(), and Meta.Numerics.Analysis.MultiExtremum.Value.
PackCirclesInSquare()
void Test.MultiExtremumTest.PackCirclesInSquare () inline
References Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Analysis.MultiFunctionMath.FindGlobalMaximum(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.MoreMath.Hypot(), and Meta.Numerics.Analysis.MultiExtremum.Value.
PackCirclesInCircle()
void Test.MultiExtremumTest.PackCirclesInCircle () inline
References Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Analysis.MultiFunctionMath.FindGlobalMaximum(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.MoreMath.Hypot(), Meta.Numerics.Analysis.MultiExtremum.Location, and Meta.Numerics.Analysis.MultiExtremum.Value.
PackSpheresInCube()
void Test.MultiExtremumTest.PackSpheresInCube () inline
References Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Analysis.MultiFunctionMath.FindGlobalMinimum(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.MoreMath.Sqr(), and Meta.Numerics.Analysis.MultiExtremum.Value.
ThompsonProblem()
void Test.MultiExtremumTest.ThompsonProblem () inline
References Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Analysis.MultiFunctionMath.FindGlobalMinimum(), Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.MultiExtremum.Location, and Meta.Numerics.Analysis.MultiExtremum.Value.
LocalThomson()
void Test.MultiExtremumTest.LocalThomson () inline
References Meta.Numerics.Analysis.EvaluationResult.EvaluationCount, Meta.Numerics.Analysis.MultiFunctionMath.FindMinimum(), and Meta.Numerics.Analysis.MultiExtremum.Value.
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/MultiExtremumTest.cs