Doc: IGLib EXTENDED: NUnit.Engine.ITestEngineRunner Interface Reference
NUnit.Engine.ITestEngineRunner Interface Reference
Interface implemented by all internal test runners in the engine, allowing them to pass back TestEngineResults to any higher-level runner that calls them.
Public Member Functions
TestEngineResult Load ()
Load a TestPackage for possible execution
void Unload ()
Unload any loaded TestPackage. If none is loaded, the call is ignored.
TestEngineResult Reload ()
Reload the loaded test package.
int CountTestCases (TestFilter filter)
Count the test cases that would be run under the specified filter.
TestEngineResult Run (ITestEventListener listener, TestFilter filter)
Run the tests in the loaded TestPackage and return a test result. The tests are run synchronously and the listener interface is notified as it progresses.
AsyncTestEngineResult RunAsync (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the loaded TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses.
void StartRun (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the loaded TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses.
void StopRun (bool force)
Cancel the current test run. If no test is running, the call is ignored.
TestEngineResult Explore (TestFilter filter)
Explore a loaded TestPackage and return information about the tests found.
Detailed Description
Interface implemented by all internal test runners in the engine, allowing them to pass back TestEngineResults to any higher-level runner that calls them.
Member Function Documentation
Load()
TestEngineResult NUnit.Engine.ITestEngineRunner.Load ()
Load a TestPackage for possible execution
Returns
A TestEngineResult.
Implemented in NUnit.Engine.Runners.AbstractTestRunner, NUnit.Engine.Runners.MasterTestRunner, and NUnit.Engine.Agents.RemoteTestAgent.
Referenced by NUnit.Engine.Agents.RemoteTestAgent.Load(), NUnit.Engine.Runners.MasterTestRunner.LoadPackage(), and NUnit.Engine.Runners.ProcessRunner.LoadPackage().
Unload()
void NUnit.Engine.ITestEngineRunner.Unload ()
Unload any loaded TestPackage. If none is loaded, the call is ignored.
Implemented in NUnit.Engine.Runners.AbstractTestRunner, and NUnit.Engine.Agents.RemoteTestAgent.
Referenced by NUnit.Engine.Agents.RemoteTestAgent.Unload(), NUnit.Engine.Runners.MasterTestRunner.UnloadPackage(), NUnit.Engine.Runners.AggregatingTestRunner.UnloadPackage(), and NUnit.Engine.Runners.ProcessRunner.UnloadPackage().
Reload()
TestEngineResult NUnit.Engine.ITestEngineRunner.Reload ()
Reload the loaded test package.
Returns
A TestEngineResult.
Exceptions
InvalidOperationException If no package is loaded.
Implemented in NUnit.Engine.Runners.AbstractTestRunner, NUnit.Engine.Runners.MasterTestRunner, and NUnit.Engine.Agents.RemoteTestAgent.
Referenced by NUnit.Engine.Agents.RemoteTestAgent.Reload().
CountTestCases()
int NUnit.Engine.ITestEngineRunner.CountTestCases (TestFilter filter)
Count the test cases that would be run under the specified filter.
Parameters
filter A TestFilter
Returns
The count of test cases
Implemented in NUnit.Engine.Runners.AbstractTestRunner, and NUnit.Engine.Agents.RemoteTestAgent.
Referenced by NUnit.Engine.Agents.RemoteTestAgent.CountTestCases(), NUnit.Engine.Runners.MasterTestRunner.CountTests(), NUnit.Engine.Runners.AggregatingTestRunner.CountTests(), and NUnit.Engine.Runners.ProcessRunner.CountTests().
Run()
TestEngineResult NUnit.Engine.ITestEngineRunner.Run (ITestEventListener listener, TestFilter filter)
Run the tests in the loaded TestPackage and return a test result. The tests are run synchronously and the listener interface is notified as it progresses.
Parameters
listener An ITestEventHandler to receive events
filter A TestFilter used to select tests
Returns
A TestEngineResult giving the result of the test execution
Implemented in NUnit.Engine.Runners.AbstractTestRunner, NUnit.Engine.Runners.MasterTestRunner, and NUnit.Engine.Agents.RemoteTestAgent.
Referenced by NUnit.Engine.Runners.TestExecutionTask.Execute(), NUnit.Engine.Agents.RemoteTestAgent.Run(), NUnit.Engine.Runners.MasterTestRunner.RunTests(), NUnit.Engine.Runners.AggregatingTestRunner.RunTests(), and NUnit.Engine.Runners.ProcessRunner.RunTests().
RunAsync()
AsyncTestEngineResult NUnit.Engine.ITestEngineRunner.RunAsync (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the loaded TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses.
Parameters
listener An ITestEventHandler to receive events
filter A TestFilter used to select tests
Returns
An AsyncTestEngineResult that will provide the result of the test execution
Implemented in NUnit.Engine.Runners.AbstractTestRunner, NUnit.Engine.Runners.MasterTestRunner, and NUnit.Engine.Agents.RemoteTestAgent.
Referenced by NUnit.Engine.Agents.RemoteTestAgent.RunAsync(), and NUnit.Engine.Runners.ProcessRunner.RunTestsAsync().
StartRun()
void NUnit.Engine.ITestEngineRunner.StartRun (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the loaded TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses.
Parameters
listener An ITestEventHandler to receive events
filter A TestFilter used to select tests
Implemented in NUnit.Engine.Runners.AbstractTestRunner, and NUnit.Engine.Agents.RemoteTestAgent.
StopRun()
void NUnit.Engine.ITestEngineRunner.StopRun (bool force)
Cancel the current test run. If no test is running, the call is ignored.
Parameters
force If true, force a stop by cancelling threads if necessary.
Implemented in NUnit.Engine.Agents.RemoteTestAgent, NUnit.Engine.Runners.ProcessRunner, NUnit.Engine.Runners.AggregatingTestRunner, NUnit.Engine.Runners.AbstractTestRunner, NUnit.Engine.Runners.DirectTestRunner, and NUnit.Engine.Runners.MasterTestRunner.
Referenced by NUnit.Engine.Runners.MasterTestRunner.StopRun(), NUnit.Engine.Runners.ProcessRunner.StopRun(), and NUnit.Engine.Agents.RemoteTestAgent.StopRun().
Explore()
TestEngineResult NUnit.Engine.ITestEngineRunner.Explore (TestFilter filter)
Explore a loaded TestPackage and return information about the tests found.
Parameters
filter Criteria used to filter the search results
Returns
A TestEngineResult.
Implemented in NUnit.Engine.Runners.MasterTestRunner, NUnit.Engine.Runners.AbstractTestRunner, and NUnit.Engine.Agents.RemoteTestAgent.
Referenced by NUnit.Engine.Agents.RemoteTestAgent.Explore(), NUnit.Engine.Runners.AggregatingTestRunner.ExploreTests(), NUnit.Engine.Runners.MasterTestRunner.ExploreTests(), and NUnit.Engine.Runners.ProcessRunner.ExploreTests().
The documentation for this interface was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/ITestEngineRunner.cs