Doc: IGLib EXTENDED: AForge.Genetic.IChromosome Interface Reference
AForge.Genetic.IChromosome Interface Reference
Chromosome interface.
Public Member Functions
void Generate ()
Generate random chromosome value.
IChromosome CreateNew ()
Create new random chromosome with same parameters (factory method).
IChromosome Clone ()
Clone the chromosome.
void Mutate ()
Mutation operator.
void Crossover (IChromosome pair)
Crossover operator.
void Evaluate (IFitnessFunction function)
Evaluate chromosome with specified fitness function.
Properties
double Fitness [get]
Chromosome's fintess value.
Detailed Description
Chromosome interface.
The interfase should be implemented by all classes, which implement particular chromosome type.
Member Function Documentation
Generate()
void AForge.Genetic.IChromosome.Generate ()
Generate random chromosome value.
Regenerates chromosome's value using random number generator.
Implemented in AForge.Genetic.DoubleArrayChromosome, AForge.Genetic.ShortArrayChromosome, AForge.Genetic.GEPChromosome, AForge.Genetic.BinaryChromosome, AForge.Genetic.GPTreeChromosome, AForge.Genetic.PermutationChromosome, and AForge.Genetic.ChromosomeBase.
CreateNew()
IChromosome AForge.Genetic.IChromosome.CreateNew ()
Create new random chromosome with same parameters (factory method).
The method creates new chromosome of the same type, but randomly initialized. The method is useful as factory method for those classes, which work with chromosome's interface, but not with particular chromosome class.
Implemented in AForge.Genetic.DoubleArrayChromosome, AForge.Genetic.GEPChromosome, AForge.Genetic.GPTreeChromosome, AForge.Genetic.ShortArrayChromosome, AForge.Genetic.BinaryChromosome, AForge.Genetic.PermutationChromosome, AForge.Genetic.ChromosomeBase, and TSP.TSPChromosome.
Referenced by AForge.Genetic.Population.Population(), AForge.Genetic.Population.Regenerate(), and AForge.Genetic.Population.Selection().
Clone()
IChromosome AForge.Genetic.IChromosome.Clone ()
Clone the chromosome.
The method clones the chromosome returning the exact copy of it.
Implemented in AForge.Genetic.DoubleArrayChromosome, AForge.Genetic.GEPChromosome, AForge.Genetic.GPTreeChromosome, AForge.Genetic.ShortArrayChromosome, AForge.Genetic.BinaryChromosome, AForge.Genetic.PermutationChromosome, AForge.Genetic.ChromosomeBase, and TSP.TSPChromosome.
Referenced by AForge.Genetic.Population.Population().
Mutate()
void AForge.Genetic.IChromosome.Mutate ()
Mutation operator.
The method performs chromosome's mutation, changing its part randomly.
Implemented in AForge.Genetic.DoubleArrayChromosome, AForge.Genetic.GEPChromosome, AForge.Genetic.GPTreeChromosome, AForge.Genetic.ShortArrayChromosome, AForge.Genetic.BinaryChromosome, AForge.Genetic.PermutationChromosome, and AForge.Genetic.ChromosomeBase.
Crossover()
void AForge.Genetic.IChromosome.Crossover (IChromosome pair)
Crossover operator.
Parameters
pair Pair chromosome to crossover with.
The method performs crossover between two chromosomes – interchanging some parts of chromosomes.
Implemented in AForge.Genetic.GEPChromosome, AForge.Genetic.DoubleArrayChromosome, AForge.Genetic.GPTreeChromosome, AForge.Genetic.ShortArrayChromosome, AForge.Genetic.BinaryChromosome, AForge.Genetic.PermutationChromosome, AForge.Genetic.ChromosomeBase, and TSP.TSPChromosome.
Referenced by AForge.Genetic.Population.Crossover().
Evaluate()
void AForge.Genetic.IChromosome.Evaluate (IFitnessFunction function)
Evaluate chromosome with specified fitness function.
Parameters
function Fitness function to use for evaluation of the chromosome.
Calculates chromosome's fitness using the specifed fitness function.
Implemented in AForge.Genetic.ChromosomeBase.
Referenced by AForge.Genetic.Population.AddChromosome(), AForge.Genetic.Population.Crossover(), and AForge.Genetic.Population.Population().
Property Documentation
Fitness
double AForge.Genetic.IChromosome.Fitness get
Chromosome's fintess value.
The fitness value represents chromosome's usefulness - the greater the value, the more useful it.
Referenced by AForge.Genetic.Population.FindBestChromosome().
The documentation for this interface was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Genetic/Chromosomes/IChromosome.cs