Doc: IGLib EXTENDED: NUnit.Framework.Constraints.CollectionTally Class Reference
NUnit.Framework.Constraints.CollectionTally Class Reference
CollectionTally counts (tallies) the number of occurrences of each object in one or more enumerations.
Public Member Functions
CollectionTally (NUnitEqualityComparer comparer, IEnumerable c)
Construct a CollectionTally object from a comparer and a collection
bool TryRemove (object o)
Try to remove an object from the tally
bool TryRemove (IEnumerable c)
Try to remove a set of objects from the tally
Properties
int Count [get]
The number of objects remaining in the tally
Private Member Functions
bool ItemsEqual (object expected, object actual)
Private Attributes
readonly List< object > list = new List<object>()
readonly NUnitEqualityComparer comparer
Detailed Description
CollectionTally counts (tallies) the number of occurrences of each object in one or more enumerations.
Constructor & Destructor Documentation
CollectionTally()
NUnit.Framework.Constraints.CollectionTally.CollectionTally (NUnitEqualityComparer comparer, IEnumerable c) inline
Construct a CollectionTally object from a comparer and a collection
References NUnit.Framework.Constraints.CollectionTally.comparer, and NUnit.Framework.Constraints.CollectionTally.list.
Member Function Documentation
ItemsEqual()
bool NUnit.Framework.Constraints.CollectionTally.ItemsEqual (object expected, object actual) inline private
References NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(), NUnit.Framework.Constraints.CollectionTally.comparer, and NUnit.Framework.Constraints.Tolerance.Default.
Referenced by NUnit.Framework.Constraints.CollectionTally.TryRemove().
TryRemove() [1/2]
bool NUnit.Framework.Constraints.CollectionTally.TryRemove (object o) inline
Try to remove an object from the tally
Parameters
o The object to remove
Returns
True if successful, false if the object was not found
References NUnit.Framework.Constraints.CollectionTally.ItemsEqual(), and NUnit.Framework.Constraints.CollectionTally.list.
Referenced by NUnit.Framework.Constraints.NUnitEqualityComparer.DictionariesEqual(), NUnit.Framework.Constraints.CollectionSubsetConstraint.Matches(), NUnit.Framework.Constraints.CollectionEquivalentConstraint.Matches(), NUnit.Framework.Constraints.CollectionSupersetConstraint.Matches(), and NUnit.Framework.Constraints.CollectionTally.TryRemove().
TryRemove() [2/2]
bool NUnit.Framework.Constraints.CollectionTally.TryRemove (IEnumerable c) inline
Try to remove a set of objects from the tally
Parameters
c The objects to remove
Returns
True if successful, false if any object was not found
References NUnit.Framework.Constraints.CollectionTally.TryRemove().
Member Data Documentation
list
readonly List<object> NUnit.Framework.Constraints.CollectionTally.list = new List<object>() private
Referenced by NUnit.Framework.Constraints.CollectionTally.CollectionTally(), and NUnit.Framework.Constraints.CollectionTally.TryRemove().
comparer
readonly NUnitEqualityComparer NUnit.Framework.Constraints.CollectionTally.comparer private
Referenced by NUnit.Framework.Constraints.CollectionTally.CollectionTally(), and NUnit.Framework.Constraints.CollectionTally.ItemsEqual().
Property Documentation
Count
int NUnit.Framework.Constraints.CollectionTally.Count get
The number of objects remaining in the tally
Referenced by NUnit.Framework.Constraints.NUnitEqualityComparer.DictionariesEqual(), and NUnit.Framework.Constraints.CollectionEquivalentConstraint.Matches().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Constraints/CollectionTally.cs