Doc: IGLib EXTENDED: Meta.Numerics.SignalProcessing.FourierTransformer Class Reference
Meta.Numerics.SignalProcessing.FourierTransformer Class Reference
An engine for performing Fourier transforms on complex series.
Public Member Functions
FourierTransformer (int size)
Initializes a new instance of the Fourier transformer.
FourierTransformer (int size, FourierSign signConvention, FourierNormalization normalizationConvention)
Initializes a new instance of the Fourier transformer with the given sign and normalization conventions.
Complex[] Transform (IList< Complex > values)
Computes the Fourier transform of the given series.
Complex[] InverseTransform (IList< Complex > values)
Computes the inverse Fourier transform of the given series.
Properties
int Length [get]
The series length for which the transformer is specialized.
FourierNormalization NormalizationConvention [get]
Gets the normalization convention used by the transformer.
FourierSign SignConvention [get]
Gets the normalization convention used by the transformer.
Private Member Functions
int GetSign ()
Static Private Member Functions
static void Normalize (Complex[] x, double f)
Private Attributes
int size
List< Factor > factors
List< Transformlet > plan
FourierNormalization normalizationConvention
FourierSign signConvention
Complex[] roots
Detailed Description
An engine for performing Fourier transforms on complex series.
A Fourier transform decomposes a function into a sum of different frequency components. This is useful for a wide array of applications.
Mathematically, the DFT is an N-dimensional linear transfromation with coefficients that are the Nth complex roots of unity.
An instance of the FourierTransformer class performs DFTs on series of a particular length, given by its FourierTransformer.Length property. This specialization allows certain parts of the DFT calculation, which are indepdent of the transformed series but dependent on the length of the series, to be performed only once and then re-used for all transforms of that length. This saves time and improves performance. If you need to perform DFTs on series with different lengths, simply create a seperate instance of the FourierTransform class for each required length.
Many simple DFT implementations require that the series length be a power of two (2, 4, 8, 16, etc.). Meta.Numerics supports DFTs of any length. Our DFT implementation is fast – order O(N log N) – for all lengths, including lengths that have large prime factors.
The following code performs a simple DFT and then inverts it to re-obtain the original data.
// Create a Fourier transformer for length-6 series
FourierTransformer ft = new FourierTransformer(6);
// Create a length-6 series and transform it
Complex[] x = new Complex[] { 0.0, 1.0, 0.0, 0.0, 0.0, 0.0 };
Complex[] xt = ft.Transform(x);
// Re-use the same transformer to transform a different  series
Complex[] y = new Complex[] { 1.0, 1.0, 1.0, 1.0, 1.0, 1.0 };
Complex[] yt = ft.Transform(y);
// Transform them back
Complex[] xtt = ft.InverseTransform(xt);
Complex[] ytt = ft.InverseTransform(yt);
Constructor & Destructor Documentation
FourierTransformer() [1/2]
Meta.Numerics.SignalProcessing.FourierTransformer.FourierTransformer (int size) inline
Initializes a new instance of the Fourier transformer.
Parameters
size The series length of the transformer, which must be positive.
References Meta.Numerics.SignalProcessing.Negative.
FourierTransformer() [2/2]
Meta.Numerics.SignalProcessing.FourierTransformer.FourierTransformer (int size, FourierSign signConvention, FourierNormalization normalizationConvention) inline
Initializes a new instance of the Fourier transformer with the given sign and normalization conventions.
Parameters
size The series length of the transformer, which must be positive.
signConvention The sign convention of the transformer.
normalizationConvention The normalization convention of the transformer.
There are multiple conventions for both the sign of the exponent and the overall normalization of Fourier transforms. The default conventions for some widely used software packages are summarized in the following table.
Software Sign Normalization
Meta.Numerics FourierSign.Negative FourierNormalization.None
Matlab FourierSign.Negative FourierNormalization.None
Mathmatica FourierSign.Positive FourierNormalization.Unitary
Numerical Recipies FourierSign.Positive FourierNormalization.None
References Meta.Numerics.SignalProcessing.FourierTransformer.factors, Meta.Numerics.SignalProcessing.FourierTransformer.normalizationConvention, Meta.Numerics.SignalProcessing.FourierTransformer.plan, Meta.Numerics.SignalProcessing.FourierTransformer.roots, Meta.Numerics.SignalProcessing.FourierTransformer.signConvention, and Meta.Numerics.SignalProcessing.FourierTransformer.size.
Member Function Documentation
GetSign()
int Meta.Numerics.SignalProcessing.FourierTransformer.GetSign () inline private
References Meta.Numerics.SignalProcessing.FourierTransformer.signConvention.
Referenced by Meta.Numerics.SignalProcessing.FourierTransformer.InverseTransform(), and Meta.Numerics.SignalProcessing.FourierTransformer.Transform().
Normalize()
static void Meta.Numerics.SignalProcessing.FourierTransformer.Normalize (Complex[] x, double f) inline static private
Referenced by Meta.Numerics.SignalProcessing.FourierTransformer.InverseTransform(), and Meta.Numerics.SignalProcessing.FourierTransformer.Transform().
Transform()
Complex [] Meta.Numerics.SignalProcessing.FourierTransformer.Transform (IList< Complex > values) inline
Computes the Fourier transform of the given series.
Parameters
values The series to transform.
Returns
The discrete Fourier transform of the series.
References Meta.Numerics.SignalProcessing.FourierTransformer.GetSign(), Meta.Numerics.SignalProcessing.FourierTransformer.normalizationConvention, Meta.Numerics.SignalProcessing.FourierTransformer.Normalize(), and Meta.Numerics.SignalProcessing.FourierTransformer.size.
InverseTransform()
Complex [] Meta.Numerics.SignalProcessing.FourierTransformer.InverseTransform (IList< Complex > values) inline
Computes the inverse Fourier transform of the given series.
Parameters
values The series to invert.
Returns
The inverse discrete Fourier transform of the series.
References Meta.Numerics.SignalProcessing.FourierTransformer.GetSign(), Meta.Numerics.SignalProcessing.FourierTransformer.normalizationConvention, Meta.Numerics.SignalProcessing.FourierTransformer.Normalize(), and Meta.Numerics.SignalProcessing.FourierTransformer.size.
Referenced by Test.FourierTest.FourierInverse(), Test.FourierTest.FourierSpecialCases(), and Test.FourierTest.TestMethod1().
Member Data Documentation
size
int Meta.Numerics.SignalProcessing.FourierTransformer.size private
Referenced by Meta.Numerics.SignalProcessing.FourierTransformer.FourierTransformer(), Meta.Numerics.SignalProcessing.FourierTransformer.InverseTransform(), and Meta.Numerics.SignalProcessing.FourierTransformer.Transform().
factors
List<Factor> Meta.Numerics.SignalProcessing.FourierTransformer.factors private
Referenced by Meta.Numerics.SignalProcessing.FourierTransformer.FourierTransformer().
plan
List<Transformlet> Meta.Numerics.SignalProcessing.FourierTransformer.plan private
Referenced by Meta.Numerics.SignalProcessing.FourierTransformer.FourierTransformer().
normalizationConvention
FourierNormalization Meta.Numerics.SignalProcessing.FourierTransformer.normalizationConvention private
Referenced by Meta.Numerics.SignalProcessing.FourierTransformer.FourierTransformer(), Meta.Numerics.SignalProcessing.FourierTransformer.InverseTransform(), and Meta.Numerics.SignalProcessing.FourierTransformer.Transform().
signConvention
FourierSign Meta.Numerics.SignalProcessing.FourierTransformer.signConvention private
Referenced by Meta.Numerics.SignalProcessing.FourierTransformer.FourierTransformer(), and Meta.Numerics.SignalProcessing.FourierTransformer.GetSign().
roots
Complex [] Meta.Numerics.SignalProcessing.FourierTransformer.roots private
Referenced by Meta.Numerics.SignalProcessing.FourierTransformer.FourierTransformer().
Property Documentation
Length
int Meta.Numerics.SignalProcessing.FourierTransformer.Length get
The series length for which the transformer is specialized.
Referenced by Test.FourierTest.FourierSpecialCases().
NormalizationConvention
FourierNormalization Meta.Numerics.SignalProcessing.FourierTransformer.NormalizationConvention get
Gets the normalization convention used by the transformer.
SignConvention
FourierSign Meta.Numerics.SignalProcessing.FourierTransformer.SignConvention get
Gets the normalization convention used by the transformer.
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/SignalProcessing/FourierTransformer.cs