Doc: IGLib EXTENDED: NUnit.Engine.Runners.ProcessRunner Class Reference
NUnit.Engine.Runners.ProcessRunner Class Reference
Summary description for ProcessRunner.
Public Member Functions
ProcessRunner (IServiceLocator services, TestPackage package)
override void UnloadPackage ()
Unload any loaded TestPackage and clear the reference to the remote runner.
override void StopRun (bool force)
Cancel the ongoing test run. If no test is running, the call is ignored.
Public Member Functions inherited from NUnit.Engine.Runners.AbstractTestRunner
AbstractTestRunner (IServiceLocator services, TestPackage package)
TestEngineResult Explore (TestFilter filter)
Explores the TestPackage and returns information about the tests found. Loads the package if not done previously.
TestEngineResult Load ()
Loads the TestPackage for exploration or execution, saving the result.
TestEngineResult Reload ()
Reload the currently loaded test package, saving the result.
void Unload ()
Unload any loaded TestPackage.
int CountTestCases (TestFilter filter)
Count the test cases that would be run under the specified filter, loading the TestPackage if it is not already loaded.
TestEngineResult Run (ITestEventListener listener, TestFilter filter)
Run the tests in the TestPackage, loading the package if this has not already been done.
AsyncTestEngineResult RunAsync (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the loaded TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses.
void StartRun (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the TestPackage. The tests are run asynchronously and the listener interface is notified as it progresses. Loads the TestPackage if not already loaded.
void Dispose ()
Protected Member Functions
override TestEngineResult ExploreTests (TestFilter filter)
Explore a TestPackage and return information about the tests found.
override TestEngineResult LoadPackage ()
Load a TestPackage for possible execution
override int CountTests (TestFilter filter)
Count the test cases that would be run under the specified filter.
override TestEngineResult RunTests (ITestEventListener listener, TestFilter filter)
Run the tests in a loaded TestPackage
override AsyncTestEngineResult RunTestsAsync (ITestEventListener listener, TestFilter filter)
Start a run of the tests in the loaded TestPackage, returning immediately. The tests are run asynchronously and the listener interface is notified as it progresses.
override void Dispose (bool disposing)
Protected Member Functions inherited from NUnit.Engine.Runners.AbstractTestRunner
virtual TestEngineResult ReloadPackage ()
Reload the currently loaded test package. Overridden in derived classes to take any additional action.
bool IsProjectPackage (TestPackage package)
Properties
RuntimeFramework RuntimeFramework [get, private set]
Properties inherited from NUnit.Engine.Runners.AbstractTestRunner
IServiceLocator Services [get, private set]
Our Service Context
IProjectService ProjectService [get, private set]
ITestRunnerFactory TestRunnerFactory [get, private set]
TestPackage TestPackage [get, set]
The TestPackage for which this is the runner
TestEngineResult LoadResult [get, set]
The result of the last call to LoadPackage
bool IsPackageLoaded [get]
Gets an indicator of whether the package has been loaded.
Private Member Functions
TestEngineResult CreateFailedResult (Exception e)
Private Attributes
ITestAgent _agent
ITestEngineRunner _remoteRunner
TestAgency _agency
Static Private Attributes
const int NORMAL_TIMEOUT = 30000
const int DEBUG_TIMEOUT = NORMAL_TIMEOUT * 10
static readonly Logger log = InternalTrace.GetLogger(typeof(ProcessRunner))
Additional Inherited Members
Protected Attributes inherited from NUnit.Engine.Runners.AbstractTestRunner
bool _disposed = false
Static Protected Attributes inherited from NUnit.Engine.Runners.AbstractTestRunner
const string TEST_RUN_ELEMENT = "test-run"
Detailed Description
Summary description for ProcessRunner.
Constructor & Destructor Documentation
ProcessRunner()
NUnit.Engine.Runners.ProcessRunner.ProcessRunner (IServiceLocator services, TestPackage package) inline
References NUnit.Engine.Runners.ProcessRunner._agency, NUnit.Engine.IServiceLocator.GetService(), and NUnit.Engine.Runners.AbstractTestRunner.Services.
Member Function Documentation
ExploreTests()
override TestEngineResult NUnit.Engine.Runners.ProcessRunner.ExploreTests (TestFilter filter) inline protected virtual
Explore a TestPackage and return information about the tests found.
Parameters
filter A TestFilter used to select tests
Returns
A TestEngineResult.
Implements NUnit.Engine.Runners.AbstractTestRunner.
References NUnit.Engine.Runners.ProcessRunner._remoteRunner, NUnit.Engine.Runners.ProcessRunner.CreateFailedResult(), NUnit.Common.Logger.Error(), NUnit.Engine.ITestEngineRunner.Explore(), and NUnit.Engine.Runners.ProcessRunner.log.
LoadPackage()
override TestEngineResult NUnit.Engine.Runners.ProcessRunner.LoadPackage () inline protected virtual
Load a TestPackage for possible execution
Returns
A TestEngineResult.
Implements NUnit.Engine.Runners.AbstractTestRunner.
References NUnit.Engine.Runners.ProcessRunner._agency, NUnit.Engine.Runners.ProcessRunner._agent, NUnit.Engine.Runners.ProcessRunner._remoteRunner, NUnit.Engine.ITestAgent.CreateRunner(), NUnit.Engine.Runners.ProcessRunner.DEBUG_TIMEOUT, NUnit.Common.PackageSettings.DebugAgent, NUnit.Engine.Services.TestAgency.GetAgent(), NUnit.Common.Logger.Info(), NUnit.Engine.ITestEngineRunner.Load(), NUnit.Engine.Runners.ProcessRunner.log, NUnit.Engine.TestPackage.Name, NUnit.Engine.Runners.ProcessRunner.NORMAL_TIMEOUT, NUnit.Common.PackageSettings.PauseBeforeRun, and NUnit.Engine.Runners.AbstractTestRunner.Unload().
UnloadPackage()
override void NUnit.Engine.Runners.ProcessRunner.UnloadPackage () inline virtual
Unload any loaded TestPackage and clear the reference to the remote runner.
Reimplemented from NUnit.Engine.Runners.AbstractTestRunner.
References NUnit.Engine.Runners.ProcessRunner._remoteRunner, NUnit.Common.Logger.Info(), NUnit.Engine.Runners.ProcessRunner.log, NUnit.Engine.ITestEngineRunner.Unload(), and NUnit.Common.Logger.Warning().
CountTests()
override int NUnit.Engine.Runners.ProcessRunner.CountTests (TestFilter filter) inline protected virtual
Count the test cases that would be run under the specified filter.
Parameters
filter A TestFilter
Returns
The count of test cases
Implements NUnit.Engine.Runners.AbstractTestRunner.
References NUnit.Engine.Runners.ProcessRunner._remoteRunner, NUnit.Engine.ITestEngineRunner.CountTestCases(), NUnit.Common.Logger.Error(), and NUnit.Engine.Runners.ProcessRunner.log.
RunTests()
override TestEngineResult NUnit.Engine.Runners.ProcessRunner.RunTests (ITestEventListener listener, TestFilter filter) inline protected virtual
Run the tests in a loaded TestPackage
Parameters
listener An ITestEventHandler to receive events
filter A TestFilter used to select tests
Returns
A TestResult giving the result of the test execution
Implements NUnit.Engine.Runners.AbstractTestRunner.
References NUnit.Engine.Runners.ProcessRunner._remoteRunner, NUnit.Engine.Runners.ProcessRunner.CreateFailedResult(), NUnit.Common.Logger.Error(), NUnit.Engine.Runners.ProcessRunner.log, and NUnit.Engine.ITestEngineRunner.Run().
RunTestsAsync()
override AsyncTestEngineResult NUnit.Engine.Runners.ProcessRunner.RunTestsAsync (ITestEventListener listener, TestFilter filter) inline protected virtual
Start a run of the tests in the loaded TestPackage, returning immediately. The tests are run asynchronously and the listener interface is notified as it progresses.
Parameters
listener An ITestEventHandler to receive events
filter A TestFilter used to select tests
Returns
An AsyncTestRun that will provide the result of the test execution
Reimplemented from NUnit.Engine.Runners.AbstractTestRunner.
References NUnit.Engine.Runners.ProcessRunner._remoteRunner, NUnit.Engine.Runners.ProcessRunner.CreateFailedResult(), NUnit.Common.Logger.Error(), NUnit.Engine.Runners.ProcessRunner.log, and NUnit.Engine.ITestEngineRunner.RunAsync().
StopRun()
override void NUnit.Engine.Runners.ProcessRunner.StopRun (bool force) inline virtual
Cancel the ongoing test run. If no test is running, the call is ignored.
Parameters
force If true, cancel any ongoing test threads, otherwise wait for them to complete.
Implements NUnit.Engine.Runners.AbstractTestRunner.
References NUnit.Engine.Runners.ProcessRunner._remoteRunner, NUnit.Common.Logger.Error(), NUnit.Engine.Runners.ProcessRunner.log, and NUnit.Engine.ITestEngineRunner.StopRun().
Dispose()
override void NUnit.Engine.Runners.ProcessRunner.Dispose (bool disposing) inline protected virtual
Reimplemented from NUnit.Engine.Runners.AbstractTestRunner.
References NUnit.Engine.Runners.ProcessRunner._agent, NUnit.Common.Logger.Error(), NUnit.Common.Logger.Info(), NUnit.Engine.Runners.ProcessRunner.log, and NUnit.Engine.ITestAgent.Stop().
CreateFailedResult()
TestEngineResult NUnit.Engine.Runners.ProcessRunner.CreateFailedResult (Exception e) inline private
References NUnit.Common.XmlHelper.AddAttribute(), NUnit.Common.XmlHelper.CreateTopLevelElement(), NUnit.Engine.TestPackage.FullName, NUnit.Engine.TestPackage.ID, and NUnit.Engine.TestPackage.Name.
Referenced by NUnit.Engine.Runners.ProcessRunner.ExploreTests(), NUnit.Engine.Runners.ProcessRunner.RunTests(), and NUnit.Engine.Runners.ProcessRunner.RunTestsAsync().
Member Data Documentation
NORMAL_TIMEOUT
const int NUnit.Engine.Runners.ProcessRunner.NORMAL_TIMEOUT = 30000 static private
Referenced by NUnit.Engine.Runners.ProcessRunner.LoadPackage().
DEBUG_TIMEOUT
const int NUnit.Engine.Runners.ProcessRunner.DEBUG_TIMEOUT = NORMAL_TIMEOUT * 10 static private
Referenced by NUnit.Engine.Runners.ProcessRunner.LoadPackage().
log
readonly Logger NUnit.Engine.Runners.ProcessRunner.log = InternalTrace.GetLogger(typeof(ProcessRunner)) static private
Referenced by NUnit.Engine.Runners.ProcessRunner.CountTests(), NUnit.Engine.Runners.ProcessRunner.Dispose(), NUnit.Engine.Runners.ProcessRunner.ExploreTests(), NUnit.Engine.Runners.ProcessRunner.LoadPackage(), NUnit.Engine.Runners.ProcessRunner.RunTests(), NUnit.Engine.Runners.ProcessRunner.RunTestsAsync(), NUnit.Engine.Runners.ProcessRunner.StopRun(), and NUnit.Engine.Runners.ProcessRunner.UnloadPackage().
_agent
ITestAgent NUnit.Engine.Runners.ProcessRunner._agent private
Referenced by NUnit.Engine.Runners.ProcessRunner.Dispose(), and NUnit.Engine.Runners.ProcessRunner.LoadPackage().
_remoteRunner
ITestEngineRunner NUnit.Engine.Runners.ProcessRunner._remoteRunner private
Referenced by NUnit.Engine.Runners.ProcessRunner.CountTests(), NUnit.Engine.Runners.ProcessRunner.ExploreTests(), NUnit.Engine.Runners.ProcessRunner.LoadPackage(), NUnit.Engine.Runners.ProcessRunner.RunTests(), NUnit.Engine.Runners.ProcessRunner.RunTestsAsync(), NUnit.Engine.Runners.ProcessRunner.StopRun(), and NUnit.Engine.Runners.ProcessRunner.UnloadPackage().
_agency
TestAgency NUnit.Engine.Runners.ProcessRunner._agency private
Referenced by NUnit.Engine.Runners.ProcessRunner.LoadPackage(), and NUnit.Engine.Runners.ProcessRunner.ProcessRunner().
Property Documentation
RuntimeFramework
RuntimeFramework NUnit.Engine.Runners.ProcessRunner.RuntimeFramework get private set
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Runners/ProcessRunner.cs