Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAED4 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAED4 Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAED4 (DLAMCH dlamch, DLAED5 dlaed5, DLAED6 dlaed6)
DLAED4 ()
void Run (int N, int I, double[] D, int offset_d, double[] Z, int offset_z, ref double[] DELTA, int offset_delta, double RHO, ref double DLAM, ref int INFO)
Private Attributes
DLAMCH _dlamch
DLAED5 _dlaed5
DLAED6 _dlaed6
double[] ZZ = new double[3]
Static Private Attributes
const int MAXIT = 30
const double ZERO = 0.0E0
const double ONE = 1.0E0
const double TWO = 2.0E0
const double THREE = 3.0E0
const double FOUR = 4.0E0
const double EIGHT = 8.0E0
const double TEN = 10.0E0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
This subroutine computes the I-th updated eigenvalue of a symmetric rank-one modification to a diagonal matrix whose elements are given in the array d, and that
D(i) .LT. D(j) for i .LT. j
and that RHO .GT. 0. This is arranged by the calling routine, and is no loss in generality. The rank-one modified system is thus
diag(D) + RHO * Z * Z_transpose.
where we assume the Euclidean norm of Z is 1.
The method consists of approximating the rational functions in the secular equation by simpler interpolating rational functions.
/summary>
Constructor & Destructor Documentation
DLAED4() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAED4.DLAED4 (DLAMCH dlamch, DLAED5 dlaed5, DLAED6 dlaed6) inline
DLAED4() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAED4.DLAED4 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAED4.Run (int N, int I, double[] D, int offset_d, double[] Z, int offset_z, ref double[] DELTA, int offset_delta, double RHO, ref double DLAM, ref int INFO) inline
Purpose
This subroutine computes the I-th updated eigenvalue of a symmetric rank-one modification to a diagonal matrix whose elements are given in the array d, and that
D(i) .LT. D(j) for i .LT. j
and that RHO .GT. 0. This is arranged by the calling routine, and is no loss in generality. The rank-one modified system is thus
diag(D) + RHO * Z * Z_transpose.
where we assume the Euclidean norm of Z is 1.
The method consists of approximating the rational functions in the secular equation by simpler interpolating rational functions.
/summary>
Parameters
N (input) INTEGER The length of all arrays. /param>
Parameters
I (input) INTEGER The index of the eigenvalue to be computed. 1 .LE. I .LE. N. /param>
Parameters
D (input) DOUBLE PRECISION array, dimension (N) The original eigenvalues. It is assumed that they are in order, D(I) .LT. D(J) for I .LT. J. /param>
Parameters
Z (input) DOUBLE PRECISION array, dimension (N) The components of the updating vector. /param>
Parameters
DELTA (output) DOUBLE PRECISION array, dimension (N) If N .GT. 2, DELTA contains (D(j) - lambda_I) in its j-th component. If N = 1, then DELTA(1) = 1. If N = 2, see DLAED5 for detail. The vector DELTA contains the information necessary to construct the eigenvectors by DLAED3 and DLAED9. /param>
Parameters
RHO (input) DOUBLE PRECISION The scalar in the symmetric updating formula. /param>
Parameters
DLAM (output) DOUBLE PRECISION The computed lambda_I, the I-th updated eigenvalue. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .GT. 0: if INFO = 1, the updating process failed. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLAED4.EIGHT, DotNumerics.LinearAlgebra.CSLapack.DLAED4.FOUR, DotNumerics.LinearAlgebra.CSLapack.DLAED4.MAXIT, DotNumerics.LinearAlgebra.CSLapack.DLAED4.ONE, DotNumerics.LinearAlgebra.CSLapack.DLAED5.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED6.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED4.TEN, DotNumerics.LinearAlgebra.CSLapack.DLAED4.THREE, DotNumerics.LinearAlgebra.CSLapack.DLAED4.TWO, DotNumerics.LinearAlgebra.CSLapack.DLAED4.ZERO, and DotNumerics.LinearAlgebra.CSLapack.DLAED4.ZZ.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED9.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAED3.Run().
Member Data Documentation
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLAED4._dlamch private
_dlaed5
DLAED5 DotNumerics.LinearAlgebra.CSLapack.DLAED4._dlaed5 private
_dlaed6
DLAED6 DotNumerics.LinearAlgebra.CSLapack.DLAED4._dlaed6 private
MAXIT
const int DotNumerics.LinearAlgebra.CSLapack.DLAED4.MAXIT = 30 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED4.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAED4.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED4.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAED4.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED4.Run().
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DLAED4.TWO = 2.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED4.Run().
THREE
const double DotNumerics.LinearAlgebra.CSLapack.DLAED4.THREE = 3.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED4.Run().
FOUR
const double DotNumerics.LinearAlgebra.CSLapack.DLAED4.FOUR = 4.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED4.Run().
EIGHT
const double DotNumerics.LinearAlgebra.CSLapack.DLAED4.EIGHT = 8.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED4.Run().
TEN
const double DotNumerics.LinearAlgebra.CSLapack.DLAED4.TEN = 10.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED4.Run().
ZZ
double [] DotNumerics.LinearAlgebra.CSLapack.DLAED4.ZZ = new double[3] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED4.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlaed4.cs