Doc: IGLib EXTENDED: IG.Neural.Applications.TadejFormOld Class Reference
IG.Neural.Applications.TadejFormOld Class Reference
GUI Form for training neural networks.
Public Member Functions
TadejFormOld ()
void testSmooth ()
TadejFormOld ()
void testSmooth ()
TadejFormOld ()
void testSmooth ()
Public Attributes
SampledDataSet trainingData = null
InputOutputDataDefiniton definitionData = null
System.Windows.Forms.TextBox tbLoad
System.Windows.Forms.Button btStartTrain
System.ComponentModel.BackgroundWorker backgroundWorker1
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
string filePathSave = @"../../testdata/LoadTrainingFile/"
string savedNetwNameJson = "Network"
string savedNetwNameDat = "Network"
bool multipleNetwork = true
bool uniqueOutput = false
bool uniqueInput = false
bool zrtoData = false
int numHiddenLayers = 0
int hiddenLayer1 = 40
int hiddenLayer2 = 0
int hiddenLayer3 = 0
int maxEpoch = 5000
int epochInBoundle = 500
double toleranceRMS = 0.1
double learningRate = 0.03
double alphaValue = 2.0
double momentum = 0.6
double verifPointsPercent = 0.2
double standDeviation = 0.0
bool breakTrainingFlag = false
Properties
Boolean btStartVisible [get, set]
Private Member Functions
void backgroundWorker1_DoWork (object sender, DoWorkEventArgs e)
void backgroundWorker1_ProgressChanged (object sender, ProgressChangedEventArgs e)
string MakeTheTimeString (double time)
void backgroundWorker1_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
void cBxSmoothData_CheckedChanged (object sender, EventArgs e)
void cBxMultipleNetwork_CheckedChanged (object sender, EventArgs e)
void cBxSaveNet_CheckedChanged (object sender, EventArgs e)
void cbxVerifPoints_CheckedChanged (object sender, EventArgs e)
void cbNeuralNetworkType_SelectedIndexChanged (object sender, EventArgs e)
void numHiddenLayer1_ValueChanged (object sender, EventArgs e)
void numHiddenLayer2_ValueChanged (object sender, EventArgs e)
void numHiddenLayer3_ValueChanged (object sender, EventArgs e)
void numMaxEpoch_ValueChanged (object sender, EventArgs e)
void numEpochinBoundle_ValueChanged (object sender, EventArgs e)
void numTolerance_ValueChanged (object sender, EventArgs e)
void numLearningRate_ValueChanged (object sender, EventArgs e)
void numAlphaValue_ValueChanged (object sender, EventArgs e)
void numMomentum_ValueChanged (object sender, EventArgs e)
void numStandardDev_ValueChanged (object sender, EventArgs e)
void numVerifPoints_ValueChanged (object sender, EventArgs e)
void button2_Click (object sender, EventArgs e)
void btnPredictSave_Click (object sender, EventArgs e)
void btnLoadTrainJSON_Click (object sender, EventArgs e)
void btnLoadTrainCSV_Click (object sender, EventArgs e)
void btResetTrainingData_Click (object sender, EventArgs e)
void btSelectSaveNetworkPath_Click (object sender, EventArgs e)
void TranscribeDataToNetwork ()
void btStartTrain_Click (object sender, EventArgs e)
void btStopTraining_Click (object sender, EventArgs e)
void btTestSmooth_Click (object sender, EventArgs e)
void cbxUniqueInput_CheckedChanged (object sender, EventArgs e)
void cbxUniqueOutput_CheckedChanged (object sender, EventArgs e)
void cbxZeroData_CheckedChanged (object sender, EventArgs e)
void tBxSavedNameJson_TextChanged (object sender, EventArgs e)
void tBxSavedNameDat_TextChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void backgroundWorker1_DoWork (object sender, DoWorkEventArgs e)
void backgroundWorker1_ProgressChanged (object sender, ProgressChangedEventArgs e)
string MakeTheTimeString (double time)
void backgroundWorker1_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
void cBxSmoothData_CheckedChanged (object sender, EventArgs e)
void cBxMultipleNetwork_CheckedChanged (object sender, EventArgs e)
void cBxSaveNet_CheckedChanged (object sender, EventArgs e)
void cbxVerifPoints_CheckedChanged (object sender, EventArgs e)
void cbNeuralNetworkType_SelectedIndexChanged (object sender, EventArgs e)
void numHiddenLayer1_ValueChanged (object sender, EventArgs e)
void numHiddenLayer2_ValueChanged (object sender, EventArgs e)
void numHiddenLayer3_ValueChanged (object sender, EventArgs e)
void numMaxEpoch_ValueChanged (object sender, EventArgs e)
void numEpochinBoundle_ValueChanged (object sender, EventArgs e)
void numTolerance_ValueChanged (object sender, EventArgs e)
void numLearningRate_ValueChanged (object sender, EventArgs e)
void numAlphaValue_ValueChanged (object sender, EventArgs e)
void numMomentum_ValueChanged (object sender, EventArgs e)
void numStandardDev_ValueChanged (object sender, EventArgs e)
void numVerifPoints_ValueChanged (object sender, EventArgs e)
void button2_Click (object sender, EventArgs e)
void btnPredictSave_Click (object sender, EventArgs e)
void btnLoadTrainJSON_Click (object sender, EventArgs e)
void btnLoadTrainCSV_Click (object sender, EventArgs e)
void btResetTrainingData_Click (object sender, EventArgs e)
void btSelectSaveNetworkPath_Click (object sender, EventArgs e)
void TranscribeDataToNetwork ()
void btStartTrain_Click (object sender, EventArgs e)
void btStopTraining_Click (object sender, EventArgs e)
void btTestSmooth_Click (object sender, EventArgs e)
void cbxUniqueInput_CheckedChanged (object sender, EventArgs e)
void cbxUniqueOutput_CheckedChanged (object sender, EventArgs e)
void cbxZeroData_CheckedChanged (object sender, EventArgs e)
void tBxSavedNameJson_TextChanged (object sender, EventArgs e)
void tBxSavedNameDat_TextChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void backgroundWorker1_DoWork (object sender, DoWorkEventArgs e)
void backgroundWorker1_ProgressChanged (object sender, ProgressChangedEventArgs e)
string MakeTheTimeString (double time)
void backgroundWorker1_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
void cBxSmoothData_CheckedChanged (object sender, EventArgs e)
void cBxMultipleNetwork_CheckedChanged (object sender, EventArgs e)
void cBxSaveNet_CheckedChanged (object sender, EventArgs e)
void cbxVerifPoints_CheckedChanged (object sender, EventArgs e)
void cbNeuralNetworkType_SelectedIndexChanged (object sender, EventArgs e)
void numHiddenLayer1_ValueChanged (object sender, EventArgs e)
void numHiddenLayer2_ValueChanged (object sender, EventArgs e)
void numHiddenLayer3_ValueChanged (object sender, EventArgs e)
void numMaxEpoch_ValueChanged (object sender, EventArgs e)
void numEpochinBoundle_ValueChanged (object sender, EventArgs e)
void numTolerance_ValueChanged (object sender, EventArgs e)
void numLearningRate_ValueChanged (object sender, EventArgs e)
void numAlphaValue_ValueChanged (object sender, EventArgs e)
void numMomentum_ValueChanged (object sender, EventArgs e)
void numStandardDev_ValueChanged (object sender, EventArgs e)
void numVerifPoints_ValueChanged (object sender, EventArgs e)
void button2_Click (object sender, EventArgs e)
void btnPredictSave_Click (object sender, EventArgs e)
void btnLoadTrainJSON_Click (object sender, EventArgs e)
void btnLoadTrainCSV_Click (object sender, EventArgs e)
void btResetTrainingData_Click (object sender, EventArgs e)
void btSelectSaveNetworkPath_Click (object sender, EventArgs e)
void TranscribeDataToNetwork ()
void btStartTrain_Click (object sender, EventArgs e)
void btStopTraining_Click (object sender, EventArgs e)
void btTestSmooth_Click (object sender, EventArgs e)
void cbxUniqueInput_CheckedChanged (object sender, EventArgs e)
void cbxUniqueOutput_CheckedChanged (object sender, EventArgs e)
void cbxZeroData_CheckedChanged (object sender, EventArgs e)
void tBxSavedNameJson_TextChanged (object sender, EventArgs e)
void tBxSavedNameDat_TextChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.OpenFileDialog openFD
System.Windows.Forms.Button btnPredictSave
System.Windows.Forms.NumericUpDown numLearningRate
System.Windows.Forms.NumericUpDown numTolerance
System.Windows.Forms.Label labLearningRate
System.Windows.Forms.NumericUpDown numEpochinBoundle
System.Windows.Forms.NumericUpDown numAlphaValue
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.Label labMultipleNetwork
System.Windows.Forms.CheckBox cBxMultipleNetwork
System.Windows.Forms.NumericUpDown numHiddenLayer3
System.Windows.Forms.NumericUpDown numMomentum
System.Windows.Forms.NumericUpDown numHiddenLayer2
System.Windows.Forms.NumericUpDown numMaxEpoch
System.Windows.Forms.NumericUpDown numHiddenLayer1
System.Windows.Forms.Label labMaxEpoch
System.Windows.Forms.Label labAlphaValue
System.Windows.Forms.Label labHiddenLayer
System.Windows.Forms.Label labEpoch
System.Windows.Forms.Label labTollerance
System.Windows.Forms.Label labMomentum
System.Windows.Forms.FolderBrowserDialog folderBrouseSaveNetwork
System.Windows.Forms.GroupBox groupBox5
System.Windows.Forms.Button btnLoadTrainJSON
System.Windows.Forms.Button btnLoadTrainCSV
System.Windows.Forms.Button btResetTrainingData
System.Windows.Forms.GroupBox gbLoad
System.Windows.Forms.GroupBox gbSmooth
System.Windows.Forms.NumericUpDown numStandardDev
System.Windows.Forms.Label labStandardDev
System.Windows.Forms.Label label1
System.Windows.Forms.CheckBox cBxSmoothData
System.Windows.Forms.Label label4
System.Windows.Forms.Button btStopTraining
System.Windows.Forms.GroupBox groupBox4
System.Windows.Forms.ComboBox cbNeuralNetworkType
System.Windows.Forms.Label label5
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.Label labNumVerifPoints_
System.Windows.Forms.NumericUpDown numVerifPoints
System.Windows.Forms.Label labNumVerifPoints
System.Windows.Forms.CheckBox cbxVerifPoints
System.Windows.Forms.Label label14
System.Windows.Forms.GroupBox groupBox3
System.Windows.Forms.GroupBox gbSaveNet
System.Windows.Forms.TextBox tbSavePath
System.Windows.Forms.Label labSaveNet2
System.Windows.Forms.TextBox tBxSavedNameJson
System.Windows.Forms.TextBox tBxSavedNameDat
System.Windows.Forms.Label labSaveNet1
System.Windows.Forms.GroupBox gbTrainSave
System.Windows.Forms.CheckBox cBxSaveNet
System.Windows.Forms.Label label3
System.Windows.Forms.Button btSelectSaveNetworkPath
System.Windows.Forms.Button btnExit
System.Windows.Forms.Button btTestSmooth
System.Windows.Forms.TextBox tbTrainPairs
System.Windows.Forms.TextBox tbOutputVal
System.Windows.Forms.TextBox tbInputPar
System.Windows.Forms.Label labInputParamSmooth
System.Windows.Forms.Label labOutputValSmooth
System.Windows.Forms.Label labTrainPairsSmooth
System.Windows.Forms.CheckBox cbxUniqueOutput
System.Windows.Forms.CheckBox cbxUniqueInput
System.Windows.Forms.Label labUniqueOutput
System.Windows.Forms.Label labUniqueInbput
System.Windows.Forms.CheckBox cbxZeroData
System.Windows.Forms.Label labZeroData
System.Windows.Forms.Label labAfter
System.Windows.Forms.Label labBefore
System.Windows.Forms.TextBox tbTrainPairsSmooth
System.Windows.Forms.TextBox tbOutputValSmooth
System.Windows.Forms.TextBox tbInputParSmooth
System.Windows.Forms.TextBox tbTrainingTime
System.Windows.Forms.ProgressBar progressBarTraining
System.Windows.Forms.Label label2
Detailed Description
GUI Form for training neural networks.
$A Tako78 May11;
Constructor & Destructor Documentation
TadejFormOld() [1/3]
IG.Neural.Applications.TadejFormOld.TadejFormOld () inline
References IG.Neural.Applications.TadejFormOld.backgroundWorker1, and IG.Neural.Applications.TadejFormOld.InitializeComponent().
TadejFormOld() [2/3]
IG.Neural.Applications.TadejFormOld.TadejFormOld () inline
References IG.Neural.Applications.TadejFormOld.backgroundWorker1, and IG.Neural.Applications.TadejFormOld.InitializeComponent().
TadejFormOld() [3/3]
IG.Neural.Applications.TadejFormOld.TadejFormOld () inline
References IG.Neural.Applications.TadejFormOld.backgroundWorker1, and IG.Neural.Applications.TadejFormOld.InitializeComponent().
Member Function Documentation
backgroundWorker1_DoWork() [1/3]
void IG.Neural.Applications.TadejFormOld.backgroundWorker1_DoWork (object sender, DoWorkEventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.breakTrainingFlag, IG.Neural.Applications.TadejFormOld.epochInBoundle, IG.Num.INeuralApproximator.EpochsInBundle, IG.Neural.Applications.TadejFormOld.MakeTheTimeString(), IG.Neural.Applications.TadejFormOld.maxEpoch, IG.Num.INeuralApproximator.MaxEpochs, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Num.INeuralApproximator.StopTrainingCriteriaMet(), IG.Lib.StopWatch1.TotalTime, and IG.Num.INeuralApproximator.TrainNetwork().
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
backgroundWorker1_ProgressChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.backgroundWorker1_ProgressChanged (object sender, ProgressChangedEventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.epochInBoundle, IG.Neural.Applications.TadejFormOld.maxEpoch, IG.Neural.Applications.TadejFormOld.progressBarTraining, and IG.Neural.Applications.TadejFormOld.tbTrainingTime.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
MakeTheTimeString() [1/3]
string IG.Neural.Applications.TadejFormOld.MakeTheTimeString (double time) inline private
Referenced by IG.Neural.Applications.TadejFormOld.backgroundWorker1_DoWork().
backgroundWorker1_RunWorkerCompleted() [1/3]
void IG.Neural.Applications.TadejFormOld.backgroundWorker1_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.btStartTrain, IG.Neural.Applications.TadejFormOld.btStopTraining, and IG.Neural.Applications.TadejFormOld.tbLoad.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
cBxSmoothData_CheckedChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.btTestSmooth, IG.Neural.Applications.TadejFormOld.cBxSmoothData, IG.Neural.Applications.TadejFormOld.cbxUniqueInput, IG.Neural.Applications.TadejFormOld.cbxUniqueOutput, IG.Neural.Applications.TadejFormOld.cbxZeroData, IG.Neural.Applications.TadejFormOld.labAfter, IG.Neural.Applications.TadejFormOld.labBefore, IG.Neural.Applications.TadejFormOld.labInputParamSmooth, IG.Neural.Applications.TadejFormOld.labOutputValSmooth, IG.Neural.Applications.TadejFormOld.labStandardDev, IG.Neural.Applications.TadejFormOld.labTrainPairsSmooth, IG.Neural.Applications.TadejFormOld.labUniqueInbput, IG.Neural.Applications.TadejFormOld.labUniqueOutput, IG.Neural.Applications.TadejFormOld.labZeroData, IG.Neural.Applications.TadejFormOld.numStandardDev, IG.Neural.Applications.TadejFormOld.standDeviation, IG.Neural.Applications.TadejFormOld.tbInputPar, IG.Neural.Applications.TadejFormOld.tbInputParSmooth, IG.Neural.Applications.TadejFormOld.tbLoad, IG.Neural.Applications.TadejFormOld.tbOutputVal, IG.Neural.Applications.TadejFormOld.tbOutputValSmooth, IG.Neural.Applications.TadejFormOld.tbTrainPairs, IG.Neural.Applications.TadejFormOld.tbTrainPairsSmooth, and IG.Neural.Applications.TadejFormOld.testSmooth().
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
cBxMultipleNetwork_CheckedChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.cBxMultipleNetwork_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cBxMultipleNetwork, and IG.Neural.Applications.TadejFormOld.multipleNetwork.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
cBxSaveNet_CheckedChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.cBxSaveNet_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.btSelectSaveNetworkPath, IG.Neural.Applications.TadejFormOld.cBxSaveNet, IG.Neural.Applications.TadejFormOld.filePathSave, IG.Neural.Applications.TadejFormOld.gbSaveNet, IG.Neural.Applications.TadejFormOld.labSaveNet1, IG.Neural.Applications.TadejFormOld.labSaveNet2, IG.Neural.Applications.TadejFormOld.tbLoad, IG.Neural.Applications.TadejFormOld.tbSavePath, IG.Neural.Applications.TadejFormOld.tBxSavedNameDat, and IG.Neural.Applications.TadejFormOld.tBxSavedNameJson.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
cbxVerifPoints_CheckedChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.cbxVerifPoints_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cbxVerifPoints, IG.Neural.Applications.TadejFormOld.labNumVerifPoints, IG.Neural.Applications.TadejFormOld.labNumVerifPoints_, IG.Neural.Applications.TadejFormOld.numVerifPoints, and IG.Neural.Applications.TadejFormOld.verifPointsPercent.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
cbNeuralNetworkType_SelectedIndexChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType, IG.Neural.Applications.TadejFormOld.cBxMultipleNetwork, IG.Neural.Applications.TadejFormOld.labAlphaValue, IG.Neural.Applications.TadejFormOld.labEpoch, IG.Neural.Applications.TadejFormOld.labHiddenLayer, IG.Neural.Applications.TadejFormOld.labLearningRate, IG.Neural.Applications.TadejFormOld.labMaxEpoch, IG.Neural.Applications.TadejFormOld.labMomentum, IG.Neural.Applications.TadejFormOld.labMultipleNetwork, IG.Neural.Applications.TadejFormOld.labTollerance, IG.Neural.Applications.TadejFormOld.numAlphaValue, IG.Neural.Applications.TadejFormOld.numEpochinBoundle, IG.Neural.Applications.TadejFormOld.numHiddenLayer1, IG.Neural.Applications.TadejFormOld.numHiddenLayer2, IG.Neural.Applications.TadejFormOld.numHiddenLayer3, IG.Neural.Applications.TadejFormOld.numLearningRate, IG.Neural.Applications.TadejFormOld.numMaxEpoch, IG.Neural.Applications.TadejFormOld.numMomentum, and IG.Neural.Applications.TadejFormOld.numTolerance.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
numHiddenLayer1_ValueChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.numHiddenLayer1_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.hiddenLayer1, and IG.Neural.Applications.TadejFormOld.numHiddenLayer1.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
numHiddenLayer2_ValueChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.numHiddenLayer2_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.hiddenLayer2, and IG.Neural.Applications.TadejFormOld.numHiddenLayer2.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
numHiddenLayer3_ValueChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.numHiddenLayer3_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.hiddenLayer3, and IG.Neural.Applications.TadejFormOld.numHiddenLayer3.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
numMaxEpoch_ValueChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.numMaxEpoch_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.maxEpoch, and IG.Neural.Applications.TadejFormOld.numMaxEpoch.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
numEpochinBoundle_ValueChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.numEpochinBoundle_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.epochInBoundle, and IG.Neural.Applications.TadejFormOld.numEpochinBoundle.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
numTolerance_ValueChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.numTolerance_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.numTolerance, and IG.Neural.Applications.TadejFormOld.toleranceRMS.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
numLearningRate_ValueChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.numLearningRate_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.learningRate, and IG.Neural.Applications.TadejFormOld.numLearningRate.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
numAlphaValue_ValueChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.numAlphaValue_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.alphaValue, and IG.Neural.Applications.TadejFormOld.numAlphaValue.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
numMomentum_ValueChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.numMomentum_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.momentum, and IG.Neural.Applications.TadejFormOld.numMomentum.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
numStandardDev_ValueChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.numStandardDev_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cBxSmoothData, IG.Neural.Applications.TadejFormOld.numStandardDev, IG.Neural.Applications.TadejFormOld.standDeviation, and IG.Neural.Applications.TadejFormOld.tbLoad.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
numVerifPoints_ValueChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.numVerifPoints_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.numVerifPoints, and IG.Neural.Applications.TadejFormOld.verifPointsPercent.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
button2_Click() [1/3]
void IG.Neural.Applications.TadejFormOld.button2_Click (object sender, EventArgs e) inline private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
btnPredictSave_Click() [1/3]
void IG.Neural.Applications.TadejFormOld.btnPredictSave_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.ProgramTestTadejApp.TestPrediction().
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
btnLoadTrainJSON_Click() [1/3]
void IG.Neural.Applications.TadejFormOld.btnLoadTrainJSON_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.btStartVisible, IG.Neural.NeuralTadej.LoadSampledDataJson(), IG.Neural.Applications.TadejFormOld.tbLoad, IG.Neural.Applications.TadejFormOld.testSmooth(), and IG.Neural.Applications.TadejFormOld.trainingData.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
btnLoadTrainCSV_Click() [1/3]
void IG.Neural.Applications.TadejFormOld.btnLoadTrainCSV_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.btStartTrain, IG.Neural.Applications.formLoadCSV.tadejForm, IG.Neural.Applications.TadejFormOld.tbLoad, IG.Neural.Applications.TadejFormOld.testSmooth(), and IG.Neural.Applications.TadejFormOld.trainingData.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
btResetTrainingData_Click() [1/3]
void IG.Neural.Applications.TadejFormOld.btResetTrainingData_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.btStartVisible, IG.Neural.Applications.TadejFormOld.progressBarTraining, IG.Neural.Applications.TadejFormOld.tbLoad, IG.Neural.Applications.TadejFormOld.tbTrainingTime, IG.Neural.Applications.TadejFormOld.testSmooth(), and IG.Neural.Applications.TadejFormOld.trainingData.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
btSelectSaveNetworkPath_Click() [1/3]
void IG.Neural.Applications.TadejFormOld.btSelectSaveNetworkPath_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.filePathSave, and IG.Neural.Applications.TadejFormOld.tbSavePath.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
TranscribeDataToNetwork() [1/3]
void IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork () inline private
References IG.Neural.Applications.TadejFormOld.alphaValue, IG.Neural.Applications.TadejFormOld.cBxSaveNet, IG.Neural.Applications.TadejFormOld.cBxSmoothData, IG.Lib.IndexList.CreateRandom(), IG.Neural.Applications.TadejFormOld.epochInBoundle, IG.Num.INeuralApproximator.EpochsInBundle, IG.Neural.Applications.TadejFormOld.filePathSave, IG.Neural.Applications.TadejFormOld.hiddenLayer1, IG.Neural.Applications.TadejFormOld.hiddenLayer2, IG.Neural.Applications.TadejFormOld.hiddenLayer3, IG.Num.INeuralApproximator.InputBoundsSafetyFactor, IG.Num.IVectorApproximator.InputLength, IG.Num.SampledDataSet.InputLength, IG.Num.INeuralApproximator.InputNeuronsRange, IG.Neural.Applications.TadejFormOld.learningRate, IG.Num.INeuralApproximator.LearningRate, IG.Num.SampledDataSet.Length, IG.Neural.Applications.TadejFormOld.maxEpoch, IG.Num.INeuralApproximator.MaxEpochs, IG.Neural.Applications.TadejFormOld.momentum, IG.Num.INeuralApproximator.Momentum, IG.Neural.Applications.TadejFormOld.multipleNetwork, IG.Num.INeuralApproximator.MultipleNetworks, IG.Neural.Applications.TadejFormOld.numHiddenLayers, IG.Num.INeuralApproximator.OutputBoundsSafetyFactor, IG.Num.IVectorApproximator.OutputLength, IG.Num.SampledDataSet.OutputLength, IG.Num.INeuralApproximator.OutputLevel, IG.Num.INeuralApproximator.OutputNeuronsRange, IG.Num.IBoundingBox.Reset(), IG.Num.INeuralApproximator.SetHiddenLayers(), IG.Num.INeuralApproximator.SigmoidAlphaValue, IG.Neural.NeuralTadej.SmoothingTrainingData(), IG.Neural.Applications.TadejFormOld.standDeviation, IG.Neural.Applications.TadejFormOld.tBxSavedNameDat, IG.Neural.Applications.TadejFormOld.tBxSavedNameJson, IG.Neural.Applications.TadejFormOld.toleranceRMS, IG.Num.INeuralApproximator.ToleranceRms, IG.Neural.Applications.TadejFormOld.trainingData, IG.Num.INeuralApproximator.TrainingData, IG.Neural.Applications.TadejFormOld.uniqueInput, IG.Neural.Applications.TadejFormOld.uniqueOutput, IG.Num.IBoundingBox.UpdateAll(), IG.Num.INeuralApproximator.VerificationIndices, and IG.Neural.Applications.TadejFormOld.zrtoData.
Referenced by IG.Neural.Applications.TadejFormOld.btStartTrain_Click().
btStartTrain_Click() [1/3]
void IG.Neural.Applications.TadejFormOld.btStartTrain_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.backgroundWorker1, IG.Num.INeuralApproximator.BreakTraining, IG.Neural.Applications.TadejFormOld.btStartTrain, IG.Neural.Applications.TadejFormOld.btStopTraining, IG.Neural.Applications.TadejFormOld.tbLoad, and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
btStopTraining_Click() [1/3]
void IG.Neural.Applications.TadejFormOld.btStopTraining_Click (object sender, EventArgs e) inline private
References IG.Num.INeuralApproximator.BreakTraining, and IG.Neural.Applications.TadejFormOld.breakTrainingFlag.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
btTestSmooth_Click() [1/3]
void IG.Neural.Applications.TadejFormOld.btTestSmooth_Click (object sender, EventArgs e) inline private
References IG.Neural.NeuralTadej.SmoothingTrainingData(), IG.Neural.Applications.TadejFormOld.standDeviation, IG.Neural.Applications.TadejFormOld.testSmooth(), IG.Neural.Applications.TadejFormOld.trainingData, IG.Neural.Applications.TadejFormOld.uniqueInput, IG.Neural.Applications.TadejFormOld.uniqueOutput, and IG.Neural.Applications.TadejFormOld.zrtoData.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
cbxUniqueInput_CheckedChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.cbxUniqueInput_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cbxUniqueInput, and IG.Neural.Applications.TadejFormOld.uniqueInput.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
cbxUniqueOutput_CheckedChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.cbxUniqueOutput_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cbxUniqueOutput, and IG.Neural.Applications.TadejFormOld.uniqueOutput.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
cbxZeroData_CheckedChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.cbxZeroData_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cbxZeroData, and IG.Neural.Applications.TadejFormOld.zrtoData.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
tBxSavedNameJson_TextChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.tBxSavedNameJson_TextChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.savedNetwNameJson, and IG.Neural.Applications.TadejFormOld.tBxSavedNameJson.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
tBxSavedNameDat_TextChanged() [1/3]
void IG.Neural.Applications.TadejFormOld.tBxSavedNameDat_TextChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.savedNetwNameDat, and IG.Neural.Applications.TadejFormOld.tBxSavedNameDat.
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
testSmooth() [1/3]
void IG.Neural.Applications.TadejFormOld.testSmooth () inline
References IG.Num.SampledDataSet.InputLength, IG.Num.SampledDataSet.Length, IG.Num.SampledDataSet.OutputLength, IG.Neural.Applications.TadejFormOld.tbInputPar, IG.Neural.Applications.TadejFormOld.tbInputParSmooth, IG.Neural.Applications.TadejFormOld.tbOutputVal, IG.Neural.Applications.TadejFormOld.tbOutputValSmooth, IG.Neural.Applications.TadejFormOld.tbTrainPairs, IG.Neural.Applications.TadejFormOld.tbTrainPairsSmooth, and IG.Neural.Applications.TadejFormOld.trainingData.
Referenced by IG.Neural.Applications.TadejFormOld.btnLoadTrainCSV_Click(), IG.Neural.Applications.TadejFormOld.btnLoadTrainJSON_Click(), IG.Neural.Applications.TadejFormOld.btResetTrainingData_Click(), IG.Neural.Applications.TadejFormOld.btTestSmooth_Click(), and IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged().
Dispose() [1/3]
override void IG.Neural.Applications.TadejFormOld.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.TadejFormOld.components.
InitializeComponent() [1/3]
void IG.Neural.Applications.TadejFormOld.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.TadejFormOld.backgroundWorker1, IG.Neural.Applications.TadejFormOld.backgroundWorker1_DoWork(), IG.Neural.Applications.TadejFormOld.backgroundWorker1_ProgressChanged(), IG.Neural.Applications.TadejFormOld.backgroundWorker1_RunWorkerCompleted(), IG.Neural.Applications.TadejFormOld.btnExit, IG.Neural.Applications.TadejFormOld.btnLoadTrainCSV, IG.Neural.Applications.TadejFormOld.btnLoadTrainCSV_Click(), IG.Neural.Applications.TadejFormOld.btnLoadTrainJSON, IG.Neural.Applications.TadejFormOld.btnLoadTrainJSON_Click(), IG.Neural.Applications.TadejFormOld.btnPredictSave, IG.Neural.Applications.TadejFormOld.btnPredictSave_Click(), IG.Neural.Applications.TadejFormOld.btResetTrainingData, IG.Neural.Applications.TadejFormOld.btResetTrainingData_Click(), IG.Neural.Applications.TadejFormOld.btSelectSaveNetworkPath, IG.Neural.Applications.TadejFormOld.btSelectSaveNetworkPath_Click(), IG.Neural.Applications.TadejFormOld.btStartTrain, IG.Neural.Applications.TadejFormOld.btStartTrain_Click(), IG.Neural.Applications.TadejFormOld.btStopTraining, IG.Neural.Applications.TadejFormOld.btStopTraining_Click(), IG.Neural.Applications.TadejFormOld.btTestSmooth, IG.Neural.Applications.TadejFormOld.btTestSmooth_Click(), IG.Neural.Applications.TadejFormOld.button2_Click(), IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType, IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), IG.Neural.Applications.TadejFormOld.cBxMultipleNetwork, IG.Neural.Applications.TadejFormOld.cBxMultipleNetwork_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cBxSaveNet, IG.Neural.Applications.TadejFormOld.cBxSaveNet_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cBxSmoothData, IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cbxUniqueInput, IG.Neural.Applications.TadejFormOld.cbxUniqueInput_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cbxUniqueOutput, IG.Neural.Applications.TadejFormOld.cbxUniqueOutput_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cbxVerifPoints, IG.Neural.Applications.TadejFormOld.cbxVerifPoints_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cbxZeroData, IG.Neural.Applications.TadejFormOld.cbxZeroData_CheckedChanged(), IG.Neural.Applications.TadejFormOld.folderBrouseSaveNetwork, IG.Neural.Applications.TadejFormOld.gbLoad, IG.Neural.Applications.TadejFormOld.gbSaveNet, IG.Neural.Applications.TadejFormOld.gbSmooth, IG.Neural.Applications.TadejFormOld.gbTrainSave, IG.Neural.Applications.TadejFormOld.groupBox1, IG.Neural.Applications.TadejFormOld.groupBox2, IG.Neural.Applications.TadejFormOld.groupBox3, IG.Neural.Applications.TadejFormOld.groupBox4, IG.Neural.Applications.TadejFormOld.groupBox5, IG.Neural.Applications.TadejFormOld.labAfter, IG.Neural.Applications.TadejFormOld.labAlphaValue, IG.Neural.Applications.TadejFormOld.labBefore, IG.Neural.Applications.TadejFormOld.label1, IG.Neural.Applications.TadejFormOld.label14, IG.Neural.Applications.TadejFormOld.label2, IG.Neural.Applications.TadejFormOld.label3, IG.Neural.Applications.TadejFormOld.label4, IG.Neural.Applications.TadejFormOld.label5, IG.Neural.Applications.TadejFormOld.labEpoch, IG.Neural.Applications.TadejFormOld.labHiddenLayer, IG.Neural.Applications.TadejFormOld.labInputParamSmooth, IG.Neural.Applications.TadejFormOld.labLearningRate, IG.Neural.Applications.TadejFormOld.labMaxEpoch, IG.Neural.Applications.TadejFormOld.labMomentum, IG.Neural.Applications.TadejFormOld.labMultipleNetwork, IG.Neural.Applications.TadejFormOld.labNumVerifPoints, IG.Neural.Applications.TadejFormOld.labNumVerifPoints_, IG.Neural.Applications.TadejFormOld.labOutputValSmooth, IG.Neural.Applications.TadejFormOld.labSaveNet1, IG.Neural.Applications.TadejFormOld.labSaveNet2, IG.Neural.Applications.TadejFormOld.labStandardDev, IG.Neural.Applications.TadejFormOld.labTollerance, IG.Neural.Applications.TadejFormOld.labTrainPairsSmooth, IG.Neural.Applications.TadejFormOld.labUniqueInbput, IG.Neural.Applications.TadejFormOld.labUniqueOutput, IG.Neural.Applications.TadejFormOld.labZeroData, IG.Neural.Applications.TadejFormOld.numAlphaValue, IG.Neural.Applications.TadejFormOld.numAlphaValue_ValueChanged(), IG.Neural.Applications.TadejFormOld.numEpochinBoundle, IG.Neural.Applications.TadejFormOld.numEpochinBoundle_ValueChanged(), IG.Neural.Applications.TadejFormOld.numHiddenLayer1, IG.Neural.Applications.TadejFormOld.numHiddenLayer1_ValueChanged(), IG.Neural.Applications.TadejFormOld.numHiddenLayer2, IG.Neural.Applications.TadejFormOld.numHiddenLayer2_ValueChanged(), IG.Neural.Applications.TadejFormOld.numHiddenLayer3, IG.Neural.Applications.TadejFormOld.numHiddenLayer3_ValueChanged(), IG.Neural.Applications.TadejFormOld.numLearningRate, IG.Neural.Applications.TadejFormOld.numLearningRate_ValueChanged(), IG.Neural.Applications.TadejFormOld.numMaxEpoch, IG.Neural.Applications.TadejFormOld.numMaxEpoch_ValueChanged(), IG.Neural.Applications.TadejFormOld.numMomentum, IG.Neural.Applications.TadejFormOld.numMomentum_ValueChanged(), IG.Neural.Applications.TadejFormOld.numStandardDev, IG.Neural.Applications.TadejFormOld.numStandardDev_ValueChanged(), IG.Neural.Applications.TadejFormOld.numTolerance, IG.Neural.Applications.TadejFormOld.numTolerance_ValueChanged(), IG.Neural.Applications.TadejFormOld.numVerifPoints, IG.Neural.Applications.TadejFormOld.numVerifPoints_ValueChanged(), IG.Neural.Applications.TadejFormOld.openFD, IG.Neural.Applications.TadejFormOld.progressBarTraining, IG.Neural.Applications.TadejFormOld.tbInputPar, IG.Neural.Applications.TadejFormOld.tbInputParSmooth, IG.Neural.Applications.TadejFormOld.tbLoad, IG.Neural.Applications.TadejFormOld.tbOutputVal, IG.Neural.Applications.TadejFormOld.tbOutputValSmooth, IG.Neural.Applications.TadejFormOld.tbSavePath, IG.Neural.Applications.TadejFormOld.tbTrainingTime, IG.Neural.Applications.TadejFormOld.tbTrainPairs, IG.Neural.Applications.TadejFormOld.tbTrainPairsSmooth, IG.Neural.Applications.TadejFormOld.tBxSavedNameDat, IG.Neural.Applications.TadejFormOld.tBxSavedNameDat_TextChanged(), IG.Neural.Applications.TadejFormOld.tBxSavedNameJson, and IG.Neural.Applications.TadejFormOld.tBxSavedNameJson_TextChanged().
Referenced by IG.Neural.Applications.TadejFormOld.TadejFormOld().
backgroundWorker1_DoWork() [2/3]
void IG.Neural.Applications.TadejFormOld.backgroundWorker1_DoWork (object sender, DoWorkEventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.breakTrainingFlag, IG.Neural.Applications.TadejFormOld.epochInBoundle, IG.Num.INeuralApproximator.EpochsInBundle, IG.Neural.Applications.TadejFormOld.MakeTheTimeString(), IG.Neural.Applications.TadejFormOld.maxEpoch, IG.Num.INeuralApproximator.MaxEpochs, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Num.INeuralApproximator.StopTrainingCriteriaMet(), IG.Lib.StopWatch1.TotalTime, and IG.Num.INeuralApproximator.TrainNetwork().
backgroundWorker1_ProgressChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.backgroundWorker1_ProgressChanged (object sender, ProgressChangedEventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.epochInBoundle, IG.Neural.Applications.TadejFormOld.maxEpoch, IG.Neural.Applications.TadejFormOld.progressBarTraining, and IG.Neural.Applications.TadejFormOld.tbTrainingTime.
MakeTheTimeString() [2/3]
string IG.Neural.Applications.TadejFormOld.MakeTheTimeString (double time) inline private
backgroundWorker1_RunWorkerCompleted() [2/3]
void IG.Neural.Applications.TadejFormOld.backgroundWorker1_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.btStartTrain, IG.Neural.Applications.TadejFormOld.btStopTraining, and IG.Neural.Applications.TadejFormOld.tbLoad.
cBxSmoothData_CheckedChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.btTestSmooth, IG.Neural.Applications.TadejFormOld.cBxSmoothData, IG.Neural.Applications.TadejFormOld.cbxUniqueInput, IG.Neural.Applications.TadejFormOld.cbxUniqueOutput, IG.Neural.Applications.TadejFormOld.cbxZeroData, IG.Neural.Applications.TadejFormOld.labAfter, IG.Neural.Applications.TadejFormOld.labBefore, IG.Neural.Applications.TadejFormOld.labInputParamSmooth, IG.Neural.Applications.TadejFormOld.labOutputValSmooth, IG.Neural.Applications.TadejFormOld.labStandardDev, IG.Neural.Applications.TadejFormOld.labTrainPairsSmooth, IG.Neural.Applications.TadejFormOld.labUniqueInbput, IG.Neural.Applications.TadejFormOld.labUniqueOutput, IG.Neural.Applications.TadejFormOld.labZeroData, IG.Neural.Applications.TadejFormOld.numStandardDev, IG.Neural.Applications.TadejFormOld.standDeviation, IG.Neural.Applications.TadejFormOld.tbInputPar, IG.Neural.Applications.TadejFormOld.tbInputParSmooth, IG.Neural.Applications.TadejFormOld.tbLoad, IG.Neural.Applications.TadejFormOld.tbOutputVal, IG.Neural.Applications.TadejFormOld.tbOutputValSmooth, IG.Neural.Applications.TadejFormOld.tbTrainPairs, IG.Neural.Applications.TadejFormOld.tbTrainPairsSmooth, and IG.Neural.Applications.TadejFormOld.testSmooth().
cBxMultipleNetwork_CheckedChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.cBxMultipleNetwork_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cBxMultipleNetwork, and IG.Neural.Applications.TadejFormOld.multipleNetwork.
cBxSaveNet_CheckedChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.cBxSaveNet_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.btSelectSaveNetworkPath, IG.Neural.Applications.TadejFormOld.cBxSaveNet, IG.Neural.Applications.TadejFormOld.filePathSave, IG.Neural.Applications.TadejFormOld.gbSaveNet, IG.Neural.Applications.TadejFormOld.labSaveNet1, IG.Neural.Applications.TadejFormOld.labSaveNet2, IG.Neural.Applications.TadejFormOld.tbLoad, IG.Neural.Applications.TadejFormOld.tbSavePath, IG.Neural.Applications.TadejFormOld.tBxSavedNameDat, and IG.Neural.Applications.TadejFormOld.tBxSavedNameJson.
cbxVerifPoints_CheckedChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.cbxVerifPoints_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cbxVerifPoints, IG.Neural.Applications.TadejFormOld.labNumVerifPoints, IG.Neural.Applications.TadejFormOld.labNumVerifPoints_, IG.Neural.Applications.TadejFormOld.numVerifPoints, and IG.Neural.Applications.TadejFormOld.verifPointsPercent.
cbNeuralNetworkType_SelectedIndexChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType, IG.Neural.Applications.TadejFormOld.cBxMultipleNetwork, IG.Neural.Applications.TadejFormOld.labAlphaValue, IG.Neural.Applications.TadejFormOld.labEpoch, IG.Neural.Applications.TadejFormOld.labHiddenLayer, IG.Neural.Applications.TadejFormOld.labLearningRate, IG.Neural.Applications.TadejFormOld.labMaxEpoch, IG.Neural.Applications.TadejFormOld.labMomentum, IG.Neural.Applications.TadejFormOld.labMultipleNetwork, IG.Neural.Applications.TadejFormOld.labTollerance, IG.Neural.Applications.TadejFormOld.numAlphaValue, IG.Neural.Applications.TadejFormOld.numEpochinBoundle, IG.Neural.Applications.TadejFormOld.numHiddenLayer1, IG.Neural.Applications.TadejFormOld.numHiddenLayer2, IG.Neural.Applications.TadejFormOld.numHiddenLayer3, IG.Neural.Applications.TadejFormOld.numLearningRate, IG.Neural.Applications.TadejFormOld.numMaxEpoch, IG.Neural.Applications.TadejFormOld.numMomentum, and IG.Neural.Applications.TadejFormOld.numTolerance.
numHiddenLayer1_ValueChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.numHiddenLayer1_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.hiddenLayer1, and IG.Neural.Applications.TadejFormOld.numHiddenLayer1.
numHiddenLayer2_ValueChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.numHiddenLayer2_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.hiddenLayer2, and IG.Neural.Applications.TadejFormOld.numHiddenLayer2.
numHiddenLayer3_ValueChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.numHiddenLayer3_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.hiddenLayer3, and IG.Neural.Applications.TadejFormOld.numHiddenLayer3.
numMaxEpoch_ValueChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.numMaxEpoch_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.maxEpoch, and IG.Neural.Applications.TadejFormOld.numMaxEpoch.
numEpochinBoundle_ValueChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.numEpochinBoundle_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.epochInBoundle, and IG.Neural.Applications.TadejFormOld.numEpochinBoundle.
numTolerance_ValueChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.numTolerance_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.numTolerance, and IG.Neural.Applications.TadejFormOld.toleranceRMS.
numLearningRate_ValueChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.numLearningRate_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.learningRate, and IG.Neural.Applications.TadejFormOld.numLearningRate.
numAlphaValue_ValueChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.numAlphaValue_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.alphaValue, and IG.Neural.Applications.TadejFormOld.numAlphaValue.
numMomentum_ValueChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.numMomentum_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.momentum, and IG.Neural.Applications.TadejFormOld.numMomentum.
numStandardDev_ValueChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.numStandardDev_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cBxSmoothData, IG.Neural.Applications.TadejFormOld.numStandardDev, IG.Neural.Applications.TadejFormOld.standDeviation, and IG.Neural.Applications.TadejFormOld.tbLoad.
numVerifPoints_ValueChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.numVerifPoints_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.numVerifPoints, and IG.Neural.Applications.TadejFormOld.verifPointsPercent.
button2_Click() [2/3]
void IG.Neural.Applications.TadejFormOld.button2_Click (object sender, EventArgs e) inline private
btnPredictSave_Click() [2/3]
void IG.Neural.Applications.TadejFormOld.btnPredictSave_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.ProgramTestTadejApp.TestPrediction().
btnLoadTrainJSON_Click() [2/3]
void IG.Neural.Applications.TadejFormOld.btnLoadTrainJSON_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.btStartVisible, IG.Neural.NeuralTadej.LoadSampledDataJson(), IG.Neural.Applications.TadejFormOld.tbLoad, IG.Neural.Applications.TadejFormOld.testSmooth(), and IG.Neural.Applications.TadejFormOld.trainingData.
btnLoadTrainCSV_Click() [2/3]
void IG.Neural.Applications.TadejFormOld.btnLoadTrainCSV_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.btStartTrain, IG.Neural.Applications.formLoadCSV.tadejForm, IG.Neural.Applications.TadejFormOld.tbLoad, IG.Neural.Applications.TadejFormOld.testSmooth(), and IG.Neural.Applications.TadejFormOld.trainingData.
btResetTrainingData_Click() [2/3]
void IG.Neural.Applications.TadejFormOld.btResetTrainingData_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.btStartVisible, IG.Neural.Applications.TadejFormOld.progressBarTraining, IG.Neural.Applications.TadejFormOld.tbLoad, IG.Neural.Applications.TadejFormOld.tbTrainingTime, IG.Neural.Applications.TadejFormOld.testSmooth(), and IG.Neural.Applications.TadejFormOld.trainingData.
btSelectSaveNetworkPath_Click() [2/3]
void IG.Neural.Applications.TadejFormOld.btSelectSaveNetworkPath_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.filePathSave, and IG.Neural.Applications.TadejFormOld.tbSavePath.
TranscribeDataToNetwork() [2/3]
void IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork () inline private
References IG.Neural.Applications.TadejFormOld.alphaValue, IG.Neural.Applications.TadejFormOld.cBxSaveNet, IG.Neural.Applications.TadejFormOld.cBxSmoothData, IG.Lib.IndexList.CreateRandom(), IG.Neural.Applications.TadejFormOld.epochInBoundle, IG.Num.INeuralApproximator.EpochsInBundle, IG.Neural.Applications.TadejFormOld.filePathSave, IG.Neural.Applications.TadejFormOld.hiddenLayer1, IG.Neural.Applications.TadejFormOld.hiddenLayer2, IG.Neural.Applications.TadejFormOld.hiddenLayer3, IG.Num.INeuralApproximator.InputBoundsSafetyFactor, IG.Num.IVectorApproximator.InputLength, IG.Num.SampledDataSet.InputLength, IG.Num.INeuralApproximator.InputNeuronsRange, IG.Neural.Applications.TadejFormOld.learningRate, IG.Num.INeuralApproximator.LearningRate, IG.Num.SampledDataSet.Length, IG.Neural.Applications.TadejFormOld.maxEpoch, IG.Num.INeuralApproximator.MaxEpochs, IG.Neural.Applications.TadejFormOld.momentum, IG.Num.INeuralApproximator.Momentum, IG.Neural.Applications.TadejFormOld.multipleNetwork, IG.Num.INeuralApproximator.MultipleNetworks, IG.Neural.Applications.TadejFormOld.numHiddenLayers, IG.Num.INeuralApproximator.OutputBoundsSafetyFactor, IG.Num.IVectorApproximator.OutputLength, IG.Num.SampledDataSet.OutputLength, IG.Num.INeuralApproximator.OutputLevel, IG.Num.INeuralApproximator.OutputNeuronsRange, IG.Num.IBoundingBox.Reset(), IG.Num.INeuralApproximator.SetHiddenLayers(), IG.Num.INeuralApproximator.SigmoidAlphaValue, IG.Neural.NeuralTadej.SmoothingTrainingData(), IG.Neural.Applications.TadejFormOld.standDeviation, IG.Neural.Applications.TadejFormOld.tBxSavedNameDat, IG.Neural.Applications.TadejFormOld.tBxSavedNameJson, IG.Neural.Applications.TadejFormOld.toleranceRMS, IG.Num.INeuralApproximator.ToleranceRms, IG.Neural.Applications.TadejFormOld.trainingData, IG.Num.INeuralApproximator.TrainingData, IG.Neural.Applications.TadejFormOld.uniqueInput, IG.Neural.Applications.TadejFormOld.uniqueOutput, IG.Num.IBoundingBox.UpdateAll(), IG.Num.INeuralApproximator.VerificationIndices, and IG.Neural.Applications.TadejFormOld.zrtoData.
btStartTrain_Click() [2/3]
void IG.Neural.Applications.TadejFormOld.btStartTrain_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.backgroundWorker1, IG.Num.INeuralApproximator.BreakTraining, IG.Neural.Applications.TadejFormOld.btStartTrain, IG.Neural.Applications.TadejFormOld.btStopTraining, IG.Neural.Applications.TadejFormOld.tbLoad, and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
btStopTraining_Click() [2/3]
void IG.Neural.Applications.TadejFormOld.btStopTraining_Click (object sender, EventArgs e) inline private
References IG.Num.INeuralApproximator.BreakTraining, and IG.Neural.Applications.TadejFormOld.breakTrainingFlag.
btTestSmooth_Click() [2/3]
void IG.Neural.Applications.TadejFormOld.btTestSmooth_Click (object sender, EventArgs e) inline private
References IG.Neural.NeuralTadej.SmoothingTrainingData(), IG.Neural.Applications.TadejFormOld.standDeviation, IG.Neural.Applications.TadejFormOld.testSmooth(), IG.Neural.Applications.TadejFormOld.trainingData, IG.Neural.Applications.TadejFormOld.uniqueInput, IG.Neural.Applications.TadejFormOld.uniqueOutput, and IG.Neural.Applications.TadejFormOld.zrtoData.
cbxUniqueInput_CheckedChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.cbxUniqueInput_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cbxUniqueInput, and IG.Neural.Applications.TadejFormOld.uniqueInput.
cbxUniqueOutput_CheckedChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.cbxUniqueOutput_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cbxUniqueOutput, and IG.Neural.Applications.TadejFormOld.uniqueOutput.
cbxZeroData_CheckedChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.cbxZeroData_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cbxZeroData, and IG.Neural.Applications.TadejFormOld.zrtoData.
tBxSavedNameJson_TextChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.tBxSavedNameJson_TextChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.savedNetwNameJson, and IG.Neural.Applications.TadejFormOld.tBxSavedNameJson.
tBxSavedNameDat_TextChanged() [2/3]
void IG.Neural.Applications.TadejFormOld.tBxSavedNameDat_TextChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.savedNetwNameDat, and IG.Neural.Applications.TadejFormOld.tBxSavedNameDat.
testSmooth() [2/3]
void IG.Neural.Applications.TadejFormOld.testSmooth () inline
References IG.Num.SampledDataSet.InputLength, IG.Num.SampledDataSet.Length, IG.Num.SampledDataSet.OutputLength, IG.Neural.Applications.TadejFormOld.tbInputPar, IG.Neural.Applications.TadejFormOld.tbInputParSmooth, IG.Neural.Applications.TadejFormOld.tbOutputVal, IG.Neural.Applications.TadejFormOld.tbOutputValSmooth, IG.Neural.Applications.TadejFormOld.tbTrainPairs, IG.Neural.Applications.TadejFormOld.tbTrainPairsSmooth, and IG.Neural.Applications.TadejFormOld.trainingData.
Dispose() [2/3]
override void IG.Neural.Applications.TadejFormOld.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.TadejFormOld.components.
InitializeComponent() [2/3]
void IG.Neural.Applications.TadejFormOld.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.TadejFormOld.backgroundWorker1, IG.Neural.Applications.TadejFormOld.backgroundWorker1_DoWork(), IG.Neural.Applications.TadejFormOld.backgroundWorker1_ProgressChanged(), IG.Neural.Applications.TadejFormOld.backgroundWorker1_RunWorkerCompleted(), IG.Neural.Applications.TadejFormOld.btnExit, IG.Neural.Applications.TadejFormOld.btnLoadTrainCSV, IG.Neural.Applications.TadejFormOld.btnLoadTrainCSV_Click(), IG.Neural.Applications.TadejFormOld.btnLoadTrainJSON, IG.Neural.Applications.TadejFormOld.btnLoadTrainJSON_Click(), IG.Neural.Applications.TadejFormOld.btnPredictSave, IG.Neural.Applications.TadejFormOld.btnPredictSave_Click(), IG.Neural.Applications.TadejFormOld.btResetTrainingData, IG.Neural.Applications.TadejFormOld.btResetTrainingData_Click(), IG.Neural.Applications.TadejFormOld.btSelectSaveNetworkPath, IG.Neural.Applications.TadejFormOld.btSelectSaveNetworkPath_Click(), IG.Neural.Applications.TadejFormOld.btStartTrain, IG.Neural.Applications.TadejFormOld.btStartTrain_Click(), IG.Neural.Applications.TadejFormOld.btStopTraining, IG.Neural.Applications.TadejFormOld.btStopTraining_Click(), IG.Neural.Applications.TadejFormOld.btTestSmooth, IG.Neural.Applications.TadejFormOld.btTestSmooth_Click(), IG.Neural.Applications.TadejFormOld.button2_Click(), IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType, IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), IG.Neural.Applications.TadejFormOld.cBxMultipleNetwork, IG.Neural.Applications.TadejFormOld.cBxMultipleNetwork_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cBxSaveNet, IG.Neural.Applications.TadejFormOld.cBxSaveNet_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cBxSmoothData, IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cbxUniqueInput, IG.Neural.Applications.TadejFormOld.cbxUniqueInput_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cbxUniqueOutput, IG.Neural.Applications.TadejFormOld.cbxUniqueOutput_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cbxVerifPoints, IG.Neural.Applications.TadejFormOld.cbxVerifPoints_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cbxZeroData, IG.Neural.Applications.TadejFormOld.cbxZeroData_CheckedChanged(), IG.Neural.Applications.TadejFormOld.folderBrouseSaveNetwork, IG.Neural.Applications.TadejFormOld.gbLoad, IG.Neural.Applications.TadejFormOld.gbSaveNet, IG.Neural.Applications.TadejFormOld.gbSmooth, IG.Neural.Applications.TadejFormOld.gbTrainSave, IG.Neural.Applications.TadejFormOld.groupBox1, IG.Neural.Applications.TadejFormOld.groupBox2, IG.Neural.Applications.TadejFormOld.groupBox3, IG.Neural.Applications.TadejFormOld.groupBox4, IG.Neural.Applications.TadejFormOld.groupBox5, IG.Neural.Applications.TadejFormOld.labAfter, IG.Neural.Applications.TadejFormOld.labAlphaValue, IG.Neural.Applications.TadejFormOld.labBefore, IG.Neural.Applications.TadejFormOld.label1, IG.Neural.Applications.TadejFormOld.label14, IG.Neural.Applications.TadejFormOld.label2, IG.Neural.Applications.TadejFormOld.label3, IG.Neural.Applications.TadejFormOld.label4, IG.Neural.Applications.TadejFormOld.label5, IG.Neural.Applications.TadejFormOld.labEpoch, IG.Neural.Applications.TadejFormOld.labHiddenLayer, IG.Neural.Applications.TadejFormOld.labInputParamSmooth, IG.Neural.Applications.TadejFormOld.labLearningRate, IG.Neural.Applications.TadejFormOld.labMaxEpoch, IG.Neural.Applications.TadejFormOld.labMomentum, IG.Neural.Applications.TadejFormOld.labMultipleNetwork, IG.Neural.Applications.TadejFormOld.labNumVerifPoints, IG.Neural.Applications.TadejFormOld.labNumVerifPoints_, IG.Neural.Applications.TadejFormOld.labOutputValSmooth, IG.Neural.Applications.TadejFormOld.labSaveNet1, IG.Neural.Applications.TadejFormOld.labSaveNet2, IG.Neural.Applications.TadejFormOld.labStandardDev, IG.Neural.Applications.TadejFormOld.labTollerance, IG.Neural.Applications.TadejFormOld.labTrainPairsSmooth, IG.Neural.Applications.TadejFormOld.labUniqueInbput, IG.Neural.Applications.TadejFormOld.labUniqueOutput, IG.Neural.Applications.TadejFormOld.labZeroData, IG.Neural.Applications.TadejFormOld.numAlphaValue, IG.Neural.Applications.TadejFormOld.numAlphaValue_ValueChanged(), IG.Neural.Applications.TadejFormOld.numEpochinBoundle, IG.Neural.Applications.TadejFormOld.numEpochinBoundle_ValueChanged(), IG.Neural.Applications.TadejFormOld.numHiddenLayer1, IG.Neural.Applications.TadejFormOld.numHiddenLayer1_ValueChanged(), IG.Neural.Applications.TadejFormOld.numHiddenLayer2, IG.Neural.Applications.TadejFormOld.numHiddenLayer2_ValueChanged(), IG.Neural.Applications.TadejFormOld.numHiddenLayer3, IG.Neural.Applications.TadejFormOld.numHiddenLayer3_ValueChanged(), IG.Neural.Applications.TadejFormOld.numLearningRate, IG.Neural.Applications.TadejFormOld.numLearningRate_ValueChanged(), IG.Neural.Applications.TadejFormOld.numMaxEpoch, IG.Neural.Applications.TadejFormOld.numMaxEpoch_ValueChanged(), IG.Neural.Applications.TadejFormOld.numMomentum, IG.Neural.Applications.TadejFormOld.numMomentum_ValueChanged(), IG.Neural.Applications.TadejFormOld.numStandardDev, IG.Neural.Applications.TadejFormOld.numStandardDev_ValueChanged(), IG.Neural.Applications.TadejFormOld.numTolerance, IG.Neural.Applications.TadejFormOld.numTolerance_ValueChanged(), IG.Neural.Applications.TadejFormOld.numVerifPoints, IG.Neural.Applications.TadejFormOld.numVerifPoints_ValueChanged(), IG.Neural.Applications.TadejFormOld.openFD, IG.Neural.Applications.TadejFormOld.progressBarTraining, IG.Neural.Applications.TadejFormOld.tbInputPar, IG.Neural.Applications.TadejFormOld.tbInputParSmooth, IG.Neural.Applications.TadejFormOld.tbLoad, IG.Neural.Applications.TadejFormOld.tbOutputVal, IG.Neural.Applications.TadejFormOld.tbOutputValSmooth, IG.Neural.Applications.TadejFormOld.tbSavePath, IG.Neural.Applications.TadejFormOld.tbTrainingTime, IG.Neural.Applications.TadejFormOld.tbTrainPairs, IG.Neural.Applications.TadejFormOld.tbTrainPairsSmooth, IG.Neural.Applications.TadejFormOld.tBxSavedNameDat, IG.Neural.Applications.TadejFormOld.tBxSavedNameDat_TextChanged(), IG.Neural.Applications.TadejFormOld.tBxSavedNameJson, and IG.Neural.Applications.TadejFormOld.tBxSavedNameJson_TextChanged().
backgroundWorker1_DoWork() [3/3]
void IG.Neural.Applications.TadejFormOld.backgroundWorker1_DoWork (object sender, DoWorkEventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.breakTrainingFlag, IG.Neural.Applications.TadejFormOld.epochInBoundle, IG.Num.INeuralApproximator.EpochsInBundle, IG.Neural.Applications.TadejFormOld.MakeTheTimeString(), IG.Neural.Applications.TadejFormOld.maxEpoch, IG.Num.INeuralApproximator.MaxEpochs, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Num.INeuralApproximator.StopTrainingCriteriaMet(), IG.Lib.StopWatch1.TotalTime, and IG.Num.INeuralApproximator.TrainNetwork().
backgroundWorker1_ProgressChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.backgroundWorker1_ProgressChanged (object sender, ProgressChangedEventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.epochInBoundle, IG.Neural.Applications.TadejFormOld.maxEpoch, IG.Neural.Applications.TadejFormOld.progressBarTraining, and IG.Neural.Applications.TadejFormOld.tbTrainingTime.
MakeTheTimeString() [3/3]
string IG.Neural.Applications.TadejFormOld.MakeTheTimeString (double time) inline private
backgroundWorker1_RunWorkerCompleted() [3/3]
void IG.Neural.Applications.TadejFormOld.backgroundWorker1_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.btStartTrain, IG.Neural.Applications.TadejFormOld.btStopTraining, and IG.Neural.Applications.TadejFormOld.tbLoad.
cBxSmoothData_CheckedChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.btTestSmooth, IG.Neural.Applications.TadejFormOld.cBxSmoothData, IG.Neural.Applications.TadejFormOld.cbxUniqueInput, IG.Neural.Applications.TadejFormOld.cbxUniqueOutput, IG.Neural.Applications.TadejFormOld.cbxZeroData, IG.Neural.Applications.TadejFormOld.labAfter, IG.Neural.Applications.TadejFormOld.labBefore, IG.Neural.Applications.TadejFormOld.labInputParamSmooth, IG.Neural.Applications.TadejFormOld.labOutputValSmooth, IG.Neural.Applications.TadejFormOld.labStandardDev, IG.Neural.Applications.TadejFormOld.labTrainPairsSmooth, IG.Neural.Applications.TadejFormOld.labUniqueInbput, IG.Neural.Applications.TadejFormOld.labUniqueOutput, IG.Neural.Applications.TadejFormOld.labZeroData, IG.Neural.Applications.TadejFormOld.numStandardDev, IG.Neural.Applications.TadejFormOld.standDeviation, IG.Neural.Applications.TadejFormOld.tbInputPar, IG.Neural.Applications.TadejFormOld.tbInputParSmooth, IG.Neural.Applications.TadejFormOld.tbLoad, IG.Neural.Applications.TadejFormOld.tbOutputVal, IG.Neural.Applications.TadejFormOld.tbOutputValSmooth, IG.Neural.Applications.TadejFormOld.tbTrainPairs, IG.Neural.Applications.TadejFormOld.tbTrainPairsSmooth, and IG.Neural.Applications.TadejFormOld.testSmooth().
cBxMultipleNetwork_CheckedChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.cBxMultipleNetwork_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cBxMultipleNetwork, and IG.Neural.Applications.TadejFormOld.multipleNetwork.
cBxSaveNet_CheckedChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.cBxSaveNet_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.btSelectSaveNetworkPath, IG.Neural.Applications.TadejFormOld.cBxSaveNet, IG.Neural.Applications.TadejFormOld.filePathSave, IG.Neural.Applications.TadejFormOld.gbSaveNet, IG.Neural.Applications.TadejFormOld.labSaveNet1, IG.Neural.Applications.TadejFormOld.labSaveNet2, IG.Neural.Applications.TadejFormOld.tbLoad, IG.Neural.Applications.TadejFormOld.tbSavePath, IG.Neural.Applications.TadejFormOld.tBxSavedNameDat, and IG.Neural.Applications.TadejFormOld.tBxSavedNameJson.
cbxVerifPoints_CheckedChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.cbxVerifPoints_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cbxVerifPoints, IG.Neural.Applications.TadejFormOld.labNumVerifPoints, IG.Neural.Applications.TadejFormOld.labNumVerifPoints_, IG.Neural.Applications.TadejFormOld.numVerifPoints, and IG.Neural.Applications.TadejFormOld.verifPointsPercent.
cbNeuralNetworkType_SelectedIndexChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType, IG.Neural.Applications.TadejFormOld.cBxMultipleNetwork, IG.Neural.Applications.TadejFormOld.labAlphaValue, IG.Neural.Applications.TadejFormOld.labEpoch, IG.Neural.Applications.TadejFormOld.labHiddenLayer, IG.Neural.Applications.TadejFormOld.labLearningRate, IG.Neural.Applications.TadejFormOld.labMaxEpoch, IG.Neural.Applications.TadejFormOld.labMomentum, IG.Neural.Applications.TadejFormOld.labMultipleNetwork, IG.Neural.Applications.TadejFormOld.labTollerance, IG.Neural.Applications.TadejFormOld.numAlphaValue, IG.Neural.Applications.TadejFormOld.numEpochinBoundle, IG.Neural.Applications.TadejFormOld.numHiddenLayer1, IG.Neural.Applications.TadejFormOld.numHiddenLayer2, IG.Neural.Applications.TadejFormOld.numHiddenLayer3, IG.Neural.Applications.TadejFormOld.numLearningRate, IG.Neural.Applications.TadejFormOld.numMaxEpoch, IG.Neural.Applications.TadejFormOld.numMomentum, and IG.Neural.Applications.TadejFormOld.numTolerance.
numHiddenLayer1_ValueChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.numHiddenLayer1_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.hiddenLayer1, and IG.Neural.Applications.TadejFormOld.numHiddenLayer1.
numHiddenLayer2_ValueChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.numHiddenLayer2_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.hiddenLayer2, and IG.Neural.Applications.TadejFormOld.numHiddenLayer2.
numHiddenLayer3_ValueChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.numHiddenLayer3_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.hiddenLayer3, and IG.Neural.Applications.TadejFormOld.numHiddenLayer3.
numMaxEpoch_ValueChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.numMaxEpoch_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.maxEpoch, and IG.Neural.Applications.TadejFormOld.numMaxEpoch.
numEpochinBoundle_ValueChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.numEpochinBoundle_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.epochInBoundle, and IG.Neural.Applications.TadejFormOld.numEpochinBoundle.
numTolerance_ValueChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.numTolerance_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.numTolerance, and IG.Neural.Applications.TadejFormOld.toleranceRMS.
numLearningRate_ValueChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.numLearningRate_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.learningRate, and IG.Neural.Applications.TadejFormOld.numLearningRate.
numAlphaValue_ValueChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.numAlphaValue_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.alphaValue, and IG.Neural.Applications.TadejFormOld.numAlphaValue.
numMomentum_ValueChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.numMomentum_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.momentum, and IG.Neural.Applications.TadejFormOld.numMomentum.
numStandardDev_ValueChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.numStandardDev_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cBxSmoothData, IG.Neural.Applications.TadejFormOld.numStandardDev, IG.Neural.Applications.TadejFormOld.standDeviation, and IG.Neural.Applications.TadejFormOld.tbLoad.
numVerifPoints_ValueChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.numVerifPoints_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.numVerifPoints, and IG.Neural.Applications.TadejFormOld.verifPointsPercent.
button2_Click() [3/3]
void IG.Neural.Applications.TadejFormOld.button2_Click (object sender, EventArgs e) inline private
btnPredictSave_Click() [3/3]
void IG.Neural.Applications.TadejFormOld.btnPredictSave_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.ProgramTestTadejApp.TestPrediction().
btnLoadTrainJSON_Click() [3/3]
void IG.Neural.Applications.TadejFormOld.btnLoadTrainJSON_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.btStartVisible, IG.Neural.NeuralTadej.LoadSampledDataJson(), IG.Neural.Applications.TadejFormOld.tbLoad, IG.Neural.Applications.TadejFormOld.testSmooth(), and IG.Neural.Applications.TadejFormOld.trainingData.
btnLoadTrainCSV_Click() [3/3]
void IG.Neural.Applications.TadejFormOld.btnLoadTrainCSV_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.btStartTrain, IG.Neural.Applications.formLoadCSV.tadejForm, IG.Neural.Applications.TadejFormOld.tbLoad, IG.Neural.Applications.TadejFormOld.testSmooth(), and IG.Neural.Applications.TadejFormOld.trainingData.
btResetTrainingData_Click() [3/3]
void IG.Neural.Applications.TadejFormOld.btResetTrainingData_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.btStartVisible, IG.Neural.Applications.TadejFormOld.progressBarTraining, IG.Neural.Applications.TadejFormOld.tbLoad, IG.Neural.Applications.TadejFormOld.tbTrainingTime, IG.Neural.Applications.TadejFormOld.testSmooth(), and IG.Neural.Applications.TadejFormOld.trainingData.
btSelectSaveNetworkPath_Click() [3/3]
void IG.Neural.Applications.TadejFormOld.btSelectSaveNetworkPath_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.filePathSave, and IG.Neural.Applications.TadejFormOld.tbSavePath.
TranscribeDataToNetwork() [3/3]
void IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork () inline private
References IG.Neural.Applications.TadejFormOld.alphaValue, IG.Neural.Applications.TadejFormOld.cBxSaveNet, IG.Neural.Applications.TadejFormOld.cBxSmoothData, IG.Lib.IndexList.CreateRandom(), IG.Neural.Applications.TadejFormOld.epochInBoundle, IG.Num.INeuralApproximator.EpochsInBundle, IG.Neural.Applications.TadejFormOld.filePathSave, IG.Neural.Applications.TadejFormOld.hiddenLayer1, IG.Neural.Applications.TadejFormOld.hiddenLayer2, IG.Neural.Applications.TadejFormOld.hiddenLayer3, IG.Num.INeuralApproximator.InputBoundsSafetyFactor, IG.Num.IVectorApproximator.InputLength, IG.Num.SampledDataSet.InputLength, IG.Num.INeuralApproximator.InputNeuronsRange, IG.Neural.Applications.TadejFormOld.learningRate, IG.Num.INeuralApproximator.LearningRate, IG.Num.SampledDataSet.Length, IG.Neural.Applications.TadejFormOld.maxEpoch, IG.Num.INeuralApproximator.MaxEpochs, IG.Neural.Applications.TadejFormOld.momentum, IG.Num.INeuralApproximator.Momentum, IG.Neural.Applications.TadejFormOld.multipleNetwork, IG.Num.INeuralApproximator.MultipleNetworks, IG.Neural.Applications.TadejFormOld.numHiddenLayers, IG.Num.INeuralApproximator.OutputBoundsSafetyFactor, IG.Num.IVectorApproximator.OutputLength, IG.Num.SampledDataSet.OutputLength, IG.Num.INeuralApproximator.OutputLevel, IG.Num.INeuralApproximator.OutputNeuronsRange, IG.Num.IBoundingBox.Reset(), IG.Num.INeuralApproximator.SetHiddenLayers(), IG.Num.INeuralApproximator.SigmoidAlphaValue, IG.Neural.NeuralTadej.SmoothingTrainingData(), IG.Neural.Applications.TadejFormOld.standDeviation, IG.Neural.Applications.TadejFormOld.tBxSavedNameDat, IG.Neural.Applications.TadejFormOld.tBxSavedNameJson, IG.Neural.Applications.TadejFormOld.toleranceRMS, IG.Num.INeuralApproximator.ToleranceRms, IG.Neural.Applications.TadejFormOld.trainingData, IG.Num.INeuralApproximator.TrainingData, IG.Neural.Applications.TadejFormOld.uniqueInput, IG.Neural.Applications.TadejFormOld.uniqueOutput, IG.Num.IBoundingBox.UpdateAll(), IG.Num.INeuralApproximator.VerificationIndices, and IG.Neural.Applications.TadejFormOld.zrtoData.
btStartTrain_Click() [3/3]
void IG.Neural.Applications.TadejFormOld.btStartTrain_Click (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.backgroundWorker1, IG.Num.INeuralApproximator.BreakTraining, IG.Neural.Applications.TadejFormOld.btStartTrain, IG.Neural.Applications.TadejFormOld.btStopTraining, IG.Neural.Applications.TadejFormOld.tbLoad, and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
btStopTraining_Click() [3/3]
void IG.Neural.Applications.TadejFormOld.btStopTraining_Click (object sender, EventArgs e) inline private
References IG.Num.INeuralApproximator.BreakTraining, and IG.Neural.Applications.TadejFormOld.breakTrainingFlag.
btTestSmooth_Click() [3/3]
void IG.Neural.Applications.TadejFormOld.btTestSmooth_Click (object sender, EventArgs e) inline private
References IG.Neural.NeuralTadej.SmoothingTrainingData(), IG.Neural.Applications.TadejFormOld.standDeviation, IG.Neural.Applications.TadejFormOld.testSmooth(), IG.Neural.Applications.TadejFormOld.trainingData, IG.Neural.Applications.TadejFormOld.uniqueInput, IG.Neural.Applications.TadejFormOld.uniqueOutput, and IG.Neural.Applications.TadejFormOld.zrtoData.
cbxUniqueInput_CheckedChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.cbxUniqueInput_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cbxUniqueInput, and IG.Neural.Applications.TadejFormOld.uniqueInput.
cbxUniqueOutput_CheckedChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.cbxUniqueOutput_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cbxUniqueOutput, and IG.Neural.Applications.TadejFormOld.uniqueOutput.
cbxZeroData_CheckedChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.cbxZeroData_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.cbxZeroData, and IG.Neural.Applications.TadejFormOld.zrtoData.
tBxSavedNameJson_TextChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.tBxSavedNameJson_TextChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.savedNetwNameJson, and IG.Neural.Applications.TadejFormOld.tBxSavedNameJson.
tBxSavedNameDat_TextChanged() [3/3]
void IG.Neural.Applications.TadejFormOld.tBxSavedNameDat_TextChanged (object sender, EventArgs e) inline private
References IG.Neural.Applications.TadejFormOld.savedNetwNameDat, and IG.Neural.Applications.TadejFormOld.tBxSavedNameDat.
testSmooth() [3/3]
void IG.Neural.Applications.TadejFormOld.testSmooth () inline
References IG.Num.SampledDataSet.InputLength, IG.Num.SampledDataSet.Length, IG.Num.SampledDataSet.OutputLength, IG.Neural.Applications.TadejFormOld.tbInputPar, IG.Neural.Applications.TadejFormOld.tbInputParSmooth, IG.Neural.Applications.TadejFormOld.tbOutputVal, IG.Neural.Applications.TadejFormOld.tbOutputValSmooth, IG.Neural.Applications.TadejFormOld.tbTrainPairs, IG.Neural.Applications.TadejFormOld.tbTrainPairsSmooth, and IG.Neural.Applications.TadejFormOld.trainingData.
Dispose() [3/3]
override void IG.Neural.Applications.TadejFormOld.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.TadejFormOld.components.
InitializeComponent() [3/3]
void IG.Neural.Applications.TadejFormOld.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.TadejFormOld.backgroundWorker1, IG.Neural.Applications.TadejFormOld.backgroundWorker1_DoWork(), IG.Neural.Applications.TadejFormOld.backgroundWorker1_ProgressChanged(), IG.Neural.Applications.TadejFormOld.backgroundWorker1_RunWorkerCompleted(), IG.Neural.Applications.TadejFormOld.btnExit, IG.Neural.Applications.TadejFormOld.btnLoadTrainCSV, IG.Neural.Applications.TadejFormOld.btnLoadTrainCSV_Click(), IG.Neural.Applications.TadejFormOld.btnLoadTrainJSON, IG.Neural.Applications.TadejFormOld.btnLoadTrainJSON_Click(), IG.Neural.Applications.TadejFormOld.btnPredictSave, IG.Neural.Applications.TadejFormOld.btnPredictSave_Click(), IG.Neural.Applications.TadejFormOld.btResetTrainingData, IG.Neural.Applications.TadejFormOld.btResetTrainingData_Click(), IG.Neural.Applications.TadejFormOld.btSelectSaveNetworkPath, IG.Neural.Applications.TadejFormOld.btSelectSaveNetworkPath_Click(), IG.Neural.Applications.TadejFormOld.btStartTrain, IG.Neural.Applications.TadejFormOld.btStartTrain_Click(), IG.Neural.Applications.TadejFormOld.btStopTraining, IG.Neural.Applications.TadejFormOld.btStopTraining_Click(), IG.Neural.Applications.TadejFormOld.btTestSmooth, IG.Neural.Applications.TadejFormOld.btTestSmooth_Click(), IG.Neural.Applications.TadejFormOld.button2_Click(), IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType, IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), IG.Neural.Applications.TadejFormOld.cBxMultipleNetwork, IG.Neural.Applications.TadejFormOld.cBxMultipleNetwork_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cBxSaveNet, IG.Neural.Applications.TadejFormOld.cBxSaveNet_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cBxSmoothData, IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cbxUniqueInput, IG.Neural.Applications.TadejFormOld.cbxUniqueInput_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cbxUniqueOutput, IG.Neural.Applications.TadejFormOld.cbxUniqueOutput_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cbxVerifPoints, IG.Neural.Applications.TadejFormOld.cbxVerifPoints_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cbxZeroData, IG.Neural.Applications.TadejFormOld.cbxZeroData_CheckedChanged(), IG.Neural.Applications.TadejFormOld.folderBrouseSaveNetwork, IG.Neural.Applications.TadejFormOld.gbLoad, IG.Neural.Applications.TadejFormOld.gbSaveNet, IG.Neural.Applications.TadejFormOld.gbSmooth, IG.Neural.Applications.TadejFormOld.gbTrainSave, IG.Neural.Applications.TadejFormOld.groupBox1, IG.Neural.Applications.TadejFormOld.groupBox2, IG.Neural.Applications.TadejFormOld.groupBox3, IG.Neural.Applications.TadejFormOld.groupBox4, IG.Neural.Applications.TadejFormOld.groupBox5, IG.Neural.Applications.TadejFormOld.labAfter, IG.Neural.Applications.TadejFormOld.labAlphaValue, IG.Neural.Applications.TadejFormOld.labBefore, IG.Neural.Applications.TadejFormOld.label1, IG.Neural.Applications.TadejFormOld.label14, IG.Neural.Applications.TadejFormOld.label2, IG.Neural.Applications.TadejFormOld.label3, IG.Neural.Applications.TadejFormOld.label4, IG.Neural.Applications.TadejFormOld.label5, IG.Neural.Applications.TadejFormOld.labEpoch, IG.Neural.Applications.TadejFormOld.labHiddenLayer, IG.Neural.Applications.TadejFormOld.labInputParamSmooth, IG.Neural.Applications.TadejFormOld.labLearningRate, IG.Neural.Applications.TadejFormOld.labMaxEpoch, IG.Neural.Applications.TadejFormOld.labMomentum, IG.Neural.Applications.TadejFormOld.labMultipleNetwork, IG.Neural.Applications.TadejFormOld.labNumVerifPoints, IG.Neural.Applications.TadejFormOld.labNumVerifPoints_, IG.Neural.Applications.TadejFormOld.labOutputValSmooth, IG.Neural.Applications.TadejFormOld.labSaveNet1, IG.Neural.Applications.TadejFormOld.labSaveNet2, IG.Neural.Applications.TadejFormOld.labStandardDev, IG.Neural.Applications.TadejFormOld.labTollerance, IG.Neural.Applications.TadejFormOld.labTrainPairsSmooth, IG.Neural.Applications.TadejFormOld.labUniqueInbput, IG.Neural.Applications.TadejFormOld.labUniqueOutput, IG.Neural.Applications.TadejFormOld.labZeroData, IG.Neural.Applications.TadejFormOld.numAlphaValue, IG.Neural.Applications.TadejFormOld.numAlphaValue_ValueChanged(), IG.Neural.Applications.TadejFormOld.numEpochinBoundle, IG.Neural.Applications.TadejFormOld.numEpochinBoundle_ValueChanged(), IG.Neural.Applications.TadejFormOld.numHiddenLayer1, IG.Neural.Applications.TadejFormOld.numHiddenLayer1_ValueChanged(), IG.Neural.Applications.TadejFormOld.numHiddenLayer2, IG.Neural.Applications.TadejFormOld.numHiddenLayer2_ValueChanged(), IG.Neural.Applications.TadejFormOld.numHiddenLayer3, IG.Neural.Applications.TadejFormOld.numHiddenLayer3_ValueChanged(), IG.Neural.Applications.TadejFormOld.numLearningRate, IG.Neural.Applications.TadejFormOld.numLearningRate_ValueChanged(), IG.Neural.Applications.TadejFormOld.numMaxEpoch, IG.Neural.Applications.TadejFormOld.numMaxEpoch_ValueChanged(), IG.Neural.Applications.TadejFormOld.numMomentum, IG.Neural.Applications.TadejFormOld.numMomentum_ValueChanged(), IG.Neural.Applications.TadejFormOld.numStandardDev, IG.Neural.Applications.TadejFormOld.numStandardDev_ValueChanged(), IG.Neural.Applications.TadejFormOld.numTolerance, IG.Neural.Applications.TadejFormOld.numTolerance_ValueChanged(), IG.Neural.Applications.TadejFormOld.numVerifPoints, IG.Neural.Applications.TadejFormOld.numVerifPoints_ValueChanged(), IG.Neural.Applications.TadejFormOld.openFD, IG.Neural.Applications.TadejFormOld.progressBarTraining, IG.Neural.Applications.TadejFormOld.tbInputPar, IG.Neural.Applications.TadejFormOld.tbInputParSmooth, IG.Neural.Applications.TadejFormOld.tbLoad, IG.Neural.Applications.TadejFormOld.tbOutputVal, IG.Neural.Applications.TadejFormOld.tbOutputValSmooth, IG.Neural.Applications.TadejFormOld.tbSavePath, IG.Neural.Applications.TadejFormOld.tbTrainingTime, IG.Neural.Applications.TadejFormOld.tbTrainPairs, IG.Neural.Applications.TadejFormOld.tbTrainPairsSmooth, IG.Neural.Applications.TadejFormOld.tBxSavedNameDat, IG.Neural.Applications.TadejFormOld.tBxSavedNameDat_TextChanged(), IG.Neural.Applications.TadejFormOld.tBxSavedNameJson, and IG.Neural.Applications.TadejFormOld.tBxSavedNameJson_TextChanged().
Member Data Documentation
trainingData
SampledDataSet IG.Neural.Applications.TadejFormOld.trainingData = null
Referenced by IG.Neural.Applications.formLoadCSV.btnLoadCSV_Click(), IG.Neural.Applications.TadejFormOld.btnLoadTrainCSV_Click(), IG.Neural.Applications.TadejFormOld.btnLoadTrainJSON_Click(), IG.Neural.Applications.TadejFormOld.btResetTrainingData_Click(), IG.Neural.Applications.TadejFormOld.btTestSmooth_Click(), IG.Neural.Applications.TadejFormOld.testSmooth(), and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
definitionData
InputOutputDataDefiniton IG.Neural.Applications.TadejFormOld.definitionData = null
Referenced by IG.Neural.Applications.formLoadCSV.btnLoadCSV_Click().
filePathSave
string IG.Neural.Applications.TadejFormOld.filePathSave = @"../../testdata/LoadTrainingFile/" protected
Referenced by IG.Neural.Applications.TadejFormOld.btSelectSaveNetworkPath_Click(), IG.Neural.Applications.TadejFormOld.cBxSaveNet_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
savedNetwNameJson
string IG.Neural.Applications.TadejFormOld.savedNetwNameJson = "Network" protected
Referenced by IG.Neural.Applications.TadejFormOld.tBxSavedNameJson_TextChanged().
savedNetwNameDat
string IG.Neural.Applications.TadejFormOld.savedNetwNameDat = "Network" protected
Referenced by IG.Neural.Applications.TadejFormOld.tBxSavedNameDat_TextChanged().
multipleNetwork
bool IG.Neural.Applications.TadejFormOld.multipleNetwork = true protected
Referenced by IG.Neural.Applications.TadejFormOld.cBxMultipleNetwork_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
uniqueOutput
bool IG.Neural.Applications.TadejFormOld.uniqueOutput = false protected
Referenced by IG.Neural.Applications.TadejFormOld.btTestSmooth_Click(), IG.Neural.Applications.TadejFormOld.cbxUniqueOutput_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
uniqueInput
bool IG.Neural.Applications.TadejFormOld.uniqueInput = false protected
Referenced by IG.Neural.Applications.TadejFormOld.btTestSmooth_Click(), IG.Neural.Applications.TadejFormOld.cbxUniqueInput_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
zrtoData
bool IG.Neural.Applications.TadejFormOld.zrtoData = false protected
Referenced by IG.Neural.Applications.TadejFormOld.btTestSmooth_Click(), IG.Neural.Applications.TadejFormOld.cbxZeroData_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
numHiddenLayers
int IG.Neural.Applications.TadejFormOld.numHiddenLayers = 0 protected
Referenced by IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
hiddenLayer1
int IG.Neural.Applications.TadejFormOld.hiddenLayer1 = 40 protected
Referenced by IG.Neural.Applications.TadejFormOld.numHiddenLayer1_ValueChanged(), and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
hiddenLayer2
int IG.Neural.Applications.TadejFormOld.hiddenLayer2 = 0 protected
Referenced by IG.Neural.Applications.TadejFormOld.numHiddenLayer2_ValueChanged(), and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
hiddenLayer3
int IG.Neural.Applications.TadejFormOld.hiddenLayer3 = 0 protected
Referenced by IG.Neural.Applications.TadejFormOld.numHiddenLayer3_ValueChanged(), and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
maxEpoch
int IG.Neural.Applications.TadejFormOld.maxEpoch = 5000 protected
Referenced by IG.Neural.Applications.TadejFormOld.backgroundWorker1_DoWork(), IG.Neural.Applications.TadejFormOld.backgroundWorker1_ProgressChanged(), IG.Neural.Applications.TadejFormOld.numMaxEpoch_ValueChanged(), and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
epochInBoundle
int IG.Neural.Applications.TadejFormOld.epochInBoundle = 500 protected
Referenced by IG.Neural.Applications.TadejFormOld.backgroundWorker1_DoWork(), IG.Neural.Applications.TadejFormOld.backgroundWorker1_ProgressChanged(), IG.Neural.Applications.TadejFormOld.numEpochinBoundle_ValueChanged(), and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
toleranceRMS
double IG.Neural.Applications.TadejFormOld.toleranceRMS = 0.1 protected
Referenced by IG.Neural.Applications.TadejFormOld.numTolerance_ValueChanged(), and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
learningRate
double IG.Neural.Applications.TadejFormOld.learningRate = 0.03 protected
Referenced by IG.Neural.Applications.TadejFormOld.numLearningRate_ValueChanged(), and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
alphaValue
double IG.Neural.Applications.TadejFormOld.alphaValue = 2.0 protected
Referenced by IG.Neural.Applications.TadejFormOld.numAlphaValue_ValueChanged(), and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
momentum
double IG.Neural.Applications.TadejFormOld.momentum = 0.6 protected
Referenced by IG.Neural.Applications.TadejFormOld.numMomentum_ValueChanged(), and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
verifPointsPercent
double IG.Neural.Applications.TadejFormOld.verifPointsPercent = 0.2 protected
Referenced by IG.Neural.Applications.TadejFormOld.cbxVerifPoints_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.numVerifPoints_ValueChanged().
standDeviation
double IG.Neural.Applications.TadejFormOld.standDeviation = 0.0 protected
Referenced by IG.Neural.Applications.TadejFormOld.btTestSmooth_Click(), IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), IG.Neural.Applications.TadejFormOld.numStandardDev_ValueChanged(), and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
breakTrainingFlag
bool IG.Neural.Applications.TadejFormOld.breakTrainingFlag = false protected
Referenced by IG.Neural.Applications.TadejFormOld.backgroundWorker1_DoWork(), and IG.Neural.Applications.TadejFormOld.btStopTraining_Click().
components
System ComponentModel IContainer IG.Neural.Applications.TadejFormOld.components = null private
Required designer variable.
Referenced by IG.Neural.Applications.TadejFormOld.Dispose().
openFD
System Windows Forms OpenFileDialog IG.Neural.Applications.TadejFormOld.openFD private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
btnPredictSave
System Windows Forms Button IG.Neural.Applications.TadejFormOld.btnPredictSave private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
numLearningRate
System Windows Forms NumericUpDown IG.Neural.Applications.TadejFormOld.numLearningRate private
Referenced by IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), and IG.Neural.Applications.TadejFormOld.numLearningRate_ValueChanged().
numTolerance
System Windows Forms NumericUpDown IG.Neural.Applications.TadejFormOld.numTolerance private
Referenced by IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), and IG.Neural.Applications.TadejFormOld.numTolerance_ValueChanged().
labLearningRate
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labLearningRate private
Referenced by IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
numEpochinBoundle
System Windows Forms NumericUpDown IG.Neural.Applications.TadejFormOld.numEpochinBoundle private
Referenced by IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), and IG.Neural.Applications.TadejFormOld.numEpochinBoundle_ValueChanged().
numAlphaValue
System Windows Forms NumericUpDown IG.Neural.Applications.TadejFormOld.numAlphaValue private
Referenced by IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), and IG.Neural.Applications.TadejFormOld.numAlphaValue_ValueChanged().
groupBox2
System Windows Forms GroupBox IG.Neural.Applications.TadejFormOld.groupBox2 private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
labMultipleNetwork
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labMultipleNetwork private
Referenced by IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
cBxMultipleNetwork
System Windows Forms CheckBox IG.Neural.Applications.TadejFormOld.cBxMultipleNetwork private
Referenced by IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), IG.Neural.Applications.TadejFormOld.cBxMultipleNetwork_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
numHiddenLayer3
System Windows Forms NumericUpDown IG.Neural.Applications.TadejFormOld.numHiddenLayer3 private
Referenced by IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), and IG.Neural.Applications.TadejFormOld.numHiddenLayer3_ValueChanged().
numMomentum
System Windows Forms NumericUpDown IG.Neural.Applications.TadejFormOld.numMomentum private
Referenced by IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), and IG.Neural.Applications.TadejFormOld.numMomentum_ValueChanged().
numHiddenLayer2
System Windows Forms NumericUpDown IG.Neural.Applications.TadejFormOld.numHiddenLayer2 private
Referenced by IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), and IG.Neural.Applications.TadejFormOld.numHiddenLayer2_ValueChanged().
numMaxEpoch
System Windows Forms NumericUpDown IG.Neural.Applications.TadejFormOld.numMaxEpoch private
Referenced by IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), and IG.Neural.Applications.TadejFormOld.numMaxEpoch_ValueChanged().
numHiddenLayer1
System Windows Forms NumericUpDown IG.Neural.Applications.TadejFormOld.numHiddenLayer1 private
Referenced by IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), and IG.Neural.Applications.TadejFormOld.numHiddenLayer1_ValueChanged().
labMaxEpoch
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labMaxEpoch private
Referenced by IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
labAlphaValue
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labAlphaValue private
Referenced by IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
labHiddenLayer
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labHiddenLayer private
Referenced by IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
labEpoch
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labEpoch private
Referenced by IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
labTollerance
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labTollerance private
Referenced by IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
labMomentum
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labMomentum private
Referenced by IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
folderBrouseSaveNetwork
System Windows Forms FolderBrowserDialog IG.Neural.Applications.TadejFormOld.folderBrouseSaveNetwork private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
groupBox5
System Windows Forms GroupBox IG.Neural.Applications.TadejFormOld.groupBox5 private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
tbLoad
System Windows Forms TextBox IG.Neural.Applications.TadejFormOld.tbLoad
Referenced by IG.Neural.Applications.TadejFormOld.backgroundWorker1_RunWorkerCompleted(), IG.Neural.Applications.TadejFormOld.btnLoadTrainCSV_Click(), IG.Neural.Applications.TadejFormOld.btnLoadTrainJSON_Click(), IG.Neural.Applications.TadejFormOld.btResetTrainingData_Click(), IG.Neural.Applications.TadejFormOld.btStartTrain_Click(), IG.Neural.Applications.TadejFormOld.cBxSaveNet_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), and IG.Neural.Applications.TadejFormOld.numStandardDev_ValueChanged().
btnLoadTrainJSON
System Windows Forms Button IG.Neural.Applications.TadejFormOld.btnLoadTrainJSON private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
btnLoadTrainCSV
System Windows Forms Button IG.Neural.Applications.TadejFormOld.btnLoadTrainCSV private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
btResetTrainingData
System Windows Forms Button IG.Neural.Applications.TadejFormOld.btResetTrainingData private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
gbLoad
System Windows Forms GroupBox IG.Neural.Applications.TadejFormOld.gbLoad private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
gbSmooth
System Windows Forms GroupBox IG.Neural.Applications.TadejFormOld.gbSmooth private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
numStandardDev
System Windows Forms NumericUpDown IG.Neural.Applications.TadejFormOld.numStandardDev private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), and IG.Neural.Applications.TadejFormOld.numStandardDev_ValueChanged().
labStandardDev
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labStandardDev private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
label1
System Windows Forms Label IG.Neural.Applications.TadejFormOld.label1 private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
cBxSmoothData
System Windows Forms CheckBox IG.Neural.Applications.TadejFormOld.cBxSmoothData private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), IG.Neural.Applications.TadejFormOld.numStandardDev_ValueChanged(), and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
btStartTrain
System Windows Forms Button IG.Neural.Applications.TadejFormOld.btStartTrain
Referenced by IG.Neural.Applications.TadejFormOld.backgroundWorker1_RunWorkerCompleted(), IG.Neural.Applications.TadejFormOld.btnLoadTrainCSV_Click(), IG.Neural.Applications.TadejFormOld.btStartTrain_Click(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
label4
System Windows Forms Label IG.Neural.Applications.TadejFormOld.label4 private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
btStopTraining
System Windows Forms Button IG.Neural.Applications.TadejFormOld.btStopTraining private
Referenced by IG.Neural.Applications.TadejFormOld.backgroundWorker1_RunWorkerCompleted(), IG.Neural.Applications.TadejFormOld.btStartTrain_Click(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
groupBox4
System Windows Forms GroupBox IG.Neural.Applications.TadejFormOld.groupBox4 private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
cbNeuralNetworkType
System Windows Forms ComboBox IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType private
Referenced by IG.Neural.Applications.TadejFormOld.cbNeuralNetworkType_SelectedIndexChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
label5
System Windows Forms Label IG.Neural.Applications.TadejFormOld.label5 private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
groupBox1
System Windows Forms GroupBox IG.Neural.Applications.TadejFormOld.groupBox1 private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
labNumVerifPoints_
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labNumVerifPoints_ private
Referenced by IG.Neural.Applications.TadejFormOld.cbxVerifPoints_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
numVerifPoints
System Windows Forms NumericUpDown IG.Neural.Applications.TadejFormOld.numVerifPoints private
Referenced by IG.Neural.Applications.TadejFormOld.cbxVerifPoints_CheckedChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), and IG.Neural.Applications.TadejFormOld.numVerifPoints_ValueChanged().
labNumVerifPoints
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labNumVerifPoints private
Referenced by IG.Neural.Applications.TadejFormOld.cbxVerifPoints_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
cbxVerifPoints
System Windows Forms CheckBox IG.Neural.Applications.TadejFormOld.cbxVerifPoints private
Referenced by IG.Neural.Applications.TadejFormOld.cbxVerifPoints_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
label14
System Windows Forms Label IG.Neural.Applications.TadejFormOld.label14 private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
groupBox3
System Windows Forms GroupBox IG.Neural.Applications.TadejFormOld.groupBox3 private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
gbSaveNet
System Windows Forms GroupBox IG.Neural.Applications.TadejFormOld.gbSaveNet private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSaveNet_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
tbSavePath
System Windows Forms TextBox IG.Neural.Applications.TadejFormOld.tbSavePath private
Referenced by IG.Neural.Applications.TadejFormOld.btSelectSaveNetworkPath_Click(), IG.Neural.Applications.TadejFormOld.cBxSaveNet_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
labSaveNet2
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labSaveNet2 private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSaveNet_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
tBxSavedNameJson
System Windows Forms TextBox IG.Neural.Applications.TadejFormOld.tBxSavedNameJson private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSaveNet_CheckedChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), IG.Neural.Applications.TadejFormOld.tBxSavedNameJson_TextChanged(), and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
tBxSavedNameDat
System Windows Forms TextBox IG.Neural.Applications.TadejFormOld.tBxSavedNameDat private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSaveNet_CheckedChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), IG.Neural.Applications.TadejFormOld.tBxSavedNameDat_TextChanged(), and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
labSaveNet1
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labSaveNet1 private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSaveNet_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
gbTrainSave
System Windows Forms GroupBox IG.Neural.Applications.TadejFormOld.gbTrainSave private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
cBxSaveNet
System Windows Forms CheckBox IG.Neural.Applications.TadejFormOld.cBxSaveNet private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSaveNet_CheckedChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), and IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork().
label3
System Windows Forms Label IG.Neural.Applications.TadejFormOld.label3 private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
btSelectSaveNetworkPath
System Windows Forms Button IG.Neural.Applications.TadejFormOld.btSelectSaveNetworkPath private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSaveNet_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
btnExit
System Windows Forms Button IG.Neural.Applications.TadejFormOld.btnExit private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
btTestSmooth
System Windows Forms Button IG.Neural.Applications.TadejFormOld.btTestSmooth private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
tbTrainPairs
System Windows Forms TextBox IG.Neural.Applications.TadejFormOld.tbTrainPairs private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), and IG.Neural.Applications.TadejFormOld.testSmooth().
tbOutputVal
System Windows Forms TextBox IG.Neural.Applications.TadejFormOld.tbOutputVal private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), and IG.Neural.Applications.TadejFormOld.testSmooth().
tbInputPar
System Windows Forms TextBox IG.Neural.Applications.TadejFormOld.tbInputPar private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), and IG.Neural.Applications.TadejFormOld.testSmooth().
labInputParamSmooth
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labInputParamSmooth private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
labOutputValSmooth
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labOutputValSmooth private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
labTrainPairsSmooth
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labTrainPairsSmooth private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
cbxUniqueOutput
System Windows Forms CheckBox IG.Neural.Applications.TadejFormOld.cbxUniqueOutput private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cbxUniqueOutput_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
cbxUniqueInput
System Windows Forms CheckBox IG.Neural.Applications.TadejFormOld.cbxUniqueInput private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cbxUniqueInput_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
labUniqueOutput
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labUniqueOutput private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
labUniqueInbput
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labUniqueInbput private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
cbxZeroData
System Windows Forms CheckBox IG.Neural.Applications.TadejFormOld.cbxZeroData private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), IG.Neural.Applications.TadejFormOld.cbxZeroData_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
labZeroData
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labZeroData private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
labAfter
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labAfter private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
labBefore
System Windows Forms Label IG.Neural.Applications.TadejFormOld.labBefore private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
tbTrainPairsSmooth
System Windows Forms TextBox IG.Neural.Applications.TadejFormOld.tbTrainPairsSmooth private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), and IG.Neural.Applications.TadejFormOld.testSmooth().
tbOutputValSmooth
System Windows Forms TextBox IG.Neural.Applications.TadejFormOld.tbOutputValSmooth private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), and IG.Neural.Applications.TadejFormOld.testSmooth().
tbInputParSmooth
System Windows Forms TextBox IG.Neural.Applications.TadejFormOld.tbInputParSmooth private
Referenced by IG.Neural.Applications.TadejFormOld.cBxSmoothData_CheckedChanged(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), and IG.Neural.Applications.TadejFormOld.testSmooth().
backgroundWorker1
System ComponentModel BackgroundWorker IG.Neural.Applications.TadejFormOld.backgroundWorker1
Referenced by IG.Neural.Applications.TadejFormOld.btStartTrain_Click(), IG.Neural.Applications.TadejFormOld.InitializeComponent(), and IG.Neural.Applications.TadejFormOld.TadejFormOld().
tbTrainingTime
System Windows Forms TextBox IG.Neural.Applications.TadejFormOld.tbTrainingTime private
Referenced by IG.Neural.Applications.TadejFormOld.backgroundWorker1_ProgressChanged(), IG.Neural.Applications.TadejFormOld.btResetTrainingData_Click(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
progressBarTraining
System Windows Forms ProgressBar IG.Neural.Applications.TadejFormOld.progressBarTraining private
Referenced by IG.Neural.Applications.TadejFormOld.backgroundWorker1_ProgressChanged(), IG.Neural.Applications.TadejFormOld.btResetTrainingData_Click(), and IG.Neural.Applications.TadejFormOld.InitializeComponent().
label2
System Windows Forms Label IG.Neural.Applications.TadejFormOld.label2 private
Referenced by IG.Neural.Applications.TadejFormOld.InitializeComponent().
Property Documentation
btStartVisible
Boolean IG.Neural.Applications.TadejFormOld.btStartVisible get set
Referenced by IG.Neural.Applications.TadejFormOld.btnLoadTrainJSON_Click(), and IG.Neural.Applications.TadejFormOld.btResetTrainingData_Click().
The documentation for this class was generated from the following files:
shelldev/lib/extended/LibNeuralExtForms/FormsExperimental/NeuralApplications/TadejFormOld/TadejForm.cs
shelldev/lib/extended/LibNeuralExtForms/FormsExperimental/NeuralApplications/TadejFormOld/TadejForm.designer.cs