Doc: IGLib EXTENDED: CShell.Framework.Services.IRepl Interface Reference
CShell.Framework.Services.IRepl Interface Reference
Public Member Functions
void Clear ()
void SuppressWarning (string warningCode)
void ShowWarning (string warningCode)
Properties
bool IsEvaluating [get]
IEnumerable< string > SuppressedWarnings [get]
bool ShowConsoleOutput [get, set]
string Font [get, set]
double FontSize [get, set]
Color BackgroundColor [get, set]
Color OutputColor [get, set]
Color WarningColor [get, set]
Color ErrorColor [get, set]
Color ReplColor [get, set]
Member Function Documentation
Clear()
void CShell.Framework.Services.IRepl.Clear ()
Implemented in CShell.Modules.Repl.Controls.CSRepl, and CShell.Modules.Repl.ViewModels.ReplViewModel.
Referenced by CShell.Modules.Repl.ViewModels.ReplViewModel.Clear().
SuppressWarning()
void CShell.Framework.Services.IRepl.SuppressWarning (string warningCode)
Implemented in CShell.Modules.Repl.Controls.CSRepl, and CShell.Modules.Repl.ViewModels.ReplViewModel.
Referenced by CShell.Modules.Repl.ViewModels.ReplViewModel.SuppressWarning().
ShowWarning()
void CShell.Framework.Services.IRepl.ShowWarning (string warningCode)
Implemented in CShell.Modules.Repl.Controls.CSRepl, and CShell.Modules.Repl.ViewModels.ReplViewModel.
Referenced by CShell.Modules.Repl.ViewModels.ReplViewModel.ShowWarning().
Property Documentation
IsEvaluating
bool CShell.Framework.Services.IRepl.IsEvaluating get
Referenced by CShell.Modules.Repl.ViewModels.ReplViewModel.TimerOnElapsed().
SuppressedWarnings
IEnumerable<string> CShell.Framework.Services.IRepl.SuppressedWarnings get
ShowConsoleOutput
bool CShell.Framework.Services.IRepl.ShowConsoleOutput get set
Font
string CShell.Framework.Services.IRepl.Font get set
FontSize
double CShell.Framework.Services.IRepl.FontSize get set
BackgroundColor
Color CShell.Framework.Services.IRepl.BackgroundColor get set
OutputColor
Color CShell.Framework.Services.IRepl.OutputColor get set
WarningColor
Color CShell.Framework.Services.IRepl.WarningColor get set
ErrorColor
Color CShell.Framework.Services.IRepl.ErrorColor get set
ReplColor
Color CShell.Framework.Services.IRepl.ReplColor get set
The documentation for this interface was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore/Framework/Services/IRepl.cs