Doc: IGLib EXTENDED: NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality Class Reference
NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality Class Reference
Public Member Functions
void CanMatchDates ()
void CanMatchDatesWithinTimeSpan ()
void CanMatchDatesWithinDays ()
void CanMatchUsingIsEqualToWithinTimeSpan ()
void CanMatchDatesWithinMinutes ()
void CanMatchDatesWithinSeconds ()
void CanMatchDatesWithinMilliseconds ()
void CanMatchDatesWithinTicks ()
void DTimeOffsetCanMatchDatesWithinHours ()
Member Function Documentation
CanMatchDates()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality.CanMatchDates () inline
References NUnit.Framework.Assert.That().
CanMatchDatesWithinTimeSpan()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality.CanMatchDatesWithinTimeSpan () inline
References NUnit.Framework.Assert.That().
CanMatchDatesWithinDays()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality.CanMatchDatesWithinDays () inline
References NUnit.Framework.Assert.That().
CanMatchUsingIsEqualToWithinTimeSpan()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality.CanMatchUsingIsEqualToWithinTimeSpan () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
CanMatchDatesWithinMinutes()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality.CanMatchDatesWithinMinutes () inline
References NUnit.Framework.Assert.That().
CanMatchDatesWithinSeconds()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality.CanMatchDatesWithinSeconds () inline
References NUnit.Framework.Assert.That().
CanMatchDatesWithinMilliseconds()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality.CanMatchDatesWithinMilliseconds () inline
References NUnit.Framework.Assert.That().
CanMatchDatesWithinTicks()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality.CanMatchDatesWithinTicks () inline
References NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.EqualConstraint.Ticks.
DTimeOffsetCanMatchDatesWithinHours()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffSetEquality.DTimeOffsetCanMatchDatesWithinHours () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/EqualConstraintTests.cs