Doc: IGLib EXTENDED: NUnit.Framework.Internal.TestFilter Class Reference
NUnit.Framework.Internal.TestFilter Class Reference abstract
Interface to be implemented by filters applied to tests. The filter applies when running the test, after it has been loaded, since this is the only time an ITest exists.
Classes
class EmptyFilter
Nested class provides an empty filter - one that always returns true when called. It never matches explicitly.
Public Member Functions
virtual bool Pass (ITest test)
Determine if a particular test passes the filter criteria. The default implementation checks the test itself, its parents and any descendants.
virtual bool IsExplicitMatch (ITest test)
Determine if a test matches the filter expicitly. That is, it must be a direct match of the test itself or one of it's children.
abstract bool Match (ITest test)
Determine whether the test itself matches the filter criteria, without examining either parents or descendants. This is overridden by each different type of filter to perform the necessary tests.
bool MatchParent (ITest test)
Determine whether any ancestor of the test matches the filter criteria
TNode ToXml (bool recursive)
Adds an XML node
abstract TNode AddToXml (TNode parentNode, bool recursive)
Adds an XML node
Static Public Member Functions
static TestFilter FromXml (string xmlText)
Create a TestFilter instance from an xml representation.
static TestFilter FromXml (TNode node)
Create a TestFilter from it's TNode representation
Static Public Attributes
static readonly TestFilter Empty = new EmptyFilter()
Unique Empty filter.
Protected Member Functions
virtual bool MatchDescendant (ITest test)
Determine whether any descendant of the test matches the filter criteria.
Properties
bool IsEmpty [get]
Indicates whether this is the EmptyFilter
bool TopLevel [get, set]
Indicates whether this is a top-level filter, not contained in any other filter.
Static Private Attributes
static readonly char[] COMMA = new char[] { ',' }
Detailed Description
Interface to be implemented by filters applied to tests. The filter applies when running the test, after it has been loaded, since this is the only time an ITest exists.
Member Function Documentation
Pass()
virtual bool NUnit.Framework.Internal.TestFilter.Pass (ITest test) inline virtual
Determine if a particular test passes the filter criteria. The default implementation checks the test itself, its parents and any descendants.
Derived classes may override this method or any of the Match methods to change the behavior of the filter.
Parameters
test The test to which the filter is applied
Returns
True if the test passes the filter, otherwise false
Implements NUnit.Framework.Interfaces.ITestFilter.
Reimplemented in NUnit.Framework.Internal.TestFilter.EmptyFilter, NUnit.Framework.Internal.Filters.NotFilter, NUnit.Framework.Internal.Filters.AndFilter, and NUnit.Framework.Internal.Filters.OrFilter.
References NUnit.Framework.Internal.TestFilter.Match(), NUnit.Framework.Internal.TestFilter.MatchDescendant(), and NUnit.Framework.Internal.TestFilter.MatchParent().
Referenced by NUnit.Framework.Internal.Filters.CategoryFilterTests.PassTest(), NUnit.Framework.Internal.Filters.IdFilterTests.PassTest(), NUnit.Framework.Internal.Filters.PropertyFilterTests.PassTest(), NUnit.Framework.Internal.Filters.MethodNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.FullNameFilterTests.PassTest(), and NUnit.Framework.Internal.Filters.TestNameFilterTests.PassTest().
IsExplicitMatch()
virtual bool NUnit.Framework.Internal.TestFilter.IsExplicitMatch (ITest test) inline virtual
Determine if a test matches the filter expicitly. That is, it must be a direct match of the test itself or one of it's children.
Parameters
test The test to which the filter is applied
Returns
True if the test matches the filter explicityly, otherwise false
Implements NUnit.Framework.Interfaces.ITestFilter.
Reimplemented in NUnit.Framework.Internal.TestFilter.EmptyFilter, and NUnit.Framework.Internal.Filters.NotFilter.
References NUnit.Framework.Internal.TestFilter.Match(), and NUnit.Framework.Internal.TestFilter.MatchDescendant().
Referenced by NUnit.Framework.Internal.Filters.MethodNameFilterTests.ExplicitMatch_SingleName(), NUnit.Framework.Internal.Filters.FullNameFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.TestNameFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.IdFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.CategoryFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.PropertyFilterTests.ExplicitMatchTest(), and NUnit.Framework.Internal.Filters.EmptyFilterTests.MatchesNothihngExplicitly().
Match()
abstract bool NUnit.Framework.Internal.TestFilter.Match (ITest test) pure virtual
Determine whether the test itself matches the filter criteria, without examining either parents or descendants. This is overridden by each different type of filter to perform the necessary tests.
Parameters
test The test to which the filter is applied
Returns
True if the filter matches the any parent of the test
Implemented in NUnit.Framework.Internal.TestFilter.EmptyFilter, NUnit.Framework.Internal.Filters.NotFilter, NUnit.Framework.Internal.Filters.AndFilter, NUnit.Framework.Internal.Filters.OrFilter, NUnit.Framework.Internal.Filters.PropertyFilter, NUnit.Framework.Internal.Filters.CategoryFilter, NUnit.Framework.Internal.Filters.IdFilter, NUnit.Framework.Internal.Filters.ClassNameFilter, NUnit.Framework.Internal.Filters.FullNameFilter, NUnit.Framework.Internal.Filters.MethodNameFilter, and NUnit.Framework.Internal.Filters.TestNameFilter.
Referenced by NUnit.Framework.Internal.Filters.AndFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.OrFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.NotFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.AndFilterTests.BuildFromXml_TopLevelDefaultsToAnd(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.BuildMethodNameFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.IdFilter_FromXml(), NUnit.Framework.Internal.TestFilter.IsExplicitMatch(), NUnit.Framework.Internal.Filters.OrFilter.Match(), NUnit.Framework.Internal.Filters.AndFilter.Match(), NUnit.Framework.Internal.Filters.NotFilter.Match(), NUnit.Framework.Internal.TestFilter.MatchDescendant(), NUnit.Framework.Internal.Filters.EmptyFilterTests.MatchesAnything(), NUnit.Framework.Internal.TestFilter.MatchParent(), NUnit.Framework.Internal.Filters.IdFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.PropertyFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.CategoryFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.MethodNameFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.TestNameFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.FullNameFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.MethodNameFilter_FromXml(), NUnit.Framework.Internal.Filters.NotFilter.Pass(), NUnit.Framework.Internal.TestFilter.Pass(), NUnit.Framework.Internal.Filters.EmptyFilterTests.PassesAnything(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_FromXml(), and NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_FromXml_Regex().
MatchParent()
bool NUnit.Framework.Internal.TestFilter.MatchParent (ITest test) inline
Determine whether any ancestor of the test matches the filter criteria
Parameters
test The test to which the filter is applied
Returns
True if the filter matches the an ancestor of the test
References NUnit.Framework.Internal.TestFilter.Match(), and NUnit.Framework.Interfaces.ITest.Parent.
Referenced by NUnit.Framework.Internal.Filters.NotFilter.Pass(), and NUnit.Framework.Internal.TestFilter.Pass().
MatchDescendant()
virtual bool NUnit.Framework.Internal.TestFilter.MatchDescendant (ITest test) inline protected virtual
Determine whether any descendant of the test matches the filter criteria.
Parameters
test The test to be matched
Returns
True if at least one descendant matches the filter criteria
References NUnit.Framework.Internal.TestFilter.Match(), and NUnit.Framework.Interfaces.ITest.Tests.
Referenced by NUnit.Framework.Internal.TestFilter.IsExplicitMatch(), and NUnit.Framework.Internal.TestFilter.Pass().
FromXml() [1/2]
static TestFilter NUnit.Framework.Internal.TestFilter.FromXml (string xmlText) inline static
Create a TestFilter instance from an xml representation.
References NUnit.Framework.Interfaces.TNode.ChildNodes, NUnit.Framework.Internal.TestFilter.Empty, NUnit.Framework.Interfaces.TNode.FirstChild, NUnit.Framework.Interfaces.TNode.FromXml(), NUnit.Framework.Interfaces.TNode.Name, and NUnit.Framework.Internal.TestFilter.TopLevel.
Referenced by NUnit.Framework.Internal.Filters.EmptyFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.AndFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.OrFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.NotFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.AndFilterTests.BuildFromXml_TopLevelDefaultsToAnd(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.BuildMethodNameFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_FromXml_Regex(), NUnit.Framework.Api.FrameworkController.CountTests(), NUnitLite.TextRunner.CreateTestFilter(), NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.IdFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.MethodNameFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_FromXml_Regex(), NUnit.Framework.Api.FrameworkController.RunAsync(), NUnit.Framework.Api.FrameworkController.RunTests(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_FromXml(), and NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_FromXml_Regex().
FromXml() [2/2]
static TestFilter NUnit.Framework.Internal.TestFilter.FromXml (TNode node) inline static
Create a TestFilter from it's TNode representation
References NUnit.Framework.Interfaces.TNode.Attributes, NUnit.Framework.Interfaces.TNode.ChildNodes, NUnit.Framework.Interfaces.TNode.FirstChild, NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Interfaces.TNode.Name, and NUnit.Framework.Interfaces.TNode.Value.
ToXml()
TNode NUnit.Framework.Internal.TestFilter.ToXml (bool recursive) inline
Adds an XML node
Parameters
recursive True if recursive
Returns
The added XML node
Implements NUnit.Framework.Interfaces.IXmlNodeBuilder.
References NUnit.Framework.Internal.TestFilter.AddToXml().
Referenced by NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_ToXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_ToXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_ToXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_ToXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_ToXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_ToXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.IdFilter_ToXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.MethodNameFilter_ToXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.MethodNameFilter_ToXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_ToXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_ToXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_ToXml(), and NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_ToXml_Regex().
AddToXml()
abstract TNode NUnit.Framework.Internal.TestFilter.AddToXml (TNode parentNode, bool recursive) pure virtual
Adds an XML node
Parameters
parentNode Parent node
recursive True if recursive
Returns
The added XML node
Implements NUnit.Framework.Interfaces.IXmlNodeBuilder.
Implemented in NUnit.Framework.Internal.TestFilter.EmptyFilter, NUnit.Framework.Internal.Filters.NotFilter, NUnit.Framework.Internal.Filters.ValueMatchFilter, NUnit.Framework.Internal.Filters.PropertyFilter, and NUnit.Framework.Internal.Filters.CompositeFilter.
Referenced by NUnit.Framework.Internal.Filters.NotFilter.AddToXml(), NUnitLite.NUnit3XmlOutputWriter.MakeTestFilterElement(), and NUnit.Framework.Internal.TestFilter.ToXml().
Member Data Documentation
Empty
readonly TestFilter NUnit.Framework.Internal.TestFilter.Empty = new EmptyFilter() static
Unique Empty filter.
Referenced by NUnit.Framework.Api.TestAssemblyRunnerTests.CancelRun_WhenTestIsRunning_StopsTest(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_AfterLoad_ReturnsCorrectCount(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_BadFile_ReturnsZero(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_FileNotFound_ReturnsZero(), NUnit.Framework.Api.TestAssemblyRunnerTests.CountTestCases_WithoutLoad_ThrowsInvalidOperation(), NUnitLite.TextRunner.CreateTestFilter(), NUnitLite.TextRunner.Execute(), NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Internal.Filters.EmptyFilterTests.IsEmpty(), NUnit.Framework.Internal.Filters.EmptyFilterTests.MatchesAnything(), NUnit.Framework.Internal.Filters.EmptyFilterTests.MatchesNothihngExplicitly(), NUnit.Framework.Internal.Filters.EmptyFilterTests.PassesAnything(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.Run_WithoutLoad_ReturnsError(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_ReturnsRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_AfterLoad_SendsExpectedEvents(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.TestAssemblyRunnerTests.RunAsync_WithoutLoad_ReturnsError(), NUnit.TestUtilities.TestBuilder.RunTest(), NUnit.Framework.Internal.SetUpFixtureTests.runTests(), NUnit.TestUtilities.TestBuilder.RunTestSuite(), NUnit.Framework.Tests.ActionAttributeTests.Setup(), NUnit.Framework.Api.TestAssemblyRunnerTests.StopRun_WhenTestIsRunning_StopsTest(), and NUnitLite.Tests.CreateTestFilterTests.TestListFileMissing().
COMMA
readonly char [] NUnit.Framework.Internal.TestFilter.COMMA = new char[] { ',' } static private
Property Documentation
IsEmpty
bool NUnit.Framework.Internal.TestFilter.IsEmpty get
Indicates whether this is the EmptyFilter
Referenced by NUnit.Framework.Internal.Filters.EmptyFilterTests.BuildFromXml(), NUnitLite.TextRunner.CreateTestFilter(), NUnit.Framework.Internal.Filters.EmptyFilterTests.IsEmpty(), NUnit.Framework.Internal.Filters.IdFilterTests.IsNotEmpty(), NUnit.Framework.Internal.Filters.PropertyFilterTests.IsNotEmpty(), NUnit.Framework.Internal.Filters.CategoryFilterTests.IsNotEmpty(), NUnit.Framework.Internal.Filters.TestNameFilterTests.IsNotEmpty(), NUnit.Framework.Internal.Filters.MethodNameFilterTests.IsNotEmpty(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.IsNotEmpty(), NUnit.Framework.Internal.Filters.FullNameFilterTests.IsNotEmpty(), and NUnitLite.NUnit3XmlOutputWriter.MakeTestFilterElement().
TopLevel
bool NUnit.Framework.Internal.TestFilter.TopLevel get set
Indicates whether this is a top-level filter, not contained in any other filter.
Referenced by NUnit.Framework.Internal.TestFilter.FromXml().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/TestFilter.cs