Doc: IGLib EXTENDED: alglib.odesolver Class Reference
alglib.odesolver Class Reference
Classes
class odesolverreport
class odesolverstate
Static Public Member Functions
static void odesolverrkck (double[] y, int n, double[] x, int m, double eps, double h, odesolverstate state)
static bool odesolveriteration (odesolverstate state)
static void odesolverresults (odesolverstate state, ref int m, ref double[] xtbl, ref double[,] ytbl, odesolverreport rep)
static void odesolverrkck (double[] y, int n, double[] x, int m, double eps, double h, odesolverstate state)
static bool odesolveriteration (odesolverstate state)
static void odesolverresults (odesolverstate state, ref int m, ref double[] xtbl, ref double[,] ytbl, odesolverreport rep)
Static Public Attributes
const double odesolvermaxgrow = 3.0
const double odesolvermaxshrink = 10.0
Static Private Member Functions
static void odesolverinit (int solvertype, double[] y, int n, double[] x, int m, double eps, double h, odesolverstate state)
static void odesolverinit (int solvertype, double[] y, int n, double[] x, int m, double eps, double h, odesolverstate state)
Member Function Documentation
odesolverrkck() [1/2]
static void alglib.odesolver.odesolverrkck (double[] y, int n, double[] x, int m, double eps, double h, odesolverstate state) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), and alglib.odesolver.odesolverinit().
Referenced by alglib.odesolverrkck(), and alglib.testodesolverunit.testodesolver().
odesolveriteration() [1/2]
static bool alglib.odesolver.odesolveriteration (odesolverstate state) inline static
References alglib.ap.assert(), alglib.rcommstate.ba, alglib.odesolver.odesolverstate.dy, alglib.odesolver.odesolverstate.eps, alglib.odesolver.odesolverstate.escale, alglib.odesolver.odesolverstate.fraceps, alglib.odesolver.odesolverstate.h, alglib.rcommstate.ia, alglib.odesolver.odesolverstate.m, alglib.odesolver.odesolverstate.n, alglib.odesolver.odesolverstate.needdy, alglib.odesolver.odesolvermaxgrow, alglib.odesolver.odesolvermaxshrink, alglib.rcommstate.ra, alglib.odesolver.odesolverstate.repnfev, alglib.odesolver.odesolverstate.repterminationtype, alglib.odesolver.odesolverstate.rka, alglib.odesolver.odesolverstate.rkb, alglib.odesolver.odesolverstate.rkc, alglib.odesolver.odesolverstate.rkcs, alglib.odesolver.odesolverstate.rkk, alglib.odesolver.odesolverstate.rstate, alglib.odesolver.odesolverstate.solvertype, alglib.rcommstate.stage, alglib.odesolver.odesolverstate.x, alglib.odesolver.odesolverstate.xg, alglib.odesolver.odesolverstate.xscale, alglib.odesolver.odesolverstate.y, alglib.odesolver.odesolverstate.yc, alglib.odesolver.odesolverstate.yn, alglib.odesolver.odesolverstate.yns, and alglib.odesolver.odesolverstate.ytbl.
Referenced by alglib.odesolveriteration(), and alglib.testodesolverunit.testodesolver().
odesolverresults() [1/2]
static void alglib.odesolver.odesolverresults (odesolverstate state, ref int m, ref double[] xtbl, ref double ytbl[,], odesolverreport rep) inline static
References alglib.odesolver.odesolverstate.m, alglib.odesolver.odesolverstate.n, alglib.odesolver.odesolverreport.nfev, alglib.odesolver.odesolverstate.repnfev, alglib.odesolver.odesolverstate.repterminationtype, alglib.odesolver.odesolverreport.terminationtype, alglib.odesolver.odesolverstate.xg, alglib.odesolver.odesolverstate.xscale, and alglib.odesolver.odesolverstate.ytbl.
Referenced by alglib.odesolverresults(), and alglib.testodesolverunit.testodesolver().
odesolverinit() [1/2]
static void alglib.odesolver.odesolverinit (int solvertype, double[] y, int n, double[] x, int m, double eps, double h, odesolverstate state) inline static private
References alglib.rcommstate.ba, alglib.odesolver.odesolverstate.dy, alglib.odesolver.odesolverstate.eps, alglib.odesolver.odesolverstate.fraceps, alglib.odesolver.odesolverstate.h, alglib.rcommstate.ia, alglib.odesolver.odesolverstate.m, alglib.odesolver.odesolverstate.n, alglib.odesolver.odesolverstate.needdy, alglib.rcommstate.ra, alglib.odesolver.odesolverstate.repnfev, alglib.odesolver.odesolverstate.repterminationtype, alglib.odesolver.odesolverstate.rstate, alglib.odesolver.odesolverstate.solvertype, alglib.rcommstate.stage, alglib.odesolver.odesolverstate.xg, alglib.odesolver.odesolverstate.xscale, alglib.odesolver.odesolverstate.y, alglib.odesolver.odesolverstate.yc, and alglib.odesolver.odesolverstate.ytbl.
Referenced by alglib.odesolver.odesolverrkck().
odesolverrkck() [2/2]
static void alglib.odesolver.odesolverrkck (double[] y, int n, double[] x, int m, double eps, double h, odesolverstate state) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), and alglib.odesolver.odesolverinit().
odesolveriteration() [2/2]
static bool alglib.odesolver.odesolveriteration (odesolverstate state) inline static
References alglib.ap.assert(), alglib.odesolver.odesolvermaxgrow, and alglib.odesolver.odesolvermaxshrink.
odesolverresults() [2/2]
static void alglib.odesolver.odesolverresults (odesolverstate state, ref int m, ref double[] xtbl, ref double ytbl[,], odesolverreport rep) inline static
odesolverinit() [2/2]
static void alglib.odesolver.odesolverinit (int solvertype, double[] y, int n, double[] x, int m, double eps, double h, odesolverstate state) inline static private
Member Data Documentation
odesolvermaxgrow
const double alglib.odesolver.odesolvermaxgrow = 3.0 static
Referenced by alglib.odesolver.odesolveriteration().
odesolvermaxshrink
const double alglib.odesolver.odesolvermaxshrink = 10.0 static
Referenced by alglib.odesolver.odesolveriteration().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/diffequations.cs