Doc: IGLib EXTENDED: AForge.Imaging.BlobCounterBase Class Reference
AForge.Imaging.BlobCounterBase Class Reference abstract
Base class for different blob counting algorithms.
Classes
class BlobsSorter
Public Member Functions
BlobCounterBase ()
Initializes a new instance of the BlobCounterBase class.
BlobCounterBase (Bitmap image)
Initializes a new instance of the BlobCounterBase class.
BlobCounterBase (BitmapData imageData)
Initializes a new instance of the BlobCounterBase class.
BlobCounterBase (UnmanagedImage image)
Initializes a new instance of the BlobCounterBase class.
void ProcessImage (Bitmap image)
Build objects map.
void ProcessImage (BitmapData imageData)
Build objects map.
void ProcessImage (UnmanagedImage image)
Build object map from raw image data.
Rectangle[] GetObjectsRectangles ()
Get objects' rectangles.
Blob[] GetObjectsInformation ()
Get objects' information.
Blob[] GetObjects (Bitmap image, bool extractInOriginalSize)
Get blobs.
Blob[] GetObjects (UnmanagedImage image, bool extractInOriginalSize)
Get blobs.
void ExtractBlobsImage (Bitmap image, Blob blob, bool extractInOriginalSize)
Extract blob's image.
void ExtractBlobsImage (UnmanagedImage image, Blob blob, bool extractInOriginalSize)
Extract blob's image.
void GetBlobsLeftAndRightEdges (Blob blob, out List< IntPoint > leftEdge, out List< IntPoint > rightEdge)
Get list of points on the left and right edges of the blob.
void GetBlobsTopAndBottomEdges (Blob blob, out List< IntPoint > topEdge, out List< IntPoint > bottomEdge)
Get list of points on the top and bottom edges of the blob.
List< IntPoint > GetBlobsEdgePoints (Blob blob)
Get list of object's edge points.
Protected Member Functions
abstract void BuildObjectsMap (UnmanagedImage image)
Actual objects map building.
Protected Attributes
int objectsCount
Objects count.
int[] objectLabels
Objects' labels.
int imageWidth
Width of processed image.
int imageHeight
Height of processed image.
Properties
int ObjectsCount [get]
Objects count.
int[] ObjectLabels [get]
Objects' labels.
ObjectsOrder ObjectsOrder [get, set]
Objects sort order.
bool FilterBlobs [get, set]
Specifies if blobs should be filtered.
bool CoupledSizeFiltering [get, set]
Specifies if size filetering should be coupled or not.
int MinWidth [get, set]
Minimum allowed width of blob.
int MinHeight [get, set]
Minimum allowed height of blob.
int MaxWidth [get, set]
Maximum allowed width of blob.
int MaxHeight [get, set]
Maximum allowed height of blob.
IBlobsFilter BlobsFilter [get, set]
Custom blobs' filter to use.
Private Member Functions
unsafe void CollectObjectsInfo (UnmanagedImage image)
Private Attributes
List< Blob > blobs = new List<Blob>()
ObjectsOrder objectsOrder = ObjectsOrder.None
bool filterBlobs = false
IBlobsFilter filter = null
bool coupledSizeFiltering = false
int minWidth = 1
int minHeight = 1
int maxWidth = int.MaxValue
int maxHeight = int.MaxValue
Detailed Description
Base class for different blob counting algorithms.
The class is abstract and serves as a base for different blob counting algorithms. Classes, which inherit from this base class, require to implement BuildObjectsMap method, which does actual building of object's label's map.
For blobs' searcing usually all inherited classes accept binary images, which are actually grayscale thresholded images. But the exact supported format should be checked in particular class, inheriting from the base class. For blobs' extraction the class supports grayscale (8 bpp indexed) and color images (24 and 32 bpp).
Sample usage:
// create an instance of blob counter algorithm
BlobCounterBase bc = new ...
// set filtering options
bc.FilterBlobs = true;
bc.MinWidth  = 5;
bc.MinHeight = 5;
// process binary image
bc.ProcessImage(image);
Blob[] blobs = bc.GetObjects(image, false);
// process blobs
foreach (Blob blob in blobs)
{
    // ...
    // blob.Rectangle - blob's rectangle
    // blob.Image - blob's image
}
Constructor & Destructor Documentation
BlobCounterBase() [1/4]
AForge.Imaging.BlobCounterBase.BlobCounterBase () inline
Initializes a new instance of the BlobCounterBase class.
Creates new instance of the BlobCounterBase class with an empty objects map. Before using methods, which provide information about blobs or extract them, the ProcessImage(Bitmap), ProcessImage(BitmapData) or ProcessImage(UnmanagedImage) method should be called to collect objects map.
BlobCounterBase() [2/4]
AForge.Imaging.BlobCounterBase.BlobCounterBase (Bitmap image) inline
Initializes a new instance of the BlobCounterBase class.
Parameters
image Binary image to look for objects in.
Creates new instance of the BlobCounterBase class with initialized objects map built by calling ProcessImage(Bitmap) method.
References AForge.Imaging.BlobCounterBase.ProcessImage().
BlobCounterBase() [3/4]
AForge.Imaging.BlobCounterBase.BlobCounterBase (BitmapData imageData) inline
Initializes a new instance of the BlobCounterBase class.
Parameters
imageData Binary image data to look for objects in.
Creates new instance of the BlobCounterBase class with initialized objects map built by calling ProcessImage(BitmapData) method.
References AForge.Imaging.BlobCounterBase.ProcessImage().
BlobCounterBase() [4/4]
AForge.Imaging.BlobCounterBase.BlobCounterBase (UnmanagedImage image) inline
Initializes a new instance of the BlobCounterBase class.
Parameters
image Unmanaged binary image to look for objects in.
Creates new instance of the BlobCounterBase class with initialized objects map built by calling ProcessImage(UnmanagedImage) method.
References AForge.Imaging.BlobCounterBase.ProcessImage().
Member Function Documentation
ProcessImage() [1/3]
void AForge.Imaging.BlobCounterBase.ProcessImage (Bitmap image) inline
Build objects map.
Parameters
image Source binary image.
Processes the image and builds objects map, which is used later to extracts blobs.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.BlobCounterBase.BlobCounterBase(), IPPrototyperSample.CoinsFinder.Process(), AForge.Imaging.Filters.FillHoles.ProcessFilter(), AForge.Imaging.Filters.ConnectedComponentsLabeling.ProcessFilter(), AForge.Imaging.Filters.BlobsFiltering.ProcessFilter(), AForge.Vision.Motion.BlobCountingObjectsProcessing.ProcessFrame(), ShapeChecker.MainForm.ProcessImage(), AForge.Imaging.BlobCounterBase.ProcessImage(), and BlobsExplorer.BlobsBrowser.SetImage().
ProcessImage() [2/3]
void AForge.Imaging.BlobCounterBase.ProcessImage (BitmapData imageData) inline
Build objects map.
Parameters
imageData Source binary image data.
Processes the image and builds objects map, which is used later to extracts blobs.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Imaging.BlobCounterBase.ProcessImage().
ProcessImage() [3/3]
void AForge.Imaging.BlobCounterBase.ProcessImage (UnmanagedImage image) inline
Build object map from raw image data.
Parameters
image Source unmanaged binary image data.
Processes the image and builds objects map, which is used later to extracts blobs.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
InvalidImagePropertiesException Thrown by some inherited classes if some image property other than the pixel format is not supported. See that class's documentation or the exception message for details.
References AForge.Imaging.BlobCounterBase.blobs, AForge.Imaging.BlobCounterBase.BuildObjectsMap(), AForge.Imaging.IBlobsFilter.Check(), AForge.Imaging.BlobCounterBase.CollectObjectsInfo(), AForge.Imaging.BlobCounterBase.coupledSizeFiltering, AForge.Imaging.BlobCounterBase.filter, AForge.Imaging.BlobCounterBase.filterBlobs, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.BlobCounterBase.imageHeight, AForge.Imaging.BlobCounterBase.imageWidth, AForge.Imaging.BlobCounterBase.maxHeight, AForge.Imaging.BlobCounterBase.maxWidth, AForge.Imaging.BlobCounterBase.minHeight, AForge.Imaging.BlobCounterBase.minWidth, AForge.Imaging.BlobCounterBase.objectLabels, AForge.Imaging.BlobCounterBase.objectsCount, AForge.Imaging.BlobCounterBase.objectsOrder, and AForge.Imaging.UnmanagedImage.Width.
GetObjectsRectangles()
Rectangle [] AForge.Imaging.BlobCounterBase.GetObjectsRectangles () inline
Get objects' rectangles.
Returns
Returns array of objects' rectangles.
The method returns array of objects rectangles. Before calling the method, the ProcessImage(Bitmap), ProcessImage(BitmapData) or ProcessImage(UnmanagedImage) method should be called, which will build objects map.
Exceptions
ApplicationException No image was processed before, so objects' rectangles can not be collected.
References AForge.Imaging.BlobCounterBase.blobs, AForge.Imaging.BlobCounterBase.objectLabels, AForge.Imaging.BlobCounterBase.objectsCount, and AForge.Math.Geometry.Rectangle.
Referenced by AForge.Vision.Motion.BlobCountingObjectsProcessing.ProcessFrame().
GetObjectsInformation()
Blob [] AForge.Imaging.BlobCounterBase.GetObjectsInformation () inline
Get objects' information.
Returns
Returns array of partially initialized blobs (without Blob.Image property initialized).
By the amount of provided information, the method is between GetObjectsRectangles and GetObjects(UnmanagedImage, bool) methods. The method provides array of blobs without initialized their image. Blob's image may be extracted later using ExtractBlobsImage(Bitmap, Blob, bool) or ExtractBlobsImage(UnmanagedImage, Blob, bool) method.
// create blob counter and process image
BlobCounter bc = new BlobCounter(sourceImage);
// specify sort order
bc.ObjectsOrder = ObjectsOrder.Size;
// get objects' information (blobs without image)
Blob[] blobs = bc.GetObjectInformation();
// process blobs
foreach (Blob blob in blobs)
{
    // check blob's properties
    if ( blob.Rectangle.Width > 50 )
    {
        // the blob looks interesting, let's extract it
        bc.ExtractBlobsImage( sourceImage, blob );
    }
}
Exceptions
ApplicationException No image was processed before, so objects' information can not be collected.
References AForge.Imaging.BlobCounterBase.blobs, AForge.Imaging.BlobCounterBase.objectLabels, and AForge.Imaging.BlobCounterBase.objectsCount.
Referenced by AForge.Imaging.Filters.ExtractBiggestBlob.Apply(), IPPrototyperSample.CoinsFinder.Process(), AForge.Imaging.Filters.FillHoles.ProcessFilter(), ShapeChecker.MainForm.ProcessImage(), and BlobsExplorer.BlobsBrowser.SetImage().
GetObjects() [1/2]
Blob [] AForge.Imaging.BlobCounterBase.GetObjects (Bitmap image, bool extractInOriginalSize) inline
Get blobs.
Parameters
image Source image to extract objects from.
Returns
Returns array of blobs.
Parameters
extractInOriginalSize Specifies size of blobs' image to extract. If set to true each blobs' image will have the same size as the specified image. If set to false each blobs' image will have the size of its blob.
The method returns array of blobs. Before calling the method, the ProcessImage(Bitmap), ProcessImage(BitmapData) or ProcessImage(UnmanagedImage) method should be called, which will build objects map.
The method supports 24/32 bpp color and 8 bpp indexed grayscale images.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the provided image.
ApplicationException No image was processed before, so objects can not be collected.
References AForge.Imaging.BlobCounterBase.blobs, and AForge.Math.Geometry.Rectangle.
GetObjects() [2/2]
Blob [] AForge.Imaging.BlobCounterBase.GetObjects (UnmanagedImage image, bool extractInOriginalSize) inline
Get blobs.
Parameters
image Source unmanaged image to extract objects from.
extractInOriginalSize Specifies size of blobs' image to extract. If set to true each blobs' image will have the same size as the specified image. If set to false each blobs' image will have the size of its blob.
Returns
Returns array of blobs.
The method returns array of blobs. Before calling the method, the ProcessImage(Bitmap), ProcessImage(BitmapData) or ProcessImage(UnmanagedImage) method should be called, which will build objects map.
The method supports 24/32 bpp color and 8 bpp indexed grayscale images.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the provided image.
ApplicationException No image was processed before, so objects can not be collected.
References AForge.Imaging.BlobCounterBase.blobs, AForge.Imaging.UnmanagedImage.Create(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.Blob.Image, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.BlobCounterBase.objectLabels, AForge.Imaging.BlobCounterBase.objectsCount, AForge.Imaging.Blob.OriginalSize, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
ExtractBlobsImage() [1/2]
void AForge.Imaging.BlobCounterBase.ExtractBlobsImage (Bitmap image, Blob blob, bool extractInOriginalSize) inline
Extract blob's image.
Parameters
image Source image to extract blob's image from.
blob Blob which is required to be extracted.
extractInOriginalSize Specifies size of blobs' image to extract. If set to true each blobs' image will have the same size as the specified image. If set to false each blobs' image will have the size of its blob.
The method is used to extract image of partially initialized blob, which was provided by GetObjectsInformation method. Before calling the method, the ProcessImage(Bitmap), ProcessImage(BitmapData) or ProcessImage(UnmanagedImage) method should be called, which will build objects map.
The method supports 24/32 bpp color and 8 bpp indexed grayscale images.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the provided image.
ApplicationException No image was processed before, so blob can not be extracted.
References AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.Filters.ExtractBiggestBlob.Apply().
ExtractBlobsImage() [2/2]
void AForge.Imaging.BlobCounterBase.ExtractBlobsImage (UnmanagedImage image, Blob blob, bool extractInOriginalSize) inline
Extract blob's image.
Parameters
image Source unmanaged image to extract blob's image from.
blob Blob which is required to be extracted.
extractInOriginalSize Specifies size of blobs' image to extract. If set to true each blobs' image will have the same size as the specified image. If set to false each blobs' image will have the size of its blob.
The method is used to extract image of partially initialized blob, which was provided by GetObjectsInformation method. Before calling the method, the ProcessImage(Bitmap), ProcessImage(BitmapData) or ProcessImage(UnmanagedImage) method should be called, which will build objects map.
The method supports 24/32 bpp color and 8 bpp indexed grayscale images.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the provided image.
ApplicationException No image was processed before, so blob can not be extracted.
References AForge.Imaging.UnmanagedImage.Create(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.Blob.ID, AForge.Imaging.Blob.Image, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.BlobCounterBase.objectLabels, AForge.Imaging.Blob.OriginalSize, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.Blob.Rectangle, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
GetBlobsLeftAndRightEdges()
void AForge.Imaging.BlobCounterBase.GetBlobsLeftAndRightEdges (Blob blob, out List< IntPoint > leftEdge, out List< IntPoint > rightEdge) inline
Get list of points on the left and right edges of the blob.
Parameters
blob Blob to collect edge points for.
leftEdge List of points on the left edge of the blob.
rightEdge List of points on the right edge of the blob.
The method scans each line of the blob and finds the most left and the most right points for it adding them to appropriate lists. The method may be very useful in conjunction with different routines from AForge.Math.Geometry, which allow finding convex hull or quadrilateral's corners.
<note>Both lists of points are sorted by Y coordinate - points with smaller Y value go first.</note>
Exceptions
ApplicationException No image was processed before, so blob can not be extracted.
References AForge.Imaging.Blob.ID, AForge.Imaging.BlobCounterBase.imageWidth, AForge.Imaging.BlobCounterBase.objectLabels, and AForge.Imaging.Blob.Rectangle.
Referenced by BlobsExplorer.BlobsBrowser.SetImage().
GetBlobsTopAndBottomEdges()
void AForge.Imaging.BlobCounterBase.GetBlobsTopAndBottomEdges (Blob blob, out List< IntPoint > topEdge, out List< IntPoint > bottomEdge) inline
Get list of points on the top and bottom edges of the blob.
Parameters
blob Blob to collect edge points for.
topEdge List of points on the top edge of the blob.
bottomEdge List of points on the bottom edge of the blob.
The method scans each column of the blob and finds the most top and the most bottom points for it adding them to appropriate lists. The method may be very useful in conjunction with different routines from AForge.Math.Geometry, which allow finding convex hull or quadrilateral's corners.
<note>Both lists of points are sorted by X coordinate - points with smaller X value go first.</note>
Exceptions
ApplicationException No image was processed before, so blob can not be extracted.
References AForge.Imaging.Blob.ID, AForge.Imaging.BlobCounterBase.imageWidth, AForge.Imaging.BlobCounterBase.objectLabels, and AForge.Imaging.Blob.Rectangle.
Referenced by BlobsExplorer.BlobsBrowser.SetImage().
GetBlobsEdgePoints()
List<IntPoint> AForge.Imaging.BlobCounterBase.GetBlobsEdgePoints (Blob blob) inline
Get list of object's edge points.
Parameters
blob Blob to collect edge points for.
Returns
Returns unsorted list of blob's edge points.
The method scans each row and column of the blob and finds the most top/bottom/left/right points. The method returns similar result as if results of both GetBlobsLeftAndRightEdges and GetBlobsTopAndBottomEdges methods were combined, but each edge point occurs only once in the list.
<note>Edge points in the returned list are not ordered. This makes the list unusable for visualization with methods, which draw polygon or poly-line. But the returned list can be used with such algorithms, like convex hull search, shape analyzer, etc.</note>
Exceptions
ApplicationException No image was processed before, so blob can not be extracted.
References AForge.Imaging.Blob.ID, AForge.Imaging.BlobCounterBase.imageWidth, AForge.Imaging.BlobCounterBase.objectLabels, and AForge.Imaging.Blob.Rectangle.
Referenced by ShapeChecker.MainForm.ProcessImage().
BuildObjectsMap()
abstract void AForge.Imaging.BlobCounterBase.BuildObjectsMap (UnmanagedImage image) protected pure virtual
Actual objects map building.
Parameters
image Unmanaged image to process.
<note>By the time this method is called bitmap's pixel format is not yet checked, so this should be done by the class inheriting from the base class. imageWidth and imageHeight members are initialized before the method is called, so these members may be used safely.</note>
Implemented in AForge.Imaging.RecursiveBlobCounter, and AForge.Imaging.BlobCounter.
Referenced by AForge.Imaging.BlobCounterBase.ProcessImage().
CollectObjectsInfo()
unsafe void AForge.Imaging.BlobCounterBase.CollectObjectsInfo (UnmanagedImage image) inline private
References AForge.Imaging.Blob.Area, AForge.Imaging.RGB.B, AForge.Imaging.BlobCounterBase.blobs, AForge.Imaging.Blob.CenterOfGravity, AForge.Imaging.Blob.ColorMean, AForge.Imaging.Blob.ColorStdDev, AForge.Imaging.Blob.Fullness, AForge.Imaging.RGB.G, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.BlobCounterBase.imageHeight, AForge.Imaging.BlobCounterBase.imageWidth, AForge.Imaging.BlobCounterBase.objectLabels, AForge.Imaging.BlobCounterBase.objectsCount, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, AForge.Math.Geometry.Rectangle, and AForge.Imaging.UnmanagedImage.Stride.
Referenced by AForge.Imaging.BlobCounterBase.ProcessImage().
Member Data Documentation
blobs
List<Blob> AForge.Imaging.BlobCounterBase.blobs = new List<Blob>() private
Referenced by AForge.Imaging.BlobCounterBase.CollectObjectsInfo(), AForge.Imaging.BlobCounterBase.GetObjects(), AForge.Imaging.BlobCounterBase.GetObjectsInformation(), AForge.Imaging.BlobCounterBase.GetObjectsRectangles(), and AForge.Imaging.BlobCounterBase.ProcessImage().
objectsOrder
ObjectsOrder AForge.Imaging.BlobCounterBase.objectsOrder = ObjectsOrder.None private
Referenced by AForge.Imaging.BlobCounterBase.ProcessImage().
filterBlobs
bool AForge.Imaging.BlobCounterBase.filterBlobs = false private
Referenced by AForge.Imaging.BlobCounterBase.ProcessImage().
filter
IBlobsFilter AForge.Imaging.BlobCounterBase.filter = null private
Referenced by AForge.Imaging.BlobCounterBase.ProcessImage().
coupledSizeFiltering
bool AForge.Imaging.BlobCounterBase.coupledSizeFiltering = false private
Referenced by AForge.Imaging.BlobCounterBase.ProcessImage().
minWidth
int AForge.Imaging.BlobCounterBase.minWidth = 1 private
Referenced by AForge.Imaging.BlobCounterBase.ProcessImage().
minHeight
int AForge.Imaging.BlobCounterBase.minHeight = 1 private
Referenced by AForge.Imaging.BlobCounterBase.ProcessImage().
maxWidth
int AForge.Imaging.BlobCounterBase.maxWidth = int.MaxValue private
Referenced by AForge.Imaging.BlobCounterBase.ProcessImage().
maxHeight
int AForge.Imaging.BlobCounterBase.maxHeight = int.MaxValue private
Referenced by AForge.Imaging.BlobCounterBase.ProcessImage().
objectsCount
int AForge.Imaging.BlobCounterBase.objectsCount protected
Objects count.
Referenced by AForge.Imaging.BlobCounter.BuildObjectsMap(), AForge.Imaging.RecursiveBlobCounter.BuildObjectsMap(), AForge.Imaging.BlobCounterBase.CollectObjectsInfo(), AForge.Imaging.BlobCounterBase.GetObjects(), AForge.Imaging.BlobCounterBase.GetObjectsInformation(), AForge.Imaging.BlobCounterBase.GetObjectsRectangles(), AForge.Imaging.RecursiveBlobCounter.LabelColorPixel(), AForge.Imaging.RecursiveBlobCounter.LabelPixel(), and AForge.Imaging.BlobCounterBase.ProcessImage().
objectLabels
int [] AForge.Imaging.BlobCounterBase.objectLabels protected
Objects' labels.
Referenced by AForge.Imaging.BlobCounter.BuildObjectsMap(), AForge.Imaging.RecursiveBlobCounter.BuildObjectsMap(), AForge.Imaging.BlobCounterBase.CollectObjectsInfo(), AForge.Imaging.BlobCounterBase.ExtractBlobsImage(), AForge.Imaging.BlobCounterBase.GetBlobsEdgePoints(), AForge.Imaging.BlobCounterBase.GetBlobsLeftAndRightEdges(), AForge.Imaging.BlobCounterBase.GetBlobsTopAndBottomEdges(), AForge.Imaging.BlobCounterBase.GetObjects(), AForge.Imaging.BlobCounterBase.GetObjectsInformation(), AForge.Imaging.BlobCounterBase.GetObjectsRectangles(), and AForge.Imaging.BlobCounterBase.ProcessImage().
imageWidth
int AForge.Imaging.BlobCounterBase.imageWidth protected
Width of processed image.
Referenced by AForge.Imaging.BlobCounter.BuildObjectsMap(), AForge.Imaging.RecursiveBlobCounter.BuildObjectsMap(), AForge.Imaging.BlobCounterBase.CollectObjectsInfo(), AForge.Imaging.BlobCounterBase.GetBlobsEdgePoints(), AForge.Imaging.BlobCounterBase.GetBlobsLeftAndRightEdges(), AForge.Imaging.BlobCounterBase.GetBlobsTopAndBottomEdges(), AForge.Imaging.RecursiveBlobCounter.LabelColorPixel(), AForge.Imaging.RecursiveBlobCounter.LabelPixel(), and AForge.Imaging.BlobCounterBase.ProcessImage().
imageHeight
int AForge.Imaging.BlobCounterBase.imageHeight protected
Height of processed image.
Referenced by AForge.Imaging.BlobCounter.BuildObjectsMap(), AForge.Imaging.RecursiveBlobCounter.BuildObjectsMap(), AForge.Imaging.BlobCounterBase.CollectObjectsInfo(), and AForge.Imaging.BlobCounterBase.ProcessImage().
Property Documentation
ObjectsCount
int AForge.Imaging.BlobCounterBase.ObjectsCount get
Objects count.
Number of objects (blobs) found by ProcessImage(Bitmap) method.
ObjectLabels
int [] AForge.Imaging.BlobCounterBase.ObjectLabels get
Objects' labels.
The array of width * height size, which holds labels for all objects. Background is represented with 0 value, but objects are represented with labels starting from 1.
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser_MouseClick(), BlobsExplorer.BlobsBrowser.BlobsBrowser_MouseMove(), AForge.Imaging.Filters.FillHoles.ProcessFilter(), AForge.Imaging.Filters.ConnectedComponentsLabeling.ProcessFilter(), and AForge.Imaging.Filters.BlobsFiltering.ProcessFilter().
ObjectsOrder
ObjectsOrder AForge.Imaging.BlobCounterBase.ObjectsOrder get set
Objects sort order.
The property specifies objects' sort order, which are provided by GetObjectsRectangles, GetObjectsInformation, etc.
FilterBlobs
bool AForge.Imaging.BlobCounterBase.FilterBlobs get set
Specifies if blobs should be filtered.
If the property is equal to false, then there is no any additional post processing after image was processed. If the property is set to true, then blobs filtering is done right after image processing routine. If BlobsFilter is set, then custom blobs' filtering is done, which is implemented by user. Otherwise blobs are filtered according to dimensions specified in MinWidth, MinHeight, MaxWidth and MaxHeight properties.
Default value is set to false.
Referenced by AForge.Vision.Motion.BlobCountingObjectsProcessing.BlobCountingObjectsProcessing(), AForge.Imaging.Filters.BlobsFiltering.BlobsFiltering(), IPPrototyperSample.CoinsFinder.Process(), and ShapeChecker.MainForm.ProcessImage().
CoupledSizeFiltering
bool AForge.Imaging.BlobCounterBase.CoupledSizeFiltering get set
Specifies if size filetering should be coupled or not.
In uncoupled filtering mode, objects are filtered out in the case if their width is smaller than MinWidth or height is smaller than MinHeight. But in coupled filtering mode, objects are filtered out in the case if their width is smaller than MinWidth and height is smaller than MinHeight. In both modes the idea with filtering by objects' maximum size is the same as filtering by objects' minimum size.
Default value is set to false, what means uncoupled filtering by size.
Referenced by AForge.Imaging.Filters.BlobsFiltering.BlobsFiltering().
MinWidth
int AForge.Imaging.BlobCounterBase.MinWidth get set
Minimum allowed width of blob.
The property specifies minimum object's width acceptable by blob counting routine and has power only when FilterBlobs property is set to true and custom blobs' filter is set to null.
See documentation to CoupledSizeFiltering for additional information.
Referenced by AForge.Vision.Motion.BlobCountingObjectsProcessing.BlobCountingObjectsProcessing(), AForge.Imaging.Filters.BlobsFiltering.BlobsFiltering(), IPPrototyperSample.CoinsFinder.Process(), and ShapeChecker.MainForm.ProcessImage().
MinHeight
int AForge.Imaging.BlobCounterBase.MinHeight get set
Minimum allowed height of blob.
The property specifies minimum object's height acceptable by blob counting routine and has power only when FilterBlobs property is set to true and custom blobs' filter is set to null.
See documentation to CoupledSizeFiltering for additional information.
Referenced by AForge.Vision.Motion.BlobCountingObjectsProcessing.BlobCountingObjectsProcessing(), AForge.Imaging.Filters.BlobsFiltering.BlobsFiltering(), and ShapeChecker.MainForm.ProcessImage().
MaxWidth
int AForge.Imaging.BlobCounterBase.MaxWidth get set
Maximum allowed width of blob.
The property specifies maximum object's width acceptable by blob counting routine and has power only when FilterBlobs property is set to true and custom blobs' filter is set to null.
See documentation to CoupledSizeFiltering for additional information.
Referenced by AForge.Imaging.Filters.BlobsFiltering.BlobsFiltering().
MaxHeight
int AForge.Imaging.BlobCounterBase.MaxHeight get set
Maximum allowed height of blob.
The property specifies maximum object's height acceptable by blob counting routine and has power only when FilterBlobs property is set to true and custom blobs' filter is set to null.
See documentation to CoupledSizeFiltering for additional information.
Referenced by AForge.Imaging.Filters.BlobsFiltering.BlobsFiltering().
BlobsFilter
IBlobsFilter AForge.Imaging.BlobCounterBase.BlobsFilter get set
Custom blobs' filter to use.
The property specifies custom blobs' filtering routine to use. It has effect only in the case if FilterBlobs property is set to true.
<note>When custom blobs' filtering routine is set, it has priority over default filtering done with MinWidth, MinHeight, MaxWidth and MaxHeight.</note>
Referenced by AForge.Imaging.Filters.BlobsFiltering.BlobsFiltering().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/BlobCounterBase.cs