Doc: IGLib EXTENDED: BlobsExplorer.BlobsBrowser Class Reference
BlobsExplorer.BlobsBrowser Class Reference
Public Types
enum HightlightType { HightlightType.ConvexHull, HightlightType.LeftAndRightEdges, HightlightType.TopAndBottomEdges, HightlightType.Quadrilateral }
Public Member Functions
BlobsBrowser ()
int SetImage (Bitmap image)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
HightlightType Highlighting [get, set]
bool ShowRectangleAroundSelection [get, set]
Events
BlobSelectionHandler BlobSelected
Private Member Functions
void BlobsBrowser_Paint (object sender, PaintEventArgs e)
void UpdatePosition ()
void BlobsBrowser_ParentChanged (object sender, EventArgs e)
void parent_SizeChanged (object sender, EventArgs e)
void BlobsBrowser_MouseMove (object sender, MouseEventArgs e)
void BlobsBrowser_MouseClick (object sender, MouseEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Static Private Member Functions
static System.Drawing.Point[] PointsListToArray (List< IntPoint > list)
static void DrawEdge (Graphics g, Pen pen, List< IntPoint > edge)
Private Attributes
Bitmap image = null
int imageWidth
int imageHeight
Control parent = null
BlobCounter blobCounter = new BlobCounter()
Blob[] blobs
int selectedBlobID
Dictionary< int, List< IntPoint > > leftEdges = new Dictionary<int, List<IntPoint>>()
Dictionary< int, List< IntPoint > > rightEdges = new Dictionary<int, List<IntPoint>>()
Dictionary< int, List< IntPoint > > topEdges = new Dictionary<int, List<IntPoint>>()
Dictionary< int, List< IntPoint > > bottomEdges = new Dictionary<int, List<IntPoint>>()
Dictionary< int, List< IntPoint > > hulls = new Dictionary<int, List<IntPoint>>()
Dictionary< int, List< IntPoint > > quadrilaterals = new Dictionary<int, List<IntPoint>>()
HightlightType highlighting = HightlightType.Quadrilateral
bool showRectangleAroundSelection = false
System.ComponentModel.IContainer components = null
Required designer variable.
Member Enumeration Documentation
HightlightType
enum BlobsExplorer.BlobsBrowser.HightlightType strong
Enumerator
ConvexHull
LeftAndRightEdges
TopAndBottomEdges
Quadrilateral
Constructor & Destructor Documentation
BlobsBrowser()
BlobsExplorer.BlobsBrowser.BlobsBrowser () inline
References BlobsExplorer.BlobsBrowser.InitializeComponent().
Member Function Documentation
SetImage()
int BlobsExplorer.BlobsBrowser.SetImage (Bitmap image) inline
References BlobsExplorer.BlobsBrowser.blobCounter, BlobsExplorer.BlobsBrowser.blobs, BlobsExplorer.BlobsBrowser.bottomEdges, AForge.Imaging.Image.Clone(), AForge.Math.Geometry.PointsCloud.FindQuadrilateralCorners(), AForge.Imaging.BlobCounterBase.GetBlobsLeftAndRightEdges(), AForge.Imaging.BlobCounterBase.GetBlobsTopAndBottomEdges(), AForge.Imaging.BlobCounterBase.GetObjectsInformation(), BlobsExplorer.BlobsBrowser.hulls, AForge.Imaging.Blob.ID, BlobsExplorer.BlobsBrowser.image, BlobsExplorer.BlobsBrowser.imageHeight, BlobsExplorer.BlobsBrowser.imageWidth, BlobsExplorer.BlobsBrowser.leftEdges, AForge.Imaging.BlobCounterBase.ProcessImage(), BlobsExplorer.BlobsBrowser.quadrilaterals, BlobsExplorer.BlobsBrowser.rightEdges, BlobsExplorer.BlobsBrowser.selectedBlobID, AForge.Math.Geometry.PointsCloud.Shift(), BlobsExplorer.BlobsBrowser.topEdges, and BlobsExplorer.BlobsBrowser.UpdatePosition().
Referenced by BlobsExplorer.MainForm.ProcessImage().
BlobsBrowser_Paint()
void BlobsExplorer.BlobsBrowser.BlobsBrowser_Paint (object sender, PaintEventArgs e) inline private
References BlobsExplorer.BlobsBrowser.blobs, BlobsExplorer.BlobsBrowser.bottomEdges, BlobsExplorer.BlobsBrowser.DrawEdge(), BlobsExplorer.BlobsBrowser.highlighting, BlobsExplorer.BlobsBrowser.hulls, AForge.Imaging.Blob.ID, BlobsExplorer.BlobsBrowser.image, BlobsExplorer.BlobsBrowser.leftEdges, BlobsExplorer.BlobsBrowser.PointsListToArray(), BlobsExplorer.BlobsBrowser.quadrilaterals, AForge.Math.Geometry.Rectangle, AForge.Imaging.Blob.Rectangle, BlobsExplorer.BlobsBrowser.rightEdges, BlobsExplorer.BlobsBrowser.selectedBlobID, BlobsExplorer.BlobsBrowser.showRectangleAroundSelection, and BlobsExplorer.BlobsBrowser.topEdges.
Referenced by BlobsExplorer.BlobsBrowser.InitializeComponent().
UpdatePosition()
void BlobsExplorer.BlobsBrowser.UpdatePosition () inline private
References BlobsExplorer.BlobsBrowser.image, BlobsExplorer.BlobsBrowser.imageHeight, BlobsExplorer.BlobsBrowser.imageWidth, AForge.Math.Geometry.Rectangle, and AForge.Imaging.Size.
Referenced by BlobsExplorer.BlobsBrowser.parent_SizeChanged(), and BlobsExplorer.BlobsBrowser.SetImage().
BlobsBrowser_ParentChanged()
void BlobsExplorer.BlobsBrowser.BlobsBrowser_ParentChanged (object sender, EventArgs e) inline private
References BlobsExplorer.BlobsBrowser.parent, and BlobsExplorer.BlobsBrowser.parent_SizeChanged().
Referenced by BlobsExplorer.BlobsBrowser.InitializeComponent().
parent_SizeChanged()
void BlobsExplorer.BlobsBrowser.parent_SizeChanged (object sender, EventArgs e) inline private
References BlobsExplorer.BlobsBrowser.UpdatePosition().
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser_ParentChanged().
BlobsBrowser_MouseMove()
void BlobsExplorer.BlobsBrowser.BlobsBrowser_MouseMove (object sender, MouseEventArgs e) inline private
References BlobsExplorer.BlobsBrowser.blobCounter, BlobsExplorer.BlobsBrowser.image, BlobsExplorer.BlobsBrowser.imageHeight, BlobsExplorer.BlobsBrowser.imageWidth, and AForge.Imaging.BlobCounterBase.ObjectLabels.
Referenced by BlobsExplorer.BlobsBrowser.InitializeComponent().
BlobsBrowser_MouseClick()
void BlobsExplorer.BlobsBrowser.BlobsBrowser_MouseClick (object sender, MouseEventArgs e) inline private
References BlobsExplorer.BlobsBrowser.blobCounter, BlobsExplorer.BlobsBrowser.blobs, BlobsExplorer.BlobsBrowser.BlobSelected, BlobsExplorer.BlobsBrowser.image, BlobsExplorer.BlobsBrowser.imageHeight, BlobsExplorer.BlobsBrowser.imageWidth, AForge.Imaging.BlobCounterBase.ObjectLabels, and BlobsExplorer.BlobsBrowser.selectedBlobID.
Referenced by BlobsExplorer.BlobsBrowser.InitializeComponent().
PointsListToArray()
static System.Drawing.Point [] BlobsExplorer.BlobsBrowser.PointsListToArray (List< IntPoint > list) inline static private
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser_Paint(), and BlobsExplorer.BlobsBrowser.DrawEdge().
DrawEdge()
static void BlobsExplorer.BlobsBrowser.DrawEdge (Graphics g, Pen pen, List< IntPoint > edge) inline static private
References BlobsExplorer.BlobsBrowser.PointsListToArray().
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser_Paint().
Dispose()
override void BlobsExplorer.BlobsBrowser.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References BlobsExplorer.BlobsBrowser.components.
InitializeComponent()
void BlobsExplorer.BlobsBrowser.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References BlobsExplorer.BlobsBrowser.BlobsBrowser_MouseClick(), BlobsExplorer.BlobsBrowser.BlobsBrowser_MouseMove(), BlobsExplorer.BlobsBrowser.BlobsBrowser_Paint(), and BlobsExplorer.BlobsBrowser.BlobsBrowser_ParentChanged().
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser().
Member Data Documentation
image
Bitmap BlobsExplorer.BlobsBrowser.image = null private
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser_MouseClick(), BlobsExplorer.BlobsBrowser.BlobsBrowser_MouseMove(), BlobsExplorer.BlobsBrowser.BlobsBrowser_Paint(), BlobsExplorer.BlobsBrowser.SetImage(), and BlobsExplorer.BlobsBrowser.UpdatePosition().
imageWidth
int BlobsExplorer.BlobsBrowser.imageWidth private
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser_MouseClick(), BlobsExplorer.BlobsBrowser.BlobsBrowser_MouseMove(), BlobsExplorer.BlobsBrowser.SetImage(), and BlobsExplorer.BlobsBrowser.UpdatePosition().
imageHeight
int BlobsExplorer.BlobsBrowser.imageHeight private
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser_MouseClick(), BlobsExplorer.BlobsBrowser.BlobsBrowser_MouseMove(), BlobsExplorer.BlobsBrowser.SetImage(), and BlobsExplorer.BlobsBrowser.UpdatePosition().
parent
Control BlobsExplorer.BlobsBrowser.parent = null private
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser_ParentChanged().
blobCounter
BlobCounter BlobsExplorer.BlobsBrowser.blobCounter = new BlobCounter() private
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser_MouseClick(), BlobsExplorer.BlobsBrowser.BlobsBrowser_MouseMove(), and BlobsExplorer.BlobsBrowser.SetImage().
blobs
Blob [] BlobsExplorer.BlobsBrowser.blobs private
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser_MouseClick(), BlobsExplorer.BlobsBrowser.BlobsBrowser_Paint(), and BlobsExplorer.BlobsBrowser.SetImage().
selectedBlobID
int BlobsExplorer.BlobsBrowser.selectedBlobID private
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser_MouseClick(), BlobsExplorer.BlobsBrowser.BlobsBrowser_Paint(), and BlobsExplorer.BlobsBrowser.SetImage().
leftEdges
Dictionary<int, List<IntPoint> > BlobsExplorer.BlobsBrowser.leftEdges = new Dictionary<int, List<IntPoint>>() private
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser_Paint(), and BlobsExplorer.BlobsBrowser.SetImage().
rightEdges
Dictionary<int, List<IntPoint> > BlobsExplorer.BlobsBrowser.rightEdges = new Dictionary<int, List<IntPoint>>() private
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser_Paint(), and BlobsExplorer.BlobsBrowser.SetImage().
topEdges
Dictionary<int, List<IntPoint> > BlobsExplorer.BlobsBrowser.topEdges = new Dictionary<int, List<IntPoint>>() private
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser_Paint(), and BlobsExplorer.BlobsBrowser.SetImage().
bottomEdges
Dictionary<int, List<IntPoint> > BlobsExplorer.BlobsBrowser.bottomEdges = new Dictionary<int, List<IntPoint>>() private
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser_Paint(), and BlobsExplorer.BlobsBrowser.SetImage().
hulls
Dictionary<int, List<IntPoint> > BlobsExplorer.BlobsBrowser.hulls = new Dictionary<int, List<IntPoint>>() private
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser_Paint(), and BlobsExplorer.BlobsBrowser.SetImage().
quadrilaterals
Dictionary<int, List<IntPoint> > BlobsExplorer.BlobsBrowser.quadrilaterals = new Dictionary<int, List<IntPoint>>() private
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser_Paint(), and BlobsExplorer.BlobsBrowser.SetImage().
highlighting
HightlightType BlobsExplorer.BlobsBrowser.highlighting = HightlightType.Quadrilateral private
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser_Paint().
showRectangleAroundSelection
bool BlobsExplorer.BlobsBrowser.showRectangleAroundSelection = false private
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser_Paint().
components
System.ComponentModel.IContainer BlobsExplorer.BlobsBrowser.components = null private
Required designer variable.
Referenced by BlobsExplorer.BlobsBrowser.Dispose().
Property Documentation
Highlighting
HightlightType BlobsExplorer.BlobsBrowser.Highlighting get set
Referenced by BlobsExplorer.MainForm.highlightTypeCombo_SelectedIndexChanged().
ShowRectangleAroundSelection
bool BlobsExplorer.BlobsBrowser.ShowRectangleAroundSelection get set
Referenced by BlobsExplorer.MainForm.MainForm(), and BlobsExplorer.MainForm.showRectangleAroundSelectionCheck_CheckedChanged().
Event Documentation
BlobSelected
BlobSelectionHandler BlobsExplorer.BlobsBrowser.BlobSelected
Referenced by BlobsExplorer.BlobsBrowser.BlobsBrowser_MouseClick().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Imaging/BlobsExplorer/BlobsBrowser.cs
shelldev/lib_ann/aforge.net/Samples/Imaging/BlobsExplorer/BlobsBrowser.Designer.cs