Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLASWP Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLASWP Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLASWP ()
void Run (int N, ref double[] A, int offset_a, int LDA, int K1, int K2, int[] IPIV, int offset_ipiv, int INCX)
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLASWP performs a series of row interchanges on the matrix A. One row interchange is initiated for each of rows K1 through K2 of A.
/summary>
Constructor & Destructor Documentation
DLASWP()
DotNumerics.LinearAlgebra.CSLapack.DLASWP.DLASWP () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLASWP.Run (int N, ref double[] A, int offset_a, int LDA, int K1, int K2, int[] IPIV, int offset_ipiv, int INCX) inline
Purpose
DLASWP performs a series of row interchanges on the matrix A. One row interchange is initiated for each of rows K1 through K2 of A.
/summary>
Parameters
N (input) INTEGER The number of columns of the matrix A. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the matrix of column dimension N to which the row interchanges will be applied. On exit, the permuted matrix. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. /param>
Parameters
K1 (input) INTEGER The first element of IPIV for which a row interchange will be done. /param>
Parameters
K2 (input) INTEGER The last element of IPIV for which a row interchange will be done. /param>
Parameters
IPIV (input) INTEGER array, dimension (K2*abs(INCX)) The vector of pivot indices. Only the elements in positions K1 through K2 of IPIV are accessed. IPIV(K) = L implies rows K and L are to be interchanged. /param>
Parameters
INCX (input) INTEGER The increment between successive values of IPIV. If IPIV is negative, the pivots are applied in reverse order. /param>
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGETRS.Run(), DotNumerics.LinearAlgebra.CSLapack.DGETRF.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGBTRF.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlaswp.cs