Doc: IGLib EXTENDED: AForge.Controls.VideoSourcePlayer Class Reference
AForge.Controls.VideoSourcePlayer Class Reference
Video source player control.
Public Member Functions
delegate void NewFrameHandler (object sender, ref Bitmap image)
Delegate to notify about new frame.
VideoSourcePlayer ()
Initializes a new instance of the VideoSourcePlayer class.
void Start ()
Start video source and displaying its frames.
void Stop ()
Stop video source.
void SignalToStop ()
Signal video source to stop.
void WaitForStop ()
Wait for video source has stopped.
Bitmap GetCurrentVideoFrame ()
Get clone of current video frame displayed by the control.
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
bool AutoSizeControl [get, set]
Auto size control or not.
Color BorderColor [get, set]
Control's border color.
IVideoSource VideoSource [get, set]
Video source to play.
bool? IsRunning [get]
State of the current video source.
Events
NewFrameHandler NewFrame
New frame event.
PlayingFinishedEventHandler PlayingFinished
Playing finished event.
Private Member Functions
void CheckForCrossThreadAccess ()
void VideoSourcePlayer_Paint (object sender, PaintEventArgs e)
void UpdatePosition ()
void videoSource_NewFrame (object sender, NewFrameEventArgs eventArgs)
void videoSource_VideoSourceError (object sender, VideoSourceErrorEventArgs eventArgs)
void videoSource_PlayingFinished (object sender, ReasonToFinishPlaying reason)
void VideoSourcePlayer_ParentChanged (object sender, EventArgs e)
void parent_SizeChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
IVideoSource videoSource = null
Bitmap currentFrame = null
Bitmap convertedFrame = null
string lastMessage = null
Color borderColor = Color.Black
Size frameSize = new Size(320, 240)
bool autosize = false
bool needSizeUpdate = false
bool firstFrameNotProcessed = true
volatile bool requestedToStop = false
Control parent = null
object sync = new object()
System.ComponentModel.IContainer components = null
Required designer variable.
Detailed Description
Video source player control.
The control is aimed to play video sources, which implement AForge.Video.IVideoSource interface. To start playing a video the VideoSource property should be initialized first and then Start method should be called. In the case if user needs to perform some sort of image processing with video frames before they are displayed, the NewFrame event may be used.
Sample usage:
// set new frame event handler if we need processing of new frames
playerControl.NewFrame += new VideoSourcePlayer.NewFrameHandler(this.playerControl_NewFrame);
// create video source
IVideoSource videoSource = new ...
// start playing it
playerControl.VideoSource = videoSource;
playerControl.Start();
...
// new frame event handler
private void playerControl_NewFrame(object sender, ref Bitmap image)
{
    // process new frame somehow ...
    // Note: it may be even changed, so the control will display the result
    // of image processing done here
}
Constructor & Destructor Documentation
VideoSourcePlayer()
AForge.Controls.VideoSourcePlayer.VideoSourcePlayer () inline
Initializes a new instance of the VideoSourcePlayer class.
References AForge.Controls.VideoSourcePlayer.InitializeComponent().
Member Function Documentation
NewFrameHandler()
delegate void AForge.Controls.VideoSourcePlayer.NewFrameHandler (object sender, ref Bitmap image)
Delegate to notify about new frame.
Parameters
sender Event sender.
image New frame.
Referenced by Player.MainForm.InitializeComponent(), SVSTest.MainForm.showStereoButton_Click(), and SVSTest.MainForm.stereoViewForm_OnFormClosing().
CheckForCrossThreadAccess()
void AForge.Controls.VideoSourcePlayer.CheckForCrossThreadAccess () inline private
Referenced by AForge.Controls.VideoSourcePlayer.SignalToStop(), AForge.Controls.VideoSourcePlayer.Start(), AForge.Controls.VideoSourcePlayer.Stop(), and AForge.Controls.VideoSourcePlayer.WaitForStop().
Start()
void AForge.Controls.VideoSourcePlayer.Start () inline
Start video source and displaying its frames.
References AForge.Controls.VideoSourcePlayer.CheckForCrossThreadAccess(), AForge.Controls.VideoSourcePlayer.firstFrameNotProcessed, AForge.Controls.VideoSourcePlayer.requestedToStop, AForge.Video.IVideoSource.Start(), and AForge.Controls.VideoSourcePlayer.videoSource.
Referenced by SRVTest.MainForm.Connect(), and SVSTest.MainForm.Connect().
Stop()
void AForge.Controls.VideoSourcePlayer.Stop () inline
Stop video source.
The method stops video source by calling its AForge.Video.IVideoSource.Stop method, which abourts internal video source's thread. Use SignalToStop and WaitForStop for more polite video source stopping, which gives a chance for video source to perform proper shut down and clean up.
References AForge.Controls.VideoSourcePlayer.CheckForCrossThreadAccess(), AForge.Controls.VideoSourcePlayer.currentFrame, AForge.Controls.VideoSourcePlayer.requestedToStop, AForge.Video.IVideoSource.Stop(), and AForge.Controls.VideoSourcePlayer.videoSource.
SignalToStop()
void AForge.Controls.VideoSourcePlayer.SignalToStop () inline
Signal video source to stop.
Use WaitForStop method to wait until video source stops.
References AForge.Controls.VideoSourcePlayer.CheckForCrossThreadAccess(), AForge.Controls.VideoSourcePlayer.requestedToStop, AForge.Video.IVideoSource.SignalToStop(), and AForge.Controls.VideoSourcePlayer.videoSource.
Referenced by AForge.Controls.VideoSourcePlayer.WaitForStop().
WaitForStop()
void AForge.Controls.VideoSourcePlayer.WaitForStop () inline
Wait for video source has stopped.
Waits for video source stopping after it was signaled to stop using SignalToStop method. If SignalToStop was not called, then it will be called automatically.
References AForge.Controls.VideoSourcePlayer.CheckForCrossThreadAccess(), AForge.Controls.VideoSourcePlayer.currentFrame, AForge.Controls.VideoSourcePlayer.requestedToStop, AForge.Controls.VideoSourcePlayer.SignalToStop(), AForge.Controls.VideoSourcePlayer.videoSource, and AForge.Video.IVideoSource.WaitForStop().
GetCurrentVideoFrame()
Bitmap AForge.Controls.VideoSourcePlayer.GetCurrentVideoFrame () inline
Get clone of current video frame displayed by the control.
Returns
Returns copy of the video frame, which is currently displayed by the control - the last video frame received from video source. If the control did not receive any video frames yet, then the method returns null.
References AForge.Imaging.Image.Clone(), AForge.Controls.VideoSourcePlayer.currentFrame, and AForge.Controls.VideoSourcePlayer.sync.
VideoSourcePlayer_Paint()
void AForge.Controls.VideoSourcePlayer.VideoSourcePlayer_Paint (object sender, PaintEventArgs e) inline private
References AForge.Controls.VideoSourcePlayer.borderColor, AForge.Controls.VideoSourcePlayer.convertedFrame, AForge.Controls.VideoSourcePlayer.currentFrame, AForge.Controls.VideoSourcePlayer.firstFrameNotProcessed, AForge.Controls.VideoSourcePlayer.lastMessage, AForge.Controls.VideoSourcePlayer.needSizeUpdate, AForge.Controls.VideoSourcePlayer.sync, AForge.Controls.VideoSourcePlayer.UpdatePosition(), and AForge.Controls.VideoSourcePlayer.videoSource.
Referenced by AForge.Controls.VideoSourcePlayer.InitializeComponent().
UpdatePosition()
void AForge.Controls.VideoSourcePlayer.UpdatePosition () inline private
References AForge.Controls.VideoSourcePlayer.autosize, and AForge.Controls.VideoSourcePlayer.frameSize.
Referenced by AForge.Controls.VideoSourcePlayer.parent_SizeChanged(), and AForge.Controls.VideoSourcePlayer.VideoSourcePlayer_Paint().
videoSource_NewFrame()
void AForge.Controls.VideoSourcePlayer.videoSource_NewFrame (object sender, NewFrameEventArgs eventArgs) inline private
References AForge.Imaging.Image.Convert16bppTo8bpp(), AForge.Controls.VideoSourcePlayer.convertedFrame, AForge.Controls.VideoSourcePlayer.currentFrame, AForge.Video.NewFrameEventArgs.Frame, AForge.Controls.VideoSourcePlayer.frameSize, AForge.Controls.VideoSourcePlayer.lastMessage, AForge.Controls.VideoSourcePlayer.needSizeUpdate, AForge.Controls.VideoSourcePlayer.NewFrame, AForge.Controls.VideoSourcePlayer.requestedToStop, and AForge.Controls.VideoSourcePlayer.sync.
videoSource_VideoSourceError()
void AForge.Controls.VideoSourcePlayer.videoSource_VideoSourceError (object sender, VideoSourceErrorEventArgs eventArgs) inline private
References AForge.Video.VideoSourceErrorEventArgs.Description, and AForge.Controls.VideoSourcePlayer.lastMessage.
videoSource_PlayingFinished()
void AForge.Controls.VideoSourcePlayer.videoSource_PlayingFinished (object sender, ReasonToFinishPlaying reason) inline private
References AForge.Controls.VideoSourcePlayer.lastMessage, and AForge.Controls.VideoSourcePlayer.PlayingFinished.
VideoSourcePlayer_ParentChanged()
void AForge.Controls.VideoSourcePlayer.VideoSourcePlayer_ParentChanged (object sender, EventArgs e) inline private
References AForge.Controls.VideoSourcePlayer.parent, and AForge.Controls.VideoSourcePlayer.parent_SizeChanged().
Referenced by AForge.Controls.VideoSourcePlayer.InitializeComponent().
parent_SizeChanged()
void AForge.Controls.VideoSourcePlayer.parent_SizeChanged (object sender, EventArgs e) inline private
References AForge.Controls.VideoSourcePlayer.UpdatePosition().
Referenced by AForge.Controls.VideoSourcePlayer.VideoSourcePlayer_ParentChanged().
Dispose()
override void AForge.Controls.VideoSourcePlayer.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References AForge.Controls.VideoSourcePlayer.components.
InitializeComponent()
void AForge.Controls.VideoSourcePlayer.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References AForge.Controls.VideoSourcePlayer.VideoSourcePlayer_Paint(), and AForge.Controls.VideoSourcePlayer.VideoSourcePlayer_ParentChanged().
Referenced by AForge.Controls.VideoSourcePlayer.VideoSourcePlayer().
Member Data Documentation
videoSource
IVideoSource AForge.Controls.VideoSourcePlayer.videoSource = null private
Referenced by AForge.Controls.VideoSourcePlayer.SignalToStop(), AForge.Controls.VideoSourcePlayer.Start(), AForge.Controls.VideoSourcePlayer.Stop(), AForge.Controls.VideoSourcePlayer.VideoSourcePlayer_Paint(), and AForge.Controls.VideoSourcePlayer.WaitForStop().
currentFrame
Bitmap AForge.Controls.VideoSourcePlayer.currentFrame = null private
Referenced by AForge.Controls.VideoSourcePlayer.GetCurrentVideoFrame(), AForge.Controls.VideoSourcePlayer.Stop(), AForge.Controls.VideoSourcePlayer.videoSource_NewFrame(), AForge.Controls.VideoSourcePlayer.VideoSourcePlayer_Paint(), and AForge.Controls.VideoSourcePlayer.WaitForStop().
convertedFrame
Bitmap AForge.Controls.VideoSourcePlayer.convertedFrame = null private
Referenced by AForge.Controls.VideoSourcePlayer.videoSource_NewFrame(), and AForge.Controls.VideoSourcePlayer.VideoSourcePlayer_Paint().
lastMessage
string AForge.Controls.VideoSourcePlayer.lastMessage = null private
Referenced by AForge.Controls.VideoSourcePlayer.videoSource_NewFrame(), AForge.Controls.VideoSourcePlayer.videoSource_PlayingFinished(), AForge.Controls.VideoSourcePlayer.videoSource_VideoSourceError(), and AForge.Controls.VideoSourcePlayer.VideoSourcePlayer_Paint().
borderColor
Color AForge.Controls.VideoSourcePlayer.borderColor = Color.Black private
Referenced by AForge.Controls.VideoSourcePlayer.VideoSourcePlayer_Paint().
frameSize
Size AForge.Controls.VideoSourcePlayer.frameSize = new Size(320, 240) private
Referenced by AForge.Controls.VideoSourcePlayer.UpdatePosition(), and AForge.Controls.VideoSourcePlayer.videoSource_NewFrame().
autosize
bool AForge.Controls.VideoSourcePlayer.autosize = false private
Referenced by AForge.Controls.VideoSourcePlayer.UpdatePosition().
needSizeUpdate
bool AForge.Controls.VideoSourcePlayer.needSizeUpdate = false private
Referenced by AForge.Controls.VideoSourcePlayer.videoSource_NewFrame(), and AForge.Controls.VideoSourcePlayer.VideoSourcePlayer_Paint().
firstFrameNotProcessed
bool AForge.Controls.VideoSourcePlayer.firstFrameNotProcessed = true private
Referenced by AForge.Controls.VideoSourcePlayer.Start(), and AForge.Controls.VideoSourcePlayer.VideoSourcePlayer_Paint().
requestedToStop
volatile bool AForge.Controls.VideoSourcePlayer.requestedToStop = false private
Referenced by AForge.Controls.VideoSourcePlayer.SignalToStop(), AForge.Controls.VideoSourcePlayer.Start(), AForge.Controls.VideoSourcePlayer.Stop(), AForge.Controls.VideoSourcePlayer.videoSource_NewFrame(), and AForge.Controls.VideoSourcePlayer.WaitForStop().
parent
Control AForge.Controls.VideoSourcePlayer.parent = null private
Referenced by AForge.Controls.VideoSourcePlayer.VideoSourcePlayer_ParentChanged().
sync
object AForge.Controls.VideoSourcePlayer.sync = new object() private
Referenced by AForge.Controls.VideoSourcePlayer.GetCurrentVideoFrame(), AForge.Controls.VideoSourcePlayer.videoSource_NewFrame(), and AForge.Controls.VideoSourcePlayer.VideoSourcePlayer_Paint().
components
System.ComponentModel.IContainer AForge.Controls.VideoSourcePlayer.components = null private
Required designer variable.
Referenced by AForge.Controls.VideoSourcePlayer.Dispose().
Property Documentation
AutoSizeControl
bool AForge.Controls.VideoSourcePlayer.AutoSizeControl get set
Auto size control or not.
The property specifies if the control should be autosized or not. If the property is set to true, then the control will change its size according to video size and control will change its position automatically to be in the center of parent's control.
<note>Setting the property to true has no effect if Control.Dock property is set to DockStyle.Fill.</note>
BorderColor
Color AForge.Controls.VideoSourcePlayer.BorderColor get set
Control's border color.
Specifies color of the border drawn around video frame.
VideoSource
IVideoSource AForge.Controls.VideoSourcePlayer.VideoSource get set
Video source to play.
The property sets the video source to play. After setting the property the Start method should be used to start playing the video source.
<note>Trying to change video source while currently set video source is still playing will generate an exception. Use IsRunning property to check if current video source is still playing or Stop or SignalToStop and WaitForStop methods to stop current video source.</note>
Exceptions
Exception Video source can not be changed while current video source is still running.
Referenced by SRVTest.MainForm.Connect(), SVSTest.MainForm.Connect(), SRVTest.MainForm.Disconnect(), SVSTest.MainForm.Disconnect(), SRVTest.MainForm.timer_Tick(), and SVSTest.MainForm.timer_Tick().
IsRunning
bool? AForge.Controls.VideoSourcePlayer.IsRunning get
State of the current video source.
Current state of the current video source object - running or not.
Event Documentation
NewFrame
NewFrameHandler AForge.Controls.VideoSourcePlayer.NewFrame
New frame event.
The event is fired on each new frame received from video source. The event is fired right after receiving and before displaying, what gives user a chance to perform some image processing on the new frame and/or update it.
<note>Users should not keep references of the passed to the event handler image. If user needs to keep the image, it should be cloned, since the original image will be disposed by the control when it is required.</note>
Referenced by SVSTest.MainForm.showStereoButton_Click(), SVSTest.MainForm.stereoViewForm_OnFormClosing(), and AForge.Controls.VideoSourcePlayer.videoSource_NewFrame().
PlayingFinished
PlayingFinishedEventHandler AForge.Controls.VideoSourcePlayer.PlayingFinished
Playing finished event.
The event is fired when/if video playing finishes. The reason of video stopping is provided as an argument to the event handler.
Referenced by AForge.Controls.VideoSourcePlayer.videoSource_PlayingFinished().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Sources/Controls/VideoSourcePlayer.cs
shelldev/lib_ann/aforge.net/Sources/Controls/VideoSourcePlayer.Designer.cs