Doc: IGLib EXTENDED: IG.Neural.Forms.NeuralParametricTest2d Class Reference
IG.Neural.Forms.NeuralParametricTest2d Class Reference
Form for simple parametric tests (variation of selected parameter) performed on ANN models.
Public Member Functions
NeuralParametricTest2d (INeuralModel neuralModel)
Constructs the control, with ANN-based model specified.
NeuralParametricTest2d ()
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
void ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
void PlotParametricTestZedGraph ()
plots the selected outpt dependend on the selected parameter.
virtual void ApplySurfacePlotSettingsDefault (VtkSurfacePlotBase plot)
Applies default settings to surface plots.
virtual void ApplySurfacePlottterSettingsDefault (VtkPlotter plotter, int whichInput1, int whichInput2, int whichOutput)
Applies default settings to plotter used to render 3D graphs.
void PlotParametricTest ()
plots the selected outpt dependend on the selected parameter.
Static Public Attributes
static string SelectedParametersIntroStr = "Selected input parameters: "
Protected Member Functions
void UpdateSeclectedParametersDependencies ()
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
INeuralModelContainer _neuralModelContainerControl
int _selectedParameterId1 = 0
int _selectedParameterId2 = 0
int _selectedOutputId = 0
ColorScale SurfaceColorScale
BoundingBox3d OriginalBounds
Properties
INeuralModel NeuralModel [get, protected set]
Neural network - based model.
INeuralApproximator TrainedNetwork [get]
Traint artificial neural network.
InputOutputDataDefiniton NeuralDataDefinition [get]
Neural data definition.
int NumInputParameters [get]
Gets number of input parameters.
int NumOutputValues [get]
Gets number of output values.
IVector ParameterValues [get]
Vector of current values of input parameters as defined by the DadaGridView.
double[] MinValues [get]
Minimal values of parameters.
double[] MaxValues [get]
Maximal values of parameters.
int SelectedParameterId1 [get, protected set]
Sequential number of the selected first parameter as specified by the user.
double SelectedParameterMin1 [get]
Minimal value of the selected first parameter.
double SelectedParameterMax1 [get]
Maximal value of the selected first parameter as specified by the user.
int SelectedParameterId2 [get, protected set]
Sequential number of the selected second parameter as specified by the user.
double SelectedParameterMin2 [get]
Minimal value of the selected second parameter.
double SelectedParameterMax2 [get]
Maximal value of the selected second parameter as specified by the user.
int SelectedOutputId [get, protected set]
string SelectedParameterLabelText [get]
Gets axis label text for the currently selected parameter.
string SelectedOutputLabelText [get]
Gets axis label text for the currently selected output value.
PlotterZedGraph Plotterzedgraph [get]
Plotter that is used for plotting the graphs.
Properties inherited from IG.Neural.INeuralModelContainer
INeuralModel NeuralModel [get]
Artificial neural network - based model.
Private Member Functions
void btnParmTestStart_Click (object sender, EventArgs e)
Plots the parametric test.
void neuralInputSelector1_SelectedParameterIdChanged (int oldId, int newId)
Executes when ID of the selected first input parameter changes; Plots the parametric test.
void neuralInputSelector1_SelectedParameterMinChanged (double oldValue, double newValue)
Executes when minimal value of the selected first parameter changes by user interaction; Plots the parametric test.
void neuralInputSelector1_SelectedParameterMaxChanged (double oldValue, double newValue)
Executes when maximal value of the selected first parameter changes by user interaction; Plots the parametric test.
void neuralInputSelector2_SelectedParameterIdChanged (int oldId, int newId)
Executes when ID of the selected second input parameter changes; Plots the parametric test.
void neuralInputSelector2_SelectedParameterMinChanged (double oldValue, double newValue)
Executes when minimal value of the selected second parameter changes by user interaction; Plots the parametric test.
void neuralInputSelector2_SelectedParameterMaxChanged (double oldValue, double newValue)
Executes when maximal value of the selected second parameter changes by user interaction; Plots the parametric test.
void neuralOutputValueSelector1_SelectedOutputIdChanged (int oldId, int newId)
Executes when ID of the selected output value changes; Plots the parametric test.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
INeuralModel _neuralModel
PlotterZedGraph _plotterZedgraph
System.ComponentModel.IContainer components = null
Required designer variable.
NeuralInputControl neuralInputControl1
System.Windows.Forms.Panel pnlGraph
System.Windows.Forms.NumericUpDown txtNumPoints1
System.Windows.Forms.Label lblNumPoints
ZedGraph.ZedGraphControl ParmTestFGraph
System.Windows.Forms.Button btnParmTestStart
Forms.NeuralOutputValueSelector neuralOutputValueSelector1
NeuralInputParameterSelectorMinMax neuralInputSelector1
System.Windows.Forms.Label lblTitleParametric2d
NeuralInputParameterSelectorMinMax neuralInputSelector2
System.Windows.Forms.NumericUpDown txtNumPoints2
System.Windows.Forms.Label lblNumPointsCross
System.Windows.Forms.Label lblSelectedParameters
System.Windows.Forms.CheckBox chkScaled
Detailed Description
Form for simple parametric tests (variation of selected parameter) performed on ANN models.
$A Igor Jun13;
Constructor & Destructor Documentation
NeuralParametricTest2d() [1/2]
IG.Neural.Forms.NeuralParametricTest2d.NeuralParametricTest2d (INeuralModel neuralModel) inline
Constructs the control, with ANN-based model specified.
Parameters
neuralModel ANN-based model, containing data definitions and trained neural network.
References IG.Neural.Forms.NeuralParametricTest2d.NeuralModel.
NeuralParametricTest2d() [2/2]
IG.Neural.Forms.NeuralParametricTest2d.NeuralParametricTest2d () inline
References IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent().
Member Function Documentation
SetNeuralModel()
void IG.Neural.Forms.NeuralParametricTest2d.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
Implements IG.Neural.INeuralModelContainer.
References IG.Neural.Forms.NeuralParametricTest2d.NeuralModel.
UpdateSeclectedParametersDependencies()
void IG.Neural.Forms.NeuralParametricTest2d.UpdateSeclectedParametersDependencies () inline protected
References IG.Neural.Forms.NeuralParametricTest2d.lblSelectedParameters, IG.Neural.Forms.NeuralParametricTest2d.SelectedParameterId1, IG.Neural.Forms.NeuralParametricTest2d.SelectedParameterId2, and IG.Neural.Forms.NeuralParametricTest2d.SelectedParametersIntroStr.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector1_SelectedParameterIdChanged(), and IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector2_SelectedParameterIdChanged().
ApplyPlotterSettingsDefault()
void IG.Neural.Forms.NeuralParametricTest2d.ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Num.InputOutputDataDefiniton.InputElementList, IG.Gr.PlotterZedGraph.IsShowPointValues, IG.Neural.Forms.NeuralParametricTest2d.NeuralDataDefinition, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Neural.Forms.NeuralParametricTest2d.SelectedOutputLabelText, IG.Neural.Forms.NeuralParametricTest2d.SelectedParameterLabelText, IG.Gr.PlotterZedGraph.XAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabel.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTestZedGraph().
ApplyPlotCurveSettingsDefault()
void IG.Neural.Forms.NeuralParametricTest2d.ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichInput, int numInputs, int whichOutput, int numOutpts) inline
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LineWidth, IG.Gr.PlotZedgraphCurve.PointBorderColor, IG.Gr.PlotZedgraphCurve.PointFillColor, and IG.Gr.PlotZedgraphCurve.PointsVisible.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTestZedGraph().
PlotParametricTestZedGraph()
void IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTestZedGraph () inline
plots the selected outpt dependend on the selected parameter.
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Neural.Forms.NeuralParametricTest2d.ApplyPlotCurveSettingsDefault(), IG.Neural.Forms.NeuralParametricTest2d.ApplyPlotterSettingsDefault(), IG.Num.IVectorApproximator.CalculateOutput(), IG.Num.VectorBase.CopyPlain(), IG.Neural.Forms.NeuralParametricTest2d.NumInputParameters, IG.Neural.Forms.NeuralParametricTest2d.NumOutputValues, IG.Neural.Forms.NeuralParametricTest2d.ParameterValues, IG.Neural.Forms.NeuralParametricTest2d.Plotterzedgraph, IG.Gr.PlotterZedGraph.RemoveAllPlotObjects(), IG.Gr.PlotterZedGraph.ResetView(), IG.Neural.Forms.NeuralParametricTest2d.SelectedOutputId, IG.Neural.Forms.NeuralParametricTest2d.SelectedParameterId1, IG.Neural.Forms.NeuralParametricTest2d.SelectedParameterMax1, IG.Neural.Forms.NeuralParametricTest2d.SelectedParameterMin1, IG.Neural.Forms.NeuralParametricTest2d.TrainedNetwork, IG.Neural.Forms.NeuralParametricTest2d.txtNumPoints1, and IG.Gr.PlotterZedGraph.Update().
Referenced by IG.Neural.Forms.NeuralParametricTest2d.btnParmTestStart_Click().
ApplySurfacePlotSettingsDefault()
virtual void IG.Neural.Forms.NeuralParametricTest2d.ApplySurfacePlotSettingsDefault (VtkSurfacePlotBase plot) inline virtual
Applies default settings to surface plots.
Parameters
plot Surface plot to which settings are applied.
References IG.Gr3d.VtkSurfacePlotBase.LineColor, IG.Gr3d.VtkSurfacePlotBase.LinesVisible, IG.Gr3d.VtkSurfacePlotBase.LineWidth, IG.Gr3d.VtkSurfacePlotBase.PointsVisible, IG.Gr3d.VtkSurfacePlotBase.SurfaceColor, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorIsScaled, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorOpacity, IG.Gr3d.VtkSurfacePlotBase.SurfaceColorScale, IG.Neural.Forms.NeuralParametricTest2d.SurfaceColorScale, and IG.Gr3d.VtkSurfacePlotBase.SurfacesVisible.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTest().
ApplySurfacePlottterSettingsDefault()
virtual void IG.Neural.Forms.NeuralParametricTest2d.ApplySurfacePlottterSettingsDefault (VtkPlotter plotter, int whichInput1, int whichInput2, int whichOutput) inline virtual
Applies default settings to plotter used to render 3D graphs.
Parameters
plotter 3D Plotter to which settings are applied.
References IG.Gr3d.VtkPlotter.BackGround, IG.Neural.Forms.NeuralParametricTest2d.chkScaled, IG.Gr3d.VtkDecorationHandler.CubeAxesFlyMode, IG.Gr3d.VtkDecorationHandler.CubeAxesXLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesYLabel, IG.Gr3d.VtkDecorationHandler.CubeAxesZLabel, IG.Gr3d.VtkPlotter.DecorationHandler, IG.Num.InputOutputDataDefiniton.InputElementList, IG.Gr3d.VtkDecorationHandler.LookUpTableColorScale, IG.Gr3d.VtkDecorationHandler.LookUpTableMaxRange, IG.Gr3d.VtkDecorationHandler.LookUpTableMinRange, IG.Num.BoundingBox3d.MaxZ, IG.Num.BoundingBox3d.MinZ, IG.Neural.Forms.NeuralParametricTest2d.NeuralDataDefinition, IG.Neural.Forms.NeuralParametricTest2d.OriginalBounds, IG.Num.InputOutputDataDefiniton.OutputElementList, IG.Gr3d.VtkDecorationHandler.ScalarBarNumberOfLabels, IG.Gr3d.VtkDecorationHandler.ScalarBarTitle, IG.Gr3d.VtkDecorationHandler.ShowCubeAxes, IG.Gr3d.VtkDecorationHandler.ShowScalarBar, IG.Neural.Forms.NeuralParametricTest2d.SurfaceColorScale, IG.Gr3d.VtkPlotter.WindowSizeX, and IG.Gr3d.VtkPlotter.WindowSizeY.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTest().
PlotParametricTest()
void IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTest () inline
plots the selected outpt dependend on the selected parameter.
References IG.Neural.Forms.NeuralParametricTest2d.ApplySurfacePlotSettingsDefault(), IG.Neural.Forms.NeuralParametricTest2d.ApplySurfacePlottterSettingsDefault(), IG.Num.IVectorApproximator.CalculateOutput(), IG.Neural.Forms.NeuralParametricTest2d.chkScaled, IG.Gr3d.VtkSurfacePlot.ClearSurfaceDefinition(), IG.Num.VectorBase.CopyPlain(), IG.Gr3d.VtkSurfacePlot.Create(), IG.Num.BoundingBoxBase.Map(), IG.Num.BoundingBoxBase.Max, IG.Gr3d.VtkSurfacePlot.Mesh, IG.Num.BoundingBoxBase.Min, IG.Neural.Forms.NeuralParametricTest2d.NumInputParameters, IG.Neural.Forms.NeuralParametricTest2d.OriginalBounds, IG.Gr3d.VtkPlotBase.OutputLevel, IG.Neural.Forms.NeuralParametricTest2d.ParameterValues, IG.Gr3d.VtkPlotter.ResetCamera(), IG.Neural.Forms.NeuralParametricTest2d.SelectedOutputId, IG.Neural.Forms.NeuralParametricTest2d.SelectedParameterId1, IG.Neural.Forms.NeuralParametricTest2d.SelectedParameterId2, IG.Neural.Forms.NeuralParametricTest2d.SelectedParameterMax1, IG.Neural.Forms.NeuralParametricTest2d.SelectedParameterMax2, IG.Neural.Forms.NeuralParametricTest2d.SelectedParameterMin1, IG.Neural.Forms.NeuralParametricTest2d.SelectedParameterMin2, IG.Gr3d.VtkPlotBase.ShowPlot(), IG.Num.BoundingBoxBase.ToString(), IG.Neural.Forms.NeuralParametricTest2d.TrainedNetwork, IG.Neural.Forms.NeuralParametricTest2d.txtNumPoints1, IG.Neural.Forms.NeuralParametricTest2d.txtNumPoints2, IG.Num.BoundingBox3d.Update(), and IG.Num.Vector3d.Vec.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.btnParmTestStart_Click().
btnParmTestStart_Click()
void IG.Neural.Forms.NeuralParametricTest2d.btnParmTestStart_Click (object sender, EventArgs e) inline private
Plots the parametric test.
References IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTest(), and IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTestZedGraph().
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent().
neuralInputSelector1_SelectedParameterIdChanged()
void IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector1_SelectedParameterIdChanged (int oldId, int newId) inline private
Executes when ID of the selected first input parameter changes; Plots the parametric test.
Parameters
oldId Old ID of the selected output value (after change).
newId New ID of the selected output value (after changed).
References IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector1, IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector2, IG.Neural.Forms.NeuralParametricTest2d.NumInputParameters, IG.Neural.Forms.NeuralInputParameterSelectorMinMax.SelectedParameterId, IG.Neural.Forms.NeuralInputParameterSelectorMinMax.SetSelectedParameterId(), and IG.Neural.Forms.NeuralParametricTest2d.UpdateSeclectedParametersDependencies().
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent().
neuralInputSelector1_SelectedParameterMinChanged()
void IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector1_SelectedParameterMinChanged (double oldValue, double newValue) inline private
Executes when minimal value of the selected first parameter changes by user interaction; Plots the parametric test.
Parameters
oldValue Old value.
newValue New value.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent().
neuralInputSelector1_SelectedParameterMaxChanged()
void IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector1_SelectedParameterMaxChanged (double oldValue, double newValue) inline private
Executes when maximal value of the selected first parameter changes by user interaction; Plots the parametric test.
Parameters
oldValue Old value.
newValue New value.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent().
neuralInputSelector2_SelectedParameterIdChanged()
void IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector2_SelectedParameterIdChanged (int oldId, int newId) inline private
Executes when ID of the selected second input parameter changes; Plots the parametric test.
Parameters
oldId Old ID of the selected output value (after change).
newId New ID of the selected output value (after changed).
References IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector1, IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector2, IG.Neural.Forms.NeuralInputParameterSelectorMinMax.SelectedParameterId, IG.Neural.Forms.NeuralInputParameterSelectorMinMax.SetSelectedParameterId(), and IG.Neural.Forms.NeuralParametricTest2d.UpdateSeclectedParametersDependencies().
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent().
neuralInputSelector2_SelectedParameterMinChanged()
void IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector2_SelectedParameterMinChanged (double oldValue, double newValue) inline private
Executes when minimal value of the selected second parameter changes by user interaction; Plots the parametric test.
Parameters
oldValue Old value.
newValue New value.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent().
neuralInputSelector2_SelectedParameterMaxChanged()
void IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector2_SelectedParameterMaxChanged (double oldValue, double newValue) inline private
Executes when maximal value of the selected second parameter changes by user interaction; Plots the parametric test.
Parameters
oldValue Old value.
newValue New value.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent().
neuralOutputValueSelector1_SelectedOutputIdChanged()
void IG.Neural.Forms.NeuralParametricTest2d.neuralOutputValueSelector1_SelectedOutputIdChanged (int oldId, int newId) inline private
Executes when ID of the selected output value changes; Plots the parametric test.
Parameters
oldId Old ID of the selected output value (after change).
newId New ID of the selected output value (after changed).
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent().
Dispose()
override void IG.Neural.Forms.NeuralParametricTest2d.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralParametricTest2d.components.
InitializeComponent()
void IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralParametricTest2d.btnParmTestStart, IG.Neural.Forms.NeuralParametricTest2d.btnParmTestStart_Click(), IG.Neural.Forms.NeuralParametricTest2d.chkScaled, IG.Neural.Forms.NeuralParametricTest2d.lblNumPoints, IG.Neural.Forms.NeuralParametricTest2d.lblNumPointsCross, IG.Neural.Forms.NeuralParametricTest2d.lblSelectedParameters, IG.Neural.Forms.NeuralParametricTest2d.lblTitleParametric2d, IG.Neural.Forms.NeuralParametricTest2d.neuralInputControl1, IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector1, IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector1_SelectedParameterIdChanged(), IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector1_SelectedParameterMaxChanged(), IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector1_SelectedParameterMinChanged(), IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector2, IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector2_SelectedParameterIdChanged(), IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector2_SelectedParameterMaxChanged(), IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector2_SelectedParameterMinChanged(), IG.Neural.Forms.NeuralParametricTest2d.neuralOutputValueSelector1, IG.Neural.Forms.NeuralParametricTest2d.neuralOutputValueSelector1_SelectedOutputIdChanged(), IG.Neural.Forms.NeuralParametricTest2d.ParmTestFGraph, IG.Neural.Forms.NeuralParametricTest2d.pnlGraph, IG.Neural.Forms.NeuralOutputValueSelector.SelectedOutputIdChanged, IG.Neural.Forms.NeuralInputParameterSelectorMinMax.SelectedParameterIdChanged, IG.Neural.Forms.NeuralInputParameterSelectorMinMax.SelectedParameterMaxChanged, IG.Neural.Forms.NeuralInputParameterSelectorMinMax.SelectedParameterMinChanged, IG.Neural.Forms.NeuralInputParameterSelectorMinMax.TitleParameterSelection, IG.Neural.Forms.NeuralParametricTest2d.txtNumPoints1, and IG.Neural.Forms.NeuralParametricTest2d.txtNumPoints2.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.NeuralParametricTest2d().
Member Data Documentation
_neuralModelContainerControl
INeuralModelContainer IG.Neural.Forms.NeuralParametricTest2d._neuralModelContainerControl protected
_neuralModel
INeuralModel IG.Neural.Forms.NeuralParametricTest2d._neuralModel private
_selectedParameterId1
int IG.Neural.Forms.NeuralParametricTest2d._selectedParameterId1 = 0 protected
_selectedParameterId2
int IG.Neural.Forms.NeuralParametricTest2d._selectedParameterId2 = 0 protected
SelectedParametersIntroStr
string IG.Neural.Forms.NeuralParametricTest2d.SelectedParametersIntroStr = "Selected input parameters: " static
Referenced by IG.Neural.Forms.NeuralParametricTest2d.UpdateSeclectedParametersDependencies().
_selectedOutputId
int IG.Neural.Forms.NeuralParametricTest2d._selectedOutputId = 0 protected
_plotterZedgraph
PlotterZedGraph IG.Neural.Forms.NeuralParametricTest2d._plotterZedgraph private
SurfaceColorScale
ColorScale IG.Neural.Forms.NeuralParametricTest2d.SurfaceColorScale protected
Referenced by IG.Neural.Forms.NeuralParametricTest2d.ApplySurfacePlotSettingsDefault(), and IG.Neural.Forms.NeuralParametricTest2d.ApplySurfacePlottterSettingsDefault().
OriginalBounds
BoundingBox3d IG.Neural.Forms.NeuralParametricTest2d.OriginalBounds protected
Referenced by IG.Neural.Forms.NeuralParametricTest2d.ApplySurfacePlottterSettingsDefault(), and IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTest().
components
System.ComponentModel.IContainer IG.Neural.Forms.NeuralParametricTest2d.components = null private
Required designer variable.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.Dispose().
neuralInputControl1
NeuralInputControl IG.Neural.Forms.NeuralParametricTest2d.neuralInputControl1 private
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent().
pnlGraph
System.Windows.Forms.Panel IG.Neural.Forms.NeuralParametricTest2d.pnlGraph private
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent().
txtNumPoints1
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralParametricTest2d.txtNumPoints1 private
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent(), IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTest(), and IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTestZedGraph().
lblNumPoints
System.Windows.Forms.Label IG.Neural.Forms.NeuralParametricTest2d.lblNumPoints private
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent().
ParmTestFGraph
ZedGraph.ZedGraphControl IG.Neural.Forms.NeuralParametricTest2d.ParmTestFGraph private
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent().
btnParmTestStart
System.Windows.Forms.Button IG.Neural.Forms.NeuralParametricTest2d.btnParmTestStart private
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent().
neuralOutputValueSelector1
Forms.NeuralOutputValueSelector IG.Neural.Forms.NeuralParametricTest2d.neuralOutputValueSelector1 private
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent().
neuralInputSelector1
NeuralInputParameterSelectorMinMax IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector1 private
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent(), IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector1_SelectedParameterIdChanged(), and IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector2_SelectedParameterIdChanged().
lblTitleParametric2d
System.Windows.Forms.Label IG.Neural.Forms.NeuralParametricTest2d.lblTitleParametric2d private
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent().
neuralInputSelector2
NeuralInputParameterSelectorMinMax IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector2 private
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent(), IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector1_SelectedParameterIdChanged(), and IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector2_SelectedParameterIdChanged().
txtNumPoints2
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralParametricTest2d.txtNumPoints2 private
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent(), and IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTest().
lblNumPointsCross
System.Windows.Forms.Label IG.Neural.Forms.NeuralParametricTest2d.lblNumPointsCross private
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent().
lblSelectedParameters
System.Windows.Forms.Label IG.Neural.Forms.NeuralParametricTest2d.lblSelectedParameters private
Referenced by IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent(), and IG.Neural.Forms.NeuralParametricTest2d.UpdateSeclectedParametersDependencies().
chkScaled
System.Windows.Forms.CheckBox IG.Neural.Forms.NeuralParametricTest2d.chkScaled private
Referenced by IG.Neural.Forms.NeuralParametricTest2d.ApplySurfacePlottterSettingsDefault(), IG.Neural.Forms.NeuralParametricTest2d.InitializeComponent(), and IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTest().
Property Documentation
NeuralModel
INeuralModel IG.Neural.Forms.NeuralParametricTest2d.NeuralModel get protected set
Neural network - based model.
Contains data definition and trained neural network approximator.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.NeuralParametricTest2d(), and IG.Neural.Forms.NeuralParametricTest2d.SetNeuralModel().
TrainedNetwork
INeuralApproximator IG.Neural.Forms.NeuralParametricTest2d.TrainedNetwork get
Traint artificial neural network.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTest(), and IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTestZedGraph().
NeuralDataDefinition
InputOutputDataDefiniton IG.Neural.Forms.NeuralParametricTest2d.NeuralDataDefinition get
Neural data definition.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.ApplyPlotterSettingsDefault(), and IG.Neural.Forms.NeuralParametricTest2d.ApplySurfacePlottterSettingsDefault().
NumInputParameters
int IG.Neural.Forms.NeuralParametricTest2d.NumInputParameters get
Gets number of input parameters.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.neuralInputSelector1_SelectedParameterIdChanged(), IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTest(), and IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTestZedGraph().
NumOutputValues
int IG.Neural.Forms.NeuralParametricTest2d.NumOutputValues get
Gets number of output values.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTestZedGraph().
ParameterValues
IVector IG.Neural.Forms.NeuralParametricTest2d.ParameterValues get
Vector of current values of input parameters as defined by the DadaGridView.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTest(), and IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTestZedGraph().
MinValues
double [] IG.Neural.Forms.NeuralParametricTest2d.MinValues get
Minimal values of parameters.
MaxValues
double [] IG.Neural.Forms.NeuralParametricTest2d.MaxValues get
Maximal values of parameters.
SelectedParameterId1
int IG.Neural.Forms.NeuralParametricTest2d.SelectedParameterId1 get protected set
Sequential number of the selected first parameter as specified by the user.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTest(), IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTestZedGraph(), and IG.Neural.Forms.NeuralParametricTest2d.UpdateSeclectedParametersDependencies().
SelectedParameterMin1
double IG.Neural.Forms.NeuralParametricTest2d.SelectedParameterMin1 get
Minimal value of the selected first parameter.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTest(), and IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTestZedGraph().
SelectedParameterMax1
double IG.Neural.Forms.NeuralParametricTest2d.SelectedParameterMax1 get
Maximal value of the selected first parameter as specified by the user.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTest(), and IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTestZedGraph().
SelectedParameterId2
int IG.Neural.Forms.NeuralParametricTest2d.SelectedParameterId2 get protected set
Sequential number of the selected second parameter as specified by the user.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTest(), and IG.Neural.Forms.NeuralParametricTest2d.UpdateSeclectedParametersDependencies().
SelectedParameterMin2
double IG.Neural.Forms.NeuralParametricTest2d.SelectedParameterMin2 get
Minimal value of the selected second parameter.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTest().
SelectedParameterMax2
double IG.Neural.Forms.NeuralParametricTest2d.SelectedParameterMax2 get
Maximal value of the selected second parameter as specified by the user.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTest().
SelectedOutputId
int IG.Neural.Forms.NeuralParametricTest2d.SelectedOutputId get protected set
Referenced by IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTest(), and IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTestZedGraph().
SelectedParameterLabelText
string IG.Neural.Forms.NeuralParametricTest2d.SelectedParameterLabelText get
Gets axis label text for the currently selected parameter.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.ApplyPlotterSettingsDefault().
SelectedOutputLabelText
string IG.Neural.Forms.NeuralParametricTest2d.SelectedOutputLabelText get
Gets axis label text for the currently selected output value.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.ApplyPlotterSettingsDefault().
Plotterzedgraph
PlotterZedGraph IG.Neural.Forms.NeuralParametricTest2d.Plotterzedgraph get
Plotter that is used for plotting the graphs.
Referenced by IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTestZedGraph().
The documentation for this class was generated from the following files:
shelldev/extensions/ExtAppAnnApp/ResponseForms/TestingStage/NeuralParametricTest2d.cs
shelldev/extensions/ExtAppAnnApp/ResponseForms/TestingStage/NeuralParametricTest2d.Designer.cs