Doc: IGLib EXTENDED: AForge.PolishExpression Class Reference
AForge.PolishExpression Class Reference
Evaluator of expressions written in polish notation
Static Public Member Functions
static double Evaluate (string expression, double[] variables)
Evaluates specified expression
static double Evaluate (string expression, double[] variables)
Evaluates specified expression
static double Evaluate (string expression, double[] variables)
Evaluates specified expression.
Private Member Functions
PolishExpression ()
Constructor (the class should not be instantiated at this moment)
PolishExpression ()
Constructor (the class should not be instantiated at this moment)
Detailed Description
Evaluator of expressions written in polish notation
Evaluator of expressions written in reverse polish notation.
The class evaluates expressions writen in postfix polish notation. The list of supported functuins is:
Arithmetic functions: +, -, *, /;
sin - sine;
cos - cosine;
ln - natural logarithm;
exp - exponent;
sqrt - square root.
Arguments for these functions could be as usual constants, written as numbers, as variables, writen as $<var_number> ($2, for example). The variable number is zero based index of variables array.
The following sample illustrates the usage of PolishExpression class:
// expression written in polish notation
string expression = "2 $0 / 3 $1 * +";
// variables for the expression
double[] vars = new double[] { 3, 4 };
// expression evaluation
double result = PolishExpression.Evaluate(expression, vars);
The class evaluates expressions writen in reverse postfix polish notation.
The list of supported functuins is:
Arithmetic functions: +, -, *, /;
sin - sine;
cos - cosine;
ln - natural logarithm;
exp - exponent;
sqrt - square root.
Arguments for these functions could be as usual constants, written as numbers, as variables, writen as $<var_number> ($2, for example). The variable number is zero based index of variables array.
Sample usage:
// expression written in polish notation
string expression = "2 $0 / 3 $1 * +";
// variables for the expression
double[] vars = new double[] { 3, 4 };
// expression evaluation
double result = PolishExpression.Evaluate(expression, vars);
Constructor & Destructor Documentation
PolishExpression() [1/2]
AForge.PolishExpression.PolishExpression () inline private
Constructor (the class should not be instantiated at this moment)
PolishExpression() [2/2]
AForge.PolishExpression.PolishExpression () inline private
Constructor (the class should not be instantiated at this moment)
Member Function Documentation
Evaluate() [1/3]
static double AForge.PolishExpression.Evaluate (string expression, double[] variables) inline static
Evaluates specified expression
Parameters
expression Expression written in postfix polish notation
variables Variables for the expression
Returns
Evaluated value of the expression
Referenced by AForge.Genetic.SymbolicRegressionFitness.Evaluate(), AForge.Genetic.TimeSeriesPredictionFitness.Evaluate(), Approximation.MainForm.SearchSolution(), and TimeSeries.MainForm.SearchSolution().
Evaluate() [2/3]
static double AForge.PolishExpression.Evaluate (string expression, double[] variables) inline static
Evaluates specified expression
Parameters
expression Expression written in postfix polish notation
variables Variables for the expression
Returns
Evaluated value of the expression
Evaluate() [3/3]
static double AForge.PolishExpression.Evaluate (string expression, double[] variables) inline static
Evaluates specified expression.
Parameters
expression Expression written in postfix polish notation.
variables Variables for the expression.
Returns
Evaluated value of the expression.
Exceptions
ArgumentException Unsupported function is used in the expression.
ArgumentException Incorrect postfix polish expression.
The documentation for this class was generated from the following file:
shelldev/lib/external/neuralnetworks/neuro_src/Sources/Backup/Core/PolishExpression.cs