Doc: IGLib EXTENDED: NUnit.Engine.RuntimeFramework Class Reference
NUnit.Engine.RuntimeFramework Class Reference
RuntimeFramework represents a particular version of a common language runtime implementation.
Public Member Functions
RuntimeFramework (RuntimeType runtime, Version version)
Construct from a runtime type and version. If the version has two parts, it is taken as a framework version. If it has three or more, it is taken as a CLR version. In either case, the other version is deduced based on the runtime type and provided version.
override string ToString ()
Overridden to return the short name of the framework
bool Supports (RuntimeFramework target)
Returns true if the current framework matches the one supplied as an argument. Two frameworks match if their runtime types are the same or either one is RuntimeType.Any and all specified version components are equal. Negative (i.e. unspecified) version components are ignored.
Static Public Member Functions
static RuntimeFramework Parse (string s)
Parses a string representing a RuntimeFramework. The string may be just a RuntimeType name or just a Version or a hyphenated RuntimeType-Version or a Version prefixed by 'v'.
static RuntimeFramework GetBestAvailableFramework (RuntimeFramework target)
Returns the best available framework that matches a target framework. If the target framework has a build number specified, then an exact match is needed. Otherwise, the matching framework with the highest build number is used.
Static Public Attributes
static readonly Version DefaultVersion = new Version(0, 0)
DefaultVersion is an empty Version, used to indicate that NUnit should select the CLR version to use for the test.
Properties
static RuntimeFramework?? CurrentFramework [get]
Static method to return a RuntimeFramework object for the framework that is currently in use.
static RuntimeFramework[] AvailableFrameworks [get]
Gets an array of all available frameworks
bool IsAvailable [get]
Returns true if the current RuntimeFramework is available. In the current implementation, only Mono and Microsoft .NET are supported.
RuntimeType Runtime [get, private set]
The type of this runtime framework
Version FrameworkVersion [get, private set]
The framework version for this runtime framework
Version ClrVersion [get, private set]
The CLR version for this runtime framework
bool AllowAnyVersion [get]
Return true if any CLR version may be used in matching this RuntimeFramework object.
string DisplayName [get, private set]
Returns the Display name for this framework
Private Member Functions
void InitFromFrameworkVersion (Version version)
void InitFromClrVersion (Version version)
Static Private Member Functions
static void ThrowInvalidFrameworkVersion (Version version)
static bool IsRuntimeTypeName (string name)
static string GetDefaultDisplayName (RuntimeType runtime, Version version)
static bool VersionsMatch (Version v1, Version v2)
static void AppendMonoFrameworks (List< RuntimeFramework > frameworks)
static void AppendAllMonoFrameworks (List< RuntimeFramework > frameworks)
static void AppendDefaultMonoFramework (List< RuntimeFramework > frameworks)
static void AppendMonoFramework (List< RuntimeFramework > frameworks, string monoPrefix, string version)
static void AppendDotNetFrameworks (List< RuntimeFramework > frameworks)
static void AppendExtremelyOldDotNetFrameworkVersions (List< RuntimeFramework > frameworks)
static void AppendOlderDotNetFrameworkVersion (List< RuntimeFramework > frameworks, RegistryKey versionKey, Version version)
static void AppendDotNetFourFrameworkVersions (List< RuntimeFramework > frameworks, RegistryKey versionKey)
static bool CheckInstallDword (RegistryKey key)
Static Private Attributes
static RuntimeFramework currentFramework
static RuntimeFramework[] availableFrameworks
Detailed Description
RuntimeFramework represents a particular version of a common language runtime implementation.
Constructor & Destructor Documentation
RuntimeFramework()
NUnit.Engine.RuntimeFramework.RuntimeFramework (RuntimeType runtime, Version version) inline
Construct from a runtime type and version. If the version has two parts, it is taken as a framework version. If it has three or more, it is taken as a CLR version. In either case, the other version is deduced based on the runtime type and provided version.
Parameters
runtime The runtime type of the framework
version The version of the framework
References NUnit.Engine.RuntimeFramework.DisplayName, NUnit.Engine.RuntimeFramework.GetDefaultDisplayName(), NUnit.Engine.RuntimeFramework.InitFromClrVersion(), NUnit.Engine.RuntimeFramework.InitFromFrameworkVersion(), and NUnit.Engine.RuntimeFramework.Runtime.
Referenced by NUnit.Engine.RuntimeFramework.AppendDotNetFourFrameworkVersions(), NUnit.Engine.RuntimeFramework.AppendExtremelyOldDotNetFrameworkVersions(), NUnit.Engine.RuntimeFramework.AppendMonoFramework(), NUnit.Engine.RuntimeFramework.AppendOlderDotNetFrameworkVersion(), and NUnit.Engine.RuntimeFramework.Parse().
Member Function Documentation
InitFromFrameworkVersion()
void NUnit.Engine.RuntimeFramework.InitFromFrameworkVersion (Version version) inline private
References NUnit.Engine.RuntimeFramework.ClrVersion, NUnit.Engine.RuntimeFramework.FrameworkVersion, NUnit.Engine.RuntimeFramework.Runtime, and NUnit.Engine.RuntimeFramework.ThrowInvalidFrameworkVersion().
Referenced by NUnit.Engine.RuntimeFramework.RuntimeFramework().
ThrowInvalidFrameworkVersion()
static void NUnit.Engine.RuntimeFramework.ThrowInvalidFrameworkVersion (Version version) inline static private
Referenced by NUnit.Engine.RuntimeFramework.InitFromFrameworkVersion().
InitFromClrVersion()
void NUnit.Engine.RuntimeFramework.InitFromClrVersion (Version version) inline private
References NUnit.Engine.RuntimeFramework.ClrVersion, NUnit.Engine.RuntimeFramework.FrameworkVersion, and NUnit.Engine.RuntimeFramework.Runtime.
Referenced by NUnit.Engine.RuntimeFramework.RuntimeFramework().
Parse()
static RuntimeFramework NUnit.Engine.RuntimeFramework.Parse (string s) inline static
Parses a string representing a RuntimeFramework. The string may be just a RuntimeType name or just a Version or a hyphenated RuntimeType-Version or a Version prefixed by 'v'.
Parameters
s
Returns
References NUnit.Engine.RuntimeFramework.DefaultVersion, NUnit.Engine.RuntimeFramework.IsRuntimeTypeName(), and NUnit.Engine.RuntimeFramework.RuntimeFramework().
Referenced by NUnit.Engine.Services.RuntimeFrameworkService.IsAvailable(), NUnit.Engine.Services.TestAgency.LaunchAgentProcess(), NUnit.Engine.Services.Tests.RuntimeFrameworkServiceTests.SelectRuntimeFramework(), NUnit.Engine.Services.RuntimeFrameworkService.SelectRuntimeFramework(), and NUnit.Engine.Runners.MasterTestRunner.ValidatePackageSettings().
GetBestAvailableFramework()
static RuntimeFramework NUnit.Engine.RuntimeFramework.GetBestAvailableFramework (RuntimeFramework target) inline static
Returns the best available framework that matches a target framework. If the target framework has a build number specified, then an exact match is needed. Otherwise, the matching framework with the highest build number is used.
Parameters
target
Returns
References NUnit.Engine.RuntimeFramework.AvailableFrameworks, NUnit.Engine.RuntimeFramework.ClrVersion, and NUnit.Engine.RuntimeFramework.Supports().
Referenced by NUnit.Engine.Services.TestAgency.LaunchAgentProcess().
ToString()
override string NUnit.Engine.RuntimeFramework.ToString () inline
Overridden to return the short name of the framework
Returns
References NUnit.Engine.RuntimeFramework.AllowAnyVersion, NUnit.Engine.RuntimeFramework.FrameworkVersion, and NUnit.Engine.RuntimeFramework.Runtime.
Referenced by NUnit.Engine.Services.RuntimeFrameworkService.SelectRuntimeFramework().
Supports()
bool NUnit.Engine.RuntimeFramework.Supports (RuntimeFramework target) inline
Returns true if the current framework matches the one supplied as an argument. Two frameworks match if their runtime types are the same or either one is RuntimeType.Any and all specified version components are equal. Negative (i.e. unspecified) version components are ignored.
Parameters
target The RuntimeFramework to be matched.
Returns
true on match, otherwise false
References NUnit.Engine.RuntimeFramework.AllowAnyVersion, NUnit.Engine.RuntimeFramework.ClrVersion, NUnit.Engine.RuntimeFramework.FrameworkVersion, NUnit.Engine.RuntimeFramework.Runtime, and NUnit.Engine.RuntimeFramework.VersionsMatch().
Referenced by NUnit.Engine.RuntimeFramework.GetBestAvailableFramework().
IsRuntimeTypeName()
static bool NUnit.Engine.RuntimeFramework.IsRuntimeTypeName (string name) inline static private
Referenced by NUnit.Engine.RuntimeFramework.Parse().
GetDefaultDisplayName()
static string NUnit.Engine.RuntimeFramework.GetDefaultDisplayName (RuntimeType runtime, Version version) inline static private
References NUnit.Engine.RuntimeFramework.DefaultVersion.
Referenced by NUnit.Engine.RuntimeFramework.RuntimeFramework().
VersionsMatch()
static bool NUnit.Engine.RuntimeFramework.VersionsMatch (Version v1, Version v2) inline static private
Referenced by NUnit.Engine.RuntimeFramework.Supports().
AppendMonoFrameworks()
static void NUnit.Engine.RuntimeFramework.AppendMonoFrameworks (List< RuntimeFramework > frameworks) inline static private
References NUnit.Engine.RuntimeFramework.AppendAllMonoFrameworks(), and NUnit.Engine.RuntimeFramework.AppendDefaultMonoFramework().
AppendAllMonoFrameworks()
static void NUnit.Engine.RuntimeFramework.AppendAllMonoFrameworks (List< RuntimeFramework > frameworks) inline static private
References NUnit.Engine.RuntimeFramework.AppendDefaultMonoFramework(), and NUnit.Engine.RuntimeFramework.AppendMonoFramework().
Referenced by NUnit.Engine.RuntimeFramework.AppendMonoFrameworks().
AppendDefaultMonoFramework()
static void NUnit.Engine.RuntimeFramework.AppendDefaultMonoFramework (List< RuntimeFramework > frameworks) inline static private
References NUnit.Engine.RuntimeFramework.AppendMonoFramework().
Referenced by NUnit.Engine.RuntimeFramework.AppendAllMonoFrameworks(), and NUnit.Engine.RuntimeFramework.AppendMonoFrameworks().
AppendMonoFramework()
static void NUnit.Engine.RuntimeFramework.AppendMonoFramework (List< RuntimeFramework > frameworks, string monoPrefix, string version) inline static private
References NUnit.Engine.RuntimeFramework.DisplayName, NUnit.Engine.RuntimeFramework.FrameworkVersion, and NUnit.Engine.RuntimeFramework.RuntimeFramework().
Referenced by NUnit.Engine.RuntimeFramework.AppendAllMonoFrameworks(), and NUnit.Engine.RuntimeFramework.AppendDefaultMonoFramework().
AppendDotNetFrameworks()
static void NUnit.Engine.RuntimeFramework.AppendDotNetFrameworks (List< RuntimeFramework > frameworks) inline static private
References NUnit.Engine.RuntimeFramework.AppendDotNetFourFrameworkVersions(), NUnit.Engine.RuntimeFramework.AppendExtremelyOldDotNetFrameworkVersions(), and NUnit.Engine.RuntimeFramework.AppendOlderDotNetFrameworkVersion().
AppendExtremelyOldDotNetFrameworkVersions()
static void NUnit.Engine.RuntimeFramework.AppendExtremelyOldDotNetFrameworkVersions (List< RuntimeFramework > frameworks) inline static private
References NUnit.Engine.RuntimeFramework.RuntimeFramework().
Referenced by NUnit.Engine.RuntimeFramework.AppendDotNetFrameworks().
AppendOlderDotNetFrameworkVersion()
static void NUnit.Engine.RuntimeFramework.AppendOlderDotNetFrameworkVersion (List< RuntimeFramework > frameworks, RegistryKey versionKey, Version version) inline static private
References NUnit.Engine.RuntimeFramework.CheckInstallDword(), and NUnit.Engine.RuntimeFramework.RuntimeFramework().
Referenced by NUnit.Engine.RuntimeFramework.AppendDotNetFrameworks().
AppendDotNetFourFrameworkVersions()
static void NUnit.Engine.RuntimeFramework.AppendDotNetFourFrameworkVersions (List< RuntimeFramework > frameworks, RegistryKey versionKey) inline static private
References NUnit.Engine.RuntimeFramework.CheckInstallDword(), and NUnit.Engine.RuntimeFramework.RuntimeFramework().
Referenced by NUnit.Engine.RuntimeFramework.AppendDotNetFrameworks().
CheckInstallDword()
static bool NUnit.Engine.RuntimeFramework.CheckInstallDword (RegistryKey key) inline static private
Referenced by NUnit.Engine.RuntimeFramework.AppendDotNetFourFrameworkVersions(), and NUnit.Engine.RuntimeFramework.AppendOlderDotNetFrameworkVersion().
Member Data Documentation
DefaultVersion
readonly Version NUnit.Engine.RuntimeFramework.DefaultVersion = new Version(0, 0) static
DefaultVersion is an empty Version, used to indicate that NUnit should select the CLR version to use for the test.
Referenced by NUnit.Engine.RuntimeFramework.GetDefaultDisplayName(), NUnit.Engine.RuntimeFramework.Parse(), and NUnit.Engine.Services.RuntimeFrameworkService.SelectRuntimeFramework().
currentFramework
RuntimeFramework NUnit.Engine.RuntimeFramework.currentFramework static private
availableFrameworks
RuntimeFramework [] NUnit.Engine.RuntimeFramework.availableFrameworks static private
Property Documentation
CurrentFramework
RuntimeFramework?? NUnit.Engine.RuntimeFramework.CurrentFramework static get
Static method to return a RuntimeFramework object for the framework that is currently in use.
Referenced by NUnit.Engine.Services.TestAgency.LaunchAgentProcess(), NUnit.Agent.NUnitTestAgent.Main(), NUnit.Engine.Services.RuntimeFrameworkService.SelectRuntimeFramework(), and NUnit.Engine.Runners.MasterTestRunner.ValidatePackageSettings().
AvailableFrameworks
RuntimeFramework [] NUnit.Engine.RuntimeFramework.AvailableFrameworks static get
Gets an array of all available frameworks
Referenced by NUnit.Engine.RuntimeFramework.GetBestAvailableFramework(), and NUnit.Engine.Services.RuntimeFrameworkService.IsAvailable().
IsAvailable
bool NUnit.Engine.RuntimeFramework.IsAvailable get
Returns true if the current RuntimeFramework is available. In the current implementation, only Mono and Microsoft .NET are supported.
Returns
True if it's available, false if not
Referenced by NUnit.Engine.Services.TestAgency.LaunchAgentProcess(), and NUnit.Engine.Services.RuntimeFrameworkService.SelectRuntimeFramework().
Runtime
RuntimeType NUnit.Engine.RuntimeFramework.Runtime get private set
The type of this runtime framework
Referenced by NUnit.Engine.Services.RuntimeFrameworkService.FrameworksMatch(), NUnit.Engine.RuntimeFramework.InitFromClrVersion(), NUnit.Engine.RuntimeFramework.InitFromFrameworkVersion(), NUnit.Engine.Services.TestAgency.LaunchAgentProcess(), NUnit.Engine.RuntimeFramework.RuntimeFramework(), NUnit.Engine.Services.RuntimeFrameworkService.SelectRuntimeFramework(), NUnit.Engine.RuntimeFramework.Supports(), and NUnit.Engine.RuntimeFramework.ToString().
FrameworkVersion
Version NUnit.Engine.RuntimeFramework.FrameworkVersion get private set
The framework version for this runtime framework
Referenced by NUnit.Engine.RuntimeFramework.AppendMonoFramework(), NUnit.Engine.Services.RuntimeFrameworkService.FrameworksMatch(), NUnit.Engine.RuntimeFramework.InitFromClrVersion(), NUnit.Engine.RuntimeFramework.InitFromFrameworkVersion(), NUnit.Engine.Services.RuntimeFrameworkService.SelectRuntimeFramework(), NUnit.Engine.RuntimeFramework.Supports(), and NUnit.Engine.RuntimeFramework.ToString().
ClrVersion
Version NUnit.Engine.RuntimeFramework.ClrVersion get private set
The CLR version for this runtime framework
Referenced by NUnit.Engine.Services.RuntimeFrameworkService.FrameworksMatch(), NUnit.Engine.RuntimeFramework.GetBestAvailableFramework(), NUnit.Engine.RuntimeFramework.InitFromClrVersion(), NUnit.Engine.RuntimeFramework.InitFromFrameworkVersion(), NUnit.Engine.Services.TestAgency.LaunchAgentProcess(), and NUnit.Engine.RuntimeFramework.Supports().
AllowAnyVersion
bool NUnit.Engine.RuntimeFramework.AllowAnyVersion get
Return true if any CLR version may be used in matching this RuntimeFramework object.
Referenced by NUnit.Engine.RuntimeFramework.Supports(), and NUnit.Engine.RuntimeFramework.ToString().
DisplayName
string NUnit.Engine.RuntimeFramework.DisplayName get private set
Returns the Display name for this framework
Referenced by NUnit.Engine.RuntimeFramework.AppendMonoFramework(), NUnit.Agent.NUnitTestAgent.Main(), and NUnit.Engine.RuntimeFramework.RuntimeFramework().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/RuntimeFramework.cs