Doc: IGLib EXTENDED: AForge.Imaging.Drawing Class Reference
AForge.Imaging.Drawing Class Reference
Drawing primitives.
Static Public Member Functions
static unsafe void FillRectangle (BitmapData imageData, Rectangle rectangle, Color color)
Fill rectangle on the specified image.
static unsafe void FillRectangle (UnmanagedImage image, Rectangle rectangle, Color color)
Fill rectangle on the specified image.
static unsafe void Rectangle (BitmapData imageData, Rectangle rectangle, Color color)
Draw rectangle on the specified image.
static unsafe void Rectangle (UnmanagedImage image, Rectangle rectangle, Color color)
Draw rectangle on the specified image.
static unsafe void Line (BitmapData imageData, IntPoint point1, IntPoint point2, Color color)
Draw a line on the specified image.
static unsafe void Line (UnmanagedImage image, IntPoint point1, IntPoint point2, Color color)
Draw a line on the specified image.
static void Polygon (BitmapData imageData, List< IntPoint > points, Color color)
Draw a polygon on the specified image.
static void Polygon (UnmanagedImage image, List< IntPoint > points, Color color)
Draw a polygon on the specified image.
static void Polyline (BitmapData imageData, List< IntPoint > points, Color color)
Draw a polyline on the specified image.
static void Polyline (UnmanagedImage image, List< IntPoint > points, Color color)
Draw a polyline on the specified image.
Static Private Member Functions
static void CheckPixelFormat (PixelFormat format)
static void CheckEndPoint (int width, int height, IntPoint start, ref IntPoint end)
Detailed Description
Drawing primitives.
The class allows to do drawing of some primitives directly on locked image data or unmanaged image.
<note>All methods of this class support drawing only on color 24/32 bpp images and on grayscale 8 bpp indexed images.</note>
<note>When it comes to alpha blending for 24/32 bpp images, all calculations are done as described on Wikipeadia (see "over" operator).</note>
Member Function Documentation
FillRectangle() [1/2]
static unsafe void AForge.Imaging.Drawing.FillRectangle (BitmapData imageData, Rectangle rectangle, Color color) inline static
Fill rectangle on the specified image.
Parameters
imageData Source image data to draw on.
rectangle Rectangle's coordinates to fill.
color Rectangle's color.
Exceptions
UnsupportedImageFormatException The source image has incorrect pixel format.
Referenced by AForge.Imaging.Tests.UnmanagedImageTest.CollectActivePixelsTest().
FillRectangle() [2/2]
static unsafe void AForge.Imaging.Drawing.FillRectangle (UnmanagedImage image, Rectangle rectangle, Color color) inline static
Fill rectangle on the specified image.
Parameters
image Source image to draw on.
rectangle Rectangle's coordinates to fill.
color Rectangle's color.
Exceptions
UnsupportedImageFormatException The source image has incorrect pixel format.
References AForge.Imaging.RGB.A, AForge.Imaging.RGB.B, AForge.Imaging.Drawing.CheckPixelFormat(), AForge.Imaging.RGB.G, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, AForge.SystemTools.SetUnmanagedMemory(), AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
Rectangle() [1/2]
static unsafe void AForge.Imaging.Drawing.Rectangle (BitmapData imageData, Rectangle rectangle, Color color) inline static
Draw rectangle on the specified image.
Parameters
imageData Source image data to draw on.
rectangle Rectangle's coordinates to draw.
color Rectangle's color.
Exceptions
UnsupportedImageFormatException The source image has incorrect pixel format.
Referenced by AForge.Vision.Motion.BlobCountingObjectsProcessing.ProcessFrame().
Rectangle() [2/2]
static unsafe void AForge.Imaging.Drawing.Rectangle (UnmanagedImage image, Rectangle rectangle, Color color) inline static
Draw rectangle on the specified image.
Parameters
image Source image to draw on.
rectangle Rectangle's coordinates to draw.
color Rectangle's color.
Exceptions
UnsupportedImageFormatException The source image has incorrect pixel format.
References AForge.Imaging.Drawing.CheckPixelFormat(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.Drawing.Line(), AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
Line() [1/2]
static unsafe void AForge.Imaging.Drawing.Line (BitmapData imageData, IntPoint point1, IntPoint point2, Color color) inline static
Draw a line on the specified image.
Parameters
imageData Source image data to draw on.
point1 The first point to connect.
point2 The second point to connect.
color Line's color.
Exceptions
UnsupportedImageFormatException The source image has incorrect pixel format.
Referenced by AForge.Imaging.Tests.UnmanagedImageTest.Collect8bppPixelValuesTest_Grayscale(), AForge.Imaging.Tests.UnmanagedImageTest.Collect8bppPixelValuesTest_RGB(), MotionDetectorSample.MainForm.DrawMotionHistory(), AForge.Imaging.Drawing.Polygon(), AForge.Imaging.Drawing.Polyline(), and AForge.Imaging.Drawing.Rectangle().
Line() [2/2]
static unsafe void AForge.Imaging.Drawing.Line (UnmanagedImage image, IntPoint point1, IntPoint point2, Color color) inline static
Draw a line on the specified image.
Parameters
image Source image to draw on.
point1 The first point to connect.
point2 The second point to connect.
color Line's color.
Exceptions
UnsupportedImageFormatException The source image has incorrect pixel format.
References AForge.Imaging.RGB.A, AForge.Imaging.RGB.B, AForge.Imaging.Drawing.CheckEndPoint(), AForge.Imaging.Drawing.CheckPixelFormat(), AForge.Imaging.RGB.G, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, AForge.Imaging.UnmanagedImage.Stride, AForge.Imaging.UnmanagedImage.Width, AForge.IntPoint.X, and AForge.IntPoint.Y.
Polygon() [1/2]
static void AForge.Imaging.Drawing.Polygon (BitmapData imageData, List< IntPoint > points, Color color) inline static
Draw a polygon on the specified image.
Parameters
imageData Source image data to draw on.
points Points of the polygon to draw.
color Polygon's color.
The method draws a polygon by connecting all points from the first one to the last one and then connecting the last point with the first one.
Polygon() [2/2]
static void AForge.Imaging.Drawing.Polygon (UnmanagedImage image, List< IntPoint > points, Color color) inline static
Draw a polygon on the specified image.
Parameters
image Source image to draw on.
points Points of the polygon to draw.
color Polygon's color.
The method draws a polygon by connecting all points from the first one to the last one and then connecting the last point with the first one.
References AForge.Imaging.Drawing.Line().
Polyline() [1/2]
static void AForge.Imaging.Drawing.Polyline (BitmapData imageData, List< IntPoint > points, Color color) inline static
Draw a polyline on the specified image.
Parameters
imageData Source image data to draw on.
points Points of the polyline to draw.
color polyline's color.
The method draws a polyline by connecting all points from the first one to the last one. Unlike Polygon(BitmapData, List<IntPoint>, Color) method, this method does not connect the last point with the first one.
Polyline() [2/2]
static void AForge.Imaging.Drawing.Polyline (UnmanagedImage image, List< IntPoint > points, Color color) inline static
Draw a polyline on the specified image.
Parameters
image Source image to draw on.
points Points of the polyline to draw.
color polyline's color.
The method draws a polyline by connecting all points from the first one to the last one. Unlike Polygon(UnmanagedImage, List<IntPoint>, Color) method, this method does not connect the last point with the first one.
References AForge.Imaging.Drawing.Line().
CheckPixelFormat()
static void AForge.Imaging.Drawing.CheckPixelFormat (PixelFormat format) inline static private
Referenced by AForge.Imaging.Drawing.FillRectangle(), AForge.Imaging.Drawing.Line(), and AForge.Imaging.Drawing.Rectangle().
CheckEndPoint()
static void AForge.Imaging.Drawing.CheckEndPoint (int width, int height, IntPoint start, ref IntPoint end) inline static private
References AForge.IntPoint.X, and AForge.IntPoint.Y.
Referenced by AForge.Imaging.Drawing.Line().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Drawing.cs