Doc: IGLib EXTENDED: NUnit.Framework.Internal.GenericMethodHelper Class Reference
NUnit.Framework.Internal.GenericMethodHelper Class Reference
GenericMethodHelper is able to deduce the Type arguments for a generic method from the actual arguments provided.
Public Member Functions
GenericMethodHelper (MethodInfo method)
Construct a GenericMethodHelper for a method
Type[] GetTypeArguments (object[] argList)
Return the type argments for the method, deducing them from the arguments actually provided.
Properties
MethodInfo Method [get, set]
Type[] TypeParms [get, set]
Type[] TypeArgs [get, set]
Type[] ParmTypes [get, set]
Private Member Functions
void TryApplyArgType (Type parmType, Type argType)
void ApplyArgType (Type parmType, Type argType)
bool IsAssignableToGenericType (Type givenType, Type genericType)
Detailed Description
GenericMethodHelper is able to deduce the Type arguments for a generic method from the actual arguments provided.
Constructor & Destructor Documentation
GenericMethodHelper()
NUnit.Framework.Internal.GenericMethodHelper.GenericMethodHelper (MethodInfo method) inline
Construct a GenericMethodHelper for a method
Parameters
method MethodInfo for the method to examine
References NUnit.Framework.Internal.GenericMethodHelper.Method, NUnit.Framework.Internal.GenericMethodHelper.ParmTypes, NUnit.Framework.Internal.GenericMethodHelper.TypeArgs, and NUnit.Framework.Internal.GenericMethodHelper.TypeParms.
Member Function Documentation
GetTypeArguments()
Type [] NUnit.Framework.Internal.GenericMethodHelper.GetTypeArguments (object[] argList) inline
Return the type argments for the method, deducing them from the arguments actually provided.
Parameters
argList The arguments to the method
Returns
An array of type arguments.
References NUnit.Framework.Internal.GenericMethodHelper.ParmTypes, NUnit.Framework.Internal.GenericMethodHelper.TryApplyArgType(), and NUnit.Framework.Internal.GenericMethodHelper.TypeArgs.
Referenced by NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.CheckTestMethodSignature().
TryApplyArgType()
void NUnit.Framework.Internal.GenericMethodHelper.TryApplyArgType (Type parmType, Type argType) inline private
References NUnit.Framework.Internal.GenericMethodHelper.ApplyArgType(), and NUnit.Framework.Internal.GenericMethodHelper.IsAssignableToGenericType().
Referenced by NUnit.Framework.Internal.GenericMethodHelper.GetTypeArguments().
ApplyArgType()
void NUnit.Framework.Internal.GenericMethodHelper.ApplyArgType (Type parmType, Type argType) inline private
References NUnit.Framework.Internal.TypeHelper.BestCommonType(), NUnit.Framework.Internal.GenericMethodHelper.TypeArgs, and NUnit.Framework.Internal.GenericMethodHelper.TypeParms.
Referenced by NUnit.Framework.Internal.GenericMethodHelper.TryApplyArgType().
IsAssignableToGenericType()
bool NUnit.Framework.Internal.GenericMethodHelper.IsAssignableToGenericType (Type givenType, Type genericType) inline private
Referenced by NUnit.Framework.Internal.GenericMethodHelper.TryApplyArgType().
Property Documentation
Method
MethodInfo NUnit.Framework.Internal.GenericMethodHelper.Method get set private
Referenced by NUnit.Framework.Internal.GenericMethodHelper.GenericMethodHelper().
TypeParms
Type [] NUnit.Framework.Internal.GenericMethodHelper.TypeParms get set private
Referenced by NUnit.Framework.Internal.GenericMethodHelper.ApplyArgType(), and NUnit.Framework.Internal.GenericMethodHelper.GenericMethodHelper().
TypeArgs
Type [] NUnit.Framework.Internal.GenericMethodHelper.TypeArgs get set private
Referenced by NUnit.Framework.Internal.GenericMethodHelper.ApplyArgType(), NUnit.Framework.Internal.GenericMethodHelper.GenericMethodHelper(), and NUnit.Framework.Internal.GenericMethodHelper.GetTypeArguments().
ParmTypes
Type [] NUnit.Framework.Internal.GenericMethodHelper.ParmTypes get set private
Referenced by NUnit.Framework.Internal.GenericMethodHelper.GenericMethodHelper(), and NUnit.Framework.Internal.GenericMethodHelper.GetTypeArguments().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/GenericMethodHelper.cs