Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DORGHR Class Reference
DotNumerics.LinearAlgebra.CSLapack.DORGHR Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DORGHR (DORGQR dorgqr, XERBLA xerbla, ILAENV ilaenv)
DORGHR ()
void Run (int N, int ILO, int IHI, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
DORGQR _dorgqr
XERBLA _xerbla
ILAENV _ilaenv
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DORGHR generates a real orthogonal matrix Q which is defined as the product of IHI-ILO elementary reflectors of order N, as returned by DGEHRD:
Q = H(ilo) H(ilo+1) . . . H(ihi-1).
/summary>
Constructor & Destructor Documentation
DORGHR() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DORGHR.DORGHR (DORGQR dorgqr, XERBLA xerbla, ILAENV ilaenv) inline
DORGHR() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DORGHR.DORGHR () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DORGHR.Run (int N, int ILO, int IHI, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DORGHR generates a real orthogonal matrix Q which is defined as the product of IHI-ILO elementary reflectors of order N, as returned by DGEHRD:
Q = H(ilo) H(ilo+1) . . . H(ihi-1).
/summary>
Parameters
N (input) INTEGER The order of the matrix Q. N .GE. 0. /param>
Parameters
ILO (input) INTEGER /param>
Parameters
IHI (input) INTEGER ILO and IHI must have the same values as in the previous call of DGEHRD. Q is equal to the unit matrix except in the submatrix Q(ilo+1:ihi,ilo+1:ihi). 1 .LE. ILO .LE. IHI .LE. N, if N .GT. 0; ILO=1 and IHI=0, if N=0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the vectors which define the elementary reflectors, as returned by DGEHRD. On exit, the N-by-N orthogonal matrix Q. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,N). /param>
Parameters
TAU (input) DOUBLE PRECISION array, dimension (N-1) TAU(i) must contain the scalar factor of the elementary reflector H(i), as returned by DGEHRD. /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. IHI-ILO. For optimum performance LWORK .GE. (IHI-ILO)*NB, where NB is the optimal blocksize.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.DORGHR.ONE, DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGQR.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DORGHR.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR2.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAQR3.Run().
Member Data Documentation
_dorgqr
DORGQR DotNumerics.LinearAlgebra.CSLapack.DORGHR._dorgqr private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DORGHR._xerbla private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DORGHR._ilaenv private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DORGHR.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORGHR.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DORGHR.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORGHR.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dorghr.cs