Doc: IGLib EXTENDED: alglib.testhqrndunit Class Reference
alglib.testhqrndunit Class Reference
Static Public Member Functions
static bool testhqrnd (bool silent)
static bool hqrndcontinuoustest (bool silent)
static bool hqrnddiscretetest (bool silent)
static bool testhqrnd (bool silent)
static bool _pexec_testhqrnd (bool silent)
static bool hqrndcontinuoustest (bool silent)
static bool hqrnddiscretetest (bool silent)
Static Private Member Functions
static void calculatemv (double[] x, int n, ref double mean, ref double means, ref double stddev, ref double stddevs)
static void unsetstate (hqrnd.hqrndstate state)
static void calculatemv (double[] x, int n, ref double mean, ref double means, ref double stddev, ref double stddevs)
static void unsetstate (hqrnd.hqrndstate state)
Member Function Documentation
testhqrnd() [1/2]
static bool alglib.testhqrndunit.testhqrnd (bool silent) inline static
References alglib.testhqrndunit.calculatemv(), alglib.testhqrndunit.hqrndcontinuoustest(), alglib.testhqrndunit.hqrnddiscretetest(), alglib.hqrnd.hqrndexponential(), alglib.hqrnd.hqrndnormal2(), alglib.hqrnd.hqrndrandomize(), alglib.hqrnd.hqrndseed(), alglib.hqrnd.hqrnduniformi(), alglib.hqrnd.hqrnduniformr(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.math.sqr(), and alglib.testhqrndunit.unsetstate().
Referenced by alglib.testhqrndunit._pexec_testhqrnd(), and _Test.Main().
hqrndcontinuoustest() [1/2]
static bool alglib.testhqrndunit.hqrndcontinuoustest (bool silent) inline static
References alglib.hqrnd.hqrndcontinuous(), alglib.hqrnd.hqrndrandomize(), and alglib.math.randomreal().
Referenced by alglib.testhqrndunit.testhqrnd().
hqrnddiscretetest() [1/2]
static bool alglib.testhqrndunit.hqrnddiscretetest (bool silent) inline static
References alglib.hqrnd.hqrnddiscrete(), alglib.hqrnd.hqrndseed(), alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testhqrndunit.testhqrnd().
calculatemv() [1/2]
static void alglib.testhqrndunit.calculatemv (double[] x, int n, ref double mean, ref double means, ref double stddev, ref double stddevs) inline static private
References alglib.math.sqr().
Referenced by alglib.testhqrndunit.testhqrnd().
unsetstate() [1/2]
static void alglib.testhqrndunit.unsetstate (hqrnd.hqrndstate state) inline static private
Referenced by alglib.testhqrndunit.testhqrnd().
testhqrnd() [2/2]
static bool alglib.testhqrndunit.testhqrnd (bool silent) inline static
References alglib.testhqrndunit.calculatemv(), alglib.testhqrndunit.hqrndcontinuoustest(), alglib.testhqrndunit.hqrnddiscretetest(), alglib.hqrnd.hqrndexponential(), alglib.hqrnd.hqrndnormal2(), alglib.hqrnd.hqrndrandomize(), alglib.hqrnd.hqrndseed(), alglib.hqrnd.hqrnduniformi(), alglib.hqrnd.hqrnduniformr(), alglib.hqrnd.hqrndunit2(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.apserv.seterrorflag(), alglib.math.sqr(), and alglib.testhqrndunit.unsetstate().
_pexec_testhqrnd()
static bool alglib.testhqrndunit._pexec_testhqrnd (bool silent) inline static
References alglib.testhqrndunit.testhqrnd().
Referenced by _Test.Main().
hqrndcontinuoustest() [2/2]
static bool alglib.testhqrndunit.hqrndcontinuoustest (bool silent) inline static
References alglib.hqrnd.hqrndcontinuous(), alglib.hqrnd.hqrndrandomize(), and alglib.math.randomreal().
hqrnddiscretetest() [2/2]
static bool alglib.testhqrndunit.hqrnddiscretetest (bool silent) inline static
References alglib.hqrnd.hqrnddiscrete(), alglib.hqrnd.hqrndseed(), alglib.math.randominteger(), and alglib.math.randomreal().
calculatemv() [2/2]
static void alglib.testhqrndunit.calculatemv (double[] x, int n, ref double mean, ref double means, ref double stddev, ref double stddevs) inline static private
References alglib.math.sqr().
unsetstate() [2/2]
static void alglib.testhqrndunit.unsetstate (hqrnd.hqrndstate state) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs