Doc: IGLib EXTENDED: NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality Class Reference
NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality Class Reference
Public Member Functions
void CanMatchDates ()
void CanMatchDatesWithinTimeSpan ()
void CanMatchDatesWithinDays ()
void CanMatchDatesWithinHours ()
void CanMatchUsingIsEqualToWithinTimeSpan ()
void CanMatchDatesWithinMinutes ()
void CanMatchTimeSpanWithinMinutes ()
void CanMatchDatesWithinSeconds ()
void CanMatchDatesWithinMilliseconds ()
void CanMatchDatesWithinTicks ()
void ErrorIfDaysPrecedesWithin ()
void ErrorIfHoursPrecedesWithin ()
void ErrorIfMinutesPrecedesWithin ()
void ErrorIfSecondsPrecedesWithin ()
void ErrorIfMillisecondsPrecedesWithin ()
void ErrorIfTicksPrecedesWithin ()
Member Function Documentation
CanMatchDates()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchDates () inline
References NUnit.Framework.Assert.That().
CanMatchDatesWithinTimeSpan()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchDatesWithinTimeSpan () inline
References NUnit.Framework.Assert.That().
CanMatchDatesWithinDays()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchDatesWithinDays () inline
References NUnit.Framework.Assert.That().
CanMatchDatesWithinHours()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchDatesWithinHours () inline
References NUnit.Framework.Assert.That().
CanMatchUsingIsEqualToWithinTimeSpan()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchUsingIsEqualToWithinTimeSpan () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
CanMatchDatesWithinMinutes()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchDatesWithinMinutes () inline
References NUnit.Framework.Assert.That().
CanMatchTimeSpanWithinMinutes()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchTimeSpanWithinMinutes () inline
References NUnit.Framework.Assert.That().
CanMatchDatesWithinSeconds()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchDatesWithinSeconds () inline
References NUnit.Framework.Assert.That().
CanMatchDatesWithinMilliseconds()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchDatesWithinMilliseconds () inline
References NUnit.Framework.Assert.That().
CanMatchDatesWithinTicks()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.CanMatchDatesWithinTicks () inline
References NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.EqualConstraint.Ticks.
ErrorIfDaysPrecedesWithin()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfDaysPrecedesWithin () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
ErrorIfHoursPrecedesWithin()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfHoursPrecedesWithin () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
ErrorIfMinutesPrecedesWithin()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfMinutesPrecedesWithin () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
ErrorIfSecondsPrecedesWithin()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfSecondsPrecedesWithin () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
ErrorIfMillisecondsPrecedesWithin()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfMillisecondsPrecedesWithin () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
ErrorIfTicksPrecedesWithin()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeEquality.ErrorIfTicksPrecedesWithin () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/EqualConstraintTests.cs