Doc: IGLib EXTENDED: IG.Lib.LoadableScriptBase Class Reference
IG.Lib.LoadableScriptBase Class Reference abstract
Base class for classes that can be dynamically loadeded from scripts and run, which provides functionality of dynamic scripting. It is recommendable to derive all such classes that implement the ILoadableScript interface from this base class.
Classes
class Script_CommandAdapter
Adapts that converts internal script commands (delegate of type Script_CommandDelegate) to interpreter commands.
class StoredScriptSettings
In methods of this class you will find all the settings that apply to this script.
Public Member Functions
LoadableScriptBase ()
Argument-less constructor. If argument-less constructor is called then initialization is not performed and will be performed later.
string Run (string[] arguments)
Performs the action of this object. Override this in derived classes!
void Initialize (string[] arguments)
Initializes the object. If not called explicitly, this method is automatically called at the first call to the Run method.
virtual string Script_DefaultInitialize (string[] arguments)
Default initialization method for scripts.
virtual string Script_DefaultRun (string[] arguments)
Default run method for the script. Can be used when only installed commands are run by hte script.
virtual ICommandLineApplicationInterpreter Script_CreateInterpreterWithoutCommands ()
Creates and returns an interpreter that can be used as script's internal interpreter for running script's commands.
virtual void Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings)
Add wscript's internal commands to the specified interpreter.
delegate string Script_CommandDelegate (string[] args)
Delegate for commands that are installed on script's internal interpreter (property Script_Interpreter).
void Script_AddCommand (string commandName, Script_CommandDelegate command, string helpString)
Adds a new internal script command under specified name to the internal interpreter of the current script object.
virtual void Script_AddCommand (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings, string commandName, Script_CommandDelegate command, string helpString)
Adds a new internal script command under specified name to the internal interpreter of the current script object.
string Script_GetHelpString (string scriptCommandName)
Returns help string for internal script command with specified name, or null if help string is not installed for such a command.
void Script_PrintCommandsHelp ()
Prits help for the installed internal commands of the script.
virtual bool Script_ContainsCommand (string commandName)
Returns true if the internal script's interpreter contains a command with specified name, false otherwise.
virtual bool Script_ContainsScriptCommand (string commandName)
Returns true if the specified command is script command (i.e. its first argument is command-name and it is run through the Script_CommandAdapter object).
virtual void Script_RemoveCommand (string commandName)
Removes the specified internal script command from the internal interpreter of the current scripting object.
virtual void Script_RemoveAllCommands ()
Removes ALL internal script commands from the internal interpreter of the current scripting object.
string Script_Run (string[] arguments)
Runs internal script command.
string Script_Run (string commandName, params string[] otherArguments)
Runs internal script command.
virtual void Script_PrintArguments (string messageString, string[] arguments)
Prints the specified array of string arguments (usually passed as command-line arguments).
Static Public Attributes
const string ConstDefaultHelp = "Help"
Default command name for help.
const string ConstHelpDefaultUniversal = "?"
Universal name of the help command.
const string ConstDefaultTestScrip = "TestScript"
Default command name for test method.
Protected Member Functions
delegate string CommandMethod (string commandName, string[] args)
Delegate for internal command methods.
abstract string RunThis (string[] arguments)
Performs the action of this object. Override this in derived classes!
abstract void InitializeThis (string[] arguments)
Performs all the necessary initializations of the object. Override this method in derived classes (if extra initialization is needed) and call the base class' method in it.
ICommandLineApplicationInterpreter Script_CreateInterpreter ()
Creates and returns an interpreter that can be used as script's internal interpreter for running script's commands.
virtual string Script_CommandHelp (string[] arguments)
Prints help.
virtual string Script_CommandTestScript (string[] arguments)
Prints help.
Protected Attributes
string _embeddedCommandName = null
int _outputLevel = DefaultOutputLevel
ICommandLineApplicationInterpreter _script_interpreter
Properties
string EmbeddedCommandName [get, set]
Command that was used to launch the current embedded application script.
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
string[] InitializationArguments [get, set]
Arguments used by the initialization method. WARNING: arguments can only be set before initialization is performed. Initialization is performed either implicitly at the first call to the Run method or explicitly by calling the Initialize method.
virtual bool IsInitialized [get, protected set]
Whether the object has been initialized or not.
static int DefaultOutputLevel [get, set]
int OutputLevel [get, set]
Level of output to console produced by some operations of the current object.
virtual ICommandLineApplicationInterpreter Script_Interpreter [get, protected set]
Script's internal interpreter that takes care for execution of installed internal commands.
SortedList< string, string > Script_CommandHelpStrings [get]
Contains help strings associated with script commands installed on interpreter.
Properties inherited from IG.Lib.ILoadableScript
string EmbeddedCommandName [get, set]
Command that was used to launch the current embedded application script.
string[] InitializationArguments [get, set]
Arguments used by the initialization method.
bool IsInitialized [get]
Whether the object has been initialized or not.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
object _mainLock = new object()
string[] _initializationArguments
bool _isInitialized = false
SortedList< string, string > _script_CommandHelpStrings
Static Private Attributes
static int _defaultOutputLevel = -1
Detailed Description
Base class for classes that can be dynamically loadeded from scripts and run, which provides functionality of dynamic scripting. It is recommendable to derive all such classes that implement the ILoadableScript interface from this base class.
Initialization of objects of this class can be performed by the Initialize method. If not performed explicitly, initialization is perform automatically at the first call to teh Run() method.
$A Igor Jul09 May10;
Constructor & Destructor Documentation
LoadableScriptBase()
IG.Lib.LoadableScriptBase.LoadableScriptBase () inline
Argument-less constructor. If argument-less constructor is called then initialization is not performed and will be performed later.
Member Function Documentation
CommandMethod()
delegate string IG.Lib.LoadableScriptBase.CommandMethod (string commandName, string[] args) protected
Delegate for internal command methods.
Parameters
commandName Name of the internal command.
args Arguments to the command.
Returns
Referenced by IG.Script.ScriptGraphics3DBase.Run3DSurfaceTest(), IG.Script.ScriptGraphics2dBase.RunTestGraph(), IG.Script.ScriptGraphics3DBase.RunTestPlot3d(), and IG.Script.ScriptGraphics3DBase.RunTestVtk().
RunThis()
abstract string IG.Lib.LoadableScriptBase.RunThis (string[] arguments) protected pure virtual
Performs the action of this object. Override this in derived classes!
Parameters
arguments Arguments through which different information can be passed.
Returns
String that represents result of the action.
Implemented in IG.Script.LoadableScriptSpecialFunctionBase, IG.Lib.LoadableScriptOptTest.LoadableScriptOptDerived, IG.Script.S_12_03_paper_gk, IG.Script.S_12_01_Paper_NeuralOptCasting_00, IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00, IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00, IG.Script.S_11_10_clanek_neural_00, IG.Script.S_13_5_Convection, IG.Script.S_12_09_jmatpro, IG.Script.S_12_09_jmatpro, IG.Script.Script_11_10_clanek_neural_01, IG.Script.Script2, IG.Script.LoadableScriptExample, IG.Script.S_TestExt3, IG.Script.S_TestNeural3, IG.Script.S_TestExt3, IG.Script.S_12_02_paper_neural_process_chain_model, IG.Script.LoadableScriptShellNeural, IG.Script.S_12_02_paper_neural_process_chain_model, IG.Script.S_TestOpt3, IG.Lib.LoadableScriptRealFunctionBase, IG.Script.TestClass1, IG.Script.S_TestExt1, IG.Script.S_TestNeural1, IG.Script.S_TestShellExt1, IG.Script.S_TestOpt1, IG.Script.Scrip_OdeChem, IG.Lib.LoadableScriptScalarFunctionBase, IG.Script.ScriptGraphics3DBase, IG.Script.ScriptExtNumeric, IG.Script.S_TestExt2, IG.Script.S_TestNeural2, IG.Script.S_TestExt2, IG.Script.S_TestOpt2, IG.Script.ScriptGraphics2dBase, IG.Script.ScriptExtExamples, IG.Script.ScriptExtExamplesExt, IG.Script.ScriptOptTemplate, IG.Script.Script_Examples, IG.Script.Script_Misc, IG.Script.Script_Optimization, IG.Script.ScriptOptTemplateExt, IG.Script.ScriptExtTemplate, IG.Script.ScriptNeuralTemplate, IG.Script.ScriptExtTemplate, IG.Script.ScriptExtTemplate, IG.Script.Script_Numeric, IG.Script.ScriptNeuralExamples, IG.Script.ScriptExtExamples, IG.Script.ScriptExtFormats, IG.Script.ScriptExtFormats, IG.Script.TestIglibExt_ToDelete, IG.Script.NeuralTestScript, and IG.Script.NeuralTestScriptShellExt.
Referenced by IG.Lib.LoadableScriptBase.Run().
InitializeThis()
abstract void IG.Lib.LoadableScriptBase.InitializeThis (string[] arguments) protected pure virtual
Performs all the necessary initializations of the object. Override this method in derived classes (if extra initialization is needed) and call the base class' method in it.
Implemented in IG.Script.LoadableScriptSpecialFunctionBase, IG.Lib.LoadableScriptOptTest.LoadableScriptOptDerived, IG.Lib.LoadableScriptOptShellBaseControllable, IG.Script.S_12_09_jmatpro, IG.Script.S_12_09_jmatpro, IG.Script.LoadableScriptShellNeuralBase, IG.Script.LoadableScriptShellNeuralITOriginalBase, IG.Script.LoadableScriptExample, IG.Lib.LoadableScriptRealFunctionBase, IG.Script.LoadableScriptShellNeural, IG.Script.S_11_10_clanek_neural_00, IG.Script.Script_11_10_clanek_neural_01, IG.Script.LoadableScriptShellNeuralIT, IG.Lib.LoadableScriptShellBase, IG.Lib.LoadableScriptOptBase, IG.Lib.LoadableScriptScalarFunctionBase, IG.Script.S_12_01_Paper_NeuralOptCasting_00, IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00, IG.Script.S_12_02_paper_neural_process_chain_model, IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00, IG.Lib.LoadableScriptShellBase, IG.Script.S_12_02_paper_neural_process_chain_model, IG.Script.S_12_03_paper_gk, IG.Script.Scrip_OdeChem, IG.Script.ScriptGraphics3DBase, IG.Script.ScriptExtNumeric, IG.Script.ScriptGraphics2dBase, IG.Script.ScriptExtExamples, IG.Script.Script2, IG.Script.S_TestExt3, IG.Script.S_TestNeural3, IG.Script.S_TestExt3, IG.Script.ScriptExtExamplesExt, IG.Script.ScriptOptTemplate, IG.Script.Script_Examples, IG.Script.Script_Misc, IG.Script.Script_Optimization, IG.Script.ScriptOptTemplateExt, IG.Script.ScriptExtTemplate, IG.Script.ScriptNeuralTemplate, IG.Script.ScriptExtTemplate, IG.Script.ScriptExtTemplate, IG.Script.Script_Numeric, IG.Script.S_13_5_Convection, IG.Script.S_13_7_ConvectionRev1, IG.Script.ScriptNeuralExamples, IG.Script.ScriptExtExamples, IG.Script.ScriptExtFormats, IG.Script.ScriptExtFormats, IG.Script.S_TestExt1, IG.Script.S_TestExt2, IG.Script.S_TestNeural1, IG.Script.S_TestNeural2, IG.Script.S_TestShellExt1, IG.Script.S_TestExt2, IG.Script.S_TestOpt1, IG.Script.S_TestOpt2, IG.Script.S_TestOpt3, IG.Script.TestClass1, and IG.Script.TestIglibExt_ToDelete.
Referenced by IG.Lib.LoadableScriptBase.Initialize().
Run()
string IG.Lib.LoadableScriptBase.Run (string[] arguments) inline
Performs the action of this object. Override this in derived classes!
Parameters
arguments Arguments through which different information can be passed.
Returns
String that represents result of the action.
Implements IG.Lib.ILoadableScript.
References IG.Lib.LoadableScriptBase.InitializationArguments, IG.Lib.LoadableScriptBase.Initialize(), IG.Lib.LoadableScriptBase.IsInitialized, IG.Lib.LoadableScriptBase.Lock, and IG.Lib.LoadableScriptBase.RunThis().
Referenced by IG.Script.AppIgorForFerdo.AppExGraphics(), IG.Script.AppIgorGresovnik.AppExGraphics(), IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00.ExampleRunFromCode(), and IG.App.ProgramExampleIJS.ExampleUsingScriptIJS().
Initialize()
void IG.Lib.LoadableScriptBase.Initialize (string[] arguments) inline
Initializes the object. If not called explicitly, this method is automatically called at the first call to the Run method.
Implements IG.Lib.ILoadableScript.
References IG.Lib.LoadableScriptBase.InitializationArguments, IG.Lib.LoadableScriptBase.InitializeThis(), IG.Lib.LoadableScriptBase.IsInitialized, and IG.Lib.LoadableScriptBase.Lock.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00.ExampleRunFromCode(), IG.App.ProgramExampleIJS.ExampleUsingScriptIJS(), IG.Test.ProgramTestIgor.MainDefault(), and IG.Lib.LoadableScriptBase.Run().
Script_DefaultInitialize()
virtual string IG.Lib.LoadableScriptBase.Script_DefaultInitialize (string[] arguments) inline virtual
Default initialization method for scripts.
Parameters
arguments Initialization arguments.
Returns
null string.
References IG.Lib.LoadableScriptBase.OutputLevel, and IG.Lib.LoadableScriptBase.Script_PrintArguments().
Referenced by IG.Script.ScriptExtFormats.InitializeThis(), IG.Script.ScriptNeuralExamples.InitializeThis(), IG.Script.ScriptNeuralTemplate.InitializeThis(), IG.Script.ScriptExtTemplate.InitializeThis(), IG.Script.ScriptOptTemplate.InitializeThis(), IG.Script.ScriptOptTemplateExt.InitializeThis(), IG.Script.Script_Optimization.InitializeThis(), IG.Script.Script_Examples.InitializeThis(), IG.Script.ScriptExtExamplesExt.InitializeThis(), IG.Script.Script_Misc.InitializeThis(), IG.Script.ScriptGraphics2dBase.InitializeThis(), IG.Script.ScriptExtExamples.InitializeThis(), IG.Script.ScriptGraphics3DBase.InitializeThis(), IG.Script.Scrip_OdeChem.InitializeThis(), and IG.Script.LoadableScriptSpecialFunctionBase.InitializeThis().
Script_DefaultRun()
virtual string IG.Lib.LoadableScriptBase.Script_DefaultRun (string[] arguments) inline virtual
Default run method for the script. Can be used when only installed commands are run by hte script.
Parameters
arguments Command arguments. The first argument must be name of the command that is run.
Returns
Return value of the script command that is run.
References IG.Lib.LoadableScriptBase.OutputLevel, IG.Lib.LoadableScriptBase.Script_PrintArguments(), IG.Lib.LoadableScriptBase.Script_PrintCommandsHelp(), and IG.Lib.LoadableScriptBase.Script_Run().
Referenced by IG.Script.ScriptExtFormats.RunThis(), IG.Script.ScriptNeuralExamples.RunThis(), IG.Script.ScriptExtTemplate.RunThis(), IG.Script.Script_Numeric.RunThis(), IG.Script.ScriptNeuralTemplate.RunThis(), IG.Script.ScriptExtExamplesExt.RunThis(), IG.Script.Script_Optimization.RunThis(), IG.Script.ScriptOptTemplate.RunThis(), IG.Script.ScriptOptTemplateExt.RunThis(), IG.Script.Script_Examples.RunThis(), IG.Script.Script_Misc.RunThis(), IG.Script.ScriptGraphics2dBase.RunThis(), IG.Script.ScriptExtExamples.RunThis(), IG.Script.ScriptExtNumeric.RunThis(), IG.Script.ScriptGraphics3DBase.RunThis(), IG.Script.Scrip_OdeChem.RunThis(), and IG.Script.LoadableScriptSpecialFunctionBase.RunThis().
Script_CreateInterpreterWithoutCommands()
virtual ICommandLineApplicationInterpreter IG.Lib.LoadableScriptBase.Script_CreateInterpreterWithoutCommands () inline virtual
Creates and returns an interpreter that can be used as script's internal interpreter for running script's commands.
Commands installed on this interpreter recieve the same command arguments as the Run command.
References IG.Lib.CommandLineApplicationScriptInterpreter.Script_CommandHelpStrings, IG.Lib.LoadableScriptBase.Script_CommandHelpStrings, and IG.Lib.CommandLineApplicationInterpreter.WarnCommandReplacement.
Referenced by IG.Lib.LoadableScriptBase.Script_CreateInterpreter().
Script_CreateInterpreter()
ICommandLineApplicationInterpreter IG.Lib.LoadableScriptBase.Script_CreateInterpreter () inline protected
Creates and returns an interpreter that can be used as script's internal interpreter for running script's commands.
Script's internal commands are added by the Script_AddCommands method before the created interpreter is returned.
In order to create another interpreter, override the Script_CreateInterpreterWithoutCommands method. In order to add another set of script internal commands, override the Script_AddCommands method.
Commands installed on this interpreter recieve the same command arguments as the Run command.
References IG.Lib.LoadableScriptBase.Script_AddCommands(), IG.Lib.LoadableScriptBase.Script_CommandHelpStrings, and IG.Lib.LoadableScriptBase.Script_CreateInterpreterWithoutCommands().
Script_AddCommands()
virtual void IG.Lib.LoadableScriptBase.Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings) inline virtual
Add wscript's internal commands to the specified interpreter.
Parameters
interpreter Interpreter to which commands are added.
helpStrings List where help strings for corresponding commands are stored (optional).
Reimplemented in IG.Script.LoadableScriptSpecialFunctionBase, IG.Script.S_12_01_Paper_NeuralOptCasting_00, IG.Script.S_12_02_paper_neural_process_chain_model, IG.Script.S_12_02_paper_neural_process_chain_model, IG.Script.S_13_5_Convection, IG.Script.LoadableScriptShellNeuralBase, IG.Script.LoadableScriptShellNeuralITOriginalBase, IG.Script.S_12_09_jmatpro, IG.Script.S_12_09_jmatpro, IG.Script.S_12_03_paper_gk, IG.Script.LoadableScriptShellNeuralIT, IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00, IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00, IG.Script.Script_Numeric, IG.Script.Script_Misc, IG.Script.ScriptGraphics3DBase, IG.Script.Script_Examples, IG.Script.ScriptExtNumeric, IG.Script.NeuralTestScript, IG.Script.NeuralTestScriptShellExt, IG.Script.ScriptGraphics2dBase, IG.Script.Scrip_OdeChem, IG.Script.ScriptExtExamples, IG.Script.LoadableScriptScalarFunctionCreator, IG.Script.ScriptExtExamples, IG.Script.ScriptNeuralTemplate, IG.Script.ScriptExtFormats, IG.Script.ScriptExtFormats, IG.Script.Script_Optimization, IG.Script.ScriptNeuralExamples, IG.Script.ScriptExtTemplate, IG.Script.ScriptExtTemplate, IG.Script.ScriptExtTemplate, IG.Script.ScriptOptTemplate, IG.Script.ScriptOptTemplateExt, IG.Script.ScriptExtExamplesExt, and IG.Script.ScriptExtGraphics3d.
References IG.Lib.LoadableScriptBase.ConstDefaultHelp, IG.Lib.LoadableScriptBase.ConstDefaultTestScrip, IG.Lib.LoadableScriptBase.ConstHelpDefaultUniversal, IG.Lib.LoadableScriptBase.Script_AddCommand(), IG.Lib.LoadableScriptBase.Script_CommandHelp(), and IG.Lib.LoadableScriptBase.Script_CommandTestScript().
Referenced by IG.Lib.LoadableScriptBase.Script_CreateInterpreter().
Script_CommandHelp()
virtual string IG.Lib.LoadableScriptBase.Script_CommandHelp (string[] arguments) inline protected virtual
Prints help.
Parameters
arguments Arguments.
Returns
null.
Reimplemented in IG.Script.S_12_02_paper_neural_process_chain_model, IG.Script.S_12_02_paper_neural_process_chain_model, IG.Script.S_12_03_paper_gk, IG.Script.S_TestNeural1, IG.Script.S_TestExt3, IG.Script.S_TestNeural3, IG.Script.S_TestExt3, IG.Script.S_TestOpt3, IG.Script.S_TestExt1, IG.Script.S_TestShellExt1, IG.Script.S_TestOpt1, IG.Script.S_TestExt2, IG.Script.S_TestNeural2, IG.Script.S_TestExt2, and IG.Script.S_TestOpt2.
References IG.Lib.LoadableScriptBase.Script_GetHelpString(), and IG.Lib.LoadableScriptBase.Script_PrintCommandsHelp().
Referenced by IG.Script.NeuralTestScript.RunThis(), IG.Script.NeuralTestScriptShellExt.RunThis(), IG.Script.LoadableScriptShellNeural.RunThis(), IG.Script.LoadableScriptExample.RunThis(), IG.Script.S_12_09_jmatpro.RunThis(), IG.Script.S_13_5_Convection.RunThis(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.RunThis(), IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00.RunThis(), and IG.Lib.LoadableScriptBase.Script_AddCommands().
Script_CommandTestScript()
virtual string IG.Lib.LoadableScriptBase.Script_CommandTestScript (string[] arguments) inline protected virtual
Prints help.
Parameters
arguments Arguments.
Returns
null.
Reimplemented in IG.Script.S_12_01_Paper_NeuralOptCasting_00, IG.Script.S_12_02_paper_neural_process_chain_model, IG.Script.S_12_02_paper_neural_process_chain_model, IG.Script.S_12_09_jmatpro, IG.Script.S_12_09_jmatpro, IG.Script.S_12_03_paper_gk, IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00, IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00, IG.Script.S_TestNeural1, IG.Script.S_TestExt3, IG.Script.S_TestNeural3, IG.Script.S_TestExt3, IG.Script.S_TestOpt3, IG.Script.S_TestExt1, IG.Script.S_TestShellExt1, IG.Script.S_TestOpt1, IG.Script.S_TestExt2, IG.Script.S_TestNeural2, IG.Script.S_TestExt2, and IG.Script.S_TestOpt2.
References IG.Lib.LoadableScriptBase.Script_PrintArguments(), and IG.Lib.LoadableScriptBase.Script_PrintCommandsHelp().
Referenced by IG.Lib.LoadableScriptBase.Script_AddCommands(), IG.Script.Script_Optimization.TestScriptArguments(), IG.Script.ScriptExtNumeric.TestScriptArguments(), and IG.Script.Script_Numeric.TestScriptArguments().
Script_CommandDelegate()
delegate string IG.Lib.LoadableScriptBase.Script_CommandDelegate (string[] args)
Delegate for commands that are installed on script's internal interpreter (property Script_Interpreter).
These methods only take command arguments as parameters, and the first argument is usually name under which command is installed.
Parameters
args Command arguments. The first argument is internal script's command name.
Returns
Command's return value.
Script_AddCommand() [1/2]
void IG.Lib.LoadableScriptBase.Script_AddCommand (string commandName, Script_CommandDelegate command, string helpString) inline
Adds a new internal script command under specified name to the internal interpreter of the current script object.
Parameters
commandName Name of the command.
Must not be null or empty string.
Parameters
command Method that executes the command.
Must not be null.
Parameters
helpString Help string associated with command, optionsl (can be null).
References IG.Lib.LoadableScriptBase._script_interpreter, IG.Lib.LoadableScriptBase.Script_CommandHelpStrings, and IG.Lib.LoadableScriptBase.Script_Interpreter.
Referenced by IG.Script.ScriptExtGraphics3d.Script_AddCommands(), IG.Script.ScriptOptTemplateExt.Script_AddCommands(), IG.Script.ScriptOptTemplate.Script_AddCommands(), IG.Script.ScriptExtTemplate.Script_AddCommands(), IG.Script.ScriptNeuralExamples.Script_AddCommands(), IG.Script.Script_Optimization.Script_AddCommands(), IG.Script.ScriptExtFormats.Script_AddCommands(), IG.Script.ScriptNeuralTemplate.Script_AddCommands(), IG.Script.ScriptExtExamples.Script_AddCommands(), IG.Script.Scrip_OdeChem.Script_AddCommands(), IG.Script.ScriptGraphics2dBase.Script_AddCommands(), IG.Script.ScriptExtNumeric.Script_AddCommands(), IG.Script.Script_Examples.Script_AddCommands(), IG.Script.ScriptGraphics3DBase.Script_AddCommands(), IG.Script.Script_Misc.Script_AddCommands(), IG.Script.Script_Numeric.Script_AddCommands(), IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00.Script_AddCommands(), IG.Script.LoadableScriptShellNeuralIT.Script_AddCommands(), IG.Script.S_12_03_paper_gk.Script_AddCommands(), IG.Script.S_12_09_jmatpro.Script_AddCommands(), IG.Script.LoadableScriptShellNeuralITOriginalBase.Script_AddCommands(), IG.Script.LoadableScriptShellNeuralBase.Script_AddCommands(), IG.Lib.LoadableScriptBase.Script_AddCommands(), IG.Script.S_13_5_Convection.Script_AddCommands(), IG.Script.S_12_02_paper_neural_process_chain_model.Script_AddCommands(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
Script_AddCommand() [2/2]
virtual void IG.Lib.LoadableScriptBase.Script_AddCommand (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings, string commandName, Script_CommandDelegate command, string helpString) inline virtual
Adds a new internal script command under specified name to the internal interpreter of the current script object.
Parameters
interpreter Interpreter on which the command is added.
helpStrings Dictionary containing help strings corresponding to interpreter commands.
commandName Name of the command.
Must not be null or empty string.
Parameters
command Method that executes the command.
Must not be null.
Parameters
helpString Help string associated with command, optionsl (can be null).
Reimplemented in IG.Script.LoadableScriptSpecialFunctionBase, and IG.Script.LoadableScriptScalarFunctionCreator.
References IG.Lib.ICommandLineApplicationInterpreter.AddCommand(), IG.Lib.ICommandLineApplicationInterpreter.ContainsCommand(), IG.Lib.LoadableScriptBase.Script_CommandAdapter.InterpreterCommand(), IG.Lib.LoadableScriptBase.OutputLevel, and IG.Lib.ICommandLineApplicationInterpreter.RemoveCommand().
Script_GetHelpString()
string IG.Lib.LoadableScriptBase.Script_GetHelpString (string scriptCommandName) inline
Returns help string for internal script command with specified name, or null if help string is not installed for such a command.
Parameters
scriptCommandName Name of the csript command.
References IG.Lib.LoadableScriptBase.Script_CommandHelpStrings.
Referenced by IG.Lib.LoadableScriptBase.Script_CommandAdapter.InterpreterCommand(), and IG.Lib.LoadableScriptBase.Script_CommandHelp().
Script_PrintCommandsHelp()
void IG.Lib.LoadableScriptBase.Script_PrintCommandsHelp () inline
Prits help for the installed internal commands of the script.
References IG.Lib.LoadableScriptBase.Script_CommandHelpStrings.
Referenced by IG.Lib.LoadableScriptBase.Script_CommandHelp(), IG.Lib.LoadableScriptBase.Script_CommandTestScript(), and IG.Lib.LoadableScriptBase.Script_DefaultRun().
Script_ContainsCommand()
virtual bool IG.Lib.LoadableScriptBase.Script_ContainsCommand (string commandName) inline virtual
Returns true if the internal script's interpreter contains a command with specified name, false otherwise.
Parameters
commandName Name of the command whose existence is queried.
References IG.Lib.ICommandLineApplicationInterpreter.ContainsCommand(), and IG.Lib.LoadableScriptBase.Script_Interpreter.
Referenced by IG.Script.NeuralTestScript.RunThis(), IG.Script.NeuralTestScriptShellExt.RunThis(), IG.Script.LoadableScriptShellNeural.RunThis(), IG.Script.S_12_02_paper_neural_process_chain_model.RunThis(), IG.Script.LoadableScriptExample.RunThis(), IG.Script.S_12_09_jmatpro.RunThis(), IG.Script.S_13_5_Convection.RunThis(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.RunThis(), IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00.RunThis(), IG.Script.S_12_03_paper_gk.RunThis(), and IG.Lib.LoadableScriptBase.Script_Run().
Script_ContainsScriptCommand()
virtual bool IG.Lib.LoadableScriptBase.Script_ContainsScriptCommand (string commandName) inline virtual
Returns true if the specified command is script command (i.e. its first argument is command-name and it is run through the Script_CommandAdapter object).
Parameters
commandName Name of the command that is queried.
References IG.Lib.LoadableScriptBase._script_CommandHelpStrings.
Referenced by IG.Lib.LoadableScriptBase.Script_Run().
Script_RemoveCommand()
virtual void IG.Lib.LoadableScriptBase.Script_RemoveCommand (string commandName) inline virtual
Removes the specified internal script command from the internal interpreter of the current scripting object.
Parameters
commandName Name of the command.
Must not be null or empty string.
References IG.Lib.LoadableScriptBase.OutputLevel, IG.Lib.ICommandLineApplicationInterpreter.RemoveCommand(), IG.Lib.LoadableScriptBase.Script_CommandHelpStrings, and IG.Lib.LoadableScriptBase.Script_Interpreter.
Script_RemoveAllCommands()
virtual void IG.Lib.LoadableScriptBase.Script_RemoveAllCommands () inline virtual
Removes ALL internal script commands from the internal interpreter of the current scripting object.
References IG.Lib.LoadableScriptBase.OutputLevel, IG.Lib.ICommandLineApplicationInterpreter.RemoveAllCommands(), and IG.Lib.LoadableScriptBase.Script_Interpreter.
Script_Run() [1/2]
string IG.Lib.LoadableScriptBase.Script_Run (string[] arguments) inline
Runs internal script command.
Parameters
arguments Arguments of the command. The first argument must be command name.
Returns
The return valu of executed command.
Exceptions
ArgumentException When argumens or command are not specified or command is not known.
References IG.Lib.ICommandLineApplicationInterpreter.MainThread, IG.Lib.ICommandLineApplicationInterpreter.RunWithoutModifications(), IG.Lib.LoadableScriptBase.Script_ContainsCommand(), IG.Lib.LoadableScriptBase.Script_ContainsScriptCommand(), and IG.Lib.LoadableScriptBase.Script_Interpreter.
Referenced by IG.Script.NeuralTestScript.RunThis(), IG.Script.NeuralTestScriptShellExt.RunThis(), IG.Script.S_TestOpt3.RunThis(), IG.Script.LoadableScriptShellNeural.RunThis(), IG.Script.S_12_02_paper_neural_process_chain_model.RunThis(), IG.Script.S_TestExt3.RunThis(), IG.Script.S_TestNeural3.RunThis(), IG.Script.LoadableScriptExample.RunThis(), IG.Script.S_12_09_jmatpro.RunThis(), IG.Script.S_13_5_Convection.RunThis(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.RunThis(), IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00.RunThis(), IG.Script.S_12_03_paper_gk.RunThis(), IG.Lib.LoadableScriptBase.Script_DefaultRun(), and IG.Lib.LoadableScriptBase.Script_Run().
Script_Run() [2/2]
string IG.Lib.LoadableScriptBase.Script_Run (string commandName, params string[] otherArguments) inline
Runs internal script command.
Parameters
commandName Name of the command
otherArguments The remainind command arguments (without a name).
Name is prepended to arguments before the script is run.
Exceptions
ArgumentException When argumens or command are not specified or command is not known.
References IG.Lib.LoadableScriptBase.Script_Run().
Script_PrintArguments()
virtual void IG.Lib.LoadableScriptBase.Script_PrintArguments (string messageString, string[] arguments) inline virtual
Prints the specified array of string arguments (usually passed as command-line arguments).
Parameters
arguments Arguments to be printed.
messageString Message to be printed first (optional, can be null).
Referenced by IG.Script.LoadableScriptScalarFunctionCreator.AppCustomApp(), IG.Script.LoadableScriptSpecialFunctionBase.AppCustomApp(), IG.Script.LoadableScriptScalarFunctionCreator.AppMyTest(), IG.Script.LoadableScriptSpecialFunctionBase.AppMyTest(), IG.Script.Scrip_OdeChem.ChemicalReactions(), IG.Script.LoadableScriptShellNeuralITOriginalBase.CollectParallelSimulationResults(), IG.Script.LoadableScriptShellNeuralBase.CollectParallelSimulationResults(), IG.Script.S_12_09_jmatpro.CommandCustom(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.CustomTests(), IG.Script.Script_Examples.FunctionLoader(), IG.Script.ScriptNeuralExamples.Graphics3d(), IG.Script.Script_Examples.Graphics3d(), IG.Script.ScriptExtExamples.Graphics3d(), IG.Script.S_TestOpt1.InitializeThis(), IG.Script.S_TestOpt2.InitializeThis(), IG.Script.S_TestExt1.InitializeThis(), IG.Script.S_TestOpt3.InitializeThis(), IG.Script.S_TestExt2.InitializeThis(), IG.Script.S_TestNeural1.InitializeThis(), IG.Script.S_TestNeural2.InitializeThis(), IG.Script.S_TestShellExt1.InitializeThis(), IG.Script.S_13_5_Convection.InitializeThis(), IG.Script.S_13_7_ConvectionRev1.InitializeThis(), IG.Script.S_TestExt3.InitializeThis(), IG.Script.S_TestNeural3.InitializeThis(), IG.Script.S_12_03_paper_gk.InitializeThis(), IG.Script.S_12_02_paper_neural_process_chain_model.InitializeThis(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.InitializeThis(), IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00.InitializeThis(), IG.Script.Script_11_10_clanek_neural_01.InitializeThis(), IG.Script.S_11_10_clanek_neural_00.InitializeThis(), IG.Script.S_12_09_jmatpro.InitializeThis(), IG.Script.ScriptExtExamples.NamedPipeClient(), IG.Script.ScriptExtExamples.NamedPipes(), IG.Script.ScriptExtExamples.NamedPipeServer(), IG.Script.Scrip_OdeChem.OrdinaryDifferentialEquations(), IG.Script.Scrip_OdeChem.Oscillation(), IG.Script.LoadableScriptShellNeuralIT.PlotConvergence(), IG.Script.ScriptNeuralExamples.PointClouds(), IG.Script.ScriptExtExamples.PointClouds(), IG.Script.Script_Examples.PointClouds(), IG.Script.LoadableScriptShellNeuralITOriginalBase.PrintInternalCommandAndArguments(), IG.Script.S_12_02_paper_neural_process_chain_model.PrintInternalCommandAndArguments(), IG.Script.LoadableScriptShellNeuralBase.PrintInternalCommandAndArguments(), IG.Script.S_13_5_Convection.RunConvectionSimulator(), IG.Script.S_13_5_Convection.RunConvectionSimulatorLog(), IG.Script.LoadableScriptShellNeuralITOriginalBase.RunParallelSimulations(), IG.Script.LoadableScriptShellNeuralBase.RunParallelSimulations(), IG.Script.NeuralTestScriptShellExt.RunThis(), IG.Script.NeuralTestScript.RunThis(), IG.Script.S_TestExt2.RunThis(), IG.Script.S_TestOpt2.RunThis(), IG.Script.S_TestNeural2.RunThis(), IG.Script.S_TestOpt1.RunThis(), IG.Script.S_TestExt1.RunThis(), IG.Script.S_TestNeural1.RunThis(), IG.Script.S_TestShellExt1.RunThis(), IG.Script.S_TestOpt3.RunThis(), IG.Script.LoadableScriptShellNeural.RunThis(), IG.Script.S_12_02_paper_neural_process_chain_model.RunThis(), IG.Script.S_TestExt3.RunThis(), IG.Script.S_TestNeural3.RunThis(), IG.Script.LoadableScriptExample.RunThis(), IG.Script.Script_11_10_clanek_neural_01.RunThis(), IG.Script.S_12_09_jmatpro.RunThis(), IG.Script.S_13_5_Convection.RunThis(), IG.Script.S_11_10_clanek_neural_00.RunThis(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.RunThis(), IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00.RunThis(), IG.Script.S_12_03_paper_gk.RunThis(), IG.Lib.LoadableScriptBase.Script_CommandTestScript(), IG.Lib.LoadableScriptBase.Script_DefaultInitialize(), IG.Lib.LoadableScriptBase.Script_DefaultRun(), IG.Script.LoadableScriptShellNeuralITOriginalBase.StochasticCreateInput(), IG.Script.LoadableScriptShellNeuralITOriginalBase.StochasticInfluence(), IG.Script.Script_Misc.TestConsoleUtilities(), IG.Script.ScriptGraphics2dBase.TestCustom(), IG.Script.ScriptGraphics3DBase.TestCustom(), IG.Script.ScriptExtFormats.TestCustom(), IG.Script.ScriptExtGraphics3d.TestCustom3d(), IG.Script.Script_Misc.TestExoticAndObsolete(), IG.Script.Script_Misc.TestExpressionEvaluatorJavaScript(), IG.Script.Script_Misc.TestFileOperations(), IG.Script.ScriptGraphics2dBase.TestGraph(), IG.Script.Script_Misc.TestListsOperations(), IG.Script.ScriptExtFormats.TestMyTest(), IG.Script.ScriptGraphics2dBase.TestMyTest(), IG.Script.ScriptGraphics3DBase.TestMyTest(), IG.Script.ScriptGraphics3DBase.TestPlot3d(), IG.Script.Script_Misc.TestRegisterable_IdGenerator(), IG.Script.Script_Misc.TestSerializationJson(), IG.Script.Script_Misc.TestStringParser(), IG.Script.ScriptGraphics3DBase.TestSurface3d(), IG.Script.ScriptGraphics3DBase.TestVtkTest(), IG.Script.S_12_02_paper_neural_process_chain_model.TrainNetwork(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainNetwork(), IG.Script.LoadableScriptShellNeuralIT.TrainNetwork(), and IG.Script.LoadableScriptShellNeuralIT.TrainParallelExample().
Member Data Documentation
_embeddedCommandName
string IG.Lib.LoadableScriptBase._embeddedCommandName = null protected
_mainLock
object IG.Lib.LoadableScriptBase._mainLock = new object() private
_initializationArguments
string [] IG.Lib.LoadableScriptBase._initializationArguments private
_isInitialized
bool IG.Lib.LoadableScriptBase._isInitialized = false private
_defaultOutputLevel
int IG.Lib.LoadableScriptBase._defaultOutputLevel = -1 static private
_outputLevel
int IG.Lib.LoadableScriptBase._outputLevel = DefaultOutputLevel protected
ConstDefaultHelp
const string IG.Lib.LoadableScriptBase.ConstDefaultHelp = "Help" static
Default command name for help.
Referenced by IG.Script.S_TestOpt3.RunThis(), IG.Script.S_TestExt3.RunThis(), IG.Script.S_TestNeural3.RunThis(), IG.Lib.LoadableScriptBase.Script_AddCommands(), IG.Test.ProgramTestIgor.TestMain(), TestOpt.IGLibShellExtMainProgram.TestMain(), TestOpt.IGLibShellMainProgram.TestMain(), and IG.Test.ProgramTestIgorIT.TestMain().
ConstHelpDefaultUniversal
const string IG.Lib.LoadableScriptBase.ConstHelpDefaultUniversal = "?" static
Universal name of the help command.
Referenced by IG.Lib.LoadableScriptBase.Script_CommandAdapter.InterpreterCommand(), IG.Lib.LoadableScriptBase.Script_AddCommands(), IG.Test.ProgramTestIgor.TestMain(), TestOpt.IGLibShellExtMainProgram.TestMain(), TestOpt.IGLibShellMainProgram.TestMain(), and IG.Test.ProgramTestIgorIT.TestMain().
ConstDefaultTestScrip
const string IG.Lib.LoadableScriptBase.ConstDefaultTestScrip = "TestScript" static
Default command name for test method.
Referenced by IG.Lib.LoadableScriptBase.Script_AddCommands(), IG.Test.ProgramTestIgor.TestMain(), TestOpt.IGLibShellExtMainProgram.TestMain(), TestOpt.IGLibShellMainProgram.TestMain(), and IG.Test.ProgramTestIgorIT.TestMain().
_script_interpreter
ICommandLineApplicationInterpreter IG.Lib.LoadableScriptBase._script_interpreter protected
Referenced by IG.Lib.LoadableScriptBase.Script_AddCommand().
_script_CommandHelpStrings
SortedList<string, string> IG.Lib.LoadableScriptBase._script_CommandHelpStrings private
Referenced by IG.Lib.LoadableScriptBase.Script_ContainsScriptCommand().
Property Documentation
EmbeddedCommandName
string IG.Lib.LoadableScriptBase.EmbeddedCommandName get set
Command that was used to launch the current embedded application script.
Lock
object IG.Lib.LoadableScriptBase.Lock get
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Referenced by IG.Script.ScriptGraphics2dBase.AddGraphCommand(), IG.Script.ScriptGraphics3DBase.AddPlot3dCommand(), IG.Script.ScriptGraphics3DBase.AddSurfaceCommand(), IG.Script.ScriptGraphics3DBase.AddTestVtkCommand(), IG.Lib.LoadableScriptBase.Initialize(), IG.Script.ScriptGraphics3DBase.InitSurfaceCommands(), IG.Script.ScriptGraphics2dBase.InitTestGraph(), IG.Script.ScriptGraphics3DBase.InitTestPlot3d(), IG.Script.ScriptGraphics3DBase.InitTestVtk(), and IG.Lib.LoadableScriptBase.Run().
InitializationArguments
string [] IG.Lib.LoadableScriptBase.InitializationArguments get set
Arguments used by the initialization method. WARNING: arguments can only be set before initialization is performed. Initialization is performed either implicitly at the first call to the Run method or explicitly by calling the Initialize method.
Referenced by IG.Lib.LoadableScriptBase.Initialize(), and IG.Lib.LoadableScriptBase.Run().
IsInitialized
virtual bool IG.Lib.LoadableScriptBase.IsInitialized get protected set
Whether the object has been initialized or not.
Referenced by IG.Lib.LoadableScriptBase.Initialize(), and IG.Lib.LoadableScriptBase.Run().
DefaultOutputLevel
int IG.Lib.LoadableScriptBase.DefaultOutputLevel static get set
Referenced by IG.Test.ProgramTestIgor.TestMain(), TestOpt.IGLibShellExtMainProgram.TestMain(), TestOpt.IGLibShellMainProgram.TestMain(), IG.Test.ProgramTestIgorIT.TestMain(), IG.Lib.ShellApplication< CommandLineApplicationInterpreter >.TestMain(), and IG.Script.LoadableScriptShellNeuralIT.TrainParallel().
OutputLevel
int IG.Lib.LoadableScriptBase.OutputLevel get set
Level of output to console produced by some operations of the current object.
Referenced by IG.Script.LoadableScriptShellNeuralITOriginalBase.ParSimAsyncCallback(), IG.Script.LoadableScriptShellNeuralBase.ParSimAsyncCallback(), IG.Script.LoadableScriptShellNeuralITOriginalBase.ParSimGetOptimizationDirectoryPath(), IG.Script.LoadableScriptShellNeuralBase.ParSimGetOptimizationDirectoryPath(), IG.Script.LoadableScriptShellNeuralITOriginalBase.ParSimPreparelDirectory(), IG.Script.LoadableScriptShellNeuralBase.ParSimPreparelDirectory(), IG.Script.LoadableScriptShellNeuralITOriginalBase.ParSimRunJob(), IG.Script.LoadableScriptShellNeuralBase.ParSimRunJob(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.PrepareTransfNeuralSimulation(), IG.Lib.LoadableScriptBase.Script_AddCommand(), IG.Lib.LoadableScriptBase.Script_DefaultInitialize(), IG.Lib.LoadableScriptBase.Script_DefaultRun(), IG.Lib.LoadableScriptBase.Script_RemoveAllCommands(), and IG.Lib.LoadableScriptBase.Script_RemoveCommand().
Script_Interpreter
virtual ICommandLineApplicationInterpreter IG.Lib.LoadableScriptBase.Script_Interpreter get protected set
Script's internal interpreter that takes care for execution of installed internal commands.
This interpreter is created when first needed (lazy evaluation).
Although this property is market virtual, you will normally not need to override it. Instead, override the Script_CreateInterpreter method, whch should do all the initializations of the interpreter.
Referenced by IG.Script.S_TestOpt1.InitializeThis(), IG.Script.S_TestNeural1.InitializeThis(), IG.Script.S_TestShellExt1.InitializeThis(), IG.Script.S_TestExt1.InitializeThis(), IG.Lib.LoadableScriptBase.Script_AddCommand(), IG.Lib.LoadableScriptBase.Script_ContainsCommand(), IG.Lib.LoadableScriptBase.Script_RemoveAllCommands(), IG.Lib.LoadableScriptBase.Script_RemoveCommand(), and IG.Lib.LoadableScriptBase.Script_Run().
Script_CommandHelpStrings
SortedList<string, string> IG.Lib.LoadableScriptBase.Script_CommandHelpStrings get protected
Contains help strings associated with script commands installed on interpreter.
Referenced by IG.Lib.LoadableScriptBase.Script_AddCommand(), IG.Lib.LoadableScriptBase.Script_CreateInterpreter(), IG.Lib.LoadableScriptBase.Script_CreateInterpreterWithoutCommands(), IG.Lib.LoadableScriptBase.Script_GetHelpString(), IG.Lib.LoadableScriptBase.Script_PrintCommandsHelp(), and IG.Lib.LoadableScriptBase.Script_RemoveCommand().
The documentation for this class was generated from the following file:
iglib/igbase/interpreters/scriptloader/LoadableScriptBase.cs