Doc: IGLib EXTENDED: IG.Forms.ControlManipulator Class Reference
IG.Forms.ControlManipulator Class Reference
Performs various operations on the specified controls:
Public Member Functions
ControlManipulator ()
ControlManipulator (params Control[] controls)
Constructs control manipulators, initialized with the specified controls to be manipulated.
void RemoveAllControls ()
Removes all manipulated controls from the object.
void RemoveControl (Control control)
Removes the specified control from this object, if it contains it.
void AddControl (Control control)
void AddControls (params Control[] controls)
void SaveProperties ()
void RestoreProperties ()
void Blink (int numBlinks=2, double blinkIntervalSeconds=0.2, params Control[] controls)
void Blink (Color blinkBackground, int numBlinks=2, double blinkIntervalSeconds=0.2, params Control[] controls)
void StartBlinking ()
Starts blinking the control.
void StopBlinking ()
Interrups blinking process, if it is currently happening. It is ensured that controls' normal background will be reset before timer is actually shut off.
Protected Member Functions
void ApplyBlinkColor ()
void ApplyNormalColor ()
Static Protected Attributes
static Color DefaultBlinkColor = Color.Orange
Properties
Dictionary< Control, ControlPropertyStore > Controls [get]
Dictionary that contains controls, and for each control it contains a storage object that saves and restores control's state when necessary.
System.Windows.Forms.Timer BlinkTimer [get]
Timer used for blinking, has pre-installed event handler. Created as necessary (azy evaluation).
Color BlinkBackColor [get, set]
Background color used for blinking.
double BlinkIntervalSeconds [get, set]
Interval between color switches, in seconds.
int BlinkIntervalMs [get, set]
Interval between successive blinks, in milliseconds. Bound to BlinkIntervalSeconds, so these properties can be used interchangeably, dependent on which time unit you prefer to use.
int NumBlinks [get, set]
Number of blinks.
bool IssBlinkOn [get, set]
Indicates whether blinking is currently switched on.
int NumPerformedBlinks [get, set]
bool DoBlink [get, set]
Private Member Functions
void BlinkTimer_Tick (object sender, EventArgs e)
Timer event handler that performes blining of control in the specified color.
Private Attributes
Dictionary< Control, ControlPropertyStore > _controls = new Dictionary<Control, ControlPropertyStore>()
System.Windows.Forms.Timer _timer
Color _blinkBackColor = Color.Orange
double _blinkIntervalSeconds = 0.2
int _numBlinks = 2
bool _isBlinkOn = false
bool _doBlink1 = false
Detailed Description
Performs various operations on the specified controls:
- Blinks the control.
Constructor & Destructor Documentation
ControlManipulator() [1/2]
IG.Forms.ControlManipulator.ControlManipulator () inline
ControlManipulator() [2/2]
IG.Forms.ControlManipulator.ControlManipulator (params Control[] controls) inline
Constructs control manipulators, initialized with the specified controls to be manipulated.
Parameters
controls
References IG.Forms.ControlManipulator.AddControls().
Member Function Documentation
RemoveAllControls()
void IG.Forms.ControlManipulator.RemoveAllControls () inline
Removes all manipulated controls from the object.
References IG.Forms.ControlManipulator.Controls.
RemoveControl()
void IG.Forms.ControlManipulator.RemoveControl (Control control) inline
Removes the specified control from this object, if it contains it.
Parameters
control
References IG.Forms.ControlManipulator.Controls.
AddControl()
void IG.Forms.ControlManipulator.AddControl (Control control) inline
References IG.Forms.ControlManipulator.Controls.
Referenced by IG.Forms.ControlManipulator.AddControls(), and IG.Forms.InputOutputDataDefinitionControl.btnGenerateTestData_Click().
AddControls()
void IG.Forms.ControlManipulator.AddControls (params Control[] controls) inline
References IG.Forms.ControlManipulator.AddControl().
Referenced by IG.Forms.ControlManipulator.Blink(), and IG.Forms.ControlManipulator.ControlManipulator().
SaveProperties()
void IG.Forms.ControlManipulator.SaveProperties () inline
References IG.Forms.ControlManipulator.Controls, and IG.Forms.ControlPropertyStore.SaveProperties().
RestoreProperties()
void IG.Forms.ControlManipulator.RestoreProperties () inline
References IG.Forms.ControlManipulator.Controls, and IG.Forms.ControlPropertyStore.SaveProperties().
Blink() [1/2]
void IG.Forms.ControlManipulator.Blink (int numBlinks = 2, double blinkIntervalSeconds = 0.2, params Control[] controls) inline
References IG.Forms.ControlManipulator.DefaultBlinkColor.
Referenced by IG.Forms.UtilForms.BlinkForm(), and IG.Forms.InputOutputDataDefinitionControl.btnGenerateTestData_Click().
Blink() [2/2]
void IG.Forms.ControlManipulator.Blink (Color blinkBackground, int numBlinks = 2, double blinkIntervalSeconds = 0.2, params Control[] controls) inline
References IG.Forms.ControlManipulator.AddControls(), IG.Forms.ControlManipulator.BlinkBackColor, IG.Forms.ControlManipulator.BlinkIntervalSeconds, IG.Forms.ControlManipulator.Controls, IG.Forms.ControlManipulator.NumBlinks, and IG.Forms.ControlManipulator.StartBlinking().
StartBlinking()
void IG.Forms.ControlManipulator.StartBlinking () inline
Starts blinking the control.
References IG.Forms.ControlManipulator.ApplyBlinkColor(), IG.Forms.ControlManipulator.ApplyNormalColor(), IG.Forms.ControlManipulator.BlinkIntervalMs, IG.Forms.ControlManipulator.BlinkTimer, IG.Forms.ControlManipulator.DoBlink, and IG.Forms.ControlManipulator.NumPerformedBlinks.
Referenced by IG.Forms.ControlManipulator.Blink().
StopBlinking()
void IG.Forms.ControlManipulator.StopBlinking () inline
Interrups blinking process, if it is currently happening. It is ensured that controls' normal background will be reset before timer is actually shut off.
References IG.Forms.ControlManipulator.ApplyNormalColor(), IG.Forms.ControlManipulator.BlinkTimer, and IG.Forms.ControlManipulator.DoBlink.
ApplyBlinkColor()
void IG.Forms.ControlManipulator.ApplyBlinkColor () inline protected
References IG.Forms.ControlManipulator.BlinkBackColor, IG.Forms.ControlManipulator.Controls, and IG.Forms.ControlManipulator.IssBlinkOn.
Referenced by IG.Forms.ControlManipulator.BlinkTimer_Tick(), and IG.Forms.ControlManipulator.StartBlinking().
ApplyNormalColor()
void IG.Forms.ControlManipulator.ApplyNormalColor () inline protected
References IG.Forms.ControlPropertyStore.BackColor, IG.Forms.ControlPropertyStore.Control, IG.Forms.ControlManipulator.Controls, and IG.Forms.ControlManipulator.IssBlinkOn.
Referenced by IG.Forms.ControlManipulator.BlinkTimer_Tick(), IG.Forms.ControlManipulator.StartBlinking(), and IG.Forms.ControlManipulator.StopBlinking().
BlinkTimer_Tick()
void IG.Forms.ControlManipulator.BlinkTimer_Tick (object sender, EventArgs e) inline private
Timer event handler that performes blining of control in the specified color.
References IG.Forms.ControlManipulator._timer, IG.Forms.ControlManipulator.ApplyBlinkColor(), IG.Forms.ControlManipulator.ApplyNormalColor(), IG.Forms.ControlManipulator.DoBlink, IG.Forms.ControlManipulator.IssBlinkOn, IG.Forms.ControlManipulator.NumBlinks, and IG.Forms.ControlManipulator.NumPerformedBlinks.
Member Data Documentation
_controls
Dictionary<Control, ControlPropertyStore> IG.Forms.ControlManipulator._controls = new Dictionary<Control, ControlPropertyStore>() private
_timer
System.Windows.Forms.Timer IG.Forms.ControlManipulator._timer private
Referenced by IG.Forms.ControlManipulator.BlinkTimer_Tick().
DefaultBlinkColor
Color IG.Forms.ControlManipulator.DefaultBlinkColor = Color.Orange static protected
Referenced by IG.Forms.ControlManipulator.Blink().
_blinkBackColor
Color IG.Forms.ControlManipulator._blinkBackColor = Color.Orange private
_blinkIntervalSeconds
double IG.Forms.ControlManipulator._blinkIntervalSeconds = 0.2 private
_numBlinks
int IG.Forms.ControlManipulator._numBlinks = 2 private
_isBlinkOn
bool IG.Forms.ControlManipulator._isBlinkOn = false private
_doBlink1
bool IG.Forms.ControlManipulator._doBlink1 = false private
Property Documentation
Controls
Dictionary<Control, ControlPropertyStore> IG.Forms.ControlManipulator.Controls get protected
Dictionary that contains controls, and for each control it contains a storage object that saves and restores control's state when necessary.
Referenced by IG.Forms.ControlManipulator.AddControl(), IG.Forms.ControlManipulator.ApplyBlinkColor(), IG.Forms.ControlManipulator.ApplyNormalColor(), IG.Forms.ControlManipulator.Blink(), IG.Forms.ControlManipulator.RemoveAllControls(), IG.Forms.ControlManipulator.RemoveControl(), IG.Forms.ControlManipulator.RestoreProperties(), and IG.Forms.ControlManipulator.SaveProperties().
BlinkTimer
System.Windows.Forms.Timer IG.Forms.ControlManipulator.BlinkTimer get protected
Timer used for blinking, has pre-installed event handler. Created as necessary (azy evaluation).
Referenced by IG.Forms.ControlManipulator.StartBlinking(), and IG.Forms.ControlManipulator.StopBlinking().
BlinkBackColor
Color IG.Forms.ControlManipulator.BlinkBackColor get set
Background color used for blinking.
Referenced by IG.Forms.ControlManipulator.ApplyBlinkColor(), and IG.Forms.ControlManipulator.Blink().
BlinkIntervalSeconds
double IG.Forms.ControlManipulator.BlinkIntervalSeconds get set
Interval between color switches, in seconds.
This is actually the time of half of a blink (the time interval in which one of two colors is displayed.)
Referenced by IG.Forms.ControlManipulator.Blink().
BlinkIntervalMs
int IG.Forms.ControlManipulator.BlinkIntervalMs get set
Interval between successive blinks, in milliseconds. Bound to BlinkIntervalSeconds, so these properties can be used interchangeably, dependent on which time unit you prefer to use.
Referenced by IG.Forms.ControlManipulator.StartBlinking().
NumBlinks
int IG.Forms.ControlManipulator.NumBlinks get set
Number of blinks.
Referenced by IG.Forms.ControlManipulator.Blink(), and IG.Forms.ControlManipulator.BlinkTimer_Tick().
IssBlinkOn
bool IG.Forms.ControlManipulator.IssBlinkOn get set protected
Indicates whether blinking is currently switched on.
When true, the BlinkTimer tick handlers will alternately switch background colors of controls and cause blinking in this way.
Referenced by IG.Forms.ControlManipulator.ApplyBlinkColor(), IG.Forms.ControlManipulator.ApplyNormalColor(), and IG.Forms.ControlManipulator.BlinkTimer_Tick().
NumPerformedBlinks
int IG.Forms.ControlManipulator.NumPerformedBlinks get set protected
Referenced by IG.Forms.ControlManipulator.BlinkTimer_Tick(), and IG.Forms.ControlManipulator.StartBlinking().
DoBlink
bool IG.Forms.ControlManipulator.DoBlink get set protected
Referenced by IG.Forms.ControlManipulator.BlinkTimer_Tick(), IG.Forms.ControlManipulator.StartBlinking(), and IG.Forms.ControlManipulator.StopBlinking().
The documentation for this class was generated from the following file:
iglib/igforms/Basic/ControlManipulator.cs