Doc: IGLib EXTENDED: AForge.Math.Random.UniformOneGenerator Class Reference
AForge.Math.Random.UniformOneGenerator Class Reference
Uniform random numbers generator in the range of [0, 1).
Public Member Functions
UniformOneGenerator ()
Initializes a new instance of the UniformOneGenerator class.
UniformOneGenerator (int seed)
Initializes a new instance of the UniformOneGenerator class.
float Next ()
Generate next random number.
void SetSeed (int seed)
Set seed of the random numbers generator.
Properties
float Mean [get]
Mean value of the generator.
float Variance [get]
Variance value of the generator.
Properties inherited from AForge.Math.Random.IRandomNumberGenerator
float Mean [get]
Mean value of generator.
float Variance [get]
Variance value of generator.
Private Attributes
ThreadSafeRandom rand = null
Detailed Description
Uniform random numbers generator in the range of [0, 1).
The random number generator generates uniformly distributed numbers in the range of [0, 1) - greater or equal to 0.0 and less than 1.0.
<note>At this point the generator is based on the internal .NET generator, but may be rewritten to use faster generation algorithm.</note>
Sample usage:
// create instance of random generator
IRandomNumberGenerator generator = new UniformOneGenerator();
// generate random number
float randomNumber = generator.Next();
Constructor & Destructor Documentation
UniformOneGenerator() [1/2]
AForge.Math.Random.UniformOneGenerator.UniformOneGenerator () inline
Initializes a new instance of the UniformOneGenerator class.
Initializes random numbers generator with zero seed.
References AForge.Math.Random.UniformOneGenerator.rand.
UniformOneGenerator() [2/2]
AForge.Math.Random.UniformOneGenerator.UniformOneGenerator (int seed) inline
Initializes a new instance of the UniformOneGenerator class.
Parameters
seed Seed value to initialize random numbers generator.
References AForge.Math.Random.UniformOneGenerator.rand.
Member Function Documentation
Next()
float AForge.Math.Random.UniformOneGenerator.Next () inline
Generate next random number.
Returns
Returns next random number.
Implements AForge.Math.Random.IRandomNumberGenerator.
References AForge.ThreadSafeRandom.NextDouble(), and AForge.Math.Random.UniformOneGenerator.rand.
Referenced by AForge.Math.Random.StandardGenerator.Next(), AForge.Math.Random.ExponentialGenerator.Next(), and AForge.Math.Random.UniformGenerator.Next().
SetSeed()
void AForge.Math.Random.UniformOneGenerator.SetSeed (int seed) inline
Set seed of the random numbers generator.
Parameters
seed Seed value.
Resets random numbers generator initializing it with specified seed value.
Implements AForge.Math.Random.IRandomNumberGenerator.
References AForge.Math.Random.UniformOneGenerator.rand.
Member Data Documentation
rand
ThreadSafeRandom AForge.Math.Random.UniformOneGenerator.rand = null private
Referenced by AForge.Math.Random.UniformOneGenerator.Next(), AForge.Math.Random.UniformOneGenerator.SetSeed(), and AForge.Math.Random.UniformOneGenerator.UniformOneGenerator().
Property Documentation
Mean
float AForge.Math.Random.UniformOneGenerator.Mean get
Mean value of the generator.
Variance
float AForge.Math.Random.UniformOneGenerator.Variance get
Variance value of the generator.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Math/Random/UniformOneGenerator.cs