Doc: IGLib EXTENDED: NUnit.Framework.Interfaces.IXmlNodeBuilder Interface Reference
NUnit.Framework.Interfaces.IXmlNodeBuilder Interface Reference
An object implementing IXmlNodeBuilder is able to build an XML representation of itself and any children.
Public Member Functions
TNode ToXml (bool recursive)
Returns a TNode representing the current object.
TNode AddToXml (TNode parentNode, bool recursive)
Returns a TNode representing the current object after adding it as a child of the supplied parent node.
Detailed Description
An object implementing IXmlNodeBuilder is able to build an XML representation of itself and any children.
Member Function Documentation
ToXml()
TNode NUnit.Framework.Interfaces.IXmlNodeBuilder.ToXml (bool recursive)
Returns a TNode representing the current object.
Parameters
recursive If true, children are included where applicable
Returns
A TNode representing the result
Implemented in NUnit.Framework.Internal.Test, NUnit.Framework.Internal.TestFilter, NUnit.Framework.Internal.TestResult, and NUnit.Framework.Internal.PropertyBag.
Referenced by NUnit.Framework.Api.FrameworkController.ExploreTests(), NUnit.Framework.Api.FrameworkController.LoadTests(), NUnit.Framework.Api.FrameworkController.RunTests(), NUnit.Framework.Internal.TestProgressReporter.TestFinished(), NUnitLite.NUnit3XmlOutputWriter.WriteTestFile(), and NUnitLite.NUnit3XmlOutputWriter.WriteXmlResultOutput().
AddToXml()
TNode NUnit.Framework.Interfaces.IXmlNodeBuilder.AddToXml (TNode parentNode, bool recursive)
Returns a TNode representing the current object after adding it as a child of the supplied parent node.
Parameters
parentNode The parent node.
recursive If true, children are included, where applicable
Returns
Implemented in NUnit.Framework.Internal.Test, NUnit.Framework.Internal.TestFilter, NUnit.Framework.Internal.TestResult, NUnit.Framework.Internal.TestSuite, NUnit.Framework.Internal.TestFilter.EmptyFilter, NUnit.Framework.Internal.PropertyBag, NUnit.Framework.Internal.TestMethod, NUnit.Framework.Internal.Filters.NotFilter, NUnit.Framework.Internal.Filters.ValueMatchFilter, NUnit.Framework.Internal.Filters.PropertyFilter, NUnit.Framework.Internal.Filters.CompositeFilter, and NUnit.Framework.Attributes.TestDummy.
Referenced by NUnit.Framework.Internal.Filters.CompositeFilter.AddToXml(), and NUnit.Framework.Internal.Test.PopulateTestNode().
The documentation for this interface was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Interfaces/IXmlNodeBuilder.cs