Doc: IGLib EXTENDED: Test.DiscreteDistributionTest Class Reference
Test.DiscreteDistributionTest Class Reference
Public Member Functions
void DiscreteDistributionUnitarity ()
void DiscreteDistributionMean ()
void DiscreteDistributionVariance ()
void DiscreteDistributionSkewness ()
void DiscreteDistributionProbabilityAxioms ()
void DiscreteDistributionInverseCDF ()
void DiscreteContinuousAgreement ()
void OutsideDiscreteDistributionSupport ()
void PoissonBug ()
void DiscreteDistributionRandomValues ()
void DiscreteDistributionBase ()
Static Public Member Functions
static DiscreteDistribution[] GetDistributions ()
Properties
TestContext TestContext [get, set]
Gets or sets the test context which provides information about and functionality for the current test run. /summary>
Private Attributes
TestContext testContextInstance
DiscreteDistribution[] distributions
Member Function Documentation
GetDistributions()
static DiscreteDistribution [] Test.DiscreteDistributionTest.GetDistributions () inline static
Referenced by Test.UnivariateDistributionTest.Initialize().
DiscreteDistributionUnitarity()
void Test.DiscreteDistributionTest.DiscreteDistributionUnitarity () inline
References Test.DiscreteDistributionTest.distributions, and Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ExpectationValue().
DiscreteDistributionMean()
void Test.DiscreteDistributionTest.DiscreteDistributionMean () inline
References Test.DiscreteDistributionTest.distributions, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ExpectationValue(), and Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Mean.
DiscreteDistributionVariance()
void Test.DiscreteDistributionTest.DiscreteDistributionVariance () inline
References Test.DiscreteDistributionTest.distributions, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ExpectationValue(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Mean, and Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Variance.
DiscreteDistributionSkewness()
void Test.DiscreteDistributionTest.DiscreteDistributionSkewness () inline
References Test.DiscreteDistributionTest.distributions, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.MomentAboutMean(), and Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Skewness.
DiscreteDistributionProbabilityAxioms()
void Test.DiscreteDistributionTest.DiscreteDistributionProbabilityAxioms () inline
References Test.DiscreteDistributionTest.distributions, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.LeftInclusiveProbability(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ProbabilityMass(), and Meta.Numerics.Statistics.Distributions.DiscreteDistribution.RightExclusiveProbability().
DiscreteDistributionInverseCDF()
void Test.DiscreteDistributionTest.DiscreteDistributionInverseCDF () inline
References Test.DiscreteDistributionTest.distributions, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.InverseLeftProbability(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.LeftExclusiveProbability(), and Meta.Numerics.Statistics.Distributions.DiscreteDistribution.LeftInclusiveProbability().
DiscreteContinuousAgreement()
void Test.DiscreteDistributionTest.DiscreteContinuousAgreement () inline
References Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Maximum, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Mean, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Minimum, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Moment(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.MomentAboutMean(), Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Skewness, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.StandardDeviation, and Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Variance.
OutsideDiscreteDistributionSupport()
void Test.DiscreteDistributionTest.OutsideDiscreteDistributionSupport () inline
References Test.DiscreteDistributionTest.distributions, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.LeftInclusiveProbability(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Maximum, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Minimum, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ProbabilityMass(), and Meta.Numerics.Statistics.Distributions.DiscreteDistribution.RightExclusiveProbability().
PoissonBug()
void Test.DiscreteDistributionTest.PoissonBug () inline
References Meta.Numerics.Statistics.Distributions.PoissonDistribution.InverseLeftProbability().
DiscreteDistributionRandomValues()
void Test.DiscreteDistributionTest.DiscreteDistributionRandomValues () inline
References Test.DiscreteDistributionTest.distributions, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.GetRandomValue(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Maximum, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Mean, Meta.Numerics.Statistics.TestResult.RightProbability, and Meta.Numerics.Statistics.Distributions.UnivariateDistribution.StandardDeviation.
DiscreteDistributionBase()
void Test.DiscreteDistributionTest.DiscreteDistributionBase () inline
References Meta.Numerics.Statistics.Distributions.DiscreteDistribution.InverseLeftProbability(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.LeftInclusiveProbability(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Mean, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Moment(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.MomentAboutMean(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ProbabilityMass(), and Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Variance.
Member Data Documentation
testContextInstance
TestContext Test.DiscreteDistributionTest.testContextInstance private
distributions
DiscreteDistribution [] Test.DiscreteDistributionTest.distributions private
Initial value:
= new DiscreteDistribution[] {
            new BernoulliDistribution(0.1),
            new BinomialDistribution(0.2, 30), new BinomialDistribution(0.4, 5),
            new PoissonDistribution(4.5), new PoissonDistribution(400.0),
            new DiscreteUniformDistribution(5, 11),
            new GeometricDistribution(0.6)
        }
Referenced by Test.DiscreteDistributionTest.DiscreteDistributionInverseCDF(), Test.DiscreteDistributionTest.DiscreteDistributionMean(), Test.DiscreteDistributionTest.DiscreteDistributionProbabilityAxioms(), Test.DiscreteDistributionTest.DiscreteDistributionRandomValues(), Test.DiscreteDistributionTest.DiscreteDistributionSkewness(), Test.DiscreteDistributionTest.DiscreteDistributionUnitarity(), Test.DiscreteDistributionTest.DiscreteDistributionVariance(), and Test.DiscreteDistributionTest.OutsideDiscreteDistributionSupport().
Property Documentation
TestContext
TestContext Test.DiscreteDistributionTest.TestContext get set
Gets or sets the test context which provides information about and functionality for the current test run. /summary>
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/DiscreteDistributionTest.cs