Doc: IGLib EXTENDED: IG.Forms.XmlTreeViewControl Class Reference
IG.Forms.XmlTreeViewControl Class Reference
Classes
class NodeData
Public Types
enum XMLSourceType : byte { XMLSourceType.TextFile, XMLSourceType.String, XMLSourceType.XMLNode }
Public Member Functions
XmlTreeViewControl ()
Static Public Member Functions
static void Example ()
Public Attributes
bool Editable = true
XMLSourceType SourceType = XMLSourceType.TextFile
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
XmlDocument Doc = null
XMLTestPathForm PathTester = null
System.Drawing.Color RootBackColor = Color.FromArgb(255, 180, 180)
string NoneImageKey = "xml_none"
Properties
string InitialTextRichTextBoxXml [get]
Text that is initially written
bool HasChanged [get, set]
bool DocumentLoaded [get, set]
bool ExpAttr [get, set]
bool AttrSubnode [get, set]
Private Types
enum VIEW { VIEW.TREE_VIEW = 0 }
Private Member Functions
void ReportError0 (string str)
void ReportError (string str)
void ReportError (Exception ex)
void Main0 ()
The main entry point for the application.
void XMLTreeView_Load (object sender, System.EventArgs e)
void FinalizeNotifications ()
void ResetNotifications ()
void LockNotifications ()
void UnlockNotifications ()
void NotifyStarted ()
void NotifyFinished ()
void openFileDialog1_FileOk (object sender, System.ComponentModel.CancelEventArgs e)
void LoadFileToListBox ()
void LoadFileToTextBox ()
void MoveToLine (int ln)
void LoadFileToDoc ()
void UpdateDocumentInTreeView ()
void ParseDocumentToTreeView ()
void ParseFileToTreeView ()
bool isAttributeContainter (TreeNode node)
string getTreeNodePath (TreeNode node)
string getTreeNodeTypeName (TreeNode node)
string getTreeNodeName (TreeNode node)
string getTreeNodeText (TreeNode node)
int getTreeNodeLineNumber (TreeNode node)
XmlNode FindXmlNode (TreeNode TNode)
void treeViewXML_Click (object sender, System.EventArgs e)
void ExpandNodes (TreeNode node, int numlevels, bool atleast, bool atmost)
void ExpandNodesExactly (TreeNode node, int numlevels)
void ExpandNodesAtLeast (TreeNode node, int numlevels)
void ExpandNodesAtMost (TreeNode node, int numlevels)
void ExpandNodes (TreeNode node, int numlevels, int level, bool atleast, bool atmost)
void EditNode (TreeNode node)
void CutNode (TreeNode node)
void CopyNode (TreeNode node)
void PasteNode (TreeNode node)
void DeleteNode (TreeNode node)
void treeViewXML_NodeMouseClick (object sender, TreeNodeMouseClickEventArgs e)
void treeViewXML_AfterSelect (object sender, System.Windows.Forms.TreeViewEventArgs e)
void menuItem2_Click (object sender, System.EventArgs e)
void WindowClose ()
void AssociateTag (TreeNode t, XmlReader reader)
void menuItem5_Click (object sender, System.EventArgs e)
void ShowAboutBox ()
void EnableDisableControls ()
void ThreadMessage (string message)
void TExpandAll ()
void ExpandAll ()
void TCollapseAll ()
void Clear ()
void menuItem1_DrawItem (object sender, System.Windows.Forms.DrawItemEventArgs e)
void menuItem1_MeasureItem (object sender, System.Windows.Forms.MeasureItemEventArgs e)
void menuItem3_MeasureItem (object sender, System.Windows.Forms.MeasureItemEventArgs e)
void menuItem3_DrawItem (object sender, System.Windows.Forms.DrawItemEventArgs e)
void ExpAllBtn_Click (object sender, EventArgs e)
void CollAllBtn_Click (object sender, EventArgs e)
void ExpandAllMenuItem_Click (object sender, EventArgs e)
void CollapseAllMenuItem_Click (object sender, EventArgs e)
void ExpMinBtn_Click (object sender, EventArgs e)
void ExpMaxBtn_Click (object sender, EventArgs e)
void ControlPanelSwitchMenuItem_Click (object sender, EventArgs e)
void TopPnlHideBtn_Click (object sender, EventArgs e)
void ShowControlPnl ()
void HideControlPnl ()
void ExpBtn_Click (object sender, EventArgs e)
void MenuFile_Open_Click (object sender, EventArgs e)
void MenuFile_Close_Click (object sender, EventArgs e)
void MenuFile_CloseDocument_Click (object sender, EventArgs e)
void MenuTools_Edit_Click (object sender, EventArgs e)
void MenuTools_Cut_Click (object sender, EventArgs e)
void MenuTools_Copy_Click (object sender, EventArgs e)
void MenuTools_Paste_Click (object sender, EventArgs e)
void PathTester_Close ()
void MenuTools_TestXPath_Click (object sender, EventArgs e)
void MenuTools_Controls_Click (object sender, EventArgs e)
void MenuTools_ExpandAll_Click (object sender, EventArgs e)
void MenuTools_CollapseAll_Click (object sender, EventArgs e)
void MenuTools_Stop_Click (object sender, EventArgs e)
void MenuHelp_About_Click (object sender, EventArgs e)
void ContextMenu_CopyFullPath_Click (object sender, EventArgs e)
void ContextMenu_CopyFullPathExactly_Click (object sender, EventArgs e)
void ContextMenu_CopyNodeText_Click (object sender, EventArgs e)
void ContextMenu_Edit_Click (object sender, EventArgs e)
void ContextMenu_Cut_Click (object sender, EventArgs e)
void ContextMenu_Copy_Click (object sender, EventArgs e)
void ContextMenu_Paste_Click (object sender, EventArgs e)
void ContextMenu_Delete_Click (object sender, EventArgs e)
void ContextMenu_ExpandAll_Click (object sender, EventArgs e)
void ContextMenu_ExpandSpecified_Click (object sender, EventArgs e)
void ContextMenu_Expand1_Click (object sender, EventArgs e)
void richTextBoxXML_TextChanged (object sender, EventArgs e)
void ContextMenu_Expand2_Click (object sender, EventArgs e)
void ContextMenu_Expand3_Click (object sender, EventArgs e)
void splitContainer2_Panel2_Paint (object sender, PaintEventArgs e)
void chkShowText_CheckedChanged (object sender, EventArgs e)
State of this check box specified whether the text representation of XML is visible or not (in this case, the appropriate panel collapses).
void chkShowList_CheckedChanged (object sender, EventArgs e)
State of this check box specified whether the list representation of XML is visible or not (in this case, the appropriate panel collapses).
void ContextMenu_Expand4_Click (object sender, EventArgs e)
void ContextMenu_Expand5_Click (object sender, EventArgs e)
void ContextMenu_ExpandAtLeastSpecified_Click (object sender, EventArgs e)
void ContextMenu_ExpandAtLeast1_Click (object sender, EventArgs e)
void ContextMenu_ExpandAtLeast2_Click (object sender, EventArgs e)
void ContextMenu_ExpandAtLeast3_Click (object sender, EventArgs e)
void ContextMenu_ExpandAtLeast4_Click (object sender, EventArgs e)
void ContextMenu_ExpandAtLeast5_Click (object sender, EventArgs e)
void ContextMenu_ExpandAtMostSpecified_Click (object sender, EventArgs e)
void ContextMenu_ExpandAtMost1_Click (object sender, EventArgs e)
void ContextMenu_ExpandAtMost2_Click (object sender, EventArgs e)
void ContextMenu_ExpandAtMost3_Click (object sender, EventArgs e)
void ContextMenu_ExpandAtMost4_Click (object sender, EventArgs e)
void ContextMenu_ExpandAtMost5_Click (object sender, EventArgs e)
void ContextMenu_Collapse_Click (object sender, EventArgs e)
void treeViewXML_NodeMouseHover (object sender, TreeNodeMouseHoverEventArgs e)
void XMLTreeView_Closing (object sender, FormClosingEventArgs e)
void StatusError_Click (object sender, EventArgs e)
void StatusStatus_Click (object sender, EventArgs e)
void MenuStrip_Enter (object sender, EventArgs e)
void NodeContextMenu_Opening (object sender, CancelEventArgs e)
void XmlTreeViewControl_DragDrop (object sender, DragEventArgs e)
void XmlTreeViewControl_DragEnter (object sender, DragEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
delegate void MyDelegate ()
Private Attributes
string _InitialTextRichTextBoxXML = "<< Drag & drop XML files above. >>"
Cursor CursorDefault = Cursors.Default
Color ActiveBackColor = Color.White
Color InActiveBackColor = Color.WhiteSmoke
bool ShowText = true
string TitleBase = "XMLViewer"
System.Drawing.Color RootForeColor = Color.Black
System.Drawing.Color ElementBackColor = Color.White
System.Drawing.Color ElementForeColor = Color.Red
System.Drawing.Color TextBackColor = Color.FromArgb(255, 255, 180)
System.Drawing.Color TextForeColor = Color.Black
System.Drawing.Color AttrNameBackColor = Color.White
System.Drawing.Color AttrNameForeColor = Color.Blue
System.Drawing.Color AttrValBackColor = Color.White
System.Drawing.Color AttrValForeColor = Color.Green
System.Drawing.Color CommentBackColor = Color.White
System.Drawing.Color CommentForeColor = Color.Gray
System.Drawing.Color AttrContBackColor = Color.White
System.Drawing.Color AttrContForeColor = Color.LightGray
string RootImageKey = "xml_root"
string ElementImageKey = "xml_element"
string TextImageKey = "xml_text"
string AttrNameImageKey = "xml_attribute_name"
string AttrValImageKey = "xml_attribute_value"
string CommentImageKey = "xml_comment"
bool haschanged = false
bool docloaded = false
bool expattr = true
bool attsubnode = true
string XMLInputFile = null
string FileSize = ""
string WorkingDir = Directory.GetCurrentDirectory()
int CurrentView = (int)VIEW.TREE_VIEW
Thread t = null
TreeNode RootNode = null
Point ClickedPoint = new Point(0, 0)
ArrayList TreeNodeArray = new ArrayList()
System.ComponentModel.ComponentResourceManager resources = null
int numLoadsToPerform = 0
int countLock = 0
System.ComponentModel.IContainer components = null
Required designer variable.
Bitmap img_fileopen
Bitmap img_exit
Bitmap img_collapse
Bitmap img_expand
Bitmap img_about
System.Windows.Forms.TreeView treeViewXML
System.Windows.Forms.ListBox listBoxXML
Panel DispPanel
Panel TopPnl
Panel BottomPnl
Button ExpAllBtn
Button CollAllBtn
Label LevelLbl
NumericUpDown LevelNumUpDown
Button ExpMinBtn
Button ExpBtn
Button ExpMaxBtn
Button TopPnlHideBtn
MenuStrip MenuStrip
ToolStripMenuItem ContextMenu_CopyFullPath
ToolStripMenuItem ContextMenu_CopyFullPathExactly
ToolStripMenuItem ContextMenu_CopyNodeText
ToolStripSeparator toolStripSeparator2
ToolStripMenuItem ContextMenu_EditMenu
ToolStripSeparator toolStripSeparator1
ToolStripMenuItem ContextMenu_Expand
ToolStripMenuItem ContextMenu_ExpandSpecified
ToolStripMenuItem ContextMenu_Expand1
ToolStripMenuItem ContextMenu_Expand2
ToolStripMenuItem ContextMenu_Expand3
ToolStripMenuItem ContextMenu_Expand4
ToolStripMenuItem ContextMenu_Expand5
ToolStripMenuItem ContextMenu_ExpandAtLeast
ToolStripMenuItem ContextMenu_ExpandAtLeastSpecified
ToolStripMenuItem ContextMenu_ExpandAtLeast1
ToolStripMenuItem ContextMenu_ExpandAtLeast2
ToolStripMenuItem ContextMenu_ExpandAtLeast3
ToolStripMenuItem ContextMenu_ExpandAtLeast4
ToolStripMenuItem ContextMenu_ExpandAtLeast5
ToolStripMenuItem ContextMenu_ExpandAtMost
ToolStripMenuItem ContextMenu_ExpandAtMostSpecified
ToolStripMenuItem ContextMenu_ExpandAtMost1
ToolStripMenuItem ContextMenu_ExpandAtMost2
ToolStripMenuItem ContextMenu_ExpandAtMost3
ToolStripMenuItem ContextMenu_ExpandAtMost4
ToolStripMenuItem ContextMenu_ExpandAtMost5
ToolStripMenuItem Collapse
ContextMenuStrip NodeContextMenu
ToolStripMenuItem MenuFile
ToolStripMenuItem MenuTools
ToolStripMenuItem MenuGelp
ToolStripMenuItem MenuFile_Open
ToolStripMenuItem MenuFile_Close
ToolStripMenuItem MenuTools_ExpandAll
ToolStripMenuItem MenuTools_CollapseAll
ToolStripMenuItem MenuTools_Stop
ToolStripMenuItem MenuHelp_About
ToolStripMenuItem MenuTools_Controls
Panel ControlPnl
ToolStripSeparator toolStripSeparator3
ToolStripSeparator toolStripSeparator4
StatusStrip statusStrip1
ToolStripStatusLabel StatusPath
ToolStripStatusLabel StatusType
ToolStripStatusLabel StatusError
SplitContainer splitContainer1
System.Windows.Forms.OpenFileDialog openFileDialog1
int NumErr = 0
int MaxErr = 3
ToolStripMenuItem editToolStripMenuItem
ToolStripMenuItem editElementToolStripMenuItem
ToolStripMenuItem cutToolStripMenuItem
ToolStripMenuItem copyToolStripMenuItem
ToolStripMenuItem pasteToolStripMenuItem
ImageList NodeImages
ToolStripMenuItem MenuTools_TestXPath
ToolStripSeparator toolStripSeparator5
ToolStripSeparator toolStripSeparator6
ToolTip toolTip1
ToolStripMenuItem deleteToolStripMenuItem
ToolStripMenuItem MenuFile_CloseDocument
ToolStripMenuItem ContextMenu_Edit
ToolStripMenuItem ContextMenu_Cut
ToolStripMenuItem ContextMenu_Copy
ToolStripMenuItem ContextMenu_Paste
ToolStripMenuItem ContextMenu_Delete
RichTextBox richTextBoxXML
ToolStripStatusLabel StatusStatus
ToolStripMenuItem ContextMenu_ExpandAll
SplitContainer splitContainer2
CheckBox chkShowList
CheckBox chkShowText
Member Enumeration Documentation
XMLSourceType
enum IG.Forms.XmlTreeViewControl.XMLSourceType : byte strong
Enumerator
TextFile
String
XMLNode
VIEW
enum IG.Forms.XmlTreeViewControl.VIEW strong private
Enumerator
TREE_VIEW
Constructor & Destructor Documentation
XmlTreeViewControl()
IG.Forms.XmlTreeViewControl.XmlTreeViewControl () inline
References IG.Forms.XmlTreeViewControl.InitializeComponent(), IG.Forms.XmlTreeViewControl.InitialTextRichTextBoxXml, and IG.Forms.XmlTreeViewControl.richTextBoxXML.
Member Function Documentation
ReportError0()
void IG.Forms.XmlTreeViewControl.ReportError0 (string str) inline private
References IG.Forms.FadingMessage.BackGroundColor, IG.Forms.FadingMessage.Launch(), IG.Forms.FadingMessage.MsgText, IG.Forms.FadingMessage.MsgTitle, and IG.Forms.FadingMessage.ShowTime.
Referenced by IG.Forms.XmlTreeViewControl.CopyNode(), IG.Forms.XmlTreeViewControl.CutNode(), IG.Forms.XmlTreeViewControl.DeleteNode(), IG.Forms.XmlTreeViewControl.EditNode(), IG.Forms.XmlTreeViewControl.PasteNode(), and IG.Forms.XmlTreeViewControl.ReportError().
ReportError() [1/2]
void IG.Forms.XmlTreeViewControl.ReportError (string str) inline private
References IG.Forms.XmlTreeViewControl.ReportError0(), and IG.Forms.XmlTreeViewControl.StatusError.
Referenced by IG.Forms.XmlTreeViewControl.CollAllBtn_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Collapse_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Copy_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Cut_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Delete_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Edit_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Expand1_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Expand2_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Expand3_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Expand4_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Expand5_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAll_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast1_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast2_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast3_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast4_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast5_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeastSpecified_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost1_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost2_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost3_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost4_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost5_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMostSpecified_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandSpecified_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Paste_Click(), IG.Forms.XmlTreeViewControl.ExpAllBtn_Click(), IG.Forms.XmlTreeViewControl.ExpBtn_Click(), IG.Forms.XmlTreeViewControl.ExpMaxBtn_Click(), IG.Forms.XmlTreeViewControl.ExpMinBtn_Click(), IG.Forms.XmlTreeViewControl.FinalizeNotifications(), IG.Forms.XmlTreeViewControl.FindXmlNode(), IG.Forms.XmlTreeViewControl.getTreeNodeName(), IG.Forms.XmlTreeViewControl.getTreeNodePath(), IG.Forms.XmlTreeViewControl.getTreeNodeTypeName(), IG.Forms.XmlTreeViewControl.LoadFileToDoc(), IG.Forms.XmlTreeViewControl.LoadFileToListBox(), IG.Forms.XmlTreeViewControl.LoadFileToTextBox(), IG.Forms.XmlTreeViewControl.MenuTools_Copy_Click(), IG.Forms.XmlTreeViewControl.MenuTools_Cut_Click(), IG.Forms.XmlTreeViewControl.MenuTools_Edit_Click(), IG.Forms.XmlTreeViewControl.MenuTools_Paste_Click(), IG.Forms.XmlTreeViewControl.MenuTools_TestXPath_Click(), IG.Forms.XmlTreeViewControl.MoveToLine(), IG.Forms.XmlTreeViewControl.openFileDialog1_FileOk(), IG.Forms.XmlTreeViewControl.ParseDocumentToTreeView(), IG.Forms.XmlTreeViewControl.ReportError(), IG.Forms.XmlTreeViewControl.treeViewXML_AfterSelect(), and IG.Forms.XmlTreeViewControl.UpdateDocumentInTreeView().
ReportError() [2/2]
void IG.Forms.XmlTreeViewControl.ReportError (Exception ex) inline private
References IG.Forms.XmlTreeViewControl.ReportError().
Main0()
void IG.Forms.XmlTreeViewControl.Main0 () inline private
The main entry point for the application.
XMLTreeView_Load()
void IG.Forms.XmlTreeViewControl.XMLTreeView_Load (object sender, System.EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.CursorDefault, IG.Forms.XmlTreeViewControl.img_about, IG.Forms.XmlTreeViewControl.img_collapse, IG.Forms.XmlTreeViewControl.img_exit, IG.Forms.XmlTreeViewControl.img_expand, IG.Forms.XmlTreeViewControl.img_fileopen, IG.Forms.XmlTreeViewControl.listBoxXML, IG.Forms.XmlTreeViewControl.resources, IG.Forms.XmlTreeViewControl.richTextBoxXML, IG.Forms.XmlTreeViewControl.ShowText, IG.Forms.XmlTreeViewControl.StatusError, and IG.Forms.XmlTreeViewControl.TitleBase.
FinalizeNotifications()
void IG.Forms.XmlTreeViewControl.FinalizeNotifications () inline private
References IG.Forms.XmlTreeViewControl.ActiveBackColor, IG.Forms.XmlTreeViewControl.CursorDefault, IG.Forms.XmlTreeViewControl.DocumentLoaded, IG.Forms.XmlTreeViewControl.LockNotifications(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.NotifyFinished(), and IG.Forms.XmlTreeViewControl.UnlockNotifications().
ResetNotifications()
void IG.Forms.XmlTreeViewControl.ResetNotifications () inline private
References IG.Forms.XmlTreeViewControl.countLock, IG.Forms.XmlTreeViewControl.DocumentLoaded, IG.Forms.XmlTreeViewControl.InActiveBackColor, IG.Forms.XmlTreeViewControl.listBoxXML, IG.Forms.XmlTreeViewControl.numLoadsToPerform, IG.Forms.XmlTreeViewControl.richTextBoxXML, and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.openFileDialog1_FileOk().
LockNotifications()
void IG.Forms.XmlTreeViewControl.LockNotifications () inline private
References IG.Forms.XmlTreeViewControl.countLock.
Referenced by IG.Forms.XmlTreeViewControl.FinalizeNotifications(), and IG.Forms.XmlTreeViewControl.openFileDialog1_FileOk().
UnlockNotifications()
void IG.Forms.XmlTreeViewControl.UnlockNotifications () inline private
References IG.Forms.XmlTreeViewControl.countLock, IG.Forms.XmlTreeViewControl.FinalizeNotifications(), and IG.Forms.XmlTreeViewControl.numLoadsToPerform.
Referenced by IG.Forms.XmlTreeViewControl.openFileDialog1_FileOk().
NotifyStarted()
void IG.Forms.XmlTreeViewControl.NotifyStarted () inline private
References IG.Forms.XmlTreeViewControl.numLoadsToPerform.
Referenced by IG.Forms.XmlTreeViewControl.LoadFileToDoc(), IG.Forms.XmlTreeViewControl.LoadFileToListBox(), IG.Forms.XmlTreeViewControl.LoadFileToTextBox(), IG.Forms.XmlTreeViewControl.ParseDocumentToTreeView(), IG.Forms.XmlTreeViewControl.ParseFileToTreeView(), and IG.Forms.XmlTreeViewControl.UpdateDocumentInTreeView().
NotifyFinished()
void IG.Forms.XmlTreeViewControl.NotifyFinished () inline private
References IG.Forms.XmlTreeViewControl.countLock, IG.Forms.XmlTreeViewControl.FinalizeNotifications(), and IG.Forms.XmlTreeViewControl.numLoadsToPerform.
Referenced by IG.Forms.XmlTreeViewControl.LoadFileToDoc(), IG.Forms.XmlTreeViewControl.LoadFileToListBox(), IG.Forms.XmlTreeViewControl.LoadFileToTextBox(), IG.Forms.XmlTreeViewControl.ParseDocumentToTreeView(), IG.Forms.XmlTreeViewControl.ParseFileToTreeView(), and IG.Forms.XmlTreeViewControl.UpdateDocumentInTreeView().
openFileDialog1_FileOk()
void IG.Forms.XmlTreeViewControl.openFileDialog1_FileOk (object sender, System.ComponentModel.CancelEventArgs e) inline private
References IG.Forms.XmlTreeViewControl.EnableDisableControls(), IG.Forms.XmlTreeViewControl.FileSize, IG.Forms.XmlTreeViewControl.listBoxXML, IG.Forms.XmlTreeViewControl.LoadFileToDoc(), IG.Forms.XmlTreeViewControl.LoadFileToListBox(), IG.Forms.XmlTreeViewControl.LoadFileToTextBox(), IG.Forms.XmlTreeViewControl.LockNotifications(), IG.Forms.XmlTreeViewControl.openFileDialog1, IG.Forms.XmlTreeViewControl.ParseFileToTreeView(), IG.Forms.XmlTreeViewControl.ReportError(), IG.Forms.XmlTreeViewControl.ResetNotifications(), IG.Forms.XmlTreeViewControl.TitleBase, IG.Forms.XmlTreeViewControl.TreeNodeArray, IG.Forms.XmlTreeViewControl.treeViewXML, IG.Forms.XmlTreeViewControl.UnlockNotifications(), and IG.Forms.XmlTreeViewControl.XMLInputFile.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent(), and IG.Forms.XmlTreeViewControl.XmlTreeViewControl_DragDrop().
LoadFileToListBox()
void IG.Forms.XmlTreeViewControl.LoadFileToListBox () inline private
References IG.Forms.XmlTreeViewControl.listBoxXML, IG.Forms.XmlTreeViewControl.NotifyFinished(), IG.Forms.XmlTreeViewControl.NotifyStarted(), IG.Forms.XmlTreeViewControl.ReportError(), IG.Forms.VoidDelegate(), and IG.Forms.XmlTreeViewControl.XMLInputFile.
Referenced by IG.Forms.XmlTreeViewControl.openFileDialog1_FileOk().
LoadFileToTextBox()
void IG.Forms.XmlTreeViewControl.LoadFileToTextBox () inline private
References IG.Forms.XmlTreeViewControl.NotifyFinished(), IG.Forms.XmlTreeViewControl.NotifyStarted(), IG.Forms.XmlTreeViewControl.ReportError(), IG.Forms.XmlTreeViewControl.richTextBoxXML, IG.Forms.VoidDelegate(), and IG.Forms.XmlTreeViewControl.XMLInputFile.
Referenced by IG.Forms.XmlTreeViewControl.openFileDialog1_FileOk().
MoveToLine()
void IG.Forms.XmlTreeViewControl.MoveToLine (int ln) inline private
References IG.Forms.XmlTreeViewControl.listBoxXML, IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.richTextBoxXML.
Referenced by IG.Forms.XmlTreeViewControl.treeViewXML_AfterSelect().
LoadFileToDoc()
void IG.Forms.XmlTreeViewControl.LoadFileToDoc () inline private
References IG.Forms.XmlTreeViewControl.Doc, IG.Forms.XmlTreeViewControl.NotifyFinished(), IG.Forms.XmlTreeViewControl.NotifyStarted(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.XMLInputFile.
Referenced by IG.Forms.XmlTreeViewControl.openFileDialog1_FileOk().
UpdateDocumentInTreeView()
void IG.Forms.XmlTreeViewControl.UpdateDocumentInTreeView () inline private
References IG.Forms.XmlTreeViewControl.NotifyFinished(), IG.Forms.XmlTreeViewControl.NotifyStarted(), and IG.Forms.XmlTreeViewControl.ReportError().
ParseDocumentToTreeView()
void IG.Forms.XmlTreeViewControl.ParseDocumentToTreeView () inline private
References IG.Forms.XmlTreeViewControl.NotifyFinished(), IG.Forms.XmlTreeViewControl.NotifyStarted(), and IG.Forms.XmlTreeViewControl.ReportError().
ParseFileToTreeView()
void IG.Forms.XmlTreeViewControl.ParseFileToTreeView () inline private
References IG.Forms.XmlTreeViewControl.AssociateTag(), IG.Forms.XmlTreeViewControl.AttrContBackColor, IG.Forms.XmlTreeViewControl.AttrContForeColor, IG.Forms.XmlTreeViewControl.AttrNameBackColor, IG.Forms.XmlTreeViewControl.AttrNameForeColor, IG.Forms.XmlTreeViewControl.AttrNameImageKey, IG.Forms.XmlTreeViewControl.AttrValBackColor, IG.Forms.XmlTreeViewControl.AttrValForeColor, IG.Forms.XmlTreeViewControl.AttrValImageKey, IG.Forms.XmlTreeViewControl.CommentBackColor, IG.Forms.XmlTreeViewControl.CommentForeColor, IG.Forms.XmlTreeViewControl.CommentImageKey, IG.Forms.XmlTreeViewControl.ElementBackColor, IG.Forms.XmlTreeViewControl.ElementForeColor, IG.Forms.XmlTreeViewControl.ElementImageKey, IG.Forms.XmlTreeViewControl.MaxErr, IG.Forms.XmlTreeViewControl.NotifyFinished(), IG.Forms.XmlTreeViewControl.NotifyStarted(), IG.Forms.XmlTreeViewControl.NumErr, IG.Forms.XmlTreeViewControl.RootBackColor, IG.Forms.XmlTreeViewControl.RootForeColor, IG.Forms.XmlTreeViewControl.RootImageKey, IG.Forms.XmlTreeViewControl.RootNode, IG.Forms.XmlTreeViewControl.SourceType, IG.Forms.XmlTreeViewControl.TextBackColor, IG.Forms.XmlTreeViewControl.TextForeColor, IG.Forms.XmlTreeViewControl.TextImageKey, IG.Forms.XmlTreeViewControl.treeViewXML, IG.Forms.VoidDelegate(), and IG.Forms.XmlTreeViewControl.XMLInputFile.
Referenced by IG.Forms.XmlTreeViewControl.openFileDialog1_FileOk().
isAttributeContainter()
bool IG.Forms.XmlTreeViewControl.isAttributeContainter (TreeNode node) inline private
References IG.Forms.XmlTreeViewControl.NodeData.NodeType.
Referenced by IG.Forms.XmlTreeViewControl.treeViewXML_NodeMouseHover().
getTreeNodePath()
string IG.Forms.XmlTreeViewControl.getTreeNodePath (TreeNode node) inline private
References IG.Forms.XmlTreeViewControl.NodeData.NodeType, and IG.Forms.XmlTreeViewControl.ReportError().
Referenced by IG.Forms.XmlTreeViewControl.ContextMenu_CopyFullPath_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_CopyFullPathExactly_Click(), IG.Forms.XmlTreeViewControl.MenuTools_TestXPath_Click(), IG.Forms.XmlTreeViewControl.treeViewXML_AfterSelect(), and IG.Forms.XmlTreeViewControl.treeViewXML_NodeMouseHover().
getTreeNodeTypeName()
string IG.Forms.XmlTreeViewControl.getTreeNodeTypeName (TreeNode node) inline private
References IG.Forms.XmlTreeViewControl.NodeData.NodeType, and IG.Forms.XmlTreeViewControl.ReportError().
Referenced by IG.Forms.XmlTreeViewControl.FindXmlNode(), and IG.Forms.XmlTreeViewControl.treeViewXML_AfterSelect().
getTreeNodeName()
string IG.Forms.XmlTreeViewControl.getTreeNodeName (TreeNode node) inline private
References IG.Forms.XmlTreeViewControl.NodeData.NodeName, and IG.Forms.XmlTreeViewControl.ReportError().
Referenced by IG.Forms.XmlTreeViewControl.FindXmlNode().
getTreeNodeText()
string IG.Forms.XmlTreeViewControl.getTreeNodeText (TreeNode node) inline private
getTreeNodeLineNumber()
int IG.Forms.XmlTreeViewControl.getTreeNodeLineNumber (TreeNode node) inline private
References IG.Forms.XmlTreeViewControl.NodeData.LineNumber.
FindXmlNode()
XmlNode IG.Forms.XmlTreeViewControl.FindXmlNode (TreeNode TNode) inline private
References IG.Forms.XmlTreeViewControl.Doc, IG.Forms.XmlTreeViewControl.getTreeNodeName(), IG.Forms.XmlTreeViewControl.getTreeNodeTypeName(), and IG.Forms.XmlTreeViewControl.ReportError().
treeViewXML_Click()
void IG.Forms.XmlTreeViewControl.treeViewXML_Click (object sender, System.EventArgs e) inline private
ExpandNodes() [1/2]
void IG.Forms.XmlTreeViewControl.ExpandNodes (TreeNode node, int numlevels, bool atleast, bool atmost) inline private
Referenced by IG.Forms.XmlTreeViewControl.ExpandNodes(), IG.Forms.XmlTreeViewControl.ExpandNodesAtLeast(), IG.Forms.XmlTreeViewControl.ExpandNodesAtMost(), and IG.Forms.XmlTreeViewControl.ExpandNodesExactly().
ExpandNodesExactly()
void IG.Forms.XmlTreeViewControl.ExpandNodesExactly (TreeNode node, int numlevels) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodes().
Referenced by IG.Forms.XmlTreeViewControl.ContextMenu_Expand1_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Expand2_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Expand3_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Expand4_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Expand5_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandSpecified_Click(), and IG.Forms.XmlTreeViewControl.ExpBtn_Click().
ExpandNodesAtLeast()
void IG.Forms.XmlTreeViewControl.ExpandNodesAtLeast (TreeNode node, int numlevels) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodes().
Referenced by IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast1_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast2_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast3_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast4_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast5_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeastSpecified_Click(), and IG.Forms.XmlTreeViewControl.ExpMinBtn_Click().
ExpandNodesAtMost()
void IG.Forms.XmlTreeViewControl.ExpandNodesAtMost (TreeNode node, int numlevels) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodes().
Referenced by IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost1_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost2_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost3_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost4_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost5_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMostSpecified_Click(), and IG.Forms.XmlTreeViewControl.ExpMaxBtn_Click().
ExpandNodes() [2/2]
void IG.Forms.XmlTreeViewControl.ExpandNodes (TreeNode node, int numlevels, int level, bool atleast, bool atmost) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodes().
EditNode()
void IG.Forms.XmlTreeViewControl.EditNode (TreeNode node) inline private
References IG.Forms.XmlTreeViewControl.DocumentLoaded, IG.Forms.XmlTreeViewControl.Editable, IG.Forms.XmlTreeViewControl.HasChanged, and IG.Forms.XmlTreeViewControl.ReportError0().
Referenced by IG.Forms.XmlTreeViewControl.ContextMenu_Copy_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Cut_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Delete_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Edit_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Paste_Click(), and IG.Forms.XmlTreeViewControl.MenuTools_Edit_Click().
CutNode()
void IG.Forms.XmlTreeViewControl.CutNode (TreeNode node) inline private
References IG.Forms.XmlTreeViewControl.DocumentLoaded, IG.Forms.XmlTreeViewControl.Editable, IG.Forms.XmlTreeViewControl.HasChanged, and IG.Forms.XmlTreeViewControl.ReportError0().
Referenced by IG.Forms.XmlTreeViewControl.MenuTools_Cut_Click().
CopyNode()
void IG.Forms.XmlTreeViewControl.CopyNode (TreeNode node) inline private
References IG.Forms.XmlTreeViewControl.DocumentLoaded, IG.Forms.XmlTreeViewControl.Editable, IG.Forms.XmlTreeViewControl.HasChanged, and IG.Forms.XmlTreeViewControl.ReportError0().
Referenced by IG.Forms.XmlTreeViewControl.MenuTools_Copy_Click().
PasteNode()
void IG.Forms.XmlTreeViewControl.PasteNode (TreeNode node) inline private
References IG.Forms.XmlTreeViewControl.DocumentLoaded, IG.Forms.XmlTreeViewControl.Editable, IG.Forms.XmlTreeViewControl.HasChanged, and IG.Forms.XmlTreeViewControl.ReportError0().
Referenced by IG.Forms.XmlTreeViewControl.MenuTools_Paste_Click().
DeleteNode()
void IG.Forms.XmlTreeViewControl.DeleteNode (TreeNode node) inline private
References IG.Forms.XmlTreeViewControl.DocumentLoaded, IG.Forms.XmlTreeViewControl.Editable, IG.Forms.XmlTreeViewControl.HasChanged, and IG.Forms.XmlTreeViewControl.ReportError0().
treeViewXML_NodeMouseClick()
void IG.Forms.XmlTreeViewControl.treeViewXML_NodeMouseClick (object sender, TreeNodeMouseClickEventArgs e) inline private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
treeViewXML_AfterSelect()
void IG.Forms.XmlTreeViewControl.treeViewXML_AfterSelect (object sender, System.Windows.Forms.TreeViewEventArgs e) inline private
References IG.Forms.XmlTreeViewControl.getTreeNodePath(), IG.Forms.XmlTreeViewControl.getTreeNodeTypeName(), IG.Forms.XmlTreeViewControl.MoveToLine(), IG.Forms.XmlTreeViewControl.PathTester, IG.Forms.XmlTreeViewControl.ReportError(), IG.Forms.XmlTreeViewControl.ShowText, IG.Forms.XmlTreeViewControl.StatusError, IG.Forms.XmlTreeViewControl.StatusPath, IG.Forms.XmlTreeViewControl.StatusStatus, and IG.Forms.XmlTreeViewControl.StatusType.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
menuItem2_Click()
void IG.Forms.XmlTreeViewControl.menuItem2_Click (object sender, System.EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.WindowClose().
WindowClose()
void IG.Forms.XmlTreeViewControl.WindowClose () inline private
References IG.Forms.XmlTreeViewControl.Dispose().
Referenced by IG.Forms.XmlTreeViewControl.MenuFile_Close_Click(), and IG.Forms.XmlTreeViewControl.menuItem2_Click().
AssociateTag()
void IG.Forms.XmlTreeViewControl.AssociateTag (TreeNode t, XmlReader reader) inline private
References IG.Forms.XmlTreeViewControl.NodeData.Depth, IG.Forms.XmlTreeViewControl.NodeData.IsEmptyElement, IG.Forms.XmlTreeViewControl.NodeData.LineNumber, IG.Forms.XmlTreeViewControl.NodeData.NodeName, IG.Forms.XmlTreeViewControl.NodeData.NodeType, IG.Forms.XmlTreeViewControl.NodeData.NodeValue, and IG.Forms.XmlTreeViewControl.t.
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
menuItem5_Click()
void IG.Forms.XmlTreeViewControl.menuItem5_Click (object sender, System.EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ShowAboutBox().
ShowAboutBox()
void IG.Forms.XmlTreeViewControl.ShowAboutBox () inline private
Referenced by IG.Forms.XmlTreeViewControl.MenuHelp_About_Click(), and IG.Forms.XmlTreeViewControl.menuItem5_Click().
EnableDisableControls()
void IG.Forms.XmlTreeViewControl.EnableDisableControls () inline private
References IG.Forms.XmlTreeViewControl.CurrentView, and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.openFileDialog1_FileOk().
ThreadMessage()
void IG.Forms.XmlTreeViewControl.ThreadMessage (string message) inline private
TExpandAll()
void IG.Forms.XmlTreeViewControl.TExpandAll () inline private
References IG.Forms.XmlTreeViewControl.ExpandAll(), and IG.Forms.XmlTreeViewControl.t.
Referenced by IG.Forms.XmlTreeViewControl.ExpAllBtn_Click(), IG.Forms.XmlTreeViewControl.ExpandAllMenuItem_Click(), and IG.Forms.XmlTreeViewControl.MenuTools_ExpandAll_Click().
ExpandAll()
void IG.Forms.XmlTreeViewControl.ExpandAll () inline private
References IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.TExpandAll().
TCollapseAll()
void IG.Forms.XmlTreeViewControl.TCollapseAll () inline private
References IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.CollAllBtn_Click(), IG.Forms.XmlTreeViewControl.CollapseAllMenuItem_Click(), and IG.Forms.XmlTreeViewControl.MenuTools_CollapseAll_Click().
Clear()
void IG.Forms.XmlTreeViewControl.Clear () inline private
References IG.Forms.XmlTreeViewControl.TreeNodeArray.
menuItem1_DrawItem()
void IG.Forms.XmlTreeViewControl.menuItem1_DrawItem (object sender, System.Windows.Forms.DrawItemEventArgs e) inline private
menuItem1_MeasureItem()
void IG.Forms.XmlTreeViewControl.menuItem1_MeasureItem (object sender, System.Windows.Forms.MeasureItemEventArgs e) inline private
menuItem3_MeasureItem()
void IG.Forms.XmlTreeViewControl.menuItem3_MeasureItem (object sender, System.Windows.Forms.MeasureItemEventArgs e) inline private
menuItem3_DrawItem()
void IG.Forms.XmlTreeViewControl.menuItem3_DrawItem (object sender, System.Windows.Forms.DrawItemEventArgs e) inline private
References IG.Forms.XmlTreeViewControl.CurrentView, IG.Forms.XmlTreeViewControl.img_about, IG.Forms.XmlTreeViewControl.img_collapse, IG.Forms.XmlTreeViewControl.img_exit, IG.Forms.XmlTreeViewControl.img_expand, and IG.Forms.XmlTreeViewControl.img_fileopen.
ExpAllBtn_Click()
void IG.Forms.XmlTreeViewControl.ExpAllBtn_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ReportError(), IG.Forms.XmlTreeViewControl.StatusError, IG.Forms.XmlTreeViewControl.StatusStatus, and IG.Forms.XmlTreeViewControl.TExpandAll().
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
CollAllBtn_Click()
void IG.Forms.XmlTreeViewControl.CollAllBtn_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ReportError(), IG.Forms.XmlTreeViewControl.StatusError, IG.Forms.XmlTreeViewControl.StatusStatus, and IG.Forms.XmlTreeViewControl.TCollapseAll().
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ExpandAllMenuItem_Click()
void IG.Forms.XmlTreeViewControl.ExpandAllMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.TExpandAll().
CollapseAllMenuItem_Click()
void IG.Forms.XmlTreeViewControl.CollapseAllMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.TCollapseAll().
ExpMinBtn_Click()
void IG.Forms.XmlTreeViewControl.ExpMinBtn_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesAtLeast(), IG.Forms.XmlTreeViewControl.LevelNumUpDown, IG.Forms.XmlTreeViewControl.ReportError(), IG.Forms.XmlTreeViewControl.StatusError, IG.Forms.XmlTreeViewControl.StatusStatus, and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ExpMaxBtn_Click()
void IG.Forms.XmlTreeViewControl.ExpMaxBtn_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesAtMost(), IG.Forms.XmlTreeViewControl.LevelNumUpDown, IG.Forms.XmlTreeViewControl.ReportError(), IG.Forms.XmlTreeViewControl.StatusError, IG.Forms.XmlTreeViewControl.StatusStatus, and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ControlPanelSwitchMenuItem_Click()
void IG.Forms.XmlTreeViewControl.ControlPanelSwitchMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.HideControlPnl(), and IG.Forms.XmlTreeViewControl.ShowControlPnl().
TopPnlHideBtn_Click()
void IG.Forms.XmlTreeViewControl.TopPnlHideBtn_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.HideControlPnl(), and IG.Forms.XmlTreeViewControl.MenuTools_Controls.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ShowControlPnl()
void IG.Forms.XmlTreeViewControl.ShowControlPnl () inline private
References IG.Forms.XmlTreeViewControl.ControlPnl.
Referenced by IG.Forms.XmlTreeViewControl.ControlPanelSwitchMenuItem_Click(), and IG.Forms.XmlTreeViewControl.MenuTools_Controls_Click().
HideControlPnl()
void IG.Forms.XmlTreeViewControl.HideControlPnl () inline private
References IG.Forms.XmlTreeViewControl.ControlPnl.
Referenced by IG.Forms.XmlTreeViewControl.ControlPanelSwitchMenuItem_Click(), IG.Forms.XmlTreeViewControl.MenuTools_Controls_Click(), and IG.Forms.XmlTreeViewControl.TopPnlHideBtn_Click().
ExpBtn_Click()
void IG.Forms.XmlTreeViewControl.ExpBtn_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesExactly(), IG.Forms.XmlTreeViewControl.LevelNumUpDown, IG.Forms.XmlTreeViewControl.ReportError(), IG.Forms.XmlTreeViewControl.StatusError, IG.Forms.XmlTreeViewControl.StatusStatus, and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
MenuFile_Open_Click()
void IG.Forms.XmlTreeViewControl.MenuFile_Open_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.openFileDialog1.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
MenuFile_Close_Click()
void IG.Forms.XmlTreeViewControl.MenuFile_Close_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.WindowClose().
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
MenuFile_CloseDocument_Click()
void IG.Forms.XmlTreeViewControl.MenuFile_CloseDocument_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.DocumentLoaded.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
MenuTools_Edit_Click()
void IG.Forms.XmlTreeViewControl.MenuTools_Edit_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.EditNode(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
MenuTools_Cut_Click()
void IG.Forms.XmlTreeViewControl.MenuTools_Cut_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.CutNode(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
MenuTools_Copy_Click()
void IG.Forms.XmlTreeViewControl.MenuTools_Copy_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.CopyNode(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
MenuTools_Paste_Click()
void IG.Forms.XmlTreeViewControl.MenuTools_Paste_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.PasteNode(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
PathTester_Close()
void IG.Forms.XmlTreeViewControl.PathTester_Close () inline private
References IG.Forms.XmlTreeViewControl.PathTester.
Referenced by IG.Forms.XmlTreeViewControl.MenuTools_TestXPath_Click().
MenuTools_TestXPath_Click()
void IG.Forms.XmlTreeViewControl.MenuTools_TestXPath_Click (object sender, EventArgs e) inline private
References IG.Forms.UtilForms.BlinkControl(), IG.Forms.XMLTestPathForm.CloseDelegate, IG.Forms.XmlTreeViewControl.Doc, IG.Forms.XmlTreeViewControl.getTreeNodePath(), IG.Forms.XMLTestPathForm.MyDelegate(), IG.Forms.XmlTreeViewControl.PathTester, IG.Forms.XmlTreeViewControl.PathTester_Close(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
MenuTools_Controls_Click()
void IG.Forms.XmlTreeViewControl.MenuTools_Controls_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.HideControlPnl(), and IG.Forms.XmlTreeViewControl.ShowControlPnl().
MenuTools_ExpandAll_Click()
void IG.Forms.XmlTreeViewControl.MenuTools_ExpandAll_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.TExpandAll().
MenuTools_CollapseAll_Click()
void IG.Forms.XmlTreeViewControl.MenuTools_CollapseAll_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.TCollapseAll().
MenuTools_Stop_Click()
void IG.Forms.XmlTreeViewControl.MenuTools_Stop_Click (object sender, EventArgs e) inline private
MenuHelp_About_Click()
void IG.Forms.XmlTreeViewControl.MenuHelp_About_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ShowAboutBox().
ContextMenu_CopyFullPath_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_CopyFullPath_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.getTreeNodePath(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_CopyFullPathExactly_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_CopyFullPathExactly_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.getTreeNodePath(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_CopyNodeText_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_CopyNodeText_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Edit_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_Edit_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.EditNode(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Cut_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_Cut_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.EditNode(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Copy_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_Copy_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.EditNode(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Paste_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_Paste_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.EditNode(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Delete_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_Delete_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.EditNode(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAll_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAll_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandSpecified_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_ExpandSpecified_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesExactly(), IG.Forms.XmlTreeViewControl.LevelNumUpDown, IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Expand1_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_Expand1_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesExactly(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
richTextBoxXML_TextChanged()
void IG.Forms.XmlTreeViewControl.richTextBoxXML_TextChanged (object sender, EventArgs e) inline private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Expand2_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_Expand2_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesExactly(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Expand3_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_Expand3_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesExactly(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
splitContainer2_Panel2_Paint()
void IG.Forms.XmlTreeViewControl.splitContainer2_Panel2_Paint (object sender, PaintEventArgs e) inline private
chkShowText_CheckedChanged()
void IG.Forms.XmlTreeViewControl.chkShowText_CheckedChanged (object sender, EventArgs e) inline private
State of this check box specified whether the text representation of XML is visible or not (in this case, the appropriate panel collapses).
References IG.Forms.XmlTreeViewControl.chkShowList, IG.Forms.XmlTreeViewControl.chkShowText, and IG.Forms.XmlTreeViewControl.splitContainer2.
chkShowList_CheckedChanged()
void IG.Forms.XmlTreeViewControl.chkShowList_CheckedChanged (object sender, EventArgs e) inline private
State of this check box specified whether the list representation of XML is visible or not (in this case, the appropriate panel collapses).
References IG.Forms.XmlTreeViewControl.chkShowList, IG.Forms.XmlTreeViewControl.chkShowText, and IG.Forms.XmlTreeViewControl.splitContainer2.
ContextMenu_Expand4_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_Expand4_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesExactly(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Expand5_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_Expand5_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesExactly(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtLeastSpecified_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeastSpecified_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesAtLeast(), IG.Forms.XmlTreeViewControl.LevelNumUpDown, IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtLeast1_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast1_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesAtLeast(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtLeast2_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast2_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesAtLeast(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtLeast3_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast3_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesAtLeast(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtLeast4_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast4_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesAtLeast(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtLeast5_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast5_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesAtLeast(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtMostSpecified_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMostSpecified_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesAtMost(), IG.Forms.XmlTreeViewControl.LevelNumUpDown, IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtMost1_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost1_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesAtMost(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtMost2_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost2_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesAtMost(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtMost3_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost3_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesAtMost(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtMost4_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost4_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesAtMost(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtMost5_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost5_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ExpandNodesAtMost(), IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Collapse_Click()
void IG.Forms.XmlTreeViewControl.ContextMenu_Collapse_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.ReportError(), and IG.Forms.XmlTreeViewControl.treeViewXML.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
treeViewXML_NodeMouseHover()
void IG.Forms.XmlTreeViewControl.treeViewXML_NodeMouseHover (object sender, TreeNodeMouseHoverEventArgs e) inline private
References IG.Forms.XmlTreeViewControl.docloaded, IG.Forms.XmlTreeViewControl.getTreeNodePath(), IG.Forms.XmlTreeViewControl.isAttributeContainter(), IG.Forms.XmlTreeViewControl.NodeData.NodeType, and IG.Forms.XmlTreeViewControl.StatusError.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
XMLTreeView_Closing()
void IG.Forms.XmlTreeViewControl.XMLTreeView_Closing (object sender, FormClosingEventArgs e) inline private
References IG.Forms.XmlTreeViewControl.PathTester.
StatusError_Click()
void IG.Forms.XmlTreeViewControl.StatusError_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.StatusError, and IG.Forms.XmlTreeViewControl.StatusStatus.
StatusStatus_Click()
void IG.Forms.XmlTreeViewControl.StatusStatus_Click (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.StatusError, and IG.Forms.XmlTreeViewControl.StatusStatus.
MenuStrip_Enter()
void IG.Forms.XmlTreeViewControl.MenuStrip_Enter (object sender, EventArgs e) inline private
References IG.Forms.XmlTreeViewControl.StatusError, and IG.Forms.XmlTreeViewControl.StatusStatus.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
NodeContextMenu_Opening()
void IG.Forms.XmlTreeViewControl.NodeContextMenu_Opening (object sender, CancelEventArgs e) inline private
References IG.Forms.XmlTreeViewControl.StatusError, and IG.Forms.XmlTreeViewControl.StatusStatus.
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
XmlTreeViewControl_DragDrop()
void IG.Forms.XmlTreeViewControl.XmlTreeViewControl_DragDrop (object sender, DragEventArgs e) inline private
References IG.Forms.XmlTreeViewControl.openFileDialog1, and IG.Forms.XmlTreeViewControl.openFileDialog1_FileOk().
XmlTreeViewControl_DragEnter()
void IG.Forms.XmlTreeViewControl.XmlTreeViewControl_DragEnter (object sender, DragEventArgs e) inline private
Example()
static void IG.Forms.XmlTreeViewControl.Example () inline static
Referenced by igform_console_test.test_igform_console_program.Main().
Dispose()
override void IG.Forms.XmlTreeViewControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.XmlTreeViewControl.components.
Referenced by IG.Forms.XmlTreeViewControl.WindowClose().
InitializeComponent()
void IG.Forms.XmlTreeViewControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.XmlTreeViewControl.BottomPnl, IG.Forms.XmlTreeViewControl.chkShowList, IG.Forms.XmlTreeViewControl.chkShowText, IG.Forms.XmlTreeViewControl.CollAllBtn, IG.Forms.XmlTreeViewControl.CollAllBtn_Click(), IG.Forms.XmlTreeViewControl.Collapse, IG.Forms.XmlTreeViewControl.components, IG.Forms.XmlTreeViewControl.ContextMenu_Collapse_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Copy, IG.Forms.XmlTreeViewControl.ContextMenu_Copy_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_CopyFullPath, IG.Forms.XmlTreeViewControl.ContextMenu_CopyFullPath_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_CopyFullPathExactly, IG.Forms.XmlTreeViewControl.ContextMenu_CopyFullPathExactly_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_CopyNodeText, IG.Forms.XmlTreeViewControl.ContextMenu_CopyNodeText_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Cut, IG.Forms.XmlTreeViewControl.ContextMenu_Cut_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Delete, IG.Forms.XmlTreeViewControl.ContextMenu_Delete_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Edit, IG.Forms.XmlTreeViewControl.ContextMenu_Edit_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_EditMenu, IG.Forms.XmlTreeViewControl.ContextMenu_Expand, IG.Forms.XmlTreeViewControl.ContextMenu_Expand1, IG.Forms.XmlTreeViewControl.ContextMenu_Expand1_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Expand2, IG.Forms.XmlTreeViewControl.ContextMenu_Expand2_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Expand3, IG.Forms.XmlTreeViewControl.ContextMenu_Expand3_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Expand4, IG.Forms.XmlTreeViewControl.ContextMenu_Expand4_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Expand5, IG.Forms.XmlTreeViewControl.ContextMenu_Expand5_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAll, IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAll_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast, IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast1, IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast1_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast2, IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast2_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast3, IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast3_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast4, IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast4_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast5, IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast5_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeastSpecified, IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeastSpecified_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost, IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost1, IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost1_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost2, IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost2_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost3, IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost3_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost4, IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost4_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost5, IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost5_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMostSpecified, IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMostSpecified_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandSpecified, IG.Forms.XmlTreeViewControl.ContextMenu_ExpandSpecified_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Paste, IG.Forms.XmlTreeViewControl.ContextMenu_Paste_Click(), IG.Forms.XmlTreeViewControl.ControlPnl, IG.Forms.XmlTreeViewControl.copyToolStripMenuItem, IG.Forms.XmlTreeViewControl.cutToolStripMenuItem, IG.Forms.XmlTreeViewControl.deleteToolStripMenuItem, IG.Forms.XmlTreeViewControl.DispPanel, IG.Forms.XmlTreeViewControl.editElementToolStripMenuItem, IG.Forms.XmlTreeViewControl.editToolStripMenuItem, IG.Forms.XmlTreeViewControl.ExpAllBtn, IG.Forms.XmlTreeViewControl.ExpAllBtn_Click(), IG.Forms.XmlTreeViewControl.ExpBtn, IG.Forms.XmlTreeViewControl.ExpBtn_Click(), IG.Forms.XmlTreeViewControl.ExpMaxBtn, IG.Forms.XmlTreeViewControl.ExpMaxBtn_Click(), IG.Forms.XmlTreeViewControl.ExpMinBtn, IG.Forms.XmlTreeViewControl.ExpMinBtn_Click(), IG.Forms.XmlTreeViewControl.LevelLbl, IG.Forms.XmlTreeViewControl.LevelNumUpDown, IG.Forms.XmlTreeViewControl.listBoxXML, IG.Forms.XmlTreeViewControl.MenuFile, IG.Forms.XmlTreeViewControl.MenuFile_Close, IG.Forms.XmlTreeViewControl.MenuFile_Close_Click(), IG.Forms.XmlTreeViewControl.MenuFile_CloseDocument, IG.Forms.XmlTreeViewControl.MenuFile_CloseDocument_Click(), IG.Forms.XmlTreeViewControl.MenuFile_Open, IG.Forms.XmlTreeViewControl.MenuFile_Open_Click(), IG.Forms.XmlTreeViewControl.MenuGelp, IG.Forms.XmlTreeViewControl.MenuHelp_About, IG.Forms.XmlTreeViewControl.MenuStrip, IG.Forms.XmlTreeViewControl.MenuStrip_Enter(), IG.Forms.XmlTreeViewControl.MenuTools, IG.Forms.XmlTreeViewControl.MenuTools_CollapseAll, IG.Forms.XmlTreeViewControl.MenuTools_Controls, IG.Forms.XmlTreeViewControl.MenuTools_ExpandAll, IG.Forms.XmlTreeViewControl.MenuTools_Stop, IG.Forms.XmlTreeViewControl.MenuTools_TestXPath, IG.Forms.XmlTreeViewControl.NodeContextMenu, IG.Forms.XmlTreeViewControl.NodeContextMenu_Opening(), IG.Forms.XmlTreeViewControl.NodeImages, IG.Forms.XmlTreeViewControl.openFileDialog1, IG.Forms.XmlTreeViewControl.openFileDialog1_FileOk(), IG.Forms.XmlTreeViewControl.pasteToolStripMenuItem, IG.Forms.XmlTreeViewControl.resources, IG.Forms.XmlTreeViewControl.richTextBoxXML, IG.Forms.XmlTreeViewControl.richTextBoxXML_TextChanged(), IG.Forms.XmlTreeViewControl.splitContainer1, IG.Forms.XmlTreeViewControl.splitContainer2, IG.Forms.XmlTreeViewControl.StatusError, IG.Forms.XmlTreeViewControl.StatusPath, IG.Forms.XmlTreeViewControl.StatusStatus, IG.Forms.XmlTreeViewControl.statusStrip1, IG.Forms.XmlTreeViewControl.StatusType, IG.Forms.XmlTreeViewControl.toolStripSeparator1, IG.Forms.XmlTreeViewControl.toolStripSeparator2, IG.Forms.XmlTreeViewControl.toolStripSeparator3, IG.Forms.XmlTreeViewControl.toolStripSeparator4, IG.Forms.XmlTreeViewControl.toolStripSeparator5, IG.Forms.XmlTreeViewControl.toolStripSeparator6, IG.Forms.XmlTreeViewControl.toolTip1, IG.Forms.XmlTreeViewControl.TopPnl, IG.Forms.XmlTreeViewControl.TopPnlHideBtn, IG.Forms.XmlTreeViewControl.TopPnlHideBtn_Click(), IG.Forms.XmlTreeViewControl.treeViewXML, IG.Forms.XmlTreeViewControl.treeViewXML_AfterSelect(), IG.Forms.XmlTreeViewControl.treeViewXML_NodeMouseClick(), and IG.Forms.XmlTreeViewControl.treeViewXML_NodeMouseHover().
Referenced by IG.Forms.XmlTreeViewControl.XmlTreeViewControl().
MyDelegate()
delegate void IG.Forms.XmlTreeViewControl.MyDelegate () private
Member Data Documentation
_InitialTextRichTextBoxXML
string IG.Forms.XmlTreeViewControl._InitialTextRichTextBoxXML = "<< Drag & drop XML files above. >>" private
CursorDefault
Cursor IG.Forms.XmlTreeViewControl.CursorDefault = Cursors.Default private
Referenced by IG.Forms.XmlTreeViewControl.FinalizeNotifications(), and IG.Forms.XmlTreeViewControl.XMLTreeView_Load().
ActiveBackColor
Color IG.Forms.XmlTreeViewControl.ActiveBackColor = Color.White private
Referenced by IG.Forms.XmlTreeViewControl.FinalizeNotifications().
InActiveBackColor
Color IG.Forms.XmlTreeViewControl.InActiveBackColor = Color.WhiteSmoke private
Referenced by IG.Forms.XmlTreeViewControl.ResetNotifications().
Editable
bool IG.Forms.XmlTreeViewControl.Editable = true
Referenced by IG.Forms.XmlTreeViewControl.CopyNode(), IG.Forms.XmlTreeViewControl.CutNode(), IG.Forms.XmlTreeViewControl.DeleteNode(), IG.Forms.XmlTreeViewControl.EditNode(), and IG.Forms.XmlTreeViewControl.PasteNode().
ShowText
bool IG.Forms.XmlTreeViewControl.ShowText = true private
Referenced by IG.Forms.XmlTreeViewControl.treeViewXML_AfterSelect(), and IG.Forms.XmlTreeViewControl.XMLTreeView_Load().
Doc
XmlDocument IG.Forms.XmlTreeViewControl.Doc = null protected
Referenced by IG.Forms.XmlTreeViewControl.FindXmlNode(), IG.Forms.XmlTreeViewControl.LoadFileToDoc(), and IG.Forms.XmlTreeViewControl.MenuTools_TestXPath_Click().
PathTester
XMLTestPathForm IG.Forms.XmlTreeViewControl.PathTester = null protected
Referenced by IG.Forms.XmlTreeViewControl.MenuTools_TestXPath_Click(), IG.Forms.XmlTreeViewControl.PathTester_Close(), IG.Forms.XmlTreeViewControl.treeViewXML_AfterSelect(), and IG.Forms.XmlTreeViewControl.XMLTreeView_Closing().
SourceType
XMLSourceType IG.Forms.XmlTreeViewControl.SourceType = XMLSourceType.TextFile
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
TitleBase
string IG.Forms.XmlTreeViewControl.TitleBase = "XMLViewer" private
Referenced by IG.Forms.XmlTreeViewControl.openFileDialog1_FileOk(), and IG.Forms.XmlTreeViewControl.XMLTreeView_Load().
RootBackColor
System.Drawing.Color IG.Forms.XmlTreeViewControl.RootBackColor = Color.FromArgb(255, 180, 180) protected
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
RootForeColor
System.Drawing.Color IG.Forms.XmlTreeViewControl.RootForeColor = Color.Black private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
ElementBackColor
System.Drawing.Color IG.Forms.XmlTreeViewControl.ElementBackColor = Color.White private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
ElementForeColor
System.Drawing.Color IG.Forms.XmlTreeViewControl.ElementForeColor = Color.Red private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
TextBackColor
System.Drawing.Color IG.Forms.XmlTreeViewControl.TextBackColor = Color.FromArgb(255, 255, 180) private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
TextForeColor
System.Drawing.Color IG.Forms.XmlTreeViewControl.TextForeColor = Color.Black private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
AttrNameBackColor
System.Drawing.Color IG.Forms.XmlTreeViewControl.AttrNameBackColor = Color.White private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
AttrNameForeColor
System.Drawing.Color IG.Forms.XmlTreeViewControl.AttrNameForeColor = Color.Blue private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
AttrValBackColor
System.Drawing.Color IG.Forms.XmlTreeViewControl.AttrValBackColor = Color.White private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
AttrValForeColor
System.Drawing.Color IG.Forms.XmlTreeViewControl.AttrValForeColor = Color.Green private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
CommentBackColor
System.Drawing.Color IG.Forms.XmlTreeViewControl.CommentBackColor = Color.White private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
CommentForeColor
System.Drawing.Color IG.Forms.XmlTreeViewControl.CommentForeColor = Color.Gray private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
AttrContBackColor
System.Drawing.Color IG.Forms.XmlTreeViewControl.AttrContBackColor = Color.White private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
AttrContForeColor
System.Drawing.Color IG.Forms.XmlTreeViewControl.AttrContForeColor = Color.LightGray private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
NoneImageKey
string IG.Forms.XmlTreeViewControl.NoneImageKey = "xml_none" protected
RootImageKey
string IG.Forms.XmlTreeViewControl.RootImageKey = "xml_root" private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
ElementImageKey
string IG.Forms.XmlTreeViewControl.ElementImageKey = "xml_element" private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
TextImageKey
string IG.Forms.XmlTreeViewControl.TextImageKey = "xml_text" private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
AttrNameImageKey
string IG.Forms.XmlTreeViewControl.AttrNameImageKey = "xml_attribute_name" private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
AttrValImageKey
string IG.Forms.XmlTreeViewControl.AttrValImageKey = "xml_attribute_value" private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
CommentImageKey
string IG.Forms.XmlTreeViewControl.CommentImageKey = "xml_comment" private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
haschanged
bool IG.Forms.XmlTreeViewControl.haschanged = false private
docloaded
bool IG.Forms.XmlTreeViewControl.docloaded = false private
Referenced by IG.Forms.XmlTreeViewControl.treeViewXML_NodeMouseHover().
expattr
bool IG.Forms.XmlTreeViewControl.expattr = true private
attsubnode
bool IG.Forms.XmlTreeViewControl.attsubnode = true private
XMLInputFile
string IG.Forms.XmlTreeViewControl.XMLInputFile = null private
Referenced by IG.Forms.XmlTreeViewControl.LoadFileToDoc(), IG.Forms.XmlTreeViewControl.LoadFileToListBox(), IG.Forms.XmlTreeViewControl.LoadFileToTextBox(), IG.Forms.XmlTreeViewControl.openFileDialog1_FileOk(), and IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
FileSize
string IG.Forms.XmlTreeViewControl.FileSize = "" private
Referenced by IG.Forms.XmlTreeViewControl.openFileDialog1_FileOk().
WorkingDir
string IG.Forms.XmlTreeViewControl.WorkingDir = Directory.GetCurrentDirectory() private
CurrentView
int IG.Forms.XmlTreeViewControl.CurrentView = (int)VIEW.TREE_VIEW private
Referenced by IG.Forms.XmlTreeViewControl.EnableDisableControls(), and IG.Forms.XmlTreeViewControl.menuItem3_DrawItem().
t
Thread IG.Forms.XmlTreeViewControl.t = null private
Referenced by IG.Forms.XmlTreeViewControl.AssociateTag(), and IG.Forms.XmlTreeViewControl.TExpandAll().
RootNode
TreeNode IG.Forms.XmlTreeViewControl.RootNode = null private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
ClickedPoint
Point IG.Forms.XmlTreeViewControl.ClickedPoint = new Point(0, 0) private
TreeNodeArray
ArrayList IG.Forms.XmlTreeViewControl.TreeNodeArray = new ArrayList() private
Referenced by IG.Forms.XmlTreeViewControl.Clear(), and IG.Forms.XmlTreeViewControl.openFileDialog1_FileOk().
resources
System.ComponentModel.ComponentResourceManager IG.Forms.XmlTreeViewControl.resources = null private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent(), and IG.Forms.XmlTreeViewControl.XMLTreeView_Load().
numLoadsToPerform
int IG.Forms.XmlTreeViewControl.numLoadsToPerform = 0 private
Referenced by IG.Forms.XmlTreeViewControl.NotifyFinished(), IG.Forms.XmlTreeViewControl.NotifyStarted(), IG.Forms.XmlTreeViewControl.ResetNotifications(), and IG.Forms.XmlTreeViewControl.UnlockNotifications().
countLock
int IG.Forms.XmlTreeViewControl.countLock = 0 private
Referenced by IG.Forms.XmlTreeViewControl.LockNotifications(), IG.Forms.XmlTreeViewControl.NotifyFinished(), IG.Forms.XmlTreeViewControl.ResetNotifications(), and IG.Forms.XmlTreeViewControl.UnlockNotifications().
components
System.ComponentModel.IContainer IG.Forms.XmlTreeViewControl.components = null private
Required designer variable.
Referenced by IG.Forms.XmlTreeViewControl.Dispose(), and IG.Forms.XmlTreeViewControl.InitializeComponent().
img_fileopen
Bitmap IG.Forms.XmlTreeViewControl.img_fileopen private
Referenced by IG.Forms.XmlTreeViewControl.menuItem3_DrawItem(), and IG.Forms.XmlTreeViewControl.XMLTreeView_Load().
img_exit
Bitmap IG.Forms.XmlTreeViewControl.img_exit private
Referenced by IG.Forms.XmlTreeViewControl.menuItem3_DrawItem(), and IG.Forms.XmlTreeViewControl.XMLTreeView_Load().
img_collapse
Bitmap IG.Forms.XmlTreeViewControl.img_collapse private
Referenced by IG.Forms.XmlTreeViewControl.menuItem3_DrawItem(), and IG.Forms.XmlTreeViewControl.XMLTreeView_Load().
img_expand
Bitmap IG.Forms.XmlTreeViewControl.img_expand private
Referenced by IG.Forms.XmlTreeViewControl.menuItem3_DrawItem(), and IG.Forms.XmlTreeViewControl.XMLTreeView_Load().
img_about
Bitmap IG.Forms.XmlTreeViewControl.img_about private
Referenced by IG.Forms.XmlTreeViewControl.menuItem3_DrawItem(), and IG.Forms.XmlTreeViewControl.XMLTreeView_Load().
treeViewXML
System.Windows.Forms.TreeView IG.Forms.XmlTreeViewControl.treeViewXML private
Referenced by IG.Forms.XmlTreeViewControl.ContextMenu_Collapse_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Copy_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_CopyFullPath_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_CopyFullPathExactly_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_CopyNodeText_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Cut_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Delete_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Edit_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Expand1_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Expand2_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Expand3_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Expand4_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Expand5_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAll_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast1_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast2_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast3_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast4_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast5_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeastSpecified_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost1_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost2_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost3_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost4_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost5_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMostSpecified_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandSpecified_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_Paste_Click(), IG.Forms.XmlTreeViewControl.EnableDisableControls(), IG.Forms.XmlTreeViewControl.ExpandAll(), IG.Forms.XmlTreeViewControl.ExpBtn_Click(), IG.Forms.XmlTreeViewControl.ExpMaxBtn_Click(), IG.Forms.XmlTreeViewControl.ExpMinBtn_Click(), IG.Forms.XmlTreeViewControl.FinalizeNotifications(), IG.Forms.XmlTreeViewControl.InitializeComponent(), IG.Forms.XmlTreeViewControl.MenuTools_Copy_Click(), IG.Forms.XmlTreeViewControl.MenuTools_Cut_Click(), IG.Forms.XmlTreeViewControl.MenuTools_Edit_Click(), IG.Forms.XmlTreeViewControl.MenuTools_Paste_Click(), IG.Forms.XmlTreeViewControl.MenuTools_TestXPath_Click(), IG.Forms.XmlTreeViewControl.openFileDialog1_FileOk(), IG.Forms.XmlTreeViewControl.ParseFileToTreeView(), IG.Forms.XmlTreeViewControl.ResetNotifications(), and IG.Forms.XmlTreeViewControl.TCollapseAll().
listBoxXML
System.Windows.Forms.ListBox IG.Forms.XmlTreeViewControl.listBoxXML private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent(), IG.Forms.XmlTreeViewControl.LoadFileToListBox(), IG.Forms.XmlTreeViewControl.MoveToLine(), IG.Forms.XmlTreeViewControl.openFileDialog1_FileOk(), IG.Forms.XmlTreeViewControl.ResetNotifications(), and IG.Forms.XmlTreeViewControl.XMLTreeView_Load().
DispPanel
Panel IG.Forms.XmlTreeViewControl.DispPanel private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
TopPnl
Panel IG.Forms.XmlTreeViewControl.TopPnl private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
BottomPnl
Panel IG.Forms.XmlTreeViewControl.BottomPnl private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ExpAllBtn
Button IG.Forms.XmlTreeViewControl.ExpAllBtn private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
CollAllBtn
Button IG.Forms.XmlTreeViewControl.CollAllBtn private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
LevelLbl
Label IG.Forms.XmlTreeViewControl.LevelLbl private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
LevelNumUpDown
NumericUpDown IG.Forms.XmlTreeViewControl.LevelNumUpDown private
Referenced by IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeastSpecified_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMostSpecified_Click(), IG.Forms.XmlTreeViewControl.ContextMenu_ExpandSpecified_Click(), IG.Forms.XmlTreeViewControl.ExpBtn_Click(), IG.Forms.XmlTreeViewControl.ExpMaxBtn_Click(), IG.Forms.XmlTreeViewControl.ExpMinBtn_Click(), and IG.Forms.XmlTreeViewControl.InitializeComponent().
ExpMinBtn
Button IG.Forms.XmlTreeViewControl.ExpMinBtn private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ExpBtn
Button IG.Forms.XmlTreeViewControl.ExpBtn private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ExpMaxBtn
Button IG.Forms.XmlTreeViewControl.ExpMaxBtn private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
TopPnlHideBtn
Button IG.Forms.XmlTreeViewControl.TopPnlHideBtn private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
MenuStrip
MenuStrip IG.Forms.XmlTreeViewControl.MenuStrip private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_CopyFullPath
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_CopyFullPath private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_CopyFullPathExactly
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_CopyFullPathExactly private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_CopyNodeText
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_CopyNodeText private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
toolStripSeparator2
ToolStripSeparator IG.Forms.XmlTreeViewControl.toolStripSeparator2 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_EditMenu
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_EditMenu private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
toolStripSeparator1
ToolStripSeparator IG.Forms.XmlTreeViewControl.toolStripSeparator1 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Expand
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_Expand private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandSpecified
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_ExpandSpecified private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Expand1
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_Expand1 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Expand2
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_Expand2 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Expand3
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_Expand3 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Expand4
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_Expand4 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Expand5
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_Expand5 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtLeast
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtLeastSpecified
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeastSpecified private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtLeast1
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast1 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtLeast2
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast2 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtLeast3
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast3 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtLeast4
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast4 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtLeast5
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtLeast5 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtMost
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtMostSpecified
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMostSpecified private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtMost1
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost1 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtMost2
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost2 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtMost3
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost3 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtMost4
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost4 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_ExpandAtMost5
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAtMost5 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
Collapse
ToolStripMenuItem IG.Forms.XmlTreeViewControl.Collapse private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
NodeContextMenu
ContextMenuStrip IG.Forms.XmlTreeViewControl.NodeContextMenu private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
MenuFile
ToolStripMenuItem IG.Forms.XmlTreeViewControl.MenuFile private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
MenuTools
ToolStripMenuItem IG.Forms.XmlTreeViewControl.MenuTools private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
MenuGelp
ToolStripMenuItem IG.Forms.XmlTreeViewControl.MenuGelp private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
MenuFile_Open
ToolStripMenuItem IG.Forms.XmlTreeViewControl.MenuFile_Open private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
MenuFile_Close
ToolStripMenuItem IG.Forms.XmlTreeViewControl.MenuFile_Close private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
MenuTools_ExpandAll
ToolStripMenuItem IG.Forms.XmlTreeViewControl.MenuTools_ExpandAll private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
MenuTools_CollapseAll
ToolStripMenuItem IG.Forms.XmlTreeViewControl.MenuTools_CollapseAll private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
MenuTools_Stop
ToolStripMenuItem IG.Forms.XmlTreeViewControl.MenuTools_Stop private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
MenuHelp_About
ToolStripMenuItem IG.Forms.XmlTreeViewControl.MenuHelp_About private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
MenuTools_Controls
ToolStripMenuItem IG.Forms.XmlTreeViewControl.MenuTools_Controls private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent(), and IG.Forms.XmlTreeViewControl.TopPnlHideBtn_Click().
ControlPnl
Panel IG.Forms.XmlTreeViewControl.ControlPnl private
Referenced by IG.Forms.XmlTreeViewControl.HideControlPnl(), IG.Forms.XmlTreeViewControl.InitializeComponent(), and IG.Forms.XmlTreeViewControl.ShowControlPnl().
toolStripSeparator3
ToolStripSeparator IG.Forms.XmlTreeViewControl.toolStripSeparator3 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
toolStripSeparator4
ToolStripSeparator IG.Forms.XmlTreeViewControl.toolStripSeparator4 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
statusStrip1
StatusStrip IG.Forms.XmlTreeViewControl.statusStrip1 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
StatusPath
ToolStripStatusLabel IG.Forms.XmlTreeViewControl.StatusPath private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent(), and IG.Forms.XmlTreeViewControl.treeViewXML_AfterSelect().
StatusType
ToolStripStatusLabel IG.Forms.XmlTreeViewControl.StatusType private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent(), and IG.Forms.XmlTreeViewControl.treeViewXML_AfterSelect().
StatusError
ToolStripStatusLabel IG.Forms.XmlTreeViewControl.StatusError private
Referenced by IG.Forms.XmlTreeViewControl.CollAllBtn_Click(), IG.Forms.XmlTreeViewControl.ExpAllBtn_Click(), IG.Forms.XmlTreeViewControl.ExpBtn_Click(), IG.Forms.XmlTreeViewControl.ExpMaxBtn_Click(), IG.Forms.XmlTreeViewControl.ExpMinBtn_Click(), IG.Forms.XmlTreeViewControl.InitializeComponent(), IG.Forms.XmlTreeViewControl.MenuStrip_Enter(), IG.Forms.XmlTreeViewControl.NodeContextMenu_Opening(), IG.Forms.XmlTreeViewControl.ReportError(), IG.Forms.XmlTreeViewControl.StatusError_Click(), IG.Forms.XmlTreeViewControl.StatusStatus_Click(), IG.Forms.XmlTreeViewControl.treeViewXML_AfterSelect(), IG.Forms.XmlTreeViewControl.treeViewXML_NodeMouseHover(), and IG.Forms.XmlTreeViewControl.XMLTreeView_Load().
splitContainer1
SplitContainer IG.Forms.XmlTreeViewControl.splitContainer1 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
openFileDialog1
System.Windows.Forms.OpenFileDialog IG.Forms.XmlTreeViewControl.openFileDialog1 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent(), IG.Forms.XmlTreeViewControl.MenuFile_Open_Click(), IG.Forms.XmlTreeViewControl.openFileDialog1_FileOk(), and IG.Forms.XmlTreeViewControl.XmlTreeViewControl_DragDrop().
NumErr
int IG.Forms.XmlTreeViewControl.NumErr = 0 private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
MaxErr
int IG.Forms.XmlTreeViewControl.MaxErr = 3 private
Referenced by IG.Forms.XmlTreeViewControl.ParseFileToTreeView().
editToolStripMenuItem
ToolStripMenuItem IG.Forms.XmlTreeViewControl.editToolStripMenuItem private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
editElementToolStripMenuItem
ToolStripMenuItem IG.Forms.XmlTreeViewControl.editElementToolStripMenuItem private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
cutToolStripMenuItem
ToolStripMenuItem IG.Forms.XmlTreeViewControl.cutToolStripMenuItem private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
copyToolStripMenuItem
ToolStripMenuItem IG.Forms.XmlTreeViewControl.copyToolStripMenuItem private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
pasteToolStripMenuItem
ToolStripMenuItem IG.Forms.XmlTreeViewControl.pasteToolStripMenuItem private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
NodeImages
ImageList IG.Forms.XmlTreeViewControl.NodeImages private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
MenuTools_TestXPath
ToolStripMenuItem IG.Forms.XmlTreeViewControl.MenuTools_TestXPath private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
toolStripSeparator5
ToolStripSeparator IG.Forms.XmlTreeViewControl.toolStripSeparator5 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
toolStripSeparator6
ToolStripSeparator IG.Forms.XmlTreeViewControl.toolStripSeparator6 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
toolTip1
ToolTip IG.Forms.XmlTreeViewControl.toolTip1 private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
deleteToolStripMenuItem
ToolStripMenuItem IG.Forms.XmlTreeViewControl.deleteToolStripMenuItem private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
MenuFile_CloseDocument
ToolStripMenuItem IG.Forms.XmlTreeViewControl.MenuFile_CloseDocument private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Edit
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_Edit private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Cut
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_Cut private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Copy
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_Copy private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Paste
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_Paste private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
ContextMenu_Delete
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_Delete private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
richTextBoxXML
RichTextBox IG.Forms.XmlTreeViewControl.richTextBoxXML private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent(), IG.Forms.XmlTreeViewControl.LoadFileToTextBox(), IG.Forms.XmlTreeViewControl.MoveToLine(), IG.Forms.XmlTreeViewControl.ResetNotifications(), IG.Forms.XmlTreeViewControl.XMLTreeView_Load(), and IG.Forms.XmlTreeViewControl.XmlTreeViewControl().
StatusStatus
ToolStripStatusLabel IG.Forms.XmlTreeViewControl.StatusStatus private
Referenced by IG.Forms.XmlTreeViewControl.CollAllBtn_Click(), IG.Forms.XmlTreeViewControl.ExpAllBtn_Click(), IG.Forms.XmlTreeViewControl.ExpBtn_Click(), IG.Forms.XmlTreeViewControl.ExpMaxBtn_Click(), IG.Forms.XmlTreeViewControl.ExpMinBtn_Click(), IG.Forms.XmlTreeViewControl.InitializeComponent(), IG.Forms.XmlTreeViewControl.MenuStrip_Enter(), IG.Forms.XmlTreeViewControl.NodeContextMenu_Opening(), IG.Forms.XmlTreeViewControl.StatusError_Click(), IG.Forms.XmlTreeViewControl.StatusStatus_Click(), and IG.Forms.XmlTreeViewControl.treeViewXML_AfterSelect().
ContextMenu_ExpandAll
ToolStripMenuItem IG.Forms.XmlTreeViewControl.ContextMenu_ExpandAll private
Referenced by IG.Forms.XmlTreeViewControl.InitializeComponent().
splitContainer2
SplitContainer IG.Forms.XmlTreeViewControl.splitContainer2 private
Referenced by IG.Forms.XmlTreeViewControl.chkShowList_CheckedChanged(), IG.Forms.XmlTreeViewControl.chkShowText_CheckedChanged(), and IG.Forms.XmlTreeViewControl.InitializeComponent().
chkShowList
CheckBox IG.Forms.XmlTreeViewControl.chkShowList private
Referenced by IG.Forms.XmlTreeViewControl.chkShowList_CheckedChanged(), IG.Forms.XmlTreeViewControl.chkShowText_CheckedChanged(), and IG.Forms.XmlTreeViewControl.InitializeComponent().
chkShowText
CheckBox IG.Forms.XmlTreeViewControl.chkShowText private
Referenced by IG.Forms.XmlTreeViewControl.chkShowList_CheckedChanged(), IG.Forms.XmlTreeViewControl.chkShowText_CheckedChanged(), and IG.Forms.XmlTreeViewControl.InitializeComponent().
Property Documentation
InitialTextRichTextBoxXml
string IG.Forms.XmlTreeViewControl.InitialTextRichTextBoxXml get
Text that is initially written
Referenced by IG.Forms.XmlTreeViewControl.XmlTreeViewControl().
HasChanged
bool IG.Forms.XmlTreeViewControl.HasChanged get set
Referenced by IG.Forms.XmlTreeViewControl.CopyNode(), IG.Forms.XmlTreeViewControl.CutNode(), IG.Forms.XmlTreeViewControl.DeleteNode(), IG.Forms.XmlTreeViewControl.EditNode(), and IG.Forms.XmlTreeViewControl.PasteNode().
DocumentLoaded
bool IG.Forms.XmlTreeViewControl.DocumentLoaded get set
Referenced by IG.Forms.XmlTreeViewControl.CopyNode(), IG.Forms.XmlTreeViewControl.CutNode(), IG.Forms.XmlTreeViewControl.DeleteNode(), IG.Forms.XmlTreeViewControl.EditNode(), IG.Forms.XmlTreeViewControl.FinalizeNotifications(), IG.Forms.XmlTreeViewControl.MenuFile_CloseDocument_Click(), IG.Forms.XmlTreeViewControl.PasteNode(), and IG.Forms.XmlTreeViewControl.ResetNotifications().
ExpAttr
bool IG.Forms.XmlTreeViewControl.ExpAttr get set
Referenced by IG.Forms.XmlTreeViewForm.InitializeComponent().
AttrSubnode
bool IG.Forms.XmlTreeViewControl.AttrSubnode get set
Referenced by IG.Forms.XmlTreeViewForm.InitializeComponent().
The documentation for this class was generated from the following files:
iglib/igforms/Basic/XmlTreeViewControl.cs
iglib/igforms/Basic/XmlTreeViewControl.Designer.cs