Doc: IGLib EXTENDED: NUnit.Framework.Syntax.PropertySyntaxVariations Class Reference
NUnit.Framework.Syntax.PropertySyntaxVariations Class Reference
Public Member Functions
void ExistenceTest ()
void SeparateConstraintTest ()
Private Attributes
readonly int[] ints = new int[] { 1, 2, 3 }
Member Function Documentation
ExistenceTest()
void NUnit.Framework.Syntax.PropertySyntaxVariations.ExistenceTest () inline
References NUnit.Framework.Syntax.PropertySyntaxVariations.ints, NUnit.Framework.Has.Length, NUnit.Framework.Has.Property(), and NUnit.Framework.Assert.That().
SeparateConstraintTest()
void NUnit.Framework.Syntax.PropertySyntaxVariations.SeparateConstraintTest () inline
References NUnit.Framework.Syntax.PropertySyntaxVariations.ints, NUnit.Framework.Has.Length, NUnit.Framework.Has.Property(), and NUnit.Framework.Assert.That().
Member Data Documentation
ints
readonly int [] NUnit.Framework.Syntax.PropertySyntaxVariations.ints = new int[] { 1, 2, 3 } private
Referenced by NUnit.Framework.Syntax.PropertySyntaxVariations.ExistenceTest(), and NUnit.Framework.Syntax.PropertySyntaxVariations.SeparateConstraintTest().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Syntax/PropertyTests.cs