Doc: IGLib EXTENDED: NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests Class Reference
NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests Class Reference
Public Member Functions
void CreateLoader ()
void ValidExtensions (string project, bool isGood)
void CannotLoadWebProject ()
void CanLoadVsProject (string resourceName, string[] configs, string assemblyName)
void FromVSSolution2003 ()
void FromVSSolution2005 ()
void FromWebApplication ()
void WithUnmanagedCpp ()
void FromSolutionWithDisabledProject ()
Private Attributes
VisualStudioProjectLoader _loader
Member Function Documentation
CreateLoader()
void NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.CreateLoader () inline
References NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests._loader.
ValidExtensions()
void NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.ValidExtensions (string project, bool isGood) inline
References NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests._loader, NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader.CanLoadFrom(), NUnit.Framework.Assert.False(), and NUnit.Framework.Assert.That().
CannotLoadWebProject()
void NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.CannotLoadWebProject () inline
References NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests._loader, NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader.CanLoadFrom(), and NUnit.Framework.Assert.IsFalse().
CanLoadVsProject()
void NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.CanLoadVsProject (string resourceName, string[] configs, string assemblyName) inline
References NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests._loader, NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader.CanLoadFrom(), NUnit.Engine.Extensibility.IProject.ConfigNames, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader.LoadFrom(), NUnit.Engine.Tests.TempResourceFile.Path, NUnit.Framework.Is.SamePath(), and NUnit.Framework.Assert.That().
FromVSSolution2003()
void NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromVSSolution2003 () inline
References NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests._loader, NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Extensibility.IProject.ConfigNames, NUnit.Engine.Extensibility.IProject.GetTestPackage(), NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader.LoadFrom(), NUnit.Engine.Tests.TempResourceFile.Path, and NUnit.Engine.TestPackage.SubPackages.
FromVSSolution2005()
void NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromVSSolution2005 () inline
References NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests._loader, NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Extensibility.IProject.ConfigNames, NUnit.Engine.Extensibility.IProject.GetTestPackage(), NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader.LoadFrom(), NUnit.Engine.Tests.TempResourceFile.Path, and NUnit.Engine.TestPackage.SubPackages.
FromWebApplication()
void NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromWebApplication () inline
References NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests._loader, NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Extensibility.IProject.ConfigNames, NUnit.Engine.Extensibility.IProject.GetTestPackage(), NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader.LoadFrom(), NUnit.Engine.Tests.TempResourceFile.Path, and NUnit.Engine.TestPackage.SubPackages.
WithUnmanagedCpp()
void NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.WithUnmanagedCpp () inline
References NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests._loader, NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Extensibility.IProject.ConfigNames, NUnit.Engine.Extensibility.IProject.GetTestPackage(), NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader.LoadFrom(), NUnit.Engine.Tests.TempResourceFile.Path, and NUnit.Engine.TestPackage.SubPackages.
FromSolutionWithDisabledProject()
void NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromSolutionWithDisabledProject () inline
References NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests._loader, NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Extensibility.IProject.ConfigNames, NUnit.Engine.Extensibility.IProject.GetTestPackage(), NUnit.Engine.Services.ProjectLoaders.VisualStudioProjectLoader.LoadFrom(), NUnit.Engine.Tests.TempResourceFile.Path, and NUnit.Engine.TestPackage.SubPackages.
Member Data Documentation
_loader
VisualStudioProjectLoader NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests._loader private
Referenced by NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.CanLoadVsProject(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.CannotLoadWebProject(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.CreateLoader(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromSolutionWithDisabledProject(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromVSSolution2003(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromVSSolution2005(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.FromWebApplication(), NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.ValidExtensions(), and NUnit.Engine.Services.ProjectLoaders.Tests.VisualStudioProjectLoaderTests.WithUnmanagedCpp().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/Addins/addin-tests/VisualStudioProjectLoaderTests.cs