Doc: IGLib EXTENDED: NUnit.Framework.Internal.TestProgressReporter Class Reference
NUnit.Framework.Internal.TestProgressReporter Class Reference
TestProgressReporter translates ITestListener events into the async callbacks that are used to inform the client software about the progress of a test run.
Public Member Functions
TestProgressReporter (ICallbackEventHandler handler)
Initializes a new instance of the TestProgressReporter class.
void TestStarted (ITest test)
Called when a test has just started
void TestFinished (ITestResult result)
Called when a test has finished. Sends a result summary to the callback. to
Static Private Member Functions
static ITest GetParent (ITest test)
Returns the parent test item for the targer test item if it exists
static string FormatAttributeValue (string original)
Makes a string safe for use as an attribute, replacing characters characters that can't be used with their corresponding xml representations.
Private Attributes
ICallbackEventHandler handler
Static Private Attributes
static Logger log = InternalTrace.GetLogger("TestProgressReporter")
Detailed Description
TestProgressReporter translates ITestListener events into the async callbacks that are used to inform the client software about the progress of a test run.
Constructor & Destructor Documentation
TestProgressReporter()
NUnit.Framework.Internal.TestProgressReporter.TestProgressReporter (ICallbackEventHandler handler) inline
Initializes a new instance of the TestProgressReporter class.
Parameters
handler The callback handler to be used for reporting progress.
References NUnit.Framework.Internal.TestProgressReporter.handler.
Member Function Documentation
TestStarted()
void NUnit.Framework.Internal.TestProgressReporter.TestStarted (ITest test) inline
Called when a test has just started
Parameters
test The test that is starting
Implements NUnit.Framework.Interfaces.ITestListener.
References NUnit.Framework.Internal.TestProgressReporter.FormatAttributeValue(), NUnit.Framework.Interfaces.ITest.FullName, NUnit.Framework.Internal.TestProgressReporter.GetParent(), NUnit.Framework.Internal.TestProgressReporter.handler, NUnit.Framework.Interfaces.ITest.Id, NUnit.Framework.Internal.TestProgressReporter.log, NUnit.Framework.Interfaces.ITest.Name, and NUnit.Env.NewLine.
TestFinished()
void NUnit.Framework.Internal.TestProgressReporter.TestFinished (ITestResult result) inline
Called when a test has finished. Sends a result summary to the callback. to
Parameters
result The result of the test
Implements NUnit.Framework.Interfaces.ITestListener.
References NUnit.Framework.Interfaces.ITestResult.FullName, NUnit.Framework.Internal.TestProgressReporter.GetParent(), NUnit.Framework.Internal.TestProgressReporter.handler, NUnit.Framework.Internal.TestProgressReporter.log, NUnit.Env.NewLine, NUnit.Framework.Interfaces.ITestResult.Test, and NUnit.Framework.Interfaces.IXmlNodeBuilder.ToXml().
GetParent()
static ITest NUnit.Framework.Internal.TestProgressReporter.GetParent (ITest test) inline static private
Returns the parent test item for the targer test item if it exists
Parameters
test
Returns
parent test item
References NUnit.Framework.Interfaces.ITest.IsSuite, and NUnit.Framework.Interfaces.ITest.Parent.
Referenced by NUnit.Framework.Internal.TestProgressReporter.TestFinished(), and NUnit.Framework.Internal.TestProgressReporter.TestStarted().
FormatAttributeValue()
static string NUnit.Framework.Internal.TestProgressReporter.FormatAttributeValue (string original) inline static private
Makes a string safe for use as an attribute, replacing characters characters that can't be used with their corresponding xml representations.
Parameters
original The string to be used
Returns
A new string with the _values replaced
Referenced by NUnit.Framework.Internal.TestProgressReporter.TestStarted().
Member Data Documentation
log
Logger NUnit.Framework.Internal.TestProgressReporter.log = InternalTrace.GetLogger("TestProgressReporter") static private
Referenced by NUnit.Framework.Internal.TestProgressReporter.TestFinished(), and NUnit.Framework.Internal.TestProgressReporter.TestStarted().
handler
ICallbackEventHandler NUnit.Framework.Internal.TestProgressReporter.handler private
Referenced by NUnit.Framework.Internal.TestProgressReporter.TestFinished(), NUnit.Framework.Internal.TestProgressReporter.TestProgressReporter(), and NUnit.Framework.Internal.TestProgressReporter.TestStarted().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/TestProgressReporter.cs