Doc: IGLib EXTENDED: NUnit.Framework.Constraints.CollectionContainsConstraintTests Class Reference
NUnit.Framework.Constraints.CollectionContainsConstraintTests Class Reference
Public Member Functions
void CanTestContentsOfArray ()
void CanTestContentsOfObjectList ()
void CanTestContentsOfSortedList ()
void CanTestContentsOfCollectionNotImplementingIList ()
void IgnoreCaseIsHonored (object expected, IEnumerable actual)
void UsingIsHonored ()
Static Private Attributes
static readonly object[] IgnoreCaseData
Member Function Documentation
CanTestContentsOfArray()
void NUnit.Framework.Constraints.CollectionContainsConstraintTests.CanTestContentsOfArray () inline
References NUnit.Framework.Assert.That().
CanTestContentsOfObjectList()
void NUnit.Framework.Constraints.CollectionContainsConstraintTests.CanTestContentsOfObjectList () inline
References NUnit.Framework.Assert.That().
CanTestContentsOfSortedList()
void NUnit.Framework.Constraints.CollectionContainsConstraintTests.CanTestContentsOfSortedList () inline
References NUnit.Framework.Assert.That().
CanTestContentsOfCollectionNotImplementingIList()
void NUnit.Framework.Constraints.CollectionContainsConstraintTests.CanTestContentsOfCollectionNotImplementingIList () inline
References NUnit.Framework.Assert.That().
IgnoreCaseIsHonored()
void NUnit.Framework.Constraints.CollectionContainsConstraintTests.IgnoreCaseIsHonored (object expected, IEnumerable actual) inline
References NUnit.Framework.Assert.Fail(), and NUnit.Framework.Constraints.CollectionItemsEqualConstraint.IgnoreCase.
UsingIsHonored()
void NUnit.Framework.Constraints.CollectionContainsConstraintTests.UsingIsHonored () inline
References NUnit.Framework.Internal.StringUtil.Compare(), NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.CollectionItemsEqualConstraint.Using().
Member Data Documentation
IgnoreCaseData
readonly object [] NUnit.Framework.Constraints.CollectionContainsConstraintTests.IgnoreCaseData static private
Initial value:
=
        {
            new object[] {"WORLD", new string[] { "Hello", "World" }},
            new object[] {"z",new SimpleObjectCollection("z", "Y", "X")},
            new object[] {'A', new object[] {'a', 'b', 'c'}},
            new object[] {"a", new object[] {"A", "B", "C"}}
        }
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/CollectionContainsConstraintTests.cs