Doc: IGLib EXTENDED: AForge.Imaging.HoughLineTransformation Class Reference
AForge.Imaging.HoughLineTransformation Class Reference
Hough line transformation.
Public Member Functions
HoughLineTransformation ()
Initializes a new instance of the HoughLineTransformation class.
void ProcessImage (Bitmap image)
Process an image building Hough map.
void ProcessImage (Bitmap image, Rectangle rect)
Process an image building Hough map.
void ProcessImage (BitmapData imageData)
Process an image building Hough map.
void ProcessImage (BitmapData imageData, Rectangle rect)
Process an image building Hough map.
void ProcessImage (UnmanagedImage image)
Process an image building Hough map.
void ProcessImage (UnmanagedImage image, Rectangle rect)
Process an image building Hough map.
Bitmap ToBitmap ()
Convert Hough map to bitmap.
HoughLine[] GetMostIntensiveLines (int count)
Get specified amount of lines with highest intensity.
HoughLine[] GetLinesByRelativeIntensity (double minRelativeIntensity)
Get lines with relative intensity higher then specified value.
Properties
int StepsPerDegree [get, set]
Steps per degree.
short MinLineIntensity [get, set]
Minimum line's intensity in Hough map to recognize a line.
int LocalPeakRadius [get, set]
Radius for searching local peak value.
short MaxIntensity [get]
Maximum found intensity in Hough map.
int LinesCount [get]
Found lines count.
Private Member Functions
void CollectLines ()
Private Attributes
int stepsPerDegree
int houghHeight
double thetaStep
double[] sinMap
double[] cosMap
short[,] houghMap
short maxMapIntensity = 0
int localPeakRadius = 4
short minLineIntensity = 10
ArrayList lines = new ArrayList()
Detailed Description
Hough line transformation.
The class implements Hough line transformation, which allows to detect straight lines in an image. Lines, which are found by the class, are provided in polar coordinates system - lines' distances from image's center and lines' slopes are provided. The pole of polar coordinates system is put into processing image's center and the polar axis is directed to the right from the pole. Lines' slope is measured in degrees and is actually represented by angle between polar axis and line's radius (normal going from pole to the line), which is measured in counter-clockwise direction.
<note>Found lines may have negative radius. This means, that the line resides in lower part of the polar coordinates system and its HoughLine.Theta value should be increased by 180 degrees and radius should be made positive. </note>
The class accepts binary images for processing, which are represented by 8 bpp grayscale images. All black pixels (0 pixel's value) are treated as background, but pixels with different value are treated as lines' pixels.
See also documentation to HoughLine class for additional information about Hough Lines.
Sample usage:
HoughLineTransformation lineTransform = new HoughLineTransformation();
// apply Hough line transofrm
lineTransform.ProcessImage(sourceImage);
Bitmap houghLineImage = lineTransform.ToBitmap();
// get lines using relative intensity
HoughLine[] lines = lineTransform.GetLinesByRelativeIntensity(0.5);
foreach (HoughLine line in lines)
{
    // ...
}
Initial image:
Hough line transformation image:
See also
HoughLine
Constructor & Destructor Documentation
HoughLineTransformation()
AForge.Imaging.HoughLineTransformation.HoughLineTransformation () inline
Initializes a new instance of the HoughLineTransformation class.
References AForge.Imaging.HoughLineTransformation.StepsPerDegree.
Member Function Documentation
ProcessImage() [1/6]
void AForge.Imaging.HoughLineTransformation.ProcessImage (Bitmap image) inline
Process an image building Hough map.
Parameters
image Source image to process.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Math.Geometry.Rectangle.
Referenced by HoughTransform.MainForm.openToolStripMenuItem_Click(), and AForge.Imaging.HoughLineTransformation.ProcessImage().
ProcessImage() [2/6]
void AForge.Imaging.HoughLineTransformation.ProcessImage (Bitmap image, Rectangle rect) inline
Process an image building Hough map.
Parameters
image Source image to process.
rect Image's rectangle to process.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Imaging.HoughLineTransformation.ProcessImage(), and AForge.Math.Geometry.Rectangle.
ProcessImage() [3/6]
void AForge.Imaging.HoughLineTransformation.ProcessImage (BitmapData imageData) inline
Process an image building Hough map.
Parameters
imageData Source image data to process.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Imaging.HoughLineTransformation.ProcessImage(), and AForge.Math.Geometry.Rectangle.
ProcessImage() [4/6]
void AForge.Imaging.HoughLineTransformation.ProcessImage (BitmapData imageData, Rectangle rect) inline
Process an image building Hough map.
Parameters
imageData Source image data to process.
rect Image's rectangle to process.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Imaging.HoughLineTransformation.ProcessImage().
ProcessImage() [5/6]
void AForge.Imaging.HoughLineTransformation.ProcessImage (UnmanagedImage image) inline
Process an image building Hough map.
Parameters
image Source unmanaged image to process.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.HoughLineTransformation.ProcessImage(), AForge.Math.Geometry.Rectangle, and AForge.Imaging.UnmanagedImage.Width.
ProcessImage() [6/6]
void AForge.Imaging.HoughLineTransformation.ProcessImage (UnmanagedImage image, Rectangle rect) inline
Process an image building Hough map.
Parameters
image Source unmanaged image to process.
rect Image's rectangle to process.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Imaging.HoughLineTransformation.CollectLines(), AForge.Imaging.HoughLineTransformation.cosMap, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.HoughLineTransformation.houghHeight, AForge.Imaging.HoughLineTransformation.houghMap, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.HoughLineTransformation.maxMapIntensity, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Math.Geometry.Rectangle, AForge.Imaging.HoughLineTransformation.sinMap, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
ToBitmap()
Bitmap AForge.Imaging.HoughLineTransformation.ToBitmap () inline
Convert Hough map to bitmap.
Returns
Returns 8 bppp grayscale bitmap, which shows Hough map.
Exceptions
ApplicationException Hough transformation was not yet done by calling ProcessImage() method.
References AForge.Imaging.Image.CreateGrayscaleImage(), AForge.Imaging.HoughLineTransformation.houghMap, AForge.Imaging.HoughLineTransformation.maxMapIntensity, and AForge.Math.Geometry.Rectangle.
Referenced by HoughTransform.MainForm.openToolStripMenuItem_Click().
GetMostIntensiveLines()
HoughLine [] AForge.Imaging.HoughLineTransformation.GetMostIntensiveLines (int count) inline
Get specified amount of lines with highest intensity.
Parameters
count Amount of lines to get.
Returns
Returns array of most intesive lines. If there are no lines detected, the returned array has zero length.
References AForge.Imaging.HoughLineTransformation.lines.
Referenced by AForge.Imaging.HoughLineTransformation.GetLinesByRelativeIntensity().
GetLinesByRelativeIntensity()
HoughLine [] AForge.Imaging.HoughLineTransformation.GetLinesByRelativeIntensity (double minRelativeIntensity) inline
Get lines with relative intensity higher then specified value.
Parameters
minRelativeIntensity Minimum relative intesity of lines.
Returns
Returns array of lines. If there are no lines detected, the returned array has zero length.
References AForge.Imaging.HoughLineTransformation.GetMostIntensiveLines(), and AForge.Imaging.HoughLineTransformation.lines.
Referenced by HoughTransform.MainForm.openToolStripMenuItem_Click().
CollectLines()
void AForge.Imaging.HoughLineTransformation.CollectLines () inline private
References AForge.Imaging.HoughLineTransformation.houghMap, AForge.Imaging.HoughLineTransformation.lines, AForge.Imaging.HoughLineTransformation.localPeakRadius, AForge.Imaging.HoughLineTransformation.maxMapIntensity, AForge.Imaging.HoughLineTransformation.minLineIntensity, and AForge.Imaging.HoughLineTransformation.stepsPerDegree.
Referenced by AForge.Imaging.HoughLineTransformation.ProcessImage().
Member Data Documentation
stepsPerDegree
int AForge.Imaging.HoughLineTransformation.stepsPerDegree private
Referenced by AForge.Imaging.HoughLineTransformation.CollectLines().
houghHeight
int AForge.Imaging.HoughLineTransformation.houghHeight private
Referenced by AForge.Imaging.HoughLineTransformation.ProcessImage().
thetaStep
double AForge.Imaging.HoughLineTransformation.thetaStep private
sinMap
double [] AForge.Imaging.HoughLineTransformation.sinMap private
Referenced by AForge.Imaging.HoughLineTransformation.ProcessImage().
cosMap
double [] AForge.Imaging.HoughLineTransformation.cosMap private
Referenced by AForge.Imaging.HoughLineTransformation.ProcessImage().
houghMap
short [,] AForge.Imaging.HoughLineTransformation.houghMap private
Referenced by AForge.Imaging.HoughLineTransformation.CollectLines(), AForge.Imaging.HoughLineTransformation.ProcessImage(), and AForge.Imaging.HoughLineTransformation.ToBitmap().
maxMapIntensity
short AForge.Imaging.HoughLineTransformation.maxMapIntensity = 0 private
Referenced by AForge.Imaging.HoughLineTransformation.CollectLines(), AForge.Imaging.HoughLineTransformation.ProcessImage(), and AForge.Imaging.HoughLineTransformation.ToBitmap().
localPeakRadius
int AForge.Imaging.HoughLineTransformation.localPeakRadius = 4 private
Referenced by AForge.Imaging.HoughLineTransformation.CollectLines().
minLineIntensity
short AForge.Imaging.HoughLineTransformation.minLineIntensity = 10 private
Referenced by AForge.Imaging.HoughLineTransformation.CollectLines().
lines
ArrayList AForge.Imaging.HoughLineTransformation.lines = new ArrayList() private
Referenced by AForge.Imaging.HoughLineTransformation.CollectLines(), AForge.Imaging.HoughLineTransformation.GetLinesByRelativeIntensity(), and AForge.Imaging.HoughLineTransformation.GetMostIntensiveLines().
Property Documentation
StepsPerDegree
int AForge.Imaging.HoughLineTransformation.StepsPerDegree get set
Steps per degree.
The value defines quality of Hough line transformation and its ability to detect lines' slope precisely.
Default value is set to 1. Minimum value is 1. Maximum value is 10.
Referenced by AForge.Imaging.HoughLineTransformation.HoughLineTransformation().
MinLineIntensity
short AForge.Imaging.HoughLineTransformation.MinLineIntensity get set
Minimum line's intensity in Hough map to recognize a line.
The value sets minimum intensity level for a line. If a value in Hough map has lower intensity, then it is not treated as a line.
Default value is set to 10.
Referenced by HoughTransform.MainForm.MainForm().
LocalPeakRadius
int AForge.Imaging.HoughLineTransformation.LocalPeakRadius get set
Radius for searching local peak value.
The value determines radius around a map's value, which is analyzed to determine if the map's value is a local maximum in specified area.
Default value is set to 4. Minimum value is 1. Maximum value is 10.
MaxIntensity
short AForge.Imaging.HoughLineTransformation.MaxIntensity get
Maximum found intensity in Hough map.
The property provides maximum found line's intensity.
Referenced by HoughTransform.MainForm.openToolStripMenuItem_Click().
LinesCount
int AForge.Imaging.HoughLineTransformation.LinesCount get
Found lines count.
The property provides total number of found lines, which intensity is higher (or equal to), than the requested minimum intensity.
Referenced by HoughTransform.MainForm.openToolStripMenuItem_Click().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/HoughLineTransformation.cs