Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLASR Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLASR Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLASR (LSAME lsame, XERBLA xerbla)
DLASR ()
void Run (string SIDE, string PIVOT, string DIRECT, int M, int N, double[] C, int offset_c, double[] S, int offset_s, ref double[] A, int offset_a, int LDA)
Private Attributes
LSAME _lsame
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLASR applies a sequence of plane rotations to a real matrix A, from either the left or the right.
When SIDE = 'L', the transformation takes the form
A := P*A
and when SIDE = 'R', the transformation takes the form
A := A*P**T
where P is an orthogonal matrix consisting of a sequence of z plane rotations, with z = M when SIDE = 'L' and z = N when SIDE = 'R', and P**T is the transpose of P.
When DIRECT = 'F' (Forward sequence), then
P = P(z-1) * ... * P(2) * P(1)
and when DIRECT = 'B' (Backward sequence), then
P = P(1) * P(2) * ... * P(z-1)
where P(k) is a plane rotation matrix defined by the 2-by-2 rotation
R(k) = (c(k) s(k)) = (-s(k) c(k)).
When PIVOT = 'V' (Variable pivot), the rotation is performed for the plane (k,k+1), i.e., P(k) has the form
P(k) = (1) (...) (1) (c(k) s(k)) (-s(k) c(k)) (1) (...) (1)
where R(k) appears as a rank-2 modification to the identity matrix in rows and columns k and k+1.
When PIVOT = 'T' (Top pivot), the rotation is performed for the plane (1,k+1), so P(k) has the form
P(k) = (c(k) s(k)) (1) (...) (1) (-s(k) c(k)) (1) (...) (1)
where R(k) appears in rows and columns 1 and k+1.
Similarly, when PIVOT = 'B' (Bottom pivot), the rotation is performed for the plane (k,z), giving P(k) the form
P(k) = (1) (...) (1) (c(k) s(k)) (1) (...) (1) (-s(k) c(k))
where R(k) appears in rows and columns k and z. The rotations are performed without ever forming P(k) explicitly.
/summary>
Constructor & Destructor Documentation
DLASR() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLASR.DLASR (LSAME lsame, XERBLA xerbla) inline
DLASR() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLASR.DLASR () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLASR.Run (string SIDE, string PIVOT, string DIRECT, int M, int N, double[] C, int offset_c, double[] S, int offset_s, ref double[] A, int offset_a, int LDA) inline
Purpose
DLASR applies a sequence of plane rotations to a real matrix A, from either the left or the right.
When SIDE = 'L', the transformation takes the form
A := P*A
and when SIDE = 'R', the transformation takes the form
A := A*P**T
where P is an orthogonal matrix consisting of a sequence of z plane rotations, with z = M when SIDE = 'L' and z = N when SIDE = 'R', and P**T is the transpose of P.
When DIRECT = 'F' (Forward sequence), then
P = P(z-1) * ... * P(2) * P(1)
and when DIRECT = 'B' (Backward sequence), then
P = P(1) * P(2) * ... * P(z-1)
where P(k) is a plane rotation matrix defined by the 2-by-2 rotation
R(k) = (c(k) s(k)) = (-s(k) c(k)).
When PIVOT = 'V' (Variable pivot), the rotation is performed for the plane (k,k+1), i.e., P(k) has the form
P(k) = (1) (...) (1) (c(k) s(k)) (-s(k) c(k)) (1) (...) (1)
where R(k) appears as a rank-2 modification to the identity matrix in rows and columns k and k+1.
When PIVOT = 'T' (Top pivot), the rotation is performed for the plane (1,k+1), so P(k) has the form
P(k) = (c(k) s(k)) (1) (...) (1) (-s(k) c(k)) (1) (...) (1)
where R(k) appears in rows and columns 1 and k+1.
Similarly, when PIVOT = 'B' (Bottom pivot), the rotation is performed for the plane (k,z), giving P(k) the form
P(k) = (1) (...) (1) (c(k) s(k)) (1) (...) (1) (-s(k) c(k))
where R(k) appears in rows and columns k and z. The rotations are performed without ever forming P(k) explicitly.
/summary>
Parameters
SIDE (input) CHARACTER*1 Specifies whether the plane rotation matrix P is applied to A on the left or the right. = 'L': Left, compute A := P*A = 'R': Right, compute A:= A*P**T /param>
Parameters
PIVOT (input) CHARACTER*1 Specifies the plane for which P(k) is a plane rotation matrix. = 'V': Variable pivot, the plane (k,k+1) = 'T': Top pivot, the plane (1,k+1) = 'B': Bottom pivot, the plane (k,z) /param>
Parameters
DIRECT (input) CHARACTER*1 Specifies whether P is a forward or backward sequence of plane rotations. = 'F': Forward, P = P(z-1)*...*P(2)*P(1) = 'B': Backward, P = P(1)*P(2)*...*P(z-1) /param>
Parameters
M (input) INTEGER The number of rows of the matrix A. If m .LE. 1, an immediate return is effected. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. If n .LE. 1, an immediate return is effected. /param>
Parameters
C (input) DOUBLE PRECISION array, dimension (M-1) if SIDE = 'L' (N-1) if SIDE = 'R' The cosines c(k) of the plane rotations. /param>
Parameters
S (input) DOUBLE PRECISION array, dimension (M-1) if SIDE = 'L' (N-1) if SIDE = 'R' The sines s(k) of the plane rotations. The 2-by-2 plane rotation part of the matrix P(k), R(k), has the form R(k) = (c(k) s(k)) (-s(k) c(k)). /param>
Parameters
A := P*A /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
References DotNumerics.LinearAlgebra.CSLapack.DLASR.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLASR.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASDQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run(), and DotNumerics.LinearAlgebra.CSLapack.DBDSDC.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLASR._lsame private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLASR._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLASR.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASR.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLASR.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASR.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlasr.cs