Doc: IGLib EXTENDED: CShell.Modules.Repl.Controls.CSRepl Class Reference
CShell.Modules.Repl.Controls.CSRepl Class Reference
Interaction logic for CommandLineControl.xaml
Public Member Functions
CSRepl ()
void SuppressWarning (string warningCode)
void ShowWarning (string warningCode)
void Clear ()
void ClearLine ()
void WritePrompt ()
void Write (string text)
void Write (string text, TextType textType)
void WriteLine ()
void WriteLine (string text)
void WriteLine (string text, TextType textType)
Color GetColor (TextType textType)
Properties
ScriptingEngine ScriptingEngine [get, set]
bool IsEvaluating [get]
string Font [get, set]
new double FontSize [get, set]
Color BackgroundColor [get, set]
Color OutputColor [get, set]
Color WarningColor [get, set]
Color ErrorColor [get, set]
Color ReplColor [get, set]
IEnumerable< string > SuppressedWarnings [get]
bool ShowConsoleOutput [get, set]
TextDocument Doc [get]
int Offset [get]
int PromptOffset [get]
Properties inherited from CShell.Framework.Services.IRepl
bool IsEvaluating [get]
IEnumerable< string > SuppressedWarnings [get]
bool ShowConsoleOutput [get, set]
string Font [get, set]
double FontSize [get, set]
Color BackgroundColor [get, set]
Color OutputColor [get, set]
Color WarningColor [get, set]
Color ErrorColor [get, set]
Color ReplColor [get, set]
Private Member Functions
IEnumerable< string > FilterWarnings (IEnumerable< string > warnings)
string GetWarningCode (string warning)
void CommandEntered (string command)
void ShowPreviousCommand ()
void ShowNextCommand ()
void ScriptingEngineOnEvaluateStarted (object sender, EvaluateStartedEventArgs evaluateStartedEventArgs)
void ScriptingEngineOnEvaluateCompleted (object sender, EvaluateCompletedEventArgs evaluateCompletedEventArgs)
void ScriptingEngineOnConsoleOutput (object sender, ConsoleEventArgs eventArgs)
string ToPrettyString (object o)
void TextAreaOnPreviewKeyDown (object sender, KeyEventArgs keyEventArgs)
void MoveCaretToEnd ()
bool IsCaretAtCurrentLine ()
bool IsCaretAfterPrompt ()
bool IsCaretAtPrompt ()
bool IsCaretAtWritablePosition ()
bool IsSelectionBeforePrompOffset ()
void SelectCurrentLineOnly ()
void SelectCurrentLine ()
string GetCurrentLineText ()
Private Attributes
CSReplTextEditor textEditor
ScriptingEngine scriptingEngine
readonly CommandHistory commandHistory
bool executingInternalCommand
string partialCommand = ""
int evaluationsRunning
IVisualLineTransformer[] initialTransformers
CompletionWindow completionWindow
OverloadInsightWindow insightWindow
readonly HashSet< string > suppressedWarnings = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
string promptComplete = " > "
string promptIncomplete = " "
string prompt = " > "
Detailed Description
Interaction logic for CommandLineControl.xaml
Constructor & Destructor Documentation
CSRepl()
CShell.Modules.Repl.Controls.CSRepl.CSRepl () inline
References CShell.Modules.Repl.Controls.CSRepl.Clear(), CShell.Modules.Repl.Controls.CSRepl.commandHistory, CShell.Modules.Repl.Controls.CSRepl.ErrorColor, CShellCore.CodeCompletion.CodeTextEditor.FileName, CShell.Modules.Repl.Controls.CSRepl.initialTransformers, CShell.Modules.Repl.Controls.CSRepl.OutputColor, CShell.Modules.Repl.Controls.CSReplTextEditor.Repl, CShell.Modules.Repl.Controls.CSRepl.ReplColor, CShell.Modules.Repl.Controls.CSRepl.ShowConsoleOutput, CShell.Modules.Repl.Controls.CSRepl.SuppressWarning(), CShell.Modules.Repl.Controls.CSRepl.TextAreaOnPreviewKeyDown(), CShell.Modules.Repl.Controls.CSRepl.textEditor, and CShell.Modules.Repl.Controls.CSRepl.WarningColor.
Member Function Documentation
SuppressWarning()
void CShell.Modules.Repl.Controls.CSRepl.SuppressWarning (string warningCode) inline
Implements CShell.Framework.Services.IRepl.
References CShell.Modules.Repl.Controls.CSRepl.suppressedWarnings.
Referenced by CShell.Modules.Repl.Controls.CSRepl.CSRepl().
ShowWarning()
void CShell.Modules.Repl.Controls.CSRepl.ShowWarning (string warningCode) inline
Implements CShell.Framework.Services.IRepl.
References CShell.Modules.Repl.Controls.CSRepl.suppressedWarnings.
FilterWarnings()
IEnumerable<string> CShell.Modules.Repl.Controls.CSRepl.FilterWarnings (IEnumerable< string > warnings) inline private
References CShell.Modules.Repl.Controls.CSRepl.GetWarningCode(), and CShell.Modules.Repl.Controls.CSRepl.suppressedWarnings.
GetWarningCode()
string CShell.Modules.Repl.Controls.CSRepl.GetWarningCode (string warning) inline private
Referenced by CShell.Modules.Repl.Controls.CSRepl.FilterWarnings().
Clear()
void CShell.Modules.Repl.Controls.CSRepl.Clear () inline
Implements CShell.Framework.Services.IRepl.
References CShell.Modules.Repl.Controls.CSRepl.initialTransformers, CShell.Modules.Repl.Controls.CSRepl.scriptingEngine, CShell.Modules.Repl.Controls.CSRepl.textEditor, CShell.Modules.Repl.Controls.CSRepl.WriteLine(), and CShell.Modules.Repl.Controls.CSRepl.WritePrompt().
Referenced by CShell.Modules.Repl.Controls.CSRepl.CSRepl().
CommandEntered()
void CShell.Modules.Repl.Controls.CSRepl.CommandEntered (string command) inline private
References CShell.Modules.Repl.Controls.CSRepl.commandHistory, CShell.ScriptingEngine.EvaluateAsync(), CShell.Modules.Repl.Controls.CSRepl.evaluationsRunning, CShell.Modules.Repl.Controls.CSRepl.executingInternalCommand, CShell.Modules.Repl.Controls.CSRepl.partialCommand, CShell.Modules.Repl.Controls.CSRepl.scriptingEngine, and CShell.Modules.Repl.Controls.CSRepl.WriteLine().
Referenced by CShell.Modules.Repl.Controls.CSRepl.TextAreaOnPreviewKeyDown().
ShowPreviousCommand()
void CShell.Modules.Repl.Controls.CSRepl.ShowPreviousCommand () inline private
References CShell.Modules.Repl.Controls.CSRepl.ClearLine(), CShell.Modules.Repl.Controls.CSRepl.commandHistory, and CShell.Modules.Repl.Controls.CSRepl.Write().
Referenced by CShell.Modules.Repl.Controls.CSRepl.TextAreaOnPreviewKeyDown().
ShowNextCommand()
void CShell.Modules.Repl.Controls.CSRepl.ShowNextCommand () inline private
References CShell.Modules.Repl.Controls.CSRepl.ClearLine(), CShell.Modules.Repl.Controls.CSRepl.commandHistory, and CShell.Modules.Repl.Controls.CSRepl.Write().
Referenced by CShell.Modules.Repl.Controls.CSRepl.TextAreaOnPreviewKeyDown().
ScriptingEngineOnEvaluateStarted()
void CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnEvaluateStarted (object sender, EvaluateStartedEventArgs evaluateStartedEventArgs) inline private
References CShell.Modules.Repl.Controls.CSRepl.ClearLine(), CShell.Modules.Repl.Controls.CSRepl.evaluationsRunning, CShell.Modules.Repl.Controls.CSRepl.executingInternalCommand, CShell.Modules.Repl.Controls.CSRepl.IsEvaluating, CShell.Framework.Services.Execute.OnUIThread(), CShell.Code.EvaluateStartedEventArgs.SourceFile, and CShell.Modules.Repl.Controls.CSRepl.WriteLine().
ScriptingEngineOnEvaluateCompleted()
void CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnEvaluateCompleted (object sender, EvaluateCompletedEventArgs evaluateCompletedEventArgs) inline private
References CShell.Code.ScriptingInteractiveBase.ClearRequested, CShell.Modules.Repl.Controls.CSRepl.evaluationsRunning, CShell.Modules.Repl.Controls.CSRepl.executingInternalCommand, CShell.Modules.Repl.Controls.CSRepl.IsEvaluating, CShell.Framework.Services.Execute.OnUIThread(), CShell.Code.EvaluateCompletedEventArgs.Resuslt, CShell.Modules.Repl.Controls.CSRepl.ToPrettyString(), CShell.Modules.Repl.Controls.CSRepl.WriteLine(), and CShell.Modules.Repl.Controls.CSRepl.WritePrompt().
ScriptingEngineOnConsoleOutput()
void CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnConsoleOutput (object sender, ConsoleEventArgs eventArgs) inline private
References CShell.Framework.Services.Execute.OnUIThread(), CShell.Modules.Repl.Controls.CSRepl.ShowConsoleOutput, CShell.Code.ConsoleEventArgs.Text, and CShell.Modules.Repl.Controls.CSRepl.Write().
ToPrettyString()
string CShell.Modules.Repl.Controls.CSRepl.ToPrettyString (object o) inline private
Referenced by CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnEvaluateCompleted().
TextAreaOnPreviewKeyDown()
void CShell.Modules.Repl.Controls.CSRepl.TextAreaOnPreviewKeyDown (object sender, KeyEventArgs keyEventArgs) inline private
References CShell.Modules.Repl.Controls.CSRepl.CommandEntered(), CShell.Modules.Repl.Controls.CSRepl.GetCurrentLineText(), CShell.ScriptingEngine.Interrupt(), CShell.Modules.Repl.Controls.CSRepl.IsCaretAtPrompt(), CShell.Modules.Repl.Controls.CSRepl.IsCaretAtWritablePosition(), CShell.Modules.Repl.Controls.CSRepl.IsEvaluating, CShell.Modules.Repl.Controls.CSRepl.IsSelectionBeforePrompOffset(), CShell.Modules.Repl.Controls.CSRepl.MoveCaretToEnd(), CShell.Modules.Repl.Controls.CSRepl.SelectCurrentLine(), CShell.Modules.Repl.Controls.CSRepl.SelectCurrentLineOnly(), CShell.Modules.Repl.Controls.CSRepl.ShowNextCommand(), CShell.Modules.Repl.Controls.CSRepl.ShowPreviousCommand(), CShell.Modules.Repl.Controls.CSRepl.textEditor, and CShell.Modules.Repl.Controls.CSRepl.WriteLine().
Referenced by CShell.Modules.Repl.Controls.CSRepl.CSRepl().
MoveCaretToEnd()
void CShell.Modules.Repl.Controls.CSRepl.MoveCaretToEnd () inline private
References CShell.Modules.Repl.Controls.CSRepl.Doc, and CShell.Modules.Repl.Controls.CSRepl.textEditor.
Referenced by CShell.Modules.Repl.Controls.CSRepl.ClearLine(), CShell.Modules.Repl.Controls.CSRepl.TextAreaOnPreviewKeyDown(), and CShell.Modules.Repl.Controls.CSRepl.Write().
IsCaretAtCurrentLine()
bool CShell.Modules.Repl.Controls.CSRepl.IsCaretAtCurrentLine () inline private
References CShell.Modules.Repl.Controls.CSRepl.Doc, and CShell.Modules.Repl.Controls.CSRepl.Offset.
Referenced by CShell.Modules.Repl.Controls.CSRepl.IsCaretAtWritablePosition().
IsCaretAfterPrompt()
bool CShell.Modules.Repl.Controls.CSRepl.IsCaretAfterPrompt () inline private
References CShell.Modules.Repl.Controls.CSRepl.Doc, CShell.Modules.Repl.Controls.CSRepl.Offset, and CShell.Modules.Repl.Controls.CSRepl.prompt.
Referenced by CShell.Modules.Repl.Controls.CSRepl.IsCaretAtWritablePosition().
IsCaretAtPrompt()
bool CShell.Modules.Repl.Controls.CSRepl.IsCaretAtPrompt () inline private
References CShell.Modules.Repl.Controls.CSRepl.Doc, CShell.Modules.Repl.Controls.CSRepl.Offset, and CShell.Modules.Repl.Controls.CSRepl.prompt.
Referenced by CShell.Modules.Repl.Controls.CSRepl.TextAreaOnPreviewKeyDown().
IsCaretAtWritablePosition()
bool CShell.Modules.Repl.Controls.CSRepl.IsCaretAtWritablePosition () inline private
References CShell.Modules.Repl.Controls.CSRepl.IsCaretAfterPrompt(), and CShell.Modules.Repl.Controls.CSRepl.IsCaretAtCurrentLine().
Referenced by CShell.Modules.Repl.Controls.CSRepl.TextAreaOnPreviewKeyDown().
IsSelectionBeforePrompOffset()
bool CShell.Modules.Repl.Controls.CSRepl.IsSelectionBeforePrompOffset () inline private
References CShell.Modules.Repl.Controls.CSRepl.PromptOffset, and CShell.Modules.Repl.Controls.CSRepl.textEditor.
Referenced by CShell.Modules.Repl.Controls.CSRepl.TextAreaOnPreviewKeyDown().
SelectCurrentLineOnly()
void CShell.Modules.Repl.Controls.CSRepl.SelectCurrentLineOnly () inline private
References CShell.Modules.Repl.Controls.CSRepl.PromptOffset, and CShell.Modules.Repl.Controls.CSRepl.textEditor.
Referenced by CShell.Modules.Repl.Controls.CSRepl.TextAreaOnPreviewKeyDown().
SelectCurrentLine()
void CShell.Modules.Repl.Controls.CSRepl.SelectCurrentLine () inline private
References CShell.Modules.Repl.Controls.CSRepl.Doc, CShell.Modules.Repl.Controls.CSRepl.PromptOffset, and CShell.Modules.Repl.Controls.CSRepl.textEditor.
Referenced by CShell.Modules.Repl.Controls.CSRepl.TextAreaOnPreviewKeyDown().
GetCurrentLineText()
string CShell.Modules.Repl.Controls.CSRepl.GetCurrentLineText () inline private
References CShell.Modules.Repl.Controls.CSRepl.Doc, and CShell.Modules.Repl.Controls.CSRepl.prompt.
Referenced by CShell.Modules.Repl.Controls.CSRepl.TextAreaOnPreviewKeyDown().
ClearLine()
void CShell.Modules.Repl.Controls.CSRepl.ClearLine () inline
References CShell.Modules.Repl.Controls.CSRepl.Doc, CShell.Modules.Repl.Controls.CSRepl.MoveCaretToEnd(), and CShell.Modules.Repl.Controls.CSRepl.prompt.
Referenced by CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnEvaluateStarted(), CShell.Modules.Repl.Controls.CSRepl.ShowNextCommand(), and CShell.Modules.Repl.Controls.CSRepl.ShowPreviousCommand().
WritePrompt()
void CShell.Modules.Repl.Controls.CSRepl.WritePrompt () inline
References CShell.Modules.Repl.Controls.CSRepl.prompt, CShell.Modules.Repl.Controls.CSRepl.textEditor, CShell.Modules.Repl.Controls.CSRepl.Write(), and CShell.Modules.Repl.Controls.CSRepl.WriteLine().
Referenced by CShell.Modules.Repl.Controls.CSRepl.Clear(), and CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnEvaluateCompleted().
Write() [1/2]
void CShell.Modules.Repl.Controls.CSRepl.Write (string text) inline
Referenced by CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnConsoleOutput(), CShell.Modules.Repl.Controls.CSRepl.ShowNextCommand(), CShell.Modules.Repl.Controls.CSRepl.ShowPreviousCommand(), CShell.Modules.Repl.Controls.CSRepl.WriteLine(), and CShell.Modules.Repl.Controls.CSRepl.WritePrompt().
Write() [2/2]
void CShell.Modules.Repl.Controls.CSRepl.Write (string text, TextType textType) inline
References CShell.Modules.Repl.Controls.CSRepl.Doc, CShell.Modules.Repl.Controls.CSRepl.GetColor(), CShell.Modules.Repl.Controls.CSRepl.MoveCaretToEnd(), and CShell.Modules.Repl.Controls.CSRepl.textEditor.
WriteLine() [1/3]
void CShell.Modules.Repl.Controls.CSRepl.WriteLine () inline
References CShell.Modules.Repl.Controls.CSRepl.Write().
Referenced by CShell.Modules.Repl.Controls.CSRepl.Clear(), CShell.Modules.Repl.Controls.CSRepl.CommandEntered(), CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnEvaluateCompleted(), CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnEvaluateStarted(), CShell.Modules.Repl.Controls.CSRepl.TextAreaOnPreviewKeyDown(), and CShell.Modules.Repl.Controls.CSRepl.WritePrompt().
WriteLine() [2/3]
void CShell.Modules.Repl.Controls.CSRepl.WriteLine (string text) inline
References CShell.Modules.Repl.Controls.CSRepl.Write().
WriteLine() [3/3]
void CShell.Modules.Repl.Controls.CSRepl.WriteLine (string text, TextType textType) inline
References CShell.Modules.Repl.Controls.CSRepl.Write().
GetColor()
Color CShell.Modules.Repl.Controls.CSRepl.GetColor (TextType textType) inline
References CShell.Modules.Repl.Controls.CSRepl.ErrorColor, CShell.Modules.Repl.Controls.CSRepl.OutputColor, CShell.Modules.Repl.Controls.CSRepl.ReplColor, and CShell.Modules.Repl.Controls.CSRepl.WarningColor.
Referenced by CShell.Modules.Repl.Controls.CSRepl.Write().
Member Data Documentation
textEditor
CSReplTextEditor CShell.Modules.Repl.Controls.CSRepl.textEditor private
Referenced by CShell.Modules.Repl.Controls.CSRepl.Clear(), CShell.Modules.Repl.Controls.CSRepl.CSRepl(), CShell.Modules.Repl.Controls.CSRepl.IsSelectionBeforePrompOffset(), CShell.Modules.Repl.Controls.CSRepl.MoveCaretToEnd(), CShell.Modules.Repl.Controls.CSRepl.SelectCurrentLine(), CShell.Modules.Repl.Controls.CSRepl.SelectCurrentLineOnly(), CShell.Modules.Repl.Controls.CSRepl.TextAreaOnPreviewKeyDown(), CShell.Modules.Repl.Controls.CSRepl.Write(), and CShell.Modules.Repl.Controls.CSRepl.WritePrompt().
scriptingEngine
ScriptingEngine CShell.Modules.Repl.Controls.CSRepl.scriptingEngine private
Referenced by CShell.Modules.Repl.Controls.CSRepl.Clear(), and CShell.Modules.Repl.Controls.CSRepl.CommandEntered().
commandHistory
readonly CommandHistory CShell.Modules.Repl.Controls.CSRepl.commandHistory private
Referenced by CShell.Modules.Repl.Controls.CSRepl.CommandEntered(), CShell.Modules.Repl.Controls.CSRepl.CSRepl(), CShell.Modules.Repl.Controls.CSRepl.ShowNextCommand(), and CShell.Modules.Repl.Controls.CSRepl.ShowPreviousCommand().
executingInternalCommand
bool CShell.Modules.Repl.Controls.CSRepl.executingInternalCommand private
Referenced by CShell.Modules.Repl.Controls.CSRepl.CommandEntered(), CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnEvaluateCompleted(), and CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnEvaluateStarted().
partialCommand
string CShell.Modules.Repl.Controls.CSRepl.partialCommand = "" private
Referenced by CShell.Modules.Repl.Controls.CSRepl.CommandEntered().
evaluationsRunning
int CShell.Modules.Repl.Controls.CSRepl.evaluationsRunning private
Referenced by CShell.Modules.Repl.Controls.CSRepl.CommandEntered(), CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnEvaluateCompleted(), and CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnEvaluateStarted().
initialTransformers
IVisualLineTransformer [] CShell.Modules.Repl.Controls.CSRepl.initialTransformers private
Referenced by CShell.Modules.Repl.Controls.CSRepl.Clear(), and CShell.Modules.Repl.Controls.CSRepl.CSRepl().
completionWindow
CompletionWindow CShell.Modules.Repl.Controls.CSRepl.completionWindow private
insightWindow
OverloadInsightWindow CShell.Modules.Repl.Controls.CSRepl.insightWindow private
suppressedWarnings
readonly HashSet<string> CShell.Modules.Repl.Controls.CSRepl.suppressedWarnings = new HashSet<string>(StringComparer.OrdinalIgnoreCase) private
Referenced by CShell.Modules.Repl.Controls.CSRepl.FilterWarnings(), CShell.Modules.Repl.Controls.CSRepl.ShowWarning(), and CShell.Modules.Repl.Controls.CSRepl.SuppressWarning().
promptComplete
string CShell.Modules.Repl.Controls.CSRepl.promptComplete = " > " private
promptIncomplete
string CShell.Modules.Repl.Controls.CSRepl.promptIncomplete = " " private
prompt
string CShell.Modules.Repl.Controls.CSRepl.prompt = " > " private
Referenced by CShell.Modules.Repl.Controls.CSRepl.ClearLine(), CShell.Modules.Repl.Controls.CSRepl.GetCurrentLineText(), CShell.Modules.Repl.Controls.CSRepl.IsCaretAfterPrompt(), CShell.Modules.Repl.Controls.CSRepl.IsCaretAtPrompt(), and CShell.Modules.Repl.Controls.CSRepl.WritePrompt().
Property Documentation
ScriptingEngine
ScriptingEngine CShell.Modules.Repl.Controls.CSRepl.ScriptingEngine get set
IsEvaluating
bool CShell.Modules.Repl.Controls.CSRepl.IsEvaluating get
Referenced by CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnEvaluateCompleted(), CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnEvaluateStarted(), and CShell.Modules.Repl.Controls.CSRepl.TextAreaOnPreviewKeyDown().
Font
string CShell.Modules.Repl.Controls.CSRepl.Font get set
FontSize
new double CShell.Modules.Repl.Controls.CSRepl.FontSize get set
BackgroundColor
Color CShell.Modules.Repl.Controls.CSRepl.BackgroundColor get set
OutputColor
Color CShell.Modules.Repl.Controls.CSRepl.OutputColor get set
Referenced by CShell.Modules.Repl.Controls.CSRepl.CSRepl(), and CShell.Modules.Repl.Controls.CSRepl.GetColor().
WarningColor
Color CShell.Modules.Repl.Controls.CSRepl.WarningColor get set
Referenced by CShell.Modules.Repl.Controls.CSRepl.CSRepl(), and CShell.Modules.Repl.Controls.CSRepl.GetColor().
ErrorColor
Color CShell.Modules.Repl.Controls.CSRepl.ErrorColor get set
Referenced by CShell.Modules.Repl.Controls.CSRepl.CSRepl(), and CShell.Modules.Repl.Controls.CSRepl.GetColor().
ReplColor
Color CShell.Modules.Repl.Controls.CSRepl.ReplColor get set
Referenced by CShell.Modules.Repl.Controls.CSRepl.CSRepl(), and CShell.Modules.Repl.Controls.CSRepl.GetColor().
SuppressedWarnings
IEnumerable<string> CShell.Modules.Repl.Controls.CSRepl.SuppressedWarnings get
ShowConsoleOutput
bool CShell.Modules.Repl.Controls.CSRepl.ShowConsoleOutput get set
Referenced by CShell.Modules.Repl.Controls.CSRepl.CSRepl(), and CShell.Modules.Repl.Controls.CSRepl.ScriptingEngineOnConsoleOutput().
Doc
TextDocument CShell.Modules.Repl.Controls.CSRepl.Doc get private
Referenced by CShell.Modules.Repl.Controls.CSRepl.ClearLine(), CShell.Modules.Repl.Controls.CSRepl.GetCurrentLineText(), CShell.Modules.Repl.Controls.CSRepl.IsCaretAfterPrompt(), CShell.Modules.Repl.Controls.CSRepl.IsCaretAtCurrentLine(), CShell.Modules.Repl.Controls.CSRepl.IsCaretAtPrompt(), CShell.Modules.Repl.Controls.CSRepl.MoveCaretToEnd(), CShell.Modules.Repl.Controls.CSRepl.SelectCurrentLine(), and CShell.Modules.Repl.Controls.CSRepl.Write().
Offset
int CShell.Modules.Repl.Controls.CSRepl.Offset get private
Referenced by CShell.Modules.Repl.Controls.CSRepl.IsCaretAfterPrompt(), CShell.Modules.Repl.Controls.CSRepl.IsCaretAtCurrentLine(), and CShell.Modules.Repl.Controls.CSRepl.IsCaretAtPrompt().
PromptOffset
int CShell.Modules.Repl.Controls.CSRepl.PromptOffset get private
Referenced by CShell.Modules.Repl.Controls.CSRepl.IsSelectionBeforePrompOffset(), CShell.Modules.Repl.Controls.CSRepl.SelectCurrentLine(), and CShell.Modules.Repl.Controls.CSRepl.SelectCurrentLineOnly().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Repl/Controls/CSRepl.xaml.cs