Doc: IGLib EXTENDED: NUnit.ConsoleRunner.ConsoleRunner Class Reference
NUnit.ConsoleRunner.ConsoleRunner Class Reference
ConsoleRunner provides the nunit3-console text-based user interface, running the tests and reporting the results.
Public Member Functions
ConsoleRunner (ITestEngine engine, ConsoleOptions options, ExtendedTextWriter writer)
int Execute ()
Executes tests according to the provided commandline options.
Static Public Member Functions
static TestPackage MakeTestPackage (ConsoleOptions options)
Static Public Attributes
static readonly int OK = 0
static readonly int INVALID_ARG = -1
static readonly int INVALID_ASSEMBLY = -2
static readonly int FIXTURE_NOT_FOUND = -3
static readonly int UNEXPECTED_ERROR = -100
Private Member Functions
void DisplayTestFiles ()
int ExploreTests (TestPackage package, TestFilter filter)
int RunTests (TestPackage package, TestFilter filter)
void DisplayRuntimeEnvironment (ExtendedTextWriter OutWriter)
static int uname (IntPtr buf)
void DisplayTestFilters ()
void RedirectErrorOutputAsRequested ()
ExtendedTextWriter CreateOutputWriter ()
void RestoreErrorOutput ()
IResultWriter GetResultWriter (OutputSpecification spec)
TestFilter CreateTestFilter (ConsoleOptions options)
Static Private Member Functions
static string GetOSVersion ()
Private Attributes
ITestEngine _engine
ConsoleOptions _options
IResultService _resultService
ITestFilterService _filterService
ExtendedTextWriter _outWriter
TextWriter _errorWriter = Console.Error
string _workDirectory
Detailed Description
ConsoleRunner provides the nunit3-console text-based user interface, running the tests and reporting the results.
Constructor & Destructor Documentation
ConsoleRunner()
NUnit.ConsoleRunner.ConsoleRunner.ConsoleRunner (ITestEngine engine, ConsoleOptions options, ExtendedTextWriter writer) inline
References NUnit.ConsoleRunner.ConsoleRunner._engine, NUnit.ConsoleRunner.ConsoleRunner._filterService, NUnit.ConsoleRunner.ConsoleRunner._options, NUnit.ConsoleRunner.ConsoleRunner._outWriter, NUnit.ConsoleRunner.ConsoleRunner._resultService, NUnit.ConsoleRunner.ConsoleRunner._workDirectory, NUnit.Engine.IServiceLocator.GetService(), NUnit.Engine.ITestEngine.Services, and NUnit.Common.CommandLineOptions.WorkDirectory.
Member Function Documentation
Execute()
int NUnit.ConsoleRunner.ConsoleRunner.Execute () inline
Executes tests according to the provided commandline options.
Returns
References NUnit.ConsoleRunner.ConsoleRunner._options, NUnit.ConsoleRunner.ConsoleRunner._outWriter, NUnit.ConsoleRunner.ConsoleRunner.CreateTestFilter(), NUnit.ConsoleRunner.ConsoleRunner.DisplayRuntimeEnvironment(), NUnit.ConsoleRunner.ConsoleRunner.DisplayTestFiles(), NUnit.ConsoleRunner.ConsoleRunner.DisplayTestFilters(), NUnit.Common.CommandLineOptions.Explore, NUnit.ConsoleRunner.ConsoleRunner.ExploreTests(), and NUnit.ConsoleRunner.ConsoleRunner.RunTests().
Referenced by NUnit.ConsoleRunner.Program.Main().
DisplayTestFiles()
void NUnit.ConsoleRunner.ConsoleRunner.DisplayTestFiles () inline private
References NUnit.ConsoleRunner.ConsoleRunner._options, NUnit.ConsoleRunner.ConsoleRunner._outWriter, NUnit.Common.CommandLineOptions.InputFiles, and NUnit.Common.ExtendedTextWriter.WriteLine().
Referenced by NUnit.ConsoleRunner.ConsoleRunner.Execute().
ExploreTests()
int NUnit.ConsoleRunner.ConsoleRunner.ExploreTests (TestPackage package, TestFilter filter) inline private
References NUnit.ConsoleRunner.ConsoleRunner._engine, NUnit.ConsoleRunner.ConsoleRunner._options, NUnit.ConsoleRunner.ConsoleRunner._outWriter, NUnit.ConsoleRunner.ConsoleRunner._resultService, NUnit.Common.CommandLineOptions.ExploreOutputSpecifications, NUnit.Common.OutputSpecification.Format, NUnit.Engine.IResultService.GetResultWriter(), NUnit.Engine.ITestEngine.GetRunner(), NUnit.Common.OutputSpecification.OutputPath, NUnit.Common.OutputSpecification.Transform, NUnit.Common.ExtendedTextWriter.WriteLine(), and NUnit.Engine.Extensibility.IResultWriter.WriteResultFile().
Referenced by NUnit.ConsoleRunner.ConsoleRunner.Execute().
RunTests()
int NUnit.ConsoleRunner.ConsoleRunner.RunTests (TestPackage package, TestFilter filter) inline private
References NUnit.ConsoleRunner.ConsoleRunner._engine, NUnit.ConsoleRunner.ConsoleRunner._options, NUnit.ConsoleRunner.ConsoleRunner._outWriter, NUnit.ConsoleRunner.ConsoleRunner._workDirectory, NUnit.Engine.Extensibility.IResultWriter.CheckWritability(), NUnit.ConsoleRunner.ConsoleRunner.CreateOutputWriter(), NUnit.Common.CommandLineOptions.DisplayTestLabels, NUnit.ConsoleRunner.ConsoleRunner.GetResultWriter(), NUnit.Engine.ITestEngine.GetRunner(), NUnit.ConsoleRunner.ConsoleRunner.INVALID_ASSEMBLY, NUnit.Common.CommandLineOptions.NoColor, NUnit.ConsoleRunner.ConsoleRunner.RedirectErrorOutputAsRequested(), NUnit.ConsoleRunner.ConsoleRunner.RestoreErrorOutput(), NUnit.Common.CommandLineOptions.ResultOutputSpecifications, NUnit.Common.CommandLineOptions.TeamCity, NUnit.ConsoleRunner.ConsoleRunner.UNEXPECTED_ERROR, NUnit.Common.ExtendedTextWriter.WriteLine(), and NUnit.Engine.Extensibility.IResultWriter.WriteResultFile().
Referenced by NUnit.ConsoleRunner.ConsoleRunner.Execute().
DisplayRuntimeEnvironment()
void NUnit.ConsoleRunner.ConsoleRunner.DisplayRuntimeEnvironment (ExtendedTextWriter OutWriter) inline private
References NUnit.ConsoleRunner.ConsoleRunner.GetOSVersion(), NUnit.Common.ExtendedTextWriter.WriteLabelLine(), and NUnit.Common.ExtendedTextWriter.WriteLine().
Referenced by NUnit.ConsoleRunner.ConsoleRunner.Execute().
GetOSVersion()
static string NUnit.ConsoleRunner.ConsoleRunner.GetOSVersion () inline static private
References NUnit.ConsoleRunner.ConsoleRunner.uname().
Referenced by NUnit.ConsoleRunner.ConsoleRunner.DisplayRuntimeEnvironment().
uname()
static int NUnit.ConsoleRunner.ConsoleRunner.uname (IntPtr buf) private
Referenced by NUnit.ConsoleRunner.ConsoleRunner.GetOSVersion().
DisplayTestFilters()
void NUnit.ConsoleRunner.ConsoleRunner.DisplayTestFilters () inline private
References NUnit.ConsoleRunner.ConsoleRunner._options, NUnit.ConsoleRunner.ConsoleRunner._outWriter, NUnit.Common.CommandLineOptions.TestList, NUnit.Common.CommandLineOptions.WhereClause, NUnit.Common.CommandLineOptions.WhereClauseSpecified, NUnit.Common.ExtendedTextWriter.WriteLabelLine(), and NUnit.Common.ExtendedTextWriter.WriteLine().
Referenced by NUnit.ConsoleRunner.ConsoleRunner.Execute().
RedirectErrorOutputAsRequested()
void NUnit.ConsoleRunner.ConsoleRunner.RedirectErrorOutputAsRequested () inline private
References NUnit.ConsoleRunner.ConsoleRunner._errorWriter, NUnit.ConsoleRunner.ConsoleRunner._options, NUnit.ConsoleRunner.ConsoleRunner._workDirectory, NUnit.Common.CommandLineOptions.ErrFile, and NUnit.Common.CommandLineOptions.ErrFileSpecified.
Referenced by NUnit.ConsoleRunner.ConsoleRunner.RunTests().
CreateOutputWriter()
ExtendedTextWriter NUnit.ConsoleRunner.ConsoleRunner.CreateOutputWriter () inline private
References NUnit.ConsoleRunner.ConsoleRunner._options, NUnit.ConsoleRunner.ConsoleRunner._outWriter, NUnit.ConsoleRunner.ConsoleRunner._workDirectory, NUnit.Common.CommandLineOptions.OutFile, and NUnit.Common.CommandLineOptions.OutFileSpecified.
Referenced by NUnit.ConsoleRunner.ConsoleRunner.RunTests().
RestoreErrorOutput()
void NUnit.ConsoleRunner.ConsoleRunner.RestoreErrorOutput () inline private
References NUnit.ConsoleRunner.ConsoleRunner._errorWriter, NUnit.ConsoleRunner.ConsoleRunner._options, and NUnit.Common.CommandLineOptions.ErrFileSpecified.
Referenced by NUnit.ConsoleRunner.ConsoleRunner.RunTests().
GetResultWriter()
IResultWriter NUnit.ConsoleRunner.ConsoleRunner.GetResultWriter (OutputSpecification spec) inline private
References NUnit.ConsoleRunner.ConsoleRunner._resultService, NUnit.Common.OutputSpecification.Format, and NUnit.Engine.IResultService.GetResultWriter().
Referenced by NUnit.ConsoleRunner.ConsoleRunner.RunTests().
MakeTestPackage()
static TestPackage NUnit.ConsoleRunner.ConsoleRunner.MakeTestPackage (ConsoleOptions options) inline static
References NUnit.Common.ConsoleOptions.ActiveConfig, NUnit.Common.PackageSettings.ActiveConfig, NUnit.Common.ConsoleOptions.ActiveConfigSpecified, NUnit.Engine.TestPackage.AddSetting(), NUnit.Common.ConsoleOptions.DebugAgent, NUnit.Common.PackageSettings.DebugAgent, NUnit.Common.PackageSettings.DebugTests, NUnit.Common.ConsoleOptions.DebugTests, NUnit.Common.CommandLineOptions.DefaultTimeout, NUnit.Common.PackageSettings.DefaultTimeout, NUnit.Common.ConsoleOptions.DisposeRunners, NUnit.Common.PackageSettings.DisposeRunners, NUnit.Common.ConsoleOptions.DomainUsage, NUnit.Common.PackageSettings.DomainUsage, NUnit.Common.ConsoleOptions.DomainUsageSpecified, NUnit.Common.ConsoleOptions.Framework, NUnit.Common.ConsoleOptions.FrameworkSpecified, NUnit.Common.PackageSettings.InternalTraceLevel, NUnit.Common.CommandLineOptions.InternalTraceLevel, NUnit.Common.CommandLineOptions.InternalTraceLevelSpecified, NUnit.Common.ConsoleOptions.MaxAgents, NUnit.Common.PackageSettings.MaxAgents, NUnit.Common.ConsoleOptions.MaxAgentsSpecified, NUnit.Common.CommandLineOptions.NumberOfTestWorkers, NUnit.Common.PackageSettings.NumberOfTestWorkers, NUnit.Common.CommandLineOptions.NumberOfTestWorkersSpecified, NUnit.Common.PackageSettings.PauseBeforeRun, NUnit.Common.ConsoleOptions.PauseBeforeRun, NUnit.Common.ConsoleOptions.ProcessModel, NUnit.Common.PackageSettings.ProcessModel, NUnit.Common.ConsoleOptions.ProcessModelSpecified, NUnit.Common.CommandLineOptions.RandomSeed, NUnit.Common.PackageSettings.RandomSeed, NUnit.Common.CommandLineOptions.RandomSeedSpecified, NUnit.Common.ConsoleOptions.RunAsX86, NUnit.Common.PackageSettings.RunAsX86, NUnit.Common.PackageSettings.RuntimeFramework, NUnit.Common.ConsoleOptions.ShadowCopyFiles, NUnit.Common.PackageSettings.ShadowCopyFiles, NUnit.Common.CommandLineOptions.StopOnError, NUnit.Common.PackageSettings.StopOnError, NUnit.Common.CommandLineOptions.Verbose, NUnit.Common.PackageSettings.WorkDirectory, and NUnit.Common.CommandLineOptions.WorkDirectory.
CreateTestFilter()
TestFilter NUnit.ConsoleRunner.ConsoleRunner.CreateTestFilter (ConsoleOptions options) inline private
References NUnit.ConsoleRunner.ConsoleRunner._filterService, NUnit.Engine.ITestFilterBuilder.AddTest(), NUnit.Engine.ITestFilterService.GetTestFilterBuilder(), NUnit.Common.CommandLineOptions.TestList, NUnit.Common.CommandLineOptions.WhereClause, and NUnit.Common.CommandLineOptions.WhereClauseSpecified.
Referenced by NUnit.ConsoleRunner.ConsoleRunner.Execute().
Member Data Documentation
OK
readonly int NUnit.ConsoleRunner.ConsoleRunner.OK = 0 static
Referenced by NUnit.ConsoleRunner.Program.Main().
INVALID_ARG
readonly int NUnit.ConsoleRunner.ConsoleRunner.INVALID_ARG = -1 static
Referenced by NUnit.ConsoleRunner.Program.Main().
INVALID_ASSEMBLY
readonly int NUnit.ConsoleRunner.ConsoleRunner.INVALID_ASSEMBLY = -2 static
Referenced by NUnit.ConsoleRunner.Program.Main(), and NUnit.ConsoleRunner.ConsoleRunner.RunTests().
FIXTURE_NOT_FOUND
readonly int NUnit.ConsoleRunner.ConsoleRunner.FIXTURE_NOT_FOUND = -3 static
UNEXPECTED_ERROR
readonly int NUnit.ConsoleRunner.ConsoleRunner.UNEXPECTED_ERROR = -100 static
Referenced by NUnit.ConsoleRunner.Program.Main(), and NUnit.ConsoleRunner.ConsoleRunner.RunTests().
_engine
ITestEngine NUnit.ConsoleRunner.ConsoleRunner._engine private
Referenced by NUnit.ConsoleRunner.ConsoleRunner.ConsoleRunner(), NUnit.ConsoleRunner.ConsoleRunner.ExploreTests(), and NUnit.ConsoleRunner.ConsoleRunner.RunTests().
_options
ConsoleOptions NUnit.ConsoleRunner.ConsoleRunner._options private
Referenced by NUnit.ConsoleRunner.ConsoleRunner.ConsoleRunner(), NUnit.ConsoleRunner.ConsoleRunner.CreateOutputWriter(), NUnit.ConsoleRunner.ConsoleRunner.DisplayTestFiles(), NUnit.ConsoleRunner.ConsoleRunner.DisplayTestFilters(), NUnit.ConsoleRunner.ConsoleRunner.Execute(), NUnit.ConsoleRunner.ConsoleRunner.ExploreTests(), NUnit.ConsoleRunner.ConsoleRunner.RedirectErrorOutputAsRequested(), NUnit.ConsoleRunner.ConsoleRunner.RestoreErrorOutput(), and NUnit.ConsoleRunner.ConsoleRunner.RunTests().
_resultService
IResultService NUnit.ConsoleRunner.ConsoleRunner._resultService private
Referenced by NUnit.ConsoleRunner.ConsoleRunner.ConsoleRunner(), NUnit.ConsoleRunner.ConsoleRunner.ExploreTests(), and NUnit.ConsoleRunner.ConsoleRunner.GetResultWriter().
_filterService
ITestFilterService NUnit.ConsoleRunner.ConsoleRunner._filterService private
Referenced by NUnit.ConsoleRunner.ConsoleRunner.ConsoleRunner(), and NUnit.ConsoleRunner.ConsoleRunner.CreateTestFilter().
_outWriter
ExtendedTextWriter NUnit.ConsoleRunner.ConsoleRunner._outWriter private
Referenced by NUnit.ConsoleRunner.ConsoleRunner.ConsoleRunner(), NUnit.ConsoleRunner.ConsoleRunner.CreateOutputWriter(), NUnit.ConsoleRunner.ConsoleRunner.DisplayTestFiles(), NUnit.ConsoleRunner.ConsoleRunner.DisplayTestFilters(), NUnit.ConsoleRunner.ConsoleRunner.Execute(), NUnit.ConsoleRunner.ConsoleRunner.ExploreTests(), and NUnit.ConsoleRunner.ConsoleRunner.RunTests().
_errorWriter
TextWriter NUnit.ConsoleRunner.ConsoleRunner._errorWriter = Console.Error private
Referenced by NUnit.ConsoleRunner.ConsoleRunner.RedirectErrorOutputAsRequested(), and NUnit.ConsoleRunner.ConsoleRunner.RestoreErrorOutput().
_workDirectory
string NUnit.ConsoleRunner.ConsoleRunner._workDirectory private
Referenced by NUnit.ConsoleRunner.ConsoleRunner.ConsoleRunner(), NUnit.ConsoleRunner.ConsoleRunner.CreateOutputWriter(), NUnit.ConsoleRunner.ConsoleRunner.RedirectErrorOutputAsRequested(), and NUnit.ConsoleRunner.ConsoleRunner.RunTests().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitConsole/nunit3-console/ConsoleRunner.cs