Doc: IGLib EXTENDED: AForge.Imaging.Filters.HSLLinear Class Reference
AForge.Imaging.Filters.HSLLinear Class Reference
Luminance and saturation linear correction.
Public Member Functions
HSLLinear ()
Initializes a new instance of the HSLLinear class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image, Rectangle rect)
Process the filter on the specified image.
Properties
Range InLuminance [get, set]
Luminance input range.
Range OutLuminance [get, set]
Luminance output range.
Range InSaturation [get, set]
Saturation input range.
Range OutSaturation [get, set]
Saturation output range.
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
Range inLuminance = new Range(0.0f, 1.0f)
Range inSaturation = new Range(0.0f, 1.0f)
Range outLuminance = new Range(0.0f, 1.0f)
Range outSaturation = new Range(0.0f, 1.0f)
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Luminance and saturation linear correction.
The filter operates in HSL color space and provides with the facility of luminance and saturation linear correction - mapping specified channels' input ranges to specified output ranges.
The filter accepts 24 and 32 bpp color images for processing.
Sample usage:
// create filter
HSLLinear filter = new HSLLinear();
// configure the filter
filter.InLuminance   = new Range(0, 0.85f);
filter.OutSaturation = new Range(0.25f, 1);
// apply the filter
filter.ApplyInPlace(image);
Initial image:
Result image:
See also
LevelsLinear, YCbCrLinear
Constructor & Destructor Documentation
HSLLinear()
AForge.Imaging.Filters.HSLLinear.HSLLinear () inline
Initializes a new instance of the HSLLinear class.
References AForge.Imaging.Filters.HSLLinear.formatTranslations.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.HSLLinear.ProcessFilter (UnmanagedImage image, Rectangle rect) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
rect Image rectangle for processing by the filter.
Implements AForge.Imaging.Filters.BaseInPlacePartialFilter.
References AForge.Imaging.RGB.B, AForge.Imaging.RGB.Blue, AForge.Imaging.HSL.FromRGB(), AForge.Imaging.RGB.G, AForge.Imaging.RGB.Green, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.Filters.HSLLinear.inLuminance, AForge.Imaging.Filters.HSLLinear.inSaturation, AForge.Imaging.HSL.Luminance, AForge.Range.Max, AForge.Range.Min, AForge.Imaging.Filters.HSLLinear.outLuminance, AForge.Imaging.Filters.HSLLinear.outSaturation, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, AForge.Imaging.RGB.Red, AForge.Imaging.HSL.Saturation, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.HSL.ToRGB().
Member Data Documentation
inLuminance
Range AForge.Imaging.Filters.HSLLinear.inLuminance = new Range(0.0f, 1.0f) private
Referenced by AForge.Imaging.Filters.HSLLinear.ProcessFilter().
inSaturation
Range AForge.Imaging.Filters.HSLLinear.inSaturation = new Range(0.0f, 1.0f) private
Referenced by AForge.Imaging.Filters.HSLLinear.ProcessFilter().
outLuminance
Range AForge.Imaging.Filters.HSLLinear.outLuminance = new Range(0.0f, 1.0f) private
Referenced by AForge.Imaging.Filters.HSLLinear.ProcessFilter().
outSaturation
Range AForge.Imaging.Filters.HSLLinear.outSaturation = new Range(0.0f, 1.0f) private
Referenced by AForge.Imaging.Filters.HSLLinear.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.HSLLinear.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.HSLLinear.HSLLinear().
Property Documentation
InLuminance
Range AForge.Imaging.Filters.HSLLinear.InLuminance get set
Luminance input range.
Luminance component is measured in the range of [0, 1].
OutLuminance
Range AForge.Imaging.Filters.HSLLinear.OutLuminance get set
Luminance output range.
Luminance component is measured in the range of [0, 1].
InSaturation
Range AForge.Imaging.Filters.HSLLinear.InSaturation get set
Saturation input range.
Saturation component is measured in the range of [0, 1].
OutSaturation
Range AForge.Imaging.Filters.HSLLinear.OutSaturation get set
Saturation output range.
Saturation component is measured in the range of [0, 1].
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.HSLLinear.FormatTranslations get
Format translations dictionary.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/HSL Filters/HSLLinear.cs