Doc: IGLib EXTENDED: IG.Forms.ImageViewerForm Class Reference
IG.Forms.ImageViewerForm Class Reference
Public Member Functions
ImageViewerForm ()
ImageViewerForm ()
ImageViewerForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
ImageViewerControl imageViewerControl1
Constructor & Destructor Documentation
ImageViewerForm() [1/3]
IG.Forms.ImageViewerForm.ImageViewerForm () inline
References IG.Forms.ImageViewerForm.InitializeComponent().
ImageViewerForm() [2/3]
IG.Forms.ImageViewerForm.ImageViewerForm () inline
References IG.Forms.ImageViewerForm.InitializeComponent().
ImageViewerForm() [3/3]
IG.Forms.ImageViewerForm.ImageViewerForm () inline
References IG.Forms.ImageViewerForm.InitializeComponent().
Member Function Documentation
Dispose() [1/3]
override void IG.Forms.ImageViewerForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ImageViewerForm.components.
InitializeComponent() [1/3]
void IG.Forms.ImageViewerForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ImageViewerForm.imageViewerControl1.
Referenced by IG.Forms.ImageViewerForm.ImageViewerForm().
Dispose() [2/3]
override void IG.Forms.ImageViewerForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ImageViewerForm.components.
InitializeComponent() [2/3]
void IG.Forms.ImageViewerForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ImageViewerForm.imageViewerControl1.
Dispose() [3/3]
override void IG.Forms.ImageViewerForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ImageViewerForm.components.
InitializeComponent() [3/3]
void IG.Forms.ImageViewerForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ImageViewerForm.imageViewerControl1.
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.ImageViewerForm.components = null private
Required designer variable.
Referenced by IG.Forms.ImageViewerForm.Dispose().
imageViewerControl1
ImageViewerControl IG.Forms.ImageViewerForm.imageViewerControl1 private
Referenced by IG.Forms.ImageViewerForm.InitializeComponent().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/Viewers/ImageViewerForm.cs
iglib/igforms/Utilities/Viewers/ImageViewerForm.Designer.cs