Doc: IGLib EXTENDED: FuzzyAGV.AboutForm Class Reference
FuzzyAGV.AboutForm Class Reference
Public Member Functions
AboutForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void LinkClicked (object sender, LinkLabelLinkClickedEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.LinkLabel emailLabel
System.Windows.Forms.Label label3
System.Windows.Forms.LinkLabel aforgeFrameworkLabel
System.Windows.Forms.Label label2
System.Windows.Forms.Label label1
Constructor & Destructor Documentation
AboutForm()
FuzzyAGV.AboutForm.AboutForm () inline
References FuzzyAGV.AboutForm.aforgeFrameworkLabel, FuzzyAGV.AboutForm.emailLabel, and FuzzyAGV.AboutForm.InitializeComponent().
Member Function Documentation
LinkClicked()
void FuzzyAGV.AboutForm.LinkClicked (object sender, LinkLabelLinkClickedEventArgs e) inline private
Referenced by FuzzyAGV.AboutForm.InitializeComponent().
Dispose()
override void FuzzyAGV.AboutForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References FuzzyAGV.AboutForm.components.
InitializeComponent()
void FuzzyAGV.AboutForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References FuzzyAGV.AboutForm.aforgeFrameworkLabel, FuzzyAGV.AboutForm.emailLabel, FuzzyAGV.AboutForm.label1, FuzzyAGV.AboutForm.label2, FuzzyAGV.AboutForm.label3, and FuzzyAGV.AboutForm.LinkClicked().
Referenced by FuzzyAGV.AboutForm.AboutForm().
Member Data Documentation
components
System.ComponentModel.IContainer FuzzyAGV.AboutForm.components = null private
Required designer variable.
Referenced by FuzzyAGV.AboutForm.Dispose().
emailLabel
System.Windows.Forms.LinkLabel FuzzyAGV.AboutForm.emailLabel private
Referenced by FuzzyAGV.AboutForm.AboutForm(), and FuzzyAGV.AboutForm.InitializeComponent().
label3
System.Windows.Forms.Label FuzzyAGV.AboutForm.label3 private
Referenced by FuzzyAGV.AboutForm.InitializeComponent().
aforgeFrameworkLabel
System.Windows.Forms.LinkLabel FuzzyAGV.AboutForm.aforgeFrameworkLabel private
Referenced by FuzzyAGV.AboutForm.AboutForm(), and FuzzyAGV.AboutForm.InitializeComponent().
label2
System.Windows.Forms.Label FuzzyAGV.AboutForm.label2 private
Referenced by FuzzyAGV.AboutForm.InitializeComponent().
label1
System.Windows.Forms.Label FuzzyAGV.AboutForm.label1 private
Referenced by FuzzyAGV.AboutForm.InitializeComponent().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Fuzzy/FuzzyAGV/AboutForm.cs
shelldev/lib_ann/aforge.net/Samples/Fuzzy/FuzzyAGV/AboutForm.Designer.cs