Doc: IGLib EXTENDED: AForge.Fuzzy.InferenceSystem Class Reference
AForge.Fuzzy.InferenceSystem Class Reference
This class represents a Fuzzy Inference System.
Public Member Functions
InferenceSystem (Database database, IDefuzzifier defuzzifier)
Initializes a new Fuzzy InferenceSystem.
InferenceSystem (Database database, IDefuzzifier defuzzifier, INorm normOperator, ICoNorm conormOperator)
Initializes a new Fuzzy InferenceSystem.
Rule NewRule (string name, string rule)
Creates a new Rule and add it to the Rulebase of the InferenceSystem.
void SetInput (string variableName, float value)
Sets a numerical input for one of the linguistic variables of the Database.
LinguisticVariable GetLinguisticVariable (string variableName)
Gets one of the LinguisticVariable of the Database.
Rule GetRule (string ruleName)
Gets one of the Rules of the Rulebase.
float Evaluate (string variableName)
Executes the fuzzy inference, obtaining a numerical output for a choosen output linguistic variable.
FuzzyOutput ExecuteInference (string variableName)
Executes the fuzzy inference, obtaining the FuzzyOutput of the system for the required LinguisticVariable.
Private Attributes
Database database
Rulebase rulebase
IDefuzzifier defuzzifier
INorm normOperator
ICoNorm conormOperator
Detailed Description
This class represents a Fuzzy Inference System.
A Fuzzy Inference System is a model capable of executing fuzzy computing. It is mainly composed by a Database with the linguistic variables (see LinguisticVariable) and a Rulebase with the fuzzy rules (see Rule) that represent the behavior of the system. The typical operation of a Fuzzy Inference System is:
Get the numeric inputs;
Use the Database with the linguistic variables (see LinguisticVariable) to obtain linguistic meaning for each numerical input;
Verify which rules (see Rule) of the Rulebase are activated by the input;
Combine the consequent of the activated rules to obtain a FuzzyOutput;
Use some defuzzifier (see IDefuzzifier) to obtain a numerical output.
The following sample usage is a Fuzzy Inference System that controls an auto guided vehicle avoing frontal collisions:
// linguistic labels (fuzzy sets) that compose the distances
FuzzySet fsNear = new FuzzySet("Near",
    new TrapezoidalFunction( 15, 50, TrapezoidalFunction.EdgeType.Right ) );
FuzzySet fsMedium = new FuzzySet("Medium",
    new TrapezoidalFunction( 15, 50, 60, 100 ) );
FuzzySet fsFar = new FuzzySet("Far",
    new TrapezoidalFunction( 60, 100, TrapezoidalFunction.EdgeType.Left ) );
// front distance (input)
LinguisticVariable lvFront = new LinguisticVariable("FrontalDistance", 0, 120);
lvFront.AddLabel(fsNear);
lvFront.AddLabel(fsMedium);
lvFront.AddLabel(fsFar);
// linguistic labels (fuzzy sets) that compose the angle
FuzzySet fsZero = new FuzzySet("Zero",
    new TrapezoidalFunction( -10, 5, 5, 10 ) );
FuzzySet fsLP = new FuzzySet("LittlePositive",
    new TrapezoidalFunction( 5, 10, 20, 25 ) );
FuzzySet fsP = new FuzzySet("Positive",
    new TrapezoidalFunction( 20, 25, 35, 40 ) );
FuzzySet fsVP = new FuzzySet("VeryPositive",
    new TrapezoidalFunction( 35, 40, TrapezoidalFunction.EdgeType.Left ) );
// angle
LinguisticVariable lvAngle = new LinguisticVariable("Angle", -10, 50);
lvAngle.AddLabel(fsZero);
lvAngle.AddLabel(fsLP);
lvAngle.AddLabel(fsP);
lvAngle.AddLabel(fsVP);
// the database
Database fuzzyDB = new Database();
fuzzyDB.AddVariable(lvFront);
fuzzyDB.AddVariable(lvAngle);
// creating the inference system
InferenceSystem IS = new InferenceSystem(fuzzyDB, new CentroidDefuzzifier(1000));
// going Straight
IS.NewRule("Rule 1", "IF FrontalDistance IS Far THEN Angle IS Zero");
// Turning Left
IS.NewRule("Rule 2", "IF FrontalDistance IS Near THEN Angle IS Positive");
...
// inference section
// setting inputs
IS.SetInput("FrontalDistance", 20);
// getting outputs
try
{
    float newAngle = IS.Evaluate( "Angle" );
}
catch (Exception)
{
...
}
Constructor & Destructor Documentation
InferenceSystem() [1/2]
AForge.Fuzzy.InferenceSystem.InferenceSystem (Database database, IDefuzzifier defuzzifier) inline
Initializes a new Fuzzy InferenceSystem.
Parameters
database A fuzzy Database containing the system linguistic variables.
defuzzifier A defuzzyfier method used to evaluate the numeric uotput of the system.
InferenceSystem() [2/2]
AForge.Fuzzy.InferenceSystem.InferenceSystem (Database database, IDefuzzifier defuzzifier, INorm normOperator, ICoNorm conormOperator) inline
Initializes a new Fuzzy InferenceSystem.
Parameters
database A fuzzy Database containing the system linguistic variables.
defuzzifier A defuzzyfier method used to evaluate the numeric otput of the system.
normOperator A INorm operator used to evaluate the norms in the InferenceSystem. For more information of the norm evaluation see Rule.
conormOperator A ICoNorm operator used to evaluate the conorms in the InferenceSystem. For more information of the conorm evaluation see Rule.
References AForge.Fuzzy.InferenceSystem.conormOperator, AForge.Fuzzy.InferenceSystem.database, AForge.Fuzzy.InferenceSystem.defuzzifier, and AForge.Fuzzy.InferenceSystem.normOperator.
Member Function Documentation
NewRule()
Rule AForge.Fuzzy.InferenceSystem.NewRule (string name, string rule) inline
Creates a new Rule and add it to the Rulebase of the InferenceSystem.
Parameters
name Name of the Rule to create.
rule A string representing the fuzzy rule.
Returns
The new Rule reference.
References AForge.Fuzzy.Rulebase.AddRule(), AForge.Fuzzy.InferenceSystem.conormOperator, AForge.Fuzzy.InferenceSystem.database, and AForge.Fuzzy.InferenceSystem.normOperator.
Referenced by FuzzyAGV.MainForm.InitFuzzyEngine().
SetInput()
void AForge.Fuzzy.InferenceSystem.SetInput (string variableName, float value) inline
Sets a numerical input for one of the linguistic variables of the Database.
Parameters
variableName Name of the LinguisticVariable.
value Numeric value to be used as input.
Exceptions
KeyNotFoundException The variable indicated in variableName was not found in the database.
References AForge.Fuzzy.Database.GetVariable(), and AForge.Fuzzy.LinguisticVariable.NumericInput.
Referenced by FuzzyAGV.MainForm.DoInference().
GetLinguisticVariable()
LinguisticVariable AForge.Fuzzy.InferenceSystem.GetLinguisticVariable (string variableName) inline
Gets one of the LinguisticVariable of the Database.
Parameters
variableName Name of the LinguisticVariable to get.
Exceptions
KeyNotFoundException The variable indicated in variableName was not found in the database.
References AForge.Fuzzy.Database.GetVariable().
GetRule()
Rule AForge.Fuzzy.InferenceSystem.GetRule (string ruleName) inline
Gets one of the Rules of the Rulebase.
Parameters
ruleName Name of the Rule to get.
Exceptions
KeyNotFoundException The rule indicated in ruleName was not found in the rulebase.
References AForge.Fuzzy.Rulebase.GetRule().
Evaluate()
float AForge.Fuzzy.InferenceSystem.Evaluate (string variableName) inline
Executes the fuzzy inference, obtaining a numerical output for a choosen output linguistic variable.
Parameters
variableName Name of the LinguisticVariable to evaluate.
Returns
The numerical output of the Fuzzy Inference System for the choosen variable.
Exceptions
KeyNotFoundException The variable indicated was not found in the database.
References AForge.Fuzzy.InferenceSystem.defuzzifier, AForge.Fuzzy.IDefuzzifier.Defuzzify(), AForge.Fuzzy.InferenceSystem.ExecuteInference(), and AForge.Fuzzy.InferenceSystem.normOperator.
Referenced by FuzzyAGV.MainForm.DoInference().
ExecuteInference()
FuzzyOutput AForge.Fuzzy.InferenceSystem.ExecuteInference (string variableName) inline
Executes the fuzzy inference, obtaining the FuzzyOutput of the system for the required LinguisticVariable.
Parameters
variableName Name of the LinguisticVariable to evaluate.
Returns
A FuzzyOutput containing the fuzzy output of the system for the LinguisticVariable specified in variableName .
Exceptions
KeyNotFoundException The variable indicated was not found in the database.
References AForge.Fuzzy.InferenceSystem.database, AForge.Fuzzy.Rule.EvaluateFiringStrength(), AForge.Fuzzy.Rulebase.GetRules(), AForge.Fuzzy.Database.GetVariable(), AForge.Fuzzy.Clause.Label, AForge.Fuzzy.FuzzySet.Name, AForge.Fuzzy.LinguisticVariable.Name, AForge.Fuzzy.Rule.Output, AForge.Fuzzy.InferenceSystem.rulebase, and AForge.Fuzzy.Clause.Variable.
Referenced by AForge.Fuzzy.InferenceSystem.Evaluate().
Member Data Documentation
database
Database AForge.Fuzzy.InferenceSystem.database private
Referenced by AForge.Fuzzy.InferenceSystem.ExecuteInference(), AForge.Fuzzy.InferenceSystem.InferenceSystem(), and AForge.Fuzzy.InferenceSystem.NewRule().
rulebase
Rulebase AForge.Fuzzy.InferenceSystem.rulebase private
Referenced by AForge.Fuzzy.InferenceSystem.ExecuteInference().
defuzzifier
IDefuzzifier AForge.Fuzzy.InferenceSystem.defuzzifier private
Referenced by AForge.Fuzzy.InferenceSystem.Evaluate(), and AForge.Fuzzy.InferenceSystem.InferenceSystem().
normOperator
INorm AForge.Fuzzy.InferenceSystem.normOperator private
Referenced by AForge.Fuzzy.InferenceSystem.Evaluate(), AForge.Fuzzy.InferenceSystem.InferenceSystem(), and AForge.Fuzzy.InferenceSystem.NewRule().
conormOperator
ICoNorm AForge.Fuzzy.InferenceSystem.conormOperator private
Referenced by AForge.Fuzzy.InferenceSystem.InferenceSystem(), and AForge.Fuzzy.InferenceSystem.NewRule().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Fuzzy/InferenceSystem.cs