Doc: IGLib EXTENDED: DotNumerics.FortranLibrary.Characters Class Reference
DotNumerics.FortranLibrary.Characters Class Reference
Public Member Functions
Characters (int length)
Characters (char[] sourceChars, bool copy)
Characters (string s)
Characters (string s, int length)
void Copy (int startIndex, int lastIndex, char[] sourceCharArray)
void Copy (int startIndex, char[] sourceCharArray)
void Copy (char[] sourceCharArray)
void Copy (int startIndex, int lastIndex, string sourceString)
void Copy (int startIndex, string sourceString)
void Copy (string sourceString)
void Replace (char[] source)
void Replace (Characters source)
void Replace (string source)
Characters Substring (int startIndex, int lastIndex)
Characters Substring (int startIndex)
void ToUpper ()
void ToLower ()
void ToBlanks ()
void ToBlanks (int start, int last)
void ToBlanks (int length)
int ToInt32 ()
string Trim ()
void AdjustLeft ()
void AdjustRight ()
int LenTrim ()
override bool Equals (System.Object obj)
override int GetHashCode ()
override string ToString ()
Static Public Member Functions
static Characters operator+ (Characters c1, Characters c2)
static Characters operator+ (string s, Characters c2)
static Characters operator+ (Characters c1, string s)
static Characters Add (char[] c1, char[] c2)
static bool operator== (Characters c1, Characters c2)
static bool operator== (string s, Characters c2)
static bool operator== (Characters c1, string s)
static bool operator!= (Characters c1, Characters c2)
static bool operator!= (string s, Characters c2)
static bool operator!= (Characters c1, string s)
static bool AreEqual (char[] left, char[] right)
static bool operator> (Characters c1, Characters c2)
static bool operator> (string s, Characters c2)
static bool operator> (Characters c1, string s)
static bool operator>= (Characters c1, Characters c2)
static bool operator>= (string s, Characters c2)
static bool operator>= (Characters c1, string s)
static bool LargeThan (char[] left, char[] right)
static bool operator< (Characters c1, Characters c2)
static bool operator< (string s, Characters c2)
static bool operator< (Characters c1, string s)
static bool operator<= (Characters c1, Characters c2)
static bool operator<= (string s, Characters c2)
static bool operator<= (Characters c1, string s)
static bool LeastThan (char[] left, char[] right)
static implicit operator Characters (string s)
Properties
char[] CharArray [get]
int Length [get]
Static Private Member Functions
static char[] GetCharArray (char[] source, int length)
Private Attributes
char[] _CharArray = new char[0]
Constructor & Destructor Documentation
Characters() [1/4]
DotNumerics.FortranLibrary.Characters.Characters (int length) inline
Referenced by DotNumerics.FortranLibrary.Characters.Add(), DotNumerics.FortranLibrary.Characters.Equals(), DotNumerics.FortranLibrary.Characters.operator Characters(), and DotNumerics.FortranLibrary.Characters.Substring().
Characters() [2/4]
DotNumerics.FortranLibrary.Characters.Characters (char[] sourceChars, bool copy) inline
Characters() [3/4]
DotNumerics.FortranLibrary.Characters.Characters (string s) inline
Characters() [4/4]
DotNumerics.FortranLibrary.Characters.Characters (string s, int length) inline
References DotNumerics.FortranLibrary.Characters.Copy().
Member Function Documentation
Copy() [1/6]
void DotNumerics.FortranLibrary.Characters.Copy (int startIndex, int lastIndex, char[] sourceCharArray) inline
References DotNumerics.FortranLibrary.Characters.Length.
Referenced by DotNumerics.FortranLibrary.Characters.Characters(), DotNumerics.FortranLibrary.Characters.Copy(), and DotNumerics.FortranLibrary.Characters.Replace().
Copy() [2/6]
void DotNumerics.FortranLibrary.Characters.Copy (int startIndex, char[] sourceCharArray) inline
References DotNumerics.FortranLibrary.Characters.Copy(), and DotNumerics.FortranLibrary.Characters.Length.
Copy() [3/6]
void DotNumerics.FortranLibrary.Characters.Copy (char[] sourceCharArray) inline
References DotNumerics.FortranLibrary.Characters.Copy().
Copy() [4/6]
void DotNumerics.FortranLibrary.Characters.Copy (int startIndex, int lastIndex, string sourceString) inline
References DotNumerics.FortranLibrary.Characters.Copy().
Copy() [5/6]
void DotNumerics.FortranLibrary.Characters.Copy (int startIndex, string sourceString) inline
References DotNumerics.FortranLibrary.Characters.Copy().
Copy() [6/6]
void DotNumerics.FortranLibrary.Characters.Copy (string sourceString) inline
References DotNumerics.FortranLibrary.Characters.Copy().
Replace() [1/3]
void DotNumerics.FortranLibrary.Characters.Replace (char[] source) inline
References DotNumerics.FortranLibrary.Characters.Copy(), and DotNumerics.FortranLibrary.Characters.ToBlanks().
Referenced by DotNumerics.FortranLibrary.Characters.Replace().
Replace() [2/3]
void DotNumerics.FortranLibrary.Characters.Replace (Characters source) inline
References DotNumerics.FortranLibrary.Characters.CharArray, and DotNumerics.FortranLibrary.Characters.Replace().
Replace() [3/3]
void DotNumerics.FortranLibrary.Characters.Replace (string source) inline
References DotNumerics.FortranLibrary.Characters.Replace().
Substring() [1/2]
Characters DotNumerics.FortranLibrary.Characters.Substring (int startIndex, int lastIndex) inline
References DotNumerics.FortranLibrary.Characters.Characters(), and DotNumerics.FortranLibrary.Characters.CharArray.
Referenced by DotNumerics.FortranLibrary.Characters.Substring().
Substring() [2/2]
Characters DotNumerics.FortranLibrary.Characters.Substring (int startIndex) inline
References DotNumerics.FortranLibrary.Characters.Length, and DotNumerics.FortranLibrary.Characters.Substring().
ToUpper()
void DotNumerics.FortranLibrary.Characters.ToUpper () inline
ToLower()
void DotNumerics.FortranLibrary.Characters.ToLower () inline
ToBlanks() [1/3]
void DotNumerics.FortranLibrary.Characters.ToBlanks () inline
Referenced by DotNumerics.FortranLibrary.Characters.Replace(), and DotNumerics.FortranLibrary.Characters.ToBlanks().
ToBlanks() [2/3]
void DotNumerics.FortranLibrary.Characters.ToBlanks (int start, int last) inline
ToBlanks() [3/3]
void DotNumerics.FortranLibrary.Characters.ToBlanks (int length) inline
References DotNumerics.FortranLibrary.Characters.ToBlanks().
ToInt32()
int DotNumerics.FortranLibrary.Characters.ToInt32 () inline
References DotNumerics.FortranLibrary.Characters.LenTrim().
Trim()
string DotNumerics.FortranLibrary.Characters.Trim () inline
AdjustLeft()
void DotNumerics.FortranLibrary.Characters.AdjustLeft () inline
Referenced by DotNumerics.FortranLibrary.Characters.AdjustRight().
AdjustRight()
void DotNumerics.FortranLibrary.Characters.AdjustRight () inline
References DotNumerics.FortranLibrary.Characters.AdjustLeft().
LenTrim()
int DotNumerics.FortranLibrary.Characters.LenTrim () inline
Referenced by DotNumerics.FortranLibrary.FortranLib.LEN_TRIM(), and DotNumerics.FortranLibrary.Characters.ToInt32().
operator+() [1/3]
static Characters DotNumerics.FortranLibrary.Characters.operator+ (Characters c1, Characters c2) inline static
References DotNumerics.FortranLibrary.Characters.Add(), and DotNumerics.FortranLibrary.Characters.CharArray.
operator+() [2/3]
static Characters DotNumerics.FortranLibrary.Characters.operator+ (string s, Characters c2) inline static
References DotNumerics.FortranLibrary.Characters.Add(), and DotNumerics.FortranLibrary.Characters.CharArray.
operator+() [3/3]
static Characters DotNumerics.FortranLibrary.Characters.operator+ (Characters c1, string s) inline static
References DotNumerics.FortranLibrary.Characters.Add(), and DotNumerics.FortranLibrary.Characters.CharArray.
Add()
static Characters DotNumerics.FortranLibrary.Characters.Add (char[] c1, char[] c2) inline static
References DotNumerics.FortranLibrary.Characters.Characters(), and DotNumerics.FortranLibrary.Characters.CharArray.
Referenced by DotNumerics.FortranLibrary.Characters.operator+().
operator==() [1/3]
static bool DotNumerics.FortranLibrary.Characters.operator== (Characters c1, Characters c2) inline static
References DotNumerics.FortranLibrary.Characters.AreEqual(), and DotNumerics.FortranLibrary.Characters.CharArray.
operator==() [2/3]
static bool DotNumerics.FortranLibrary.Characters.operator== (string s, Characters c2) inline static
References DotNumerics.FortranLibrary.Characters.AreEqual(), and DotNumerics.FortranLibrary.Characters.CharArray.
operator==() [3/3]
static bool DotNumerics.FortranLibrary.Characters.operator== (Characters c1, string s) inline static
References DotNumerics.FortranLibrary.Characters.AreEqual(), and DotNumerics.FortranLibrary.Characters.CharArray.
operator!=() [1/3]
static bool DotNumerics.FortranLibrary.Characters.operator!= (Characters c1, Characters c2) inline static
References DotNumerics.FortranLibrary.Characters.AreEqual(), and DotNumerics.FortranLibrary.Characters.CharArray.
operator!=() [2/3]
static bool DotNumerics.FortranLibrary.Characters.operator!= (string s, Characters c2) inline static
References DotNumerics.FortranLibrary.Characters.AreEqual(), and DotNumerics.FortranLibrary.Characters.CharArray.
operator!=() [3/3]
static bool DotNumerics.FortranLibrary.Characters.operator!= (Characters c1, string s) inline static
References DotNumerics.FortranLibrary.Characters.AreEqual(), and DotNumerics.FortranLibrary.Characters.CharArray.
AreEqual()
static bool DotNumerics.FortranLibrary.Characters.AreEqual (char[] left, char[] right) inline static
References DotNumerics.FortranLibrary.Characters.GetCharArray().
Referenced by DotNumerics.FortranLibrary.Characters.Equals(), DotNumerics.FortranLibrary.Characters.operator!=(), DotNumerics.FortranLibrary.Characters.operator<=(), DotNumerics.FortranLibrary.Characters.operator==(), and DotNumerics.FortranLibrary.Characters.operator>=().
Equals()
override bool DotNumerics.FortranLibrary.Characters.Equals (System.Object obj) inline
References DotNumerics.FortranLibrary.Characters.AreEqual(), and DotNumerics.FortranLibrary.Characters.Characters().
GetHashCode()
override int DotNumerics.FortranLibrary.Characters.GetHashCode () inline
operator>() [1/3]
static bool DotNumerics.FortranLibrary.Characters.operator> (Characters c1, Characters c2) inline static
References DotNumerics.FortranLibrary.Characters.CharArray, and DotNumerics.FortranLibrary.Characters.LargeThan().
operator>() [2/3]
static bool DotNumerics.FortranLibrary.Characters.operator> (string s, Characters c2) inline static
References DotNumerics.FortranLibrary.Characters.CharArray, and DotNumerics.FortranLibrary.Characters.LargeThan().
operator>() [3/3]
static bool DotNumerics.FortranLibrary.Characters.operator> (Characters c1, string s) inline static
References DotNumerics.FortranLibrary.Characters.CharArray, and DotNumerics.FortranLibrary.Characters.LargeThan().
operator>=() [1/3]
static bool DotNumerics.FortranLibrary.Characters.operator>= (Characters c1, Characters c2) inline static
References DotNumerics.FortranLibrary.Characters.AreEqual(), DotNumerics.FortranLibrary.Characters.CharArray, and DotNumerics.FortranLibrary.Characters.LargeThan().
operator>=() [2/3]
static bool DotNumerics.FortranLibrary.Characters.operator>= (string s, Characters c2) inline static
References DotNumerics.FortranLibrary.Characters.AreEqual(), DotNumerics.FortranLibrary.Characters.CharArray, and DotNumerics.FortranLibrary.Characters.LargeThan().
operator>=() [3/3]
static bool DotNumerics.FortranLibrary.Characters.operator>= (Characters c1, string s) inline static
References DotNumerics.FortranLibrary.Characters.AreEqual(), DotNumerics.FortranLibrary.Characters.CharArray, and DotNumerics.FortranLibrary.Characters.LargeThan().
LargeThan()
static bool DotNumerics.FortranLibrary.Characters.LargeThan (char[] left, char[] right) inline static
References DotNumerics.FortranLibrary.Characters.GetCharArray().
Referenced by DotNumerics.FortranLibrary.Characters.operator>(), and DotNumerics.FortranLibrary.Characters.operator>=().
operator<() [1/3]
static bool DotNumerics.FortranLibrary.Characters.operator< (Characters c1, Characters c2) inline static
References DotNumerics.FortranLibrary.Characters.CharArray, and DotNumerics.FortranLibrary.Characters.LeastThan().
operator<() [2/3]
static bool DotNumerics.FortranLibrary.Characters.operator< (string s, Characters c2) inline static
References DotNumerics.FortranLibrary.Characters.CharArray, and DotNumerics.FortranLibrary.Characters.LeastThan().
operator<() [3/3]
static bool DotNumerics.FortranLibrary.Characters.operator< (Characters c1, string s) inline static
References DotNumerics.FortranLibrary.Characters.CharArray, and DotNumerics.FortranLibrary.Characters.LeastThan().
operator<=() [1/3]
static bool DotNumerics.FortranLibrary.Characters.operator<= (Characters c1, Characters c2) inline static
References DotNumerics.FortranLibrary.Characters.AreEqual(), DotNumerics.FortranLibrary.Characters.CharArray, and DotNumerics.FortranLibrary.Characters.LeastThan().
operator<=() [2/3]
static bool DotNumerics.FortranLibrary.Characters.operator<= (string s, Characters c2) inline static
References DotNumerics.FortranLibrary.Characters.AreEqual(), DotNumerics.FortranLibrary.Characters.CharArray, and DotNumerics.FortranLibrary.Characters.LeastThan().
operator<=() [3/3]
static bool DotNumerics.FortranLibrary.Characters.operator<= (Characters c1, string s) inline static
References DotNumerics.FortranLibrary.Characters.AreEqual(), DotNumerics.FortranLibrary.Characters.CharArray, and DotNumerics.FortranLibrary.Characters.LeastThan().
LeastThan()
static bool DotNumerics.FortranLibrary.Characters.LeastThan (char[] left, char[] right) inline static
References DotNumerics.FortranLibrary.Characters.GetCharArray().
Referenced by DotNumerics.FortranLibrary.Characters.operator<(), and DotNumerics.FortranLibrary.Characters.operator<=().
GetCharArray()
static char [] DotNumerics.FortranLibrary.Characters.GetCharArray (char[] source, int length) inline static private
Referenced by DotNumerics.FortranLibrary.Characters.AreEqual(), DotNumerics.FortranLibrary.Characters.LargeThan(), and DotNumerics.FortranLibrary.Characters.LeastThan().
operator Characters()
static implicit DotNumerics.FortranLibrary.Characters.operator Characters (string s) inline static
References DotNumerics.FortranLibrary.Characters.Characters().
ToString()
override string DotNumerics.FortranLibrary.Characters.ToString () inline
Referenced by DotNumerics.FortranLibrary.FortranLib.INDEX(), and DotNumerics.FortranLibrary.FortranLib.SCAN().
Member Data Documentation
_CharArray
char [] DotNumerics.FortranLibrary.Characters._CharArray = new char[0] private
Property Documentation
CharArray
char [] DotNumerics.FortranLibrary.Characters.CharArray get
Referenced by DotNumerics.FortranLibrary.Characters.Add(), DotNumerics.FortranLibrary.FortranLib.Copy(), DotNumerics.FortranLibrary.Characters.operator!=(), DotNumerics.FortranLibrary.Characters.operator+(), DotNumerics.FortranLibrary.Characters.operator<(), DotNumerics.FortranLibrary.Characters.operator<=(), DotNumerics.FortranLibrary.Characters.operator==(), DotNumerics.FortranLibrary.Characters.operator>(), DotNumerics.FortranLibrary.Characters.operator>=(), DotNumerics.FortranLibrary.Characters.Replace(), and DotNumerics.FortranLibrary.Characters.Substring().
Length
int DotNumerics.FortranLibrary.Characters.Length get
Referenced by DotNumerics.FortranLibrary.Characters.Copy(), and DotNumerics.FortranLibrary.Characters.Substring().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/Characters.cs