Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAED9 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAED9 Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAED9 (DLAMC3 dlamc3, DNRM2 dnrm2, DCOPY dcopy, DLAED4 dlaed4, XERBLA xerbla)
DLAED9 ()
void Run (int K, int KSTART, int KSTOP, int N, ref double[] D, int offset_d, ref double[] Q, int offset_q, int LDQ, double RHO, ref double[] DLAMDA, int offset_dlamda, ref double[] W, int offset_w, ref double[] S, int offset_s, int LDS, ref int INFO)
Private Attributes
DLAMC3 _dlamc3
DNRM2 _dnrm2
DCOPY _dcopy
DLAED4 _dlaed4
XERBLA _xerbla
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAED9 finds the roots of the secular equation, as defined by the values in D, Z, and RHO, between KSTART and KSTOP. It makes the appropriate calls to DLAED4 and then stores the new matrix of eigenvectors for use in calculating the next level of Z vectors.
/summary>
Constructor & Destructor Documentation
DLAED9() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAED9.DLAED9 (DLAMC3 dlamc3, DNRM2 dnrm2, DCOPY dcopy, DLAED4 dlaed4, XERBLA xerbla) inline
DLAED9() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAED9.DLAED9 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAED9.Run (int K, int KSTART, int KSTOP, int N, ref double[] D, int offset_d, ref double[] Q, int offset_q, int LDQ, double RHO, ref double[] DLAMDA, int offset_dlamda, ref double[] W, int offset_w, ref double[] S, int offset_s, int LDS, ref int INFO) inline
Purpose
DLAED9 finds the roots of the secular equation, as defined by the values in D, Z, and RHO, between KSTART and KSTOP. It makes the appropriate calls to DLAED4 and then stores the new matrix of eigenvectors for use in calculating the next level of Z vectors.
/summary>
Parameters
K (input) INTEGER The number of terms in the rational function to be solved by DLAED4. K .GE. 0. /param>
Parameters
KSTART (input) INTEGER /param>
Parameters
KSTOP (input) INTEGER The updated eigenvalues Lambda(I), KSTART .LE. I .LE. KSTOP are to be computed. 1 .LE. KSTART .LE. KSTOP .LE. K. /param>
Parameters
N (input) INTEGER The number of rows and columns in the Q matrix. N .GE. K (delation may result in N .GT. K). /param>
Parameters
D (output) DOUBLE PRECISION array, dimension (N) D(I) contains the updated eigenvalues for KSTART .LE. I .LE. KSTOP. /param>
Parameters
Q (workspace) DOUBLE PRECISION array, dimension (LDQ,N) /param>
Parameters
LDQ (input) INTEGER The leading dimension of the array Q. LDQ .GE. max(1, N). /param>
Parameters
RHO (input) DOUBLE PRECISION The value of the parameter in the rank one update equation. RHO .GE. 0 required. /param>
Parameters
DLAMDA (input) DOUBLE PRECISION array, dimension (K) The first K elements of this array contain the old roots of the deflated updating problem. These are the poles of the secular equation. /param>
Parameters
W (input) DOUBLE PRECISION array, dimension (K) The first K elements of this array contain the components of the deflation-adjusted updating vector. /param>
Parameters
S (output) DOUBLE PRECISION array, dimension (LDS, K) Will contain the eigenvectors of the repaired matrix which will be stored for subsequent Z vector calculation and multiplied by the previously accumulated eigenvectors to update the system. /param>
Parameters
LDS (input) INTEGER The leading dimension of S. LDS .GE. max(1, K). /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. .GT. 0: if INFO = 1, an eigenvalue did not converge /param>
References DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DNRM2.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED4.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMC3.Run(), and DotNumerics.FortranLibrary.FortranLib.Sign().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED7.Run().
Member Data Documentation
_dlamc3
DLAMC3 DotNumerics.LinearAlgebra.CSLapack.DLAED9._dlamc3 private
_dnrm2
DNRM2 DotNumerics.LinearAlgebra.CSLapack.DLAED9._dnrm2 private
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLAED9._dcopy private
_dlaed4
DLAED4 DotNumerics.LinearAlgebra.CSLapack.DLAED9._dlaed4 private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLAED9._xerbla private
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlaed9.cs