Doc: IGLib EXTENDED: AForge.Genetic.DoubleArrayChromosome Class Reference
AForge.Genetic.DoubleArrayChromosome Class Reference
Double array chromosome.
Public Member Functions
DoubleArrayChromosome (IRandomNumberGenerator chromosomeGenerator, IRandomNumberGenerator mutationMultiplierGenerator, IRandomNumberGenerator mutationAdditionGenerator, int length)
Initializes a new instance of the DoubleArrayChromosome class.
DoubleArrayChromosome (IRandomNumberGenerator chromosomeGenerator, IRandomNumberGenerator mutationMultiplierGenerator, IRandomNumberGenerator mutationAdditionGenerator, double[] values)
Initializes a new instance of the DoubleArrayChromosome class.
DoubleArrayChromosome (DoubleArrayChromosome source)
Initializes a new instance of the DoubleArrayChromosome class.
override string ToString ()
Get string representation of the chromosome.
override void Generate ()
Generate random chromosome value.
override IChromosome CreateNew ()
Create new random chromosome with same parameters (factory method).
override IChromosome Clone ()
Clone the chromosome.
override void Mutate ()
Mutation operator.
override void Crossover (IChromosome pair)
Crossover operator.
Public Member Functions inherited from AForge.Genetic.ChromosomeBase
void Evaluate (IFitnessFunction function)
Evaluate chromosome with specified fitness function.
int CompareTo (object o)
Compare two chromosomes.
Static Public Attributes
const int MaxLength = 65536
Chromosome's maximum length.
Protected Attributes
IRandomNumberGenerator chromosomeGenerator
Chromosome generator.
IRandomNumberGenerator mutationMultiplierGenerator
Mutation multiplier generator.
IRandomNumberGenerator mutationAdditionGenerator
Mutation addition generator.
double[] val = null
Chromosome's value.
Protected Attributes inherited from AForge.Genetic.ChromosomeBase
double fitness = 0
Chromosome's fintess value.
Static Protected Attributes
static ThreadSafeRandom rand = new ThreadSafeRandom()
Random number generator for crossover and mutation points selection.
Properties
int Length [get]
Chromosome's length.
double[] Value [get]
Chromosome's value.
double MutationBalancer [get, set]
Mutation balancer to control mutation type, [0, 1].
double CrossoverBalancer [get, set]
Crossover balancer to control crossover type, [0, 1].
Properties inherited from AForge.Genetic.ChromosomeBase
double Fitness [get]
Chromosome's fintess value.
Properties inherited from AForge.Genetic.IChromosome
double Fitness [get]
Chromosome's fintess value.
Private Attributes
int length
Chromosome's length in number of elements.
double mutationBalancer = 0.5
double crossoverBalancer = 0.5
Detailed Description
Double array chromosome.
Double array chromosome represents array of double values. Array length is in the range of [2, 65536].
See documentation to Mutate and Crossover methods for information regarding implemented mutation and crossover operators.
Constructor & Destructor Documentation
DoubleArrayChromosome() [1/3]
AForge.Genetic.DoubleArrayChromosome.DoubleArrayChromosome (IRandomNumberGenerator chromosomeGenerator, IRandomNumberGenerator mutationMultiplierGenerator, IRandomNumberGenerator mutationAdditionGenerator, int length) inline
Initializes a new instance of the DoubleArrayChromosome class.
Parameters
chromosomeGenerator Chromosome generator - random number generator, which is used to initialize chromosome's genes, which is done by calling Generate method or in class constructor.
mutationMultiplierGenerator Mutation multiplier generator - random number generator, which is used to generate random multiplier values, which are used to multiply chromosome's genes during mutation.
mutationAdditionGenerator Mutation addition generator - random number generator, which is used to generate random addition values, which are used to add to chromosome's genes during mutation.
length Chromosome's length in array elements, [2, MaxLength].
The constructor initializes the new chromosome randomly by calling Generate method.
References AForge.Genetic.DoubleArrayChromosome.chromosomeGenerator, AForge.Genetic.DoubleArrayChromosome.Generate(), AForge.Genetic.DoubleArrayChromosome.length, AForge.Genetic.DoubleArrayChromosome.MaxLength, AForge.Genetic.DoubleArrayChromosome.mutationAdditionGenerator, AForge.Genetic.DoubleArrayChromosome.mutationMultiplierGenerator, and AForge.Genetic.DoubleArrayChromosome.val.
Referenced by AForge.Genetic.DoubleArrayChromosome.Clone(), AForge.Genetic.DoubleArrayChromosome.CreateNew(), and AForge.Genetic.DoubleArrayChromosome.Crossover().
DoubleArrayChromosome() [2/3]
AForge.Genetic.DoubleArrayChromosome.DoubleArrayChromosome (IRandomNumberGenerator chromosomeGenerator, IRandomNumberGenerator mutationMultiplierGenerator, IRandomNumberGenerator mutationAdditionGenerator, double[] values) inline
Initializes a new instance of the DoubleArrayChromosome class.
Parameters
chromosomeGenerator Chromosome generator - random number generator, which is used to initialize chromosome's genes, which is done by calling Generate method or in class constructor.
mutationMultiplierGenerator Mutation multiplier generator - random number generator, which is used to generate random multiplier values, which are used to multiply chromosome's genes during mutation.
mutationAdditionGenerator Mutation addition generator - random number generator, which is used to generate random addition values, which are used to add to chromosome's genes during mutation.
values Values used to initialize the chromosome.
The constructor initializes the new chromosome with specified values values.
Exceptions
ArgumentOutOfRangeException Invalid length of values array.
References AForge.Genetic.DoubleArrayChromosome.chromosomeGenerator, AForge.Genetic.DoubleArrayChromosome.MaxLength, AForge.Genetic.DoubleArrayChromosome.mutationAdditionGenerator, AForge.Genetic.DoubleArrayChromosome.mutationMultiplierGenerator, and AForge.Genetic.DoubleArrayChromosome.val.
DoubleArrayChromosome() [3/3]
AForge.Genetic.DoubleArrayChromosome.DoubleArrayChromosome (DoubleArrayChromosome source) inline
Initializes a new instance of the DoubleArrayChromosome class.
Parameters
source Source chromosome to copy.
This is a copy constructor, which creates the exact copy of specified chromosome.
References AForge.Genetic.DoubleArrayChromosome.chromosomeGenerator, AForge.Genetic.DoubleArrayChromosome.crossoverBalancer, AForge.Genetic.ChromosomeBase.fitness, AForge.Genetic.DoubleArrayChromosome.length, AForge.Genetic.DoubleArrayChromosome.mutationAdditionGenerator, AForge.Genetic.DoubleArrayChromosome.mutationBalancer, AForge.Genetic.DoubleArrayChromosome.mutationMultiplierGenerator, and AForge.Genetic.DoubleArrayChromosome.val.
Member Function Documentation
ToString()
override string AForge.Genetic.DoubleArrayChromosome.ToString () inline
Get string representation of the chromosome.
Returns
Returns string representation of the chromosome.
References AForge.Genetic.DoubleArrayChromosome.length, and AForge.Genetic.DoubleArrayChromosome.val.
Generate()
override void AForge.Genetic.DoubleArrayChromosome.Generate () inline virtual
Generate random chromosome value.
Regenerates chromosome's value using random number generator.
Implements AForge.Genetic.ChromosomeBase.
References AForge.Genetic.DoubleArrayChromosome.chromosomeGenerator, AForge.Genetic.DoubleArrayChromosome.length, AForge.Math.Random.IRandomNumberGenerator.Next(), and AForge.Genetic.DoubleArrayChromosome.val.
Referenced by AForge.Genetic.DoubleArrayChromosome.DoubleArrayChromosome().
CreateNew()
override IChromosome AForge.Genetic.DoubleArrayChromosome.CreateNew () inline virtual
Create new random chromosome with same parameters (factory method).
The method creates new chromosome of the same type, but randomly initialized. The method is useful as factory method for those classes, which work with chromosome's interface, but not with particular chromosome type.
Implements AForge.Genetic.ChromosomeBase.
References AForge.Genetic.DoubleArrayChromosome.chromosomeGenerator, AForge.Genetic.DoubleArrayChromosome.DoubleArrayChromosome(), AForge.Genetic.DoubleArrayChromosome.length, AForge.Genetic.DoubleArrayChromosome.mutationAdditionGenerator, and AForge.Genetic.DoubleArrayChromosome.mutationMultiplierGenerator.
Clone()
override IChromosome AForge.Genetic.DoubleArrayChromosome.Clone () inline virtual
Clone the chromosome.
Returns
Return's clone of the chromosome.
The method clones the chromosome returning the exact copy of it.
Implements AForge.Genetic.ChromosomeBase.
References AForge.Genetic.DoubleArrayChromosome.DoubleArrayChromosome().
Mutate()
override void AForge.Genetic.DoubleArrayChromosome.Mutate () inline virtual
Mutation operator.
The method performs chromosome's mutation, adding random number to chromosome's gene or multiplying the gene by random number. These random numbers are generated with help of mutation multiplier and mutation addition generators.
The exact type of mutation applied to the particular gene is selected randomly each time and depends on MutationBalancer. Before mutation is done a random number is generated in [0, 1] range - if the random number is smaller than MutationBalancer, then multiplication mutation is done, otherwise addition mutation.
Implements AForge.Genetic.ChromosomeBase.
References AForge.Genetic.DoubleArrayChromosome.length, AForge.Genetic.DoubleArrayChromosome.mutationAdditionGenerator, AForge.Genetic.DoubleArrayChromosome.mutationBalancer, AForge.Genetic.DoubleArrayChromosome.mutationMultiplierGenerator, AForge.Math.Random.IRandomNumberGenerator.Next(), AForge.ThreadSafeRandom.Next(), AForge.ThreadSafeRandom.NextDouble(), AForge.Genetic.DoubleArrayChromosome.rand, and AForge.Genetic.DoubleArrayChromosome.val.
Crossover()
override void AForge.Genetic.DoubleArrayChromosome.Crossover (IChromosome pair) inline virtual
Crossover operator.
Parameters
pair Pair chromosome to crossover with.
The method performs crossover between two chromosomes, selecting randomly the exact type of crossover to perform, which depends on CrossoverBalancer. Before crossover is done a random number is generated in [0, 1] range - if the random number is smaller than CrossoverBalancer, then the first crossover type is used, otherwise second type is used.
The first crossover type is based on interchanging range of genes (array elements) between these chromosomes and is known as one point crossover. A crossover point is selected randomly and chromosomes interchange genes, which start from the selected point.
The second crossover type is aimed to produce one child, which genes' values are between corresponding genes of parents, and another child, which genes' values are outside of the range formed by corresponding genes of parents. Let take, for example, two genes with 1.0 and 3.0 value (of course chromosomes have more genes, but for simplicity lets think about one). First of all we randomly choose a factor in the [0, 1] range, let's take 0.4. Then, for each pair of genes (we have one pair) we calculate difference value, which is 2.0 in our case. In the result well have two children one between and one outside of the range formed by parents genes' values. We may have 1.8 and 3.8 children, or we may have 0.2 and 2.2 children. As we can see we add/subtract (chosen randomly) difference * factor. So, this gives us exploration in between and in near outside. The randomly chosen factor is applied to all genes of the chromosomes participating in crossover.
Implements AForge.Genetic.ChromosomeBase.
References AForge.Genetic.DoubleArrayChromosome.crossoverBalancer, AForge.Genetic.DoubleArrayChromosome.DoubleArrayChromosome(), AForge.Genetic.DoubleArrayChromosome.length, AForge.ThreadSafeRandom.Next(), AForge.ThreadSafeRandom.NextDouble(), AForge.Genetic.DoubleArrayChromosome.rand, and AForge.Genetic.DoubleArrayChromosome.val.
Member Data Documentation
chromosomeGenerator
IRandomNumberGenerator AForge.Genetic.DoubleArrayChromosome.chromosomeGenerator protected
Chromosome generator.
This random number generator is used to initialize chromosome's genes, which is done by calling Generate method.
Referenced by AForge.Genetic.DoubleArrayChromosome.CreateNew(), AForge.Genetic.DoubleArrayChromosome.DoubleArrayChromosome(), and AForge.Genetic.DoubleArrayChromosome.Generate().
mutationMultiplierGenerator
IRandomNumberGenerator AForge.Genetic.DoubleArrayChromosome.mutationMultiplierGenerator protected
Mutation multiplier generator.
This random number generator is used to generate random multiplier values, which are used to multiply chromosome's genes during mutation.
Referenced by AForge.Genetic.DoubleArrayChromosome.CreateNew(), AForge.Genetic.DoubleArrayChromosome.DoubleArrayChromosome(), and AForge.Genetic.DoubleArrayChromosome.Mutate().
mutationAdditionGenerator
IRandomNumberGenerator AForge.Genetic.DoubleArrayChromosome.mutationAdditionGenerator protected
Mutation addition generator.
This random number generator is used to generate random addition values, which are used to add to chromosome's genes during mutation.
Referenced by AForge.Genetic.DoubleArrayChromosome.CreateNew(), AForge.Genetic.DoubleArrayChromosome.DoubleArrayChromosome(), and AForge.Genetic.DoubleArrayChromosome.Mutate().
rand
ThreadSafeRandom AForge.Genetic.DoubleArrayChromosome.rand = new ThreadSafeRandom() static protected
Random number generator for crossover and mutation points selection.
This random number generator is used to select crossover and mutation points.
Referenced by AForge.Genetic.DoubleArrayChromosome.Crossover(), and AForge.Genetic.DoubleArrayChromosome.Mutate().
MaxLength
const int AForge.Genetic.DoubleArrayChromosome.MaxLength = 65536 static
Chromosome's maximum length.
Maxim chromosome's length in array elements.
Referenced by AForge.Genetic.DoubleArrayChromosome.DoubleArrayChromosome().
length
int AForge.Genetic.DoubleArrayChromosome.length private
Chromosome's length in number of elements.
Referenced by AForge.Genetic.DoubleArrayChromosome.CreateNew(), AForge.Genetic.DoubleArrayChromosome.Crossover(), AForge.Genetic.DoubleArrayChromosome.DoubleArrayChromosome(), AForge.Genetic.DoubleArrayChromosome.Generate(), AForge.Genetic.DoubleArrayChromosome.Mutate(), and AForge.Genetic.DoubleArrayChromosome.ToString().
val
double [] AForge.Genetic.DoubleArrayChromosome.val = null protected
Chromosome's value.
Referenced by AForge.Genetic.DoubleArrayChromosome.Crossover(), AForge.Genetic.DoubleArrayChromosome.DoubleArrayChromosome(), AForge.Genetic.DoubleArrayChromosome.Generate(), AForge.Genetic.DoubleArrayChromosome.Mutate(), and AForge.Genetic.DoubleArrayChromosome.ToString().
mutationBalancer
double AForge.Genetic.DoubleArrayChromosome.mutationBalancer = 0.5 private
Referenced by AForge.Genetic.DoubleArrayChromosome.DoubleArrayChromosome(), and AForge.Genetic.DoubleArrayChromosome.Mutate().
crossoverBalancer
double AForge.Genetic.DoubleArrayChromosome.crossoverBalancer = 0.5 private
Referenced by AForge.Genetic.DoubleArrayChromosome.Crossover(), and AForge.Genetic.DoubleArrayChromosome.DoubleArrayChromosome().
Property Documentation
Length
int AForge.Genetic.DoubleArrayChromosome.Length get
Chromosome's length.
Length of the chromosome in array elements.
Value
double [] AForge.Genetic.DoubleArrayChromosome.Value get
Chromosome's value.
Current value of the chromosome.
Referenced by AForge.Neuro.Learning.EvolutionaryLearning.RunEpoch().
MutationBalancer
double AForge.Genetic.DoubleArrayChromosome.MutationBalancer get set
Mutation balancer to control mutation type, [0, 1].
The property controls type of mutation, which is used more frequently. A radnom number is generated each time before doing mutation - if the random number is smaller than the specified balance value, then one mutation type is used, otherwse another. See Mutate method for more information.
Default value is set to 0.5.
CrossoverBalancer
double AForge.Genetic.DoubleArrayChromosome.CrossoverBalancer get set
Crossover balancer to control crossover type, [0, 1].
The property controls type of crossover, which is used more frequently. A radnom number is generated each time before doing crossover - if the random number is smaller than the specified balance value, then one crossover type is used, otherwse another. See Crossover method for more information.
Default value is set to 0.5.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Genetic/Chromosomes/DoubleArrayChromosome.cs