Doc: IGLib EXTENDED: NUnit.Common.Tests.TestSelectionParserTests Class Reference
NUnit.Common.Tests.TestSelectionParserTests Class Reference
Public Member Functions
void CreateParser ()
void TestParser (string input, string output)
void TestParser_InvalidInput (string input, Type type)
Private Attributes
TestSelectionParser _parser
Member Function Documentation
CreateParser()
void NUnit.Common.Tests.TestSelectionParserTests.CreateParser () inline
TestParser()
void NUnit.Common.Tests.TestSelectionParserTests.TestParser (string input, string output) inline
References NUnit.Framework.Assert.DoesNotThrow(), NUnit.Framework.Is.EqualTo(), NUnit.Common.TestSelectionParser.Parse(), and NUnit.Framework.Assert.That().
TestParser_InvalidInput()
void NUnit.Common.Tests.TestSelectionParserTests.TestParser_InvalidInput (string input, Type type) inline
References NUnit.Common.TestSelectionParser.Parse(), NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
Member Data Documentation
_parser
TestSelectionParser NUnit.Common.Tests.TestSelectionParserTests._parser private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/tests/TestSelectionParserTests.cs