Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLASQ2 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLASQ2 Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLASQ2 (DLAZQ3 dlazq3, DLASRT dlasrt, XERBLA xerbla, DLAMCH dlamch, ILAENV ilaenv)
DLASQ2 ()
void Run (int N, ref double[] Z, int offset_z, ref int INFO)
Private Attributes
DLAZQ3 _dlazq3
DLASRT _dlasrt
XERBLA _xerbla
DLAMCH _dlamch
ILAENV _ilaenv
Static Private Attributes
const double CBIAS = 1.50E0
const double ZERO = 0.0E0
const double HALF = 0.5E0
const double ONE = 1.0E0
const double TWO = 2.0E0
const double FOUR = 4.0E0
const double HUNDRD = 100.0E0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLASQ2 computes all the eigenvalues of the symmetric positive definite tridiagonal matrix associated with the qd array Z to high relative accuracy are computed to high relative accuracy, in the absence of denormalization, underflow and overflow.
To see the relation of Z to the tridiagonal matrix, let L be a unit lower bidiagonal matrix with subdiagonals Z(2,4,6,,..) and let U be an upper bidiagonal matrix with 1's above and diagonal Z(1,3,5,,..). The tridiagonal is L*U or, if you prefer, the symmetric tridiagonal to which it is similar.
Note : DLASQ2 defines a logical variable, IEEE, which is true on machines which follow ieee-754 floating-point standard in their handling of infinities and NaNs, and false otherwise. This variable is passed to DLAZQ3.
/summary>
Constructor & Destructor Documentation
DLASQ2() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLASQ2.DLASQ2 (DLAZQ3 dlazq3, DLASRT dlasrt, XERBLA xerbla, DLAMCH dlamch, ILAENV ilaenv) inline
DLASQ2() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLASQ2.DLASQ2 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLASQ2.Run (int N, ref double[] Z, int offset_z, ref int INFO) inline
Purpose
DLASQ2 computes all the eigenvalues of the symmetric positive definite tridiagonal matrix associated with the qd array Z to high relative accuracy are computed to high relative accuracy, in the absence of denormalization, underflow and overflow.
To see the relation of Z to the tridiagonal matrix, let L be a unit lower bidiagonal matrix with subdiagonals Z(2,4,6,,..) and let U be an upper bidiagonal matrix with 1's above and diagonal Z(1,3,5,,..). The tridiagonal is L*U or, if you prefer, the symmetric tridiagonal to which it is similar.
Note : DLASQ2 defines a logical variable, IEEE, which is true on machines which follow ieee-754 floating-point standard in their handling of infinities and NaNs, and false otherwise. This variable is passed to DLAZQ3.
/summary>
Parameters
N (input) INTEGER The number of rows and columns in the matrix. N .GE. 0. /param>
Parameters
Z (workspace) DOUBLE PRECISION array, dimension (4*N) On entry Z holds the qd array. On exit, entries 1 to N hold the eigenvalues in decreasing order, Z(2*N+1) holds the trace, and Z(2*N+2) holds the sum of the eigenvalues. If N .GT. 2, then Z(2*N+3) holds the iteration count, Z(2*N+4) holds NDIVS/NIN^2, and Z(2*N+5) holds the percentage of shifts that failed. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if the i-th argument is a scalar and had an illegal value, then INFO = -i, if the i-th argument is an array and the j-entry had an illegal value, then INFO = -(i*100+j) .GT. 0: the algorithm failed = 1, a split was marked by a positive value in E = 2, current block of Z not diagonalized after 30*N iterations (in inner while loop) = 3, termination criterion of outer while loop not met (program created more than N unreduced blocks) /param>
References DotNumerics.LinearAlgebra.CSLapack.DLASQ2.CBIAS, DotNumerics.LinearAlgebra.CSLapack.DLASQ2.FOUR, DotNumerics.LinearAlgebra.CSLapack.DLASQ2.HALF, DotNumerics.LinearAlgebra.CSLapack.DLASQ2.HUNDRD, DotNumerics.LinearAlgebra.CSLapack.DLASQ2.ONE, DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASRT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASQ2.TWO, and DotNumerics.LinearAlgebra.CSLapack.DLASQ2.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASQ1.Run().
Member Data Documentation
_dlazq3
DLAZQ3 DotNumerics.LinearAlgebra.CSLapack.DLASQ2._dlazq3 private
_dlasrt
DLASRT DotNumerics.LinearAlgebra.CSLapack.DLASQ2._dlasrt private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLASQ2._xerbla private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLASQ2._dlamch private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DLASQ2._ilaenv private
CBIAS
const double DotNumerics.LinearAlgebra.CSLapack.DLASQ2.CBIAS = 1.50E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASQ2.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLASQ2.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASQ2.Run().
HALF
const double DotNumerics.LinearAlgebra.CSLapack.DLASQ2.HALF = 0.5E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASQ2.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLASQ2.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASQ2.Run().
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DLASQ2.TWO = 2.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASQ2.Run().
FOUR
const double DotNumerics.LinearAlgebra.CSLapack.DLASQ2.FOUR = 4.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASQ2.Run().
HUNDRD
const double DotNumerics.LinearAlgebra.CSLapack.DLASQ2.HUNDRD = 100.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASQ2.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlasq2.cs