Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DORMQR Class Reference
DotNumerics.LinearAlgebra.CSLapack.DORMQR Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DORMQR (LSAME lsame, ILAENV ilaenv, DLARFB dlarfb, DLARFT dlarft, DORM2R dorm2r, XERBLA xerbla)
DORMQR ()
void Run (string SIDE, string TRANS, int M, int N, int K, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
LSAME _lsame
ILAENV _ilaenv
DLARFB _dlarfb
DLARFT _dlarft
DORM2R _dorm2r
XERBLA _xerbla
double[] T = new double[LDT * NBMAX]
Static Private Attributes
const int NBMAX = 64
const int LDT = NBMAX + 1
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DORMQR overwrites the general real M-by-N matrix C with
SIDE = 'L' SIDE = 'R' TRANS = 'N': Q * C C * Q TRANS = 'T': Q**T * C C * Q**T
where Q is a real orthogonal matrix defined as the product of k elementary reflectors
Q = H(1) H(2) . . . H(k)
as returned by DGEQRF. Q is of order M if SIDE = 'L' and of order N if SIDE = 'R'.
/summary>
Constructor & Destructor Documentation
DORMQR() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DORMQR.DORMQR (LSAME lsame, ILAENV ilaenv, DLARFB dlarfb, DLARFT dlarft, DORM2R dorm2r, XERBLA xerbla) inline
DORMQR() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DORMQR.DORMQR () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DORMQR.Run (string SIDE, string TRANS, int M, int N, int K, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DORMQR overwrites the general real M-by-N matrix C with
SIDE = 'L' SIDE = 'R' TRANS = 'N': Q * C C * Q TRANS = 'T': Q**T * C C * Q**T
where Q is a real orthogonal matrix defined as the product of k elementary reflectors
Q = H(1) H(2) . . . H(k)
as returned by DGEQRF. Q is of order M if SIDE = 'L' and of order N if SIDE = 'R'.
/summary>
Parameters
SIDE = 'L' SIDE = 'R' /param>
Parameters
TRANS (input) CHARACTER*1 = 'N': No transpose, apply Q; = 'T': Transpose, apply Q**T. /param>
Parameters
M (input) INTEGER The number of rows of the matrix C. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix C. N .GE. 0. /param>
Parameters
K (input) INTEGER The number of elementary reflectors whose product defines the matrix Q. If SIDE = 'L', M .GE. K .GE. 0; if SIDE = 'R', N .GE. K .GE. 0. /param>
Parameters
A (input) DOUBLE PRECISION array, dimension (LDA,K) The i-th column must contain the vector which defines the elementary reflector H(i), for i = 1,2,...,k, as returned by DGEQRF in the first k columns of its array argument A. A is modified by the routine but restored on exit. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. If SIDE = 'L', LDA .GE. max(1,M); if SIDE = 'R', LDA .GE. max(1,N). /param>
Parameters
TAU (input) DOUBLE PRECISION array, dimension (K) TAU(i) must contain the scalar factor of the elementary reflector H(i), as returned by DGEQRF. /param>
Parameters
C (input/output) DOUBLE PRECISION array, dimension (LDC,N) On entry, the M-by-N matrix C. On exit, C is overwritten by Q*C or Q**T*C or C*Q**T or C*Q. /param>
Parameters
LDC (input) INTEGER The leading dimension of the array C. LDC .GE. max(1,M). /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. If SIDE = 'L', LWORK .GE. max(1,N); if SIDE = 'R', LWORK .GE. max(1,M). For optimum performance LWORK .GE. N*NB if SIDE = 'L', and LWORK .GE. M*NB if SIDE = 'R', where NB is the optimal blocksize.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.DORMQR.LDT, DotNumerics.LinearAlgebra.CSLapack.DORMQR.NBMAX, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFT.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFB.Run(), DotNumerics.LinearAlgebra.CSLapack.DORM2R.Run(), and DotNumerics.LinearAlgebra.CSLapack.DORMQR.T.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEQP3.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMTR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGQRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMBR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGLSE.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGGLM.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELS.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELSY.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGELSD.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DORMQR._lsame private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DORMQR._ilaenv private
_dlarfb
DLARFB DotNumerics.LinearAlgebra.CSLapack.DORMQR._dlarfb private
_dlarft
DLARFT DotNumerics.LinearAlgebra.CSLapack.DORMQR._dlarft private
_dorm2r
DORM2R DotNumerics.LinearAlgebra.CSLapack.DORMQR._dorm2r private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DORMQR._xerbla private
NBMAX
const int DotNumerics.LinearAlgebra.CSLapack.DORMQR.NBMAX = 64 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORMQR.Run().
LDT
const int DotNumerics.LinearAlgebra.CSLapack.DORMQR.LDT = NBMAX + 1 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORMQR.Run().
T
double [] DotNumerics.LinearAlgebra.CSLapack.DORMQR.T = new double[LDT * NBMAX] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORMQR.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dormqr.cs