Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLARZB Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLARZB Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLARZB (LSAME lsame, DCOPY dcopy, DGEMM dgemm, DTRMM dtrmm, XERBLA xerbla)
DLARZB ()
void Run (string SIDE, string TRANS, string DIRECT, string STOREV, int M, int N, int K, int L, double[] V, int offset_v, int LDV, double[] T, int offset_t, int LDT, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work, int LDWORK)
Private Attributes
LSAME _lsame
DCOPY _dcopy
DGEMM _dgemm
DTRMM _dtrmm
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLARZB applies a real block reflector H or its transpose H**T to a real distributed M-by-N C from the left or the right.
Currently, only STOREV = 'R' and DIRECT = 'B' are supported.
/summary>
Constructor & Destructor Documentation
DLARZB() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLARZB.DLARZB (LSAME lsame, DCOPY dcopy, DGEMM dgemm, DTRMM dtrmm, XERBLA xerbla) inline
DLARZB() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLARZB.DLARZB () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLARZB.Run (string SIDE, string TRANS, string DIRECT, string STOREV, int M, int N, int K, int L, double[] V, int offset_v, int LDV, double[] T, int offset_t, int LDT, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work, int LDWORK) inline
Purpose
DLARZB applies a real block reflector H or its transpose H**T to a real distributed M-by-N C from the left or the right.
Currently, only STOREV = 'R' and DIRECT = 'B' are supported.
/summary>
Parameters
SIDE (input) CHARACTER*1 = 'L': apply H or H' from the Left = 'R': apply H or H' from the Right /param>
Parameters
TRANS (input) CHARACTER*1 = 'N': apply H (No transpose) = 'C': apply H' (Transpose) /param>
Parameters
DIRECT (input) CHARACTER*1 Indicates how H is formed from a product of elementary reflectors = 'F': H = H(1) H(2) . . . H(k) (Forward, not supported yet) = 'B': H = H(k) . . . H(2) H(1) (Backward) /param>
Parameters
STOREV (input) CHARACTER*1 Indicates how the vectors which define the elementary reflectors are stored: = 'C': Columnwise (not supported yet) = 'R': Rowwise /param>
Parameters
M (input) INTEGER The number of rows of the matrix C. /param>
Parameters
N (input) INTEGER The number of columns of the matrix C. /param>
Parameters
K (input) INTEGER The order of the matrix T (= the number of elementary reflectors whose product defines the block reflector). /param>
Parameters
L (input) INTEGER The number of columns of the matrix V containing the meaningful part of the Householder reflectors. If SIDE = 'L', M .GE. L .GE. 0, if SIDE = 'R', N .GE. L .GE. 0. /param>
Parameters
V (input) DOUBLE PRECISION array, dimension (LDV,NV). If STOREV = 'C', NV = K; if STOREV = 'R', NV = L. /param>
Parameters
LDV (input) INTEGER The leading dimension of the array V. If STOREV = 'C', LDV .GE. L; if STOREV = 'R', LDV .GE. K. /param>
Parameters
T (input) DOUBLE PRECISION array, dimension (LDT,K) The triangular K-by-K matrix T in the representation of the block reflector. /param>
Parameters
LDT (input) INTEGER The leading dimension of the array T. LDT .GE. K. /param>
Parameters
C (input/output) DOUBLE PRECISION array, dimension (LDC,N) On entry, the M-by-N matrix C. On exit, C is overwritten by H*C or H'*C or C*H or C*H'. /param>
Parameters
LDC (input) INTEGER The leading dimension of the array C. LDC .GE. max(1,M). /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (LDWORK,K) /param>
Parameters
LDWORK (input) INTEGER The leading dimension of the array WORK. If SIDE = 'L', LDWORK .GE. max(1,N); if SIDE = 'R', LDWORK .GE. max(1,M). /param>
References DotNumerics.FortranLibrary.FortranLib.Copy(), DotNumerics.LinearAlgebra.CSLapack.DLARZB.ONE, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), and DotNumerics.LinearAlgebra.CSLapack.DTRMM.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTZRZF.Run(), and DotNumerics.LinearAlgebra.CSLapack.DORMRZ.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLARZB._lsame private
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLARZB._dcopy private
_dgemm
DGEMM DotNumerics.LinearAlgebra.CSLapack.DLARZB._dgemm private
_dtrmm
DTRMM DotNumerics.LinearAlgebra.CSLapack.DLARZB._dtrmm private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLARZB._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLARZB.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLARZB.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlarzb.cs