var searchData=
[
  ['labyrinthtexture_36625',['LabyrinthTexture',['../d3/d24/classAForge_1_1Imaging_1_1Textures_1_1LabyrinthTexture.html',1,'AForge::Imaging::Textures']]],
  ['laguerre_36626',['laguerre',['../dc/dad/classalglib_1_1laguerre.html',1,'alglib']]],
  ['lanczostest_36627',['LanczosTest',['../d2/d5d/classTest_1_1LanczosTest.html',1,'Test']]],
  ['layer_36628',['Layer',['../d1/d23/classAForge_1_1Neuro_1_1Layer.html',1,'AForge.Neuro.Layer'],['../db/d81/classNeuronDotNet_1_1Core_1_1Layer.html',1,'NeuronDotNet.Core.Layer&lt; TNeuron &gt;']]],
  ['layer_3c_20activationneuron_20_3e_36629',['Layer&lt; ActivationNeuron &gt;',['../db/d81/classNeuronDotNet_1_1Core_1_1Layer.html',1,'NeuronDotNet::Core']]],
  ['layer_3c_20positionneuron_20_3e_36630',['Layer&lt; PositionNeuron &gt;',['../db/d81/classNeuronDotNet_1_1Core_1_1Layer.html',1,'NeuronDotNet::Core']]],
  ['layoutinitializer_36631',['LayoutInitializer',['../d0/d0a/classCShell_1_1Framework_1_1Controls_1_1LayoutInitializer.html',1,'CShell::Framework::Controls']]],
  ['layoutitembase_36632',['LayoutItemBase',['../d5/d57/classCShell_1_1Framework_1_1LayoutItemBase.html',1,'CShell::Framework']]],
  ['layoutitemviewconverter_36633',['LayoutItemViewConverter',['../da/d08/classCShell_1_1Framework_1_1Converters_1_1LayoutItemViewConverter.html',1,'CShell::Framework::Converters']]],
  ['lbfgs_36634',['lbfgs',['../da/d47/classAlgLib_1_1lbfgs.html',1,'AlgLib.lbfgs'],['../db/d6f/classlbfgs.html',1,'lbfgs']]],
  ['lbfgsreport_36635',['lbfgsreport',['../d0/da9/structAlgLib_1_1lbfgs_1_1lbfgsreport.html',1,'AlgLib.lbfgs.lbfgsreport'],['../d6/dd3/structlbfgs_1_1lbfgsreport.html',1,'lbfgs.lbfgsreport']]],
  ['lbfgsstate_36636',['lbfgsstate',['../d3/ddc/structlbfgs_1_1lbfgsstate.html',1,'lbfgs.lbfgsstate'],['../d9/dcd/structAlgLib_1_1lbfgs_1_1lbfgsstate.html',1,'AlgLib.lbfgs.lbfgsstate']]],
  ['lda_36637',['lda',['../de/d89/classalglib_1_1lda.html',1,'alglib']]],
  ['led_36638',['LED',['../d5/d4e/classAForge_1_1Video_1_1Ximea_1_1CameraParameter_1_1LED.html',1,'AForge::Video::Ximea::CameraParameter']]],
  ['leds_36639',['Leds',['../d3/d29/classAForge_1_1Robotics_1_1TeRK_1_1Qwerk_1_1Leds.html',1,'AForge::Robotics::TeRK::Qwerk']]],
  ['legendre_36640',['legendre',['../dd/d99/classalglib_1_1legendre.html',1,'alglib']]],
  ['lengthtest_36641',['LengthTest',['../d0/d90/classNUnit_1_1Framework_1_1Syntax_1_1LengthTest.html',1,'NUnit::Framework::Syntax']]],
  ['lessequalfixture_36642',['LessEqualFixture',['../d1/d7c/classNUnit_1_1Framework_1_1Assertions_1_1LessEqualFixture.html',1,'NUnit::Framework::Assertions']]],
  ['lessfixture_36643',['LessFixture',['../d4/dfd/classNUnit_1_1Framework_1_1Assertions_1_1LessFixture.html',1,'NUnit::Framework::Assertions']]],
  ['lessthanconstraint_36644',['LessThanConstraint',['../df/d48/classNUnit_1_1Framework_1_1Constraints_1_1LessThanConstraint.html',1,'NUnit::Framework::Constraints']]],
  ['lessthanconstrainttests_36645',['LessThanConstraintTests',['../df/d18/classNUnit_1_1Framework_1_1Constraints_1_1LessThanConstraintTests.html',1,'NUnit::Framework::Constraints']]],
  ['lessthanorequalconstraint_36646',['LessThanOrEqualConstraint',['../d2/d5a/classNUnit_1_1Framework_1_1Constraints_1_1LessThanOrEqualConstraint.html',1,'NUnit::Framework::Constraints']]],
  ['lessthanorequalconstrainttests_36647',['LessThanOrEqualConstraintTests',['../d6/d4e/classNUnit_1_1Framework_1_1Constraints_1_1LessThanOrEqualConstraintTests.html',1,'NUnit::Framework::Constraints']]],
  ['lessthanorequaltest_36648',['LessThanOrEqualTest',['../d9/d98/classNUnit_1_1Framework_1_1Syntax_1_1LessThanOrEqualTest.html',1,'NUnit::Framework::Syntax']]],
  ['lessthantest_36649',['LessThanTest',['../da/d73/classNUnit_1_1Framework_1_1Syntax_1_1LessThanTest.html',1,'NUnit::Framework::Syntax']]],
  ['levanormalgenerator_36650',['LevaNormalGenerator',['../d2/db3/classTest_1_1LevaNormalGenerator.html',1,'Test']]],
  ['levelofparallelismattribute_36651',['LevelOfParallelismAttribute',['../de/dbe/classNUnit_1_1Framework_1_1LevelOfParallelismAttribute.html',1,'NUnit::Framework']]],
  ['levelslinear_36652',['LevelsLinear',['../da/d12/classAForge_1_1Imaging_1_1Filters_1_1LevelsLinear.html',1,'AForge::Imaging::Filters']]],
  ['levelslinear16bpp_36653',['LevelsLinear16bpp',['../d6/dfe/classAForge_1_1Imaging_1_1Filters_1_1LevelsLinear16bpp.html',1,'AForge::Imaging::Filters']]],
  ['lightingdefinition_5f05_36654',['LightingDefinition_05',['../dd/d61/classIGLib_1_1Gr3D_1_1LightingDefinition__05.html',1,'IGLib::Gr3D']]],
  ['lightingdefinitionexamples_36655',['LightingDefinitionExamples',['../d0/d73/classIGLib_1_1Gr3D_1_1LightingDefinitionExamples.html',1,'IGLib::Gr3D']]],
  ['lightingdefinitionexamples_5f05_36656',['LightingDefinitionExamples_05',['../dc/de9/classIGLib_1_1Gr3D_1_1LightingDefinitionExamples__05.html',1,'IGLib::Gr3D']]],
  ['lightsource_36657',['LightSource',['../d8/d90/classIGLib_1_1Gr3D_1_1LightSource.html',1,'IGLib::Gr3D']]],
  ['limitedconcurrencyleveltaskscheduler_36658',['LimitedConcurrencyLevelTaskScheduler',['../db/dc2/classIG_1_1Test_1_1LimitedConcurrencyLevelTaskScheduler.html',1,'IG::Test']]],
  ['lincg_36659',['lincg',['../db/dbc/classalglib_1_1lincg.html',1,'alglib']]],
  ['lincgreport_36660',['lincgreport',['../db/df6/classalglib_1_1lincgreport.html',1,'alglib.lincgreport'],['../dc/dd7/classalglib_1_1lincg_1_1lincgreport.html',1,'alglib.lincg.lincgreport']]],
  ['lincgstate_36661',['lincgstate',['../d0/dda/classalglib_1_1lincgstate.html',1,'alglib.lincgstate'],['../dc/d2b/classalglib_1_1lincg_1_1lincgstate.html',1,'alglib.lincg.lincgstate']]],
  ['line_36662',['Line',['../da/de1/classAForge_1_1Math_1_1Geometry_1_1Line.html',1,'AForge::Math::Geometry']]],
  ['linear_36663',['Linear',['../d8/ddb/classIG_1_1Num_1_1Func_1_1Linear.html',1,'IG::Num::Func']]],
  ['linearbasis_36664',['LinearBasis',['../da/d4f/classIG_1_1Num_1_1LinearBasis.html',1,'IG::Num']]],
  ['linearbasissafer_36665',['LinearBasisSafer',['../d9/d57/classIG_1_1Num_1_1LinearBasisSafer.html',1,'IG::Num']]],
  ['linearfunction_36666',['LinearFunction',['../d3/da1/classNeuronDotNet_1_1Core_1_1LearningRateFunctions_1_1LinearFunction.html',1,'NeuronDotNet::Core::LearningRateFunctions']]],
  ['linearlayer_36667',['LinearLayer',['../dc/da8/classNeuronDotNet_1_1Core_1_1Backpropagation_1_1LinearLayer.html',1,'NeuronDotNet::Core::Backpropagation']]],
  ['linearmodel_36668',['linearmodel',['../d4/d3f/classalglib_1_1linearmodel.html',1,'alglib.linearmodel'],['../d6/d1a/classalglib_1_1linreg_1_1linearmodel.html',1,'alglib.linreg.linearmodel']]],
  ['linearsolverbase_36669',['LinearSolverBase',['../d1/d9a/classIG_1_1Num_1_1LinearSolverBase.html',1,'IG::Num']]],
  ['lineprimitive_36670',['LinePrimitive',['../df/d95/classIG_1_1Gr_1_1LinePrimitive.html',1,'IG::Gr']]],
  ['linesearchtestfunc_36671',['LineSearchTestFunc',['../da/d41/classIG_1_1Num_1_1LineSearchTestFunc.html',1,'IG::Num']]],
  ['linesegment_36672',['LineSegment',['../d4/d4c/classAForge_1_1Math_1_1Geometry_1_1LineSegment.html',1,'AForge::Math::Geometry']]],
  ['linesegmenttest_36673',['LineSegmentTest',['../d0/d1b/classAForge_1_1Math_1_1Geometry_1_1Tests_1_1LineSegmentTest.html',1,'AForge::Math::Geometry::Tests']]],
  ['linestraighteningoptimizer_36674',['LineStraighteningOptimizer',['../db/d3f/classAForge_1_1Math_1_1Geometry_1_1LineStraighteningOptimizer.html',1,'AForge::Math::Geometry']]],
  ['linestraighteningoptimizertest_36675',['LineStraighteningOptimizerTest',['../df/d43/classAForge_1_1Math_1_1Geometry_1_1Tests_1_1LineStraighteningOptimizerTest.html',1,'AForge::Math::Geometry::Tests']]],
  ['linetest_36676',['LineTest',['../d3/d78/classAForge_1_1Math_1_1Geometry_1_1Tests_1_1LineTest.html',1,'AForge::Math::Geometry::Tests']]],
  ['linguisticvariable_36677',['LinguisticVariable',['../d7/dbf/classAForge_1_1Fuzzy_1_1LinguisticVariable.html',1,'AForge::Fuzzy']]],
  ['linlsqr_36678',['linlsqr',['../d2/d30/classalglib_1_1linlsqr.html',1,'alglib']]],
  ['linlsqrreport_36679',['linlsqrreport',['../d3/dd9/classalglib_1_1linlsqrreport.html',1,'alglib.linlsqrreport'],['../d3/dfc/classalglib_1_1linlsqr_1_1linlsqrreport.html',1,'alglib.linlsqr.linlsqrreport']]],
  ['linlsqrstate_36680',['linlsqrstate',['../db/dfa/classalglib_1_1linlsqrstate.html',1,'alglib.linlsqrstate'],['../d3/d33/classalglib_1_1linlsqr_1_1linlsqrstate.html',1,'alglib.linlsqr.linlsqrstate']]],
  ['linmin_36681',['linmin',['../df/d27/classalglib_1_1linmin.html',1,'alglib']]],
  ['linminstate_36682',['linminstate',['../d9/d4f/classalglib_1_1linmin_1_1linminstate.html',1,'alglib::linmin']]],
  ['linreg_36683',['linreg',['../da/d92/classalglib_1_1linreg.html',1,'alglib']]],
  ['lissajouscurve3d_36684',['LissajousCurve3D',['../d7/dcb/classIGLib_1_1Gr3D_1_1LissajousCurve3D.html',1,'IGLib::Gr3D']]],
  ['lissajousknot3d_36685',['LissajousKnot3D',['../d7/ddc/classIGLib_1_1Gr3D_1_1LissajousKnot3D.html',1,'IGLib::Gr3D']]],
  ['list_36686',['List',['../d7/d49/classNUnit_1_1Framework_1_1List.html',1,'NUnit::Framework']]],
  ['list_3c_20disposableenumerator_3c_20t_20_3e_20_3e_36687',['List&lt; DisposableEnumerator&lt; T &gt; &gt;',['../d7/d49/classNUnit_1_1Framework_1_1List.html',1,'NUnit::Framework']]],
  ['list_3c_20featuretuple_20_3e_36688',['List&lt; FeatureTuple &gt;',['../d7/d49/classNUnit_1_1Framework_1_1List.html',1,'NUnit::Framework']]],
  ['list_3c_20nunit_3a_3aframework_3a_3aconstraints_3a_3aequalityadapter_20_3e_36689',['List&lt; NUnit::Framework::Constraints::EqualityAdapter &gt;',['../d7/d49/classNUnit_1_1Framework_1_1List.html',1,'NUnit::Framework']]],
  ['list_3c_20nunit_3a_3aframework_3a_3aconstraints_3a_3anunitequalitycomparer_3a_3afailurepoint_20_3e_36690',['List&lt; NUnit::Framework::Constraints::NUnitEqualityComparer::FailurePoint &gt;',['../d7/d49/classNUnit_1_1Framework_1_1List.html',1,'NUnit::Framework']]],
  ['list_3c_20nunit_3a_3aframework_3a_3ainterfaces_3a_3aiparameterdataprovider_20_3e_36691',['List&lt; NUnit::Framework::Interfaces::IParameterDataProvider &gt;',['../d7/d49/classNUnit_1_1Framework_1_1List.html',1,'NUnit::Framework']]],
  ['list_3c_20nunit_3a_3aframework_3a_3ainterfaces_3a_3aitest_20_3e_36692',['List&lt; NUnit::Framework::Interfaces::ITest &gt;',['../d7/d49/classNUnit_1_1Framework_1_1List.html',1,'NUnit::Framework']]],
  ['list_3c_20nunit_3a_3aframework_3a_3ainternal_3a_3acommands_3a_3asetupteardownitem_20_3e_36693',['List&lt; NUnit::Framework::Internal::Commands::SetUpTearDownItem &gt;',['../d7/d49/classNUnit_1_1Framework_1_1List.html',1,'NUnit::Framework']]],
  ['list_3c_20nunit_3a_3aframework_3a_3ainternal_3a_3acommands_3a_3atestactionitem_20_3e_36694',['List&lt; NUnit::Framework::Internal::Commands::TestActionItem &gt;',['../d7/d49/classNUnit_1_1Framework_1_1List.html',1,'NUnit::Framework']]],
  ['list_3c_20nunit_3a_3aframework_3a_3ainternal_3a_3aexecution_3a_3aworkitem_20_3e_36695',['List&lt; NUnit::Framework::Internal::Execution::WorkItem &gt;',['../d7/d49/classNUnit_1_1Framework_1_1List.html',1,'NUnit::Framework']]],
  ['list_3c_20nunit_3a_3aframework_3a_3ainternal_3a_3atestnamegenerator_3a_3anamefragment_20_3e_36696',['List&lt; NUnit::Framework::Internal::TestNameGenerator::NameFragment &gt;',['../d7/d49/classNUnit_1_1Framework_1_1List.html',1,'NUnit::Framework']]],
  ['list_3c_20nunit_3a_3aframework_3a_3aitestaction_20_3e_36697',['List&lt; NUnit::Framework::ITestAction &gt;',['../d7/d49/classNUnit_1_1Framework_1_1List.html',1,'NUnit::Framework']]],
  ['list_3c_20object_20_3e_36698',['List&lt; object &gt;',['../d7/d49/classNUnit_1_1Framework_1_1List.html',1,'NUnit::Framework']]],
  ['list_3c_20string_20_3e_36699',['List&lt; string &gt;',['../d7/d49/classNUnit_1_1Framework_1_1List.html',1,'NUnit::Framework']]],
  ['listcontentstests_36700',['ListContentsTests',['../d1/d34/classNUnit_1_1Framework_1_1Assertions_1_1ListContentsTests.html',1,'NUnit::Framework::Assertions']]],
  ['listdto_36701',['ListDto',['../dd/d74/classIG_1_1Lib_1_1ListDto.html',1,'IG.Lib.ListDto&lt; ElementType, ElementDtoType &gt;'],['../dd/d74/classIG_1_1Lib_1_1ListDto.html',1,'IG.Lib.ListDto&lt; ElementType, ElementBaseType, ElementDtoType &gt;']]],
  ['listdto_3c_20elementtype_2c_20elementtype_2c_20elementdtotype_20_3e_36702',['ListDto&lt; ElementType, ElementType, ElementDtoType &gt;',['../dd/d74/classIG_1_1Lib_1_1ListDto.html',1,'IG::Lib']]],
  ['listmapper_36703',['ListMapper',['../d2/d7b/classNUnit_1_1Framework_1_1ListMapper.html',1,'NUnit::Framework']]],
  ['livetest_36704',['LiveTest',['../da/da6/classNUnit_1_1Framework_1_1Attributes_1_1PairwiseTest_1_1LiveTest.html',1,'NUnit.Framework.Attributes.PairwiseTest.LiveTest'],['../d2/d9c/classNUnit_1_1Core_1_1Tests_1_1PairwiseTest_1_1LiveTest.html',1,'NUnit.Core.Tests.PairwiseTest.LiveTest']]],
  ['loadablerealfunctionbase_36705',['LoadableRealFunctionBase',['../db/d84/classIG_1_1Lib_1_1LoadableRealFunctionBase.html',1,'IG::Lib']]],
  ['loadablescalarfunctionbase_36706',['LoadableScalarFunctionBase',['../d5/d06/classIG_1_1Lib_1_1LoadableScalarFunctionBase.html',1,'IG::Lib']]],
  ['loadablescriptbase_36707',['LoadableScriptBase',['../d7/d15/classIG_1_1Lib_1_1LoadableScriptBase.html',1,'IG::Lib']]],
  ['loadablescriptexample_36708',['LoadableScriptExample',['../d4/d2e/classIG_1_1Script_1_1LoadableScriptExample.html',1,'IG::Script']]],
  ['loadablescriptinterpreterbase_36709',['LoadableScriptInterpreterBase',['../d6/d7c/classIG_1_1Lib_1_1LoadableScriptInterpreterBase.html',1,'IG::Lib']]],
  ['loadablescriptoptbase_36710',['LoadableScriptOptBase',['../d5/d05/classIG_1_1Lib_1_1LoadableScriptOptBase.html',1,'IG::Lib']]],
  ['loadablescriptoptderived_36711',['LoadableScriptOptDerived',['../d2/dae/classIG_1_1Lib_1_1LoadableScriptOptTest_1_1LoadableScriptOptDerived.html',1,'IG::Lib::LoadableScriptOptTest']]],
  ['loadablescriptoptshellbasecontrollable_36712',['LoadableScriptOptShellBaseControllable',['../d7/d31/classIG_1_1Lib_1_1LoadableScriptOptShellBaseControllable.html',1,'IG::Lib']]],
  ['loadablescriptopttest_36713',['LoadableScriptOptTest',['../d4/d57/classIG_1_1Lib_1_1LoadableScriptOptTest.html',1,'IG::Lib']]],
  ['loadablescriptrealfunctionbase_36714',['LoadableScriptRealFunctionBase',['../d0/d74/classIG_1_1Lib_1_1LoadableScriptRealFunctionBase.html',1,'IG::Lib']]],
  ['loadablescriptscalarfunctionbase_36715',['LoadableScriptScalarFunctionBase',['../d7/dba/classIG_1_1Lib_1_1LoadableScriptScalarFunctionBase.html',1,'IG::Lib']]],
  ['loadablescriptscalarfunctioncreator_36716',['LoadableScriptScalarFunctionCreator',['../de/dbd/classIG_1_1Script_1_1LoadableScriptScalarFunctionCreator.html',1,'IG::Script']]],
  ['loadablescriptshellbase_36717',['LoadableScriptShellBase',['../d6/d59/classIG_1_1Lib_1_1LoadableScriptShellBase.html',1,'IG::Lib']]],
  ['loadablescriptshellneural_36718',['LoadableScriptShellNeural',['../d1/d30/classIG_1_1Script_1_1LoadableScriptShellNeural.html',1,'IG::Script']]],
  ['loadablescriptshellneuralbase_36719',['LoadableScriptShellNeuralBase',['../dc/d0c/classIG_1_1Script_1_1LoadableScriptShellNeuralBase.html',1,'IG::Script']]],
  ['loadablescriptshellneuralit_36720',['LoadableScriptShellNeuralIT',['../d5/d3c/classIG_1_1Script_1_1LoadableScriptShellNeuralIT.html',1,'IG::Script']]],
  ['loadablescriptshellneuralitoriginalbase_36721',['LoadableScriptShellNeuralITOriginalBase',['../d8/dd6/classIG_1_1Script_1_1LoadableScriptShellNeuralITOriginalBase.html',1,'IG::Script']]],
  ['loadablescriptspecialfunctionbase_36722',['LoadableScriptSpecialFunctionBase',['../da/d52/classIG_1_1Script_1_1LoadableScriptSpecialFunctionBase.html',1,'IG::Script']]],
  ['loadtestsaction_36723',['LoadTestsAction',['../d3/d02/classNUnit_1_1Framework_1_1Api_1_1FrameworkController_1_1LoadTestsAction.html',1,'NUnit::Framework::Api::FrameworkController']]],
  ['localizationexample_36724',['LocalizationExample',['../d0/dee/classIG_1_1Lib_1_1StringParser_1_1LocalizationExample.html',1,'IG::Lib::StringParser']]],
  ['localtestrunner_36725',['LocalTestRunner',['../d1/d77/classNUnit_1_1Engine_1_1Runners_1_1LocalTestRunner.html',1,'NUnit::Engine::Runners']]],
  ['logarithmlayer_36726',['LogarithmLayer',['../dd/daf/classNeuronDotNet_1_1Core_1_1Backpropagation_1_1LogarithmLayer.html',1,'NeuronDotNet::Core::Backpropagation']]],
  ['logger_36727',['Logger',['../d7/df0/classIG_1_1Lib_1_1Logger.html',1,'IG.Lib.Logger'],['../d3/d26/classNUnit_1_1Common_1_1Logger.html',1,'NUnit.Common.Logger']]],
  ['logisticdistribution_36728',['LogisticDistribution',['../d8/d95/classMeta_1_1Numerics_1_1Statistics_1_1Distributions_1_1LogisticDistribution.html',1,'Meta::Numerics::Statistics::Distributions']]],
  ['logit_36729',['logit',['../d0/d5c/classalglib_1_1logit.html',1,'alglib']]],
  ['logitmcstate_36730',['logitmcstate',['../d7/d75/classalglib_1_1logit_1_1logitmcstate.html',1,'alglib::logit']]],
  ['logitmodel_36731',['logitmodel',['../df/d34/classalglib_1_1logitmodel.html',1,'alglib.logitmodel'],['../d4/d40/classalglib_1_1logit_1_1logitmodel.html',1,'alglib.logit.logitmodel']]],
  ['lognormaldistribution_36732',['LognormalDistribution',['../df/d29/classMeta_1_1Numerics_1_1Statistics_1_1Distributions_1_1LognormalDistribution.html',1,'Meta::Numerics::Statistics::Distributions']]],
  ['logrecord_36733',['LogRecord',['../d9/d76/classIG_1_1Lib_1_1LogRecord.html',1,'IG::Lib']]],
  ['longdatasource_36734',['LongDataSource',['../dc/da4/classNUnit_1_1Framework_1_1RandomAttribute_1_1LongDataSource.html',1,'NUnit::Framework::RandomAttribute']]],
  ['longlivedmarshalbyrefobject_36735',['LongLivedMarshalByRefObject',['../d8/d34/classNUnit_1_1Framework_1_1Compatibility_1_1LongLivedMarshalByRefObject.html',1,'NUnit::Framework::Compatibility']]],
  ['lrreport_36736',['lrreport',['../d2/d2a/classalglib_1_1lrreport.html',1,'alglib.lrreport'],['../d4/df3/classalglib_1_1linreg_1_1lrreport.html',1,'alglib.linreg.lrreport']]],
  ['lsame_36737',['LSAME',['../dd/dac/classDotNumerics_1_1LinearAlgebra_1_1CSLapack_1_1LSAME.html',1,'DotNumerics::LinearAlgebra::CSLapack']]],
  ['lsfit_36738',['lsfit',['../d3/d40/classalglib_1_1lsfit.html',1,'alglib']]],
  ['lsfitreport_36739',['lsfitreport',['../dc/d86/classalglib_1_1lsfitreport.html',1,'alglib.lsfitreport'],['../df/df3/classalglib_1_1lsfit_1_1lsfitreport.html',1,'alglib.lsfit.lsfitreport']]],
  ['lsfitstate_36740',['lsfitstate',['../d8/dd3/classalglib_1_1lsfitstate.html',1,'alglib.lsfitstate'],['../d4/d64/classalglib_1_1lsfit_1_1lsfitstate.html',1,'alglib.lsfit.lsfitstate']]],
  ['ludecomposition_36741',['LUDecomposition',['../db/dc0/classIG_1_1Num_1_1LUDecomposition.html',1,'IG.Num.LUDecomposition'],['../d5/dcc/classDotNetMatrix_1_1LUDecomposition.html',1,'DotNetMatrix.LUDecomposition'],['../dc/d76/classMeta_1_1Numerics_1_1Matrices_1_1LUDecomposition.html',1,'Meta.Numerics.Matrices.LUDecomposition']]],
  ['lut_36742',['LUT',['../db/d5d/classAForge_1_1Video_1_1Ximea_1_1CameraParameter_1_1LUT.html',1,'AForge::Video::Ximea::CameraParameter']]]
];
