Doc: IGLib EXTENDED: NUnit.Framework.Assertions.ConditionAssertTests Class Reference
NUnit.Framework.Assertions.ConditionAssertTests Class Reference
Public Member Functions
void IsTrue ()
void IsTrueNullable ()
void IsTrueFails ()
void IsTrueFailsForNullable (bool? actual, string expectedButWas)
void IsFalse ()
void IsFalseNullable ()
void IsFalseFails ()
void IsFalseFailsForNullable (bool? actual, string expectedButWas)
void IsNull ()
void IsNullFails ()
void IsNotNull ()
void IsNotNullFails ()
void IsNaN ()
void IsNaNFails ()
void IsEmpty ()
void IsEmptyFailsOnString ()
void IsEmptyFailsOnNullString ()
void IsEmptyFailsOnNonEmptyArray ()
void IsEmptyFailsOnNonEmptyIEnumerable ()
void IsNotEmpty ()
void IsNotEmptyFailsOnEmptyString ()
void IsNotEmptyFailsOnEmptyArray ()
void IsNotEmptyFailsOnEmptyIEnumerable ()
void IsNotEmptyFailsOnEmptyArrayList ()
void IsNotEmptyFailsOnEmptyHashTable ()
Member Function Documentation
IsTrue()
void NUnit.Framework.Assertions.ConditionAssertTests.IsTrue () inline
References NUnit.Framework.Assert.IsTrue().
IsTrueNullable()
void NUnit.Framework.Assertions.ConditionAssertTests.IsTrueNullable () inline
References NUnit.Framework.Assert.IsTrue().
IsTrueFails()
void NUnit.Framework.Assertions.ConditionAssertTests.IsTrueFails () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.IsTrue(), NUnit.Env.NewLine, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
IsTrueFailsForNullable()
void NUnit.Framework.Assertions.ConditionAssertTests.IsTrueFailsForNullable (bool? actual, string expectedButWas) inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.IsTrue(), NUnit.Env.NewLine, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
IsFalse()
void NUnit.Framework.Assertions.ConditionAssertTests.IsFalse () inline
References NUnit.Framework.Assert.IsFalse().
IsFalseNullable()
void NUnit.Framework.Assertions.ConditionAssertTests.IsFalseNullable () inline
References NUnit.Framework.Assert.IsFalse().
IsFalseFails()
void NUnit.Framework.Assertions.ConditionAssertTests.IsFalseFails () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.IsFalse(), NUnit.Env.NewLine, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
IsFalseFailsForNullable()
void NUnit.Framework.Assertions.ConditionAssertTests.IsFalseFailsForNullable (bool? actual, string expectedButWas) inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.IsFalse(), NUnit.Env.NewLine, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
IsNull()
void NUnit.Framework.Assertions.ConditionAssertTests.IsNull () inline
References NUnit.Framework.Assert.IsNull().
IsNullFails()
void NUnit.Framework.Assertions.ConditionAssertTests.IsNullFails () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.IsNull(), NUnit.Env.NewLine, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
IsNotNull()
void NUnit.Framework.Assertions.ConditionAssertTests.IsNotNull () inline
References NUnit.Framework.Assert.IsNotNull().
IsNotNullFails()
void NUnit.Framework.Assertions.ConditionAssertTests.IsNotNullFails () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.IsNotNull(), NUnit.Env.NewLine, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
IsNaN()
void NUnit.Framework.Assertions.ConditionAssertTests.IsNaN () inline
References NUnit.Framework.Assert.IsNaN().
IsNaNFails()
void NUnit.Framework.Assertions.ConditionAssertTests.IsNaNFails () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.IsNaN(), NUnit.Env.NewLine, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
IsEmpty()
void NUnit.Framework.Assertions.ConditionAssertTests.IsEmpty () inline
References NUnit.Framework.Assert.IsEmpty().
IsEmptyFailsOnString()
void NUnit.Framework.Assertions.ConditionAssertTests.IsEmptyFailsOnString () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.IsEmpty(), NUnit.Env.NewLine, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
IsEmptyFailsOnNullString()
void NUnit.Framework.Assertions.ConditionAssertTests.IsEmptyFailsOnNullString () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.IsEmpty(), NUnit.Env.NewLine, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
IsEmptyFailsOnNonEmptyArray()
void NUnit.Framework.Assertions.ConditionAssertTests.IsEmptyFailsOnNonEmptyArray () inline
References NUnit.Framework.Assert.IsEmpty(), NUnit.Env.NewLine, and NUnit.Framework.Assert.Throws().
IsEmptyFailsOnNonEmptyIEnumerable()
void NUnit.Framework.Assertions.ConditionAssertTests.IsEmptyFailsOnNonEmptyIEnumerable () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.IsEmpty(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
IsNotEmpty()
void NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmpty () inline
References NUnit.Framework.Assert.IsNotEmpty().
IsNotEmptyFailsOnEmptyString()
void NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyString () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.IsNotEmpty(), NUnit.Env.NewLine, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
IsNotEmptyFailsOnEmptyArray()
void NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyArray () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.IsNotEmpty(), NUnit.Env.NewLine, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
IsNotEmptyFailsOnEmptyIEnumerable()
void NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyIEnumerable () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.IsNotEmpty(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
IsNotEmptyFailsOnEmptyArrayList()
void NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyArrayList () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.IsNotEmpty(), NUnit.Env.NewLine, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
IsNotEmptyFailsOnEmptyHashTable()
void NUnit.Framework.Assertions.ConditionAssertTests.IsNotEmptyFailsOnEmptyHashTable () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.IsNotEmpty(), NUnit.Env.NewLine, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/ConditionAssertTests.cs