Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAMRG Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAMRG Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAMRG ()
void Run (int N1, int N2, double[] A, int offset_a, int DTRD1, int DTRD2, ref int[] INDEX, int offset_index)
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAMRG will create a permutation list which will merge the elements of A (which is composed of two independently sorted sets) into a single set which is sorted in ascending order.
/summary>
Constructor & Destructor Documentation
DLAMRG()
DotNumerics.LinearAlgebra.CSLapack.DLAMRG.DLAMRG () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAMRG.Run (int N1, int N2, double[] A, int offset_a, int DTRD1, int DTRD2, ref int[] INDEX, int offset_index) inline
Purpose
DLAMRG will create a permutation list which will merge the elements of A (which is composed of two independently sorted sets) into a single set which is sorted in ascending order.
/summary>
Parameters
N1 (input) INTEGER /param>
Parameters
N2 (input) INTEGER These arguements contain the respective lengths of the two sorted lists to be merged. /param>
Parameters
A (input) DOUBLE PRECISION array, dimension (N1+N2) The first N1 elements of A contain a list of numbers which are sorted in either ascending or descending order. Likewise for the final N2 elements. /param>
Parameters
DTRD1 (input) INTEGER /param>
Parameters
DTRD2 (input) INTEGER These are the strides to be taken through the array A. Allowable strides are 1 and -1. They indicate whether a subset of A is sorted in ascending (DTRDx = 1) or descending (DTRDx = -1) order. /param>
Parameters
INDEX (output) INTEGER array, dimension (N1+N2) On exit this array will contain a permutation such that if B(I) = A(INDEX(I)) for I=1,N1+N2, then B will be sorted in ascending order. /param>
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED1.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED8.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD1.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD7.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED7.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLASD6.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlamrg.cs