Doc: IGLib EXTENDED: NUnit.Framework.AssertionHelper Class Reference
NUnit.Framework.AssertionHelper Class Reference
AssertionHelper is an optional base class for user tests, allowing the use of shorter ids for constraints and asserts and avoiding conflict with the definition of Is, from which it inherits much of its behavior, in certain mock object frameworks.
Public Member Functions
void Expect (bool condition, string message, params object[] args)
Asserts that a condition is true. If the condition is false the method throws an AssertionException. Works Identically to Assert.That(bool, string, object[]).
void Expect (bool condition)
Asserts that a condition is true. If the condition is false the method throws an AssertionException. Works Identically to Assert.That(bool).
void Expect< TActual > (ActualValueDelegate< TActual > del, IResolveConstraint expr)
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure.
void Expect< TActual > (ActualValueDelegate< TActual > del, IResolveConstraint expr, string message, params object[] args)
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure.
void Expect (TestDelegate code, IResolveConstraint constraint)
Asserts that the code represented by a delegate throws an exception that satisfies the constraint provided.
ListMapper Map (ICollection original)
Returns a ListMapper based on a collection.
Public Member Functions inherited from NUnit.Framework.Constraints.ConstraintFactory
ResolvableConstraintExpression Property (string name)
Returns a new PropertyConstraintExpression, which will either test for the existence of the named property on the object being tested or apply any following constraint to that property.
ResolvableConstraintExpression Attribute (Type expectedType)
Returns a new AttributeConstraint checking for the presence of a particular attribute on an object.
ResolvableConstraintExpression Attribute< TExpected > ()
Returns a new AttributeConstraint checking for the presence of a particular attribute on an object.
EqualConstraint EqualTo (object expected)
Returns a constraint that tests two items for equality
SameAsConstraint SameAs (object expected)
Returns a constraint that tests that two references are the same object
GreaterThanConstraint GreaterThan (object expected)
Returns a constraint that tests whether the actual value is greater than the supplied argument
GreaterThanOrEqualConstraint GreaterThanOrEqualTo (object expected)
Returns a constraint that tests whether the actual value is greater than or equal to the supplied argument
GreaterThanOrEqualConstraint AtLeast (object expected)
Returns a constraint that tests whether the actual value is greater than or equal to the supplied argument
LessThanConstraint LessThan (object expected)
Returns a constraint that tests whether the actual value is less than the supplied argument
LessThanOrEqualConstraint LessThanOrEqualTo (object expected)
Returns a constraint that tests whether the actual value is less than or equal to the supplied argument
LessThanOrEqualConstraint AtMost (object expected)
Returns a constraint that tests whether the actual value is less than or equal to the supplied argument
ExactTypeConstraint TypeOf (Type expectedType)
Returns a constraint that tests whether the actual value is of the exact type supplied as an argument.
ExactTypeConstraint TypeOf< TExpected > ()
Returns a constraint that tests whether the actual value is of the exact type supplied as an argument.
InstanceOfTypeConstraint InstanceOf (Type expectedType)
Returns a constraint that tests whether the actual value is of the type supplied as an argument or a derived type.
InstanceOfTypeConstraint InstanceOf< TExpected > ()
Returns a constraint that tests whether the actual value is of the type supplied as an argument or a derived type.
AssignableFromConstraint AssignableFrom (Type expectedType)
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
AssignableFromConstraint AssignableFrom< TExpected > ()
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
AssignableToConstraint AssignableTo (Type expectedType)
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
AssignableToConstraint AssignableTo< TExpected > ()
Returns a constraint that tests whether the actual value is assignable from the type supplied as an argument.
CollectionEquivalentConstraint EquivalentTo (IEnumerable expected)
Returns a constraint that tests whether the actual value is a collection containing the same elements as the collection supplied as an argument.
CollectionSubsetConstraint SubsetOf (IEnumerable expected)
Returns a constraint that tests whether the actual value is a subset of the collection supplied as an argument.
CollectionSupersetConstraint SupersetOf (IEnumerable expected)
Returns a constraint that tests whether the actual value is a superset of the collection supplied as an argument.
CollectionContainsConstraint Member (object expected)
Returns a new CollectionContainsConstraint checking for the presence of a particular object in the collection.
CollectionContainsConstraint Contains (object expected)
Returns a new CollectionContainsConstraint checking for the presence of a particular object in the collection.
ContainsConstraint Contains (string expected)
Returns a new ContainsConstraint. This constraint will, in turn, make use of the appropriate second-level constraint, depending on the type of the actual argument. This overload is only used if the item sought is a string, since any other type implies that we are looking for a collection member.
SubstringConstraint StringContaining (string expected)
Returns a constraint that succeeds if the actual value contains the substring supplied as an argument.
SubstringConstraint ContainsSubstring (string expected)
Returns a constraint that succeeds if the actual value contains the substring supplied as an argument.
SubstringConstraint DoesNotContain (string expected)
Returns a constraint that fails if the actual value contains the substring supplied as an argument.
StartsWithConstraint StartWith (string expected)
Returns a constraint that succeeds if the actual value starts with the substring supplied as an argument.
StartsWithConstraint StartsWith (string expected)
Returns a constraint that succeeds if the actual value starts with the substring supplied as an argument.
StartsWithConstraint StringStarting (string expected)
Returns a constraint that succeeds if the actual value starts with the substring supplied as an argument.
StartsWithConstraint DoesNotStartWith (string expected)
Returns a constraint that fails if the actual value starts with the substring supplied as an argument.
EndsWithConstraint EndWith (string expected)
Returns a constraint that succeeds if the actual value ends with the substring supplied as an argument.
EndsWithConstraint EndsWith (string expected)
Returns a constraint that succeeds if the actual value ends with the substring supplied as an argument.
EndsWithConstraint StringEnding (string expected)
Returns a constraint that succeeds if the actual value ends with the substring supplied as an argument.
EndsWithConstraint DoesNotEndWith (string expected)
Returns a constraint that fails if the actual value ends with the substring supplied as an argument.
RegexConstraint Match (string pattern)
Returns a constraint that succeeds if the actual value matches the regular expression supplied as an argument.
RegexConstraint Matches (string pattern)
Returns a constraint that succeeds if the actual value matches the regular expression supplied as an argument.
RegexConstraint StringMatching (string pattern)
Returns a constraint that succeeds if the actual value matches the regular expression supplied as an argument.
RegexConstraint DoesNotMatch (string pattern)
Returns a constraint that fails if the actual value matches the pattern supplied as an argument.
SamePathConstraint SamePath (string expected)
Returns a constraint that tests whether the path provided is the same as an expected path after canonicalization.
SubPathConstraint SubPathOf (string expected)
Returns a constraint that tests whether the path provided is a subpath of the expected path after canonicalization.
SamePathOrUnderConstraint SamePathOrUnder (string expected)
Returns a constraint that tests whether the path provided is the same path or under an expected path after canonicalization.
RangeConstraint InRange (IComparable from, IComparable to)
Returns a constraint that tests whether the actual value falls within a specified range.
Static Public Member Functions
static void Expect< TActual > (TActual actual, IResolveConstraint expression)
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure.
static void Expect< TActual > (TActual actual, IResolveConstraint expression, string message, params object[] args)
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure.
Static Public Member Functions inherited from NUnit.Framework.Constraints.ConstraintFactory
static ConstraintExpression Exactly (int expectedCount)
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding only if a specified number of them succeed.
Additional Inherited Members
Properties inherited from NUnit.Framework.Constraints.ConstraintFactory
ConstraintExpression Not [get]
Returns a ConstraintExpression that negates any following constraint.
ConstraintExpression No [get]
Returns a ConstraintExpression that negates any following constraint.
ConstraintExpression All [get]
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if all of them succeed.
ConstraintExpression Some [get]
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if at least one of them succeeds.
ConstraintExpression None [get]
Returns a ConstraintExpression, which will apply the following constraint to all members of a collection, succeeding if all of them fail.
ResolvableConstraintExpression Length [get]
Returns a new ConstraintExpression, which will apply the following constraint to the Length property of the object being tested.
ResolvableConstraintExpression Count [get]
Returns a new ConstraintExpression, which will apply the following constraint to the Count property of the object being tested.
ResolvableConstraintExpression Message [get]
Returns a new ConstraintExpression, which will apply the following constraint to the Message property of the object being tested.
ResolvableConstraintExpression InnerException [get]
Returns a new ConstraintExpression, which will apply the following constraint to the InnerException property of the object being tested.
NullConstraint Null [get]
Returns a constraint that tests for null
TrueConstraint True [get]
Returns a constraint that tests for True
FalseConstraint False [get]
Returns a constraint that tests for False
GreaterThanConstraint Positive [get]
Returns a constraint that tests for a positive value
LessThanConstraint Negative [get]
Returns a constraint that tests for a negative value
NaNConstraint NaN [get]
Returns a constraint that tests for NaN
EmptyConstraint Empty [get]
Returns a constraint that tests for empty
UniqueItemsConstraint Unique [get]
Returns a constraint that tests whether a collection contains all unique items.
BinarySerializableConstraint BinarySerializable [get]
Returns a constraint that tests whether an object graph is serializable in binary format.
XmlSerializableConstraint XmlSerializable [get]
Returns a constraint that tests whether an object graph is serializable in xml format.
CollectionOrderedConstraint Ordered [get]
Returns a constraint that tests whether a collection is ordered
Detailed Description
AssertionHelper is an optional base class for user tests, allowing the use of shorter ids for constraints and asserts and avoiding conflict with the definition of Is, from which it inherits much of its behavior, in certain mock object frameworks.
Member Function Documentation
Expect() [1/3]
void NUnit.Framework.AssertionHelper.Expect (bool condition, string message, params object[] args) inline
Asserts that a condition is true. If the condition is false the method throws an AssertionException. Works Identically to Assert.That(bool, string, object[]).
Parameters
condition The evaluated condition
message The message to display if the condition is false
args Arguments to be used in formatting the message
References NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.AllItemsTests(), NUnit.Framework.Tests.AssertSyntaxTests.AndOperator(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayAndCollection(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayIsEqualToItself(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArrayOfIntAndArrayOfDouble(), NUnit.Framework.Assertions.ArrayNotEqualFixture.ArraysDeclaredAsDifferentTypes(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysDeclaredAsDifferentTypes(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfArrays(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfDecimal(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfDouble(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfInt(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfMixedTypes(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysOfString(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysPassedAsObjects(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysWithDifferentDimensionsMatchedAsCollection(), NUnit.Framework.Assertions.ArrayEqualsFixture.ArraysWithDifferentRanksComparedAsCollection(), NUnit.Framework.Tests.AssertSyntaxTests.AssignableFromTypeTests(), NUnit.Framework.Tests.AssertSyntaxTests.CollectionContainsTests(), NUnit.Framework.Tests.AssertSyntaxTests.CollectionEquivalenceTests(), NUnit.Framework.Tests.AssertSyntaxTests.ComparisonTests(), NUnit.Framework.Tests.AssertSyntaxTests.ComplexTests(), NUnit.Framework.Assertions.ArrayNotEqualFixture.DifferentLengthArrays(), NUnit.Framework.Internal.TextMessageWriterTests.DisplayStringDifferences(), NUnit.Framework.Internal.TextMessageWriterTests.DisplayStringDifferences_NoClipping(), NUnit.Framework.Assertions.ArrayEqualsFixture.DoubleDimensionedArrays(), NUnit.Framework.Tests.AssertSyntaxTests.EmptyCollectionTests(), NUnit.Framework.Tests.AssertSyntaxTests.EmptyStringTests(), NUnit.Framework.Tests.AssertSyntaxTests.EndsWithTests(), NUnit.Framework.Tests.AssertSyntaxTests.EqualIgnoringCaseTests(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTests(), NUnit.Framework.Tests.AssertSyntaxTests.EqualityTestsWithTolerance(), NUnit.Framework.Tests.AssertSyntaxTests.ExactTypeTests(), NUnit.Framework.Assertions.ArrayEqualsFixture.FiveDimensionedArrays(), NUnit.Framework.Tests.AssertSyntaxTests.InstanceOfTests(), NUnit.Framework.Tests.AssertSyntaxTests.IsFalse(), NUnit.Framework.Tests.AssertSyntaxTests.IsNaN(), NUnit.Framework.Tests.AssertSyntaxTests.IsNotNull(), NUnit.Framework.Tests.AssertSyntaxTests.IsNull(), NUnit.Framework.Tests.AssertSyntaxTests.IsTrue(), NUnit.Framework.Assertions.ArrayEqualsFixture.JaggedArrays(), NUnit.Framework.Tests.AssertSyntaxTests.NoItemTests(), NUnit.Framework.Tests.AssertSyntaxTests.NotOperator(), NUnit.Framework.Tests.AssertSyntaxTests.NotTests(), NUnit.Framework.Tests.AssertSyntaxTests.OrOperator(), NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests(), NUnit.Framework.Tests.AssertSyntaxTests.RegularExpressionTests(), NUnit.Framework.Assertions.ArrayNotEqualFixture.SameLengthDifferentContent(), NUnit.Framework.Tests.AssertSyntaxTests.SomeItemTests(), NUnit.Framework.Tests.AssertSyntaxTests.StartsWithTests(), NUnit.Framework.Tests.AssertSyntaxTests.SubsetTests(), NUnit.Framework.Tests.AssertSyntaxTests.SubstringTests(), NUnit.Framework.Assertions.ArrayEqualsFixture.TripleDimensionedArrays(), NUnit.Framework.Internal.TextMessageWriterTests.WriteMessageLine_EmbeddedZeroes(), and NUnit.Framework.Internal.TextMessageWriterTests.WriteMessageLine_EmbeddedZeroesAsArgs().
Expect() [2/3]
void NUnit.Framework.AssertionHelper.Expect (bool condition) inline
Asserts that a condition is true. If the condition is false the method throws an AssertionException. Works Identically to Assert.That(bool).
Parameters
condition The evaluated condition
References NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
Expect< TActual >() [1/4]
void NUnit.Framework.AssertionHelper.Expect< TActual > (ActualValueDelegate< TActual > del, IResolveConstraint expr) inline
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure.
Parameters
expr A Constraint expression to be applied
del An ActualValueDelegate returning the value to be tested
Expect< TActual >() [2/4]
void NUnit.Framework.AssertionHelper.Expect< TActual > (ActualValueDelegate< TActual > del, IResolveConstraint expr, string message, params object[] args) inline
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure.
Parameters
del An ActualValueDelegate returning the value to be tested
expr A Constraint expression to be applied
message The message that will be displayed on failure
args Arguments to be used in formatting the message
References NUnit.Framework.Assert.That().
Expect() [3/3]
void NUnit.Framework.AssertionHelper.Expect (TestDelegate code, IResolveConstraint constraint) inline
Asserts that the code represented by a delegate throws an exception that satisfies the constraint provided.
Parameters
code A TestDelegate to be executed
constraint A ThrowsConstraint used in the test
References NUnit.Framework.Assert.That().
Expect< TActual >() [3/4]
static void NUnit.Framework.AssertionHelper.Expect< TActual > (TActual actual, IResolveConstraint expression) inline static
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure.
Parameters
expression A Constraint to be applied
actual The actual value to test
References NUnit.Framework.Assert.That().
Expect< TActual >() [4/4]
static void NUnit.Framework.AssertionHelper.Expect< TActual > (TActual actual, IResolveConstraint expression, string message, params object[] args) inline static
Apply a constraint to an actual value, succeeding if the constraint is satisfied and throwing an assertion exception on failure.
Parameters
expression A Constraint expression to be applied
actual The actual value to test
message The message that will be displayed on failure
args Arguments to be used in formatting the message
References NUnit.Framework.Assert.That().
Map()
ListMapper NUnit.Framework.AssertionHelper.Map (ICollection original) inline
Returns a ListMapper based on a collection.
Parameters
original The original collection
Returns
Referenced by NUnit.Framework.Tests.AssertSyntaxTests.PropertyTests().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/AssertionHelper.cs