Doc: IGLib EXTENDED: IG.Test.TestMatrixDecompositonMathNet Class Reference
IG.Test.TestMatrixDecompositonMathNet Class Reference
Unit tests for matrix decompositions from MathDotNet library.
Public Member Functions
void AccessOutOfRangeMatrix1 ()
void LU_MathNet ()
Unit test for testing correctness of the LU decomposition of a matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
void Cholesky_MathNet ()
Unit test for testing correctness of the Cholesky (LLT) decomposition of a symmetric positive definite matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
void QR_MathNet ()
Unit test for testing correctness of the QR decomposition of a matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
void Eigen_MathNet ()
Unit test for testing correctness of the Cholesky (LLT) decomposition of a symmetric positive definite matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
void AccessOutOfRangeMatrix1 ()
void LU_MathNet ()
Unit test for testing correctness of the LU decomposition of a matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
void Cholesky_MathNet ()
Unit test for testing correctness of the Cholesky (LLT) decomposition of a symmetric positive definite matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
void QR_MathNet ()
Unit test for testing correctness of the QR decomposition of a matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
void Eigen_MathNet ()
Unit test for testing correctness of the Cholesky (LLT) decomposition of a symmetric positive definite matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
Detailed Description
Unit tests for matrix decompositions from MathDotNet library.
$A Igor Dec14;
Member Function Documentation
AccessOutOfRangeMatrix1() [1/2]
void IG.Test.TestMatrixDecompositonMathNet.AccessOutOfRangeMatrix1 () inline
References IG.Num.A.
LU_MathNet() [1/2]
void IG.Test.TestMatrixDecompositonMathNet.LU_MathNet () inline
Unit test for testing correctness of the LU decomposition of a matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
References IG.Num.A, IG.Num.MatrixBase.Multiply(), IG.Num.IVector< T >.Norm, IG.Num.MatrixBase.SetIdentity(), IG.Num.VectorBase.SetRandom(), IG.Num.MatrixBase.SetRandomInvertible(), IG.Num.MatrixBase.SetZero(), IG.Num.VectorBase.Subtract(), and IG.Num.MatrixBase.Subtract().
Cholesky_MathNet() [1/2]
void IG.Test.TestMatrixDecompositonMathNet.Cholesky_MathNet () inline
Unit test for testing correctness of the Cholesky (LLT) decomposition of a symmetric positive definite matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
References IG.Num.A, IG.Num.MatrixBase.IsSymmetric(), IG.Num.MatrixBase.Multiply(), IG.Num.IVector< T >.Norm, IG.Num.MatrixBase.SetIdentity(), IG.Num.VectorBase.SetRandom(), IG.Num.MatrixBase.SetRandomPositiveDefiniteSymmetric(), IG.Num.MatrixBase.SetZero(), IG.Num.VectorBase.Subtract(), and IG.Num.MatrixBase.Subtract().
QR_MathNet() [1/2]
void IG.Test.TestMatrixDecompositonMathNet.QR_MathNet () inline
Unit test for testing correctness of the QR decomposition of a matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
References IG.Num.A, IG.Num.MatrixBase.Multiply(), IG.Num.IVector< T >.Norm, IG.Num.MatrixBase.SetIdentity(), IG.Num.VectorBase.SetRandom(), IG.Num.MatrixBase.SetRandomInvertible(), IG.Num.MatrixBase.SetZero(), IG.Num.VectorBase.Subtract(), and IG.Num.MatrixBase.Subtract().
Eigen_MathNet() [1/2]
void IG.Test.TestMatrixDecompositonMathNet.Eigen_MathNet () inline
Unit test for testing correctness of the Cholesky (LLT) decomposition of a symmetric positive definite matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
References IG.Num.A, IG.Num.MatrixBase.IsSymmetric(), IG.Num.MatrixBase.Multiply(), IG.Num.IVector< T >.Norm, IG.Num.MatrixBase.SetIdentity(), IG.Num.VectorBase.SetRandom(), IG.Num.MatrixBase.SetRandomPositiveDefiniteSymmetric(), IG.Num.MatrixBase.SetZero(), IG.Num.VectorBase.Subtract(), and IG.Num.MatrixBase.Subtract().
AccessOutOfRangeMatrix1() [2/2]
void IG.Test.TestMatrixDecompositonMathNet.AccessOutOfRangeMatrix1 () inline
References IG.Num.A, and NUnit.Framework.Assert.Throws().
LU_MathNet() [2/2]
void IG.Test.TestMatrixDecompositonMathNet.LU_MathNet () inline
Unit test for testing correctness of the LU decomposition of a matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
References IG.Num.A, NUnit.Framework.Assert.AreEqual(), IG.Num.MatrixBase.Multiply(), IG.Num.IVector< T >.Norm, IG.Num.MatrixBase.SetIdentity(), IG.Num.VectorBase.SetRandom(), IG.Num.MatrixBase.SetRandomInvertible(), IG.Num.MatrixBase.SetZero(), IG.Num.VectorBase.Subtract(), and IG.Num.MatrixBase.Subtract().
Cholesky_MathNet() [2/2]
void IG.Test.TestMatrixDecompositonMathNet.Cholesky_MathNet () inline
Unit test for testing correctness of the Cholesky (LLT) decomposition of a symmetric positive definite matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
References IG.Num.A, NUnit.Framework.Assert.AreEqual(), IG.Num.MatrixBase.IsSymmetric(), NUnit.Framework.Assert.IsTrue(), IG.Num.MatrixBase.Multiply(), IG.Num.IVector< T >.Norm, IG.Num.MatrixBase.SetIdentity(), IG.Num.VectorBase.SetRandom(), IG.Num.MatrixBase.SetRandomPositiveDefiniteSymmetric(), IG.Num.MatrixBase.SetZero(), IG.Num.VectorBase.Subtract(), and IG.Num.MatrixBase.Subtract().
QR_MathNet() [2/2]
void IG.Test.TestMatrixDecompositonMathNet.QR_MathNet () inline
Unit test for testing correctness of the QR decomposition of a matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
References IG.Num.A, NUnit.Framework.Assert.AreEqual(), IG.Num.MatrixBase.Multiply(), IG.Num.IVector< T >.Norm, IG.Num.MatrixBase.SetIdentity(), IG.Num.VectorBase.SetRandom(), IG.Num.MatrixBase.SetRandomInvertible(), IG.Num.MatrixBase.SetZero(), IG.Num.VectorBase.Subtract(), and IG.Num.MatrixBase.Subtract().
Eigen_MathNet() [2/2]
void IG.Test.TestMatrixDecompositonMathNet.Eigen_MathNet () inline
Unit test for testing correctness of the Cholesky (LLT) decomposition of a symmetric positive definite matrix and of operations performed with such decomposition (solution of system of equations, matrix inversion, determinant).
References IG.Num.A, NUnit.Framework.Assert.AreEqual(), IG.Num.MatrixBase.IsSymmetric(), NUnit.Framework.Assert.IsTrue(), IG.Num.MatrixBase.Multiply(), IG.Num.IVector< T >.Norm, IG.Num.MatrixBase.SetIdentity(), IG.Num.VectorBase.SetRandom(), IG.Num.MatrixBase.SetRandomPositiveDefiniteSymmetric(), IG.Num.MatrixBase.SetZero(), IG.Num.VectorBase.Subtract(), and IG.Num.MatrixBase.Subtract().
The documentation for this class was generated from the following file:
unittests/MSTests/TestNumeric/TstMatrixDecompositionMathNet.cs