Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGGGLM Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGGGLM Class Reference
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGGGLM (DCOPY dcopy, DGEMV dgemv, DGGQRF dggqrf, DORMQR dormqr, DORMRQ dormrq, DTRTRS dtrtrs, XERBLA xerbla, ILAENV ilaenv)
DGGGLM ()
void Run (int N, int M, int P, ref double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB, ref double[] D, int offset_d, ref double[] X, int offset_x, ref double[] Y, int offset_y, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
DCOPY _dcopy
DGEMV _dgemv
DGGQRF _dggqrf
DORMQR _dormqr
DORMRQ _dormrq
DTRTRS _dtrtrs
XERBLA _xerbla
ILAENV _ilaenv
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGGGLM solves a general Gauss-Markov linear model (GLM) problem:
minimize || y ||_2 subject to d = A*x + B*y x
where A is an N-by-M matrix, B is an N-by-P matrix, and d is a given N-vector. It is assumed that M .LE. N .LE. M+P, and
rank(A) = M and rank(A B) = N.
Under these assumptions, the constrained equation is always consistent, and there is a unique solution x and a minimal 2-norm solution y, which is obtained using a generalized QR factorization of the matrices (A, B) given by
A = Q*(R), B = Q*T*Z. (0)
In particular, if matrix B is square nonsingular, then the problem GLM is equivalent to the following weighted linear least squares problem
minimize || inv(B)*(d-A*x) ||_2 x
where inv(B) denotes the inverse of B.
/summary>
Constructor & Destructor Documentation
DGGGLM() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGGGLM.DGGGLM (DCOPY dcopy, DGEMV dgemv, DGGQRF dggqrf, DORMQR dormqr, DORMRQ dormrq, DTRTRS dtrtrs, XERBLA xerbla, ILAENV ilaenv) inline
DGGGLM() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGGGLM.DGGGLM () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGGGLM.Run (int N, int M, int P, ref double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB, ref double[] D, int offset_d, ref double[] X, int offset_x, ref double[] Y, int offset_y, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DGGGLM solves a general Gauss-Markov linear model (GLM) problem:
minimize || y ||_2 subject to d = A*x + B*y x
where A is an N-by-M matrix, B is an N-by-P matrix, and d is a given N-vector. It is assumed that M .LE. N .LE. M+P, and
rank(A) = M and rank(A B) = N.
Under these assumptions, the constrained equation is always consistent, and there is a unique solution x and a minimal 2-norm solution y, which is obtained using a generalized QR factorization of the matrices (A, B) given by
A = Q*(R), B = Q*T*Z. (0)
In particular, if matrix B is square nonsingular, then the problem GLM is equivalent to the following weighted linear least squares problem
minimize || inv(B)*(d-A*x) ||_2 x
where inv(B) denotes the inverse of B.
/summary>
Parameters
N (input) INTEGER The number of rows of the matrices A and B. N .GE. 0. /param>
Parameters
M (input) INTEGER The number of columns of the matrix A. 0 .LE. M .LE. N. /param>
Parameters
P (input) INTEGER The number of columns of the matrix B. P .GE. N-M. /param>
Parameters
A = Q*(R), B = Q*T*Z. (0) /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,N). /param>
Parameters
B (input/output) DOUBLE PRECISION array, dimension (LDB,P) On entry, the N-by-P matrix B. On exit, if N .LE. P, the upper triangle of the subarray B(1:N,P-N+1:P) contains the N-by-N upper triangular matrix T; if N .GT. P, the elements on and above the (N-P)th subdiagonal contain the N-by-P upper trapezoidal matrix T. /param>
Parameters
LDB (input) INTEGER The leading dimension of the array B. LDB .GE. max(1,N). /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension (N) On entry, D is the left hand side of the GLM equation. On exit, D is destroyed. /param>
Parameters
X (output) DOUBLE PRECISION array, dimension (M) /param>
Parameters
Y (output) DOUBLE PRECISION array, dimension (P) On exit, X and Y are the solutions of the GLM problem. /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. max(1,N+M+P). For optimum performance, LWORK .GE. M+min(N,P)+max(N,P)*NB, where NB is an upper bound for the optimal blocksizes for DGEQRF, SGERQF, DORMQR and SORMRQ.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. = 1: the upper triangular factor R associated with A in the generalized QR factorization of the pair (A, B) is singular, so that rank(A) .LT. M; the least squares solution could not be computed. = 2: the bottom (N-M) by (N-M) part of the upper trapezoidal factor T associated with B in the generalized QR factorization of the pair (A, B) is singular, so that rank(A B) .LT. N; the least squares solution could not be computed. /param>
References DotNumerics.LinearAlgebra.CSLapack.DGGGLM.ONE, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRTRS.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMRQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGQRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGGGLM.ZERO.
Member Data Documentation
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DGGGLM._dcopy private
_dgemv
DGEMV DotNumerics.LinearAlgebra.CSLapack.DGGGLM._dgemv private
_dggqrf
DGGQRF DotNumerics.LinearAlgebra.CSLapack.DGGGLM._dggqrf private
_dormqr
DORMQR DotNumerics.LinearAlgebra.CSLapack.DGGGLM._dormqr private
_dormrq
DORMRQ DotNumerics.LinearAlgebra.CSLapack.DGGGLM._dormrq private
_dtrtrs
DTRTRS DotNumerics.LinearAlgebra.CSLapack.DGGGLM._dtrtrs private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGGGLM._xerbla private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DGGGLM._ilaenv private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DGGGLM.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGGGLM.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGGGLM.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGGGLM.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dggglm.cs