Doc: IGLib EXTENDED: NUnit.Engine.Services.ProjectLoaders.VSSolution Class Reference
NUnit.Engine.Services.ProjectLoaders.VSSolution Class Reference
Classes
class SolutionConfig
Public Member Functions
VSSolution (string projectPath)
TestPackage GetTestPackage ()
Gets a test package for the primary or active configuration within the project. The package includes all the assemblies and any settings specified in the project format.
TestPackage GetTestPackage (string configName)
Gets a TestPackage for a specific configuration within the project. The package includes all the assemblies and any settings specified in the project format.
Properties
string ProjectPath [get, private set]
The path to the project
string? ActiveConfigName [get]
IList< string > ConfigNames [get]
Properties inherited from NUnit.Engine.Extensibility.IProject
string ProjectPath [get]
Gets the path to the file storing this project, if any. If the project has not been saved, this is null.
string ActiveConfigName [get]
Gets the active configuration, as defined by the particular project.
IList< string > ConfigNames [get]
Gets a list of the configs for this project
Private Member Functions
void Load ()
Private Attributes
IDictionary< string, VSProject > _projectLookup = new Dictionary<string, VSProject>()
IDictionary< string, SolutionConfig > _configs = new Dictionary<string, SolutionConfig>()
Static Private Attributes
static readonly char[] DELIMS = { '=', ',' }
static readonly char[] TRIM_CHARS = { ' ', '"' }
const string BUILD_MARKER = ".Build.0 ="
Constructor & Destructor Documentation
VSSolution()
NUnit.Engine.Services.ProjectLoaders.VSSolution.VSSolution (string projectPath) inline
References NUnit.Engine.Services.ProjectLoaders.VSSolution.Load(), and NUnit.Engine.Services.ProjectLoaders.VSSolution.ProjectPath.
Member Function Documentation
GetTestPackage() [1/2]
TestPackage NUnit.Engine.Services.ProjectLoaders.VSSolution.GetTestPackage () inline
Gets a test package for the primary or active configuration within the project. The package includes all the assemblies and any settings specified in the project format.
Returns
A TestPackage
Implements NUnit.Engine.Extensibility.IProject.
GetTestPackage() [2/2]
TestPackage NUnit.Engine.Services.ProjectLoaders.VSSolution.GetTestPackage (string configName) inline
Gets a TestPackage for a specific configuration within the project. The package includes all the assemblies and any settings specified in the project format.
Parameters
configName The name of the config to use
Returns
A TestPackage for the named configuration.
Implements NUnit.Engine.Extensibility.IProject.
References NUnit.Engine.Services.ProjectLoaders.VSSolution._configs.
Load()
void NUnit.Engine.Services.ProjectLoaders.VSSolution.Load () inline private
References NUnit.Engine.Services.ProjectLoaders.VSSolution._configs, NUnit.Engine.Services.ProjectLoaders.VSSolution._projectLookup, NUnit.Engine.Services.ProjectLoaders.VSSolution.BUILD_MARKER, NUnit.Engine.Services.ProjectLoaders.VSSolution.DELIMS, NUnit.Engine.Services.ProjectLoaders.VSProject.IsProjectFile(), NUnit.Engine.Services.ProjectLoaders.VSSolution.ProjectPath, and NUnit.Engine.Services.ProjectLoaders.VSSolution.TRIM_CHARS.
Referenced by NUnit.Engine.Services.ProjectLoaders.VSSolution.VSSolution().
Member Data Documentation
DELIMS
readonly char [] NUnit.Engine.Services.ProjectLoaders.VSSolution.DELIMS = { '=', ',' } static private
Referenced by NUnit.Engine.Services.ProjectLoaders.VSSolution.Load().
TRIM_CHARS
readonly char [] NUnit.Engine.Services.ProjectLoaders.VSSolution.TRIM_CHARS = { ' ', '"' } static private
Referenced by NUnit.Engine.Services.ProjectLoaders.VSSolution.Load().
BUILD_MARKER
const string NUnit.Engine.Services.ProjectLoaders.VSSolution.BUILD_MARKER = ".Build.0 =" static private
Referenced by NUnit.Engine.Services.ProjectLoaders.VSSolution.Load().
_projectLookup
IDictionary<string, VSProject> NUnit.Engine.Services.ProjectLoaders.VSSolution._projectLookup = new Dictionary<string, VSProject>() private
Referenced by NUnit.Engine.Services.ProjectLoaders.VSSolution.Load().
_configs
IDictionary<string, SolutionConfig> NUnit.Engine.Services.ProjectLoaders.VSSolution._configs = new Dictionary<string, SolutionConfig>() private
Referenced by NUnit.Engine.Services.ProjectLoaders.VSSolution.GetTestPackage(), and NUnit.Engine.Services.ProjectLoaders.VSSolution.Load().
Property Documentation
ProjectPath
string NUnit.Engine.Services.ProjectLoaders.VSSolution.ProjectPath get private set
The path to the project
Referenced by NUnit.Engine.Services.ProjectLoaders.VSSolution.Load(), and NUnit.Engine.Services.ProjectLoaders.VSSolution.VSSolution().
ActiveConfigName
string? NUnit.Engine.Services.ProjectLoaders.VSSolution.ActiveConfigName get
ConfigNames
IList<string> NUnit.Engine.Services.ProjectLoaders.VSSolution.ConfigNames get
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/Addins/vs-project-loader/VSSolution.cs