Doc: IGLib EXTENDED: AForge.Imaging.Textures.CloudsTexture Class Reference
AForge.Imaging.Textures.CloudsTexture Class Reference
Clouds texture.
Public Member Functions
CloudsTexture ()
Initializes a new instance of the CloudsTexture class.
float[,] Generate (int width, int height)
Generate texture.
void Reset ()
Reset generator.
Private Attributes
AForge.Math.PerlinNoise noise = new AForge.Math.PerlinNoise(8, 0.5, 1.0 / 32, 1.0)
Random rand = new Random()
int r
Detailed Description
Clouds texture.
The texture generator creates textures with effect of clouds.
The generator is based on the Perlin noise function.
Sample usage:
// create texture generator
CloudsTexture textureGenerator = new CloudsTexture();
// generate new texture
float[,] texture = textureGenerator.Generate(320, 240);
// convert it to image to visualize
Bitmap textureImage = TextureTools.ToBitmap(texture);
Result image:
Constructor & Destructor Documentation
CloudsTexture()
AForge.Imaging.Textures.CloudsTexture.CloudsTexture () inline
Initializes a new instance of the CloudsTexture class.
References AForge.Imaging.Textures.CloudsTexture.Reset().
Member Function Documentation
Generate()
float [,] AForge.Imaging.Textures.CloudsTexture.Generate (int width, int height) inline
Generate texture.
Parameters
width Texture's width.
height Texture's height.
Returns
Two dimensional array of intensities.
Generates new texture of the specified size.
Implements AForge.Imaging.Textures.ITextureGenerator.
References AForge.Math.PerlinNoise.Function2D(), AForge.Imaging.Textures.CloudsTexture.noise, and AForge.Imaging.Textures.CloudsTexture.r.
Reset()
void AForge.Imaging.Textures.CloudsTexture.Reset () inline
Reset generator.
Regenerates internal random numbers.
Implements AForge.Imaging.Textures.ITextureGenerator.
References AForge.Imaging.Textures.CloudsTexture.r, and AForge.Imaging.Textures.CloudsTexture.rand.
Referenced by AForge.Imaging.Textures.CloudsTexture.CloudsTexture().
Member Data Documentation
noise
AForge.Math.PerlinNoise AForge.Imaging.Textures.CloudsTexture.noise = new AForge.Math.PerlinNoise(8, 0.5, 1.0 / 32, 1.0) private
Referenced by AForge.Imaging.Textures.CloudsTexture.Generate().
rand
Random AForge.Imaging.Textures.CloudsTexture.rand = new Random() private
Referenced by AForge.Imaging.Textures.CloudsTexture.Reset().
r
int AForge.Imaging.Textures.CloudsTexture.r private
Referenced by AForge.Imaging.Textures.CloudsTexture.Generate(), and AForge.Imaging.Textures.CloudsTexture.Reset().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Textures/CloudsTexture.cs