Doc: IGLib EXTENDED: alglib.testhermiteunit Class Reference
alglib.testhermiteunit Class Reference
Static Public Member Functions
static bool testhermite (bool silent)
static bool testhermite (bool silent)
static bool _pexec_testhermite (bool silent)
Member Function Documentation
testhermite() [1/2]
static bool alglib.testhermiteunit.testhermite (bool silent) inline static
References alglib.hermite.hermitecalculate(), alglib.hermite.hermitecoefficients(), alglib.hermite.hermitesum(), and alglib.math.randomreal().
Referenced by alglib.testhermiteunit._pexec_testhermite(), and _Test.Main().
testhermite() [2/2]
static bool alglib.testhermiteunit.testhermite (bool silent) inline static
References alglib.hermite.hermitecalculate(), alglib.hermite.hermitecoefficients(), alglib.hermite.hermitesum(), and alglib.math.randomreal().
_pexec_testhermite()
static bool alglib.testhermiteunit._pexec_testhermite (bool silent) inline static
References alglib.testhermiteunit.testhermite().
Referenced by _Test.Main().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs