Doc: IGLib EXTENDED: IG.MPetekLib.Application.Scripts.NonlinearOscillator._15SolutionPlot Class Reference
IG.MPetekLib.Application.Scripts.NonlinearOscillator._15SolutionPlot Class Reference
Static Public Member Functions
static void Run (string[] arguments)
Member Function Documentation
Run()
static void IG.MPetekLib.Application.Scripts.NonlinearOscillator._15SolutionPlot.Run (string[] arguments) inline static
References IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenNonlinearOscillator.bOverJ, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenNonlinearOscillator.DOverJ, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.DrivingAngularFrequency, IG.MPetekLib.Algorithms.Solvers.InitialProblemODE_RK4.InitialProblemSolverBase.EndPoint, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.Gamma, IG.MPetekLib.Algorithms.PlottableModels.PlottableODEModelBase.InitialConditions, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenNonlinearOscillator.M0OverJ, IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase.NewCurveFromPlottableData(), IG.MPetekLib.Algorithms.PlottableModels.PlottableODEModelBase.SolveNumerically(), IG.MPetekLib.Algorithms.PlottableModels.PlottableODEModelBase.Solver, and IG.MPetekLib.Algorithms.Solvers.InitialProblemODE_RK4.InitialProblemSolverBase.StepSize.
Referenced by IG.Script.AppMarkoPetek.App15SolutionPlot().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/Guest_Marko_Petek_Lib/application/scripts/NonlinearOscillator/15SolutionPlot.cs