Doc: IGLib EXTENDED: IG.Forms.Utilities.Notification.NotificationWindow Class Reference
IG.Forms.Utilities.Notification.NotificationWindow Class Reference
Public Member Functions
NotificationWindow ()
NotificationWindow ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
NotificationPanel notificationPanel1
Constructor & Destructor Documentation
NotificationWindow() [1/2]
IG.Forms.Utilities.Notification.NotificationWindow.NotificationWindow () inline
References IG.Forms.Utilities.Notification.NotificationWindow.InitializeComponent().
NotificationWindow() [2/2]
IG.Forms.Utilities.Notification.NotificationWindow.NotificationWindow () inline
References IG.Forms.Utilities.Notification.NotificationWindow.InitializeComponent().
Member Function Documentation
Dispose() [1/2]
override void IG.Forms.Utilities.Notification.NotificationWindow.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.Utilities.Notification.NotificationWindow.components.
InitializeComponent() [1/2]
void IG.Forms.Utilities.Notification.NotificationWindow.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.NotificationPanel.BackgroundColor, IG.Forms.NotificationPanel.FadeColor, IG.Forms.NotificationPanel.FadingPortion, IG.Forms.NotificationPanel.FadingTime, IG.Forms.NotificationPanel.MessageColor, IG.Forms.NotificationPanel.NonFadingTime, IG.Forms.Utilities.Notification.NotificationWindow.notificationPanel1, IG.Forms.NotificationPanel.ShowTime, IG.Forms.NotificationPanel.ShowTmeMilliseconds, IG.Forms.NotificationPanel.TimerInterval, IG.Forms.NotificationPanel.TimerIntervalMilliseconds, IG.Forms.NotificationPanel.Title, IG.Forms.NotificationPanel.TitleColor, and IG.Forms.NotificationPanel.Type.
Referenced by IG.Forms.Utilities.Notification.NotificationWindow.NotificationWindow().
Dispose() [2/2]
override void IG.Forms.Utilities.Notification.NotificationWindow.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.Utilities.Notification.NotificationWindow.components.
InitializeComponent() [2/2]
void IG.Forms.Utilities.Notification.NotificationWindow.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.NotificationPanel.BackgroundColor, IG.Forms.NotificationPanel.FadeColor, IG.Forms.NotificationPanel.FadingPortion, IG.Forms.NotificationPanel.FadingTime, IG.Forms.NotificationPanel.MessageColor, IG.Forms.NotificationPanel.NonFadingTime, IG.Forms.Utilities.Notification.NotificationWindow.notificationPanel1, IG.Forms.NotificationPanel.ShowTime, IG.Forms.NotificationPanel.ShowTmeMilliseconds, IG.Forms.NotificationPanel.TimerInterval, IG.Forms.NotificationPanel.TimerIntervalMilliseconds, IG.Forms.NotificationPanel.Title, IG.Forms.NotificationPanel.TitleColor, and IG.Forms.NotificationPanel.Type.
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.Utilities.Notification.NotificationWindow.components = null private
Required designer variable.
Referenced by IG.Forms.Utilities.Notification.NotificationWindow.Dispose().
notificationPanel1
NotificationPanel IG.Forms.Utilities.Notification.NotificationWindow.notificationPanel1 private
Referenced by IG.Forms.Utilities.Notification.NotificationWindow.InitializeComponent().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/Notification/NotificationWindow.cs
iglib/igforms/Utilities/Notification/NotificationWindow.Designer.cs