Doc: IGLib EXTENDED: IG.Forms.ScalarFunctionEvaluatorForm Class Reference
IG.Forms.ScalarFunctionEvaluatorForm Class Reference
Control for test evaluation of scalar functions.
Public Member Functions
ScalarFunctionEvaluatorForm ()
ScalarFunctionEvaluatorForm (IScalarFunction function, string[] parameterNames, double[] parameterValues)
Constructs the control, with starting data specified.
ScalarFunctionEvaluatorForm ()
ScalarFunctionEvaluatorForm (IScalarFunction function, string[] parameterNames, double[] parameterValues)
Constructs the control, with starting data specified.
ScalarFunctionEvaluatorForm ()
ScalarFunctionEvaluatorForm (IScalarFunction function, string[] parameterNames, double[] parameterValues)
Constructs the control, with starting data specified.
ScalarFunctionEvaluatorForm ()
ScalarFunctionEvaluatorForm (IScalarFunction function, string[] parameterNames, double[] parameterValues)
Constructs the control, with starting data specified.
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
ScalarFunctionEvaluatorControl MainControl [get]
Returns this form's main control.
IVectorFunction VectorFunction [get, set]
Scalar function that is evaluated by the current control.
IScalarFunction ScalarFunction [get, set]
Scalar function that is evaluated by the current control.
string[] ParameterNames [get, set]
double[] ParameterValues [get, set]
int NumParameters [get, set]
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
ScalarFunctionEvaluatorControl scalarFunctionEvaluatorControl1
Detailed Description
Control for test evaluation of scalar functions.
User can define input parameter values and evaluate the function at those parameters.
$A Igor Jul14;
Constructor & Destructor Documentation
ScalarFunctionEvaluatorForm() [1/8]
IG.Forms.ScalarFunctionEvaluatorForm.ScalarFunctionEvaluatorForm () inline
References IG.Forms.ScalarFunctionEvaluatorForm.InitializeComponent().
ScalarFunctionEvaluatorForm() [2/8]
IG.Forms.ScalarFunctionEvaluatorForm.ScalarFunctionEvaluatorForm (IScalarFunction function, string[] parameterNames, double[] parameterValues) inline
Constructs the control, with starting data specified.
Parameters
function Scalar function.
References IG.Forms.ScalarFunctionEvaluatorForm.ParameterNames, IG.Forms.ScalarFunctionEvaluatorForm.ParameterValues, and IG.Forms.ScalarFunctionEvaluatorForm.ScalarFunction.
ScalarFunctionEvaluatorForm() [3/8]
IG.Forms.ScalarFunctionEvaluatorForm.ScalarFunctionEvaluatorForm () inline
References IG.Forms.ScalarFunctionEvaluatorForm.InitializeComponent().
ScalarFunctionEvaluatorForm() [4/8]
IG.Forms.ScalarFunctionEvaluatorForm.ScalarFunctionEvaluatorForm (IScalarFunction function, string[] parameterNames, double[] parameterValues) inline
Constructs the control, with starting data specified.
Parameters
function Scalar function.
References IG.Forms.ScalarFunctionEvaluatorForm.ParameterNames, IG.Forms.ScalarFunctionEvaluatorForm.ParameterValues, and IG.Forms.ScalarFunctionEvaluatorForm.ScalarFunction.
ScalarFunctionEvaluatorForm() [5/8]
IG.Forms.ScalarFunctionEvaluatorForm.ScalarFunctionEvaluatorForm () inline
References IG.Forms.ScalarFunctionEvaluatorForm.InitializeComponent().
ScalarFunctionEvaluatorForm() [6/8]
IG.Forms.ScalarFunctionEvaluatorForm.ScalarFunctionEvaluatorForm (IScalarFunction function, string[] parameterNames, double[] parameterValues) inline
Constructs the control, with starting data specified.
Parameters
function Scalar function.
References IG.Forms.ScalarFunctionEvaluatorForm.ParameterNames, IG.Forms.ScalarFunctionEvaluatorForm.ParameterValues, and IG.Forms.ScalarFunctionEvaluatorForm.ScalarFunction.
ScalarFunctionEvaluatorForm() [7/8]
IG.Forms.ScalarFunctionEvaluatorForm.ScalarFunctionEvaluatorForm () inline
References IG.Forms.ScalarFunctionEvaluatorForm.InitializeComponent().
ScalarFunctionEvaluatorForm() [8/8]
IG.Forms.ScalarFunctionEvaluatorForm.ScalarFunctionEvaluatorForm (IScalarFunction function, string[] parameterNames, double[] parameterValues) inline
Constructs the control, with starting data specified.
Parameters
function Scalar function.
References IG.Forms.ScalarFunctionEvaluatorForm.ParameterNames, IG.Forms.ScalarFunctionEvaluatorForm.ParameterValues, and IG.Forms.ScalarFunctionEvaluatorForm.ScalarFunction.
Member Function Documentation
Dispose() [1/4]
override void IG.Forms.ScalarFunctionEvaluatorForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ScalarFunctionEvaluatorForm.components.
InitializeComponent() [1/4]
void IG.Forms.ScalarFunctionEvaluatorForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ScalarFunctionEvaluatorControl.FunctionDefinition, IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation, IG.Forms.ScalarFunctionEvaluatorControl.NumParameters, IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames, IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues, IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunction, IG.Forms.ScalarFunctionEvaluatorForm.scalarFunctionEvaluatorControl1, IG.Forms.ScalarFunctionEvaluatorControl.TreatScalarAsVectorFunction, IG.Forms.ScalarFunctionEvaluatorControl.VectorFunction, and IG.Forms.ScalarFunctionEvaluatorControl.VisibleTreatAsVector.
Referenced by IG.Forms.ScalarFunctionEvaluatorForm.ScalarFunctionEvaluatorForm().
Dispose() [2/4]
override void IG.Forms.ScalarFunctionEvaluatorForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ScalarFunctionEvaluatorForm.components.
InitializeComponent() [2/4]
void IG.Forms.ScalarFunctionEvaluatorForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ScalarFunctionEvaluatorControl.FunctionDefinition, IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation, IG.Forms.ScalarFunctionEvaluatorControl.NumParameters, IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames, IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues, IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunction, IG.Forms.ScalarFunctionEvaluatorForm.scalarFunctionEvaluatorControl1, IG.Forms.ScalarFunctionEvaluatorControl.TreatScalarAsVectorFunction, IG.Forms.ScalarFunctionEvaluatorControl.VectorFunction, and IG.Forms.ScalarFunctionEvaluatorControl.VisibleTreatAsVector.
Dispose() [3/4]
override void IG.Forms.ScalarFunctionEvaluatorForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ScalarFunctionEvaluatorForm.components.
InitializeComponent() [3/4]
void IG.Forms.ScalarFunctionEvaluatorForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ScalarFunctionEvaluatorControl.FunctionDefinition, IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation, IG.Forms.ScalarFunctionEvaluatorControl.NumParameters, IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames, IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues, IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunction, IG.Forms.ScalarFunctionEvaluatorForm.scalarFunctionEvaluatorControl1, IG.Forms.ScalarFunctionEvaluatorControl.TreatScalarAsVectorFunction, IG.Forms.ScalarFunctionEvaluatorControl.VectorFunction, and IG.Forms.ScalarFunctionEvaluatorControl.VisibleTreatAsVector.
Dispose() [4/4]
override void IG.Forms.ScalarFunctionEvaluatorForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ScalarFunctionEvaluatorForm.components.
InitializeComponent() [4/4]
void IG.Forms.ScalarFunctionEvaluatorForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ScalarFunctionEvaluatorControl.FunctionDefinition, IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation, IG.Forms.ScalarFunctionEvaluatorControl.NumParameters, IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames, IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues, IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunction, IG.Forms.ScalarFunctionEvaluatorForm.scalarFunctionEvaluatorControl1, IG.Forms.ScalarFunctionEvaluatorControl.TreatScalarAsVectorFunction, IG.Forms.ScalarFunctionEvaluatorControl.VectorFunction, and IG.Forms.ScalarFunctionEvaluatorControl.VisibleTreatAsVector.
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.ScalarFunctionEvaluatorForm.components = null private
Required designer variable.
Referenced by IG.Forms.ScalarFunctionEvaluatorForm.Dispose().
scalarFunctionEvaluatorControl1
ScalarFunctionEvaluatorControl IG.Forms.ScalarFunctionEvaluatorForm.scalarFunctionEvaluatorControl1 private
Referenced by IG.Forms.ScalarFunctionEvaluatorForm.InitializeComponent().
Property Documentation
MainControl
ScalarFunctionEvaluatorControl IG.Forms.ScalarFunctionEvaluatorForm.MainControl get
Returns this form's main control.
Referenced by IG.Forms.ScalarFunctionScriptControl.btnValueCalculator_Click().
VectorFunction
IVectorFunction IG.Forms.ScalarFunctionEvaluatorForm.VectorFunction get set
Scalar function that is evaluated by the current control.
ScalarFunction
IScalarFunction IG.Forms.ScalarFunctionEvaluatorForm.ScalarFunction get set
Scalar function that is evaluated by the current control.
Referenced by IG.Forms.ScalarFunctionEvaluatorForm.ScalarFunctionEvaluatorForm().
ParameterNames
string [] IG.Forms.ScalarFunctionEvaluatorForm.ParameterNames get set
Referenced by IG.Forms.ScalarFunctionEvaluatorForm.ScalarFunctionEvaluatorForm().
ParameterValues
double [] IG.Forms.ScalarFunctionEvaluatorForm.ParameterValues get set
Referenced by IG.Forms.ScalarFunctionEvaluatorForm.ScalarFunctionEvaluatorForm().
NumParameters
int IG.Forms.ScalarFunctionEvaluatorForm.NumParameters get set
The documentation for this class was generated from the following files:
iglib/extensions/iglibext/Forms/Numeric/ScalarFunctionEvaluatorForm.cs
iglib/extensions/iglibext/Forms/Numeric/ScalarFunctionEvaluatorForm.Designer.cs