Doc: IGLib EXTENDED: IG.Neural.Forms.Old.FormNeural1DOld Class Reference
IG.Neural.Forms.Old.FormNeural1DOld Class Reference
Public Member Functions
FormNeural1DOld ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void LoadForm (object sender, EventArgs e)
void btStart_Click (object sender, EventArgs e)
void btnGenerateOptData_Click (object sender, EventArgs e)
void PrepareTrainingPoints (bool randomPoints)
Preparing training points
IRealFunction createFunction ()
Creates a function loader and uses it for dynamic definition of functions.
void cbxAforge_CheckedChanged (object sender, EventArgs e)
void cbxNeuron_CheckedChanged (object sender, EventArgs e)
void numMaxEpoch_ValueChanged (object sender, EventArgs e)
void numEpochBundle_ValueChanged (object sender, EventArgs e)
void numRMS_ValueChanged (object sender, EventArgs e)
void numLearningRate_ValueChanged (object sender, EventArgs e)
void numMomentum_ValueChanged (object sender, EventArgs e)
void numSamples_ValueChanged (object sender, EventArgs e)
void numHiddenNeuron_ValueChanged (object sender, EventArgs e)
void numLowLimit_ValueChanged (object sender, EventArgs e)
void numHighLimit_ValueChanged (object sender, EventArgs e)
void numInputSafety_ValueChanged (object sender, EventArgs e)
void numOutputSafety_ValueChanged (object sender, EventArgs e)
void cbEquation_SelectedIndexChanged (object sender, EventArgs e)
void WriteDefaultFunction ()
string OnPointEdit (ZedGraphControl sender, GraphPane pane, CurveItem curve, int iPt)
void EnableControls (bool enabled)
void CleanseGraph (bool dafaultF, bool approximatedF, bool trainingF)
void GraphDimensions (SampledDataSet data)
Defines graph dimensions.
void WriteTrainingPoints (SampledDataSet trainingData)
void Stop ()
void Prediction (INeuralApproximator approximator, ref IVector[] exactInputParameters, ref IVector[] approximatedOutputValues, bool testFromFile)
void CalculateError (IVector[] exactOutputValues, IVector[] approximatedOutputValues, ref double maxError, ref double averageError)
void btnReset_Click (object sender, EventArgs e)
void cbMultipleThread_CheckedChanged (object sender, EventArgs e)
void numThreads_ValueChanged (object sender, EventArgs e)
void numFunctionType_ValueChanged (object sender, EventArgs e)
void tbSelfMadeEquation_TextChanged (object sender, EventArgs e)
void cbSelfMade_CheckedChanged (object sender, EventArgs e)
void bthelp_Click (object sender, EventArgs e)
void tbSelfMadeEquation_Enter (object sender, EventArgs e)
void tbSelfMadeEquation_KeyPress (object sender, KeyPressEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
SampledDataSet trainingData = null
SampledDataSet verificationData = null
SampledDataSet defaultFunctionData = null
INeuralApproximator approximator = new NeuralApproximatorNeuron()
int hiddenNeuron = 5
int maxEpoch = 5000
int epochInBundle = 500
double rmsError = 0.001
double learningRate = 0.3
double momentum = 0.6
int samples = 3
int nnType = 1
double lowHorizontalLimit = -5.0
double highHorizontalLimit = 5.0
double lowVerificationHorizontalLimit = -5.0
double highVerificationHorizontalLimit = 5.0
double inputSafetyFactor = 1.3
double outputSafetyFactor = 1.3
bool multipleThread = false
int noThreads = 100
int thread = 0
double tmpMaxMaxTrainError = 0.0
double tmpAvgMaxTrainError = 0.0
double tmpMaxMinTrainError = 1.0
double tmpAvgMinTrainError = 1.0
double tmpMaxMaxVerifError = 0.0
double tmpAvgMaxVerifError = 0.0
double tmpMaxMinVerifError = 1.0
double tmpAvgMinVerifError = 1.0
double abc = 0
string equation = "x*x"
GraphPane pane
LineItem trainingPoints
LineItem[] approximatedLine
LineItem defaultFunction
System.ComponentModel.IContainer components = null
Required designer variable.
ZedGraph.ZedGraphControl functionGraph
System.Windows.Forms.Button btStart
System.Windows.Forms.Button btnReset
System.Windows.Forms.TextBox tbMaxError
System.Windows.Forms.Label label1
System.Windows.Forms.Label label2
System.Windows.Forms.TextBox tbAverageError
System.Windows.Forms.CheckBox cbxAforge
System.Windows.Forms.CheckBox cbxNeuron
System.Windows.Forms.Label label3
System.Windows.Forms.Label label4
System.Windows.Forms.Label label5
System.Windows.Forms.Label label6
System.Windows.Forms.Label label7
System.Windows.Forms.Label label8
System.Windows.Forms.NumericUpDown numMaxEpoch
System.Windows.Forms.NumericUpDown numEpochBundle
System.Windows.Forms.NumericUpDown numRMS
System.Windows.Forms.NumericUpDown numLearningRate
System.Windows.Forms.NumericUpDown numMomentum
System.Windows.Forms.Label label9
System.Windows.Forms.NumericUpDown numSamples
System.Windows.Forms.NumericUpDown numHiddenNeuron
System.Windows.Forms.Label label11
System.Windows.Forms.Button btnGenerateOptData
System.Windows.Forms.TextBox tbAvgTrainError
System.Windows.Forms.Label label12
System.Windows.Forms.Label label13
System.Windows.Forms.TextBox tbMaxTrainError
System.Windows.Forms.NumericUpDown numLowLimit
System.Windows.Forms.NumericUpDown numHighLimit
System.Windows.Forms.Label label14
System.Windows.Forms.NumericUpDown numInputSafety
System.Windows.Forms.Label label15
System.Windows.Forms.NumericUpDown numOutputSafety
System.Windows.Forms.Label label16
System.Windows.Forms.TextBox tbAvgMinTrainError
System.Windows.Forms.TextBox tbMaxMinTrainError
System.Windows.Forms.TextBox tbAverageMinError
System.Windows.Forms.TextBox tbMaxMinError
System.Windows.Forms.Label label17
System.Windows.Forms.Label labelMaxError
System.Windows.Forms.CheckBox cbMultipleThread
System.Windows.Forms.NumericUpDown numThreads
System.Windows.Forms.Label labMultipleThread
System.Windows.Forms.Label label19
System.Windows.Forms.TextBox tbEquationError
System.Windows.Forms.ComboBox cbEquation
System.Windows.Forms.CheckBox cbRandomData
System.Windows.Forms.Label label10
System.Windows.Forms.Label label20
System.Windows.Forms.CheckBox cbSelfMade
System.Windows.Forms.TextBox tbSelfMadeEquation
System.Windows.Forms.Button bthelp
System.Windows.Forms.ToolTip toolTip
ZedGraph.ZedGraphControl zedGraphControl1
Static Private Attributes
static readonly Color enabledColor = Color.Tomato
static readonly Color disabledColor = Color.Goldenrod
Constructor & Destructor Documentation
FormNeural1DOld()
IG.Neural.Forms.Old.FormNeural1DOld.FormNeural1DOld () inline
References IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
Member Function Documentation
LoadForm()
void IG.Neural.Forms.Old.FormNeural1DOld.LoadForm (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.functionGraph, IG.Neural.Forms.Old.FormNeural1DOld.multipleThread, and IG.Neural.Forms.Old.FormNeural1DOld.pane.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
btStart_Click()
void IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.approximator, IG.Neural.Forms.Old.FormNeural1DOld.CleanseGraph(), IG.Neural.Forms.Old.FormNeural1DOld.EnableControls(), IG.Neural.Forms.Old.FormNeural1DOld.enabledColor, IG.Neural.NeuralNetworks.EpochBundle, IG.Neural.Forms.Old.FormNeural1DOld.epochInBundle, IG.Neural.Forms.Old.FormNeural1DOld.hiddenNeuron, IG.Neural.NeuralNetworks.HiddenNeuron1L, IG.Neural.Forms.Old.FormNeural1DOld.inputSafetyFactor, IG.Neural.NeuralNetworks.InputSafetyFactor, IG.Neural.Forms.Old.FormNeural1DOld.learningRate, IG.Neural.NeuralNetworks.LearningRate, IG.Neural.Forms.Old.FormNeural1DOld.maxEpoch, IG.Neural.NeuralNetworks.MaxEpoch, IG.Neural.Forms.Old.FormNeural1DOld.momentum, IG.Neural.NeuralNetworks.Momentum, IG.Neural.Forms.Old.FormNeural1DOld.multipleThread, IG.Neural.Forms.Old.FormNeural1DOld.noThreads, IG.Neural.Forms.Old.FormNeural1DOld.outputSafetyFactor, IG.Neural.NeuralNetworks.OutputSafetyFactor, IG.Neural.NeuralNetworks.RMS, IG.Neural.Forms.Old.FormNeural1DOld.rmsError, IG.Neural.Forms.Old.FormNeural1DOld.Stop(), IG.Neural.Forms.Old.FormNeural1DOld.trainingData, IG.Neural.Forms.Old.FormNeural1DOld.trainingPoints, IG.Neural.NeuralNetworks.TrainNetwork(), and IG.Neural.Forms.Old.FormNeural1DOld.verificationData.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
btnGenerateOptData_Click()
void IG.Neural.Forms.Old.FormNeural1DOld.btnGenerateOptData_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.cbRandomData, IG.Neural.Forms.Old.FormNeural1DOld.CleanseGraph(), IG.Neural.Forms.Old.FormNeural1DOld.createFunction(), IG.Neural.Forms.Old.FormNeural1DOld.defaultFunctionData, IG.Neural.TestFunctions.GenerateFunctionTrainingSamples(), IG.Neural.Forms.Old.FormNeural1DOld.highHorizontalLimit, IG.Neural.Forms.Old.FormNeural1DOld.lowHorizontalLimit, IG.Neural.Forms.Old.FormNeural1DOld.pane, IG.Neural.Forms.Old.FormNeural1DOld.PrepareTrainingPoints(), IG.Neural.Forms.Old.FormNeural1DOld.tbEquationError, IG.Neural.Forms.Old.FormNeural1DOld.trainingData, IG.Neural.Forms.Old.FormNeural1DOld.verificationData, IG.Neural.Forms.Old.FormNeural1DOld.WriteDefaultFunction(), and IG.Neural.Forms.Old.FormNeural1DOld.WriteTrainingPoints().
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
PrepareTrainingPoints()
void IG.Neural.Forms.Old.FormNeural1DOld.PrepareTrainingPoints (bool randomPoints) inline private
Preparing training points
References IG.Num.SampledDataSet.AddElement(), IG.Neural.Forms.Old.FormNeural1DOld.defaultFunctionData, IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Neural.Forms.Old.FormNeural1DOld.highVerificationHorizontalLimit, IG.Num.SampledDataSet.Length, IG.Neural.Forms.Old.FormNeural1DOld.lowVerificationHorizontalLimit, IG.Neural.Forms.Old.FormNeural1DOld.samples, and IG.Neural.Forms.Old.FormNeural1DOld.trainingData.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btnGenerateOptData_Click().
createFunction()
IRealFunction IG.Neural.Forms.Old.FormNeural1DOld.createFunction () inline private
Creates a function loader and uses it for dynamic definition of functions.
References IG.Lib.RealFunctionLoader.CreateRealFunction(), IG.Neural.Forms.Old.FormNeural1DOld.equation, IG.Lib.RealFunctionLoader.IndependentVariableName, IG.Lib.RealFunctionLoader.InvalidateDefinitions(), IG.Neural.Forms.Old.FormNeural1DOld.tbEquationError, IG.Neural.Forms.Old.FormNeural1DOld.tbSelfMadeEquation, and IG.Lib.RealFunctionLoader.ValueDefinitionString.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btnGenerateOptData_Click().
cbxAforge_CheckedChanged()
void IG.Neural.Forms.Old.FormNeural1DOld.cbxAforge_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.approximator, IG.Neural.Forms.Old.FormNeural1DOld.cbxAforge, IG.Neural.Forms.Old.FormNeural1DOld.cbxNeuron, and IG.Neural.Forms.Old.FormNeural1DOld.nnType.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
cbxNeuron_CheckedChanged()
void IG.Neural.Forms.Old.FormNeural1DOld.cbxNeuron_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.approximator, IG.Neural.Forms.Old.FormNeural1DOld.cbxAforge, IG.Neural.Forms.Old.FormNeural1DOld.cbxNeuron, and IG.Neural.Forms.Old.FormNeural1DOld.nnType.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
numMaxEpoch_ValueChanged()
void IG.Neural.Forms.Old.FormNeural1DOld.numMaxEpoch_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.maxEpoch, and IG.Neural.Forms.Old.FormNeural1DOld.numMaxEpoch.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
numEpochBundle_ValueChanged()
void IG.Neural.Forms.Old.FormNeural1DOld.numEpochBundle_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.epochInBundle, and IG.Neural.Forms.Old.FormNeural1DOld.numEpochBundle.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
numRMS_ValueChanged()
void IG.Neural.Forms.Old.FormNeural1DOld.numRMS_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.numRMS, and IG.Neural.Forms.Old.FormNeural1DOld.rmsError.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
numLearningRate_ValueChanged()
void IG.Neural.Forms.Old.FormNeural1DOld.numLearningRate_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.learningRate, and IG.Neural.Forms.Old.FormNeural1DOld.numLearningRate.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
numMomentum_ValueChanged()
void IG.Neural.Forms.Old.FormNeural1DOld.numMomentum_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.momentum, and IG.Neural.Forms.Old.FormNeural1DOld.numMomentum.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
numSamples_ValueChanged()
void IG.Neural.Forms.Old.FormNeural1DOld.numSamples_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.numSamples, and IG.Neural.Forms.Old.FormNeural1DOld.samples.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
numHiddenNeuron_ValueChanged()
void IG.Neural.Forms.Old.FormNeural1DOld.numHiddenNeuron_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.hiddenNeuron, and IG.Neural.Forms.Old.FormNeural1DOld.numHiddenNeuron.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
numLowLimit_ValueChanged()
void IG.Neural.Forms.Old.FormNeural1DOld.numLowLimit_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.lowHorizontalLimit, and IG.Neural.Forms.Old.FormNeural1DOld.numLowLimit.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
numHighLimit_ValueChanged()
void IG.Neural.Forms.Old.FormNeural1DOld.numHighLimit_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.highHorizontalLimit, and IG.Neural.Forms.Old.FormNeural1DOld.numHighLimit.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
numInputSafety_ValueChanged()
void IG.Neural.Forms.Old.FormNeural1DOld.numInputSafety_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.inputSafetyFactor, and IG.Neural.Forms.Old.FormNeural1DOld.numInputSafety.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
numOutputSafety_ValueChanged()
void IG.Neural.Forms.Old.FormNeural1DOld.numOutputSafety_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.numOutputSafety, and IG.Neural.Forms.Old.FormNeural1DOld.outputSafetyFactor.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
cbEquation_SelectedIndexChanged()
void IG.Neural.Forms.Old.FormNeural1DOld.cbEquation_SelectedIndexChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.cbEquation, and IG.Neural.Forms.Old.FormNeural1DOld.equation.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
WriteDefaultFunction()
void IG.Neural.Forms.Old.FormNeural1DOld.WriteDefaultFunction () inline private
References IG.Neural.Forms.Old.FormNeural1DOld.defaultFunction, IG.Neural.Forms.Old.FormNeural1DOld.defaultFunctionData, IG.Neural.Forms.Old.FormNeural1DOld.functionGraph, IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Neural.Forms.Old.FormNeural1DOld.GraphDimensions(), and IG.Num.SampledDataSet.Length.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btnGenerateOptData_Click().
OnPointEdit()
string IG.Neural.Forms.Old.FormNeural1DOld.OnPointEdit (ZedGraphControl sender, GraphPane pane, CurveItem curve, int iPt) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.CleanseGraph().
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
EnableControls()
void IG.Neural.Forms.Old.FormNeural1DOld.EnableControls (bool enabled) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.disabledColor, IG.Neural.Forms.Old.FormNeural1DOld.enabledColor, IG.Neural.Forms.Old.FormNeural1DOld.functionGraph, and IG.Neural.Forms.Old.FormNeural1DOld.trainingPoints.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), and IG.Neural.Forms.Old.FormNeural1DOld.Stop().
CleanseGraph()
void IG.Neural.Forms.Old.FormNeural1DOld.CleanseGraph (bool dafaultF, bool approximatedF, bool trainingF) inline private
Parameters
dafaultF Flag to clean default Line.
approximatedF Flag to clean approximated Line.
trainingF Flag to clean training points.
References IG.Neural.Forms.Old.FormNeural1DOld.approximatedLine, IG.Neural.Forms.Old.FormNeural1DOld.defaultFunction, IG.Neural.Forms.Old.FormNeural1DOld.functionGraph, IG.Neural.Forms.Old.FormNeural1DOld.thread, IG.Neural.Forms.Old.FormNeural1DOld.tmpAvgMaxTrainError, IG.Neural.Forms.Old.FormNeural1DOld.tmpAvgMaxVerifError, IG.Neural.Forms.Old.FormNeural1DOld.tmpAvgMinTrainError, IG.Neural.Forms.Old.FormNeural1DOld.tmpAvgMinVerifError, IG.Neural.Forms.Old.FormNeural1DOld.tmpMaxMaxTrainError, IG.Neural.Forms.Old.FormNeural1DOld.tmpMaxMaxVerifError, IG.Neural.Forms.Old.FormNeural1DOld.tmpMaxMinTrainError, IG.Neural.Forms.Old.FormNeural1DOld.tmpMaxMinVerifError, and IG.Neural.Forms.Old.FormNeural1DOld.trainingPoints.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btnGenerateOptData_Click(), IG.Neural.Forms.Old.FormNeural1DOld.btnReset_Click(), IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), and IG.Neural.Forms.Old.FormNeural1DOld.OnPointEdit().
GraphDimensions()
void IG.Neural.Forms.Old.FormNeural1DOld.GraphDimensions (SampledDataSet data) inline private
Defines graph dimensions.
Parameters
data
References IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.Length, and IG.Neural.Forms.Old.FormNeural1DOld.pane.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.WriteDefaultFunction().
WriteTrainingPoints()
void IG.Neural.Forms.Old.FormNeural1DOld.WriteTrainingPoints (SampledDataSet trainingData) inline private
Parameters
inputParam
outputVal
References IG.Neural.Forms.Old.FormNeural1DOld.btStart, IG.Neural.Forms.Old.FormNeural1DOld.enabledColor, IG.Neural.Forms.Old.FormNeural1DOld.functionGraph, IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.InputLength, IG.Num.IVector< T >.Length, IG.Num.SampledDataSet.Length, IG.Num.SampledDataSet.OutputLength, IG.Neural.Forms.Old.FormNeural1DOld.trainingData, and IG.Neural.Forms.Old.FormNeural1DOld.trainingPoints.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btnGenerateOptData_Click().
Stop()
void IG.Neural.Forms.Old.FormNeural1DOld.Stop () inline private
References IG.Neural.Forms.Old.FormNeural1DOld.approximatedLine, IG.Neural.Forms.Old.FormNeural1DOld.approximator, IG.Neural.Forms.Old.FormNeural1DOld.EnableControls(), IG.Neural.Forms.Old.FormNeural1DOld.functionGraph, IG.Neural.Forms.Old.FormNeural1DOld.noThreads, IG.Neural.Forms.Old.FormNeural1DOld.Prediction(), and IG.Neural.Forms.Old.FormNeural1DOld.thread.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click().
Prediction()
void IG.Neural.Forms.Old.FormNeural1DOld.Prediction (INeuralApproximator approximator, ref IVector[] exactInputParameters, ref IVector[] approximatedOutputValues, bool testFromFile) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.abc, IG.Neural.Forms.Old.FormNeural1DOld.approximator, IG.Neural.Forms.Old.FormNeural1DOld.CalculateError(), IG.Num.IVectorApproximator.CalculateOutput(), IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputRange(), IG.Num.SampledDataSet.GetOutputValues(), IG.Neural.Forms.Old.FormNeural1DOld.highVerificationHorizontalLimit, IG.Num.SampledDataSet.Length, IG.Neural.Forms.Old.FormNeural1DOld.lowVerificationHorizontalLimit, IG.Neural.Forms.Old.FormNeural1DOld.multipleThread, IG.Num.IVectorApproximator.OutputLength, IG.Num.SampledDataSet.OutputLength, IG.Neural.Forms.Old.FormNeural1DOld.tbAverageError, IG.Neural.Forms.Old.FormNeural1DOld.tbAverageMinError, IG.Neural.Forms.Old.FormNeural1DOld.tbAvgMinTrainError, IG.Neural.Forms.Old.FormNeural1DOld.tbAvgTrainError, IG.Neural.Forms.Old.FormNeural1DOld.tbMaxError, IG.Neural.Forms.Old.FormNeural1DOld.tbMaxMinError, IG.Neural.Forms.Old.FormNeural1DOld.tbMaxMinTrainError, IG.Neural.Forms.Old.FormNeural1DOld.tbMaxTrainError, IG.Neural.Forms.Old.FormNeural1DOld.tmpAvgMaxTrainError, IG.Neural.Forms.Old.FormNeural1DOld.tmpAvgMaxVerifError, IG.Neural.Forms.Old.FormNeural1DOld.tmpAvgMinTrainError, IG.Neural.Forms.Old.FormNeural1DOld.tmpAvgMinVerifError, IG.Neural.Forms.Old.FormNeural1DOld.tmpMaxMaxTrainError, IG.Neural.Forms.Old.FormNeural1DOld.tmpMaxMaxVerifError, IG.Neural.Forms.Old.FormNeural1DOld.tmpMaxMinTrainError, IG.Neural.Forms.Old.FormNeural1DOld.tmpMaxMinVerifError, IG.Num.INeuralApproximator.TrainingData, and IG.Neural.Forms.Old.FormNeural1DOld.verificationData.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.Stop().
CalculateError()
void IG.Neural.Forms.Old.FormNeural1DOld.CalculateError (IVector[] exactOutputValues, IVector[] approximatedOutputValues, ref double maxError, ref double averageError) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.approximator, IG.Num.SampledDataSet.GetOutputRange(), IG.Num.IVector< T >.Length, IG.Num.IVectorApproximator.OutputLength, and IG.Num.INeuralApproximator.TrainingData.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.Prediction().
btnReset_Click()
void IG.Neural.Forms.Old.FormNeural1DOld.btnReset_Click (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.CleanseGraph().
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
cbMultipleThread_CheckedChanged()
void IG.Neural.Forms.Old.FormNeural1DOld.cbMultipleThread_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.cbMultipleThread, IG.Neural.Forms.Old.FormNeural1DOld.labelMaxError, IG.Neural.Forms.Old.FormNeural1DOld.labMultipleThread, IG.Neural.Forms.Old.FormNeural1DOld.multipleThread, IG.Neural.Forms.Old.FormNeural1DOld.noThreads, IG.Neural.Forms.Old.FormNeural1DOld.numThreads, IG.Neural.Forms.Old.FormNeural1DOld.tbAverageMinError, IG.Neural.Forms.Old.FormNeural1DOld.tbAvgMinTrainError, IG.Neural.Forms.Old.FormNeural1DOld.tbMaxMinError, and IG.Neural.Forms.Old.FormNeural1DOld.tbMaxMinTrainError.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
numThreads_ValueChanged()
void IG.Neural.Forms.Old.FormNeural1DOld.numThreads_ValueChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.noThreads, and IG.Neural.Forms.Old.FormNeural1DOld.numThreads.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
numFunctionType_ValueChanged()
void IG.Neural.Forms.Old.FormNeural1DOld.numFunctionType_ValueChanged (object sender, EventArgs e) inline private
tbSelfMadeEquation_TextChanged()
void IG.Neural.Forms.Old.FormNeural1DOld.tbSelfMadeEquation_TextChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.equation, and IG.Neural.Forms.Old.FormNeural1DOld.tbSelfMadeEquation.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
cbSelfMade_CheckedChanged()
void IG.Neural.Forms.Old.FormNeural1DOld.cbSelfMade_CheckedChanged (object sender, EventArgs e) inline private
References IG.Neural.Forms.Old.FormNeural1DOld.bthelp, IG.Neural.Forms.Old.FormNeural1DOld.cbEquation, IG.Neural.Forms.Old.FormNeural1DOld.cbSelfMade, and IG.Neural.Forms.Old.FormNeural1DOld.tbSelfMadeEquation.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
bthelp_Click()
void IG.Neural.Forms.Old.FormNeural1DOld.bthelp_Click (object sender, EventArgs e) inline private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
tbSelfMadeEquation_Enter()
void IG.Neural.Forms.Old.FormNeural1DOld.tbSelfMadeEquation_Enter (object sender, EventArgs e) inline private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
tbSelfMadeEquation_KeyPress()
void IG.Neural.Forms.Old.FormNeural1DOld.tbSelfMadeEquation_KeyPress (object sender, KeyPressEventArgs e) inline private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
Dispose()
override void IG.Neural.Forms.Old.FormNeural1DOld.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.Old.FormNeural1DOld.components.
InitializeComponent()
void IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.Old.FormNeural1DOld.bthelp, IG.Neural.Forms.Old.FormNeural1DOld.bthelp_Click(), IG.Neural.Forms.Old.FormNeural1DOld.btnGenerateOptData, IG.Neural.Forms.Old.FormNeural1DOld.btnGenerateOptData_Click(), IG.Neural.Forms.Old.FormNeural1DOld.btnReset, IG.Neural.Forms.Old.FormNeural1DOld.btnReset_Click(), IG.Neural.Forms.Old.FormNeural1DOld.btStart, IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), IG.Neural.Forms.Old.FormNeural1DOld.cbEquation, IG.Neural.Forms.Old.FormNeural1DOld.cbEquation_SelectedIndexChanged(), IG.Neural.Forms.Old.FormNeural1DOld.cbMultipleThread, IG.Neural.Forms.Old.FormNeural1DOld.cbMultipleThread_CheckedChanged(), IG.Neural.Forms.Old.FormNeural1DOld.cbRandomData, IG.Neural.Forms.Old.FormNeural1DOld.cbSelfMade, IG.Neural.Forms.Old.FormNeural1DOld.cbSelfMade_CheckedChanged(), IG.Neural.Forms.Old.FormNeural1DOld.cbxAforge, IG.Neural.Forms.Old.FormNeural1DOld.cbxAforge_CheckedChanged(), IG.Neural.Forms.Old.FormNeural1DOld.cbxNeuron, IG.Neural.Forms.Old.FormNeural1DOld.cbxNeuron_CheckedChanged(), IG.Neural.Forms.Old.FormNeural1DOld.components, IG.Neural.Forms.Old.FormNeural1DOld.functionGraph, IG.Neural.Forms.Old.FormNeural1DOld.label1, IG.Neural.Forms.Old.FormNeural1DOld.label10, IG.Neural.Forms.Old.FormNeural1DOld.label11, IG.Neural.Forms.Old.FormNeural1DOld.label12, IG.Neural.Forms.Old.FormNeural1DOld.label13, IG.Neural.Forms.Old.FormNeural1DOld.label14, IG.Neural.Forms.Old.FormNeural1DOld.label15, IG.Neural.Forms.Old.FormNeural1DOld.label16, IG.Neural.Forms.Old.FormNeural1DOld.label17, IG.Neural.Forms.Old.FormNeural1DOld.label19, IG.Neural.Forms.Old.FormNeural1DOld.label2, IG.Neural.Forms.Old.FormNeural1DOld.label20, IG.Neural.Forms.Old.FormNeural1DOld.label3, IG.Neural.Forms.Old.FormNeural1DOld.label4, IG.Neural.Forms.Old.FormNeural1DOld.label5, IG.Neural.Forms.Old.FormNeural1DOld.label6, IG.Neural.Forms.Old.FormNeural1DOld.label7, IG.Neural.Forms.Old.FormNeural1DOld.label8, IG.Neural.Forms.Old.FormNeural1DOld.label9, IG.Neural.Forms.Old.FormNeural1DOld.labelMaxError, IG.Neural.Forms.Old.FormNeural1DOld.labMultipleThread, IG.Neural.Forms.Old.FormNeural1DOld.LoadForm(), IG.Neural.Forms.Old.FormNeural1DOld.numEpochBundle, IG.Neural.Forms.Old.FormNeural1DOld.numEpochBundle_ValueChanged(), IG.Neural.Forms.Old.FormNeural1DOld.numHiddenNeuron, IG.Neural.Forms.Old.FormNeural1DOld.numHiddenNeuron_ValueChanged(), IG.Neural.Forms.Old.FormNeural1DOld.numHighLimit, IG.Neural.Forms.Old.FormNeural1DOld.numHighLimit_ValueChanged(), IG.Neural.Forms.Old.FormNeural1DOld.numInputSafety, IG.Neural.Forms.Old.FormNeural1DOld.numInputSafety_ValueChanged(), IG.Neural.Forms.Old.FormNeural1DOld.numLearningRate, IG.Neural.Forms.Old.FormNeural1DOld.numLearningRate_ValueChanged(), IG.Neural.Forms.Old.FormNeural1DOld.numLowLimit, IG.Neural.Forms.Old.FormNeural1DOld.numLowLimit_ValueChanged(), IG.Neural.Forms.Old.FormNeural1DOld.numMaxEpoch, IG.Neural.Forms.Old.FormNeural1DOld.numMaxEpoch_ValueChanged(), IG.Neural.Forms.Old.FormNeural1DOld.numMomentum, IG.Neural.Forms.Old.FormNeural1DOld.numMomentum_ValueChanged(), IG.Neural.Forms.Old.FormNeural1DOld.numOutputSafety, IG.Neural.Forms.Old.FormNeural1DOld.numOutputSafety_ValueChanged(), IG.Neural.Forms.Old.FormNeural1DOld.numRMS, IG.Neural.Forms.Old.FormNeural1DOld.numRMS_ValueChanged(), IG.Neural.Forms.Old.FormNeural1DOld.numSamples, IG.Neural.Forms.Old.FormNeural1DOld.numSamples_ValueChanged(), IG.Neural.Forms.Old.FormNeural1DOld.numThreads, IG.Neural.Forms.Old.FormNeural1DOld.numThreads_ValueChanged(), IG.Neural.Forms.Old.FormNeural1DOld.OnPointEdit(), IG.Neural.Forms.Old.FormNeural1DOld.tbAverageError, IG.Neural.Forms.Old.FormNeural1DOld.tbAverageMinError, IG.Neural.Forms.Old.FormNeural1DOld.tbAvgMinTrainError, IG.Neural.Forms.Old.FormNeural1DOld.tbAvgTrainError, IG.Neural.Forms.Old.FormNeural1DOld.tbEquationError, IG.Neural.Forms.Old.FormNeural1DOld.tbMaxError, IG.Neural.Forms.Old.FormNeural1DOld.tbMaxMinError, IG.Neural.Forms.Old.FormNeural1DOld.tbMaxMinTrainError, IG.Neural.Forms.Old.FormNeural1DOld.tbMaxTrainError, IG.Neural.Forms.Old.FormNeural1DOld.tbSelfMadeEquation, IG.Neural.Forms.Old.FormNeural1DOld.tbSelfMadeEquation_Enter(), IG.Neural.Forms.Old.FormNeural1DOld.tbSelfMadeEquation_KeyPress(), IG.Neural.Forms.Old.FormNeural1DOld.tbSelfMadeEquation_TextChanged(), IG.Neural.Forms.Old.FormNeural1DOld.toolTip, and IG.Neural.Forms.Old.FormNeural1DOld.zedGraphControl1.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.FormNeural1DOld().
Member Data Documentation
trainingData
SampledDataSet IG.Neural.Forms.Old.FormNeural1DOld.trainingData = null private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btnGenerateOptData_Click(), IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), IG.Neural.Forms.Old.FormNeural1DOld.PrepareTrainingPoints(), and IG.Neural.Forms.Old.FormNeural1DOld.WriteTrainingPoints().
verificationData
SampledDataSet IG.Neural.Forms.Old.FormNeural1DOld.verificationData = null private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btnGenerateOptData_Click(), IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), and IG.Neural.Forms.Old.FormNeural1DOld.Prediction().
defaultFunctionData
SampledDataSet IG.Neural.Forms.Old.FormNeural1DOld.defaultFunctionData = null private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btnGenerateOptData_Click(), IG.Neural.Forms.Old.FormNeural1DOld.PrepareTrainingPoints(), and IG.Neural.Forms.Old.FormNeural1DOld.WriteDefaultFunction().
approximator
INeuralApproximator IG.Neural.Forms.Old.FormNeural1DOld.approximator = new NeuralApproximatorNeuron() private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), IG.Neural.Forms.Old.FormNeural1DOld.CalculateError(), IG.Neural.Forms.Old.FormNeural1DOld.cbxAforge_CheckedChanged(), IG.Neural.Forms.Old.FormNeural1DOld.cbxNeuron_CheckedChanged(), IG.Neural.Forms.Old.FormNeural1DOld.Prediction(), and IG.Neural.Forms.Old.FormNeural1DOld.Stop().
hiddenNeuron
int IG.Neural.Forms.Old.FormNeural1DOld.hiddenNeuron = 5 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), and IG.Neural.Forms.Old.FormNeural1DOld.numHiddenNeuron_ValueChanged().
maxEpoch
int IG.Neural.Forms.Old.FormNeural1DOld.maxEpoch = 5000 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), and IG.Neural.Forms.Old.FormNeural1DOld.numMaxEpoch_ValueChanged().
epochInBundle
int IG.Neural.Forms.Old.FormNeural1DOld.epochInBundle = 500 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), and IG.Neural.Forms.Old.FormNeural1DOld.numEpochBundle_ValueChanged().
rmsError
double IG.Neural.Forms.Old.FormNeural1DOld.rmsError = 0.001 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), and IG.Neural.Forms.Old.FormNeural1DOld.numRMS_ValueChanged().
learningRate
double IG.Neural.Forms.Old.FormNeural1DOld.learningRate = 0.3 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), and IG.Neural.Forms.Old.FormNeural1DOld.numLearningRate_ValueChanged().
momentum
double IG.Neural.Forms.Old.FormNeural1DOld.momentum = 0.6 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), and IG.Neural.Forms.Old.FormNeural1DOld.numMomentum_ValueChanged().
samples
int IG.Neural.Forms.Old.FormNeural1DOld.samples = 3 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.numSamples_ValueChanged(), and IG.Neural.Forms.Old.FormNeural1DOld.PrepareTrainingPoints().
nnType
int IG.Neural.Forms.Old.FormNeural1DOld.nnType = 1 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.cbxAforge_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural1DOld.cbxNeuron_CheckedChanged().
lowHorizontalLimit
double IG.Neural.Forms.Old.FormNeural1DOld.lowHorizontalLimit = -5.0 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btnGenerateOptData_Click(), and IG.Neural.Forms.Old.FormNeural1DOld.numLowLimit_ValueChanged().
highHorizontalLimit
double IG.Neural.Forms.Old.FormNeural1DOld.highHorizontalLimit = 5.0 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btnGenerateOptData_Click(), and IG.Neural.Forms.Old.FormNeural1DOld.numHighLimit_ValueChanged().
lowVerificationHorizontalLimit
double IG.Neural.Forms.Old.FormNeural1DOld.lowVerificationHorizontalLimit = -5.0 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.Prediction(), and IG.Neural.Forms.Old.FormNeural1DOld.PrepareTrainingPoints().
highVerificationHorizontalLimit
double IG.Neural.Forms.Old.FormNeural1DOld.highVerificationHorizontalLimit = 5.0 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.Prediction(), and IG.Neural.Forms.Old.FormNeural1DOld.PrepareTrainingPoints().
inputSafetyFactor
double IG.Neural.Forms.Old.FormNeural1DOld.inputSafetyFactor = 1.3 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), and IG.Neural.Forms.Old.FormNeural1DOld.numInputSafety_ValueChanged().
outputSafetyFactor
double IG.Neural.Forms.Old.FormNeural1DOld.outputSafetyFactor = 1.3 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), and IG.Neural.Forms.Old.FormNeural1DOld.numOutputSafety_ValueChanged().
multipleThread
bool IG.Neural.Forms.Old.FormNeural1DOld.multipleThread = false private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), IG.Neural.Forms.Old.FormNeural1DOld.cbMultipleThread_CheckedChanged(), IG.Neural.Forms.Old.FormNeural1DOld.LoadForm(), and IG.Neural.Forms.Old.FormNeural1DOld.Prediction().
noThreads
int IG.Neural.Forms.Old.FormNeural1DOld.noThreads = 100 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), IG.Neural.Forms.Old.FormNeural1DOld.cbMultipleThread_CheckedChanged(), IG.Neural.Forms.Old.FormNeural1DOld.numThreads_ValueChanged(), and IG.Neural.Forms.Old.FormNeural1DOld.Stop().
thread
int IG.Neural.Forms.Old.FormNeural1DOld.thread = 0 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.CleanseGraph(), and IG.Neural.Forms.Old.FormNeural1DOld.Stop().
tmpMaxMaxTrainError
double IG.Neural.Forms.Old.FormNeural1DOld.tmpMaxMaxTrainError = 0.0 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.CleanseGraph(), and IG.Neural.Forms.Old.FormNeural1DOld.Prediction().
tmpAvgMaxTrainError
double IG.Neural.Forms.Old.FormNeural1DOld.tmpAvgMaxTrainError = 0.0 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.CleanseGraph(), and IG.Neural.Forms.Old.FormNeural1DOld.Prediction().
tmpMaxMinTrainError
double IG.Neural.Forms.Old.FormNeural1DOld.tmpMaxMinTrainError = 1.0 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.CleanseGraph(), and IG.Neural.Forms.Old.FormNeural1DOld.Prediction().
tmpAvgMinTrainError
double IG.Neural.Forms.Old.FormNeural1DOld.tmpAvgMinTrainError = 1.0 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.CleanseGraph(), and IG.Neural.Forms.Old.FormNeural1DOld.Prediction().
tmpMaxMaxVerifError
double IG.Neural.Forms.Old.FormNeural1DOld.tmpMaxMaxVerifError = 0.0 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.CleanseGraph(), and IG.Neural.Forms.Old.FormNeural1DOld.Prediction().
tmpAvgMaxVerifError
double IG.Neural.Forms.Old.FormNeural1DOld.tmpAvgMaxVerifError = 0.0 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.CleanseGraph(), and IG.Neural.Forms.Old.FormNeural1DOld.Prediction().
tmpMaxMinVerifError
double IG.Neural.Forms.Old.FormNeural1DOld.tmpMaxMinVerifError = 1.0 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.CleanseGraph(), and IG.Neural.Forms.Old.FormNeural1DOld.Prediction().
tmpAvgMinVerifError
double IG.Neural.Forms.Old.FormNeural1DOld.tmpAvgMinVerifError = 1.0 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.CleanseGraph(), and IG.Neural.Forms.Old.FormNeural1DOld.Prediction().
abc
double IG.Neural.Forms.Old.FormNeural1DOld.abc = 0 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.Prediction().
equation
string IG.Neural.Forms.Old.FormNeural1DOld.equation = "x*x" private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.cbEquation_SelectedIndexChanged(), IG.Neural.Forms.Old.FormNeural1DOld.createFunction(), and IG.Neural.Forms.Old.FormNeural1DOld.tbSelfMadeEquation_TextChanged().
pane
GraphPane IG.Neural.Forms.Old.FormNeural1DOld.pane private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btnGenerateOptData_Click(), IG.Neural.Forms.Old.FormNeural1DOld.GraphDimensions(), and IG.Neural.Forms.Old.FormNeural1DOld.LoadForm().
trainingPoints
LineItem IG.Neural.Forms.Old.FormNeural1DOld.trainingPoints private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), IG.Neural.Forms.Old.FormNeural1DOld.CleanseGraph(), IG.Neural.Forms.Old.FormNeural1DOld.EnableControls(), and IG.Neural.Forms.Old.FormNeural1DOld.WriteTrainingPoints().
approximatedLine
LineItem [] IG.Neural.Forms.Old.FormNeural1DOld.approximatedLine private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.CleanseGraph(), and IG.Neural.Forms.Old.FormNeural1DOld.Stop().
defaultFunction
LineItem IG.Neural.Forms.Old.FormNeural1DOld.defaultFunction private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.CleanseGraph(), and IG.Neural.Forms.Old.FormNeural1DOld.WriteDefaultFunction().
enabledColor
readonly Color IG.Neural.Forms.Old.FormNeural1DOld.enabledColor = Color.Tomato static private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btStart_Click(), IG.Neural.Forms.Old.FormNeural1DOld.EnableControls(), and IG.Neural.Forms.Old.FormNeural1DOld.WriteTrainingPoints().
disabledColor
readonly Color IG.Neural.Forms.Old.FormNeural1DOld.disabledColor = Color.Goldenrod static private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.EnableControls().
components
System.ComponentModel.IContainer IG.Neural.Forms.Old.FormNeural1DOld.components = null private
Required designer variable.
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.Dispose(), and IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
functionGraph
ZedGraph.ZedGraphControl IG.Neural.Forms.Old.FormNeural1DOld.functionGraph private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.CleanseGraph(), IG.Neural.Forms.Old.FormNeural1DOld.EnableControls(), IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), IG.Neural.Forms.Old.FormNeural1DOld.LoadForm(), IG.Neural.Forms.Old.FormNeural1DOld.Stop(), IG.Neural.Forms.Old.FormNeural1DOld.WriteDefaultFunction(), and IG.Neural.Forms.Old.FormNeural1DOld.WriteTrainingPoints().
btStart
System.Windows.Forms.Button IG.Neural.Forms.Old.FormNeural1DOld.btStart private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.WriteTrainingPoints().
btnReset
System.Windows.Forms.Button IG.Neural.Forms.Old.FormNeural1DOld.btnReset private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
tbMaxError
System.Windows.Forms.TextBox IG.Neural.Forms.Old.FormNeural1DOld.tbMaxError private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.Prediction().
label1
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.label1 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
label2
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.label2 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
tbAverageError
System.Windows.Forms.TextBox IG.Neural.Forms.Old.FormNeural1DOld.tbAverageError private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.Prediction().
cbxAforge
System.Windows.Forms.CheckBox IG.Neural.Forms.Old.FormNeural1DOld.cbxAforge private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.cbxAforge_CheckedChanged(), IG.Neural.Forms.Old.FormNeural1DOld.cbxNeuron_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
cbxNeuron
System.Windows.Forms.CheckBox IG.Neural.Forms.Old.FormNeural1DOld.cbxNeuron private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.cbxAforge_CheckedChanged(), IG.Neural.Forms.Old.FormNeural1DOld.cbxNeuron_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
label3
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.label3 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
label4
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.label4 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
label5
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.label5 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
label6
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.label6 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
label7
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.label7 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
label8
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.label8 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
numMaxEpoch
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural1DOld.numMaxEpoch private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.numMaxEpoch_ValueChanged().
numEpochBundle
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural1DOld.numEpochBundle private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.numEpochBundle_ValueChanged().
numRMS
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural1DOld.numRMS private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.numRMS_ValueChanged().
numLearningRate
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural1DOld.numLearningRate private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.numLearningRate_ValueChanged().
numMomentum
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural1DOld.numMomentum private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.numMomentum_ValueChanged().
label9
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.label9 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
numSamples
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural1DOld.numSamples private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.numSamples_ValueChanged().
numHiddenNeuron
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural1DOld.numHiddenNeuron private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.numHiddenNeuron_ValueChanged().
label11
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.label11 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
btnGenerateOptData
System.Windows.Forms.Button IG.Neural.Forms.Old.FormNeural1DOld.btnGenerateOptData private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
tbAvgTrainError
System.Windows.Forms.TextBox IG.Neural.Forms.Old.FormNeural1DOld.tbAvgTrainError private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.Prediction().
label12
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.label12 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
label13
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.label13 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
tbMaxTrainError
System.Windows.Forms.TextBox IG.Neural.Forms.Old.FormNeural1DOld.tbMaxTrainError private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.Prediction().
numLowLimit
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural1DOld.numLowLimit private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.numLowLimit_ValueChanged().
numHighLimit
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural1DOld.numHighLimit private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.numHighLimit_ValueChanged().
label14
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.label14 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
numInputSafety
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural1DOld.numInputSafety private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.numInputSafety_ValueChanged().
label15
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.label15 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
numOutputSafety
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural1DOld.numOutputSafety private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.numOutputSafety_ValueChanged().
label16
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.label16 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
tbAvgMinTrainError
System.Windows.Forms.TextBox IG.Neural.Forms.Old.FormNeural1DOld.tbAvgMinTrainError private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.cbMultipleThread_CheckedChanged(), IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.Prediction().
tbMaxMinTrainError
System.Windows.Forms.TextBox IG.Neural.Forms.Old.FormNeural1DOld.tbMaxMinTrainError private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.cbMultipleThread_CheckedChanged(), IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.Prediction().
tbAverageMinError
System.Windows.Forms.TextBox IG.Neural.Forms.Old.FormNeural1DOld.tbAverageMinError private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.cbMultipleThread_CheckedChanged(), IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.Prediction().
tbMaxMinError
System.Windows.Forms.TextBox IG.Neural.Forms.Old.FormNeural1DOld.tbMaxMinError private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.cbMultipleThread_CheckedChanged(), IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.Prediction().
label17
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.label17 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
labelMaxError
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.labelMaxError private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.cbMultipleThread_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
cbMultipleThread
System.Windows.Forms.CheckBox IG.Neural.Forms.Old.FormNeural1DOld.cbMultipleThread private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.cbMultipleThread_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
numThreads
System.Windows.Forms.NumericUpDown IG.Neural.Forms.Old.FormNeural1DOld.numThreads private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.cbMultipleThread_CheckedChanged(), IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.numThreads_ValueChanged().
labMultipleThread
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.labMultipleThread private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.cbMultipleThread_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
label19
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.label19 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
tbEquationError
System.Windows.Forms.TextBox IG.Neural.Forms.Old.FormNeural1DOld.tbEquationError private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btnGenerateOptData_Click(), IG.Neural.Forms.Old.FormNeural1DOld.createFunction(), and IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
cbEquation
System.Windows.Forms.ComboBox IG.Neural.Forms.Old.FormNeural1DOld.cbEquation private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.cbEquation_SelectedIndexChanged(), IG.Neural.Forms.Old.FormNeural1DOld.cbSelfMade_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
cbRandomData
System.Windows.Forms.CheckBox IG.Neural.Forms.Old.FormNeural1DOld.cbRandomData private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.btnGenerateOptData_Click(), and IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
label10
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.label10 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
label20
System.Windows.Forms.Label IG.Neural.Forms.Old.FormNeural1DOld.label20 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
cbSelfMade
System.Windows.Forms.CheckBox IG.Neural.Forms.Old.FormNeural1DOld.cbSelfMade private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.cbSelfMade_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
tbSelfMadeEquation
System.Windows.Forms.TextBox IG.Neural.Forms.Old.FormNeural1DOld.tbSelfMadeEquation private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.cbSelfMade_CheckedChanged(), IG.Neural.Forms.Old.FormNeural1DOld.createFunction(), IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent(), and IG.Neural.Forms.Old.FormNeural1DOld.tbSelfMadeEquation_TextChanged().
bthelp
System.Windows.Forms.Button IG.Neural.Forms.Old.FormNeural1DOld.bthelp private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.cbSelfMade_CheckedChanged(), and IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
toolTip
System.Windows.Forms.ToolTip IG.Neural.Forms.Old.FormNeural1DOld.toolTip private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
zedGraphControl1
ZedGraph.ZedGraphControl IG.Neural.Forms.Old.FormNeural1DOld.zedGraphControl1 private
Referenced by IG.Neural.Forms.Old.FormNeural1DOld.InitializeComponent().
The documentation for this class was generated from the following files:
shelldev/lib/extended/LibNeuralExtForms/FormsOld/Old/FormNeural1DOld.cs
shelldev/lib/extended/LibNeuralExtForms/FormsOld/Old/FormNeural1DOld.Designer.cs