Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.XERBLA Class Reference
DotNumerics.LinearAlgebra.CSLapack.XERBLA Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
XERBLA ()
void Run (string SRNAME, int INFO)
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
XERBLA is an error handler for the LAPACK routines. It is called by an LAPACK routine if an input parameter has an invalid value. A message is printed and execution stops.
Installers may consider modifying the STOP statement in order to call system-specific exception-handling facilities.
/summary>
Constructor & Destructor Documentation
XERBLA()
DotNumerics.LinearAlgebra.CSLapack.XERBLA.XERBLA () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run (string SRNAME, int INFO) inline
Purpose
XERBLA is an error handler for the LAPACK routines. It is called by an LAPACK routine if an input parameter has an invalid value. A message is printed and execution stops.
Installers may consider modifying the STOP statement in order to call system-specific exception-handling facilities.
/summary>
Parameters
SRNAME (input) CHARACTER*6 The name of the routine which called XERBLA. /param>
Parameters
INFO (input) INTEGER The position of the invalid parameter in the parameter list of the calling routine. /param>
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASRT.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTERF.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRTI2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELQ2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGERQ2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGETRS.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGL2.Run(), DotNumerics.LinearAlgebra.CSLapack.DORG2R.Run(), DotNumerics.LinearAlgebra.CSLapack.DORG2L.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRTRI.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEHD2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBAK.Run(), DotNumerics.LinearAlgebra.CSLapack.DGBTF2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGER.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRTRS.Run(), DotNumerics.LinearAlgebra.CSLapack.DGETF2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGETRI.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELQF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGTSV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQPF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGBTRS.Run(), DotNumerics.LinearAlgebra.CSLapack.DGERQF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGETRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASQ2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASQ1.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGHR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.LinearAlgebra.CSLapack.DGESV.Run(), DotNumerics.LinearAlgebra.CSLapack.DDISNA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED9.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYTD2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGBTRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGLQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGTR.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGQL.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBAL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAEDA.Run(), DotNumerics.LinearAlgebra.CSLapack.DTZRZF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBD2.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYMV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGBSV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEHRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRCON.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARZT.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQP3.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARZB.Run(), DotNumerics.LinearAlgebra.CSLapack.DSBTRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRSV.Run(), DotNumerics.LinearAlgebra.CSLapack.DORM2L.Run(), DotNumerics.LinearAlgebra.CSLapack.DORM2R.Run(), DotNumerics.LinearAlgebra.CSLapack.DORML2.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYTRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMR3.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD8.Run(), DotNumerics.LinearAlgebra.CSLapack.DSBEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DTREXC.Run(), DotNumerics.LinearAlgebra.CSLapack.DLATRS.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD0.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMTR.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMLQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMQL.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMRQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYR2K.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGBR.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRSM.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED3.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMRZ.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED1.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED0.Run(), DotNumerics.LinearAlgebra.CSLapack.DTBSV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGRQF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGQRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMBR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD3.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGLSE.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED8.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASDQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALSD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGGLM.Run(), DotNumerics.LinearAlgebra.CSLapack.DTREVC.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEDC.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALSA.Run(), DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD1.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELS.Run(), DotNumerics.LinearAlgebra.CSLapack.DSBEVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD7.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD2.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYEVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DBDSDC.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGSVP.Run(), DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALS0.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED7.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELSY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASDA.Run(), DotNumerics.LinearAlgebra.CSLapack.DHSEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRMV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELSD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD6.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGSVD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DTGSJA.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/xerbla.cs