Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLASQ1 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLASQ1 Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLASQ1 (DCOPY dcopy, DLAS2 dlas2, DLASCL dlascl, DLASQ2 dlasq2, DLASRT dlasrt, XERBLA xerbla, DLAMCH dlamch)
DLASQ1 ()
void Run (int N, ref double[] D, int offset_d, double[] E, int offset_e, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
DCOPY _dcopy
DLAS2 _dlas2
DLASCL _dlascl
DLASQ2 _dlasq2
DLASRT _dlasrt
XERBLA _xerbla
DLAMCH _dlamch
Static Private Attributes
const double ZERO = 0.0E0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLASQ1 computes the singular values of a real N-by-N bidiagonal matrix with diagonal D and off-diagonal E. The singular values are computed to high relative accuracy, in the absence of denormalization, underflow and overflow. The algorithm was first presented in
"Accurate singular values and differential qd algorithms" by K. V. Fernando and B. N. Parlett, Numer. Math., Vol-67, No. 2, pp. 191-230, 1994,
and the present implementation is described in "An implementation of the dqds Algorithm (Positive Case)", LAPACK Working Note.
/summary>
Constructor & Destructor Documentation
DLASQ1() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLASQ1.DLASQ1 (DCOPY dcopy, DLAS2 dlas2, DLASCL dlascl, DLASQ2 dlasq2, DLASRT dlasrt, XERBLA xerbla, DLAMCH dlamch) inline
DLASQ1() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLASQ1.DLASQ1 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLASQ1.Run (int N, ref double[] D, int offset_d, double[] E, int offset_e, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
DLASQ1 computes the singular values of a real N-by-N bidiagonal matrix with diagonal D and off-diagonal E. The singular values are computed to high relative accuracy, in the absence of denormalization, underflow and overflow. The algorithm was first presented in
"Accurate singular values and differential qd algorithms" by K. V. Fernando and B. N. Parlett, Numer. Math., Vol-67, No. 2, pp. 191-230, 1994,
and the present implementation is described in "An implementation of the dqds Algorithm (Positive Case)", LAPACK Working Note.
/summary>
Parameters
N (input) INTEGER The number of rows and columns in the matrix. N .GE. 0. /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension (N) On entry, D contains the diagonal elements of the bidiagonal matrix whose SVD is desired. On normal exit, D contains the singular values in decreasing order. /param>
Parameters
E (input/output) DOUBLE PRECISION array, dimension (N) On entry, elements E(1:N-1) contain the off-diagonal elements of the bidiagonal matrix whose SVD is desired. On exit, E is overwritten. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (4*N) /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value .GT. 0: the algorithm failed = 1, a split was marked by a positive value in E = 2, current block of Z not diagonalized after 30*N iterations (in inner while loop) = 3, termination criterion of outer while loop not met (program created more than N unreduced blocks) /param>
References DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAS2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASRT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASQ2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLASQ1.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run().
Member Data Documentation
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLASQ1._dcopy private
_dlas2
DLAS2 DotNumerics.LinearAlgebra.CSLapack.DLASQ1._dlas2 private
_dlascl
DLASCL DotNumerics.LinearAlgebra.CSLapack.DLASQ1._dlascl private
_dlasq2
DLASQ2 DotNumerics.LinearAlgebra.CSLapack.DLASQ1._dlasq2 private
_dlasrt
DLASRT DotNumerics.LinearAlgebra.CSLapack.DLASQ1._dlasrt private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLASQ1._xerbla private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLASQ1._dlamch private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLASQ1.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASQ1.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlasq1.cs