Doc: IGLib EXTENDED: FuzzyAGV.MainForm Class Reference
FuzzyAGV.MainForm Class Reference
Public Member Functions
MainForm ()
Static Public Member Functions
static void Main ()
The main entry point for the application.
Protected Member Functions
override void Dispose (bool disposing)
Stoping the movement thread
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitFuzzyEngine ()
void DoInference ()
void pbTerrain_MouseDown (object sender, System.Windows.Forms.MouseEventArgs e)
void pbTerrain_MouseMove (object sender, System.Windows.Forms.MouseEventArgs e)
void GetMeasures ()
int GetDistance (Point p1, Point p2)
Point GetObstacle (Point Start, Bitmap Map, int Inc, int AngleOffset)
Bitmap CopyImage (Bitmap Src)
void btnReset_Click (object sender, System.EventArgs e)
void MoveAGV ()
void btnRun_Click (object sender, System.EventArgs e)
void button3_Click (object sender, System.EventArgs e)
void StartMovement ()
void MoveCycle ()
void AGVStep ()
void StopMovement ()
void aboutButton_Click (object sender, EventArgs e)
Private Attributes
string RunLabel
Point InitialPos
bool FirstInference
int LastX
int LastY
double Angle
Bitmap OriginalMap
Bitmap InitialMap
InferenceSystem IS
Thread thMovement
System.Windows.Forms.PictureBox pbTerrain
Required designer variable.
System.Windows.Forms.Button btnRun
System.Windows.Forms.TextBox txtInterval
System.Windows.Forms.CheckBox cbLasers
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.Label txtRight
System.Windows.Forms.Label txtLeft
System.Windows.Forms.Label txtFront
System.Windows.Forms.Label lbl
System.Windows.Forms.Label label2
System.Windows.Forms.Label label1
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.Label label3
System.Windows.Forms.Label txtAngle
System.Windows.Forms.Button btnStep
System.Windows.Forms.Label label4
System.Windows.Forms.PictureBox pbRobot
System.Windows.Forms.Button btnReset
System.Windows.Forms.GroupBox gbComandos
System.ComponentModel.Container components = null
GroupBox groupBox3
Label label5
Button aboutButton
System.Windows.Forms.CheckBox cbTrajeto
Constructor & Destructor Documentation
MainForm()
FuzzyAGV.MainForm.MainForm () inline
References FuzzyAGV.MainForm.Angle, FuzzyAGV.MainForm.btnRun, FuzzyAGV.MainForm.FirstInference, FuzzyAGV.MainForm.InitFuzzyEngine(), FuzzyAGV.MainForm.InitializeComponent(), FuzzyAGV.MainForm.InitialMap, FuzzyAGV.MainForm.InitialPos, FuzzyAGV.MainForm.OriginalMap, FuzzyAGV.MainForm.pbRobot, FuzzyAGV.MainForm.pbTerrain, and FuzzyAGV.MainForm.RunLabel.
Referenced by FuzzyAGV.MainForm.Main().
Member Function Documentation
Main()
static void FuzzyAGV.MainForm.Main () inline static
The main entry point for the application.
References FuzzyAGV.MainForm.MainForm().
Dispose()
override void FuzzyAGV.MainForm.Dispose (bool disposing) inline protected
Stoping the movement thread
References FuzzyAGV.MainForm.components, and FuzzyAGV.MainForm.StopMovement().
InitializeComponent()
void FuzzyAGV.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by FuzzyAGV.MainForm.MainForm().
InitFuzzyEngine()
void FuzzyAGV.MainForm.InitFuzzyEngine () inline private
References AForge.Fuzzy.LinguisticVariable.AddLabel(), AForge.Fuzzy.Database.AddVariable(), FuzzyAGV.MainForm.IS, and AForge.Fuzzy.InferenceSystem.NewRule().
Referenced by FuzzyAGV.MainForm.MainForm().
DoInference()
void FuzzyAGV.MainForm.DoInference () inline private
References FuzzyAGV.MainForm.Angle, AForge.Fuzzy.InferenceSystem.Evaluate(), FuzzyAGV.MainForm.IS, AForge.Fuzzy.InferenceSystem.SetInput(), FuzzyAGV.MainForm.txtAngle, FuzzyAGV.MainForm.txtFront, FuzzyAGV.MainForm.txtLeft, and FuzzyAGV.MainForm.txtRight.
Referenced by FuzzyAGV.MainForm.AGVStep().
pbTerrain_MouseDown()
void FuzzyAGV.MainForm.pbTerrain_MouseDown (object sender, System.Windows.Forms.MouseEventArgs e) inline private
References FuzzyAGV.MainForm.CopyImage(), FuzzyAGV.MainForm.LastX, FuzzyAGV.MainForm.LastY, FuzzyAGV.MainForm.OriginalMap, and FuzzyAGV.MainForm.pbTerrain.
pbTerrain_MouseMove()
void FuzzyAGV.MainForm.pbTerrain_MouseMove (object sender, System.Windows.Forms.MouseEventArgs e) inline private
References FuzzyAGV.MainForm.CopyImage(), FuzzyAGV.MainForm.LastX, FuzzyAGV.MainForm.LastY, FuzzyAGV.MainForm.OriginalMap, and FuzzyAGV.MainForm.pbTerrain.
GetMeasures()
void FuzzyAGV.MainForm.GetMeasures () inline private
References FuzzyAGV.MainForm.btnRun, FuzzyAGV.MainForm.btnRun_Click(), FuzzyAGV.MainForm.cbLasers, FuzzyAGV.MainForm.CopyImage(), FuzzyAGV.MainForm.GetDistance(), FuzzyAGV.MainForm.GetObstacle(), FuzzyAGV.MainForm.OriginalMap, FuzzyAGV.MainForm.pbRobot, FuzzyAGV.MainForm.pbTerrain, FuzzyAGV.MainForm.RunLabel, FuzzyAGV.MainForm.txtFront, FuzzyAGV.MainForm.txtLeft, FuzzyAGV.MainForm.txtRight, AForge.Point.X, and AForge.Point.Y.
Referenced by FuzzyAGV.MainForm.AGVStep().
GetDistance()
int FuzzyAGV.MainForm.GetDistance (Point p1, Point p2) inline private
References AForge.Point.X, and AForge.Point.Y.
Referenced by FuzzyAGV.MainForm.GetMeasures().
GetObstacle()
Point FuzzyAGV.MainForm.GetObstacle (Point Start, Bitmap Map, int Inc, int AngleOffset) inline private
References FuzzyAGV.MainForm.Angle, AForge.Point.X, and AForge.Point.Y.
Referenced by FuzzyAGV.MainForm.GetMeasures().
CopyImage()
Bitmap FuzzyAGV.MainForm.CopyImage (Bitmap Src) inline private
Referenced by FuzzyAGV.MainForm.btnRun_Click(), FuzzyAGV.MainForm.GetMeasures(), FuzzyAGV.MainForm.pbTerrain_MouseDown(), and FuzzyAGV.MainForm.pbTerrain_MouseMove().
btnReset_Click()
void FuzzyAGV.MainForm.btnReset_Click (object sender, System.EventArgs e) inline private
References FuzzyAGV.MainForm.Angle, FuzzyAGV.MainForm.FirstInference, FuzzyAGV.MainForm.InitialMap, FuzzyAGV.MainForm.InitialPos, FuzzyAGV.MainForm.OriginalMap, FuzzyAGV.MainForm.pbRobot, FuzzyAGV.MainForm.pbTerrain, FuzzyAGV.MainForm.txtAngle, FuzzyAGV.MainForm.txtFront, FuzzyAGV.MainForm.txtLeft, and FuzzyAGV.MainForm.txtRight.
MoveAGV()
void FuzzyAGV.MainForm.MoveAGV () inline private
References FuzzyAGV.MainForm.Angle, FuzzyAGV.MainForm.cbTrajeto, FuzzyAGV.MainForm.OriginalMap, FuzzyAGV.MainForm.pbRobot, FuzzyAGV.MainForm.pbTerrain, AForge.Point.X, and AForge.Point.Y.
Referenced by FuzzyAGV.MainForm.AGVStep().
btnRun_Click()
void FuzzyAGV.MainForm.btnRun_Click (object sender, System.EventArgs e) inline private
References FuzzyAGV.MainForm.btnReset, FuzzyAGV.MainForm.btnStep, FuzzyAGV.MainForm.cbLasers, FuzzyAGV.MainForm.cbTrajeto, FuzzyAGV.MainForm.CopyImage(), FuzzyAGV.MainForm.OriginalMap, FuzzyAGV.MainForm.pbRobot, FuzzyAGV.MainForm.pbTerrain, FuzzyAGV.MainForm.RunLabel, FuzzyAGV.MainForm.StartMovement(), FuzzyAGV.MainForm.StopMovement(), and FuzzyAGV.MainForm.txtInterval.
Referenced by FuzzyAGV.MainForm.GetMeasures().
button3_Click()
void FuzzyAGV.MainForm.button3_Click (object sender, System.EventArgs e) inline private
References FuzzyAGV.MainForm.AGVStep(), and FuzzyAGV.MainForm.pbRobot.
StartMovement()
void FuzzyAGV.MainForm.StartMovement () inline private
References FuzzyAGV.MainForm.MoveCycle(), and FuzzyAGV.MainForm.thMovement.
Referenced by FuzzyAGV.MainForm.btnRun_Click().
MoveCycle()
void FuzzyAGV.MainForm.MoveCycle () inline private
References FuzzyAGV.MainForm.AGVStep(), and FuzzyAGV.MainForm.txtInterval.
Referenced by FuzzyAGV.MainForm.StartMovement().
AGVStep()
void FuzzyAGV.MainForm.AGVStep () inline private
References FuzzyAGV.MainForm.DoInference(), FuzzyAGV.MainForm.FirstInference, FuzzyAGV.MainForm.GetMeasures(), and FuzzyAGV.MainForm.MoveAGV().
Referenced by FuzzyAGV.MainForm.button3_Click(), and FuzzyAGV.MainForm.MoveCycle().
StopMovement()
void FuzzyAGV.MainForm.StopMovement () inline private
References FuzzyAGV.MainForm.thMovement.
Referenced by FuzzyAGV.MainForm.btnRun_Click(), and FuzzyAGV.MainForm.Dispose().
aboutButton_Click()
void FuzzyAGV.MainForm.aboutButton_Click (object sender, EventArgs e) inline private
Member Data Documentation
RunLabel
string FuzzyAGV.MainForm.RunLabel private
Referenced by FuzzyAGV.MainForm.btnRun_Click(), FuzzyAGV.MainForm.GetMeasures(), and FuzzyAGV.MainForm.MainForm().
InitialPos
Point FuzzyAGV.MainForm.InitialPos private
Referenced by FuzzyAGV.MainForm.btnReset_Click(), and FuzzyAGV.MainForm.MainForm().
FirstInference
bool FuzzyAGV.MainForm.FirstInference private
Referenced by FuzzyAGV.MainForm.AGVStep(), FuzzyAGV.MainForm.btnReset_Click(), and FuzzyAGV.MainForm.MainForm().
LastX
int FuzzyAGV.MainForm.LastX private
Referenced by FuzzyAGV.MainForm.pbTerrain_MouseDown(), and FuzzyAGV.MainForm.pbTerrain_MouseMove().
LastY
int FuzzyAGV.MainForm.LastY private
Referenced by FuzzyAGV.MainForm.pbTerrain_MouseDown(), and FuzzyAGV.MainForm.pbTerrain_MouseMove().
Angle
double FuzzyAGV.MainForm.Angle private
Referenced by FuzzyAGV.MainForm.btnReset_Click(), FuzzyAGV.MainForm.DoInference(), FuzzyAGV.MainForm.GetObstacle(), FuzzyAGV.MainForm.MainForm(), and FuzzyAGV.MainForm.MoveAGV().
OriginalMap
Bitmap FuzzyAGV.MainForm.OriginalMap private
Referenced by FuzzyAGV.MainForm.btnReset_Click(), FuzzyAGV.MainForm.btnRun_Click(), FuzzyAGV.MainForm.GetMeasures(), FuzzyAGV.MainForm.MainForm(), FuzzyAGV.MainForm.MoveAGV(), FuzzyAGV.MainForm.pbTerrain_MouseDown(), and FuzzyAGV.MainForm.pbTerrain_MouseMove().
InitialMap
Bitmap FuzzyAGV.MainForm.InitialMap private
Referenced by FuzzyAGV.MainForm.btnReset_Click(), and FuzzyAGV.MainForm.MainForm().
IS
InferenceSystem FuzzyAGV.MainForm.IS private
Referenced by FuzzyAGV.MainForm.DoInference(), and FuzzyAGV.MainForm.InitFuzzyEngine().
thMovement
Thread FuzzyAGV.MainForm.thMovement private
Referenced by FuzzyAGV.MainForm.StartMovement(), and FuzzyAGV.MainForm.StopMovement().
pbTerrain
System.Windows.Forms.PictureBox FuzzyAGV.MainForm.pbTerrain private
Required designer variable.
Referenced by FuzzyAGV.MainForm.btnReset_Click(), FuzzyAGV.MainForm.btnRun_Click(), FuzzyAGV.MainForm.GetMeasures(), FuzzyAGV.MainForm.MainForm(), FuzzyAGV.MainForm.MoveAGV(), FuzzyAGV.MainForm.pbTerrain_MouseDown(), and FuzzyAGV.MainForm.pbTerrain_MouseMove().
btnRun
System.Windows.Forms.Button FuzzyAGV.MainForm.btnRun private
Referenced by FuzzyAGV.MainForm.GetMeasures(), and FuzzyAGV.MainForm.MainForm().
txtInterval
System.Windows.Forms.TextBox FuzzyAGV.MainForm.txtInterval private
Referenced by FuzzyAGV.MainForm.btnRun_Click(), and FuzzyAGV.MainForm.MoveCycle().
cbLasers
System.Windows.Forms.CheckBox FuzzyAGV.MainForm.cbLasers private
Referenced by FuzzyAGV.MainForm.btnRun_Click(), and FuzzyAGV.MainForm.GetMeasures().
groupBox1
System.Windows.Forms.GroupBox FuzzyAGV.MainForm.groupBox1 private
txtRight
System.Windows.Forms.Label FuzzyAGV.MainForm.txtRight private
Referenced by FuzzyAGV.MainForm.btnReset_Click(), FuzzyAGV.MainForm.DoInference(), and FuzzyAGV.MainForm.GetMeasures().
txtLeft
System.Windows.Forms.Label FuzzyAGV.MainForm.txtLeft private
Referenced by FuzzyAGV.MainForm.btnReset_Click(), FuzzyAGV.MainForm.DoInference(), and FuzzyAGV.MainForm.GetMeasures().
txtFront
System.Windows.Forms.Label FuzzyAGV.MainForm.txtFront private
Referenced by FuzzyAGV.MainForm.btnReset_Click(), FuzzyAGV.MainForm.DoInference(), and FuzzyAGV.MainForm.GetMeasures().
lbl
System.Windows.Forms.Label FuzzyAGV.MainForm.lbl private
label2
System.Windows.Forms.Label FuzzyAGV.MainForm.label2 private
label1
System.Windows.Forms.Label FuzzyAGV.MainForm.label1 private
groupBox2
System.Windows.Forms.GroupBox FuzzyAGV.MainForm.groupBox2 private
label3
System.Windows.Forms.Label FuzzyAGV.MainForm.label3 private
txtAngle
System.Windows.Forms.Label FuzzyAGV.MainForm.txtAngle private
Referenced by FuzzyAGV.MainForm.btnReset_Click(), and FuzzyAGV.MainForm.DoInference().
btnStep
System.Windows.Forms.Button FuzzyAGV.MainForm.btnStep private
Referenced by FuzzyAGV.MainForm.btnRun_Click().
label4
System.Windows.Forms.Label FuzzyAGV.MainForm.label4 private
pbRobot
System.Windows.Forms.PictureBox FuzzyAGV.MainForm.pbRobot private
Referenced by FuzzyAGV.MainForm.btnReset_Click(), FuzzyAGV.MainForm.btnRun_Click(), FuzzyAGV.MainForm.button3_Click(), FuzzyAGV.MainForm.GetMeasures(), FuzzyAGV.MainForm.MainForm(), and FuzzyAGV.MainForm.MoveAGV().
btnReset
System.Windows.Forms.Button FuzzyAGV.MainForm.btnReset private
Referenced by FuzzyAGV.MainForm.btnRun_Click().
gbComandos
System.Windows.Forms.GroupBox FuzzyAGV.MainForm.gbComandos private
components
System.ComponentModel.Container FuzzyAGV.MainForm.components = null private
Referenced by FuzzyAGV.MainForm.Dispose().
groupBox3
GroupBox FuzzyAGV.MainForm.groupBox3 private
label5
Label FuzzyAGV.MainForm.label5 private
aboutButton
Button FuzzyAGV.MainForm.aboutButton private
cbTrajeto
System.Windows.Forms.CheckBox FuzzyAGV.MainForm.cbTrajeto private
Referenced by FuzzyAGV.MainForm.btnRun_Click(), and FuzzyAGV.MainForm.MoveAGV().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Samples/Fuzzy/FuzzyAGV/MainForm.cs