Doc: IGLib EXTENDED: IG.Forms.ScalarFunctionScriptControl Class Reference
IG.Forms.ScalarFunctionScriptControl Class Reference
Control for definition of scalar functions by user defined expressions (through a script loader).
Public Member Functions
ScalarFunctionScriptControl ()
Constructs the scalar function script control.
ScalarFunctionScriptControl (bool setTestDefinitions)
Constructs the scalar function script control.
void SetTestDefinitions ()
Setts a test definition.
bool HasParentUnsavedChanges (bool set=false)
Get or sets a flag indicating whether the parent control has unsaved changes.
void CopyDataFromController ()
Copies data from the internal DTO to the current control.
void ResetFunctionDefinition ()
Resets function definition to simply "0". Gradients are redefined accordingly.
string CreateFunctonSummary ()
ScalarFunctionScriptControl ()
void CopyDataFromController ()
Copies data from the internal DTO to the current control.
void ResetFunctionDefinition ()
Resets function definition to simply "0". Gradients are redefined accordingly.
string CreateFunctonSummary ()
ScalarFunctionScriptControl ()
Constructs the scalar function script control.
ScalarFunctionScriptControl (bool setTestDefinitions)
Constructs the scalar function script control.
void SetTestDefinitions ()
Setts a test definition.
bool HasParentUnsavedChanges (bool set=false)
Get or sets a flag indicating whether the parent control has unsaved changes.
void CopyDataFromController ()
Copies data from the internal DTO to the current control.
void ResetFunctionDefinition ()
Resets function definition to simply "0". Gradients are redefined accordingly.
string CreateFunctonSummary ()
ScalarFunctionScriptControl ()
Constructs the scalar function script control.
ScalarFunctionScriptControl (bool setTestDefinitions)
Constructs the scalar function script control.
void SetTestDefinitions ()
Setts a test definition.
bool HasParentUnsavedChanges (bool set=false)
Get or sets a flag indicating whether the parent control has unsaved changes.
void CopyDataFromController ()
Copies data from the internal DTO to the current control.
void ResetFunctionDefinition ()
Resets function definition to simply "0". Gradients are redefined accordingly.
string CreateFunctonSummary ()
Protected Member Functions
string GetFunctionSignature ()
Returns function signature created from the data.
override void Dispose (bool disposing)
Clean up any resources being used.
string GetFunctionSignature ()
Returns function signature created from the data.
override void Dispose (bool disposing)
Clean up any resources being used.
string GetFunctionSignature ()
Returns function signature created from the data.
override void Dispose (bool disposing)
Clean up any resources being used.
string GetFunctionSignature ()
Returns function signature created from the data.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
bool _isGradientDefined = false
string[] _gradientDefinitions
Properties
IG.Lib.IReporter Reporter [get]
Reporter used for internal reporting.
string FunctionNameTitleNormal [get, set]
Normal text of the label that introduces function name input box.
string FunctionNameTitleModified [get, set]
Normal text of the label that introduces function name input box.
ScalarFunctionScriptController FunctionController [get, set]
Cotroller that holds the definition data of the scalar function entered by the current control, and also holds mechanism for compiling and loading scalar function from these definitions.
ScalarFunctionLoader FunctionLoader [get, protected set]
Scalar function loader that is responsible for creation of scalar function objects from data.
LoadableScalarFunctionBase Function [get]
Gets the function generated by the function loader.
VectorFunctionScriptControl VectorFunctionControl [get, set]
The parent vector function script control. When this control is embedded within the vector function script control, this property should be set such that communication back to parent is enabled (in particular, communication about unsaved changes).
bool HasUnsavedChanges [get, set, protected set]
Whether the current function definition has unsaved changes.
bool IsLoaderConsistent [get, protected set]
Whether function loader is in consistent state.
string FunctionName [get, set]
Name of the function.
string FunctionDescription [get, set]
int Dimension [get, set]
Gets or sets function dimension.
string[] ParameterNames [get, set]
Names of function parameters.
string ValueDefinition [get, set]
String that defines function value.
bool IsGradientDefined [get, set]
string[] GradientDefinitions [get, set]
String that defines function gradients.
InputOutputDataDefiniton DataDefinition [get, set]
Definition of input and output data for the represented scalar function.
FileSelector FileSelector [get]
GUI component for seclecting files.
Private Member Functions
void CopyDataToController ()
Copies data from the current control to the internal function DTO.
void btnSummary_Click (object sender, EventArgs e)
void txtName_Validated (object sender, EventArgs e)
void txtDescription_Validated (object sender, EventArgs e)
void txtParameterNames_Validated (object sender, EventArgs e)
void numDimension_Validated (object sender, EventArgs e)
void txtValue_Validated (object sender, EventArgs e)
void txtGradients_Validated (object sender, EventArgs e)
void chkGradients_CheckedChanged (object sender, EventArgs e)
void btnCreateFunction_Click (object sender, EventArgs e)
Creates a function i advance (before it is eeded for any other operation). Error message is launched if creation is not successful.
void btnValueCalculator_Click (object sender, EventArgs e)
Launches value calculator where user can calculate functio values with the function that was defined in the current control.
void btnPlot1d_Click (object sender, EventArgs e)
Launches 1D parametric plots of the function defined in this control.
void btnPlot2d_Click (object sender, EventArgs e)
Launches 2D parametric plots of the function defined in this control.
void btnSave_Click (object sender, EventArgs e)
Saves the current fucntion definition to a JSON file.
void btnLoad_Click (object sender, EventArgs e)
Loads the current function definition from a JSON file.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void CopyDataToController ()
Copies data from the current control to the internal function DTO.
void btnSummary_Click (object sender, EventArgs e)
void txtName_Validated (object sender, EventArgs e)
void txtDescription_Validated (object sender, EventArgs e)
void txtParameterNames_Validated (object sender, EventArgs e)
void numDimension_Validated (object sender, EventArgs e)
void txtValue_Validated (object sender, EventArgs e)
void txtGradients_Validated (object sender, EventArgs e)
void chkGradients_CheckedChanged (object sender, EventArgs e)
void btnCreateFunction_Click (object sender, EventArgs e)
Creates a function i advance (before it is eeded for any other operation). Error message is launched if creation is not successful.
void btnValueCalculator_Click (object sender, EventArgs e)
Launches value calculator where user can calculate functio values with the function that was defined in the current control.
void btnPlot1d_Click (object sender, EventArgs e)
Launches 1D parametric plots of the function defined in this control.
void btnPlot2d_Click (object sender, EventArgs e)
Launches 2D parametric plots of the function defined in this control.
void btnSave_Click (object sender, EventArgs e)
Saves the current fucntion definition to a JSON file.
void btnLoad_Click (object sender, EventArgs e)
Loads the current function definition from a JSON file.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void CopyDataToController ()
Copies data from the current control to the internal function DTO.
void btnSummary_Click (object sender, EventArgs e)
void txtName_Validated (object sender, EventArgs e)
void txtDescription_Validated (object sender, EventArgs e)
void txtParameterNames_Validated (object sender, EventArgs e)
void numDimension_Validated (object sender, EventArgs e)
void txtValue_Validated (object sender, EventArgs e)
void txtGradients_Validated (object sender, EventArgs e)
void chkGradients_CheckedChanged (object sender, EventArgs e)
void btnCreateFunction_Click (object sender, EventArgs e)
Creates a function i advance (before it is eeded for any other operation). Error message is launched if creation is not successful.
void btnValueCalculator_Click (object sender, EventArgs e)
Launches value calculator where user can calculate functio values with the function that was defined in the current control.
void btnPlot1d_Click (object sender, EventArgs e)
Launches 1D parametric plots of the function defined in this control.
void btnPlot2d_Click (object sender, EventArgs e)
Launches 2D parametric plots of the function defined in this control.
void btnSave_Click (object sender, EventArgs e)
Saves the current fucntion definition to a JSON file.
void btnLoad_Click (object sender, EventArgs e)
Loads the current function definition from a JSON file.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void CopyDataToController ()
Copies data from the current control to the internal function DTO.
void btnSummary_Click (object sender, EventArgs e)
void txtName_Validated (object sender, EventArgs e)
void txtDescription_Validated (object sender, EventArgs e)
void txtParameterNames_Validated (object sender, EventArgs e)
void numDimension_Validated (object sender, EventArgs e)
void txtValue_Validated (object sender, EventArgs e)
void txtGradients_Validated (object sender, EventArgs e)
void chkGradients_CheckedChanged (object sender, EventArgs e)
void btnCreateFunction_Click (object sender, EventArgs e)
Creates a function i advance (before it is eeded for any other operation). Error message is launched if creation is not successful.
void btnValueCalculator_Click (object sender, EventArgs e)
Launches value calculator where user can calculate functio values with the function that was defined in the current control.
void btnPlot1d_Click (object sender, EventArgs e)
Launches 1D parametric plots of the function defined in this control.
void btnPlot2d_Click (object sender, EventArgs e)
Launches 2D parametric plots of the function defined in this control.
void btnSave_Click (object sender, EventArgs e)
Saves the current fucntion definition to a JSON file.
void btnLoad_Click (object sender, EventArgs e)
Loads the current function definition from a JSON file.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
string _functionNameTitleNormal = "Function Name: "
string _functionNameTitleModified = "Function Name: (*)"
ScalarFunctionScriptController _functionController
VectorFunctionScriptControl _parentVectorFunctionControl = null
bool _hasUnsavedChanges = false
bool _isLoaderConsistent = false
Color _bgDefined = Color.White
Color _bgUndefined = Color.LightGray
InputOutputDataDefiniton _dataDefinition = null
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Label lblTitle
System.Windows.Forms.Label lblDimension
System.Windows.Forms.Label lblName
System.Windows.Forms.TextBox txtName
System.Windows.Forms.NumericUpDown numDimension
System.Windows.Forms.Panel pnlOuter
System.Windows.Forms.TextBox txtValue
System.Windows.Forms.Label lblValue
System.Windows.Forms.TextBox txtParameterNames
System.Windows.Forms.Label lblParameterNames
System.Windows.Forms.CheckBox chkGradients
System.Windows.Forms.Button btnValueCalculator
System.Windows.Forms.Button btnCreateFunction
System.Windows.Forms.TextBox txtGradients
System.Windows.Forms.Label label1
System.Windows.Forms.Label lblFunctionSignature
System.Windows.Forms.Button btnSummary
System.Windows.Forms.TextBox txtDescription
System.Windows.Forms.Label lblDescription
System.Windows.Forms.Button btnPlot1d
System.Windows.Forms.Button btnPlot2d
System.Windows.Forms.Button btnSave
FileSelector fileSelector1
System.Windows.Forms.Panel pnlParameters
System.Windows.Forms.Panel pnlValues
System.Windows.Forms.Panel pnlGradients
System.Windows.Forms.Panel pnlButtons
System.Windows.Forms.Panel pnlPlotButtons
System.Windows.Forms.Panel pnlBasic
System.Windows.Forms.Panel pnlTop
System.Windows.Forms.Panel pnlBasicAndTitle
System.Windows.Forms.Button btnLoad
Detailed Description
Control for definition of scalar functions by user defined expressions (through a script loader).
Control for definition of scalar functions by user defined expressions (through script loader).
$A Igor Jun14;
Constructor & Destructor Documentation
ScalarFunctionScriptControl() [1/7]
IG.Forms.ScalarFunctionScriptControl.ScalarFunctionScriptControl () inline
Constructs the scalar function script control.
References IG.Forms.ScalarFunctionScriptControl._bgDefined, IG.Forms.ScalarFunctionScriptControl.FunctionNameTitleNormal, IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, IG.Forms.ScalarFunctionScriptControl.InitializeComponent(), IG.Forms.ScalarFunctionScriptControl.lblName, and IG.Forms.ScalarFunctionScriptControl.txtValue.
ScalarFunctionScriptControl() [2/7]
IG.Forms.ScalarFunctionScriptControl.ScalarFunctionScriptControl (bool setTestDefinitions) inline
Constructs the scalar function script control.
Parameters
setTestDefinitions If true then control is filled with test definitions, such that the represented function can be immediately plotted, saved, etc.
Beside for debugging, this is convenient for testing by users who are not used to use the control.
References IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, and IG.Forms.ScalarFunctionScriptControl.SetTestDefinitions().
ScalarFunctionScriptControl() [3/7]
IG.Forms.ScalarFunctionScriptControl.ScalarFunctionScriptControl () inline
References IG.Forms.ScalarFunctionScriptControl._bgDefined, IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, IG.Forms.ScalarFunctionScriptControl.InitializeComponent(), IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Forms.ScalarFunctionScriptControl.ParameterNames, IG.Forms.ScalarFunctionScriptControl.txtValue, and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
ScalarFunctionScriptControl() [4/7]
IG.Forms.ScalarFunctionScriptControl.ScalarFunctionScriptControl () inline
Constructs the scalar function script control.
References IG.Forms.ScalarFunctionScriptControl._bgDefined, IG.Forms.ScalarFunctionScriptControl.FunctionNameTitleNormal, IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, IG.Forms.ScalarFunctionScriptControl.InitializeComponent(), IG.Forms.ScalarFunctionScriptControl.lblName, and IG.Forms.ScalarFunctionScriptControl.txtValue.
ScalarFunctionScriptControl() [5/7]
IG.Forms.ScalarFunctionScriptControl.ScalarFunctionScriptControl (bool setTestDefinitions) inline
Constructs the scalar function script control.
Parameters
setTestDefinitions If true then control is filled with test definitions, such that the represented function can be immediately plotted, saved, etc.
Beside for debugging, this is convenient for testing by users who are not used to use the control.
References IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, and IG.Forms.ScalarFunctionScriptControl.SetTestDefinitions().
ScalarFunctionScriptControl() [6/7]
IG.Forms.ScalarFunctionScriptControl.ScalarFunctionScriptControl () inline
Constructs the scalar function script control.
References IG.Forms.ScalarFunctionScriptControl._bgDefined, IG.Forms.ScalarFunctionScriptControl.FunctionNameTitleNormal, IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, IG.Forms.ScalarFunctionScriptControl.InitializeComponent(), IG.Forms.ScalarFunctionScriptControl.lblName, and IG.Forms.ScalarFunctionScriptControl.txtValue.
ScalarFunctionScriptControl() [7/7]
IG.Forms.ScalarFunctionScriptControl.ScalarFunctionScriptControl (bool setTestDefinitions) inline
Constructs the scalar function script control.
Parameters
setTestDefinitions If true then control is filled with test definitions, such that the represented function can be immediately plotted, saved, etc.
Beside for debugging, this is convenient for testing by users who are not used to use the control.
References IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, and IG.Forms.ScalarFunctionScriptControl.SetTestDefinitions().
Member Function Documentation
SetTestDefinitions() [1/3]
void IG.Forms.ScalarFunctionScriptControl.SetTestDefinitions () inline
Setts a test definition.
References IG.Forms.ScalarFunctionScriptControl.FunctionDescription, IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, IG.Forms.ScalarFunctionScriptControl.ParameterNames, and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
Referenced by IG.Forms.ScalarFunctionScriptControl.ScalarFunctionScriptControl().
HasParentUnsavedChanges() [1/3]
bool IG.Forms.ScalarFunctionScriptControl.HasParentUnsavedChanges (bool set = false) inline
Get or sets a flag indicating whether the parent control has unsaved changes.
The flag may only be set to false.
If there is no parent control (such as VectorFunctionScriptControl) then getter returns false and setter has no effect.
Parameters
set If true then the "Has unsaved changes" is set on the parent. Otherwise, only the value indicating whether the parent has unsaved changes is returned. Default value is false.
Returns
Flag indicating whether parent control had unsaved changes before this method was called.
References IG.Forms.VectorFunctionScriptControl.HasUnsavedChanges, and IG.Forms.ScalarFunctionScriptControl.VectorFunctionControl.
Referenced by IG.Forms.ScalarFunctionScriptControl.btnLoad_Click().
CopyDataToController() [1/4]
void IG.Forms.ScalarFunctionScriptControl.CopyDataToController () inline private
Copies data from the current control to the internal function DTO.
References IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ConvertParameterNamesToArray(), IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Description, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Dimension, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Name, IG.Forms.ScalarFunctionScriptControl.numDimension, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ParameterNames, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.SetGradientDefinitionSingleString(), IG.Forms.ScalarFunctionScriptControl.txtDescription, IG.Forms.ScalarFunctionScriptControl.txtGradients, IG.Forms.ScalarFunctionScriptControl.txtName, IG.Forms.ScalarFunctionScriptControl.txtParameterNames, IG.Forms.ScalarFunctionScriptControl.txtValue, and IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ValueDefinitonString.
CopyDataFromController() [1/4]
void IG.Forms.ScalarFunctionScriptControl.CopyDataFromController () inline
Copies data from the internal DTO to the current control.
References IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Description, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Dimension, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.GetFunctionSignature(), IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetGradientDefinitionSingleString(), IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetParametersString(), IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.IsGradientDefined, IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Forms.ScalarFunctionScriptControl.lblFunctionSignature, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Name, IG.Forms.ScalarFunctionScriptControl.numDimension, IG.Forms.ScalarFunctionScriptControl.txtDescription, IG.Forms.ScalarFunctionScriptControl.txtGradients, IG.Forms.ScalarFunctionScriptControl.txtName, IG.Forms.ScalarFunctionScriptControl.txtParameterNames, IG.Forms.ScalarFunctionScriptControl.txtValue, and IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ValueDefinitonString.
Referenced by IG.Forms.VectorFunctionScriptControl.SynchronizeData().
GetFunctionSignature() [1/4]
string IG.Forms.ScalarFunctionScriptControl.GetFunctionSignature () inline protected
Returns function signature created from the data.
References IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Lib.UtilStr.GetParametersStringPlain(), and IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ParameterNames.
Referenced by IG.Forms.ScalarFunctionScriptControl.CopyDataFromController().
ResetFunctionDefinition() [1/4]
void IG.Forms.ScalarFunctionScriptControl.ResetFunctionDefinition () inline
Resets function definition to simply "0". Gradients are redefined accordingly.
References IG.Forms.ScalarFunctionScriptControl.Dimension, IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
CreateFunctonSummary() [1/4]
string IG.Forms.ScalarFunctionScriptControl.CreateFunctonSummary () inline
References IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Lib.UtilStr.GetParametersStringPlain(), IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Forms.ScalarFunctionScriptControl.ParameterNames, IG.Forms.ScalarFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
Referenced by IG.Forms.ScalarFunctionScriptControl.btnSummary_Click(), and IG.Forms.ScalarFunctionScriptControl.btnValueCalculator_Click().
btnSummary_Click() [1/4]
void IG.Forms.ScalarFunctionScriptControl.btnSummary_Click (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.CreateFunctonSummary().
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
txtName_Validated() [1/4]
void IG.Forms.ScalarFunctionScriptControl.txtName_Validated (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.FunctionName, and IG.Forms.ScalarFunctionScriptControl.txtName.
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
txtDescription_Validated() [1/4]
void IG.Forms.ScalarFunctionScriptControl.txtDescription_Validated (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.FunctionDescription, and IG.Forms.ScalarFunctionScriptControl.txtDescription.
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
txtParameterNames_Validated() [1/4]
void IG.Forms.ScalarFunctionScriptControl.txtParameterNames_Validated (object sender, EventArgs e) inline private
References IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ConvertParameterNamesToArray(), IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.ParameterNames, and IG.Forms.ScalarFunctionScriptControl.txtParameterNames.
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
numDimension_Validated() [1/4]
void IG.Forms.ScalarFunctionScriptControl.numDimension_Validated (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.Dimension, and IG.Forms.ScalarFunctionScriptControl.numDimension.
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
txtValue_Validated() [1/4]
void IG.Forms.ScalarFunctionScriptControl.txtValue_Validated (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.txtValue, and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
txtGradients_Validated() [1/4]
void IG.Forms.ScalarFunctionScriptControl.txtGradients_Validated (object sender, EventArgs e) inline private
References IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ConvertFunctionDefinitionsToArray(), IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, and IG.Forms.ScalarFunctionScriptControl.txtGradients.
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
chkGradients_CheckedChanged() [1/4]
void IG.Forms.ScalarFunctionScriptControl.chkGradients_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.chkGradients, and IG.Forms.ScalarFunctionScriptControl.IsGradientDefined.
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
btnCreateFunction_Click() [1/4]
void IG.Forms.ScalarFunctionScriptControl.btnCreateFunction_Click (object sender, EventArgs e) inline private
Creates a function i advance (before it is eeded for any other operation). Error message is launched if creation is not successful.
References IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetFunction(), IG.Forms.ScalarFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
btnValueCalculator_Click() [1/4]
void IG.Forms.ScalarFunctionScriptControl.btnValueCalculator_Click (object sender, EventArgs e) inline private
Launches value calculator where user can calculate functio values with the function that was defined in the current control.
References IG.Forms.ScalarFunctionScriptControl.CreateFunctonSummary(), IG.Forms.ScalarFunctionScriptControl.Dimension, IG.Forms.ScalarFunctionScriptControl.Function, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionEvaluatorControl.FunctionDefinition, IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetFunction(), IG.Forms.ScalarFunctionEvaluatorForm.MainControl, IG.Forms.ScalarFunctionScriptControl.ParameterNames, IG.Forms.ScalarFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Forms.ScalarFunctionEvaluatorControl.TreatScalarAsVectorFunction, and IG.Num.ScalarFunctionBase.Value().
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
btnPlot1d_Click() [1/4]
void IG.Forms.ScalarFunctionScriptControl.btnPlot1d_Click (object sender, EventArgs e) inline private
Launches 1D parametric plots of the function defined in this control.
References IG.Forms.ScalarFunctionScriptControl.DataDefinition, IG.Forms.ScalarFunctionScriptControl.Function, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.VectorFunctionPlotter1dForm.MainControl, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Forms.ScalarFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Forms.VectorFunctionPlotter1d.ScalarFunction.
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
btnPlot2d_Click() [1/4]
void IG.Forms.ScalarFunctionScriptControl.btnPlot2d_Click (object sender, EventArgs e) inline private
Launches 2D parametric plots of the function defined in this control.
References IG.Forms.ScalarFunctionScriptControl.DataDefinition, IG.Forms.ScalarFunctionScriptControl.Function, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.VectorFunctionPlotter2dForm.MainControl, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Forms.ScalarFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Forms.VectorFunctionPlotter2d.ScalarFunction.
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
btnSave_Click() [1/4]
void IG.Forms.ScalarFunctionScriptControl.btnSave_Click (object sender, EventArgs e) inline private
Saves the current fucntion definition to a JSON file.
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.ScalarFunctionScriptControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.ScalarFunctionScriptControl.fileSelector1, IG.Forms.FileSelector.Filter, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, IG.Forms.ScalarFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.IReporterBase.ReportWarning(), and IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.SaveJson().
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
btnLoad_Click() [1/4]
void IG.Forms.ScalarFunctionScriptControl.btnLoad_Click (object sender, EventArgs e) inline private
Loads the current function definition from a JSON file.
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.ScalarFunctionScriptControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.ScalarFunctionScriptControl.fileSelector1, IG.Forms.FileSelector.Filter, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.HasParentUnsavedChanges(), IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.LoadJson(), IG.Forms.ScalarFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
Dispose() [1/4]
override void IG.Forms.ScalarFunctionScriptControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ScalarFunctionScriptControl.components.
InitializeComponent() [1/4]
void IG.Forms.ScalarFunctionScriptControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.FileSelector.AllowEnvironmentVariables, IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.ScalarFunctionScriptControl.btnCreateFunction, IG.Forms.ScalarFunctionScriptControl.btnCreateFunction_Click(), IG.Forms.ScalarFunctionScriptControl.btnLoad, IG.Forms.ScalarFunctionScriptControl.btnLoad_Click(), IG.Forms.ScalarFunctionScriptControl.btnPlot1d, IG.Forms.ScalarFunctionScriptControl.btnPlot1d_Click(), IG.Forms.ScalarFunctionScriptControl.btnPlot2d, IG.Forms.ScalarFunctionScriptControl.btnPlot2d_Click(), IG.Forms.ScalarFunctionScriptControl.btnSave, IG.Forms.ScalarFunctionScriptControl.btnSave_Click(), IG.Forms.ScalarFunctionScriptControl.btnSummary, IG.Forms.ScalarFunctionScriptControl.btnSummary_Click(), IG.Forms.ScalarFunctionScriptControl.btnValueCalculator, IG.Forms.ScalarFunctionScriptControl.btnValueCalculator_Click(), IG.Forms.ScalarFunctionScriptControl.chkGradients, IG.Forms.ScalarFunctionScriptControl.chkGradients_CheckedChanged(), IG.Forms.ScalarFunctionScriptControl.components, IG.Forms.FileSelector.ErrorBackground, IG.Forms.FileSelector.ErrorForeground, IG.Forms.FileSelector.FilePath, IG.Forms.ScalarFunctionScriptControl.fileSelector1, IG.Forms.FileSelector.Filter, IG.Forms.FileSelector.IsBrowsable, IG.Forms.FileSelector.IsDragAndDrop, IG.Forms.ScalarFunctionScriptControl.label1, IG.Forms.ScalarFunctionScriptControl.lblDescription, IG.Forms.ScalarFunctionScriptControl.lblDimension, IG.Forms.ScalarFunctionScriptControl.lblFunctionSignature, IG.Forms.ScalarFunctionScriptControl.lblName, IG.Forms.ScalarFunctionScriptControl.lblParameterNames, IG.Forms.ScalarFunctionScriptControl.lblTitle, IG.Forms.ScalarFunctionScriptControl.lblValue, IG.Forms.FileSelector.NormalBackground, IG.Forms.FileSelector.NormalForeground, IG.Forms.ScalarFunctionScriptControl.numDimension, IG.Forms.ScalarFunctionScriptControl.numDimension_Validated(), IG.Forms.FileSelector.OriginalFilePath, IG.Forms.ScalarFunctionScriptControl.pnlBasic, IG.Forms.ScalarFunctionScriptControl.pnlBasicAndTitle, IG.Forms.ScalarFunctionScriptControl.pnlButtons, IG.Forms.ScalarFunctionScriptControl.pnlGradients, IG.Forms.ScalarFunctionScriptControl.pnlOuter, IG.Forms.ScalarFunctionScriptControl.pnlParameters, IG.Forms.ScalarFunctionScriptControl.pnlPlotButtons, IG.Forms.ScalarFunctionScriptControl.pnlTop, IG.Forms.ScalarFunctionScriptControl.pnlValues, IG.Forms.ScalarFunctionScriptControl.txtDescription, IG.Forms.ScalarFunctionScriptControl.txtDescription_Validated(), IG.Forms.ScalarFunctionScriptControl.txtGradients, IG.Forms.ScalarFunctionScriptControl.txtGradients_Validated(), IG.Forms.ScalarFunctionScriptControl.txtName, IG.Forms.ScalarFunctionScriptControl.txtName_Validated(), IG.Forms.ScalarFunctionScriptControl.txtParameterNames, IG.Forms.ScalarFunctionScriptControl.txtParameterNames_Validated(), IG.Forms.ScalarFunctionScriptControl.txtValue, IG.Forms.ScalarFunctionScriptControl.txtValue_Validated(), IG.Forms.FileSelector.UseAbsolutePaths, and IG.Forms.FileSelector.UseRelativePaths.
Referenced by IG.Forms.ScalarFunctionScriptControl.ScalarFunctionScriptControl().
CopyDataToController() [2/4]
void IG.Forms.ScalarFunctionScriptControl.CopyDataToController () inline private
Copies data from the current control to the internal function DTO.
References IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ConvertParameterNamesToArray(), IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Description, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Dimension, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Name, IG.Forms.ScalarFunctionScriptControl.numDimension, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ParameterNames, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.SetGradientDefinitionSingleString(), IG.Forms.ScalarFunctionScriptControl.txtDescription, IG.Forms.ScalarFunctionScriptControl.txtGradients, IG.Forms.ScalarFunctionScriptControl.txtName, IG.Forms.ScalarFunctionScriptControl.txtParameterNames, IG.Forms.ScalarFunctionScriptControl.txtValue, and IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ValueDefinitonString.
CopyDataFromController() [2/4]
void IG.Forms.ScalarFunctionScriptControl.CopyDataFromController () inline
Copies data from the internal DTO to the current control.
References IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Description, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Dimension, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.GetFunctionSignature(), IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetGradientDefinitionSingleString(), IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetParametersString(), IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.IsGradientDefined, IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Forms.ScalarFunctionScriptControl.lblFunctionSignature, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Name, IG.Forms.ScalarFunctionScriptControl.numDimension, IG.Forms.ScalarFunctionScriptControl.txtDescription, IG.Forms.ScalarFunctionScriptControl.txtGradients, IG.Forms.ScalarFunctionScriptControl.txtName, IG.Forms.ScalarFunctionScriptControl.txtParameterNames, IG.Forms.ScalarFunctionScriptControl.txtValue, and IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ValueDefinitonString.
GetFunctionSignature() [2/4]
string IG.Forms.ScalarFunctionScriptControl.GetFunctionSignature () inline protected
Returns function signature created from the data.
References IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Lib.UtilStr.GetParametersStringPlain(), and IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ParameterNames.
ResetFunctionDefinition() [2/4]
void IG.Forms.ScalarFunctionScriptControl.ResetFunctionDefinition () inline
Resets function definition to simply "0". Gradients are redefined accordingly.
References IG.Forms.ScalarFunctionScriptControl.Dimension, IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
CreateFunctonSummary() [2/4]
string IG.Forms.ScalarFunctionScriptControl.CreateFunctonSummary () inline
References IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Lib.UtilStr.GetParametersStringPlain(), IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Forms.ScalarFunctionScriptControl.ParameterNames, IG.Forms.ScalarFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
btnSummary_Click() [2/4]
void IG.Forms.ScalarFunctionScriptControl.btnSummary_Click (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.CreateFunctonSummary().
txtName_Validated() [2/4]
void IG.Forms.ScalarFunctionScriptControl.txtName_Validated (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.FunctionName, and IG.Forms.ScalarFunctionScriptControl.txtName.
txtDescription_Validated() [2/4]
void IG.Forms.ScalarFunctionScriptControl.txtDescription_Validated (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.FunctionDescription, and IG.Forms.ScalarFunctionScriptControl.txtDescription.
txtParameterNames_Validated() [2/4]
void IG.Forms.ScalarFunctionScriptControl.txtParameterNames_Validated (object sender, EventArgs e) inline private
References IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ConvertParameterNamesToArray(), IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.ParameterNames, and IG.Forms.ScalarFunctionScriptControl.txtParameterNames.
numDimension_Validated() [2/4]
void IG.Forms.ScalarFunctionScriptControl.numDimension_Validated (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.Dimension, and IG.Forms.ScalarFunctionScriptControl.numDimension.
txtValue_Validated() [2/4]
void IG.Forms.ScalarFunctionScriptControl.txtValue_Validated (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.txtValue, and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
txtGradients_Validated() [2/4]
void IG.Forms.ScalarFunctionScriptControl.txtGradients_Validated (object sender, EventArgs e) inline private
References IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ConvertFunctionDefinitionsToArray(), IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, and IG.Forms.ScalarFunctionScriptControl.txtGradients.
chkGradients_CheckedChanged() [2/4]
void IG.Forms.ScalarFunctionScriptControl.chkGradients_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.chkGradients, and IG.Forms.ScalarFunctionScriptControl.IsGradientDefined.
btnCreateFunction_Click() [2/4]
void IG.Forms.ScalarFunctionScriptControl.btnCreateFunction_Click (object sender, EventArgs e) inline private
Creates a function i advance (before it is eeded for any other operation). Error message is launched if creation is not successful.
References IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetFunction(), IG.Forms.ScalarFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
btnValueCalculator_Click() [2/4]
void IG.Forms.ScalarFunctionScriptControl.btnValueCalculator_Click (object sender, EventArgs e) inline private
Launches value calculator where user can calculate functio values with the function that was defined in the current control.
References IG.Forms.ScalarFunctionScriptControl.CreateFunctonSummary(), IG.Forms.ScalarFunctionScriptControl.Dimension, IG.Forms.ScalarFunctionScriptControl.Function, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionEvaluatorControl.FunctionDefinition, IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetFunction(), IG.Forms.ScalarFunctionEvaluatorForm.MainControl, IG.Forms.ScalarFunctionScriptControl.ParameterNames, IG.Forms.ScalarFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Forms.ScalarFunctionEvaluatorControl.TreatScalarAsVectorFunction, and IG.Num.ScalarFunctionBase.Value().
btnPlot1d_Click() [2/4]
void IG.Forms.ScalarFunctionScriptControl.btnPlot1d_Click (object sender, EventArgs e) inline private
Launches 1D parametric plots of the function defined in this control.
References IG.Forms.ScalarFunctionScriptControl.DataDefinition, IG.Forms.ScalarFunctionScriptControl.Function, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.VectorFunctionPlotter1dForm.MainControl, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Forms.ScalarFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Forms.VectorFunctionPlotter1d.ScalarFunction.
btnPlot2d_Click() [2/4]
void IG.Forms.ScalarFunctionScriptControl.btnPlot2d_Click (object sender, EventArgs e) inline private
Launches 2D parametric plots of the function defined in this control.
References IG.Forms.ScalarFunctionScriptControl.DataDefinition, IG.Forms.ScalarFunctionScriptControl.Function, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.VectorFunctionPlotter2dForm.MainControl, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Forms.ScalarFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Forms.VectorFunctionPlotter2d.ScalarFunction.
btnSave_Click() [2/4]
void IG.Forms.ScalarFunctionScriptControl.btnSave_Click (object sender, EventArgs e) inline private
Saves the current fucntion definition to a JSON file.
References IG.Forms.FileSelector.BrowseFile(), IG.Forms.ScalarFunctionScriptControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.ScalarFunctionScriptControl.fileSelector1, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.ScalarFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.IReporterBase.ReportWarning(), and IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.SaveJson().
btnLoad_Click() [2/4]
void IG.Forms.ScalarFunctionScriptControl.btnLoad_Click (object sender, EventArgs e) inline private
Loads the current function definition from a JSON file.
References IG.Forms.FileSelector.BrowseFile(), IG.Forms.ScalarFunctionScriptControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.ScalarFunctionScriptControl.fileSelector1, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.LoadJson(), IG.Forms.ScalarFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
Dispose() [2/4]
override void IG.Forms.ScalarFunctionScriptControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ScalarFunctionScriptControl.components.
InitializeComponent() [2/4]
void IG.Forms.ScalarFunctionScriptControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.FileSelector.AllowEnvironmentVariables, IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.ScalarFunctionScriptControl.btnCreateFunction, IG.Forms.ScalarFunctionScriptControl.btnCreateFunction_Click(), IG.Forms.ScalarFunctionScriptControl.btnLoad, IG.Forms.ScalarFunctionScriptControl.btnLoad_Click(), IG.Forms.ScalarFunctionScriptControl.btnPlot1d, IG.Forms.ScalarFunctionScriptControl.btnPlot1d_Click(), IG.Forms.ScalarFunctionScriptControl.btnPlot2d, IG.Forms.ScalarFunctionScriptControl.btnPlot2d_Click(), IG.Forms.ScalarFunctionScriptControl.btnSave, IG.Forms.ScalarFunctionScriptControl.btnSave_Click(), IG.Forms.ScalarFunctionScriptControl.btnSummary, IG.Forms.ScalarFunctionScriptControl.btnSummary_Click(), IG.Forms.ScalarFunctionScriptControl.btnValueCalculator, IG.Forms.ScalarFunctionScriptControl.btnValueCalculator_Click(), IG.Forms.ScalarFunctionScriptControl.chkGradients, IG.Forms.ScalarFunctionScriptControl.chkGradients_CheckedChanged(), IG.Forms.ScalarFunctionScriptControl.components, IG.Forms.FileSelector.ErrorBackground, IG.Forms.FileSelector.ErrorForeground, IG.Forms.FileSelector.FilePath, IG.Forms.ScalarFunctionScriptControl.fileSelector1, IG.Forms.FileSelector.IsBrowsable, IG.Forms.FileSelector.IsDragAndDrop, IG.Forms.ScalarFunctionScriptControl.label1, IG.Forms.ScalarFunctionScriptControl.lblDescription, IG.Forms.ScalarFunctionScriptControl.lblDimension, IG.Forms.ScalarFunctionScriptControl.lblFunctionSignature, IG.Forms.ScalarFunctionScriptControl.lblName, IG.Forms.ScalarFunctionScriptControl.lblParameterNames, IG.Forms.ScalarFunctionScriptControl.lblTitle, IG.Forms.ScalarFunctionScriptControl.lblValue, IG.Forms.FileSelector.NormalBackground, IG.Forms.FileSelector.NormalForeground, IG.Forms.ScalarFunctionScriptControl.numDimension, IG.Forms.ScalarFunctionScriptControl.numDimension_Validated(), IG.Forms.FileSelector.OriginalFilePath, IG.Forms.ScalarFunctionScriptControl.pnlBasic, IG.Forms.ScalarFunctionScriptControl.pnlBasicAndTitle, IG.Forms.ScalarFunctionScriptControl.pnlButtons, IG.Forms.ScalarFunctionScriptControl.pnlGradients, IG.Forms.ScalarFunctionScriptControl.pnlOuter, IG.Forms.ScalarFunctionScriptControl.pnlParameters, IG.Forms.ScalarFunctionScriptControl.pnlPlotButtons, IG.Forms.ScalarFunctionScriptControl.pnlTop, IG.Forms.ScalarFunctionScriptControl.pnlValues, IG.Forms.ScalarFunctionScriptControl.txtDescription, IG.Forms.ScalarFunctionScriptControl.txtDescription_Validated(), IG.Forms.ScalarFunctionScriptControl.txtGradients, IG.Forms.ScalarFunctionScriptControl.txtGradients_Validated(), IG.Forms.ScalarFunctionScriptControl.txtName, IG.Forms.ScalarFunctionScriptControl.txtName_Validated(), IG.Forms.ScalarFunctionScriptControl.txtParameterNames, IG.Forms.ScalarFunctionScriptControl.txtParameterNames_Validated(), IG.Forms.ScalarFunctionScriptControl.txtValue, IG.Forms.ScalarFunctionScriptControl.txtValue_Validated(), IG.Forms.FileSelector.UseAbsolutePaths, and IG.Forms.FileSelector.UseRelativePaths.
SetTestDefinitions() [2/3]
void IG.Forms.ScalarFunctionScriptControl.SetTestDefinitions () inline
Setts a test definition.
References IG.Forms.ScalarFunctionScriptControl.FunctionDescription, IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, IG.Forms.ScalarFunctionScriptControl.ParameterNames, and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
HasParentUnsavedChanges() [2/3]
bool IG.Forms.ScalarFunctionScriptControl.HasParentUnsavedChanges (bool set = false) inline
Get or sets a flag indicating whether the parent control has unsaved changes.
The flag may only be set to false.
If there is no parent control (such as VectorFunctionScriptControl) then getter returns false and setter has no effect.
Parameters
set If true then the "Has unsaved changes" is set on the parent. Otherwise, only the value indicating whether the parent has unsaved changes is returned. Default value is false.
Returns
Flag indicating whether parent control had unsaved changes before this method was called.
References IG.Forms.VectorFunctionScriptControl.HasUnsavedChanges, and IG.Forms.ScalarFunctionScriptControl.VectorFunctionControl.
CopyDataToController() [3/4]
void IG.Forms.ScalarFunctionScriptControl.CopyDataToController () inline private
Copies data from the current control to the internal function DTO.
References IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ConvertParameterNamesToArray(), IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Description, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Dimension, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Name, IG.Forms.ScalarFunctionScriptControl.numDimension, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ParameterNames, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.SetGradientDefinitionSingleString(), IG.Forms.ScalarFunctionScriptControl.txtDescription, IG.Forms.ScalarFunctionScriptControl.txtGradients, IG.Forms.ScalarFunctionScriptControl.txtName, IG.Forms.ScalarFunctionScriptControl.txtParameterNames, IG.Forms.ScalarFunctionScriptControl.txtValue, and IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ValueDefinitonString.
CopyDataFromController() [3/4]
void IG.Forms.ScalarFunctionScriptControl.CopyDataFromController () inline
Copies data from the internal DTO to the current control.
References IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Description, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Dimension, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.GetFunctionSignature(), IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetGradientDefinitionSingleString(), IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetParametersString(), IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.IsGradientDefined, IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Forms.ScalarFunctionScriptControl.lblFunctionSignature, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Name, IG.Forms.ScalarFunctionScriptControl.numDimension, IG.Forms.ScalarFunctionScriptControl.txtDescription, IG.Forms.ScalarFunctionScriptControl.txtGradients, IG.Forms.ScalarFunctionScriptControl.txtName, IG.Forms.ScalarFunctionScriptControl.txtParameterNames, IG.Forms.ScalarFunctionScriptControl.txtValue, and IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ValueDefinitonString.
GetFunctionSignature() [3/4]
string IG.Forms.ScalarFunctionScriptControl.GetFunctionSignature () inline protected
Returns function signature created from the data.
References IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Lib.UtilStr.GetParametersStringPlain(), and IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ParameterNames.
ResetFunctionDefinition() [3/4]
void IG.Forms.ScalarFunctionScriptControl.ResetFunctionDefinition () inline
Resets function definition to simply "0". Gradients are redefined accordingly.
References IG.Forms.ScalarFunctionScriptControl.Dimension, IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
CreateFunctonSummary() [3/4]
string IG.Forms.ScalarFunctionScriptControl.CreateFunctonSummary () inline
References IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Lib.UtilStr.GetParametersStringPlain(), IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Forms.ScalarFunctionScriptControl.ParameterNames, IG.Forms.ScalarFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
btnSummary_Click() [3/4]
void IG.Forms.ScalarFunctionScriptControl.btnSummary_Click (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.CreateFunctonSummary().
txtName_Validated() [3/4]
void IG.Forms.ScalarFunctionScriptControl.txtName_Validated (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.FunctionName, and IG.Forms.ScalarFunctionScriptControl.txtName.
txtDescription_Validated() [3/4]
void IG.Forms.ScalarFunctionScriptControl.txtDescription_Validated (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.FunctionDescription, and IG.Forms.ScalarFunctionScriptControl.txtDescription.
txtParameterNames_Validated() [3/4]
void IG.Forms.ScalarFunctionScriptControl.txtParameterNames_Validated (object sender, EventArgs e) inline private
References IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ConvertParameterNamesToArray(), IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.ParameterNames, and IG.Forms.ScalarFunctionScriptControl.txtParameterNames.
numDimension_Validated() [3/4]
void IG.Forms.ScalarFunctionScriptControl.numDimension_Validated (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.Dimension, and IG.Forms.ScalarFunctionScriptControl.numDimension.
txtValue_Validated() [3/4]
void IG.Forms.ScalarFunctionScriptControl.txtValue_Validated (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.txtValue, and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
txtGradients_Validated() [3/4]
void IG.Forms.ScalarFunctionScriptControl.txtGradients_Validated (object sender, EventArgs e) inline private
References IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ConvertFunctionDefinitionsToArray(), IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, and IG.Forms.ScalarFunctionScriptControl.txtGradients.
chkGradients_CheckedChanged() [3/4]
void IG.Forms.ScalarFunctionScriptControl.chkGradients_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.chkGradients, and IG.Forms.ScalarFunctionScriptControl.IsGradientDefined.
btnCreateFunction_Click() [3/4]
void IG.Forms.ScalarFunctionScriptControl.btnCreateFunction_Click (object sender, EventArgs e) inline private
Creates a function i advance (before it is eeded for any other operation). Error message is launched if creation is not successful.
References IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetFunction(), IG.Forms.ScalarFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
btnValueCalculator_Click() [3/4]
void IG.Forms.ScalarFunctionScriptControl.btnValueCalculator_Click (object sender, EventArgs e) inline private
Launches value calculator where user can calculate functio values with the function that was defined in the current control.
References IG.Forms.ScalarFunctionScriptControl.CreateFunctonSummary(), IG.Forms.ScalarFunctionScriptControl.Dimension, IG.Forms.ScalarFunctionScriptControl.Function, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionEvaluatorControl.FunctionDefinition, IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetFunction(), IG.Forms.ScalarFunctionEvaluatorForm.MainControl, IG.Forms.ScalarFunctionScriptControl.ParameterNames, IG.Forms.ScalarFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Forms.ScalarFunctionEvaluatorControl.TreatScalarAsVectorFunction, and IG.Num.ScalarFunctionBase.Value().
btnPlot1d_Click() [3/4]
void IG.Forms.ScalarFunctionScriptControl.btnPlot1d_Click (object sender, EventArgs e) inline private
Launches 1D parametric plots of the function defined in this control.
References IG.Forms.ScalarFunctionScriptControl.DataDefinition, IG.Forms.ScalarFunctionScriptControl.Function, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.VectorFunctionPlotter1dForm.MainControl, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Forms.ScalarFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Forms.VectorFunctionPlotter1d.ScalarFunction.
btnPlot2d_Click() [3/4]
void IG.Forms.ScalarFunctionScriptControl.btnPlot2d_Click (object sender, EventArgs e) inline private
Launches 2D parametric plots of the function defined in this control.
References IG.Forms.ScalarFunctionScriptControl.DataDefinition, IG.Forms.ScalarFunctionScriptControl.Function, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.VectorFunctionPlotter2dForm.MainControl, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Forms.ScalarFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Forms.VectorFunctionPlotter2d.ScalarFunction.
btnSave_Click() [3/4]
void IG.Forms.ScalarFunctionScriptControl.btnSave_Click (object sender, EventArgs e) inline private
Saves the current fucntion definition to a JSON file.
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.ScalarFunctionScriptControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.ScalarFunctionScriptControl.fileSelector1, IG.Forms.FileSelector.Filter, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, IG.Forms.ScalarFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.IReporterBase.ReportWarning(), and IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.SaveJson().
btnLoad_Click() [3/4]
void IG.Forms.ScalarFunctionScriptControl.btnLoad_Click (object sender, EventArgs e) inline private
Loads the current function definition from a JSON file.
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.ScalarFunctionScriptControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.ScalarFunctionScriptControl.fileSelector1, IG.Forms.FileSelector.Filter, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.HasParentUnsavedChanges(), IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.LoadJson(), IG.Forms.ScalarFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
Dispose() [3/4]
override void IG.Forms.ScalarFunctionScriptControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ScalarFunctionScriptControl.components.
InitializeComponent() [3/4]
void IG.Forms.ScalarFunctionScriptControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.FileSelector.AllowEnvironmentVariables, IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.ScalarFunctionScriptControl.btnCreateFunction, IG.Forms.ScalarFunctionScriptControl.btnCreateFunction_Click(), IG.Forms.ScalarFunctionScriptControl.btnLoad, IG.Forms.ScalarFunctionScriptControl.btnLoad_Click(), IG.Forms.ScalarFunctionScriptControl.btnPlot1d, IG.Forms.ScalarFunctionScriptControl.btnPlot1d_Click(), IG.Forms.ScalarFunctionScriptControl.btnPlot2d, IG.Forms.ScalarFunctionScriptControl.btnPlot2d_Click(), IG.Forms.ScalarFunctionScriptControl.btnSave, IG.Forms.ScalarFunctionScriptControl.btnSave_Click(), IG.Forms.ScalarFunctionScriptControl.btnSummary, IG.Forms.ScalarFunctionScriptControl.btnSummary_Click(), IG.Forms.ScalarFunctionScriptControl.btnValueCalculator, IG.Forms.ScalarFunctionScriptControl.btnValueCalculator_Click(), IG.Forms.ScalarFunctionScriptControl.chkGradients, IG.Forms.ScalarFunctionScriptControl.chkGradients_CheckedChanged(), IG.Forms.ScalarFunctionScriptControl.components, IG.Forms.FileSelector.ErrorBackground, IG.Forms.FileSelector.ErrorForeground, IG.Forms.FileSelector.FilePath, IG.Forms.ScalarFunctionScriptControl.fileSelector1, IG.Forms.FileSelector.Filter, IG.Forms.FileSelector.IsBrowsable, IG.Forms.FileSelector.IsDragAndDrop, IG.Forms.ScalarFunctionScriptControl.label1, IG.Forms.ScalarFunctionScriptControl.lblDescription, IG.Forms.ScalarFunctionScriptControl.lblDimension, IG.Forms.ScalarFunctionScriptControl.lblFunctionSignature, IG.Forms.ScalarFunctionScriptControl.lblName, IG.Forms.ScalarFunctionScriptControl.lblParameterNames, IG.Forms.ScalarFunctionScriptControl.lblTitle, IG.Forms.ScalarFunctionScriptControl.lblValue, IG.Forms.FileSelector.NormalBackground, IG.Forms.FileSelector.NormalForeground, IG.Forms.ScalarFunctionScriptControl.numDimension, IG.Forms.ScalarFunctionScriptControl.numDimension_Validated(), IG.Forms.FileSelector.OriginalFilePath, IG.Forms.ScalarFunctionScriptControl.pnlBasic, IG.Forms.ScalarFunctionScriptControl.pnlBasicAndTitle, IG.Forms.ScalarFunctionScriptControl.pnlButtons, IG.Forms.ScalarFunctionScriptControl.pnlGradients, IG.Forms.ScalarFunctionScriptControl.pnlOuter, IG.Forms.ScalarFunctionScriptControl.pnlParameters, IG.Forms.ScalarFunctionScriptControl.pnlPlotButtons, IG.Forms.ScalarFunctionScriptControl.pnlTop, IG.Forms.ScalarFunctionScriptControl.pnlValues, IG.Forms.ScalarFunctionScriptControl.txtDescription, IG.Forms.ScalarFunctionScriptControl.txtDescription_Validated(), IG.Forms.ScalarFunctionScriptControl.txtGradients, IG.Forms.ScalarFunctionScriptControl.txtGradients_Validated(), IG.Forms.ScalarFunctionScriptControl.txtName, IG.Forms.ScalarFunctionScriptControl.txtName_Validated(), IG.Forms.ScalarFunctionScriptControl.txtParameterNames, IG.Forms.ScalarFunctionScriptControl.txtParameterNames_Validated(), IG.Forms.ScalarFunctionScriptControl.txtValue, IG.Forms.ScalarFunctionScriptControl.txtValue_Validated(), IG.Forms.FileSelector.UseAbsolutePaths, and IG.Forms.FileSelector.UseRelativePaths.
SetTestDefinitions() [3/3]
void IG.Forms.ScalarFunctionScriptControl.SetTestDefinitions () inline
Setts a test definition.
References IG.Forms.ScalarFunctionScriptControl.FunctionDescription, IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, IG.Forms.ScalarFunctionScriptControl.ParameterNames, and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
HasParentUnsavedChanges() [3/3]
bool IG.Forms.ScalarFunctionScriptControl.HasParentUnsavedChanges (bool set = false) inline
Get or sets a flag indicating whether the parent control has unsaved changes.
The flag may only be set to false.
If there is no parent control (such as VectorFunctionScriptControl) then getter returns false and setter has no effect.
Parameters
set If true then the "Has unsaved changes" is set on the parent. Otherwise, only the value indicating whether the parent has unsaved changes is returned. Default value is false.
Returns
Flag indicating whether parent control had unsaved changes before this method was called.
References IG.Forms.VectorFunctionScriptControl.HasUnsavedChanges, and IG.Forms.ScalarFunctionScriptControl.VectorFunctionControl.
CopyDataToController() [4/4]
void IG.Forms.ScalarFunctionScriptControl.CopyDataToController () inline private
Copies data from the current control to the internal function DTO.
References IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ConvertParameterNamesToArray(), IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Description, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Dimension, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Name, IG.Forms.ScalarFunctionScriptControl.numDimension, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ParameterNames, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.SetGradientDefinitionSingleString(), IG.Forms.ScalarFunctionScriptControl.txtDescription, IG.Forms.ScalarFunctionScriptControl.txtGradients, IG.Forms.ScalarFunctionScriptControl.txtName, IG.Forms.ScalarFunctionScriptControl.txtParameterNames, IG.Forms.ScalarFunctionScriptControl.txtValue, and IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ValueDefinitonString.
CopyDataFromController() [4/4]
void IG.Forms.ScalarFunctionScriptControl.CopyDataFromController () inline
Copies data from the internal DTO to the current control.
References IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Description, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Dimension, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.GetFunctionSignature(), IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetGradientDefinitionSingleString(), IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetParametersString(), IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.IsGradientDefined, IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Forms.ScalarFunctionScriptControl.lblFunctionSignature, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.Name, IG.Forms.ScalarFunctionScriptControl.numDimension, IG.Forms.ScalarFunctionScriptControl.txtDescription, IG.Forms.ScalarFunctionScriptControl.txtGradients, IG.Forms.ScalarFunctionScriptControl.txtName, IG.Forms.ScalarFunctionScriptControl.txtParameterNames, IG.Forms.ScalarFunctionScriptControl.txtValue, and IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ValueDefinitonString.
GetFunctionSignature() [4/4]
string IG.Forms.ScalarFunctionScriptControl.GetFunctionSignature () inline protected
Returns function signature created from the data.
References IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Lib.UtilStr.GetParametersStringPlain(), and IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ParameterNames.
ResetFunctionDefinition() [4/4]
void IG.Forms.ScalarFunctionScriptControl.ResetFunctionDefinition () inline
Resets function definition to simply "0". Gradients are redefined accordingly.
References IG.Forms.ScalarFunctionScriptControl.Dimension, IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
CreateFunctonSummary() [4/4]
string IG.Forms.ScalarFunctionScriptControl.CreateFunctonSummary () inline
References IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Lib.UtilStr.GetParametersStringPlain(), IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, IG.Forms.ScalarFunctionScriptControl.IsGradientDefined, IG.Forms.ScalarFunctionScriptControl.ParameterNames, IG.Forms.ScalarFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
btnSummary_Click() [4/4]
void IG.Forms.ScalarFunctionScriptControl.btnSummary_Click (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.CreateFunctonSummary().
txtName_Validated() [4/4]
void IG.Forms.ScalarFunctionScriptControl.txtName_Validated (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.FunctionName, and IG.Forms.ScalarFunctionScriptControl.txtName.
txtDescription_Validated() [4/4]
void IG.Forms.ScalarFunctionScriptControl.txtDescription_Validated (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.FunctionDescription, and IG.Forms.ScalarFunctionScriptControl.txtDescription.
txtParameterNames_Validated() [4/4]
void IG.Forms.ScalarFunctionScriptControl.txtParameterNames_Validated (object sender, EventArgs e) inline private
References IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ConvertParameterNamesToArray(), IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.ParameterNames, and IG.Forms.ScalarFunctionScriptControl.txtParameterNames.
numDimension_Validated() [4/4]
void IG.Forms.ScalarFunctionScriptControl.numDimension_Validated (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.Dimension, and IG.Forms.ScalarFunctionScriptControl.numDimension.
txtValue_Validated() [4/4]
void IG.Forms.ScalarFunctionScriptControl.txtValue_Validated (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.txtValue, and IG.Forms.ScalarFunctionScriptControl.ValueDefinition.
txtGradients_Validated() [4/4]
void IG.Forms.ScalarFunctionScriptControl.txtGradients_Validated (object sender, EventArgs e) inline private
References IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.ConvertFunctionDefinitionsToArray(), IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.GradientDefinitions, and IG.Forms.ScalarFunctionScriptControl.txtGradients.
chkGradients_CheckedChanged() [4/4]
void IG.Forms.ScalarFunctionScriptControl.chkGradients_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionScriptControl.chkGradients, and IG.Forms.ScalarFunctionScriptControl.IsGradientDefined.
btnCreateFunction_Click() [4/4]
void IG.Forms.ScalarFunctionScriptControl.btnCreateFunction_Click (object sender, EventArgs e) inline private
Creates a function i advance (before it is eeded for any other operation). Error message is launched if creation is not successful.
References IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetFunction(), IG.Forms.ScalarFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
btnValueCalculator_Click() [4/4]
void IG.Forms.ScalarFunctionScriptControl.btnValueCalculator_Click (object sender, EventArgs e) inline private
Launches value calculator where user can calculate functio values with the function that was defined in the current control.
References IG.Forms.ScalarFunctionScriptControl.CreateFunctonSummary(), IG.Forms.ScalarFunctionScriptControl.Dimension, IG.Forms.ScalarFunctionScriptControl.Function, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionEvaluatorControl.FunctionDefinition, IG.Forms.ScalarFunctionScriptControl.FunctionName, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetFunction(), IG.Forms.ScalarFunctionEvaluatorForm.MainControl, IG.Forms.ScalarFunctionScriptControl.ParameterNames, IG.Forms.ScalarFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Forms.ScalarFunctionEvaluatorControl.TreatScalarAsVectorFunction, and IG.Num.ScalarFunctionBase.Value().
btnPlot1d_Click() [4/4]
void IG.Forms.ScalarFunctionScriptControl.btnPlot1d_Click (object sender, EventArgs e) inline private
Launches 1D parametric plots of the function defined in this control.
References IG.Forms.ScalarFunctionScriptControl.DataDefinition, IG.Forms.ScalarFunctionScriptControl.Function, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.VectorFunctionPlotter1dForm.MainControl, IG.Forms.VectorFunctionPlotter1d.NeuralDataDefinition, IG.Forms.ScalarFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Forms.VectorFunctionPlotter1d.ScalarFunction.
btnPlot2d_Click() [4/4]
void IG.Forms.ScalarFunctionScriptControl.btnPlot2d_Click (object sender, EventArgs e) inline private
Launches 2D parametric plots of the function defined in this control.
References IG.Forms.ScalarFunctionScriptControl.DataDefinition, IG.Forms.ScalarFunctionScriptControl.Function, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.VectorFunctionPlotter2dForm.MainControl, IG.Forms.VectorFunctionPlotter2d.NeuralDataDefinition, IG.Forms.ScalarFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), and IG.Forms.VectorFunctionPlotter2d.ScalarFunction.
btnSave_Click() [4/4]
void IG.Forms.ScalarFunctionScriptControl.btnSave_Click (object sender, EventArgs e) inline private
Saves the current fucntion definition to a JSON file.
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.ScalarFunctionScriptControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.ScalarFunctionScriptControl.fileSelector1, IG.Forms.FileSelector.Filter, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.GetDataDefinitionObject(), IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, IG.Forms.ScalarFunctionScriptControl.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.IReporterBase.ReportWarning(), and IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.SaveJson().
btnLoad_Click() [4/4]
void IG.Forms.ScalarFunctionScriptControl.btnLoad_Click (object sender, EventArgs e) inline private
Loads the current function definition from a JSON file.
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.ScalarFunctionScriptControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.ScalarFunctionScriptControl.fileSelector1, IG.Forms.FileSelector.Filter, IG.Forms.ScalarFunctionScriptControl.FunctionController, IG.Forms.ScalarFunctionScriptControl.HasParentUnsavedChanges(), IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges, IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.LoadJson(), IG.Forms.ScalarFunctionScriptControl.Reporter, and IG.Lib.IReporterBase.ReportError().
Dispose() [4/4]
override void IG.Forms.ScalarFunctionScriptControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ScalarFunctionScriptControl.components.
InitializeComponent() [4/4]
void IG.Forms.ScalarFunctionScriptControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.FileSelector.AllowEnvironmentVariables, IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.ScalarFunctionScriptControl.btnCreateFunction, IG.Forms.ScalarFunctionScriptControl.btnCreateFunction_Click(), IG.Forms.ScalarFunctionScriptControl.btnLoad, IG.Forms.ScalarFunctionScriptControl.btnLoad_Click(), IG.Forms.ScalarFunctionScriptControl.btnPlot1d, IG.Forms.ScalarFunctionScriptControl.btnPlot1d_Click(), IG.Forms.ScalarFunctionScriptControl.btnPlot2d, IG.Forms.ScalarFunctionScriptControl.btnPlot2d_Click(), IG.Forms.ScalarFunctionScriptControl.btnSave, IG.Forms.ScalarFunctionScriptControl.btnSave_Click(), IG.Forms.ScalarFunctionScriptControl.btnSummary, IG.Forms.ScalarFunctionScriptControl.btnSummary_Click(), IG.Forms.ScalarFunctionScriptControl.btnValueCalculator, IG.Forms.ScalarFunctionScriptControl.btnValueCalculator_Click(), IG.Forms.ScalarFunctionScriptControl.chkGradients, IG.Forms.ScalarFunctionScriptControl.chkGradients_CheckedChanged(), IG.Forms.ScalarFunctionScriptControl.components, IG.Forms.FileSelector.ErrorBackground, IG.Forms.FileSelector.ErrorForeground, IG.Forms.FileSelector.FilePath, IG.Forms.ScalarFunctionScriptControl.fileSelector1, IG.Forms.FileSelector.Filter, IG.Forms.FileSelector.IsBrowsable, IG.Forms.FileSelector.IsDragAndDrop, IG.Forms.ScalarFunctionScriptControl.label1, IG.Forms.ScalarFunctionScriptControl.lblDescription, IG.Forms.ScalarFunctionScriptControl.lblDimension, IG.Forms.ScalarFunctionScriptControl.lblFunctionSignature, IG.Forms.ScalarFunctionScriptControl.lblName, IG.Forms.ScalarFunctionScriptControl.lblParameterNames, IG.Forms.ScalarFunctionScriptControl.lblTitle, IG.Forms.ScalarFunctionScriptControl.lblValue, IG.Forms.FileSelector.NormalBackground, IG.Forms.FileSelector.NormalForeground, IG.Forms.ScalarFunctionScriptControl.numDimension, IG.Forms.ScalarFunctionScriptControl.numDimension_Validated(), IG.Forms.FileSelector.OriginalFilePath, IG.Forms.ScalarFunctionScriptControl.pnlBasic, IG.Forms.ScalarFunctionScriptControl.pnlBasicAndTitle, IG.Forms.ScalarFunctionScriptControl.pnlButtons, IG.Forms.ScalarFunctionScriptControl.pnlGradients, IG.Forms.ScalarFunctionScriptControl.pnlOuter, IG.Forms.ScalarFunctionScriptControl.pnlParameters, IG.Forms.ScalarFunctionScriptControl.pnlPlotButtons, IG.Forms.ScalarFunctionScriptControl.pnlTop, IG.Forms.ScalarFunctionScriptControl.pnlValues, IG.Forms.ScalarFunctionScriptControl.txtDescription, IG.Forms.ScalarFunctionScriptControl.txtDescription_Validated(), IG.Forms.ScalarFunctionScriptControl.txtGradients, IG.Forms.ScalarFunctionScriptControl.txtGradients_Validated(), IG.Forms.ScalarFunctionScriptControl.txtName, IG.Forms.ScalarFunctionScriptControl.txtName_Validated(), IG.Forms.ScalarFunctionScriptControl.txtParameterNames, IG.Forms.ScalarFunctionScriptControl.txtParameterNames_Validated(), IG.Forms.ScalarFunctionScriptControl.txtValue, IG.Forms.ScalarFunctionScriptControl.txtValue_Validated(), IG.Forms.FileSelector.UseAbsolutePaths, and IG.Forms.FileSelector.UseRelativePaths.
Member Data Documentation
_functionNameTitleNormal
string IG.Forms.ScalarFunctionScriptControl._functionNameTitleNormal = "Function Name: " private
_functionNameTitleModified
string IG.Forms.ScalarFunctionScriptControl._functionNameTitleModified = "Function Name: (*)" private
_functionController
ScalarFunctionScriptController IG.Forms.ScalarFunctionScriptControl._functionController private
_parentVectorFunctionControl
VectorFunctionScriptControl IG.Forms.ScalarFunctionScriptControl._parentVectorFunctionControl = null private
_hasUnsavedChanges
bool IG.Forms.ScalarFunctionScriptControl._hasUnsavedChanges = false private
_isLoaderConsistent
bool IG.Forms.ScalarFunctionScriptControl._isLoaderConsistent = false private
_isGradientDefined
bool IG.Forms.ScalarFunctionScriptControl._isGradientDefined = false protected
_bgDefined
Color IG.Forms.ScalarFunctionScriptControl._bgDefined = Color.White private
Referenced by IG.Forms.ScalarFunctionScriptControl.ScalarFunctionScriptControl().
_bgUndefined
Color IG.Forms.ScalarFunctionScriptControl._bgUndefined = Color.LightGray private
_dataDefinition
InputOutputDataDefiniton IG.Forms.ScalarFunctionScriptControl._dataDefinition = null private
components
System ComponentModel IContainer IG.Forms.ScalarFunctionScriptControl.components = null private
Required designer variable.
Referenced by IG.Forms.ScalarFunctionScriptControl.Dispose(), and IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
lblTitle
System Windows Forms Label IG.Forms.ScalarFunctionScriptControl.lblTitle private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
lblDimension
System Windows Forms Label IG.Forms.ScalarFunctionScriptControl.lblDimension private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
lblName
System Windows Forms Label IG.Forms.ScalarFunctionScriptControl.lblName private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent(), and IG.Forms.ScalarFunctionScriptControl.ScalarFunctionScriptControl().
txtName
System Windows Forms TextBox IG.Forms.ScalarFunctionScriptControl.txtName private
Referenced by IG.Forms.ScalarFunctionScriptControl.CopyDataFromController(), IG.Forms.ScalarFunctionScriptControl.CopyDataToController(), IG.Forms.ScalarFunctionScriptControl.InitializeComponent(), and IG.Forms.ScalarFunctionScriptControl.txtName_Validated().
numDimension
System Windows Forms NumericUpDown IG.Forms.ScalarFunctionScriptControl.numDimension private
Referenced by IG.Forms.ScalarFunctionScriptControl.CopyDataFromController(), IG.Forms.ScalarFunctionScriptControl.CopyDataToController(), IG.Forms.ScalarFunctionScriptControl.InitializeComponent(), and IG.Forms.ScalarFunctionScriptControl.numDimension_Validated().
pnlOuter
System Windows Forms Panel IG.Forms.ScalarFunctionScriptControl.pnlOuter private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
txtValue
System Windows Forms TextBox IG.Forms.ScalarFunctionScriptControl.txtValue private
Referenced by IG.Forms.ScalarFunctionScriptControl.CopyDataFromController(), IG.Forms.ScalarFunctionScriptControl.CopyDataToController(), IG.Forms.ScalarFunctionScriptControl.InitializeComponent(), IG.Forms.ScalarFunctionScriptControl.ScalarFunctionScriptControl(), and IG.Forms.ScalarFunctionScriptControl.txtValue_Validated().
lblValue
System Windows Forms Label IG.Forms.ScalarFunctionScriptControl.lblValue private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
txtParameterNames
System Windows Forms TextBox IG.Forms.ScalarFunctionScriptControl.txtParameterNames private
Referenced by IG.Forms.ScalarFunctionScriptControl.CopyDataFromController(), IG.Forms.ScalarFunctionScriptControl.CopyDataToController(), IG.Forms.ScalarFunctionScriptControl.InitializeComponent(), and IG.Forms.ScalarFunctionScriptControl.txtParameterNames_Validated().
lblParameterNames
System Windows Forms Label IG.Forms.ScalarFunctionScriptControl.lblParameterNames private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
chkGradients
System Windows Forms CheckBox IG.Forms.ScalarFunctionScriptControl.chkGradients private
Referenced by IG.Forms.ScalarFunctionScriptControl.chkGradients_CheckedChanged(), and IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
btnValueCalculator
System Windows Forms Button IG.Forms.ScalarFunctionScriptControl.btnValueCalculator private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
btnCreateFunction
System Windows Forms Button IG.Forms.ScalarFunctionScriptControl.btnCreateFunction private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
txtGradients
System Windows Forms TextBox IG.Forms.ScalarFunctionScriptControl.txtGradients private
Referenced by IG.Forms.ScalarFunctionScriptControl.CopyDataFromController(), IG.Forms.ScalarFunctionScriptControl.CopyDataToController(), IG.Forms.ScalarFunctionScriptControl.InitializeComponent(), and IG.Forms.ScalarFunctionScriptControl.txtGradients_Validated().
label1
System Windows Forms Label IG.Forms.ScalarFunctionScriptControl.label1 private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
lblFunctionSignature
System Windows Forms Label IG.Forms.ScalarFunctionScriptControl.lblFunctionSignature private
Referenced by IG.Forms.ScalarFunctionScriptControl.CopyDataFromController(), and IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
btnSummary
System Windows Forms Button IG.Forms.ScalarFunctionScriptControl.btnSummary private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
txtDescription
System Windows Forms TextBox IG.Forms.ScalarFunctionScriptControl.txtDescription private
Referenced by IG.Forms.ScalarFunctionScriptControl.CopyDataFromController(), IG.Forms.ScalarFunctionScriptControl.CopyDataToController(), IG.Forms.ScalarFunctionScriptControl.InitializeComponent(), and IG.Forms.ScalarFunctionScriptControl.txtDescription_Validated().
lblDescription
System Windows Forms Label IG.Forms.ScalarFunctionScriptControl.lblDescription private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
btnPlot1d
System Windows Forms Button IG.Forms.ScalarFunctionScriptControl.btnPlot1d private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
btnPlot2d
System Windows Forms Button IG.Forms.ScalarFunctionScriptControl.btnPlot2d private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
btnSave
System Windows Forms Button IG.Forms.ScalarFunctionScriptControl.btnSave private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
fileSelector1
FileSelector IG.Forms.ScalarFunctionScriptControl.fileSelector1 private
Referenced by IG.Forms.ScalarFunctionScriptControl.btnLoad_Click(), IG.Forms.ScalarFunctionScriptControl.btnSave_Click(), and IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
pnlParameters
System Windows Forms Panel IG.Forms.ScalarFunctionScriptControl.pnlParameters private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
pnlValues
System Windows Forms Panel IG.Forms.ScalarFunctionScriptControl.pnlValues private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
pnlGradients
System Windows Forms Panel IG.Forms.ScalarFunctionScriptControl.pnlGradients private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
pnlButtons
System Windows Forms Panel IG.Forms.ScalarFunctionScriptControl.pnlButtons private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
pnlPlotButtons
System Windows Forms Panel IG.Forms.ScalarFunctionScriptControl.pnlPlotButtons private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
pnlBasic
System Windows Forms Panel IG.Forms.ScalarFunctionScriptControl.pnlBasic private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
pnlTop
System Windows Forms Panel IG.Forms.ScalarFunctionScriptControl.pnlTop private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
pnlBasicAndTitle
System Windows Forms Panel IG.Forms.ScalarFunctionScriptControl.pnlBasicAndTitle private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
btnLoad
System Windows Forms Button IG.Forms.ScalarFunctionScriptControl.btnLoad private
Referenced by IG.Forms.ScalarFunctionScriptControl.InitializeComponent().
_gradientDefinitions
string [] IG.Forms.ScalarFunctionScriptControl._gradientDefinitions protected
Property Documentation
Reporter
IG Lib IReporter IG.Forms.ScalarFunctionScriptControl.Reporter get protected
Reporter used for internal reporting.
Referenced by IG.Forms.ScalarFunctionScriptControl.btnCreateFunction_Click(), IG.Forms.ScalarFunctionScriptControl.btnLoad_Click(), IG.Forms.ScalarFunctionScriptControl.btnPlot1d_Click(), IG.Forms.ScalarFunctionScriptControl.btnPlot2d_Click(), IG.Forms.ScalarFunctionScriptControl.btnSave_Click(), IG.Forms.ScalarFunctionScriptControl.btnValueCalculator_Click(), and IG.Forms.ScalarFunctionScriptControl.CreateFunctonSummary().
FunctionNameTitleNormal
string IG.Forms.ScalarFunctionScriptControl.FunctionNameTitleNormal get set protected
Normal text of the label that introduces function name input box.
Referenced by IG.Forms.ScalarFunctionScriptControl.ScalarFunctionScriptControl().
FunctionNameTitleModified
string IG.Forms.ScalarFunctionScriptControl.FunctionNameTitleModified get set protected
Normal text of the label that introduces function name input box.
FunctionController
ScalarFunctionScriptController IG.Forms.ScalarFunctionScriptControl.FunctionController get set
Cotroller that holds the definition data of the scalar function entered by the current control, and also holds mechanism for compiling and loading scalar function from these definitions.
Referenced by IG.Forms.ScalarFunctionScriptControl.btnCreateFunction_Click(), IG.Forms.ScalarFunctionScriptControl.btnLoad_Click(), IG.Forms.ScalarFunctionScriptControl.btnPlot1d_Click(), IG.Forms.ScalarFunctionScriptControl.btnPlot2d_Click(), IG.Forms.ScalarFunctionScriptControl.btnSave_Click(), IG.Forms.ScalarFunctionScriptControl.btnValueCalculator_Click(), IG.Forms.ScalarFunctionScriptControl.CopyDataFromController(), IG.Forms.ScalarFunctionScriptControl.CopyDataToController(), IG.Forms.ScalarFunctionScriptControl.GetFunctionSignature(), IG.Forms.VectorFunctionScriptControl.InitializeComponent(), IG.Forms.ScalarFunctionScriptForm.InitializeComponent(), IG.Forms.VectorFunctionScriptControl.SynchronizeData(), IG.Forms.ScalarFunctionScriptControl.txtGradients_Validated(), and IG.Forms.ScalarFunctionScriptControl.txtParameterNames_Validated().
FunctionLoader
ScalarFunctionLoader IG.Forms.ScalarFunctionScriptControl.FunctionLoader get protected set
Scalar function loader that is responsible for creation of scalar function objects from data.
Function
LoadableScalarFunctionBase IG.Forms.ScalarFunctionScriptControl.Function get
Gets the function generated by the function loader.
Function loader from the FunctionController is used.
Referenced by IG.Forms.ScalarFunctionScriptControl.btnPlot1d_Click(), IG.Forms.ScalarFunctionScriptControl.btnPlot2d_Click(), and IG.Forms.ScalarFunctionScriptControl.btnValueCalculator_Click().
VectorFunctionControl
VectorFunctionScriptControl IG.Forms.ScalarFunctionScriptControl.VectorFunctionControl get set
The parent vector function script control. When this control is embedded within the vector function script control, this property should be set such that communication back to parent is enabled (in particular, communication about unsaved changes).
Referenced by IG.Forms.ScalarFunctionScriptControl.HasParentUnsavedChanges(), IG.Forms.VectorFunctionScriptControl.InitializeComponent(), and IG.Forms.VectorFunctionScriptControl.VectorFunctionScriptControl().
HasUnsavedChanges
bool IG.Forms.ScalarFunctionScriptControl.HasUnsavedChanges get set protected set
Whether the current function definition has unsaved changes.
Referenced by IG.Forms.ScalarFunctionScriptControl.btnLoad_Click(), IG.Forms.ScalarFunctionScriptControl.btnSave_Click(), IG.Forms.VectorFunctionScriptControl.InitializeComponent(), IG.Forms.ScalarFunctionScriptControl.ScalarFunctionScriptControl(), IG.Forms.ScalarFunctionScriptForm.ScalarFunctionScriptForm(), and IG.Forms.VectorFunctionScriptControl.VectorFunctionScriptControl().
IsLoaderConsistent
bool IG.Forms.ScalarFunctionScriptControl.IsLoaderConsistent get protected set
Whether function loader is in consistent state.
This method shoulld be elaborated or dropped.
FunctionName
string IG.Forms.ScalarFunctionScriptControl.FunctionName get set
Name of the function.
Referenced by IG.Forms.ScalarFunctionScriptControl.btnValueCalculator_Click(), IG.Forms.ScalarFunctionScriptControl.CreateFunctonSummary(), IG.Forms.ScalarFunctionScriptControl.GetFunctionSignature(), IG.Forms.VectorFunctionScriptControl.InitializeComponent(), IG.Neural.Forms.NeuralSamplingControl.InitializeComponent(), IG.Forms.ScalarFunctionScriptForm.InitializeComponent(), IG.Forms.ScalarFunctionScriptControl.ScalarFunctionScriptControl(), IG.Forms.ScalarFunctionScriptControl.SetTestDefinitions(), and IG.Forms.ScalarFunctionScriptControl.txtName_Validated().
FunctionDescription
string IG.Forms.ScalarFunctionScriptControl.FunctionDescription get set
Referenced by IG.Forms.VectorFunctionScriptControl.InitializeComponent(), IG.Forms.ScalarFunctionScriptForm.InitializeComponent(), IG.Forms.ScalarFunctionScriptControl.SetTestDefinitions(), and IG.Forms.ScalarFunctionScriptControl.txtDescription_Validated().
Dimension
int IG.Forms.ScalarFunctionScriptControl.Dimension get set
Gets or sets function dimension.
Referenced by IG.Forms.ScalarFunctionScriptControl.btnValueCalculator_Click(), IG.Forms.VectorFunctionScriptControl.InitializeComponent(), IG.Forms.ScalarFunctionScriptForm.InitializeComponent(), IG.Neural.Forms.NeuralSamplingControl.InitializeComponent(), IG.Forms.ScalarFunctionScriptControl.numDimension_Validated(), and IG.Forms.ScalarFunctionScriptControl.ResetFunctionDefinition().
ParameterNames
string [] IG.Forms.ScalarFunctionScriptControl.ParameterNames get set
Names of function parameters.
Referenced by IG.Forms.ScalarFunctionScriptControl.btnValueCalculator_Click(), IG.Forms.ScalarFunctionScriptControl.CreateFunctonSummary(), IG.Forms.VectorFunctionScriptControl.InitializeComponent(), IG.Neural.Forms.NeuralSamplingControl.InitializeComponent(), IG.Forms.ScalarFunctionScriptForm.InitializeComponent(), IG.Forms.ScalarFunctionScriptControl.ScalarFunctionScriptControl(), IG.Forms.ScalarFunctionScriptControl.SetTestDefinitions(), and IG.Forms.ScalarFunctionScriptControl.txtParameterNames_Validated().
ValueDefinition
string IG.Forms.ScalarFunctionScriptControl.ValueDefinition get set
String that defines function value.
Referenced by IG.Forms.ScalarFunctionScriptControl.CreateFunctonSummary(), IG.Forms.VectorFunctionScriptControl.InitializeComponent(), IG.Neural.Forms.NeuralSamplingControl.InitializeComponent(), IG.Forms.ScalarFunctionScriptForm.InitializeComponent(), IG.Forms.ScalarFunctionScriptControl.ResetFunctionDefinition(), IG.Forms.ScalarFunctionScriptControl.ScalarFunctionScriptControl(), IG.Forms.ScalarFunctionScriptControl.SetTestDefinitions(), and IG.Forms.ScalarFunctionScriptControl.txtValue_Validated().
IsGradientDefined
bool IG.Forms.ScalarFunctionScriptControl.IsGradientDefined get set
Referenced by IG.Forms.ScalarFunctionScriptControl.chkGradients_CheckedChanged(), IG.Forms.ScalarFunctionScriptControl.CopyDataFromController(), IG.Forms.ScalarFunctionScriptControl.CopyDataToController(), IG.Forms.ScalarFunctionScriptControl.CreateFunctonSummary(), IG.Forms.VectorFunctionScriptControl.InitializeComponent(), IG.Neural.Forms.NeuralSamplingControl.InitializeComponent(), IG.Forms.ScalarFunctionScriptForm.InitializeComponent(), and IG.Forms.ScalarFunctionScriptControl.ScalarFunctionScriptControl().
GradientDefinitions
string [] IG.Forms.ScalarFunctionScriptControl.GradientDefinitions get set
String that defines function gradients.
Referenced by IG.Forms.ScalarFunctionScriptControl.CreateFunctonSummary(), IG.Forms.VectorFunctionScriptControl.InitializeComponent(), IG.Neural.Forms.NeuralSamplingControl.InitializeComponent(), IG.Forms.ScalarFunctionScriptForm.InitializeComponent(), IG.Forms.ScalarFunctionScriptControl.ResetFunctionDefinition(), IG.Forms.ScalarFunctionScriptControl.ScalarFunctionScriptControl(), IG.Forms.ScalarFunctionScriptControl.SetTestDefinitions(), and IG.Forms.ScalarFunctionScriptControl.txtGradients_Validated().
DataDefinition
InputOutputDataDefiniton IG.Forms.ScalarFunctionScriptControl.DataDefinition get set private
Definition of input and output data for the represented scalar function.
Referenced by IG.Forms.ScalarFunctionScriptControl.btnLoad_Click(), IG.Forms.ScalarFunctionScriptControl.btnPlot1d_Click(), IG.Forms.ScalarFunctionScriptControl.btnPlot2d_Click(), and IG.Forms.ScalarFunctionScriptControl.btnSave_Click().
FileSelector
FileSelector IG.Forms.ScalarFunctionScriptControl.FileSelector get
GUI component for seclecting files.
The documentation for this class was generated from the following files:
iglib/extensions/iglibext/Forms/Numeric/ScalarFunctionScriptControl.cs
iglib/extensions/iglibext/Forms/Numeric/ScalarFunctionScriptControl.Designer.cs