Doc: IGLib EXTENDED: XORProblem.MainForm Class Reference
XORProblem.MainForm Class Reference
Summary description for Form1.
Public Member Functions
MainForm ()
MainForm ()
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void EnableControls (bool enable)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void EnableControls (bool enable)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
delegate void SetTextCallback (System.Windows.Forms.Control control, string text)
void SetText (System.Windows.Forms.Control control, string text)
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
delegate void EnableCallback (bool enable)
void EnableControls (bool enable)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
Static Private Member Functions
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
Private Attributes
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.Label label1
System.Windows.Forms.TextBox learningRateBox
System.Windows.Forms.Label label2
System.Windows.Forms.TextBox alphaBox
System.Windows.Forms.Label label3
System.Windows.Forms.TextBox errorLimitBox
System.Windows.Forms.Label label4
System.Windows.Forms.ComboBox sigmoidTypeCombo
System.Windows.Forms.TextBox currentErrorBox
System.Windows.Forms.Label label11
System.Windows.Forms.TextBox currentIterationBox
System.Windows.Forms.Label label8
System.Windows.Forms.Label label7
System.Windows.Forms.Label label5
System.Windows.Forms.Button stopButton
System.Windows.Forms.Button startButton
System.Windows.Forms.GroupBox groupBox2
AForge.Controls.Chart errorChart
System.Windows.Forms.CheckBox saveFilesCheck
System.Windows.Forms.Label label6
System.Windows.Forms.TextBox momentumBox
System.ComponentModel.Container components = null
Required designer variable.
double learningRate = 0.1
double momentum = 0.0
double sigmoidAlphaValue = 2.0
double learningErrorLimit = 0.1
int sigmoidType = 0
bool saveStatisticsToFiles = false
Thread workerThread = null
bool needToStop = false
Chart errorChart
volatile bool needToStop = false
Detailed Description
Summary description for Form1.
Summary description for MainForm.
Constructor & Destructor Documentation
MainForm() [1/3]
XORProblem.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), XORProblem.MainForm.errorChart, XORProblem.MainForm.InitializeComponent(), and XORProblem.MainForm.UpdateSettings().
Referenced by XORProblem.MainForm.Main().
MainForm() [2/3]
XORProblem.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), XORProblem.MainForm.errorChart, XORProblem.MainForm.InitializeComponent(), and XORProblem.MainForm.UpdateSettings().
MainForm() [3/3]
XORProblem.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), XORProblem.MainForm.errorChart, XORProblem.MainForm.InitializeComponent(), and XORProblem.MainForm.UpdateSettings().
Member Function Documentation
Dispose() [1/3]
override void XORProblem.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References XORProblem.MainForm.components.
InitializeComponent() [1/3]
void XORProblem.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by XORProblem.MainForm.MainForm().
Main() [1/3]
static void XORProblem.MainForm.Main () inline static private
The main entry point for the application.
References XORProblem.MainForm.MainForm().
MainForm_Closing() [1/3]
void XORProblem.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References XORProblem.MainForm.needToStop, and XORProblem.MainForm.workerThread.
UpdateSettings() [1/3]
void XORProblem.MainForm.UpdateSettings () inline private
References XORProblem.MainForm.alphaBox, XORProblem.MainForm.errorLimitBox, XORProblem.MainForm.learningErrorLimit, XORProblem.MainForm.learningRate, XORProblem.MainForm.learningRateBox, XORProblem.MainForm.momentum, XORProblem.MainForm.momentumBox, XORProblem.MainForm.saveFilesCheck, XORProblem.MainForm.saveStatisticsToFiles, XORProblem.MainForm.sigmoidAlphaValue, XORProblem.MainForm.sigmoidType, and XORProblem.MainForm.sigmoidTypeCombo.
Referenced by XORProblem.MainForm.MainForm(), and XORProblem.MainForm.startButton_Click().
EnableControls() [1/3]
void XORProblem.MainForm.EnableControls (bool enable) inline private
References XORProblem.MainForm.alphaBox, XORProblem.MainForm.errorLimitBox, XORProblem.MainForm.learningRateBox, XORProblem.MainForm.momentumBox, XORProblem.MainForm.saveFilesCheck, XORProblem.MainForm.sigmoidTypeCombo, XORProblem.MainForm.startButton, and XORProblem.MainForm.stopButton.
Referenced by XORProblem.MainForm.EnableControls(), XORProblem.MainForm.SearchSolution(), and XORProblem.MainForm.startButton_Click().
startButton_Click() [1/3]
void XORProblem.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References XORProblem.MainForm.alphaBox, XORProblem.MainForm.EnableControls(), XORProblem.MainForm.errorLimitBox, XORProblem.MainForm.learningErrorLimit, XORProblem.MainForm.learningRate, XORProblem.MainForm.learningRateBox, XORProblem.MainForm.momentum, XORProblem.MainForm.momentumBox, XORProblem.MainForm.needToStop, XORProblem.MainForm.saveFilesCheck, XORProblem.MainForm.saveStatisticsToFiles, XORProblem.MainForm.SearchSolution(), XORProblem.MainForm.sigmoidAlphaValue, XORProblem.MainForm.sigmoidType, XORProblem.MainForm.sigmoidTypeCombo, XORProblem.MainForm.UpdateSettings(), and XORProblem.MainForm.workerThread.
stopButton_Click() [1/3]
void XORProblem.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References XORProblem.MainForm.needToStop, and XORProblem.MainForm.workerThread.
SearchSolution() [1/3]
void XORProblem.MainForm.SearchSolution () inline private
References XORProblem.MainForm.currentErrorBox, XORProblem.MainForm.currentIterationBox, XORProblem.MainForm.EnableControls(), XORProblem.MainForm.errorChart, XORProblem.MainForm.learningErrorLimit, AForge.Neuro.Learning.BackPropagationLearning.LearningRate, XORProblem.MainForm.learningRate, XORProblem.MainForm.momentum, AForge.Neuro.Learning.BackPropagationLearning.Momentum, XORProblem.MainForm.needToStop, AForge.Controls.Chart.RangeX, AForge.Neuro.Learning.BackPropagationLearning.RunEpoch(), XORProblem.MainForm.saveStatisticsToFiles, XORProblem.MainForm.sigmoidAlphaValue, XORProblem.MainForm.sigmoidType, and AForge.Controls.Chart.UpdateDataSeries().
Referenced by XORProblem.MainForm.startButton_Click().
Dispose() [2/3]
override void XORProblem.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References XORProblem.MainForm.components.
InitializeComponent() [2/3]
void XORProblem.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [2/3]
static void XORProblem.MainForm.Main () inline static private
The main entry point for the application.
References XORProblem.MainForm.MainForm().
MainForm_Closing() [2/3]
void XORProblem.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References XORProblem.MainForm.needToStop, and XORProblem.MainForm.workerThread.
UpdateSettings() [2/3]
void XORProblem.MainForm.UpdateSettings () inline private
References XORProblem.MainForm.alphaBox, XORProblem.MainForm.errorLimitBox, XORProblem.MainForm.learningErrorLimit, XORProblem.MainForm.learningRate, XORProblem.MainForm.learningRateBox, XORProblem.MainForm.momentum, XORProblem.MainForm.momentumBox, XORProblem.MainForm.saveFilesCheck, XORProblem.MainForm.saveStatisticsToFiles, XORProblem.MainForm.sigmoidAlphaValue, XORProblem.MainForm.sigmoidType, and XORProblem.MainForm.sigmoidTypeCombo.
EnableControls() [2/3]
void XORProblem.MainForm.EnableControls (bool enable) inline private
References XORProblem.MainForm.alphaBox, XORProblem.MainForm.errorLimitBox, XORProblem.MainForm.learningRateBox, XORProblem.MainForm.momentumBox, XORProblem.MainForm.saveFilesCheck, XORProblem.MainForm.sigmoidTypeCombo, XORProblem.MainForm.startButton, and XORProblem.MainForm.stopButton.
startButton_Click() [2/3]
void XORProblem.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References XORProblem.MainForm.alphaBox, XORProblem.MainForm.EnableControls(), XORProblem.MainForm.errorLimitBox, XORProblem.MainForm.learningErrorLimit, XORProblem.MainForm.learningRate, XORProblem.MainForm.learningRateBox, XORProblem.MainForm.momentum, XORProblem.MainForm.momentumBox, XORProblem.MainForm.needToStop, XORProblem.MainForm.saveFilesCheck, XORProblem.MainForm.saveStatisticsToFiles, XORProblem.MainForm.SearchSolution(), XORProblem.MainForm.sigmoidAlphaValue, XORProblem.MainForm.sigmoidType, XORProblem.MainForm.sigmoidTypeCombo, XORProblem.MainForm.UpdateSettings(), and XORProblem.MainForm.workerThread.
stopButton_Click() [2/3]
void XORProblem.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References XORProblem.MainForm.needToStop, and XORProblem.MainForm.workerThread.
SearchSolution() [2/3]
void XORProblem.MainForm.SearchSolution () inline private
References XORProblem.MainForm.currentErrorBox, XORProblem.MainForm.currentIterationBox, XORProblem.MainForm.EnableControls(), XORProblem.MainForm.errorChart, XORProblem.MainForm.learningErrorLimit, AForge.Neuro.Learning.BackPropagationLearning.LearningRate, XORProblem.MainForm.learningRate, XORProblem.MainForm.momentum, AForge.Neuro.Learning.BackPropagationLearning.Momentum, XORProblem.MainForm.needToStop, AForge.Controls.Chart.RangeX, AForge.Neuro.Learning.BackPropagationLearning.RunEpoch(), XORProblem.MainForm.saveStatisticsToFiles, XORProblem.MainForm.sigmoidAlphaValue, XORProblem.MainForm.sigmoidType, and AForge.Controls.Chart.UpdateDataSeries().
Dispose() [3/3]
override void XORProblem.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References XORProblem.MainForm.components.
InitializeComponent() [3/3]
void XORProblem.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [3/3]
static void XORProblem.MainForm.Main () inline static private
The main entry point for the application.
References XORProblem.MainForm.MainForm().
SetTextCallback()
delegate void XORProblem.MainForm.SetTextCallback (System.Windows.Forms.Control control, string text) private
Referenced by XORProblem.MainForm.SetText().
SetText()
void XORProblem.MainForm.SetText (System.Windows.Forms.Control control, string text) inline private
References XORProblem.MainForm.SetTextCallback().
Referenced by XORProblem.MainForm.SearchSolution().
MainForm_Closing() [3/3]
void XORProblem.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References XORProblem.MainForm.needToStop, and XORProblem.MainForm.workerThread.
UpdateSettings() [3/3]
void XORProblem.MainForm.UpdateSettings () inline private
References XORProblem.MainForm.alphaBox, XORProblem.MainForm.errorLimitBox, XORProblem.MainForm.learningErrorLimit, XORProblem.MainForm.learningRate, XORProblem.MainForm.learningRateBox, XORProblem.MainForm.momentum, XORProblem.MainForm.momentumBox, XORProblem.MainForm.saveFilesCheck, XORProblem.MainForm.saveStatisticsToFiles, XORProblem.MainForm.sigmoidAlphaValue, XORProblem.MainForm.sigmoidType, and XORProblem.MainForm.sigmoidTypeCombo.
EnableCallback()
delegate void XORProblem.MainForm.EnableCallback (bool enable) private
Referenced by XORProblem.MainForm.EnableControls().
EnableControls() [3/3]
void XORProblem.MainForm.EnableControls (bool enable) inline private
References XORProblem.MainForm.alphaBox, XORProblem.MainForm.EnableCallback(), XORProblem.MainForm.EnableControls(), XORProblem.MainForm.errorLimitBox, XORProblem.MainForm.learningRateBox, XORProblem.MainForm.momentumBox, XORProblem.MainForm.saveFilesCheck, XORProblem.MainForm.sigmoidTypeCombo, XORProblem.MainForm.startButton, and XORProblem.MainForm.stopButton.
startButton_Click() [3/3]
void XORProblem.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References XORProblem.MainForm.alphaBox, XORProblem.MainForm.EnableControls(), XORProblem.MainForm.errorLimitBox, XORProblem.MainForm.learningErrorLimit, XORProblem.MainForm.learningRate, XORProblem.MainForm.learningRateBox, XORProblem.MainForm.momentum, XORProblem.MainForm.momentumBox, XORProblem.MainForm.needToStop, XORProblem.MainForm.saveFilesCheck, XORProblem.MainForm.saveStatisticsToFiles, XORProblem.MainForm.SearchSolution(), XORProblem.MainForm.sigmoidAlphaValue, XORProblem.MainForm.sigmoidType, XORProblem.MainForm.sigmoidTypeCombo, XORProblem.MainForm.UpdateSettings(), and XORProblem.MainForm.workerThread.
stopButton_Click() [3/3]
void XORProblem.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References XORProblem.MainForm.needToStop, and XORProblem.MainForm.workerThread.
SearchSolution() [3/3]
void XORProblem.MainForm.SearchSolution () inline private
References XORProblem.MainForm.currentErrorBox, XORProblem.MainForm.currentIterationBox, XORProblem.MainForm.EnableControls(), XORProblem.MainForm.errorChart, XORProblem.MainForm.learningErrorLimit, AForge.Neuro.Learning.BackPropagationLearning.LearningRate, XORProblem.MainForm.learningRate, XORProblem.MainForm.momentum, AForge.Neuro.Learning.BackPropagationLearning.Momentum, XORProblem.MainForm.needToStop, AForge.Controls.Chart.RangeX, AForge.Neuro.Learning.BackPropagationLearning.RunEpoch(), XORProblem.MainForm.saveStatisticsToFiles, XORProblem.MainForm.SetText(), XORProblem.MainForm.sigmoidAlphaValue, XORProblem.MainForm.sigmoidType, and AForge.Controls.Chart.UpdateDataSeries().
Member Data Documentation
groupBox1
System Windows Forms GroupBox XORProblem.MainForm.groupBox1 private
label1
System Windows Forms Label XORProblem.MainForm.label1 private
learningRateBox
System Windows Forms TextBox XORProblem.MainForm.learningRateBox private
Referenced by XORProblem.MainForm.EnableControls(), XORProblem.MainForm.startButton_Click(), and XORProblem.MainForm.UpdateSettings().
label2
System Windows Forms Label XORProblem.MainForm.label2 private
alphaBox
System Windows Forms TextBox XORProblem.MainForm.alphaBox private
Referenced by XORProblem.MainForm.EnableControls(), XORProblem.MainForm.startButton_Click(), and XORProblem.MainForm.UpdateSettings().
label3
System Windows Forms Label XORProblem.MainForm.label3 private
errorLimitBox
System Windows Forms TextBox XORProblem.MainForm.errorLimitBox private
Referenced by XORProblem.MainForm.EnableControls(), XORProblem.MainForm.startButton_Click(), and XORProblem.MainForm.UpdateSettings().
label4
System Windows Forms Label XORProblem.MainForm.label4 private
sigmoidTypeCombo
System Windows Forms ComboBox XORProblem.MainForm.sigmoidTypeCombo private
Referenced by XORProblem.MainForm.EnableControls(), XORProblem.MainForm.startButton_Click(), and XORProblem.MainForm.UpdateSettings().
currentErrorBox
System Windows Forms TextBox XORProblem.MainForm.currentErrorBox private
Referenced by XORProblem.MainForm.SearchSolution().
label11
System Windows Forms Label XORProblem.MainForm.label11 private
currentIterationBox
System Windows Forms TextBox XORProblem.MainForm.currentIterationBox private
Referenced by XORProblem.MainForm.SearchSolution().
label8
System Windows Forms Label XORProblem.MainForm.label8 private
label7
System Windows Forms Label XORProblem.MainForm.label7 private
label5
System Windows Forms Label XORProblem.MainForm.label5 private
stopButton
System Windows Forms Button XORProblem.MainForm.stopButton private
Referenced by XORProblem.MainForm.EnableControls().
startButton
System Windows Forms Button XORProblem.MainForm.startButton private
Referenced by XORProblem.MainForm.EnableControls().
groupBox2
System Windows Forms GroupBox XORProblem.MainForm.groupBox2 private
errorChart [1/2]
AForge Controls Chart XORProblem.MainForm.errorChart private
Referenced by XORProblem.MainForm.MainForm(), and XORProblem.MainForm.SearchSolution().
saveFilesCheck
System Windows Forms CheckBox XORProblem.MainForm.saveFilesCheck private
Referenced by XORProblem.MainForm.EnableControls(), XORProblem.MainForm.startButton_Click(), and XORProblem.MainForm.UpdateSettings().
label6
System Windows Forms Label XORProblem.MainForm.label6 private
momentumBox
System Windows Forms TextBox XORProblem.MainForm.momentumBox private
Referenced by XORProblem.MainForm.EnableControls(), XORProblem.MainForm.startButton_Click(), and XORProblem.MainForm.UpdateSettings().
components
System ComponentModel Container XORProblem.MainForm.components = null private
Required designer variable.
Referenced by XORProblem.MainForm.Dispose().
learningRate
double XORProblem.MainForm.learningRate = 0.1 private
Referenced by XORProblem.MainForm.SearchSolution(), XORProblem.MainForm.startButton_Click(), and XORProblem.MainForm.UpdateSettings().
momentum
double XORProblem.MainForm.momentum = 0.0 private
Referenced by XORProblem.MainForm.SearchSolution(), XORProblem.MainForm.startButton_Click(), and XORProblem.MainForm.UpdateSettings().
sigmoidAlphaValue
double XORProblem.MainForm.sigmoidAlphaValue = 2.0 private
Referenced by XORProblem.MainForm.SearchSolution(), XORProblem.MainForm.startButton_Click(), and XORProblem.MainForm.UpdateSettings().
learningErrorLimit
double XORProblem.MainForm.learningErrorLimit = 0.1 private
Referenced by XORProblem.MainForm.SearchSolution(), XORProblem.MainForm.startButton_Click(), and XORProblem.MainForm.UpdateSettings().
sigmoidType
int XORProblem.MainForm.sigmoidType = 0 private
Referenced by XORProblem.MainForm.SearchSolution(), XORProblem.MainForm.startButton_Click(), and XORProblem.MainForm.UpdateSettings().
saveStatisticsToFiles
bool XORProblem.MainForm.saveStatisticsToFiles = false private
Referenced by XORProblem.MainForm.SearchSolution(), XORProblem.MainForm.startButton_Click(), and XORProblem.MainForm.UpdateSettings().
workerThread
Thread XORProblem.MainForm.workerThread = null private
Referenced by XORProblem.MainForm.MainForm_Closing(), XORProblem.MainForm.startButton_Click(), and XORProblem.MainForm.stopButton_Click().
needToStop [1/2]
bool XORProblem.MainForm.needToStop = false private
Referenced by XORProblem.MainForm.MainForm_Closing(), XORProblem.MainForm.SearchSolution(), XORProblem.MainForm.startButton_Click(), and XORProblem.MainForm.stopButton_Click().
errorChart [2/2]
Chart XORProblem.MainForm.errorChart private
needToStop [2/2]
volatile bool XORProblem.MainForm.needToStop = false private
The documentation for this class was generated from the following file:
shelldev/lib/external/neuralnetworks/neuro_src/Samples/Neuro/Back Propagation/XORProblem/Backup/MainForm.cs