Doc: IGLib EXTENDED: AForge.Imaging.Filters.PointedColorFloodFill Class Reference
AForge.Imaging.Filters.PointedColorFloodFill Class Reference
Flood filling with specified color starting from specified point.
Public Member Functions
PointedColorFloodFill ()
Initializes a new instance of the PointedColorFloodFill class.
PointedColorFloodFill (Color fillColor)
Initializes a new instance of the PointedColorFloodFill class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image, Rectangle rect)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Color Tolerance [get, set]
Flood fill tolerance.
Color FillColor [get, set]
Fill color.
IntPoint StartingPoint [get, set]
Point to start filling from.
Properties inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Member Functions
unsafe void LinearFloodFill4Gray (IntPoint startingPoint)
unsafe void LinearFloodFill4RGB (IntPoint startPoint)
unsafe bool CheckGrayPixel (byte pixel)
unsafe bool CheckRGBPixel (byte *pixel)
byte * CoordsToPointerGray (int x, int y)
byte * CoordsToPointerRGB (int x, int y)
Private Attributes
bool[,] checkedPixels
byte * scan0
int stride
int startX
int stopX
int startY
int stopY
byte minR
byte maxR
byte minG
byte maxG
byte minB
byte maxB
byte fillR
byte fillG
byte fillB
IntPoint startingPoint = new IntPoint(0, 0)
Color tolerance = Color.FromArgb(0, 0, 0)
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Flood filling with specified color starting from specified point.
The filter performs image's area filling (4 directional) starting from the specified point. It fills the area of the pointed color, but also fills other colors, which are similar to the pointed within specified tolerance. The area is filled using specified fill color.
The filter accepts 8 bpp grayscale images and 24 bpp color images for processing.
Sample usage:
// create filter
PointedColorFloodFill filter = new PointedColorFloodFill();
// configure the filter
filter.Tolerance = Color.FromArgb(150, 92, 92);
filter.FillColor = Color.FromArgb(255, 255, 255);
filter.StartingPoint = new IntPoint(150, 100);
// apply the filter
filter.ApplyInPlace(image);
Initial image:
Result image:
See also
PointedMeanFloodFill
Constructor & Destructor Documentation
PointedColorFloodFill() [1/2]
AForge.Imaging.Filters.PointedColorFloodFill.PointedColorFloodFill () inline
Initializes a new instance of the PointedColorFloodFill class.
References AForge.Imaging.Filters.PointedColorFloodFill.formatTranslations.
PointedColorFloodFill() [2/2]
AForge.Imaging.Filters.PointedColorFloodFill.PointedColorFloodFill (Color fillColor) inline
Initializes a new instance of the PointedColorFloodFill class.
Parameters
fillColor Fill color.
References AForge.Imaging.Filters.PointedColorFloodFill.FillColor.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.PointedColorFloodFill.ProcessFilter (UnmanagedImage image, Rectangle rect) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
rect Image rectangle for processing by the filter.
Implements AForge.Imaging.Filters.BaseInPlacePartialFilter.
References AForge.Imaging.RGB.B, AForge.Imaging.Filters.PointedColorFloodFill.checkedPixels, AForge.Imaging.Filters.PointedColorFloodFill.CoordsToPointerGray(), AForge.Imaging.Filters.PointedColorFloodFill.CoordsToPointerRGB(), AForge.Imaging.RGB.G, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4Gray(), AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4RGB(), AForge.Imaging.Filters.PointedColorFloodFill.maxB, AForge.Imaging.Filters.PointedColorFloodFill.maxG, AForge.Imaging.Filters.PointedColorFloodFill.maxR, AForge.Imaging.Filters.PointedColorFloodFill.minB, AForge.Imaging.Filters.PointedColorFloodFill.minG, AForge.Imaging.Filters.PointedColorFloodFill.minR, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, AForge.Imaging.Filters.PointedColorFloodFill.scan0, AForge.Imaging.Filters.PointedColorFloodFill.startingPoint, AForge.Imaging.Filters.PointedColorFloodFill.startX, AForge.Imaging.Filters.PointedColorFloodFill.startY, AForge.Imaging.Filters.PointedColorFloodFill.stopX, AForge.Imaging.Filters.PointedColorFloodFill.stopY, AForge.Imaging.Filters.PointedColorFloodFill.stride, AForge.Imaging.UnmanagedImage.Stride, AForge.Imaging.Filters.PointedColorFloodFill.tolerance, AForge.Imaging.UnmanagedImage.Width, AForge.IntPoint.X, and AForge.IntPoint.Y.
LinearFloodFill4Gray()
unsafe void AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4Gray (IntPoint startingPoint) inline private
References AForge.Imaging.Filters.PointedColorFloodFill.checkedPixels, AForge.Imaging.Filters.PointedColorFloodFill.CheckGrayPixel(), AForge.Imaging.Filters.PointedColorFloodFill.CoordsToPointerGray(), AForge.Imaging.Filters.PointedColorFloodFill.fillG, AForge.Imaging.Filters.PointedColorFloodFill.startingPoint, AForge.Imaging.Filters.PointedColorFloodFill.startX, AForge.Imaging.Filters.PointedColorFloodFill.startY, AForge.Imaging.Filters.PointedColorFloodFill.stopX, AForge.Imaging.Filters.PointedColorFloodFill.stopY, AForge.Imaging.Filters.PointedColorFloodFill.stride, AForge.IntPoint.X, and AForge.IntPoint.Y.
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.ProcessFilter().
LinearFloodFill4RGB()
unsafe void AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4RGB (IntPoint startPoint) inline private
References AForge.Imaging.RGB.B, AForge.Imaging.Filters.PointedColorFloodFill.checkedPixels, AForge.Imaging.Filters.PointedColorFloodFill.CheckRGBPixel(), AForge.Imaging.Filters.PointedColorFloodFill.CoordsToPointerRGB(), AForge.Imaging.Filters.PointedColorFloodFill.fillB, AForge.Imaging.Filters.PointedColorFloodFill.fillG, AForge.Imaging.Filters.PointedColorFloodFill.fillR, AForge.Imaging.RGB.G, AForge.Imaging.RGB.R, AForge.Imaging.Filters.PointedColorFloodFill.startingPoint, AForge.Imaging.Filters.PointedColorFloodFill.startX, AForge.Imaging.Filters.PointedColorFloodFill.startY, AForge.Imaging.Filters.PointedColorFloodFill.stopX, AForge.Imaging.Filters.PointedColorFloodFill.stopY, AForge.Imaging.Filters.PointedColorFloodFill.stride, AForge.IntPoint.X, and AForge.IntPoint.Y.
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.ProcessFilter().
CheckGrayPixel()
unsafe bool AForge.Imaging.Filters.PointedColorFloodFill.CheckGrayPixel (byte pixel) inline private
References AForge.Imaging.Filters.PointedColorFloodFill.maxG, and AForge.Imaging.Filters.PointedColorFloodFill.minG.
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4Gray().
CheckRGBPixel()
unsafe bool AForge.Imaging.Filters.PointedColorFloodFill.CheckRGBPixel (byte * pixel) inline private
References AForge.Imaging.RGB.B, AForge.Imaging.RGB.G, AForge.Imaging.Filters.PointedColorFloodFill.maxB, AForge.Imaging.Filters.PointedColorFloodFill.maxG, AForge.Imaging.Filters.PointedColorFloodFill.maxR, AForge.Imaging.Filters.PointedColorFloodFill.minB, AForge.Imaging.Filters.PointedColorFloodFill.minG, AForge.Imaging.Filters.PointedColorFloodFill.minR, and AForge.Imaging.RGB.R.
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4RGB().
CoordsToPointerGray()
byte* AForge.Imaging.Filters.PointedColorFloodFill.CoordsToPointerGray (int x, int y) inline private
References AForge.Imaging.Filters.PointedColorFloodFill.scan0, and AForge.Imaging.Filters.PointedColorFloodFill.stride.
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4Gray(), and AForge.Imaging.Filters.PointedColorFloodFill.ProcessFilter().
CoordsToPointerRGB()
byte* AForge.Imaging.Filters.PointedColorFloodFill.CoordsToPointerRGB (int x, int y) inline private
References AForge.Imaging.Filters.PointedColorFloodFill.scan0, and AForge.Imaging.Filters.PointedColorFloodFill.stride.
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4RGB(), and AForge.Imaging.Filters.PointedColorFloodFill.ProcessFilter().
Member Data Documentation
checkedPixels
bool [,] AForge.Imaging.Filters.PointedColorFloodFill.checkedPixels private
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4Gray(), AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4RGB(), and AForge.Imaging.Filters.PointedColorFloodFill.ProcessFilter().
scan0
byte* AForge.Imaging.Filters.PointedColorFloodFill.scan0 private
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.CoordsToPointerGray(), AForge.Imaging.Filters.PointedColorFloodFill.CoordsToPointerRGB(), and AForge.Imaging.Filters.PointedColorFloodFill.ProcessFilter().
stride
int AForge.Imaging.Filters.PointedColorFloodFill.stride private
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.CoordsToPointerGray(), AForge.Imaging.Filters.PointedColorFloodFill.CoordsToPointerRGB(), AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4Gray(), AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4RGB(), and AForge.Imaging.Filters.PointedColorFloodFill.ProcessFilter().
startX
int AForge.Imaging.Filters.PointedColorFloodFill.startX private
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4Gray(), AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4RGB(), and AForge.Imaging.Filters.PointedColorFloodFill.ProcessFilter().
stopX
int AForge.Imaging.Filters.PointedColorFloodFill.stopX private
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4Gray(), AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4RGB(), and AForge.Imaging.Filters.PointedColorFloodFill.ProcessFilter().
startY
int AForge.Imaging.Filters.PointedColorFloodFill.startY private
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4Gray(), AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4RGB(), and AForge.Imaging.Filters.PointedColorFloodFill.ProcessFilter().
stopY
int AForge.Imaging.Filters.PointedColorFloodFill.stopY private
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4Gray(), AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4RGB(), and AForge.Imaging.Filters.PointedColorFloodFill.ProcessFilter().
minR
byte AForge.Imaging.Filters.PointedColorFloodFill.minR private
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.CheckRGBPixel(), and AForge.Imaging.Filters.PointedColorFloodFill.ProcessFilter().
maxR
byte AForge.Imaging.Filters.PointedColorFloodFill.maxR private
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.CheckRGBPixel(), and AForge.Imaging.Filters.PointedColorFloodFill.ProcessFilter().
minG
byte AForge.Imaging.Filters.PointedColorFloodFill.minG private
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.CheckGrayPixel(), AForge.Imaging.Filters.PointedColorFloodFill.CheckRGBPixel(), and AForge.Imaging.Filters.PointedColorFloodFill.ProcessFilter().
maxG
byte AForge.Imaging.Filters.PointedColorFloodFill.maxG private
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.CheckGrayPixel(), AForge.Imaging.Filters.PointedColorFloodFill.CheckRGBPixel(), and AForge.Imaging.Filters.PointedColorFloodFill.ProcessFilter().
minB
byte AForge.Imaging.Filters.PointedColorFloodFill.minB private
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.CheckRGBPixel(), and AForge.Imaging.Filters.PointedColorFloodFill.ProcessFilter().
maxB
byte AForge.Imaging.Filters.PointedColorFloodFill.maxB private
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.CheckRGBPixel(), and AForge.Imaging.Filters.PointedColorFloodFill.ProcessFilter().
fillR
byte AForge.Imaging.Filters.PointedColorFloodFill.fillR private
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4RGB().
fillG
byte AForge.Imaging.Filters.PointedColorFloodFill.fillG private
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4Gray(), and AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4RGB().
fillB
byte AForge.Imaging.Filters.PointedColorFloodFill.fillB private
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4RGB().
startingPoint
IntPoint AForge.Imaging.Filters.PointedColorFloodFill.startingPoint = new IntPoint(0, 0) private
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4Gray(), AForge.Imaging.Filters.PointedColorFloodFill.LinearFloodFill4RGB(), and AForge.Imaging.Filters.PointedColorFloodFill.ProcessFilter().
tolerance
Color AForge.Imaging.Filters.PointedColorFloodFill.tolerance = Color.FromArgb(0, 0, 0) private
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.PointedColorFloodFill.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.PointedColorFloodFill().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.PointedColorFloodFill.FormatTranslations get
Format translations dictionary.
Tolerance
Color AForge.Imaging.Filters.PointedColorFloodFill.Tolerance get set
Flood fill tolerance.
The tolerance value determines which colors to fill. If the value is set to 0, then only color of the pointed pixel is filled. If the value is not 0, then other colors may be filled as well, which are similar to the color of the pointed pixel within the specified tolerance.
The tolerance value is specified as System.Drawing.Color, where each component (R, G and B) represents tolerance for the corresponding component of color. This allows to set different tolerances for red, green and blue components.
FillColor
Color AForge.Imaging.Filters.PointedColorFloodFill.FillColor get set
Fill color.
The fill color is used to fill image's area starting from the specified point.
For grayscale images the color needs to be specified with all three RGB values set to the same value, (128, 128, 128) for example.
Default value is set to black.
Referenced by AForge.Imaging.Filters.PointedColorFloodFill.PointedColorFloodFill().
StartingPoint
IntPoint AForge.Imaging.Filters.PointedColorFloodFill.StartingPoint get set
Point to start filling from.
The property allows to set the starting point, where filling is started from.
Default value is set to (0, 0).
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Flood Fillers/PointedColorFloodFill.cs