Doc: IGLib EXTENDED: NUnit.Framework.Api.ITestAssemblyBuilder Interface Reference
NUnit.Framework.Api.ITestAssemblyBuilder Interface Reference
The ITestAssemblyBuilder interface is implemented by a class that is able to build a suite of tests given an assembly or an assembly filename.
Public Member Functions
ITest Build (Assembly assembly, IDictionary options)
Build a suite of tests from a provided assembly
ITest Build (string assemblyName, IDictionary options)
Build a suite of tests given the filename of an assembly
Detailed Description
The ITestAssemblyBuilder interface is implemented by a class that is able to build a suite of tests given an assembly or an assembly filename.
Member Function Documentation
Build() [1/2]
ITest NUnit.Framework.Api.ITestAssemblyBuilder.Build (Assembly assembly, IDictionary options)
Build a suite of tests from a provided assembly
Parameters
assembly The assembly from which tests are to be built
options A dictionary of options to use in building the suite
Returns
A TestSuite containing the tests found in the assembly
Implemented in NUnit.Framework.Api.DefaultTestAssemblyBuilder.
Referenced by NUnit.Framework.Internal.SetUpFixtureTests.AssemblySetUpFixtureReplacesAssemblyNodeInTree(), NUnit.Framework.Internal.SetUpFixtureTests.InvalidAssemblySetUpFixtureIsLoadedCorrectly(), NUnit.Framework.Api.NUnitTestAssemblyRunner.Load(), and NUnit.Framework.Internal.SetUpFixtureTests.NamespaceSetUpFixtureReplacesNamespaceNodeInTree().
Build() [2/2]
ITest NUnit.Framework.Api.ITestAssemblyBuilder.Build (string assemblyName, IDictionary options)
Build a suite of tests given the filename of an assembly
Parameters
assemblyName The filename of the assembly from which tests are to be built
options A dictionary of options to use in building the suite
Returns
A TestSuite containing the tests found in the assembly
Implemented in NUnit.Framework.Api.DefaultTestAssemblyBuilder.
The documentation for this interface was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Api/ITestAssemblyBuilder.cs