Doc: IGLib EXTENDED: CShell.Modules.Editors.ViewModels.EditorViewModel Class Reference
CShell.Modules.Editors.ViewModels.EditorViewModel Class Reference
Public Member Functions
override void CanClose (System.Action< bool > callback)
void Open (Uri uri)
override void Save ()
override void SaveAs (string newFile)
string GetSelectionOrCurrentLine ()
override bool Equals (object obj)
void Undo ()
void Redo ()
void Cut ()
void Copy ()
void Paste ()
void SelectAll ()
void Select (int start, int length)
Selects a section in the text.
void Comment ()
void Uncomment ()
Protected Member Functions
override void OnViewLoaded (object view)
Properties
string File [get]
override Uri Uri [get, set]
override bool IsDirty [get, set]
string Text [get, set]
Properties inherited from CShell.Framework.Document
ICommand?? CloseCommand [get]
virtual Uri Uri [get, set]
virtual bool IsDirty [get, set]
Properties inherited from CShell.Framework.IDocument
ICommand CloseCommand [get]
Uri Uri [get]
bool IsDirty [get]
Properties inherited from CShell.Framework.ITextDocument
string Text [get, set]
Private Member Functions
IHighlightingDefinition GetHighlighting (string fileExtension)
Private Attributes
string originalText
string path
string fileName
bool isDirty
CodeTextEditor textEditor
EditorView editorView
Member Function Documentation
CanClose()
override void CShell.Modules.Editors.ViewModels.EditorViewModel.CanClose (System.Action< bool > callback) inline
References CShell.Modules.Editors.ViewModels.EditorViewModel.IsDirty, CShell.Framework.Services.Execute.OnUIThreadEx(), and CShell.Modules.Editors.ViewModels.EditorViewModel.Uri.
Open()
void CShell.Modules.Editors.ViewModels.EditorViewModel.Open (Uri uri) inline
References CShell.Modules.Editors.ViewModels.EditorViewModel.fileName, CShell.Modules.Editors.ViewModels.EditorViewModel.path, and CShell.Modules.Editors.ViewModels.EditorViewModel.Uri.
OnViewLoaded()
override void CShell.Modules.Editors.ViewModels.EditorViewModel.OnViewLoaded (object view) inline protected
References CShell.ScriptingEngine.CodeCompletion, CShellCore.CodeCompletion.CodeTextEditor.Completion, CShell.Modules.Editors.ViewModels.EditorViewModel.editorView, CShell.Modules.Editors.ViewModels.EditorViewModel.GetHighlighting(), CShell.Modules.Editors.ViewModels.EditorViewModel.IsDirty, CShellCore.CodeCompletion.CodeTextEditor.OpenFile(), CShell.Modules.Editors.ViewModels.EditorViewModel.originalText, CShell.Modules.Editors.ViewModels.EditorViewModel.path, CShell.Workspace.ScriptingEngine, CShell.Modules.Editors.ViewModels.EditorViewModel.textEditor, and CShell.Shell.Workspace.
Save()
override void CShell.Modules.Editors.ViewModels.EditorViewModel.Save () inline virtual
Reimplemented from CShell.Framework.Document.
References CShell.Modules.Editors.ViewModels.EditorViewModel.IsDirty, CShell.Framework.Services.Execute.OnUIThreadEx(), CShell.Modules.Editors.ViewModels.EditorViewModel.originalText, CShell.Modules.Editors.ViewModels.EditorViewModel.path, and CShell.Modules.Editors.ViewModels.EditorViewModel.textEditor.
SaveAs()
override void CShell.Modules.Editors.ViewModels.EditorViewModel.SaveAs (string newFile) inline virtual
Reimplemented from CShell.Framework.Document.
References CShell.Modules.Editors.ViewModels.EditorViewModel.fileName, CShell.Modules.Editors.ViewModels.EditorViewModel.IsDirty, CShell.Framework.Services.Execute.OnUIThreadEx(), CShell.Modules.Editors.ViewModels.EditorViewModel.originalText, CShell.Modules.Editors.ViewModels.EditorViewModel.textEditor, and CShell.Modules.Editors.ViewModels.EditorViewModel.Uri.
GetSelectionOrCurrentLine()
string CShell.Modules.Editors.ViewModels.EditorViewModel.GetSelectionOrCurrentLine () inline
References CShell.Modules.Editors.ViewModels.EditorViewModel.textEditor.
Referenced by CShell.Modules.Editors.Module.ExecuteSelection().
Equals()
override bool CShell.Modules.Editors.ViewModels.EditorViewModel.Equals (object obj) inline
References CShell.Modules.Editors.ViewModels.EditorViewModel.Uri.
GetHighlighting()
IHighlightingDefinition CShell.Modules.Editors.ViewModels.EditorViewModel.GetHighlighting (string fileExtension) inline private
Referenced by CShell.Modules.Editors.ViewModels.EditorViewModel.OnViewLoaded().
Undo()
void CShell.Modules.Editors.ViewModels.EditorViewModel.Undo () inline
Implements CShell.Framework.ITextDocument.
References CShell.Framework.Services.Execute.OnUIThreadEx(), and CShell.Modules.Editors.ViewModels.EditorViewModel.textEditor.
Redo()
void CShell.Modules.Editors.ViewModels.EditorViewModel.Redo () inline
Implements CShell.Framework.ITextDocument.
References CShell.Framework.Services.Execute.OnUIThreadEx(), and CShell.Modules.Editors.ViewModels.EditorViewModel.textEditor.
Cut()
void CShell.Modules.Editors.ViewModels.EditorViewModel.Cut () inline
Implements CShell.Framework.ITextDocument.
References CShell.Framework.Services.Execute.OnUIThreadEx(), and CShell.Modules.Editors.ViewModels.EditorViewModel.textEditor.
Copy()
void CShell.Modules.Editors.ViewModels.EditorViewModel.Copy () inline
Implements CShell.Framework.ITextDocument.
References CShell.Framework.Services.Execute.OnUIThreadEx(), and CShell.Modules.Editors.ViewModels.EditorViewModel.textEditor.
Paste()
void CShell.Modules.Editors.ViewModels.EditorViewModel.Paste () inline
Implements CShell.Framework.ITextDocument.
References CShell.Framework.Services.Execute.OnUIThreadEx(), and CShell.Modules.Editors.ViewModels.EditorViewModel.textEditor.
SelectAll()
void CShell.Modules.Editors.ViewModels.EditorViewModel.SelectAll () inline
Implements CShell.Framework.ITextDocument.
References CShell.Framework.Services.Execute.OnUIThreadEx(), and CShell.Modules.Editors.ViewModels.EditorViewModel.textEditor.
Select()
void CShell.Modules.Editors.ViewModels.EditorViewModel.Select (int start, int length) inline
Selects a section in the text.
Parameters
start The start index of the selection.
length The length of the selection.
Implements CShell.Framework.ITextDocument.
References CShell.Framework.Services.Execute.OnUIThreadEx(), and CShell.Modules.Editors.ViewModels.EditorViewModel.textEditor.
Comment()
void CShell.Modules.Editors.ViewModels.EditorViewModel.Comment () inline
Implements CShell.Framework.ITextDocument.
References CShell.Modules.Editors.Views.EditorView.Comment(), CShell.Modules.Editors.ViewModels.EditorViewModel.editorView, and CShell.Framework.Services.Execute.OnUIThreadEx().
Uncomment()
void CShell.Modules.Editors.ViewModels.EditorViewModel.Uncomment () inline
Implements CShell.Framework.ITextDocument.
References CShell.Modules.Editors.ViewModels.EditorViewModel.editorView, CShell.Framework.Services.Execute.OnUIThreadEx(), and CShell.Modules.Editors.Views.EditorView.Uncomment().
Member Data Documentation
originalText
string CShell.Modules.Editors.ViewModels.EditorViewModel.originalText private
Referenced by CShell.Modules.Editors.ViewModels.EditorViewModel.OnViewLoaded(), CShell.Modules.Editors.ViewModels.EditorViewModel.Save(), and CShell.Modules.Editors.ViewModels.EditorViewModel.SaveAs().
path
string CShell.Modules.Editors.ViewModels.EditorViewModel.path private
Referenced by CShell.Modules.Editors.ViewModels.EditorViewModel.OnViewLoaded(), CShell.Modules.Editors.ViewModels.EditorViewModel.Open(), and CShell.Modules.Editors.ViewModels.EditorViewModel.Save().
fileName
string CShell.Modules.Editors.ViewModels.EditorViewModel.fileName private
Referenced by CShell.Modules.Editors.ViewModels.EditorViewModel.Open(), and CShell.Modules.Editors.ViewModels.EditorViewModel.SaveAs().
isDirty
bool CShell.Modules.Editors.ViewModels.EditorViewModel.isDirty private
textEditor
CodeTextEditor CShell.Modules.Editors.ViewModels.EditorViewModel.textEditor private
Referenced by CShell.Modules.Editors.ViewModels.EditorViewModel.Copy(), CShell.Modules.Editors.ViewModels.EditorViewModel.Cut(), CShell.Modules.Editors.ViewModels.EditorViewModel.GetSelectionOrCurrentLine(), CShell.Modules.Editors.ViewModels.EditorViewModel.OnViewLoaded(), CShell.Modules.Editors.ViewModels.EditorViewModel.Paste(), CShell.Modules.Editors.ViewModels.EditorViewModel.Redo(), CShell.Modules.Editors.ViewModels.EditorViewModel.Save(), CShell.Modules.Editors.ViewModels.EditorViewModel.SaveAs(), CShell.Modules.Editors.ViewModels.EditorViewModel.Select(), CShell.Modules.Editors.ViewModels.EditorViewModel.SelectAll(), and CShell.Modules.Editors.ViewModels.EditorViewModel.Undo().
editorView
EditorView CShell.Modules.Editors.ViewModels.EditorViewModel.editorView private
Referenced by CShell.Modules.Editors.ViewModels.EditorViewModel.Comment(), CShell.Modules.Editors.ViewModels.EditorViewModel.OnViewLoaded(), and CShell.Modules.Editors.ViewModels.EditorViewModel.Uncomment().
Property Documentation
File
string CShell.Modules.Editors.ViewModels.EditorViewModel.File get
Uri
override Uri CShell.Modules.Editors.ViewModels.EditorViewModel.Uri get set
Referenced by CShell.Modules.Editors.ViewModels.EditorViewModel.CanClose(), CShell.Modules.Editors.ViewModels.EditorViewModel.Equals(), CShell.Modules.Editors.ViewModels.EditorViewModel.Open(), and CShell.Modules.Editors.ViewModels.EditorViewModel.SaveAs().
IsDirty
override bool CShell.Modules.Editors.ViewModels.EditorViewModel.IsDirty get set
Referenced by CShell.Modules.Editors.ViewModels.EditorViewModel.CanClose(), CShell.Modules.Editors.ViewModels.EditorViewModel.OnViewLoaded(), CShell.Modules.Editors.ViewModels.EditorViewModel.Save(), and CShell.Modules.Editors.ViewModels.EditorViewModel.SaveAs().
Text
string CShell.Modules.Editors.ViewModels.EditorViewModel.Text get set
Referenced by CShell.Modules.Editors.Module.ExecuteFile().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Editors/ViewModels/EditorViewModel.cs