Doc: IGLib EXTENDED: IG.Web.Forms.WSClientsForm Class Reference
IG.Web.Forms.WSClientsForm Class Reference
Form for parametric tests and other viewing operations performed on ANN models.
Public Member Functions
WSClientsForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
string _workingDirectory = Directory.GetCurrentDirectory()
WSClientFormsAboutWindow _aboutWindow
Properties
string WorkingDirectory [get, set]
Working directory of the outer form.
WSClientFormsAboutWindow AboutWindow [get]
Window that shows information about the software.
Private Member Functions
void NeuralParametricDemo_HelpEventHandlers (object sender, KeyEventArgs e)
void NeuralParametricDemo_KeyUp (object sender, KeyEventArgs e)
void tabControl_KeyUp (object sender, KeyEventArgs e)
void btnSavePrediction_Click (object sender, EventArgs e)
Saves image of the prediction control to a file that is chosen via a file dialog box.
void btnPrintPrediction_Click (object sender, EventArgs e)
Prints the image of the prediction control to a file that is chosen via a file dialog box.
void btnSaveParametricTest_Click (object sender, EventArgs e)
Saves image of the parametric test control to a file that is chosen via a file dialog box.
void btnPrintParametricTest_Click (object sender, EventArgs e)
Prints the image of the parametric test control to a file that is chosen via a file dialog box.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.TextBox tbInfoLine
System.Windows.Forms.TabControl tabControl
System.Windows.Forms.TabPage tpPrediction
System.Windows.Forms.TabPage tpParmTest
Forms.WSClient1Control neuralPredictionControl1
System.Windows.Forms.Button btnSavePrediction
System.Windows.Forms.Button btnPrintPrediction
System.Windows.Forms.TabPage tpAbout
WSClientFormsAboutForm wsClientFormsAboutForm1
Detailed Description
Form for parametric tests and other viewing operations performed on ANN models.
$A Igor Apr13;
Constructor & Destructor Documentation
WSClientsForm()
IG.Web.Forms.WSClientsForm.WSClientsForm () inline
References IG.Web.Forms.WSClientsForm.InitializeComponent().
Member Function Documentation
NeuralParametricDemo_HelpEventHandlers()
void IG.Web.Forms.WSClientsForm.NeuralParametricDemo_HelpEventHandlers (object sender, KeyEventArgs e) inline private
References IG.Web.Forms.WSClientsForm.AboutWindow, and IG.Web.Forms.WSClientFormsAboutWindow.ShowHelp().
Referenced by IG.Web.Forms.WSClientsForm.NeuralParametricDemo_KeyUp(), and IG.Web.Forms.WSClientsForm.tabControl_KeyUp().
NeuralParametricDemo_KeyUp()
void IG.Web.Forms.WSClientsForm.NeuralParametricDemo_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Web.Forms.WSClientsForm.NeuralParametricDemo_HelpEventHandlers().
Referenced by IG.Web.Forms.WSClientsForm.InitializeComponent().
tabControl_KeyUp()
void IG.Web.Forms.WSClientsForm.tabControl_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Web.Forms.WSClientsForm.NeuralParametricDemo_HelpEventHandlers().
Referenced by IG.Web.Forms.WSClientsForm.InitializeComponent().
btnSavePrediction_Click()
void IG.Web.Forms.WSClientsForm.btnSavePrediction_Click (object sender, EventArgs e) inline private
Saves image of the prediction control to a file that is chosen via a file dialog box.
References IG.Web.Forms.WSClientsForm.neuralPredictionControl1, IG.Forms.UtilForms.SaveControlFileDialogJpeg(), and IG.Web.Forms.WSClientsForm.WorkingDirectory.
Referenced by IG.Web.Forms.WSClientsForm.InitializeComponent().
btnPrintPrediction_Click()
void IG.Web.Forms.WSClientsForm.btnPrintPrediction_Click (object sender, EventArgs e) inline private
Prints the image of the prediction control to a file that is chosen via a file dialog box.
References IG.Web.Forms.WSClientsForm.neuralPredictionControl1, and IG.Forms.UtilForms.PrintControl().
Referenced by IG.Web.Forms.WSClientsForm.InitializeComponent().
btnSaveParametricTest_Click()
void IG.Web.Forms.WSClientsForm.btnSaveParametricTest_Click (object sender, EventArgs e) inline private
Saves image of the parametric test control to a file that is chosen via a file dialog box.
btnPrintParametricTest_Click()
void IG.Web.Forms.WSClientsForm.btnPrintParametricTest_Click (object sender, EventArgs e) inline private
Prints the image of the parametric test control to a file that is chosen via a file dialog box.
Dispose()
override void IG.Web.Forms.WSClientsForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Web.Forms.WSClientsForm.components.
InitializeComponent()
void IG.Web.Forms.WSClientsForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Web.Forms.WSClientsForm.btnPrintPrediction, IG.Web.Forms.WSClientsForm.btnPrintPrediction_Click(), IG.Web.Forms.WSClientsForm.btnSavePrediction, IG.Web.Forms.WSClientsForm.btnSavePrediction_Click(), IG.Web.Forms.WSClientsForm.NeuralParametricDemo_KeyUp(), IG.Web.Forms.WSClientsForm.neuralPredictionControl1, IG.Web.Forms.WSClientsForm.tabControl, IG.Web.Forms.WSClientsForm.tabControl_KeyUp(), IG.Web.Forms.WSClientsForm.tbInfoLine, IG.Web.Forms.WSClientsForm.tpAbout, IG.Web.Forms.WSClientsForm.tpParmTest, IG.Web.Forms.WSClientsForm.tpPrediction, and IG.Web.Forms.WSClientsForm.wsClientFormsAboutForm1.
Referenced by IG.Web.Forms.WSClientsForm.WSClientsForm().
Member Data Documentation
_workingDirectory
string IG.Web.Forms.WSClientsForm._workingDirectory = Directory.GetCurrentDirectory() protected
_aboutWindow
WSClientFormsAboutWindow IG.Web.Forms.WSClientsForm._aboutWindow protected
components
System.ComponentModel.IContainer IG.Web.Forms.WSClientsForm.components = null private
Required designer variable.
Referenced by IG.Web.Forms.WSClientsForm.Dispose().
tbInfoLine
System.Windows.Forms.TextBox IG.Web.Forms.WSClientsForm.tbInfoLine private
Referenced by IG.Web.Forms.WSClientsForm.InitializeComponent().
tabControl
System.Windows.Forms.TabControl IG.Web.Forms.WSClientsForm.tabControl private
Referenced by IG.Web.Forms.WSClientsForm.InitializeComponent().
tpPrediction
System.Windows.Forms.TabPage IG.Web.Forms.WSClientsForm.tpPrediction private
Referenced by IG.Web.Forms.WSClientsForm.InitializeComponent().
tpParmTest
System.Windows.Forms.TabPage IG.Web.Forms.WSClientsForm.tpParmTest private
Referenced by IG.Web.Forms.WSClientsForm.InitializeComponent().
neuralPredictionControl1
Forms.WSClient1Control IG.Web.Forms.WSClientsForm.neuralPredictionControl1 private
Referenced by IG.Web.Forms.WSClientsForm.btnPrintPrediction_Click(), IG.Web.Forms.WSClientsForm.btnSavePrediction_Click(), and IG.Web.Forms.WSClientsForm.InitializeComponent().
btnSavePrediction
System.Windows.Forms.Button IG.Web.Forms.WSClientsForm.btnSavePrediction private
Referenced by IG.Web.Forms.WSClientsForm.InitializeComponent().
btnPrintPrediction
System.Windows.Forms.Button IG.Web.Forms.WSClientsForm.btnPrintPrediction private
Referenced by IG.Web.Forms.WSClientsForm.InitializeComponent().
tpAbout
System.Windows.Forms.TabPage IG.Web.Forms.WSClientsForm.tpAbout private
Referenced by IG.Web.Forms.WSClientsForm.InitializeComponent().
wsClientFormsAboutForm1
WSClientFormsAboutForm IG.Web.Forms.WSClientsForm.wsClientFormsAboutForm1 private
Referenced by IG.Web.Forms.WSClientsForm.InitializeComponent().
Property Documentation
WorkingDirectory
string IG.Web.Forms.WSClientsForm.WorkingDirectory get set
Working directory of the outer form.
Referenced by IG.Web.Forms.WSClientsForm.btnSavePrediction_Click().
AboutWindow
WSClientFormsAboutWindow IG.Web.Forms.WSClientsForm.AboutWindow get
Window that shows information about the software.
Help is also accessible through that window.
Referenced by IG.Web.Forms.WSClientsForm.NeuralParametricDemo_HelpEventHandlers().
The documentation for this class was generated from the following files:
igtest/IGLibTestShell/WebServices/WebServiceForms/Applications/WSClientsForm.cs
igtest/IGLibTestShell/WebServices/WebServiceForms/Applications/WSClientsForm.Designer.cs