Doc: IGLib EXTENDED: NUnit.Samples.Money.MoneyBag Class Reference
NUnit.Samples.Money.MoneyBag Class Reference
A MoneyBag defers exchange rate conversions.
Public Member Functions
MoneyBag (Money[] bag)
MoneyBag (Money m1, Money m2)
MoneyBag (Money m, MoneyBag bag)
MoneyBag (MoneyBag m1, MoneyBag m2)
IMoney Add (IMoney m)
Adds a money to this money.
IMoney AddMoney (Money m)
Adds a simple Money to this money. This is a helper method for implementing double dispatch.
IMoney AddMoneyBag (MoneyBag s)
Adds a MoneyBag to this money. This is a helper method for implementing double dispatch.
override bool Equals (Object anObject)
override int GetHashCode ()
IMoney Multiply (int factor)
Multiplies a money by the given factor.
IMoney Negate ()
Negates this money.
IMoney Subtract (IMoney m)
Subtracts a money from this money.
override String ToString ()
Properties
bool IsZero [get]
Properties inherited from NUnit.Samples.Money.IMoney
bool IsZero [get]
True if this money is zero.
Private Member Functions
MoneyBag ()
void AppendBag (MoneyBag aBag)
void AppendMoney (Money aMoney)
bool Contains (Money aMoney)
Money FindMoney (String currency)
IMoney Simplify ()
Private Attributes
ArrayList fMonies = new ArrayList(5)
Detailed Description
A MoneyBag defers exchange rate conversions.
For example adding 12 Swiss Francs to 14 US Dollars is represented as a bag containing the two Monies 12 CHF and 14 USD. Adding another 10 Swiss francs gives a bag with 22 CHF and 14 USD. Due to the deferred exchange rate conversion we can later value a MoneyBag with different exchange rates.
A MoneyBag is represented as a list of Monies and provides different constructors to create a MoneyBag.
Constructor & Destructor Documentation
MoneyBag() [1/5]
NUnit.Samples.Money.MoneyBag.MoneyBag () inline private
Referenced by NUnit.Samples.Money.MoneyBag.AddMoney(), NUnit.Samples.Money.MoneyBag.AddMoneyBag(), NUnit.Samples.Money.MoneyBag.Equals(), NUnit.Samples.Money.MoneyBag.Multiply(), and NUnit.Samples.Money.MoneyBag.Negate().
MoneyBag() [2/5]
NUnit.Samples.Money.MoneyBag.MoneyBag (Money[] bag) inline
References NUnit.Samples.Money.MoneyBag.AppendMoney(), and NUnit.Samples.Money.MoneyBag.IsZero.
MoneyBag() [3/5]
NUnit.Samples.Money.MoneyBag.MoneyBag (Money m1, Money m2) inline
References NUnit.Samples.Money.MoneyBag.AppendMoney().
MoneyBag() [4/5]
NUnit.Samples.Money.MoneyBag.MoneyBag (Money m, MoneyBag bag) inline
References NUnit.Samples.Money.MoneyBag.AppendBag(), and NUnit.Samples.Money.MoneyBag.AppendMoney().
MoneyBag() [5/5]
NUnit.Samples.Money.MoneyBag.MoneyBag (MoneyBag m1, MoneyBag m2) inline
References NUnit.Samples.Money.MoneyBag.AppendBag().
Member Function Documentation
Add()
IMoney NUnit.Samples.Money.MoneyBag.Add (IMoney m) inline
Adds a money to this money.
Implements NUnit.Samples.Money.IMoney.
Referenced by NUnit.Samples.Money.MoneyTest.BagSimpleAdd(), NUnit.Samples.Money.MoneyTest.BagSumAdd(), and NUnit.Samples.Money.MoneyBag.Subtract().
AddMoney()
IMoney NUnit.Samples.Money.MoneyBag.AddMoney (Money m) inline
Adds a simple Money to this money. This is a helper method for implementing double dispatch.
Implements NUnit.Samples.Money.IMoney.
References NUnit.Samples.Money.MoneyBag.MoneyBag().
AddMoneyBag()
IMoney NUnit.Samples.Money.MoneyBag.AddMoneyBag (MoneyBag s) inline
Adds a MoneyBag to this money. This is a helper method for implementing double dispatch.
Implements NUnit.Samples.Money.IMoney.
References NUnit.Samples.Money.MoneyBag.MoneyBag().
AppendBag()
void NUnit.Samples.Money.MoneyBag.AppendBag (MoneyBag aBag) inline private
References NUnit.Samples.Money.MoneyBag.AppendMoney().
Referenced by NUnit.Samples.Money.MoneyBag.MoneyBag().
AppendMoney()
void NUnit.Samples.Money.MoneyBag.AppendMoney (Money aMoney) inline private
References NUnit.Samples.Money.IMoney.Add(), NUnit.Samples.Money.Money.Currency, NUnit.Samples.Money.MoneyBag.FindMoney(), NUnit.Samples.Money.MoneyBag.fMonies, and NUnit.Samples.Money.IMoney.IsZero.
Referenced by NUnit.Samples.Money.MoneyBag.AppendBag(), NUnit.Samples.Money.MoneyBag.MoneyBag(), and NUnit.Samples.Money.MoneyBag.Multiply().
Contains()
bool NUnit.Samples.Money.MoneyBag.Contains (Money aMoney) inline private
References NUnit.Samples.Money.Money.Amount, NUnit.Samples.Money.Money.Currency, and NUnit.Samples.Money.MoneyBag.FindMoney().
Equals()
override bool NUnit.Samples.Money.MoneyBag.Equals (Object anObject) inline
References NUnit.Samples.Money.MoneyBag.fMonies, NUnit.Samples.Money.MoneyBag.IsZero, and NUnit.Samples.Money.MoneyBag.MoneyBag().
Referenced by NUnit.Samples.Money.MoneyTest.MoneyBagEquals().
FindMoney()
Money NUnit.Samples.Money.MoneyBag.FindMoney (String currency) inline private
References NUnit.Samples.Money.MoneyBag.fMonies.
Referenced by NUnit.Samples.Money.MoneyBag.AppendMoney(), and NUnit.Samples.Money.MoneyBag.Contains().
GetHashCode()
override int NUnit.Samples.Money.MoneyBag.GetHashCode () inline
References NUnit.Samples.Money.MoneyBag.fMonies.
Referenced by NUnit.Samples.Money.MoneyTest.MoneyBagHash().
Multiply()
IMoney NUnit.Samples.Money.MoneyBag.Multiply (int factor) inline
Multiplies a money by the given factor.
Implements NUnit.Samples.Money.IMoney.
References NUnit.Samples.Money.MoneyBag.AppendMoney(), NUnit.Samples.Money.MoneyBag.fMonies, and NUnit.Samples.Money.MoneyBag.MoneyBag().
Referenced by NUnit.Samples.Money.MoneyTest.BagMultiply().
Negate()
IMoney NUnit.Samples.Money.MoneyBag.Negate () inline
Negates this money.
Implements NUnit.Samples.Money.IMoney.
References NUnit.Samples.Money.MoneyBag.fMonies, and NUnit.Samples.Money.MoneyBag.MoneyBag().
Referenced by NUnit.Samples.Money.MoneyTest.BagNegate().
Simplify()
IMoney NUnit.Samples.Money.MoneyBag.Simplify () inline private
References NUnit.Samples.Money.MoneyBag.fMonies.
Subtract()
IMoney NUnit.Samples.Money.MoneyBag.Subtract (IMoney m) inline
Subtracts a money from this money.
Implements NUnit.Samples.Money.IMoney.
References NUnit.Samples.Money.MoneyBag.Add().
Referenced by NUnit.Samples.Money.MoneyTest.BagSubtract(), NUnit.Samples.Money.MoneyTest.IsZero(), NUnit.Samples.Money.MoneyTest.Normalize2(), and NUnit.Samples.Money.MoneyTest.Normalize3().
ToString()
override String NUnit.Samples.Money.MoneyBag.ToString () inline
References NUnit.Samples.Money.MoneyBag.fMonies.
Member Data Documentation
fMonies
ArrayList NUnit.Samples.Money.MoneyBag.fMonies = new ArrayList(5) private
Referenced by NUnit.Samples.Money.MoneyBag.AppendMoney(), NUnit.Samples.Money.MoneyBag.Equals(), NUnit.Samples.Money.MoneyBag.FindMoney(), NUnit.Samples.Money.MoneyBag.GetHashCode(), NUnit.Samples.Money.MoneyBag.Multiply(), NUnit.Samples.Money.MoneyBag.Negate(), NUnit.Samples.Money.MoneyBag.Simplify(), and NUnit.Samples.Money.MoneyBag.ToString().
Property Documentation
IsZero
bool NUnit.Samples.Money.MoneyBag.IsZero get
Referenced by NUnit.Samples.Money.MoneyBag.Equals(), and NUnit.Samples.Money.MoneyBag.MoneyBag().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1/samples/csharp/money/MoneyBag.cs