Doc: IGLib EXTENDED: NUnit.ConsoleRunner.Program Class Reference
NUnit.ConsoleRunner.Program Class Reference
This class provides the entry point for the console runner.
Static Public Member Functions
static int Main (string[] args)
Properties
static ExtendedTextWriter OutWriter [get]
Static Private Member Functions
static void WriteHeader ()
static void WriteHelpText ()
Static Private Attributes
static ConsoleOptions Options = new ConsoleOptions(new DefaultOptionsProvider())
static ExtendedTextWriter _outWriter
Detailed Description
This class provides the entry point for the console runner.
Member Function Documentation
Main()
static int NUnit.ConsoleRunner.Program.Main (string[] args) inline static
References NUnit.Engine.TestEngineActivator.CreateInstance(), NUnit.Common.CommandLineOptions.ErrorMessages, NUnit.ConsoleRunner.ConsoleRunner.Execute(), NUnit.Common.CommandLineOptions.InputFiles, NUnit.Engine.ITestEngine.InternalTraceLevel, NUnit.Common.CommandLineOptions.InternalTraceLevel, NUnit.ConsoleRunner.ConsoleRunner.INVALID_ARG, NUnit.ConsoleRunner.ConsoleRunner.INVALID_ASSEMBLY, NUnit.Common.CommandLineOptions.NoHeader, NUnit.ConsoleRunner.ConsoleRunner.OK, NUnit.ConsoleRunner.Program.Options, NUnit.ConsoleRunner.Program.OutWriter, NUnit.Common.CommandLineOptions.ShowHelp, NUnit.Common.CommandLineOptions.ShowVersion, NUnit.ConsoleRunner.ConsoleRunner.UNEXPECTED_ERROR, NUnit.Common.CommandLineOptions.Validate(), NUnit.Common.CommandLineOptions.WaitBeforeExit, NUnit.Engine.ITestEngine.WorkDirectory, NUnit.Common.CommandLineOptions.WorkDirectory, NUnit.ConsoleRunner.Program.WriteHeader(), NUnit.ConsoleRunner.Program.WriteHelpText(), and NUnit.Common.ExtendedTextWriter.WriteLine().
WriteHeader()
static void NUnit.ConsoleRunner.Program.WriteHeader () inline static private
References NUnit.ConsoleRunner.Program.OutWriter, and NUnit.Common.ExtendedTextWriter.WriteLine().
Referenced by NUnit.ConsoleRunner.Program.Main().
WriteHelpText()
static void NUnit.ConsoleRunner.Program.WriteHelpText () inline static private
References NUnit.ConsoleRunner.Program.Options, NUnit.ConsoleRunner.Program.OutWriter, and NUnit.Common.ExtendedTextWriter.WriteLine().
Referenced by NUnit.ConsoleRunner.Program.Main().
Member Data Documentation
Options
ConsoleOptions NUnit.ConsoleRunner.Program.Options = new ConsoleOptions(new DefaultOptionsProvider()) static private
Referenced by NUnit.ConsoleRunner.Program.Main(), and NUnit.ConsoleRunner.Program.WriteHelpText().
_outWriter
ExtendedTextWriter NUnit.ConsoleRunner.Program._outWriter static private
Property Documentation
OutWriter
ExtendedTextWriter NUnit.ConsoleRunner.Program.OutWriter static get private
Referenced by NUnit.ConsoleRunner.Program.Main(), NUnit.ConsoleRunner.Program.WriteHeader(), and NUnit.ConsoleRunner.Program.WriteHelpText().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitConsole/nunit3-console/Program.cs