Doc: IGLib EXTENDED: NUnit.Engine.Services.ServiceManager Class Reference
NUnit.Engine.Services.ServiceManager Class Reference
ServiceManager handles access to all services - global facilities shared by all instances of TestEngine.
Public Member Functions
IService GetService (Type serviceType)
void AddService (IService service)
void StartServices ()
void StopServices ()
void ClearServices ()
void Dispose ()
Protected Member Functions
virtual void Dispose (bool disposing)
Properties
bool ServicesInitialized [get, private set]
Private Attributes
List< IService > _services = new List<IService>()
Dictionary< Type, IService > _serviceIndex = new Dictionary<Type, IService>()
bool _disposed = false
Static Private Attributes
static Logger log = InternalTrace.GetLogger(typeof(ServiceManager))
Detailed Description
ServiceManager handles access to all services - global facilities shared by all instances of TestEngine.
Member Function Documentation
GetService()
IService NUnit.Engine.Services.ServiceManager.GetService (Type serviceType) inline
References NUnit.Engine.Services.ServiceManager._serviceIndex, NUnit.Engine.Services.ServiceManager._services, and NUnit.Engine.Services.ServiceManager.log.
Referenced by NUnit.Engine.Services.Tests.ServiceManagerTests.AccessServiceByClass(), NUnit.Engine.Services.Tests.ServiceManagerTests.AccessServiceByInterface(), NUnit.Engine.ServiceContext.GetService(), NUnit.Engine.ServiceContext.GetService< T >(), and NUnit.Engine.Services.Tests.ServiceManagerTests.InitializeServices().
AddService()
void NUnit.Engine.Services.ServiceManager.AddService (IService service) inline
References NUnit.Engine.Services.ServiceManager._services, and NUnit.Engine.Services.ServiceManager.log.
Referenced by NUnit.Engine.ServiceContext.Add(), and NUnit.Engine.Services.Tests.ServiceManagerTests.SetUp().
StartServices()
void NUnit.Engine.Services.ServiceManager.StartServices () inline
References NUnit.Engine.Services.ServiceManager._services, NUnit.Engine.Services.ServiceManager.log, NUnit.Engine.Services.ServiceManager.ServicesInitialized, NUnit.Engine.IService.StartService(), and NUnit.Engine.IService.Status.
Referenced by NUnit.Engine.Services.Tests.ServiceManagerTests.InitializationFailure(), NUnit.Engine.TestEngine.Initialize(), and NUnit.Engine.Services.Tests.ServiceManagerTests.InitializeServices().
StopServices()
void NUnit.Engine.Services.ServiceManager.StopServices () inline
References NUnit.Engine.Services.ServiceManager._services, NUnit.Engine.Services.ServiceManager.log, NUnit.Engine.IService.Status, and NUnit.Engine.IService.StopService().
Referenced by NUnit.Engine.TestEngine.Dispose(), and NUnit.Engine.Services.ServiceManager.Dispose().
ClearServices()
void NUnit.Engine.Services.ServiceManager.ClearServices () inline
References NUnit.Engine.Services.ServiceManager._services, and NUnit.Engine.Services.ServiceManager.log.
Dispose() [1/2]
void NUnit.Engine.Services.ServiceManager.Dispose () inline
Referenced by NUnit.Engine.TestEngine.Dispose().
Dispose() [2/2]
virtual void NUnit.Engine.Services.ServiceManager.Dispose (bool disposing) inline protected virtual
References NUnit.Engine.Services.ServiceManager._disposed, NUnit.Engine.Services.ServiceManager._services, and NUnit.Engine.Services.ServiceManager.StopServices().
Member Data Documentation
_services
List<IService> NUnit.Engine.Services.ServiceManager._services = new List<IService>() private
Referenced by NUnit.Engine.Services.ServiceManager.AddService(), NUnit.Engine.Services.ServiceManager.ClearServices(), NUnit.Engine.Services.ServiceManager.Dispose(), NUnit.Engine.Services.ServiceManager.GetService(), NUnit.Engine.Services.ServiceManager.StartServices(), and NUnit.Engine.Services.ServiceManager.StopServices().
_serviceIndex
Dictionary<Type, IService> NUnit.Engine.Services.ServiceManager._serviceIndex = new Dictionary<Type, IService>() private
Referenced by NUnit.Engine.Services.ServiceManager.GetService().
log
Logger NUnit.Engine.Services.ServiceManager.log = InternalTrace.GetLogger(typeof(ServiceManager)) static private
Referenced by NUnit.Engine.Services.ServiceManager.AddService(), NUnit.Engine.Services.ServiceManager.ClearServices(), NUnit.Engine.Services.ServiceManager.GetService(), NUnit.Engine.Services.ServiceManager.StartServices(), and NUnit.Engine.Services.ServiceManager.StopServices().
_disposed
bool NUnit.Engine.Services.ServiceManager._disposed = false private
Referenced by NUnit.Engine.Services.ServiceManager.Dispose().
Property Documentation
ServicesInitialized
bool NUnit.Engine.Services.ServiceManager.ServicesInitialized get private set
Referenced by NUnit.Engine.TestEngine.GetRunner(), and NUnit.Engine.Services.ServiceManager.StartServices().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Services/ServiceManager.cs