Doc: IGLib EXTENDED: AForge.Neuro.ThresholdFunction Class Reference
AForge.Neuro.ThresholdFunction Class Reference
Threshold activation function
Public Member Functions
ThresholdFunction ()
Initializes a new instance of the ThresholdFunction class
double Function (double x)
Calculates function value
double Derivative (double x)
Not supported
double Derivative2 (double y)
Not supported
ThresholdFunction ()
Initializes a new instance of the ThresholdFunction class
double Function (double x)
Calculates function value
double Derivative (double x)
Not supported
double Derivative2 (double y)
Not supported
ThresholdFunction ()
Initializes a new instance of the ThresholdFunction class.
double Function (double x)
Calculates function value.
double Derivative (double x)
Calculates function derivative (not supported).
double Derivative2 (double y)
Calculates function derivative (not supported).
Detailed Description
Threshold activation function
Threshold activation function.
The class represents threshold activation function with the next expression:
f(x) = 1, if x >= 0, otherwise 0
Output range of the function: [0, 1]
Functions graph:
The class represents threshold activation function with the next expression:
f(x) = 1, if x >= 0, otherwise 0
Output range of the function: [0, 1].
Functions graph:
Constructor & Destructor Documentation
ThresholdFunction() [1/3]
AForge.Neuro.ThresholdFunction.ThresholdFunction () inline
Initializes a new instance of the ThresholdFunction class
ThresholdFunction() [2/3]
AForge.Neuro.ThresholdFunction.ThresholdFunction () inline
Initializes a new instance of the ThresholdFunction class
ThresholdFunction() [3/3]
AForge.Neuro.ThresholdFunction.ThresholdFunction () inline
Initializes a new instance of the ThresholdFunction class.
Member Function Documentation
Function() [1/3]
double AForge.Neuro.ThresholdFunction.Function (double x) inline
Calculates function value
Parameters
x Function input value
Returns
Function output value, f(x)
The method calculates function value at point x.
Implements AForge.Neuro.IActivationFunction.
Referenced by AForge.Neuro.ThresholdFunction.Derivative().
Derivative() [1/3]
double AForge.Neuro.ThresholdFunction.Derivative (double x) inline
Not supported
Parameters
x Input value
Returns
Always returns 0
The method is not supported, because it is not possible to calculate derivative of the function.
Implements AForge.Neuro.IActivationFunction.
References AForge.Neuro.ThresholdFunction.Function().
Derivative2() [1/3]
double AForge.Neuro.ThresholdFunction.Derivative2 (double y) inline
Not supported
Parameters
y Input value
Returns
Always returns 0
The method is not supported, because it is not possible to calculate derivative of the function.
Implements AForge.Neuro.IActivationFunction.
Function() [2/3]
double AForge.Neuro.ThresholdFunction.Function (double x) inline
Calculates function value
Parameters
x Function input value
Returns
Function output value, f(x)
The method calculates function value at point x.
Implements AForge.Neuro.IActivationFunction.
Derivative() [2/3]
double AForge.Neuro.ThresholdFunction.Derivative (double x) inline
Not supported
Parameters
x Input value
Returns
Always returns 0
The method is not supported, because it is not possible to calculate derivative of the function.
Implements AForge.Neuro.IActivationFunction.
References AForge.Neuro.ThresholdFunction.Function().
Derivative2() [2/3]
double AForge.Neuro.ThresholdFunction.Derivative2 (double y) inline
Not supported
Parameters
y Input value
Returns
Always returns 0
The method is not supported, because it is not possible to calculate derivative of the function.
Implements AForge.Neuro.IActivationFunction.
Function() [3/3]
double AForge.Neuro.ThresholdFunction.Function (double x) inline
Calculates function value.
Parameters
x Function input value.
Returns
Function output value, f(x).
The method calculates function value at point x .
Implements AForge.Neuro.IActivationFunction.
Derivative() [3/3]
double AForge.Neuro.ThresholdFunction.Derivative (double x) inline
Calculates function derivative (not supported).
Parameters
x Input value.
Returns
Always returns 0.
<note>The method is not supported, because it is not possible to calculate derivative of the function.</note>
Implements AForge.Neuro.IActivationFunction.
Derivative2() [3/3]
double AForge.Neuro.ThresholdFunction.Derivative2 (double y) inline
Calculates function derivative (not supported).
Parameters
y Input value.
Returns
Always returns 0.
<note>The method is not supported, because it is not possible to calculate derivative of the function.</note>
Implements AForge.Neuro.IActivationFunction.
The documentation for this class was generated from the following file:
shelldev/lib/external/neuralnetworks/neuro_src/Sources/Backup/Neuro/Activation Functions/ThresholdFunction.cs