Doc: IGLib EXTENDED: IG.Forms.ScalarFunctionEvaluatorControl Class Reference
IG.Forms.ScalarFunctionEvaluatorControl Class Reference
Control for test evaluation of scalar functions.
Public Member Functions
ScalarFunctionEvaluatorControl (IScalarFunction function, string[] parameterNames, double[] parameterValues)
Constructs the control, with ANN-based model specified.
DataGridView GetGridControl ()
Returns the DataGridView control that is used for setting values of the input parameters.
void InitializeCells ()
Initializes contents of the DataGridView.
void DataToGrid ()
Copies internal data to grid view.
void DataFromGrid ()
Copies internal data to grid view.
void ClearCells ()
Clears contents of all DataGridView cells.
void ClearDataGrid ()
Removes all the data from the DataGridView.
void ResetToDefault ()
Resets cells to default values.
void ShowContextMenuControl (object sender, MouseEventArgs e)
string CreateFunctionSummary ()
Returns a string that contains a summary of the evaluated function.
ScalarFunctionEvaluatorControl (IScalarFunction function, string[] parameterNames, double[] parameterValues)
Constructs the control, with ANN-based model specified.
DataGridView GetGridControl ()
Returns the DataGridView control that is used for setting values of the input parameters.
void InitializeCells ()
Initializes contents of the DataGridView.
void DataToGrid ()
Copies internal data to grid view.
void DataFromGrid ()
Copies internal data to grid view.
void ClearCells ()
Clears contents of all DataGridView cells.
void ClearDataGrid ()
Removes all the data from the DataGridView.
void ResetToDefault ()
Resets cells to default values.
void ShowContextMenuControl (object sender, MouseEventArgs e)
string CreateFunctionSummary ()
Returns a string that contains a summary of the evaluated function.
ScalarFunctionEvaluatorControl (IScalarFunction function, string[] parameterNames, double[] parameterValues)
Constructs the control, with ANN-based model specified.
DataGridView GetGridControl ()
Returns the DataGridView control that is used for setting values of the input parameters.
void InitializeCells ()
Initializes contents of the DataGridView.
void DataToGrid ()
Copies internal data to grid view.
void DataFromGrid ()
Copies internal data to grid view.
void ClearCells ()
Clears contents of all DataGridView cells.
void ClearDataGrid ()
Removes all the data from the DataGridView.
void ResetToDefault ()
Resets cells to default values.
void ShowContextMenuControl (object sender, MouseEventArgs e)
string CreateFunctionSummary ()
Returns a string that contains a summary of the evaluated function.
ScalarFunctionEvaluatorControl (IScalarFunction function, string[] parameterNames, double[] parameterValues)
Constructs the control, with ANN-based model specified.
DataGridView GetGridControl ()
Returns the DataGridView control that is used for setting values of the input parameters.
void InitializeCells ()
Initializes contents of the DataGridView.
void DataToGrid ()
Copies internal data to grid view.
void DataFromGrid ()
Copies internal data to grid view.
void ClearCells ()
Clears contents of all DataGridView cells.
void ClearDataGrid ()
Removes all the data from the DataGridView.
void ResetToDefault ()
Resets cells to default values.
void ShowContextMenuControl (object sender, MouseEventArgs e)
string CreateFunctionSummary ()
Returns a string that contains a summary of the evaluated function.
Protected Member Functions
void SetDefaultParameterNames (int dim, string baseName="x")
Sets parameter names to default.
void SetDefaultParameterValues (int dim, double defaultValue=0)
Sets parameter values to default.
void CalculateFunctionValue ()
override void Dispose (bool disposing)
Clean up any resources being used.
void SetDefaultParameterNames (int dim, string baseName="x")
Sets parameter names to default.
void SetDefaultParameterValues (int dim, double defaultValue=0)
Sets parameter values to default.
void CalculateFunctionValue ()
override void Dispose (bool disposing)
Clean up any resources being used.
void SetDefaultParameterNames (int dim, string baseName="x")
Sets parameter names to default.
void SetDefaultParameterValues (int dim, double defaultValue=0)
Sets parameter values to default.
void CalculateFunctionValue ()
override void Dispose (bool disposing)
Clean up any resources being used.
void SetDefaultParameterNames (int dim, string baseName="x")
Sets parameter names to default.
void SetDefaultParameterValues (int dim, double defaultValue=0)
Sets parameter values to default.
void CalculateFunctionValue ()
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
string _functionDefinition = null
int _colNumValue = 2
bool _gridEvents = true
Properties
IScalarFunction ScalarFunction [get, set]
Scalar function that is evaluated by the current control.
IVectorFunction VectorFunction [get, set]
Vector function whose values are calculated.
bool VisibleTreatAsVector [get, set]
Whether the check box for treating scalar function as a vector will be visible or not.
bool TreatScalarAsVectorFunction [get, set]
If true then scalar function is converted to a vector funciton when set.
string FunctionDefinition [get, set]
Function definition that can be assigned by creator of the window. This will be used when the verification button is pressed.
string[] ParameterNames [get, set]
Names of function parameters, shown in data grid.
double[] ParameterValues [get, set]
Valuse of parameters, shown in data grid.
int NumParameters [get, set]
Gets or sets number of parameters.
int ColNumValue [get, protected set]
Number of DataGrid Column that contains the value.
bool ImmediateCalculation [get, set]
Private Member Functions
void ScalarFunctionEvaluatorControl_MouseClick (object sender, MouseEventArgs e)
void dGridInputParam_MouseClick (object sender, MouseEventArgs e)
void btnResetDefault_Click (object sender, EventArgs e)
void btnCalculate_Click (object sender, EventArgs e)
void dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e)
void resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e)
void btnShowDefinition_Click (object sender, EventArgs e)
void chkImmediateCalculation_CheckedChanged (object sender, EventArgs e)
void chkTreatAsVector_CheckedChanged (object sender, EventArgs e)
void btnIdentifyThread_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void ScalarFunctionEvaluatorControl_MouseClick (object sender, MouseEventArgs e)
void dGridInputParam_MouseClick (object sender, MouseEventArgs e)
void btnResetDefault_Click (object sender, EventArgs e)
void btnCalculate_Click (object sender, EventArgs e)
void dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e)
void resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e)
void btnShowDefinition_Click (object sender, EventArgs e)
void chkImmediateCalculation_CheckedChanged (object sender, EventArgs e)
void chkTreatAsVector_CheckedChanged (object sender, EventArgs e)
void btnIdentifyThread_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void ScalarFunctionEvaluatorControl_MouseClick (object sender, MouseEventArgs e)
void dGridInputParam_MouseClick (object sender, MouseEventArgs e)
void btnResetDefault_Click (object sender, EventArgs e)
void btnCalculate_Click (object sender, EventArgs e)
void dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e)
void resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e)
void btnShowDefinition_Click (object sender, EventArgs e)
void chkImmediateCalculation_CheckedChanged (object sender, EventArgs e)
void chkTreatAsVector_CheckedChanged (object sender, EventArgs e)
void btnIdentifyThread_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void ScalarFunctionEvaluatorControl_MouseClick (object sender, MouseEventArgs e)
void dGridInputParam_MouseClick (object sender, MouseEventArgs e)
void btnResetDefault_Click (object sender, EventArgs e)
void btnCalculate_Click (object sender, EventArgs e)
void dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e)
void resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e)
void btnShowDefinition_Click (object sender, EventArgs e)
void chkImmediateCalculation_CheckedChanged (object sender, EventArgs e)
void chkTreatAsVector_CheckedChanged (object sender, EventArgs e)
void btnIdentifyThread_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
IScalarFunction _scalarFunction
IVectorFunction _vectorFunction
bool _visibleTreatAsVector = true
bool _treatAsVectorFunction = false
string[] _parameterNames
double[] _parameterValues
List< double > _vectorFunctionValues = new List<double>()
bool _immediateCalculation = true
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.DataGridView dGridInputParam
System.Windows.Forms.Button btnResetDefault
System.Windows.Forms.Button btnCalculate
System.Windows.Forms.ContextMenuStrip contextMenuControl
System.Windows.Forms.ToolStripMenuItem resetToDefaultToolStripMenuItem
System.Windows.Forms.Label label1
System.Windows.Forms.TextBox txtValue
System.Windows.Forms.Label lblParameters
System.Windows.Forms.Button btnShowDefinition
System.Windows.Forms.CheckBox chkImmediateCalculation
System.Windows.Forms.CheckBox chkTreatAsVector
System.Windows.Forms.DataGridViewTextBoxColumn columnID
System.Windows.Forms.DataGridViewTextBoxColumn columnName
System.Windows.Forms.DataGridViewTextBoxColumn columnValue
System.Windows.Forms.Button btnIdentifyThread
Detailed Description
Control for test evaluation of scalar functions.
User can define input parameter values and evaluate the function at those parameters.
$A Igor Jul14;
Constructor & Destructor Documentation
ScalarFunctionEvaluatorControl() [1/4]
IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunctionEvaluatorControl (IScalarFunction function, string[] parameterNames, double[] parameterValues) inline
Constructs the control, with ANN-based model specified.
Parameters
neuralModel ANN-based model, containing data definitions and trained neural network.
References IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames, IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues, and IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunction.
ScalarFunctionEvaluatorControl() [2/4]
IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunctionEvaluatorControl (IScalarFunction function, string[] parameterNames, double[] parameterValues) inline
Constructs the control, with ANN-based model specified.
Parameters
neuralModel ANN-based model, containing data definitions and trained neural network.
References IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames, IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues, and IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunction.
ScalarFunctionEvaluatorControl() [3/4]
IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunctionEvaluatorControl (IScalarFunction function, string[] parameterNames, double[] parameterValues) inline
Constructs the control, with ANN-based model specified.
Parameters
neuralModel ANN-based model, containing data definitions and trained neural network.
References IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames, IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues, and IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunction.
ScalarFunctionEvaluatorControl() [4/4]
IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunctionEvaluatorControl (IScalarFunction function, string[] parameterNames, double[] parameterValues) inline
Constructs the control, with ANN-based model specified.
Parameters
neuralModel ANN-based model, containing data definitions and trained neural network.
References IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames, IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues, and IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunction.
Member Function Documentation
SetDefaultParameterNames() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.SetDefaultParameterNames (int dim, string baseName = "x") inline protected
Sets parameter names to default.
Parameters
dim Number of parameters.
baseName Optiional base name for parameters.
References IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames.
SetDefaultParameterValues() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.SetDefaultParameterValues (int dim, double defaultValue = 0) inline protected
Sets parameter values to default.
Parameters
dim Number of parameters.
defaultValue Optional default value, if not specified then 0.
References IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue(), IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation, and IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues.
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.btnResetDefault_Click(), and IG.Forms.ScalarFunctionEvaluatorControl.resetToDefaultToolStripMenuItem_Click().
GetGridControl() [1/4]
DataGridView IG.Forms.ScalarFunctionEvaluatorControl.GetGridControl () inline
Returns the DataGridView control that is used for setting values of the input parameters.
Returns
References IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam.
InitializeCells() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.InitializeCells () inline
Initializes contents of the DataGridView.
References IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, IG.Forms.ScalarFunctionEvaluatorControl.NumParameters, IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames, and IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues.
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.ResetToDefault().
DataToGrid() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.DataToGrid () inline
Copies internal data to grid view.
References IG.Forms.ScalarFunctionEvaluatorControl._gridEvents, IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames, and IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues.
DataFromGrid() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.DataFromGrid () inline
Copies internal data to grid view.
References IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues, and IG.Lib.UtilStr.ToDouble().
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue(), and IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam_CellValueChanged().
ClearCells() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.ClearCells () inline
Clears contents of all DataGridView cells.
References IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, and IG.Forms.ScalarFunctionEvaluatorControl.NumParameters.
ClearDataGrid() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.ClearDataGrid () inline
Removes all the data from the DataGridView.
References IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam.
ResetToDefault() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.ResetToDefault () inline
Resets cells to default values.
References IG.Forms.ScalarFunctionEvaluatorControl.ColNumValue, IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, IG.Forms.ScalarFunctionEvaluatorControl.InitializeCells(), and IG.Forms.ScalarFunctionEvaluatorControl.NumParameters.
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.resetToDefaultToolStripMenuItem_Click().
ShowContextMenuControl() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.ShowContextMenuControl (object sender, MouseEventArgs e) inline
References IG.Forms.ScalarFunctionEvaluatorControl.contextMenuControl.
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam_MouseClick(), and IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunctionEvaluatorControl_MouseClick().
ScalarFunctionEvaluatorControl_MouseClick() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunctionEvaluatorControl_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.ShowContextMenuControl().
dGridInputParam_MouseClick() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.ShowContextMenuControl().
btnResetDefault_Click() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.btnResetDefault_Click (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.NumParameters, and IG.Forms.ScalarFunctionEvaluatorControl.SetDefaultParameterValues().
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
CalculateFunctionValue() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue () inline protected
References IG.Forms.ScalarFunctionEvaluatorControl._vectorFunctionValues, IG.Forms.ScalarFunctionEvaluatorControl.DataFromGrid(), IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues, IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunction, IG.Num.VectorBase.ToString(), IG.Forms.ScalarFunctionEvaluatorControl.txtValue, IG.Num.IScalarFunctionUntransformed.Value(), IG.Num.IVectorFunction.Value(), and IG.Forms.ScalarFunctionEvaluatorControl.VectorFunction.
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.btnCalculate_Click(), IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam_CellValueChanged(), and IG.Forms.ScalarFunctionEvaluatorControl.SetDefaultParameterValues().
btnCalculate_Click() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.btnCalculate_Click (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue().
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
dGridInputParam_CellValueChanged() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl._gridEvents, IG.Forms.ScalarFunctionEvaluatorControl.btnResetDefault, IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue(), IG.Forms.ScalarFunctionEvaluatorControl.DataFromGrid(), IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation, and IG.Lib.Util.SleepSeconds().
resetToDefaultToolStripMenuItem_Click() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.NumParameters, IG.Forms.ScalarFunctionEvaluatorControl.ResetToDefault(), and IG.Forms.ScalarFunctionEvaluatorControl.SetDefaultParameterValues().
CreateFunctionSummary() [1/4]
string IG.Forms.ScalarFunctionEvaluatorControl.CreateFunctionSummary () inline
Returns a string that contains a summary of the evaluated function.
References IG.Forms.ScalarFunctionEvaluatorControl.FunctionDefinition, IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation, IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunction, IG.Forms.ScalarFunctionEvaluatorControl.TreatScalarAsVectorFunction, and IG.Forms.ScalarFunctionEvaluatorControl.VectorFunction.
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.btnShowDefinition_Click().
btnShowDefinition_Click() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.btnShowDefinition_Click (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.CreateFunctionSummary(), IG.Forms.UtilForms.Reporter, and IG.Lib.IReporterBase.ReportInfo().
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
chkImmediateCalculation_CheckedChanged() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.chkImmediateCalculation_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.chkImmediateCalculation, and IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation.
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
chkTreatAsVector_CheckedChanged() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.chkTreatAsVector_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.chkTreatAsVector, and IG.Forms.ScalarFunctionEvaluatorControl.TreatScalarAsVectorFunction.
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
btnIdentifyThread_Click() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.btnIdentifyThread_Click (object sender, EventArgs e) inline private
References IG.Forms.UtilForms.GetCurrentThreadInfo(), and IG.Forms.FadingMessage.Launch().
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
Dispose() [1/4]
override void IG.Forms.ScalarFunctionEvaluatorControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ScalarFunctionEvaluatorControl.components.
InitializeComponent() [1/4]
void IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ScalarFunctionEvaluatorControl.btnCalculate, IG.Forms.ScalarFunctionEvaluatorControl.btnCalculate_Click(), IG.Forms.ScalarFunctionEvaluatorControl.btnIdentifyThread, IG.Forms.ScalarFunctionEvaluatorControl.btnIdentifyThread_Click(), IG.Forms.ScalarFunctionEvaluatorControl.btnResetDefault, IG.Forms.ScalarFunctionEvaluatorControl.btnResetDefault_Click(), IG.Forms.ScalarFunctionEvaluatorControl.btnShowDefinition, IG.Forms.ScalarFunctionEvaluatorControl.btnShowDefinition_Click(), IG.Forms.ScalarFunctionEvaluatorControl.chkImmediateCalculation, IG.Forms.ScalarFunctionEvaluatorControl.chkImmediateCalculation_CheckedChanged(), IG.Forms.ScalarFunctionEvaluatorControl.chkTreatAsVector, IG.Forms.ScalarFunctionEvaluatorControl.chkTreatAsVector_CheckedChanged(), IG.Forms.ScalarFunctionEvaluatorControl.columnID, IG.Forms.ScalarFunctionEvaluatorControl.columnName, IG.Forms.ScalarFunctionEvaluatorControl.columnValue, IG.Forms.ScalarFunctionEvaluatorControl.components, IG.Forms.ScalarFunctionEvaluatorControl.contextMenuControl, IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, IG.Forms.ScalarFunctionEvaluatorControl.groupBox1, IG.Forms.ScalarFunctionEvaluatorControl.label1, IG.Forms.ScalarFunctionEvaluatorControl.lblParameters, IG.Forms.ScalarFunctionEvaluatorControl.resetToDefaultToolStripMenuItem, and IG.Forms.ScalarFunctionEvaluatorControl.txtValue.
SetDefaultParameterNames() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.SetDefaultParameterNames (int dim, string baseName = "x") inline protected
Sets parameter names to default.
Parameters
dim Number of parameters.
baseName Optiional base name for parameters.
References IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames.
SetDefaultParameterValues() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.SetDefaultParameterValues (int dim, double defaultValue = 0) inline protected
Sets parameter values to default.
Parameters
dim Number of parameters.
defaultValue Optional default value, if not specified then 0.
References IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue(), IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation, and IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues.
GetGridControl() [2/4]
DataGridView IG.Forms.ScalarFunctionEvaluatorControl.GetGridControl () inline
Returns the DataGridView control that is used for setting values of the input parameters.
Returns
References IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam.
InitializeCells() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.InitializeCells () inline
Initializes contents of the DataGridView.
References IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, IG.Forms.ScalarFunctionEvaluatorControl.NumParameters, IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames, and IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues.
DataToGrid() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.DataToGrid () inline
Copies internal data to grid view.
References IG.Forms.ScalarFunctionEvaluatorControl._gridEvents, IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames, and IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues.
DataFromGrid() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.DataFromGrid () inline
Copies internal data to grid view.
References IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues, and IG.Lib.UtilStr.ToDouble().
ClearCells() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.ClearCells () inline
Clears contents of all DataGridView cells.
References IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, and IG.Forms.ScalarFunctionEvaluatorControl.NumParameters.
ClearDataGrid() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.ClearDataGrid () inline
Removes all the data from the DataGridView.
References IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam.
ResetToDefault() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.ResetToDefault () inline
Resets cells to default values.
References IG.Forms.ScalarFunctionEvaluatorControl.ColNumValue, IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, IG.Forms.ScalarFunctionEvaluatorControl.InitializeCells(), and IG.Forms.ScalarFunctionEvaluatorControl.NumParameters.
ShowContextMenuControl() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.ShowContextMenuControl (object sender, MouseEventArgs e) inline
References IG.Forms.ScalarFunctionEvaluatorControl.contextMenuControl.
ScalarFunctionEvaluatorControl_MouseClick() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunctionEvaluatorControl_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.ShowContextMenuControl().
dGridInputParam_MouseClick() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.ShowContextMenuControl().
btnResetDefault_Click() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.btnResetDefault_Click (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.NumParameters, and IG.Forms.ScalarFunctionEvaluatorControl.SetDefaultParameterValues().
CalculateFunctionValue() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue () inline protected
References IG.Forms.ScalarFunctionEvaluatorControl._vectorFunctionValues, IG.Forms.ScalarFunctionEvaluatorControl.DataFromGrid(), IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues, IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunction, IG.Num.VectorBase.ToString(), IG.Forms.ScalarFunctionEvaluatorControl.txtValue, IG.Num.IScalarFunctionUntransformed.Value(), IG.Num.IVectorFunction.Value(), and IG.Forms.ScalarFunctionEvaluatorControl.VectorFunction.
btnCalculate_Click() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.btnCalculate_Click (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue().
dGridInputParam_CellValueChanged() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl._gridEvents, IG.Forms.ScalarFunctionEvaluatorControl.btnResetDefault, IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue(), IG.Forms.ScalarFunctionEvaluatorControl.DataFromGrid(), IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation, and IG.Lib.Util.SleepSeconds().
resetToDefaultToolStripMenuItem_Click() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.NumParameters, IG.Forms.ScalarFunctionEvaluatorControl.ResetToDefault(), and IG.Forms.ScalarFunctionEvaluatorControl.SetDefaultParameterValues().
CreateFunctionSummary() [2/4]
string IG.Forms.ScalarFunctionEvaluatorControl.CreateFunctionSummary () inline
Returns a string that contains a summary of the evaluated function.
References IG.Forms.ScalarFunctionEvaluatorControl.FunctionDefinition, IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation, IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunction, IG.Forms.ScalarFunctionEvaluatorControl.TreatScalarAsVectorFunction, and IG.Forms.ScalarFunctionEvaluatorControl.VectorFunction.
btnShowDefinition_Click() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.btnShowDefinition_Click (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.CreateFunctionSummary(), IG.Forms.UtilForms.Reporter, and IG.Lib.IReporterBase.ReportInfo().
chkImmediateCalculation_CheckedChanged() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.chkImmediateCalculation_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.chkImmediateCalculation, and IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation.
chkTreatAsVector_CheckedChanged() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.chkTreatAsVector_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.chkTreatAsVector, and IG.Forms.ScalarFunctionEvaluatorControl.TreatScalarAsVectorFunction.
btnIdentifyThread_Click() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.btnIdentifyThread_Click (object sender, EventArgs e) inline private
References IG.Forms.UtilForms.GetCurrentThreadInfo(), and IG.Forms.FadingMessage.Launch().
Dispose() [2/4]
override void IG.Forms.ScalarFunctionEvaluatorControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ScalarFunctionEvaluatorControl.components.
InitializeComponent() [2/4]
void IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ScalarFunctionEvaluatorControl.btnCalculate, IG.Forms.ScalarFunctionEvaluatorControl.btnCalculate_Click(), IG.Forms.ScalarFunctionEvaluatorControl.btnIdentifyThread, IG.Forms.ScalarFunctionEvaluatorControl.btnIdentifyThread_Click(), IG.Forms.ScalarFunctionEvaluatorControl.btnResetDefault, IG.Forms.ScalarFunctionEvaluatorControl.btnResetDefault_Click(), IG.Forms.ScalarFunctionEvaluatorControl.btnShowDefinition, IG.Forms.ScalarFunctionEvaluatorControl.btnShowDefinition_Click(), IG.Forms.ScalarFunctionEvaluatorControl.chkImmediateCalculation, IG.Forms.ScalarFunctionEvaluatorControl.chkImmediateCalculation_CheckedChanged(), IG.Forms.ScalarFunctionEvaluatorControl.chkTreatAsVector, IG.Forms.ScalarFunctionEvaluatorControl.chkTreatAsVector_CheckedChanged(), IG.Forms.ScalarFunctionEvaluatorControl.columnID, IG.Forms.ScalarFunctionEvaluatorControl.columnName, IG.Forms.ScalarFunctionEvaluatorControl.columnValue, IG.Forms.ScalarFunctionEvaluatorControl.components, IG.Forms.ScalarFunctionEvaluatorControl.contextMenuControl, IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, IG.Forms.ScalarFunctionEvaluatorControl.groupBox1, IG.Forms.ScalarFunctionEvaluatorControl.label1, IG.Forms.ScalarFunctionEvaluatorControl.lblParameters, IG.Forms.ScalarFunctionEvaluatorControl.resetToDefaultToolStripMenuItem, and IG.Forms.ScalarFunctionEvaluatorControl.txtValue.
SetDefaultParameterNames() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.SetDefaultParameterNames (int dim, string baseName = "x") inline protected
Sets parameter names to default.
Parameters
dim Number of parameters.
baseName Optiional base name for parameters.
References IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames.
SetDefaultParameterValues() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.SetDefaultParameterValues (int dim, double defaultValue = 0) inline protected
Sets parameter values to default.
Parameters
dim Number of parameters.
defaultValue Optional default value, if not specified then 0.
References IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue(), IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation, and IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues.
GetGridControl() [3/4]
DataGridView IG.Forms.ScalarFunctionEvaluatorControl.GetGridControl () inline
Returns the DataGridView control that is used for setting values of the input parameters.
Returns
References IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam.
InitializeCells() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.InitializeCells () inline
Initializes contents of the DataGridView.
References IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, IG.Forms.ScalarFunctionEvaluatorControl.NumParameters, IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames, and IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues.
DataToGrid() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.DataToGrid () inline
Copies internal data to grid view.
References IG.Forms.ScalarFunctionEvaluatorControl._gridEvents, IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames, and IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues.
DataFromGrid() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.DataFromGrid () inline
Copies internal data to grid view.
References IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues, and IG.Lib.UtilStr.ToDouble().
ClearCells() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.ClearCells () inline
Clears contents of all DataGridView cells.
References IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, and IG.Forms.ScalarFunctionEvaluatorControl.NumParameters.
ClearDataGrid() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.ClearDataGrid () inline
Removes all the data from the DataGridView.
References IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam.
ResetToDefault() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.ResetToDefault () inline
Resets cells to default values.
References IG.Forms.ScalarFunctionEvaluatorControl.ColNumValue, IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, IG.Forms.ScalarFunctionEvaluatorControl.InitializeCells(), and IG.Forms.ScalarFunctionEvaluatorControl.NumParameters.
ShowContextMenuControl() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.ShowContextMenuControl (object sender, MouseEventArgs e) inline
References IG.Forms.ScalarFunctionEvaluatorControl.contextMenuControl.
ScalarFunctionEvaluatorControl_MouseClick() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunctionEvaluatorControl_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.ShowContextMenuControl().
dGridInputParam_MouseClick() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.ShowContextMenuControl().
btnResetDefault_Click() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.btnResetDefault_Click (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.NumParameters, and IG.Forms.ScalarFunctionEvaluatorControl.SetDefaultParameterValues().
CalculateFunctionValue() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue () inline protected
References IG.Forms.ScalarFunctionEvaluatorControl._vectorFunctionValues, IG.Forms.ScalarFunctionEvaluatorControl.DataFromGrid(), IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues, IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunction, IG.Num.VectorBase.ToString(), IG.Forms.ScalarFunctionEvaluatorControl.txtValue, IG.Num.IScalarFunctionUntransformed.Value(), IG.Num.IVectorFunction.Value(), and IG.Forms.ScalarFunctionEvaluatorControl.VectorFunction.
btnCalculate_Click() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.btnCalculate_Click (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue().
dGridInputParam_CellValueChanged() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl._gridEvents, IG.Forms.ScalarFunctionEvaluatorControl.btnResetDefault, IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue(), IG.Forms.ScalarFunctionEvaluatorControl.DataFromGrid(), IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation, and IG.Lib.Util.SleepSeconds().
resetToDefaultToolStripMenuItem_Click() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.NumParameters, IG.Forms.ScalarFunctionEvaluatorControl.ResetToDefault(), and IG.Forms.ScalarFunctionEvaluatorControl.SetDefaultParameterValues().
CreateFunctionSummary() [3/4]
string IG.Forms.ScalarFunctionEvaluatorControl.CreateFunctionSummary () inline
Returns a string that contains a summary of the evaluated function.
References IG.Forms.ScalarFunctionEvaluatorControl.FunctionDefinition, IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation, IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunction, IG.Forms.ScalarFunctionEvaluatorControl.TreatScalarAsVectorFunction, and IG.Forms.ScalarFunctionEvaluatorControl.VectorFunction.
btnShowDefinition_Click() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.btnShowDefinition_Click (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.CreateFunctionSummary(), IG.Forms.UtilForms.Reporter, and IG.Lib.IReporterBase.ReportInfo().
chkImmediateCalculation_CheckedChanged() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.chkImmediateCalculation_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.chkImmediateCalculation, and IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation.
chkTreatAsVector_CheckedChanged() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.chkTreatAsVector_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.chkTreatAsVector, and IG.Forms.ScalarFunctionEvaluatorControl.TreatScalarAsVectorFunction.
btnIdentifyThread_Click() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.btnIdentifyThread_Click (object sender, EventArgs e) inline private
References IG.Forms.UtilForms.GetCurrentThreadInfo(), and IG.Forms.FadingMessage.Launch().
Dispose() [3/4]
override void IG.Forms.ScalarFunctionEvaluatorControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ScalarFunctionEvaluatorControl.components.
InitializeComponent() [3/4]
void IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ScalarFunctionEvaluatorControl.btnCalculate, IG.Forms.ScalarFunctionEvaluatorControl.btnCalculate_Click(), IG.Forms.ScalarFunctionEvaluatorControl.btnIdentifyThread, IG.Forms.ScalarFunctionEvaluatorControl.btnIdentifyThread_Click(), IG.Forms.ScalarFunctionEvaluatorControl.btnResetDefault, IG.Forms.ScalarFunctionEvaluatorControl.btnResetDefault_Click(), IG.Forms.ScalarFunctionEvaluatorControl.btnShowDefinition, IG.Forms.ScalarFunctionEvaluatorControl.btnShowDefinition_Click(), IG.Forms.ScalarFunctionEvaluatorControl.chkImmediateCalculation, IG.Forms.ScalarFunctionEvaluatorControl.chkImmediateCalculation_CheckedChanged(), IG.Forms.ScalarFunctionEvaluatorControl.chkTreatAsVector, IG.Forms.ScalarFunctionEvaluatorControl.chkTreatAsVector_CheckedChanged(), IG.Forms.ScalarFunctionEvaluatorControl.columnID, IG.Forms.ScalarFunctionEvaluatorControl.columnName, IG.Forms.ScalarFunctionEvaluatorControl.columnValue, IG.Forms.ScalarFunctionEvaluatorControl.components, IG.Forms.ScalarFunctionEvaluatorControl.contextMenuControl, IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, IG.Forms.ScalarFunctionEvaluatorControl.groupBox1, IG.Forms.ScalarFunctionEvaluatorControl.label1, IG.Forms.ScalarFunctionEvaluatorControl.lblParameters, IG.Forms.ScalarFunctionEvaluatorControl.resetToDefaultToolStripMenuItem, and IG.Forms.ScalarFunctionEvaluatorControl.txtValue.
SetDefaultParameterNames() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.SetDefaultParameterNames (int dim, string baseName = "x") inline protected
Sets parameter names to default.
Parameters
dim Number of parameters.
baseName Optiional base name for parameters.
References IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames.
SetDefaultParameterValues() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.SetDefaultParameterValues (int dim, double defaultValue = 0) inline protected
Sets parameter values to default.
Parameters
dim Number of parameters.
defaultValue Optional default value, if not specified then 0.
References IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue(), IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation, and IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues.
GetGridControl() [4/4]
DataGridView IG.Forms.ScalarFunctionEvaluatorControl.GetGridControl () inline
Returns the DataGridView control that is used for setting values of the input parameters.
Returns
References IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam.
InitializeCells() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.InitializeCells () inline
Initializes contents of the DataGridView.
References IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, IG.Forms.ScalarFunctionEvaluatorControl.NumParameters, IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames, and IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues.
DataToGrid() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.DataToGrid () inline
Copies internal data to grid view.
References IG.Forms.ScalarFunctionEvaluatorControl._gridEvents, IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames, and IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues.
DataFromGrid() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.DataFromGrid () inline
Copies internal data to grid view.
References IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues, and IG.Lib.UtilStr.ToDouble().
ClearCells() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.ClearCells () inline
Clears contents of all DataGridView cells.
References IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, and IG.Forms.ScalarFunctionEvaluatorControl.NumParameters.
ClearDataGrid() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.ClearDataGrid () inline
Removes all the data from the DataGridView.
References IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam.
ResetToDefault() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.ResetToDefault () inline
Resets cells to default values.
References IG.Forms.ScalarFunctionEvaluatorControl.ColNumValue, IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, IG.Forms.ScalarFunctionEvaluatorControl.InitializeCells(), and IG.Forms.ScalarFunctionEvaluatorControl.NumParameters.
ShowContextMenuControl() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.ShowContextMenuControl (object sender, MouseEventArgs e) inline
References IG.Forms.ScalarFunctionEvaluatorControl.contextMenuControl.
ScalarFunctionEvaluatorControl_MouseClick() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunctionEvaluatorControl_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.ShowContextMenuControl().
dGridInputParam_MouseClick() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam_MouseClick (object sender, MouseEventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.ShowContextMenuControl().
btnResetDefault_Click() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.btnResetDefault_Click (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.NumParameters, and IG.Forms.ScalarFunctionEvaluatorControl.SetDefaultParameterValues().
CalculateFunctionValue() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue () inline protected
References IG.Forms.ScalarFunctionEvaluatorControl._vectorFunctionValues, IG.Forms.ScalarFunctionEvaluatorControl.DataFromGrid(), IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues, IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunction, IG.Num.VectorBase.ToString(), IG.Forms.ScalarFunctionEvaluatorControl.txtValue, IG.Num.IScalarFunctionUntransformed.Value(), IG.Num.IVectorFunction.Value(), and IG.Forms.ScalarFunctionEvaluatorControl.VectorFunction.
btnCalculate_Click() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.btnCalculate_Click (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue().
dGridInputParam_CellValueChanged() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam_CellValueChanged (object sender, DataGridViewCellEventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl._gridEvents, IG.Forms.ScalarFunctionEvaluatorControl.btnResetDefault, IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue(), IG.Forms.ScalarFunctionEvaluatorControl.DataFromGrid(), IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation, and IG.Lib.Util.SleepSeconds().
resetToDefaultToolStripMenuItem_Click() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.resetToDefaultToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.NumParameters, IG.Forms.ScalarFunctionEvaluatorControl.ResetToDefault(), and IG.Forms.ScalarFunctionEvaluatorControl.SetDefaultParameterValues().
CreateFunctionSummary() [4/4]
string IG.Forms.ScalarFunctionEvaluatorControl.CreateFunctionSummary () inline
Returns a string that contains a summary of the evaluated function.
References IG.Forms.ScalarFunctionEvaluatorControl.FunctionDefinition, IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation, IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunction, IG.Forms.ScalarFunctionEvaluatorControl.TreatScalarAsVectorFunction, and IG.Forms.ScalarFunctionEvaluatorControl.VectorFunction.
btnShowDefinition_Click() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.btnShowDefinition_Click (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.CreateFunctionSummary(), IG.Forms.UtilForms.Reporter, and IG.Lib.IReporterBase.ReportInfo().
chkImmediateCalculation_CheckedChanged() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.chkImmediateCalculation_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.chkImmediateCalculation, and IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation.
chkTreatAsVector_CheckedChanged() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.chkTreatAsVector_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.ScalarFunctionEvaluatorControl.chkTreatAsVector, and IG.Forms.ScalarFunctionEvaluatorControl.TreatScalarAsVectorFunction.
btnIdentifyThread_Click() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.btnIdentifyThread_Click (object sender, EventArgs e) inline private
References IG.Forms.UtilForms.GetCurrentThreadInfo(), and IG.Forms.FadingMessage.Launch().
Dispose() [4/4]
override void IG.Forms.ScalarFunctionEvaluatorControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.ScalarFunctionEvaluatorControl.components.
InitializeComponent() [4/4]
void IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.ScalarFunctionEvaluatorControl.btnCalculate, IG.Forms.ScalarFunctionEvaluatorControl.btnCalculate_Click(), IG.Forms.ScalarFunctionEvaluatorControl.btnIdentifyThread, IG.Forms.ScalarFunctionEvaluatorControl.btnIdentifyThread_Click(), IG.Forms.ScalarFunctionEvaluatorControl.btnResetDefault, IG.Forms.ScalarFunctionEvaluatorControl.btnResetDefault_Click(), IG.Forms.ScalarFunctionEvaluatorControl.btnShowDefinition, IG.Forms.ScalarFunctionEvaluatorControl.btnShowDefinition_Click(), IG.Forms.ScalarFunctionEvaluatorControl.chkImmediateCalculation, IG.Forms.ScalarFunctionEvaluatorControl.chkImmediateCalculation_CheckedChanged(), IG.Forms.ScalarFunctionEvaluatorControl.chkTreatAsVector, IG.Forms.ScalarFunctionEvaluatorControl.chkTreatAsVector_CheckedChanged(), IG.Forms.ScalarFunctionEvaluatorControl.columnID, IG.Forms.ScalarFunctionEvaluatorControl.columnName, IG.Forms.ScalarFunctionEvaluatorControl.columnValue, IG.Forms.ScalarFunctionEvaluatorControl.components, IG.Forms.ScalarFunctionEvaluatorControl.contextMenuControl, IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam, IG.Forms.ScalarFunctionEvaluatorControl.groupBox1, IG.Forms.ScalarFunctionEvaluatorControl.label1, IG.Forms.ScalarFunctionEvaluatorControl.lblParameters, IG.Forms.ScalarFunctionEvaluatorControl.resetToDefaultToolStripMenuItem, and IG.Forms.ScalarFunctionEvaluatorControl.txtValue.
Member Data Documentation
_scalarFunction
IScalarFunction IG.Forms.ScalarFunctionEvaluatorControl._scalarFunction private
_vectorFunction
IVectorFunction IG.Forms.ScalarFunctionEvaluatorControl._vectorFunction private
_visibleTreatAsVector
bool IG.Forms.ScalarFunctionEvaluatorControl._visibleTreatAsVector = true private
_treatAsVectorFunction
bool IG.Forms.ScalarFunctionEvaluatorControl._treatAsVectorFunction = false private
_functionDefinition
string IG.Forms.ScalarFunctionEvaluatorControl._functionDefinition = null protected
_parameterNames
string [] IG.Forms.ScalarFunctionEvaluatorControl._parameterNames private
_parameterValues
double [] IG.Forms.ScalarFunctionEvaluatorControl._parameterValues private
_colNumValue
int IG.Forms.ScalarFunctionEvaluatorControl._colNumValue = 2 protected
_gridEvents
bool IG.Forms.ScalarFunctionEvaluatorControl._gridEvents = true protected
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.DataToGrid(), and IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam_CellValueChanged().
_vectorFunctionValues
List< double > IG.Forms.ScalarFunctionEvaluatorControl._vectorFunctionValues = new List<double>() private
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue().
_immediateCalculation
bool IG.Forms.ScalarFunctionEvaluatorControl._immediateCalculation = true private
components
System ComponentModel IContainer IG.Forms.ScalarFunctionEvaluatorControl.components = null private
Required designer variable.
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.Dispose(), and IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
groupBox1
System Windows Forms GroupBox IG.Forms.ScalarFunctionEvaluatorControl.groupBox1 private
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
dGridInputParam
System Windows Forms DataGridView IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam private
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.ClearCells(), IG.Forms.ScalarFunctionEvaluatorControl.ClearDataGrid(), IG.Forms.ScalarFunctionEvaluatorControl.DataFromGrid(), IG.Forms.ScalarFunctionEvaluatorControl.DataToGrid(), IG.Forms.ScalarFunctionEvaluatorControl.GetGridControl(), IG.Forms.ScalarFunctionEvaluatorControl.InitializeCells(), IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent(), and IG.Forms.ScalarFunctionEvaluatorControl.ResetToDefault().
btnResetDefault
System Windows Forms Button IG.Forms.ScalarFunctionEvaluatorControl.btnResetDefault private
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam_CellValueChanged(), and IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
btnCalculate
System Windows Forms Button IG.Forms.ScalarFunctionEvaluatorControl.btnCalculate private
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
contextMenuControl
System Windows Forms ContextMenuStrip IG.Forms.ScalarFunctionEvaluatorControl.contextMenuControl private
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent(), and IG.Forms.ScalarFunctionEvaluatorControl.ShowContextMenuControl().
resetToDefaultToolStripMenuItem
System Windows Forms ToolStripMenuItem IG.Forms.ScalarFunctionEvaluatorControl.resetToDefaultToolStripMenuItem private
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
label1
System Windows Forms Label IG.Forms.ScalarFunctionEvaluatorControl.label1 private
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
txtValue
System Windows Forms TextBox IG.Forms.ScalarFunctionEvaluatorControl.txtValue private
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue(), and IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
lblParameters
System Windows Forms Label IG.Forms.ScalarFunctionEvaluatorControl.lblParameters private
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
btnShowDefinition
System Windows Forms Button IG.Forms.ScalarFunctionEvaluatorControl.btnShowDefinition private
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
chkImmediateCalculation
System Windows Forms CheckBox IG.Forms.ScalarFunctionEvaluatorControl.chkImmediateCalculation private
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.chkImmediateCalculation_CheckedChanged(), and IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
chkTreatAsVector
System Windows Forms CheckBox IG.Forms.ScalarFunctionEvaluatorControl.chkTreatAsVector private
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.chkTreatAsVector_CheckedChanged(), and IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
columnID
System Windows Forms DataGridViewTextBoxColumn IG.Forms.ScalarFunctionEvaluatorControl.columnID private
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
columnName
System Windows Forms DataGridViewTextBoxColumn IG.Forms.ScalarFunctionEvaluatorControl.columnName private
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
columnValue
System Windows Forms DataGridViewTextBoxColumn IG.Forms.ScalarFunctionEvaluatorControl.columnValue private
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
btnIdentifyThread
System Windows Forms Button IG.Forms.ScalarFunctionEvaluatorControl.btnIdentifyThread private
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.InitializeComponent().
Property Documentation
ScalarFunction
IScalarFunction IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunction get set
Scalar function that is evaluated by the current control.
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue(), IG.Forms.ScalarFunctionEvaluatorControl.CreateFunctionSummary(), IG.Forms.ScalarFunctionEvaluatorForm.InitializeComponent(), and IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunctionEvaluatorControl().
VectorFunction
IVectorFunction IG.Forms.ScalarFunctionEvaluatorControl.VectorFunction get set
Vector function whose values are calculated.
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue(), IG.Forms.ScalarFunctionEvaluatorControl.CreateFunctionSummary(), and IG.Forms.ScalarFunctionEvaluatorForm.InitializeComponent().
VisibleTreatAsVector
bool IG.Forms.ScalarFunctionEvaluatorControl.VisibleTreatAsVector get set
Whether the check box for treating scalar function as a vector will be visible or not.
Referenced by IG.Forms.ScalarFunctionEvaluatorForm.InitializeComponent().
TreatScalarAsVectorFunction
bool IG.Forms.ScalarFunctionEvaluatorControl.TreatScalarAsVectorFunction get set
If true then scalar function is converted to a vector funciton when set.
Referenced by IG.Forms.ScalarFunctionScriptControl.btnValueCalculator_Click(), IG.Forms.ScalarFunctionEvaluatorControl.chkTreatAsVector_CheckedChanged(), IG.Forms.ScalarFunctionEvaluatorControl.CreateFunctionSummary(), and IG.Forms.ScalarFunctionEvaluatorForm.InitializeComponent().
FunctionDefinition
string IG.Forms.ScalarFunctionEvaluatorControl.FunctionDefinition get set
Function definition that can be assigned by creator of the window. This will be used when the verification button is pressed.
Referenced by IG.Forms.ScalarFunctionScriptControl.btnValueCalculator_Click(), IG.Forms.ScalarFunctionEvaluatorControl.CreateFunctionSummary(), and IG.Forms.ScalarFunctionEvaluatorForm.InitializeComponent().
ParameterNames
string [] IG.Forms.ScalarFunctionEvaluatorControl.ParameterNames get set
Names of function parameters, shown in data grid.
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.DataToGrid(), IG.Forms.ScalarFunctionEvaluatorControl.InitializeCells(), IG.Forms.ScalarFunctionEvaluatorForm.InitializeComponent(), IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunctionEvaluatorControl(), and IG.Forms.ScalarFunctionEvaluatorControl.SetDefaultParameterNames().
ParameterValues
double [] IG.Forms.ScalarFunctionEvaluatorControl.ParameterValues get set
Valuse of parameters, shown in data grid.
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.CalculateFunctionValue(), IG.Forms.ScalarFunctionEvaluatorControl.DataFromGrid(), IG.Forms.ScalarFunctionEvaluatorControl.DataToGrid(), IG.Forms.ScalarFunctionEvaluatorControl.InitializeCells(), IG.Forms.ScalarFunctionEvaluatorForm.InitializeComponent(), IG.Forms.ScalarFunctionEvaluatorControl.ScalarFunctionEvaluatorControl(), and IG.Forms.ScalarFunctionEvaluatorControl.SetDefaultParameterValues().
NumParameters
int IG.Forms.ScalarFunctionEvaluatorControl.NumParameters get set
Gets or sets number of parameters.
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.btnResetDefault_Click(), IG.Forms.ScalarFunctionEvaluatorControl.ClearCells(), IG.Forms.ScalarFunctionEvaluatorControl.InitializeCells(), IG.Forms.ScalarFunctionEvaluatorForm.InitializeComponent(), IG.Forms.ScalarFunctionEvaluatorControl.ResetToDefault(), and IG.Forms.ScalarFunctionEvaluatorControl.resetToDefaultToolStripMenuItem_Click().
ColNumValue
int IG.Forms.ScalarFunctionEvaluatorControl.ColNumValue get protected set
Number of DataGrid Column that contains the value.
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.ResetToDefault().
ImmediateCalculation
bool IG.Forms.ScalarFunctionEvaluatorControl.ImmediateCalculation get set
Referenced by IG.Forms.ScalarFunctionEvaluatorControl.chkImmediateCalculation_CheckedChanged(), IG.Forms.ScalarFunctionEvaluatorControl.CreateFunctionSummary(), IG.Forms.ScalarFunctionEvaluatorControl.dGridInputParam_CellValueChanged(), IG.Forms.ScalarFunctionEvaluatorForm.InitializeComponent(), and IG.Forms.ScalarFunctionEvaluatorControl.SetDefaultParameterValues().
The documentation for this class was generated from the following files:
iglib/extensions/iglibext/Forms/Numeric/ScalarFunctionEvaluatorControl.cs
iglib/extensions/iglibext/Forms/Numeric/ScalarFunctionEvaluatorControl.Designer.cs