Doc: IGLib EXTENDED: NUnit.Framework.Internal.SetUpTearDownTests Class Reference
NUnit.Framework.Internal.SetUpTearDownTests Class Reference
Classes
class SetupCallBase
class SetupCallDerived
Public Member Functions
void SetUpAndTearDownCounter ()
void MakeSureSetUpAndTearDownAreCalled ()
void CheckInheritedSetUpAndTearDownAreCalled ()
void CheckOverriddenSetUpAndTearDownAreNotCalled ()
void MultipleSetUpAndTearDownMethodsAreCalled ()
void BaseSetUpIsCalledFirstTearDownLast ()
void FailureInBaseSetUpCausesDerivedSetUpAndTearDownToBeSkipped ()
void HandleExceptionInSetUp ()
void HandleExceptionInTearDown ()
void HandleExceptionInBothSetUpAndTearDown ()
Member Function Documentation
SetUpAndTearDownCounter()
void NUnit.Framework.Internal.SetUpTearDownTests.SetUpAndTearDownCounter () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.SetUpData.SetUpAndTearDownCounterFixture.setUpCounter, and NUnit.TestData.SetUpData.SetUpAndTearDownCounterFixture.tearDownCounter.
MakeSureSetUpAndTearDownAreCalled()
void NUnit.Framework.Internal.SetUpTearDownTests.MakeSureSetUpAndTearDownAreCalled () inline
References NUnit.Framework.Assert.IsTrue(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.SetUpData.SetUpAndTearDownFixture.wasSetUpCalled, and NUnit.TestData.SetUpData.SetUpAndTearDownFixture.wasTearDownCalled.
CheckInheritedSetUpAndTearDownAreCalled()
void NUnit.Framework.Internal.SetUpTearDownTests.CheckInheritedSetUpAndTearDownAreCalled () inline
References NUnit.Framework.Assert.IsTrue(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.SetUpData.SetUpAndTearDownFixture.wasSetUpCalled, and NUnit.TestData.SetUpData.SetUpAndTearDownFixture.wasTearDownCalled.
CheckOverriddenSetUpAndTearDownAreNotCalled()
void NUnit.Framework.Internal.SetUpTearDownTests.CheckOverriddenSetUpAndTearDownAreNotCalled () inline
References NUnit.TestData.SetUpData.DefineInheritSetUpAndTearDown.derivedSetUpCalled, NUnit.TestData.SetUpData.DefineInheritSetUpAndTearDown.derivedTearDownCalled, NUnit.Framework.Assert.IsFalse(), NUnit.Framework.Assert.IsTrue(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.SetUpData.SetUpAndTearDownFixture.wasSetUpCalled, and NUnit.TestData.SetUpData.SetUpAndTearDownFixture.wasTearDownCalled.
MultipleSetUpAndTearDownMethodsAreCalled()
void NUnit.Framework.Internal.SetUpTearDownTests.MultipleSetUpAndTearDownMethodsAreCalled () inline
References NUnit.Framework.Assert.IsTrue(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.SetUpData.MultipleSetUpTearDownFixture.wasSetUp1Called, NUnit.TestData.SetUpData.MultipleSetUpTearDownFixture.wasSetUp2Called, NUnit.TestData.SetUpData.MultipleSetUpTearDownFixture.wasSetUp3Called, NUnit.TestData.SetUpData.MultipleSetUpTearDownFixture.wasTearDown1Called, and NUnit.TestData.SetUpData.MultipleSetUpTearDownFixture.wasTearDown2Called.
BaseSetUpIsCalledFirstTearDownLast()
void NUnit.Framework.Internal.SetUpTearDownTests.BaseSetUpIsCalledFirstTearDownLast () inline
References NUnit.Framework.Assert.IsTrue(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.SetUpData.DerivedClassWithSeparateSetUp.wasBaseSetUpCalledFirst, NUnit.TestData.SetUpData.DerivedClassWithSeparateSetUp.wasBaseTearDownCalledLast, NUnit.TestData.SetUpData.DerivedClassWithSeparateSetUp.wasDerivedSetUpCalled, NUnit.TestData.SetUpData.DerivedClassWithSeparateSetUp.wasDerivedTearDownCalled, NUnit.TestData.SetUpData.SetUpAndTearDownFixture.wasSetUpCalled, and NUnit.TestData.SetUpData.SetUpAndTearDownFixture.wasTearDownCalled.
FailureInBaseSetUpCausesDerivedSetUpAndTearDownToBeSkipped()
void NUnit.Framework.Internal.SetUpTearDownTests.FailureInBaseSetUpCausesDerivedSetUpAndTearDownToBeSkipped () inline
References NUnit.Framework.Assert.IsFalse(), NUnit.Framework.Assert.IsTrue(), NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.SetUpData.SetUpAndTearDownFixture.throwInBaseSetUp, NUnit.TestData.SetUpData.DerivedClassWithSeparateSetUp.wasDerivedSetUpCalled, NUnit.TestData.SetUpData.DerivedClassWithSeparateSetUp.wasDerivedTearDownCalled, NUnit.TestData.SetUpData.SetUpAndTearDownFixture.wasSetUpCalled, and NUnit.TestData.SetUpData.SetUpAndTearDownFixture.wasTearDownCalled.
HandleExceptionInSetUp()
void NUnit.Framework.Internal.SetUpTearDownTests.HandleExceptionInSetUp () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ITestResult.Children, NUnit.Framework.Does.Contain(), NUnit.Framework.Interfaces.ResultState.Error, NUnit.Framework.Interfaces.ITestResult.HasChildren, NUnit.Framework.Assert.IsTrue(), NUnit.Framework.Internal.TestResult.Message, NUnit.Framework.Internal.TestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.SetUpData.SetupAndTearDownExceptionFixture.setupException, NUnit.Framework.Internal.TestResult.StackTrace, and NUnit.Framework.Assert.That().
HandleExceptionInTearDown()
void NUnit.Framework.Internal.SetUpTearDownTests.HandleExceptionInTearDown () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ITestResult.Children, NUnit.Framework.Does.Contain(), NUnit.Framework.Interfaces.ResultState.Error, NUnit.Framework.Interfaces.ITestResult.HasChildren, NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.Framework.Interfaces.ITestResult.StackTrace, NUnit.Framework.Does.StartWith(), NUnit.TestData.SetUpData.SetupAndTearDownExceptionFixture.tearDownException, and NUnit.Framework.Assert.That().
HandleExceptionInBothSetUpAndTearDown()
void NUnit.Framework.Internal.SetUpTearDownTests.HandleExceptionInBothSetUpAndTearDown () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ITestResult.Children, NUnit.Framework.Does.Contain(), NUnit.Framework.Interfaces.ResultState.Error, NUnit.Framework.Interfaces.ITestResult.HasChildren, NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Env.NewLine, NUnit.Framework.Interfaces.ITestResult.ResultState, NUnit.TestUtilities.TestBuilder.RunTestFixture(), NUnit.TestData.SetUpData.SetupAndTearDownExceptionFixture.setupException, NUnit.Framework.Interfaces.ITestResult.StackTrace, NUnit.TestData.SetUpData.SetupAndTearDownExceptionFixture.tearDownException, and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/SetUpTearDownTests.cs