Doc: IGLib EXTENDED: IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator > Class Template Reference
IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator > Class Template Reference abstract
Base class for a variety of response evaluators. Calculates response at specific parameters, stores calculated responses in a list, etc. The current generic class can be used for differnt types of respnses (results) and different types of object for evaluation of responses, such as vector funcitons or optimization analyses.
Public Member Functions
ResponseEvaluatorWithStorageBase ()
Creates a ResponseEvaluatorBase object.
ResponseEvaluatorWithStorageBase (TypeEvaluator evaluationFunction)
Creates a ResponseEvaluatorBase object with the specified response evaluator that will be used for response evaluation.
virtual void EvaluateResponse (IVector parameters)
Evaluates the response at specific parameters.
virtual void EvaluateResponse (TypeData requestAndResponse)
void ClearResults ()
Removes all results from the list of results. The list is intended to store the results.
void AddResult (TypeData result)
Adds a new result to the list of results. The list is intended to store the results.
Protected Member Functions
abstract void GetData (TypeData results)
Copies input data from results object.
abstract TypeData CopyResults (TypeData results)
Creates and returns a copy of the speccified results object.
abstract void CreateRequestThis (IVector parameters, ref TypeData request)
Creates a request for response evaluation at the specified parameters, where request options are transcribed from the current response evaluator.
TypeData CreateRequestThis (IVector parameters)
Creates and returns request for response evaluation at the specified parameters, where request options are transcribed from the current response evaluator.
abstract void EvaluateResponseThis (TypeData requestAndResponse)
Evaluates the response.
Properties
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
object InternalLock [get]
Used internally for locking access to internal fields.
virtual TypeData LastResults [get, set]
Results of the last evaluation of response performed by the current response evaluator.
virtual bool AddResultsAutomatically [get, set]
Flag indicated whether the last evaluated results are automatically added to the list of results when these results are set (by setting the LastResults property).
List< TypeData > Results [get, protected set]
List of calculated results. The list is intended to store the results.
virtual TypeData this[int which] [get, set]
abstract TypeEvaluator EvaluationObject [get, set]
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
object _mainLock = new object()
object _internalLock = new object()
TypeData _lastResults
bool _addResultsAutomatically = true
List< TypeData > _results
Detailed Description
Base class for a variety of response evaluators. Calculates response at specific parameters, stores calculated responses in a list, etc. The current generic class can be used for differnt types of respnses (results) and different types of object for evaluation of responses, such as vector funcitons or optimization analyses.
Template Parameters
TypeResults Type of the objects wheer results of evaluation response are stored. Type of objects that hold requests for evaluation of respone must be the same.
TypeEvaluator Type of the function that performs response calculation.</type>
This class provides a generic way for performing evaluation of response at specified parameters and for storing a list of evaluated responses on the followng grounds:
* Response is evaluated by a special designated evaluation object.
* Input parameters for response evaluation are specified as vector.
* Evaluation object performs evaluation on basis of object of a special class that contains the input parameters, the request flags specifying what and how should be evaluated, and results.
$A Igor Jul08;
Type Constraints
TypeData : class
TypeEvaluator : class
Constructor & Destructor Documentation
ResponseEvaluatorWithStorageBase() [1/2]
IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >.ResponseEvaluatorWithStorageBase () inline
Creates a ResponseEvaluatorBase object.
ResponseEvaluatorWithStorageBase() [2/2]
IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >.ResponseEvaluatorWithStorageBase (TypeEvaluator evaluationFunction) inline
Creates a ResponseEvaluatorBase object with the specified response evaluator that will be used for response evaluation.
Parameters
evaluationFunction Evaluator object that is used for calculation of respones.
Member Function Documentation
GetData()
abstract void IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >.GetData (TypeData results) protected pure virtual
Copies input data from results object.
Parameters
results
Referenced by IG.Num.ResponseEvaluatorWithStorageBase< VectorFunctionResults, IVectorFunction >.EvaluateResponse().
CopyResults()
abstract TypeData IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >.CopyResults (TypeData results) protected pure virtual
Creates and returns a copy of the speccified results object.
Parameters
results Results object to be copied.
Returns
A copy of results object.
Referenced by IG.Num.ResponseEvaluatorWithStorageBase< VectorFunctionResults, IVectorFunction >.EvaluateResponse().
CreateRequestThis() [1/2]
abstract void IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >.CreateRequestThis (IVector parameters, ref TypeData request) protected pure virtual
Creates a request for response evaluation at the specified parameters, where request options are transcribed from the current response evaluator.
Parameters
parameters Vector of parameters for which response will be calculated.
request Reference to the object where request data for response evaluation is written to.
Referenced by IG.Num.ResponseEvaluatorWithStorageBase< VectorFunctionResults, IVectorFunction >.CreateRequestThis(), and IG.Num.ResponseEvaluatorWithStorageBase< VectorFunctionResults, IVectorFunction >.EvaluateResponse().
CreateRequestThis() [2/2]
TypeData IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >.CreateRequestThis (IVector parameters) inline protected
Creates and returns request for response evaluation at the specified parameters, where request options are transcribed from the current response evaluator.
Parameters
parameters Vector of parameters for which response will be calculated.
Returns
Object where request data for response evaluation is written to.
EvaluateResponseThis()
abstract void IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >.EvaluateResponseThis (TypeData requestAndResponse) protected pure virtual
Evaluates the response.
Parameters
results Object that must contain complete response evaluation request data, and where results of response evaluation will be stored.
Referenced by IG.Num.ResponseEvaluatorWithStorageBase< VectorFunctionResults, IVectorFunction >.EvaluateResponse().
EvaluateResponse() [1/2]
virtual void IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >.EvaluateResponse (IVector parameters) inline virtual
Evaluates the response at specific parameters.
Parameters
parameters
EvaluateResponse() [2/2]
virtual void IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >.EvaluateResponse (TypeData requestAndResponse) inline virtual
ClearResults()
void IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >.ClearResults () inline
Removes all results from the list of results. The list is intended to store the results.
AddResult()
void IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >.AddResult (TypeData result) inline
Adds a new result to the list of results. The list is intended to store the results.
Parameters
result Object containing results to be added.
Member Data Documentation
_mainLock
object IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >._mainLock = new object() private
_internalLock
object IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >._internalLock = new object() private
_lastResults
TypeData IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >._lastResults private
_addResultsAutomatically
bool IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >._addResultsAutomatically = true private
_results
List<TypeData> IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >._results private
Property Documentation
Lock
object IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >.Lock get
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Referenced by IG.Num.ResponseEvaluatorWithStorageBase< VectorFunctionResults, IVectorFunction >.ClearResults(), and IG.Num.ResponseEvaluatorWithStorageBase< VectorFunctionResults, IVectorFunction >.EvaluateResponse().
InternalLock
object IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >.InternalLock get protected
Used internally for locking access to internal fields.
LastResults
virtual TypeData IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >.LastResults get set
Results of the last evaluation of response performed by the current response evaluator.
Referenced by IG.Num.ResponseEvaluatorWithStorageBase< VectorFunctionResults, IVectorFunction >.EvaluateResponse().
AddResultsAutomatically
virtual bool IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >.AddResultsAutomatically get set
Flag indicated whether the last evaluated results are automatically added to the list of results when these results are set (by setting the LastResults property).
Referenced by IG.Num.ResponseEvaluatorWithStorageVectorDtoBase< ResponseEvaluatorWithStorageVector >.CopyFromPlain(), and IG.Num.ResponseEvaluatorWithStorageAnalysisDtoBase< ResponseEvaluatorWithStorageAnalysis >.CopyFromPlain().
Results
List<TypeData> IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >.Results get protected set
List of calculated results. The list is intended to store the results.
Referenced by IG.Num.ResponseEvaluatorWithStorageBase< VectorFunctionResults, IVectorFunction >.AddResult(), IG.Num.ResponseEvaluatorWithStorageBase< VectorFunctionResults, IVectorFunction >.ClearResults(), IG.Num.ResponseEvaluatorWithStorageVectorDtoBase< ResponseEvaluatorWithStorageVector >.CopyFromPlain(), and IG.Num.ResponseEvaluatorWithStorageAnalysisDtoBase< ResponseEvaluatorWithStorageAnalysis >.CopyFromPlain().
this[int which]
virtual TypeData IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >.this[int which] get set
EvaluationObject
abstract TypeEvaluator IG.Num.ResponseEvaluatorWithStorageBase< TypeData, TypeEvaluator >.EvaluationObject get set
Referenced by IG.Num.ResponseEvaluatorWithStorageBase< VectorFunctionResults, IVectorFunction >.ResponseEvaluatorWithStorageBase().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/numeric/responseevaluator/ResponseEvaluatorGeneric.cs