Doc: IGLib EXTENDED: IG.Web.Forms.WSClientFormsAboutForm Class Reference
IG.Web.Forms.WSClientFormsAboutForm Class Reference
Form containing information about Web service test clients software.
Public Member Functions
WSClientFormsAboutForm ()
virtual string GetHelpLocationInExecutableDirectory ()
void ShowHelp ()
void ShowWebPage ()
Public Attributes
string DefaultApplicationName = "WS Test Clients"
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
string _homePageShort
string _helpLocation
BrowserSimpleForm _browser
string _applicationName
Properties
virtual string HomePageShort [get, protected set]
Short version of the application's home page.
virtual string HomePage [get]
virtual string HelpLocation [get]
Location of the help file that can be displayed in a web browser.
BrowserSimpleForm Browser [get]
string ApplicationName [get]
Private Member Functions
void lblAboutWeb_Click (object sender, EventArgs e)
void btnHelp_Click (object sender, EventArgs e)
void btnWeb_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Label lblTitle
System.Windows.Forms.Button btnHelp
System.Windows.Forms.Panel pnlAbout
System.Windows.Forms.Label lblAboutAuthors
System.Windows.Forms.Label lblAboutAuthorsIntro
System.Windows.Forms.Label lblAboutTitle
System.Windows.Forms.Label lblAboutWeb
System.Windows.Forms.Label lblAboutContact
System.Windows.Forms.Label lblAbourContactIntro
System.Windows.Forms.PictureBox pbIGLib
System.Windows.Forms.Label lblPoweredIGLib
System.Windows.Forms.Panel pnlIGLib
System.Windows.Forms.Button btnWeb
Static Private Attributes
const string DefaultHomePageShort = "www2.arnes.si/~ljc3m2/igor/iglib/"
const string DefaultHelpLocation = "http://www2.arnes.si/~ljc3m2/igor/iglib/index.html"
Detailed Description
Form containing information about Web service test clients software.
Help can also be triggered from here.
Constructor & Destructor Documentation
WSClientFormsAboutForm()
IG.Web.Forms.WSClientFormsAboutForm.WSClientFormsAboutForm () inline
References IG.Web.Forms.WSClientFormsAboutForm.DefaultHomePageShort, IG.Web.Forms.WSClientFormsAboutForm.InitializeComponent(), and IG.Web.Forms.WSClientFormsAboutForm.lblAboutWeb.
Member Function Documentation
GetHelpLocationInExecutableDirectory()
virtual string IG.Web.Forms.WSClientFormsAboutForm.GetHelpLocationInExecutableDirectory () inline virtual
References IG.Web.Forms.WSClientFormsAboutForm.ApplicationName.
ShowHelp()
void IG.Web.Forms.WSClientFormsAboutForm.ShowHelp () inline
References IG.Web.Forms.WSClientFormsAboutForm.Browser, IG.Web.Forms.WSClientFormsAboutForm.HelpLocation, and IG.Forms.BrowserSimpleForm.OpenLocation().
Referenced by IG.Web.Forms.WSClientFormsAboutForm.btnHelp_Click(), and IG.Web.Forms.WSClientFormsAboutWindow.ShowHelp().
ShowWebPage()
void IG.Web.Forms.WSClientFormsAboutForm.ShowWebPage () inline
References IG.Web.Forms.WSClientFormsAboutForm.Browser, IG.Web.Forms.WSClientFormsAboutForm.HomePage, and IG.Forms.BrowserSimpleForm.OpenLocation().
Referenced by IG.Web.Forms.WSClientFormsAboutForm.btnWeb_Click(), and IG.Web.Forms.WSClientFormsAboutWindow.ShowWebPage().
lblAboutWeb_Click()
void IG.Web.Forms.WSClientFormsAboutForm.lblAboutWeb_Click (object sender, EventArgs e) inline private
References IG.Web.Forms.WSClientFormsAboutForm.lblAboutWeb.
Referenced by IG.Web.Forms.WSClientFormsAboutForm.InitializeComponent().
btnHelp_Click()
void IG.Web.Forms.WSClientFormsAboutForm.btnHelp_Click (object sender, EventArgs e) inline private
References IG.Web.Forms.WSClientFormsAboutForm.ShowHelp().
Referenced by IG.Web.Forms.WSClientFormsAboutForm.InitializeComponent().
btnWeb_Click()
void IG.Web.Forms.WSClientFormsAboutForm.btnWeb_Click (object sender, EventArgs e) inline private
References IG.Web.Forms.WSClientFormsAboutForm.ShowWebPage().
Referenced by IG.Web.Forms.WSClientFormsAboutForm.InitializeComponent().
Dispose()
override void IG.Web.Forms.WSClientFormsAboutForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Web.Forms.WSClientFormsAboutForm.components.
InitializeComponent()
void IG.Web.Forms.WSClientFormsAboutForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Web.Forms.WSClientFormsAboutForm.btnHelp, IG.Web.Forms.WSClientFormsAboutForm.btnHelp_Click(), IG.Web.Forms.WSClientFormsAboutForm.btnWeb, IG.Web.Forms.WSClientFormsAboutForm.btnWeb_Click(), IG.Web.Forms.WSClientFormsAboutForm.lblAbourContactIntro, IG.Web.Forms.WSClientFormsAboutForm.lblAboutAuthors, IG.Web.Forms.WSClientFormsAboutForm.lblAboutAuthorsIntro, IG.Web.Forms.WSClientFormsAboutForm.lblAboutContact, IG.Web.Forms.WSClientFormsAboutForm.lblAboutTitle, IG.Web.Forms.WSClientFormsAboutForm.lblAboutWeb, IG.Web.Forms.WSClientFormsAboutForm.lblAboutWeb_Click(), IG.Web.Forms.WSClientFormsAboutForm.lblPoweredIGLib, IG.Web.Forms.WSClientFormsAboutForm.lblTitle, IG.Web.Forms.WSClientFormsAboutForm.pbIGLib, IG.Web.Forms.WSClientFormsAboutForm.pnlAbout, and IG.Web.Forms.WSClientFormsAboutForm.pnlIGLib.
Referenced by IG.Web.Forms.WSClientFormsAboutForm.WSClientFormsAboutForm().
Member Data Documentation
DefaultHomePageShort
const string IG.Web.Forms.WSClientFormsAboutForm.DefaultHomePageShort = "www2.arnes.si/~ljc3m2/igor/iglib/" static private
Referenced by IG.Web.Forms.WSClientFormsAboutForm.WSClientFormsAboutForm().
_homePageShort
string IG.Web.Forms.WSClientFormsAboutForm._homePageShort protected
DefaultHelpLocation
const string IG.Web.Forms.WSClientFormsAboutForm.DefaultHelpLocation = "http://www2.arnes.si/~ljc3m2/igor/iglib/index.html" static private
_helpLocation
string IG.Web.Forms.WSClientFormsAboutForm._helpLocation protected
_browser
BrowserSimpleForm IG.Web.Forms.WSClientFormsAboutForm._browser protected
DefaultApplicationName
string IG.Web.Forms.WSClientFormsAboutForm.DefaultApplicationName = "WS Test Clients"
_applicationName
string IG.Web.Forms.WSClientFormsAboutForm._applicationName protected
components
System.ComponentModel.IContainer IG.Web.Forms.WSClientFormsAboutForm.components = null private
Required designer variable.
Referenced by IG.Web.Forms.WSClientFormsAboutForm.Dispose().
lblTitle
System.Windows.Forms.Label IG.Web.Forms.WSClientFormsAboutForm.lblTitle private
Referenced by IG.Web.Forms.WSClientFormsAboutForm.InitializeComponent().
btnHelp
System.Windows.Forms.Button IG.Web.Forms.WSClientFormsAboutForm.btnHelp private
Referenced by IG.Web.Forms.WSClientFormsAboutForm.InitializeComponent().
pnlAbout
System.Windows.Forms.Panel IG.Web.Forms.WSClientFormsAboutForm.pnlAbout private
Referenced by IG.Web.Forms.WSClientFormsAboutForm.InitializeComponent().
lblAboutAuthors
System.Windows.Forms.Label IG.Web.Forms.WSClientFormsAboutForm.lblAboutAuthors private
Referenced by IG.Web.Forms.WSClientFormsAboutForm.InitializeComponent().
lblAboutAuthorsIntro
System.Windows.Forms.Label IG.Web.Forms.WSClientFormsAboutForm.lblAboutAuthorsIntro private
Referenced by IG.Web.Forms.WSClientFormsAboutForm.InitializeComponent().
lblAboutTitle
System.Windows.Forms.Label IG.Web.Forms.WSClientFormsAboutForm.lblAboutTitle private
Referenced by IG.Web.Forms.WSClientFormsAboutForm.InitializeComponent().
lblAboutWeb
System.Windows.Forms.Label IG.Web.Forms.WSClientFormsAboutForm.lblAboutWeb private
Referenced by IG.Web.Forms.WSClientFormsAboutForm.InitializeComponent(), IG.Web.Forms.WSClientFormsAboutForm.lblAboutWeb_Click(), and IG.Web.Forms.WSClientFormsAboutForm.WSClientFormsAboutForm().
lblAboutContact
System.Windows.Forms.Label IG.Web.Forms.WSClientFormsAboutForm.lblAboutContact private
Referenced by IG.Web.Forms.WSClientFormsAboutForm.InitializeComponent().
lblAbourContactIntro
System.Windows.Forms.Label IG.Web.Forms.WSClientFormsAboutForm.lblAbourContactIntro private
Referenced by IG.Web.Forms.WSClientFormsAboutForm.InitializeComponent().
pbIGLib
System.Windows.Forms.PictureBox IG.Web.Forms.WSClientFormsAboutForm.pbIGLib private
Referenced by IG.Web.Forms.WSClientFormsAboutForm.InitializeComponent().
lblPoweredIGLib
System.Windows.Forms.Label IG.Web.Forms.WSClientFormsAboutForm.lblPoweredIGLib private
Referenced by IG.Web.Forms.WSClientFormsAboutForm.InitializeComponent().
pnlIGLib
System.Windows.Forms.Panel IG.Web.Forms.WSClientFormsAboutForm.pnlIGLib private
Referenced by IG.Web.Forms.WSClientFormsAboutForm.InitializeComponent().
btnWeb
System.Windows.Forms.Button IG.Web.Forms.WSClientFormsAboutForm.btnWeb private
Referenced by IG.Web.Forms.WSClientFormsAboutForm.InitializeComponent().
Property Documentation
HomePageShort
virtual string IG.Web.Forms.WSClientFormsAboutForm.HomePageShort get protected set
Short version of the application's home page.
HomePage
virtual string IG.Web.Forms.WSClientFormsAboutForm.HomePage get
Referenced by IG.Web.Forms.WSClientFormsAboutForm.ShowWebPage().
HelpLocation
virtual string IG.Web.Forms.WSClientFormsAboutForm.HelpLocation get
Location of the help file that can be displayed in a web browser.
Referenced by IG.Web.Forms.WSClientFormsAboutForm.ShowHelp().
Browser
BrowserSimpleForm IG.Web.Forms.WSClientFormsAboutForm.Browser get protected
Referenced by IG.Web.Forms.WSClientFormsAboutForm.ShowHelp(), and IG.Web.Forms.WSClientFormsAboutForm.ShowWebPage().
ApplicationName
string IG.Web.Forms.WSClientFormsAboutForm.ApplicationName get
Referenced by IG.Web.Forms.WSClientFormsAboutForm.GetHelpLocationInExecutableDirectory().
The documentation for this class was generated from the following files:
igtest/IGLibTestShell/WebServices/WebServiceForms/WSClientFormsAbout.cs
igtest/IGLibTestShell/WebServices/WebServiceForms/WSClientFormsAbout.Designer.cs