Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLARZ Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLARZ Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLARZ (DAXPY daxpy, DCOPY dcopy, DGEMV dgemv, DGER dger, LSAME lsame)
DLARZ ()
void Run (string SIDE, int M, int N, int L, double[] V, int offset_v, int INCV, double TAU, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work)
Private Attributes
DAXPY _daxpy
DCOPY _dcopy
DGEMV _dgemv
DGER _dger
LSAME _lsame
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLARZ applies a real elementary reflector H to a real M-by-N matrix C, from either the left or the right. H is represented in the form
H = I - tau * v * v'
where tau is a real scalar and v is a real vector.
If tau = 0, then H is taken to be the unit matrix. /summary>
Constructor & Destructor Documentation
DLARZ() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLARZ.DLARZ (DAXPY daxpy, DCOPY dcopy, DGEMV dgemv, DGER dger, LSAME lsame) inline
DLARZ() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLARZ.DLARZ () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLARZ.Run (string SIDE, int M, int N, int L, double[] V, int offset_v, int INCV, double TAU, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work) inline
Purpose
DLARZ applies a real elementary reflector H to a real M-by-N matrix C, from either the left or the right. H is represented in the form
H = I - tau * v * v'
where tau is a real scalar and v is a real vector.
If tau = 0, then H is taken to be the unit matrix. /summary>
Parameters
SIDE (input) CHARACTER*1 = 'L': form H * C = 'R': form C * H /param>
Parameters
M (input) INTEGER The number of rows of the matrix C. /param>
Parameters
N (input) INTEGER The number of columns of the matrix C. /param>
Parameters
L (input) INTEGER The number of entries of the vector V containing the meaningful part of the Householder vectors. If SIDE = 'L', M .GE. L .GE. 0, if SIDE = 'R', N .GE. L .GE. 0. /param>
Parameters
V (input) DOUBLE PRECISION array, dimension (1+(L-1)*abs(INCV)) The vector v in the representation of H as returned by DTZRZF. V is not used if TAU = 0. /param>
Parameters
INCV (input) INTEGER The increment between elements of v. INCV .LT..GT. 0. /param>
Parameters
TAU (input) DOUBLE PRECISION The value tau in the representation of H. /param>
Parameters
C (input/output) DOUBLE PRECISION array, dimension (LDC,N) On entry, the M-by-N matrix C. On exit, C is overwritten by the matrix H * C if SIDE = 'L', or C * H if SIDE = 'R'. /param>
Parameters
LDC (input) INTEGER The leading dimension of the array C. LDC .GE. max(1,M). /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (N) if SIDE = 'L' or (M) if SIDE = 'R' /param>
References DotNumerics.LinearAlgebra.CSLapack.DLARZ.ONE, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DAXPY.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.DGER.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLARZ.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLATRZ.Run(), and DotNumerics.LinearAlgebra.CSLapack.DORMR3.Run().
Member Data Documentation
_daxpy
DAXPY DotNumerics.LinearAlgebra.CSLapack.DLARZ._daxpy private
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLARZ._dcopy private
_dgemv
DGEMV DotNumerics.LinearAlgebra.CSLapack.DLARZ._dgemv private
_dger
DGER DotNumerics.LinearAlgebra.CSLapack.DLARZ._dger private
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLARZ._lsame private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLARZ.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLARZ.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLARZ.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLARZ.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlarz.cs