Doc: IGLib EXTENDED: alglib.safesolve Class Reference
alglib.safesolve Class Reference
Static Public Member Functions
static bool rmatrixscaledtrsafesolve (double[,] a, double sa, int n, ref double[] x, bool isupper, int trans, bool isunit, double maxgrowth)
static bool cmatrixscaledtrsafesolve (complex[,] a, double sa, int n, ref complex[] x, bool isupper, int trans, bool isunit, double maxgrowth)
static bool rmatrixscaledtrsafesolve (double[,] a, double sa, int n, ref double[] x, bool isupper, int trans, bool isunit, double maxgrowth)
static bool cmatrixscaledtrsafesolve (complex[,] a, double sa, int n, ref complex[] x, bool isupper, int trans, bool isunit, double maxgrowth)
Static Private Member Functions
static bool cbasicsolveandupdate (complex alpha, complex beta, double lnmax, double bnorm, double maxgrowth, ref double xnorm, ref complex x)
static bool cbasicsolveandupdate (complex alpha, complex beta, double lnmax, double bnorm, double maxgrowth, ref double xnorm, ref complex x)
Member Function Documentation
rmatrixscaledtrsafesolve() [1/2]
static bool alglib.safesolve.rmatrixscaledtrsafesolve (double a[,], double sa, int n, ref double[] x, bool isupper, int trans, bool isunit, double maxgrowth) inline static
References alglib.ap.assert(), alglib.beta(), alglib.safesolve.cbasicsolveandupdate(), and alglib.math.maxrealnumber.
Referenced by alglib.testsafesolveunit.testsafesolve().
cmatrixscaledtrsafesolve() [1/2]
static bool alglib.safesolve.cmatrixscaledtrsafesolve (complex a[,], double sa, int n, ref complex[] x, bool isupper, int trans, bool isunit, double maxgrowth) inline static
References alglib.math.abscomplex(), alglib.ap.assert(), alglib.beta(), alglib.safesolve.cbasicsolveandupdate(), alglib.math.conj(), and alglib.math.maxrealnumber.
Referenced by alglib.testsafesolveunit.testsafesolve().
cbasicsolveandupdate() [1/2]
static bool alglib.safesolve.cbasicsolveandupdate (complex alpha, complex beta, double lnmax, double bnorm, double maxgrowth, ref double xnorm, ref complex x) inline static private
References alglib.math.abscomplex(), and alglib.beta().
Referenced by alglib.safesolve.cmatrixscaledtrsafesolve(), and alglib.safesolve.rmatrixscaledtrsafesolve().
rmatrixscaledtrsafesolve() [2/2]
static bool alglib.safesolve.rmatrixscaledtrsafesolve (double a[,], double sa, int n, ref double[] x, bool isupper, int trans, bool isunit, double maxgrowth) inline static
References alglib.ap.assert(), alglib.beta(), alglib.safesolve.cbasicsolveandupdate(), and alglib.math.maxrealnumber.
cmatrixscaledtrsafesolve() [2/2]
static bool alglib.safesolve.cmatrixscaledtrsafesolve (complex a[,], double sa, int n, ref complex[] x, bool isupper, int trans, bool isunit, double maxgrowth) inline static
References alglib.math.abscomplex(), alglib.ap.assert(), alglib.beta(), alglib.safesolve.cbasicsolveandupdate(), alglib.math.conj(), and alglib.math.maxrealnumber.
cbasicsolveandupdate() [2/2]
static bool alglib.safesolve.cbasicsolveandupdate (complex alpha, complex beta, double lnmax, double bnorm, double maxgrowth, ref double xnorm, ref complex x) inline static private
References alglib.math.abscomplex(), and alglib.beta().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/alglibinternal.cs