Doc: IGLib EXTENDED: NUnit.TestUtilities.TestFinder Class Reference
NUnit.TestUtilities.TestFinder Class Reference
Utility class used to locate tests by name in a test suite
Static Public Member Functions
static Test Find (string name, TestSuite suite, bool recursive)
static ITestResult Find (string name, ITestResult result, bool recursive)
Private Member Functions
TestFinder ()
Detailed Description
Utility class used to locate tests by name in a test suite
Constructor & Destructor Documentation
TestFinder()
NUnit.TestUtilities.TestFinder.TestFinder () inline private
Member Function Documentation
Find() [1/2]
static Test NUnit.TestUtilities.TestFinder.Find (string name, TestSuite suite, bool recursive) inline static
References NUnit.Framework.Internal.Test.Name.
Referenced by NUnit.Framework.Attributes.TestCaseAttributeTests.CanExcludePlatform(), NUnit.Framework.Attributes.TestCaseSourceTests.CanIgnoreIndividualTestCases(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanIgnoreIndividualTestCases(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanIncludePlatform(), NUnit.Framework.Attributes.TestCaseSourceTests.CanMarkIndividualTestCasesExplicit(), NUnit.Framework.Attributes.TestCaseAttributeTests.CanMarkIndividualTestCasesExplicit(), NUnit.TestUtilities.TestFinder.Find(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.MethodWithoutParamsIsNamedCorrectly(), NUnit.Framework.Attributes.ParameterizedTestFixtureNamingTests.MethodWithParamsIsNamedCorrectly(), NUnit.Framework.Attributes.TimeoutTests.SetUpTimesOutAndTearDownIsRun(), NUnit.Framework.Attributes.TimeoutTests.TestTimeOutElapsed(), NUnit.Framework.Attributes.TimeoutTests.TestTimeOutNotElapsed(), NUnit.Framework.Attributes.TimeoutTests.TestTimeOutTestCaseWithOutElapsed(), NUnit.Framework.Attributes.TimeoutTests.TestTimesOutAndTearDownIsRun(), and NUnit.Framework.Attributes.TimeoutTests.TimeoutCanBeSetOnTestFixture().
Find() [2/2]
static ITestResult NUnit.TestUtilities.TestFinder.Find (string name, ITestResult result, bool recursive) inline static
References NUnit.Framework.Interfaces.ITestResult.Children, NUnit.TestUtilities.TestFinder.Find(), NUnit.Framework.Interfaces.ITestResult.HasChildren, NUnit.Framework.Internal.TestResult.HasChildren, and NUnit.Framework.Internal.TestResult.Name.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/TestUtilities/TestFinder.cs