Doc: IGLib EXTENDED: NUnit.TestUtilities.Collections.SimpleObjectList Class Reference
NUnit.TestUtilities.Collections.SimpleObjectList Class Reference
SimpleObjectCollection is used in testing to ensure that only methods of the ICollection interface are accessible.
Public Member Functions
SimpleObjectList (IEnumerable< object > source)
SimpleObjectList (params object[] source)
void CopyTo (Array array, int index)
IEnumerator GetEnumerator ()
int Add (object value)
void Clear ()
bool Contains (object value)
int IndexOf (object value)
void Insert (int index, object value)
void Remove (object value)
void RemoveAt (int index)
Properties
int Count [get]
bool IsSynchronized [get]
object SyncRoot [get]
bool IsFixedSize [get]
bool IsReadOnly [get]
object this[int index] [get, set]
Private Attributes
readonly List< object > contents = new List<object>()
Detailed Description
SimpleObjectCollection is used in testing to ensure that only methods of the ICollection interface are accessible.
Constructor & Destructor Documentation
SimpleObjectList() [1/2]
NUnit.TestUtilities.Collections.SimpleObjectList.SimpleObjectList (IEnumerable< object > source) inline
SimpleObjectList() [2/2]
NUnit.TestUtilities.Collections.SimpleObjectList.SimpleObjectList (params object[] source) inline
Member Function Documentation
CopyTo()
void NUnit.TestUtilities.Collections.SimpleObjectList.CopyTo (Array array, int index) inline
References NUnit.TestUtilities.Collections.SimpleObjectList.contents.
GetEnumerator()
IEnumerator NUnit.TestUtilities.Collections.SimpleObjectList.GetEnumerator () inline
References NUnit.TestUtilities.Collections.SimpleObjectList.contents.
Add()
int NUnit.TestUtilities.Collections.SimpleObjectList.Add (object value) inline
References NUnit.TestUtilities.Collections.SimpleObjectList.contents.
Clear()
void NUnit.TestUtilities.Collections.SimpleObjectList.Clear () inline
References NUnit.TestUtilities.Collections.SimpleObjectList.contents.
Contains()
bool NUnit.TestUtilities.Collections.SimpleObjectList.Contains (object value) inline
References NUnit.TestUtilities.Collections.SimpleObjectList.contents.
IndexOf()
int NUnit.TestUtilities.Collections.SimpleObjectList.IndexOf (object value) inline
References NUnit.TestUtilities.Collections.SimpleObjectList.contents.
Insert()
void NUnit.TestUtilities.Collections.SimpleObjectList.Insert (int index, object value) inline
References NUnit.TestUtilities.Collections.SimpleObjectList.contents.
Remove()
void NUnit.TestUtilities.Collections.SimpleObjectList.Remove (object value) inline
References NUnit.TestUtilities.Collections.SimpleObjectList.contents.
RemoveAt()
void NUnit.TestUtilities.Collections.SimpleObjectList.RemoveAt (int index) inline
References NUnit.TestUtilities.Collections.SimpleObjectList.contents.
Member Data Documentation
contents
readonly List<object> NUnit.TestUtilities.Collections.SimpleObjectList.contents = new List<object>() private
Referenced by NUnit.TestUtilities.Collections.SimpleObjectList.Add(), NUnit.TestUtilities.Collections.SimpleObjectList.Clear(), NUnit.TestUtilities.Collections.SimpleObjectList.Contains(), NUnit.TestUtilities.Collections.SimpleObjectList.CopyTo(), NUnit.TestUtilities.Collections.SimpleObjectList.GetEnumerator(), NUnit.TestUtilities.Collections.SimpleObjectList.IndexOf(), NUnit.TestUtilities.Collections.SimpleObjectList.Insert(), NUnit.TestUtilities.Collections.SimpleObjectList.Remove(), and NUnit.TestUtilities.Collections.SimpleObjectList.RemoveAt().
Property Documentation
Count
int NUnit.TestUtilities.Collections.SimpleObjectList.Count get
IsSynchronized
bool NUnit.TestUtilities.Collections.SimpleObjectList.IsSynchronized get
SyncRoot
object NUnit.TestUtilities.Collections.SimpleObjectList.SyncRoot get
IsFixedSize
bool NUnit.TestUtilities.Collections.SimpleObjectList.IsFixedSize get
IsReadOnly
bool NUnit.TestUtilities.Collections.SimpleObjectList.IsReadOnly get
this[int index]
object NUnit.TestUtilities.Collections.SimpleObjectList.this[int index] get set
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/TestUtilities/Collections/SimpleObjectList.cs