Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGEHRD Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGEHRD Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGEHRD (DAXPY daxpy, DGEHD2 dgehd2, DGEMM dgemm, DLAHR2 dlahr2, DLARFB dlarfb, DTRMM dtrmm, XERBLA xerbla, ILAENV ilaenv)
DGEHRD ()
void Run (int N, int ILO, int IHI, ref double[] A, int offset_a, int LDA, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
DAXPY _daxpy
DGEHD2 _dgehd2
DGEMM _dgemm
DLAHR2 _dlahr2
DLARFB _dlarfb
DTRMM _dtrmm
XERBLA _xerbla
ILAENV _ilaenv
double[] T = new double[LDT * NBMAX]
Static Private Attributes
const int NBMAX = 64
const int LDT = NBMAX + 1
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGEHRD reduces a real general matrix A to upper Hessenberg form H by an orthogonal similarity transformation: Q' * A * Q = H .
/summary>
Constructor & Destructor Documentation
DGEHRD() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGEHRD.DGEHRD (DAXPY daxpy, DGEHD2 dgehd2, DGEMM dgemm, DLAHR2 dlahr2, DLARFB dlarfb, DTRMM dtrmm, XERBLA xerbla, ILAENV ilaenv) inline
DGEHRD() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGEHRD.DGEHRD () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGEHRD.Run (int N, int ILO, int IHI, ref double[] A, int offset_a, int LDA, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DGEHRD reduces a real general matrix A to upper Hessenberg form H by an orthogonal similarity transformation: Q' * A * Q = H .
/summary>
Parameters
N (input) INTEGER The order of the matrix A. N .GE. 0. /param>
Parameters
ILO (input) INTEGER /param>
Parameters
IHI (input) INTEGER It is assumed that A is already upper triangular in rows and columns 1:ILO-1 and IHI+1:N. ILO and IHI are normally set by a previous call to DGEBAL; otherwise they should be set to 1 and N respectively. See Further Details. 1 .LE. ILO .LE. IHI .LE. N, if N .GT. 0; ILO=1 and IHI=0, if N=0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the N-by-N general matrix to be reduced. On exit, the upper triangle and the first subdiagonal of A are overwritten with the upper Hessenberg matrix H, and the elements below the first subdiagonal, with the array TAU, represent the orthogonal matrix Q as a product of elementary reflectors. See Further Details. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,N). /param>
Parameters
TAU (output) DOUBLE PRECISION array, dimension (N-1) The scalar factors of the elementary reflectors (see Further Details). Elements 1:ILO-1 and IHI:N-1 of TAU are set to zero. /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (LWORK) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The length of the array WORK. LWORK .GE. max(1,N). For optimum performance LWORK .GE. N*NB, where NB is the optimal blocksize.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value. /param>
References DotNumerics.LinearAlgebra.CSLapack.DGEHRD.LDT, DotNumerics.LinearAlgebra.CSLapack.DGEHRD.NBMAX, DotNumerics.LinearAlgebra.CSLapack.DGEHRD.ONE, DotNumerics.LinearAlgebra.CSLapack.DAXPY.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEHD2.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAHR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFB.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEHRD.T, and DotNumerics.LinearAlgebra.CSLapack.DGEHRD.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR2.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAQR3.Run().
Member Data Documentation
_daxpy
DAXPY DotNumerics.LinearAlgebra.CSLapack.DGEHRD._daxpy private
_dgehd2
DGEHD2 DotNumerics.LinearAlgebra.CSLapack.DGEHRD._dgehd2 private
_dgemm
DGEMM DotNumerics.LinearAlgebra.CSLapack.DGEHRD._dgemm private
_dlahr2
DLAHR2 DotNumerics.LinearAlgebra.CSLapack.DGEHRD._dlahr2 private
_dlarfb
DLARFB DotNumerics.LinearAlgebra.CSLapack.DGEHRD._dlarfb private
_dtrmm
DTRMM DotNumerics.LinearAlgebra.CSLapack.DGEHRD._dtrmm private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGEHRD._xerbla private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DGEHRD._ilaenv private
NBMAX
const int DotNumerics.LinearAlgebra.CSLapack.DGEHRD.NBMAX = 64 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEHRD.Run().
LDT
const int DotNumerics.LinearAlgebra.CSLapack.DGEHRD.LDT = NBMAX + 1 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEHRD.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DGEHRD.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEHRD.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGEHRD.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEHRD.Run().
T
double [] DotNumerics.LinearAlgebra.CSLapack.DGEHRD.T = new double[LDT * NBMAX] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEHRD.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgehrd.cs