Doc: IGLib EXTENDED: NUnit.Engine.Services.Tests.DomainManagerTests Class Reference
NUnit.Engine.Services.Tests.DomainManagerTests Class Reference
Public Member Functions
void CreateDomainManager ()
void ServiceIsStarted ()
void CanCreateDomain ()
void CanCreateDomainWithApplicationBaseSpecified ()
void CanUnloadDomain ()
void UnloadingTwiceDoesNoHarm ()
Private Member Functions
void CheckDomainIsUnloaded (AppDomain domain)
Private Attributes
DomainManager _domainManager
TestPackage _package = new TestPackage(MockAssembly.AssemblyPath)
Member Function Documentation
CreateDomainManager()
void NUnit.Engine.Services.Tests.DomainManagerTests.CreateDomainManager () inline
References NUnit.Engine.Services.Tests.DomainManagerTests._domainManager.
ServiceIsStarted()
void NUnit.Engine.Services.Tests.DomainManagerTests.ServiceIsStarted () inline
References NUnit.Engine.Services.Tests.DomainManagerTests._domainManager, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Services.Service.Status, and NUnit.Framework.Assert.That().
CanCreateDomain()
void NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomain () inline
References NUnit.Engine.Services.Tests.DomainManagerTests._domainManager, NUnit.Engine.Services.Tests.DomainManagerTests._package, NUnit.Framework.Assert.AreEqual(), NUnit.Tests.Assemblies.MockAssembly.AssemblyPath, NUnit.Engine.Services.DomainManager.CreateDomain(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.NotNull(), NUnit.Framework.Is.Null, NUnit.Framework.Is.SamePath(), NUnit.Framework.Does.StartWith(), and NUnit.Framework.Assert.That().
CanCreateDomainWithApplicationBaseSpecified()
void NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomainWithApplicationBaseSpecified () inline
References NUnit.Engine.Services.Tests.DomainManagerTests._domainManager, NUnit.Engine.Services.Tests.DomainManagerTests._package, NUnit.Engine.Services.DomainManager.CreateDomain(), NUnit.Framework.Is.EqualTo(), NUnit.Engine.TestPackage.FullName, NUnit.Framework.Assert.NotNull(), NUnit.Framework.Is.Null, NUnit.Framework.Is.SamePath(), NUnit.Engine.TestPackage.Settings, NUnit.Framework.Does.StartWith(), and NUnit.Framework.Assert.That().
CanUnloadDomain()
void NUnit.Engine.Services.Tests.DomainManagerTests.CanUnloadDomain () inline
References NUnit.Engine.Services.Tests.DomainManagerTests._domainManager, NUnit.Engine.Services.Tests.DomainManagerTests._package, NUnit.Engine.Services.Tests.DomainManagerTests.CheckDomainIsUnloaded(), NUnit.Engine.Services.DomainManager.CreateDomain(), and NUnit.Engine.Services.DomainManager.Unload().
UnloadingTwiceDoesNoHarm()
void NUnit.Engine.Services.Tests.DomainManagerTests.UnloadingTwiceDoesNoHarm () inline
References NUnit.Engine.Services.Tests.DomainManagerTests._domainManager, NUnit.Engine.Services.Tests.DomainManagerTests._package, NUnit.Engine.Services.Tests.DomainManagerTests.CheckDomainIsUnloaded(), NUnit.Engine.Services.DomainManager.CreateDomain(), and NUnit.Engine.Services.DomainManager.Unload().
CheckDomainIsUnloaded()
void NUnit.Engine.Services.Tests.DomainManagerTests.CheckDomainIsUnloaded (AppDomain domain) inline private
References NUnit.Framework.Assert.True().
Referenced by NUnit.Engine.Services.Tests.DomainManagerTests.CanUnloadDomain(), and NUnit.Engine.Services.Tests.DomainManagerTests.UnloadingTwiceDoesNoHarm().
Member Data Documentation
_domainManager
DomainManager NUnit.Engine.Services.Tests.DomainManagerTests._domainManager private
Referenced by NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomain(), NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomainWithApplicationBaseSpecified(), NUnit.Engine.Services.Tests.DomainManagerTests.CanUnloadDomain(), NUnit.Engine.Services.Tests.DomainManagerTests.CreateDomainManager(), NUnit.Engine.Services.Tests.DomainManagerTests.ServiceIsStarted(), and NUnit.Engine.Services.Tests.DomainManagerTests.UnloadingTwiceDoesNoHarm().
_package
TestPackage NUnit.Engine.Services.Tests.DomainManagerTests._package = new TestPackage(MockAssembly.AssemblyPath) private
Referenced by NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomain(), NUnit.Engine.Services.Tests.DomainManagerTests.CanCreateDomainWithApplicationBaseSpecified(), NUnit.Engine.Services.Tests.DomainManagerTests.CanUnloadDomain(), and NUnit.Engine.Services.Tests.DomainManagerTests.UnloadingTwiceDoesNoHarm().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Services/DomainManagerTests.cs