Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DORGTR Class Reference
DotNumerics.LinearAlgebra.CSLapack.DORGTR Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DORGTR (LSAME lsame, ILAENV ilaenv, DORGQL dorgql, DORGQR dorgqr, XERBLA xerbla)
DORGTR ()
void Run (string UPLO, int N, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
LSAME _lsame
ILAENV _ilaenv
DORGQL _dorgql
DORGQR _dorgqr
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DORGTR generates a real orthogonal matrix Q which is defined as the product of n-1 elementary reflectors of order N, as returned by DSYTRD:
if UPLO = 'U', Q = H(n-1) . . . H(2) H(1),
if UPLO = 'L', Q = H(1) H(2) . . . H(n-1).
/summary>
Constructor & Destructor Documentation
DORGTR() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DORGTR.DORGTR (LSAME lsame, ILAENV ilaenv, DORGQL dorgql, DORGQR dorgqr, XERBLA xerbla) inline
DORGTR() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DORGTR.DORGTR () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DORGTR.Run (string UPLO, int N, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DORGTR generates a real orthogonal matrix Q which is defined as the product of n-1 elementary reflectors of order N, as returned by DSYTRD:
if UPLO = 'U', Q = H(n-1) . . . H(2) H(1),
if UPLO = 'L', Q = H(1) H(2) . . . H(n-1).
/summary>
Parameters
UPLO (input) CHARACTER*1 = 'U': Upper triangle of A contains elementary reflectors from DSYTRD; = 'L': Lower triangle of A contains elementary reflectors from DSYTRD. /param>
Parameters
N (input) INTEGER The order of the matrix Q. N .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the vectors which define the elementary reflectors, as returned by DSYTRD. On exit, the N-by-N orthogonal matrix Q. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,N). /param>
Parameters
TAU (input) DOUBLE PRECISION array, dimension (N-1) TAU(i) must contain the scalar factor of the elementary reflector H(i), as returned by DSYTRD. /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. max(1,N-1). For optimum performance LWORK .GE. (N-1)*NB, where NB is the optimal blocksize.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.DORGTR.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGQL.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DORGTR.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYEV.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DORGTR._lsame private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DORGTR._ilaenv private
_dorgql
DORGQL DotNumerics.LinearAlgebra.CSLapack.DORGTR._dorgql private
_dorgqr
DORGQR DotNumerics.LinearAlgebra.CSLapack.DORGTR._dorgqr private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DORGTR._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DORGTR.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORGTR.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DORGTR.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORGTR.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dorgtr.cs