Doc: IGLib EXTENDED: IG.Script.Script_Numeric Class Reference
IG.Script.Script_Numeric Class Reference
Public Member Functions
Script_Numeric ()
override void Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings)
Adds commands to the internal interpreter.
string TestScriptArguments (string[] arguments)
Simple test, just writes script arguments to console.
string TestCustom (string[] arguments)
Test of matrix operations (decompositions, etc.).
string TestMatrixOperations (string[] arguments)
Test of matrix operations (decompositions, etc.).
string TestRealFunction (string[] arguments)
Test of real functions of one variable.
string TestDifferentiation (string[] arguments)
Test of numerical differentiation.
string TestLinearApproximation (string[] arguments)
Test of linear approximations.
string TestMovingLeastSquares (string[] arguments)
Test of linear approximations.
string TestPerformanceTests (string[] arguments)
Test of various performance tests.
string TestTabResults (string[] arguments)
Test of tables of results (e.g. tables of approximated values or of optimization analysis results).
string TestParallelJobs (string[] arguments)
Test of parallel jobs.
string TestSampling (string[] arguments)
Test of various sampling algorithms.
string TestOptAlglib (string[] arguments)
Test of AlgLib optimization algorithms.
Public Member Functions inherited from IG.Lib.LoadableScriptBase
LoadableScriptBase ()
Argument-less constructor. If argument-less constructor is called then initialization is not performed and will be performed later.
string Run (string[] arguments)
Performs the action of this object. Override this in derived classes!
void Initialize (string[] arguments)
Initializes the object. If not called explicitly, this method is automatically called at the first call to the Run method.
virtual string Script_DefaultInitialize (string[] arguments)
Default initialization method for scripts.
virtual string Script_DefaultRun (string[] arguments)
Default run method for the script. Can be used when only installed commands are run by hte script.
virtual ICommandLineApplicationInterpreter Script_CreateInterpreterWithoutCommands ()
Creates and returns an interpreter that can be used as script's internal interpreter for running script's commands.
delegate string Script_CommandDelegate (string[] args)
Delegate for commands that are installed on script's internal interpreter (property Script_Interpreter).
void Script_AddCommand (string commandName, Script_CommandDelegate command, string helpString)
Adds a new internal script command under specified name to the internal interpreter of the current script object.
virtual void Script_AddCommand (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings, string commandName, Script_CommandDelegate command, string helpString)
Adds a new internal script command under specified name to the internal interpreter of the current script object.
string Script_GetHelpString (string scriptCommandName)
Returns help string for internal script command with specified name, or null if help string is not installed for such a command.
void Script_PrintCommandsHelp ()
Prits help for the installed internal commands of the script.
virtual bool Script_ContainsCommand (string commandName)
Returns true if the internal script's interpreter contains a command with specified name, false otherwise.
virtual bool Script_ContainsScriptCommand (string commandName)
Returns true if the specified command is script command (i.e. its first argument is command-name and it is run through the Script_CommandAdapter object).
virtual void Script_RemoveCommand (string commandName)
Removes the specified internal script command from the internal interpreter of the current scripting object.
virtual void Script_RemoveAllCommands ()
Removes ALL internal script commands from the internal interpreter of the current scripting object.
string Script_Run (string[] arguments)
Runs internal script command.
string Script_Run (string commandName, params string[] otherArguments)
Runs internal script command.
virtual void Script_PrintArguments (string messageString, string[] arguments)
Prints the specified array of string arguments (usually passed as command-line arguments).
Static Public Attributes
const string ConstTestScriptArguments = "Test1"
Test of running the script, writes arguments.
const string ConstHelpTestScriptArguments = "Performs test , outputs script arguments."
const string ConstCustom = "CustomTest"
Custom test.
const string ConstHelpCustom = "Custom test."
const string ConstMatrixOperations = "MatrixOperations"
Tests of matrix operations.
const string ConstHelpMatrixOperations = "Tests of matrix operations."
const string ConstPerformanceTests = "PerformanceTests"
Test of real functions of one variable.
const string ConstHelpPerformanceTests = "Tests of various performance tests."
const string ConstRealFunction = "RealFunction"
Test of real functions of one variable.
const string ConstHelpRealFunction = "Tests of real function of one variable."
const string ConstDifferentiation = "Differentiation"
Test of numerical differentiation.
const string ConstHelpDifferentiation = "Tests of numerical differentiation."
const string ConstLinearApproximation = "LinearApproximation"
Test of linear approximation.
const string ConstHelpLinearApproximation = "Tests of linear approximations."
const string ConstMovingLeastSquares = "MovingLeastSquares"
Test of moving least squares.
const string ConstHelpMovingLeastSquares = "Tests of the moving least squares method."
const string ConstTabResults = "TabResults"
Test of result tables.
const string ConstHelpTabResults = "Demonstrations of linear reault tables."
const string ConstParallelJobs = "ParallelJobs"
Tests parallel job dispatcher.
const string ConstHelpParallelJobs = "Testing of parallel job dispatcher."
const string ConstSampling = "Sampling"
Tests sampling algorithms.
const string ConstHelpSampling = "Testing of various sampling algorithms."
const string ConstOptAlgLib = "OptAlgLib"
Tests Alglib optimization algorithms.
const string ConstHelpOptAlgLib = "Testing of AlgLib's optimization algorithms."
Static Public Attributes inherited from IG.Lib.LoadableScriptBase
const string ConstDefaultHelp = "Help"
Default command name for help.
const string ConstHelpDefaultUniversal = "?"
Universal name of the help command.
const string ConstDefaultTestScrip = "TestScript"
Default command name for test method.
Protected Member Functions
override void InitializeThis (string[] arguments)
Initializes the current object.
override string RunThis (string[] arguments)
Runs action of the current object.
Protected Member Functions inherited from IG.Lib.LoadableScriptBase
delegate string CommandMethod (string commandName, string[] args)
Delegate for internal command methods.
ICommandLineApplicationInterpreter Script_CreateInterpreter ()
Creates and returns an interpreter that can be used as script's internal interpreter for running script's commands.
virtual string Script_CommandHelp (string[] arguments)
Prints help.
virtual string Script_CommandTestScript (string[] arguments)
Prints help.
Additional Inherited Members
Protected Attributes inherited from IG.Lib.LoadableScriptBase
string _embeddedCommandName = null
int _outputLevel = DefaultOutputLevel
ICommandLineApplicationInterpreter _script_interpreter
Properties inherited from IG.Lib.LoadableScriptBase
string EmbeddedCommandName [get, set]
Command that was used to launch the current embedded application script.
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
string[] InitializationArguments [get, set]
Arguments used by the initialization method. WARNING: arguments can only be set before initialization is performed. Initialization is performed either implicitly at the first call to the Run method or explicitly by calling the Initialize method.
virtual bool IsInitialized [get, protected set]
Whether the object has been initialized or not.
static int DefaultOutputLevel [get, set]
int OutputLevel [get, set]
Level of output to console produced by some operations of the current object.
virtual ICommandLineApplicationInterpreter Script_Interpreter [get, protected set]
Script's internal interpreter that takes care for execution of installed internal commands.
SortedList< string, string > Script_CommandHelpStrings [get]
Contains help strings associated with script commands installed on interpreter.
Properties inherited from IG.Lib.ILoadableScript
string EmbeddedCommandName [get, set]
Command that was used to launch the current embedded application script.
string[] InitializationArguments [get, set]
Arguments used by the initialization method.
bool IsInitialized [get]
Whether the object has been initialized or not.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Constructor & Destructor Documentation
Script_Numeric()
IG.Script.Script_Numeric.Script_Numeric () inline
Member Function Documentation
InitializeThis()
override void IG.Script.Script_Numeric.InitializeThis (string[] arguments) inline protected virtual
Initializes the current object.
Implements IG.Lib.LoadableScriptBase.
RunThis()
override string IG.Script.Script_Numeric.RunThis (string[] arguments) inline protected virtual
Runs action of the current object.
Parameters
arguments Command-line arguments of the action.
Implements IG.Lib.LoadableScriptBase.
References IG.Lib.LoadableScriptBase.Script_DefaultRun().
Script_AddCommands()
override void IG.Script.Script_Numeric.Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings) inline virtual
Adds commands to the internal interpreter.
Parameters
interpreter Interpreter where commands are executed.
helpStrings List containg help strings.
Reimplemented from IG.Lib.LoadableScriptBase.
References IG.Script.Script_Numeric.ConstCustom, IG.Script.Script_Numeric.ConstDifferentiation, IG.Script.Script_Numeric.ConstHelpCustom, IG.Script.Script_Numeric.ConstHelpDifferentiation, IG.Script.Script_Numeric.ConstHelpLinearApproximation, IG.Script.Script_Numeric.ConstHelpMatrixOperations, IG.Script.Script_Numeric.ConstHelpMovingLeastSquares, IG.Script.Script_Numeric.ConstHelpOptAlgLib, IG.Script.Script_Numeric.ConstHelpParallelJobs, IG.Script.Script_Numeric.ConstHelpPerformanceTests, IG.Script.Script_Numeric.ConstHelpRealFunction, IG.Script.Script_Numeric.ConstHelpSampling, IG.Script.Script_Numeric.ConstHelpTabResults, IG.Script.Script_Numeric.ConstHelpTestScriptArguments, IG.Script.Script_Numeric.ConstLinearApproximation, IG.Script.Script_Numeric.ConstMatrixOperations, IG.Script.Script_Numeric.ConstMovingLeastSquares, IG.Script.Script_Numeric.ConstOptAlgLib, IG.Script.Script_Numeric.ConstParallelJobs, IG.Script.Script_Numeric.ConstPerformanceTests, IG.Script.Script_Numeric.ConstRealFunction, IG.Script.Script_Numeric.ConstSampling, IG.Script.Script_Numeric.ConstTabResults, IG.Script.Script_Numeric.ConstTestScriptArguments, IG.Lib.LoadableScriptBase.Script_AddCommand(), IG.Script.Script_Numeric.TestCustom(), IG.Script.Script_Numeric.TestDifferentiation(), IG.Script.Script_Numeric.TestLinearApproximation(), IG.Script.Script_Numeric.TestMatrixOperations(), IG.Script.Script_Numeric.TestMovingLeastSquares(), IG.Script.Script_Numeric.TestOptAlglib(), IG.Script.Script_Numeric.TestParallelJobs(), IG.Script.Script_Numeric.TestPerformanceTests(), IG.Script.Script_Numeric.TestRealFunction(), IG.Script.Script_Numeric.TestSampling(), IG.Script.Script_Numeric.TestScriptArguments(), and IG.Script.Script_Numeric.TestTabResults().
TestScriptArguments()
string IG.Script.Script_Numeric.TestScriptArguments (string[] arguments) inline
Simple test, just writes script arguments to console.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Lib.LoadableScriptBase.Script_CommandTestScript().
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
TestCustom()
string IG.Script.Script_Numeric.TestCustom (string[] arguments) inline
Test of matrix operations (decompositions, etc.).
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Num.M.CheckFactorialsArray(), IG.Num.M.TestBinomialCoefficients(), and IG.Num.M.TestFactorials().
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
TestMatrixOperations()
string IG.Script.Script_Numeric.TestMatrixOperations (string[] arguments) inline
Test of matrix operations (decompositions, etc.).
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Num.SpeedTestCpu.ExampleMathNetNumericsEVD(), IG.Num.MatrixBase.SetRandomSymmetricPositiveDefinite(), IG.Num.SpeedTestCpu.TestComputationalTimesCholesky(), IG.Num.SpeedTestCpu.TestComputationalTimesLU(), IG.Num.SpeedTestCpu.TestComputationalTimesQR(), and IG.Num.MatrixBaseDev.TestMatrixDecompositions().
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
TestRealFunction()
string IG.Script.Script_Numeric.TestRealFunction (string[] arguments) inline
Test of real functions of one variable.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Num.RealFunctionBase.ExampleTests(), and IG.Num.RealFunction.TestSpeed().
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
TestDifferentiation()
string IG.Script.Script_Numeric.TestDifferentiation (string[] arguments) inline
Test of numerical differentiation.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Num.Numeric.TestDifferentiation().
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
TestLinearApproximation()
string IG.Script.Script_Numeric.TestLinearApproximation (string[] arguments) inline
Test of linear approximations.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Num.LinearBasis.Example().
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
TestMovingLeastSquares()
string IG.Script.Script_Numeric.TestMovingLeastSquares (string[] arguments) inline
Test of linear approximations.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
TestPerformanceTests()
string IG.Script.Script_Numeric.TestPerformanceTests (string[] arguments) inline
Test of various performance tests.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Lib.ThreadPerformanceTest.Example().
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
TestTabResults()
string IG.Script.Script_Numeric.TestTabResults (string[] arguments) inline
Test of tables of results (e.g. tables of approximated values or of optimization analysis results).
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Num.AnalysisTable.ExampleTableFactors().
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
TestParallelJobs()
string IG.Script.Script_Numeric.TestParallelJobs (string[] arguments) inline
Test of parallel jobs.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Num.ParallelJobContainerBase.DefaultOutputLevel, and IG.Num.ParallelJobContainerBase.TestPerformance().
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
TestSampling()
string IG.Script.Script_Numeric.TestSampling (string[] arguments) inline
Test of various sampling algorithms.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Num.SamplerUnitBallRandomFromCube.TestSamplingSpeed().
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
TestOptAlglib()
string IG.Script.Script_Numeric.TestOptAlglib (string[] arguments) inline
Test of AlgLib optimization algorithms.
Parameters
arguments Array of command-line arguments.
Returns
The null string.
References IG.Num.TestAlgLibBase2008.DefaultOutputLevel, and IG.Num.TestAlglibOld2008.TestLbfgsAlglibOld().
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
Member Data Documentation
ConstTestScriptArguments
const string IG.Script.Script_Numeric.ConstTestScriptArguments = "Test1" static
Test of running the script, writes arguments.
Referenced by IG.Script.Script_Numeric.Script_AddCommands(), TestOpt.IGLibShellExtMainProgram.TestMain(), and TestOpt.IGLibShellMainProgram.TestMain().
ConstHelpTestScriptArguments
const string IG.Script.Script_Numeric.ConstHelpTestScriptArguments = "Performs test , outputs script arguments." static
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
ConstCustom
const string IG.Script.Script_Numeric.ConstCustom = "CustomTest" static
Custom test.
Referenced by IG.Script.Script_Numeric.Script_AddCommands(), TestOpt.IGLibShellExtMainProgram.TestMain(), and TestOpt.IGLibShellMainProgram.TestMain().
ConstHelpCustom
const string IG.Script.Script_Numeric.ConstHelpCustom = "Custom test." static
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
ConstMatrixOperations
const string IG.Script.Script_Numeric.ConstMatrixOperations = "MatrixOperations" static
Tests of matrix operations.
Referenced by IG.Script.Script_Numeric.Script_AddCommands(), TestOpt.IGLibShellExtMainProgram.TestMain(), and TestOpt.IGLibShellMainProgram.TestMain().
ConstHelpMatrixOperations
const string IG.Script.Script_Numeric.ConstHelpMatrixOperations = "Tests of matrix operations." static
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
ConstPerformanceTests
const string IG.Script.Script_Numeric.ConstPerformanceTests = "PerformanceTests" static
Test of real functions of one variable.
Referenced by IG.Script.Script_Numeric.Script_AddCommands(), TestOpt.IGLibShellExtMainProgram.TestMain(), and TestOpt.IGLibShellMainProgram.TestMain().
ConstHelpPerformanceTests
const string IG.Script.Script_Numeric.ConstHelpPerformanceTests = "Tests of various performance tests." static
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
ConstRealFunction
const string IG.Script.Script_Numeric.ConstRealFunction = "RealFunction" static
Test of real functions of one variable.
Referenced by IG.Script.Script_Numeric.Script_AddCommands(), TestOpt.IGLibShellExtMainProgram.TestMain(), and TestOpt.IGLibShellMainProgram.TestMain().
ConstHelpRealFunction
const string IG.Script.Script_Numeric.ConstHelpRealFunction = "Tests of real function of one variable." static
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
ConstDifferentiation
const string IG.Script.Script_Numeric.ConstDifferentiation = "Differentiation" static
Test of numerical differentiation.
Referenced by IG.Script.Script_Numeric.Script_AddCommands(), TestOpt.IGLibShellExtMainProgram.TestMain(), and TestOpt.IGLibShellMainProgram.TestMain().
ConstHelpDifferentiation
const string IG.Script.Script_Numeric.ConstHelpDifferentiation = "Tests of numerical differentiation." static
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
ConstLinearApproximation
const string IG.Script.Script_Numeric.ConstLinearApproximation = "LinearApproximation" static
Test of linear approximation.
Referenced by IG.Script.Script_Numeric.Script_AddCommands(), TestOpt.IGLibShellExtMainProgram.TestMain(), and TestOpt.IGLibShellMainProgram.TestMain().
ConstHelpLinearApproximation
const string IG.Script.Script_Numeric.ConstHelpLinearApproximation = "Tests of linear approximations." static
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
ConstMovingLeastSquares
const string IG.Script.Script_Numeric.ConstMovingLeastSquares = "MovingLeastSquares" static
Test of moving least squares.
Referenced by IG.Script.Script_Numeric.Script_AddCommands(), TestOpt.IGLibShellExtMainProgram.TestMain(), and TestOpt.IGLibShellMainProgram.TestMain().
ConstHelpMovingLeastSquares
const string IG.Script.Script_Numeric.ConstHelpMovingLeastSquares = "Tests of the moving least squares method." static
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
ConstTabResults
const string IG.Script.Script_Numeric.ConstTabResults = "TabResults" static
Test of result tables.
Referenced by IG.Script.Script_Numeric.Script_AddCommands(), TestOpt.IGLibShellExtMainProgram.TestMain(), and TestOpt.IGLibShellMainProgram.TestMain().
ConstHelpTabResults
const string IG.Script.Script_Numeric.ConstHelpTabResults = "Demonstrations of linear reault tables." static
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
ConstParallelJobs
const string IG.Script.Script_Numeric.ConstParallelJobs = "ParallelJobs" static
Tests parallel job dispatcher.
Referenced by IG.Script.Script_Numeric.Script_AddCommands(), TestOpt.IGLibShellExtMainProgram.TestMain(), and TestOpt.IGLibShellMainProgram.TestMain().
ConstHelpParallelJobs
const string IG.Script.Script_Numeric.ConstHelpParallelJobs = "Testing of parallel job dispatcher." static
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
ConstSampling
const string IG.Script.Script_Numeric.ConstSampling = "Sampling" static
Tests sampling algorithms.
Referenced by IG.Script.Script_Numeric.Script_AddCommands(), TestOpt.IGLibShellExtMainProgram.TestMain(), and TestOpt.IGLibShellMainProgram.TestMain().
ConstHelpSampling
const string IG.Script.Script_Numeric.ConstHelpSampling = "Testing of various sampling algorithms." static
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
ConstOptAlgLib
const string IG.Script.Script_Numeric.ConstOptAlgLib = "OptAlgLib" static
Tests Alglib optimization algorithms.
Referenced by IG.Script.Script_Numeric.Script_AddCommands(), TestOpt.IGLibShellExtMainProgram.TestMain(), and TestOpt.IGLibShellMainProgram.TestMain().
ConstHelpOptAlgLib
const string IG.Script.Script_Numeric.ConstHelpOptAlgLib = "Testing of AlgLib's optimization algorithms." static
Referenced by IG.Script.Script_Numeric.Script_AddCommands().
The documentation for this class was generated from the following file:
igtest/IGLibTestShell/00testscriptsopt/tests/Script_Numeric.cs