Doc: IGLib EXTENDED: AForge.Imaging.Filters.AdditiveNoise Class Reference
AForge.Imaging.Filters.AdditiveNoise Class Reference
Additive noise filter.
Public Member Functions
AdditiveNoise ()
Initializes a new instance of the AdditiveNoise class.
AdditiveNoise (IRandomNumberGenerator generator)
Initializes a new instance of the AdditiveNoise class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image, Rectangle rect)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
IRandomNumberGenerator Generator [get, set]
Random number genertor used to add noise.
Properties inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
IRandomNumberGenerator generator = new UniformGenerator(new Range(-10, 10))
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Additive noise filter.
The filter adds random value to each pixel of the source image. The distribution of random values can be specified by random generator.
The filter accepts 8 bpp grayscale images and 24 bpp color images for processing.
Sample usage:
// create random generator
IRandomNumberGenerator generator = new UniformGenerator(new Range(-50, 50));
// create filter
AdditiveNoise filter = new AdditiveNoise(generator);
// apply the filter
filter.ApplyInPlace(image);
Initial image:
Result image:
Constructor & Destructor Documentation
AdditiveNoise() [1/2]
AForge.Imaging.Filters.AdditiveNoise.AdditiveNoise () inline
Initializes a new instance of the AdditiveNoise class.
References AForge.Imaging.Filters.AdditiveNoise.formatTranslations.
AdditiveNoise() [2/2]
AForge.Imaging.Filters.AdditiveNoise.AdditiveNoise (IRandomNumberGenerator generator) inline
Initializes a new instance of the AdditiveNoise class.
Parameters
generator Random number genertor used to add noise.
References AForge.Imaging.Filters.AdditiveNoise.generator.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.AdditiveNoise.ProcessFilter (UnmanagedImage image, Rectangle rect) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
rect Image rectangle for processing by the filter.
Implements AForge.Imaging.Filters.BaseInPlacePartialFilter.
References AForge.Imaging.Filters.AdditiveNoise.generator, AForge.Imaging.UnmanagedImage.ImageData, AForge.Math.Random.IRandomNumberGenerator.Next(), AForge.Imaging.UnmanagedImage.PixelFormat, and AForge.Imaging.UnmanagedImage.Stride.
Member Data Documentation
generator
IRandomNumberGenerator AForge.Imaging.Filters.AdditiveNoise.generator = new UniformGenerator(new Range(-10, 10)) private
Referenced by AForge.Imaging.Filters.AdditiveNoise.AdditiveNoise(), and AForge.Imaging.Filters.AdditiveNoise.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.AdditiveNoise.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.AdditiveNoise.AdditiveNoise().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.AdditiveNoise.FormatTranslations get
Format translations dictionary.
Generator
IRandomNumberGenerator AForge.Imaging.Filters.AdditiveNoise.Generator get set
Random number genertor used to add noise.
Default generator is uniform generator in the range of (-10, 10).
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Noise generation/AdditiveNoise.cs