Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DORGL2 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DORGL2 Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DORGL2 (DLARF dlarf, DSCAL dscal, XERBLA xerbla)
DORGL2 ()
void Run (int M, int N, int K, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
DLARF _dlarf
DSCAL _dscal
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DORGL2 generates an m by n real matrix Q with orthonormal rows, which is defined as the first m rows of a product of k elementary reflectors of order n
Q = H(k) . . . H(2) H(1)
as returned by DGELQF.
/summary>
Constructor & Destructor Documentation
DORGL2() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DORGL2.DORGL2 (DLARF dlarf, DSCAL dscal, XERBLA xerbla) inline
DORGL2() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DORGL2.DORGL2 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DORGL2.Run (int M, int N, int K, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
DORGL2 generates an m by n real matrix Q with orthonormal rows, which is defined as the first m rows of a product of k elementary reflectors of order n
Q = H(k) . . . H(2) H(1)
as returned by DGELQF.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix Q. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix Q. N .GE. M. /param>
Parameters
K (input) INTEGER The number of elementary reflectors whose product defines the matrix Q. M .GE. K .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the i-th row must contain the vector which defines the elementary reflector H(i), for i = 1,2,...,k, as returned by DGELQF in the first k rows of its array argument A. On exit, the m-by-n matrix Q. /param>
Parameters
LDA (input) INTEGER The first dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
TAU (input) DOUBLE PRECISION array, dimension (K) TAU(i) must contain the scalar factor of the elementary reflector H(i), as returned by DGELQF. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (M) /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument has an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.DORGL2.ONE, DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARF.Run(), and DotNumerics.LinearAlgebra.CSLapack.DORGL2.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORGLQ.Run().
Member Data Documentation
_dlarf
DLARF DotNumerics.LinearAlgebra.CSLapack.DORGL2._dlarf private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DORGL2._dscal private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DORGL2._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DORGL2.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORGL2.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DORGL2.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORGL2.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dorgl2.cs