Doc: IGLib EXTENDED: NUnit.ConsoleRunner.Tests.ColorConsoleTests Class Reference
NUnit.ConsoleRunner.Tests.ColorConsoleTests Class Reference
Public Member Functions
void SetUp ()
void TearDown ()
void TestConstructor ()
Private Attributes
ColorStyle _testStyle
Member Function Documentation
SetUp()
void NUnit.ConsoleRunner.Tests.ColorConsoleTests.SetUp () inline
References NUnit.ConsoleRunner.Tests.ColorConsoleTests._testStyle, NUnit.Framework.Is.EqualTo(), NUnit.Common.ColorConsole.GetColor(), NUnit.Framework.Assert.Inconclusive(), and NUnit.Framework.Assume.That().
TearDown()
void NUnit.ConsoleRunner.Tests.ColorConsoleTests.TearDown () inline
TestConstructor()
void NUnit.ConsoleRunner.Tests.ColorConsoleTests.TestConstructor () inline
References NUnit.ConsoleRunner.Tests.ColorConsoleTests._testStyle, NUnit.Framework.Is.EqualTo(), NUnit.Common.ColorConsole.GetColor(), NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
Member Data Documentation
_testStyle
ColorStyle NUnit.ConsoleRunner.Tests.ColorConsoleTests._testStyle private
Referenced by NUnit.ConsoleRunner.Tests.ColorConsoleTests.SetUp(), and NUnit.ConsoleRunner.Tests.ColorConsoleTests.TestConstructor().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitConsole/nunit3-console.tests/ColorConsoleTests.cs