Doc: IGLib EXTENDED: AForge.Imaging.Filters.ExtractBiggestBlob Class Reference
AForge.Imaging.Filters.ExtractBiggestBlob Class Reference
Extract the biggest blob from image.
Public Member Functions
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image (not implemented).
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image (not implemented).
Properties
IntPoint BlobPosition [get]
Position of the extracted blob.
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Bitmap OriginalImage [get, set]
Original image, which is the source of the processed image where the biggest blob is searched for.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
Bitmap originalImage = null
IntPoint blobPosition
Detailed Description
Extract the biggest blob from image.
The filter locates the biggest blob in the source image and extracts it. The filter also can use the source image for the biggest blob's location only, but extract it from another image, which is set using OriginalImage property. The original image usually is the source of the processed image.
The filter accepts 8 bpp grayscale images and 24/32 color images for processing as source image passed to Apply(Bitmap) method and also for the OriginalImage.
Sample usage:
// create filter
ExtractBiggestBlob filter = new ExtractBiggestBlob();
// apply the filter
Bitmap biggestBlobsImage = filter.Apply(image);
Initial image:
Result image:
Member Function Documentation
Apply() [1/4]
Bitmap AForge.Imaging.Filters.ExtractBiggestBlob.Apply (Bitmap image) inline
Apply filter to an image.
Parameters
image Source image to get biggest blob from.
Returns
Returns image of the biggest blob.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
UnsupportedImageFormatException Unsupported pixel format of the original image.
InvalidImagePropertiesException Source and original images must have the same size.
ArgumentException The source image does not contain any blobs.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Math.Geometry.Rectangle.
Apply() [2/4]
Bitmap AForge.Imaging.Filters.ExtractBiggestBlob.Apply (BitmapData imageData) inline
Apply filter to an image.
Parameters
imageData Source image to get biggest blob from.
Returns
Returns image of the biggest blob.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
UnsupportedImageFormatException Unsupported pixel format of the original image.
InvalidImagePropertiesException Source and original images must have the same size.
ArgumentException The source image does not contain any blobs.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.ExtractBiggestBlob.blobPosition, AForge.Imaging.UnmanagedImage.Dispose(), AForge.Imaging.BlobCounterBase.ExtractBlobsImage(), AForge.Imaging.Filters.ExtractBiggestBlob.FormatTranslations, AForge.Imaging.BlobCounterBase.GetObjectsInformation(), AForge.Imaging.Blob.Image, AForge.Imaging.Filters.ExtractBiggestBlob.originalImage, AForge.Imaging.Blob.Rectangle, and AForge.Imaging.UnmanagedImage.ToManagedImage().
Apply() [3/4]
UnmanagedImage AForge.Imaging.Filters.ExtractBiggestBlob.Apply (UnmanagedImage image) inline
Apply filter to an image (not implemented).
Parameters
image Image in unmanaged memory.
Returns
Returns filter's result obtained by applying the filter to the source image.
Exceptions
NotImplementedException The method is not implemented.
Implements AForge.Imaging.Filters.IFilter.
Apply() [4/4]
void AForge.Imaging.Filters.ExtractBiggestBlob.Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage) inline
Apply filter to an image (not implemented).
Parameters
sourceImage Source image to be processed.
destinationImage Destination image to store filter's result.
Exceptions
NotImplementedException The method is not implemented.
Implements AForge.Imaging.Filters.IFilter.
Member Data Documentation
originalImage
Bitmap AForge.Imaging.Filters.ExtractBiggestBlob.originalImage = null private
Referenced by AForge.Imaging.Filters.ExtractBiggestBlob.Apply().
blobPosition
IntPoint AForge.Imaging.Filters.ExtractBiggestBlob.blobPosition private
Referenced by AForge.Imaging.Filters.ExtractBiggestBlob.Apply().
Property Documentation
BlobPosition
IntPoint AForge.Imaging.Filters.ExtractBiggestBlob.BlobPosition get
Position of the extracted blob.
After applying the filter this property keeps position of the extracted blob in the source image.
FormatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.ExtractBiggestBlob.FormatTranslations get
Format translations dictionary.
The dictionary defines, which pixel formats are supported for source images and which pixel format will be used for resulting image.
See IFilterInformation.FormatTranslations for more information.
Referenced by AForge.Imaging.Filters.ExtractBiggestBlob.Apply().
OriginalImage
Bitmap AForge.Imaging.Filters.ExtractBiggestBlob.OriginalImage get set
Original image, which is the source of the processed image where the biggest blob is searched for.
The property may be set to null. In this case the biggest blob is extracted from the image, which is passed to Apply(Bitmap) image.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Other/ExtractBiggestBlob.cs