Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DTGSJA Class Reference
DotNumerics.LinearAlgebra.CSLapack.DTGSJA Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DTGSJA (LSAME lsame, DCOPY dcopy, DLAGS2 dlags2, DLAPLL dlapll, DLARTG dlartg, DLASET dlaset, DROT drot, DSCAL dscal, XERBLA xerbla)
DTGSJA ()
void Run (string JOBU, string JOBV, string JOBQ, int M, int P, int N, int K, int L, ref double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB, double TOLA, double TOLB, ref double[] ALPHA, int offset_alpha, ref double[] BETA, int offset_beta, ref double[] U, int offset_u, int LDU, ref double[] V, int offset_v, int LDV, ref double[] Q, int offset_q, int LDQ, ref double[] WORK, int offset_work, ref int NCYCLE, ref int INFO)
Private Attributes
LSAME _lsame
DCOPY _dcopy
DLAGS2 _dlags2
DLAPLL _dlapll
DLARTG _dlartg
DLASET _dlaset
DROT _drot
DSCAL _dscal
XERBLA _xerbla
Static Private Attributes
const int MAXIT = 40
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DTGSJA computes the generalized singular value decomposition (GSVD) of two real upper triangular (or trapezoidal) matrices A and B.
On entry, it is assumed that matrices A and B have the following forms, which may be obtained by the preprocessing subroutine DGGSVP from a general M-by-N matrix A and P-by-N matrix B:
N-K-L K L A = K (0 A12 A13) if M-K-L .GE. 0; L (0 0 A23) M-K-L (0 0 0)
N-K-L K L A = K (0 A12 A13) if M-K-L .LT. 0; M-K (0 0 A23)
N-K-L K L B = L (0 0 B13) P-L (0 0 0)
where the K-by-K matrix A12 and L-by-L matrix B13 are nonsingular upper triangular; A23 is L-by-L upper triangular if M-K-L .GE. 0, otherwise A23 is (M-K)-by-L upper trapezoidal.
On exit,
U'A*Q = D1(0 R), V'B*Q = D2(0 R),
where U, V and Q are orthogonal matrices, Z' denotes the transpose of Z, R is a nonsingular upper triangular matrix, and D1 and D2 are `‘diagonal’' matrices, which are of the following structures:
If M-K-L .GE. 0,
K L D1 = K (I 0) L (0 C) M-K-L (0 0)
K L D2 = L (0 S) P-L (0 0)
N-K-L K L (0 R) = K (0 R11 R12) K L (0 0 R22) L
where
C = diag(ALPHA(K+1), ... , ALPHA(K+L)), S = diag(BETA(K+1), ... , BETA(K+L)), C**2 + S**2 = I.
R is stored in A(1:K+L,N-K-L+1:N) on exit.
If M-K-L .LT. 0,
K M-K K+L-M D1 = K (I 0 0) M-K (0 C 0)
K M-K K+L-M D2 = M-K (0 S 0) K+L-M (0 0 I) P-L (0 0 0)
N-K-L K M-K K+L-M (0 R) = K (0 R11 R12 R13) M-K (0 0 R22 R23) K+L-M (0 0 0 R33)
where C = diag(ALPHA(K+1), ... , ALPHA(M)), S = diag(BETA(K+1), ... , BETA(M)), C**2 + S**2 = I.
R = (R11 R12 R13) is stored in A(1:M, N-K-L+1:N) and R33 is stored (0 R22 R23) in B(M-K+1:L,N+M-K-L+1:N) on exit.
The computation of the orthogonal transformation matrices U, V or Q is optional. These matrices may either be formed explicitly, or they may be postmultiplied into input matrices U1, V1, or Q1.
/summary>
Constructor & Destructor Documentation
DTGSJA() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DTGSJA.DTGSJA (LSAME lsame, DCOPY dcopy, DLAGS2 dlags2, DLAPLL dlapll, DLARTG dlartg, DLASET dlaset, DROT drot, DSCAL dscal, XERBLA xerbla) inline
DTGSJA() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DTGSJA.DTGSJA () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DTGSJA.Run (string JOBU, string JOBV, string JOBQ, int M, int P, int N, int K, int L, ref double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB, double TOLA, double TOLB, ref double[] ALPHA, int offset_alpha, ref double[] BETA, int offset_beta, ref double[] U, int offset_u, int LDU, ref double[] V, int offset_v, int LDV, ref double[] Q, int offset_q, int LDQ, ref double[] WORK, int offset_work, ref int NCYCLE, ref int INFO) inline
Purpose
DTGSJA computes the generalized singular value decomposition (GSVD) of two real upper triangular (or trapezoidal) matrices A and B.
On entry, it is assumed that matrices A and B have the following forms, which may be obtained by the preprocessing subroutine DGGSVP from a general M-by-N matrix A and P-by-N matrix B:
N-K-L K L A = K (0 A12 A13) if M-K-L .GE. 0; L (0 0 A23) M-K-L (0 0 0)
N-K-L K L A = K (0 A12 A13) if M-K-L .LT. 0; M-K (0 0 A23)
N-K-L K L B = L (0 0 B13) P-L (0 0 0)
where the K-by-K matrix A12 and L-by-L matrix B13 are nonsingular upper triangular; A23 is L-by-L upper triangular if M-K-L .GE. 0, otherwise A23 is (M-K)-by-L upper trapezoidal.
On exit,
U'A*Q = D1(0 R), V'B*Q = D2(0 R),
where U, V and Q are orthogonal matrices, Z' denotes the transpose of Z, R is a nonsingular upper triangular matrix, and D1 and D2 are `‘diagonal’' matrices, which are of the following structures:
If M-K-L .GE. 0,
K L D1 = K (I 0) L (0 C) M-K-L (0 0)
K L D2 = L (0 S) P-L (0 0)
N-K-L K L (0 R) = K (0 R11 R12) K L (0 0 R22) L
where
C = diag(ALPHA(K+1), ... , ALPHA(K+L)), S = diag(BETA(K+1), ... , BETA(K+L)), C**2 + S**2 = I.
R is stored in A(1:K+L,N-K-L+1:N) on exit.
If M-K-L .LT. 0,
K M-K K+L-M D1 = K (I 0 0) M-K (0 C 0)
K M-K K+L-M D2 = M-K (0 S 0) K+L-M (0 0 I) P-L (0 0 0)
N-K-L K M-K K+L-M (0 R) = K (0 R11 R12 R13) M-K (0 0 R22 R23) K+L-M (0 0 0 R33)
where C = diag(ALPHA(K+1), ... , ALPHA(M)), S = diag(BETA(K+1), ... , BETA(M)), C**2 + S**2 = I.
R = (R11 R12 R13) is stored in A(1:M, N-K-L+1:N) and R33 is stored (0 R22 R23) in B(M-K+1:L,N+M-K-L+1:N) on exit.
The computation of the orthogonal transformation matrices U, V or Q is optional. These matrices may either be formed explicitly, or they may be postmultiplied into input matrices U1, V1, or Q1.
/summary>
Parameters
JOBU (input) CHARACTER*1 = 'U': U must contain an orthogonal matrix U1 on entry, and the product U1*U is returned; = 'I': U is initialized to the unit matrix, and the orthogonal matrix U is returned; = 'N': U is not computed. /param>
Parameters
JOBV (input) CHARACTER*1 = 'V': V must contain an orthogonal matrix V1 on entry, and the product V1*V is returned; = 'I': V is initialized to the unit matrix, and the orthogonal matrix V is returned; = 'N': V is not computed. /param>
Parameters
JOBQ (input) CHARACTER*1 = 'Q': Q must contain an orthogonal matrix Q1 on entry, and the product Q1*Q is returned; = 'I': Q is initialized to the unit matrix, and the orthogonal matrix Q is returned; = 'N': Q is not computed. /param>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
P (input) INTEGER The number of rows of the matrix B. P .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrices A and B. N .GE. 0. /param>
Parameters
K L /param>
Parameters
L (0 0 A23) /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the M-by-N matrix A. On exit, A(N-K+1:N,1:MIN(K+L,M)) contains the triangular matrix R or part of R. See Purpose for details. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
B (input/output) DOUBLE PRECISION array, dimension (LDB,N) On entry, the P-by-N matrix B. On exit, if necessary, B(M-K+1:L,N+M-K-L+1:N) contains a part of R. See Purpose for details. /param>
Parameters
LDB (input) INTEGER The leading dimension of the array B. LDB .GE. max(1,P). /param>
Parameters
TOLA (input) DOUBLE PRECISION /param>
Parameters
TOLB (input) DOUBLE PRECISION TOLA and TOLB are the convergence criteria for the Jacobi- Kogbetliantz iteration procedure. Generally, they are the same as used in the preprocessing step, say TOLA = max(M,N)*norm(A)*MAZHEPS, TOLB = max(P,N)*norm(B)*MAZHEPS. /param>
Parameters
ALPHA (output) DOUBLE PRECISION array, dimension (N) /param>
Parameters
BETA (output) DOUBLE PRECISION array, dimension (N) On exit, ALPHA and BETA contain the generalized singular value pairs of A and B; ALPHA(1:K) = 1, BETA(1:K) = 0, and if M-K-L .GE. 0, ALPHA(K+1:K+L) = diag(C), BETA(K+1:K+L) = diag(S), or if M-K-L .LT. 0, ALPHA(K+1:M)= C, ALPHA(M+1:K+L)= 0 BETA(K+1:M) = S, BETA(M+1:K+L) = 1. Furthermore, if K+L .LT. N, ALPHA(K+L+1:N) = 0 and BETA(K+L+1:N) = 0. /param>
Parameters
U (input/output) DOUBLE PRECISION array, dimension (LDU,M) On entry, if JOBU = 'U', U must contain a matrix U1 (usually the orthogonal matrix returned by DGGSVP). On exit, if JOBU = 'I', U contains the orthogonal matrix U; if JOBU = 'U', U contains the product U1*U. If JOBU = 'N', U is not referenced. /param>
Parameters
LDU (input) INTEGER The leading dimension of the array U. LDU .GE. max(1,M) if JOBU = 'U'; LDU .GE. 1 otherwise. /param>
Parameters
V (input/output) DOUBLE PRECISION array, dimension (LDV,P) On entry, if JOBV = 'V', V must contain a matrix V1 (usually the orthogonal matrix returned by DGGSVP). On exit, if JOBV = 'I', V contains the orthogonal matrix V; if JOBV = 'V', V contains the product V1*V. If JOBV = 'N', V is not referenced. /param>
Parameters
LDV (input) INTEGER The leading dimension of the array V. LDV .GE. max(1,P) if JOBV = 'V'; LDV .GE. 1 otherwise. /param>
Parameters
Q (input/output) DOUBLE PRECISION array, dimension (LDQ,N) On entry, if JOBQ = 'Q', Q must contain a matrix Q1 (usually the orthogonal matrix returned by DGGSVP). On exit, if JOBQ = 'I', Q contains the orthogonal matrix Q; if JOBQ = 'Q', Q contains the product Q1*Q. If JOBQ = 'N', Q is not referenced. /param>
Parameters
LDQ (input) INTEGER The leading dimension of the array Q. LDQ .GE. max(1,N) if JOBQ = 'Q'; LDQ .GE. 1 otherwise. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (2*N) /param>
Parameters
NCYCLE (output) INTEGER The number of cycles required for convergence. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value. = 1: the procedure does not converge after MAXIT cycles. /param>
References DotNumerics.LinearAlgebra.CSLapack.DTGSJA.MAXIT, DotNumerics.LinearAlgebra.CSLapack.DTGSJA.ONE, DotNumerics.LinearAlgebra.CSLapack.DROT.Run(), DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASET.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARTG.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAPLL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAGS2.Run(), and DotNumerics.LinearAlgebra.CSLapack.DTGSJA.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGGSVD.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DTGSJA._lsame private
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DTGSJA._dcopy private
_dlags2
DLAGS2 DotNumerics.LinearAlgebra.CSLapack.DTGSJA._dlags2 private
_dlapll
DLAPLL DotNumerics.LinearAlgebra.CSLapack.DTGSJA._dlapll private
_dlartg
DLARTG DotNumerics.LinearAlgebra.CSLapack.DTGSJA._dlartg private
_dlaset
DLASET DotNumerics.LinearAlgebra.CSLapack.DTGSJA._dlaset private
_drot
DROT DotNumerics.LinearAlgebra.CSLapack.DTGSJA._drot private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DTGSJA._dscal private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DTGSJA._xerbla private
MAXIT
const int DotNumerics.LinearAlgebra.CSLapack.DTGSJA.MAXIT = 40 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTGSJA.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DTGSJA.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTGSJA.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DTGSJA.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTGSJA.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dtgsja.cs