Doc: IGLib EXTENDED: AForge.Imaging.HorizontalIntensityStatistics Class Reference
AForge.Imaging.HorizontalIntensityStatistics Class Reference
Horizontal intensity statistics.
Public Member Functions
HorizontalIntensityStatistics (Bitmap image)
Initializes a new instance of the HorizontalIntensityStatistics class.
HorizontalIntensityStatistics (BitmapData imageData)
Initializes a new instance of the HorizontalIntensityStatistics class.
HorizontalIntensityStatistics (UnmanagedImage image)
Initializes a new instance of the HorizontalIntensityStatistics class.
Properties
Histogram Red [get]
Histogram for red channel.
Histogram Green [get]
Histogram for green channel.
Histogram Blue [get]
Histogram for blue channel.
Histogram Gray [get]
Histogram for gray channel (intensities).
bool IsGrayscale [get]
Value wich specifies if the processed image was color or grayscale.
Private Member Functions
void ProcessImage (UnmanagedImage image)
Gather horizontal intensity statistics for specified image.
Private Attributes
Histogram red = null
Histogram green = null
Histogram blue = null
Histogram gray = null
Detailed Description
Horizontal intensity statistics.
The class provides information about horizontal distribution of pixel intensities, which may be used to locate objects, their centers, etc.
The class accepts grayscale (8 bpp indexed and 16 bpp) and color (24, 32, 48 and 64 bpp) images. In the case of 32 and 64 bpp color images, the alpha channel is not processed - statistics is not gathered for this channel.
Sample usage:
// collect statistics
HorizontalIntensityStatistics his = new HorizontalIntensityStatistics(sourceImage);
// get gray histogram (for grayscale image)
Histogram histogram = his.Gray;
// output some histogram's information
System.Diagnostics.Debug.WriteLine("Mean = " + histogram.Mean);
System.Diagnostics.Debug.WriteLine("Min = " + histogram.Min);
System.Diagnostics.Debug.WriteLine("Max = " + histogram.Max);
Sample grayscale image with its horizontal intensity histogram:
See also
VerticalIntensityStatistics
Constructor & Destructor Documentation
HorizontalIntensityStatistics() [1/3]
AForge.Imaging.HorizontalIntensityStatistics.HorizontalIntensityStatistics (Bitmap image) inline
Initializes a new instance of the HorizontalIntensityStatistics class.
Parameters
image Source image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Imaging.HorizontalIntensityStatistics.ProcessImage(), and AForge.Math.Geometry.Rectangle.
HorizontalIntensityStatistics() [2/3]
AForge.Imaging.HorizontalIntensityStatistics.HorizontalIntensityStatistics (BitmapData imageData) inline
Initializes a new instance of the HorizontalIntensityStatistics class.
Parameters
imageData Source image data.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
HorizontalIntensityStatistics() [3/3]
AForge.Imaging.HorizontalIntensityStatistics.HorizontalIntensityStatistics (UnmanagedImage image) inline
Initializes a new instance of the HorizontalIntensityStatistics class.
Parameters
image Source unmanaged image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
References AForge.Imaging.UnmanagedImage.PixelFormat, and AForge.Imaging.HorizontalIntensityStatistics.ProcessImage().
Member Function Documentation
ProcessImage()
void AForge.Imaging.HorizontalIntensityStatistics.ProcessImage (UnmanagedImage image) inline private
Gather horizontal intensity statistics for specified image.
Parameters
image Source image.
References AForge.Imaging.RGB.B, AForge.Imaging.HorizontalIntensityStatistics.blue, AForge.Imaging.RGB.G, AForge.Imaging.HorizontalIntensityStatistics.gray, AForge.Imaging.HorizontalIntensityStatistics.green, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, AForge.Imaging.HorizontalIntensityStatistics.red, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
Referenced by AForge.Imaging.HorizontalIntensityStatistics.HorizontalIntensityStatistics().
Member Data Documentation
red
Histogram AForge.Imaging.HorizontalIntensityStatistics.red = null private
Referenced by AForge.Imaging.HorizontalIntensityStatistics.ProcessImage().
green
Histogram AForge.Imaging.HorizontalIntensityStatistics.green = null private
Referenced by AForge.Imaging.HorizontalIntensityStatistics.ProcessImage().
blue
Histogram AForge.Imaging.HorizontalIntensityStatistics.blue = null private
Referenced by AForge.Imaging.HorizontalIntensityStatistics.ProcessImage().
gray
Histogram AForge.Imaging.HorizontalIntensityStatistics.gray = null private
Referenced by AForge.Imaging.HorizontalIntensityStatistics.ProcessImage().
Property Documentation
Red
Histogram AForge.Imaging.HorizontalIntensityStatistics.Red get
Histogram for red channel.
Green
Histogram AForge.Imaging.HorizontalIntensityStatistics.Green get
Histogram for green channel.
Blue
Histogram AForge.Imaging.HorizontalIntensityStatistics.Blue get
Histogram for blue channel.
Gray
Histogram AForge.Imaging.HorizontalIntensityStatistics.Gray get
Histogram for gray channel (intensities).
IsGrayscale
bool AForge.Imaging.HorizontalIntensityStatistics.IsGrayscale get
Value wich specifies if the processed image was color or grayscale.
If the property equals to true, then the Gray property should be used to retrieve histogram for the processed grayscale image. Otherwise Red, Green and Blue property should be used to retrieve histogram for particular RGB channel of the processed color image.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/HorizontalIntensityStatistics.cs