Doc: IGLib EXTENDED: CShell.Framework.Results.ResultBase Class Reference
CShell.Framework.Results.ResultBase Class Reference abstract
Public Member Functions
abstract void Execute (ActionExecutionContext context)
Protected Member Functions
virtual void OnCompleted (Exception exception)
virtual void OnCompleted (Exception exception, bool wasCancelled)
Events
EventHandler< ResultCompletionEventArgs > Completed
Member Function Documentation
Execute()
abstract void CShell.Framework.Results.ResultBase.Execute (ActionExecutionContext context) pure virtual
Implemented in CShell.Framework.Results.CloseWorkspaceResult, CShell.Framework.Results.SaveDocumentResult, CShell.Framework.Results.ShowDialogResult, CShell.Framework.Results.RunCodeResult, and CShell.Framework.Results.OpenWorkspaceResult.
OnCompleted() [1/2]
virtual void CShell.Framework.Results.ResultBase.OnCompleted (Exception exception) inline protected virtual
References CShell.Framework.Results.ResultBase.Completed.
Referenced by CShell.Framework.Results.OpenWorkspaceResult.Execute(), CShell.Modules.Workspace.Results.AddFilesResult.Execute(), CShell.Framework.Results.RunCodeResult.Execute(), CShell.Framework.Results.ShowDialogResult.Execute(), CShell.Framework.Results.SaveDocumentResult.Execute(), CShell.Framework.Results.CloseWorkspaceResult.Execute(), and CShell.Modules.Workspace.Results.AddReferencesResult.Execute().
OnCompleted() [2/2]
virtual void CShell.Framework.Results.ResultBase.OnCompleted (Exception exception, bool wasCancelled) inline protected virtual
References CShell.Framework.Results.ResultBase.Completed.
Event Documentation
Completed
EventHandler<ResultCompletionEventArgs> CShell.Framework.Results.ResultBase.Completed
Referenced by CShell.Framework.Results.ResultBase.OnCompleted().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore/Framework/Results/ResultBase.cs