Doc: IGLib EXTENDED: SVSTest.MainForm Class Reference
SVSTest.MainForm Class Reference
Public Member Functions
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void MainForm_FormClosing (object sender, FormClosingEventArgs e)
void EnableContols (bool enable)
void connectButton_Click (object sender, EventArgs e)
void disconnectButton_Click (object sender, EventArgs e)
bool Connect (string host)
void Disconnect ()
void timer_Tick (object sender, EventArgs e)
void qualityCombo_SelectedIndexChanged (object sender, EventArgs e)
void resolutionCombo_SelectedIndexChanged (object sender, EventArgs e)
void showStereoButton_Click (object sender, EventArgs e)
void stereoViewForm_OnFormClosing (object sender, FormClosingEventArgs eventArgs)
void srvDriverControl_SrvDrivingCommand (object sender, SRV1.MotorCommand command)
void directControlRadio_CheckedChanged (object sender, EventArgs e)
void manipulatorControl_PositionChanged (object sender, ManipulatorControl.PositionEventArgs eventArgs)
void turnControl_PositionChanged (object sender, float x)
void DriveMotors (float leftMotor, float rightMotor)
void minPowerUpDown_ValueChanged (object sender, EventArgs e)
void maxPowerUpDown_ValueChanged (object sender, EventArgs e)
void aboutButton_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
SVS svs = new SVS()
StereoViewForm stereoViewForm
int statIndex = 0
int statReady = 0
int[] statCount1 = new int[statLength]
int[] statCount2 = new int[statLength]
bool receivedFirstDrivingCommand = false
SRV1.MotorCommand lastMotorCommand
float[] maxPowers
int maxMotorPower = 90
int minMotorPower = 50
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.Button disconnectButton
System.Windows.Forms.Button connectButton
System.Windows.Forms.TextBox ipBox
System.Windows.Forms.Label label1
System.Windows.Forms.StatusStrip statusStrip
System.Windows.Forms.ToolStripStatusLabel statusLabel
System.Windows.Forms.ToolStripStatusLabel fpsLabel
System.Windows.Forms.GroupBox groupBox2
AForge.Controls.VideoSourcePlayer leftCameraPlayer
System.Windows.Forms.GroupBox groupBox3
AForge.Controls.VideoSourcePlayer rightCameraPlayer
System.Windows.Forms.Timer timer
System.Windows.Forms.ToolStripStatusLabel versionLabel
System.Windows.Forms.Button showStereoButton
System.Windows.Forms.GroupBox groupBox4
System.Windows.Forms.ComboBox resolutionCombo
System.Windows.Forms.Label label3
System.Windows.Forms.ComboBox qualityCombo
System.Windows.Forms.Label label2
System.Windows.Forms.GroupBox groupBox5
SrvDriverControl srvDriverControl
AForge.Controls.ManipulatorControl manipulatorControl
System.Windows.Forms.RadioButton directControlRadio
System.Windows.Forms.RadioButton predefinedCommandsRadio
AForge.Controls.SliderControl turnControl
System.Windows.Forms.NumericUpDown maxPowerUpDown
System.Windows.Forms.NumericUpDown minPowerUpDown
System.Windows.Forms.Label maxPowerLabel
System.Windows.Forms.Label minPowerLabel
System.Windows.Forms.Button aboutButton
Static Private Attributes
const int statLength = 15
Constructor & Destructor Documentation
MainForm()
SVSTest.MainForm.MainForm () inline
References SVSTest.MainForm.EnableContols(), SVSTest.MainForm.InitializeComponent(), SVSTest.MainForm.maxMotorPower, SVSTest.MainForm.maxPowerUpDown, SVSTest.MainForm.minMotorPower, and SVSTest.MainForm.minPowerUpDown.
Member Function Documentation
MainForm_FormClosing()
void SVSTest.MainForm.MainForm_FormClosing (object sender, FormClosingEventArgs e) inline private
References SVSTest.MainForm.Disconnect().
Referenced by SVSTest.MainForm.InitializeComponent().
EnableContols()
void SVSTest.MainForm.EnableContols (bool enable) inline private
References SVSTest.MainForm.connectButton, SVSTest.MainForm.disconnectButton, SVSTest.MainForm.ipBox, SVSTest.MainForm.manipulatorControl, SVSTest.MainForm.qualityCombo, SVSTest.MainForm.resolutionCombo, SVSTest.MainForm.srvDriverControl, and SVSTest.MainForm.turnControl.
Referenced by SVSTest.MainForm.connectButton_Click(), SVSTest.MainForm.Disconnect(), and SVSTest.MainForm.MainForm().
connectButton_Click()
void SVSTest.MainForm.connectButton_Click (object sender, EventArgs e) inline private
References SVSTest.MainForm.Connect(), SVSTest.MainForm.EnableContols(), SVSTest.MainForm.ipBox, SVSTest.MainForm.qualityCombo, SVSTest.MainForm.resolutionCombo, and SVSTest.MainForm.statusLabel.
Referenced by SVSTest.MainForm.InitializeComponent().
disconnectButton_Click()
void SVSTest.MainForm.disconnectButton_Click (object sender, EventArgs e) inline private
References SVSTest.MainForm.Disconnect(), SVSTest.MainForm.fpsLabel, SVSTest.MainForm.statusLabel, and SVSTest.MainForm.versionLabel.
Referenced by SVSTest.MainForm.InitializeComponent().
Connect()
bool SVSTest.MainForm.Connect (string host) inline private
References AForge.Robotics.Surveyor.SVS.Connect(), SVSTest.MainForm.Disconnect(), AForge.Robotics.Surveyor.SVS.EnableFailsafeMode(), AForge.Robotics.Surveyor.SVS.FlipVideo(), AForge.Robotics.Surveyor.SVS.GetCamera(), AForge.Robotics.Surveyor.SVS.GetVersion(), SVSTest.MainForm.leftCameraPlayer, SVSTest.MainForm.receivedFirstDrivingCommand, SVSTest.MainForm.rightCameraPlayer, AForge.Robotics.Surveyor.SVS.SetQuality(), AForge.Robotics.Surveyor.SVS.SetResolution(), AForge.Controls.VideoSourcePlayer.Start(), SVSTest.MainForm.statIndex, SVSTest.MainForm.statReady, SVSTest.MainForm.svs, SVSTest.MainForm.timer, SVSTest.MainForm.versionLabel, and AForge.Controls.VideoSourcePlayer.VideoSource.
Referenced by SVSTest.MainForm.connectButton_Click().
Disconnect()
void SVSTest.MainForm.Disconnect () inline private
References AForge.Robotics.Surveyor.SVS.Disconnect(), SVSTest.MainForm.EnableContols(), AForge.Robotics.Surveyor.SVS.IsConnected, SVSTest.MainForm.leftCameraPlayer, SVSTest.MainForm.rightCameraPlayer, AForge.Video.IVideoSource.SignalToStop(), AForge.Robotics.Surveyor.SVS.StopMotors(), SVSTest.MainForm.svs, SVSTest.MainForm.timer, AForge.Controls.VideoSourcePlayer.VideoSource, and AForge.Video.IVideoSource.WaitForStop().
Referenced by SVSTest.MainForm.Connect(), SVSTest.MainForm.disconnectButton_Click(), and SVSTest.MainForm.MainForm_FormClosing().
timer_Tick()
void SVSTest.MainForm.timer_Tick (object sender, EventArgs e) inline private
References SVSTest.MainForm.fpsLabel, AForge.Video.IVideoSource.FramesReceived, SVSTest.MainForm.leftCameraPlayer, SVSTest.MainForm.rightCameraPlayer, SVSTest.MainForm.statCount1, SVSTest.MainForm.statCount2, SVSTest.MainForm.statIndex, SVSTest.MainForm.statLength, SVSTest.MainForm.statReady, and AForge.Controls.VideoSourcePlayer.VideoSource.
Referenced by SVSTest.MainForm.InitializeComponent().
qualityCombo_SelectedIndexChanged()
void SVSTest.MainForm.qualityCombo_SelectedIndexChanged (object sender, EventArgs e) inline private
References AForge.Robotics.Surveyor.SVS.IsConnected, SVSTest.MainForm.qualityCombo, AForge.Robotics.Surveyor.SVS.SetQuality(), SVSTest.MainForm.statIndex, SVSTest.MainForm.statReady, and SVSTest.MainForm.svs.
Referenced by SVSTest.MainForm.InitializeComponent().
resolutionCombo_SelectedIndexChanged()
void SVSTest.MainForm.resolutionCombo_SelectedIndexChanged (object sender, EventArgs e) inline private
References AForge.Robotics.Surveyor.SVS.IsConnected, SVSTest.MainForm.resolutionCombo, AForge.Robotics.Surveyor.SVS.SetResolution(), SVSTest.MainForm.statIndex, SVSTest.MainForm.statReady, and SVSTest.MainForm.svs.
Referenced by SVSTest.MainForm.InitializeComponent().
showStereoButton_Click()
void SVSTest.MainForm.showStereoButton_Click (object sender, EventArgs e) inline private
References SVSTest.MainForm.leftCameraPlayer, AForge.Controls.VideoSourcePlayer.NewFrame, AForge.Controls.VideoSourcePlayer.NewFrameHandler(), SVSTest.StereoViewForm.OnNewLeftFrame(), SVSTest.StereoViewForm.OnNewRightFrame(), SVSTest.MainForm.rightCameraPlayer, SVSTest.MainForm.stereoViewForm, and SVSTest.MainForm.stereoViewForm_OnFormClosing().
Referenced by SVSTest.MainForm.InitializeComponent().
stereoViewForm_OnFormClosing()
void SVSTest.MainForm.stereoViewForm_OnFormClosing (object sender, FormClosingEventArgs eventArgs) inline private
References SVSTest.MainForm.leftCameraPlayer, AForge.Controls.VideoSourcePlayer.NewFrame, AForge.Controls.VideoSourcePlayer.NewFrameHandler(), SVSTest.StereoViewForm.OnNewLeftFrame(), SVSTest.StereoViewForm.OnNewRightFrame(), SVSTest.MainForm.rightCameraPlayer, and SVSTest.MainForm.stereoViewForm.
Referenced by SVSTest.MainForm.showStereoButton_Click().
srvDriverControl_SrvDrivingCommand()
void SVSTest.MainForm.srvDriverControl_SrvDrivingCommand (object sender, SRV1.MotorCommand command) inline private
References AForge.Robotics.Surveyor.SVS.ControlMotors(), AForge.Robotics.Surveyor.SVS.IsConnected, SVSTest.MainForm.lastMotorCommand, SVSTest.MainForm.receivedFirstDrivingCommand, AForge.Robotics.Surveyor.SVS.StopMotors(), and SVSTest.MainForm.svs.
Referenced by SVSTest.MainForm.InitializeComponent().
directControlRadio_CheckedChanged()
void SVSTest.MainForm.directControlRadio_CheckedChanged (object sender, EventArgs e) inline private
References SVSTest.MainForm.directControlRadio, SVSTest.MainForm.manipulatorControl, SVSTest.MainForm.maxPowerLabel, SVSTest.MainForm.maxPowerUpDown, SVSTest.MainForm.minPowerLabel, SVSTest.MainForm.minPowerUpDown, SVSTest.MainForm.srvDriverControl, and SVSTest.MainForm.turnControl.
Referenced by SVSTest.MainForm.InitializeComponent().
manipulatorControl_PositionChanged()
void SVSTest.MainForm.manipulatorControl_PositionChanged (object sender, ManipulatorControl.PositionEventArgs eventArgs) inline private
References SVSTest.MainForm.DriveMotors(), and SVSTest.MainForm.maxPowers.
Referenced by SVSTest.MainForm.InitializeComponent().
turnControl_PositionChanged()
void SVSTest.MainForm.turnControl_PositionChanged (object sender, float x) inline private
References SVSTest.MainForm.DriveMotors().
Referenced by SVSTest.MainForm.InitializeComponent().
DriveMotors()
void SVSTest.MainForm.DriveMotors (float leftMotor, float rightMotor) inline private
References AForge.Robotics.Surveyor.SVS.IsConnected, SVSTest.MainForm.maxMotorPower, SVSTest.MainForm.minMotorPower, AForge.Robotics.Surveyor.SVS.RunMotors(), and SVSTest.MainForm.svs.
Referenced by SVSTest.MainForm.manipulatorControl_PositionChanged(), and SVSTest.MainForm.turnControl_PositionChanged().
minPowerUpDown_ValueChanged()
void SVSTest.MainForm.minPowerUpDown_ValueChanged (object sender, EventArgs e) inline private
References SVSTest.MainForm.minMotorPower, and SVSTest.MainForm.minPowerUpDown.
Referenced by SVSTest.MainForm.InitializeComponent().
maxPowerUpDown_ValueChanged()
void SVSTest.MainForm.maxPowerUpDown_ValueChanged (object sender, EventArgs e) inline private
References SVSTest.MainForm.maxMotorPower, and SVSTest.MainForm.maxPowerUpDown.
Referenced by SVSTest.MainForm.InitializeComponent().
aboutButton_Click()
void SVSTest.MainForm.aboutButton_Click (object sender, EventArgs e) inline private
Referenced by SVSTest.MainForm.InitializeComponent().
Dispose()
override void SVSTest.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References SVSTest.MainForm.components.
InitializeComponent()
void SVSTest.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References SVSTest.MainForm.aboutButton, SVSTest.MainForm.aboutButton_Click(), SVSTest.MainForm.components, SVSTest.MainForm.connectButton, SVSTest.MainForm.connectButton_Click(), SVSTest.MainForm.directControlRadio, SVSTest.MainForm.directControlRadio_CheckedChanged(), SVSTest.MainForm.disconnectButton, SVSTest.MainForm.disconnectButton_Click(), SVSTest.MainForm.fpsLabel, SVSTest.MainForm.groupBox1, SVSTest.MainForm.groupBox2, SVSTest.MainForm.groupBox3, SVSTest.MainForm.groupBox4, SVSTest.MainForm.groupBox5, SVSTest.MainForm.ipBox, SVSTest.MainForm.label1, SVSTest.MainForm.label2, SVSTest.MainForm.label3, SVSTest.MainForm.leftCameraPlayer, SVSTest.MainForm.MainForm_FormClosing(), SVSTest.MainForm.manipulatorControl, SVSTest.MainForm.manipulatorControl_PositionChanged(), SVSTest.MainForm.maxPowerLabel, SVSTest.MainForm.maxPowerUpDown, SVSTest.MainForm.maxPowerUpDown_ValueChanged(), SVSTest.MainForm.minPowerLabel, SVSTest.MainForm.minPowerUpDown, SVSTest.MainForm.minPowerUpDown_ValueChanged(), AForge.Controls.SliderControl.PositionChangedHandler(), AForge.Controls.ManipulatorControl.PositionChangedHandler(), SVSTest.MainForm.predefinedCommandsRadio, SVSTest.MainForm.qualityCombo, SVSTest.MainForm.qualityCombo_SelectedIndexChanged(), SVSTest.MainForm.resolutionCombo, SVSTest.MainForm.resolutionCombo_SelectedIndexChanged(), SVSTest.MainForm.rightCameraPlayer, SVSTest.MainForm.showStereoButton, SVSTest.MainForm.showStereoButton_Click(), SVSTest.MainForm.srvDriverControl, SVSTest.MainForm.srvDriverControl_SrvDrivingCommand(), SVSTest.SrvDriverControl.SrvDrivingCommand, SVSTest.MainForm.statusLabel, SVSTest.MainForm.statusStrip, SVSTest.MainForm.timer, SVSTest.MainForm.timer_Tick(), SVSTest.MainForm.turnControl, SVSTest.MainForm.turnControl_PositionChanged(), and SVSTest.MainForm.versionLabel.
Referenced by SVSTest.MainForm.MainForm().
Member Data Documentation
svs
SVS SVSTest.MainForm.svs = new SVS() private
Referenced by SVSTest.MainForm.Connect(), SVSTest.MainForm.Disconnect(), SVSTest.MainForm.DriveMotors(), SVSTest.MainForm.qualityCombo_SelectedIndexChanged(), SVSTest.MainForm.resolutionCombo_SelectedIndexChanged(), and SVSTest.MainForm.srvDriverControl_SrvDrivingCommand().
stereoViewForm
StereoViewForm SVSTest.MainForm.stereoViewForm private
Referenced by SVSTest.MainForm.showStereoButton_Click(), and SVSTest.MainForm.stereoViewForm_OnFormClosing().
statLength
const int SVSTest.MainForm.statLength = 15 static private
Referenced by SVSTest.MainForm.timer_Tick().
statIndex
int SVSTest.MainForm.statIndex = 0 private
Referenced by SVSTest.MainForm.Connect(), SVSTest.MainForm.qualityCombo_SelectedIndexChanged(), SVSTest.MainForm.resolutionCombo_SelectedIndexChanged(), and SVSTest.MainForm.timer_Tick().
statReady
int SVSTest.MainForm.statReady = 0 private
Referenced by SVSTest.MainForm.Connect(), SVSTest.MainForm.qualityCombo_SelectedIndexChanged(), SVSTest.MainForm.resolutionCombo_SelectedIndexChanged(), and SVSTest.MainForm.timer_Tick().
statCount1
int [] SVSTest.MainForm.statCount1 = new int[statLength] private
Referenced by SVSTest.MainForm.timer_Tick().
statCount2
int [] SVSTest.MainForm.statCount2 = new int[statLength] private
Referenced by SVSTest.MainForm.timer_Tick().
receivedFirstDrivingCommand
bool SVSTest.MainForm.receivedFirstDrivingCommand = false private
Referenced by SVSTest.MainForm.Connect(), and SVSTest.MainForm.srvDriverControl_SrvDrivingCommand().
lastMotorCommand
SRV1.MotorCommand SVSTest.MainForm.lastMotorCommand private
Referenced by SVSTest.MainForm.srvDriverControl_SrvDrivingCommand().
maxPowers
float [] SVSTest.MainForm.maxPowers private
Initial value:
= new float[] { 0.1f, 0.2f, 0.35f, 0.5f, 0.65f, 0.8f, 0.9f, 1.0f,
            1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f }
Referenced by SVSTest.MainForm.manipulatorControl_PositionChanged().
maxMotorPower
int SVSTest.MainForm.maxMotorPower = 90 private
Referenced by SVSTest.MainForm.DriveMotors(), SVSTest.MainForm.MainForm(), and SVSTest.MainForm.maxPowerUpDown_ValueChanged().
minMotorPower
int SVSTest.MainForm.minMotorPower = 50 private
Referenced by SVSTest.MainForm.DriveMotors(), SVSTest.MainForm.MainForm(), and SVSTest.MainForm.minPowerUpDown_ValueChanged().
components
System.ComponentModel.IContainer SVSTest.MainForm.components = null private
Required designer variable.
Referenced by SVSTest.MainForm.Dispose(), and SVSTest.MainForm.InitializeComponent().
groupBox1
System.Windows.Forms.GroupBox SVSTest.MainForm.groupBox1 private
Referenced by SVSTest.MainForm.InitializeComponent().
disconnectButton
System.Windows.Forms.Button SVSTest.MainForm.disconnectButton private
Referenced by SVSTest.MainForm.EnableContols(), and SVSTest.MainForm.InitializeComponent().
connectButton
System.Windows.Forms.Button SVSTest.MainForm.connectButton private
Referenced by SVSTest.MainForm.EnableContols(), and SVSTest.MainForm.InitializeComponent().
ipBox
System.Windows.Forms.TextBox SVSTest.MainForm.ipBox private
Referenced by SVSTest.MainForm.connectButton_Click(), SVSTest.MainForm.EnableContols(), and SVSTest.MainForm.InitializeComponent().
label1
System.Windows.Forms.Label SVSTest.MainForm.label1 private
Referenced by SVSTest.MainForm.InitializeComponent().
statusStrip
System.Windows.Forms.StatusStrip SVSTest.MainForm.statusStrip private
Referenced by SVSTest.MainForm.InitializeComponent().
statusLabel
System.Windows.Forms.ToolStripStatusLabel SVSTest.MainForm.statusLabel private
Referenced by SVSTest.MainForm.connectButton_Click(), SVSTest.MainForm.disconnectButton_Click(), and SVSTest.MainForm.InitializeComponent().
fpsLabel
System.Windows.Forms.ToolStripStatusLabel SVSTest.MainForm.fpsLabel private
Referenced by SVSTest.MainForm.disconnectButton_Click(), SVSTest.MainForm.InitializeComponent(), and SVSTest.MainForm.timer_Tick().
groupBox2
System.Windows.Forms.GroupBox SVSTest.MainForm.groupBox2 private
Referenced by SVSTest.MainForm.InitializeComponent().
leftCameraPlayer
AForge.Controls.VideoSourcePlayer SVSTest.MainForm.leftCameraPlayer private
Referenced by SVSTest.MainForm.Connect(), SVSTest.MainForm.Disconnect(), SVSTest.MainForm.InitializeComponent(), SVSTest.MainForm.showStereoButton_Click(), SVSTest.MainForm.stereoViewForm_OnFormClosing(), and SVSTest.MainForm.timer_Tick().
groupBox3
System.Windows.Forms.GroupBox SVSTest.MainForm.groupBox3 private
Referenced by SVSTest.MainForm.InitializeComponent().
rightCameraPlayer
AForge.Controls.VideoSourcePlayer SVSTest.MainForm.rightCameraPlayer private
Referenced by SVSTest.MainForm.Connect(), SVSTest.MainForm.Disconnect(), SVSTest.MainForm.InitializeComponent(), SVSTest.MainForm.showStereoButton_Click(), SVSTest.MainForm.stereoViewForm_OnFormClosing(), and SVSTest.MainForm.timer_Tick().
timer
System.Windows.Forms.Timer SVSTest.MainForm.timer private
Referenced by SVSTest.MainForm.Connect(), SVSTest.MainForm.Disconnect(), and SVSTest.MainForm.InitializeComponent().
versionLabel
System.Windows.Forms.ToolStripStatusLabel SVSTest.MainForm.versionLabel private
Referenced by SVSTest.MainForm.Connect(), SVSTest.MainForm.disconnectButton_Click(), and SVSTest.MainForm.InitializeComponent().
showStereoButton
System.Windows.Forms.Button SVSTest.MainForm.showStereoButton private
Referenced by SVSTest.MainForm.InitializeComponent().
groupBox4
System.Windows.Forms.GroupBox SVSTest.MainForm.groupBox4 private
Referenced by SVSTest.MainForm.InitializeComponent().
resolutionCombo
System.Windows.Forms.ComboBox SVSTest.MainForm.resolutionCombo private
Referenced by SVSTest.MainForm.connectButton_Click(), SVSTest.MainForm.EnableContols(), SVSTest.MainForm.InitializeComponent(), and SVSTest.MainForm.resolutionCombo_SelectedIndexChanged().
label3
System.Windows.Forms.Label SVSTest.MainForm.label3 private
Referenced by SVSTest.MainForm.InitializeComponent().
qualityCombo
System.Windows.Forms.ComboBox SVSTest.MainForm.qualityCombo private
Referenced by SVSTest.MainForm.connectButton_Click(), SVSTest.MainForm.EnableContols(), SVSTest.MainForm.InitializeComponent(), and SVSTest.MainForm.qualityCombo_SelectedIndexChanged().
label2
System.Windows.Forms.Label SVSTest.MainForm.label2 private
Referenced by SVSTest.MainForm.InitializeComponent().
groupBox5
System.Windows.Forms.GroupBox SVSTest.MainForm.groupBox5 private
Referenced by SVSTest.MainForm.InitializeComponent().
srvDriverControl
SrvDriverControl SVSTest.MainForm.srvDriverControl private
Referenced by SVSTest.MainForm.directControlRadio_CheckedChanged(), SVSTest.MainForm.EnableContols(), and SVSTest.MainForm.InitializeComponent().
manipulatorControl
AForge.Controls.ManipulatorControl SVSTest.MainForm.manipulatorControl private
Referenced by SVSTest.MainForm.directControlRadio_CheckedChanged(), SVSTest.MainForm.EnableContols(), and SVSTest.MainForm.InitializeComponent().
directControlRadio
System.Windows.Forms.RadioButton SVSTest.MainForm.directControlRadio private
Referenced by SVSTest.MainForm.directControlRadio_CheckedChanged(), and SVSTest.MainForm.InitializeComponent().
predefinedCommandsRadio
System.Windows.Forms.RadioButton SVSTest.MainForm.predefinedCommandsRadio private
Referenced by SVSTest.MainForm.InitializeComponent().
turnControl
AForge.Controls.SliderControl SVSTest.MainForm.turnControl private
Referenced by SVSTest.MainForm.directControlRadio_CheckedChanged(), SVSTest.MainForm.EnableContols(), and SVSTest.MainForm.InitializeComponent().
maxPowerUpDown
System.Windows.Forms.NumericUpDown SVSTest.MainForm.maxPowerUpDown private
Referenced by SVSTest.MainForm.directControlRadio_CheckedChanged(), SVSTest.MainForm.InitializeComponent(), SVSTest.MainForm.MainForm(), and SVSTest.MainForm.maxPowerUpDown_ValueChanged().
minPowerUpDown
System.Windows.Forms.NumericUpDown SVSTest.MainForm.minPowerUpDown private
Referenced by SVSTest.MainForm.directControlRadio_CheckedChanged(), SVSTest.MainForm.InitializeComponent(), SVSTest.MainForm.MainForm(), and SVSTest.MainForm.minPowerUpDown_ValueChanged().
maxPowerLabel
System.Windows.Forms.Label SVSTest.MainForm.maxPowerLabel private
Referenced by SVSTest.MainForm.directControlRadio_CheckedChanged(), and SVSTest.MainForm.InitializeComponent().
minPowerLabel
System.Windows.Forms.Label SVSTest.MainForm.minPowerLabel private
Referenced by SVSTest.MainForm.directControlRadio_CheckedChanged(), and SVSTest.MainForm.InitializeComponent().
aboutButton
System.Windows.Forms.Button SVSTest.MainForm.aboutButton private
Referenced by SVSTest.MainForm.InitializeComponent().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Robotics/Surveyor/SVSTest/MainForm.cs
shelldev/lib_ann/aforge.net/Samples/Robotics/Surveyor/SVSTest/MainForm.Designer.cs