Doc: IGLib EXTENDED: AlgLib.lbfgs Class Reference
AlgLib.lbfgs Class Reference
Classes
struct lbfgsreport
struct lbfgsstate
Static Public Member Functions
static void minlbfgs (int n, int m, ref double[] x, double epsg, double epsf, double epsx, int maxits, int flags, ref lbfgsstate state)
static bool minlbfgsiteration (ref lbfgsstate state)
static void minlbfgsresults (ref lbfgsstate state, ref double[] x, ref lbfgsreport rep)
Static Public Attributes
const double ftol = 0.0001
const double xtol = 100 * AP1.Mathe.MachineEpsilon
const double gtol = 0.9
const int maxfev = 20
const double stpmin = 1.0E-20
const double stpmax = 1.0E20
Static Private Member Functions
static void mcsrch (int n, ref double[] x, ref double f, ref double[] g, ref double[] s, ref double stp, ref int info, ref int nfev, ref double[] wa, ref lbfgsstate state, ref int stage)
static void mcstep (ref double stx, ref double fx, ref double dx, ref double sty, ref double fy, ref double dy, ref double stp, double fp, double dp, ref bool brackt, double stmin, double stmax, ref int info)
Member Function Documentation
minlbfgs()
static void AlgLib.lbfgs.minlbfgs (int n, int m, ref double[] x, double epsg, double epsf, double epsx, int maxits, int flags, ref lbfgsstate state) inline static
Referenced by NumLib.MinimizerLbfgs.InitializeIteration(), NumLib.ExampleAlgLib2008.OptimizeQuadratic(), NumLib.ExampleAlgLib2008.OptimizeRosenbrock(), NumLib.ExampleAlgLib2008.OptimizeRosenbrockOriginal(), and IG.Num.TestAlglibOld2008.TestLbfgsAlglibOld().
minlbfgsiteration()
static bool AlgLib.lbfgs.minlbfgsiteration (ref lbfgsstate state) inline static
References AlgLib.lbfgs.mcsrch().
Referenced by NumLib.MinimizerLbfgs.NextIteration(), NumLib.ExampleAlgLib2008.OptimizeQuadratic(), NumLib.ExampleAlgLib2008.OptimizeRosenbrock(), NumLib.ExampleAlgLib2008.OptimizeRosenbrockOriginal(), and IG.Num.TestAlglibOld2008.TestLbfgsAlglibOld().
minlbfgsresults()
static void AlgLib.lbfgs.minlbfgsresults (ref lbfgsstate state, ref double[] x, ref lbfgsreport rep) inline static
Referenced by NumLib.MinimizerLbfgs.Minimize(), NumLib.ExampleAlgLib2008.OptimizeQuadratic(), NumLib.ExampleAlgLib2008.OptimizeRosenbrock(), and NumLib.ExampleAlgLib2008.OptimizeRosenbrockOriginal().
mcsrch()
static void AlgLib.lbfgs.mcsrch (int n, ref double[] x, ref double f, ref double[] g, ref double[] s, ref double stp, ref int info, ref int nfev, ref double[] wa, ref lbfgsstate state, ref int stage) inline static private
References AlgLib.lbfgs.ftol, AlgLib.lbfgs.gtol, AlgLib.lbfgs.maxfev, AlgLib.lbfgs.mcstep(), AlgLib.lbfgs.stpmax, AlgLib.lbfgs.stpmin, and AlgLib.lbfgs.xtol.
Referenced by AlgLib.lbfgs.minlbfgsiteration().
mcstep()
static void AlgLib.lbfgs.mcstep (ref double stx, ref double fx, ref double dx, ref double sty, ref double fy, ref double dy, ref double stp, double fp, double dp, ref bool brackt, double stmin, double stmax, ref int info) inline static private
References AP1.Mathe.Sqr().
Referenced by AlgLib.lbfgs.mcsrch().
Member Data Documentation
ftol
const double AlgLib.lbfgs.ftol = 0.0001 static
Referenced by AlgLib.lbfgs.mcsrch().
xtol
const double AlgLib.lbfgs.xtol = 100 * AP1.Mathe.MachineEpsilon static
Referenced by AlgLib.lbfgs.mcsrch().
gtol
const double AlgLib.lbfgs.gtol = 0.9 static
Referenced by AlgLib.lbfgs.mcsrch().
maxfev
const int AlgLib.lbfgs.maxfev = 20 static
Referenced by AlgLib.lbfgs.mcsrch().
stpmin
const double AlgLib.lbfgs.stpmin = 1.0E-20 static
Referenced by AlgLib.lbfgs.mcsrch().
stpmax
const double AlgLib.lbfgs.stpmax = 1.0E20 static
Referenced by AlgLib.lbfgs.mcsrch().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/opt/alglib/Alglib_Old_UniMb/AlgLib2008/OriginalCode/lbfgs.cs