Doc: IGLib EXTENDED: AForge.Fuzzy.Database Class Reference
AForge.Fuzzy.Database Class Reference
The class represents a fuzzy database, a set of linguistic variables used in a Fuzzy Inference System.
Public Member Functions
Database ()
Initializes a new instance of the Database class.
void AddVariable (LinguisticVariable variable)
Adds a linguistic variable to the database.
void ClearVariables ()
Removes all the linguistic variables of the database.
LinguisticVariable GetVariable (string variableName)
Returns an existing linguistic variable from the database.
Private Attributes
Dictionary< string, LinguisticVariable > variables
Detailed Description
The class represents a fuzzy database, a set of linguistic variables used in a Fuzzy Inference System.
Constructor & Destructor Documentation
Database()
AForge.Fuzzy.Database.Database () inline
Initializes a new instance of the Database class.
Member Function Documentation
AddVariable()
void AForge.Fuzzy.Database.AddVariable (LinguisticVariable variable) inline
Adds a linguistic variable to the database.
Parameters
variable A linguistic variable to add.
Exceptions
NullReferenceException The linguistic variable was not initialized.
ArgumentException The linguistic variable name already exists in the database.
References AForge.Fuzzy.LinguisticVariable.Name.
Referenced by FuzzyAGV.MainForm.InitFuzzyEngine().
ClearVariables()
void AForge.Fuzzy.Database.ClearVariables () inline
Removes all the linguistic variables of the database.
GetVariable()
LinguisticVariable AForge.Fuzzy.Database.GetVariable (string variableName) inline
Returns an existing linguistic variable from the database.
Parameters
variableName Name of the linguistic variable to retrieve.
Returns
Reference to named LinguisticVariable.
Exceptions
KeyNotFoundException The variable indicated was not found in the database.
References AForge.Fuzzy.Database.variables.
Referenced by AForge.Fuzzy.InferenceSystem.ExecuteInference(), AForge.Fuzzy.InferenceSystem.GetLinguisticVariable(), AForge.Fuzzy.Rule.ParseRule(), and AForge.Fuzzy.InferenceSystem.SetInput().
Member Data Documentation
variables
Dictionary<string, LinguisticVariable> AForge.Fuzzy.Database.variables private
Referenced by AForge.Fuzzy.Database.GetVariable().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Fuzzy/Database.cs