Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DORGBR Class Reference
DotNumerics.LinearAlgebra.CSLapack.DORGBR Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DORGBR (LSAME lsame, ILAENV ilaenv, DORGLQ dorglq, DORGQR dorgqr, XERBLA xerbla)
DORGBR ()
void Run (string VECT, int M, int N, int K, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
LSAME _lsame
ILAENV _ilaenv
DORGLQ _dorglq
DORGQR _dorgqr
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DORGBR generates one of the real orthogonal matrices Q or P**T determined by DGEBRD when reducing a real matrix A to bidiagonal form: A = Q * B * P**T. Q and P**T are defined as products of elementary reflectors H(i) or G(i) respectively.
If VECT = 'Q', A is assumed to have been an M-by-K matrix, and Q is of order M: if m .GE. k, Q = H(1) H(2) . . . H(k) and DORGBR returns the first n columns of Q, where m .GE. n .GE. k; if m .LT. k, Q = H(1) H(2) . . . H(m-1) and DORGBR returns Q as an M-by-M matrix.
If VECT = 'P', A is assumed to have been a K-by-N matrix, and P**T is of order N: if k .LT. n, P**T = G(k) . . . G(2) G(1) and DORGBR returns the first m rows of P**T, where n .GE. m .GE. k; if k .GE. n, P**T = G(n-1) . . . G(2) G(1) and DORGBR returns P**T as an N-by-N matrix.
/summary>
Constructor & Destructor Documentation
DORGBR() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DORGBR.DORGBR (LSAME lsame, ILAENV ilaenv, DORGLQ dorglq, DORGQR dorgqr, XERBLA xerbla) inline
DORGBR() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DORGBR.DORGBR () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DORGBR.Run (string VECT, int M, int N, int K, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DORGBR generates one of the real orthogonal matrices Q or P**T determined by DGEBRD when reducing a real matrix A to bidiagonal form: A = Q * B * P**T. Q and P**T are defined as products of elementary reflectors H(i) or G(i) respectively.
If VECT = 'Q', A is assumed to have been an M-by-K matrix, and Q is of order M: if m .GE. k, Q = H(1) H(2) . . . H(k) and DORGBR returns the first n columns of Q, where m .GE. n .GE. k; if m .LT. k, Q = H(1) H(2) . . . H(m-1) and DORGBR returns Q as an M-by-M matrix.
If VECT = 'P', A is assumed to have been a K-by-N matrix, and P**T is of order N: if k .LT. n, P**T = G(k) . . . G(2) G(1) and DORGBR returns the first m rows of P**T, where n .GE. m .GE. k; if k .GE. n, P**T = G(n-1) . . . G(2) G(1) and DORGBR returns P**T as an N-by-N matrix.
/summary>
Parameters
VECT (input) CHARACTER*1 Specifies whether the matrix Q or the matrix P**T is required, as defined in the transformation applied by DGEBRD: = 'Q': generate Q; = 'P': generate P**T. /param>
Parameters
M (input) INTEGER The number of rows of the matrix Q or P**T to be returned. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix Q or P**T to be returned. N .GE. 0. If VECT = 'Q', M .GE. N .GE. min(M,K); if VECT = 'P', N .GE. M .GE. min(N,K). /param>
Parameters
K (input) INTEGER If VECT = 'Q', the number of columns in the original M-by-K matrix reduced by DGEBRD. If VECT = 'P', the number of rows in the original K-by-N matrix reduced by DGEBRD. K .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the vectors which define the elementary reflectors, as returned by DGEBRD. On exit, the M-by-N matrix Q or P**T. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
TAU (input) DOUBLE PRECISION array, dimension (min(M,K)) if VECT = 'Q' (min(N,K)) if VECT = 'P' TAU(i) must contain the scalar factor of the elementary reflector H(i) or G(i), which determines Q or P**T, as returned by DGEBRD in its array argument TAUQ or TAUP. /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. max(1,min(M,N)). For optimum performance LWORK .GE. min(M,N)*NB, where NB is the optimal blocksize.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.DORGBR.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGLQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGQR.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DORGBR.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DORGBR._lsame private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DORGBR._ilaenv private
_dorglq
DORGLQ DotNumerics.LinearAlgebra.CSLapack.DORGBR._dorglq private
_dorgqr
DORGQR DotNumerics.LinearAlgebra.CSLapack.DORGBR._dorgqr private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DORGBR._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DORGBR.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORGBR.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DORGBR.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORGBR.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dorgbr.cs