Doc: IGLib EXTENDED: AForge.Math.Geometry.Tests.SimpleShapeCheckerTest Class Reference
AForge.Math.Geometry.Tests.SimpleShapeCheckerTest Class Reference
Public Member Functions
SimpleShapeCheckerTest ()
void IsCircleTest ()
void IsQuadrilateralTest ()
void CheckQuadrilateralCornersTest ()
void IsTriangleTest ()
void IsConvexPolygon ()
void CheckShapeTypeTest ()
void CheckPolygonSubTypeTest (PolygonSubType expectedSubType, int[] corners)
Private Member Functions
bool CompareShape (List< IntPoint > shape1, List< IntPoint > shape2)
List< IntPoint > GetListOfPointFromArray (int[] points)
Private Attributes
SimpleShapeChecker shapeChecker = new SimpleShapeChecker()
List< IntPoint > idealCicle = new List<IntPoint>()
List< IntPoint > distorredCircle = new List<IntPoint>()
List< IntPoint > square1 = new List<IntPoint>()
List< IntPoint > square1Test = new List<IntPoint>()
List< IntPoint > square2 = new List<IntPoint>()
List< IntPoint > square2Test = new List<IntPoint>()
List< IntPoint > square3 = new List<IntPoint>()
List< IntPoint > rectangle = new List<IntPoint>()
List< IntPoint > triangle1 = new List<IntPoint>()
List< IntPoint > isoscelesTriangle = new List<IntPoint>()
List< IntPoint > equilateralTriangle = new List<IntPoint>()
List< IntPoint > rectangledTriangle = new List<IntPoint>()
Constructor & Destructor Documentation
SimpleShapeCheckerTest()
AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.SimpleShapeCheckerTest () inline
References AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.distorredCircle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.equilateralTriangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.idealCicle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.isoscelesTriangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.rectangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.rectangledTriangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square1, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square1Test, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square2, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square2Test, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square3, and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.triangle1.
Member Function Documentation
IsCircleTest()
void AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsCircleTest () inline
References AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.distorredCircle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.equilateralTriangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.idealCicle, AForge.Math.Geometry.SimpleShapeChecker.IsCircle(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.isoscelesTriangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.rectangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.rectangledTriangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.shapeChecker, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square1, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square2, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square3, and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.triangle1.
IsQuadrilateralTest()
void AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsQuadrilateralTest () inline
References AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.distorredCircle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.equilateralTriangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.idealCicle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.isoscelesTriangle, AForge.Math.Geometry.SimpleShapeChecker.IsQuadrilateral(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.rectangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.rectangledTriangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.shapeChecker, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square1, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square2, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square3, and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.triangle1.
CheckQuadrilateralCornersTest()
void AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckQuadrilateralCornersTest () inline
References AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CompareShape(), AForge.Math.Geometry.SimpleShapeChecker.IsQuadrilateral(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.shapeChecker, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square1, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square1Test, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square2, and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square2Test.
IsTriangleTest()
void AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsTriangleTest () inline
References AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.distorredCircle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.equilateralTriangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.idealCicle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.isoscelesTriangle, AForge.Math.Geometry.SimpleShapeChecker.IsTriangle(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.rectangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.rectangledTriangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.shapeChecker, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square1, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square2, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square3, and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.triangle1.
IsConvexPolygon()
void AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsConvexPolygon () inline
References AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.distorredCircle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.equilateralTriangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.idealCicle, AForge.Math.Geometry.SimpleShapeChecker.IsConvexPolygon(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.isoscelesTriangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.rectangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.rectangledTriangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.shapeChecker, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square1, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square2, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square3, and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.triangle1.
CheckShapeTypeTest()
void AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckShapeTypeTest () inline
References AForge.Math.Geometry.SimpleShapeChecker.CheckShapeType(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.distorredCircle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.equilateralTriangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.idealCicle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.isoscelesTriangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.rectangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.rectangledTriangle, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.shapeChecker, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square1, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square2, AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square3, and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.triangle1.
CompareShape()
bool AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CompareShape (List< IntPoint > shape1, List< IntPoint > shape2) inline private
Referenced by AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckQuadrilateralCornersTest().
CheckPolygonSubTypeTest()
void AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckPolygonSubTypeTest (PolygonSubType expectedSubType, int[] corners) inline
References AForge.Math.Geometry.SimpleShapeChecker.CheckPolygonSubType(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.GetListOfPointFromArray(), and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.shapeChecker.
GetListOfPointFromArray()
List<IntPoint> AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.GetListOfPointFromArray (int[] points) inline private
Referenced by AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckPolygonSubTypeTest().
Member Data Documentation
shapeChecker
SimpleShapeChecker AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.shapeChecker = new SimpleShapeChecker() private
Referenced by AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckPolygonSubTypeTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckQuadrilateralCornersTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckShapeTypeTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsCircleTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsConvexPolygon(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsQuadrilateralTest(), and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsTriangleTest().
idealCicle
List<IntPoint> AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.idealCicle = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckShapeTypeTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsCircleTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsConvexPolygon(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsQuadrilateralTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsTriangleTest(), and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.SimpleShapeCheckerTest().
distorredCircle
List<IntPoint> AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.distorredCircle = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckShapeTypeTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsCircleTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsConvexPolygon(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsQuadrilateralTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsTriangleTest(), and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.SimpleShapeCheckerTest().
square1
List<IntPoint> AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square1 = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckQuadrilateralCornersTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckShapeTypeTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsCircleTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsConvexPolygon(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsQuadrilateralTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsTriangleTest(), and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.SimpleShapeCheckerTest().
square1Test
List<IntPoint> AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square1Test = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckQuadrilateralCornersTest(), and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.SimpleShapeCheckerTest().
square2
List<IntPoint> AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square2 = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckQuadrilateralCornersTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckShapeTypeTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsCircleTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsConvexPolygon(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsQuadrilateralTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsTriangleTest(), and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.SimpleShapeCheckerTest().
square2Test
List<IntPoint> AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square2Test = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckQuadrilateralCornersTest(), and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.SimpleShapeCheckerTest().
square3
List<IntPoint> AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.square3 = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckShapeTypeTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsCircleTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsConvexPolygon(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsQuadrilateralTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsTriangleTest(), and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.SimpleShapeCheckerTest().
rectangle
List<IntPoint> AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.rectangle = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckShapeTypeTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsCircleTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsConvexPolygon(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsQuadrilateralTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsTriangleTest(), and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.SimpleShapeCheckerTest().
triangle1
List<IntPoint> AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.triangle1 = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckShapeTypeTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsCircleTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsConvexPolygon(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsQuadrilateralTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsTriangleTest(), and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.SimpleShapeCheckerTest().
isoscelesTriangle
List<IntPoint> AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.isoscelesTriangle = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckShapeTypeTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsCircleTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsConvexPolygon(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsQuadrilateralTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsTriangleTest(), and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.SimpleShapeCheckerTest().
equilateralTriangle
List<IntPoint> AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.equilateralTriangle = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckShapeTypeTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsCircleTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsConvexPolygon(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsQuadrilateralTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsTriangleTest(), and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.SimpleShapeCheckerTest().
rectangledTriangle
List<IntPoint> AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.rectangledTriangle = new List<IntPoint>() private
Referenced by AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckShapeTypeTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsCircleTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsConvexPolygon(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsQuadrilateralTest(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsTriangleTest(), and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.SimpleShapeCheckerTest().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Unit Tests/AForge.Math.Tests/Geometry/SimpleShapeCheckerTest.cs