Doc: IGLib EXTENDED: IG.Forms.WindowShiftControlNumeric Class Reference
IG.Forms.WindowShiftControlNumeric Class Reference
Control for setting window positions, relative positions, sizes, positions, shifts, etc.
Public Member Functions
WindowShiftControlNumeric ()
WindowShiftControlNumeric ()
WindowShiftControlNumeric ()
Protected Member Functions
void OnValueChanged (object sender, EventArgs eventArgs)
Triggers the ValueChanged event.
override void Dispose (bool disposing)
Clean up any resources being used.
void OnValueChanged (object sender, EventArgs eventArgs)
Triggers the ValueChanged event.
override void Dispose (bool disposing)
Clean up any resources being used.
void OnValueChanged (object sender, EventArgs eventArgs)
Triggers the ValueChanged event.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
vec2 _shift = new vec2(0.0, 0.0)
double _initialValueX
double _initialValueY
double _minValue
double _maxValue
double _increment
Properties
string Title [get, set]
Title text that is written on the outer group box.
vec2 Shift [get, set]
Gets or sets the resulting shift stored in 2D vector structure of type vec2
double InitialValueX [get, set]
Initial value of the first component of Shift.
double InitialValueY [get, set]
Initial value of the second component of Shift.
double MinimumValue [get, set]
Minimal value of components of Shift.
double MaximumValue [get, set]
Maximal value of components of Shift.
double Increment [get, set]
Increment for text controls for components of Shift.
Events
EventHandler ValueChanged
Event that occurs when the value of window position (or shift, size, relative position, etc.) kept by this control changes.
Private Member Functions
void txtWindowShiftRelX_Validated (object sender, EventArgs e)
void txtWindowShiftRelY_Validated (object sender, EventArgs e)
void txtWindowShiftRelX_Enter (object sender, EventArgs e)
void txtWindowShiftRelY_Enter (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void txtWindowShiftRelX_Validated (object sender, EventArgs e)
void txtWindowShiftRelY_Validated (object sender, EventArgs e)
void txtWindowShiftRelX_Enter (object sender, EventArgs e)
void txtWindowShiftRelY_Enter (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void txtWindowShiftRelX_Validated (object sender, EventArgs e)
void txtWindowShiftRelY_Validated (object sender, EventArgs e)
void txtWindowShiftRelX_Enter (object sender, EventArgs e)
void txtWindowShiftRelY_Enter (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.GroupBox pnlOuter
System.Windows.Forms.NumericUpDown txtWindowShiftRelY
System.Windows.Forms.Label lblWindowRelY
System.Windows.Forms.NumericUpDown txtWindowShiftRelX
System.Windows.Forms.Label lblWindowShiftRelX
Detailed Description
Control for setting window positions, relative positions, sizes, positions, shifts, etc.
This is a dummy control used for various tests such as window positioning.
$A Igor Oct09;
Constructor & Destructor Documentation
WindowShiftControlNumeric() [1/3]
IG.Forms.WindowShiftControlNumeric.WindowShiftControlNumeric () inline
References IG.Forms.WindowShiftControlNumeric.InitializeComponent().
WindowShiftControlNumeric() [2/3]
IG.Forms.WindowShiftControlNumeric.WindowShiftControlNumeric () inline
References IG.Forms.WindowShiftControlNumeric.InitializeComponent().
WindowShiftControlNumeric() [3/3]
IG.Forms.WindowShiftControlNumeric.WindowShiftControlNumeric () inline
References IG.Forms.WindowShiftControlNumeric.InitializeComponent().
Member Function Documentation
OnValueChanged() [1/3]
void IG.Forms.WindowShiftControlNumeric.OnValueChanged (object sender, EventArgs eventArgs) inline protected
Triggers the ValueChanged event.
References IG.Forms.WindowShiftControlNumeric.Shift, and IG.Forms.WindowShiftControlNumeric.ValueChanged.
Referenced by IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX_Validated(), and IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY_Validated().
txtWindowShiftRelX_Validated() [1/3]
void IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX_Validated (object sender, EventArgs e) inline private
References IG.Forms.WindowShiftControlNumeric._shift, IG.Forms.WindowShiftControlNumeric.OnValueChanged(), IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX, and IG.Num.vec2.x.
Referenced by IG.Forms.WindowShiftControlNumeric.InitializeComponent().
txtWindowShiftRelY_Validated() [1/3]
void IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY_Validated (object sender, EventArgs e) inline private
References IG.Forms.WindowShiftControlNumeric._shift, IG.Forms.WindowShiftControlNumeric.OnValueChanged(), IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY, and IG.Num.vec2.y.
Referenced by IG.Forms.WindowShiftControlNumeric.InitializeComponent().
txtWindowShiftRelX_Enter() [1/3]
void IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX_Enter (object sender, EventArgs e) inline private
References IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX.
Referenced by IG.Forms.WindowShiftControlNumeric.InitializeComponent().
txtWindowShiftRelY_Enter() [1/3]
void IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY_Enter (object sender, EventArgs e) inline private
References IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY.
Referenced by IG.Forms.WindowShiftControlNumeric.InitializeComponent().
Dispose() [1/3]
override void IG.Forms.WindowShiftControlNumeric.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.WindowShiftControlNumeric.components.
InitializeComponent() [1/3]
void IG.Forms.WindowShiftControlNumeric.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.WindowShiftControlNumeric.lblWindowRelY, IG.Forms.WindowShiftControlNumeric.lblWindowShiftRelX, IG.Forms.WindowShiftControlNumeric.pnlOuter, IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX, IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX_Enter(), IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX_Validated(), IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY, IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY_Enter(), and IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY_Validated().
Referenced by IG.Forms.WindowShiftControlNumeric.WindowShiftControlNumeric().
OnValueChanged() [2/3]
void IG.Forms.WindowShiftControlNumeric.OnValueChanged (object sender, EventArgs eventArgs) inline protected
Triggers the ValueChanged event.
References IG.Forms.WindowShiftControlNumeric.Shift, and IG.Forms.WindowShiftControlNumeric.ValueChanged.
txtWindowShiftRelX_Validated() [2/3]
void IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX_Validated (object sender, EventArgs e) inline private
References IG.Forms.WindowShiftControlNumeric._shift, IG.Forms.WindowShiftControlNumeric.OnValueChanged(), IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX, and IG.Num.vec2.x.
txtWindowShiftRelY_Validated() [2/3]
void IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY_Validated (object sender, EventArgs e) inline private
References IG.Forms.WindowShiftControlNumeric._shift, IG.Forms.WindowShiftControlNumeric.OnValueChanged(), IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY, and IG.Num.vec2.y.
txtWindowShiftRelX_Enter() [2/3]
void IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX_Enter (object sender, EventArgs e) inline private
References IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX.
txtWindowShiftRelY_Enter() [2/3]
void IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY_Enter (object sender, EventArgs e) inline private
References IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY.
Dispose() [2/3]
override void IG.Forms.WindowShiftControlNumeric.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.WindowShiftControlNumeric.components.
InitializeComponent() [2/3]
void IG.Forms.WindowShiftControlNumeric.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.WindowShiftControlNumeric.lblWindowRelY, IG.Forms.WindowShiftControlNumeric.lblWindowShiftRelX, IG.Forms.WindowShiftControlNumeric.pnlOuter, IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX, IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX_Enter(), IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX_Validated(), IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY, IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY_Enter(), and IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY_Validated().
OnValueChanged() [3/3]
void IG.Forms.WindowShiftControlNumeric.OnValueChanged (object sender, EventArgs eventArgs) inline protected
Triggers the ValueChanged event.
References IG.Forms.WindowShiftControlNumeric.Shift, and IG.Forms.WindowShiftControlNumeric.ValueChanged.
txtWindowShiftRelX_Validated() [3/3]
void IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX_Validated (object sender, EventArgs e) inline private
References IG.Forms.WindowShiftControlNumeric._shift, IG.Forms.WindowShiftControlNumeric.OnValueChanged(), IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX, and IG.Num.vec2.x.
txtWindowShiftRelY_Validated() [3/3]
void IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY_Validated (object sender, EventArgs e) inline private
References IG.Forms.WindowShiftControlNumeric._shift, IG.Forms.WindowShiftControlNumeric.OnValueChanged(), IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY, and IG.Num.vec2.y.
txtWindowShiftRelX_Enter() [3/3]
void IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX_Enter (object sender, EventArgs e) inline private
References IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX.
txtWindowShiftRelY_Enter() [3/3]
void IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY_Enter (object sender, EventArgs e) inline private
References IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY.
Dispose() [3/3]
override void IG.Forms.WindowShiftControlNumeric.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.WindowShiftControlNumeric.components.
InitializeComponent() [3/3]
void IG.Forms.WindowShiftControlNumeric.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.WindowShiftControlNumeric.lblWindowRelY, IG.Forms.WindowShiftControlNumeric.lblWindowShiftRelX, IG.Forms.WindowShiftControlNumeric.pnlOuter, IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX, IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX_Enter(), IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX_Validated(), IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY, IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY_Enter(), and IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY_Validated().
Member Data Documentation
_shift
vec2 IG.Forms.WindowShiftControlNumeric._shift = new vec2(0.0, 0.0) protected
Referenced by IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX_Validated(), and IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY_Validated().
_initialValueX
double IG.Forms.WindowShiftControlNumeric._initialValueX protected
_initialValueY
double IG.Forms.WindowShiftControlNumeric._initialValueY protected
_minValue
double IG.Forms.WindowShiftControlNumeric._minValue protected
_maxValue
double IG.Forms.WindowShiftControlNumeric._maxValue protected
_increment
double IG.Forms.WindowShiftControlNumeric._increment protected
components
System ComponentModel IContainer IG.Forms.WindowShiftControlNumeric.components = null private
Required designer variable.
Referenced by IG.Forms.WindowShiftControlNumeric.Dispose().
pnlOuter
System Windows Forms GroupBox IG.Forms.WindowShiftControlNumeric.pnlOuter private
Referenced by IG.Forms.WindowShiftControlNumeric.InitializeComponent().
txtWindowShiftRelY
System Windows Forms NumericUpDown IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY private
Referenced by IG.Forms.WindowShiftControlNumeric.InitializeComponent(), IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY_Enter(), and IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelY_Validated().
lblWindowRelY
System Windows Forms Label IG.Forms.WindowShiftControlNumeric.lblWindowRelY private
Referenced by IG.Forms.WindowShiftControlNumeric.InitializeComponent().
txtWindowShiftRelX
System Windows Forms NumericUpDown IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX private
Referenced by IG.Forms.WindowShiftControlNumeric.InitializeComponent(), IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX_Enter(), and IG.Forms.WindowShiftControlNumeric.txtWindowShiftRelX_Validated().
lblWindowShiftRelX
System Windows Forms Label IG.Forms.WindowShiftControlNumeric.lblWindowShiftRelX private
Referenced by IG.Forms.WindowShiftControlNumeric.InitializeComponent().
Property Documentation
Title
string IG.Forms.WindowShiftControlNumeric.Title get set
Title text that is written on the outer group box.
Shift
vec2 IG.Forms.WindowShiftControlNumeric.Shift get set
Gets or sets the resulting shift stored in 2D vector structure of type vec2
Referenced by IG.Forms.WindowShiftControlNumeric.OnValueChanged().
InitialValueX
double IG.Forms.WindowShiftControlNumeric.InitialValueX get set
Initial value of the first component of Shift.
InitialValueY
double IG.Forms.WindowShiftControlNumeric.InitialValueY get set
Initial value of the second component of Shift.
MinimumValue
double IG.Forms.WindowShiftControlNumeric.MinimumValue get set
Minimal value of components of Shift.
MaximumValue
double IG.Forms.WindowShiftControlNumeric.MaximumValue get set
Maximal value of components of Shift.
Increment
double IG.Forms.WindowShiftControlNumeric.Increment get set
Increment for text controls for components of Shift.
Event Documentation
ValueChanged
EventHandler IG.Forms.WindowShiftControlNumeric.ValueChanged
Event that occurs when the value of window position (or shift, size, relative position, etc.) kept by this control changes.
Referenced by IG.Forms.WindowShiftControlNumeric.OnValueChanged().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/WindowPositioner/Old/ShiftControlNumeric.cs
iglib/igforms/Utilities/WindowPositioner/Old/ShiftControlNumeric.Designer.cs