Doc: IGLib EXTENDED: CShell.Modules.Repl.Module Class Reference
CShell.Modules.Repl.Module Class Reference
Public Member Functions
Module ()
override void Initialize ()
Public Member Functions inherited from CShell.Framework.ModuleBase
void Dispose ()
Private Member Functions
IEnumerable< IResult > OpenOutput ()
IEnumerable< IResult > OpenRepl ()
Additional Inherited Members
Protected Member Functions inherited from CShell.Framework.ModuleBase
virtual void Dispose (bool disposing)
Properties inherited from CShell.Framework.ModuleBase
IShell Shell [get]
IMenu MainMenu [get]
IToolBar ToolBar [get]
int Order [get, set]
Properties inherited from CShell.Framework.IModule
int Order [get]
Constructor & Destructor Documentation
Module()
CShell.Modules.Repl.Module.Module () inline
References CShell.Framework.ModuleBase.Order.
Member Function Documentation
Initialize()
override void CShell.Modules.Repl.Module.Initialize () inline virtual
Implements CShell.Framework.ModuleBase.
References CShell.Framework.Menus.IMenu.All, CShell.Framework.ModuleBase.MainMenu, CShell.Modules.Repl.Module.OpenOutput(), and CShell.Modules.Repl.Module.OpenRepl().
OpenOutput()
IEnumerable<IResult> CShell.Modules.Repl.Module.OpenOutput () inline private
Referenced by CShell.Modules.Repl.Module.Initialize().
OpenRepl()
IEnumerable<IResult> CShell.Modules.Repl.Module.OpenRepl () inline private
Referenced by CShell.Modules.Repl.Module.Initialize().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Repl/Module.cs