Doc: IGLib EXTENDED: alglib.testpsplineunit Class Reference
alglib.testpsplineunit Class Reference
Static Public Member Functions
static bool testpspline (bool silent)
static bool testpspline (bool silent)
static bool _pexec_testpspline (bool silent)
Static Private Member Functions
static void unsetp2 (pspline.pspline2interpolant p)
static void unsetp3 (pspline.pspline3interpolant p)
static void unset1d (ref double[] x)
static void unsetp2 (pspline.pspline2interpolant p)
static void unsetp3 (pspline.pspline3interpolant p)
static void unset1d (ref double[] x)
Member Function Documentation
testpspline() [1/2]
static bool alglib.testpsplineunit.testpspline (bool silent) inline static
References alglib.ap.assert(), alglib.math.machineepsilon, alglib.pspline.pspline2arclength(), alglib.pspline.pspline2build(), alglib.pspline.pspline2buildperiodic(), alglib.pspline.pspline2calc(), alglib.pspline.pspline2diff(), alglib.pspline.pspline2diff2(), alglib.pspline.pspline2parametervalues(), alglib.pspline.pspline2tangent(), alglib.pspline.pspline3arclength(), alglib.pspline.pspline3build(), alglib.pspline.pspline3buildperiodic(), alglib.pspline.pspline3calc(), alglib.pspline.pspline3diff(), alglib.pspline.pspline3diff2(), alglib.pspline.pspline3parametervalues(), alglib.pspline.pspline3tangent(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.apserv.safepythag2(), alglib.apserv.safepythag3(), alglib.spline1d.spline1dbuildcubic(), alglib.spline1d.spline1ddiff(), alglib.apserv.taskgenint1dequidist(), alglib.testpsplineunit.unsetp2(), and alglib.testpsplineunit.unsetp3().
Referenced by alglib.testpsplineunit._pexec_testpspline(), and _Test.Main().
unsetp2() [1/2]
static void alglib.testpsplineunit.unsetp2 (pspline.pspline2interpolant p) inline static private
References alglib.pspline.pspline2build().
Referenced by alglib.testpsplineunit.testpspline().
unsetp3() [1/2]
static void alglib.testpsplineunit.unsetp3 (pspline.pspline3interpolant p) inline static private
References alglib.pspline.pspline3build().
Referenced by alglib.testpsplineunit.testpspline().
unset1d() [1/2]
static void alglib.testpsplineunit.unset1d (ref double[] x) inline static private
References alglib.math.randomreal().
testpspline() [2/2]
static bool alglib.testpsplineunit.testpspline (bool silent) inline static
References alglib.ap.assert(), alglib.math.machineepsilon, alglib.pspline.pspline2arclength(), alglib.pspline.pspline2build(), alglib.pspline.pspline2buildperiodic(), alglib.pspline.pspline2calc(), alglib.pspline.pspline2diff(), alglib.pspline.pspline2diff2(), alglib.pspline.pspline2parametervalues(), alglib.pspline.pspline2tangent(), alglib.pspline.pspline3arclength(), alglib.pspline.pspline3build(), alglib.pspline.pspline3buildperiodic(), alglib.pspline.pspline3calc(), alglib.pspline.pspline3diff(), alglib.pspline.pspline3diff2(), alglib.pspline.pspline3parametervalues(), alglib.pspline.pspline3tangent(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.apserv.safepythag2(), alglib.apserv.safepythag3(), alglib.spline1d.spline1dbuildcubic(), alglib.spline1d.spline1ddiff(), alglib.apserv.taskgenint1dequidist(), alglib.testpsplineunit.unsetp2(), and alglib.testpsplineunit.unsetp3().
_pexec_testpspline()
static bool alglib.testpsplineunit._pexec_testpspline (bool silent) inline static
References alglib.testpsplineunit.testpspline().
Referenced by _Test.Main().
unsetp2() [2/2]
static void alglib.testpsplineunit.unsetp2 (pspline.pspline2interpolant p) inline static private
References alglib.pspline.pspline2build().
unsetp3() [2/2]
static void alglib.testpsplineunit.unsetp3 (pspline.pspline3interpolant p) inline static private
References alglib.pspline.pspline3build().
unset1d() [2/2]
static void alglib.testpsplineunit.unset1d (ref double[] x) inline static private
References alglib.math.randomreal().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs