Doc: IGLib EXTENDED: NUnit.Framework.Internal.Builders.NamespaceTreeBuilder Class Reference
NUnit.Framework.Internal.Builders.NamespaceTreeBuilder Class Reference
Class that can build a tree of automatic namespace suites from a group of fixtures.
Public Member Functions
NamespaceTreeBuilder (TestSuite rootSuite)
Initializes a new instance of the NamespaceTreeBuilder class.
void Add (IList< Test > fixtures)
Adds the specified fixtures to the tree.
void Add (TestSuite fixture)
Adds the specified fixture to the tree.
Properties
TestSuite RootSuite [get]
Gets the root entry in the tree created by the NamespaceTreeBuilder.
Private Member Functions
TestSuite BuildFromNameSpace (string ns)
void AddSetUpFixture (TestSuite newSetupFixture, TestSuite containingSuite, string ns)
Static Private Member Functions
static string GetNamespaceForFixture (TestSuite fixture)
Private Attributes
Dictionary< string, TestSuite > namespaceSuites = new Dictionary<string, TestSuite>()
NamespaceDictionary of all test suites we have created to represent namespaces. Used to locate namespace parent suites for fixtures.
TestSuite rootSuite
The root of the test suite being created by this builder.
Detailed Description
Class that can build a tree of automatic namespace suites from a group of fixtures.
Constructor & Destructor Documentation
NamespaceTreeBuilder()
NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.NamespaceTreeBuilder (TestSuite rootSuite) inline
Initializes a new instance of the NamespaceTreeBuilder class.
Parameters
rootSuite The root suite.
References NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.rootSuite.
Member Function Documentation
Add() [1/2]
void NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.Add (IList< Test > fixtures) inline
Adds the specified fixtures to the tree.
Parameters
fixtures The fixtures to be added.
Referenced by NUnit.Framework.Api.DefaultTestAssemblyBuilder.BuildTestAssembly().
Add() [2/2]
void NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.Add (TestSuite fixture) inline
Adds the specified fixture to the tree.
Parameters
fixture The fixture to be added.
References NUnit.Framework.Internal.TestSuite.Add(), NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.AddSetUpFixture(), NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.BuildFromNameSpace(), and NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.GetNamespaceForFixture().
GetNamespaceForFixture()
static string NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.GetNamespaceForFixture (TestSuite fixture) inline static private
References NUnit.Framework.Internal.Test.FullName.
Referenced by NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.Add().
BuildFromNameSpace()
TestSuite NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.BuildFromNameSpace (string ns) inline private
References NUnit.Framework.Internal.TestSuite.Add(), NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.namespaceSuites, and NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.rootSuite.
Referenced by NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.Add().
AddSetUpFixture()
void NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.AddSetUpFixture (TestSuite newSetupFixture, TestSuite containingSuite, string ns) inline private
References NUnit.Framework.Internal.TestSuite.Add(), NUnit.Framework.Interfaces.ITest.Name, NUnit.Framework.Internal.Test.Name, NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.namespaceSuites, NUnit.Framework.Internal.Test.Parent, NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.rootSuite, and NUnit.Framework.Internal.TestSuite.Tests.
Referenced by NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.Add().
Member Data Documentation
namespaceSuites
Dictionary<string, TestSuite> NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.namespaceSuites = new Dictionary<string, TestSuite>() private
NamespaceDictionary of all test suites we have created to represent namespaces. Used to locate namespace parent suites for fixtures.
Referenced by NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.AddSetUpFixture(), and NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.BuildFromNameSpace().
rootSuite
TestSuite NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.rootSuite private
The root of the test suite being created by this builder.
Referenced by NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.AddSetUpFixture(), NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.BuildFromNameSpace(), and NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.NamespaceTreeBuilder().
Property Documentation
RootSuite
TestSuite NUnit.Framework.Internal.Builders.NamespaceTreeBuilder.RootSuite get
Gets the root entry in the tree created by the NamespaceTreeBuilder.
The root suite.
Referenced by NUnit.Framework.Api.DefaultTestAssemblyBuilder.BuildTestAssembly().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/Builders/NamespaceTreeBuilder.cs