Doc: IGLib EXTENDED: IG.Forms.TestLayoutControl Class Reference
IG.Forms.TestLayoutControl Class Reference
Public Member Functions
TestLayoutControl ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void pnlOuter_Paint (object sender, PaintEventArgs e)
void pnlBtnOutepPanel_Paint (object sender, PaintEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Button btnTestLayoutControl
System.Windows.Forms.Panel pnlControls
System.Windows.Forms.Button btnZoomOut
System.Windows.Forms.Button btnZoomIn
System.Windows.Forms.Button btnControls2
System.Windows.Forms.Button btnControls1
System.Windows.Forms.Panel pnlOuter
System.Windows.Forms.Button btnPnlOuter
System.Windows.Forms.Button brnPnlControls
System.Windows.Forms.Panel pnlBtnOutepPanel
Constructor & Destructor Documentation
TestLayoutControl()
IG.Forms.TestLayoutControl.TestLayoutControl () inline
References IG.Forms.TestLayoutControl.InitializeComponent().
Member Function Documentation
pnlOuter_Paint()
void IG.Forms.TestLayoutControl.pnlOuter_Paint (object sender, PaintEventArgs e) inline private
Referenced by IG.Forms.TestLayoutControl.InitializeComponent().
pnlBtnOutepPanel_Paint()
void IG.Forms.TestLayoutControl.pnlBtnOutepPanel_Paint (object sender, PaintEventArgs e) inline private
Referenced by IG.Forms.TestLayoutControl.InitializeComponent().
Dispose()
override void IG.Forms.TestLayoutControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.TestLayoutControl.components.
InitializeComponent()
void IG.Forms.TestLayoutControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.TestLayoutControl.brnPnlControls, IG.Forms.TestLayoutControl.btnControls1, IG.Forms.TestLayoutControl.btnControls2, IG.Forms.TestLayoutControl.btnPnlOuter, IG.Forms.TestLayoutControl.btnTestLayoutControl, IG.Forms.TestLayoutControl.btnZoomIn, IG.Forms.TestLayoutControl.btnZoomOut, IG.Forms.TestLayoutControl.pnlBtnOutepPanel, IG.Forms.TestLayoutControl.pnlBtnOutepPanel_Paint(), IG.Forms.TestLayoutControl.pnlControls, IG.Forms.TestLayoutControl.pnlOuter, and IG.Forms.TestLayoutControl.pnlOuter_Paint().
Referenced by IG.Forms.TestLayoutControl.TestLayoutControl().
Member Data Documentation
components
System.ComponentModel.IContainer IG.Forms.TestLayoutControl.components = null private
Required designer variable.
Referenced by IG.Forms.TestLayoutControl.Dispose().
btnTestLayoutControl
System.Windows.Forms.Button IG.Forms.TestLayoutControl.btnTestLayoutControl private
Referenced by IG.Forms.TestLayoutControl.InitializeComponent().
pnlControls
System.Windows.Forms.Panel IG.Forms.TestLayoutControl.pnlControls private
Referenced by IG.Forms.TestLayoutControl.InitializeComponent().
btnZoomOut
System.Windows.Forms.Button IG.Forms.TestLayoutControl.btnZoomOut private
Referenced by IG.Forms.TestLayoutControl.InitializeComponent().
btnZoomIn
System.Windows.Forms.Button IG.Forms.TestLayoutControl.btnZoomIn private
Referenced by IG.Forms.TestLayoutControl.InitializeComponent().
btnControls2
System.Windows.Forms.Button IG.Forms.TestLayoutControl.btnControls2 private
Referenced by IG.Forms.TestLayoutControl.InitializeComponent().
btnControls1
System.Windows.Forms.Button IG.Forms.TestLayoutControl.btnControls1 private
Referenced by IG.Forms.TestLayoutControl.InitializeComponent().
pnlOuter
System.Windows.Forms.Panel IG.Forms.TestLayoutControl.pnlOuter private
Referenced by IG.Forms.TestLayoutControl.InitializeComponent().
btnPnlOuter
System.Windows.Forms.Button IG.Forms.TestLayoutControl.btnPnlOuter private
Referenced by IG.Forms.TestLayoutControl.InitializeComponent().
brnPnlControls
System.Windows.Forms.Button IG.Forms.TestLayoutControl.brnPnlControls private
Referenced by IG.Forms.TestLayoutControl.InitializeComponent().
pnlBtnOutepPanel
System.Windows.Forms.Panel IG.Forms.TestLayoutControl.pnlBtnOutepPanel private
Referenced by IG.Forms.TestLayoutControl.InitializeComponent().
The documentation for this class was generated from the following files:
iglib/igforms/0Testing/TestLayoutControl.cs
iglib/igforms/0Testing/TestLayoutControl.Designer.cs