Doc: IGLib EXTENDED: NUnit.Framework.Attributes.TestCaseAttributeTests Class Reference
NUnit.Framework.Attributes.TestCaseAttributeTests Class Reference
Public Member Functions
void IntegerDivisionWithResultPassedToTest (int n, int d, int q)
int IntegerDivisionWithResultCheckedByNUnit (int n, int d)
double CanConvertIntToDouble (double x, double y)
decimal CanConvertStringToDecimal (decimal x, decimal y)
decimal CanConvertDoubleToDecimal (decimal x, decimal y)
decimal CanConvertIntToDecimal (decimal x, decimal y)
short CanConvertSmallIntsToShort (short x, short y)
byte CanConvertSmallIntsToByte (byte x, byte y)
sbyte CanConvertSmallIntsToSByte (sbyte x, sbyte y)
void TestCaseRunnableState (string methodName, RunState expectedState)
void CanConvertStringToDateTime (DateTime dt)
void CanConvertStringToTimeSpan (TimeSpan ts)
void CanPassNullAsFirstArgument (object a)
void CanPassObjectArrayAsFirstArgument (object[] a)
void CanPassArrayAsArgument (object[] array)
void ArgumentsAreCoalescedInObjectArray (object[] array)
void ArgumentsOfDifferentTypeAreCoalescedInObjectArray (object[] array)
object ResultCanBeNull ()
void HandlesParamsArrayAsSoleArgument (params string[] array)
void HandlesParamsArrayWithOneItemAsSoleArgument (params string[] array)
void HandlesParamsArrayAsLastArgument (string s1, string s2, params object[] array)
void HandlesParamsArrayWithNoItemsAsLastArgument (string s1, string s2, params object[] array)
void HandlesParamsArrayWithOneItemAsLastArgument (string s1, string s2, params object[] array)
void CanSpecifyDescription ()
void CanSpecifyTestName_FixedText ()
void CanSpecifyTestName_WithMethodName ()
void CanSpecifyCategory ()
void CanSpecifyMultipleCategories ()
void CanIgnoreIndividualTestCases ()
void CanMarkIndividualTestCasesExplicit ()
void CanIncludePlatform ()
void CanExcludePlatform ()
void NullableIntegerDivisionWithResultPassedToTest (int? n, int? d, int? q)
int? NullableIntegerDivisionWithResultCheckedByNUnit (int? n, int? d)
double? CanConvertIntToNullableDouble (double? x, double? y)
void CanConvertIntToNullableShort (short? x)
void CanConvertIntToNullableByte (byte? x)
void CanConvertIntToNullableSByte (sbyte? x)
decimal? CanConvertStringToNullableDecimal (decimal? x, decimal? y)
void SupportsNullableDecimal (decimal? x)
decimal? CanConvertDoubleToNullableDecimal (decimal? x, decimal? y)
decimal? CanConvertIntToNullableDecimal (decimal? x, decimal? y)
short? CanConvertSmallIntsToNullableShort (short? x, short? y)
byte? CanConvertSmallIntsToNullableByte (byte? x, byte? y)
sbyte? CanConvertSmallIntsToNullableSByte (sbyte? x, sbyte? y)
void CanConvertStringToNullableDateTime (DateTime? dt)
void SupportsNullableDateTime (DateTime? dt)
void CanConvertStringToNullableTimeSpan (TimeSpan? ts)
void SupportsNullableTimeSpan (TimeSpan? dt)
void NullableSimpleFormalParametersWithArgument (int? a)
void NullableSimpleFormalParametersWithNullArgument (int? a)
int? TestCaseWithNullableReturnValue (int? a)
Member Function Documentation
IntegerDivisionWithResultPassedToTest()
void NUnit.Framework.Attributes.TestCaseAttributeTests.IntegerDivisionWithResultPassedToTest (int n, int d, int q) inline
References NUnit.Framework.Assert.AreEqual().
IntegerDivisionWithResultCheckedByNUnit()
int NUnit.Framework.Attributes.TestCaseAttributeTests.IntegerDivisionWithResultCheckedByNUnit (int n, int d) inline
CanConvertIntToDouble()
double NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertIntToDouble (double x, double y) inline
CanConvertStringToDecimal()
decimal NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertStringToDecimal (decimal x, decimal y) inline
CanConvertDoubleToDecimal()
decimal NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertDoubleToDecimal (decimal x, decimal y) inline
CanConvertIntToDecimal()
decimal NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertIntToDecimal (decimal x, decimal y) inline
CanConvertSmallIntsToShort()
short NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertSmallIntsToShort (short x, short y) inline
CanConvertSmallIntsToByte()
byte NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertSmallIntsToByte (byte x, byte y) inline
CanConvertSmallIntsToSByte()
sbyte NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertSmallIntsToSByte (sbyte x, sbyte y) inline
TestCaseRunnableState()
void NUnit.Framework.Attributes.TestCaseAttributeTests.TestCaseRunnableState (string methodName, RunState expectedState) inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite().
CanConvertStringToDateTime()
void NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertStringToDateTime (DateTime dt) inline
References NUnit.Framework.Assert.AreEqual().
CanConvertStringToTimeSpan()
void NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertStringToTimeSpan (TimeSpan ts) inline
References NUnit.Framework.Assert.AreEqual().
CanPassNullAsFirstArgument()
void NUnit.Framework.Attributes.TestCaseAttributeTests.CanPassNullAsFirstArgument (object a) inline
References NUnit.Framework.Assert.IsNull().
CanPassObjectArrayAsFirstArgument()
void NUnit.Framework.Attributes.TestCaseAttributeTests.CanPassObjectArrayAsFirstArgument (object[] a) inline
CanPassArrayAsArgument()
void NUnit.Framework.Attributes.TestCaseAttributeTests.CanPassArrayAsArgument (object[] array) inline
References NUnit.Framework.Assert.AreEqual().
ArgumentsAreCoalescedInObjectArray()
void NUnit.Framework.Attributes.TestCaseAttributeTests.ArgumentsAreCoalescedInObjectArray (object[] array) inline
References NUnit.Framework.Assert.AreEqual().
ArgumentsOfDifferentTypeAreCoalescedInObjectArray()
void NUnit.Framework.Attributes.TestCaseAttributeTests.ArgumentsOfDifferentTypeAreCoalescedInObjectArray (object[] array) inline
References NUnit.Framework.Assert.AreEqual().
ResultCanBeNull()
object NUnit.Framework.Attributes.TestCaseAttributeTests.ResultCanBeNull () inline
HandlesParamsArrayAsSoleArgument()
void NUnit.Framework.Attributes.TestCaseAttributeTests.HandlesParamsArrayAsSoleArgument (params string[] array) inline
References NUnit.Framework.Assert.AreEqual().
HandlesParamsArrayWithOneItemAsSoleArgument()
void NUnit.Framework.Attributes.TestCaseAttributeTests.HandlesParamsArrayWithOneItemAsSoleArgument (params string[] array) inline
References NUnit.Framework.Assert.AreEqual().
HandlesParamsArrayAsLastArgument()
void NUnit.Framework.Attributes.TestCaseAttributeTests.HandlesParamsArrayAsLastArgument (string s1, string s2, params object[] array) inline
References NUnit.Framework.Assert.AreEqual().
HandlesParamsArrayWithNoItemsAsLastArgument()
void NUnit.Framework.Attributes.TestCaseAttributeTests.HandlesParamsArrayWithNoItemsAsLastArgument (string s1, string s2, params object[] array) inline
References NUnit.Framework.Assert.AreEqual().
HandlesParamsArrayWithOneItemAsLastArgument()
void NUnit.Framework.Attributes.TestCaseAttributeTests.HandlesParamsArrayWithOneItemAsLastArgument (string s1, string s2, params object[] array) inline
References NUnit.Framework.Assert.AreEqual().
CanSpecifyDescription()
void NUnit.Framework.Attributes.TestCaseAttributeTests.CanSpecifyDescription () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.PropertyNames.Description, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), and NUnit.Framework.Internal.Test.Properties.
CanSpecifyTestName_FixedText()
void NUnit.Framework.Attributes.TestCaseAttributeTests.CanSpecifyTestName_FixedText () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.Test.FullName, NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), and NUnit.Framework.Internal.Test.Name.
CanSpecifyTestName_WithMethodName()
void NUnit.Framework.Attributes.TestCaseAttributeTests.CanSpecifyTestName_WithMethodName () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.Test.FullName, NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), and NUnit.Framework.Internal.Test.Name.
CanSpecifyCategory()
void NUnit.Framework.Attributes.TestCaseAttributeTests.CanSpecifyCategory () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), and NUnit.Framework.Internal.Test.Properties.
CanSpecifyMultipleCategories()
void NUnit.Framework.Attributes.TestCaseAttributeTests.CanSpecifyMultipleCategories () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), and NUnit.Framework.Internal.Test.Properties.
CanIgnoreIndividualTestCases()
void NUnit.Framework.Attributes.TestCaseAttributeTests.CanIgnoreIndividualTestCases () inline
References NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestFinder.Find(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Internal.PropertyNames.SkipReason, and NUnit.Framework.Assert.That().
CanMarkIndividualTestCasesExplicit()
void NUnit.Framework.Attributes.TestCaseAttributeTests.CanMarkIndividualTestCasesExplicit () inline
References NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestFinder.Find(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Internal.PropertyNames.SkipReason, and NUnit.Framework.Assert.That().
CanIncludePlatform()
void NUnit.Framework.Attributes.TestCaseAttributeTests.CanIncludePlatform () inline
References NUnit.Framework.Internal.OSPlatform.CurrentPlatform, NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestFinder.Find(), NUnit.Framework.Internal.OSPlatform.IsMacOSX, NUnit.Framework.Internal.OSPlatform.IsUnix, NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), NUnit.Framework.Internal.Test.RunState, and NUnit.Framework.Assert.That().
CanExcludePlatform()
void NUnit.Framework.Attributes.TestCaseAttributeTests.CanExcludePlatform () inline
References NUnit.Framework.Internal.OSPlatform.CurrentPlatform, NUnit.Framework.Is.EqualTo(), NUnit.TestUtilities.TestFinder.Find(), NUnit.Framework.Internal.OSPlatform.IsMacOSX, NUnit.Framework.Internal.OSPlatform.IsUnix, NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), NUnit.Framework.Internal.Test.RunState, and NUnit.Framework.Assert.That().
NullableIntegerDivisionWithResultPassedToTest()
void NUnit.Framework.Attributes.TestCaseAttributeTests.NullableIntegerDivisionWithResultPassedToTest (int? n, int? d, int? q) inline
References NUnit.Framework.Assert.AreEqual().
NullableIntegerDivisionWithResultCheckedByNUnit()
int? NUnit.Framework.Attributes.TestCaseAttributeTests.NullableIntegerDivisionWithResultCheckedByNUnit (int? n, int? d) inline
CanConvertIntToNullableDouble()
double? NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertIntToNullableDouble (double? x, double? y) inline
CanConvertIntToNullableShort()
void NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertIntToNullableShort (short? x) inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
CanConvertIntToNullableByte()
void NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertIntToNullableByte (byte? x) inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
CanConvertIntToNullableSByte()
void NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertIntToNullableSByte (sbyte? x) inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
CanConvertStringToNullableDecimal()
decimal? NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertStringToNullableDecimal (decimal? x, decimal? y) inline
References NUnit.Framework.Assert.That().
SupportsNullableDecimal()
void NUnit.Framework.Attributes.TestCaseAttributeTests.SupportsNullableDecimal (decimal? x) inline
References NUnit.Framework.Is.False, and NUnit.Framework.Assert.That().
CanConvertDoubleToNullableDecimal()
decimal? NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertDoubleToNullableDecimal (decimal? x, decimal? y) inline
CanConvertIntToNullableDecimal()
decimal? NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertIntToNullableDecimal (decimal? x, decimal? y) inline
CanConvertSmallIntsToNullableShort()
short? NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertSmallIntsToNullableShort (short? x, short? y) inline
CanConvertSmallIntsToNullableByte()
byte? NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertSmallIntsToNullableByte (byte? x, byte? y) inline
CanConvertSmallIntsToNullableSByte()
sbyte? NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertSmallIntsToNullableSByte (sbyte? x, sbyte? y) inline
CanConvertStringToNullableDateTime()
void NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertStringToNullableDateTime (DateTime? dt) inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.That().
SupportsNullableDateTime()
void NUnit.Framework.Attributes.TestCaseAttributeTests.SupportsNullableDateTime (DateTime? dt) inline
References NUnit.Framework.Is.False, and NUnit.Framework.Assert.That().
CanConvertStringToNullableTimeSpan()
void NUnit.Framework.Attributes.TestCaseAttributeTests.CanConvertStringToNullableTimeSpan (TimeSpan? ts) inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Assert.That().
SupportsNullableTimeSpan()
void NUnit.Framework.Attributes.TestCaseAttributeTests.SupportsNullableTimeSpan (TimeSpan? dt) inline
References NUnit.Framework.Is.False, and NUnit.Framework.Assert.That().
NullableSimpleFormalParametersWithArgument()
void NUnit.Framework.Attributes.TestCaseAttributeTests.NullableSimpleFormalParametersWithArgument (int? a) inline
References NUnit.Framework.Assert.AreEqual().
NullableSimpleFormalParametersWithNullArgument()
void NUnit.Framework.Attributes.TestCaseAttributeTests.NullableSimpleFormalParametersWithNullArgument (int? a) inline
References NUnit.Framework.Assert.IsNull().
TestCaseWithNullableReturnValue()
int? NUnit.Framework.Attributes.TestCaseAttributeTests.TestCaseWithNullableReturnValue (int? a) inline
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/TestCaseAttributeTests.cs