Doc: IGLib EXTENDED: AForge.Video.Kinect.Kinect Class Reference
AForge.Video.Kinect.Kinect Class Reference
The class provides access to Microsoft's Xbox Kinect controller.
Classes
class DeviceContext
Public Member Functions
void Dispose ()
Dispose device freeing all associated unmanaged resources.
void SetLedColor (LedColorOption ledColor)
Set color of Kinect's LED.
void SetMotorTilt (int angle)
Set motor's tilt value.
void GetAccelerometerValues (out double x, out double y, out double z)
Get accelerometer values for 3 axes.
KinectVideoCamera GetVideoCamera ()
Get Kinect's video camera.
KinectDepthCamera GetDepthCamera ()
Get Kinect's depth camera.
Static Public Member Functions
static Kinect GetDevice (int deviceID)
Get initialized instance of the Kinect device.
Properties
int DeviceID [get]
ID of the opened Kinect device.
static int DeviceCount [get]
Number of Kinect devices available in the system.
Private Member Functions
Kinect (IntPtr rawDevice, int deviceID)
~Kinect ()
Object finalizer/destructor makes sure unmanaged resource are freed if user did not call Dispose().
void Dispose (bool disposing)
void CheckDevice ()
void Kinect_OnError (IntPtr device)
Static Private Member Functions
static void StartStatusThread ()
static void StopStatusThread ()
static void KinectStatusThread ()
Private Attributes
IntPtr rawDevice
readonly int deviceID
object sync = new object()
Static Private Attributes
static Dictionary< int, DeviceContext > openDevices = new Dictionary<int, DeviceContext>()
static Thread updateStatusThread
static ManualResetEvent stopEvent
const double CountsPerGravity = 819.0
const double Gravity = 9.80665
static object statusThreadSync = new object()
Detailed Description
The class provides access to Microsoft's Xbox Kinect controller.
The class allows to manipulate Kinec device by changing its LED color, setting motor's tilt value and accessing its camera. See KinectVideoCamera and KinectDepthCamera classes, which provide access to actual video.
<note>In order to run correctly the class requires freenect.dll library to be put into solution's output folder. This can be found within the AForge.NET framework's distribution in Externals folder.</note>
Sample usage:
// get Kinect device
Kinect kinectDevice = Kinect.GetDevice(0);
// change LED color
kinectDevice.LedColor = LedColorOption.Yellow;
// set motor tilt angle to -10 degrees
kinectDevice.SetMotorTilt(-10);
// get video camera
KinectVideoCamera videoCamera = kinectDevice.GetVideoCamera();
// see example for video camera also
Constructor & Destructor Documentation
Kinect()
AForge.Video.Kinect.Kinect.Kinect (IntPtr rawDevice, int deviceID) inline private
References AForge.Video.Kinect.Kinect.deviceID, AForge.Video.Kinect.Kinect.Kinect_OnError(), and AForge.Video.Kinect.Kinect.rawDevice.
Referenced by AForge.Video.Kinect.Kinect.GetDevice().
~Kinect()
AForge.Video.Kinect.Kinect.~Kinect () inline private
Object finalizer/destructor makes sure unmanaged resource are freed if user did not call Dispose().
References AForge.Video.Kinect.Kinect.Dispose().
Member Function Documentation
GetDevice()
static Kinect AForge.Video.Kinect.Kinect.GetDevice (int deviceID) inline static
Get initialized instance of the Kinect device.
Parameters
deviceID ID of the Kinect device to get instance of, [0, DeviceCount),
Returns
Returns initialized Kinect device. Use Dispose() method when the device is no longer required.
Exceptions
ArgumentException There is no Kinect device with specified ID connected to the system.
ConnectionFailedException Failed connecting to the Kinect device specified ID.
References AForge.Video.Kinect.Kinect.DeviceCount, AForge.Video.Kinect.Kinect.deviceID, AForge.Video.Kinect.Kinect.Kinect(), AForge.Video.Kinect.Kinect.openDevices, and AForge.Video.Kinect.Kinect.StartStatusThread().
Referenced by KinectCapture.MainForm.Connect(), AForge.Video.Kinect.KinectDepthCamera.Start(), and AForge.Video.Kinect.KinectVideoCamera.Start().
Dispose() [1/2]
void AForge.Video.Kinect.Kinect.Dispose () inline
Dispose device freeing all associated unmanaged resources.
References AForge.Video.Kinect.Kinect.Kinect_OnError(), AForge.Video.Kinect.Kinect.rawDevice, and AForge.Video.Kinect.Kinect.sync.
Referenced by KinectCapture.MainForm.Disconnect(), AForge.Video.Kinect.KinectDepthCamera.Start(), AForge.Video.Kinect.KinectVideoCamera.Start(), AForge.Video.Kinect.KinectDepthCamera.Stop(), AForge.Video.Kinect.KinectVideoCamera.Stop(), and AForge.Video.Kinect.Kinect.~Kinect().
Dispose() [2/2]
void AForge.Video.Kinect.Kinect.Dispose (bool disposing) inline private
References AForge.Video.Kinect.Kinect.deviceID, AForge.Video.Kinect.Kinect.openDevices, AForge.Video.Kinect.Kinect.rawDevice, and AForge.Video.Kinect.Kinect.StopStatusThread().
CheckDevice()
void AForge.Video.Kinect.Kinect.CheckDevice () inline private
References AForge.Video.Kinect.Kinect.rawDevice.
Referenced by AForge.Video.Kinect.Kinect.GetAccelerometerValues(), AForge.Video.Kinect.Kinect.SetLedColor(), and AForge.Video.Kinect.Kinect.SetMotorTilt().
SetLedColor()
void AForge.Video.Kinect.Kinect.SetLedColor (LedColorOption ledColor) inline
Set color of Kinect's LED.
Parameters
ledColor LED color to set.
Exceptions
DeviceErrorException Some error occurred with the device. Check error message.
References AForge.Video.Kinect.Kinect.CheckDevice(), AForge.Video.Kinect.Kinect.rawDevice, and AForge.Video.Kinect.Kinect.sync.
Referenced by KinectCapture.MainForm.ledColorCombo_SelectedIndexChanged().
SetMotorTilt()
void AForge.Video.Kinect.Kinect.SetMotorTilt (int angle) inline
Set motor's tilt value.
Parameters
angle Tilt value to set, [-31, 30] degrees.
Exceptions
ArgumentOutOfRangeException Motor tilt has to be in the [-31, 31] range.
DeviceErrorException Some error occurred with the device. Check error message.
References AForge.Video.Kinect.Kinect.CheckDevice(), AForge.Video.Kinect.Kinect.rawDevice, and AForge.Video.Kinect.Kinect.sync.
Referenced by KinectCapture.MainForm.Connect(), and KinectCapture.MainForm.tiltUpDown_ValueChanged().
GetAccelerometerValues()
void AForge.Video.Kinect.Kinect.GetAccelerometerValues (out double x, out double y, out double z) inline
Get accelerometer values for 3 axes.
Parameters
x X axis value on the accelerometer.
y Y axis value on the accelerometer.
z Z axis value on the accelerometer.
Units of all 3 values are m/s2. The g value used for calculations is taken as 9.80665 m/s2.
References AForge.Video.Kinect.Kinect.CheckDevice(), AForge.Video.Kinect.Kinect.CountsPerGravity, AForge.Video.Kinect.Kinect.deviceID, AForge.Video.Kinect.Kinect.Gravity, AForge.Video.Kinect.Kinect.openDevices, and AForge.Video.Kinect.Kinect.sync.
Referenced by KinectCapture.MainForm.timer_Tick().
GetVideoCamera()
KinectVideoCamera AForge.Video.Kinect.Kinect.GetVideoCamera () inline
Get Kinect's video camera.
Returns
Returns Kinect's video camera.
The method simply creates instance of the KinectVideoCamera class by calling its appropriate constructor. Use KinectVideoCamera.Start method to start the video then.
References AForge.Video.Kinect.Kinect.deviceID.
Referenced by KinectCapture.MainForm.Connect().
GetDepthCamera()
KinectDepthCamera AForge.Video.Kinect.Kinect.GetDepthCamera () inline
Get Kinect's depth camera.
Returns
Returns Kinect's depth camera.
The method simply creates instance of the KinectDepthCamera class by calling its appropriate constructor. Use KinectDepthCamera.Start method to start the video then.
References AForge.Video.Kinect.Kinect.deviceID.
Referenced by KinectCapture.MainForm.Connect().
StartStatusThread()
static void AForge.Video.Kinect.Kinect.StartStatusThread () inline static private
References AForge.Video.Kinect.Kinect.KinectStatusThread(), AForge.Video.Kinect.Kinect.statusThreadSync, AForge.Video.Kinect.Kinect.stopEvent, and AForge.Video.Kinect.Kinect.updateStatusThread.
Referenced by AForge.Video.Kinect.Kinect.GetDevice().
StopStatusThread()
static void AForge.Video.Kinect.Kinect.StopStatusThread () inline static private
References AForge.Video.Kinect.Kinect.statusThreadSync, AForge.Video.Kinect.Kinect.stopEvent, and AForge.Video.Kinect.Kinect.updateStatusThread.
Referenced by AForge.Video.Kinect.Kinect.Dispose().
KinectStatusThread()
static void AForge.Video.Kinect.Kinect.KinectStatusThread () inline static private
References AForge.Video.Kinect.Kinect.DeviceContext.Device, AForge.Video.Kinect.Kinect.DeviceContext.DeviceFailed, AForge.Video.Kinect.Kinect.DeviceContext.FireFailureHandlers(), AForge.Video.Kinect.Kinect.openDevices, AForge.Video.Kinect.Kinect.stopEvent, and AForge.Video.Kinect.Kinect.DeviceContext.TiltState.
Referenced by AForge.Video.Kinect.Kinect.StartStatusThread().
Kinect_OnError()
void AForge.Video.Kinect.Kinect.Kinect_OnError (IntPtr device) inline private
References AForge.Video.Kinect.Kinect.deviceID, and AForge.Video.Kinect.Kinect.rawDevice.
Referenced by AForge.Video.Kinect.Kinect.Dispose(), and AForge.Video.Kinect.Kinect.Kinect().
Member Data Documentation
openDevices
Dictionary<int, DeviceContext> AForge.Video.Kinect.Kinect.openDevices = new Dictionary<int, DeviceContext>() static private
Referenced by AForge.Video.Kinect.Kinect.Dispose(), AForge.Video.Kinect.Kinect.GetAccelerometerValues(), AForge.Video.Kinect.Kinect.GetDevice(), and AForge.Video.Kinect.Kinect.KinectStatusThread().
updateStatusThread
Thread AForge.Video.Kinect.Kinect.updateStatusThread static private
Referenced by AForge.Video.Kinect.Kinect.StartStatusThread(), and AForge.Video.Kinect.Kinect.StopStatusThread().
stopEvent
ManualResetEvent AForge.Video.Kinect.Kinect.stopEvent static private
Referenced by AForge.Video.Kinect.Kinect.KinectStatusThread(), AForge.Video.Kinect.Kinect.StartStatusThread(), and AForge.Video.Kinect.Kinect.StopStatusThread().
rawDevice
IntPtr AForge.Video.Kinect.Kinect.rawDevice private
Referenced by AForge.Video.Kinect.Kinect.CheckDevice(), AForge.Video.Kinect.Kinect.Dispose(), AForge.Video.Kinect.Kinect.Kinect(), AForge.Video.Kinect.Kinect.Kinect_OnError(), AForge.Video.Kinect.Kinect.SetLedColor(), and AForge.Video.Kinect.Kinect.SetMotorTilt().
deviceID
readonly int AForge.Video.Kinect.Kinect.deviceID private
Referenced by AForge.Video.Kinect.Kinect.Dispose(), AForge.Video.Kinect.Kinect.GetAccelerometerValues(), AForge.Video.Kinect.Kinect.GetDepthCamera(), AForge.Video.Kinect.Kinect.GetDevice(), AForge.Video.Kinect.Kinect.GetVideoCamera(), AForge.Video.Kinect.Kinect.Kinect(), and AForge.Video.Kinect.Kinect.Kinect_OnError().
sync
object AForge.Video.Kinect.Kinect.sync = new object() private
Referenced by AForge.Video.Kinect.Kinect.Dispose(), AForge.Video.Kinect.Kinect.GetAccelerometerValues(), AForge.Video.Kinect.Kinect.SetLedColor(), and AForge.Video.Kinect.Kinect.SetMotorTilt().
CountsPerGravity
const double AForge.Video.Kinect.Kinect.CountsPerGravity = 819.0 static private
Referenced by AForge.Video.Kinect.Kinect.GetAccelerometerValues().
Gravity
const double AForge.Video.Kinect.Kinect.Gravity = 9.80665 static private
Referenced by AForge.Video.Kinect.Kinect.GetAccelerometerValues().
statusThreadSync
object AForge.Video.Kinect.Kinect.statusThreadSync = new object() static private
Referenced by AForge.Video.Kinect.Kinect.StartStatusThread(), and AForge.Video.Kinect.Kinect.StopStatusThread().
Property Documentation
DeviceID
int AForge.Video.Kinect.Kinect.DeviceID get
ID of the opened Kinect device.
DeviceCount
int AForge.Video.Kinect.Kinect.DeviceCount static get
Number of Kinect devices available in the system.
Referenced by KinectCapture.MainForm.Connect(), AForge.Video.Kinect.Kinect.GetDevice(), and KinectCapture.MainForm.MainForm_Load().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Video.Kinect/Kinect.cs