Doc: IGLib EXTENDED: AForge.DebuggerVisualizers.HistogramView Class Reference
AForge.DebuggerVisualizers.HistogramView Class Reference
Public Member Functions
HistogramView ()
void SetHistogram (Histogram histogram)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void histogramControl_PositionChanged (object sender, AForge.Controls.HistogramEventArgs e)
void histogramControl_SelectionChanged (object sender, AForge.Controls.HistogramEventArgs e)
void logCheck_CheckedChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Histogram histogram
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Panel mainPanel
AForge.Controls.Histogram histogramControl
System.Windows.Forms.TextBox textBox
System.Windows.Forms.TextBox statsBox
System.Windows.Forms.CheckBox logCheck
Static Private Attributes
const int HistogramHeight = 100
Constructor & Destructor Documentation
HistogramView()
AForge.DebuggerVisualizers.HistogramView.HistogramView () inline
References AForge.DebuggerVisualizers.HistogramView.InitializeComponent().
Member Function Documentation
SetHistogram()
void AForge.DebuggerVisualizers.HistogramView.SetHistogram (Histogram histogram) inline
References AForge.DebuggerVisualizers.HistogramView.histogram, AForge.DebuggerVisualizers.HistogramView.histogramControl, AForge.DebuggerVisualizers.HistogramView.HistogramHeight, AForge.DebuggerVisualizers.HistogramView.mainPanel, AForge.Math.Histogram.Max, AForge.Math.Histogram.Mean, AForge.Math.Histogram.Min, AForge.DebuggerVisualizers.HistogramView.statsBox, AForge.Math.Histogram.StdDev, and AForge.Math.Histogram.Values.
Referenced by AForge.DebuggerVisualizers.HistogramVisualizer.Show().
histogramControl_PositionChanged()
void AForge.DebuggerVisualizers.HistogramView.histogramControl_PositionChanged (object sender, AForge.Controls.HistogramEventArgs e) inline private
References AForge.DebuggerVisualizers.HistogramView.histogram, AForge.DebuggerVisualizers.HistogramView.textBox, AForge.Math.Histogram.TotalCount, and AForge.Math.Histogram.Values.
Referenced by AForge.DebuggerVisualizers.HistogramView.InitializeComponent().
histogramControl_SelectionChanged()
void AForge.DebuggerVisualizers.HistogramView.histogramControl_SelectionChanged (object sender, AForge.Controls.HistogramEventArgs e) inline private
References AForge.DebuggerVisualizers.HistogramView.histogram, AForge.DebuggerVisualizers.HistogramView.textBox, AForge.Math.Histogram.TotalCount, and AForge.Math.Histogram.Values.
Referenced by AForge.DebuggerVisualizers.HistogramView.InitializeComponent().
logCheck_CheckedChanged()
void AForge.DebuggerVisualizers.HistogramView.logCheck_CheckedChanged (object sender, EventArgs e) inline private
References AForge.DebuggerVisualizers.HistogramView.histogramControl, and AForge.DebuggerVisualizers.HistogramView.logCheck.
Referenced by AForge.DebuggerVisualizers.HistogramView.InitializeComponent().
Dispose()
override void AForge.DebuggerVisualizers.HistogramView.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References AForge.DebuggerVisualizers.HistogramView.components.
InitializeComponent()
void AForge.DebuggerVisualizers.HistogramView.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References AForge.DebuggerVisualizers.HistogramView.histogramControl, AForge.DebuggerVisualizers.HistogramView.histogramControl_PositionChanged(), AForge.DebuggerVisualizers.HistogramView.histogramControl_SelectionChanged(), AForge.DebuggerVisualizers.HistogramView.logCheck, AForge.DebuggerVisualizers.HistogramView.logCheck_CheckedChanged(), AForge.DebuggerVisualizers.HistogramView.mainPanel, AForge.DebuggerVisualizers.HistogramView.statsBox, and AForge.DebuggerVisualizers.HistogramView.textBox.
Referenced by AForge.DebuggerVisualizers.HistogramView.HistogramView().
Member Data Documentation
HistogramHeight
const int AForge.DebuggerVisualizers.HistogramView.HistogramHeight = 100 static private
Referenced by AForge.DebuggerVisualizers.HistogramView.SetHistogram().
histogram
Histogram AForge.DebuggerVisualizers.HistogramView.histogram private
Referenced by AForge.DebuggerVisualizers.HistogramView.histogramControl_PositionChanged(), AForge.DebuggerVisualizers.HistogramView.histogramControl_SelectionChanged(), and AForge.DebuggerVisualizers.HistogramView.SetHistogram().
components
System.ComponentModel.IContainer AForge.DebuggerVisualizers.HistogramView.components = null private
Required designer variable.
Referenced by AForge.DebuggerVisualizers.HistogramView.Dispose().
mainPanel
System.Windows.Forms.Panel AForge.DebuggerVisualizers.HistogramView.mainPanel private
Referenced by AForge.DebuggerVisualizers.HistogramView.InitializeComponent(), and AForge.DebuggerVisualizers.HistogramView.SetHistogram().
histogramControl
AForge.Controls.Histogram AForge.DebuggerVisualizers.HistogramView.histogramControl private
Referenced by AForge.DebuggerVisualizers.HistogramView.InitializeComponent(), AForge.DebuggerVisualizers.HistogramView.logCheck_CheckedChanged(), and AForge.DebuggerVisualizers.HistogramView.SetHistogram().
textBox
System.Windows.Forms.TextBox AForge.DebuggerVisualizers.HistogramView.textBox private
Referenced by AForge.DebuggerVisualizers.HistogramView.histogramControl_PositionChanged(), AForge.DebuggerVisualizers.HistogramView.histogramControl_SelectionChanged(), and AForge.DebuggerVisualizers.HistogramView.InitializeComponent().
statsBox
System.Windows.Forms.TextBox AForge.DebuggerVisualizers.HistogramView.statsBox private
Referenced by AForge.DebuggerVisualizers.HistogramView.InitializeComponent(), and AForge.DebuggerVisualizers.HistogramView.SetHistogram().
logCheck
System.Windows.Forms.CheckBox AForge.DebuggerVisualizers.HistogramView.logCheck private
Referenced by AForge.DebuggerVisualizers.HistogramView.InitializeComponent(), and AForge.DebuggerVisualizers.HistogramView.logCheck_CheckedChanged().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Tools/DebuggerVisualizers/HistogramView.cs
shelldev/lib_ann/aforge.net/Tools/DebuggerVisualizers/HistogramView.Designer.cs