Doc: IGLib EXTENDED: TexturesDemo.MainForm Class Reference
TexturesDemo.MainForm Class Reference
Public Member Functions
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void texturesCombo_SelectedIndexChanged (object sender, EventArgs e)
void ShowTexture ()
void regenerateButton_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
ITextureGenerator textureGenerator = null
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Label label1
System.Windows.Forms.ComboBox texturesCombo
System.Windows.Forms.PictureBox pictureBox
System.Windows.Forms.Button regenerateButton
Constructor & Destructor Documentation
MainForm()
TexturesDemo.MainForm.MainForm () inline
References TexturesDemo.MainForm.InitializeComponent(), and TexturesDemo.MainForm.texturesCombo.
Member Function Documentation
texturesCombo_SelectedIndexChanged()
void TexturesDemo.MainForm.texturesCombo_SelectedIndexChanged (object sender, EventArgs e) inline private
References TexturesDemo.MainForm.ShowTexture(), TexturesDemo.MainForm.textureGenerator, and TexturesDemo.MainForm.texturesCombo.
Referenced by TexturesDemo.MainForm.InitializeComponent().
ShowTexture()
void TexturesDemo.MainForm.ShowTexture () inline private
References AForge.Imaging.Textures.ITextureGenerator.Generate(), TexturesDemo.MainForm.pictureBox, TexturesDemo.MainForm.textureGenerator, and AForge.Imaging.Textures.TextureTools.ToBitmap().
Referenced by TexturesDemo.MainForm.regenerateButton_Click(), and TexturesDemo.MainForm.texturesCombo_SelectedIndexChanged().
regenerateButton_Click()
void TexturesDemo.MainForm.regenerateButton_Click (object sender, EventArgs e) inline private
References AForge.Imaging.Textures.ITextureGenerator.Reset(), TexturesDemo.MainForm.ShowTexture(), and TexturesDemo.MainForm.textureGenerator.
Referenced by TexturesDemo.MainForm.InitializeComponent().
Dispose()
override void TexturesDemo.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References TexturesDemo.MainForm.components.
InitializeComponent()
void TexturesDemo.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References TexturesDemo.MainForm.label1, TexturesDemo.MainForm.pictureBox, TexturesDemo.MainForm.regenerateButton, TexturesDemo.MainForm.regenerateButton_Click(), TexturesDemo.MainForm.texturesCombo, and TexturesDemo.MainForm.texturesCombo_SelectedIndexChanged().
Referenced by TexturesDemo.MainForm.MainForm().
Member Data Documentation
textureGenerator
ITextureGenerator TexturesDemo.MainForm.textureGenerator = null private
Referenced by TexturesDemo.MainForm.regenerateButton_Click(), TexturesDemo.MainForm.ShowTexture(), and TexturesDemo.MainForm.texturesCombo_SelectedIndexChanged().
components
System.ComponentModel.IContainer TexturesDemo.MainForm.components = null private
Required designer variable.
Referenced by TexturesDemo.MainForm.Dispose().
label1
System.Windows.Forms.Label TexturesDemo.MainForm.label1 private
Referenced by TexturesDemo.MainForm.InitializeComponent().
texturesCombo
System.Windows.Forms.ComboBox TexturesDemo.MainForm.texturesCombo private
Referenced by TexturesDemo.MainForm.InitializeComponent(), TexturesDemo.MainForm.MainForm(), and TexturesDemo.MainForm.texturesCombo_SelectedIndexChanged().
pictureBox
System.Windows.Forms.PictureBox TexturesDemo.MainForm.pictureBox private
Referenced by TexturesDemo.MainForm.InitializeComponent(), and TexturesDemo.MainForm.ShowTexture().
regenerateButton
System.Windows.Forms.Button TexturesDemo.MainForm.regenerateButton private
Referenced by TexturesDemo.MainForm.InitializeComponent().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Imaging/TexturesDemo/MainForm.cs
shelldev/lib_ann/aforge.net/Samples/Imaging/TexturesDemo/MainForm.Designer.cs