Doc: IGLib EXTENDED: IG.Forms.HashAboutControl Class Reference
IG.Forms.HashAboutControl Class Reference
Public Member Functions
HashAboutControl ()
virtual string GetHelpLocationHtmlInExecutableDirectory ()
virtual string GetHelpLocationPdfInExecutableDirectory ()
void HelpBrowse ()
void HelpPdf ()
void WebPageBrowse ()
void HelpShow ()
void WebPageShow ()
HashAboutControl ()
virtual string GetHelpLocationHtmlInExecutableDirectory ()
virtual string GetHelpLocationPdfInExecutableDirectory ()
void HelpBrowse ()
void HelpPdf ()
void WebPageBrowse ()
void HelpShow ()
void WebPageShow ()
HashAboutControl ()
virtual string GetHelpLocationHtmlInExecutableDirectory ()
virtual string GetHelpLocationPdfInExecutableDirectory ()
void HelpBrowse ()
void HelpPdf ()
void WebPageBrowse ()
void HelpShow ()
void WebPageShow ()
Public Attributes
string DefaultApplicationName = "HashForm"
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
string _homePageShort
string _helpLocation
string _helpLocationPdf
BrowserSimpleForm _browser
string _applicationName
int _fadingMessageShowTimeMs = 1000
Properties
virtual string HomePageShort [get, protected set]
Short version of the application's home page.
virtual string HomePage [get]
virtual string HelpLocation [get]
Location of the help file that can be displayed in a web browser.
virtual string HelpLocationPdf [get]
Location of the help file that can be displayed in a web browser.
BrowserSimpleForm Browser [get]
string ApplicationName [get]
Private Member Functions
void lblAboutWeb_Click (object sender, EventArgs e)
void btnHelpPdf_Click (object sender, EventArgs e)
void btnHelpHtml_Click (object sender, EventArgs e)
void btnWeb_Click (object sender, EventArgs e)
void pnlAbout_Paint (object sender, PaintEventArgs e)
Triggered on each repaint of the panel. can be attemted to make background transparent.
void lblBrowseHelp_Click (object sender, EventArgs e)
void lblHelpPdf_Click (object sender, EventArgs e)
void lblBrowseHome_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void lblAboutWeb_Click (object sender, EventArgs e)
void btnHelpPdf_Click (object sender, EventArgs e)
void btnHelpHtml_Click (object sender, EventArgs e)
void btnWeb_Click (object sender, EventArgs e)
void pnlAbout_Paint (object sender, PaintEventArgs e)
Triggered on each repaint of the panel. can be attemted to make background transparent.
void lblBrowseHelp_Click (object sender, EventArgs e)
void lblHelpPdf_Click (object sender, EventArgs e)
void lblBrowseHome_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void lblAboutWeb_Click (object sender, EventArgs e)
void btnHelpPdf_Click (object sender, EventArgs e)
void btnHelpHtml_Click (object sender, EventArgs e)
void btnWeb_Click (object sender, EventArgs e)
void pnlAbout_Paint (object sender, PaintEventArgs e)
Triggered on each repaint of the panel. can be attemted to make background transparent.
void lblBrowseHelp_Click (object sender, EventArgs e)
void lblHelpPdf_Click (object sender, EventArgs e)
void lblBrowseHome_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Label lblTitle
System.Windows.Forms.Button btnHelpHtml
System.Windows.Forms.Panel pnlAbout
System.Windows.Forms.Label lblAboutAuthors
System.Windows.Forms.Label lblAboutAuthorsIntro
System.Windows.Forms.Label lblAboutTitle
System.Windows.Forms.Label lblAboutWeb
System.Windows.Forms.Label lblAboutContact
System.Windows.Forms.Label lblAbourContactIntro
System.Windows.Forms.PictureBox pbIGLib
System.Windows.Forms.Label lblPoweredIGLib
System.Windows.Forms.Panel pnlIGLib
System.Windows.Forms.Button btnWeb
System.Windows.Forms.Label lblHomeBrowse
System.Windows.Forms.Label lblHelpBrowse
System.Windows.Forms.Button btnHelpPdf
Static Private Attributes
const string DefaultHomePageShort = "www2.arnes.si/~ljc3m2/igor/software/IGLibShellApp/HashForm.html#hashform"
const string DefaultDocumentLocation = "http://www2.arnes.si/~ljc3m2/igor/software/IGLibShellApp/versions/1.6.1/doc/"
const string DefaultHelpFileNameWithoutExtension = "HashForm_help"
const string DefaultHelpFilenamePdf = DefaultHelpFileNameWithoutExtension + ".pdf"
const string DefaultHelpFilenameHtml = DefaultHelpFileNameWithoutExtension + ".html"
const string DefaultHelpLocation = DefaultDocumentLocation + DefaultHelpFilenameHtml
const string DefaultHelpLocationPdf = DefaultDocumentLocation + DefaultHelpFilenamePdf
Constructor & Destructor Documentation
HashAboutControl() [1/3]
IG.Forms.HashAboutControl.HashAboutControl () inline
References IG.Forms.HashAboutControl.DefaultHomePageShort, IG.Forms.HashAboutControl.InitializeComponent(), and IG.Forms.HashAboutControl.lblAboutWeb.
HashAboutControl() [2/3]
IG.Forms.HashAboutControl.HashAboutControl () inline
References IG.Forms.HashAboutControl.DefaultHomePageShort, IG.Forms.HashAboutControl.InitializeComponent(), and IG.Forms.HashAboutControl.lblAboutWeb.
HashAboutControl() [3/3]
IG.Forms.HashAboutControl.HashAboutControl () inline
References IG.Forms.HashAboutControl.DefaultHomePageShort, IG.Forms.HashAboutControl.InitializeComponent(), and IG.Forms.HashAboutControl.lblAboutWeb.
Member Function Documentation
GetHelpLocationHtmlInExecutableDirectory() [1/3]
virtual string IG.Forms.HashAboutControl.GetHelpLocationHtmlInExecutableDirectory () inline virtual
References IG.Forms.HashAboutControl.DefaultHelpFilenameHtml.
GetHelpLocationPdfInExecutableDirectory() [1/3]
virtual string IG.Forms.HashAboutControl.GetHelpLocationPdfInExecutableDirectory () inline virtual
References IG.Forms.HashAboutControl.DefaultHelpFilenamePdf.
HelpBrowse() [1/3]
void IG.Forms.HashAboutControl.HelpBrowse () inline
References IG.Forms.HashAboutControl._fadingMessageShowTimeMs, IG.Forms.HashAboutControl.HelpLocation, IG.Forms.FadingMessage.LaunchedAtMouseCursor, and IG.Forms.FadingMessage.LaunchedInParallelThread.
Referenced by IG.Forms.HashAboutControl.lblBrowseHelp_Click().
HelpPdf() [1/3]
void IG.Forms.HashAboutControl.HelpPdf () inline
References IG.Forms.HashAboutControl._fadingMessageShowTimeMs, IG.Forms.HashAboutControl.HelpLocationPdf, IG.Forms.FadingMessage.LaunchedAtMouseCursor, and IG.Forms.FadingMessage.LaunchedInParallelThread.
Referenced by IG.Forms.HashControl.btnHelp_Click(), IG.Forms.HashAboutControl.btnHelpPdf_Click(), IG.Forms.HashControl.btnInfo_Click(), and IG.Forms.HashAboutControl.lblHelpPdf_Click().
WebPageBrowse() [1/3]
void IG.Forms.HashAboutControl.WebPageBrowse () inline
References IG.Forms.HashAboutControl._fadingMessageShowTimeMs, IG.Forms.HashAboutControl.HomePage, IG.Forms.FadingMessage.LaunchedAtMouseCursor, and IG.Forms.FadingMessage.LaunchedInParallelThread.
Referenced by IG.Forms.HashAboutControl.lblBrowseHome_Click().
HelpShow() [1/3]
void IG.Forms.HashAboutControl.HelpShow () inline
References IG.Forms.HashAboutControl.Browser, IG.Forms.HashAboutControl.HelpLocation, and IG.Forms.BrowserSimpleForm.OpenLocation().
Referenced by IG.Forms.HashAboutControl.btnHelpHtml_Click().
WebPageShow() [1/3]
void IG.Forms.HashAboutControl.WebPageShow () inline
References IG.Forms.HashAboutControl.Browser, IG.Forms.HashAboutControl.HomePage, and IG.Forms.BrowserSimpleForm.OpenLocation().
Referenced by IG.Forms.HashAboutControl.btnWeb_Click().
lblAboutWeb_Click() [1/3]
void IG.Forms.HashAboutControl.lblAboutWeb_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.lblAboutWeb.
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
btnHelpPdf_Click() [1/3]
void IG.Forms.HashAboutControl.btnHelpPdf_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.HelpPdf().
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
btnHelpHtml_Click() [1/3]
void IG.Forms.HashAboutControl.btnHelpHtml_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.HelpShow().
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
btnWeb_Click() [1/3]
void IG.Forms.HashAboutControl.btnWeb_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.WebPageShow().
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
pnlAbout_Paint() [1/3]
void IG.Forms.HashAboutControl.pnlAbout_Paint (object sender, PaintEventArgs e) inline private
Triggered on each repaint of the panel. can be attemted to make background transparent.
Does not work. Color.FromArgb(25, Color.White); gets the closest to doing something.
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
lblBrowseHelp_Click() [1/3]
void IG.Forms.HashAboutControl.lblBrowseHelp_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.HelpBrowse().
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
lblHelpPdf_Click() [1/3]
void IG.Forms.HashAboutControl.lblHelpPdf_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.HelpPdf().
lblBrowseHome_Click() [1/3]
void IG.Forms.HashAboutControl.lblBrowseHome_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.WebPageBrowse().
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
Dispose() [1/3]
override void IG.Forms.HashAboutControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.HashAboutControl.components.
InitializeComponent() [1/3]
void IG.Forms.HashAboutControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.HashAboutControl.btnHelpHtml, IG.Forms.HashAboutControl.btnHelpHtml_Click(), IG.Forms.HashAboutControl.btnHelpPdf, IG.Forms.HashAboutControl.btnHelpPdf_Click(), IG.Forms.HashAboutControl.btnWeb, IG.Forms.HashAboutControl.btnWeb_Click(), IG.Forms.HashAboutControl.lblAbourContactIntro, IG.Forms.HashAboutControl.lblAboutAuthors, IG.Forms.HashAboutControl.lblAboutAuthorsIntro, IG.Forms.HashAboutControl.lblAboutContact, IG.Forms.HashAboutControl.lblAboutTitle, IG.Forms.HashAboutControl.lblAboutWeb, IG.Forms.HashAboutControl.lblAboutWeb_Click(), IG.Forms.HashAboutControl.lblBrowseHelp_Click(), IG.Forms.HashAboutControl.lblBrowseHome_Click(), IG.Forms.HashAboutControl.lblHelpBrowse, IG.Forms.HashAboutControl.lblHomeBrowse, IG.Forms.HashAboutControl.lblPoweredIGLib, IG.Forms.HashAboutControl.lblTitle, IG.Forms.HashAboutControl.pbIGLib, IG.Forms.HashAboutControl.pnlAbout, IG.Forms.HashAboutControl.pnlAbout_Paint(), and IG.Forms.HashAboutControl.pnlIGLib.
Referenced by IG.Forms.HashAboutControl.HashAboutControl().
GetHelpLocationHtmlInExecutableDirectory() [2/3]
virtual string IG.Forms.HashAboutControl.GetHelpLocationHtmlInExecutableDirectory () inline virtual
References IG.Forms.HashAboutControl.DefaultHelpFilenameHtml.
GetHelpLocationPdfInExecutableDirectory() [2/3]
virtual string IG.Forms.HashAboutControl.GetHelpLocationPdfInExecutableDirectory () inline virtual
References IG.Forms.HashAboutControl.DefaultHelpFilenamePdf.
HelpBrowse() [2/3]
void IG.Forms.HashAboutControl.HelpBrowse () inline
References IG.Forms.HashAboutControl._fadingMessageShowTimeMs, IG.Forms.HashAboutControl.HelpLocation, IG.Forms.FadingMessage.LaunchedAtMouseCursor, and IG.Forms.FadingMessage.LaunchedInParallelThread.
HelpPdf() [2/3]
void IG.Forms.HashAboutControl.HelpPdf () inline
References IG.Forms.HashAboutControl._fadingMessageShowTimeMs, IG.Forms.HashAboutControl.HelpLocationPdf, IG.Forms.FadingMessage.LaunchedAtMouseCursor, and IG.Forms.FadingMessage.LaunchedInParallelThread.
WebPageBrowse() [2/3]
void IG.Forms.HashAboutControl.WebPageBrowse () inline
References IG.Forms.HashAboutControl._fadingMessageShowTimeMs, IG.Forms.HashAboutControl.HomePage, IG.Forms.FadingMessage.LaunchedAtMouseCursor, and IG.Forms.FadingMessage.LaunchedInParallelThread.
HelpShow() [2/3]
void IG.Forms.HashAboutControl.HelpShow () inline
References IG.Forms.HashAboutControl.Browser, IG.Forms.HashAboutControl.HelpLocation, and IG.Forms.BrowserSimpleForm.OpenLocation().
WebPageShow() [2/3]
void IG.Forms.HashAboutControl.WebPageShow () inline
References IG.Forms.HashAboutControl.Browser, IG.Forms.HashAboutControl.HomePage, and IG.Forms.BrowserSimpleForm.OpenLocation().
lblAboutWeb_Click() [2/3]
void IG.Forms.HashAboutControl.lblAboutWeb_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.lblAboutWeb.
btnHelpPdf_Click() [2/3]
void IG.Forms.HashAboutControl.btnHelpPdf_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.HelpPdf().
btnHelpHtml_Click() [2/3]
void IG.Forms.HashAboutControl.btnHelpHtml_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.HelpShow().
btnWeb_Click() [2/3]
void IG.Forms.HashAboutControl.btnWeb_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.WebPageShow().
pnlAbout_Paint() [2/3]
void IG.Forms.HashAboutControl.pnlAbout_Paint (object sender, PaintEventArgs e) inline private
Triggered on each repaint of the panel. can be attemted to make background transparent.
Does not work. Color.FromArgb(25, Color.White); gets the closest to doing something.
lblBrowseHelp_Click() [2/3]
void IG.Forms.HashAboutControl.lblBrowseHelp_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.HelpBrowse().
lblHelpPdf_Click() [2/3]
void IG.Forms.HashAboutControl.lblHelpPdf_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.HelpPdf().
lblBrowseHome_Click() [2/3]
void IG.Forms.HashAboutControl.lblBrowseHome_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.WebPageBrowse().
Dispose() [2/3]
override void IG.Forms.HashAboutControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.HashAboutControl.components.
InitializeComponent() [2/3]
void IG.Forms.HashAboutControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.HashAboutControl.btnHelpHtml, IG.Forms.HashAboutControl.btnHelpHtml_Click(), IG.Forms.HashAboutControl.btnHelpPdf, IG.Forms.HashAboutControl.btnHelpPdf_Click(), IG.Forms.HashAboutControl.btnWeb, IG.Forms.HashAboutControl.btnWeb_Click(), IG.Forms.HashAboutControl.lblAbourContactIntro, IG.Forms.HashAboutControl.lblAboutAuthors, IG.Forms.HashAboutControl.lblAboutAuthorsIntro, IG.Forms.HashAboutControl.lblAboutContact, IG.Forms.HashAboutControl.lblAboutTitle, IG.Forms.HashAboutControl.lblAboutWeb, IG.Forms.HashAboutControl.lblAboutWeb_Click(), IG.Forms.HashAboutControl.lblBrowseHelp_Click(), IG.Forms.HashAboutControl.lblBrowseHome_Click(), IG.Forms.HashAboutControl.lblHelpBrowse, IG.Forms.HashAboutControl.lblHomeBrowse, IG.Forms.HashAboutControl.lblPoweredIGLib, IG.Forms.HashAboutControl.lblTitle, IG.Forms.HashAboutControl.pbIGLib, IG.Forms.HashAboutControl.pnlAbout, IG.Forms.HashAboutControl.pnlAbout_Paint(), and IG.Forms.HashAboutControl.pnlIGLib.
GetHelpLocationHtmlInExecutableDirectory() [3/3]
virtual string IG.Forms.HashAboutControl.GetHelpLocationHtmlInExecutableDirectory () inline virtual
References IG.Forms.HashAboutControl.DefaultHelpFilenameHtml.
GetHelpLocationPdfInExecutableDirectory() [3/3]
virtual string IG.Forms.HashAboutControl.GetHelpLocationPdfInExecutableDirectory () inline virtual
References IG.Forms.HashAboutControl.DefaultHelpFilenamePdf.
HelpBrowse() [3/3]
void IG.Forms.HashAboutControl.HelpBrowse () inline
References IG.Forms.HashAboutControl._fadingMessageShowTimeMs, IG.Forms.HashAboutControl.HelpLocation, IG.Forms.FadingMessage.LaunchedAtMouseCursor, and IG.Forms.FadingMessage.LaunchedInParallelThread.
HelpPdf() [3/3]
void IG.Forms.HashAboutControl.HelpPdf () inline
References IG.Forms.HashAboutControl._fadingMessageShowTimeMs, IG.Forms.HashAboutControl.HelpLocationPdf, IG.Forms.FadingMessage.LaunchedAtMouseCursor, and IG.Forms.FadingMessage.LaunchedInParallelThread.
WebPageBrowse() [3/3]
void IG.Forms.HashAboutControl.WebPageBrowse () inline
References IG.Forms.HashAboutControl._fadingMessageShowTimeMs, IG.Forms.HashAboutControl.HomePage, IG.Forms.FadingMessage.LaunchedAtMouseCursor, and IG.Forms.FadingMessage.LaunchedInParallelThread.
HelpShow() [3/3]
void IG.Forms.HashAboutControl.HelpShow () inline
References IG.Forms.HashAboutControl.Browser, IG.Forms.HashAboutControl.HelpLocation, and IG.Forms.BrowserSimpleForm.OpenLocation().
WebPageShow() [3/3]
void IG.Forms.HashAboutControl.WebPageShow () inline
References IG.Forms.HashAboutControl.Browser, IG.Forms.HashAboutControl.HomePage, and IG.Forms.BrowserSimpleForm.OpenLocation().
lblAboutWeb_Click() [3/3]
void IG.Forms.HashAboutControl.lblAboutWeb_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.lblAboutWeb.
btnHelpPdf_Click() [3/3]
void IG.Forms.HashAboutControl.btnHelpPdf_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.HelpPdf().
btnHelpHtml_Click() [3/3]
void IG.Forms.HashAboutControl.btnHelpHtml_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.HelpShow().
btnWeb_Click() [3/3]
void IG.Forms.HashAboutControl.btnWeb_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.WebPageShow().
pnlAbout_Paint() [3/3]
void IG.Forms.HashAboutControl.pnlAbout_Paint (object sender, PaintEventArgs e) inline private
Triggered on each repaint of the panel. can be attemted to make background transparent.
Does not work. Color.FromArgb(25, Color.White); gets the closest to doing something.
lblBrowseHelp_Click() [3/3]
void IG.Forms.HashAboutControl.lblBrowseHelp_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.HelpBrowse().
lblHelpPdf_Click() [3/3]
void IG.Forms.HashAboutControl.lblHelpPdf_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.HelpPdf().
lblBrowseHome_Click() [3/3]
void IG.Forms.HashAboutControl.lblBrowseHome_Click (object sender, EventArgs e) inline private
References IG.Forms.HashAboutControl.WebPageBrowse().
Dispose() [3/3]
override void IG.Forms.HashAboutControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.HashAboutControl.components.
InitializeComponent() [3/3]
void IG.Forms.HashAboutControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.HashAboutControl.btnHelpHtml, IG.Forms.HashAboutControl.btnHelpHtml_Click(), IG.Forms.HashAboutControl.btnHelpPdf, IG.Forms.HashAboutControl.btnHelpPdf_Click(), IG.Forms.HashAboutControl.btnWeb, IG.Forms.HashAboutControl.btnWeb_Click(), IG.Forms.HashAboutControl.lblAbourContactIntro, IG.Forms.HashAboutControl.lblAboutAuthors, IG.Forms.HashAboutControl.lblAboutAuthorsIntro, IG.Forms.HashAboutControl.lblAboutContact, IG.Forms.HashAboutControl.lblAboutTitle, IG.Forms.HashAboutControl.lblAboutWeb, IG.Forms.HashAboutControl.lblAboutWeb_Click(), IG.Forms.HashAboutControl.lblBrowseHelp_Click(), IG.Forms.HashAboutControl.lblBrowseHome_Click(), IG.Forms.HashAboutControl.lblHelpBrowse, IG.Forms.HashAboutControl.lblHomeBrowse, IG.Forms.HashAboutControl.lblPoweredIGLib, IG.Forms.HashAboutControl.lblTitle, IG.Forms.HashAboutControl.pbIGLib, IG.Forms.HashAboutControl.pnlAbout, IG.Forms.HashAboutControl.pnlAbout_Paint(), and IG.Forms.HashAboutControl.pnlIGLib.
Member Data Documentation
DefaultHomePageShort
const string IG.Forms.HashAboutControl.DefaultHomePageShort = "www2.arnes.si/~ljc3m2/igor/software/IGLibShellApp/HashForm.html#hashform" static private
Referenced by IG.Forms.HashAboutControl.HashAboutControl().
DefaultDocumentLocation
const string IG.Forms.HashAboutControl.DefaultDocumentLocation = "http://www2.arnes.si/~ljc3m2/igor/software/IGLibShellApp/versions/1.6.1/doc/" static private
DefaultHelpFileNameWithoutExtension
const string IG.Forms.HashAboutControl.DefaultHelpFileNameWithoutExtension = "HashForm_help" static private
DefaultHelpFilenamePdf
const string IG.Forms.HashAboutControl.DefaultHelpFilenamePdf = DefaultHelpFileNameWithoutExtension + ".pdf" static private
Referenced by IG.Forms.HashAboutControl.GetHelpLocationPdfInExecutableDirectory().
DefaultHelpFilenameHtml
const string IG.Forms.HashAboutControl.DefaultHelpFilenameHtml = DefaultHelpFileNameWithoutExtension + ".html" static private
Referenced by IG.Forms.HashAboutControl.GetHelpLocationHtmlInExecutableDirectory().
DefaultHelpLocation
const string IG.Forms.HashAboutControl.DefaultHelpLocation = DefaultDocumentLocation + DefaultHelpFilenameHtml static private
DefaultHelpLocationPdf
const string IG.Forms.HashAboutControl.DefaultHelpLocationPdf = DefaultDocumentLocation + DefaultHelpFilenamePdf static private
_homePageShort
string IG.Forms.HashAboutControl._homePageShort protected
_helpLocation
string IG.Forms.HashAboutControl._helpLocation protected
_helpLocationPdf
string IG.Forms.HashAboutControl._helpLocationPdf protected
_browser
BrowserSimpleForm IG.Forms.HashAboutControl._browser protected
DefaultApplicationName
string IG.Forms.HashAboutControl.DefaultApplicationName = "HashForm"
_applicationName
string IG.Forms.HashAboutControl._applicationName protected
_fadingMessageShowTimeMs
int IG.Forms.HashAboutControl._fadingMessageShowTimeMs = 1000 protected
Referenced by IG.Forms.HashAboutControl.HelpBrowse(), IG.Forms.HashAboutControl.HelpPdf(), and IG.Forms.HashAboutControl.WebPageBrowse().
components
System ComponentModel IContainer IG.Forms.HashAboutControl.components = null private
Required designer variable.
Referenced by IG.Forms.HashAboutControl.Dispose().
lblTitle
System Windows Forms Label IG.Forms.HashAboutControl.lblTitle private
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
btnHelpHtml
System Windows Forms Button IG.Forms.HashAboutControl.btnHelpHtml private
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
pnlAbout
System Windows Forms Panel IG.Forms.HashAboutControl.pnlAbout private
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
lblAboutAuthors
System Windows Forms Label IG.Forms.HashAboutControl.lblAboutAuthors private
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
lblAboutAuthorsIntro
System Windows Forms Label IG.Forms.HashAboutControl.lblAboutAuthorsIntro private
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
lblAboutTitle
System Windows Forms Label IG.Forms.HashAboutControl.lblAboutTitle private
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
lblAboutWeb
System Windows Forms Label IG.Forms.HashAboutControl.lblAboutWeb private
Referenced by IG.Forms.HashAboutControl.HashAboutControl(), IG.Forms.HashAboutControl.InitializeComponent(), and IG.Forms.HashAboutControl.lblAboutWeb_Click().
lblAboutContact
System Windows Forms Label IG.Forms.HashAboutControl.lblAboutContact private
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
lblAbourContactIntro
System Windows Forms Label IG.Forms.HashAboutControl.lblAbourContactIntro private
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
pbIGLib
System Windows Forms PictureBox IG.Forms.HashAboutControl.pbIGLib private
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
lblPoweredIGLib
System Windows Forms Label IG.Forms.HashAboutControl.lblPoweredIGLib private
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
pnlIGLib
System Windows Forms Panel IG.Forms.HashAboutControl.pnlIGLib private
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
btnWeb
System Windows Forms Button IG.Forms.HashAboutControl.btnWeb private
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
lblHomeBrowse
System Windows Forms Label IG.Forms.HashAboutControl.lblHomeBrowse private
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
lblHelpBrowse
System Windows Forms Label IG.Forms.HashAboutControl.lblHelpBrowse private
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
btnHelpPdf
System Windows Forms Button IG.Forms.HashAboutControl.btnHelpPdf private
Referenced by IG.Forms.HashAboutControl.InitializeComponent().
Property Documentation
HomePageShort
string IG.Forms.HashAboutControl.HomePageShort get protected set
Short version of the application's home page.
HomePage
string IG.Forms.HashAboutControl.HomePage get
Referenced by IG.Forms.HashAboutControl.WebPageBrowse(), and IG.Forms.HashAboutControl.WebPageShow().
HelpLocation
string IG.Forms.HashAboutControl.HelpLocation get
Location of the help file that can be displayed in a web browser.
Referenced by IG.Forms.HashAboutControl.HelpBrowse(), and IG.Forms.HashAboutControl.HelpShow().
HelpLocationPdf
string IG.Forms.HashAboutControl.HelpLocationPdf get
Location of the help file that can be displayed in a web browser.
Referenced by IG.Forms.HashAboutControl.HelpPdf().
Browser
BrowserSimpleForm IG.Forms.HashAboutControl.Browser get protected
Referenced by IG.Forms.HashAboutControl.HelpShow(), and IG.Forms.HashAboutControl.WebPageShow().
ApplicationName
string IG.Forms.HashAboutControl.ApplicationName get
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/Cryptography/HashAboutControl.cs
iglib/igforms/Utilities/Cryptography/HashAboutControl.Designer.cs