Doc: IGLib EXTENDED: NUnit.Framework.ValueSourceAttribute Class Reference
NUnit.Framework.ValueSourceAttribute Class Reference
ValueSourceAttribute indicates the source to be used to provide data for one parameter of a test method.
Public Member Functions
ValueSourceAttribute (string sourceName)
Construct with the name of the factory - for use with languages that don't support params arrays.
ValueSourceAttribute (Type sourceType, string sourceName)
Construct with a Type and name - for use with languages that don't support params arrays.
IEnumerable GetData (IParameterInfo parameter)
Gets an enumeration of data items for use as arguments for a test method parameter.
Public Member Functions inherited from NUnit.Framework.DataAttribute
DataAttribute ()
Default constructor
Public Member Functions inherited from NUnit.Framework.NUnitAttribute
NUnitAttribute ()
Default constructor
Properties
string SourceName [get, private set]
The name of a the method, property or fiend to be used as a source
Type SourceType [get, private set]
A Type to be used as a source
Private Member Functions
IEnumerable GetDataSource (IParameterInfo parameter)
Static Private Member Functions
static void ThrowInvalidDataSourceException ()
Detailed Description
ValueSourceAttribute indicates the source to be used to provide data for one parameter of a test method.
Constructor & Destructor Documentation
ValueSourceAttribute() [1/2]
NUnit.Framework.ValueSourceAttribute.ValueSourceAttribute (string sourceName) inline
Construct with the name of the factory - for use with languages that don't support params arrays.
Parameters
sourceName The name of a static method, property or field that will provide data.
References NUnit.Framework.ValueSourceAttribute.SourceName.
ValueSourceAttribute() [2/2]
NUnit.Framework.ValueSourceAttribute.ValueSourceAttribute (Type sourceType, string sourceName) inline
Construct with a Type and name - for use with languages that don't support params arrays.
Parameters
sourceType The Type that will provide data
sourceName The name of a static method, property or field that will provide data.
References NUnit.Framework.ValueSourceAttribute.SourceName, and NUnit.Framework.ValueSourceAttribute.SourceType.
Member Function Documentation
GetData()
IEnumerable NUnit.Framework.ValueSourceAttribute.GetData (IParameterInfo parameter) inline
Gets an enumeration of data items for use as arguments for a test method parameter.
Parameters
parameter The parameter for which data is needed
Returns
An enumeration containing individual data items
Implements NUnit.Framework.Interfaces.IParameterDataSource.
References NUnit.Framework.ValueSourceAttribute.GetDataSource().
GetDataSource()
IEnumerable NUnit.Framework.ValueSourceAttribute.GetDataSource (IParameterInfo parameter) inline private
References NUnit.Framework.Internal.Reflect.Construct(), NUnit.Framework.Interfaces.IParameterInfo.Method, NUnit.Framework.ValueSourceAttribute.SourceName, NUnit.Framework.ValueSourceAttribute.SourceType, NUnit.Framework.ValueSourceAttribute.ThrowInvalidDataSourceException(), NUnit.Framework.Interfaces.ITypeInfo.Type, and NUnit.Framework.Interfaces.IMethodInfo.TypeInfo.
Referenced by NUnit.Framework.ValueSourceAttribute.GetData().
ThrowInvalidDataSourceException()
static void NUnit.Framework.ValueSourceAttribute.ThrowInvalidDataSourceException () inline static private
Referenced by NUnit.Framework.ValueSourceAttribute.GetDataSource().
Property Documentation
SourceName
string NUnit.Framework.ValueSourceAttribute.SourceName get private set
The name of a the method, property or fiend to be used as a source
Referenced by NUnit.Framework.ValueSourceAttribute.GetDataSource(), and NUnit.Framework.ValueSourceAttribute.ValueSourceAttribute().
SourceType
Type NUnit.Framework.ValueSourceAttribute.SourceType get private set
A Type to be used as a source
Referenced by NUnit.Framework.ValueSourceAttribute.GetDataSource(), and NUnit.Framework.ValueSourceAttribute.ValueSourceAttribute().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Attributes/ValueSourceAttribute.cs