Doc: IGLib EXTENDED: FuzzySetSample.Sample Class Reference
FuzzySetSample.Sample Class Reference
Public Member Functions
Sample ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void runFuzzySetTestButton_Click (object sender, EventArgs e)
void runLingVarTestButton_Click (object sender, EventArgs e)
void ClearDataSeries ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Button runFuzzySetTestButton
AForge.Controls.Chart chart
System.Windows.Forms.Label label1
System.Windows.Forms.Label label2
System.Windows.Forms.Label label3
System.Windows.Forms.Label label4
System.Windows.Forms.Button runLingVarTestButton
Constructor & Destructor Documentation
Sample()
FuzzySetSample.Sample.Sample () inline
References AForge.Controls.Chart.AddDataSeries(), FuzzySetSample.Sample.chart, FuzzySetSample.Sample.InitializeComponent(), and AForge.Controls.Chart.RangeX.
Member Function Documentation
runFuzzySetTestButton_Click()
void FuzzySetSample.Sample.runFuzzySetTestButton_Click (object sender, EventArgs e) inline private
References FuzzySetSample.Sample.chart, FuzzySetSample.Sample.ClearDataSeries(), AForge.Fuzzy.FuzzySet.GetMembership(), and AForge.Controls.Chart.UpdateDataSeries().
Referenced by FuzzySetSample.Sample.InitializeComponent().
runLingVarTestButton_Click()
void FuzzySetSample.Sample.runLingVarTestButton_Click (object sender, EventArgs e) inline private
References AForge.Fuzzy.LinguisticVariable.AddLabel(), FuzzySetSample.Sample.chart, FuzzySetSample.Sample.ClearDataSeries(), AForge.Fuzzy.LinguisticVariable.GetLabelMembership(), and AForge.Controls.Chart.UpdateDataSeries().
Referenced by FuzzySetSample.Sample.InitializeComponent().
ClearDataSeries()
void FuzzySetSample.Sample.ClearDataSeries () inline private
References FuzzySetSample.Sample.chart, and AForge.Controls.Chart.UpdateDataSeries().
Referenced by FuzzySetSample.Sample.runFuzzySetTestButton_Click(), and FuzzySetSample.Sample.runLingVarTestButton_Click().
Dispose()
override void FuzzySetSample.Sample.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References FuzzySetSample.Sample.components.
InitializeComponent()
void FuzzySetSample.Sample.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References FuzzySetSample.Sample.chart, FuzzySetSample.Sample.label1, FuzzySetSample.Sample.label2, FuzzySetSample.Sample.label3, FuzzySetSample.Sample.label4, FuzzySetSample.Sample.runFuzzySetTestButton, FuzzySetSample.Sample.runFuzzySetTestButton_Click(), FuzzySetSample.Sample.runLingVarTestButton, and FuzzySetSample.Sample.runLingVarTestButton_Click().
Referenced by FuzzySetSample.Sample.Sample().
Member Data Documentation
components
System.ComponentModel.IContainer FuzzySetSample.Sample.components = null private
Required designer variable.
Referenced by FuzzySetSample.Sample.Dispose().
runFuzzySetTestButton
System.Windows.Forms.Button FuzzySetSample.Sample.runFuzzySetTestButton private
Referenced by FuzzySetSample.Sample.InitializeComponent().
chart
AForge.Controls.Chart FuzzySetSample.Sample.chart private
Referenced by FuzzySetSample.Sample.ClearDataSeries(), FuzzySetSample.Sample.InitializeComponent(), FuzzySetSample.Sample.runFuzzySetTestButton_Click(), FuzzySetSample.Sample.runLingVarTestButton_Click(), and FuzzySetSample.Sample.Sample().
label1
System.Windows.Forms.Label FuzzySetSample.Sample.label1 private
Referenced by FuzzySetSample.Sample.InitializeComponent().
label2
System.Windows.Forms.Label FuzzySetSample.Sample.label2 private
Referenced by FuzzySetSample.Sample.InitializeComponent().
label3
System.Windows.Forms.Label FuzzySetSample.Sample.label3 private
Referenced by FuzzySetSample.Sample.InitializeComponent().
label4
System.Windows.Forms.Label FuzzySetSample.Sample.label4 private
Referenced by FuzzySetSample.Sample.InitializeComponent().
runLingVarTestButton
System.Windows.Forms.Button FuzzySetSample.Sample.runLingVarTestButton private
Referenced by FuzzySetSample.Sample.InitializeComponent().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Fuzzy/Fuzzy Set Sample/Sample.cs
shelldev/lib_ann/aforge.net/Samples/Fuzzy/Fuzzy Set Sample/Sample.Designer.cs