Doc: IGLib EXTENDED: CShell.Modules.Sink.ViewModels.PlotSinkViewModel Class Reference
CShell.Modules.Sink.ViewModels.PlotSinkViewModel Class Reference
Classes
class HistogramChartHelper
Helper class that creates a histogram chart. Histogram is a data distribution chart which shows how many values, from the data series, are inside each segment interval.
Public Member Functions
PlotSinkViewModel (Uri uri)
override void Dump (object o, string description)
override void Clear ()
void Plot (Series series)
void Plot (Chart newChart)
void Plot (IEnumerable ys, string seriesName=null, string chartType="Line")
void Plot (IEnumerable ys, IEnumerable xs, string seriesName=null, string chartType="Line")
void PlotFunction (Func< double, double > f, string seriesName=null, string chartType="Line", double from=-3.0, double to=3.0, int points=100)
void PlotHistogram (IEnumerable ys, string seriesName=null, string histogramName=null)
Public Member Functions inherited from CShell.Framework.Sink
virtual void Dump (object o)
Public Member Functions inherited from CShell.Framework.Document
virtual void Save ()
virtual void SaveAs (string newFile)
Properties
Chart?? Chart [get, set]
Properties inherited from CShell.Framework.Sink
virtual Uri IconSource [get]
bool IsVisible [get, set]
virtual PaneLocation PreferredLocation [get]
Properties inherited from CShell.Framework.Document
ICommand?? CloseCommand [get]
virtual Uri Uri [get, set]
virtual bool IsDirty [get, set]
Properties inherited from CShell.Framework.IDocument
ICommand CloseCommand [get]
Uri Uri [get]
bool IsDirty [get]
Properties inherited from CShell.Framework.ISink
PaneLocation PreferredLocation [get]
bool IsVisible [get, set]
Private Member Functions
Chart InitChart ()
Static Private Member Functions
static bool CheckDataType (object values)
static bool CheckDataType (object values, out bool isNested)
Private Attributes
Chart chart
Static Private Attributes
const string SupportedTypes = "Supported types are: Double, Decimal, Single, int, long, uint, ulong, String, DateTime, short, ushort, and IEnumerable<IEnumerable> containing the previous types."
Additional Inherited Members
Protected Member Functions inherited from CShell.Framework.Sink
Sink ()
string GetUriPathPart (Uri uri, int pathIndex)
Gets the display name from the uri, which is usually the second part of the absolute path.
string GetTitle (Uri uri, string defaultTitle)
Constructor & Destructor Documentation
PlotSinkViewModel()
CShell.Modules.Sink.ViewModels.PlotSinkViewModel.PlotSinkViewModel (Uri uri) inline
References CShell.Framework.Sink.GetTitle(), and CShell.Framework.Document.Uri.
Member Function Documentation
InitChart()
Chart CShell.Modules.Sink.ViewModels.PlotSinkViewModel.InitChart () inline private
References CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Chart.
Referenced by CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Clear(), and CShell.Modules.Sink.ViewModels.PlotSinkViewModel.PlotHistogram().
CheckDataType() [1/2]
static bool CShell.Modules.Sink.ViewModels.PlotSinkViewModel.CheckDataType (object values) inline static private
Referenced by CShell.Modules.Sink.ViewModels.PlotSinkViewModel.CheckDataType(), CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Dump(), CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Plot(), and CShell.Modules.Sink.ViewModels.PlotSinkViewModel.PlotHistogram().
CheckDataType() [2/2]
static bool CShell.Modules.Sink.ViewModels.PlotSinkViewModel.CheckDataType (object values, out bool isNested) inline static private
References CShell.Modules.Sink.ViewModels.PlotSinkViewModel.CheckDataType().
Dump()
override void CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Dump (object o, string description) inline virtual
Implements CShell.Framework.Sink.
References CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Chart, CShell.Modules.Sink.ViewModels.PlotSinkViewModel.CheckDataType(), and CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Plot().
Clear()
override void CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Clear () inline virtual
Implements CShell.Framework.Sink.
References CShell.Modules.Sink.ViewModels.PlotSinkViewModel.InitChart(), and CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Plot().
Plot() [1/4]
void CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Plot (Series series) inline
Implements CShell.Sinks.IPlotSink.
References CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Chart.
Referenced by CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Clear(), CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Dump(), CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Plot(), CShell.Modules.Sink.ViewModels.PlotSinkViewModel.PlotFunction(), and CShell.Modules.Sink.ViewModels.PlotSinkViewModel.PlotHistogram().
Plot() [2/4]
void CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Plot (Chart newChart) inline
Implements CShell.Sinks.IPlotSink.
References CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Chart.
Plot() [3/4]
void CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Plot (IEnumerable ys, string seriesName = null, string chartType = "Line") inline
Implements CShell.Sinks.IPlotSink.
References CShell.Modules.Sink.ViewModels.PlotSinkViewModel.CheckDataType(), CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Plot(), and CShell.Modules.Sink.ViewModels.PlotSinkViewModel.SupportedTypes.
Plot() [4/4]
void CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Plot (IEnumerable ys, IEnumerable xs, string seriesName = null, string chartType = "Line") inline
Implements CShell.Sinks.IPlotSink.
References CShell.Modules.Sink.ViewModels.PlotSinkViewModel.CheckDataType(), CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Plot(), and CShell.Modules.Sink.ViewModels.PlotSinkViewModel.SupportedTypes.
PlotFunction()
void CShell.Modules.Sink.ViewModels.PlotSinkViewModel.PlotFunction (Func< double, double > f, string seriesName = null, string chartType = "Line", double from = -3.0, double to = 3.0, int points = 100) inline
Implements CShell.Sinks.IPlotSink.
References CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Plot().
PlotHistogram()
void CShell.Modules.Sink.ViewModels.PlotSinkViewModel.PlotHistogram (IEnumerable ys, string seriesName = null, string histogramName = null) inline
Implements CShell.Sinks.IPlotSink.
References CShell.Modules.Sink.ViewModels.PlotSinkViewModel.CheckDataType(), CShell.Modules.Sink.ViewModels.PlotSinkViewModel.InitChart(), CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Plot(), and CShell.Modules.Sink.ViewModels.PlotSinkViewModel.SupportedTypes.
Member Data Documentation
chart
Chart CShell.Modules.Sink.ViewModels.PlotSinkViewModel.chart private
SupportedTypes
const string CShell.Modules.Sink.ViewModels.PlotSinkViewModel.SupportedTypes = "Supported types are: Double, Decimal, Single, int, long, uint, ulong, String, DateTime, short, ushort, and IEnumerable<IEnumerable> containing the previous types." static private
Referenced by CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Plot(), and CShell.Modules.Sink.ViewModels.PlotSinkViewModel.PlotHistogram().
Property Documentation
Chart
Chart?? CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Chart get set
Referenced by CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Dump(), CShell.Modules.Sink.ViewModels.PlotSinkViewModel.InitChart(), CShell.Modules.Sink.ViewModels.PlotSinkViewModel.Plot(), and CShell.Modules.Sink.Views.PlotSinkView.VmOnPropertyChanged().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Sink/ViewModels/PlotSinkViewModel.cs