Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DTZRZF Class Reference
DotNumerics.LinearAlgebra.CSLapack.DTZRZF Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DTZRZF (DLARZB dlarzb, DLARZT dlarzt, DLATRZ dlatrz, XERBLA xerbla, ILAENV ilaenv)
DTZRZF ()
void Run (int M, int N, ref double[] A, int offset_a, int LDA, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
DLARZB _dlarzb
DLARZT _dlarzt
DLATRZ _dlatrz
XERBLA _xerbla
ILAENV _ilaenv
Static Private Attributes
const double ZERO = 0.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DTZRZF reduces the M-by-N (M.LE.N) real upper trapezoidal matrix A to upper triangular form by means of orthogonal transformations.
The upper trapezoidal matrix A is factored as
A = (R 0) * Z,
where Z is an N-by-N orthogonal matrix and R is an M-by-M upper triangular matrix.
/summary>
Constructor & Destructor Documentation
DTZRZF() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DTZRZF.DTZRZF (DLARZB dlarzb, DLARZT dlarzt, DLATRZ dlatrz, XERBLA xerbla, ILAENV ilaenv) inline
DTZRZF() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DTZRZF.DTZRZF () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DTZRZF.Run (int M, int N, ref double[] A, int offset_a, int LDA, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DTZRZF reduces the M-by-N (M.LE.N) real upper trapezoidal matrix A to upper triangular form by means of orthogonal transformations.
The upper trapezoidal matrix A is factored as
A = (R 0) * Z,
where Z is an N-by-N orthogonal matrix and R is an M-by-M upper triangular matrix.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. M. /param>
Parameters
A = (R 0) * Z, /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
TAU (output) DOUBLE PRECISION array, dimension (M) The scalar factors of the elementary reflectors. /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. max(1,M). For optimum performance LWORK .GE. M*NB, where NB is the optimal blocksize.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLATRZ.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARZT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARZB.Run(), and DotNumerics.LinearAlgebra.CSLapack.DTZRZF.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGELSY.Run().
Member Data Documentation
_dlarzb
DLARZB DotNumerics.LinearAlgebra.CSLapack.DTZRZF._dlarzb private
_dlarzt
DLARZT DotNumerics.LinearAlgebra.CSLapack.DTZRZF._dlarzt private
_dlatrz
DLATRZ DotNumerics.LinearAlgebra.CSLapack.DTZRZF._dlatrz private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DTZRZF._xerbla private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DTZRZF._ilaenv private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DTZRZF.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTZRZF.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dtzrzf.cs