Doc: IGLib EXTENDED: NUnit.Engine.Drivers.NUnit3FrameworkDriver Class Reference
NUnit.Engine.Drivers.NUnit3FrameworkDriver Class Reference
NUnitFrameworkDriver is used by the test-runner to load and run tests using the NUnit framework assembly.
Public Member Functions
NUnit3FrameworkDriver (AppDomain testDomain)
Construct an NUnit3FrameworkDriver
string Load (string testAssemblyPath, IDictionary< string, object > settings)
Loads the tests in an assembly.
int CountTestCases (string filter)
Count the test cases that would be executed.
string Run (ITestEventListener listener, string filter)
Executes the tests in an assembly.
void StopRun (bool force)
Cancel the ongoing test run. If no test is running, the call is ignored.
string Explore (string filter)
Returns information about the tests in an assembly.
Properties
string ID [get, set]
Properties inherited from NUnit.Engine.Extensibility.IFrameworkDriver
string ID [get, set]
Gets and sets the unique identifier for this driver, used to ensure that test ids are unique across drivers.
Private Member Functions
void CheckLoadWasCalled ()
object CreateObject (string typeName, params object[] args)
Private Attributes
AppDomain _testDomain
string _testAssemblyPath
object _frameworkController
Static Private Attributes
const string NUNIT_FRAMEWORK = "nunit.framework"
const string LOAD_MESSAGE = "Method called without calling Load first"
static readonly string CONTROLLER_TYPE = "NUnit.Framework.Api.FrameworkController"
static readonly string LOAD_ACTION = CONTROLLER_TYPE + "+LoadTestsAction"
static readonly string EXPLORE_ACTION = CONTROLLER_TYPE + "+ExploreTestsAction"
static readonly string COUNT_ACTION = CONTROLLER_TYPE + "+CountTestsAction"
static readonly string RUN_ACTION = CONTROLLER_TYPE + "+RunTestsAction"
static readonly string STOP_RUN_ACTION = CONTROLLER_TYPE + "+StopRunAction"
static ILogger log = InternalTrace.GetLogger("NUnitFrameworkDriver")
Detailed Description
NUnitFrameworkDriver is used by the test-runner to load and run tests using the NUnit framework assembly.
Constructor & Destructor Documentation
NUnit3FrameworkDriver()
NUnit.Engine.Drivers.NUnit3FrameworkDriver.NUnit3FrameworkDriver (AppDomain testDomain) inline
Construct an NUnit3FrameworkDriver
Parameters
testDomain The AppDomain in which to create the FrameworkController
References NUnit.Engine.Drivers.NUnit3FrameworkDriver._testDomain.
Member Function Documentation
Load()
string NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load (string testAssemblyPath, IDictionary< string, object > settings) inline
Loads the tests in an assembly.
Returns
An Xml string representing the loaded test
Implements NUnit.Engine.Extensibility.IFrameworkDriver.
References NUnit.Engine.Drivers.NUnit3FrameworkDriver._frameworkController, NUnit.Engine.Drivers.NUnit3FrameworkDriver._testAssemblyPath, NUnit.Engine.Drivers.NUnit3FrameworkDriver.CONTROLLER_TYPE, NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.ID, NUnit.Engine.Drivers.NUnit3FrameworkDriver.LOAD_ACTION, NUnit.Engine.Drivers.NUnit3FrameworkDriver.log, and NUnit.Engine.CallbackHandler.Result.
Referenced by NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.CountTestsAction_AfterLoad_ReturnsCorrectCount(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.Explore_AfterLoad_ReturnsRunnableSuite(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.Load_GoodFile_ReturnsRunnableSuite(), NUnit.Engine.Services.Tests.TestFilteringTests.LoadAssembly(), and NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite().
CountTestCases()
int NUnit.Engine.Drivers.NUnit3FrameworkDriver.CountTestCases (string filter) inline
Count the test cases that would be executed.
Parameters
filter An XML string representing the TestFilter to use in counting the tests
Returns
The number of test cases counted
Implements NUnit.Engine.Extensibility.IFrameworkDriver.
References NUnit.Engine.Drivers.NUnit3FrameworkDriver._frameworkController, NUnit.Engine.Drivers.NUnit3FrameworkDriver.CheckLoadWasCalled(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.COUNT_ACTION, NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(), and NUnit.Engine.CallbackHandler.Result.
Referenced by NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.CountTestsAction_AfterLoad_ReturnsCorrectCount(), NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.CountTestsAction_WithoutLoad_ThrowsInvalidOperationException(), NUnit.Engine.Services.Tests.TestFilteringTests.UsingTestFilterBuilderAddTest(), NUnit.Engine.Services.Tests.TestFilteringTests.UsingTestFilterBuilderSelectWhere(), and NUnit.Engine.Services.Tests.TestFilteringTests.UsingXml().
Run()
string NUnit.Engine.Drivers.NUnit3FrameworkDriver.Run (ITestEventListener listener, string filter) inline
Executes the tests in an assembly.
Parameters
listener An ITestEventHandler that receives progress notices
filter A filter that controls which tests are executed
Returns
An Xml string representing the result
Implements NUnit.Engine.Extensibility.IFrameworkDriver.
References NUnit.Engine.Drivers.NUnit3FrameworkDriver._frameworkController, NUnit.Engine.Drivers.NUnit3FrameworkDriver._testAssemblyPath, NUnit.Engine.Drivers.NUnit3FrameworkDriver.CheckLoadWasCalled(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.log, NUnit.Engine.CallbackHandler.Result, and NUnit.Engine.Drivers.NUnit3FrameworkDriver.RUN_ACTION.
Referenced by NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.RunTestsAction_AfterLoad_ReturnsRunnableSuite(), and NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.RunTestsAction_WithoutLoad_ThrowsInvalidOperationException().
StopRun()
void NUnit.Engine.Drivers.NUnit3FrameworkDriver.StopRun (bool force) inline
Cancel the ongoing test run. If no test is running, the call is ignored.
Parameters
force If true, cancel any ongoing test threads, otherwise wait for them to complete.
Implements NUnit.Engine.Extensibility.IFrameworkDriver.
References NUnit.Engine.Drivers.NUnit3FrameworkDriver._frameworkController, NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(), and NUnit.Engine.Drivers.NUnit3FrameworkDriver.STOP_RUN_ACTION.
Explore()
string NUnit.Engine.Drivers.NUnit3FrameworkDriver.Explore (string filter) inline
Returns information about the tests in an assembly.
Parameters
filter A filter indicating which tests to include
Returns
An Xml string representing the tests
Implements NUnit.Engine.Extensibility.IFrameworkDriver.
References NUnit.Engine.Drivers.NUnit3FrameworkDriver._frameworkController, NUnit.Engine.Drivers.NUnit3FrameworkDriver._testAssemblyPath, NUnit.Engine.Drivers.NUnit3FrameworkDriver.CheckLoadWasCalled(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.EXPLORE_ACTION, NUnit.Engine.Drivers.NUnit3FrameworkDriver.log, and NUnit.Engine.CallbackHandler.Result.
Referenced by NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.Explore_AfterLoad_ReturnsRunnableSuite(), and NUnit.Engine.Drivers.Tests.NUnit3FrameworkDriverTests.ExploreTestsAction_WithoutLoad_ThrowsInvalidOperationException().
CheckLoadWasCalled()
void NUnit.Engine.Drivers.NUnit3FrameworkDriver.CheckLoadWasCalled () inline private
References NUnit.Engine.Drivers.NUnit3FrameworkDriver._frameworkController, and NUnit.Engine.Drivers.NUnit3FrameworkDriver.LOAD_MESSAGE.
Referenced by NUnit.Engine.Drivers.NUnit3FrameworkDriver.CountTestCases(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.Explore(), and NUnit.Engine.Drivers.NUnit3FrameworkDriver.Run().
CreateObject()
object NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject (string typeName, params object[] args) inline private
References NUnit.Engine.Drivers.NUnit3FrameworkDriver._testDomain, and NUnit.Engine.Drivers.NUnit3FrameworkDriver.NUNIT_FRAMEWORK.
Referenced by NUnit.Engine.Drivers.NUnit3FrameworkDriver.CountTestCases(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.Explore(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.Run(), and NUnit.Engine.Drivers.NUnit3FrameworkDriver.StopRun().
Member Data Documentation
NUNIT_FRAMEWORK
const string NUnit.Engine.Drivers.NUnit3FrameworkDriver.NUNIT_FRAMEWORK = "nunit.framework" static private
Referenced by NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject().
LOAD_MESSAGE
const string NUnit.Engine.Drivers.NUnit3FrameworkDriver.LOAD_MESSAGE = "Method called without calling Load first" static private
Referenced by NUnit.Engine.Drivers.NUnit3FrameworkDriver.CheckLoadWasCalled().
CONTROLLER_TYPE
readonly string NUnit.Engine.Drivers.NUnit3FrameworkDriver.CONTROLLER_TYPE = "NUnit.Framework.Api.FrameworkController" static private
Referenced by NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load().
LOAD_ACTION
readonly string NUnit.Engine.Drivers.NUnit3FrameworkDriver.LOAD_ACTION = CONTROLLER_TYPE + "+LoadTestsAction" static private
Referenced by NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load().
EXPLORE_ACTION
readonly string NUnit.Engine.Drivers.NUnit3FrameworkDriver.EXPLORE_ACTION = CONTROLLER_TYPE + "+ExploreTestsAction" static private
Referenced by NUnit.Engine.Drivers.NUnit3FrameworkDriver.Explore().
COUNT_ACTION
readonly string NUnit.Engine.Drivers.NUnit3FrameworkDriver.COUNT_ACTION = CONTROLLER_TYPE + "+CountTestsAction" static private
Referenced by NUnit.Engine.Drivers.NUnit3FrameworkDriver.CountTestCases().
RUN_ACTION
readonly string NUnit.Engine.Drivers.NUnit3FrameworkDriver.RUN_ACTION = CONTROLLER_TYPE + "+RunTestsAction" static private
Referenced by NUnit.Engine.Drivers.NUnit3FrameworkDriver.Run().
STOP_RUN_ACTION
readonly string NUnit.Engine.Drivers.NUnit3FrameworkDriver.STOP_RUN_ACTION = CONTROLLER_TYPE + "+StopRunAction" static private
Referenced by NUnit.Engine.Drivers.NUnit3FrameworkDriver.StopRun().
log
ILogger NUnit.Engine.Drivers.NUnit3FrameworkDriver.log = InternalTrace.GetLogger("NUnitFrameworkDriver") static private
Referenced by NUnit.Engine.Drivers.NUnit3FrameworkDriver.Explore(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(), and NUnit.Engine.Drivers.NUnit3FrameworkDriver.Run().
_testDomain
AppDomain NUnit.Engine.Drivers.NUnit3FrameworkDriver._testDomain private
Referenced by NUnit.Engine.Drivers.NUnit3FrameworkDriver.CreateObject(), and NUnit.Engine.Drivers.NUnit3FrameworkDriver.NUnit3FrameworkDriver().
_testAssemblyPath
string NUnit.Engine.Drivers.NUnit3FrameworkDriver._testAssemblyPath private
Referenced by NUnit.Engine.Drivers.NUnit3FrameworkDriver.Explore(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(), and NUnit.Engine.Drivers.NUnit3FrameworkDriver.Run().
_frameworkController
object NUnit.Engine.Drivers.NUnit3FrameworkDriver._frameworkController private
Referenced by NUnit.Engine.Drivers.NUnit3FrameworkDriver.CheckLoadWasCalled(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.CountTestCases(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.Explore(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load(), NUnit.Engine.Drivers.NUnit3FrameworkDriver.Run(), and NUnit.Engine.Drivers.NUnit3FrameworkDriver.StopRun().
Property Documentation
ID
string NUnit.Engine.Drivers.NUnit3FrameworkDriver.ID get set
Referenced by NUnit.Engine.Drivers.NUnit3FrameworkDriver.Load().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Drivers/NUnit3FrameworkDriver.cs