Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DSTEQR Class Reference
DotNumerics.LinearAlgebra.CSLapack.DSTEQR Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DSTEQR (LSAME lsame, DLAMCH dlamch, DLANST dlanst, DLAPY2 dlapy2, DLAE2 dlae2, DLAEV2 dlaev2, DLARTG dlartg, DLASCL dlascl, DLASET dlaset, DLASR dlasr, DLASRT dlasrt, DSWAP dswap, XERBLA xerbla)
DSTEQR ()
void Run (string COMPZ, int N, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] Z, int offset_z, int LDZ, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
LSAME _lsame
DLAMCH _dlamch
DLANST _dlanst
DLAPY2 _dlapy2
DLAE2 _dlae2
DLAEV2 _dlaev2
DLARTG _dlartg
DLASCL _dlascl
DLASET _dlaset
DLASR _dlasr
DLASRT _dlasrt
DSWAP _dswap
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
const double TWO = 2.0E0
const double THREE = 3.0E0
const int MAXIT = 30
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DSTEQR computes all eigenvalues and, optionally, eigenvectors of a symmetric tridiagonal matrix using the implicit QL or QR method. The eigenvectors of a full or band symmetric matrix can also be found if DSYTRD or DSPTRD or DSBTRD has been used to reduce this matrix to tridiagonal form.
/summary>
Constructor & Destructor Documentation
DSTEQR() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DSTEQR.DSTEQR (LSAME lsame, DLAMCH dlamch, DLANST dlanst, DLAPY2 dlapy2, DLAE2 dlae2, DLAEV2 dlaev2, DLARTG dlartg, DLASCL dlascl, DLASET dlaset, DLASR dlasr, DLASRT dlasrt, DSWAP dswap, XERBLA xerbla) inline
DSTEQR() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DSTEQR.DSTEQR () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run (string COMPZ, int N, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] Z, int offset_z, int LDZ, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
DSTEQR computes all eigenvalues and, optionally, eigenvectors of a symmetric tridiagonal matrix using the implicit QL or QR method. The eigenvectors of a full or band symmetric matrix can also be found if DSYTRD or DSPTRD or DSBTRD has been used to reduce this matrix to tridiagonal form.
/summary>
Parameters
COMPZ (input) CHARACTER*1 = 'N': Compute eigenvalues only. = 'V': Compute eigenvalues and eigenvectors of the original symmetric matrix. On entry, Z must contain the orthogonal matrix used to reduce the original matrix to tridiagonal form. = 'I': Compute eigenvalues and eigenvectors of the tridiagonal matrix. Z is initialized to the identity matrix. /param>
Parameters
N (input) INTEGER The order of the matrix. N .GE. 0. /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension (N) On entry, the diagonal elements of the tridiagonal matrix. On exit, if INFO = 0, the eigenvalues in ascending order. /param>
Parameters
E (input/output) DOUBLE PRECISION array, dimension (N-1) On entry, the (n-1) subdiagonal elements of the tridiagonal matrix. On exit, E has been destroyed. /param>
Parameters
Z (input/output) DOUBLE PRECISION array, dimension (LDZ, N) On entry, if COMPZ = 'V', then Z contains the orthogonal matrix used in the reduction to tridiagonal form. On exit, if INFO = 0, then if COMPZ = 'V', Z contains the orthonormal eigenvectors of the original symmetric matrix, and if COMPZ = 'I', Z contains the orthonormal eigenvectors of the symmetric tridiagonal matrix. If COMPZ = 'N', then Z is not referenced. /param>
Parameters
LDZ (input) INTEGER The leading dimension of the array Z. LDZ .GE. 1, and if eigenvectors are desired, then LDZ .GE. max(1,N). /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (max(1,2*N-2)) If COMPZ = 'N', then WORK is not referenced. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value .GT. 0: the algorithm has failed to find all the eigenvalues in a total of 30*N iterations; if INFO = i, then i elements of E have not converged to zero; on exit, D and E contain the elements of a symmetric tridiagonal matrix which is orthogonally similar to the original matrix. /param>
References DotNumerics.LinearAlgebra.CSLapack.DSTEQR.MAXIT, DotNumerics.LinearAlgebra.CSLapack.DSTEQR.ONE, DotNumerics.LinearAlgebra.CSLapack.DSWAP.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAPY2.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAE2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAEV2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASRT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASET.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARTG.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANST.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASR.Run(), DotNumerics.FortranLibrary.FortranLib.Sign(), DotNumerics.LinearAlgebra.CSLapack.DSTEQR.THREE, DotNumerics.LinearAlgebra.CSLapack.DSTEQR.TWO, and DotNumerics.LinearAlgebra.CSLapack.DSTEQR.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSBEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED0.Run(), and DotNumerics.LinearAlgebra.CSLapack.DSTEDC.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DSTEQR._lsame private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DSTEQR._dlamch private
_dlanst
DLANST DotNumerics.LinearAlgebra.CSLapack.DSTEQR._dlanst private
_dlapy2
DLAPY2 DotNumerics.LinearAlgebra.CSLapack.DSTEQR._dlapy2 private
_dlae2
DLAE2 DotNumerics.LinearAlgebra.CSLapack.DSTEQR._dlae2 private
_dlaev2
DLAEV2 DotNumerics.LinearAlgebra.CSLapack.DSTEQR._dlaev2 private
_dlartg
DLARTG DotNumerics.LinearAlgebra.CSLapack.DSTEQR._dlartg private
_dlascl
DLASCL DotNumerics.LinearAlgebra.CSLapack.DSTEQR._dlascl private
_dlaset
DLASET DotNumerics.LinearAlgebra.CSLapack.DSTEQR._dlaset private
_dlasr
DLASR DotNumerics.LinearAlgebra.CSLapack.DSTEQR._dlasr private
_dlasrt
DLASRT DotNumerics.LinearAlgebra.CSLapack.DSTEQR._dlasrt private
_dswap
DSWAP DotNumerics.LinearAlgebra.CSLapack.DSTEQR._dswap private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DSTEQR._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DSTEQR.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DSTEQR.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run().
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DSTEQR.TWO = 2.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run().
THREE
const double DotNumerics.LinearAlgebra.CSLapack.DSTEQR.THREE = 3.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run().
MAXIT
const int DotNumerics.LinearAlgebra.CSLapack.DSTEQR.MAXIT = 30 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dsteqr.cs