Doc: IGLib EXTENDED: CShellCore.CodeCompletion.CSharpCompletionDataFactory Class Reference
CShellCore.CodeCompletion.CSharpCompletionDataFactory Class Reference
Public Member Functions
CSharpCompletionDataFactory (CSharpTypeResolveContext contextAtCaret, CSharpCompletionContext context)
IParameterDataProvider CreateIndexerParameterDataProvider (int startOffset, IType type, IEnumerable< IProperty > accessibleIndexers, AstNode resolvedNode)
IParameterDataProvider CreateTypeParameterDataProvider (int startOffset, IEnumerable< IMethod > methods)
Private Member Functions
ICompletionData ICompletionDataFactory. CreateEntityCompletionData (IEntity entity)
ICompletionData ICompletionDataFactory. CreateEntityCompletionData (IEntity entity, string text)
ICompletionData ICompletionDataFactory. CreateTypeCompletionData (IType type, bool showFullName, bool isInAttributeContext, bool addForTypeCreation)
ICompletionData ICompletionDataFactory. CreateMemberCompletionData (IType type, IEntity member)
ICompletionData ICompletionDataFactory. CreateLiteralCompletionData (string title, string description, string insertText)
ICompletionData ICompletionDataFactory. CreateNamespaceCompletionData (INamespace name)
ICompletionData ICompletionDataFactory. CreateVariableCompletionData (IVariable variable)
ICompletionData ICompletionDataFactory. CreateVariableCompletionData (ITypeParameter parameter)
ICompletionData ICompletionDataFactory. CreateEventCreationCompletionData (string varName, IType delegateType, IEvent evt, string parameterDefinition, IUnresolvedMember currentMember, IUnresolvedTypeDefinition currentType)
ICompletionData ICompletionDataFactory. CreateNewOverrideCompletionData (int declarationBegin, IUnresolvedTypeDefinition type, IMember m)
ICompletionData ICompletionDataFactory. CreateNewPartialCompletionData (int declarationBegin, IUnresolvedTypeDefinition type, IUnresolvedMember m)
IEnumerable< ICompletionData > ICompletionDataFactory. CreateCodeTemplateCompletionData ()
IEnumerable< ICompletionData > ICompletionDataFactory. CreatePreProcessorDefinesCompletionData ()
ICompletionData ICompletionDataFactory. CreateImportCompletionData (IType type, bool useFullName, bool addForTypeCreation)
ICompletionData ICompletionDataFactory. CreateFormatItemCompletionData (string format, string description, object example)
ICompletionData ICompletionDataFactory. CreateXmlDocCompletionData (string tag, string description=null, string tagInsertionText=null)
IParameterDataProvider CreateMethodDataProvider (int startOffset, IEnumerable< IParameterizedMember > methods)
IParameterDataProvider IParameterCompletionDataFactory. CreateConstructorProvider (int startOffset, IType type)
IParameterDataProvider IParameterCompletionDataFactory. CreateConstructorProvider (int startOffset, IType type, AstNode thisInitializer)
IParameterDataProvider IParameterCompletionDataFactory. CreateMethodDataProvider (int startOffset, IEnumerable< IMethod > methods)
IParameterDataProvider IParameterCompletionDataFactory. CreateDelegateDataProvider (int startOffset, IType type)
IParameterDataProvider IParameterCompletionDataFactory. CreateTypeParameterDataProvider (int startOffset, IEnumerable< IType > types)
Private Attributes
readonly CSharpTypeResolveContext contextAtCaret
readonly CSharpCompletionContext context
Constructor & Destructor Documentation
CSharpCompletionDataFactory()
CShellCore.CodeCompletion.CSharpCompletionDataFactory.CSharpCompletionDataFactory (CSharpTypeResolveContext contextAtCaret, CSharpCompletionContext context) inline
References CShellCore.CodeCompletion.CSharpCompletionDataFactory.context, and CShellCore.CodeCompletion.CSharpCompletionDataFactory.contextAtCaret.
Member Function Documentation
CreateEntityCompletionData() [1/2]
ICompletionData ICompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateEntityCompletionData (IEntity entity) inline private
CreateEntityCompletionData() [2/2]
ICompletionData ICompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateEntityCompletionData (IEntity entity, string text) inline private
CreateTypeCompletionData()
ICompletionData ICompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateTypeCompletionData (IType type, bool showFullName, bool isInAttributeContext, bool addForTypeCreation) inline private
CreateMemberCompletionData()
ICompletionData ICompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateMemberCompletionData (IType type, IEntity member) inline private
CreateLiteralCompletionData()
ICompletionData ICompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateLiteralCompletionData (string title, string description, string insertText) inline private
References CShellCore.CodeCompletion.Images.CompletionImage.BaseImage, and CShellCore.CodeCompletion.Images.CompletionImage.Literal.
CreateNamespaceCompletionData()
ICompletionData ICompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateNamespaceCompletionData (INamespace name) inline private
References CShellCore.CodeCompletion.Images.CompletionImage.NamespaceImage.
CreateVariableCompletionData() [1/2]
ICompletionData ICompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateVariableCompletionData (IVariable variable) inline private
CreateVariableCompletionData() [2/2]
ICompletionData ICompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateVariableCompletionData (ITypeParameter parameter) inline private
CreateEventCreationCompletionData()
ICompletionData ICompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateEventCreationCompletionData (string varName, IType delegateType, IEvent evt, string parameterDefinition, IUnresolvedMember currentMember, IUnresolvedTypeDefinition currentType) inline private
CreateNewOverrideCompletionData()
ICompletionData ICompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateNewOverrideCompletionData (int declarationBegin, IUnresolvedTypeDefinition type, IMember m) inline private
References CShellCore.CodeCompletion.CSharpCompletionDataFactory.contextAtCaret.
CreateNewPartialCompletionData()
ICompletionData ICompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateNewPartialCompletionData (int declarationBegin, IUnresolvedTypeDefinition type, IUnresolvedMember m) inline private
CreateCodeTemplateCompletionData()
IEnumerable<ICompletionData> ICompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateCodeTemplateCompletionData () inline private
CreatePreProcessorDefinesCompletionData()
IEnumerable<ICompletionData> ICompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreatePreProcessorDefinesCompletionData () inline private
CreateImportCompletionData()
ICompletionData ICompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateImportCompletionData (IType type, bool useFullName, bool addForTypeCreation) inline private
References CShellCore.CodeCompletion.CSharpCompletionDataFactory.contextAtCaret.
CreateFormatItemCompletionData()
ICompletionData ICompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateFormatItemCompletionData (string format, string description, object example) inline private
CreateXmlDocCompletionData()
ICompletionData ICompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateXmlDocCompletionData (string tag, string description = null, string tagInsertionText = null) inline private
CreateMethodDataProvider() [1/2]
IParameterDataProvider CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateMethodDataProvider (int startOffset, IEnumerable< IParameterizedMember > methods) inline private
References CShellCore.CodeCompletion.CSharpCompletionDataFactory.context.
Referenced by CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateConstructorProvider(), CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateDelegateDataProvider(), CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateMethodDataProvider(), and CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateTypeParameterDataProvider().
CreateConstructorProvider() [1/2]
IParameterDataProvider IParameterCompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateConstructorProvider (int startOffset, IType type) inline private
References CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateMethodDataProvider().
CreateConstructorProvider() [2/2]
IParameterDataProvider IParameterCompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateConstructorProvider (int startOffset, IType type, AstNode thisInitializer) inline private
References CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateMethodDataProvider().
CreateMethodDataProvider() [2/2]
IParameterDataProvider IParameterCompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateMethodDataProvider (int startOffset, IEnumerable< IMethod > methods) inline private
References CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateMethodDataProvider().
CreateDelegateDataProvider()
IParameterDataProvider IParameterCompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateDelegateDataProvider (int startOffset, IType type) inline private
References CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateMethodDataProvider().
CreateIndexerParameterDataProvider()
IParameterDataProvider CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateIndexerParameterDataProvider (int startOffset, IType type, IEnumerable< IProperty > accessibleIndexers, AstNode resolvedNode) inline
CreateTypeParameterDataProvider() [1/2]
IParameterDataProvider IParameterCompletionDataFactory. CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateTypeParameterDataProvider (int startOffset, IEnumerable< IType > types) inline private
CreateTypeParameterDataProvider() [2/2]
IParameterDataProvider CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateTypeParameterDataProvider (int startOffset, IEnumerable< IMethod > methods) inline
References CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateMethodDataProvider().
Member Data Documentation
contextAtCaret
readonly CSharpTypeResolveContext CShellCore.CodeCompletion.CSharpCompletionDataFactory.contextAtCaret private
Referenced by CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateImportCompletionData(), CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateNewOverrideCompletionData(), and CShellCore.CodeCompletion.CSharpCompletionDataFactory.CSharpCompletionDataFactory().
context
readonly CSharpCompletionContext CShellCore.CodeCompletion.CSharpCompletionDataFactory.context private
Referenced by CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateMethodDataProvider(), and CShellCore.CodeCompletion.CSharpCompletionDataFactory.CSharpCompletionDataFactory().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore.CodeCompletion/CSharpCompletionDataFactory.cs