Doc: IGLib EXTENDED: NUnit.Framework.Attributes.TheoryTests.SqrtTests Class Reference
NUnit.Framework.Attributes.TheoryTests.SqrtTests Class Reference
Public Member Functions
void SqrtTimesItselfGivesOriginal (double num)
Public Attributes
double zero = 0
double positive = 1
double negative = -1
double max = double.MaxValue
double infinity = double.PositiveInfinity
Member Function Documentation
SqrtTimesItselfGivesOriginal()
void NUnit.Framework.Attributes.TheoryTests.SqrtTests.SqrtTimesItselfGivesOriginal (double num) inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
Member Data Documentation
zero
double NUnit.Framework.Attributes.TheoryTests.SqrtTests.zero = 0
positive
double NUnit.Framework.Attributes.TheoryTests.SqrtTests.positive = 1
negative
double NUnit.Framework.Attributes.TheoryTests.SqrtTests.negative = -1
max
double NUnit.Framework.Attributes.TheoryTests.SqrtTests.max = double.MaxValue
infinity
double NUnit.Framework.Attributes.TheoryTests.SqrtTests.infinity = double.PositiveInfinity
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/TheoryTests.cs