Doc: IGLib EXTENDED: AForge.Imaging.Formats.ImageDecoder Class Reference
AForge.Imaging.Formats.ImageDecoder Class Reference
Image decoder to decode different custom image file formats.
Static Public Member Functions
static void RegisterDecoder (string fileExtension, IImageDecoder decoder)
Register image decoder for a specified file extension.
static Bitmap DecodeFromFile (string fileName)
Decode first frame for the specified file.
static Bitmap DecodeFromFile (string fileName, out ImageInfo imageInfo)
Decode first frame for the specified file.
Static Private Member Functions
static ImageDecoder ()
static System.Drawing.Bitmap FromFile (string fileName)
Static Private Attributes
static Dictionary< string, IImageDecoder > decoders = new Dictionary<string, IImageDecoder>()
Detailed Description
Image decoder to decode different custom image file formats.
The class represent a help class, which simplifies decoding of image files finding appropriate image decoder automatically (using list of registered image decoders). Instead of using required image decoder directly, users may use this class, which will find required decoder by file's extension.
By default the class registers on its own all decoders, which are available in AForge.Imaging.Formats library. If user has implementation of his own image decoders, he needs to register them using RegisterDecoder method to be able to use them through the ImageDecoder class.
<note>If the class can not find appropriate decode in the list of registered decoders, it passes file to .NET's image decoder for decoding.</note>
Sample usage:
// sample file name
string fileName = "myFile.pnm";
// decode image file
Bitmap = ImageDecoder.DecodeFromFile(fileName);
See also
PNMCodec, FITSCodec
Constructor & Destructor Documentation
ImageDecoder()
static AForge.Imaging.Formats.ImageDecoder.ImageDecoder () inline static private
References AForge.Imaging.Formats.ImageDecoder.RegisterDecoder().
Member Function Documentation
RegisterDecoder()
static void AForge.Imaging.Formats.ImageDecoder.RegisterDecoder (string fileExtension, IImageDecoder decoder) inline static
Register image decoder for a specified file extension.
Parameters
fileExtension File extension to register decoder for ("bmp", for example).
decoder Image decoder to use for the specified file extension.
The method allows to register image decoder object, which should be used to decode images from files with the specified extension.
References AForge.Imaging.Formats.ImageDecoder.decoders.
Referenced by AForge.Imaging.Formats.ImageDecoder.ImageDecoder().
DecodeFromFile() [1/2]
static Bitmap AForge.Imaging.Formats.ImageDecoder.DecodeFromFile (string fileName) inline static
Decode first frame for the specified file.
Parameters
fileName File name to read image from.
Returns
Return decoded image. In the case if file format support multiple frames, the method return the first frame.
The method uses table of registered image decoders to find the one, which should be used for the specified file. If there is not appropriate decoder found, the method uses default .NET's image decoding routine (see System.Drawing.Image.FromFile(string)).
Referenced by ImageViewer.MainForm.openToolStripMenuItem_Click().
DecodeFromFile() [2/2]
static Bitmap AForge.Imaging.Formats.ImageDecoder.DecodeFromFile (string fileName, out ImageInfo imageInfo) inline static
Decode first frame for the specified file.
Parameters
fileName File name to read image from.
imageInfo Information about the decoded image.
Returns
Return decoded image. In the case if file format support multiple frames, the method return the first frame.
The method uses table of registered image decoders to find the one, which should be used for the specified file. If there is not appropriate decoder found, the method uses default .NET's image decoding routine (see System.Drawing.Image.FromFile(string)).
References AForge.Imaging.Formats.IImageDecoder.Close(), AForge.Imaging.Formats.IImageDecoder.DecodeFrame(), AForge.Imaging.Formats.ImageDecoder.decoders, AForge.Imaging.Formats.ImageDecoder.FromFile(), and AForge.Imaging.Formats.IImageDecoder.Open().
FromFile()
static System.Drawing.Bitmap AForge.Imaging.Formats.ImageDecoder.FromFile (string fileName) inline static private
Referenced by AForge.Imaging.Formats.ImageDecoder.DecodeFromFile().
Member Data Documentation
decoders
Dictionary< string, IImageDecoder > AForge.Imaging.Formats.ImageDecoder.decoders = new Dictionary<string, IImageDecoder>() static private
Referenced by AForge.Imaging.Formats.ImageDecoder.DecodeFromFile(), and AForge.Imaging.Formats.ImageDecoder.RegisterDecoder().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging.Formats/ImageDecoder.cs