Doc: IGLib EXTENDED: Meta.Numerics.Matrices.AnyRectangularMatrix Class Reference
Meta.Numerics.Matrices.AnyRectangularMatrix Class Reference
Describes the form of all real matrices.
Public Member Functions
virtual double OneNorm ()
Computes the 1-norm of the matrix.
virtual double InfinityNorm ()
Computes the &#x221E;-norm of the matrix.
virtual double FrobeniusNorm ()
Computes the Frobenius-norm of the matrix.
virtual ColumnVector Column (int c)
Gets a copy of the specified column.
virtual RowVector Row (int r)
Gets a copy of the specified row.
virtual SymmetricMatrix MultiplySelfByTranspose ()
Computes the product of the matrix and its transpose.
virtual SymmetricMatrix MultiplyTransposeBySelf ()
Computes the product of the matrix's transpose and itself.
bool Equals (AnyRectangularMatrix other)
Determines whether the given matrix equals the current matrix.
override bool Equals (object obj)
Determines whether the given object is an equal matrix.
override int GetHashCode ()
Not a valid operation.
Public Member Functions inherited from Meta.Numerics.Matrices.AnyMatrix< double >
virtual void Fill (Func< int, int, T > f)
Sets all matrix entries according to a supplied fill function.
virtual T[,] ToArray ()
Copies the matrix into an array.
Static Public Member Functions
static RectangularMatrix operator+ (AnyRectangularMatrix A, AnyRectangularMatrix B)
Adds any two real, rectangular matrices.
static RectangularMatrix operator- (AnyRectangularMatrix A, AnyRectangularMatrix B)
Subtracts any two real, rectangular matrices.
static RectangularMatrix operator* (AnyRectangularMatrix A, AnyRectangularMatrix B)
Multiplies any two real, rectangular matrices.
static RectangularMatrix operator* (double alpha, AnyRectangularMatrix A)
Multiplies any real, rectangular matrix by a real constant.
static ColumnVector operator* (AnyRectangularMatrix A, ColumnVector v)
Multiplies any real, rectangular matrix with a real column vector.
static bool operator== (AnyRectangularMatrix A, AnyRectangularMatrix B)
Determines whether two matrices are equal.
static bool operator!= (AnyRectangularMatrix A, AnyRectangularMatrix B)
Determines whether two matrices are not equal.
Protected Member Functions
AnyRectangularMatrix ()
Protected Member Functions inherited from Meta.Numerics.Matrices.AnyMatrix< double >
AnyMatrix ()
Static Private Member Functions
static bool InternalEquals (AnyRectangularMatrix A, AnyRectangularMatrix B)
Additional Inherited Members
Properties inherited from Meta.Numerics.Matrices.AnyMatrix< double >
abstract int RowCount [get]
Gets the number of matrix rows.
abstract int ColumnCount [get]
Gets the number of matrix columns.
abstract T this[int r, int c] [get, set]
Gets or sets the value of a matrix entry.
bool IsReadOnly [get, set]
Gets a flag indicating whether the matrix is read-only.
Detailed Description
Describes the form of all real matrices.
This is an abstract class that describes any real matrix. If you wish to create a concrete instance of a real, non-square matrix, use the RectangularMatrix class. If, on the other hand, you wish to write a function that can operate on any real matrix, it's probably a good idea to accept a AnyRectangularMatrix, so that any concrete implementation can also be passed into your function.
Constructor & Destructor Documentation
AnyRectangularMatrix()
Meta.Numerics.Matrices.AnyRectangularMatrix.AnyRectangularMatrix () inline protected
Member Function Documentation
OneNorm()
virtual double Meta.Numerics.Matrices.AnyRectangularMatrix.OneNorm () inline virtual
Computes the 1-norm of the matrix.
Returns
||M||1
The 1-norm of a matrix is the largest column sum.
Reimplemented in Meta.Numerics.Matrices.SquareMatrix, and Meta.Numerics.Matrices.RectangularMatrix.
References Meta.Numerics.Matrices.AnyMatrix< double >.ColumnCount, and Meta.Numerics.Matrices.AnyMatrix< double >.RowCount.
InfinityNorm()
virtual double Meta.Numerics.Matrices.AnyRectangularMatrix.InfinityNorm () inline virtual
Computes the &#x221E;-norm of the matrix.
Returns
||M||&#x221E;
The &#x221E;-norm of a matrix is the largest row sum.
Reimplemented in Meta.Numerics.Matrices.SquareMatrix, and Meta.Numerics.Matrices.RectangularMatrix.
References Meta.Numerics.Matrices.AnyMatrix< double >.ColumnCount, and Meta.Numerics.Matrices.AnyMatrix< double >.RowCount.
Referenced by Meta.Numerics.Analysis.FunctionMath.FindZero().
FrobeniusNorm()
virtual double Meta.Numerics.Matrices.AnyRectangularMatrix.FrobeniusNorm () inline virtual
Computes the Frobenius-norm of the matrix.
Returns
||M||F
The Frobenius-norm of a matrix the square root of the sum of the squares of all the elements. In the case of a row or column vector, this reduces to the Euclidean vector norm.
References Meta.Numerics.Matrices.AnyMatrix< double >.ColumnCount, Meta.Numerics.Matrices.AnyMatrix< double >.RowCount, and Meta.Numerics.MoreMath.Sqr().
Referenced by Meta.Numerics.Matrices.SparseSquareMatrix.Solve().
Column()
virtual ColumnVector Meta.Numerics.Matrices.AnyRectangularMatrix.Column (int c) inline virtual
Gets a copy of the specified column.
Parameters
c The (zero-based) column index.
Returns
An independent copy of the specified column.
Reimplemented in Meta.Numerics.Matrices.SparseSquareMatrix, Meta.Numerics.Matrices.SquareMatrix, and Meta.Numerics.Matrices.RectangularMatrix.
References Meta.Numerics.Matrices.AnyMatrix< double >.ColumnCount, and Meta.Numerics.Matrices.AnyMatrix< double >.RowCount.
Referenced by Test.RectangularMatrixTest.RectangularMatrixAccess().
Row()
virtual RowVector Meta.Numerics.Matrices.AnyRectangularMatrix.Row (int r) inline virtual
Gets a copy of the specified row.
Parameters
r The (zero-based) row index.
Returns
An independent copy of the specified row.
Reimplemented in Meta.Numerics.Matrices.SparseSquareMatrix, Meta.Numerics.Matrices.RectangularMatrix, and Meta.Numerics.Matrices.SquareMatrix.
References Meta.Numerics.Matrices.AnyMatrix< double >.ColumnCount, and Meta.Numerics.Matrices.AnyMatrix< double >.RowCount.
Referenced by Test.RectangularMatrixTest.RectangularMatrixAccess(), and Test.SymmetricMatrixTest.SymmetricMatrixAccess().
operator+()
static RectangularMatrix Meta.Numerics.Matrices.AnyRectangularMatrix.operator+ (AnyRectangularMatrix A, AnyRectangularMatrix B) inline static
Adds any two real, rectangular matrices.
Parameters
A The first matrix.
B The second matrix.
Returns
The sum matrix A + B.
Matrix addition is an O(N2) process.
operator-()
static RectangularMatrix Meta.Numerics.Matrices.AnyRectangularMatrix.operator- (AnyRectangularMatrix A, AnyRectangularMatrix B) inline static
Subtracts any two real, rectangular matrices.
Parameters
A The first matrix.
B The second matrix.
Returns
The difference matrix A - B.
Matrix subtraction is an O(N2) process.
operator*() [1/3]
static RectangularMatrix Meta.Numerics.Matrices.AnyRectangularMatrix.operator* (AnyRectangularMatrix A, AnyRectangularMatrix B) inline static
Multiplies any two real, rectangular matrices.
Parameters
A The first matrix.
B The second matrix.
Returns
The product matrix AB.
For matrix multiplication, the column count of the first matrix must equal the row count of the second matrix.
Matrix multiplication is an O(N3) process.
MultiplySelfByTranspose()
virtual SymmetricMatrix Meta.Numerics.Matrices.AnyRectangularMatrix.MultiplySelfByTranspose () inline virtual
Computes the product of the matrix and its transpose.
Returns
The product matrix A AT.
References Meta.Numerics.Matrices.AnyMatrix< double >.ColumnCount, and Meta.Numerics.Matrices.AnyMatrix< double >.RowCount.
MultiplyTransposeBySelf()
virtual SymmetricMatrix Meta.Numerics.Matrices.AnyRectangularMatrix.MultiplyTransposeBySelf () inline virtual
Computes the product of the matrix's transpose and itself.
Returns
The product matrix AT A.
References Meta.Numerics.Matrices.AnyMatrix< double >.ColumnCount, and Meta.Numerics.Matrices.AnyMatrix< double >.RowCount.
operator*() [2/3]
static RectangularMatrix Meta.Numerics.Matrices.AnyRectangularMatrix.operator* (double alpha, AnyRectangularMatrix A) inline static
Multiplies any real, rectangular matrix by a real constant.
Parameters
alpha The constant.
A The matrix.
Returns
The product matrix.
operator*() [3/3]
static ColumnVector Meta.Numerics.Matrices.AnyRectangularMatrix.operator* (AnyRectangularMatrix A, ColumnVector v) inline static
Multiplies any real, rectangular matrix with a real column vector.
Parameters
A The matrix.
v The column vector.
Returns
The product column vector.
References Meta.Numerics.Matrices.VectorBase.Dimension.
InternalEquals()
static bool Meta.Numerics.Matrices.AnyRectangularMatrix.InternalEquals (AnyRectangularMatrix A, AnyRectangularMatrix B) inline static private
Referenced by Meta.Numerics.Matrices.AnyRectangularMatrix.Equals(), and Meta.Numerics.Matrices.AnyRectangularMatrix.operator==().
operator==()
static bool Meta.Numerics.Matrices.AnyRectangularMatrix.operator== (AnyRectangularMatrix A, AnyRectangularMatrix B) inline static
Determines whether two matrices are equal.
Parameters
A The first matrix.
B The second matrix.
Returns
True if A and B are equal, otherwise false.
References Meta.Numerics.Matrices.AnyRectangularMatrix.InternalEquals().
operator!=()
static bool Meta.Numerics.Matrices.AnyRectangularMatrix.operator!= (AnyRectangularMatrix A, AnyRectangularMatrix B) inline static
Determines whether two matrices are not equal.
Parameters
A The first matrix.
B The second matrix.
Returns
False if A and B are equal, otherwise true.
Equals() [1/2]
bool Meta.Numerics.Matrices.AnyRectangularMatrix.Equals (AnyRectangularMatrix other) inline
Determines whether the given matrix equals the current matrix.
Parameters
other The matrix to compare.
Returns
True if the other is equal to the current matrix, otherwise false.
References Meta.Numerics.Matrices.AnyRectangularMatrix.InternalEquals().
Referenced by Meta.Numerics.Matrices.AnyRectangularMatrix.Equals().
Equals() [2/2]
override bool Meta.Numerics.Matrices.AnyRectangularMatrix.Equals (object obj) inline
Determines whether the given object is an equal matrix.
Parameters
obj The object to compare.
Returns
True if obj is an equal matrix, otherwise false.
References Meta.Numerics.Matrices.AnyRectangularMatrix.Equals().
GetHashCode()
override int Meta.Numerics.Matrices.AnyRectangularMatrix.GetHashCode () inline
Not a valid operation.
Returns
Throws an InvalidOperationException.
The Object.GetHashCode method is used to provide a quick equality test when an object is used as a key in a System.Collections.Generic.Dictionary<TKey,TValue> or System.Collections.Hashtable. Since a useful hash code of a matrix would need to involve all its elements, it is not possible to make this a fast operation. Also, since matrices are not immutable, they should not be used as hash keys. (A matrix might be changed after it had already been used as a key.) For these reasons, requesting a hash code for a matrix is not supported.
Exceptions
NotSupportedException This method always throws this exception.
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Matrices/AnyRectangularMatrix.cs