Doc: IGLib EXTENDED: AForge.Imaging.Filters.Closing Class Reference
AForge.Imaging.Filters.Closing Class Reference
Closing operator from Mathematical Morphology.
Public Member Functions
Closing ()
Initializes a new instance of the Closing class.
Closing (short[,] se)
Initializes a new instance of the Closing class.
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Properties
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
Erosion errosion = new Erosion()
Dilatation dilatation = new Dilatation()
Detailed Description
Closing operator from Mathematical Morphology.
Closing morphology operator equals to dilatation followed by erosion.
Applied to binary image, the filter may be used connect or fill objects. Since dilatation is used first, it may connect/fill object areas. Then erosion restores objects. But since dilatation may connect something before, erosion may not remove after that because of the formed connection.
See documentation to Erosion and Dilatation classes for more information and list of supported pixel formats.
Sample usage:
// create filter
Closing filter = new Closing();
// apply the filter
filter.Apply(image);
Initial image:
Result image:
See also
Erosion, Dilatation, Opening
Constructor & Destructor Documentation
Closing() [1/2]
AForge.Imaging.Filters.Closing.Closing () inline
Initializes a new instance of the Closing class.
Initializes new instance of the Closing class using default structuring element for both Erosion and Dilatation classes - 3x3 structuring element with all elements equal to 1.
Closing() [2/2]
AForge.Imaging.Filters.Closing.Closing (short se[,]) inline
Initializes a new instance of the Closing class.
Parameters
se Structuring element.
See documentation to Erosion and Dilatation classes for information about structuring element constraints.
References AForge.Imaging.Filters.Closing.dilatation, and AForge.Imaging.Filters.Closing.errosion.
Member Function Documentation
Apply() [1/4]
Bitmap AForge.Imaging.Filters.Closing.Apply (Bitmap image) inline
Apply filter to an image.
Parameters
image Source image to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The method keeps the source image unchanged and returns the result of image processing filter as new image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.Apply(), AForge.Imaging.Filters.Closing.dilatation, and AForge.Imaging.Filters.Closing.errosion.
Apply() [2/4]
Bitmap AForge.Imaging.Filters.Closing.Apply (BitmapData imageData) inline
Apply filter to an image.
Parameters
imageData Source image to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The filter accepts bitmap data as input and returns the result of image processing filter as new image. The source image data are kept unchanged.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.Apply(), AForge.Imaging.Filters.Closing.dilatation, and AForge.Imaging.Filters.Closing.errosion.
Apply() [3/4]
UnmanagedImage AForge.Imaging.Filters.Closing.Apply (UnmanagedImage image) inline
Apply filter to an image in unmanaged memory.
Parameters
image Source image in unmanaged memory to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The method keeps the source image unchanged and returns the result of image processing filter as new image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.Apply(), AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace(), AForge.Imaging.Filters.Closing.dilatation, and AForge.Imaging.Filters.Closing.errosion.
Apply() [4/4]
void AForge.Imaging.Filters.Closing.Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage) inline
Apply filter to an image in unmanaged memory.
Parameters
sourceImage Source image in unmanaged memory to apply filter to.
destinationImage Destination image in unmanaged memory to put result into.
The method keeps the source image unchanged and puts result of image processing into destination image.
<note>The destination image must have the same width and height as source image. Also destination image must have pixel format, which is expected by particular filter (see FormatTranslations property for information about pixel format conversions).</note>
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
InvalidImagePropertiesException Incorrect destination pixel format.
InvalidImagePropertiesException Destination image has wrong width and/or height.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.Apply(), AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace(), AForge.Imaging.Filters.Closing.dilatation, and AForge.Imaging.Filters.Closing.errosion.
ApplyInPlace() [1/6]
void AForge.Imaging.Filters.Closing.ApplyInPlace (Bitmap image) inline
Apply filter to an image.
Parameters
image Image to apply filter to.
The method applies the filter directly to the provided source image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlaceFilter.
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace(), AForge.Imaging.Filters.Closing.dilatation, and AForge.Imaging.Filters.Closing.errosion.
Referenced by AForge.Imaging.Filters.BottomHat.ProcessFilter().
ApplyInPlace() [2/6]
void AForge.Imaging.Filters.Closing.ApplyInPlace (BitmapData imageData) inline
Apply filter to an image.
Parameters
imageData Image data to apply filter to.
The method applies the filter directly to the provided source image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlaceFilter.
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace(), AForge.Imaging.Filters.Closing.dilatation, and AForge.Imaging.Filters.Closing.errosion.
ApplyInPlace() [3/6]
void AForge.Imaging.Filters.Closing.ApplyInPlace (UnmanagedImage image) inline
Apply filter to an unmanaged image.
Parameters
image Unmanaged image to apply filter to.
The method applies the filter directly to the provided source unmanaged image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlaceFilter.
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace(), AForge.Imaging.Filters.Closing.dilatation, and AForge.Imaging.Filters.Closing.errosion.
ApplyInPlace() [4/6]
void AForge.Imaging.Filters.Closing.ApplyInPlace (Bitmap image, Rectangle rect) inline
Apply filter to an image or its part.
Parameters
image Image to apply filter to.
rect Image rectangle for processing by the filter.
The method applies the filter directly to the provided source image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlacePartialFilter.
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace(), AForge.Imaging.Filters.Closing.dilatation, and AForge.Imaging.Filters.Closing.errosion.
ApplyInPlace() [5/6]
void AForge.Imaging.Filters.Closing.ApplyInPlace (BitmapData imageData, Rectangle rect) inline
Apply filter to an image or its part.
Parameters
imageData Image data to apply filter to.
rect Image rectangle for processing by the filter.
The method applies the filter directly to the provided source image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlacePartialFilter.
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace(), AForge.Imaging.Filters.Closing.dilatation, and AForge.Imaging.Filters.Closing.errosion.
ApplyInPlace() [6/6]
void AForge.Imaging.Filters.Closing.ApplyInPlace (UnmanagedImage image, Rectangle rect) inline
Apply filter to an unmanaged image or its part.
Parameters
image Unmanaged image to apply filter to.
rect Image rectangle for processing by the filter.
The method applies the filter directly to the provided source image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlacePartialFilter.
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace(), AForge.Imaging.Filters.Closing.dilatation, and AForge.Imaging.Filters.Closing.errosion.
Member Data Documentation
errosion
Erosion AForge.Imaging.Filters.Closing.errosion = new Erosion() private
Referenced by AForge.Imaging.Filters.Closing.Apply(), AForge.Imaging.Filters.Closing.ApplyInPlace(), and AForge.Imaging.Filters.Closing.Closing().
dilatation
Dilatation AForge.Imaging.Filters.Closing.dilatation = new Dilatation() private
Referenced by AForge.Imaging.Filters.Closing.Apply(), AForge.Imaging.Filters.Closing.ApplyInPlace(), and AForge.Imaging.Filters.Closing.Closing().
Property Documentation
FormatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.Closing.FormatTranslations get
Format translations dictionary.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Morphology/Closing.cs