Doc: IGLib EXTENDED: AForge.Imaging.Filters.BradleyLocalThresholding Class Reference
AForge.Imaging.Filters.BradleyLocalThresholding Class Reference
Adaptive thresholding using the internal image.
Public Member Functions
BradleyLocalThresholding ()
Initializes a new instance of the BradleyLocalThresholding class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlaceFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image)
Process the filter on the specified image.
Properties
int WindowSize [get, set]
Window size to calculate average value of pixels for.
float PixelBrightnessDifferenceLimit [get, set]
Brightness difference limit between processing pixel and average value across neighbors.
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.BaseInPlaceFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
int windowSize = 41
float pixelBrightnessDifferenceLimit = 0.15f
Detailed Description
Adaptive thresholding using the internal image.
The image processing routine implements local thresholding technique described by Derek Bradley and Gerhard Roth in the "Adaptive Thresholding Using the Integral Image" paper.
The brief idea of the algorithm is that every image's pixel is set to black if its brightness is t percent lower (see PixelBrightnessDifferenceLimit) than the average brightness of surrounding pixels in the window of the specified size (see WindowSize), othwerwise it is set to white.
Sample usage:
// create the filter
BradleyLocalThresholding filter = new BradleyLocalThresholding();
// apply the filter
filter.ApplyInPlace(image);
Initial image:
Result image:
Constructor & Destructor Documentation
BradleyLocalThresholding()
AForge.Imaging.Filters.BradleyLocalThresholding.BradleyLocalThresholding () inline
Initializes a new instance of the BradleyLocalThresholding class.
References AForge.Imaging.Filters.BradleyLocalThresholding.formatTranslations.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.BradleyLocalThresholding.ProcessFilter (UnmanagedImage image) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
Implements AForge.Imaging.Filters.BaseInPlaceFilter.
References AForge.Imaging.IntegralImage.FromBitmap(), AForge.Imaging.IntegralImage.GetRectangleMeanUnsafe(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.Filters.BradleyLocalThresholding.pixelBrightnessDifferenceLimit, AForge.Imaging.UnmanagedImage.Stride, AForge.Imaging.UnmanagedImage.Width, and AForge.Imaging.Filters.BradleyLocalThresholding.windowSize.
Member Data Documentation
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.BradleyLocalThresholding.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.BradleyLocalThresholding.BradleyLocalThresholding().
windowSize
int AForge.Imaging.Filters.BradleyLocalThresholding.windowSize = 41 private
Referenced by AForge.Imaging.Filters.BradleyLocalThresholding.ProcessFilter().
pixelBrightnessDifferenceLimit
float AForge.Imaging.Filters.BradleyLocalThresholding.pixelBrightnessDifferenceLimit = 0.15f private
Referenced by AForge.Imaging.Filters.BradleyLocalThresholding.ProcessFilter().
Property Documentation
WindowSize
int AForge.Imaging.Filters.BradleyLocalThresholding.WindowSize get set
Window size to calculate average value of pixels for.
The property specifies window size around processing pixel, which determines number of neighbor pixels to use for calculating their average brightness.
Default value is set to 41.
<note>The value should be odd.</note>
PixelBrightnessDifferenceLimit
float AForge.Imaging.Filters.BradleyLocalThresholding.PixelBrightnessDifferenceLimit get set
Brightness difference limit between processing pixel and average value across neighbors.
The property specifies what is the allowed difference percent between processing pixel and average brightness of neighbor pixels in order to be set white. If the value of the current pixel is t percent (this property value) lower than the average then it is set to black, otherwise it is set to white.
Default value is set to 0.15.
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.BradleyLocalThresholding.FormatTranslations get
Format translations dictionary.
See IFilterInformation.FormatTranslations for more information.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Adaptive Binarization/BradleyLocalThresholding.cs