Doc: IGLib EXTENDED: NUnit.Engine.ISettings Interface Reference
NUnit.Engine.ISettings Interface Reference
The ISettings interface is used to access all user settings and options.
Public Member Functions
object GetSetting (string settingName)
Load a setting from the storage.
T GetSetting< T > (string settingName, T defaultValue)
Load a setting from the storage or return a default value
void RemoveSetting (string settingName)
Remove a setting from the storage
void RemoveGroup (string groupName)
Remove an entire group of settings from the storage
void SaveSetting (string settingName, object settingValue)
Save a setting in the storage
Events
SettingsEventHandler Changed
Occurs when the settings are changed.
Detailed Description
The ISettings interface is used to access all user settings and options.
Member Function Documentation
GetSetting()
object NUnit.Engine.ISettings.GetSetting (string settingName)
Load a setting from the storage.
Parameters
settingName Name of the setting to load
Returns
Value of the setting or null
Implemented in NUnit.Engine.Internal.SettingsGroup.
Referenced by NUnit.Engine.Services.RecentFilesService.AddEntriesForPrefix(), and NUnit.Engine.Services.DomainManager.StartService().
GetSetting< T >()
T NUnit.Engine.ISettings.GetSetting< T > (string settingName, T defaultValue)
Load a setting from the storage or return a default value
Parameters
settingName Name of the setting to load
defaultValue Value to return if the setting is missing
Returns
Value of the setting or the default value
Implemented in NUnit.Engine.Internal.SettingsGroup.
RemoveSetting()
void NUnit.Engine.ISettings.RemoveSetting (string settingName)
Remove a setting from the storage
Parameters
settingName Name of the setting to remove
Implemented in NUnit.Engine.Internal.SettingsGroup.
Referenced by NUnit.Engine.Services.RecentFilesService.SaveEntriesToSettings().
RemoveGroup()
void NUnit.Engine.ISettings.RemoveGroup (string groupName)
Remove an entire group of settings from the storage
Parameters
groupName Name of the group to remove
Implemented in NUnit.Engine.Internal.SettingsGroup.
Referenced by NUnit.Engine.Services.RecentFilesService.SaveEntriesToSettings().
SaveSetting()
void NUnit.Engine.ISettings.SaveSetting (string settingName, object settingValue)
Save a setting in the storage
Parameters
settingName Name of the setting to save
settingValue Value to be saved
Implemented in NUnit.Engine.Internal.SettingsGroup.
Referenced by NUnit.Engine.Services.RecentFilesService.SaveEntriesToSettings().
Event Documentation
Changed
SettingsEventHandler NUnit.Engine.ISettings.Changed
Occurs when the settings are changed.
The documentation for this interface was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.api/ISettings.cs