Doc: IGLib EXTENDED: NUnit.Engine.Internal.ServerUtilities Class Reference
NUnit.Engine.Internal.ServerUtilities Class Reference
A collection of utility methods used to create, retrieve and release TcpChannels.
Static Public Member Functions
static TcpChannel GetTcpChannel ()
Get a default channel. If one does not exist, then one is created and registered.
static TcpChannel GetTcpChannel (string name, int port)
Get a channel by name, casting it to a TcpChannel. Otherwise, create, register and return a TcpChannel with that name, on the port provided as the second argument.
static TcpChannel GetTcpChannel (string name, int port, int limit)
Get a channel by name, casting it to a TcpChannel. Otherwise, create, register and return a TcpChannel with that name, on the port provided as the second argument.
static void SafeReleaseChannel (IChannel channel)
Unregisters the IChannel from the ChannelServices registry.
Static Private Member Functions
static TcpChannel CreateTcpChannel (string name, int port, int limit)
Create a TcpChannel with a given name on a given port.
Static Private Attributes
static Logger log = InternalTrace.GetLogger(typeof(ServerUtilities))
Detailed Description
A collection of utility methods used to create, retrieve and release TcpChannels.
Member Function Documentation
CreateTcpChannel()
static TcpChannel NUnit.Engine.Internal.ServerUtilities.CreateTcpChannel (string name, int port, int limit) inline static private
Create a TcpChannel with a given name on a given port.
Parameters
name The name of the channel to create.
port The port number of the channel to create.
limit The rate limit of the channel to create.
Returns
A TcpChannel configured with the given name and port.
Referenced by NUnit.Engine.Internal.ServerUtilities.GetTcpChannel().
GetTcpChannel() [1/3]
static TcpChannel NUnit.Engine.Internal.ServerUtilities.GetTcpChannel () inline static
Get a default channel. If one does not exist, then one is created and registered.
Returns
The specified TcpChannel or null if it cannot be found and created
Referenced by NUnit.Engine.Internal.Tests.ServerUtilityTests.CanGetTcpChannelOnSpecifiedPort(), NUnit.Engine.Internal.Tests.ServerUtilityTests.CanGetTcpChannelOnUnspecifiedPort(), NUnit.Engine.Internal.ServerUtilities.GetTcpChannel(), NUnit.Agent.NUnitTestAgent.Main(), and NUnit.Engine.Internal.ServerBase.Start().
GetTcpChannel() [2/3]
static TcpChannel NUnit.Engine.Internal.ServerUtilities.GetTcpChannel (string name, int port) inline static
Get a channel by name, casting it to a TcpChannel. Otherwise, create, register and return a TcpChannel with that name, on the port provided as the second argument.
Parameters
name The name of the channel
port The port to use if the channel must be created
Returns
The specified TcpChannel or null if it cannot be found and created
References NUnit.Engine.Internal.ServerUtilities.GetTcpChannel().
GetTcpChannel() [3/3]
static TcpChannel NUnit.Engine.Internal.ServerUtilities.GetTcpChannel (string name, int port, int limit) inline static
Get a channel by name, casting it to a TcpChannel. Otherwise, create, register and return a TcpChannel with that name, on the port provided as the second argument.
Parameters
name The name of the channel
port The port to use if the channel must be created
limit The client connection limit or negative for the default
Returns
The specified TcpChannel or null if it cannot be found and created
References NUnit.Engine.Internal.ServerUtilities.CreateTcpChannel(), and NUnit.Engine.Internal.ServerUtilities.log.
SafeReleaseChannel()
static void NUnit.Engine.Internal.ServerUtilities.SafeReleaseChannel (IChannel channel) inline static
Unregisters the IChannel from the ChannelServices registry.
Parameters
channel The channel to unregister.
Referenced by NUnit.Engine.Internal.Tests.ServerUtilityTests.ReleaseChannels().
Member Data Documentation
log
Logger NUnit.Engine.Internal.ServerUtilities.log = InternalTrace.GetLogger(typeof(ServerUtilities)) static private
Referenced by NUnit.Engine.Internal.ServerUtilities.GetTcpChannel().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Internal/ServerUtilities.cs