Doc: IGLib EXTENDED: AForge.Imaging.Filters.BaseUsingCopyPartialFilter Class Reference
AForge.Imaging.Filters.BaseUsingCopyPartialFilter Class Reference abstract
Base class for filters, which require source image backup to make them applicable to source image (or its part) directly.
Public Member Functions
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
abstract unsafe void ProcessFilter (UnmanagedImage sourceData, UnmanagedImage destinationData, Rectangle rect)
Process the filter on the specified image.
Properties
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Member Functions
void CheckSourceFormat (PixelFormat pixelFormat)
Detailed Description
Base class for filters, which require source image backup to make them applicable to source image (or its part) directly.
The base class is used for filters, which can not do direct manipulations with source image. To make effect of in-place filtering, these filters create a background copy of the original image (done by this base class) and then do manipulations with it putting result back to the original source image.
<note>The background copy of the source image is created only in the case of in-place filtering. Otherwise background copy is not created - source image is processed and result is put to destination image.</note>
The base class is for those filters, which support as filtering entire image, as partial filtering of specified rectangle only.
Member Function Documentation
Apply() [1/4]
Bitmap AForge.Imaging.Filters.BaseUsingCopyPartialFilter.Apply (Bitmap image) inline
Apply filter to an image.
Parameters
image Source image to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The method keeps the source image unchanged and returns the result of image processing filter as new image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.Filters.Closing.Apply(), AForge.Imaging.Filters.Opening.Apply(), AForge.Imaging.Filters.CannyEdgeDetector.ProcessFilter(), AForge.Vision.Motion.TwoFramesDifferenceDetector.ProcessFrame(), AForge.Vision.Motion.CustomFrameDifferenceDetector.ProcessFrame(), and AForge.Vision.Motion.SimpleBackgroundModelingDetector.ProcessFrame().
Apply() [2/4]
Bitmap AForge.Imaging.Filters.BaseUsingCopyPartialFilter.Apply (BitmapData imageData) inline
Apply filter to an image.
Parameters
imageData Source image to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The filter accepts bitmap data as input and returns the result of image processing filter as new image. The source image data are kept unchanged.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.CheckSourceFormat(), AForge.Imaging.Image.CreateGrayscaleImage(), AForge.Imaging.Filters.BaseUsingCopyPartialFilter.FormatTranslations, AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ProcessFilter(), and AForge.Math.Geometry.Rectangle.
Apply() [3/4]
UnmanagedImage AForge.Imaging.Filters.BaseUsingCopyPartialFilter.Apply (UnmanagedImage image) inline
Apply filter to an image in unmanaged memory.
Parameters
image Source image in unmanaged memory to apply filter to.
Returns
Returns filter's result obtained by applying the filter to the source image.
The method keeps the source image unchanged and returns the result of image processing filter as new image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.CheckSourceFormat(), AForge.Imaging.UnmanagedImage.Create(), AForge.Imaging.Filters.BaseUsingCopyPartialFilter.FormatTranslations, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ProcessFilter(), AForge.Math.Geometry.Rectangle, and AForge.Imaging.UnmanagedImage.Width.
Apply() [4/4]
void AForge.Imaging.Filters.BaseUsingCopyPartialFilter.Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage) inline
Apply filter to an image in unmanaged memory.
Parameters
sourceImage Source image in unmanaged memory to apply filter to.
destinationImage Destination image in unmanaged memory to put result into.
The method keeps the source image unchanged and puts result of image processing into destination image.
<note>The destination image must have the same width and height as source image. Also destination image must have pixel format, which is expected by particular filter (see FormatTranslations property for information about pixel format conversions).</note>
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
InvalidImagePropertiesException Incorrect destination pixel format.
InvalidImagePropertiesException Destination image has wrong width and/or height.
Implements AForge.Imaging.Filters.IFilter.
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.CheckSourceFormat(), AForge.Imaging.Filters.BaseUsingCopyPartialFilter.FormatTranslations, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ProcessFilter(), AForge.Math.Geometry.Rectangle, and AForge.Imaging.UnmanagedImage.Width.
ApplyInPlace() [1/6]
void AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace (Bitmap image) inline
Apply filter to an image.
Parameters
image Image to apply filter to.
The method applies the filter directly to the provided source image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlaceFilter.
References AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.Filters.Closing.Apply(), AForge.Imaging.Filters.Opening.Apply(), AForge.Imaging.Filters.Closing.ApplyInPlace(), AForge.Imaging.Filters.Opening.ApplyInPlace(), AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace(), and AForge.Imaging.Filters.FlatFieldCorrection.ProcessFilter().
ApplyInPlace() [2/6]
void AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace (BitmapData imageData) inline
Apply filter to an image.
Parameters
imageData Image data to apply filter to.
The method applies the filter directly to the provided source image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlaceFilter.
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace(), and AForge.Math.Geometry.Rectangle.
ApplyInPlace() [3/6]
void AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace (UnmanagedImage image) inline
Apply filter to an unmanaged image.
Parameters
image Unmanaged image to apply filter to.
The method applies the filter directly to the provided source unmanaged image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlaceFilter.
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace(), AForge.Imaging.UnmanagedImage.Height, AForge.Math.Geometry.Rectangle, and AForge.Imaging.UnmanagedImage.Width.
ApplyInPlace() [4/6]
void AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace (Bitmap image, Rectangle rect) inline
Apply filter to an image or its part.
Parameters
image Image to apply filter to.
rect Image rectangle for processing by the filter.
The method applies the filter directly to the provided source image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlacePartialFilter.
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace(), and AForge.Math.Geometry.Rectangle.
ApplyInPlace() [5/6]
void AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace (BitmapData imageData, Rectangle rect) inline
Apply filter to an image or its part.
Parameters
imageData Image data to apply filter to.
rect Image rectangle for processing by the filter.
The method applies the filter directly to the provided source image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlacePartialFilter.
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace().
ApplyInPlace() [6/6]
void AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace (UnmanagedImage image, Rectangle rect) inline
Apply filter to an unmanaged image or its part.
Parameters
image Unmanaged image to apply filter to.
rect Image rectangle for processing by the filter.
The method applies the filter directly to the provided source image.
Exceptions
UnsupportedImageFormatException Unsupported pixel format of the source image.
Implements AForge.Imaging.Filters.IInPlacePartialFilter.
References AForge.Imaging.MemoryManager.Alloc(), AForge.Imaging.Filters.BaseUsingCopyPartialFilter.CheckSourceFormat(), AForge.SystemTools.CopyUnmanagedMemory(), AForge.Imaging.MemoryManager.Free(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ProcessFilter(), AForge.Math.Geometry.Rectangle, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
ProcessFilter()
abstract unsafe void AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ProcessFilter (UnmanagedImage sourceData, UnmanagedImage destinationData, Rectangle rect) protected pure virtual
Process the filter on the specified image.
Parameters
sourceData Source image data.
destinationData Destination image data.
rect Image rectangle for processing by the filter.
Implemented in AForge.Imaging.Filters.HitAndMiss, AForge.Imaging.Filters.Erosion, AForge.Imaging.Filters.Dilatation, AForge.Imaging.Filters.BinaryDilatation3x3, AForge.Imaging.Filters.BinaryErosion3x3, AForge.Imaging.Filters.Dilatation3x3, AForge.Imaging.Filters.Erosion3x3, AForge.Imaging.Filters.BilateralSmoothing, AForge.Imaging.Filters.Convolution, AForge.Imaging.Filters.CannyEdgeDetector, AForge.Imaging.Filters.AdaptiveSmoothing, AForge.Imaging.Filters.SimpleSkeletonization, AForge.Imaging.Filters.SobelEdgeDetector, AForge.Imaging.Filters.ConservativeSmoothing, AForge.Imaging.Filters.Jitter, AForge.Imaging.Filters.OilPainting, AForge.Imaging.Filters.Median, AForge.Imaging.Filters.HomogenityEdgeDetector, and AForge.Imaging.Filters.DifferenceEdgeDetector.
Referenced by AForge.Imaging.Filters.BaseUsingCopyPartialFilter.Apply(), and AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace().
CheckSourceFormat()
void AForge.Imaging.Filters.BaseUsingCopyPartialFilter.CheckSourceFormat (PixelFormat pixelFormat) inline private
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.FormatTranslations.
Referenced by AForge.Imaging.Filters.BaseUsingCopyPartialFilter.Apply(), and AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace().
Property Documentation
FormatTranslations
abstract Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.BaseUsingCopyPartialFilter.FormatTranslations get
Format translations dictionary.
The dictionary defines, which pixel formats are supported for source images and which pixel format will be used for resulting image.
See IFilterInformation.FormatTranslations for more information.
Referenced by AForge.Imaging.Filters.BaseUsingCopyPartialFilter.Apply(), and AForge.Imaging.Filters.BaseUsingCopyPartialFilter.CheckSourceFormat().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Base classes/BaseUsingCopyPartialFilter.cs