Doc: IGLib EXTENDED: IG.Forms.ReporterConfigurationForm Class Reference
IG.Forms.ReporterConfigurationForm Class Reference
Reporter configuration.
Public Member Functions
ReporterConfigurationForm ()
ReporterConfigurationForm (ReporterForms rf)
void HideForm ()
void CloseForm ()
Closes the consform by properly (i.e. thread-safe) calling the Close() and Dispose().
void ShowThread ()
Shows a fading message in a new thread.
void ShowThread (string title)
Shows a fading message in a new thread, with message text equal to mshtext and without a title;.
Public Attributes
string Title =""
Properties
ReporterForms reporter [get, private set]
bool IsBackground [get, set]
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void FormThreadFunc ()
Shows the window in a separate thread.
void ConsoleForm_Load (object sender, System.EventArgs args)
void ConsoleForm_Dispose (object sender, System.EventArgs e)
void CloseBtn_Click (object sender, EventArgs e)
void HideBtn_Click (object sender, EventArgs e)
void ReportConfig_MouseMove (object sender, MouseEventArgs e)
void ReportConfig_MouseDown (object sender, MouseEventArgs e)
void ReportConfig_MouseClick (object sender, MouseEventArgs e)
Enables closing the consform with right-clicking.
void SetCommonEvents (Control f)
void BtnCancel_Click (object sender, EventArgs e)
void btnLaunch_Click (object sender, EventArgs e)
void rbConsoleFormOn_CheckedChanged (object sender, EventArgs e)
void rbMessageBoxOn_CheckedChanged (object sender, EventArgs e)
void rbFadingMessageOn_CheckedChanged (object sender, EventArgs e)
void txtFadingShowtime_TextChanged (object sender, EventArgs e)
void txtFadingPortion_TextChanged (object sender, EventArgs e)
void txtFadingBG_BackColorChanged (object sender, EventArgs e)
void btnFadeBG_Click (object sender, EventArgs e)
void txtFadeBGFinal_BackColorChanged (object sender, EventArgs e)
void btnFadeBGFinal_Click (object sender, EventArgs e)
void rbConsoleOn_CheckedChanged (object sender, EventArgs e)
Private Attributes
ReporterForms _reporter = null
bool bgthread = false
GroupBox grpFadeMessage
Panel pnlFadingMessageSwitch
RadioButton rbFadeMessageOn
RadioButton rbFadeMessageOff
Label lblFadeBGFade
Button btnFadeBGFinal
Button btnFadeBG
Label lblFadingBG
TextBox txtFadeBGFinal
Label lblFadingPortion
TextBox txtFadeBG
Label lblFadingShowtime
TextBox txtFadePortion
TextBox txtFadeShowtime
GroupBox grpConsole
Panel pnlConsoleSwitch
RadioButton rbConsoleOn
RadioButton rbConsoleOff
GroupBox grpConsoleForm
Panel pnlConsoleFormSwitch
RadioButton rbConsoleFormOn
RadioButton rbConsoleFormOff
GroupBox grpMessageBox
Panel pnlMessageBoxSwitch
RadioButton rbMessageBoxOn
RadioButton rbMessageBoxOff
GroupBox grpTest
GroupBox grpOutputLevel
RadioButton rbOutVerbose
RadioButton rbOutInfo
RadioButton rbOutWarning
RadioButton rbOutError
GroupBox grpReportType
RadioButton rbInfo
RadioButton rbWarning
RadioButton rbError
Button btnLaunch
GroupBox grpMultipleReports
CheckBox chkMultiple
TextBox txtNumLaunches
TextBox txtDelay
Label lblMultipleNum
Label lblDelay
Label label1
Label lblMessage
TextBox txtExMessage
Label lblLocation
TextBox txtMessage
TextBox txtLocation
Label lblDescription
Label lblTitle
Panel PnlStatus
Button CancelBtn
Label StatusLbl
CheckBox chkThrowException
Thread formthread = null
int m_PrevX
int m_PrevY
Detailed Description
Reporter configuration.
Constructor & Destructor Documentation
ReporterConfigurationForm() [1/2]
IG.Forms.ReporterConfigurationForm.ReporterConfigurationForm () inline
ReporterConfigurationForm() [2/2]
IG.Forms.ReporterConfigurationForm.ReporterConfigurationForm (ReporterForms rf) inline
References IG.Forms.ReporterConfigurationForm.InitializeComponent(), and IG.Forms.ReporterConfigurationForm.reporter.
Member Function Documentation
InitializeComponent()
void IG.Forms.ReporterConfigurationForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by IG.Forms.ReporterConfigurationForm.ReporterConfigurationForm().
FormThreadFunc()
void IG.Forms.ReporterConfigurationForm.FormThreadFunc () inline private
Shows the window in a separate thread.
References IG.Forms.ReporterForms.Global, and IG.Lib.ReporterBase.ReportError().
Referenced by IG.Forms.ReporterConfigurationForm.ShowThread().
ConsoleForm_Load()
void IG.Forms.ReporterConfigurationForm.ConsoleForm_Load (object sender, System.EventArgs args) inline private
References IG.Forms.ControlDelegate(), IG.Forms.ReporterForms.FadeMessageBackColor, IG.Forms.ReporterForms.FadeMessageBackColorFinal, IG.Forms.ReporterForms.FadeMessageFadingTimePortion, IG.Forms.ReporterForms.FadeMessageShowtime, IG.Forms.ReporterForms.Global, IG.Forms.ReporterConfigurationForm.rbConsoleFormOff, IG.Forms.ReporterConfigurationForm.rbConsoleFormOn, IG.Forms.ReporterConfigurationForm.rbConsoleOff, IG.Forms.ReporterConfigurationForm.rbConsoleOn, IG.Forms.ReporterConfigurationForm.rbFadeMessageOff, IG.Forms.ReporterConfigurationForm.rbFadeMessageOn, IG.Forms.ReporterConfigurationForm.rbMessageBoxOff, IG.Forms.ReporterConfigurationForm.rbMessageBoxOn, IG.Forms.UtilForms.RecursiveControlDelegate(), IG.Forms.ReporterConfigurationForm.reporter, IG.Lib.ReporterBase.ReportError(), IG.Forms.ReporterConfigurationForm.SetCommonEvents(), IG.Forms.ReporterConfigurationForm.txtFadeBG, IG.Forms.ReporterConfigurationForm.txtFadeBGFinal, IG.Forms.ReporterConfigurationForm.txtFadePortion, IG.Forms.ReporterConfigurationForm.txtFadeShowtime, IG.Forms.ReporterForms.UseConsole, IG.Forms.ReporterForms.UseConsoleForm, IG.Forms.ReporterForms.UseFadeMessage, and IG.Forms.ReporterForms.UseMessageBox.
ConsoleForm_Dispose()
void IG.Forms.ReporterConfigurationForm.ConsoleForm_Dispose (object sender, System.EventArgs e) inline private
References IG.Forms.ReporterForms.Global, and IG.Lib.ReporterBase.ReportError().
CloseBtn_Click()
void IG.Forms.ReporterConfigurationForm.CloseBtn_Click (object sender, EventArgs e) inline private
References IG.Forms.ReporterConfigurationForm.CloseForm(), IG.Forms.ReporterForms.Global, and IG.Lib.ReporterBase.ReportError().
HideBtn_Click()
void IG.Forms.ReporterConfigurationForm.HideBtn_Click (object sender, EventArgs e) inline private
References IG.Forms.ReporterForms.Global, IG.Forms.ReporterConfigurationForm.HideForm(), and IG.Lib.ReporterBase.ReportError().
HideForm()
void IG.Forms.ReporterConfigurationForm.HideForm () inline
References IG.Forms.ReporterForms.Global, and IG.Lib.ReporterBase.ReportError().
Referenced by IG.Forms.ReporterConfigurationForm.HideBtn_Click().
CloseForm()
void IG.Forms.ReporterConfigurationForm.CloseForm () inline
Closes the consform by properly (i.e. thread-safe) calling the Close() and Dispose().
References IG.Forms.ReporterForms.Global, IG.Lib.ReporterBase.ReportError(), and IG.Forms.VoidDelegate().
Referenced by IG.Forms.ReporterConfigurationForm.BtnCancel_Click(), IG.Forms.ReporterConfigurationForm.CloseBtn_Click(), and IG.Forms.ReporterConfigurationForm.ReportConfig_MouseClick().
ShowThread() [1/2]
void IG.Forms.ReporterConfigurationForm.ShowThread () inline
Shows a fading message in a new thread.
References IG.Forms.ReporterConfigurationForm.bgthread, IG.Forms.ReporterConfigurationForm.formthread, and IG.Forms.ReporterConfigurationForm.FormThreadFunc().
Referenced by IG.Forms.ReporterConfigurationForm.ShowThread().
ShowThread() [2/2]
void IG.Forms.ReporterConfigurationForm.ShowThread (string title) inline
Shows a fading message in a new thread, with message text equal to mshtext and without a title;.
References IG.Forms.ReporterConfigurationForm.ShowThread(), and IG.Forms.ReporterConfigurationForm.Title.
ReportConfig_MouseMove()
void IG.Forms.ReporterConfigurationForm.ReportConfig_MouseMove (object sender, MouseEventArgs e) inline private
References IG.Lib.Left, IG.Forms.ReporterConfigurationForm.m_PrevX, IG.Forms.ReporterConfigurationForm.m_PrevY, and IG.Lib.Top.
Referenced by IG.Forms.ReporterConfigurationForm.SetCommonEvents().
ReportConfig_MouseDown()
void IG.Forms.ReporterConfigurationForm.ReportConfig_MouseDown (object sender, MouseEventArgs e) inline private
References IG.Forms.ReporterConfigurationForm.m_PrevX, and IG.Forms.ReporterConfigurationForm.m_PrevY.
Referenced by IG.Forms.ReporterConfigurationForm.SetCommonEvents().
ReportConfig_MouseClick()
void IG.Forms.ReporterConfigurationForm.ReportConfig_MouseClick (object sender, MouseEventArgs e) inline private
Enables closing the consform with right-clicking.
References IG.Forms.ReporterConfigurationForm.CloseForm().
Referenced by IG.Forms.ReporterConfigurationForm.SetCommonEvents().
SetCommonEvents()
void IG.Forms.ReporterConfigurationForm.SetCommonEvents (Control f) inline private
References IG.Forms.ReporterConfigurationForm.ReportConfig_MouseClick(), IG.Forms.ReporterConfigurationForm.ReportConfig_MouseDown(), and IG.Forms.ReporterConfigurationForm.ReportConfig_MouseMove().
Referenced by IG.Forms.ReporterConfigurationForm.ConsoleForm_Load().
BtnCancel_Click()
void IG.Forms.ReporterConfigurationForm.BtnCancel_Click (object sender, EventArgs e) inline private
References IG.Forms.ReporterConfigurationForm.CloseForm().
btnLaunch_Click()
void IG.Forms.ReporterConfigurationForm.btnLaunch_Click (object sender, EventArgs e) inline private
References IG.Forms.ReporterConfigurationForm.chkMultiple, IG.Forms.ReporterConfigurationForm.chkThrowException, IG.Forms.ReporterForms.Global, IG.Forms.ReporterConfigurationForm.rbError, IG.Forms.ReporterConfigurationForm.rbInfo, IG.Forms.ReporterConfigurationForm.rbOutError, IG.Forms.ReporterConfigurationForm.rbOutInfo, IG.Forms.ReporterConfigurationForm.rbOutVerbose, IG.Forms.ReporterConfigurationForm.rbOutWarning, IG.Forms.ReporterConfigurationForm.rbWarning, IG.Forms.ReporterForms.Report(), IG.Forms.ReporterConfigurationForm.reporter, IG.Lib.ReporterBase.ReportError(), IG.Lib.ReporterBase.ReportingLevel, IG.Lib.ReporterBase.ThrowTestException, IG.Forms.ReporterConfigurationForm.txtDelay, IG.Forms.ReporterConfigurationForm.txtExMessage, IG.Forms.ReporterConfigurationForm.txtLocation, IG.Forms.ReporterConfigurationForm.txtMessage, and IG.Forms.ReporterConfigurationForm.txtNumLaunches.
rbConsoleFormOn_CheckedChanged()
void IG.Forms.ReporterConfigurationForm.rbConsoleFormOn_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.ReporterForms.Global, IG.Forms.ReporterConfigurationForm.rbConsoleFormOn, IG.Forms.ReporterConfigurationForm.reporter, IG.Lib.ReporterBase.ReportError(), and IG.Forms.ReporterForms.UseConsoleForm.
rbMessageBoxOn_CheckedChanged()
void IG.Forms.ReporterConfigurationForm.rbMessageBoxOn_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.ReporterForms.Global, IG.Forms.ReporterConfigurationForm.rbMessageBoxOn, IG.Forms.ReporterConfigurationForm.reporter, IG.Lib.ReporterBase.ReportError(), and IG.Forms.ReporterForms.UseMessageBox.
rbFadingMessageOn_CheckedChanged()
void IG.Forms.ReporterConfigurationForm.rbFadingMessageOn_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.ReporterForms.Global, IG.Forms.ReporterConfigurationForm.rbFadeMessageOn, IG.Forms.ReporterConfigurationForm.reporter, IG.Lib.ReporterBase.ReportError(), and IG.Forms.ReporterForms.UseFadeMessage.
txtFadingShowtime_TextChanged()
void IG.Forms.ReporterConfigurationForm.txtFadingShowtime_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.ReporterForms.FadeMessageShowtime, IG.Forms.ReporterForms.Global, IG.Forms.ReporterConfigurationForm.reporter, IG.Lib.ReporterBase.ReportError(), and IG.Forms.ReporterConfigurationForm.txtFadeShowtime.
txtFadingPortion_TextChanged()
void IG.Forms.ReporterConfigurationForm.txtFadingPortion_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.ReporterForms.FadeMessageFadingTimePortion, IG.Forms.ReporterForms.Global, IG.Forms.ReporterConfigurationForm.reporter, IG.Lib.ReporterBase.ReportError(), and IG.Forms.ReporterConfigurationForm.txtFadePortion.
txtFadingBG_BackColorChanged()
void IG.Forms.ReporterConfigurationForm.txtFadingBG_BackColorChanged (object sender, EventArgs e) inline private
References IG.Forms.ReporterForms.FadeMessageBackColor, IG.Forms.ReporterForms.Global, IG.Forms.ReporterConfigurationForm.reporter, IG.Lib.ReporterBase.ReportError(), and IG.Forms.ReporterConfigurationForm.txtFadeBG.
btnFadeBG_Click()
void IG.Forms.ReporterConfigurationForm.btnFadeBG_Click (object sender, EventArgs e) inline private
References IG.Forms.ReporterForms.Global, IG.Lib.ReporterBase.ReportError(), and IG.Forms.ReporterConfigurationForm.txtFadeBG.
txtFadeBGFinal_BackColorChanged()
void IG.Forms.ReporterConfigurationForm.txtFadeBGFinal_BackColorChanged (object sender, EventArgs e) inline private
References IG.Forms.ReporterForms.FadeMessageBackColorFinal, IG.Forms.ReporterForms.Global, IG.Forms.ReporterConfigurationForm.reporter, IG.Lib.ReporterBase.ReportError(), and IG.Forms.ReporterConfigurationForm.txtFadeBGFinal.
btnFadeBGFinal_Click()
void IG.Forms.ReporterConfigurationForm.btnFadeBGFinal_Click (object sender, EventArgs e) inline private
References IG.Forms.ReporterForms.Global, IG.Lib.ReporterBase.ReportError(), and IG.Forms.ReporterConfigurationForm.txtFadeBGFinal.
rbConsoleOn_CheckedChanged()
void IG.Forms.ReporterConfigurationForm.rbConsoleOn_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.ReporterForms.Global, IG.Forms.ReporterConfigurationForm.rbConsoleOn, IG.Forms.ReporterConfigurationForm.reporter, IG.Lib.ReporterBase.ReportError(), and IG.Forms.ReporterForms.UseConsole.
Member Data Documentation
_reporter
ReporterForms IG.Forms.ReporterConfigurationForm._reporter = null private
bgthread
bool IG.Forms.ReporterConfigurationForm.bgthread = false private
Referenced by IG.Forms.ReporterConfigurationForm.ShowThread().
grpFadeMessage
GroupBox IG.Forms.ReporterConfigurationForm.grpFadeMessage private
pnlFadingMessageSwitch
Panel IG.Forms.ReporterConfigurationForm.pnlFadingMessageSwitch private
rbFadeMessageOn
RadioButton IG.Forms.ReporterConfigurationForm.rbFadeMessageOn private
Referenced by IG.Forms.ReporterConfigurationForm.ConsoleForm_Load(), and IG.Forms.ReporterConfigurationForm.rbFadingMessageOn_CheckedChanged().
rbFadeMessageOff
RadioButton IG.Forms.ReporterConfigurationForm.rbFadeMessageOff private
Referenced by IG.Forms.ReporterConfigurationForm.ConsoleForm_Load().
lblFadeBGFade
Label IG.Forms.ReporterConfigurationForm.lblFadeBGFade private
btnFadeBGFinal
Button IG.Forms.ReporterConfigurationForm.btnFadeBGFinal private
btnFadeBG
Button IG.Forms.ReporterConfigurationForm.btnFadeBG private
lblFadingBG
Label IG.Forms.ReporterConfigurationForm.lblFadingBG private
txtFadeBGFinal
TextBox IG.Forms.ReporterConfigurationForm.txtFadeBGFinal private
Referenced by IG.Forms.ReporterConfigurationForm.btnFadeBGFinal_Click(), IG.Forms.ReporterConfigurationForm.ConsoleForm_Load(), and IG.Forms.ReporterConfigurationForm.txtFadeBGFinal_BackColorChanged().
lblFadingPortion
Label IG.Forms.ReporterConfigurationForm.lblFadingPortion private
txtFadeBG
TextBox IG.Forms.ReporterConfigurationForm.txtFadeBG private
Referenced by IG.Forms.ReporterConfigurationForm.btnFadeBG_Click(), IG.Forms.ReporterConfigurationForm.ConsoleForm_Load(), and IG.Forms.ReporterConfigurationForm.txtFadingBG_BackColorChanged().
lblFadingShowtime
Label IG.Forms.ReporterConfigurationForm.lblFadingShowtime private
txtFadePortion
TextBox IG.Forms.ReporterConfigurationForm.txtFadePortion private
Referenced by IG.Forms.ReporterConfigurationForm.ConsoleForm_Load(), and IG.Forms.ReporterConfigurationForm.txtFadingPortion_TextChanged().
txtFadeShowtime
TextBox IG.Forms.ReporterConfigurationForm.txtFadeShowtime private
Referenced by IG.Forms.ReporterConfigurationForm.ConsoleForm_Load(), and IG.Forms.ReporterConfigurationForm.txtFadingShowtime_TextChanged().
grpConsole
GroupBox IG.Forms.ReporterConfigurationForm.grpConsole private
pnlConsoleSwitch
Panel IG.Forms.ReporterConfigurationForm.pnlConsoleSwitch private
rbConsoleOn
RadioButton IG.Forms.ReporterConfigurationForm.rbConsoleOn private
Referenced by IG.Forms.ReporterConfigurationForm.ConsoleForm_Load(), and IG.Forms.ReporterConfigurationForm.rbConsoleOn_CheckedChanged().
rbConsoleOff
RadioButton IG.Forms.ReporterConfigurationForm.rbConsoleOff private
Referenced by IG.Forms.ReporterConfigurationForm.ConsoleForm_Load().
grpConsoleForm
GroupBox IG.Forms.ReporterConfigurationForm.grpConsoleForm private
pnlConsoleFormSwitch
Panel IG.Forms.ReporterConfigurationForm.pnlConsoleFormSwitch private
rbConsoleFormOn
RadioButton IG.Forms.ReporterConfigurationForm.rbConsoleFormOn private
Referenced by IG.Forms.ReporterConfigurationForm.ConsoleForm_Load(), and IG.Forms.ReporterConfigurationForm.rbConsoleFormOn_CheckedChanged().
rbConsoleFormOff
RadioButton IG.Forms.ReporterConfigurationForm.rbConsoleFormOff private
Referenced by IG.Forms.ReporterConfigurationForm.ConsoleForm_Load().
grpMessageBox
GroupBox IG.Forms.ReporterConfigurationForm.grpMessageBox private
pnlMessageBoxSwitch
Panel IG.Forms.ReporterConfigurationForm.pnlMessageBoxSwitch private
rbMessageBoxOn
RadioButton IG.Forms.ReporterConfigurationForm.rbMessageBoxOn private
Referenced by IG.Forms.ReporterConfigurationForm.ConsoleForm_Load(), and IG.Forms.ReporterConfigurationForm.rbMessageBoxOn_CheckedChanged().
rbMessageBoxOff
RadioButton IG.Forms.ReporterConfigurationForm.rbMessageBoxOff private
Referenced by IG.Forms.ReporterConfigurationForm.ConsoleForm_Load().
grpTest
GroupBox IG.Forms.ReporterConfigurationForm.grpTest private
grpOutputLevel
GroupBox IG.Forms.ReporterConfigurationForm.grpOutputLevel private
rbOutVerbose
RadioButton IG.Forms.ReporterConfigurationForm.rbOutVerbose private
Referenced by IG.Forms.ReporterConfigurationForm.btnLaunch_Click().
rbOutInfo
RadioButton IG.Forms.ReporterConfigurationForm.rbOutInfo private
Referenced by IG.Forms.ReporterConfigurationForm.btnLaunch_Click().
rbOutWarning
RadioButton IG.Forms.ReporterConfigurationForm.rbOutWarning private
Referenced by IG.Forms.ReporterConfigurationForm.btnLaunch_Click().
rbOutError
RadioButton IG.Forms.ReporterConfigurationForm.rbOutError private
Referenced by IG.Forms.ReporterConfigurationForm.btnLaunch_Click().
grpReportType
GroupBox IG.Forms.ReporterConfigurationForm.grpReportType private
rbInfo
RadioButton IG.Forms.ReporterConfigurationForm.rbInfo private
Referenced by IG.Forms.ReporterConfigurationForm.btnLaunch_Click().
rbWarning
RadioButton IG.Forms.ReporterConfigurationForm.rbWarning private
Referenced by IG.Forms.ReporterConfigurationForm.btnLaunch_Click().
rbError
RadioButton IG.Forms.ReporterConfigurationForm.rbError private
Referenced by IG.Forms.ReporterConfigurationForm.btnLaunch_Click().
btnLaunch
Button IG.Forms.ReporterConfigurationForm.btnLaunch private
grpMultipleReports
GroupBox IG.Forms.ReporterConfigurationForm.grpMultipleReports private
chkMultiple
CheckBox IG.Forms.ReporterConfigurationForm.chkMultiple private
Referenced by IG.Forms.ReporterConfigurationForm.btnLaunch_Click().
txtNumLaunches
TextBox IG.Forms.ReporterConfigurationForm.txtNumLaunches private
Referenced by IG.Forms.ReporterConfigurationForm.btnLaunch_Click().
txtDelay
TextBox IG.Forms.ReporterConfigurationForm.txtDelay private
Referenced by IG.Forms.ReporterConfigurationForm.btnLaunch_Click().
lblMultipleNum
Label IG.Forms.ReporterConfigurationForm.lblMultipleNum private
lblDelay
Label IG.Forms.ReporterConfigurationForm.lblDelay private
label1
Label IG.Forms.ReporterConfigurationForm.label1 private
lblMessage
Label IG.Forms.ReporterConfigurationForm.lblMessage private
txtExMessage
TextBox IG.Forms.ReporterConfigurationForm.txtExMessage private
Referenced by IG.Forms.ReporterConfigurationForm.btnLaunch_Click().
lblLocation
Label IG.Forms.ReporterConfigurationForm.lblLocation private
txtMessage
TextBox IG.Forms.ReporterConfigurationForm.txtMessage private
Referenced by IG.Forms.ReporterConfigurationForm.btnLaunch_Click().
txtLocation
TextBox IG.Forms.ReporterConfigurationForm.txtLocation private
Referenced by IG.Forms.ReporterConfigurationForm.btnLaunch_Click().
lblDescription
Label IG.Forms.ReporterConfigurationForm.lblDescription private
lblTitle
Label IG.Forms.ReporterConfigurationForm.lblTitle private
PnlStatus
Panel IG.Forms.ReporterConfigurationForm.PnlStatus private
CancelBtn
Button IG.Forms.ReporterConfigurationForm.CancelBtn private
StatusLbl
Label IG.Forms.ReporterConfigurationForm.StatusLbl private
chkThrowException
CheckBox IG.Forms.ReporterConfigurationForm.chkThrowException private
Referenced by IG.Forms.ReporterConfigurationForm.btnLaunch_Click().
Title
string IG.Forms.ReporterConfigurationForm.Title =""
Referenced by IG.Forms.ReporterConfigurationForm.ShowThread().
formthread
Thread IG.Forms.ReporterConfigurationForm.formthread = null private
Referenced by IG.Forms.ReporterConfigurationForm.ShowThread().
m_PrevX
int IG.Forms.ReporterConfigurationForm.m_PrevX private
Referenced by IG.Forms.ReporterConfigurationForm.ReportConfig_MouseDown(), and IG.Forms.ReporterConfigurationForm.ReportConfig_MouseMove().
m_PrevY
int IG.Forms.ReporterConfigurationForm.m_PrevY private
Referenced by IG.Forms.ReporterConfigurationForm.ReportConfig_MouseDown(), and IG.Forms.ReporterConfigurationForm.ReportConfig_MouseMove().
Property Documentation
reporter
ReporterForms IG.Forms.ReporterConfigurationForm.reporter get private set protected
Referenced by IG.Forms.ReporterConfigurationForm.btnLaunch_Click(), IG.Forms.ReporterConfigurationForm.ConsoleForm_Load(), IG.Forms.ReporterConfigurationForm.rbConsoleFormOn_CheckedChanged(), IG.Forms.ReporterConfigurationForm.rbConsoleOn_CheckedChanged(), IG.Forms.ReporterConfigurationForm.rbFadingMessageOn_CheckedChanged(), IG.Forms.ReporterConfigurationForm.rbMessageBoxOn_CheckedChanged(), IG.Forms.ReporterConfigurationForm.ReporterConfigurationForm(), IG.Forms.ReporterConfigurationForm.txtFadeBGFinal_BackColorChanged(), IG.Forms.ReporterConfigurationForm.txtFadingBG_BackColorChanged(), IG.Forms.ReporterConfigurationForm.txtFadingPortion_TextChanged(), and IG.Forms.ReporterConfigurationForm.txtFadingShowtime_TextChanged().
IsBackground
bool IG.Forms.ReporterConfigurationForm.IsBackground get set
The documentation for this class was generated from the following file:
iglib/igforms/Basic/ReporterConfigurationForm.cs