Doc: IGLib EXTENDED: IG.Physics.ChemicalCompound Class Reference
IG.Physics.ChemicalCompound Class Reference
Chemical compoind.
Public Member Functions
ChemicalCompound (params ChemicalElementQuantity[] elementQuantities)
Constructs a new chemical compound that consists of the specified stoichiometric quantities of elements listed in the specified order.
ChemicalCompound (ChemicalElements el1, int q1)
Construct a chemical compound containing the specified element with corresponding stoichiometric number.
ChemicalCompound (ChemicalElements el1, int q1, ChemicalElements el2, int q2, ChemicalElements el3, int q3, ChemicalElements el4, int q4, ChemicalElements el5, int q5)
Construct a chemical compound containing the specified 5 elements with corresponding stoichiometric numbers.
ChemicalCompound (ChemicalElements el1, int q1, ChemicalElements el2, int q2, ChemicalElements el3, int q3, ChemicalElements el4, int q4, ChemicalElements el5, int q5, ChemicalElements el6, int q6, ChemicalElements el7, int q7, ChemicalElements el8, int q8, ChemicalElements el9, int q9, ChemicalElements el10, int q10)
Construct a chemical compound containing the specified 10 elements with corresponding stoichiometric numbers.
ChemicalCompound (ChemicalElement el1, int q1)
Construct a chemical compound containing the specified 10 elements with corresponding stoichiometric numbers.
ChemicalCompound (ChemicalElement el1, int q1, ChemicalElement el2, int q2, ChemicalElement el3, int q3, ChemicalElement el4, int q4, ChemicalElement el5, int q5)
Construct a chemical compound containing the specified 10 elements with corresponding stoichiometric numbers.
ChemicalCompound (ChemicalElement el1, int q1, ChemicalElement el2, int q2, ChemicalElement el3, int q3, ChemicalElement el4, int q4, ChemicalElement el5, int q5, ChemicalElement el6, int q6, ChemicalElement el7, int q7, ChemicalElement el8, int q8, ChemicalElement el9, int q9, ChemicalElement el10, int q10)
Construct a chemical compound containing the specified 10 elements with corresponding stoichiometric numbers.
ChemicalElementQuantity[] GetElements ()
Returns an array of chemical elements with stoichiometric numbers that form the current chemical compound.
void ClearElements ()
Clears the list of elements with stoichiometric quantities that form the compound.
void AddElement (ChemicalElementQuantity el)
Adds the specified element with stoichiometric quantity to the list defining the compound.
void AddElements (params ChemicalElementQuantity[] chemicalElements)
Adds the specified elements with stoichiometric quantities to the list defining the compound.
void RemoveElement (ChemicalElementQuantity el)
Removes the specified element with stoichiometric quantity to the list defining the compound.
void RemoveElement (ChemicalElements whichElement)
Removes the chemical element specified by the ChemicalElements enumerator from the list of elements forming the compound.
void RemoveElement (string elementSymbolOrName)
Removes the element with either the specified name or symbol from the list of elements forming the compound.
int GetElementIndex (ChemicalElements whichElement)
Returns index of the specified element (defined by the ChemicalElements enumerator) on the list of elements forming the chemical compound, or a negative number if there is no matching element on the list.
int GetElementIndex (string elementSymbolOrName)
Returns index of the element with the specified name or symbol on the list of elements forming the chemical compound, or a negative number if there is no matching element on the list.
ChemicalElementQuantity GetElement (ChemicalElements whichElement)
Returns the chemical element quantity from the list of elements that form the compound that match the specified chemical element enumerator of type ChemicalElements, or null if there is no matchig element.
ChemicalElementQuantity GetElement (string elementSymbolOrName)
Returns the chemical element with stoichiometric quantity from the list of elements that form the compound that match the specified element symbol or name, or null if there is no matchig element.
Protected Attributes
List< ChemicalElementQuantity > _elements = new List<ChemicalElementQuantity>()
List of chemical elements with stoichiometric quantities that form the chemical compound.
Properties
int NumElements [get]
Gets the number of elements in the chemical compound.
Detailed Description
Chemical compoind.
Consists of a list of chemical elements with quantities.
$A Igor Nov08;
Constructor & Destructor Documentation
ChemicalCompound() [1/7]
IG.Physics.ChemicalCompound.ChemicalCompound (params ChemicalElementQuantity[] elementQuantities) inline
Constructs a new chemical compound that consists of the specified stoichiometric quantities of elements listed in the specified order.
Parameters
elementQuantities
References IG.Physics.ChemicalCompound.AddElement().
ChemicalCompound() [2/7]
IG.Physics.ChemicalCompound.ChemicalCompound (ChemicalElements el1, int q1) inline
Construct a chemical compound containing the specified element with corresponding stoichiometric number.
Elements and corresponding stoichiometric numbers are specified in alternating order - first element, first st. number, second element, second number, etc.
Only elements that are defined and have stoichiometric numbers greater thatn 0 are added.
References IG.Lib.None.
ChemicalCompound() [3/7]
IG.Physics.ChemicalCompound.ChemicalCompound (ChemicalElements el1, int q1, ChemicalElements el2, int q2, ChemicalElements el3, int q3, ChemicalElements el4, int q4, ChemicalElements el5, int q5) inline
Construct a chemical compound containing the specified 5 elements with corresponding stoichiometric numbers.
Elements and corresponding stoichiometric numbers are specified in alternating order - first element, first st. number, second element, second number, etc.
Only elements that are defined and have stoichiometric numbers greater thatn 0 are added.
References IG.Lib.None.
ChemicalCompound() [4/7]
IG.Physics.ChemicalCompound.ChemicalCompound (ChemicalElements el1, int q1, ChemicalElements el2, int q2, ChemicalElements el3, int q3, ChemicalElements el4, int q4, ChemicalElements el5, int q5, ChemicalElements el6, int q6, ChemicalElements el7, int q7, ChemicalElements el8, int q8, ChemicalElements el9, int q9, ChemicalElements el10, int q10) inline
Construct a chemical compound containing the specified 10 elements with corresponding stoichiometric numbers.
Elements and corresponding stoichiometric numbers are specified in alternating order - first element, first st. number, second element, second number, etc.
Only elements that are defined and have stoichiometric numbers greater thatn 0 are added.
References IG.Physics.ChemicalCompound.AddElement().
ChemicalCompound() [5/7]
IG.Physics.ChemicalCompound.ChemicalCompound (ChemicalElement el1, int q1) inline
Construct a chemical compound containing the specified 10 elements with corresponding stoichiometric numbers.
Elements and corresponding stoichiometric numbers are specified in alternating order - first element, first st. number, second element, second number, etc.
Only elements that are defined and have stoichiometric numbers greater thatn 0 are added.
ChemicalCompound() [6/7]
IG.Physics.ChemicalCompound.ChemicalCompound (ChemicalElement el1, int q1, ChemicalElement el2, int q2, ChemicalElement el3, int q3, ChemicalElement el4, int q4, ChemicalElement el5, int q5) inline
Construct a chemical compound containing the specified 10 elements with corresponding stoichiometric numbers.
Elements and corresponding stoichiometric numbers are specified in alternating order - first element, first st. number, second element, second number, etc.
Only elements that are defined and have stoichiometric numbers greater thatn 0 are added.
ChemicalCompound() [7/7]
IG.Physics.ChemicalCompound.ChemicalCompound (ChemicalElement el1, int q1, ChemicalElement el2, int q2, ChemicalElement el3, int q3, ChemicalElement el4, int q4, ChemicalElement el5, int q5, ChemicalElement el6, int q6, ChemicalElement el7, int q7, ChemicalElement el8, int q8, ChemicalElement el9, int q9, ChemicalElement el10, int q10) inline
Construct a chemical compound containing the specified 10 elements with corresponding stoichiometric numbers.
Elements and corresponding stoichiometric numbers are specified in alternating order - first element, first st. number, second element, second number, etc.
Only elements that are defined and have stoichiometric numbers greater thatn 0 are added.
References IG.Physics.ChemicalCompound.AddElement().
Member Function Documentation
GetElements()
ChemicalElementQuantity [] IG.Physics.ChemicalCompound.GetElements () inline
Returns an array of chemical elements with stoichiometric numbers that form the current chemical compound.
References IG.Physics.ChemicalCompound._elements.
Referenced by ChemicalCompoundDto.CopyFromPlain().
ClearElements()
void IG.Physics.ChemicalCompound.ClearElements () inline
Clears the list of elements with stoichiometric quantities that form the compound.
References IG.Physics.ChemicalCompound._elements.
AddElement()
void IG.Physics.ChemicalCompound.AddElement (ChemicalElementQuantity el) inline
Adds the specified element with stoichiometric quantity to the list defining the compound.
Parameters
el Element to be added.
References IG.Physics.ChemicalCompound._elements.
Referenced by IG.Physics.ChemicalCompound.ChemicalCompound().
AddElements()
void IG.Physics.ChemicalCompound.AddElements (params ChemicalElementQuantity[] chemicalElements) inline
Adds the specified elements with stoichiometric quantities to the list defining the compound.
Parameters
el Elements to be added.
References IG.Physics.ChemicalCompound._elements.
RemoveElement() [1/3]
void IG.Physics.ChemicalCompound.RemoveElement (ChemicalElementQuantity el) inline
Removes the specified element with stoichiometric quantity to the list defining the compound.
Parameters
el Element to be removed.
References IG.Physics.ChemicalCompound._elements.
RemoveElement() [2/3]
void IG.Physics.ChemicalCompound.RemoveElement (ChemicalElements whichElement) inline
Removes the chemical element specified by the ChemicalElements enumerator from the list of elements forming the compound.
Parameters
whichElement Specifies the element to be removed.
References IG.Physics.ChemicalCompound._elements, and IG.Physics.ChemicalCompound.GetElementIndex().
RemoveElement() [3/3]
void IG.Physics.ChemicalCompound.RemoveElement (string elementSymbolOrName) inline
Removes the element with either the specified name or symbol from the list of elements forming the compound.
Parameters
elementSymbolOrName Symbol or name (any ofthose two is valid) of the chemical element to be removed.
References IG.Physics.ChemicalCompound._elements, and IG.Physics.ChemicalCompound.GetElementIndex().
GetElementIndex() [1/2]
int IG.Physics.ChemicalCompound.GetElementIndex (ChemicalElements whichElement) inline
Returns index of the specified element (defined by the ChemicalElements enumerator) on the list of elements forming the chemical compound, or a negative number if there is no matching element on the list.
Parameters
whichElement Enumerator of type ChemicalElements that specifies the element whose index is returned.
Returns
Index of the matching element, or a negative number if there is no matching element.
References IG.Physics.ChemicalCompound._elements, and IG.Physics.ChemicalElement.Element.
Referenced by IG.Physics.ChemicalCompound.GetElement(), and IG.Physics.ChemicalCompound.RemoveElement().
GetElementIndex() [2/2]
int IG.Physics.ChemicalCompound.GetElementIndex (string elementSymbolOrName) inline
Returns index of the element with the specified name or symbol on the list of elements forming the chemical compound, or a negative number if there is no matching element on the list.
Parameters
elementSymbolOrName Either symbol of name of the element whose index is returned (both are acceptable).
Returns
Index of the matching element, or a negative number if there is no matching element.
References IG.Physics.ChemicalCompound._elements, IG.Physics.ChemicalElement.Name, and IG.Physics.ChemicalElement.Symbol.
GetElement() [1/2]
ChemicalElementQuantity IG.Physics.ChemicalCompound.GetElement (ChemicalElements whichElement) inline
Returns the chemical element quantity from the list of elements that form the compound that match the specified chemical element enumerator of type ChemicalElements, or null if there is no matchig element.
Parameters
whichElement Enumerator of type ChemicalElements that defines which element with stoichiometric quantity is to be returned.
Returns
Matching element from the list of elements that form the compound, or null if there is no such element in the compound.
References IG.Physics.ChemicalCompound._elements, and IG.Physics.ChemicalCompound.GetElementIndex().
GetElement() [2/2]
ChemicalElementQuantity IG.Physics.ChemicalCompound.GetElement (string elementSymbolOrName) inline
Returns the chemical element with stoichiometric quantity from the list of elements that form the compound that match the specified element symbol or name, or null if there is no matchig element.
Parameters
whichElement Symbol or name of the element to be returned (both are accepted).
If null or empty string then null is returned.
Returns
Matching element from the list of elements that form the compound, or null if there is no such element in the compound.
References IG.Physics.ChemicalCompound._elements, and IG.Physics.ChemicalCompound.GetElementIndex().
Member Data Documentation
_elements
List<ChemicalElementQuantity> IG.Physics.ChemicalCompound._elements = new List<ChemicalElementQuantity>() protected
List of chemical elements with stoichiometric quantities that form the chemical compound.
Order of elements matters as it is used for printing the compound's molecular formula.
Referenced by IG.Physics.ChemicalCompound.AddElement(), IG.Physics.ChemicalCompound.AddElements(), IG.Physics.ChemicalCompound.ClearElements(), IG.Physics.ChemicalCompound.GetElement(), IG.Physics.ChemicalCompound.GetElementIndex(), IG.Physics.ChemicalCompound.GetElements(), and IG.Physics.ChemicalCompound.RemoveElement().
Property Documentation
NumElements
int IG.Physics.ChemicalCompound.NumElements get
Gets the number of elements in the chemical compound.
Referenced by ChemicalCompoundDto.CopyFromPlain().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/physics/chemistry/ChemicalCompound.cs