Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAGS2 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAGS2 Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAGS2 (DLARTG dlartg, DLASV2 dlasv2)
DLAGS2 ()
void Run (bool UPPER, double A1, double A2, double A3, double B1, double B2, double B3, ref double CSU, ref double SNU, ref double CSV, ref double SNV, ref double CSQ, ref double SNQ)
Private Attributes
DLARTG _dlartg
DLASV2 _dlasv2
Static Private Attributes
const double ZERO = 0.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAGS2 computes 2-by-2 orthogonal matrices U, V and Q, such that if (UPPER) then
U'A*Q = U'(A1 A2)*Q = (x 0) (0 A3) (x x) and V'B*Q = V'(B1 B2)*Q = (x 0) (0 B3) (x x)
or if (.NOT.UPPER) then
U'A*Q = U'(A1 0)*Q = (x x) (A2 A3) (0 x) and V'B*Q = V'(B1 0)*Q = (x x) (B2 B3) (0 x)
The rows of the transformed A and B are parallel, where
U = (CSU SNU), V = (CSV SNV), Q = (CSQ SNQ) (-SNU CSU) (-SNV CSV) (-SNQ CSQ)
Z' denotes the transpose of Z. /summary>
Constructor & Destructor Documentation
DLAGS2() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAGS2.DLAGS2 (DLARTG dlartg, DLASV2 dlasv2) inline
DLAGS2() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAGS2.DLAGS2 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAGS2.Run (bool UPPER, double A1, double A2, double A3, double B1, double B2, double B3, ref double CSU, ref double SNU, ref double CSV, ref double SNV, ref double CSQ, ref double SNQ) inline
Purpose
DLAGS2 computes 2-by-2 orthogonal matrices U, V and Q, such that if (UPPER) then
U'A*Q = U'(A1 A2)*Q = (x 0) (0 A3) (x x) and V'B*Q = V'(B1 B2)*Q = (x 0) (0 B3) (x x)
or if (.NOT.UPPER) then
U'A*Q = U'(A1 0)*Q = (x x) (A2 A3) (0 x) and V'B*Q = V'(B1 0)*Q = (x x) (B2 B3) (0 x)
The rows of the transformed A and B are parallel, where
U = (CSU SNU), V = (CSV SNV), Q = (CSQ SNQ) (-SNU CSU) (-SNV CSV) (-SNQ CSQ)
Z' denotes the transpose of Z. /summary>
Parameters
UPPER (input) LOGICAL = .TRUE.: the input matrices A and B are upper triangular. = .FALSE.: the input matrices A and B are lower triangular. /param>
Parameters
A1 (input) DOUBLE PRECISION /param>
Parameters
A2 (input) DOUBLE PRECISION /param>
Parameters
A3 (input) DOUBLE PRECISION On entry, A1, A2 and A3 are elements of the input 2-by-2 upper (lower) triangular matrix A. /param>
Parameters
B1 (input) DOUBLE PRECISION /param>
Parameters
B2 (input) DOUBLE PRECISION /param>
Parameters
B3 (input) DOUBLE PRECISION On entry, B1, B2 and B3 are elements of the input 2-by-2 upper (lower) triangular matrix B. /param>
Parameters
CSU (output) DOUBLE PRECISION /param>
Parameters
SNU (output) DOUBLE PRECISION The desired orthogonal matrix U. /param>
Parameters
CSV (output) DOUBLE PRECISION /param>
Parameters
SNV (output) DOUBLE PRECISION The desired orthogonal matrix V. /param>
Parameters
CSQ (output) DOUBLE PRECISION /param>
Parameters
SNQ (output) DOUBLE PRECISION The desired orthogonal matrix Q. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLARTG.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASV2.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAGS2.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTGSJA.Run().
Member Data Documentation
_dlartg
DLARTG DotNumerics.LinearAlgebra.CSLapack.DLAGS2._dlartg private
_dlasv2
DLASV2 DotNumerics.LinearAlgebra.CSLapack.DLAGS2._dlasv2 private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAGS2.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAGS2.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlags2.cs