Doc: IGLib EXTENDED: AForge.Controls.ManipulatorControl Class Reference
AForge.Controls.ManipulatorControl Class Reference
Manipulator control.
Classes
class PositionEventArgs
Class, which summarizes arguments of manipulator's position change event.
Public Member Functions
delegate void PositionChangedHandler (object sender, PositionEventArgs eventArgs)
Delegate used for notification about manipulator's position changes.
ManipulatorControl ()
Initializes a new instance of the ManipulatorControl class.
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
bool IsSquareLook [get, set]
Determines if the control has square or round look.
bool DrawHorizontalAxis [get, set]
Determines if horizontal axis should be drawn or not.
bool DrawVerticalAxis [get, set]
Determines if vertical axis should be drawn or not.
bool ResetPositionOnMouseRelease [get, set]
Determines behaviour of manipulator, when mouse button is released.
Color BorderColor [get, set]
Color used for drawing borders and axis's.
Color TopLeftBackgroundColor [get, set]
Background color used for filling top left quarter of the control.
Color TopRightBackgroundColor [get, set]
Background color used for filling top right quarter of the control.
Color BottomLeftBackgroundColor [get, set]
Background color used for filling bottom left quarter of the control.
Color BottomRightBackgroundColor [get, set]
Background color used for filling bottom right quarter of the control.
Color ManipulatorColor [get, set]
Color used for filling manipulator.
PointF ManipulatorPosition [get, set]
Current manipulator's position.
Events
PositionChangedHandler PositionChanged
Event used for notification about manipulator's position changes.
Private Member Functions
void ManipulatorControl_Paint (object sender, PaintEventArgs e)
void ManipulatorControl_MouseDown (object sender, MouseEventArgs e)
void ManipulatorControl_MouseUp (object sender, MouseEventArgs e)
void ManipulatorControl_MouseMove (object sender, MouseEventArgs e)
void timer_Tick (object sender, EventArgs e)
void NotifyClients ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
bool isSquareLook = false
bool drawHorizontalAxis = true
bool drawVerticalAxis = false
bool resetPositionOnMouseRelease = true
Pen borderPen = new Pen(Color.Black)
SolidBrush topLeftBackgroundBrush = new SolidBrush(Color.White)
SolidBrush topRightBackgroundBrush = new SolidBrush(Color.White)
SolidBrush bottomLeftBackgroundBrush = new SolidBrush(Color.LightGray)
SolidBrush bottomRightBackgroundBrush = new SolidBrush(Color.LightGray)
SolidBrush manipulatorBrush = new SolidBrush(Color.LightSeaGreen)
SolidBrush disabledBrash = new SolidBrush(Color.FromArgb(240, 240, 240))
float manipulatatorX = 0
float manipulatatorY = 0
int areaSize = 0
int areaRadius = 0
int areaMargin = manipulatorSize / 2 + 2
bool tracking = false
int ticksBeforeNotificiation = -1
System.Windows.Forms.Timer timer
System.ComponentModel.IContainer components
Static Private Attributes
const int manipulatorSize = 21
const int manipulatorRadius = manipulatorSize / 2
Detailed Description
Manipulator control.
The manipulator control can be used to mimic behaviour of analogue joystick using regular mouse. By dragging manipulator away from control's centre, it fires PositionChanged event notifying about its X/Y coordinates (or about R/Theta coordinates in Polar coordinates system).
For example, in robotics applications the control can be used to drive robots. If user drags manipulator further from centre (increasing distance between centre and manipulator), then higher power (speed) should be set for robot's motors. But dragging it in different directions away from centre should result in changing robot's direction: straight forward, backward, turning right or left, etc.
Another possible application of the control is to control position of some device, etc. For example, the control could be used with pan-tilt camera - by dragging control away from centre, the camera may rotate in one of the directions.
Constructor & Destructor Documentation
ManipulatorControl()
AForge.Controls.ManipulatorControl.ManipulatorControl () inline
Initializes a new instance of the ManipulatorControl class.
References AForge.Controls.ManipulatorControl.InitializeComponent().
Member Function Documentation
PositionChangedHandler()
delegate void AForge.Controls.ManipulatorControl.PositionChangedHandler (object sender, PositionEventArgs eventArgs)
Delegate used for notification about manipulator's position changes.
Parameters
sender Event sender - object sending the event.
eventArgs Event arguments - current manipulator's position.
Referenced by SRVTest.MainForm.InitializeComponent(), and SVSTest.MainForm.InitializeComponent().
ManipulatorControl_Paint()
void AForge.Controls.ManipulatorControl.ManipulatorControl_Paint (object sender, PaintEventArgs e) inline private
References AForge.Controls.ManipulatorControl.areaMargin, AForge.Controls.ManipulatorControl.areaRadius, AForge.Controls.ManipulatorControl.areaSize, AForge.Controls.ManipulatorControl.borderPen, AForge.Controls.ManipulatorControl.bottomLeftBackgroundBrush, AForge.Controls.ManipulatorControl.bottomRightBackgroundBrush, AForge.Controls.ManipulatorControl.disabledBrash, AForge.Controls.ManipulatorControl.drawHorizontalAxis, AForge.Controls.ManipulatorControl.drawVerticalAxis, AForge.Controls.ManipulatorControl.isSquareLook, AForge.Controls.ManipulatorControl.manipulatatorX, AForge.Controls.ManipulatorControl.manipulatatorY, AForge.Controls.ManipulatorControl.manipulatorBrush, AForge.Controls.ManipulatorControl.manipulatorRadius, AForge.Controls.ManipulatorControl.manipulatorSize, AForge.Controls.ManipulatorControl.topLeftBackgroundBrush, and AForge.Controls.ManipulatorControl.topRightBackgroundBrush.
Referenced by AForge.Controls.ManipulatorControl.InitializeComponent().
ManipulatorControl_MouseDown()
void AForge.Controls.ManipulatorControl.ManipulatorControl_MouseDown (object sender, MouseEventArgs e) inline private
References AForge.Controls.ManipulatorControl.areaMargin, AForge.Controls.ManipulatorControl.areaRadius, AForge.Controls.ManipulatorControl.isSquareLook, AForge.Controls.ManipulatorControl.manipulatatorX, AForge.Controls.ManipulatorControl.manipulatatorY, AForge.Controls.ManipulatorControl.NotifyClients(), AForge.Controls.ManipulatorControl.ticksBeforeNotificiation, AForge.Controls.ManipulatorControl.timer, and AForge.Controls.ManipulatorControl.tracking.
Referenced by AForge.Controls.ManipulatorControl.InitializeComponent().
ManipulatorControl_MouseUp()
void AForge.Controls.ManipulatorControl.ManipulatorControl_MouseUp (object sender, MouseEventArgs e) inline private
References AForge.Controls.ManipulatorControl.manipulatatorX, AForge.Controls.ManipulatorControl.manipulatatorY, AForge.Controls.ManipulatorControl.NotifyClients(), AForge.Controls.ManipulatorControl.resetPositionOnMouseRelease, AForge.Controls.ManipulatorControl.timer, and AForge.Controls.ManipulatorControl.tracking.
Referenced by AForge.Controls.ManipulatorControl.InitializeComponent().
ManipulatorControl_MouseMove()
void AForge.Controls.ManipulatorControl.ManipulatorControl_MouseMove (object sender, MouseEventArgs e) inline private
References AForge.Controls.ManipulatorControl.areaMargin, AForge.Controls.ManipulatorControl.areaRadius, AForge.Controls.ManipulatorControl.isSquareLook, AForge.Controls.ManipulatorControl.manipulatatorX, AForge.Controls.ManipulatorControl.manipulatatorY, AForge.Controls.ManipulatorControl.ticksBeforeNotificiation, and AForge.Controls.ManipulatorControl.tracking.
Referenced by AForge.Controls.ManipulatorControl.InitializeComponent().
timer_Tick()
void AForge.Controls.ManipulatorControl.timer_Tick (object sender, EventArgs e) inline private
References AForge.Controls.ManipulatorControl.NotifyClients(), and AForge.Controls.ManipulatorControl.ticksBeforeNotificiation.
Referenced by AForge.Controls.ManipulatorControl.InitializeComponent().
NotifyClients()
void AForge.Controls.ManipulatorControl.NotifyClients () inline private
References AForge.Controls.ManipulatorControl.manipulatatorX, AForge.Controls.ManipulatorControl.manipulatatorY, and AForge.Controls.ManipulatorControl.PositionChanged.
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_MouseDown(), AForge.Controls.ManipulatorControl.ManipulatorControl_MouseUp(), and AForge.Controls.ManipulatorControl.timer_Tick().
Dispose()
override void AForge.Controls.ManipulatorControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References AForge.Controls.ManipulatorControl.components.
InitializeComponent()
void AForge.Controls.ManipulatorControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References AForge.Controls.ManipulatorControl.components, AForge.Controls.ManipulatorControl.ManipulatorControl_MouseDown(), AForge.Controls.ManipulatorControl.ManipulatorControl_MouseMove(), AForge.Controls.ManipulatorControl.ManipulatorControl_MouseUp(), AForge.Controls.ManipulatorControl.ManipulatorControl_Paint(), AForge.Controls.ManipulatorControl.timer, and AForge.Controls.ManipulatorControl.timer_Tick().
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl().
Member Data Documentation
isSquareLook
bool AForge.Controls.ManipulatorControl.isSquareLook = false private
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_MouseDown(), AForge.Controls.ManipulatorControl.ManipulatorControl_MouseMove(), and AForge.Controls.ManipulatorControl.ManipulatorControl_Paint().
drawHorizontalAxis
bool AForge.Controls.ManipulatorControl.drawHorizontalAxis = true private
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_Paint().
drawVerticalAxis
bool AForge.Controls.ManipulatorControl.drawVerticalAxis = false private
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_Paint().
resetPositionOnMouseRelease
bool AForge.Controls.ManipulatorControl.resetPositionOnMouseRelease = true private
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_MouseUp().
borderPen
Pen AForge.Controls.ManipulatorControl.borderPen = new Pen(Color.Black) private
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_Paint().
topLeftBackgroundBrush
SolidBrush AForge.Controls.ManipulatorControl.topLeftBackgroundBrush = new SolidBrush(Color.White) private
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_Paint().
topRightBackgroundBrush
SolidBrush AForge.Controls.ManipulatorControl.topRightBackgroundBrush = new SolidBrush(Color.White) private
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_Paint().
bottomLeftBackgroundBrush
SolidBrush AForge.Controls.ManipulatorControl.bottomLeftBackgroundBrush = new SolidBrush(Color.LightGray) private
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_Paint().
bottomRightBackgroundBrush
SolidBrush AForge.Controls.ManipulatorControl.bottomRightBackgroundBrush = new SolidBrush(Color.LightGray) private
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_Paint().
manipulatorBrush
SolidBrush AForge.Controls.ManipulatorControl.manipulatorBrush = new SolidBrush(Color.LightSeaGreen) private
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_Paint().
disabledBrash
SolidBrush AForge.Controls.ManipulatorControl.disabledBrash = new SolidBrush(Color.FromArgb(240, 240, 240)) private
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_Paint().
manipulatatorX
float AForge.Controls.ManipulatorControl.manipulatatorX = 0 private
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_MouseDown(), AForge.Controls.ManipulatorControl.ManipulatorControl_MouseMove(), AForge.Controls.ManipulatorControl.ManipulatorControl_MouseUp(), AForge.Controls.ManipulatorControl.ManipulatorControl_Paint(), and AForge.Controls.ManipulatorControl.NotifyClients().
manipulatatorY
float AForge.Controls.ManipulatorControl.manipulatatorY = 0 private
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_MouseDown(), AForge.Controls.ManipulatorControl.ManipulatorControl_MouseMove(), AForge.Controls.ManipulatorControl.ManipulatorControl_MouseUp(), AForge.Controls.ManipulatorControl.ManipulatorControl_Paint(), and AForge.Controls.ManipulatorControl.NotifyClients().
manipulatorSize
const int AForge.Controls.ManipulatorControl.manipulatorSize = 21 static private
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_Paint().
manipulatorRadius
const int AForge.Controls.ManipulatorControl.manipulatorRadius = manipulatorSize / 2 static private
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_Paint().
areaSize
int AForge.Controls.ManipulatorControl.areaSize = 0 private
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_Paint().
areaRadius
int AForge.Controls.ManipulatorControl.areaRadius = 0 private
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_MouseDown(), AForge.Controls.ManipulatorControl.ManipulatorControl_MouseMove(), and AForge.Controls.ManipulatorControl.ManipulatorControl_Paint().
areaMargin
int AForge.Controls.ManipulatorControl.areaMargin = manipulatorSize / 2 + 2 private
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_MouseDown(), AForge.Controls.ManipulatorControl.ManipulatorControl_MouseMove(), and AForge.Controls.ManipulatorControl.ManipulatorControl_Paint().
tracking
bool AForge.Controls.ManipulatorControl.tracking = false private
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_MouseDown(), AForge.Controls.ManipulatorControl.ManipulatorControl_MouseMove(), and AForge.Controls.ManipulatorControl.ManipulatorControl_MouseUp().
ticksBeforeNotificiation
int AForge.Controls.ManipulatorControl.ticksBeforeNotificiation = -1 private
Referenced by AForge.Controls.ManipulatorControl.ManipulatorControl_MouseDown(), AForge.Controls.ManipulatorControl.ManipulatorControl_MouseMove(), and AForge.Controls.ManipulatorControl.timer_Tick().
timer
System.Windows.Forms.Timer AForge.Controls.ManipulatorControl.timer private
Referenced by AForge.Controls.ManipulatorControl.InitializeComponent(), AForge.Controls.ManipulatorControl.ManipulatorControl_MouseDown(), and AForge.Controls.ManipulatorControl.ManipulatorControl_MouseUp().
components
System.ComponentModel.IContainer AForge.Controls.ManipulatorControl.components private
Referenced by AForge.Controls.ManipulatorControl.Dispose(), and AForge.Controls.ManipulatorControl.InitializeComponent().
Property Documentation
IsSquareLook
bool AForge.Controls.ManipulatorControl.IsSquareLook get set
Determines if the control has square or round look.
The control has a square look if the property is set to true, otherwise it has round look.
Default value is set to false.
DrawHorizontalAxis
bool AForge.Controls.ManipulatorControl.DrawHorizontalAxis get set
Determines if horizontal axis should be drawn or not.
Default value is set to true.
DrawVerticalAxis
bool AForge.Controls.ManipulatorControl.DrawVerticalAxis get set
Determines if vertical axis should be drawn or not.
Default value is set to false.
ResetPositionOnMouseRelease
bool AForge.Controls.ManipulatorControl.ResetPositionOnMouseRelease get set
Determines behaviour of manipulator, when mouse button is released.
The property controls behaviour of manipulator on releasing mouse button. If the property is set to true, then position of manipulator is reset to (0, 0), when mouse button is released. Otherwise manipulator stays on the place, where it was left.
Default value is set to true.
BorderColor
Color AForge.Controls.ManipulatorControl.BorderColor get set
Color used for drawing borders and axis's.
Default value is set to Color.Black.
TopLeftBackgroundColor
Color AForge.Controls.ManipulatorControl.TopLeftBackgroundColor get set
Background color used for filling top left quarter of the control.
Default value is set to Color.White.
TopRightBackgroundColor
Color AForge.Controls.ManipulatorControl.TopRightBackgroundColor get set
Background color used for filling top right quarter of the control.
Default value is set to Color.White.
BottomLeftBackgroundColor
Color AForge.Controls.ManipulatorControl.BottomLeftBackgroundColor get set
Background color used for filling bottom left quarter of the control.
Default value is set to Color.LightGray.
BottomRightBackgroundColor
Color AForge.Controls.ManipulatorControl.BottomRightBackgroundColor get set
Background color used for filling bottom right quarter of the control.
Default value is set to Color.LightGray.
ManipulatorColor
Color AForge.Controls.ManipulatorControl.ManipulatorColor get set
Color used for filling manipulator.
Default value is set to Color.LightSeaGreen.
ManipulatorPosition
PointF AForge.Controls.ManipulatorControl.ManipulatorPosition get set
Current manipulator's position.
The property equals to current manipulator's position. Both X and Y values are in the [-1, 1] range and represented in Cartesian coordinate system.
Event Documentation
PositionChanged
PositionChangedHandler AForge.Controls.ManipulatorControl.PositionChanged
Event used for notification about manipulator's position changes.
Referenced by AForge.Controls.ManipulatorControl.NotifyClients().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Sources/Controls/ManipulatorControl.cs
shelldev/lib_ann/aforge.net/Sources/Controls/ManipulatorControl.Designer.cs