Doc: IGLib EXTENDED: NUnit.Engine.Services.Tests.DriverServiceTests Class Reference
NUnit.Engine.Services.Tests.DriverServiceTests Class Reference
Public Member Functions
void CreateDriverFactory ()
void ServiceIsStarted ()
void CorrectDriverIsUsed (string fileName, Type expectedType)
Private Attributes
DriverService _driverService
Member Function Documentation
CreateDriverFactory()
void NUnit.Engine.Services.Tests.DriverServiceTests.CreateDriverFactory () inline
References NUnit.Engine.Services.Tests.DriverServiceTests._driverService.
ServiceIsStarted()
void NUnit.Engine.Services.Tests.DriverServiceTests.ServiceIsStarted () inline
References NUnit.Engine.Services.Tests.DriverServiceTests._driverService, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Services.Service.Status, and NUnit.Framework.Assert.That().
CorrectDriverIsUsed()
void NUnit.Engine.Services.Tests.DriverServiceTests.CorrectDriverIsUsed (string fileName, Type expectedType) inline
References NUnit.Engine.Services.Tests.DriverServiceTests._driverService, NUnit.Framework.TestContext.CurrentContext, NUnit.Engine.Services.DriverService.GetDriver(), NUnit.Framework.Is.InstanceOf(), NUnit.Framework.TestContext.TestDirectory, and NUnit.Framework.Assert.That().
Member Data Documentation
_driverService
DriverService NUnit.Engine.Services.Tests.DriverServiceTests._driverService private
Referenced by NUnit.Engine.Services.Tests.DriverServiceTests.CorrectDriverIsUsed(), NUnit.Engine.Services.Tests.DriverServiceTests.CreateDriverFactory(), and NUnit.Engine.Services.Tests.DriverServiceTests.ServiceIsStarted().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Services/DriverServiceTests.cs