Doc: IGLib EXTENDED: Meta.Numerics.Statistics.Distributions.MomentMath Class Reference
Meta.Numerics.Statistics.Distributions.MomentMath Class Reference
Contains methods for converting between different kinds of moments.
Static Public Member Functions
static double[] RawToCentral (double[] M)
Converts raw moments to central moments.
static double[] CentralToRaw (double mu, double[] C)
Converts central moments to raw moments.
static double[] CumulantToRaw (double[] K)
Converts cumulants to raw moments.
static double[] CumulantToCentral (double[] K)
Converts cumulants to central moments.
static double[] RawToCumulant (double[] M)
Converts raw moments to cumulants.
static double[] CentralToCumulant (double mu, double[] C)
Converts central moments to cumulants.
Detailed Description
Contains methods for converting between different kinds of moments.
Member Function Documentation
RawToCentral()
static double [] Meta.Numerics.Statistics.Distributions.MomentMath.RawToCentral (double[] M) inline static
Converts raw moments to central moments.
Parameters
M A set or raw moments.
Returns
The corresponding set of central moments.
Exceptions
ArgumentNullException M is null.
ArgumentOutOfRangeException The zeroth raw moment is not one.
Referenced by Meta.Numerics.Statistics.Distributions.UnivariateDistribution.MomentAboutMean().
CentralToRaw()
static double [] Meta.Numerics.Statistics.Distributions.MomentMath.CentralToRaw (double mu, double[] C) inline static
Converts central moments to raw moments.
Parameters
mu The mean.
C A set or central moments.
Returns
The corresponding set of central moments.
Exceptions
ArgumentNullException C is null.
ArgumentOutOfRangeException The zeroth central moment is not one, or the first central moment is not zero.
Referenced by Test.DistributionTest.DistributionMomentTranslations(), Meta.Numerics.Statistics.Distributions.NormalDistribution.Moment(), Meta.Numerics.Statistics.Distributions.LogisticDistribution.Moment(), and FutureTest.FutureTest.TestCumulant2().
CumulantToRaw()
static double [] Meta.Numerics.Statistics.Distributions.MomentMath.CumulantToRaw (double[] K) inline static
Converts cumulants to raw moments.
Parameters
K A set or cumulants.
Returns
The corresponding set of raw moments.
Exceptions
ArgumentNullException K is null.
ArgumentOutOfRangeException The zeroth cumulant is not zero.
Referenced by FutureTest.FutureTest.CumulantTest(), Test.UnivariateDistributionTest.CumulantToCentralAndRaw(), and FutureTest.FutureTest.TestCumulant2().
CumulantToCentral()
static double [] Meta.Numerics.Statistics.Distributions.MomentMath.CumulantToCentral (double[] K) inline static
Converts cumulants to central moments.
Parameters
K A set or cumulants.
Returns
The corresponding set of central moments.
Exceptions
ArgumentNullException K is null.
ArgumentOutOfRangeException The zeroth cumulant is not zero.
Referenced by FutureTest.FutureTest.CumulantTest(), Test.UnivariateDistributionTest.CumulantToCentralAndRaw(), and FutureTest.FutureTest.TestCumulant2().
RawToCumulant()
static double [] Meta.Numerics.Statistics.Distributions.MomentMath.RawToCumulant (double[] M) inline static
Converts raw moments to cumulants.
Parameters
M A set of raw moments.
Returns
The corresponding set of cumulants.
Exceptions
ArgumentNullException M is null.
ArgumentOutOfRangeException The zeroth raw moment is not one.
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficient().
Referenced by FutureTest.FutureTest.CumulantTest().
CentralToCumulant()
static double [] Meta.Numerics.Statistics.Distributions.MomentMath.CentralToCumulant (double mu, double[] C) inline static
Converts central moments to cumulants.
Parameters
mu The mean.
C A set of central moments.
Returns
The corresponding set of cumulants.
Exceptions
ArgumentNullException C is null.
ArgumentOutOfRangeException The zeroth central moment is not one, or the first central moment is not zero.
References Meta.Numerics.Functions.AdvancedIntegerMath.BinomialCoefficient().
Referenced by Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Cumulant(), and FutureTest.FutureTest.TestCumulant2().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/Distributions/MomentMath.cs