Doc: IGLib EXTENDED: NUnit.Framework.Assertions.AssertThrowsTests Class Reference
NUnit.Framework.Assertions.AssertThrowsTests Class Reference
Public Member Functions
void CorrectExceptionThrown ()
void CorrectExceptionIsReturnedToMethod ()
void NoExceptionThrown ()
void UnrelatedExceptionThrown ()
void BaseExceptionThrown ()
void DerivedExceptionThrown ()
void DoesNotThrowSuceeds ()
void DoesNotThrowFails ()
Private Member Functions
Exception CatchException (TestDelegate del)
Member Function Documentation
CorrectExceptionThrown()
void NUnit.Framework.Assertions.AssertThrowsTests.CorrectExceptionThrown () inline
References NUnit.Framework.Throws.Exception, NUnit.Framework.TestDelegate(), NUnit.Framework.Assert.That(), NUnit.Framework.Assert.Throws(), and NUnit.TestUtilities.TestDelegates.ThrowsArgumentException().
CorrectExceptionIsReturnedToMethod()
void NUnit.Framework.Assertions.AssertThrowsTests.CorrectExceptionIsReturnedToMethod () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.IsNotNull(), NUnit.Framework.Does.StartWith(), NUnit.Framework.TestDelegate(), NUnit.Framework.Assert.That(), NUnit.Framework.Assert.Throws(), and NUnit.TestUtilities.TestDelegates.ThrowsArgumentException().
NoExceptionThrown()
void NUnit.Framework.Assertions.AssertThrowsTests.NoExceptionThrown () inline
References NUnit.Framework.Assertions.AssertThrowsTests.CatchException(), NUnit.Framework.Is.EqualTo(), NUnit.Env.NewLine, NUnit.Framework.Assert.That(), NUnit.Framework.Assert.Throws(), and NUnit.TestUtilities.TestDelegates.ThrowsNothing().
UnrelatedExceptionThrown()
void NUnit.Framework.Assertions.AssertThrowsTests.UnrelatedExceptionThrown () inline
References NUnit.Framework.Assertions.AssertThrowsTests.CatchException(), NUnit.Env.NewLine, NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), NUnit.Framework.Assert.Throws(), and NUnit.TestUtilities.TestDelegates.ThrowsNullReferenceException().
BaseExceptionThrown()
void NUnit.Framework.Assertions.AssertThrowsTests.BaseExceptionThrown () inline
References NUnit.Framework.Assertions.AssertThrowsTests.CatchException(), NUnit.Env.NewLine, NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), NUnit.Framework.Assert.Throws(), and NUnit.TestUtilities.TestDelegates.ThrowsSystemException().
DerivedExceptionThrown()
void NUnit.Framework.Assertions.AssertThrowsTests.DerivedExceptionThrown () inline
References NUnit.Framework.Assertions.AssertThrowsTests.CatchException(), NUnit.Env.NewLine, NUnit.Framework.Does.StartWith(), NUnit.Framework.Assert.That(), NUnit.Framework.Assert.Throws(), and NUnit.TestUtilities.TestDelegates.ThrowsArgumentException().
DoesNotThrowSuceeds()
void NUnit.Framework.Assertions.AssertThrowsTests.DoesNotThrowSuceeds () inline
References NUnit.Framework.Assert.DoesNotThrow(), and NUnit.TestUtilities.TestDelegates.ThrowsNothing().
DoesNotThrowFails()
void NUnit.Framework.Assertions.AssertThrowsTests.DoesNotThrowFails () inline
References NUnit.Framework.Assertions.AssertThrowsTests.CatchException(), NUnit.Framework.Assert.DoesNotThrow(), NUnit.Framework.Is.Not, NUnit.Framework.Assert.That(), and NUnit.TestUtilities.TestDelegates.ThrowsArgumentException().
CatchException()
Exception NUnit.Framework.Assertions.AssertThrowsTests.CatchException (TestDelegate del) inline private
Referenced by NUnit.Framework.Assertions.AssertThrowsTests.BaseExceptionThrown(), NUnit.Framework.Assertions.AssertThrowsTests.DerivedExceptionThrown(), NUnit.Framework.Assertions.AssertThrowsTests.DoesNotThrowFails(), NUnit.Framework.Assertions.AssertThrowsTests.NoExceptionThrown(), and NUnit.Framework.Assertions.AssertThrowsTests.UnrelatedExceptionThrown().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/AssertThrowsTests.cs