Doc: IGLib EXTENDED: NUnit.Engine.Tests.RuntimeFrameworkTests Class Reference
NUnit.Engine.Tests.RuntimeFrameworkTests Class Reference
Classes
struct FrameworkData
Public Member Functions
void CanGetCurrentFramework ()
void CurrentFrameworkHasBuildSpecified ()
void CurrentFrameworkMustBeAvailable ()
void CanListAvailableFrameworks ()
void CanCreateUsingFrameworkVersion (FrameworkData data)
void CanCreateUsingClrVersion (FrameworkData data)
void CanParseRuntimeFramework (FrameworkData data)
void CanDisplayFrameworkAsString (FrameworkData data)
bool CanMatchRuntimes (RuntimeFramework f1, RuntimeFramework f2)
Static Private Attributes
static RuntimeType currentRuntime
static TestCaseData[] matchData
static FrameworkData[] frameworkData
Member Function Documentation
CanGetCurrentFramework()
void NUnit.Engine.Tests.RuntimeFrameworkTests.CanGetCurrentFramework () inline
References NUnit.Framework.Internal.RuntimeFramework.ClrVersion, NUnit.Framework.Internal.RuntimeFramework.CurrentFramework, NUnit.Engine.Tests.RuntimeFrameworkTests.currentRuntime, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.RuntimeFramework.Runtime, and NUnit.Framework.Assert.That().
CurrentFrameworkHasBuildSpecified()
void NUnit.Engine.Tests.RuntimeFrameworkTests.CurrentFrameworkHasBuildSpecified () inline
References NUnit.Framework.Internal.RuntimeFramework.ClrVersion, NUnit.Framework.Internal.RuntimeFramework.CurrentFramework, NUnit.Framework.Is.GreaterThan(), and NUnit.Framework.Assert.That().
CurrentFrameworkMustBeAvailable()
void NUnit.Engine.Tests.RuntimeFrameworkTests.CurrentFrameworkMustBeAvailable () inline
References NUnit.Framework.Internal.RuntimeFramework.CurrentFramework, and NUnit.Framework.Assert.That().
CanListAvailableFrameworks()
void NUnit.Engine.Tests.RuntimeFrameworkTests.CanListAvailableFrameworks () inline
References NUnit.Framework.Internal.RuntimeFramework.CurrentFramework, NUnit.Framework.Internal.RuntimeFramework.DisplayName, NUnit.Framework.Has.Length, NUnit.Framework.Internal.RuntimeFramework.Supports(), and NUnit.Framework.Assert.That().
CanCreateUsingFrameworkVersion()
void NUnit.Engine.Tests.RuntimeFrameworkTests.CanCreateUsingFrameworkVersion (FrameworkData data) inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Tests.RuntimeFrameworkTests.FrameworkData.clrVersion, NUnit.Framework.Internal.RuntimeFramework.ClrVersion, NUnit.Engine.Tests.RuntimeFrameworkTests.FrameworkData.frameworkVersion, NUnit.Framework.Internal.RuntimeFramework.FrameworkVersion, NUnit.Engine.Tests.RuntimeFrameworkTests.FrameworkData.runtime, and NUnit.Framework.Internal.RuntimeFramework.Runtime.
CanCreateUsingClrVersion()
void NUnit.Engine.Tests.RuntimeFrameworkTests.CanCreateUsingClrVersion (FrameworkData data) inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Tests.RuntimeFrameworkTests.FrameworkData.clrVersion, NUnit.Framework.Internal.RuntimeFramework.ClrVersion, NUnit.Engine.Tests.RuntimeFrameworkTests.FrameworkData.frameworkVersion, NUnit.Framework.Internal.RuntimeFramework.FrameworkVersion, NUnit.Engine.Tests.RuntimeFrameworkTests.FrameworkData.runtime, NUnit.Framework.Internal.RuntimeFramework.Runtime, and NUnit.Framework.Assume.That().
CanParseRuntimeFramework()
void NUnit.Engine.Tests.RuntimeFrameworkTests.CanParseRuntimeFramework (FrameworkData data) inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Tests.RuntimeFrameworkTests.FrameworkData.clrVersion, NUnit.Framework.Internal.RuntimeFramework.ClrVersion, NUnit.Framework.Internal.RuntimeFramework.Parse(), NUnit.Engine.Tests.RuntimeFrameworkTests.FrameworkData.representation, NUnit.Engine.Tests.RuntimeFrameworkTests.FrameworkData.runtime, and NUnit.Framework.Internal.RuntimeFramework.Runtime.
CanDisplayFrameworkAsString()
void NUnit.Engine.Tests.RuntimeFrameworkTests.CanDisplayFrameworkAsString (FrameworkData data) inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Tests.RuntimeFrameworkTests.FrameworkData.displayName, NUnit.Framework.Internal.RuntimeFramework.DisplayName, NUnit.Engine.Tests.RuntimeFrameworkTests.FrameworkData.frameworkVersion, NUnit.Engine.Tests.RuntimeFrameworkTests.FrameworkData.representation, NUnit.Engine.Tests.RuntimeFrameworkTests.FrameworkData.runtime, and NUnit.Framework.Internal.RuntimeFramework.ToString().
CanMatchRuntimes()
bool NUnit.Engine.Tests.RuntimeFrameworkTests.CanMatchRuntimes (RuntimeFramework f1, RuntimeFramework f2) inline
References NUnit.Framework.Internal.RuntimeFramework.Supports().
Member Data Documentation
currentRuntime
RuntimeType NUnit.Engine.Tests.RuntimeFrameworkTests.currentRuntime static private
Initial value:
=
            Type.GetType("Mono.Runtime", false) != null
                ? RuntimeType.Mono
                : Environment.OSVersion.Platform == PlatformID.WinCE
                    ? RuntimeType.NetCF
                    : RuntimeType.Net
Referenced by NUnit.Engine.Tests.RuntimeFrameworkTests.CanGetCurrentFramework().
matchData
TestCaseData [] NUnit.Engine.Tests.RuntimeFrameworkTests.matchData static private
frameworkData
FrameworkData [] NUnit.Engine.Tests.RuntimeFrameworkTests.frameworkData static private
Initial value:
= new FrameworkData[] {
            new FrameworkData(RuntimeType.Net, new Version(1,0), new Version(1,0,3705), "net-1.0", "Net 1.0"),
            new FrameworkData(RuntimeType.Net, new Version(1,1), new Version(1,1,4322), "net-1.1", "Net 1.1"),
            new FrameworkData(RuntimeType.Net, new Version(2,0), new Version(2,0,50727), "net-2.0", "Net 2.0"),
            new FrameworkData(RuntimeType.Net, new Version(3,0), new Version(2,0,50727), "net-3.0", "Net 3.0"),
            new FrameworkData(RuntimeType.Net, new Version(3,5), new Version(2,0,50727), "net-3.5", "Net 3.5"),
            new FrameworkData(RuntimeType.Net, new Version(4,0), new Version(4,0,30319), "net-4.0", "Net 4.0"),
            new FrameworkData(RuntimeType.Net, RuntimeFramework.DefaultVersion, RuntimeFramework.DefaultVersion, "net", "Net"),
            new FrameworkData(RuntimeType.Mono, new Version(1,0), new Version(1,1,4322), "mono-1.0", "Mono 1.0"),
            new FrameworkData(RuntimeType.Mono, new Version(2,0), new Version(2,0,50727), "mono-2.0", "Mono 2.0"),
            new FrameworkData(RuntimeType.Mono, new Version(3,5), new Version(2,0,50727), "mono-3.5", "Mono 3.5"),
            new FrameworkData(RuntimeType.Mono, new Version(4,0), new Version(4,0,30319), "mono-4.0", "Mono 4.0"),
            new FrameworkData(RuntimeType.Mono, RuntimeFramework.DefaultVersion, RuntimeFramework.DefaultVersion, "mono", "Mono"),
            new FrameworkData(RuntimeType.Any, new Version(1,1), new Version(1,1,4322), "v1.1", "v1.1"),
            new FrameworkData(RuntimeType.Any, new Version(2,0), new Version(2,0,50727), "v2.0", "v2.0"),
            new FrameworkData(RuntimeType.Any, new Version(3,5), new Version(2,0,50727), "v3.5", "v3.5"),
            new FrameworkData(RuntimeType.Any, new Version(4,0), new Version(4,0,30319), "v4.0", "v4.0"),
            new FrameworkData(RuntimeType.Any, RuntimeFramework.DefaultVersion, RuntimeFramework.DefaultVersion, "any", "Any")
        }
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/RuntimeFrameworkTests.cs