Doc: IGLib EXTENDED: AForge.Math.Geometry.Posit Class Reference
AForge.Math.Geometry.Posit Class Reference
3D pose estimation algorithm.
Public Member Functions
Posit (Vector3[] model, float focalLength)
Initializes a new instance of the Posit class.
void EstimatePose (Point[] points, out Matrix3x3 rotation, out Vector3 translation)
Estimate pose of a model from it's projected 2D coordinates.
Properties
Vector3[] Model [get]
Coordinates of the model points which pose should be estimated.
float FocalLength [get, set]
Effective focal length of the camera used to capture the model.
Private Attributes
float focalLength
Vector3[] modelPoints
Matrix3x3 modelVectors
Matrix3x3 modelPseudoInverse
Static Private Attributes
const float stop_epsilon = 1.0e-4f
Detailed Description
3D pose estimation algorithm.
The class implements an algorithm for 3D object's pose estimation from it's 2D coordinates obtained by perspective projection, when the object is described none coplanar points. The idea of the implemented math and algorithm is described in "Model-Based Object Pose in 25 Lines of Code" paper written by Daniel F. DeMenthon and Larry S. Davis (the implementation of the algorithm is almost 1 to 1 translation of the pseudo code given by the paper, so should be easy to follow).
<note>At this point the implementation works only with models described by 4 points, which is the minimum number of points enough for 3D pose estimation.</note>
<note>The 4 model's point must not be coplanar, i.e. must not reside all within same planer. See CoplanarPosit for coplanar case.</note>
Read 3D Pose Estimation article for additional information and samples.
Sample usage:
// points of real object - model
Vector3[] positObject = new Vector3[4]
{
    new Vector3(  28,  28, -28 ),
    new Vector3( -28,  28, -28 ),
    new Vector3(  28, -28, -28 ),
    new Vector3(  28,  28,  28 ),
};
// focal length of camera used to capture the object
float focalLength = 640; // depends on your camera or projection system
// initialize POSIT object
Posit posit = new Posit(positObject, focalLength);
// 2D points of te object - projection
AForge.Point[] projectedPoints = new AForge.Point[4]
{
    new AForge.Point(   -4,   29 ),
    new AForge.Point( -180,   86 ),
    new AForge.Point(   -5, -102 ),
    new AForge.Point(   76,  137 ),
};
// estimate pose
Matrix3x3 rotationMatrix;
Vector3 translationVector;
posit.EstimatePose(projectedPoints,
    out rotationMatrix, out translationVector );
See also
CoplanarPosit
Constructor & Destructor Documentation
Posit()
AForge.Math.Geometry.Posit.Posit (Vector3[] model, float focalLength) inline
Initializes a new instance of the Posit class.
Parameters
model Array of vectors containing coordinates of four real model's point (points must not be on the same plane).
focalLength Effective focal length of the camera used to capture the model.
Exceptions
ArgumentException The model must have 4 points.
References AForge.Math.Matrix3x3.CreateFromRows(), AForge.Math.Geometry.Posit.focalLength, AForge.Math.Geometry.Posit.modelPoints, AForge.Math.Geometry.Posit.modelPseudoInverse, AForge.Math.Geometry.Posit.modelVectors, and AForge.Math.Matrix3x3.PseudoInverse().
Member Function Documentation
EstimatePose()
void AForge.Math.Geometry.Posit.EstimatePose (Point[] points, out Matrix3x3 rotation, out Vector3 translation) inline
Estimate pose of a model from it's projected 2D coordinates.
Parameters
points 4 2D points of the model's projection.
rotation Gets object's rotation.
translation Gets object's translation.
Exceptions
ArgumentException 4 points must be be given for pose estimation.
References AForge.Math.Matrix3x3.CreateFromRows(), AForge.Math.Vector3.Cross(), AForge.Math.Geometry.Posit.focalLength, AForge.Math.Geometry.Posit.modelPoints, AForge.Math.Geometry.Posit.modelPseudoInverse, AForge.Math.Geometry.Posit.modelVectors, AForge.Math.Vector3.Normalize(), AForge.Math.Geometry.Posit.stop_epsilon, AForge.Math.Vector3.X, AForge.Math.Vector3.Y, and AForge.Point.Y.
Referenced by PoseEstimation.MainForm.EstimatePose().
Member Data Documentation
focalLength
float AForge.Math.Geometry.Posit.focalLength private
Referenced by AForge.Math.Geometry.Posit.EstimatePose(), and AForge.Math.Geometry.Posit.Posit().
modelPoints
Vector3 [] AForge.Math.Geometry.Posit.modelPoints private
Referenced by AForge.Math.Geometry.Posit.EstimatePose(), and AForge.Math.Geometry.Posit.Posit().
modelVectors
Matrix3x3 AForge.Math.Geometry.Posit.modelVectors private
Referenced by AForge.Math.Geometry.Posit.EstimatePose(), and AForge.Math.Geometry.Posit.Posit().
modelPseudoInverse
Matrix3x3 AForge.Math.Geometry.Posit.modelPseudoInverse private
Referenced by AForge.Math.Geometry.Posit.EstimatePose(), and AForge.Math.Geometry.Posit.Posit().
stop_epsilon
const float AForge.Math.Geometry.Posit.stop_epsilon = 1.0e-4f static private
Referenced by AForge.Math.Geometry.Posit.EstimatePose().
Property Documentation
Model
Vector3 [] AForge.Math.Geometry.Posit.Model get
Coordinates of the model points which pose should be estimated.
FocalLength
float AForge.Math.Geometry.Posit.FocalLength get set
Effective focal length of the camera used to capture the model.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Math/Geometry/POSIT.cs