Doc: IGLib EXTENDED: Animat.CellWorld Class Reference
Animat.CellWorld Class Reference
Public Member Functions
CellWorld ()
Protected Member Functions
override void OnPaint (PaintEventArgs pe)
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
int[,] Map [get, set]
World's map
Color[] Coloring [get, set]
World's coloring
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Pen blackPen = new Pen(Color.Black)
Brush whiteBrush = new SolidBrush(Color.White)
int[,] map = null
Color[] coloring = null
System.ComponentModel.IContainer components = null
Required designer variable.
Constructor & Destructor Documentation
CellWorld()
Animat.CellWorld.CellWorld () inline
References Animat.CellWorld.InitializeComponent().
Member Function Documentation
OnPaint()
override void Animat.CellWorld.OnPaint (PaintEventArgs pe) inline protected
References Animat.CellWorld.blackPen, Animat.CellWorld.coloring, Animat.CellWorld.map, and Animat.CellWorld.whiteBrush.
Dispose()
override void Animat.CellWorld.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References Animat.CellWorld.components.
InitializeComponent()
void Animat.CellWorld.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by Animat.CellWorld.CellWorld().
Member Data Documentation
blackPen
Pen Animat.CellWorld.blackPen = new Pen(Color.Black) private
Referenced by Animat.CellWorld.OnPaint().
whiteBrush
Brush Animat.CellWorld.whiteBrush = new SolidBrush(Color.White) private
Referenced by Animat.CellWorld.OnPaint().
map
int [,] Animat.CellWorld.map = null private
Referenced by Animat.CellWorld.OnPaint().
coloring
Color [] Animat.CellWorld.coloring = null private
Referenced by Animat.CellWorld.OnPaint().
components
System.ComponentModel.IContainer Animat.CellWorld.components = null private
Required designer variable.
Referenced by Animat.CellWorld.Dispose().
Property Documentation
Map
int [,] Animat.CellWorld.Map get set
World's map
Referenced by Animat.MainForm.InitializeComponent(), Animat.MainForm.loadButton_Click(), and Animat.MainForm.ShowSolutionThread().
Coloring
Color [] Animat.CellWorld.Coloring get set
World's coloring
Referenced by Animat.MainForm.InitializeComponent(), and Animat.MainForm.MainForm().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/MachineLearning/Animat/CellWorld.cs
shelldev/lib_ann/aforge.net/Samples/MachineLearning/Animat/CellWorld.Designer.cs