Doc: IGLib EXTENDED: AForge.Math.Geometry.GeometryTools Class Reference
AForge.Math.Geometry.GeometryTools Class Reference
Collection of some gemetry tool methods.
Static Public Member Functions
static float GetAngleBetweenVectors (Point startPoint, Point vector1end, Point vector2end)
Calculate angle between to vectors measured in [0, 180] degrees range.
static float GetAngleBetweenLines (Point a1, Point a2, Point b1, Point b2)
Calculate minimum angle between two lines measured in [0, 90] degrees range.
Detailed Description
Collection of some gemetry tool methods.
Member Function Documentation
GetAngleBetweenVectors()
static float AForge.Math.Geometry.GeometryTools.GetAngleBetweenVectors (Point startPoint, Point vector1end, Point vector2end) inline static
Calculate angle between to vectors measured in [0, 180] degrees range.
Parameters
startPoint Starting point of both vectors.
vector1end Ending point of the first vector.
vector2end Ending point of the second vector.
Returns
Returns angle between specified vectors measured in degrees.
References AForge.Point.X, and AForge.Point.Y.
Referenced by AForge.Math.Geometry.SimpleShapeChecker.CheckPolygonSubType(), AForge.Math.Geometry.Tests.GeometryToolsTest.GetAngleBetweenVectorsTest(), AForge.Math.Geometry.CoplanarPosit.GetError(), and AForge.Math.Geometry.FlatAnglesOptimizer.OptimizeShape().
GetAngleBetweenLines()
static float AForge.Math.Geometry.GeometryTools.GetAngleBetweenLines (Point a1, Point a2, Point b1, Point b2) inline static
Calculate minimum angle between two lines measured in [0, 90] degrees range.
Parameters
a1 A point on the first line.
a2 Another point on the first line.
b1 A point on the second line.
b2 Another point on the second line.
Returns
Returns minimum angle between two lines.
<note>It is preferred to use Line.GetAngleBetweenLines if it is required to calculate angle multiple times for one of the lines.</note>
Exceptions
ArgumentException a1 and a2 are the same, -OR- b1 and b2 are the same.
References AForge.Math.Geometry.Line.FromPoints(), and AForge.Math.Geometry.Line.GetAngleBetweenLines().
Referenced by AForge.Math.Geometry.SimpleShapeChecker.CheckPolygonSubType(), and AForge.Math.Geometry.Tests.GeometryToolsTest.GetAngleBetweenLinesTest().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Math/Geometry/GeometryTools.cs