Doc: IGLib EXTENDED: NUnit.Framework.Attributes.ThreadingTests Class Reference
NUnit.Framework.Attributes.ThreadingTests Class Reference
Public Member Functions
void GetParentThreadInfo ()
Static Protected Member Functions
static ApartmentState GetApartmentState (Thread thread)
Properties
Thread ParentThread [get, private set]
ApartmentState ParentThreadApartment [get, private set]
Member Function Documentation
GetParentThreadInfo()
void NUnit.Framework.Attributes.ThreadingTests.GetParentThreadInfo () inline
References NUnit.Framework.Attributes.ThreadingTests.GetApartmentState(), NUnit.Framework.Attributes.ThreadingTests.ParentThread, and NUnit.Framework.Attributes.ThreadingTests.ParentThreadApartment.
GetApartmentState()
static ApartmentState NUnit.Framework.Attributes.ThreadingTests.GetApartmentState (Thread thread) inline static protected
Referenced by NUnit.Framework.Attributes.ThreadingTests.GetParentThreadInfo(), NUnit.Framework.Attributes.ApartmentAttributeTests.FixtureRequiresMTA.RequiresMTACanBeSetOnTestFixture(), NUnit.Framework.Attributes.ApartmentAttributeTests.FixtureRequiresSTA.RequiresSTACanBeSetOnTestFixture(), NUnit.Framework.Attributes.ApartmentAttributeTests.TestWithRequiresMTARunsInMTA(), NUnit.Framework.Attributes.ApartmentAttributeTests.TestWithRequiresSTARunsInSTA(), NUnit.Framework.Attributes.RequiresThreadAttributeTests.TestWithRequiresThreadWithMTAArgRunsOnSeparateThreadInMTA(), and NUnit.Framework.Attributes.RequiresThreadAttributeTests.TestWithRequiresThreadWithSTAArgRunsOnSeparateThreadInSTA().
Property Documentation
ParentThread
Thread NUnit.Framework.Attributes.ThreadingTests.ParentThread get private set protected
Referenced by NUnit.Framework.Attributes.ThreadingTests.GetParentThreadInfo(), NUnit.Framework.Attributes.ApartmentAttributeTests.TestWithRequiresMTARunsInMTA(), NUnit.Framework.Attributes.ApartmentAttributeTests.TestWithRequiresSTARunsInSTA(), NUnit.Framework.Attributes.RequiresThreadAttributeTests.TestWithRequiresThreadRunsInSeparateThread(), NUnit.Framework.Attributes.RequiresThreadAttributeTests.TestWithRequiresThreadWithMTAArgRunsOnSeparateThreadInMTA(), and NUnit.Framework.Attributes.RequiresThreadAttributeTests.TestWithRequiresThreadWithSTAArgRunsOnSeparateThreadInSTA().
ParentThreadApartment
ApartmentState NUnit.Framework.Attributes.ThreadingTests.ParentThreadApartment get private set protected
Referenced by NUnit.Framework.Attributes.ThreadingTests.GetParentThreadInfo(), NUnit.Framework.Attributes.ApartmentAttributeTests.TestWithRequiresMTARunsInMTA(), and NUnit.Framework.Attributes.ApartmentAttributeTests.TestWithRequiresSTARunsInSTA().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/ThreadingTests.cs