Doc: IGLib EXTENDED: alglib.wsr Class Reference
alglib.wsr Class Reference
Static Public Member Functions
static void wilcoxonsignedranktest (double[] x, int n, double e, ref double bothtails, ref double lefttail, ref double righttail)
static void wilcoxonsignedranktest (double[] x, int n, double e, ref double bothtails, ref double lefttail, ref double righttail)
Static Private Member Functions
static void wcheb (double x, double c, ref double tj, ref double tj1, ref double r)
static double w5 (double s)
static double w6 (double s)
static double w7 (double s)
static double w8 (double s)
static double w9 (double s)
static double w10 (double s)
static double w11 (double s)
static double w12 (double s)
static double w13 (double s)
static double w14 (double s)
static double w15 (double s)
static double w16 (double s)
static double w17 (double s)
static double w18 (double s)
static double w19 (double s)
static double w20 (double s)
static double w21 (double s)
static double w22 (double s)
static double w23 (double s)
static double w24 (double s)
static double w25 (double s)
static double w26 (double s)
static double w27 (double s)
static double w28 (double s)
static double w29 (double s)
static double w30 (double s)
static double w40 (double s)
static double w60 (double s)
static double w120 (double s)
static double w200 (double s)
static double wsigma (double s, int n)
static void wcheb (double x, double c, ref double tj, ref double tj1, ref double r)
static double w5 (double s)
static double w6 (double s)
static double w7 (double s)
static double w8 (double s)
static double w9 (double s)
static double w10 (double s)
static double w11 (double s)
static double w12 (double s)
static double w13 (double s)
static double w14 (double s)
static double w15 (double s)
static double w16 (double s)
static double w17 (double s)
static double w18 (double s)
static double w19 (double s)
static double w20 (double s)
static double w21 (double s)
static double w22 (double s)
static double w23 (double s)
static double w24 (double s)
static double w25 (double s)
static double w26 (double s)
static double w27 (double s)
static double w28 (double s)
static double w29 (double s)
static double w30 (double s)
static double w40 (double s)
static double w60 (double s)
static double w120 (double s)
static double w200 (double s)
static double wsigma (double s, int n)
Member Function Documentation
wilcoxonsignedranktest() [1/2]
static void alglib.wsr.wilcoxonsignedranktest (double[] x, int n, double e, ref double bothtails, ref double lefttail, ref double righttail) inline static
References alglib.wsr.wsigma().
Referenced by alglib.wilcoxonsignedranktest().
wcheb() [1/2]
static void alglib.wsr.wcheb (double x, double c, ref double tj, ref double tj1, ref double r) inline static private
Referenced by alglib.wsr.w120(), alglib.wsr.w200(), alglib.wsr.w25(), alglib.wsr.w26(), alglib.wsr.w27(), alglib.wsr.w28(), alglib.wsr.w29(), alglib.wsr.w30(), alglib.wsr.w40(), and alglib.wsr.w60().
w5() [1/2]
static double alglib.wsr.w5 (double s) inline static private
Referenced by alglib.wsr.wsigma().
w6() [1/2]
static double alglib.wsr.w6 (double s) inline static private
Referenced by alglib.wsr.wsigma().
w7() [1/2]
static double alglib.wsr.w7 (double s) inline static private
Referenced by alglib.wsr.wsigma().
w8() [1/2]
static double alglib.wsr.w8 (double s) inline static private
Referenced by alglib.wsr.wsigma().
w9() [1/2]
static double alglib.wsr.w9 (double s) inline static private
Referenced by alglib.wsr.wsigma().
w10() [1/2]
static double alglib.wsr.w10 (double s) inline static private
Referenced by alglib.wsr.wsigma().
w11() [1/2]
static double alglib.wsr.w11 (double s) inline static private
Referenced by alglib.wsr.wsigma().
w12() [1/2]
static double alglib.wsr.w12 (double s) inline static private
Referenced by alglib.wsr.wsigma().
w13() [1/2]
static double alglib.wsr.w13 (double s) inline static private
Referenced by alglib.wsr.wsigma().
w14() [1/2]
static double alglib.wsr.w14 (double s) inline static private
Referenced by alglib.wsr.wsigma().
w15() [1/2]
static double alglib.wsr.w15 (double s) inline static private
Referenced by alglib.wsr.wsigma().
w16() [1/2]
static double alglib.wsr.w16 (double s) inline static private
Referenced by alglib.wsr.wsigma().
w17() [1/2]
static double alglib.wsr.w17 (double s) inline static private
Referenced by alglib.wsr.wsigma().
w18() [1/2]
static double alglib.wsr.w18 (double s) inline static private
Referenced by alglib.wsr.wsigma().
w19() [1/2]
static double alglib.wsr.w19 (double s) inline static private
Referenced by alglib.wsr.wsigma().
w20() [1/2]
static double alglib.wsr.w20 (double s) inline static private
Referenced by alglib.wsr.wsigma().
w21() [1/2]
static double alglib.wsr.w21 (double s) inline static private
Referenced by alglib.wsr.wsigma().
w22() [1/2]
static double alglib.wsr.w22 (double s) inline static private
Referenced by alglib.wsr.wsigma().
w23() [1/2]
static double alglib.wsr.w23 (double s) inline static private
Referenced by alglib.wsr.wsigma().
w24() [1/2]
static double alglib.wsr.w24 (double s) inline static private
Referenced by alglib.wsr.wsigma().
w25() [1/2]
static double alglib.wsr.w25 (double s) inline static private
References alglib.wsr.wcheb().
Referenced by alglib.wsr.wsigma().
w26() [1/2]
static double alglib.wsr.w26 (double s) inline static private
References alglib.wsr.wcheb().
Referenced by alglib.wsr.wsigma().
w27() [1/2]
static double alglib.wsr.w27 (double s) inline static private
References alglib.wsr.wcheb().
Referenced by alglib.wsr.wsigma().
w28() [1/2]
static double alglib.wsr.w28 (double s) inline static private
References alglib.wsr.wcheb().
Referenced by alglib.wsr.wsigma().
w29() [1/2]
static double alglib.wsr.w29 (double s) inline static private
References alglib.wsr.wcheb().
Referenced by alglib.wsr.wsigma().
w30() [1/2]
static double alglib.wsr.w30 (double s) inline static private
References alglib.wsr.wcheb().
Referenced by alglib.wsr.wsigma().
w40() [1/2]
static double alglib.wsr.w40 (double s) inline static private
References alglib.wsr.wcheb().
Referenced by alglib.wsr.wsigma().
w60() [1/2]
static double alglib.wsr.w60 (double s) inline static private
References alglib.wsr.wcheb().
Referenced by alglib.wsr.wsigma().
w120() [1/2]
static double alglib.wsr.w120 (double s) inline static private
References alglib.wsr.wcheb().
Referenced by alglib.wsr.wsigma().
w200() [1/2]
static double alglib.wsr.w200 (double s) inline static private
References alglib.wsr.wcheb().
Referenced by alglib.wsr.wsigma().
wsigma() [1/2]
static double alglib.wsr.wsigma (double s, int n) inline static private
References alglib.wsr.w10(), alglib.wsr.w11(), alglib.wsr.w12(), alglib.wsr.w120(), alglib.wsr.w13(), alglib.wsr.w14(), alglib.wsr.w15(), alglib.wsr.w16(), alglib.wsr.w17(), alglib.wsr.w18(), alglib.wsr.w19(), alglib.wsr.w20(), alglib.wsr.w200(), alglib.wsr.w21(), alglib.wsr.w22(), alglib.wsr.w23(), alglib.wsr.w24(), alglib.wsr.w25(), alglib.wsr.w26(), alglib.wsr.w27(), alglib.wsr.w28(), alglib.wsr.w29(), alglib.wsr.w30(), alglib.wsr.w40(), alglib.wsr.w5(), alglib.wsr.w6(), alglib.wsr.w60(), alglib.wsr.w7(), alglib.wsr.w8(), and alglib.wsr.w9().
Referenced by alglib.wsr.wilcoxonsignedranktest().
wilcoxonsignedranktest() [2/2]
static void alglib.wsr.wilcoxonsignedranktest (double[] x, int n, double e, ref double bothtails, ref double lefttail, ref double righttail) inline static
References alglib.wsr.wsigma().
wcheb() [2/2]
static void alglib.wsr.wcheb (double x, double c, ref double tj, ref double tj1, ref double r) inline static private
w5() [2/2]
static double alglib.wsr.w5 (double s) inline static private
w6() [2/2]
static double alglib.wsr.w6 (double s) inline static private
w7() [2/2]
static double alglib.wsr.w7 (double s) inline static private
w8() [2/2]
static double alglib.wsr.w8 (double s) inline static private
w9() [2/2]
static double alglib.wsr.w9 (double s) inline static private
w10() [2/2]
static double alglib.wsr.w10 (double s) inline static private
w11() [2/2]
static double alglib.wsr.w11 (double s) inline static private
w12() [2/2]
static double alglib.wsr.w12 (double s) inline static private
w13() [2/2]
static double alglib.wsr.w13 (double s) inline static private
w14() [2/2]
static double alglib.wsr.w14 (double s) inline static private
w15() [2/2]
static double alglib.wsr.w15 (double s) inline static private
w16() [2/2]
static double alglib.wsr.w16 (double s) inline static private
w17() [2/2]
static double alglib.wsr.w17 (double s) inline static private
w18() [2/2]
static double alglib.wsr.w18 (double s) inline static private
w19() [2/2]
static double alglib.wsr.w19 (double s) inline static private
w20() [2/2]
static double alglib.wsr.w20 (double s) inline static private
w21() [2/2]
static double alglib.wsr.w21 (double s) inline static private
w22() [2/2]
static double alglib.wsr.w22 (double s) inline static private
w23() [2/2]
static double alglib.wsr.w23 (double s) inline static private
w24() [2/2]
static double alglib.wsr.w24 (double s) inline static private
w25() [2/2]
static double alglib.wsr.w25 (double s) inline static private
References alglib.wsr.wcheb().
w26() [2/2]
static double alglib.wsr.w26 (double s) inline static private
References alglib.wsr.wcheb().
w27() [2/2]
static double alglib.wsr.w27 (double s) inline static private
References alglib.wsr.wcheb().
w28() [2/2]
static double alglib.wsr.w28 (double s) inline static private
References alglib.wsr.wcheb().
w29() [2/2]
static double alglib.wsr.w29 (double s) inline static private
References alglib.wsr.wcheb().
w30() [2/2]
static double alglib.wsr.w30 (double s) inline static private
References alglib.wsr.wcheb().
w40() [2/2]
static double alglib.wsr.w40 (double s) inline static private
References alglib.wsr.wcheb().
w60() [2/2]
static double alglib.wsr.w60 (double s) inline static private
References alglib.wsr.wcheb().
w120() [2/2]
static double alglib.wsr.w120 (double s) inline static private
References alglib.wsr.wcheb().
w200() [2/2]
static double alglib.wsr.w200 (double s) inline static private
References alglib.wsr.wcheb().
wsigma() [2/2]
static double alglib.wsr.wsigma (double s, int n) inline static private
References alglib.wsr.w10(), alglib.wsr.w11(), alglib.wsr.w12(), alglib.wsr.w120(), alglib.wsr.w13(), alglib.wsr.w14(), alglib.wsr.w15(), alglib.wsr.w16(), alglib.wsr.w17(), alglib.wsr.w18(), alglib.wsr.w19(), alglib.wsr.w20(), alglib.wsr.w200(), alglib.wsr.w21(), alglib.wsr.w22(), alglib.wsr.w23(), alglib.wsr.w24(), alglib.wsr.w25(), alglib.wsr.w26(), alglib.wsr.w27(), alglib.wsr.w28(), alglib.wsr.w29(), alglib.wsr.w30(), alglib.wsr.w40(), alglib.wsr.w5(), alglib.wsr.w6(), alglib.wsr.w60(), alglib.wsr.w7(), alglib.wsr.w8(), and alglib.wsr.w9().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/statistics.cs