Doc: IGLib EXTENDED: IG.Gr3d.VtkFormPlain Class Reference
IG.Gr3d.VtkFormPlain Class Reference
Windows form for presenting VTK graphics.
Public Member Functions
VtkFormPlain ()
void ShowManipulator ()
Public Member Functions inherited from IG.Forms.IClosableFromContainedForm
void Close ()
Static Public Attributes
static bool DefaultIsManipulatorControlsButtonVisible = true
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
bool _isManipulatorControlsButtonVisible = DefaultIsManipulatorControlsButtonVisible
Graph3dManipulatorWindowExtended _manipulatorWindow
Properties
bool IsManipulatorControlsButtonVisible [get, set]
Specifies whether the button that launches manipulator controls is visible or not.
VtkControlBase VtkControl [get]
Gets the control of type VtkControlBase through which VTK functionality is controlled.
Kitware.VTK.RenderWindowControl VtkRenderWindowControl [get]
VTK's control that is actually used for rendering graphics and through which VTK can be interacted directly.
Graph3dManipulatorWindowExtended ManipulatorWindow [get]
Window that shows information about the software.
Properties inherited from IG.Gr3d.IVtkFormContainerGen< Kitware.VTK.RenderWindowControl >
VtkControlBase VtkControl [get]
Base windows forms control through which the basic VTK functionality and all additional features can be accessed.
VtkControlType VtkRenderWindowControl [get]
VTK's control that is actually used for rendering graphics and through which VTK can be interacted directly.
Private Member Functions
void VtkFormPlain_HelpEventHandlers (object sender, KeyEventArgs e)
Used to handle key up events that launch the manipulator window that has controls for rotating 3D graphics, zooming, and others.
void VtkFormPlain_KeyUp (object sender, KeyEventArgs e)
Key up event.
void btnManipulatorControls_Click (object sender, EventArgs e)
Opens window with manipulator controls for manipulation of graphics (rotation, etc.).
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
VtkControlBase _vtkControl
Kitware.VTK.RenderWindowControl _vtkRenderWindowControl
System.ComponentModel.IContainer components = null
Required designer variable.
VtkControlBase vtkControlWin1
System.Windows.Forms.Button btnManipulatorControls
Detailed Description
Windows form for presenting VTK graphics.
Contains some additional buttons beside just the VTK renderer control.
This is a toplevel form that only contains a control of type VtkControlWin, which handles all VTK related stuff.
$A Igor May13;
Constructor & Destructor Documentation
VtkFormPlain()
IG.Gr3d.VtkFormPlain.VtkFormPlain () inline
References IG.Gr3d.VtkFormPlain.btnManipulatorControls, IG.Gr3d.VtkFormPlain.InitializeComponent(), IG.Gr3d.VtkControlBase.InitializeState(), IG.Gr3d.VtkFormPlain.IsManipulatorControlsButtonVisible, and IG.Gr3d.VtkFormPlain.VtkControl.
Member Function Documentation
ShowManipulator()
void IG.Gr3d.VtkFormPlain.ShowManipulator () inline
References IG.Gr3d.VtkFormPlain.VtkControl.
Referenced by IG.Gr3d.VtkFormPlain.btnManipulatorControls_Click(), and IG.Gr3d.VtkFormPlain.VtkFormPlain_HelpEventHandlers().
VtkFormPlain_HelpEventHandlers()
void IG.Gr3d.VtkFormPlain.VtkFormPlain_HelpEventHandlers (object sender, KeyEventArgs e) inline private
Used to handle key up events that launch the manipulator window that has controls for rotating 3D graphics, zooming, and others.
Parameters
sender
e
References IG.Gr3d.VtkFormPlain.ShowManipulator().
Referenced by IG.Gr3d.VtkFormPlain.VtkFormPlain_KeyUp().
VtkFormPlain_KeyUp()
void IG.Gr3d.VtkFormPlain.VtkFormPlain_KeyUp (object sender, KeyEventArgs e) inline private
Key up event.
References IG.Gr3d.VtkFormPlain.VtkFormPlain_HelpEventHandlers().
btnManipulatorControls_Click()
void IG.Gr3d.VtkFormPlain.btnManipulatorControls_Click (object sender, EventArgs e) inline private
Opens window with manipulator controls for manipulation of graphics (rotation, etc.).
References IG.Gr3d.VtkFormPlain.ShowManipulator().
Referenced by IG.Gr3d.VtkFormPlain.InitializeComponent().
Dispose()
override void IG.Gr3d.VtkFormPlain.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Gr3d.VtkFormPlain.components.
InitializeComponent()
void IG.Gr3d.VtkFormPlain.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Gr3d.VtkFormPlain.btnManipulatorControls, IG.Gr3d.VtkFormPlain.btnManipulatorControls_Click(), IG.Gr3d.VtkControlBase.CameraRoll, IG.Gr3d.VtkControlBase.CameraViewAngle, IG.Gr3d.VtkControlBase.IsActorsMode, IG.Gr3d.VtkControlBase.IsCameraMode, IG.Gr3d.VtkControlBase.IsJoystickMode, IG.Gr3d.VtkControlBase.IsSurfaceMode, IG.Gr3d.VtkControlBase.IsTrackballMode, IG.Gr3d.VtkControlBase.IsWireframeMode, IG.Gr3d.VtkControlBase.RotationStep, IG.Gr3d.VtkControlBase.VtkAddTestActors, IG.Gr3d.VtkControlBase.VtkAddTestActorsIGLib, IG.Gr3d.VtkFormPlain.vtkControlWin1, and IG.Gr3d.VtkControlBase.ZoomFactor.
Referenced by IG.Gr3d.VtkFormPlain.VtkFormPlain().
Member Data Documentation
DefaultIsManipulatorControlsButtonVisible
bool IG.Gr3d.VtkFormPlain.DefaultIsManipulatorControlsButtonVisible = true static
_isManipulatorControlsButtonVisible
bool IG.Gr3d.VtkFormPlain._isManipulatorControlsButtonVisible = DefaultIsManipulatorControlsButtonVisible protected
_vtkControl
VtkControlBase IG.Gr3d.VtkFormPlain._vtkControl private
_vtkRenderWindowControl
Kitware.VTK.RenderWindowControl IG.Gr3d.VtkFormPlain._vtkRenderWindowControl private
_manipulatorWindow
Graph3dManipulatorWindowExtended IG.Gr3d.VtkFormPlain._manipulatorWindow protected
components
System.ComponentModel.IContainer IG.Gr3d.VtkFormPlain.components = null private
Required designer variable.
Referenced by IG.Gr3d.VtkFormPlain.Dispose().
vtkControlWin1
VtkControlBase IG.Gr3d.VtkFormPlain.vtkControlWin1 private
Referenced by IG.Gr3d.VtkFormPlain.InitializeComponent().
btnManipulatorControls
System.Windows.Forms.Button IG.Gr3d.VtkFormPlain.btnManipulatorControls private
Referenced by IG.Gr3d.VtkFormPlain.InitializeComponent(), and IG.Gr3d.VtkFormPlain.VtkFormPlain().
Property Documentation
IsManipulatorControlsButtonVisible
bool IG.Gr3d.VtkFormPlain.IsManipulatorControlsButtonVisible get set
Specifies whether the button that launches manipulator controls is visible or not.
If true, a small button sows in the bottom-right corner of the VTK plotting area.
Referenced by IG.Gr3d.VtkFormPlain.VtkFormPlain().
VtkControl
VtkControlBase IG.Gr3d.VtkFormPlain.VtkControl get
Gets the control of type VtkControlBase through which VTK functionality is controlled.
Referenced by IG.Gr3d.VtkFormPlain.ShowManipulator(), and IG.Gr3d.VtkFormPlain.VtkFormPlain().
VtkRenderWindowControl
Kitware.VTK.RenderWindowControl IG.Gr3d.VtkFormPlain.VtkRenderWindowControl get
VTK's control that is actually used for rendering graphics and through which VTK can be interacted directly.
Instead of accessing this control directly, you should normally access it through the VtkControlBase.VtkControl property of the VtkControl property.
ManipulatorWindow
Graph3dManipulatorWindowExtended IG.Gr3d.VtkFormPlain.ManipulatorWindow get
Window that shows information about the software.
Help is also accessible through that window.
The documentation for this class was generated from the following files:
iglib/extensions/igplot3d/plot3d/vtkbased/Forms/VtkFormPlain.cs
iglib/extensions/igplot3d/plot3d/vtkbased/Forms/VtkFormPlain.Designer.cs