Doc: IGLib EXTENDED: IG.Forms.WindowPositionerControl Class Reference
IG.Forms.WindowPositionerControl Class Reference
Control for testing window positioning.
Public Member Functions
WindowPositionerControl ()
Constructs a new positioner form with undefined positioner, positioned window and master window.
WindowPositionerControl (Form positionedWindow, Form masterWindow)
Constructs a new positioner form with unspecified positioner and specified positioned window and master window.
WindowPositionerControl (Form positionedWindow)
Constructs a new positioner form with unspecified positioner and master window, and specified positioned window.
WindowPositionerControl (WindowPositioner positioner)
Constructs a new positioner form with the specified positioner and undefined positioned window and master window.
WindowPositionerControl (WindowPositioner positioner, Form positionedWindow)
Constructs a new positioner form with the specified positioner and positioned window, and undefined master window.
WindowPositionerControl (WindowPositioner positioner, Form positionedWindow, Form masterWindow)
Constructs a new positioner form with the specified positioner, positioned window and master window.
double DoubleVal (string str, double defaultValue)
Converts string to double and returns the value.
double DoubleVal (string str)
Converts string to double and returns the value (or 0 if conversion was not successful).
void CopyDataToPositioner ()
Copies data from the form to positioner.
void CopyDataFromPositioner ()
void LaunchWindows ()
void MakeWindowsVisible ()
WindowPositionerControl ()
Constructs a new positioner form with undefined positioner, positioned window and master window.
WindowPositionerControl (Form positionedWindow, Form masterWindow)
Constructs a new positioner form with unspecified positioner and specified positioned window and master window.
WindowPositionerControl (Form positionedWindow)
Constructs a new positioner form with unspecified positioner and master window, and specified positioned window.
WindowPositionerControl (WindowPositioner positioner)
Constructs a new positioner form with the specified positioner and undefined positioned window and master window.
WindowPositionerControl (WindowPositioner positioner, Form positionedWindow)
Constructs a new positioner form with the specified positioner and positioned window, and undefined master window.
WindowPositionerControl (WindowPositioner positioner, Form positionedWindow, Form masterWindow)
Constructs a new positioner form with the specified positioner, positioned window and master window.
double DoubleVal (string str, double defaultValue)
Converts string to double and returns the value.
double DoubleVal (string str)
Converts string to double and returns the value (or 0 if conversion was not successful).
void CopyDataToPositioner ()
Copies data from the form to positioner.
void CopyDataFromPositioner ()
void LaunchWindows ()
void MakeWindowsVisible ()
WindowPositionerControl ()
Constructs a new positioner form with undefined positioner, positioned window and master window.
WindowPositionerControl (Form positionedWindow, Form masterWindow)
Constructs a new positioner form with unspecified positioner and specified positioned window and master window.
WindowPositionerControl (Form positionedWindow)
Constructs a new positioner form with unspecified positioner and master window, and specified positioned window.
WindowPositionerControl (WindowPositioner positioner)
Constructs a new positioner form with the specified positioner and undefined positioned window and master window.
WindowPositionerControl (WindowPositioner positioner, Form positionedWindow)
Constructs a new positioner form with the specified positioner and positioned window, and undefined master window.
WindowPositionerControl (WindowPositioner positioner, Form positionedWindow, Form masterWindow)
Constructs a new positioner form with the specified positioner, positioned window and master window.
double DoubleVal (string str, double defaultValue)
Converts string to double and returns the value.
double DoubleVal (string str)
Converts string to double and returns the value (or 0 if conversion was not successful).
void CopyDataToPositioner ()
Copies data from the form to positioner.
void CopyDataFromPositioner ()
void LaunchWindows ()
void MakeWindowsVisible ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
WindowPositioner _positioner
Form _window
Form _masterWindow
Properties
WindowPositioner Positioner [get, set]
Window positioner.
Form Window [get, set]
Window to be positioned.
Form MasterWindow [get, set]
Master window relative to which position is set.
string Title [get]
Private Member Functions
void btnLaunchWindows_Click (object sender, EventArgs e)
Launches the master window and the window to be positioned.
void btnPositionWindows_Click (object sender, EventArgs e)
Launches the master window and the window to be positioned.
void btnRememberPosition_Click (object sender, EventArgs e)
void btnStickToMaster_Click (object sender, EventArgs e)
void btnUnStickFromMaster_Click (object sender, EventArgs e)
void txtMasterWeight_Enter (object sender, EventArgs e)
void txtPause_Validated (object sender, EventArgs e)
void txtPause_Enter (object sender, EventArgs e)
void chkRememberPositions_CheckedChanged (object sender, EventArgs e)
void btnRefreshData_Click (object sender, EventArgs e)
void btnUpdate_Click (object sender, EventArgs e)
void WindowPositionerControl_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void btnLaunchWindows_Click (object sender, EventArgs e)
Launches the master window and the window to be positioned.
void btnPositionWindows_Click (object sender, EventArgs e)
Launches the master window and the window to be positioned.
void btnRememberPosition_Click (object sender, EventArgs e)
void btnStickToMaster_Click (object sender, EventArgs e)
void btnUnStickFromMaster_Click (object sender, EventArgs e)
void txtMasterWeight_Enter (object sender, EventArgs e)
void txtPause_Validated (object sender, EventArgs e)
void txtPause_Enter (object sender, EventArgs e)
void chkRememberPositions_CheckedChanged (object sender, EventArgs e)
void btnRefreshData_Click (object sender, EventArgs e)
void btnUpdate_Click (object sender, EventArgs e)
void WindowPositionerControl_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void btnLaunchWindows_Click (object sender, EventArgs e)
Launches the master window and the window to be positioned.
void btnPositionWindows_Click (object sender, EventArgs e)
Launches the master window and the window to be positioned.
void btnRememberPosition_Click (object sender, EventArgs e)
void btnStickToMaster_Click (object sender, EventArgs e)
void btnUnStickFromMaster_Click (object sender, EventArgs e)
void txtMasterWeight_Enter (object sender, EventArgs e)
void txtPause_Validated (object sender, EventArgs e)
void txtPause_Enter (object sender, EventArgs e)
void chkRememberPositions_CheckedChanged (object sender, EventArgs e)
void btnRefreshData_Click (object sender, EventArgs e)
void btnUpdate_Click (object sender, EventArgs e)
void WindowPositionerControl_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Label lblTitle
System.Windows.Forms.GroupBox grpGeneral
System.Windows.Forms.GroupBox grpMaster
System.Windows.Forms.GroupBox grpScreen
System.Windows.Forms.Label lblMasterWeight
System.Windows.Forms.NumericUpDown txtMasterWeight
IG.Forms.AlignmentControl alignWindow
AlignmentControl alignMaster
AlignmentControl alignScreen
WindowShiftControlText shiftWindowRel
WindowShiftControlText shiftWindowAbsolute
WindowShiftControlText shiftMasterRel
WindowShiftControlText shiftScreenRel
System.Windows.Forms.Button btnLaunchWindows
System.Windows.Forms.Button btnPositionWindows
System.Windows.Forms.Button btnStickToMaster
System.Windows.Forms.Button button1
System.Windows.Forms.TextBox txtPause
System.Windows.Forms.Label lblPause
System.Windows.Forms.Button btnRememberPosition
System.Windows.Forms.CheckBox chkRememberPositions
System.Windows.Forms.Button btnUpdate
System.Windows.Forms.Button btnRefreshData
Detailed Description
Control for testing window positioning.
$A Igor xx Oct09;
Constructor & Destructor Documentation
WindowPositionerControl() [1/18]
IG.Forms.WindowPositionerControl.WindowPositionerControl () inline
Constructs a new positioner form with undefined positioner, positioned window and master window.
WindowPositionerControl() [2/18]
IG.Forms.WindowPositionerControl.WindowPositionerControl (Form positionedWindow, Form masterWindow) inline
Constructs a new positioner form with unspecified positioner and specified positioned window and master window.
Positioner is created automatically and initialized to default state.
Parameters
positionedWindow Window that is positioned.
masterWindow Master window.
WindowPositionerControl() [3/18]
IG.Forms.WindowPositionerControl.WindowPositionerControl (Form positionedWindow) inline
Constructs a new positioner form with unspecified positioner and master window, and specified positioned window.
Positioner is created automatically and initialized to default state.
Parameters
positionedWindow Window that is positioned.
WindowPositionerControl() [4/18]
IG.Forms.WindowPositionerControl.WindowPositionerControl (WindowPositioner positioner) inline
Constructs a new positioner form with the specified positioner and undefined positioned window and master window.
Parameters
positioner Positioner object that positions the window.
WindowPositionerControl() [5/18]
IG.Forms.WindowPositionerControl.WindowPositionerControl (WindowPositioner positioner, Form positionedWindow) inline
Constructs a new positioner form with the specified positioner and positioned window, and undefined master window.
Parameters
positioner Positioner object that positions the window.
positionedWindow Window that is positioned.
WindowPositionerControl() [6/18]
IG.Forms.WindowPositionerControl.WindowPositionerControl (WindowPositioner positioner, Form positionedWindow, Form masterWindow) inline
Constructs a new positioner form with the specified positioner, positioned window and master window.
Parameters
positioner Positioner object that positions the window.
positionedWindow Window that is positioned.
masterWindow Master window.
References IG.Forms.WindowPositionerControl.InitializeComponent(), IG.Forms.WindowPositionerControl.lblTitle, IG.Forms.WindowPositionerControl.MasterWindow, IG.Forms.WindowPositionerControl.Positioner, IG.Forms.WindowPositionerControl.Title, and IG.Forms.WindowPositionerControl.Window.
WindowPositionerControl() [7/18]
IG.Forms.WindowPositionerControl.WindowPositionerControl () inline
Constructs a new positioner form with undefined positioner, positioned window and master window.
WindowPositionerControl() [8/18]
IG.Forms.WindowPositionerControl.WindowPositionerControl (Form positionedWindow, Form masterWindow) inline
Constructs a new positioner form with unspecified positioner and specified positioned window and master window.
Positioner is created automatically and initialized to default state.
Parameters
positionedWindow Window that is positioned.
masterWindow Master window.
WindowPositionerControl() [9/18]
IG.Forms.WindowPositionerControl.WindowPositionerControl (Form positionedWindow) inline
Constructs a new positioner form with unspecified positioner and master window, and specified positioned window.
Positioner is created automatically and initialized to default state.
Parameters
positionedWindow Window that is positioned.
WindowPositionerControl() [10/18]
IG.Forms.WindowPositionerControl.WindowPositionerControl (WindowPositioner positioner) inline
Constructs a new positioner form with the specified positioner and undefined positioned window and master window.
Parameters
positioner Positioner object that positions the window.
WindowPositionerControl() [11/18]
IG.Forms.WindowPositionerControl.WindowPositionerControl (WindowPositioner positioner, Form positionedWindow) inline
Constructs a new positioner form with the specified positioner and positioned window, and undefined master window.
Parameters
positioner Positioner object that positions the window.
positionedWindow Window that is positioned.
WindowPositionerControl() [12/18]
IG.Forms.WindowPositionerControl.WindowPositionerControl (WindowPositioner positioner, Form positionedWindow, Form masterWindow) inline
Constructs a new positioner form with the specified positioner, positioned window and master window.
Parameters
positioner Positioner object that positions the window.
positionedWindow Window that is positioned.
masterWindow Master window.
References IG.Forms.WindowPositionerControl.InitializeComponent(), IG.Forms.WindowPositionerControl.lblTitle, IG.Forms.WindowPositionerControl.MasterWindow, IG.Forms.WindowPositionerControl.Positioner, IG.Forms.WindowPositionerControl.Title, and IG.Forms.WindowPositionerControl.Window.
WindowPositionerControl() [13/18]
IG.Forms.WindowPositionerControl.WindowPositionerControl () inline
Constructs a new positioner form with undefined positioner, positioned window and master window.
WindowPositionerControl() [14/18]
IG.Forms.WindowPositionerControl.WindowPositionerControl (Form positionedWindow, Form masterWindow) inline
Constructs a new positioner form with unspecified positioner and specified positioned window and master window.
Positioner is created automatically and initialized to default state.
Parameters
positionedWindow Window that is positioned.
masterWindow Master window.
WindowPositionerControl() [15/18]
IG.Forms.WindowPositionerControl.WindowPositionerControl (Form positionedWindow) inline
Constructs a new positioner form with unspecified positioner and master window, and specified positioned window.
Positioner is created automatically and initialized to default state.
Parameters
positionedWindow Window that is positioned.
WindowPositionerControl() [16/18]
IG.Forms.WindowPositionerControl.WindowPositionerControl (WindowPositioner positioner) inline
Constructs a new positioner form with the specified positioner and undefined positioned window and master window.
Parameters
positioner Positioner object that positions the window.
WindowPositionerControl() [17/18]
IG.Forms.WindowPositionerControl.WindowPositionerControl (WindowPositioner positioner, Form positionedWindow) inline
Constructs a new positioner form with the specified positioner and positioned window, and undefined master window.
Parameters
positioner Positioner object that positions the window.
positionedWindow Window that is positioned.
WindowPositionerControl() [18/18]
IG.Forms.WindowPositionerControl.WindowPositionerControl (WindowPositioner positioner, Form positionedWindow, Form masterWindow) inline
Constructs a new positioner form with the specified positioner, positioned window and master window.
Parameters
positioner Positioner object that positions the window.
positionedWindow Window that is positioned.
masterWindow Master window.
References IG.Forms.WindowPositionerControl.InitializeComponent(), IG.Forms.WindowPositionerControl.lblTitle, IG.Forms.WindowPositionerControl.MasterWindow, IG.Forms.WindowPositionerControl.Positioner, IG.Forms.WindowPositionerControl.Title, and IG.Forms.WindowPositionerControl.Window.
Member Function Documentation
DoubleVal() [1/6]
double IG.Forms.WindowPositionerControl.DoubleVal (string str, double defaultValue) inline
Converts string to double and returns the value.
Parameters
str String to be converted.
defaultValue Value returned if conversion is not successful.
Referenced by IG.Forms.WindowPositionerControl.CopyDataToPositioner().
DoubleVal() [2/6]
double IG.Forms.WindowPositionerControl.DoubleVal (string str) inline
Converts string to double and returns the value (or 0 if conversion was not successful).
References IG.Forms.WindowPositionerControl.DoubleVal().
Referenced by IG.Forms.WindowPositionerControl.DoubleVal().
CopyDataToPositioner() [1/3]
void IG.Forms.WindowPositionerControl.CopyDataToPositioner () inline
Copies data from the form to positioner.
References IG.Forms.WindowPositionerControl.alignMaster, IG.Forms.AlignmentControl.Alignment, IG.Forms.WindowPositionerControl.alignScreen, IG.Forms.WindowPositionerControl.alignWindow, IG.Forms.WindowPositionerControl.DoubleVal(), IG.Forms.WindowPositioner.MasterWeight, IG.Forms.WindowPositioner.MasterWindowAlignment, IG.Forms.WindowPositioner.MasterWindowShiftRelative, IG.Forms.WindowPositioner.MovementPauseSeconds, IG.Forms.WindowPositionerControl.Positioner, IG.Forms.WindowPositioner.ScreenAlignment, IG.Forms.WindowPositioner.ScreenShiftRelative, IG.Forms.WindowShiftControlText.Shift, IG.Forms.WindowPositioner.ShiftAbsolute, IG.Forms.WindowPositionerControl.shiftMasterRel, IG.Forms.WindowPositionerControl.shiftScreenRel, IG.Forms.WindowPositionerControl.shiftWindowAbsolute, IG.Forms.WindowPositionerControl.shiftWindowRel, IG.Forms.WindowPositionerControl.txtMasterWeight, IG.Forms.WindowPositionerControl.txtPause, IG.Forms.WindowPositioner.WindowAlignment, and IG.Forms.WindowPositioner.WindowShiftRelative.
Referenced by IG.Forms.WindowPositionerControl.btnPositionWindows_Click(), IG.Forms.WindowPositionerControl.btnStickToMaster_Click(), IG.Forms.WindowPositionerControl.btnUnStickFromMaster_Click(), IG.Forms.WindowPositionerControl.btnUpdate_Click(), and IG.Forms.WindowPositionerControl.chkRememberPositions_CheckedChanged().
CopyDataFromPositioner() [1/3]
void IG.Forms.WindowPositionerControl.CopyDataFromPositioner () inline
References IG.Forms.WindowPositionerControl.alignMaster, IG.Forms.AlignmentControl.Alignment, IG.Forms.WindowPositionerControl.alignScreen, IG.Forms.WindowPositionerControl.alignWindow, IG.Forms.WindowPositioner.MasterWeight, IG.Forms.WindowPositioner.MasterWindowAlignment, IG.Forms.WindowPositioner.MasterWindowShiftRelative, IG.Forms.WindowPositioner.MovementPauseSeconds, IG.Forms.WindowPositionerControl.Positioner, IG.Forms.WindowPositioner.ScreenAlignment, IG.Forms.WindowPositioner.ScreenShiftRelative, IG.Forms.WindowShiftControlText.Shift, IG.Forms.WindowPositioner.ShiftAbsolute, IG.Forms.WindowPositionerControl.shiftMasterRel, IG.Forms.WindowPositionerControl.shiftScreenRel, IG.Forms.WindowPositionerControl.shiftWindowAbsolute, IG.Forms.WindowPositionerControl.shiftWindowRel, IG.Forms.WindowPositionerControl.txtMasterWeight, IG.Forms.WindowPositionerControl.txtPause, IG.Forms.WindowPositioner.WindowAlignment, and IG.Forms.WindowPositioner.WindowShiftRelative.
Referenced by IG.Forms.WindowPositionerControl.btnRefreshData_Click(), and IG.Forms.WindowPositionerControl.btnRememberPosition_Click().
LaunchWindows() [1/3]
void IG.Forms.WindowPositionerControl.LaunchWindows () inline
References IG.Forms.WindowPositionerControl.MakeWindowsVisible(), IG.Forms.WindowPositionerControl.MasterWindow, IG.Forms.WindowPositionerControl.Positioner, IG.Forms.WindowPositioner.ScreenBounds, and IG.Forms.WindowPositionerControl.Window.
Referenced by IG.Forms.WindowPositionerControl.btnLaunchWindows_Click(), and IG.Forms.WindowPositionerControl.WindowPositionerControl_Load().
MakeWindowsVisible() [1/3]
void IG.Forms.WindowPositionerControl.MakeWindowsVisible () inline
References IG.Forms.UtilForms.BlinkControl(), IG.Forms.WindowPositionerControl.MasterWindow, and IG.Forms.WindowPositionerControl.Window.
Referenced by IG.Forms.WindowPositionerControl.btnPositionWindows_Click(), and IG.Forms.WindowPositionerControl.LaunchWindows().
btnLaunchWindows_Click() [1/3]
void IG.Forms.WindowPositionerControl.btnLaunchWindows_Click (object sender, EventArgs e) inline private
Launches the master window and the window to be positioned.
References IG.Forms.WindowPositionerControl.LaunchWindows().
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
btnPositionWindows_Click() [1/3]
void IG.Forms.WindowPositionerControl.btnPositionWindows_Click (object sender, EventArgs e) inline private
Launches the master window and the window to be positioned.
References IG.Forms.WindowPositionerControl.CopyDataToPositioner(), IG.Forms.WindowPositionerControl.MakeWindowsVisible(), IG.Forms.WindowPositionerControl.Positioner, and IG.Forms.WindowPositioner.PositionWindow().
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
btnRememberPosition_Click() [1/3]
void IG.Forms.WindowPositionerControl.btnRememberPosition_Click (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.Positioner, and IG.Forms.WindowPositioner.SetToCurrentPosition().
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
btnStickToMaster_Click() [1/3]
void IG.Forms.WindowPositionerControl.btnStickToMaster_Click (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.CopyDataToPositioner(), IG.Forms.WindowPositionerControl.Positioner, and IG.Forms.WindowPositioner.StickToMaster().
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
btnUnStickFromMaster_Click() [1/3]
void IG.Forms.WindowPositionerControl.btnUnStickFromMaster_Click (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.CopyDataToPositioner(), IG.Forms.WindowPositionerControl.Positioner, and IG.Forms.WindowPositioner.UnStickFromMaster().
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
txtMasterWeight_Enter() [1/3]
void IG.Forms.WindowPositionerControl.txtMasterWeight_Enter (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.txtMasterWeight.
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
txtPause_Validated() [1/3]
void IG.Forms.WindowPositionerControl.txtPause_Validated (object sender, EventArgs e) inline private
References IG.Forms.UtilForms.BlinkControl(), IG.Forms.WindowPositioner.MovementPauseSeconds, IG.Forms.WindowPositionerControl.Positioner, and IG.Forms.WindowPositionerControl.txtPause.
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
txtPause_Enter() [1/3]
void IG.Forms.WindowPositionerControl.txtPause_Enter (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.txtPause.
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
chkRememberPositions_CheckedChanged() [1/3]
void IG.Forms.WindowPositionerControl.chkRememberPositions_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.chkRememberPositions, IG.Forms.WindowPositionerControl.CopyDataToPositioner(), IG.Forms.WindowPositionerControl.Positioner, IG.Forms.WindowPositioner.RememberPosition(), and IG.Forms.WindowPositioner.StopRememberPosition().
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
btnRefreshData_Click() [1/3]
void IG.Forms.WindowPositionerControl.btnRefreshData_Click (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.CopyDataFromPositioner().
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
btnUpdate_Click() [1/3]
void IG.Forms.WindowPositionerControl.btnUpdate_Click (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.CopyDataToPositioner().
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
WindowPositionerControl_Load() [1/3]
void IG.Forms.WindowPositionerControl.WindowPositionerControl_Load (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl._masterWindow, IG.Forms.WindowPositionerControl._window, and IG.Forms.WindowPositionerControl.LaunchWindows().
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
Dispose() [1/3]
override void IG.Forms.WindowPositionerControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.WindowPositionerControl.components.
InitializeComponent() [1/3]
void IG.Forms.WindowPositionerControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.WindowPositionerControl.alignMaster, IG.Forms.WindowPositionerControl.alignScreen, IG.Forms.WindowPositionerControl.alignWindow, IG.Forms.WindowPositionerControl.btnLaunchWindows, IG.Forms.WindowPositionerControl.btnLaunchWindows_Click(), IG.Forms.WindowPositionerControl.btnPositionWindows, IG.Forms.WindowPositionerControl.btnPositionWindows_Click(), IG.Forms.WindowPositionerControl.btnRefreshData, IG.Forms.WindowPositionerControl.btnRefreshData_Click(), IG.Forms.WindowPositionerControl.btnRememberPosition, IG.Forms.WindowPositionerControl.btnRememberPosition_Click(), IG.Forms.WindowPositionerControl.btnStickToMaster, IG.Forms.WindowPositionerControl.btnStickToMaster_Click(), IG.Forms.WindowPositionerControl.btnUnStickFromMaster_Click(), IG.Forms.WindowPositionerControl.btnUpdate, IG.Forms.WindowPositionerControl.btnUpdate_Click(), IG.Forms.WindowPositionerControl.button1, IG.Forms.WindowPositionerControl.chkRememberPositions, IG.Forms.WindowPositionerControl.chkRememberPositions_CheckedChanged(), IG.Forms.WindowPositionerControl.grpGeneral, IG.Forms.WindowPositionerControl.grpMaster, IG.Forms.WindowPositionerControl.grpScreen, IG.Forms.WindowShiftControlText.Increment, IG.Forms.WindowShiftControlText.InitialValueX, IG.Forms.WindowShiftControlText.InitialValueY, IG.Forms.WindowPositionerControl.lblMasterWeight, IG.Forms.WindowPositionerControl.lblPause, IG.Forms.WindowPositionerControl.lblTitle, IG.Forms.WindowShiftControlText.MaximumValue, IG.Forms.WindowShiftControlText.MinimumValue, IG.Forms.WindowPositionerControl.shiftMasterRel, IG.Forms.WindowPositionerControl.shiftScreenRel, IG.Forms.WindowPositionerControl.shiftWindowAbsolute, IG.Forms.WindowPositionerControl.shiftWindowRel, IG.Forms.AlignmentControl.Title, IG.Forms.WindowShiftControlText.Title, IG.Forms.WindowPositionerControl.txtMasterWeight, IG.Forms.WindowPositionerControl.txtMasterWeight_Enter(), IG.Forms.WindowPositionerControl.txtPause, IG.Forms.WindowPositionerControl.txtPause_Enter(), IG.Forms.WindowPositionerControl.txtPause_Validated(), and IG.Forms.WindowPositionerControl.WindowPositionerControl_Load().
Referenced by IG.Forms.WindowPositionerControl.WindowPositionerControl().
DoubleVal() [3/6]
double IG.Forms.WindowPositionerControl.DoubleVal (string str, double defaultValue) inline
Converts string to double and returns the value.
Parameters
str String to be converted.
defaultValue Value returned if conversion is not successful.
DoubleVal() [4/6]
double IG.Forms.WindowPositionerControl.DoubleVal (string str) inline
Converts string to double and returns the value (or 0 if conversion was not successful).
References IG.Forms.WindowPositionerControl.DoubleVal().
Referenced by IG.Forms.WindowPositionerControl.DoubleVal().
CopyDataToPositioner() [2/3]
void IG.Forms.WindowPositionerControl.CopyDataToPositioner () inline
Copies data from the form to positioner.
References IG.Forms.WindowPositionerControl.alignMaster, IG.Forms.AlignmentControl.Alignment, IG.Forms.WindowPositionerControl.alignScreen, IG.Forms.WindowPositionerControl.alignWindow, IG.Forms.WindowPositionerControl.DoubleVal(), IG.Forms.WindowPositioner.MasterWeight, IG.Forms.WindowPositioner.MasterWindowAlignment, IG.Forms.WindowPositioner.MasterWindowShiftRelative, IG.Forms.WindowPositioner.MovementPauseSeconds, IG.Forms.WindowPositionerControl.Positioner, IG.Forms.WindowPositioner.ScreenAlignment, IG.Forms.WindowPositioner.ScreenShiftRelative, IG.Forms.WindowShiftControlText.Shift, IG.Forms.WindowPositioner.ShiftAbsolute, IG.Forms.WindowPositionerControl.shiftMasterRel, IG.Forms.WindowPositionerControl.shiftScreenRel, IG.Forms.WindowPositionerControl.shiftWindowAbsolute, IG.Forms.WindowPositionerControl.shiftWindowRel, IG.Forms.WindowPositionerControl.txtMasterWeight, IG.Forms.WindowPositionerControl.txtPause, IG.Forms.WindowPositioner.WindowAlignment, and IG.Forms.WindowPositioner.WindowShiftRelative.
CopyDataFromPositioner() [2/3]
void IG.Forms.WindowPositionerControl.CopyDataFromPositioner () inline
References IG.Forms.WindowPositionerControl.alignMaster, IG.Forms.AlignmentControl.Alignment, IG.Forms.WindowPositionerControl.alignScreen, IG.Forms.WindowPositionerControl.alignWindow, IG.Forms.WindowPositioner.MasterWeight, IG.Forms.WindowPositioner.MasterWindowAlignment, IG.Forms.WindowPositioner.MasterWindowShiftRelative, IG.Forms.WindowPositioner.MovementPauseSeconds, IG.Forms.WindowPositionerControl.Positioner, IG.Forms.WindowPositioner.ScreenAlignment, IG.Forms.WindowPositioner.ScreenShiftRelative, IG.Forms.WindowShiftControlText.Shift, IG.Forms.WindowPositioner.ShiftAbsolute, IG.Forms.WindowPositionerControl.shiftMasterRel, IG.Forms.WindowPositionerControl.shiftScreenRel, IG.Forms.WindowPositionerControl.shiftWindowAbsolute, IG.Forms.WindowPositionerControl.shiftWindowRel, IG.Forms.WindowPositionerControl.txtMasterWeight, IG.Forms.WindowPositionerControl.txtPause, IG.Forms.WindowPositioner.WindowAlignment, and IG.Forms.WindowPositioner.WindowShiftRelative.
LaunchWindows() [2/3]
void IG.Forms.WindowPositionerControl.LaunchWindows () inline
References IG.Forms.WindowPositionerControl.MakeWindowsVisible(), IG.Forms.WindowPositionerControl.MasterWindow, IG.Forms.WindowPositionerControl.Positioner, IG.Forms.WindowPositioner.ScreenBounds, and IG.Forms.WindowPositionerControl.Window.
MakeWindowsVisible() [2/3]
void IG.Forms.WindowPositionerControl.MakeWindowsVisible () inline
References IG.Forms.UtilForms.BlinkControl(), IG.Forms.WindowPositionerControl.MasterWindow, and IG.Forms.WindowPositionerControl.Window.
btnLaunchWindows_Click() [2/3]
void IG.Forms.WindowPositionerControl.btnLaunchWindows_Click (object sender, EventArgs e) inline private
Launches the master window and the window to be positioned.
References IG.Forms.WindowPositionerControl.LaunchWindows().
btnPositionWindows_Click() [2/3]
void IG.Forms.WindowPositionerControl.btnPositionWindows_Click (object sender, EventArgs e) inline private
Launches the master window and the window to be positioned.
References IG.Forms.WindowPositionerControl.CopyDataToPositioner(), IG.Forms.WindowPositionerControl.MakeWindowsVisible(), IG.Forms.WindowPositionerControl.Positioner, and IG.Forms.WindowPositioner.PositionWindow().
btnRememberPosition_Click() [2/3]
void IG.Forms.WindowPositionerControl.btnRememberPosition_Click (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.Positioner, and IG.Forms.WindowPositioner.SetToCurrentPosition().
btnStickToMaster_Click() [2/3]
void IG.Forms.WindowPositionerControl.btnStickToMaster_Click (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.CopyDataToPositioner(), IG.Forms.WindowPositionerControl.Positioner, and IG.Forms.WindowPositioner.StickToMaster().
btnUnStickFromMaster_Click() [2/3]
void IG.Forms.WindowPositionerControl.btnUnStickFromMaster_Click (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.CopyDataToPositioner(), IG.Forms.WindowPositionerControl.Positioner, and IG.Forms.WindowPositioner.UnStickFromMaster().
txtMasterWeight_Enter() [2/3]
void IG.Forms.WindowPositionerControl.txtMasterWeight_Enter (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.txtMasterWeight.
txtPause_Validated() [2/3]
void IG.Forms.WindowPositionerControl.txtPause_Validated (object sender, EventArgs e) inline private
References IG.Forms.UtilForms.BlinkControl(), IG.Forms.WindowPositioner.MovementPauseSeconds, IG.Forms.WindowPositionerControl.Positioner, and IG.Forms.WindowPositionerControl.txtPause.
txtPause_Enter() [2/3]
void IG.Forms.WindowPositionerControl.txtPause_Enter (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.txtPause.
chkRememberPositions_CheckedChanged() [2/3]
void IG.Forms.WindowPositionerControl.chkRememberPositions_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.chkRememberPositions, IG.Forms.WindowPositionerControl.CopyDataToPositioner(), IG.Forms.WindowPositionerControl.Positioner, IG.Forms.WindowPositioner.RememberPosition(), and IG.Forms.WindowPositioner.StopRememberPosition().
btnRefreshData_Click() [2/3]
void IG.Forms.WindowPositionerControl.btnRefreshData_Click (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.CopyDataFromPositioner().
btnUpdate_Click() [2/3]
void IG.Forms.WindowPositionerControl.btnUpdate_Click (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.CopyDataToPositioner().
WindowPositionerControl_Load() [2/3]
void IG.Forms.WindowPositionerControl.WindowPositionerControl_Load (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl._masterWindow, IG.Forms.WindowPositionerControl._window, and IG.Forms.WindowPositionerControl.LaunchWindows().
Dispose() [2/3]
override void IG.Forms.WindowPositionerControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.WindowPositionerControl.components.
InitializeComponent() [2/3]
void IG.Forms.WindowPositionerControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.WindowPositionerControl.alignMaster, IG.Forms.WindowPositionerControl.alignScreen, IG.Forms.WindowPositionerControl.alignWindow, IG.Forms.WindowPositionerControl.btnLaunchWindows, IG.Forms.WindowPositionerControl.btnLaunchWindows_Click(), IG.Forms.WindowPositionerControl.btnPositionWindows, IG.Forms.WindowPositionerControl.btnPositionWindows_Click(), IG.Forms.WindowPositionerControl.btnRefreshData, IG.Forms.WindowPositionerControl.btnRefreshData_Click(), IG.Forms.WindowPositionerControl.btnRememberPosition, IG.Forms.WindowPositionerControl.btnRememberPosition_Click(), IG.Forms.WindowPositionerControl.btnStickToMaster, IG.Forms.WindowPositionerControl.btnStickToMaster_Click(), IG.Forms.WindowPositionerControl.btnUnStickFromMaster_Click(), IG.Forms.WindowPositionerControl.btnUpdate, IG.Forms.WindowPositionerControl.btnUpdate_Click(), IG.Forms.WindowPositionerControl.button1, IG.Forms.WindowPositionerControl.chkRememberPositions, IG.Forms.WindowPositionerControl.chkRememberPositions_CheckedChanged(), IG.Forms.WindowPositionerControl.grpGeneral, IG.Forms.WindowPositionerControl.grpMaster, IG.Forms.WindowPositionerControl.grpScreen, IG.Forms.WindowShiftControlText.Increment, IG.Forms.WindowShiftControlText.InitialValueX, IG.Forms.WindowShiftControlText.InitialValueY, IG.Forms.WindowPositionerControl.lblMasterWeight, IG.Forms.WindowPositionerControl.lblPause, IG.Forms.WindowPositionerControl.lblTitle, IG.Forms.WindowShiftControlText.MaximumValue, IG.Forms.WindowShiftControlText.MinimumValue, IG.Forms.WindowPositionerControl.shiftMasterRel, IG.Forms.WindowPositionerControl.shiftScreenRel, IG.Forms.WindowPositionerControl.shiftWindowAbsolute, IG.Forms.WindowPositionerControl.shiftWindowRel, IG.Forms.AlignmentControl.Title, IG.Forms.WindowShiftControlText.Title, IG.Forms.WindowPositionerControl.txtMasterWeight, IG.Forms.WindowPositionerControl.txtMasterWeight_Enter(), IG.Forms.WindowPositionerControl.txtPause, IG.Forms.WindowPositionerControl.txtPause_Enter(), IG.Forms.WindowPositionerControl.txtPause_Validated(), and IG.Forms.WindowPositionerControl.WindowPositionerControl_Load().
DoubleVal() [5/6]
double IG.Forms.WindowPositionerControl.DoubleVal (string str, double defaultValue) inline
Converts string to double and returns the value.
Parameters
str String to be converted.
defaultValue Value returned if conversion is not successful.
DoubleVal() [6/6]
double IG.Forms.WindowPositionerControl.DoubleVal (string str) inline
Converts string to double and returns the value (or 0 if conversion was not successful).
References IG.Forms.WindowPositionerControl.DoubleVal().
Referenced by IG.Forms.WindowPositionerControl.DoubleVal().
CopyDataToPositioner() [3/3]
void IG.Forms.WindowPositionerControl.CopyDataToPositioner () inline
Copies data from the form to positioner.
References IG.Forms.WindowPositionerControl.alignMaster, IG.Forms.AlignmentControl.Alignment, IG.Forms.WindowPositionerControl.alignScreen, IG.Forms.WindowPositionerControl.alignWindow, IG.Forms.WindowPositionerControl.DoubleVal(), IG.Forms.WindowPositioner.MasterWeight, IG.Forms.WindowPositioner.MasterWindowAlignment, IG.Forms.WindowPositioner.MasterWindowShiftRelative, IG.Forms.WindowPositioner.MovementPauseSeconds, IG.Forms.WindowPositionerControl.Positioner, IG.Forms.WindowPositioner.ScreenAlignment, IG.Forms.WindowPositioner.ScreenShiftRelative, IG.Forms.WindowShiftControlText.Shift, IG.Forms.WindowPositioner.ShiftAbsolute, IG.Forms.WindowPositionerControl.shiftMasterRel, IG.Forms.WindowPositionerControl.shiftScreenRel, IG.Forms.WindowPositionerControl.shiftWindowAbsolute, IG.Forms.WindowPositionerControl.shiftWindowRel, IG.Forms.WindowPositionerControl.txtMasterWeight, IG.Forms.WindowPositionerControl.txtPause, IG.Forms.WindowPositioner.WindowAlignment, and IG.Forms.WindowPositioner.WindowShiftRelative.
CopyDataFromPositioner() [3/3]
void IG.Forms.WindowPositionerControl.CopyDataFromPositioner () inline
References IG.Forms.WindowPositionerControl.alignMaster, IG.Forms.AlignmentControl.Alignment, IG.Forms.WindowPositionerControl.alignScreen, IG.Forms.WindowPositionerControl.alignWindow, IG.Forms.WindowPositioner.MasterWeight, IG.Forms.WindowPositioner.MasterWindowAlignment, IG.Forms.WindowPositioner.MasterWindowShiftRelative, IG.Forms.WindowPositioner.MovementPauseSeconds, IG.Forms.WindowPositionerControl.Positioner, IG.Forms.WindowPositioner.ScreenAlignment, IG.Forms.WindowPositioner.ScreenShiftRelative, IG.Forms.WindowShiftControlText.Shift, IG.Forms.WindowPositioner.ShiftAbsolute, IG.Forms.WindowPositionerControl.shiftMasterRel, IG.Forms.WindowPositionerControl.shiftScreenRel, IG.Forms.WindowPositionerControl.shiftWindowAbsolute, IG.Forms.WindowPositionerControl.shiftWindowRel, IG.Forms.WindowPositionerControl.txtMasterWeight, IG.Forms.WindowPositionerControl.txtPause, IG.Forms.WindowPositioner.WindowAlignment, and IG.Forms.WindowPositioner.WindowShiftRelative.
LaunchWindows() [3/3]
void IG.Forms.WindowPositionerControl.LaunchWindows () inline
References IG.Forms.WindowPositionerControl.MakeWindowsVisible(), IG.Forms.WindowPositionerControl.MasterWindow, IG.Forms.WindowPositionerControl.Positioner, IG.Forms.WindowPositioner.ScreenBounds, and IG.Forms.WindowPositionerControl.Window.
MakeWindowsVisible() [3/3]
void IG.Forms.WindowPositionerControl.MakeWindowsVisible () inline
References IG.Forms.UtilForms.BlinkControl(), IG.Forms.WindowPositionerControl.MasterWindow, and IG.Forms.WindowPositionerControl.Window.
btnLaunchWindows_Click() [3/3]
void IG.Forms.WindowPositionerControl.btnLaunchWindows_Click (object sender, EventArgs e) inline private
Launches the master window and the window to be positioned.
References IG.Forms.WindowPositionerControl.LaunchWindows().
btnPositionWindows_Click() [3/3]
void IG.Forms.WindowPositionerControl.btnPositionWindows_Click (object sender, EventArgs e) inline private
Launches the master window and the window to be positioned.
References IG.Forms.WindowPositionerControl.CopyDataToPositioner(), IG.Forms.WindowPositionerControl.MakeWindowsVisible(), IG.Forms.WindowPositionerControl.Positioner, and IG.Forms.WindowPositioner.PositionWindow().
btnRememberPosition_Click() [3/3]
void IG.Forms.WindowPositionerControl.btnRememberPosition_Click (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.Positioner, and IG.Forms.WindowPositioner.SetToCurrentPosition().
btnStickToMaster_Click() [3/3]
void IG.Forms.WindowPositionerControl.btnStickToMaster_Click (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.CopyDataToPositioner(), IG.Forms.WindowPositionerControl.Positioner, and IG.Forms.WindowPositioner.StickToMaster().
btnUnStickFromMaster_Click() [3/3]
void IG.Forms.WindowPositionerControl.btnUnStickFromMaster_Click (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.CopyDataToPositioner(), IG.Forms.WindowPositionerControl.Positioner, and IG.Forms.WindowPositioner.UnStickFromMaster().
txtMasterWeight_Enter() [3/3]
void IG.Forms.WindowPositionerControl.txtMasterWeight_Enter (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.txtMasterWeight.
txtPause_Validated() [3/3]
void IG.Forms.WindowPositionerControl.txtPause_Validated (object sender, EventArgs e) inline private
References IG.Forms.UtilForms.BlinkControl(), IG.Forms.WindowPositioner.MovementPauseSeconds, IG.Forms.WindowPositionerControl.Positioner, and IG.Forms.WindowPositionerControl.txtPause.
txtPause_Enter() [3/3]
void IG.Forms.WindowPositionerControl.txtPause_Enter (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.txtPause.
chkRememberPositions_CheckedChanged() [3/3]
void IG.Forms.WindowPositionerControl.chkRememberPositions_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.chkRememberPositions, IG.Forms.WindowPositionerControl.CopyDataToPositioner(), IG.Forms.WindowPositionerControl.Positioner, IG.Forms.WindowPositioner.RememberPosition(), and IG.Forms.WindowPositioner.StopRememberPosition().
btnRefreshData_Click() [3/3]
void IG.Forms.WindowPositionerControl.btnRefreshData_Click (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.CopyDataFromPositioner().
btnUpdate_Click() [3/3]
void IG.Forms.WindowPositionerControl.btnUpdate_Click (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl.CopyDataToPositioner().
WindowPositionerControl_Load() [3/3]
void IG.Forms.WindowPositionerControl.WindowPositionerControl_Load (object sender, EventArgs e) inline private
References IG.Forms.WindowPositionerControl._masterWindow, IG.Forms.WindowPositionerControl._window, and IG.Forms.WindowPositionerControl.LaunchWindows().
Dispose() [3/3]
override void IG.Forms.WindowPositionerControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.WindowPositionerControl.components.
InitializeComponent() [3/3]
void IG.Forms.WindowPositionerControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.WindowPositionerControl.alignMaster, IG.Forms.WindowPositionerControl.alignScreen, IG.Forms.WindowPositionerControl.alignWindow, IG.Forms.WindowPositionerControl.btnLaunchWindows, IG.Forms.WindowPositionerControl.btnLaunchWindows_Click(), IG.Forms.WindowPositionerControl.btnPositionWindows, IG.Forms.WindowPositionerControl.btnPositionWindows_Click(), IG.Forms.WindowPositionerControl.btnRefreshData, IG.Forms.WindowPositionerControl.btnRefreshData_Click(), IG.Forms.WindowPositionerControl.btnRememberPosition, IG.Forms.WindowPositionerControl.btnRememberPosition_Click(), IG.Forms.WindowPositionerControl.btnStickToMaster, IG.Forms.WindowPositionerControl.btnStickToMaster_Click(), IG.Forms.WindowPositionerControl.btnUnStickFromMaster_Click(), IG.Forms.WindowPositionerControl.btnUpdate, IG.Forms.WindowPositionerControl.btnUpdate_Click(), IG.Forms.WindowPositionerControl.button1, IG.Forms.WindowPositionerControl.chkRememberPositions, IG.Forms.WindowPositionerControl.chkRememberPositions_CheckedChanged(), IG.Forms.WindowPositionerControl.grpGeneral, IG.Forms.WindowPositionerControl.grpMaster, IG.Forms.WindowPositionerControl.grpScreen, IG.Forms.WindowShiftControlText.Increment, IG.Forms.WindowShiftControlText.InitialValueX, IG.Forms.WindowShiftControlText.InitialValueY, IG.Forms.WindowPositionerControl.lblMasterWeight, IG.Forms.WindowPositionerControl.lblPause, IG.Forms.WindowPositionerControl.lblTitle, IG.Forms.WindowShiftControlText.MaximumValue, IG.Forms.WindowShiftControlText.MinimumValue, IG.Forms.WindowPositionerControl.shiftMasterRel, IG.Forms.WindowPositionerControl.shiftScreenRel, IG.Forms.WindowPositionerControl.shiftWindowAbsolute, IG.Forms.WindowPositionerControl.shiftWindowRel, IG.Forms.AlignmentControl.Title, IG.Forms.WindowShiftControlText.Title, IG.Forms.WindowPositionerControl.txtMasterWeight, IG.Forms.WindowPositionerControl.txtMasterWeight_Enter(), IG.Forms.WindowPositionerControl.txtPause, IG.Forms.WindowPositionerControl.txtPause_Enter(), IG.Forms.WindowPositionerControl.txtPause_Validated(), and IG.Forms.WindowPositionerControl.WindowPositionerControl_Load().
Member Data Documentation
_positioner
WindowPositioner IG.Forms.WindowPositionerControl._positioner protected
_window
Form IG.Forms.WindowPositionerControl._window protected
Referenced by IG.Forms.WindowPositionerControl.WindowPositionerControl_Load().
_masterWindow
Form IG.Forms.WindowPositionerControl._masterWindow protected
Referenced by IG.Forms.WindowPositionerControl.WindowPositionerControl_Load().
components
System ComponentModel IContainer IG.Forms.WindowPositionerControl.components = null private
Required designer variable.
Referenced by IG.Forms.WindowPositionerControl.Dispose().
lblTitle
System Windows Forms Label IG.Forms.WindowPositionerControl.lblTitle private
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent(), and IG.Forms.WindowPositionerControl.WindowPositionerControl().
grpGeneral
System Windows Forms GroupBox IG.Forms.WindowPositionerControl.grpGeneral private
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
grpMaster
System Windows Forms GroupBox IG.Forms.WindowPositionerControl.grpMaster private
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
grpScreen
System Windows Forms GroupBox IG.Forms.WindowPositionerControl.grpScreen private
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
lblMasterWeight
System Windows Forms Label IG.Forms.WindowPositionerControl.lblMasterWeight private
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
txtMasterWeight
System Windows Forms NumericUpDown IG.Forms.WindowPositionerControl.txtMasterWeight private
Referenced by IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.CopyDataToPositioner(), IG.Forms.WindowPositionerControl.InitializeComponent(), and IG.Forms.WindowPositionerControl.txtMasterWeight_Enter().
alignWindow
IG Forms AlignmentControl IG.Forms.WindowPositionerControl.alignWindow private
Referenced by IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.CopyDataToPositioner(), and IG.Forms.WindowPositionerControl.InitializeComponent().
alignMaster
AlignmentControl IG.Forms.WindowPositionerControl.alignMaster private
Referenced by IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.CopyDataToPositioner(), and IG.Forms.WindowPositionerControl.InitializeComponent().
alignScreen
AlignmentControl IG.Forms.WindowPositionerControl.alignScreen private
Referenced by IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.CopyDataToPositioner(), and IG.Forms.WindowPositionerControl.InitializeComponent().
shiftWindowRel
WindowShiftControlText IG.Forms.WindowPositionerControl.shiftWindowRel private
Referenced by IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.CopyDataToPositioner(), and IG.Forms.WindowPositionerControl.InitializeComponent().
shiftWindowAbsolute
WindowShiftControlText IG.Forms.WindowPositionerControl.shiftWindowAbsolute private
Referenced by IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.CopyDataToPositioner(), and IG.Forms.WindowPositionerControl.InitializeComponent().
shiftMasterRel
WindowShiftControlText IG.Forms.WindowPositionerControl.shiftMasterRel private
Referenced by IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.CopyDataToPositioner(), and IG.Forms.WindowPositionerControl.InitializeComponent().
shiftScreenRel
WindowShiftControlText IG.Forms.WindowPositionerControl.shiftScreenRel private
Referenced by IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.CopyDataToPositioner(), and IG.Forms.WindowPositionerControl.InitializeComponent().
btnLaunchWindows
System Windows Forms Button IG.Forms.WindowPositionerControl.btnLaunchWindows private
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
btnPositionWindows
System Windows Forms Button IG.Forms.WindowPositionerControl.btnPositionWindows private
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
btnStickToMaster
System Windows Forms Button IG.Forms.WindowPositionerControl.btnStickToMaster private
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
button1
System Windows Forms Button IG.Forms.WindowPositionerControl.button1 private
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
txtPause
System Windows Forms TextBox IG.Forms.WindowPositionerControl.txtPause private
Referenced by IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.CopyDataToPositioner(), IG.Forms.WindowPositionerControl.InitializeComponent(), IG.Forms.WindowPositionerControl.txtPause_Enter(), and IG.Forms.WindowPositionerControl.txtPause_Validated().
lblPause
System Windows Forms Label IG.Forms.WindowPositionerControl.lblPause private
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
btnRememberPosition
System Windows Forms Button IG.Forms.WindowPositionerControl.btnRememberPosition private
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
chkRememberPositions
System Windows Forms CheckBox IG.Forms.WindowPositionerControl.chkRememberPositions private
Referenced by IG.Forms.WindowPositionerControl.chkRememberPositions_CheckedChanged(), and IG.Forms.WindowPositionerControl.InitializeComponent().
btnUpdate
System Windows Forms Button IG.Forms.WindowPositionerControl.btnUpdate private
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
btnRefreshData
System Windows Forms Button IG.Forms.WindowPositionerControl.btnRefreshData private
Referenced by IG.Forms.WindowPositionerControl.InitializeComponent().
Property Documentation
Positioner
WindowPositioner IG.Forms.WindowPositionerControl.Positioner get set
Window positioner.
Referenced by IG.Forms.WindowPositionerControl.btnPositionWindows_Click(), IG.Forms.WindowPositionerControl.btnRememberPosition_Click(), IG.Forms.WindowPositionerControl.btnStickToMaster_Click(), IG.Forms.WindowPositionerControl.btnUnStickFromMaster_Click(), IG.Forms.WindowPositionerControl.chkRememberPositions_CheckedChanged(), IG.Forms.WindowPositionerControl.CopyDataFromPositioner(), IG.Forms.WindowPositionerControl.CopyDataToPositioner(), IG.Forms.WindowPositionerControl.LaunchWindows(), IG.Forms.WindowPositionerControl.txtPause_Validated(), and IG.Forms.WindowPositionerControl.WindowPositionerControl().
Window
Form IG.Forms.WindowPositionerControl.Window get set
Window to be positioned.
Referenced by IG.Forms.WindowPositionerControl.LaunchWindows(), IG.Forms.WindowPositionerControl.MakeWindowsVisible(), and IG.Forms.WindowPositionerControl.WindowPositionerControl().
MasterWindow
Form IG.Forms.WindowPositionerControl.MasterWindow get set
Master window relative to which position is set.
Referenced by IG.Forms.WindowPositionerControl.LaunchWindows(), IG.Forms.WindowPositionerControl.MakeWindowsVisible(), and IG.Forms.WindowPositionerControl.WindowPositionerControl().
Title
string IG.Forms.WindowPositionerControl.Title get
Referenced by IG.Forms.WindowPositionerControl.WindowPositionerControl().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/WindowPositioner/WindowPositionerControl.cs
iglib/igforms/Utilities/WindowPositioner/WindowPositionerControl.Designer.cs