Doc: IGLib EXTENDED: alglib.filters Class Reference
alglib.filters Class Reference
Static Public Member Functions
static void filtersma (ref double[] x, int n, int k)
static void filterema (ref double[] x, int n, double alpha)
static void filterlrma (ref double[] x, int n, int k)
static void filtersma (ref double[] x, int n, int k)
static void filterema (ref double[] x, int n, double alpha)
static void filterlrma (ref double[] x, int n, int k)
Member Function Documentation
filtersma() [1/2]
static void alglib.filters.filtersma (ref double[] x, int n, int k) inline static
References alglib.ap.assert(), and alglib.apserv.isfinitevector().
Referenced by alglib.filtersma(), and alglib.testfiltersunit.testsma().
filterema() [1/2]
static void alglib.filters.filterema (ref double[] x, int n, double alpha) inline static
References alglib.ap.assert(), and alglib.apserv.isfinitevector().
Referenced by alglib.filterema(), and alglib.testfiltersunit.testema().
filterlrma() [1/2]
static void alglib.filters.filterlrma (ref double[] x, int n, int k) inline static
References alglib.ap.assert(), alglib.apserv.isfinitevector(), and alglib.linreg.lrlines().
Referenced by alglib.filterlrma(), and alglib.testfiltersunit.testlrma().
filtersma() [2/2]
static void alglib.filters.filtersma (ref double[] x, int n, int k) inline static
filterema() [2/2]
static void alglib.filters.filterema (ref double[] x, int n, double alpha) inline static
filterlrma() [2/2]
static void alglib.filters.filterlrma (ref double[] x, int n, int k) inline static
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/dataanalysis.cs