var dir_8900a7852f77278df5bb0ac78eb42b78 =
[
    [ "IAMCrossbar.cs", "df/dac/IAMCrossbar_8cs.html", null ],
    [ "IAMStreamConfig.cs", "de/daa/IAMStreamConfig_8cs.html", null ],
    [ "IAMVideoControl.cs", "da/dfc/IAMVideoControl_8cs.html", null ],
    [ "IBaseFilter.cs", "dc/d79/IBaseFilter_8cs.html", null ],
    [ "ICaptureGraphBuilder2.cs", "d3/da1/ICaptureGraphBuilder2_8cs.html", null ],
    [ "ICreateDevEnum.cs", "dc/d97/ICreateDevEnum_8cs.html", null ],
    [ "IEnumFilters.cs", "dc/dc1/IEnumFilters_8cs.html", null ],
    [ "IEnumPins.cs", "da/dc8/IEnumPins_8cs.html", null ],
    [ "IFileSourceFilter.cs", "d7/d11/IFileSourceFilter_8cs.html", null ],
    [ "IFilterGraph.cs", "d4/d71/IFilterGraph_8cs.html", null ],
    [ "IFilterGraph2.cs", "d8/df7/IFilterGraph2_8cs.html", null ],
    [ "IGraphBuilder.cs", "d4/d25/IGraphBuilder_8cs.html", null ],
    [ "IMediaControl.cs", "d4/d45/IMediaControl_8cs.html", null ],
    [ "IMediaEventEx.cs", "d5/d80/IMediaEventEx_8cs.html", null ],
    [ "IMediaFilter.cs", "d1/dd3/IMediaFilter_8cs.html", null ],
    [ "IPersist.cs", "de/d3b/IPersist_8cs.html", null ],
    [ "IPin.cs", "d9/d8e/IPin_8cs.html", null ],
    [ "IPropertyBag.cs", "d7/d07/shelldev_2lib__ann_2aforge_8net_2Sources_2Video_8DirectShow_2Internals_2IPropertyBag_8cs.html", null ],
    [ "IReferenceClock.cs", "d8/d6a/IReferenceClock_8cs.html", null ],
    [ "ISampleGrabber.cs", "d1/d83/ISampleGrabber_8cs.html", null ],
    [ "ISampleGrabberCB.cs", "d1/d50/ISampleGrabberCB_8cs.html", null ],
    [ "ISpecifyPropertyPages.cs", "db/dec/ISpecifyPropertyPages_8cs.html", null ],
    [ "IVideoWindow.cs", "d2/df3/IVideoWindow_8cs.html", null ],
    [ "Structures.cs", "dd/de7/Structures_8cs.html", "dd/de7/Structures_8cs" ],
    [ "Tools.cs", "d8/de8/Video_8DirectShow_2Internals_2Tools_8cs.html", null ],
    [ "Uuids.cs", "d9/dc7/Internals_2Uuids_8cs.html", null ],
    [ "Win32.cs", "d3/dc4/Video_8DirectShow_2Internals_2Win32_8cs.html", null ]
];