Doc: IGLib EXTENDED: IG.Forms.InputOutputDataDefinitionControl Class Reference
IG.Forms.InputOutputDataDefinitionControl Class Reference
Public Member Functions
InputOutputDataDefinitionControl ()
virtual string CreateSummary ()
InputOutputDataDefinitionControl ()
virtual string CreateSummary ()
InputOutputDataDefinitionControl ()
virtual string CreateSummary ()
Protected Member Functions
void OnDefinitionObjectChanged (InputOutputDataDefiniton oldDataDefinition, InputOutputDataDefiniton newDataDefinition)
Raises the DefinitionObjectChanged event. This method should be called preferrably, rather than the event itself.
void OnInputLengthChanged (int oldLength, int newLength)
Raises the InputLengthChanged event. This method should be called preferrably, rather than the event itself.
void OnOutputLengthChanged (int oldLength, int newLength)
Raises the <see cref=OutputLengthChanged"/> event. This method should be called preferrably, rather than the event itself.
void OnInputElementDataChanged (EventArgs e)
Raises the InputElementDataChanged event. This method should be called preferrably, rather than the event itself.
void OnOutputElementDataChanged (EventArgs e)
Raises the OutputElementDataChanged event. This method should be called preferrably, rather than the event itself.
override void Dispose (bool disposing)
Clean up any resources being used.
void OnDefinitionObjectChanged (InputOutputDataDefiniton oldDataDefinition, InputOutputDataDefiniton newDataDefinition)
Raises the DefinitionObjectChanged event. This method should be called preferrably, rather than the event itself.
void OnInputLengthChanged (int oldLength, int newLength)
Raises the InputLengthChanged event. This method should be called preferrably, rather than the event itself.
void OnOutputLengthChanged (int oldLength, int newLength)
Raises the <see cref=OutputLengthChanged"/> event. This method should be called preferrably, rather than the event itself.
override void Dispose (bool disposing)
Clean up any resources being used.
void OnDefinitionObjectChanged (InputOutputDataDefiniton oldDataDefinition, InputOutputDataDefiniton newDataDefinition)
Raises the DefinitionObjectChanged event. This method should be called preferrably, rather than the event itself.
void OnInputLengthChanged (int oldLength, int newLength)
Raises the InputLengthChanged event. This method should be called preferrably, rather than the event itself.
void OnOutputLengthChanged (int oldLength, int newLength)
Raises the <see cref=OutputLengthChanged"/> event. This method should be called preferrably, rather than the event itself.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
InputOutputDataDefiniton _dataDefinition
int _inputLength
int _outputLength
string _name
string _description
Properties
IG.Lib.IReporter Reporter [get]
Reporter used for internal reporting.
InpuOrOutputtDataDefinitionControl InputDataControl [get]
Gets control used for editing definitions of input data elements.
InpuOrOutputtDataDefinitionControl OutputDataControl [get]
Gets control used for editing definitions of output data elements.
virtual InputOutputDataDefiniton DataDefinition [get, set]
Data about input and output quantities of the manipulated functions or response.
virtual int InputLength [get, protected set]
Number of input parameters or data elements.
virtual int OutputLength [get, protected set]
Number of input parameters or data elements.
virtual string DataName [get, protected set]
Name of the data defined by DataDefinition
virtual string DataDescription [get, protected set]
Description of the data defined by DataDefinition
string Title [get, set]
Title that is shown on the top of control, in the lblMainTitle label.
string TitleWithChangedSign [get]
Actual title that is shown on the top of control, in the lblMainTitle label, includes eventual marks for unsaved changes.
bool HasUnsavedChanges [get, set]
Whether the current function definition has unsaved changes.
bool IsDimentionChangeAllowed [get, set]
Indicates whetherr user can change dimensions (number of input/output data elements).
bool UseLegalVariableNames [get, set]
Specifies whether legal variable names (according to rules in programming languages such as C++, C# or Java) should be enforced for naming input and utput elements.
InputDataDefinitionControl InputDataControl [get]
Gets control used for editing definitions of input data elements.
InputDataDefinitionControl OutputDataControl [get]
Gets control used for editing definitions of output data elements.
Events
EventHandler< ValueChangeEventArgs< InputOutputDataDefiniton > > DefinitionObjectChanged
Occurs when data definition object is changed (i.e., when object reference changes), meaning that whole data definition object is replaced.
EventHandler< IndexChangeEventArgs > InputLengthChanged
Occurs when number of input parameters (InputLength) is changed.
EventHandler< IndexChangeEventArgs > OutputLengthChanged
Occurs when number of output values (OutputLength) is changed.
EventHandler InputElementDataChanged
Occurs when some input element property is changed.
EventHandler OutputElementDataChanged
Occurs when some output element property is changed.
Private Member Functions
void menuSummary_Click (object sender, EventArgs e)
void numNumInputParameters_Validated (object sender, EventArgs e)
void numNumOutputValues_Validated (object sender, EventArgs e)
void txtName_Validated (object sender, EventArgs e)
void txtDescription_Validated (object sender, EventArgs e)
void btnLoad_Click (object sender, EventArgs e)
void btnSave_Click (object sender, EventArgs e)
void btnGenerateTestData_Click (object sender, EventArgs e)
void btnLoadFromFunction_Click (object sender, EventArgs e)
void inputDataDefinitionControl1_NumElementsChanged (object sender, IndexChangeEventArgs e)
void outputDataDefinitionControl2_NumElementsChanged (object sender, IndexChangeEventArgs e)
void inputDataDefinitionControl1_DataChanged (object sender, EventArgs e)
void outputDataDefinitionControl2_DataChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void menuSummary_Click (object sender, EventArgs e)
void numNumInputParameters_Validated (object sender, EventArgs e)
void numNumOutputValues_Validated (object sender, EventArgs e)
void txtName_Validated (object sender, EventArgs e)
void txtDescription_Validated (object sender, EventArgs e)
void btnLoad_Click (object sender, EventArgs e)
void btnSave_Click (object sender, EventArgs e)
void btnGenerateTestData_Click (object sender, EventArgs e)
void btnLoadFromFunction_Click (object sender, EventArgs e)
void inputDataDefinitionControl1_NumElementsChanged (object sender, IndexChangeEventArgs e)
void outputDataDefinitionControl2_NumElementsChanged (object sender, IndexChangeEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void menuSummary_Click (object sender, EventArgs e)
void numNumInputParameters_Validated (object sender, EventArgs e)
void numNumOutputValues_Validated (object sender, EventArgs e)
void txtName_Validated (object sender, EventArgs e)
void txtDescription_Validated (object sender, EventArgs e)
void btnLoad_Click (object sender, EventArgs e)
void btnSave_Click (object sender, EventArgs e)
void btnGenerateTestData_Click (object sender, EventArgs e)
void btnLoadFromFunction_Click (object sender, EventArgs e)
void inputDataDefinitionControl1_NumElementsChanged (object sender, IndexChangeEventArgs e)
void outputDataDefinitionControl2_NumElementsChanged (object sender, IndexChangeEventArgs e)
void inputDataDefinitionControl1_DataChanged (object sender, EventArgs e)
void outputDataDefinitionControl2_DataChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
string _title = "Input and Output Data Definition"
bool _hasUnsavedChanges = false
bool _isDimentionChangeAllowed = true
bool _useLegalVariableNames = true
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Label lblMainTitle
IG.Forms.InpuOrOutputtDataDefinitionControl inputDataDefinitionControl1
IG.Forms.InpuOrOutputtDataDefinitionControl outputDataDefinitionControl2
System.Windows.Forms.Panel pnlControls
System.Windows.Forms.Button btnSave
System.Windows.Forms.Button btnLoadFromFunction
System.Windows.Forms.Button btnLoad
System.Windows.Forms.ContextMenuStrip contextMenuStrip1
System.Windows.Forms.ToolStripMenuItem menuSummary
System.Windows.Forms.Label lblNumOutputValues
System.Windows.Forms.Label lblNminputParameters
System.Windows.Forms.NumericUpDown numNumOutputValues
System.Windows.Forms.NumericUpDown numNumInputParameters
System.Windows.Forms.Button btnGenerateTestData
System.Windows.Forms.SplitContainer splitContainer1
System.Windows.Forms.TextBox txtDescription
System.Windows.Forms.TextBox txtName
System.Windows.Forms.Label lblDescription
System.Windows.Forms.Label lblName
FileSelector fileSelector1
IndicatorLight indicatorLight1
IG.Forms.InputDataDefinitionControl inputDataDefinitionControl1
IG.Forms.InputDataDefinitionControl outputDataDefinitionControl2
System.Windows.Forms.Button btnToDeleteLater
Constructor & Destructor Documentation
InputOutputDataDefinitionControl() [1/3]
IG.Forms.InputOutputDataDefinitionControl.InputOutputDataDefinitionControl () inline
References IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1, IG.Forms.InpuOrOutputtDataDefinitionControl.IsInputData, IG.Forms.InputOutputDataDefinitionControl.lblMainTitle, IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2, and IG.Forms.InputOutputDataDefinitionControl.TitleWithChangedSign.
InputOutputDataDefinitionControl() [2/3]
IG.Forms.InputOutputDataDefinitionControl.InputOutputDataDefinitionControl () inline
References IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1, IG.Forms.InpuOrOutputtDataDefinitionControl.IsInputData, and IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2.
InputOutputDataDefinitionControl() [3/3]
IG.Forms.InputOutputDataDefinitionControl.InputOutputDataDefinitionControl () inline
References IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1, IG.Forms.InpuOrOutputtDataDefinitionControl.IsInputData, IG.Forms.InputOutputDataDefinitionControl.lblMainTitle, IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2, and IG.Forms.InputOutputDataDefinitionControl.TitleWithChangedSign.
Member Function Documentation
OnDefinitionObjectChanged() [1/3]
void IG.Forms.InputOutputDataDefinitionControl.OnDefinitionObjectChanged (InputOutputDataDefiniton oldDataDefinition, InputOutputDataDefiniton newDataDefinition) inline protected
Raises the DefinitionObjectChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldDataDefinition Old data definition object.
newDataDefinition New data definition object.
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.InputOutputDataDefinitionControl.DefinitionObjectChanged, and IG.Forms.InputOutputDataDefinitionControl.indicatorLight1.
OnInputLengthChanged() [1/3]
void IG.Forms.InputOutputDataDefinitionControl.OnInputLengthChanged (int oldLength, int newLength) inline protected
Raises the InputLengthChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldLength Old length.
newLength New length.
References IG.Forms.InputOutputDataDefinitionControl.InputLengthChanged.
OnOutputLengthChanged() [1/3]
void IG.Forms.InputOutputDataDefinitionControl.OnOutputLengthChanged (int oldLength, int newLength) inline protected
Raises the <see cref=OutputLengthChanged"/> event. This method should be called preferrably, rather than the event itself.
Parameters
oldLength Old length.
newLength New length.
References IG.Forms.InputOutputDataDefinitionControl.OutputLengthChanged.
OnInputElementDataChanged()
void IG.Forms.InputOutputDataDefinitionControl.OnInputElementDataChanged (EventArgs e) inline protected
Raises the InputElementDataChanged event. This method should be called preferrably, rather than the event itself.
References IG.Forms.InputOutputDataDefinitionControl.InputElementDataChanged.
Referenced by IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1_DataChanged().
OnOutputElementDataChanged()
void IG.Forms.InputOutputDataDefinitionControl.OnOutputElementDataChanged (EventArgs e) inline protected
Raises the OutputElementDataChanged event. This method should be called preferrably, rather than the event itself.
References IG.Forms.InputOutputDataDefinitionControl.OutputElementDataChanged.
Referenced by IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2_DataChanged().
CreateSummary() [1/3]
virtual string IG.Forms.InputOutputDataDefinitionControl.CreateSummary () inline virtual
References IG.Forms.InpuOrOutputtDataDefinitionControl.CreateSummary(), IG.Forms.InputOutputDataDefinitionControl.DataDefinition, IG.Forms.InputOutputDataDefinitionControl.DefinitionObjectChanged, IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1, IG.Forms.InputOutputDataDefinitionControl.InputElementDataChanged, IG.Forms.InputOutputDataDefinitionControl.InputLengthChanged, IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2, IG.Forms.InputOutputDataDefinitionControl.OutputElementDataChanged, IG.Forms.InputOutputDataDefinitionControl.OutputLengthChanged, and IG.Num.InputOutputDataDefiniton.ToString().
Referenced by IG.Forms.InputOutputDataDefinitionControl.menuSummary_Click().
menuSummary_Click() [1/3]
void IG.Forms.InputOutputDataDefinitionControl.menuSummary_Click (object sender, EventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.CreateSummary(), and IG.Forms.FadingMessage.Launch().
numNumInputParameters_Validated() [1/3]
void IG.Forms.InputOutputDataDefinitionControl.numNumInputParameters_Validated (object sender, EventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.InputLength, and IG.Forms.InputOutputDataDefinitionControl.numNumInputParameters.
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
numNumOutputValues_Validated() [1/3]
void IG.Forms.InputOutputDataDefinitionControl.numNumOutputValues_Validated (object sender, EventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.numNumOutputValues, and IG.Forms.InputOutputDataDefinitionControl.OutputLength.
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
txtName_Validated() [1/3]
void IG.Forms.InputOutputDataDefinitionControl.txtName_Validated (object sender, EventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.DataName, and IG.Forms.InputOutputDataDefinitionControl.txtName.
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
txtDescription_Validated() [1/3]
void IG.Forms.InputOutputDataDefinitionControl.txtDescription_Validated (object sender, EventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.DataDescription, and IG.Forms.InputOutputDataDefinitionControl.txtDescription.
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
btnLoad_Click() [1/3]
void IG.Forms.InputOutputDataDefinitionControl.btnLoad_Click (object sender, EventArgs e) inline private
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.InputOutputDataDefinitionControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.InputOutputDataDefinitionControl.fileSelector1, IG.Forms.FileSelector.Filter, IG.Forms.InputOutputDataDefinitionControl.HasUnsavedChanges, IG.Num.InputOutputDataDefiniton.LoadJson(), IG.Forms.InputOutputDataDefinitionControl.Reporter, and IG.Lib.IReporterBase.ReportError().
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
btnSave_Click() [1/3]
void IG.Forms.InputOutputDataDefinitionControl.btnSave_Click (object sender, EventArgs e) inline private
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.InputOutputDataDefinitionControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.InputOutputDataDefinitionControl.fileSelector1, IG.Forms.FileSelector.Filter, IG.Forms.InputOutputDataDefinitionControl.HasUnsavedChanges, IG.Forms.InputOutputDataDefinitionControl.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.IReporterBase.ReportWarning(), and IG.Num.InputOutputDataDefiniton.SaveJson().
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
btnGenerateTestData_Click() [1/3]
void IG.Forms.InputOutputDataDefinitionControl.btnGenerateTestData_Click (object sender, EventArgs e) inline private
References IG.Forms.ControlManipulator.AddControl(), IG.Forms.ControlManipulator.Blink(), IG.Num.InputOutputDataDefiniton.CreateDefault(), IG.Forms.InputOutputDataDefinitionControl.DataDefinition, IG.Forms.InputOutputDataDefinitionControl.HasUnsavedChanges, IG.Forms.InputOutputDataDefinitionControl.InputLength, IG.Forms.InputOutputDataDefinitionControl.numNumInputParameters, IG.Forms.InputOutputDataDefinitionControl.numNumOutputValues, IG.Forms.InputOutputDataDefinitionControl.OutputLength, IG.Forms.InputOutputDataDefinitionControl.Reporter, and IG.Lib.IReporterBase.ReportWarning().
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
btnLoadFromFunction_Click() [1/3]
void IG.Forms.InputOutputDataDefinitionControl.btnLoadFromFunction_Click (object sender, EventArgs e) inline private
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.InputOutputDataDefinitionControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.InputOutputDataDefinitionControl.fileSelector1, IG.Forms.FileSelector.Filter, IG.Forms.InputOutputDataDefinitionControl.HasUnsavedChanges, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.LoadJson(), IG.Num.ScalarFunctionScriptControllerBase< ScalarFunctionType >.LoadJson(), IG.Forms.InputOutputDataDefinitionControl.Reporter, and IG.Lib.IReporterBase.ReportError().
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
inputDataDefinitionControl1_NumElementsChanged() [1/3]
void IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1_NumElementsChanged (object sender, IndexChangeEventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.HasUnsavedChanges, IG.Forms.InpuOrOutputtDataDefinitionControl.HasUnsavedChanges, IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1, IG.Forms.InputOutputDataDefinitionControl.InputLength, IG.Forms.InpuOrOutputtDataDefinitionControl.InputLength, IG.Forms.ValueChangeEventArgs< ValueType >.New, and IG.Forms.ValueChangeEventArgs< ValueType >.NewDefined.
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
outputDataDefinitionControl2_NumElementsChanged() [1/3]
void IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2_NumElementsChanged (object sender, IndexChangeEventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.HasUnsavedChanges, IG.Forms.InpuOrOutputtDataDefinitionControl.HasUnsavedChanges, IG.Forms.ValueChangeEventArgs< ValueType >.New, IG.Forms.ValueChangeEventArgs< ValueType >.NewDefined, IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2, IG.Forms.InputOutputDataDefinitionControl.OutputLength, and IG.Forms.InpuOrOutputtDataDefinitionControl.OutputLength.
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
inputDataDefinitionControl1_DataChanged() [1/2]
void IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1_DataChanged (object sender, EventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.HasUnsavedChanges, IG.Forms.InpuOrOutputtDataDefinitionControl.HasUnsavedChanges, IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1, and IG.Forms.InputOutputDataDefinitionControl.OnInputElementDataChanged().
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
outputDataDefinitionControl2_DataChanged() [1/2]
void IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2_DataChanged (object sender, EventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.HasUnsavedChanges, IG.Forms.InpuOrOutputtDataDefinitionControl.HasUnsavedChanges, IG.Forms.InputOutputDataDefinitionControl.OnOutputElementDataChanged(), and IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2.
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
Dispose() [1/3]
override void IG.Forms.InputOutputDataDefinitionControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.InputOutputDataDefinitionControl.components.
InitializeComponent() [1/3]
void IG.Forms.InputOutputDataDefinitionControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.InputOutputDataDefinitionControl.btnGenerateTestData, IG.Forms.InputOutputDataDefinitionControl.btnGenerateTestData_Click(), IG.Forms.InputOutputDataDefinitionControl.btnLoad, IG.Forms.InputOutputDataDefinitionControl.btnLoad_Click(), IG.Forms.InputOutputDataDefinitionControl.btnLoadFromFunction, IG.Forms.InputOutputDataDefinitionControl.btnLoadFromFunction_Click(), IG.Forms.InputOutputDataDefinitionControl.btnSave, IG.Forms.InputOutputDataDefinitionControl.btnSave_Click(), IG.Forms.IndicatorLight.ColorLabel, IG.Forms.InputOutputDataDefinitionControl.components, IG.Forms.InputOutputDataDefinitionControl.contextMenuStrip1, IG.Forms.InpuOrOutputtDataDefinitionControl.DataDefinition, IG.Forms.InpuOrOutputtDataDefinitionControl.ElementDataChanged, IG.Forms.InputOutputDataDefinitionControl.fileSelector1, IG.Forms.IndicatorLight.FlowDirection, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.InpuOrOutputtDataDefinitionControl.HasUnsavedChanges, IG.Forms.InputOutputDataDefinitionControl.indicatorLight1, IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1, IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1_DataChanged(), IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1_NumElementsChanged(), IG.Forms.InpuOrOutputtDataDefinitionControl.InputLength, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.InpuOrOutputtDataDefinitionControl.IsDimentionChangeAllowed, IG.Forms.InpuOrOutputtDataDefinitionControl.IsInputData, IG.Forms.IndicatorLight.LabelFont, IG.Forms.IndicatorLight.LabelText, IG.Forms.InputOutputDataDefinitionControl.lblDescription, IG.Forms.InputOutputDataDefinitionControl.lblMainTitle, IG.Forms.InputOutputDataDefinitionControl.lblName, IG.Forms.InputOutputDataDefinitionControl.lblNminputParameters, IG.Forms.InputOutputDataDefinitionControl.lblNumOutputValues, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.InputOutputDataDefinitionControl.menuSummary, IG.Forms.InpuOrOutputtDataDefinitionControl.NumElementsChanged, IG.Forms.InputOutputDataDefinitionControl.numNumInputParameters, IG.Forms.InputOutputDataDefinitionControl.numNumInputParameters_Validated(), IG.Forms.InputOutputDataDefinitionControl.numNumOutputValues, IG.Forms.InputOutputDataDefinitionControl.numNumOutputValues_Validated(), IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2, IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2_DataChanged(), IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2_NumElementsChanged(), IG.Forms.InpuOrOutputtDataDefinitionControl.OutputLength, IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.InputOutputDataDefinitionControl.pnlControls, IG.Forms.InputOutputDataDefinitionControl.splitContainer1, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, IG.Forms.InpuOrOutputtDataDefinitionControl.TitleInputData, IG.Forms.InpuOrOutputtDataDefinitionControl.TitleOutputData, IG.Forms.InputOutputDataDefinitionControl.txtDescription, IG.Forms.InputOutputDataDefinitionControl.txtDescription_Validated(), IG.Forms.InputOutputDataDefinitionControl.txtName, IG.Forms.InputOutputDataDefinitionControl.txtName_Validated(), and IG.Forms.InpuOrOutputtDataDefinitionControl.UseLegalVariableNames.
Referenced by IG.Forms.InputOutputDataDefinitionControl.InputOutputDataDefinitionControl().
OnDefinitionObjectChanged() [2/3]
void IG.Forms.InputOutputDataDefinitionControl.OnDefinitionObjectChanged (InputOutputDataDefiniton oldDataDefinition, InputOutputDataDefiniton newDataDefinition) inline protected
Raises the DefinitionObjectChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldDataDefinition Old data definition object.
newDataDefinition New data definition object.
References IG.Forms.InputOutputDataDefinitionControl.DefinitionObjectChanged.
OnInputLengthChanged() [2/3]
void IG.Forms.InputOutputDataDefinitionControl.OnInputLengthChanged (int oldLength, int newLength) inline protected
Raises the InputLengthChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldLength Old length.
newLength New length.
References IG.Forms.InputOutputDataDefinitionControl.InputLengthChanged.
OnOutputLengthChanged() [2/3]
void IG.Forms.InputOutputDataDefinitionControl.OnOutputLengthChanged (int oldLength, int newLength) inline protected
Raises the <see cref=OutputLengthChanged"/> event. This method should be called preferrably, rather than the event itself.
Parameters
oldLength Old length.
newLength New length.
References IG.Forms.InputOutputDataDefinitionControl.OutputLengthChanged.
CreateSummary() [2/3]
virtual string IG.Forms.InputOutputDataDefinitionControl.CreateSummary () inline virtual
References IG.Forms.InpuOrOutputtDataDefinitionControl.CreateSummary(), IG.Forms.InputOutputDataDefinitionControl.DataDefinition, IG.Forms.InputOutputDataDefinitionControl.DefinitionObjectChanged, IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1, IG.Forms.InputOutputDataDefinitionControl.InputLengthChanged, IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2, IG.Forms.InputOutputDataDefinitionControl.OutputLengthChanged, and IG.Num.InputOutputDataDefiniton.ToString().
menuSummary_Click() [2/3]
void IG.Forms.InputOutputDataDefinitionControl.menuSummary_Click (object sender, EventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.CreateSummary(), and IG.Forms.FadingMessage.Launch().
numNumInputParameters_Validated() [2/3]
void IG.Forms.InputOutputDataDefinitionControl.numNumInputParameters_Validated (object sender, EventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.InputLength, and IG.Forms.InputOutputDataDefinitionControl.numNumInputParameters.
numNumOutputValues_Validated() [2/3]
void IG.Forms.InputOutputDataDefinitionControl.numNumOutputValues_Validated (object sender, EventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.numNumInputParameters, and IG.Forms.InputOutputDataDefinitionControl.OutputLength.
txtName_Validated() [2/3]
void IG.Forms.InputOutputDataDefinitionControl.txtName_Validated (object sender, EventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.DataName, and IG.Forms.InputOutputDataDefinitionControl.txtName.
txtDescription_Validated() [2/3]
void IG.Forms.InputOutputDataDefinitionControl.txtDescription_Validated (object sender, EventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.DataDescription, and IG.Forms.InputOutputDataDefinitionControl.txtDescription.
btnLoad_Click() [2/3]
void IG.Forms.InputOutputDataDefinitionControl.btnLoad_Click (object sender, EventArgs e) inline private
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.InputOutputDataDefinitionControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.InputOutputDataDefinitionControl.fileSelector1, IG.Forms.FileSelector.Filter, IG.Forms.InputOutputDataDefinitionControl.HasUnsavedChanges, IG.Num.InputOutputDataDefiniton.LoadJson(), IG.Forms.InputOutputDataDefinitionControl.Reporter, and IG.Lib.IReporterBase.ReportError().
btnSave_Click() [2/3]
void IG.Forms.InputOutputDataDefinitionControl.btnSave_Click (object sender, EventArgs e) inline private
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.InputOutputDataDefinitionControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.InputOutputDataDefinitionControl.fileSelector1, IG.Forms.FileSelector.Filter, IG.Forms.InputOutputDataDefinitionControl.HasUnsavedChanges, IG.Forms.InputOutputDataDefinitionControl.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.IReporterBase.ReportWarning(), and IG.Num.InputOutputDataDefiniton.SaveJson().
btnGenerateTestData_Click() [2/3]
void IG.Forms.InputOutputDataDefinitionControl.btnGenerateTestData_Click (object sender, EventArgs e) inline private
References IG.Num.InputOutputDataDefiniton.CreateDefault(), IG.Forms.InputOutputDataDefinitionControl.DataDefinition, IG.Forms.InputOutputDataDefinitionControl.InputLength, and IG.Forms.InputOutputDataDefinitionControl.OutputLength.
btnLoadFromFunction_Click() [2/3]
void IG.Forms.InputOutputDataDefinitionControl.btnLoadFromFunction_Click (object sender, EventArgs e) inline private
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.InputOutputDataDefinitionControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.InputOutputDataDefinitionControl.fileSelector1, IG.Forms.FileSelector.Filter, IG.Forms.InputOutputDataDefinitionControl.HasUnsavedChanges, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.LoadJson(), IG.Forms.InputOutputDataDefinitionControl.Reporter, and IG.Lib.IReporterBase.ReportError().
inputDataDefinitionControl1_NumElementsChanged() [2/3]
void IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1_NumElementsChanged (object sender, IndexChangeEventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1, IG.Forms.InputOutputDataDefinitionControl.InputLength, IG.Forms.InpuOrOutputtDataDefinitionControl.InputLength, IG.Forms.ValueChangeEventArgs< ValueType >.New, and IG.Forms.ValueChangeEventArgs< ValueType >.NewDefined.
outputDataDefinitionControl2_NumElementsChanged() [2/3]
void IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2_NumElementsChanged (object sender, IndexChangeEventArgs e) inline private
References IG.Forms.ValueChangeEventArgs< ValueType >.New, IG.Forms.ValueChangeEventArgs< ValueType >.NewDefined, IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2, IG.Forms.InputOutputDataDefinitionControl.OutputLength, and IG.Forms.InpuOrOutputtDataDefinitionControl.OutputLength.
Dispose() [2/3]
override void IG.Forms.InputOutputDataDefinitionControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.InputOutputDataDefinitionControl.components.
InitializeComponent() [2/3]
void IG.Forms.InputOutputDataDefinitionControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.InputOutputDataDefinitionControl.btnGenerateTestData, IG.Forms.InputOutputDataDefinitionControl.btnGenerateTestData_Click(), IG.Forms.InputOutputDataDefinitionControl.btnLoad, IG.Forms.InputOutputDataDefinitionControl.btnLoad_Click(), IG.Forms.InputOutputDataDefinitionControl.btnLoadFromFunction, IG.Forms.InputOutputDataDefinitionControl.btnLoadFromFunction_Click(), IG.Forms.InputOutputDataDefinitionControl.btnSave, IG.Forms.InputOutputDataDefinitionControl.btnSave_Click(), IG.Forms.InputOutputDataDefinitionControl.btnToDeleteLater, IG.Forms.InputOutputDataDefinitionControl.components, IG.Forms.InputOutputDataDefinitionControl.contextMenuStrip1, IG.Forms.InpuOrOutputtDataDefinitionControl.DataDefinition, IG.Forms.InputOutputDataDefinitionControl.fileSelector1, IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1, IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1_NumElementsChanged(), IG.Forms.InpuOrOutputtDataDefinitionControl.InputLength, IG.Forms.InpuOrOutputtDataDefinitionControl.IsDimentionChangeAllowed, IG.Forms.InpuOrOutputtDataDefinitionControl.IsInputData, IG.Forms.InputOutputDataDefinitionControl.lblDescription, IG.Forms.InputOutputDataDefinitionControl.lblMainTitle, IG.Forms.InputOutputDataDefinitionControl.lblName, IG.Forms.InputOutputDataDefinitionControl.lblNminputParameters, IG.Forms.InputOutputDataDefinitionControl.lblNumOutputValues, IG.Forms.InputOutputDataDefinitionControl.menuSummary, IG.Forms.InpuOrOutputtDataDefinitionControl.NumElementsChanged, IG.Forms.InputOutputDataDefinitionControl.numNumInputParameters, IG.Forms.InputOutputDataDefinitionControl.numNumInputParameters_Validated(), IG.Forms.InputOutputDataDefinitionControl.numNumOutputValues, IG.Forms.InputOutputDataDefinitionControl.numNumOutputValues_Validated(), IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2, IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2_NumElementsChanged(), IG.Forms.InpuOrOutputtDataDefinitionControl.OutputLength, IG.Forms.InputOutputDataDefinitionControl.pnlControls, IG.Forms.InputOutputDataDefinitionControl.splitContainer1, IG.Forms.InpuOrOutputtDataDefinitionControl.Title, IG.Forms.InputOutputDataDefinitionControl.txtDescription, IG.Forms.InputOutputDataDefinitionControl.txtDescription_Validated(), IG.Forms.InputOutputDataDefinitionControl.txtName, IG.Forms.InputOutputDataDefinitionControl.txtName_Validated(), and IG.Forms.InpuOrOutputtDataDefinitionControl.UseLegalVariableNames.
OnDefinitionObjectChanged() [3/3]
void IG.Forms.InputOutputDataDefinitionControl.OnDefinitionObjectChanged (InputOutputDataDefiniton oldDataDefinition, InputOutputDataDefiniton newDataDefinition) inline protected
Raises the DefinitionObjectChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldDataDefinition Old data definition object.
newDataDefinition New data definition object.
References IG.Forms.InputOutputDataDefinitionControl.DefinitionObjectChanged.
OnInputLengthChanged() [3/3]
void IG.Forms.InputOutputDataDefinitionControl.OnInputLengthChanged (int oldLength, int newLength) inline protected
Raises the InputLengthChanged event. This method should be called preferrably, rather than the event itself.
Parameters
oldLength Old length.
newLength New length.
References IG.Forms.InputOutputDataDefinitionControl.InputLengthChanged.
OnOutputLengthChanged() [3/3]
void IG.Forms.InputOutputDataDefinitionControl.OnOutputLengthChanged (int oldLength, int newLength) inline protected
Raises the <see cref=OutputLengthChanged"/> event. This method should be called preferrably, rather than the event itself.
Parameters
oldLength Old length.
newLength New length.
References IG.Forms.InputOutputDataDefinitionControl.OutputLengthChanged.
CreateSummary() [3/3]
virtual string IG.Forms.InputOutputDataDefinitionControl.CreateSummary () inline virtual
References IG.Forms.InpuOrOutputtDataDefinitionControl.CreateSummary(), IG.Forms.InputOutputDataDefinitionControl.DataDefinition, IG.Forms.InputOutputDataDefinitionControl.DefinitionObjectChanged, IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1, IG.Forms.InputOutputDataDefinitionControl.InputLengthChanged, IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2, IG.Forms.InputOutputDataDefinitionControl.OutputLengthChanged, and IG.Num.InputOutputDataDefiniton.ToString().
menuSummary_Click() [3/3]
void IG.Forms.InputOutputDataDefinitionControl.menuSummary_Click (object sender, EventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.CreateSummary(), and IG.Forms.FadingMessage.Launch().
numNumInputParameters_Validated() [3/3]
void IG.Forms.InputOutputDataDefinitionControl.numNumInputParameters_Validated (object sender, EventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.InputLength, and IG.Forms.InputOutputDataDefinitionControl.numNumInputParameters.
numNumOutputValues_Validated() [3/3]
void IG.Forms.InputOutputDataDefinitionControl.numNumOutputValues_Validated (object sender, EventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.numNumInputParameters, and IG.Forms.InputOutputDataDefinitionControl.OutputLength.
txtName_Validated() [3/3]
void IG.Forms.InputOutputDataDefinitionControl.txtName_Validated (object sender, EventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.DataName, and IG.Forms.InputOutputDataDefinitionControl.txtName.
txtDescription_Validated() [3/3]
void IG.Forms.InputOutputDataDefinitionControl.txtDescription_Validated (object sender, EventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.DataDescription, and IG.Forms.InputOutputDataDefinitionControl.txtDescription.
btnLoad_Click() [3/3]
void IG.Forms.InputOutputDataDefinitionControl.btnLoad_Click (object sender, EventArgs e) inline private
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.InputOutputDataDefinitionControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.InputOutputDataDefinitionControl.fileSelector1, IG.Forms.FileSelector.Filter, IG.Forms.InputOutputDataDefinitionControl.HasUnsavedChanges, IG.Num.InputOutputDataDefiniton.LoadJson(), IG.Forms.InputOutputDataDefinitionControl.Reporter, and IG.Lib.IReporterBase.ReportError().
btnSave_Click() [3/3]
void IG.Forms.InputOutputDataDefinitionControl.btnSave_Click (object sender, EventArgs e) inline private
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.InputOutputDataDefinitionControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.InputOutputDataDefinitionControl.fileSelector1, IG.Forms.FileSelector.Filter, IG.Forms.InputOutputDataDefinitionControl.HasUnsavedChanges, IG.Forms.InputOutputDataDefinitionControl.Reporter, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.IReporterBase.ReportWarning(), and IG.Num.InputOutputDataDefiniton.SaveJson().
btnGenerateTestData_Click() [3/3]
void IG.Forms.InputOutputDataDefinitionControl.btnGenerateTestData_Click (object sender, EventArgs e) inline private
References IG.Num.InputOutputDataDefiniton.CreateDefault(), IG.Forms.InputOutputDataDefinitionControl.DataDefinition, IG.Forms.InputOutputDataDefinitionControl.InputLength, and IG.Forms.InputOutputDataDefinitionControl.OutputLength.
btnLoadFromFunction_Click() [3/3]
void IG.Forms.InputOutputDataDefinitionControl.btnLoadFromFunction_Click (object sender, EventArgs e) inline private
References IG.Forms.FileSelector.AllowExistentFiles, IG.Forms.FileSelector.AllowNonexistentFiles, IG.Forms.FileSelector.BrowseFile(), IG.Forms.InputOutputDataDefinitionControl.DataDefinition, IG.Forms.FileSelector.FilePath, IG.Forms.InputOutputDataDefinitionControl.fileSelector1, IG.Forms.FileSelector.Filter, IG.Forms.InputOutputDataDefinitionControl.HasUnsavedChanges, IG.Num.VectorFunctionScriptControllerBase< VectorFunctionType, ScalarFunctionControllerType, ScalarFunctionType >.LoadJson(), IG.Forms.InputOutputDataDefinitionControl.Reporter, and IG.Lib.IReporterBase.ReportError().
inputDataDefinitionControl1_NumElementsChanged() [3/3]
void IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1_NumElementsChanged (object sender, IndexChangeEventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.HasUnsavedChanges, IG.Forms.InpuOrOutputtDataDefinitionControl.HasUnsavedChanges, IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1, IG.Forms.InputOutputDataDefinitionControl.InputLength, IG.Forms.InpuOrOutputtDataDefinitionControl.InputLength, IG.Forms.ValueChangeEventArgs< ValueType >.New, and IG.Forms.ValueChangeEventArgs< ValueType >.NewDefined.
outputDataDefinitionControl2_NumElementsChanged() [3/3]
void IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2_NumElementsChanged (object sender, IndexChangeEventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.HasUnsavedChanges, IG.Forms.InpuOrOutputtDataDefinitionControl.HasUnsavedChanges, IG.Forms.ValueChangeEventArgs< ValueType >.New, IG.Forms.ValueChangeEventArgs< ValueType >.NewDefined, IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2, IG.Forms.InputOutputDataDefinitionControl.OutputLength, and IG.Forms.InpuOrOutputtDataDefinitionControl.OutputLength.
inputDataDefinitionControl1_DataChanged() [2/2]
void IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1_DataChanged (object sender, EventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.HasUnsavedChanges.
outputDataDefinitionControl2_DataChanged() [2/2]
void IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2_DataChanged (object sender, EventArgs e) inline private
References IG.Forms.InputOutputDataDefinitionControl.HasUnsavedChanges.
Dispose() [3/3]
override void IG.Forms.InputOutputDataDefinitionControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.InputOutputDataDefinitionControl.components.
InitializeComponent() [3/3]
void IG.Forms.InputOutputDataDefinitionControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.InputOutputDataDefinitionControl.btnGenerateTestData, IG.Forms.InputOutputDataDefinitionControl.btnGenerateTestData_Click(), IG.Forms.InputOutputDataDefinitionControl.btnLoad, IG.Forms.InputOutputDataDefinitionControl.btnLoad_Click(), IG.Forms.InputOutputDataDefinitionControl.btnLoadFromFunction, IG.Forms.InputOutputDataDefinitionControl.btnLoadFromFunction_Click(), IG.Forms.InputOutputDataDefinitionControl.btnSave, IG.Forms.InputOutputDataDefinitionControl.btnSave_Click(), IG.Forms.InputOutputDataDefinitionControl.components, IG.Forms.InputOutputDataDefinitionControl.contextMenuStrip1, IG.Forms.InpuOrOutputtDataDefinitionControl.DataDefinition, IG.Forms.InputOutputDataDefinitionControl.fileSelector1, IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1, IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1_DataChanged(), IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1_NumElementsChanged(), IG.Forms.InpuOrOutputtDataDefinitionControl.InputLength, IG.Forms.InpuOrOutputtDataDefinitionControl.IsDimentionChangeAllowed, IG.Forms.InpuOrOutputtDataDefinitionControl.IsInputData, IG.Forms.InputOutputDataDefinitionControl.lblDescription, IG.Forms.InputOutputDataDefinitionControl.lblMainTitle, IG.Forms.InputOutputDataDefinitionControl.lblName, IG.Forms.InputOutputDataDefinitionControl.lblNminputParameters, IG.Forms.InputOutputDataDefinitionControl.lblNumOutputValues, IG.Forms.InputOutputDataDefinitionControl.menuSummary, IG.Forms.InpuOrOutputtDataDefinitionControl.NumElementsChanged, IG.Forms.InputOutputDataDefinitionControl.numNumInputParameters, IG.Forms.InputOutputDataDefinitionControl.numNumInputParameters_Validated(), IG.Forms.InputOutputDataDefinitionControl.numNumOutputValues, IG.Forms.InputOutputDataDefinitionControl.numNumOutputValues_Validated(), IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2, IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2_DataChanged(), IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2_NumElementsChanged(), IG.Forms.InpuOrOutputtDataDefinitionControl.OutputLength, IG.Forms.InputOutputDataDefinitionControl.pnlControls, IG.Forms.InputOutputDataDefinitionControl.splitContainer1, IG.Forms.InpuOrOutputtDataDefinitionControl.TitleInputData, IG.Forms.InpuOrOutputtDataDefinitionControl.TitleOutputData, IG.Forms.InputOutputDataDefinitionControl.txtDescription, IG.Forms.InputOutputDataDefinitionControl.txtDescription_Validated(), IG.Forms.InputOutputDataDefinitionControl.txtName, IG.Forms.InputOutputDataDefinitionControl.txtName_Validated(), and IG.Forms.InpuOrOutputtDataDefinitionControl.UseLegalVariableNames.
Member Data Documentation
_dataDefinition
InputOutputDataDefiniton IG.Forms.InputOutputDataDefinitionControl._dataDefinition protected
_inputLength
int IG.Forms.InputOutputDataDefinitionControl._inputLength protected
_outputLength
int IG.Forms.InputOutputDataDefinitionControl._outputLength protected
_name
string IG.Forms.InputOutputDataDefinitionControl._name protected
_description
string IG.Forms.InputOutputDataDefinitionControl._description protected
_title
string IG.Forms.InputOutputDataDefinitionControl._title = "Input and Output Data Definition" private
_hasUnsavedChanges
bool IG.Forms.InputOutputDataDefinitionControl._hasUnsavedChanges = false private
_isDimentionChangeAllowed
bool IG.Forms.InputOutputDataDefinitionControl._isDimentionChangeAllowed = true private
_useLegalVariableNames
bool IG.Forms.InputOutputDataDefinitionControl._useLegalVariableNames = true private
components
System ComponentModel IContainer IG.Forms.InputOutputDataDefinitionControl.components = null private
Required designer variable.
Referenced by IG.Forms.InputOutputDataDefinitionControl.Dispose(), and IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
lblMainTitle
System Windows Forms Label IG.Forms.InputOutputDataDefinitionControl.lblMainTitle private
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), and IG.Forms.InputOutputDataDefinitionControl.InputOutputDataDefinitionControl().
inputDataDefinitionControl1 [1/2]
IG Forms InputDataDefinitionControl IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1 private
Referenced by IG.Forms.InputOutputDataDefinitionControl.CreateSummary(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1_DataChanged(), IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1_NumElementsChanged(), and IG.Forms.InputOutputDataDefinitionControl.InputOutputDataDefinitionControl().
outputDataDefinitionControl2 [1/2]
IG Forms InputDataDefinitionControl IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2 private
Referenced by IG.Forms.InputOutputDataDefinitionControl.CreateSummary(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.InputOutputDataDefinitionControl.InputOutputDataDefinitionControl(), IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2_DataChanged(), and IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2_NumElementsChanged().
pnlControls
System Windows Forms Panel IG.Forms.InputOutputDataDefinitionControl.pnlControls private
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
btnSave
System Windows Forms Button IG.Forms.InputOutputDataDefinitionControl.btnSave private
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
btnLoadFromFunction
System Windows Forms Button IG.Forms.InputOutputDataDefinitionControl.btnLoadFromFunction private
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
btnLoad
System Windows Forms Button IG.Forms.InputOutputDataDefinitionControl.btnLoad private
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
contextMenuStrip1
System Windows Forms ContextMenuStrip IG.Forms.InputOutputDataDefinitionControl.contextMenuStrip1 private
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
menuSummary
System Windows Forms ToolStripMenuItem IG.Forms.InputOutputDataDefinitionControl.menuSummary private
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
lblNumOutputValues
System Windows Forms Label IG.Forms.InputOutputDataDefinitionControl.lblNumOutputValues private
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
lblNminputParameters
System Windows Forms Label IG.Forms.InputOutputDataDefinitionControl.lblNminputParameters private
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
numNumOutputValues
System Windows Forms NumericUpDown IG.Forms.InputOutputDataDefinitionControl.numNumOutputValues private
Referenced by IG.Forms.InputOutputDataDefinitionControl.btnGenerateTestData_Click(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), and IG.Forms.InputOutputDataDefinitionControl.numNumOutputValues_Validated().
numNumInputParameters
System Windows Forms NumericUpDown IG.Forms.InputOutputDataDefinitionControl.numNumInputParameters private
Referenced by IG.Forms.InputOutputDataDefinitionControl.btnGenerateTestData_Click(), IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), IG.Forms.InputOutputDataDefinitionControl.numNumInputParameters_Validated(), and IG.Forms.InputOutputDataDefinitionControl.numNumOutputValues_Validated().
btnGenerateTestData
System Windows Forms Button IG.Forms.InputOutputDataDefinitionControl.btnGenerateTestData private
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
splitContainer1
System Windows Forms SplitContainer IG.Forms.InputOutputDataDefinitionControl.splitContainer1 private
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
txtDescription
System Windows Forms TextBox IG.Forms.InputOutputDataDefinitionControl.txtDescription private
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), and IG.Forms.InputOutputDataDefinitionControl.txtDescription_Validated().
txtName
System Windows Forms TextBox IG.Forms.InputOutputDataDefinitionControl.txtName private
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), and IG.Forms.InputOutputDataDefinitionControl.txtName_Validated().
lblDescription
System Windows Forms Label IG.Forms.InputOutputDataDefinitionControl.lblDescription private
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
lblName
System Windows Forms Label IG.Forms.InputOutputDataDefinitionControl.lblName private
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
fileSelector1
FileSelector IG.Forms.InputOutputDataDefinitionControl.fileSelector1 private
Referenced by IG.Forms.InputOutputDataDefinitionControl.btnLoad_Click(), IG.Forms.InputOutputDataDefinitionControl.btnLoadFromFunction_Click(), IG.Forms.InputOutputDataDefinitionControl.btnSave_Click(), and IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
indicatorLight1
IndicatorLight IG.Forms.InputOutputDataDefinitionControl.indicatorLight1 private
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent(), and IG.Forms.InputOutputDataDefinitionControl.OnDefinitionObjectChanged().
inputDataDefinitionControl1 [2/2]
IG.Forms.InputDataDefinitionControl IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1 private
outputDataDefinitionControl2 [2/2]
IG.Forms.InputDataDefinitionControl IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2 private
btnToDeleteLater
System.Windows.Forms.Button IG.Forms.InputOutputDataDefinitionControl.btnToDeleteLater private
Referenced by IG.Forms.InputOutputDataDefinitionControl.InitializeComponent().
Property Documentation
Reporter
IG Lib IReporter IG.Forms.InputOutputDataDefinitionControl.Reporter get protected
Reporter used for internal reporting.
Referenced by IG.Forms.InputOutputDataDefinitionControl.btnGenerateTestData_Click(), IG.Forms.InputOutputDataDefinitionControl.btnLoad_Click(), IG.Forms.InputOutputDataDefinitionControl.btnLoadFromFunction_Click(), and IG.Forms.InputOutputDataDefinitionControl.btnSave_Click().
InputDataControl [1/2]
InputDataDefinitionControl IG.Forms.InputOutputDataDefinitionControl.InputDataControl get
Gets control used for editing definitions of input data elements.
Referenced by IG.Forms.InputOutputDataDefinitionForm.InputOutputDataDefinitionForm().
OutputDataControl [1/2]
InputDataDefinitionControl IG.Forms.InputOutputDataDefinitionControl.OutputDataControl get
Gets control used for editing definitions of output data elements.
Referenced by IG.Forms.InputOutputDataDefinitionForm.InputOutputDataDefinitionForm().
DataDefinition
InputOutputDataDefiniton IG.Forms.InputOutputDataDefinitionControl.DataDefinition get set
Data about input and output quantities of the manipulated functions or response.
Referenced by IG.Forms.InputOutputDataDefinitionControl.btnGenerateTestData_Click(), IG.Forms.InputOutputDataDefinitionControl.btnLoad_Click(), IG.Forms.InputOutputDataDefinitionControl.btnLoadFromFunction_Click(), IG.Forms.InputOutputDataDefinitionControl.btnSave_Click(), and IG.Forms.InputOutputDataDefinitionControl.CreateSummary().
InputLength
int IG.Forms.InputOutputDataDefinitionControl.InputLength get protected set
Number of input parameters or data elements.
Referenced by IG.Forms.InputOutputDataDefinitionControl.btnGenerateTestData_Click(), IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1_NumElementsChanged(), and IG.Forms.InputOutputDataDefinitionControl.numNumInputParameters_Validated().
OutputLength
int IG.Forms.InputOutputDataDefinitionControl.OutputLength get protected set
Number of input parameters or data elements.
Referenced by IG.Forms.InputOutputDataDefinitionControl.btnGenerateTestData_Click(), IG.Forms.InputOutputDataDefinitionControl.numNumOutputValues_Validated(), and IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2_NumElementsChanged().
DataName
string IG.Forms.InputOutputDataDefinitionControl.DataName get protected set
Name of the data defined by DataDefinition
Referenced by IG.Forms.InputOutputDataDefinitionControl.txtName_Validated().
DataDescription
string IG.Forms.InputOutputDataDefinitionControl.DataDescription get protected set
Description of the data defined by DataDefinition
Referenced by IG.Forms.InputOutputDataDefinitionControl.txtDescription_Validated().
Title
string IG.Forms.InputOutputDataDefinitionControl.Title get set
Title that is shown on the top of control, in the lblMainTitle label.
TitleWithChangedSign
string IG.Forms.InputOutputDataDefinitionControl.TitleWithChangedSign get
Actual title that is shown on the top of control, in the lblMainTitle label, includes eventual marks for unsaved changes.
Referenced by IG.Forms.InputOutputDataDefinitionControl.InputOutputDataDefinitionControl().
HasUnsavedChanges
bool IG.Forms.InputOutputDataDefinitionControl.HasUnsavedChanges get set
Whether the current function definition has unsaved changes.
Referenced by IG.Forms.InputOutputDataDefinitionControl.btnGenerateTestData_Click(), IG.Forms.InputOutputDataDefinitionControl.btnLoad_Click(), IG.Forms.InputOutputDataDefinitionControl.btnLoadFromFunction_Click(), IG.Forms.InputOutputDataDefinitionControl.btnSave_Click(), IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1_DataChanged(), IG.Forms.InputOutputDataDefinitionControl.inputDataDefinitionControl1_NumElementsChanged(), IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2_DataChanged(), and IG.Forms.InputOutputDataDefinitionControl.outputDataDefinitionControl2_NumElementsChanged().
IsDimentionChangeAllowed
bool IG.Forms.InputOutputDataDefinitionControl.IsDimentionChangeAllowed get set
Indicates whetherr user can change dimensions (number of input/output data elements).
UseLegalVariableNames
bool IG.Forms.InputOutputDataDefinitionControl.UseLegalVariableNames get set
Specifies whether legal variable names (according to rules in programming languages such as C++, C# or Java) should be enforced for naming input and utput elements.
InputDataControl [2/2]
InputDataDefinitionControl IG.Forms.InputOutputDataDefinitionControl.InputDataControl get
Gets control used for editing definitions of input data elements.
OutputDataControl [2/2]
InputDataDefinitionControl IG.Forms.InputOutputDataDefinitionControl.OutputDataControl get
Gets control used for editing definitions of output data elements.
Event Documentation
DefinitionObjectChanged
EventHandler< ValueChangeEventArgs< InputOutputDataDefiniton > > IG.Forms.InputOutputDataDefinitionControl.DefinitionObjectChanged
Occurs when data definition object is changed (i.e., when object reference changes), meaning that whole data definition object is replaced.
Referenced by IG.Forms.InputOutputDataDefinitionControl.CreateSummary(), and IG.Forms.InputOutputDataDefinitionControl.OnDefinitionObjectChanged().
InputLengthChanged
EventHandler< IndexChangeEventArgs > IG.Forms.InputOutputDataDefinitionControl.InputLengthChanged
Occurs when number of input parameters (InputLength) is changed.
Referenced by IG.Forms.InputOutputDataDefinitionControl.CreateSummary(), and IG.Forms.InputOutputDataDefinitionControl.OnInputLengthChanged().
OutputLengthChanged
EventHandler< IndexChangeEventArgs > IG.Forms.InputOutputDataDefinitionControl.OutputLengthChanged
Occurs when number of output values (OutputLength) is changed.
Referenced by IG.Forms.InputOutputDataDefinitionControl.CreateSummary(), and IG.Forms.InputOutputDataDefinitionControl.OnOutputLengthChanged().
InputElementDataChanged
EventHandler IG.Forms.InputOutputDataDefinitionControl.InputElementDataChanged
Occurs when some input element property is changed.
Referenced by IG.Forms.InputOutputDataDefinitionControl.CreateSummary(), and IG.Forms.InputOutputDataDefinitionControl.OnInputElementDataChanged().
OutputElementDataChanged
EventHandler IG.Forms.InputOutputDataDefinitionControl.OutputElementDataChanged
Occurs when some output element property is changed.
Referenced by IG.Forms.InputOutputDataDefinitionControl.CreateSummary(), and IG.Forms.InputOutputDataDefinitionControl.OnOutputElementDataChanged().
The documentation for this class was generated from the following files:
iglib/extensions/iglibext/Forms/Numeric/FromNeural/Basic/InputOutputDataDefinitionControl.cs
iglib/extensions/iglibext/Forms/Numeric/FromNeural/Basic/InputOutputDataDefinitionControl.Designer.cs