Doc: IGLib EXTENDED: CShell.Framework.Sink Class Reference
CShell.Framework.Sink Class Reference abstract
Public Member Functions
virtual void Dump (object o)
abstract void Dump (object o, string description)
abstract void Clear ()
Public Member Functions inherited from CShell.Framework.Document
virtual void Save ()
virtual void SaveAs (string newFile)
Protected Member Functions
Sink ()
string GetUriPathPart (Uri uri, int pathIndex)
Gets the display name from the uri, which is usually the second part of the absolute path.
string GetTitle (Uri uri, string defaultTitle)
Properties
virtual Uri IconSource [get]
bool IsVisible [get, set]
virtual PaneLocation PreferredLocation [get]
Properties inherited from CShell.Framework.Document
ICommand?? CloseCommand [get]
virtual Uri Uri [get, set]
virtual bool IsDirty [get, set]
Properties inherited from CShell.Framework.IDocument
ICommand CloseCommand [get]
Uri Uri [get]
bool IsDirty [get]
Properties inherited from CShell.Framework.ISink
PaneLocation PreferredLocation [get]
bool IsVisible [get, set]
Private Attributes
bool _isVisible
Constructor & Destructor Documentation
Sink()
CShell.Framework.Sink.Sink () inline protected
References CShell.Framework.Sink.IsVisible.
Member Function Documentation
Dump() [1/2]
virtual void CShell.Framework.Sink.Dump (object o) inline virtual
Implements CShell.Framework.ISink.
Dump() [2/2]
abstract void CShell.Framework.Sink.Dump (object o, string description) pure virtual
Implements CShell.Framework.ISink.
Implemented in CShell.Modules.Sink.ViewModels.PlotSinkViewModel, CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel, CShell.Modules.Sink.ViewModels.ControlSinkViewModel, and CShell.Modules.Sink.ViewModels.GridSinkViewModel.
Clear()
abstract void CShell.Framework.Sink.Clear () pure virtual
Implements CShell.Framework.ISink.
Implemented in CShell.Modules.Sink.ViewModels.PlotSinkViewModel, CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel, CShell.Modules.Sink.ViewModels.ControlSinkViewModel, and CShell.Modules.Sink.ViewModels.GridSinkViewModel.
GetUriPathPart()
string CShell.Framework.Sink.GetUriPathPart (Uri uri, int pathIndex) inline protected
Gets the display name from the uri, which is usually the second part of the absolute path.
Parameters
uri The URI.
pathIndex Zero based index. 0 gets the first part of the path, e.g. /mypah/hello -> "mypath"
Returns
The name of the path part if the path contains such a item, otherwise returns null.
Referenced by CShell.Framework.Sink.GetTitle().
GetTitle()
string CShell.Framework.Sink.GetTitle (Uri uri, string defaultTitle) inline protected
References CShell.Framework.Sink.GetUriPathPart(), and CShell.Framework.Document.Uri.
Referenced by CShell.Modules.Sink.ViewModels.ControlSinkViewModel.ControlSinkViewModel(), CShell.Modules.Sink.ViewModels.GridSinkViewModel.GridSinkViewModel(), CShell.Modules.Sink.ViewModels.PlotSinkViewModel.PlotSinkViewModel(), and CShell.Modules.Sink.ViewModels.XhtmlSinkViewModel.XhtmlSinkViewModel().
Member Data Documentation
_isVisible
bool CShell.Framework.Sink._isVisible private
Property Documentation
IconSource
virtual Uri CShell.Framework.Sink.IconSource get
IsVisible
bool CShell.Framework.Sink.IsVisible get set
Referenced by CShell.Framework.Sink.Sink().
PreferredLocation
virtual PaneLocation CShell.Framework.Sink.PreferredLocation get
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore/Framework/Sink.cs