Doc: IGLib EXTENDED: NumLib.FunctionWithGradient Class Reference
NumLib.FunctionWithGradient Class Reference abstract
Base class for implementation of various functions with gradients.
Public Member Functions
abstract double Value (double[] parameters)
Returns function value at the specified parameters.
abstract double[] Gradient (double[] parameters)
Returns function value at the specified parameters.
Static Public Member Functions
static double Norm (double[] x)
Calculates and returns Euclidean norm of the specified vector.
static string ArrayToString (double[] x)
Properties
abstract string Description [get]
Detailed Description
Base class for implementation of various functions with gradients.
Member Function Documentation
Value()
abstract double NumLib.FunctionWithGradient.Value (double[] parameters) pure virtual
Returns function value at the specified parameters.
Parameters
parameters Parameters where function is evaluated.
Implemented in NumLib.RosenbrockFunction, and NumLib.QuadraticFunctionShifted.
Referenced by NumLib.MinimizerLbfgs.Minimize(), and NumLib.MinimizerLbfgs.NextIteration().
Gradient()
abstract double [] NumLib.FunctionWithGradient.Gradient (double[] parameters) pure virtual
Returns function value at the specified parameters.
Parameters
parameters Parameters where function is evaluated.
Implemented in NumLib.RosenbrockFunction, and NumLib.QuadraticFunctionShifted.
Referenced by NumLib.MinimizerLbfgs.Minimize(), and NumLib.MinimizerLbfgs.NextIteration().
Norm()
static double NumLib.FunctionWithGradient.Norm (double[] x) inline static
Calculates and returns Euclidean norm of the specified vector.
Parameters
x Array of elements of the vector for which norm is calculated.
Returns
Referenced by NumLib.MinimizerLbfgs.Minimize(), NumLib.MinimizerLbfgs.NextIteration(), NumLib.ExampleAlgLib2008.OptimizeQuadratic(), and NumLib.ExampleAlgLib2008.OptimizeRosenbrock().
ArrayToString()
static string NumLib.FunctionWithGradient.ArrayToString (double[] x) inline static
Referenced by NumLib.MinimizerLbfgs.Minimize(), NumLib.MinimizerLbfgs.NextIteration(), and NumLib.ExampleAlgLib2008.OptimizeQuadratic().
Property Documentation
Description
abstract string NumLib.FunctionWithGradient.Description get
Referenced by NumLib.MinimizerLbfgs.Minimize().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/opt/alglib/Alglib_Old_UniMb/0Functions.cs