Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.IDAMAX Class Reference
DotNumerics.LinearAlgebra.CSLapack.IDAMAX Class Reference
Public Member Functions
IDAMAX ()
int Run (int N, double[] DX, int offset_dx, int INCX)
Detailed Description
Purpose
finds the index of element having max. absolute value. jack dongarra, linpack, 3/11/78. modified 3/93 to return if incx .le. 0. modified 12/3/93, array(1) declarations changed to array(*) /summary>
Constructor & Destructor Documentation
IDAMAX()
DotNumerics.LinearAlgebra.CSLapack.IDAMAX.IDAMAX () inline
Member Function Documentation
Run()
int DotNumerics.LinearAlgebra.CSLapack.IDAMAX.Run (int N, double[] DX, int offset_dx, int INCX) inline
Purpose
finds the index of element having max. absolute value. jack dongarra, linpack, 3/11/78. modified 3/93 to return if incx .le. 0. modified 12/3/93, array(1) declarations changed to array(*) /summary>
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLACON.Run(), DotNumerics.LinearAlgebra.CSLapack.DGBTF2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGETF2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQPF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQP2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGBTRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBAL.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRCON.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQPS.Run(), DotNumerics.LinearAlgebra.CSLapack.DLATRS.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED8.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALSD.Run(), DotNumerics.LinearAlgebra.CSLapack.DTREVC.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASY2.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/idamax.cs