Doc: IGLib EXTENDED: alglib.reflections Class Reference
alglib.reflections Class Reference
Static Public Member Functions
static void generatereflection (ref double[] x, int n, ref double tau)
static void applyreflectionfromtheleft (ref double[,] c, double tau, double[] v, int m1, int m2, int n1, int n2, ref double[] work)
static void applyreflectionfromtheright (ref double[,] c, double tau, double[] v, int m1, int m2, int n1, int n2, ref double[] work)
static void generatereflection (ref double[] x, int n, ref double tau)
static void applyreflectionfromtheleft (ref double[,] c, double tau, double[] v, int m1, int m2, int n1, int n2, ref double[] work)
static void applyreflectionfromtheright (ref double[,] c, double tau, double[] v, int m1, int m2, int n1, int n2, ref double[] work)
Member Function Documentation
generatereflection() [1/2]
static void alglib.reflections.generatereflection (ref double[] x, int n, ref double tau) inline static
References alglib.beta(), alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.math.minrealnumber, and alglib.math.sqr().
Referenced by alglib.idwint.idwinternalsolver(), alglib.hsschur.internalauxschur(), alglib.hsschur.internalschurdecomposition(), and alglib.testreflectionsunit.testreflections().
applyreflectionfromtheleft() [1/2]
static void alglib.reflections.applyreflectionfromtheleft (ref double c[,], double tau, double[] v, int m1, int m2, int n1, int n2, ref double[] work) inline static
Referenced by alglib.hsschur.internalschurdecomposition(), alglib.ortfac.rmatrixqr(), and alglib.testreflectionsunit.testreflections().
applyreflectionfromtheright() [1/2]
static void alglib.reflections.applyreflectionfromtheright (ref double c[,], double tau, double[] v, int m1, int m2, int n1, int n2, ref double[] work) inline static
Referenced by alglib.hsschur.internalschurdecomposition(), alglib.ortfac.rmatrixlq(), and alglib.testreflectionsunit.testreflections().
generatereflection() [2/2]
static void alglib.reflections.generatereflection (ref double[] x, int n, ref double tau) inline static
References alglib.beta(), alglib.math.machineepsilon, alglib.math.maxrealnumber, alglib.math.minrealnumber, and alglib.math.sqr().
applyreflectionfromtheleft() [2/2]
static void alglib.reflections.applyreflectionfromtheleft (ref double c[,], double tau, double[] v, int m1, int m2, int n1, int n2, ref double[] work) inline static
applyreflectionfromtheright() [2/2]
static void alglib.reflections.applyreflectionfromtheright (ref double c[,], double tau, double[] v, int m1, int m2, int n1, int n2, ref double[] work) inline static
References alglib.apserv.touchint().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/alglibinternal.cs