Doc: IGLib EXTENDED: NeuronDotNet.Core.SOM.PositionNeuron Class Reference
NeuronDotNet.Core.SOM.PositionNeuron Class Reference
Position Neuron is a neuron in a two-dimensional space used in Kohonen networks.
Public Member Functions
PositionNeuron (int x, int y, KohonenLayer parent)
Creates new position neuron
PositionNeuron (Point coordinate, KohonenLayer parent)
Creates new positon neuron
void Run ()
Runs the neuron. (Propagates the source synapses and update input and output values)
void Learn (double learningRate)
Trains weights of associated source synapses.
Properties
KohonenLayer Parent [get]
Gets the parent layer containing this neuron
double Value [get]
Gets the neuron value
double INeuron. Input [get, set]
double INeuron. Output [get]
ILayer INeuron. Parent [get]
Point Coordinate [get]
Gets the position of the neuron
IList< ISynapse > SourceSynapses [get]
Gets the list of source synapses associated with this neuron
IList< ISynapse > TargetSynapses [get]
Gets the list of target synapses associated with this neuron
double NeighborhoodValue [get]
Gets the neighborhood of this neuron with respect to the winner neuron in this layer
Properties inherited from NeuronDotNet.Core.INeuron
double Input [get, set]
Gets or sets the neuron input.
double Output [get]
Gets the output of the neuron.
IList< ISynapse > SourceSynapses [get]
Gets the list of source synapses associated with this neuron
IList< ISynapse > TargetSynapses [get]
Gets the list of target synapses associated with this neuron
ILayer Parent [get]
Gets the parent layer containing this neuron
Private Attributes
readonly KohonenLayer parent
readonly Point coordinate
readonly IList< ISynapse > sourceSynapses = new List<ISynapse>()
readonly IList< ISynapse > targetSynapses = new List<ISynapse>()
Detailed Description
Position Neuron is a neuron in a two-dimensional space used in Kohonen networks.
Constructor & Destructor Documentation
PositionNeuron() [1/2]
NeuronDotNet.Core.SOM.PositionNeuron.PositionNeuron (int x, int y, KohonenLayer parent) inline
Creates new position neuron
Parameters
x X-Coordinate of the neuron positon
y Y-Coordinate of the neuron position
parent Parent layer containing this neuron
Exceptions
ArgumentNullException If parent is null
PositionNeuron() [2/2]
NeuronDotNet.Core.SOM.PositionNeuron.PositionNeuron (Point coordinate, KohonenLayer parent) inline
Creates new positon neuron
Parameters
coordinate Neuron Position
parent Parent neuron containing this neuron
If parent is null
References NeuronDotNet.Core.SOM.PositionNeuron.coordinate, NeuronDotNet.Core.SOM.PositionNeuron.parent, and NeuronDotNet.Core.Helper.ValidateNotNull().
Member Function Documentation
Run()
void NeuronDotNet.Core.SOM.PositionNeuron.Run () inline
Runs the neuron. (Propagates the source synapses and update input and output values)
Implements NeuronDotNet.Core.INeuron.
References NeuronDotNet.Core.SOM.PositionNeuron.sourceSynapses.
Learn()
void NeuronDotNet.Core.SOM.PositionNeuron.Learn (double learningRate) inline
Trains weights of associated source synapses.
Parameters
learningRate The current learning rate (this depends on training progress as well)
Implements NeuronDotNet.Core.INeuron.
References NeuronDotNet.Core.SOM.PositionNeuron.sourceSynapses.
Member Data Documentation
parent
readonly KohonenLayer NeuronDotNet.Core.SOM.PositionNeuron.parent private
Referenced by NeuronDotNet.Core.SOM.PositionNeuron.PositionNeuron().
coordinate
readonly Point NeuronDotNet.Core.SOM.PositionNeuron.coordinate private
Referenced by NeuronDotNet.Core.SOM.PositionNeuron.PositionNeuron().
sourceSynapses
readonly IList<ISynapse> NeuronDotNet.Core.SOM.PositionNeuron.sourceSynapses = new List<ISynapse>() private
Referenced by NeuronDotNet.Core.SOM.PositionNeuron.Learn(), and NeuronDotNet.Core.SOM.PositionNeuron.Run().
targetSynapses
readonly IList<ISynapse> NeuronDotNet.Core.SOM.PositionNeuron.targetSynapses = new List<ISynapse>() private
Property Documentation
Parent [1/2]
KohonenLayer NeuronDotNet.Core.SOM.PositionNeuron.Parent get
Gets the parent layer containing this neuron
The parent layer containing this neuron. It is never null
Value
double NeuronDotNet.Core.SOM.PositionNeuron.Value get
Gets the neuron value
Neuron Value
Input
double INeuron. NeuronDotNet.Core.SOM.PositionNeuron.Input get set private
Output
double INeuron. NeuronDotNet.Core.SOM.PositionNeuron.Output get private
Parent [2/2]
ILayer INeuron. NeuronDotNet.Core.SOM.PositionNeuron.Parent get private
Coordinate
Point NeuronDotNet.Core.SOM.PositionNeuron.Coordinate get
Gets the position of the neuron
Neuron Co-ordinate
Referenced by NeuronDotNet.Core.SOM.NeighborhoodFunctions.GaussianFunction.EvaluateNeighborhood(), and NeuronDotNet.Core.SOM.NeighborhoodFunctions.MexicanHatFunction.EvaluateNeighborhood().
SourceSynapses
IList<ISynapse> NeuronDotNet.Core.SOM.PositionNeuron.SourceSynapses get
Gets the list of source synapses associated with this neuron
A list of source synapses. It can neither be null, nor contain null elements.
TargetSynapses
IList<ISynapse> NeuronDotNet.Core.SOM.PositionNeuron.TargetSynapses get
Gets the list of target synapses associated with this neuron
A list of target synapses. It can neither be null, nor contains null elements.
NeighborhoodValue
double NeuronDotNet.Core.SOM.PositionNeuron.NeighborhoodValue get
Gets the neighborhood of this neuron with respect to the winner neuron in this layer
Neighborhood Value
The documentation for this class was generated from the following file:
shelldev/lib/externalextended/NeuronDotNetGPL/source/Core/SOM/PositionNeuron.cs