Doc: IGLib EXTENDED: AForge.Imaging.Filters.Morph Class Reference
AForge.Imaging.Filters.Morph Class Reference
Morph filter.
Public Member Functions
Morph ()
Initializes a new instance of the Morph class.
Morph (Bitmap overlayImage)
Initializes a new instance of the Morph class.
Morph (UnmanagedImage unmanagedOverlayImage)
Initializes a new instance of the Morph class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlaceFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image, UnmanagedImage overlay)
Process the filter on the specified image.
Protected Member Functions inherited from AForge.Imaging.Filters.BaseInPlaceFilter2
BaseInPlaceFilter2 ()
Initializes a new instance of the BaseInPlaceFilter2 class.
BaseInPlaceFilter2 (Bitmap overlayImage)
Initializes a new instance of the BaseInPlaceFilter2 class.
BaseInPlaceFilter2 (UnmanagedImage unmanagedOverlayImage)
Initializes a new instance of the BaseInPlaceFilter2 class.
override unsafe void ProcessFilter (UnmanagedImage image)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
double SourcePercent [get, set]
Percent of source image to keep, [0, 1].
Properties inherited from AForge.Imaging.Filters.BaseInPlaceFilter2
Bitmap OverlayImage [get, set]
Overlay image.
UnmanagedImage UnmanagedOverlayImage [get, set]
Unmanaged overlay image.
Properties inherited from AForge.Imaging.Filters.BaseInPlaceFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Member Functions
void InitFormatTranslations ()
Private Attributes
double sourcePercent = 0.50
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Morph filter.
The filter combines two images by taking specified percent of pixels' intensities from source image and the rest from overlay image. For example, if the source percent value is set to 0.8, then each pixel of the result image equals to 0.8 * source + 0.2 * overlay, where source and overlay are corresponding pixels' values in source and overlay images.
The filter accepts 8 bpp grayscale and 24 bpp color images for processing.
Sample usage:
// create filter
Morph filter = new Morph(overlayImage);
filter.SourcePercent = 0.75;
// apply the filter
Bitmap resultImage = filter.Apply(sourceImage);
Source image:
Overlay image:
Result image:
Constructor & Destructor Documentation
Morph() [1/3]
AForge.Imaging.Filters.Morph.Morph () inline
Initializes a new instance of the Morph class.
References AForge.Imaging.Filters.Morph.InitFormatTranslations().
Morph() [2/3]
AForge.Imaging.Filters.Morph.Morph (Bitmap overlayImage) inline
Initializes a new instance of the Morph class.
Parameters
overlayImage Overlay image.
References AForge.Imaging.Filters.Morph.InitFormatTranslations().
Morph() [3/3]
AForge.Imaging.Filters.Morph.Morph (UnmanagedImage unmanagedOverlayImage) inline
Initializes a new instance of the Morph class.
Parameters
unmanagedOverlayImage Unmanaged overlay image.
References AForge.Imaging.Filters.Morph.InitFormatTranslations().
Member Function Documentation
InitFormatTranslations()
void AForge.Imaging.Filters.Morph.InitFormatTranslations () inline private
References AForge.Imaging.Filters.Morph.formatTranslations.
Referenced by AForge.Imaging.Filters.Morph.Morph().
ProcessFilter()
override unsafe void AForge.Imaging.Filters.Morph.ProcessFilter (UnmanagedImage image, UnmanagedImage overlay) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
overlay Overlay image data.
Implements AForge.Imaging.Filters.BaseInPlaceFilter2.
References AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.Filters.Morph.sourcePercent, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
Member Data Documentation
sourcePercent
double AForge.Imaging.Filters.Morph.sourcePercent = 0.50 private
Referenced by AForge.Imaging.Filters.Morph.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.Morph.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.Morph.InitFormatTranslations().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.Morph.FormatTranslations get
Format translations dictionary.
SourcePercent
double AForge.Imaging.Filters.Morph.SourcePercent get set
Percent of source image to keep, [0, 1].
The property specifies the percentage of source pixels' to take. The rest is taken from an overlay image.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/2 Source filters/Morph.cs