Doc: IGLib EXTENDED: alglib.testpcaunit Class Reference
alglib.testpcaunit Class Reference
Static Public Member Functions
static bool testpca (bool silent)
static bool testpca (bool silent)
static bool _pexec_testpca (bool silent)
Static Private Member Functions
static void calculatemv (double[] x, int n, ref double mean, ref double means, ref double stddev, ref double stddevs)
static void calculatemv (double[] x, int n, ref double mean, ref double means, ref double stddev, ref double stddevs)
Member Function Documentation
testpca() [1/2]
static bool alglib.testpcaunit.testpca (bool silent) inline static
References alglib.testpcaunit.calculatemv(), alglib.math.machineepsilon, alglib.pca.pcabuildbasis(), alglib.math.randomreal(), and alglib.math.sqr().
Referenced by alglib.testpcaunit._pexec_testpca(), and _Test.Main().
calculatemv() [1/2]
static void alglib.testpcaunit.calculatemv (double[] x, int n, ref double mean, ref double means, ref double stddev, ref double stddevs) inline static private
References alglib.math.sqr().
Referenced by alglib.testpcaunit.testpca().
testpca() [2/2]
static bool alglib.testpcaunit.testpca (bool silent) inline static
References alglib.testpcaunit.calculatemv(), alglib.math.machineepsilon, alglib.pca.pcabuildbasis(), alglib.math.randomreal(), and alglib.math.sqr().
_pexec_testpca()
static bool alglib.testpcaunit._pexec_testpca (bool silent) inline static
References alglib.testpcaunit.testpca().
Referenced by _Test.Main().
calculatemv() [2/2]
static void alglib.testpcaunit.calculatemv (double[] x, int n, ref double mean, ref double means, ref double stddev, ref double stddevs) inline static private
References alglib.math.sqr().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs