Doc: IGLib EXTENDED: NUnit.Engine.AsyncTestEngineResult Class Reference
NUnit.Engine.AsyncTestEngineResult Class Reference
The TestRun class encapsulates an ongoing test run.
Public Member Functions
void SetResult (TestEngineResult result)
bool Wait (int timeout)
Blocks the current thread until the current test run completes or the timeout is reached
Properties
TestEngineResult EngineResult [get]
Get the result of this run.
EventWaitHandle WaitHandle [get]
bool IsComplete [get]
True if the test run has completed
XmlNode ITestRun. Result [get]
Properties inherited from NUnit.Engine.ITestRun
XmlNode Result [get]
Get the result of the test.
Private Member Functions
bool ITestRun. Wait (int timeout)
Blocks the current thread until the current test run completes or the timeout is reached
Private Attributes
volatile TestEngineResult _result
readonly ManualResetEvent _waitHandle = new ManualResetEvent(false)
Detailed Description
The TestRun class encapsulates an ongoing test run.
Member Function Documentation
SetResult()
void NUnit.Engine.AsyncTestEngineResult.SetResult (TestEngineResult result) inline
References NUnit.Engine.AsyncTestEngineResult._result, and NUnit.Engine.AsyncTestEngineResult._waitHandle.
Referenced by NUnit.Engine.Tests.AsyncTestEngineResultTests.IsComplete_TrueIfComplete(), NUnit.Engine.Tests.AsyncTestEngineResultTests.SetResult_ThrowsIfNull(), NUnit.Engine.Tests.AsyncTestEngineResultTests.SetResult_ThrowsIfSetTwice(), NUnit.Engine.Tests.AsyncTestEngineResultTests.Wait_AllowsMultipleWaits(), and NUnit.Engine.Tests.AsyncTestEngineResultTests.Wait_ReturnsFalseTillTestCompletes().
Wait() [1/2]
bool NUnit.Engine.AsyncTestEngineResult.Wait (int timeout) inline
Blocks the current thread until the current test run completes or the timeout is reached
Parameters
timeout A T:System.Int32 that represents the number of milliseconds to wait, or -1 milliseconds to wait indefinitely.
Returns
True if the run completed
Implements NUnit.Engine.ITestRun.
References NUnit.Engine.AsyncTestEngineResult._waitHandle.
Referenced by NUnit.Engine.AsyncTestEngineResult.Wait(), NUnit.Engine.Tests.AsyncTestEngineResultTests.Wait_AllowsMultipleWaits(), and NUnit.Engine.Tests.AsyncTestEngineResultTests.Wait_ReturnsFalseTillTestCompletes().
Wait() [2/2]
bool ITestRun. NUnit.Engine.AsyncTestEngineResult.Wait (int timeout) inline private
Blocks the current thread until the current test run completes or the timeout is reached
Parameters
timeout A T:System.Int32 that represents the number of milliseconds to wait or -1 milliseconds to wait indefinitely.
Returns
True if the run completed
Implements NUnit.Engine.ITestRun.
References NUnit.Engine.AsyncTestEngineResult.Wait().
Member Data Documentation
_result
volatile TestEngineResult NUnit.Engine.AsyncTestEngineResult._result private
Referenced by NUnit.Engine.AsyncTestEngineResult.SetResult().
_waitHandle
readonly ManualResetEvent NUnit.Engine.AsyncTestEngineResult._waitHandle = new ManualResetEvent(false) private
Referenced by NUnit.Engine.AsyncTestEngineResult.SetResult(), and NUnit.Engine.AsyncTestEngineResult.Wait().
Property Documentation
EngineResult
TestEngineResult NUnit.Engine.AsyncTestEngineResult.EngineResult get
Get the result of this run.
Exceptions
InvalidOperationException Cannot retrieve Result from an incomplete or cancelled TestRun.
Referenced by NUnit.Engine.Tests.AsyncTestEngineResultTests.Result_ThrowsIfNotSet(), and NUnit.Engine.Tests.AsyncTestEngineResultTests.Wait_ReturnsFalseTillTestCompletes().
WaitHandle
EventWaitHandle NUnit.Engine.AsyncTestEngineResult.WaitHandle get
IsComplete
bool NUnit.Engine.AsyncTestEngineResult.IsComplete get
True if the test run has completed
Referenced by NUnit.Engine.Tests.AsyncTestEngineResultTests.IsComplete_FalseIfNotComplete(), and NUnit.Engine.Tests.AsyncTestEngineResultTests.IsComplete_TrueIfComplete().
Result
XmlNode ITestRun. NUnit.Engine.AsyncTestEngineResult.Result get private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/AsyncTestEngineResult.cs