Doc: IGLib EXTENDED: IG.Lib.StringVariableSystemDtoBase< VariableSystemType > Class Template Reference
IG.Lib.StringVariableSystemDtoBase< VariableSystemType > Class Template Reference abstract
Base class for various DTOs (Data Transfer Objects) for systems of string-valued variables. Used to store a state of a variable system or to store a set of variables to be imported into a system.
Public Member Functions
StringVariableSystemDtoBase ()
Default constructor, sets IsNull to true.
abstract VariableSystemType CreateVariableSystem ()
Creates and returns a new vector of the specified dimension.
override VariableSystemType CreateObject ()
Creates and returns a new vector of the specified type and dimension.
override string ToString ()
Creates and returns a string representation of the curren variable system DTO.
Public Member Functions inherited from IG.Lib.SerializationDtoBase< VariableSystemType, StringVariableSystem >
SerializationDtoBase ()
virtual bool GetNull ()
Returns a flag indicating whether the object represented by the current DTO is null.
virtual void SetNull (bool isNull)
Sets a flag indicating whether the object represented by the current DTO is null.
virtual void CopyFromBase (BaseType obj)
Copies data to the current DTO from an object of type BaseType.
virtual void CopyToBase (ref BaseType obj)
Copies data from the current DTO to an object of the base type. Object is created anew if necessary by using the CreateObject() method.
virtual void CopyFrom (Type obj)
Copies data to the current DTO from an object of type Type.
virtual void CopyTo (ref Type obj)
Copies data from the current DTO to an object of type Type. Object is created anew if necessary by using the CreateObject() method.
virtual void CopyFromObject (object obj)
Copies data to the current DTO from an object of type object. The necessary casts are performed.
virtual void CopyToObject (ref object obj)
Copies data from the current DTO to an object of type object. Object is created anew if necessary by using the CreateObject() method. The necessary casts are performed.
override string ToString ()
Creates and returns string representation of the current DTO (data transfer object).
Public Attributes
string[][] Variables
Variable definitions.
string[] VariablesToRemove
bool SetNullOnImport = true
Protected Member Functions
override void CopyFromPlain (StringVariableSystem variableSystem)
Copies data to the current DTO from a string variable system object.
override void CopyToPlain (ref StringVariableSystem variableSystem)
Copies data from the current DTO to a variable system object.
Protected Member Functions inherited from IG.Lib.SerializationDtoBase< VariableSystemType, StringVariableSystem >
abstract void CopyFromPlain (BaseType obj)
Copies contents of the specified object to the current DTO (Data Transfer Object).
abstract void CopyToPlain (ref BaseType obj)
Copies contents of the current DTO (Data Transfer Object) to the specified object.
Additional Inherited Members
Protected Attributes inherited from IG.Lib.SerializationDtoBase< VariableSystemType, StringVariableSystem >
bool _isNull
Properties inherited from IG.Lib.SerializationDtoBase< VariableSystemType, StringVariableSystem >
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
Detailed Description
Base class for various DTOs (Data Transfer Objects) for systems of string-valued variables. Used to store a state of a variable system or to store a set of variables to be imported into a system.
Template Parameters
VariableSystemType Type parameter specifying the specific variable system type for which concrete DTO is designed.
$A Igor Jun09;
Type Constraints
VariableSystemType : StringVariableSystem
Constructor & Destructor Documentation
StringVariableSystemDtoBase()
IG.Lib.StringVariableSystemDtoBase< VariableSystemType >.StringVariableSystemDtoBase () inline
Default constructor, sets IsNull to true.
Member Function Documentation
CreateVariableSystem()
abstract VariableSystemType IG.Lib.StringVariableSystemDtoBase< VariableSystemType >.CreateVariableSystem () pure virtual
Creates and returns a new vector of the specified dimension.
Parameters
length Vector dimension.
Implemented in IG.Lib.StringSettingsDto, IG.Lib.StringVariableSystemDto< VariableSystemType >, and IG.Lib.StringVariableSystemDto< VariableSystemType >.
Referenced by IG.Lib.StringVariableSystemDtoBase< StringVariableSystem >.CreateObject().
CreateObject()
override VariableSystemType IG.Lib.StringVariableSystemDtoBase< VariableSystemType >.CreateObject () inline virtual
Creates and returns a new vector of the specified type and dimension.
Implements IG.Lib.SerializationDtoBase< VariableSystemType, StringVariableSystem >.
Referenced by IG.Lib.StringVariableSystemDtoBase< StringVariableSystem >.CopyToPlain().
CopyFromPlain()
override void IG.Lib.StringVariableSystemDtoBase< VariableSystemType >.CopyFromPlain (StringVariableSystem variableSystem) inline protected
Copies data to the current DTO from a string variable system object.
Parameters
variableSystem Variable system object from which data is copied.
CopyToPlain()
override void IG.Lib.StringVariableSystemDtoBase< VariableSystemType >.CopyToPlain (ref StringVariableSystem variableSystem) inline protected
Copies data from the current DTO to a variable system object.
Parameters
variableSystem Variable system object that data is copied to.
ToString()
override string IG.Lib.StringVariableSystemDtoBase< VariableSystemType >.ToString () inline
Creates and returns a string representation of the curren variable system DTO.
Referenced by IG.Lib.StringVariableSystemDtoBase< StringVariableSystem >.ToString().
Member Data Documentation
Variables
string [][] IG.Lib.StringVariableSystemDtoBase< VariableSystemType >.Variables
Variable definitions.
Each element must be an array with two elements (variable name and variable value).
Referenced by IG.Lib.StringVariableSystemDtoBase< StringVariableSystem >.CopyFromPlain(), IG.Lib.StringVariableSystemDtoBase< StringVariableSystem >.CopyToPlain(), and IG.Lib.StringVariableSystemDtoBase< StringVariableSystem >.ToString().
VariablesToRemove
string [] IG.Lib.StringVariableSystemDtoBase< VariableSystemType >.VariablesToRemove
Referenced by IG.Lib.StringVariableSystemDtoBase< StringVariableSystem >.CopyToPlain().
SetNullOnImport
bool IG.Lib.StringVariableSystemDtoBase< VariableSystemType >.SetNullOnImport = true
Referenced by IG.Lib.StringVariableSystemDtoBase< StringVariableSystem >.CopyToPlain().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/varstring/VarSystemStringDto.cs