Doc: IGLib EXTENDED: alglib.chebyshev Class Reference
alglib.chebyshev Class Reference
Static Public Member Functions
static double chebyshevcalculate (int r, int n, double x)
static double chebyshevsum (double[] c, int r, int n, double x)
static void chebyshevcoefficients (int n, ref double[] c)
static void fromchebyshev (double[] a, int n, ref double[] b)
static double chebyshevcalculate (int r, int n, double x)
static double chebyshevsum (double[] c, int r, int n, double x)
static void chebyshevcoefficients (int n, ref double[] c)
static void fromchebyshev (double[] a, int n, ref double[] b)
Member Function Documentation
chebyshevcalculate() [1/2]
static double alglib.chebyshev.chebyshevcalculate (int r, int n, double x) inline static
Referenced by alglib.chebyshevcalculate(), and alglib.testchebyshevunit.testchebyshev().
chebyshevsum() [1/2]
static double alglib.chebyshev.chebyshevsum (double[] c, int r, int n, double x) inline static
Referenced by alglib.chebyshevsum(), and alglib.testchebyshevunit.testchebyshev().
chebyshevcoefficients() [1/2]
static void alglib.chebyshev.chebyshevcoefficients (int n, ref double[] c) inline static
Referenced by alglib.chebyshevcoefficients(), and alglib.testchebyshevunit.testchebyshev().
fromchebyshev() [1/2]
static void alglib.chebyshev.fromchebyshev (double[] a, int n, ref double[] b) inline static
Referenced by alglib.fromchebyshev(), and alglib.testchebyshevunit.testchebyshev().
chebyshevcalculate() [2/2]
static double alglib.chebyshev.chebyshevcalculate (int r, int n, double x) inline static
chebyshevsum() [2/2]
static double alglib.chebyshev.chebyshevsum (double[] c, int r, int n, double x) inline static
chebyshevcoefficients() [2/2]
static void alglib.chebyshev.chebyshevcoefficients (int n, ref double[] c) inline static
fromchebyshev() [2/2]
static void alglib.chebyshev.fromchebyshev (double[] a, int n, ref double[] b) inline static
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/specialfunctions.cs