Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLASRT Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLASRT Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLASRT (LSAME lsame, XERBLA xerbla)
DLASRT ()
void Run (string ID, int N, ref double[] D, int offset_d, ref int INFO)
Private Attributes
LSAME _lsame
XERBLA _xerbla
int[] STACK = new int[2 * 32]
Static Private Attributes
const int SELECT = 20
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
Sort the numbers in D in increasing order (if ID = 'I') or in decreasing order (if ID = 'D').
Use Quick Sort, reverting to Insertion sort on arrays of size .LE. 20. Dimension of STACK limits N to about 2**32.
/summary>
Constructor & Destructor Documentation
DLASRT() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLASRT.DLASRT (LSAME lsame, XERBLA xerbla) inline
DLASRT() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLASRT.DLASRT () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLASRT.Run (string ID, int N, ref double[] D, int offset_d, ref int INFO) inline
Purpose
Sort the numbers in D in increasing order (if ID = 'I') or in decreasing order (if ID = 'D').
Use Quick Sort, reverting to Insertion sort on arrays of size .LE. 20. Dimension of STACK limits N to about 2**32.
/summary>
Parameters
ID (input) CHARACTER*1 = 'I': sort D in increasing order; = 'D': sort D in decreasing order. /param>
Parameters
N (input) INTEGER The length of the array D. /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension (N) On entry, the array to be sorted. On exit, D has been sorted into increasing order (D(1) .LE. ... .LE. D(N)) or into decreasing order (D(1) .GE. ... .GE. D(N)), depending on ID. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASRT.SELECT, and DotNumerics.LinearAlgebra.CSLapack.DLASRT.STACK.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTERF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASQ2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASQ1.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALSD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DSTEDC.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLASRT._lsame private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLASRT._xerbla private
SELECT
const int DotNumerics.LinearAlgebra.CSLapack.DLASRT.SELECT = 20 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASRT.Run().
STACK
int [] DotNumerics.LinearAlgebra.CSLapack.DLASRT.STACK = new int[2 * 32] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASRT.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlasrt.cs