Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGELS Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGELS Class Reference
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGELS (LSAME lsame, ILAENV ilaenv, DLABAD dlabad, DLAMCH dlamch, DLANGE dlange, DGELQF dgelqf, DGEQRF dgeqrf, DLASCL dlascl, DLASET dlaset, DORMLQ dormlq, DORMQR dormqr, DTRTRS dtrtrs, XERBLA xerbla)
DGELS ()
void Run (string TRANS, int M, int N, int NRHS, ref double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
LSAME _lsame
ILAENV _ilaenv
DLABAD _dlabad
DLAMCH _dlamch
DLANGE _dlange
DGELQF _dgelqf
DGEQRF _dgeqrf
DLASCL _dlascl
DLASET _dlaset
DORMLQ _dormlq
DORMQR _dormqr
DTRTRS _dtrtrs
XERBLA _xerbla
double[] RWORK = new double[1]
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
Detailed Description
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGELS solves overdetermined or underdetermined real linear systems involving an M-by-N matrix A, or its transpose, using a QR or LQ factorization of A. It is assumed that A has full rank.
The following options are provided:
If TRANS = 'N' and m .GE. n: find the least squares solution of an overdetermined system, i.e., solve the least squares problem minimize || B - A*X ||.
If TRANS = 'N' and m .LT. n: find the minimum norm solution of an underdetermined system A * X = B.
If TRANS = 'T' and m .GE. n: find the minimum norm solution of an undetermined system A**T * X = B.
If TRANS = 'T' and m .LT. n: find the least squares solution of an overdetermined system, i.e., solve the least squares problem minimize || B - A**T * X ||.
Several right hand side vectors b and solution vectors x can be handled in a single call; they are stored as the columns of the M-by-NRHS right hand side matrix B and the N-by-NRHS solution matrix X.
/summary>
Constructor & Destructor Documentation
DGELS() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGELS.DGELS (LSAME lsame, ILAENV ilaenv, DLABAD dlabad, DLAMCH dlamch, DLANGE dlange, DGELQF dgelqf, DGEQRF dgeqrf, DLASCL dlascl, DLASET dlaset, DORMLQ dormlq, DORMQR dormqr, DTRTRS dtrtrs, XERBLA xerbla) inline
DGELS() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGELS.DGELS () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGELS.Run (string TRANS, int M, int N, int NRHS, ref double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DGELS solves overdetermined or underdetermined real linear systems involving an M-by-N matrix A, or its transpose, using a QR or LQ factorization of A. It is assumed that A has full rank.
The following options are provided:
If TRANS = 'N' and m .GE. n: find the least squares solution of an overdetermined system, i.e., solve the least squares problem minimize || B - A*X ||.
If TRANS = 'N' and m .LT. n: find the minimum norm solution of an underdetermined system A * X = B.
If TRANS = 'T' and m .GE. n: find the minimum norm solution of an undetermined system A**T * X = B.
If TRANS = 'T' and m .LT. n: find the least squares solution of an overdetermined system, i.e., solve the least squares problem minimize || B - A**T * X ||.
Several right hand side vectors b and solution vectors x can be handled in a single call; they are stored as the columns of the M-by-NRHS right hand side matrix B and the N-by-NRHS solution matrix X.
/summary>
Parameters
TRANS (input) CHARACTER*1 = 'N': the linear system involves A; = 'T': the linear system involves A**T. /param>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. 0. /param>
Parameters
NRHS (input) INTEGER The number of right hand sides, i.e., the number of columns of the matrices B and X. NRHS .GE.0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the M-by-N matrix A. On exit, if M .GE. N, A is overwritten by details of its QR factorization as returned by DGEQRF; if M .LT. N, A is overwritten by details of its LQ factorization as returned by DGELQF. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
B (input/output) DOUBLE PRECISION array, dimension (LDB,NRHS) On entry, the matrix B of right hand side vectors, stored columnwise; B is M-by-NRHS if TRANS = 'N', or N-by-NRHS if TRANS = 'T'. On exit, if INFO = 0, B is overwritten by the solution vectors, stored columnwise: if TRANS = 'N' and m .GE. n, rows 1 to n of B contain the least squares solution vectors; the residual sum of squares for the solution in each column is given by the sum of squares of elements N+1 to M in that column; if TRANS = 'N' and m .LT. n, rows 1 to N of B contain the minimum norm solution vectors; if TRANS = 'T' and m .GE. n, rows 1 to M of B contain the minimum norm solution vectors; if TRANS = 'T' and m .LT. n, rows 1 to M of B contain the least squares solution vectors; the residual sum of squares for the solution in each column is given by the sum of squares of elements M+1 to N in that column. /param>
Parameters
LDB (input) INTEGER The leading dimension of the array B. LDB .GE. MAX(1,M,N). /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. max(1, MN + max(MN, NRHS)). For optimal performance, LWORK .GE. max(1, MN + max(MN, NRHS)*NB). where MN = min(M,N) and NB is the optimum block size.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value .GT. 0: if INFO = i, the i-th diagonal element of the triangular factor of A is zero, so that A does not have full rank; the least squares solution could not be computed. /param>
References DotNumerics.LinearAlgebra.CSLapack.DGELS.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLABAD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASET.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRTRS.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELQF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANGE.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMLQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELS.RWORK, and DotNumerics.LinearAlgebra.CSLapack.DGELS.ZERO.
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DGELS._lsame private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DGELS._ilaenv private
_dlabad
DLABAD DotNumerics.LinearAlgebra.CSLapack.DGELS._dlabad private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DGELS._dlamch private
_dlange
DLANGE DotNumerics.LinearAlgebra.CSLapack.DGELS._dlange private
_dgelqf
DGELQF DotNumerics.LinearAlgebra.CSLapack.DGELS._dgelqf private
_dgeqrf
DGEQRF DotNumerics.LinearAlgebra.CSLapack.DGELS._dgeqrf private
_dlascl
DLASCL DotNumerics.LinearAlgebra.CSLapack.DGELS._dlascl private
_dlaset
DLASET DotNumerics.LinearAlgebra.CSLapack.DGELS._dlaset private
_dormlq
DORMLQ DotNumerics.LinearAlgebra.CSLapack.DGELS._dormlq private
_dormqr
DORMQR DotNumerics.LinearAlgebra.CSLapack.DGELS._dormqr private
_dtrtrs
DTRTRS DotNumerics.LinearAlgebra.CSLapack.DGELS._dtrtrs private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGELS._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DGELS.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGELS.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGELS.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGELS.Run().
RWORK
double [] DotNumerics.LinearAlgebra.CSLapack.DGELS.RWORK = new double[1] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGELS.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgels.cs