Doc: IGLib EXTENDED: IG.Lib.MsgObservationEvent Class Reference
IG.Lib.MsgObservationEvent Class Reference
Class for holding and manipulating the data about observation event. Includes parsing an XML file, storing data internally, and transcription of read data to a PADO object that enables saving data to a database.
Public Member Functions
MsgObservationEvent ()
Default constructor, sets the type information.
override void Read ()
Reads msg data from the internal XML document containing the msg.
override void Read (XmlParser data)
Read msg data from an XML document containing the msg.
override void CheckConsistency (AccummulatedReport rep)
Check correctness and consistency of data and creates a report on this.
void SetVerifierId (string ID)
Postavi ID avtorizatorja, ta funkcija je narejena samo za testiranje in se v delovnem okolju ne sme uporabljati!
void LoadFindings (string FileName)
Loads findings from a file.
override string ToString ()
override XmlDocument ToXml ()
Converts a msg to Xml and returns it.
Public Member Functions inherited from IG.Lib.MsgBaseWithModel
void SetModelFile (string FilePath)
Sets the model document for creation of the msg to the contents of the specified file.
void SetModelString (string XmlString)
Sets the model document for creation of the msg to the contents of the specified string.
void SetModelDocument (XmlDocument doc)
Sets the model document for creation of the msg to the contents of the specified string.
Public Member Functions inherited from IG.Lib.MsgBase
void SetSenderLabex ()
Sets msg data such that sender is Labex and receiver is Bis.
void SetSenderBis ()
Sets msg data such that sender is Bis and receiver is Labex.
Public Member Functions inherited from IG.Lib.ParsableXmlObject
virtual void Save (string filename)
Saves contents of the msg to an xml file.
virtual void CreateXml ()
Creates msg Xml from the current msg data and stores it in this object.
virtual void Load (string filename)
Loads msg data from a file containing the XML msg.
virtual void LoadXml (string doc)
Loads msg data from a string containing the XML msg.
virtual void LoadXml (XmlDocument doc)
Loads msg data from an XmlDocument containing XML msg.
virtual void WriteToConsole ()
Writes cntents of the msg in a human readable form to the system console.
virtual void Write (string filename, bool append)
Writes cntents of the msg in a human readable form to a file.
Public Attributes
int? Id
string FindingsIdOid = ""
DocFindings Findings = null
string aaa = null
Public Attributes inherited from IG.Lib.MsgBase
MessageType Type = MessageType.Unknown
Message type. Helps with general methods that operate on any datatype of msg.
string MessageId = null
Message ID, obtained form the web service.
string MessageFile = null
Specifies the file where message has been backed up. Warning: this file may be deleted at any time!
string MessageNumber = null
Public Attributes inherited from IG.Lib.ParsableXmlObject
string XmlString = null
Properties
OeAction Action [get, set]
Action is bound to order status, therefore this propety is implemented in this way!
string ActionCode [get, set]
Actioncode is bound to action, which is ensured by this property.
string MessageCode [get, set]
MessageCode is bound to action, which is ensured by this property.
string FindingsId [get, private set]
string FindingsString [get, set]
Gets or sets findings (attachment) as XML string. This is coupled with FindingsXml.
string FindingsStringPartial [get]
Gets or sets findings (attachment) as XML string. This is coupled with FindingsXml.
XmlDocument FindingsXml [get, set]
Gets or sets findings (attachment) as XmlDocument. This is coupled with FindingsStringPartial.
Properties inherited from IG.Lib.MsgBaseWithModel
virtual XmlDocument ModelDocument [get, set]
Gets or seta the XML document that is used as model for creation of XML. Warning: Each call to execution of get() makes a clone of an XmlDocument.
Properties inherited from IG.Lib.MsgBase
static MsgConst Const [get]
Gets objects that contains all constants related to communication messages.
string MessageXml [get, set]
Complete msg as obtained from the web service.
Properties inherited from IG.Lib.ParsableXmlObject
virtual IReporter R [get]
Reporter for this class.
XmlDocument Doc [get]
Returns the XML document representing the msg.
Private Member Functions
string GenerateMessageId ()
Returns a generated msg Id.
Private Attributes
string ActionRoot = null
string MessageCodeSystem = null
string ProtocolNumber = null
string ProtocolNumberOid = null
string RsrType = null
string RsrTypeCodeSystem = null
string Comment = null
string PatientId = null
string PatientIdOid = null
string AuthorId = null
string AuthorIdOid = null
string VerifierId = null
string VerifierIdOid = null
string BisorderId = null
string BisorderIdOid = null
OeAction _action = OeAction.Unknown
OoStatus OrderStatus = OoStatus.Unknown
DateTime CreationTime = DateTime.Now
DateTime? OrderCreationTime = null
DateTime? OrderCompletionTime = null
string _FindingsId = null
string _findingsStr = null
XmlDocument _findingsXml = null
Static Private Attributes
static int IdWithinSession = 0
Additional Inherited Members
Static Public Member Functions inherited from IG.Lib.MsgBase
static void SetMessageReceiverOld (ref XmlDocument msg, string receiver, out bool changed)
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false. WARNING: searching for receiver element is done through an XPath expression, which may fail due to default namespaces that were not detected.
static void SetMessageReceiver (ref string message, string receiver, out bool changed)
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetMessageReceiver (ref XmlDocument msg, string receiver, out bool changed)
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetMessageReceiver (ref XmlBuilder data, string receiver, out bool changed)
Sets the receiver of the communication msg stored in an Xml builder to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetMessageSender (ref XmlBuilder data, string sender, out bool changed)
Sets the sender of the communication msg stored in an Xml builder to the specified sender, and indicates through an output argument whether the sender has been changed in msg. If the Sender stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetMessageResponder (ref XmlBuilder data, string responder, out bool changed)
Sets the responder of the communication msg stored in an Xml builder to the specified responder, and indicates through an output argument whether the responder has been changed in msg. If the responder stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static MessageType GetMessageType (string msgstring)
Infers the msg type from the XML string containing the msg, and returns it.
static MessageType GetMessageType (XmlDocument msg)
Infers the msg type from the XML document containing the msg, and returns it.
static MessageType GetMessageType (XmlParser data)
Infers the msg type from the XML parser containing the msg, and returns it.
Protected Attributes inherited from IG.Lib.ParsableXmlObject
XmlBuilder Data = new XmlBuilder()
Static Protected Attributes inherited from IG.Lib.MsgBase
static string LabexIdLowercase = null
Detailed Description
Class for holding and manipulating the data about observation event. Includes parsing an XML file, storing data internally, and transcription of read data to a PADO object that enables saving data to a database.
Constructor & Destructor Documentation
MsgObservationEvent()
IG.Lib.MsgObservationEvent.MsgObservationEvent () inline
Default constructor, sets the type information.
References IG.Lib.MsgBase.Type.
Member Function Documentation
Read() [1/2]
override void IG.Lib.MsgObservationEvent.Read () inline virtual
Reads msg data from the internal XML document containing the msg.
Implements IG.Lib.ParsableXmlObject.
References IG.Lib.ParsableXmlObject.Data.
Referenced by IGTest.ProgramIGTest.TestMsgObservationEvent().
Read() [2/2]
override void IG.Lib.MsgObservationEvent.Read (XmlParser data) inline virtual
Read msg data from an XML document containing the msg.
Parameters
doc Document containing the msg.
Implements IG.Lib.ParsableXmlObject.
References IG.Lib.MsgObservationEvent.Action, IG.Lib.MsgConstObservationOrder.ActionAttribute, IG.Lib.MsgObservationEvent.ActionCode, IG.Lib.MsgConstObservationOrder.ActionElement, IG.Lib.MsgConstObservationOrder.ActionOidAttribute, IG.Lib.MsgObservationEvent.ActionRoot, IG.Lib.XmlParser.Attribute(), IG.Lib.MsgObservationEvent.AuthorId, IG.Lib.MsgObservationEvent.AuthorIdOid, IG.Lib.XmlParser.Back(), IG.Lib.XmlParser.BackToMark(), IG.Lib.MsgObservationEvent.BisorderId, IG.Lib.MsgObservationEvent.BisorderIdOid, IG.Lib.MsgObservationEvent.CheckConsistency(), IG.Lib.MsgConstCommon.CodeAttribute, IG.Lib.MsgConstCommon.CodeElement, IG.Lib.MsgConstCommon.CodeSystemAttribute, IG.Lib.MsgObservationEvent.Comment, IG.Lib.MsgBase.Const, IG.Lib.MsgConst.ConvertOoStatus(), IG.Lib.MsgConst.ConvertTime(), IG.Lib.MsgObservationEvent.CreationTime, IG.Lib.MsgConstObservationOrder.CreationTimeAttribute, IG.Lib.MsgConstObservationOrder.CreationTimeElement, IG.Lib.XmlParser.Current, IG.Lib.ParsableXmlObject.Data, IG.Lib.IReporterBase.Depth, IG.Lib.XmlParser.Doc, IG.Lib.MsgObservationEvent.FindingsId, IG.Lib.MsgObservationEvent.FindingsIdOid, IG.Lib.MsgObservationEvent.FindingsString, IG.Lib.MsgConstCommon.FtRootName, IG.Lib.XmlParser.GoToRoot(), IG.Lib.MsgObservationEvent.Id, IG.Lib.MsgConstCommon.IdElement, IG.Lib.MsgConstCommon.IdIdAttribute, IG.Lib.MsgConstCommon.IdOidAttribute, IG.Lib.MsgObservationEvent.MessageCode, IG.Lib.MsgObservationEvent.MessageCodeSystem, IG.Lib.MsgBase.MessageNumber, IG.Lib.MsgBase.MessageNumberOid, IG.Lib.MsgBase.MessageReceiver, IG.Lib.MsgBase.MessageReceiverOid, IG.Lib.MsgBase.MessageResponder, IG.Lib.MsgBase.MessageResponderOid, IG.Lib.MsgBase.MessageSender, IG.Lib.MsgBase.MessageSenderOid, IG.Lib.MsgConstCommon.MessageSubContainer, IG.Lib.MsgConstCommon.MessageSubContainerTypeAttribute, IG.Lib.MsgConstCommon.MessageSubContainerTypeAttributeValue, IG.Lib.MsgConstCommon.MessageTypeAttribute, IG.Lib.XmlParser.Name, IG.Lib.XmlParser.NextElement(), IG.Lib.XmlParser.NextNode(), IG.Lib.XmlParser.NextOrCurrentElement(), IG.Lib.MsgConstObservationEvent.OeAttachmentContainer, IG.Lib.MsgConstObservationEvent.OeAttachmentElement, IG.Lib.MsgConstObservationEvent.OeAuthorContainer, IG.Lib.MsgConstObservationEvent.OeAuthorSubcontainer, IG.Lib.MsgConstObservationEvent.OeBisOrderIdContainter, IG.Lib.MsgConstObservationEvent.OeBisOrderIdSubContainter, IG.Lib.MsgConstObservationEvent.OeCommentElement, IG.Lib.MsgConstCommon.OeMessageContainer, IG.Lib.MsgConstCommon.OeMessageSubContainer2, IG.Lib.MsgConstObservationEvent.OeMessageType, IG.Lib.MsgConstObservationEvent.OeOrderCompletionTimeElement, IG.Lib.MsgConstObservationEvent.OeOrderCreationTimeElement, IG.Lib.MsgConstObservationEvent.OePatientContainer, IG.Lib.MsgConstObservationEvent.OePatientSubcontainer, IG.Lib.MsgConstCommon.OeRootName, IG.Lib.MsgConstObservationEvent.OeTimeContainer, IG.Lib.MsgConstObservationEvent.OeVerifierContainter, IG.Lib.MsgConstObservationEvent.OeVerifierSubContainter, IG.Lib.MsgConstObservationOrder.OoOrderStatusAttribute, IG.Lib.MsgConstObservationOrder.OoOrderStatusElement, IG.Lib.MsgObservationEvent.OrderCompletionTime, IG.Lib.MsgObservationEvent.OrderCreationTime, IG.Lib.MsgObservationEvent.OrderStatus, IG.Lib.MsgObservationEvent.PatientId, IG.Lib.MsgObservationEvent.PatientIdOid, IG.Lib.MsgObservationEvent.ProtocolNumber, IG.Lib.MsgObservationEvent.ProtocolNumberOid, IG.Lib.ParsableXmlObject.R, IG.Lib.MsgConstCommon.ReceiverContainer, IG.Lib.MsgConstCommon.ReceiverSubContainer, IG.Lib.XmlParser.RemoveMark(), IG.Lib.ParsableXmlObject.AccummulatedReport.Report(), IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.MsgConstCommon.ResponderContainer, IG.Lib.MsgConstCommon.ResponderSubContainer, IG.Lib.ReporterBase.ReviseException(), IG.Lib.MsgObservationEvent.RsrType, IG.Lib.MsgObservationEvent.RsrTypeCodeSystem, IG.Lib.MsgConstCommon.SenderContainer, IG.Lib.MsgConstCommon.SenderSubContainer, IG.Lib.XmlParser.SetMark(), IG.Lib.XmlParser.StepIn(), IG.Lib.XmlParser.StepOut(), IG.Lib.IReporterBase.TreatInfo, IG.Lib.XmlParser.Value, IG.Lib.MsgObservationEvent.VerifierId, and IG.Lib.MsgObservationEvent.VerifierIdOid.
CheckConsistency()
override void IG.Lib.MsgObservationEvent.CheckConsistency (AccummulatedReport rep) inline virtual
Check correctness and consistency of data and creates a report on this.
Parameters
rep Object where error, warning and info reports are accumulated.
Reimplemented from IG.Lib.ParsableXmlObject.
References IG.Lib.ParsableXmlObject.AccummulatedReport.AddError(), and IG.Lib.ParsableXmlObject.AccummulatedReport.AddInfo().
Referenced by IG.Lib.MsgObservationEvent.Read().
SetVerifierId()
void IG.Lib.MsgObservationEvent.SetVerifierId (string ID) inline
Postavi ID avtorizatorja, ta funkcija je narejena samo za testiranje in se v delovnem okolju ne sme uporabljati!
References IG.Lib.ParsableXmlObject.R, IG.Lib.IReporterBase.ReportWarning(), and IG.Lib.MsgObservationEvent.VerifierId.
LoadFindings()
void IG.Lib.MsgObservationEvent.LoadFindings (string FileName) inline
Loads findings from a file.
References IG.Lib.MsgObservationEvent.FindingsXml.
Referenced by IGTest.ProgramIGTest.TestMsgObservationEvent().
ToString()
override string IG.Lib.MsgObservationEvent.ToString () inline
References IG.Lib.MsgObservationEvent.ActionCode, IG.Lib.MsgObservationEvent.ActionRoot, IG.Lib.MsgObservationEvent.AuthorId, IG.Lib.MsgObservationEvent.AuthorIdOid, IG.Lib.MsgObservationEvent.BisorderId, IG.Lib.MsgObservationEvent.BisorderIdOid, IG.Lib.MsgObservationEvent.Comment, IG.Lib.MsgBase.Const, IG.Lib.MsgConst.ConvertOeAction(), IG.Lib.MsgObservationEvent.CreationTime, IG.Lib.IReporterBase.Depth, IG.Lib.MsgObservationEvent.FindingsId, IG.Lib.MsgObservationEvent.FindingsIdOid, IG.Lib.MsgObservationEvent.FindingsStringPartial, IG.Lib.MsgObservationEvent.MessageCode, IG.Lib.MsgBase.MessageFile, IG.Lib.MsgBase.MessageId, IG.Lib.MsgBase.MessageNumber, IG.Lib.MsgBase.MessageNumberOid, IG.Lib.MsgBase.MessageReceiver, IG.Lib.MsgBase.MessageReceiverOid, IG.Lib.MsgBase.MessageResponder, IG.Lib.MsgBase.MessageResponderOid, IG.Lib.MsgBase.MessageSender, IG.Lib.MsgBase.MessageSenderOid, IG.Lib.MsgBase.MessageXml, IG.Lib.MsgObservationEvent.OrderCompletionTime, IG.Lib.MsgObservationEvent.OrderCreationTime, IG.Lib.MsgObservationEvent.OrderStatus, IG.Lib.MsgObservationEvent.PatientId, IG.Lib.MsgObservationEvent.PatientIdOid, IG.Lib.MsgObservationEvent.ProtocolNumber, IG.Lib.ParsableXmlObject.R, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.MsgObservationEvent.RsrType, IG.Lib.MsgObservationEvent.RsrTypeCodeSystem, IG.Lib.IReporterBase.TreatInfo, IG.Lib.MsgBase.Type, IG.Lib.MsgObservationEvent.VerifierId, and IG.Lib.MsgObservationEvent.VerifierIdOid.
GenerateMessageId()
string IG.Lib.MsgObservationEvent.GenerateMessageId () inline private
Returns a generated msg Id.
References IG.Lib.MsgBase.Const, IG.Lib.MsgConst.ConvertTime(), IG.Lib.MsgObservationEvent.IdWithinSession, and IG.Lib.MsgObservationEvent.PatientId.
Referenced by IG.Lib.MsgObservationEvent.ToXml().
ToXml()
override XmlDocument IG.Lib.MsgObservationEvent.ToXml () inline virtual
Converts a msg to Xml and returns it.
Implements IG.Lib.ParsableXmlObject.
References IG.Lib.MsgConstObservationOrder.ActionAttribute, IG.Lib.MsgConstObservationOrder.ActionElement, IG.Lib.MsgObservationEvent.AuthorId, IG.Lib.XmlParser.Back(), IG.Lib.XmlParser.BackToMark(), IG.Lib.MsgObservationEvent.BisorderId, IG.Lib.MsgConstCommon.CodeAttribute, IG.Lib.MsgConstCommon.CodeElement, IG.Lib.MsgObservationEvent.Comment, IG.Lib.MsgBase.Const, IG.Lib.MsgConst.ConvertOeAction(), IG.Lib.MsgConst.ConvertOeActionCode(), IG.Lib.MsgConst.ConvertOoStatus(), IG.Lib.MsgConst.ConvertTime(), IG.Lib.MsgConstObservationOrder.CreationTimeAttribute, IG.Lib.MsgConstObservationOrder.CreationTimeElement, IG.Lib.XmlParser.Current, IG.Lib.ParsableXmlObject.Data, IG.Lib.IReporterBase.Depth, IG.Lib.XmlParser.Doc, IG.Lib.ParsableXmlObject.Doc, IG.Lib.MsgConstCommon.ExtensionAttribute, IG.Lib.MsgObservationEvent.FindingsId, IG.Lib.MsgObservationEvent.FindingsStringPartial, IG.Lib.MsgObservationEvent.FindingsXml, IG.Lib.MsgConstCommon.FtRootName, IG.Lib.MsgObservationEvent.GenerateMessageId(), IG.Lib.XmlParser.GoToRoot(), IG.Lib.MsgConstCommon.IdElement, IG.Lib.MsgConstCommon.IdIdAttribute, IG.Lib.MsgBase.MessageNumber, IG.Lib.MsgBase.MessageReceiver, IG.Lib.MsgBase.MessageResponder, IG.Lib.MsgBase.MessageSender, IG.Lib.MsgConstCommon.MessageSubContainer, IG.Lib.MsgBaseWithModel.ModelDocument, IG.Lib.XmlParser.Name, IG.Lib.XmlParser.NextOrCurrentElement(), IG.Lib.MsgConstObservationEvent.OeAttachmentContainer, IG.Lib.MsgConstObservationEvent.OeAttachmentElement, IG.Lib.MsgConstObservationEvent.OeAuthorContainer, IG.Lib.MsgConstObservationEvent.OeAuthorSubcontainer, IG.Lib.MsgConstObservationEvent.OeBisOrderIdContainter, IG.Lib.MsgConstObservationEvent.OeBisOrderIdSubContainter, IG.Lib.MsgConstObservationEvent.OeCommentElement, IG.Lib.MsgConstCommon.OeMessageContainer, IG.Lib.MsgConstCommon.OeMessageSubContainer2, IG.Lib.MsgConstObservationEvent.OeOrderCompletionTimeElement, IG.Lib.MsgConstObservationEvent.OeOrderCreationTimeElement, IG.Lib.MsgConstObservationEvent.OePatientContainer, IG.Lib.MsgConstObservationEvent.OePatientSubcontainer, IG.Lib.MsgConstCommon.OeRootName, IG.Lib.MsgConstObservationEvent.OeTimeContainer, IG.Lib.MsgConstObservationEvent.OeVerifierContainter, IG.Lib.MsgConstObservationEvent.OeVerifierSubContainter, IG.Lib.MsgConstObservationOrder.OoOrderStatusAttribute, IG.Lib.MsgConstObservationOrder.OoOrderStatusElement, IG.Lib.MsgObservationEvent.OrderCompletionTime, IG.Lib.MsgObservationEvent.OrderCreationTime, IG.Lib.MsgObservationEvent.OrderStatus, IG.Lib.MsgObservationEvent.PatientId, IG.Lib.MsgObservationEvent.ProtocolNumber, IG.Lib.ParsableXmlObject.R, IG.Lib.MsgConstCommon.ReceiverContainer, IG.Lib.MsgConstCommon.ReceiverSubContainer, IG.Lib.XmlBuilder.RemoveCurrent(), IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.MsgConstCommon.ResponderContainer, IG.Lib.MsgConstCommon.ResponderSubContainer, IG.Lib.ReporterBase.ReviseException(), IG.Lib.MsgConstCommon.SenderContainer, IG.Lib.MsgConstCommon.SenderSubContainer, IG.Lib.XmlBuilder.SetAttribute(), IG.Lib.XmlBuilder.SetInnerText(), IG.Lib.XmlParser.SetMark(), IG.Lib.XmlParser.StepIn(), IG.Lib.IReporterBase.TreatInfo, and IG.Lib.MsgObservationEvent.VerifierId.
Referenced by IGTest.ProgramIGTest.TestMsgObservationEvent().
Member Data Documentation
ActionRoot
string IG.Lib.MsgObservationEvent.ActionRoot = null private
Referenced by IG.Lib.MsgObservationEvent.Read(), and IG.Lib.MsgObservationEvent.ToString().
MessageCodeSystem
string IG.Lib.MsgObservationEvent.MessageCodeSystem = null private
Referenced by IG.Lib.MsgObservationEvent.Read().
ProtocolNumber
string IG.Lib.MsgObservationEvent.ProtocolNumber = null private
Referenced by IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgObservationEvent.ToString(), and IG.Lib.MsgObservationEvent.ToXml().
ProtocolNumberOid
string IG.Lib.MsgObservationEvent.ProtocolNumberOid = null private
Referenced by IG.Lib.MsgObservationEvent.Read().
RsrType
string IG.Lib.MsgObservationEvent.RsrType = null private
Referenced by IG.Lib.MsgObservationEvent.Read(), and IG.Lib.MsgObservationEvent.ToString().
RsrTypeCodeSystem
string IG.Lib.MsgObservationEvent.RsrTypeCodeSystem = null private
Referenced by IG.Lib.MsgObservationEvent.Read(), and IG.Lib.MsgObservationEvent.ToString().
Comment
string IG.Lib.MsgObservationEvent.Comment = null private
Referenced by IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgObservationEvent.ToString(), and IG.Lib.MsgObservationEvent.ToXml().
PatientId
string IG.Lib.MsgObservationEvent.PatientId = null private
Referenced by IG.Lib.MsgObservationEvent.GenerateMessageId(), IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgObservationEvent.ToString(), and IG.Lib.MsgObservationEvent.ToXml().
PatientIdOid
string IG.Lib.MsgObservationEvent.PatientIdOid = null private
Referenced by IG.Lib.MsgObservationEvent.Read(), and IG.Lib.MsgObservationEvent.ToString().
AuthorId
string IG.Lib.MsgObservationEvent.AuthorId = null private
Referenced by IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgObservationEvent.ToString(), and IG.Lib.MsgObservationEvent.ToXml().
AuthorIdOid
string IG.Lib.MsgObservationEvent.AuthorIdOid = null private
Referenced by IG.Lib.MsgObservationEvent.Read(), and IG.Lib.MsgObservationEvent.ToString().
VerifierId
string IG.Lib.MsgObservationEvent.VerifierId = null private
Referenced by IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgObservationEvent.SetVerifierId(), IG.Lib.MsgObservationEvent.ToString(), and IG.Lib.MsgObservationEvent.ToXml().
VerifierIdOid
string IG.Lib.MsgObservationEvent.VerifierIdOid = null private
Referenced by IG.Lib.MsgObservationEvent.Read(), and IG.Lib.MsgObservationEvent.ToString().
BisorderId
string IG.Lib.MsgObservationEvent.BisorderId = null private
Referenced by IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgObservationEvent.ToString(), and IG.Lib.MsgObservationEvent.ToXml().
BisorderIdOid
string IG.Lib.MsgObservationEvent.BisorderIdOid = null private
Referenced by IG.Lib.MsgObservationEvent.Read(), and IG.Lib.MsgObservationEvent.ToString().
_action
OeAction IG.Lib.MsgObservationEvent._action = OeAction.Unknown private
OrderStatus
OoStatus IG.Lib.MsgObservationEvent.OrderStatus = OoStatus.Unknown private
Referenced by IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgObservationEvent.ToString(), and IG.Lib.MsgObservationEvent.ToXml().
CreationTime
DateTime IG.Lib.MsgObservationEvent.CreationTime = DateTime.Now private
Referenced by IG.Lib.MsgObservationEvent.Read(), and IG.Lib.MsgObservationEvent.ToString().
OrderCreationTime
DateTime? IG.Lib.MsgObservationEvent.OrderCreationTime = null private
Referenced by IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgObservationEvent.ToString(), and IG.Lib.MsgObservationEvent.ToXml().
OrderCompletionTime
DateTime? IG.Lib.MsgObservationEvent.OrderCompletionTime = null private
Referenced by IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgObservationEvent.ToString(), and IG.Lib.MsgObservationEvent.ToXml().
Id
int? IG.Lib.MsgObservationEvent.Id
Referenced by IG.Lib.MsgObservationEvent.Read().
FindingsIdOid
string IG.Lib.MsgObservationEvent.FindingsIdOid = ""
Referenced by IG.Lib.MsgObservationEvent.Read(), and IG.Lib.MsgObservationEvent.ToString().
_FindingsId
string IG.Lib.MsgObservationEvent._FindingsId = null private
Findings
DocFindings IG.Lib.MsgObservationEvent.Findings = null
_findingsStr
string IG.Lib.MsgObservationEvent._findingsStr = null private
_findingsXml
XmlDocument IG.Lib.MsgObservationEvent._findingsXml = null private
aaa
string IG.Lib.MsgObservationEvent.aaa = null
IdWithinSession
int IG.Lib.MsgObservationEvent.IdWithinSession = 0 static private
Referenced by IG.Lib.MsgObservationEvent.GenerateMessageId().
Property Documentation
Action
OeAction IG.Lib.MsgObservationEvent.Action get set private
Action is bound to order status, therefore this propety is implemented in this way!
Referenced by IG.Lib.MsgObservationEvent.Read().
ActionCode
string IG.Lib.MsgObservationEvent.ActionCode get set private
Actioncode is bound to action, which is ensured by this property.
Referenced by IG.Lib.MsgObservationEvent.Read(), and IG.Lib.MsgObservationEvent.ToString().
MessageCode
string IG.Lib.MsgObservationEvent.MessageCode get set private
MessageCode is bound to action, which is ensured by this property.
Referenced by IG.Lib.MsgObservationEvent.Read(), and IG.Lib.MsgObservationEvent.ToString().
FindingsId
string IG.Lib.MsgObservationEvent.FindingsId get private set
Referenced by IG.Lib.MsgObservationEvent.Read(), IG.Lib.MsgObservationEvent.ToString(), and IG.Lib.MsgObservationEvent.ToXml().
FindingsString
string IG.Lib.MsgObservationEvent.FindingsString get set
Gets or sets findings (attachment) as XML string. This is coupled with FindingsXml.
Referenced by IG.Lib.MsgObservationEvent.Read().
FindingsStringPartial
string IG.Lib.MsgObservationEvent.FindingsStringPartial get
Gets or sets findings (attachment) as XML string. This is coupled with FindingsXml.
Referenced by IG.Lib.MsgObservationEvent.ToString(), and IG.Lib.MsgObservationEvent.ToXml().
FindingsXml
XmlDocument IG.Lib.MsgObservationEvent.FindingsXml get set
Gets or sets findings (attachment) as XmlDocument. This is coupled with FindingsStringPartial.
Referenced by IG.Lib.MsgObservationEvent.LoadFindings(), and IG.Lib.MsgObservationEvent.ToXml().
The documentation for this class was generated from the following file:
igtest/tmp_prem/prlab/LabexBis/MsgObservationEvent.cs