Doc: IGLib EXTENDED: CShell.Modules.Workspace.ViewModels.RootFolderViewModel Class Reference
CShell.Modules.Workspace.ViewModels.RootFolderViewModel Class Reference
Public Member Functions
RootFolderViewModel (string path, CShell.Workspace workspace)
IEnumerable< IResult > ChangeRootFolder ()
Public Member Functions inherited from CShell.Modules.Workspace.ViewModels.FolderViewModel
FolderViewModel (DirectoryInfo info, CShell.Workspace workspace)
IEnumerable< IResult > AddNewFile ()
IEnumerable< IResult > AddNewFolder ()
IEnumerable< IResult > Delete ()
IEnumerable< IResult > Rename ()
Public Member Functions inherited from CShell.Modules.Workspace.ViewModels.TreeViewModel
IEnumerable< TreeViewModel > GetAllChildren ()
Recursively returns all children in the tree.
void Dispose ()
Private Member Functions
void Initialize ()
void WorkspaceOnPropertyChanged (object sender, PropertyChangedEventArgs args)
void OnChanged (object source, FileSystemEventArgs e)
void OnRenamed (object source, RenamedEventArgs e)
Private Attributes
readonly CShell.Workspace workspace
FileSystemWatcher fileSystemWatcher
Additional Inherited Members
Static Public Member Functions inherited from CShell.Modules.Workspace.ViewModels.FolderViewModel
static string WildcardToRegex (string pattern)
Protected Member Functions inherited from CShell.Modules.Workspace.ViewModels.FolderViewModel
FolderViewModel (string path, CShell.Workspace workspace)
BindableCollection< TreeViewModel > LoadChildren ()
override void EditModeFinished ()
Protected Member Functions inherited from CShell.Modules.Workspace.ViewModels.TreeViewModel
virtual void Dispose (bool disposing)
Protected Attributes inherited from CShell.Modules.Workspace.ViewModels.FolderViewModel
DirectoryInfo directoryInfo
Properties inherited from CShell.Modules.Workspace.ViewModels.FolderViewModel
override Uri IconSource [get]
string RelativePath [get]
string ToolTip [get]
override IObservableCollection< TreeViewModel >?? Children [get]
Properties inherited from CShell.Modules.Workspace.ViewModels.TreeViewModel
virtual string DisplayName [get, set]
virtual Uri IconSource [get]
virtual IObservableCollection< TreeViewModel > Children [get]
bool IsSelected [get, set]
bool IsExpanded [get, set]
bool IsEditable [get, set]
virtual bool IsInEditMode [get, set]
Constructor & Destructor Documentation
RootFolderViewModel()
CShell.Modules.Workspace.ViewModels.RootFolderViewModel.RootFolderViewModel (string path, CShell.Workspace workspace) inline
References CShell.Modules.Workspace.ViewModels.FolderViewModel.directoryInfo, CShell.Modules.Workspace.ViewModels.TreeViewModel.DisplayName, CShell.Modules.Workspace.ViewModels.RootFolderViewModel.Initialize(), CShell.Modules.Workspace.ViewModels.TreeViewModel.IsEditable, CShell.Modules.Workspace.ViewModels.TreeViewModel.IsExpanded, and CShell.Modules.Workspace.ViewModels.RootFolderViewModel.workspace.
Member Function Documentation
Initialize()
void CShell.Modules.Workspace.ViewModels.RootFolderViewModel.Initialize () inline private
References CShell.Modules.Workspace.ViewModels.FolderViewModel.directoryInfo, CShell.Modules.Workspace.ViewModels.RootFolderViewModel.fileSystemWatcher, CShell.Modules.Workspace.ViewModels.RootFolderViewModel.OnChanged(), CShell.Modules.Workspace.ViewModels.RootFolderViewModel.OnRenamed(), CShell.Workspace.PropertyChanged, CShell.Modules.Workspace.ViewModels.RootFolderViewModel.workspace, and CShell.Modules.Workspace.ViewModels.RootFolderViewModel.WorkspaceOnPropertyChanged().
Referenced by CShell.Modules.Workspace.ViewModels.RootFolderViewModel.RootFolderViewModel().
WorkspaceOnPropertyChanged()
void CShell.Modules.Workspace.ViewModels.RootFolderViewModel.WorkspaceOnPropertyChanged (object sender, PropertyChangedEventArgs args) inline private
References CShell.Modules.Workspace.ViewModels.FolderViewModel.Children, CShell.Modules.Workspace.ViewModels.FolderViewModel.directoryInfo, CShell.Modules.Workspace.ViewModels.TreeViewModel.DisplayName, CShell.Modules.Workspace.ViewModels.RootFolderViewModel.fileSystemWatcher, CShell.Modules.Workspace.ViewModels.FolderViewModel.LoadChildren(), CShell.Modules.Workspace.ViewModels.FolderViewModel.RelativePath, CShell.Workspace.RootFolder, CShell.Modules.Workspace.ViewModels.FolderViewModel.ToolTip, and CShell.Modules.Workspace.ViewModels.RootFolderViewModel.workspace.
Referenced by CShell.Modules.Workspace.ViewModels.RootFolderViewModel.Initialize().
OnChanged()
void CShell.Modules.Workspace.ViewModels.RootFolderViewModel.OnChanged (object source, FileSystemEventArgs e) inline private
References CShell.Modules.Workspace.ViewModels.FolderViewModel.Children, and CShell.Modules.Workspace.ViewModels.FolderViewModel.LoadChildren().
Referenced by CShell.Modules.Workspace.ViewModels.RootFolderViewModel.Initialize().
OnRenamed()
void CShell.Modules.Workspace.ViewModels.RootFolderViewModel.OnRenamed (object source, RenamedEventArgs e) inline private
References CShell.Modules.Workspace.ViewModels.FolderViewModel.Children, and CShell.Modules.Workspace.ViewModels.FolderViewModel.LoadChildren().
Referenced by CShell.Modules.Workspace.ViewModels.RootFolderViewModel.Initialize().
ChangeRootFolder()
IEnumerable<IResult> CShell.Modules.Workspace.ViewModels.RootFolderViewModel.ChangeRootFolder () inline
References CShell.Framework.Results.Show.Dialog().
Member Data Documentation
workspace
readonly CShell.Workspace CShell.Modules.Workspace.ViewModels.RootFolderViewModel.workspace private
Referenced by CShell.Modules.Workspace.ViewModels.RootFolderViewModel.Initialize(), CShell.Modules.Workspace.ViewModels.RootFolderViewModel.RootFolderViewModel(), and CShell.Modules.Workspace.ViewModels.RootFolderViewModel.WorkspaceOnPropertyChanged().
fileSystemWatcher
FileSystemWatcher CShell.Modules.Workspace.ViewModels.RootFolderViewModel.fileSystemWatcher private
Referenced by CShell.Modules.Workspace.ViewModels.RootFolderViewModel.Initialize(), and CShell.Modules.Workspace.ViewModels.RootFolderViewModel.WorkspaceOnPropertyChanged().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Workspace/ViewModels/RootFolderViewModel.cs