Doc: IGLib EXTENDED: AForge.Math.Geometry.SimpleShapeChecker Class Reference
AForge.Math.Geometry.SimpleShapeChecker Class Reference
A class for checking simple geometrical shapes.
Public Member Functions
ShapeType CheckShapeType (List< IntPoint > edgePoints)
Check type of the shape formed by specified points.
bool IsCircle (List< IntPoint > edgePoints)
Check if the specified set of points form a circle shape.
bool IsCircle (List< IntPoint > edgePoints, out Point center, out float radius)
Check if the specified set of points form a circle shape.
bool IsQuadrilateral (List< IntPoint > edgePoints)
Check if the specified set of points form a quadrilateral shape.
bool IsQuadrilateral (List< IntPoint > edgePoints, out List< IntPoint > corners)
Check if the specified set of points form a quadrilateral shape.
bool IsTriangle (List< IntPoint > edgePoints)
Check if the specified set of points form a triangle shape.
bool IsTriangle (List< IntPoint > edgePoints, out List< IntPoint > corners)
Check if the specified set of points form a triangle shape.
bool IsConvexPolygon (List< IntPoint > edgePoints, out List< IntPoint > corners)
Check if the specified set of points form a convex polygon shape.
PolygonSubType CheckPolygonSubType (List< IntPoint > corners)
Check sub type of a convex polygon.
bool CheckIfPointsFitShape (List< IntPoint > edgePoints, List< IntPoint > corners)
Check if a shape specified by the set of points fits a convex polygon specified by the set of corners.
Properties
float MinAcceptableDistortion [get, set]
Minimum value of allowed shapes' distortion.
float RelativeDistortionLimit [get, set]
Maximum value of allowed shapes' distortion, [0, 1].
float AngleError [get, set]
Maximum allowed angle error in degrees, [0, 20].
float LengthError [get, set]
Maximum allowed difference in sides' length (relative to shapes' size), [0, 1].
Private Member Functions
List< IntPoint > GetShapeCorners (List< IntPoint > edgePoints)
Private Attributes
FlatAnglesOptimizer shapeOptimizer = new FlatAnglesOptimizer(160)
float minAcceptableDistortion = 0.5f
float relativeDistortionLimit = 0.03f
float angleError = 7
float lengthError = 0.1f
Detailed Description
A class for checking simple geometrical shapes.
The class performs checking/detection of some simple geometrical shapes for provided set of points (shape's edge points). During the check the class goes through the list of all provided points and checks how accurately they fit into assumed shape.
All the shape checks allow some deviation of points from the shape with assumed parameters. In other words it is allowed that specified set of points may form a little bit distorted shape, which may be still recognized. The allowed amount of distortion is controlled by two properties (MinAcceptableDistortion and RelativeDistortionLimit), which allow higher distortion level for bigger shapes and smaller amount of distortion for smaller shapes. Checking specified set of points, the class calculates mean distance between specified set of points and edge of the assumed shape. If the mean distance is equal to or less than maximum allowed distance, then a shape is recognized. The maximum allowed distance is calculated as:
maxDistance = max(minAcceptableDistortion, relativeDistortionLimit * (width + height) / 2)
, where width and height is the size of bounding rectangle for the specified points.
See also AngleError and LengthError properties, which set acceptable errors for polygon sub type checking done by CheckPolygonSubType method.
<note>See the next article for details about the implemented algorithms: Detecting some simple shapes in images. </note>
Sample usage:
private List<IntPoint> idealCicle = new List<IntPoint>();
private List<IntPoint> distorredCircle = new List<IntPoint>();
System.Random rand = new System.Random();
// generate sample circles
float radius = 100;
for (int i = 0; i < 360; i += 10)
{
    float angle = (float) ( (float) i / 180 * System.Math.PI );
    // add point to ideal circle
    idealCicle.Add( new IntPoint(
        (int) ( radius * System.Math.Cos( angle ) ),
        (int) ( radius * System.Math.Sin( angle ) ) ) );
    // add a bit distortion for distorred cirlce
    float distorredRadius = radius + rand.Next( 7 ) - 3;
    distorredCircle.Add( new IntPoint(
        (int) ( distorredRadius * System.Math.Cos( angle ) ),
        (int) ( distorredRadius * System.Math.Sin( angle ) ) ) );
}
// check shape
SimpleShapeChecker shapeChecker = new SimpleShapeChecker();
if (shapeChecker.IsCircle(idealCicle))
{
    // ...
}
if (shapeChecker.CheckShapeType(distorredCircle) == ShapeType.Circle)
{
    // ...
}
Member Function Documentation
CheckShapeType()
ShapeType AForge.Math.Geometry.SimpleShapeChecker.CheckShapeType (List< IntPoint > edgePoints) inline
Check type of the shape formed by specified points.
Parameters
edgePoints Shape's points to check.
Returns
Returns type of the detected shape.
References AForge.Math.Geometry.SimpleShapeChecker.IsCircle(), and AForge.Math.Geometry.SimpleShapeChecker.IsConvexPolygon().
Referenced by AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckShapeTypeTest().
IsCircle() [1/2]
bool AForge.Math.Geometry.SimpleShapeChecker.IsCircle (List< IntPoint > edgePoints) inline
Check if the specified set of points form a circle shape.
Parameters
edgePoints Shape's points to check.
Returns
Returns true if the specified set of points form a circle shape or false otherwise.
<note>Circle shape must contain at least 8 points to be recognized. The method returns false always, of number of points in the specified shape is less than 8.</note>
Referenced by AForge.Math.Geometry.SimpleShapeChecker.CheckShapeType(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsCircleTest(), and ShapeChecker.MainForm.ProcessImage().
IsCircle() [2/2]
bool AForge.Math.Geometry.SimpleShapeChecker.IsCircle (List< IntPoint > edgePoints, out Point center, out float radius) inline
Check if the specified set of points form a circle shape.
Parameters
edgePoints Shape's points to check.
center Receives circle's center on successful return.
radius Receives circle's radius on successful return.
Returns
Returns true if the specified set of points form a circle shape or false otherwise.
<note>Circle shape must contain at least 8 points to be recognized. The method returns false always, of number of points in the specified shape is less than 8.</note>
References AForge.Math.Geometry.PointsCloud.GetBoundingRectangle(), AForge.Math.Geometry.SimpleShapeChecker.minAcceptableDistortion, AForge.Math.Geometry.SimpleShapeChecker.relativeDistortionLimit, AForge.IntPoint.X, and AForge.IntPoint.Y.
IsQuadrilateral() [1/2]
bool AForge.Math.Geometry.SimpleShapeChecker.IsQuadrilateral (List< IntPoint > edgePoints) inline
Check if the specified set of points form a quadrilateral shape.
Parameters
edgePoints Shape's points to check.
Returns
Returns true if the specified set of points form a quadrilateral shape or false otherwise.
Referenced by AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckQuadrilateralCornersTest(), and AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsQuadrilateralTest().
IsQuadrilateral() [2/2]
bool AForge.Math.Geometry.SimpleShapeChecker.IsQuadrilateral (List< IntPoint > edgePoints, out List< IntPoint > corners) inline
Check if the specified set of points form a quadrilateral shape.
Parameters
edgePoints Shape's points to check.
corners List of quadrilateral corners on successful return.
Returns
Returns true if the specified set of points form a quadrilateral shape or false otherwise.
References AForge.Math.Geometry.SimpleShapeChecker.CheckIfPointsFitShape(), and AForge.Math.Geometry.SimpleShapeChecker.GetShapeCorners().
IsTriangle() [1/2]
bool AForge.Math.Geometry.SimpleShapeChecker.IsTriangle (List< IntPoint > edgePoints) inline
Check if the specified set of points form a triangle shape.
Parameters
edgePoints Shape's points to check.
Returns
Returns true if the specified set of points form a triangle shape or false otherwise.
Referenced by AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsTriangleTest().
IsTriangle() [2/2]
bool AForge.Math.Geometry.SimpleShapeChecker.IsTriangle (List< IntPoint > edgePoints, out List< IntPoint > corners) inline
Check if the specified set of points form a triangle shape.
Parameters
edgePoints Shape's points to check.
corners List of triangle corners on successful return.
Returns
Returns true if the specified set of points form a triangle shape or false otherwise.
References AForge.Math.Geometry.SimpleShapeChecker.CheckIfPointsFitShape(), and AForge.Math.Geometry.SimpleShapeChecker.GetShapeCorners().
IsConvexPolygon()
bool AForge.Math.Geometry.SimpleShapeChecker.IsConvexPolygon (List< IntPoint > edgePoints, out List< IntPoint > corners) inline
Check if the specified set of points form a convex polygon shape.
Parameters
edgePoints Shape's points to check.
corners List of polygon corners on successful return.
Returns
Returns true if the specified set of points form a convex polygon shape or false otherwise.
<note>The method is able to detect only triangles and quadrilaterals for now. Check number of detected corners to resolve type of the detected polygon. </note>
References AForge.Math.Geometry.SimpleShapeChecker.CheckIfPointsFitShape(), and AForge.Math.Geometry.SimpleShapeChecker.GetShapeCorners().
Referenced by AForge.Math.Geometry.SimpleShapeChecker.CheckShapeType(), AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.IsConvexPolygon(), and ShapeChecker.MainForm.ProcessImage().
CheckPolygonSubType()
PolygonSubType AForge.Math.Geometry.SimpleShapeChecker.CheckPolygonSubType (List< IntPoint > corners) inline
Check sub type of a convex polygon.
Parameters
corners Corners of the convex polygon to check.
Returns
Return detected sub type of the specified shape.
The method check corners of a convex polygon detecting its subtype. Polygon's corners are usually retrieved using IsConvexPolygon method, but can be any list of 3-4 points (only sub types of triangles and quadrilateral are checked).
See AngleError and LengthError properties, which set acceptable errors for polygon sub type checking.
References AForge.Math.Geometry.SimpleShapeChecker.angleError, AForge.Math.Geometry.GeometryTools.GetAngleBetweenLines(), AForge.Math.Geometry.GeometryTools.GetAngleBetweenVectors(), AForge.Math.Geometry.PointsCloud.GetBoundingRectangle(), AForge.Math.Geometry.SimpleShapeChecker.lengthError, AForge.IntPoint.X, and AForge.IntPoint.Y.
Referenced by AForge.Math.Geometry.Tests.SimpleShapeCheckerTest.CheckPolygonSubTypeTest(), and ShapeChecker.MainForm.ProcessImage().
CheckIfPointsFitShape()
bool AForge.Math.Geometry.SimpleShapeChecker.CheckIfPointsFitShape (List< IntPoint > edgePoints, List< IntPoint > corners) inline
Check if a shape specified by the set of points fits a convex polygon specified by the set of corners.
Parameters
edgePoints Shape's points to check.
corners Corners of convex polygon to check fitting into.
Returns
Returns true if the specified shape fits the specified convex polygon or false otherwise.
The method checks if the set of specified points form the same shape as the set of provided corners.
References AForge.Math.Geometry.PointsCloud.GetBoundingRectangle(), AForge.Math.Geometry.SimpleShapeChecker.minAcceptableDistortion, AForge.Math.Geometry.SimpleShapeChecker.relativeDistortionLimit, AForge.IntPoint.X, and AForge.IntPoint.Y.
Referenced by AForge.Math.Geometry.SimpleShapeChecker.IsConvexPolygon(), AForge.Math.Geometry.SimpleShapeChecker.IsQuadrilateral(), and AForge.Math.Geometry.SimpleShapeChecker.IsTriangle().
GetShapeCorners()
List<IntPoint> AForge.Math.Geometry.SimpleShapeChecker.GetShapeCorners (List< IntPoint > edgePoints) inline private
References AForge.Math.Geometry.PointsCloud.FindQuadrilateralCorners(), AForge.Math.Geometry.FlatAnglesOptimizer.OptimizeShape(), and AForge.Math.Geometry.SimpleShapeChecker.shapeOptimizer.
Referenced by AForge.Math.Geometry.SimpleShapeChecker.IsConvexPolygon(), AForge.Math.Geometry.SimpleShapeChecker.IsQuadrilateral(), and AForge.Math.Geometry.SimpleShapeChecker.IsTriangle().
Member Data Documentation
shapeOptimizer
FlatAnglesOptimizer AForge.Math.Geometry.SimpleShapeChecker.shapeOptimizer = new FlatAnglesOptimizer(160) private
Referenced by AForge.Math.Geometry.SimpleShapeChecker.GetShapeCorners().
minAcceptableDistortion
float AForge.Math.Geometry.SimpleShapeChecker.minAcceptableDistortion = 0.5f private
Referenced by AForge.Math.Geometry.SimpleShapeChecker.CheckIfPointsFitShape(), and AForge.Math.Geometry.SimpleShapeChecker.IsCircle().
relativeDistortionLimit
float AForge.Math.Geometry.SimpleShapeChecker.relativeDistortionLimit = 0.03f private
Referenced by AForge.Math.Geometry.SimpleShapeChecker.CheckIfPointsFitShape(), and AForge.Math.Geometry.SimpleShapeChecker.IsCircle().
angleError
float AForge.Math.Geometry.SimpleShapeChecker.angleError = 7 private
Referenced by AForge.Math.Geometry.SimpleShapeChecker.CheckPolygonSubType().
lengthError
float AForge.Math.Geometry.SimpleShapeChecker.lengthError = 0.1f private
Referenced by AForge.Math.Geometry.SimpleShapeChecker.CheckPolygonSubType().
Property Documentation
MinAcceptableDistortion
float AForge.Math.Geometry.SimpleShapeChecker.MinAcceptableDistortion get set
Minimum value of allowed shapes' distortion.
The property sets minimum value for allowed shapes' distortion (in pixels). See documentation to SimpleShapeChecker class for more details about this property.
Default value is set to 0.5.
RelativeDistortionLimit
float AForge.Math.Geometry.SimpleShapeChecker.RelativeDistortionLimit get set
Maximum value of allowed shapes' distortion, [0, 1].
The property sets maximum value for allowed shapes' distortion. The value is measured in [0, 1] range, which corresponds to [0%, 100%] range, which means that maximum allowed shapes' distortion is calculated relatively to shape's size. This results to higher allowed distortion level for bigger shapes and smaller allowed distortion for smaller shapers. See documentation to SimpleShapeChecker class for more details about this property.
Default value is set to 0.03 (3%).
AngleError
float AForge.Math.Geometry.SimpleShapeChecker.AngleError get set
Maximum allowed angle error in degrees, [0, 20].
The value sets maximum allowed difference between two angles to treat them as equal. It is used by CheckPolygonSubType method to check for parallel lines and angles of triangles and quadrilaterals. For example, if angle between two lines equals 5 degrees and this properties value is set to 7, then two compared lines are treated as parallel.
Default value is set to 7.
LengthError
float AForge.Math.Geometry.SimpleShapeChecker.LengthError get set
Maximum allowed difference in sides' length (relative to shapes' size), [0, 1].
The values sets maximum allowed difference between two sides' length to treat them as equal. The error value is set relative to shapes size and measured in [0, 1] range, which corresponds to [0%, 100%] range. Absolute length error in pixels is calculated as:
LengthError * (width + height) / 2
, where width and height is the size of bounding rectangle for the specified shape.
Default value is set to 0.1 (10%).
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Math/Geometry/SimpleShapeChecker.cs