Doc: IGLib EXTENDED: NUnit.TestUtilities.SimpleEventRecorder.ExpectedEventsRecorder Class Reference
NUnit.TestUtilities.SimpleEventRecorder.ExpectedEventsRecorder Class Reference
Helper class for recording expected events.
Public Member Functions
ExpectedEventsRecorder (Queue< string > actualEvents, params string[] expectedEvents)
ExpectedEventsRecorder AndThen (params string[] expectedEvents)
Adds the specified events as expected events.
void Verify ()
Verifies the recorded expected events with the actual recorded events.
Private Attributes
readonly Queue< string > _actualEvents
readonly Queue< EventMatcher > _eventMatchers
Detailed Description
Helper class for recording expected events.
Constructor & Destructor Documentation
ExpectedEventsRecorder()
NUnit.TestUtilities.SimpleEventRecorder.ExpectedEventsRecorder.ExpectedEventsRecorder (Queue< string > actualEvents, params string[] expectedEvents) inline
References NUnit.TestUtilities.SimpleEventRecorder.ExpectedEventsRecorder._actualEvents, NUnit.TestUtilities.SimpleEventRecorder.ExpectedEventsRecorder._eventMatchers, and NUnit.TestUtilities.SimpleEventRecorder.ExpectedEventsRecorder.AndThen().
Member Function Documentation
AndThen()
ExpectedEventsRecorder NUnit.TestUtilities.SimpleEventRecorder.ExpectedEventsRecorder.AndThen (params string[] expectedEvents) inline
Adds the specified events as expected events.
Parameters
expectedEvents An array of strings identifying the test events
Returns
Returns the ExpectedEventsRecorder for adding new expected events.
References NUnit.TestUtilities.SimpleEventRecorder.ExpectedEventsRecorder._eventMatchers.
Referenced by NUnit.TestUtilities.SimpleEventRecorder.ExpectedEventsRecorder.ExpectedEventsRecorder().
Verify()
void NUnit.TestUtilities.SimpleEventRecorder.ExpectedEventsRecorder.Verify () inline
Verifies the recorded expected events with the actual recorded events.
References NUnit.TestUtilities.SimpleEventRecorder.ExpectedEventsRecorder._actualEvents, NUnit.TestUtilities.SimpleEventRecorder.ExpectedEventsRecorder._eventMatchers, and NUnit.Framework.Assert.Fail().
Member Data Documentation
_actualEvents
readonly Queue<string> NUnit.TestUtilities.SimpleEventRecorder.ExpectedEventsRecorder._actualEvents private
Referenced by NUnit.TestUtilities.SimpleEventRecorder.ExpectedEventsRecorder.ExpectedEventsRecorder(), and NUnit.TestUtilities.SimpleEventRecorder.ExpectedEventsRecorder.Verify().
_eventMatchers
readonly Queue<EventMatcher> NUnit.TestUtilities.SimpleEventRecorder.ExpectedEventsRecorder._eventMatchers private
Referenced by NUnit.TestUtilities.SimpleEventRecorder.ExpectedEventsRecorder.AndThen(), NUnit.TestUtilities.SimpleEventRecorder.ExpectedEventsRecorder.ExpectedEventsRecorder(), and NUnit.TestUtilities.SimpleEventRecorder.ExpectedEventsRecorder.Verify().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/testdata/SetUpFixtureData.cs