Doc: IGLib EXTENDED: NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests Class Reference
NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests Class Reference
Public Member Functions
void SetUp ()
void TearDown ()
void ShouldSendMessagesWithValidFlowIdWhenParallelizedTestsFromNUnit3 ()
void ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit3 ()
void ShouldSendMessagesWithValidFlowIdWhenHasNoSuiteFromNUnit3 ()
void ShouldSendMessagesWithValidFlowIdWhenOutputIsEmpty ()
void ShouldSendMessagesWithValidFlowIdWhenHasNoOutput ()
void ShouldSendMessagesWithValidFlowIdWhenTestsFromNUnit2 ()
void ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit2 ()
void ShouldSendMessagesWithValidFlowIdWhenHasNoSuiteFromNUnit2 ()
Private Member Functions
TeamCityServiceMessagePublisher CreateInstance ()
Static Private Member Functions
static XmlNode CreateMessage (string text)
static XmlNode CreateStartRun (int count)
static XmlNode CreateTestRun ()
static XmlNode CreateStartSuite (string id, string parentId, string name)
static XmlNode CreateFinishSuite (string id, string parentId, string name)
static XmlNode CreateStartTest (string id, string parentId, string name)
static XmlNode CreateTestCaseSuccessful (string id, string parentId, string name, string duration, string output)
static XmlNode CreateTestCaseFailed (string id, string parentId, string name, string duration, string message, string stackTrace)
static string GetNamedAttr (string attrName, string attrValue)
static string GetNamedElement (string elementName, string elementValue)
Private Attributes
StringBuilder _output
StringWriter _outputWriter
Member Function Documentation
SetUp()
void NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.SetUp () inline
References NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests._output, and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests._outputWriter.
TearDown()
void NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.TearDown () inline
References NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests._outputWriter.
ShouldSendMessagesWithValidFlowIdWhenParallelizedTestsFromNUnit3()
void NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenParallelizedTestsFromNUnit3 () inline
References NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests._output, NUnit.Framework.Assert.AreEqual(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateFinishSuite(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateInstance(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartRun(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartSuite(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartTest(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestCaseFailed(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestCaseSuccessful(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestRun().
ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit3()
void NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit3 () inline
References NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests._output, NUnit.Framework.Assert.AreEqual(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateFinishSuite(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateInstance(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartRun(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartSuite(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartTest(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestCaseSuccessful(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestRun().
ShouldSendMessagesWithValidFlowIdWhenHasNoSuiteFromNUnit3()
void NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoSuiteFromNUnit3 () inline
References NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests._output, NUnit.Framework.Assert.AreEqual(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateInstance(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartRun(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartTest(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestCaseSuccessful(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestRun().
ShouldSendMessagesWithValidFlowIdWhenOutputIsEmpty()
void NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenOutputIsEmpty () inline
References NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests._output, NUnit.Framework.Assert.AreEqual(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateInstance(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartRun(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartTest(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestCaseSuccessful(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestRun().
ShouldSendMessagesWithValidFlowIdWhenHasNoOutput()
void NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoOutput () inline
References NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests._output, NUnit.Framework.Assert.AreEqual(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateInstance(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartRun(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartTest(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestCaseSuccessful(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestRun().
ShouldSendMessagesWithValidFlowIdWhenTestsFromNUnit2()
void NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenTestsFromNUnit2 () inline
References NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests._output, NUnit.Framework.Assert.AreEqual(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateFinishSuite(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateInstance(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartRun(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartSuite(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartTest(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestCaseFailed(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestCaseSuccessful(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestRun().
ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit2()
void NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit2 () inline
References NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests._output, NUnit.Framework.Assert.AreEqual(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateFinishSuite(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateInstance(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartRun(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartSuite(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartTest(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestCaseSuccessful(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestRun().
ShouldSendMessagesWithValidFlowIdWhenHasNoSuiteFromNUnit2()
void NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoSuiteFromNUnit2 () inline
References NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests._output, NUnit.Framework.Assert.AreEqual(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateInstance(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartRun(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartTest(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestCaseSuccessful(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestRun().
CreateMessage()
static XmlNode NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateMessage (string text) inline static private
Referenced by NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateFinishSuite(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartRun(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartSuite(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartTest(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestCaseFailed(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestCaseSuccessful(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestRun().
CreateStartRun()
static XmlNode NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartRun (int count) inline static private
References NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateMessage().
Referenced by NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit2(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit3(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoOutput(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoSuiteFromNUnit2(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoSuiteFromNUnit3(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenOutputIsEmpty(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenParallelizedTestsFromNUnit3(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenTestsFromNUnit2().
CreateTestRun()
static XmlNode NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestRun () inline static private
References NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateMessage().
Referenced by NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit2(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit3(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoOutput(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoSuiteFromNUnit2(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoSuiteFromNUnit3(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenOutputIsEmpty(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenParallelizedTestsFromNUnit3(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenTestsFromNUnit2().
CreateStartSuite()
static XmlNode NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartSuite (string id, string parentId, string name) inline static private
References NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateMessage(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.GetNamedAttr().
Referenced by NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit2(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit3(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenParallelizedTestsFromNUnit3(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenTestsFromNUnit2().
CreateFinishSuite()
static XmlNode NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateFinishSuite (string id, string parentId, string name) inline static private
References NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateMessage(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.GetNamedAttr().
Referenced by NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit2(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit3(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenParallelizedTestsFromNUnit3(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenTestsFromNUnit2().
CreateStartTest()
static XmlNode NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartTest (string id, string parentId, string name) inline static private
References NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateMessage(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.GetNamedAttr().
Referenced by NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit2(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit3(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoOutput(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoSuiteFromNUnit2(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoSuiteFromNUnit3(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenOutputIsEmpty(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenParallelizedTestsFromNUnit3(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenTestsFromNUnit2().
CreateTestCaseSuccessful()
static XmlNode NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestCaseSuccessful (string id, string parentId, string name, string duration, string output) inline static private
References NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateMessage(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.GetNamedAttr(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.GetNamedElement().
Referenced by NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit2(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit3(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoOutput(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoSuiteFromNUnit2(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoSuiteFromNUnit3(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenOutputIsEmpty(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenParallelizedTestsFromNUnit3(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenTestsFromNUnit2().
CreateTestCaseFailed()
static XmlNode NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestCaseFailed (string id, string parentId, string name, string duration, string message, string stackTrace) inline static private
References NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateMessage(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.GetNamedAttr().
Referenced by NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenParallelizedTestsFromNUnit3(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenTestsFromNUnit2().
CreateInstance()
TeamCityServiceMessagePublisher NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateInstance () inline private
References NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests._outputWriter.
Referenced by NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit2(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit3(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoOutput(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoSuiteFromNUnit2(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoSuiteFromNUnit3(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenOutputIsEmpty(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenParallelizedTestsFromNUnit3(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenTestsFromNUnit2().
GetNamedAttr()
static string NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.GetNamedAttr (string attrName, string attrValue) inline static private
Referenced by NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateFinishSuite(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartSuite(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateStartTest(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestCaseFailed(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestCaseSuccessful().
GetNamedElement()
static string NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.GetNamedElement (string elementName, string elementValue) inline static private
Referenced by NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateTestCaseSuccessful().
Member Data Documentation
_output
StringBuilder NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests._output private
Referenced by NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.SetUp(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit2(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHas1SuiteFromNUnit3(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoOutput(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoSuiteFromNUnit2(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenHasNoSuiteFromNUnit3(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenOutputIsEmpty(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenParallelizedTestsFromNUnit3(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.ShouldSendMessagesWithValidFlowIdWhenTestsFromNUnit2().
_outputWriter
StringWriter NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests._outputWriter private
Referenced by NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.CreateInstance(), NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.SetUp(), and NUnit.ConsoleRunner.Tests.TeamCityServiceMessagePublisherTests.TearDown().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitConsole/nunit3-console.tests/TeamCityServiceMessagePublisherTests.cs