Doc: IGLib EXTENDED: alglib.testtsortunit Class Reference
alglib.testtsortunit Class Reference
Static Public Member Functions
static bool testtsort (bool silent)
static bool testtsort (bool silent)
static bool _pexec_testtsort (bool silent)
Static Private Member Functions
static void unset2d (ref complex[,] a)
static void unset1d (ref double[] a)
static void unset1di (ref int[] a)
static void testsortresults (double[] asorted, int[] p1, int[] p2, double[] aoriginal, int n, ref bool waserrors)
static void unset2d (ref complex[,] a)
static void unset1d (ref double[] a)
static void unset1di (ref int[] a)
static void testsortresults (double[] asorted, int[] p1, int[] p2, double[] aoriginal, int n, ref bool waserrors)
Member Function Documentation
testtsort() [1/2]
static bool alglib.testtsortunit.testtsort (bool silent) inline static
References alglib.math.randominteger(), alglib.tsort.tagsort(), alglib.tsort.tagsortfast(), alglib.tsort.tagsortfasti(), alglib.tsort.tagsortfastr(), alglib.tsort.tagsortmiddleir(), alglib.testtsortunit.testsortresults(), and alglib.testtsortunit.unset1di().
Referenced by alglib.testtsortunit._pexec_testtsort(), and _Test.Main().
unset2d() [1/2]
static void alglib.testtsortunit.unset2d (ref complex a[,]) inline static private
References alglib.math.randomreal().
unset1d() [1/2]
static void alglib.testtsortunit.unset1d (ref double[] a) inline static private
References alglib.math.randomreal().
unset1di() [1/2]
static void alglib.testtsortunit.unset1di (ref int[] a) inline static private
References alglib.math.randominteger().
Referenced by alglib.testtsortunit.testtsort().
testsortresults() [1/2]
static void alglib.testtsortunit.testsortresults (double[] asorted, int[] p1, int[] p2, double[] aoriginal, int n, ref bool waserrors) inline static private
Referenced by alglib.testtsortunit.testtsort().
testtsort() [2/2]
static bool alglib.testtsortunit.testtsort (bool silent) inline static
References alglib.math.randominteger(), alglib.tsort.tagsort(), alglib.tsort.tagsortfast(), alglib.tsort.tagsortfasti(), alglib.tsort.tagsortfastr(), alglib.tsort.tagsortmiddleir(), alglib.testtsortunit.testsortresults(), and alglib.testtsortunit.unset1di().
_pexec_testtsort()
static bool alglib.testtsortunit._pexec_testtsort (bool silent) inline static
References alglib.testtsortunit.testtsort().
Referenced by _Test.Main().
unset2d() [2/2]
static void alglib.testtsortunit.unset2d (ref complex a[,]) inline static private
References alglib.math.randomreal().
unset1d() [2/2]
static void alglib.testtsortunit.unset1d (ref double[] a) inline static private
References alglib.math.randomreal().
unset1di() [2/2]
static void alglib.testtsortunit.unset1di (ref int[] a) inline static private
References alglib.math.randominteger().
testsortresults() [2/2]
static void alglib.testtsortunit.testsortresults (double[] asorted, int[] p1, int[] p2, double[] aoriginal, int n, ref bool waserrors) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs