Doc: IGLib EXTENDED: alglib.testalglibbasicsunit.poolsummand Class Reference
alglib.testalglibbasicsunit.poolsummand Class Reference
Public Member Functions
poolsummand ()
override void init ()
override alglib.apobject make_copy ()
Public Attributes
int val
Constructor & Destructor Documentation
poolsummand()
alglib.testalglibbasicsunit.poolsummand.poolsummand () inline
References alglib.testalglibbasicsunit.poolsummand.init().
Referenced by alglib.testalglibbasicsunit.poolsummand.make_copy().
Member Function Documentation
init()
override void alglib.testalglibbasicsunit.poolsummand.init () inline virtual
Implements alglib.apobject.
Referenced by alglib.testalglibbasicsunit.poolsummand.poolsummand().
make_copy()
override alglib.apobject alglib.testalglibbasicsunit.poolsummand.make_copy () inline virtual
Implements alglib.apobject.
References alglib.testalglibbasicsunit.poolsummand.poolsummand(), and alglib.testalglibbasicsunit.poolsummand.val.
Member Data Documentation
val
int alglib.testalglibbasicsunit.poolsummand.val
Referenced by alglib.testalglibbasicsunit.poolsummand.make_copy(), and alglib.testalglibbasicsunit.performtestpoolsum().
The documentation for this class was generated from the following file:
igtest/numerics/alglib_0.8.2/tests/test_c.cs