Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DTRTRS Class Reference
DotNumerics.LinearAlgebra.CSLapack.DTRTRS Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DTRTRS (LSAME lsame, DTRSM dtrsm, XERBLA xerbla)
DTRTRS ()
void Run (string UPLO, string TRANS, string DIAG, int N, int NRHS, double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB, ref int INFO)
Private Attributes
LSAME _lsame
DTRSM _dtrsm
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DTRTRS solves a triangular system of the form
A * X = B or A**T * X = B,
where A is a triangular matrix of order N, and B is an N-by-NRHS matrix. A check is made to verify that A is nonsingular.
/summary>
Constructor & Destructor Documentation
DTRTRS() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DTRTRS.DTRTRS (LSAME lsame, DTRSM dtrsm, XERBLA xerbla) inline
DTRTRS() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DTRTRS.DTRTRS () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DTRTRS.Run (string UPLO, string TRANS, string DIAG, int N, int NRHS, double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB, ref int INFO) inline
Purpose
DTRTRS solves a triangular system of the form
A * X = B or A**T * X = B,
where A is a triangular matrix of order N, and B is an N-by-NRHS matrix. A check is made to verify that A is nonsingular.
/summary>
Parameters
UPLO (input) CHARACTER*1 = 'U': A is upper triangular; = 'L': A is lower triangular. /param>
Parameters
TRANS (input) CHARACTER*1 Specifies the form of the system of equations: = 'N': A * X = B (No transpose) = 'T': A**T * X = B (Transpose) = 'C': A**H * X = B (Conjugate transpose = Transpose) /param>
Parameters
DIAG (input) CHARACTER*1 = 'N': A is non-unit triangular; = 'U': A is unit triangular. /param>
Parameters
N (input) INTEGER The order of the matrix A. N .GE. 0. /param>
Parameters
NRHS (input) INTEGER The number of right hand sides, i.e., the number of columns of the matrix B. NRHS .GE. 0. /param>
Parameters
A
X = B or A**T * X = B, /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,N). /param>
Parameters
B (input/output) DOUBLE PRECISION array, dimension (LDB,NRHS) On entry, the right hand side matrix B. On exit, if INFO = 0, the solution matrix X. /param>
Parameters
LDB (input) INTEGER The leading dimension of the array B. LDB .GE. max(1,N). /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value .GT. 0: if INFO = i, the i-th diagonal element of A is zero, indicating that the matrix is singular and the solutions X have not been computed. /param>
References DotNumerics.LinearAlgebra.CSLapack.DTRTRS.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRSM.Run(), and DotNumerics.LinearAlgebra.CSLapack.DTRTRS.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGGLSE.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGGLM.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGELS.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DTRTRS._lsame private
_dtrsm
DTRSM DotNumerics.LinearAlgebra.CSLapack.DTRTRS._dtrsm private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DTRTRS._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DTRTRS.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTRTRS.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DTRTRS.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTRTRS.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dtrtrs.cs