Doc: IGLib EXTENDED: NUnit.Common.Tests.ExtendedTextWrapperTests Class Reference
NUnit.Common.Tests.ExtendedTextWrapperTests Class Reference
Public Member Functions
void SetUp ()
void Write ()
void Write_ColorStyle ()
void WriteLine ()
void WriteLine_ColorStyle ()
void WriteLabel ()
void WriteLabel_ColorStyle ()
void WriteLabelLine ()
void WriteLabelLine_ColorStyle ()
Private Attributes
StringBuilder sb
ExtendedTextWrapper writer
Static Private Attributes
const string LABEL = "My Label: "
const string OPTION = "option value"
const string TESTING = "testing"
static readonly string NL = Environment.NewLine
Member Function Documentation
SetUp()
void NUnit.Common.Tests.ExtendedTextWrapperTests.SetUp () inline
References NUnit.Common.Tests.ExtendedTextWrapperTests.sb, and NUnit.Common.Tests.ExtendedTextWrapperTests.writer.
Write()
void NUnit.Common.Tests.ExtendedTextWrapperTests.Write () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Common.Tests.ExtendedTextWrapperTests.sb, NUnit.Common.Tests.ExtendedTextWrapperTests.TESTING, NUnit.Framework.Assert.That(), NUnit.Common.ExtendedTextWrapper.Write(), and NUnit.Common.Tests.ExtendedTextWrapperTests.writer.
Write_ColorStyle()
void NUnit.Common.Tests.ExtendedTextWrapperTests.Write_ColorStyle () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Common.Tests.ExtendedTextWrapperTests.sb, NUnit.Common.Tests.ExtendedTextWrapperTests.TESTING, NUnit.Framework.Assert.That(), NUnit.Common.ExtendedTextWrapper.Write(), and NUnit.Common.Tests.ExtendedTextWrapperTests.writer.
WriteLine()
void NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLine () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Common.Tests.ExtendedTextWrapperTests.NL, NUnit.Common.Tests.ExtendedTextWrapperTests.sb, NUnit.Common.Tests.ExtendedTextWrapperTests.TESTING, NUnit.Framework.Assert.That(), NUnit.Common.ExtendedTextWrapper.WriteLine(), and NUnit.Common.Tests.ExtendedTextWrapperTests.writer.
WriteLine_ColorStyle()
void NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLine_ColorStyle () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Common.Tests.ExtendedTextWrapperTests.NL, NUnit.Common.Tests.ExtendedTextWrapperTests.sb, NUnit.Common.Tests.ExtendedTextWrapperTests.TESTING, NUnit.Framework.Assert.That(), NUnit.Common.ExtendedTextWrapper.WriteLine(), and NUnit.Common.Tests.ExtendedTextWrapperTests.writer.
WriteLabel()
void NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabel () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Common.Tests.ExtendedTextWrapperTests.LABEL, NUnit.Common.Tests.ExtendedTextWrapperTests.OPTION, NUnit.Common.Tests.ExtendedTextWrapperTests.sb, NUnit.Framework.Assert.That(), NUnit.Common.ExtendedTextWrapper.WriteLabel(), and NUnit.Common.Tests.ExtendedTextWrapperTests.writer.
WriteLabel_ColorStyle()
void NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabel_ColorStyle () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Common.Tests.ExtendedTextWrapperTests.LABEL, NUnit.Common.Tests.ExtendedTextWrapperTests.OPTION, NUnit.Common.Tests.ExtendedTextWrapperTests.sb, NUnit.Framework.Assert.That(), NUnit.Common.ExtendedTextWrapper.WriteLabel(), and NUnit.Common.Tests.ExtendedTextWrapperTests.writer.
WriteLabelLine()
void NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabelLine () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Common.Tests.ExtendedTextWrapperTests.LABEL, NUnit.Common.Tests.ExtendedTextWrapperTests.NL, NUnit.Common.Tests.ExtendedTextWrapperTests.OPTION, NUnit.Common.Tests.ExtendedTextWrapperTests.sb, NUnit.Framework.Assert.That(), NUnit.Common.ExtendedTextWrapper.WriteLabelLine(), and NUnit.Common.Tests.ExtendedTextWrapperTests.writer.
WriteLabelLine_ColorStyle()
void NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabelLine_ColorStyle () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Common.Tests.ExtendedTextWrapperTests.LABEL, NUnit.Common.Tests.ExtendedTextWrapperTests.NL, NUnit.Common.Tests.ExtendedTextWrapperTests.OPTION, NUnit.Common.Tests.ExtendedTextWrapperTests.sb, NUnit.Framework.Assert.That(), NUnit.Common.ExtendedTextWrapper.WriteLabelLine(), and NUnit.Common.Tests.ExtendedTextWrapperTests.writer.
Member Data Documentation
sb
StringBuilder NUnit.Common.Tests.ExtendedTextWrapperTests.sb private
Referenced by NUnit.Common.Tests.ExtendedTextWrapperTests.SetUp(), NUnit.Common.Tests.ExtendedTextWrapperTests.Write(), NUnit.Common.Tests.ExtendedTextWrapperTests.Write_ColorStyle(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabel(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabel_ColorStyle(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabelLine(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabelLine_ColorStyle(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLine(), and NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLine_ColorStyle().
writer
ExtendedTextWrapper NUnit.Common.Tests.ExtendedTextWrapperTests.writer private
Referenced by NUnit.Common.Tests.ExtendedTextWrapperTests.SetUp(), NUnit.Common.Tests.ExtendedTextWrapperTests.Write(), NUnit.Common.Tests.ExtendedTextWrapperTests.Write_ColorStyle(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabel(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabel_ColorStyle(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabelLine(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabelLine_ColorStyle(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLine(), and NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLine_ColorStyle().
LABEL
const string NUnit.Common.Tests.ExtendedTextWrapperTests.LABEL = "My Label: " static private
Referenced by NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabel(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabel_ColorStyle(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabelLine(), and NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabelLine_ColorStyle().
OPTION
const string NUnit.Common.Tests.ExtendedTextWrapperTests.OPTION = "option value" static private
Referenced by NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabel(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabel_ColorStyle(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabelLine(), and NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabelLine_ColorStyle().
TESTING
const string NUnit.Common.Tests.ExtendedTextWrapperTests.TESTING = "testing" static private
Referenced by NUnit.Common.Tests.ExtendedTextWrapperTests.Write(), NUnit.Common.Tests.ExtendedTextWrapperTests.Write_ColorStyle(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLine(), and NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLine_ColorStyle().
NL
readonly string NUnit.Common.Tests.ExtendedTextWrapperTests.NL = Environment.NewLine static private
Referenced by NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabelLine(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLabelLine_ColorStyle(), NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLine(), and NUnit.Common.Tests.ExtendedTextWrapperTests.WriteLine_ColorStyle().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/tests/ExtendedTextWrapperTests.cs