var namespaceAForge =
[
    [ "Controls", "dc/d90/namespaceAForge_1_1Controls.html", "dc/d90/namespaceAForge_1_1Controls" ],
    [ "DebuggerVisualizers", "db/d3d/namespaceAForge_1_1DebuggerVisualizers.html", "db/d3d/namespaceAForge_1_1DebuggerVisualizers" ],
    [ "Fuzzy", "da/d87/namespaceAForge_1_1Fuzzy.html", "da/d87/namespaceAForge_1_1Fuzzy" ],
    [ "Genetic", "db/d18/namespaceAForge_1_1Genetic.html", "db/d18/namespaceAForge_1_1Genetic" ],
    [ "Imaging", "d2/d21/namespaceAForge_1_1Imaging.html", "d2/d21/namespaceAForge_1_1Imaging" ],
    [ "MachineLearning", "dd/d78/namespaceAForge_1_1MachineLearning.html", "dd/d78/namespaceAForge_1_1MachineLearning" ],
    [ "Math", "d0/d9b/namespaceAForge_1_1Math.html", "d0/d9b/namespaceAForge_1_1Math" ],
    [ "Neuro", "d1/d5c/namespaceAForge_1_1Neuro.html", "d1/d5c/namespaceAForge_1_1Neuro" ],
    [ "Robotics", "d7/dfb/namespaceAForge_1_1Robotics.html", "d7/dfb/namespaceAForge_1_1Robotics" ],
    [ "Tests", "da/d98/namespaceAForge_1_1Tests.html", "da/d98/namespaceAForge_1_1Tests" ],
    [ "Video", "da/d69/namespaceAForge_1_1Video.html", "da/d69/namespaceAForge_1_1Video" ],
    [ "Vision", "dc/d0a/namespaceAForge_1_1Vision.html", "dc/d0a/namespaceAForge_1_1Vision" ],
    [ "CommunicationBufferEventArgs", "d9/d20/classAForge_1_1CommunicationBufferEventArgs.html", "d9/d20/classAForge_1_1CommunicationBufferEventArgs" ],
    [ "ConnectionFailedException", "dd/d4b/classAForge_1_1ConnectionFailedException.html", "dd/d4b/classAForge_1_1ConnectionFailedException" ],
    [ "ConnectionLostException", "d2/d83/classAForge_1_1ConnectionLostException.html", "d2/d83/classAForge_1_1ConnectionLostException" ],
    [ "DeviceBusyException", "d2/def/classAForge_1_1DeviceBusyException.html", "d2/def/classAForge_1_1DeviceBusyException" ],
    [ "DeviceErrorException", "dd/d1b/classAForge_1_1DeviceErrorException.html", "dd/d1b/classAForge_1_1DeviceErrorException" ],
    [ "DoublePoint", "d1/dcd/structAForge_1_1DoublePoint.html", "d1/dcd/structAForge_1_1DoublePoint" ],
    [ "DoubleRange", "d8/dbc/classAForge_1_1DoubleRange.html", "d8/dbc/classAForge_1_1DoubleRange" ],
    [ "IntPoint", "dc/d3d/structAForge_1_1IntPoint.html", "dc/d3d/structAForge_1_1IntPoint" ],
    [ "IntRange", "d9/d09/classAForge_1_1IntRange.html", "d9/d09/classAForge_1_1IntRange" ],
    [ "NotConnectedException", "d6/de3/classAForge_1_1NotConnectedException.html", "d6/de3/classAForge_1_1NotConnectedException" ],
    [ "Parallel", "d3/dee/classAForge_1_1Parallel.html", "d3/dee/classAForge_1_1Parallel" ],
    [ "Point", "d2/d04/structAForge_1_1Point.html", "d2/d04/structAForge_1_1Point" ],
    [ "PolishExpression", "d6/dad/classAForge_1_1PolishExpression.html", "d6/dad/classAForge_1_1PolishExpression" ],
    [ "Range", "dd/de1/structAForge_1_1Range.html", "dd/de1/structAForge_1_1Range" ],
    [ "SystemTools", "d9/d8c/classAForge_1_1SystemTools.html", "d9/d8c/classAForge_1_1SystemTools" ],
    [ "ThreadSafeRandom", "d6/d36/classAForge_1_1ThreadSafeRandom.html", "d6/d36/classAForge_1_1ThreadSafeRandom" ]
];