Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DTRTI2 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DTRTI2 Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DTRTI2 (LSAME lsame, DSCAL dscal, DTRMV dtrmv, XERBLA xerbla)
DTRTI2 ()
void Run (string UPLO, string DIAG, int N, ref double[] A, int offset_a, int LDA, ref int INFO)
Private Attributes
LSAME _lsame
DSCAL _dscal
DTRMV _dtrmv
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DTRTI2 computes the inverse of a real upper or lower triangular matrix.
This is the Level 2 BLAS version of the algorithm.
/summary>
Constructor & Destructor Documentation
DTRTI2() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DTRTI2.DTRTI2 (LSAME lsame, DSCAL dscal, DTRMV dtrmv, XERBLA xerbla) inline
DTRTI2() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DTRTI2.DTRTI2 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DTRTI2.Run (string UPLO, string DIAG, int N, ref double[] A, int offset_a, int LDA, ref int INFO) inline
Purpose
DTRTI2 computes the inverse of a real upper or lower triangular matrix.
This is the Level 2 BLAS version of the algorithm.
/summary>
Parameters
UPLO (input) CHARACTER*1 Specifies whether the matrix A is upper or lower triangular. = 'U': Upper triangular = 'L': Lower triangular /param>
Parameters
DIAG (input) CHARACTER*1 Specifies whether or not the matrix A is unit triangular. = 'N': Non-unit triangular = 'U': Unit triangular /param>
Parameters
N (input) INTEGER The order of the matrix A. N .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the triangular matrix A. If UPLO = 'U', the leading n by n upper triangular part of the array A contains the upper triangular matrix, and the strictly lower triangular part of A is not referenced. If UPLO = 'L', the leading n by n lower triangular part of the array A contains the lower triangular matrix, and the strictly upper triangular part of A is not referenced. If DIAG = 'U', the diagonal elements of A are also not referenced and are assumed to be 1.
On exit, the (triangular) inverse of the original matrix, in the same storage format. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,N). /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -k, the k-th argument had an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.DTRTI2.ONE, DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), and DotNumerics.LinearAlgebra.CSLapack.DTRMV.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTRTRI.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DTRTI2._lsame private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DTRTI2._dscal private
_dtrmv
DTRMV DotNumerics.LinearAlgebra.CSLapack.DTRTI2._dtrmv private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DTRTI2._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DTRTI2.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTRTI2.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dtrti2.cs