Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAQR0 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAQR0 Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAQR0 (ILAENV ilaenv, DLACPY dlacpy, DLAHQR dlahqr, DLANV2 dlanv2, DLAQR3 dlaqr3, DLAQR4 dlaqr4, DLAQR5 dlaqr5)
DLAQR0 ()
void Run (bool WANTT, bool WANTZ, int N, int ILO, int IHI, ref double[] H, int offset_h, int LDH, ref double[] WR, int offset_wr, ref double[] WI, int offset_wi, int ILOZ, int IHIZ, ref double[] Z, int offset_z, int LDZ, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
ILAENV _ilaenv
DLACPY _dlacpy
DLAHQR _dlahqr
DLANV2 _dlanv2
DLAQR3 _dlaqr3
DLAQR4 _dlaqr4
DLAQR5 _dlaqr5
double[] ZDUM = new double[1 * 1]
Static Private Attributes
const int NTINY = 11
const int KEXNW = 5
const int KEXSH = 6
const double WILK1 = 0.75E0
const double WILK2 = - 0.4375E0
const double ZERO = 0.0E0
const double ONE = 1.0E0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAQR0 computes the eigenvalues of a Hessenberg matrix H and, optionally, the matrices T and Z from the Schur decomposition H = Z T Z**T, where T is an upper quasi-triangular matrix (the Schur form), and Z is the orthogonal matrix of Schur vectors.
Optionally Z may be postmultiplied into an input orthogonal matrix Q so that this routine can give the Schur factorization of a matrix A which has been reduced to the Hessenberg form H by the orthogonal matrix Q: A = Q*H*Q**T = (QZ)*T*(QZ)**T.
/summary>
Constructor & Destructor Documentation
DLAQR0() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAQR0.DLAQR0 (ILAENV ilaenv, DLACPY dlacpy, DLAHQR dlahqr, DLANV2 dlanv2, DLAQR3 dlaqr3, DLAQR4 dlaqr4, DLAQR5 dlaqr5) inline
DLAQR0() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAQR0.DLAQR0 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAQR0.Run (bool WANTT, bool WANTZ, int N, int ILO, int IHI, ref double[] H, int offset_h, int LDH, ref double[] WR, int offset_wr, ref double[] WI, int offset_wi, int ILOZ, int IHIZ, ref double[] Z, int offset_z, int LDZ, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DLAQR0 computes the eigenvalues of a Hessenberg matrix H and, optionally, the matrices T and Z from the Schur decomposition H = Z T Z**T, where T is an upper quasi-triangular matrix (the Schur form), and Z is the orthogonal matrix of Schur vectors.
Optionally Z may be postmultiplied into an input orthogonal matrix Q so that this routine can give the Schur factorization of a matrix A which has been reduced to the Hessenberg form H by the orthogonal matrix Q: A = Q*H*Q**T = (QZ)*T*(QZ)**T.
/summary>
Parameters
WANTT (input) LOGICAL = .TRUE. : the full Schur form T is required; = .FALSE.: only eigenvalues are required. /param>
Parameters
WANTZ (input) LOGICAL = .TRUE. : the matrix of Schur vectors Z is required; = .FALSE.: Schur vectors are not required. /param>
Parameters
N (input) INTEGER The order of the matrix H. N .GE. 0. /param>
Parameters
ILO (input) INTEGER /param>
Parameters
IHI (input) INTEGER It is assumed that H is already upper triangular in rows and columns 1:ILO-1 and IHI+1:N and, if ILO.GT.1, H(ILO,ILO-1) is zero. ILO and IHI are normally set by a previous call to DGEBAL, and then passed to DGEHRD when the matrix output by DGEBAL is reduced to Hessenberg form. Otherwise, ILO and IHI should be set to 1 and N, respectively. If N.GT.0, then 1.LE.ILO.LE.IHI.LE.N. If N = 0, then ILO = 1 and IHI = 0. /param>
Parameters
H (input/output) DOUBLE PRECISION array, dimension (LDH,N) On entry, the upper Hessenberg matrix H. On exit, if INFO = 0 and WANTT is .TRUE., then H contains the upper quasi-triangular matrix T from the Schur decomposition (the Schur form); 2-by-2 diagonal blocks (corresponding to complex conjugate pairs of eigenvalues) are returned in standard form, with H(i,i) = H(i+1,i+1) and H(i+1,i)*H(i,i+1).LT.0. If INFO = 0 and WANTT is .FALSE., then the contents of H are unspecified on exit. (The output value of H when INFO.GT.0 is given under the description of INFO below.)
This subroutine may explicitly set H(i,j) = 0 for i.GT.j and j = 1, 2, ... ILO-1 or j = IHI+1, IHI+2, ... N. /param>
Parameters
LDH (input) INTEGER The leading dimension of the array H. LDH .GE. max(1,N). /param>
Parameters
WR (output) DOUBLE PRECISION array, dimension (IHI) /param>
Parameters
WI (output) DOUBLE PRECISION array, dimension (IHI) The real and imaginary parts, respectively, of the computed eigenvalues of H(ILO:IHI,ILO:IHI) are stored WR(ILO:IHI) and WI(ILO:IHI). If two eigenvalues are computed as a complex conjugate pair, they are stored in consecutive elements of WR and WI, say the i-th and (i+1)th, with WI(i) .GT. 0 and WI(i+1) .LT. 0. If WANTT is .TRUE., then the eigenvalues are stored in the same order as on the diagonal of the Schur form returned in H, with WR(i) = H(i,i) and, if H(i:i+1,i:i+1) is a 2-by-2 diagonal block, WI(i) = sqrt(-H(i+1,i)*H(i,i+1)) and WI(i+1) = -WI(i). /param>
Parameters
ILOZ (input) INTEGER /param>
Parameters
IHIZ (input) INTEGER Specify the rows of Z to which transformations must be applied if WANTZ is .TRUE.. 1 .LE. ILOZ .LE. ILO; IHI .LE. IHIZ .LE. N. /param>
Parameters
Z (input/output) DOUBLE PRECISION array, dimension (LDZ,IHI) If WANTZ is .FALSE., then Z is not referenced. If WANTZ is .TRUE., then Z(ILO:IHI,ILOZ:IHIZ) is replaced by Z(ILO:IHI,ILOZ:IHIZ)*U where U is the orthogonal Schur factor of H(ILO:IHI,ILO:IHI). (The output value of Z when INFO.GT.0 is given under the description of INFO below.) /param>
Parameters
LDZ (input) INTEGER The leading dimension of the array Z. if WANTZ is .TRUE. then LDZ.GE.MAX(1,IHIZ). Otherwize, LDZ.GE.1. /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension LWORK On exit, if LWORK = -1, WORK(1) returns an estimate of the optimal value for LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. max(1,N) is sufficient, but LWORK typically as large as 6*N may be required for optimal performance. A workspace query to determine the optimal workspace size is recommended.
If LWORK = -1, then DLAQR0 does a workspace query. In this case, DLAQR0 checks the input parameters and estimates the optimal workspace size for the given values of N, ILO and IHI. The estimate is returned in WORK(1). No error message related to LWORK is issued by XERBLA. Neither H nor Z are accessed.
/param>
Parameters
INFO (output) INTEGER = 0: successful exit .GT. 0: if INFO = i, DLAQR0 failed to compute all of the eigenvalues. Elements 1:ilo-1 and i+1:n of WR and WI contain those eigenvalues which have been successfully computed. (Failures are rare.)
If INFO .GT. 0 and WANT is .FALSE., then on exit, the remaining unconverged eigenvalues are the eigen- values of the upper Hessenberg matrix rows and columns ILO through INFO of the final, output value of H.
If INFO .GT. 0 and WANTT is .TRUE., then on exit
(*) (initial value of H)*U = U*(final value of H)
where U is an orthogonal matrix. The final value of H is upper Hessenberg and quasi-triangular in rows and columns INFO+1 through IHI.
If INFO .GT. 0 and WANTZ is .TRUE., then on exit
(final value of Z(ILO:IHI,ILOZ:IHIZ) = (initial value of Z(ILO:IHI,ILOZ:IHIZ)*U
where U is the orthogonal matrix in (*) (regard- less of the value of WANTT.)
If INFO .GT. 0 and WANTZ is .FALSE., then Z is not accessed.
/param>
References DotNumerics.FortranLibrary.FortranLib.Copy(), DotNumerics.LinearAlgebra.CSLapack.DLAQR0.KEXNW, DotNumerics.LinearAlgebra.CSLapack.DLAQR0.KEXSH, DotNumerics.FortranLibrary.FortranLib.Mod(), DotNumerics.LinearAlgebra.CSLapack.DLAQR0.NTINY, DotNumerics.LinearAlgebra.CSLapack.DLAQR0.ONE, DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANV2.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAHQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR5.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR3.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR4.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR0.WILK1, DotNumerics.LinearAlgebra.CSLapack.DLAQR0.WILK2, DotNumerics.LinearAlgebra.CSLapack.DLAQR0.ZDUM, and DotNumerics.LinearAlgebra.CSLapack.DLAQR0.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DHSEQR.Run().
Member Data Documentation
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DLAQR0._ilaenv private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DLAQR0._dlacpy private
_dlahqr
DLAHQR DotNumerics.LinearAlgebra.CSLapack.DLAQR0._dlahqr private
_dlanv2
DLANV2 DotNumerics.LinearAlgebra.CSLapack.DLAQR0._dlanv2 private
_dlaqr3
DLAQR3 DotNumerics.LinearAlgebra.CSLapack.DLAQR0._dlaqr3 private
_dlaqr4
DLAQR4 DotNumerics.LinearAlgebra.CSLapack.DLAQR0._dlaqr4 private
_dlaqr5
DLAQR5 DotNumerics.LinearAlgebra.CSLapack.DLAQR0._dlaqr5 private
NTINY
const int DotNumerics.LinearAlgebra.CSLapack.DLAQR0.NTINY = 11 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQR0.Run().
KEXNW
const int DotNumerics.LinearAlgebra.CSLapack.DLAQR0.KEXNW = 5 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQR0.Run().
KEXSH
const int DotNumerics.LinearAlgebra.CSLapack.DLAQR0.KEXSH = 6 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQR0.Run().
WILK1
const double DotNumerics.LinearAlgebra.CSLapack.DLAQR0.WILK1 = 0.75E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQR0.Run().
WILK2
const double DotNumerics.LinearAlgebra.CSLapack.DLAQR0.WILK2 = - 0.4375E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQR0.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAQR0.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQR0.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAQR0.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQR0.Run().
ZDUM
double [] DotNumerics.LinearAlgebra.CSLapack.DLAQR0.ZDUM = new double[1 * 1] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQR0.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlaqr0.cs