Doc: IGLib EXTENDED: CShellCore.CodeCompletion.Images.CompletionImage Class Reference
CShellCore.CodeCompletion.Images.CompletionImage Class Reference
Provides icons for code-completion.
Public Member Functions
ImageSource GetImage (Accessibility accessibility, bool isStatic=false)
Gets this image combined with the specified accessibility overlay.
override string ToString ()
Static Public Member Functions
static CompletionImage GetCompletionImage (IEntity entity)
Gets the CompletionImage instance for the specified entity. Returns null when no image is available for the entity type.
static CompletionImage GetCompletionImage (IUnresolvedEntity entity)
Gets the CompletionImage instance for the specified entity. Returns null when no image is available for the entity type.
static ImageSource GetImage (IEntity entity)
Gets the image for the specified entity. Returns null when no image is available for the entity type.
static ImageSource GetImage (IUnresolvedEntity entity)
Gets the image for the specified entity. Returns null when no image is available for the entity type.
static ImageSource GetAccessibilityOverlay (Accessibility accessibility)
Gets an overlay image for the specified accessibility. Returns null if no overlay exists (for example, public members don't use overlays).
Properties
static ImageSource NamespaceImage [get]
Gets the image for namespaces.
static CompletionImage Class [get]
Gets the image used for non-static classes.
static CompletionImage Struct [get]
Gets the image used for structs.
static CompletionImage Interface [get]
Gets the image used for interfaces.
static CompletionImage Delegate [get]
Gets the image used for delegates.
static CompletionImage Enum [get]
Gets the image used for enums.
static CompletionImage StaticClass [get]
Gets the image used for modules/static classes.
static CompletionImage Field [get]
Gets the image used for non-static classes.
static CompletionImage ReadOnlyField [get]
Gets the image used for structs.
static CompletionImage Literal [get]
Gets the image used for constants.
static CompletionImage EnumValue [get]
Gets the image used for enum values.
static CompletionImage Method [get]
Gets the image used for methods.
static CompletionImage Constructor [get]
Gets the image used for constructos.
static CompletionImage VirtualMethod [get]
Gets the image used for virtual methods.
static CompletionImage Operator [get]
Gets the image used for operators.
static CompletionImage ExtensionMethod [get]
Gets the image used for extension methods.
static CompletionImage PInvokeMethod [get]
Gets the image used for P/Invoke methods.
static CompletionImage Property [get]
Gets the image used for properties.
static CompletionImage Indexer [get]
Gets the image used for indexers.
static CompletionImage Event [get]
Gets the image used for events.
ImageSource StaticOverlay [get]
Gets the overlay image for the static modifier.
ImageSource BaseImage [get]
Gets the image without any overlays.
Private Member Functions
CompletionImage (string imageName, bool showStaticOverlay)
Static Private Member Functions
static BitmapImage LoadBitmap (string name)
static CompletionImage GetCompletionImageForType (TypeKind typeKind, bool isStatic)
static int GetAccessibilityOverlayIndex (Accessibility accessibility)
Private Attributes
readonly string imageName
readonly bool showStaticOverlay
ImageSource[] images = new ImageSource[2 * AccessibilityOverlaysLength]
Static Private Attributes
static readonly BitmapImage namespaceImage = LoadBitmap("NameSpace")
static readonly CompletionImage imageClass = new CompletionImage("Class", false)
static readonly CompletionImage imageStruct = new CompletionImage("Struct", false)
static readonly CompletionImage imageInterface = new CompletionImage("Interface", false)
static readonly CompletionImage imageDelegate = new CompletionImage("Delegate", false)
static readonly CompletionImage imageEnum = new CompletionImage("Enum", false)
static readonly CompletionImage imageStaticClass = new CompletionImage("StaticClass", false)
static readonly CompletionImage imageField = new CompletionImage("Field", true)
static readonly CompletionImage imageFieldReadOnly = new CompletionImage("FieldReadOnly", true)
static readonly CompletionImage imageLiteral = new CompletionImage("Literal", false)
static readonly CompletionImage imageEnumValue = new CompletionImage("EnumValue", false)
static readonly CompletionImage imageMethod = new CompletionImage("Method", true)
static readonly CompletionImage imageConstructor = new CompletionImage("Constructor", true)
static readonly CompletionImage imageVirtualMethod = new CompletionImage("VirtualMethod", true)
static readonly CompletionImage imageOperator = new CompletionImage("Operator", false)
static readonly CompletionImage imageExtensionMethod = new CompletionImage("ExtensionMethod", true)
static readonly CompletionImage imagePInvokeMethod = new CompletionImage("PInvokeMethod", true)
static readonly CompletionImage imageProperty = new CompletionImage("Property", true)
static readonly CompletionImage imageIndexer = new CompletionImage("Indexer", true)
static readonly CompletionImage imageEvent = new CompletionImage("Event", true)
static readonly BitmapImage overlayStatic = LoadBitmap("OverlayStatic")
const int AccessibilityOverlaysLength = 5
static readonly BitmapImage[] accessibilityOverlays
Detailed Description
Provides icons for code-completion.
Constructor & Destructor Documentation
CompletionImage()
CShellCore.CodeCompletion.Images.CompletionImage.CompletionImage (string imageName, bool showStaticOverlay) inline private
References CShellCore.CodeCompletion.Images.CompletionImage.imageName, and CShellCore.CodeCompletion.Images.CompletionImage.showStaticOverlay.
Member Function Documentation
LoadBitmap()
static BitmapImage CShellCore.CodeCompletion.Images.CompletionImage.LoadBitmap (string name) inline static private
GetCompletionImage() [1/2]
static CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage (IEntity entity) inline static
Gets the CompletionImage instance for the specified entity. Returns null when no image is available for the entity type.
References CShellCore.CodeCompletion.Images.CompletionImage.Constructor, CShellCore.CodeCompletion.Images.CompletionImage.Event, CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImageForType(), CShellCore.CodeCompletion.Images.CompletionImage.imageConstructor, CShellCore.CodeCompletion.Images.CompletionImage.imageEnumValue, CShellCore.CodeCompletion.Images.CompletionImage.imageEvent, CShellCore.CodeCompletion.Images.CompletionImage.imageExtensionMethod, CShellCore.CodeCompletion.Images.CompletionImage.imageField, CShellCore.CodeCompletion.Images.CompletionImage.imageFieldReadOnly, CShellCore.CodeCompletion.Images.CompletionImage.imageIndexer, CShellCore.CodeCompletion.Images.CompletionImage.imageLiteral, CShellCore.CodeCompletion.Images.CompletionImage.imageMethod, CShellCore.CodeCompletion.Images.CompletionImage.imageOperator, CShellCore.CodeCompletion.Images.CompletionImage.imageProperty, CShellCore.CodeCompletion.Images.CompletionImage.imageVirtualMethod, CShellCore.CodeCompletion.Images.CompletionImage.Indexer, CShellCore.CodeCompletion.Images.CompletionImage.Method, CShellCore.CodeCompletion.Images.CompletionImage.Operator, and CShellCore.CodeCompletion.Images.CompletionImage.Property.
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetImage().
GetCompletionImage() [2/2]
static CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage (IUnresolvedEntity entity) inline static
Gets the CompletionImage instance for the specified entity. Returns null when no image is available for the entity type.
References CShellCore.CodeCompletion.Images.CompletionImage.Constructor, CShellCore.CodeCompletion.Images.CompletionImage.Event, CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImageForType(), CShellCore.CodeCompletion.Images.CompletionImage.imageConstructor, CShellCore.CodeCompletion.Images.CompletionImage.imageEnumValue, CShellCore.CodeCompletion.Images.CompletionImage.imageEvent, CShellCore.CodeCompletion.Images.CompletionImage.imageField, CShellCore.CodeCompletion.Images.CompletionImage.imageFieldReadOnly, CShellCore.CodeCompletion.Images.CompletionImage.imageIndexer, CShellCore.CodeCompletion.Images.CompletionImage.imageLiteral, CShellCore.CodeCompletion.Images.CompletionImage.imageMethod, CShellCore.CodeCompletion.Images.CompletionImage.imageOperator, CShellCore.CodeCompletion.Images.CompletionImage.imageProperty, CShellCore.CodeCompletion.Images.CompletionImage.imageVirtualMethod, CShellCore.CodeCompletion.Images.CompletionImage.Indexer, CShellCore.CodeCompletion.Images.CompletionImage.Method, CShellCore.CodeCompletion.Images.CompletionImage.Operator, and CShellCore.CodeCompletion.Images.CompletionImage.Property.
GetCompletionImageForType()
static CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImageForType (TypeKind typeKind, bool isStatic) inline static private
References CShellCore.CodeCompletion.Images.CompletionImage.Class, CShellCore.CodeCompletion.Images.CompletionImage.Delegate, CShellCore.CodeCompletion.Images.CompletionImage.Enum, CShellCore.CodeCompletion.Images.CompletionImage.imageClass, CShellCore.CodeCompletion.Images.CompletionImage.imageDelegate, CShellCore.CodeCompletion.Images.CompletionImage.imageEnum, CShellCore.CodeCompletion.Images.CompletionImage.imageInterface, CShellCore.CodeCompletion.Images.CompletionImage.imageStaticClass, CShellCore.CodeCompletion.Images.CompletionImage.imageStruct, CShellCore.CodeCompletion.Images.CompletionImage.Interface, and CShellCore.CodeCompletion.Images.CompletionImage.Struct.
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage().
GetImage() [1/3]
static ImageSource CShellCore.CodeCompletion.Images.CompletionImage.GetImage (IEntity entity) inline static
Gets the image for the specified entity. Returns null when no image is available for the entity type.
References CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage(), and CShellCore.CodeCompletion.Images.CompletionImage.GetImage().
Referenced by CShellCore.CodeCompletion.DataItems.EntityCompletionData.EntityCompletionData(), and CShellCore.CodeCompletion.Images.CompletionImage.GetImage().
GetImage() [2/3]
static ImageSource CShellCore.CodeCompletion.Images.CompletionImage.GetImage (IUnresolvedEntity entity) inline static
Gets the image for the specified entity. Returns null when no image is available for the entity type.
References CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage(), and CShellCore.CodeCompletion.Images.CompletionImage.GetImage().
GetAccessibilityOverlay()
static ImageSource CShellCore.CodeCompletion.Images.CompletionImage.GetAccessibilityOverlay (Accessibility accessibility) inline static
Gets an overlay image for the specified accessibility. Returns null if no overlay exists (for example, public members don't use overlays).
References CShellCore.CodeCompletion.Images.CompletionImage.accessibilityOverlays, and CShellCore.CodeCompletion.Images.CompletionImage.GetAccessibilityOverlayIndex().
GetAccessibilityOverlayIndex()
static int CShellCore.CodeCompletion.Images.CompletionImage.GetAccessibilityOverlayIndex (Accessibility accessibility) inline static private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetAccessibilityOverlay(), and CShellCore.CodeCompletion.Images.CompletionImage.GetImage().
GetImage() [3/3]
ImageSource CShellCore.CodeCompletion.Images.CompletionImage.GetImage (Accessibility accessibility, bool isStatic = false) inline
Gets this image combined with the specified accessibility overlay.
References CShellCore.CodeCompletion.Images.CompletionImage.accessibilityOverlays, CShellCore.CodeCompletion.Images.CompletionImage.BaseImage, CShellCore.CodeCompletion.Images.CompletionImage.GetAccessibilityOverlayIndex(), CShellCore.CodeCompletion.Images.CompletionImage.images, and CShellCore.CodeCompletion.Images.CompletionImage.showStaticOverlay.
ToString()
override string CShellCore.CodeCompletion.Images.CompletionImage.ToString () inline
References CShellCore.CodeCompletion.Images.CompletionImage.imageName.
Member Data Documentation
namespaceImage
readonly BitmapImage CShellCore.CodeCompletion.Images.CompletionImage.namespaceImage = LoadBitmap("NameSpace") static private
imageClass
readonly CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.imageClass = new CompletionImage("Class", false) static private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImageForType().
imageStruct
readonly CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.imageStruct = new CompletionImage("Struct", false) static private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImageForType().
imageInterface
readonly CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.imageInterface = new CompletionImage("Interface", false) static private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImageForType().
imageDelegate
readonly CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.imageDelegate = new CompletionImage("Delegate", false) static private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImageForType().
imageEnum
readonly CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.imageEnum = new CompletionImage("Enum", false) static private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImageForType().
imageStaticClass
readonly CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.imageStaticClass = new CompletionImage("StaticClass", false) static private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImageForType().
imageField
readonly CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.imageField = new CompletionImage("Field", true) static private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage().
imageFieldReadOnly
readonly CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.imageFieldReadOnly = new CompletionImage("FieldReadOnly", true) static private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage().
imageLiteral
readonly CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.imageLiteral = new CompletionImage("Literal", false) static private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage().
imageEnumValue
readonly CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.imageEnumValue = new CompletionImage("EnumValue", false) static private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage().
imageMethod
readonly CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.imageMethod = new CompletionImage("Method", true) static private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage().
imageConstructor
readonly CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.imageConstructor = new CompletionImage("Constructor", true) static private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage().
imageVirtualMethod
readonly CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.imageVirtualMethod = new CompletionImage("VirtualMethod", true) static private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage().
imageOperator
readonly CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.imageOperator = new CompletionImage("Operator", false) static private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage().
imageExtensionMethod
readonly CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.imageExtensionMethod = new CompletionImage("ExtensionMethod", true) static private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage().
imagePInvokeMethod
readonly CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.imagePInvokeMethod = new CompletionImage("PInvokeMethod", true) static private
imageProperty
readonly CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.imageProperty = new CompletionImage("Property", true) static private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage().
imageIndexer
readonly CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.imageIndexer = new CompletionImage("Indexer", true) static private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage().
imageEvent
readonly CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.imageEvent = new CompletionImage("Event", true) static private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage().
overlayStatic
readonly BitmapImage CShellCore.CodeCompletion.Images.CompletionImage.overlayStatic = LoadBitmap("OverlayStatic") static private
AccessibilityOverlaysLength
const int CShellCore.CodeCompletion.Images.CompletionImage.AccessibilityOverlaysLength = 5 static private
accessibilityOverlays
readonly BitmapImage [] CShellCore.CodeCompletion.Images.CompletionImage.accessibilityOverlays static private
Initial value:
= new BitmapImage[AccessibilityOverlaysLength] {
            null,
            LoadBitmap("OverlayPrivate"),
            LoadBitmap("OverlayProtected"),
            LoadBitmap("OverlayInternal"),
            LoadBitmap("OverlayProtectedInternal")
        }
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetAccessibilityOverlay(), and CShellCore.CodeCompletion.Images.CompletionImage.GetImage().
imageName
readonly string CShellCore.CodeCompletion.Images.CompletionImage.imageName private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.CompletionImage(), and CShellCore.CodeCompletion.Images.CompletionImage.ToString().
showStaticOverlay
readonly bool CShellCore.CodeCompletion.Images.CompletionImage.showStaticOverlay private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.CompletionImage(), and CShellCore.CodeCompletion.Images.CompletionImage.GetImage().
images
ImageSource [] CShellCore.CodeCompletion.Images.CompletionImage.images = new ImageSource[2 * AccessibilityOverlaysLength] private
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetImage().
Property Documentation
NamespaceImage
ImageSource CShellCore.CodeCompletion.Images.CompletionImage.NamespaceImage static get
Gets the image for namespaces.
Referenced by CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateNamespaceCompletionData().
Class
CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.Class static get
Gets the image used for non-static classes.
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImageForType().
Struct
CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.Struct static get
Gets the image used for structs.
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImageForType().
Interface
CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.Interface static get
Gets the image used for interfaces.
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImageForType().
Delegate
CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.Delegate static get
Gets the image used for delegates.
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImageForType().
Enum
CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.Enum static get
Gets the image used for enums.
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImageForType().
StaticClass
CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.StaticClass static get
Gets the image used for modules/static classes.
Field
CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.Field static get
Gets the image used for non-static classes.
ReadOnlyField
CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.ReadOnlyField static get
Gets the image used for structs.
Literal
CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.Literal static get
Gets the image used for constants.
Referenced by CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateLiteralCompletionData().
EnumValue
CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.EnumValue static get
Gets the image used for enum values.
Method
CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.Method static get
Gets the image used for methods.
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage().
Constructor
CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.Constructor static get
Gets the image used for constructos.
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage().
VirtualMethod
CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.VirtualMethod static get
Gets the image used for virtual methods.
Operator
CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.Operator static get
Gets the image used for operators.
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage().
ExtensionMethod
CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.ExtensionMethod static get
Gets the image used for extension methods.
PInvokeMethod
CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.PInvokeMethod static get
Gets the image used for P/Invoke methods.
Property
CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.Property static get
Gets the image used for properties.
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage().
Indexer
CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.Indexer static get
Gets the image used for indexers.
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage().
Event
CompletionImage CShellCore.CodeCompletion.Images.CompletionImage.Event static get
Gets the image used for events.
Referenced by CShellCore.CodeCompletion.Images.CompletionImage.GetCompletionImage().
StaticOverlay
ImageSource CShellCore.CodeCompletion.Images.CompletionImage.StaticOverlay get
Gets the overlay image for the static modifier.
BaseImage
ImageSource CShellCore.CodeCompletion.Images.CompletionImage.BaseImage get
Gets the image without any overlays.
Referenced by CShellCore.CodeCompletion.CSharpCompletionDataFactory.CreateLiteralCompletionData(), and CShellCore.CodeCompletion.Images.CompletionImage.GetImage().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore.CodeCompletion/Images/CompletionImage.cs