Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGESVD Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGESVD Class Reference
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGESVD (DBDSQR dbdsqr, DGEBRD dgebrd, DGELQF dgelqf, DGEMM dgemm, DGEQRF dgeqrf, DLACPY dlacpy, DLASCL dlascl, DLASET dlaset, DORGBR dorgbr, DORGLQ dorglq, DORGQR dorgqr, DORMBR dormbr, XERBLA xerbla, LSAME lsame, ILAENV ilaenv, DLAMCH dlamch, DLANGE dlange)
DGESVD ()
void Run (string JOBU, string JOBVT, int M, int N, ref double[] A, int offset_a, int LDA, ref double[] S, int offset_s, ref double[] U, int offset_u, int LDU, ref double[] VT, int offset_vt, int LDVT, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
DBDSQR _dbdsqr
DGEBRD _dgebrd
DGELQF _dgelqf
DGEMM _dgemm
DGEQRF _dgeqrf
DLACPY _dlacpy
DLASCL _dlascl
DLASET _dlaset
DORGBR _dorgbr
DORGLQ _dorglq
DORGQR _dorgqr
DORMBR _dormbr
XERBLA _xerbla
LSAME _lsame
ILAENV _ilaenv
DLAMCH _dlamch
DLANGE _dlange
double[] DUM = new double[1]
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
Detailed Description
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGESVD computes the singular value decomposition (SVD) of a real M-by-N matrix A, optionally computing the left and/or right singular vectors. The SVD is written
A = U * SIGMA * transpose(V)
where SIGMA is an M-by-N matrix which is zero except for its min(m,n) diagonal elements, U is an M-by-M orthogonal matrix, and V is an N-by-N orthogonal matrix. The diagonal elements of SIGMA are the singular values of A; they are real and non-negative, and are returned in descending order. The first min(m,n) columns of U and V are the left and right singular vectors of A.
Note that the routine returns V**T, not V.
/summary>
Constructor & Destructor Documentation
DGESVD() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGESVD.DGESVD (DBDSQR dbdsqr, DGEBRD dgebrd, DGELQF dgelqf, DGEMM dgemm, DGEQRF dgeqrf, DLACPY dlacpy, DLASCL dlascl, DLASET dlaset, DORGBR dorgbr, DORGLQ dorglq, DORGQR dorgqr, DORMBR dormbr, XERBLA xerbla, LSAME lsame, ILAENV ilaenv, DLAMCH dlamch, DLANGE dlange) inline
DGESVD() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGESVD.DGESVD () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run (string JOBU, string JOBVT, int M, int N, ref double[] A, int offset_a, int LDA, ref double[] S, int offset_s, ref double[] U, int offset_u, int LDU, ref double[] VT, int offset_vt, int LDVT, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DGESVD computes the singular value decomposition (SVD) of a real M-by-N matrix A, optionally computing the left and/or right singular vectors. The SVD is written
A = U * SIGMA * transpose(V)
where SIGMA is an M-by-N matrix which is zero except for its min(m,n) diagonal elements, U is an M-by-M orthogonal matrix, and V is an N-by-N orthogonal matrix. The diagonal elements of SIGMA are the singular values of A; they are real and non-negative, and are returned in descending order. The first min(m,n) columns of U and V are the left and right singular vectors of A.
Note that the routine returns V**T, not V.
/summary>
Parameters
JOBU (input) CHARACTER*1 Specifies options for computing all or part of the matrix U: = 'A': all M columns of U are returned in array U: = 'S': the first min(m,n) columns of U (the left singular vectors) are returned in the array U; = 'O': the first min(m,n) columns of U (the left singular vectors) are overwritten on the array A; = 'N': no columns of U (no left singular vectors) are computed. /param>
Parameters
JOBVT (input) CHARACTER*1 Specifies options for computing all or part of the matrix V**T: = 'A': all N rows of V**T are returned in the array VT; = 'S': the first min(m,n) rows of V**T (the right singular vectors) are returned in the array VT; = 'O': the first min(m,n) rows of V**T (the right singular vectors) are overwritten on the array A; = 'N': no rows of V**T (no right singular vectors) are computed.
JOBVT and JOBU cannot both be 'O'. /param>
Parameters
M (input) INTEGER The number of rows of the input matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the input matrix A. N .GE. 0. /param>
Parameters
A = U * SIGMA * transpose(V) /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
S (output) DOUBLE PRECISION array, dimension (min(M,N)) The singular values of A, sorted so that S(i) .GE. S(i+1). /param>
Parameters
U (output) DOUBLE PRECISION array, dimension (LDU,UCOL) (LDU,M) if JOBU = 'A' or (LDU,min(M,N)) if JOBU = 'S'. If JOBU = 'A', U contains the M-by-M orthogonal matrix U; if JOBU = 'S', U contains the first min(m,n) columns of U (the left singular vectors, stored columnwise); if JOBU = 'N' or 'O', U is not referenced. /param>
Parameters
LDU (input) INTEGER The leading dimension of the array U. LDU .GE. 1; if JOBU = 'S' or 'A', LDU .GE. M. /param>
Parameters
VT (output) DOUBLE PRECISION array, dimension (LDVT,N) If JOBVT = 'A', VT contains the N-by-N orthogonal matrix V**T; if JOBVT = 'S', VT contains the first min(m,n) rows of V**T (the right singular vectors, stored rowwise); if JOBVT = 'N' or 'O', VT is not referenced. /param>
Parameters
LDVT (input) INTEGER The leading dimension of the array VT. LDVT .GE. 1; if JOBVT = 'A', LDVT .GE. N; if JOBVT = 'S', LDVT .GE. min(M,N). /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK; if INFO .GT. 0, WORK(2:MIN(M,N)) contains the unconverged superdiagonal elements of an upper bidiagonal matrix B whose diagonal is in S (not necessarily sorted). B satisfies A = U * B * VT, so it has the same singular values as A, and singular vectors related by U and VT. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. MAX(1,3*MIN(M,N)+MAX(M,N),5*MIN(M,N)). For good performance, LWORK should generally be larger.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. .GT. 0: if DBDSQR did not converge, INFO specifies how many superdiagonals of an intermediate bidiagonal form B did not converge to zero. See the description of WORK above for details. /param>
References DotNumerics.LinearAlgebra.CSLapack.DGESVD.DUM, DotNumerics.LinearAlgebra.CSLapack.DGESVD.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASET.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELQF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANGE.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGLQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGQR.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGBR.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMBR.Run(), DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGESVD.ZERO.
Member Data Documentation
_dbdsqr
DBDSQR DotNumerics.LinearAlgebra.CSLapack.DGESVD._dbdsqr private
_dgebrd
DGEBRD DotNumerics.LinearAlgebra.CSLapack.DGESVD._dgebrd private
_dgelqf
DGELQF DotNumerics.LinearAlgebra.CSLapack.DGESVD._dgelqf private
_dgemm
DGEMM DotNumerics.LinearAlgebra.CSLapack.DGESVD._dgemm private
_dgeqrf
DGEQRF DotNumerics.LinearAlgebra.CSLapack.DGESVD._dgeqrf private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DGESVD._dlacpy private
_dlascl
DLASCL DotNumerics.LinearAlgebra.CSLapack.DGESVD._dlascl private
_dlaset
DLASET DotNumerics.LinearAlgebra.CSLapack.DGESVD._dlaset private
_dorgbr
DORGBR DotNumerics.LinearAlgebra.CSLapack.DGESVD._dorgbr private
_dorglq
DORGLQ DotNumerics.LinearAlgebra.CSLapack.DGESVD._dorglq private
_dorgqr
DORGQR DotNumerics.LinearAlgebra.CSLapack.DGESVD._dorgqr private
_dormbr
DORMBR DotNumerics.LinearAlgebra.CSLapack.DGESVD._dormbr private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGESVD._xerbla private
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DGESVD._lsame private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DGESVD._ilaenv private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DGESVD._dlamch private
_dlange
DLANGE DotNumerics.LinearAlgebra.CSLapack.DGESVD._dlange private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DGESVD.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGESVD.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run().
DUM
double [] DotNumerics.LinearAlgebra.CSLapack.DGESVD.DUM = new double[1] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgesvd.cs