Doc: IGLib EXTENDED: NUnit.Engine.Services.Tests.DomainManagerStaticTests Class Reference
NUnit.Engine.Services.Tests.DomainManagerStaticTests Class Reference
Static Public Member Functions
static void GetPrivateBinPath ()
static void GetCommonAppBase_OneElement ()
static void GetCommonAppBase_TwoElements_SameDirectory ()
static void GetCommonAppBase_TwoElements_DifferentDirectories ()
static void GetCommonAppBase_ThreeElements_DifferentDirectories ()
static void ProperConfigFileIsUsed ()
static void CanReadConfigFile ()
static void ApplicationBaseTests (string filePath, string appBase, string expected)
static void PrivateBinPathTests (string filePath, string appBase, string expected)
static void ConfigFileTests (string filePath, string appBase, string configSetting, string expected)
Static Private Member Functions
static string TestPath (string path)
Take a valid Linux filePath and make a valid windows filePath out of it if we are on Windows. Change slashes to backslashes and, if the filePath starts with a slash, add C: in front of it.
static IEnumerable< TestCaseData > AppDomainData ()
Static Private Attributes
static string path1 = TestPath("/test/bin/debug/test1.dll")
static string path2 = TestPath("/test/bin/debug/test2.dll")
static string path3 = TestPath("/test/utils/test3.dll")
Member Function Documentation
GetPrivateBinPath()
static void NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetPrivateBinPath () inline static
References NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Services.DomainManager.GetPrivateBinPath(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.path1, NUnit.Engine.Services.Tests.DomainManagerStaticTests.path2, NUnit.Engine.Services.Tests.DomainManagerStaticTests.path3, and NUnit.Engine.Services.Tests.DomainManagerStaticTests.TestPath().
GetCommonAppBase_OneElement()
static void NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_OneElement () inline static
References NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Services.DomainManager.GetCommonAppBase(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.path1, and NUnit.Engine.Services.Tests.DomainManagerStaticTests.TestPath().
GetCommonAppBase_TwoElements_SameDirectory()
static void NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_TwoElements_SameDirectory () inline static
References NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Services.DomainManager.GetCommonAppBase(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.path1, NUnit.Engine.Services.Tests.DomainManagerStaticTests.path2, and NUnit.Engine.Services.Tests.DomainManagerStaticTests.TestPath().
GetCommonAppBase_TwoElements_DifferentDirectories()
static void NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_TwoElements_DifferentDirectories () inline static
References NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Services.DomainManager.GetCommonAppBase(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.path1, NUnit.Engine.Services.Tests.DomainManagerStaticTests.path3, and NUnit.Engine.Services.Tests.DomainManagerStaticTests.TestPath().
GetCommonAppBase_ThreeElements_DifferentDirectories()
static void NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_ThreeElements_DifferentDirectories () inline static
References NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Services.DomainManager.GetCommonAppBase(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.path1, NUnit.Engine.Services.Tests.DomainManagerStaticTests.path2, NUnit.Engine.Services.Tests.DomainManagerStaticTests.path3, and NUnit.Engine.Services.Tests.DomainManagerStaticTests.TestPath().
ProperConfigFileIsUsed()
static void NUnit.Engine.Services.Tests.DomainManagerStaticTests.ProperConfigFileIsUsed () inline static
References NUnit.Framework.TestContext.CurrentContext, NUnit.Framework.Is.EqualTo(), NUnit.Framework.TestContext.TestDirectory, and NUnit.Framework.Assert.That().
CanReadConfigFile()
static void NUnit.Engine.Services.Tests.DomainManagerStaticTests.CanReadConfigFile () inline static
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
ApplicationBaseTests()
static void NUnit.Engine.Services.Tests.DomainManagerStaticTests.ApplicationBaseTests (string filePath, string appBase, string expected) inline static
References NUnit.Engine.Services.DomainManager.GetApplicationBase(), NUnit.Framework.Is.SamePath(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.TestPath(), and NUnit.Framework.Assert.That().
PrivateBinPathTests()
static void NUnit.Engine.Services.Tests.DomainManagerStaticTests.PrivateBinPathTests (string filePath, string appBase, string expected) inline static
References NUnit.Framework.Is.EqualTo(), NUnit.Engine.Services.DomainManager.GetPrivateBinPath(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.TestPath(), and NUnit.Framework.Assert.That().
ConfigFileTests()
static void NUnit.Engine.Services.Tests.DomainManagerStaticTests.ConfigFileTests (string filePath, string appBase, string configSetting, string expected) inline static
References NUnit.Framework.Is.EqualTo(), NUnit.Engine.Services.DomainManager.GetConfigFile(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.TestPath(), and NUnit.Framework.Assert.That().
TestPath()
static string NUnit.Engine.Services.Tests.DomainManagerStaticTests.TestPath (string path) inline static private
Take a valid Linux filePath and make a valid windows filePath out of it if we are on Windows. Change slashes to backslashes and, if the filePath starts with a slash, add C: in front of it.
Referenced by NUnit.Engine.Services.Tests.DomainManagerStaticTests.ApplicationBaseTests(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.ConfigFileTests(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_OneElement(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_ThreeElements_DifferentDirectories(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_TwoElements_DifferentDirectories(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_TwoElements_SameDirectory(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetPrivateBinPath(), and NUnit.Engine.Services.Tests.DomainManagerStaticTests.PrivateBinPathTests().
AppDomainData()
static IEnumerable<TestCaseData> NUnit.Engine.Services.Tests.DomainManagerStaticTests.AppDomainData () inline static private
Member Data Documentation
path1
string NUnit.Engine.Services.Tests.DomainManagerStaticTests.path1 = TestPath("/test/bin/debug/test1.dll") static private
Referenced by NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_OneElement(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_ThreeElements_DifferentDirectories(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_TwoElements_DifferentDirectories(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_TwoElements_SameDirectory(), and NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetPrivateBinPath().
path2
string NUnit.Engine.Services.Tests.DomainManagerStaticTests.path2 = TestPath("/test/bin/debug/test2.dll") static private
Referenced by NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_ThreeElements_DifferentDirectories(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_TwoElements_SameDirectory(), and NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetPrivateBinPath().
path3
string NUnit.Engine.Services.Tests.DomainManagerStaticTests.path3 = TestPath("/test/utils/test3.dll") static private
Referenced by NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_ThreeElements_DifferentDirectories(), NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetCommonAppBase_TwoElements_DifferentDirectories(), and NUnit.Engine.Services.Tests.DomainManagerStaticTests.GetPrivateBinPath().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Services/DomainManagerStaticTests.cs