Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLACPY Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLACPY Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLACPY (LSAME lsame)
DLACPY ()
void Run (string UPLO, int M, int N, double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB)
Private Attributes
LSAME _lsame
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLACPY copies all or part of a two-dimensional matrix A to another matrix B.
/summary>
Constructor & Destructor Documentation
DLACPY() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLACPY.DLACPY (LSAME lsame) inline
DLACPY() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLACPY.DLACPY () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run (string UPLO, int M, int N, double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB) inline
Purpose
DLACPY copies all or part of a two-dimensional matrix A to another matrix B.
/summary>
Parameters
UPLO (input) CHARACTER*1 Specifies the part of the matrix A to be copied to B. = 'U': Upper triangular part = 'L': Lower triangular part Otherwise: All of the matrix A /param>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. 0. /param>
Parameters
A (input) DOUBLE PRECISION array, dimension (LDA,N) The m by n matrix A. If UPLO = 'U', only the upper triangle or trapezoid is accessed; if UPLO = 'L', only the lower triangle or trapezoid is accessed. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
B (output) DOUBLE PRECISION array, dimension (LDB,N) On exit, B = A in the locations specified by UPLO. /param>
Parameters
LDB (input) INTEGER The leading dimension of the array B. LDB .GE. max(1,M). /param>
References DotNumerics.LinearAlgebra.CSLapack.LSAME.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAHR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAEXC.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED3.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED0.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR5.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD3.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED8.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALSD.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEDC.Run(), DotNumerics.LinearAlgebra.CSLapack.DSBEVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD2.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYEVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGSVP.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR3.Run(), DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALS0.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR4.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR0.Run(), DotNumerics.LinearAlgebra.CSLapack.DHSEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELSD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLACPY._lsame private
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlacpy.cs