Doc: IGLib EXTENDED: alglib.bdss.cvreport Class Reference
alglib.bdss.cvreport Class Reference
Public Member Functions
cvreport ()
override void init ()
override alglib.apobject make_copy ()
Public Attributes
double relclserror
double avgce
double rmserror
double avgerror
double avgrelerror
Constructor & Destructor Documentation
cvreport()
alglib.bdss.cvreport.cvreport () inline
References alglib.bdss.cvreport.init().
Referenced by alglib.bdss.cvreport.make_copy().
Member Function Documentation
init()
override void alglib.bdss.cvreport.init () inline
Referenced by alglib.bdss.cvreport.cvreport().
make_copy()
override alglib.apobject alglib.bdss.cvreport.make_copy () inline
References alglib.bdss.cvreport.avgce, alglib.bdss.cvreport.avgerror, alglib.bdss.cvreport.avgrelerror, alglib.bdss.cvreport.cvreport(), alglib.bdss.cvreport.relclserror, and alglib.bdss.cvreport.rmserror.
Member Data Documentation
relclserror
double alglib.bdss.cvreport.relclserror
Referenced by alglib.bdss.cvreport.make_copy().
avgce
double alglib.bdss.cvreport.avgce
Referenced by alglib.bdss.cvreport.make_copy().
rmserror
double alglib.bdss.cvreport.rmserror
Referenced by alglib.bdss.cvreport.make_copy().
avgerror
double alglib.bdss.cvreport.avgerror
Referenced by alglib.bdss.cvreport.make_copy().
avgrelerror
double alglib.bdss.cvreport.avgrelerror
Referenced by alglib.bdss.cvreport.make_copy().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/dataanalysis.cs