Doc: IGLib EXTENDED: alglib.testtrfacunit Class Reference
alglib.testtrfacunit Class Reference
Static Public Member Functions
static bool testtrfac (bool silent)
static bool testtrfac (bool silent)
static bool _pexec_testtrfac (bool silent)
Static Private Member Functions
static void testcluproblem (complex[,] a, int m, int n, double threshold, ref bool err, ref bool properr)
static void testrluproblem (double[,] a, int m, int n, double threshold, ref bool err, ref bool properr)
static void testcluproblem (complex[,] a, int m, int n, double threshold, ref bool err, ref bool properr)
static void testrluproblem (double[,] a, int m, int n, double threshold, ref bool err, ref bool properr)
Member Function Documentation
testtrfac() [1/2]
static bool alglib.testtrfacunit.testtrfac (bool silent) inline static
References alglib.ablas.ablasblocksize(), alglib.math.abscomplex(), alglib.matgen.cmatrixrndorthogonalfromtheleft(), alglib.matgen.cmatrixrndorthogonalfromtheright(), alglib.math.conj(), alglib.trfac.hpdmatrixcholesky(), alglib.matgen.hpdmatrixrndcond(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.matgen.rmatrixrndorthogonalfromtheleft(), alglib.matgen.rmatrixrndorthogonalfromtheright(), alglib.trfac.spdmatrixcholesky(), alglib.matgen.spdmatrixrndcond(), alglib.testtrfacunit.testcluproblem(), and alglib.testtrfacunit.testrluproblem().
Referenced by alglib.testtrfacunit._pexec_testtrfac(), and _Test.Main().
testcluproblem() [1/2]
static void alglib.testtrfacunit.testcluproblem (complex a[,], int m, int n, double threshold, ref bool err, ref bool properr) inline static private
References alglib.math.abscomplex(), alglib.trfac.cmatrixlup(), and alglib.trfac.cmatrixplu().
Referenced by alglib.testtrfacunit.testtrfac().
testrluproblem() [1/2]
static void alglib.testtrfacunit.testrluproblem (double a[,], int m, int n, double threshold, ref bool err, ref bool properr) inline static private
References alglib.trfac.rmatrixlup(), and alglib.trfac.rmatrixplu().
Referenced by alglib.testtrfacunit.testtrfac().
testtrfac() [2/2]
static bool alglib.testtrfacunit.testtrfac (bool silent) inline static
References alglib.ablas.ablasblocksize(), alglib.math.abscomplex(), alglib.matgen.cmatrixrndorthogonalfromtheleft(), alglib.matgen.cmatrixrndorthogonalfromtheright(), alglib.math.conj(), alglib.trfac.hpdmatrixcholesky(), alglib.matgen.hpdmatrixrndcond(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.matgen.rmatrixrndorthogonalfromtheleft(), alglib.matgen.rmatrixrndorthogonalfromtheright(), alglib.trfac.spdmatrixcholesky(), alglib.matgen.spdmatrixrndcond(), alglib.testtrfacunit.testcluproblem(), and alglib.testtrfacunit.testrluproblem().
_pexec_testtrfac()
static bool alglib.testtrfacunit._pexec_testtrfac (bool silent) inline static
References alglib.testtrfacunit.testtrfac().
Referenced by _Test.Main().
testcluproblem() [2/2]
static void alglib.testtrfacunit.testcluproblem (complex a[,], int m, int n, double threshold, ref bool err, ref bool properr) inline static private
References alglib.math.abscomplex(), alglib.trfac.cmatrixlup(), and alglib.trfac.cmatrixplu().
testrluproblem() [2/2]
static void alglib.testtrfacunit.testrluproblem (double a[,], int m, int n, double threshold, ref bool err, ref bool properr) inline static private
References alglib.trfac.rmatrixlup(), and alglib.trfac.rmatrixplu().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs