Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAED0 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAED0 Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAED0 (DCOPY dcopy, DGEMM dgemm, DLACPY dlacpy, DLAED1 dlaed1, DLAED7 dlaed7, DSTEQR dsteqr, XERBLA xerbla, ILAENV ilaenv)
DLAED0 ()
void Run (int ICOMPQ, int QSIZ, int N, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] Q, int offset_q, int LDQ, ref double[] QSTORE, int offset_qstore, int LDQS, ref double[] WORK, int offset_work, ref int[] IWORK, int offset_iwork, ref int INFO)
Private Attributes
DCOPY _dcopy
DGEMM _dgemm
DLACPY _dlacpy
DLAED1 _dlaed1
DLAED7 _dlaed7
DSTEQR _dsteqr
XERBLA _xerbla
ILAENV _ilaenv
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
const double TWO = 2.0E0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAED0 computes all eigenvalues and corresponding eigenvectors of a symmetric tridiagonal matrix using the divide and conquer method.
/summary>
Constructor & Destructor Documentation
DLAED0() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAED0.DLAED0 (DCOPY dcopy, DGEMM dgemm, DLACPY dlacpy, DLAED1 dlaed1, DLAED7 dlaed7, DSTEQR dsteqr, XERBLA xerbla, ILAENV ilaenv) inline
DLAED0() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAED0.DLAED0 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAED0.Run (int ICOMPQ, int QSIZ, int N, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] Q, int offset_q, int LDQ, ref double[] QSTORE, int offset_qstore, int LDQS, ref double[] WORK, int offset_work, ref int[] IWORK, int offset_iwork, ref int INFO) inline
Purpose
DLAED0 computes all eigenvalues and corresponding eigenvectors of a symmetric tridiagonal matrix using the divide and conquer method.
/summary>
Parameters
ICOMPQ (input) INTEGER = 0: Compute eigenvalues only. = 1: Compute eigenvectors of original dense symmetric matrix also. On entry, Q contains the orthogonal matrix used to reduce the original matrix to tridiagonal form. = 2: Compute eigenvalues and eigenvectors of tridiagonal matrix. /param>
Parameters
QSIZ (input) INTEGER The dimension of the orthogonal matrix used to reduce the full matrix to tridiagonal form. QSIZ .GE. N if ICOMPQ = 1. /param>
Parameters
N (input) INTEGER The dimension of the symmetric tridiagonal matrix. N .GE. 0. /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension (N) On entry, the main diagonal of the tridiagonal matrix. On exit, its eigenvalues. /param>
Parameters
E (input) DOUBLE PRECISION array, dimension (N-1) The off-diagonal elements of the tridiagonal matrix. On exit, E has been destroyed. /param>
Parameters
Q (input/output) DOUBLE PRECISION array, dimension (LDQ, N) On entry, Q must contain an N-by-N orthogonal matrix. If ICOMPQ = 0 Q is not referenced. If ICOMPQ = 1 On entry, Q is a subset of the columns of the orthogonal matrix used to reduce the full matrix to tridiagonal form corresponding to the subset of the full matrix which is being decomposed at this time. If ICOMPQ = 2 On entry, Q will be the identity matrix. On exit, Q contains the eigenvectors of the tridiagonal matrix. /param>
Parameters
LDQ (input) INTEGER The leading dimension of the array Q. If eigenvectors are desired, then LDQ .GE. max(1,N). In any case, LDQ .GE. 1. /param>
Parameters
QSTORE (workspace) DOUBLE PRECISION array, dimension (LDQS, N) Referenced only when ICOMPQ = 1. Used to store parts of the eigenvector matrix when the updating matrix multiplies take place. /param>
Parameters
LDQS (input) INTEGER The leading dimension of the array QSTORE. If ICOMPQ = 1, then LDQS .GE. max(1,N). In any case, LDQS .GE. 1. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, If ICOMPQ = 0 or 1, the dimension of WORK must be at least 1 + 3*N + 2*N*lg N + 2*N**2 (lg(N) = smallest integer k such that 2^k .GE. N) If ICOMPQ = 2, the dimension of WORK must be at least 4*N + N**2. /param>
Parameters
IWORK (workspace) INTEGER array, If ICOMPQ = 0 or 1, the dimension of IWORK must be at least 6 + 6*N + 5*N*lg N. (lg(N) = smallest integer k such that 2^k .GE. N) If ICOMPQ = 2, the dimension of IWORK must be at least 3 + 5*N. /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. .GT. 0: The algorithm failed to compute an eigenvalue while working on the submatrix lying in rows and columns INFO/(N+1) through mod(INFO,N+1). /param>
References DotNumerics.LinearAlgebra.CSLapack.DLAED0.ONE, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED1.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED7.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED0.TWO, and DotNumerics.LinearAlgebra.CSLapack.DLAED0.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTEDC.Run().
Member Data Documentation
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLAED0._dcopy private
_dgemm
DGEMM DotNumerics.LinearAlgebra.CSLapack.DLAED0._dgemm private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DLAED0._dlacpy private
_dlaed1
DLAED1 DotNumerics.LinearAlgebra.CSLapack.DLAED0._dlaed1 private
_dlaed7
DLAED7 DotNumerics.LinearAlgebra.CSLapack.DLAED0._dlaed7 private
_dsteqr
DSTEQR DotNumerics.LinearAlgebra.CSLapack.DLAED0._dsteqr private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLAED0._xerbla private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DLAED0._ilaenv private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAED0.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED0.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAED0.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED0.Run().
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DLAED0.TWO = 2.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAED0.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlaed0.cs