Doc: IGLib EXTENDED: IG.Num.IAnalysis Interface Reference
IG.Num.IAnalysis Interface Reference
Interface for direct analysis classes used in optimization problems.
Public Member Functions
void Analyse (IAnalysisResults analysisData)
Performs analysis - calculates requested results and writes them to the provided data structure.
Properties
int NumParameters [get, set]
Number of parameters.
int NumObjectives [get, set]
Number of objective functions (normally 1 for this type, but can be 0).
int NumConstraints [get, set]
Number of constraints.
int NumEqualityConstraints [get, set]
Number of equality constraints.
Detailed Description
Interface for direct analysis classes used in optimization problems.
$A Igor May08 Jun10;
Member Function Documentation
Analyse()
void IG.Num.IAnalysis.Analyse (IAnalysisResults analysisData)
Performs analysis - calculates requested results and writes them to the provided data structure.
Parameters
analysisData Data structure where analysis request parameters are obtained and where analysis results are written.
Implemented in IG.Lib.LoadableScriptOptBase.AnalysisScript, IG.Num.OptConstrained.Example2dTestSimple, IG.Num.OptConstrained.Example2dTest, IG.Num.OptConstrained.Example2dTest1, IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent, IG.Neural.AnalysisFileServerNeural, IG.Num.AnalysisBase, and IG.Num.OptUnconstrained.ExampleRosenbrock.
Referenced by IG.Num.ResponseEvaluatorWithStorageAnalysis.EvaluateResponseThis(), IG.NumExperimental.ResponseEvaluatorWithStorageAnalysis.EvaluateResponseThis(), IG.Num.OptFileManager.ServerAnalyse(), IG.Script.LoadableScriptShellNeuralITOriginalBase.TestAnalysis(), and IG.Script.LoadableScriptShellNeuralBase.TestAnalysis().
Property Documentation
NumParameters
int IG.Num.IAnalysis.NumParameters get set
Number of parameters.
Referenced by IG.Num.OptUnconstrained.ExampleRosenbrockGeneralizedAdjacent.Analyse().
NumObjectives
int IG.Num.IAnalysis.NumObjectives get set
Number of objective functions (normally 1 for this type, but can be 0).
NumConstraints
int IG.Num.IAnalysis.NumConstraints get set
Number of constraints.
NumEqualityConstraints
int IG.Num.IAnalysis.NumEqualityConstraints get set
Number of equality constraints.
The documentation for this interface was generated from the following file:
iglib/igbase/optimization/Analysis.cs