Doc: IGLib EXTENDED: NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame Class Reference
NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame Class Reference
Public Member Functions
void PositiveEqualityTest (DateTimeOffset value1, DateTimeOffset value2)
void NegativeEqualityTest (DateTimeOffset value1, DateTimeOffset value2)
void PositiveEqualityTestWithTolerance (DateTimeOffset value1, DateTimeOffset value2)
void NegativeEqualityTestWithTolerance (DateTimeOffset value1, DateTimeOffset value2)
void NegativeEqualityTestWithToleranceAndWithSameOffset (DateTimeOffset value1, DateTimeOffset value2)
void PositiveEqualityTestWithToleranceAndWithSameOffset (DateTimeOffset value1, DateTimeOffset value2)
void NegativeEqualityTestWithinToleranceAndWithSameOffset (DateTimeOffset value1, DateTimeOffset value2)
Static Public Attributes
static readonly DateTimeOffset[] sameDateTimeOffsets
Member Function Documentation
PositiveEqualityTest()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.PositiveEqualityTest (DateTimeOffset value1, DateTimeOffset value2) inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
NegativeEqualityTest()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.NegativeEqualityTest (DateTimeOffset value1, DateTimeOffset value2) inline
References NUnit.Framework.Is.Not, NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
PositiveEqualityTestWithTolerance()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.PositiveEqualityTestWithTolerance (DateTimeOffset value1, DateTimeOffset value2) inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
NegativeEqualityTestWithTolerance()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.NegativeEqualityTestWithTolerance (DateTimeOffset value1, DateTimeOffset value2) inline
References NUnit.Framework.Is.Not, NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
NegativeEqualityTestWithToleranceAndWithSameOffset()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.NegativeEqualityTestWithToleranceAndWithSameOffset (DateTimeOffset value1, DateTimeOffset value2) inline
References NUnit.Framework.Is.Not, NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
PositiveEqualityTestWithToleranceAndWithSameOffset()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.PositiveEqualityTestWithToleranceAndWithSameOffset (DateTimeOffset value1, DateTimeOffset value2) inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
NegativeEqualityTestWithinToleranceAndWithSameOffset()
void NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.NegativeEqualityTestWithinToleranceAndWithSameOffset (DateTimeOffset value1, DateTimeOffset value2) inline
References NUnit.Framework.Is.Not, NUnit.Framework.Assert.That(), and NUnit.Framework.Assume.That().
Member Data Documentation
sameDateTimeOffsets
readonly DateTimeOffset [] NUnit.Framework.Constraints.EqualConstraintTests.DateTimeOffsetShouldBeSame.sameDateTimeOffsets static
Initial value:
=
                {
                    new DateTimeOffset(new DateTime(2014, 1, 30, 12, 34, 56), new TimeSpan(6, 15, 0)),
                    new DateTimeOffset(new DateTime(2014, 1, 30, 9, 19, 56), new TimeSpan(3, 0, 0)),
                    new DateTimeOffset(new DateTime(2014, 1, 30, 9, 19, 56), new TimeSpan(3, 1, 0)),
                    new DateTimeOffset(new DateTime(2014, 1, 30, 9, 19, 55), new TimeSpan(3, 0, 0)),
                    new DateTimeOffset(new DateTime(2014, 1, 30, 9, 19, 55), new TimeSpan(3, 50, 0))
                }
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/EqualConstraintTests.cs