Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAPLL Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAPLL Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAPLL (DDOT ddot, DAXPY daxpy, DLARFG dlarfg, DLAS2 dlas2)
DLAPLL ()
void Run (int N, ref double[] X, int offset_x, int INCX, ref double[] Y, int offset_y, int INCY, ref double SSMIN)
Private Attributes
DDOT _ddot
DAXPY _daxpy
DLARFG _dlarfg
DLAS2 _dlas2
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
Given two column vectors X and Y, let
A = (X Y).
The subroutine first computes the QR factorization of A = Q*R, and then computes the SVD of the 2-by-2 upper triangular matrix R. The smaller singular value of R is returned in SSMIN, which is used as the measurement of the linear dependency of the vectors X and Y.
/summary>
Constructor & Destructor Documentation
DLAPLL() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAPLL.DLAPLL (DDOT ddot, DAXPY daxpy, DLARFG dlarfg, DLAS2 dlas2) inline
DLAPLL() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAPLL.DLAPLL () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAPLL.Run (int N, ref double[] X, int offset_x, int INCX, ref double[] Y, int offset_y, int INCY, ref double SSMIN) inline
Purpose
Given two column vectors X and Y, let
A = (X Y).
The subroutine first computes the QR factorization of A = Q*R, and then computes the SVD of the 2-by-2 upper triangular matrix R. The smaller singular value of R is returned in SSMIN, which is used as the measurement of the linear dependency of the vectors X and Y.
/summary>
Parameters
N (input) INTEGER The length of the vectors X and Y. /param>
Parameters
X (input/output) DOUBLE PRECISION array, dimension (1+(N-1)*INCX) On entry, X contains the N-vector X. On exit, X is overwritten. /param>
Parameters
INCX (input) INTEGER The increment between successive elements of X. INCX .GT. 0. /param>
Parameters
Y (input/output) DOUBLE PRECISION array, dimension (1+(N-1)*INCY) On entry, Y contains the N-vector Y. On exit, Y is overwritten. /param>
Parameters
INCY (input) INTEGER The increment between successive elements of Y. INCY .GT. 0. /param>
Parameters
SSMIN (output) DOUBLE PRECISION The smallest singular value of the N-by-2 matrix A = (X Y). /param>
References DotNumerics.LinearAlgebra.CSLapack.DLAPLL.ONE, DotNumerics.LinearAlgebra.CSLapack.DDOT.Run(), DotNumerics.LinearAlgebra.CSLapack.DAXPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAS2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAPLL.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTGSJA.Run().
Member Data Documentation
_ddot
DDOT DotNumerics.LinearAlgebra.CSLapack.DLAPLL._ddot private
_daxpy
DAXPY DotNumerics.LinearAlgebra.CSLapack.DLAPLL._daxpy private
_dlarfg
DLARFG DotNumerics.LinearAlgebra.CSLapack.DLAPLL._dlarfg private
_dlas2
DLAS2 DotNumerics.LinearAlgebra.CSLapack.DLAPLL._dlas2 private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAPLL.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAPLL.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAPLL.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAPLL.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlapll.cs