Doc: IGLib EXTENDED: IG.Neural.Applications.ProgramNeuralParametric Class Reference
IG.Neural.Applications.ProgramNeuralParametric Class Reference
Static Protected Member Functions
static void SetWorkingDirectoryHardCoded ()
Properties
static NeuralParametric App [get]
Application driver.
Static Private Member Functions
static void Main (string[] args)
Static Private Attributes
static bool NormalModeNewForm = false
Member Function Documentation
SetWorkingDirectoryHardCoded()
static void IG.Neural.Applications.ProgramNeuralParametric.SetWorkingDirectoryHardCoded () inline static protected
References IG.Neural.Applications.ProgramNeuralParametric.App, IG.Lib.UtilSystem.IsUserIgor, IG.Lib.UtilSystem.IsUserTadej, and IG.Neural.Applications.NeuralParametric.WorkingDirectory.
Referenced by IG.Neural.Applications.ProgramNeuralParametric.Main().
Main()
static void IG.Neural.Applications.ProgramNeuralParametric.Main (string[] args) inline static private
References IG.Neural.Applications.ProgramNeuralParametric.App, IG.Neural.Applications.NeuralParametric.Init(), IG.Neural.Applications.NeuralParametric.IsDevelopMode, IG.Neural.Applications.NeuralParametric.IsDirectoryCasting, IG.Neural.Applications.NeuralParametric.IsDirectoryCustom, IG.Neural.Applications.NeuralParametric.IsDirectoryDefault, IG.Neural.Applications.NeuralParametric.IsDirectoryProcessChain, IG.Neural.Applications.NeuralParametric.IsDirectoryTestModel, IG.Neural.Applications.NeuralParametric.IsExperimentalMode, IG.Neural.Applications.NeuralParametric.IsNormalMode, IG.Neural.Applications.NeuralParametric.IsOldMode, IG.Neural.Applications.NeuralParametric.IsOldTadejMode, IG.Neural.Applications.NeuralParametric.IsOldTestMode, IG.Neural.Applications.NeuralParametric.IsPredictionMode, IG.Neural.Forms.Old.NeuralParametricDemoOld.IsTabPageVisibleParametric, IG.Neural.Applications.NeuralParametric.IsVerbose, IG.Neural.Applications.ProgramNeuralParametric.NormalModeNewForm, IG.Neural.Applications.NeuralParametric.SetWorkingDirectoryCasting(), IG.Neural.Applications.NeuralParametric.SetWorkingDirectoryCustom(), IG.Neural.Applications.NeuralParametric.SetWorkingDirectoryDefault(), IG.Neural.Applications.ProgramNeuralParametric.SetWorkingDirectoryHardCoded(), IG.Neural.Applications.NeuralParametric.SetWorkingDirectoryProcessChain(), IG.Neural.Applications.NeuralParametric.SetWorkingDirectoryTestModel(), and IG.Neural.Applications.NeuralParametric.WorkingDirectory.
Member Data Documentation
NormalModeNewForm
bool IG.Neural.Applications.ProgramNeuralParametric.NormalModeNewForm = false static private
Referenced by IG.Neural.Applications.ProgramNeuralParametric.Main().
Property Documentation
App
NeuralParametric IG.Neural.Applications.ProgramNeuralParametric.App static get
Application driver.
Referenced by IG.Neural.Applications.ProgramNeuralParametric.Main(), and IG.Neural.Applications.ProgramNeuralParametric.SetWorkingDirectoryHardCoded().
The documentation for this class was generated from the following file:
shelldev/extensions_shell/ExtAppNeuralParametric/ProgramNeuralParametric.cs