Doc: IGLib EXTENDED: IPPrototyperSample.CoinsFinder Class Reference
IPPrototyperSample.CoinsFinder Class Reference
Public Member Functions
void Process (Bitmap image, IImageProcessingLog log)
Perform image processing routine.
Properties
string Name [get]
Properties inherited from AForge.Imaging.IPPrototyper.IImageProcessingRoutine
string Name [get]
Image processing routine's name.
Member Function Documentation
Process()
void IPPrototyperSample.CoinsFinder.Process (Bitmap image, IImageProcessingLog log) inline
Perform image processing routine.
Parameters
image Source image to perform image processing on.
log Logger to use to put information about image processing steps/results.
Implements AForge.Imaging.IPPrototyper.IImageProcessingRoutine.
References AForge.Imaging.IPPrototyper.IImageProcessingLog.AddImage(), AForge.Imaging.IPPrototyper.IImageProcessingLog.AddMessage(), AForge.Imaging.Filters.BaseInPlacePartialFilter.Apply(), AForge.Imaging.Filters.BaseFilter.Apply(), AForge.Imaging.Filters.Grayscale.CommonAlgorithms.BT709, AForge.Imaging.BlobCounterBase.FilterBlobs, AForge.Imaging.BlobCounterBase.GetObjectsInformation(), AForge.Imaging.BlobCounterBase.MinWidth, AForge.Imaging.BlobCounterBase.ProcessImage(), and AForge.Imaging.Filters.OtsuThreshold.ThresholdValue.
Property Documentation
Name
string IPPrototyperSample.CoinsFinder.Name get
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Samples/Imaging/IPPrototyper Sample/CoinsFinder.cs