Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DSBEV Class Reference
DotNumerics.LinearAlgebra.CSLapack.DSBEV Class Reference
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DSBEV (LSAME lsame, DLAMCH dlamch, DLANSB dlansb, DLASCL dlascl, DSBTRD dsbtrd, DSCAL dscal, DSTEQR dsteqr, DSTERF dsterf, XERBLA xerbla)
DSBEV ()
void Run (string JOBZ, string UPLO, int N, int KD, ref double[] AB, int offset_ab, int LDAB, ref double[] W, int offset_w, ref double[] Z, int offset_z, int LDZ, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
LSAME _lsame
DLAMCH _dlamch
DLANSB _dlansb
DLASCL _dlascl
DSBTRD _dsbtrd
DSCAL _dscal
DSTEQR _dsteqr
DSTERF _dsterf
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
Detailed Description
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DSBEV computes all the eigenvalues and, optionally, eigenvectors of a real symmetric band matrix A.
/summary>
Constructor & Destructor Documentation
DSBEV() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DSBEV.DSBEV (LSAME lsame, DLAMCH dlamch, DLANSB dlansb, DLASCL dlascl, DSBTRD dsbtrd, DSCAL dscal, DSTEQR dsteqr, DSTERF dsterf, XERBLA xerbla) inline
DSBEV() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DSBEV.DSBEV () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DSBEV.Run (string JOBZ, string UPLO, int N, int KD, ref double[] AB, int offset_ab, int LDAB, ref double[] W, int offset_w, ref double[] Z, int offset_z, int LDZ, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
DSBEV computes all the eigenvalues and, optionally, eigenvectors of a real symmetric band matrix A.
/summary>
Parameters
JOBZ (input) CHARACTER*1 = 'N': Compute eigenvalues only; = 'V': Compute eigenvalues and eigenvectors. /param>
Parameters
UPLO (input) CHARACTER*1 = 'U': Upper triangle of A is stored; = 'L': Lower triangle of A is stored. /param>
Parameters
N (input) INTEGER The order of the matrix A. N .GE. 0. /param>
Parameters
KD (input) INTEGER The number of superdiagonals of the matrix A if UPLO = 'U', or the number of subdiagonals if UPLO = 'L'. KD .GE. 0. /param>
Parameters
AB (input/output) DOUBLE PRECISION array, dimension (LDAB, N) On entry, the upper or lower triangle of the symmetric band matrix A, stored in the first KD+1 rows of the array. The j-th column of A is stored in the j-th column of the array AB as follows: if UPLO = 'U', AB(kd+1+i-j,j) = A(i,j) for max(1,j-kd).LE.i.LE.j; if UPLO = 'L', AB(1+i-j,j) = A(i,j) for j.LE.i.LE.min(n,j+kd).
On exit, AB is overwritten by values generated during the reduction to tridiagonal form. If UPLO = 'U', the first superdiagonal and the diagonal of the tridiagonal matrix T are returned in rows KD and KD+1 of AB, and if UPLO = 'L', the diagonal and first subdiagonal of T are returned in the first two rows of AB. /param>
Parameters
LDAB (input) INTEGER The leading dimension of the array AB. LDAB .GE. KD + 1. /param>
Parameters
W (output) DOUBLE PRECISION array, dimension (N) If INFO = 0, the eigenvalues in ascending order. /param>
Parameters
Z (output) DOUBLE PRECISION array, dimension (LDZ, N) If JOBZ = 'V', then if INFO = 0, Z contains the orthonormal eigenvectors of the matrix A, with the i-th column of Z holding the eigenvector associated with W(i). If JOBZ = 'N', then Z is not referenced. /param>
Parameters
LDZ (input) INTEGER The leading dimension of the array Z. LDZ .GE. 1, and if JOBZ = 'V', LDZ .GE. max(1,N). /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (max(1,3*N-2)) /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value .GT. 0: if INFO = i, the algorithm failed to converge; i off-diagonal elements of an intermediate tridiagonal form did not converge to zero. /param>
References DotNumerics.LinearAlgebra.CSLapack.DSBEV.ONE, DotNumerics.LinearAlgebra.CSLapack.DSCAL.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTERF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANSB.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DSBTRD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DSBEV.ZERO.
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DSBEV._lsame private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DSBEV._dlamch private
_dlansb
DLANSB DotNumerics.LinearAlgebra.CSLapack.DSBEV._dlansb private
_dlascl
DLASCL DotNumerics.LinearAlgebra.CSLapack.DSBEV._dlascl private
_dsbtrd
DSBTRD DotNumerics.LinearAlgebra.CSLapack.DSBEV._dsbtrd private
_dscal
DSCAL DotNumerics.LinearAlgebra.CSLapack.DSBEV._dscal private
_dsteqr
DSTEQR DotNumerics.LinearAlgebra.CSLapack.DSBEV._dsteqr private
_dsterf
DSTERF DotNumerics.LinearAlgebra.CSLapack.DSBEV._dsterf private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DSBEV._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DSBEV.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSBEV.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DSBEV.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSBEV.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dsbev.cs