Doc: IGLib EXTENDED: AForge.Robotics.Surveyor.SRV1Camera Class Reference
AForge.Robotics.Surveyor.SRV1Camera Class Reference
Provides access to video stream from Surveyor SRV-1 Blackfin camera.
Public Member Functions
void Start ()
Start video source.
void SignalToStop ()
Signal video source to stop its work.
void WaitForStop ()
Wait for video source has stopped.
void Stop ()
Stop video source.
void SetQuality (int quality)
Set video quality.
void SetResolution (SRV1.VideoResolution resolution)
Set video resolution.
void FlipVideo (bool isFlipped)
Flip video capture or not (for use with upside-down camera).
Properties
int FrameInterval [get, set]
Frame interval.
string? Source [get]
Video source string.
int FramesReceived [get]
Received frames count.
long BytesReceived [get]
Received bytes count.
bool IsRunning [get]
State of the video source.
Properties inherited from AForge.Video.IVideoSource
string Source [get]
Video source.
int FramesReceived [get]
Received frames count.
long BytesReceived [get]
Received bytes count.
bool IsRunning [get]
State of the video source.
Events
NewFrameEventHandler NewFrame
New frame event.
VideoSourceErrorEventHandler VideoSourceError
Video source error event.
PlayingFinishedEventHandler PlayingFinished
Video playing finished event.
Events inherited from AForge.Video.IVideoSource
NewFrameEventHandler NewFrame
New frame event.
VideoSourceErrorEventHandler VideoSourceError
Video source error event.
PlayingFinishedEventHandler PlayingFinished
Video playing finished event.
Private Member Functions
void Free ()
Free resource.
void WorkerThread ()
Worker thread.
Private Attributes
SRV1 communicator
int framesReceived
long bytesReceived
int frameInterval = 0
Thread thread = null
ManualResetEvent stopEvent = null
Static Private Attributes
const int bufferSize = 768 * 1024
Detailed Description
Provides access to video stream from Surveyor SRV-1 Blackfin camera.
The class allows to continuously receive video frames from Surveyor SRV-1 Blackfin camera. It creates a background thread and periodically requests new video frames from SRV-1 robot/camera, which are provided to user through NewFrame event. The video frame rate can be configured using FrameInterval property, which sets time interval between frames.
In order to get instance of this class, use SRV1.GetCamera or SVS.GetCamera methods.
Sample usage:
// get SRV-1 camera
SRV1Camera camera = srv.GetCamera();
// in the case you work with Surveyor SVS board
// the next line can be use
// SRV1Camera camera = svs.GetCamera(SVS.Camera.Left);
// set NewFrame event handler
camera.NewFrame += new NewFrameEventHandler(video_NewFrame);
// start the video source
camera.Start();
// ...
private void video_NewFrame(object sender, NewFrameEventArgs eventArgs)
{
    // get new frame
    Bitmap bitmap = eventArgs.Frame;
    // process the frame
}
Member Function Documentation
Start()
void AForge.Robotics.Surveyor.SRV1Camera.Start () inline
Start video source.
Starts video source and return execution to caller. Video source object creates background thread and notifies about new frames with the help of NewFrame event.
Exceptions
NotConnectedException Not connected to SRV-1. Connection to SRV-1 was closed using SRV1.Disconnect method. New SRV1Camera instance must be obtained using SRV1.GetCamera or SVS.GetCamera methods.
Implements AForge.Video.IVideoSource.
References AForge.Robotics.Surveyor.SRV1Camera.bytesReceived, AForge.Robotics.Surveyor.SRV1Camera.communicator, AForge.Robotics.Surveyor.SRV1Camera.framesReceived, AForge.Robotics.Surveyor.SRV1Camera.Source, AForge.Robotics.Surveyor.SRV1Camera.stopEvent, AForge.Robotics.Surveyor.SRV1Camera.thread, and AForge.Robotics.Surveyor.SRV1Camera.WorkerThread().
SignalToStop()
void AForge.Robotics.Surveyor.SRV1Camera.SignalToStop () inline
Signal video source to stop its work.
Signals video source to stop its background thread, stop to provide new frames and free resources.
Implements AForge.Video.IVideoSource.
References AForge.Robotics.Surveyor.SRV1Camera.stopEvent, and AForge.Robotics.Surveyor.SRV1Camera.thread.
Referenced by AForge.Robotics.Surveyor.SVS.Disconnect(), and AForge.Robotics.Surveyor.SRV1.Disconnect().
WaitForStop()
void AForge.Robotics.Surveyor.SRV1Camera.WaitForStop () inline
Wait for video source has stopped.
Waits for video source stopping after it was signalled to stop using SignalToStop method.
Implements AForge.Video.IVideoSource.
References AForge.Robotics.Surveyor.SRV1Camera.Free(), and AForge.Robotics.Surveyor.SRV1Camera.thread.
Referenced by AForge.Robotics.Surveyor.SRV1Camera.Stop().
Stop()
void AForge.Robotics.Surveyor.SRV1Camera.Stop () inline
Stop video source.
Stops video source aborting its thread.
<note>Since the method aborts background thread, its usage is highly not preferred and should be done only if there are no other options. The correct way of stopping camera is signaling it to stop and then waiting for background thread's completion.</note>
Implements AForge.Video.IVideoSource.
References AForge.Robotics.Surveyor.SRV1Camera.IsRunning, and AForge.Robotics.Surveyor.SRV1Camera.WaitForStop().
Referenced by AForge.Robotics.Surveyor.SVS.Disconnect(), and AForge.Robotics.Surveyor.SRV1.Disconnect().
Free()
void AForge.Robotics.Surveyor.SRV1Camera.Free () inline private
Free resource.
References AForge.Robotics.Surveyor.SRV1Camera.stopEvent, and AForge.Robotics.Surveyor.SRV1Camera.thread.
Referenced by AForge.Robotics.Surveyor.SRV1Camera.WaitForStop().
SetQuality()
void AForge.Robotics.Surveyor.SRV1Camera.SetQuality (int quality) inline
Set video quality.
Parameters
quality Video quality to set, [1, 8].
The method sets video quality, which is specified in [1, 8] range - 1 is the highest quality level, 8 is the lowest quality level.
<note>Setting higher quality level and resolution may increase delays for other requests processed by SRV1 class. So if robot is used not only for video, but also for controlling servos/motors, and higher response level is required, then do not set very high quality and resolution. </note>
Exceptions
ArgumentOutOfRangeException Invalid quality level was specified.
References AForge.Robotics.Surveyor.SRV1Camera.communicator, and AForge.Robotics.Surveyor.SRV1.SetQuality().
SetResolution()
void AForge.Robotics.Surveyor.SRV1Camera.SetResolution (SRV1.VideoResolution resolution) inline
Set video resolution.
Parameters
resolution Video resolution to set.
<note>Setting higher quality level and resolution may increase delays for other requests processed by SRV1 class. So if robot is used not only for video, but also for controlling servos/motors, and higher response level is required, then do not set very high quality and resolution. </note>
References AForge.Robotics.Surveyor.SRV1Camera.communicator, and AForge.Robotics.Surveyor.SRV1.SetResolution().
FlipVideo()
void AForge.Robotics.Surveyor.SRV1Camera.FlipVideo (bool isFlipped) inline
Flip video capture or not (for use with upside-down camera).
Parameters
isFlipped Specifies if video should be flipped (true), or not (false).
References AForge.Robotics.Surveyor.SRV1Camera.communicator, and AForge.Robotics.Surveyor.SRV1.FlipVideo().
WorkerThread()
void AForge.Robotics.Surveyor.SRV1Camera.WorkerThread () inline private
Worker thread.
References AForge.Robotics.Surveyor.SRV1Camera.bufferSize, AForge.Robotics.Surveyor.SRV1Camera.bytesReceived, AForge.Robotics.Surveyor.SRV1Camera.communicator, AForge.Robotics.Surveyor.SRV1Camera.frameInterval, AForge.Robotics.Surveyor.SRV1Camera.framesReceived, AForge.Robotics.Surveyor.SRV1Camera.NewFrame, AForge.Robotics.Surveyor.SRV1Camera.PlayingFinished, AForge.Robotics.Surveyor.SRV1.SendAndReceive(), AForge.Robotics.Surveyor.SRV1Camera.stopEvent, and AForge.Robotics.Surveyor.SRV1Camera.VideoSourceError.
Referenced by AForge.Robotics.Surveyor.SRV1Camera.Start().
Member Data Documentation
communicator
SRV1 AForge.Robotics.Surveyor.SRV1Camera.communicator private
Referenced by AForge.Robotics.Surveyor.SRV1Camera.FlipVideo(), AForge.Robotics.Surveyor.SRV1Camera.SetQuality(), AForge.Robotics.Surveyor.SRV1Camera.SetResolution(), AForge.Robotics.Surveyor.SRV1Camera.Start(), and AForge.Robotics.Surveyor.SRV1Camera.WorkerThread().
framesReceived
int AForge.Robotics.Surveyor.SRV1Camera.framesReceived private
Referenced by AForge.Robotics.Surveyor.SRV1Camera.Start(), and AForge.Robotics.Surveyor.SRV1Camera.WorkerThread().
bytesReceived
long AForge.Robotics.Surveyor.SRV1Camera.bytesReceived private
Referenced by AForge.Robotics.Surveyor.SRV1Camera.Start(), and AForge.Robotics.Surveyor.SRV1Camera.WorkerThread().
frameInterval
int AForge.Robotics.Surveyor.SRV1Camera.frameInterval = 0 private
Referenced by AForge.Robotics.Surveyor.SRV1Camera.WorkerThread().
thread
Thread AForge.Robotics.Surveyor.SRV1Camera.thread = null private
Referenced by AForge.Robotics.Surveyor.SRV1Camera.Free(), AForge.Robotics.Surveyor.SRV1Camera.SignalToStop(), AForge.Robotics.Surveyor.SRV1Camera.Start(), and AForge.Robotics.Surveyor.SRV1Camera.WaitForStop().
stopEvent
ManualResetEvent AForge.Robotics.Surveyor.SRV1Camera.stopEvent = null private
Referenced by AForge.Robotics.Surveyor.SRV1Camera.Free(), AForge.Robotics.Surveyor.SRV1Camera.SignalToStop(), AForge.Robotics.Surveyor.SRV1Camera.Start(), and AForge.Robotics.Surveyor.SRV1Camera.WorkerThread().
bufferSize
const int AForge.Robotics.Surveyor.SRV1Camera.bufferSize = 768 * 1024 static private
Referenced by AForge.Robotics.Surveyor.SRV1Camera.WorkerThread().
Property Documentation
FrameInterval
int AForge.Robotics.Surveyor.SRV1Camera.FrameInterval get set
Frame interval.
The property sets the interval in milliseconds betwen frames. If the property is set to 100, then the desired frame rate will be 10 frames per second.
Default value is set to 0 - get new frames as fast as possible.
Source
string? AForge.Robotics.Surveyor.SRV1Camera.Source get
Video source string.
The property keeps connection string, which was used to connect to SRV-1 Blackfin camera.
Referenced by AForge.Robotics.Surveyor.SRV1Camera.Start().
FramesReceived
int AForge.Robotics.Surveyor.SRV1Camera.FramesReceived get
Received frames count.
Number of frames the video source provided from the moment of the last access to the property.
BytesReceived
long AForge.Robotics.Surveyor.SRV1Camera.BytesReceived get
Received bytes count.
Number of bytes the video source provided from the moment of the last access to the property.
IsRunning
bool AForge.Robotics.Surveyor.SRV1Camera.IsRunning get
State of the video source.
Current state of video source object - running or not.
Referenced by AForge.Robotics.Surveyor.SVS.Disconnect(), AForge.Robotics.Surveyor.SRV1.Disconnect(), and AForge.Robotics.Surveyor.SRV1Camera.Stop().
Event Documentation
NewFrame
NewFrameEventHandler AForge.Robotics.Surveyor.SRV1Camera.NewFrame
New frame event.
Notifies clients about new available frame from video source.
<note>Since video source may have multiple clients, each client is responsible for making a copy (cloning) of the passed video frame, because the video source disposes its own original copy after notifying of clients.</note>
Referenced by AForge.Robotics.Surveyor.SRV1Camera.WorkerThread().
VideoSourceError
VideoSourceErrorEventHandler AForge.Robotics.Surveyor.SRV1Camera.VideoSourceError
Video source error event.
This event is used to notify clients about any type of errors occurred in video source object, for example internal exceptions.
Referenced by AForge.Robotics.Surveyor.SRV1Camera.WorkerThread().
PlayingFinished
PlayingFinishedEventHandler AForge.Robotics.Surveyor.SRV1Camera.PlayingFinished
Video playing finished event.
This event is used to notify clients that the video playing has finished.
Referenced by AForge.Robotics.Surveyor.SRV1Camera.WorkerThread().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Robotics.Surveyor/SRV1Camera.cs