Doc: IGLib EXTENDED: NUnit.Framework.Constraints.RangeTests Class Reference
NUnit.Framework.Constraints.RangeTests Class Reference
Public Member Functions
void InRangeSucceeds ()
void InRangeFails ()
void NotInRangeSucceeds ()
void NotInRangeFails ()
void ShouldThrowExceptionIfFromIsLessThanTo ()
void RangeBoundaryConditions (int actual, int from, int to)
void MixedRangeTests< TMin, TMax, TVal > (TMin min, TMax max, TVal val)
Private Member Functions
void FailingInRangeMethod ()
void FailingNotInRangeMethod ()
Member Function Documentation
InRangeSucceeds()
void NUnit.Framework.Constraints.RangeTests.InRangeSucceeds () inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
InRangeFails()
void NUnit.Framework.Constraints.RangeTests.InRangeFails () inline
References NUnit.Framework.Constraints.RangeTests.FailingInRangeMethod(), NUnit.Env.NewLine, NUnit.Framework.TestDelegate(), NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
FailingInRangeMethod()
void NUnit.Framework.Constraints.RangeTests.FailingInRangeMethod () inline private
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Constraints.RangeTests.InRangeFails().
NotInRangeSucceeds()
void NUnit.Framework.Constraints.RangeTests.NotInRangeSucceeds () inline
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
NotInRangeFails()
void NUnit.Framework.Constraints.RangeTests.NotInRangeFails () inline
References NUnit.Framework.Constraints.RangeTests.FailingNotInRangeMethod(), NUnit.Env.NewLine, NUnit.Framework.TestDelegate(), NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
FailingNotInRangeMethod()
void NUnit.Framework.Constraints.RangeTests.FailingNotInRangeMethod () inline private
References NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Constraints.RangeTests.NotInRangeFails().
ShouldThrowExceptionIfFromIsLessThanTo()
void NUnit.Framework.Constraints.RangeTests.ShouldThrowExceptionIfFromIsLessThanTo () inline
References NUnit.Framework.Throws.ArgumentException, NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
RangeBoundaryConditions()
void NUnit.Framework.Constraints.RangeTests.RangeBoundaryConditions (int actual, int from, int to) inline
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
MixedRangeTests< TMin, TMax, TVal >()
void NUnit.Framework.Constraints.RangeTests.MixedRangeTests< TMin, TMax, TVal > (TMin min, TMax max, TVal val) inline
Type Constraints
TMin : IComparable
TMax : IComparable
TVal : IComparable
References NUnit.Framework.Is.InRange(), and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/RangeTests.cs