Doc: IGLib EXTENDED: Meta.Numerics.Statistics.Distributions.DiscreteDistribution Class Reference
Meta.Numerics.Statistics.Distributions.DiscreteDistribution Class Reference abstract
Represents all discrete, univariate probability distrubtions.
Public Member Functions
abstract double ProbabilityMass (int k)
Returns the probability of the obtaining the given value.
virtual double LeftExclusiveProbability (int k)
Computes the probability of obtaining a value less than the given value.
virtual double LeftInclusiveProbability (int k)
Computes the probability of obtaining a value less than or equal to the given value.
virtual double RightExclusiveProbability (int k)
Computes the probability of obtaining a value greater than the given value.
virtual int InverseLeftProbability (double P)
Computes the value corresponding to the given percentile.
virtual double ExpectationValue (Func< int, double > f)
Computes the expectation value of an artibrary function.
override double Moment (int r)
Gets a raw moment of the distribution.
override double MomentAboutMean (int r)
Gets a central moment of the distribution.
virtual int GetRandomValue (Random rng)
Produces a random integer drawn from the distribution.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Cumulant (int r)
Computes a cumulant of the distribution.
Properties
abstract int Minimum [get]
Gets the smallest value in the distribution.
abstract int Maximum [get]
Gets the largest value in the distribution.
override double Mean [get]
Gets the mean of the distribution.
Properties inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Mean [get]
Gets the mean of the distribution.
virtual double Variance [get]
Gets the variance of the distribution.
virtual double StandardDeviation [get]
Gets the standard deviation of the distribution.
virtual double Skewness [get]
Gets the skewness of the distribution.
virtual double ExcessKurtosis [get]
Gets the excess kurtosis of the distribution.
Detailed Description
Represents all discrete, univariate probability distrubtions.
A discrete distribution is a distribution over the integers.
Member Function Documentation
ProbabilityMass()
abstract double Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ProbabilityMass (int k) pure virtual
Returns the probability of the obtaining the given value.
Parameters
k The value.
Returns
The probability of obtaining the value.
Implemented in Test.DiscreteTestDistribution, Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution, Meta.Numerics.Statistics.Distributions.GeometricDistribution, Meta.Numerics.Statistics.Distributions.DiscreteUniformDistribution, Meta.Numerics.Statistics.Distributions.BinomialDistribution, Meta.Numerics.Statistics.Distributions.BernoulliDistribution, and Meta.Numerics.Statistics.Distributions.PoissonDistribution.
Referenced by Meta.Numerics.Statistics.Histogram.ChiSquaredTest(), Test.DiscreteDistributionTest.DiscreteDistributionBase(), Test.DiscreteDistributionTest.DiscreteDistributionProbabilityAxioms(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ExpectationValue(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.InverseLeftProbability(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.LeftExclusiveProbability(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.LeftInclusiveProbability(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.LeftProbability(), Test.DiscreteDistributionTest.OutsideDiscreteDistributionSupport(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.ProbabilityDensity(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.RightExclusiveProbability(), and Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.RightProbability().
LeftExclusiveProbability()
virtual double Meta.Numerics.Statistics.Distributions.DiscreteDistribution.LeftExclusiveProbability (int k) inline virtual
Computes the probability of obtaining a value less than the given value.
Parameters
k The value.
Returns
The total probability of obtaining a value strictly less than k .
See also
RightExclusiveProbability
Reimplemented in Meta.Numerics.Statistics.Distributions.BinomialDistribution, Meta.Numerics.Statistics.Distributions.BernoulliDistribution, Meta.Numerics.Statistics.Distributions.PoissonDistribution, Meta.Numerics.Statistics.Distributions.DiscreteUniformDistribution, Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution, and Meta.Numerics.Statistics.Distributions.GeometricDistribution.
References Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Maximum, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Minimum, and Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ProbabilityMass().
Referenced by Test.DiscreteDistributionTest.DiscreteDistributionInverseCDF(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.LeftInclusiveProbability(), and Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.LeftProbability().
LeftInclusiveProbability()
virtual double Meta.Numerics.Statistics.Distributions.DiscreteDistribution.LeftInclusiveProbability (int k) inline virtual
Computes the probability of obtaining a value less than or equal to the given value.
Parameters
k The value.
Returns
The total probability of obtaining a value les than or equal to k .
Reimplemented in Meta.Numerics.Statistics.Distributions.PoissonDistribution, and Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution.
References Meta.Numerics.Statistics.Distributions.DiscreteDistribution.LeftExclusiveProbability(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Maximum, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Minimum, and Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ProbabilityMass().
Referenced by Test.DiscreteDistributionTest.DiscreteDistributionBase(), Test.DiscreteDistributionTest.DiscreteDistributionInverseCDF(), Test.DiscreteDistributionTest.DiscreteDistributionProbabilityAxioms(), Meta.Numerics.Statistics.Distributions.BinomialDistribution.InverseLeftProbability(), and Test.DiscreteDistributionTest.OutsideDiscreteDistributionSupport().
RightExclusiveProbability()
virtual double Meta.Numerics.Statistics.Distributions.DiscreteDistribution.RightExclusiveProbability (int k) inline virtual
Computes the probability of obtaining a value greater than the given value.
Parameters
k The value.
Returns
The total probability of obtaining a value strictly greater than k .
See also
LeftExclusiveProbability
Reimplemented in Meta.Numerics.Statistics.Distributions.BinomialDistribution, Meta.Numerics.Statistics.Distributions.BernoulliDistribution, Meta.Numerics.Statistics.Distributions.PoissonDistribution, Meta.Numerics.Statistics.Distributions.DiscreteUniformDistribution, and Meta.Numerics.Statistics.Distributions.GeometricDistribution.
References Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Maximum, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Minimum, and Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ProbabilityMass().
Referenced by Test.DiscreteDistributionTest.DiscreteDistributionProbabilityAxioms(), Test.DiscreteDistributionTest.OutsideDiscreteDistributionSupport(), and Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.RightProbability().
InverseLeftProbability()
virtual int Meta.Numerics.Statistics.Distributions.DiscreteDistribution.InverseLeftProbability (double P) inline virtual
Computes the value corresponding to the given percentile.
Parameters
P The percentile.
Returns
The value.
Reimplemented in Meta.Numerics.Statistics.Distributions.BinomialDistribution, Meta.Numerics.Statistics.Distributions.BernoulliDistribution, Meta.Numerics.Statistics.Distributions.PoissonDistribution, Meta.Numerics.Statistics.Distributions.DiscreteUniformDistribution, and Meta.Numerics.Statistics.Distributions.GeometricDistribution.
References Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Maximum, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Minimum, and Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ProbabilityMass().
Referenced by Test.DiscreteDistributionTest.DiscreteDistributionBase(), Test.DiscreteDistributionTest.DiscreteDistributionInverseCDF(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.GetRandomValue(), and Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.InverseLeftProbability().
ExpectationValue()
virtual double Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ExpectationValue (Func< int, double > f) inline virtual
Computes the expectation value of an artibrary function.
Parameters
f The function.
Returns
The expectation value of the function.
Reimplemented in Meta.Numerics.Statistics.Distributions.KolmogorovTwoSampleExactDistribution.
References Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Maximum, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Mean, Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Minimum, and Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ProbabilityMass().
Referenced by Test.DiscreteDistributionTest.DiscreteDistributionMean(), Test.DiscreteDistributionTest.DiscreteDistributionUnitarity(), Test.DiscreteDistributionTest.DiscreteDistributionVariance(), Meta.Numerics.Statistics.Distributions.BinomialDistribution.Moment(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Moment(), and Meta.Numerics.Statistics.Distributions.DiscreteDistribution.MomentAboutMean().
Moment()
override double Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Moment (int r) inline virtual
Gets a raw moment of the distribution.
Parameters
r The order of the moment.
Returns
The raw moment Mr.
Implements Meta.Numerics.Statistics.Distributions.UnivariateDistribution.
Reimplemented in Meta.Numerics.Statistics.Distributions.PoissonDistribution, and Meta.Numerics.Statistics.Distributions.GeometricDistribution.
References Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ExpectationValue(), and Meta.Numerics.MoreMath.Pow().
Referenced by Test.DiscreteDistributionTest.DiscreteContinuousAgreement(), Test.DiscreteDistributionTest.DiscreteDistributionBase(), and Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.Moment().
MomentAboutMean()
override double Meta.Numerics.Statistics.Distributions.DiscreteDistribution.MomentAboutMean (int r) inline virtual
Gets a central moment of the distribution.
Parameters
r The order of the moment.
Returns
The central moment Cr.
Reimplemented from Meta.Numerics.Statistics.Distributions.UnivariateDistribution.
Reimplemented in Meta.Numerics.Statistics.Distributions.PoissonDistribution, and Meta.Numerics.Statistics.Distributions.DiscreteUniformDistribution.
References Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ExpectationValue(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Mean, and Meta.Numerics.MoreMath.Pow().
Referenced by Test.DiscreteDistributionTest.DiscreteContinuousAgreement(), Test.DiscreteDistributionTest.DiscreteDistributionBase(), Test.DiscreteDistributionTest.DiscreteDistributionSkewness(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.MomentAboutMean(), and Test.SampleTest.SignTestDistribution().
GetRandomValue()
virtual int Meta.Numerics.Statistics.Distributions.DiscreteDistribution.GetRandomValue (Random rng) inline virtual
Produces a random integer drawn from the distribution.
Parameters
rng A random number generator.
Returns
A random integer drawn from the distribution.
References Meta.Numerics.Statistics.Distributions.DiscreteDistribution.InverseLeftProbability().
Referenced by Test.DiscreteDistributionTest.DiscreteDistributionRandomValues().
Property Documentation
Minimum
abstract int Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Minimum get
Gets the smallest value in the distribution.
Referenced by Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.ComputeEffectiveBin(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.DiscreteAsContinuousDistribution(), Test.DiscreteDistributionTest.DiscreteContinuousAgreement(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ExpectationValue(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.InverseLeftProbability(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.LeftExclusiveProbability(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.LeftInclusiveProbability(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.MomentAboutMean(), Test.DiscreteDistributionTest.OutsideDiscreteDistributionSupport(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.ProbabilityDensity(), and Meta.Numerics.Statistics.Distributions.DiscreteDistribution.RightExclusiveProbability().
Maximum
abstract int Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Maximum get
Gets the largest value in the distribution.
Referenced by Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.ComputeEffectiveBin(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.DiscreteAsContinuousDistribution(), Test.DiscreteDistributionTest.DiscreteContinuousAgreement(), Test.DiscreteDistributionTest.DiscreteDistributionRandomValues(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ExpectationValue(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.InverseLeftProbability(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.LeftExclusiveProbability(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.LeftInclusiveProbability(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.MomentAboutMean(), Test.DiscreteDistributionTest.OutsideDiscreteDistributionSupport(), Meta.Numerics.Statistics.Distributions.DiscreteAsContinuousDistribution.ProbabilityDensity(), and Meta.Numerics.Statistics.Distributions.DiscreteDistribution.RightExclusiveProbability().
Mean
override double Meta.Numerics.Statistics.Distributions.DiscreteDistribution.Mean get
Gets the mean of the distribution.
Referenced by Test.DiscreteDistributionTest.DiscreteContinuousAgreement(), Test.DiscreteDistributionTest.DiscreteDistributionBase(), Test.DiscreteDistributionTest.DiscreteDistributionMean(), Test.DiscreteDistributionTest.DiscreteDistributionRandomValues(), Test.DiscreteDistributionTest.DiscreteDistributionVariance(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.ExpectationValue(), Meta.Numerics.Statistics.Distributions.DiscreteDistribution.MomentAboutMean(), and Test.SampleTest.SignTestDistribution().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/Distributions/DiscreteDistribution.cs