Doc: IGLib EXTENDED: SVSTest.SrvDriverControl Class Reference
SVSTest.SrvDriverControl Class Reference
Public Member Functions
SrvDriverControl ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Events
SrvDrivingCommandHandler SrvDrivingCommand
Private Member Functions
void DispatchCommand (SRV1.MotorCommand command)
void leftButton_Click (object sender, EventArgs e)
void forwardButton_Click (object sender, EventArgs e)
void rightButton_Click (object sender, EventArgs e)
void leftDriftButton_Click (object sender, EventArgs e)
void stopButton_Click (object sender, EventArgs e)
void rightDriftButton_Click (object sender, EventArgs e)
void leftBackwardButton_Click (object sender, EventArgs e)
void backwardButton_Click (object sender, EventArgs e)
void rightBackwardButton_Click (object sender, EventArgs e)
void speedUpButton_Click (object sender, EventArgs e)
void slowDownButton_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Button stopButton
System.Windows.Forms.Button forwardButton
System.Windows.Forms.Button backwardButton
System.Windows.Forms.Button leftButton
System.Windows.Forms.Button leftBackwardButton
System.Windows.Forms.Button rightBackwardButton
System.Windows.Forms.Button leftDriftButton
System.Windows.Forms.Button rightButton
System.Windows.Forms.Button rightDriftButton
System.Windows.Forms.Button speedUpButton
System.Windows.Forms.Button slowDownButton
Constructor & Destructor Documentation
SrvDriverControl()
SVSTest.SrvDriverControl.SrvDriverControl () inline
References SVSTest.SrvDriverControl.InitializeComponent().
Member Function Documentation
DispatchCommand()
void SVSTest.SrvDriverControl.DispatchCommand (SRV1.MotorCommand command) inline private
References SVSTest.SrvDriverControl.SrvDrivingCommand.
Referenced by SVSTest.SrvDriverControl.backwardButton_Click(), SVSTest.SrvDriverControl.forwardButton_Click(), SVSTest.SrvDriverControl.leftBackwardButton_Click(), SVSTest.SrvDriverControl.leftButton_Click(), SVSTest.SrvDriverControl.leftDriftButton_Click(), SVSTest.SrvDriverControl.rightBackwardButton_Click(), SVSTest.SrvDriverControl.rightButton_Click(), SVSTest.SrvDriverControl.rightDriftButton_Click(), SVSTest.SrvDriverControl.slowDownButton_Click(), SVSTest.SrvDriverControl.speedUpButton_Click(), and SVSTest.SrvDriverControl.stopButton_Click().
leftButton_Click()
void SVSTest.SrvDriverControl.leftButton_Click (object sender, EventArgs e) inline private
References SVSTest.SrvDriverControl.DispatchCommand().
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
forwardButton_Click()
void SVSTest.SrvDriverControl.forwardButton_Click (object sender, EventArgs e) inline private
References SVSTest.SrvDriverControl.DispatchCommand().
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
rightButton_Click()
void SVSTest.SrvDriverControl.rightButton_Click (object sender, EventArgs e) inline private
References SVSTest.SrvDriverControl.DispatchCommand().
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
leftDriftButton_Click()
void SVSTest.SrvDriverControl.leftDriftButton_Click (object sender, EventArgs e) inline private
References SVSTest.SrvDriverControl.DispatchCommand().
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
stopButton_Click()
void SVSTest.SrvDriverControl.stopButton_Click (object sender, EventArgs e) inline private
References SVSTest.SrvDriverControl.DispatchCommand().
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
rightDriftButton_Click()
void SVSTest.SrvDriverControl.rightDriftButton_Click (object sender, EventArgs e) inline private
References SVSTest.SrvDriverControl.DispatchCommand().
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
leftBackwardButton_Click()
void SVSTest.SrvDriverControl.leftBackwardButton_Click (object sender, EventArgs e) inline private
References SVSTest.SrvDriverControl.DispatchCommand().
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
backwardButton_Click()
void SVSTest.SrvDriverControl.backwardButton_Click (object sender, EventArgs e) inline private
References SVSTest.SrvDriverControl.DispatchCommand().
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
rightBackwardButton_Click()
void SVSTest.SrvDriverControl.rightBackwardButton_Click (object sender, EventArgs e) inline private
References SVSTest.SrvDriverControl.DispatchCommand().
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
speedUpButton_Click()
void SVSTest.SrvDriverControl.speedUpButton_Click (object sender, EventArgs e) inline private
References SVSTest.SrvDriverControl.DispatchCommand().
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
slowDownButton_Click()
void SVSTest.SrvDriverControl.slowDownButton_Click (object sender, EventArgs e) inline private
References SVSTest.SrvDriverControl.DispatchCommand().
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
Dispose()
override void SVSTest.SrvDriverControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References SVSTest.SrvDriverControl.components.
InitializeComponent()
void SVSTest.SrvDriverControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References SVSTest.SrvDriverControl.backwardButton, SVSTest.SrvDriverControl.backwardButton_Click(), SVSTest.SrvDriverControl.forwardButton, SVSTest.SrvDriverControl.forwardButton_Click(), SVSTest.SrvDriverControl.leftBackwardButton, SVSTest.SrvDriverControl.leftBackwardButton_Click(), SVSTest.SrvDriverControl.leftButton, SVSTest.SrvDriverControl.leftButton_Click(), SVSTest.SrvDriverControl.leftDriftButton, SVSTest.SrvDriverControl.leftDriftButton_Click(), SVSTest.SrvDriverControl.rightBackwardButton, SVSTest.SrvDriverControl.rightBackwardButton_Click(), SVSTest.SrvDriverControl.rightButton, SVSTest.SrvDriverControl.rightButton_Click(), SVSTest.SrvDriverControl.rightDriftButton, SVSTest.SrvDriverControl.rightDriftButton_Click(), SVSTest.SrvDriverControl.slowDownButton, SVSTest.SrvDriverControl.slowDownButton_Click(), SVSTest.SrvDriverControl.speedUpButton, SVSTest.SrvDriverControl.speedUpButton_Click(), SVSTest.SrvDriverControl.stopButton, and SVSTest.SrvDriverControl.stopButton_Click().
Referenced by SVSTest.SrvDriverControl.SrvDriverControl().
Member Data Documentation
components
System.ComponentModel.IContainer SVSTest.SrvDriverControl.components = null private
Required designer variable.
Referenced by SVSTest.SrvDriverControl.Dispose().
stopButton
System.Windows.Forms.Button SVSTest.SrvDriverControl.stopButton private
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
forwardButton
System.Windows.Forms.Button SVSTest.SrvDriverControl.forwardButton private
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
backwardButton
System.Windows.Forms.Button SVSTest.SrvDriverControl.backwardButton private
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
leftButton
System.Windows.Forms.Button SVSTest.SrvDriverControl.leftButton private
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
leftBackwardButton
System.Windows.Forms.Button SVSTest.SrvDriverControl.leftBackwardButton private
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
rightBackwardButton
System.Windows.Forms.Button SVSTest.SrvDriverControl.rightBackwardButton private
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
leftDriftButton
System.Windows.Forms.Button SVSTest.SrvDriverControl.leftDriftButton private
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
rightButton
System.Windows.Forms.Button SVSTest.SrvDriverControl.rightButton private
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
rightDriftButton
System.Windows.Forms.Button SVSTest.SrvDriverControl.rightDriftButton private
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
speedUpButton
System.Windows.Forms.Button SVSTest.SrvDriverControl.speedUpButton private
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
slowDownButton
System.Windows.Forms.Button SVSTest.SrvDriverControl.slowDownButton private
Referenced by SVSTest.SrvDriverControl.InitializeComponent().
Event Documentation
SrvDrivingCommand
SrvDrivingCommandHandler SVSTest.SrvDriverControl.SrvDrivingCommand
Referenced by SVSTest.SrvDriverControl.DispatchCommand(), and SVSTest.MainForm.InitializeComponent().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Robotics/Surveyor/SVSTest/SrvDriverControl.cs
shelldev/lib_ann/aforge.net/Samples/Robotics/Surveyor/SVSTest/SrvDriverControl.Designer.cs