Doc: IGLib EXTENDED: CShell.Framework.Services.IStatusBar Interface Reference
CShell.Framework.Services.IStatusBar Interface Reference
Public Member Functions
void UpdateMessage ()
void UpdateMessage (string message)
void UpdateProgress (bool running)
void UpdateProgress (int progress)
Properties
string Message [get]
int Progress [get]
bool ShowingProgress [get]
Member Function Documentation
UpdateMessage() [1/2]
void CShell.Framework.Services.IStatusBar.UpdateMessage ()
Implemented in CShell.Modules.Shell.ViewModels.StatusBarViewModel.
Referenced by CShell.Modules.Shell.ViewModels.ShellViewModel.OnViewLoaded(), and CShell.Modules.Repl.ViewModels.ReplViewModel.TimerOnElapsed().
UpdateMessage() [2/2]
void CShell.Framework.Services.IStatusBar.UpdateMessage (string message)
Implemented in CShell.Modules.Shell.ViewModels.StatusBarViewModel.
UpdateProgress() [1/2]
void CShell.Framework.Services.IStatusBar.UpdateProgress (bool running)
Implemented in CShell.Modules.Shell.ViewModels.StatusBarViewModel.
Referenced by CShell.Modules.Shell.ViewModels.ShellViewModel.OnViewLoaded(), and CShell.Modules.Repl.ViewModels.ReplViewModel.TimerOnElapsed().
UpdateProgress() [2/2]
void CShell.Framework.Services.IStatusBar.UpdateProgress (int progress)
Implemented in CShell.Modules.Shell.ViewModels.StatusBarViewModel.
Property Documentation
Message
string CShell.Framework.Services.IStatusBar.Message get
Referenced by CShell.Modules.Repl.ViewModels.ReplViewModel.TimerOnElapsed().
Progress
int CShell.Framework.Services.IStatusBar.Progress get
ShowingProgress
bool CShell.Framework.Services.IStatusBar.ShowingProgress get
The documentation for this interface was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore/Framework/Services/IStatusBar.cs