Doc: IGLib EXTENDED: alglib.creflections Class Reference
alglib.creflections Class Reference
Static Public Member Functions
static void complexgeneratereflection (ref complex[] x, int n, ref complex tau)
static void complexapplyreflectionfromtheleft (ref complex[,] c, complex tau, complex[] v, int m1, int m2, int n1, int n2, ref complex[] work)
static void complexapplyreflectionfromtheright (ref complex[,] c, complex tau, ref complex[] v, int m1, int m2, int n1, int n2, ref complex[] work)
static void complexgeneratereflection (ref complex[] x, int n, ref complex tau)
static void complexapplyreflectionfromtheleft (ref complex[,] c, complex tau, complex[] v, int m1, int m2, int n1, int n2, ref complex[] work)
static void complexapplyreflectionfromtheright (ref complex[,] c, complex tau, ref complex[] v, int m1, int m2, int n1, int n2, ref complex[] work)
Member Function Documentation
complexgeneratereflection() [1/2]
static void alglib.creflections.complexgeneratereflection (ref complex[] x, int n, ref complex tau) inline static
References alglib.math.abscomplex(), alglib.beta(), alglib.math.conj(), alglib.math.maxrealnumber, alglib.math.minrealnumber, alglib.math.sqr(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.testcreflectionsunit.testcreflections().
complexapplyreflectionfromtheleft() [1/2]
static void alglib.creflections.complexapplyreflectionfromtheleft (ref complex c[,], complex tau, complex[] v, int m1, int m2, int n1, int n2, ref complex[] work) inline static
References alglib.math.conj().
Referenced by alglib.ortfac.cmatrixqr(), and alglib.testcreflectionsunit.testcreflections().
complexapplyreflectionfromtheright() [1/2]
static void alglib.creflections.complexapplyreflectionfromtheright (ref complex c[,], complex tau, ref complex[] v, int m1, int m2, int n1, int n2, ref complex[] work) inline static
References alglib.math.conj().
Referenced by alglib.ortfac.cmatrixlq(), and alglib.testcreflectionsunit.testcreflections().
complexgeneratereflection() [2/2]
static void alglib.creflections.complexgeneratereflection (ref complex[] x, int n, ref complex tau) inline static
References alglib.math.abscomplex(), alglib.beta(), alglib.math.conj(), alglib.math.maxrealnumber, alglib.math.minrealnumber, alglib.math.sqr(), alglib.complex.x, and alglib.complex.y.
complexapplyreflectionfromtheleft() [2/2]
static void alglib.creflections.complexapplyreflectionfromtheleft (ref complex c[,], complex tau, complex[] v, int m1, int m2, int n1, int n2, ref complex[] work) inline static
References alglib.math.conj().
complexapplyreflectionfromtheright() [2/2]
static void alglib.creflections.complexapplyreflectionfromtheright (ref complex c[,], complex tau, ref complex[] v, int m1, int m2, int n1, int n2, ref complex[] work) inline static
References alglib.math.conj().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/alglibinternal.cs