Doc: IGLib EXTENDED: IG.Forms.UtilResponseForms Class Reference
IG.Forms.UtilResponseForms Class Reference
Utilities that enable uniform behavior of response plotting forms.
Static Public Member Functions
static string SelectedParameterLabelText (InputOutputDataDefiniton dataDefinition, int parameterId)
Returns axis label text for the specified parameter.
static string SelectedOutputLabelText (InputOutputDataDefiniton dataDefinition, int outputId)
Returns axis label text for the specified output value from the ANN model.
static string SelectedParameterLabelText (InputOutputDataDefiniton dataDefinition, int parameterId)
Returns axis label text for the specified parameter.
static string SelectedOutputLabelText (InputOutputDataDefiniton dataDefinition, int outputId)
Returns axis label text for the specified output value from the ANN model.
static string SelectedParameterLabelText (InputOutputDataDefiniton dataDefinition, int parameterId)
Returns axis label text for the specified parameter.
static string SelectedOutputLabelText (InputOutputDataDefiniton dataDefinition, int outputId)
Returns axis label text for the specified output value from the ANN model.
static string SelectedParameterLabelText (InputOutputDataDefiniton dataDefinition, int parameterId)
Returns axis label text for the specified parameter.
static string SelectedOutputLabelText (InputOutputDataDefiniton dataDefinition, int outputId)
Returns axis label text for the specified output value from the ANN model.
Static Public Attributes
const int DefaultRecommendedMaxLabelLength = 30
Static Protected Attributes
static int _recommendedMaxLabelLength = DefaultRecommendedMaxLabelLength
Properties
static int RecommendedMaxLabelLength [get, set]
Returns recommended maximal length for graph axis labels.
Detailed Description
Utilities that enable uniform behavior of response plotting forms.
Member Function Documentation
SelectedParameterLabelText() [1/4]
static string IG.Forms.UtilResponseForms.SelectedParameterLabelText (InputOutputDataDefiniton dataDefinition, int parameterId) inline static
Returns axis label text for the specified parameter.
Parameters
dataDefinition Data definition used as source of information about input parameters and output values.
parameterId ID (seqential number) of data element for which axis label is returned.
References IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.Name, and IG.Num.InputOutputElementDefinition.Title.
SelectedOutputLabelText() [1/4]
static string IG.Forms.UtilResponseForms.SelectedOutputLabelText (InputOutputDataDefiniton dataDefinition, int outputId) inline static
Returns axis label text for the specified output value from the ANN model.
Parameters
dataDefinition Data definition used as source of information about input parameters and output values.
outputId ID (seqential number) of data element for which axis label is returned.
References IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Num.InputOutputElementDefinition.Name, IG.Num.InputOutputDataDefiniton.OutputLength, and IG.Num.InputOutputElementDefinition.Title.
SelectedParameterLabelText() [2/4]
static string IG.Forms.UtilResponseForms.SelectedParameterLabelText (InputOutputDataDefiniton dataDefinition, int parameterId) inline static
Returns axis label text for the specified parameter.
Parameters
dataDefinition Data definition used as source of information about input parameters and output values.
parameterId ID (seqential number) of data element for which axis label is returned.
References IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.Name, and IG.Num.InputOutputElementDefinition.Title.
SelectedOutputLabelText() [2/4]
static string IG.Forms.UtilResponseForms.SelectedOutputLabelText (InputOutputDataDefiniton dataDefinition, int outputId) inline static
Returns axis label text for the specified output value from the ANN model.
Parameters
dataDefinition Data definition used as source of information about input parameters and output values.
outputId ID (seqential number) of data element for which axis label is returned.
References IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Num.InputOutputElementDefinition.Name, IG.Num.InputOutputDataDefiniton.OutputLength, and IG.Num.InputOutputElementDefinition.Title.
SelectedParameterLabelText() [3/4]
static string IG.Forms.UtilResponseForms.SelectedParameterLabelText (InputOutputDataDefiniton dataDefinition, int parameterId) inline static
Returns axis label text for the specified parameter.
Parameters
dataDefinition Data definition used as source of information about input parameters and output values.
parameterId ID (seqential number) of data element for which axis label is returned.
References IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.Name, and IG.Num.InputOutputElementDefinition.Title.
SelectedOutputLabelText() [3/4]
static string IG.Forms.UtilResponseForms.SelectedOutputLabelText (InputOutputDataDefiniton dataDefinition, int outputId) inline static
Returns axis label text for the specified output value from the ANN model.
Parameters
dataDefinition Data definition used as source of information about input parameters and output values.
outputId ID (seqential number) of data element for which axis label is returned.
References IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Num.InputOutputElementDefinition.Name, IG.Num.InputOutputDataDefiniton.OutputLength, and IG.Num.InputOutputElementDefinition.Title.
SelectedParameterLabelText() [4/4]
static string IG.Forms.UtilResponseForms.SelectedParameterLabelText (InputOutputDataDefiniton dataDefinition, int parameterId) inline static
Returns axis label text for the specified parameter.
Parameters
dataDefinition Data definition used as source of information about input parameters and output values.
parameterId ID (seqential number) of data element for which axis label is returned.
References IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.InputOutputDataDefiniton.InputLength, IG.Num.InputOutputElementDefinition.Name, and IG.Num.InputOutputElementDefinition.Title.
SelectedOutputLabelText() [4/4]
static string IG.Forms.UtilResponseForms.SelectedOutputLabelText (InputOutputDataDefiniton dataDefinition, int outputId) inline static
Returns axis label text for the specified output value from the ANN model.
Parameters
dataDefinition Data definition used as source of information about input parameters and output values.
outputId ID (seqential number) of data element for which axis label is returned.
References IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Num.InputOutputElementDefinition.Name, IG.Num.InputOutputDataDefiniton.OutputLength, and IG.Num.InputOutputElementDefinition.Title.
Member Data Documentation
DefaultRecommendedMaxLabelLength
const int IG.Forms.UtilResponseForms.DefaultRecommendedMaxLabelLength = 30 static
_recommendedMaxLabelLength
static int IG.Forms.UtilResponseForms._recommendedMaxLabelLength = DefaultRecommendedMaxLabelLength static protected
Property Documentation
RecommendedMaxLabelLength
static int IG.Forms.UtilResponseForms.RecommendedMaxLabelLength static get set
Returns recommended maximal length for graph axis labels.
The documentation for this class was generated from the following file:
iglib/extensions/iglibext/Forms/Numeric/UtilResponseFormsExt.cs