Doc: IGLib EXTENDED: IG.Lib.DynamicWrapperBase Class Reference
IG.Lib.DynamicWrapperBase Class Reference
Base class for DynamicWrapper class.
Public Member Functions
virtual object GetArrayElementS (object nodeObject, int arrayIndex)
Returns the specified array element of the currently wrapped element, or null if this object is not an array-lika object.
Static Public Member Functions
static WrapperType CreateArrayWrapperS< WrapperType > ()
Creates and returns a new wrapped object of an appropriate type, which can act as array of objects.
static object CreateStructWrapperS< WrapperType > ()
Creates and returns a new wrapped object of the appropriate type, which can act as a struct containing other objects as named fields.
static object CreateArrayObjectS ()
Creates and returns an obect of the appropriate type, which can act as array (or list) of other objects.
static object CreateStructObjectS< WrapperType > ()
Creates and returns an obect of the appropriate type, which can act struct that contains arbitrary numbe of other objects in as named fields.
static object UnwrapObjectS (DynamicWrapper wrappedObject)
Returns the object that is wrapped by the wrappedObject , or null if wrappedObject is null.
static object UnwrapObjectIfWrappedS (object wrappedOrPlain)
If wrappedOrPlain is a wrapper of type DynamicWrapper or its subtype, this method returns the unwrapped object that it contains, otherwise it returns the wrappedOrPlain itself.
static WrapperType WrapObjectS< WrapperType > (object obj)
Wraps the specified object (obj) in to a dynamic wrapper of type WrapperType and returns the wrapped object.
static bool IsStructS (object nodeObject)
Returns true if the wrapped object implements IDictionary<string, object> interface, meaning that it contains fields addressable by field names, thus behaving like a struct.
static bool IsArrayS (object nodeObject)
Returns true if the wrapped object implements IDictionary interface, meaning that it contains fields addressable by field names, thus behaving like a struct.
static bool IsLeafS (object nodeObject)
Returns true if the currently wrapped object is a leaf object, i.e., it is neither an array object nor a struct-like object.
static int NumStructFieldsS (object nodeObject)
Returns the number of struct fields of the currently wrapped object, or 0 if this object is not a struct-like object with field members.
static int NumArrayElementsS (object nodeObject)
Returns the number of array elements of the currently wrapped object, of 0 if this object is not an array-like object with indexed elements.
static IDictionary< String, object > GetStructElementsS (object nodeObject)
Returns a dictionary of struct elements of the currently wrapped object, or null if this object is not a struct-like object containing named fields.
static ICollection< string > GetStructKeysS (object nodeObject)
Returns a collection of field names of the currently wrapped element, or null if this object is not a struct-like object containing named fields.
static IList< string > GetStrucKeysAsListS (object nodeObject)
Returns a list of field names of the currently wrapped element, or null if this object is not a struct-like object containing named fields.
static IList< object > GetArrayElementsS (object nodeObject)
Returns a list of array elements of the currently wrapped element, or null if this object is not an array-like object containing indexed elements.
static object GetStructElemetS (object nodeObject, string fieldName)
Returns the specified field of the currently wrapped object, or null if this object is not a struct-like object containing named fields.
static string GetReadableJsonStringS (string jsonString)
Returns a re-formatred input JSON string jsonString formated in such a way that it is more readable (with newlines and indentation added).
static string SerializeJsonS (object obj, bool inReadableForm=false)
Serializes the first argument obj into a JSON string and returns that string.
static object DeserializeJsonPlainS (string jsonString)
Deserialized the specified JSON string parameter jsonString into an object and returns that object.
static WrapperType DeserializeJsonS< WrapperType > (string jsonString)
Deserialized the specified JSON string parameter jsonString into an object and returns that object wrapped into a dynamic object wrapper of type WrapperType .
Static Private Attributes
static int MaxJsonLength = (int)1.0e8
Detailed Description
Base class for DynamicWrapper class.
Contains some auxiliary static functions.
$A Igor Nov18;
Member Function Documentation
CreateArrayWrapperS< WrapperType >()
static WrapperType IG.Lib.DynamicWrapperBase.CreateArrayWrapperS< WrapperType > () inline static
Creates and returns a new wrapped object of an appropriate type, which can act as array of objects.
Template Parameters
WrapperType Type of the wrapper class (subtype of DynamicWrapper) of which the returned object is.
Type Constraints
WrapperType : DynamicWrapper
WrapperType : new()
References IG.Lib.DynamicWrapperBase.WrapObjectS< WrapperType >().
Referenced by IG.Lib.DynamicWrapper.CreateArrayWrapper< WrapperType >().
CreateStructWrapperS< WrapperType >()
static object IG.Lib.DynamicWrapperBase.CreateStructWrapperS< WrapperType > () inline static
Creates and returns a new wrapped object of the appropriate type, which can act as a struct containing other objects as named fields.
Template Parameters
WrapperType Type of the wrapper class (subtype of DynamicWrapper) of which the returned object is.
Type Constraints
WrapperType : DynamicWrapper
WrapperType : new()
References IG.Lib.DynamicWrapperBase.WrapObjectS< WrapperType >().
Referenced by IG.Lib.DynamicWrapper.CreateStructWrapper< WrapperType >().
CreateArrayObjectS()
static object IG.Lib.DynamicWrapperBase.CreateArrayObjectS () inline static
Creates and returns an obect of the appropriate type, which can act as array (or list) of other objects.
This is a helper method whose purpose is to ensure uniform typing of objects composing object graphs that are wrapped by wrappers of type DynamicWrapper or its subtypes
Referenced by IG.Lib.DynamicWrapper.CreateArrayObject().
CreateStructObjectS< WrapperType >()
static object IG.Lib.DynamicWrapperBase.CreateStructObjectS< WrapperType > () inline static
Creates and returns an obect of the appropriate type, which can act struct that contains arbitrary numbe of other objects in as named fields.
This is a helper method whose purpose is to ensure uniform types of objects composing object graphs that are wrapped by wrappers of type DynamicWrapper or its subtypes
Type Constraints
WrapperType : DynamicWrapper
WrapperType : new()
Referenced by IG.Lib.DynamicWrapper.CreateStructObject< WrapperType >().
UnwrapObjectS()
static object IG.Lib.DynamicWrapperBase.UnwrapObjectS (DynamicWrapper wrappedObject) inline static
Returns the object that is wrapped by the wrappedObject , or null if wrappedObject is null.
UnwrapObjectS(wrapper) is equivalent to wrapper.GetObject(), except when wrapper==null, in which case the later expression would throw exception while the first one returns null.
Parameters
wrappedObject Object that whose internal unwrapped object is returned.
References IG.Lib.DynamicWrapper.GetObject().
Referenced by IG.Lib.DynamicWrapper.ExampleElementReferencing(), IG.Lib.DynamicWrapperBase.SerializeJsonS(), and IG.Lib.DynamicWrapperBase.WrapObjectS< WrapperType >().
UnwrapObjectIfWrappedS()
static object IG.Lib.DynamicWrapperBase.UnwrapObjectIfWrappedS (object wrappedOrPlain) inline static
If wrappedOrPlain is a wrapper of type DynamicWrapper or its subtype, this method returns the unwrapped object that it contains, otherwise it returns the wrappedOrPlain itself.
Parameters
wrappedOrPlain Object that is unwrapped (when applicable) and returned.
References IG.Lib.DynamicWrapper.GetObject().
Referenced by IG.Lib.DynamicWrapper.ExampleElementReferencing(), and IG.Lib.DynamicWrapper.UnwrapObjectIfWrapped().
WrapObjectS< WrapperType >()
static WrapperType IG.Lib.DynamicWrapperBase.WrapObjectS< WrapperType > (object obj) inline static
Wraps the specified object (obj) in to a dynamic wrapper of type WrapperType and returns the wrapped object.
Template Parameters
WrapperType Type of the dynamic wrapper into which object is wrapped.
Parameters
obj
Type Constraints
WrapperType : DynamicWrapper
WrapperType : new()
References IG.Lib.DynamicWrapperBase.UnwrapObjectS().
Referenced by IG.Lib.DynamicWrapperBase.CreateArrayWrapperS< WrapperType >(), IG.Lib.DynamicWrapperBase.CreateStructWrapperS< WrapperType >(), IG.Lib.DynamicWrapperBase.DeserializeJsonS< WrapperType >(), and IG.Lib.DynamicWrapper.WrapObject< WrapperType >().
IsStructS()
static bool IG.Lib.DynamicWrapperBase.IsStructS (object nodeObject) inline static
Returns true if the wrapped object implements IDictionary<string, object> interface, meaning that it contains fields addressable by field names, thus behaving like a struct.
Parameters
nodeObject Object on which the method operates. It should be a node in an object graph used in DynamicWrapper and its derived classes.
Returns
True if wrapped object behaves like struct and implements IDIctionary interface.
Referenced by IG.Lib.DynamicWrapperBase.IsLeafS().
IsArrayS()
static bool IG.Lib.DynamicWrapperBase.IsArrayS (object nodeObject) inline static
Returns true if the wrapped object implements IDictionary interface, meaning that it contains fields addressable by field names, thus behaving like a struct.
Parameters
nodeObject Object on which the method operates. It should be a node in an object graph used in DynamicWrapper and its derived classes.
Returns
True if wrapped object behaves like struct and implements IDIctionary interface.
Referenced by IG.Lib.DynamicWrapperBase.IsLeafS().
IsLeafS()
static bool IG.Lib.DynamicWrapperBase.IsLeafS (object nodeObject) inline static
Returns true if the currently wrapped object is a leaf object, i.e., it is neither an array object nor a struct-like object.
Parameters
nodeObject Object on which the method operates. It should be a node in an object graph used in DynamicWrapper and its derived classes.
References IG.Lib.DynamicWrapperBase.IsArrayS(), and IG.Lib.DynamicWrapperBase.IsStructS().
NumStructFieldsS()
static int IG.Lib.DynamicWrapperBase.NumStructFieldsS (object nodeObject) inline static
Returns the number of struct fields of the currently wrapped object, or 0 if this object is not a struct-like object with field members.
Parameters
nodeObject Object on which the method operates. It should be a node in an object graph used in DynamicWrapper and its derived classes.
NumArrayElementsS()
static int IG.Lib.DynamicWrapperBase.NumArrayElementsS (object nodeObject) inline static
Returns the number of array elements of the currently wrapped object, of 0 if this object is not an array-like object with indexed elements.
Parameters
nodeObject Object on which the method operates. It should be a node in an object graph used in DynamicWrapper and its derived classes.
GetStructElementsS()
static IDictionary<String, object> IG.Lib.DynamicWrapperBase.GetStructElementsS (object nodeObject) inline static
Returns a dictionary of struct elements of the currently wrapped object, or null if this object is not a struct-like object containing named fields.
Parameters
nodeObject Object on which the method operates. It should be a node in an object graph used in DynamicWrapper and its derived classes.
Referenced by IG.Lib.DynamicWrapperBase.GetStructKeysS().
GetStructKeysS()
static ICollection<string> IG.Lib.DynamicWrapperBase.GetStructKeysS (object nodeObject) inline static
Returns a collection of field names of the currently wrapped element, or null if this object is not a struct-like object containing named fields.
Parameters
nodeObject Object on which the method operates. It should be a node in an object graph used in DynamicWrapper and its derived classes.
References IG.Lib.DynamicWrapperBase.GetStructElementsS().
Referenced by IG.Lib.DynamicWrapperBase.GetStrucKeysAsListS().
GetStrucKeysAsListS()
static IList<string> IG.Lib.DynamicWrapperBase.GetStrucKeysAsListS (object nodeObject) inline static
Returns a list of field names of the currently wrapped element, or null if this object is not a struct-like object containing named fields.
Parameters
nodeObject Object on which the method operates. It should be a node in an object graph used in DynamicWrapper and its derived classes.
References IG.Lib.DynamicWrapperBase.GetStructKeysS().
GetArrayElementsS()
static IList<object> IG.Lib.DynamicWrapperBase.GetArrayElementsS (object nodeObject) inline static
Returns a list of array elements of the currently wrapped element, or null if this object is not an array-like object containing indexed elements.
Parameters
nodeObject Object on which the method operates. It should be a node in an object graph used in DynamicWrapper and its derived classes.
GetStructElemetS()
static object IG.Lib.DynamicWrapperBase.GetStructElemetS (object nodeObject, string fieldName) inline static
Returns the specified field of the currently wrapped object, or null if this object is not a struct-like object containing named fields.
Parameters
nodeObject Object on which the method operates. It should be a node in an object graph used in DynamicWrapper and its derived classes.
fieldName Name of the field of a struct-like object to be returned.
GetArrayElementS()
virtual object IG.Lib.DynamicWrapperBase.GetArrayElementS (object nodeObject, int arrayIndex) inline virtual
Returns the specified array element of the currently wrapped element, or null if this object is not an array-lika object.
Parameters
nodeObject Object on which the method operates. It should be a node in an object graph used in DynamicWrapper and its derived classes.
arrayIndex Index of the array element to be returned.
GetReadableJsonStringS()
static string IG.Lib.DynamicWrapperBase.GetReadableJsonStringS (string jsonString) inline static
Returns a re-formatred input JSON string jsonString formated in such a way that it is more readable (with newlines and indentation added).
Parameters
jsonString JSON string that is re-formatted.
Referenced by IG.Test.Json.Main_JsonBasic(), and IG.Lib.DynamicWrapperBase.SerializeJsonS().
SerializeJsonS()
static string IG.Lib.DynamicWrapperBase.SerializeJsonS (object obj, bool inReadableForm = false) inline static
Serializes the first argument obj into a JSON string and returns that string.
If obj is wrapped by DynamicWrapper or one of its derived clases then it is first unwrapped before serialization takes place.
Parameters
obj Object to be serialized.
inReadableForm If true then the returned JSON string is formatted (with indentation and line breaks added) in such a way that it is more readable.
Returns
Returns the Json string representing the object.
References IG.Lib.DynamicWrapperBase.GetReadableJsonStringS(), IG.Lib.DynamicWrapperBase.MaxJsonLength, and IG.Lib.DynamicWrapperBase.UnwrapObjectS().
Referenced by IG.Lib.DynamicWrapper.ExampleJsonSerializationOrSpeedTest(), and IG.Lib.DynamicWrapper.SerializeJson().
DeserializeJsonPlainS()
static object IG.Lib.DynamicWrapperBase.DeserializeJsonPlainS (string jsonString) inline static
Deserialized the specified JSON string parameter jsonString into an object and returns that object.
Parameters
jsonString JSON string from which the returned object is deserialized.
Returns
References IG.Lib.DynamicWrapperBase.MaxJsonLength.
Referenced by IG.Lib.DynamicWrapper.DeserializeJsonPlain(), and IG.Lib.DynamicWrapperBase.DeserializeJsonS< WrapperType >().
DeserializeJsonS< WrapperType >()
static WrapperType IG.Lib.DynamicWrapperBase.DeserializeJsonS< WrapperType > (string jsonString) inline static
Deserialized the specified JSON string parameter jsonString into an object and returns that object wrapped into a dynamic object wrapper of type WrapperType .
Template Parameters
WrapperType generic parameter specifying the type of the wrapper object by which the deseralized object is wrapped.
Parameters
jsonString String from which the object is deserialized.
Returns
Deserialized object (from the specified JSON string) wrapped into the dynamic object wrapper of type
Template Parameters
WrapperType
Type Constraints
WrapperType : DynamicWrapper
WrapperType : new()
References IG.Lib.DynamicWrapperBase.DeserializeJsonPlainS(), and IG.Lib.DynamicWrapperBase.WrapObjectS< WrapperType >().
Referenced by IG.Lib.DynamicWrapper.DeserializeJson< WrapperType >().
Member Data Documentation
MaxJsonLength
int IG.Lib.DynamicWrapperBase.MaxJsonLength = (int)1.0e8 static private
Referenced by IG.Lib.DynamicWrapperBase.DeserializeJsonPlainS(), and IG.Lib.DynamicWrapperBase.SerializeJsonS().
The documentation for this class was generated from the following file:
unittests/Guest_IGTestQuick/DynamicWrapper/DynamicWrapperBase.cs