Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DSTERF Class Reference
DotNumerics.LinearAlgebra.CSLapack.DSTERF Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DSTERF (DLAMCH dlamch, DLANST dlanst, DLAPY2 dlapy2, DLAE2 dlae2, DLASCL dlascl, DLASRT dlasrt, XERBLA xerbla)
DSTERF ()
void Run (int N, ref double[] D, int offset_d, ref double[] E, int offset_e, ref int INFO)
Private Attributes
DLAMCH _dlamch
DLANST _dlanst
DLAPY2 _dlapy2
DLAE2 _dlae2
DLASCL _dlascl
DLASRT _dlasrt
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
const double TWO = 2.0E0
const double THREE = 3.0E0
const int MAXIT = 30
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DSTERF computes all eigenvalues of a symmetric tridiagonal matrix using the Pal-Walker-Kahan variant of the QL or QR algorithm.
/summary>
Constructor & Destructor Documentation
DSTERF() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DSTERF.DSTERF (DLAMCH dlamch, DLANST dlanst, DLAPY2 dlapy2, DLAE2 dlae2, DLASCL dlascl, DLASRT dlasrt, XERBLA xerbla) inline
DSTERF() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DSTERF.DSTERF () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DSTERF.Run (int N, ref double[] D, int offset_d, ref double[] E, int offset_e, ref int INFO) inline
Purpose
DSTERF computes all eigenvalues of a symmetric tridiagonal matrix using the Pal-Walker-Kahan variant of the QL or QR algorithm.
/summary>
Parameters
N (input) INTEGER The order of the matrix. N .GE. 0. /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension (N) On entry, the n diagonal elements of the tridiagonal matrix. On exit, if INFO = 0, the eigenvalues in ascending order. /param>
Parameters
E (input/output) DOUBLE PRECISION array, dimension (N-1) On entry, the (n-1) subdiagonal elements of the tridiagonal matrix. On exit, E has been destroyed. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value .GT. 0: the algorithm failed to find all of the eigenvalues in a total of 30*N iterations; if INFO = i, then i elements of E have not converged to zero. /param>
References DotNumerics.LinearAlgebra.CSLapack.DSTERF.MAXIT, DotNumerics.LinearAlgebra.CSLapack.DSTERF.ONE, DotNumerics.LinearAlgebra.CSLapack.DLAPY2.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAE2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASRT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANST.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.FortranLibrary.FortranLib.Sign(), DotNumerics.LinearAlgebra.CSLapack.DSTERF.THREE, DotNumerics.LinearAlgebra.CSLapack.DSTERF.TWO, and DotNumerics.LinearAlgebra.CSLapack.DSTERF.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSBEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEDC.Run(), DotNumerics.LinearAlgebra.CSLapack.DSBEVD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DSYEVD.Run().
Member Data Documentation
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DSTERF._dlamch private
_dlanst
DLANST DotNumerics.LinearAlgebra.CSLapack.DSTERF._dlanst private
_dlapy2
DLAPY2 DotNumerics.LinearAlgebra.CSLapack.DSTERF._dlapy2 private
_dlae2
DLAE2 DotNumerics.LinearAlgebra.CSLapack.DSTERF._dlae2 private
_dlascl
DLASCL DotNumerics.LinearAlgebra.CSLapack.DSTERF._dlascl private
_dlasrt
DLASRT DotNumerics.LinearAlgebra.CSLapack.DSTERF._dlasrt private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DSTERF._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DSTERF.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTERF.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DSTERF.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTERF.Run().
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DSTERF.TWO = 2.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTERF.Run().
THREE
const double DotNumerics.LinearAlgebra.CSLapack.DSTERF.THREE = 3.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTERF.Run().
MAXIT
const int DotNumerics.LinearAlgebra.CSLapack.DSTERF.MAXIT = 30 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTERF.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dsterf.cs