Doc: IGLib EXTENDED: IG.Num.IVectorApproximator Interface Reference
IG.Num.IVectorApproximator Interface Reference
Interface for vector function approximators.
Public Member Functions
void CalculateOutput (IVector input, ref IVector output)
Calculates and returns the approximated outputs corresponding to the specified inputs, by using the current vector function approximator.
double CalculateOutput (IVector input, int whichElement)
Calculates and returns the specified output by using the current vector function approximator.
void CalculateOutput (IVector input, int[] indices, ref IVector filteredOutput)
Calculates and returns the required output values corresponding to the specified inputs, by using the current vector function approximator.
Properties
int InputLength [get, set]
Gets or sets the number of input parameters.
int OutputLength [get, set]
Gets or sets the number of output values.
Detailed Description
Interface for vector function approximators.
Member Function Documentation
CalculateOutput() [1/3]
void IG.Num.IVectorApproximator.CalculateOutput (IVector input, ref IVector output)
Calculates and returns the approximated outputs corresponding to the specified inputs, by using the current vector function approximator.
Parameters
input Input parameters.
output Output values.
Returns
Vector of output values generated by the approximator.
Currently, only all outputs at once can be calculated. This makes no difference in the arrangement with a single network with multiple outputs, but does when several networks with single output each are used. If the implementation changes in the future then performance configuratins should be taken into account carefully, and tracking input for which input parameters the outputs have been calculated might be necessary.
Implemented in IG.Neural.NeuralApproximatorNeuron, IG.Neural.NeuralApproximatorAforge, IG.Num.NeuralApproximatorAforgeFake, and IG.Num.VectorApproximatorBase.
Referenced by IG.Neural.NeuralNetworks.Approximate(), IG.Neural.Forms.NeuralPredictionControl.btnPredict_Click(), IG.Neural.Forms.Old.NeuralParametricDemoOldCopy.btnPredict_Click(), IG.Neural.Forms.Old.NeuralParametricDemoOld.btnPredict_Click(), IG.Script.LoadableScriptShellNeuralIT.CalculateSensitivity(), IG.Script.S_12_02_paper_neural_process_chain_model.CalculateTrainingError(), IG.Script.LoadableScriptShellNeuralIT.CalculateTrainingError(), IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00.CalculateVectorResponse(), IG.Script.S_12_02_paper_neural_process_chain_model.CalculateVerificationError(), IG.Script.LoadableScriptShellNeuralIT.CalculateVerificationError(), IG.Script.LoadableScriptShellNeuralITOriginalBase.CreateDistortedModelData(), IG.Script.LoadableScriptShellNeuralBase.CreateDistortedModelData(), IG.Script.S_12_01_Paper_NeuralOptCasting_IJS_00.ExampleCalculateNeuralResponses(), IG.Neural.NeuralTadej.ExampleCasting(), Test_Tadej.ProgramTestTadejApp.ExamplePredictNetwork(), IG.Neural.NeuralTadej.ExampleQuadratic(), IG.Script.Script_11_10_clanek_neural_01.NeuralCalculate(), IG.Script.LoadableScriptShellNeuralITOriginalBase.NeuralCalculate(), IG.Script.LoadableScriptShellNeuralBase.NeuralCalculate(), IG.Script.LoadableScriptShellNeuralIT.PlotNetworkResponseGrouped(), IG.Script.LoadableScriptShellNeuralIT.PlotNeuralResponse(), IG.Neural.Forms.NeuralParametricTest.PlotParametricTest(), IG.Neural.Forms.NeuralParametricTestMultiple.PlotParametricTest(), IG.Neural.Forms.Old.NeuralParametricTestOld.PlotParametricTest(), IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTest(), IG.Neural.Forms.NeuralParametricTest2d.PlotParametricTestZedGraph(), IG.Neural.Forms.Old.NeuralParametricDemoOld.PlotRandTrainingAndVerificationPointsResponse(), IG.Script.S_12_02_paper_neural_process_chain_model.PlotResponseOnLine(), IG.Script.LoadableScriptShellNeuralIT.PlotTrainingAndVerificationPointResponse(), IG.Script.S_13_5_Convection.PlotTrainingAndVerificationPointResponse2D(), IG.Neural.Forms.Old.NeuralParametricDemoOldCopy.PlotTrainingAndVerificationPointsResponse(), IG.Neural.Forms.Old.NeuralParametricDemoOld.PlotTrainingAndVerificationPointsResponse(), IG.Script.S_12_02_paper_neural_process_chain_model.PlotTrainingAndVerificationPointsResponse(), IG.Script.LoadableScriptShellNeuralIT.PlotTrainingAndVerificationPointsResponse(), IG.Script.S_12_02_paper_neural_process_chain_model.PlotVerificationPointsResponse(), IG.Neural.Applications.DemoNeuralOld.PredictFromApproximator(), IG.Neural.Forms.NeuralDemo1D.PredictFromApproximator(), IG.Neural.Forms.Old.FormNeural1DOld.Prediction(), IG.Script.Script_11_10_clanek_neural_01.TestNeuralSpeed(), IG.Script.LoadableScriptShellNeuralBase.TestNeuralSpeed(), IG.Script.LoadableScriptShellNeuralITOriginalBase.TestNeuralSpeed(), IG.Neural.ProgramTestTadej.TestPrediction(), IG.Script.LoadableScriptShellNeuralITOriginalBase.TrainANN(), IG.Script.LoadableScriptShellNeuralBase.TrainANN(), and IG.Neural.Func2dFromApproximator.Value().
CalculateOutput() [2/3]
double IG.Num.IVectorApproximator.CalculateOutput (IVector input, int whichElement)
Calculates and returns the specified output by using the current vector function approximator.
Implemented in IG.Num.NeuralApproximatorBase, IG.Num.VectorApproximatorBase, and IG.Num.NeuralApproximatorAforgeFake.
CalculateOutput() [3/3]
void IG.Num.IVectorApproximator.CalculateOutput (IVector input, int[] indices, ref IVector filteredOutput)
Calculates and returns the required output values corresponding to the specified inputs, by using the current vector function approximator.
Parameters
input Input parameters for which output values are calculated.
indices Array of indices of the output values to be returned.
filteredOutput Vector where filtered output values are stored.
Implemented in IG.Num.NeuralApproximatorBase, IG.Num.VectorApproximatorBase, and IG.Num.NeuralApproximatorAforgeFake.
Property Documentation
InputLength
int IG.Num.IVectorApproximator.InputLength get set
Gets or sets the number of input parameters.
Referenced by IG.Neural.Forms.Old.NeuralParametricDemoOldCopy.btnParmTestClearAll_Click(), IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestClearAll_Click(), IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestClearAllRand_Click(), IG.Neural.Forms.Old.NeuralParametricDemoOldCopy.btnParmTestSelectAll_Click(), IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestSelectAll_Click(), IG.Neural.Forms.Old.NeuralParametricDemoOld.btnParmTestSelectAllRand_Click(), IG.Num.NeuralApproximatorDtoBase< NeuralApproximatorAforgeFake >.CopyFromPlain(), IG.Neural.Forms.Old.NeuralParametricDemoOldCopy.dGridInputParam_CellValueChanged(), IG.Neural.Forms.Old.NeuralParametricDemoOld.dGridInputParam_CellValueChanged(), IG.Neural.Forms.Old.NeuralParametricDemoOldCopy.dGridParmTestInputParam_CellValueChanged(), IG.Neural.Forms.Old.NeuralParametricDemoOld.dGridParmTestInputParam_CellValueChanged(), IG.Neural.NeuralTadej.ExampleCasting(), Test_Tadej.ProgramTestTadejApp.ExamplePredictNetwork(), IG.Neural.NeuralTadej.ExampleQuadratic(), IG.Neural.Forms.Old.NeuralParametricDemoOldCopy.GenerateANNPredictionInfoGrid(), IG.Neural.Forms.Old.NeuralParametricDemoOld.GenerateANNPredictionInfoGrid(), IG.Script.Script_11_10_clanek_neural_01.GetNeuralInputPerturbance(), IG.Script.LoadableScriptShellNeuralITOriginalBase.GetNeuralInputPerturbance(), IG.Script.LoadableScriptShellNeuralBase.GetNeuralInputPerturbance(), IG.Script.Script_11_10_clanek_neural_01.GetNeuralInputVector(), IG.Script.LoadableScriptShellNeuralITOriginalBase.GetNeuralInputVector(), IG.Script.LoadableScriptShellNeuralBase.GetNeuralInputVector(), IG.Script.LoadableScriptShellNeuralITOriginalBase.GetRandomNeuralInputFromDataDefinition(), IG.Script.LoadableScriptShellNeuralBase.GetRandomNeuralInputFromDataDefinition(), IG.Script.Script_11_10_clanek_neural_01.NeuralCalculate(), IG.Script.LoadableScriptShellNeuralITOriginalBase.NeuralCalculate(), IG.Script.LoadableScriptShellNeuralBase.NeuralCalculate(), IG.Neural.Forms.Old.NeuralParametricDemoOldCopy.PrepareTrainingAndVerificationData(), IG.Neural.Forms.Old.NeuralParametricDemoOld.PrepareTrainingAndVerificationData(), IG.Neural.NeuralTadej.StoreNetwork(), IG.Script.LoadableScriptShellNeuralITOriginalBase.TrainANN(), IG.Script.LoadableScriptShellNeuralBase.TrainANN(), IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork(), and IG.App.TadejFormOldObsolete.TranscribeDataToNetwork().
OutputLength
int IG.Num.IVectorApproximator.OutputLength get set
Gets or sets the number of output values.
Referenced by IG.Neural.NeuralNetworks.Approximate(), IG.Neural.Forms.Old.FormNeural1DOld.CalculateError(), IG.Num.NeuralApproximatorDtoBase< NeuralApproximatorAforgeFake >.CopyFromPlain(), IG.Neural.NeuralTadej.ExampleCasting(), IG.Neural.NeuralTadej.ExampleQuadratic(), Test_Tadej.ProgramTestTadejApp.ExampleSaveCastingNetwork(), IG.Num.NeuralApproximatorBase.ExampleSaveNetwork(), Test_Tadej.ProgramTestTadejApp.ExampleSaveStoreNetwork(), IG.Neural.Forms.Old.NeuralParametricDemoOldCopy.GenerateANNPredictionInfoGrid(), IG.Neural.Forms.Old.NeuralParametricDemoOld.GenerateANNPredictionInfoGrid(), IG.Script.Script_11_10_clanek_neural_01.GetNeuralOutputPerturbance(), IG.Script.LoadableScriptShellNeuralITOriginalBase.GetNeuralOutputPerturbance(), IG.Script.LoadableScriptShellNeuralBase.GetNeuralOutputPerturbance(), IG.Script.LoadableScriptShellNeuralITOriginalBase.GetRandomNeuralOutput(), IG.Script.LoadableScriptShellNeuralBase.GetRandomNeuralOutput(), IG.Script.Script_11_10_clanek_neural_01.NeuralCalculate(), IG.Script.LoadableScriptShellNeuralITOriginalBase.NeuralCalculate(), IG.Script.LoadableScriptShellNeuralBase.NeuralCalculate(), IG.Neural.Forms.Old.NeuralParametricDemoOldCopy.ParmTestPrepareGraphs(), IG.Neural.Forms.Old.NeuralParametricDemoOld.ParmTestPrepareGraphs(), IG.Neural.Forms.Old.NeuralParametricDemoOld.ParmTestRandPrepareGraphs(), IG.Neural.Forms.Old.FormNeural1DOld.Prediction(), IG.Neural.Forms.Old.NeuralParametricDemoOldCopy.PrepareTrainingAndVerificationData(), IG.Neural.Forms.Old.NeuralParametricDemoOld.PrepareTrainingAndVerificationData(), IG.Neural.ProgramTestTadej.SaveNetworkNeuron(), IG.Script.LoadableScriptShellNeuralBase.SaveSensitivityCSV(), IG.Script.LoadableScriptShellNeuralITOriginalBase.SaveSensitivityCSV(), IG.Neural.NeuralTadej.StoreNetwork(), IG.Script.Script_11_10_clanek_neural_01.TestNeuralSpeed(), IG.Script.LoadableScriptShellNeuralBase.TestNeuralSpeed(), IG.Script.LoadableScriptShellNeuralITOriginalBase.TestNeuralSpeed(), IG.Neural.ProgramTestTadej.TestPrediction(), IG.Script.LoadableScriptShellNeuralITOriginalBase.TrainANN(), IG.Script.LoadableScriptShellNeuralBase.TrainANN(), IG.Neural.Applications.TadejFormOld.TranscribeDataToNetwork(), and IG.App.TadejFormOldObsolete.TranscribeDataToNetwork().
The documentation for this interface was generated from the following file:
iglib/igbase/numeric/approximation/IVectorApproximator.cs