Doc: IGLib EXTENDED: AForge.Vision.Motion.CustomFrameDifferenceDetector Class Reference
AForge.Vision.Motion.CustomFrameDifferenceDetector Class Reference
Motion detector based on difference with predefined background frame.
Public Member Functions
CustomFrameDifferenceDetector ()
Initializes a new instance of the CustomFrameDifferenceDetector class.
CustomFrameDifferenceDetector (bool suppressNoise)
Initializes a new instance of the CustomFrameDifferenceDetector class.
CustomFrameDifferenceDetector (bool suppressNoise, bool keepObjectEdges)
Initializes a new instance of the CustomFrameDifferenceDetector class.
unsafe void ProcessFrame (UnmanagedImage videoFrame)
Process new video frame.
void Reset ()
Reset motion detector to initial state.
void SetBackgroundFrame (Bitmap backgroundFrame)
Set background frame.
void SetBackgroundFrame (BitmapData backgroundFrame)
Set background frame.
void SetBackgroundFrame (UnmanagedImage backgroundFrame)
Set background frame.
Properties
int DifferenceThreshold [get, set]
Difference threshold value, [1, 255].
float MotionLevel [get]
Motion level value, [0, 1].
UnmanagedImage MotionFrame [get]
Motion frame containing detected areas of motion.
bool SuppressNoise [get, set]
Suppress noise in video frames or not.
bool KeepObjectsEdges [get, set]
Restore objects edges after noise suppression or not.
Properties inherited from AForge.Vision.Motion.IMotionDetector
float MotionLevel [get]
Motion level value, [0, 1].
UnmanagedImage MotionFrame [get]
Motion frame containing detected areas of motion.
Private Member Functions
void Reset (bool force)
Private Attributes
int width
int height
int frameSize
UnmanagedImage backgroundFrame
UnmanagedImage motionFrame
UnmanagedImage tempFrame
int pixelsChanged
bool manuallySetBackgroundFrame = false
bool suppressNoise = true
bool keepObjectEdges = false
int differenceThreshold = 15
int differenceThresholdNeg = -15
BinaryErosion3x3 erosionFilter = new BinaryErosion3x3()
BinaryDilatation3x3 dilatationFilter = new BinaryDilatation3x3()
object sync = new object()
Detailed Description
Motion detector based on difference with predefined background frame.
The class implements motion detection algorithm, which is based on difference of current video frame with predefined background frame. The difference frame is thresholded and the amount of difference pixels is calculated. To suppress stand-alone noisy pixels erosion morphological operator may be applied, which is controlled by SuppressNoise property.
<note>In the case if precise motion area's borders are required (for example, for further motion post processing), then KeepObjectsEdges property may be used to restore borders after noise suppression.</note>
<note>In the case if custom background frame is not specified by using SetBackgroundFrame(Bitmap) method, the algorithm takes first video frame as a background frame and calculates difference of further video frames with it.</note>
Unlike TwoFramesDifferenceDetector motion detection algorithm, this algorithm allows to identify quite clearly all objects, which are not part of the background (scene) - most likely moving objects.
Sample usage:
// create motion detector
MotionDetector detector = new MotionDetector(
    new CustomFrameDifferenceDetector( ),
    new MotionAreaHighlighting( ) );
// continuously feed video frames to motion detector
while (...)
{
    // process new video frame and check motion level
    if ( detector.ProcessFrame( videoFrame ) > 0.02 )
    {
        // ring alarm or do somethng else
    }
}
See also
MotionDetector
Constructor & Destructor Documentation
CustomFrameDifferenceDetector() [1/3]
AForge.Vision.Motion.CustomFrameDifferenceDetector.CustomFrameDifferenceDetector () inline
Initializes a new instance of the CustomFrameDifferenceDetector class.
CustomFrameDifferenceDetector() [2/3]
AForge.Vision.Motion.CustomFrameDifferenceDetector.CustomFrameDifferenceDetector (bool suppressNoise) inline
Initializes a new instance of the CustomFrameDifferenceDetector class.
Parameters
suppressNoise Suppress noise in video frames or not (see SuppressNoise property).
References AForge.Vision.Motion.CustomFrameDifferenceDetector.suppressNoise.
CustomFrameDifferenceDetector() [3/3]
AForge.Vision.Motion.CustomFrameDifferenceDetector.CustomFrameDifferenceDetector (bool suppressNoise, bool keepObjectEdges) inline
Initializes a new instance of the CustomFrameDifferenceDetector class.
Parameters
suppressNoise Suppress noise in video frames or not (see SuppressNoise property).
keepObjectEdges Restore objects edges after noise suppression or not (see KeepObjectsEdges property).
References AForge.Vision.Motion.CustomFrameDifferenceDetector.keepObjectEdges, and AForge.Vision.Motion.CustomFrameDifferenceDetector.suppressNoise.
Member Function Documentation
ProcessFrame()
unsafe void AForge.Vision.Motion.CustomFrameDifferenceDetector.ProcessFrame (UnmanagedImage videoFrame) inline
Process new video frame.
Parameters
videoFrame Video frame to process (detect motion in).
Processes new frame from video source and detects motion in it.
Check MotionLevel property to get information about amount of motion (changes) in the processed frame.
Implements AForge.Vision.Motion.IMotionDetector.
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.Apply(), AForge.Vision.Motion.CustomFrameDifferenceDetector.backgroundFrame, AForge.SystemTools.CopyUnmanagedMemory(), AForge.Imaging.UnmanagedImage.Create(), AForge.Vision.Motion.CustomFrameDifferenceDetector.differenceThreshold, AForge.Vision.Motion.CustomFrameDifferenceDetector.differenceThresholdNeg, AForge.Vision.Motion.CustomFrameDifferenceDetector.dilatationFilter, AForge.Vision.Motion.CustomFrameDifferenceDetector.erosionFilter, AForge.Vision.Motion.CustomFrameDifferenceDetector.frameSize, AForge.Vision.Motion.CustomFrameDifferenceDetector.height, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Vision.Motion.CustomFrameDifferenceDetector.keepObjectEdges, AForge.Vision.Motion.CustomFrameDifferenceDetector.motionFrame, AForge.Vision.Motion.CustomFrameDifferenceDetector.pixelsChanged, AForge.Imaging.UnmanagedImage.Stride, AForge.Vision.Motion.CustomFrameDifferenceDetector.suppressNoise, AForge.Vision.Motion.CustomFrameDifferenceDetector.sync, AForge.Vision.Motion.CustomFrameDifferenceDetector.tempFrame, AForge.Vision.Motion.CustomFrameDifferenceDetector.width, and AForge.Imaging.UnmanagedImage.Width.
Reset() [1/2]
void AForge.Vision.Motion.CustomFrameDifferenceDetector.Reset () inline
Reset motion detector to initial state.
Resets internal state and variables of motion detection algorithm. Usually this is required to be done before processing new video source, but may be also done at any time to restart motion detection algorithm.
<note>In the case if custom background frame was set using SetBackgroundFrame(Bitmap) method, this method does not reset it. The method resets only automatically generated background frame. </note>
Implements AForge.Vision.Motion.IMotionDetector.
Referenced by AForge.Vision.Motion.CustomFrameDifferenceDetector.SetBackgroundFrame().
Reset() [2/2]
void AForge.Vision.Motion.CustomFrameDifferenceDetector.Reset (bool force) inline private
References AForge.Vision.Motion.CustomFrameDifferenceDetector.backgroundFrame, AForge.Imaging.UnmanagedImage.Dispose(), AForge.Vision.Motion.CustomFrameDifferenceDetector.manuallySetBackgroundFrame, AForge.Vision.Motion.CustomFrameDifferenceDetector.motionFrame, AForge.Vision.Motion.CustomFrameDifferenceDetector.sync, and AForge.Vision.Motion.CustomFrameDifferenceDetector.tempFrame.
SetBackgroundFrame() [1/3]
void AForge.Vision.Motion.CustomFrameDifferenceDetector.SetBackgroundFrame (Bitmap backgroundFrame) inline
Set background frame.
Parameters
backgroundFrame Background frame to set.
The method sets background frame, which will be used to calculate difference with.
References AForge.Vision.Motion.CustomFrameDifferenceDetector.backgroundFrame, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Math.Geometry.Rectangle, and AForge.Imaging.UnmanagedImage.Width.
Referenced by AForge.Vision.Motion.CustomFrameDifferenceDetector.SetBackgroundFrame().
SetBackgroundFrame() [2/3]
void AForge.Vision.Motion.CustomFrameDifferenceDetector.SetBackgroundFrame (BitmapData backgroundFrame) inline
Set background frame.
Parameters
backgroundFrame Background frame to set.
The method sets background frame, which will be used to calculate difference with.
References AForge.Vision.Motion.CustomFrameDifferenceDetector.backgroundFrame, and AForge.Vision.Motion.CustomFrameDifferenceDetector.SetBackgroundFrame().
SetBackgroundFrame() [3/3]
void AForge.Vision.Motion.CustomFrameDifferenceDetector.SetBackgroundFrame (UnmanagedImage backgroundFrame) inline
Set background frame.
Parameters
backgroundFrame Background frame to set.
The method sets background frame, which will be used to calculate difference with.
References AForge.Vision.Motion.CustomFrameDifferenceDetector.backgroundFrame, AForge.Imaging.UnmanagedImage.Create(), AForge.Vision.Motion.CustomFrameDifferenceDetector.frameSize, AForge.Vision.Motion.CustomFrameDifferenceDetector.height, AForge.Imaging.UnmanagedImage.Height, AForge.Vision.Motion.CustomFrameDifferenceDetector.manuallySetBackgroundFrame, AForge.Vision.Motion.CustomFrameDifferenceDetector.Reset(), AForge.Imaging.UnmanagedImage.Stride, AForge.Vision.Motion.CustomFrameDifferenceDetector.sync, AForge.Vision.Motion.CustomFrameDifferenceDetector.width, and AForge.Imaging.UnmanagedImage.Width.
Member Data Documentation
width
int AForge.Vision.Motion.CustomFrameDifferenceDetector.width private
Referenced by AForge.Vision.Motion.CustomFrameDifferenceDetector.ProcessFrame(), and AForge.Vision.Motion.CustomFrameDifferenceDetector.SetBackgroundFrame().
height
int AForge.Vision.Motion.CustomFrameDifferenceDetector.height private
Referenced by AForge.Vision.Motion.CustomFrameDifferenceDetector.ProcessFrame(), and AForge.Vision.Motion.CustomFrameDifferenceDetector.SetBackgroundFrame().
frameSize
int AForge.Vision.Motion.CustomFrameDifferenceDetector.frameSize private
Referenced by AForge.Vision.Motion.CustomFrameDifferenceDetector.ProcessFrame(), and AForge.Vision.Motion.CustomFrameDifferenceDetector.SetBackgroundFrame().
backgroundFrame
UnmanagedImage AForge.Vision.Motion.CustomFrameDifferenceDetector.backgroundFrame private
Referenced by AForge.Vision.Motion.CustomFrameDifferenceDetector.ProcessFrame(), AForge.Vision.Motion.CustomFrameDifferenceDetector.Reset(), and AForge.Vision.Motion.CustomFrameDifferenceDetector.SetBackgroundFrame().
motionFrame
UnmanagedImage AForge.Vision.Motion.CustomFrameDifferenceDetector.motionFrame private
Referenced by AForge.Vision.Motion.CustomFrameDifferenceDetector.ProcessFrame(), and AForge.Vision.Motion.CustomFrameDifferenceDetector.Reset().
tempFrame
UnmanagedImage AForge.Vision.Motion.CustomFrameDifferenceDetector.tempFrame private
Referenced by AForge.Vision.Motion.CustomFrameDifferenceDetector.ProcessFrame(), and AForge.Vision.Motion.CustomFrameDifferenceDetector.Reset().
pixelsChanged
int AForge.Vision.Motion.CustomFrameDifferenceDetector.pixelsChanged private
Referenced by AForge.Vision.Motion.CustomFrameDifferenceDetector.ProcessFrame().
manuallySetBackgroundFrame
bool AForge.Vision.Motion.CustomFrameDifferenceDetector.manuallySetBackgroundFrame = false private
Referenced by AForge.Vision.Motion.CustomFrameDifferenceDetector.Reset(), and AForge.Vision.Motion.CustomFrameDifferenceDetector.SetBackgroundFrame().
suppressNoise
bool AForge.Vision.Motion.CustomFrameDifferenceDetector.suppressNoise = true private
Referenced by AForge.Vision.Motion.CustomFrameDifferenceDetector.CustomFrameDifferenceDetector(), and AForge.Vision.Motion.CustomFrameDifferenceDetector.ProcessFrame().
keepObjectEdges
bool AForge.Vision.Motion.CustomFrameDifferenceDetector.keepObjectEdges = false private
Referenced by AForge.Vision.Motion.CustomFrameDifferenceDetector.CustomFrameDifferenceDetector(), and AForge.Vision.Motion.CustomFrameDifferenceDetector.ProcessFrame().
differenceThreshold
int AForge.Vision.Motion.CustomFrameDifferenceDetector.differenceThreshold = 15 private
Referenced by AForge.Vision.Motion.CustomFrameDifferenceDetector.ProcessFrame().
differenceThresholdNeg
int AForge.Vision.Motion.CustomFrameDifferenceDetector.differenceThresholdNeg = -15 private
Referenced by AForge.Vision.Motion.CustomFrameDifferenceDetector.ProcessFrame().
erosionFilter
BinaryErosion3x3 AForge.Vision.Motion.CustomFrameDifferenceDetector.erosionFilter = new BinaryErosion3x3() private
Referenced by AForge.Vision.Motion.CustomFrameDifferenceDetector.ProcessFrame().
dilatationFilter
BinaryDilatation3x3 AForge.Vision.Motion.CustomFrameDifferenceDetector.dilatationFilter = new BinaryDilatation3x3() private
Referenced by AForge.Vision.Motion.CustomFrameDifferenceDetector.ProcessFrame().
sync
object AForge.Vision.Motion.CustomFrameDifferenceDetector.sync = new object() private
Referenced by AForge.Vision.Motion.CustomFrameDifferenceDetector.ProcessFrame(), AForge.Vision.Motion.CustomFrameDifferenceDetector.Reset(), and AForge.Vision.Motion.CustomFrameDifferenceDetector.SetBackgroundFrame().
Property Documentation
DifferenceThreshold
int AForge.Vision.Motion.CustomFrameDifferenceDetector.DifferenceThreshold get set
Difference threshold value, [1, 255].
The value specifies the amount off difference between pixels, which is treated as motion pixel.
Default value is set to 15.
MotionLevel
float AForge.Vision.Motion.CustomFrameDifferenceDetector.MotionLevel get
Motion level value, [0, 1].
Amount of changes in the last processed frame. For example, if value of this property equals to 0.1, then it means that last processed frame has 10% difference with defined background frame.
MotionFrame
UnmanagedImage AForge.Vision.Motion.CustomFrameDifferenceDetector.MotionFrame get
Motion frame containing detected areas of motion.
Motion frame is a grayscale image, which shows areas of detected motion. All black pixels in the motion frame correspond to areas, where no motion is detected. But white pixels correspond to areas, where motion is detected.
<note>The property is set to null after processing of the first video frame by the algorithm in the case if custom background frame was not set manually by using SetBackgroundFrame(Bitmap) method (it will be not null after second call in this case). If correct custom background was set then the property should bet set to estimated motion frame after ProcessFrame method call.</note>
SuppressNoise
bool AForge.Vision.Motion.CustomFrameDifferenceDetector.SuppressNoise get set
Suppress noise in video frames or not.
The value specifies if additional filtering should be done to suppress standalone noisy pixels by applying 3x3 erosion image processing filter. See KeepObjectsEdges property, if it is required to restore edges of objects, which are not noise.
Default value is set to true.
<note>Turning the value on leads to more processing time of video frame.</note>
KeepObjectsEdges
bool AForge.Vision.Motion.CustomFrameDifferenceDetector.KeepObjectsEdges get set
Restore objects edges after noise suppression or not.
The value specifies if additional filtering should be done to restore objects' edges after noise suppression by applying 3x3 dilatation image processing filter.
Default value is set to false.
<note>Turning the value on leads to more processing time of video frame.</note>
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Vision/Motion/CustomFrameDifferenceDetector.cs