Doc: IGLib EXTENDED: NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest Class Reference
NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest Class Reference
This is the abstract base for all XML output tests, which need to work on a TestEngineResult. Creating a second level engine in the test domain causes problems, so this class uses internal framework classes to run the test and then transforms the XML result into a TestEngineResult for use by derived tests.
Public Member Functions
void InitializeTestEngineResult ()
Protected Member Functions
string GetLocalPath (string fileName)
Static Protected Attributes
const string AssemblyName = "mock-nunit-assembly.exe"
Properties
TestEngineResult EngineResult [get, private set]
string AssemblyPath [get, private set]
Private Attributes
ITestEngine engine
string localDirectory
Detailed Description
This is the abstract base for all XML output tests, which need to work on a TestEngineResult. Creating a second level engine in the test domain causes problems, so this class uses internal framework classes to run the test and then transforms the XML result into a TestEngineResult for use by derived tests.
Member Function Documentation
GetLocalPath()
string NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.GetLocalPath (string fileName) inline protected
References NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.localDirectory.
Referenced by NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.InitializeTestEngineResult(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.InitializeValidator(), and NUnit.Engine.Services.ResultWriters.Tests.XmlTransformResultWriterTests.SummaryTransformTest().
InitializeTestEngineResult()
void NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.InitializeTestEngineResult () inline
References NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.AssemblyName, NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.AssemblyPath, NUnit.Engine.TestEngineActivator.CreateInstance(), NUnit.Engine.TestFilter.Empty, NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.engine, NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.EngineResult, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.GetLocalPath(), NUnit.Engine.ITestEngine.InternalTraceLevel, NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.localDirectory, NUnit.Framework.Internal.TestListener.NULL, and NUnit.Framework.Assert.That().
Member Data Documentation
engine
ITestEngine NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.engine private
Referenced by NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.InitializeTestEngineResult().
localDirectory
string NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.localDirectory private
Referenced by NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.GetLocalPath(), and NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.InitializeTestEngineResult().
AssemblyName
const string NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.AssemblyName = "mock-nunit-assembly.exe" static protected
Referenced by NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.InitializeTestEngineResult().
Property Documentation
EngineResult
TestEngineResult NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.EngineResult get private set protected
Referenced by NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.ConvertEngineResultToXml(), NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.InitializeTestEngineResult(), NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlValidationTests.runSchemaValidatorTest(), and NUnit.Engine.Services.ResultWriters.Tests.XmlTransformResultWriterTests.SummaryTransformTest().
AssemblyPath
string NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.AssemblyPath get private set protected
Referenced by NUnit.Engine.Services.ResultWriters.Tests.XmlOutputTest.InitializeTestEngineResult(), and NUnit.Engine.Services.ResultWriters.Tests.NUnit2XmlResultWriterTests.TestResults_AssemblyPathIsCorrect().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Services/ResultWriters/XmlOutputTest.cs