Doc: IGLib EXTENDED: NUnit.Engine.Services.Tests.RecentFilesTests Class Reference
NUnit.Engine.Services.Tests.RecentFilesTests Class Reference
This fixture is used to test both RecentProjects and its base class RecentFiles. If we add any other derived classes, the tests should be refactored.
Public Member Functions
void SetUp ()
void ServiceIsStarted ()
void CountDefault ()
void CountOverMax ()
void CountUnderMin ()
void CountAtMax ()
void CountAtMin ()
void EmptyList ()
void AddSingleItem ()
void AddMaxItems ()
void AddTooManyItems ()
void IncreaseSize ()
void ReduceSize ()
void IncreaseSizeAfterAdd ()
void ReduceSizeAfterAdd ()
void ReorderLastProject ()
void ReorderSingleProject ()
void ReorderMultipleProjects ()
void ReorderSameProject ()
void ReorderWithListNotFull ()
void RemoveFirstProject ()
void RemoveOneProject ()
void RemoveMultipleProjects ()
void RemoveLastProject ()
Private Member Functions
void SetMockValues (int count)
void CheckMockValues (int count)
void CheckAddItems (int count)
void CheckListContains (params int[] item)
Private Attributes
RecentFilesService _recentFiles
Static Private Attributes
const int MAX = 24
const int MIN = 0
const int DEFAULT = 5
Detailed Description
This fixture is used to test both RecentProjects and its base class RecentFiles. If we add any other derived classes, the tests should be refactored.
Member Function Documentation
SetUp()
void NUnit.Engine.Services.Tests.RecentFilesTests.SetUp () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles.
ServiceIsStarted()
void NUnit.Engine.Services.Tests.RecentFilesTests.ServiceIsStarted () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Services.Service.Status, and NUnit.Framework.Assert.That().
CountDefault()
void NUnit.Engine.Services.Tests.RecentFilesTests.CountDefault () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Services.Tests.RecentFilesTests.DEFAULT, and NUnit.Engine.Services.RecentFilesService.MaxFiles.
CountOverMax()
void NUnit.Engine.Services.Tests.RecentFilesTests.CountOverMax () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Services.Tests.RecentFilesTests.MAX, and NUnit.Engine.Services.RecentFilesService.MaxFiles.
CountUnderMin()
void NUnit.Engine.Services.Tests.RecentFilesTests.CountUnderMin () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Services.RecentFilesService.MaxFiles, and NUnit.Engine.Services.Tests.RecentFilesTests.MIN.
CountAtMax()
void NUnit.Engine.Services.Tests.RecentFilesTests.CountAtMax () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Services.Tests.RecentFilesTests.MAX, and NUnit.Engine.Services.RecentFilesService.MaxFiles.
CountAtMin()
void NUnit.Engine.Services.Tests.RecentFilesTests.CountAtMin () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Services.RecentFilesService.MaxFiles, and NUnit.Engine.Services.Tests.RecentFilesTests.MIN.
EmptyList()
void NUnit.Engine.Services.Tests.RecentFilesTests.EmptyList () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Services.RecentFilesService.Entries, and NUnit.Framework.Assert.IsNotNull().
AddSingleItem()
void NUnit.Engine.Services.Tests.RecentFilesTests.AddSingleItem () inline
References NUnit.Engine.Services.Tests.RecentFilesTests.CheckAddItems().
AddMaxItems()
void NUnit.Engine.Services.Tests.RecentFilesTests.AddMaxItems () inline
References NUnit.Engine.Services.Tests.RecentFilesTests.CheckAddItems().
AddTooManyItems()
void NUnit.Engine.Services.Tests.RecentFilesTests.AddTooManyItems () inline
References NUnit.Engine.Services.Tests.RecentFilesTests.CheckAddItems().
IncreaseSize()
void NUnit.Engine.Services.Tests.RecentFilesTests.IncreaseSize () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Engine.Services.Tests.RecentFilesTests.CheckAddItems(), and NUnit.Engine.Services.RecentFilesService.MaxFiles.
ReduceSize()
void NUnit.Engine.Services.Tests.RecentFilesTests.ReduceSize () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Engine.Services.Tests.RecentFilesTests.CheckAddItems(), and NUnit.Engine.Services.RecentFilesService.MaxFiles.
IncreaseSizeAfterAdd()
void NUnit.Engine.Services.Tests.RecentFilesTests.IncreaseSizeAfterAdd () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Engine.Services.Tests.RecentFilesTests.CheckListContains(), NUnit.Engine.Services.RecentFilesService.MaxFiles, NUnit.Engine.Services.Tests.RecentFilesTests.SetMockValues(), and NUnit.Engine.Services.RecentFilesService.SetMostRecent().
ReduceSizeAfterAdd()
void NUnit.Engine.Services.Tests.RecentFilesTests.ReduceSizeAfterAdd () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Engine.Services.Tests.RecentFilesTests.CheckMockValues(), NUnit.Engine.Services.RecentFilesService.MaxFiles, and NUnit.Engine.Services.Tests.RecentFilesTests.SetMockValues().
ReorderLastProject()
void NUnit.Engine.Services.Tests.RecentFilesTests.ReorderLastProject () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Engine.Services.Tests.RecentFilesTests.CheckListContains(), NUnit.Engine.Services.Tests.RecentFilesTests.SetMockValues(), and NUnit.Engine.Services.RecentFilesService.SetMostRecent().
ReorderSingleProject()
void NUnit.Engine.Services.Tests.RecentFilesTests.ReorderSingleProject () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Engine.Services.Tests.RecentFilesTests.CheckListContains(), NUnit.Engine.Services.Tests.RecentFilesTests.SetMockValues(), and NUnit.Engine.Services.RecentFilesService.SetMostRecent().
ReorderMultipleProjects()
void NUnit.Engine.Services.Tests.RecentFilesTests.ReorderMultipleProjects () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Engine.Services.Tests.RecentFilesTests.CheckListContains(), NUnit.Engine.Services.Tests.RecentFilesTests.SetMockValues(), and NUnit.Engine.Services.RecentFilesService.SetMostRecent().
ReorderSameProject()
void NUnit.Engine.Services.Tests.RecentFilesTests.ReorderSameProject () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Engine.Services.Tests.RecentFilesTests.CheckListContains(), NUnit.Engine.Services.Tests.RecentFilesTests.SetMockValues(), and NUnit.Engine.Services.RecentFilesService.SetMostRecent().
ReorderWithListNotFull()
void NUnit.Engine.Services.Tests.RecentFilesTests.ReorderWithListNotFull () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Engine.Services.Tests.RecentFilesTests.CheckListContains(), NUnit.Engine.Services.Tests.RecentFilesTests.SetMockValues(), and NUnit.Engine.Services.RecentFilesService.SetMostRecent().
RemoveFirstProject()
void NUnit.Engine.Services.Tests.RecentFilesTests.RemoveFirstProject () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Engine.Services.Tests.RecentFilesTests.CheckListContains(), NUnit.Engine.Services.RecentFilesService.Remove(), and NUnit.Engine.Services.Tests.RecentFilesTests.SetMockValues().
RemoveOneProject()
void NUnit.Engine.Services.Tests.RecentFilesTests.RemoveOneProject () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Engine.Services.Tests.RecentFilesTests.CheckListContains(), NUnit.Engine.Services.RecentFilesService.Remove(), and NUnit.Engine.Services.Tests.RecentFilesTests.SetMockValues().
RemoveMultipleProjects()
void NUnit.Engine.Services.Tests.RecentFilesTests.RemoveMultipleProjects () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Engine.Services.Tests.RecentFilesTests.CheckListContains(), NUnit.Engine.Services.RecentFilesService.Remove(), and NUnit.Engine.Services.Tests.RecentFilesTests.SetMockValues().
RemoveLastProject()
void NUnit.Engine.Services.Tests.RecentFilesTests.RemoveLastProject () inline
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Engine.Services.Tests.RecentFilesTests.CheckListContains(), NUnit.Engine.Services.RecentFilesService.Remove(), and NUnit.Engine.Services.Tests.RecentFilesTests.SetMockValues().
SetMockValues()
void NUnit.Engine.Services.Tests.RecentFilesTests.SetMockValues (int count) inline private
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, and NUnit.Engine.Services.RecentFilesService.SetMostRecent().
Referenced by NUnit.Engine.Services.Tests.RecentFilesTests.CheckAddItems(), NUnit.Engine.Services.Tests.RecentFilesTests.IncreaseSizeAfterAdd(), NUnit.Engine.Services.Tests.RecentFilesTests.ReduceSizeAfterAdd(), NUnit.Engine.Services.Tests.RecentFilesTests.RemoveFirstProject(), NUnit.Engine.Services.Tests.RecentFilesTests.RemoveLastProject(), NUnit.Engine.Services.Tests.RecentFilesTests.RemoveMultipleProjects(), NUnit.Engine.Services.Tests.RecentFilesTests.RemoveOneProject(), NUnit.Engine.Services.Tests.RecentFilesTests.ReorderLastProject(), NUnit.Engine.Services.Tests.RecentFilesTests.ReorderMultipleProjects(), NUnit.Engine.Services.Tests.RecentFilesTests.ReorderSameProject(), NUnit.Engine.Services.Tests.RecentFilesTests.ReorderSingleProject(), and NUnit.Engine.Services.Tests.RecentFilesTests.ReorderWithListNotFull().
CheckMockValues()
void NUnit.Engine.Services.Tests.RecentFilesTests.CheckMockValues (int count) inline private
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Framework.Assert.AreEqual(), and NUnit.Engine.Services.RecentFilesService.Entries.
Referenced by NUnit.Engine.Services.Tests.RecentFilesTests.CheckAddItems(), and NUnit.Engine.Services.Tests.RecentFilesTests.ReduceSizeAfterAdd().
CheckAddItems()
void NUnit.Engine.Services.Tests.RecentFilesTests.CheckAddItems (int count) inline private
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Services.Tests.RecentFilesTests.CheckMockValues(), NUnit.Engine.Services.RecentFilesService.Entries, NUnit.Engine.Services.RecentFilesService.MaxFiles, and NUnit.Engine.Services.Tests.RecentFilesTests.SetMockValues().
Referenced by NUnit.Engine.Services.Tests.RecentFilesTests.AddMaxItems(), NUnit.Engine.Services.Tests.RecentFilesTests.AddSingleItem(), NUnit.Engine.Services.Tests.RecentFilesTests.AddTooManyItems(), NUnit.Engine.Services.Tests.RecentFilesTests.IncreaseSize(), and NUnit.Engine.Services.Tests.RecentFilesTests.ReduceSize().
CheckListContains()
void NUnit.Engine.Services.Tests.RecentFilesTests.CheckListContains (params int[] item) inline private
References NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles, NUnit.Framework.Assert.AreEqual(), and NUnit.Engine.Services.RecentFilesService.Entries.
Referenced by NUnit.Engine.Services.Tests.RecentFilesTests.IncreaseSizeAfterAdd(), NUnit.Engine.Services.Tests.RecentFilesTests.RemoveFirstProject(), NUnit.Engine.Services.Tests.RecentFilesTests.RemoveLastProject(), NUnit.Engine.Services.Tests.RecentFilesTests.RemoveMultipleProjects(), NUnit.Engine.Services.Tests.RecentFilesTests.RemoveOneProject(), NUnit.Engine.Services.Tests.RecentFilesTests.ReorderLastProject(), NUnit.Engine.Services.Tests.RecentFilesTests.ReorderMultipleProjects(), NUnit.Engine.Services.Tests.RecentFilesTests.ReorderSameProject(), NUnit.Engine.Services.Tests.RecentFilesTests.ReorderSingleProject(), and NUnit.Engine.Services.Tests.RecentFilesTests.ReorderWithListNotFull().
Member Data Documentation
MAX
const int NUnit.Engine.Services.Tests.RecentFilesTests.MAX = 24 static private
Referenced by NUnit.Engine.Services.Tests.RecentFilesTests.CountAtMax(), and NUnit.Engine.Services.Tests.RecentFilesTests.CountOverMax().
MIN
const int NUnit.Engine.Services.Tests.RecentFilesTests.MIN = 0 static private
Referenced by NUnit.Engine.Services.Tests.RecentFilesTests.CountAtMin(), and NUnit.Engine.Services.Tests.RecentFilesTests.CountUnderMin().
DEFAULT
const int NUnit.Engine.Services.Tests.RecentFilesTests.DEFAULT = 5 static private
Referenced by NUnit.Engine.Services.Tests.RecentFilesTests.CountDefault().
_recentFiles
RecentFilesService NUnit.Engine.Services.Tests.RecentFilesTests._recentFiles private
Referenced by NUnit.Engine.Services.Tests.RecentFilesTests.CheckAddItems(), NUnit.Engine.Services.Tests.RecentFilesTests.CheckListContains(), NUnit.Engine.Services.Tests.RecentFilesTests.CheckMockValues(), NUnit.Engine.Services.Tests.RecentFilesTests.CountAtMax(), NUnit.Engine.Services.Tests.RecentFilesTests.CountAtMin(), NUnit.Engine.Services.Tests.RecentFilesTests.CountDefault(), NUnit.Engine.Services.Tests.RecentFilesTests.CountOverMax(), NUnit.Engine.Services.Tests.RecentFilesTests.CountUnderMin(), NUnit.Engine.Services.Tests.RecentFilesTests.EmptyList(), NUnit.Engine.Services.Tests.RecentFilesTests.IncreaseSize(), NUnit.Engine.Services.Tests.RecentFilesTests.IncreaseSizeAfterAdd(), NUnit.Engine.Services.Tests.RecentFilesTests.ReduceSize(), NUnit.Engine.Services.Tests.RecentFilesTests.ReduceSizeAfterAdd(), NUnit.Engine.Services.Tests.RecentFilesTests.RemoveFirstProject(), NUnit.Engine.Services.Tests.RecentFilesTests.RemoveLastProject(), NUnit.Engine.Services.Tests.RecentFilesTests.RemoveMultipleProjects(), NUnit.Engine.Services.Tests.RecentFilesTests.RemoveOneProject(), NUnit.Engine.Services.Tests.RecentFilesTests.ReorderLastProject(), NUnit.Engine.Services.Tests.RecentFilesTests.ReorderMultipleProjects(), NUnit.Engine.Services.Tests.RecentFilesTests.ReorderSameProject(), NUnit.Engine.Services.Tests.RecentFilesTests.ReorderSingleProject(), NUnit.Engine.Services.Tests.RecentFilesTests.ReorderWithListNotFull(), NUnit.Engine.Services.Tests.RecentFilesTests.ServiceIsStarted(), NUnit.Engine.Services.Tests.RecentFilesTests.SetMockValues(), and NUnit.Engine.Services.Tests.RecentFilesTests.SetUp().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Services/RecentFilesTests.cs