Doc: IGLib EXTENDED: NUnit.Framework.Assertions.SameFixture Class Reference
NUnit.Framework.Assertions.SameFixture Class Reference
Public Member Functions
void Same ()
void SameFails ()
void SameValueTypes ()
Member Function Documentation
Same()
void NUnit.Framework.Assertions.SameFixture.Same () inline
References NUnit.Framework.Assert.AreSame().
SameFails()
void NUnit.Framework.Assertions.SameFixture.SameFails () inline
References NUnit.Framework.Assert.AreSame(), NUnit.Framework.Is.EqualTo(), NUnit.Env.NewLine, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
SameValueTypes()
void NUnit.Framework.Assertions.SameFixture.SameValueTypes () inline
References NUnit.Framework.Assert.AreSame(), NUnit.Framework.Is.EqualTo(), NUnit.Env.NewLine, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/SameFixture.cs