Doc: IGLib EXTENDED: Meta.Numerics.Statistics.UncertainMeasurementSample< T > Class Template Reference
Meta.Numerics.Statistics.UncertainMeasurementSample< T > Class Template Reference
Represents a set of measurements.
Public Member Functions
UncertainMeasurementSample ()
Initializes a new, empty data set.
void Add (UncertainMeasurement< T > datum)
Adds a new data point to the set.
void Add (T x, double y, double dy)
Adds a new data point to the set.
void Add (IEnumerable< UncertainMeasurement< T >> data)
Adds a series of data points to the set.
bool Remove (UncertainMeasurement< T > datum)
Removes a data point from the set.
bool Contains (UncertainMeasurement< T > datum)
Determines whether the set contains the given data point.
void Clear ()
Removes all data points from the set.
FitResult FitToLinearFunction (Func< T, double >[] functions)
Fits the data to a linear combination of fit functions.
FitResult FitToFunction (Func< double[], T, double > function, double[] start)
Fits the data to an arbitrary parameterized function.
IEnumerator< UncertainMeasurement< T > > GetEnumerator ()
Gets an enumerator over the measurements.
UncertainMeasurementSample ()
Initializes a new, empty data set.
UncertainMeasurementSample (IEnumerable< UncertainMeasurement< double >> data)
Initializes a new data set with the specified data.
FitResult FitToConstant ()
Fits the data to a constant value.
FitResult FitToProportionality ()
Fit the data to a proportionality relationship.
FitResult FitToLine ()
Fits the data to a line.
FitResult FitToPolynomial (int order)
Fits the data to a polynomial.
Properties
int Count [get]
Gets the size of the data set.
bool ICollection< UncertainMeasurement< T > >. IsReadOnly [get]
Private Member Functions
void ICollection< UncertainMeasurement< T > >. CopyTo (UncertainMeasurement< T >[] array, int offset)
System.Collections.IEnumerator System.Collections.IEnumerable. GetEnumerator ()
Private Attributes
List< UncertainMeasurement< T > > data = new List<UncertainMeasurement<T>>()
Detailed Description
Represents a set of measurements.
Represents a set of UncertainMeasurement<Double> measurements.
Template Parameters
T The type of independent variable associated with each measurement.
This class adds functionality to the UncertainMeasurementSample class which applies when the independent variable (X variable) is a single real number. This includes fitting to a constant, line, or polynomial.
Constructor & Destructor Documentation
UncertainMeasurementSample() [1/3]
Meta.Numerics.Statistics.UncertainMeasurementSample< T >.UncertainMeasurementSample () inline
Initializes a new, empty data set.
UncertainMeasurementSample() [2/3]
Meta.Numerics.Statistics.UncertainMeasurementSample< T >.UncertainMeasurementSample () inline
Initializes a new, empty data set.
UncertainMeasurementSample() [3/3]
Meta.Numerics.Statistics.UncertainMeasurementSample< T >.UncertainMeasurementSample (IEnumerable< UncertainMeasurement< double >> data) inline
Initializes a new data set with the specified data.
Parameters
data An enumerator over the UncertainMeasurement<Double>s to place in the set.
References Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Add(), and Meta.Numerics.Statistics.UncertainMeasurementSample< T >.data.
Member Function Documentation
Add() [1/3]
void Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Add (UncertainMeasurement< T > datum) inline
Adds a new data point to the set.
Parameters
datum The data point.
References Meta.Numerics.Statistics.UncertainMeasurementSample< T >.data.
Referenced by Test.BugTests.Bug6162(), and Meta.Numerics.Statistics.UncertainMeasurementSample< T >.UncertainMeasurementSample().
Add() [2/3]
void Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Add (T x, double y, double dy) inline
Adds a new data point to the set.
Parameters
x The value of the ordinate (independent variable).
y The value of the abcissa (dependent variable).
dy The uncertainty of the abcissa (dependent variable).
References Meta.Numerics.Statistics.UncertainMeasurementSample< T >.data.
Add() [3/3]
void Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Add (IEnumerable< UncertainMeasurement< T >> data) inline
Adds a series of data points to the set.
Parameters
data The data points.
References Meta.Numerics.Statistics.UncertainMeasurementSample< T >.data.
Remove()
bool Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Remove (UncertainMeasurement< T > datum) inline
Removes a data point from the set.
Parameters
datum The data point to remove.
Returns
True if the data point was found and removed; otherwise false.
References Meta.Numerics.Statistics.UncertainMeasurementSample< T >.data.
Contains()
bool Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Contains (UncertainMeasurement< T > datum) inline
Determines whether the set contains the given data point.
Parameters
datum The data point.
Returns
True if the set contains the given data point, otherwise false.
References Meta.Numerics.Statistics.UncertainMeasurementSample< T >.data.
Clear()
void Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Clear () inline
Removes all data points from the set.
References Meta.Numerics.Statistics.UncertainMeasurementSample< T >.data.
FitToLinearFunction()
FitResult Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToLinearFunction (Func< T, double >[] functions) inline
Fits the data to a linear combination of fit functions.
Parameters
functions The component functions.
Returns
A fit result containing the best-fit coefficients of the component functions and a &#x3C7;2 test of the quality of the fit.
Exceptions
ArgumentNullException functions is null.
InsufficientDataException There are fewer data points than fit parameters.
References Meta.Numerics.Statistics.UncertainMeasurementSample< T >.data.
Referenced by Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToPolynomial().
FitToFunction()
FitResult Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToFunction (Func< double[], T, double > function, double[] start) inline
Fits the data to an arbitrary parameterized function.
Parameters
function The fit function.
start An initial guess at the parameters.
Returns
A fit result containing the best-fitting function parameters and a &#x3C7;2 test of the quality of the fit.
Exceptions
ArgumentNullException function or start are null.
InsufficientDataException There are fewer data points than fit parameters.
References Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Count, Meta.Numerics.Analysis.SpaceExtremum.Curvature(), Meta.Numerics.Analysis.SpaceExtremum.Dimension, Meta.Numerics.Analysis.FunctionMath.FindMinimum(), Meta.Numerics.Matrices.CholeskyDecomposition.Inverse(), Meta.Numerics.Analysis.SpaceExtremum.Location(), and Meta.Numerics.Analysis.SpaceExtremum.Value.
GetEnumerator() [1/2]
IEnumerator<UncertainMeasurement<T> > Meta.Numerics.Statistics.UncertainMeasurementSample< T >.GetEnumerator () inline
Gets an enumerator over the measurements.
Returns
An enumerator over the measurements.
References Meta.Numerics.Statistics.UncertainMeasurementSample< T >.data.
CopyTo()
void ICollection<UncertainMeasurement<T> >. Meta.Numerics.Statistics.UncertainMeasurementSample< T >.CopyTo (UncertainMeasurement< T >[] array, int offset) inline private
References Meta.Numerics.Statistics.UncertainMeasurementSample< T >.data.
GetEnumerator() [2/2]
System.Collections.IEnumerator System.Collections.IEnumerable. Meta.Numerics.Statistics.UncertainMeasurementSample< T >.GetEnumerator () inline private
References Meta.Numerics.Statistics.UncertainMeasurementSample< T >.data.
FitToConstant()
FitResult Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToConstant () inline
Fits the data to a constant value.
Returns
A fit result containing the best combined value and a &#x3C7;2 test of the quality of the fit.
This method provides a simple way to
References Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Count, and Meta.Numerics.Statistics.UncertainMeasurement< T >.Y.
Referenced by Test.DataSetTest.FitDataToLineTest().
FitToProportionality()
FitResult Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToProportionality () inline
Fit the data to a proportionality relationship.
Returns
A fit result containing the best-fit proportionality constant parameter and a &#x3C7;2 test of the quality of the fit.
References Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Count, Meta.Numerics.Statistics.UncertainMeasurement< T >.X, and Meta.Numerics.Statistics.UncertainMeasurement< T >.Y.
FitToLine()
FitResult Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToLine () inline
Fits the data to a line.
Returns
A fit result containing the best-fit intercept and slope parameters and a &#x3C7;2 test of the quality of the fit.
References Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Count, Meta.Numerics.Statistics.UncertainMeasurement< T >.X, and Meta.Numerics.Statistics.UncertainMeasurement< T >.Y.
Referenced by Test.DataSetTest.FitDataToLineChiSquaredTest(), Test.DataSetTest.FitDataToLineTest(), and Test.DataSetTest.FitDataToLineUncertaintyTest().
FitToPolynomial()
FitResult Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToPolynomial (int order) inline
Fits the data to a polynomial.
Parameters
order The order of the polynomial to fit.
Returns
A fit result containg the best-fit polynomial coefficients, in order of ascending power from 0 to order , and a &#x3C7;2 test of the quality of the fit.
Exceptions
InvalidOperationException There are more polynomial coefficients than data points.
References Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Count, Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToLinearFunction(), and Meta.Numerics.MoreMath.Pow().
Referenced by Test.BugTests.Bug6162(), Test.DataSetTest.FitDataToLineTest(), and Test.DataSetTest.FitDataToPolynomialChiSquaredTest().
Member Data Documentation
data
List<UncertainMeasurement<T> > Meta.Numerics.Statistics.UncertainMeasurementSample< T >.data = new List<UncertainMeasurement<T>>() private
Referenced by Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Add(), Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Clear(), Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Contains(), Meta.Numerics.Statistics.UncertainMeasurementSample< T >.CopyTo(), Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToLinearFunction(), Meta.Numerics.Statistics.UncertainMeasurementSample< T >.GetEnumerator(), Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Remove(), and Meta.Numerics.Statistics.UncertainMeasurementSample< T >.UncertainMeasurementSample().
Property Documentation
Count
int Meta.Numerics.Statistics.UncertainMeasurementSample< T >.Count get
Gets the size of the data set.
Referenced by Test.DataSetTest.FitDataToLineTest(), Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToConstant(), Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToFunction(), Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToLine(), Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToPolynomial(), and Meta.Numerics.Statistics.UncertainMeasurementSample< T >.FitToProportionality().
IsReadOnly
bool ICollection<UncertainMeasurement<T> >. Meta.Numerics.Statistics.UncertainMeasurementSample< T >.IsReadOnly get private
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/UncertainMeasurementSample.cs