Doc: IGLib EXTENDED: IG.Forms.HashForm Class Reference
IG.Forms.HashForm Class Reference
A window form to calculate various checksums of selected files or inserted text.
Public Member Functions
HashForm ()
HashForm ()
HashForm ()
HashForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
HashControl hashGeneratorControl1
Detailed Description
A window form to calculate various checksums of selected files or inserted text.
This is only a window container for HashForm.
See:
http://www2.arnes.si/~ljc3m2/igor/software/IGLibShellApp/HashForm.html#hashform
$A Igor Aug 08;
Constructor & Destructor Documentation
HashForm() [1/4]
IG.Forms.HashForm.HashForm () inline
References IG.Forms.HashForm.InitializeComponent().
HashForm() [2/4]
IG.Forms.HashForm.HashForm () inline
References IG.Forms.HashForm.InitializeComponent().
HashForm() [3/4]
IG.Forms.HashForm.HashForm () inline
References IG.Forms.HashForm.InitializeComponent().
HashForm() [4/4]
IG.Forms.HashForm.HashForm () inline
References IG.Forms.HashForm.InitializeComponent().
Member Function Documentation
Dispose() [1/4]
override void IG.Forms.HashForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.HashForm.components.
InitializeComponent() [1/4]
void IG.Forms.HashForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.HashControl.DirectoryPath, IG.Forms.HashControl.FilePath, and IG.Forms.HashForm.hashGeneratorControl1.
Referenced by IG.Forms.HashForm.HashForm().
Dispose() [2/4]
override void IG.Forms.HashForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.HashForm.components.
InitializeComponent() [2/4]
void IG.Forms.HashForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.HashControl.DirectoryPath, IG.Forms.HashControl.FilePath, and IG.Forms.HashForm.hashGeneratorControl1.
Dispose() [3/4]
override void IG.Forms.HashForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.HashForm.components.
InitializeComponent() [3/4]
void IG.Forms.HashForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.HashControl.DirectoryPath, IG.Forms.HashControl.FilePath, and IG.Forms.HashForm.hashGeneratorControl1.
Dispose() [4/4]
override void IG.Forms.HashForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.HashForm.components.
InitializeComponent() [4/4]
void IG.Forms.HashForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.HashControl.DirectoryPath, IG.Forms.HashControl.FilePath, and IG.Forms.HashForm.hashGeneratorControl1.
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.HashForm.components = null private
Required designer variable.
Referenced by IG.Forms.HashForm.Dispose().
hashGeneratorControl1
HashControl IG.Forms.HashForm.hashGeneratorControl1 private
Referenced by IG.Forms.HashForm.InitializeComponent().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/Cryptography/HashForm.cs
iglib/igforms/Utilities/Cryptography/HashForm.Designer.cs