Doc: IGLib EXTENDED: AForge.Imaging.Textures.WoodTexture Class Reference
AForge.Imaging.Textures.WoodTexture Class Reference
Wood texture.
Public Member Functions
WoodTexture ()
Initializes a new instance of the WoodTexture class.
WoodTexture (double rings)
Initializes a new instance of the WoodTexture class.
float[,] Generate (int width, int height)
Generate texture.
void Reset ()
Reset generator.
Properties
double Rings [get, set]
Wood rings amount, ≥ 3.
Private Attributes
AForge.Math.PerlinNoise noise = new AForge.Math.PerlinNoise(8, 0.5, 1.0 / 32, 0.05)
Random rand = new Random()
int r
double rings = 12
Detailed Description
Wood texture.
The texture generator creates textures with effect of rings on trunk's shear. The Rings property allows to specify the desired amount of wood rings.
The generator is based on the Perlin noise function.
Sample usage:
// create texture generator
WoodTexture textureGenerator = new WoodTexture();
// generate new texture
float[,] texture = textureGenerator.Generate(320, 240);
// convert it to image to visualize
Bitmap textureImage = TextureTools.ToBitmap(texture);
Result image:
Constructor & Destructor Documentation
WoodTexture() [1/2]
AForge.Imaging.Textures.WoodTexture.WoodTexture () inline
Initializes a new instance of the WoodTexture class.
References AForge.Imaging.Textures.WoodTexture.Reset().
WoodTexture() [2/2]
AForge.Imaging.Textures.WoodTexture.WoodTexture (double rings) inline
Initializes a new instance of the WoodTexture class.
Parameters
rings Wood rings amount.
References AForge.Imaging.Textures.WoodTexture.Reset(), and AForge.Imaging.Textures.WoodTexture.rings.
Member Function Documentation
Generate()
float [,] AForge.Imaging.Textures.WoodTexture.Generate (int width, int height) inline
Generate texture.
Parameters
width Texture's width.
height Texture's height.
Returns
Two dimensional array of intensities.
Generates new texture of the specified size.
Implements AForge.Imaging.Textures.ITextureGenerator.
References AForge.Math.PerlinNoise.Function2D(), AForge.Imaging.Textures.WoodTexture.noise, AForge.Imaging.Textures.WoodTexture.r, and AForge.Imaging.Textures.WoodTexture.rings.
Reset()
void AForge.Imaging.Textures.WoodTexture.Reset () inline
Reset generator.
Regenerates internal random numbers.
Implements AForge.Imaging.Textures.ITextureGenerator.
References AForge.Imaging.Textures.WoodTexture.r, and AForge.Imaging.Textures.WoodTexture.rand.
Referenced by AForge.Imaging.Textures.WoodTexture.WoodTexture().
Member Data Documentation
noise
AForge.Math.PerlinNoise AForge.Imaging.Textures.WoodTexture.noise = new AForge.Math.PerlinNoise(8, 0.5, 1.0 / 32, 0.05) private
Referenced by AForge.Imaging.Textures.WoodTexture.Generate().
rand
Random AForge.Imaging.Textures.WoodTexture.rand = new Random() private
Referenced by AForge.Imaging.Textures.WoodTexture.Reset().
r
int AForge.Imaging.Textures.WoodTexture.r private
Referenced by AForge.Imaging.Textures.WoodTexture.Generate(), and AForge.Imaging.Textures.WoodTexture.Reset().
rings
double AForge.Imaging.Textures.WoodTexture.rings = 12 private
Referenced by AForge.Imaging.Textures.WoodTexture.Generate(), and AForge.Imaging.Textures.WoodTexture.WoodTexture().
Property Documentation
Rings
double AForge.Imaging.Textures.WoodTexture.Rings get set
Wood rings amount, ≥ 3.
The property sets the amount of wood rings, which make effect of rings on trunk's shear.
Default value is set to 12.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Textures/WoodTexture.cs