Doc: IGLib EXTENDED: NUnit.TestData.UnhandledExceptionData.UnhandledExceptions Class Reference
NUnit.TestData.UnhandledExceptionData.UnhandledExceptions Class Reference
Public Member Functions
void Normal ()
void Threaded ()
void ThreadedAndForget ()
void ThreadedAndWait ()
void ThreadedAssert ()
Private Member Functions
void ThreadedAssertProc ()
Member Function Documentation
Normal()
void NUnit.TestData.UnhandledExceptionData.UnhandledExceptions.Normal () inline
Referenced by NUnit.TestData.UnhandledExceptionData.UnhandledExceptions.Threaded(), NUnit.TestData.UnhandledExceptionData.UnhandledExceptions.ThreadedAndForget(), and NUnit.TestData.UnhandledExceptionData.UnhandledExceptions.ThreadedAndWait().
Threaded()
void NUnit.TestData.UnhandledExceptionData.UnhandledExceptions.Threaded () inline
References NUnit.TestData.UnhandledExceptionData.UnhandledExceptions.Normal().
ThreadedAndForget()
void NUnit.TestData.UnhandledExceptionData.UnhandledExceptions.ThreadedAndForget () inline
References NUnit.TestData.UnhandledExceptionData.UnhandledExceptions.Normal().
ThreadedAndWait()
void NUnit.TestData.UnhandledExceptionData.UnhandledExceptions.ThreadedAndWait () inline
References NUnit.TestData.UnhandledExceptionData.UnhandledExceptions.Normal().
ThreadedAssert()
void NUnit.TestData.UnhandledExceptionData.UnhandledExceptions.ThreadedAssert () inline
References NUnit.TestData.UnhandledExceptionData.UnhandledExceptions.ThreadedAssertProc().
ThreadedAssertProc()
void NUnit.TestData.UnhandledExceptionData.UnhandledExceptions.ThreadedAssertProc () inline private
References NUnit.Framework.Assert.AreEqual().
Referenced by NUnit.TestData.UnhandledExceptionData.UnhandledExceptions.ThreadedAssert().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/testdata/UnhandledExceptions.cs