Doc: IGLib EXTENDED: IG.Forms.TimerForm Class Reference
IG.Forms.TimerForm Class Reference
Public Member Functions
TimerForm ()
TimerForm ()
TimerForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void resizeFormToContainedControl ()
void containedFormSizeChanged (object sender, EventArgs e)
void StopWatchForm_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void resizeFormToContainedControl ()
void containedFormSizeChanged (object sender, EventArgs e)
void StopWatchForm_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void resizeFormToContainedControl ()
void containedFormSizeChanged (object sender, EventArgs e)
void StopWatchForm_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
TimerControl stopWatchControl2
Constructor & Destructor Documentation
TimerForm() [1/3]
IG.Forms.TimerForm.TimerForm () inline
References IG.Forms.TimerForm.InitializeComponent().
TimerForm() [2/3]
IG.Forms.TimerForm.TimerForm () inline
References IG.Forms.TimerForm.InitializeComponent().
TimerForm() [3/3]
IG.Forms.TimerForm.TimerForm () inline
References IG.Forms.TimerForm.InitializeComponent().
Member Function Documentation
resizeFormToContainedControl() [1/3]
void IG.Forms.TimerForm.resizeFormToContainedControl () inline private
References IG.Forms.TimerForm.stopWatchControl2.
containedFormSizeChanged() [1/3]
void IG.Forms.TimerForm.containedFormSizeChanged (object sender, EventArgs e) inline private
StopWatchForm_Load() [1/3]
void IG.Forms.TimerForm.StopWatchForm_Load (object sender, EventArgs e) inline private
Referenced by IG.Forms.TimerForm.InitializeComponent().
Dispose() [1/3]
override void IG.Forms.TimerForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.TimerForm.components.
InitializeComponent() [1/3]
void IG.Forms.TimerForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.TimerControl.CdShowHoursWhenZero, IG.Forms.TimerControl.CdShowMilliSeconds, IG.Forms.TimerControl.CdStartText, IG.Forms.TimerControl.CdStopText, IG.Forms.TimerControl.ColorBgOk, IG.Forms.TimerControl.ColorBgWarning, IG.Forms.TimerControl.MilliSecondsSizeRatio, IG.Forms.TimerForm.stopWatchControl2, IG.Forms.TimerForm.StopWatchForm_Load(), IG.Forms.TimerControl.SwShowHoursWhenZero, IG.Forms.TimerControl.SwShowMilliSeconds, IG.Forms.TimerControl.SwStartText, and IG.Forms.TimerControl.SwStopText.
Referenced by IG.Forms.TimerForm.TimerForm().
resizeFormToContainedControl() [2/3]
void IG.Forms.TimerForm.resizeFormToContainedControl () inline private
References IG.Forms.TimerForm.stopWatchControl2.
containedFormSizeChanged() [2/3]
void IG.Forms.TimerForm.containedFormSizeChanged (object sender, EventArgs e) inline private
StopWatchForm_Load() [2/3]
void IG.Forms.TimerForm.StopWatchForm_Load (object sender, EventArgs e) inline private
Dispose() [2/3]
override void IG.Forms.TimerForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.TimerForm.components.
InitializeComponent() [2/3]
void IG.Forms.TimerForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.TimerControl.CdShowHoursWhenZero, IG.Forms.TimerControl.CdShowMilliSeconds, IG.Forms.TimerControl.CdStartText, IG.Forms.TimerControl.CdStopText, IG.Forms.TimerControl.ColorBgOk, IG.Forms.TimerControl.ColorBgWarning, IG.Forms.TimerControl.MilliSecondsSizeRatio, IG.Forms.TimerForm.stopWatchControl2, IG.Forms.TimerForm.StopWatchForm_Load(), IG.Forms.TimerControl.SwShowHoursWhenZero, IG.Forms.TimerControl.SwShowMilliSeconds, IG.Forms.TimerControl.SwStartText, and IG.Forms.TimerControl.SwStopText.
resizeFormToContainedControl() [3/3]
void IG.Forms.TimerForm.resizeFormToContainedControl () inline private
References IG.Forms.TimerForm.stopWatchControl2.
containedFormSizeChanged() [3/3]
void IG.Forms.TimerForm.containedFormSizeChanged (object sender, EventArgs e) inline private
StopWatchForm_Load() [3/3]
void IG.Forms.TimerForm.StopWatchForm_Load (object sender, EventArgs e) inline private
Dispose() [3/3]
override void IG.Forms.TimerForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.TimerForm.components.
InitializeComponent() [3/3]
void IG.Forms.TimerForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.TimerControl.CdShowHoursWhenZero, IG.Forms.TimerControl.CdShowMilliSeconds, IG.Forms.TimerControl.CdStartText, IG.Forms.TimerControl.CdStopText, IG.Forms.TimerControl.ColorBgOk, IG.Forms.TimerControl.ColorBgWarning, IG.Forms.TimerControl.MilliSecondsSizeRatio, IG.Forms.TimerForm.stopWatchControl2, IG.Forms.TimerForm.StopWatchForm_Load(), IG.Forms.TimerControl.SwShowHoursWhenZero, IG.Forms.TimerControl.SwShowMilliSeconds, IG.Forms.TimerControl.SwStartText, and IG.Forms.TimerControl.SwStopText.
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.TimerForm.components = null private
Required designer variable.
Referenced by IG.Forms.TimerForm.Dispose().
stopWatchControl2
TimerControl IG.Forms.TimerForm.stopWatchControl2 private
Referenced by IG.Forms.TimerForm.InitializeComponent(), and IG.Forms.TimerForm.resizeFormToContainedControl().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/Timer/TimerForm.cs
iglib/igforms/Utilities/Timer/TimerForm.Designer.cs