Doc: IGLib EXTENDED: TestGui.Form2 Class Reference
TestGui.Form2 Class Reference
Public Member Functions
Form2 ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
byte PaketTipId [get, set]
DateTime PaketDatum [get, set]
int StZapisov [get, set]
decimal VsotaDokumentDatum [get, set]
decimal VsotaCenaNeto [get, set]
string PaketXml [get, set]
Private Member Functions
void Form2_Load (object sender, EventArgs e)
void button1_Click (object sender, EventArgs e)
void button2_Click (object sender, EventArgs e)
void button3_Click (object sender, EventArgs e)
void button4_Click (object sender, EventArgs e)
void button5_Click (object sender, EventArgs e)
void button6_Click (object sender, EventArgs e)
void button7_Click (object sender, EventArgs e)
void button8_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
efakt1.WebServiceSimulator web
byte paketTipId
DateTime paketDatum
int stZapisov
decimal vsotaDokumentDatum
decimal vsotaCenaNeto
string paketXml
decimal paketId
string paketStatus
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Button button1
System.Windows.Forms.Button button2
System.Windows.Forms.Button button3
System.Windows.Forms.Button button4
System.Windows.Forms.Button button5
System.Windows.Forms.Button button6
System.Windows.Forms.TextBox textBox1
System.Windows.Forms.Button button7
System.Windows.Forms.Button button8
Constructor & Destructor Documentation
Form2()
TestGui.Form2.Form2 () inline
References TestGui.Form2.InitializeComponent().
Member Function Documentation
Form2_Load()
void TestGui.Form2.Form2_Load (object sender, EventArgs e) inline private
References TestGui.Form2.web.
Referenced by TestGui.Form2.InitializeComponent().
button1_Click()
void TestGui.Form2.button1_Click (object sender, EventArgs e) inline private
References efakt1.WebServiceSimulator.Connect(), efakt1.WebServiceSimulator.Disconnect(), efakt1.WebServiceSimulator.InsertIntoEfaPaket(), TestGui.Form2.paketDatum, TestGui.Form2.paketId, TestGui.Form2.paketTipId, TestGui.Form2.stZapisov, TestGui.Form2.vsotaCenaNeto, TestGui.Form2.vsotaDokumentDatum, and TestGui.Form2.web.
Referenced by TestGui.Form2.InitializeComponent().
button2_Click()
void TestGui.Form2.button2_Click (object sender, EventArgs e) inline private
References efakt1.WebServiceSimulator.Connect(), efakt1.WebServiceSimulator.Disconnect(), TestGui.Form2.paketId, TestGui.Form2.paketXml, efakt1.WebServiceSimulator.SaveXmlToDisk(), and TestGui.Form2.web.
Referenced by TestGui.Form2.InitializeComponent().
button3_Click()
void TestGui.Form2.button3_Click (object sender, EventArgs e) inline private
References efakt1.WebServiceSimulator.Connect(), efakt1.WebServiceSimulator.Disconnect(), efakt1.WebServiceSimulator.InsertPaketXml(), TestGui.Form2.paketId, and TestGui.Form2.web.
Referenced by TestGui.Form2.InitializeComponent().
button4_Click()
void TestGui.Form2.button4_Click (object sender, EventArgs e) inline private
References efakt1.WebServiceSimulator.Connect(), efakt1.WebServiceSimulator.Disconnect(), TestGui.Form2.paketId, efakt1.WebServiceSimulator.UpdateGlavaPostavke(), and TestGui.Form2.web.
Referenced by TestGui.Form2.InitializeComponent().
button5_Click()
void TestGui.Form2.button5_Click (object sender, EventArgs e) inline private
References efakt1.WebServiceSimulator.Connect(), efakt1.WebServiceSimulator.Disconnect(), efakt1.WebServiceSimulator.GetPaketStatusXml(), TestGui.Form2.paketId, TestGui.Form2.paketStatus, TestGui.Form2.textBox1, and TestGui.Form2.web.
Referenced by TestGui.Form2.InitializeComponent().
button6_Click()
void TestGui.Form2.button6_Click (object sender, EventArgs e) inline private
References TestGui.Form2.paketStatus, TestGui.Form2.paketXml, and TestGui.Form2.textBox1.
Referenced by TestGui.Form2.InitializeComponent().
button7_Click()
void TestGui.Form2.button7_Click (object sender, EventArgs e) inline private
References efakt1.WebServiceSimulator.Connect(), efakt1.WebServiceSimulator.Disconnect(), TestGui.Form2.paketXml, efakt1.WebServiceSimulator.ValidateXml(), and TestGui.Form2.web.
Referenced by TestGui.Form2.InitializeComponent().
button8_Click()
void TestGui.Form2.button8_Click (object sender, EventArgs e) inline private
Referenced by TestGui.Form2.InitializeComponent().
Dispose()
override void TestGui.Form2.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References TestGui.Form2.components.
InitializeComponent()
void TestGui.Form2.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References TestGui.Form2.button1, TestGui.Form2.button1_Click(), TestGui.Form2.button2, TestGui.Form2.button2_Click(), TestGui.Form2.button3, TestGui.Form2.button3_Click(), TestGui.Form2.button4, TestGui.Form2.button4_Click(), TestGui.Form2.button5, TestGui.Form2.button5_Click(), TestGui.Form2.button6, TestGui.Form2.button6_Click(), TestGui.Form2.button7, TestGui.Form2.button7_Click(), TestGui.Form2.button8, TestGui.Form2.button8_Click(), TestGui.Form2.Form2_Load(), and TestGui.Form2.textBox1.
Referenced by TestGui.Form2.Form2().
Member Data Documentation
web
efakt1.WebServiceSimulator TestGui.Form2.web private
Referenced by TestGui.Form2.button1_Click(), TestGui.Form2.button2_Click(), TestGui.Form2.button3_Click(), TestGui.Form2.button4_Click(), TestGui.Form2.button5_Click(), TestGui.Form2.button7_Click(), and TestGui.Form2.Form2_Load().
paketTipId
byte TestGui.Form2.paketTipId private
Referenced by TestGui.Form2.button1_Click().
paketDatum
DateTime TestGui.Form2.paketDatum private
Referenced by TestGui.Form2.button1_Click().
stZapisov
int TestGui.Form2.stZapisov private
Referenced by TestGui.Form2.button1_Click().
vsotaDokumentDatum
decimal TestGui.Form2.vsotaDokumentDatum private
Referenced by TestGui.Form2.button1_Click().
vsotaCenaNeto
decimal TestGui.Form2.vsotaCenaNeto private
Referenced by TestGui.Form2.button1_Click().
paketXml
string TestGui.Form2.paketXml private
Referenced by TestGui.Form2.button2_Click(), TestGui.Form2.button6_Click(), and TestGui.Form2.button7_Click().
paketId
decimal TestGui.Form2.paketId private
Referenced by TestGui.Form2.button1_Click(), TestGui.Form2.button2_Click(), TestGui.Form2.button3_Click(), TestGui.Form2.button4_Click(), and TestGui.Form2.button5_Click().
paketStatus
string TestGui.Form2.paketStatus private
Referenced by TestGui.Form2.button5_Click(), and TestGui.Form2.button6_Click().
components
System.ComponentModel.IContainer TestGui.Form2.components = null private
Required designer variable.
Referenced by TestGui.Form2.Dispose().
button1
System.Windows.Forms.Button TestGui.Form2.button1 private
Referenced by TestGui.Form2.InitializeComponent().
button2
System.Windows.Forms.Button TestGui.Form2.button2 private
Referenced by TestGui.Form2.InitializeComponent().
button3
System.Windows.Forms.Button TestGui.Form2.button3 private
Referenced by TestGui.Form2.InitializeComponent().
button4
System.Windows.Forms.Button TestGui.Form2.button4 private
Referenced by TestGui.Form2.InitializeComponent().
button5
System.Windows.Forms.Button TestGui.Form2.button5 private
Referenced by TestGui.Form2.InitializeComponent().
button6
System.Windows.Forms.Button TestGui.Form2.button6 private
Referenced by TestGui.Form2.InitializeComponent().
textBox1
System.Windows.Forms.TextBox TestGui.Form2.textBox1 private
Referenced by TestGui.Form2.button5_Click(), TestGui.Form2.button6_Click(), and TestGui.Form2.InitializeComponent().
button7
System.Windows.Forms.Button TestGui.Form2.button7 private
Referenced by TestGui.Form2.InitializeComponent().
button8
System.Windows.Forms.Button TestGui.Form2.button8 private
Referenced by TestGui.Form2.InitializeComponent().
Property Documentation
PaketTipId
byte TestGui.Form2.PaketTipId get set
Referenced by TestGui.Form1.btnTest_Click().
PaketDatum
DateTime TestGui.Form2.PaketDatum get set
Referenced by TestGui.Form1.btnTest_Click().
StZapisov
int TestGui.Form2.StZapisov get set
Referenced by TestGui.Form1.btnTest_Click().
VsotaDokumentDatum
decimal TestGui.Form2.VsotaDokumentDatum get set
Referenced by TestGui.Form1.btnTest_Click().
VsotaCenaNeto
decimal TestGui.Form2.VsotaCenaNeto get set
Referenced by TestGui.Form1.btnTest_Click().
PaketXml
string TestGui.Form2.PaketXml get set
Referenced by TestGui.Form1.btnTest_Click().
The documentation for this class was generated from the following files:
igtest/tmp_prem/prefa/95_Test/TestUtils/TestGui/Form2.cs
igtest/tmp_prem/prefa/95_Test/TestUtils/TestGui/Form2.Designer.cs