Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DHSEQR Class Reference
DotNumerics.LinearAlgebra.CSLapack.DHSEQR Class Reference
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DHSEQR (ILAENV ilaenv, LSAME lsame, DLACPY dlacpy, DLAHQR dlahqr, DLAQR0 dlaqr0, DLASET dlaset, XERBLA xerbla)
DHSEQR ()
void Run (string JOB, string COMPZ, int N, int ILO, int IHI, ref double[] H, int offset_h, int LDH, ref double[] WR, int offset_wr, ref double[] WI, int offset_wi, ref double[] Z, int offset_z, int LDZ, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
ILAENV _ilaenv
LSAME _lsame
DLACPY _dlacpy
DLAHQR _dlahqr
DLAQR0 _dlaqr0
DLASET _dlaset
XERBLA _xerbla
double[] HL = new double[NL * NL]
double[] WORKL = new double[NL]
Static Private Attributes
const int NTINY = 11
const int NL = 49
const double ZERO = 0.0E0
const double ONE = 1.0E0
Detailed Description
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DHSEQR computes the eigenvalues of a Hessenberg matrix H and, optionally, the matrices T and Z from the Schur decomposition H = Z T Z**T, where T is an upper quasi-triangular matrix (the Schur form), and Z is the orthogonal matrix of Schur vectors.
Optionally Z may be postmultiplied into an input orthogonal matrix Q so that this routine can give the Schur factorization of a matrix A which has been reduced to the Hessenberg form H by the orthogonal matrix Q: A = Q*H*Q**T = (QZ)*T*(QZ)**T.
/summary>
Constructor & Destructor Documentation
DHSEQR() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DHSEQR.DHSEQR (ILAENV ilaenv, LSAME lsame, DLACPY dlacpy, DLAHQR dlahqr, DLAQR0 dlaqr0, DLASET dlaset, XERBLA xerbla) inline
DHSEQR() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DHSEQR.DHSEQR () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DHSEQR.Run (string JOB, string COMPZ, int N, int ILO, int IHI, ref double[] H, int offset_h, int LDH, ref double[] WR, int offset_wr, ref double[] WI, int offset_wi, ref double[] Z, int offset_z, int LDZ, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DHSEQR computes the eigenvalues of a Hessenberg matrix H and, optionally, the matrices T and Z from the Schur decomposition H = Z T Z**T, where T is an upper quasi-triangular matrix (the Schur form), and Z is the orthogonal matrix of Schur vectors.
Optionally Z may be postmultiplied into an input orthogonal matrix Q so that this routine can give the Schur factorization of a matrix A which has been reduced to the Hessenberg form H by the orthogonal matrix Q: A = Q*H*Q**T = (QZ)*T*(QZ)**T.
/summary>
Parameters
JOB (input) CHARACTER*1 = 'E': compute eigenvalues only; = 'S': compute eigenvalues and the Schur form T. /param>
Parameters
COMPZ (input) CHARACTER*1 = 'N': no Schur vectors are computed; = 'I': Z is initialized to the unit matrix and the matrix Z of Schur vectors of H is returned; = 'V': Z must contain an orthogonal matrix Q on entry, and the product Q*Z is returned. /param>
Parameters
N (input) INTEGER The order of the matrix H. N .GE. 0. /param>
Parameters
ILO (input) INTEGER /param>
Parameters
IHI (input) INTEGER It is assumed that H is already upper triangular in rows and columns 1:ILO-1 and IHI+1:N. ILO and IHI are normally set by a previous call to DGEBAL, and then passed to DGEHRD when the matrix output by DGEBAL is reduced to Hessenberg form. Otherwise ILO and IHI should be set to 1 and N respectively. If N.GT.0, then 1.LE.ILO.LE.IHI.LE.N. If N = 0, then ILO = 1 and IHI = 0. /param>
Parameters
H (input/output) DOUBLE PRECISION array, dimension (LDH,N) On entry, the upper Hessenberg matrix H. On exit, if INFO = 0 and JOB = 'S', then H contains the upper quasi-triangular matrix T from the Schur decomposition (the Schur form); 2-by-2 diagonal blocks (corresponding to complex conjugate pairs of eigenvalues) are returned in standard form, with H(i,i) = H(i+1,i+1) and H(i+1,i)*H(i,i+1).LT.0. If INFO = 0 and JOB = 'E', the contents of H are unspecified on exit. (The output value of H when INFO.GT.0 is given under the description of INFO below.)
Unlike earlier versions of DHSEQR, this subroutine may explicitly H(i,j) = 0 for i.GT.j and j = 1, 2, ... ILO-1 or j = IHI+1, IHI+2, ... N. /param>
Parameters
LDH (input) INTEGER The leading dimension of the array H. LDH .GE. max(1,N). /param>
Parameters
WR (output) DOUBLE PRECISION array, dimension (N) /param>
Parameters
WI (output) DOUBLE PRECISION array, dimension (N) The real and imaginary parts, respectively, of the computed eigenvalues. If two eigenvalues are computed as a complex conjugate pair, they are stored in consecutive elements of WR and WI, say the i-th and (i+1)th, with WI(i) .GT. 0 and WI(i+1) .LT. 0. If JOB = 'S', the eigenvalues are stored in the same order as on the diagonal of the Schur form returned in H, with WR(i) = H(i,i) and, if H(i:i+1,i:i+1) is a 2-by-2 diagonal block, WI(i) = sqrt(-H(i+1,i)*H(i,i+1)) and WI(i+1) = -WI(i). /param>
Parameters
Z (input/output) DOUBLE PRECISION array, dimension (LDZ,N) If COMPZ = 'N', Z is not referenced. If COMPZ = 'I', on entry Z need not be set and on exit, if INFO = 0, Z contains the orthogonal matrix Z of the Schur vectors of H. If COMPZ = 'V', on entry Z must contain an N-by-N matrix Q, which is assumed to be equal to the unit matrix except for the submatrix Z(ILO:IHI,ILO:IHI). On exit, if INFO = 0, Z contains Q*Z. Normally Q is the orthogonal matrix generated by DORGHR after the call to DGEHRD which formed the Hessenberg matrix H. (The output value of Z when INFO.GT.0 is given under the description of INFO below.) /param>
Parameters
LDZ (input) INTEGER The leading dimension of the array Z. if COMPZ = 'I' or COMPZ = 'V', then LDZ.GE.MAX(1,N). Otherwize, LDZ.GE.1. /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (LWORK) On exit, if INFO = 0, WORK(1) returns an estimate of the optimal value for LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. max(1,N) is sufficient, but LWORK typically as large as 6*N may be required for optimal performance. A workspace query to determine the optimal workspace size is recommended.
If LWORK = -1, then DHSEQR does a workspace query. In this case, DHSEQR checks the input parameters and estimates the optimal workspace size for the given values of N, ILO and IHI. The estimate is returned in WORK(1). No error message related to LWORK is issued by XERBLA. Neither H nor Z are accessed.
/param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value .GT. 0: if INFO = i, DHSEQR failed to compute all of the eigenvalues. Elements 1:ilo-1 and i+1:n of WR and WI contain those eigenvalues which have been successfully computed. (Failures are rare.)
If INFO .GT. 0 and JOB = 'E', then on exit, the remaining unconverged eigenvalues are the eigen- values of the upper Hessenberg matrix rows and columns ILO through INFO of the final, output value of H.
If INFO .GT. 0 and JOB = 'S', then on exit
(*) (initial value of H)*U = U*(final value of H)
where U is an orthogonal matrix. The final value of H is upper Hessenberg and quasi-triangular in rows and columns INFO+1 through IHI.
If INFO .GT. 0 and COMPZ = 'V', then on exit
(final value of Z) = (initial value of Z)*U
where U is the orthogonal matrix in (*) (regard- less of the value of JOB.)
If INFO .GT. 0 and COMPZ = 'I', then on exit (final value of Z) = U where U is the orthogonal matrix in (*) (regard- less of the value of JOB.)
If INFO .GT. 0 and COMPZ = 'N', then Z is not accessed. /param>
References DotNumerics.LinearAlgebra.CSLapack.DHSEQR.HL, DotNumerics.LinearAlgebra.CSLapack.DHSEQR.NL, DotNumerics.LinearAlgebra.CSLapack.DHSEQR.NTINY, DotNumerics.LinearAlgebra.CSLapack.DHSEQR.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASET.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAHQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR0.Run(), DotNumerics.FortranLibrary.FortranLib.Substring(), DotNumerics.LinearAlgebra.CSLapack.DHSEQR.WORKL, and DotNumerics.LinearAlgebra.CSLapack.DHSEQR.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run().
Member Data Documentation
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DHSEQR._ilaenv private
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DHSEQR._lsame private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DHSEQR._dlacpy private
_dlahqr
DLAHQR DotNumerics.LinearAlgebra.CSLapack.DHSEQR._dlahqr private
_dlaqr0
DLAQR0 DotNumerics.LinearAlgebra.CSLapack.DHSEQR._dlaqr0 private
_dlaset
DLASET DotNumerics.LinearAlgebra.CSLapack.DHSEQR._dlaset private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DHSEQR._xerbla private
NTINY
const int DotNumerics.LinearAlgebra.CSLapack.DHSEQR.NTINY = 11 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DHSEQR.Run().
NL
const int DotNumerics.LinearAlgebra.CSLapack.DHSEQR.NL = 49 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DHSEQR.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DHSEQR.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DHSEQR.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DHSEQR.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DHSEQR.Run().
HL
double [] DotNumerics.LinearAlgebra.CSLapack.DHSEQR.HL = new double[NL * NL] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DHSEQR.Run().
WORKL
double [] DotNumerics.LinearAlgebra.CSLapack.DHSEQR.WORKL = new double[NL] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DHSEQR.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dhseqr.cs