Doc: IGLib EXTENDED: AForge.Imaging.Filters.HistogramEqualization Class Reference
AForge.Imaging.Filters.HistogramEqualization Class Reference
Histogram equalization filter.
Public Member Functions
HistogramEqualization ()
Initializes a new instance of the HistogramEqualization class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image, Rectangle rect)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Member Functions
byte[] Equalize (int[] histogram, long numPixel)
Private Attributes
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Histogram equalization filter.
The filter does histogram equalization increasing local contrast in images. The effect of histogram equalization can be better seen on images, where pixel values have close contrast values. Through this adjustment, pixels intensities can be better distributed on the histogram. This allows for areas of lower local contrast to gain a higher contrast without affecting the global contrast.
The filter accepts 8 bpp grayscale images and 24/32 bpp color images for processing.
<note>For color images the histogram equalization is applied to each color plane separately.</note>
Sample usage:
// create filter
HistogramEqualization filter = new HistogramEqualization();
// process image
filter.ApplyInPlace(sourceImage);
Source image:
Result image:
Constructor & Destructor Documentation
HistogramEqualization()
AForge.Imaging.Filters.HistogramEqualization.HistogramEqualization () inline
Initializes a new instance of the HistogramEqualization class.
References AForge.Imaging.Filters.HistogramEqualization.formatTranslations.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.HistogramEqualization.ProcessFilter (UnmanagedImage image, Rectangle rect) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
rect Image rectangle for processing by the filter.
Implements AForge.Imaging.Filters.BaseInPlacePartialFilter.
References AForge.Imaging.RGB.B, AForge.Imaging.Filters.HistogramEqualization.Equalize(), AForge.Imaging.RGB.G, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, and AForge.Imaging.UnmanagedImage.Stride.
Equalize()
byte [] AForge.Imaging.Filters.HistogramEqualization.Equalize (int[] histogram, long numPixel) inline private
Referenced by AForge.Imaging.Filters.HistogramEqualization.ProcessFilter().
Member Data Documentation
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.HistogramEqualization.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.HistogramEqualization.HistogramEqualization().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.HistogramEqualization.FormatTranslations get
Format translations dictionary.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Color Filters/HistogramEqualization.cs