Doc: IGLib EXTENDED: NUnit.Framework.Internal.ResultStateTests Class Reference
NUnit.Framework.Internal.ResultStateTests Class Reference
Public Member Functions
void Status_ConstructorWithOneArguments_ReturnsConstructorArgumentStatus (TestStatus status)
void Label_ConstructorWithOneArguments_ReturnsStringEmpty ()
void Status_ConstructorWithTwoArguments_ReturnsConstructorArgumentStatus (TestStatus status)
void Label_ConstructorWithTwoArguments_ReturnsConstructorArgumentLabel (string label)
void Label_ConstructorWithTwoArgumentsLabelArgumentIsNull_ReturnsEmptyString ()
void Site_ConstructorWithOneArguments_ReturnsTest ()
void Site_ConstructorWithTwoArguments_ReturnsTest (string label)
void Site_ConstructorWithThreeArguments_ReturnsSite (string label, FailureSite site)
void ToString_Constructor_ReturnsExpectedString (TestStatus status, string label, string expected)
void TestEquality_StatusSpecified ()
void TestEquality_StatusAndLabelSpecified ()
void TestEquality_StatusAndSiteSpecified ()
void TestEquality_StatusLabelAndSiteSpecified ()
void TestEquality_StatusDiffers ()
void TestEquality_LabelDiffers ()
void TestEquality_SiteDiffers ()
void TestEquality_WrongType ()
void TestEquality_Null ()
void AddSiteToResult (TestStatus status, string label, FailureSite site)
void Inconclusive_ReturnsResultStateWithPropertiesCorrectlySet ()
void NotRunnable_ReturnsResultStateWithPropertiesCorrectlySet ()
void Skipped_ReturnsResultStateWithPropertiesCorrectlySet ()
void Ignored_ReturnsResultStateWithPropertiesCorrectlySet ()
void Success_ReturnsResultStateWithPropertiesCorrectlySet ()
void Failure_ReturnsResultStateWithPropertiesCorrectlySet ()
void ChildFailure_ReturnsResultStateWithPropertiesSet ()
void Error_ReturnsResultStateWithPropertiesCorrectlySet ()
void Cancelled_ReturnsResultStateWithPropertiesCorrectlySet ()
Member Function Documentation
Status_ConstructorWithOneArguments_ReturnsConstructorArgumentStatus()
void NUnit.Framework.Internal.ResultStateTests.Status_ConstructorWithOneArguments_ReturnsConstructorArgumentStatus (TestStatus status) inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Interfaces.ResultState.Status.
Label_ConstructorWithOneArguments_ReturnsStringEmpty()
void NUnit.Framework.Internal.ResultStateTests.Label_ConstructorWithOneArguments_ReturnsStringEmpty () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Interfaces.ResultState.Label.
Status_ConstructorWithTwoArguments_ReturnsConstructorArgumentStatus()
void NUnit.Framework.Internal.ResultStateTests.Status_ConstructorWithTwoArguments_ReturnsConstructorArgumentStatus (TestStatus status) inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Interfaces.ResultState.Status.
Label_ConstructorWithTwoArguments_ReturnsConstructorArgumentLabel()
void NUnit.Framework.Internal.ResultStateTests.Label_ConstructorWithTwoArguments_ReturnsConstructorArgumentLabel (string label) inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Interfaces.ResultState.Label.
Label_ConstructorWithTwoArgumentsLabelArgumentIsNull_ReturnsEmptyString()
void NUnit.Framework.Internal.ResultStateTests.Label_ConstructorWithTwoArgumentsLabelArgumentIsNull_ReturnsEmptyString () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Interfaces.ResultState.Label.
Site_ConstructorWithOneArguments_ReturnsTest()
void NUnit.Framework.Internal.ResultStateTests.Site_ConstructorWithOneArguments_ReturnsTest () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Interfaces.ResultState.Site.
Site_ConstructorWithTwoArguments_ReturnsTest()
void NUnit.Framework.Internal.ResultStateTests.Site_ConstructorWithTwoArguments_ReturnsTest (string label) inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Interfaces.ResultState.Site.
Site_ConstructorWithThreeArguments_ReturnsSite()
void NUnit.Framework.Internal.ResultStateTests.Site_ConstructorWithThreeArguments_ReturnsSite (string label, FailureSite site) inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Interfaces.ResultState.Site.
ToString_Constructor_ReturnsExpectedString()
void NUnit.Framework.Internal.ResultStateTests.ToString_Constructor_ReturnsExpectedString (TestStatus status, string label, string expected) inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Interfaces.ResultState.ToString().
TestEquality_StatusSpecified()
void NUnit.Framework.Internal.ResultStateTests.TestEquality_StatusSpecified () inline
References NUnit.Framework.Assert.AreEqual().
TestEquality_StatusAndLabelSpecified()
void NUnit.Framework.Internal.ResultStateTests.TestEquality_StatusAndLabelSpecified () inline
References NUnit.Framework.Assert.AreEqual().
TestEquality_StatusAndSiteSpecified()
void NUnit.Framework.Internal.ResultStateTests.TestEquality_StatusAndSiteSpecified () inline
References NUnit.Framework.Assert.AreEqual().
TestEquality_StatusLabelAndSiteSpecified()
void NUnit.Framework.Internal.ResultStateTests.TestEquality_StatusLabelAndSiteSpecified () inline
References NUnit.Framework.Assert.AreEqual().
TestEquality_StatusDiffers()
void NUnit.Framework.Internal.ResultStateTests.TestEquality_StatusDiffers () inline
References NUnit.Framework.Assert.AreNotEqual().
TestEquality_LabelDiffers()
void NUnit.Framework.Internal.ResultStateTests.TestEquality_LabelDiffers () inline
References NUnit.Framework.Assert.AreNotEqual().
TestEquality_SiteDiffers()
void NUnit.Framework.Internal.ResultStateTests.TestEquality_SiteDiffers () inline
References NUnit.Framework.Assert.AreNotEqual().
TestEquality_WrongType()
void NUnit.Framework.Internal.ResultStateTests.TestEquality_WrongType () inline
References NUnit.Framework.Assert.AreNotEqual(), and NUnit.Framework.Assert.False().
TestEquality_Null()
void NUnit.Framework.Internal.ResultStateTests.TestEquality_Null () inline
References NUnit.Framework.Assert.AreNotEqual(), and NUnit.Framework.Assert.False().
AddSiteToResult()
void NUnit.Framework.Internal.ResultStateTests.AddSiteToResult (TestStatus status, string label, FailureSite site) inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Interfaces.ResultState.WithSite().
Inconclusive_ReturnsResultStateWithPropertiesCorrectlySet()
void NUnit.Framework.Internal.ResultStateTests.Inconclusive_ReturnsResultStateWithPropertiesCorrectlySet () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.Inconclusive, NUnit.Framework.Interfaces.ResultState.Label, NUnit.Framework.Interfaces.ResultState.Site, and NUnit.Framework.Interfaces.ResultState.Status.
NotRunnable_ReturnsResultStateWithPropertiesCorrectlySet()
void NUnit.Framework.Internal.ResultStateTests.NotRunnable_ReturnsResultStateWithPropertiesCorrectlySet () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.Label, NUnit.Framework.Interfaces.ResultState.NotRunnable, NUnit.Framework.Interfaces.ResultState.Site, and NUnit.Framework.Interfaces.ResultState.Status.
Skipped_ReturnsResultStateWithPropertiesCorrectlySet()
void NUnit.Framework.Internal.ResultStateTests.Skipped_ReturnsResultStateWithPropertiesCorrectlySet () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.Label, NUnit.Framework.Interfaces.ResultState.Site, NUnit.Framework.Interfaces.ResultState.Skipped, and NUnit.Framework.Interfaces.ResultState.Status.
Ignored_ReturnsResultStateWithPropertiesCorrectlySet()
void NUnit.Framework.Internal.ResultStateTests.Ignored_ReturnsResultStateWithPropertiesCorrectlySet () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.Ignored, NUnit.Framework.Interfaces.ResultState.Label, NUnit.Framework.Interfaces.ResultState.Site, and NUnit.Framework.Interfaces.ResultState.Status.
Success_ReturnsResultStateWithPropertiesCorrectlySet()
void NUnit.Framework.Internal.ResultStateTests.Success_ReturnsResultStateWithPropertiesCorrectlySet () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.Label, NUnit.Framework.Interfaces.ResultState.Site, NUnit.Framework.Interfaces.ResultState.Status, and NUnit.Framework.Interfaces.ResultState.Success.
Failure_ReturnsResultStateWithPropertiesCorrectlySet()
void NUnit.Framework.Internal.ResultStateTests.Failure_ReturnsResultStateWithPropertiesCorrectlySet () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.Failure, NUnit.Framework.Interfaces.ResultState.Label, NUnit.Framework.Interfaces.ResultState.Site, and NUnit.Framework.Interfaces.ResultState.Status.
ChildFailure_ReturnsResultStateWithPropertiesSet()
void NUnit.Framework.Internal.ResultStateTests.ChildFailure_ReturnsResultStateWithPropertiesSet () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.ChildFailure, NUnit.Framework.Interfaces.ResultState.Label, NUnit.Framework.Interfaces.ResultState.Site, and NUnit.Framework.Interfaces.ResultState.Status.
Error_ReturnsResultStateWithPropertiesCorrectlySet()
void NUnit.Framework.Internal.ResultStateTests.Error_ReturnsResultStateWithPropertiesCorrectlySet () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.Error, NUnit.Framework.Interfaces.ResultState.Label, NUnit.Framework.Interfaces.ResultState.Site, and NUnit.Framework.Interfaces.ResultState.Status.
Cancelled_ReturnsResultStateWithPropertiesCorrectlySet()
void NUnit.Framework.Internal.ResultStateTests.Cancelled_ReturnsResultStateWithPropertiesCorrectlySet () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.Cancelled, NUnit.Framework.Interfaces.ResultState.Label, NUnit.Framework.Interfaces.ResultState.Site, and NUnit.Framework.Interfaces.ResultState.Status.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Api/ResultStateTests.cs