Doc: IGLib EXTENDED: AForge.Genetic.GPTreeChromosome Class Reference
AForge.Genetic.GPTreeChromosome Class Reference
Tree chromosome represents a tree of genes, which is is used for different tasks of Genetic Programming (GP).
Public Member Functions
GPTreeChromosome (IGPGene ancestor)
Initializes a new instance of the GPTreeChromosome class.
override string ToString ()
Get string representation of the chromosome by providing its expression in reverse polish notation (postfix notation).
override void Generate ()
Generate random chromosome value.
override IChromosome CreateNew ()
Create new random chromosome with same parameters (factory method).
override IChromosome Clone ()
Clone the chromosome.
override void Mutate ()
Mutation operator.
override void Crossover (IChromosome pair)
Crossover operator.
Public Member Functions inherited from AForge.Genetic.ChromosomeBase
void Evaluate (IFitnessFunction function)
Evaluate chromosome with specified fitness function.
int CompareTo (object o)
Compare two chromosomes.
Protected Member Functions
GPTreeChromosome (GPTreeChromosome source)
Initializes a new instance of the GPTreeChromosome class.
void Generate (GPTreeNode node, int level)
Generate chromosome's subtree of specified level.
Static Protected Attributes
static ThreadSafeRandom rand = new ThreadSafeRandom()
Random generator used for chromosoms' generation.
Properties
static int MaxInitialLevel [get, set]
Maximum initial level of genetic trees, [1, 25].
static int MaxLevel [get, set]
Maximum level of genetic trees, [1, 50].
Properties inherited from AForge.Genetic.ChromosomeBase
double Fitness [get]
Chromosome's fintess value.
Properties inherited from AForge.Genetic.IChromosome
double Fitness [get]
Chromosome's fintess value.
Private Member Functions
GPTreeNode RandomSwap (GPTreeNode source)
Crossover helper routine - selects random node of chromosomes tree and swaps it with specified node.
Static Private Member Functions
static void Trim (GPTreeNode node, int level)
Trim tree node, so its depth does not exceed specified level.
Private Attributes
GPTreeNode root = new GPTreeNode()
Static Private Attributes
static int maxInitialLevel = 3
static int maxLevel = 5
Additional Inherited Members
Protected Attributes inherited from AForge.Genetic.ChromosomeBase
double fitness = 0
Chromosome's fintess value.
Detailed Description
Tree chromosome represents a tree of genes, which is is used for different tasks of Genetic Programming (GP).
This type of chromosome represents a tree, where each node is represented by GPTreeNode containing IGPGene. Depending on type of genes used to build the tree, it may represent different types of expressions aimed to solve different type of tasks. For example, a particular implementation of IGPGene interface may represent simple algebraic operations and their arguments.
See documentation to IGPGene implementations for additional information about possible Genetic Programming trees.
Constructor & Destructor Documentation
GPTreeChromosome() [1/2]
AForge.Genetic.GPTreeChromosome.GPTreeChromosome (IGPGene ancestor) inline
Initializes a new instance of the GPTreeChromosome class.
Parameters
ancestor A gene, which is used as generator for the genetic tree.
This constructor creates a randomly generated genetic tree, which has all genes of the same type and properties as the specified ancestor .
References AForge.Genetic.IGPGene.Clone(), AForge.Genetic.GPTreeNode.Gene, AForge.Genetic.GPTreeChromosome.Generate(), and AForge.Genetic.GPTreeChromosome.root.
Referenced by AForge.Genetic.GPTreeChromosome.Clone(), AForge.Genetic.GPTreeChromosome.CreateNew(), and AForge.Genetic.GPTreeChromosome.Crossover().
GPTreeChromosome() [2/2]
AForge.Genetic.GPTreeChromosome.GPTreeChromosome (GPTreeChromosome source) inline protected
Initializes a new instance of the GPTreeChromosome class.
Parameters
source Source genetic tree to clone from.
This constructor creates new genetic tree as a copy of the specified source tree.
References AForge.Genetic.GPTreeNode.Clone(), AForge.Genetic.ChromosomeBase.fitness, and AForge.Genetic.GPTreeChromosome.root.
Member Function Documentation
ToString()
override string AForge.Genetic.GPTreeChromosome.ToString () inline
Get string representation of the chromosome by providing its expression in reverse polish notation (postfix notation).
Returns
Returns string representation of the genetic tree.
The method returns string representation of the tree's root node (see GPTreeNode.ToString).
References AForge.Genetic.GPTreeChromosome.root, and AForge.Genetic.GPTreeNode.ToString().
Generate() [1/2]
override void AForge.Genetic.GPTreeChromosome.Generate () inline virtual
Generate random chromosome value.
Regenerates chromosome's value using random number generator.
Implements AForge.Genetic.ChromosomeBase.
References AForge.Genetic.IGPGene.ArgumentsCount, AForge.Genetic.GPTreeNode.Children, AForge.Genetic.GPTreeNode.Gene, AForge.Genetic.IGPGene.Generate(), AForge.Genetic.GPTreeChromosome.maxInitialLevel, AForge.ThreadSafeRandom.Next(), AForge.Genetic.GPTreeChromosome.rand, and AForge.Genetic.GPTreeChromosome.root.
Referenced by AForge.Genetic.GPTreeChromosome.Generate(), AForge.Genetic.GPTreeChromosome.GPTreeChromosome(), and AForge.Genetic.GPTreeChromosome.Mutate().
Generate() [2/2]
void AForge.Genetic.GPTreeChromosome.Generate (GPTreeNode node, int level) inline protected
Generate chromosome's subtree of specified level.
Parameters
node Sub tree's node to generate.
level Sub tree's level to generate.
References AForge.Genetic.IGPGene.ArgumentsCount, AForge.Genetic.GPTreeNode.Children, AForge.Genetic.IGPGene.CreateNew(), AForge.Genetic.GPTreeNode.Gene, AForge.Genetic.GPTreeChromosome.Generate(), and AForge.Genetic.GPTreeChromosome.root.
CreateNew()
override IChromosome AForge.Genetic.GPTreeChromosome.CreateNew () inline virtual
Create new random chromosome with same parameters (factory method).
The method creates new chromosome of the same type, but randomly initialized. The method is useful as factory method for those classes, which work with chromosome's interface, but not with particular chromosome type.
Implements AForge.Genetic.ChromosomeBase.
References AForge.Genetic.IGPGene.Clone(), AForge.Genetic.GPTreeNode.Gene, AForge.Genetic.GPTreeChromosome.GPTreeChromosome(), and AForge.Genetic.GPTreeChromosome.root.
Clone()
override IChromosome AForge.Genetic.GPTreeChromosome.Clone () inline virtual
Clone the chromosome.
Returns
Return's clone of the chromosome.
The method clones the chromosome returning the exact copy of it.
Implements AForge.Genetic.ChromosomeBase.
References AForge.Genetic.GPTreeChromosome.GPTreeChromosome().
Mutate()
override void AForge.Genetic.GPTreeChromosome.Mutate () inline virtual
Mutation operator.
The method performs chromosome's mutation by regenerating tree's randomly selected node.
Implements AForge.Genetic.ChromosomeBase.
References AForge.Genetic.IGPGene.ArgumentsCount, AForge.Genetic.GPTreeNode.Children, AForge.Genetic.GPTreeNode.Gene, AForge.Genetic.IGPGene.Generate(), AForge.Genetic.GPTreeChromosome.Generate(), AForge.Genetic.IGPGene.GeneType, AForge.Genetic.GPTreeChromosome.maxLevel, AForge.ThreadSafeRandom.Next(), AForge.Genetic.GPTreeChromosome.rand, and AForge.Genetic.GPTreeChromosome.root.
Crossover()
override void AForge.Genetic.GPTreeChromosome.Crossover (IChromosome pair) inline virtual
Crossover operator.
Parameters
pair Pair chromosome to crossover with.
The method performs crossover between two chromosomes – interchanging randomly selected sub trees.
Implements AForge.Genetic.ChromosomeBase.
References AForge.Genetic.IGPGene.ArgumentsCount, AForge.Genetic.GPTreeNode.Children, AForge.Genetic.GPTreeNode.Gene, AForge.Genetic.GPTreeChromosome.GPTreeChromosome(), AForge.Genetic.GPTreeChromosome.maxLevel, AForge.ThreadSafeRandom.Next(), AForge.Genetic.GPTreeChromosome.rand, AForge.Genetic.GPTreeChromosome.root, and AForge.Genetic.GPTreeChromosome.Trim().
RandomSwap()
GPTreeNode AForge.Genetic.GPTreeChromosome.RandomSwap (GPTreeNode source) inline private
Crossover helper routine - selects random node of chromosomes tree and swaps it with specified node.
References AForge.Genetic.IGPGene.ArgumentsCount, AForge.Genetic.GPTreeNode.Children, AForge.Genetic.GPTreeNode.Gene, AForge.Genetic.GPTreeChromosome.maxLevel, AForge.ThreadSafeRandom.Next(), AForge.Genetic.GPTreeChromosome.rand, and AForge.Genetic.GPTreeChromosome.root.
Trim()
static void AForge.Genetic.GPTreeChromosome.Trim (GPTreeNode node, int level) inline static private
Trim tree node, so its depth does not exceed specified level.
References AForge.Genetic.GPTreeNode.Children, AForge.Genetic.GPTreeNode.Gene, and AForge.Genetic.IGPGene.Generate().
Referenced by AForge.Genetic.GPTreeChromosome.Crossover().
Member Data Documentation
root
GPTreeNode AForge.Genetic.GPTreeChromosome.root = new GPTreeNode() private
Referenced by AForge.Genetic.GPTreeChromosome.CreateNew(), AForge.Genetic.GPTreeChromosome.Crossover(), AForge.Genetic.GPTreeChromosome.Generate(), AForge.Genetic.GPTreeChromosome.GPTreeChromosome(), AForge.Genetic.GPTreeChromosome.Mutate(), AForge.Genetic.GPTreeChromosome.RandomSwap(), and AForge.Genetic.GPTreeChromosome.ToString().
maxInitialLevel
int AForge.Genetic.GPTreeChromosome.maxInitialLevel = 3 static private
Referenced by AForge.Genetic.GPTreeChromosome.Generate().
maxLevel
int AForge.Genetic.GPTreeChromosome.maxLevel = 5 static private
Referenced by AForge.Genetic.GPTreeChromosome.Crossover(), AForge.Genetic.GPTreeChromosome.Mutate(), and AForge.Genetic.GPTreeChromosome.RandomSwap().
rand
ThreadSafeRandom AForge.Genetic.GPTreeChromosome.rand = new ThreadSafeRandom() static protected
Random generator used for chromosoms' generation.
Referenced by AForge.Genetic.GPTreeChromosome.Crossover(), AForge.Genetic.GPTreeChromosome.Generate(), AForge.Genetic.GPTreeChromosome.Mutate(), and AForge.Genetic.GPTreeChromosome.RandomSwap().
Property Documentation
MaxInitialLevel
int AForge.Genetic.GPTreeChromosome.MaxInitialLevel static get set
Maximum initial level of genetic trees, [1, 25].
The property sets maximum possible initial depth of new genetic programming tree. For example, if it is set to 1, then largest initial tree may have a root and one level of children.
Default value is set to 3.
Referenced by TimeSeries.MainForm.moreSettingsButton_Click().
MaxLevel
int AForge.Genetic.GPTreeChromosome.MaxLevel static get set
Maximum level of genetic trees, [1, 50].
The property sets maximum possible depth of genetic programming tree, which may be created with mutation and crossover operators. This property guarantees that genetic programmin tree will never have higher depth, than the specified value.
Default value is set to 5.
Referenced by TimeSeries.MainForm.moreSettingsButton_Click().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Genetic/Chromosomes/GP/GPTreeChromosome.cs