Doc: IGLib EXTENDED: NUnit.Engine.Services.Tests.TestFilterBuilderTests Class Reference
NUnit.Engine.Services.Tests.TestFilterBuilderTests Class Reference
Public Member Functions
void CreateBuilder ()
void EmptyFilter ()
void OneTestSelected ()
void OneTestSelected_XmlEscape ()
void ThreeTestsSelected ()
void WhereClause ()
void WhereClause_XmlEscape ()
void OneTestAndWhereClause ()
Private Attributes
TestFilterBuilder builder
Member Function Documentation
CreateBuilder()
void NUnit.Engine.Services.Tests.TestFilterBuilderTests.CreateBuilder () inline
EmptyFilter()
void NUnit.Engine.Services.Tests.TestFilterBuilderTests.EmptyFilter () inline
References NUnit.Engine.Services.Tests.TestFilterBuilderTests.builder, NUnit.Framework.Is.EqualTo(), NUnit.Engine.TestFilterBuilder.GetFilter(), NUnit.Engine.TestFilter.Text, and NUnit.Framework.Assert.That().
OneTestSelected()
void NUnit.Engine.Services.Tests.TestFilterBuilderTests.OneTestSelected () inline
References NUnit.Engine.TestFilterBuilder.AddTest(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.builder, NUnit.Framework.Is.EqualTo(), NUnit.Engine.TestFilterBuilder.GetFilter(), NUnit.Engine.TestFilter.Text, and NUnit.Framework.Assert.That().
OneTestSelected_XmlEscape()
void NUnit.Engine.Services.Tests.TestFilterBuilderTests.OneTestSelected_XmlEscape () inline
References NUnit.Engine.TestFilterBuilder.AddTest(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.builder, NUnit.Framework.Is.EqualTo(), NUnit.Engine.TestFilterBuilder.GetFilter(), NUnit.Engine.TestFilter.Text, and NUnit.Framework.Assert.That().
ThreeTestsSelected()
void NUnit.Engine.Services.Tests.TestFilterBuilderTests.ThreeTestsSelected () inline
References NUnit.Engine.TestFilterBuilder.AddTest(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.builder, NUnit.Framework.Is.EqualTo(), NUnit.Engine.TestFilterBuilder.GetFilter(), NUnit.Engine.TestFilter.Text, and NUnit.Framework.Assert.That().
WhereClause()
void NUnit.Engine.Services.Tests.TestFilterBuilderTests.WhereClause () inline
References NUnit.Engine.Services.Tests.TestFilterBuilderTests.builder, NUnit.Framework.Is.EqualTo(), NUnit.Engine.TestFilterBuilder.GetFilter(), NUnit.Engine.TestFilterBuilder.SelectWhere(), NUnit.Engine.TestFilter.Text, and NUnit.Framework.Assert.That().
WhereClause_XmlEscape()
void NUnit.Engine.Services.Tests.TestFilterBuilderTests.WhereClause_XmlEscape () inline
References NUnit.Engine.Services.Tests.TestFilterBuilderTests.builder, NUnit.Framework.Is.EqualTo(), NUnit.Engine.TestFilterBuilder.GetFilter(), NUnit.Engine.TestFilterBuilder.SelectWhere(), NUnit.Engine.TestFilter.Text, and NUnit.Framework.Assert.That().
OneTestAndWhereClause()
void NUnit.Engine.Services.Tests.TestFilterBuilderTests.OneTestAndWhereClause () inline
References NUnit.Engine.TestFilterBuilder.AddTest(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.builder, NUnit.Framework.Is.EqualTo(), NUnit.Engine.TestFilterBuilder.GetFilter(), NUnit.Engine.TestFilterBuilder.SelectWhere(), NUnit.Engine.TestFilter.Text, and NUnit.Framework.Assert.That().
Member Data Documentation
builder
TestFilterBuilder NUnit.Engine.Services.Tests.TestFilterBuilderTests.builder private
Referenced by NUnit.Engine.Services.Tests.TestFilterBuilderTests.EmptyFilter(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.OneTestAndWhereClause(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.OneTestSelected(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.OneTestSelected_XmlEscape(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.ThreeTestsSelected(), NUnit.Engine.Services.Tests.TestFilterBuilderTests.WhereClause(), and NUnit.Engine.Services.Tests.TestFilterBuilderTests.WhereClause_XmlEscape().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Services/TestFilterBuilderTests.cs