Doc: IGLib EXTENDED: NUnit.Framework.StringAssert Class Reference
NUnit.Framework.StringAssert Class Reference
Basic Asserts on strings.
Static Public Member Functions
static new bool Equals (object a, object b)
The Equals method throws an AssertionException. This is done to make sure there is no mistake by calling this function.
static new void ReferenceEquals (object a, object b)
override the default ReferenceEquals to throw an AssertionException. This implementation makes sure there is no mistake in calling this function as part of Assert.
static void Contains (string expected, string actual, string message, params object[] args)
Asserts that a string is found within another string.
static void Contains (string expected, string actual)
Asserts that a string is found within another string.
static void DoesNotContain (string expected, string actual, string message, params object[] args)
Asserts that a string is not found within another string.
static void DoesNotContain (string expected, string actual)
Asserts that a string is found within another string.
static void StartsWith (string expected, string actual, string message, params object[] args)
Asserts that a string starts with another string.
static void StartsWith (string expected, string actual)
Asserts that a string starts with another string.
static void DoesNotStartWith (string expected, string actual, string message, params object[] args)
Asserts that a string does not start with another string.
static void DoesNotStartWith (string expected, string actual)
Asserts that a string does not start with another string.
static void EndsWith (string expected, string actual, string message, params object[] args)
Asserts that a string ends with another string.
static void EndsWith (string expected, string actual)
Asserts that a string ends with another string.
static void DoesNotEndWith (string expected, string actual, string message, params object[] args)
Asserts that a string does not end with another string.
static void DoesNotEndWith (string expected, string actual)
Asserts that a string does not end with another string.
static void AreEqualIgnoringCase (string expected, string actual, string message, params object[] args)
Asserts that two strings are equal, without regard to case.
static void AreEqualIgnoringCase (string expected, string actual)
Asserts that two strings are equal, without regard to case.
static void AreNotEqualIgnoringCase (string expected, string actual, string message, params object[] args)
Asserts that two strings are not equal, without regard to case.
static void AreNotEqualIgnoringCase (string expected, string actual)
Asserts that two strings are not equal, without regard to case.
static void IsMatch (string pattern, string actual, string message, params object[] args)
Asserts that a string matches an expected regular expression pattern.
static void IsMatch (string pattern, string actual)
Asserts that a string matches an expected regular expression pattern.
static void DoesNotMatch (string pattern, string actual, string message, params object[] args)
Asserts that a string does not match an expected regular expression pattern.
static void DoesNotMatch (string pattern, string actual)
Asserts that a string does not match an expected regular expression pattern.
Detailed Description
Basic Asserts on strings.
Member Function Documentation
Equals()
static new bool NUnit.Framework.StringAssert.Equals (object a, object b) inline static
The Equals method throws an AssertionException. This is done to make sure there is no mistake by calling this function.
Parameters
a
b
ReferenceEquals()
static new void NUnit.Framework.StringAssert.ReferenceEquals (object a, object b) inline static
override the default ReferenceEquals to throw an AssertionException. This implementation makes sure there is no mistake in calling this function as part of Assert.
Parameters
a
b
Contains() [1/2]
static void NUnit.Framework.StringAssert.Contains (string expected, string actual, string message, params object[] args) inline static
Asserts that a string is found within another string.
Parameters
expected The expected string
actual The string to be examined
message The message to display in case of failure
args Arguments used in formatting the message
References NUnit.Framework.Does.Contain(), and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Assertions.StringAssertTests.Contains(), NUnit.Framework.StringAssert.Contains(), NUnit.Framework.Assertions.StringAssertTests.ContainsFails(), NUnit.Framework.Assertions.LessFixture.FailureMessage(), NUnit.Framework.Assertions.GreaterEqualFixture.FailureMessage(), and NUnit.Framework.Tests.AssertSyntaxTests.SubstringTests().
Contains() [2/2]
static void NUnit.Framework.StringAssert.Contains (string expected, string actual) inline static
Asserts that a string is found within another string.
Parameters
expected The expected string
actual The string to be examined
References NUnit.Framework.StringAssert.Contains().
DoesNotContain() [1/2]
static void NUnit.Framework.StringAssert.DoesNotContain (string expected, string actual, string message, params object[] args) inline static
Asserts that a string is not found within another string.
Parameters
expected The expected string
actual The string to be examined
message The message to display in case of failure
args Arguments used in formatting the message
References NUnit.Framework.Constraints.ConstraintExpression.Contain(), NUnit.Framework.Does.Not, and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Assertions.StringAssertTests.DoesNotContain(), NUnit.Framework.StringAssert.DoesNotContain(), and NUnit.Framework.Assertions.StringAssertTests.DoesNotContainFails().
DoesNotContain() [2/2]
static void NUnit.Framework.StringAssert.DoesNotContain (string expected, string actual) inline static
Asserts that a string is found within another string.
Parameters
expected The expected string
actual The string to be examined
References NUnit.Framework.StringAssert.DoesNotContain().
StartsWith() [1/2]
static void NUnit.Framework.StringAssert.StartsWith (string expected, string actual, string message, params object[] args) inline static
Asserts that a string starts with another string.
Parameters
expected The expected string
actual The string to be examined
message The message to display in case of failure
args Arguments used in formatting the message
References NUnit.Framework.Does.StartWith(), and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Assertions.StringAssertTests.StartsWith(), NUnit.Framework.StringAssert.StartsWith(), NUnit.Framework.Assertions.StringAssertTests.StartsWithFails(), and NUnit.Framework.Tests.AssertSyntaxTests.StartsWithTests().
StartsWith() [2/2]
static void NUnit.Framework.StringAssert.StartsWith (string expected, string actual) inline static
Asserts that a string starts with another string.
Parameters
expected The expected string
actual The string to be examined
References NUnit.Framework.StringAssert.StartsWith().
DoesNotStartWith() [1/2]
static void NUnit.Framework.StringAssert.DoesNotStartWith (string expected, string actual, string message, params object[] args) inline static
Asserts that a string does not start with another string.
Parameters
expected The expected string
actual The string to be examined
message The message to display in case of failure
args Arguments used in formatting the message
References NUnit.Framework.Does.Not, NUnit.Framework.Constraints.ConstraintExpression.StartWith(), and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Assertions.StringAssertTests.DoesNotStartWith(), NUnit.Framework.StringAssert.DoesNotStartWith(), and NUnit.Framework.Assertions.StringAssertTests.DoesNotStartWithFails().
DoesNotStartWith() [2/2]
static void NUnit.Framework.StringAssert.DoesNotStartWith (string expected, string actual) inline static
Asserts that a string does not start with another string.
Parameters
expected The expected string
actual The string to be examined
References NUnit.Framework.StringAssert.DoesNotStartWith().
EndsWith() [1/2]
static void NUnit.Framework.StringAssert.EndsWith (string expected, string actual, string message, params object[] args) inline static
Asserts that a string ends with another string.
Parameters
expected The expected string
actual The string to be examined
message The message to display in case of failure
args Arguments used in formatting the message
References NUnit.Framework.Does.EndWith(), and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Assertions.StringAssertTests.EndsWith(), NUnit.Framework.StringAssert.EndsWith(), NUnit.Framework.Assertions.StringAssertTests.EndsWithFails(), and NUnit.Framework.Tests.AssertSyntaxTests.EndsWithTests().
EndsWith() [2/2]
static void NUnit.Framework.StringAssert.EndsWith (string expected, string actual) inline static
Asserts that a string ends with another string.
Parameters
expected The expected string
actual The string to be examined
References NUnit.Framework.StringAssert.EndsWith().
DoesNotEndWith() [1/2]
static void NUnit.Framework.StringAssert.DoesNotEndWith (string expected, string actual, string message, params object[] args) inline static
Asserts that a string does not end with another string.
Parameters
expected The expected string
actual The string to be examined
message The message to display in case of failure
args Arguments used in formatting the message
References NUnit.Framework.Constraints.ConstraintExpression.EndWith(), NUnit.Framework.Does.Not, and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.Assertions.StringAssertTests.DoesNotEndWith(), NUnit.Framework.StringAssert.DoesNotEndWith(), and NUnit.Framework.Assertions.StringAssertTests.DoesNotEndWithFails().
DoesNotEndWith() [2/2]
static void NUnit.Framework.StringAssert.DoesNotEndWith (string expected, string actual) inline static
Asserts that a string does not end with another string.
Parameters
expected The expected string
actual The string to be examined
References NUnit.Framework.StringAssert.DoesNotEndWith().
AreEqualIgnoringCase() [1/2]
static void NUnit.Framework.StringAssert.AreEqualIgnoringCase (string expected, string actual, string message, params object[] args) inline static
Asserts that two strings are equal, without regard to case.
Parameters
expected The expected string
actual The actual string
message The message to display in case of failure
args Arguments used in formatting the message
Referenced by NUnit.Framework.StringAssert.AreEqualIgnoringCase(), NUnit.Framework.Assertions.StringAssertTests.CaseInsensitiveCompare(), NUnit.Framework.Assertions.StringAssertTests.CaseInsensitiveCompareFails(), and NUnit.Framework.Tests.AssertSyntaxTests.EqualIgnoringCaseTests().
AreEqualIgnoringCase() [2/2]
static void NUnit.Framework.StringAssert.AreEqualIgnoringCase (string expected, string actual) inline static
Asserts that two strings are equal, without regard to case.
Parameters
expected The expected string
actual The actual string
References NUnit.Framework.StringAssert.AreEqualIgnoringCase().
AreNotEqualIgnoringCase() [1/2]
static void NUnit.Framework.StringAssert.AreNotEqualIgnoringCase (string expected, string actual, string message, params object[] args) inline static
Asserts that two strings are not equal, without regard to case.
Parameters
expected The expected string
actual The actual string
message The message to display in case of failure
args Arguments used in formatting the message
Referenced by NUnit.Framework.StringAssert.AreNotEqualIgnoringCase().
AreNotEqualIgnoringCase() [2/2]
static void NUnit.Framework.StringAssert.AreNotEqualIgnoringCase (string expected, string actual) inline static
Asserts that two strings are not equal, without regard to case.
Parameters
expected The expected string
actual The actual string
References NUnit.Framework.StringAssert.AreNotEqualIgnoringCase().
IsMatch() [1/2]
static void NUnit.Framework.StringAssert.IsMatch (string pattern, string actual, string message, params object[] args) inline static
Asserts that a string matches an expected regular expression pattern.
Parameters
pattern The regex pattern to be matched
actual The actual string
message The message to display in case of failure
args Arguments used in formatting the message
Referenced by NUnit.Framework.Assertions.StringAssertTests.IsMatch(), NUnit.Framework.StringAssert.IsMatch(), NUnit.Framework.Assertions.StringAssertTests.IsMatchFails(), and NUnit.Framework.Tests.AssertSyntaxTests.RegularExpressionTests().
IsMatch() [2/2]
static void NUnit.Framework.StringAssert.IsMatch (string pattern, string actual) inline static
Asserts that a string matches an expected regular expression pattern.
Parameters
pattern The regex pattern to be matched
actual The actual string
References NUnit.Framework.StringAssert.IsMatch().
DoesNotMatch() [1/2]
static void NUnit.Framework.StringAssert.DoesNotMatch (string pattern, string actual, string message, params object[] args) inline static
Asserts that a string does not match an expected regular expression pattern.
Parameters
pattern The regex pattern to be used
actual The actual string
message The message to display in case of failure
args Arguments used in formatting the message
Referenced by NUnit.Framework.StringAssert.DoesNotMatch().
DoesNotMatch() [2/2]
static void NUnit.Framework.StringAssert.DoesNotMatch (string pattern, string actual) inline static
Asserts that a string does not match an expected regular expression pattern.
Parameters
pattern The regex pattern to be used
actual The actual string
References NUnit.Framework.StringAssert.DoesNotMatch().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/StringAssert.cs