Doc: IGLib EXTENDED: NUnit.Framework.Internal.GenericTestMethodTests Class Reference
NUnit.Framework.Internal.GenericTestMethodTests Class Reference
Public Member Functions
void TestCase_OneTypeParameterOnTwoArgs< T > (T x, T y, string label)
void TestCase_IncompatibleArgsAreNotRunnable ()
void TestCase_TwoTypeParameters< T1, T2 > (T1 x, T2 y, string label)
void TestCase_TwoTypeParameters_Reversed< T1, T2 > (T2 x, T1 y, string label)
void TestCaseSource_OneTypeParameterOnTwoArgs< T > (T x, T y, string label)
void TestCaseSource_IncompatibleArgsAreNotRunnable ()
void TestCaseSource_TwoTypeParameters< T1, T2 > (T1 x, T2 y, string label)
void Combinatorial_OneTypeParameterOnTwoArgs< T > ([Values(5, 5.0)] T x, [Values(2.0, 2)] T y)
void Combinatorial_TwoTypeParameters< T1, T2 > ([Values(5, 5.0)] T1 x, [Values(2.0, 2)] T2 y)
void Combinatorial_IncompatibleArgsAreNotRunnable ()
Static Private Attributes
static readonly object[] Source
Member Function Documentation
TestCase_OneTypeParameterOnTwoArgs< T >()
void NUnit.Framework.Internal.GenericTestMethodTests.TestCase_OneTypeParameterOnTwoArgs< T > (T x, T y, string label) inline
References NUnit.Framework.Assert.AreEqual().
TestCase_IncompatibleArgsAreNotRunnable()
void NUnit.Framework.Internal.GenericTestMethodTests.TestCase_IncompatibleArgsAreNotRunnable () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.NotRunnable, NUnit.TestUtilities.TestBuilder.RunTestFixture(), and NUnit.Framework.Assert.That().
TestCase_TwoTypeParameters< T1, T2 >()
void NUnit.Framework.Internal.GenericTestMethodTests.TestCase_TwoTypeParameters< T1, T2 > (T1 x, T2 y, string label) inline
References NUnit.Framework.Assert.AreEqual().
TestCase_TwoTypeParameters_Reversed< T1, T2 >()
void NUnit.Framework.Internal.GenericTestMethodTests.TestCase_TwoTypeParameters_Reversed< T1, T2 > (T2 x, T1 y, string label) inline
References NUnit.Framework.Assert.AreEqual().
TestCaseSource_OneTypeParameterOnTwoArgs< T >()
void NUnit.Framework.Internal.GenericTestMethodTests.TestCaseSource_OneTypeParameterOnTwoArgs< T > (T x, T y, string label) inline
References NUnit.Framework.Assert.AreEqual().
TestCaseSource_IncompatibleArgsAreNotRunnable()
void NUnit.Framework.Internal.GenericTestMethodTests.TestCaseSource_IncompatibleArgsAreNotRunnable () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.NotRunnable, NUnit.TestUtilities.TestBuilder.RunTestFixture(), and NUnit.Framework.Assert.That().
TestCaseSource_TwoTypeParameters< T1, T2 >()
void NUnit.Framework.Internal.GenericTestMethodTests.TestCaseSource_TwoTypeParameters< T1, T2 > (T1 x, T2 y, string label) inline
References NUnit.Framework.Assert.AreEqual().
Combinatorial_OneTypeParameterOnTwoArgs< T >()
void NUnit.Framework.Internal.GenericTestMethodTests.Combinatorial_OneTypeParameterOnTwoArgs< T > ([Values(5, 5.0)] T x, [Values(2.0, 2)] T y) inline
References NUnit.Framework.Assert.AreEqual().
Combinatorial_TwoTypeParameters< T1, T2 >()
void NUnit.Framework.Internal.GenericTestMethodTests.Combinatorial_TwoTypeParameters< T1, T2 > ([Values(5, 5.0)] T1 x, [Values(2.0, 2)] T2 y) inline
References NUnit.Framework.Assert.AreEqual().
Combinatorial_IncompatibleArgsAreNotRunnable()
void NUnit.Framework.Internal.GenericTestMethodTests.Combinatorial_IncompatibleArgsAreNotRunnable () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.ResultState.NotRunnable, NUnit.TestUtilities.TestBuilder.RunTestFixture(), and NUnit.Framework.Assert.That().
Member Data Documentation
Source
readonly object [] NUnit.Framework.Internal.GenericTestMethodTests.Source static private
Initial value:
= new object[] {
            new object[] { 5, 2, "ABC" },
            new object[] { 5.0, 2.0, "ABC" },
            new object[] { 5, 2.0, "ABC" },
            new object[] { 5.0, 2L, "ABC" }
        }
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/GenericTestMethodTests.cs