Doc: IGLib EXTENDED: alglib.ratint Class Reference
alglib.ratint Class Reference
Classes
class barycentricinterpolant
Static Public Member Functions
static double barycentriccalc (barycentricinterpolant b, double t)
static void barycentricdiff1 (barycentricinterpolant b, double t, ref double f, ref double df)
static void barycentricdiff2 (barycentricinterpolant b, double t, ref double f, ref double df, ref double d2f)
static void barycentriclintransx (barycentricinterpolant b, double ca, double cb)
static void barycentriclintransy (barycentricinterpolant b, double ca, double cb)
static void barycentricunpack (barycentricinterpolant b, ref int n, ref double[] x, ref double[] y, ref double[] w)
static void barycentricbuildxyw (double[] x, double[] y, double[] w, int n, barycentricinterpolant b)
static void barycentricbuildfloaterhormann (double[] x, double[] y, int n, int d, barycentricinterpolant b)
static void barycentriccopy (barycentricinterpolant b, barycentricinterpolant b2)
static double barycentriccalc (barycentricinterpolant b, double t)
static void barycentricdiff1 (barycentricinterpolant b, double t, ref double f, ref double df)
static void barycentricdiff2 (barycentricinterpolant b, double t, ref double f, ref double df, ref double d2f)
static void barycentriclintransx (barycentricinterpolant b, double ca, double cb)
static void barycentriclintransy (barycentricinterpolant b, double ca, double cb)
static void barycentricunpack (barycentricinterpolant b, ref int n, ref double[] x, ref double[] y, ref double[] w)
static void barycentricbuildxyw (double[] x, double[] y, double[] w, int n, barycentricinterpolant b)
static void barycentricbuildfloaterhormann (double[] x, double[] y, int n, int d, barycentricinterpolant b)
static void barycentriccopy (barycentricinterpolant b, barycentricinterpolant b2)
Static Private Member Functions
static void barycentricnormalize (barycentricinterpolant b)
static void barycentricnormalize (barycentricinterpolant b)
Member Function Documentation
barycentriccalc() [1/2]
static double alglib.ratint.barycentriccalc (barycentricinterpolant b, double t) inline static
References alglib.ap.assert(), alglib.ratint.barycentricinterpolant.n, alglib.ratint.barycentricinterpolant.sy, alglib.ratint.barycentricinterpolant.w, alglib.ratint.barycentricinterpolant.x, and alglib.ratint.barycentricinterpolant.y.
Referenced by alglib.barycentriccalc(), alglib.ratint.barycentriclintransx(), alglib.polint.polynomialbar2cheb(), alglib.polint.polynomialbar2pow(), alglib.testpolintunit.testpolint(), alglib.testlsfitunit.testpolynomialfitting(), alglib.testratintunit.testratint(), and alglib.testlsfitunit.testrationalfitting().
barycentricdiff1() [1/2]
static void alglib.ratint.barycentricdiff1 (barycentricinterpolant b, double t, ref double f, ref double df) inline static
References alglib.ap.assert(), alglib.ratint.barycentricinterpolant.n, alglib.math.sqr(), alglib.ratint.barycentricinterpolant.sy, alglib.ratint.barycentricinterpolant.w, alglib.ratint.barycentricinterpolant.x, and alglib.ratint.barycentricinterpolant.y.
Referenced by alglib.barycentricdiff1(), alglib.testlsfitunit.testpolynomialfitting(), alglib.testratintunit.testratint(), and alglib.testlsfitunit.testrationalfitting().
barycentricdiff2() [1/2]
static void alglib.ratint.barycentricdiff2 (barycentricinterpolant b, double t, ref double f, ref double df, ref double d2f) inline static
References alglib.ap.assert(), alglib.ratint.barycentricinterpolant.n, alglib.math.sqr(), alglib.ratint.barycentricinterpolant.sy, alglib.ratint.barycentricinterpolant.w, alglib.ratint.barycentricinterpolant.x, and alglib.ratint.barycentricinterpolant.y.
Referenced by alglib.barycentricdiff2(), and alglib.testratintunit.testratint().
barycentriclintransx() [1/2]
static void alglib.ratint.barycentriclintransx (barycentricinterpolant b, double ca, double cb) inline static
References alglib.ratint.barycentriccalc(), alglib.ratint.barycentricinterpolant.n, alglib.ratint.barycentricinterpolant.sy, alglib.ratint.barycentricinterpolant.w, alglib.ratint.barycentricinterpolant.x, and alglib.ratint.barycentricinterpolant.y.
Referenced by alglib.barycentriclintransx(), and alglib.testratintunit.testratint().
barycentriclintransy() [1/2]
static void alglib.ratint.barycentriclintransy (barycentricinterpolant b, double ca, double cb) inline static
References alglib.ratint.barycentricinterpolant.n, alglib.ratint.barycentricinterpolant.sy, and alglib.ratint.barycentricinterpolant.y.
Referenced by alglib.barycentriclintransy(), and alglib.testratintunit.testratint().
barycentricunpack() [1/2]
static void alglib.ratint.barycentricunpack (barycentricinterpolant b, ref int n, ref double[] x, ref double[] y, ref double[] w) inline static
References alglib.ratint.barycentricinterpolant.n, alglib.ratint.barycentricinterpolant.sy, alglib.ratint.barycentricinterpolant.w, alglib.ratint.barycentricinterpolant.x, and alglib.ratint.barycentricinterpolant.y.
Referenced by alglib.barycentricunpack(), and alglib.testratintunit.testratint().
barycentricbuildxyw() [1/2]
static void alglib.ratint.barycentricbuildxyw (double[] x, double[] y, double[] w, int n, barycentricinterpolant b) inline static
References alglib.ap.assert(), alglib.ratint.barycentricnormalize(), alglib.ratint.barycentricinterpolant.n, alglib.ratint.barycentricinterpolant.w, alglib.ratint.barycentricinterpolant.x, and alglib.ratint.barycentricinterpolant.y.
Referenced by alglib.barycentricbuildxyw(), alglib.testratintunit.brcunset(), alglib.testpolintunit.brcunset(), alglib.polint.polynomialbuild(), alglib.polint.polynomialbuildcheb1(), alglib.polint.polynomialbuildcheb2(), alglib.polint.polynomialbuildeqdist(), and alglib.testratintunit.testratint().
barycentricbuildfloaterhormann() [1/2]
static void alglib.ratint.barycentricbuildfloaterhormann (double[] x, double[] y, int n, int d, barycentricinterpolant b) inline static
References alglib.ap.assert(), alglib.ratint.barycentricnormalize(), alglib.ratint.barycentricinterpolant.n, alglib.tsort.tagsortfastr(), alglib.ratint.barycentricinterpolant.w, alglib.ratint.barycentricinterpolant.x, and alglib.ratint.barycentricinterpolant.y.
Referenced by alglib.barycentricbuildfloaterhormann(), alglib.testratintunit.testratint(), and alglib.testlsfitunit.testrationalfitting().
barycentriccopy() [1/2]
static void alglib.ratint.barycentriccopy (barycentricinterpolant b, barycentricinterpolant b2) inline static
References alglib.ratint.barycentricinterpolant.n, alglib.ratint.barycentricinterpolant.sy, alglib.ratint.barycentricinterpolant.w, alglib.ratint.barycentricinterpolant.x, and alglib.ratint.barycentricinterpolant.y.
Referenced by alglib.testratintunit.testratint().
barycentricnormalize() [1/2]
static void alglib.ratint.barycentricnormalize (barycentricinterpolant b) inline static private
References alglib.math.machineepsilon, alglib.ratint.barycentricinterpolant.n, alglib.ratint.barycentricinterpolant.sy, alglib.tsort.tagsort(), alglib.ratint.barycentricinterpolant.w, alglib.ratint.barycentricinterpolant.x, and alglib.ratint.barycentricinterpolant.y.
Referenced by alglib.ratint.barycentricbuildfloaterhormann(), and alglib.ratint.barycentricbuildxyw().
barycentriccalc() [2/2]
static double alglib.ratint.barycentriccalc (barycentricinterpolant b, double t) inline static
References alglib.ap.assert().
barycentricdiff1() [2/2]
static void alglib.ratint.barycentricdiff1 (barycentricinterpolant b, double t, ref double f, ref double df) inline static
References alglib.ap.assert(), and alglib.math.sqr().
barycentricdiff2() [2/2]
static void alglib.ratint.barycentricdiff2 (barycentricinterpolant b, double t, ref double f, ref double df, ref double d2f) inline static
References alglib.ap.assert(), and alglib.math.sqr().
barycentriclintransx() [2/2]
static void alglib.ratint.barycentriclintransx (barycentricinterpolant b, double ca, double cb) inline static
References alglib.ratint.barycentriccalc().
barycentriclintransy() [2/2]
static void alglib.ratint.barycentriclintransy (barycentricinterpolant b, double ca, double cb) inline static
barycentricunpack() [2/2]
static void alglib.ratint.barycentricunpack (barycentricinterpolant b, ref int n, ref double[] x, ref double[] y, ref double[] w) inline static
barycentricbuildxyw() [2/2]
static void alglib.ratint.barycentricbuildxyw (double[] x, double[] y, double[] w, int n, barycentricinterpolant b) inline static
References alglib.ap.assert(), and alglib.ratint.barycentricnormalize().
barycentricbuildfloaterhormann() [2/2]
static void alglib.ratint.barycentricbuildfloaterhormann (double[] x, double[] y, int n, int d, barycentricinterpolant b) inline static
References alglib.ap.assert(), alglib.ratint.barycentricnormalize(), and alglib.tsort.tagsortfastr().
barycentriccopy() [2/2]
static void alglib.ratint.barycentriccopy (barycentricinterpolant b, barycentricinterpolant b2) inline static
barycentricnormalize() [2/2]
static void alglib.ratint.barycentricnormalize (barycentricinterpolant b) inline static private
References alglib.math.machineepsilon, and alglib.tsort.tagsort().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/interpolation.cs