Doc: IGLib EXTENDED: AForge.SystemTools Class Reference
AForge.SystemTools Class Reference
Set of systems tools.
Static Public Member Functions
static IntPtr CopyUnmanagedMemory (IntPtr dst, IntPtr src, int count)
Copy block of unmanaged memory.
static unsafe byte * CopyUnmanagedMemory (byte *dst, byte *src, int count)
Copy block of unmanaged memory.
static IntPtr SetUnmanagedMemory (IntPtr dst, int filler, int count)
Fill memory region with specified value.
static unsafe byte * SetUnmanagedMemory (byte *dst, int filler, int count)
Fill memory region with specified value.
Private Member Functions
static unsafe byte * memcpy (byte *dst, byte *src, int count)
static unsafe byte * memset (byte *dst, int filler, int count)
Detailed Description
Set of systems tools.
The class is a container of different system tools, which are used across the framework. Some of these tools are platform specific, so their implementation is different on different platform, like .NET and Mono.
Member Function Documentation
CopyUnmanagedMemory() [1/2]
static IntPtr AForge.SystemTools.CopyUnmanagedMemory (IntPtr dst, IntPtr src, int count) inline static
Copy block of unmanaged memory.
Parameters
dst Destination pointer.
src Source pointer.
count Memory block's length to copy.
Returns
Return's value of dst - pointer to destination.
This function is required because of the fact that .NET does not provide any way to copy unmanaged blocks, but provides only methods to copy from unmanaged memory to managed memory and vise versa.
Referenced by AForge.Imaging.Filters.BaseInPlaceFilter.Apply(), AForge.Imaging.Filters.BaseInPlacePartialFilter.Apply(), AForge.Imaging.Filters.BaseUsingCopyPartialFilter.ApplyInPlace(), AForge.Imaging.Image.Clone(), AForge.Imaging.UnmanagedImage.Clone(), AForge.Video.AsyncVideoSource.CloneImage(), AForge.Imaging.UnmanagedImage.Copy(), AForge.Imaging.UnmanagedImage.FromManagedImage(), AForge.Video.Ximea.XimeaCamera.GetImage(), AForge.Video.Kinect.KinectDepthCamera.HandleDataReceived(), AForge.Video.Kinect.KinectVideoCamera.HandleDataReceived(), AForge.Imaging.Filters.Crop.ProcessFilter(), AForge.Imaging.Filters.Jitter.ProcessFilter(), AForge.Imaging.Filters.ImageWarp.ProcessFilter(), AForge.Imaging.Filters.Shrink.ProcessFilter(), AForge.Vision.Motion.TwoFramesDifferenceDetector.ProcessFrame(), AForge.Vision.Motion.CustomFrameDifferenceDetector.ProcessFrame(), AForge.Vision.Motion.SimpleBackgroundModelingDetector.ProcessFrame(), and AForge.Imaging.UnmanagedImage.ToManagedImage().
CopyUnmanagedMemory() [2/2]
static unsafe byte* AForge.SystemTools.CopyUnmanagedMemory (byte * dst, byte * src, int count) inline static
Copy block of unmanaged memory.
Parameters
dst Destination pointer.
src Source pointer.
count Memory block's length to copy.
Returns
Return's value of dst - pointer to destination.
This function is required because of the fact that .NET does not provide any way to copy unmanaged blocks, but provides only methods to copy from unmanaged memory to managed memory and vise versa.
References AForge.SystemTools.memcpy().
SetUnmanagedMemory() [1/2]
static IntPtr AForge.SystemTools.SetUnmanagedMemory (IntPtr dst, int filler, int count) inline static
Fill memory region with specified value.
Parameters
dst Destination pointer.
filler Filler byte's value.
count Memory block's length to fill.
Returns
Return's value of dst - pointer to destination.
Referenced by AForge.Imaging.UnmanagedImage.Create(), AForge.Vision.Motion.MotionDetector.CreateMotionZonesFrame(), AForge.Imaging.Drawing.FillRectangle(), AForge.Imaging.Filters.SimpleSkeletonization.ProcessFilter(), and AForge.Imaging.Filters.CanvasFill.ProcessFilter().
SetUnmanagedMemory() [2/2]
static unsafe byte* AForge.SystemTools.SetUnmanagedMemory (byte * dst, int filler, int count) inline static
Fill memory region with specified value.
Parameters
dst Destination pointer.
filler Filler byte's value.
count Memory block's length to fill.
Returns
Return's value of dst - pointer to destination.
References AForge.SystemTools.memset().
memcpy()
static unsafe byte* AForge.SystemTools.memcpy (byte * dst, byte * src, int count) private
Referenced by AForge.SystemTools.CopyUnmanagedMemory().
memset()
static unsafe byte* AForge.SystemTools.memset (byte * dst, int filler, int count) private
Referenced by AForge.SystemTools.SetUnmanagedMemory().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Core/SystemTools.cs