Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLASD7 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLASD7 Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLASD7 (DCOPY dcopy, DLAMRG dlamrg, DROT drot, XERBLA xerbla, DLAMCH dlamch, DLAPY2 dlapy2)
DLASD7 ()
void Run (int ICOMPQ, int NL, int NR, int SQRE, ref int K, ref double[] D, int offset_d, ref double[] Z, int offset_z, ref double[] ZW, int offset_zw, ref double[] VF, int offset_vf, ref double[] VFW, int offset_vfw, ref double[] VL, int offset_vl, ref double[] VLW, int offset_vlw, double ALPHA, double BETA, ref double[] DSIGMA, int offset_dsigma, ref int[] IDX, int offset_idx, ref int[] IDXP, int offset_idxp, ref int[] IDXQ, int offset_idxq, ref int[] PERM, int offset_perm, ref int GIVPTR, ref int[] GIVCOL, int offset_givcol, int LDGCOL, ref double[] GIVNUM, int offset_givnum, int LDGNUM, ref double C, ref double S, ref int INFO)
Private Attributes
DCOPY _dcopy
DLAMRG _dlamrg
DROT _drot
XERBLA _xerbla
DLAMCH _dlamch
DLAPY2 _dlapy2
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
const double TWO = 2.0E+0
const double EIGHT = 8.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLASD7 merges the two sets of singular values together into a single sorted set. Then it tries to deflate the size of the problem. There are two ways in which deflation can occur: when two or more singular values are close together or if there is a tiny entry in the Z vector. For each such occurrence the order of the related secular equation problem is reduced by one.
DLASD7 is called from DLASD6.
/summary>
Constructor & Destructor Documentation
DLASD7() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLASD7.DLASD7 (DCOPY dcopy, DLAMRG dlamrg, DROT drot, XERBLA xerbla, DLAMCH dlamch, DLAPY2 dlapy2) inline
DLASD7() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLASD7.DLASD7 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLASD7.Run (int ICOMPQ, int NL, int NR, int SQRE, ref int K, ref double[] D, int offset_d, ref double[] Z, int offset_z, ref double[] ZW, int offset_zw, ref double[] VF, int offset_vf, ref double[] VFW, int offset_vfw, ref double[] VL, int offset_vl, ref double[] VLW, int offset_vlw, double ALPHA, double BETA, ref double[] DSIGMA, int offset_dsigma, ref int[] IDX, int offset_idx, ref int[] IDXP, int offset_idxp, ref int[] IDXQ, int offset_idxq, ref int[] PERM, int offset_perm, ref int GIVPTR, ref int[] GIVCOL, int offset_givcol, int LDGCOL, ref double[] GIVNUM, int offset_givnum, int LDGNUM, ref double C, ref double S, ref int INFO) inline
Purpose
DLASD7 merges the two sets of singular values together into a single sorted set. Then it tries to deflate the size of the problem. There are two ways in which deflation can occur: when two or more singular values are close together or if there is a tiny entry in the Z vector. For each such occurrence the order of the related secular equation problem is reduced by one.
DLASD7 is called from DLASD6.
/summary>
Parameters
ICOMPQ (input) INTEGER Specifies whether singular vectors are to be computed in compact form, as follows: = 0: Compute singular values only. = 1: Compute singular vectors of upper bidiagonal matrix in compact form. /param>
Parameters
NL (input) INTEGER The row dimension of the upper block. NL .GE. 1. /param>
Parameters
NR (input) INTEGER The row dimension of the lower block. NR .GE. 1. /param>
Parameters
SQRE (input) INTEGER = 0: the lower block is an NR-by-NR square matrix. = 1: the lower block is an NR-by-(NR+1) rectangular matrix.
The bidiagonal matrix has N = NL + NR + 1 rows and M = N + SQRE .GE. N columns. /param>
Parameters
K (output) INTEGER Contains the dimension of the non-deflated matrix, this is the order of the related secular equation. 1 .LE. K .LE.N. /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension (N) On entry D contains the singular values of the two submatrices to be combined. On exit D contains the trailing (N-K) updated singular values (those which were deflated) sorted into increasing order. /param>
Parameters
Z (output) DOUBLE PRECISION array, dimension (M) On exit Z contains the updating row vector in the secular equation. /param>
Parameters
ZW (workspace) DOUBLE PRECISION array, dimension (M) Workspace for Z. /param>
Parameters
VF (input/output) DOUBLE PRECISION array, dimension (M) On entry, VF(1:NL+1) contains the first components of all right singular vectors of the upper block; and VF(NL+2:M) contains the first components of all right singular vectors of the lower block. On exit, VF contains the first components of all right singular vectors of the bidiagonal matrix. /param>
Parameters
VFW (workspace) DOUBLE PRECISION array, dimension (M) Workspace for VF. /param>
Parameters
VL (input/output) DOUBLE PRECISION array, dimension (M) On entry, VL(1:NL+1) contains the last components of all right singular vectors of the upper block; and VL(NL+2:M) contains the last components of all right singular vectors of the lower block. On exit, VL contains the last components of all right singular vectors of the bidiagonal matrix. /param>
Parameters
VLW (workspace) DOUBLE PRECISION array, dimension (M) Workspace for VL. /param>
Parameters
ALPHA (input) DOUBLE PRECISION Contains the diagonal element associated with the added row. /param>
Parameters
BETA (input) DOUBLE PRECISION Contains the off-diagonal element associated with the added row. /param>
Parameters
DSIGMA (output) DOUBLE PRECISION array, dimension (N) Contains a copy of the diagonal elements (K-1 singular values and one zero) in the secular equation. /param>
Parameters
IDX (workspace) INTEGER array, dimension (N) This will contain the permutation used to sort the contents of D into ascending order. /param>
Parameters
IDXP (workspace) INTEGER array, dimension (N) This will contain the permutation used to place deflated values of D at the end of the array. On output IDXP(2:K) points to the nondeflated D-values and IDXP(K+1:N) points to the deflated singular values. /param>
Parameters
IDXQ (input) INTEGER array, dimension (N) This contains the permutation which separately sorts the two sub-problems in D into ascending order. Note that entries in the first half of this permutation must first be moved one position backward; and entries in the second half must first have NL+1 added to their values. /param>
Parameters
PERM (output) INTEGER array, dimension (N) The permutations (from deflation and sorting) to be applied to each singular block. Not referenced if ICOMPQ = 0. /param>
Parameters
GIVPTR (output) INTEGER The number of Givens rotations which took place in this subproblem. Not referenced if ICOMPQ = 0. /param>
Parameters
GIVCOL (output) INTEGER array, dimension (LDGCOL, 2) Each pair of numbers indicates a pair of columns to take place in a Givens rotation. Not referenced if ICOMPQ = 0. /param>
Parameters
LDGCOL (input) INTEGER The leading dimension of GIVCOL, must be at least N. /param>
Parameters
GIVNUM (output) DOUBLE PRECISION array, dimension (LDGNUM, 2) Each number indicates the C or S value to be used in the corresponding Givens rotation. Not referenced if ICOMPQ = 0. /param>
Parameters
LDGNUM (input) INTEGER The leading dimension of GIVNUM, must be at least N. /param>
Parameters
C (output) DOUBLE PRECISION C contains garbage if SQRE =0 and the C-value of a Givens rotation related to the right null space if SQRE = 1. /param>
Parameters
S (output) DOUBLE PRECISION S contains garbage if SQRE =0 and the S-value of a Givens rotation related to the right null space if SQRE = 1. /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLASD7.EIGHT, DotNumerics.LinearAlgebra.CSLapack.DLASD7.ONE, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DROT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAPY2.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMRG.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD7.TWO, and DotNumerics.LinearAlgebra.CSLapack.DLASD7.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD6.Run().
Member Data Documentation
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLASD7._dcopy private
_dlamrg
DLAMRG DotNumerics.LinearAlgebra.CSLapack.DLASD7._dlamrg private
_drot
DROT DotNumerics.LinearAlgebra.CSLapack.DLASD7._drot private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLASD7._xerbla private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLASD7._dlamch private
_dlapy2
DLAPY2 DotNumerics.LinearAlgebra.CSLapack.DLASD7._dlapy2 private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLASD7.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD7.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLASD7.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD7.Run().
TWO
const double DotNumerics.LinearAlgebra.CSLapack.DLASD7.TWO = 2.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD7.Run().
EIGHT
const double DotNumerics.LinearAlgebra.CSLapack.DLASD7.EIGHT = 8.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD7.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlasd7.cs