Doc: IGLib EXTENDED: alglib.hblas Class Reference
alglib.hblas Class Reference
Static Public Member Functions
static void hermitianmatrixvectormultiply (complex[,] a, bool isupper, int i1, int i2, complex[] x, complex alpha, ref complex[] y)
static void hermitianrank2update (ref complex[,] a, bool isupper, int i1, int i2, complex[] x, complex[] y, ref complex[] t, complex alpha)
static void hermitianmatrixvectormultiply (complex[,] a, bool isupper, int i1, int i2, complex[] x, complex alpha, ref complex[] y)
static void hermitianrank2update (ref complex[,] a, bool isupper, int i1, int i2, complex[] x, complex[] y, ref complex[] t, complex alpha)
Member Function Documentation
hermitianmatrixvectormultiply() [1/2]
static void alglib.hblas.hermitianmatrixvectormultiply (complex a[,], bool isupper, int i1, int i2, complex[] x, complex alpha, ref complex[] y) inline static
References alglib.math.conj().
Referenced by alglib.testhblasunit.testhblas().
hermitianrank2update() [1/2]
static void alglib.hblas.hermitianrank2update (ref complex a[,], bool isupper, int i1, int i2, complex[] x, complex[] y, ref complex[] t, complex alpha) inline static
References alglib.math.conj().
hermitianmatrixvectormultiply() [2/2]
static void alglib.hblas.hermitianmatrixvectormultiply (complex a[,], bool isupper, int i1, int i2, complex[] x, complex alpha, ref complex[] y) inline static
References alglib.math.conj().
hermitianrank2update() [2/2]
static void alglib.hblas.hermitianrank2update (ref complex a[,], bool isupper, int i1, int i2, complex[] x, complex[] y, ref complex[] t, complex alpha) inline static
References alglib.math.conj().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/alglibinternal.cs