Doc: IGLib EXTENDED: AForge.Math.Gaussian Class Reference
AForge.Math.Gaussian Class Reference
Gaussian function.
Public Member Functions
Gaussian ()
Initializes a new instance of the Gaussian class.
Gaussian (double sigma)
Initializes a new instance of the Gaussian class.
double Function (double x)
1-D Gaussian function.
double Function2D (double x, double y)
2-D Gaussian function.
double[] Kernel (int size)
1-D Gaussian kernel.
double[,] Kernel2D (int size)
2-D Gaussian kernel.
Properties
double Sigma [get, set]
Sigma value.
Private Attributes
double sigma = 1.0
double sqrSigma = 1.0
Detailed Description
Gaussian function.
The class is used to calculate 1D and 2D Gaussian functions for specified Sigma (s) value:
1-D: f(x) = exp(x * x / (-2 * s * s)) / (s * sqrt(2 * PI))
2-D: f(x, y) = exp(x * x + y * y / (-2 * s * s)) / (s * s * 2 * PI)
Constructor & Destructor Documentation
Gaussian() [1/2]
AForge.Math.Gaussian.Gaussian () inline
Initializes a new instance of the Gaussian class.
Gaussian() [2/2]
AForge.Math.Gaussian.Gaussian (double sigma) inline
Initializes a new instance of the Gaussian class.
Parameters
sigma Sigma value.
References AForge.Math.Gaussian.sigma, and AForge.Math.Gaussian.Sigma.
Member Function Documentation
Function()
double AForge.Math.Gaussian.Function (double x) inline
1-D Gaussian function.
Parameters
x x value.
Returns
Returns function's value at point x .
The function calculates 1-D Gaussian function:
f(x) = exp(x * x / (-2 * s * s)) / (s * sqrt(2 * PI))
References AForge.Math.Gaussian.sigma, and AForge.Math.Gaussian.sqrSigma.
Referenced by AForge.Math.Gaussian.Kernel().
Function2D()
double AForge.Math.Gaussian.Function2D (double x, double y) inline
2-D Gaussian function.
Parameters
x x value.
y y value.
Returns
Returns function's value at point (x , y).
The function calculates 2-D Gaussian function:
f(x, y) = exp(x * x + y * y / (-2 * s * s)) / (s * s * 2 * PI)
References AForge.Math.Gaussian.sqrSigma.
Referenced by AForge.Math.Gaussian.Kernel2D().
Kernel()
double [] AForge.Math.Gaussian.Kernel (int size) inline
1-D Gaussian kernel.
Parameters
size Kernel size (should be odd), [3, 101].
Returns
Returns 1-D Gaussian kernel of the specified size.
The function calculates 1-D Gaussian kernel, which is array of Gaussian function's values in the [-r, r] range of x value, where r=floor(size /2).
Exceptions
ArgumentException Wrong kernel size.
References AForge.Math.Gaussian.Function().
Kernel2D()
double [,] AForge.Math.Gaussian.Kernel2D (int size) inline
2-D Gaussian kernel.
Parameters
size Kernel size (should be odd), [3, 101].
Returns
Returns 2-D Gaussian kernel of specified size.
The function calculates 2-D Gaussian kernel, which is array of Gaussian function's values in the [-r, r] range of x,y values, where r=floor(size /2).
Exceptions
ArgumentException Wrong kernel size.
References AForge.Math.Gaussian.Function2D().
Member Data Documentation
sigma
double AForge.Math.Gaussian.sigma = 1.0 private
Referenced by AForge.Math.Gaussian.Function(), and AForge.Math.Gaussian.Gaussian().
sqrSigma
double AForge.Math.Gaussian.sqrSigma = 1.0 private
Referenced by AForge.Math.Gaussian.Function(), and AForge.Math.Gaussian.Function2D().
Property Documentation
Sigma
double AForge.Math.Gaussian.Sigma get set
Sigma value.
Sigma property of Gaussian function.
Default value is set to 1. Minimum allowed value is 0.00000001.
Referenced by AForge.Math.Gaussian.Gaussian().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Math/Gaussian.cs