Doc: IGLib EXTENDED: NUnit.TestUtilities.SimpleEventRecorder Class Reference
NUnit.TestUtilities.SimpleEventRecorder Class Reference
A static helper to Verify that Setup/Teardown 'events' occur, and that they are in the correct order...
Classes
class EventMatcher
A helper class for matching test events.
class ExpectedEventsRecorder
Helper class for recording expected events.
Static Public Member Functions
static void RegisterEvent (string evnt)
Registers an event.
static void Verify (params string[] expectedEvents)
Verifies the specified expected events occurred and that they occurred in the specified order.
static ExpectedEventsRecorder ExpectEvents (params string[] expectedEvents)
Record the specified events as recorded expected events.
static void Clear ()
Clears any unverified events.
Static Private Member Functions
static SimpleEventRecorder ()
Initializes the SimpleEventRecorder 'static' class.
Static Private Attributes
static Queue< string > _events
Detailed Description
A static helper to Verify that Setup/Teardown 'events' occur, and that they are in the correct order...
Constructor & Destructor Documentation
SimpleEventRecorder()
static NUnit.TestUtilities.SimpleEventRecorder.SimpleEventRecorder () inline static private
Initializes the SimpleEventRecorder 'static' class.
References NUnit.TestUtilities.SimpleEventRecorder._events.
Member Function Documentation
RegisterEvent()
static void NUnit.TestUtilities.SimpleEventRecorder.RegisterEvent (string evnt) inline static
Registers an event.
Parameters
evnt The event to register.
References NUnit.TestUtilities.SimpleEventRecorder._events.
Referenced by NoNamespaceSetupFixture.DoNamespaceSetUp(), NoNamespaceSetupFixture.DoNamespaceTearDown(), and SomeFixture.Test().
Verify()
static void NUnit.TestUtilities.SimpleEventRecorder.Verify (params string[] expectedEvents) inline static
Verifies the specified expected events occurred and that they occurred in the specified order.
Parameters
expectedEvents The expected events.
References NUnit.TestUtilities.SimpleEventRecorder._events, and NUnit.Framework.Assert.AreEqual().
ExpectEvents()
static ExpectedEventsRecorder NUnit.TestUtilities.SimpleEventRecorder.ExpectEvents (params string[] expectedEvents) inline static
Record the specified events as recorded expected events.
Parameters
expectedEvents An array of strings identifying the test events
Returns
An ExpectedEventsRecorder so that further expected events can be recorded and verified
References NUnit.TestUtilities.SimpleEventRecorder._events.
Clear()
static void NUnit.TestUtilities.SimpleEventRecorder.Clear () inline static
Clears any unverified events.
References NUnit.TestUtilities.SimpleEventRecorder._events.
Member Data Documentation
_events
Queue<string> NUnit.TestUtilities.SimpleEventRecorder._events static private
Referenced by NUnit.TestUtilities.SimpleEventRecorder.Clear(), NUnit.TestUtilities.SimpleEventRecorder.ExpectEvents(), NUnit.TestUtilities.SimpleEventRecorder.RegisterEvent(), NUnit.TestUtilities.SimpleEventRecorder.SimpleEventRecorder(), and NUnit.TestUtilities.SimpleEventRecorder.Verify().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/testdata/SetUpFixtureData.cs