Doc: IGLib EXTENDED: NUnit.Framework.Tests.TestContextTearDownTests Class Reference
NUnit.Framework.Tests.TestContextTearDownTests Class Reference
Public Member Functions
void TestTheMeaningOfLife ()
void TearDown ()
Static Private Attributes
const int THE_MEANING_OF_LIFE = 42
Member Function Documentation
TestTheMeaningOfLife()
void NUnit.Framework.Tests.TestContextTearDownTests.TestTheMeaningOfLife () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Assert.That(), and NUnit.Framework.Tests.TestContextTearDownTests.THE_MEANING_OF_LIFE.
TearDown()
void NUnit.Framework.Tests.TestContextTearDownTests.TearDown () inline
References NUnit.Framework.TestContext.CurrentContext, NUnit.Framework.Is.EqualTo(), NUnit.Framework.TestContext.ResultAdapter.FailCount, NUnit.Framework.TestContext.TestAdapter.Name, NUnit.Framework.Is.Not, NUnit.Framework.TestContext.ResultAdapter.Outcome, NUnit.Framework.TestContext.ResultAdapter.PassCount, NUnit.Framework.TestContext.Result, NUnit.Framework.Interfaces.ResultState.Success, NUnit.Framework.TestContext.Test, NUnit.Framework.TestContext.TestDirectory, NUnit.Framework.Assert.That(), and NUnit.Framework.TestContext.WorkDirectory.
Member Data Documentation
THE_MEANING_OF_LIFE
const int NUnit.Framework.Tests.TestContextTearDownTests.THE_MEANING_OF_LIFE = 42 static private
Referenced by NUnit.Framework.Tests.TestContextTearDownTests.TestTheMeaningOfLife().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/TestContextTests.cs