Doc: IGLib EXTENDED: AForge.Controls.Chart Class Reference
AForge.Controls.Chart Class Reference
Chart control
Classes
class DataSeries
Public Types
enum SeriesType {
SeriesType.Line, SeriesType.Dots, SeriesType.ConnectedDots, SeriesType.Line,
SeriesType.Dots, SeriesType.ConnectedDots, SeriesType.Line, SeriesType.Dots,
SeriesType.ConnectedDots
}
Chart series type enumeration
enum SeriesType {
SeriesType.Line, SeriesType.Dots, SeriesType.ConnectedDots, SeriesType.Line,
SeriesType.Dots, SeriesType.ConnectedDots, SeriesType.Line, SeriesType.Dots,
SeriesType.ConnectedDots
}
Chart series type enumeration
enum SeriesType {
SeriesType.Line, SeriesType.Dots, SeriesType.ConnectedDots, SeriesType.Line,
SeriesType.Dots, SeriesType.ConnectedDots, SeriesType.Line, SeriesType.Dots,
SeriesType.ConnectedDots
}
Chart series type enumeration.
Public Member Functions
Chart ()
Initializes a new instance of the Chart class
void AddDataSeries (string name, Color color, SeriesType type, int width)
Add data series to the chart
void AddDataSeries (string name, Color color, SeriesType type, int width, bool updateYRange)
Add data series to the chart
void UpdateDataSeries (string name, double[,] data)
Update data series on the chart
void RemoveDataSeries (string name)
Remove data series from the chart
void RemoveAllDataSeries ()
Remove all data series from the chart
Chart ()
Initializes a new instance of the Chart class
void AddDataSeries (string name, Color color, SeriesType type, int width)
Add data series to the chart
void AddDataSeries (string name, Color color, SeriesType type, int width, bool updateYRange)
Add data series to the chart
void UpdateDataSeries (string name, double[,] data)
Update data series on the chart
void RemoveDataSeries (string name)
Remove data series from the chart
void RemoveAllDataSeries ()
Remove all data series from the chart
Chart ()
Initializes a new instance of the Chart class.
void AddDataSeries (string name, Color color, SeriesType type, int width)
Add data series to the chart.
void AddDataSeries (string name, Color color, SeriesType type, int width, bool updateYRange)
Add data series to the chart.
void UpdateDataSeries (string name, double[,] data)
Update data series on the chart.
void RemoveDataSeries (string name)
Remove data series from the chart.
void RemoveAllDataSeries ()
Remove all data series from the chart.
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void OnPaint (PaintEventArgs pe)
Paint the control with all available data series
override void Dispose (bool disposing)
Clean up any resources being used.
override void OnPaint (PaintEventArgs pe)
Paint the control with all available data series
override void Dispose (bool disposing)
Dispose the object.
Properties
DoubleRange RangeX [get, set]
Chart's X range
DoubleRange RangeY [get, set]
Chart's Y range
Range RangeX [get, set]
Chart's X range.
Range RangeY [get, set]
Chart's Y range.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void UpdateYRange ()
displayable Y range
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void UpdateYRange ()
displayable Y range
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void Chart_Paint (object sender, PaintEventArgs e)
void UpdateYRange ()
Update Y range.
Private Attributes
Hashtable seriesTable = new Hashtable()
Pen blackPen = new Pen(Color.Black)
Brush whiteBrush = new SolidBrush(Color.White)
DoubleRange rangeX = new DoubleRange(0, 1)
DoubleRange rangeY = new DoubleRange(0, 1)
System.ComponentModel.Container components = null
Required designer variable.
Dictionary< string, DataSeries > seriesTable = new Dictionary<string, DataSeries>()
Range rangeX = new Range(0, 1)
Range rangeY = new Range(0, 1)
Detailed Description
Chart control
Chart control.
The chart control allows to display multiple charts at time of different types: dots, lines, connected dots.
The chart control allows to display multiple charts at time of different types: dots, lines, connected dots.
Sample usage:
// create data series array
double[,] testValues = new double[10, 2];
// fill data series
for (int i = 0; i < 10; i++)
{
    testValues[i, 0] = i; // X values
    testValues[i, 1] = Math.Sin( i / 18.0 * Math.PI ); // Y values
}
// add new data series to the chart
chart.AddDataSeries("Test", Color.DarkGreen, Chart.SeriesType.ConnectedDots, 3);
// set X range to display
chart.RangeX = new AForge.Range(0, 9);
// update the chart
chart.UpdateDataSeries("Test", testValues);
Member Enumeration Documentation
SeriesType [1/3]
enum AForge.Controls.Chart.SeriesType strong
Chart series type enumeration
Enumerator
Line
Line style
Dots
Dots style
ConnectedDots
Connected dots style
Line
Line style
Dots
Dots style
ConnectedDots
Connected dots style
Line
Line style.
Dots
Dots style.
ConnectedDots
Connected dots style.
SeriesType [2/3]
enum AForge.Controls.Chart.SeriesType strong
Chart series type enumeration
Enumerator
Line
Line style
Dots
Dots style
ConnectedDots
Connected dots style
Line
Line style
Dots
Dots style
ConnectedDots
Connected dots style
Line
Line style.
Dots
Dots style.
ConnectedDots
Connected dots style.
SeriesType [3/3]
enum AForge.Controls.Chart.SeriesType strong
Chart series type enumeration.
Enumerator
Line
Line style
Dots
Dots style
ConnectedDots
Connected dots style
Line
Line style
Dots
Dots style
ConnectedDots
Connected dots style
Line
Line style.
Dots
Dots style.
ConnectedDots
Connected dots style.
Constructor & Destructor Documentation
Chart() [1/3]
AForge.Controls.Chart.Chart () inline
Initializes a new instance of the Chart class
References AForge.Controls.Chart.InitializeComponent().
Chart() [2/3]
AForge.Controls.Chart.Chart () inline
Initializes a new instance of the Chart class
References AForge.Controls.Chart.InitializeComponent().
Chart() [3/3]
AForge.Controls.Chart.Chart () inline
Initializes a new instance of the Chart class.
References AForge.Controls.Chart.InitializeComponent().
Member Function Documentation
Dispose() [1/3]
override void AForge.Controls.Chart.Dispose (bool disposing) inline protected
Clean up any resources being used.
References AForge.Controls.Chart.blackPen, AForge.Controls.Chart.components, and AForge.Controls.Chart.whiteBrush.
InitializeComponent() [1/3]
void AForge.Controls.Chart.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by AForge.Controls.Chart.Chart().
OnPaint() [1/2]
override void AForge.Controls.Chart.OnPaint (PaintEventArgs pe) inline protected
Paint the control with all available data series
Parameters
pe Data for Paint event
References AForge.Controls.Chart.blackPen, AForge.Controls.Chart.DataSeries.color, AForge.Controls.Chart.DataSeries.data, AForge.DoubleRange.Length, AForge.DoubleRange.Min, AForge.Controls.Chart.rangeX, AForge.Controls.Chart.rangeY, AForge.Controls.Chart.seriesTable, AForge.Controls.Chart.DataSeries.type, AForge.Controls.Chart.whiteBrush, and AForge.Controls.Chart.DataSeries.width.
AddDataSeries() [1/6]
void AForge.Controls.Chart.AddDataSeries (string name, Color color, SeriesType type, int width) inline
Add data series to the chart
Parameters
name Data series name
color Data series color
type Data series type
width Width (depends on the data series type, see remarks)
Adds new empty data series to the collection of data series. To update this series the UpdateDataSeries method should be used.
The meaning of the width parameter depends on the data series type:
Line - width of the line;
Dots - size of dots (rectangular dots with specified width and the same height);
Connected dots - size of dots (dots are connected with one pixel width line).
Referenced by AForge.Controls.Chart.AddDataSeries(), TSP.MainForm.MainForm(), XORProblem.MainForm.MainForm(), Optimization1D.MainForm.MainForm(), TimeSeries.MainForm.MainForm(), Classifier.MainForm.MainForm(), Approximation.MainForm.MainForm(), Approximation.MainFormNeuralApproximation.MainFormNeuralApproximation(), FuzzySetSample.Sample.Sample(), and Classifier.MainForm.ShowTrainingData().
AddDataSeries() [2/6]
void AForge.Controls.Chart.AddDataSeries (string name, Color color, SeriesType type, int width, bool updateYRange) inline
Add data series to the chart
Parameters
name Data series name
color Data series color
type Data series type
width Width (depends on the data series type, see remarks)
updateYRange Specifies if RangeY should be updated
Adds new empty data series to the collection of data series. The updateYRange parameter specifies if the data series can affect displayable Y range.
References AForge.Controls.Chart.DataSeries.color, AForge.Controls.Chart.seriesTable, AForge.Controls.Chart.DataSeries.type, AForge.Controls.Chart.DataSeries.updateYRange, and AForge.Controls.Chart.DataSeries.width.
UpdateDataSeries() [1/3]
void AForge.Controls.Chart.UpdateDataSeries (string name, double data[,]) inline
Update data series on the chart
Parameters
name Data series name to update
data Data series values
References AForge.Controls.Chart.DataSeries.data, AForge.Controls.Chart.seriesTable, AForge.Controls.Chart.DataSeries.updateYRange, and AForge.Controls.Chart.UpdateYRange().
Referenced by Classifier.MainForm.ClearCurrentSolution(), FuzzySetSample.Sample.ClearDataSeries(), Classifier.MainForm.ClearSolution(), TimeSeries.MainForm.ClearSolution(), Approximation.MainForm.ClearSolution(), TSP.MainForm.GenerateMap(), Classifier.MainForm.loadButton_Click(), Approximation.MainForm.loadDataButton_Click(), Approximation.MainFormNeuralApproximation.loadDataButton_Click(), TimeSeries.MainForm.loadDataButton_Click(), FuzzySetSample.Sample.runFuzzySetTestButton_Click(), FuzzySetSample.Sample.runLingVarTestButton_Click(), XORProblem.MainForm.SearchSolution(), TSP.MainForm.SearchSolution(), Optimization1D.MainForm.SearchSolution(), Approximation.MainFormNeuralApproximation.SearchSolution(), TimeSeries.MainForm.SearchSolution(), Classifier.MainForm.SearchSolution(), Approximation.MainForm.SearchSolution(), Classifier.MainForm.ShowTrainingData(), Optimization1D.MainForm.UpdateChart(), and TimeSeries.MainForm.UpdateDelimiters().
RemoveDataSeries() [1/3]
void AForge.Controls.Chart.RemoveDataSeries (string name) inline
Remove data series from the chart
Parameters
name Data series name
References AForge.Controls.Chart.seriesTable.
RemoveAllDataSeries() [1/3]
void AForge.Controls.Chart.RemoveAllDataSeries () inline
Remove all data series from the chart
References AForge.Controls.Chart.seriesTable.
Referenced by Classifier.MainForm.ShowTrainingData().
UpdateYRange() [1/3]
void AForge.Controls.Chart.UpdateYRange () inline private
displayable Y range
References AForge.Controls.Chart.DataSeries.data, AForge.Controls.Chart.rangeY, AForge.Controls.Chart.seriesTable, and AForge.Controls.Chart.DataSeries.updateYRange.
Referenced by AForge.Controls.Chart.UpdateDataSeries().
Dispose() [2/3]
override void AForge.Controls.Chart.Dispose (bool disposing) inline protected
Clean up any resources being used.
References AForge.Controls.Chart.blackPen, AForge.Controls.Chart.components, and AForge.Controls.Chart.whiteBrush.
InitializeComponent() [2/3]
void AForge.Controls.Chart.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
OnPaint() [2/2]
override void AForge.Controls.Chart.OnPaint (PaintEventArgs pe) inline protected
Paint the control with all available data series
Parameters
pe Data for Paint event
References AForge.Controls.Chart.blackPen, AForge.DoubleRange.Length, AForge.DoubleRange.Min, AForge.Controls.Chart.rangeX, AForge.Controls.Chart.rangeY, AForge.Controls.Chart.seriesTable, and AForge.Controls.Chart.whiteBrush.
AddDataSeries() [3/6]
void AForge.Controls.Chart.AddDataSeries (string name, Color color, SeriesType type, int width) inline
Add data series to the chart
Parameters
name Data series name
color Data series color
type Data series type
width Width (depends on the data series type, see remarks)
Adds new empty data series to the collection of data series. To update this series the UpdateDataSeries method should be used.
The meaning of the width parameter depends on the data series type:
Line - width of the line;
Dots - size of dots (rectangular dots with specified width and the same height);
Connected dots - size of dots (dots are connected with one pixel width line).
References AForge.Controls.Chart.AddDataSeries().
AddDataSeries() [4/6]
void AForge.Controls.Chart.AddDataSeries (string name, Color color, SeriesType type, int width, bool updateYRange) inline
Add data series to the chart
Parameters
name Data series name
color Data series color
type Data series type
width Width (depends on the data series type, see remarks)
updateYRange Specifies if RangeY should be updated
Adds new empty data series to the collection of data series. The updateYRange parameter specifies if the data series can affect displayable Y range.
References AForge.Controls.Chart.seriesTable.
UpdateDataSeries() [2/3]
void AForge.Controls.Chart.UpdateDataSeries (string name, double data[,]) inline
Update data series on the chart
Parameters
name Data series name to update
data Data series values
References AForge.Controls.Chart.seriesTable, and AForge.Controls.Chart.UpdateYRange().
RemoveDataSeries() [2/3]
void AForge.Controls.Chart.RemoveDataSeries (string name) inline
Remove data series from the chart
Parameters
name Data series name
References AForge.Controls.Chart.seriesTable.
RemoveAllDataSeries() [2/3]
void AForge.Controls.Chart.RemoveAllDataSeries () inline
Remove all data series from the chart
References AForge.Controls.Chart.seriesTable.
UpdateYRange() [2/3]
void AForge.Controls.Chart.UpdateYRange () inline private
displayable Y range
References AForge.Controls.Chart.rangeY, and AForge.Controls.Chart.seriesTable.
Dispose() [3/3]
override void AForge.Controls.Chart.Dispose (bool disposing) inline protected
Dispose the object.
References AForge.Controls.Chart.blackPen, and AForge.Controls.Chart.components.
InitializeComponent() [3/3]
void AForge.Controls.Chart.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Chart_Paint()
void AForge.Controls.Chart.Chart_Paint (object sender, PaintEventArgs e) inline private
References AForge.Controls.Chart.blackPen, AForge.DoubleRange.Length, AForge.DoubleRange.Min, AForge.Controls.Chart.rangeX, AForge.Controls.Chart.rangeY, and AForge.Controls.Chart.seriesTable.
AddDataSeries() [5/6]
void AForge.Controls.Chart.AddDataSeries (string name, Color color, SeriesType type, int width) inline
Add data series to the chart.
Parameters
name Data series name.
color Data series color.
type Data series type.
width Width (depends on the data series type, see remarks).
Adds new empty data series to the collection of data series. To update this series the UpdateDataSeries method should be used.
The meaning of the width parameter depends on the data series type:
Line - width of the line;
Dots - size of dots (rectangular dots with specified width and the same height);
Connected dots - size of dots (dots are connected with one pixel width line).
References AForge.Controls.Chart.AddDataSeries().
AddDataSeries() [6/6]
void AForge.Controls.Chart.AddDataSeries (string name, Color color, SeriesType type, int width, bool updateYRange) inline
Add data series to the chart.
Parameters
name Data series name.
color Data series color.
type Data series type.
width Width (depends on the data series type, see remarks).
updateYRange Specifies if RangeY should be updated.
Adds new empty data series to the collection of data series.
The updateYRange parameter specifies if the data series may affect displayable Y range. If the value is set to false, then displayable Y range is not updated, but used the range, which was specified by user (see RangeY property). In the case if the value is set to true, the displayable Y range is recalculated to fully fit the new data series.
References AForge.Controls.Chart.seriesTable.
UpdateDataSeries() [3/3]
void AForge.Controls.Chart.UpdateDataSeries (string name, double data[,]) inline
Update data series on the chart.
Parameters
name Data series name to update.
data Data series values.
References AForge.Controls.Chart.seriesTable, and AForge.Controls.Chart.UpdateYRange().
RemoveDataSeries() [3/3]
void AForge.Controls.Chart.RemoveDataSeries (string name) inline
Remove data series from the chart.
Parameters
name Data series name to remove.
References AForge.Controls.Chart.seriesTable.
RemoveAllDataSeries() [3/3]
void AForge.Controls.Chart.RemoveAllDataSeries () inline
Remove all data series from the chart.
References AForge.Controls.Chart.seriesTable.
UpdateYRange() [3/3]
void AForge.Controls.Chart.UpdateYRange () inline private
Update Y range.
References AForge.DoubleRange.IsInside(), AForge.Controls.Chart.rangeX, AForge.Controls.Chart.rangeY, and AForge.Controls.Chart.seriesTable.
Member Data Documentation
seriesTable [1/2]
Hashtable AForge.Controls.Chart.seriesTable = new Hashtable() private
Referenced by AForge.Controls.Chart.AddDataSeries(), AForge.Controls.Chart.Chart_Paint(), AForge.Controls.Chart.OnPaint(), AForge.Controls.Chart.RemoveAllDataSeries(), AForge.Controls.Chart.RemoveDataSeries(), AForge.Controls.Chart.UpdateDataSeries(), and AForge.Controls.Chart.UpdateYRange().
blackPen
Pen AForge.Controls.Chart.blackPen = new Pen(Color.Black) private
Referenced by AForge.Controls.Chart.Chart_Paint(), AForge.Controls.Chart.Dispose(), and AForge.Controls.Chart.OnPaint().
whiteBrush
Brush AForge.Controls.Chart.whiteBrush = new SolidBrush(Color.White) private
Referenced by AForge.Controls.Chart.Dispose(), and AForge.Controls.Chart.OnPaint().
rangeX [1/2]
DoubleRange AForge.Controls.Chart.rangeX = new DoubleRange(0, 1) private
Referenced by AForge.Controls.Chart.Chart_Paint(), AForge.Controls.Chart.OnPaint(), and AForge.Controls.Chart.UpdateYRange().
rangeY [1/2]
DoubleRange AForge.Controls.Chart.rangeY = new DoubleRange(0, 1) private
Referenced by AForge.Controls.Chart.Chart_Paint(), AForge.Controls.Chart.OnPaint(), and AForge.Controls.Chart.UpdateYRange().
components
System ComponentModel Container AForge.Controls.Chart.components = null private
Required designer variable.
Referenced by AForge.Controls.Chart.Dispose().
seriesTable [2/2]
Dictionary<string, DataSeries> AForge.Controls.Chart.seriesTable = new Dictionary<string, DataSeries>() private
rangeX [2/2]
Range AForge.Controls.Chart.rangeX = new Range(0, 1) private
rangeY [2/2]
Range AForge.Controls.Chart.rangeY = new Range(0, 1) private
Property Documentation
RangeX [1/2]
DoubleRange AForge.Controls.Chart.RangeX get set
Chart's X range
The value sets the X's range of data to be displayed on the chart
Referenced by Classifier.MainForm.loadButton_Click(), Approximation.MainForm.loadDataButton_Click(), Approximation.MainFormNeuralApproximation.loadDataButton_Click(), TimeSeries.MainForm.loadDataButton_Click(), TSP.MainForm.MainForm(), FuzzySetSample.Sample.Sample(), XORProblem.MainForm.SearchSolution(), Approximation.MainFormNeuralApproximation.SearchSolution(), Classifier.MainForm.SearchSolution(), Approximation.MainForm.SearchSolution(), and Optimization1D.MainForm.UpdateChart().
RangeY [1/2]
DoubleRange AForge.Controls.Chart.RangeY get set
Chart's Y range
The value sets the Y's range of data to be displayed on the chart
Referenced by TSP.MainForm.MainForm(), Classifier.MainForm.SearchSolution(), Approximation.MainForm.SearchSolution(), Approximation.MainFormNeuralApproximation.SearchSolution(), TimeSeries.MainForm.SearchSolution(), and TimeSeries.MainForm.UpdateDelimiters().
RangeX [2/2]
Range AForge.Controls.Chart.RangeX get set
Chart's X range.
The value sets the X range of data to be displayed on the chart.
RangeY [2/2]
Range AForge.Controls.Chart.RangeY get set
Chart's Y range.
The value sets the Y range of data to be displayed on the chart.
The documentation for this class was generated from the following file:
shelldev/lib/external/neuralnetworks/neuro_src/Sources/Backup/Controls/Chart.cs