Doc: IGLib EXTENDED: TimeSeries.MainForm Class Reference
TimeSeries.MainForm Class Reference
Summary description for Form1.
Public Member Functions
MainForm ()
MainForm ()
MainForm ()
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void loadDataButton_Click (object sender, System.EventArgs e)
void UpdateDelimiters ()
void UpdateDataListView ()
void EnableControls (bool enable)
void windowSizeBox_TextChanged (object sender, System.EventArgs e)
void predictionSizeBox_TextChanged (object sender, System.EventArgs e)
void UpdateWindowSize ()
void UpdatePredictionSize ()
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void loadDataButton_Click (object sender, System.EventArgs e)
void UpdateDelimiters ()
void UpdateDataListView ()
void EnableControls (bool enable)
void windowSizeBox_TextChanged (object sender, System.EventArgs e)
void predictionSizeBox_TextChanged (object sender, System.EventArgs e)
void UpdateWindowSize ()
void UpdatePredictionSize ()
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
delegate void SetTextCallback (System.Windows.Forms.Control control, string text)
delegate void AddSubItemCallback (System.Windows.Forms.ListView control, int item, string subitemText)
void SetText (System.Windows.Forms.Control control, string text)
void AddSubItem (System.Windows.Forms.ListView control, int item, string subitemText)
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void loadDataButton_Click (object sender, System.EventArgs e)
void UpdateDelimiters ()
void UpdateDataListView ()
delegate void EnableCallback (bool enable)
void EnableControls (bool enable)
void windowSizeBox_TextChanged (object sender, System.EventArgs e)
void predictionSizeBox_TextChanged (object sender, System.EventArgs e)
void UpdateWindowSize ()
void UpdatePredictionSize ()
void ClearSolution ()
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
void moreSettingsButton_Click (object sender, System.EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
delegate void SetTextCallback (System.Windows.Forms.Control control, string text)
delegate void AddSubItemCallback (System.Windows.Forms.ListView control, int item, string subitemText)
void SetText (System.Windows.Forms.Control control, string text)
void AddSubItem (System.Windows.Forms.ListView control, int item, string subitemText)
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void loadDataButton_Click (object sender, System.EventArgs e)
void UpdateDelimiters ()
void UpdateDataListView ()
delegate void EnableCallback (bool enable)
void EnableControls (bool enable)
void windowSizeBox_TextChanged (object sender, System.EventArgs e)
void predictionSizeBox_TextChanged (object sender, System.EventArgs e)
void UpdateWindowSize ()
void UpdatePredictionSize ()
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
Static Private Member Functions
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
static void Main ()
The main entry point for the application.
Private Attributes
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.ListView dataList
System.Windows.Forms.ColumnHeader yColumnHeader
System.Windows.Forms.ColumnHeader estimatedYColumnHeader
System.Windows.Forms.Button loadDataButton
System.Windows.Forms.GroupBox groupBox2
AForge.Controls.Chart chart
System.Windows.Forms.OpenFileDialog openFileDialog
System.Windows.Forms.GroupBox groupBox3
System.Windows.Forms.TextBox momentumBox
System.Windows.Forms.Label label6
System.Windows.Forms.TextBox alphaBox
System.Windows.Forms.Label label2
System.Windows.Forms.TextBox learningRateBox
System.Windows.Forms.Label label1
System.Windows.Forms.Label label10
System.Windows.Forms.TextBox iterationsBox
System.Windows.Forms.Label label9
System.Windows.Forms.Label label8
System.Windows.Forms.TextBox predictionSizeBox
System.Windows.Forms.Label label7
System.Windows.Forms.TextBox windowSizeBox
System.Windows.Forms.Label label3
System.Windows.Forms.Label label5
System.Windows.Forms.Button stopButton
System.Windows.Forms.Button startButton
System.Windows.Forms.GroupBox groupBox4
System.Windows.Forms.TextBox currentPredictionErrorBox
System.Windows.Forms.Label label13
System.Windows.Forms.TextBox currentLearningErrorBox
System.Windows.Forms.Label label12
System.Windows.Forms.TextBox currentIterationBox
System.Windows.Forms.Label label11
System.ComponentModel.Container components = null
Required designer variable.
double[] data = null
double[,] dataToShow = null
double learningRate = 0.1
double momentum = 0.0
double sigmoidAlphaValue = 2.0
int windowSize = 5
int predictionSize = 1
int iterations = 1000
Thread workerThread = null
bool needToStop = false
double[,] windowDelimiter = new double[2, 2] { { 0, 0 }, { 0, 0 } }
double[,] predictionDelimiter = new double[2, 2] { { 0, 0 }, { 0, 0 } }
System.ComponentModel.IContainer components
System.Windows.Forms.TextBox populationSizeBox
System.Windows.Forms.ComboBox selectionBox
System.Windows.Forms.ComboBox functionsSetBox
System.Windows.Forms.Label label4
System.Windows.Forms.ComboBox geneticMethodBox
System.Windows.Forms.GroupBox groupBox5
System.Windows.Forms.TextBox solutionBox
System.Windows.Forms.Button moreSettingsButton
System.Windows.Forms.ToolTip toolTip
int populationSize = 100
int selectionMethod = 0
int functionsSet = 0
int geneticMethod = 0
int headLength = 20
volatile bool needToStop = false
Detailed Description
Summary description for Form1.
Constructor & Destructor Documentation
MainForm() [1/4]
TimeSeries.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), TimeSeries.MainForm.chart, TimeSeries.MainForm.InitializeComponent(), and TimeSeries.MainForm.UpdateSettings().
Referenced by TimeSeries.MainForm.Main().
MainForm() [2/4]
TimeSeries.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), TimeSeries.MainForm.chart, TimeSeries.MainForm.InitializeComponent(), and TimeSeries.MainForm.UpdateSettings().
MainForm() [3/4]
TimeSeries.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), TimeSeries.MainForm.chart, TimeSeries.MainForm.functionsSet, TimeSeries.MainForm.functionsSetBox, TimeSeries.MainForm.geneticMethod, TimeSeries.MainForm.geneticMethodBox, TimeSeries.MainForm.InitializeComponent(), TimeSeries.MainForm.selectionBox, TimeSeries.MainForm.selectionMethod, and TimeSeries.MainForm.UpdateSettings().
MainForm() [4/4]
TimeSeries.MainForm.MainForm () inline
References AForge.Controls.Chart.AddDataSeries(), TimeSeries.MainForm.chart, TimeSeries.MainForm.InitializeComponent(), and TimeSeries.MainForm.UpdateSettings().
Member Function Documentation
Dispose() [1/4]
override void TimeSeries.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References TimeSeries.MainForm.components.
InitializeComponent() [1/4]
void TimeSeries.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by TimeSeries.MainForm.MainForm().
Main() [1/4]
static void TimeSeries.MainForm.Main () inline static private
The main entry point for the application.
References TimeSeries.MainForm.MainForm().
MainForm_Closing() [1/4]
void TimeSeries.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References TimeSeries.MainForm.needToStop, and TimeSeries.MainForm.workerThread.
UpdateSettings() [1/4]
void TimeSeries.MainForm.UpdateSettings () inline private
References TimeSeries.MainForm.alphaBox, TimeSeries.MainForm.iterations, TimeSeries.MainForm.iterationsBox, TimeSeries.MainForm.learningRate, TimeSeries.MainForm.learningRateBox, TimeSeries.MainForm.momentum, TimeSeries.MainForm.momentumBox, TimeSeries.MainForm.predictionSize, TimeSeries.MainForm.predictionSizeBox, TimeSeries.MainForm.sigmoidAlphaValue, TimeSeries.MainForm.windowSize, and TimeSeries.MainForm.windowSizeBox.
Referenced by TimeSeries.MainForm.MainForm(), and TimeSeries.MainForm.startButton_Click().
loadDataButton_Click() [1/4]
void TimeSeries.MainForm.loadDataButton_Click (object sender, System.EventArgs e) inline private
References TimeSeries.MainForm.chart, TimeSeries.MainForm.data, TimeSeries.MainForm.dataToShow, TimeSeries.MainForm.openFileDialog, AForge.Controls.Chart.RangeX, TimeSeries.MainForm.startButton, TimeSeries.MainForm.UpdateDataListView(), AForge.Controls.Chart.UpdateDataSeries(), and TimeSeries.MainForm.UpdateDelimiters().
UpdateDelimiters() [1/4]
void TimeSeries.MainForm.UpdateDelimiters () inline private
References TimeSeries.MainForm.chart, TimeSeries.MainForm.data, AForge.DoubleRange.Max, AForge.DoubleRange.Min, TimeSeries.MainForm.predictionDelimiter, TimeSeries.MainForm.predictionSize, AForge.Controls.Chart.RangeY, AForge.Controls.Chart.UpdateDataSeries(), TimeSeries.MainForm.windowDelimiter, and TimeSeries.MainForm.windowSize.
Referenced by TimeSeries.MainForm.loadDataButton_Click(), TimeSeries.MainForm.UpdatePredictionSize(), and TimeSeries.MainForm.UpdateWindowSize().
UpdateDataListView() [1/4]
void TimeSeries.MainForm.UpdateDataListView () inline private
References TimeSeries.MainForm.data, and TimeSeries.MainForm.dataList.
Referenced by TimeSeries.MainForm.loadDataButton_Click().
EnableControls() [1/4]
void TimeSeries.MainForm.EnableControls (bool enable) inline private
References TimeSeries.MainForm.alphaBox, TimeSeries.MainForm.iterationsBox, TimeSeries.MainForm.learningRateBox, TimeSeries.MainForm.loadDataButton, TimeSeries.MainForm.momentumBox, TimeSeries.MainForm.predictionSizeBox, TimeSeries.MainForm.startButton, TimeSeries.MainForm.stopButton, and TimeSeries.MainForm.windowSizeBox.
Referenced by TimeSeries.MainForm.EnableControls(), TimeSeries.MainForm.SearchSolution(), and TimeSeries.MainForm.startButton_Click().
windowSizeBox_TextChanged() [1/4]
void TimeSeries.MainForm.windowSizeBox_TextChanged (object sender, System.EventArgs e) inline private
References TimeSeries.MainForm.UpdateWindowSize().
predictionSizeBox_TextChanged() [1/4]
void TimeSeries.MainForm.predictionSizeBox_TextChanged (object sender, System.EventArgs e) inline private
References TimeSeries.MainForm.UpdatePredictionSize().
UpdateWindowSize() [1/4]
void TimeSeries.MainForm.UpdateWindowSize () inline private
References TimeSeries.MainForm.data, TimeSeries.MainForm.UpdateDelimiters(), TimeSeries.MainForm.windowSize, and TimeSeries.MainForm.windowSizeBox.
Referenced by TimeSeries.MainForm.windowSizeBox_TextChanged().
UpdatePredictionSize() [1/4]
void TimeSeries.MainForm.UpdatePredictionSize () inline private
References TimeSeries.MainForm.data, TimeSeries.MainForm.predictionSize, TimeSeries.MainForm.predictionSizeBox, TimeSeries.MainForm.UpdateDelimiters(), and TimeSeries.MainForm.windowSize.
Referenced by TimeSeries.MainForm.predictionSizeBox_TextChanged().
startButton_Click() [1/4]
void TimeSeries.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References TimeSeries.MainForm.alphaBox, TimeSeries.MainForm.data, TimeSeries.MainForm.dataList, TimeSeries.MainForm.EnableControls(), TimeSeries.MainForm.iterations, TimeSeries.MainForm.iterationsBox, TimeSeries.MainForm.learningRate, TimeSeries.MainForm.learningRateBox, TimeSeries.MainForm.momentum, TimeSeries.MainForm.momentumBox, TimeSeries.MainForm.needToStop, TimeSeries.MainForm.SearchSolution(), TimeSeries.MainForm.sigmoidAlphaValue, TimeSeries.MainForm.UpdateSettings(), and TimeSeries.MainForm.workerThread.
stopButton_Click() [1/4]
void TimeSeries.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References TimeSeries.MainForm.needToStop, and TimeSeries.MainForm.workerThread.
SearchSolution() [1/4]
void TimeSeries.MainForm.SearchSolution () inline private
References TimeSeries.MainForm.chart, AForge.Neuro.Network.Compute(), TimeSeries.MainForm.currentIterationBox, TimeSeries.MainForm.currentLearningErrorBox, TimeSeries.MainForm.currentPredictionErrorBox, TimeSeries.MainForm.data, TimeSeries.MainForm.dataList, TimeSeries.MainForm.EnableControls(), TimeSeries.MainForm.iterations, AForge.Neuro.Learning.BackPropagationLearning.LearningRate, TimeSeries.MainForm.learningRate, AForge.DoubleRange.Length, AForge.DoubleRange.Min, AForge.Neuro.Learning.BackPropagationLearning.Momentum, TimeSeries.MainForm.momentum, TimeSeries.MainForm.needToStop, TimeSeries.MainForm.predictionSize, AForge.Controls.Chart.RangeY, AForge.Neuro.Learning.BackPropagationLearning.RunEpoch(), TimeSeries.MainForm.sigmoidAlphaValue, AForge.Controls.Chart.UpdateDataSeries(), and TimeSeries.MainForm.windowSize.
Referenced by TimeSeries.MainForm.startButton_Click().
Dispose() [2/4]
override void TimeSeries.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References TimeSeries.MainForm.components.
InitializeComponent() [2/4]
void TimeSeries.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [2/4]
static void TimeSeries.MainForm.Main () inline static private
The main entry point for the application.
References TimeSeries.MainForm.MainForm().
MainForm_Closing() [2/4]
void TimeSeries.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References TimeSeries.MainForm.needToStop, and TimeSeries.MainForm.workerThread.
UpdateSettings() [2/4]
void TimeSeries.MainForm.UpdateSettings () inline private
References TimeSeries.MainForm.alphaBox, TimeSeries.MainForm.iterations, TimeSeries.MainForm.iterationsBox, TimeSeries.MainForm.learningRate, TimeSeries.MainForm.learningRateBox, TimeSeries.MainForm.momentum, TimeSeries.MainForm.momentumBox, TimeSeries.MainForm.predictionSize, TimeSeries.MainForm.predictionSizeBox, TimeSeries.MainForm.sigmoidAlphaValue, TimeSeries.MainForm.windowSize, and TimeSeries.MainForm.windowSizeBox.
loadDataButton_Click() [2/4]
void TimeSeries.MainForm.loadDataButton_Click (object sender, System.EventArgs e) inline private
References TimeSeries.MainForm.chart, TimeSeries.MainForm.data, TimeSeries.MainForm.dataToShow, TimeSeries.MainForm.openFileDialog, AForge.Controls.Chart.RangeX, TimeSeries.MainForm.startButton, TimeSeries.MainForm.UpdateDataListView(), AForge.Controls.Chart.UpdateDataSeries(), and TimeSeries.MainForm.UpdateDelimiters().
UpdateDelimiters() [2/4]
void TimeSeries.MainForm.UpdateDelimiters () inline private
References TimeSeries.MainForm.chart, TimeSeries.MainForm.data, AForge.DoubleRange.Max, AForge.DoubleRange.Min, TimeSeries.MainForm.predictionDelimiter, TimeSeries.MainForm.predictionSize, AForge.Controls.Chart.RangeY, AForge.Controls.Chart.UpdateDataSeries(), TimeSeries.MainForm.windowDelimiter, and TimeSeries.MainForm.windowSize.
UpdateDataListView() [2/4]
void TimeSeries.MainForm.UpdateDataListView () inline private
References TimeSeries.MainForm.data, and TimeSeries.MainForm.dataList.
EnableControls() [2/4]
void TimeSeries.MainForm.EnableControls (bool enable) inline private
References TimeSeries.MainForm.alphaBox, TimeSeries.MainForm.iterationsBox, TimeSeries.MainForm.learningRateBox, TimeSeries.MainForm.loadDataButton, TimeSeries.MainForm.momentumBox, TimeSeries.MainForm.predictionSizeBox, TimeSeries.MainForm.startButton, TimeSeries.MainForm.stopButton, and TimeSeries.MainForm.windowSizeBox.
windowSizeBox_TextChanged() [2/4]
void TimeSeries.MainForm.windowSizeBox_TextChanged (object sender, System.EventArgs e) inline private
References TimeSeries.MainForm.UpdateWindowSize().
predictionSizeBox_TextChanged() [2/4]
void TimeSeries.MainForm.predictionSizeBox_TextChanged (object sender, System.EventArgs e) inline private
References TimeSeries.MainForm.UpdatePredictionSize().
UpdateWindowSize() [2/4]
void TimeSeries.MainForm.UpdateWindowSize () inline private
References TimeSeries.MainForm.data, TimeSeries.MainForm.UpdateDelimiters(), TimeSeries.MainForm.windowSize, and TimeSeries.MainForm.windowSizeBox.
UpdatePredictionSize() [2/4]
void TimeSeries.MainForm.UpdatePredictionSize () inline private
References TimeSeries.MainForm.data, TimeSeries.MainForm.predictionSize, TimeSeries.MainForm.predictionSizeBox, TimeSeries.MainForm.UpdateDelimiters(), and TimeSeries.MainForm.windowSize.
startButton_Click() [2/4]
void TimeSeries.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References TimeSeries.MainForm.alphaBox, TimeSeries.MainForm.data, TimeSeries.MainForm.dataList, TimeSeries.MainForm.EnableControls(), TimeSeries.MainForm.iterations, TimeSeries.MainForm.iterationsBox, TimeSeries.MainForm.learningRate, TimeSeries.MainForm.learningRateBox, TimeSeries.MainForm.momentum, TimeSeries.MainForm.momentumBox, TimeSeries.MainForm.needToStop, TimeSeries.MainForm.SearchSolution(), TimeSeries.MainForm.sigmoidAlphaValue, TimeSeries.MainForm.UpdateSettings(), and TimeSeries.MainForm.workerThread.
stopButton_Click() [2/4]
void TimeSeries.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References TimeSeries.MainForm.needToStop, and TimeSeries.MainForm.workerThread.
SearchSolution() [2/4]
void TimeSeries.MainForm.SearchSolution () inline private
References TimeSeries.MainForm.chart, AForge.Neuro.Network.Compute(), TimeSeries.MainForm.currentIterationBox, TimeSeries.MainForm.currentLearningErrorBox, TimeSeries.MainForm.currentPredictionErrorBox, TimeSeries.MainForm.data, TimeSeries.MainForm.dataList, TimeSeries.MainForm.EnableControls(), TimeSeries.MainForm.iterations, AForge.Neuro.Learning.BackPropagationLearning.LearningRate, TimeSeries.MainForm.learningRate, AForge.DoubleRange.Length, AForge.DoubleRange.Min, AForge.Neuro.Learning.BackPropagationLearning.Momentum, TimeSeries.MainForm.momentum, TimeSeries.MainForm.needToStop, TimeSeries.MainForm.predictionSize, AForge.Controls.Chart.RangeY, AForge.Neuro.Learning.BackPropagationLearning.RunEpoch(), TimeSeries.MainForm.sigmoidAlphaValue, AForge.Controls.Chart.UpdateDataSeries(), and TimeSeries.MainForm.windowSize.
Dispose() [3/4]
override void TimeSeries.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References TimeSeries.MainForm.components.
InitializeComponent() [3/4]
void TimeSeries.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [3/4]
static void TimeSeries.MainForm.Main () inline static private
The main entry point for the application.
References TimeSeries.MainForm.MainForm().
SetTextCallback() [1/2]
delegate void TimeSeries.MainForm.SetTextCallback (System.Windows.Forms.Control control, string text) private
Referenced by TimeSeries.MainForm.SetText().
AddSubItemCallback() [1/2]
delegate void TimeSeries.MainForm.AddSubItemCallback (System.Windows.Forms.ListView control, int item, string subitemText) private
Referenced by TimeSeries.MainForm.AddSubItem().
SetText() [1/2]
void TimeSeries.MainForm.SetText (System.Windows.Forms.Control control, string text) inline private
References TimeSeries.MainForm.SetTextCallback().
Referenced by TimeSeries.MainForm.SearchSolution(), and TimeSeries.MainForm.SetText().
AddSubItem() [1/2]
void TimeSeries.MainForm.AddSubItem (System.Windows.Forms.ListView control, int item, string subitemText) inline private
References TimeSeries.MainForm.AddSubItemCallback().
Referenced by TimeSeries.MainForm.AddSubItem(), and TimeSeries.MainForm.SearchSolution().
MainForm_Closing() [3/4]
void TimeSeries.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References TimeSeries.MainForm.needToStop, and TimeSeries.MainForm.workerThread.
UpdateSettings() [3/4]
void TimeSeries.MainForm.UpdateSettings () inline private
References TimeSeries.MainForm.iterations, TimeSeries.MainForm.iterationsBox, TimeSeries.MainForm.populationSize, TimeSeries.MainForm.populationSizeBox, TimeSeries.MainForm.predictionSize, TimeSeries.MainForm.predictionSizeBox, TimeSeries.MainForm.windowSize, and TimeSeries.MainForm.windowSizeBox.
loadDataButton_Click() [3/4]
void TimeSeries.MainForm.loadDataButton_Click (object sender, System.EventArgs e) inline private
References TimeSeries.MainForm.chart, TimeSeries.MainForm.data, TimeSeries.MainForm.dataToShow, TimeSeries.MainForm.openFileDialog, AForge.Controls.Chart.RangeX, TimeSeries.MainForm.startButton, TimeSeries.MainForm.UpdateDataListView(), AForge.Controls.Chart.UpdateDataSeries(), and TimeSeries.MainForm.UpdateDelimiters().
UpdateDelimiters() [3/4]
void TimeSeries.MainForm.UpdateDelimiters () inline private
References TimeSeries.MainForm.chart, TimeSeries.MainForm.data, AForge.DoubleRange.Max, AForge.DoubleRange.Min, TimeSeries.MainForm.predictionDelimiter, TimeSeries.MainForm.predictionSize, AForge.Controls.Chart.RangeY, AForge.Controls.Chart.UpdateDataSeries(), TimeSeries.MainForm.windowDelimiter, and TimeSeries.MainForm.windowSize.
UpdateDataListView() [3/4]
void TimeSeries.MainForm.UpdateDataListView () inline private
References TimeSeries.MainForm.data, and TimeSeries.MainForm.dataList.
EnableCallback() [1/2]
delegate void TimeSeries.MainForm.EnableCallback (bool enable) private
Referenced by TimeSeries.MainForm.EnableControls().
EnableControls() [3/4]
void TimeSeries.MainForm.EnableControls (bool enable) inline private
References TimeSeries.MainForm.EnableCallback(), TimeSeries.MainForm.EnableControls(), TimeSeries.MainForm.functionsSetBox, TimeSeries.MainForm.geneticMethodBox, TimeSeries.MainForm.iterationsBox, TimeSeries.MainForm.loadDataButton, TimeSeries.MainForm.moreSettingsButton, TimeSeries.MainForm.populationSizeBox, TimeSeries.MainForm.predictionSizeBox, TimeSeries.MainForm.selectionBox, TimeSeries.MainForm.startButton, TimeSeries.MainForm.stopButton, and TimeSeries.MainForm.windowSizeBox.
windowSizeBox_TextChanged() [3/4]
void TimeSeries.MainForm.windowSizeBox_TextChanged (object sender, System.EventArgs e) inline private
References TimeSeries.MainForm.UpdateWindowSize().
predictionSizeBox_TextChanged() [3/4]
void TimeSeries.MainForm.predictionSizeBox_TextChanged (object sender, System.EventArgs e) inline private
References TimeSeries.MainForm.UpdatePredictionSize().
UpdateWindowSize() [3/4]
void TimeSeries.MainForm.UpdateWindowSize () inline private
References TimeSeries.MainForm.data, TimeSeries.MainForm.UpdateDelimiters(), TimeSeries.MainForm.windowSize, and TimeSeries.MainForm.windowSizeBox.
UpdatePredictionSize() [3/4]
void TimeSeries.MainForm.UpdatePredictionSize () inline private
References TimeSeries.MainForm.data, TimeSeries.MainForm.predictionSize, TimeSeries.MainForm.predictionSizeBox, TimeSeries.MainForm.UpdateDelimiters(), and TimeSeries.MainForm.windowSize.
ClearSolution()
void TimeSeries.MainForm.ClearSolution () inline private
References TimeSeries.MainForm.chart, TimeSeries.MainForm.dataList, TimeSeries.MainForm.solutionBox, and AForge.Controls.Chart.UpdateDataSeries().
Referenced by TimeSeries.MainForm.startButton_Click().
startButton_Click() [3/4]
void TimeSeries.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References TimeSeries.MainForm.ClearSolution(), TimeSeries.MainForm.EnableControls(), TimeSeries.MainForm.functionsSet, TimeSeries.MainForm.functionsSetBox, TimeSeries.MainForm.geneticMethod, TimeSeries.MainForm.geneticMethodBox, TimeSeries.MainForm.iterations, TimeSeries.MainForm.iterationsBox, TimeSeries.MainForm.needToStop, TimeSeries.MainForm.populationSize, TimeSeries.MainForm.populationSizeBox, TimeSeries.MainForm.SearchSolution(), TimeSeries.MainForm.selectionBox, TimeSeries.MainForm.selectionMethod, TimeSeries.MainForm.UpdateSettings(), and TimeSeries.MainForm.workerThread.
stopButton_Click() [3/4]
void TimeSeries.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References TimeSeries.MainForm.needToStop, and TimeSeries.MainForm.workerThread.
SearchSolution() [3/4]
void TimeSeries.MainForm.SearchSolution () inline private
References TimeSeries.MainForm.AddSubItem(), AForge.Genetic.Population.BestChromosome, TimeSeries.MainForm.chart, TimeSeries.MainForm.currentIterationBox, TimeSeries.MainForm.currentLearningErrorBox, TimeSeries.MainForm.currentPredictionErrorBox, TimeSeries.MainForm.data, TimeSeries.MainForm.dataList, TimeSeries.MainForm.EnableControls(), AForge.PolishExpression.Evaluate(), TimeSeries.MainForm.functionsSet, TimeSeries.MainForm.geneticMethod, TimeSeries.MainForm.headLength, TimeSeries.MainForm.iterations, TimeSeries.MainForm.needToStop, TimeSeries.MainForm.populationSize, TimeSeries.MainForm.predictionSize, AForge.Genetic.Population.RunEpoch(), TimeSeries.MainForm.selectionMethod, TimeSeries.MainForm.SetText(), TimeSeries.MainForm.solutionBox, AForge.Controls.Chart.UpdateDataSeries(), and TimeSeries.MainForm.windowSize.
moreSettingsButton_Click()
void TimeSeries.MainForm.moreSettingsButton_Click (object sender, System.EventArgs e) inline private
References TimeSeries.ExSettingsDialog.HeadLength, TimeSeries.MainForm.headLength, AForge.Genetic.GPTreeChromosome.MaxInitialLevel, TimeSeries.ExSettingsDialog.MaxInitialTreeLevel, AForge.Genetic.GPTreeChromosome.MaxLevel, and TimeSeries.ExSettingsDialog.MaxTreeLevel.
Dispose() [4/4]
override void TimeSeries.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
References TimeSeries.MainForm.components.
InitializeComponent() [4/4]
void TimeSeries.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Main() [4/4]
static void TimeSeries.MainForm.Main () inline static private
The main entry point for the application.
References TimeSeries.MainForm.MainForm().
SetTextCallback() [2/2]
delegate void TimeSeries.MainForm.SetTextCallback (System.Windows.Forms.Control control, string text) private
AddSubItemCallback() [2/2]
delegate void TimeSeries.MainForm.AddSubItemCallback (System.Windows.Forms.ListView control, int item, string subitemText) private
SetText() [2/2]
void TimeSeries.MainForm.SetText (System.Windows.Forms.Control control, string text) inline private
References TimeSeries.MainForm.SetText(), and TimeSeries.MainForm.SetTextCallback().
AddSubItem() [2/2]
void TimeSeries.MainForm.AddSubItem (System.Windows.Forms.ListView control, int item, string subitemText) inline private
References TimeSeries.MainForm.AddSubItem(), and TimeSeries.MainForm.AddSubItemCallback().
MainForm_Closing() [4/4]
void TimeSeries.MainForm.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References TimeSeries.MainForm.needToStop, and TimeSeries.MainForm.workerThread.
UpdateSettings() [4/4]
void TimeSeries.MainForm.UpdateSettings () inline private
References TimeSeries.MainForm.alphaBox, TimeSeries.MainForm.iterations, TimeSeries.MainForm.iterationsBox, TimeSeries.MainForm.learningRate, TimeSeries.MainForm.learningRateBox, TimeSeries.MainForm.momentum, TimeSeries.MainForm.momentumBox, TimeSeries.MainForm.predictionSize, TimeSeries.MainForm.predictionSizeBox, TimeSeries.MainForm.sigmoidAlphaValue, TimeSeries.MainForm.windowSize, and TimeSeries.MainForm.windowSizeBox.
loadDataButton_Click() [4/4]
void TimeSeries.MainForm.loadDataButton_Click (object sender, System.EventArgs e) inline private
References TimeSeries.MainForm.chart, TimeSeries.MainForm.data, TimeSeries.MainForm.dataToShow, TimeSeries.MainForm.openFileDialog, AForge.Controls.Chart.RangeX, TimeSeries.MainForm.startButton, TimeSeries.MainForm.UpdateDataListView(), AForge.Controls.Chart.UpdateDataSeries(), and TimeSeries.MainForm.UpdateDelimiters().
UpdateDelimiters() [4/4]
void TimeSeries.MainForm.UpdateDelimiters () inline private
References TimeSeries.MainForm.chart, TimeSeries.MainForm.data, AForge.DoubleRange.Max, AForge.DoubleRange.Min, TimeSeries.MainForm.predictionDelimiter, TimeSeries.MainForm.predictionSize, AForge.Controls.Chart.RangeY, AForge.Controls.Chart.UpdateDataSeries(), TimeSeries.MainForm.windowDelimiter, and TimeSeries.MainForm.windowSize.
UpdateDataListView() [4/4]
void TimeSeries.MainForm.UpdateDataListView () inline private
References TimeSeries.MainForm.data, and TimeSeries.MainForm.dataList.
EnableCallback() [2/2]
delegate void TimeSeries.MainForm.EnableCallback (bool enable) private
EnableControls() [4/4]
void TimeSeries.MainForm.EnableControls (bool enable) inline private
References TimeSeries.MainForm.alphaBox, TimeSeries.MainForm.EnableCallback(), TimeSeries.MainForm.EnableControls(), TimeSeries.MainForm.iterationsBox, TimeSeries.MainForm.learningRateBox, TimeSeries.MainForm.loadDataButton, TimeSeries.MainForm.momentumBox, TimeSeries.MainForm.predictionSizeBox, TimeSeries.MainForm.startButton, TimeSeries.MainForm.stopButton, and TimeSeries.MainForm.windowSizeBox.
windowSizeBox_TextChanged() [4/4]
void TimeSeries.MainForm.windowSizeBox_TextChanged (object sender, System.EventArgs e) inline private
References TimeSeries.MainForm.UpdateWindowSize().
predictionSizeBox_TextChanged() [4/4]
void TimeSeries.MainForm.predictionSizeBox_TextChanged (object sender, System.EventArgs e) inline private
References TimeSeries.MainForm.UpdatePredictionSize().
UpdateWindowSize() [4/4]
void TimeSeries.MainForm.UpdateWindowSize () inline private
References TimeSeries.MainForm.data, TimeSeries.MainForm.UpdateDelimiters(), TimeSeries.MainForm.windowSize, and TimeSeries.MainForm.windowSizeBox.
UpdatePredictionSize() [4/4]
void TimeSeries.MainForm.UpdatePredictionSize () inline private
References TimeSeries.MainForm.data, TimeSeries.MainForm.predictionSize, TimeSeries.MainForm.predictionSizeBox, TimeSeries.MainForm.UpdateDelimiters(), and TimeSeries.MainForm.windowSize.
startButton_Click() [4/4]
void TimeSeries.MainForm.startButton_Click (object sender, System.EventArgs e) inline private
References TimeSeries.MainForm.alphaBox, TimeSeries.MainForm.data, TimeSeries.MainForm.dataList, TimeSeries.MainForm.EnableControls(), TimeSeries.MainForm.iterations, TimeSeries.MainForm.iterationsBox, TimeSeries.MainForm.learningRate, TimeSeries.MainForm.learningRateBox, TimeSeries.MainForm.momentum, TimeSeries.MainForm.momentumBox, TimeSeries.MainForm.needToStop, TimeSeries.MainForm.SearchSolution(), TimeSeries.MainForm.sigmoidAlphaValue, TimeSeries.MainForm.UpdateSettings(), and TimeSeries.MainForm.workerThread.
stopButton_Click() [4/4]
void TimeSeries.MainForm.stopButton_Click (object sender, System.EventArgs e) inline private
References TimeSeries.MainForm.needToStop, and TimeSeries.MainForm.workerThread.
SearchSolution() [4/4]
void TimeSeries.MainForm.SearchSolution () inline private
References TimeSeries.MainForm.AddSubItem(), TimeSeries.MainForm.chart, AForge.Neuro.Network.Compute(), TimeSeries.MainForm.currentIterationBox, TimeSeries.MainForm.currentLearningErrorBox, TimeSeries.MainForm.currentPredictionErrorBox, TimeSeries.MainForm.data, TimeSeries.MainForm.dataList, TimeSeries.MainForm.EnableControls(), TimeSeries.MainForm.iterations, AForge.Neuro.Learning.BackPropagationLearning.LearningRate, TimeSeries.MainForm.learningRate, AForge.DoubleRange.Length, AForge.DoubleRange.Min, AForge.Neuro.Learning.BackPropagationLearning.Momentum, TimeSeries.MainForm.momentum, TimeSeries.MainForm.needToStop, TimeSeries.MainForm.predictionSize, AForge.Controls.Chart.RangeY, AForge.Neuro.Learning.BackPropagationLearning.RunEpoch(), TimeSeries.MainForm.SetText(), TimeSeries.MainForm.sigmoidAlphaValue, AForge.Controls.Chart.UpdateDataSeries(), and TimeSeries.MainForm.windowSize.
Member Data Documentation
groupBox1
System Windows Forms GroupBox TimeSeries.MainForm.groupBox1 private
dataList
System Windows Forms ListView TimeSeries.MainForm.dataList private
Referenced by TimeSeries.MainForm.ClearSolution(), TimeSeries.MainForm.SearchSolution(), TimeSeries.MainForm.startButton_Click(), and TimeSeries.MainForm.UpdateDataListView().
yColumnHeader
System Windows Forms ColumnHeader TimeSeries.MainForm.yColumnHeader private
estimatedYColumnHeader
System Windows Forms ColumnHeader TimeSeries.MainForm.estimatedYColumnHeader private
loadDataButton
System Windows Forms Button TimeSeries.MainForm.loadDataButton private
Referenced by TimeSeries.MainForm.EnableControls().
groupBox2
System Windows Forms GroupBox TimeSeries.MainForm.groupBox2 private
chart
AForge Controls Chart TimeSeries.MainForm.chart private
Referenced by TimeSeries.MainForm.ClearSolution(), TimeSeries.MainForm.loadDataButton_Click(), TimeSeries.MainForm.MainForm(), TimeSeries.MainForm.SearchSolution(), and TimeSeries.MainForm.UpdateDelimiters().
openFileDialog
System Windows Forms OpenFileDialog TimeSeries.MainForm.openFileDialog private
Referenced by TimeSeries.MainForm.loadDataButton_Click().
groupBox3
System Windows Forms GroupBox TimeSeries.MainForm.groupBox3 private
momentumBox
System Windows Forms TextBox TimeSeries.MainForm.momentumBox private
Referenced by TimeSeries.MainForm.EnableControls(), TimeSeries.MainForm.startButton_Click(), and TimeSeries.MainForm.UpdateSettings().
label6
System Windows Forms Label TimeSeries.MainForm.label6 private
alphaBox
System Windows Forms TextBox TimeSeries.MainForm.alphaBox private
Referenced by TimeSeries.MainForm.EnableControls(), TimeSeries.MainForm.startButton_Click(), and TimeSeries.MainForm.UpdateSettings().
label2
System Windows Forms Label TimeSeries.MainForm.label2 private
learningRateBox
System Windows Forms TextBox TimeSeries.MainForm.learningRateBox private
Referenced by TimeSeries.MainForm.EnableControls(), TimeSeries.MainForm.startButton_Click(), and TimeSeries.MainForm.UpdateSettings().
label1
System Windows Forms Label TimeSeries.MainForm.label1 private
label10
System Windows Forms Label TimeSeries.MainForm.label10 private
iterationsBox
System Windows Forms TextBox TimeSeries.MainForm.iterationsBox private
Referenced by TimeSeries.MainForm.EnableControls(), TimeSeries.MainForm.startButton_Click(), and TimeSeries.MainForm.UpdateSettings().
label9
System Windows Forms Label TimeSeries.MainForm.label9 private
label8
System Windows Forms Label TimeSeries.MainForm.label8 private
predictionSizeBox
System Windows Forms TextBox TimeSeries.MainForm.predictionSizeBox private
Referenced by TimeSeries.MainForm.EnableControls(), TimeSeries.MainForm.UpdatePredictionSize(), and TimeSeries.MainForm.UpdateSettings().
label7
System Windows Forms Label TimeSeries.MainForm.label7 private
windowSizeBox
System Windows Forms TextBox TimeSeries.MainForm.windowSizeBox private
Referenced by TimeSeries.MainForm.EnableControls(), TimeSeries.MainForm.UpdateSettings(), and TimeSeries.MainForm.UpdateWindowSize().
label3
System Windows Forms Label TimeSeries.MainForm.label3 private
label5
System Windows Forms Label TimeSeries.MainForm.label5 private
stopButton
System Windows Forms Button TimeSeries.MainForm.stopButton private
Referenced by TimeSeries.MainForm.EnableControls().
startButton
System Windows Forms Button TimeSeries.MainForm.startButton private
Referenced by TimeSeries.MainForm.EnableControls(), and TimeSeries.MainForm.loadDataButton_Click().
groupBox4
System Windows Forms GroupBox TimeSeries.MainForm.groupBox4 private
currentPredictionErrorBox
System Windows Forms TextBox TimeSeries.MainForm.currentPredictionErrorBox private
Referenced by TimeSeries.MainForm.SearchSolution().
label13
System Windows Forms Label TimeSeries.MainForm.label13 private
currentLearningErrorBox
System Windows Forms TextBox TimeSeries.MainForm.currentLearningErrorBox private
Referenced by TimeSeries.MainForm.SearchSolution().
label12
System Windows Forms Label TimeSeries.MainForm.label12 private
currentIterationBox
System Windows Forms TextBox TimeSeries.MainForm.currentIterationBox private
Referenced by TimeSeries.MainForm.SearchSolution().
label11
System Windows Forms Label TimeSeries.MainForm.label11 private
components [1/2]
System ComponentModel Container TimeSeries.MainForm.components = null private
Required designer variable.
Referenced by TimeSeries.MainForm.Dispose().
data
double [] TimeSeries.MainForm.data = null private
Referenced by TimeSeries.MainForm.loadDataButton_Click(), TimeSeries.MainForm.SearchSolution(), TimeSeries.MainForm.startButton_Click(), TimeSeries.MainForm.UpdateDataListView(), TimeSeries.MainForm.UpdateDelimiters(), TimeSeries.MainForm.UpdatePredictionSize(), and TimeSeries.MainForm.UpdateWindowSize().
dataToShow
double [,] TimeSeries.MainForm.dataToShow = null private
Referenced by TimeSeries.MainForm.loadDataButton_Click().
learningRate
double TimeSeries.MainForm.learningRate = 0.1 private
Referenced by TimeSeries.MainForm.SearchSolution(), TimeSeries.MainForm.startButton_Click(), and TimeSeries.MainForm.UpdateSettings().
momentum
double TimeSeries.MainForm.momentum = 0.0 private
Referenced by TimeSeries.MainForm.SearchSolution(), TimeSeries.MainForm.startButton_Click(), and TimeSeries.MainForm.UpdateSettings().
sigmoidAlphaValue
double TimeSeries.MainForm.sigmoidAlphaValue = 2.0 private
Referenced by TimeSeries.MainForm.SearchSolution(), TimeSeries.MainForm.startButton_Click(), and TimeSeries.MainForm.UpdateSettings().
windowSize
int TimeSeries.MainForm.windowSize = 5 private
Referenced by TimeSeries.MainForm.SearchSolution(), TimeSeries.MainForm.UpdateDelimiters(), TimeSeries.MainForm.UpdatePredictionSize(), TimeSeries.MainForm.UpdateSettings(), and TimeSeries.MainForm.UpdateWindowSize().
predictionSize
int TimeSeries.MainForm.predictionSize = 1 private
Referenced by TimeSeries.MainForm.SearchSolution(), TimeSeries.MainForm.UpdateDelimiters(), TimeSeries.MainForm.UpdatePredictionSize(), and TimeSeries.MainForm.UpdateSettings().
iterations
int TimeSeries.MainForm.iterations = 1000 private
Referenced by TimeSeries.MainForm.SearchSolution(), TimeSeries.MainForm.startButton_Click(), and TimeSeries.MainForm.UpdateSettings().
workerThread
Thread TimeSeries.MainForm.workerThread = null private
Referenced by TimeSeries.MainForm.MainForm_Closing(), TimeSeries.MainForm.startButton_Click(), and TimeSeries.MainForm.stopButton_Click().
needToStop [1/2]
volatile bool TimeSeries.MainForm.needToStop = false private
Referenced by TimeSeries.MainForm.MainForm_Closing(), TimeSeries.MainForm.SearchSolution(), TimeSeries.MainForm.startButton_Click(), and TimeSeries.MainForm.stopButton_Click().
windowDelimiter
double [,] TimeSeries.MainForm.windowDelimiter = new double[2, 2] { { 0, 0 }, { 0, 0 } } private
Referenced by TimeSeries.MainForm.UpdateDelimiters().
predictionDelimiter
double [,] TimeSeries.MainForm.predictionDelimiter = new double[2, 2] { { 0, 0 }, { 0, 0 } } private
Referenced by TimeSeries.MainForm.UpdateDelimiters().
components [2/2]
System.ComponentModel.IContainer TimeSeries.MainForm.components private
populationSizeBox
System.Windows.Forms.TextBox TimeSeries.MainForm.populationSizeBox private
Referenced by TimeSeries.MainForm.EnableControls(), TimeSeries.MainForm.startButton_Click(), and TimeSeries.MainForm.UpdateSettings().
selectionBox
System.Windows.Forms.ComboBox TimeSeries.MainForm.selectionBox private
Referenced by TimeSeries.MainForm.EnableControls(), TimeSeries.MainForm.MainForm(), and TimeSeries.MainForm.startButton_Click().
functionsSetBox
System.Windows.Forms.ComboBox TimeSeries.MainForm.functionsSetBox private
Referenced by TimeSeries.MainForm.EnableControls(), TimeSeries.MainForm.MainForm(), and TimeSeries.MainForm.startButton_Click().
label4
System.Windows.Forms.Label TimeSeries.MainForm.label4 private
geneticMethodBox
System.Windows.Forms.ComboBox TimeSeries.MainForm.geneticMethodBox private
Referenced by TimeSeries.MainForm.EnableControls(), TimeSeries.MainForm.MainForm(), and TimeSeries.MainForm.startButton_Click().
groupBox5
System.Windows.Forms.GroupBox TimeSeries.MainForm.groupBox5 private
solutionBox
System.Windows.Forms.TextBox TimeSeries.MainForm.solutionBox private
Referenced by TimeSeries.MainForm.ClearSolution(), and TimeSeries.MainForm.SearchSolution().
moreSettingsButton
System.Windows.Forms.Button TimeSeries.MainForm.moreSettingsButton private
Referenced by TimeSeries.MainForm.EnableControls().
toolTip
System.Windows.Forms.ToolTip TimeSeries.MainForm.toolTip private
populationSize
int TimeSeries.MainForm.populationSize = 100 private
Referenced by TimeSeries.MainForm.SearchSolution(), TimeSeries.MainForm.startButton_Click(), and TimeSeries.MainForm.UpdateSettings().
selectionMethod
int TimeSeries.MainForm.selectionMethod = 0 private
Referenced by TimeSeries.MainForm.MainForm(), TimeSeries.MainForm.SearchSolution(), and TimeSeries.MainForm.startButton_Click().
functionsSet
int TimeSeries.MainForm.functionsSet = 0 private
Referenced by TimeSeries.MainForm.MainForm(), TimeSeries.MainForm.SearchSolution(), and TimeSeries.MainForm.startButton_Click().
geneticMethod
int TimeSeries.MainForm.geneticMethod = 0 private
Referenced by TimeSeries.MainForm.MainForm(), TimeSeries.MainForm.SearchSolution(), and TimeSeries.MainForm.startButton_Click().
headLength
int TimeSeries.MainForm.headLength = 20 private
Referenced by TimeSeries.MainForm.moreSettingsButton_Click(), and TimeSeries.MainForm.SearchSolution().
needToStop [2/2]
volatile bool TimeSeries.MainForm.needToStop = false private
The documentation for this class was generated from the following file:
shelldev/lib/external/neuralnetworks/neuro_src/Samples/Neuro/Back Propagation/TimeSeries/Backup/MainForm.cs