Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGESDD Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGESDD Class Reference
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGESDD (DBDSDC dbdsdc, DGEBRD dgebrd, DGELQF dgelqf, DGEMM dgemm, DGEQRF dgeqrf, DLACPY dlacpy, DLASCL dlascl, DLASET dlaset, DORGBR dorgbr, DORGLQ dorglq, DORGQR dorgqr, DORMBR dormbr, XERBLA xerbla, DLAMCH dlamch, DLANGE dlange, ILAENV ilaenv, LSAME lsame)
DGESDD ()
void Run (string JOBZ, int M, int N, ref double[] A, int offset_a, int LDA, ref double[] S, int offset_s, ref double[] U, int offset_u, int LDU, ref double[] VT, int offset_vt, int LDVT, ref double[] WORK, int offset_work, int LWORK, ref int[] IWORK, int offset_iwork, ref int INFO)
Private Attributes
DBDSDC _dbdsdc
DGEBRD _dgebrd
DGELQF _dgelqf
DGEMM _dgemm
DGEQRF _dgeqrf
DLACPY _dlacpy
DLASCL _dlascl
DLASET _dlaset
DORGBR _dorgbr
DORGLQ _dorglq
DORGQR _dorgqr
DORMBR _dormbr
XERBLA _xerbla
DLAMCH _dlamch
DLANGE _dlange
ILAENV _ilaenv
LSAME _lsame
int[] IDUM = new int[1]
double[] DUM = new double[1]
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
Detailed Description
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGESDD computes the singular value decomposition (SVD) of a real M-by-N matrix A, optionally computing the left and right singular vectors. If singular vectors are desired, it uses a divide-and-conquer algorithm.
The SVD is written
A = U * SIGMA * transpose(V)
where SIGMA is an M-by-N matrix which is zero except for its min(m,n) diagonal elements, U is an M-by-M orthogonal matrix, and V is an N-by-N orthogonal matrix. The diagonal elements of SIGMA are the singular values of A; they are real and non-negative, and are returned in descending order. The first min(m,n) columns of U and V are the left and right singular vectors of A.
Note that the routine returns VT = V**T, not V.
The divide and conquer algorithm makes very mild assumptions about floating point arithmetic. It will work on machines with a guard digit in add/subtract, or on those binary machines without guard digits which subtract like the Cray X-MP, Cray Y-MP, Cray C-90, or Cray-2. It could conceivably fail on hexadecimal or decimal machines without guard digits, but we know of none.
/summary>
Constructor & Destructor Documentation
DGESDD() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGESDD.DGESDD (DBDSDC dbdsdc, DGEBRD dgebrd, DGELQF dgelqf, DGEMM dgemm, DGEQRF dgeqrf, DLACPY dlacpy, DLASCL dlascl, DLASET dlaset, DORGBR dorgbr, DORGLQ dorglq, DORGQR dorgqr, DORMBR dormbr, XERBLA xerbla, DLAMCH dlamch, DLANGE dlange, ILAENV ilaenv, LSAME lsame) inline
DGESDD() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGESDD.DGESDD () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run (string JOBZ, int M, int N, ref double[] A, int offset_a, int LDA, ref double[] S, int offset_s, ref double[] U, int offset_u, int LDU, ref double[] VT, int offset_vt, int LDVT, ref double[] WORK, int offset_work, int LWORK, ref int[] IWORK, int offset_iwork, ref int INFO) inline
Purpose
DGESDD computes the singular value decomposition (SVD) of a real M-by-N matrix A, optionally computing the left and right singular vectors. If singular vectors are desired, it uses a divide-and-conquer algorithm.
The SVD is written
A = U * SIGMA * transpose(V)
where SIGMA is an M-by-N matrix which is zero except for its min(m,n) diagonal elements, U is an M-by-M orthogonal matrix, and V is an N-by-N orthogonal matrix. The diagonal elements of SIGMA are the singular values of A; they are real and non-negative, and are returned in descending order. The first min(m,n) columns of U and V are the left and right singular vectors of A.
Note that the routine returns VT = V**T, not V.
The divide and conquer algorithm makes very mild assumptions about floating point arithmetic. It will work on machines with a guard digit in add/subtract, or on those binary machines without guard digits which subtract like the Cray X-MP, Cray Y-MP, Cray C-90, or Cray-2. It could conceivably fail on hexadecimal or decimal machines without guard digits, but we know of none.
/summary>
Parameters
JOBZ (input) CHARACTER*1 Specifies options for computing all or part of the matrix U: = 'A': all M columns of U and all N rows of V**T are returned in the arrays U and VT; = 'S': the first min(M,N) columns of U and the first min(M,N) rows of V**T are returned in the arrays U and VT; = 'O': If M .GE. N, the first N columns of U are overwritten on the array A and all rows of V**T are returned in the array VT; otherwise, all columns of U are returned in the array U and the first M rows of V**T are overwritten in the array A; = 'N': no columns of U or rows of V**T are computed. /param>
Parameters
M (input) INTEGER The number of rows of the input matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the input matrix A. N .GE. 0. /param>
Parameters
A = U * SIGMA * transpose(V) /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
S (output) DOUBLE PRECISION array, dimension (min(M,N)) The singular values of A, sorted so that S(i) .GE. S(i+1). /param>
Parameters
U (output) DOUBLE PRECISION array, dimension (LDU,UCOL) UCOL = M if JOBZ = 'A' or JOBZ = 'O' and M .LT. N; UCOL = min(M,N) if JOBZ = 'S'. If JOBZ = 'A' or JOBZ = 'O' and M .LT. N, U contains the M-by-M orthogonal matrix U; if JOBZ = 'S', U contains the first min(M,N) columns of U (the left singular vectors, stored columnwise); if JOBZ = 'O' and M .GE. N, or JOBZ = 'N', U is not referenced. /param>
Parameters
LDU (input) INTEGER The leading dimension of the array U. LDU .GE. 1; if JOBZ = 'S' or 'A' or JOBZ = 'O' and M .LT. N, LDU .GE. M. /param>
Parameters
VT (output) DOUBLE PRECISION array, dimension (LDVT,N) If JOBZ = 'A' or JOBZ = 'O' and M .GE. N, VT contains the N-by-N orthogonal matrix V**T; if JOBZ = 'S', VT contains the first min(M,N) rows of V**T (the right singular vectors, stored rowwise); if JOBZ = 'O' and M .LT. N, or JOBZ = 'N', VT is not referenced. /param>
Parameters
LDVT (input) INTEGER The leading dimension of the array VT. LDVT .GE. 1; if JOBZ = 'A' or JOBZ = 'O' and M .GE. N, LDVT .GE. N; if JOBZ = 'S', LDVT .GE. min(M,N). /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK; /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. 1. If JOBZ = 'N', LWORK .GE. 3*min(M,N) + max(max(M,N),7*min(M,N)). If JOBZ = 'O', LWORK .GE. 3*min(M,N)*min(M,N) + max(max(M,N),5*min(M,N)*min(M,N)+4*min(M,N)). If JOBZ = 'S' or 'A' LWORK .GE. 3*min(M,N)*min(M,N) + max(max(M,N),4*min(M,N)*min(M,N)+4*min(M,N)). For good performance, LWORK should generally be larger. If LWORK = -1 but other input arguments are legal, WORK(1) returns the optimal LWORK. /param>
Parameters
IWORK (workspace) INTEGER array, dimension (8*min(M,N)) /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. .GT. 0: DBDSDC did not converge, updating process failed. /param>
References DotNumerics.LinearAlgebra.CSLapack.DGESDD.DUM, DotNumerics.LinearAlgebra.CSLapack.DGESDD.IDUM, DotNumerics.LinearAlgebra.CSLapack.DGESDD.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASET.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELQF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANGE.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGLQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGQR.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGBR.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMBR.Run(), DotNumerics.LinearAlgebra.CSLapack.DBDSDC.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGESDD.ZERO.
Member Data Documentation
_dbdsdc
DBDSDC DotNumerics.LinearAlgebra.CSLapack.DGESDD._dbdsdc private
_dgebrd
DGEBRD DotNumerics.LinearAlgebra.CSLapack.DGESDD._dgebrd private
_dgelqf
DGELQF DotNumerics.LinearAlgebra.CSLapack.DGESDD._dgelqf private
_dgemm
DGEMM DotNumerics.LinearAlgebra.CSLapack.DGESDD._dgemm private
_dgeqrf
DGEQRF DotNumerics.LinearAlgebra.CSLapack.DGESDD._dgeqrf private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DGESDD._dlacpy private
_dlascl
DLASCL DotNumerics.LinearAlgebra.CSLapack.DGESDD._dlascl private
_dlaset
DLASET DotNumerics.LinearAlgebra.CSLapack.DGESDD._dlaset private
_dorgbr
DORGBR DotNumerics.LinearAlgebra.CSLapack.DGESDD._dorgbr private
_dorglq
DORGLQ DotNumerics.LinearAlgebra.CSLapack.DGESDD._dorglq private
_dorgqr
DORGQR DotNumerics.LinearAlgebra.CSLapack.DGESDD._dorgqr private
_dormbr
DORMBR DotNumerics.LinearAlgebra.CSLapack.DGESDD._dormbr private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGESDD._xerbla private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DGESDD._dlamch private
_dlange
DLANGE DotNumerics.LinearAlgebra.CSLapack.DGESDD._dlange private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DGESDD._ilaenv private
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DGESDD._lsame private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DGESDD.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGESDD.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run().
IDUM
int [] DotNumerics.LinearAlgebra.CSLapack.DGESDD.IDUM = new int[1] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run().
DUM
double [] DotNumerics.LinearAlgebra.CSLapack.DGESDD.DUM = new double[1] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgesdd.cs