Doc: IGLib EXTENDED: IGTest.TestWebReference.TempConvert Class Reference
IGTest.TestWebReference.TempConvert Class Reference
Public Member Functions
TempConvert ()
string FahrenheitToCelsius (string Fahrenheit)
void FahrenheitToCelsiusAsync (string Fahrenheit)
void FahrenheitToCelsiusAsync (string Fahrenheit, object userState)
string CelsiusToFahrenheit (string Celsius)
void CelsiusToFahrenheitAsync (string Celsius)
void CelsiusToFahrenheitAsync (string Celsius, object userState)
new void CancelAsync (object userState)
Properties
new string Url [get, set]
new bool UseDefaultCredentials [get, set]
Events
FahrenheitToCelsiusCompletedEventHandler FahrenheitToCelsiusCompleted
CelsiusToFahrenheitCompletedEventHandler CelsiusToFahrenheitCompleted
Private Member Functions
void OnFahrenheitToCelsiusOperationCompleted (object arg)
void OnCelsiusToFahrenheitOperationCompleted (object arg)
bool IsLocalFileSystemWebService (string url)
Private Attributes
System.Threading.SendOrPostCallback FahrenheitToCelsiusOperationCompleted
System.Threading.SendOrPostCallback CelsiusToFahrenheitOperationCompleted
bool useDefaultCredentialsSetExplicitly
Detailed Description
Constructor & Destructor Documentation
TempConvert()
IGTest.TestWebReference.TempConvert.TempConvert () inline
References IGTest.TestWebReference.TempConvert.IsLocalFileSystemWebService(), IGTest.TestWebReference.TempConvert.Url, and IGTest.TestWebReference.TempConvert.UseDefaultCredentials.
Member Function Documentation
FahrenheitToCelsius()
string IGTest.TestWebReference.TempConvert.FahrenheitToCelsius (string Fahrenheit) inline
FahrenheitToCelsiusAsync() [1/2]
void IGTest.TestWebReference.TempConvert.FahrenheitToCelsiusAsync (string Fahrenheit) inline
FahrenheitToCelsiusAsync() [2/2]
void IGTest.TestWebReference.TempConvert.FahrenheitToCelsiusAsync (string Fahrenheit, object userState) inline
References IGTest.TestWebReference.TempConvert.FahrenheitToCelsiusOperationCompleted, and IGTest.TestWebReference.TempConvert.OnFahrenheitToCelsiusOperationCompleted().
OnFahrenheitToCelsiusOperationCompleted()
void IGTest.TestWebReference.TempConvert.OnFahrenheitToCelsiusOperationCompleted (object arg) inline private
References IGTest.TestWebReference.TempConvert.FahrenheitToCelsiusCompleted.
Referenced by IGTest.TestWebReference.TempConvert.FahrenheitToCelsiusAsync().
CelsiusToFahrenheit()
string IGTest.TestWebReference.TempConvert.CelsiusToFahrenheit (string Celsius) inline
CelsiusToFahrenheitAsync() [1/2]
void IGTest.TestWebReference.TempConvert.CelsiusToFahrenheitAsync (string Celsius) inline
CelsiusToFahrenheitAsync() [2/2]
void IGTest.TestWebReference.TempConvert.CelsiusToFahrenheitAsync (string Celsius, object userState) inline
References IGTest.TestWebReference.TempConvert.CelsiusToFahrenheitOperationCompleted, and IGTest.TestWebReference.TempConvert.OnCelsiusToFahrenheitOperationCompleted().
OnCelsiusToFahrenheitOperationCompleted()
void IGTest.TestWebReference.TempConvert.OnCelsiusToFahrenheitOperationCompleted (object arg) inline private
References IGTest.TestWebReference.TempConvert.CelsiusToFahrenheitCompleted.
Referenced by IGTest.TestWebReference.TempConvert.CelsiusToFahrenheitAsync().
CancelAsync()
new void IGTest.TestWebReference.TempConvert.CancelAsync (object userState) inline
IsLocalFileSystemWebService()
bool IGTest.TestWebReference.TempConvert.IsLocalFileSystemWebService (string url) inline private
Referenced by IGTest.TestWebReference.TempConvert.TempConvert().
Member Data Documentation
FahrenheitToCelsiusOperationCompleted
System.Threading.SendOrPostCallback IGTest.TestWebReference.TempConvert.FahrenheitToCelsiusOperationCompleted private
Referenced by IGTest.TestWebReference.TempConvert.FahrenheitToCelsiusAsync().
CelsiusToFahrenheitOperationCompleted
System.Threading.SendOrPostCallback IGTest.TestWebReference.TempConvert.CelsiusToFahrenheitOperationCompleted private
Referenced by IGTest.TestWebReference.TempConvert.CelsiusToFahrenheitAsync().
useDefaultCredentialsSetExplicitly
bool IGTest.TestWebReference.TempConvert.useDefaultCredentialsSetExplicitly private
Property Documentation
Url
new string IGTest.TestWebReference.TempConvert.Url get set
Referenced by IGTest.TestWebReference.TempConvert.TempConvert(), and IGTest.ProgramIGTest.TestW3cWs().
UseDefaultCredentials
new bool IGTest.TestWebReference.TempConvert.UseDefaultCredentials get set
Referenced by IGTest.TestWebReference.TempConvert.TempConvert().
Event Documentation
FahrenheitToCelsiusCompleted
FahrenheitToCelsiusCompletedEventHandler IGTest.TestWebReference.TempConvert.FahrenheitToCelsiusCompleted
Referenced by IGTest.TestWebReference.TempConvert.OnFahrenheitToCelsiusOperationCompleted().
CelsiusToFahrenheitCompleted
CelsiusToFahrenheitCompletedEventHandler IGTest.TestWebReference.TempConvert.CelsiusToFahrenheitCompleted
Referenced by IGTest.TestWebReference.TempConvert.OnCelsiusToFahrenheitOperationCompleted().
The documentation for this class was generated from the following file:
igtest/tmp_prem/prlab/IGTest/Web References/TestWebReference/Reference.cs