Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DSWAP Class Reference
DotNumerics.LinearAlgebra.CSLapack.DSWAP Class Reference
Public Member Functions
DSWAP ()
void Run (int N, ref double[] DX, int offset_dx, int INCX, ref double[] DY, int offset_dy, int INCY)
Detailed Description
Purpose
interchanges two vectors. uses unrolled loops for increments equal one. jack dongarra, linpack, 3/11/78. modified 12/3/93, array(1) declarations changed to array(*) /summary>
Constructor & Destructor Documentation
DSWAP()
DotNumerics.LinearAlgebra.CSLapack.DSWAP.DSWAP () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DSWAP.Run (int N, ref double[] DX, int offset_dx, int INCX, ref double[] DY, int offset_dy, int INCY) inline
Purpose
interchanges two vectors. uses unrolled loops for increments equal one. jack dongarra, linpack, 3/11/78. modified 12/3/93, array(1) declarations changed to array(*) /summary>
References DotNumerics.FortranLibrary.FortranLib.Mod().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGBTF2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBAK.Run(), DotNumerics.LinearAlgebra.CSLapack.DGETF2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGETRI.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQPF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGBTRS.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQP2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGBTRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBAL.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQP3.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQPS.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASDQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEDC.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASY2.Run(), DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run(), and DotNumerics.LinearAlgebra.CSLapack.DBDSDC.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dswap.cs