Doc: IGLib EXTENDED: IG.Forms.WindowPositionerForm Class Reference
IG.Forms.WindowPositionerForm Class Reference
Windows form for testing window positioning./summary> $A Igor xx Oct09;
Public Member Functions
WindowPositionerForm ()
Constructs a new positioner form with undefined positioner, positioned window and master window.
WindowPositionerForm (Form positionedWindow, Form masterWindow)
Constructs a new positioner form with unspecified positioner and specified positioned window and master window.
WindowPositionerForm (Form positionedWindow)
Constructs a new positioner form with unspecified positioner and master window, and specified positioned window.
WindowPositionerForm (WindowPositioner positioner)
Constructs a new positioner form with the specified positioner and undefined positioned window and master window.
WindowPositionerForm (WindowPositioner positioner, Form positionedWindow)
Constructs a new positioner form with the specified positioner and positioned window, and undefined master window.
WindowPositionerForm (WindowPositioner positioner, Form positionedWindow, Form masterWindow)
Constructs a new positioner form with the specified positioner, positioned window and master window.
WindowPositionerForm ()
Constructs a new positioner form with undefined positioner, positioned window and master window.
WindowPositionerForm (Form positionedWindow, Form masterWindow)
Constructs a new positioner form with unspecified positioner and specified positioned window and master window.
WindowPositionerForm (Form positionedWindow)
Constructs a new positioner form with unspecified positioner and master window, and specified positioned window.
WindowPositionerForm (WindowPositioner positioner)
Constructs a new positioner form with the specified positioner and undefined positioned window and master window.
WindowPositionerForm (WindowPositioner positioner, Form positionedWindow)
Constructs a new positioner form with the specified positioner and positioned window, and undefined master window.
WindowPositionerForm (WindowPositioner positioner, Form positionedWindow, Form masterWindow)
Constructs a new positioner form with the specified positioner, positioned window and master window.
WindowPositionerForm ()
Constructs a new positioner form with undefined positioner, positioned window and master window.
WindowPositionerForm (Form positionedWindow, Form masterWindow)
Constructs a new positioner form with unspecified positioner and specified positioned window and master window.
WindowPositionerForm (Form positionedWindow)
Constructs a new positioner form with unspecified positioner and master window, and specified positioned window.
WindowPositionerForm (WindowPositioner positioner)
Constructs a new positioner form with the specified positioner and undefined positioned window and master window.
WindowPositionerForm (WindowPositioner positioner, Form positionedWindow)
Constructs a new positioner form with the specified positioner and positioned window, and undefined master window.
WindowPositionerForm (WindowPositioner positioner, Form positionedWindow, Form masterWindow)
Constructs a new positioner form with the specified positioner, positioned window and master window.
Public Member Functions inherited from IG.Forms.IClosableFromContainedForm
void Close ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
Form _masterWindow
WindowPositionerControl windowPositionerControl1 = null
Properties
string Title [get]
WindowPositionerControl PositionerControl [get]
Provides direct access to the embedded positioner control.
WindowPositioner Positioner [get, set]
Window positioner.
Form Window [get, set]
Window to be positioned.
Form MasterWindow [get, set]
Master window relative to which position is set.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
Detailed Description
Windows form for testing window positioning./summary> $A Igor xx Oct09;
Constructor & Destructor Documentation
WindowPositionerForm() [1/18]
IG.Forms.WindowPositionerForm.WindowPositionerForm () inline
Constructs a new positioner form with undefined positioner, positioned window and master window.
WindowPositionerForm() [2/18]
IG.Forms.WindowPositionerForm.WindowPositionerForm (Form positionedWindow, Form masterWindow) inline
Constructs a new positioner form with unspecified positioner and specified positioned window and master window.
Positioner is created automatically and initialized to default state.
Parameters
positionedWindow Window that is positioned.
masterWindow Master window.
WindowPositionerForm() [3/18]
IG.Forms.WindowPositionerForm.WindowPositionerForm (Form positionedWindow) inline
Constructs a new positioner form with unspecified positioner and master window, and specified positioned window.
Positioner is created automatically and initialized to default state.
Parameters
positionedWindow Window that is positioned.
WindowPositionerForm() [4/18]
IG.Forms.WindowPositionerForm.WindowPositionerForm (WindowPositioner positioner) inline
Constructs a new positioner form with the specified positioner and undefined positioned window and master window.
Parameters
positioner Positioner object that positions the window.
WindowPositionerForm() [5/18]
IG.Forms.WindowPositionerForm.WindowPositionerForm (WindowPositioner positioner, Form positionedWindow) inline
Constructs a new positioner form with the specified positioner and positioned window, and undefined master window.
Parameters
positioner Positioner object that positions the window.
positionedWindow Window that is positioned.
WindowPositionerForm() [6/18]
IG.Forms.WindowPositionerForm.WindowPositionerForm (WindowPositioner positioner, Form positionedWindow, Form masterWindow) inline
Constructs a new positioner form with the specified positioner, positioned window and master window.
Parameters
positioner Positioner object that positions the window.
positionedWindow Window that is positioned.
masterWindow Master window.
References IG.Forms.WindowPositionerForm.InitializeComponent(), IG.Forms.WindowPositionerForm.MasterWindow, IG.Forms.WindowPositionerForm.Positioner, IG.Forms.WindowPositionerForm.Title, and IG.Forms.WindowPositionerForm.Window.
WindowPositionerForm() [7/18]
IG.Forms.WindowPositionerForm.WindowPositionerForm () inline
Constructs a new positioner form with undefined positioner, positioned window and master window.
WindowPositionerForm() [8/18]
IG.Forms.WindowPositionerForm.WindowPositionerForm (Form positionedWindow, Form masterWindow) inline
Constructs a new positioner form with unspecified positioner and specified positioned window and master window.
Positioner is created automatically and initialized to default state.
Parameters
positionedWindow Window that is positioned.
masterWindow Master window.
WindowPositionerForm() [9/18]
IG.Forms.WindowPositionerForm.WindowPositionerForm (Form positionedWindow) inline
Constructs a new positioner form with unspecified positioner and master window, and specified positioned window.
Positioner is created automatically and initialized to default state.
Parameters
positionedWindow Window that is positioned.
WindowPositionerForm() [10/18]
IG.Forms.WindowPositionerForm.WindowPositionerForm (WindowPositioner positioner) inline
Constructs a new positioner form with the specified positioner and undefined positioned window and master window.
Parameters
positioner Positioner object that positions the window.
WindowPositionerForm() [11/18]
IG.Forms.WindowPositionerForm.WindowPositionerForm (WindowPositioner positioner, Form positionedWindow) inline
Constructs a new positioner form with the specified positioner and positioned window, and undefined master window.
Parameters
positioner Positioner object that positions the window.
positionedWindow Window that is positioned.
WindowPositionerForm() [12/18]
IG.Forms.WindowPositionerForm.WindowPositionerForm (WindowPositioner positioner, Form positionedWindow, Form masterWindow) inline
Constructs a new positioner form with the specified positioner, positioned window and master window.
Parameters
positioner Positioner object that positions the window.
positionedWindow Window that is positioned.
masterWindow Master window.
References IG.Forms.WindowPositionerForm.InitializeComponent(), IG.Forms.WindowPositionerForm.MasterWindow, IG.Forms.WindowPositionerForm.Positioner, IG.Forms.WindowPositionerForm.Title, and IG.Forms.WindowPositionerForm.Window.
WindowPositionerForm() [13/18]
IG.Forms.WindowPositionerForm.WindowPositionerForm () inline
Constructs a new positioner form with undefined positioner, positioned window and master window.
WindowPositionerForm() [14/18]
IG.Forms.WindowPositionerForm.WindowPositionerForm (Form positionedWindow, Form masterWindow) inline
Constructs a new positioner form with unspecified positioner and specified positioned window and master window.
Positioner is created automatically and initialized to default state.
Parameters
positionedWindow Window that is positioned.
masterWindow Master window.
WindowPositionerForm() [15/18]
IG.Forms.WindowPositionerForm.WindowPositionerForm (Form positionedWindow) inline
Constructs a new positioner form with unspecified positioner and master window, and specified positioned window.
Positioner is created automatically and initialized to default state.
Parameters
positionedWindow Window that is positioned.
WindowPositionerForm() [16/18]
IG.Forms.WindowPositionerForm.WindowPositionerForm (WindowPositioner positioner) inline
Constructs a new positioner form with the specified positioner and undefined positioned window and master window.
Parameters
positioner Positioner object that positions the window.
WindowPositionerForm() [17/18]
IG.Forms.WindowPositionerForm.WindowPositionerForm (WindowPositioner positioner, Form positionedWindow) inline
Constructs a new positioner form with the specified positioner and positioned window, and undefined master window.
Parameters
positioner Positioner object that positions the window.
positionedWindow Window that is positioned.
WindowPositionerForm() [18/18]
IG.Forms.WindowPositionerForm.WindowPositionerForm (WindowPositioner positioner, Form positionedWindow, Form masterWindow) inline
Constructs a new positioner form with the specified positioner, positioned window and master window.
Parameters
positioner Positioner object that positions the window.
positionedWindow Window that is positioned.
masterWindow Master window.
References IG.Forms.WindowPositionerForm.InitializeComponent(), IG.Forms.WindowPositionerForm.MasterWindow, IG.Forms.WindowPositionerForm.Positioner, IG.Forms.WindowPositionerForm.Title, and IG.Forms.WindowPositionerForm.Window.
Member Function Documentation
Dispose() [1/3]
override void IG.Forms.WindowPositionerForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.WindowPositionerForm.components.
InitializeComponent() [1/3]
void IG.Forms.WindowPositionerForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.WindowPositionerForm.windowPositionerControl1.
Referenced by IG.Forms.WindowPositionerForm.WindowPositionerForm().
Dispose() [2/3]
override void IG.Forms.WindowPositionerForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.WindowPositionerForm.components.
InitializeComponent() [2/3]
void IG.Forms.WindowPositionerForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.WindowPositionerForm.windowPositionerControl1.
Dispose() [3/3]
override void IG.Forms.WindowPositionerForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.WindowPositionerForm.components.
InitializeComponent() [3/3]
void IG.Forms.WindowPositionerForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.WindowPositionerForm.windowPositionerControl1.
Member Data Documentation
_masterWindow
Form IG.Forms.WindowPositionerForm._masterWindow protected
components
System ComponentModel IContainer IG.Forms.WindowPositionerForm.components = null private
Required designer variable.
Referenced by IG.Forms.WindowPositionerForm.Dispose().
windowPositionerControl1
WindowPositionerControl IG.Forms.WindowPositionerForm.windowPositionerControl1 = null protected
Referenced by IG.Forms.WindowPositionerForm.InitializeComponent().
Property Documentation
Title
string IG.Forms.WindowPositionerForm.Title get
Referenced by IG.Forms.WindowPositionerForm.WindowPositionerForm().
PositionerControl
WindowPositionerControl IG.Forms.WindowPositionerForm.PositionerControl get
Provides direct access to the embedded positioner control.
Positioner
WindowPositioner IG.Forms.WindowPositionerForm.Positioner get set
Window positioner.
Referenced by IG.Forms.WindowPositionerForm.WindowPositionerForm().
Window
Form IG.Forms.WindowPositionerForm.Window get set
Window to be positioned.
Referenced by IG.Forms.WindowPositionerForm.WindowPositionerForm().
MasterWindow
Form IG.Forms.WindowPositionerForm.MasterWindow get set
Master window relative to which position is set.
Referenced by IG.Forms.WindowPositionerForm.WindowPositionerForm().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/WindowPositioner/WindowPositionerForm.cs
iglib/igforms/Utilities/WindowPositioner/WindowPositionerForm.Designer.cs