Doc: IGLib EXTENDED: IG.Neural.Applications.AnnAppDemo Class Reference
IG.Neural.Applications.AnnAppDemo Class Reference
Form for parametric tests and other viewing operations performed on ANN models.
Public Member Functions
AnnAppDemo ()
AnnAppDemo (INeuralModel model)
Construct a new window for ANN based predictions, with the model specified.
AnnAppDemo (string neuralDirectoryPath)
Construct a new window for ANN based predictions, with the specified base directory of the model.
virtual new void InitLayout ()
Initializes the layout. Eventually, this specifies which tabs appear on the form and wich do not.
virtual void Initform ()
Initializes the form, including the layout by calling the InitLayout method.
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
void SetNeuralScriptShellPath (string path)
Sets the directory for
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
string _workingDirectory = Directory.GetCurrentDirectory()
string _neuralScriptShellPath = null
NeuralParametricDemoAboutWindow _aboutWindow
Properties
bool IsTabPageVisibleCommand [get, set]
Whether the "Command" tab is visible or not.
bool IsTabPageVisibleAbout [get, set]
Whether the "About" tab is visible or not.
bool IsTabPageVisibleParametric [get, set]
Whether the parametric test tab is visible or not.
bool IsTabPageVisibleParametricMultiple [get, set]
Whether the multiple curve parametric test tab is visible or not.
bool IsTabPageVisibleParametric2D [get, set]
Whether the 2D parametric test tab is visible or not.
bool IsTabPageVisibleTrain [get, set]
Whether the training tab is included or not.
bool IsTabPageVisibleData [get, set]
Whether the data tab is included or not.
bool IsTabPageVisibleSampling [get, set]
Whether the sampling tab is visible or not.
string WorkingDirectory [get, set]
Working directory of the outer form.
INeuralModel NeuralModel [get, protected set]
Neural network - based model.
string NeuralScriptShellPath [get, protected set]
Path of the working directory for the ANN-based approximation approximation scripts.
INeuralApproximator TrainedNetwork [get]
Traint artificial neural network.
InputOutputDataDefiniton NeuralDataDefinition [get]
Neural data definition.
NeuralParametricDemoAboutWindow AboutWindow [get]
Window that shows information about the software.
Properties inherited from IG.Neural.INeuralModelContainer
INeuralModel NeuralModel [get]
Artificial neural network - based model.
Private Member Functions
void NeuralParametricDemo_HelpEventHandlers (object sender, KeyEventArgs e)
void NeuralParametricDemo_KeyUp (object sender, KeyEventArgs e)
void tabControl_KeyUp (object sender, KeyEventArgs e)
void btnSavePrediction_Click (object sender, EventArgs e)
Saves image of the prediction control to a file that is chosen via a file dialog box.
void btnPrintPrediction_Click (object sender, EventArgs e)
Prints the image of the prediction control to a file that is chosen via a file dialog box.
void btnSaveParametricTest_Click (object sender, EventArgs e)
Saves image of the parametric test control to a file that is chosen via a file dialog box.
void btnPrintParametricTest_Click (object sender, EventArgs e)
Prints the image of the parametric test control to a file that is chosen via a file dialog box.
void btnSwitchAbout_Click (object sender, EventArgs e)
Switches the About tab on or off.
void btnSwitch2dParametric_Click (object sender, EventArgs e)
Switches the 2D parametric tests tab on or off.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
INeuralModel _neuralModel
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.TextBox tbInfoLine
System.Windows.Forms.TabControl tabControlAnnApp
System.Windows.Forms.TabPage tpPrediction
System.Windows.Forms.TabPage tpParmetric
Forms.NeuralPredictionControl neuralPredictionControl1
NeuralParametricTest neuralParametricTest1
System.Windows.Forms.Button btnSavePrediction
System.Windows.Forms.Button btnPrintPrediction
System.Windows.Forms.Button btnSaveParametricTest
System.Windows.Forms.Button btnPrintParametricTest
System.Windows.Forms.TabPage tpAbout
System.Windows.Forms.TabPage tpCommand
System.Windows.Forms.Label lblTitleCommand
System.Windows.Forms.Button btnSwitch2dParametric
System.Windows.Forms.Button btnSwitchAbout
System.Windows.Forms.TabPage tpParametric2d
NeuralParametricTest2d neuralParametricTest2d1
System.Windows.Forms.TabPage tpTrain
System.Windows.Forms.TabPage tpData
NeuralTrainingControl neuralTrainingControl1
NeuralDataControl neuralDataControl1
System.Windows.Forms.TabPage tpParametricMultiple
System.Windows.Forms.TabPage tpSampling
NeuralParametricTestMultiple neuralParametricTestMultiple1
NeuralSamplingControl neuralSamplingControl1
NeuralAboutControlToDelete abautNeurAppPnl
Detailed Description
Form for parametric tests and other viewing operations performed on ANN models.
$A Igor Apr13 Jun13;
Constructor & Destructor Documentation
AnnAppDemo() [1/3]
IG.Neural.Applications.AnnAppDemo.AnnAppDemo () inline
References IG.Neural.Applications.AnnAppDemo.Initform(), and IG.Neural.Applications.AnnAppDemo.InitializeComponent().
AnnAppDemo() [2/3]
IG.Neural.Applications.AnnAppDemo.AnnAppDemo (INeuralModel model) inline
Construct a new window for ANN based predictions, with the model specified.
Parameters
model ANN - base model, contains input and output data definitions and
References IG.Neural.Applications.AnnAppDemo.NeuralModel.
AnnAppDemo() [3/3]
IG.Neural.Applications.AnnAppDemo.AnnAppDemo (string neuralDirectoryPath) inline
Construct a new window for ANN based predictions, with the specified base directory of the model.
Parameters
neuralDirectoryPath Directory containing all data for the ANN-based model.
References IG.Neural.Applications.AnnAppDemo.NeuralScriptShellPath, and IG.Neural.Applications.AnnAppDemo.WorkingDirectory.
Member Function Documentation
InitLayout()
virtual new void IG.Neural.Applications.AnnAppDemo.InitLayout () inline virtual
Initializes the layout. Eventually, this specifies which tabs appear on the form and wich do not.
Constructors call the Initform method that call this method.
This should be overridden in derived classes, and overridden method should not call the base method.
Reimplemented in IG.Neural.Applications.AnnAppDemoExperimental.
References IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleAbout, IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleCommand, IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleData, IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleParametric2D, IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleParametricMultiple, IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleSampling, and IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleTrain.
Referenced by IG.Neural.Applications.AnnAppDemo.Initform().
Initform()
virtual void IG.Neural.Applications.AnnAppDemo.Initform () inline virtual
Initializes the form, including the layout by calling the InitLayout method.
This method is called in constructors.
This might be overridden in derived classes, but usually this is not necessary. The overridden methods should call this method from the base class.
Reimplemented in IG.Neural.Applications.AnnAppDemoExperimental.
References IG.Neural.Applications.AnnAppDemo.InitLayout().
Referenced by IG.Neural.Applications.AnnAppDemo.AnnAppDemo().
SetNeuralModel()
void IG.Neural.Applications.AnnAppDemo.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
Implements IG.Neural.INeuralModelContainer.
References IG.Neural.Applications.AnnAppDemo.NeuralModel.
SetNeuralScriptShellPath()
void IG.Neural.Applications.AnnAppDemo.SetNeuralScriptShellPath (string path) inline
Sets the directory for
Parameters
path
References IG.Neural.Applications.AnnAppDemo.NeuralScriptShellPath.
NeuralParametricDemo_HelpEventHandlers()
void IG.Neural.Applications.AnnAppDemo.NeuralParametricDemo_HelpEventHandlers (object sender, KeyEventArgs e) inline private
References IG.Neural.Applications.AnnAppDemo.AboutWindow, and IG.Neural.Applications.NeuralParametricDemoAboutWindow.ShowHelp().
Referenced by IG.Neural.Applications.AnnAppDemo.NeuralParametricDemo_KeyUp(), and IG.Neural.Applications.AnnAppDemo.tabControl_KeyUp().
NeuralParametricDemo_KeyUp()
void IG.Neural.Applications.AnnAppDemo.NeuralParametricDemo_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Neural.Applications.AnnAppDemo.NeuralParametricDemo_HelpEventHandlers().
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
tabControl_KeyUp()
void IG.Neural.Applications.AnnAppDemo.tabControl_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Neural.Applications.AnnAppDemo.NeuralParametricDemo_HelpEventHandlers().
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
btnSavePrediction_Click()
void IG.Neural.Applications.AnnAppDemo.btnSavePrediction_Click (object sender, EventArgs e) inline private
Saves image of the prediction control to a file that is chosen via a file dialog box.
References IG.Neural.Applications.AnnAppDemo.neuralPredictionControl1, IG.Forms.UtilForms.SaveControlFileDialogJpeg(), and IG.Neural.Applications.AnnAppDemo.WorkingDirectory.
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
btnPrintPrediction_Click()
void IG.Neural.Applications.AnnAppDemo.btnPrintPrediction_Click (object sender, EventArgs e) inline private
Prints the image of the prediction control to a file that is chosen via a file dialog box.
References IG.Neural.Applications.AnnAppDemo.neuralPredictionControl1, and IG.Forms.UtilForms.PrintControl().
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
btnSaveParametricTest_Click()
void IG.Neural.Applications.AnnAppDemo.btnSaveParametricTest_Click (object sender, EventArgs e) inline private
Saves image of the parametric test control to a file that is chosen via a file dialog box.
References IG.Neural.Applications.AnnAppDemo.neuralParametricTest1, IG.Forms.UtilForms.SaveControlFileDialogJpeg(), and IG.Neural.Applications.AnnAppDemo.WorkingDirectory.
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
btnPrintParametricTest_Click()
void IG.Neural.Applications.AnnAppDemo.btnPrintParametricTest_Click (object sender, EventArgs e) inline private
Prints the image of the parametric test control to a file that is chosen via a file dialog box.
References IG.Neural.Applications.AnnAppDemo.neuralParametricTest1, and IG.Forms.UtilForms.PrintControl().
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
btnSwitchAbout_Click()
void IG.Neural.Applications.AnnAppDemo.btnSwitchAbout_Click (object sender, EventArgs e) inline private
Switches the About tab on or off.
References IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleAbout.
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
btnSwitch2dParametric_Click()
void IG.Neural.Applications.AnnAppDemo.btnSwitch2dParametric_Click (object sender, EventArgs e) inline private
Switches the 2D parametric tests tab on or off.
References IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleParametric2D.
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
Dispose()
override void IG.Neural.Applications.AnnAppDemo.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Applications.AnnAppDemo.components.
InitializeComponent()
void IG.Neural.Applications.AnnAppDemo.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Applications.AnnAppDemo.abautNeurAppPnl, IG.Neural.Applications.AnnAppDemo.btnPrintParametricTest, IG.Neural.Applications.AnnAppDemo.btnPrintParametricTest_Click(), IG.Neural.Applications.AnnAppDemo.btnPrintPrediction, IG.Neural.Applications.AnnAppDemo.btnPrintPrediction_Click(), IG.Neural.Applications.AnnAppDemo.btnSaveParametricTest, IG.Neural.Applications.AnnAppDemo.btnSaveParametricTest_Click(), IG.Neural.Applications.AnnAppDemo.btnSavePrediction, IG.Neural.Applications.AnnAppDemo.btnSavePrediction_Click(), IG.Neural.Applications.AnnAppDemo.btnSwitch2dParametric, IG.Neural.Applications.AnnAppDemo.btnSwitch2dParametric_Click(), IG.Neural.Applications.AnnAppDemo.btnSwitchAbout, IG.Neural.Applications.AnnAppDemo.btnSwitchAbout_Click(), IG.Neural.Applications.AnnAppDemo.lblTitleCommand, IG.Neural.Applications.AnnAppDemo.neuralDataControl1, IG.Neural.Applications.AnnAppDemo.NeuralParametricDemo_KeyUp(), IG.Neural.Applications.AnnAppDemo.neuralParametricTest1, IG.Neural.Applications.AnnAppDemo.neuralParametricTest2d1, IG.Neural.Applications.AnnAppDemo.neuralParametricTestMultiple1, IG.Neural.Applications.AnnAppDemo.neuralPredictionControl1, IG.Neural.Applications.AnnAppDemo.neuralSamplingControl1, IG.Neural.Applications.AnnAppDemo.neuralTrainingControl1, IG.Neural.Applications.AnnAppDemo.tabControl_KeyUp(), IG.Neural.Applications.AnnAppDemo.tabControlAnnApp, IG.Neural.Applications.AnnAppDemo.tbInfoLine, IG.Neural.Applications.AnnAppDemo.tpAbout, IG.Neural.Applications.AnnAppDemo.tpCommand, IG.Neural.Applications.AnnAppDemo.tpData, IG.Neural.Applications.AnnAppDemo.tpParametric2d, IG.Neural.Applications.AnnAppDemo.tpParametricMultiple, IG.Neural.Applications.AnnAppDemo.tpParmetric, IG.Neural.Applications.AnnAppDemo.tpPrediction, IG.Neural.Applications.AnnAppDemo.tpSampling, and IG.Neural.Applications.AnnAppDemo.tpTrain.
Referenced by IG.Neural.Applications.AnnAppDemo.AnnAppDemo().
Member Data Documentation
_workingDirectory
string IG.Neural.Applications.AnnAppDemo._workingDirectory = Directory.GetCurrentDirectory() protected
_neuralModel
INeuralModel IG.Neural.Applications.AnnAppDemo._neuralModel private
_neuralScriptShellPath
string IG.Neural.Applications.AnnAppDemo._neuralScriptShellPath = null protected
_aboutWindow
NeuralParametricDemoAboutWindow IG.Neural.Applications.AnnAppDemo._aboutWindow protected
components
System.ComponentModel.IContainer IG.Neural.Applications.AnnAppDemo.components = null private
Required designer variable.
Referenced by IG.Neural.Applications.AnnAppDemo.Dispose().
tbInfoLine
System.Windows.Forms.TextBox IG.Neural.Applications.AnnAppDemo.tbInfoLine private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
tabControlAnnApp
System.Windows.Forms.TabControl IG.Neural.Applications.AnnAppDemo.tabControlAnnApp private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
tpPrediction
System.Windows.Forms.TabPage IG.Neural.Applications.AnnAppDemo.tpPrediction private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
tpParmetric
System.Windows.Forms.TabPage IG.Neural.Applications.AnnAppDemo.tpParmetric private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
neuralPredictionControl1
Forms.NeuralPredictionControl IG.Neural.Applications.AnnAppDemo.neuralPredictionControl1 private
Referenced by IG.Neural.Applications.AnnAppDemo.btnPrintPrediction_Click(), IG.Neural.Applications.AnnAppDemo.btnSavePrediction_Click(), and IG.Neural.Applications.AnnAppDemo.InitializeComponent().
neuralParametricTest1
NeuralParametricTest IG.Neural.Applications.AnnAppDemo.neuralParametricTest1 private
Referenced by IG.Neural.Applications.AnnAppDemo.btnPrintParametricTest_Click(), IG.Neural.Applications.AnnAppDemo.btnSaveParametricTest_Click(), and IG.Neural.Applications.AnnAppDemo.InitializeComponent().
btnSavePrediction
System.Windows.Forms.Button IG.Neural.Applications.AnnAppDemo.btnSavePrediction private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
btnPrintPrediction
System.Windows.Forms.Button IG.Neural.Applications.AnnAppDemo.btnPrintPrediction private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
btnSaveParametricTest
System.Windows.Forms.Button IG.Neural.Applications.AnnAppDemo.btnSaveParametricTest private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
btnPrintParametricTest
System.Windows.Forms.Button IG.Neural.Applications.AnnAppDemo.btnPrintParametricTest private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
tpAbout
System.Windows.Forms.TabPage IG.Neural.Applications.AnnAppDemo.tpAbout private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
tpCommand
System.Windows.Forms.TabPage IG.Neural.Applications.AnnAppDemo.tpCommand private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
lblTitleCommand
System.Windows.Forms.Label IG.Neural.Applications.AnnAppDemo.lblTitleCommand private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
btnSwitch2dParametric
System.Windows.Forms.Button IG.Neural.Applications.AnnAppDemo.btnSwitch2dParametric private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
btnSwitchAbout
System.Windows.Forms.Button IG.Neural.Applications.AnnAppDemo.btnSwitchAbout private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
tpParametric2d
System.Windows.Forms.TabPage IG.Neural.Applications.AnnAppDemo.tpParametric2d private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
neuralParametricTest2d1
NeuralParametricTest2d IG.Neural.Applications.AnnAppDemo.neuralParametricTest2d1 private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
tpTrain
System.Windows.Forms.TabPage IG.Neural.Applications.AnnAppDemo.tpTrain private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
tpData
System.Windows.Forms.TabPage IG.Neural.Applications.AnnAppDemo.tpData private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
neuralTrainingControl1
NeuralTrainingControl IG.Neural.Applications.AnnAppDemo.neuralTrainingControl1 private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
neuralDataControl1
NeuralDataControl IG.Neural.Applications.AnnAppDemo.neuralDataControl1 private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
tpParametricMultiple
System.Windows.Forms.TabPage IG.Neural.Applications.AnnAppDemo.tpParametricMultiple private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
tpSampling
System.Windows.Forms.TabPage IG.Neural.Applications.AnnAppDemo.tpSampling private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
neuralParametricTestMultiple1
NeuralParametricTestMultiple IG.Neural.Applications.AnnAppDemo.neuralParametricTestMultiple1 private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
neuralSamplingControl1
NeuralSamplingControl IG.Neural.Applications.AnnAppDemo.neuralSamplingControl1 private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
abautNeurAppPnl
NeuralAboutControlToDelete IG.Neural.Applications.AnnAppDemo.abautNeurAppPnl private
Referenced by IG.Neural.Applications.AnnAppDemo.InitializeComponent().
Property Documentation
IsTabPageVisibleCommand
bool IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleCommand get set
Whether the "Command" tab is visible or not.
Referenced by IG.Neural.Applications.AnnAppDemo.InitLayout().
IsTabPageVisibleAbout
bool IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleAbout get set
Whether the "About" tab is visible or not.
Referenced by IG.Neural.Applications.AnnAppDemo.btnSwitchAbout_Click(), and IG.Neural.Applications.AnnAppDemo.InitLayout().
IsTabPageVisibleParametric
bool IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleParametric get set
Whether the parametric test tab is visible or not.
Referenced by IG.Neural.Applications.ProgramAnnApp.Main().
IsTabPageVisibleParametricMultiple
bool IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleParametricMultiple get set
Whether the multiple curve parametric test tab is visible or not.
Referenced by IG.Neural.Applications.AnnAppDemo.InitLayout().
IsTabPageVisibleParametric2D
bool IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleParametric2D get set
Whether the 2D parametric test tab is visible or not.
Referenced by IG.Neural.Applications.AnnAppDemo.btnSwitch2dParametric_Click(), and IG.Neural.Applications.AnnAppDemo.InitLayout().
IsTabPageVisibleTrain
bool IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleTrain get set
Whether the training tab is included or not.
Referenced by IG.Neural.Applications.AnnAppDemo.InitLayout(), and IG.Neural.Applications.ProgramAnnApp.Main().
IsTabPageVisibleData
bool IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleData get set
Whether the data tab is included or not.
Referenced by IG.Neural.Applications.AnnAppDemo.InitLayout(), and IG.Neural.Applications.ProgramAnnApp.Main().
IsTabPageVisibleSampling
bool IG.Neural.Applications.AnnAppDemo.IsTabPageVisibleSampling get set
Whether the sampling tab is visible or not.
This tab performs sampling on the basis of an analytical function.
Referenced by IG.Neural.Applications.AnnAppDemo.InitLayout(), and IG.Neural.Applications.ProgramAnnApp.Main().
WorkingDirectory
string IG.Neural.Applications.AnnAppDemo.WorkingDirectory get set
Working directory of the outer form.
Referenced by IG.Neural.Applications.AnnAppDemo.AnnAppDemo(), IG.Neural.Applications.AnnAppDemo.btnSaveParametricTest_Click(), and IG.Neural.Applications.AnnAppDemo.btnSavePrediction_Click().
NeuralModel
INeuralModel IG.Neural.Applications.AnnAppDemo.NeuralModel get protected set
Neural network - based model.
Contains data definition and trained neural network approximator.
Referenced by IG.Neural.Applications.AnnAppDemo.AnnAppDemo(), and IG.Neural.Applications.AnnAppDemo.SetNeuralModel().
NeuralScriptShellPath
string IG.Neural.Applications.AnnAppDemo.NeuralScriptShellPath get protected set
Path of the working directory for the ANN-based approximation approximation scripts.
Referenced by IG.Neural.Applications.AnnAppDemo.AnnAppDemo(), and IG.Neural.Applications.AnnAppDemo.SetNeuralScriptShellPath().
TrainedNetwork
INeuralApproximator IG.Neural.Applications.AnnAppDemo.TrainedNetwork get
Traint artificial neural network.
NeuralDataDefinition
InputOutputDataDefiniton IG.Neural.Applications.AnnAppDemo.NeuralDataDefinition get
Neural data definition.
AboutWindow
NeuralParametricDemoAboutWindow IG.Neural.Applications.AnnAppDemo.AboutWindow get
Window that shows information about the software.
Help is also accessible through that window.
Referenced by IG.Neural.Applications.AnnAppDemo.NeuralParametricDemo_HelpEventHandlers().
The documentation for this class was generated from the following files:
shelldev/extensions/ExtAppAnnApp/ResponseForms/ResponseFormsApplications/AnnAppDemo.cs
shelldev/extensions/ExtAppAnnApp/ResponseForms/ResponseFormsApplications/AnnAppDemo.Designer.cs