Doc: IGLib EXTENDED: NUnit.Framework.Assertions.AssertFailTests Class Reference
NUnit.Framework.Assertions.AssertFailTests Class Reference
Public Member Functions
void ThrowsAssertionException ()
void ThrowsAssertionException_MessageSpecified ()
void ThrowsAssertionExceptionWithMessage ()
void ThrowsAssertionExceptionWithMessageAndArgs ()
void AssertFailWorks ()
void AssertFailWorksWithMessage ()
void AssertFailWorksWithMessageAndArgs ()
Member Function Documentation
ThrowsAssertionException()
void NUnit.Framework.Assertions.AssertFailTests.ThrowsAssertionException () inline
References NUnit.Framework.Assert.Fail(), NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
ThrowsAssertionException_MessageSpecified()
void NUnit.Framework.Assertions.AssertFailTests.ThrowsAssertionException_MessageSpecified () inline
References NUnit.Framework.Assert.Fail(), NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
ThrowsAssertionExceptionWithMessage()
void NUnit.Framework.Assertions.AssertFailTests.ThrowsAssertionExceptionWithMessage () inline
References NUnit.Framework.Assert.Fail(), NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
ThrowsAssertionExceptionWithMessageAndArgs()
void NUnit.Framework.Assertions.AssertFailTests.ThrowsAssertionExceptionWithMessageAndArgs () inline
References NUnit.Framework.Assert.Fail(), NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
AssertFailWorks()
void NUnit.Framework.Assertions.AssertFailTests.AssertFailWorks () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.Failure, NUnit.Framework.Interfaces.ITestResult.ResultState, and NUnit.TestUtilities.TestBuilder.RunTestCase().
AssertFailWorksWithMessage()
void NUnit.Framework.Assertions.AssertFailTests.AssertFailWorksWithMessage () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.Failure, NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, and NUnit.TestUtilities.TestBuilder.RunTestCase().
AssertFailWorksWithMessageAndArgs()
void NUnit.Framework.Assertions.AssertFailTests.AssertFailWorksWithMessageAndArgs () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.ResultState.Failure, NUnit.Framework.Interfaces.ITestResult.Message, NUnit.Framework.Interfaces.ITestResult.ResultState, and NUnit.TestUtilities.TestBuilder.RunTestCase().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/AssertFailTests.cs