Doc: IGLib EXTENDED: AForge.MachineLearning.TabuSearchExploration Class Reference
AForge.MachineLearning.TabuSearchExploration Class Reference
Tabu search exploration policy.
Public Member Functions
TabuSearchExploration (int actions, IExplorationPolicy basePolicy)
Initializes a new instance of the TabuSearchExploration class.
int ChooseAction (double[] actionEstimates)
Choose an action.
void ResetTabuList ()
Reset tabu list.
void SetTabuAction (int action, int tabuTime)
Set tabu action.
Properties
IExplorationPolicy BasePolicy [get, set]
Base exploration policy.
Private Attributes
int actions
int[] tabuActions = null
IExplorationPolicy basePolicy
Detailed Description
Tabu search exploration policy.
The class implements simple tabu search exploration policy, allowing to set certain actions as tabu for a specified amount of iterations. The actual exploration and choosing from non-tabu actions is done by base exploration policy.
See also
BoltzmannExploration, EpsilonGreedyExploration, RouletteWheelExploration
Constructor & Destructor Documentation
TabuSearchExploration()
AForge.MachineLearning.TabuSearchExploration.TabuSearchExploration (int actions, IExplorationPolicy basePolicy) inline
Initializes a new instance of the TabuSearchExploration class.
Parameters
actions Total actions count.
basePolicy Base exploration policy.
References AForge.MachineLearning.TabuSearchExploration.actions, AForge.MachineLearning.TabuSearchExploration.basePolicy, and AForge.MachineLearning.TabuSearchExploration.tabuActions.
Member Function Documentation
ChooseAction()
int AForge.MachineLearning.TabuSearchExploration.ChooseAction (double[] actionEstimates) inline
Choose an action.
Parameters
actionEstimates Action estimates.
Returns
Returns selected action.
The method chooses an action depending on the provided estimates. The estimates can be any sort of estimate, which values usefulness of the action (expected summary reward, discounted reward, etc). The action is choosed from non-tabu actions only.
Implements AForge.MachineLearning.IExplorationPolicy.
References AForge.MachineLearning.TabuSearchExploration.actions, AForge.MachineLearning.TabuSearchExploration.basePolicy, AForge.MachineLearning.IExplorationPolicy.ChooseAction(), and AForge.MachineLearning.TabuSearchExploration.tabuActions.
ResetTabuList()
void AForge.MachineLearning.TabuSearchExploration.ResetTabuList () inline
Reset tabu list.
Clears tabu list making all actions allowed.
References AForge.MachineLearning.TabuSearchExploration.actions, and AForge.MachineLearning.TabuSearchExploration.tabuActions.
Referenced by Animat.MainForm.QLearningThread(), Animat.MainForm.SarsaThread(), and Animat.MainForm.ShowSolutionThread().
SetTabuAction()
void AForge.MachineLearning.TabuSearchExploration.SetTabuAction (int action, int tabuTime) inline
Set tabu action.
Parameters
action Action to set tabu for.
tabuTime Tabu time in iterations.
References AForge.MachineLearning.TabuSearchExploration.tabuActions.
Referenced by Animat.MainForm.QLearningThread(), and Animat.MainForm.SarsaThread().
Member Data Documentation
actions
int AForge.MachineLearning.TabuSearchExploration.actions private
Referenced by AForge.MachineLearning.TabuSearchExploration.ChooseAction(), AForge.MachineLearning.TabuSearchExploration.ResetTabuList(), and AForge.MachineLearning.TabuSearchExploration.TabuSearchExploration().
tabuActions
int [] AForge.MachineLearning.TabuSearchExploration.tabuActions = null private
Referenced by AForge.MachineLearning.TabuSearchExploration.ChooseAction(), AForge.MachineLearning.TabuSearchExploration.ResetTabuList(), AForge.MachineLearning.TabuSearchExploration.SetTabuAction(), and AForge.MachineLearning.TabuSearchExploration.TabuSearchExploration().
basePolicy
IExplorationPolicy AForge.MachineLearning.TabuSearchExploration.basePolicy private
Referenced by AForge.MachineLearning.TabuSearchExploration.ChooseAction(), and AForge.MachineLearning.TabuSearchExploration.TabuSearchExploration().
Property Documentation
BasePolicy
IExplorationPolicy AForge.MachineLearning.TabuSearchExploration.BasePolicy get set
Base exploration policy.
Base exploration policy is the policy, which is used to choose from non-tabu actions.
Referenced by Animat.MainForm.QLearningThread(), Animat.MainForm.SarsaThread(), and Animat.MainForm.ShowSolutionThread().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/MachineLearning/Exploration Policy/TabuSearchExploration.cs