Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLASD0 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLASD0 Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLASD0 (DLASD1 dlasd1, DLASDQ dlasdq, DLASDT dlasdt, XERBLA xerbla)
DLASD0 ()
void Run (int N, int SQRE, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] U, int offset_u, int LDU, ref double[] VT, int offset_vt, int LDVT, int SMLSIZ, ref int[] IWORK, int offset_iwork, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
DLASD1 _dlasd1
DLASDQ _dlasdq
DLASDT _dlasdt
XERBLA _xerbla
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
Using a divide and conquer approach, DLASD0 computes the singular value decomposition (SVD) of a real upper bidiagonal N-by-M matrix B with diagonal D and offdiagonal E, where M = N + SQRE. The algorithm computes orthogonal matrices U and VT such that B = U * S * VT. The singular values S are overwritten on D.
A related subroutine, DLASDA, computes only the singular values, and optionally, the singular vectors in compact form.
/summary>
Constructor & Destructor Documentation
DLASD0() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLASD0.DLASD0 (DLASD1 dlasd1, DLASDQ dlasdq, DLASDT dlasdt, XERBLA xerbla) inline
DLASD0() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLASD0.DLASD0 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLASD0.Run (int N, int SQRE, ref double[] D, int offset_d, ref double[] E, int offset_e, ref double[] U, int offset_u, int LDU, ref double[] VT, int offset_vt, int LDVT, int SMLSIZ, ref int[] IWORK, int offset_iwork, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
Using a divide and conquer approach, DLASD0 computes the singular value decomposition (SVD) of a real upper bidiagonal N-by-M matrix B with diagonal D and offdiagonal E, where M = N + SQRE. The algorithm computes orthogonal matrices U and VT such that B = U * S * VT. The singular values S are overwritten on D.
A related subroutine, DLASDA, computes only the singular values, and optionally, the singular vectors in compact form.
/summary>
Parameters
N (input) INTEGER On entry, the row dimension of the upper bidiagonal matrix. This is also the dimension of the main diagonal array D. /param>
Parameters
SQRE (input) INTEGER Specifies the column dimension of the bidiagonal matrix. = 0: The bidiagonal matrix has column dimension M = N; = 1: The bidiagonal matrix has column dimension M = N+1; /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension (N) On entry D contains the main diagonal of the bidiagonal matrix. On exit D, if INFO = 0, contains its singular values. /param>
Parameters
E (input) DOUBLE PRECISION array, dimension (M-1) Contains the subdiagonal entries of the bidiagonal matrix. On exit, E has been destroyed. /param>
Parameters
U (output) DOUBLE PRECISION array, dimension at least (LDQ, N) On exit, U contains the left singular vectors. /param>
Parameters
LDU (input) INTEGER On entry, leading dimension of U. /param>
Parameters
VT (output) DOUBLE PRECISION array, dimension at least (LDVT, M) On exit, VT' contains the right singular vectors. /param>
Parameters
LDVT (input) INTEGER On entry, leading dimension of VT. /param>
Parameters
SMLSIZ (input) INTEGER On entry, maximum size of the subproblems at the bottom of the computation tree. /param>
Parameters
IWORK (workspace) INTEGER work array. Dimension must be at least (8 * N) /param>
Parameters
WORK (workspace) DOUBLE PRECISION work array. Dimension must be at least (3 * M**2 + 2 * M) /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. .GT. 0: if INFO = 1, an singular value did not converge /param>
References DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASDT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASDQ.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLASD1.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DBDSDC.Run().
Member Data Documentation
_dlasd1
DLASD1 DotNumerics.LinearAlgebra.CSLapack.DLASD0._dlasd1 private
_dlasdq
DLASDQ DotNumerics.LinearAlgebra.CSLapack.DLASD0._dlasdq private
_dlasdt
DLASDT DotNumerics.LinearAlgebra.CSLapack.DLASD0._dlasdt private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLASD0._xerbla private
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlasd0.cs