Doc: IGLib EXTENDED: IG.Script._02LPAttenuation Class Reference
IG.Script._02LPAttenuation Class Reference
Solves a simple LP program using the simplex algorithm.
Static Public Member Functions
static void Run (string[] arguments)
Static Private Member Functions
static double attXL (int k)
static double attXD (int k)
static double attYZ (int j)
static double attYS (int j)
Static Private Attributes
static double attCoef = 0.0
static double unitLength = 1
Detailed Description
Solves a simple LP program using the simplex algorithm.
Member Function Documentation
attXL()
static double IG.Script._02LPAttenuation.attXL (int k) inline static private
References IG.Script._02LPAttenuation.attCoef, and IG.Script._02LPAttenuation.unitLength.
Referenced by IG.Script._02LPAttenuation.Run().
attXD()
static double IG.Script._02LPAttenuation.attXD (int k) inline static private
References IG.Script._02LPAttenuation.attCoef, and IG.Script._02LPAttenuation.unitLength.
Referenced by IG.Script._02LPAttenuation.Run().
attYZ()
static double IG.Script._02LPAttenuation.attYZ (int j) inline static private
References IG.Script._02LPAttenuation.attCoef, and IG.Script._02LPAttenuation.unitLength.
Referenced by IG.Script._02LPAttenuation.Run().
attYS()
static double IG.Script._02LPAttenuation.attYS (int j) inline static private
References IG.Script._02LPAttenuation.attCoef, and IG.Script._02LPAttenuation.unitLength.
Referenced by IG.Script._02LPAttenuation.Run().
Run()
static void IG.Script._02LPAttenuation.Run (string[] arguments) inline static
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Script._02LPAttenuation.attXD(), IG.Script._02LPAttenuation.attXL(), IG.Script._02LPAttenuation.attYS(), IG.Script._02LPAttenuation.attYZ(), IG.Gr.PlotZedGraphBase.LegendString, IG.Gr.PlotZedgraphCurve.LinesVisible, IG.MPetekLib.Algorithms.Plotting.PlotHQ.Plotter, IG.Gr.PlotZedgraphCurve.PointColor, IG.Gr.PlotZedgraphCurve.PointSize, IG.Gr.PlotZedgraphCurve.PointsVisible, IG.MPetekLib.Algorithms.Plotting.PlotHQ.ShowPlot(), IG.Gr.PlotterZedGraph.Title, IG.Gr.PlotterZedGraph.Window, IG.Gr.PlotterZedGraph.XAxisScaleFont, and IG.Gr.PlotterZedGraph.YAxisScaleFont.
Referenced by IG.Script.AppMarkoPetekExt.App02LPAttenuation().
Member Data Documentation
attCoef
double IG.Script._02LPAttenuation.attCoef = 0.0 static private
Referenced by IG.Script._02LPAttenuation.attXD(), IG.Script._02LPAttenuation.attXL(), IG.Script._02LPAttenuation.attYS(), and IG.Script._02LPAttenuation.attYZ().
unitLength
double IG.Script._02LPAttenuation.unitLength = 1 static private
Referenced by IG.Script._02LPAttenuation.attXD(), IG.Script._02LPAttenuation.attXL(), IG.Script._02LPAttenuation.attYS(), and IG.Script._02LPAttenuation.attYZ().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/extended/Guest_Marko_Petek_LibExt/application/scripts/02LPAttenuation.cs