Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.LSAME Class Reference
DotNumerics.LinearAlgebra.CSLapack.LSAME Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
LSAME ()
bool Run (string CA, string CB)
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
LSAME returns .TRUE. if CA is the same letter as CB regardless of case.
/summary>
Constructor & Destructor Documentation
LSAME()
DotNumerics.LinearAlgebra.CSLapack.LSAME.LSAME () inline
Member Function Documentation
Run()
bool DotNumerics.LinearAlgebra.CSLapack.LSAME.Run (string CA, string CB) inline
Purpose
LSAME returns .TRUE. if CA is the same letter as CB regardless of case.
/summary>
Parameters
CA (input) CHARACTER*1 /param>
Parameters
CB (input) CHARACTER*1 CA and CB specify the single characters to be compared. /param>
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASRT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASET.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRTI2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGETRS.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRTRI.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBAK.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANST.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFX.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRTRS.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARZ.Run(), DotNumerics.LinearAlgebra.CSLapack.DGBTRS.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANGE.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.LinearAlgebra.CSLapack.DDISNA.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYTD2.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGTR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANSY.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBAL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANSB.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYMV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFB.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRCON.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARZT.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARZB.Run(), DotNumerics.LinearAlgebra.CSLapack.DSBTRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRSV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANTR.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYTRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DORM2L.Run(), DotNumerics.LinearAlgebra.CSLapack.DORM2R.Run(), DotNumerics.LinearAlgebra.CSLapack.DORML2.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMR3.Run(), DotNumerics.LinearAlgebra.CSLapack.DSBEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLATRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DTREXC.Run(), DotNumerics.LinearAlgebra.CSLapack.DLATRS.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMTR.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMQL.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMLQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMRQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGBR.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYR2K.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRSM.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMRZ.Run(), DotNumerics.LinearAlgebra.CSLapack.DTBSV.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMBR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASDQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DTREVC.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEDC.Run(), DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELS.Run(), DotNumerics.LinearAlgebra.CSLapack.DSBEVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYEVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DBDSDC.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGSVP.Run(), DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASR.Run(), DotNumerics.LinearAlgebra.CSLapack.DHSEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRMV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run(), DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGSVD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DTGSJA.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/lsame.cs