Doc: IGLib EXTENDED: NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests Class Reference
NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests Class Reference
Public Member Functions
void CreateLoader ()
void CheckExtension ()
void CanLoadEmptyProject ()
void LoadEmptyConfigs ()
void LoadNormalProject ()
void LoadProjectWithManualBinPath ()
void LoadProjectWithComplexSettings ()
Private Attributes
NUnitProjectLoader _loader
Member Function Documentation
CreateLoader()
void NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.CreateLoader () inline
References NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests._loader.
CheckExtension()
void NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.CheckExtension () inline
References NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests._loader, NUnit.Engine.Services.ProjectLoaders.NUnitProjectLoader.CanLoadFrom(), NUnit.Framework.Assert.False(), and NUnit.Framework.Assert.That().
CanLoadEmptyProject()
void NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.CanLoadEmptyProject () inline
References NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests._loader, NUnit.Engine.Extensibility.IProject.ActiveConfigName, NUnit.Engine.Extensibility.IProject.ConfigNames, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Services.ProjectLoaders.NUnitProjectLoader.LoadFrom(), NUnit.Framework.Assert.Null(), NUnit.Engine.Tests.TempResourceFile.Path, NUnit.Engine.Extensibility.IProject.ProjectPath, and NUnit.Framework.Assert.That().
LoadEmptyConfigs()
void NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadEmptyConfigs () inline
References NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests._loader, NUnit.Engine.Extensibility.IProject.ActiveConfigName, NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Extensibility.IProject.ConfigNames, NUnit.Engine.Extensibility.IProject.GetTestPackage(), NUnit.Engine.Services.ProjectLoaders.NUnitProjectLoader.LoadFrom(), NUnit.Engine.Tests.TempResourceFile.Path, and NUnit.Engine.TestPackage.Settings.
LoadNormalProject()
void NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadNormalProject () inline
References NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests._loader, NUnit.Engine.Extensibility.IProject.ActiveConfigName, NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Extensibility.IProject.ConfigNames, NUnit.Engine.Extensibility.IProject.GetTestPackage(), NUnit.Engine.Services.ProjectLoaders.NUnitProjectLoader.LoadFrom(), NUnit.Engine.Tests.TempResourceFile.Path, NUnit.Engine.TestPackage.Settings, and NUnit.Engine.TestPackage.SubPackages.
LoadProjectWithManualBinPath()
void NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadProjectWithManualBinPath () inline
References NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests._loader, NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Extensibility.IProject.ConfigNames, NUnit.Engine.Extensibility.IProject.GetTestPackage(), NUnit.Engine.Services.ProjectLoaders.NUnitProjectLoader.LoadFrom(), NUnit.Engine.Tests.TempResourceFile.Path, and NUnit.Engine.TestPackage.Settings.
LoadProjectWithComplexSettings()
void NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadProjectWithComplexSettings () inline
References NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests._loader, NUnit.Framework.Assert.AreEqual(), NUnit.Engine.Extensibility.IProject.ConfigNames, NUnit.Engine.Extensibility.IProject.GetTestPackage(), NUnit.Engine.Services.ProjectLoaders.NUnitProjectLoader.LoadFrom(), NUnit.Engine.Tests.TempResourceFile.Path, NUnit.Engine.TestPackage.Settings, and NUnit.Engine.TestPackage.SubPackages.
Member Data Documentation
_loader
NUnitProjectLoader NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests._loader private
Referenced by NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.CanLoadEmptyProject(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.CheckExtension(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.CreateLoader(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadEmptyConfigs(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadNormalProject(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadProjectWithComplexSettings(), and NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadProjectWithManualBinPath().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/Addins/addin-tests/NUnitProjectLoaderTests.cs