Doc: IGLib EXTENDED: NUnit.Framework.Attributes.ApplyToContextTests Class Reference
NUnit.Framework.Attributes.ApplyToContextTests Class Reference
Public Member Functions
void SetUp ()
void ParallelizableAttribute ()
void SetCultureAttribute ()
void SetUICultureAttribute ()
void TimeoutAttribute ()
Private Attributes
TestExecutionContext _context
Member Function Documentation
SetUp()
void NUnit.Framework.Attributes.ApplyToContextTests.SetUp () inline
References NUnit.Framework.Attributes.ApplyToContextTests._context.
ParallelizableAttribute()
void NUnit.Framework.Attributes.ApplyToContextTests.ParallelizableAttribute () inline
References NUnit.Framework.Attributes.ApplyToContextTests._context, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestExecutionContext.ParallelScope, and NUnit.Framework.Assert.That().
SetCultureAttribute()
void NUnit.Framework.Attributes.ApplyToContextTests.SetCultureAttribute () inline
References NUnit.Framework.Attributes.ApplyToContextTests._context, NUnit.Framework.Interfaces.IApplyToContext.ApplyToContext(), NUnit.Framework.Internal.TestExecutionContext.CurrentCulture, NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
SetUICultureAttribute()
void NUnit.Framework.Attributes.ApplyToContextTests.SetUICultureAttribute () inline
References NUnit.Framework.Attributes.ApplyToContextTests._context, NUnit.Framework.Interfaces.IApplyToContext.ApplyToContext(), NUnit.Framework.Internal.TestExecutionContext.CurrentUICulture, NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
TimeoutAttribute()
void NUnit.Framework.Attributes.ApplyToContextTests.TimeoutAttribute () inline
References NUnit.Framework.Attributes.ApplyToContextTests._context, NUnit.Framework.Interfaces.IApplyToContext.ApplyToContext(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestExecutionContext.TestCaseTimeout, and NUnit.Framework.Assert.That().
Member Data Documentation
_context
TestExecutionContext NUnit.Framework.Attributes.ApplyToContextTests._context private
Referenced by NUnit.Framework.Attributes.ApplyToContextTests.ParallelizableAttribute(), NUnit.Framework.Attributes.ApplyToContextTests.SetCultureAttribute(), NUnit.Framework.Attributes.ApplyToContextTests.SetUICultureAttribute(), NUnit.Framework.Attributes.ApplyToContextTests.SetUp(), and NUnit.Framework.Attributes.ApplyToContextTests.TimeoutAttribute().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/ApplyToContextTests.cs