Doc: IGLib EXTENDED: NUnit.Framework.Attributes.SetCultureAttributeTests Class Reference
NUnit.Framework.Attributes.SetCultureAttributeTests Class Reference
Classes
class NestedBehavior
Public Member Functions
void Setup ()
void SetUICultureOnlyToFrench ()
void SetUICultureOnlyToFrenchCanadian ()
void SetUICultureOnlyToRussian ()
void SetBothCulturesToFrench ()
void SetBothCulturesToFrenchCanadian ()
void SetBothCulturesToRussian ()
void SetMixedCulturesToFrenchAndUIFrenchCanadian ()
void SetMixedCulturesToRussianAndUIEnglishUS ()
string UseWithParameterizedTest ()
Private Attributes
CultureInfo originalCulture
CultureInfo originalUICulture
Member Function Documentation
Setup()
void NUnit.Framework.Attributes.SetCultureAttributeTests.Setup () inline
References NUnit.Framework.Attributes.SetCultureAttributeTests.originalCulture, and NUnit.Framework.Attributes.SetCultureAttributeTests.originalUICulture.
SetUICultureOnlyToFrench()
void NUnit.Framework.Attributes.SetCultureAttributeTests.SetUICultureOnlyToFrench () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Attributes.SetCultureAttributeTests.originalCulture.
SetUICultureOnlyToFrenchCanadian()
void NUnit.Framework.Attributes.SetCultureAttributeTests.SetUICultureOnlyToFrenchCanadian () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Attributes.SetCultureAttributeTests.originalCulture.
SetUICultureOnlyToRussian()
void NUnit.Framework.Attributes.SetCultureAttributeTests.SetUICultureOnlyToRussian () inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.Framework.Attributes.SetCultureAttributeTests.originalCulture.
SetBothCulturesToFrench()
void NUnit.Framework.Attributes.SetCultureAttributeTests.SetBothCulturesToFrench () inline
References NUnit.Framework.Assert.AreEqual().
SetBothCulturesToFrenchCanadian()
void NUnit.Framework.Attributes.SetCultureAttributeTests.SetBothCulturesToFrenchCanadian () inline
References NUnit.Framework.Assert.AreEqual().
SetBothCulturesToRussian()
void NUnit.Framework.Attributes.SetCultureAttributeTests.SetBothCulturesToRussian () inline
References NUnit.Framework.Assert.AreEqual().
SetMixedCulturesToFrenchAndUIFrenchCanadian()
void NUnit.Framework.Attributes.SetCultureAttributeTests.SetMixedCulturesToFrenchAndUIFrenchCanadian () inline
References NUnit.Framework.Assert.AreEqual().
SetMixedCulturesToRussianAndUIEnglishUS()
void NUnit.Framework.Attributes.SetCultureAttributeTests.SetMixedCulturesToRussianAndUIEnglishUS () inline
References NUnit.Framework.Assert.AreEqual().
UseWithParameterizedTest()
string NUnit.Framework.Attributes.SetCultureAttributeTests.UseWithParameterizedTest () inline
Member Data Documentation
originalCulture
CultureInfo NUnit.Framework.Attributes.SetCultureAttributeTests.originalCulture private
Referenced by NUnit.Framework.Attributes.SetCultureAttributeTests.SetUICultureOnlyToFrench(), NUnit.Framework.Attributes.SetCultureAttributeTests.SetUICultureOnlyToFrenchCanadian(), NUnit.Framework.Attributes.SetCultureAttributeTests.SetUICultureOnlyToRussian(), and NUnit.Framework.Attributes.SetCultureAttributeTests.Setup().
originalUICulture
CultureInfo NUnit.Framework.Attributes.SetCultureAttributeTests.originalUICulture private
Referenced by NUnit.Framework.Attributes.SetCultureAttributeTests.Setup().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/SetCultureAttributeTests.cs