Doc: IGLib EXTENDED: AForge.Imaging.Filters.CannyEdgeDetector Class Reference
AForge.Imaging.Filters.CannyEdgeDetector Class Reference
Canny edge detector.
Public Member Functions
CannyEdgeDetector ()
Initializes a new instance of the CannyEdgeDetector class.
CannyEdgeDetector (byte lowThreshold, byte highThreshold)
Initializes a new instance of the CannyEdgeDetector class.
CannyEdgeDetector (byte lowThreshold, byte highThreshold, double sigma)
Initializes a new instance of the CannyEdgeDetector class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseUsingCopyPartialFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage source, UnmanagedImage destination, Rectangle rect)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
byte LowThreshold [get, set]
Low threshold.
byte HighThreshold [get, set]
High threshold.
double GaussianSigma [get, set]
Gaussian sigma.
int GaussianSize [get, set]
Gaussian size.
Properties inherited from AForge.Imaging.Filters.BaseUsingCopyPartialFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
GaussianBlur gaussianFilter = new GaussianBlur()
byte lowThreshold = 20
byte highThreshold = 100
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Canny edge detector.
The filter searches for objects' edges by applying Canny edge detector. The implementation follows Bill Green's Canny edge detection tutorial.
<note>The implemented canny edge detector has one difference with the above linked algorithm. The difference is in hysteresis step, which is a bit simplified (getting faster as a result). On the hysteresis step each pixel is compared with two threshold values: HighThreshold and LowThreshold. If pixel's value is greater or equal to HighThreshold, then it is kept as edge pixel. If pixel's value is greater or equal to LowThreshold, then it is kept as edge pixel only if there is at least one neighbouring pixel (8 neighbours are checked) which has value greater or equal to HighThreshold; otherwise it is none edge pixel. In the case if pixel's value is less than LowThreshold, then it is marked as none edge immediately. </note>
The filter accepts 8 bpp grayscale images for processing.
Sample usage:
// create filter
CannyEdgeDetector filter = new CannyEdgeDetector();
// apply the filter
filter.ApplyInPlace(image);
Initial image:
Result image:
Constructor & Destructor Documentation
CannyEdgeDetector() [1/3]
AForge.Imaging.Filters.CannyEdgeDetector.CannyEdgeDetector () inline
Initializes a new instance of the CannyEdgeDetector class.
References AForge.Imaging.Filters.CannyEdgeDetector.formatTranslations.
CannyEdgeDetector() [2/3]
AForge.Imaging.Filters.CannyEdgeDetector.CannyEdgeDetector (byte lowThreshold, byte highThreshold) inline
Initializes a new instance of the CannyEdgeDetector class.
Parameters
lowThreshold Low threshold.
highThreshold High threshold.
References AForge.Imaging.Filters.CannyEdgeDetector.highThreshold, and AForge.Imaging.Filters.CannyEdgeDetector.lowThreshold.
CannyEdgeDetector() [3/3]
AForge.Imaging.Filters.CannyEdgeDetector.CannyEdgeDetector (byte lowThreshold, byte highThreshold, double sigma) inline
Initializes a new instance of the CannyEdgeDetector class.
Parameters
lowThreshold Low threshold.
highThreshold High threshold.
sigma Gaussian sigma.
References AForge.Imaging.Filters.CannyEdgeDetector.gaussianFilter, AForge.Imaging.Filters.CannyEdgeDetector.highThreshold, AForge.Imaging.Filters.CannyEdgeDetector.lowThreshold, and AForge.Imaging.Filters.GaussianBlur.Sigma.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.CannyEdgeDetector.ProcessFilter (UnmanagedImage source, UnmanagedImage destination, Rectangle rect) inline protected virtual
Process the filter on the specified image.
Parameters
source Source image data.
destination Destination image data.
rect Image rectangle for processing by the filter.
Implements AForge.Imaging.Filters.BaseUsingCopyPartialFilter.
References AForge.Imaging.Filters.BaseUsingCopyPartialFilter.Apply(), AForge.Imaging.UnmanagedImage.Dispose(), AForge.Imaging.Filters.CannyEdgeDetector.gaussianFilter, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.Filters.CannyEdgeDetector.highThreshold, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.Filters.CannyEdgeDetector.lowThreshold, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
Member Data Documentation
gaussianFilter
GaussianBlur AForge.Imaging.Filters.CannyEdgeDetector.gaussianFilter = new GaussianBlur() private
Referenced by AForge.Imaging.Filters.CannyEdgeDetector.CannyEdgeDetector(), and AForge.Imaging.Filters.CannyEdgeDetector.ProcessFilter().
lowThreshold
byte AForge.Imaging.Filters.CannyEdgeDetector.lowThreshold = 20 private
Referenced by AForge.Imaging.Filters.CannyEdgeDetector.CannyEdgeDetector(), and AForge.Imaging.Filters.CannyEdgeDetector.ProcessFilter().
highThreshold
byte AForge.Imaging.Filters.CannyEdgeDetector.highThreshold = 100 private
Referenced by AForge.Imaging.Filters.CannyEdgeDetector.CannyEdgeDetector(), and AForge.Imaging.Filters.CannyEdgeDetector.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.CannyEdgeDetector.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.CannyEdgeDetector.CannyEdgeDetector().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.CannyEdgeDetector.FormatTranslations get
Format translations dictionary.
LowThreshold
byte AForge.Imaging.Filters.CannyEdgeDetector.LowThreshold get set
Low threshold.
Low threshold value used for hysteresis (see tutorial for more information).
Default value is set to 20.
HighThreshold
byte AForge.Imaging.Filters.CannyEdgeDetector.HighThreshold get set
High threshold.
High threshold value used for hysteresis (see tutorial for more information).
Default value is set to 100.
GaussianSigma
double AForge.Imaging.Filters.CannyEdgeDetector.GaussianSigma get set
Gaussian sigma.
Sigma value for Gaussian bluring.
GaussianSize
int AForge.Imaging.Filters.CannyEdgeDetector.GaussianSize get set
Gaussian size.
Size of Gaussian kernel.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Edge Detectors/CannyEdgeDetector.cs