Doc: IGLib EXTENDED: NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture Class Reference
NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture Class Reference
Public Member Functions
void MethodCallsIgnore (int x, int y, int z)
void MethodWithIgnoredTestCases (int num)
void MethodWithExplicitTestCases (int num)
void MethodWithInstancePropertyAsSource (string source)
void MethodWithInstanceMethodAsSource (string source)
void MethodWithInstanceFieldAsSource (string source)
void MethodWithSourceThrowingException (string lhs, string rhs)
Properties
IEnumerable InstanceProperty [get]
static IEnumerable ignored_source [get]
static IEnumerable explicit_source [get]
static IEnumerable exception_source [get]
Private Member Functions
IEnumerable InstanceMethod ()
Private Attributes
object[] InstanceField = { new object[] { "InstanceField" } }
Static Private Attributes
static object[] source
Member Function Documentation
MethodCallsIgnore()
void NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.MethodCallsIgnore (int x, int y, int z) inline
References NUnit.Framework.Assert.Ignore().
MethodWithIgnoredTestCases()
void NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.MethodWithIgnoredTestCases (int num) inline
MethodWithExplicitTestCases()
void NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.MethodWithExplicitTestCases (int num) inline
MethodWithInstancePropertyAsSource()
void NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.MethodWithInstancePropertyAsSource (string source) inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.source.
MethodWithInstanceMethodAsSource()
void NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.MethodWithInstanceMethodAsSource (string source) inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.source.
InstanceMethod()
IEnumerable NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.InstanceMethod () inline private
MethodWithInstanceFieldAsSource()
void NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.MethodWithInstanceFieldAsSource (string source) inline
References NUnit.Framework.Assert.AreEqual(), and NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.source.
MethodWithSourceThrowingException()
void NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.MethodWithSourceThrowingException (string lhs, string rhs) inline
Member Data Documentation
source
object [] NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.source static private
Initial value:
= new object[] {
            new TestCaseData( 2, 3, 4 ) }
Referenced by NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.MethodWithInstanceFieldAsSource(), NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.MethodWithInstanceMethodAsSource(), and NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.MethodWithInstancePropertyAsSource().
InstanceField
object [] NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.InstanceField = { new object[] { "InstanceField" } } private
Property Documentation
InstanceProperty
IEnumerable NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.InstanceProperty get private
ignored_source
IEnumerable NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.ignored_source static get private
explicit_source
IEnumerable NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.explicit_source static get private
exception_source
IEnumerable NUnit.TestData.TestCaseSourceAttributeFixture.TestCaseSourceAttributeFixture.exception_source static get private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/testdata/TestCaseSourceAttributeFixture.cs