Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAQP2 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAQP2 Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAQP2 (DLARF dlarf, DLARFG dlarfg, DSWAP dswap, IDAMAX idamax, DLAMCH dlamch, DNRM2 dnrm2)
DLAQP2 ()
void Run (int M, int N, int OFFSET, ref double[] A, int offset_a, int LDA, ref int[] JPVT, int offset_jpvt, ref double[] TAU, int offset_tau, ref double[] VN1, int offset_vn1, ref double[] VN2, int offset_vn2, ref double[] WORK, int offset_work)
Private Attributes
DLARF _dlarf
DLARFG _dlarfg
DSWAP _dswap
IDAMAX _idamax
DLAMCH _dlamch
DNRM2 _dnrm2
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAQP2 computes a QR factorization with column pivoting of the block A(OFFSET+1:M,1:N). The block A(1:OFFSET,1:N) is accordingly pivoted, but not factorized.
/summary>
Constructor & Destructor Documentation
DLAQP2() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAQP2.DLAQP2 (DLARF dlarf, DLARFG dlarfg, DSWAP dswap, IDAMAX idamax, DLAMCH dlamch, DNRM2 dnrm2) inline
DLAQP2() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAQP2.DLAQP2 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAQP2.Run (int M, int N, int OFFSET, ref double[] A, int offset_a, int LDA, ref int[] JPVT, int offset_jpvt, ref double[] TAU, int offset_tau, ref double[] VN1, int offset_vn1, ref double[] VN2, int offset_vn2, ref double[] WORK, int offset_work) inline
Purpose
DLAQP2 computes a QR factorization with column pivoting of the block A(OFFSET+1:M,1:N). The block A(1:OFFSET,1:N) is accordingly pivoted, but not factorized.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. 0. /param>
Parameters
OFFSET (input) INTEGER The number of rows of the matrix A that must be pivoted but no factorized. OFFSET .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the M-by-N matrix A. On exit, the upper triangle of block A(OFFSET+1:M,1:N) is the triangular factor obtained; the elements in block A(OFFSET+1:M,1:N) below the diagonal, together with the array TAU, represent the orthogonal matrix Q as a product of elementary reflectors. Block A(1:OFFSET,1:N) has been accordingly pivoted, but no factorized. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
JPVT (input/output) INTEGER array, dimension (N) On entry, if JPVT(i) .ne. 0, the i-th column of A is permuted to the front of A*P (a leading column); if JPVT(i) = 0, the i-th column of A is a free column. On exit, if JPVT(i) = k, then the i-th column of A*P was the k-th column of A. /param>
Parameters
TAU (output) DOUBLE PRECISION array, dimension (min(M,N)) The scalar factors of the elementary reflectors. /param>
Parameters
VN1 (input/output) DOUBLE PRECISION array, dimension (N) The vector with the partial column norms. /param>
Parameters
VN2 (input/output) DOUBLE PRECISION array, dimension (N) The vector with the exact column norms. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (N) /param>
References DotNumerics.LinearAlgebra.CSLapack.DLAQP2.ONE, DotNumerics.LinearAlgebra.CSLapack.DNRM2.Run(), DotNumerics.LinearAlgebra.CSLapack.IDAMAX.Run(), DotNumerics.LinearAlgebra.CSLapack.DSWAP.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAQP2.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEQP3.Run().
Member Data Documentation
_dlarf
DLARF DotNumerics.LinearAlgebra.CSLapack.DLAQP2._dlarf private
_dlarfg
DLARFG DotNumerics.LinearAlgebra.CSLapack.DLAQP2._dlarfg private
_dswap
DSWAP DotNumerics.LinearAlgebra.CSLapack.DLAQP2._dswap private
_idamax
IDAMAX DotNumerics.LinearAlgebra.CSLapack.DLAQP2._idamax private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLAQP2._dlamch private
_dnrm2
DNRM2 DotNumerics.LinearAlgebra.CSLapack.DLAQP2._dnrm2 private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAQP2.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQP2.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAQP2.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQP2.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlaqp2.cs