Doc: IGLib EXTENDED: NUnit.TestUtilities.UniqueValues Class Reference
NUnit.TestUtilities.UniqueValues Class Reference
UniqueValues is used to check a set of values to ensure that all values are unique or close enough to it. We specify how close as a ratio.
Static Public Member Functions
static void Check< T > (ActualValueDelegate< T > del, int targetCount, int maxTries)
Call a delegate until a certain number of unique values are returned, up to a maximum number of tries. Assert that the target was reached.
static int CountUniqueValuesTest (params int[] values)
Static Private Member Functions
static int CountUniqueValues (IEnumerable actual)
Count the number of actually unique values in an IEnumerable
static int CountUniqueValues< T > (ActualValueDelegate< T > del, int count)
Detailed Description
UniqueValues is used to check a set of values to ensure that all values are unique or close enough to it. We specify how close as a ratio.
Member Function Documentation
Check< T >()
static void NUnit.TestUtilities.UniqueValues.Check< T > (ActualValueDelegate< T > del, int targetCount, int maxTries) inline static
Call a delegate until a certain number of unique values are returned, up to a maximum number of tries. Assert that the target was reached.
References NUnit.Framework.Assert.Fail().
CountUniqueValues()
static int NUnit.TestUtilities.UniqueValues.CountUniqueValues (IEnumerable actual) inline static private
Count the number of actually unique values in an IEnumerable
Referenced by NUnit.TestUtilities.UniqueValues.CountUniqueValuesTest().
CountUniqueValues< T >()
static int NUnit.TestUtilities.UniqueValues.CountUniqueValues< T > (ActualValueDelegate< T > del, int count) inline static private
CountUniqueValuesTest()
static int NUnit.TestUtilities.UniqueValues.CountUniqueValuesTest (params int[] values) inline static
References NUnit.TestUtilities.UniqueValues.CountUniqueValues().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/TestUtilities/UniqueValues.cs