Doc: IGLib EXTENDED: SRVTest.SrvDriverControl Class Reference
SRVTest.SrvDriverControl Class Reference
Public Member Functions
SrvDriverControl ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Events
SrvDrivingCommandHandler SrvDrivingCommand
Private Member Functions
void DispatchCommand (SRV1.MotorCommand command)
void leftButton_Click (object sender, EventArgs e)
void forwardButton_Click (object sender, EventArgs e)
void rightButton_Click (object sender, EventArgs e)
void leftDriftButton_Click (object sender, EventArgs e)
void stopButton_Click (object sender, EventArgs e)
void rightDriftButton_Click (object sender, EventArgs e)
void leftBackwardButton_Click (object sender, EventArgs e)
void backwardButton_Click (object sender, EventArgs e)
void rightBackwardButton_Click (object sender, EventArgs e)
void speedUpButton_Click (object sender, EventArgs e)
void slowDownButton_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Button stopButton
System.Windows.Forms.Button forwardButton
System.Windows.Forms.Button backwardButton
System.Windows.Forms.Button leftButton
System.Windows.Forms.Button leftBackwardButton
System.Windows.Forms.Button rightBackwardButton
System.Windows.Forms.Button leftDriftButton
System.Windows.Forms.Button rightButton
System.Windows.Forms.Button rightDriftButton
System.Windows.Forms.Button speedUpButton
System.Windows.Forms.Button slowDownButton
Constructor & Destructor Documentation
SrvDriverControl()
SRVTest.SrvDriverControl.SrvDriverControl () inline
References SRVTest.SrvDriverControl.InitializeComponent().
Member Function Documentation
DispatchCommand()
void SRVTest.SrvDriverControl.DispatchCommand (SRV1.MotorCommand command) inline private
References SRVTest.SrvDriverControl.SrvDrivingCommand.
Referenced by SRVTest.SrvDriverControl.backwardButton_Click(), SRVTest.SrvDriverControl.forwardButton_Click(), SRVTest.SrvDriverControl.leftBackwardButton_Click(), SRVTest.SrvDriverControl.leftButton_Click(), SRVTest.SrvDriverControl.leftDriftButton_Click(), SRVTest.SrvDriverControl.rightBackwardButton_Click(), SRVTest.SrvDriverControl.rightButton_Click(), SRVTest.SrvDriverControl.rightDriftButton_Click(), SRVTest.SrvDriverControl.slowDownButton_Click(), SRVTest.SrvDriverControl.speedUpButton_Click(), and SRVTest.SrvDriverControl.stopButton_Click().
leftButton_Click()
void SRVTest.SrvDriverControl.leftButton_Click (object sender, EventArgs e) inline private
References SRVTest.SrvDriverControl.DispatchCommand().
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
forwardButton_Click()
void SRVTest.SrvDriverControl.forwardButton_Click (object sender, EventArgs e) inline private
References SRVTest.SrvDriverControl.DispatchCommand().
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
rightButton_Click()
void SRVTest.SrvDriverControl.rightButton_Click (object sender, EventArgs e) inline private
References SRVTest.SrvDriverControl.DispatchCommand().
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
leftDriftButton_Click()
void SRVTest.SrvDriverControl.leftDriftButton_Click (object sender, EventArgs e) inline private
References SRVTest.SrvDriverControl.DispatchCommand().
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
stopButton_Click()
void SRVTest.SrvDriverControl.stopButton_Click (object sender, EventArgs e) inline private
References SRVTest.SrvDriverControl.DispatchCommand().
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
rightDriftButton_Click()
void SRVTest.SrvDriverControl.rightDriftButton_Click (object sender, EventArgs e) inline private
References SRVTest.SrvDriverControl.DispatchCommand().
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
leftBackwardButton_Click()
void SRVTest.SrvDriverControl.leftBackwardButton_Click (object sender, EventArgs e) inline private
References SRVTest.SrvDriverControl.DispatchCommand().
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
backwardButton_Click()
void SRVTest.SrvDriverControl.backwardButton_Click (object sender, EventArgs e) inline private
References SRVTest.SrvDriverControl.DispatchCommand().
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
rightBackwardButton_Click()
void SRVTest.SrvDriverControl.rightBackwardButton_Click (object sender, EventArgs e) inline private
References SRVTest.SrvDriverControl.DispatchCommand().
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
speedUpButton_Click()
void SRVTest.SrvDriverControl.speedUpButton_Click (object sender, EventArgs e) inline private
References SRVTest.SrvDriverControl.DispatchCommand().
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
slowDownButton_Click()
void SRVTest.SrvDriverControl.slowDownButton_Click (object sender, EventArgs e) inline private
References SRVTest.SrvDriverControl.DispatchCommand().
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
Dispose()
override void SRVTest.SrvDriverControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References SRVTest.SrvDriverControl.components.
InitializeComponent()
void SRVTest.SrvDriverControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References SRVTest.SrvDriverControl.backwardButton, SRVTest.SrvDriverControl.backwardButton_Click(), SRVTest.SrvDriverControl.forwardButton, SRVTest.SrvDriverControl.forwardButton_Click(), SRVTest.SrvDriverControl.leftBackwardButton, SRVTest.SrvDriverControl.leftBackwardButton_Click(), SRVTest.SrvDriverControl.leftButton, SRVTest.SrvDriverControl.leftButton_Click(), SRVTest.SrvDriverControl.leftDriftButton, SRVTest.SrvDriverControl.leftDriftButton_Click(), SRVTest.SrvDriverControl.rightBackwardButton, SRVTest.SrvDriverControl.rightBackwardButton_Click(), SRVTest.SrvDriverControl.rightButton, SRVTest.SrvDriverControl.rightButton_Click(), SRVTest.SrvDriverControl.rightDriftButton, SRVTest.SrvDriverControl.rightDriftButton_Click(), SRVTest.SrvDriverControl.slowDownButton, SRVTest.SrvDriverControl.slowDownButton_Click(), SRVTest.SrvDriverControl.speedUpButton, SRVTest.SrvDriverControl.speedUpButton_Click(), SRVTest.SrvDriverControl.stopButton, and SRVTest.SrvDriverControl.stopButton_Click().
Referenced by SRVTest.SrvDriverControl.SrvDriverControl().
Member Data Documentation
components
System.ComponentModel.IContainer SRVTest.SrvDriverControl.components = null private
Required designer variable.
Referenced by SRVTest.SrvDriverControl.Dispose().
stopButton
System.Windows.Forms.Button SRVTest.SrvDriverControl.stopButton private
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
forwardButton
System.Windows.Forms.Button SRVTest.SrvDriverControl.forwardButton private
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
backwardButton
System.Windows.Forms.Button SRVTest.SrvDriverControl.backwardButton private
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
leftButton
System.Windows.Forms.Button SRVTest.SrvDriverControl.leftButton private
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
leftBackwardButton
System.Windows.Forms.Button SRVTest.SrvDriverControl.leftBackwardButton private
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
rightBackwardButton
System.Windows.Forms.Button SRVTest.SrvDriverControl.rightBackwardButton private
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
leftDriftButton
System.Windows.Forms.Button SRVTest.SrvDriverControl.leftDriftButton private
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
rightButton
System.Windows.Forms.Button SRVTest.SrvDriverControl.rightButton private
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
rightDriftButton
System.Windows.Forms.Button SRVTest.SrvDriverControl.rightDriftButton private
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
speedUpButton
System.Windows.Forms.Button SRVTest.SrvDriverControl.speedUpButton private
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
slowDownButton
System.Windows.Forms.Button SRVTest.SrvDriverControl.slowDownButton private
Referenced by SRVTest.SrvDriverControl.InitializeComponent().
Event Documentation
SrvDrivingCommand
SrvDrivingCommandHandler SRVTest.SrvDriverControl.SrvDrivingCommand
Referenced by SRVTest.SrvDriverControl.DispatchCommand(), and SRVTest.MainForm.InitializeComponent().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Robotics/Surveyor/SRVTest/SrvDriverControl.cs
shelldev/lib_ann/aforge.net/Samples/Robotics/Surveyor/SRVTest/SrvDriverControl.Designer.cs