Doc: IGLib EXTENDED: Player.MainForm Class Reference
Player.MainForm Class Reference
Public Member Functions
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void MainForm_FormClosing (object sender, FormClosingEventArgs e)
void exitToolStripMenuItem_Click (object sender, EventArgs e)
void localVideoCaptureDeviceToolStripMenuItem_Click (object sender, EventArgs e)
void openVideofileusingDirectShowToolStripMenuItem_Click (object sender, EventArgs e)
void openJPEGURLToolStripMenuItem_Click (object sender, EventArgs e)
void openMJPEGURLToolStripMenuItem_Click (object sender, EventArgs e)
void OpenVideoSource (IVideoSource source)
void CloseCurrentVideoSource ()
void videoSourcePlayer_NewFrame (object sender, ref Bitmap image)
void timer_Tick (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Stopwatch stopWatch = null
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.MenuStrip mainMenuStrip
System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem
System.Windows.Forms.StatusStrip statusStrip
System.Windows.Forms.Panel mainPanel
System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem localVideoCaptureDeviceToolStripMenuItem
System.Windows.Forms.ToolStripSeparator toolStripMenuItem1
AForge.Controls.VideoSourcePlayer videoSourcePlayer
System.Windows.Forms.Timer timer
System.Windows.Forms.ToolStripStatusLabel fpsLabel
System.Windows.Forms.ToolStripMenuItem openVideofileusingDirectShowToolStripMenuItem
System.Windows.Forms.OpenFileDialog openFileDialog
System.Windows.Forms.ToolStripMenuItem openJPEGURLToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem openMJPEGURLToolStripMenuItem
Constructor & Destructor Documentation
MainForm()
Player.MainForm.MainForm () inline
References Player.MainForm.InitializeComponent().
Member Function Documentation
MainForm_FormClosing()
void Player.MainForm.MainForm_FormClosing (object sender, FormClosingEventArgs e) inline private
References Player.MainForm.CloseCurrentVideoSource().
Referenced by Player.MainForm.InitializeComponent().
exitToolStripMenuItem_Click()
void Player.MainForm.exitToolStripMenuItem_Click (object sender, EventArgs e) inline private
Referenced by Player.MainForm.InitializeComponent().
localVideoCaptureDeviceToolStripMenuItem_Click()
void Player.MainForm.localVideoCaptureDeviceToolStripMenuItem_Click (object sender, EventArgs e) inline private
References Player.MainForm.OpenVideoSource(), and AForge.Video.DirectShow.VideoCaptureDeviceForm.VideoDevice.
Referenced by Player.MainForm.InitializeComponent().
openVideofileusingDirectShowToolStripMenuItem_Click()
void Player.MainForm.openVideofileusingDirectShowToolStripMenuItem_Click (object sender, EventArgs e) inline private
References Player.MainForm.openFileDialog, and Player.MainForm.OpenVideoSource().
Referenced by Player.MainForm.InitializeComponent().
openJPEGURLToolStripMenuItem_Click()
void Player.MainForm.openJPEGURLToolStripMenuItem_Click (object sender, EventArgs e) inline private
References Player.URLForm.Description, Player.MainForm.OpenVideoSource(), Player.URLForm.URL, and Player.URLForm.URLs.
Referenced by Player.MainForm.InitializeComponent().
openMJPEGURLToolStripMenuItem_Click()
void Player.MainForm.openMJPEGURLToolStripMenuItem_Click (object sender, EventArgs e) inline private
References Player.URLForm.Description, Player.MainForm.OpenVideoSource(), Player.URLForm.URL, and Player.URLForm.URLs.
Referenced by Player.MainForm.InitializeComponent().
OpenVideoSource()
void Player.MainForm.OpenVideoSource (IVideoSource source) inline private
References Player.MainForm.CloseCurrentVideoSource(), Player.MainForm.stopWatch, Player.MainForm.timer, and Player.MainForm.videoSourcePlayer.
Referenced by Player.MainForm.localVideoCaptureDeviceToolStripMenuItem_Click(), Player.MainForm.openJPEGURLToolStripMenuItem_Click(), Player.MainForm.openMJPEGURLToolStripMenuItem_Click(), and Player.MainForm.openVideofileusingDirectShowToolStripMenuItem_Click().
CloseCurrentVideoSource()
void Player.MainForm.CloseCurrentVideoSource () inline private
References Player.MainForm.videoSourcePlayer.
Referenced by Player.MainForm.MainForm_FormClosing(), and Player.MainForm.OpenVideoSource().
videoSourcePlayer_NewFrame()
void Player.MainForm.videoSourcePlayer_NewFrame (object sender, ref Bitmap image) inline private
Referenced by Player.MainForm.InitializeComponent().
timer_Tick()
void Player.MainForm.timer_Tick (object sender, EventArgs e) inline private
References Player.MainForm.fpsLabel, AForge.Video.IVideoSource.FramesReceived, Player.MainForm.stopWatch, and Player.MainForm.videoSourcePlayer.
Referenced by Player.MainForm.InitializeComponent().
Dispose()
override void Player.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References Player.MainForm.components.
InitializeComponent()
void Player.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References Player.MainForm.components, Player.MainForm.exitToolStripMenuItem, Player.MainForm.exitToolStripMenuItem_Click(), Player.MainForm.fileToolStripMenuItem, Player.MainForm.fpsLabel, Player.MainForm.localVideoCaptureDeviceToolStripMenuItem, Player.MainForm.localVideoCaptureDeviceToolStripMenuItem_Click(), Player.MainForm.MainForm_FormClosing(), Player.MainForm.mainMenuStrip, Player.MainForm.mainPanel, AForge.Controls.VideoSourcePlayer.NewFrameHandler(), Player.MainForm.openFileDialog, Player.MainForm.openJPEGURLToolStripMenuItem, Player.MainForm.openJPEGURLToolStripMenuItem_Click(), Player.MainForm.openMJPEGURLToolStripMenuItem, Player.MainForm.openMJPEGURLToolStripMenuItem_Click(), Player.MainForm.openVideofileusingDirectShowToolStripMenuItem, Player.MainForm.openVideofileusingDirectShowToolStripMenuItem_Click(), Player.MainForm.statusStrip, Player.MainForm.timer, Player.MainForm.timer_Tick(), Player.MainForm.toolStripMenuItem1, Player.MainForm.videoSourcePlayer, and Player.MainForm.videoSourcePlayer_NewFrame().
Referenced by Player.MainForm.MainForm().
Member Data Documentation
stopWatch
Stopwatch Player.MainForm.stopWatch = null private
Referenced by Player.MainForm.OpenVideoSource(), and Player.MainForm.timer_Tick().
components
System.ComponentModel.IContainer Player.MainForm.components = null private
Required designer variable.
Referenced by Player.MainForm.Dispose(), and Player.MainForm.InitializeComponent().
mainMenuStrip
System.Windows.Forms.MenuStrip Player.MainForm.mainMenuStrip private
Referenced by Player.MainForm.InitializeComponent().
fileToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem Player.MainForm.fileToolStripMenuItem private
Referenced by Player.MainForm.InitializeComponent().
statusStrip
System.Windows.Forms.StatusStrip Player.MainForm.statusStrip private
Referenced by Player.MainForm.InitializeComponent().
mainPanel
System.Windows.Forms.Panel Player.MainForm.mainPanel private
Referenced by Player.MainForm.InitializeComponent().
exitToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem Player.MainForm.exitToolStripMenuItem private
Referenced by Player.MainForm.InitializeComponent().
localVideoCaptureDeviceToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem Player.MainForm.localVideoCaptureDeviceToolStripMenuItem private
Referenced by Player.MainForm.InitializeComponent().
toolStripMenuItem1
System.Windows.Forms.ToolStripSeparator Player.MainForm.toolStripMenuItem1 private
Referenced by Player.MainForm.InitializeComponent().
videoSourcePlayer
AForge.Controls.VideoSourcePlayer Player.MainForm.videoSourcePlayer private
Referenced by Player.MainForm.CloseCurrentVideoSource(), Player.MainForm.InitializeComponent(), Player.MainForm.OpenVideoSource(), and Player.MainForm.timer_Tick().
timer
System.Windows.Forms.Timer Player.MainForm.timer private
Referenced by Player.MainForm.InitializeComponent(), and Player.MainForm.OpenVideoSource().
fpsLabel
System.Windows.Forms.ToolStripStatusLabel Player.MainForm.fpsLabel private
Referenced by Player.MainForm.InitializeComponent(), and Player.MainForm.timer_Tick().
openVideofileusingDirectShowToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem Player.MainForm.openVideofileusingDirectShowToolStripMenuItem private
Referenced by Player.MainForm.InitializeComponent().
openFileDialog
System.Windows.Forms.OpenFileDialog Player.MainForm.openFileDialog private
Referenced by Player.MainForm.InitializeComponent(), and Player.MainForm.openVideofileusingDirectShowToolStripMenuItem_Click().
openJPEGURLToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem Player.MainForm.openJPEGURLToolStripMenuItem private
Referenced by Player.MainForm.InitializeComponent().
openMJPEGURLToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem Player.MainForm.openMJPEGURLToolStripMenuItem private
Referenced by Player.MainForm.InitializeComponent().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Video/Player/MainForm.cs
shelldev/lib_ann/aforge.net/Samples/Video/Player/MainForm.Designer.cs