Doc: IGLib EXTENDED: IG.MPetekLib.Application.Scripts.LinearOscillator._10MultipleResCurvesPlotObsolete Class Reference
IG.MPetekLib.Application.Scripts.LinearOscillator._10MultipleResCurvesPlotObsolete Class Reference
Static Public Member Functions
static void ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts)
Applies style and other settings to the plotter used to show the parametric graph.
static void ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichCurve, int numCurves)
Applies style and other settings to the plotter used to show the parametric graph.
static void Run (double dampingMin, double dampingMax, int numCurves, int numPoints)
Plots a family of resonance curves.
static void Run (string[] arguments)
Plots a family of resonance curves.
Member Function Documentation
ApplyPlotterSettingsDefault()
static void IG.MPetekLib.Application.Scripts.LinearOscillator._10MultipleResCurvesPlotObsolete.ApplyPlotterSettingsDefault (PlotterZedGraph plotter, int whichInput, int numInputs, int whichOutput, int numOutpts) inline static
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plotter Plotter to which settings are applied.
whichInput ID of the input to be plotted.
whichOutpput ID of the output to be plotted.
References IG.Gr.PlotterZedGraph.IsShowPointValues.
ApplyPlotCurveSettingsDefault()
static void IG.MPetekLib.Application.Scripts.LinearOscillator._10MultipleResCurvesPlotObsolete.ApplyPlotCurveSettingsDefault (PlotZedgraphCurve plot, int whichCurve, int numCurves) inline static
Applies style and other settings to the plotter used to show the parametric graph.
Parameters
plot Curve plot to which settings are applied.
whichInput ID of the curve to be plotted.
whichOutpput Number of all curves to be plotted.
References IG.Lib.ColorScaleBase.Create(), IG.Lib.ColorScaleBase.GetColor(), IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LineWidth, IG.Gr.PlotZedgraphCurve.PointBorderColor, IG.Gr.PlotZedgraphCurve.PointFillColor, and IG.Gr.PlotZedgraphCurve.PointsVisible.
Referenced by IG.MPetekLib.Application.Scripts.LinearOscillator._10MultipleResCurvesPlotObsolete.Run().
Run() [1/2]
static void IG.MPetekLib.Application.Scripts.LinearOscillator._10MultipleResCurvesPlotObsolete.Run (double dampingMin, double dampingMax, int numCurves, int numPoints) inline static
Plots a family of resonance curves.
Parameters
dampingMin Minimal damping coefficient.
dampingMax Maximal damping coefficient.
numCurves Number of resonance curves plotted.
numPoints Number of points on each curve.
Plotting is performed in the main thread.
References IG.MPetekLib.Application.Scripts.LinearOscillator._10MultipleResCurvesPlotObsolete.ApplyPlotCurveSettingsDefault(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.CalcSteadyStateAmplitudeVsDrivingFrequency(), IG.Gr.PlotterZedGraph.CreateDefault(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.DampingCoefficient, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.EndingDrivingAngularFrequency, IG.Gr.ZedGraphWindow.GraphControl, IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase.NewCurveFromPlottableData(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.NSamplesForResonanceCurve, IG.Gr.PlotterZedGraph.RemoveAllPlotObjects(), IG.Gr.PlotterZedGraph.ResetView(), IG.MPetekLib.Algorithms.PlottableModels.PlottableODEModelBase.Solver, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.StartingDrivingAngularFrequency, IG.MPetekLib.Algorithms.Solvers.InitialProblemODE_RK4.InitialProblemSolverBase.StepSize, IG.Gr.PlotterZedGraph.Title, IG.Gr.PlotterZedGraph.Update(), IG.Gr.PlotterZedGraph.XAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabel.
Referenced by IG.Script.AppMarkoPetek.App10MultipleResCurvesPlotObsolete(), and IG.MPetekLib.Application.Scripts.LinearOscillator._10MultipleResCurvesPlotObsolete.Run().
Run() [2/2]
static void IG.MPetekLib.Application.Scripts.LinearOscillator._10MultipleResCurvesPlotObsolete.Run (string[] arguments) inline static
Plots a family of resonance curves.
Plotting is performed in the main thread.
References IG.MPetekLib.Application.Scripts.LinearOscillator._10MultipleResCurvesPlotObsolete.Run().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/Guest_Marko_Petek_Lib/application/scripts/LinearOscillator/10MultipleResCurvesPlotObsolete.cs