Doc: IGLib EXTENDED: alglib.normaldistr Class Reference
alglib.normaldistr Class Reference
Static Public Member Functions
static double errorfunction (double x)
static double errorfunctionc (double x)
static double normaldistribution (double x)
static double inverf (double e)
static double invnormaldistribution (double y0)
static double errorfunction (double x)
static double errorfunctionc (double x)
static double normaldistribution (double x)
static double inverf (double e)
static double invnormaldistribution (double y0)
Member Function Documentation
errorfunction() [1/2]
static double alglib.normaldistr.errorfunction (double x) inline static
References alglib.normaldistr.errorfunctionc().
Referenced by alglib.errorfunction(), alglib.normaldistr.errorfunctionc(), and alglib.normaldistr.normaldistribution().
errorfunctionc() [1/2]
static double alglib.normaldistr.errorfunctionc (double x) inline static
References alglib.normaldistr.errorfunction(), and alglib.math.sqr().
Referenced by alglib.normaldistr.errorfunction(), alglib.errorfunctionc(), and alglib.normaldistr.errorfunctionc().
normaldistribution() [1/2]
static double alglib.normaldistr.normaldistribution (double x) inline static
References alglib.normaldistr.errorfunction().
Referenced by alglib.normaldistribution().
inverf() [1/2]
static double alglib.normaldistr.inverf (double e) inline static
References alglib.normaldistr.invnormaldistribution().
Referenced by alglib.inverf().
invnormaldistribution() [1/2]
static double alglib.normaldistr.invnormaldistribution (double y0) inline static
References alglib.math.maxrealnumber.
Referenced by alglib.normaldistr.inverf(), alglib.ibetaf.invincompletebeta(), alglib.igammaf.invincompletegammac(), and alglib.invnormaldistribution().
errorfunction() [2/2]
static double alglib.normaldistr.errorfunction (double x) inline static
References alglib.normaldistr.errorfunctionc().
errorfunctionc() [2/2]
static double alglib.normaldistr.errorfunctionc (double x) inline static
References alglib.normaldistr.errorfunction(), alglib.normaldistr.errorfunctionc(), and alglib.math.sqr().
normaldistribution() [2/2]
static double alglib.normaldistr.normaldistribution (double x) inline static
References alglib.normaldistr.errorfunction().
inverf() [2/2]
static double alglib.normaldistr.inverf (double e) inline static
References alglib.normaldistr.invnormaldistribution().
invnormaldistribution() [2/2]
static double alglib.normaldistr.invnormaldistribution (double y0) inline static
References alglib.math.maxrealnumber.
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/specialfunctions.cs