Doc: IGLib EXTENDED: KinectCapture.MainForm Class Reference
KinectCapture.MainForm Class Reference
Public Member Functions
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void MainForm_Load (object sender, EventArgs e)
void MainForm_FormClosing (object sender, FormClosingEventArgs e)
void EnableConnectionControls (bool enable)
void connectButton_Click (object sender, EventArgs e)
void disconnectButton_Click (object sender, EventArgs e)
bool Connect ()
void Disconnect ()
void ledColorCombo_SelectedIndexChanged (object sender, EventArgs e)
void tiltUpDown_ValueChanged (object sender, EventArgs e)
void timer_Tick (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Kinect kinectDevice = null
KinectVideoCamera videoCamera = null
KinectDepthCamera depthCamera = null
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Label label1
System.Windows.Forms.ComboBox devicesCombo
System.Windows.Forms.Button connectButton
System.Windows.Forms.Button disconnectButton
System.Windows.Forms.TableLayoutPanel tableLayoutPanel
System.Windows.Forms.Panel leftPanel
System.Windows.Forms.Panel rightPanel
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.GroupBox groupBox2
AForge.Controls.VideoSourcePlayer videoCameraPlayer
AForge.Controls.VideoSourcePlayer depthCameraPlayer
System.Windows.Forms.Label label2
System.Windows.Forms.ComboBox ledColorCombo
System.Windows.Forms.Label label3
System.Windows.Forms.NumericUpDown tiltUpDown
System.Windows.Forms.Label label4
System.Windows.Forms.ComboBox videoModeCombo
System.Windows.Forms.StatusStrip statusStrip
System.Windows.Forms.ToolStripStatusLabel accelerometerLabel
System.Windows.Forms.Timer timer
Static Private Attributes
static readonly LedColorOption[] ledMode
Constructor & Destructor Documentation
MainForm()
KinectCapture.MainForm.MainForm () inline
References KinectCapture.MainForm.InitializeComponent().
Member Function Documentation
MainForm_Load()
void KinectCapture.MainForm.MainForm_Load (object sender, EventArgs e) inline private
References AForge.Video.Kinect.Kinect.DeviceCount, KinectCapture.MainForm.devicesCombo, KinectCapture.MainForm.EnableConnectionControls(), and KinectCapture.MainForm.videoModeCombo.
Referenced by KinectCapture.MainForm.InitializeComponent().
MainForm_FormClosing()
void KinectCapture.MainForm.MainForm_FormClosing (object sender, FormClosingEventArgs e) inline private
References KinectCapture.MainForm.Disconnect().
Referenced by KinectCapture.MainForm.InitializeComponent().
EnableConnectionControls()
void KinectCapture.MainForm.EnableConnectionControls (bool enable) inline private
References KinectCapture.MainForm.connectButton, KinectCapture.MainForm.devicesCombo, KinectCapture.MainForm.disconnectButton, KinectCapture.MainForm.ledColorCombo, KinectCapture.MainForm.tiltUpDown, and KinectCapture.MainForm.videoModeCombo.
Referenced by KinectCapture.MainForm.connectButton_Click(), KinectCapture.MainForm.disconnectButton_Click(), and KinectCapture.MainForm.MainForm_Load().
connectButton_Click()
void KinectCapture.MainForm.connectButton_Click (object sender, EventArgs e) inline private
References KinectCapture.MainForm.Connect(), and KinectCapture.MainForm.EnableConnectionControls().
Referenced by KinectCapture.MainForm.InitializeComponent().
disconnectButton_Click()
void KinectCapture.MainForm.disconnectButton_Click (object sender, EventArgs e) inline private
References KinectCapture.MainForm.Disconnect(), and KinectCapture.MainForm.EnableConnectionControls().
Referenced by KinectCapture.MainForm.InitializeComponent().
Connect()
bool KinectCapture.MainForm.Connect () inline private
References AForge.Video.Kinect.KinectVideoCamera.CameraMode, KinectCapture.MainForm.depthCamera, KinectCapture.MainForm.depthCameraPlayer, AForge.Video.Kinect.Kinect.DeviceCount, KinectCapture.MainForm.devicesCombo, KinectCapture.MainForm.Disconnect(), AForge.Video.Kinect.Kinect.GetDepthCamera(), AForge.Video.Kinect.Kinect.GetDevice(), AForge.Video.Kinect.Kinect.GetVideoCamera(), KinectCapture.MainForm.kinectDevice, KinectCapture.MainForm.ledColorCombo, AForge.Video.Kinect.Kinect.SetMotorTilt(), KinectCapture.MainForm.tiltUpDown, KinectCapture.MainForm.timer, KinectCapture.MainForm.videoCamera, KinectCapture.MainForm.videoCameraPlayer, and KinectCapture.MainForm.videoModeCombo.
Referenced by KinectCapture.MainForm.connectButton_Click().
Disconnect()
void KinectCapture.MainForm.Disconnect () inline private
References KinectCapture.MainForm.depthCamera, KinectCapture.MainForm.depthCameraPlayer, AForge.Video.Kinect.Kinect.Dispose(), KinectCapture.MainForm.kinectDevice, AForge.Video.Kinect.KinectDepthCamera.Stop(), AForge.Video.Kinect.KinectVideoCamera.Stop(), KinectCapture.MainForm.timer, KinectCapture.MainForm.videoCamera, and KinectCapture.MainForm.videoCameraPlayer.
Referenced by KinectCapture.MainForm.Connect(), KinectCapture.MainForm.disconnectButton_Click(), and KinectCapture.MainForm.MainForm_FormClosing().
ledColorCombo_SelectedIndexChanged()
void KinectCapture.MainForm.ledColorCombo_SelectedIndexChanged (object sender, EventArgs e) inline private
References KinectCapture.MainForm.kinectDevice, KinectCapture.MainForm.ledColorCombo, KinectCapture.MainForm.ledMode, and AForge.Video.Kinect.Kinect.SetLedColor().
Referenced by KinectCapture.MainForm.InitializeComponent().
tiltUpDown_ValueChanged()
void KinectCapture.MainForm.tiltUpDown_ValueChanged (object sender, EventArgs e) inline private
References KinectCapture.MainForm.kinectDevice, AForge.Video.Kinect.Kinect.SetMotorTilt(), and KinectCapture.MainForm.tiltUpDown.
Referenced by KinectCapture.MainForm.InitializeComponent().
timer_Tick()
void KinectCapture.MainForm.timer_Tick (object sender, EventArgs e) inline private
References KinectCapture.MainForm.accelerometerLabel, AForge.Video.Kinect.Kinect.GetAccelerometerValues(), and KinectCapture.MainForm.kinectDevice.
Referenced by KinectCapture.MainForm.InitializeComponent().
Dispose()
override void KinectCapture.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References KinectCapture.MainForm.components.
InitializeComponent()
void KinectCapture.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References KinectCapture.MainForm.accelerometerLabel, KinectCapture.MainForm.components, KinectCapture.MainForm.connectButton, KinectCapture.MainForm.connectButton_Click(), KinectCapture.MainForm.depthCameraPlayer, KinectCapture.MainForm.devicesCombo, KinectCapture.MainForm.disconnectButton, KinectCapture.MainForm.disconnectButton_Click(), KinectCapture.MainForm.groupBox1, KinectCapture.MainForm.groupBox2, KinectCapture.MainForm.label1, KinectCapture.MainForm.label2, KinectCapture.MainForm.label3, KinectCapture.MainForm.label4, KinectCapture.MainForm.ledColorCombo, KinectCapture.MainForm.ledColorCombo_SelectedIndexChanged(), KinectCapture.MainForm.leftPanel, KinectCapture.MainForm.MainForm_FormClosing(), KinectCapture.MainForm.MainForm_Load(), KinectCapture.MainForm.rightPanel, KinectCapture.MainForm.statusStrip, KinectCapture.MainForm.tableLayoutPanel, KinectCapture.MainForm.tiltUpDown, KinectCapture.MainForm.tiltUpDown_ValueChanged(), KinectCapture.MainForm.timer, KinectCapture.MainForm.timer_Tick(), KinectCapture.MainForm.videoCameraPlayer, and KinectCapture.MainForm.videoModeCombo.
Referenced by KinectCapture.MainForm.MainForm().
Member Data Documentation
kinectDevice
Kinect KinectCapture.MainForm.kinectDevice = null private
Referenced by KinectCapture.MainForm.Connect(), KinectCapture.MainForm.Disconnect(), KinectCapture.MainForm.ledColorCombo_SelectedIndexChanged(), KinectCapture.MainForm.tiltUpDown_ValueChanged(), and KinectCapture.MainForm.timer_Tick().
videoCamera
KinectVideoCamera KinectCapture.MainForm.videoCamera = null private
Referenced by KinectCapture.MainForm.Connect(), and KinectCapture.MainForm.Disconnect().
depthCamera
KinectDepthCamera KinectCapture.MainForm.depthCamera = null private
Referenced by KinectCapture.MainForm.Connect(), and KinectCapture.MainForm.Disconnect().
ledMode
readonly LedColorOption [] KinectCapture.MainForm.ledMode static private
Initial value:
=
        {
           LedColorOption.Off, LedColorOption.Green, LedColorOption.Red,
           LedColorOption.Yellow, LedColorOption.BlinkGreen, LedColorOption.BlinkRedYellow
        }
Referenced by KinectCapture.MainForm.ledColorCombo_SelectedIndexChanged().
components
System.ComponentModel.IContainer KinectCapture.MainForm.components = null private
Required designer variable.
Referenced by KinectCapture.MainForm.Dispose(), and KinectCapture.MainForm.InitializeComponent().
label1
System.Windows.Forms.Label KinectCapture.MainForm.label1 private
Referenced by KinectCapture.MainForm.InitializeComponent().
devicesCombo
System.Windows.Forms.ComboBox KinectCapture.MainForm.devicesCombo private
Referenced by KinectCapture.MainForm.Connect(), KinectCapture.MainForm.EnableConnectionControls(), KinectCapture.MainForm.InitializeComponent(), and KinectCapture.MainForm.MainForm_Load().
connectButton
System.Windows.Forms.Button KinectCapture.MainForm.connectButton private
Referenced by KinectCapture.MainForm.EnableConnectionControls(), and KinectCapture.MainForm.InitializeComponent().
disconnectButton
System.Windows.Forms.Button KinectCapture.MainForm.disconnectButton private
Referenced by KinectCapture.MainForm.EnableConnectionControls(), and KinectCapture.MainForm.InitializeComponent().
tableLayoutPanel
System.Windows.Forms.TableLayoutPanel KinectCapture.MainForm.tableLayoutPanel private
Referenced by KinectCapture.MainForm.InitializeComponent().
leftPanel
System.Windows.Forms.Panel KinectCapture.MainForm.leftPanel private
Referenced by KinectCapture.MainForm.InitializeComponent().
rightPanel
System.Windows.Forms.Panel KinectCapture.MainForm.rightPanel private
Referenced by KinectCapture.MainForm.InitializeComponent().
groupBox1
System.Windows.Forms.GroupBox KinectCapture.MainForm.groupBox1 private
Referenced by KinectCapture.MainForm.InitializeComponent().
groupBox2
System.Windows.Forms.GroupBox KinectCapture.MainForm.groupBox2 private
Referenced by KinectCapture.MainForm.InitializeComponent().
videoCameraPlayer
AForge.Controls.VideoSourcePlayer KinectCapture.MainForm.videoCameraPlayer private
Referenced by KinectCapture.MainForm.Connect(), KinectCapture.MainForm.Disconnect(), and KinectCapture.MainForm.InitializeComponent().
depthCameraPlayer
AForge.Controls.VideoSourcePlayer KinectCapture.MainForm.depthCameraPlayer private
Referenced by KinectCapture.MainForm.Connect(), KinectCapture.MainForm.Disconnect(), and KinectCapture.MainForm.InitializeComponent().
label2
System.Windows.Forms.Label KinectCapture.MainForm.label2 private
Referenced by KinectCapture.MainForm.InitializeComponent().
ledColorCombo
System.Windows.Forms.ComboBox KinectCapture.MainForm.ledColorCombo private
Referenced by KinectCapture.MainForm.Connect(), KinectCapture.MainForm.EnableConnectionControls(), KinectCapture.MainForm.InitializeComponent(), and KinectCapture.MainForm.ledColorCombo_SelectedIndexChanged().
label3
System.Windows.Forms.Label KinectCapture.MainForm.label3 private
Referenced by KinectCapture.MainForm.InitializeComponent().
tiltUpDown
System.Windows.Forms.NumericUpDown KinectCapture.MainForm.tiltUpDown private
Referenced by KinectCapture.MainForm.Connect(), KinectCapture.MainForm.EnableConnectionControls(), KinectCapture.MainForm.InitializeComponent(), and KinectCapture.MainForm.tiltUpDown_ValueChanged().
label4
System.Windows.Forms.Label KinectCapture.MainForm.label4 private
Referenced by KinectCapture.MainForm.InitializeComponent().
videoModeCombo
System.Windows.Forms.ComboBox KinectCapture.MainForm.videoModeCombo private
Referenced by KinectCapture.MainForm.Connect(), KinectCapture.MainForm.EnableConnectionControls(), KinectCapture.MainForm.InitializeComponent(), and KinectCapture.MainForm.MainForm_Load().
statusStrip
System.Windows.Forms.StatusStrip KinectCapture.MainForm.statusStrip private
Referenced by KinectCapture.MainForm.InitializeComponent().
accelerometerLabel
System.Windows.Forms.ToolStripStatusLabel KinectCapture.MainForm.accelerometerLabel private
Referenced by KinectCapture.MainForm.InitializeComponent(), and KinectCapture.MainForm.timer_Tick().
timer
System.Windows.Forms.Timer KinectCapture.MainForm.timer private
Referenced by KinectCapture.MainForm.Connect(), KinectCapture.MainForm.Disconnect(), and KinectCapture.MainForm.InitializeComponent().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Video/Kinect Capture/MainForm.cs
shelldev/lib_ann/aforge.net/Samples/Video/Kinect Capture/MainForm.Designer.cs