Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLASD6 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLASD6 Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLASD6 (DCOPY dcopy, DLAMRG dlamrg, DLASCL dlascl, DLASD7 dlasd7, DLASD8 dlasd8, XERBLA xerbla)
DLASD6 ()
void Run (int ICOMPQ, int NL, int NR, int SQRE, ref double[] D, int offset_d, ref double[] VF, int offset_vf, ref double[] VL, int offset_vl, ref double ALPHA, ref double BETA, ref int[] IDXQ, int offset_idxq, ref int[] PERM, int offset_perm, ref int GIVPTR, ref int[] GIVCOL, int offset_givcol, int LDGCOL, ref double[] GIVNUM, int offset_givnum, int LDGNUM, ref double[] POLES, int offset_poles, ref double[] DIFL, int offset_difl, ref double[] DIFR, int offset_difr, ref double[] Z, int offset_z, ref int K, ref double C, ref double S, ref double[] WORK, int offset_work, ref int[] IWORK, int offset_iwork, ref int INFO)
Private Attributes
DCOPY _dcopy
DLAMRG _dlamrg
DLASCL _dlascl
DLASD7 _dlasd7
DLASD8 _dlasd8
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLASD6 computes the SVD of an updated upper bidiagonal matrix B obtained by merging two smaller ones by appending a row. This routine is used only for the problem which requires all singular values and optionally singular vector matrices in factored form. B is an N-by-M matrix with N = NL + NR + 1 and M = N + SQRE. A related subroutine, DLASD1, handles the case in which all singular values and singular vectors of the bidiagonal matrix are desired.
DLASD6 computes the SVD as follows:
(D1(in) 0 0 0) B = U(in) * (Z1' a Z2' b) * VT(in) (0 0 D2(in) 0)
= U(out) * (D(out) 0) * VT(out)
where Z' = (Z1' a Z2' b) = u' VT', and u is a vector of dimension M with ALPHA and BETA in the NL+1 and NL+2 th entries and zeros elsewhere; and the entry b is empty if SQRE = 0.
The singular values of B can be computed using D1, D2, the first components of all the right singular vectors of the lower block, and the last components of all the right singular vectors of the upper block. These components are stored and updated in VF and VL, respectively, in DLASD6. Hence U and VT are not explicitly referenced.
The singular values are stored in D. The algorithm consists of two stages:
The first stage consists of deflating the size of the problem when there are multiple singular values or if there is a zero in the Z vector. For each such occurence the dimension of the secular equation problem is reduced by one. This stage is performed by the routine DLASD7.
The second stage consists of calculating the updated singular values. This is done by finding the roots of the secular equation via the routine DLASD4 (as called by DLASD8). This routine also updates VF and VL and computes the distances between the updated singular values and the old singular values.
DLASD6 is called from DLASDA.
/summary>
Constructor & Destructor Documentation
DLASD6() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLASD6.DLASD6 (DCOPY dcopy, DLAMRG dlamrg, DLASCL dlascl, DLASD7 dlasd7, DLASD8 dlasd8, XERBLA xerbla) inline
DLASD6() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLASD6.DLASD6 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLASD6.Run (int ICOMPQ, int NL, int NR, int SQRE, ref double[] D, int offset_d, ref double[] VF, int offset_vf, ref double[] VL, int offset_vl, ref double ALPHA, ref double BETA, ref int[] IDXQ, int offset_idxq, ref int[] PERM, int offset_perm, ref int GIVPTR, ref int[] GIVCOL, int offset_givcol, int LDGCOL, ref double[] GIVNUM, int offset_givnum, int LDGNUM, ref double[] POLES, int offset_poles, ref double[] DIFL, int offset_difl, ref double[] DIFR, int offset_difr, ref double[] Z, int offset_z, ref int K, ref double C, ref double S, ref double[] WORK, int offset_work, ref int[] IWORK, int offset_iwork, ref int INFO) inline
Purpose
DLASD6 computes the SVD of an updated upper bidiagonal matrix B obtained by merging two smaller ones by appending a row. This routine is used only for the problem which requires all singular values and optionally singular vector matrices in factored form. B is an N-by-M matrix with N = NL + NR + 1 and M = N + SQRE. A related subroutine, DLASD1, handles the case in which all singular values and singular vectors of the bidiagonal matrix are desired.
DLASD6 computes the SVD as follows:
(D1(in) 0 0 0) B = U(in) * (Z1' a Z2' b) * VT(in) (0 0 D2(in) 0)
= U(out) * (D(out) 0) * VT(out)
where Z' = (Z1' a Z2' b) = u' VT', and u is a vector of dimension M with ALPHA and BETA in the NL+1 and NL+2 th entries and zeros elsewhere; and the entry b is empty if SQRE = 0.
The singular values of B can be computed using D1, D2, the first components of all the right singular vectors of the lower block, and the last components of all the right singular vectors of the upper block. These components are stored and updated in VF and VL, respectively, in DLASD6. Hence U and VT are not explicitly referenced.
The singular values are stored in D. The algorithm consists of two stages:
The first stage consists of deflating the size of the problem when there are multiple singular values or if there is a zero in the Z vector. For each such occurence the dimension of the secular equation problem is reduced by one. This stage is performed by the routine DLASD7.
The second stage consists of calculating the updated singular values. This is done by finding the roots of the secular equation via the routine DLASD4 (as called by DLASD8). This routine also updates VF and VL and computes the distances between the updated singular values and the old singular values.
DLASD6 is called from DLASDA.
/summary>
Parameters
ICOMPQ (input) INTEGER Specifies whether singular vectors are to be computed in factored form: = 0: Compute singular values only. = 1: Compute singular vectors in factored form as well. /param>
Parameters
NL (input) INTEGER The row dimension of the upper block. NL .GE. 1. /param>
Parameters
NR (input) INTEGER The row dimension of the lower block. NR .GE. 1. /param>
Parameters
SQRE (input) INTEGER = 0: the lower block is an NR-by-NR square matrix. = 1: the lower block is an NR-by-(NR+1) rectangular matrix.
The bidiagonal matrix has row dimension N = NL + NR + 1, and column dimension M = N + SQRE. /param>
Parameters
D (input/output) DOUBLE PRECISION array, dimension (NL+NR+1). On entry D(1:NL,1:NL) contains the singular values of the upper block, and D(NL+2:N) contains the singular values of the lower block. On exit D(1:N) contains the singular values of the modified matrix. /param>
Parameters
VF (input/output) DOUBLE PRECISION array, dimension (M) On entry, VF(1:NL+1) contains the first components of all right singular vectors of the upper block; and VF(NL+2:M) contains the first components of all right singular vectors of the lower block. On exit, VF contains the first components of all right singular vectors of the bidiagonal matrix. /param>
Parameters
VL (input/output) DOUBLE PRECISION array, dimension (M) On entry, VL(1:NL+1) contains the last components of all right singular vectors of the upper block; and VL(NL+2:M) contains the last components of all right singular vectors of the lower block. On exit, VL contains the last components of all right singular vectors of the bidiagonal matrix. /param>
Parameters
ALPHA (input/output) DOUBLE PRECISION Contains the diagonal element associated with the added row. /param>
Parameters
BETA (input/output) DOUBLE PRECISION Contains the off-diagonal element associated with the added row. /param>
Parameters
IDXQ (output) INTEGER array, dimension (N) This contains the permutation which will reintegrate the subproblem just solved back into sorted order, i.e. D(IDXQ(I = 1, N)) will be in ascending order. /param>
Parameters
PERM (output) INTEGER array, dimension (N) The permutations (from deflation and sorting) to be applied to each block. Not referenced if ICOMPQ = 0. /param>
Parameters
GIVPTR (output) INTEGER The number of Givens rotations which took place in this subproblem. Not referenced if ICOMPQ = 0. /param>
Parameters
GIVCOL (output) INTEGER array, dimension (LDGCOL, 2) Each pair of numbers indicates a pair of columns to take place in a Givens rotation. Not referenced if ICOMPQ = 0. /param>
Parameters
LDGCOL (input) INTEGER leading dimension of GIVCOL, must be at least N. /param>
Parameters
GIVNUM (output) DOUBLE PRECISION array, dimension (LDGNUM, 2) Each number indicates the C or S value to be used in the corresponding Givens rotation. Not referenced if ICOMPQ = 0. /param>
Parameters
LDGNUM (input) INTEGER The leading dimension of GIVNUM and POLES, must be at least N. /param>
Parameters
POLES (output) DOUBLE PRECISION array, dimension (LDGNUM, 2) On exit, POLES(1,*) is an array containing the new singular values obtained from solving the secular equation, and POLES(2,*) is an array containing the poles in the secular equation. Not referenced if ICOMPQ = 0. /param>
Parameters
DIFL (output) DOUBLE PRECISION array, dimension (N) On exit, DIFL(I) is the distance between I-th updated (undeflated) singular value and the I-th (undeflated) old singular value. /param>
Parameters
DIFR (output) DOUBLE PRECISION array, dimension (LDGNUM, 2) if ICOMPQ = 1 and dimension (N) if ICOMPQ = 0. On exit, DIFR(I, 1) is the distance between I-th updated (undeflated) singular value and the I+1-th (undeflated) old singular value.
If ICOMPQ = 1, DIFR(1:K,2) is an array containing the normalizing factors for the right singular vector matrix.
See DLASD8 for details on DIFL and DIFR. /param>
Parameters
Z (output) DOUBLE PRECISION array, dimension (M) The first elements of this array contain the components of the deflation-adjusted updating row vector. /param>
Parameters
K (output) INTEGER Contains the dimension of the non-deflated matrix, This is the order of the related secular equation. 1 .LE. K .LE.N. /param>
Parameters
C (output) DOUBLE PRECISION C contains garbage if SQRE =0 and the C-value of a Givens rotation related to the right null space if SQRE = 1. /param>
Parameters
S (output) DOUBLE PRECISION S contains garbage if SQRE =0 and the S-value of a Givens rotation related to the right null space if SQRE = 1. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (4 * M) /param>
Parameters
IWORK (workspace) INTEGER array, dimension (3 * N) /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. .GT. 0: if INFO = 1, an singular value did not converge /param>
References DotNumerics.LinearAlgebra.CSLapack.DLASD6.ONE, DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMRG.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD8.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD7.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLASD6.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASDA.Run().
Member Data Documentation
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DLASD6._dcopy private
_dlamrg
DLAMRG DotNumerics.LinearAlgebra.CSLapack.DLASD6._dlamrg private
_dlascl
DLASCL DotNumerics.LinearAlgebra.CSLapack.DLASD6._dlascl private
_dlasd7
DLASD7 DotNumerics.LinearAlgebra.CSLapack.DLASD6._dlasd7 private
_dlasd8
DLASD8 DotNumerics.LinearAlgebra.CSLapack.DLASD6._dlasd8 private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLASD6._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLASD6.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD6.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLASD6.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASD6.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlasd6.cs