Doc: IGLib EXTENDED: LabexBis.BisCommunicationSettings Class Reference
LabexBis.BisCommunicationSettings Class Reference
Holds settings used by the Labex - Bis communication module.
Public Member Functions
override string ToString ()
void ReadSettingsAppConfig ()
Reads settindgs for communication with Bis from the application settings file.
string IncomingFileName (string Id)
Returns the name of the file in which incoming msg is stored.
string IncomingFileName (string Id, bool AddGuid)
Returns the name of the file in which incoming msg is stored.
string OutgoingFileName (string Id)
Returns the name of the file in which an outgoing msg is stored.
string OutgoingFileName (string Id, bool AddGuid)
Returns the file name for an outgoing msg with the specified Id.
string NullifiedFileName (string Id)
Returns the name of the file in which an nullified message is stored.
string NullifiedFileName (string Id, bool AddGuid)
Returns the file name for a nullified message with the specified Id.
string ExampleFile (MessageType type)
Returns filename of an example msg.
string ForcedFileName (string Id)
Returns the name of the file in which incoming msg should be stored for a file whose receipt confirmation was forced.
string ForcedFileName (string Id, bool AddGuid)
Returns the name of the file in which incoming msg should be stored for a file whose receipt confirmation was forced.
Public Member Functions inherited from IG.Lib.SettingsReaderAppConfig
override string GetSetting (string settingname)
Retrieves the specified setting from the current settings source.
override string GetSetting (string settingname)
Retrieves the specified setting from the current settings source.
Public Member Functions inherited from IG.Lib.SettingsReaderBase
virtual bool GetBooleanSetting (string settingname)
Retrieves the specified boolean setting from the current settings source.
virtual long GetIntegerSetting (string settingname)
Retrieves the specified integer setting from the current settings source. If the specific setting is not specified in the configuration then 0 is returned.
virtual long GetIntegerSetting (string settingname, long defaultvalue)
Retrieves the specified integer setting from the current settings source.
virtual bool GetBooleanSetting (string settingname)
Retrieves the specified boolean setting from the current settings source.
virtual long GetIntegerSetting (string settingname)
Retrieves the specified integer setting from the current settings source. If the specific setting is not specified in the configuration then 0 is returned.
virtual long GetIntegerSetting (string settingname, long defaultvalue)
Retrieves the specified integer setting from the current settings source.
Public Attributes
bool StartCalypsoReceiver = false
int MaxNumMessages = 0
string MessageFile = null
Static Public Attributes
const string SettingName_StartCalypsoReceiver = "StartCalypsoReceiver"
Protected Member Functions
void getsettings ()
Common method used for retrieving the settings. Methods for reading settings form different sources call this method.
string MessageFileName (string leader, string Id, bool AddGuid)
Returns the name of the file where messages are stored.
Protected Member Functions inherited from IG.Lib.SettingsReaderAppConfig
virtual string GetSettingAppConfig (string settingname)
virtual string GetSettingAppConfig (string settingname)
Protected Member Functions inherited from IG.Lib.SettingsReaderBase
bool ToBoolean (string strsetting)
Converts a string representation of a boolean setting to boolean. Strings "true", "yes" and "on" (regardless of capitalization) or non-zero integer representations result to true, anything else (including null or empty string) result in false.
long ToInt (string strsetting)
Converts a string representation of an integer setting to an integer value. If the setting is not defined then 0 is returned.
long ToInt (string strsetting, long defaultvalue)
Converts a string representation of an integer setting to an integer value.
Protected Attributes
bool settingsread = false
Protected Attributes inherited from IG.Lib.SettingsReaderBase
bool _expandEnv = true
Properties
static MsgConst Msg [get]
Gets objects that contains all constants related to communication messages.
static IReporter R [get]
Reporter for this class.
Properties inherited from IG.Lib.SettingsReaderBase
object Lock [get]
ILockable.Lock, gets a public lock for the current object.
virtual bool ExpandEnvironmentVariables [get, set]
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
bool ForceMessageReceiptConfirmation = false
bool DebugCalypsoReceiver = false
string MessageSchemaDir = null
string MessageIncomingDir = null
string ForcedIncomingReceiptsDirectory = "Forced"
string MessageOutgoingDir = null
string MessageServiceUrl = null
string ModelFileObservationOrder
string ModelFileObservationEvent
string ModelFileFinancialTransaction
Static Private Attributes
static IReporter _rep = new ReporterConsole()
const string SettingName_ForceMessageReceiptConfirmation = "ForceMessageReceiptConfirmation"
const string SettingName_MaxNumMessages = "MaxNumMessages"
const string SettingName_DebugCalypsoReceiver = "DebugCalypsoReceiver"
const string SettingName_MessageFile = "MessageFile"
const string SettingName_MessageSchemaDir = "MessageSchemaDir"
const string SettingName_MessageIncomingDir = "MessageIncomingDir"
const string SettingName_MessageOutgoingDir = "MessageOutgoingDir"
const string SettingName_MessageServiceUrl = "MessageServiceUrl"
const string SettingName_ModelFileObservationOrder = "ModelFileObservationOrder"
const string SettingName_ModelFileObservationEvent = "ModelFileObservationEvent"
const string SettingName_ModelFileFinancialTransaction = "ModelFileFinancialTransaction"
Detailed Description
Holds settings used by the Labex - Bis communication module.
Member Function Documentation
ToString()
override string LabexBis.BisCommunicationSettings.ToString () inline
References LabexBis.BisCommunicationSettings.DebugCalypsoReceiver, LabexBis.BisCommunicationSettings.ForceMessageReceiptConfirmation, LabexBis.BisCommunicationSettings.MaxNumMessages, LabexBis.BisCommunicationSettings.MessageFile, LabexBis.BisCommunicationSettings.MessageIncomingDir, LabexBis.BisCommunicationSettings.MessageOutgoingDir, LabexBis.BisCommunicationSettings.MessageSchemaDir, LabexBis.BisCommunicationSettings.MessageServiceUrl, LabexBis.BisCommunicationSettings.ModelFileFinancialTransaction, LabexBis.BisCommunicationSettings.ModelFileObservationEvent, LabexBis.BisCommunicationSettings.ModelFileObservationOrder, LabexBis.BisCommunicationSettings.SettingName_DebugCalypsoReceiver, LabexBis.BisCommunicationSettings.SettingName_ForceMessageReceiptConfirmation, LabexBis.BisCommunicationSettings.SettingName_MaxNumMessages, LabexBis.BisCommunicationSettings.SettingName_MessageFile, LabexBis.BisCommunicationSettings.SettingName_MessageIncomingDir, LabexBis.BisCommunicationSettings.SettingName_MessageOutgoingDir, LabexBis.BisCommunicationSettings.SettingName_MessageSchemaDir, LabexBis.BisCommunicationSettings.SettingName_MessageServiceUrl, LabexBis.BisCommunicationSettings.SettingName_ModelFileFinancialTransaction, LabexBis.BisCommunicationSettings.SettingName_ModelFileObservationEvent, LabexBis.BisCommunicationSettings.SettingName_ModelFileObservationOrder, LabexBis.BisCommunicationSettings.SettingName_StartCalypsoReceiver, and LabexBis.BisCommunicationSettings.StartCalypsoReceiver.
Referenced by IGTest.ProgramIGTest.ReceiveSpecimenObservationOrder(), IGTest.ProgramIGTest.TestCalypsoWs(), IGTest.ProgramIGTest.TestcalypsoWsSimple(), IGTest.ProgramIGTest.TestMsgFinancialTransaction(), and IGTest.ProgramIGTest.TestMsgObservationEvent().
getsettings()
void LabexBis.BisCommunicationSettings.getsettings () inline protected
Common method used for retrieving the settings. Methods for reading settings form different sources call this method.
References LabexBis.BisCommunicationSettings.DebugCalypsoReceiver, LabexBis.BisCommunicationSettings.ForceMessageReceiptConfirmation, IG.Lib.SettingsReaderBase.GetBooleanSetting(), IG.Lib.SettingsReaderBase.GetIntegerSetting(), IG.Lib.SettingsReaderAppConfig.GetSetting(), LabexBis.BisCommunicationSettings.MaxNumMessages, LabexBis.BisCommunicationSettings.MessageFile, LabexBis.BisCommunicationSettings.MessageIncomingDir, LabexBis.BisCommunicationSettings.MessageOutgoingDir, LabexBis.BisCommunicationSettings.MessageSchemaDir, LabexBis.BisCommunicationSettings.MessageServiceUrl, LabexBis.BisCommunicationSettings.ModelFileFinancialTransaction, LabexBis.BisCommunicationSettings.ModelFileObservationEvent, LabexBis.BisCommunicationSettings.ModelFileObservationOrder, LabexBis.BisCommunicationSettings.SettingName_DebugCalypsoReceiver, LabexBis.BisCommunicationSettings.SettingName_ForceMessageReceiptConfirmation, LabexBis.BisCommunicationSettings.SettingName_MaxNumMessages, LabexBis.BisCommunicationSettings.SettingName_MessageFile, LabexBis.BisCommunicationSettings.SettingName_MessageIncomingDir, LabexBis.BisCommunicationSettings.SettingName_MessageOutgoingDir, LabexBis.BisCommunicationSettings.SettingName_MessageSchemaDir, LabexBis.BisCommunicationSettings.SettingName_MessageServiceUrl, LabexBis.BisCommunicationSettings.SettingName_ModelFileFinancialTransaction, LabexBis.BisCommunicationSettings.SettingName_ModelFileObservationEvent, LabexBis.BisCommunicationSettings.SettingName_ModelFileObservationOrder, LabexBis.BisCommunicationSettings.SettingName_StartCalypsoReceiver, LabexBis.BisCommunicationSettings.settingsread, and LabexBis.BisCommunicationSettings.StartCalypsoReceiver.
Referenced by LabexBis.BisCommunicationSettings.ExampleFile(), LabexBis.BisCommunicationSettings.ForcedFileName(), LabexBis.BisCommunicationSettings.IncomingFileName(), LabexBis.BisCommunicationSettings.NullifiedFileName(), LabexBis.BisCommunicationSettings.OutgoingFileName(), and LabexBis.BisCommunicationSettings.ReadSettingsAppConfig().
ReadSettingsAppConfig()
void LabexBis.BisCommunicationSettings.ReadSettingsAppConfig () inline
Reads settindgs for communication with Bis from the application settings file.
References LabexBis.BisCommunicationSettings.getsettings(), and IG.Lib.SettingsReaderBase.lockobj.
Referenced by IGTest.ProgramIGTest.ReceiveSpecimenObservationOrder(), IGTest.ProgramIGTest.TestCalypsoWs(), IGTest.ProgramIGTest.TestcalypsoWsSimple(), IGTest.ProgramIGTest.TestMsgFinancialTransaction(), IGTest.ProgramIGTest.TestMsgObservationEvent(), IGTest.ProgramIGTest.TestMsgObservationOrder(), IGTest.ProgramIGTest.TestMsgObservationOrderNullify(), and IGTest.ProgramIGTest.TestMsgObservationOrderNullifySend().
MessageFileName()
string LabexBis.BisCommunicationSettings.MessageFileName (string leader, string Id, bool AddGuid) inline protected
Returns the name of the file where messages are stored.
Parameters
leader The leading string of the file name, such as "Incoming".
Id Id incorporated in the file name.
AddGuid If true then a global unique string is included in file name.
Returns
Composed file name.
References IG.Lib.IReporterBase.Depth, LabexBis.BisCommunicationSettings.Msg, LabexBis.BisCommunicationSettings.R, IG.Lib.IReporterBase.ReportInfo(), IG.Lib.MsgConst.TimeStamp(), and IG.Lib.IReporterBase.TreatInfo.
Referenced by LabexBis.BisCommunicationSettings.ForcedFileName(), LabexBis.BisCommunicationSettings.IncomingFileName(), LabexBis.BisCommunicationSettings.NullifiedFileName(), and LabexBis.BisCommunicationSettings.OutgoingFileName().
IncomingFileName() [1/2]
string LabexBis.BisCommunicationSettings.IncomingFileName (string Id) inline
Returns the name of the file in which incoming msg is stored.
Parameters
Id ID of the incoming msg.
Referenced by LabexBis.Calypso.GetMessage(), LabexBis.Calypso.SaveIncomingMessage(), and IGTest.ProgramIGTest.TestcalypsoWsSimple().
IncomingFileName() [2/2]
string LabexBis.BisCommunicationSettings.IncomingFileName (string Id, bool AddGuid) inline
Returns the name of the file in which incoming msg is stored.
Parameters
Id ID of the incoming msg.
AddGuid Specifies whether or not a GUID is added to msg filenames.
References IG.Lib.IReporterBase.Depth, LabexBis.BisCommunicationSettings.getsettings(), LabexBis.BisCommunicationSettings.MessageFileName(), LabexBis.BisCommunicationSettings.MessageIncomingDir, LabexBis.BisCommunicationSettings.R, IG.Lib.IReporterBase.ReportInfo(), LabexBis.BisCommunicationSettings.settingsread, and IG.Lib.IReporterBase.TreatInfo.
OutgoingFileName() [1/2]
string LabexBis.BisCommunicationSettings.OutgoingFileName (string Id) inline
Returns the name of the file in which an outgoing msg is stored.
Parameters
Id ID of the outgoing msg.
Referenced by LabexBis.Calypso.SendMessage().
OutgoingFileName() [2/2]
string LabexBis.BisCommunicationSettings.OutgoingFileName (string Id, bool AddGuid) inline
Returns the file name for an outgoing msg with the specified Id.
Parameters
Id Id of the msg.
Returns
Name of the file where outgoing msg is stored.
References IG.Lib.IReporterBase.Depth, LabexBis.BisCommunicationSettings.getsettings(), LabexBis.BisCommunicationSettings.MessageFileName(), LabexBis.BisCommunicationSettings.MessageOutgoingDir, LabexBis.BisCommunicationSettings.R, IG.Lib.IReporterBase.ReportInfo(), LabexBis.BisCommunicationSettings.settingsread, and IG.Lib.IReporterBase.TreatInfo.
NullifiedFileName() [1/2]
string LabexBis.BisCommunicationSettings.NullifiedFileName (string Id) inline
Returns the name of the file in which an nullified message is stored.
Parameters
Id ID of the outgoing msg.
NullifiedFileName() [2/2]
string LabexBis.BisCommunicationSettings.NullifiedFileName (string Id, bool AddGuid) inline
Returns the file name for a nullified message with the specified Id.
Parameters
Id Id of the msg.
Returns
Name of the file where outgoing msg is stored.
References IG.Lib.IReporterBase.Depth, LabexBis.BisCommunicationSettings.getsettings(), LabexBis.BisCommunicationSettings.MessageFileName(), LabexBis.BisCommunicationSettings.MessageOutgoingDir, LabexBis.BisCommunicationSettings.R, IG.Lib.IReporterBase.ReportInfo(), LabexBis.BisCommunicationSettings.settingsread, and IG.Lib.IReporterBase.TreatInfo.
ExampleFile()
string LabexBis.BisCommunicationSettings.ExampleFile (MessageType type) inline
Returns filename of an example msg.
References IG.Lib.IReporterBase.Depth, LabexBis.BisCommunicationSettings.getsettings(), LabexBis.BisCommunicationSettings.MessageSchemaDir, LabexBis.BisCommunicationSettings.R, IG.Lib.IReporterBase.ReportInfo(), LabexBis.BisCommunicationSettings.settingsread, and IG.Lib.IReporterBase.TreatInfo.
Referenced by IGTest.ProgramIGTest.TestMsgFinancialTransaction(), IGTest.ProgramIGTest.TestMsgObservationEvent(), IGTest.ProgramIGTest.TestMsgObservationOrder(), and IGTest.ProgramIGTest.TestMsgObservationOrderNullify().
ForcedFileName() [1/2]
string LabexBis.BisCommunicationSettings.ForcedFileName (string Id) inline
Returns the name of the file in which incoming msg should be stored for a file whose receipt confirmation was forced.
Parameters
Id ID of the incoming msg.
ForcedFileName() [2/2]
string LabexBis.BisCommunicationSettings.ForcedFileName (string Id, bool AddGuid) inline
Returns the name of the file in which incoming msg should be stored for a file whose receipt confirmation was forced.
Parameters
Id ID of the incoming msg.
AddGuid Specifies whether or not a GUID is added to msg filenames.
References IG.Lib.IReporterBase.Depth, LabexBis.BisCommunicationSettings.ForcedIncomingReceiptsDirectory, LabexBis.BisCommunicationSettings.getsettings(), LabexBis.BisCommunicationSettings.MessageFileName(), LabexBis.BisCommunicationSettings.MessageIncomingDir, LabexBis.BisCommunicationSettings.R, IG.Lib.IReporterBase.ReportInfo(), LabexBis.BisCommunicationSettings.settingsread, and IG.Lib.IReporterBase.TreatInfo.
Member Data Documentation
_rep
IReporter LabexBis.BisCommunicationSettings._rep = new ReporterConsole() static private
SettingName_StartCalypsoReceiver
const string LabexBis.BisCommunicationSettings.SettingName_StartCalypsoReceiver = "StartCalypsoReceiver" static
Referenced by LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
SettingName_ForceMessageReceiptConfirmation
const string LabexBis.BisCommunicationSettings.SettingName_ForceMessageReceiptConfirmation = "ForceMessageReceiptConfirmation" static private
Referenced by LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
SettingName_MaxNumMessages
const string LabexBis.BisCommunicationSettings.SettingName_MaxNumMessages = "MaxNumMessages" static private
Referenced by LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
SettingName_DebugCalypsoReceiver
const string LabexBis.BisCommunicationSettings.SettingName_DebugCalypsoReceiver = "DebugCalypsoReceiver" static private
Referenced by LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
SettingName_MessageFile
const string LabexBis.BisCommunicationSettings.SettingName_MessageFile = "MessageFile" static private
Referenced by LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
SettingName_MessageSchemaDir
const string LabexBis.BisCommunicationSettings.SettingName_MessageSchemaDir = "MessageSchemaDir" static private
Referenced by LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
SettingName_MessageIncomingDir
const string LabexBis.BisCommunicationSettings.SettingName_MessageIncomingDir = "MessageIncomingDir" static private
Referenced by LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
SettingName_MessageOutgoingDir
const string LabexBis.BisCommunicationSettings.SettingName_MessageOutgoingDir = "MessageOutgoingDir" static private
Referenced by LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
SettingName_MessageServiceUrl
const string LabexBis.BisCommunicationSettings.SettingName_MessageServiceUrl = "MessageServiceUrl" static private
Referenced by LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
SettingName_ModelFileObservationOrder
const string LabexBis.BisCommunicationSettings.SettingName_ModelFileObservationOrder = "ModelFileObservationOrder" static private
Referenced by LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
SettingName_ModelFileObservationEvent
const string LabexBis.BisCommunicationSettings.SettingName_ModelFileObservationEvent = "ModelFileObservationEvent" static private
Referenced by LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
SettingName_ModelFileFinancialTransaction
const string LabexBis.BisCommunicationSettings.SettingName_ModelFileFinancialTransaction = "ModelFileFinancialTransaction" static private
Referenced by LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
StartCalypsoReceiver
bool LabexBis.BisCommunicationSettings.StartCalypsoReceiver = false
Referenced by LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
ForceMessageReceiptConfirmation
bool LabexBis.BisCommunicationSettings.ForceMessageReceiptConfirmation = false private
Referenced by LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
DebugCalypsoReceiver
bool LabexBis.BisCommunicationSettings.DebugCalypsoReceiver = false private
Referenced by LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
MaxNumMessages
int LabexBis.BisCommunicationSettings.MaxNumMessages = 0
Referenced by LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
MessageFile
string LabexBis.BisCommunicationSettings.MessageFile = null
Referenced by LabexBis.BisCommunicationSettings.getsettings(), IGTest.ProgramIGTest.TestCalypsoWs(), and LabexBis.BisCommunicationSettings.ToString().
MessageSchemaDir
string LabexBis.BisCommunicationSettings.MessageSchemaDir = null private
Referenced by LabexBis.BisCommunicationSettings.ExampleFile(), LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
MessageIncomingDir
string LabexBis.BisCommunicationSettings.MessageIncomingDir = null private
Referenced by LabexBis.BisCommunicationSettings.ForcedFileName(), LabexBis.BisCommunicationSettings.getsettings(), LabexBis.BisCommunicationSettings.IncomingFileName(), and LabexBis.BisCommunicationSettings.ToString().
ForcedIncomingReceiptsDirectory
string LabexBis.BisCommunicationSettings.ForcedIncomingReceiptsDirectory = "Forced" private
Referenced by LabexBis.BisCommunicationSettings.ForcedFileName().
MessageOutgoingDir
string LabexBis.BisCommunicationSettings.MessageOutgoingDir = null private
Referenced by LabexBis.BisCommunicationSettings.getsettings(), LabexBis.BisCommunicationSettings.NullifiedFileName(), LabexBis.BisCommunicationSettings.OutgoingFileName(), and LabexBis.BisCommunicationSettings.ToString().
MessageServiceUrl
string LabexBis.BisCommunicationSettings.MessageServiceUrl = null private
Referenced by LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
ModelFileObservationOrder
string LabexBis.BisCommunicationSettings.ModelFileObservationOrder private
Referenced by LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
ModelFileObservationEvent
string LabexBis.BisCommunicationSettings.ModelFileObservationEvent private
Referenced by LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
ModelFileFinancialTransaction
string LabexBis.BisCommunicationSettings.ModelFileFinancialTransaction private
Referenced by LabexBis.BisCommunicationSettings.getsettings(), and LabexBis.BisCommunicationSettings.ToString().
settingsread
bool LabexBis.BisCommunicationSettings.settingsread = false protected
Referenced by LabexBis.BisCommunicationSettings.ExampleFile(), LabexBis.BisCommunicationSettings.ForcedFileName(), LabexBis.BisCommunicationSettings.getsettings(), LabexBis.BisCommunicationSettings.IncomingFileName(), LabexBis.BisCommunicationSettings.NullifiedFileName(), and LabexBis.BisCommunicationSettings.OutgoingFileName().
Property Documentation
Msg
MsgConst LabexBis.BisCommunicationSettings.Msg static get protected
Gets objects that contains all constants related to communication messages.
Referenced by LabexBis.BisCommunicationSettings.MessageFileName().
R
IReporter LabexBis.BisCommunicationSettings.R static get
Reporter for this class.
Referenced by LabexBis.BisCommunicationSettings.ExampleFile(), LabexBis.BisCommunicationSettings.ForcedFileName(), LabexBis.BisCommunicationSettings.IncomingFileName(), LabexBis.BisCommunicationSettings.MessageFileName(), LabexBis.BisCommunicationSettings.NullifiedFileName(), and LabexBis.BisCommunicationSettings.OutgoingFileName().
The documentation for this class was generated from the following file:
igtest/tmp_prem/prlab/LabexBis/WSBis.cs