Doc: IGLib EXTENDED: NUnit.Engine.Services.Tests.ResultServiceTests Class Reference
NUnit.Engine.Services.Tests.ResultServiceTests Class Reference
Public Member Functions
void CreateService ()
void ServiceIsStarted ()
void AvailableFormats ()
string CanGetWriter (string format, object[] args)
void NUnit3Format_NonExistentTransform_ThrowsArgumentException ()
void NUnit3Format_NullArgument_ThrowsArgumentNullException ()
Private Attributes
ResultService _resultService
Member Function Documentation
CreateService()
void NUnit.Engine.Services.Tests.ResultServiceTests.CreateService () inline
References NUnit.Engine.Services.Tests.ResultServiceTests._resultService.
ServiceIsStarted()
void NUnit.Engine.Services.Tests.ResultServiceTests.ServiceIsStarted () inline
References NUnit.Engine.Services.Tests.ResultServiceTests._resultService, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Services.Service.Status, and NUnit.Framework.Assert.That().
AvailableFormats()
void NUnit.Engine.Services.Tests.ResultServiceTests.AvailableFormats () inline
References NUnit.Engine.Services.Tests.ResultServiceTests._resultService, NUnit.Framework.Is.EquivalentTo(), NUnit.Engine.Services.ResultService.Formats, and NUnit.Framework.Assert.That().
CanGetWriter()
string NUnit.Engine.Services.Tests.ResultServiceTests.CanGetWriter (string format, object[] args) inline
References NUnit.Engine.Services.Tests.ResultServiceTests._resultService, NUnit.Engine.Services.ResultService.GetResultWriter(), and NUnit.Framework.Assert.NotNull().
NUnit3Format_NonExistentTransform_ThrowsArgumentException()
void NUnit.Engine.Services.Tests.ResultServiceTests.NUnit3Format_NonExistentTransform_ThrowsArgumentException () inline
References NUnit.Engine.Services.Tests.ResultServiceTests._resultService, NUnit.Framework.Throws.ArgumentException, NUnit.Engine.Services.ResultService.GetResultWriter(), and NUnit.Framework.Assert.That().
NUnit3Format_NullArgument_ThrowsArgumentNullException()
void NUnit.Engine.Services.Tests.ResultServiceTests.NUnit3Format_NullArgument_ThrowsArgumentNullException () inline
References NUnit.Engine.Services.Tests.ResultServiceTests._resultService, NUnit.Engine.Services.ResultService.GetResultWriter(), NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
Member Data Documentation
_resultService
ResultService NUnit.Engine.Services.Tests.ResultServiceTests._resultService private
Referenced by NUnit.Engine.Services.Tests.ResultServiceTests.AvailableFormats(), NUnit.Engine.Services.Tests.ResultServiceTests.CanGetWriter(), NUnit.Engine.Services.Tests.ResultServiceTests.CreateService(), NUnit.Engine.Services.Tests.ResultServiceTests.NUnit3Format_NonExistentTransform_ThrowsArgumentException(), NUnit.Engine.Services.Tests.ResultServiceTests.NUnit3Format_NullArgument_ThrowsArgumentNullException(), and NUnit.Engine.Services.Tests.ResultServiceTests.ServiceIsStarted().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Services/ResultServiceTests.cs