Doc: IGLib EXTENDED: NUnit.Framework.Tests.TestContextOneTimeTearDownTests Class Reference
NUnit.Framework.Tests.TestContextOneTimeTearDownTests Class Reference
Public Member Functions
void TestTruth ()
void TestFalsehood ()
void TestExplicit ()
void OneTimeTearDown ()
Member Function Documentation
TestTruth()
void NUnit.Framework.Tests.TestContextOneTimeTearDownTests.TestTruth () inline
References NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
TestFalsehood()
void NUnit.Framework.Tests.TestContextOneTimeTearDownTests.TestFalsehood () inline
References NUnit.Framework.Is.False, and NUnit.Framework.Assert.That().
TestExplicit()
void NUnit.Framework.Tests.TestContextOneTimeTearDownTests.TestExplicit () inline
References NUnit.Framework.Assert.Pass().
OneTimeTearDown()
void NUnit.Framework.Tests.TestContextOneTimeTearDownTests.OneTimeTearDown () inline
References NUnit.Framework.TestContext.CurrentContext, NUnit.Framework.Is.EqualTo(), NUnit.Framework.TestContext.ResultAdapter.FailCount, NUnit.Framework.TestContext.TestAdapter.Name, NUnit.Framework.Is.Not, NUnit.Framework.TestContext.ResultAdapter.Outcome, NUnit.Framework.TestContext.ResultAdapter.PassCount, NUnit.Framework.TestContext.Result, NUnit.Framework.TestContext.ResultAdapter.SkipCount, NUnit.Framework.Interfaces.ResultState.Success, NUnit.Framework.TestContext.Test, and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/TestContextTests.cs