Doc: IGLib EXTENDED: alglib.testalglibbasicsunit Class Reference
alglib.testalglibbasicsunit Class Reference
Classes
class poolrec1
class poolrec2
class poolsummand
class rec1
class rec4serialization
Static Public Member Functions
static void rec4serializationalloc (alglib.serializer s, rec4serialization v)
static void rec4serializationserialize (alglib.serializer s, rec4serialization v)
static void rec4serializationunserialize (alglib.serializer s, rec4serialization v)
static bool testalglibbasics (bool silent)
static void rec4serializationalloc (alglib.serializer s, rec4serialization v)
static void rec4serializationserialize (alglib.serializer s, rec4serialization v)
static void rec4serializationunserialize (alglib.serializer s, rec4serialization v)
static bool testalglibbasics (bool silent)
static bool _pexec_testalglibbasics (bool silent)
Static Private Member Functions
static bool testcomplexarithmetics (bool silent)
static bool testieeespecial (bool silent)
static bool testswapfunctions (bool silent)
static bool teststandardfunctions (bool silent)
static bool testserializationfunctions (bool silent)
static bool testcomplexarithmetics (bool silent)
static bool testieeespecial (bool silent)
static bool testswapfunctions (bool silent)
static bool teststandardfunctions (bool silent)
static bool testserializationfunctions (bool silent)
static void createpoolandrecords (poolrec2 seedrec2, poolrec2 seedrec2copy, alglib.smp.shared_pool pool)
static bool sharedpoolerrors ()
static bool testsharedpool (bool silent)
static void testsort0func (int[] a, int[] buf, int idx0, int idx2)
static bool performtestsort0 ()
static void testsort1func (int[] a, int[] buf, int idx0, int idx2, bool usesmp)
static bool performtestsort1 ()
static void testsort2func (int[] a, int[] buf, int idx0, int idx2)
static bool performtestsort2 ()
static bool performtestpoolsum ()
static void parallelpoolsum (alglib.smp.shared_pool sumpool, int ind0, int ind1)
static void mergesortedarrays (int[] a, int[] buf, int idx0, int idx1, int idx2)
static bool testsmp (bool silent)
Member Function Documentation
rec4serializationalloc() [1/2]
static void alglib.testalglibbasicsunit.rec4serializationalloc (alglib.serializer s, rec4serialization v) inline static
References alglib.testalglibbasicsunit.rec4serialization.b, alglib.testalglibbasicsunit.rec4serialization.i, and alglib.testalglibbasicsunit.rec4serialization.r.
Referenced by alglib.testalglibbasicsunit.testserializationfunctions().
rec4serializationserialize() [1/2]
static void alglib.testalglibbasicsunit.rec4serializationserialize (alglib.serializer s, rec4serialization v) inline static
References alglib.testalglibbasicsunit.rec4serialization.b, alglib.testalglibbasicsunit.rec4serialization.i, and alglib.testalglibbasicsunit.rec4serialization.r.
Referenced by alglib.testalglibbasicsunit.testserializationfunctions().
rec4serializationunserialize() [1/2]
static void alglib.testalglibbasicsunit.rec4serializationunserialize (alglib.serializer s, rec4serialization v) inline static
References alglib.testalglibbasicsunit.rec4serialization.b, alglib.testalglibbasicsunit.rec4serialization.i, and alglib.testalglibbasicsunit.rec4serialization.r.
Referenced by alglib.testalglibbasicsunit.testserializationfunctions().
testalglibbasics() [1/2]
static bool alglib.testalglibbasicsunit.testalglibbasics (bool silent) inline static
References alglib.testalglibbasicsunit.testcomplexarithmetics(), alglib.testalglibbasicsunit.testieeespecial(), alglib.testalglibbasicsunit.testserializationfunctions(), alglib.testalglibbasicsunit.teststandardfunctions(), and alglib.testalglibbasicsunit.testswapfunctions().
Referenced by alglib.testalglibbasicsunit._pexec_testalglibbasics(), and _Test.Main().
testcomplexarithmetics() [1/2]
static bool alglib.testalglibbasicsunit.testcomplexarithmetics (bool silent) inline static private
References alglib.math.abscomplex(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.math.sqr(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.testalglibbasicsunit.testalglibbasics().
testieeespecial() [1/2]
static bool alglib.testalglibbasicsunit.testieeespecial (bool silent) inline static private
References alglib.math.isfinite(), alglib.math.maxrealnumber, and alglib.math.minrealnumber.
Referenced by alglib.testalglibbasicsunit.testalglibbasics().
testswapfunctions() [1/2]
static bool alglib.testalglibbasicsunit.testswapfunctions (bool silent) inline static private
Referenced by alglib.testalglibbasicsunit.testalglibbasics().
teststandardfunctions() [1/2]
static bool alglib.testalglibbasicsunit.teststandardfunctions (bool silent) inline static private
Referenced by alglib.testalglibbasicsunit.testalglibbasics().
testserializationfunctions() [1/2]
static bool alglib.testalglibbasicsunit.testserializationfunctions (bool silent) inline static private
References alglib.serializer.alloc_start(), alglib.testalglibbasicsunit.rec4serialization.b, alglib.serializer.get_string(), alglib.testalglibbasicsunit.rec4serialization.i, alglib.testalglibbasicsunit.rec4serialization.r, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testalglibbasicsunit.rec4serializationalloc(), alglib.testalglibbasicsunit.rec4serializationserialize(), alglib.testalglibbasicsunit.rec4serializationunserialize(), alglib.serializer.sstart_str(), alglib.serializer.stop(), and alglib.serializer.ustart_str().
Referenced by alglib.testalglibbasicsunit.testalglibbasics().
rec4serializationalloc() [2/2]
static void alglib.testalglibbasicsunit.rec4serializationalloc (alglib.serializer s, rec4serialization v) inline static
rec4serializationserialize() [2/2]
static void alglib.testalglibbasicsunit.rec4serializationserialize (alglib.serializer s, rec4serialization v) inline static
rec4serializationunserialize() [2/2]
static void alglib.testalglibbasicsunit.rec4serializationunserialize (alglib.serializer s, rec4serialization v) inline static
testalglibbasics() [2/2]
static bool alglib.testalglibbasicsunit.testalglibbasics (bool silent) inline static
References alglib.testalglibbasicsunit.testcomplexarithmetics(), alglib.testalglibbasicsunit.testieeespecial(), alglib.testalglibbasicsunit.testserializationfunctions(), alglib.testalglibbasicsunit.testsharedpool(), alglib.testalglibbasicsunit.testsmp(), alglib.testalglibbasicsunit.teststandardfunctions(), and alglib.testalglibbasicsunit.testswapfunctions().
_pexec_testalglibbasics()
static bool alglib.testalglibbasicsunit._pexec_testalglibbasics (bool silent) inline static
References alglib.testalglibbasicsunit.testalglibbasics().
Referenced by _Test.Main().
testcomplexarithmetics() [2/2]
static bool alglib.testalglibbasicsunit.testcomplexarithmetics (bool silent) inline static private
References alglib.math.abscomplex(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.math.sqr(), alglib.complex.x, and alglib.complex.y.
testieeespecial() [2/2]
static bool alglib.testalglibbasicsunit.testieeespecial (bool silent) inline static private
References alglib.math.isfinite(), alglib.math.maxrealnumber, and alglib.math.minrealnumber.
testswapfunctions() [2/2]
static bool alglib.testalglibbasicsunit.testswapfunctions (bool silent) inline static private
teststandardfunctions() [2/2]
static bool alglib.testalglibbasicsunit.teststandardfunctions (bool silent) inline static private
testserializationfunctions() [2/2]
static bool alglib.testalglibbasicsunit.testserializationfunctions (bool silent) inline static private
References alglib.serializer.alloc_start(), alglib.serializer.get_string(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.testalglibbasicsunit.rec4serializationalloc(), alglib.testalglibbasicsunit.rec4serializationserialize(), alglib.testalglibbasicsunit.rec4serializationunserialize(), alglib.serializer.sstart_str(), alglib.serializer.stop(), and alglib.serializer.ustart_str().
createpoolandrecords()
static void alglib.testalglibbasicsunit.createpoolandrecords (poolrec2 seedrec2, poolrec2 seedrec2copy, alglib.smp.shared_pool pool) inline static private
References alglib.smp.ae_shared_pool_set_seed(), alglib.testalglibbasicsunit.poolrec1.bval, alglib.testalglibbasicsunit.poolrec2.bval, alglib.testalglibbasicsunit.poolrec1.cval, alglib.testalglibbasicsunit.poolrec1.i1val, alglib.testalglibbasicsunit.poolrec1.ival, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testalglibbasicsunit.poolrec2.recval, alglib.testalglibbasicsunit.poolrec1.rval, alglib.complex.x, and alglib.complex.y.
Referenced by alglib.testalglibbasicsunit.sharedpoolerrors().
sharedpoolerrors()
static bool alglib.testalglibbasicsunit.sharedpoolerrors () inline static private
References alglib.smp.ae_shared_pool_clear_recycled(), alglib.smp.ae_shared_pool_is_initialized(), alglib.smp.ae_shared_pool_reset(), alglib.smp.ae_shared_pool_set_seed(), alglib.testalglibbasicsunit.poolrec2.bval, alglib.testalglibbasicsunit.createpoolandrecords(), alglib.testalglibbasicsunit.poolrec1.i1val, alglib.testalglibbasicsunit.poolrec1.ival, alglib.testalglibbasicsunit.poolrec2.pool, and alglib.testalglibbasicsunit.poolrec2.recval.
Referenced by alglib.testalglibbasicsunit.testsharedpool().
testsharedpool()
static bool alglib.testalglibbasicsunit.testsharedpool (bool silent) inline static private
References alglib.testalglibbasicsunit.sharedpoolerrors().
Referenced by alglib.testalglibbasicsunit.testalglibbasics().
testsort0func()
static void alglib.testalglibbasicsunit.testsort0func (int[] a, int[] buf, int idx0, int idx2) inline static private
References alglib.testalglibbasicsunit.mergesortedarrays().
Referenced by alglib.testalglibbasicsunit.performtestsort0(), and alglib.testalglibbasicsunit.testsort2func().
performtestsort0()
static bool alglib.testalglibbasicsunit.performtestsort0 () inline static private
References alglib.math.randominteger(), and alglib.testalglibbasicsunit.testsort0func().
Referenced by alglib.testalglibbasicsunit.testsmp().
testsort1func()
static void alglib.testalglibbasicsunit.testsort1func (int[] a, int[] buf, int idx0, int idx2, bool usesmp) inline static private
References alglib.testalglibbasicsunit.mergesortedarrays().
Referenced by alglib.testalglibbasicsunit.performtestsort1().
performtestsort1()
static bool alglib.testalglibbasicsunit.performtestsort1 () inline static private
References alglib.math.randominteger(), and alglib.testalglibbasicsunit.testsort1func().
Referenced by alglib.testalglibbasicsunit.testsmp().
testsort2func()
static void alglib.testalglibbasicsunit.testsort2func (int[] a, int[] buf, int idx0, int idx2) inline static private
References alglib.testalglibbasicsunit.mergesortedarrays(), alglib.math.randominteger(), and alglib.testalglibbasicsunit.testsort0func().
Referenced by alglib.testalglibbasicsunit.performtestsort2().
performtestsort2()
static bool alglib.testalglibbasicsunit.performtestsort2 () inline static private
References alglib.math.randominteger(), and alglib.testalglibbasicsunit.testsort2func().
Referenced by alglib.testalglibbasicsunit.testsmp().
performtestpoolsum()
static bool alglib.testalglibbasicsunit.performtestpoolsum () inline static private
References alglib.smp.ae_shared_pool_set_seed(), alglib.testalglibbasicsunit.parallelpoolsum(), and alglib.testalglibbasicsunit.poolsummand.val.
Referenced by alglib.testalglibbasicsunit.testsmp().
parallelpoolsum()
static void alglib.testalglibbasicsunit.parallelpoolsum (alglib.smp.shared_pool sumpool, int ind0, int ind1) inline static private
Referenced by alglib.testalglibbasicsunit.performtestpoolsum().
mergesortedarrays()
static void alglib.testalglibbasicsunit.mergesortedarrays (int[] a, int[] buf, int idx0, int idx1, int idx2) inline static private
Referenced by alglib.testalglibbasicsunit.testsort0func(), alglib.testalglibbasicsunit.testsort1func(), and alglib.testalglibbasicsunit.testsort2func().
testsmp()
static bool alglib.testalglibbasicsunit.testsmp (bool silent) inline static private
References alglib.testalglibbasicsunit.performtestpoolsum(), alglib.testalglibbasicsunit.performtestsort0(), alglib.testalglibbasicsunit.performtestsort1(), and alglib.testalglibbasicsunit.performtestsort2().
Referenced by alglib.testalglibbasicsunit.testalglibbasics().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs