Doc: IGLib EXTENDED: DotNetMatrix.examples.MagicSquareExample Class Reference
DotNetMatrix.examples.MagicSquareExample Class Reference
Example of use of GeneralMatrix Class, featuring magic squares. *
Static Public Member Functions
static GeneralMatrix magic (int n)
Generate magic square test matrix. *
static System.String fixedWidthDoubletoString (double x, int w, int d)
Format double with Fw.d. *
static System.String fixedWidthIntegertoString (int n, int w)
Format integer with Iw. *
static void Main (System.String[] argv)
static GeneralMatrix magic (int n)
Generate magic square test matrix. *
static System.String fixedWidthDoubletoString (double x, int w, int d)
Format double with Fw.d. *
static System.String fixedWidthIntegertoString (int n, int w)
Format integer with Iw. *
static void Main (System.String[] argv)
Static Private Member Functions
static void print (System.String s)
Shorten spelling of print. *
static void print (System.String s)
Shorten spelling of print. *
Detailed Description
Example of use of GeneralMatrix Class, featuring magic squares. *
Member Function Documentation
magic() [1/2]
static GeneralMatrix DotNetMatrix.examples.MagicSquareExample.magic (int n) inline static
Generate magic square test matrix. *
Referenced by DotNetMatrix.examples.MagicSquareExample.magic(), and DotNetMatrix.examples.MagicSquareExample.Main().
print() [1/2]
static void DotNetMatrix.examples.MagicSquareExample.print (System.String s) inline static private
Shorten spelling of print. *
Referenced by DotNetMatrix.examples.MagicSquareExample.Main().
fixedWidthDoubletoString() [1/2]
static System.String DotNetMatrix.examples.MagicSquareExample.fixedWidthDoubletoString (double x, int w, int d) inline static
Format double with Fw.d. *
Referenced by DotNetMatrix.examples.MagicSquareExample.Main().
fixedWidthIntegertoString() [1/2]
static System.String DotNetMatrix.examples.MagicSquareExample.fixedWidthIntegertoString (int n, int w) inline static
Format integer with Iw. *
Referenced by DotNetMatrix.examples.MagicSquareExample.Main().
Main() [1/2]
static void DotNetMatrix.examples.MagicSquareExample.Main (System.String[] argv) inline static
References DotNetMatrix.examples.MagicSquareExample.fixedWidthDoubletoString(), DotNetMatrix.examples.MagicSquareExample.fixedWidthIntegertoString(), DotNetMatrix.LUDecomposition.L, DotNetMatrix.examples.MagicSquareExample.magic(), DotNetMatrix.GeneralMatrix.Multiply(), DotNetMatrix.GeneralMatrix.Norm1(), DotNetMatrix.LUDecomposition.Pivot, DotNetMatrix.examples.MagicSquareExample.print(), DotNetMatrix.QRDecomposition.Q, DotNetMatrix.QRDecomposition.R, DotNetMatrix.GeneralMatrix.Subtract(), and DotNetMatrix.LUDecomposition.U.
magic() [2/2]
static GeneralMatrix DotNetMatrix.examples.MagicSquareExample.magic (int n) inline static
Generate magic square test matrix. *
References DotNetMatrix.examples.MagicSquareExample.magic().
print() [2/2]
static void DotNetMatrix.examples.MagicSquareExample.print (System.String s) inline static private
Shorten spelling of print. *
fixedWidthDoubletoString() [2/2]
static System.String DotNetMatrix.examples.MagicSquareExample.fixedWidthDoubletoString (double x, int w, int d) inline static
Format double with Fw.d. *
fixedWidthIntegertoString() [2/2]
static System.String DotNetMatrix.examples.MagicSquareExample.fixedWidthIntegertoString (int n, int w) inline static
Format integer with Iw. *
Main() [2/2]
static void DotNetMatrix.examples.MagicSquareExample.Main (System.String[] argv) inline static
References DotNetMatrix.examples.MagicSquareExample.fixedWidthDoubletoString(), DotNetMatrix.examples.MagicSquareExample.fixedWidthIntegertoString(), DotNetMatrix.LUDecomposition.L, DotNetMatrix.examples.MagicSquareExample.magic(), DotNetMatrix.GeneralMatrix.Multiply(), DotNetMatrix.GeneralMatrix.Norm1(), DotNetMatrix.LUDecomposition.Pivot, DotNetMatrix.examples.MagicSquareExample.print(), DotNetMatrix.QRDecomposition.Q, DotNetMatrix.QRDecomposition.R, DotNetMatrix.GeneralMatrix.Subtract(), and DotNetMatrix.LUDecomposition.U.
The documentation for this class was generated from the following file:
igtest/numerics/DotMatrix/Example/Backup/MagicSquareExample.cs