Doc: IGLib EXTENDED: LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService Class Reference
LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService Class Reference
Public Member Functions
CalypsoWSNSService ()
object[] getVersionList ()
void getVersionListAsync ()
void getVersionListAsync (object userState)
void sendMessage (string msg)
void sendMessageAsync (string msg)
void sendMessageAsync (string msg, object userState)
void sendMessage (string msg, string HL7Version)
void sendMessage1Async (string msg, string HL7Version)
void sendMessage1Async (string msg, string HL7Version, object userState)
Message receiveMessage (string queueName)
void receiveMessageAsync (string queueName)
void receiveMessageAsync (string queueName, object userState)
Message receiveMessage (string queueName, string HL7Version)
void receiveMessage1Async (string queueName, string HL7Version)
void receiveMessage1Async (string queueName, string HL7Version, object userState)
void ackMessage (string msgID, string queueName)
void ackMessageAsync (string msgID, string queueName)
void ackMessageAsync (string msgID, string queueName, object userState)
string getUniqueID ()
void getUniqueIDAsync ()
void getUniqueIDAsync (object userState)
new void CancelAsync (object userState)
Properties
new string Url [get, set]
new bool UseDefaultCredentials [get, set]
Events
getVersionListCompletedEventHandler getVersionListCompleted
sendMessageCompletedEventHandler sendMessageCompleted
sendMessage1CompletedEventHandler sendMessage1Completed
receiveMessageCompletedEventHandler receiveMessageCompleted
receiveMessage1CompletedEventHandler receiveMessage1Completed
ackMessageCompletedEventHandler ackMessageCompleted
getUniqueIDCompletedEventHandler getUniqueIDCompleted
Private Member Functions
void OngetVersionListOperationCompleted (object arg)
void OnsendMessageOperationCompleted (object arg)
void OnsendMessage1OperationCompleted (object arg)
void OnreceiveMessageOperationCompleted (object arg)
void OnreceiveMessage1OperationCompleted (object arg)
void OnackMessageOperationCompleted (object arg)
void OngetUniqueIDOperationCompleted (object arg)
bool IsLocalFileSystemWebService (string url)
Private Attributes
System.Threading.SendOrPostCallback getVersionListOperationCompleted
System.Threading.SendOrPostCallback sendMessageOperationCompleted
System.Threading.SendOrPostCallback sendMessage1OperationCompleted
System.Threading.SendOrPostCallback receiveMessageOperationCompleted
System.Threading.SendOrPostCallback receiveMessage1OperationCompleted
System.Threading.SendOrPostCallback ackMessageOperationCompleted
System.Threading.SendOrPostCallback getUniqueIDOperationCompleted
bool useDefaultCredentialsSetExplicitly
Detailed Description
Constructor & Destructor Documentation
CalypsoWSNSService()
LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.CalypsoWSNSService () inline
References LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.IsLocalFileSystemWebService(), LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.Url, and LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.UseDefaultCredentials.
Member Function Documentation
getVersionList()
object [] LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.getVersionList () inline
getVersionListAsync() [1/2]
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.getVersionListAsync () inline
getVersionListAsync() [2/2]
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.getVersionListAsync (object userState) inline
References LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.getVersionListOperationCompleted, and LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OngetVersionListOperationCompleted().
OngetVersionListOperationCompleted()
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OngetVersionListOperationCompleted (object arg) inline private
References LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.getVersionListCompleted.
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.getVersionListAsync().
sendMessage() [1/2]
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.sendMessage (string msg) inline
sendMessageAsync() [1/2]
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.sendMessageAsync (string msg) inline
sendMessageAsync() [2/2]
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.sendMessageAsync (string msg, object userState) inline
References LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OnsendMessageOperationCompleted(), and LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.sendMessageOperationCompleted.
OnsendMessageOperationCompleted()
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OnsendMessageOperationCompleted (object arg) inline private
References LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.sendMessageCompleted.
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.sendMessageAsync().
sendMessage() [2/2]
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.sendMessage (string msg, string HL7Version) inline
sendMessage1Async() [1/2]
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.sendMessage1Async (string msg, string HL7Version) inline
sendMessage1Async() [2/2]
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.sendMessage1Async (string msg, string HL7Version, object userState) inline
References LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OnsendMessage1OperationCompleted(), and LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.sendMessage1OperationCompleted.
OnsendMessage1OperationCompleted()
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OnsendMessage1OperationCompleted (object arg) inline private
References LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.sendMessage1Completed.
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.sendMessage1Async().
receiveMessage() [1/2]
Message LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.receiveMessage (string queueName) inline
receiveMessageAsync() [1/2]
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.receiveMessageAsync (string queueName) inline
receiveMessageAsync() [2/2]
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.receiveMessageAsync (string queueName, object userState) inline
References LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OnreceiveMessageOperationCompleted(), and LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.receiveMessageOperationCompleted.
OnreceiveMessageOperationCompleted()
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OnreceiveMessageOperationCompleted (object arg) inline private
References LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.receiveMessageCompleted.
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.receiveMessageAsync().
receiveMessage() [2/2]
Message LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.receiveMessage (string queueName, string HL7Version) inline
receiveMessage1Async() [1/2]
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.receiveMessage1Async (string queueName, string HL7Version) inline
receiveMessage1Async() [2/2]
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.receiveMessage1Async (string queueName, string HL7Version, object userState) inline
References LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OnreceiveMessage1OperationCompleted(), and LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.receiveMessage1OperationCompleted.
OnreceiveMessage1OperationCompleted()
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OnreceiveMessage1OperationCompleted (object arg) inline private
References LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.receiveMessage1Completed.
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.receiveMessage1Async().
ackMessage()
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.ackMessage (string msgID, string queueName) inline
ackMessageAsync() [1/2]
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.ackMessageAsync (string msgID, string queueName) inline
ackMessageAsync() [2/2]
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.ackMessageAsync (string msgID, string queueName, object userState) inline
References LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.ackMessageOperationCompleted, and LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OnackMessageOperationCompleted().
OnackMessageOperationCompleted()
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OnackMessageOperationCompleted (object arg) inline private
References LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.ackMessageCompleted.
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.ackMessageAsync().
getUniqueID()
string LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.getUniqueID () inline
getUniqueIDAsync() [1/2]
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.getUniqueIDAsync () inline
getUniqueIDAsync() [2/2]
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.getUniqueIDAsync (object userState) inline
References LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.getUniqueIDOperationCompleted, and LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OngetUniqueIDOperationCompleted().
OngetUniqueIDOperationCompleted()
void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OngetUniqueIDOperationCompleted (object arg) inline private
References LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.getUniqueIDCompleted.
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.getUniqueIDAsync().
CancelAsync()
new void LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.CancelAsync (object userState) inline
IsLocalFileSystemWebService()
bool LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.IsLocalFileSystemWebService (string url) inline private
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.CalypsoWSNSService().
Member Data Documentation
getVersionListOperationCompleted
System.Threading.SendOrPostCallback LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.getVersionListOperationCompleted private
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.getVersionListAsync().
sendMessageOperationCompleted
System.Threading.SendOrPostCallback LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.sendMessageOperationCompleted private
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.sendMessageAsync().
sendMessage1OperationCompleted
System.Threading.SendOrPostCallback LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.sendMessage1OperationCompleted private
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.sendMessage1Async().
receiveMessageOperationCompleted
System.Threading.SendOrPostCallback LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.receiveMessageOperationCompleted private
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.receiveMessageAsync().
receiveMessage1OperationCompleted
System.Threading.SendOrPostCallback LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.receiveMessage1OperationCompleted private
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.receiveMessage1Async().
ackMessageOperationCompleted
System.Threading.SendOrPostCallback LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.ackMessageOperationCompleted private
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.ackMessageAsync().
getUniqueIDOperationCompleted
System.Threading.SendOrPostCallback LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.getUniqueIDOperationCompleted private
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.getUniqueIDAsync().
useDefaultCredentialsSetExplicitly
bool LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.useDefaultCredentialsSetExplicitly private
Property Documentation
Url
new string LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.Url get set
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.CalypsoWSNSService().
UseDefaultCredentials
new bool LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.UseDefaultCredentials get set
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.CalypsoWSNSService().
Event Documentation
getVersionListCompleted
getVersionListCompletedEventHandler LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.getVersionListCompleted
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OngetVersionListOperationCompleted().
sendMessageCompleted
sendMessageCompletedEventHandler LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.sendMessageCompleted
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OnsendMessageOperationCompleted().
sendMessage1Completed
sendMessage1CompletedEventHandler LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.sendMessage1Completed
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OnsendMessage1OperationCompleted().
receiveMessageCompleted
receiveMessageCompletedEventHandler LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.receiveMessageCompleted
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OnreceiveMessageOperationCompleted().
receiveMessage1Completed
receiveMessage1CompletedEventHandler LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.receiveMessage1Completed
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OnreceiveMessage1OperationCompleted().
ackMessageCompleted
ackMessageCompletedEventHandler LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.ackMessageCompleted
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OnackMessageOperationCompleted().
getUniqueIDCompleted
getUniqueIDCompletedEventHandler LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.getUniqueIDCompleted
Referenced by LabexBis.CalypsoWs.ServiceReference.CalypsoWSNSService.OngetUniqueIDOperationCompleted().
The documentation for this class was generated from the following file:
igtest/tmp_prem/prlab/LabexBis/ServiceReference.cs