Doc: IGLib EXTENDED: NUnitLite.AutoRun Class Reference
NUnitLite.AutoRun Class Reference
The AutoRun class is used by executable test assemblies to control their own execution.
Public Member Functions
int Execute (string[] args)
Execute the tests in the assembly, passing in a list of arguments.
int Execute (Assembly callingAssembly, TextWriter writer, TextReader reader, string[] args)
Execute the tests in the assembly, passing in a list of arguments.
Private Member Functions
void InitializeInternalTrace (string assemblyPath, InternalTraceLevel traceLevel)
Static Private Attributes
const string LOG_FILE_FORMAT = "InternalTrace.{0}.{1}.log"
Detailed Description
The AutoRun class is used by executable test assemblies to control their own execution.
Member Function Documentation
Execute() [1/2]
int NUnitLite.AutoRun.Execute (string[] args) inline
Execute the tests in the assembly, passing in a list of arguments.
Parameters
args Execution options
References NUnitLite.TextRunner.Execute(), NUnitLite.AutoRun.InitializeInternalTrace(), NUnitLite.TextRunner.INVALID_ARG, and NUnitLite.TextRunner.OK.
Referenced by NUnitLite.Program.Main(), NUnitLite.Tests.Program.Main(), NUnitLite.Tests.NUnitLite.Main(), and NUnit.Tests.Assemblies.MockAssembly.Main().
InitializeInternalTrace()
void NUnitLite.AutoRun.InitializeInternalTrace (string assemblyPath, InternalTraceLevel traceLevel) inline private
References NUnit.Env.DocumentFolder, NUnit.Common.InternalTrace.Initialize(), and NUnitLite.AutoRun.LOG_FILE_FORMAT.
Referenced by NUnitLite.AutoRun.Execute().
Execute() [2/2]
int NUnitLite.AutoRun.Execute (Assembly callingAssembly, TextWriter writer, TextReader reader, string[] args) inline
Execute the tests in the assembly, passing in a list of arguments.
Parameters
args Execution options
References NUnitLite.TextRunner.Execute(), NUnitLite.TextRunner.INVALID_ARG, and NUnitLite.TextRunner.OK.
Member Data Documentation
LOG_FILE_FORMAT
const string NUnitLite.AutoRun.LOG_FILE_FORMAT = "InternalTrace.{0}.{1}.log" static private
Referenced by NUnitLite.AutoRun.InitializeInternalTrace().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/nunitlite.runner/AutoRun.cs