Doc: IGLib EXTENDED: IG.Forms.SoundPlayerControlSimple Class Reference
IG.Forms.SoundPlayerControlSimple Class Reference
Public Member Functions
SoundPlayerControlSimple ()
SoundPlayerControlSimple ()
SoundPlayerControlSimple ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
System.Media.SoundPlayer Player [get]
Private Member Functions
void fileSelector1_FileSelected (object sender, EventArgs e)
void pictureBox1_DragDrop (object sender, DragEventArgs e)
void pictureBox1_DragEnter (object sender, DragEventArgs e)
void btnPlay_Click (object sender, EventArgs e)
void button1_Click (object sender, EventArgs e)
void chkRepeat_CheckedChanged (object sender, EventArgs e)
void numericUpDown1_ValueChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void fileSelector1_FileSelected (object sender, EventArgs e)
void pictureBox1_DragDrop (object sender, DragEventArgs e)
void pictureBox1_DragEnter (object sender, DragEventArgs e)
void btnPlay_Click (object sender, EventArgs e)
void button1_Click (object sender, EventArgs e)
void chkRepeat_CheckedChanged (object sender, EventArgs e)
void numericUpDown1_ValueChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void fileSelector1_FileSelected (object sender, EventArgs e)
void pictureBox1_DragDrop (object sender, DragEventArgs e)
void pictureBox1_DragEnter (object sender, DragEventArgs e)
void btnPlay_Click (object sender, EventArgs e)
void button1_Click (object sender, EventArgs e)
void chkRepeat_CheckedChanged (object sender, EventArgs e)
void numericUpDown1_ValueChanged (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.Media.SoundPlayer _soundPlayer
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Panel panelUpper
System.Windows.Forms.Button btnPlay
System.Windows.Forms.Panel panel1
IG.Forms.FileSelector fileSelector1
System.Windows.Forms.Label lblPause
System.Windows.Forms.CheckBox chkRepeat
System.Windows.Forms.Button button1
System.Windows.Forms.NumericUpDown numericUpDown1
Constructor & Destructor Documentation
SoundPlayerControlSimple() [1/3]
IG.Forms.SoundPlayerControlSimple.SoundPlayerControlSimple () inline
References IG.Forms.SoundPlayerControlSimple.InitializeComponent().
SoundPlayerControlSimple() [2/3]
IG.Forms.SoundPlayerControlSimple.SoundPlayerControlSimple () inline
References IG.Forms.SoundPlayerControlSimple.InitializeComponent().
SoundPlayerControlSimple() [3/3]
IG.Forms.SoundPlayerControlSimple.SoundPlayerControlSimple () inline
References IG.Forms.SoundPlayerControlSimple.InitializeComponent().
Member Function Documentation
fileSelector1_FileSelected() [1/3]
void IG.Forms.SoundPlayerControlSimple.fileSelector1_FileSelected (object sender, EventArgs e) inline private
References IG.Forms.FileSelector.FilePath, and IG.Forms.SoundPlayerControlSimple.fileSelector1.
Referenced by IG.Forms.SoundPlayerControlSimple.InitializeComponent().
pictureBox1_DragDrop() [1/3]
void IG.Forms.SoundPlayerControlSimple.pictureBox1_DragDrop (object sender, DragEventArgs e) inline private
References IG.Forms.FileSelector.FilePath, and IG.Forms.SoundPlayerControlSimple.fileSelector1.
Referenced by IG.Forms.SoundPlayerControlSimple.InitializeComponent().
pictureBox1_DragEnter() [1/3]
void IG.Forms.SoundPlayerControlSimple.pictureBox1_DragEnter (object sender, DragEventArgs e) inline private
Referenced by IG.Forms.SoundPlayerControlSimple.InitializeComponent().
btnPlay_Click() [1/3]
void IG.Forms.SoundPlayerControlSimple.btnPlay_Click (object sender, EventArgs e) inline private
Referenced by IG.Forms.SoundPlayerControlSimple.InitializeComponent().
button1_Click() [1/3]
void IG.Forms.SoundPlayerControlSimple.button1_Click (object sender, EventArgs e) inline private
Referenced by IG.Forms.SoundPlayerControlSimple.InitializeComponent().
chkRepeat_CheckedChanged() [1/3]
void IG.Forms.SoundPlayerControlSimple.chkRepeat_CheckedChanged (object sender, EventArgs e) inline private
Referenced by IG.Forms.SoundPlayerControlSimple.InitializeComponent().
numericUpDown1_ValueChanged() [1/3]
void IG.Forms.SoundPlayerControlSimple.numericUpDown1_ValueChanged (object sender, EventArgs e) inline private
Referenced by IG.Forms.SoundPlayerControlSimple.InitializeComponent().
Dispose() [1/3]
override void IG.Forms.SoundPlayerControlSimple.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.SoundPlayerControlSimple.components.
InitializeComponent() [1/3]
void IG.Forms.SoundPlayerControlSimple.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.SoundPlayerControlSimple.btnPlay, IG.Forms.SoundPlayerControlSimple.btnPlay_Click(), IG.Forms.SoundPlayerControlSimple.button1, IG.Forms.SoundPlayerControlSimple.button1_Click(), IG.Forms.SoundPlayerControlSimple.chkRepeat, IG.Forms.SoundPlayerControlSimple.chkRepeat_CheckedChanged(), IG.Forms.FileSelector.FilePath, IG.Forms.FileSelector.FileSelected, IG.Forms.SoundPlayerControlSimple.fileSelector1, IG.Forms.SoundPlayerControlSimple.fileSelector1_FileSelected(), IG.Forms.SoundPlayerControlSimple.lblPause, IG.Forms.SoundPlayerControlSimple.numericUpDown1, IG.Forms.SoundPlayerControlSimple.numericUpDown1_ValueChanged(), IG.Forms.SoundPlayerControlSimple.panel1, IG.Forms.SoundPlayerControlSimple.panelUpper, IG.Forms.SoundPlayerControlSimple.pictureBox1_DragDrop(), and IG.Forms.SoundPlayerControlSimple.pictureBox1_DragEnter().
Referenced by IG.Forms.SoundPlayerControlSimple.SoundPlayerControlSimple().
fileSelector1_FileSelected() [2/3]
void IG.Forms.SoundPlayerControlSimple.fileSelector1_FileSelected (object sender, EventArgs e) inline private
References IG.Forms.FileSelector.FilePath, and IG.Forms.SoundPlayerControlSimple.fileSelector1.
pictureBox1_DragDrop() [2/3]
void IG.Forms.SoundPlayerControlSimple.pictureBox1_DragDrop (object sender, DragEventArgs e) inline private
References IG.Forms.FileSelector.FilePath, and IG.Forms.SoundPlayerControlSimple.fileSelector1.
pictureBox1_DragEnter() [2/3]
void IG.Forms.SoundPlayerControlSimple.pictureBox1_DragEnter (object sender, DragEventArgs e) inline private
btnPlay_Click() [2/3]
void IG.Forms.SoundPlayerControlSimple.btnPlay_Click (object sender, EventArgs e) inline private
button1_Click() [2/3]
void IG.Forms.SoundPlayerControlSimple.button1_Click (object sender, EventArgs e) inline private
chkRepeat_CheckedChanged() [2/3]
void IG.Forms.SoundPlayerControlSimple.chkRepeat_CheckedChanged (object sender, EventArgs e) inline private
numericUpDown1_ValueChanged() [2/3]
void IG.Forms.SoundPlayerControlSimple.numericUpDown1_ValueChanged (object sender, EventArgs e) inline private
Dispose() [2/3]
override void IG.Forms.SoundPlayerControlSimple.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.SoundPlayerControlSimple.components.
InitializeComponent() [2/3]
void IG.Forms.SoundPlayerControlSimple.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.SoundPlayerControlSimple.btnPlay, IG.Forms.SoundPlayerControlSimple.btnPlay_Click(), IG.Forms.SoundPlayerControlSimple.button1, IG.Forms.SoundPlayerControlSimple.button1_Click(), IG.Forms.SoundPlayerControlSimple.chkRepeat, IG.Forms.SoundPlayerControlSimple.chkRepeat_CheckedChanged(), IG.Forms.FileSelector.FilePath, IG.Forms.FileSelector.FileSelected, IG.Forms.SoundPlayerControlSimple.fileSelector1, IG.Forms.SoundPlayerControlSimple.fileSelector1_FileSelected(), IG.Forms.SoundPlayerControlSimple.lblPause, IG.Forms.SoundPlayerControlSimple.numericUpDown1, IG.Forms.SoundPlayerControlSimple.numericUpDown1_ValueChanged(), IG.Forms.SoundPlayerControlSimple.panel1, IG.Forms.SoundPlayerControlSimple.panelUpper, IG.Forms.SoundPlayerControlSimple.pictureBox1_DragDrop(), and IG.Forms.SoundPlayerControlSimple.pictureBox1_DragEnter().
fileSelector1_FileSelected() [3/3]
void IG.Forms.SoundPlayerControlSimple.fileSelector1_FileSelected (object sender, EventArgs e) inline private
References IG.Forms.FileSelector.FilePath, and IG.Forms.SoundPlayerControlSimple.fileSelector1.
pictureBox1_DragDrop() [3/3]
void IG.Forms.SoundPlayerControlSimple.pictureBox1_DragDrop (object sender, DragEventArgs e) inline private
References IG.Forms.FileSelector.FilePath, and IG.Forms.SoundPlayerControlSimple.fileSelector1.
pictureBox1_DragEnter() [3/3]
void IG.Forms.SoundPlayerControlSimple.pictureBox1_DragEnter (object sender, DragEventArgs e) inline private
btnPlay_Click() [3/3]
void IG.Forms.SoundPlayerControlSimple.btnPlay_Click (object sender, EventArgs e) inline private
button1_Click() [3/3]
void IG.Forms.SoundPlayerControlSimple.button1_Click (object sender, EventArgs e) inline private
chkRepeat_CheckedChanged() [3/3]
void IG.Forms.SoundPlayerControlSimple.chkRepeat_CheckedChanged (object sender, EventArgs e) inline private
numericUpDown1_ValueChanged() [3/3]
void IG.Forms.SoundPlayerControlSimple.numericUpDown1_ValueChanged (object sender, EventArgs e) inline private
Dispose() [3/3]
override void IG.Forms.SoundPlayerControlSimple.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.SoundPlayerControlSimple.components.
InitializeComponent() [3/3]
void IG.Forms.SoundPlayerControlSimple.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.SoundPlayerControlSimple.btnPlay, IG.Forms.SoundPlayerControlSimple.btnPlay_Click(), IG.Forms.SoundPlayerControlSimple.button1, IG.Forms.SoundPlayerControlSimple.button1_Click(), IG.Forms.SoundPlayerControlSimple.chkRepeat, IG.Forms.SoundPlayerControlSimple.chkRepeat_CheckedChanged(), IG.Forms.FileSelector.FilePath, IG.Forms.FileSelector.FileSelected, IG.Forms.SoundPlayerControlSimple.fileSelector1, IG.Forms.SoundPlayerControlSimple.fileSelector1_FileSelected(), IG.Forms.SoundPlayerControlSimple.lblPause, IG.Forms.SoundPlayerControlSimple.numericUpDown1, IG.Forms.SoundPlayerControlSimple.numericUpDown1_ValueChanged(), IG.Forms.SoundPlayerControlSimple.panel1, IG.Forms.SoundPlayerControlSimple.panelUpper, IG.Forms.SoundPlayerControlSimple.pictureBox1_DragDrop(), and IG.Forms.SoundPlayerControlSimple.pictureBox1_DragEnter().
Member Data Documentation
_soundPlayer
System Media SoundPlayer IG.Forms.SoundPlayerControlSimple._soundPlayer private
components
System ComponentModel IContainer IG.Forms.SoundPlayerControlSimple.components = null private
Required designer variable.
Referenced by IG.Forms.SoundPlayerControlSimple.Dispose().
panelUpper
System Windows Forms Panel IG.Forms.SoundPlayerControlSimple.panelUpper private
Referenced by IG.Forms.SoundPlayerControlSimple.InitializeComponent().
btnPlay
System Windows Forms Button IG.Forms.SoundPlayerControlSimple.btnPlay private
Referenced by IG.Forms.SoundPlayerControlSimple.InitializeComponent().
panel1
System Windows Forms Panel IG.Forms.SoundPlayerControlSimple.panel1 private
Referenced by IG.Forms.SoundPlayerControlSimple.InitializeComponent().
fileSelector1
IG Forms FileSelector IG.Forms.SoundPlayerControlSimple.fileSelector1 private
Referenced by IG.Forms.SoundPlayerControlSimple.fileSelector1_FileSelected(), IG.Forms.SoundPlayerControlSimple.InitializeComponent(), and IG.Forms.SoundPlayerControlSimple.pictureBox1_DragDrop().
lblPause
System Windows Forms Label IG.Forms.SoundPlayerControlSimple.lblPause private
Referenced by IG.Forms.SoundPlayerControlSimple.InitializeComponent().
chkRepeat
System Windows Forms CheckBox IG.Forms.SoundPlayerControlSimple.chkRepeat private
Referenced by IG.Forms.SoundPlayerControlSimple.InitializeComponent().
button1
System Windows Forms Button IG.Forms.SoundPlayerControlSimple.button1 private
Referenced by IG.Forms.SoundPlayerControlSimple.InitializeComponent().
numericUpDown1
System Windows Forms NumericUpDown IG.Forms.SoundPlayerControlSimple.numericUpDown1 private
Referenced by IG.Forms.SoundPlayerControlSimple.InitializeComponent().
Property Documentation
Player
System Media SoundPlayer IG.Forms.SoundPlayerControlSimple.Player get private
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/Viewers/SoundPlayControlSimple.cs
iglib/igforms/Utilities/Viewers/SoundPlayControlSimple.Designer.cs