Doc: IGLib EXTENDED: alglib.blas Class Reference
alglib.blas Class Reference
Static Public Member Functions
static double vectornorm2 (double[] x, int i1, int i2)
static int vectoridxabsmax (double[] x, int i1, int i2)
static int columnidxabsmax (double[,] x, int i1, int i2, int j)
static int rowidxabsmax (double[,] x, int j1, int j2, int i)
static double upperhessenberg1norm (double[,] a, int i1, int i2, int j1, int j2, ref double[] work)
static void copymatrix (double[,] a, int is1, int is2, int js1, int js2, ref double[,] b, int id1, int id2, int jd1, int jd2)
static void inplacetranspose (ref double[,] a, int i1, int i2, int j1, int j2, ref double[] work)
static void copyandtranspose (double[,] a, int is1, int is2, int js1, int js2, ref double[,] b, int id1, int id2, int jd1, int jd2)
static void matrixvectormultiply (double[,] a, int i1, int i2, int j1, int j2, bool trans, double[] x, int ix1, int ix2, double alpha, ref double[] y, int iy1, int iy2, double beta)
static double pythag2 (double x, double y)
static void matrixmatrixmultiply (double[,] a, int ai1, int ai2, int aj1, int aj2, bool transa, double[,] b, int bi1, int bi2, int bj1, int bj2, bool transb, double alpha, ref double[,] c, int ci1, int ci2, int cj1, int cj2, double beta, ref double[] work)
static double vectornorm2 (double[] x, int i1, int i2)
static int vectoridxabsmax (double[] x, int i1, int i2)
static int columnidxabsmax (double[,] x, int i1, int i2, int j)
static int rowidxabsmax (double[,] x, int j1, int j2, int i)
static double upperhessenberg1norm (double[,] a, int i1, int i2, int j1, int j2, ref double[] work)
static void copymatrix (double[,] a, int is1, int is2, int js1, int js2, ref double[,] b, int id1, int id2, int jd1, int jd2)
static void inplacetranspose (ref double[,] a, int i1, int i2, int j1, int j2, ref double[] work)
static void copyandtranspose (double[,] a, int is1, int is2, int js1, int js2, ref double[,] b, int id1, int id2, int jd1, int jd2)
static void matrixvectormultiply (double[,] a, int i1, int i2, int j1, int j2, bool trans, double[] x, int ix1, int ix2, double alpha, ref double[] y, int iy1, int iy2, double beta)
static double pythag2 (double x, double y)
static void matrixmatrixmultiply (double[,] a, int ai1, int ai2, int aj1, int aj2, bool transa, double[,] b, int bi1, int bi2, int bj1, int bj2, bool transb, double alpha, ref double[,] c, int ci1, int ci2, int cj1, int cj2, double beta, ref double[] work)
Member Function Documentation
vectornorm2() [1/2]
static double alglib.blas.vectornorm2 (double[] x, int i1, int i2) inline static
References alglib.math.sqr().
Referenced by alglib.testblasunit.testblas().
vectoridxabsmax() [1/2]
static int alglib.blas.vectoridxabsmax (double[] x, int i1, int i2) inline static
Referenced by alglib.hsschur.internalschurdecomposition(), and alglib.testblasunit.testblas().
columnidxabsmax() [1/2]
static int alglib.blas.columnidxabsmax (double x[,], int i1, int i2, int j) inline static
Referenced by alglib.testblasunit.testblas().
rowidxabsmax() [1/2]
static int alglib.blas.rowidxabsmax (double x[,], int j1, int j2, int i) inline static
Referenced by alglib.testblasunit.testblas().
upperhessenberg1norm() [1/2]
static double alglib.blas.upperhessenberg1norm (double a[,], int i1, int i2, int j1, int j2, ref double[] work) inline static
References alglib.ap.assert().
Referenced by alglib.hsschur.internalauxschur(), alglib.hsschur.internalschurdecomposition(), and alglib.testblasunit.testblas().
copymatrix() [1/2]
static void alglib.blas.copymatrix (double a[,], int is1, int is2, int js1, int js2, ref double b[,], int id1, int id2, int jd1, int jd2) inline static
References alglib.ap.assert().
Referenced by alglib.hsschur.internalschurdecomposition(), alglib.kmeans.kmeansgenerate(), alglib.testblasunit.testblas(), and alglib.testdensesolverunit.testrsolver().
inplacetranspose() [1/2]
static void alglib.blas.inplacetranspose (ref double a[,], int i1, int i2, int j1, int j2, ref double[] work) inline static
References alglib.ap.assert().
Referenced by alglib.testblasunit.testblas().
copyandtranspose() [1/2]
static void alglib.blas.copyandtranspose (double a[,], int is1, int is2, int js1, int js2, ref double b[,], int id1, int id2, int jd1, int jd2) inline static
References alglib.ap.assert().
Referenced by alglib.kmeans.kmeansgenerate(), and alglib.testblasunit.testblas().
matrixvectormultiply() [1/2]
static void alglib.blas.matrixvectormultiply (double a[,], int i1, int i2, int j1, int j2, bool trans, double[] x, int ix1, int ix2, double alpha, ref double[] y, int iy1, int iy2, double beta) inline static
References alglib.ap.assert(), and alglib.beta().
Referenced by alglib.hsschur.internalschurdecomposition(), and alglib.testblasunit.testblas().
pythag2() [1/2]
static double alglib.blas.pythag2 (double x, double y) inline static
References alglib.math.sqr().
Referenced by alglib.hsschur.aux2x2schur(), and alglib.hsschur.internalschurdecomposition().
matrixmatrixmultiply() [1/2]
static void alglib.blas.matrixmatrixmultiply (double a[,], int ai1, int ai2, int aj1, int aj2, bool transa, double b[,], int bi1, int bi2, int bj1, int bj2, bool transb, double alpha, ref double c[,], int ci1, int ci2, int cj1, int cj2, double beta, ref double[] work) inline static
References alglib.ap.assert(), and alglib.beta().
Referenced by alglib.lda.fisherldan(), alglib.linreg.lrinternal(), alglib.testblasunit.testblas(), and alglib.testldaunit.testwn().
vectornorm2() [2/2]
static double alglib.blas.vectornorm2 (double[] x, int i1, int i2) inline static
References alglib.math.sqr().
vectoridxabsmax() [2/2]
static int alglib.blas.vectoridxabsmax (double[] x, int i1, int i2) inline static
columnidxabsmax() [2/2]
static int alglib.blas.columnidxabsmax (double x[,], int i1, int i2, int j) inline static
rowidxabsmax() [2/2]
static int alglib.blas.rowidxabsmax (double x[,], int j1, int j2, int i) inline static
upperhessenberg1norm() [2/2]
static double alglib.blas.upperhessenberg1norm (double a[,], int i1, int i2, int j1, int j2, ref double[] work) inline static
References alglib.ap.assert().
copymatrix() [2/2]
static void alglib.blas.copymatrix (double a[,], int is1, int is2, int js1, int js2, ref double b[,], int id1, int id2, int jd1, int jd2) inline static
References alglib.ap.assert().
inplacetranspose() [2/2]
static void alglib.blas.inplacetranspose (ref double a[,], int i1, int i2, int j1, int j2, ref double[] work) inline static
References alglib.ap.assert().
copyandtranspose() [2/2]
static void alglib.blas.copyandtranspose (double a[,], int is1, int is2, int js1, int js2, ref double b[,], int id1, int id2, int jd1, int jd2) inline static
References alglib.ap.assert().
matrixvectormultiply() [2/2]
static void alglib.blas.matrixvectormultiply (double a[,], int i1, int i2, int j1, int j2, bool trans, double[] x, int ix1, int ix2, double alpha, ref double[] y, int iy1, int iy2, double beta) inline static
References alglib.ap.assert(), and alglib.beta().
pythag2() [2/2]
static double alglib.blas.pythag2 (double x, double y) inline static
References alglib.math.sqr().
matrixmatrixmultiply() [2/2]
static void alglib.blas.matrixmatrixmultiply (double a[,], int ai1, int ai2, int aj1, int aj2, bool transa, double b[,], int bi1, int bi2, int bj1, int bj2, bool transb, double alpha, ref double c[,], int ci1, int ci2, int cj1, int cj2, double beta, ref double[] work) inline static
References alglib.ap.assert(), and alglib.beta().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/alglibinternal.cs