Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DORMRZ Class Reference
DotNumerics.LinearAlgebra.CSLapack.DORMRZ Class Reference
– LAPACK routine (version 3.1.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. January 2007
Public Member Functions
DORMRZ (LSAME lsame, ILAENV ilaenv, DLARZB dlarzb, DLARZT dlarzt, DORMR3 dormr3, XERBLA xerbla)
DORMRZ ()
void Run (string SIDE, string TRANS, int M, int N, int K, int L, double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
LSAME _lsame
ILAENV _ilaenv
DLARZB _dlarzb
DLARZT _dlarzt
DORMR3 _dormr3
XERBLA _xerbla
double[] T = new double[LDT * NBMAX]
Static Private Attributes
const int NBMAX = 64
const int LDT = NBMAX + 1
Detailed Description
– LAPACK routine (version 3.1.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. January 2007
Purpose
DORMRZ overwrites the general real M-by-N matrix C with
SIDE = 'L' SIDE = 'R' TRANS = 'N': Q * C C * Q TRANS = 'T': Q**T * C C * Q**T
where Q is a real orthogonal matrix defined as the product of k elementary reflectors
Q = H(1) H(2) . . . H(k)
as returned by DTZRZF. Q is of order M if SIDE = 'L' and of order N if SIDE = 'R'.
/summary>
Constructor & Destructor Documentation
DORMRZ() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DORMRZ.DORMRZ (LSAME lsame, ILAENV ilaenv, DLARZB dlarzb, DLARZT dlarzt, DORMR3 dormr3, XERBLA xerbla) inline
DORMRZ() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DORMRZ.DORMRZ () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DORMRZ.Run (string SIDE, string TRANS, int M, int N, int K, int L, double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DORMRZ overwrites the general real M-by-N matrix C with
SIDE = 'L' SIDE = 'R' TRANS = 'N': Q * C C * Q TRANS = 'T': Q**T * C C * Q**T
where Q is a real orthogonal matrix defined as the product of k elementary reflectors
Q = H(1) H(2) . . . H(k)
as returned by DTZRZF. Q is of order M if SIDE = 'L' and of order N if SIDE = 'R'.
/summary>
Parameters
SIDE = 'L' SIDE = 'R' /param>
Parameters
TRANS (input) CHARACTER*1 = 'N': No transpose, apply Q; = 'T': Transpose, apply Q**T. /param>
Parameters
M (input) INTEGER The number of rows of the matrix C. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix C. N .GE. 0. /param>
Parameters
K (input) INTEGER The number of elementary reflectors whose product defines the matrix Q. If SIDE = 'L', M .GE. K .GE. 0; if SIDE = 'R', N .GE. K .GE. 0. /param>
Parameters
L (input) INTEGER The number of columns of the matrix A containing the meaningful part of the Householder reflectors. If SIDE = 'L', M .GE. L .GE. 0, if SIDE = 'R', N .GE. L .GE. 0. /param>
Parameters
A (input) DOUBLE PRECISION array, dimension (LDA,M) if SIDE = 'L', (LDA,N) if SIDE = 'R' The i-th row must contain the vector which defines the elementary reflector H(i), for i = 1,2,...,k, as returned by DTZRZF in the last k rows of its array argument A. A is modified by the routine but restored on exit. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,K). /param>
Parameters
TAU (input) DOUBLE PRECISION array, dimension (K) TAU(i) must contain the scalar factor of the elementary reflector H(i), as returned by DTZRZF. /param>
Parameters
C (input/output) DOUBLE PRECISION array, dimension (LDC,N) On entry, the M-by-N matrix C. On exit, C is overwritten by Q*C or Q**H*C or C*Q**H or C*Q. /param>
Parameters
LDC (input) INTEGER The leading dimension of the array C. LDC .GE. max(1,M). /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. If SIDE = 'L', LWORK .GE. max(1,N); if SIDE = 'R', LWORK .GE. max(1,M). For optimum performance LWORK .GE. N*NB if SIDE = 'L', and LWORK .GE. M*NB if SIDE = 'R', where NB is the optimal blocksize.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value /param>
References DotNumerics.FortranLibrary.FortranLib.Copy(), DotNumerics.LinearAlgebra.CSLapack.DORMRZ.LDT, DotNumerics.LinearAlgebra.CSLapack.DORMRZ.NBMAX, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARZT.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARZB.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMR3.Run(), and DotNumerics.LinearAlgebra.CSLapack.DORMRZ.T.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGELSY.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DORMRZ._lsame private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DORMRZ._ilaenv private
_dlarzb
DLARZB DotNumerics.LinearAlgebra.CSLapack.DORMRZ._dlarzb private
_dlarzt
DLARZT DotNumerics.LinearAlgebra.CSLapack.DORMRZ._dlarzt private
_dormr3
DORMR3 DotNumerics.LinearAlgebra.CSLapack.DORMRZ._dormr3 private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DORMRZ._xerbla private
NBMAX
const int DotNumerics.LinearAlgebra.CSLapack.DORMRZ.NBMAX = 64 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORMRZ.Run().
LDT
const int DotNumerics.LinearAlgebra.CSLapack.DORMRZ.LDT = NBMAX + 1 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORMRZ.Run().
T
double [] DotNumerics.LinearAlgebra.CSLapack.DORMRZ.T = new double[LDT * NBMAX] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORMRZ.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dormrz.cs