Doc: IGLib EXTENDED: NUnit.Framework.Internal.TestExecutionContextTests Class Reference
NUnit.Framework.Internal.TestExecutionContextTests Class Reference
Summary description for TestExecutionContextTests.
Classes
class TestClass
Public Member Functions
void OneTimeSetUp ()
void OneTimeTearDown ()
void Initialize ()
Since we are testing the mechanism that saves and restores contexts, we save manually here
void Cleanup ()
void FixtureSetUpCanAccessFixtureName ()
void FixtureSetUpCanAccessFixtureFullName ()
void FixtureSetUpCanAccessFixtureId ()
void FixtureSetUpCanAccessFixtureProperties ()
void SetUpCanAccessTestName ()
void SetUpCanAccessTestFullName ()
void SetUpCanAccessTestId ()
void SetUpCanAccessTestProperties ()
void TestCanAccessItsOwnName ()
void TestCanAccessItsOwnFullName ()
void TestCanAccessItsOwnId ()
void TestCanAccessItsOwnProperties ()
void FixtureSetUpontextReflectsCurrentCulture ()
void FixtureSetUpContextReflectsCurrentUICulture ()
void SetUpContextReflectsCurrentCulture ()
void SetUpContextReflectsCurrentUICulture ()
void TestContextReflectsCurrentCulture ()
void TestContextReflectsCurrentUICulture ()
void SetAndRestoreCurrentCulture ()
void SetAndRestoreCurrentUICulture ()
void FixtureSetUpContextReflectsCurrentPrincipal ()
void SetUpContextReflectsCurrentPrincipal ()
void TestContextReflectsCurrentPrincipal ()
void SetAndRestoreCurrentPrincipal ()
void ExecutionStatusIsPushedToHigherContext ()
void ExecutionStatusIsPulledFromHigherContext ()
void ExecutionStatusIsPromulgatedAcrossBranches ()
void CanCreateObjectInAppDomain ()
Private Attributes
TestExecutionContext fixtureContext
TestExecutionContext setupContext
string originalDirectory
IPrincipal originalPrincipal
CultureInfo originalCulture
CultureInfo originalUICulture
Detailed Description
Summary description for TestExecutionContextTests.
Member Function Documentation
OneTimeSetUp()
void NUnit.Framework.Internal.TestExecutionContextTests.OneTimeSetUp () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentContext, and NUnit.Framework.Internal.TestExecutionContextTests.fixtureContext.
OneTimeTearDown()
void NUnit.Framework.Internal.TestExecutionContextTests.OneTimeTearDown () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentContext, NUnit.Framework.Internal.TestExecutionContext.CurrentTest, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestExecutionContextTests.fixtureContext, NUnit.Framework.Internal.Test.FullName, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Id, NUnit.Framework.Internal.Test.Name, NUnit.Framework.Is.Not, NUnit.Framework.Internal.Test.Properties, and NUnit.Framework.Assert.That().
Initialize()
void NUnit.Framework.Internal.TestExecutionContextTests.Initialize () inline
Since we are testing the mechanism that saves and restores contexts, we save manually here
References NUnit.Framework.Internal.TestExecutionContext.CurrentContext, NUnit.Framework.Internal.TestExecutionContextTests.originalCulture, NUnit.Framework.Internal.TestExecutionContextTests.originalDirectory, NUnit.Framework.Internal.TestExecutionContextTests.originalPrincipal, NUnit.Framework.Internal.TestExecutionContextTests.originalUICulture, and NUnit.Framework.Internal.TestExecutionContextTests.setupContext.
Cleanup()
void NUnit.Framework.Internal.TestExecutionContextTests.Cleanup () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentContext, NUnit.Framework.Internal.TestExecutionContext.CurrentTest, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Test.FullName, NUnit.Framework.Internal.TestExecutionContextTests.originalCulture, NUnit.Framework.Internal.TestExecutionContextTests.originalDirectory, NUnit.Framework.Internal.TestExecutionContextTests.originalPrincipal, NUnit.Framework.Internal.TestExecutionContextTests.originalUICulture, NUnit.Framework.Internal.TestExecutionContextTests.setupContext, and NUnit.Framework.Assert.That().
FixtureSetUpCanAccessFixtureName()
void NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpCanAccessFixtureName () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentTest, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestExecutionContextTests.fixtureContext, NUnit.Framework.Internal.Test.Name, and NUnit.Framework.Assert.That().
FixtureSetUpCanAccessFixtureFullName()
void NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpCanAccessFixtureFullName () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentTest, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestExecutionContextTests.fixtureContext, NUnit.Framework.Internal.Test.FullName, and NUnit.Framework.Assert.That().
FixtureSetUpCanAccessFixtureId()
void NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpCanAccessFixtureId () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentTest, NUnit.Framework.Internal.TestExecutionContextTests.fixtureContext, NUnit.Framework.Internal.Test.Id, NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
FixtureSetUpCanAccessFixtureProperties()
void NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpCanAccessFixtureProperties () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentTest, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestExecutionContextTests.fixtureContext, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, and NUnit.Framework.Assert.That().
SetUpCanAccessTestName()
void NUnit.Framework.Internal.TestExecutionContextTests.SetUpCanAccessTestName () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentTest, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Test.Name, NUnit.Framework.Internal.TestExecutionContextTests.setupContext, and NUnit.Framework.Assert.That().
SetUpCanAccessTestFullName()
void NUnit.Framework.Internal.TestExecutionContextTests.SetUpCanAccessTestFullName () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentTest, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Test.FullName, NUnit.Framework.Internal.TestExecutionContextTests.setupContext, and NUnit.Framework.Assert.That().
SetUpCanAccessTestId()
void NUnit.Framework.Internal.TestExecutionContextTests.SetUpCanAccessTestId () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentTest, NUnit.Framework.Internal.Test.Id, NUnit.Framework.Is.Not, NUnit.Framework.Internal.TestExecutionContextTests.setupContext, and NUnit.Framework.Assert.That().
SetUpCanAccessTestProperties()
void NUnit.Framework.Internal.TestExecutionContextTests.SetUpCanAccessTestProperties () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentTest, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.TestExecutionContextTests.setupContext, and NUnit.Framework.Assert.That().
TestCanAccessItsOwnName()
void NUnit.Framework.Internal.TestExecutionContextTests.TestCanAccessItsOwnName () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentContext, NUnit.Framework.Internal.TestExecutionContext.CurrentTest, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Test.Name, and NUnit.Framework.Assert.That().
TestCanAccessItsOwnFullName()
void NUnit.Framework.Internal.TestExecutionContextTests.TestCanAccessItsOwnFullName () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentContext, NUnit.Framework.Internal.TestExecutionContext.CurrentTest, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.Test.FullName, and NUnit.Framework.Assert.That().
TestCanAccessItsOwnId()
void NUnit.Framework.Internal.TestExecutionContextTests.TestCanAccessItsOwnId () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentContext, NUnit.Framework.Internal.TestExecutionContext.CurrentTest, NUnit.Framework.Internal.Test.Id, NUnit.Framework.Is.Not, and NUnit.Framework.Assert.That().
TestCanAccessItsOwnProperties()
void NUnit.Framework.Internal.TestExecutionContextTests.TestCanAccessItsOwnProperties () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentContext, NUnit.Framework.Internal.TestExecutionContext.CurrentTest, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Internal.Test.Properties, and NUnit.Framework.Assert.That().
FixtureSetUpontextReflectsCurrentCulture()
void NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpontextReflectsCurrentCulture () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentCulture, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestExecutionContextTests.fixtureContext, and NUnit.Framework.Assert.That().
FixtureSetUpContextReflectsCurrentUICulture()
void NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpContextReflectsCurrentUICulture () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentUICulture, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestExecutionContextTests.fixtureContext, and NUnit.Framework.Assert.That().
SetUpContextReflectsCurrentCulture()
void NUnit.Framework.Internal.TestExecutionContextTests.SetUpContextReflectsCurrentCulture () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentCulture, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestExecutionContextTests.setupContext, and NUnit.Framework.Assert.That().
SetUpContextReflectsCurrentUICulture()
void NUnit.Framework.Internal.TestExecutionContextTests.SetUpContextReflectsCurrentUICulture () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentUICulture, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestExecutionContextTests.setupContext, and NUnit.Framework.Assert.That().
TestContextReflectsCurrentCulture()
void NUnit.Framework.Internal.TestExecutionContextTests.TestContextReflectsCurrentCulture () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentContext, NUnit.Framework.Internal.TestExecutionContext.CurrentCulture, NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
TestContextReflectsCurrentUICulture()
void NUnit.Framework.Internal.TestExecutionContextTests.TestContextReflectsCurrentUICulture () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentContext, NUnit.Framework.Internal.TestExecutionContext.CurrentUICulture, NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
SetAndRestoreCurrentCulture()
void NUnit.Framework.Internal.TestExecutionContextTests.SetAndRestoreCurrentCulture () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.TestExecutionContext.CurrentCulture, NUnit.Framework.Internal.TestExecutionContext.EstablishExecutionEnvironment(), NUnit.Framework.Internal.TestExecutionContextTests.originalCulture, and NUnit.Framework.Internal.TestExecutionContextTests.setupContext.
SetAndRestoreCurrentUICulture()
void NUnit.Framework.Internal.TestExecutionContextTests.SetAndRestoreCurrentUICulture () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.TestExecutionContext.CurrentUICulture, NUnit.Framework.Internal.TestExecutionContext.EstablishExecutionEnvironment(), NUnit.Framework.Internal.TestExecutionContextTests.originalUICulture, and NUnit.Framework.Internal.TestExecutionContextTests.setupContext.
FixtureSetUpContextReflectsCurrentPrincipal()
void NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpContextReflectsCurrentPrincipal () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentPrincipal, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestExecutionContextTests.fixtureContext, and NUnit.Framework.Assert.That().
SetUpContextReflectsCurrentPrincipal()
void NUnit.Framework.Internal.TestExecutionContextTests.SetUpContextReflectsCurrentPrincipal () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentPrincipal, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestExecutionContextTests.setupContext, and NUnit.Framework.Assert.That().
TestContextReflectsCurrentPrincipal()
void NUnit.Framework.Internal.TestExecutionContextTests.TestContextReflectsCurrentPrincipal () inline
References NUnit.Framework.Internal.TestExecutionContext.CurrentContext, NUnit.Framework.Internal.TestExecutionContext.CurrentPrincipal, NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
SetAndRestoreCurrentPrincipal()
void NUnit.Framework.Internal.TestExecutionContextTests.SetAndRestoreCurrentPrincipal () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.TestExecutionContext.CurrentPrincipal, NUnit.Framework.Internal.TestExecutionContext.EstablishExecutionEnvironment(), NUnit.Framework.Internal.TestExecutionContextTests.originalPrincipal, and NUnit.Framework.Internal.TestExecutionContextTests.setupContext.
ExecutionStatusIsPushedToHigherContext()
void NUnit.Framework.Internal.TestExecutionContextTests.ExecutionStatusIsPushedToHigherContext () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
ExecutionStatusIsPulledFromHigherContext()
void NUnit.Framework.Internal.TestExecutionContextTests.ExecutionStatusIsPulledFromHigherContext () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
ExecutionStatusIsPromulgatedAcrossBranches()
void NUnit.Framework.Internal.TestExecutionContextTests.ExecutionStatusIsPromulgatedAcrossBranches () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
CanCreateObjectInAppDomain()
void NUnit.Framework.Internal.TestExecutionContextTests.CanCreateObjectInAppDomain () inline
References NUnit.Common.AssemblyHelper.GetDirectoryName(), and NUnit.Framework.Assert.NotNull().
Member Data Documentation
fixtureContext
TestExecutionContext NUnit.Framework.Internal.TestExecutionContextTests.fixtureContext private
Referenced by NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpCanAccessFixtureFullName(), NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpCanAccessFixtureId(), NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpCanAccessFixtureName(), NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpCanAccessFixtureProperties(), NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpContextReflectsCurrentPrincipal(), NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpContextReflectsCurrentUICulture(), NUnit.Framework.Internal.TestExecutionContextTests.FixtureSetUpontextReflectsCurrentCulture(), NUnit.Framework.Internal.TestExecutionContextTests.OneTimeSetUp(), and NUnit.Framework.Internal.TestExecutionContextTests.OneTimeTearDown().
setupContext
TestExecutionContext NUnit.Framework.Internal.TestExecutionContextTests.setupContext private
Referenced by NUnit.Framework.Internal.TestExecutionContextTests.Cleanup(), NUnit.Framework.Internal.TestExecutionContextTests.Initialize(), NUnit.Framework.Internal.TestExecutionContextTests.SetAndRestoreCurrentCulture(), NUnit.Framework.Internal.TestExecutionContextTests.SetAndRestoreCurrentPrincipal(), NUnit.Framework.Internal.TestExecutionContextTests.SetAndRestoreCurrentUICulture(), NUnit.Framework.Internal.TestExecutionContextTests.SetUpCanAccessTestFullName(), NUnit.Framework.Internal.TestExecutionContextTests.SetUpCanAccessTestId(), NUnit.Framework.Internal.TestExecutionContextTests.SetUpCanAccessTestName(), NUnit.Framework.Internal.TestExecutionContextTests.SetUpCanAccessTestProperties(), NUnit.Framework.Internal.TestExecutionContextTests.SetUpContextReflectsCurrentCulture(), NUnit.Framework.Internal.TestExecutionContextTests.SetUpContextReflectsCurrentPrincipal(), and NUnit.Framework.Internal.TestExecutionContextTests.SetUpContextReflectsCurrentUICulture().
originalDirectory
string NUnit.Framework.Internal.TestExecutionContextTests.originalDirectory private
Referenced by NUnit.Framework.Internal.TestExecutionContextTests.Cleanup(), and NUnit.Framework.Internal.TestExecutionContextTests.Initialize().
originalPrincipal
IPrincipal NUnit.Framework.Internal.TestExecutionContextTests.originalPrincipal private
Referenced by NUnit.Framework.Internal.TestExecutionContextTests.Cleanup(), NUnit.Framework.Internal.TestExecutionContextTests.Initialize(), and NUnit.Framework.Internal.TestExecutionContextTests.SetAndRestoreCurrentPrincipal().
originalCulture
CultureInfo NUnit.Framework.Internal.TestExecutionContextTests.originalCulture private
Referenced by NUnit.Framework.Internal.TestExecutionContextTests.Cleanup(), NUnit.Framework.Internal.TestExecutionContextTests.Initialize(), and NUnit.Framework.Internal.TestExecutionContextTests.SetAndRestoreCurrentCulture().
originalUICulture
CultureInfo NUnit.Framework.Internal.TestExecutionContextTests.originalUICulture private
Referenced by NUnit.Framework.Internal.TestExecutionContextTests.Cleanup(), NUnit.Framework.Internal.TestExecutionContextTests.Initialize(), and NUnit.Framework.Internal.TestExecutionContextTests.SetAndRestoreCurrentUICulture().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/TestExecutionContextTests.cs