Doc: IGLib EXTENDED: NUnit.Framework.Assertions.AssertInconclusiveTests Class Reference
NUnit.Framework.Assertions.AssertInconclusiveTests Class Reference
Public Member Functions
void ThrowsInconclusiveException ()
void ThrowsInconclusiveExceptionWithMessage ()
void ThrowsInconclusiveExceptionWithMessageAndArgs ()
Member Function Documentation
ThrowsInconclusiveException()
void NUnit.Framework.Assertions.AssertInconclusiveTests.ThrowsInconclusiveException () inline
References NUnit.Framework.Assert.Inconclusive(), NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
ThrowsInconclusiveExceptionWithMessage()
void NUnit.Framework.Assertions.AssertInconclusiveTests.ThrowsInconclusiveExceptionWithMessage () inline
References NUnit.Framework.Assert.Inconclusive(), NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
ThrowsInconclusiveExceptionWithMessageAndArgs()
void NUnit.Framework.Assertions.AssertInconclusiveTests.ThrowsInconclusiveExceptionWithMessageAndArgs () inline
References NUnit.Framework.Assert.Inconclusive(), NUnit.Framework.Assert.That(), and NUnit.Framework.Throws.TypeOf().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Assertions/AssertInconclusiveTests.cs