Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLASCL Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLASCL Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLASCL (LSAME lsame, DLAMCH dlamch, XERBLA xerbla)
DLASCL ()
void Run (string TYPE, int KL, int KU, double CFROM, double CTO, int M, int N, ref double[] A, int offset_a, int LDA, ref int INFO)
Private Attributes
LSAME _lsame
DLAMCH _dlamch
XERBLA _xerbla
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLASCL multiplies the M by N real matrix A by the real scalar CTO/CFROM. This is done without over/underflow as long as the final result CTO*A(I,J)/CFROM does not over/underflow. TYPE specifies that A may be full, upper triangular, lower triangular, upper Hessenberg, or banded.
/summary>
Constructor & Destructor Documentation
DLASCL() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLASCL.DLASCL (LSAME lsame, DLAMCH dlamch, XERBLA xerbla) inline
DLASCL() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLASCL.DLASCL () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run (string TYPE, int KL, int KU, double CFROM, double CTO, int M, int N, ref double[] A, int offset_a, int LDA, ref int INFO) inline
Purpose
DLASCL multiplies the M by N real matrix A by the real scalar CTO/CFROM. This is done without over/underflow as long as the final result CTO*A(I,J)/CFROM does not over/underflow. TYPE specifies that A may be full, upper triangular, lower triangular, upper Hessenberg, or banded.
/summary>
Parameters
TYPE (input) CHARACTER*1 TYPE indices the storage type of the input matrix. = 'G': A is a full matrix. = 'L': A is a lower triangular matrix. = 'U': A is an upper triangular matrix. = 'H': A is an upper Hessenberg matrix. = 'B': A is a symmetric band matrix with lower bandwidth KL and upper bandwidth KU and with the only the lower half stored. = 'Q': A is a symmetric band matrix with lower bandwidth KL and upper bandwidth KU and with the only the upper half stored. = 'Z': A is a band matrix with lower bandwidth KL and upper bandwidth KU. /param>
Parameters
KL (input) INTEGER The lower bandwidth of A. Referenced only if TYPE = 'B', 'Q' or 'Z'. /param>
Parameters
KU (input) INTEGER The upper bandwidth of A. Referenced only if TYPE = 'B', 'Q' or 'Z'. /param>
Parameters
CFROM (input) DOUBLE PRECISION /param>
Parameters
CTO (input) DOUBLE PRECISION The matrix A is multiplied by CTO/CFROM. A(I,J) is computed without over/underflow if the final result CTO*A(I,J)/CFROM can be represented without over/underflow. CFROM must be nonzero. /param>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) The matrix to be multiplied by CTO/CFROM. See TYPE for the storage type. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
INFO (output) INTEGER 0 - successful exit .LT.0 - if INFO = -i, the i-th argument had an illegal value. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLASCL.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLASCL.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTERF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASQ1.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD8.Run(), DotNumerics.LinearAlgebra.CSLapack.DSBEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD3.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALSD.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEDC.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD1.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELS.Run(), DotNumerics.LinearAlgebra.CSLapack.DSBEVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYEVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DBDSDC.Run(), DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALS0.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELSY.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELSD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLASD6.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLASCL._lsame private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLASCL._dlamch private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DLASCL._xerbla private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLASCL.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLASCL.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlascl.cs