Doc: IGLib EXTENDED: AForge.Imaging.Filters.Merge Class Reference
AForge.Imaging.Filters.Merge Class Reference
Merge filter - get MAX of pixels in two images.
Public Member Functions
Merge ()
Initializes a new instance of the Merge class
Merge (Bitmap overlayImage)
Initializes a new instance of the Merge class.
Merge (UnmanagedImage unmanagedOverlayImage)
Initializes a new instance of the Merge class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlaceFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image, UnmanagedImage overlay)
Process the filter on the specified image.
Protected Member Functions inherited from AForge.Imaging.Filters.BaseInPlaceFilter2
BaseInPlaceFilter2 ()
Initializes a new instance of the BaseInPlaceFilter2 class.
BaseInPlaceFilter2 (Bitmap overlayImage)
Initializes a new instance of the BaseInPlaceFilter2 class.
BaseInPlaceFilter2 (UnmanagedImage unmanagedOverlayImage)
Initializes a new instance of the BaseInPlaceFilter2 class.
override unsafe void ProcessFilter (UnmanagedImage image)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.BaseInPlaceFilter2
Bitmap OverlayImage [get, set]
Overlay image.
UnmanagedImage UnmanagedOverlayImage [get, set]
Unmanaged overlay image.
Properties inherited from AForge.Imaging.Filters.BaseInPlaceFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Member Functions
void InitFormatTranslations ()
Private Attributes
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Merge filter - get MAX of pixels in two images.
The merge filter takes two images (source and overlay images) of the same size and pixel format and produces an image, where each pixel equals to the maximum value of corresponding pixels from provided images.
The filter accepts 8 and 16 bpp grayscale images and 24, 32, 48 and 64 bpp color images for processing.
Sample usage:
// create filter
Merge filter = new Merge(overlayImage);
// apply the filter
Bitmap resultImage = filter.Apply(sourceImage);
Source image:
Overlay image:
Result image:
See also
Intersect, Difference, Add, Subtract
Constructor & Destructor Documentation
Merge() [1/3]
AForge.Imaging.Filters.Merge.Merge () inline
Initializes a new instance of the Merge class
References AForge.Imaging.Filters.Merge.InitFormatTranslations().
Merge() [2/3]
AForge.Imaging.Filters.Merge.Merge (Bitmap overlayImage) inline
Initializes a new instance of the Merge class.
Parameters
overlayImage Overlay image.
References AForge.Imaging.Filters.Merge.InitFormatTranslations().
Merge() [3/3]
AForge.Imaging.Filters.Merge.Merge (UnmanagedImage unmanagedOverlayImage) inline
Initializes a new instance of the Merge class.
Parameters
unmanagedOverlayImage Unmanaged overlay image.
References AForge.Imaging.Filters.Merge.InitFormatTranslations().
Member Function Documentation
InitFormatTranslations()
void AForge.Imaging.Filters.Merge.InitFormatTranslations () inline private
References AForge.Imaging.Filters.Merge.formatTranslations.
Referenced by AForge.Imaging.Filters.Merge.Merge().
ProcessFilter()
override unsafe void AForge.Imaging.Filters.Merge.ProcessFilter (UnmanagedImage image, UnmanagedImage overlay) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
overlay Overlay image data.
Implements AForge.Imaging.Filters.BaseInPlaceFilter2.
References AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
Member Data Documentation
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.Merge.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.Merge.InitFormatTranslations().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.Merge.FormatTranslations get
Format translations dictionary.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/2 Source filters/Merge.cs