Doc: IGLib EXTENDED: Test.RootsTest Class Reference
Test.RootsTest Class Reference
Public Member Functions
void RootOfEi ()
void RootOfPsi ()
void RootOfJ0 ()
void MultiRootMathworksExample ()
void MultiRootExtendedRosenbock ()
void MultiRootTrigExp ()
Private Member Functions
double[] GetRandomStartingVector (Random rng, int d)
Member Function Documentation
RootOfEi()
void Test.RootsTest.RootOfEi () inline
References Meta.Numerics.Analysis.FunctionMath.FindZero(), Meta.Numerics.Interval.FromEndpoints(), and Meta.Numerics.Functions.AdvancedMath.IntegralEi().
RootOfPsi()
void Test.RootsTest.RootOfPsi () inline
References Meta.Numerics.Analysis.FunctionMath.FindZero(), and Meta.Numerics.Functions.AdvancedMath.Psi().
RootOfJ0()
void Test.RootsTest.RootOfJ0 () inline
References Meta.Numerics.Functions.AdvancedMath.BesselJ(), Meta.Numerics.Analysis.FunctionMath.FindZero(), and Meta.Numerics.Interval.FromEndpoints().
MultiRootMathworksExample()
void Test.RootsTest.MultiRootMathworksExample () inline
References Meta.Numerics.Analysis.FunctionMath.FindZero(), and Test.RootsTest.GetRandomStartingVector().
MultiRootExtendedRosenbock()
void Test.RootsTest.MultiRootExtendedRosenbock () inline
References Meta.Numerics.Analysis.FunctionMath.FindZero(), Test.RootsTest.GetRandomStartingVector(), and Meta.Numerics.MoreMath.Pow().
MultiRootTrigExp()
void Test.RootsTest.MultiRootTrigExp () inline
References Meta.Numerics.Analysis.FunctionMath.FindZero(), Test.RootsTest.GetRandomStartingVector(), and Meta.Numerics.MoreMath.Pow().
GetRandomStartingVector()
double [] Test.RootsTest.GetRandomStartingVector (Random rng, int d) inline private
Referenced by Test.RootsTest.MultiRootExtendedRosenbock(), Test.RootsTest.MultiRootMathworksExample(), and Test.RootsTest.MultiRootTrigExp().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/RootsTest.cs