Doc: IGLib EXTENDED: NUnit.Engine.Services.TestAgency.AgentDataBase Class Reference
NUnit.Engine.Services.TestAgency.AgentDataBase Class Reference
A simple class that tracks data about this agencies active and available agents
Public Member Functions
void Add (AgentRecord r)
void Remove (Guid agentId)
void Clear ()
Properties
AgentRecord this[Guid id] [get, set]
AgentRecord this[ITestAgent agent] [get]
Private Attributes
Dictionary< Guid, AgentRecord > agentData = new Dictionary<Guid, AgentRecord>()
Detailed Description
A simple class that tracks data about this agencies active and available agents
Member Function Documentation
Add()
void NUnit.Engine.Services.TestAgency.AgentDataBase.Add (AgentRecord r) inline
References NUnit.Engine.Services.TestAgency.AgentDataBase.agentData, and NUnit.Engine.Services.TestAgency.AgentRecord.Id.
Referenced by NUnit.Engine.Services.TestAgency.LaunchAgentProcess().
Remove()
void NUnit.Engine.Services.TestAgency.AgentDataBase.Remove (Guid agentId) inline
References NUnit.Engine.Services.TestAgency.AgentDataBase.agentData.
Clear()
void NUnit.Engine.Services.TestAgency.AgentDataBase.Clear () inline
References NUnit.Engine.Services.TestAgency.AgentDataBase.agentData.
Member Data Documentation
agentData
Dictionary<Guid, AgentRecord> NUnit.Engine.Services.TestAgency.AgentDataBase.agentData = new Dictionary<Guid, AgentRecord>() private
Referenced by NUnit.Engine.Services.TestAgency.AgentDataBase.Add(), NUnit.Engine.Services.TestAgency.AgentDataBase.Clear(), and NUnit.Engine.Services.TestAgency.AgentDataBase.Remove().
Property Documentation
this[Guid id]
AgentRecord NUnit.Engine.Services.TestAgency.AgentDataBase.this[Guid id] get set
this[ITestAgent agent]
AgentRecord NUnit.Engine.Services.TestAgency.AgentDataBase.this[ITestAgent agent] get
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Services/TestAgency.cs