Doc: IGLib EXTENDED: alglib.variancetests Class Reference
alglib.variancetests Class Reference
Static Public Member Functions
static void ftest (double[] x, int n, double[] y, int m, ref double bothtails, ref double lefttail, ref double righttail)
static void onesamplevariancetest (double[] x, int n, double variance, ref double bothtails, ref double lefttail, ref double righttail)
static void ftest (double[] x, int n, double[] y, int m, ref double bothtails, ref double lefttail, ref double righttail)
static void onesamplevariancetest (double[] x, int n, double variance, ref double bothtails, ref double lefttail, ref double righttail)
Member Function Documentation
ftest() [1/2]
static void alglib.variancetests.ftest (double[] x, int n, double[] y, int m, ref double bothtails, ref double lefttail, ref double righttail) inline static
References alglib.fdistr.fdistribution(), and alglib.math.sqr().
Referenced by alglib.ftest().
onesamplevariancetest() [1/2]
static void alglib.variancetests.onesamplevariancetest (double[] x, int n, double variance, ref double bothtails, ref double lefttail, ref double righttail) inline static
References alglib.chisquaredistr.chisquaredistribution(), and alglib.math.sqr().
Referenced by alglib.onesamplevariancetest().
ftest() [2/2]
static void alglib.variancetests.ftest (double[] x, int n, double[] y, int m, ref double bothtails, ref double lefttail, ref double righttail) inline static
References alglib.fdistr.fdistribution(), and alglib.math.sqr().
onesamplevariancetest() [2/2]
static void alglib.variancetests.onesamplevariancetest (double[] x, int n, double variance, ref double bothtails, ref double lefttail, ref double righttail) inline static
References alglib.chisquaredistr.chisquaredistribution(), and alglib.math.sqr().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/statistics.cs