Doc: IGLib EXTENDED: RCXTest.MainForm Class Reference
RCXTest.MainForm Class Reference
Public Member Functions
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void connectButton_Click (object sender, EventArgs e)
void disconnectButton_Click (object sender, EventArgs e)
void EnableConnectionControls (bool enable)
void playButton_Click (object sender, EventArgs e)
void getValueButton_Click (object sender, EventArgs e)
void clearSensorButton_Click (object sender, EventArgs e)
void setSensorTypeButton_Click (object sender, EventArgs e)
void setSensorModeButton_Click (object sender, EventArgs e)
void motorOnButton_Click (object sender, EventArgs e)
void motorOffButton_Click (object sender, EventArgs e)
void turnDeviceOffButton_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
RCXBrick rcx = new RCXBrick()
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.Button connectButton
System.Windows.Forms.Button disconnectButton
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.Label label1
System.Windows.Forms.Label label2
System.Windows.Forms.TextBox romVersionBox
System.Windows.Forms.Label label3
System.Windows.Forms.TextBox firmwareVersionBox
System.Windows.Forms.TextBox powerBox
System.Windows.Forms.GroupBox groupBox3
System.Windows.Forms.ComboBox soundTypeCombo
System.Windows.Forms.Button playButton
System.Windows.Forms.GroupBox groupBox4
System.Windows.Forms.Button getValueButton
System.Windows.Forms.ComboBox sensorCombo
System.Windows.Forms.TextBox valueBox
System.Windows.Forms.Label label4
System.Windows.Forms.Button clearSensorButton
System.Windows.Forms.ComboBox sensorTypeCombo
System.Windows.Forms.Label label5
System.Windows.Forms.Button setSensorTypeButton
System.Windows.Forms.Button setSensorModeButton
System.Windows.Forms.ComboBox sensorModeCombo
System.Windows.Forms.Label label6
System.Windows.Forms.GroupBox groupBox5
System.Windows.Forms.ComboBox motorCombo
System.Windows.Forms.ComboBox directionCombo
System.Windows.Forms.Label label7
System.Windows.Forms.Button motorOffButton
System.Windows.Forms.Button motorOnButton
System.Windows.Forms.ComboBox powerCombo
System.Windows.Forms.Label label8
System.Windows.Forms.Button turnDeviceOffButton
Static Private Attributes
static RCXBrick.Motor[] motors
Constructor & Destructor Documentation
MainForm()
RCXTest.MainForm.MainForm () inline
References RCXTest.MainForm.directionCombo, RCXTest.MainForm.InitializeComponent(), RCXTest.MainForm.motorCombo, RCXTest.MainForm.powerCombo, RCXTest.MainForm.sensorCombo, RCXTest.MainForm.sensorModeCombo, RCXTest.MainForm.sensorTypeCombo, and RCXTest.MainForm.soundTypeCombo.
Member Function Documentation
connectButton_Click()
void RCXTest.MainForm.connectButton_Click (object sender, EventArgs e) inline private
References AForge.Robotics.Lego.RCXBrick.Connect(), RCXTest.MainForm.EnableConnectionControls(), RCXTest.MainForm.firmwareVersionBox, AForge.Robotics.Lego.RCXBrick.GetBatteryPower(), AForge.Robotics.Lego.RCXBrick.GetVersion(), RCXTest.MainForm.powerBox, RCXTest.MainForm.rcx, RCXTest.MainForm.romVersionBox, and AForge.Robotics.Lego.RCXBrick.SetTransmitterRange().
Referenced by RCXTest.MainForm.InitializeComponent().
disconnectButton_Click()
void RCXTest.MainForm.disconnectButton_Click (object sender, EventArgs e) inline private
References AForge.Robotics.Lego.RCXBrick.Disconnect(), RCXTest.MainForm.EnableConnectionControls(), and RCXTest.MainForm.rcx.
Referenced by RCXTest.MainForm.InitializeComponent().
EnableConnectionControls()
void RCXTest.MainForm.EnableConnectionControls (bool enable) inline private
References RCXTest.MainForm.clearSensorButton, RCXTest.MainForm.connectButton, RCXTest.MainForm.disconnectButton, RCXTest.MainForm.getValueButton, RCXTest.MainForm.motorOffButton, RCXTest.MainForm.motorOnButton, RCXTest.MainForm.playButton, RCXTest.MainForm.setSensorModeButton, RCXTest.MainForm.setSensorTypeButton, and RCXTest.MainForm.turnDeviceOffButton.
Referenced by RCXTest.MainForm.connectButton_Click(), RCXTest.MainForm.disconnectButton_Click(), and RCXTest.MainForm.turnDeviceOffButton_Click().
playButton_Click()
void RCXTest.MainForm.playButton_Click (object sender, EventArgs e) inline private
References AForge.Robotics.Lego.RCXBrick.PlaySound(), RCXTest.MainForm.rcx, and RCXTest.MainForm.soundTypeCombo.
Referenced by RCXTest.MainForm.InitializeComponent().
getValueButton_Click()
void RCXTest.MainForm.getValueButton_Click (object sender, EventArgs e) inline private
References AForge.Robotics.Lego.RCXBrick.GetSensorValue(), RCXTest.MainForm.rcx, RCXTest.MainForm.sensorCombo, and RCXTest.MainForm.valueBox.
Referenced by RCXTest.MainForm.InitializeComponent().
clearSensorButton_Click()
void RCXTest.MainForm.clearSensorButton_Click (object sender, EventArgs e) inline private
References AForge.Robotics.Lego.RCXBrick.ClearSensor(), RCXTest.MainForm.rcx, and RCXTest.MainForm.sensorCombo.
Referenced by RCXTest.MainForm.InitializeComponent().
setSensorTypeButton_Click()
void RCXTest.MainForm.setSensorTypeButton_Click (object sender, EventArgs e) inline private
References RCXTest.MainForm.rcx, RCXTest.MainForm.sensorCombo, RCXTest.MainForm.sensorTypeCombo, and AForge.Robotics.Lego.RCXBrick.SetSensorType().
Referenced by RCXTest.MainForm.InitializeComponent().
setSensorModeButton_Click()
void RCXTest.MainForm.setSensorModeButton_Click (object sender, EventArgs e) inline private
References RCXTest.MainForm.rcx, RCXTest.MainForm.sensorCombo, RCXTest.MainForm.sensorModeCombo, and AForge.Robotics.Lego.RCXBrick.SetSensorMode().
Referenced by RCXTest.MainForm.InitializeComponent().
motorOnButton_Click()
void RCXTest.MainForm.motorOnButton_Click (object sender, EventArgs e) inline private
References RCXTest.MainForm.directionCombo, RCXTest.MainForm.motorCombo, RCXTest.MainForm.motors, RCXTest.MainForm.powerCombo, RCXTest.MainForm.rcx, AForge.Robotics.Lego.RCXBrick.SetMotorDirection(), AForge.Robotics.Lego.RCXBrick.SetMotorOn(), and AForge.Robotics.Lego.RCXBrick.SetMotorPower().
Referenced by RCXTest.MainForm.InitializeComponent().
motorOffButton_Click()
void RCXTest.MainForm.motorOffButton_Click (object sender, EventArgs e) inline private
References RCXTest.MainForm.motorCombo, RCXTest.MainForm.motors, RCXTest.MainForm.rcx, and AForge.Robotics.Lego.RCXBrick.SetMotorOn().
Referenced by RCXTest.MainForm.InitializeComponent().
turnDeviceOffButton_Click()
void RCXTest.MainForm.turnDeviceOffButton_Click (object sender, EventArgs e) inline private
References AForge.Robotics.Lego.RCXBrick.Disconnect(), RCXTest.MainForm.EnableConnectionControls(), AForge.Robotics.Lego.RCXBrick.PowerOff(), and RCXTest.MainForm.rcx.
Referenced by RCXTest.MainForm.InitializeComponent().
Dispose()
override void RCXTest.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References RCXTest.MainForm.components.
InitializeComponent()
void RCXTest.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References RCXTest.MainForm.clearSensorButton, RCXTest.MainForm.clearSensorButton_Click(), RCXTest.MainForm.connectButton, RCXTest.MainForm.connectButton_Click(), RCXTest.MainForm.directionCombo, RCXTest.MainForm.disconnectButton, RCXTest.MainForm.disconnectButton_Click(), RCXTest.MainForm.firmwareVersionBox, RCXTest.MainForm.getValueButton, RCXTest.MainForm.getValueButton_Click(), RCXTest.MainForm.groupBox1, RCXTest.MainForm.groupBox2, RCXTest.MainForm.groupBox3, RCXTest.MainForm.groupBox4, RCXTest.MainForm.groupBox5, RCXTest.MainForm.label1, RCXTest.MainForm.label2, RCXTest.MainForm.label3, RCXTest.MainForm.label4, RCXTest.MainForm.label5, RCXTest.MainForm.label6, RCXTest.MainForm.label7, RCXTest.MainForm.label8, RCXTest.MainForm.motorCombo, RCXTest.MainForm.motorOffButton, RCXTest.MainForm.motorOffButton_Click(), RCXTest.MainForm.motorOnButton, RCXTest.MainForm.motorOnButton_Click(), RCXTest.MainForm.playButton, RCXTest.MainForm.playButton_Click(), RCXTest.MainForm.powerBox, RCXTest.MainForm.powerCombo, RCXTest.MainForm.romVersionBox, RCXTest.MainForm.sensorCombo, RCXTest.MainForm.sensorModeCombo, RCXTest.MainForm.sensorTypeCombo, RCXTest.MainForm.setSensorModeButton, RCXTest.MainForm.setSensorModeButton_Click(), RCXTest.MainForm.setSensorTypeButton, RCXTest.MainForm.setSensorTypeButton_Click(), RCXTest.MainForm.soundTypeCombo, RCXTest.MainForm.turnDeviceOffButton, RCXTest.MainForm.turnDeviceOffButton_Click(), and RCXTest.MainForm.valueBox.
Referenced by RCXTest.MainForm.MainForm().
Member Data Documentation
rcx
RCXBrick RCXTest.MainForm.rcx = new RCXBrick() private
Referenced by RCXTest.MainForm.clearSensorButton_Click(), RCXTest.MainForm.connectButton_Click(), RCXTest.MainForm.disconnectButton_Click(), RCXTest.MainForm.getValueButton_Click(), RCXTest.MainForm.motorOffButton_Click(), RCXTest.MainForm.motorOnButton_Click(), RCXTest.MainForm.playButton_Click(), RCXTest.MainForm.setSensorModeButton_Click(), RCXTest.MainForm.setSensorTypeButton_Click(), and RCXTest.MainForm.turnDeviceOffButton_Click().
motors
RCXBrick.Motor [] RCXTest.MainForm.motors static private
Initial value:
= new RCXBrick.Motor[] {
            RCXBrick.Motor.A, RCXBrick.Motor.B, RCXBrick.Motor.C,
            RCXBrick.Motor.AC
        }
Referenced by RCXTest.MainForm.motorOffButton_Click(), and RCXTest.MainForm.motorOnButton_Click().
components
System.ComponentModel.IContainer RCXTest.MainForm.components = null private
Required designer variable.
Referenced by RCXTest.MainForm.Dispose().
connectButton
System.Windows.Forms.Button RCXTest.MainForm.connectButton private
Referenced by RCXTest.MainForm.EnableConnectionControls(), and RCXTest.MainForm.InitializeComponent().
disconnectButton
System.Windows.Forms.Button RCXTest.MainForm.disconnectButton private
Referenced by RCXTest.MainForm.EnableConnectionControls(), and RCXTest.MainForm.InitializeComponent().
groupBox1
System.Windows.Forms.GroupBox RCXTest.MainForm.groupBox1 private
Referenced by RCXTest.MainForm.InitializeComponent().
groupBox2
System.Windows.Forms.GroupBox RCXTest.MainForm.groupBox2 private
Referenced by RCXTest.MainForm.InitializeComponent().
label1
System.Windows.Forms.Label RCXTest.MainForm.label1 private
Referenced by RCXTest.MainForm.InitializeComponent().
label2
System.Windows.Forms.Label RCXTest.MainForm.label2 private
Referenced by RCXTest.MainForm.InitializeComponent().
romVersionBox
System.Windows.Forms.TextBox RCXTest.MainForm.romVersionBox private
Referenced by RCXTest.MainForm.connectButton_Click(), and RCXTest.MainForm.InitializeComponent().
label3
System.Windows.Forms.Label RCXTest.MainForm.label3 private
Referenced by RCXTest.MainForm.InitializeComponent().
firmwareVersionBox
System.Windows.Forms.TextBox RCXTest.MainForm.firmwareVersionBox private
Referenced by RCXTest.MainForm.connectButton_Click(), and RCXTest.MainForm.InitializeComponent().
powerBox
System.Windows.Forms.TextBox RCXTest.MainForm.powerBox private
Referenced by RCXTest.MainForm.connectButton_Click(), and RCXTest.MainForm.InitializeComponent().
groupBox3
System.Windows.Forms.GroupBox RCXTest.MainForm.groupBox3 private
Referenced by RCXTest.MainForm.InitializeComponent().
soundTypeCombo
System.Windows.Forms.ComboBox RCXTest.MainForm.soundTypeCombo private
Referenced by RCXTest.MainForm.InitializeComponent(), RCXTest.MainForm.MainForm(), and RCXTest.MainForm.playButton_Click().
playButton
System.Windows.Forms.Button RCXTest.MainForm.playButton private
Referenced by RCXTest.MainForm.EnableConnectionControls(), and RCXTest.MainForm.InitializeComponent().
groupBox4
System.Windows.Forms.GroupBox RCXTest.MainForm.groupBox4 private
Referenced by RCXTest.MainForm.InitializeComponent().
getValueButton
System.Windows.Forms.Button RCXTest.MainForm.getValueButton private
Referenced by RCXTest.MainForm.EnableConnectionControls(), and RCXTest.MainForm.InitializeComponent().
sensorCombo
System.Windows.Forms.ComboBox RCXTest.MainForm.sensorCombo private
Referenced by RCXTest.MainForm.clearSensorButton_Click(), RCXTest.MainForm.getValueButton_Click(), RCXTest.MainForm.InitializeComponent(), RCXTest.MainForm.MainForm(), RCXTest.MainForm.setSensorModeButton_Click(), and RCXTest.MainForm.setSensorTypeButton_Click().
valueBox
System.Windows.Forms.TextBox RCXTest.MainForm.valueBox private
Referenced by RCXTest.MainForm.getValueButton_Click(), and RCXTest.MainForm.InitializeComponent().
label4
System.Windows.Forms.Label RCXTest.MainForm.label4 private
Referenced by RCXTest.MainForm.InitializeComponent().
clearSensorButton
System.Windows.Forms.Button RCXTest.MainForm.clearSensorButton private
Referenced by RCXTest.MainForm.EnableConnectionControls(), and RCXTest.MainForm.InitializeComponent().
sensorTypeCombo
System.Windows.Forms.ComboBox RCXTest.MainForm.sensorTypeCombo private
Referenced by RCXTest.MainForm.InitializeComponent(), RCXTest.MainForm.MainForm(), and RCXTest.MainForm.setSensorTypeButton_Click().
label5
System.Windows.Forms.Label RCXTest.MainForm.label5 private
Referenced by RCXTest.MainForm.InitializeComponent().
setSensorTypeButton
System.Windows.Forms.Button RCXTest.MainForm.setSensorTypeButton private
Referenced by RCXTest.MainForm.EnableConnectionControls(), and RCXTest.MainForm.InitializeComponent().
setSensorModeButton
System.Windows.Forms.Button RCXTest.MainForm.setSensorModeButton private
Referenced by RCXTest.MainForm.EnableConnectionControls(), and RCXTest.MainForm.InitializeComponent().
sensorModeCombo
System.Windows.Forms.ComboBox RCXTest.MainForm.sensorModeCombo private
Referenced by RCXTest.MainForm.InitializeComponent(), RCXTest.MainForm.MainForm(), and RCXTest.MainForm.setSensorModeButton_Click().
label6
System.Windows.Forms.Label RCXTest.MainForm.label6 private
Referenced by RCXTest.MainForm.InitializeComponent().
groupBox5
System.Windows.Forms.GroupBox RCXTest.MainForm.groupBox5 private
Referenced by RCXTest.MainForm.InitializeComponent().
motorCombo
System.Windows.Forms.ComboBox RCXTest.MainForm.motorCombo private
Referenced by RCXTest.MainForm.InitializeComponent(), RCXTest.MainForm.MainForm(), RCXTest.MainForm.motorOffButton_Click(), and RCXTest.MainForm.motorOnButton_Click().
directionCombo
System.Windows.Forms.ComboBox RCXTest.MainForm.directionCombo private
Referenced by RCXTest.MainForm.InitializeComponent(), RCXTest.MainForm.MainForm(), and RCXTest.MainForm.motorOnButton_Click().
label7
System.Windows.Forms.Label RCXTest.MainForm.label7 private
Referenced by RCXTest.MainForm.InitializeComponent().
motorOffButton
System.Windows.Forms.Button RCXTest.MainForm.motorOffButton private
Referenced by RCXTest.MainForm.EnableConnectionControls(), and RCXTest.MainForm.InitializeComponent().
motorOnButton
System.Windows.Forms.Button RCXTest.MainForm.motorOnButton private
Referenced by RCXTest.MainForm.EnableConnectionControls(), and RCXTest.MainForm.InitializeComponent().
powerCombo
System.Windows.Forms.ComboBox RCXTest.MainForm.powerCombo private
Referenced by RCXTest.MainForm.InitializeComponent(), RCXTest.MainForm.MainForm(), and RCXTest.MainForm.motorOnButton_Click().
label8
System.Windows.Forms.Label RCXTest.MainForm.label8 private
Referenced by RCXTest.MainForm.InitializeComponent().
turnDeviceOffButton
System.Windows.Forms.Button RCXTest.MainForm.turnDeviceOffButton private
Referenced by RCXTest.MainForm.EnableConnectionControls(), and RCXTest.MainForm.InitializeComponent().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Robotics/Lego/RCXTest/MainForm.cs
shelldev/lib_ann/aforge.net/Samples/Robotics/Lego/RCXTest/MainForm.Designer.cs