Doc: IGLib EXTENDED: IG.Forms.TestTcpServer Class Reference
IG.Forms.TestTcpServer Class Reference
Public Member Functions
TestTcpServer ()
Constructor with default IP address and port (local:8000).
TestTcpServer (string IP, int port)
void StopRequest ()
A gentle way to stop the server.
void StartServer ()
void Report (string str)
void ReportMarked (string str)
void ReportError (string str)
void ReportError (Exception e, string additionalmessage)
void ReportError (Exception e)
Public Attributes
int Port = 8000
string IPstr = "127.0.0.1"
int ID =0
string Name = ""
bool SingleClient = true
bool TooManyConnections = false
TestTcpMultiThreadedServer parent
Thread ServerThread =null
Parent that launhed this server instance.
Properties
ConsoleForm ServerConsole [get, set]
Returns the server's own console.
Private Member Functions
void SendData (string Data)
bool ConsoleReady ()
void CloseConsoleHandler (object sender, System.EventArgs e)
Private Attributes
bool StopRequested = false
int MaxReportLength = 60
string ReceivedMessage =null
string ReceivedData =null
bool Stop =false
int NumRequests = 0
TcpListener listener = null
NetworkStream stream = null
BinaryWriter SWriter = null
BinaryReader SReader = null
IG.Forms.ConsoleForm servercons = null
IG.Forms.ConsoleForm auxcons
int reccount = 0
Static Private Attributes
static int numinstances = 0
static int totcount = 0
Constructor & Destructor Documentation
TestTcpServer() [1/2]
IG.Forms.TestTcpServer.TestTcpServer () inline
Constructor with default IP address and port (local:8000).
References IG.Forms.TestTcpServer.ID, IG.Forms.TestTcpServer.Name, and IG.Forms.TestTcpServer.numinstances.
TestTcpServer() [2/2]
IG.Forms.TestTcpServer.TestTcpServer (string IP, int port) inline
References IG.Forms.TestTcpServer.ID, IG.Forms.TestTcpServer.IPstr, IG.Forms.TestTcpServer.Name, IG.Forms.TestTcpServer.numinstances, and IG.Forms.TestTcpServer.Port.
Member Function Documentation
StopRequest()
void IG.Forms.TestTcpServer.StopRequest () inline
A gentle way to stop the server.
References IG.Forms.TestTcpServer.StopRequested.
SendData()
void IG.Forms.TestTcpServer.SendData (string Data) inline private
References IG.Forms.TestTcpServer.MaxReportLength, IG.Forms.ClientMessages.ReadyClient, IG.Forms.ClientMessages.ReceivedClient, IG.Forms.TestTcpServer.ReceivedMessage, IG.Forms.TestTcpServer.Report(), IG.Forms.TestTcpServer.ReportError(), IG.Forms.ServerMessages.SendSrv, IG.Forms.TestTcpServer.SReader, and IG.Forms.TestTcpServer.SWriter.
StartServer()
void IG.Forms.TestTcpServer.StartServer () inline
References IG.Forms.ConsoleForm.CloseForm(), IG.Forms.ServerMessages.ConnectAcknowledged, IG.Forms.ServerMessages.DisconnectAcknowledged, IG.Forms.ClientMessages.DisconnectClient, IG.Forms.ServerMessages.DisconnectSrv, IG.Forms.TestTcpServer.IPstr, IG.Forms.TestTcpServer.listener, IG.Forms.TestTcpServer.MaxReportLength, IG.Forms.TestTcpServer.NumRequests, IG.Forms.TestTcpServer.parent, IG.Forms.ServerMessages.PingAcknowledgeSrv, IG.Forms.ClientMessages.PingRequestClient, IG.Forms.TestTcpServer.Port, IG.Forms.ClientMessages.ReadyClient, IG.Forms.ServerMessages.ReadySrv, IG.Forms.TestTcpServer.ReceivedData, IG.Forms.TestTcpServer.ReceivedMessage, IG.Forms.ServerMessages.ReceivedSrv, IG.Forms.TestTcpServer.Report(), IG.Forms.TestTcpServer.ReportError(), IG.Forms.ConsoleForm.ReportError(), IG.Forms.ClientMessages.RequestConnect, IG.Forms.ClientMessages.SendClient, IG.Forms.TestTcpServer.servercons, IG.Forms.TestTcpServer.ServerConsole, IG.Forms.TestTcpServer.ServerThread, IG.Forms.TestTcpServer.SReader, IG.Forms.TestTcpServer.Stop, IG.Forms.TestTcpServer.StopRequested, IG.Forms.TestTcpServer.stream, IG.Forms.TestTcpServer.SWriter, IG.Forms.TestTcpServer.TooManyConnections, IG.Forms.ServerMessages.TooManyConnectionsSrv, and IG.Forms.ServerMessages.UnknownRequestSrv.
Referenced by IG.Forms.TestTcpMultiThreadedServer.ServerThreadFunc().
ConsoleReady()
bool IG.Forms.TestTcpServer.ConsoleReady () inline private
References IG.Forms.TestTcpServer.servercons.
Referenced by IG.Forms.TestTcpServer.Report(), IG.Forms.TestTcpServer.ReportError(), and IG.Forms.TestTcpServer.ReportMarked().
CloseConsoleHandler()
void IG.Forms.TestTcpServer.CloseConsoleHandler (object sender, System.EventArgs e) inline private
Report()
void IG.Forms.TestTcpServer.Report (string str) inline
References IG.Forms.TestTcpServer.auxcons, IG.Forms.TestTcpServer.ConsoleReady(), IG.Forms.UtilForms.Reporter, IG.Forms.TestTcpServer.ServerConsole, IG.Forms.ConsoleForm.Style, and IG.Forms.ConsoleForm.WriteLine().
Referenced by IG.Forms.TestTcpServer.SendData(), and IG.Forms.TestTcpServer.StartServer().
ReportMarked()
void IG.Forms.TestTcpServer.ReportMarked (string str) inline
References IG.Forms.TestTcpServer.auxcons, IG.Forms.TestTcpServer.ConsoleReady(), IG.Forms.UtilForms.Reporter, IG.Forms.TestTcpServer.ServerConsole, IG.Forms.ConsoleForm.Style, and IG.Forms.ConsoleForm.WriteLine().
ReportError() [1/3]
void IG.Forms.TestTcpServer.ReportError (string str) inline
References IG.Forms.TestTcpServer.auxcons, IG.Forms.TestTcpServer.ConsoleReady(), IG.Forms.UtilForms.Reporter, IG.Forms.TestTcpServer.ServerConsole, IG.Forms.ConsoleForm.Style, and IG.Forms.ConsoleForm.WriteLine().
Referenced by IG.Forms.TestTcpServer.ReportError(), IG.Forms.TestTcpServer.SendData(), and IG.Forms.TestTcpServer.StartServer().
ReportError() [2/3]
void IG.Forms.TestTcpServer.ReportError (Exception e, string additionalmessage) inline
References IG.Forms.UtilForms.Reporter, and IG.Forms.TestTcpServer.ReportError().
ReportError() [3/3]
void IG.Forms.TestTcpServer.ReportError (Exception e) inline
References IG.Forms.TestTcpServer.ReportError().
Referenced by IG.Forms.TestTcpServer.ReportError().
Member Data Documentation
Port
int IG.Forms.TestTcpServer.Port = 8000
Referenced by IG.Forms.TestTcpServer.StartServer(), and IG.Forms.TestTcpServer.TestTcpServer().
IPstr
string IG.Forms.TestTcpServer.IPstr = "127.0.0.1"
Referenced by IG.Forms.TestTcpServer.StartServer(), and IG.Forms.TestTcpServer.TestTcpServer().
ID
int IG.Forms.TestTcpServer.ID =0
Referenced by IG.Forms.TestTcpMultiThreadedServer.ServerThreadFunc(), and IG.Forms.TestTcpServer.TestTcpServer().
Name
string IG.Forms.TestTcpServer.Name = ""
Referenced by IG.Forms.TestTcpMultiThreadedServer.ServerThreadFunc(), and IG.Forms.TestTcpServer.TestTcpServer().
SingleClient
bool IG.Forms.TestTcpServer.SingleClient = true
Referenced by IG.Forms.TestTcpMultiThreadedServer.ServerThreadFunc().
TooManyConnections
bool IG.Forms.TestTcpServer.TooManyConnections = false
Referenced by IG.Forms.TestTcpMultiThreadedServer.ServerThreadFunc(), and IG.Forms.TestTcpServer.StartServer().
StopRequested
bool IG.Forms.TestTcpServer.StopRequested = false private
Referenced by IG.Forms.TestTcpServer.StartServer(), and IG.Forms.TestTcpServer.StopRequest().
parent
TestTcpMultiThreadedServer IG.Forms.TestTcpServer.parent
Referenced by IG.Forms.TestTcpMultiThreadedServer.ServerThreadFunc(), and IG.Forms.TestTcpServer.StartServer().
ServerThread
Thread IG.Forms.TestTcpServer.ServerThread =null
Parent that launhed this server instance.
Referenced by IG.Forms.TestTcpServer.StartServer().
MaxReportLength
int IG.Forms.TestTcpServer.MaxReportLength = 60 private
Referenced by IG.Forms.TestTcpServer.SendData(), and IG.Forms.TestTcpServer.StartServer().
numinstances
int IG.Forms.TestTcpServer.numinstances = 0 static private
Referenced by IG.Forms.TestTcpServer.TestTcpServer().
ReceivedMessage
string IG.Forms.TestTcpServer.ReceivedMessage =null private
Referenced by IG.Forms.TestTcpServer.SendData(), and IG.Forms.TestTcpServer.StartServer().
ReceivedData
string IG.Forms.TestTcpServer.ReceivedData =null private
Referenced by IG.Forms.TestTcpServer.StartServer().
Stop
bool IG.Forms.TestTcpServer.Stop =false private
Referenced by IG.Forms.TestTcpServer.StartServer().
NumRequests
int IG.Forms.TestTcpServer.NumRequests = 0 private
Referenced by IG.Forms.TestTcpServer.StartServer().
listener
TcpListener IG.Forms.TestTcpServer.listener = null private
Referenced by IG.Forms.TestTcpServer.StartServer().
stream
NetworkStream IG.Forms.TestTcpServer.stream = null private
Referenced by IG.Forms.TestTcpServer.StartServer().
SWriter
BinaryWriter IG.Forms.TestTcpServer.SWriter = null private
Referenced by IG.Forms.TestTcpServer.SendData(), and IG.Forms.TestTcpServer.StartServer().
SReader
BinaryReader IG.Forms.TestTcpServer.SReader = null private
Referenced by IG.Forms.TestTcpServer.SendData(), and IG.Forms.TestTcpServer.StartServer().
servercons
IG.Forms.ConsoleForm IG.Forms.TestTcpServer.servercons = null private
Referenced by IG.Forms.TestTcpServer.ConsoleReady(), and IG.Forms.TestTcpServer.StartServer().
auxcons
IG.Forms.ConsoleForm IG.Forms.TestTcpServer.auxcons private
Referenced by IG.Forms.TestTcpServer.Report(), IG.Forms.TestTcpServer.ReportError(), and IG.Forms.TestTcpServer.ReportMarked().
reccount
int IG.Forms.TestTcpServer.reccount = 0 private
totcount
int IG.Forms.TestTcpServer.totcount = 0 static private
Property Documentation
ServerConsole
ConsoleForm IG.Forms.TestTcpServer.ServerConsole get set
Returns the server's own console.
Referenced by IG.Forms.TestTcpServer.Report(), IG.Forms.TestTcpServer.ReportError(), IG.Forms.TestTcpServer.ReportMarked(), and IG.Forms.TestTcpServer.StartServer().
The documentation for this class was generated from the following file:
igtest/iglib_sandbox/testserver/server_program.cs