Doc: IGLib EXTENDED: IG.Script.S_12_01_Paper_NeuralOptCasting_00 Class Reference
IG.Script.S_12_01_Paper_NeuralOptCasting_00 Class Reference
Classes
class StoredScriptSettings
In methods of this class you will find all the settings that apply to this script.
Public Member Functions
S_12_01_Paper_NeuralOptCasting_00 ()
virtual string TrainNetwork (string[] arguments)
Trains neural network on the results of simulations.
virtual string TestPlotNetworkResponse (string[] arguments)
Shows some plots of neural network response.
virtual string TestNetworkResponse (string[] arguments)
Tests the approximated response of the neural network.
string PlotVerificationAndTrainingPoints (string[] arguments)
Plot training and verification points on the same graph.
virtual string SolveOpt (string[] arguments)
Solves the final problem.
virtual string TestHtmlGenerator (string[] arguments)
Used for testing of HTML generator.
string PlotEuclideanDistance (string[] arguments)
Plot the smallest Euclidean distances for all training points.
string PlotEuclideanDistanceVRF (string[] arguments)
string PlotInputOutputRelation (string[] arguments)
Plots output and input training points.
virtual string CustomTests (string[] arguments)
override void Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings)
Adds commands to the internal interpreter.
virtual void TestHtmlGenerator (string directoryPath, string cssPath)
Tests the HTML generator. Creates a file named "test.html" in the specified directory.
void PlotRMSErrors (List< IVector > errorsRMSList)
Plots RMS errors on training points during training.
void PlotRMSErrors (List< IVector > errorsRMSList, int whichOut)
Plots RMS errors on training points during training.
void PlotInOutRelation ()
Plots input and output relation on training points.
void PlotInOutRelation (int whichOut, int whichParam)
Plots input and output relation on training points.
void PlotTrainingAndVerificationPointsResponse (int numVerificationPoints, int numTrainingPoints)
Plots the ANN approximation on the verification and training points
void PlotTrainingPointResponse (IVector selectedTrainingPoint, int whichOutput, int whichParameter, double min, double max)
Plots the ANN approximation on the training point.
Parameters
selectedTrainingPoints Training points ID.
whichOutput Which output to plot.
whichParameter Which parameter to plot.
min Minimum range.
max Maximum range.
$A Tako78 Nov12;
void PlotEuclideanDistance (int nearestDistanceFromPoint)
Plot N-th Euclidean distances for all training points.
void PlotEuclideanDistance (int whichOut, List< IVector > smallestDistances, List< IVector > averageDistances)
Plot N-th Euclidean distances for all training points.
void PlotEuclideanDistanceVRF (int nearestDistanceFromPoint)
Plot N-th Euclidean distances for all verification points.
void PlotEuclideanDistanceVRF (int whichOut, List< IVector > averageDistancesVRF)
Plot N-th Euclidean distances for all verification points.
void TestSimulationExecution ()
IVector GetCharacteristicSimulationParameters ()
Creates and returns characteristic simulation parameters.
override void ParSimGetNextNeuralInput (ref IVector simInput)
Generates the next vector of neural input parameters that will be used for calculation of a new training element.
override string ParSimGetSimulationDirectoryPath (int threadIndex)
Returns the simulation directory for the specified parallel calculation thread.
override IResponseEvaluatorVectorSimple ParSimGetSimulator (int threadIndex)
Creates simulator file manager for the simulator that will the specified parallel task.
override void TransfSimulationToNeuralInput (IVector original, ref IVector result)
Transforms the specified vector of simulation input parameters to the vector of neural input parameters and stores the vector to the specified variable.
override void TransfNeuralToSimulationInput (IVector original, ref IVector result)
Transforms the specified vector of neural input parameters to the vector of simulation input parameters and stores the vector to the specified variable.
override void TransfSimulationToNeuralOutput (IVector original, ref IVector result)
Transforms the specified vector of simulation output values (results) to the vector of neural output values and stores the vector to the specified variable.
override void TransfNeuralToSimulationOutput (IVector original, ref IVector result)
Transforms the specified vector of neural output values to the vector of simulation output values (results) and stores the vector to the specified variable.
void CusomTrainingSetExtract (int whichOutput, double minValue, double maxValue, double minError, bool fromTraining, bool fromVerification)
void CustomSensitivityTest (IVector sensTrainingPoint, IVector sensVerificationPoint, int whichOutput, int whichParameter)
Write to csv file results for sensitivity test. Influence of input parameters to output values.
void TrainANN (int annType, int[] hiddenNeurons, int MaxEpochs, int EpochsInBundle, double LearnignRate, double Momentum, double AlphaValue, double InputSafetyFactor, double OutputSafetyFactor, double PercentVerificationPoints)
Train the artificial neural network.
void EuclideanDistanceVRF (int nearestDistanceFromPoint, ref List< IVector > averageDistancesVRF)
Calculates (verification points) Euclidean distnace to the N-th point.
void EuclideanDistance (int nearestDistanceFromPoint, ref List< IVector > distances, ref List< IVector > averageDistances)
Calculates (training points) Euclidean distnace to the N-th point.
Public Member Functions inherited from IG.Script.LoadableScriptShellNeuralIT
LoadableScriptShellNeuralIT ()
override void Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings)
Adds commands to the internal interpreter.
void TrainANN ()
Train the artificial neural network.
void PlotTrainingRmsError (List< NeuralTrainingParameters > trainParameters, bool showMinAndMaxError, bool showMinToMaxError, bool showBestNErrors, int numErrorsShow, int numBoundles)
Plots graph for training Rms errors.
void PlotTrainingMaxError (List< NeuralTrainingParameters > trainParameters, bool showMinAndMaxError, bool showMinToMaxError, bool showBestNErrors, int numErrorsShow, int numBoundles)
Plots graph for training Max errors.
void PlotVerificationRmsError (List< NeuralTrainingParameters > trainParameters, bool showMinAndMaxError, bool showMinToMaxError, bool showBestNErrors, int numErrorsShow, int numBoundles)
Plots graph for verification Rms errors.
void PlotVerificationMaxError (List< NeuralTrainingParameters > trainParameters, bool showMinAndMaxError, bool showMinToMaxError, bool showBestNErrors, int numErrorsShow, int numBoundles)
Plots graph for verification Max errors.
virtual void ApplyPlotSettings (PlotterZedGraph plotter, PlotZedGraphBase plot)
Applies basic plot settings for various kinds of plots.
virtual void ApplyPlotSettingsCurveRGB (PlotterZedGraph plotter, PlotZedgraphCurve plot, double r, double g, double b)
virtual void ApplyPlotSettingsCurve (PlotterZedGraph plotter, PlotZedgraphCurve plot)
Applies basic plot settings for basic kinds of curve plots.
virtual void ApplyPlotSettingsCurve (PlotterZedGraph plotter, PlotZedgraphCurve plot, int i, int max)
Applies basic plot settings for basic kinds of curve plots where groups of curves are plotted.
virtual void ApplyPlotSettingsCurveBlueRed (PlotterZedGraph plotter, PlotZedgraphCurve plot, int i, int max)
Applies basic plot settings for basic kinds of curve plots where groups of curves are plotted.
virtual void ApplyPlotSettingsCurveMonotoneBlue (PlotterZedGraph plotter, PlotZedgraphCurve plot, int i, int max)
virtual void ApplyPlotSettingsCurveMonotoneRed (PlotterZedGraph plotter, PlotZedgraphCurve plot, int i, int max)
virtual void PlotNeuralResponse (IVector parameters, int whichOut, int whichParam, double minParam, double maxParam, int numPoints)
Plots a parametrix stydy of neural network approximated response by plotting dependency of the specified output on the specified parameter.
virtual void PlotNetworkResponse (int numPoints)
Plots some parametric studies of responses generated by the trained network.
virtual void PlotNetworkResponseGrouped (IVector parameters, int whichOut, IBoundingBox parameterBounds, int numPoints)
Plots a parametrix stydy of neural network approximated response by plotting dependency of the specified output on the specified parameter.
virtual void PlotNetworkResponseGrouped (int numPoints)
Plots some parametric studies of responses generated by the trained network.
virtual void PlotAnalysisTable (AnalysisResults[] tabres)
Plots the specified table of analysis results.
virtual void PlotApproximationTable (IVector[][] tabApproximationResults)
Plots the specified table of calculated approximation results.
void PlotVerificationError (bool showErrorInPercentage, bool verificationPoFromFile)
Plots the ANN approximation on verification points and real points.
void PlotVerificationError (bool verificationFromFile, int whichOutput)
Plots the ANN approximation on verification points and real points.
void PlotVerificationError (bool showErrorInPercentage, bool verificationFromFile, int whichOutput)
Plots the ANN approximation on verification points and real points.
void CalculateVerificationError (int whichOut, ref List< IVector > verificationPointsResponse)
Calculates response on verification points.
void CalculateVerificationError (bool verificationFromFile, int whichOut, ref List< IVector > verificationPointsResponse)
Calculates response on verification points.
void PlotTrainingError ()
Plots the ANN approximation on training points and real points.
void PlotTrainingError (int whichOutput)
Plots the ANN approximation on training points and real points.
void PlotTrainingError (bool showErrorInPercentage, int whichOutput)
Plots the ANN approximation on training points and real points.
void CalculateTrainingError (int whichOut, ref List< IVector > trainingPointsResponse)
Calculates response on training points.
void PointsOnLine ()
Network response on the points calculated between two selected points.
void PlotResponseOnLine (IVector p1Training, IVector p2Training, IVector p1Verification, IVector p2Verification, int numPoints)
Network response on the points calculated between two selected points.
void PlotTrainingAndVerificationPointsResponse (List< IVector > selectedTrainingPoints, List< IVector > selectedVerificationPoints, int whichOutput, int whichParameter, double min, double max)
Plots the ANN approcimation on the verification points and/or real points.
SampledDataSet GetVerificationFromApproximator ()
Returns verification points from complete training data set in approximator.
SampledDataSet GetTrainingFromApproximator ()
Returns training points from complete training data set in approximator.
void SensitivityStart ()
Perform sensitiviy test from training and verification data.
void SensitivityPerform (IVector trainingCenterPoint, IVector verificationCenterPoint)
void CenterPointResponse ()
Plots the ANN approcimation on the center point from verification point and/or real point.
void PlotNetworkCenteredPointResponse (IVector trainingCenterPoint, IVector verificationCenterPoint)
Plots the ANN approcimation on the center point from verification point and/or real point.
void CalculateSensitivity (IVector selectedTrainingPoint, IVector selectedVerificationPoint, int whichParameter, double min, double max)
void PlotTrainingAndVerificationPointResponse (IVector selectedTrainingPoint, IVector selectedVerificationPoint, int whichOutput, int whichParameter, double min, double max)
Plots the ANN approcimation on the verification point and real point.
void CenterPoint (INeuralApproximator Approximator, ref IVector inputCenterParameters, bool centerOnTrainingPoint)
Calculate the average center point for each parameter from complete data set.
void CenterPoint (SampledDataSet DataSet, ref IVector inputCenterParameters)
Calculate the average center point for each parameter from complete data set.
virtual string TrainParallelExample (string[] arguments)
Performs parallel training of neural networks with different parameters and default data.
virtual string PlotConvergence (string[] arguments)
Plot different convergences from traininglimits file
virtual string PlotTrainingTime (string[] arguments)
Plot graph sorted on training time.
virtual string PlotVerificationResponse (string[] arguments)
Plot the approximated response of the neural network in the verification points.
virtual string PlotTrainingResponse (string[] arguments)
Plot the approximated response of the neural network in the training points.
virtual string PlotNetworkResponseOnLineAll (string[] arguments)
Plot the approximated responses of the neural network on two selected points and on the points between them.
string PlotNetworkCenteredPoint (string[] arguments)
Pots parametric study on center point from training and/or verification sets.
string Sensitivity (string[] arguments)
Execute sensitivity test and saves to CSV file.
Public Member Functions inherited from IG.Script.LoadableScriptShellNeuralITOriginalBase
LoadableScriptShellNeuralITOriginalBase ()
override void Analyse (Num.IAnalysisResults anRes)
Dummy analysis, jsut throws the exception.
virtual string Test (string[] arguments)
Runs a custom basic test.
virtual string Custom (string[] arguments)
Runs a custom test.
virtual string RunParallelSimulations (string[] arguments)
Runs multiple simulations in parallel threads and saves results in each parallel thread.
virtual string CollectParallelSimulationResults (string[] arguments)
Collects results of simulations run in parallel threads, joins them into a single object and saves them.
override void Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings)
Adds commands to the internal interpreter.
virtual IVector TestApproximation (IVector parameters)
Performs a test approximation at the specified vector of parameters and outputs and returns results.
virtual IVector[][] TestApproximationTable (int numPoints)
Calculates a table of specified number of approximations, with parameters running between two points that are chosen by the algorithm.
virtual IVector[][] TestApproximationTable (IVector param1, IVector param2, int numPoints)
Performs a table of approximatinos between two specified vectors of approximation input parameters, and outputs results. It also returns the table of results (approximated output values in form of vectors).
virtual AnalysisResults TestAnalysis (IVector parameters)
Performs test analysis at the specified optimization parameters and outputs results.
virtual AnalysisResults[] TestAnalysisTable (int numPoints)
Calculates a table of specified number of analyses, with parameters running between two points that are chosen by the algorithm.
virtual AnalysisResults[] TestAnalysisTable (IVector param1, IVector param2, int numPoints)
Performs a table of direct analyses between two specified vectors of optimization parameters, and outputs results. It also returns the table of analysis results.
virtual void OptimizeSimplex ()
virtual void TransfNeuralToOptimizationParameters (IVector neuralParameters, ref IVector optimizationParameters)
Maps input parameters for neural network to optimization input parameters.
virtual void TransfOptimizationToNeuralParameters (IVector optimizationParameters, ref IVector neuralParameters)
Maps optimization input parameters to neural network input parameters.
delegate string ParallelRunDelegate (int threadIndex)
virtual void ParSimBegin (int numThreads)
Launches parallel jobs.
virtual void GatherParallelResults (int numThreads)
Reads results form all parallel threads, gathers them in a single training set, and saves them in the template optimiation directory.
virtual string ParSimGetOptimizationDirectoryPath (int threadIndex)
Returns path to the directory containing optimization data for the specified parallel thread.
virtual string ParSimGetMutexName (int threadIndex)
Returns name of the mutex for locking data on disk that is used by the specified parallel thread.
virtual string ParSimGetParallelResultsFilePath (int threadIndex)
Returns path of the file where resuls of calculation in the specified parallel thread are stored.
virtual string GetParallelResultFilePath ()
Returns path of the file where resuls of calculation in the specified parallel thread are stored.
virtual void ParSimPreparelDirectory (int threadIndex)
Prepares data for running calculations in the parallel thread with the specified index.
void ParSimAddResults (int threadIndex, SampledDataSet results)
Reads results of the specified thread and adds them to the existing training set.
string ParSimRunJob (int threadIndex)
Runs the job in the specified parallel thread.
virtual void ParSimGetNextInput (ref IVector simInput)
Generates the next vector of simulation input parameters that will be used for calculation of a new parallel simulation.
override void TransfSimulationToNeuralInput (IVector original, ref IVector result)
Transforms the specified vector of simulation input parameters to the vector of neural input parameters and stores the vector to the specified variable.
override void TransfNeuralToSimulationInput (IVector original, ref IVector result)
Transforms the specified vector of neural input parameters to the vector of simulation input parameters and stores the vector to the specified variable.
override void TransfSimulationToNeuralOutput (IVector original, ref IVector result)
Transforms the specified vector of simulation output values (results) to the vector of neural output values and stores the vector to the specified variable.
virtual SampledDataElement GetTrainingElement (int i)
Gets the training element with the specified index (chosen out of al training points, including verificaion points).
virtual bool IsVerificationPoint (int trainingPointIndex)
Whether the training point with the specified index is a verification points and has not been used in training.
List< SampledDataElement > GetTrainingElements (bool includeVerificationPoints)
Returns a list of all neural training elements.
List< SampledDataElement > GetTrainingElements (bool includeVerificationPoints, bool includeNonVerificationPoints)
Returns a list of all neural training elements.
virtual void GetNeuralInputPerturbance (double ratio, ref IVector perturbance)
Returns a perturbance vector whose componenets represent magnitudes of perturbances of neural input parameters with the specified relative ratio with corresponding parameters' scaling lengths.
virtual void GetNeuralOutputPerturbance (double ratio, ref IVector perturbance)
Returns a perturbance vector whose componenets represent magnitudes of perturbances of neural output values with the specified relative ratio with corresponding values' scaling lengths.
virtual void GetNeuralInputVector (double relativeComponents, ref IVector inputVector)
Returns an input vector whose components are at specified relative distances (with respect to full range) from lower bounds on componens of input vectors.
virtual void GetNeuralOutputVector (double relativeComponents, ref IVector outputVector)
Returns an output vector whose components are at specified relative distances (with respect to full range) from lower bounds on componens of input vectors.
virtual void GetNeuralInputVector (IVector relativeComponents, ref IVector inputVector)
Returns an input vector whose components are at specified relative distances (with respect to full range) from lower bounds on componens of input vectors.
virtual void GetNeuralOutputVector (IVector relativeComponents, ref IVector outputVector)
Returns an output vector whose components are at specified relative distances (with respect to full range) from lower bounds on componens of input vectors.
virtual void GetNeuralInputRelative (IVector inputVector, ref IVector relativeComponents)
Calculates relative components (running from 0 to 1 within bounds for specified vector component) for the specified vector of neural input parameters.
virtual void GetNeuralOutputRelative (IVector outputVector, ref IVector relativeComponents)
Calculates relative components (running from 0 to 1 within bounds for specified vector component) for the specified vector of neural output values.
virtual double InputDistance (IVector v1, IVector v2)
Returns measure of distance between two vectors in the space of input parameters. Euclidean norm scaled accorging to individual parameter ranges is returned.
virtual double OutputDistance (IVector v1, IVector v2)
Returns measure of distance between two vectors in the space of output parameters. Euclidean norm scaled accorging to individual parameter ranges is returned.
virtual double InputDistance (IVector v1, int trainingPointIndex)
Returns measure of distance between the specified neural input vector and vector of input parameters of the training point with the specified index.
virtual double OutputDistance (IVector v1, int trainingPointIndex)
Returns measure of distance between the specified neural output values vector and vector of output values of the training point with the specified index.
virtual int GetClosestInputIndex (IVector v1, bool includeVerificationPoints)
Returns index of training element with the shortest distance of its input parameters to the specified vector.
virtual int GetClosestOutputIndex (IVector v1, bool includeVerificationPoints)
Returns index of training element with the shortest distance of its output values to the specified vector of output values.
void TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, params IVector[] points)
For each point in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
void TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, bool printIndividualPointsComp, params IVector[] points)
For each point in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
void TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, params SampledDataElement[] points)
For each point (training element) in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
void TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, bool printIndividualPointsComp, params SampledDataElement[] points)
For each point (training element) in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
virtual void NeuralCalculate (params double[] inputParameters)
Calculates approximation at specified input parameters.
virtual void NeuralCalculate (IVector inputParameters)
Calculates approximation at specified input parameters.
virtual void NeuralCalculate (IVector inputParameters, ref IVector outputValues)
Calculates approximation at specified input parameters.
virtual List< SampledDataElement > GetRandomTrainingElements (int numElements, bool includeVerificationPoints)
Creates and returns a list of training elements that are randomly chosen from the current training set. Trainingpoints that are not verification points are always included in the set of points for selection.
virtual List< SampledDataElement > GetRandomTrainingElements (int numElements, bool includeVerificationPoints, bool includeNonVerificationPoints)
Creates and returns a list of training elements that are randomly chosen from the current training set.
virtual List< SampledDataElement > GetRandomTrainingElements (IRandomGenerator rand, int numElements, bool includeVerificationPoints)
Creates and returns a list of training elements that are randomly chosen from the current training set. Trainingpoints that are not verification points are always included in the set of points for selection.
virtual List< SampledDataElement > GetRandomTrainingElements (IRandomGenerator rand, int numElements, bool includeVerificationPoints, bool includeNonVerificationPoints)
Creates and returns a list of training elements that are randomly chosen from the current training set.
virtual IVector GetRandomNeuralInput ()
Creates and returns a random vector of neural input parameters whose elements (components) lie within the lower and upper bounds on parameters.
virtual void GetRandomNeuralInput (IRandomGenerator rand, ref IVector result)
Generates a random vector of neural input parameters whose elements (components) lie within the lower and upper bounds on parameters, and stores it to the specified vector.
virtual IVector GetRandomNeuralInput (IRandomGenerator rand)
Creates and returns a random vector of neural input parameters whose elements (components) lie within the lower and upper bounds on parameters.
virtual void GetRandomNeuralInput (ref IVector result)
Generates a random vector of neural input parameters whose elements (components) lie within the lower and upper bounds on parameters.
virtual IVector GetRandomNeuralOutput ()
Creates and returns a random vector of neural output values whose elements (components) lie within the lower and upper bounds on values.
virtual IVector GetRandomNeuralOutput (IRandomGenerator rand)
Creates and returns a random vector of neural output values whose elements (components) lie within the lower and upper bounds on values.
virtual void GetRandomNeuralOutput (ref IVector result)
Generates a random vector of neural output values whose elements (components) lie within the lower and upper bounds on values.
virtual void GetRandomNeuralOutput (IRandomGenerator rand, ref IVector result)
Generates a random vector of neural output values whose elements (components) lie within the lower and upper bounds on neural output values, and stores it to the specified vector.
virtual void PrepareNeuronsTable (int minNeurons, int maxNeurons, int numNeurons, ref int[] neurpnsTable)
Prepares table of neurons in geometric sequence.
void TrainANN (int annType, int NumNeurons, int MaxEpochs, int EpochsInBundle, double LearnignRate, double Momentum, double InputSafetyFactor, double OutputSafetyFactor, double PercentVerificationPoints)
Train the artificial neural network.
virtual string CreateDistortedModelData (string[] arguments)
Creates data for distorted model and stores the data in the specified directory.
virtual string StochasticCreateInput (string[] arguments)
Creates a sample input file for analysis of influence of stochastic variables.
virtual string StochasticInfluence (string[] arguments)
Analysis influence of stochastivc input parameters with specified means and standard deviations on the output values of the model.
virtual string CreateBinarySampledData (string[] arguments)
Reads sampled data from the standard location and stores it in the same directory in binary form, in the file with extension .bin *_binaryTrainingDataExtension(.
virtual string RestoreBinarySampledData (string[] arguments)
Reads sampled data in binary form from from the standard location and stores it in the same directory in JSON, in the file with extension .jsonrestored (_restoredTrainingDataExtension).
virtual void TestDistances (int referencePointIndex, int maxNumPoints)
Test of distances of a specified number of training points with respect to the training point with specified index, in the input parameters space as well as in the output parameter space.
virtual void TestNeuralSpeed (int numEvaluations)
Performs test of speed of calculation of neural network.
virtual void PrintNeuralData ()
This example demonstrates how to extract data necessary for definition of optimization problems.
void SaveSensitivityCSV ()
Saves sensitivity test in csv file.
Public Member Functions inherited from IG.Script.ScriptShellNeuralWithSimulatorManagers
virtual void InitSimCastingRobert (string rootDirectory, string projectName, string simulationName)
Initializes the data for casting simulation interface.
virtual void InitSimConvectionRobert (string rootDirectory, string projectName, string simulationName)
Initializes the data for Convection simulation interface.
Public Member Functions inherited from IG.Script.LoadableScriptShellNeural
LoadableScriptShellNeural ()
override void Analyse (Num.IAnalysisResults anRes)
Dummy analysis, jsut throws the exception.
Public Member Functions inherited from IG.Script.LoadableScriptShellNeuralBase
LoadableScriptShellNeuralBase ()
override void Analyse (Num.IAnalysisResults anRes)
Dummy analysis, jsut throws the exception.
delegate string ParallelRunDelegate (int threadIndex)
void ParSimAddResults (int threadIndex, SampledDataSet results)
Reads results of the specified thread and adds them to the existing training set.
string ParSimRunJob (int threadIndex)
Runs the job in the specified parallel thread.
List< SampledDataElement > GetTrainingElements (bool includeVerificationPoints)
Returns a list of all neural training elements.
List< SampledDataElement > GetTrainingElements (bool includeVerificationPoints, bool includeNonVerificationPoints)
Returns a list of all neural training elements.
void TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, params IVector[] points)
For each point in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
void TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, bool printIndividualPointsComp, params IVector[] points)
For each point in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
void TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, params SampledDataElement[] points)
For each point (training element) in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
void TestClosestPoints (int numClosestPoints, bool includeVerificationPoints, bool printByComponents, bool printIndividualPointsComp, params SampledDataElement[] points)
For each point (training element) in the specified array, the training points are sorted according to the distance to this point, and data for the specified number of closest points are written.
void TrainANN (int annType, int NumNeurons, int MaxEpochs, int EpochsInBundle, double LearnignRate, double Momentum, double InputSafetyFactor, double OutputSafetyFactor, double PercentVerificationPoints)
Train the artificial neural network.
void SaveSensitivityCSV ()
Saves sensitivity test in csv file.
Public Member Functions inherited from IG.Lib.LoadableScriptShellBase
LoadableScriptShellBase ()
Constructor.
virtual bool RepairSimulationParameters (IVector parameters)
Repairs simulation parameters, if necessary, in such a way that values are consistent with simuation data (e.g. spacing of nodes).
virtual void SimulatorCalculateResponse (IResponseEvaluatorVectorSimple simulator, IVector inputParameters, ref IVector outputValues)
Calculates vector response by the specified simulator, and stores output values to the specified vector variable.
void SimulatorCalculateResponse (IVector parameters, ref IVector outputValues)
Calculates vector response by the main simulator of the script, and stores output values to the specified vector variable.
LoadableScriptShellBase ()
Public Member Functions inherited from IG.Lib.LoadableScriptOptShellBaseControllable
LoadableScriptOptShellBaseControllable ()
Creates a LoadableScriptOptBase object.
Public Member Functions inherited from IG.Lib.LoadableScriptOptBase
LoadableScriptOptBase ()
Creates the LoadableScriptOptBase object.
abstract void Analyse (IAnalysisResults anRes)
Performs direct analysis for optimization problems. This method must be overridden in derived classes where one wants to have direct analysis defined.
Public Member Functions inherited from IG.Lib.LoadableScriptBase
LoadableScriptBase ()
Argument-less constructor. If argument-less constructor is called then initialization is not performed and will be performed later.
string Run (string[] arguments)
Performs the action of this object. Override this in derived classes!
void Initialize (string[] arguments)
Initializes the object. If not called explicitly, this method is automatically called at the first call to the Run method.
virtual string Script_DefaultInitialize (string[] arguments)
Default initialization method for scripts.
virtual string Script_DefaultRun (string[] arguments)
Default run method for the script. Can be used when only installed commands are run by hte script.
virtual ICommandLineApplicationInterpreter Script_CreateInterpreterWithoutCommands ()
Creates and returns an interpreter that can be used as script's internal interpreter for running script's commands.
delegate string Script_CommandDelegate (string[] args)
Delegate for commands that are installed on script's internal interpreter (property Script_Interpreter).
void Script_AddCommand (string commandName, Script_CommandDelegate command, string helpString)
Adds a new internal script command under specified name to the internal interpreter of the current script object.
virtual void Script_AddCommand (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings, string commandName, Script_CommandDelegate command, string helpString)
Adds a new internal script command under specified name to the internal interpreter of the current script object.
string Script_GetHelpString (string scriptCommandName)
Returns help string for internal script command with specified name, or null if help string is not installed for such a command.
void Script_PrintCommandsHelp ()
Prits help for the installed internal commands of the script.
virtual bool Script_ContainsCommand (string commandName)
Returns true if the internal script's interpreter contains a command with specified name, false otherwise.
virtual bool Script_ContainsScriptCommand (string commandName)
Returns true if the specified command is script command (i.e. its first argument is command-name and it is run through the Script_CommandAdapter object).
virtual void Script_RemoveCommand (string commandName)
Removes the specified internal script command from the internal interpreter of the current scripting object.
virtual void Script_RemoveAllCommands ()
Removes ALL internal script commands from the internal interpreter of the current scripting object.
string Script_Run (string[] arguments)
Runs internal script command.
string Script_Run (string commandName, params string[] otherArguments)
Runs internal script command.
virtual void Script_PrintArguments (string messageString, string[] arguments)
Prints the specified array of string arguments (usually passed as command-line arguments).
Public Attributes
int ANNType = 1
int NumNeuronsHidden1 = 40
int NumNeuronsHidden2 = 0
int MaxEpochs = 1000
int EpochsInBundle = 5
double LearnignRate = 0.3
double Momentum = 0.6
double AlphaValue = 1.0
double InputSafetyFactor = 1.35
double OutputSafetyFactor = 1.35
double PercentVerificationPoints = 0.05
int numVerificationLinesOnGraph = 5
int numTrainingLinesOnGraph = 5
int nearestDistanceFrom = 0
bool saveGraphs = false
bool enableLabels = true
bool verificationPointsFromFile = false
bool trainingPointsFromFile = false
bool allReadFromFile = false
Public Attributes inherited from IG.Script.LoadableScriptShellNeuralIT
int ParallelNumServersDefault = 4
int ParallelMaxEnqueuedDefault = 10
double LearningRateFrom = 0.05
Learning rate from number.
double LearningRateTo = 0.8
Learning rate to number.
int NumLearningRate = 4
Number of learning rates in selected region.
double MomentumFrom = 0.1
Momentum from number.
double MomentumTo = 0.6
Momentum to number.
int NumMomentum = 4
Number of momentum in selected region.
double AlphaFrom = 1.2
Alpha value from number.
double AlphaTo = 1.8
Alpha value to number.
int NumAlpha = 4
Number of alpha values in selected region.
int MaxEpochs = 1000
Max number of epochs.
int EpochBundle = 100
Number of epochs in bundle.
double ToleranceRMS = 0.01
Maximum tolerance for RMS.
int NumHiddenLayers = 1
Number of hidden layer in ANN.
int[] NumHiddenNeurons = new int[] { 10 }
Number of nwueons in each hidden layer.
double InputBoundSafetyFactor = 1.3
Safety factor for input bound.
double OutputBoundSafetyFactor = 1.3
Safety factor for output bound.
bool allReadFromFile = false
int ANNType = 1
int NumNeuronsHidden1 = 40
int NumNeuronsHidden2 = 0
double LearnignRate = 0.3
double Momentum = 0.6
double AlphaValue = 1.0
double RatioVerificationPoints = 0.05
bool showErrorPercentages = false
bool verificationPointsFromFile = false
bool enableLabels = true
Public Attributes inherited from IG.Script.LoadableScriptShellNeuralITOriginalBase
string ParallelResultsFilename = "ParallelResults"
int ParSimNumRuns = 2
Number of runs of simulator in each parallel thread.
int ParSimNumThreads = 2
Number of jobs that can be executed in parallel.
int ParSimSavingFrequency = 4
Specifies how often the results are saved.
string ParSimResultFilename = "GatheredNeuralTrainingData.json"
bool saveGraphs = false
Public Attributes inherited from IG.Script.LoadableScriptShellNeuralBase
string ParallelResultsFilename = "ParallelResults"
int ParSimNumRuns = 2
Number of runs of simulator in each parallel thread.
int ParSimNumThreads = 2
Number of jobs that can be executed in parallel.
int ParSimSavingFrequency = 4
Specifies how often the results are saved.
string ParSimResultFilename = "GatheredNeuralTrainingData.json"
bool saveGraphs = false
Static Public Attributes
const string ConstTrainNetwork = "TrainNetwork"
Comamnd name for training the network.
const string ConstHelpTrainNetwork = "Trains NN on basis of standard data. Args: <numLayers> <numNeurons>"
const string ConstTestPlotNetworkResponse = "TestPlotNetworkResponse"
Comamnd name for testing network response (plots, etc.).
const string ConstHelpTestPlotNetworkResponse = "Plots network response. "
const string ConstTestNetworkResponse = "TestNetwork"
Comamnd name for testing network response (plots, etc.).
const string ConstHelpTestNetworkResponse = "Shows some basic plots of network response. "
const string ConstPlotNetworkResponseOnLine = "PlotNetworkResponseOnLine"
Comamnd name for testing network response for verification points on line for specifi Input/output.
const string ConstHelpNetworkResponseOnLine = "Plots network response for points on line from p1 to p2. "
const string ConstPlotEuclideanDistance = "plotteuclideandistance"
Comamnd name for testing network response for verification points on line for specifi Input/output.
const string ConstHelpPlotEuclideanDistance = "Plots euclidean distances for all points. "
const string ConstPlotEuclideanDistanceVRF = "plotteuclideandistancevrf"
Comamnd name for testing network response for verification points on line for specifi Input/output.
const string ConstHelpPlotEuclideanDistanceVRF = "Plots euclidean distances from verification points to training points. "
const string ConstPlotInputOutputRelation = "plotinputoutputrelation"
Comamnd name for testing network response for verification points on line for specifi Input/output.
const string ConstHelpPlotInputOutputRelation = "Plots input and output training points. "
const string ConstSolveOpt = "SolveOpt"
Comamnd name for running solution procedure for opt. problem.
const string ConstHelpSolveOpt = "Solves the optimization problem. "
const string ConstTestHtmlGenerator = "TestHtmlGenerator"
Comamnd name for running solution procedure for opt. problem.
const string ConstHelpTestHtmlGenerator = "Tests html Generation."
const string ConstCustomTests = "customtests"
Comamnd name for custom tests.
const string ConstHelpCustomTests = "Custom tests. Args: "
Static Public Attributes inherited from IG.Script.LoadableScriptShellNeuralIT
const string ConstTrainNetwork = "TrainNetwork"
Comamnd name for training the network.
const string ConstHelpTrainNetwork = "Trains NN on basis of standard data. Args: <numLayers> <numNeurons>"
const string ConstTrainParallelExample = "TrainParallel"
Command name for parallel training of neural network.
const string ConstHelpTrainParallelExample = "Performs multiple trainings of neural networks at different parameters in parallel."
const string ConstPlotConvergence = "plotconvergence"
Comamnd name for plotting convergence errors.
const string ConstHelpPlotConvergence = "Plots convergence errors of parallel trainings. Args: "
const string ConstPlotTrainingTime = "plottrainingtime"
Comamnd name for plotting training time.
const string ConstHelpPlotTrainingTime = "Plots training times of parallel trainings. Args: "
const string ConstPlotVerificationResponse = "PlotVerificationResponse"
Comamnd name for testing network response for verification points(plots, etc.).
const string ConstHelpVerificationResponse = "Plots verification response. "
const string ConstPlotTrainingResponse = "PlotTrainingResponse"
Comamnd name for testing network response for verification points(plots, etc.).
const string ConstHelpTrainingResponse = "Plots training response. "
const string ConstPlotVerificationAndTrainingPoints = "plotverificationandtrainingpoints"
Comamnd name for testing network response for verification points on line for all Inputs/outputs.
const string ConstHelpPlotVerificationAndTrainingPoints = "Plots network response for verification and training points. "
const string ConstPlotNetworkResponseOnLineAll = "PlotNetworkResponseOnLineAll"
Comamnd name for testing network response for verification points on line for all Inputs/outputs.
const string ConstHelpNetworkResponseOnLineAll = "Plots network response for points on line from p1 to p2. "
const string ConstPlotNetworkCenteredPoint = "PlotNetworkResponseCenteredPoint"
Comamnd name for testing network response for centered point from verification or training points for all Inputs/outputs.
const string ConstHelpPlotNetworkCenteredPoint = "Plots network response for centered point from verification or training set. "
const string ConstSensitivity = "Sensitivity"
Comamnd name for testing network response for centered point from verification or training points for all Inputs/outputs.
const string ConstHelpSensitivity = "Executes sensitivity test. "
Static Public Attributes inherited from IG.Script.LoadableScriptShellNeuralITOriginalBase
const string ConstTest = "Test"
Comamnd name for test.
const string ConstHelpTest = "Test of functionality."
const string ConstCustom = "Custom"
Comamnd name for test.
const string ConstHelpCustom = "Custom command that can be quickly modified as needed, for performing."
const string ConstRunParallel = "RunParallel"
Comamnd name for running parallel simulations.
const string ConstHelpRunParallel = "Runs parallel simulations. Args: numThreads numRunsPerThread"
const string ConstCollectParallel = "collectparallel"
Comamnd name for running parallel simulations.
const string ConstHelpCollectParallel = "Collects results of parallel simulations. Args: numThreads"
const string ConstCreateDistortedModelData = "CreateDistortedModelData"
Comamnd name for creating distorted model data.
const string ConstHelpCreateDistortedModelData
const string ConstStochasticCreateInput = "StochasticCreateInput"
Command name for creating input data for analysis how stochastic variables influence outputs.
const string ConstHelpStochasticCreateInput
const string ConstStochasticInfluence = "StochasticInfluence"
Command name for calculating influence of stochastic Gaussian distributed input variables on outputs.
const string ConstHelpStochasticInfluence
const string ConstCreateBinarySampledData = "CreateBinarySampledData"
Comamnd name for saving model's sampled data in binary form.
const string ConstHelpCreateBinarySampledData
const string ConstRestoreBinarySampledData = "RestoreBinarySampledData"
Comamnd name for restoring sampled data in binary form and storing it in JSON.
const string ConstHelpRestoreBinarySampledData
static string TrainedNetworkAlternativeLovation = null
If different than null, this static property provides alternative location of the file which neural network approximator is resd from, in terms of path relative to optimization directory.
Static Public Attributes inherited from IG.Script.LoadableScriptShellNeuralBase
const string ConstTest = "Test"
Comamnd name for test.
const string ConstHelpTest = "Test of functionality."
const string ConstCustom = "Custom"
Comamnd name for test.
const string ConstHelpCustom = "Custom command that can be quickly modified as needed, for performing."
const string ConstRunParallel = "RunParallel"
Comamnd name for running parallel simulations.
const string ConstHelpRunParallel = "Runs parallel simulations. Args: numThreads numRunsPerThread"
const string ConstCollectParallel = "collectparallel"
Comamnd name for running parallel simulations.
const string ConstHelpCollectParallel = "Collects results of parallel simulations. Args: numThreads"
const string ConstCreateDistortedModelData = "CreateDistortedModelData"
Comamnd name for testing network response for centered point from verification or training points for all Inputs/outputs.
const string ConstHelpCreateDistortedModelData
static string TrainedNetworkAlternativeLovation = null
If different than null, this static property provides alternative location of the file which neural network approximator is resd from, in terms of path relative to optimization directory.
Static Public Attributes inherited from IG.Lib.LoadableScriptBase
const string ConstDefaultHelp = "Help"
Default command name for help.
const string ConstHelpDefaultUniversal = "?"
Universal name of the help command.
const string ConstDefaultTestScrip = "TestScript"
Default command name for test method.
Protected Member Functions
override void InitializeThis (string[] arguments)
Initializes the current object.
override string RunThis (string[] arguments)
Runs action of the current object.
override string Script_CommandTestScript (string[] arguments)
Override the TestScript runnable method in order to print some additional information.
void PrepareTransfNeuralSimulation ()
Prepares arrays
Protected Member Functions inherited from IG.Script.LoadableScriptShellNeuralIT
override void InitializeThis (string[] arguments)
Inializes the current script object.
override void LoadJson (string path, ref INeuralApproximator network)
Loads the neural network approximator from the specified file.
override void SaveJson (INeuralApproximator approximator, string trainedNetworkFilePath)
Saves the specified trained network to a file.
override INeuralApproximator CreateApproximator (int annType=2)
Creates and returns a new neural network approximator, with the basic properties pre-set to default values, dependent on the type of the requires approximator.
virtual NeuralApproximatorBase CreateParallelApproximator ()
Creates a parallel approximator for parallel training and comparison of training resultw at different parameters.
virtual NeuralTrainingParameters TrainNetwork (NeuralTrainingParameters parameters)
Trains network. Used as execution delegate on job containers.
virtual void TrainSerial ()
Performs training of neural networks with the specified parameters in non-parallel way.
virtual void TrainParallel ()
Performs parallel training of neural networks with the specified parameters.
virtual void TrainParallel (bool isParallel)
Performs parallel training of neural networks with the specified parameters.
Protected Member Functions inherited from IG.Script.LoadableScriptShellNeuralITOriginalBase
override void InitializeThis (string[] arguments)
Inializes the current script object.
virtual void PrintInternalCommandAndArguments (string[] arguments)
Prints internal command being executed and its actual arguments
virtual void GetSimulationInputDefault (ref IVector result)
Gets the vector of default values of simulation parameters and stores it in the specified vector.
virtual void GetSimulationInputMin (ref IVector result)
Gets the vector of lower bounds on simulation parameters and stores it in the specified vector.
virtual void GetSimulationInputMax (ref IVector result)
Gets the vector of upper bounds on simulation parameters and stores it in the specified vector.
virtual void ParSimPrepareDirectories (int numThreads)
Prepares data for the specified number of parallel execution threads.
virtual void ParSimWaitAllCompletion ()
Waits until all parallel jobs complete.
virtual void ParSimAsyncCallback (IAsyncResult ar)
Callback method for asynchronous runs.
virtual string ParSimGetDirectoryExtension (int threadIndex)
Returns directory extension for data directory used in the specified parallel calculation thread.
virtual void GetNeuralInputDefault (ref IVector result)
Gets the vector of default values of neural parameters and stores it in the specified vector.
virtual void GetNeuralInputMin (ref IVector result)
Gets the vector of lower bounds on neural parameters and stores it in the specified vector.
virtual void GetNeuralInputMax (ref IVector result)
Gets the vector of upper bounds on neural parameters and stores it in the specified vector.
virtual void GetRandomNeuralInputFromDataDefinition (IRandomGenerator rand, ref IVector result)
Generates a random vector of neural input parameters whose elements (components) lie within the lower and upper bounds on parameters, and stores it to the specified vector.
Protected Member Functions inherited from IG.Lib.LoadableScriptShellBase
virtual void CreateNewSimulator (string simulatorPath, ref IResponseEvaluatorVectorSimple simulator)
Creates a new simulator that uses the specified simulator directory, and stores it to the specified variable.
Protected Member Functions inherited from IG.Lib.LoadableScriptBase
delegate string CommandMethod (string commandName, string[] args)
Delegate for internal command methods.
ICommandLineApplicationInterpreter Script_CreateInterpreter ()
Creates and returns an interpreter that can be used as script's internal interpreter for running script's commands.
virtual string Script_CommandHelp (string[] arguments)
Prints help.
Protected Attributes
int[] NeuralInputIndices
Indices of neural input parameters in simulation input parameters.
string[] NeuralInputNames
Names of neural input parameters.
Protected Attributes inherited from IG.Script.LoadableScriptShellNeuralIT
int numPointsOnLine = 5
bool maxDistancePoints = true
bool enableTrainingPoint = false
bool enableVerificationPoint = true
Protected Attributes inherited from IG.Script.LoadableScriptShellNeuralITOriginalBase
IVector _simulationInputDefault
IVector _simulationInputMin
IVector _simulationInputMax
IBoundingBox _simulationInputBounds
string _parallelResultsFilename = "ParallelResults"
string _parallelResultsFileExtension = ".json"
List< IAsyncResult > ParallelResults
object ParSimProcessDelayLock = new object()
int ParSimProcessDelayMilliseconds = 500
Minimal delay between two successive launches of simulator processes, in milliseconds. This delay is introduced in order to prevent unusual errors that occur when running two simulator processes at approcimately the same time (although they use completely separate data directory structures).
List< IVector > _sensitivityResultsVerification
List< IVector > _sensitivityResultsTraining
INeuralApproximator _trainedNetwork
SampledDataSet _trainingData
SampledDataSet _verificationData
IVector _neuralInputDefault
IVector _neuralInputMin
IVector _neuralInputMax
IBoundingBox _neuralInputBounds
Protected Attributes inherited from IG.Script.ScriptShellNeuralWithSimulatorManagers
string _simCastingRobertRootDirectory
string _simCastingRobertProjectName
SimCastingRobertFileManager _simCastingRobertFM
string _simConvectionRobertRootDirectory
string _simConvectionRobertProjectName
ConvectionRobertFileManager _simConvectionRobertFM
ConvectionRev1RobertFileManager _simConvectionRev1RobertFM
string _simKosecDirectoryRelativePath = "Code"
string _simKosecDirectory = null
SimKosecFileManagerBase _simKosecFM
Protected Attributes inherited from IG.Script.LoadableScriptShellNeuralBase
IVector _simulationInputDefault
IVector _simulationInputMin
IVector _simulationInputMax
IBoundingBox _simulationInputBounds
string _parallelResultsFilename = "ParallelResults"
string _parallelResultsFileExtension = ".json"
List< IAsyncResult > ParallelResults
object ParSimProcessDelayLock = new object()
int ParSimProcessDelayMilliseconds = 500
Minimal delay between two successive launches of simulator processes, in milliseconds. This delay is introduced in order to prevent unusual errors that occur when running two simulator processes at approcimately the same time (although they use completely separate data directory structures).
List< IVector > _sensitivityResultsVerification
List< IVector > _sensitivityResultsTraining
INeuralApproximator _trainedNetwork
SampledDataSet _trainingData
SampledDataSet _verificationData
IVector _neuralInputDefault
IVector _neuralInputMin
IVector _neuralInputMax
IBoundingBox _neuralInputBounds
Protected Attributes inherited from IG.Lib.LoadableScriptShellBase
IResponseEvaluatorVectorSimple _simulator
string _projectName
string _simulationName
Protected Attributes inherited from IG.Lib.LoadableScriptOptBase
StopWatch1 _timer = null
bool _checkOptimizationDirectoryExistence = true
Whether to check existence of optimization directory when set. Also applies to working directory.
Protected Attributes inherited from IG.Lib.LoadableScriptBase
string _embeddedCommandName = null
int _outputLevel = DefaultOutputLevel
ICommandLineApplicationInterpreter _script_interpreter
Properties
override int NumOptimizationParameters [get, protected set]
Number of optimization parameters.
override int NumOptimizationConstraints [get, protected set]
Number of optimization constraints.
Properties inherited from IG.Script.LoadableScriptShellNeuralIT
virtual List< NeuralTrainingParameters > TrainingParametersAndResults [get]
List of training parameters for which training should be performed.
virtual string TrainingParametersPath [get]
Path to the default location lwhere training parameters and convergence results from multiple training attempts are stored.
virtual string TrainingLimitsPath [get]
Path to the default location lwhere training limits are stored.
virtual string TrainingResultsPath [get]
Path to the default location lwhere training complete results are stored.
virtual string TrainingResultsCSVPath [get]
Path to the default location lwhere training complete results are stored.
virtual string OptimalTrainingParametersPath [get]
Path to the default location where optimal training parameters for the current problem are stored.
virtual string AdditionalTrainingParametersFilename [get, set]
Eventual relative path of an additional file name where results are stored.
int ParallelNumServers [get, set]
Number of parallel servers that will be used for parallel execution of jobs.
int ParallelMaxEnqueued [get, set]
Maximal number of enqueued jobs when performing parallel execution of jobs.
int ParallelSleepTimeMs [get, set]
Sleeping time in milliseconds.
bool ParallelIsServerMode [get, set]
Whether servers will operate in server mode (true) or by running each job in a new thread (false).
int ParallelClientOutputLevel [get, set]
Client's output level when executing parallel jobs.
int ParallelOutputLevel [get, set]
Output level for parallel dispatcher, servers and job containers when executing parallel jobs.
bool ParallelIsTestMode [get, set]
Specifies whether parallel jobs will be executing in testing mode (where e.g. delay times apply).
double ParallelDelayTimeSeconds [get, set]
Delay in seconds used in parallel execution. This is useful only for testing purposes, default is 0.
double ParallelDelayTimeRelativeError [get, set]
Relative variation in delay time used in parallel execution. This is useful only for testing purposes, default is 0.
virtual int ParallelSavingFrequency [get, set]
Frequency of saving the results of parallel execution:
Properties inherited from IG.Script.LoadableScriptShellNeuralITOriginalBase
override int NumOptimizationParameters [get, protected set]
Number of optimization parameters.
override int NumOptimizationConstraints [get, protected set]
Number of optimization constraints.
virtual InputOutputDataDefiniton SimulationDataDefinition [get]
Simulation data definition (input and output used by simulator).
virtual int NumSimulationParameters [get, protected set]
Number of simulation input parameters.
virtual int NumSimulationOutputs [get, protected set]
Number of simulation output values.
virtual IBoundingBox SimulationInputBounds [get, protected set]
Bounds on simulation input parameters.
string ParallelResultsFileExtension [get, protected set]
virtual NeuraApproximationFileManager NeuralFM [get]
File manager that provides access to trained neural network and related data.
virtual INeuralApproximator TrainedNetwork [get, protected set]
Trained neural network.
virtual List< IVector > SensitivityVerificationResults [get, protected set]
virtual List< IVector > SensitivityTrainingResults [get, protected set]
virtual INeuralApproximator XXX_TrainedNetwork [get, protected set]
Trained neural network.
virtual InputOutputDataDefiniton NeuralDataDefinition [get, protected set]
Neural data definition.
virtual SampledDataSet TrainingData [get, set]
virtual SampledDataSet VerificationData [get, set]
virtual int NumNeuralParameters [get, protected set]
Number of neural network input parameters.
virtual int NumNeuralOutputs [get, protected set]
Number of neural network output values.
virtual IBoundingBox NeuralInputBounds [get, protected set]
Bounds on neural input parameters.
virtual SampledDataSet NeuralTrainingData [get]
Gets the training data.
virtual int NumAllTrainingPoints [get]
Gets number of all training points, including verification points.
virtual IVector SomeNeuralInput [get]
Returns some vector of input parameters that is within the range.
virtual IVector NeuralInputFromFile [get]
Vector of input parameters read form the file.
Properties inherited from IG.Script.ScriptShellNeuralWithSimulatorManagers
virtual string SimCastingRobertRootDirectory [get, protected set]
Root directory for casting simulator.
virtual string SimCastingRobertProjectName [get, protected set]
Project name for interfacing Robert Vertnik's casting simulator.
virtual string SimCastingRobertSimulationName [get, protected set]
Simulation name for interfacing Robert Vertnik's casting simulator.
virtual SimCastingRobertFileManager SimCastingRobertFM [get, set]
File manager for interfacing Robert Vertnik's casting simulator. Lazy evaluation: The object is created when first accessed, if possible. For this, ProjectName, SimulationName and SimCastingRobertRootDirectory must be defined.
virtual string SimConvectionRobertRootDirectory [get, protected set]
Root directory for Convection simulator.
virtual string SimConvectionRobertProjectName [get, protected set]
Project name for interfacing Robert Vertnik's Convection simulator.
virtual string SimConvectionRobertSimulationName [get, protected set]
Simulation name for interfacing Robert Vertnik's Convection simulator.
virtual ConvectionRobertFileManager SimConvectionRobertFM [get, set]
File manager for interfacing Robert Vertnik's casting simulator. Lazy evaluation: The object is created when first accessed, if possible. For this, ProjectName, SimulationName and SimCastingRobertRootDirectory must be defined.
virtual ConvectionRev1RobertFileManager SimConvectionRev1RobertFM [get, set]
File manager for interfacing Robert Vertnik's casting simulator. Lazy evaluation: The object is created when first accessed, if possible. For this, ProjectName, SimulationName and SimCastingRobertRootDirectory must be defined.
virtual string SimKosecDirectoryRelativePath [get, set]
Relative path of the directory that contains Kosec' simulation data, with respect to optimization directory.
string SimKosecDirectory [get, set]
Path so directory containing Kosec' simulator data.
virtual SimKosecFileManagerBase SimKosecFM [get, protected set]
File manager of simulatior of Gregor Kosec.
Properties inherited from IG.Script.LoadableScriptShellNeural
override IResponseEvaluatorVectorSimple Simulator [get, protected set]
override int NumOptimizationParameters [get, protected set]
Throws NotImplementedException.
override int NumOptimizationConstraints [get, protected set]
Throws NotImplementedException.
Properties inherited from IG.Script.LoadableScriptShellNeuralBase
abstract int NumOptimizationParameters [get, protected set]
Number of optimization parameters.
abstract int NumOptimizationConstraints [get, protected set]
Number of optimization constraints.
virtual InputOutputDataDefiniton SimulationDataDefinition [get]
Simulation data definition (input and output used by simulator).
virtual int NumSimulationParameters [get, protected set]
Number of simulation input parameters.
virtual int NumSimulationOutputs [get, protected set]
Number of simulation output values.
virtual IBoundingBox SimulationInputBounds [get, protected set]
Bounds on simulation input parameters.
string ParallelResultsFileExtension [get, protected set]
virtual NeuraApproximationFileManager NeuralFM [get]
File manager that provides access to trained neural network and related data.
virtual INeuralApproximator TrainedNetwork [get, protected set]
Trained neural network.
virtual List< IVector > SensitivityVerificationResults [get, protected set]
virtual List< IVector > SensitivityTrainingResults [get, protected set]
virtual INeuralApproximator XXX_TrainedNetwork [get, protected set]
Trained neural network.
virtual InputOutputDataDefiniton NeuralDataDefinition [get, protected set]
Neural data definition.
virtual SampledDataSet TrainingData [get, set]
virtual SampledDataSet VerificationData [get, set]
virtual int NumNeuralParameters [get, protected set]
Number of neural network input parameters.
virtual int NumNeuralOutputs [get, protected set]
Number of neural network output values.
virtual IBoundingBox NeuralInputBounds [get, protected set]
Bounds on neural input parameters.
virtual SampledDataSet NeuralTrainingData [get]
Gets the training data.
virtual int NumAllTrainingPoints [get]
Gets number of all training points, including verification points.
virtual IVector SomeNeuralInput [get]
Returns some vector of input parameters that is within the range.
virtual IVector NeuralInputFromFile [get]
Vector of input parameters read form the file.
Properties inherited from IG.Lib.LoadableScriptShellBase
abstract IResponseEvaluatorVectorSimple Simulator [get, protected set]
Simulator that is used to calculate vector response.
virtual bool SimulatorSuppressOutput [get, set]
A flag indicating whether simulators should suppress output or not, default is false.
virtual string ProjectName [get, set, protected set]
Name of the current project, used in some simulation and other interfaces.
virtual string SimulationName [get, set, protected set]
Name of the current simulation, used in some simulation and other interfaces.
string CastingRobertProjectName [get, set]
Project name for interfacing Robert Vertnik's casting simulator.
string CastingRobertSimulationName [get, set]
Simulation name for interfacing Robert Vertnik's casting simulator.
string CastingRobertRootDirectory [get, set]
Root directory for casting simulator.
SimCastingRobertFileManager CastingRobertFileManager [get, set]
File manager for interfacing Robert Vertnik's casting simulator. Lazy evaluation: The object is created when first accessed, if possible. For this, ProjectName, SimulationName and CastingRobertRootDirectory must be defined.
Properties inherited from IG.Lib.LoadableScriptOptShellBaseControllable
bool IsLoadable [get, set]
Either or not the script can be dynamically loaded.
bool IsRunnable [get, set]
Either or not the script can be run (some scripts only support other tasks).
Properties inherited from IG.Lib.LoadableScriptOptBase
StopWatch1 Timer [get]
virtual IRandomGenerator Random [get, protected set]
Random generator used by the current object.
virtual string OptimizationDirectory [get, set]
Optimization directory. This directory is a base directory for data used optimization and neural network - based approximation servers and for other directories that contain data for specific tasks.
virtual string WorkingDirectory [get, set]
Working directory. This directory is a base directory for data used by the script. It is usually obtained as parent directory of the optimization directory.
virtual IAnalysis Analysis [get, protected set]
Direct analysis object used in optimization. Initialized when first accessed with the embedded class, whose analysis function calls Analyse(...).
Properties inherited from IG.Lib.LoadableScriptBase
string EmbeddedCommandName [get, set]
Command that was used to launch the current embedded application script.
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
string[] InitializationArguments [get, set]
Arguments used by the initialization method. WARNING: arguments can only be set before initialization is performed. Initialization is performed either implicitly at the first call to the Run method or explicitly by calling the Initialize method.
virtual bool IsInitialized [get, protected set]
Whether the object has been initialized or not.
static int DefaultOutputLevel [get, set]
int OutputLevel [get, set]
Level of output to console produced by some operations of the current object.
virtual ICommandLineApplicationInterpreter Script_Interpreter [get, protected set]
Script's internal interpreter that takes care for execution of installed internal commands.
SortedList< string, string > Script_CommandHelpStrings [get]
Contains help strings associated with script commands installed on interpreter.
Properties inherited from IG.Lib.ILoadableScript
string EmbeddedCommandName [get, set]
Command that was used to launch the current embedded application script.
string[] InitializationArguments [get, set]
Arguments used by the initialization method.
bool IsInitialized [get]
Whether the object has been initialized or not.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Properties inherited from IG.Lib.ILoadableScriptC
bool IsLoadable [get, set]
Either or not the script can be dynamically loaded.
bool IsRunnable [get, set]
Either or not the script can be run (some scripts only support other tasks).
Properties inherited from IG.Num.INeuralModel
INeuralApproximator TrainedNetwork [get]
Traint artificial neural network.
InputOutputDataDefiniton NeuralDataDefinition [get]
Neural data definition.
Private Attributes
int _numOptimizationConstraints = 0
HtmlWriter html = null
int numPointsOnLine = 5
bool maxDistancePoints = true
bool enableTrainingPoint = true
bool enableVerificationPoint = true
Additional Inherited Members
Static Protected Attributes inherited from IG.Script.LoadableScriptShellNeuralITOriginalBase
const string _binaryTrainingDataExtension = ".bin"
const string _restoredTrainingDataExtension = ".jsonrestored"
Constructor & Destructor Documentation
S_12_01_Paper_NeuralOptCasting_00()
IG.Script.S_12_01_Paper_NeuralOptCasting_00.S_12_01_Paper_NeuralOptCasting_00 () inline
Member Function Documentation
InitializeThis()
override void IG.Script.S_12_01_Paper_NeuralOptCasting_00.InitializeThis (string[] arguments) inline protected virtual
Initializes the current object.
Reimplemented from IG.Script.LoadableScriptShellNeural.
References IG.Script.ScriptShellNeuralWithSimulatorManagers.InitSimCastingRobert(), IG.Lib.LoadableScriptOptBase.OptimizationDirectory, IG.Num.SimCastingRobertFileManager.OutputLevel, IG.Lib.LoadableScriptBase.Script_PrintArguments(), IG.Script.ScriptShellNeuralWithSimulatorManagers.SimCastingRobertFM, IG.Num.SimCastingRobertFileManager.ToString(), and IG.Lib.LoadableScriptOptBase.WorkingDirectory.
RunThis()
override string IG.Script.S_12_01_Paper_NeuralOptCasting_00.RunThis (string[] arguments) inline protected virtual
Runs action of the current object.
Parameters
arguments Command-line arguments of the action.
Reimplemented from IG.Script.LoadableScriptShellNeural.
References IG.Lib.LoadableScriptBase.Script_CommandHelp(), IG.Lib.LoadableScriptBase.Script_ContainsCommand(), IG.Lib.LoadableScriptBase.Script_PrintArguments(), and IG.Lib.LoadableScriptBase.Script_Run().
TrainNetwork()
virtual string IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainNetwork (string[] arguments) inline virtual
Trains neural network on the results of simulations.
Parameters
arguments Command arguments, first one (index 0) is always command name.
Returns
null.
Reimplemented from IG.Script.LoadableScriptShellNeuralIT.
References IG.Script.S_12_01_Paper_NeuralOptCasting_00.AlphaValue, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ANNType, IG.Script.S_12_01_Paper_NeuralOptCasting_00.EpochsInBundle, IG.Script.S_12_01_Paper_NeuralOptCasting_00.InputSafetyFactor, IG.Script.S_12_01_Paper_NeuralOptCasting_00.LearnignRate, IG.Script.S_12_01_Paper_NeuralOptCasting_00.MaxEpochs, IG.Script.S_12_01_Paper_NeuralOptCasting_00.Momentum, IG.Script.S_12_01_Paper_NeuralOptCasting_00.NumNeuronsHidden1, IG.Script.S_12_01_Paper_NeuralOptCasting_00.NumNeuronsHidden2, IG.Script.S_12_01_Paper_NeuralOptCasting_00.OutputSafetyFactor, IG.Script.S_12_01_Paper_NeuralOptCasting_00.PercentVerificationPoints, IG.Script.S_12_01_Paper_NeuralOptCasting_00.saveGraphs, IG.Lib.LoadableScriptBase.Script_PrintArguments(), and IG.Script.LoadableScriptShellNeuralIT.TrainANN().
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
TestPlotNetworkResponse()
virtual string IG.Script.S_12_01_Paper_NeuralOptCasting_00.TestPlotNetworkResponse (string[] arguments) inline virtual
Shows some plots of neural network response.
Parameters
arguments Arguments of the method. Method accepts numbe of calculated points in plots.
Returns
null.
References IG.Script.LoadableScriptShellNeuralIT.PlotNetworkResponse(), and IG.Script.LoadableScriptShellNeuralIT.PlotNetworkResponseGrouped().
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
TestNetworkResponse()
virtual string IG.Script.S_12_01_Paper_NeuralOptCasting_00.TestNetworkResponse (string[] arguments) inline virtual
Tests the approximated response of the neural network.
Parameters
arguments Command arguments, first one (index 0) is always command name.
Returns
n ull.
References IG.Script.LoadableScriptShellNeuralIT.PlotNetworkResponse(), and IG.Script.LoadableScriptShellNeuralITOriginalBase.TrainedNetwork.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
PlotVerificationAndTrainingPoints()
string IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotVerificationAndTrainingPoints (string[] arguments) inline
Plot training and verification points on the same graph.
Parameters
arguments ommand arguments, first one (index 0) is always command name.
Returns
null.
References IG.Script.S_12_01_Paper_NeuralOptCasting_00.numTrainingLinesOnGraph, IG.Script.S_12_01_Paper_NeuralOptCasting_00.numVerificationLinesOnGraph, IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotTrainingAndVerificationPointsResponse(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.saveGraphs, and IG.Script.S_12_01_Paper_NeuralOptCasting_00.verificationPointsFromFile.
SolveOpt()
virtual string IG.Script.S_12_01_Paper_NeuralOptCasting_00.SolveOpt (string[] arguments) inline virtual
Solves the final problem.
Parameters
arguments Command arguments, first one (index 0) is always command name.
Returns
null.
References IG.Num.SampledDataSet.LoadJson(), IG.Script.LoadableScriptShellNeuralITOriginalBase.NeuralFM, IG.Neural.NeuraApproximationFileManager.NeuralNetworkPath, IG.Neural.NeuraApproximationFileManager.NeuralTrainingDataPath, and IG.Neural.NeuralApproximatorBaseExt.SaveJson().
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
TestHtmlGenerator() [1/2]
virtual string IG.Script.S_12_01_Paper_NeuralOptCasting_00.TestHtmlGenerator (string[] arguments) inline virtual
Used for testing of HTML generator.
Parameters
arguments Arguments. Meaning is as follows:
0: Path to testing directory. If not specified then directory is "html" within the working directory.
Returns
null.
References IG.Lib.LoadableScriptOptBase.WorkingDirectory.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
PlotEuclideanDistance() [1/3]
string IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistance (string[] arguments) inline
Plot the smallest Euclidean distances for all training points.
Parameters
arguments Arguments. Meaning is as follows:
Returns
null
References IG.Script.S_12_01_Paper_NeuralOptCasting_00.enableLabels, IG.Script.S_12_01_Paper_NeuralOptCasting_00.nearestDistanceFrom, and IG.Script.S_12_01_Paper_NeuralOptCasting_00.saveGraphs.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistance(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
PlotEuclideanDistanceVRF() [1/3]
string IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistanceVRF (string[] arguments) inline
References IG.Script.S_12_01_Paper_NeuralOptCasting_00.nearestDistanceFrom, and IG.Script.S_12_01_Paper_NeuralOptCasting_00.saveGraphs.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistanceVRF(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
PlotInputOutputRelation()
string IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotInputOutputRelation (string[] arguments) inline
Plots output and input training points.
Parameters
arguments Arguments. Meaning is as follows:
Returns
null
References IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotInOutRelation(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.saveGraphs.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
CustomTests()
virtual string IG.Script.S_12_01_Paper_NeuralOptCasting_00.CustomTests (string[] arguments) inline virtual
References IG.Script.S_12_01_Paper_NeuralOptCasting_00.CusomTrainingSetExtract(), and IG.Lib.LoadableScriptBase.Script_PrintArguments().
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
Script_AddCommands()
override void IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands (ICommandLineApplicationInterpreter interpreter, SortedList< string, string > helpStrings) inline virtual
Adds commands to the internal interpreter.
Parameters
interpreter Interpreter where commands are executed.
helpStrings List containg help strings.
Reimplemented from IG.Script.LoadableScriptShellNeuralBase.
References IG.Script.LoadableScriptShellNeuralITOriginalBase.CollectParallelSimulationResults(), IG.Script.LoadableScriptShellNeuralITOriginalBase.ConstCollectParallel, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstCustomTests, IG.Script.LoadableScriptShellNeuralITOriginalBase.ConstHelpCollectParallel, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstHelpCustomTests, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstHelpPlotEuclideanDistance, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstHelpPlotEuclideanDistanceVRF, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstHelpPlotInputOutputRelation, IG.Script.LoadableScriptShellNeuralITOriginalBase.ConstHelpRunParallel, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstHelpSolveOpt, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstHelpTestHtmlGenerator, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstHelpTestNetworkResponse, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstHelpTestPlotNetworkResponse, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstHelpTrainNetwork, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstPlotEuclideanDistance, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstPlotEuclideanDistanceVRF, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstPlotInputOutputRelation, IG.Script.LoadableScriptShellNeuralITOriginalBase.ConstRunParallel, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstSolveOpt, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstTestHtmlGenerator, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstTestNetworkResponse, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstTestPlotNetworkResponse, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstTrainNetwork, IG.Script.S_12_01_Paper_NeuralOptCasting_00.CustomTests(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistance(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistanceVRF(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotInputOutputRelation(), IG.Script.LoadableScriptShellNeuralITOriginalBase.RunParallelSimulations(), IG.Lib.LoadableScriptBase.Script_AddCommand(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.SolveOpt(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.TestHtmlGenerator(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.TestNetworkResponse(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.TestPlotNetworkResponse(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainNetwork().
Script_CommandTestScript()
override string IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_CommandTestScript (string[] arguments) inline protected virtual
Override the TestScript runnable method in order to print some additional information.
Parameters
arguments Script arguments.
Returns
null.
Reimplemented from IG.Lib.LoadableScriptBase.
TestHtmlGenerator() [2/2]
virtual void IG.Script.S_12_01_Paper_NeuralOptCasting_00.TestHtmlGenerator (string directoryPath, string cssPath) inline virtual
Tests the HTML generator. Creates a file named "test.html" in the specified directory.
Parameters
directoryPath Path to the directory containing test files.
References IG.Lib.HtmlWriter.AddHeading1(), IG.Lib.HtmlWriter.AddHeading2(), IG.Lib.HtmlWriter.AddImage(), IG.Lib.HtmlWriter.AddKeywords(), IG.Lib.HtmlWriter.AddNewLine(), IG.Lib.HtmlWriter.AddParagraph(), IG.Lib.HtmlWriter.AddPlainTextLine(), IG.Lib.HtmlWriter.BeginSection(), IG.Lib.HtmlWriter.CloseWriter(), IG.Lib.HtmlWriter.ConstAttributeClass, IG.Lib.HtmlWriter.ConstAttributeId, IG.Lib.HtmlWriter.DocumentStyle, IG.Lib.HtmlWriter.DocumentTitle, IG.Lib.HtmlWriter.EndDocument(), IG.Lib.HtmlWriter.EndSection(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.html, and IG.Lib.UtilSystem.OpenFileInDefaultBrowser().
PlotRMSErrors() [1/2]
void IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotRMSErrors (List< IVector > errorsRMSList) inline
Plots RMS errors on training points during training.
Parameters
errorsRMSList List of RMS errors for all outputs.
References IG.Lib.HtmlWriter.AddHeading1(), IG.Lib.HtmlWriter.AddHeading2(), IG.Lib.HtmlWriter.AddImage(), IG.Lib.HtmlWriter.CloseWriter(), IG.Num.InputOutputElementDefinition.Description, IG.Lib.HtmlWriter.EndDocument(), IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.html, IG.Num.InputOutputElementDefinition.Name, IG.Script.LoadableScriptShellNeuralITOriginalBase.NeuralDataDefinition, IG.Script.LoadableScriptShellNeuralITOriginalBase.NumNeuralOutputs, IG.Lib.UtilSystem.OpenFileInDefaultBrowser(), IG.Lib.LoadableScriptOptBase.OptimizationDirectory, and IG.Script.S_12_01_Paper_NeuralOptCasting_00.saveGraphs.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainANN().
PlotRMSErrors() [2/2]
void IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotRMSErrors (List< IVector > errorsRMSList, int whichOut) inline
Plots RMS errors on training points during training.
Parameters
errorsRMSList List of RMS errors for all outputs.
whichOut Which output RMS to plot.
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Script.LoadableScriptShellNeuralIT.ApplyPlotSettingsCurve(), IG.Gr.PlotterZedGraph.CreateDefault(), IG.Num.InputOutputElementDefinition.Description, IG.Num.INeuralApproximator.EpochsInBundle, IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Gr.ZedGraphWindow.GraphControl, IG.Gr.PlotterZedGraph.GraphPane, IG.Gr.PlotZedGraphBase.LegendString, IG.Num.INeuralApproximator.MaxEpochs, IG.Num.InputOutputElementDefinition.Name, IG.Script.LoadableScriptShellNeuralITOriginalBase.NeuralDataDefinition, IG.Script.LoadableScriptShellNeuralITOriginalBase.NumNeuralOutputs, IG.Lib.LoadableScriptOptBase.OptimizationDirectory, IG.Gr.PlotZedgraphCurve.PointSize, IG.Script.S_12_01_Paper_NeuralOptCasting_00.saveGraphs, IG.Gr.PlotterZedGraph.Title, IG.Script.LoadableScriptShellNeuralITOriginalBase.TrainedNetwork, IG.Gr.PlotterZedGraph.Update(), IG.Gr.PlotterZedGraph.XAxis, IG.Gr.PlotterZedGraph.XAxisLabel, IG.Gr.PlotterZedGraph.YAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabelFont.
PlotInOutRelation() [1/2]
void IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotInOutRelation () inline
Plots input and output relation on training points.
References IG.Lib.HtmlWriter.AddHeading1(), IG.Lib.HtmlWriter.AddHeading2(), IG.Lib.HtmlWriter.AddImage(), IG.Lib.HtmlWriter.AddNewLine(), IG.Lib.HtmlWriter.AddParagraph(), IG.Lib.HtmlWriter.CloseWriter(), IG.Num.InputOutputElementDefinition.Description, IG.Lib.HtmlWriter.EndDocument(), IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.html, IG.Num.InputOutputElementDefinition.Name, IG.Script.LoadableScriptShellNeuralITOriginalBase.NeuralDataDefinition, IG.Script.LoadableScriptShellNeuralITOriginalBase.NumNeuralOutputs, IG.Script.LoadableScriptShellNeuralITOriginalBase.NumNeuralParameters, IG.Lib.UtilSystem.OpenFileInDefaultBrowser(), IG.Lib.LoadableScriptOptBase.OptimizationDirectory, and IG.Script.S_12_01_Paper_NeuralOptCasting_00.saveGraphs.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotInputOutputRelation().
PlotInOutRelation() [2/2]
void IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotInOutRelation (int whichOut, int whichParam) inline
Plots input and output relation on training points.
Parameters
whichOut Which oitput to plot.
whichParam Which input parameter to increase in the test.
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Gr.PlotterZedGraph.CreateDefault(), IG.Num.InputOutputElementDefinition.Description, IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.SampledDataSet.GetInputParameters(), IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Num.SampledDataSet.GetOutputValues(), IG.Gr.ZedGraphWindow.GraphControl, IG.Gr.PlotterZedGraph.GraphPane, IG.Num.SampledDataSet.InputLength, IG.Gr.PlotZedgraphCurve.Is2Axis, IG.Gr.PlotZedGraphBase.LegendString, IG.Num.SampledDataSet.Length, IG.Gr.PlotZedgraphCurve.LineColor, IG.Gr.PlotZedgraphCurve.LinesVisible, IG.Num.InputOutputElementDefinition.Name, IG.Script.LoadableScriptShellNeuralITOriginalBase.NeuralDataDefinition, IG.Script.LoadableScriptShellNeuralITOriginalBase.NeuralTrainingData, IG.Lib.LoadableScriptOptBase.OptimizationDirectory, IG.Num.SampledDataSet.OutputLength, IG.Gr.PlotZedgraphCurve.PointColor, IG.Gr.PlotZedgraphCurve.PointSize, IG.Script.S_12_01_Paper_NeuralOptCasting_00.saveGraphs, IG.Gr.PlotterZedGraph.Title, IG.Gr.PlotterZedGraph.Update(), IG.Gr.PlotterZedGraph.X2Axis, IG.Gr.PlotterZedGraph.XAxis, IG.Gr.PlotterZedGraph.XAxisLabel, IG.Gr.PlotterZedGraph.Y2Axis, IG.Gr.PlotterZedGraph.Y2AxisIsVisible, IG.Gr.PlotterZedGraph.Y2AxisLabel, IG.Gr.PlotterZedGraph.Y2AxisLabelFont, IG.Gr.PlotterZedGraph.YAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabelFont.
PlotTrainingAndVerificationPointsResponse()
void IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotTrainingAndVerificationPointsResponse (int numVerificationPoints, int numTrainingPoints) inline
Plots the ANN approximation on the verification and training points
Parameters
numTrainingPoints Number of training points to be written on graph.
numVerificationPoints Number of verification points to be written on graph.
References IG.Lib.HtmlWriter.AddHeading1(), IG.Lib.HtmlWriter.AddHeading2(), IG.Lib.HtmlWriter.AddImage(), IG.Lib.HtmlWriter.AddNewLine(), IG.Lib.HtmlWriter.AddParagraph(), IG.Lib.HtmlWriter.CloseWriter(), IG.Lib.SortedUniqueItemList< Type >.Contains(), IG.Num.InputOutputElementDefinition.Description, IG.Lib.HtmlWriter.EndDocument(), IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.SampledDataSet.GetInputParameters(), IG.Script.LoadableScriptShellNeuralITOriginalBase.GetNeuralInputMax(), IG.Script.LoadableScriptShellNeuralITOriginalBase.GetNeuralInputMin(), IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.html, IG.Num.SampledDataSet.InputLength, IG.Num.SampledDataSet.Length, IG.Num.InputOutputElementDefinition.Name, IG.Script.LoadableScriptShellNeuralITOriginalBase.NeuralDataDefinition, IG.Script.LoadableScriptShellNeuralITOriginalBase.NumNeuralOutputs, IG.Script.LoadableScriptShellNeuralITOriginalBase.NumNeuralParameters, IG.Num.INeuralApproximator.NumTrainingPoints, IG.Num.INeuralApproximator.NumVerificationPoints, IG.Lib.UtilSystem.OpenFileInDefaultBrowser(), IG.Lib.LoadableScriptOptBase.OptimizationDirectory, IG.Lib.LoadableScriptOptBase.Random, IG.Script.S_12_01_Paper_NeuralOptCasting_00.saveGraphs, IG.Script.LoadableScriptShellNeuralITOriginalBase.TrainedNetwork, IG.Num.INeuralApproximator.TrainingData, IG.Script.LoadableScriptShellNeuralITOriginalBase.VerificationData, IG.Num.INeuralApproximator.VerificationIndices, and IG.Script.S_12_01_Paper_NeuralOptCasting_00.verificationPointsFromFile.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotVerificationAndTrainingPoints().
PlotTrainingPointResponse()
void IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotTrainingPointResponse (IVector selectedTrainingPoint, int whichOutput, int whichParameter, double min, double max) inline
Plots the ANN approximation on the training point.
Parameters
selectedTrainingPoints Training points ID.
whichOutput Which output to plot.
whichParameter Which parameter to plot.
min Minimum range.
max Maximum range.
$A Tako78 Nov12;
References IG.Script.LoadableScriptShellNeuralIT.PlotTrainingAndVerificationPointResponse().
PlotEuclideanDistance() [2/3]
void IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistance (int nearestDistanceFromPoint) inline
Plot N-th Euclidean distances for all training points.
Parameters
nearestDistanceFromPoint Distance to N-th neareast point.
References IG.Lib.HtmlWriter.AddHeading1(), IG.Lib.HtmlWriter.AddImage(), IG.Lib.HtmlWriter.AddNewLine(), IG.Lib.HtmlWriter.AddParagraph(), IG.Lib.HtmlWriter.CloseWriter(), IG.Num.InputOutputElementDefinition.Description, IG.Lib.HtmlWriter.EndDocument(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.EuclideanDistance(), IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.html, IG.Num.InputOutputElementDefinition.Name, IG.Script.LoadableScriptShellNeuralITOriginalBase.NeuralDataDefinition, IG.Script.LoadableScriptShellNeuralITOriginalBase.NumNeuralOutputs, IG.Lib.UtilSystem.OpenFileInDefaultBrowser(), IG.Lib.LoadableScriptOptBase.OptimizationDirectory, IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistance(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.saveGraphs.
PlotEuclideanDistance() [3/3]
void IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistance (int whichOut, List< IVector > smallestDistances, List< IVector > averageDistances) inline
Plot N-th Euclidean distances for all training points.
Parameters
whichOut Which output to plot.
smallestDistances Which parameter to plot.
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Script.LoadableScriptShellNeuralIT.CalculateVerificationError(), IG.Gr.PlotterZedGraph.CreateDefault(), IG.Num.InputOutputElementDefinition.Description, IG.Script.S_12_01_Paper_NeuralOptCasting_00.enableLabels, IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Gr.ZedGraphWindow.GraphControl, IG.Gr.PlotterZedGraph.GraphPane, IG.Gr.PlotZedgraphCurve.IsY2Axis, IG.Gr.PlotZedGraphBase.LegendString, IG.Num.SampledDataSet.Length, IG.Gr.PlotZedgraphCurve.LinesVisible, IG.Num.InputOutputElementDefinition.Name, IG.Script.LoadableScriptShellNeuralITOriginalBase.NeuralDataDefinition, IG.Num.INeuralApproximator.NumVerificationPoints, IG.Lib.LoadableScriptOptBase.OptimizationDirectory, IG.Gr.PlotZedgraphCurve.PointColor, IG.Gr.PlotZedgraphCurve.PointSize, IG.Script.S_12_01_Paper_NeuralOptCasting_00.saveGraphs, IG.Num.InputOutputElementDefinition.Title, IG.Gr.PlotterZedGraph.Title, IG.Script.LoadableScriptShellNeuralITOriginalBase.TrainedNetwork, IG.Num.INeuralApproximator.TrainingData, IG.Gr.PlotterZedGraph.Update(), IG.Gr.PlotterZedGraph.XAxis, IG.Gr.PlotterZedGraph.XAxisLabel, IG.Gr.PlotterZedGraph.Y2AxisLabel, IG.Gr.PlotterZedGraph.Y2AxisLabelFont, IG.Gr.PlotterZedGraph.YAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabelFont.
PlotEuclideanDistanceVRF() [2/3]
void IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistanceVRF (int nearestDistanceFromPoint) inline
Plot N-th Euclidean distances for all verification points.
Parameters
nearestDistanceFromPoint Distance to N-th neareast point.
References IG.Lib.HtmlWriter.AddHeading1(), IG.Lib.HtmlWriter.AddImage(), IG.Lib.HtmlWriter.AddNewLine(), IG.Lib.HtmlWriter.AddParagraph(), IG.Lib.HtmlWriter.CloseWriter(), IG.Num.InputOutputElementDefinition.Description, IG.Lib.HtmlWriter.EndDocument(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.EuclideanDistanceVRF(), IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.html, IG.Num.InputOutputElementDefinition.Name, IG.Script.LoadableScriptShellNeuralITOriginalBase.NeuralDataDefinition, IG.Script.LoadableScriptShellNeuralITOriginalBase.NumNeuralOutputs, IG.Lib.UtilSystem.OpenFileInDefaultBrowser(), IG.Lib.LoadableScriptOptBase.OptimizationDirectory, IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistanceVRF(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.saveGraphs.
PlotEuclideanDistanceVRF() [3/3]
void IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistanceVRF (int whichOut, List< IVector > averageDistancesVRF) inline
Plot N-th Euclidean distances for all verification points.
Parameters
whichOut Which output to plot.
averageDistancesVRF Which parameter to plot.
References IG.Gr.PlotZedgraphCurve.AddPoint(), IG.Script.LoadableScriptShellNeuralIT.CalculateVerificationError(), IG.Gr.PlotterZedGraph.CreateDefault(), IG.Num.InputOutputElementDefinition.Description, IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Gr.ZedGraphWindow.GraphControl, IG.Gr.PlotterZedGraph.GraphPane, IG.Gr.PlotZedgraphCurve.LineColor, IG.Num.InputOutputElementDefinition.Name, IG.Script.LoadableScriptShellNeuralITOriginalBase.NeuralDataDefinition, IG.Lib.LoadableScriptOptBase.OptimizationDirectory, IG.Gr.PlotZedgraphCurve.PointColor, IG.Gr.PlotZedgraphCurve.PointSize, IG.Script.S_12_01_Paper_NeuralOptCasting_00.saveGraphs, IG.Num.InputOutputElementDefinition.Title, IG.Gr.PlotterZedGraph.Title, IG.Gr.PlotterZedGraph.Update(), IG.Gr.PlotterZedGraph.XAxis, IG.Gr.PlotterZedGraph.XAxisLabel, IG.Gr.PlotterZedGraph.Y2Axis, IG.Gr.PlotterZedGraph.Y2AxisIsVisible, IG.Gr.PlotterZedGraph.Y2AxisLabel, IG.Gr.PlotterZedGraph.Y2AxisLabelFont, IG.Gr.PlotterZedGraph.YAxisLabel, and IG.Gr.PlotterZedGraph.YAxisLabelFont.
TestSimulationExecution()
void IG.Script.S_12_01_Paper_NeuralOptCasting_00.TestSimulationExecution () inline
References IG.Num.SimCastingRobertFileManager.CalculateVectorResponse(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.GetCharacteristicSimulationParameters(), and IG.Script.ScriptShellNeuralWithSimulatorManagers.SimCastingRobertFM.
GetCharacteristicSimulationParameters()
IVector IG.Script.S_12_01_Paper_NeuralOptCasting_00.GetCharacteristicSimulationParameters () inline
Creates and returns characteristic simulation parameters.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.TestSimulationExecution().
ParSimGetNextNeuralInput()
override void IG.Script.S_12_01_Paper_NeuralOptCasting_00.ParSimGetNextNeuralInput (ref IVector simInput) inline virtual
Generates the next vector of neural input parameters that will be used for calculation of a new training element.
Reimplemented from IG.Script.LoadableScriptShellNeuralITOriginalBase.
References IG.Script.LoadableScriptShellNeuralITOriginalBase.GetRandomNeuralInput(), IG.Lib.ILockable.Lock, and IG.Lib.LoadableScriptOptBase.Random.
ParSimGetSimulationDirectoryPath()
override string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ParSimGetSimulationDirectoryPath (int threadIndex) inline virtual
Returns the simulation directory for the specified parallel calculation thread.
Parameters
threadIndex Index of parallel calculation thread for which the directory is returned.
Reimplemented from IG.Script.LoadableScriptShellNeuralITOriginalBase.
References IG.Script.LoadableScriptShellNeuralITOriginalBase.ParSimGetOptimizationDirectoryPath(), IG.Lib.SimCastingRobertConst.RootDirname, and IG.Lib.UtilSystem.StandardizeDirectoryPath().
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.ParSimGetSimulator().
ParSimGetSimulator()
override IResponseEvaluatorVectorSimple IG.Script.S_12_01_Paper_NeuralOptCasting_00.ParSimGetSimulator (int threadIndex) inline virtual
Creates simulator file manager for the simulator that will the specified parallel task.
Parameters
threadIndex Index of parallel task and its corresponding data directory.
Reimplemented from IG.Script.LoadableScriptShellNeuralITOriginalBase.
References IG.Script.S_12_01_Paper_NeuralOptCasting_00.ParSimGetSimulationDirectoryPath(), IG.Script.ScriptShellNeuralWithSimulatorManagers.SimCastingRobertProjectName, and IG.Script.ScriptShellNeuralWithSimulatorManagers.SimCastingRobertSimulationName.
PrepareTransfNeuralSimulation()
void IG.Script.S_12_01_Paper_NeuralOptCasting_00.PrepareTransfNeuralSimulation () inline protected
Prepares arrays
References IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.InputOutputDataDefiniton.GetInputIndex(), IG.Num.InputOutputDataDefiniton.InputLength, IG.Lib.ILockable.Lock, IG.Num.InputOutputElementDefinition.Name, IG.Script.LoadableScriptShellNeuralITOriginalBase.NeuralDataDefinition, IG.Script.S_12_01_Paper_NeuralOptCasting_00.NeuralInputIndices, IG.Script.S_12_01_Paper_NeuralOptCasting_00.NeuralInputNames, IG.Lib.LoadableScriptBase.OutputLevel, and IG.Script.LoadableScriptShellNeuralITOriginalBase.SimulationDataDefinition.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.TransfNeuralToSimulationInput(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.TransfSimulationToNeuralInput().
TransfSimulationToNeuralInput()
override void IG.Script.S_12_01_Paper_NeuralOptCasting_00.TransfSimulationToNeuralInput (IVector original, ref IVector result) inline virtual
Transforms the specified vector of simulation input parameters to the vector of neural input parameters and stores the vector to the specified variable.
Parameters
original Vector to be transformed.
result Vector where result of transformation is stored.
Reimplemented from IG.Script.LoadableScriptShellNeural.
References IG.Script.LoadableScriptShellNeuralITOriginalBase.GetNeuralInputDefault(), IG.Num.IVector< T >.Length, IG.Lib.ILockable.Lock, IG.Script.S_12_01_Paper_NeuralOptCasting_00.NeuralInputIndices, IG.Script.LoadableScriptShellNeuralITOriginalBase.NumNeuralParameters, IG.Script.LoadableScriptShellNeuralITOriginalBase.NumSimulationParameters, IG.Script.S_12_01_Paper_NeuralOptCasting_00.PrepareTransfNeuralSimulation(), and IG.Num.VectorBase.Resize().
TransfNeuralToSimulationInput()
override void IG.Script.S_12_01_Paper_NeuralOptCasting_00.TransfNeuralToSimulationInput (IVector original, ref IVector result) inline virtual
Transforms the specified vector of neural input parameters to the vector of simulation input parameters and stores the vector to the specified variable.
Parameters
original Vector to be transformed.
result Vector where result of transformation is stored.
Reimplemented from IG.Script.LoadableScriptShellNeural.
References IG.Script.LoadableScriptShellNeuralITOriginalBase.GetSimulationInputDefault(), IG.Num.IVector< T >.Length, IG.Lib.ILockable.Lock, IG.Script.S_12_01_Paper_NeuralOptCasting_00.NeuralInputIndices, IG.Script.LoadableScriptShellNeuralITOriginalBase.NumNeuralParameters, IG.Script.LoadableScriptShellNeuralITOriginalBase.NumSimulationParameters, IG.Script.S_12_01_Paper_NeuralOptCasting_00.PrepareTransfNeuralSimulation(), and IG.Num.VectorBase.Resize().
TransfSimulationToNeuralOutput()
override void IG.Script.S_12_01_Paper_NeuralOptCasting_00.TransfSimulationToNeuralOutput (IVector original, ref IVector result) inline virtual
Transforms the specified vector of simulation output values (results) to the vector of neural output values and stores the vector to the specified variable.
Parameters
original Vector to be transformed.
result Vector where result of transformation is stored.
Reimplemented from IG.Script.LoadableScriptShellNeural.
References IG.Num.VectorBase.Copy().
TransfNeuralToSimulationOutput()
override void IG.Script.S_12_01_Paper_NeuralOptCasting_00.TransfNeuralToSimulationOutput (IVector original, ref IVector result) inline virtual
Transforms the specified vector of neural output values to the vector of simulation output values (results) and stores the vector to the specified variable.
Parameters
original Vector to be transformed.
result Vector where result of transformation is stored.
Reimplemented from IG.Script.LoadableScriptShellNeuralITOriginalBase.
References IG.Num.VectorBase.Copy().
CusomTrainingSetExtract()
void IG.Script.S_12_01_Paper_NeuralOptCasting_00.CusomTrainingSetExtract (int whichOutput, double minValue, double maxValue, double minError, bool fromTraining, bool fromVerification) inline
Parameters
whichOutput
minValue
maxValue
minError
fromTraining
fromVerification
References IG.Num.SampledDataSet.AddElement(), IG.Script.LoadableScriptShellNeuralIT.CalculateTrainingError(), IG.Script.LoadableScriptShellNeuralIT.CalculateVerificationError(), IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.InputLength, IG.Script.LoadableScriptShellNeuralITOriginalBase.NeuralDataDefinition, IG.Num.SampledDataSet.OutputLength, IG.Neural.NeuralTadej.SaveTrainingDataCSV(), IG.Script.LoadableScriptShellNeuralITOriginalBase.TrainedNetwork, and IG.Num.INeuralApproximator.TrainingData.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.CustomTests().
CustomSensitivityTest()
void IG.Script.S_12_01_Paper_NeuralOptCasting_00.CustomSensitivityTest (IVector sensTrainingPoint, IVector sensVerificationPoint, int whichOutput, int whichParameter) inline
Write to csv file results for sensitivity test. Influence of input parameters to output values.
Parameters
sensTrainingPoint Test on training point.
sensVerificationPoint Test on verification point.
whichOutput Which output.
whichParameter Which parameter.
$A Tako78 Nov12;
References IG.Num.InputOutputDataDefiniton.GetInputElement(), IG.Num.InputOutputDataDefiniton.GetOutputElement(), IG.Num.InputOutputElementDefinition.Name, and IG.Script.LoadableScriptShellNeuralITOriginalBase.NeuralDataDefinition.
TrainANN()
void IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainANN (int annType, int[] hiddenNeurons, int MaxEpochs, int EpochsInBundle, double LearnignRate, double Momentum, double AlphaValue, double InputSafetyFactor, double OutputSafetyFactor, double PercentVerificationPoints) inline
Train the artificial neural network.
Parameters
annType 1 - NeuronDotNet, 2 - Aforge.
NumNeurons Number of neirons in 1st hidden layer.
MaxEpochs Max epochs.
EpochsInBundle Epochs in bundle.
LearnignRate Learning rate.
Momentum Momentum.
InputSafetyFactor Input safety factor.
OutputSafetyFactor Output safety factor.
PercentVerificationPoints Percentage for verification points.
References IG.Script.S_12_01_Paper_NeuralOptCasting_00.AlphaValue, IG.Script.S_12_01_Paper_NeuralOptCasting_00.ANNType, IG.Num.NeuralApproximatorBase.CalculateOutput(), IG.Num.NeuralApproximatorBase.ConvergenceErrorsTrainingRmsList, IG.Lib.IndexList.CreateRandom(), IG.Num.NeuralApproximatorBase.EpochsInBundle, IG.Script.S_12_01_Paper_NeuralOptCasting_00.EpochsInBundle, IG.Num.NeuralApproximatorBase.InputBoundsSafetyFactor, IG.Num.NeuralApproximatorBase.InputLength, IG.Num.NeuralApproximatorBase.InputNeuronsRange, IG.Script.S_12_01_Paper_NeuralOptCasting_00.InputSafetyFactor, IG.Script.S_12_01_Paper_NeuralOptCasting_00.LearnignRate, IG.Num.NeuralApproximatorBase.LearningRate, IG.Num.SampledDataSet.LoadJson(), IG.Num.NeuralApproximatorBase.MaxEpochs, IG.Script.S_12_01_Paper_NeuralOptCasting_00.MaxEpochs, IG.Num.NeuralApproximatorBase.Momentum, IG.Script.S_12_01_Paper_NeuralOptCasting_00.Momentum, IG.Num.NeuralApproximatorBase.MultipleNetworks, IG.Script.LoadableScriptShellNeuralITOriginalBase.NeuralFM, IG.Neural.NeuraApproximationFileManager.NeuralNetworkPath, IG.Neural.NeuraApproximationFileManager.NeuralTrainingDataPath, IG.Neural.NeuraApproximationFileManager.NeuralVerificationDataPath, IG.Num.NeuralApproximatorBase.OutputBoundsSafetyFactor, IG.Num.NeuralApproximatorBase.OutputLength, IG.Num.NeuralApproximatorBase.OutputLevel, IG.Num.NeuralApproximatorBase.OutputNeuronsRange, IG.Script.S_12_01_Paper_NeuralOptCasting_00.OutputSafetyFactor, IG.Script.S_12_01_Paper_NeuralOptCasting_00.PercentVerificationPoints, IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotRMSErrors(), IG.Num.IBoundingBox.Reset(), IG.Num.NeuralApproximatorBase.SaveConvergenceRms, IG.Neural.NeuralApproximatorBaseExt.SaveJson(), IG.Num.NeuralApproximatorBase.SetHiddenLayers(), IG.Num.NeuralApproximatorBase.SetTrainingAndVerificationData(), IG.Num.NeuralApproximatorBase.SigmoidAlphaValue, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Num.VectorBase.Subtract(), IG.Lib.StopWatch1.Time, IG.Num.NeuralApproximatorBase.ToleranceRms, IG.Num.IVector< T >.ToString(), IG.Num.NeuralApproximatorBase.ToString(), IG.Num.NeuralApproximatorBase.TrainingData, IG.Script.LoadableScriptShellNeuralITOriginalBase.TrainingData, IG.Num.NeuralApproximatorBase.TrainNetwork(), IG.Num.IBoundingBox.UpdateAll(), IG.Script.LoadableScriptShellNeuralITOriginalBase.VerificationData, and IG.Num.NeuralApproximatorBase.VerificationIndices.
EuclideanDistanceVRF()
void IG.Script.S_12_01_Paper_NeuralOptCasting_00.EuclideanDistanceVRF (int nearestDistanceFromPoint, ref List< IVector > averageDistancesVRF) inline
Calculates (verification points) Euclidean distnace to the N-th point.
Parameters
nearestDistanceFromPoint N-th point.
averageDistancesVRF List of distances for all points.
References IG.Num.SampledDataSet.GetInputParameters(), IG.Script.LoadableScriptShellNeuralITOriginalBase.InputDistance(), IG.Num.SampledDataSet.InputLength, IG.Num.SampledDataSet.Length, IG.Num.SampledDataSet.LoadJson(), IG.Script.LoadableScriptShellNeuralITOriginalBase.NeuralFM, IG.Neural.NeuraApproximationFileManager.NeuralVerificationDataPath, IG.Script.LoadableScriptShellNeuralITOriginalBase.TrainedNetwork, and IG.Num.INeuralApproximator.TrainingData.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistanceVRF().
EuclideanDistance()
void IG.Script.S_12_01_Paper_NeuralOptCasting_00.EuclideanDistance (int nearestDistanceFromPoint, ref List< IVector > distances, ref List< IVector > averageDistances) inline
Calculates (training points) Euclidean distnace to the N-th point.
Parameters
nearestDistanceFromPoint N-th point.
distances List of distances for all points.
References IG.Lib.SortedUniqueItemList< Type >.Contains(), IG.Num.SampledDataSet.GetInputParameters(), IG.Script.LoadableScriptShellNeuralITOriginalBase.InputDistance(), IG.Num.SampledDataSet.InputLength, IG.Num.SampledDataSet.Length, IG.Script.LoadableScriptShellNeuralITOriginalBase.TrainedNetwork, IG.Num.INeuralApproximator.TrainingData, and IG.Num.INeuralApproximator.VerificationIndices.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistance().
Member Data Documentation
ConstTrainNetwork
const string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstTrainNetwork = "TrainNetwork" static
Comamnd name for training the network.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands(), and IG.Test.ProgramTestIgorIT.TestMain().
ConstHelpTrainNetwork
const string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstHelpTrainNetwork = "Trains NN on basis of standard data. Args: <numLayers> <numNeurons>" static
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
ConstTestPlotNetworkResponse
const string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstTestPlotNetworkResponse = "TestPlotNetworkResponse" static
Comamnd name for testing network response (plots, etc.).
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands(), and IG.Test.ProgramTestIgorIT.TestMain().
ConstHelpTestPlotNetworkResponse
const string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstHelpTestPlotNetworkResponse = "Plots network response. " static
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
ConstTestNetworkResponse
const string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstTestNetworkResponse = "TestNetwork" static
Comamnd name for testing network response (plots, etc.).
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands(), and IG.Test.ProgramTestIgorIT.TestMain().
ConstHelpTestNetworkResponse
const string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstHelpTestNetworkResponse = "Shows some basic plots of network response. " static
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
ConstPlotNetworkResponseOnLine
const string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstPlotNetworkResponseOnLine = "PlotNetworkResponseOnLine" static
Comamnd name for testing network response for verification points on line for specifi Input/output.
Referenced by IG.Test.ProgramTestIgorIT.TestMain().
ConstHelpNetworkResponseOnLine
const string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstHelpNetworkResponseOnLine = "Plots network response for points on line from p1 to p2. " static
ConstPlotEuclideanDistance
const string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstPlotEuclideanDistance = "plotteuclideandistance" static
Comamnd name for testing network response for verification points on line for specifi Input/output.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
ConstHelpPlotEuclideanDistance
const string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstHelpPlotEuclideanDistance = "Plots euclidean distances for all points. " static
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
ConstPlotEuclideanDistanceVRF
const string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstPlotEuclideanDistanceVRF = "plotteuclideandistancevrf" static
Comamnd name for testing network response for verification points on line for specifi Input/output.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
ConstHelpPlotEuclideanDistanceVRF
const string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstHelpPlotEuclideanDistanceVRF = "Plots euclidean distances from verification points to training points. " static
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
ConstPlotInputOutputRelation
const string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstPlotInputOutputRelation = "plotinputoutputrelation" static
Comamnd name for testing network response for verification points on line for specifi Input/output.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
ConstHelpPlotInputOutputRelation
const string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstHelpPlotInputOutputRelation = "Plots input and output training points. " static
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
ConstSolveOpt
const string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstSolveOpt = "SolveOpt" static
Comamnd name for running solution procedure for opt. problem.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
ConstHelpSolveOpt
const string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstHelpSolveOpt = "Solves the optimization problem. " static
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
ConstTestHtmlGenerator
const string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstTestHtmlGenerator = "TestHtmlGenerator" static
Comamnd name for running solution procedure for opt. problem.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
ConstHelpTestHtmlGenerator
const string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstHelpTestHtmlGenerator = "Tests html Generation." static
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
ConstCustomTests
const string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstCustomTests = "customtests" static
Comamnd name for custom tests.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
ConstHelpCustomTests
const string IG.Script.S_12_01_Paper_NeuralOptCasting_00.ConstHelpCustomTests = "Custom tests. Args: " static
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.Script_AddCommands().
NeuralInputIndices
int [] IG.Script.S_12_01_Paper_NeuralOptCasting_00.NeuralInputIndices protected
Indices of neural input parameters in simulation input parameters.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.PrepareTransfNeuralSimulation(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.TransfNeuralToSimulationInput(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.TransfSimulationToNeuralInput().
NeuralInputNames
string [] IG.Script.S_12_01_Paper_NeuralOptCasting_00.NeuralInputNames protected
Names of neural input parameters.
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.PrepareTransfNeuralSimulation().
_numOptimizationConstraints
int IG.Script.S_12_01_Paper_NeuralOptCasting_00._numOptimizationConstraints = 0 private
ANNType
int IG.Script.S_12_01_Paper_NeuralOptCasting_00.ANNType = 1
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainANN(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainNetwork().
NumNeuronsHidden1
int IG.Script.S_12_01_Paper_NeuralOptCasting_00.NumNeuronsHidden1 = 40
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainNetwork().
NumNeuronsHidden2
int IG.Script.S_12_01_Paper_NeuralOptCasting_00.NumNeuronsHidden2 = 0
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainNetwork().
MaxEpochs
int IG.Script.S_12_01_Paper_NeuralOptCasting_00.MaxEpochs = 1000
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainANN(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainNetwork().
EpochsInBundle
int IG.Script.S_12_01_Paper_NeuralOptCasting_00.EpochsInBundle = 5
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainANN(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainNetwork().
LearnignRate
double IG.Script.S_12_01_Paper_NeuralOptCasting_00.LearnignRate = 0.3
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainANN(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainNetwork().
Momentum
double IG.Script.S_12_01_Paper_NeuralOptCasting_00.Momentum = 0.6
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainANN(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainNetwork().
AlphaValue
double IG.Script.S_12_01_Paper_NeuralOptCasting_00.AlphaValue = 1.0
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainANN(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainNetwork().
InputSafetyFactor
double IG.Script.S_12_01_Paper_NeuralOptCasting_00.InputSafetyFactor = 1.35
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainANN(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainNetwork().
OutputSafetyFactor
double IG.Script.S_12_01_Paper_NeuralOptCasting_00.OutputSafetyFactor = 1.35
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainANN(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainNetwork().
PercentVerificationPoints
double IG.Script.S_12_01_Paper_NeuralOptCasting_00.PercentVerificationPoints = 0.05
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainANN(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainNetwork().
html
HtmlWriter IG.Script.S_12_01_Paper_NeuralOptCasting_00.html = null private
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistance(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistanceVRF(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotInOutRelation(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotRMSErrors(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotTrainingAndVerificationPointsResponse(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.TestHtmlGenerator().
numPointsOnLine
int IG.Script.S_12_01_Paper_NeuralOptCasting_00.numPointsOnLine = 5 private
maxDistancePoints
bool IG.Script.S_12_01_Paper_NeuralOptCasting_00.maxDistancePoints = true private
numVerificationLinesOnGraph
int IG.Script.S_12_01_Paper_NeuralOptCasting_00.numVerificationLinesOnGraph = 5
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotVerificationAndTrainingPoints().
numTrainingLinesOnGraph
int IG.Script.S_12_01_Paper_NeuralOptCasting_00.numTrainingLinesOnGraph = 5
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotVerificationAndTrainingPoints().
enableTrainingPoint
bool IG.Script.S_12_01_Paper_NeuralOptCasting_00.enableTrainingPoint = true private
enableVerificationPoint
bool IG.Script.S_12_01_Paper_NeuralOptCasting_00.enableVerificationPoint = true private
nearestDistanceFrom
int IG.Script.S_12_01_Paper_NeuralOptCasting_00.nearestDistanceFrom = 0
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistance(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistanceVRF().
saveGraphs
bool IG.Script.S_12_01_Paper_NeuralOptCasting_00.saveGraphs = false
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistance(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistanceVRF(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotInOutRelation(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotInputOutputRelation(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotRMSErrors(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotTrainingAndVerificationPointsResponse(), IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotVerificationAndTrainingPoints(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.TrainNetwork().
enableLabels
bool IG.Script.S_12_01_Paper_NeuralOptCasting_00.enableLabels = true
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotEuclideanDistance().
verificationPointsFromFile
bool IG.Script.S_12_01_Paper_NeuralOptCasting_00.verificationPointsFromFile = false
Referenced by IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotTrainingAndVerificationPointsResponse(), and IG.Script.S_12_01_Paper_NeuralOptCasting_00.PlotVerificationAndTrainingPoints().
trainingPointsFromFile
bool IG.Script.S_12_01_Paper_NeuralOptCasting_00.trainingPointsFromFile = false
allReadFromFile
bool IG.Script.S_12_01_Paper_NeuralOptCasting_00.allReadFromFile = false
Property Documentation
NumOptimizationParameters
override int IG.Script.S_12_01_Paper_NeuralOptCasting_00.NumOptimizationParameters get protected set
Number of optimization parameters.
NumOptimizationConstraints
override int IG.Script.S_12_01_Paper_NeuralOptCasting_00.NumOptimizationConstraints get protected set
Number of optimization constraints.
The documentation for this class was generated from the following file:
shelldev/extensions/ExtShellIT/00testscriptsext/tmp/S_12_01_Paper_NeuralOptCasting_00.cs