Doc: IGLib EXTENDED: IG.Neural.Forms.NeuralTrainingControl Class Reference
IG.Neural.Forms.NeuralTrainingControl Class Reference
A 2D neural network approximation demo control.
Public Member Functions
NeuralTrainingControl ()
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
void GenerateDefaultPoints2D ()
Generates the set of default points according to settings.
void RemoveApproximationActors ()
void Bounds2D ()
void ResetAll2D ()
Reset all to default.
void PrepareDefaultPlots ()
Prepare default plots of.
Static Public Member Functions
static ColorScale CreateGreenRedYellow (double minValue, double maxValue)
Public Attributes
System.ComponentModel.BackgroundWorker backgroundWorker2D
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
INeuralModelContainer _neuralModelContainerControl
INeuralApproximator _neuralApproximator
Properties
INeuralModel NeuralModel [get, protected set]
Neural network - based model.
INeuralApproximator TrainedNetwork [get]
Traint artificial neural network.
InputOutputDataDefiniton NeuralDataDefinition [get]
Neural data definition.
INeuralApproximator network2D [get]
Traint artificial neural network.
virtual INeuralApproximator NeuralApproximator [get, set]
Neural approximator.
BoundingBox3d ScaledBounds [get]
Properties inherited from IG.Neural.INeuralModelContainer
INeuralModel NeuralModel [get]
Artificial neural network - based model.
Private Member Functions
void LoadForm (object sender, EventArgs e)
void InitializeApproximator2D ()
Clean and initialize the approximator.
void InitializeTrainingData2D ()
Clean and initialize the training data set.
void InitializeVerificationData2D ()
Clean and initialize the verification data set.
void InitializeDefaultData2D ()
Clean and initialize the default data set.
void WriteErrors2D ()
Write training and verification errors in text box.
void ClearErrorGraph2D ()
Clear Graph with error convergence for 2 dimension.
void btReset2D_Click (object sender, EventArgs e)
Reset button.
void btStart2D_Click (object sender, EventArgs e)
Start training button.
void btStop2D_Click (object sender, EventArgs e)
Stop training button.
void TrainNetworkThread2D ()
void btnGenerateOptData2D_Click (object sender, EventArgs e)
Generate training data button.
void btnShowDefault_Click (object sender, EventArgs e)
Show default graph button.
void rbMaxTrainError2D_CheckedChanged (object sender, EventArgs e)
Enable Maximum training error convergence to be written on graph.
void rbRmsTrainError2D_CheckedChanged (object sender, EventArgs e)
Enable Rms training error convergence to be written on graph.
void rbMaxVerError2D_CheckedChanged (object sender, EventArgs e)
Enable Maximum verification error convergence to be written on graph.
void rbRmsVerError2D_CheckedChanged (object sender, EventArgs e)
Enable Rms verification error convergence to be written on graph.
void numMaxEpoch2D_ValueChanged (object sender, EventArgs e)
Maximum number of epochs.
void numEpochBundle2D_ValueChanged (object sender, EventArgs e)
Number of epochs in bundle.
void numRMS2D_ValueChanged (object sender, EventArgs e)
Rms error limit.
void numLearningRate2D_ValueChanged (object sender, EventArgs e)
Learning rate.
void numMomentum2D_ValueChanged (object sender, EventArgs e)
Momentum.
void numHiddenNeuron2D_ValueChanged (object sender, EventArgs e)
Number of neurons in first hidden layer.
void numHiddenNeuronL22D_ValueChanged (object sender, EventArgs e)
Number of neurons in second hidden layer.
void numInputSafety2D_ValueChanged (object sender, EventArgs e)
Input safety factor.
void numOutputSafety2D_ValueChanged (object sender, EventArgs e)
Output safety factor.
void backgroundWorker2D_DoWork (object sender, DoWorkEventArgs e)
void backgroundWorker2D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
INeuralModel _neuralModel
GraphPane pane2DError
Error graph.
SampledDataSet trainingData2D = null
Training data set.
SampledDataSet verificationData2D = null
Verification data set.
SampledDataSet defaultFunctionData2D = null
Default data set.
int hiddenNeuronL12D = 5
int hiddenNeuronL22D = 0
int maxEpoch2D = 5000
int epochInBundle2D = 500
double rmsError2D = 0.001
double learningRate2D = 0.3
double momentum2D = 0.6
double lowHorizontalLimit2D = -1.0
double highHorizontalLimit2D = 1.0
double lowVerticalLimit2D = -1.0
double highVerticalLimit2D = 1.0
double inputSafetyFactor2D = 1.3
double outputSafetyFactor2D = 1.3
string equation2D = "x*x + y*y"
string[] variableNames2D = { "x", "y" }
bool maxTrainErrorEnabled2D = true
bool rmsTrainErrorEnabled2D = false
bool maxVerErrorEnabled2D = false
bool rmsVerErrorEnabled2D = false
int numAllXPoints2D = 100
int numAllYPoints2D = 100
LineItem errorConvergenceFunction2D
Func2dFromScalarFunction iFunctionDefault2D
Scalar function that is approximated.
IScalarFunction scalarFunctionDefault2D
Scalar function that is approximated.
StructuredMesh2d3d Default2DMesh
Maeh of default points used for plotting.
BoundingBox2d paramBounds2D
Bounding box for function limits. </summary
BoundingBox3d _scaledBounds
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.TextBox tbEquationError2D
System.Windows.Forms.RadioButton rbRmsTrainError2D
System.Windows.Forms.RadioButton rbMaxTrainError2D
System.Windows.Forms.RadioButton rbRmsVerError2D
System.Windows.Forms.RadioButton rbMaxVerError2D
System.Windows.Forms.TextBox tbRmsTrainError2D
System.Windows.Forms.Label label26
System.Windows.Forms.Label label27
System.Windows.Forms.TextBox tbMaxTrainError2D
System.Windows.Forms.TextBox tbRmsVerError2D
System.Windows.Forms.TextBox tbMaxVerError2D
System.Windows.Forms.Label label28
System.Windows.Forms.Label label29
ZedGraph.ZedGraphControl errorConvergence2D
System.Windows.Forms.NumericUpDown numHiddenNeuronL22D
System.Windows.Forms.NumericUpDown numHiddenNeuron2D
System.Windows.Forms.Button btLoadANN2D
System.Windows.Forms.Button btSaveANN2D
System.Windows.Forms.Button btReset2D
System.Windows.Forms.Button btStart2D
System.Windows.Forms.NumericUpDown numOutputSafety2D
System.Windows.Forms.Label label17
System.Windows.Forms.NumericUpDown numInputSafety2D
System.Windows.Forms.Label label18
System.Windows.Forms.Label label20
System.Windows.Forms.NumericUpDown numMomentum2D
System.Windows.Forms.NumericUpDown numLearningRate2D
System.Windows.Forms.NumericUpDown numRMS2D
System.Windows.Forms.NumericUpDown numEpochBundle2D
System.Windows.Forms.NumericUpDown numMaxEpoch2D
System.Windows.Forms.Label label21
System.Windows.Forms.Label label22
System.Windows.Forms.Label label23
System.Windows.Forms.Label label24
System.Windows.Forms.Label label25
System.Windows.Forms.Button btLoad2D
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.GroupBox groupBox2
System.Windows.Forms.GroupBox groupBox4
System.Windows.Forms.Button btStop2D
Detailed Description
A 2D neural network approximation demo control.
$A Tadej xx; Igor Feb13;
Constructor & Destructor Documentation
NeuralTrainingControl()
IG.Neural.Forms.NeuralTrainingControl.NeuralTrainingControl () inline
References IG.Neural.Forms.NeuralTrainingControl.Bounds2D(), and IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
Member Function Documentation
SetNeuralModel()
void IG.Neural.Forms.NeuralTrainingControl.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
Implements IG.Neural.INeuralModelContainer.
References IG.Neural.Forms.NeuralTrainingControl.NeuralModel.
LoadForm()
void IG.Neural.Forms.NeuralTrainingControl.LoadForm (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralTrainingControl.errorConvergence2D, and IG.Neural.Forms.NeuralTrainingControl.pane2DError.
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
CreateGreenRedYellow()
static ColorScale IG.Neural.Forms.NeuralTrainingControl.CreateGreenRedYellow (double minValue, double maxValue) inline static
InitializeApproximator2D()
void IG.Neural.Forms.NeuralTrainingControl.InitializeApproximator2D () inline private
Clean and initialize the approximator.
References IG.Neural.Forms.NeuralTrainingControl.NeuralApproximator.
Referenced by IG.Neural.Forms.NeuralTrainingControl.btnGenerateOptData2D_Click(), IG.Neural.Forms.NeuralTrainingControl.btStart2D_Click(), and IG.Neural.Forms.NeuralTrainingControl.ResetAll2D().
InitializeTrainingData2D()
void IG.Neural.Forms.NeuralTrainingControl.InitializeTrainingData2D () inline private
Clean and initialize the training data set.
References IG.Neural.Forms.NeuralTrainingControl.trainingData2D.
Referenced by IG.Neural.Forms.NeuralTrainingControl.btnGenerateOptData2D_Click(), and IG.Neural.Forms.NeuralTrainingControl.ResetAll2D().
InitializeVerificationData2D()
void IG.Neural.Forms.NeuralTrainingControl.InitializeVerificationData2D () inline private
Clean and initialize the verification data set.
References IG.Neural.Forms.NeuralTrainingControl.verificationData2D.
Referenced by IG.Neural.Forms.NeuralTrainingControl.btnGenerateOptData2D_Click(), and IG.Neural.Forms.NeuralTrainingControl.ResetAll2D().
InitializeDefaultData2D()
void IG.Neural.Forms.NeuralTrainingControl.InitializeDefaultData2D () inline private
Clean and initialize the default data set.
References IG.Neural.Forms.NeuralTrainingControl.defaultFunctionData2D.
Referenced by IG.Neural.Forms.NeuralTrainingControl.btnGenerateOptData2D_Click(), and IG.Neural.Forms.NeuralTrainingControl.ResetAll2D().
WriteErrors2D()
void IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D () inline private
Write training and verification errors in text box.
References IG.Neural.Forms.NeuralTrainingControl.ClearErrorGraph2D(), IG.Num.INeuralApproximator.ConvergenceErrorsTrainingMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsTrainingRmsList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationRmsList, IG.Neural.Forms.NeuralTrainingControl.epochInBundle2D, IG.Neural.Forms.NeuralTrainingControl.errorConvergence2D, IG.Neural.Forms.NeuralTrainingControl.errorConvergenceFunction2D, IG.Num.INeuralApproximator.GetErrorsTrainingMax(), IG.Num.INeuralApproximator.GetErrorsTrainingRms(), IG.Num.INeuralApproximator.GetErrorsVerificationMax(), IG.Num.INeuralApproximator.GetErrorsVerificationRms(), IG.Neural.Forms.NeuralTrainingControl.maxTrainErrorEnabled2D, IG.Neural.Forms.NeuralTrainingControl.maxVerErrorEnabled2D, IG.Neural.Forms.NeuralTrainingControl.NeuralApproximator, IG.Neural.Forms.NeuralTrainingControl.pane2DError, IG.Neural.Forms.NeuralTrainingControl.rmsTrainErrorEnabled2D, IG.Neural.Forms.NeuralTrainingControl.rmsVerErrorEnabled2D, IG.Neural.Forms.NeuralTrainingControl.tbMaxTrainError2D, IG.Neural.Forms.NeuralTrainingControl.tbMaxVerError2D, IG.Neural.Forms.NeuralTrainingControl.tbRmsTrainError2D, and IG.Neural.Forms.NeuralTrainingControl.tbRmsVerError2D.
Referenced by IG.Neural.Forms.NeuralTrainingControl.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralTrainingControl.rbMaxTrainError2D_CheckedChanged(), IG.Neural.Forms.NeuralTrainingControl.rbMaxVerError2D_CheckedChanged(), IG.Neural.Forms.NeuralTrainingControl.rbRmsTrainError2D_CheckedChanged(), and IG.Neural.Forms.NeuralTrainingControl.rbRmsVerError2D_CheckedChanged().
ClearErrorGraph2D()
void IG.Neural.Forms.NeuralTrainingControl.ClearErrorGraph2D () inline private
Clear Graph with error convergence for 2 dimension.
References IG.Neural.Forms.NeuralTrainingControl.errorConvergence2D, IG.Neural.Forms.NeuralTrainingControl.errorConvergenceFunction2D, IG.Neural.Forms.NeuralTrainingControl.tbMaxTrainError2D, IG.Neural.Forms.NeuralTrainingControl.tbMaxVerError2D, IG.Neural.Forms.NeuralTrainingControl.tbRmsTrainError2D, and IG.Neural.Forms.NeuralTrainingControl.tbRmsVerError2D.
Referenced by IG.Neural.Forms.NeuralTrainingControl.btnGenerateOptData2D_Click(), IG.Neural.Forms.NeuralTrainingControl.btStart2D_Click(), IG.Neural.Forms.NeuralTrainingControl.ResetAll2D(), and IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D().
GenerateDefaultPoints2D()
void IG.Neural.Forms.NeuralTrainingControl.GenerateDefaultPoints2D () inline
Generates the set of default points according to settings.
References IG.Num.Func2dFromScalarScript.CreateScalarFunction(), IG.Neural.Forms.NeuralTrainingControl.Default2DMesh, IG.Neural.Forms.NeuralTrainingControl.equation2D, IG.Num.StructuredMesh2d3d.GenerateCoordinates(), IG.Neural.Forms.NeuralTrainingControl.iFunctionDefault2D, IG.Num.BoundingBox2d.MaxX, IG.Num.BoundingBox2d.MaxY, IG.Num.BoundingBox2d.MinX, IG.Num.BoundingBox2d.MinY, IG.Neural.Forms.NeuralTrainingControl.numAllXPoints2D, IG.Neural.Forms.NeuralTrainingControl.numAllYPoints2D, IG.Neural.Forms.NeuralTrainingControl.paramBounds2D, IG.Neural.Forms.NeuralTrainingControl.scalarFunctionDefault2D, IG.Neural.Forms.NeuralTrainingControl.tbEquationError2D, IG.Num.IScalarFunctionUntransformed.Value(), and IG.Neural.Forms.NeuralTrainingControl.variableNames2D.
Referenced by IG.Neural.Forms.NeuralTrainingControl.btnGenerateOptData2D_Click().
RemoveApproximationActors()
void IG.Neural.Forms.NeuralTrainingControl.RemoveApproximationActors () inline
Referenced by IG.Neural.Forms.NeuralTrainingControl.btnGenerateOptData2D_Click(), and IG.Neural.Forms.NeuralTrainingControl.ResetAll2D().
Bounds2D()
void IG.Neural.Forms.NeuralTrainingControl.Bounds2D () inline
References IG.Neural.Forms.NeuralTrainingControl.highHorizontalLimit2D, IG.Neural.Forms.NeuralTrainingControl.highVerticalLimit2D, IG.Neural.Forms.NeuralTrainingControl.lowHorizontalLimit2D, IG.Neural.Forms.NeuralTrainingControl.lowVerticalLimit2D, and IG.Neural.Forms.NeuralTrainingControl.paramBounds2D.
Referenced by IG.Neural.Forms.NeuralTrainingControl.NeuralTrainingControl().
ResetAll2D()
void IG.Neural.Forms.NeuralTrainingControl.ResetAll2D () inline
Reset all to default.
References IG.Neural.Forms.NeuralTrainingControl.btStart2D, IG.Neural.Forms.NeuralTrainingControl.ClearErrorGraph2D(), IG.Neural.Forms.NeuralTrainingControl.InitializeApproximator2D(), IG.Neural.Forms.NeuralTrainingControl.InitializeDefaultData2D(), IG.Neural.Forms.NeuralTrainingControl.InitializeTrainingData2D(), IG.Neural.Forms.NeuralTrainingControl.InitializeVerificationData2D(), and IG.Neural.Forms.NeuralTrainingControl.RemoveApproximationActors().
Referenced by IG.Neural.Forms.NeuralTrainingControl.btReset2D_Click().
btReset2D_Click()
void IG.Neural.Forms.NeuralTrainingControl.btReset2D_Click (object sender, EventArgs e) inline private
Reset button.
References IG.Neural.Forms.NeuralTrainingControl.ResetAll2D().
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
btStart2D_Click()
void IG.Neural.Forms.NeuralTrainingControl.btStart2D_Click (object sender, EventArgs e) inline private
Start training button.
References IG.Num.SampledDataSet.AddElement(), IG.Neural.Forms.NeuralTrainingControl.btLoadANN2D, IG.Neural.Forms.NeuralTrainingControl.btReset2D, IG.Neural.Forms.NeuralTrainingControl.btSaveANN2D, IG.Neural.Forms.NeuralTrainingControl.btStart2D, IG.Neural.Forms.NeuralTrainingControl.btStop2D, IG.Neural.Forms.NeuralTrainingControl.ClearErrorGraph2D(), IG.Neural.Forms.NeuralTrainingControl.InitializeApproximator2D(), IG.Num.SampledDataSet.InputLength, IG.Num.INeuralApproximator.LearningRate, IG.Neural.Forms.NeuralTrainingControl.learningRate2D, IG.Num.INeuralApproximator.Momentum, IG.Neural.Forms.NeuralTrainingControl.momentum2D, IG.Neural.Forms.NeuralTrainingControl.network2D, IG.Neural.Forms.NeuralTrainingControl.numAllXPoints2D, IG.Neural.Forms.NeuralTrainingControl.numAllYPoints2D, IG.Num.SampledDataSet.OutputLength, IG.Neural.Forms.NeuralTrainingControl.trainingData2D, IG.Neural.Forms.NeuralTrainingControl.TrainNetworkThread2D(), and IG.Neural.Forms.NeuralTrainingControl.verificationData2D.
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
btStop2D_Click()
void IG.Neural.Forms.NeuralTrainingControl.btStop2D_Click (object sender, EventArgs e) inline private
Stop training button.
References IG.Num.INeuralApproximator.BreakTraining, and IG.Neural.Forms.NeuralTrainingControl.network2D.
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
TrainNetworkThread2D()
void IG.Neural.Forms.NeuralTrainingControl.TrainNetworkThread2D () inline private
References IG.Neural.Forms.NeuralTrainingControl.backgroundWorker2D.
Referenced by IG.Neural.Forms.NeuralTrainingControl.btStart2D_Click().
btnGenerateOptData2D_Click()
void IG.Neural.Forms.NeuralTrainingControl.btnGenerateOptData2D_Click (object sender, EventArgs e) inline private
Generate training data button.
References IG.Neural.Forms.NeuralTrainingControl.btStart2D, IG.Neural.Forms.NeuralTrainingControl.ClearErrorGraph2D(), IG.Neural.Forms.NeuralTrainingControl.GenerateDefaultPoints2D(), IG.Neural.Forms.NeuralTrainingControl.InitializeApproximator2D(), IG.Neural.Forms.NeuralTrainingControl.InitializeDefaultData2D(), IG.Neural.Forms.NeuralTrainingControl.InitializeTrainingData2D(), IG.Neural.Forms.NeuralTrainingControl.InitializeVerificationData2D(), IG.Neural.Forms.NeuralTrainingControl.PrepareDefaultPlots(), and IG.Neural.Forms.NeuralTrainingControl.RemoveApproximationActors().
btnShowDefault_Click()
void IG.Neural.Forms.NeuralTrainingControl.btnShowDefault_Click (object sender, EventArgs e) inline private
Show default graph button.
PrepareDefaultPlots()
void IG.Neural.Forms.NeuralTrainingControl.PrepareDefaultPlots () inline
Prepare default plots of.
Referenced by IG.Neural.Forms.NeuralTrainingControl.btnGenerateOptData2D_Click().
rbMaxTrainError2D_CheckedChanged()
void IG.Neural.Forms.NeuralTrainingControl.rbMaxTrainError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum training error convergence to be written on graph.
References IG.Neural.Forms.NeuralTrainingControl.maxTrainErrorEnabled2D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralTrainingControl.NeuralApproximator, and IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D().
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
rbRmsTrainError2D_CheckedChanged()
void IG.Neural.Forms.NeuralTrainingControl.rbRmsTrainError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms training error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralTrainingControl.NeuralApproximator, IG.Neural.Forms.NeuralTrainingControl.rmsTrainErrorEnabled2D, and IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D().
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
rbMaxVerError2D_CheckedChanged()
void IG.Neural.Forms.NeuralTrainingControl.rbMaxVerError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum verification error convergence to be written on graph.
References IG.Neural.Forms.NeuralTrainingControl.maxVerErrorEnabled2D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralTrainingControl.NeuralApproximator, and IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D().
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
rbRmsVerError2D_CheckedChanged()
void IG.Neural.Forms.NeuralTrainingControl.rbRmsVerError2D_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms verification error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralTrainingControl.NeuralApproximator, IG.Neural.Forms.NeuralTrainingControl.rmsVerErrorEnabled2D, and IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D().
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
numMaxEpoch2D_ValueChanged()
void IG.Neural.Forms.NeuralTrainingControl.numMaxEpoch2D_ValueChanged (object sender, EventArgs e) inline private
Maximum number of epochs.
References IG.Neural.Forms.NeuralTrainingControl.maxEpoch2D, and IG.Neural.Forms.NeuralTrainingControl.numMaxEpoch2D.
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
numEpochBundle2D_ValueChanged()
void IG.Neural.Forms.NeuralTrainingControl.numEpochBundle2D_ValueChanged (object sender, EventArgs e) inline private
Number of epochs in bundle.
References IG.Neural.Forms.NeuralTrainingControl.epochInBundle2D, and IG.Neural.Forms.NeuralTrainingControl.numEpochBundle2D.
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
numRMS2D_ValueChanged()
void IG.Neural.Forms.NeuralTrainingControl.numRMS2D_ValueChanged (object sender, EventArgs e) inline private
Rms error limit.
References IG.Neural.Forms.NeuralTrainingControl.numRMS2D, and IG.Neural.Forms.NeuralTrainingControl.rmsError2D.
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
numLearningRate2D_ValueChanged()
void IG.Neural.Forms.NeuralTrainingControl.numLearningRate2D_ValueChanged (object sender, EventArgs e) inline private
Learning rate.
References IG.Neural.Forms.NeuralTrainingControl.learningRate2D, and IG.Neural.Forms.NeuralTrainingControl.numLearningRate2D.
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
numMomentum2D_ValueChanged()
void IG.Neural.Forms.NeuralTrainingControl.numMomentum2D_ValueChanged (object sender, EventArgs e) inline private
Momentum.
References IG.Neural.Forms.NeuralTrainingControl.momentum2D, and IG.Neural.Forms.NeuralTrainingControl.numMomentum2D.
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
numHiddenNeuron2D_ValueChanged()
void IG.Neural.Forms.NeuralTrainingControl.numHiddenNeuron2D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in first hidden layer.
References IG.Neural.Forms.NeuralTrainingControl.hiddenNeuronL12D, and IG.Neural.Forms.NeuralTrainingControl.numHiddenNeuron2D.
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
numHiddenNeuronL22D_ValueChanged()
void IG.Neural.Forms.NeuralTrainingControl.numHiddenNeuronL22D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in second hidden layer.
References IG.Neural.Forms.NeuralTrainingControl.hiddenNeuronL22D, and IG.Neural.Forms.NeuralTrainingControl.numHiddenNeuronL22D.
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
numInputSafety2D_ValueChanged()
void IG.Neural.Forms.NeuralTrainingControl.numInputSafety2D_ValueChanged (object sender, EventArgs e) inline private
Input safety factor.
References IG.Neural.Forms.NeuralTrainingControl.inputSafetyFactor2D, and IG.Neural.Forms.NeuralTrainingControl.numInputSafety2D.
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
numOutputSafety2D_ValueChanged()
void IG.Neural.Forms.NeuralTrainingControl.numOutputSafety2D_ValueChanged (object sender, EventArgs e) inline private
Output safety factor.
References IG.Neural.Forms.NeuralTrainingControl.numOutputSafety2D, and IG.Neural.Forms.NeuralTrainingControl.outputSafetyFactor2D.
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
backgroundWorker2D_DoWork()
void IG.Neural.Forms.NeuralTrainingControl.backgroundWorker2D_DoWork (object sender, DoWorkEventArgs e) inline private
References IG.Num.INeuralApproximator.BreakTraining, IG.Neural.Forms.NeuralTrainingControl.network2D, IG.Lib.StopWatch1.Start(), and IG.Lib.StopWatch1.Stop().
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
backgroundWorker2D_RunWorkerCompleted()
void IG.Neural.Forms.NeuralTrainingControl.backgroundWorker2D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
References IG.Neural.Forms.NeuralTrainingControl.btLoadANN2D, IG.Neural.Forms.NeuralTrainingControl.btReset2D, IG.Neural.Forms.NeuralTrainingControl.btSaveANN2D, IG.Neural.Forms.NeuralTrainingControl.btStart2D, IG.Neural.Forms.NeuralTrainingControl.btStop2D, and IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D().
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
Dispose()
override void IG.Neural.Forms.NeuralTrainingControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralTrainingControl.components.
InitializeComponent()
void IG.Neural.Forms.NeuralTrainingControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralTrainingControl.backgroundWorker2D, IG.Neural.Forms.NeuralTrainingControl.backgroundWorker2D_DoWork(), IG.Neural.Forms.NeuralTrainingControl.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralTrainingControl.btLoad2D, IG.Neural.Forms.NeuralTrainingControl.btLoadANN2D, IG.Neural.Forms.NeuralTrainingControl.btReset2D, IG.Neural.Forms.NeuralTrainingControl.btReset2D_Click(), IG.Neural.Forms.NeuralTrainingControl.btSaveANN2D, IG.Neural.Forms.NeuralTrainingControl.btStart2D, IG.Neural.Forms.NeuralTrainingControl.btStart2D_Click(), IG.Neural.Forms.NeuralTrainingControl.btStop2D, IG.Neural.Forms.NeuralTrainingControl.btStop2D_Click(), IG.Neural.Forms.NeuralTrainingControl.components, IG.Neural.Forms.NeuralTrainingControl.errorConvergence2D, IG.Neural.Forms.NeuralTrainingControl.groupBox1, IG.Neural.Forms.NeuralTrainingControl.groupBox2, IG.Neural.Forms.NeuralTrainingControl.groupBox4, IG.Neural.Forms.NeuralTrainingControl.label17, IG.Neural.Forms.NeuralTrainingControl.label18, IG.Neural.Forms.NeuralTrainingControl.label20, IG.Neural.Forms.NeuralTrainingControl.label21, IG.Neural.Forms.NeuralTrainingControl.label22, IG.Neural.Forms.NeuralTrainingControl.label23, IG.Neural.Forms.NeuralTrainingControl.label24, IG.Neural.Forms.NeuralTrainingControl.label25, IG.Neural.Forms.NeuralTrainingControl.label26, IG.Neural.Forms.NeuralTrainingControl.label27, IG.Neural.Forms.NeuralTrainingControl.label28, IG.Neural.Forms.NeuralTrainingControl.label29, IG.Neural.Forms.NeuralTrainingControl.LoadForm(), IG.Neural.Forms.NeuralTrainingControl.numEpochBundle2D, IG.Neural.Forms.NeuralTrainingControl.numEpochBundle2D_ValueChanged(), IG.Neural.Forms.NeuralTrainingControl.numHiddenNeuron2D, IG.Neural.Forms.NeuralTrainingControl.numHiddenNeuron2D_ValueChanged(), IG.Neural.Forms.NeuralTrainingControl.numHiddenNeuronL22D, IG.Neural.Forms.NeuralTrainingControl.numHiddenNeuronL22D_ValueChanged(), IG.Neural.Forms.NeuralTrainingControl.numInputSafety2D, IG.Neural.Forms.NeuralTrainingControl.numInputSafety2D_ValueChanged(), IG.Neural.Forms.NeuralTrainingControl.numLearningRate2D, IG.Neural.Forms.NeuralTrainingControl.numLearningRate2D_ValueChanged(), IG.Neural.Forms.NeuralTrainingControl.numMaxEpoch2D, IG.Neural.Forms.NeuralTrainingControl.numMaxEpoch2D_ValueChanged(), IG.Neural.Forms.NeuralTrainingControl.numMomentum2D, IG.Neural.Forms.NeuralTrainingControl.numMomentum2D_ValueChanged(), IG.Neural.Forms.NeuralTrainingControl.numOutputSafety2D, IG.Neural.Forms.NeuralTrainingControl.numOutputSafety2D_ValueChanged(), IG.Neural.Forms.NeuralTrainingControl.numRMS2D, IG.Neural.Forms.NeuralTrainingControl.numRMS2D_ValueChanged(), IG.Neural.Forms.NeuralTrainingControl.rbMaxTrainError2D, IG.Neural.Forms.NeuralTrainingControl.rbMaxTrainError2D_CheckedChanged(), IG.Neural.Forms.NeuralTrainingControl.rbMaxVerError2D, IG.Neural.Forms.NeuralTrainingControl.rbMaxVerError2D_CheckedChanged(), IG.Neural.Forms.NeuralTrainingControl.rbRmsTrainError2D, IG.Neural.Forms.NeuralTrainingControl.rbRmsTrainError2D_CheckedChanged(), IG.Neural.Forms.NeuralTrainingControl.rbRmsVerError2D, IG.Neural.Forms.NeuralTrainingControl.rbRmsVerError2D_CheckedChanged(), IG.Neural.Forms.NeuralTrainingControl.tbEquationError2D, IG.Neural.Forms.NeuralTrainingControl.tbMaxTrainError2D, IG.Neural.Forms.NeuralTrainingControl.tbMaxVerError2D, IG.Neural.Forms.NeuralTrainingControl.tbRmsTrainError2D, and IG.Neural.Forms.NeuralTrainingControl.tbRmsVerError2D.
Referenced by IG.Neural.Forms.NeuralTrainingControl.NeuralTrainingControl().
Member Data Documentation
_neuralModelContainerControl
INeuralModelContainer IG.Neural.Forms.NeuralTrainingControl._neuralModelContainerControl protected
_neuralModel
INeuralModel IG.Neural.Forms.NeuralTrainingControl._neuralModel private
pane2DError
GraphPane IG.Neural.Forms.NeuralTrainingControl.pane2DError private
Error graph.
Referenced by IG.Neural.Forms.NeuralTrainingControl.LoadForm(), and IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D().
_neuralApproximator
INeuralApproximator IG.Neural.Forms.NeuralTrainingControl._neuralApproximator protected
trainingData2D
SampledDataSet IG.Neural.Forms.NeuralTrainingControl.trainingData2D = null private
Training data set.
Referenced by IG.Neural.Forms.NeuralTrainingControl.btStart2D_Click(), and IG.Neural.Forms.NeuralTrainingControl.InitializeTrainingData2D().
verificationData2D
SampledDataSet IG.Neural.Forms.NeuralTrainingControl.verificationData2D = null private
Verification data set.
Referenced by IG.Neural.Forms.NeuralTrainingControl.btStart2D_Click(), and IG.Neural.Forms.NeuralTrainingControl.InitializeVerificationData2D().
defaultFunctionData2D
SampledDataSet IG.Neural.Forms.NeuralTrainingControl.defaultFunctionData2D = null private
Default data set.
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeDefaultData2D().
hiddenNeuronL12D
int IG.Neural.Forms.NeuralTrainingControl.hiddenNeuronL12D = 5 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.numHiddenNeuron2D_ValueChanged().
hiddenNeuronL22D
int IG.Neural.Forms.NeuralTrainingControl.hiddenNeuronL22D = 0 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.numHiddenNeuronL22D_ValueChanged().
maxEpoch2D
int IG.Neural.Forms.NeuralTrainingControl.maxEpoch2D = 5000 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.numMaxEpoch2D_ValueChanged().
epochInBundle2D
int IG.Neural.Forms.NeuralTrainingControl.epochInBundle2D = 500 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.numEpochBundle2D_ValueChanged(), and IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D().
rmsError2D
double IG.Neural.Forms.NeuralTrainingControl.rmsError2D = 0.001 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.numRMS2D_ValueChanged().
learningRate2D
double IG.Neural.Forms.NeuralTrainingControl.learningRate2D = 0.3 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.btStart2D_Click(), and IG.Neural.Forms.NeuralTrainingControl.numLearningRate2D_ValueChanged().
momentum2D
double IG.Neural.Forms.NeuralTrainingControl.momentum2D = 0.6 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.btStart2D_Click(), and IG.Neural.Forms.NeuralTrainingControl.numMomentum2D_ValueChanged().
lowHorizontalLimit2D
double IG.Neural.Forms.NeuralTrainingControl.lowHorizontalLimit2D = -1.0 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.Bounds2D().
highHorizontalLimit2D
double IG.Neural.Forms.NeuralTrainingControl.highHorizontalLimit2D = 1.0 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.Bounds2D().
lowVerticalLimit2D
double IG.Neural.Forms.NeuralTrainingControl.lowVerticalLimit2D = -1.0 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.Bounds2D().
highVerticalLimit2D
double IG.Neural.Forms.NeuralTrainingControl.highVerticalLimit2D = 1.0 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.Bounds2D().
inputSafetyFactor2D
double IG.Neural.Forms.NeuralTrainingControl.inputSafetyFactor2D = 1.3 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.numInputSafety2D_ValueChanged().
outputSafetyFactor2D
double IG.Neural.Forms.NeuralTrainingControl.outputSafetyFactor2D = 1.3 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.numOutputSafety2D_ValueChanged().
equation2D
string IG.Neural.Forms.NeuralTrainingControl.equation2D = "x*x + y*y" private
Referenced by IG.Neural.Forms.NeuralTrainingControl.GenerateDefaultPoints2D().
variableNames2D
string [] IG.Neural.Forms.NeuralTrainingControl.variableNames2D = { "x", "y" } private
Referenced by IG.Neural.Forms.NeuralTrainingControl.GenerateDefaultPoints2D().
maxTrainErrorEnabled2D
bool IG.Neural.Forms.NeuralTrainingControl.maxTrainErrorEnabled2D = true private
Referenced by IG.Neural.Forms.NeuralTrainingControl.rbMaxTrainError2D_CheckedChanged(), and IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D().
rmsTrainErrorEnabled2D
bool IG.Neural.Forms.NeuralTrainingControl.rmsTrainErrorEnabled2D = false private
Referenced by IG.Neural.Forms.NeuralTrainingControl.rbRmsTrainError2D_CheckedChanged(), and IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D().
maxVerErrorEnabled2D
bool IG.Neural.Forms.NeuralTrainingControl.maxVerErrorEnabled2D = false private
Referenced by IG.Neural.Forms.NeuralTrainingControl.rbMaxVerError2D_CheckedChanged(), and IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D().
rmsVerErrorEnabled2D
bool IG.Neural.Forms.NeuralTrainingControl.rmsVerErrorEnabled2D = false private
Referenced by IG.Neural.Forms.NeuralTrainingControl.rbRmsVerError2D_CheckedChanged(), and IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D().
numAllXPoints2D
int IG.Neural.Forms.NeuralTrainingControl.numAllXPoints2D = 100 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.btStart2D_Click(), and IG.Neural.Forms.NeuralTrainingControl.GenerateDefaultPoints2D().
numAllYPoints2D
int IG.Neural.Forms.NeuralTrainingControl.numAllYPoints2D = 100 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.btStart2D_Click(), and IG.Neural.Forms.NeuralTrainingControl.GenerateDefaultPoints2D().
errorConvergenceFunction2D
LineItem IG.Neural.Forms.NeuralTrainingControl.errorConvergenceFunction2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.ClearErrorGraph2D(), and IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D().
iFunctionDefault2D
Func2dFromScalarFunction IG.Neural.Forms.NeuralTrainingControl.iFunctionDefault2D private
Scalar function that is approximated.
Referenced by IG.Neural.Forms.NeuralTrainingControl.GenerateDefaultPoints2D().
scalarFunctionDefault2D
IScalarFunction IG.Neural.Forms.NeuralTrainingControl.scalarFunctionDefault2D private
Scalar function that is approximated.
Referenced by IG.Neural.Forms.NeuralTrainingControl.GenerateDefaultPoints2D().
Default2DMesh
StructuredMesh2d3d IG.Neural.Forms.NeuralTrainingControl.Default2DMesh private
Maeh of default points used for plotting.
Referenced by IG.Neural.Forms.NeuralTrainingControl.GenerateDefaultPoints2D().
paramBounds2D
BoundingBox2d IG.Neural.Forms.NeuralTrainingControl.paramBounds2D private
Bounding box for function limits. </summary
Referenced by IG.Neural.Forms.NeuralTrainingControl.Bounds2D(), and IG.Neural.Forms.NeuralTrainingControl.GenerateDefaultPoints2D().
_scaledBounds
BoundingBox3d IG.Neural.Forms.NeuralTrainingControl._scaledBounds private
components
System.ComponentModel.IContainer IG.Neural.Forms.NeuralTrainingControl.components = null private
Required designer variable.
Referenced by IG.Neural.Forms.NeuralTrainingControl.Dispose(), and IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
tbEquationError2D
System.Windows.Forms.TextBox IG.Neural.Forms.NeuralTrainingControl.tbEquationError2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.GenerateDefaultPoints2D(), and IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
rbRmsTrainError2D
System.Windows.Forms.RadioButton IG.Neural.Forms.NeuralTrainingControl.rbRmsTrainError2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
rbMaxTrainError2D
System.Windows.Forms.RadioButton IG.Neural.Forms.NeuralTrainingControl.rbMaxTrainError2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
rbRmsVerError2D
System.Windows.Forms.RadioButton IG.Neural.Forms.NeuralTrainingControl.rbRmsVerError2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
rbMaxVerError2D
System.Windows.Forms.RadioButton IG.Neural.Forms.NeuralTrainingControl.rbMaxVerError2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
tbRmsTrainError2D
System.Windows.Forms.TextBox IG.Neural.Forms.NeuralTrainingControl.tbRmsTrainError2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.ClearErrorGraph2D(), IG.Neural.Forms.NeuralTrainingControl.InitializeComponent(), and IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D().
label26
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label26 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
label27
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label27 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
tbMaxTrainError2D
System.Windows.Forms.TextBox IG.Neural.Forms.NeuralTrainingControl.tbMaxTrainError2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.ClearErrorGraph2D(), IG.Neural.Forms.NeuralTrainingControl.InitializeComponent(), and IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D().
tbRmsVerError2D
System.Windows.Forms.TextBox IG.Neural.Forms.NeuralTrainingControl.tbRmsVerError2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.ClearErrorGraph2D(), IG.Neural.Forms.NeuralTrainingControl.InitializeComponent(), and IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D().
tbMaxVerError2D
System.Windows.Forms.TextBox IG.Neural.Forms.NeuralTrainingControl.tbMaxVerError2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.ClearErrorGraph2D(), IG.Neural.Forms.NeuralTrainingControl.InitializeComponent(), and IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D().
label28
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label28 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
label29
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label29 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
errorConvergence2D
ZedGraph.ZedGraphControl IG.Neural.Forms.NeuralTrainingControl.errorConvergence2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.ClearErrorGraph2D(), IG.Neural.Forms.NeuralTrainingControl.InitializeComponent(), IG.Neural.Forms.NeuralTrainingControl.LoadForm(), and IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D().
numHiddenNeuronL22D
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralTrainingControl.numHiddenNeuronL22D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent(), and IG.Neural.Forms.NeuralTrainingControl.numHiddenNeuronL22D_ValueChanged().
numHiddenNeuron2D
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralTrainingControl.numHiddenNeuron2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent(), and IG.Neural.Forms.NeuralTrainingControl.numHiddenNeuron2D_ValueChanged().
btLoadANN2D
System.Windows.Forms.Button IG.Neural.Forms.NeuralTrainingControl.btLoadANN2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralTrainingControl.btStart2D_Click(), and IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
btSaveANN2D
System.Windows.Forms.Button IG.Neural.Forms.NeuralTrainingControl.btSaveANN2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralTrainingControl.btStart2D_Click(), and IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
btReset2D
System.Windows.Forms.Button IG.Neural.Forms.NeuralTrainingControl.btReset2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralTrainingControl.btStart2D_Click(), and IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
btStart2D
System.Windows.Forms.Button IG.Neural.Forms.NeuralTrainingControl.btStart2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralTrainingControl.btnGenerateOptData2D_Click(), IG.Neural.Forms.NeuralTrainingControl.btStart2D_Click(), IG.Neural.Forms.NeuralTrainingControl.InitializeComponent(), and IG.Neural.Forms.NeuralTrainingControl.ResetAll2D().
numOutputSafety2D
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralTrainingControl.numOutputSafety2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent(), and IG.Neural.Forms.NeuralTrainingControl.numOutputSafety2D_ValueChanged().
label17
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label17 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
numInputSafety2D
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralTrainingControl.numInputSafety2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent(), and IG.Neural.Forms.NeuralTrainingControl.numInputSafety2D_ValueChanged().
label18
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label18 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
label20
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label20 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
numMomentum2D
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralTrainingControl.numMomentum2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent(), and IG.Neural.Forms.NeuralTrainingControl.numMomentum2D_ValueChanged().
numLearningRate2D
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralTrainingControl.numLearningRate2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent(), and IG.Neural.Forms.NeuralTrainingControl.numLearningRate2D_ValueChanged().
numRMS2D
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralTrainingControl.numRMS2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent(), and IG.Neural.Forms.NeuralTrainingControl.numRMS2D_ValueChanged().
numEpochBundle2D
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralTrainingControl.numEpochBundle2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent(), and IG.Neural.Forms.NeuralTrainingControl.numEpochBundle2D_ValueChanged().
numMaxEpoch2D
System.Windows.Forms.NumericUpDown IG.Neural.Forms.NeuralTrainingControl.numMaxEpoch2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent(), and IG.Neural.Forms.NeuralTrainingControl.numMaxEpoch2D_ValueChanged().
label21
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label21 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
label22
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label22 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
label23
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label23 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
label24
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label24 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
label25
System.Windows.Forms.Label IG.Neural.Forms.NeuralTrainingControl.label25 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
btLoad2D
System.Windows.Forms.Button IG.Neural.Forms.NeuralTrainingControl.btLoad2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
groupBox1
System.Windows.Forms.GroupBox IG.Neural.Forms.NeuralTrainingControl.groupBox1 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
groupBox2
System.Windows.Forms.GroupBox IG.Neural.Forms.NeuralTrainingControl.groupBox2 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
groupBox4
System.Windows.Forms.GroupBox IG.Neural.Forms.NeuralTrainingControl.groupBox4 private
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
btStop2D
System.Windows.Forms.Button IG.Neural.Forms.NeuralTrainingControl.btStop2D private
Referenced by IG.Neural.Forms.NeuralTrainingControl.backgroundWorker2D_RunWorkerCompleted(), IG.Neural.Forms.NeuralTrainingControl.btStart2D_Click(), and IG.Neural.Forms.NeuralTrainingControl.InitializeComponent().
backgroundWorker2D
System.ComponentModel.BackgroundWorker IG.Neural.Forms.NeuralTrainingControl.backgroundWorker2D
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeComponent(), and IG.Neural.Forms.NeuralTrainingControl.TrainNetworkThread2D().
Property Documentation
NeuralModel
INeuralModel IG.Neural.Forms.NeuralTrainingControl.NeuralModel get protected set
Neural network - based model.
Contains data definition and trained neural network approximator.
Referenced by IG.Neural.Forms.NeuralTrainingControl.SetNeuralModel().
TrainedNetwork
INeuralApproximator IG.Neural.Forms.NeuralTrainingControl.TrainedNetwork get
Traint artificial neural network.
NeuralDataDefinition
InputOutputDataDefiniton IG.Neural.Forms.NeuralTrainingControl.NeuralDataDefinition get
Neural data definition.
network2D
INeuralApproximator IG.Neural.Forms.NeuralTrainingControl.network2D get
Traint artificial neural network.
Referenced by IG.Neural.Forms.NeuralTrainingControl.backgroundWorker2D_DoWork(), IG.Neural.Forms.NeuralTrainingControl.btStart2D_Click(), and IG.Neural.Forms.NeuralTrainingControl.btStop2D_Click().
NeuralApproximator
virtual INeuralApproximator IG.Neural.Forms.NeuralTrainingControl.NeuralApproximator get set
Neural approximator.
Referenced by IG.Neural.Forms.NeuralTrainingControl.InitializeApproximator2D(), IG.Neural.Forms.NeuralTrainingControl.rbMaxTrainError2D_CheckedChanged(), IG.Neural.Forms.NeuralTrainingControl.rbMaxVerError2D_CheckedChanged(), IG.Neural.Forms.NeuralTrainingControl.rbRmsTrainError2D_CheckedChanged(), IG.Neural.Forms.NeuralTrainingControl.rbRmsVerError2D_CheckedChanged(), and IG.Neural.Forms.NeuralTrainingControl.WriteErrors2D().
ScaledBounds
BoundingBox3d IG.Neural.Forms.NeuralTrainingControl.ScaledBounds get protected
The documentation for this class was generated from the following files:
shelldev/extensions/ExtAppAnnApp/ResponseForms/TestingStage/Training/NeuralTrainingControl.cs
shelldev/extensions/ExtAppAnnApp/ResponseForms/TestingStage/Training/NeuralTrainingControl.Designer.cs