Doc: IGLib EXTENDED: NUnit.Framework.Constraints.EqualityComparerTests Class Reference
NUnit.Framework.Constraints.EqualityComparerTests Class Reference
Public Member Functions
void Setup ()
void EqualItems (object x, object y)
void UnequalItems (object greater, object lesser)
void SpecialFloatingPointValuesCompareAsEqual (object x, object y)
void SameDirectoriesAreEqual ()
void DifferentDirectoriesAreNotEqual ()
void CanCompareArrayContainingSelfToSelf ()
void IEquatableSuccess ()
void IEquatableDifferentTypesSuccess_WhenActualImplementsIEquatable ()
void IEquatableDifferentTypesSuccess_WhenExpectedImplementsIEquatable ()
void ReferenceEqualityHasPrecedenceOverIEquatable ()
void IEquatableHasPrecedenceOverDefaultEquals ()
void ImplementingIEquatableDirectlyOnTheClass ()
void ImplementingIEquatableOnABaseClassOrInterface ()
void ImplementingIEquatableOnABaseClassOrInterfaceThroughInterface ()
void CanHandleMultipleImplementationsOfIEquatable ()
void IEnumeratorIsDisposed ()
Private Attributes
Tolerance tolerance
NUnitEqualityComparer comparer
Member Function Documentation
Setup()
void NUnit.Framework.Constraints.EqualityComparerTests.Setup () inline
References NUnit.Framework.Constraints.EqualityComparerTests.comparer, NUnit.Framework.Constraints.Tolerance.Default, and NUnit.Framework.Constraints.EqualityComparerTests.tolerance.
EqualItems()
void NUnit.Framework.Constraints.EqualityComparerTests.EqualItems (object x, object y) inline
References NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(), NUnit.Framework.Constraints.EqualityComparerTests.comparer, NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.EqualityComparerTests.tolerance.
UnequalItems()
void NUnit.Framework.Constraints.EqualityComparerTests.UnequalItems (object greater, object lesser) inline
References NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(), NUnit.Framework.Constraints.EqualityComparerTests.comparer, NUnit.Framework.Assert.False(), and NUnit.Framework.Constraints.EqualityComparerTests.tolerance.
SpecialFloatingPointValuesCompareAsEqual()
void NUnit.Framework.Constraints.EqualityComparerTests.SpecialFloatingPointValuesCompareAsEqual (object x, object y) inline
References NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(), NUnit.Framework.Constraints.EqualityComparerTests.comparer, NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.EqualityComparerTests.tolerance.
SameDirectoriesAreEqual()
void NUnit.Framework.Constraints.EqualityComparerTests.SameDirectoriesAreEqual () inline
References NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(), NUnit.Framework.Constraints.EqualityComparerTests.comparer, NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.EqualityComparerTests.tolerance.
DifferentDirectoriesAreNotEqual()
void NUnit.Framework.Constraints.EqualityComparerTests.DifferentDirectoriesAreNotEqual () inline
References NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(), NUnit.Framework.Constraints.EqualityComparerTests.comparer, NUnit.Framework.Is.False, NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.EqualityComparerTests.tolerance.
CanCompareArrayContainingSelfToSelf()
void NUnit.Framework.Constraints.EqualityComparerTests.CanCompareArrayContainingSelfToSelf () inline
References NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(), NUnit.Framework.Constraints.EqualityComparerTests.comparer, NUnit.Framework.Constraints.EqualityComparerTests.tolerance, and NUnit.Framework.Assert.True().
IEquatableSuccess()
void NUnit.Framework.Constraints.EqualityComparerTests.IEquatableSuccess () inline
References NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(), NUnit.Framework.Constraints.EqualityComparerTests.comparer, NUnit.Framework.Assert.IsTrue(), and NUnit.Framework.Constraints.EqualityComparerTests.tolerance.
IEquatableDifferentTypesSuccess_WhenActualImplementsIEquatable()
void NUnit.Framework.Constraints.EqualityComparerTests.IEquatableDifferentTypesSuccess_WhenActualImplementsIEquatable () inline
References NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(), NUnit.Framework.Constraints.EqualityComparerTests.comparer, NUnit.Framework.Assert.IsTrue(), and NUnit.Framework.Constraints.EqualityComparerTests.tolerance.
IEquatableDifferentTypesSuccess_WhenExpectedImplementsIEquatable()
void NUnit.Framework.Constraints.EqualityComparerTests.IEquatableDifferentTypesSuccess_WhenExpectedImplementsIEquatable () inline
References NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(), NUnit.Framework.Constraints.EqualityComparerTests.comparer, NUnit.Framework.Assert.IsTrue(), and NUnit.Framework.Constraints.EqualityComparerTests.tolerance.
ReferenceEqualityHasPrecedenceOverIEquatable()
void NUnit.Framework.Constraints.EqualityComparerTests.ReferenceEqualityHasPrecedenceOverIEquatable () inline
References NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(), NUnit.Framework.Constraints.EqualityComparerTests.comparer, NUnit.Framework.Assert.IsTrue(), and NUnit.Framework.Constraints.EqualityComparerTests.tolerance.
IEquatableHasPrecedenceOverDefaultEquals()
void NUnit.Framework.Constraints.EqualityComparerTests.IEquatableHasPrecedenceOverDefaultEquals () inline
References NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(), NUnit.Framework.Constraints.EqualityComparerTests.comparer, NUnit.Framework.Assert.IsFalse(), and NUnit.Framework.Constraints.EqualityComparerTests.tolerance.
ImplementingIEquatableDirectlyOnTheClass()
void NUnit.Framework.Constraints.EqualityComparerTests.ImplementingIEquatableDirectlyOnTheClass () inline
References NUnit.Framework.Constraints.Tolerance.Exact, NUnit.Framework.Assert.That(), NUnit.Framework.Constraints.EqualityComparerTests.tolerance, and NUnit.Framework.Is.True.
ImplementingIEquatableOnABaseClassOrInterface()
void NUnit.Framework.Constraints.EqualityComparerTests.ImplementingIEquatableOnABaseClassOrInterface () inline
References NUnit.Framework.Constraints.Tolerance.Exact, NUnit.Framework.Assert.That(), NUnit.Framework.Constraints.EqualityComparerTests.tolerance, and NUnit.Framework.Is.True.
ImplementingIEquatableOnABaseClassOrInterfaceThroughInterface()
void NUnit.Framework.Constraints.EqualityComparerTests.ImplementingIEquatableOnABaseClassOrInterfaceThroughInterface () inline
References NUnit.Framework.Constraints.Tolerance.Exact, NUnit.Framework.Assert.That(), NUnit.Framework.Constraints.EqualityComparerTests.tolerance, and NUnit.Framework.Is.True.
CanHandleMultipleImplementationsOfIEquatable()
void NUnit.Framework.Constraints.EqualityComparerTests.CanHandleMultipleImplementationsOfIEquatable () inline
References NUnit.Framework.Constraints.Tolerance.Exact, NUnit.Framework.Is.False, NUnit.Framework.Assert.That(), NUnit.Framework.Constraints.EqualityComparerTests.tolerance, and NUnit.Framework.Is.True.
IEnumeratorIsDisposed()
void NUnit.Framework.Constraints.EqualityComparerTests.IEnumeratorIsDisposed () inline
References NUnit.Framework.Constraints.NUnitEqualityComparer.AreEqual(), NUnit.Framework.Constraints.EqualityComparerTests.comparer, NUnit.Framework.Assert.That(), NUnit.Framework.Constraints.EqualityComparerTests.tolerance, and NUnit.Framework.Assert.True().
Member Data Documentation
tolerance
Tolerance NUnit.Framework.Constraints.EqualityComparerTests.tolerance private
Referenced by NUnit.Framework.Constraints.EqualityComparerTests.CanCompareArrayContainingSelfToSelf(), NUnit.Framework.Constraints.EqualityComparerTests.CanHandleMultipleImplementationsOfIEquatable(), NUnit.Framework.Constraints.EqualityComparerTests.DifferentDirectoriesAreNotEqual(), NUnit.Framework.Constraints.EqualityComparerTests.EqualItems(), NUnit.Framework.Constraints.EqualityComparerTests.IEnumeratorIsDisposed(), NUnit.Framework.Constraints.EqualityComparerTests.IEquatableDifferentTypesSuccess_WhenActualImplementsIEquatable(), NUnit.Framework.Constraints.EqualityComparerTests.IEquatableDifferentTypesSuccess_WhenExpectedImplementsIEquatable(), NUnit.Framework.Constraints.EqualityComparerTests.IEquatableHasPrecedenceOverDefaultEquals(), NUnit.Framework.Constraints.EqualityComparerTests.IEquatableSuccess(), NUnit.Framework.Constraints.EqualityComparerTests.ImplementingIEquatableDirectlyOnTheClass(), NUnit.Framework.Constraints.EqualityComparerTests.ImplementingIEquatableOnABaseClassOrInterface(), NUnit.Framework.Constraints.EqualityComparerTests.ImplementingIEquatableOnABaseClassOrInterfaceThroughInterface(), NUnit.Framework.Constraints.EqualityComparerTests.ReferenceEqualityHasPrecedenceOverIEquatable(), NUnit.Framework.Constraints.EqualityComparerTests.SameDirectoriesAreEqual(), NUnit.Framework.Constraints.EqualityComparerTests.Setup(), NUnit.Framework.Constraints.EqualityComparerTests.SpecialFloatingPointValuesCompareAsEqual(), and NUnit.Framework.Constraints.EqualityComparerTests.UnequalItems().
comparer
NUnitEqualityComparer NUnit.Framework.Constraints.EqualityComparerTests.comparer private
Referenced by NUnit.Framework.Constraints.EqualityComparerTests.CanCompareArrayContainingSelfToSelf(), NUnit.Framework.Constraints.EqualityComparerTests.DifferentDirectoriesAreNotEqual(), NUnit.Framework.Constraints.EqualityComparerTests.EqualItems(), NUnit.Framework.Constraints.EqualityComparerTests.IEnumeratorIsDisposed(), NUnit.Framework.Constraints.EqualityComparerTests.IEquatableDifferentTypesSuccess_WhenActualImplementsIEquatable(), NUnit.Framework.Constraints.EqualityComparerTests.IEquatableDifferentTypesSuccess_WhenExpectedImplementsIEquatable(), NUnit.Framework.Constraints.EqualityComparerTests.IEquatableHasPrecedenceOverDefaultEquals(), NUnit.Framework.Constraints.EqualityComparerTests.IEquatableSuccess(), NUnit.Framework.Constraints.EqualityComparerTests.ReferenceEqualityHasPrecedenceOverIEquatable(), NUnit.Framework.Constraints.EqualityComparerTests.SameDirectoriesAreEqual(), NUnit.Framework.Constraints.EqualityComparerTests.Setup(), NUnit.Framework.Constraints.EqualityComparerTests.SpecialFloatingPointValuesCompareAsEqual(), and NUnit.Framework.Constraints.EqualityComparerTests.UnequalItems().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/NUnitEqualityComparerTests.cs