Doc: IGLib EXTENDED: AForge.Fuzzy.Rulebase Class Reference
AForge.Fuzzy.Rulebase Class Reference
The class represents a fuzzy rulebase, a set of fuzzy rules used in a Fuzzy Inference System.
Public Member Functions
Rulebase ()
Initializes a new instance of the Rulebase class.
void AddRule (Rule rule)
Adds a fuzzy rule to the database.
void ClearRules ()
Removes all the fuzzy rules of the database.
Rule GetRule (string ruleName)
Returns an existing fuzzy rule from the rulebase.
Rule[] GetRules ()
Gets all the rules of the rulebase.
Private Attributes
Dictionary< string, Rule > rules
Detailed Description
The class represents a fuzzy rulebase, a set of fuzzy rules used in a Fuzzy Inference System.
Constructor & Destructor Documentation
Rulebase()
AForge.Fuzzy.Rulebase.Rulebase () inline
Initializes a new instance of the Rulebase class.
Member Function Documentation
AddRule()
void AForge.Fuzzy.Rulebase.AddRule (Rule rule) inline
Adds a fuzzy rule to the database.
Parameters
rule A fuzzy Rule to add to the database.
Exceptions
NullReferenceException The fuzzy rule was not initialized.
ArgumentException The fuzzy rule name already exists in the rulebase.
References AForge.Fuzzy.Rule.Name.
Referenced by AForge.Fuzzy.InferenceSystem.NewRule().
ClearRules()
void AForge.Fuzzy.Rulebase.ClearRules () inline
Removes all the fuzzy rules of the database.
GetRule()
Rule AForge.Fuzzy.Rulebase.GetRule (string ruleName) inline
Returns an existing fuzzy rule from the rulebase.
Parameters
ruleName Name of the fuzzy Rule to retrieve.
Returns
Reference to named Rule.
Exceptions
KeyNotFoundException The rule indicated in ruleName was not found in the rulebase.
References AForge.Fuzzy.Rulebase.rules.
Referenced by AForge.Fuzzy.InferenceSystem.GetRule().
GetRules()
Rule [] AForge.Fuzzy.Rulebase.GetRules () inline
Gets all the rules of the rulebase.
Returns
An array with all the rulebase rules.
References AForge.Fuzzy.Rulebase.rules.
Referenced by AForge.Fuzzy.InferenceSystem.ExecuteInference().
Member Data Documentation
rules
Dictionary<string, Rule> AForge.Fuzzy.Rulebase.rules private
Referenced by AForge.Fuzzy.Rulebase.GetRule(), and AForge.Fuzzy.Rulebase.GetRules().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Fuzzy/Rulebase.cs