Doc: IGLib EXTENDED: alglib.testdensesolverunit Class Reference
alglib.testdensesolverunit Class Reference
Static Public Member Functions
static bool testdensesolver (bool silent)
static bool testdensesolver (bool silent)
static bool _pexec_testdensesolver (bool silent)
Static Private Member Functions
static bool rmatrixchecksolutionm (double[,] xe, int n, int m, double threshold, int info, densesolver.densesolverreport rep, double[,] xs)
static bool rmatrixchecksolution (double[,] xe, int n, double threshold, int info, densesolver.densesolverreport rep, double[] xs)
static bool rmatrixchecksingularm (int n, int m, int info, densesolver.densesolverreport rep, double[,] xs)
static bool rmatrixchecksingular (int n, int info, densesolver.densesolverreport rep, double[] xs)
static bool cmatrixchecksolutionm (complex[,] xe, int n, int m, double threshold, int info, densesolver.densesolverreport rep, complex[,] xs)
static bool cmatrixchecksolution (complex[,] xe, int n, double threshold, int info, densesolver.densesolverreport rep, complex[] xs)
static bool cmatrixchecksingularm (int n, int m, int info, densesolver.densesolverreport rep, complex[,] xs)
static bool cmatrixchecksingular (int n, int info, densesolver.densesolverreport rep, complex[] xs)
static void rmatrixmakeacopy (double[,] a, int m, int n, ref double[,] b)
static void cmatrixmakeacopy (complex[,] a, int m, int n, ref complex[,] b)
static void rmatrixdrophalf (ref double[,] a, int n, bool droplower)
static void cmatrixdrophalf (ref complex[,] a, int n, bool droplower)
static void testrsolver (int maxn, int maxm, int passcount, double threshold, ref bool rerrors, ref bool rfserrors)
static void testspdsolver (int maxn, int maxm, int passcount, double threshold, ref bool spderrors, ref bool rfserrors)
static void testcsolver (int maxn, int maxm, int passcount, double threshold, ref bool cerrors, ref bool rfserrors)
static void testhpdsolver (int maxn, int maxm, int passcount, double threshold, ref bool hpderrors, ref bool rfserrors)
static void unset2d (ref double[,] x)
static void unset1d (ref double[] x)
static void cunset2d (ref complex[,] x)
static void cunset1d (ref complex[] x)
static void unsetrep (densesolver.densesolverreport r)
static void unsetlsrep (densesolver.densesolverlsreport r)
static bool rmatrixchecksolutionm (double[,] xe, int n, int m, double threshold, int info, densesolver.densesolverreport rep, double[,] xs)
static bool rmatrixchecksolution (double[,] xe, int n, double threshold, int info, densesolver.densesolverreport rep, double[] xs)
static bool rmatrixchecksingularm (int n, int m, int info, densesolver.densesolverreport rep, double[,] xs)
static bool rmatrixchecksingular (int n, int info, densesolver.densesolverreport rep, double[] xs)
static bool cmatrixchecksolutionm (complex[,] xe, int n, int m, double threshold, int info, densesolver.densesolverreport rep, complex[,] xs)
static bool cmatrixchecksolution (complex[,] xe, int n, double threshold, int info, densesolver.densesolverreport rep, complex[] xs)
static bool cmatrixchecksingularm (int n, int m, int info, densesolver.densesolverreport rep, complex[,] xs)
static bool cmatrixchecksingular (int n, int info, densesolver.densesolverreport rep, complex[] xs)
static void rmatrixmakeacopy (double[,] a, int m, int n, ref double[,] b)
static void cmatrixmakeacopy (complex[,] a, int m, int n, ref complex[,] b)
static void rmatrixdrophalf (ref double[,] a, int n, bool droplower)
static void cmatrixdrophalf (ref complex[,] a, int n, bool droplower)
static void testrsolver (int maxn, int maxm, int passcount, double threshold, ref bool rerrors, ref bool rfserrors)
static void testspdsolver (int maxn, int maxm, int passcount, double threshold, ref bool spderrors, ref bool rfserrors)
static void testcsolver (int maxn, int maxm, int passcount, double threshold, ref bool cerrors, ref bool rfserrors)
static void testhpdsolver (int maxn, int maxm, int passcount, double threshold, ref bool hpderrors, ref bool rfserrors)
static void unset2d (ref double[,] x)
static void unset1d (ref double[] x)
static void cunset2d (ref complex[,] x)
static void cunset1d (ref complex[] x)
static void unsetrep (densesolver.densesolverreport r)
static void unsetlsrep (densesolver.densesolverlsreport r)
Member Function Documentation
testdensesolver() [1/2]
static bool alglib.testdensesolverunit.testdensesolver (bool silent) inline static
References alglib.math.machineepsilon, alglib.testdensesolverunit.testcsolver(), alglib.testdensesolverunit.testhpdsolver(), alglib.testdensesolverunit.testrsolver(), and alglib.testdensesolverunit.testspdsolver().
Referenced by alglib.testdensesolverunit._pexec_testdensesolver(), and _Test.Main().
rmatrixchecksolutionm() [1/2]
static bool alglib.testdensesolverunit.rmatrixchecksolutionm (double xe[,], int n, int m, double threshold, int info, densesolver.densesolverreport rep, double xs[,]) inline static private
References alglib.math.machineepsilon.
Referenced by alglib.testdensesolverunit.rmatrixchecksolution(), alglib.testdensesolverunit.testrsolver(), and alglib.testdensesolverunit.testspdsolver().
rmatrixchecksolution() [1/2]
static bool alglib.testdensesolverunit.rmatrixchecksolution (double xe[,], int n, double threshold, int info, densesolver.densesolverreport rep, double[] xs) inline static private
References alglib.testdensesolverunit.rmatrixchecksolutionm().
Referenced by alglib.testdensesolverunit.testrsolver(), and alglib.testdensesolverunit.testspdsolver().
rmatrixchecksingularm() [1/2]
static bool alglib.testdensesolverunit.rmatrixchecksingularm (int n, int m, int info, densesolver.densesolverreport rep, double xs[,]) inline static private
References alglib.math.machineepsilon.
Referenced by alglib.testdensesolverunit.rmatrixchecksingular(), alglib.testdensesolverunit.testrsolver(), and alglib.testdensesolverunit.testspdsolver().
rmatrixchecksingular() [1/2]
static bool alglib.testdensesolverunit.rmatrixchecksingular (int n, int info, densesolver.densesolverreport rep, double[] xs) inline static private
References alglib.testdensesolverunit.rmatrixchecksingularm().
Referenced by alglib.testdensesolverunit.testrsolver(), and alglib.testdensesolverunit.testspdsolver().
cmatrixchecksolutionm() [1/2]
static bool alglib.testdensesolverunit.cmatrixchecksolutionm (complex xe[,], int n, int m, double threshold, int info, densesolver.densesolverreport rep, complex xs[,]) inline static private
References alglib.math.abscomplex(), and alglib.math.machineepsilon.
Referenced by alglib.testdensesolverunit.cmatrixchecksolution(), alglib.testdensesolverunit.testcsolver(), and alglib.testdensesolverunit.testhpdsolver().
cmatrixchecksolution() [1/2]
static bool alglib.testdensesolverunit.cmatrixchecksolution (complex xe[,], int n, double threshold, int info, densesolver.densesolverreport rep, complex[] xs) inline static private
References alglib.testdensesolverunit.cmatrixchecksolutionm().
Referenced by alglib.testdensesolverunit.testcsolver(), and alglib.testdensesolverunit.testhpdsolver().
cmatrixchecksingularm() [1/2]
static bool alglib.testdensesolverunit.cmatrixchecksingularm (int n, int m, int info, densesolver.densesolverreport rep, complex xs[,]) inline static private
References alglib.math.machineepsilon.
Referenced by alglib.testdensesolverunit.cmatrixchecksingular(), alglib.testdensesolverunit.testcsolver(), and alglib.testdensesolverunit.testhpdsolver().
cmatrixchecksingular() [1/2]
static bool alglib.testdensesolverunit.cmatrixchecksingular (int n, int info, densesolver.densesolverreport rep, complex[] xs) inline static private
References alglib.testdensesolverunit.cmatrixchecksingularm().
Referenced by alglib.testdensesolverunit.testcsolver(), and alglib.testdensesolverunit.testhpdsolver().
rmatrixmakeacopy() [1/2]
static void alglib.testdensesolverunit.rmatrixmakeacopy (double a[,], int m, int n, ref double b[,]) inline static private
Referenced by alglib.testdensesolverunit.testrsolver(), and alglib.testdensesolverunit.testspdsolver().
cmatrixmakeacopy() [1/2]
static void alglib.testdensesolverunit.cmatrixmakeacopy (complex a[,], int m, int n, ref complex b[,]) inline static private
Referenced by alglib.testdensesolverunit.testcsolver(), and alglib.testdensesolverunit.testhpdsolver().
rmatrixdrophalf() [1/2]
static void alglib.testdensesolverunit.rmatrixdrophalf (ref double a[,], int n, bool droplower) inline static private
Referenced by alglib.testdensesolverunit.testspdsolver().
cmatrixdrophalf() [1/2]
static void alglib.testdensesolverunit.cmatrixdrophalf (ref complex a[,], int n, bool droplower) inline static private
Referenced by alglib.testdensesolverunit.testhpdsolver().
testrsolver() [1/2]
static void alglib.testdensesolverunit.testrsolver (int maxn, int maxm, int passcount, double threshold, ref bool rerrors, ref bool rfserrors) inline static private
References alglib.blas.copymatrix(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testdensesolverunit.rmatrixchecksingular(), alglib.testdensesolverunit.rmatrixchecksingularm(), alglib.testdensesolverunit.rmatrixchecksolution(), alglib.testdensesolverunit.rmatrixchecksolutionm(), alglib.trfac.rmatrixlu(), alglib.densesolver.rmatrixlusolve(), alglib.densesolver.rmatrixlusolvem(), alglib.testdensesolverunit.rmatrixmakeacopy(), alglib.densesolver.rmatrixmixedsolve(), alglib.densesolver.rmatrixmixedsolvem(), alglib.matgen.rmatrixrndcond(), alglib.densesolver.rmatrixsolve(), alglib.densesolver.rmatrixsolvels(), alglib.densesolver.rmatrixsolvem(), alglib.testdensesolverunit.unset1d(), alglib.testdensesolverunit.unset2d(), alglib.testdensesolverunit.unsetlsrep(), alglib.testdensesolverunit.unsetrep(), and alglib.xblas.xdot().
Referenced by alglib.testdensesolverunit.testdensesolver().
testspdsolver() [1/2]
static void alglib.testdensesolverunit.testspdsolver (int maxn, int maxm, int passcount, double threshold, ref bool spderrors, ref bool rfserrors) inline static private
References alglib.math.randominteger(), alglib.math.randomreal(), alglib.testdensesolverunit.rmatrixchecksingular(), alglib.testdensesolverunit.rmatrixchecksingularm(), alglib.testdensesolverunit.rmatrixchecksolution(), alglib.testdensesolverunit.rmatrixchecksolutionm(), alglib.testdensesolverunit.rmatrixdrophalf(), alglib.testdensesolverunit.rmatrixmakeacopy(), alglib.trfac.spdmatrixcholesky(), alglib.densesolver.spdmatrixcholeskysolve(), alglib.densesolver.spdmatrixcholeskysolvem(), alglib.matgen.spdmatrixrndcond(), alglib.densesolver.spdmatrixsolve(), alglib.densesolver.spdmatrixsolvem(), alglib.testdensesolverunit.unset1d(), alglib.testdensesolverunit.unset2d(), and alglib.testdensesolverunit.unsetrep().
Referenced by alglib.testdensesolverunit.testdensesolver().
testcsolver() [1/2]
static void alglib.testdensesolverunit.testcsolver (int maxn, int maxm, int passcount, double threshold, ref bool cerrors, ref bool rfserrors) inline static private
References alglib.math.abscomplex(), alglib.testdensesolverunit.cmatrixchecksingular(), alglib.testdensesolverunit.cmatrixchecksingularm(), alglib.testdensesolverunit.cmatrixchecksolution(), alglib.testdensesolverunit.cmatrixchecksolutionm(), alglib.trfac.cmatrixlu(), alglib.densesolver.cmatrixlusolve(), alglib.densesolver.cmatrixlusolvem(), alglib.testdensesolverunit.cmatrixmakeacopy(), alglib.densesolver.cmatrixmixedsolve(), alglib.densesolver.cmatrixmixedsolvem(), alglib.matgen.cmatrixrndcond(), alglib.densesolver.cmatrixsolve(), alglib.densesolver.cmatrixsolvem(), alglib.testdensesolverunit.cunset1d(), alglib.testdensesolverunit.cunset2d(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testdensesolverunit.unsetrep(), alglib.complex.x, alglib.xblas.xcdot(), and alglib.complex.y.
Referenced by alglib.testdensesolverunit.testdensesolver().
testhpdsolver() [1/2]
static void alglib.testdensesolverunit.testhpdsolver (int maxn, int maxm, int passcount, double threshold, ref bool hpderrors, ref bool rfserrors) inline static private
References alglib.testdensesolverunit.cmatrixchecksingular(), alglib.testdensesolverunit.cmatrixchecksingularm(), alglib.testdensesolverunit.cmatrixchecksolution(), alglib.testdensesolverunit.cmatrixchecksolutionm(), alglib.testdensesolverunit.cmatrixdrophalf(), alglib.testdensesolverunit.cmatrixmakeacopy(), alglib.testdensesolverunit.cunset1d(), alglib.testdensesolverunit.cunset2d(), alglib.trfac.hpdmatrixcholesky(), alglib.densesolver.hpdmatrixcholeskysolve(), alglib.densesolver.hpdmatrixcholeskysolvem(), alglib.matgen.hpdmatrixrndcond(), alglib.densesolver.hpdmatrixsolve(), alglib.densesolver.hpdmatrixsolvem(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.testdensesolverunit.unsetrep(), alglib.complex.x, and alglib.complex.y.
Referenced by alglib.testdensesolverunit.testdensesolver().
unset2d() [1/2]
static void alglib.testdensesolverunit.unset2d (ref double x[,]) inline static private
References alglib.math.randomreal().
Referenced by alglib.testdensesolverunit.testrsolver(), alglib.testdensesolverunit.testspdsolver(), and alglib.testdensesolverunit.unsetlsrep().
unset1d() [1/2]
static void alglib.testdensesolverunit.unset1d (ref double[] x) inline static private
References alglib.math.randomreal().
Referenced by alglib.testdensesolverunit.testrsolver(), and alglib.testdensesolverunit.testspdsolver().
cunset2d() [1/2]
static void alglib.testdensesolverunit.cunset2d (ref complex x[,]) inline static private
References alglib.math.randomreal().
Referenced by alglib.testdensesolverunit.testcsolver(), and alglib.testdensesolverunit.testhpdsolver().
cunset1d() [1/2]
static void alglib.testdensesolverunit.cunset1d (ref complex[] x) inline static private
References alglib.math.randomreal().
Referenced by alglib.testdensesolverunit.testcsolver(), and alglib.testdensesolverunit.testhpdsolver().
unsetrep() [1/2]
static void alglib.testdensesolverunit.unsetrep (densesolver.densesolverreport r) inline static private
Referenced by alglib.testdensesolverunit.testcsolver(), alglib.testdensesolverunit.testhpdsolver(), alglib.testdensesolverunit.testrsolver(), and alglib.testdensesolverunit.testspdsolver().
unsetlsrep() [1/2]
static void alglib.testdensesolverunit.unsetlsrep (densesolver.densesolverlsreport r) inline static private
References alglib.testdensesolverunit.unset2d().
Referenced by alglib.testdensesolverunit.testrsolver().
testdensesolver() [2/2]
static bool alglib.testdensesolverunit.testdensesolver (bool silent) inline static
References alglib.math.machineepsilon, alglib.testdensesolverunit.testcsolver(), alglib.testdensesolverunit.testhpdsolver(), alglib.testdensesolverunit.testrsolver(), and alglib.testdensesolverunit.testspdsolver().
_pexec_testdensesolver()
static bool alglib.testdensesolverunit._pexec_testdensesolver (bool silent) inline static
References alglib.testdensesolverunit.testdensesolver().
Referenced by _Test.Main().
rmatrixchecksolutionm() [2/2]
static bool alglib.testdensesolverunit.rmatrixchecksolutionm (double xe[,], int n, int m, double threshold, int info, densesolver.densesolverreport rep, double xs[,]) inline static private
References alglib.math.machineepsilon.
rmatrixchecksolution() [2/2]
static bool alglib.testdensesolverunit.rmatrixchecksolution (double xe[,], int n, double threshold, int info, densesolver.densesolverreport rep, double[] xs) inline static private
References alglib.testdensesolverunit.rmatrixchecksolutionm().
rmatrixchecksingularm() [2/2]
static bool alglib.testdensesolverunit.rmatrixchecksingularm (int n, int m, int info, densesolver.densesolverreport rep, double xs[,]) inline static private
References alglib.math.machineepsilon.
rmatrixchecksingular() [2/2]
static bool alglib.testdensesolverunit.rmatrixchecksingular (int n, int info, densesolver.densesolverreport rep, double[] xs) inline static private
References alglib.testdensesolverunit.rmatrixchecksingularm().
cmatrixchecksolutionm() [2/2]
static bool alglib.testdensesolverunit.cmatrixchecksolutionm (complex xe[,], int n, int m, double threshold, int info, densesolver.densesolverreport rep, complex xs[,]) inline static private
References alglib.math.abscomplex(), and alglib.math.machineepsilon.
cmatrixchecksolution() [2/2]
static bool alglib.testdensesolverunit.cmatrixchecksolution (complex xe[,], int n, double threshold, int info, densesolver.densesolverreport rep, complex[] xs) inline static private
References alglib.testdensesolverunit.cmatrixchecksolutionm().
cmatrixchecksingularm() [2/2]
static bool alglib.testdensesolverunit.cmatrixchecksingularm (int n, int m, int info, densesolver.densesolverreport rep, complex xs[,]) inline static private
References alglib.math.machineepsilon.
cmatrixchecksingular() [2/2]
static bool alglib.testdensesolverunit.cmatrixchecksingular (int n, int info, densesolver.densesolverreport rep, complex[] xs) inline static private
References alglib.testdensesolverunit.cmatrixchecksingularm().
rmatrixmakeacopy() [2/2]
static void alglib.testdensesolverunit.rmatrixmakeacopy (double a[,], int m, int n, ref double b[,]) inline static private
cmatrixmakeacopy() [2/2]
static void alglib.testdensesolverunit.cmatrixmakeacopy (complex a[,], int m, int n, ref complex b[,]) inline static private
rmatrixdrophalf() [2/2]
static void alglib.testdensesolverunit.rmatrixdrophalf (ref double a[,], int n, bool droplower) inline static private
cmatrixdrophalf() [2/2]
static void alglib.testdensesolverunit.cmatrixdrophalf (ref complex a[,], int n, bool droplower) inline static private
testrsolver() [2/2]
static void alglib.testdensesolverunit.testrsolver (int maxn, int maxm, int passcount, double threshold, ref bool rerrors, ref bool rfserrors) inline static private
References alglib.blas.copymatrix(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testdensesolverunit.rmatrixchecksingular(), alglib.testdensesolverunit.rmatrixchecksingularm(), alglib.testdensesolverunit.rmatrixchecksolution(), alglib.testdensesolverunit.rmatrixchecksolutionm(), alglib.trfac.rmatrixlu(), alglib.densesolver.rmatrixlusolve(), alglib.densesolver.rmatrixlusolvem(), alglib.testdensesolverunit.rmatrixmakeacopy(), alglib.densesolver.rmatrixmixedsolve(), alglib.densesolver.rmatrixmixedsolvem(), alglib.matgen.rmatrixrndcond(), alglib.densesolver.rmatrixsolve(), alglib.densesolver.rmatrixsolvels(), alglib.densesolver.rmatrixsolvem(), alglib.testdensesolverunit.unset1d(), alglib.testdensesolverunit.unset2d(), alglib.testdensesolverunit.unsetlsrep(), alglib.testdensesolverunit.unsetrep(), and alglib.xblas.xdot().
testspdsolver() [2/2]
static void alglib.testdensesolverunit.testspdsolver (int maxn, int maxm, int passcount, double threshold, ref bool spderrors, ref bool rfserrors) inline static private
References alglib.math.randominteger(), alglib.math.randomreal(), alglib.testdensesolverunit.rmatrixchecksingular(), alglib.testdensesolverunit.rmatrixchecksingularm(), alglib.testdensesolverunit.rmatrixchecksolution(), alglib.testdensesolverunit.rmatrixchecksolutionm(), alglib.testdensesolverunit.rmatrixdrophalf(), alglib.testdensesolverunit.rmatrixmakeacopy(), alglib.trfac.spdmatrixcholesky(), alglib.densesolver.spdmatrixcholeskysolve(), alglib.densesolver.spdmatrixcholeskysolvem(), alglib.matgen.spdmatrixrndcond(), alglib.densesolver.spdmatrixsolve(), alglib.densesolver.spdmatrixsolvem(), alglib.testdensesolverunit.unset1d(), alglib.testdensesolverunit.unset2d(), and alglib.testdensesolverunit.unsetrep().
testcsolver() [2/2]
static void alglib.testdensesolverunit.testcsolver (int maxn, int maxm, int passcount, double threshold, ref bool cerrors, ref bool rfserrors) inline static private
References alglib.math.abscomplex(), alglib.testdensesolverunit.cmatrixchecksingular(), alglib.testdensesolverunit.cmatrixchecksingularm(), alglib.testdensesolverunit.cmatrixchecksolution(), alglib.testdensesolverunit.cmatrixchecksolutionm(), alglib.trfac.cmatrixlu(), alglib.densesolver.cmatrixlusolve(), alglib.densesolver.cmatrixlusolvem(), alglib.testdensesolverunit.cmatrixmakeacopy(), alglib.densesolver.cmatrixmixedsolve(), alglib.densesolver.cmatrixmixedsolvem(), alglib.matgen.cmatrixrndcond(), alglib.densesolver.cmatrixsolve(), alglib.densesolver.cmatrixsolvem(), alglib.testdensesolverunit.cunset1d(), alglib.testdensesolverunit.cunset2d(), alglib.math.machineepsilon, alglib.math.randominteger(), alglib.math.randomreal(), alglib.testdensesolverunit.unsetrep(), alglib.complex.x, alglib.xblas.xcdot(), and alglib.complex.y.
testhpdsolver() [2/2]
static void alglib.testdensesolverunit.testhpdsolver (int maxn, int maxm, int passcount, double threshold, ref bool hpderrors, ref bool rfserrors) inline static private
References alglib.testdensesolverunit.cmatrixchecksingular(), alglib.testdensesolverunit.cmatrixchecksingularm(), alglib.testdensesolverunit.cmatrixchecksolution(), alglib.testdensesolverunit.cmatrixchecksolutionm(), alglib.testdensesolverunit.cmatrixdrophalf(), alglib.testdensesolverunit.cmatrixmakeacopy(), alglib.testdensesolverunit.cunset1d(), alglib.testdensesolverunit.cunset2d(), alglib.trfac.hpdmatrixcholesky(), alglib.densesolver.hpdmatrixcholeskysolve(), alglib.densesolver.hpdmatrixcholeskysolvem(), alglib.matgen.hpdmatrixrndcond(), alglib.densesolver.hpdmatrixsolve(), alglib.densesolver.hpdmatrixsolvem(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.testdensesolverunit.unsetrep(), alglib.complex.x, and alglib.complex.y.
unset2d() [2/2]
static void alglib.testdensesolverunit.unset2d (ref double x[,]) inline static private
References alglib.math.randomreal().
unset1d() [2/2]
static void alglib.testdensesolverunit.unset1d (ref double[] x) inline static private
References alglib.math.randomreal().
cunset2d() [2/2]
static void alglib.testdensesolverunit.cunset2d (ref complex x[,]) inline static private
References alglib.math.randomreal().
cunset1d() [2/2]
static void alglib.testdensesolverunit.cunset1d (ref complex[] x) inline static private
References alglib.math.randomreal().
unsetrep() [2/2]
static void alglib.testdensesolverunit.unsetrep (densesolver.densesolverreport r) inline static private
unsetlsrep() [2/2]
static void alglib.testdensesolverunit.unsetlsrep (densesolver.densesolverlsreport r) inline static private
References alglib.testdensesolverunit.unset2d().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs