Doc: IGLib EXTENDED: IG.Forms.HashControl Class Reference
IG.Forms.HashControl Class Reference
A control used to calculate various checksums of selected files or inserted text.
Classes
class HashJobArgumentsAndResults
Used to carry arguments and results to background jobs of calculating hash values.
Public Member Functions
HashControl ()
void FadingMessageInfo (string message, int showTimeMs=0)
void FadingMessageWarning (string message, int showTimeMs=0)
void FadingMessageError (string message, int showTimeMs=0)
void ReportError (string errorMessage)
void ReportWarning (string warningMessage)
void ReportInfo (string message)
void KeyUpHandler (object sender, KeyEventArgs e)
Handles key up events for the current form.
HashControl ()
void ReportError (string errorMessage)
void ReportWarning (string warningMessage)
void ReportInfo (string message)
HashControl ()
void FadingMessageInfo (string message, int showTimeMs=0)
void FadingMessageWarning (string message, int showTimeMs=0)
void FadingMessageError (string message, int showTimeMs=0)
void ReportError (string errorMessage)
void ReportWarning (string warningMessage)
void ReportInfo (string message)
void KeyUpHandler (object sender, KeyEventArgs e)
Handles key up events for the current form.
HashControl ()
void FadingMessageInfo (string message, int showTimeMs=0)
void FadingMessageWarning (string message, int showTimeMs=0)
void FadingMessageError (string message, int showTimeMs=0)
void ReportError (string errorMessage)
void ReportWarning (string warningMessage)
void ReportInfo (string message)
void KeyUpHandler (object sender, KeyEventArgs e)
Handles key up events for the current form.
Protected Member Functions
void SetGeneralProperties (FadingMessage fmsg)
void ClearHashes ()
Clears all text fields with calculated hash values.
void DisableActionButtons ()
void EnableActionButtons ()
void CalculateHashAsync (HashType hashType)
void LoopWhileBusy ()
long GetFileOrTextLength ()
void CancelHashCalculations ()
void CalculateHashes ()
Re-calculates all hashes that are checked for calculation.
void SaveHashesToFile ()
void BrowseFile ()
Browses for the file to be hashed.
void GenerateFilePreview ()
Generates file preview in the text preview box if the rbFile is checked.
void VerifyHash ()
void Handle_CtrlA_CtrlBackspace (TextBox textBox, object sender, KeyEventArgs e)
Handle the Ctrl-A (select all) and Ctrl-Backspace events for the specified text box.
override void Dispose (bool disposing)
Clean up any resources being used.
void ClearHashes ()
Clears all text fields with calculated hash values.
void CalculateHashes ()
void SaveHashesToFile ()
void BrowseFile ()
Browses for the file to be hashed.
void GenerateFilePreview ()
Generates file preview in the text preview box if the rbFile is checked.
void VerifyHash ()
void Handle_CtrlA_CtrlBackspace (TextBox textBox, object sender, KeyEventArgs e)
Handle the Ctrl-A (select all) and Ctrl-Backspace events for the specified text box.
override void Dispose (bool disposing)
Clean up any resources being used.
void SetGeneralProperties (FadingMessage fmsg)
void ClearHashes ()
Clears all text fields with calculated hash values.
void DisableActionButtons ()
void EnableActionButtons ()
void CalculateHashAsync (HashType hashType)
void LoopWhileBusy ()
long GetFileOrTextLength ()
void CancelHashCalculations ()
void CalculateHashes ()
Re-calculates all hashes that are checked for calculation.
void SaveHashesToFile ()
void BrowseFile ()
Browses for the file to be hashed.
void GenerateFilePreview ()
Generates file preview in the text preview box if the rbFile is checked.
void VerifyHash ()
void Handle_CtrlA_CtrlBackspace (TextBox textBox, object sender, KeyEventArgs e)
Handle the Ctrl-A (select all) and Ctrl-Backspace events for the specified text box.
override void Dispose (bool disposing)
Clean up any resources being used.
void SetGeneralProperties (FadingMessage fmsg)
void ClearHashes ()
Clears all text fields with calculated hash values.
void DisableActionButtons ()
void EnableActionButtons ()
void CalculateHashAsync (HashType hashType)
void LoopWhileBusy ()
long GetFileOrTextLength ()
void CancelHashCalculations ()
void CalculateHashes ()
Re-calculates all hashes that are checked for calculation.
void SaveHashesToFile ()
void BrowseFile ()
Browses for the file to be hashed.
void GenerateFilePreview ()
Generates file preview in the text preview box if the rbFile is checked.
void VerifyHash ()
void Handle_CtrlA_CtrlBackspace (TextBox textBox, object sender, KeyEventArgs e)
Handle the Ctrl-A (select all) and Ctrl-Backspace events for the specified text box.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
int _fadingMessageShowTimeMs = 3000
bool FileTextBoxInitialized = false
Color FileOnForeColor = Color.Black
Color FileOffForeColor = Color.DarkGray
bool ContentsTextBoxInitialized = false
Color ContentsFileBackColor = Color.LightGray
Color ContentsFileBinaryBackColor = Color.Wheat
Color ContentsTextBackColor = Color.White
Color ContentsFileForeColor = Color.Black
Color ContentsTextForeColor = Color.Blue
string _directoryPath
string _filePath
OpenFileDialog fileDialog
int NumCharsFilePreview = 1000
int NumInsertTextInfo = 0
int MaxInsertTextInfo = 1
bool TextBeingDropped = false
HashAboutForm _aboutForm = new HashAboutForm()
Properties
int FadingMessageShowTimeMs [get, set]
string DirectoryPath [get, set]
Directory where files are currently selected.
string FilePath [get, set]
Path to the file whose hash values are calculated.
bool IsAllHashesCalculated [get]
bool CalculateAllCanceled [get, set]
bool IsGroupCalculationPerformed [get, set]
bool RecalculateHashes [get, set]
HashJobArgumentsAndResults LastArguments [get, set]
HashJobArgumentsAndResults LastResults [get, set]
Form _form [get]
bool ControlDown [get]
Indicates whether Control key is currently pressed.
bool ShiftDown [get]
Indicates whether Shift key is currently pressed.
bool AltDown [get]
Indicates whether Alt key is currently pressed.
int MouseX [get]
Gets X component of current mouse cursor position (global, distance from left edge of display).
int MouseY [get]
Gets Y component of current mouse cursor position (global, distance from top edge of display).
double MouseRelX [get]
Mouse relative X position within the form (runs from -0.5 to 0.5).
double MouseRelY [get]
Mouse relative Y position within the form (runs from -0.5 to 0.5).
Private Member Functions
void backgroundWorker1_DoWork (object sender, DoWorkEventArgs e)
Calculates (in background) the required hash (specified in Argument property event arguments) as HashJobArgumentsAndResults.
void backgroundWorker1_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
void btnGenerate_Click (object sender, EventArgs e)
Requested hashs are generated and shown in the appropriate text boxes.
void btnClearHashes_Click (object sender, EventArgs e)
Hash values are cleared from the appropriate text fields.
void btnVerify_Click (object sender, EventArgs e)
Hash value is verified for the specified file or text.
void txtFile_Validated (object sender, EventArgs e)
After file has been validated.
void btnFileBrowse_Click (object sender, EventArgs e)
Browses for the file whose hash values will be calculated.
void chkMd5_CheckedChanged (object sender, EventArgs e)
void chkSha1_CheckedChanged (object sender, EventArgs e)
void chkSha256_CheckedChanged (object sender, EventArgs e)
void chkSha512_CheckedChanged (object sender, EventArgs e)
void btnMd5Copy_Click (object sender, EventArgs e)
void btnSha1Copy_Click (object sender, EventArgs e)
void btnSha256Copy_Click (object sender, EventArgs e)
void bthSha512_Click (object sender, EventArgs e)
void btnVerifyPaste_Click (object sender, EventArgs e)
void rbFile_CheckedChanged (object sender, EventArgs e)
Handles things that need to be done when we switch between hashing the file or hashing text from the textbox.
void chkGenerateFile_CheckedChanged (object sender, EventArgs e)
Handles situation when one changes the setting whether to store file's hash values to a file. If the check box gets checked then hashes are immediately saved to a file.
void txtContents_Enter (object sender, EventArgs e)
void txtContents_MouseEnter (object sender, EventArgs e)
void txtContents_TextChanged (object sender, EventArgs e)
void txtContents_Validated (object sender, EventArgs e)
After text is inserted, calculate appropriate hashes immediately.
void txtContents_KeyPress (object sender, KeyPressEventArgs e)
void chkUpperCase_CheckedChanged (object sender, EventArgs e)
Recalculates hashes because the requested lower/upper case form has changed.
void txtFile_Enter (object sender, EventArgs e)
void txtFile_MouseEnter (object sender, EventArgs e)
void txtFile_TextChanged (object sender, EventArgs e)
void txtFile_DragEnter (object sender, DragEventArgs e)
void txtFile_DragDrop (object sender, DragEventArgs e)
void txtContents_DragEnter (object sender, DragEventArgs e)
void txtContents_DragDrop (object sender, DragEventArgs e)
void txtFile_KeyDown (object sender, KeyEventArgs e)
void txtContents_KeyDown (object sender, KeyEventArgs e)
void btnAbout_Click (object sender, EventArgs e)
void btnCancelCalculation_Click (object sender, EventArgs e)
void btnHelp_Click (object sender, EventArgs e)
void chkCalculateWhenTyping_CheckedChanged (object sender, EventArgs e)
void HashControl_KeyUp (object sender, KeyEventArgs e)
Intended for handling key presses such as F1 for help, etc.
void helpToolStripMenuItem_Click (object sender, EventArgs e)
void aboutToolStripMenuItem_Click (object sender, EventArgs e)
void contextMenuStrip1_Opening (object sender, CancelEventArgs e)
void toolStripMenuItem1_Click (object sender, EventArgs e)
void SetCursorMouseUp (object sender, MouseEventArgs e)
Sets mouse cursor shape on MouseUp event, according to the current status of modifier keys.
void SetCursorMouseDown (object sender, MouseEventArgs e)
Sets mouse cursor shape on MouseDown event, according to the current status of modifier keys.
void InitiateMoveOrSize (object sender, MouseEventArgs e)
void Common_KeyDown (object sender, KeyEventArgs e)
Common event handler for key down event, installed on all controls.
void Common_KeyUp (object sender, KeyEventArgs e)
Common event handler for key up event, installed on all controls.
void Common_MouseClick (object sender, MouseEventArgs e)
Handles mouse click events for the current control. Available on non-interactive controls of the current control.
void Common_MouseDownOnInteractive (object sender, MouseEventArgs e)
Initiates dragging or resizing by mouse on MouseDown event.
void Common_MouseDownOnNoninteractiveControls (object sender, MouseEventArgs e)
Enables dragging by mouse.
void Common_MouseUp (object sender, MouseEventArgs e)
Enables dragging by mouse.
void Common_MouseMove (object sender, MouseEventArgs e)
Enables dragging by mouse.
void SetCommonEvents (Control control)
This method is used to set the common event handlers for the current control and its subcontrols.
void HashControl_Load (object sender, EventArgs e)
void helpToolStripMenuItem_Click_1 (object sender, EventArgs e)
void aboutToolStripMenuItem_Click_1 (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void btnGenerate_Click (object sender, EventArgs e)
Requested hashs are generated and shown in the appropriate text boxes.
void btnClearHashes_Click (object sender, EventArgs e)
Hash values are cleared from the appropriate text fields.
void btnVerify_Click (object sender, EventArgs e)
Hash value is verified for the specified file or text.
void txtFile_Validated (object sender, EventArgs e)
After file has been validated.
void btnFileBrowse_Click (object sender, EventArgs e)
Browses for the file whose hash values will be calculated.
void chkMd5_CheckedChanged (object sender, EventArgs e)
void chkSha1_CheckedChanged (object sender, EventArgs e)
void chkSha256_CheckedChanged (object sender, EventArgs e)
void chkSha512_CheckedChanged (object sender, EventArgs e)
void btnMd5Copy_Click (object sender, EventArgs e)
void btnSha1Copy_Click (object sender, EventArgs e)
void btnSha256Copy_Click (object sender, EventArgs e)
void bthSha512_Click (object sender, EventArgs e)
void btnVerifyPaste_Click (object sender, EventArgs e)
void rbFile_CheckedChanged (object sender, EventArgs e)
Handles things that need to be done when we switch between hashing the file or hashing text from the textbox.
void chkGenerateFile_CheckedChanged (object sender, EventArgs e)
Handles situation when one changes the setting whether to store file's hash values to a file. If the check box gets checked then hashes are immediately saved to a file.
void txtContents_Enter (object sender, EventArgs e)
void txtContents_MouseEnter (object sender, EventArgs e)
void txtContents_TextChanged (object sender, EventArgs e)
void txtContents_Validated (object sender, EventArgs e)
After text is inserted, calculate appropriate hashes immediately.
void chkUpperCase_CheckedChanged (object sender, EventArgs e)
Recalculates hashes because the requested lower/upper case form has changed.
void txtFile_Enter (object sender, EventArgs e)
void txtFile_MouseEnter (object sender, EventArgs e)
void txtFile_TextChanged (object sender, EventArgs e)
void txtFile_DragEnter (object sender, DragEventArgs e)
void txtFile_DragDrop (object sender, DragEventArgs e)
void txtContents_DragEnter (object sender, DragEventArgs e)
void txtContents_DragDrop (object sender, DragEventArgs e)
void txtFile_KeyDown (object sender, KeyEventArgs e)
void txtContents_KeyDown (object sender, KeyEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void backgroundWorker1_DoWork (object sender, DoWorkEventArgs e)
Calculates (in background) the required hash (specified in Argument property event arguments) as HashJobArgumentsAndResults.
void backgroundWorker1_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
void btnGenerate_Click (object sender, EventArgs e)
Requested hashs are generated and shown in the appropriate text boxes.
void btnClearHashes_Click (object sender, EventArgs e)
Hash values are cleared from the appropriate text fields.
void btnVerify_Click (object sender, EventArgs e)
Hash value is verified for the specified file or text.
void txtFile_Validated (object sender, EventArgs e)
After file has been validated.
void btnFileBrowse_Click (object sender, EventArgs e)
Browses for the file whose hash values will be calculated.
void chkMd5_CheckedChanged (object sender, EventArgs e)
void chkSha1_CheckedChanged (object sender, EventArgs e)
void chkSha256_CheckedChanged (object sender, EventArgs e)
void chkSha512_CheckedChanged (object sender, EventArgs e)
void btnMd5Copy_Click (object sender, EventArgs e)
void btnSha1Copy_Click (object sender, EventArgs e)
void btnSha256Copy_Click (object sender, EventArgs e)
void bthSha512_Click (object sender, EventArgs e)
void btnVerifyPaste_Click (object sender, EventArgs e)
void rbFile_CheckedChanged (object sender, EventArgs e)
Handles things that need to be done when we switch between hashing the file or hashing text from the textbox.
void chkGenerateFile_CheckedChanged (object sender, EventArgs e)
Handles situation when one changes the setting whether to store file's hash values to a file. If the check box gets checked then hashes are immediately saved to a file.
void txtContents_Enter (object sender, EventArgs e)
void txtContents_MouseEnter (object sender, EventArgs e)
void txtContents_TextChanged (object sender, EventArgs e)
void txtContents_Validated (object sender, EventArgs e)
After text is inserted, calculate appropriate hashes immediately.
void txtContents_KeyPress (object sender, KeyPressEventArgs e)
void chkUpperCase_CheckedChanged (object sender, EventArgs e)
Recalculates hashes because the requested lower/upper case form has changed.
void txtFile_Enter (object sender, EventArgs e)
void txtFile_MouseEnter (object sender, EventArgs e)
void txtFile_TextChanged (object sender, EventArgs e)
void txtFile_DragEnter (object sender, DragEventArgs e)
void txtFile_DragDrop (object sender, DragEventArgs e)
void txtContents_DragEnter (object sender, DragEventArgs e)
void txtContents_DragDrop (object sender, DragEventArgs e)
void txtFile_KeyDown (object sender, KeyEventArgs e)
void txtContents_KeyDown (object sender, KeyEventArgs e)
void btnAbout_Click (object sender, EventArgs e)
void btnCancelCalculation_Click (object sender, EventArgs e)
void btnInfo_Click (object sender, EventArgs e)
void chkCalculateWhenTyping_CheckedChanged (object sender, EventArgs e)
void HashControl_KeyUp (object sender, KeyEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void backgroundWorker1_DoWork (object sender, DoWorkEventArgs e)
Calculates (in background) the required hash (specified in Argument property event arguments) as HashJobArgumentsAndResults.
void backgroundWorker1_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
void btnGenerate_Click (object sender, EventArgs e)
Requested hashs are generated and shown in the appropriate text boxes.
void btnClearHashes_Click (object sender, EventArgs e)
Hash values are cleared from the appropriate text fields.
void btnVerify_Click (object sender, EventArgs e)
Hash value is verified for the specified file or text.
void txtFile_Validated (object sender, EventArgs e)
After file has been validated.
void btnFileBrowse_Click (object sender, EventArgs e)
Browses for the file whose hash values will be calculated.
void chkMd5_CheckedChanged (object sender, EventArgs e)
void chkSha1_CheckedChanged (object sender, EventArgs e)
void chkSha256_CheckedChanged (object sender, EventArgs e)
void chkSha512_CheckedChanged (object sender, EventArgs e)
void btnMd5Copy_Click (object sender, EventArgs e)
void btnSha1Copy_Click (object sender, EventArgs e)
void btnSha256Copy_Click (object sender, EventArgs e)
void bthSha512_Click (object sender, EventArgs e)
void btnVerifyPaste_Click (object sender, EventArgs e)
void rbFile_CheckedChanged (object sender, EventArgs e)
Handles things that need to be done when we switch between hashing the file or hashing text from the textbox.
void chkGenerateFile_CheckedChanged (object sender, EventArgs e)
Handles situation when one changes the setting whether to store file's hash values to a file. If the check box gets checked then hashes are immediately saved to a file.
void txtContents_Enter (object sender, EventArgs e)
void txtContents_MouseEnter (object sender, EventArgs e)
void txtContents_TextChanged (object sender, EventArgs e)
void txtContents_Validated (object sender, EventArgs e)
After text is inserted, calculate appropriate hashes immediately.
void txtContents_KeyPress (object sender, KeyPressEventArgs e)
void chkUpperCase_CheckedChanged (object sender, EventArgs e)
Recalculates hashes because the requested lower/upper case form has changed.
void txtFile_Enter (object sender, EventArgs e)
void txtFile_MouseEnter (object sender, EventArgs e)
void txtFile_TextChanged (object sender, EventArgs e)
void txtFile_DragEnter (object sender, DragEventArgs e)
void txtFile_DragDrop (object sender, DragEventArgs e)
void txtContents_DragEnter (object sender, DragEventArgs e)
void txtContents_DragDrop (object sender, DragEventArgs e)
void txtFile_KeyDown (object sender, KeyEventArgs e)
void txtContents_KeyDown (object sender, KeyEventArgs e)
void btnAbout_Click (object sender, EventArgs e)
void btnCancelCalculation_Click (object sender, EventArgs e)
void btnInfo_Click (object sender, EventArgs e)
void chkCalculateWhenTyping_CheckedChanged (object sender, EventArgs e)
void HashControl_KeyUp (object sender, KeyEventArgs e)
Intended for handling key presses such as F1 for help, etc.
void helpToolStripMenuItem_Click (object sender, EventArgs e)
void aboutToolStripMenuItem_Click (object sender, EventArgs e)
void contextMenuStrip1_Opening (object sender, CancelEventArgs e)
void toolStripMenuItem1_Click (object sender, EventArgs e)
void SetCursorMouseUp (object sender, MouseEventArgs e)
Sets mouse cursor shape on MouseUp event, according to the current status of modifier keys.
void SetCursorMouseDown (object sender, MouseEventArgs e)
Sets mouse cursor shape on MouseDown event, according to the current status of modifier keys.
void InitiateMoveOrSize (object sender, MouseEventArgs e)
void Common_KeyDown (object sender, KeyEventArgs e)
Common event handler for key down event, installed on all controls.
void Common_KeyUp (object sender, KeyEventArgs e)
Common event handler for key up event, installed on all controls.
void Common_MouseDownOnInteractive (object sender, MouseEventArgs e)
Initiates dragging or resizing by mouse on MouseDown event.
void Common_MouseDownOnNoninteractiveControls (object sender, MouseEventArgs e)
Enables dragging by mouse.
void Common_MouseUp (object sender, MouseEventArgs e)
Enables dragging by mouse.
void Common_MouseMove (object sender, MouseEventArgs e)
Enables dragging by mouse.
void SetCommonEvents (Control f)
This method is used to set the common event handlers for the current control and its subcontrols.
void HashControl_Load (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Color _fadingMessageInfoColor = FadingMessage.DefaultBackGroundColor
Color _fadingMessageWarningColor = Color.Orange
Color _fadingMessageErrorColor = Color.Red
bool _skipFileValidationEvent = false
int _mouseInitialLocalX
int _mouseInitialLocalY
int _mouseInitialX
int _mouseInitialY
int _formInitialLeft
int _formInitialTop
int _formInitialWidth
int _formInitialHeight
double _mouseInitialRelX
double _mouseInitialRelY
int _mousePreviousX
int _mousePreviousY
int _distMoveX
int _distMoveY
int _distSizeX
int _distSizeY
bool _isSizingOrMoving = false
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.GroupBox grpHashGeneration
System.Windows.Forms.CheckBox chkSha512
System.Windows.Forms.Button bthSha512
System.Windows.Forms.TextBox txtSha512
System.Windows.Forms.Label lblSha512
System.Windows.Forms.CheckBox chkSha256
System.Windows.Forms.CheckBox chkSha1
System.Windows.Forms.CheckBox chkMd5
System.Windows.Forms.Button btnSha256Copy
System.Windows.Forms.Button btnSha1Copy
System.Windows.Forms.Button btnMd5Copy
System.Windows.Forms.TextBox txtSha256
System.Windows.Forms.Label lblSha256
System.Windows.Forms.TextBox txtSha1
System.Windows.Forms.Label lblSha1
System.Windows.Forms.TextBox txtMd5
System.Windows.Forms.Label lblMd5
System.Windows.Forms.Button btnFileBrowse
System.Windows.Forms.TextBox txtFile
System.Windows.Forms.Label lblFile
System.Windows.Forms.RadioButton rbText
System.Windows.Forms.RadioButton rbFile
System.Windows.Forms.GroupBox grpTextPreview
System.Windows.Forms.TextBox txtContents
System.Windows.Forms.Button btnGenerate
System.Windows.Forms.CheckBox chkGenerateFile
System.Windows.Forms.Label lvlVerifyMain
System.Windows.Forms.Button btnVerify
System.Windows.Forms.Button btnVerifyPaste
System.Windows.Forms.TextBox txtVerify
System.Windows.Forms.Label lblVerify
System.Windows.Forms.OpenFileDialog openFileDialog1
System.Windows.Forms.Button btnClearHashes
System.Windows.Forms.CheckBox chkUpperCase
System.Windows.Forms.Button btnAbout
IG.Forms.AbortableBackgroundWorker backgroundWorker1
System.Windows.Forms.Button btnCancelCalculation
System.Windows.Forms.Button btnHelp
IndicatorLight indicatorLight1
System.Windows.Forms.CheckBox chkCalculateWhenTyping
System.Windows.Forms.ContextMenuStrip menuMain
System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem
System.Windows.Forms.Button btnInfo
System.Windows.Forms.ContextMenuStrip contextMenuStrip1
System.Windows.Forms.ContextMenuStrip contextMenuStrip2
Detailed Description
A control used to calculate various checksums of selected files or inserted text.
See:
http://www2.arnes.si/~ljc3m2/igor/software/IGLibShellApp/HashForm.html#hashform
$A Igor Aug 08;
Constructor & Destructor Documentation
HashControl() [1/4]
IG.Forms.HashControl.HashControl () inline
References IG.Forms.HashControl.backgroundWorker1, IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.HashControl.btnCancelCalculation, IG.Forms.HashControl.CalculateAllCanceled, IG.Forms.HashControl.chkCalculateWhenTyping, IG.Forms.HashControl.ContentsFileBackColor, IG.Forms.HashControl.ContentsFileForeColor, IG.Forms.HashControl.FileOnForeColor, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.InitializeComponent(), IG.Forms.HashControl.IsGroupCalculationPerformed, IG.Forms.HashControl.rbFile, IG.Forms.IndicatorLight.SetOff(), IG.Forms.HashControl.txtContents, and IG.Forms.HashControl.txtFile.
HashControl() [2/4]
IG.Forms.HashControl.HashControl () inline
References IG.Forms.HashControl.ContentsFileBackColor, IG.Forms.HashControl.ContentsFileForeColor, IG.Forms.HashControl.FileOnForeColor, IG.Forms.HashControl.InitializeComponent(), IG.Forms.HashControl.txtContents, and IG.Forms.HashControl.txtFile.
HashControl() [3/4]
IG.Forms.HashControl.HashControl () inline
References IG.Forms.HashControl.backgroundWorker1, IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.HashControl.btnCancelCalculation, IG.Forms.HashControl.CalculateAllCanceled, IG.Forms.HashControl.chkCalculateWhenTyping, IG.Forms.HashControl.ContentsFileBackColor, IG.Forms.HashControl.ContentsFileForeColor, IG.Forms.HashControl.FileOnForeColor, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.InitializeComponent(), IG.Forms.HashControl.IsGroupCalculationPerformed, IG.Forms.HashControl.rbFile, IG.Forms.IndicatorLight.SetOff(), IG.Forms.HashControl.txtContents, and IG.Forms.HashControl.txtFile.
HashControl() [4/4]
IG.Forms.HashControl.HashControl () inline
References IG.Forms.HashControl.backgroundWorker1, IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.HashControl.btnCancelCalculation, IG.Forms.HashControl.CalculateAllCanceled, IG.Forms.HashControl.chkCalculateWhenTyping, IG.Forms.HashControl.ContentsFileBackColor, IG.Forms.HashControl.ContentsFileForeColor, IG.Forms.HashControl.FileOnForeColor, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.InitializeComponent(), IG.Forms.HashControl.IsGroupCalculationPerformed, IG.Forms.HashControl.rbFile, IG.Forms.IndicatorLight.SetOff(), IG.Forms.HashControl.txtContents, and IG.Forms.HashControl.txtFile.
Member Function Documentation
SetGeneralProperties() [1/3]
void IG.Forms.HashControl.SetGeneralProperties (FadingMessage fmsg) inline protected
References IG.Forms.FadingMessage.BackGroundColor, IG.Forms.FadingMessage.DefaultBackGroundColor, IG.Forms.FadingMessage.IsTopMostWindow, IG.Forms.FadingMessage.LaunchedAtMouseCursor, and IG.Forms.FadingMessage.LaunchedInParallelThread.
Referenced by IG.Forms.HashControl.FadingMessageError(), IG.Forms.HashControl.FadingMessageInfo(), and IG.Forms.HashControl.FadingMessageWarning().
FadingMessageInfo() [1/3]
void IG.Forms.HashControl.FadingMessageInfo (string message, int showTimeMs = 0) inline
References IG.Forms.HashControl._fadingMessageInfoColor, IG.Forms.FadingMessage.BackGroundColor, IG.Forms.HashControl.FadingMessageShowTimeMs, IG.Lib.UtilSystem.IsWindowsOs, and IG.Forms.HashControl.SetGeneralProperties().
Referenced by IG.Forms.HashControl.CancelHashCalculations(), and IG.Forms.HashControl.rbFile_CheckedChanged().
FadingMessageWarning() [1/3]
void IG.Forms.HashControl.FadingMessageWarning (string message, int showTimeMs = 0) inline
References IG.Forms.HashControl._fadingMessageWarningColor, IG.Forms.FadingMessage.BackGroundColor, IG.Forms.HashControl.FadingMessageShowTimeMs, IG.Lib.UtilSystem.IsWindowsOs, and IG.Forms.HashControl.SetGeneralProperties().
Referenced by IG.Forms.HashControl.CancelHashCalculations().
FadingMessageError() [1/3]
void IG.Forms.HashControl.FadingMessageError (string message, int showTimeMs = 0) inline
References IG.Forms.HashControl._fadingMessageErrorColor, IG.Forms.FadingMessage.BackGroundColor, IG.Forms.HashControl.FadingMessageShowTimeMs, IG.Lib.UtilSystem.IsWindowsOs, and IG.Forms.HashControl.SetGeneralProperties().
Referenced by IG.Forms.HashControl.CalculateHashes().
ReportError() [1/4]
void IG.Forms.HashControl.ReportError (string errorMessage) inline
Referenced by IG.Forms.HashControl.bthSha512_Click(), IG.Forms.HashControl.btnMd5Copy_Click(), IG.Forms.HashControl.btnSha1Copy_Click(), IG.Forms.HashControl.btnSha256Copy_Click(), IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.HashControl_Load(), IG.Forms.HashControl.SaveHashesToFile(), IG.Forms.HashControl.txtFile_Validated(), and IG.Forms.HashControl.VerifyHash().
ReportWarning() [1/4]
void IG.Forms.HashControl.ReportWarning (string warningMessage) inline
ReportInfo() [1/4]
void IG.Forms.HashControl.ReportInfo (string message) inline
Referenced by IG.Forms.HashControl.rbFile_CheckedChanged(), IG.Forms.HashControl.SaveHashesToFile(), and IG.Forms.HashControl.VerifyHash().
ClearHashes() [1/4]
void IG.Forms.HashControl.ClearHashes () inline protected
Clears all text fields with calculated hash values.
References IG.Forms.AbortableBackgroundWorker.Abort(), IG.Forms.HashControl.backgroundWorker1, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.RecalculateHashes, IG.Forms.IndicatorLight.SetOff(), IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, and IG.Forms.HashControl.txtSha512.
Referenced by IG.Forms.HashControl.btnClearHashes_Click(), IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.rbFile_CheckedChanged(), IG.Forms.HashControl.txtContents_DragDrop(), IG.Forms.HashControl.txtContents_Enter(), and IG.Forms.HashControl.txtFile_Validated().
DisableActionButtons() [1/3]
void IG.Forms.HashControl.DisableActionButtons () inline protected
References IG.Forms.HashControl.btnGenerate, and IG.Forms.HashControl.btnVerify.
Referenced by IG.Forms.HashControl.CalculateHashAsync().
EnableActionButtons() [1/3]
void IG.Forms.HashControl.EnableActionButtons () inline protected
References IG.Forms.HashControl.btnGenerate, and IG.Forms.HashControl.btnVerify.
Referenced by IG.Forms.HashControl.backgroundWorker1_RunWorkerCompleted(), and IG.Forms.HashControl.CalculateHashes().
backgroundWorker1_DoWork() [1/3]
void IG.Forms.HashControl.backgroundWorker1_DoWork (object sender, DoWorkEventArgs e) inline private
Calculates (in background) the required hash (specified in Argument property event arguments) as HashJobArgumentsAndResults.
Parameters
sender Originaror of event that runs this event handler.
e Event arguments, contain the necessary information about how to calculate the hash.
References IG.Forms.HashControl.HashJobArgumentsAndResults.CalculatedHash, IG.Forms.HashControl.FilePath, IG.Crypto.UtilCrypto.GetFileHashMd5Hex(), IG.Crypto.UtilCrypto.GetFileHashSha1Hex(), IG.Crypto.UtilCrypto.GetFileHashSha256Hex(), IG.Crypto.UtilCrypto.GetFileHashSha512Hex(), IG.Crypto.UtilCrypto.GetStringHashMd5Hex(), IG.Crypto.UtilCrypto.GetStringHashSha1Hex(), IG.Crypto.UtilCrypto.GetStringHashSha256Hex(), IG.Crypto.UtilCrypto.GetStringHashSha512Hex(), IG.Forms.HashControl.HashJobArgumentsAndResults.HashedFilePath, IG.Forms.HashControl.HashJobArgumentsAndResults.HashedText, IG.Forms.HashControl.HashJobArgumentsAndResults.HashType, and IG.Forms.HashControl.LastArguments.
Referenced by IG.Forms.HashControl.InitializeComponent().
backgroundWorker1_RunWorkerCompleted() [1/3]
void IG.Forms.HashControl.backgroundWorker1_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.HashControl.btnCancelCalculation, IG.Forms.HashControl.HashJobArgumentsAndResults.CalculatedHash, IG.Forms.HashControl.chkUpperCase, IG.Forms.HashControl.EnableActionButtons(), IG.Forms.HashControl.HashJobArgumentsAndResults.HashType, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.IsAllHashesCalculated, IG.Forms.HashControl.LastResults, IG.Forms.IndicatorLight.SetOff(), IG.Forms.IndicatorLight.SetOk(), IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, IG.Forms.HashControl.txtSha512, and IG.Forms.HashControl.HashJobArgumentsAndResults.UpdateUI.
Referenced by IG.Forms.HashControl.InitializeComponent().
CalculateHashAsync() [1/3]
void IG.Forms.HashControl.CalculateHashAsync (HashType hashType) inline protected
References IG.Forms.HashControl.backgroundWorker1, IG.Forms.HashControl.btnCancelCalculation, IG.Forms.HashControl.CalculateAllCanceled, IG.Forms.HashControl.DisableActionButtons(), IG.Forms.HashControl.FilePath, IG.Forms.HashControl.GetFileOrTextLength(), IG.Forms.HashControl.HashJobArgumentsAndResults.HashedFilePath, IG.Forms.HashControl.HashJobArgumentsAndResults.HashedLength, IG.Forms.HashControl.HashJobArgumentsAndResults.HashedText, IG.Forms.HashControl.indicatorLight1, IG.Lib.UtilSystem.IsReadableFile(), IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.rbFile, IG.Forms.HashControl.ReportError(), IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetError(), IG.Forms.HashControl.txtContents, and IG.Forms.HashControl.HashJobArgumentsAndResults.UpdateUI.
Referenced by IG.Forms.HashControl.bthSha512_Click(), IG.Forms.HashControl.btnMd5Copy_Click(), IG.Forms.HashControl.btnSha1Copy_Click(), IG.Forms.HashControl.btnSha256Copy_Click(), IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkMd5_CheckedChanged(), IG.Forms.HashControl.chkSha1_CheckedChanged(), IG.Forms.HashControl.chkSha256_CheckedChanged(), IG.Forms.HashControl.chkSha512_CheckedChanged(), and IG.Forms.HashControl.VerifyHash().
LoopWhileBusy() [1/3]
void IG.Forms.HashControl.LoopWhileBusy () inline protected
References IG.Forms.HashControl.backgroundWorker1.
Referenced by IG.Forms.HashControl.bthSha512_Click(), IG.Forms.HashControl.btnMd5Copy_Click(), IG.Forms.HashControl.btnSha1Copy_Click(), IG.Forms.HashControl.btnSha256Copy_Click(), IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.CalculateHashes(), and IG.Forms.HashControl.VerifyHash().
GetFileOrTextLength() [1/3]
long IG.Forms.HashControl.GetFileOrTextLength () inline protected
References IG.Forms.HashControl.FilePath, IG.Forms.HashControl.rbFile, and IG.Forms.HashControl.txtContents.
Referenced by IG.Forms.HashControl.CalculateHashAsync(), and IG.Forms.HashControl.CalculateHashes().
CancelHashCalculations() [1/3]
void IG.Forms.HashControl.CancelHashCalculations () inline protected
References IG.Forms.AbortableBackgroundWorker.Abort(), IG.Forms.HashControl.backgroundWorker1, IG.Forms.HashControl.CalculateAllCanceled, IG.Forms.HashControl.FadingMessageInfo(), IG.Forms.HashControl.FadingMessageShowTimeMs, and IG.Forms.HashControl.FadingMessageWarning().
Referenced by IG.Forms.HashControl.btnCancelCalculation_Click(), and IG.Forms.HashControl.CalculateHashes().
CalculateHashes() [1/4]
void IG.Forms.HashControl.CalculateHashes () inline protected
Re-calculates all hashes that are checked for calculation.
References IG.Forms.HashControl.backgroundWorker1, IG.Forms.IndicatorLight.BlinkError(), IG.Forms.HashControl.CalculateAllCanceled, IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.CancelHashCalculations(), IG.Forms.HashControl.chkCalculateWhenTyping, IG.Forms.HashControl.chkGenerateFile, IG.Forms.HashControl.chkMd5, IG.Forms.HashControl.chkSha1, IG.Forms.HashControl.chkSha256, IG.Forms.HashControl.chkSha512, IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.EnableActionButtons(), IG.Forms.HashControl.FadingMessageError(), IG.Forms.HashControl.GetFileOrTextLength(), IG.Forms.HashControl.HashJobArgumentsAndResults.HashedLength, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.IsGroupCalculationPerformed, IG.Forms.HashControl.LastArguments, IG.Forms.HashControl.LastResults, IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.rbText, IG.Forms.HashControl.RecalculateHashes, IG.Forms.HashControl.ReportError(), IG.Forms.HashControl.SaveHashesToFile(), IG.Forms.IndicatorLight.SetError(), and IG.Forms.HashControl.txtVerify.
Referenced by IG.Forms.HashControl.BrowseFile(), IG.Forms.HashControl.btnGenerate_Click(), IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkMd5_CheckedChanged(), IG.Forms.HashControl.chkSha1_CheckedChanged(), IG.Forms.HashControl.chkSha256_CheckedChanged(), IG.Forms.HashControl.chkSha512_CheckedChanged(), IG.Forms.HashControl.chkUpperCase_CheckedChanged(), IG.Forms.HashControl.rbFile_CheckedChanged(), IG.Forms.HashControl.txtContents_TextChanged(), IG.Forms.HashControl.txtContents_Validated(), and IG.Forms.HashControl.txtFile_Validated().
SaveHashesToFile() [1/4]
void IG.Forms.HashControl.SaveHashesToFile () inline protected
References IG.Forms.HashControl.FilePath, IG.Crypto.ConstCrypto.HashFileExtension, IG.Forms.HashControl.rbFile, IG.Forms.HashControl.ReportError(), IG.Forms.HashControl.ReportInfo(), IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, and IG.Forms.HashControl.txtSha512.
Referenced by IG.Forms.HashControl.CalculateHashes(), and IG.Forms.HashControl.chkGenerateFile_CheckedChanged().
BrowseFile() [1/4]
void IG.Forms.HashControl.BrowseFile () inline protected
Browses for the file to be hashed.
References IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.DirectoryPath, IG.Forms.HashControl.fileDialog, IG.Forms.HashControl.FilePath, IG.Forms.HashControl.GenerateFilePreview(), IG.Forms.HashControl.rbFile, and IG.Forms.HashControl.txtFile.
Referenced by IG.Forms.HashControl.btnFileBrowse_Click().
GenerateFilePreview() [1/4]
void IG.Forms.HashControl.GenerateFilePreview () inline protected
Generates file preview in the text preview box if the rbFile is checked.
References IG.Forms.HashControl.ContentsFileBackColor, IG.Forms.HashControl.ContentsFileBinaryBackColor, IG.Forms.HashControl.ContentsFileForeColor, IG.Forms.HashControl.FilePath, IG.Lib.UtilSystem.IsTextFile(), IG.Forms.HashControl.NumCharsFilePreview, IG.Forms.HashControl.rbFile, and IG.Forms.HashControl.txtContents.
Referenced by IG.Forms.HashControl.BrowseFile(), IG.Forms.HashControl.rbFile_CheckedChanged(), and IG.Forms.HashControl.txtFile_Validated().
VerifyHash() [1/4]
void IG.Forms.HashControl.VerifyHash () inline protected
References IG.Lib.Util.AreHexStringsEqual(), IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.FilePath, IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.rbFile, IG.Forms.HashControl.ReportError(), IG.Forms.HashControl.ReportInfo(), IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, IG.Forms.HashControl.txtSha512, and IG.Forms.HashControl.txtVerify.
Referenced by IG.Forms.HashControl.btnVerify_Click().
btnGenerate_Click() [1/4]
void IG.Forms.HashControl.btnGenerate_Click (object sender, EventArgs e) inline private
Requested hashs are generated and shown in the appropriate text boxes.
References IG.Forms.HashControl.CalculateHashes().
Referenced by IG.Forms.HashControl.InitializeComponent().
btnClearHashes_Click() [1/4]
void IG.Forms.HashControl.btnClearHashes_Click (object sender, EventArgs e) inline private
Hash values are cleared from the appropriate text fields.
References IG.Forms.HashControl.ClearHashes().
Referenced by IG.Forms.HashControl.InitializeComponent().
btnVerify_Click() [1/4]
void IG.Forms.HashControl.btnVerify_Click (object sender, EventArgs e) inline private
Hash value is verified for the specified file or text.
References IG.Forms.HashControl.VerifyHash().
Referenced by IG.Forms.HashControl.InitializeComponent().
txtFile_Validated() [1/4]
void IG.Forms.HashControl.txtFile_Validated (object sender, EventArgs e) inline private
After file has been validated.
References IG.Forms.HashControl._skipFileValidationEvent, IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.FilePath, IG.Forms.HashControl.FileTextBoxInitialized, IG.Forms.HashControl.GenerateFilePreview(), IG.Forms.HashControl.indicatorLight1, IG.Lib.UtilSystem.IsReadableFile(), IG.Forms.HashControl.rbFile, IG.Forms.HashControl.ReportError(), IG.Forms.IndicatorLight.SetError(), and IG.Forms.HashControl.txtFile.
Referenced by IG.Forms.HashControl.InitializeComponent(), IG.Forms.HashControl.txtContents_DragDrop(), and IG.Forms.HashControl.txtFile_DragDrop().
btnFileBrowse_Click() [1/4]
void IG.Forms.HashControl.btnFileBrowse_Click (object sender, EventArgs e) inline private
Browses for the file whose hash values will be calculated.
References IG.Forms.HashControl.BrowseFile(), IG.Forms.HashControl.FilePath, and IG.Forms.HashControl.rbFile.
Referenced by IG.Forms.HashControl.InitializeComponent().
chkMd5_CheckedChanged() [1/4]
void IG.Forms.HashControl.chkMd5_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.chkMd5, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.IsAllHashesCalculated, IG.Forms.IndicatorLight.SetOk(), and IG.Forms.HashControl.txtMd5.
Referenced by IG.Forms.HashControl.InitializeComponent().
chkSha1_CheckedChanged() [1/4]
void IG.Forms.HashControl.chkSha1_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.chkSha1, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.IsAllHashesCalculated, IG.Forms.IndicatorLight.SetOk(), and IG.Forms.HashControl.txtSha1.
Referenced by IG.Forms.HashControl.InitializeComponent().
chkSha256_CheckedChanged() [1/4]
void IG.Forms.HashControl.chkSha256_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.chkSha256, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.IsAllHashesCalculated, IG.Forms.IndicatorLight.SetOk(), and IG.Forms.HashControl.txtSha256.
Referenced by IG.Forms.HashControl.InitializeComponent().
chkSha512_CheckedChanged() [1/4]
void IG.Forms.HashControl.chkSha512_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.chkSha512, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.IsAllHashesCalculated, IG.Forms.IndicatorLight.SetOk(), and IG.Forms.HashControl.txtSha512.
Referenced by IG.Forms.HashControl.InitializeComponent().
btnMd5Copy_Click() [1/4]
void IG.Forms.HashControl.btnMd5Copy_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.ReportError(), and IG.Forms.HashControl.txtMd5.
Referenced by IG.Forms.HashControl.InitializeComponent().
btnSha1Copy_Click() [1/4]
void IG.Forms.HashControl.btnSha1Copy_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.ReportError(), and IG.Forms.HashControl.txtSha1.
Referenced by IG.Forms.HashControl.InitializeComponent().
btnSha256Copy_Click() [1/4]
void IG.Forms.HashControl.btnSha256Copy_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.ReportError(), and IG.Forms.HashControl.txtSha256.
Referenced by IG.Forms.HashControl.InitializeComponent().
bthSha512_Click() [1/4]
void IG.Forms.HashControl.bthSha512_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.ReportError(), and IG.Forms.HashControl.txtSha512.
Referenced by IG.Forms.HashControl.InitializeComponent().
btnVerifyPaste_Click() [1/4]
void IG.Forms.HashControl.btnVerifyPaste_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.txtVerify.
Referenced by IG.Forms.HashControl.InitializeComponent().
rbFile_CheckedChanged() [1/4]
void IG.Forms.HashControl.rbFile_CheckedChanged (object sender, EventArgs e) inline private
Handles things that need to be done when we switch between hashing the file or hashing text from the textbox.
References IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkCalculateWhenTyping, IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.ContentsFileBackColor, IG.Forms.HashControl.ContentsFileForeColor, IG.Forms.HashControl.ContentsTextBackColor, IG.Forms.HashControl.ContentsTextForeColor, IG.Forms.HashControl.FadingMessageInfo(), IG.Forms.HashControl.FileOffForeColor, IG.Forms.HashControl.FileOnForeColor, IG.Forms.HashControl.FilePath, IG.Forms.HashControl.GenerateFilePreview(), IG.Forms.HashControl.grpTextPreview, IG.Forms.HashControl.MaxInsertTextInfo, IG.Forms.HashControl.NumInsertTextInfo, IG.Forms.HashControl.rbFile, IG.Forms.HashControl.RecalculateHashes, IG.Forms.HashControl.txtContents, and IG.Forms.HashControl.txtFile.
Referenced by IG.Forms.HashControl.InitializeComponent().
chkGenerateFile_CheckedChanged() [1/4]
void IG.Forms.HashControl.chkGenerateFile_CheckedChanged (object sender, EventArgs e) inline private
Handles situation when one changes the setting whether to store file's hash values to a file. If the check box gets checked then hashes are immediately saved to a file.
References IG.Forms.HashControl.chkGenerateFile, and IG.Forms.HashControl.SaveHashesToFile().
Referenced by IG.Forms.HashControl.InitializeComponent().
txtContents_Enter() [1/4]
void IG.Forms.HashControl.txtContents_Enter (object sender, EventArgs e) inline private
References IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.ContentsTextBoxInitialized, IG.Forms.HashControl.rbFile, and IG.Forms.HashControl.txtContents.
Referenced by IG.Forms.HashControl.InitializeComponent().
txtContents_MouseEnter() [1/4]
void IG.Forms.HashControl.txtContents_MouseEnter (object sender, EventArgs e) inline private
References IG.Forms.HashControl.ContentsTextBoxInitialized, and IG.Forms.HashControl.txtContents.
Referenced by IG.Forms.HashControl.InitializeComponent().
txtContents_TextChanged() [1/4]
void IG.Forms.HashControl.txtContents_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkCalculateWhenTyping, IG.Forms.HashControl.ContentsTextBoxInitialized, IG.Forms.HashControl.IsGroupCalculationPerformed, IG.Forms.HashControl.rbText, and IG.Forms.HashControl.RecalculateHashes.
Referenced by IG.Forms.HashControl.InitializeComponent().
txtContents_Validated() [1/4]
void IG.Forms.HashControl.txtContents_Validated (object sender, EventArgs e) inline private
After text is inserted, calculate appropriate hashes immediately.
References IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.ContentsTextBoxInitialized, and IG.Forms.HashControl.rbText.
Referenced by IG.Forms.HashControl.InitializeComponent(), and IG.Forms.HashControl.txtContents_DragDrop().
txtContents_KeyPress() [1/3]
void IG.Forms.HashControl.txtContents_KeyPress (object sender, KeyPressEventArgs e) inline private
Referenced by IG.Forms.HashControl.InitializeComponent().
chkUpperCase_CheckedChanged() [1/4]
void IG.Forms.HashControl.chkUpperCase_CheckedChanged (object sender, EventArgs e) inline private
Recalculates hashes because the requested lower/upper case form has changed.
References IG.Forms.HashControl.chkUpperCase, IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, and IG.Forms.HashControl.txtSha512.
Referenced by IG.Forms.HashControl.InitializeComponent().
txtFile_Enter() [1/4]
void IG.Forms.HashControl.txtFile_Enter (object sender, EventArgs e) inline private
References IG.Forms.HashControl.FileTextBoxInitialized, and IG.Forms.HashControl.txtFile.
Referenced by IG.Forms.HashControl.InitializeComponent().
txtFile_MouseEnter() [1/4]
void IG.Forms.HashControl.txtFile_MouseEnter (object sender, EventArgs e) inline private
References IG.Forms.HashControl.FileTextBoxInitialized, and IG.Forms.HashControl.txtFile.
Referenced by IG.Forms.HashControl.InitializeComponent().
txtFile_TextChanged() [1/4]
void IG.Forms.HashControl.txtFile_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.FileTextBoxInitialized.
Referenced by IG.Forms.HashControl.InitializeComponent().
txtFile_DragEnter() [1/4]
void IG.Forms.HashControl.txtFile_DragEnter (object sender, DragEventArgs e) inline private
Referenced by IG.Forms.HashControl.InitializeComponent().
txtFile_DragDrop() [1/4]
void IG.Forms.HashControl.txtFile_DragDrop (object sender, DragEventArgs e) inline private
References IG.Forms.HashControl.FilePath, IG.Forms.HashControl.rbFile, IG.Forms.HashControl.txtFile, and IG.Forms.HashControl.txtFile_Validated().
Referenced by IG.Forms.HashControl.InitializeComponent().
txtContents_DragEnter() [1/4]
void IG.Forms.HashControl.txtContents_DragEnter (object sender, DragEventArgs e) inline private
Referenced by IG.Forms.HashControl.InitializeComponent(), and IG.Forms.HashControl.SetCommonEvents().
txtContents_DragDrop() [1/4]
void IG.Forms.HashControl.txtContents_DragDrop (object sender, DragEventArgs e) inline private
References IG.Forms.HashControl._form, IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.FilePath, IG.Forms.HashControl.rbFile, IG.Forms.HashControl.rbText, IG.Forms.HashControl.TextBeingDropped, IG.Forms.HashControl.txtContents, IG.Forms.HashControl.txtContents_Validated(), IG.Forms.HashControl.txtFile, and IG.Forms.HashControl.txtFile_Validated().
Referenced by IG.Forms.HashControl.InitializeComponent(), and IG.Forms.HashControl.SetCommonEvents().
Handle_CtrlA_CtrlBackspace() [1/4]
void IG.Forms.HashControl.Handle_CtrlA_CtrlBackspace (TextBox textBox, object sender, KeyEventArgs e) inline protected
Handle the Ctrl-A (select all) and Ctrl-Backspace events for the specified text box.
Parameters
textBox Text box for wich the event is handled.
Referenced by IG.Forms.HashControl.txtContents_KeyDown(), and IG.Forms.HashControl.txtFile_KeyDown().
txtFile_KeyDown() [1/4]
void IG.Forms.HashControl.txtFile_KeyDown (object sender, KeyEventArgs e) inline private
References IG.Forms.HashControl.Handle_CtrlA_CtrlBackspace(), and IG.Forms.HashControl.txtFile.
Referenced by IG.Forms.HashControl.InitializeComponent().
txtContents_KeyDown() [1/4]
void IG.Forms.HashControl.txtContents_KeyDown (object sender, KeyEventArgs e) inline private
References IG.Forms.HashControl.Handle_CtrlA_CtrlBackspace(), and IG.Forms.HashControl.txtContents.
Referenced by IG.Forms.HashControl.InitializeComponent().
btnAbout_Click() [1/3]
void IG.Forms.HashControl.btnAbout_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl._aboutForm.
Referenced by IG.Forms.HashControl.aboutToolStripMenuItem_Click(), IG.Forms.HashControl.aboutToolStripMenuItem_Click_1(), IG.Forms.HashControl.InitializeComponent(), and IG.Forms.HashControl.KeyUpHandler().
btnCancelCalculation_Click() [1/3]
void IG.Forms.HashControl.btnCancelCalculation_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CancelHashCalculations().
Referenced by IG.Forms.HashControl.InitializeComponent().
btnHelp_Click()
void IG.Forms.HashControl.btnHelp_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl._aboutForm, IG.Forms.HashAboutControl.HelpPdf(), and IG.Forms.HashAboutForm.MainControl.
Referenced by IG.Forms.HashControl.helpToolStripMenuItem_Click(), IG.Forms.HashControl.helpToolStripMenuItem_Click_1(), IG.Forms.HashControl.InitializeComponent(), and IG.Forms.HashControl.KeyUpHandler().
chkCalculateWhenTyping_CheckedChanged() [1/3]
void IG.Forms.HashControl.chkCalculateWhenTyping_CheckedChanged (object sender, EventArgs e) inline private
Referenced by IG.Forms.HashControl.InitializeComponent().
HashControl_KeyUp() [1/3]
void IG.Forms.HashControl.HashControl_KeyUp (object sender, KeyEventArgs e) inline private
Intended for handling key presses such as F1 for help, etc.
Parameters
sender
e
References IG.Forms.HashControl.KeyUpHandler().
Referenced by IG.Forms.HashControl.InitializeComponent().
KeyUpHandler() [1/3]
void IG.Forms.HashControl.KeyUpHandler (object sender, KeyEventArgs e) inline
Handles key up events for the current form.
Form does not catch the KeyUp events. Therefore, the event handler code was moved to a public function, which can be called from a form, tab control, or other control that contains this control.
References IG.Forms.HashControl.btnAbout_Click(), and IG.Forms.HashControl.btnHelp_Click().
Referenced by IG.Forms.HashControl.Common_KeyUp(), IG.Forms.HashControl.HashControl_KeyUp(), and IG.Forms.HashAllControl.tabControl1_KeyUp().
helpToolStripMenuItem_Click() [1/2]
void IG.Forms.HashControl.helpToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.btnHelp_Click().
aboutToolStripMenuItem_Click() [1/2]
void IG.Forms.HashControl.aboutToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.btnAbout_Click().
contextMenuStrip1_Opening() [1/2]
void IG.Forms.HashControl.contextMenuStrip1_Opening (object sender, CancelEventArgs e) inline private
toolStripMenuItem1_Click() [1/2]
void IG.Forms.HashControl.toolStripMenuItem1_Click (object sender, EventArgs e) inline private
SetCursorMouseUp() [1/2]
void IG.Forms.HashControl.SetCursorMouseUp (object sender, MouseEventArgs e) inline private
Sets mouse cursor shape on MouseUp event, according to the current status of modifier keys.
Referenced by IG.Forms.HashControl.Common_MouseUp().
SetCursorMouseDown() [1/2]
void IG.Forms.HashControl.SetCursorMouseDown (object sender, MouseEventArgs e) inline private
Sets mouse cursor shape on MouseDown event, according to the current status of modifier keys.
References IG.Forms.HashControl.AltDown, IG.Forms.HashControl.ControlDown, and IG.Forms.HashControl.ShiftDown.
InitiateMoveOrSize() [1/2]
void IG.Forms.HashControl.InitiateMoveOrSize (object sender, MouseEventArgs e) inline private
References IG.Forms.HashControl._distMoveX, IG.Forms.HashControl._distMoveY, IG.Forms.HashControl._distSizeX, IG.Forms.HashControl._distSizeY, IG.Forms.HashControl._form, IG.Forms.HashControl._formInitialHeight, IG.Forms.HashControl._formInitialLeft, IG.Forms.HashControl._formInitialTop, IG.Forms.HashControl._formInitialWidth, IG.Forms.HashControl._isSizingOrMoving, IG.Forms.HashControl._mouseInitialLocalX, IG.Forms.HashControl._mouseInitialLocalY, IG.Forms.HashControl._mouseInitialRelX, IG.Forms.HashControl._mouseInitialRelY, IG.Forms.HashControl._mouseInitialX, IG.Forms.HashControl._mouseInitialY, IG.Forms.HashControl._mousePreviousX, IG.Forms.HashControl._mousePreviousY, IG.Forms.HashControl.ControlDown, IG.Forms.HashControl.MouseRelX, IG.Forms.HashControl.MouseRelY, IG.Forms.HashControl.MouseX, IG.Forms.HashControl.MouseY, and IG.Forms.HashControl.ShiftDown.
Referenced by IG.Forms.HashControl.Common_MouseDownOnInteractive(), and IG.Forms.HashControl.Common_MouseDownOnNoninteractiveControls().
Common_KeyDown() [1/2]
void IG.Forms.HashControl.Common_KeyDown (object sender, KeyEventArgs e) inline private
Common event handler for key down event, installed on all controls.
Referenced by IG.Forms.HashControl.SetCommonEvents().
Common_KeyUp() [1/2]
void IG.Forms.HashControl.Common_KeyUp (object sender, KeyEventArgs e) inline private
Common event handler for key up event, installed on all controls.
Parameters
sender
e
References IG.Forms.HashControl.KeyUpHandler().
Referenced by IG.Forms.HashControl.SetCommonEvents().
Common_MouseClick()
void IG.Forms.HashControl.Common_MouseClick (object sender, MouseEventArgs e) inline private
Handles mouse click events for the current control. Available on non-interactive controls of the current control.
References IG.Forms.HashControl.menuMain.
Referenced by IG.Forms.HashControl.SetCommonEvents().
Common_MouseDownOnInteractive() [1/2]
void IG.Forms.HashControl.Common_MouseDownOnInteractive (object sender, MouseEventArgs e) inline private
Initiates dragging or resizing by mouse on MouseDown event.
References IG.Forms.HashControl.AltDown, and IG.Forms.HashControl.InitiateMoveOrSize().
Referenced by IG.Forms.HashControl.SetCommonEvents().
Common_MouseDownOnNoninteractiveControls() [1/2]
void IG.Forms.HashControl.Common_MouseDownOnNoninteractiveControls (object sender, MouseEventArgs e) inline private
Enables dragging by mouse.
References IG.Forms.HashControl.InitiateMoveOrSize().
Referenced by IG.Forms.HashControl.SetCommonEvents().
Common_MouseUp() [1/2]
void IG.Forms.HashControl.Common_MouseUp (object sender, MouseEventArgs e) inline private
Enables dragging by mouse.
References IG.Forms.HashControl._isSizingOrMoving, and IG.Forms.HashControl.SetCursorMouseUp().
Referenced by IG.Forms.HashControl.SetCommonEvents().
Common_MouseMove() [1/2]
void IG.Forms.HashControl.Common_MouseMove (object sender, MouseEventArgs e) inline private
Enables dragging by mouse.
References IG.Forms.HashControl._distMoveX, IG.Forms.HashControl._distMoveY, IG.Forms.HashControl._distSizeX, IG.Forms.HashControl._distSizeY, IG.Forms.HashControl._form, IG.Forms.HashControl._formInitialHeight, IG.Forms.HashControl._formInitialLeft, IG.Forms.HashControl._formInitialTop, IG.Forms.HashControl._formInitialWidth, IG.Forms.HashControl._isSizingOrMoving, IG.Forms.HashControl._mousePreviousX, IG.Forms.HashControl._mousePreviousY, IG.Forms.HashControl.AltDown, IG.Forms.HashControl.ControlDown, IG.Forms.HashControl.MouseX, and IG.Forms.HashControl.MouseY.
Referenced by IG.Forms.HashControl.SetCommonEvents().
SetCommonEvents() [1/2]
void IG.Forms.HashControl.SetCommonEvents (Control control) inline private
This method is used to set the common event handlers for the current control and its subcontrols.
Parameters
control Control on which common event handlers are set.
References IG.Forms.HashControl.Common_KeyDown(), IG.Forms.HashControl.Common_KeyUp(), IG.Forms.HashControl.Common_MouseClick(), IG.Forms.HashControl.Common_MouseDownOnInteractive(), IG.Forms.HashControl.Common_MouseDownOnNoninteractiveControls(), IG.Forms.HashControl.Common_MouseMove(), IG.Forms.HashControl.Common_MouseUp(), IG.Forms.HashControl.txtContents, IG.Forms.HashControl.txtContents_DragDrop(), IG.Forms.HashControl.txtContents_DragEnter(), and IG.Forms.HashControl.txtFile.
Referenced by IG.Forms.HashControl.HashControl_Load().
HashControl_Load() [1/2]
void IG.Forms.HashControl.HashControl_Load (object sender, EventArgs e) inline private
References IG.Forms.ControlDelegate(), IG.Forms.UtilForms.RecursiveControlDelegate(), IG.Forms.HashControl.ReportError(), and IG.Forms.HashControl.SetCommonEvents().
helpToolStripMenuItem_Click_1()
void IG.Forms.HashControl.helpToolStripMenuItem_Click_1 (object sender, EventArgs e) inline private
References IG.Forms.HashControl.btnHelp_Click().
aboutToolStripMenuItem_Click_1()
void IG.Forms.HashControl.aboutToolStripMenuItem_Click_1 (object sender, EventArgs e) inline private
References IG.Forms.HashControl.btnAbout_Click().
Dispose() [1/4]
override void IG.Forms.HashControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.HashControl.components.
InitializeComponent() [1/4]
void IG.Forms.HashControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.HashControl.aboutToolStripMenuItem, IG.Forms.HashControl.backgroundWorker1, IG.Forms.HashControl.backgroundWorker1_DoWork(), IG.Forms.HashControl.backgroundWorker1_RunWorkerCompleted(), IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.HashControl.bthSha512, IG.Forms.HashControl.bthSha512_Click(), IG.Forms.HashControl.btnAbout, IG.Forms.HashControl.btnAbout_Click(), IG.Forms.HashControl.btnCancelCalculation, IG.Forms.HashControl.btnCancelCalculation_Click(), IG.Forms.HashControl.btnClearHashes, IG.Forms.HashControl.btnClearHashes_Click(), IG.Forms.HashControl.btnFileBrowse, IG.Forms.HashControl.btnFileBrowse_Click(), IG.Forms.HashControl.btnGenerate, IG.Forms.HashControl.btnGenerate_Click(), IG.Forms.HashControl.btnHelp, IG.Forms.HashControl.btnHelp_Click(), IG.Forms.HashControl.btnMd5Copy, IG.Forms.HashControl.btnMd5Copy_Click(), IG.Forms.HashControl.btnSha1Copy, IG.Forms.HashControl.btnSha1Copy_Click(), IG.Forms.HashControl.btnSha256Copy, IG.Forms.HashControl.btnSha256Copy_Click(), IG.Forms.HashControl.btnVerify, IG.Forms.HashControl.btnVerify_Click(), IG.Forms.HashControl.btnVerifyPaste, IG.Forms.HashControl.btnVerifyPaste_Click(), IG.Forms.HashControl.chkCalculateWhenTyping, IG.Forms.HashControl.chkCalculateWhenTyping_CheckedChanged(), IG.Forms.HashControl.chkGenerateFile, IG.Forms.HashControl.chkGenerateFile_CheckedChanged(), IG.Forms.HashControl.chkMd5, IG.Forms.HashControl.chkMd5_CheckedChanged(), IG.Forms.HashControl.chkSha1, IG.Forms.HashControl.chkSha1_CheckedChanged(), IG.Forms.HashControl.chkSha256, IG.Forms.HashControl.chkSha256_CheckedChanged(), IG.Forms.HashControl.chkSha512, IG.Forms.HashControl.chkSha512_CheckedChanged(), IG.Forms.HashControl.chkUpperCase, IG.Forms.HashControl.chkUpperCase_CheckedChanged(), IG.Forms.IndicatorLight.ColorLabel, IG.Forms.HashControl.components, IG.Forms.IndicatorLight.FlowDirection, IG.Forms.HashControl.grpHashGeneration, IG.Forms.HashControl.grpTextPreview, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.HashControl.helpToolStripMenuItem, IG.Forms.HashControl.indicatorLight1, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLight.LabelFont, IG.Forms.IndicatorLight.LabelText, IG.Forms.HashControl.lblFile, IG.Forms.HashControl.lblMd5, IG.Forms.HashControl.lblSha1, IG.Forms.HashControl.lblSha256, IG.Forms.HashControl.lblSha512, IG.Forms.HashControl.lblVerify, IG.Forms.HashControl.lvlVerifyMain, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.HashControl.menuMain, IG.Forms.HashControl.openFileDialog1, IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.HashControl.rbFile, IG.Forms.HashControl.rbFile_CheckedChanged(), IG.Forms.HashControl.rbText, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, IG.Forms.HashControl.txtContents, IG.Forms.HashControl.txtContents_DragDrop(), IG.Forms.HashControl.txtContents_DragEnter(), IG.Forms.HashControl.txtContents_Enter(), IG.Forms.HashControl.txtContents_KeyDown(), IG.Forms.HashControl.txtContents_KeyPress(), IG.Forms.HashControl.txtContents_MouseEnter(), IG.Forms.HashControl.txtContents_TextChanged(), IG.Forms.HashControl.txtContents_Validated(), IG.Forms.HashControl.txtFile, IG.Forms.HashControl.txtFile_DragDrop(), IG.Forms.HashControl.txtFile_DragEnter(), IG.Forms.HashControl.txtFile_Enter(), IG.Forms.HashControl.txtFile_KeyDown(), IG.Forms.HashControl.txtFile_MouseEnter(), IG.Forms.HashControl.txtFile_TextChanged(), IG.Forms.HashControl.txtFile_Validated(), IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, IG.Forms.HashControl.txtSha512, and IG.Forms.HashControl.txtVerify.
Referenced by IG.Forms.HashControl.HashControl().
ReportError() [2/4]
void IG.Forms.HashControl.ReportError (string errorMessage) inline
ReportWarning() [2/4]
void IG.Forms.HashControl.ReportWarning (string warningMessage) inline
ReportInfo() [2/4]
void IG.Forms.HashControl.ReportInfo (string message) inline
ClearHashes() [2/4]
void IG.Forms.HashControl.ClearHashes () inline protected
Clears all text fields with calculated hash values.
References IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, and IG.Forms.HashControl.txtSha512.
CalculateHashes() [2/4]
void IG.Forms.HashControl.CalculateHashes () inline protected
References IG.Forms.HashControl.chkGenerateFile, IG.Forms.HashControl.chkMd5, IG.Forms.HashControl.chkSha1, IG.Forms.HashControl.chkSha256, IG.Forms.HashControl.chkSha512, IG.Forms.HashControl.chkUpperCase, IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.FilePath, IG.Crypto.UtilCrypto.GetFileHashMd5Hex(), IG.Crypto.UtilCrypto.GetFileHashSha1Hex(), IG.Crypto.UtilCrypto.GetFileHashSha256Hex(), IG.Crypto.UtilCrypto.GetFileHashSha512Hex(), IG.Crypto.UtilCrypto.GetStringHashMd5Hex(), IG.Crypto.UtilCrypto.GetStringHashSha1Hex(), IG.Crypto.UtilCrypto.GetStringHashSha256Hex(), IG.Crypto.UtilCrypto.GetStringHashSha512Hex(), IG.Forms.HashControl.rbFile, IG.Forms.HashControl.ReportError(), IG.Forms.HashControl.SaveHashesToFile(), IG.Forms.HashControl.txtContents, IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, IG.Forms.HashControl.txtSha512, and IG.Forms.HashControl.txtVerify.
SaveHashesToFile() [2/4]
void IG.Forms.HashControl.SaveHashesToFile () inline protected
References IG.Forms.HashControl.FilePath, IG.Crypto.ConstCrypto.HashFileExtension, IG.Forms.HashControl.rbFile, IG.Forms.HashControl.ReportError(), IG.Forms.HashControl.ReportInfo(), IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, and IG.Forms.HashControl.txtSha512.
BrowseFile() [2/4]
void IG.Forms.HashControl.BrowseFile () inline protected
Browses for the file to be hashed.
References IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.DirectoryPath, IG.Forms.HashControl.fileDialog, IG.Forms.HashControl.FilePath, IG.Forms.HashControl.GenerateFilePreview(), IG.Forms.HashControl.rbFile, and IG.Forms.HashControl.txtFile.
GenerateFilePreview() [2/4]
void IG.Forms.HashControl.GenerateFilePreview () inline protected
Generates file preview in the text preview box if the rbFile is checked.
References IG.Forms.HashControl.ContentsFileBackColor, IG.Forms.HashControl.ContentsFileBinaryBackColor, IG.Forms.HashControl.ContentsFileForeColor, IG.Forms.HashControl.FilePath, IG.Lib.UtilSystem.IsTextFile(), IG.Forms.HashControl.NumCharsFilePreview, IG.Forms.HashControl.rbFile, and IG.Forms.HashControl.txtContents.
VerifyHash() [2/4]
void IG.Forms.HashControl.VerifyHash () inline protected
References IG.Crypto.UtilCrypto.CheckFileHashSupportedTypesHex(), IG.Crypto.UtilCrypto.CheckStringHashSupportedTypesHex(), IG.Forms.HashControl.FilePath, IG.Forms.HashControl.rbFile, IG.Forms.HashControl.rbText, IG.Forms.HashControl.ReportError(), IG.Forms.HashControl.ReportInfo(), IG.Forms.HashControl.txtContents, and IG.Forms.HashControl.txtVerify.
btnGenerate_Click() [2/4]
void IG.Forms.HashControl.btnGenerate_Click (object sender, EventArgs e) inline private
Requested hashs are generated and shown in the appropriate text boxes.
References IG.Forms.HashControl.CalculateHashes().
btnClearHashes_Click() [2/4]
void IG.Forms.HashControl.btnClearHashes_Click (object sender, EventArgs e) inline private
Hash values are cleared from the appropriate text fields.
References IG.Forms.HashControl.ClearHashes().
btnVerify_Click() [2/4]
void IG.Forms.HashControl.btnVerify_Click (object sender, EventArgs e) inline private
Hash value is verified for the specified file or text.
References IG.Forms.HashControl.VerifyHash().
txtFile_Validated() [2/4]
void IG.Forms.HashControl.txtFile_Validated (object sender, EventArgs e) inline private
After file has been validated.
References IG.Forms.HashControl._skipFileValidationEvent, IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.FilePath, IG.Forms.HashControl.FileTextBoxInitialized, IG.Forms.HashControl.GenerateFilePreview(), IG.Forms.HashControl.rbFile, and IG.Forms.HashControl.txtFile.
btnFileBrowse_Click() [2/4]
void IG.Forms.HashControl.btnFileBrowse_Click (object sender, EventArgs e) inline private
Browses for the file whose hash values will be calculated.
References IG.Forms.HashControl.BrowseFile(), IG.Forms.HashControl.FilePath, and IG.Forms.HashControl.rbFile.
chkMd5_CheckedChanged() [2/4]
void IG.Forms.HashControl.chkMd5_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkMd5, and IG.Forms.HashControl.txtMd5.
chkSha1_CheckedChanged() [2/4]
void IG.Forms.HashControl.chkSha1_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkSha1, and IG.Forms.HashControl.txtSha1.
chkSha256_CheckedChanged() [2/4]
void IG.Forms.HashControl.chkSha256_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkSha256, and IG.Forms.HashControl.txtSha256.
chkSha512_CheckedChanged() [2/4]
void IG.Forms.HashControl.chkSha512_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkSha512, and IG.Forms.HashControl.txtSha512.
btnMd5Copy_Click() [2/4]
void IG.Forms.HashControl.btnMd5Copy_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.txtMd5.
btnSha1Copy_Click() [2/4]
void IG.Forms.HashControl.btnSha1Copy_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.txtSha1.
btnSha256Copy_Click() [2/4]
void IG.Forms.HashControl.btnSha256Copy_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.txtSha256.
bthSha512_Click() [2/4]
void IG.Forms.HashControl.bthSha512_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.txtSha512.
btnVerifyPaste_Click() [2/4]
void IG.Forms.HashControl.btnVerifyPaste_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.txtVerify.
rbFile_CheckedChanged() [2/4]
void IG.Forms.HashControl.rbFile_CheckedChanged (object sender, EventArgs e) inline private
Handles things that need to be done when we switch between hashing the file or hashing text from the textbox.
References IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.ContentsFileBackColor, IG.Forms.HashControl.ContentsFileForeColor, IG.Forms.HashControl.ContentsTextBackColor, IG.Forms.HashControl.ContentsTextForeColor, IG.Forms.HashControl.FileOffForeColor, IG.Forms.HashControl.FileOnForeColor, IG.Forms.HashControl.FilePath, IG.Forms.HashControl.GenerateFilePreview(), IG.Forms.HashControl.grpTextPreview, IG.Forms.HashControl.MaxInsertTextInfo, IG.Forms.HashControl.NumInsertTextInfo, IG.Forms.HashControl.rbFile, IG.Forms.HashControl.ReportInfo(), IG.Forms.HashControl.TextBeingDropped, IG.Forms.HashControl.txtContents, and IG.Forms.HashControl.txtFile.
chkGenerateFile_CheckedChanged() [2/4]
void IG.Forms.HashControl.chkGenerateFile_CheckedChanged (object sender, EventArgs e) inline private
Handles situation when one changes the setting whether to store file's hash values to a file. If the check box gets checked then hashes are immediately saved to a file.
References IG.Forms.HashControl.chkGenerateFile, and IG.Forms.HashControl.SaveHashesToFile().
txtContents_Enter() [2/4]
void IG.Forms.HashControl.txtContents_Enter (object sender, EventArgs e) inline private
References IG.Forms.HashControl.ContentsTextBoxInitialized, and IG.Forms.HashControl.txtContents.
txtContents_MouseEnter() [2/4]
void IG.Forms.HashControl.txtContents_MouseEnter (object sender, EventArgs e) inline private
References IG.Forms.HashControl.ContentsTextBoxInitialized, and IG.Forms.HashControl.txtContents.
txtContents_TextChanged() [2/4]
void IG.Forms.HashControl.txtContents_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.ContentsTextBoxInitialized.
txtContents_Validated() [2/4]
void IG.Forms.HashControl.txtContents_Validated (object sender, EventArgs e) inline private
After text is inserted, calculate appropriate hashes immediately.
References IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.ContentsTextBoxInitialized, and IG.Forms.HashControl.rbText.
chkUpperCase_CheckedChanged() [2/4]
void IG.Forms.HashControl.chkUpperCase_CheckedChanged (object sender, EventArgs e) inline private
Recalculates hashes because the requested lower/upper case form has changed.
References IG.Forms.HashControl.CalculateHashes().
txtFile_Enter() [2/4]
void IG.Forms.HashControl.txtFile_Enter (object sender, EventArgs e) inline private
References IG.Forms.HashControl.FileTextBoxInitialized, and IG.Forms.HashControl.txtFile.
txtFile_MouseEnter() [2/4]
void IG.Forms.HashControl.txtFile_MouseEnter (object sender, EventArgs e) inline private
References IG.Forms.HashControl.FileTextBoxInitialized, and IG.Forms.HashControl.txtFile.
txtFile_TextChanged() [2/4]
void IG.Forms.HashControl.txtFile_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.FileTextBoxInitialized.
txtFile_DragEnter() [2/4]
void IG.Forms.HashControl.txtFile_DragEnter (object sender, DragEventArgs e) inline private
txtFile_DragDrop() [2/4]
void IG.Forms.HashControl.txtFile_DragDrop (object sender, DragEventArgs e) inline private
References IG.Forms.HashControl.rbFile, IG.Forms.HashControl.txtFile, and IG.Forms.HashControl.txtFile_Validated().
txtContents_DragEnter() [2/4]
void IG.Forms.HashControl.txtContents_DragEnter (object sender, DragEventArgs e) inline private
txtContents_DragDrop() [2/4]
void IG.Forms.HashControl.txtContents_DragDrop (object sender, DragEventArgs e) inline private
References IG.Forms.HashControl.rbFile, IG.Forms.HashControl.rbText, IG.Forms.HashControl.TextBeingDropped, IG.Forms.HashControl.txtContents, IG.Forms.HashControl.txtContents_Validated(), IG.Forms.HashControl.txtFile, and IG.Forms.HashControl.txtFile_Validated().
Handle_CtrlA_CtrlBackspace() [2/4]
void IG.Forms.HashControl.Handle_CtrlA_CtrlBackspace (TextBox textBox, object sender, KeyEventArgs e) inline protected
Handle the Ctrl-A (select all) and Ctrl-Backspace events for the specified text box.
Parameters
textBox Text box for wich the event is handled.
txtFile_KeyDown() [2/4]
void IG.Forms.HashControl.txtFile_KeyDown (object sender, KeyEventArgs e) inline private
References IG.Forms.HashControl.Handle_CtrlA_CtrlBackspace(), and IG.Forms.HashControl.txtFile.
txtContents_KeyDown() [2/4]
void IG.Forms.HashControl.txtContents_KeyDown (object sender, KeyEventArgs e) inline private
References IG.Forms.HashControl.Handle_CtrlA_CtrlBackspace(), and IG.Forms.HashControl.txtContents.
Dispose() [2/4]
override void IG.Forms.HashControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.HashControl.components.
InitializeComponent() [2/4]
void IG.Forms.HashControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.HashControl.bthSha512, IG.Forms.HashControl.bthSha512_Click(), IG.Forms.HashControl.btnClearHashes, IG.Forms.HashControl.btnClearHashes_Click(), IG.Forms.HashControl.btnFileBrowse, IG.Forms.HashControl.btnFileBrowse_Click(), IG.Forms.HashControl.btnGenerate, IG.Forms.HashControl.btnGenerate_Click(), IG.Forms.HashControl.btnMd5Copy, IG.Forms.HashControl.btnMd5Copy_Click(), IG.Forms.HashControl.btnSha1Copy, IG.Forms.HashControl.btnSha1Copy_Click(), IG.Forms.HashControl.btnSha256Copy, IG.Forms.HashControl.btnSha256Copy_Click(), IG.Forms.HashControl.btnVerify, IG.Forms.HashControl.btnVerify_Click(), IG.Forms.HashControl.btnVerifyPaste, IG.Forms.HashControl.btnVerifyPaste_Click(), IG.Forms.HashControl.chkGenerateFile, IG.Forms.HashControl.chkGenerateFile_CheckedChanged(), IG.Forms.HashControl.chkMd5, IG.Forms.HashControl.chkMd5_CheckedChanged(), IG.Forms.HashControl.chkSha1, IG.Forms.HashControl.chkSha1_CheckedChanged(), IG.Forms.HashControl.chkSha256, IG.Forms.HashControl.chkSha256_CheckedChanged(), IG.Forms.HashControl.chkSha512, IG.Forms.HashControl.chkSha512_CheckedChanged(), IG.Forms.HashControl.chkUpperCase, IG.Forms.HashControl.chkUpperCase_CheckedChanged(), IG.Forms.HashControl.grpHashGeneration, IG.Forms.HashControl.grpTextPreview, IG.Forms.HashControl.lblFile, IG.Forms.HashControl.lblMd5, IG.Forms.HashControl.lblSha1, IG.Forms.HashControl.lblSha256, IG.Forms.HashControl.lblSha512, IG.Forms.HashControl.lblVerify, IG.Forms.HashControl.lvlVerifyMain, IG.Forms.HashControl.openFileDialog1, IG.Forms.HashControl.rbFile, IG.Forms.HashControl.rbFile_CheckedChanged(), IG.Forms.HashControl.rbText, IG.Forms.HashControl.txtContents, IG.Forms.HashControl.txtContents_DragDrop(), IG.Forms.HashControl.txtContents_DragEnter(), IG.Forms.HashControl.txtContents_Enter(), IG.Forms.HashControl.txtContents_KeyDown(), IG.Forms.HashControl.txtContents_MouseEnter(), IG.Forms.HashControl.txtContents_TextChanged(), IG.Forms.HashControl.txtContents_Validated(), IG.Forms.HashControl.txtFile, IG.Forms.HashControl.txtFile_DragDrop(), IG.Forms.HashControl.txtFile_DragEnter(), IG.Forms.HashControl.txtFile_Enter(), IG.Forms.HashControl.txtFile_KeyDown(), IG.Forms.HashControl.txtFile_MouseEnter(), IG.Forms.HashControl.txtFile_TextChanged(), IG.Forms.HashControl.txtFile_Validated(), IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, IG.Forms.HashControl.txtSha512, and IG.Forms.HashControl.txtVerify.
SetGeneralProperties() [2/3]
void IG.Forms.HashControl.SetGeneralProperties (FadingMessage fmsg) inline protected
References IG.Forms.FadingMessage.BackGroundColor, IG.Forms.FadingMessage.DefaultBackGroundColor, IG.Forms.FadingMessage.IsTopMostWindow, IG.Forms.FadingMessage.LaunchedAtMouseCursor, and IG.Forms.FadingMessage.LaunchedInParallelThread.
FadingMessageInfo() [2/3]
void IG.Forms.HashControl.FadingMessageInfo (string message, int showTimeMs = 0) inline
References IG.Forms.HashControl._fadingMessageInfoColor, IG.Forms.FadingMessage.BackGroundColor, IG.Forms.HashControl.FadingMessageShowTimeMs, IG.Lib.UtilSystem.IsWindowsOs, and IG.Forms.HashControl.SetGeneralProperties().
FadingMessageWarning() [2/3]
void IG.Forms.HashControl.FadingMessageWarning (string message, int showTimeMs = 0) inline
References IG.Forms.HashControl._fadingMessageWarningColor, IG.Forms.FadingMessage.BackGroundColor, IG.Forms.HashControl.FadingMessageShowTimeMs, IG.Lib.UtilSystem.IsWindowsOs, and IG.Forms.HashControl.SetGeneralProperties().
FadingMessageError() [2/3]
void IG.Forms.HashControl.FadingMessageError (string message, int showTimeMs = 0) inline
References IG.Forms.HashControl._fadingMessageErrorColor, IG.Forms.FadingMessage.BackGroundColor, IG.Forms.HashControl.FadingMessageShowTimeMs, IG.Lib.UtilSystem.IsWindowsOs, and IG.Forms.HashControl.SetGeneralProperties().
ReportError() [3/4]
void IG.Forms.HashControl.ReportError (string errorMessage) inline
ReportWarning() [3/4]
void IG.Forms.HashControl.ReportWarning (string warningMessage) inline
ReportInfo() [3/4]
void IG.Forms.HashControl.ReportInfo (string message) inline
ClearHashes() [3/4]
void IG.Forms.HashControl.ClearHashes () inline protected
Clears all text fields with calculated hash values.
References IG.Forms.AbortableBackgroundWorker.Abort(), IG.Forms.HashControl.backgroundWorker1, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.RecalculateHashes, IG.Forms.IndicatorLight.SetOff(), IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, and IG.Forms.HashControl.txtSha512.
DisableActionButtons() [2/3]
void IG.Forms.HashControl.DisableActionButtons () inline protected
References IG.Forms.HashControl.btnGenerate, and IG.Forms.HashControl.btnVerify.
EnableActionButtons() [2/3]
void IG.Forms.HashControl.EnableActionButtons () inline protected
References IG.Forms.HashControl.btnGenerate, and IG.Forms.HashControl.btnVerify.
backgroundWorker1_DoWork() [2/3]
void IG.Forms.HashControl.backgroundWorker1_DoWork (object sender, DoWorkEventArgs e) inline private
Calculates (in background) the required hash (specified in Argument property event arguments) as HashJobArgumentsAndResults.
Parameters
sender Originaror of event that runs this event handler.
e Event arguments, contain the necessary information about how to calculate the hash.
References IG.Forms.HashControl.FilePath, IG.Crypto.UtilCrypto.GetFileHashMd5Hex(), IG.Crypto.UtilCrypto.GetFileHashSha1Hex(), IG.Crypto.UtilCrypto.GetFileHashSha256Hex(), IG.Crypto.UtilCrypto.GetFileHashSha512Hex(), IG.Crypto.UtilCrypto.GetStringHashMd5Hex(), IG.Crypto.UtilCrypto.GetStringHashSha1Hex(), IG.Crypto.UtilCrypto.GetStringHashSha256Hex(), IG.Crypto.UtilCrypto.GetStringHashSha512Hex(), and IG.Forms.HashControl.LastArguments.
backgroundWorker1_RunWorkerCompleted() [2/3]
void IG.Forms.HashControl.backgroundWorker1_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.HashControl.btnCancelCalculation, IG.Forms.HashControl.chkUpperCase, IG.Forms.HashControl.EnableActionButtons(), IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.IsAllHashesCalculated, IG.Forms.HashControl.LastResults, IG.Forms.IndicatorLight.SetOff(), IG.Forms.IndicatorLight.SetOk(), IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, and IG.Forms.HashControl.txtSha512.
CalculateHashAsync() [2/3]
void IG.Forms.HashControl.CalculateHashAsync (HashType hashType) inline protected
References IG.Forms.HashControl.backgroundWorker1, IG.Forms.HashControl.btnCancelCalculation, IG.Forms.HashControl.CalculateAllCanceled, IG.Forms.HashControl.DisableActionButtons(), IG.Forms.HashControl.FilePath, IG.Forms.HashControl.GetFileOrTextLength(), IG.Forms.HashControl.indicatorLight1, IG.Lib.UtilSystem.IsReadableFile(), IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.rbFile, IG.Forms.HashControl.ReportError(), IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetError(), and IG.Forms.HashControl.txtContents.
LoopWhileBusy() [2/3]
void IG.Forms.HashControl.LoopWhileBusy () inline protected
References IG.Forms.HashControl.backgroundWorker1.
GetFileOrTextLength() [2/3]
long IG.Forms.HashControl.GetFileOrTextLength () inline protected
References IG.Forms.HashControl.FilePath, IG.Forms.HashControl.rbFile, and IG.Forms.HashControl.txtContents.
CancelHashCalculations() [2/3]
void IG.Forms.HashControl.CancelHashCalculations () inline protected
References IG.Forms.AbortableBackgroundWorker.Abort(), IG.Forms.HashControl.backgroundWorker1, IG.Forms.HashControl.CalculateAllCanceled, IG.Forms.HashControl.FadingMessageInfo(), IG.Forms.HashControl.FadingMessageShowTimeMs, and IG.Forms.HashControl.FadingMessageWarning().
CalculateHashes() [3/4]
void IG.Forms.HashControl.CalculateHashes () inline protected
Re-calculates all hashes that are checked for calculation.
References IG.Forms.HashControl.backgroundWorker1, IG.Forms.IndicatorLight.BlinkError(), IG.Forms.HashControl.CalculateAllCanceled, IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.CancelHashCalculations(), IG.Forms.HashControl.chkCalculateWhenTyping, IG.Forms.HashControl.chkGenerateFile, IG.Forms.HashControl.chkMd5, IG.Forms.HashControl.chkSha1, IG.Forms.HashControl.chkSha256, IG.Forms.HashControl.chkSha512, IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.EnableActionButtons(), IG.Forms.HashControl.FadingMessageError(), IG.Forms.HashControl.GetFileOrTextLength(), IG.Forms.HashControl.HashJobArgumentsAndResults.HashedLength, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.IsGroupCalculationPerformed, IG.Forms.HashControl.LastArguments, IG.Forms.HashControl.LastResults, IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.rbText, IG.Forms.HashControl.RecalculateHashes, IG.Forms.HashControl.ReportError(), IG.Forms.HashControl.SaveHashesToFile(), IG.Forms.IndicatorLight.SetError(), and IG.Forms.HashControl.txtVerify.
SaveHashesToFile() [3/4]
void IG.Forms.HashControl.SaveHashesToFile () inline protected
References IG.Forms.HashControl.FilePath, IG.Crypto.ConstCrypto.HashFileExtension, IG.Forms.HashControl.rbFile, IG.Forms.HashControl.ReportError(), IG.Forms.HashControl.ReportInfo(), IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, and IG.Forms.HashControl.txtSha512.
BrowseFile() [3/4]
void IG.Forms.HashControl.BrowseFile () inline protected
Browses for the file to be hashed.
References IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.DirectoryPath, IG.Forms.HashControl.fileDialog, IG.Forms.HashControl.FilePath, IG.Forms.HashControl.GenerateFilePreview(), IG.Forms.HashControl.rbFile, and IG.Forms.HashControl.txtFile.
GenerateFilePreview() [3/4]
void IG.Forms.HashControl.GenerateFilePreview () inline protected
Generates file preview in the text preview box if the rbFile is checked.
References IG.Forms.HashControl.ContentsFileBackColor, IG.Forms.HashControl.ContentsFileBinaryBackColor, IG.Forms.HashControl.ContentsFileForeColor, IG.Forms.HashControl.FilePath, IG.Lib.UtilSystem.IsTextFile(), IG.Forms.HashControl.NumCharsFilePreview, IG.Forms.HashControl.rbFile, and IG.Forms.HashControl.txtContents.
VerifyHash() [3/4]
void IG.Forms.HashControl.VerifyHash () inline protected
References IG.Lib.Util.AreHexStringsEqual(), IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.FilePath, IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.rbFile, IG.Forms.HashControl.ReportError(), IG.Forms.HashControl.ReportInfo(), IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, IG.Forms.HashControl.txtSha512, and IG.Forms.HashControl.txtVerify.
btnGenerate_Click() [3/4]
void IG.Forms.HashControl.btnGenerate_Click (object sender, EventArgs e) inline private
Requested hashs are generated and shown in the appropriate text boxes.
References IG.Forms.HashControl.CalculateHashes().
btnClearHashes_Click() [3/4]
void IG.Forms.HashControl.btnClearHashes_Click (object sender, EventArgs e) inline private
Hash values are cleared from the appropriate text fields.
References IG.Forms.HashControl.ClearHashes().
btnVerify_Click() [3/4]
void IG.Forms.HashControl.btnVerify_Click (object sender, EventArgs e) inline private
Hash value is verified for the specified file or text.
References IG.Forms.HashControl.VerifyHash().
txtFile_Validated() [3/4]
void IG.Forms.HashControl.txtFile_Validated (object sender, EventArgs e) inline private
After file has been validated.
References IG.Forms.HashControl._skipFileValidationEvent, IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.FilePath, IG.Forms.HashControl.FileTextBoxInitialized, IG.Forms.HashControl.GenerateFilePreview(), IG.Forms.HashControl.rbFile, and IG.Forms.HashControl.txtFile.
btnFileBrowse_Click() [3/4]
void IG.Forms.HashControl.btnFileBrowse_Click (object sender, EventArgs e) inline private
Browses for the file whose hash values will be calculated.
References IG.Forms.HashControl.BrowseFile(), IG.Forms.HashControl.FilePath, and IG.Forms.HashControl.rbFile.
chkMd5_CheckedChanged() [3/4]
void IG.Forms.HashControl.chkMd5_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.chkMd5, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.IsAllHashesCalculated, IG.Forms.IndicatorLight.SetOk(), and IG.Forms.HashControl.txtMd5.
chkSha1_CheckedChanged() [3/4]
void IG.Forms.HashControl.chkSha1_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.chkSha1, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.IsAllHashesCalculated, IG.Forms.IndicatorLight.SetOk(), and IG.Forms.HashControl.txtSha1.
chkSha256_CheckedChanged() [3/4]
void IG.Forms.HashControl.chkSha256_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.chkSha256, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.IsAllHashesCalculated, IG.Forms.IndicatorLight.SetOk(), and IG.Forms.HashControl.txtSha256.
chkSha512_CheckedChanged() [3/4]
void IG.Forms.HashControl.chkSha512_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.chkSha512, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.IsAllHashesCalculated, IG.Forms.IndicatorLight.SetOk(), and IG.Forms.HashControl.txtSha512.
btnMd5Copy_Click() [3/4]
void IG.Forms.HashControl.btnMd5Copy_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.ReportError(), and IG.Forms.HashControl.txtMd5.
btnSha1Copy_Click() [3/4]
void IG.Forms.HashControl.btnSha1Copy_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.ReportError(), and IG.Forms.HashControl.txtSha1.
btnSha256Copy_Click() [3/4]
void IG.Forms.HashControl.btnSha256Copy_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.ReportError(), and IG.Forms.HashControl.txtSha256.
bthSha512_Click() [3/4]
void IG.Forms.HashControl.bthSha512_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.ReportError(), and IG.Forms.HashControl.txtSha512.
btnVerifyPaste_Click() [3/4]
void IG.Forms.HashControl.btnVerifyPaste_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.txtVerify.
rbFile_CheckedChanged() [3/4]
void IG.Forms.HashControl.rbFile_CheckedChanged (object sender, EventArgs e) inline private
Handles things that need to be done when we switch between hashing the file or hashing text from the textbox.
References IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkCalculateWhenTyping, IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.ContentsFileBackColor, IG.Forms.HashControl.ContentsFileForeColor, IG.Forms.HashControl.ContentsTextBackColor, IG.Forms.HashControl.ContentsTextForeColor, IG.Forms.HashControl.FadingMessageInfo(), IG.Forms.HashControl.FileOffForeColor, IG.Forms.HashControl.FileOnForeColor, IG.Forms.HashControl.FilePath, IG.Forms.HashControl.GenerateFilePreview(), IG.Forms.HashControl.grpTextPreview, IG.Forms.HashControl.MaxInsertTextInfo, IG.Forms.HashControl.NumInsertTextInfo, IG.Forms.HashControl.rbFile, IG.Forms.HashControl.RecalculateHashes, IG.Forms.HashControl.txtContents, and IG.Forms.HashControl.txtFile.
chkGenerateFile_CheckedChanged() [3/4]
void IG.Forms.HashControl.chkGenerateFile_CheckedChanged (object sender, EventArgs e) inline private
Handles situation when one changes the setting whether to store file's hash values to a file. If the check box gets checked then hashes are immediately saved to a file.
References IG.Forms.HashControl.chkGenerateFile, and IG.Forms.HashControl.SaveHashesToFile().
txtContents_Enter() [3/4]
void IG.Forms.HashControl.txtContents_Enter (object sender, EventArgs e) inline private
References IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.ContentsTextBoxInitialized, IG.Forms.HashControl.rbFile, and IG.Forms.HashControl.txtContents.
txtContents_MouseEnter() [3/4]
void IG.Forms.HashControl.txtContents_MouseEnter (object sender, EventArgs e) inline private
References IG.Forms.HashControl.ContentsTextBoxInitialized, and IG.Forms.HashControl.txtContents.
txtContents_TextChanged() [3/4]
void IG.Forms.HashControl.txtContents_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkCalculateWhenTyping, IG.Forms.HashControl.ContentsTextBoxInitialized, IG.Forms.HashControl.IsGroupCalculationPerformed, IG.Forms.HashControl.rbText, and IG.Forms.HashControl.RecalculateHashes.
txtContents_Validated() [3/4]
void IG.Forms.HashControl.txtContents_Validated (object sender, EventArgs e) inline private
After text is inserted, calculate appropriate hashes immediately.
References IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.ContentsTextBoxInitialized, and IG.Forms.HashControl.rbText.
txtContents_KeyPress() [2/3]
void IG.Forms.HashControl.txtContents_KeyPress (object sender, KeyPressEventArgs e) inline private
chkUpperCase_CheckedChanged() [3/4]
void IG.Forms.HashControl.chkUpperCase_CheckedChanged (object sender, EventArgs e) inline private
Recalculates hashes because the requested lower/upper case form has changed.
References IG.Forms.HashControl.chkUpperCase, IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, and IG.Forms.HashControl.txtSha512.
txtFile_Enter() [3/4]
void IG.Forms.HashControl.txtFile_Enter (object sender, EventArgs e) inline private
References IG.Forms.HashControl.FileTextBoxInitialized, and IG.Forms.HashControl.txtFile.
txtFile_MouseEnter() [3/4]
void IG.Forms.HashControl.txtFile_MouseEnter (object sender, EventArgs e) inline private
References IG.Forms.HashControl.FileTextBoxInitialized, and IG.Forms.HashControl.txtFile.
txtFile_TextChanged() [3/4]
void IG.Forms.HashControl.txtFile_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.FileTextBoxInitialized.
txtFile_DragEnter() [3/4]
void IG.Forms.HashControl.txtFile_DragEnter (object sender, DragEventArgs e) inline private
txtFile_DragDrop() [3/4]
void IG.Forms.HashControl.txtFile_DragDrop (object sender, DragEventArgs e) inline private
References IG.Forms.HashControl.FilePath, IG.Forms.HashControl.rbFile, IG.Forms.HashControl.txtFile, and IG.Forms.HashControl.txtFile_Validated().
txtContents_DragEnter() [3/4]
void IG.Forms.HashControl.txtContents_DragEnter (object sender, DragEventArgs e) inline private
txtContents_DragDrop() [3/4]
void IG.Forms.HashControl.txtContents_DragDrop (object sender, DragEventArgs e) inline private
References IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.FilePath, IG.Forms.HashControl.rbFile, IG.Forms.HashControl.rbText, IG.Forms.HashControl.TextBeingDropped, IG.Forms.HashControl.txtContents, IG.Forms.HashControl.txtContents_Validated(), IG.Forms.HashControl.txtFile, and IG.Forms.HashControl.txtFile_Validated().
Handle_CtrlA_CtrlBackspace() [3/4]
void IG.Forms.HashControl.Handle_CtrlA_CtrlBackspace (TextBox textBox, object sender, KeyEventArgs e) inline protected
Handle the Ctrl-A (select all) and Ctrl-Backspace events for the specified text box.
Parameters
textBox Text box for wich the event is handled.
txtFile_KeyDown() [3/4]
void IG.Forms.HashControl.txtFile_KeyDown (object sender, KeyEventArgs e) inline private
References IG.Forms.HashControl.Handle_CtrlA_CtrlBackspace(), and IG.Forms.HashControl.txtFile.
txtContents_KeyDown() [3/4]
void IG.Forms.HashControl.txtContents_KeyDown (object sender, KeyEventArgs e) inline private
References IG.Forms.HashControl.Handle_CtrlA_CtrlBackspace(), and IG.Forms.HashControl.txtContents.
btnAbout_Click() [2/3]
void IG.Forms.HashControl.btnAbout_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl._aboutForm.
btnCancelCalculation_Click() [2/3]
void IG.Forms.HashControl.btnCancelCalculation_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CancelHashCalculations().
btnInfo_Click() [1/2]
void IG.Forms.HashControl.btnInfo_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl._aboutForm, IG.Forms.HashAboutControl.HelpPdf(), and IG.Forms.HashAboutForm.MainControl.
Referenced by IG.Forms.HashControl.helpToolStripMenuItem_Click(), IG.Forms.HashControl.InitializeComponent(), and IG.Forms.HashControl.KeyUpHandler().
chkCalculateWhenTyping_CheckedChanged() [2/3]
void IG.Forms.HashControl.chkCalculateWhenTyping_CheckedChanged (object sender, EventArgs e) inline private
HashControl_KeyUp() [2/3]
void IG.Forms.HashControl.HashControl_KeyUp (object sender, KeyEventArgs e) inline private
Parameters
sender
e
References IG.Forms.HashControl.KeyUpHandler().
KeyUpHandler() [2/3]
void IG.Forms.HashControl.KeyUpHandler (object sender, KeyEventArgs e) inline
Handles key up events for the current form.
Form does not catch the KeyUp events. Therefore, the event handler code was moved to a public function, which can be called from a form, tab control, or other control that contains this control.
References IG.Forms.HashControl.btnAbout_Click(), and IG.Forms.HashControl.btnInfo_Click().
Dispose() [3/4]
override void IG.Forms.HashControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.HashControl.components.
InitializeComponent() [3/4]
void IG.Forms.HashControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.HashControl.backgroundWorker1, IG.Forms.HashControl.backgroundWorker1_DoWork(), IG.Forms.HashControl.backgroundWorker1_RunWorkerCompleted(), IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.HashControl.bthSha512, IG.Forms.HashControl.bthSha512_Click(), IG.Forms.HashControl.btnAbout, IG.Forms.HashControl.btnAbout_Click(), IG.Forms.HashControl.btnCancelCalculation, IG.Forms.HashControl.btnCancelCalculation_Click(), IG.Forms.HashControl.btnClearHashes, IG.Forms.HashControl.btnClearHashes_Click(), IG.Forms.HashControl.btnFileBrowse, IG.Forms.HashControl.btnFileBrowse_Click(), IG.Forms.HashControl.btnGenerate, IG.Forms.HashControl.btnGenerate_Click(), IG.Forms.HashControl.btnInfo, IG.Forms.HashControl.btnInfo_Click(), IG.Forms.HashControl.btnMd5Copy, IG.Forms.HashControl.btnMd5Copy_Click(), IG.Forms.HashControl.btnSha1Copy, IG.Forms.HashControl.btnSha1Copy_Click(), IG.Forms.HashControl.btnSha256Copy, IG.Forms.HashControl.btnSha256Copy_Click(), IG.Forms.HashControl.btnVerify, IG.Forms.HashControl.btnVerify_Click(), IG.Forms.HashControl.btnVerifyPaste, IG.Forms.HashControl.btnVerifyPaste_Click(), IG.Forms.HashControl.chkCalculateWhenTyping, IG.Forms.HashControl.chkCalculateWhenTyping_CheckedChanged(), IG.Forms.HashControl.chkGenerateFile, IG.Forms.HashControl.chkGenerateFile_CheckedChanged(), IG.Forms.HashControl.chkMd5, IG.Forms.HashControl.chkMd5_CheckedChanged(), IG.Forms.HashControl.chkSha1, IG.Forms.HashControl.chkSha1_CheckedChanged(), IG.Forms.HashControl.chkSha256, IG.Forms.HashControl.chkSha256_CheckedChanged(), IG.Forms.HashControl.chkSha512, IG.Forms.HashControl.chkSha512_CheckedChanged(), IG.Forms.HashControl.chkUpperCase, IG.Forms.HashControl.chkUpperCase_CheckedChanged(), IG.Forms.IndicatorLight.ColorLabel, IG.Forms.IndicatorLight.FlowDirection, IG.Forms.HashControl.grpHashGeneration, IG.Forms.HashControl.grpTextPreview, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.HashControl.HashControl_KeyUp(), IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.HashControl.indicatorLight1, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLight.LabelFont, IG.Forms.IndicatorLight.LabelText, IG.Forms.HashControl.lblFile, IG.Forms.HashControl.lblMd5, IG.Forms.HashControl.lblSha1, IG.Forms.HashControl.lblSha256, IG.Forms.HashControl.lblSha512, IG.Forms.HashControl.lblVerify, IG.Forms.HashControl.lvlVerifyMain, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.HashControl.openFileDialog1, IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.HashControl.rbFile, IG.Forms.HashControl.rbFile_CheckedChanged(), IG.Forms.HashControl.rbText, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, IG.Forms.HashControl.txtContents, IG.Forms.HashControl.txtContents_DragDrop(), IG.Forms.HashControl.txtContents_DragEnter(), IG.Forms.HashControl.txtContents_Enter(), IG.Forms.HashControl.txtContents_KeyDown(), IG.Forms.HashControl.txtContents_KeyPress(), IG.Forms.HashControl.txtContents_MouseEnter(), IG.Forms.HashControl.txtContents_TextChanged(), IG.Forms.HashControl.txtContents_Validated(), IG.Forms.HashControl.txtFile, IG.Forms.HashControl.txtFile_DragDrop(), IG.Forms.HashControl.txtFile_DragEnter(), IG.Forms.HashControl.txtFile_Enter(), IG.Forms.HashControl.txtFile_KeyDown(), IG.Forms.HashControl.txtFile_MouseEnter(), IG.Forms.HashControl.txtFile_TextChanged(), IG.Forms.HashControl.txtFile_Validated(), IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, IG.Forms.HashControl.txtSha512, and IG.Forms.HashControl.txtVerify.
SetGeneralProperties() [3/3]
void IG.Forms.HashControl.SetGeneralProperties (FadingMessage fmsg) inline protected
References IG.Forms.FadingMessage.BackGroundColor, IG.Forms.FadingMessage.DefaultBackGroundColor, IG.Forms.FadingMessage.IsTopMostWindow, IG.Forms.FadingMessage.LaunchedAtMouseCursor, and IG.Forms.FadingMessage.LaunchedInParallelThread.
FadingMessageInfo() [3/3]
void IG.Forms.HashControl.FadingMessageInfo (string message, int showTimeMs = 0) inline
References IG.Forms.HashControl._fadingMessageInfoColor, IG.Forms.FadingMessage.BackGroundColor, IG.Forms.HashControl.FadingMessageShowTimeMs, IG.Lib.UtilSystem.IsWindowsOs, and IG.Forms.HashControl.SetGeneralProperties().
FadingMessageWarning() [3/3]
void IG.Forms.HashControl.FadingMessageWarning (string message, int showTimeMs = 0) inline
References IG.Forms.HashControl._fadingMessageWarningColor, IG.Forms.FadingMessage.BackGroundColor, IG.Forms.HashControl.FadingMessageShowTimeMs, IG.Lib.UtilSystem.IsWindowsOs, and IG.Forms.HashControl.SetGeneralProperties().
FadingMessageError() [3/3]
void IG.Forms.HashControl.FadingMessageError (string message, int showTimeMs = 0) inline
References IG.Forms.HashControl._fadingMessageErrorColor, IG.Forms.FadingMessage.BackGroundColor, IG.Forms.HashControl.FadingMessageShowTimeMs, IG.Lib.UtilSystem.IsWindowsOs, and IG.Forms.HashControl.SetGeneralProperties().
ReportError() [4/4]
void IG.Forms.HashControl.ReportError (string errorMessage) inline
ReportWarning() [4/4]
void IG.Forms.HashControl.ReportWarning (string warningMessage) inline
ReportInfo() [4/4]
void IG.Forms.HashControl.ReportInfo (string message) inline
ClearHashes() [4/4]
void IG.Forms.HashControl.ClearHashes () inline protected
Clears all text fields with calculated hash values.
References IG.Forms.AbortableBackgroundWorker.Abort(), IG.Forms.HashControl.backgroundWorker1, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.RecalculateHashes, IG.Forms.IndicatorLight.SetOff(), IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, and IG.Forms.HashControl.txtSha512.
DisableActionButtons() [3/3]
void IG.Forms.HashControl.DisableActionButtons () inline protected
References IG.Forms.HashControl.btnGenerate, and IG.Forms.HashControl.btnVerify.
EnableActionButtons() [3/3]
void IG.Forms.HashControl.EnableActionButtons () inline protected
References IG.Forms.HashControl.btnGenerate, and IG.Forms.HashControl.btnVerify.
backgroundWorker1_DoWork() [3/3]
void IG.Forms.HashControl.backgroundWorker1_DoWork (object sender, DoWorkEventArgs e) inline private
Calculates (in background) the required hash (specified in Argument property event arguments) as HashJobArgumentsAndResults.
Parameters
sender Originaror of event that runs this event handler.
e Event arguments, contain the necessary information about how to calculate the hash.
References IG.Forms.HashControl.FilePath, IG.Crypto.UtilCrypto.GetFileHashMd5Hex(), IG.Crypto.UtilCrypto.GetFileHashSha1Hex(), IG.Crypto.UtilCrypto.GetFileHashSha256Hex(), IG.Crypto.UtilCrypto.GetFileHashSha512Hex(), IG.Crypto.UtilCrypto.GetStringHashMd5Hex(), IG.Crypto.UtilCrypto.GetStringHashSha1Hex(), IG.Crypto.UtilCrypto.GetStringHashSha256Hex(), IG.Crypto.UtilCrypto.GetStringHashSha512Hex(), and IG.Forms.HashControl.LastArguments.
backgroundWorker1_RunWorkerCompleted() [3/3]
void IG.Forms.HashControl.backgroundWorker1_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
References IG.Forms.IndicatorLight.BlinkSpecial(), IG.Forms.HashControl.btnCancelCalculation, IG.Forms.HashControl.chkUpperCase, IG.Forms.HashControl.EnableActionButtons(), IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.IsAllHashesCalculated, IG.Forms.HashControl.LastResults, IG.Forms.IndicatorLight.SetOff(), IG.Forms.IndicatorLight.SetOk(), IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, and IG.Forms.HashControl.txtSha512.
CalculateHashAsync() [3/3]
void IG.Forms.HashControl.CalculateHashAsync (HashType hashType) inline protected
References IG.Forms.HashControl.backgroundWorker1, IG.Forms.HashControl.btnCancelCalculation, IG.Forms.HashControl.CalculateAllCanceled, IG.Forms.HashControl.DisableActionButtons(), IG.Forms.HashControl.FilePath, IG.Forms.HashControl.GetFileOrTextLength(), IG.Forms.HashControl.indicatorLight1, IG.Lib.UtilSystem.IsReadableFile(), IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.rbFile, IG.Forms.HashControl.ReportError(), IG.Forms.IndicatorLight.SetBusy(), IG.Forms.IndicatorLight.SetError(), and IG.Forms.HashControl.txtContents.
LoopWhileBusy() [3/3]
void IG.Forms.HashControl.LoopWhileBusy () inline protected
References IG.Forms.HashControl.backgroundWorker1.
GetFileOrTextLength() [3/3]
long IG.Forms.HashControl.GetFileOrTextLength () inline protected
References IG.Forms.HashControl.FilePath, IG.Forms.HashControl.rbFile, and IG.Forms.HashControl.txtContents.
CancelHashCalculations() [3/3]
void IG.Forms.HashControl.CancelHashCalculations () inline protected
References IG.Forms.AbortableBackgroundWorker.Abort(), IG.Forms.HashControl.backgroundWorker1, IG.Forms.HashControl.CalculateAllCanceled, IG.Forms.HashControl.FadingMessageInfo(), IG.Forms.HashControl.FadingMessageShowTimeMs, and IG.Forms.HashControl.FadingMessageWarning().
CalculateHashes() [4/4]
void IG.Forms.HashControl.CalculateHashes () inline protected
Re-calculates all hashes that are checked for calculation.
References IG.Forms.HashControl.backgroundWorker1, IG.Forms.IndicatorLight.BlinkError(), IG.Forms.HashControl.CalculateAllCanceled, IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.CancelHashCalculations(), IG.Forms.HashControl.chkCalculateWhenTyping, IG.Forms.HashControl.chkGenerateFile, IG.Forms.HashControl.chkMd5, IG.Forms.HashControl.chkSha1, IG.Forms.HashControl.chkSha256, IG.Forms.HashControl.chkSha512, IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.EnableActionButtons(), IG.Forms.HashControl.FadingMessageError(), IG.Forms.HashControl.GetFileOrTextLength(), IG.Forms.HashControl.HashJobArgumentsAndResults.HashedLength, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.IsGroupCalculationPerformed, IG.Forms.HashControl.LastArguments, IG.Forms.HashControl.LastResults, IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.rbText, IG.Forms.HashControl.RecalculateHashes, IG.Forms.HashControl.ReportError(), IG.Forms.HashControl.SaveHashesToFile(), IG.Forms.IndicatorLight.SetError(), and IG.Forms.HashControl.txtVerify.
SaveHashesToFile() [4/4]
void IG.Forms.HashControl.SaveHashesToFile () inline protected
References IG.Forms.HashControl.FilePath, IG.Crypto.ConstCrypto.HashFileExtension, IG.Forms.HashControl.rbFile, IG.Forms.HashControl.ReportError(), IG.Forms.HashControl.ReportInfo(), IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, and IG.Forms.HashControl.txtSha512.
BrowseFile() [4/4]
void IG.Forms.HashControl.BrowseFile () inline protected
Browses for the file to be hashed.
References IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.DirectoryPath, IG.Forms.HashControl.fileDialog, IG.Forms.HashControl.FilePath, IG.Forms.HashControl.GenerateFilePreview(), IG.Forms.HashControl.rbFile, and IG.Forms.HashControl.txtFile.
GenerateFilePreview() [4/4]
void IG.Forms.HashControl.GenerateFilePreview () inline protected
Generates file preview in the text preview box if the rbFile is checked.
References IG.Forms.HashControl.ContentsFileBackColor, IG.Forms.HashControl.ContentsFileBinaryBackColor, IG.Forms.HashControl.ContentsFileForeColor, IG.Forms.HashControl.FilePath, IG.Lib.UtilSystem.IsTextFile(), IG.Forms.HashControl.NumCharsFilePreview, IG.Forms.HashControl.rbFile, and IG.Forms.HashControl.txtContents.
VerifyHash() [4/4]
void IG.Forms.HashControl.VerifyHash () inline protected
References IG.Lib.Util.AreHexStringsEqual(), IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.FilePath, IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.rbFile, IG.Forms.HashControl.ReportError(), IG.Forms.HashControl.ReportInfo(), IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, IG.Forms.HashControl.txtSha512, and IG.Forms.HashControl.txtVerify.
btnGenerate_Click() [4/4]
void IG.Forms.HashControl.btnGenerate_Click (object sender, EventArgs e) inline private
Requested hashs are generated and shown in the appropriate text boxes.
References IG.Forms.HashControl.CalculateHashes().
btnClearHashes_Click() [4/4]
void IG.Forms.HashControl.btnClearHashes_Click (object sender, EventArgs e) inline private
Hash values are cleared from the appropriate text fields.
References IG.Forms.HashControl.ClearHashes().
btnVerify_Click() [4/4]
void IG.Forms.HashControl.btnVerify_Click (object sender, EventArgs e) inline private
Hash value is verified for the specified file or text.
References IG.Forms.HashControl.VerifyHash().
txtFile_Validated() [4/4]
void IG.Forms.HashControl.txtFile_Validated (object sender, EventArgs e) inline private
After file has been validated.
References IG.Forms.HashControl._skipFileValidationEvent, IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.FilePath, IG.Forms.HashControl.FileTextBoxInitialized, IG.Forms.HashControl.GenerateFilePreview(), IG.Forms.HashControl.indicatorLight1, IG.Lib.UtilSystem.IsReadableFile(), IG.Forms.HashControl.rbFile, IG.Forms.HashControl.ReportError(), IG.Forms.IndicatorLight.SetError(), and IG.Forms.HashControl.txtFile.
btnFileBrowse_Click() [4/4]
void IG.Forms.HashControl.btnFileBrowse_Click (object sender, EventArgs e) inline private
Browses for the file whose hash values will be calculated.
References IG.Forms.HashControl.BrowseFile(), IG.Forms.HashControl.FilePath, and IG.Forms.HashControl.rbFile.
chkMd5_CheckedChanged() [4/4]
void IG.Forms.HashControl.chkMd5_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.chkMd5, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.IsAllHashesCalculated, IG.Forms.IndicatorLight.SetOk(), and IG.Forms.HashControl.txtMd5.
chkSha1_CheckedChanged() [4/4]
void IG.Forms.HashControl.chkSha1_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.chkSha1, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.IsAllHashesCalculated, IG.Forms.IndicatorLight.SetOk(), and IG.Forms.HashControl.txtSha1.
chkSha256_CheckedChanged() [4/4]
void IG.Forms.HashControl.chkSha256_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.chkSha256, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.IsAllHashesCalculated, IG.Forms.IndicatorLight.SetOk(), and IG.Forms.HashControl.txtSha256.
chkSha512_CheckedChanged() [4/4]
void IG.Forms.HashControl.chkSha512_CheckedChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.chkSha512, IG.Forms.HashControl.indicatorLight1, IG.Forms.HashControl.IsAllHashesCalculated, IG.Forms.IndicatorLight.SetOk(), and IG.Forms.HashControl.txtSha512.
btnMd5Copy_Click() [4/4]
void IG.Forms.HashControl.btnMd5Copy_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.ReportError(), and IG.Forms.HashControl.txtMd5.
btnSha1Copy_Click() [4/4]
void IG.Forms.HashControl.btnSha1Copy_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.ReportError(), and IG.Forms.HashControl.txtSha1.
btnSha256Copy_Click() [4/4]
void IG.Forms.HashControl.btnSha256Copy_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.ReportError(), and IG.Forms.HashControl.txtSha256.
bthSha512_Click() [4/4]
void IG.Forms.HashControl.bthSha512_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.LoopWhileBusy(), IG.Forms.HashControl.ReportError(), and IG.Forms.HashControl.txtSha512.
btnVerifyPaste_Click() [4/4]
void IG.Forms.HashControl.btnVerifyPaste_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.txtVerify.
rbFile_CheckedChanged() [4/4]
void IG.Forms.HashControl.rbFile_CheckedChanged (object sender, EventArgs e) inline private
Handles things that need to be done when we switch between hashing the file or hashing text from the textbox.
References IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkCalculateWhenTyping, IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.ContentsFileBackColor, IG.Forms.HashControl.ContentsFileForeColor, IG.Forms.HashControl.ContentsTextBackColor, IG.Forms.HashControl.ContentsTextForeColor, IG.Forms.HashControl.FadingMessageInfo(), IG.Forms.HashControl.FileOffForeColor, IG.Forms.HashControl.FileOnForeColor, IG.Forms.HashControl.FilePath, IG.Forms.HashControl.GenerateFilePreview(), IG.Forms.HashControl.grpTextPreview, IG.Forms.HashControl.MaxInsertTextInfo, IG.Forms.HashControl.NumInsertTextInfo, IG.Forms.HashControl.rbFile, IG.Forms.HashControl.RecalculateHashes, IG.Forms.HashControl.txtContents, and IG.Forms.HashControl.txtFile.
chkGenerateFile_CheckedChanged() [4/4]
void IG.Forms.HashControl.chkGenerateFile_CheckedChanged (object sender, EventArgs e) inline private
Handles situation when one changes the setting whether to store file's hash values to a file. If the check box gets checked then hashes are immediately saved to a file.
References IG.Forms.HashControl.chkGenerateFile, and IG.Forms.HashControl.SaveHashesToFile().
txtContents_Enter() [4/4]
void IG.Forms.HashControl.txtContents_Enter (object sender, EventArgs e) inline private
References IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.ContentsTextBoxInitialized, IG.Forms.HashControl.rbFile, and IG.Forms.HashControl.txtContents.
txtContents_MouseEnter() [4/4]
void IG.Forms.HashControl.txtContents_MouseEnter (object sender, EventArgs e) inline private
References IG.Forms.HashControl.ContentsTextBoxInitialized, and IG.Forms.HashControl.txtContents.
txtContents_TextChanged() [4/4]
void IG.Forms.HashControl.txtContents_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkCalculateWhenTyping, IG.Forms.HashControl.ContentsTextBoxInitialized, IG.Forms.HashControl.IsGroupCalculationPerformed, IG.Forms.HashControl.rbText, and IG.Forms.HashControl.RecalculateHashes.
txtContents_Validated() [4/4]
void IG.Forms.HashControl.txtContents_Validated (object sender, EventArgs e) inline private
After text is inserted, calculate appropriate hashes immediately.
References IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.ContentsTextBoxInitialized, and IG.Forms.HashControl.rbText.
txtContents_KeyPress() [3/3]
void IG.Forms.HashControl.txtContents_KeyPress (object sender, KeyPressEventArgs e) inline private
chkUpperCase_CheckedChanged() [4/4]
void IG.Forms.HashControl.chkUpperCase_CheckedChanged (object sender, EventArgs e) inline private
Recalculates hashes because the requested lower/upper case form has changed.
References IG.Forms.HashControl.chkUpperCase, IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, and IG.Forms.HashControl.txtSha512.
txtFile_Enter() [4/4]
void IG.Forms.HashControl.txtFile_Enter (object sender, EventArgs e) inline private
References IG.Forms.HashControl.FileTextBoxInitialized, and IG.Forms.HashControl.txtFile.
txtFile_MouseEnter() [4/4]
void IG.Forms.HashControl.txtFile_MouseEnter (object sender, EventArgs e) inline private
References IG.Forms.HashControl.FileTextBoxInitialized, and IG.Forms.HashControl.txtFile.
txtFile_TextChanged() [4/4]
void IG.Forms.HashControl.txtFile_TextChanged (object sender, EventArgs e) inline private
References IG.Forms.HashControl.FileTextBoxInitialized.
txtFile_DragEnter() [4/4]
void IG.Forms.HashControl.txtFile_DragEnter (object sender, DragEventArgs e) inline private
txtFile_DragDrop() [4/4]
void IG.Forms.HashControl.txtFile_DragDrop (object sender, DragEventArgs e) inline private
References IG.Forms.HashControl.FilePath, IG.Forms.HashControl.rbFile, IG.Forms.HashControl.txtFile, and IG.Forms.HashControl.txtFile_Validated().
txtContents_DragEnter() [4/4]
void IG.Forms.HashControl.txtContents_DragEnter (object sender, DragEventArgs e) inline private
txtContents_DragDrop() [4/4]
void IG.Forms.HashControl.txtContents_DragDrop (object sender, DragEventArgs e) inline private
References IG.Forms.HashControl._form, IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.FilePath, IG.Forms.HashControl.rbFile, IG.Forms.HashControl.rbText, IG.Forms.HashControl.TextBeingDropped, IG.Forms.HashControl.txtContents, IG.Forms.HashControl.txtContents_Validated(), IG.Forms.HashControl.txtFile, and IG.Forms.HashControl.txtFile_Validated().
Handle_CtrlA_CtrlBackspace() [4/4]
void IG.Forms.HashControl.Handle_CtrlA_CtrlBackspace (TextBox textBox, object sender, KeyEventArgs e) inline protected
Handle the Ctrl-A (select all) and Ctrl-Backspace events for the specified text box.
Parameters
textBox Text box for wich the event is handled.
txtFile_KeyDown() [4/4]
void IG.Forms.HashControl.txtFile_KeyDown (object sender, KeyEventArgs e) inline private
References IG.Forms.HashControl.Handle_CtrlA_CtrlBackspace(), and IG.Forms.HashControl.txtFile.
txtContents_KeyDown() [4/4]
void IG.Forms.HashControl.txtContents_KeyDown (object sender, KeyEventArgs e) inline private
References IG.Forms.HashControl.Handle_CtrlA_CtrlBackspace(), and IG.Forms.HashControl.txtContents.
btnAbout_Click() [3/3]
void IG.Forms.HashControl.btnAbout_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl._aboutForm.
btnCancelCalculation_Click() [3/3]
void IG.Forms.HashControl.btnCancelCalculation_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.CancelHashCalculations().
btnInfo_Click() [2/2]
void IG.Forms.HashControl.btnInfo_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl._aboutForm, IG.Forms.HashAboutControl.HelpPdf(), and IG.Forms.HashAboutForm.MainControl.
chkCalculateWhenTyping_CheckedChanged() [3/3]
void IG.Forms.HashControl.chkCalculateWhenTyping_CheckedChanged (object sender, EventArgs e) inline private
HashControl_KeyUp() [3/3]
void IG.Forms.HashControl.HashControl_KeyUp (object sender, KeyEventArgs e) inline private
Intended for handling key presses such as F1 for help, etc.
Parameters
sender
e
References IG.Forms.HashControl.KeyUpHandler().
KeyUpHandler() [3/3]
void IG.Forms.HashControl.KeyUpHandler (object sender, KeyEventArgs e) inline
Handles key up events for the current form.
Form does not catch the KeyUp events. Therefore, the event handler code was moved to a public function, which can be called from a form, tab control, or other control that contains this control.
References IG.Forms.HashControl.btnAbout_Click(), and IG.Forms.HashControl.btnInfo_Click().
helpToolStripMenuItem_Click() [2/2]
void IG.Forms.HashControl.helpToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.btnInfo_Click().
aboutToolStripMenuItem_Click() [2/2]
void IG.Forms.HashControl.aboutToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.HashControl.btnAbout_Click().
contextMenuStrip1_Opening() [2/2]
void IG.Forms.HashControl.contextMenuStrip1_Opening (object sender, CancelEventArgs e) inline private
toolStripMenuItem1_Click() [2/2]
void IG.Forms.HashControl.toolStripMenuItem1_Click (object sender, EventArgs e) inline private
SetCursorMouseUp() [2/2]
void IG.Forms.HashControl.SetCursorMouseUp (object sender, MouseEventArgs e) inline private
Sets mouse cursor shape on MouseUp event, according to the current status of modifier keys.
SetCursorMouseDown() [2/2]
void IG.Forms.HashControl.SetCursorMouseDown (object sender, MouseEventArgs e) inline private
Sets mouse cursor shape on MouseDown event, according to the current status of modifier keys.
References IG.Forms.HashControl.AltDown, IG.Forms.HashControl.ControlDown, and IG.Forms.HashControl.ShiftDown.
InitiateMoveOrSize() [2/2]
void IG.Forms.HashControl.InitiateMoveOrSize (object sender, MouseEventArgs e) inline private
References IG.Forms.HashControl._distMoveX, IG.Forms.HashControl._distMoveY, IG.Forms.HashControl._distSizeX, IG.Forms.HashControl._distSizeY, IG.Forms.HashControl._form, IG.Forms.HashControl._formInitialHeight, IG.Forms.HashControl._formInitialLeft, IG.Forms.HashControl._formInitialTop, IG.Forms.HashControl._formInitialWidth, IG.Forms.HashControl._isSizingOrMoving, IG.Forms.HashControl._mouseInitialLocalX, IG.Forms.HashControl._mouseInitialLocalY, IG.Forms.HashControl._mouseInitialRelX, IG.Forms.HashControl._mouseInitialRelY, IG.Forms.HashControl._mouseInitialX, IG.Forms.HashControl._mouseInitialY, IG.Forms.HashControl._mousePreviousX, IG.Forms.HashControl._mousePreviousY, IG.Forms.HashControl.ControlDown, IG.Forms.HashControl.MouseRelX, IG.Forms.HashControl.MouseRelY, IG.Forms.HashControl.MouseX, IG.Forms.HashControl.MouseY, and IG.Forms.HashControl.ShiftDown.
Common_KeyDown() [2/2]
void IG.Forms.HashControl.Common_KeyDown (object sender, KeyEventArgs e) inline private
Common event handler for key down event, installed on all controls.
Common_KeyUp() [2/2]
void IG.Forms.HashControl.Common_KeyUp (object sender, KeyEventArgs e) inline private
Common event handler for key up event, installed on all controls.
Parameters
sender
e
Common_MouseDownOnInteractive() [2/2]
void IG.Forms.HashControl.Common_MouseDownOnInteractive (object sender, MouseEventArgs e) inline private
Initiates dragging or resizing by mouse on MouseDown event.
References IG.Forms.HashControl.AltDown, and IG.Forms.HashControl.InitiateMoveOrSize().
Common_MouseDownOnNoninteractiveControls() [2/2]
void IG.Forms.HashControl.Common_MouseDownOnNoninteractiveControls (object sender, MouseEventArgs e) inline private
Enables dragging by mouse.
References IG.Forms.HashControl.InitiateMoveOrSize().
Common_MouseUp() [2/2]
void IG.Forms.HashControl.Common_MouseUp (object sender, MouseEventArgs e) inline private
Enables dragging by mouse.
References IG.Forms.HashControl._isSizingOrMoving, and IG.Forms.HashControl.SetCursorMouseUp().
Common_MouseMove() [2/2]
void IG.Forms.HashControl.Common_MouseMove (object sender, MouseEventArgs e) inline private
Enables dragging by mouse.
References IG.Forms.HashControl._distMoveX, IG.Forms.HashControl._distMoveY, IG.Forms.HashControl._distSizeX, IG.Forms.HashControl._distSizeY, IG.Forms.HashControl._form, IG.Forms.HashControl._formInitialHeight, IG.Forms.HashControl._formInitialLeft, IG.Forms.HashControl._formInitialTop, IG.Forms.HashControl._formInitialWidth, IG.Forms.HashControl._isSizingOrMoving, IG.Forms.HashControl._mousePreviousX, IG.Forms.HashControl._mousePreviousY, IG.Forms.HashControl.AltDown, IG.Forms.HashControl.ControlDown, IG.Forms.HashControl.MouseX, and IG.Forms.HashControl.MouseY.
SetCommonEvents() [2/2]
void IG.Forms.HashControl.SetCommonEvents (Control f) inline private
This method is used to set the common event handlers for the current control and its subcontrols.
Parameters
f Control on which common event handlers are set.
References IG.Forms.HashControl.Common_KeyDown(), IG.Forms.HashControl.Common_KeyUp(), IG.Forms.HashControl.Common_MouseDownOnInteractive(), IG.Forms.HashControl.Common_MouseDownOnNoninteractiveControls(), IG.Forms.HashControl.Common_MouseMove(), IG.Forms.HashControl.Common_MouseUp(), IG.Forms.HashControl.txtContents, IG.Forms.HashControl.txtContents_DragDrop(), IG.Forms.HashControl.txtContents_DragEnter(), and IG.Forms.HashControl.txtFile.
HashControl_Load() [2/2]
void IG.Forms.HashControl.HashControl_Load (object sender, EventArgs e) inline private
References IG.Forms.ControlDelegate(), IG.Forms.UtilForms.RecursiveControlDelegate(), IG.Forms.HashControl.ReportError(), and IG.Forms.HashControl.SetCommonEvents().
Dispose() [4/4]
override void IG.Forms.HashControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.HashControl.components.
InitializeComponent() [4/4]
void IG.Forms.HashControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.HashControl.aboutToolStripMenuItem, IG.Forms.HashControl.backgroundWorker1, IG.Forms.HashControl.backgroundWorker1_DoWork(), IG.Forms.HashControl.backgroundWorker1_RunWorkerCompleted(), IG.Forms.IndicatorLight.BlinkIntervalMilliSeconds, IG.Forms.IndicatorLight.BorderLabel, IG.Forms.IndicatorLight.BorderOut, IG.Forms.HashControl.bthSha512, IG.Forms.HashControl.bthSha512_Click(), IG.Forms.HashControl.btnAbout, IG.Forms.HashControl.btnAbout_Click(), IG.Forms.HashControl.btnCancelCalculation, IG.Forms.HashControl.btnCancelCalculation_Click(), IG.Forms.HashControl.btnClearHashes, IG.Forms.HashControl.btnClearHashes_Click(), IG.Forms.HashControl.btnFileBrowse, IG.Forms.HashControl.btnFileBrowse_Click(), IG.Forms.HashControl.btnGenerate, IG.Forms.HashControl.btnGenerate_Click(), IG.Forms.HashControl.btnInfo, IG.Forms.HashControl.btnInfo_Click(), IG.Forms.HashControl.btnMd5Copy, IG.Forms.HashControl.btnMd5Copy_Click(), IG.Forms.HashControl.btnSha1Copy, IG.Forms.HashControl.btnSha1Copy_Click(), IG.Forms.HashControl.btnSha256Copy, IG.Forms.HashControl.btnSha256Copy_Click(), IG.Forms.HashControl.btnVerify, IG.Forms.HashControl.btnVerify_Click(), IG.Forms.HashControl.btnVerifyPaste, IG.Forms.HashControl.btnVerifyPaste_Click(), IG.Forms.HashControl.chkCalculateWhenTyping, IG.Forms.HashControl.chkCalculateWhenTyping_CheckedChanged(), IG.Forms.HashControl.chkGenerateFile, IG.Forms.HashControl.chkGenerateFile_CheckedChanged(), IG.Forms.HashControl.chkMd5, IG.Forms.HashControl.chkMd5_CheckedChanged(), IG.Forms.HashControl.chkSha1, IG.Forms.HashControl.chkSha1_CheckedChanged(), IG.Forms.HashControl.chkSha256, IG.Forms.HashControl.chkSha256_CheckedChanged(), IG.Forms.HashControl.chkSha512, IG.Forms.HashControl.chkSha512_CheckedChanged(), IG.Forms.HashControl.chkUpperCase, IG.Forms.HashControl.chkUpperCase_CheckedChanged(), IG.Forms.IndicatorLight.ColorLabel, IG.Forms.HashControl.components, IG.Forms.HashControl.contextMenuStrip1, IG.Forms.HashControl.contextMenuStrip2, IG.Forms.IndicatorLight.FlowDirection, IG.Forms.HashControl.grpHashGeneration, IG.Forms.HashControl.grpTextPreview, IG.Forms.IndicatorLight.HasBusy, IG.Forms.IndicatorLight.HasError, IG.Forms.IndicatorLight.HasOff, IG.Forms.IndicatorLight.HasOk, IG.Forms.HashControl.helpToolStripMenuItem, IG.Forms.HashControl.indicatorLight1, IG.Forms.IndicatorLight.IsBlinking, IG.Forms.IndicatorLight.LabelFont, IG.Forms.IndicatorLight.LabelText, IG.Forms.HashControl.lblFile, IG.Forms.HashControl.lblMd5, IG.Forms.HashControl.lblSha1, IG.Forms.HashControl.lblSha256, IG.Forms.HashControl.lblSha512, IG.Forms.HashControl.lblVerify, IG.Forms.HashControl.lvlVerifyMain, IG.Forms.IndicatorLight.MarginLabel, IG.Forms.IndicatorLight.MarginOut, IG.Forms.HashControl.openFileDialog1, IG.Forms.IndicatorLight.PaddingLabel, IG.Forms.IndicatorLight.PaddingOut, IG.Forms.HashControl.rbFile, IG.Forms.HashControl.rbFile_CheckedChanged(), IG.Forms.HashControl.rbText, IG.Forms.IndicatorLight.ThrowOnInvalidSwitch, IG.Forms.HashControl.txtContents, IG.Forms.HashControl.txtContents_DragDrop(), IG.Forms.HashControl.txtContents_DragEnter(), IG.Forms.HashControl.txtContents_Enter(), IG.Forms.HashControl.txtContents_KeyDown(), IG.Forms.HashControl.txtContents_KeyPress(), IG.Forms.HashControl.txtContents_MouseEnter(), IG.Forms.HashControl.txtContents_TextChanged(), IG.Forms.HashControl.txtContents_Validated(), IG.Forms.HashControl.txtFile, IG.Forms.HashControl.txtFile_DragDrop(), IG.Forms.HashControl.txtFile_DragEnter(), IG.Forms.HashControl.txtFile_Enter(), IG.Forms.HashControl.txtFile_KeyDown(), IG.Forms.HashControl.txtFile_MouseEnter(), IG.Forms.HashControl.txtFile_TextChanged(), IG.Forms.HashControl.txtFile_Validated(), IG.Forms.HashControl.txtMd5, IG.Forms.HashControl.txtSha1, IG.Forms.HashControl.txtSha256, IG.Forms.HashControl.txtSha512, and IG.Forms.HashControl.txtVerify.
Member Data Documentation
_fadingMessageShowTimeMs
int IG.Forms.HashControl._fadingMessageShowTimeMs = 3000 protected
_fadingMessageInfoColor
Color IG.Forms.HashControl._fadingMessageInfoColor = FadingMessage.DefaultBackGroundColor private
Referenced by IG.Forms.HashControl.FadingMessageInfo().
_fadingMessageWarningColor
Color IG.Forms.HashControl._fadingMessageWarningColor = Color.Orange private
Referenced by IG.Forms.HashControl.FadingMessageWarning().
_fadingMessageErrorColor
Color IG.Forms.HashControl._fadingMessageErrorColor = Color.Red private
Referenced by IG.Forms.HashControl.FadingMessageError().
FileTextBoxInitialized
bool IG.Forms.HashControl.FileTextBoxInitialized = false protected
Referenced by IG.Forms.HashControl.txtFile_Enter(), IG.Forms.HashControl.txtFile_MouseEnter(), IG.Forms.HashControl.txtFile_TextChanged(), and IG.Forms.HashControl.txtFile_Validated().
FileOnForeColor
Color IG.Forms.HashControl.FileOnForeColor = Color.Black protected
Referenced by IG.Forms.HashControl.HashControl(), and IG.Forms.HashControl.rbFile_CheckedChanged().
FileOffForeColor
Color IG.Forms.HashControl.FileOffForeColor = Color.DarkGray protected
Referenced by IG.Forms.HashControl.rbFile_CheckedChanged().
ContentsTextBoxInitialized
bool IG.Forms.HashControl.ContentsTextBoxInitialized = false protected
Referenced by IG.Forms.HashControl.txtContents_Enter(), IG.Forms.HashControl.txtContents_MouseEnter(), IG.Forms.HashControl.txtContents_TextChanged(), and IG.Forms.HashControl.txtContents_Validated().
ContentsFileBackColor
Color IG.Forms.HashControl.ContentsFileBackColor = Color.LightGray protected
Referenced by IG.Forms.HashControl.GenerateFilePreview(), IG.Forms.HashControl.HashControl(), and IG.Forms.HashControl.rbFile_CheckedChanged().
ContentsFileBinaryBackColor
Color IG.Forms.HashControl.ContentsFileBinaryBackColor = Color.Wheat protected
Referenced by IG.Forms.HashControl.GenerateFilePreview().
ContentsTextBackColor
Color IG.Forms.HashControl.ContentsTextBackColor = Color.White protected
Referenced by IG.Forms.HashControl.rbFile_CheckedChanged().
ContentsFileForeColor
Color IG.Forms.HashControl.ContentsFileForeColor = Color.Black protected
Referenced by IG.Forms.HashControl.GenerateFilePreview(), IG.Forms.HashControl.HashControl(), and IG.Forms.HashControl.rbFile_CheckedChanged().
ContentsTextForeColor
Color IG.Forms.HashControl.ContentsTextForeColor = Color.Blue protected
Referenced by IG.Forms.HashControl.rbFile_CheckedChanged().
_directoryPath
string IG.Forms.HashControl._directoryPath protected
_filePath
string IG.Forms.HashControl._filePath protected
fileDialog
OpenFileDialog IG.Forms.HashControl.fileDialog protected
Referenced by IG.Forms.HashControl.BrowseFile().
NumCharsFilePreview
int IG.Forms.HashControl.NumCharsFilePreview = 1000 protected
Referenced by IG.Forms.HashControl.GenerateFilePreview().
_skipFileValidationEvent
bool IG.Forms.HashControl._skipFileValidationEvent = false private
Referenced by IG.Forms.HashControl.txtFile_Validated().
NumInsertTextInfo
int IG.Forms.HashControl.NumInsertTextInfo = 0 protected
Referenced by IG.Forms.HashControl.rbFile_CheckedChanged().
MaxInsertTextInfo
int IG.Forms.HashControl.MaxInsertTextInfo = 1 protected
Referenced by IG.Forms.HashControl.rbFile_CheckedChanged().
TextBeingDropped
bool IG.Forms.HashControl.TextBeingDropped = false protected
Referenced by IG.Forms.HashControl.rbFile_CheckedChanged(), and IG.Forms.HashControl.txtContents_DragDrop().
_aboutForm
HashAboutForm IG.Forms.HashControl._aboutForm = new HashAboutForm() protected
Referenced by IG.Forms.HashControl.btnAbout_Click(), IG.Forms.HashControl.btnHelp_Click(), and IG.Forms.HashControl.btnInfo_Click().
_mouseInitialLocalX
int IG.Forms.HashControl._mouseInitialLocalX private
Referenced by IG.Forms.HashControl.InitiateMoveOrSize().
_mouseInitialLocalY
int IG.Forms.HashControl._mouseInitialLocalY private
Referenced by IG.Forms.HashControl.InitiateMoveOrSize().
_mouseInitialX
int IG.Forms.HashControl._mouseInitialX private
Referenced by IG.Forms.HashControl.InitiateMoveOrSize().
_mouseInitialY
int IG.Forms.HashControl._mouseInitialY private
Referenced by IG.Forms.HashControl.InitiateMoveOrSize().
_formInitialLeft
int IG.Forms.HashControl._formInitialLeft private
Referenced by IG.Forms.HashControl.Common_MouseMove(), and IG.Forms.HashControl.InitiateMoveOrSize().
_formInitialTop
int IG.Forms.HashControl._formInitialTop private
Referenced by IG.Forms.HashControl.Common_MouseMove(), and IG.Forms.HashControl.InitiateMoveOrSize().
_formInitialWidth
int IG.Forms.HashControl._formInitialWidth private
Referenced by IG.Forms.HashControl.Common_MouseMove(), and IG.Forms.HashControl.InitiateMoveOrSize().
_formInitialHeight
int IG.Forms.HashControl._formInitialHeight private
Referenced by IG.Forms.HashControl.Common_MouseMove(), and IG.Forms.HashControl.InitiateMoveOrSize().
_mouseInitialRelX
double IG.Forms.HashControl._mouseInitialRelX private
Referenced by IG.Forms.HashControl.InitiateMoveOrSize().
_mouseInitialRelY
double IG.Forms.HashControl._mouseInitialRelY private
Referenced by IG.Forms.HashControl.InitiateMoveOrSize().
_mousePreviousX
int IG.Forms.HashControl._mousePreviousX private
Referenced by IG.Forms.HashControl.Common_MouseMove(), and IG.Forms.HashControl.InitiateMoveOrSize().
_mousePreviousY
int IG.Forms.HashControl._mousePreviousY private
Referenced by IG.Forms.HashControl.Common_MouseMove(), and IG.Forms.HashControl.InitiateMoveOrSize().
_distMoveX
int IG.Forms.HashControl._distMoveX private
Referenced by IG.Forms.HashControl.Common_MouseMove(), and IG.Forms.HashControl.InitiateMoveOrSize().
_distMoveY
int IG.Forms.HashControl._distMoveY private
Referenced by IG.Forms.HashControl.Common_MouseMove(), and IG.Forms.HashControl.InitiateMoveOrSize().
_distSizeX
int IG.Forms.HashControl._distSizeX private
Referenced by IG.Forms.HashControl.Common_MouseMove(), and IG.Forms.HashControl.InitiateMoveOrSize().
_distSizeY
int IG.Forms.HashControl._distSizeY private
Referenced by IG.Forms.HashControl.Common_MouseMove(), and IG.Forms.HashControl.InitiateMoveOrSize().
_isSizingOrMoving
bool IG.Forms.HashControl._isSizingOrMoving = false private
Referenced by IG.Forms.HashControl.Common_MouseMove(), IG.Forms.HashControl.Common_MouseUp(), and IG.Forms.HashControl.InitiateMoveOrSize().
components
System ComponentModel IContainer IG.Forms.HashControl.components = null private
Required designer variable.
Referenced by IG.Forms.HashControl.Dispose(), and IG.Forms.HashControl.InitializeComponent().
grpHashGeneration
System Windows Forms GroupBox IG.Forms.HashControl.grpHashGeneration private
Referenced by IG.Forms.HashControl.InitializeComponent().
chkSha512
System Windows Forms CheckBox IG.Forms.HashControl.chkSha512 private
Referenced by IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkSha512_CheckedChanged(), and IG.Forms.HashControl.InitializeComponent().
bthSha512
System Windows Forms Button IG.Forms.HashControl.bthSha512 private
Referenced by IG.Forms.HashControl.InitializeComponent().
txtSha512
System Windows Forms TextBox IG.Forms.HashControl.txtSha512 private
Referenced by IG.Forms.HashControl.backgroundWorker1_RunWorkerCompleted(), IG.Forms.HashControl.bthSha512_Click(), IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkSha512_CheckedChanged(), IG.Forms.HashControl.chkUpperCase_CheckedChanged(), IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.HashControl.SaveHashesToFile(), and IG.Forms.HashControl.VerifyHash().
lblSha512
System Windows Forms Label IG.Forms.HashControl.lblSha512 private
Referenced by IG.Forms.HashControl.InitializeComponent().
chkSha256
System Windows Forms CheckBox IG.Forms.HashControl.chkSha256 private
Referenced by IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkSha256_CheckedChanged(), and IG.Forms.HashControl.InitializeComponent().
chkSha1
System Windows Forms CheckBox IG.Forms.HashControl.chkSha1 private
Referenced by IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkSha1_CheckedChanged(), and IG.Forms.HashControl.InitializeComponent().
chkMd5
System Windows Forms CheckBox IG.Forms.HashControl.chkMd5 private
Referenced by IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkMd5_CheckedChanged(), and IG.Forms.HashControl.InitializeComponent().
btnSha256Copy
System Windows Forms Button IG.Forms.HashControl.btnSha256Copy private
Referenced by IG.Forms.HashControl.InitializeComponent().
btnSha1Copy
System Windows Forms Button IG.Forms.HashControl.btnSha1Copy private
Referenced by IG.Forms.HashControl.InitializeComponent().
btnMd5Copy
System Windows Forms Button IG.Forms.HashControl.btnMd5Copy private
Referenced by IG.Forms.HashControl.InitializeComponent().
txtSha256
System Windows Forms TextBox IG.Forms.HashControl.txtSha256 private
Referenced by IG.Forms.HashControl.backgroundWorker1_RunWorkerCompleted(), IG.Forms.HashControl.btnSha256Copy_Click(), IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkSha256_CheckedChanged(), IG.Forms.HashControl.chkUpperCase_CheckedChanged(), IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.HashControl.SaveHashesToFile(), and IG.Forms.HashControl.VerifyHash().
lblSha256
System Windows Forms Label IG.Forms.HashControl.lblSha256 private
Referenced by IG.Forms.HashControl.InitializeComponent().
txtSha1
System Windows Forms TextBox IG.Forms.HashControl.txtSha1 private
Referenced by IG.Forms.HashControl.backgroundWorker1_RunWorkerCompleted(), IG.Forms.HashControl.btnSha1Copy_Click(), IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkSha1_CheckedChanged(), IG.Forms.HashControl.chkUpperCase_CheckedChanged(), IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.HashControl.SaveHashesToFile(), and IG.Forms.HashControl.VerifyHash().
lblSha1
System Windows Forms Label IG.Forms.HashControl.lblSha1 private
Referenced by IG.Forms.HashControl.InitializeComponent().
txtMd5
System Windows Forms TextBox IG.Forms.HashControl.txtMd5 private
Referenced by IG.Forms.HashControl.backgroundWorker1_RunWorkerCompleted(), IG.Forms.HashControl.btnMd5Copy_Click(), IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkMd5_CheckedChanged(), IG.Forms.HashControl.chkUpperCase_CheckedChanged(), IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.HashControl.SaveHashesToFile(), and IG.Forms.HashControl.VerifyHash().
lblMd5
System Windows Forms Label IG.Forms.HashControl.lblMd5 private
Referenced by IG.Forms.HashControl.InitializeComponent().
btnFileBrowse
System Windows Forms Button IG.Forms.HashControl.btnFileBrowse private
Referenced by IG.Forms.HashControl.InitializeComponent().
txtFile
System Windows Forms TextBox IG.Forms.HashControl.txtFile private
Referenced by IG.Forms.HashControl.BrowseFile(), IG.Forms.HashControl.HashControl(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.HashControl.rbFile_CheckedChanged(), IG.Forms.HashControl.SetCommonEvents(), IG.Forms.HashControl.txtContents_DragDrop(), IG.Forms.HashControl.txtFile_DragDrop(), IG.Forms.HashControl.txtFile_Enter(), IG.Forms.HashControl.txtFile_KeyDown(), IG.Forms.HashControl.txtFile_MouseEnter(), and IG.Forms.HashControl.txtFile_Validated().
lblFile
System Windows Forms Label IG.Forms.HashControl.lblFile private
Referenced by IG.Forms.HashControl.InitializeComponent().
rbText
System Windows Forms RadioButton IG.Forms.HashControl.rbText private
Referenced by IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.HashControl.txtContents_DragDrop(), IG.Forms.HashControl.txtContents_TextChanged(), IG.Forms.HashControl.txtContents_Validated(), and IG.Forms.HashControl.VerifyHash().
rbFile
System Windows Forms RadioButton IG.Forms.HashControl.rbFile private
Referenced by IG.Forms.HashControl.BrowseFile(), IG.Forms.HashControl.btnFileBrowse_Click(), IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.GenerateFilePreview(), IG.Forms.HashControl.GetFileOrTextLength(), IG.Forms.HashControl.HashControl(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.HashControl.rbFile_CheckedChanged(), IG.Forms.HashControl.SaveHashesToFile(), IG.Forms.HashControl.txtContents_DragDrop(), IG.Forms.HashControl.txtContents_Enter(), IG.Forms.HashControl.txtFile_DragDrop(), IG.Forms.HashControl.txtFile_Validated(), and IG.Forms.HashControl.VerifyHash().
grpTextPreview
System Windows Forms GroupBox IG.Forms.HashControl.grpTextPreview private
Referenced by IG.Forms.HashControl.InitializeComponent(), and IG.Forms.HashControl.rbFile_CheckedChanged().
txtContents
System Windows Forms TextBox IG.Forms.HashControl.txtContents private
Referenced by IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.GenerateFilePreview(), IG.Forms.HashControl.GetFileOrTextLength(), IG.Forms.HashControl.HashControl(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.HashControl.rbFile_CheckedChanged(), IG.Forms.HashControl.SetCommonEvents(), IG.Forms.HashControl.txtContents_DragDrop(), IG.Forms.HashControl.txtContents_Enter(), IG.Forms.HashControl.txtContents_KeyDown(), IG.Forms.HashControl.txtContents_MouseEnter(), and IG.Forms.HashControl.VerifyHash().
btnGenerate
System Windows Forms Button IG.Forms.HashControl.btnGenerate private
Referenced by IG.Forms.HashControl.DisableActionButtons(), IG.Forms.HashControl.EnableActionButtons(), and IG.Forms.HashControl.InitializeComponent().
chkGenerateFile
System Windows Forms CheckBox IG.Forms.HashControl.chkGenerateFile private
Referenced by IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkGenerateFile_CheckedChanged(), and IG.Forms.HashControl.InitializeComponent().
lvlVerifyMain
System Windows Forms Label IG.Forms.HashControl.lvlVerifyMain private
Referenced by IG.Forms.HashControl.InitializeComponent().
btnVerify
System Windows Forms Button IG.Forms.HashControl.btnVerify private
Referenced by IG.Forms.HashControl.DisableActionButtons(), IG.Forms.HashControl.EnableActionButtons(), and IG.Forms.HashControl.InitializeComponent().
btnVerifyPaste
System Windows Forms Button IG.Forms.HashControl.btnVerifyPaste private
Referenced by IG.Forms.HashControl.InitializeComponent().
txtVerify
System Windows Forms TextBox IG.Forms.HashControl.txtVerify private
Referenced by IG.Forms.HashControl.btnVerifyPaste_Click(), IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.InitializeComponent(), and IG.Forms.HashControl.VerifyHash().
lblVerify
System Windows Forms Label IG.Forms.HashControl.lblVerify private
Referenced by IG.Forms.HashControl.InitializeComponent().
openFileDialog1
System Windows Forms OpenFileDialog IG.Forms.HashControl.openFileDialog1 private
Referenced by IG.Forms.HashControl.InitializeComponent().
btnClearHashes
System Windows Forms Button IG.Forms.HashControl.btnClearHashes private
Referenced by IG.Forms.HashControl.InitializeComponent().
chkUpperCase
System Windows Forms CheckBox IG.Forms.HashControl.chkUpperCase private
Referenced by IG.Forms.HashControl.backgroundWorker1_RunWorkerCompleted(), IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkUpperCase_CheckedChanged(), and IG.Forms.HashControl.InitializeComponent().
btnAbout
System Windows Forms Button IG.Forms.HashControl.btnAbout private
Referenced by IG.Forms.HashControl.InitializeComponent().
backgroundWorker1
IG Forms AbortableBackgroundWorker IG.Forms.HashControl.backgroundWorker1 private
Referenced by IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.CancelHashCalculations(), IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.HashControl(), IG.Forms.HashControl.InitializeComponent(), and IG.Forms.HashControl.LoopWhileBusy().
btnCancelCalculation
System Windows Forms Button IG.Forms.HashControl.btnCancelCalculation private
Referenced by IG.Forms.HashControl.backgroundWorker1_RunWorkerCompleted(), IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.HashControl(), and IG.Forms.HashControl.InitializeComponent().
btnHelp
System.Windows.Forms.Button IG.Forms.HashControl.btnHelp private
Referenced by IG.Forms.HashControl.InitializeComponent().
indicatorLight1
IndicatorLight IG.Forms.HashControl.indicatorLight1 private
Referenced by IG.Forms.HashControl.backgroundWorker1_RunWorkerCompleted(), IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.chkMd5_CheckedChanged(), IG.Forms.HashControl.chkSha1_CheckedChanged(), IG.Forms.HashControl.chkSha256_CheckedChanged(), IG.Forms.HashControl.chkSha512_CheckedChanged(), IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.HashControl(), IG.Forms.HashControl.InitializeComponent(), and IG.Forms.HashControl.txtFile_Validated().
chkCalculateWhenTyping
System Windows Forms CheckBox IG.Forms.HashControl.chkCalculateWhenTyping private
Referenced by IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.HashControl(), IG.Forms.HashControl.InitializeComponent(), IG.Forms.HashControl.rbFile_CheckedChanged(), and IG.Forms.HashControl.txtContents_TextChanged().
menuMain
System.Windows.Forms.ContextMenuStrip IG.Forms.HashControl.menuMain private
Referenced by IG.Forms.HashControl.Common_MouseClick(), and IG.Forms.HashControl.InitializeComponent().
helpToolStripMenuItem
System Windows Forms ToolStripMenuItem IG.Forms.HashControl.helpToolStripMenuItem private
Referenced by IG.Forms.HashControl.InitializeComponent().
aboutToolStripMenuItem
System Windows Forms ToolStripMenuItem IG.Forms.HashControl.aboutToolStripMenuItem private
Referenced by IG.Forms.HashControl.InitializeComponent().
btnInfo
System Windows Forms Button IG.Forms.HashControl.btnInfo private
Referenced by IG.Forms.HashControl.InitializeComponent().
contextMenuStrip1
System.Windows.Forms.ContextMenuStrip IG.Forms.HashControl.contextMenuStrip1 private
Referenced by IG.Forms.HashControl.InitializeComponent().
contextMenuStrip2
System.Windows.Forms.ContextMenuStrip IG.Forms.HashControl.contextMenuStrip2 private
Referenced by IG.Forms.HashControl.InitializeComponent().
Property Documentation
FadingMessageShowTimeMs
int IG.Forms.HashControl.FadingMessageShowTimeMs get set protected
Referenced by IG.Forms.HashControl.CancelHashCalculations(), IG.Forms.HashControl.FadingMessageError(), IG.Forms.HashControl.FadingMessageInfo(), and IG.Forms.HashControl.FadingMessageWarning().
DirectoryPath
string IG.Forms.HashControl.DirectoryPath get set
Directory where files are currently selected.
Referenced by IG.Forms.HashControl.BrowseFile(), IG.Forms.HashForm.InitializeComponent(), and IG.Forms.HashAllControl.InitializeComponent().
FilePath
string IG.Forms.HashControl.FilePath get set
Path to the file whose hash values are calculated.
Referenced by IG.Forms.HashControl.backgroundWorker1_DoWork(), IG.Forms.HashControl.BrowseFile(), IG.Forms.HashControl.btnFileBrowse_Click(), IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.GenerateFilePreview(), IG.Forms.HashControl.GetFileOrTextLength(), IG.Forms.HashAllControl.InitializeComponent(), IG.Forms.HashForm.InitializeComponent(), IG.Forms.HashControl.rbFile_CheckedChanged(), IG.Forms.HashControl.SaveHashesToFile(), IG.Forms.HashControl.txtContents_DragDrop(), IG.Forms.HashControl.txtFile_DragDrop(), IG.Forms.HashControl.txtFile_Validated(), and IG.Forms.HashControl.VerifyHash().
IsAllHashesCalculated
bool IG.Forms.HashControl.IsAllHashesCalculated get protected
Referenced by IG.Forms.HashControl.backgroundWorker1_RunWorkerCompleted(), IG.Forms.HashControl.chkMd5_CheckedChanged(), IG.Forms.HashControl.chkSha1_CheckedChanged(), IG.Forms.HashControl.chkSha256_CheckedChanged(), and IG.Forms.HashControl.chkSha512_CheckedChanged().
CalculateAllCanceled
bool IG.Forms.HashControl.CalculateAllCanceled get set protected
Referenced by IG.Forms.HashControl.CalculateHashAsync(), IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.CancelHashCalculations(), and IG.Forms.HashControl.HashControl().
IsGroupCalculationPerformed
bool IG.Forms.HashControl.IsGroupCalculationPerformed get set protected
Referenced by IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.HashControl(), and IG.Forms.HashControl.txtContents_TextChanged().
RecalculateHashes
bool IG.Forms.HashControl.RecalculateHashes get set protected
Referenced by IG.Forms.HashControl.CalculateHashes(), IG.Forms.HashControl.ClearHashes(), IG.Forms.HashControl.rbFile_CheckedChanged(), and IG.Forms.HashControl.txtContents_TextChanged().
LastArguments
HashJobArgumentsAndResults IG.Forms.HashControl.LastArguments get set protected
Referenced by IG.Forms.HashControl.backgroundWorker1_DoWork(), and IG.Forms.HashControl.CalculateHashes().
LastResults
HashJobArgumentsAndResults IG.Forms.HashControl.LastResults get set protected
Referenced by IG.Forms.HashControl.backgroundWorker1_RunWorkerCompleted(), and IG.Forms.HashControl.CalculateHashes().
_form
Form IG.Forms.HashControl._form get private
Referenced by IG.Forms.HashControl.Common_MouseMove(), IG.Forms.HashControl.InitiateMoveOrSize(), and IG.Forms.HashControl.txtContents_DragDrop().
ControlDown
bool IG.Forms.HashControl.ControlDown get private
Indicates whether Control key is currently pressed.
Referenced by IG.Forms.HashControl.Common_MouseMove(), IG.Forms.HashControl.InitiateMoveOrSize(), and IG.Forms.HashControl.SetCursorMouseDown().
ShiftDown
bool IG.Forms.HashControl.ShiftDown get private
Indicates whether Shift key is currently pressed.
Referenced by IG.Forms.HashControl.InitiateMoveOrSize(), and IG.Forms.HashControl.SetCursorMouseDown().
AltDown
bool IG.Forms.HashControl.AltDown get private
Indicates whether Alt key is currently pressed.
Referenced by IG.Forms.HashControl.Common_MouseDownOnInteractive(), IG.Forms.HashControl.Common_MouseMove(), and IG.Forms.HashControl.SetCursorMouseDown().
MouseX
int IG.Forms.HashControl.MouseX get private
Gets X component of current mouse cursor position (global, distance from left edge of display).
Referenced by IG.Forms.HashControl.Common_MouseMove(), and IG.Forms.HashControl.InitiateMoveOrSize().
MouseY
int IG.Forms.HashControl.MouseY get private
Gets Y component of current mouse cursor position (global, distance from top edge of display).
Referenced by IG.Forms.HashControl.Common_MouseMove(), and IG.Forms.HashControl.InitiateMoveOrSize().
MouseRelX
double IG.Forms.HashControl.MouseRelX get private
Mouse relative X position within the form (runs from -0.5 to 0.5).
Referenced by IG.Forms.HashControl.InitiateMoveOrSize().
MouseRelY
double IG.Forms.HashControl.MouseRelY get private
Mouse relative Y position within the form (runs from -0.5 to 0.5).
Referenced by IG.Forms.HashControl.InitiateMoveOrSize().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/Cryptography/HashControl.cs
iglib/igforms/Utilities/Cryptography/HashControl.Designer.cs