Doc: IGLib EXTENDED: NUnit.Framework.Tests.Attributes.AuthorTests Class Reference
NUnit.Framework.Tests.Attributes.AuthorTests Class Reference
Public Member Functions
void ReflectionTest ()
void Author ()
void NoAuthor ()
void FixtureAuthor ()
void SeparateAuthorAttribute ()
void SeparateAuthorWithEmailAttribute ()
void AuthorOnTestCase ()
Static Private Attributes
static readonly Type FixtureType = typeof(AuthorFixture)
Member Function Documentation
ReflectionTest()
void NUnit.Framework.Tests.Attributes.AuthorTests.ReflectionTest () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Tests.Attributes.AuthorTests.FixtureType, NUnit.TestUtilities.TestBuilder.MakeTestCase(), and NUnit.Framework.Internal.Test.RunState.
Author()
void NUnit.Framework.Tests.Attributes.AuthorTests.Author () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.PropertyNames.Author, NUnit.Framework.Tests.Attributes.AuthorTests.FixtureType, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeTestCase(), and NUnit.Framework.Internal.Test.Properties.
NoAuthor()
void NUnit.Framework.Tests.Attributes.AuthorTests.NoAuthor () inline
References NUnit.Framework.Internal.PropertyNames.Author, NUnit.Framework.Tests.Attributes.AuthorTests.FixtureType, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.Framework.Assert.IsNull(), NUnit.TestUtilities.TestBuilder.MakeTestCase(), and NUnit.Framework.Internal.Test.Properties.
FixtureAuthor()
void NUnit.Framework.Tests.Attributes.AuthorTests.FixtureAuthor () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.PropertyNames.Author, NUnit.Framework.Tests.Attributes.AuthorTests.FixtureType, and NUnit.TestUtilities.TestBuilder.MakeFixture().
SeparateAuthorAttribute()
void NUnit.Framework.Tests.Attributes.AuthorTests.SeparateAuthorAttribute () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.PropertyNames.Author, NUnit.Framework.Tests.Attributes.AuthorTests.FixtureType, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeTestCase(), and NUnit.Framework.Internal.Test.Properties.
SeparateAuthorWithEmailAttribute()
void NUnit.Framework.Tests.Attributes.AuthorTests.SeparateAuthorWithEmailAttribute () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.PropertyNames.Author, NUnit.Framework.Tests.Attributes.AuthorTests.FixtureType, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeTestCase(), and NUnit.Framework.Internal.Test.Properties.
AuthorOnTestCase()
void NUnit.Framework.Tests.Attributes.AuthorTests.AuthorOnTestCase () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.PropertyNames.Author, NUnit.Framework.Tests.Attributes.AuthorTests.FixtureType, NUnit.Framework.Interfaces.IPropertyBag.Get(), NUnit.TestUtilities.TestBuilder.MakeParameterizedMethodSuite(), NUnit.Framework.Internal.Test.Properties, and NUnit.Framework.Internal.TestSuite.Tests.
Member Data Documentation
FixtureType
readonly Type NUnit.Framework.Tests.Attributes.AuthorTests.FixtureType = typeof(AuthorFixture) static private
Referenced by NUnit.Framework.Tests.Attributes.AuthorTests.Author(), NUnit.Framework.Tests.Attributes.AuthorTests.AuthorOnTestCase(), NUnit.Framework.Tests.Attributes.AuthorTests.FixtureAuthor(), NUnit.Framework.Tests.Attributes.AuthorTests.NoAuthor(), NUnit.Framework.Tests.Attributes.AuthorTests.ReflectionTest(), NUnit.Framework.Tests.Attributes.AuthorTests.SeparateAuthorAttribute(), and NUnit.Framework.Tests.Attributes.AuthorTests.SeparateAuthorWithEmailAttribute().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/AuthorTests.cs