Doc: IGLib EXTENDED: IG.Lib.StringSettings Class Reference
IG.Lib.StringSettings Class Reference
Public Member Functions
StringSettings ()
override void Export (string filePath)
Saves (serializes) the specified variable system to the specified JSON file.
override void Export (string filePath, bool append)
Saves (serializes) the specified variable system to the specified JSON file.
override void Import (string filePath)
Imports variables from the specified variable system in JSON format.
bool LockFileMutexCheckAbandoned ()
Check whether the filesystem locking mutex (property LockFileMutex) has been abandoned, and returns true if it has been (otherwise, false is returned).
int AddSettingDirectories (params string[] directoryPaths)
Adds the specified directory paths to the list of directories that are periodically checked for settings to be imported.
int RemoveSettingDirectories (params string[] directoryPaths)
Removes the specified directory paths to the list of directories that are periodically checked for settings to be imported.
bool IsPeriodicImportCheckPerformed ()
Returns a flag indicating whether the state of the current setting object is such that periodic checks and imports of settings form files are performed.
Public Member Functions inherited from IG.Lib.StringVariableSystem
StringVariableSystem ()
Constructs a new system of string variables.
virtual string GetVariable (string varName)
Returns value of the specified variable, or null if it is not defined.
virtual void SetVariable (string varName, string varValue)
Sets the specified variable to the specified value.
virtual void AddNewVariable (string varName, string varValue)
Adds a new variable of the specified name and with the specified value (which can be null).
virtual bool RemoveVariable (string varName)
Removes a variable with the specified name from the current variable system, and returns a flag indicating whether variable was actually removed.
virtual int RemoveVariables (params string[] varNames)
Removes all variables whose names are specified by the argument, and returns the number of variables that were actully been removed.
virtual bool UnSetVariable (string varName)
Unsets the variable with the specified name on the current variable system, and returns a flag indicating whether variable was defined.
virtual bool IsVariableDefined (string varName)
Returns true if the specified variable is defined, false otherwise.
virtual string[][] ToArray ()
Returns array representation of variables that are currently defined on the system.
virtual void ImportVariables (string[][] variables)
Imports variables defined in form of two dimensional array.
virtual void SetVariable (string varName, object varValue)
Sets the specified variable to the specified value.
bool TryGetIntegerVariable (string varName, out int varTypedValue)
Obtains a value of an integer-typed variable of the specified name, if such a variable is defined and its value can be interpreted as an integer.
int GetIntegerVariable (string varName)
Returns the value of an integer-valued variable of the specified name.
bool TryGetDoubleVariable (string varName, out double varTypedValue)
Obtains a value of a double-typed variable of the specified name, if such a variable is defined and its value can be interpreted as a number of type double.
double GetDoubleVariable (string varName)
Returns the value of a double-valued variable of the specified name.
bool TryGetBooleanVariable (string varName, out bool varTypedValue)
Obtains a value of a boolean-typed variable of the specified name, if such a variable is defined and its value can be interpreted as a boolean value.
bool GetBooleanVariable (string varName)
Returns the value of a boolean-valued variable of the specified name.
bool GetFlag (string flagName)
Returns value of the flag with the specified name.
void SetFlag (string flagName, bool flagValue)
Sets the flag of the specified name to the specified value.
void PrintVariables ()
Prints all variables (with their values) defined on the current object.
Static Public Member Functions
static void SaveJson (StringSettings settings, string filePath)
Saves (serializes) the specified variable system to the specified JSON file. File is owerwritten if it exists.
static void SaveJson (StringSettings settings, string filePath, bool append)
Saves (serializes) the specified variable system to the specified JSON file. If the file already exists, contents either overwrites the file or is appended at the end, dependent on the value of the append flag.
static void LoadJson (string filePath, ref StringSettings settingsRestored)
Restores (deserializes) a vector from the specified file in JSON format.
static void ExportDto (StringSettingsDto settings, string filePath)
Saves (serializes) the specified variable system DTO to the specified JSON file.
static void ExportDto (StringSettingsDto variables, string filePath, bool append)
Saves (serializes) the specified variable system DTO to the specified JSON file.
static void ImportDto (string filePath, ref StringSettingsDto settings)
Restores (deserializes) variable system DTO from the specified file in JSON format.
Static Public Member Functions inherited from IG.Lib.StringVariableSystem
static void SaveJson (StringVariableSystem variableSystem, string filePath)
Saves (serializes) the specified variable system to the specified JSON file. File is owerwritten if it exists.
static void SaveJson (StringVariableSystem variableSystem, string filePath, bool append)
Saves (serializes) the specified variable system to the specified JSON file. If the file already exists, contents either overwrites the file or is appended at the end, dependent on the value of the append flag.
static void LoadJson (string filePath, ref StringVariableSystem variableSystemRestored)
Restores (deserializes) a vector from the specified file in JSON format.
static void ExportDto (StringVariableSystemDto settings, string filePath)
Saves (serializes) the specified variable system DTO to the specified JSON file.
static void ExportDto (StringVariableSystemDto variables, string filePath, bool append)
Saves (serializes) the specified variable system DTO to the specified JSON file.
static void ImportDto (string filePath, ref StringVariableSystemDto settings)
Restores (deserializes) variable system DTO from the specified file in JSON format.
static void TestMisc ()
Miscellaneous tests.
Static Public Attributes
const string DefaultLockFileMutexName = "Global\\IG.Lib.Utils.MutexSettingsDefault.R2D2_by_Igor_Gresovnik"
Default name of the mutex for system-wide locking of files used by the current class.
const string DefaultImportingFilename = "settingsglobal.json"
Default name of the file containing settings to be imported.
const string DefaultMsgImportOnceFilename = "importsettings.msg"
Default name of the message file instructing object of this class to import the settings file once and then delete the message.
const string DefaultMsgImportContinuoslyFilename = "importsettingscontinuously.msg"
Default name of the message file instructing object of this class to continuously import the settings file without deleting the message.
const double DefaultImportCheckPeriodSeconds = 1.0421
Default period for checking for settings to be imported (ind importing them, if applicable).
const double MinimalImportCheckPeriodSeconds = 0.01
Minimal period for checking for settings to be imported (ind importing them, if applicable).
Protected Member Functions
bool CheckAndImport (string directoryPath)
Check the directory with the specified path for instructions to import the settings file, imports the settings file if instructed so and if the settings file exists, and eventualy removes the message instructing a single import.
void ImportPeriodically ()
Periodically checks the designated directories for settings to be imported, and imports them if availeble.
void StartImportingThreadIfNotRunning ()
Starts the thread that periodically checks for settings to be imported and imports them.
void StopImportingThreadIfRunning ()
Stops the thread that periodically checks for settings to be imported and imports them.
void OnChangedImportingStatus ()
Method that is called every time the state of variables that influence how periodic importing is done, is changed.
Protected Attributes
string _lockFileMutexName = DefaultLockFileMutexName
Mutex _lockFileMutex
string _msgImportOnceFilename = DefaultMsgImportOnceFilename
string _msgImportContinuouslyFilename = DefaultMsgImportContinuoslyFilename
string _importingFilename = DefaultImportingFilename
bool _doImportPeriodically = true
double _importCheckPeriodSeconds = DefaultImportCheckPeriodSeconds
Thread _importingThread
Protected Attributes inherited from IG.Lib.StringVariableSystem
SortedList< string, string > _variables = new SortedList<string, string>()
Properties
string LockFileMutexName [get, set]
Name of the mutex for system-wide locking of files used by the current class.
virtual Mutex LockFileMutex [get, set]
Mutex for system-wide exclusive locks for file system operations related to the current class.
string MsgImportOnceFilename [get, set]
Name of the message file instructing object of this class to import the settings file once and then delete the message.
string MsgImportContinuoslyFilename [get, set]
Name of the message file instructing object of this class to continuously import the settings file without deleting the message.
string ImportingFilename [get, set]
Name of the message file instructing object of this class to continuously import the settings file without deleting the message.
bool DoImportPeriodically [get, set]
Flag indicating whether the current object should periodically check the designated directories for settings to be imported, and import them.
double ImportCheckPeriodSeconds [get, set]
Period for checking for settings to be imported (ind importing them, if applicable).
List< string > SettingDirectories [get]
Properties inherited from IG.Lib.StringVariableSystem
object Lock [get]
This object's central lock object to be used by other object.
bool SetNullOnImport [get, set]
Flag indicating whether null variable values are also set when importing variable values. If false then, if some imported variable has null value, this variable will not be set on the current system of variables. This means that the value of eventually existent variable will remain unchanged if variables are imported from another system where this variable is defined but has null value.
virtual SortedList< string, string > Variables [get]
virtual string this[string varName] [get, set]
Gets or sets value of the specified variable.
Properties inherited from IG.Lib.ILockable
object Lock [get]
Private Attributes
List< string > _settingDirectories
Constructor & Destructor Documentation
StringSettings()
IG.Lib.StringSettings.StringSettings () inline
Member Function Documentation
Export() [1/2]
override void IG.Lib.StringSettings.Export (string filePath) inline virtual
Saves (serializes) the specified variable system to the specified JSON file.
If the file already exists, contents overwrite the file.
Parameters
filePath Path to the file in variables and properties of the system are saved.
Reimplemented from IG.Lib.StringVariableSystem.
Export() [2/2]
override void IG.Lib.StringSettings.Export (string filePath, bool append) inline virtual
Saves (serializes) the specified variable system to the specified JSON file.
If the file already exists, contents either overwrite the file or are appended at the end, dependent on the value of the append flag.
Parameters
filePath Path to the file in variables and properties of the system are saved.
append Specifies whether serialized data is appended at the end of the file in the case that the file already exists.
Reimplemented from IG.Lib.StringVariableSystem.
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyFrom(), and IG.Lib.StringSettings.ExportDto().
Import()
override void IG.Lib.StringSettings.Import (string filePath) inline virtual
Imports variables from the specified variable system in JSON format.
Parameters
filePath File from which object is restored.
Reimplemented from IG.Lib.StringVariableSystem.
References IG.Lib.StringSettings.ImportDto().
Referenced by IG.Lib.StringSettings.CheckAndImport().
SaveJson() [1/2]
static void IG.Lib.StringSettings.SaveJson (StringSettings settings, string filePath) inline static
Saves (serializes) the specified variable system to the specified JSON file. File is owerwritten if it exists.
Parameters
settings Object that is saved to a file.
filePath Path to the file in which object is is saved.
SaveJson() [2/2]
static void IG.Lib.StringSettings.SaveJson (StringSettings settings, string filePath, bool append) inline static
Saves (serializes) the specified variable system to the specified JSON file. If the file already exists, contents either overwrites the file or is appended at the end, dependent on the value of the append flag.
Parameters
settings Object that is saved to a file.
filePath Path to the file into which object is saved.
append Specifies whether serialized data is appended at the end of the file in the case that the file already exists.
LoadJson()
static void IG.Lib.StringSettings.LoadJson (string filePath, ref StringSettings settingsRestored) inline static
Restores (deserializes) a vector from the specified file in JSON format.
Parameters
filePath File from which object is restored.
settingsRestored Object that is restored by deserialization.
ExportDto() [1/2]
static void IG.Lib.StringSettings.ExportDto (StringSettingsDto settings, string filePath) inline static
Saves (serializes) the specified variable system DTO to the specified JSON file.
If the file already exists, contents overwrite the file.
Parameters
settings Variable system DTO that is saved to a file.
filePath Path to the file into which variables (and settings and other stuff) are saved.
Referenced by IG.Lib.StringSettings.Export().
ExportDto() [2/2]
static void IG.Lib.StringSettings.ExportDto (StringSettingsDto variables, string filePath, bool append) inline static
Saves (serializes) the specified variable system DTO to the specified JSON file.
If the file already exists, contents either overwrite the file or are appended at the end, dependent on the value of the append flag.
Parameters
variables Variable system DTO that is saved to a file.
filePath Path to the file into which variables (and settings and other stuff) are saved.
append Specifies whether serialized data is appended at the end of the file in the case that the file already exists.
ImportDto()
static void IG.Lib.StringSettings.ImportDto (string filePath, ref StringSettingsDto settings) inline static
Restores (deserializes) variable system DTO from the specified file in JSON format.
The restored DTO can be used e.g. to import variables to a variable system.
Parameters
filePath File from which object is restored.
settings Variable system DTO that is restored by deserialization.
Referenced by IG.Lib.StringSettings.Import().
LockFileMutexCheckAbandoned()
bool IG.Lib.StringSettings.LockFileMutexCheckAbandoned () inline
Check whether the filesystem locking mutex (property LockFileMutex) has been abandoned, and returns true if it has been (otherwise, false is returned).
After the call, mutex is no longer in abandoned state (WaitOne() will not throw an exception) if it has been before the call.
Call does not block.
Returns
true if mutex has been abandoned, false otherwise.
References IG.Lib.StringSettings.LockFileMutex, and IG.Lib.Util.MutexCheckAbandoned().
AddSettingDirectories()
int IG.Lib.StringSettings.AddSettingDirectories (params string[] directoryPaths) inline
Adds the specified directory paths to the list of directories that are periodically checked for settings to be imported.
Parameters
directoryPaths Paths to be added to the list, can be relative or absolute.
Returns
Number of directories that were actually added to the list.
References IG.Lib.ILockable.Lock, IG.Lib.StringSettings.OnChangedImportingStatus(), IG.Lib.StringSettings.SettingDirectories, and IG.Lib.UtilSystem.StandardizeDirectoryPath().
RemoveSettingDirectories()
int IG.Lib.StringSettings.RemoveSettingDirectories (params string[] directoryPaths) inline
Removes the specified directory paths to the list of directories that are periodically checked for settings to be imported.
Parameters
directoryPaths Paths to be added to the list, can be relative or absolute.
Returns
Number of directories that were actually removed from the list.
References IG.Lib.ILockable.Lock, IG.Lib.StringSettings.OnChangedImportingStatus(), IG.Lib.StringSettings.SettingDirectories, and IG.Lib.UtilSystem.StandardizeDirectoryPath().
CheckAndImport()
bool IG.Lib.StringSettings.CheckAndImport (string directoryPath) inline protected
Check the directory with the specified path for instructions to import the settings file, imports the settings file if instructed so and if the settings file exists, and eventualy removes the message instructing a single import.
Returns true if settings were imported, false otherwise.
Parameters
directoryPath Path to the directory where settings are checked.
References IG.Lib.StringSettings.Import(), IG.Lib.StringSettings.ImportingFilename, IG.Lib.StringSettings.LockFileMutex, IG.Lib.StringSettings.MsgImportContinuoslyFilename, and IG.Lib.StringSettings.MsgImportOnceFilename.
Referenced by IG.Lib.StringSettings.ImportPeriodically().
ImportPeriodically()
void IG.Lib.StringSettings.ImportPeriodically () inline protected
Periodically checks the designated directories for settings to be imported, and imports them if availeble.
Check and import is performed by the CheckAndImport method.
References IG.Lib.StringSettings.CheckAndImport(), IG.Lib.StringSettings.DoImportPeriodically, IG.Lib.StringSettings.ImportCheckPeriodSeconds, IG.Lib.ILockable.Lock, IG.Lib.StringSettings.SettingDirectories, and IG.Lib.Util.SleepSeconds().
Referenced by IG.Lib.StringSettings.StartImportingThreadIfNotRunning().
IsPeriodicImportCheckPerformed()
bool IG.Lib.StringSettings.IsPeriodicImportCheckPerformed () inline
Returns a flag indicating whether the state of the current setting object is such that periodic checks and imports of settings form files are performed.
References IG.Lib.StringSettings.DoImportPeriodically, IG.Lib.ILockable.Lock, and IG.Lib.StringSettings.SettingDirectories.
Referenced by IG.Lib.StringSettings.OnChangedImportingStatus().
StartImportingThreadIfNotRunning()
void IG.Lib.StringSettings.StartImportingThreadIfNotRunning () inline protected
Starts the thread that periodically checks for settings to be imported and imports them.
References IG.Lib.StringSettings._importingThread, IG.Lib.StringSettings.ImportPeriodically(), and IG.Lib.ILockable.Lock.
Referenced by IG.Lib.StringSettings.OnChangedImportingStatus().
StopImportingThreadIfRunning()
void IG.Lib.StringSettings.StopImportingThreadIfRunning () inline protected
Stops the thread that periodically checks for settings to be imported and imports them.
References IG.Lib.StringSettings._importingThread, and IG.Lib.ILockable.Lock.
Referenced by IG.Lib.StringSettings.OnChangedImportingStatus().
OnChangedImportingStatus()
void IG.Lib.StringSettings.OnChangedImportingStatus () inline protected
Method that is called every time the state of variables that influence how periodic importing is done, is changed.
This method checks whether periodic checking should be performed or not. If it should be performed, then it starts the thread that does it, if it is not already running. If it sould not be performed, then it stops that tread if it is running.
References IG.Lib.StringSettings.IsPeriodicImportCheckPerformed(), IG.Lib.StringSettings.StartImportingThreadIfNotRunning(), and IG.Lib.StringSettings.StopImportingThreadIfRunning().
Referenced by IG.Lib.StringSettings.AddSettingDirectories(), and IG.Lib.StringSettings.RemoveSettingDirectories().
Member Data Documentation
DefaultLockFileMutexName
const string IG.Lib.StringSettings.DefaultLockFileMutexName = "Global\\IG.Lib.Utils.MutexSettingsDefault.R2D2_by_Igor_Gresovnik" static
Default name of the mutex for system-wide locking of files used by the current class.
DefaultImportingFilename
const string IG.Lib.StringSettings.DefaultImportingFilename = "settingsglobal.json" static
Default name of the file containing settings to be imported.
DefaultMsgImportOnceFilename
const string IG.Lib.StringSettings.DefaultMsgImportOnceFilename = "importsettings.msg" static
Default name of the message file instructing object of this class to import the settings file once and then delete the message.
DefaultMsgImportContinuoslyFilename
const string IG.Lib.StringSettings.DefaultMsgImportContinuoslyFilename = "importsettingscontinuously.msg" static
Default name of the message file instructing object of this class to continuously import the settings file without deleting the message.
DefaultImportCheckPeriodSeconds
const double IG.Lib.StringSettings.DefaultImportCheckPeriodSeconds = 1.0421 static
Default period for checking for settings to be imported (ind importing them, if applicable).
MinimalImportCheckPeriodSeconds
const double IG.Lib.StringSettings.MinimalImportCheckPeriodSeconds = 0.01 static
Minimal period for checking for settings to be imported (ind importing them, if applicable).
_lockFileMutexName
string IG.Lib.StringSettings._lockFileMutexName = DefaultLockFileMutexName protected
_lockFileMutex
Mutex IG.Lib.StringSettings._lockFileMutex protected
_msgImportOnceFilename
string IG.Lib.StringSettings._msgImportOnceFilename = DefaultMsgImportOnceFilename protected
_msgImportContinuouslyFilename
string IG.Lib.StringSettings._msgImportContinuouslyFilename = DefaultMsgImportContinuoslyFilename protected
_importingFilename
string IG.Lib.StringSettings._importingFilename = DefaultImportingFilename protected
_doImportPeriodically
bool IG.Lib.StringSettings._doImportPeriodically = true protected
_importCheckPeriodSeconds
double IG.Lib.StringSettings._importCheckPeriodSeconds = DefaultImportCheckPeriodSeconds protected
_settingDirectories
List<string> IG.Lib.StringSettings._settingDirectories private
_importingThread
Thread IG.Lib.StringSettings._importingThread protected
Referenced by IG.Lib.StringSettings.StartImportingThreadIfNotRunning(), and IG.Lib.StringSettings.StopImportingThreadIfRunning().
Property Documentation
LockFileMutexName
string IG.Lib.StringSettings.LockFileMutexName get set
Name of the mutex for system-wide locking of files used by the current class.
LockFileMutex
virtual Mutex IG.Lib.StringSettings.LockFileMutex get set protected
Mutex for system-wide exclusive locks for file system operations related to the current class.
Referenced by IG.Lib.StringSettings.CheckAndImport(), and IG.Lib.StringSettings.LockFileMutexCheckAbandoned().
MsgImportOnceFilename
string IG.Lib.StringSettings.MsgImportOnceFilename get set
Name of the message file instructing object of this class to import the settings file once and then delete the message.
Referenced by IG.Lib.StringSettings.CheckAndImport().
MsgImportContinuoslyFilename
string IG.Lib.StringSettings.MsgImportContinuoslyFilename get set
Name of the message file instructing object of this class to continuously import the settings file without deleting the message.
Referenced by IG.Lib.StringSettings.CheckAndImport().
ImportingFilename
string IG.Lib.StringSettings.ImportingFilename get set
Name of the message file instructing object of this class to continuously import the settings file without deleting the message.
Referenced by IG.Lib.StringSettings.CheckAndImport().
DoImportPeriodically
bool IG.Lib.StringSettings.DoImportPeriodically get set protected
Flag indicating whether the current object should periodically check the designated directories for settings to be imported, and import them.
Directories that are checked for settings are set by the AddSettingDirectories and RemoveSettingDirectories methods. Time periods are specified by the ImportCheckPeriodSeconds property.
Checking and importing settings is performed by the CheckAndImport method.
Referenced by IG.Lib.StringSettings.ImportPeriodically(), and IG.Lib.StringSettings.IsPeriodicImportCheckPerformed().
ImportCheckPeriodSeconds
double IG.Lib.StringSettings.ImportCheckPeriodSeconds get set
Period for checking for settings to be imported (ind importing them, if applicable).
Referenced by IG.Lib.StringSettings.ImportPeriodically().
SettingDirectories
List<string> IG.Lib.StringSettings.SettingDirectories get protected
Referenced by IG.Lib.StringSettings.AddSettingDirectories(), IG.Lib.StringSettings.ImportPeriodically(), IG.Lib.StringSettings.IsPeriodicImportCheckPerformed(), and IG.Lib.StringSettings.RemoveSettingDirectories().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev/varstring/VarSettings.cs