Doc: IGLib EXTENDED: alglib.testkmeansunit Class Reference
alglib.testkmeansunit Class Reference
Static Public Member Functions
static bool testkmeans (bool silent)
Static Private Member Functions
static void simpletest1 (int nvars, int nc, int passcount, ref bool converrors, ref bool othererrors, ref bool simpleerrors)
static void restartstest (ref bool converrors, ref bool restartserrors)
static double rnormal ()
static void rsphere (ref double[,] xy, int n, int i)
Member Function Documentation
testkmeans()
static bool alglib.testkmeansunit.testkmeans (bool silent) inline static
References alglib.testkmeansunit.restartstest(), and alglib.testkmeansunit.simpletest1().
Referenced by _Test.Main().
simpletest1()
static void alglib.testkmeansunit.simpletest1 (int nvars, int nc, int passcount, ref bool converrors, ref bool othererrors, ref bool simpleerrors) inline static private
References alglib.kmeans.kmeansgenerate(), alglib.math.maxrealnumber, alglib.math.randominteger(), and alglib.testkmeansunit.rsphere().
Referenced by alglib.testkmeansunit.testkmeans().
restartstest()
static void alglib.testkmeansunit.restartstest (ref bool converrors, ref bool restartserrors) inline static private
References alglib.kmeans.kmeansgenerate(), and alglib.testkmeansunit.rsphere().
Referenced by alglib.testkmeansunit.testkmeans().
rnormal()
static double alglib.testkmeansunit.rnormal () inline static private
References alglib.math.randomreal(), and alglib.math.sqr().
Referenced by alglib.testkmeansunit.rsphere().
rsphere()
static void alglib.testkmeansunit.rsphere (ref double xy[,], int n, int i) inline static private
References alglib.math.randomreal(), and alglib.testkmeansunit.rnormal().
Referenced by alglib.testkmeansunit.restartstest(), and alglib.testkmeansunit.simpletest1().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs