Doc: IGLib EXTENDED: NUnit.Framework.Contains Class Reference
NUnit.Framework.Contains Class Reference
Helper class with properties and methods that supply a number of constraints used in Asserts.
Static Public Member Functions
static CollectionContainsConstraint Item (object expected)
Returns a new CollectionContainsConstraint checking for the presence of a particular object in the collection.
static DictionaryContainsKeyConstraint Key (object expected)
Returns a new DictionaryContainsKeyConstraint checking for the presence of a particular key in the dictionary.
static DictionaryContainsValueConstraint Value (object expected)
Returns a new DictionaryContainsValueConstraint checking for the presence of a particular value in the dictionary.
static SubstringConstraint Substring (string expected)
Returns a constraint that succeeds if the actual value contains the substring supplied as an argument.
Detailed Description
Helper class with properties and methods that supply a number of constraints used in Asserts.
Member Function Documentation
Item()
static CollectionContainsConstraint NUnit.Framework.Contains.Item (object expected) inline static
Returns a new CollectionContainsConstraint checking for the presence of a particular object in the collection.
Referenced by NUnit.Framework.Attributes.CategoryAttributeTests.CanDeriveFromCategoryAttribute(), NUnit.Framework.Attributes.CategoryAttributeTests.CanSpecifyOnMethodAndTestCase(), NUnit.Framework.Attributes.CategoryAttributeTests.CategoryOnFixture(), NUnit.Framework.Attributes.CategoryAttributeTests.CategoryOnTestMethod(), NUnit.Framework.Attributes.CategoryAttributeTests.DerivedCategoryMayBeInherited(), NUnit.Framework.Internal.PropertyBagTests.IndexGetsListOfValues(), NUnit.Framework.Internal.PropertyBagTests.IndexSetsListOfValues(), and NUnit.ConsoleRunner.Tests.MakeTestPackageTests.WhenNoOptionsAreSpecified_PackageContainsWorkDirectorySettingOnly().
Key()
static DictionaryContainsKeyConstraint NUnit.Framework.Contains.Key (object expected) inline static
Returns a new DictionaryContainsKeyConstraint checking for the presence of a particular key in the dictionary.
Value()
static DictionaryContainsValueConstraint NUnit.Framework.Contains.Value (object expected) inline static
Returns a new DictionaryContainsValueConstraint checking for the presence of a particular value in the dictionary.
Substring()
static SubstringConstraint NUnit.Framework.Contains.Substring (string expected) inline static
Returns a constraint that succeeds if the actual value contains the substring supplied as an argument.
Referenced by NUnitLite.Tests.TextUITests.DisplayRuntimeEnvironment(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.ExploreTestsAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.LoadTestsAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_BadFile_ReturnsNonRunnableSuite(), NUnit.Framework.Api.FrameworkControllerTests.RunTestsAction_FileNotFound_ReturnsNonRunnableSuite(), NUnit.Engine.Services.ResultWriters.Tests.XmlTransformResultWriterTests.SummaryTransformTest(), and NUnit.Framework.Internal.TestXmlTests.TestNameWithInvalidCharacter().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Contains.cs