Doc: IGLib EXTENDED: NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder Class Reference
NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder Class Reference
NUnitTestCaseBuilder is a utility class used by attributes that build test cases.
Public Member Functions
NUnitTestCaseBuilder ()
Constructs an NUnitTestCaseBuilder
TestMethod BuildTestMethod (IMethodInfo method, Test parentSuite, TestCaseParameters parms)
Builds a single NUnitTestMethod, either as a child of the fixture or as one of a set of test cases under a ParameterizedTestMethodSuite.
Static Private Member Functions
static bool CheckTestMethodSignature (TestMethod testMethod, TestCaseParameters parms)
Helper method that checks the signature of a TestMethod and any supplied parameters to determine if the test is valid.
static bool MarkAsNotRunnable (TestMethod testMethod, string reason)
Private Attributes
readonly Randomizer _randomizer = Randomizer.CreateRandomizer()
readonly TestNameGenerator _nameGenerator
Static Private Attributes
const string DEFAULT_TEST_NAME_PATTERN = "{m}{a:40}"
Detailed Description
NUnitTestCaseBuilder is a utility class used by attributes that build test cases.
Constructor & Destructor Documentation
NUnitTestCaseBuilder()
NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.NUnitTestCaseBuilder () inline
Constructs an NUnitTestCaseBuilder
References NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder._nameGenerator, and NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.DEFAULT_TEST_NAME_PATTERN.
Member Function Documentation
BuildTestMethod()
TestMethod NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.BuildTestMethod (IMethodInfo method, Test parentSuite, TestCaseParameters parms) inline
Builds a single NUnitTestMethod, either as a child of the fixture or as one of a set of test cases under a ParameterizedTestMethodSuite.
Parameters
method The MethodInfo from which to construct the TestMethod
parentSuite The suite or fixture to which the new test will be added
parms The ParameterSet to be used, or null
Returns
References NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder._nameGenerator, NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder._randomizer, NUnit.Framework.Internal.TestParameters.ApplyToTest(), NUnit.Framework.Internal.TestParameters.Arguments, NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.CheckTestMethodSignature(), NUnit.Framework.Interfaces.ITypeInfo.FullName, NUnit.Framework.Internal.Test.FullName, NUnit.Framework.Internal.TestNameGenerator.GetDisplayName(), NUnit.Framework.Interfaces.IMethodInfo.MethodInfo, NUnit.Framework.Internal.TestParameters.OriginalArguments, NUnit.Framework.Internal.TestParameters.TestName, and NUnit.Framework.Interfaces.IMethodInfo.TypeInfo.
Referenced by NUnit.Framework.CombiningStrategyAttribute.BuildFrom(), NUnit.Framework.TestCaseSourceAttribute.BuildFrom(), NUnit.Framework.TestCaseAttribute.BuildFrom(), and NUnit.Framework.Internal.Builders.DefaultTestCaseBuilder.BuildSingleTestMethod().
CheckTestMethodSignature()
static bool NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.CheckTestMethodSignature (TestMethod testMethod, TestCaseParameters parms) inline static private
Helper method that checks the signature of a TestMethod and any supplied parameters to determine if the test is valid.
Currently, NUnitTestMethods are required to be public, non-abstract methods, either static or instance, returning void. They may take arguments but the _values must be provided or the TestMethod is not considered runnable.
Methods not meeting these criteria will be marked as non-runnable and the method will return false in that case.
Parameters
testMethod The TestMethod to be checked. If it is found to be non-runnable, it will be modified.
parms Parameters to be used for this test, or null
Returns
True if the method signature is valid, false if not
The return value is no longer used internally, but is retained for testing purposes.
References NUnit.Framework.Internal.TestParameters.Arguments, NUnit.Framework.Internal.TypeHelper.ConvertArgumentList(), NUnit.Framework.Interfaces.ITypeInfo.GetGenericTypeDefinition(), NUnit.Framework.Interfaces.IMethodInfo.GetParameters(), NUnit.Framework.Internal.GenericMethodHelper.GetTypeArguments(), NUnit.Framework.Interfaces.IMethodInfo.IsAbstract, NUnit.Framework.Interfaces.IMethodInfo.IsGenericMethodDefinition, NUnit.Framework.Interfaces.ITypeInfo.IsGenericType, NUnit.Framework.Interfaces.IMethodInfo.IsPublic, NUnit.Framework.Interfaces.ITypeInfo.IsType(), NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.MarkAsNotRunnable(), NUnit.Framework.Internal.Test.Method, and NUnit.Framework.Internal.TypeHelper.NonmatchingType.
Referenced by NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.BuildTestMethod().
MarkAsNotRunnable()
static bool NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.MarkAsNotRunnable (TestMethod testMethod, string reason) inline static private
References NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Interfaces.IPropertyBag.Set(), and NUnit.Framework.Internal.PropertyNames.SkipReason.
Referenced by NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.CheckTestMethodSignature().
Member Data Documentation
DEFAULT_TEST_NAME_PATTERN
const string NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.DEFAULT_TEST_NAME_PATTERN = "{m}{a:40}" static private
Referenced by NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.NUnitTestCaseBuilder().
_randomizer
readonly Randomizer NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder._randomizer = Randomizer.CreateRandomizer() private
Referenced by NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.BuildTestMethod().
_nameGenerator
readonly TestNameGenerator NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder._nameGenerator private
Referenced by NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.BuildTestMethod(), and NUnit.Framework.Internal.Builders.NUnitTestCaseBuilder.NUnitTestCaseBuilder().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/Builders/NUnitTestCaseBuilder.cs