Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGBTRS Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGBTRS Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGBTRS (LSAME lsame, DGEMV dgemv, DGER dger, DSWAP dswap, DTBSV dtbsv, XERBLA xerbla)
DGBTRS ()
void Run (string TRANS, int N, int KL, int KU, int NRHS, double[] AB, int offset_ab, int LDAB, int[] IPIV, int offset_ipiv, ref double[] B, int offset_b, int LDB, ref int INFO)
Private Attributes
LSAME _lsame
DGEMV _dgemv
DGER _dger
DSWAP _dswap
DTBSV _dtbsv
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGBTRS solves a system of linear equations A * X = B or A' * X = B with a general band matrix A using the LU factorization computed by DGBTRF.
/summary>
Constructor & Destructor Documentation
DGBTRS() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGBTRS.DGBTRS (LSAME lsame, DGEMV dgemv, DGER dger, DSWAP dswap, DTBSV dtbsv, XERBLA xerbla) inline
DGBTRS() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGBTRS.DGBTRS () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGBTRS.Run (string TRANS, int N, int KL, int KU, int NRHS, double[] AB, int offset_ab, int LDAB, int[] IPIV, int offset_ipiv, ref double[] B, int offset_b, int LDB, ref int INFO) inline
Purpose
DGBTRS solves a system of linear equations A * X = B or A' * X = B with a general band matrix A using the LU factorization computed by DGBTRF.
/summary>
Parameters
TRANS (input) CHARACTER*1 Specifies the form of the system of equations. = 'N': A * X = B (No transpose) = 'T': A'* X = B (Transpose) = 'C': A'* X = B (Conjugate transpose = Transpose) /param>
Parameters
N (input) INTEGER The order of the matrix A. N .GE. 0. /param>
Parameters
KL (input) INTEGER The number of subdiagonals within the band of A. KL .GE. 0. /param>
Parameters
KU (input) INTEGER The number of superdiagonals within the band of A. KU .GE. 0. /param>
Parameters
NRHS (input) INTEGER The number of right hand sides, i.e., the number of columns of the matrix B. NRHS .GE. 0. /param>
Parameters
AB (input) DOUBLE PRECISION array, dimension (LDAB,N) Details of the LU factorization of the band matrix A, as computed by DGBTRF. U is stored as an upper triangular band matrix with KL+KU superdiagonals in rows 1 to KL+KU+1, and the multipliers used during the factorization are stored in rows KL+KU+2 to 2*KL+KU+1. /param>
Parameters
LDAB (input) INTEGER The leading dimension of the array AB. LDAB .GE. 2*KL+KU+1. /param>
Parameters
IPIV (input) INTEGER array, dimension (N) The pivot indices; for 1 .LE. i .LE. N, row i of the matrix was interchanged with row IPIV(i). /param>
Parameters
B (input/output) DOUBLE PRECISION array, dimension (LDB,NRHS) On entry, the right hand side matrix B. On exit, the solution matrix X. /param>
Parameters
LDB (input) INTEGER The leading dimension of the array B. LDB .GE. max(1,N). /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.DGBTRS.ONE, DotNumerics.LinearAlgebra.CSLapack.DSWAP.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DGER.Run(), DotNumerics.LinearAlgebra.CSLapack.DTBSV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGEMV.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGBSV.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DGBTRS._lsame private
_dgemv
DGEMV DotNumerics.LinearAlgebra.CSLapack.DGBTRS._dgemv private
_dger
DGER DotNumerics.LinearAlgebra.CSLapack.DGBTRS._dger private
_dswap
DSWAP DotNumerics.LinearAlgebra.CSLapack.DGBTRS._dswap private
_dtbsv
DTBSV DotNumerics.LinearAlgebra.CSLapack.DGBTRS._dtbsv private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGBTRS._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGBTRS.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGBTRS.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgbtrs.cs