Doc: IGLib EXTENDED: NUnit.Common.Tests.TokenizerTests Class Reference
NUnit.Common.Tests.TokenizerTests Class Reference
Public Member Functions
void NullInputThrowsException ()
void BlankStringReturnsEof ()
void IdentifierTokens ()
void WordsInUnicode ()
void StringWithDoubleQuotes ()
void StringWithSingleQuotes ()
void StringWithSlashes ()
void StringsMayContainEscapedQuoteChar ()
void SymbolTokens_SingleChar ()
void SymbolTokens_DoubleChar ()
void MixedTokens_Simple ()
void MixedTokens_Complex ()
Member Function Documentation
NullInputThrowsException()
void NUnit.Common.Tests.TokenizerTests.NullInputThrowsException () inline
References NUnit.Framework.Throws.ArgumentNullException, and NUnit.Framework.Assert.That().
BlankStringReturnsEof()
void NUnit.Common.Tests.TokenizerTests.BlankStringReturnsEof () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
IdentifierTokens()
void NUnit.Common.Tests.TokenizerTests.IdentifierTokens () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
WordsInUnicode()
void NUnit.Common.Tests.TokenizerTests.WordsInUnicode () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
StringWithDoubleQuotes()
void NUnit.Common.Tests.TokenizerTests.StringWithDoubleQuotes () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
StringWithSingleQuotes()
void NUnit.Common.Tests.TokenizerTests.StringWithSingleQuotes () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
StringWithSlashes()
void NUnit.Common.Tests.TokenizerTests.StringWithSlashes () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
StringsMayContainEscapedQuoteChar()
void NUnit.Common.Tests.TokenizerTests.StringsMayContainEscapedQuoteChar () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
SymbolTokens_SingleChar()
void NUnit.Common.Tests.TokenizerTests.SymbolTokens_SingleChar () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
SymbolTokens_DoubleChar()
void NUnit.Common.Tests.TokenizerTests.SymbolTokens_DoubleChar () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
MixedTokens_Simple()
void NUnit.Common.Tests.TokenizerTests.MixedTokens_Simple () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
MixedTokens_Complex()
void NUnit.Common.Tests.TokenizerTests.MixedTokens_Complex () inline
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/tests/TokenizerTests.cs