Doc: IGLib EXTENDED: NUnit.TestData.TimeoutTestCaseFixture Class Reference
NUnit.TestData.TimeoutTestCaseFixture Class Reference
Public Member Functions
void TestTimeOutNotElapsed ()
void TestTimeOutElapsed ()
void TestTimeOutTestCase (int delay)
Static Private Attributes
const int TIME_OUT_TIME = 100
const int NOT_TIMEOUTED_TIME = 50
const int TIMEOUTED_TIME = 150
Member Function Documentation
TestTimeOutNotElapsed()
void NUnit.TestData.TimeoutTestCaseFixture.TestTimeOutNotElapsed () inline
References NUnit.TestData.TimeoutTestCaseFixture.NOT_TIMEOUTED_TIME, and NUnit.TestData.TimeoutTestCaseFixture.TestTimeOutTestCase().
TestTimeOutElapsed()
void NUnit.TestData.TimeoutTestCaseFixture.TestTimeOutElapsed () inline
References NUnit.TestData.TimeoutTestCaseFixture.TestTimeOutTestCase(), and NUnit.TestData.TimeoutTestCaseFixture.TIMEOUTED_TIME.
TestTimeOutTestCase()
void NUnit.TestData.TimeoutTestCaseFixture.TestTimeOutTestCase (int delay) inline
Referenced by NUnit.TestData.TimeoutTestCaseFixture.TestTimeOutElapsed(), and NUnit.TestData.TimeoutTestCaseFixture.TestTimeOutNotElapsed().
Member Data Documentation
TIME_OUT_TIME
const int NUnit.TestData.TimeoutTestCaseFixture.TIME_OUT_TIME = 100 static private
NOT_TIMEOUTED_TIME
const int NUnit.TestData.TimeoutTestCaseFixture.NOT_TIMEOUTED_TIME = 50 static private
Referenced by NUnit.TestData.TimeoutTestCaseFixture.TestTimeOutNotElapsed().
TIMEOUTED_TIME
const int NUnit.TestData.TimeoutTestCaseFixture.TIMEOUTED_TIME = 150 static private
Referenced by NUnit.TestData.TimeoutTestCaseFixture.TestTimeOutElapsed().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/testdata/TimeoutFixture.cs