Doc: IGLib EXTENDED: IG.Lib.ServiceReferenceWSBase.WSBaseSoapClient Class Reference
IG.Lib.ServiceReferenceWSBase.WSBaseSoapClient Class Reference
Public Member Functions
WSBaseSoapClient ()
WSBaseSoapClient (string endpointConfigurationName)
WSBaseSoapClient (string endpointConfigurationName, string remoteAddress)
WSBaseSoapClient (string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress)
WSBaseSoapClient (System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress)
string TestCount ()
string TestService ()
string TestServiceArg (string commandlineArguments)
string TestServiceArgs (IG.Lib.ServiceReferenceWSBase.ArrayOfString commandlineArguments)
Private Member Functions
IG.Lib.ServiceReferenceWSBase.TestCountResponse IG.Lib.ServiceReferenceWSBase.WSBaseSoap. TestCount (IG.Lib.ServiceReferenceWSBase.TestCountRequest request)
IG.Lib.ServiceReferenceWSBase.TestServiceResponse IG.Lib.ServiceReferenceWSBase.WSBaseSoap. TestService (IG.Lib.ServiceReferenceWSBase.TestServiceRequest request)
IG.Lib.ServiceReferenceWSBase.TestServiceArgResponse IG.Lib.ServiceReferenceWSBase.WSBaseSoap. TestServiceArg (IG.Lib.ServiceReferenceWSBase.TestServiceArgRequest request)
IG.Lib.ServiceReferenceWSBase.TestServiceArgsResponse IG.Lib.ServiceReferenceWSBase.WSBaseSoap. TestServiceArgs (IG.Lib.ServiceReferenceWSBase.TestServiceArgsRequest request)
Constructor & Destructor Documentation
WSBaseSoapClient() [1/5]
IG.Lib.ServiceReferenceWSBase.WSBaseSoapClient.WSBaseSoapClient () inline
WSBaseSoapClient() [2/5]
IG.Lib.ServiceReferenceWSBase.WSBaseSoapClient.WSBaseSoapClient (string endpointConfigurationName) inline
WSBaseSoapClient() [3/5]
IG.Lib.ServiceReferenceWSBase.WSBaseSoapClient.WSBaseSoapClient (string endpointConfigurationName, string remoteAddress) inline
WSBaseSoapClient() [4/5]
IG.Lib.ServiceReferenceWSBase.WSBaseSoapClient.WSBaseSoapClient (string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) inline
WSBaseSoapClient() [5/5]
IG.Lib.ServiceReferenceWSBase.WSBaseSoapClient.WSBaseSoapClient (System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) inline
Member Function Documentation
TestCount() [1/2]
IG.Lib.ServiceReferenceWSBase.TestCountResponse IG.Lib.ServiceReferenceWSBase.WSBaseSoap. IG.Lib.ServiceReferenceWSBase.WSBaseSoapClient.TestCount (IG.Lib.ServiceReferenceWSBase.TestCountRequest request) inline private
Implements IG.Lib.ServiceReferenceWSBase.WSBaseSoap.
TestCount() [2/2]
string IG.Lib.ServiceReferenceWSBase.WSBaseSoapClient.TestCount () inline
References IG.Lib.ServiceReferenceWSBase.TestCountRequest.Body.
TestService() [1/2]
IG.Lib.ServiceReferenceWSBase.TestServiceResponse IG.Lib.ServiceReferenceWSBase.WSBaseSoap. IG.Lib.ServiceReferenceWSBase.WSBaseSoapClient.TestService (IG.Lib.ServiceReferenceWSBase.TestServiceRequest request) inline private
Implements IG.Lib.ServiceReferenceWSBase.WSBaseSoap.
TestService() [2/2]
string IG.Lib.ServiceReferenceWSBase.WSBaseSoapClient.TestService () inline
References IG.Lib.ServiceReferenceWSBase.TestServiceRequest.Body.
TestServiceArg() [1/2]
IG.Lib.ServiceReferenceWSBase.TestServiceArgResponse IG.Lib.ServiceReferenceWSBase.WSBaseSoap. IG.Lib.ServiceReferenceWSBase.WSBaseSoapClient.TestServiceArg (IG.Lib.ServiceReferenceWSBase.TestServiceArgRequest request) inline private
Implements IG.Lib.ServiceReferenceWSBase.WSBaseSoap.
Referenced by IG.Lib.ServiceReferenceWSBase.WSBaseSoapClient.TestServiceArg().
TestServiceArg() [2/2]
string IG.Lib.ServiceReferenceWSBase.WSBaseSoapClient.TestServiceArg (string commandlineArguments) inline
References IG.Lib.ServiceReferenceWSBase.TestServiceArgRequest.Body, IG.Lib.ServiceReferenceWSBase.TestServiceArgResponse.Body, IG.Lib.ServiceReferenceWSBase.TestServiceArgRequestBody.commandlineArguments, IG.Lib.ServiceReferenceWSBase.WSBaseSoapClient.TestServiceArg(), and IG.Lib.ServiceReferenceWSBase.TestServiceArgResponseBody.TestServiceArgResult.
TestServiceArgs() [1/2]
IG.Lib.ServiceReferenceWSBase.TestServiceArgsResponse IG.Lib.ServiceReferenceWSBase.WSBaseSoap. IG.Lib.ServiceReferenceWSBase.WSBaseSoapClient.TestServiceArgs (IG.Lib.ServiceReferenceWSBase.TestServiceArgsRequest request) inline private
Implements IG.Lib.ServiceReferenceWSBase.WSBaseSoap.
Referenced by IG.Lib.ServiceReferenceWSBase.WSBaseSoapClient.TestServiceArgs().
TestServiceArgs() [2/2]
string IG.Lib.ServiceReferenceWSBase.WSBaseSoapClient.TestServiceArgs (IG.Lib.ServiceReferenceWSBase.ArrayOfString commandlineArguments) inline
References IG.Lib.ServiceReferenceWSBase.TestServiceArgsRequest.Body, IG.Lib.ServiceReferenceWSBase.TestServiceArgsResponse.Body, IG.Lib.ServiceReferenceWSBase.TestServiceArgsRequestBody.commandlineArguments, IG.Lib.ServiceReferenceWSBase.WSBaseSoapClient.TestServiceArgs(), and IG.Lib.ServiceReferenceWSBase.TestServiceArgsResponseBody.TestServiceArgsResult.
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/Service References/ServiceReferenceWSBase/Reference.cs