Doc: IGLib EXTENDED: NUnit.Framework.Internal.Filters.AndFilterTests Class Reference
NUnit.Framework.Internal.Filters.AndFilterTests Class Reference
Public Member Functions
void IsNotEmpty ()
void MatchTest ()
void PassTest ()
void ExplicitMatchTest ()
void BuildFromXml ()
void BuildFromXml_TopLevelDefaultsToAnd ()
Public Member Functions inherited from NUnit.Framework.Internal.Filters.TestFilterTests
void SetUpSuite ()
Additional Inherited Members
Static Public Attributes inherited from NUnit.Framework.Internal.Filters.TestFilterTests
const string DUMMY_CLASS = "NUnit.Framework.Internal.Filters.TestFilterTests+DummyFixture"
Protected Attributes inherited from NUnit.Framework.Internal.Filters.TestFilterTests
readonly TestSuite _dummyFixture = TestBuilder.MakeFixture(typeof(DummyFixture))
readonly TestSuite _anotherFixture = TestBuilder.MakeFixture(typeof(AnotherFixture))
readonly TestSuite _yetAnotherFixture = TestBuilder.MakeFixture(typeof(YetAnotherFixture))
readonly TestSuite _fixtureWithMultipleTests = TestBuilder.MakeFixture (typeof (FixtureWithMultipleTests))
readonly TestSuite _topLevelSuite = new TestSuite("MySuite")
Member Function Documentation
IsNotEmpty()
void NUnit.Framework.Internal.Filters.AndFilterTests.IsNotEmpty () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Assert.False(), and NUnit.Framework.Internal.Test.Id.
MatchTest()
void NUnit.Framework.Internal.Filters.AndFilterTests.MatchTest () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.Test.Id, and NUnit.Framework.Assert.That().
PassTest()
void NUnit.Framework.Internal.Filters.AndFilterTests.PassTest () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Internal.Filters.TestFilterTests._topLevelSuite, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.Test.Id, NUnit.Framework.Internal.TestSuite.Tests, and NUnit.Framework.Assert.That().
ExplicitMatchTest()
void NUnit.Framework.Internal.Filters.AndFilterTests.ExplicitMatchTest () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Internal.Filters.TestFilterTests._topLevelSuite, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.Test.Id, NUnit.Framework.Internal.TestSuite.Tests, and NUnit.Framework.Assert.That().
BuildFromXml()
void NUnit.Framework.Internal.Filters.AndFilterTests.BuildFromXml () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Internal.Test.Id, NUnit.Framework.Internal.TestFilter.Match(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
BuildFromXml_TopLevelDefaultsToAnd()
void NUnit.Framework.Internal.Filters.AndFilterTests.BuildFromXml_TopLevelDefaultsToAnd () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Assert.False(), NUnit.Framework.Internal.TestFilter.FromXml(), NUnit.Framework.Internal.Test.Id, NUnit.Framework.Internal.TestFilter.Match(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/Filters/AndFilterTests.cs