Doc: IGLib EXTENDED: IG.Neural.TestNeural Class Reference
IG.Neural.TestNeural Class Reference
Various tests.
Static Public Member Functions
static void TestSerializationNeural (string directory)
Tests serialization and deserialization of various data used in approximation by neural networks.
static void TestSerializationNeural (string directory, bool printData)
Tests serialization and deserialization of various data used in approximation by neural networks.
static void TestTrainingDataFileProgram (string[] args)
Program for testing training data files. Reads a file to an object and writes it into another file for comparison.
static void TestNeuralTrainingSetJson (string filePath)
Tests the format in which neural training data is written. It reads data from a JSON file and writes the read data to another JSON file, which can then be compared to the first one.
static void TestDefinitionDataFileProgram (string[] args)
Program for testing data definition files. Reads a file to an object and writes it into another file for comparison.
static void TestNeuralDataDefinitionJson (string filePath)
Tests the format in which neural definition data is written. It reads data from a JSON file and writes the read data to another JSON file, which can then be compared to the first one.
Detailed Description
Various tests.
$A Igor Apr11;
Member Function Documentation
TestSerializationNeural() [1/2]
static void IG.Neural.TestNeural.TestSerializationNeural (string directory) inline static
Tests serialization and deserialization of various data used in approximation by neural networks.
Parameters
directory
TestSerializationNeural() [2/2]
static void IG.Neural.TestNeural.TestSerializationNeural (string directory, bool printData) inline static
Tests serialization and deserialization of various data used in approximation by neural networks.
Parameters
directory Path to the directory in which the generated data is written.
printData Whether the generated data is printed to the console or not.
References IG.Num.InputOutputDataDefiniton.CreateExample(), IG.Num.SampledDataSet.CreateExampleSimple(), and IG.Num.InputOutputDataDefiniton.ToString().
TestTrainingDataFileProgram()
static void IG.Neural.TestNeural.TestTrainingDataFileProgram (string[] args) inline static
Program for testing training data files. Reads a file to an object and writes it into another file for comparison.
Parameters
args Program arguments, can contain file path as first argument, otherwise the user is asked for the path.
References IG.Neural.TestNeural.TestNeuralTrainingSetJson().
TestNeuralTrainingSetJson()
static void IG.Neural.TestNeural.TestNeuralTrainingSetJson (string filePath) inline static
Tests the format in which neural training data is written. It reads data from a JSON file and writes the read data to another JSON file, which can then be compared to the first one.
Parameters
directory Directory in which the file exists.
fileName Name of the file to be checked.
References IG.Num.SampledDataSet.CreateExampleSimple().
Referenced by IG.Neural.TestNeural.TestTrainingDataFileProgram().
TestDefinitionDataFileProgram()
static void IG.Neural.TestNeural.TestDefinitionDataFileProgram (string[] args) inline static
Program for testing data definition files. Reads a file to an object and writes it into another file for comparison.
Parameters
args Program arguments, can contain file path as first argument, otherwise the user is asked for the path.
References IG.Neural.TestNeural.TestNeuralDataDefinitionJson().
TestNeuralDataDefinitionJson()
static void IG.Neural.TestNeural.TestNeuralDataDefinitionJson (string filePath) inline static
Tests the format in which neural definition data is written. It reads data from a JSON file and writes the read data to another JSON file, which can then be compared to the first one.
Parameters
directory Directory in which the file exists.
fileName Name of the file to be checked.
References IG.Num.InputOutputDataDefiniton.CreateExample().
Referenced by IG.Neural.TestNeural.TestDefinitionDataFileProgram().
The documentation for this class was generated from the following file:
shelldev/extensions_shell/shell/Test_Igor/neural/TestNeural.cs