Doc: IGLib EXTENDED: NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly Class Reference
NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly Class Reference
Public Member Functions
void CreatePackage ()
void PackageIDsAreUnique ()
void AssemblyPathIsUsedAsFilePath ()
void FileNameIsUsedAsPackageName ()
void HasNoSubPackages ()
Private Attributes
TestPackage package
Member Function Documentation
CreatePackage()
void NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.CreatePackage () inline
PackageIDsAreUnique()
void NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.PackageIDsAreUnique () inline
References NUnit.Engine.TestPackage.ID, NUnit.Framework.Is.Not, NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.package, and NUnit.Framework.Assert.That().
AssemblyPathIsUsedAsFilePath()
void NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.AssemblyPathIsUsedAsFilePath () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Engine.TestPackage.FullName, and NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.package.
FileNameIsUsedAsPackageName()
void NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.FileNameIsUsedAsPackageName () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Engine.TestPackage.Name, NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.package, and NUnit.Framework.Assert.That().
HasNoSubPackages()
void NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.HasNoSubPackages () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.package, NUnit.Engine.TestPackage.SubPackages, and NUnit.Framework.Assert.That().
Member Data Documentation
package
TestPackage NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.package private
Referenced by NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.AssemblyPathIsUsedAsFilePath(), NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.FileNameIsUsedAsPackageName(), NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.HasNoSubPackages(), NUnit.Engine.Api.Tests.TestPackageTests_MultipleAssemblies.PackageContainsThreeSubpackages(), NUnit.Engine.Api.Tests.TestPackageTests_SingleAssembly.PackageIDsAreUnique(), and NUnit.Engine.Api.Tests.TestPackageTests_MultipleAssemblies.PackageIsAnonymous().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Api/TestPackageTests.cs