Doc: IGLib EXTENDED: alglib.testmcpdunit Class Reference
alglib.testmcpdunit Class Reference
Static Public Member Functions
static bool testmcpd (bool silent)
static bool testmcpd (bool silent)
static bool _pexec_testmcpd (bool silent)
Static Private Member Functions
static void testsimple (ref bool err)
static void testentryexit (ref bool err)
static void testec (ref bool err)
static void testbc (ref bool err)
static void testlc (ref bool err)
static void createee (int n, int entrystate, int exitstate, mcpd.mcpdstate s)
static void testsimple (ref bool err)
static void testentryexit (ref bool err)
static void testec (ref bool err)
static void testbc (ref bool err)
static void testlc (ref bool err)
static void createee (int n, int entrystate, int exitstate, mcpd.mcpdstate s)
Member Function Documentation
testmcpd() [1/2]
static bool alglib.testmcpdunit.testmcpd (bool silent) inline static
References alglib.testmcpdunit.testbc(), alglib.testmcpdunit.testec(), alglib.testmcpdunit.testentryexit(), alglib.testmcpdunit.testlc(), and alglib.testmcpdunit.testsimple().
Referenced by alglib.testmcpdunit._pexec_testmcpd(), and _Test.Main().
testsimple() [1/2]
static void alglib.testmcpdunit.testsimple (ref bool err) inline static private
References alglib.mcpd.mcpdaddtrack(), alglib.mcpd.mcpdcreate(), alglib.mcpd.mcpdresults(), alglib.mcpd.mcpdsolve(), alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testmcpdunit.testmcpd().
testentryexit() [1/2]
static void alglib.testmcpdunit.testentryexit (ref bool err) inline static private
References alglib.mcpd.mcpdaddtrack(), alglib.mcpd.mcpdcreate(), alglib.mcpd.mcpdcreateentry(), alglib.mcpd.mcpdcreateentryexit(), alglib.mcpd.mcpdcreateexit(), alglib.mcpd.mcpdresults(), alglib.mcpd.mcpdsolve(), alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testmcpdunit.testmcpd().
testec() [1/2]
static void alglib.testmcpdunit.testec (ref bool err) inline static private
References alglib.ap.assert(), alglib.testmcpdunit.createee(), alglib.math.isfinite(), alglib.mcpd.mcpdaddec(), alglib.mcpd.mcpdaddtrack(), alglib.mcpd.mcpdresults(), alglib.mcpd.mcpdsetec(), alglib.mcpd.mcpdsolve(), alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testmcpdunit.testmcpd().
testbc() [1/2]
static void alglib.testmcpdunit.testbc (ref bool err) inline static private
References alglib.ap.assert(), alglib.testmcpdunit.createee(), alglib.mcpd.mcpdaddbc(), alglib.mcpd.mcpdaddtrack(), alglib.mcpd.mcpdresults(), alglib.mcpd.mcpdsetbc(), alglib.mcpd.mcpdsolve(), alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testmcpdunit.testmcpd().
testlc() [1/2]
static void alglib.testmcpdunit.testlc (ref bool err) inline static private
References alglib.ap.assert(), alglib.testmcpdunit.createee(), alglib.math.machineepsilon, alglib.mcpd.mcpdaddtrack(), alglib.mcpd.mcpdresults(), alglib.mcpd.mcpdsetlc(), alglib.mcpd.mcpdsolve(), alglib.math.randominteger(), and alglib.math.randomreal().
Referenced by alglib.testmcpdunit.testmcpd().
createee() [1/2]
static void alglib.testmcpdunit.createee (int n, int entrystate, int exitstate, mcpd.mcpdstate s) inline static private
References alglib.mcpd.mcpdcreate(), alglib.mcpd.mcpdcreateentry(), alglib.mcpd.mcpdcreateentryexit(), and alglib.mcpd.mcpdcreateexit().
Referenced by alglib.testmcpdunit.testbc(), alglib.testmcpdunit.testec(), and alglib.testmcpdunit.testlc().
testmcpd() [2/2]
static bool alglib.testmcpdunit.testmcpd (bool silent) inline static
References alglib.testmcpdunit.testbc(), alglib.testmcpdunit.testec(), alglib.testmcpdunit.testentryexit(), alglib.testmcpdunit.testlc(), and alglib.testmcpdunit.testsimple().
_pexec_testmcpd()
static bool alglib.testmcpdunit._pexec_testmcpd (bool silent) inline static
References alglib.testmcpdunit.testmcpd().
Referenced by _Test.Main().
testsimple() [2/2]
static void alglib.testmcpdunit.testsimple (ref bool err) inline static private
References alglib.mcpd.mcpdaddtrack(), alglib.mcpd.mcpdcreate(), alglib.mcpd.mcpdresults(), alglib.mcpd.mcpdsolve(), alglib.math.randominteger(), and alglib.math.randomreal().
testentryexit() [2/2]
static void alglib.testmcpdunit.testentryexit (ref bool err) inline static private
References alglib.mcpd.mcpdaddtrack(), alglib.mcpd.mcpdcreate(), alglib.mcpd.mcpdcreateentry(), alglib.mcpd.mcpdcreateentryexit(), alglib.mcpd.mcpdcreateexit(), alglib.mcpd.mcpdresults(), alglib.mcpd.mcpdsolve(), alglib.math.randominteger(), and alglib.math.randomreal().
testec() [2/2]
static void alglib.testmcpdunit.testec (ref bool err) inline static private
References alglib.ap.assert(), alglib.testmcpdunit.createee(), alglib.math.isfinite(), alglib.mcpd.mcpdaddec(), alglib.mcpd.mcpdaddtrack(), alglib.mcpd.mcpdresults(), alglib.mcpd.mcpdsetec(), alglib.mcpd.mcpdsolve(), alglib.math.randominteger(), and alglib.math.randomreal().
testbc() [2/2]
static void alglib.testmcpdunit.testbc (ref bool err) inline static private
References alglib.ap.assert(), alglib.testmcpdunit.createee(), alglib.mcpd.mcpdaddbc(), alglib.mcpd.mcpdaddtrack(), alglib.mcpd.mcpdresults(), alglib.mcpd.mcpdsetbc(), alglib.mcpd.mcpdsolve(), alglib.math.randominteger(), and alglib.math.randomreal().
testlc() [2/2]
static void alglib.testmcpdunit.testlc (ref bool err) inline static private
References alglib.ap.assert(), alglib.testmcpdunit.createee(), alglib.math.machineepsilon, alglib.mcpd.mcpdaddtrack(), alglib.mcpd.mcpdresults(), alglib.mcpd.mcpdsetlc(), alglib.mcpd.mcpdsolve(), alglib.math.randominteger(), and alglib.math.randomreal().
createee() [2/2]
static void alglib.testmcpdunit.createee (int n, int entrystate, int exitstate, mcpd.mcpdstate s) inline static private
References alglib.mcpd.mcpdcreate(), alglib.mcpd.mcpdcreateentry(), alglib.mcpd.mcpdcreateentryexit(), and alglib.mcpd.mcpdcreateexit().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs