Doc: IGLib EXTENDED: NUnit.Framework.Syntax.ArbitraryConstraintMatching Class Reference
NUnit.Framework.Syntax.ArbitraryConstraintMatching Class Reference
Classes
class AnotherConstraint
class CustomConstraint
class Unit
Public Member Functions
void CanMatchCustomConstraint ()
void CanMatchCustomConstraintAfterPrefix ()
void CanMatchCustomConstraintsUnderAndOperator ()
void CanMatchPredicate ()
void CanMatchLambda ()
void ApplyMatchesToProperty ()
Private Member Functions
bool IsEven (int num)
Private Attributes
Constraint custom = new CustomConstraint()
Constraint another = new AnotherConstraint()
Member Function Documentation
CanMatchCustomConstraint()
void NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraint () inline
References NUnit.Framework.Syntax.ArbitraryConstraintMatching.custom, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Constraints.ConstraintExpression.Matches(), NUnit.Framework.Constraints.IResolveConstraint.Resolve(), and NUnit.Framework.Assert.That().
CanMatchCustomConstraintAfterPrefix()
void NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraintAfterPrefix () inline
References NUnit.Framework.Is.All, NUnit.Framework.Syntax.ArbitraryConstraintMatching.custom, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Constraints.ConstraintExpression.Matches(), NUnit.Framework.Constraints.IResolveConstraint.Resolve(), and NUnit.Framework.Assert.That().
CanMatchCustomConstraintsUnderAndOperator()
void NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraintsUnderAndOperator () inline
References NUnit.Framework.Is.All, NUnit.Framework.Constraints.Constraint.And, NUnit.Framework.Syntax.ArbitraryConstraintMatching.another, NUnit.Framework.Syntax.ArbitraryConstraintMatching.custom, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Constraints.ConstraintExpression.Matches(), NUnit.Framework.Constraints.IResolveConstraint.Resolve(), and NUnit.Framework.Assert.That().
CanMatchPredicate()
void NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchPredicate () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.IsEven(), NUnit.Framework.Constraints.ConstraintExpression.Matches(), NUnit.Framework.Constraints.IResolveConstraint.Resolve(), and NUnit.Framework.Assert.That().
IsEven()
bool NUnit.Framework.Syntax.ArbitraryConstraintMatching.IsEven (int num) inline private
Referenced by NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchPredicate().
CanMatchLambda()
void NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchLambda () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Constraints.ConstraintExpression.Matches(), NUnit.Framework.Constraints.IResolveConstraint.Resolve(), and NUnit.Framework.Assert.That().
ApplyMatchesToProperty()
void NUnit.Framework.Syntax.ArbitraryConstraintMatching.ApplyMatchesToProperty () inline
References NUnit.Framework.Has.Count, NUnit.Framework.Constraints.ConstraintExpression.Count, NUnit.Framework.Constraints.ConstraintExpression.EqualTo(), NUnit.Framework.Constraints.ConstraintExpression.Matches(), NUnit.Framework.Has.Property(), NUnit.Framework.Constraints.ConstraintExpression.Property(), NUnit.Framework.Assert.That(), and NUnit.Framework.Constraints.ConstraintExpression.With.
Member Data Documentation
custom
Constraint NUnit.Framework.Syntax.ArbitraryConstraintMatching.custom = new CustomConstraint() private
Referenced by NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraint(), NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraintAfterPrefix(), and NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraintsUnderAndOperator().
another
Constraint NUnit.Framework.Syntax.ArbitraryConstraintMatching.another = new AnotherConstraint() private
Referenced by NUnit.Framework.Syntax.ArbitraryConstraintMatching.CanMatchCustomConstraintsUnderAndOperator().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Syntax/ArbitraryConstraintMatching.cs