Doc: IGLib EXTENDED: alglib.testmlpeunit Class Reference
alglib.testmlpeunit Class Reference
Static Public Member Functions
static bool testmlpe (bool silent)
static bool testmlpe (bool silent)
static bool _pexec_testmlpe (bool silent)
Static Private Member Functions
static void createensemble (mlpe.mlpensemble ensemble, int nkind, double a1, double a2, int nin, int nhid1, int nhid2, int nout, int ec)
static void unsetensemble (mlpe.mlpensemble ensemble)
static void testinformational (int nkind, int nin, int nhid1, int nhid2, int nout, int ec, int passcount, ref bool err)
static void testprocessing (int nkind, int nin, int nhid1, int nhid2, int nout, int ec, int passcount, ref bool err)
static void createensemble (mlpe.mlpensemble ensemble, int nkind, double a1, double a2, int nin, int nhid1, int nhid2, int nout, int ec)
static void unsetensemble (mlpe.mlpensemble ensemble)
static void testinformational (int nkind, int nin, int nhid1, int nhid2, int nout, int ec, int passcount, ref bool err)
static void testprocessing (int nkind, int nin, int nhid1, int nhid2, int nout, int ec, int passcount, ref bool err)
static void testerr (int nkind, int nin, int nhid1, int nhid2, int nout, int ec, int passcount, int sizemin, int sizemax, ref bool err)
Member Function Documentation
testmlpe() [1/2]
static bool alglib.testmlpeunit.testmlpe (bool silent) inline static
References alglib.mlpe.mlpebagginglbfgs(), alglib.mlpe.mlpebagginglm(), alglib.mlpe.mlpecreate1(), alglib.mlpe.mlpecreatec1(), alglib.mlpe.mlpermserror(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.testmlpeunit.testinformational(), and alglib.testmlpeunit.testprocessing().
Referenced by alglib.testmlpeunit._pexec_testmlpe(), and _Test.Main().
createensemble() [1/2]
static void alglib.testmlpeunit.createensemble (mlpe.mlpensemble ensemble, int nkind, double a1, double a2, int nin, int nhid1, int nhid2, int nout, int ec) inline static private
References alglib.ap.assert(), alglib.mlpe.mlpecreate0(), alglib.mlpe.mlpecreate1(), alglib.mlpe.mlpecreate2(), alglib.mlpe.mlpecreateb0(), alglib.mlpe.mlpecreateb1(), alglib.mlpe.mlpecreateb2(), alglib.mlpe.mlpecreatec0(), alglib.mlpe.mlpecreatec1(), alglib.mlpe.mlpecreatec2(), alglib.mlpe.mlpecreater0(), alglib.mlpe.mlpecreater1(), and alglib.mlpe.mlpecreater2().
Referenced by alglib.testmlpeunit.testerr(), alglib.testmlpeunit.testinformational(), and alglib.testmlpeunit.testprocessing().
unsetensemble() [1/2]
static void alglib.testmlpeunit.unsetensemble (mlpe.mlpensemble ensemble) inline static private
References alglib.mlpe.mlpecreate0().
Referenced by alglib.testmlpeunit.testprocessing().
testinformational() [1/2]
static void alglib.testmlpeunit.testinformational (int nkind, int nin, int nhid1, int nhid2, int nout, int ec, int passcount, ref bool err) inline static private
References alglib.testmlpeunit.createensemble(), and alglib.mlpe.mlpeproperties().
Referenced by alglib.testmlpeunit.testmlpe().
testprocessing() [1/2]
static void alglib.testmlpeunit.testprocessing (int nkind, int nin, int nhid1, int nhid2, int nout, int ec, int passcount, ref bool err) inline static private
References alglib.serializer.alloc_start(), alglib.testmlpeunit.createensemble(), alglib.serializer.get_string(), alglib.math.machineepsilon, alglib.mlpe.mlpealloc(), alglib.mlpe.mlpecopy(), alglib.mlpe.mlpeprocess(), alglib.mlpe.mlperandomize(), alglib.mlpe.mlpeserialize(), alglib.mlpe.mlpeunserialize(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.serializer.sstart_str(), alglib.serializer.stop(), alglib.testmlpeunit.unsetensemble(), and alglib.serializer.ustart_str().
Referenced by alglib.testmlpeunit.testmlpe().
testmlpe() [2/2]
static bool alglib.testmlpeunit.testmlpe (bool silent) inline static
References alglib.testmlpeunit.testerr(), alglib.testmlpeunit.testinformational(), and alglib.testmlpeunit.testprocessing().
_pexec_testmlpe()
static bool alglib.testmlpeunit._pexec_testmlpe (bool silent) inline static
References alglib.testmlpeunit.testmlpe().
Referenced by _Test.Main().
createensemble() [2/2]
static void alglib.testmlpeunit.createensemble (mlpe.mlpensemble ensemble, int nkind, double a1, double a2, int nin, int nhid1, int nhid2, int nout, int ec) inline static private
References alglib.ap.assert(), alglib.mlpe.mlpecreate0(), alglib.mlpe.mlpecreate1(), alglib.mlpe.mlpecreate2(), alglib.mlpe.mlpecreateb0(), alglib.mlpe.mlpecreateb1(), alglib.mlpe.mlpecreateb2(), alglib.mlpe.mlpecreatec0(), alglib.mlpe.mlpecreatec1(), alglib.mlpe.mlpecreatec2(), alglib.mlpe.mlpecreater0(), alglib.mlpe.mlpecreater1(), and alglib.mlpe.mlpecreater2().
unsetensemble() [2/2]
static void alglib.testmlpeunit.unsetensemble (mlpe.mlpensemble ensemble) inline static private
References alglib.mlpe.mlpecreate0().
testinformational() [2/2]
static void alglib.testmlpeunit.testinformational (int nkind, int nin, int nhid1, int nhid2, int nout, int ec, int passcount, ref bool err) inline static private
References alglib.testmlpeunit.createensemble(), and alglib.mlpe.mlpeproperties().
testprocessing() [2/2]
static void alglib.testmlpeunit.testprocessing (int nkind, int nin, int nhid1, int nhid2, int nout, int ec, int passcount, ref bool err) inline static private
References alglib.serializer.alloc_start(), alglib.testmlpeunit.createensemble(), alglib.serializer.get_string(), alglib.math.machineepsilon, alglib.mlpe.mlpealloc(), alglib.mlpe.mlpecopy(), alglib.mlpe.mlpeprocess(), alglib.mlpe.mlperandomize(), alglib.mlpe.mlpeserialize(), alglib.mlpe.mlpeunserialize(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.serializer.sstart_str(), alglib.serializer.stop(), alglib.testmlpeunit.unsetensemble(), and alglib.serializer.ustart_str().
testerr()
static void alglib.testmlpeunit.testerr (int nkind, int nin, int nhid1, int nhid2, int nout, int ec, int passcount, int sizemin, int sizemax, ref bool err) inline static private
References alglib.testmlpeunit.createensemble(), alglib.math.maxrealnumber, alglib.mlpe.mlpeavgce(), alglib.mlpe.mlpeavgerror(), alglib.mlpe.mlpeavgrelerror(), alglib.mlpe.mlpeissoftmax(), alglib.mlpe.mlpeprocess(), alglib.mlpe.mlperandomize(), alglib.mlpe.mlpermserror(), alglib.mlpbase.mlpproperties(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.apserv.seterrorflagdiff(), alglib.sparse.sparseconverttocrs(), alglib.sparse.sparsecreate(), alglib.sparse.sparseset(), and alglib.math.sqr().
Referenced by alglib.testmlpeunit.testmlpe().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs