Doc: IGLib EXTENDED: AForge.Imaging.Filters.ColorFiltering Class Reference
AForge.Imaging.Filters.ColorFiltering Class Reference
Color filtering.
Public Member Functions
ColorFiltering ()
Initializes a new instance of the ColorFiltering class.
ColorFiltering (IntRange red, IntRange green, IntRange blue)
Initializes a new instance of the ColorFiltering class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image, Rectangle rect)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
IntRange Red [get, set]
Range of red color component.
IntRange Green [get, set]
Range of green color component.
IntRange Blue [get, set]
Range of blue color component.
RGB FillColor [get, set]
Fill color used to fill filtered pixels.
bool FillOutsideRange [get, set]
Determines, if pixels should be filled inside or outside of specified color ranges.
Properties inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
IntRange red = new IntRange(0, 255)
IntRange green = new IntRange(0, 255)
IntRange blue = new IntRange(0, 255)
byte fillR = 0
byte fillG = 0
byte fillB = 0
bool fillOutsideRange = true
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Color filtering.
The filter filters pixels inside/outside of specified RGB color range - it keeps pixels with colors inside/outside of specified range and fills the rest with specified color.
The filter accepts 24 and 32 bpp color images for processing.
Sample usage:
// create filter
ColorFiltering filter = new ColorFiltering();
// set color ranges to keep
filter.Red   = new IntRange(100, 255);
filter.Green = new IntRange(0, 75);
filter.Blue  = new IntRange(0, 75);
// apply the filter
filter.ApplyInPlace(image);
Initial image:
Result image:
See also
ChannelFiltering, EuclideanColorFiltering, HSLFiltering, YCbCrFiltering
Constructor & Destructor Documentation
ColorFiltering() [1/2]
AForge.Imaging.Filters.ColorFiltering.ColorFiltering () inline
Initializes a new instance of the ColorFiltering class.
References AForge.Imaging.Filters.ColorFiltering.formatTranslations.
ColorFiltering() [2/2]
AForge.Imaging.Filters.ColorFiltering.ColorFiltering (IntRange red, IntRange green, IntRange blue) inline
Initializes a new instance of the ColorFiltering class.
Parameters
red Red components filtering range.
green Green components filtering range.
blue Blue components filtering range.
References AForge.Imaging.Filters.ColorFiltering.blue, AForge.Imaging.Filters.ColorFiltering.green, and AForge.Imaging.Filters.ColorFiltering.red.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.ColorFiltering.ProcessFilter (UnmanagedImage image, Rectangle rect) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
rect Image rectangle for processing by the filter.
Implements AForge.Imaging.Filters.BaseInPlacePartialFilter.
References AForge.Imaging.RGB.B, AForge.Imaging.Filters.ColorFiltering.blue, AForge.Imaging.Filters.ColorFiltering.fillB, AForge.Imaging.Filters.ColorFiltering.fillG, AForge.Imaging.Filters.ColorFiltering.fillOutsideRange, AForge.Imaging.Filters.ColorFiltering.fillR, AForge.Imaging.RGB.G, AForge.Imaging.Filters.ColorFiltering.green, AForge.Imaging.UnmanagedImage.ImageData, AForge.IntRange.Max, AForge.IntRange.Min, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, AForge.Imaging.Filters.ColorFiltering.red, and AForge.Imaging.UnmanagedImage.Stride.
Member Data Documentation
red
IntRange AForge.Imaging.Filters.ColorFiltering.red = new IntRange(0, 255) private
Referenced by AForge.Imaging.Filters.ColorFiltering.ColorFiltering(), and AForge.Imaging.Filters.ColorFiltering.ProcessFilter().
green
IntRange AForge.Imaging.Filters.ColorFiltering.green = new IntRange(0, 255) private
Referenced by AForge.Imaging.Filters.ColorFiltering.ColorFiltering(), and AForge.Imaging.Filters.ColorFiltering.ProcessFilter().
blue
IntRange AForge.Imaging.Filters.ColorFiltering.blue = new IntRange(0, 255) private
Referenced by AForge.Imaging.Filters.ColorFiltering.ColorFiltering(), and AForge.Imaging.Filters.ColorFiltering.ProcessFilter().
fillR
byte AForge.Imaging.Filters.ColorFiltering.fillR = 0 private
Referenced by AForge.Imaging.Filters.ColorFiltering.ProcessFilter().
fillG
byte AForge.Imaging.Filters.ColorFiltering.fillG = 0 private
Referenced by AForge.Imaging.Filters.ColorFiltering.ProcessFilter().
fillB
byte AForge.Imaging.Filters.ColorFiltering.fillB = 0 private
Referenced by AForge.Imaging.Filters.ColorFiltering.ProcessFilter().
fillOutsideRange
bool AForge.Imaging.Filters.ColorFiltering.fillOutsideRange = true private
Referenced by AForge.Imaging.Filters.ColorFiltering.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.ColorFiltering.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.ColorFiltering.ColorFiltering().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.ColorFiltering.FormatTranslations get
Format translations dictionary.
Red
IntRange AForge.Imaging.Filters.ColorFiltering.Red get set
Range of red color component.
Referenced by ShapeChecker.MainForm.ProcessImage().
Green
IntRange AForge.Imaging.Filters.ColorFiltering.Green get set
Range of green color component.
Referenced by ShapeChecker.MainForm.ProcessImage().
Blue
IntRange AForge.Imaging.Filters.ColorFiltering.Blue get set
Range of blue color component.
Referenced by ShapeChecker.MainForm.ProcessImage().
FillColor
RGB AForge.Imaging.Filters.ColorFiltering.FillColor get set
Fill color used to fill filtered pixels.
FillOutsideRange
bool AForge.Imaging.Filters.ColorFiltering.FillOutsideRange get set
Determines, if pixels should be filled inside or outside of specified color ranges.
Default value is set to true, which means the filter removes colors outside of the specified range.
Referenced by ShapeChecker.MainForm.ProcessImage().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Color Filters/ColorFiltering.cs