Doc: IGLib EXTENDED: IG.Neural.Forms.NeuralInputWindow Class Reference
IG.Neural.Forms.NeuralInputWindow Class Reference
Test window for editing input parameters of an approximative model.
Public Member Functions
NeuralInputWindow ()
NeuralInputWindow ()
NeuralInputWindow ()
NeuralInputWindow ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
NeuralInputControl neuralInputControl1
NeuralOutputControl neuralOutputControl1
Detailed Description
Test window for editing input parameters of an approximative model.
$A Igor Apr13;
Constructor & Destructor Documentation
NeuralInputWindow() [1/4]
IG.Neural.Forms.NeuralInputWindow.NeuralInputWindow () inline
References IG.Neural.Forms.NeuralInputWindow.InitializeComponent().
NeuralInputWindow() [2/4]
IG.Neural.Forms.NeuralInputWindow.NeuralInputWindow () inline
References IG.Neural.Forms.NeuralInputWindow.InitializeComponent().
NeuralInputWindow() [3/4]
IG.Neural.Forms.NeuralInputWindow.NeuralInputWindow () inline
References IG.Neural.Forms.NeuralInputWindow.InitializeComponent().
NeuralInputWindow() [4/4]
IG.Neural.Forms.NeuralInputWindow.NeuralInputWindow () inline
References IG.Neural.Forms.NeuralInputWindow.InitializeComponent().
Member Function Documentation
Dispose() [1/4]
override void IG.Neural.Forms.NeuralInputWindow.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralInputWindow.components.
InitializeComponent() [1/4]
void IG.Neural.Forms.NeuralInputWindow.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralInputWindow.neuralInputControl1, and IG.Neural.Forms.NeuralInputWindow.neuralOutputControl1.
Referenced by IG.Neural.Forms.NeuralInputWindow.NeuralInputWindow().
Dispose() [2/4]
override void IG.Neural.Forms.NeuralInputWindow.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralInputWindow.components.
InitializeComponent() [2/4]
void IG.Neural.Forms.NeuralInputWindow.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralInputWindow.neuralInputControl1, and IG.Neural.Forms.NeuralInputWindow.neuralOutputControl1.
Dispose() [3/4]
override void IG.Neural.Forms.NeuralInputWindow.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralInputWindow.components.
InitializeComponent() [3/4]
void IG.Neural.Forms.NeuralInputWindow.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralInputWindow.neuralInputControl1, and IG.Neural.Forms.NeuralInputWindow.neuralOutputControl1.
Dispose() [4/4]
override void IG.Neural.Forms.NeuralInputWindow.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralInputWindow.components.
InitializeComponent() [4/4]
void IG.Neural.Forms.NeuralInputWindow.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralInputWindow.neuralInputControl1, and IG.Neural.Forms.NeuralInputWindow.neuralOutputControl1.
Member Data Documentation
components
System ComponentModel IContainer IG.Neural.Forms.NeuralInputWindow.components = null private
Required designer variable.
Referenced by IG.Neural.Forms.NeuralInputWindow.Dispose().
neuralInputControl1
NeuralInputControl IG.Neural.Forms.NeuralInputWindow.neuralInputControl1 private
Referenced by IG.Neural.Forms.NeuralInputWindow.InitializeComponent().
neuralOutputControl1
NeuralOutputControl IG.Neural.Forms.NeuralInputWindow.neuralOutputControl1 private
Referenced by IG.Neural.Forms.NeuralInputWindow.InitializeComponent().
The documentation for this class was generated from the following files:
shelldev/extensions/ExtAppAnnApp/ResponseForms/NeuralInputWindow.cs
shelldev/extensions/ExtAppAnnApp/ResponseForms/NeuralInputWindow.Designer.cs