Doc: IGLib EXTENDED: AForge.Imaging.Filters.Grayscale.CommonAlgorithms Class Reference
AForge.Imaging.Filters.Grayscale.CommonAlgorithms Class Reference
Set of predefined common grayscaling algorithms, which have aldready initialized grayscaling coefficients.
Static Public Attributes
static readonly Grayscale BT709 = new Grayscale(0.2125, 0.7154, 0.0721)
Grayscale image using BT709 algorithm.
static readonly Grayscale RMY = new Grayscale(0.5000, 0.4190, 0.0810)
Grayscale image using R-Y algorithm.
static readonly Grayscale Y = new Grayscale(0.2990, 0.5870, 0.1140)
Grayscale image using Y algorithm.
Detailed Description
Set of predefined common grayscaling algorithms, which have aldready initialized grayscaling coefficients.
Member Data Documentation
BT709
readonly Grayscale AForge.Imaging.Filters.Grayscale.CommonAlgorithms.BT709 = new Grayscale(0.2125, 0.7154, 0.0721) static
Grayscale image using BT709 algorithm.
The instance uses BT709 algorithm to convert color image to grayscale. The conversion coefficients are:
Red: 0.2125;
Green: 0.7154;
Blue: 0.0721.
Sample usage:
// apply the filter
Bitmap grayImage = Grayscale.CommonAlgorithms.BT709.Apply(image);
Referenced by FiltersDemo.MainForm.grayscaleFiltersItem_Click(), IPPrototyperSample.CoinsFinder.Process(), and AForge.Imaging.SusanCornersDetector.ProcessImage().
RMY
readonly Grayscale AForge.Imaging.Filters.Grayscale.CommonAlgorithms.RMY = new Grayscale(0.5000, 0.4190, 0.0810) static
Grayscale image using R-Y algorithm.
The instance uses R-Y algorithm to convert color image to grayscale. The conversion coefficients are:
Red: 0.5;
Green: 0.419;
Blue: 0.081.
Sample usage:
// apply the filter
Bitmap grayImage = Grayscale.CommonAlgorithms.RMY.Apply(image);
Referenced by FiltersDemo.MainForm.differenceEdgesFiltersItem_Click(), FiltersDemo.MainForm.floydFiltersItem_Click(), FiltersDemo.MainForm.homogenityEdgesFiltersItem_Click(), FiltersDemo.MainForm.orderedDitheringFiltersItem_Click(), FiltersDemo.MainForm.sobelEdgesFiltersItem_Click(), and FiltersDemo.MainForm.thresholdFiltersItem_Click().
Y
readonly Grayscale AForge.Imaging.Filters.Grayscale.CommonAlgorithms.Y = new Grayscale(0.2990, 0.5870, 0.1140) static
Grayscale image using Y algorithm.
The instance uses Y algorithm to convert color image to grayscale. The conversion coefficients are:
Red: 0.299;
Green: 0.587;
Blue: 0.114.
Sample usage:
// apply the filter
Bitmap grayImage = Grayscale.CommonAlgorithms.Y.Apply(image);
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Color Filters/Grayscale.cs