Doc: IGLib EXTENDED: AForge.Imaging.Filters.HueModifier Class Reference
AForge.Imaging.Filters.HueModifier Class Reference
Hue modifier.
Public Member Functions
HueModifier ()
Initializes a new instance of the HueModifier class.
HueModifier (int hue)
Initializes a new instance of the HueModifier class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image, Rectangle rect)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
int Hue [get, set]
Hue value to set, [0, 359].
Properties inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
int hue = 0
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Hue modifier.
The filter operates in HSL color space and updates pixels' hue values setting it to the specified value (luminance and saturation are kept unchanged). The result of the filter looks like the image is observed through a glass of the given color.
The filter accepts 24 and 32 bpp color images for processing.
Sample usage:
// create filter
HueModifier filter = new HueModifier(180);
// apply the filter
filter.ApplyInPlace(image);
Initial image:
Result image:
Constructor & Destructor Documentation
HueModifier() [1/2]
AForge.Imaging.Filters.HueModifier.HueModifier () inline
Initializes a new instance of the HueModifier class.
References AForge.Imaging.Filters.HueModifier.formatTranslations.
HueModifier() [2/2]
AForge.Imaging.Filters.HueModifier.HueModifier (int hue) inline
Initializes a new instance of the HueModifier class.
Parameters
hue Hue value to set.
References AForge.Imaging.Filters.HueModifier.hue.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.HueModifier.ProcessFilter (UnmanagedImage image, Rectangle rect) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
rect Image rectangle for processing by the filter.
Implements AForge.Imaging.Filters.BaseInPlacePartialFilter.
References AForge.Imaging.RGB.B, AForge.Imaging.RGB.Blue, AForge.Imaging.HSL.FromRGB(), AForge.Imaging.RGB.G, AForge.Imaging.RGB.Green, AForge.Imaging.Filters.HueModifier.hue, AForge.Imaging.HSL.Hue, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, AForge.Imaging.RGB.Red, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.HSL.ToRGB().
Member Data Documentation
hue
int AForge.Imaging.Filters.HueModifier.hue = 0 private
Referenced by AForge.Imaging.Filters.HueModifier.HueModifier(), and AForge.Imaging.Filters.HueModifier.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.HueModifier.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.HueModifier.HueModifier().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.HueModifier.FormatTranslations get
Format translations dictionary.
Hue
int AForge.Imaging.Filters.HueModifier.Hue get set
Hue value to set, [0, 359].
Default value is set to 0.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/HSL Filters/HueModifier.cs