Doc: IGLib EXTENDED: alglib.inverseupdate Class Reference
alglib.inverseupdate Class Reference
Static Public Member Functions
static void rmatrixinvupdatesimple (ref double[,] inva, int n, int updrow, int updcolumn, double updval)
static void rmatrixinvupdaterow (ref double[,] inva, int n, int updrow, double[] v)
static void rmatrixinvupdatecolumn (ref double[,] inva, int n, int updcolumn, double[] u)
static void rmatrixinvupdateuv (ref double[,] inva, int n, double[] u, double[] v)
static void rmatrixinvupdatesimple (ref double[,] inva, int n, int updrow, int updcolumn, double updval)
static void rmatrixinvupdaterow (ref double[,] inva, int n, int updrow, double[] v)
static void rmatrixinvupdatecolumn (ref double[,] inva, int n, int updcolumn, double[] u)
static void rmatrixinvupdateuv (ref double[,] inva, int n, double[] u, double[] v)
Member Function Documentation
rmatrixinvupdatesimple() [1/2]
static void alglib.inverseupdate.rmatrixinvupdatesimple (ref double inva[,], int n, int updrow, int updcolumn, double updval) inline static
Referenced by alglib.rmatrixinvupdatesimple(), and alglib.testinverseupdateunit.testinverseupdate().
rmatrixinvupdaterow() [1/2]
static void alglib.inverseupdate.rmatrixinvupdaterow (ref double inva[,], int n, int updrow, double[] v) inline static
Referenced by alglib.rmatrixinvupdaterow(), and alglib.testinverseupdateunit.testinverseupdate().
rmatrixinvupdatecolumn() [1/2]
static void alglib.inverseupdate.rmatrixinvupdatecolumn (ref double inva[,], int n, int updcolumn, double[] u) inline static
Referenced by alglib.rmatrixinvupdatecolumn(), and alglib.testinverseupdateunit.testinverseupdate().
rmatrixinvupdateuv() [1/2]
static void alglib.inverseupdate.rmatrixinvupdateuv (ref double inva[,], int n, double[] u, double[] v) inline static
Referenced by alglib.rmatrixinvupdateuv(), and alglib.testinverseupdateunit.testinverseupdate().
rmatrixinvupdatesimple() [2/2]
static void alglib.inverseupdate.rmatrixinvupdatesimple (ref double inva[,], int n, int updrow, int updcolumn, double updval) inline static
rmatrixinvupdaterow() [2/2]
static void alglib.inverseupdate.rmatrixinvupdaterow (ref double inva[,], int n, int updrow, double[] v) inline static
rmatrixinvupdatecolumn() [2/2]
static void alglib.inverseupdate.rmatrixinvupdatecolumn (ref double inva[,], int n, int updcolumn, double[] u) inline static
rmatrixinvupdateuv() [2/2]
static void alglib.inverseupdate.rmatrixinvupdateuv (ref double inva[,], int n, double[] u, double[] v) inline static
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/linalg.cs