Doc: IGLib EXTENDED: CShell.Modules.Sink.ViewModels.GridSinkViewModel Class Reference
CShell.Modules.Sink.ViewModels.GridSinkViewModel Class Reference
Public Member Functions
GridSinkViewModel (Uri uri)
override void Dump (object o, string description)
override void Clear ()
Public Member Functions inherited from CShell.Framework.Sink
virtual void Dump (object o)
Public Member Functions inherited from CShell.Framework.Document
virtual void Save ()
virtual void SaveAs (string newFile)
Static Public Member Functions
static IList< PropertyInfo > GetProperties (Type itemType)
static IList< PropertyInfo > GetValueProperties (Type itemType)
Properties
List< object > Data [get, set]
int DataCount [get]
Type ItemType [get]
Collection< PropertyInfo > Properties [get, private set]
Collection< PropertyInfo > SelectedProperties [get, private set]
Properties inherited from CShell.Framework.Sink
virtual Uri IconSource [get]
bool IsVisible [get, set]
virtual PaneLocation PreferredLocation [get]
Properties inherited from CShell.Framework.Document
ICommand?? CloseCommand [get]
virtual Uri Uri [get, set]
virtual bool IsDirty [get, set]
Properties inherited from CShell.Framework.IDocument
ICommand CloseCommand [get]
Uri Uri [get]
bool IsDirty [get]
Properties inherited from CShell.Framework.ISink
PaneLocation PreferredLocation [get]
bool IsVisible [get, set]
Private Member Functions
void InitializeItemProperties ()
Static Private Member Functions
static bool IsValueType (Type type)
static bool IsSimpleType (Type type)
Private Attributes
List< object > data
Type lastItemType
Additional Inherited Members
Protected Member Functions inherited from CShell.Framework.Sink
Sink ()
string GetUriPathPart (Uri uri, int pathIndex)
Gets the display name from the uri, which is usually the second part of the absolute path.
string GetTitle (Uri uri, string defaultTitle)
Constructor & Destructor Documentation
GridSinkViewModel()
CShell.Modules.Sink.ViewModels.GridSinkViewModel.GridSinkViewModel (Uri uri) inline
References CShell.Modules.Sink.ViewModels.GridSinkViewModel.data, CShell.Framework.Sink.GetTitle(), and CShell.Framework.Document.Uri.
Member Function Documentation
Dump()
override void CShell.Modules.Sink.ViewModels.GridSinkViewModel.Dump (object o, string description) inline virtual
Implements CShell.Framework.Sink.
References CShell.Modules.Sink.ViewModels.GridSinkViewModel.Data, and CShell.Modules.Sink.ViewModels.GridSinkViewModel.IsSimpleType().
Clear()
override void CShell.Modules.Sink.ViewModels.GridSinkViewModel.Clear () inline virtual
Implements CShell.Framework.Sink.
References CShell.Modules.Sink.ViewModels.GridSinkViewModel.Data.
InitializeItemProperties()
void CShell.Modules.Sink.ViewModels.GridSinkViewModel.InitializeItemProperties () inline private
References CShell.Modules.Sink.ViewModels.GridSinkViewModel.GetProperties(), CShell.Modules.Sink.ViewModels.GridSinkViewModel.ItemType, CShell.Modules.Sink.ViewModels.GridSinkViewModel.lastItemType, CShell.Modules.Sink.ViewModels.GridSinkViewModel.Properties, and CShell.Modules.Sink.ViewModels.GridSinkViewModel.SelectedProperties.
GetProperties()
static IList<PropertyInfo> CShell.Modules.Sink.ViewModels.GridSinkViewModel.GetProperties (Type itemType) inline static
Referenced by CShell.Modules.Sink.ViewModels.GridSinkViewModel.GetValueProperties(), and CShell.Modules.Sink.ViewModels.GridSinkViewModel.InitializeItemProperties().
GetValueProperties()
static IList<PropertyInfo> CShell.Modules.Sink.ViewModels.GridSinkViewModel.GetValueProperties (Type itemType) inline static
References CShell.Modules.Sink.ViewModels.GridSinkViewModel.GetProperties(), and CShell.Modules.Sink.ViewModels.GridSinkViewModel.IsValueType().
IsValueType()
static bool CShell.Modules.Sink.ViewModels.GridSinkViewModel.IsValueType (Type type) inline static private
Referenced by CShell.Modules.Sink.ViewModels.GridSinkViewModel.GetValueProperties(), and CShell.Modules.Sink.ViewModels.GridSinkViewModel.IsSimpleType().
IsSimpleType()
static bool CShell.Modules.Sink.ViewModels.GridSinkViewModel.IsSimpleType (Type type) inline static private
References CShell.Modules.Sink.ViewModels.GridSinkViewModel.IsValueType().
Referenced by CShell.Modules.Sink.ViewModels.GridSinkViewModel.Dump().
Member Data Documentation
data
List<object> CShell.Modules.Sink.ViewModels.GridSinkViewModel.data private
Referenced by CShell.Modules.Sink.ViewModels.GridSinkViewModel.GridSinkViewModel().
lastItemType
Type CShell.Modules.Sink.ViewModels.GridSinkViewModel.lastItemType private
Referenced by CShell.Modules.Sink.ViewModels.GridSinkViewModel.InitializeItemProperties().
Property Documentation
Data
List<object> CShell.Modules.Sink.ViewModels.GridSinkViewModel.Data get set
Referenced by CShell.Modules.Sink.ViewModels.GridSinkViewModel.Clear(), CShell.Modules.Sink.Views.GridSinkView.Data_DataContextChanged(), and CShell.Modules.Sink.ViewModels.GridSinkViewModel.Dump().
DataCount
int CShell.Modules.Sink.ViewModels.GridSinkViewModel.DataCount get
ItemType
Type CShell.Modules.Sink.ViewModels.GridSinkViewModel.ItemType get
Referenced by CShell.Modules.Sink.Views.GridSinkView.InitializeColumns(), CShell.Modules.Sink.ViewModels.GridSinkViewModel.InitializeItemProperties(), and CShell.Modules.Sink.Views.GridSinkView.vm_PropertyChanged().
Properties
Collection<PropertyInfo> CShell.Modules.Sink.ViewModels.GridSinkViewModel.Properties get private set
Referenced by CShell.Modules.Sink.Views.GridSinkView.GetColumnIndex(), and CShell.Modules.Sink.ViewModels.GridSinkViewModel.InitializeItemProperties().
SelectedProperties
Collection<PropertyInfo> CShell.Modules.Sink.ViewModels.GridSinkViewModel.SelectedProperties get private set
Referenced by CShell.Modules.Sink.Views.GridSinkView.GetColumnIndex(), CShell.Modules.Sink.Views.GridSinkView.InitializeColumns(), and CShell.Modules.Sink.ViewModels.GridSinkViewModel.InitializeItemProperties().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Sink/ViewModels/GridSinkViewModel.cs