Doc: IGLib EXTENDED: NUnit.Framework.TestFixtureData Class Reference
NUnit.Framework.TestFixtureData Class Reference
The TestFixtureData class represents a set of arguments and other parameter info to be used for a parameterized fixture. It is derived from TestFixtureParameters and adds a fluent syntax for use in initializing the fixture.
Public Member Functions
TestFixtureData (params object[] args)
Initializes a new instance of the TestFixtureData class.
TestFixtureData (object arg)
Initializes a new instance of the TestFixtureData class.
TestFixtureData (object arg1, object arg2)
Initializes a new instance of the TestFixtureData class.
TestFixtureData (object arg1, object arg2, object arg3)
Initializes a new instance of the TestFixtureData class.
TestFixtureData Explicit ()
Marks the test fixture as explicit.
TestFixtureData Explicit (string reason)
Marks the test fixture as explicit, specifying the reason.
TestFixtureData Ignore (string reason)
Ignores this TestFixture, specifying the reason.
Public Member Functions inherited from NUnit.Framework.Internal.TestFixtureParameters
TestFixtureParameters ()
Default Constructor creates an empty parameter set
TestFixtureParameters (Exception exception)
Construct a non-runnable ParameterSet, specifying the provider exception that made it invalid.
TestFixtureParameters (params object[] args)
Construct a parameter set with a list of arguments
TestFixtureParameters (ITestFixtureData data)
Construct a ParameterSet from an object implementing ITestCaseData
Public Member Functions inherited from NUnit.Framework.Internal.TestParameters
TestParameters ()
Default Constructor creates an empty parameter set
TestParameters (object[] args)
Construct a parameter set with a list of arguments
TestParameters (Exception exception)
Construct a non-runnable ParameterSet, specifying the provider exception that made it invalid.
TestParameters (ITestData data)
Construct a ParameterSet from an object implementing ITestData
void ApplyToTest (Test test)
Applies ParameterSet _values to the test itself.
Additional Inherited Members
Properties inherited from NUnit.Framework.Internal.TestFixtureParameters
Type[] TypeArgs [get, set]
Type arguments used to create a generic fixture instance
Properties inherited from NUnit.Framework.Internal.TestParameters
RunState RunState [get, set]
The RunState for this set of parameters.
object[] Arguments [get, set]
The arguments to be used in running the test, which must match the method signature.
string TestName [get, set]
A name to be used for this test case in lieu of the standard generated name containing the argument list.
IPropertyBag Properties [get, private set]
Gets the property dictionary for this test
object[] OriginalArguments [get, private set]
The original arguments provided by the user, used for display purposes.
Properties inherited from NUnit.Framework.Interfaces.ITestData
string TestName [get]
Gets the name to be used for the test
RunState RunState [get]
Gets the RunState for this test case.
object[] Arguments [get]
Gets the argument list to be provided to the test
IPropertyBag Properties [get]
Gets the property dictionary for the test case
Properties inherited from NUnit.Framework.Interfaces.ITestFixtureData
Type[] TypeArgs [get]
Get the TypeArgs if separately set
Detailed Description
The TestFixtureData class represents a set of arguments and other parameter info to be used for a parameterized fixture. It is derived from TestFixtureParameters and adds a fluent syntax for use in initializing the fixture.
Constructor & Destructor Documentation
TestFixtureData() [1/4]
NUnit.Framework.TestFixtureData.TestFixtureData (params object[] args) inline
Initializes a new instance of the TestFixtureData class.
Parameters
args The arguments.
TestFixtureData() [2/4]
NUnit.Framework.TestFixtureData.TestFixtureData (object arg) inline
Initializes a new instance of the TestFixtureData class.
Parameters
arg The argument.
TestFixtureData() [3/4]
NUnit.Framework.TestFixtureData.TestFixtureData (object arg1, object arg2) inline
Initializes a new instance of the TestFixtureData class.
Parameters
arg1 The first argument.
arg2 The second argument.
TestFixtureData() [4/4]
NUnit.Framework.TestFixtureData.TestFixtureData (object arg1, object arg2, object arg3) inline
Initializes a new instance of the TestFixtureData class.
Parameters
arg1 The first argument.
arg2 The second argument.
arg3 The third argument.
Member Function Documentation
Explicit() [1/2]
TestFixtureData NUnit.Framework.TestFixtureData.Explicit () inline
Marks the test fixture as explicit.
References NUnit.Framework.TestFixtureData.Explicit().
Referenced by NUnit.Framework.TestFixtureData.Explicit(), and NUnit.TestData.TestFixtureSourceData.IndividualInstancesMayBeExplicit.ExplicitData().
Explicit() [2/2]
TestFixtureData NUnit.Framework.TestFixtureData.Explicit (string reason) inline
Marks the test fixture as explicit, specifying the reason.
References NUnit.Framework.TestFixtureData.Explicit(), NUnit.Framework.Internal.TestParameters.Properties, NUnit.Framework.Interfaces.IPropertyBag.Set(), and NUnit.Framework.Internal.PropertyNames.SkipReason.
Ignore()
TestFixtureData NUnit.Framework.TestFixtureData.Ignore (string reason) inline
Ignores this TestFixture, specifying the reason.
Parameters
reason The reason.
Returns
References NUnit.Framework.Internal.TestParameters.Properties, NUnit.Framework.Interfaces.IPropertyBag.Set(), and NUnit.Framework.Internal.PropertyNames.SkipReason.
Referenced by NUnit.TestData.TestFixtureSourceData.IndividualInstancesMayBeIgnored.IgnoredData().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/TestFixtureData.cs