Doc: IGLib EXTENDED: NUnit.Engine.Services.ProjectLoaders.NUnitProjectLoader Class Reference
NUnit.Engine.Services.ProjectLoaders.NUnitProjectLoader Class Reference
Public Member Functions
bool CanLoadFrom (string path)
Returns true if the file indicated is one that this loader knows how to load.
IProject LoadFrom (string path)
Loads a project of a known format.
TestPackage GetTestPackage (string path)
TestPackage GetTestPackage (string path, string configName)
Member Function Documentation
CanLoadFrom()
bool NUnit.Engine.Services.ProjectLoaders.NUnitProjectLoader.CanLoadFrom (string path) inline
Returns true if the file indicated is one that this loader knows how to load.
Parameters
path The path of the project file
Returns
True if the loader knows how to load this file, otherwise false
Implements NUnit.Engine.Extensibility.IProjectLoader.
Referenced by NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.CheckExtension().
LoadFrom()
IProject NUnit.Engine.Services.ProjectLoaders.NUnitProjectLoader.LoadFrom (string path) inline
Loads a project of a known format.
Parameters
path The path of the project file
Returns
An IProject interface to the loaded project or null if the project cannot be loaded
Implements NUnit.Engine.Extensibility.IProjectLoader.
References NUnit.Engine.Services.ProjectLoaders.NUnitProject.Load().
Referenced by NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.CanLoadEmptyProject(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadEmptyConfigs(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadNormalProject(), NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadProjectWithComplexSettings(), and NUnit.Engine.Services.ProjectLoaders.Tests.NUnitProjectLoaderTests.LoadProjectWithManualBinPath().
GetTestPackage() [1/2]
TestPackage NUnit.Engine.Services.ProjectLoaders.NUnitProjectLoader.GetTestPackage (string path) inline
GetTestPackage() [2/2]
TestPackage NUnit.Engine.Services.ProjectLoaders.NUnitProjectLoader.GetTestPackage (string path, string configName) inline
References NUnit.Engine.Services.ProjectLoaders.NUnitProject.GetTestPackage(), and NUnit.Engine.Services.ProjectLoaders.NUnitProject.Load().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/Addins/nunit-project-loader/NUnitProjectLoader.cs