Doc: IGLib EXTENDED: Test.RatioOfUniformsNormalGenerator Class Reference
Test.RatioOfUniformsNormalGenerator Class Reference
Public Member Functions
double GetNext (Random rng)
Static Private Attributes
static readonly double c0 = Math.Sqrt(2.0 / Math.E)
static readonly double c1 = 4.0 * Math.Pow(Math.E, 0.25)
static readonly double c2 = 4.0 * Math.Pow(Math.E, -1.35)
Member Function Documentation
GetNext()
double Test.RatioOfUniformsNormalGenerator.GetNext (Random rng) inline
Implements Test.IDeviateGenerator.
References Test.RatioOfUniformsNormalGenerator.c0, Test.RatioOfUniformsNormalGenerator.c1, and Test.RatioOfUniformsNormalGenerator.c2.
Member Data Documentation
c0
readonly double Test.RatioOfUniformsNormalGenerator.c0 = Math.Sqrt(2.0 / Math.E) static private
Referenced by Test.RatioOfUniformsNormalGenerator.GetNext().
c1
readonly double Test.RatioOfUniformsNormalGenerator.c1 = 4.0 * Math.Pow(Math.E, 0.25) static private
Referenced by Test.RatioOfUniformsNormalGenerator.GetNext().
c2
readonly double Test.RatioOfUniformsNormalGenerator.c2 = 4.0 * Math.Pow(Math.E, -1.35) static private
Referenced by Test.RatioOfUniformsNormalGenerator.GetNext().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/RandomTest.cs