Doc: IGLib EXTENDED: NUnit.Common.ColorConsole Class Reference
NUnit.Common.ColorConsole Class Reference
Sets the console color in the constructor and resets it in the dispose
Public Member Functions
ColorConsole (ColorStyle style)
Initializes a new instance of the ColorConsole class.
void Dispose ()
If color is enabled, restores the console colors to their defaults
Static Public Member Functions
static ConsoleColor GetColor (ColorStyle style)
By using styles, we can keep everything consistent
Static Private Member Functions
static ConsoleColor GetColorForStyle (ColorStyle style)
Detailed Description
Sets the console color in the constructor and resets it in the dispose
Constructor & Destructor Documentation
ColorConsole()
NUnit.Common.ColorConsole.ColorConsole (ColorStyle style) inline
Initializes a new instance of the ColorConsole class.
Parameters
style The color style to use.
References NUnit.Common.ColorConsole.GetColor().
Member Function Documentation
GetColor()
static ConsoleColor NUnit.Common.ColorConsole.GetColor (ColorStyle style) inline static
By using styles, we can keep everything consistent
Parameters
style
Returns
Referenced by NUnit.Common.ColorConsole.ColorConsole(), NUnit.ConsoleRunner.Tests.ColorConsoleTests.SetUp(), NUnit.ConsoleRunner.Tests.ColorConsoleTests.TestConstructor(), and NUnit.ConsoleRunner.Utilities.Tests.ColorStyleTests.TestGetColor().
GetColorForStyle()
static ConsoleColor NUnit.Common.ColorConsole.GetColorForStyle (ColorStyle style) inline static private
Dispose()
void NUnit.Common.ColorConsole.Dispose () inline
If color is enabled, restores the console colors to their defaults
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/nunit/ColorConsole.cs