Doc: IGLib EXTENDED: AForge.Math.Tests.Matrix4x4Test Class Reference
AForge.Math.Tests.Matrix4x4Test Class Reference
Public Member Functions
Matrix4x4Test ()
void ToArrayTest ()
void CreateFromRowsTest ()
void CreateFromColumnsTest ()
void CreateRotationYTest (float angle)
void CreateRotationXTest (float angle)
void CreateRotationZTest (float angle)
void CreateFromYawPitchRollTest (float yaw, float pitch, float roll)
void ExtractYawPitchRollTest (float yaw, float pitch, float roll)
void CreateDiagonalTest (float v00, float v11, float v22, float v33)
void AddMatricesTest ()
void SubtractMatricesTest ()
void MultiplyMatricesTest ()
Private Member Functions
void CompareMatrixWithArray (Matrix4x4 matrix, float[] array)
bool ApproximateEquals (Matrix4x4 matrix1, Matrix4x4 matrix2)
Private Attributes
Matrix4x4 a1 = new Matrix4x4()
Matrix4x4 a2 = new Matrix4x4()
Static Private Attributes
const float Epsilon = 0.000001f
Constructor & Destructor Documentation
Matrix4x4Test()
AForge.Math.Tests.Matrix4x4Test.Matrix4x4Test () inline
References AForge.Math.Tests.Matrix4x4Test.a1, AForge.Math.Tests.Matrix4x4Test.a2, AForge.Math.Matrix4x4.V00, AForge.Math.Matrix4x4.V01, AForge.Math.Matrix4x4.V02, AForge.Math.Matrix4x4.V03, AForge.Math.Matrix4x4.V10, AForge.Math.Matrix4x4.V11, AForge.Math.Matrix4x4.V12, AForge.Math.Matrix4x4.V13, AForge.Math.Matrix4x4.V20, AForge.Math.Matrix4x4.V21, AForge.Math.Matrix4x4.V22, AForge.Math.Matrix4x4.V23, AForge.Math.Matrix4x4.V30, AForge.Math.Matrix4x4.V31, AForge.Math.Matrix4x4.V32, and AForge.Math.Matrix4x4.V33.
Member Function Documentation
ToArrayTest()
void AForge.Math.Tests.Matrix4x4Test.ToArrayTest () inline
References AForge.Math.Matrix4x4.ToArray(), AForge.Math.Matrix4x4.V00, AForge.Math.Matrix4x4.V01, AForge.Math.Matrix4x4.V02, AForge.Math.Matrix4x4.V03, AForge.Math.Matrix4x4.V10, AForge.Math.Matrix4x4.V11, AForge.Math.Matrix4x4.V12, AForge.Math.Matrix4x4.V13, AForge.Math.Matrix4x4.V20, AForge.Math.Matrix4x4.V21, AForge.Math.Matrix4x4.V22, AForge.Math.Matrix4x4.V23, AForge.Math.Matrix4x4.V30, AForge.Math.Matrix4x4.V31, AForge.Math.Matrix4x4.V32, and AForge.Math.Matrix4x4.V33.
CreateFromRowsTest()
void AForge.Math.Tests.Matrix4x4Test.CreateFromRowsTest () inline
References AForge.Math.Matrix4x4.CreateFromRows(), AForge.Math.Matrix4x4.GetRow(), and AForge.Math.Matrix4x4.ToArray().
CreateFromColumnsTest()
void AForge.Math.Tests.Matrix4x4Test.CreateFromColumnsTest () inline
References AForge.Math.Matrix4x4.CreateFromColumns(), AForge.Math.Matrix4x4.GetColumn(), and AForge.Math.Matrix4x4.ToArray().
CreateRotationYTest()
void AForge.Math.Tests.Matrix4x4Test.CreateRotationYTest (float angle) inline
References AForge.Math.Tests.Matrix4x4Test.CompareMatrixWithArray(), and AForge.Math.Matrix4x4.CreateRotationY().
CreateRotationXTest()
void AForge.Math.Tests.Matrix4x4Test.CreateRotationXTest (float angle) inline
References AForge.Math.Tests.Matrix4x4Test.CompareMatrixWithArray(), and AForge.Math.Matrix4x4.CreateRotationX().
CreateRotationZTest()
void AForge.Math.Tests.Matrix4x4Test.CreateRotationZTest (float angle) inline
References AForge.Math.Tests.Matrix4x4Test.CompareMatrixWithArray(), and AForge.Math.Matrix4x4.CreateRotationZ().
CreateFromYawPitchRollTest()
void AForge.Math.Tests.Matrix4x4Test.CreateFromYawPitchRollTest (float yaw, float pitch, float roll) inline
References AForge.Math.Tests.Matrix4x4Test.CompareMatrixWithArray(), AForge.Math.Matrix4x4.CreateFromYawPitchRoll(), AForge.Math.Matrix4x4.CreateRotationX(), AForge.Math.Matrix4x4.CreateRotationY(), AForge.Math.Matrix4x4.CreateRotationZ(), and AForge.Math.Matrix4x4.ToArray().
ExtractYawPitchRollTest()
void AForge.Math.Tests.Matrix4x4Test.ExtractYawPitchRollTest (float yaw, float pitch, float roll) inline
References AForge.Math.Matrix4x4.CreateFromYawPitchRoll(), AForge.Math.Tests.Matrix4x4Test.Epsilon, and AForge.Math.Matrix4x4.ExtractYawPitchRoll().
CreateDiagonalTest()
void AForge.Math.Tests.Matrix4x4Test.CreateDiagonalTest (float v00, float v11, float v22, float v33) inline
References AForge.Math.Tests.Matrix4x4Test.CompareMatrixWithArray(), and AForge.Math.Matrix4x4.CreateDiagonal().
AddMatricesTest()
void AForge.Math.Tests.Matrix4x4Test.AddMatricesTest () inline
References AForge.Math.Tests.Matrix4x4Test.a1, AForge.Math.Tests.Matrix4x4Test.a2, AForge.Math.Tests.Matrix4x4Test.ApproximateEquals(), AForge.Math.Matrix4x4.V00, AForge.Math.Matrix4x4.V01, AForge.Math.Matrix4x4.V02, AForge.Math.Matrix4x4.V03, AForge.Math.Matrix4x4.V10, AForge.Math.Matrix4x4.V11, AForge.Math.Matrix4x4.V12, AForge.Math.Matrix4x4.V13, AForge.Math.Matrix4x4.V20, AForge.Math.Matrix4x4.V21, AForge.Math.Matrix4x4.V22, AForge.Math.Matrix4x4.V23, AForge.Math.Matrix4x4.V30, AForge.Math.Matrix4x4.V31, AForge.Math.Matrix4x4.V32, and AForge.Math.Matrix4x4.V33.
SubtractMatricesTest()
void AForge.Math.Tests.Matrix4x4Test.SubtractMatricesTest () inline
References AForge.Math.Tests.Matrix4x4Test.a1, AForge.Math.Tests.Matrix4x4Test.a2, AForge.Math.Tests.Matrix4x4Test.ApproximateEquals(), AForge.Math.Matrix4x4.V00, AForge.Math.Matrix4x4.V01, AForge.Math.Matrix4x4.V02, AForge.Math.Matrix4x4.V03, AForge.Math.Matrix4x4.V10, AForge.Math.Matrix4x4.V11, AForge.Math.Matrix4x4.V12, AForge.Math.Matrix4x4.V13, AForge.Math.Matrix4x4.V20, AForge.Math.Matrix4x4.V21, AForge.Math.Matrix4x4.V22, AForge.Math.Matrix4x4.V23, AForge.Math.Matrix4x4.V30, AForge.Math.Matrix4x4.V31, AForge.Math.Matrix4x4.V32, and AForge.Math.Matrix4x4.V33.
MultiplyMatricesTest()
void AForge.Math.Tests.Matrix4x4Test.MultiplyMatricesTest () inline
References AForge.Math.Tests.Matrix4x4Test.a1, AForge.Math.Tests.Matrix4x4Test.a2, AForge.Math.Tests.Matrix4x4Test.ApproximateEquals(), AForge.Math.Matrix4x4.V00, AForge.Math.Matrix4x4.V01, AForge.Math.Matrix4x4.V02, AForge.Math.Matrix4x4.V03, AForge.Math.Matrix4x4.V10, AForge.Math.Matrix4x4.V11, AForge.Math.Matrix4x4.V12, AForge.Math.Matrix4x4.V13, AForge.Math.Matrix4x4.V20, AForge.Math.Matrix4x4.V21, AForge.Math.Matrix4x4.V22, AForge.Math.Matrix4x4.V23, AForge.Math.Matrix4x4.V30, AForge.Math.Matrix4x4.V31, AForge.Math.Matrix4x4.V32, and AForge.Math.Matrix4x4.V33.
CompareMatrixWithArray()
void AForge.Math.Tests.Matrix4x4Test.CompareMatrixWithArray (Matrix4x4 matrix, float[] array) inline private
References AForge.Math.Matrix4x4.ToArray().
Referenced by AForge.Math.Tests.Matrix4x4Test.CreateDiagonalTest(), AForge.Math.Tests.Matrix4x4Test.CreateFromYawPitchRollTest(), AForge.Math.Tests.Matrix4x4Test.CreateRotationXTest(), AForge.Math.Tests.Matrix4x4Test.CreateRotationYTest(), and AForge.Math.Tests.Matrix4x4Test.CreateRotationZTest().
ApproximateEquals()
bool AForge.Math.Tests.Matrix4x4Test.ApproximateEquals (Matrix4x4 matrix1, Matrix4x4 matrix2) inline private
References AForge.Math.Tests.Matrix4x4Test.Epsilon, AForge.Math.Matrix4x4.V00, AForge.Math.Matrix4x4.V01, AForge.Math.Matrix4x4.V02, AForge.Math.Matrix4x4.V03, AForge.Math.Matrix4x4.V10, AForge.Math.Matrix4x4.V11, AForge.Math.Matrix4x4.V12, AForge.Math.Matrix4x4.V13, AForge.Math.Matrix4x4.V20, AForge.Math.Matrix4x4.V21, AForge.Math.Matrix4x4.V22, AForge.Math.Matrix4x4.V23, AForge.Math.Matrix4x4.V30, AForge.Math.Matrix4x4.V31, AForge.Math.Matrix4x4.V32, and AForge.Math.Matrix4x4.V33.
Referenced by AForge.Math.Tests.Matrix4x4Test.AddMatricesTest(), AForge.Math.Tests.Matrix4x4Test.MultiplyMatricesTest(), and AForge.Math.Tests.Matrix4x4Test.SubtractMatricesTest().
Member Data Documentation
Epsilon
const float AForge.Math.Tests.Matrix4x4Test.Epsilon = 0.000001f static private
Referenced by AForge.Math.Tests.Matrix4x4Test.ApproximateEquals(), and AForge.Math.Tests.Matrix4x4Test.ExtractYawPitchRollTest().
a1
Matrix4x4 AForge.Math.Tests.Matrix4x4Test.a1 = new Matrix4x4() private
Referenced by AForge.Math.Tests.Matrix4x4Test.AddMatricesTest(), AForge.Math.Tests.Matrix4x4Test.Matrix4x4Test(), AForge.Math.Tests.Matrix4x4Test.MultiplyMatricesTest(), and AForge.Math.Tests.Matrix4x4Test.SubtractMatricesTest().
a2
Matrix4x4 AForge.Math.Tests.Matrix4x4Test.a2 = new Matrix4x4() private
Referenced by AForge.Math.Tests.Matrix4x4Test.AddMatricesTest(), AForge.Math.Tests.Matrix4x4Test.Matrix4x4Test(), AForge.Math.Tests.Matrix4x4Test.MultiplyMatricesTest(), and AForge.Math.Tests.Matrix4x4Test.SubtractMatricesTest().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Unit Tests/AForge.Math.Tests/Matrix4x4Test.cs