Doc: IGLib EXTENDED: AForge.Video.Ximea.XimeaVideoSource Class Reference
AForge.Video.Ximea.XimeaVideoSource Class Reference
The class provides continues access to XIMEA cameras.
Public Member Functions
XimeaVideoSource (int deviceID)
Initializes a new instance of the XimeaVideoSource class.
void Start ()
Start video source.
void SignalToStop ()
Signal video source to stop its work.
void WaitForStop ()
Wait for video source has stopped.
void Stop ()
Stop video source.
void SetParam (string parameterName, int value)
Set camera's parameter.
void SetParam (string parameterName, float value)
Set camera's parameter.
int GetParamInt (string parameterName)
Get camera's parameter as integer value.
float GetParamFloat (string parameterName)
Get camera's parameter as float value.
string GetParamString (string parameterName)
Get camera's parameter as string value.
Properties
virtual string Source [get]
A string identifying the video source.
bool IsRunning [get]
State of the video source.
long BytesReceived [get]
Received bytes count.
int FramesReceived [get]
Received frames count.
int FrameInterval [get, set]
Time interval between frames.
Properties inherited from AForge.Video.IVideoSource
string Source [get]
Video source.
int FramesReceived [get]
Received frames count.
long BytesReceived [get]
Received bytes count.
bool IsRunning [get]
State of the video source.
Events
NewFrameEventHandler NewFrame
New frame event.
VideoSourceErrorEventHandler VideoSourceError
Video source error event.
PlayingFinishedEventHandler PlayingFinished
Video playing finished event.
Events inherited from AForge.Video.IVideoSource
NewFrameEventHandler NewFrame
New frame event.
VideoSourceErrorEventHandler VideoSourceError
Video source error event.
PlayingFinishedEventHandler PlayingFinished
Video playing finished event.
Private Member Functions
void Free ()
void WorkerThread ()
Private Attributes
XimeaCamera camera = new XimeaCamera()
int deviceID
int framesReceived
long bytesReceived
int frameInterval = 200
Thread thread = null
ManualResetEvent stopEvent = null
object sync = new object()
Detailed Description
The class provides continues access to XIMEA cameras.
The video source class is aimed to provide continues access to XIMEA camera, when images are continuosly acquired from camera and provided throw the NewFrame event. It just creates a background thread and gets new images from XIMEA camera keeping the specified time interval between image acquisition. Essentially it is a wrapper class around XimeaCamera providing IVideoSource interface.
Sample usage:
// create video source for the XIMEA camera with ID 0
XimeaVideoSource videoSource = new XimeaVideoSource(0);
// set event handlers
videoSource.NewFrame += new NewFrameEventHandler(video_NewFrame);
// start the video source
videoSource.Start();
// set exposure time to 10 milliseconds
videoSource.SetParam(CameraParameter.Exposure, 10 * 1000);
// ...
// New frame event handler, which is invoked on each new available video frame
private void video_NewFrame(object sender, NewFrameEventArgs eventArgs)
{
    // get new frame
    Bitmap bitmap = eventArgs.Frame;
    // process the frame
}
See also
XimeaCamera
Constructor & Destructor Documentation
XimeaVideoSource()
AForge.Video.Ximea.XimeaVideoSource.XimeaVideoSource (int deviceID) inline
Initializes a new instance of the XimeaVideoSource class.
Parameters
deviceID XIMEA camera ID (index) to connect to.
References AForge.Video.Ximea.XimeaVideoSource.deviceID.
Member Function Documentation
Start()
void AForge.Video.Ximea.XimeaVideoSource.Start () inline
Start video source.
Starts video source and returns execution to caller. Video camera will be started and will provide new video frames through the NewFrame event.
Exceptions
ArgumentException There is no XIMEA camera with specified ID connected to the system.
VideoException An error occurred while communicating with a camera. See error message for additional information.
Implements AForge.Video.IVideoSource.
References AForge.Video.Ximea.XimeaVideoSource.bytesReceived, AForge.Video.Ximea.XimeaVideoSource.camera, AForge.Video.Ximea.XimeaCamera.CamerasCount, AForge.Video.Ximea.XimeaVideoSource.deviceID, AForge.Video.Ximea.XimeaVideoSource.framesReceived, AForge.Video.Ximea.XimeaVideoSource.IsRunning, AForge.Video.Ximea.XimeaCamera.Open(), AForge.Video.Ximea.XimeaVideoSource.Source, AForge.Video.Ximea.XimeaVideoSource.stopEvent, AForge.Video.Ximea.XimeaVideoSource.sync, AForge.Video.Ximea.XimeaVideoSource.thread, and AForge.Video.Ximea.XimeaVideoSource.WorkerThread().
Referenced by XimeaSample.MainForm.connectButton_Click().
SignalToStop()
void AForge.Video.Ximea.XimeaVideoSource.SignalToStop () inline
Signal video source to stop its work.
Implements AForge.Video.IVideoSource.
References AForge.Video.Ximea.XimeaVideoSource.stopEvent, AForge.Video.Ximea.XimeaVideoSource.sync, and AForge.Video.Ximea.XimeaVideoSource.thread.
Referenced by XimeaSample.MainForm.CloseCamera().
WaitForStop()
void AForge.Video.Ximea.XimeaVideoSource.WaitForStop () inline
Wait for video source has stopped.
Implements AForge.Video.IVideoSource.
References AForge.Video.Ximea.XimeaVideoSource.Free(), AForge.Video.Ximea.XimeaVideoSource.sync, and AForge.Video.Ximea.XimeaVideoSource.thread.
Referenced by XimeaSample.MainForm.CloseCamera().
Stop()
void AForge.Video.Ximea.XimeaVideoSource.Stop () inline
Stop video source.
The method stops the video source, so it no longer provides new video frames and does not consume any resources.
Implements AForge.Video.IVideoSource.
References AForge.Video.Ximea.XimeaVideoSource.Free(), AForge.Video.Ximea.XimeaVideoSource.sync, and AForge.Video.Ximea.XimeaVideoSource.thread.
SetParam() [1/2]
void AForge.Video.Ximea.XimeaVideoSource.SetParam (string parameterName, int value) inline
Set camera's parameter.
Parameters
parameterName Parameter name.
value Integer parameter value.
<note>The call is redirected to XimeaCamera.SetParam(string, int).</note>
References AForge.Video.Ximea.XimeaVideoSource.camera, and AForge.Video.Ximea.XimeaCamera.SetParam().
Referenced by XimeaSample.MainForm.exposureUpDown_ValueChanged(), XimeaSample.MainForm.gainUpDown_ValueChanged(), XimeaSample.MainForm.heightUpDown_ValueChanged(), XimeaSample.MainForm.offsetXUpDown_ValueChanged(), XimeaSample.MainForm.offsetYUpDown_ValueChanged(), and XimeaSample.MainForm.widthUpDown_ValueChanged().
SetParam() [2/2]
void AForge.Video.Ximea.XimeaVideoSource.SetParam (string parameterName, float value) inline
Set camera's parameter.
Parameters
parameterName Parameter name.
value Float parameter value.
<note>The call is redirected to XimeaCamera.GetParamFloat.</note>
References AForge.Video.Ximea.XimeaVideoSource.camera, and AForge.Video.Ximea.XimeaCamera.SetParam().
GetParamInt()
int AForge.Video.Ximea.XimeaVideoSource.GetParamInt (string parameterName) inline
Get camera's parameter as integer value.
Parameters
parameterName Parameter name to get from camera.
Returns
Returns integer value of the requested parameter.
<note>The call is redirected to XimeaCamera.GetParamFloat.</note>
References AForge.Video.Ximea.XimeaVideoSource.camera, and AForge.Video.Ximea.XimeaCamera.GetParamInt().
Referenced by XimeaSample.MainForm.connectButton_Click().
GetParamFloat()
float AForge.Video.Ximea.XimeaVideoSource.GetParamFloat (string parameterName) inline
Get camera's parameter as float value.
Parameters
parameterName Parameter name to get from camera.
Returns
Returns float value of the requested parameter.
<note>The call is redirected to XimeaCamera.GetParamFloat.</note>
References AForge.Video.Ximea.XimeaVideoSource.camera, and AForge.Video.Ximea.XimeaCamera.GetParamFloat().
Referenced by XimeaSample.MainForm.connectButton_Click(), and XimeaSample.MainForm.exposureUpDown_ValueChanged().
GetParamString()
string AForge.Video.Ximea.XimeaVideoSource.GetParamString (string parameterName) inline
Get camera's parameter as string value.
Parameters
parameterName Parameter name to get from camera.
Returns
Returns string value of the requested parameter.
<note>The call is redirected to XimeaCamera.GetParamString.</note>
References AForge.Video.Ximea.XimeaVideoSource.camera, and AForge.Video.Ximea.XimeaCamera.GetParamString().
Referenced by XimeaSample.MainForm.connectButton_Click().
Free()
void AForge.Video.Ximea.XimeaVideoSource.Free () inline private
References AForge.Video.Ximea.XimeaVideoSource.camera, AForge.Video.Ximea.XimeaCamera.Close(), AForge.Video.Ximea.XimeaVideoSource.stopEvent, AForge.Video.Ximea.XimeaVideoSource.sync, and AForge.Video.Ximea.XimeaVideoSource.thread.
Referenced by AForge.Video.Ximea.XimeaVideoSource.Stop(), and AForge.Video.Ximea.XimeaVideoSource.WaitForStop().
WorkerThread()
void AForge.Video.Ximea.XimeaVideoSource.WorkerThread () inline private
References AForge.Video.Ximea.XimeaVideoSource.bytesReceived, AForge.Video.Ximea.XimeaVideoSource.camera, AForge.Video.Ximea.XimeaVideoSource.frameInterval, AForge.Video.Ximea.XimeaVideoSource.framesReceived, AForge.Video.Ximea.XimeaCamera.GetImage(), AForge.Video.Ximea.XimeaVideoSource.NewFrame, AForge.Video.Ximea.XimeaVideoSource.PlayingFinished, AForge.Video.Ximea.XimeaCamera.StartAcquisition(), AForge.Video.Ximea.XimeaCamera.StopAcquisition(), AForge.Video.Ximea.XimeaVideoSource.stopEvent, and AForge.Video.Ximea.XimeaVideoSource.VideoSourceError.
Referenced by AForge.Video.Ximea.XimeaVideoSource.Start().
Member Data Documentation
camera
XimeaCamera AForge.Video.Ximea.XimeaVideoSource.camera = new XimeaCamera() private
Referenced by AForge.Video.Ximea.XimeaVideoSource.Free(), AForge.Video.Ximea.XimeaVideoSource.GetParamFloat(), AForge.Video.Ximea.XimeaVideoSource.GetParamInt(), AForge.Video.Ximea.XimeaVideoSource.GetParamString(), AForge.Video.Ximea.XimeaVideoSource.SetParam(), AForge.Video.Ximea.XimeaVideoSource.Start(), and AForge.Video.Ximea.XimeaVideoSource.WorkerThread().
deviceID
int AForge.Video.Ximea.XimeaVideoSource.deviceID private
Referenced by AForge.Video.Ximea.XimeaVideoSource.Start(), and AForge.Video.Ximea.XimeaVideoSource.XimeaVideoSource().
framesReceived
int AForge.Video.Ximea.XimeaVideoSource.framesReceived private
Referenced by AForge.Video.Ximea.XimeaVideoSource.Start(), and AForge.Video.Ximea.XimeaVideoSource.WorkerThread().
bytesReceived
long AForge.Video.Ximea.XimeaVideoSource.bytesReceived private
Referenced by AForge.Video.Ximea.XimeaVideoSource.Start(), and AForge.Video.Ximea.XimeaVideoSource.WorkerThread().
frameInterval
int AForge.Video.Ximea.XimeaVideoSource.frameInterval = 200 private
Referenced by AForge.Video.Ximea.XimeaVideoSource.WorkerThread().
thread
Thread AForge.Video.Ximea.XimeaVideoSource.thread = null private
Referenced by AForge.Video.Ximea.XimeaVideoSource.Free(), AForge.Video.Ximea.XimeaVideoSource.SignalToStop(), AForge.Video.Ximea.XimeaVideoSource.Start(), AForge.Video.Ximea.XimeaVideoSource.Stop(), and AForge.Video.Ximea.XimeaVideoSource.WaitForStop().
stopEvent
ManualResetEvent AForge.Video.Ximea.XimeaVideoSource.stopEvent = null private
Referenced by AForge.Video.Ximea.XimeaVideoSource.Free(), AForge.Video.Ximea.XimeaVideoSource.SignalToStop(), AForge.Video.Ximea.XimeaVideoSource.Start(), and AForge.Video.Ximea.XimeaVideoSource.WorkerThread().
sync
object AForge.Video.Ximea.XimeaVideoSource.sync = new object() private
Referenced by AForge.Video.Ximea.XimeaVideoSource.Free(), AForge.Video.Ximea.XimeaVideoSource.SignalToStop(), AForge.Video.Ximea.XimeaVideoSource.Start(), AForge.Video.Ximea.XimeaVideoSource.Stop(), and AForge.Video.Ximea.XimeaVideoSource.WaitForStop().
Property Documentation
Source
virtual string AForge.Video.Ximea.XimeaVideoSource.Source get
A string identifying the video source.
Referenced by AForge.Video.Ximea.XimeaVideoSource.Start().
IsRunning
bool AForge.Video.Ximea.XimeaVideoSource.IsRunning get
State of the video source.
Current state of video source object - running or not.
Referenced by AForge.Video.Ximea.XimeaVideoSource.Start().
BytesReceived
long AForge.Video.Ximea.XimeaVideoSource.BytesReceived get
Received bytes count.
Number of bytes the video source provided from the moment of the last access to the property.
FramesReceived
int AForge.Video.Ximea.XimeaVideoSource.FramesReceived get
Received frames count.
Number of frames the video source provided from the moment of the last access to the property.
Referenced by XimeaSample.MainForm.exposureUpDown_ValueChanged(), and XimeaSample.MainForm.timer_Tick().
FrameInterval
int AForge.Video.Ximea.XimeaVideoSource.FrameInterval get set
Time interval between frames.
The property sets the interval in milliseconds between getting new frames from the camera. If the property is set to 100, then the desired frame rate should be about 10 frames per second.
<note>Setting this property to 0 leads to no delay between video frames - frames are read as fast as possible.</note>
Default value is set to 200.
Referenced by XimeaSample.MainForm.exposureUpDown_ValueChanged().
Event Documentation
NewFrame
NewFrameEventHandler AForge.Video.Ximea.XimeaVideoSource.NewFrame
New frame event.
Notifies clients about new available frames from the video source.
<note>Since video source may have multiple clients, each client is responsible for making a copy (cloning) of the passed video frame, because the video source disposes its own original copy after notifying of clients.</note>
Referenced by AForge.Video.Ximea.XimeaVideoSource.WorkerThread().
VideoSourceError
VideoSourceErrorEventHandler AForge.Video.Ximea.XimeaVideoSource.VideoSourceError
Video source error event.
This event is used to notify clients about any type of errors occurred in video source object, for example internal exceptions.
Referenced by AForge.Video.Ximea.XimeaVideoSource.WorkerThread().
PlayingFinished
PlayingFinishedEventHandler AForge.Video.Ximea.XimeaVideoSource.PlayingFinished
Video playing finished event.
This event is used to notify clients that the video playing has finished.
Referenced by AForge.Video.Ximea.XimeaVideoSource.WorkerThread().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Video.Ximea/XimeaVideoSource.cs