Doc: IGLib EXTENDED: NUnit.Engine.Services.Tests.InProcessTestRunnerFactoryTests Class Reference
NUnit.Engine.Services.Tests.InProcessTestRunnerFactoryTests Class Reference
Public Member Functions
void CreateServiceContext ()
void ServiceIsStarted ()
void CorrectRunnerIsUsed (string files, string domainUsage, Type expectedType)
Private Attributes
InProcessTestRunnerFactory _factory
Member Function Documentation
CreateServiceContext()
void NUnit.Engine.Services.Tests.InProcessTestRunnerFactoryTests.CreateServiceContext () inline
References NUnit.Engine.Services.Tests.InProcessTestRunnerFactoryTests._factory.
ServiceIsStarted()
void NUnit.Engine.Services.Tests.InProcessTestRunnerFactoryTests.ServiceIsStarted () inline
References NUnit.Engine.Services.Tests.InProcessTestRunnerFactoryTests._factory, NUnit.Framework.Is.EqualTo(), NUnit.Engine.Services.Service.Status, and NUnit.Framework.Assert.That().
CorrectRunnerIsUsed()
void NUnit.Engine.Services.Tests.InProcessTestRunnerFactoryTests.CorrectRunnerIsUsed (string files, string domainUsage, Type expectedType) inline
References NUnit.Engine.Services.Tests.InProcessTestRunnerFactoryTests._factory, NUnit.Engine.Services.InProcessTestRunnerFactory.MakeTestRunner(), NUnit.Framework.Assert.That(), and NUnit.Framework.Is.TypeOf().
Member Data Documentation
_factory
InProcessTestRunnerFactory NUnit.Engine.Services.Tests.InProcessTestRunnerFactoryTests._factory private
Referenced by NUnit.Engine.Services.Tests.InProcessTestRunnerFactoryTests.CorrectRunnerIsUsed(), NUnit.Engine.Services.Tests.InProcessTestRunnerFactoryTests.CreateServiceContext(), and NUnit.Engine.Services.Tests.InProcessTestRunnerFactoryTests.ServiceIsStarted().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Services/InProcessTestRunnerFactoryTests.cs