Doc: IGLib EXTENDED: NUnit.Common.TestNameParser Class Reference
NUnit.Common.TestNameParser Class Reference
TestNameParser is used to parse the arguments to the -run option, separating testnames at the correct point.
Static Public Member Functions
static string[] Parse (string argument)
Parse the -run argument and return an array of argument
Static Private Member Functions
static string GetTestName (string argument, ref int index)
static int GetSeparator (string argument, int index)
Detailed Description
TestNameParser is used to parse the arguments to the -run option, separating testnames at the correct point.
Member Function Documentation
Parse()
static string [] NUnit.Common.TestNameParser.Parse (string argument) inline static
Parse the -run argument and return an array of argument
Parameters
argument argument
Returns
References NUnit.Common.TestNameParser.GetTestName().
Referenced by NUnit.Common.CommandLineOptions.ConfigureOptions(), NUnit.Common.Tests.TestNameParserTests.SingleName(), and NUnit.Common.Tests.TestNameParserTests.TwoNames().
GetTestName()
static string NUnit.Common.TestNameParser.GetTestName (string argument, ref int index) inline static private
References NUnit.Common.TestNameParser.GetSeparator().
Referenced by NUnit.Common.TestNameParser.Parse().
GetSeparator()
static int NUnit.Common.TestNameParser.GetSeparator (string argument, int index) inline static private
Referenced by NUnit.Common.TestNameParser.GetTestName().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/nunit/TestNameParser.cs