Doc: IGLib EXTENDED: NUnit.Engine.Internal.SettingsGroup Class Reference
NUnit.Engine.Internal.SettingsGroup Class Reference
SettingsGroup is the base class representing a group of user or system settings.
Public Member Functions
object GetSetting (string settingName)
Load the value of one of the group's settings
T GetSetting< T > (string settingName, T defaultValue)
Load the value of one of the group's settings or return a default value
void RemoveSetting (string settingName)
Remove a setting from the group
void RemoveGroup (string groupName)
Remove a group of settings
void SaveSetting (string settingName, object settingValue)
Save the value of one of the group's settings
Protected Attributes
Dictionary< string, object > _settings = new Dictionary<string, object>()
Events
SettingsEventHandler Changed
Events inherited from NUnit.Engine.ISettings
SettingsEventHandler Changed
Occurs when the settings are changed.
Static Private Attributes
static Logger log = InternalTrace.GetLogger("SettingsGroup")
Detailed Description
SettingsGroup is the base class representing a group of user or system settings.
Member Function Documentation
GetSetting()
object NUnit.Engine.Internal.SettingsGroup.GetSetting (string settingName) inline
Load the value of one of the group's settings
Parameters
settingName The name of setting to load
Returns
The value of the setting
Implements NUnit.Engine.ISettings.
References NUnit.Engine.Internal.SettingsGroup._settings.
Referenced by NUnit.Engine.Internal.SettingsGroup.GetSetting< T >(), NUnit.Engine.TestEngine.Initialize(), NUnit.Engine.Internal.SettingsGroup.SaveSetting(), NUnit.Engine.Internal.SettingsStore.SaveSettings(), NUnit.Engine.Internal.Tests.SettingsGroupTests.WhenSettingIsInitialized_ValueIsReturned(), NUnit.Engine.Internal.Tests.SettingsGroupTests.WhenSettingIsNotInitialized_DefaultValueIsReturned(), NUnit.Engine.Internal.Tests.SettingsGroupTests.WhenSettingIsNotInitialized_NullIsReturned(), NUnit.Engine.Internal.Tests.SettingsGroupTests.WhenSettingIsNotValid_DefaultSettingIsReturned(), and NUnit.Engine.Internal.Tests.SettingsGroupTests.WhenSettingIsRemoved_NullIsReturnedAndOtherSettingsAreNotAffected().
GetSetting< T >()
T NUnit.Engine.Internal.SettingsGroup.GetSetting< T > (string settingName, T defaultValue) inline
Load the value of one of the group's settings or return a default value
Parameters
settingName The name of setting to load
defaultValue The value to return if the setting is not present
Returns
The value of the setting or the default
Implements NUnit.Engine.ISettings.
References NUnit.Engine.Internal.SettingsGroup.GetSetting(), and NUnit.Engine.Internal.SettingsGroup.log.
RemoveSetting()
void NUnit.Engine.Internal.SettingsGroup.RemoveSetting (string settingName) inline
Remove a setting from the group
Parameters
settingName The name of the setting to remove
Implements NUnit.Engine.ISettings.
References NUnit.Engine.Internal.SettingsGroup._settings, and NUnit.Engine.Internal.SettingsGroup.Changed.
Referenced by NUnit.Engine.Internal.Tests.SettingsGroupTests.WhenSettingIsRemoved_NullIsReturnedAndOtherSettingsAreNotAffected().
RemoveGroup()
void NUnit.Engine.Internal.SettingsGroup.RemoveGroup (string groupName) inline
Remove a group of settings
Parameters
groupName The name of the group to remove
Implements NUnit.Engine.ISettings.
References NUnit.Engine.Internal.SettingsGroup._settings.
SaveSetting()
void NUnit.Engine.Internal.SettingsGroup.SaveSetting (string settingName, object settingValue) inline
Save the value of one of the group's settings
Parameters
settingName The name of the setting to save
settingValue The value to be saved
Implements NUnit.Engine.ISettings.
References NUnit.Engine.Internal.SettingsGroup._settings, NUnit.Engine.Internal.SettingsGroup.Changed, and NUnit.Engine.Internal.SettingsGroup.GetSetting().
Referenced by NUnit.Engine.Internal.SettingsStore.LoadSettings(), NUnit.Engine.Internal.Tests.SettingsGroupTests.WhenSettingIsInitialized_ValueIsReturned(), NUnit.Engine.Internal.Tests.SettingsGroupTests.WhenSettingIsNotValid_DefaultSettingIsReturned(), and NUnit.Engine.Internal.Tests.SettingsGroupTests.WhenSettingIsRemoved_NullIsReturnedAndOtherSettingsAreNotAffected().
Member Data Documentation
log
Logger NUnit.Engine.Internal.SettingsGroup.log = InternalTrace.GetLogger("SettingsGroup") static private
Referenced by NUnit.Engine.Internal.SettingsGroup.GetSetting< T >().
_settings
Dictionary<string, object> NUnit.Engine.Internal.SettingsGroup._settings = new Dictionary<string, object>() protected
Referenced by NUnit.Engine.Internal.SettingsGroup.GetSetting(), NUnit.Engine.Internal.SettingsGroup.RemoveGroup(), NUnit.Engine.Internal.SettingsGroup.RemoveSetting(), NUnit.Engine.Internal.SettingsGroup.SaveSetting(), and NUnit.Engine.Internal.SettingsStore.SaveSettings().
Event Documentation
Changed
SettingsEventHandler NUnit.Engine.Internal.SettingsGroup.Changed
Referenced by NUnit.Engine.Internal.SettingsGroup.RemoveSetting(), and NUnit.Engine.Internal.SettingsGroup.SaveSetting().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine/Internal/SettingsGroup.cs