Doc: IGLib EXTENDED: NUnit.Common.ColorConsoleWriter Class Reference
NUnit.Common.ColorConsoleWriter Class Reference
Public Member Functions
ColorConsoleWriter ()
Construct a ColorConsoleWriter.
ColorConsoleWriter (bool colorEnabled)
Construct a ColorConsoleWriter.
override void Write (ColorStyle style, string value)
Writes the value with the specified style.
override void WriteLine (ColorStyle style, string value)
Writes the value with the specified style.
override void WriteLabel (string label, object option)
Writes the label and the option that goes with it.
override void WriteLabelLine (string label, object option)
Writes the label and the option that goes with it followed by a new line.
override void WriteLabel (string label, object option, ColorStyle valueStyle)
Writes the label and the option that goes with it and optionally writes a new line.
override void WriteLabelLine (string label, object option, ColorStyle valueStyle)
Writes the label and the option that goes with it followed by a new line.
Public Member Functions inherited from NUnit.Common.ExtendedTextWrapper
ExtendedTextWrapper (TextWriter writer)
override void Write (char value)
Write a single char value
override void Write (string value)
Write a string value
override void WriteLine (string value)
Write a string value followed by a NewLine
override void Close ()
Close the ExtendedTextWriter
override void Write (ColorStyle style, string value)
Writes the value with the specified style.
override void WriteLine (ColorStyle style, string value)
Writes the value with the specified style
override void WriteLabel (string label, object option)
Writes the label and the option that goes with it.
override void WriteLabel (string label, object option, ColorStyle valueStyle)
Writes the label and the option that goes with it.
override void WriteLabelLine (string label, object option)
Writes the label and the option that goes with it followed by a new line.
override void WriteLabelLine (string label, object option, ColorStyle valueStyle)
Writes the label and the option that goes with it followed by a new line.
Public Attributes
bool _colorEnabled
Additional Inherited Members
Protected Member Functions inherited from NUnit.Common.ExtendedTextWrapper
override void Dispose (bool disposing)
Dispose the Extended TextWriter
Properties inherited from NUnit.Common.ExtendedTextWrapper
override Encoding Encoding [get]
Gets the encoding for this ExtendedTextWriter
Constructor & Destructor Documentation
ColorConsoleWriter() [1/2]
NUnit.Common.ColorConsoleWriter.ColorConsoleWriter () inline
Construct a ColorConsoleWriter.
ColorConsoleWriter() [2/2]
NUnit.Common.ColorConsoleWriter.ColorConsoleWriter (bool colorEnabled) inline
Construct a ColorConsoleWriter.
Parameters
colorEnabled Flag indicating whether color should be enabled
References NUnit.Common.ColorConsoleWriter._colorEnabled.
Member Function Documentation
Write()
override void NUnit.Common.ColorConsoleWriter.Write (ColorStyle style, string value) inline virtual
Writes the value with the specified style.
Parameters
style The style.
value The value.
Implements NUnit.Common.ExtendedTextWriter.
Referenced by NUnit.Common.ColorConsoleWriter.WriteLabel().
WriteLine()
override void NUnit.Common.ColorConsoleWriter.WriteLine (ColorStyle style, string value) inline virtual
Writes the value with the specified style.
Parameters
style The style.
value The value.
Implements NUnit.Common.ExtendedTextWriter.
References NUnit.Common.ColorConsoleWriter._colorEnabled.
Referenced by NUnit.Common.ColorConsoleWriter.WriteLabelLine().
WriteLabel() [1/2]
override void NUnit.Common.ColorConsoleWriter.WriteLabel (string label, object option) inline virtual
Writes the label and the option that goes with it.
Parameters
label The label.
option The option.
Implements NUnit.Common.ExtendedTextWriter.
Referenced by NUnit.Common.ColorConsoleWriter.WriteLabelLine().
WriteLabelLine() [1/2]
override void NUnit.Common.ColorConsoleWriter.WriteLabelLine (string label, object option) inline virtual
Writes the label and the option that goes with it followed by a new line.
Parameters
label The label.
option The option.
Implements NUnit.Common.ExtendedTextWriter.
WriteLabel() [2/2]
override void NUnit.Common.ColorConsoleWriter.WriteLabel (string label, object option, ColorStyle valueStyle) inline virtual
Writes the label and the option that goes with it and optionally writes a new line.
Parameters
label The label.
option The option.
valueStyle The color to display the value with
Implements NUnit.Common.ExtendedTextWriter.
References NUnit.Common.ColorConsoleWriter.Write().
WriteLabelLine() [2/2]
override void NUnit.Common.ColorConsoleWriter.WriteLabelLine (string label, object option, ColorStyle valueStyle) inline virtual
Writes the label and the option that goes with it followed by a new line.
Parameters
label The label.
option The option.
valueStyle The color to display the value with
Implements NUnit.Common.ExtendedTextWriter.
References NUnit.Common.ColorConsoleWriter.WriteLabel(), and NUnit.Common.ColorConsoleWriter.WriteLine().
Member Data Documentation
_colorEnabled
bool NUnit.Common.ColorConsoleWriter._colorEnabled
Referenced by NUnit.Common.ColorConsoleWriter.ColorConsoleWriter(), and NUnit.Common.ColorConsoleWriter.WriteLine().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/nunit/ColorConsoleWriter.cs