Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DORM2R Class Reference
DotNumerics.LinearAlgebra.CSLapack.DORM2R Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DORM2R (LSAME lsame, DLARF dlarf, XERBLA xerbla)
DORM2R ()
void Run (string SIDE, string TRANS, int M, int N, int K, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
LSAME _lsame
DLARF _dlarf
XERBLA _xerbla
Static Private Attributes
const double ONE = 1.0E+0
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DORM2R overwrites the general real m by n matrix C with
Q * C if SIDE = 'L' and TRANS = 'N', or
Q'* C if SIDE = 'L' and TRANS = 'T', or
C * Q if SIDE = 'R' and TRANS = 'N', or
C * Q' if SIDE = 'R' and TRANS = 'T',
where Q is a real orthogonal matrix defined as the product of k elementary reflectors
Q = H(1) H(2) . . . H(k)
as returned by DGEQRF. Q is of order m if SIDE = 'L' and of order n if SIDE = 'R'.
/summary>
Constructor & Destructor Documentation
DORM2R() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DORM2R.DORM2R (LSAME lsame, DLARF dlarf, XERBLA xerbla) inline
DORM2R() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DORM2R.DORM2R () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DORM2R.Run (string SIDE, string TRANS, int M, int N, int K, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
DORM2R overwrites the general real m by n matrix C with
Q * C if SIDE = 'L' and TRANS = 'N', or
Q'* C if SIDE = 'L' and TRANS = 'T', or
C * Q if SIDE = 'R' and TRANS = 'N', or
C * Q' if SIDE = 'R' and TRANS = 'T',
where Q is a real orthogonal matrix defined as the product of k elementary reflectors
Q = H(1) H(2) . . . H(k)
as returned by DGEQRF. Q is of order m if SIDE = 'L' and of order n if SIDE = 'R'.
/summary>
Parameters
SIDE (input) CHARACTER*1 = 'L': apply Q or Q' from the Left = 'R': apply Q or Q' from the Right /param>
Parameters
TRANS (input) CHARACTER*1 = 'N': apply Q (No transpose) = 'T': apply Q' (Transpose) /param>
Parameters
M (input) INTEGER The number of rows of the matrix C. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix C. N .GE. 0. /param>
Parameters
K (input) INTEGER The number of elementary reflectors whose product defines the matrix Q. If SIDE = 'L', M .GE. K .GE. 0; if SIDE = 'R', N .GE. K .GE. 0. /param>
Parameters
A (input) DOUBLE PRECISION array, dimension (LDA,K) The i-th column must contain the vector which defines the elementary reflector H(i), for i = 1,2,...,k, as returned by DGEQRF in the first k columns of its array argument A. A is modified by the routine but restored on exit. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. If SIDE = 'L', LDA .GE. max(1,M); if SIDE = 'R', LDA .GE. max(1,N). /param>
Parameters
TAU (input) DOUBLE PRECISION array, dimension (K) TAU(i) must contain the scalar factor of the elementary reflector H(i), as returned by DGEQRF. /param>
Parameters
C
Q if SIDE = 'R' and TRANS = 'N', or /param>
Parameters
LDC (input) INTEGER The leading dimension of the array C. LDC .GE. max(1,M). /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (N) if SIDE = 'L', (M) if SIDE = 'R' /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.DORM2R.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLARF.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEQPF.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMQR.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGGSVP.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DORM2R._lsame private
_dlarf
DLARF DotNumerics.LinearAlgebra.CSLapack.DORM2R._dlarf private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DORM2R._xerbla private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DORM2R.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DORM2R.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dorm2r.cs