Doc: IGLib EXTENDED: AForge.Genetic.ISelectionMethod Interface Reference
AForge.Genetic.ISelectionMethod Interface Reference
Genetic selection method interface.
Public Member Functions
void ApplySelection (List< IChromosome > chromosomes, int size)
Apply selection to the specified population.
Detailed Description
Genetic selection method interface.
The interface should be implemented by all classes, which implement genetic selection algorithm. These algorithms select members of current generation, which should be kept in the new generation. Basically, these algorithms filter provided population keeping only specified amount of members.
Member Function Documentation
ApplySelection()
void AForge.Genetic.ISelectionMethod.ApplySelection (List< IChromosome > chromosomes, int size)
Apply selection to the specified population.
Parameters
chromosomes Population, which should be filtered.
size The amount of chromosomes to keep.
Filters specified population according to the implemented selection algorithm.
Implemented in AForge.Genetic.RankSelection, AForge.Genetic.RouletteWheelSelection, and AForge.Genetic.EliteSelection.
Referenced by AForge.Genetic.Population.Migrate(), AForge.Genetic.Population.Resize(), and AForge.Genetic.Population.Selection().
The documentation for this interface was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Genetic/Selection Algorithms/ISelectionMethod.cs