Doc: IGLib EXTENDED: NUnit.Framework.Constraints.MessageWriter Class Reference
NUnit.Framework.Constraints.MessageWriter Class Reference abstract
MessageWriter is the abstract base for classes that write constraint descriptions and messages in some form. The class has separate methods for writing various components of a message, allowing implementations to tailor the presentation as needed.
Public Member Functions
void WriteMessageLine (string message, params object[] args)
Method to write single line message with optional args, usually written to precede the general failure message.
abstract void WriteMessageLine (int level, string message, params object[] args)
Method to write single line message with optional args, usually written to precede the general failure message, at a givel indentation level.
abstract void DisplayDifferences (ConstraintResult result)
Display Expected and Actual lines for a constraint. This is called by MessageWriter's default implementation of WriteMessageTo and provides the generic two-line display.
abstract void DisplayDifferences (object expected, object actual)
Display Expected and Actual lines for given _values. This method may be called by constraints that need more control over the display of actual and expected _values than is provided by the default implementation.
abstract void DisplayDifferences (object expected, object actual, Tolerance tolerance)
Display Expected and Actual lines for given _values, including a tolerance value on the Expected line.
abstract void DisplayStringDifferences (string expected, string actual, int mismatch, bool ignoreCase, bool clipping)
Display the expected and actual string _values on separate lines. If the mismatch parameter is >=0, an additional line is displayed line containing a caret that points to the mismatch point.
abstract void WriteActualValue (object actual)
Writes the text for an actual value.
abstract void WriteValue (object val)
Writes the text for a generalized value.
abstract void WriteCollectionElements (IEnumerable collection, long start, int max)
Writes the text for a collection value, starting at a particular point, to a max length
Protected Member Functions
MessageWriter ()
Construct a MessageWriter given a culture
Properties
abstract int MaxLineLength [get, set]
Abstract method to get the max line length
Detailed Description
MessageWriter is the abstract base for classes that write constraint descriptions and messages in some form. The class has separate methods for writing various components of a message, allowing implementations to tailor the presentation as needed.
Constructor & Destructor Documentation
MessageWriter()
NUnit.Framework.Constraints.MessageWriter.MessageWriter () inline protected
Construct a MessageWriter given a culture
Member Function Documentation
WriteMessageLine() [1/2]
void NUnit.Framework.Constraints.MessageWriter.WriteMessageLine (string message, params object[] args) inline
Method to write single line message with optional args, usually written to precede the general failure message.
Parameters
message The message to be written
args Any arguments used in formatting the message
Referenced by NUnit.Framework.Constraints.EqualConstraintResult.DisplayFailurePoint(), NUnit.Framework.Constraints.EqualConstraintResult.DisplayStreamDifferences(), NUnit.Framework.Constraints.EqualConstraintResult.DisplayStringDifferences(), and NUnit.Framework.Constraints.EqualConstraintResult.DisplayTypesAndSizes().
WriteMessageLine() [2/2]
abstract void NUnit.Framework.Constraints.MessageWriter.WriteMessageLine (int level, string message, params object[] args) pure virtual
Method to write single line message with optional args, usually written to precede the general failure message, at a givel indentation level.
Parameters
level The indentation level of the message
message The message to be written
args Any arguments used in formatting the message
Implemented in NUnit.Framework.Internal.TextMessageWriter.
DisplayDifferences() [1/3]
abstract void NUnit.Framework.Constraints.MessageWriter.DisplayDifferences (ConstraintResult result) pure virtual
Display Expected and Actual lines for a constraint. This is called by MessageWriter's default implementation of WriteMessageTo and provides the generic two-line display.
Parameters
result The failing constraint result
Implemented in NUnit.Framework.Internal.TextMessageWriter.
Referenced by NUnit.Framework.Constraints.EqualConstraintResult.DisplayDifferences(), and NUnit.Framework.Constraints.ConstraintResult.WriteMessageTo().
DisplayDifferences() [2/3]
abstract void NUnit.Framework.Constraints.MessageWriter.DisplayDifferences (object expected, object actual) pure virtual
Display Expected and Actual lines for given _values. This method may be called by constraints that need more control over the display of actual and expected _values than is provided by the default implementation.
Parameters
expected The expected value
actual The actual value causing the failure
Implemented in NUnit.Framework.Internal.TextMessageWriter.
DisplayDifferences() [3/3]
abstract void NUnit.Framework.Constraints.MessageWriter.DisplayDifferences (object expected, object actual, Tolerance tolerance) pure virtual
Display Expected and Actual lines for given _values, including a tolerance value on the Expected line.
Parameters
expected The expected value
actual The actual value causing the failure
tolerance The tolerance within which the test was made
Implemented in NUnit.Framework.Internal.TextMessageWriter.
DisplayStringDifferences()
abstract void NUnit.Framework.Constraints.MessageWriter.DisplayStringDifferences (string expected, string actual, int mismatch, bool ignoreCase, bool clipping) pure virtual
Display the expected and actual string _values on separate lines. If the mismatch parameter is >=0, an additional line is displayed line containing a caret that points to the mismatch point.
Parameters
expected The expected string value
actual The actual string value
mismatch The point at which the strings don't match or -1
ignoreCase If true, case is ignored in locating the point where the strings differ
clipping If true, the strings should be clipped to fit the line
Implemented in NUnit.Framework.Internal.TextMessageWriter.
Referenced by NUnit.Framework.Constraints.EqualConstraintResult.DisplayStringDifferences().
WriteActualValue()
abstract void NUnit.Framework.Constraints.MessageWriter.WriteActualValue (object actual) pure virtual
Writes the text for an actual value.
Parameters
actual The actual value.
Implemented in NUnit.Framework.Internal.TextMessageWriter.
Referenced by NUnit.Framework.Constraints.ExceptionTypeConstraint.ExceptionTypeConstraintResult.WriteActualValueTo(), and NUnit.Framework.Constraints.ConstraintResult.WriteActualValueTo().
WriteValue()
abstract void NUnit.Framework.Constraints.MessageWriter.WriteValue (object val) pure virtual
Writes the text for a generalized value.
Parameters
val The value.
Implemented in NUnit.Framework.Internal.TextMessageWriter.
WriteCollectionElements()
abstract void NUnit.Framework.Constraints.MessageWriter.WriteCollectionElements (IEnumerable collection, long start, int max) pure virtual
Writes the text for a collection value, starting at a particular point, to a max length
Parameters
collection The collection containing elements to write.
start The starting point of the elements to write
max The maximum number of elements to write
Implemented in NUnit.Framework.Internal.TextMessageWriter.
Property Documentation
MaxLineLength
abstract int NUnit.Framework.Constraints.MessageWriter.MaxLineLength get set
Abstract method to get the max line length
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Constraints/MessageWriter.cs