Doc: IGLib EXTENDED: NUnit.Common.Tests.XmlHelperTests Class Reference
NUnit.Common.Tests.XmlHelperTests Class Reference
Public Member Functions
void SingleElement ()
void SingleElementWithAttributes ()
void ElementContainsElementWithInnerText ()
void ElementContainsElementWithCData ()
void SafeAttributeAccess ()
void SafeAttributeAccessWithIntDefaultValue ()
void SafeAttributeAccessWithDoubleDefaultValue ()
Member Function Documentation
SingleElement()
void NUnit.Common.Tests.XmlHelperTests.SingleElement () inline
References NUnit.Common.XmlHelper.CreateTopLevelElement(), NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
SingleElementWithAttributes()
void NUnit.Common.Tests.XmlHelperTests.SingleElementWithAttributes () inline
References NUnit.Common.XmlHelper.AddAttribute(), NUnit.Common.XmlHelper.CreateTopLevelElement(), NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
ElementContainsElementWithInnerText()
void NUnit.Common.Tests.XmlHelperTests.ElementContainsElementWithInnerText () inline
References NUnit.Common.XmlHelper.CreateTopLevelElement(), NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
ElementContainsElementWithCData()
void NUnit.Common.Tests.XmlHelperTests.ElementContainsElementWithCData () inline
References NUnit.Common.XmlHelper.CreateTopLevelElement(), NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
SafeAttributeAccess()
void NUnit.Common.Tests.XmlHelperTests.SafeAttributeAccess () inline
References NUnit.Common.XmlHelper.CreateTopLevelElement(), NUnit.Common.XmlHelper.GetAttribute(), NUnit.Framework.Is.Null, and NUnit.Framework.Assert.That().
SafeAttributeAccessWithIntDefaultValue()
void NUnit.Common.Tests.XmlHelperTests.SafeAttributeAccessWithIntDefaultValue () inline
References NUnit.Common.XmlHelper.CreateTopLevelElement(), NUnit.Framework.Is.EqualTo(), NUnit.Common.XmlHelper.GetAttribute(), and NUnit.Framework.Assert.That().
SafeAttributeAccessWithDoubleDefaultValue()
void NUnit.Common.Tests.XmlHelperTests.SafeAttributeAccessWithDoubleDefaultValue () inline
References NUnit.Common.XmlHelper.CreateTopLevelElement(), NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/tests/XmlHelperTests.cs