Doc: IGLib EXTENDED: AForge.Imaging.ColorReduction.ColorImageQuantizer Class Reference
AForge.Imaging.ColorReduction.ColorImageQuantizer Class Reference
Color quantization tools.
Public Member Functions
ColorImageQuantizer (IColorQuantizer quantizer)
Initializes a new instance of the ColorImageQuantizer class.
Color[] CalculatePalette (Bitmap image, int paletteSize)
Calculate reduced color palette for the specified image.
Color[] CalculatePalette (UnmanagedImage image, int paletteSize)
Calculate reduced color palette for the specified image.
Bitmap ReduceColors (Bitmap image, int paletteSize)
Create an image with reduced number of colors.
Bitmap ReduceColors (UnmanagedImage image, int paletteSize)
Create an image with reduced number of colors.
Bitmap ReduceColors (Bitmap image, Color[] palette)
Create an image with reduced number of colors using the specified palette.
Bitmap ReduceColors (UnmanagedImage image, Color[] palette)
Create an image with reduced number of colors using the specified palette.
Properties
IColorQuantizer Quantizer [get, set]
Color quantization algorithm used by this class to build color palettes for the specified images.
bool UseCaching [get, set]
Use color caching during color reduction or not.
Private Member Functions
int GetClosestColor (int red, int green, int blue)
Private Attributes
IColorQuantizer quantizer
bool useCaching = false
Color[] paletteToUse
Dictionary< Color, int > cache = new Dictionary<Color, int>()
Detailed Description
Color quantization tools.
The class contains methods aimed to simplify work with color quantization algorithms implementing IColorQuantizer interface. Using its methods it is possible to calculate reduced color palette for the specified image or reduce colors to the specified number.
Sample usage:
// instantiate the images' color quantization class
ColorImageQuantizer ciq = new ColorImageQuantizer(new MedianCutQuantizer());
// get 16 color palette for a given image
Color[] colorTable = ciq.CalculatePalette(image, 16);
// ... or just reduce colors in the specified image
Bitmap newImage = ciq.ReduceColors(image, 16);
Initial image:
Result image:
Constructor & Destructor Documentation
ColorImageQuantizer()
AForge.Imaging.ColorReduction.ColorImageQuantizer.ColorImageQuantizer (IColorQuantizer quantizer) inline
Initializes a new instance of the ColorImageQuantizer class.
Parameters
quantizer Color quantization algorithm to use for processing images.
References AForge.Imaging.ColorReduction.ColorImageQuantizer.quantizer.
Member Function Documentation
CalculatePalette() [1/2]
Color [] AForge.Imaging.ColorReduction.ColorImageQuantizer.CalculatePalette (Bitmap image, int paletteSize) inline
Calculate reduced color palette for the specified image.
Parameters
image Image to calculate palette for.
paletteSize Palette size to calculate.
Returns
Return reduced color palette for the specified image.
See CalculatePalette(UnmanagedImage, int) for details.
References AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.ColorReduction.ColorImageQuantizer.ReduceColors().
CalculatePalette() [2/2]
Color [] AForge.Imaging.ColorReduction.ColorImageQuantizer.CalculatePalette (UnmanagedImage image, int paletteSize) inline
Calculate reduced color palette for the specified image.
Parameters
image Image to calculate palette for.
paletteSize Palette size to calculate.
Returns
Return reduced color palette for the specified image.
The method processes the specified image and feeds color value of each pixel to the specified color quantization algorithm. Finally it returns color palette built by that algorithm.
Exceptions
UnsupportedImageFormatException Unsupported format of the source image - it must 24 or 32 bpp color image.
References AForge.Imaging.ColorReduction.IColorQuantizer.AddColor(), AForge.Imaging.RGB.B, AForge.Imaging.ColorReduction.IColorQuantizer.Clear(), AForge.Imaging.RGB.G, AForge.Imaging.ColorReduction.IColorQuantizer.GetPalette(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.ColorReduction.ColorImageQuantizer.quantizer, AForge.Imaging.RGB.R, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
ReduceColors() [1/4]
Bitmap AForge.Imaging.ColorReduction.ColorImageQuantizer.ReduceColors (Bitmap image, int paletteSize) inline
Create an image with reduced number of colors.
Parameters
image Source image to process.
paletteSize Number of colors to get in the output image, [2, 256].
Returns
Returns image with reduced number of colors.
See ReduceColors(UnmanagedImage, int) for details.
References AForge.Math.Geometry.Rectangle.
Referenced by AForge.Imaging.ColorReduction.ColorImageQuantizer.ReduceColors().
ReduceColors() [2/4]
Bitmap AForge.Imaging.ColorReduction.ColorImageQuantizer.ReduceColors (UnmanagedImage image, int paletteSize) inline
Create an image with reduced number of colors.
Parameters
image Source image to process.
paletteSize Number of colors to get in the output image, [2, 256].
Returns
Returns image with reduced number of colors.
The method creates an image, which looks similar to the specified image, but contains reduced number of colors. First, target color palette is calculated using CalculatePalette(UnmanagedImage, int) method and then a new image is created, where pixels from the given source image are substituted by best matching colors from calculated color table.
<note>The output image has 4 bpp or 8 bpp indexed pixel format depending on the target palette size - 4 bpp for palette size 16 or less; 8 bpp otherwise.</note>
Exceptions
UnsupportedImageFormatException Unsupported format of the source image - it must 24 or 32 bpp color image.
ArgumentException Invalid size of the target color palette.
References AForge.Imaging.ColorReduction.ColorImageQuantizer.CalculatePalette(), and AForge.Imaging.ColorReduction.ColorImageQuantizer.ReduceColors().
ReduceColors() [3/4]
Bitmap AForge.Imaging.ColorReduction.ColorImageQuantizer.ReduceColors (Bitmap image, Color[] palette) inline
Create an image with reduced number of colors using the specified palette.
Parameters
image Source image to process.
palette Target color palette. Must contatin 2-256 colors.
Returns
Returns image with reduced number of colors.
See ReduceColors(UnmanagedImage, Color[]) for details.
References AForge.Math.Geometry.Rectangle, and AForge.Imaging.ColorReduction.ColorImageQuantizer.ReduceColors().
ReduceColors() [4/4]
Bitmap AForge.Imaging.ColorReduction.ColorImageQuantizer.ReduceColors (UnmanagedImage image, Color[] palette) inline
Create an image with reduced number of colors using the specified palette.
Parameters
image Source image to process.
palette Target color palette. Must contatin 2-256 colors.
Returns
Returns image with reduced number of colors.
The method creates an image, which looks similar to the specified image, but contains reduced number of colors. Is substitutes every pixel of the source image with the closest matching color in the specified paletter.
<note>The output image has 4 bpp or 8 bpp indexed pixel format depending on the target palette size - 4 bpp for palette size 16 or less; 8 bpp otherwise.</note>
Exceptions
UnsupportedImageFormatException Unsupported format of the source image - it must 24 or 32 bpp color image.
ArgumentException Invalid size of the target color palette.
References AForge.Imaging.RGB.B, AForge.Imaging.ColorReduction.ColorImageQuantizer.cache, AForge.Imaging.RGB.G, AForge.Imaging.ColorReduction.ColorImageQuantizer.GetClosestColor(), AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.ColorReduction.ColorImageQuantizer.paletteToUse, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, AForge.Math.Geometry.Rectangle, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
GetClosestColor()
int AForge.Imaging.ColorReduction.ColorImageQuantizer.GetClosestColor (int red, int green, int blue) inline private
References AForge.Imaging.ColorReduction.ColorImageQuantizer.cache, AForge.Imaging.ColorReduction.ColorImageQuantizer.paletteToUse, and AForge.Imaging.ColorReduction.ColorImageQuantizer.useCaching.
Referenced by AForge.Imaging.ColorReduction.ColorImageQuantizer.ReduceColors().
Member Data Documentation
quantizer
IColorQuantizer AForge.Imaging.ColorReduction.ColorImageQuantizer.quantizer private
Referenced by AForge.Imaging.ColorReduction.ColorImageQuantizer.CalculatePalette(), and AForge.Imaging.ColorReduction.ColorImageQuantizer.ColorImageQuantizer().
useCaching
bool AForge.Imaging.ColorReduction.ColorImageQuantizer.useCaching = false private
Referenced by AForge.Imaging.ColorReduction.ColorImageQuantizer.GetClosestColor().
paletteToUse
Color [] AForge.Imaging.ColorReduction.ColorImageQuantizer.paletteToUse private
Referenced by AForge.Imaging.ColorReduction.ColorImageQuantizer.GetClosestColor(), and AForge.Imaging.ColorReduction.ColorImageQuantizer.ReduceColors().
cache
Dictionary<Color, int> AForge.Imaging.ColorReduction.ColorImageQuantizer.cache = new Dictionary<Color, int>() private
Referenced by AForge.Imaging.ColorReduction.ColorImageQuantizer.GetClosestColor(), and AForge.Imaging.ColorReduction.ColorImageQuantizer.ReduceColors().
Property Documentation
Quantizer
IColorQuantizer AForge.Imaging.ColorReduction.ColorImageQuantizer.Quantizer get set
Color quantization algorithm used by this class to build color palettes for the specified images.
UseCaching
bool AForge.Imaging.ColorReduction.ColorImageQuantizer.UseCaching get set
Use color caching during color reduction or not.
The property has effect only for methods like ReduceColors(Bitmap, int) and specifies if internal cache of already processed colors should be used or not. For each pixel in the original image the color reduction routine does search in target color palette to find the best matching color. To avoid doing the search again and again for already processed colors, the class may use internal dictionary which maps colors of original image to indexes in target color palette.
<note>The property provides a trade off. On one hand it may speedup color reduction routine, but on another hand it increases memory usage. Also cache usage may not be efficient for very small target color tables.</note>
Default value is set to false.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Color Reduction/ColorImageQuantizer.cs