Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGEQP3 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGEQP3 Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGEQP3 (DGEQRF dgeqrf, DLAQP2 dlaqp2, DLAQPS dlaqps, DORMQR dormqr, DSWAP dswap, XERBLA xerbla, ILAENV ilaenv, DNRM2 dnrm2)
DGEQP3 ()
void Run (int M, int N, ref double[] A, int offset_a, int LDA, ref int[] JPVT, int offset_jpvt, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
DGEQRF _dgeqrf
DLAQP2 _dlaqp2
DLAQPS _dlaqps
DORMQR _dormqr
DSWAP _dswap
XERBLA _xerbla
ILAENV _ilaenv
DNRM2 _dnrm2
Static Private Attributes
const int INB = 1
const int INBMIN = 2
const int IXOVER = 3
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGEQP3 computes a QR factorization with column pivoting of a matrix A: A*P = Q*R using Level 3 BLAS.
/summary>
Constructor & Destructor Documentation
DGEQP3() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGEQP3.DGEQP3 (DGEQRF dgeqrf, DLAQP2 dlaqp2, DLAQPS dlaqps, DORMQR dormqr, DSWAP dswap, XERBLA xerbla, ILAENV ilaenv, DNRM2 dnrm2) inline
DGEQP3() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGEQP3.DGEQP3 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGEQP3.Run (int M, int N, ref double[] A, int offset_a, int LDA, ref int[] JPVT, int offset_jpvt, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DGEQP3 computes a QR factorization with column pivoting of a matrix A: A*P = Q*R using Level 3 BLAS.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. 0. /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the M-by-N matrix A. On exit, the upper triangle of the array contains the min(M,N)-by-N upper trapezoidal matrix R; the elements below the diagonal, together with the array TAU, represent the orthogonal matrix Q as a product of min(M,N) elementary reflectors. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
JPVT (input/output) INTEGER array, dimension (N) On entry, if JPVT(J).ne.0, the J-th column of A is permuted to the front of A*P (a leading column); if JPVT(J)=0, the J-th column of A is a free column. On exit, if JPVT(J)=K, then the J-th column of A*P was the the K-th column of A. /param>
Parameters
TAU (output) DOUBLE PRECISION array, dimension (min(M,N)) The scalar factors of the elementary reflectors. /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO=0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. 3*N+1. For optimal performance LWORK .GE. 2*N+(N+1)*NB, where NB is the optimal blocksize.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit. .LT. 0: if INFO = -i, the i-th argument had an illegal value. /param>
References DotNumerics.LinearAlgebra.CSLapack.DGEQP3.INB, DotNumerics.LinearAlgebra.CSLapack.DGEQP3.INBMIN, DotNumerics.LinearAlgebra.CSLapack.DGEQP3.IXOVER, DotNumerics.LinearAlgebra.CSLapack.DNRM2.Run(), DotNumerics.LinearAlgebra.CSLapack.DSWAP.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQP2.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQPS.Run(), and DotNumerics.LinearAlgebra.CSLapack.DORMQR.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGELSY.Run().
Member Data Documentation
_dgeqrf
DGEQRF DotNumerics.LinearAlgebra.CSLapack.DGEQP3._dgeqrf private
_dlaqp2
DLAQP2 DotNumerics.LinearAlgebra.CSLapack.DGEQP3._dlaqp2 private
_dlaqps
DLAQPS DotNumerics.LinearAlgebra.CSLapack.DGEQP3._dlaqps private
_dormqr
DORMQR DotNumerics.LinearAlgebra.CSLapack.DGEQP3._dormqr private
_dswap
DSWAP DotNumerics.LinearAlgebra.CSLapack.DGEQP3._dswap private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGEQP3._xerbla private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DGEQP3._ilaenv private
_dnrm2
DNRM2 DotNumerics.LinearAlgebra.CSLapack.DGEQP3._dnrm2 private
INB
const int DotNumerics.LinearAlgebra.CSLapack.DGEQP3.INB = 1 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEQP3.Run().
INBMIN
const int DotNumerics.LinearAlgebra.CSLapack.DGEQP3.INBMIN = 2 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEQP3.Run().
IXOVER
const int DotNumerics.LinearAlgebra.CSLapack.DGEQP3.IXOVER = 3 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEQP3.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgeqp3.cs