Doc: IGLib EXTENDED: NUnit.Framework.Internal.Filters.TestFilterTests Class Reference
NUnit.Framework.Internal.Filters.TestFilterTests Class Reference
Classes
class AnotherFixture
class DummyFixture
class FixtureWithMultipleTests
class YetAnotherFixture
Public Member Functions
void SetUpSuite ()
Static Public Attributes
const string DUMMY_CLASS = "NUnit.Framework.Internal.Filters.TestFilterTests+DummyFixture"
Protected Attributes
readonly TestSuite _dummyFixture = TestBuilder.MakeFixture(typeof(DummyFixture))
readonly TestSuite _anotherFixture = TestBuilder.MakeFixture(typeof(AnotherFixture))
readonly TestSuite _yetAnotherFixture = TestBuilder.MakeFixture(typeof(YetAnotherFixture))
readonly TestSuite _fixtureWithMultipleTests = TestBuilder.MakeFixture (typeof (FixtureWithMultipleTests))
readonly TestSuite _topLevelSuite = new TestSuite("MySuite")
Member Function Documentation
SetUpSuite()
void NUnit.Framework.Internal.Filters.TestFilterTests.SetUpSuite () inline
References NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture, NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture, NUnit.Framework.Internal.Filters.TestFilterTests._fixtureWithMultipleTests, NUnit.Framework.Internal.Filters.TestFilterTests._topLevelSuite, NUnit.Framework.Internal.Filters.TestFilterTests._yetAnotherFixture, and NUnit.Framework.Internal.TestSuite.Add().
Member Data Documentation
DUMMY_CLASS
const string NUnit.Framework.Internal.Filters.TestFilterTests.DUMMY_CLASS = "NUnit.Framework.Internal.Filters.TestFilterTests+DummyFixture" static
Referenced by NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_FromXml(), and NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_FromXml().
_dummyFixture
readonly TestSuite NUnit.Framework.Internal.Filters.TestFilterTests._dummyFixture = TestBuilder.MakeFixture(typeof(DummyFixture)) protected
Referenced by NUnit.Framework.Internal.Filters.AndFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.OrFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.NotFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.AndFilterTests.BuildFromXml_TopLevelDefaultsToAnd(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.BuildMethodNameFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.IdFilterTests.CreateFilter(), NUnit.Framework.Internal.Filters.MethodNameFilterTests.ExplicitMatch_SingleName(), NUnit.Framework.Internal.Filters.AndFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.FullNameFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.CategoryFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.IdFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.TestNameFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.OrFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.PropertyFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.NotFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.IdFilter_FromXml(), NUnit.Framework.Internal.Filters.AndFilterTests.IsNotEmpty(), NUnit.Framework.Internal.Filters.EmptyFilterTests.MatchesAnything(), NUnit.Framework.Internal.Filters.EmptyFilterTests.MatchesNothihngExplicitly(), NUnit.Framework.Internal.Filters.AndFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.NotFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.OrFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.CategoryFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.PropertyFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.IdFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.FullNameFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.TestNameFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.MethodNameFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.MethodNameFilter_FromXml(), NUnit.Framework.Internal.Filters.EmptyFilterTests.PassesAnything(), NUnit.Framework.Internal.Filters.AndFilterTests.PassTest(), NUnit.Framework.Internal.Filters.OrFilterTests.PassTest(), NUnit.Framework.Internal.Filters.CategoryFilterTests.PassTest(), NUnit.Framework.Internal.Filters.IdFilterTests.PassTest(), NUnit.Framework.Internal.Filters.TestNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.FullNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.MethodNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.PropertyFilterTests.PassTest(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.NotFilterTests.PassTest(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterTests.SetUpSuite(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_FromXml(), and NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_FromXml_Regex().
_anotherFixture
readonly TestSuite NUnit.Framework.Internal.Filters.TestFilterTests._anotherFixture = TestBuilder.MakeFixture(typeof(AnotherFixture)) protected
Referenced by NUnit.Framework.Internal.Filters.AndFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.OrFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.NotFilterTests.BuildFromXml(), NUnit.Framework.Internal.Filters.AndFilterTests.BuildFromXml_TopLevelDefaultsToAnd(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.BuildMethodNameFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.CategoryFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.ClassNameFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.MethodNameFilterTests.ExplicitMatch_SingleName(), NUnit.Framework.Internal.Filters.AndFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.CategoryFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.FullNameFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.IdFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.TestNameFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.PropertyFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.OrFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.NotFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.FullNameFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.IdFilter_FromXml(), NUnit.Framework.Internal.Filters.EmptyFilterTests.MatchesAnything(), NUnit.Framework.Internal.Filters.EmptyFilterTests.MatchesNothihngExplicitly(), NUnit.Framework.Internal.Filters.NotFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.AndFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.OrFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.PropertyFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.IdFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.CategoryFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.FullNameFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.MethodNameFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.TestNameFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.MethodNameFilter_FromXml(), NUnit.Framework.Internal.Filters.EmptyFilterTests.PassesAnything(), NUnit.Framework.Internal.Filters.AndFilterTests.PassTest(), NUnit.Framework.Internal.Filters.OrFilterTests.PassTest(), NUnit.Framework.Internal.Filters.CategoryFilterTests.PassTest(), NUnit.Framework.Internal.Filters.IdFilterTests.PassTest(), NUnit.Framework.Internal.Filters.MethodNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.TestNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.FullNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.PropertyFilterTests.PassTest(), NUnit.Framework.Internal.Filters.NotFilterTests.PassTest(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.TestFilterTests.SetUpSuite(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_FromXml(), and NUnit.Framework.Internal.Filters.TestFilterXmlTests.TestNameFilter_FromXml_Regex().
_yetAnotherFixture
readonly TestSuite NUnit.Framework.Internal.Filters.TestFilterTests._yetAnotherFixture = TestBuilder.MakeFixture(typeof(YetAnotherFixture)) protected
Referenced by NUnit.Framework.Internal.Filters.OrFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.PropertyFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.EmptyFilterTests.MatchesAnything(), NUnit.Framework.Internal.Filters.EmptyFilterTests.MatchesNothihngExplicitly(), NUnit.Framework.Internal.Filters.OrFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.PropertyFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.EmptyFilterTests.PassesAnything(), NUnit.Framework.Internal.Filters.OrFilterTests.PassTest(), NUnit.Framework.Internal.Filters.MethodNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.PropertyFilterTests.PassTest(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_FromXml(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.PropertyFilter_FromXml_Regex(), and NUnit.Framework.Internal.Filters.TestFilterTests.SetUpSuite().
_fixtureWithMultipleTests
readonly TestSuite NUnit.Framework.Internal.Filters.TestFilterTests._fixtureWithMultipleTests = TestBuilder.MakeFixture (typeof (FixtureWithMultipleTests)) protected
Referenced by NUnit.Framework.Internal.Filters.TestFilterXmlTests.BuildMethodNameFilter_FromXml_Regex(), NUnit.Framework.Internal.Filters.NotFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.TestFilterXmlTests.MethodNameFilter_FromXml(), NUnit.Framework.Internal.Filters.NotFilterTests.PassTest(), and NUnit.Framework.Internal.Filters.TestFilterTests.SetUpSuite().
_topLevelSuite
readonly TestSuite NUnit.Framework.Internal.Filters.TestFilterTests._topLevelSuite = new TestSuite("MySuite") protected
Referenced by NUnit.Framework.Internal.Filters.MethodNameFilterTests.ExplicitMatch_SingleName(), NUnit.Framework.Internal.Filters.AndFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.CategoryFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.FullNameFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.IdFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.TestNameFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.OrFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.PropertyFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.NotFilterTests.ExplicitMatchTest(), NUnit.Framework.Internal.Filters.NotFilterTests.MatchTest(), NUnit.Framework.Internal.Filters.AndFilterTests.PassTest(), NUnit.Framework.Internal.Filters.OrFilterTests.PassTest(), NUnit.Framework.Internal.Filters.IdFilterTests.PassTest(), NUnit.Framework.Internal.Filters.CategoryFilterTests.PassTest(), NUnit.Framework.Internal.Filters.FullNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.ClassNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.TestNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.PropertyFilterTests.PassTest(), NUnit.Framework.Internal.Filters.MethodNameFilterTests.PassTest(), NUnit.Framework.Internal.Filters.NotFilterTests.PassTest(), and NUnit.Framework.Internal.Filters.TestFilterTests.SetUpSuite().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/Filters/TestFilterTests.cs