Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGGSVD Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGGSVD Class Reference
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGGSVD (LSAME lsame, DLAMCH dlamch, DLANGE dlange, DCOPY dcopy, DGGSVP dggsvp, DTGSJA dtgsja, XERBLA xerbla)
DGGSVD ()
void Run (string JOBU, string JOBV, string JOBQ, int M, int N, int P, ref int K, ref int L, ref double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB, ref double[] ALPHA, int offset_alpha, ref double[] BETA, int offset_beta, ref double[] U, int offset_u, int LDU, ref double[] V, int offset_v, int LDV, ref double[] Q, int offset_q, int LDQ, ref double[] WORK, int offset_work, ref int[] IWORK, int offset_iwork, ref int INFO)
Private Attributes
LSAME _lsame
DLAMCH _dlamch
DLANGE _dlange
DCOPY _dcopy
DGGSVP _dggsvp
DTGSJA _dtgsja
XERBLA _xerbla
Detailed Description
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGGSVD computes the generalized singular value decomposition (GSVD) of an M-by-N real matrix A and P-by-N real matrix B:
U'A*Q = D1(0 R), V'B*Q = D2(0 R)
where U, V and Q are orthogonal matrices, and Z' is the transpose of Z. Let K+L = the effective numerical rank of the matrix (A',B')', then R is a K+L-by-K+L nonsingular upper triangular matrix, D1 and D2 are M-by-(K+L) and P-by-(K+L) "diagonal" matrices and of the following structures, respectively:
If M-K-L .GE. 0,
K L D1 = K (I 0) L (0 C) M-K-L (0 0)
K L D2 = L (0 S) P-L (0 0)
N-K-L K L (0 R) = K (0 R11 R12) L (0 0 R22)
where
C = diag(ALPHA(K+1), ... , ALPHA(K+L)), S = diag(BETA(K+1), ... , BETA(K+L)), C**2 + S**2 = I.
R is stored in A(1:K+L,N-K-L+1:N) on exit.
If M-K-L .LT. 0,
K M-K K+L-M D1 = K (I 0 0) M-K (0 C 0)
K M-K K+L-M D2 = M-K (0 S 0) K+L-M (0 0 I) P-L (0 0 0)
N-K-L K M-K K+L-M (0 R) = K (0 R11 R12 R13) M-K (0 0 R22 R23) K+L-M (0 0 0 R33)
where
C = diag(ALPHA(K+1), ... , ALPHA(M)), S = diag(BETA(K+1), ... , BETA(M)), C**2 + S**2 = I.
(R11 R12 R13) is stored in A(1:M, N-K-L+1:N), and R33 is stored (0 R22 R23) in B(M-K+1:L,N+M-K-L+1:N) on exit.
The routine computes C, S, R, and optionally the orthogonal transformation matrices U, V and Q.
In particular, if B is an N-by-N nonsingular matrix, then the GSVD of A and B implicitly gives the SVD of A*inv(B): A*inv(B) = U*(D1*inv(D2))*V'. If (A',B')' has orthonormal columns, then the GSVD of A and B is also equal to the CS decomposition of A and B. Furthermore, the GSVD can be used to derive the solution of the eigenvalue problem: A'A x = lambda B'*B x. In some literature, the GSVD of A and B is presented in the form U'*A*X = (0 D1), V'*B*X = (0 D2) where U and V are orthogonal and X is nonsingular, D1 and D2 are `‘diagonal’'. The former GSVD form can be converted to the latter form by taking the nonsingular matrix X as
X = Q*(I 0) (0 inv(R)).
/summary>
Constructor & Destructor Documentation
DGGSVD() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGGSVD.DGGSVD (LSAME lsame, DLAMCH dlamch, DLANGE dlange, DCOPY dcopy, DGGSVP dggsvp, DTGSJA dtgsja, XERBLA xerbla) inline
DGGSVD() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGGSVD.DGGSVD () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGGSVD.Run (string JOBU, string JOBV, string JOBQ, int M, int N, int P, ref int K, ref int L, ref double[] A, int offset_a, int LDA, ref double[] B, int offset_b, int LDB, ref double[] ALPHA, int offset_alpha, ref double[] BETA, int offset_beta, ref double[] U, int offset_u, int LDU, ref double[] V, int offset_v, int LDV, ref double[] Q, int offset_q, int LDQ, ref double[] WORK, int offset_work, ref int[] IWORK, int offset_iwork, ref int INFO) inline
Purpose
DGGSVD computes the generalized singular value decomposition (GSVD) of an M-by-N real matrix A and P-by-N real matrix B:
U'A*Q = D1(0 R), V'B*Q = D2(0 R)
where U, V and Q are orthogonal matrices, and Z' is the transpose of Z. Let K+L = the effective numerical rank of the matrix (A',B')', then R is a K+L-by-K+L nonsingular upper triangular matrix, D1 and D2 are M-by-(K+L) and P-by-(K+L) "diagonal" matrices and of the following structures, respectively:
If M-K-L .GE. 0,
K L D1 = K (I 0) L (0 C) M-K-L (0 0)
K L D2 = L (0 S) P-L (0 0)
N-K-L K L (0 R) = K (0 R11 R12) L (0 0 R22)
where
C = diag(ALPHA(K+1), ... , ALPHA(K+L)), S = diag(BETA(K+1), ... , BETA(K+L)), C**2 + S**2 = I.
R is stored in A(1:K+L,N-K-L+1:N) on exit.
If M-K-L .LT. 0,
K M-K K+L-M D1 = K (I 0 0) M-K (0 C 0)
K M-K K+L-M D2 = M-K (0 S 0) K+L-M (0 0 I) P-L (0 0 0)
N-K-L K M-K K+L-M (0 R) = K (0 R11 R12 R13) M-K (0 0 R22 R23) K+L-M (0 0 0 R33)
where
C = diag(ALPHA(K+1), ... , ALPHA(M)), S = diag(BETA(K+1), ... , BETA(M)), C**2 + S**2 = I.
(R11 R12 R13) is stored in A(1:M, N-K-L+1:N), and R33 is stored (0 R22 R23) in B(M-K+1:L,N+M-K-L+1:N) on exit.
The routine computes C, S, R, and optionally the orthogonal transformation matrices U, V and Q.
In particular, if B is an N-by-N nonsingular matrix, then the GSVD of A and B implicitly gives the SVD of A*inv(B): A*inv(B) = U*(D1*inv(D2))*V'. If (A',B')' has orthonormal columns, then the GSVD of A and B is also equal to the CS decomposition of A and B. Furthermore, the GSVD can be used to derive the solution of the eigenvalue problem: A'A x = lambda B'*B x. In some literature, the GSVD of A and B is presented in the form U'*A*X = (0 D1), V'*B*X = (0 D2) where U and V are orthogonal and X is nonsingular, D1 and D2 are `‘diagonal’'. The former GSVD form can be converted to the latter form by taking the nonsingular matrix X as
X = Q*(I 0) (0 inv(R)).
/summary>
Parameters
JOBU (input) CHARACTER*1 = 'U': Orthogonal matrix U is computed; = 'N': U is not computed. /param>
Parameters
JOBV (input) CHARACTER*1 = 'V': Orthogonal matrix V is computed; = 'N': V is not computed. /param>
Parameters
JOBQ (input) CHARACTER*1 = 'Q': Orthogonal matrix Q is computed; = 'N': Q is not computed. /param>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrices A and B. N .GE. 0. /param>
Parameters
P (input) INTEGER The number of rows of the matrix B. P .GE. 0. /param>
Parameters
K L /param>
Parameters
L (0 C) /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the M-by-N matrix A. On exit, A contains the triangular matrix R, or part of R. See Purpose for details. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
B (input/output) DOUBLE PRECISION array, dimension (LDB,N) On entry, the P-by-N matrix B. On exit, B contains the triangular matrix R if M-K-L .LT. 0. See Purpose for details. /param>
Parameters
LDB (input) INTEGER The leading dimension of the array B. LDB .GE. max(1,P). /param>
Parameters
ALPHA (output) DOUBLE PRECISION array, dimension (N) /param>
Parameters
BETA (output) DOUBLE PRECISION array, dimension (N) On exit, ALPHA and BETA contain the generalized singular value pairs of A and B; ALPHA(1:K) = 1, BETA(1:K) = 0, and if M-K-L .GE. 0, ALPHA(K+1:K+L) = C, BETA(K+1:K+L) = S, or if M-K-L .LT. 0, ALPHA(K+1:M)=C, ALPHA(M+1:K+L)=0 BETA(K+1:M) =S, BETA(M+1:K+L) =1 and ALPHA(K+L+1:N) = 0 BETA(K+L+1:N) = 0 /param>
Parameters
U (output) DOUBLE PRECISION array, dimension (LDU,M) If JOBU = 'U', U contains the M-by-M orthogonal matrix U. If JOBU = 'N', U is not referenced. /param>
Parameters
LDU (input) INTEGER The leading dimension of the array U. LDU .GE. max(1,M) if JOBU = 'U'; LDU .GE. 1 otherwise. /param>
Parameters
V (output) DOUBLE PRECISION array, dimension (LDV,P) If JOBV = 'V', V contains the P-by-P orthogonal matrix V. If JOBV = 'N', V is not referenced. /param>
Parameters
LDV (input) INTEGER The leading dimension of the array V. LDV .GE. max(1,P) if JOBV = 'V'; LDV .GE. 1 otherwise. /param>
Parameters
Q (output) DOUBLE PRECISION array, dimension (LDQ,N) If JOBQ = 'Q', Q contains the N-by-N orthogonal matrix Q. If JOBQ = 'N', Q is not referenced. /param>
Parameters
LDQ (input) INTEGER The leading dimension of the array Q. LDQ .GE. max(1,N) if JOBQ = 'Q'; LDQ .GE. 1 otherwise. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (max(3*N,M,P)+N) /param>
Parameters
IWORK (workspace/output) INTEGER array, dimension (N) On exit, IWORK stores the sorting information. More precisely, the following loop will sort ALPHA for I = K+1, min(M,K+L) swap ALPHA(I) and ALPHA(IWORK(I)) endfor such that ALPHA(1) .GE. ALPHA(2) .GE. ... .GE. ALPHA(N). /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value. .GT. 0: if INFO = 1, the Jacobi-type procedure failed to converge. For further details, see subroutine DTGSJA. /param>
References DotNumerics.LinearAlgebra.CSLapack.DCOPY.Run(), DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANGE.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGSVP.Run(), and DotNumerics.LinearAlgebra.CSLapack.DTGSJA.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DGGSVD._lsame private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DGGSVD._dlamch private
_dlange
DLANGE DotNumerics.LinearAlgebra.CSLapack.DGGSVD._dlange private
_dcopy
DCOPY DotNumerics.LinearAlgebra.CSLapack.DGGSVD._dcopy private
_dggsvp
DGGSVP DotNumerics.LinearAlgebra.CSLapack.DGGSVD._dggsvp private
_dtgsja
DTGSJA DotNumerics.LinearAlgebra.CSLapack.DGGSVD._dtgsja private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGGSVD._xerbla private
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dggsvd.cs