Doc: IGLib EXTENDED: MotionDetectorSample.MainForm Class Reference
MotionDetectorSample.MainForm Class Reference
Public Member Functions
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void MainForm_FormClosing (object sender, FormClosingEventArgs e)
void exitToolStripMenuItem_Click (object sender, EventArgs e)
void aboutToolStripMenuItem_Click (object sender, EventArgs e)
void openToolStripMenuItem_Click (object sender, EventArgs e)
void openJPEGURLToolStripMenuItem_Click (object sender, EventArgs e)
void openMJPEGURLToolStripMenuItem_Click (object sender, EventArgs e)
void localVideoCaptureDeviceToolStripMenuItem_Click (object sender, EventArgs e)
void openVideoFileusingDirectShowToolStripMenuItem_Click (object sender, EventArgs e)
void OpenVideoSource (IVideoSource source)
void CloseVideoSource ()
void videoSourcePlayer_NewFrame (object sender, ref Bitmap image)
void Application_Idle (object sender, EventArgs e)
void DrawMotionHistory (Bitmap image)
void timer_Tick (object sender, EventArgs e)
void noneToolStripMenuItem1_Click (object sender, EventArgs e)
void twoFramesDifferenceToolStripMenuItem_Click (object sender, EventArgs e)
void simpleBackgroundModelingToolStripMenuItem_Click (object sender, EventArgs e)
void noneToolStripMenuItem2_Click (object sender, EventArgs e)
void motionAreaHighlightingToolStripMenuItem_Click (object sender, EventArgs e)
void motionBorderHighlightingToolStripMenuItem_Click (object sender, EventArgs e)
void blobCountingToolStripMenuItem_Click (object sender, EventArgs e)
void gridMotionAreaProcessingToolStripMenuItem_Click (object sender, EventArgs e)
void SetMotionDetectionAlgorithm (IMotionDetector detectionAlgorithm)
void SetMotionProcessingAlgorithm (IMotionProcessing processingAlgorithm)
void motionToolStripMenuItem_DropDownOpening (object sender, EventArgs e)
void defineMotionregionsToolStripMenuItem_Click (object sender, EventArgs e)
void toolsToolStripMenuItem_DropDownOpening (object sender, EventArgs e)
void localVideoCaptureSettingsToolStripMenuItem_Click (object sender, EventArgs e)
void crossbarVideoSettingsToolStripMenuItem_Click (object sender, EventArgs e)
void alarmTimer_Tick (object sender, EventArgs e)
void showMotionHistoryToolStripMenuItem_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
IVideoSource videoSource = null
MotionDetector detector
int motionDetectionType = 1
int motionProcessingType = 1
int statIndex = 0
int statReady = 0
int[] statCount = new int[statLength]
int flash = 0
float motionAlarmLevel = 0.015f
List< float > motionHistory = new List<float>()
int detectedObjectsCount = -1
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.MenuStrip menuMenu
System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem openToolStripMenuItem
System.Windows.Forms.ToolStripSeparator toolStripMenuItem1
System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem motionToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem
System.Windows.Forms.OpenFileDialog openFileDialog
System.Windows.Forms.Timer timer
System.Windows.Forms.StatusStrip statusBar
System.Windows.Forms.ToolStripStatusLabel fpsLabel
System.Windows.Forms.Panel panel1
System.Windows.Forms.ToolStripMenuItem openJPEGURLToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem openMJPEGURLToolStripMenuItem
System.Windows.Forms.ToolStripSeparator toolStripMenuItem2
System.Windows.Forms.ToolStripMenuItem localVideoCaptureDeviceToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem openVideoFileusingDirectShowToolStripMenuItem
System.Windows.Forms.ToolStripStatusLabel objectsCountLabel
System.Windows.Forms.ToolStripMenuItem defineMotionregionsToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem toolsToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem localVideoCaptureSettingsToolStripMenuItem
AForge.Controls.VideoSourcePlayer videoSourcePlayer
System.Windows.Forms.ToolStripMenuItem motionDetectionAlgorithmToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem noneToolStripMenuItem1
System.Windows.Forms.ToolStripMenuItem twoFramesDifferenceToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem simpleBackgroundModelingToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem motionProcessingAlgorithmToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem noneToolStripMenuItem2
System.Windows.Forms.ToolStripMenuItem motionBorderHighlightingToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem blobCountingToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem gridMotionAreaProcessingToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem motionAreaHighlightingToolStripMenuItem
System.Windows.Forms.Timer alarmTimer
System.Windows.Forms.ToolStripSeparator toolStripMenuItem3
System.Windows.Forms.ToolStripMenuItem showMotionHistoryToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem crossbarVideoSettingsToolStripMenuItem
Static Private Attributes
const int statLength = 15
Constructor & Destructor Documentation
MainForm()
MotionDetectorSample.MainForm.MainForm () inline
References MotionDetectorSample.MainForm.Application_Idle(), and MotionDetectorSample.MainForm.InitializeComponent().
Member Function Documentation
MainForm_FormClosing()
void MotionDetectorSample.MainForm.MainForm_FormClosing (object sender, FormClosingEventArgs e) inline private
References MotionDetectorSample.MainForm.CloseVideoSource().
exitToolStripMenuItem_Click()
void MotionDetectorSample.MainForm.exitToolStripMenuItem_Click (object sender, EventArgs e) inline private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
aboutToolStripMenuItem_Click()
void MotionDetectorSample.MainForm.aboutToolStripMenuItem_Click (object sender, EventArgs e) inline private
openToolStripMenuItem_Click()
void MotionDetectorSample.MainForm.openToolStripMenuItem_Click (object sender, EventArgs e) inline private
References MotionDetectorSample.MainForm.openFileDialog, and MotionDetectorSample.MainForm.OpenVideoSource().
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
openJPEGURLToolStripMenuItem_Click()
void MotionDetectorSample.MainForm.openJPEGURLToolStripMenuItem_Click (object sender, EventArgs e) inline private
References MotionDetectorSample.URLForm.Description, MotionDetectorSample.MainForm.OpenVideoSource(), MotionDetectorSample.URLForm.URL, and MotionDetectorSample.URLForm.URLs.
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
openMJPEGURLToolStripMenuItem_Click()
void MotionDetectorSample.MainForm.openMJPEGURLToolStripMenuItem_Click (object sender, EventArgs e) inline private
References MotionDetectorSample.URLForm.Description, MotionDetectorSample.MainForm.OpenVideoSource(), MotionDetectorSample.URLForm.URL, and MotionDetectorSample.URLForm.URLs.
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
localVideoCaptureDeviceToolStripMenuItem_Click()
void MotionDetectorSample.MainForm.localVideoCaptureDeviceToolStripMenuItem_Click (object sender, EventArgs e) inline private
References MotionDetectorSample.MainForm.OpenVideoSource(), MotionDetectorSample.VideoCaptureDeviceForm.VideoDevice, and MotionDetectorSample.MainForm.videoSource.
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
openVideoFileusingDirectShowToolStripMenuItem_Click()
void MotionDetectorSample.MainForm.openVideoFileusingDirectShowToolStripMenuItem_Click (object sender, EventArgs e) inline private
References MotionDetectorSample.MainForm.openFileDialog, and MotionDetectorSample.MainForm.OpenVideoSource().
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
OpenVideoSource()
void MotionDetectorSample.MainForm.OpenVideoSource (IVideoSource source) inline private
References MotionDetectorSample.MainForm.alarmTimer, MotionDetectorSample.MainForm.CloseVideoSource(), MotionDetectorSample.MainForm.statIndex, MotionDetectorSample.MainForm.statReady, MotionDetectorSample.MainForm.timer, MotionDetectorSample.MainForm.videoSource, and MotionDetectorSample.MainForm.videoSourcePlayer.
Referenced by MotionDetectorSample.MainForm.localVideoCaptureDeviceToolStripMenuItem_Click(), MotionDetectorSample.MainForm.openJPEGURLToolStripMenuItem_Click(), MotionDetectorSample.MainForm.openMJPEGURLToolStripMenuItem_Click(), MotionDetectorSample.MainForm.openToolStripMenuItem_Click(), and MotionDetectorSample.MainForm.openVideoFileusingDirectShowToolStripMenuItem_Click().
CloseVideoSource()
void MotionDetectorSample.MainForm.CloseVideoSource () inline private
References MotionDetectorSample.MainForm.alarmTimer, MotionDetectorSample.MainForm.detector, MotionDetectorSample.MainForm.motionHistory, AForge.Vision.Motion.MotionDetector.Reset(), MotionDetectorSample.MainForm.timer, and MotionDetectorSample.MainForm.videoSourcePlayer.
Referenced by MotionDetectorSample.MainForm.MainForm_FormClosing(), and MotionDetectorSample.MainForm.OpenVideoSource().
videoSourcePlayer_NewFrame()
void MotionDetectorSample.MainForm.videoSourcePlayer_NewFrame (object sender, ref Bitmap image) inline private
References MotionDetectorSample.MainForm.alarmTimer, MotionDetectorSample.MainForm.detectedObjectsCount, MotionDetectorSample.MainForm.detector, MotionDetectorSample.MainForm.DrawMotionHistory(), MotionDetectorSample.MainForm.flash, MotionDetectorSample.MainForm.motionAlarmLevel, MotionDetectorSample.MainForm.motionHistory, AForge.Vision.Motion.MotionDetector.MotionProcessingAlgorithm, AForge.Vision.Motion.BlobCountingObjectsProcessing.ObjectsCount, AForge.Vision.Motion.MotionDetector.ProcessFrame(), and MotionDetectorSample.MainForm.showMotionHistoryToolStripMenuItem.
Application_Idle()
void MotionDetectorSample.MainForm.Application_Idle (object sender, EventArgs e) inline private
References MotionDetectorSample.MainForm.detectedObjectsCount, and MotionDetectorSample.MainForm.objectsCountLabel.
Referenced by MotionDetectorSample.MainForm.MainForm().
DrawMotionHistory()
void MotionDetectorSample.MainForm.DrawMotionHistory (Bitmap image) inline private
References AForge.Imaging.Drawing.Line(), MotionDetectorSample.MainForm.motionAlarmLevel, MotionDetectorSample.MainForm.motionHistory, and AForge.Math.Geometry.Rectangle.
Referenced by MotionDetectorSample.MainForm.videoSourcePlayer_NewFrame().
timer_Tick()
void MotionDetectorSample.MainForm.timer_Tick (object sender, EventArgs e) inline private
References MotionDetectorSample.MainForm.fpsLabel, AForge.Video.IVideoSource.FramesReceived, MotionDetectorSample.MainForm.statCount, MotionDetectorSample.MainForm.statIndex, MotionDetectorSample.MainForm.statLength, MotionDetectorSample.MainForm.statReady, MotionDetectorSample.MainForm.videoSource, and MotionDetectorSample.MainForm.videoSourcePlayer.
noneToolStripMenuItem1_Click()
void MotionDetectorSample.MainForm.noneToolStripMenuItem1_Click (object sender, EventArgs e) inline private
References MotionDetectorSample.MainForm.motionDetectionType, and MotionDetectorSample.MainForm.SetMotionDetectionAlgorithm().
twoFramesDifferenceToolStripMenuItem_Click()
void MotionDetectorSample.MainForm.twoFramesDifferenceToolStripMenuItem_Click (object sender, EventArgs e) inline private
References MotionDetectorSample.MainForm.motionDetectionType, and MotionDetectorSample.MainForm.SetMotionDetectionAlgorithm().
simpleBackgroundModelingToolStripMenuItem_Click()
void MotionDetectorSample.MainForm.simpleBackgroundModelingToolStripMenuItem_Click (object sender, EventArgs e) inline private
References MotionDetectorSample.MainForm.motionDetectionType, and MotionDetectorSample.MainForm.SetMotionDetectionAlgorithm().
noneToolStripMenuItem2_Click()
void MotionDetectorSample.MainForm.noneToolStripMenuItem2_Click (object sender, EventArgs e) inline private
References MotionDetectorSample.MainForm.motionProcessingType, and MotionDetectorSample.MainForm.SetMotionProcessingAlgorithm().
motionAreaHighlightingToolStripMenuItem_Click()
void MotionDetectorSample.MainForm.motionAreaHighlightingToolStripMenuItem_Click (object sender, EventArgs e) inline private
References MotionDetectorSample.MainForm.motionProcessingType, and MotionDetectorSample.MainForm.SetMotionProcessingAlgorithm().
motionBorderHighlightingToolStripMenuItem_Click()
void MotionDetectorSample.MainForm.motionBorderHighlightingToolStripMenuItem_Click (object sender, EventArgs e) inline private
References MotionDetectorSample.MainForm.motionProcessingType, and MotionDetectorSample.MainForm.SetMotionProcessingAlgorithm().
blobCountingToolStripMenuItem_Click()
void MotionDetectorSample.MainForm.blobCountingToolStripMenuItem_Click (object sender, EventArgs e) inline private
References MotionDetectorSample.MainForm.motionProcessingType, and MotionDetectorSample.MainForm.SetMotionProcessingAlgorithm().
gridMotionAreaProcessingToolStripMenuItem_Click()
void MotionDetectorSample.MainForm.gridMotionAreaProcessingToolStripMenuItem_Click (object sender, EventArgs e) inline private
References MotionDetectorSample.MainForm.motionProcessingType, and MotionDetectorSample.MainForm.SetMotionProcessingAlgorithm().
SetMotionDetectionAlgorithm()
void MotionDetectorSample.MainForm.SetMotionDetectionAlgorithm (IMotionDetector detectionAlgorithm) inline private
References MotionDetectorSample.MainForm.detector, AForge.Vision.Motion.MotionDetector.MotionDetectionAlgorithm, MotionDetectorSample.MainForm.motionHistory, AForge.Vision.Motion.MotionDetector.MotionProcessingAlgorithm, MotionDetectorSample.MainForm.motionProcessingType, and MotionDetectorSample.MainForm.SetMotionProcessingAlgorithm().
Referenced by MotionDetectorSample.MainForm.noneToolStripMenuItem1_Click(), MotionDetectorSample.MainForm.simpleBackgroundModelingToolStripMenuItem_Click(), and MotionDetectorSample.MainForm.twoFramesDifferenceToolStripMenuItem_Click().
SetMotionProcessingAlgorithm()
void MotionDetectorSample.MainForm.SetMotionProcessingAlgorithm (IMotionProcessing processingAlgorithm) inline private
References MotionDetectorSample.MainForm.detector, and AForge.Vision.Motion.MotionDetector.MotionProcessingAlgorithm.
Referenced by MotionDetectorSample.MainForm.blobCountingToolStripMenuItem_Click(), MotionDetectorSample.MainForm.gridMotionAreaProcessingToolStripMenuItem_Click(), MotionDetectorSample.MainForm.motionAreaHighlightingToolStripMenuItem_Click(), MotionDetectorSample.MainForm.motionBorderHighlightingToolStripMenuItem_Click(), MotionDetectorSample.MainForm.noneToolStripMenuItem2_Click(), and MotionDetectorSample.MainForm.SetMotionDetectionAlgorithm().
motionToolStripMenuItem_DropDownOpening()
void MotionDetectorSample.MainForm.motionToolStripMenuItem_DropDownOpening (object sender, EventArgs e) inline private
References MotionDetectorSample.MainForm.blobCountingToolStripMenuItem, MotionDetectorSample.MainForm.gridMotionAreaProcessingToolStripMenuItem, MotionDetectorSample.MainForm.motionAreaHighlightingToolStripMenuItem, MotionDetectorSample.MainForm.motionBorderHighlightingToolStripMenuItem, MotionDetectorSample.MainForm.motionDetectionType, MotionDetectorSample.MainForm.motionProcessingType, MotionDetectorSample.MainForm.noneToolStripMenuItem1, MotionDetectorSample.MainForm.noneToolStripMenuItem2, MotionDetectorSample.MainForm.simpleBackgroundModelingToolStripMenuItem, and MotionDetectorSample.MainForm.twoFramesDifferenceToolStripMenuItem.
defineMotionregionsToolStripMenuItem_Click()
void MotionDetectorSample.MainForm.defineMotionregionsToolStripMenuItem_Click (object sender, EventArgs e) inline private
References MotionDetectorSample.MainForm.detector, MotionDetectorSample.MotionRegionsForm.MotionRectangles, AForge.Vision.Motion.MotionDetector.MotionZones, AForge.Math.Geometry.Rectangle, MotionDetectorSample.MotionRegionsForm.VideoFrame, and MotionDetectorSample.MainForm.videoSourcePlayer.
toolsToolStripMenuItem_DropDownOpening()
void MotionDetectorSample.MainForm.toolsToolStripMenuItem_DropDownOpening (object sender, EventArgs e) inline private
References MotionDetectorSample.MainForm.crossbarVideoSettingsToolStripMenuItem, AForge.Video.IVideoSource.IsRunning, MotionDetectorSample.MainForm.localVideoCaptureSettingsToolStripMenuItem, and MotionDetectorSample.MainForm.videoSource.
localVideoCaptureSettingsToolStripMenuItem_Click()
void MotionDetectorSample.MainForm.localVideoCaptureSettingsToolStripMenuItem_Click (object sender, EventArgs e) inline private
References MotionDetectorSample.MainForm.videoSource.
crossbarVideoSettingsToolStripMenuItem_Click()
void MotionDetectorSample.MainForm.crossbarVideoSettingsToolStripMenuItem_Click (object sender, EventArgs e) inline private
References AForge.Video.IVideoSource.IsRunning, and MotionDetectorSample.MainForm.videoSource.
alarmTimer_Tick()
void MotionDetectorSample.MainForm.alarmTimer_Tick (object sender, EventArgs e) inline private
References MotionDetectorSample.MainForm.flash, and MotionDetectorSample.MainForm.videoSourcePlayer.
showMotionHistoryToolStripMenuItem_Click()
void MotionDetectorSample.MainForm.showMotionHistoryToolStripMenuItem_Click (object sender, EventArgs e) inline private
References MotionDetectorSample.MainForm.showMotionHistoryToolStripMenuItem.
Dispose()
override void MotionDetectorSample.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References MotionDetectorSample.MainForm.components.
InitializeComponent()
void MotionDetectorSample.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References MotionDetectorSample.MainForm.aboutToolStripMenuItem, MotionDetectorSample.MainForm.alarmTimer, MotionDetectorSample.MainForm.blobCountingToolStripMenuItem, MotionDetectorSample.MainForm.components, MotionDetectorSample.MainForm.crossbarVideoSettingsToolStripMenuItem, MotionDetectorSample.MainForm.defineMotionregionsToolStripMenuItem, MotionDetectorSample.MainForm.exitToolStripMenuItem, MotionDetectorSample.MainForm.exitToolStripMenuItem_Click(), MotionDetectorSample.MainForm.fileToolStripMenuItem, MotionDetectorSample.MainForm.fpsLabel, MotionDetectorSample.MainForm.gridMotionAreaProcessingToolStripMenuItem, MotionDetectorSample.MainForm.helpToolStripMenuItem, MotionDetectorSample.MainForm.localVideoCaptureDeviceToolStripMenuItem, MotionDetectorSample.MainForm.localVideoCaptureDeviceToolStripMenuItem_Click(), MotionDetectorSample.MainForm.localVideoCaptureSettingsToolStripMenuItem, MotionDetectorSample.MainForm.menuMenu, MotionDetectorSample.MainForm.motionAreaHighlightingToolStripMenuItem, MotionDetectorSample.MainForm.motionBorderHighlightingToolStripMenuItem, MotionDetectorSample.MainForm.motionDetectionAlgorithmToolStripMenuItem, MotionDetectorSample.MainForm.motionProcessingAlgorithmToolStripMenuItem, MotionDetectorSample.MainForm.motionToolStripMenuItem, MotionDetectorSample.MainForm.noneToolStripMenuItem1, MotionDetectorSample.MainForm.noneToolStripMenuItem2, MotionDetectorSample.MainForm.objectsCountLabel, MotionDetectorSample.MainForm.openFileDialog, MotionDetectorSample.MainForm.openJPEGURLToolStripMenuItem, MotionDetectorSample.MainForm.openJPEGURLToolStripMenuItem_Click(), MotionDetectorSample.MainForm.openMJPEGURLToolStripMenuItem, MotionDetectorSample.MainForm.openMJPEGURLToolStripMenuItem_Click(), MotionDetectorSample.MainForm.openToolStripMenuItem, MotionDetectorSample.MainForm.openToolStripMenuItem_Click(), MotionDetectorSample.MainForm.openVideoFileusingDirectShowToolStripMenuItem, MotionDetectorSample.MainForm.openVideoFileusingDirectShowToolStripMenuItem_Click(), MotionDetectorSample.MainForm.panel1, MotionDetectorSample.MainForm.showMotionHistoryToolStripMenuItem, MotionDetectorSample.MainForm.simpleBackgroundModelingToolStripMenuItem, MotionDetectorSample.MainForm.statusBar, MotionDetectorSample.MainForm.timer, MotionDetectorSample.MainForm.toolsToolStripMenuItem, MotionDetectorSample.MainForm.toolStripMenuItem1, MotionDetectorSample.MainForm.toolStripMenuItem2, MotionDetectorSample.MainForm.toolStripMenuItem3, MotionDetectorSample.MainForm.twoFramesDifferenceToolStripMenuItem, and MotionDetectorSample.MainForm.videoSourcePlayer.
Referenced by MotionDetectorSample.MainForm.MainForm().
Member Data Documentation
videoSource
IVideoSource MotionDetectorSample.MainForm.videoSource = null private
Referenced by MotionDetectorSample.MainForm.crossbarVideoSettingsToolStripMenuItem_Click(), MotionDetectorSample.MainForm.localVideoCaptureDeviceToolStripMenuItem_Click(), MotionDetectorSample.MainForm.localVideoCaptureSettingsToolStripMenuItem_Click(), MotionDetectorSample.MainForm.OpenVideoSource(), MotionDetectorSample.MainForm.timer_Tick(), and MotionDetectorSample.MainForm.toolsToolStripMenuItem_DropDownOpening().
detector
MotionDetector MotionDetectorSample.MainForm.detector private
Initial value:
= new MotionDetector(
            new TwoFramesDifferenceDetector( ),
            new MotionAreaHighlighting( ) )
Referenced by MotionDetectorSample.MainForm.CloseVideoSource(), MotionDetectorSample.MainForm.defineMotionregionsToolStripMenuItem_Click(), MotionDetectorSample.MainForm.SetMotionDetectionAlgorithm(), MotionDetectorSample.MainForm.SetMotionProcessingAlgorithm(), and MotionDetectorSample.MainForm.videoSourcePlayer_NewFrame().
motionDetectionType
int MotionDetectorSample.MainForm.motionDetectionType = 1 private
Referenced by MotionDetectorSample.MainForm.motionToolStripMenuItem_DropDownOpening(), MotionDetectorSample.MainForm.noneToolStripMenuItem1_Click(), MotionDetectorSample.MainForm.simpleBackgroundModelingToolStripMenuItem_Click(), and MotionDetectorSample.MainForm.twoFramesDifferenceToolStripMenuItem_Click().
motionProcessingType
int MotionDetectorSample.MainForm.motionProcessingType = 1 private
Referenced by MotionDetectorSample.MainForm.blobCountingToolStripMenuItem_Click(), MotionDetectorSample.MainForm.gridMotionAreaProcessingToolStripMenuItem_Click(), MotionDetectorSample.MainForm.motionAreaHighlightingToolStripMenuItem_Click(), MotionDetectorSample.MainForm.motionBorderHighlightingToolStripMenuItem_Click(), MotionDetectorSample.MainForm.motionToolStripMenuItem_DropDownOpening(), MotionDetectorSample.MainForm.noneToolStripMenuItem2_Click(), and MotionDetectorSample.MainForm.SetMotionDetectionAlgorithm().
statLength
const int MotionDetectorSample.MainForm.statLength = 15 static private
Referenced by MotionDetectorSample.MainForm.timer_Tick().
statIndex
int MotionDetectorSample.MainForm.statIndex = 0 private
Referenced by MotionDetectorSample.MainForm.OpenVideoSource(), and MotionDetectorSample.MainForm.timer_Tick().
statReady
int MotionDetectorSample.MainForm.statReady = 0 private
Referenced by MotionDetectorSample.MainForm.OpenVideoSource(), and MotionDetectorSample.MainForm.timer_Tick().
statCount
int [] MotionDetectorSample.MainForm.statCount = new int[statLength] private
Referenced by MotionDetectorSample.MainForm.timer_Tick().
flash
int MotionDetectorSample.MainForm.flash = 0 private
Referenced by MotionDetectorSample.MainForm.alarmTimer_Tick(), and MotionDetectorSample.MainForm.videoSourcePlayer_NewFrame().
motionAlarmLevel
float MotionDetectorSample.MainForm.motionAlarmLevel = 0.015f private
Referenced by MotionDetectorSample.MainForm.DrawMotionHistory(), and MotionDetectorSample.MainForm.videoSourcePlayer_NewFrame().
motionHistory
List<float> MotionDetectorSample.MainForm.motionHistory = new List<float>() private
Referenced by MotionDetectorSample.MainForm.CloseVideoSource(), MotionDetectorSample.MainForm.DrawMotionHistory(), MotionDetectorSample.MainForm.SetMotionDetectionAlgorithm(), and MotionDetectorSample.MainForm.videoSourcePlayer_NewFrame().
detectedObjectsCount
int MotionDetectorSample.MainForm.detectedObjectsCount = -1 private
Referenced by MotionDetectorSample.MainForm.Application_Idle(), and MotionDetectorSample.MainForm.videoSourcePlayer_NewFrame().
components
System.ComponentModel.IContainer MotionDetectorSample.MainForm.components = null private
Required designer variable.
Referenced by MotionDetectorSample.MainForm.Dispose(), and MotionDetectorSample.MainForm.InitializeComponent().
menuMenu
System.Windows.Forms.MenuStrip MotionDetectorSample.MainForm.menuMenu private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
fileToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.fileToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
openToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.openToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
toolStripMenuItem1
System.Windows.Forms.ToolStripSeparator MotionDetectorSample.MainForm.toolStripMenuItem1 private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
exitToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.exitToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
motionToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.motionToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
helpToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.helpToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
aboutToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.aboutToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
openFileDialog
System.Windows.Forms.OpenFileDialog MotionDetectorSample.MainForm.openFileDialog private
Referenced by MotionDetectorSample.MainForm.InitializeComponent(), MotionDetectorSample.MainForm.openToolStripMenuItem_Click(), and MotionDetectorSample.MainForm.openVideoFileusingDirectShowToolStripMenuItem_Click().
timer
System.Windows.Forms.Timer MotionDetectorSample.MainForm.timer private
Referenced by MotionDetectorSample.MainForm.CloseVideoSource(), MotionDetectorSample.MainForm.InitializeComponent(), and MotionDetectorSample.MainForm.OpenVideoSource().
statusBar
System.Windows.Forms.StatusStrip MotionDetectorSample.MainForm.statusBar private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
fpsLabel
System.Windows.Forms.ToolStripStatusLabel MotionDetectorSample.MainForm.fpsLabel private
Referenced by MotionDetectorSample.MainForm.InitializeComponent(), and MotionDetectorSample.MainForm.timer_Tick().
panel1
System.Windows.Forms.Panel MotionDetectorSample.MainForm.panel1 private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
openJPEGURLToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.openJPEGURLToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
openMJPEGURLToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.openMJPEGURLToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
toolStripMenuItem2
System.Windows.Forms.ToolStripSeparator MotionDetectorSample.MainForm.toolStripMenuItem2 private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
localVideoCaptureDeviceToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.localVideoCaptureDeviceToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
openVideoFileusingDirectShowToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.openVideoFileusingDirectShowToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
objectsCountLabel
System.Windows.Forms.ToolStripStatusLabel MotionDetectorSample.MainForm.objectsCountLabel private
Referenced by MotionDetectorSample.MainForm.Application_Idle(), and MotionDetectorSample.MainForm.InitializeComponent().
defineMotionregionsToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.defineMotionregionsToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
toolsToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.toolsToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
localVideoCaptureSettingsToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.localVideoCaptureSettingsToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent(), and MotionDetectorSample.MainForm.toolsToolStripMenuItem_DropDownOpening().
videoSourcePlayer
AForge.Controls.VideoSourcePlayer MotionDetectorSample.MainForm.videoSourcePlayer private
Referenced by MotionDetectorSample.MainForm.alarmTimer_Tick(), MotionDetectorSample.MainForm.CloseVideoSource(), MotionDetectorSample.MainForm.defineMotionregionsToolStripMenuItem_Click(), MotionDetectorSample.MainForm.InitializeComponent(), MotionDetectorSample.MainForm.OpenVideoSource(), and MotionDetectorSample.MainForm.timer_Tick().
motionDetectionAlgorithmToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.motionDetectionAlgorithmToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
noneToolStripMenuItem1
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.noneToolStripMenuItem1 private
Referenced by MotionDetectorSample.MainForm.InitializeComponent(), and MotionDetectorSample.MainForm.motionToolStripMenuItem_DropDownOpening().
twoFramesDifferenceToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.twoFramesDifferenceToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent(), and MotionDetectorSample.MainForm.motionToolStripMenuItem_DropDownOpening().
simpleBackgroundModelingToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.simpleBackgroundModelingToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent(), and MotionDetectorSample.MainForm.motionToolStripMenuItem_DropDownOpening().
motionProcessingAlgorithmToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.motionProcessingAlgorithmToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
noneToolStripMenuItem2
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.noneToolStripMenuItem2 private
Referenced by MotionDetectorSample.MainForm.InitializeComponent(), and MotionDetectorSample.MainForm.motionToolStripMenuItem_DropDownOpening().
motionBorderHighlightingToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.motionBorderHighlightingToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent(), and MotionDetectorSample.MainForm.motionToolStripMenuItem_DropDownOpening().
blobCountingToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.blobCountingToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent(), and MotionDetectorSample.MainForm.motionToolStripMenuItem_DropDownOpening().
gridMotionAreaProcessingToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.gridMotionAreaProcessingToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent(), and MotionDetectorSample.MainForm.motionToolStripMenuItem_DropDownOpening().
motionAreaHighlightingToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.motionAreaHighlightingToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent(), and MotionDetectorSample.MainForm.motionToolStripMenuItem_DropDownOpening().
alarmTimer
System.Windows.Forms.Timer MotionDetectorSample.MainForm.alarmTimer private
Referenced by MotionDetectorSample.MainForm.CloseVideoSource(), MotionDetectorSample.MainForm.InitializeComponent(), MotionDetectorSample.MainForm.OpenVideoSource(), and MotionDetectorSample.MainForm.videoSourcePlayer_NewFrame().
toolStripMenuItem3
System.Windows.Forms.ToolStripSeparator MotionDetectorSample.MainForm.toolStripMenuItem3 private
Referenced by MotionDetectorSample.MainForm.InitializeComponent().
showMotionHistoryToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.showMotionHistoryToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent(), MotionDetectorSample.MainForm.showMotionHistoryToolStripMenuItem_Click(), and MotionDetectorSample.MainForm.videoSourcePlayer_NewFrame().
crossbarVideoSettingsToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MotionDetectorSample.MainForm.crossbarVideoSettingsToolStripMenuItem private
Referenced by MotionDetectorSample.MainForm.InitializeComponent(), and MotionDetectorSample.MainForm.toolsToolStripMenuItem_DropDownOpening().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Vision/MotionDetector/MainForm.cs
shelldev/lib_ann/aforge.net/Samples/Vision/MotionDetector/MainForm.Designer.cs