Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DORMTR Class Reference
DotNumerics.LinearAlgebra.CSLapack.DORMTR Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DORMTR (LSAME lsame, ILAENV ilaenv, DORMQL dormql, DORMQR dormqr, XERBLA xerbla)
DORMTR ()
void Run (string SIDE, string UPLO, string TRANS, int M, int N, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
LSAME _lsame
ILAENV _ilaenv
DORMQL _dormql
DORMQR _dormqr
XERBLA _xerbla
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DORMTR overwrites the general real M-by-N matrix C with
SIDE = 'L' SIDE = 'R' TRANS = 'N': Q * C C * Q TRANS = 'T': Q**T * C C * Q**T
where Q is a real orthogonal matrix of order nq, with nq = m if SIDE = 'L' and nq = n if SIDE = 'R'. Q is defined as the product of nq-1 elementary reflectors, as returned by DSYTRD:
if UPLO = 'U', Q = H(nq-1) . . . H(2) H(1);
if UPLO = 'L', Q = H(1) H(2) . . . H(nq-1).
/summary>
Constructor & Destructor Documentation
DORMTR() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DORMTR.DORMTR (LSAME lsame, ILAENV ilaenv, DORMQL dormql, DORMQR dormqr, XERBLA xerbla) inline
DORMTR() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DORMTR.DORMTR () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DORMTR.Run (string SIDE, string UPLO, string TRANS, int M, int N, ref double[] A, int offset_a, int LDA, double[] TAU, int offset_tau, ref double[] C, int offset_c, int LDC, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DORMTR overwrites the general real M-by-N matrix C with
SIDE = 'L' SIDE = 'R' TRANS = 'N': Q * C C * Q TRANS = 'T': Q**T * C C * Q**T
where Q is a real orthogonal matrix of order nq, with nq = m if SIDE = 'L' and nq = n if SIDE = 'R'. Q is defined as the product of nq-1 elementary reflectors, as returned by DSYTRD:
if UPLO = 'U', Q = H(nq-1) . . . H(2) H(1);
if UPLO = 'L', Q = H(1) H(2) . . . H(nq-1).
/summary>
Parameters
SIDE = 'L' SIDE = 'R' /param>
Parameters
UPLO (input) CHARACTER*1 = 'U': Upper triangle of A contains elementary reflectors from DSYTRD; = 'L': Lower triangle of A contains elementary reflectors from DSYTRD. /param>
Parameters
TRANS (input) CHARACTER*1 = 'N': No transpose, apply Q; = 'T': Transpose, apply Q**T. /param>
Parameters
M (input) INTEGER The number of rows of the matrix C. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix C. N .GE. 0. /param>
Parameters
A (input) DOUBLE PRECISION array, dimension (LDA,M) if SIDE = 'L' (LDA,N) if SIDE = 'R' The vectors which define the elementary reflectors, as returned by DSYTRD. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M) if SIDE = 'L'; LDA .GE. max(1,N) if SIDE = 'R'. /param>
Parameters
TAU (input) DOUBLE PRECISION array, dimension (M-1) if SIDE = 'L' (N-1) if SIDE = 'R' TAU(i) must contain the scalar factor of the elementary reflector H(i), as returned by DSYTRD. /param>
Parameters
C (input/output) DOUBLE PRECISION array, dimension (LDC,N) On entry, the M-by-N matrix C. On exit, C is overwritten by Q*C or Q**T*C or C*Q**T or C*Q. /param>
Parameters
LDC (input) INTEGER The leading dimension of the array C. LDC .GE. max(1,M). /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. If SIDE = 'L', LWORK .GE. max(1,N); if SIDE = 'R', LWORK .GE. max(1,M). For optimum performance LWORK .GE. N*NB if SIDE = 'L', and LWORK .GE. M*NB if SIDE = 'R', where NB is the optimal blocksize.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMQR.Run(), and DotNumerics.LinearAlgebra.CSLapack.DORMQL.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSYEVD.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DORMTR._lsame private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DORMTR._ilaenv private
_dormql
DORMQL DotNumerics.LinearAlgebra.CSLapack.DORMTR._dormql private
_dormqr
DORMQR DotNumerics.LinearAlgebra.CSLapack.DORMTR._dormqr private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DORMTR._xerbla private
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dormtr.cs