Doc: IGLib EXTENDED: IG.Forms.HashDirForm Class Reference
IG.Forms.HashDirForm Class Reference
Public Member Functions
HashDirForm ()
HashDirForm ()
HashDirForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
IG.Forms.HashDirControl hashDirControl1
Constructor & Destructor Documentation
HashDirForm() [1/3]
IG.Forms.HashDirForm.HashDirForm () inline
References IG.Forms.HashDirForm.InitializeComponent().
HashDirForm() [2/3]
IG.Forms.HashDirForm.HashDirForm () inline
References IG.Forms.HashDirForm.InitializeComponent().
HashDirForm() [3/3]
IG.Forms.HashDirForm.HashDirForm () inline
References IG.Forms.HashDirForm.InitializeComponent().
Member Function Documentation
Dispose() [1/3]
override void IG.Forms.HashDirForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.HashDirForm.components.
InitializeComponent() [1/3]
void IG.Forms.HashDirForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.HashDirForm.hashDirControl1.
Referenced by IG.Forms.HashDirForm.HashDirForm().
Dispose() [2/3]
override void IG.Forms.HashDirForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.HashDirForm.components.
InitializeComponent() [2/3]
void IG.Forms.HashDirForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.HashDirForm.hashDirControl1.
Dispose() [3/3]
override void IG.Forms.HashDirForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.HashDirForm.components.
InitializeComponent() [3/3]
void IG.Forms.HashDirForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.HashDirForm.hashDirControl1.
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.HashDirForm.components = null private
Required designer variable.
Referenced by IG.Forms.HashDirForm.Dispose().
hashDirControl1
IG Forms HashDirControl IG.Forms.HashDirForm.hashDirControl1 private
Referenced by IG.Forms.HashDirForm.InitializeComponent().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/Cryptography/HashDirForm.cs
iglib/igforms/Utilities/Cryptography/HashDirForm.Designer.cs