Doc: IGLib EXTENDED: AForge.Imaging.Filters.BayerFilterOptimized Class Reference
AForge.Imaging.Filters.BayerFilterOptimized Class Reference
Optimized Bayer fileter image processing routine.
Public Member Functions
BayerFilterOptimized ()
Initializes a new instance of the BayerFilterOptimized class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
Protected Member Functions
override void ProcessFilter (UnmanagedImage sourceData, UnmanagedImage destinationData)
Process the filter on the specified image.
Properties
BayerPattern Pattern [get, set]
Bayer pattern of source images to decode.
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.BaseFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Member Functions
unsafe void ApplyGRBG (UnmanagedImage sourceData, UnmanagedImage destinationData)
unsafe void ApplyBGGR (UnmanagedImage sourceData, UnmanagedImage destinationData)
Private Attributes
BayerPattern bayerPattern = BayerPattern.GRBG
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Optimized Bayer fileter image processing routine.
The class implements Bayer filter routine, which creates color image out of grayscale image produced by image sensor built with Bayer color matrix.
This class does all the same as BayerFilter class. However this version is optimized for some well known patterns defined in BayerPattern enumeration. Also this class processes images with even width and height only. Image size must be at least 2x2 pixels.
The filter accepts 8 bpp grayscale images and produces 24 bpp RGB image.
Sample usage:
// create filter
BayerFilter filter = new BayerFilter();
// apply the filter
Bitmap rgbImage = filter.Apply(image);
See also
BayerFilter
Constructor & Destructor Documentation
BayerFilterOptimized()
AForge.Imaging.Filters.BayerFilterOptimized.BayerFilterOptimized () inline
Initializes a new instance of the BayerFilterOptimized class.
References AForge.Imaging.Filters.BayerFilterOptimized.formatTranslations.
Member Function Documentation
ProcessFilter()
override void AForge.Imaging.Filters.BayerFilterOptimized.ProcessFilter (UnmanagedImage sourceData, UnmanagedImage destinationData) inline protected virtual
Process the filter on the specified image.
Parameters
sourceData Source image data.
destinationData Destination image data.
Implements AForge.Imaging.Filters.BaseFilter.
References AForge.Imaging.Filters.BayerFilterOptimized.ApplyBGGR(), AForge.Imaging.Filters.BayerFilterOptimized.ApplyGRBG(), AForge.Imaging.Filters.BayerFilterOptimized.bayerPattern, AForge.Imaging.UnmanagedImage.Height, and AForge.Imaging.UnmanagedImage.Width.
ApplyGRBG()
unsafe void AForge.Imaging.Filters.BayerFilterOptimized.ApplyGRBG (UnmanagedImage sourceData, UnmanagedImage destinationData) inline private
References AForge.Imaging.RGB.B, AForge.Imaging.RGB.G, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.RGB.R, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
Referenced by AForge.Imaging.Filters.BayerFilterOptimized.ProcessFilter().
ApplyBGGR()
unsafe void AForge.Imaging.Filters.BayerFilterOptimized.ApplyBGGR (UnmanagedImage sourceData, UnmanagedImage destinationData) inline private
References AForge.Imaging.RGB.B, AForge.Imaging.RGB.G, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.RGB.R, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
Referenced by AForge.Imaging.Filters.BayerFilterOptimized.ProcessFilter().
Member Data Documentation
bayerPattern
BayerPattern AForge.Imaging.Filters.BayerFilterOptimized.bayerPattern = BayerPattern.GRBG private
Referenced by AForge.Imaging.Filters.BayerFilterOptimized.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.BayerFilterOptimized.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.BayerFilterOptimized.BayerFilterOptimized().
Property Documentation
Pattern
BayerPattern AForge.Imaging.Filters.BayerFilterOptimized.Pattern get set
Bayer pattern of source images to decode.
The property specifies Bayer pattern of source images to be decoded into color images.
Default value is set to BayerPattern.GRBG.
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.BayerFilterOptimized.FormatTranslations get
Format translations dictionary.
See IFilterInformation.FormatTranslations documentation for additional information.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Color Filters/BayerFilterOptimized.cs