Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGGRQF Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGGRQF Class Reference
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGGRQF (DGEQRF dgeqrf, DGERQF dgerqf, DORMRQ dormrq, XERBLA xerbla, ILAENV ilaenv)
DGGRQF ()
void Run (int M, int P, int N, ref double[] A, int offset_a, int LDA, ref double[] TAUA, int offset_taua, ref double[] B, int offset_b, int LDB, ref double[] TAUB, int offset_taub, ref double[] WORK, int offset_work, int LWORK, ref int INFO)
Private Attributes
DGEQRF _dgeqrf
DGERQF _dgerqf
DORMRQ _dormrq
XERBLA _xerbla
ILAENV _ilaenv
Detailed Description
– LAPACK routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGGRQF computes a generalized RQ factorization of an M-by-N matrix A and a P-by-N matrix B:
A = R*Q, B = Z*T*Q,
where Q is an N-by-N orthogonal matrix, Z is a P-by-P orthogonal matrix, and R and T assume one of the forms:
if M .LE. N, R = (0 R12) M, or if M .GT. N, R = (R11) M-N, N-M M (R21) N N
where R12 or R21 is upper triangular, and
if P .GE. N, T = (T11) N , or if P .LT. N, T = (T11 T12) P, (0) P-N P N-P N
where T11 is upper triangular.
In particular, if B is square and nonsingular, the GRQ factorization of A and B implicitly gives the RQ factorization of A*inv(B):
A*inv(B) = (R*inv(T))*Z'
where inv(B) denotes the inverse of the matrix B, and Z' denotes the transpose of the matrix Z.
/summary>
Constructor & Destructor Documentation
DGGRQF() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGGRQF.DGGRQF (DGEQRF dgeqrf, DGERQF dgerqf, DORMRQ dormrq, XERBLA xerbla, ILAENV ilaenv) inline
DGGRQF() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGGRQF.DGGRQF () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGGRQF.Run (int M, int P, int N, ref double[] A, int offset_a, int LDA, ref double[] TAUA, int offset_taua, ref double[] B, int offset_b, int LDB, ref double[] TAUB, int offset_taub, ref double[] WORK, int offset_work, int LWORK, ref int INFO) inline
Purpose
DGGRQF computes a generalized RQ factorization of an M-by-N matrix A and a P-by-N matrix B:
A = R*Q, B = Z*T*Q,
where Q is an N-by-N orthogonal matrix, Z is a P-by-P orthogonal matrix, and R and T assume one of the forms:
if M .LE. N, R = (0 R12) M, or if M .GT. N, R = (R11) M-N, N-M M (R21) N N
where R12 or R21 is upper triangular, and
if P .GE. N, T = (T11) N , or if P .LT. N, T = (T11 T12) P, (0) P-N P N-P N
where T11 is upper triangular.
In particular, if B is square and nonsingular, the GRQ factorization of A and B implicitly gives the RQ factorization of A*inv(B):
A*inv(B) = (R*inv(T))*Z'
where inv(B) denotes the inverse of the matrix B, and Z' denotes the transpose of the matrix Z.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
P (input) INTEGER The number of rows of the matrix B. P .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrices A and B. N .GE. 0. /param>
Parameters
A = R*Q, B = Z*T*Q, /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
TAUA (output) DOUBLE PRECISION array, dimension (min(M,N)) The scalar factors of the elementary reflectors which represent the orthogonal matrix Q (see Further Details). /param>
Parameters
B (input/output) DOUBLE PRECISION array, dimension (LDB,N) On entry, the P-by-N matrix B. On exit, the elements on and above the diagonal of the array contain the min(P,N)-by-N upper trapezoidal matrix T (T is upper triangular if P .GE. N); the elements below the diagonal, with the array TAUB, represent the orthogonal matrix Z as a product of elementary reflectors (see Further Details). /param>
Parameters
LDB (input) INTEGER The leading dimension of the array B. LDB .GE. max(1,P). /param>
Parameters
TAUB (output) DOUBLE PRECISION array, dimension (min(P,N)) The scalar factors of the elementary reflectors which represent the orthogonal matrix Z (see Further Details). /param>
Parameters
WORK (workspace/output) DOUBLE PRECISION array, dimension (MAX(1,LWORK)) On exit, if INFO = 0, WORK(1) returns the optimal LWORK. /param>
Parameters
LWORK (input) INTEGER The dimension of the array WORK. LWORK .GE. max(1,N,M,P). For optimum performance LWORK .GE. max(N,M,P)*max(NB1,NB2,NB3), where NB1 is the optimal blocksize for the RQ factorization of an M-by-N matrix, NB2 is the optimal blocksize for the QR factorization of a P-by-N matrix, and NB3 is the optimal blocksize for a call of DORMRQ.
If LWORK = -1, then a workspace query is assumed; the routine only calculates the optimal size of the WORK array, returns this value as the first entry of the WORK array, and no error message related to LWORK is issued by XERBLA. /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INF0= -i, the i-th argument had an illegal value. /param>
References DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGERQF.Run(), DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DORMRQ.Run().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGGLSE.Run().
Member Data Documentation
_dgeqrf
DGEQRF DotNumerics.LinearAlgebra.CSLapack.DGGRQF._dgeqrf private
_dgerqf
DGERQF DotNumerics.LinearAlgebra.CSLapack.DGGRQF._dgerqf private
_dormrq
DORMRQ DotNumerics.LinearAlgebra.CSLapack.DGGRQF._dormrq private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGGRQF._xerbla private
_ilaenv
ILAENV DotNumerics.LinearAlgebra.CSLapack.DGGRQF._ilaenv private
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dggrqf.cs