Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGBSV Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGBSV Class Reference
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGBSV (DGBTRF dgbtrf, DGBTRS dgbtrs, XERBLA xerbla)
DGBSV ()
void Run (int N, int KL, int KU, int NRHS, ref double[] AB, int offset_ab, int LDAB, ref int[] IPIV, int offset_ipiv, ref double[] B, int offset_b, int LDB, ref int INFO)
Private Attributes
DGBTRF _dgbtrf
DGBTRS _dgbtrs
XERBLA _xerbla
Detailed Description
– LAPACK driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DGBSV computes the solution to a real system of linear equations A * X = B, where A is a band matrix of order N with KL subdiagonals and KU superdiagonals, and X and B are N-by-NRHS matrices.
The LU decomposition with partial pivoting and row interchanges is used to factor A as A = L * U, where L is a product of permutation and unit lower triangular matrices with KL subdiagonals, and U is upper triangular with KL+KU superdiagonals. The factored form of A is then used to solve the system of equations A * X = B.
/summary>
Constructor & Destructor Documentation
DGBSV() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGBSV.DGBSV (DGBTRF dgbtrf, DGBTRS dgbtrs, XERBLA xerbla) inline
DGBSV() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGBSV.DGBSV () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGBSV.Run (int N, int KL, int KU, int NRHS, ref double[] AB, int offset_ab, int LDAB, ref int[] IPIV, int offset_ipiv, ref double[] B, int offset_b, int LDB, ref int INFO) inline
Purpose
DGBSV computes the solution to a real system of linear equations A * X = B, where A is a band matrix of order N with KL subdiagonals and KU superdiagonals, and X and B are N-by-NRHS matrices.
The LU decomposition with partial pivoting and row interchanges is used to factor A as A = L * U, where L is a product of permutation and unit lower triangular matrices with KL subdiagonals, and U is upper triangular with KL+KU superdiagonals. The factored form of A is then used to solve the system of equations A * X = B.
/summary>
Parameters
N (input) INTEGER The number of linear equations, i.e., the order of the matrix A. N .GE. 0. /param>
Parameters
KL (input) INTEGER The number of subdiagonals within the band of A. KL .GE. 0. /param>
Parameters
KU (input) INTEGER The number of superdiagonals within the band of A. KU .GE. 0. /param>
Parameters
NRHS (input) INTEGER The number of right hand sides, i.e., the number of columns of the matrix B. NRHS .GE. 0. /param>
Parameters
AB (input/output) DOUBLE PRECISION array, dimension (LDAB,N) On entry, the matrix A in band storage, in rows KL+1 to 2*KL+KU+1; rows 1 to KL of the array need not be set. The j-th column of A is stored in the j-th column of the array AB as follows: AB(KL+KU+1+i-j,j) = A(i,j) for max(1,j-KU).LE.i.LE.min(N,j+KL) On exit, details of the factorization: U is stored as an upper triangular band matrix with KL+KU superdiagonals in rows 1 to KL+KU+1, and the multipliers used during the factorization are stored in rows KL+KU+2 to 2*KL+KU+1. See below for further details. /param>
Parameters
LDAB (input) INTEGER The leading dimension of the array AB. LDAB .GE. 2*KL+KU+1. /param>
Parameters
IPIV (output) INTEGER array, dimension (N) The pivot indices that define the permutation matrix P; row i of the matrix was interchanged with row IPIV(i). /param>
Parameters
B (input/output) DOUBLE PRECISION array, dimension (LDB,NRHS) On entry, the N-by-NRHS right hand side matrix B. On exit, if INFO = 0, the N-by-NRHS solution matrix X. /param>
Parameters
LDB (input) INTEGER The leading dimension of the array B. LDB .GE. max(1,N). /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value .GT. 0: if INFO = i, U(i,i) is exactly zero. The factorization has been completed, but the factor U is exactly singular, and the solution has not been computed. /param>
References DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DGBTRS.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGBTRF.Run().
Member Data Documentation
_dgbtrf
DGBTRF DotNumerics.LinearAlgebra.CSLapack.DGBSV._dgbtrf private
_dgbtrs
DGBTRS DotNumerics.LinearAlgebra.CSLapack.DGBSV._dgbtrs private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGBSV._xerbla private
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgbsv.cs