Doc: IGLib EXTENDED: AForge.Neuro.SigmoidFunction Class Reference
AForge.Neuro.SigmoidFunction Class Reference
Sigmoid activation function
Public Member Functions
SigmoidFunction ()
Initializes a new instance of the SigmoidFunction class
SigmoidFunction (double alpha)
Initializes a new instance of the SigmoidFunction class
double Function (double x)
Calculates function value
double Derivative (double x)
Calculates function derivative
double Derivative2 (double y)
Calculates function derivative
SigmoidFunction ()
Initializes a new instance of the SigmoidFunction class
SigmoidFunction (double alpha)
Initializes a new instance of the SigmoidFunction class
double Function (double x)
Calculates function value
double Derivative (double x)
Calculates function derivative
double Derivative2 (double y)
Calculates function derivative
SigmoidFunction ()
Initializes a new instance of the SigmoidFunction class.
SigmoidFunction (double alpha)
Initializes a new instance of the SigmoidFunction class.
double Function (double x)
Calculates function value.
double Derivative (double x)
Calculates function derivative.
double Derivative2 (double y)
Calculates function derivative.
Properties
double Alpha [get, set]
Sigmoid's alpha value
Private Attributes
double alpha = 2
Detailed Description
Sigmoid activation function
Sigmoid activation function.
The class represents sigmoid activation function with the next expression:
               1
f(x) = ---------------&mdash;
       1 + exp(-alpha * x)
          alpha * exp(-alpha * x )
f'(x) = -------------------------&mdash; = alpha * f(x) * (1 - f(x))
          (1 + exp(-alpha * x))^2
Output range of the function: [0, 1]
Functions graph:
The class represents sigmoid activation function with the next expression:
               1
f(x) = ---------------&mdash;
       1 + exp(-alpha * x)
          alpha * exp(-alpha * x )
f'(x) = -------------------------&mdash; = alpha * f(x) * (1 - f(x))
          (1 + exp(-alpha * x))^2
Output range of the function: [0, 1].
Functions graph:
Constructor & Destructor Documentation
SigmoidFunction() [1/6]
AForge.Neuro.SigmoidFunction.SigmoidFunction () inline
Initializes a new instance of the SigmoidFunction class
SigmoidFunction() [2/6]
AForge.Neuro.SigmoidFunction.SigmoidFunction (double alpha) inline
Initializes a new instance of the SigmoidFunction class
Parameters
alpha Sigmoid's alpha value
References AForge.Neuro.SigmoidFunction.alpha.
SigmoidFunction() [3/6]
AForge.Neuro.SigmoidFunction.SigmoidFunction () inline
Initializes a new instance of the SigmoidFunction class
SigmoidFunction() [4/6]
AForge.Neuro.SigmoidFunction.SigmoidFunction (double alpha) inline
Initializes a new instance of the SigmoidFunction class
Parameters
alpha Sigmoid's alpha value
References AForge.Neuro.SigmoidFunction.alpha.
SigmoidFunction() [5/6]
AForge.Neuro.SigmoidFunction.SigmoidFunction () inline
Initializes a new instance of the SigmoidFunction class.
SigmoidFunction() [6/6]
AForge.Neuro.SigmoidFunction.SigmoidFunction (double alpha) inline
Initializes a new instance of the SigmoidFunction class.
Parameters
alpha Sigmoid's alpha value.
References AForge.Neuro.SigmoidFunction.alpha.
Member Function Documentation
Function() [1/3]
double AForge.Neuro.SigmoidFunction.Function (double x) inline
Calculates function value
Parameters
x Function input value
Returns
Function output value, f(x)
The method calculates function value at point x.
Implements AForge.Neuro.IActivationFunction.
References AForge.Neuro.SigmoidFunction.alpha.
Referenced by AForge.Neuro.SigmoidFunction.Derivative().
Derivative() [1/3]
double AForge.Neuro.SigmoidFunction.Derivative (double x) inline
Calculates function derivative
Parameters
x Function input value
Returns
Function derivative, f'(x)
The method calculates function derivative at point x.
Implements AForge.Neuro.IActivationFunction.
References AForge.Neuro.SigmoidFunction.alpha, and AForge.Neuro.SigmoidFunction.Function().
Derivative2() [1/3]
double AForge.Neuro.SigmoidFunction.Derivative2 (double y) inline
Calculates function derivative
Parameters
y Function output value - the value, which was obtained with the help of Function method
Returns
Function derivative, f'(x)
The method calculates the same derivative value as the Derivative method, but it takes not the input x value itself, but the function value, which was calculated previously with the help of Function method. (Some applications require as function value, as derivative value, so they can seve the amount of calculations using this method to calculate derivative)
Implements AForge.Neuro.IActivationFunction.
References AForge.Neuro.SigmoidFunction.alpha.
Function() [2/3]
double AForge.Neuro.SigmoidFunction.Function (double x) inline
Calculates function value
Parameters
x Function input value
Returns
Function output value, f(x)
The method calculates function value at point x.
Implements AForge.Neuro.IActivationFunction.
References AForge.Neuro.SigmoidFunction.alpha.
Derivative() [2/3]
double AForge.Neuro.SigmoidFunction.Derivative (double x) inline
Calculates function derivative
Parameters
x Function input value
Returns
Function derivative, f'(x)
The method calculates function derivative at point x.
Implements AForge.Neuro.IActivationFunction.
References AForge.Neuro.SigmoidFunction.alpha, and AForge.Neuro.SigmoidFunction.Function().
Derivative2() [2/3]
double AForge.Neuro.SigmoidFunction.Derivative2 (double y) inline
Calculates function derivative
Parameters
y Function output value - the value, which was obtained with the help of Function method
Returns
Function derivative, f'(x)
The method calculates the same derivative value as the Derivative method, but it takes not the input x value itself, but the function value, which was calculated previously with the help of Function method. (Some applications require as function value, as derivative value, so they can seve the amount of calculations using this method to calculate derivative)
Implements AForge.Neuro.IActivationFunction.
References AForge.Neuro.SigmoidFunction.alpha.
Function() [3/3]
double AForge.Neuro.SigmoidFunction.Function (double x) inline
Calculates function value.
Parameters
x Function input value.
Returns
Function output value, f(x).
The method calculates function value at point x .
Implements AForge.Neuro.IActivationFunction.
References AForge.Neuro.SigmoidFunction.alpha.
Derivative() [3/3]
double AForge.Neuro.SigmoidFunction.Derivative (double x) inline
Calculates function derivative.
Parameters
x Function input value.
Returns
Function derivative, f'(x).
The method calculates function derivative at point x .
Implements AForge.Neuro.IActivationFunction.
References AForge.Neuro.SigmoidFunction.alpha, and AForge.Neuro.SigmoidFunction.Function().
Derivative2() [3/3]
double AForge.Neuro.SigmoidFunction.Derivative2 (double y) inline
Calculates function derivative.
Parameters
y Function output value - the value, which was obtained with the help of Function method.
Returns
Function derivative, f'(x).
The method calculates the same derivative value as the Derivative method, but it takes not the input x value itself, but the function value, which was calculated previously with the help of Function method.
<note>Some applications require as function value, as derivative value, so they can save the amount of calculations using this method to calculate derivative.</note>
Implements AForge.Neuro.IActivationFunction.
References AForge.Neuro.SigmoidFunction.alpha.
Member Data Documentation
alpha
double AForge.Neuro.SigmoidFunction.alpha = 2 private
Referenced by AForge.Neuro.SigmoidFunction.Derivative(), AForge.Neuro.SigmoidFunction.Derivative2(), AForge.Neuro.SigmoidFunction.Function(), and AForge.Neuro.SigmoidFunction.SigmoidFunction().
Property Documentation
Alpha
double AForge.Neuro.SigmoidFunction.Alpha get set
Sigmoid's alpha value
Sigmoid's alpha value.
The value determines steepness of the function. Default value: 2.
The value determines steepness of the function. Increasing value of this property changes sigmoid to look more like a threshold function. Decreasing value of this property makes sigmoid to be very smooth (slowly growing from its minimum value to its maximum value).
Default value is set to 2.
The documentation for this class was generated from the following file:
shelldev/lib/external/neuralnetworks/neuro_src/Sources/Backup/Neuro/Activation Functions/SigmoidFunction.cs