Doc: IGLib EXTENDED: Meta.Numerics.Statistics.BivariateSample Class Reference
Meta.Numerics.Statistics.BivariateSample Class Reference
Represents a set of data points, where each data point is described by a pair of real numbers.
Public Member Functions
BivariateSample ()
Initializes a new bivariate sample.
BivariateSample (string xName, string yName)
Initializes a new bivariate sample with the given variable names.
void Add (double x, double y)
Adds a data point to the sample.
void Add (XY point)
Adds a data point to the sample.
void Add (IEnumerable< XY > points)
Adds multiple data points to the sample.
void Add (IList< double > x, IList< double > y)
Adds points from two lists to the sample.
bool Remove (double x, double y)
Removes a data point from the sample.
bool Remove (XY point)
Removes a data point from the sample.
void Clear ()
Removes all data points from the sample.
bool Contains (double x, double y)
Determines whether the sample contains a given data point.
bool Contains (XY xy)
Determines whether the sample contains a given data point.
BivariateSample Copy ()
Copies the bivariate sample.
IEnumerator< XY > GetEnumerator ()
Gets an enumerator of sample values.
void TransposeXY ()
Swaps the X and Y variables in the bivariate sample.
TestResult PearsonRTest ()
Performs a Pearson correlation test for association.
TestResult SpearmanRhoTest ()
Performs a Spearman rank-order test of association between the two variables.
TestResult KendallTauTest ()
Performs a Kendall concordance test for association.
TestResult PairedStudentTTest ()
Performs a paired Student t-test.
FitResult LinearRegression ()
Computes the best-fit linear regression from the data.
FitResult PolynomialRegression (int m)
Computes the polynomial of given degree which best fits the data.
FitResult LinearLogisticRegression ()
Computes the best-fit linear logistic regression from the data.
void Load (IDataReader reader, int xIndex, int yIndex)
Loads values from a data reader.
Properties
bool IsReadOnly [get]
Gets a value indicating whether the bivariate sample is read-only.
Sample X [get]
Gets a read-only univariate sample consisting of the x-values of the data points.
Sample Y [get]
Gets a read-only univariate sample consisting of the y-values of the data points.
int Count [get]
Gets the number of data points.
double Covariance [get]
Gets the covariance of the two variables.
double CorrelationCoefficient [get]
Gets the correlation coefficient between the two variables.
UncertainValue PopulationCovariance [get]
Estimates of the population covariance of two variables.
Private Member Functions
int IndexOf (double x, double y)
IEnumerator IEnumerable. GetEnumerator ()
void ICollection< XY >. CopyTo (XY[] array, int start)
double MomentAboutMean (int nx, int ny)
Private Attributes
SampleStorage xData
SampleStorage yData
bool isReadOnly
Detailed Description
Represents a set of data points, where each data point is described by a pair of real numbers.
A bivariate sample consists of pairs of real numbers, where each pair is an independent measurement. For example, if you measure the height and weight of a sample of people, the data could be stored as a bivariate sample. The class can compute various descriptive statistics for the sample, perform appropriate statistical tests on the sample data, and fit the sample data to various models.
Constructor & Destructor Documentation
BivariateSample() [1/2]
Meta.Numerics.Statistics.BivariateSample.BivariateSample () inline
Initializes a new bivariate sample.
References Meta.Numerics.Statistics.BivariateSample.isReadOnly, Meta.Numerics.Statistics.BivariateSample.xData, and Meta.Numerics.Statistics.BivariateSample.yData.
Referenced by Meta.Numerics.Statistics.BivariateSample.Copy().
BivariateSample() [2/2]
Meta.Numerics.Statistics.BivariateSample.BivariateSample (string xName, string yName) inline
Initializes a new bivariate sample with the given variable names.
Parameters
xName The name of the x-variable.
yName The name of the y-variable.
References Meta.Numerics.Statistics.BivariateSample.xData, and Meta.Numerics.Statistics.BivariateSample.yData.
Member Function Documentation
Add() [1/4]
void Meta.Numerics.Statistics.BivariateSample.Add (double x, double y) inline
Adds a data point to the sample.
Parameters
x The x-value of the data point.
y The y-value of the data point.
References Meta.Numerics.Statistics.BivariateSample.isReadOnly, Meta.Numerics.Statistics.BivariateSample.xData, and Meta.Numerics.Statistics.BivariateSample.yData.
Referenced by Meta.Numerics.Statistics.BivariateSample.Add(), Test.SampleTest.BetaFitUncertainty(), Test.BivariateSampleTest.BivariateLinearRegression(), Test.BivariateSampleTest.BivariateLinearRegressionGoodnessOfFitDistribution(), Test.BivariateSampleTest.BivariateSampleCopy(), Test.BugTests.Bug6162(), Test.ContingencyTableTest.ContingencyTableProbabilitiesAndUncertainties(), Test.SampleTest.GammaFitUncertainty(), Test.NullDistributionTests.KendallNullDistributionTest(), Test.BivariateSampleTest.LinearLogisticRegression(), Test.SampleTest.NormalFitUncertainties(), Test.BivariateSampleTest.PearsonRDistribution(), Test.NullDistributionTests.SpearmanNullDistributionTest(), and Test.SampleTest.WeibullFitUncertainties().
Add() [2/4]
void Meta.Numerics.Statistics.BivariateSample.Add (XY point) inline
Adds a data point to the sample.
Parameters
point The data point.
References Meta.Numerics.Statistics.BivariateSample.Add(), Meta.Numerics.XY.X, and Meta.Numerics.XY.Y.
Add() [3/4]
void Meta.Numerics.Statistics.BivariateSample.Add (IEnumerable< XY > points) inline
Adds multiple data points to the sample.
Parameters
points The data points.
References Meta.Numerics.Statistics.BivariateSample.Add().
Add() [4/4]
void Meta.Numerics.Statistics.BivariateSample.Add (IList< double > x, IList< double > y) inline
Adds points from two lists to the sample.
Parameters
x The x values of the data points.
y The y values of the data points.
Exceptions
DimensionMistachException The lengths of the two lists are not equal.
References Meta.Numerics.Statistics.BivariateSample.Add().
IndexOf()
int Meta.Numerics.Statistics.BivariateSample.IndexOf (double x, double y) inline private
References Meta.Numerics.Statistics.BivariateSample.Count, Meta.Numerics.Statistics.BivariateSample.xData, and Meta.Numerics.Statistics.BivariateSample.yData.
Referenced by Meta.Numerics.Statistics.BivariateSample.Contains(), and Meta.Numerics.Statistics.BivariateSample.Remove().
Remove() [1/2]
bool Meta.Numerics.Statistics.BivariateSample.Remove (double x, double y) inline
Removes a data point from the sample.
Parameters
x The x-value of the data point.
y The y-value of the data point.
Returns
True if the given data point was found and removed, otherwise false.
References Meta.Numerics.Statistics.BivariateSample.IndexOf(), Meta.Numerics.Statistics.BivariateSample.isReadOnly, Meta.Numerics.Statistics.BivariateSample.xData, and Meta.Numerics.Statistics.BivariateSample.yData.
Referenced by Meta.Numerics.Statistics.BivariateSample.Remove().
Remove() [2/2]
bool Meta.Numerics.Statistics.BivariateSample.Remove (XY point) inline
Removes a data point from the sample.
Parameters
point The point to remove.
Returns
True if the given data point was found and removed, otherwise false.
References Meta.Numerics.Statistics.BivariateSample.Remove(), Meta.Numerics.XY.X, and Meta.Numerics.XY.Y.
Clear()
void Meta.Numerics.Statistics.BivariateSample.Clear () inline
Removes all data points from the sample.
References Meta.Numerics.Statistics.BivariateSample.isReadOnly, Meta.Numerics.Statistics.BivariateSample.xData, and Meta.Numerics.Statistics.BivariateSample.yData.
Contains() [1/2]
bool Meta.Numerics.Statistics.BivariateSample.Contains (double x, double y) inline
Determines whether the sample contains a given data point.
Parameters
x The x-value of the data point.
y The y-value of the data point.
Returns
True if the sample contains the given data point, otherwise false.
References Meta.Numerics.Statistics.BivariateSample.IndexOf().
Referenced by Meta.Numerics.Statistics.BivariateSample.Contains().
Contains() [2/2]
bool Meta.Numerics.Statistics.BivariateSample.Contains (XY xy) inline
Determines whether the sample contains a given data point.
Parameters
xy The data point.
Returns
True if the sample contains the given data point, otherwise false.
References Meta.Numerics.Statistics.BivariateSample.Contains(), Meta.Numerics.XY.X, and Meta.Numerics.XY.Y.
Copy()
BivariateSample Meta.Numerics.Statistics.BivariateSample.Copy () inline
Copies the bivariate sample.
Returns
An independent copy of the bivariate sample.
References Meta.Numerics.Statistics.BivariateSample.BivariateSample(), Meta.Numerics.Statistics.BivariateSample.xData, and Meta.Numerics.Statistics.BivariateSample.yData.
Referenced by Test.BivariateSampleTest.BivariateSampleCopy().
GetEnumerator() [1/2]
IEnumerator<XY> Meta.Numerics.Statistics.BivariateSample.GetEnumerator () inline
Gets an enumerator of sample values.
Returns
An enumerator of sample values.
References Meta.Numerics.Statistics.BivariateSample.Count, Meta.Numerics.Statistics.BivariateSample.xData, and Meta.Numerics.Statistics.BivariateSample.yData.
Referenced by Meta.Numerics.Statistics.BivariateSample.GetEnumerator().
GetEnumerator() [2/2]
IEnumerator IEnumerable. Meta.Numerics.Statistics.BivariateSample.GetEnumerator () inline private
References Meta.Numerics.Statistics.BivariateSample.GetEnumerator().
CopyTo()
void ICollection<XY>. Meta.Numerics.Statistics.BivariateSample.CopyTo (XY[] array, int start) inline private
References Meta.Numerics.Statistics.BivariateSample.Count, Meta.Numerics.Statistics.BivariateSample.xData, and Meta.Numerics.Statistics.BivariateSample.yData.
TransposeXY()
void Meta.Numerics.Statistics.BivariateSample.TransposeXY () inline
Swaps the X and Y variables in the bivariate sample.
References Meta.Numerics.Statistics.BivariateSample.xData, and Meta.Numerics.Statistics.BivariateSample.yData.
MomentAboutMean()
double Meta.Numerics.Statistics.BivariateSample.MomentAboutMean (int nx, int ny) inline private
References Meta.Numerics.Statistics.BivariateSample.Count, Meta.Numerics.MoreMath.Pow(), Meta.Numerics.Statistics.BivariateSample.xData, and Meta.Numerics.Statistics.BivariateSample.yData.
PearsonRTest()
TestResult Meta.Numerics.Statistics.BivariateSample.PearsonRTest () inline
Performs a Pearson correlation test for association.
Returns
The result of the test.
This test measures the strength of the linear correlation between two variables. The test statistic r is simply the covariance of the two variables, scaled by their respective standard deviations so as to obtain a number between -1 (perfect linear anti-correlation) and +1 (perfect linear correlation).
The Pearson test cannot reliably detect or rule out non-linear associations. For example, variables with a perfect quadratic association may have only a weak linear correlation. If you wish to test for associations that may not be linear, consider using the Spearman or Kendall tests instead.
The Pearson correlation test requires O(N) operations.
The Pearson test requires at least three bivariate values.
Exceptions
InsufficientDataException Count is less than three.
See also
SpearmanRhoTest, KendallTauTest
References Meta.Numerics.Statistics.BivariateSample.Count, Meta.Numerics.Statistics.BivariateSample.Covariance, Meta.Numerics.Statistics.BivariateSample.xData, and Meta.Numerics.Statistics.BivariateSample.yData.
Referenced by Test.BivariateSampleTest.PearsonRDistribution().
SpearmanRhoTest()
TestResult Meta.Numerics.Statistics.BivariateSample.SpearmanRhoTest () inline
Performs a Spearman rank-order test of association between the two variables.
Returns
The result of the test.
The Spearman rank-order test of association is a non-parametric test for association between two variables. The test statistic rho is the correlation coefficient of the rank of each entry in the sample. It is thus invariant over monotonic reparameterizations of the data, and will, for example, detect a quadratic or exponential association just as well as a linear association.
The Spearman rank-order test requires O(N log N) operations.
Exceptions
InsufficientDataException There are fewer than three data points.
See also
PearsonRTest, KendallTauTest
References Meta.Numerics.Statistics.BivariateSample.Count, Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Statistics.BivariateSample.xData, and Meta.Numerics.Statistics.BivariateSample.yData.
Referenced by Test.NullDistributionTests.SpearmanNullDistributionTest().
KendallTauTest()
TestResult Meta.Numerics.Statistics.BivariateSample.KendallTauTest () inline
Performs a Kendall concordance test for association.
Returns
The result of the test.
Kendall's &#x3C4; is a non-parameteric and robust test of association between two variables. It simply measures the number of cases where an increase in one variable is associated with an increase in the other (corcordant pairs), compared with the number of cases where an increase in one variable is associated with a decrease in the other (discordant pairs).
Because &#x3C4; depends only on the sign of a change and not its magnitude, it is not skewed by outliers exhibiting very large changes, nor by cases where the degree of change in one variable associated with a given change in the other changes over the range of the varibles. Of course, it may still miss an association whoose sign changes over the range of the variables. For example, if data points lie along a semi-circle in the plane, an increase in the first variable is associated with an increase in the second variable along the rising arc and and decrease in the second variable along the falling arc. No test that looks for single-signed correlation will catch this association.
Because it examine all pairs of data points, the Kendall test requires O(N2) operations. It is thus impractical for very large data sets. While not quite as robust as the Kendall test, the Spearman test is a good fall-back in such cases.
Exceptions
InsufficientDataException Count is less than two.
See also
PearsonRTest, SpearmanRhoTest
References Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Statistics.BivariateSample.xData, and Meta.Numerics.Statistics.BivariateSample.yData.
Referenced by Test.NullDistributionTests.KendallNullDistributionTest().
PairedStudentTTest()
TestResult Meta.Numerics.Statistics.BivariateSample.PairedStudentTTest () inline
Performs a paired Student t-test.
Returns
The result of the test.
Like a two-sample, unpaired t-test (Sample.StudentTTest(Sample,Sample)), a paired t-test compares two samples to detect a difference in means. Unlike the unpaired version, the paired version assumes that each
Exceptions
InsufficientDataException There are fewer than two data points.
References Meta.Numerics.Statistics.BivariateSample.Count, Meta.Numerics.Statistics.BivariateSample.xData, and Meta.Numerics.Statistics.BivariateSample.yData.
LinearRegression()
FitResult Meta.Numerics.Statistics.BivariateSample.LinearRegression () inline
Computes the best-fit linear regression from the data.
Returns
The result of the fit.
Linear regression assumes that the data have been generated by a function y = a + b x + e, where e is normally distributed noise, and determines the values of a and b that best fit the data. It also determines an error matrix on the parameters a and b, and does an F-test to
The fit result is two-dimensional. The first parameter is the intercept a, the second is the slope b. The goodness-of-fit test is a F-test comparing the variance accounted for by the model to the remaining, unexplained variance.
Exceptions
InsufficientDataException There are fewer than three data points.
References Meta.Numerics.Statistics.BivariateSample.Count, Meta.Numerics.Statistics.BivariateSample.Covariance, Meta.Numerics.Statistics.BivariateSample.xData, and Meta.Numerics.Statistics.BivariateSample.yData.
Referenced by Test.BivariateSampleTest.BivariateLinearRegressionGoodnessOfFitDistribution(), and Test.MultivariateSampleTest.MultivariateLinearRegressionAgreement().
PolynomialRegression()
FitResult Meta.Numerics.Statistics.BivariateSample.PolynomialRegression (int m) inline
Computes the polynomial of given degree which best fits the data.
Parameters
m The degree, which must be non-negative.
Returns
The fit result.
Exceptions
ArgumentOutOfRangeException m is negative.
InsufficientDataException There are fewer data points than coefficients to be fit.
References Meta.Numerics.Statistics.BivariateSample.Count, Meta.Numerics.Matrices.ColumnVector.Transpose(), Meta.Numerics.Statistics.BivariateSample.xData, and Meta.Numerics.Statistics.BivariateSample.yData.
Referenced by Test.BugTests.Bug6162().
LinearLogisticRegression()
FitResult Meta.Numerics.Statistics.BivariateSample.LinearLogisticRegression () inline
Computes the best-fit linear logistic regression from the data.
Returns
The fit result.
Linear logistic regression is a way to fit binary outcome data to a linear model.
The method assumes that binary outcomes are encoded as 0 and 1. If any y-values other than 0 and 1 are encountered, it throws an InvalidOperationException.
The fit result is two-dimensional. The first parameter is a, the second b.
Exceptions
InsufficientDataException There are fewer than three data points.
InvalidOperationException There is a y-value other than 0 or 1.
References Meta.Numerics.Statistics.BivariateSample.Count, Meta.Numerics.Statistics.BivariateSample.Covariance, Meta.Numerics.Analysis.MultiFunctionMath.FindMinimum(), Meta.Numerics.Statistics.Sample.Mean, Meta.Numerics.Statistics.Sample.Variance, Meta.Numerics.Statistics.BivariateSample.X, Meta.Numerics.Statistics.BivariateSample.xData, Meta.Numerics.Statistics.BivariateSample.Y, and Meta.Numerics.Statistics.BivariateSample.yData.
Load()
void Meta.Numerics.Statistics.BivariateSample.Load (IDataReader reader, int xIndex, int yIndex) inline
Loads values from a data reader.
Parameters
reader The data reader.
xIndex The column number of the x-variable.
yIndex The column number of the y-variable.
Member Data Documentation
xData
SampleStorage Meta.Numerics.Statistics.BivariateSample.xData private
Referenced by Meta.Numerics.Statistics.BivariateSample.Add(), Meta.Numerics.Statistics.BivariateSample.BivariateSample(), Meta.Numerics.Statistics.BivariateSample.Clear(), Meta.Numerics.Statistics.BivariateSample.Copy(), Meta.Numerics.Statistics.BivariateSample.CopyTo(), Meta.Numerics.Statistics.BivariateSample.GetEnumerator(), Meta.Numerics.Statistics.BivariateSample.IndexOf(), Meta.Numerics.Statistics.BivariateSample.KendallTauTest(), Meta.Numerics.Statistics.BivariateSample.LinearLogisticRegression(), Meta.Numerics.Statistics.BivariateSample.LinearRegression(), Meta.Numerics.Statistics.BivariateSample.MomentAboutMean(), Meta.Numerics.Statistics.BivariateSample.PairedStudentTTest(), Meta.Numerics.Statistics.BivariateSample.PearsonRTest(), Meta.Numerics.Statistics.BivariateSample.PolynomialRegression(), Meta.Numerics.Statistics.BivariateSample.Remove(), Meta.Numerics.Statistics.BivariateSample.SpearmanRhoTest(), and Meta.Numerics.Statistics.BivariateSample.TransposeXY().
yData
SampleStorage Meta.Numerics.Statistics.BivariateSample.yData private
Referenced by Meta.Numerics.Statistics.BivariateSample.Add(), Meta.Numerics.Statistics.BivariateSample.BivariateSample(), Meta.Numerics.Statistics.BivariateSample.Clear(), Meta.Numerics.Statistics.BivariateSample.Copy(), Meta.Numerics.Statistics.BivariateSample.CopyTo(), Meta.Numerics.Statistics.BivariateSample.GetEnumerator(), Meta.Numerics.Statistics.BivariateSample.IndexOf(), Meta.Numerics.Statistics.BivariateSample.KendallTauTest(), Meta.Numerics.Statistics.BivariateSample.LinearLogisticRegression(), Meta.Numerics.Statistics.BivariateSample.LinearRegression(), Meta.Numerics.Statistics.BivariateSample.MomentAboutMean(), Meta.Numerics.Statistics.BivariateSample.PairedStudentTTest(), Meta.Numerics.Statistics.BivariateSample.PearsonRTest(), Meta.Numerics.Statistics.BivariateSample.PolynomialRegression(), Meta.Numerics.Statistics.BivariateSample.Remove(), Meta.Numerics.Statistics.BivariateSample.SpearmanRhoTest(), and Meta.Numerics.Statistics.BivariateSample.TransposeXY().
isReadOnly
bool Meta.Numerics.Statistics.BivariateSample.isReadOnly private
Referenced by Meta.Numerics.Statistics.BivariateSample.Add(), Meta.Numerics.Statistics.BivariateSample.BivariateSample(), Meta.Numerics.Statistics.BivariateSample.Clear(), and Meta.Numerics.Statistics.BivariateSample.Remove().
Property Documentation
IsReadOnly
bool Meta.Numerics.Statistics.BivariateSample.IsReadOnly get
Gets a value indicating whether the bivariate sample is read-only.
X
Sample Meta.Numerics.Statistics.BivariateSample.X get
Gets a read-only univariate sample consisting of the x-values of the data points.
Use this method to obtain sinformation specific to the x-vales, such as their Sample.Median or Sample.Variance.
Note that this is a fast, O(1) operation, which does not create an independent copy of the data. The advantage of this is that you can access x-data as a Sample as often as you like without worying about performance. The disadvantage of this is that the returned sample cannot be altered. If you need to alter x-data independent of the bivariate sample, use the Sample.Copy method to obtain an independent copy.
Referenced by Test.SampleTest.BetaFitUncertainty(), Test.BivariateSampleTest.BivariateLinearRegression(), Test.ContingencyTableTest.ContingencyTableProbabilitiesAndUncertainties(), Test.SampleTest.GammaFitUncertainty(), Test.BivariateSampleTest.LinearLogisticRegression(), Meta.Numerics.Statistics.BivariateSample.LinearLogisticRegression(), Test.SampleTest.NormalFitUncertainties(), and Test.SampleTest.WeibullFitUncertainties().
Y
Sample Meta.Numerics.Statistics.BivariateSample.Y get
Gets a read-only univariate sample consisting of the y-values of the data points.
Use this method to obtain sinformation specific to the y-vales, such as their Sample.Median or Sample.Variance.
Note that this is a fast, O(1) operation, which does not create an independent copy of the data. The advantage of this is that you can access y-data as a Sample as often as you like without worying about performance. The disadvantage of this is that the returned sample cannot be altered. If you need to alter y-data independent of the bivariate sample, use the Sample.Copy method to obtain an independent copy.
Referenced by Test.SampleTest.BetaFitUncertainty(), Test.BivariateSampleTest.BivariateLinearRegression(), Test.ContingencyTableTest.ContingencyTableProbabilitiesAndUncertainties(), Test.SampleTest.GammaFitUncertainty(), Test.BivariateSampleTest.LinearLogisticRegression(), Meta.Numerics.Statistics.BivariateSample.LinearLogisticRegression(), Test.SampleTest.NormalFitUncertainties(), and Test.SampleTest.WeibullFitUncertainties().
Count
int Meta.Numerics.Statistics.BivariateSample.Count get
Gets the number of data points.
Referenced by Test.BivariateSampleTest.BivariateLinearRegression(), Test.BivariateSampleTest.BivariateSampleCopy(), Meta.Numerics.Statistics.BivariateSample.CopyTo(), Meta.Numerics.Statistics.BivariateSample.GetEnumerator(), Meta.Numerics.Statistics.BivariateSample.IndexOf(), Test.BivariateSampleTest.LinearLogisticRegression(), Meta.Numerics.Statistics.BivariateSample.LinearLogisticRegression(), Meta.Numerics.Statistics.BivariateSample.LinearRegression(), Meta.Numerics.Statistics.BivariateSample.MomentAboutMean(), Test.SampleTest.NormalFitUncertainties(), Meta.Numerics.Statistics.BivariateSample.PairedStudentTTest(), Meta.Numerics.Statistics.BivariateSample.PearsonRTest(), Meta.Numerics.Statistics.BivariateSample.PolynomialRegression(), and Meta.Numerics.Statistics.BivariateSample.SpearmanRhoTest().
Covariance
double Meta.Numerics.Statistics.BivariateSample.Covariance get
Gets the covariance of the two variables.
Referenced by Meta.Numerics.Statistics.BivariateSample.LinearLogisticRegression(), Meta.Numerics.Statistics.BivariateSample.LinearRegression(), and Meta.Numerics.Statistics.BivariateSample.PearsonRTest().
CorrelationCoefficient
double Meta.Numerics.Statistics.BivariateSample.CorrelationCoefficient get
Gets the correlation coefficient between the two variables.
PopulationCovariance
UncertainValue Meta.Numerics.Statistics.BivariateSample.PopulationCovariance get
Estimates of the population covariance of two variables.
Returns
An estimate, with associated uncertainty, of the population covariance.
Referenced by Test.BivariateSampleTest.BivariateLinearRegression(), Test.BivariateSampleTest.LinearLogisticRegression(), and Test.SampleTest.NormalFitUncertainties().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/BivariateSample.cs