Doc: IGLib EXTENDED: AP.Math Class Reference
AP.Math Class Reference
Static Public Member Functions
static double RandomReal ()
static int RandomInteger (int N)
static double Sqr (double X)
static double AbsComplex (Complex z)
static Complex Conj (Complex z)
static Complex CSqr (Complex z)
Static Public Attributes
static System.Random RndObject = new System.Random(System.DateTime.Now.Millisecond)
const double MachineEpsilon = 5E-16
const double MaxRealNumber = 1E300
const double MinRealNumber = 1E-300
Member Function Documentation
RandomReal()
static double AP.Math.RandomReal () inline static
References AP.Math.RndObject.
RandomInteger()
static int AP.Math.RandomInteger (int N) inline static
References AP.Math.RndObject.
Sqr()
static double AP.Math.Sqr (double X) inline static
Referenced by lbfgs.mcstep().
AbsComplex()
static double AP.Math.AbsComplex (Complex z) inline static
Conj()
static Complex AP.Math.Conj (Complex z) inline static
CSqr()
static Complex AP.Math.CSqr (Complex z) inline static
Member Data Documentation
RndObject
System.Random AP.Math.RndObject = new System.Random(System.DateTime.Now.Millisecond) static
Referenced by AP.Math.RandomInteger(), and AP.Math.RandomReal().
MachineEpsilon
const double AP.Math.MachineEpsilon = 5E-16 static
MaxRealNumber
const double AP.Math.MaxRealNumber = 1E300 static
MinRealNumber
const double AP.Math.MinRealNumber = 1E-300 static
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/ap.cs