Doc: IGLib EXTENDED: IG.MPetekLib.Application.Scripts.LinearOscillator._14PhaseShiftPlot Class Reference
IG.MPetekLib.Application.Scripts.LinearOscillator._14PhaseShiftPlot Class Reference
Static Public Member Functions
static void Run (string[] arguments)
Member Function Documentation
Run()
static void IG.MPetekLib.Application.Scripts.LinearOscillator._14PhaseShiftPlot.Run (string[] arguments) inline static
References IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.DampingCoefficient, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.EndingDrivingAngularFrequency, IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenHarmonicOscillator.FindAnalyticallyPhaseVsDrivingFrequency(), IG.MPetekLib.Algorithms.PlottableModels.PlottableModelBase.NewCurveFromPlottableData(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.NSamplesForResonanceCurve, IG.MPetekLib.Algorithms.Plotting.PlotHQ.Plotter, IG.MPetekLib.Algorithms.Plotting.PlotHQ.ShowPlot(), IG.MPetekLib.Algorithms.PlottableModels.Oscillators.DrivenOscillatorBase.StartingDrivingAngularFrequency, and IG.MPetekLib.Algorithms.Plotting.PlotHQ.Window.
Referenced by IG.Script.AppMarkoPetek.App14PhaseShiftPlot().
The documentation for this class was generated from the following file:
shelldev/0guests/marko_petek/Guest_Marko_Petek_Lib/application/scripts/LinearOscillator/14PhaseShiftPlot.cs