Doc: IGLib EXTENDED: AForge.Imaging.Textures.LabyrinthTexture Class Reference
AForge.Imaging.Textures.LabyrinthTexture Class Reference
Labirinth texture.
Public Member Functions
LabyrinthTexture ()
Initializes a new instance of the LabyrinthTexture class.
float[,] Generate (int width, int height)
Generate texture.
void Reset ()
Reset generator.
Private Attributes
AForge.Math.PerlinNoise noise = new AForge.Math.PerlinNoise(1, 0.65, 1.0 / 16, 1.0)
Random rand = new Random()
int r
Detailed Description
Labirinth texture.
The texture generator creates textures with effect of labyrinth.
The generator is based on the Perlin noise function.
Sample usage:
// create texture generator
LabyrinthTexture textureGenerator = new LabyrinthTexture();
// generate new texture
float[,] texture = textureGenerator.Generate(320, 240);
// convert it to image to visualize
Bitmap textureImage = TextureTools.ToBitmap(texture);
Result image:
Constructor & Destructor Documentation
LabyrinthTexture()
AForge.Imaging.Textures.LabyrinthTexture.LabyrinthTexture () inline
Initializes a new instance of the LabyrinthTexture class.
References AForge.Imaging.Textures.LabyrinthTexture.Reset().
Member Function Documentation
Generate()
float [,] AForge.Imaging.Textures.LabyrinthTexture.Generate (int width, int height) inline
Generate texture.
Parameters
width Texture's width.
height Texture's height.
Returns
Two dimensional array of intensities.
Generates new texture of the specified size.
Implements AForge.Imaging.Textures.ITextureGenerator.
References AForge.Math.PerlinNoise.Function2D(), AForge.Imaging.Textures.LabyrinthTexture.noise, and AForge.Imaging.Textures.LabyrinthTexture.r.
Reset()
void AForge.Imaging.Textures.LabyrinthTexture.Reset () inline
Reset generator.
Regenerates internal random numbers.
Implements AForge.Imaging.Textures.ITextureGenerator.
References AForge.Imaging.Textures.LabyrinthTexture.r, and AForge.Imaging.Textures.LabyrinthTexture.rand.
Referenced by AForge.Imaging.Textures.LabyrinthTexture.LabyrinthTexture().
Member Data Documentation
noise
AForge.Math.PerlinNoise AForge.Imaging.Textures.LabyrinthTexture.noise = new AForge.Math.PerlinNoise(1, 0.65, 1.0 / 16, 1.0) private
Referenced by AForge.Imaging.Textures.LabyrinthTexture.Generate().
rand
Random AForge.Imaging.Textures.LabyrinthTexture.rand = new Random() private
Referenced by AForge.Imaging.Textures.LabyrinthTexture.Reset().
r
int AForge.Imaging.Textures.LabyrinthTexture.r private
Referenced by AForge.Imaging.Textures.LabyrinthTexture.Generate(), and AForge.Imaging.Textures.LabyrinthTexture.Reset().
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Textures/LabyrinthTexture.cs