Doc: IGLib EXTENDED: NUnit.Framework.Internal.ExceptionHelper Class Reference
NUnit.Framework.Internal.ExceptionHelper Class Reference
ExceptionHelper provides static methods for working with exceptions
Static Public Member Functions
static string BuildMessage (Exception exception)
Builds up a message, using the Message field of the specified exception as well as any InnerExceptions.
static string BuildStackTrace (Exception exception)
Builds up a message, using the Message field of the specified exception as well as any InnerExceptions.
static string GetStackTrace (Exception exception)
Gets the stack trace of the exception.
Static Private Member Functions
static List< Exception > FlattenExceptionHierarchy (Exception exception)
Detailed Description
ExceptionHelper provides static methods for working with exceptions
Member Function Documentation
BuildMessage()
static string NUnit.Framework.Internal.ExceptionHelper.BuildMessage (Exception exception) inline static
Builds up a message, using the Message field of the specified exception as well as any InnerExceptions.
Parameters
exception The exception.
Returns
A combined message string.
References NUnit.Framework.Internal.ExceptionHelper.FlattenExceptionHierarchy(), and NUnit.Env.NewLine.
Referenced by NUnit.Framework.Internal.TestResult.RecordException(), NUnit.Framework.Internal.TestResult.RecordTearDownException(), and NUnit.Framework.Internal.TestParameters.TestParameters().
BuildStackTrace()
static string NUnit.Framework.Internal.ExceptionHelper.BuildStackTrace (Exception exception) inline static
Builds up a message, using the Message field of the specified exception as well as any InnerExceptions.
Parameters
exception The exception.
Returns
A combined stack trace.
References NUnit.Framework.Internal.ExceptionHelper.FlattenExceptionHierarchy(), NUnit.Framework.Internal.ExceptionHelper.GetStackTrace(), and NUnit.Env.NewLine.
Referenced by NUnit.Framework.Internal.TestResult.RecordException(), NUnit.Framework.Internal.TestResult.RecordTearDownException(), and NUnit.Framework.Internal.TestParameters.TestParameters().
GetStackTrace()
static string NUnit.Framework.Internal.ExceptionHelper.GetStackTrace (Exception exception) inline static
Gets the stack trace of the exception.
Parameters
exception The exception.
Returns
A string representation of the stack trace.
Referenced by NUnit.Framework.Internal.ExceptionHelper.BuildStackTrace().
FlattenExceptionHierarchy()
static List<Exception> NUnit.Framework.Internal.ExceptionHelper.FlattenExceptionHierarchy (Exception exception) inline static private
Referenced by NUnit.Framework.Internal.ExceptionHelper.BuildMessage(), and NUnit.Framework.Internal.ExceptionHelper.BuildStackTrace().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/ExceptionHelper.cs