Doc: IGLib EXTENDED: alglib.poissondistr Class Reference
alglib.poissondistr Class Reference
Static Public Member Functions
static double poissondistribution (int k, double m)
static double poissoncdistribution (int k, double m)
static double invpoissondistribution (int k, double y)
static double poissondistribution (int k, double m)
static double poissoncdistribution (int k, double m)
static double invpoissondistribution (int k, double y)
Member Function Documentation
poissondistribution() [1/2]
static double alglib.poissondistr.poissondistribution (int k, double m) inline static
References alglib.ap.assert(), and alglib.igammaf.incompletegammac().
Referenced by alglib.poissondistribution().
poissoncdistribution() [1/2]
static double alglib.poissondistr.poissoncdistribution (int k, double m) inline static
References alglib.ap.assert(), and alglib.igammaf.incompletegamma().
Referenced by alglib.poissoncdistribution().
invpoissondistribution() [1/2]
static double alglib.poissondistr.invpoissondistribution (int k, double y) inline static
References alglib.ap.assert(), and alglib.igammaf.invincompletegammac().
Referenced by alglib.invpoissondistribution().
poissondistribution() [2/2]
static double alglib.poissondistr.poissondistribution (int k, double m) inline static
References alglib.ap.assert(), and alglib.igammaf.incompletegammac().
poissoncdistribution() [2/2]
static double alglib.poissondistr.poissoncdistribution (int k, double m) inline static
References alglib.ap.assert(), and alglib.igammaf.incompletegamma().
invpoissondistribution() [2/2]
static double alglib.poissondistr.invpoissondistribution (int k, double y) inline static
References alglib.ap.assert(), and alglib.igammaf.invincompletegammac().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/specialfunctions.cs