Doc: IGLib EXTENDED: TestGui.BrowseWS Class Reference
TestGui.BrowseWS Class Reference
Public Member Functions
BrowseWS ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void textBox1_TextChanged (object sender, EventArgs e)
void buttonExit_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.WebBrowser webBrowserWS
System.Windows.Forms.Label labelURL
System.Windows.Forms.TextBox textBox1
System.Windows.Forms.Button buttonExit
Constructor & Destructor Documentation
BrowseWS()
TestGui.BrowseWS.BrowseWS () inline
References TestGui.BrowseWS.InitializeComponent().
Member Function Documentation
textBox1_TextChanged()
void TestGui.BrowseWS.textBox1_TextChanged (object sender, EventArgs e) inline private
Referenced by TestGui.BrowseWS.InitializeComponent().
buttonExit_Click()
void TestGui.BrowseWS.buttonExit_Click (object sender, EventArgs e) inline private
References TestGui.BrowseWS.Dispose().
Referenced by TestGui.BrowseWS.InitializeComponent().
Dispose()
override void TestGui.BrowseWS.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References TestGui.BrowseWS.components.
Referenced by TestGui.BrowseWS.buttonExit_Click().
InitializeComponent()
void TestGui.BrowseWS.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References TestGui.BrowseWS.buttonExit, TestGui.BrowseWS.buttonExit_Click(), TestGui.BrowseWS.labelURL, TestGui.BrowseWS.textBox1, TestGui.BrowseWS.textBox1_TextChanged(), and TestGui.BrowseWS.webBrowserWS.
Referenced by TestGui.BrowseWS.BrowseWS().
Member Data Documentation
components
System.ComponentModel.IContainer TestGui.BrowseWS.components = null private
Required designer variable.
Referenced by TestGui.BrowseWS.Dispose().
webBrowserWS
System.Windows.Forms.WebBrowser TestGui.BrowseWS.webBrowserWS private
Referenced by TestGui.BrowseWS.InitializeComponent().
labelURL
System.Windows.Forms.Label TestGui.BrowseWS.labelURL private
Referenced by TestGui.BrowseWS.InitializeComponent().
textBox1
System.Windows.Forms.TextBox TestGui.BrowseWS.textBox1 private
Referenced by TestGui.BrowseWS.InitializeComponent().
buttonExit
System.Windows.Forms.Button TestGui.BrowseWS.buttonExit private
Referenced by TestGui.BrowseWS.InitializeComponent().
The documentation for this class was generated from the following files:
igtest/tmp_prem/prefa/95_Test/TestUtils/TestGui/Form3.cs
igtest/tmp_prem/prefa/95_Test/TestUtils/TestGui/Form3.Designer.cs