Doc: IGLib EXTENDED: Test.UnivariateDistributionTest Class Reference
Test.UnivariateDistributionTest Class Reference
Public Member Functions
void Initialize ()
void UnivariateDistributionRawMomentSpecialCases ()
void UnivariateDistributionCentralMomentSpecialCases ()
void UnivariantDistributionCumulantSpecialCases ()
void UnivariateDistributionExcessKurtosis ()
void UnivariateDistributionMomentSums ()
void CumulantToCentralAndRaw ()
Public Attributes
UnivariateDistribution[] Distributions
Member Function Documentation
Initialize()
void Test.UnivariateDistributionTest.Initialize () inline
References Test.UnivariateDistributionTest.Distributions, Test.DistributionTest.GetDistributions(), and Test.DiscreteDistributionTest.GetDistributions().
UnivariateDistributionRawMomentSpecialCases()
void Test.UnivariateDistributionTest.UnivariateDistributionRawMomentSpecialCases () inline
References Test.UnivariateDistributionTest.Distributions, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, and Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Moment().
UnivariateDistributionCentralMomentSpecialCases()
void Test.UnivariateDistributionTest.UnivariateDistributionCentralMomentSpecialCases () inline
References Test.UnivariateDistributionTest.Distributions, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.MomentAboutMean(), and Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Variance.
UnivariantDistributionCumulantSpecialCases()
void Test.UnivariateDistributionTest.UnivariantDistributionCumulantSpecialCases () inline
References Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Cumulant(), Test.UnivariateDistributionTest.Distributions, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Mean, and Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Variance.
UnivariateDistributionExcessKurtosis()
void Test.UnivariateDistributionTest.UnivariateDistributionExcessKurtosis () inline
References Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Cumulant(), Test.UnivariateDistributionTest.Distributions, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.ExcessKurtosis, and Meta.Numerics.MoreMath.Sqr().
UnivariateDistributionMomentSums()
void Test.UnivariateDistributionTest.UnivariateDistributionMomentSums () inline
References Test.UnivariateDistributionTest.Distributions, Meta.Numerics.Statistics.Distributions.UnivariateDistribution.Moment(), and Meta.Numerics.Statistics.Distributions.UnivariateDistribution.MomentAboutMean().
CumulantToCentralAndRaw()
void Test.UnivariateDistributionTest.CumulantToCentralAndRaw () inline
References Meta.Numerics.Statistics.Distributions.MomentMath.CumulantToCentral(), Meta.Numerics.Statistics.Distributions.MomentMath.CumulantToRaw(), and Test.UnivariateDistributionTest.Distributions.
Member Data Documentation
Distributions
UnivariateDistribution [] Test.UnivariateDistributionTest.Distributions
Referenced by Test.UnivariateDistributionTest.CumulantToCentralAndRaw(), Test.UnivariateDistributionTest.Initialize(), Test.UnivariateDistributionTest.UnivariantDistributionCumulantSpecialCases(), Test.UnivariateDistributionTest.UnivariateDistributionCentralMomentSpecialCases(), Test.UnivariateDistributionTest.UnivariateDistributionExcessKurtosis(), Test.UnivariateDistributionTest.UnivariateDistributionMomentSums(), and Test.UnivariateDistributionTest.UnivariateDistributionRawMomentSpecialCases().
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/UnivariateDistributionTest.cs