Doc: IGLib EXTENDED: PoseEstimation.WorldRendererControl Class Reference
PoseEstimation.WorldRendererControl Class Reference
Public Member Functions
WorldRendererControl ()
void SetObject (Vector3[] vertices, Color[] colors, int[,] ribs)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
Matrix4x4 WorldMatrix [get, set]
Matrix4x4 ViewMatrix [get, set]
AForge.Point[] ProjectedPoints [get]
Private Member Functions
void Recalculate ()
void WorldRendererControl_Paint (object sender, PaintEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
Vector3[] objectPoints = null
Vector3[] objectScenePoints = null
AForge.Point[] projectedPoints = null
Color[] colors = null
int[,] lines = null
Matrix4x4 worldMatrix = new Matrix4x4()
Matrix4x4 viewMatrix = new Matrix4x4()
Matrix4x4 perspectiveMatrix = new Matrix4x4()
System.ComponentModel.IContainer components = null
Required designer variable.
Constructor & Destructor Documentation
WorldRendererControl()
PoseEstimation.WorldRendererControl.WorldRendererControl () inline
References PoseEstimation.WorldRendererControl.colors, AForge.Math.Matrix4x4.CreateLookAt(), AForge.Math.Matrix4x4.CreatePerspective(), AForge.Math.Matrix4x4.Identity, PoseEstimation.WorldRendererControl.InitializeComponent(), PoseEstimation.WorldRendererControl.lines, PoseEstimation.WorldRendererControl.objectPoints, PoseEstimation.WorldRendererControl.perspectiveMatrix, PoseEstimation.WorldRendererControl.Recalculate(), PoseEstimation.WorldRendererControl.viewMatrix, and PoseEstimation.WorldRendererControl.worldMatrix.
Member Function Documentation
SetObject()
void PoseEstimation.WorldRendererControl.SetObject (Vector3[] vertices, Color[] colors, int ribs[,]) inline
References PoseEstimation.WorldRendererControl.colors, and PoseEstimation.WorldRendererControl.Recalculate().
Referenced by PoseEstimation.MainForm.objectTypeCombo_SelectedIndexChanged().
Recalculate()
void PoseEstimation.WorldRendererControl.Recalculate () inline private
References PoseEstimation.WorldRendererControl.objectPoints, PoseEstimation.WorldRendererControl.objectScenePoints, PoseEstimation.WorldRendererControl.perspectiveMatrix, PoseEstimation.WorldRendererControl.projectedPoints, AForge.Math.Vector3.ToVector4(), PoseEstimation.WorldRendererControl.viewMatrix, PoseEstimation.WorldRendererControl.worldMatrix, AForge.Math.Vector3.X, and AForge.Math.Vector3.Y.
Referenced by PoseEstimation.WorldRendererControl.SetObject(), and PoseEstimation.WorldRendererControl.WorldRendererControl().
WorldRendererControl_Paint()
void PoseEstimation.WorldRendererControl.WorldRendererControl_Paint (object sender, PaintEventArgs e) inline private
References PoseEstimation.WorldRendererControl.colors, PoseEstimation.WorldRendererControl.lines, and PoseEstimation.WorldRendererControl.projectedPoints.
Referenced by PoseEstimation.WorldRendererControl.InitializeComponent().
Dispose()
override void PoseEstimation.WorldRendererControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References PoseEstimation.WorldRendererControl.components.
InitializeComponent()
void PoseEstimation.WorldRendererControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References PoseEstimation.WorldRendererControl.WorldRendererControl_Paint().
Referenced by PoseEstimation.WorldRendererControl.WorldRendererControl().
Member Data Documentation
objectPoints
Vector3 [] PoseEstimation.WorldRendererControl.objectPoints = null private
Referenced by PoseEstimation.WorldRendererControl.Recalculate(), and PoseEstimation.WorldRendererControl.WorldRendererControl().
objectScenePoints
Vector3 [] PoseEstimation.WorldRendererControl.objectScenePoints = null private
Referenced by PoseEstimation.WorldRendererControl.Recalculate().
projectedPoints
AForge.Point [] PoseEstimation.WorldRendererControl.projectedPoints = null private
Referenced by PoseEstimation.WorldRendererControl.Recalculate(), and PoseEstimation.WorldRendererControl.WorldRendererControl_Paint().
colors
Color [] PoseEstimation.WorldRendererControl.colors = null private
Referenced by PoseEstimation.WorldRendererControl.SetObject(), PoseEstimation.WorldRendererControl.WorldRendererControl(), and PoseEstimation.WorldRendererControl.WorldRendererControl_Paint().
lines
int [,] PoseEstimation.WorldRendererControl.lines = null private
Referenced by PoseEstimation.WorldRendererControl.WorldRendererControl(), and PoseEstimation.WorldRendererControl.WorldRendererControl_Paint().
worldMatrix
Matrix4x4 PoseEstimation.WorldRendererControl.worldMatrix = new Matrix4x4() private
Referenced by PoseEstimation.WorldRendererControl.Recalculate(), and PoseEstimation.WorldRendererControl.WorldRendererControl().
viewMatrix
Matrix4x4 PoseEstimation.WorldRendererControl.viewMatrix = new Matrix4x4() private
Referenced by PoseEstimation.WorldRendererControl.Recalculate(), and PoseEstimation.WorldRendererControl.WorldRendererControl().
perspectiveMatrix
Matrix4x4 PoseEstimation.WorldRendererControl.perspectiveMatrix = new Matrix4x4() private
Referenced by PoseEstimation.WorldRendererControl.Recalculate(), and PoseEstimation.WorldRendererControl.WorldRendererControl().
components
System.ComponentModel.IContainer PoseEstimation.WorldRendererControl.components = null private
Required designer variable.
Referenced by PoseEstimation.WorldRendererControl.Dispose().
Property Documentation
WorldMatrix
Matrix4x4 PoseEstimation.WorldRendererControl.WorldMatrix get set
Referenced by PoseEstimation.MainForm.UpdateTransformationMatrix().
ViewMatrix
Matrix4x4 PoseEstimation.WorldRendererControl.ViewMatrix get set
Referenced by PoseEstimation.MainForm.UpdateViewMatrix().
ProjectedPoints
AForge.Point [] PoseEstimation.WorldRendererControl.ProjectedPoints get
Referenced by PoseEstimation.MainForm.EstimatePose(), and PoseEstimation.MainForm.UpdateProjectedPoints().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Math/Pose Estimation/WorldRendererControl.cs
shelldev/lib_ann/aforge.net/Samples/Math/Pose Estimation/WorldRendererControl.Designer.cs