Doc: IGLib EXTENDED: Meta.Numerics.Statistics.Distributions.GammaDistribution Class Reference
Meta.Numerics.Statistics.Distributions.GammaDistribution Class Reference
Represents a Gamma distribution.
Public Member Functions
GammaDistribution (double shape, double scale)
Initializes a new instance of a Gamma distribution with the given parameters.
GammaDistribution (double shape)
Initializes a new instance of the standard Gamma distribution.
override double ProbabilityDensity (double x)
Returns the probability density at the given point.
override double LeftProbability (double x)
Returns the cumulative probability to the left of (below) the given point.
override double RightProbability (double x)
Return the cumulative probability to the right of (above) the given point.
override double Moment (int r)
Computes a raw moment of the distribution.
override double MomentAboutMean (int r)
Computes a central moment of the distribution.
override double Cumulant (int r)
Computes a cumulant of the distribution.
override double InverseLeftProbability (double P)
Returns the point at which the cumulative distribution function attains a given value.
override double GetRandomValue (Random rng)
Returns a random value.
Public Member Functions inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double InverseRightProbability (double Q)
Returns the point at which the right probability function attains the given value.
virtual double ExpectationValue (Func< double, double > f)
Computes the expectation value of the given function.
Static Public Member Functions
static FitResult FitToSample (Sample sample)
Computes the Gamma distribution that best fits the given sample.
Properties
double ShapeParameter [get]
Gets the shape parameter for the distribution.
double ScaleParameter [get]
Gets the scale parameter for the distribution.
override Interval Support [get]
override double Mean [get]
override double Variance [get]
override double Skewness [get]
override double ExcessKurtosis [get]
Properties inherited from Meta.Numerics.Statistics.Distributions.Distribution
virtual double Median [get]
Gets the median of the distribution.
virtual Interval Support [get]
Gets the interval over which the distribution is nonvanishing.
Properties inherited from Meta.Numerics.Statistics.Distributions.UnivariateDistribution
virtual double Mean [get]
Gets the mean of the distribution.
virtual double Variance [get]
Gets the variance of the distribution.
virtual double StandardDeviation [get]
Gets the standard deviation of the distribution.
virtual double Skewness [get]
Gets the skewness of the distribution.
virtual double ExcessKurtosis [get]
Gets the excess kurtosis of the distribution.
Private Member Functions
double ApproximateInverseStandardGamma (double P, double Q)
double InverseLeftStandardGamma (double P)
Static Private Member Functions
static double ApproximateProbit (double P)
Private Attributes
readonly double a
readonly double s
readonly double ga
readonly IDeviateGenerator gammaRng
Detailed Description
Represents a Gamma distribution.
The sum of n exponentially distributed variates is a Gamma distributed variate.
When the shape parameter is an integer, the Gamma distribution is also called the Erlang distribution. When the shape parameter is one, the Gamma distribution reduces to the exponential distribution.
See also
ExponentialDistribution
Constructor & Destructor Documentation
GammaDistribution() [1/2]
Meta.Numerics.Statistics.Distributions.GammaDistribution.GammaDistribution (double shape, double scale) inline
Initializes a new instance of a Gamma distribution with the given parameters.
Parameters
shape The shape parameter, which must be positive.
scale The scale parameter, which must be positive.
References Meta.Numerics.Statistics.Distributions.GammaDistribution.a, Meta.Numerics.Statistics.Distributions.GammaDistribution.ga, Meta.Numerics.Functions.AdvancedMath.Gamma(), Meta.Numerics.Statistics.Distributions.GammaDistribution.gammaRng, Meta.Numerics.Functions.AdvancedMath.LogGamma(), and Meta.Numerics.Statistics.Distributions.GammaDistribution.s.
Referenced by Meta.Numerics.Statistics.Distributions.GammaDistribution.FitToSample().
GammaDistribution() [2/2]
Meta.Numerics.Statistics.Distributions.GammaDistribution.GammaDistribution (double shape) inline
Initializes a new instance of the standard Gamma distribution.
Parameters
shape The shape parameter, which must be positive.
Member Function Documentation
ProbabilityDensity()
override double Meta.Numerics.Statistics.Distributions.GammaDistribution.ProbabilityDensity (double x) inline virtual
Returns the probability density at the given point.
Implements Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.GammaDistribution.a, Meta.Numerics.Statistics.Distributions.GammaDistribution.ga, and Meta.Numerics.Statistics.Distributions.GammaDistribution.s.
Referenced by Test.DistributionTest.DistributionUnitarityIntegral(), and Meta.Numerics.Statistics.Distributions.ChiSquaredDistribution.ProbabilityDensity().
LeftProbability()
override double Meta.Numerics.Statistics.Distributions.GammaDistribution.LeftProbability (double x) inline virtual
Returns the cumulative probability to the left of (below) the given point.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.GammaDistribution.a, Meta.Numerics.Functions.AdvancedMath.LeftRegularizedGamma(), and Meta.Numerics.Statistics.Distributions.GammaDistribution.s.
Referenced by Meta.Numerics.Statistics.Distributions.ChiSquaredDistribution.LeftProbability().
RightProbability()
override double Meta.Numerics.Statistics.Distributions.GammaDistribution.RightProbability (double x) inline virtual
Return the cumulative probability to the right of (above) the given point.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.GammaDistribution.a, Meta.Numerics.Functions.AdvancedMath.RightRegularizedGamma(), and Meta.Numerics.Statistics.Distributions.GammaDistribution.s.
Referenced by Meta.Numerics.Statistics.Distributions.ChiSquaredDistribution.RightProbability().
Moment()
override double Meta.Numerics.Statistics.Distributions.GammaDistribution.Moment (int r) inline virtual
Computes a raw moment of the distribution.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.GammaDistribution.a, and Meta.Numerics.Statistics.Distributions.GammaDistribution.s.
MomentAboutMean()
override double Meta.Numerics.Statistics.Distributions.GammaDistribution.MomentAboutMean (int r) inline virtual
Computes a central moment of the distribution.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.GammaDistribution.a, and Meta.Numerics.Statistics.Distributions.GammaDistribution.s.
Cumulant()
override double Meta.Numerics.Statistics.Distributions.GammaDistribution.Cumulant (int r) inline virtual
Computes a cumulant of the distribution.
Reimplemented from Meta.Numerics.Statistics.Distributions.UnivariateDistribution.
References Meta.Numerics.Statistics.Distributions.GammaDistribution.a, Meta.Numerics.Functions.AdvancedIntegerMath.Factorial(), Meta.Numerics.MoreMath.Pow(), and Meta.Numerics.Statistics.Distributions.GammaDistribution.s.
ApproximateProbit()
static double Meta.Numerics.Statistics.Distributions.GammaDistribution.ApproximateProbit (double P) inline static private
Referenced by Meta.Numerics.Statistics.Distributions.GammaDistribution.ApproximateInverseStandardGamma().
ApproximateInverseStandardGamma()
double Meta.Numerics.Statistics.Distributions.GammaDistribution.ApproximateInverseStandardGamma (double P, double Q) inline private
References Meta.Numerics.Statistics.Distributions.GammaDistribution.a, Meta.Numerics.Statistics.Distributions.GammaDistribution.ApproximateProbit(), Meta.Numerics.Statistics.Distributions.GammaDistribution.ga, and Meta.Numerics.MoreMath.Pow().
Referenced by Meta.Numerics.Statistics.Distributions.GammaDistribution.InverseLeftStandardGamma().
InverseLeftStandardGamma()
double Meta.Numerics.Statistics.Distributions.GammaDistribution.InverseLeftStandardGamma (double P) inline private
References Meta.Numerics.Statistics.Distributions.GammaDistribution.a, Meta.Numerics.Statistics.Distributions.GammaDistribution.ApproximateInverseStandardGamma(), Meta.Numerics.Statistics.Distributions.GammaDistribution.ga, and Meta.Numerics.Functions.AdvancedMath.LeftRegularizedGamma().
Referenced by Meta.Numerics.Statistics.Distributions.GammaDistribution.InverseLeftProbability().
InverseLeftProbability()
override double Meta.Numerics.Statistics.Distributions.GammaDistribution.InverseLeftProbability (double P) inline virtual
Returns the point at which the cumulative distribution function attains a given value.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.GammaDistribution.InverseLeftStandardGamma(), and Meta.Numerics.Statistics.Distributions.GammaDistribution.s.
Referenced by Meta.Numerics.Statistics.Distributions.ChiSquaredDistribution.InverseLeftProbability().
GetRandomValue()
override double Meta.Numerics.Statistics.Distributions.GammaDistribution.GetRandomValue (Random rng) inline virtual
Returns a random value.
Reimplemented from Meta.Numerics.Statistics.Distributions.Distribution.
References Meta.Numerics.Statistics.Distributions.GammaDistribution.gammaRng, and Meta.Numerics.Statistics.Distributions.GammaDistribution.s.
FitToSample()
static FitResult Meta.Numerics.Statistics.Distributions.GammaDistribution.FitToSample (Sample sample) inline static
Computes the Gamma distribution that best fits the given sample.
Parameters
sample The sample to fit.
Returns
The best fit parameters.
The returned fit parameters are the ShapeParameter and ScaleParameter, in that order. These are the same parameters, in the same order, that are required by the GammaDistribution(double,double) constructor to specify a new Gamma distribution.
Exceptions
ArgumentNullException sample is null.
InvalidOperationException sample contains non-positive values.
InsufficientDataException sample contains fewer than three values.
References Meta.Numerics.Statistics.Sample.Count, Meta.Numerics.Analysis.FunctionMath.FindZero(), Meta.Numerics.Statistics.Distributions.GammaDistribution.GammaDistribution(), Meta.Numerics.Functions.AdvancedMath.Psi(), and Meta.Numerics.Statistics.Distributions.GammaDistribution.s.
Referenced by Test.SampleTest.GammaFit(), and Test.SampleTest.GammaFitUncertainty().
Member Data Documentation
a
readonly double Meta.Numerics.Statistics.Distributions.GammaDistribution.a private
Referenced by Meta.Numerics.Statistics.Distributions.GammaDistribution.ApproximateInverseStandardGamma(), Meta.Numerics.Statistics.Distributions.GammaDistribution.Cumulant(), Meta.Numerics.Statistics.Distributions.GammaDistribution.GammaDistribution(), Meta.Numerics.Statistics.Distributions.GammaDistribution.InverseLeftStandardGamma(), Meta.Numerics.Statistics.Distributions.GammaDistribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.GammaDistribution.Moment(), Meta.Numerics.Statistics.Distributions.GammaDistribution.MomentAboutMean(), Meta.Numerics.Statistics.Distributions.GammaDistribution.ProbabilityDensity(), and Meta.Numerics.Statistics.Distributions.GammaDistribution.RightProbability().
s
readonly double Meta.Numerics.Statistics.Distributions.GammaDistribution.s private
Referenced by Meta.Numerics.Statistics.Distributions.GammaDistribution.Cumulant(), Meta.Numerics.Statistics.Distributions.GammaDistribution.FitToSample(), Meta.Numerics.Statistics.Distributions.GammaDistribution.GammaDistribution(), Meta.Numerics.Statistics.Distributions.GammaDistribution.GetRandomValue(), Meta.Numerics.Statistics.Distributions.GammaDistribution.InverseLeftProbability(), Meta.Numerics.Statistics.Distributions.GammaDistribution.LeftProbability(), Meta.Numerics.Statistics.Distributions.GammaDistribution.Moment(), Meta.Numerics.Statistics.Distributions.GammaDistribution.MomentAboutMean(), Meta.Numerics.Statistics.Distributions.GammaDistribution.ProbabilityDensity(), and Meta.Numerics.Statistics.Distributions.GammaDistribution.RightProbability().
ga
readonly double Meta.Numerics.Statistics.Distributions.GammaDistribution.ga private
Referenced by Meta.Numerics.Statistics.Distributions.GammaDistribution.ApproximateInverseStandardGamma(), Meta.Numerics.Statistics.Distributions.GammaDistribution.GammaDistribution(), Meta.Numerics.Statistics.Distributions.GammaDistribution.InverseLeftStandardGamma(), and Meta.Numerics.Statistics.Distributions.GammaDistribution.ProbabilityDensity().
gammaRng
readonly IDeviateGenerator Meta.Numerics.Statistics.Distributions.GammaDistribution.gammaRng private
Referenced by Meta.Numerics.Statistics.Distributions.GammaDistribution.GammaDistribution(), and Meta.Numerics.Statistics.Distributions.GammaDistribution.GetRandomValue().
Property Documentation
ShapeParameter
double Meta.Numerics.Statistics.Distributions.GammaDistribution.ShapeParameter get
Gets the shape parameter for the distribution.
Referenced by Test.DistributionTest.DistributionVarianceIntegral().
ScaleParameter
double Meta.Numerics.Statistics.Distributions.GammaDistribution.ScaleParameter get
Gets the scale parameter for the distribution.
Support
override Interval Meta.Numerics.Statistics.Distributions.GammaDistribution.Support get
Referenced by Test.DistributionTest.DistributionUnitarityIntegral().
Mean
override double Meta.Numerics.Statistics.Distributions.GammaDistribution.Mean get
Variance
override double Meta.Numerics.Statistics.Distributions.GammaDistribution.Variance get
Skewness
override double Meta.Numerics.Statistics.Distributions.GammaDistribution.Skewness get
ExcessKurtosis
override double Meta.Numerics.Statistics.Distributions.GammaDistribution.ExcessKurtosis get
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Numerics/Statistics/Distributions/GammaDistribution.cs