Doc: IGLib EXTENDED: NeuronDotNet.Core.Initializers.NguyenWidrowFunction Class Reference
NeuronDotNet.Core.Initializers.NguyenWidrowFunction Class Reference
An IInitializer using Nguyen Widrow function.
Public Member Functions
NguyenWidrowFunction ()
Creates a new NGuyen Widrow Initialization function
NguyenWidrowFunction (double outputRange)
Creates a new NGuyen Widrow function using the given output range
NguyenWidrowFunction (SerializationInfo info, StreamingContext context)
Deserialization Constructor
void GetObjectData (SerializationInfo info, StreamingContext context)
Populates the serialization info with the data needed to serialize the initializer
void Initialize (ActivationLayer activationLayer)
Initializes bias values of activation neurons in the activation layer.
void Initialize (BackpropagationConnector connector)
Initializes weights of all backpropagation synapses in the backpropagation connector.
void Initialize (KohonenConnector connector)
Initializes weights of all spatial synapses in a Kohonen connector.
Properties
double OutputRange [get]
Gets the output range
Private Member Functions
double NGuyenWidrowFactor (int inputNeuronCount, int hiddenNeuronCount)
Private helper method to calculate Nguyen-Widrow factor
Private Attributes
readonly double outputRange
Detailed Description
An IInitializer using Nguyen Widrow function.
Constructor & Destructor Documentation
NguyenWidrowFunction() [1/3]
NeuronDotNet.Core.Initializers.NguyenWidrowFunction.NguyenWidrowFunction () inline
Creates a new NGuyen Widrow Initialization function
NguyenWidrowFunction() [2/3]
NeuronDotNet.Core.Initializers.NguyenWidrowFunction.NguyenWidrowFunction (double outputRange) inline
Creates a new NGuyen Widrow function using the given output range
Parameters
outputRange the range of values, that output of a neuron can take (i.e. maximum minus minimum)
References NeuronDotNet.Core.Initializers.NguyenWidrowFunction.outputRange.
NguyenWidrowFunction() [3/3]
NeuronDotNet.Core.Initializers.NguyenWidrowFunction.NguyenWidrowFunction (SerializationInfo info, StreamingContext context) inline
Deserialization Constructor
Parameters
info Serialization information to deserialize and obtain the data
context Serialization context to use
Exceptions
ArgumentNullException If info is null
References NeuronDotNet.Core.Helper.ValidateNotNull().
Member Function Documentation
GetObjectData()
void NeuronDotNet.Core.Initializers.NguyenWidrowFunction.GetObjectData (SerializationInfo info, StreamingContext context) inline
Populates the serialization info with the data needed to serialize the initializer
Parameters
info The serialization info to populate the data with
context The serialization context to use
Exceptions
ArgumentNullException If info is null
References NeuronDotNet.Core.Initializers.NguyenWidrowFunction.outputRange, and NeuronDotNet.Core.Helper.ValidateNotNull().
Initialize() [1/3]
void NeuronDotNet.Core.Initializers.NguyenWidrowFunction.Initialize (ActivationLayer activationLayer) inline
Initializes bias values of activation neurons in the activation layer.
Parameters
activationLayer The activation layer to initialize
Exceptions
ArgumentNullException If activationLayer is null
Implements NeuronDotNet.Core.IInitializer.
References NeuronDotNet.Core.ILayer.NeuronCount, NeuronDotNet.Core.Initializers.NguyenWidrowFunction.NGuyenWidrowFactor(), NeuronDotNet.Core.IConnector.TargetLayer, and NeuronDotNet.Core.Helper.ValidateNotNull().
Initialize() [2/3]
void NeuronDotNet.Core.Initializers.NguyenWidrowFunction.Initialize (BackpropagationConnector connector) inline
Initializes weights of all backpropagation synapses in the backpropagation connector.
Parameters
connector The backpropagation connector to initialize.
Exceptions
ArgumentNullException If connector is null
Implements NeuronDotNet.Core.IInitializer.
References NeuronDotNet.Core.Initializers.NguyenWidrowFunction.NGuyenWidrowFactor(), NeuronDotNet.Core.Connector< TSourceLayer, TTargetLayer, TSynapse >.SourceLayer, NeuronDotNet.Core.Connector< TSourceLayer, TTargetLayer, TSynapse >.SynapseCount, NeuronDotNet.Core.Connector< TSourceLayer, TTargetLayer, TSynapse >.TargetLayer, NeuronDotNet.Core.Helper.ValidateNotNull(), and NeuronDotNet.Core.Backpropagation.BackpropagationSynapse.Weight.
Initialize() [3/3]
void NeuronDotNet.Core.Initializers.NguyenWidrowFunction.Initialize (KohonenConnector connector) inline
Initializes weights of all spatial synapses in a Kohonen connector.
Parameters
connector The Kohonen connector to initialize.
Exceptions
ArgumentNullException If connector is null
Implements NeuronDotNet.Core.IInitializer.
References NeuronDotNet.Core.Initializers.NguyenWidrowFunction.NGuyenWidrowFactor(), NeuronDotNet.Core.Connector< TSourceLayer, TTargetLayer, TSynapse >.SourceLayer, NeuronDotNet.Core.Connector< TSourceLayer, TTargetLayer, TSynapse >.SynapseCount, NeuronDotNet.Core.Connector< TSourceLayer, TTargetLayer, TSynapse >.TargetLayer, NeuronDotNet.Core.Helper.ValidateNotNull(), and NeuronDotNet.Core.SOM.KohonenSynapse.Weight.
NGuyenWidrowFactor()
double NeuronDotNet.Core.Initializers.NguyenWidrowFunction.NGuyenWidrowFactor (int inputNeuronCount, int hiddenNeuronCount) inline private
Private helper method to calculate Nguyen-Widrow factor
Parameters
inputNeuronCount Number of input neurons
hiddenNeuronCount Number of hidden neurons
Returns
The Nguyen-Widrow factor
References NeuronDotNet.Core.Initializers.NguyenWidrowFunction.outputRange.
Referenced by NeuronDotNet.Core.Initializers.NguyenWidrowFunction.Initialize().
Member Data Documentation
outputRange
readonly double NeuronDotNet.Core.Initializers.NguyenWidrowFunction.outputRange private
Referenced by NeuronDotNet.Core.Initializers.NguyenWidrowFunction.GetObjectData(), NeuronDotNet.Core.Initializers.NguyenWidrowFunction.NGuyenWidrowFactor(), and NeuronDotNet.Core.Initializers.NguyenWidrowFunction.NguyenWidrowFunction().
Property Documentation
OutputRange
double NeuronDotNet.Core.Initializers.NguyenWidrowFunction.OutputRange get
Gets the output range
The range of values, that network output takes
The documentation for this class was generated from the following file:
shelldev/lib/externalextended/NeuronDotNetGPL/source/Core/Initializers/NguyenWidrowFunction.cs