Doc: IGLib EXTENDED: IG.Neural.Forms.Old.NeuralParametricDemoTestOld Class Reference
IG.Neural.Forms.Old.NeuralParametricDemoTestOld Class Reference
Class for testing Layout designs.
Public Member Functions
NeuralParametricDemoTestOld (INeuralModel model)
Construct a new window for ANN based predictions, with the model specified.
NeuralParametricDemoTestOld (string neuralDirectoryPath)
NeuralParametricDemoTestOld ()
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
void SetNeuralScriptShellPath (string path)
Sets the directory for
NeuralParametricDemoTestOld (INeuralModel model)
Construct a new window for ANN based predictions, with the model specified.
NeuralParametricDemoTestOld (string neuralDirectoryPath)
NeuralParametricDemoTestOld ()
void SetNeuralModel (INeuralModel model)
Sets the ANN-based model used by the current form.
void SetNeuralScriptShellPath (string path)
Sets the directory for
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
string _neuralScriptShellPath = null
NeuralParametricDemoAboutWindowOld11 _aboutWindow
NeuralParametricDemoAboutWindow _aboutWindow
Properties
INeuralModel NeuralModel [get, protected set]
Neural network - based model.
string NeuralScriptShellPath [get, protected set]
Path of the working directory for the ANN-based approximation approximation scripts.
INeuralApproximator TrainedNetwork [get]
Traint artificial neural network.
InputOutputDataDefiniton NeuralDataDefinition [get]
Neural data definition.
NeuralParametricDemoAboutWindowOld11 AboutWindow [get]
Window that shows information about the software.
NeuralParametricDemoAboutWindow AboutWindow [get]
Window that shows information about the software.
Private Member Functions
void NeuralParametricDemo_HelpEventHandlers (object sender, KeyEventArgs e)
void NeuralParametricDemo_KeyUp (object sender, KeyEventArgs e)
void tabControl_KeyUp (object sender, KeyEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void NeuralParametricDemo_HelpEventHandlers (object sender, KeyEventArgs e)
void NeuralParametricDemo_KeyUp (object sender, KeyEventArgs e)
void tabControl_KeyUp (object sender, KeyEventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
INeuralModel _neuralModel
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.TextBox tbInfoLine
System.Windows.Forms.TabControl tabControl
System.Windows.Forms.TabPage tpPrediction
System.Windows.Forms.TabPage tpParmTest
Forms.NeuralPredictionControl neuralPredictionControl1
NeuralParametricTestOld neuralParametricTest1
Detailed Description
Class for testing Layout designs.
$A Igor Apr13;
Constructor & Destructor Documentation
NeuralParametricDemoTestOld() [1/6]
IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemoTestOld (INeuralModel model) inline
Construct a new window for ANN based predictions, with the model specified.
Parameters
model ANN - base model, contains input and output data definitions and
References IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralModel.
NeuralParametricDemoTestOld() [2/6]
IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemoTestOld (string neuralDirectoryPath) inline
References IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralScriptShellPath.
NeuralParametricDemoTestOld() [3/6]
IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemoTestOld () inline
References IG.Neural.Forms.Old.NeuralParametricDemoTestOld.InitializeComponent().
NeuralParametricDemoTestOld() [4/6]
IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemoTestOld (INeuralModel model) inline
Construct a new window for ANN based predictions, with the model specified.
Parameters
model ANN - base model, contains input and output data definitions and
References IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralModel.
NeuralParametricDemoTestOld() [5/6]
IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemoTestOld (string neuralDirectoryPath) inline
References IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralScriptShellPath.
NeuralParametricDemoTestOld() [6/6]
IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemoTestOld () inline
References IG.Neural.Forms.Old.NeuralParametricDemoTestOld.InitializeComponent().
Member Function Documentation
SetNeuralModel() [1/2]
void IG.Neural.Forms.Old.NeuralParametricDemoTestOld.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
References IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralModel.
SetNeuralScriptShellPath() [1/2]
void IG.Neural.Forms.Old.NeuralParametricDemoTestOld.SetNeuralScriptShellPath (string path) inline
Sets the directory for
Parameters
path
References IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralScriptShellPath.
NeuralParametricDemo_HelpEventHandlers() [1/2]
void IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemo_HelpEventHandlers (object sender, KeyEventArgs e) inline private
References IG.Neural.Forms.Old.NeuralParametricDemoTestOld.AboutWindow, and IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11.ShowHelp().
Referenced by IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemo_KeyUp(), and IG.Neural.Forms.Old.NeuralParametricDemoTestOld.tabControl_KeyUp().
NeuralParametricDemo_KeyUp() [1/2]
void IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemo_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemo_HelpEventHandlers().
Referenced by IG.Neural.Forms.Old.NeuralParametricDemoTestOld.InitializeComponent().
tabControl_KeyUp() [1/2]
void IG.Neural.Forms.Old.NeuralParametricDemoTestOld.tabControl_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemo_HelpEventHandlers().
Referenced by IG.Neural.Forms.Old.NeuralParametricDemoTestOld.InitializeComponent().
Dispose() [1/2]
override void IG.Neural.Forms.Old.NeuralParametricDemoTestOld.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.Old.NeuralParametricDemoTestOld.components.
InitializeComponent() [1/2]
void IG.Neural.Forms.Old.NeuralParametricDemoTestOld.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemo_KeyUp(), IG.Neural.Forms.Old.NeuralParametricDemoTestOld.neuralParametricTest1, IG.Neural.Forms.Old.NeuralParametricDemoTestOld.neuralPredictionControl1, IG.Neural.Forms.Old.NeuralParametricDemoTestOld.tabControl, IG.Neural.Forms.Old.NeuralParametricDemoTestOld.tabControl_KeyUp(), IG.Neural.Forms.Old.NeuralParametricDemoTestOld.tbInfoLine, IG.Neural.Forms.Old.NeuralParametricDemoTestOld.tpParmTest, and IG.Neural.Forms.Old.NeuralParametricDemoTestOld.tpPrediction.
Referenced by IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemoTestOld().
SetNeuralModel() [2/2]
void IG.Neural.Forms.Old.NeuralParametricDemoTestOld.SetNeuralModel (INeuralModel model) inline
Sets the ANN-based model used by the current form.
Parameters
model ANN based model that is set.
Because of this dedicated method, the setter of the NeuralModel property can be non-public.
References IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralModel.
SetNeuralScriptShellPath() [2/2]
void IG.Neural.Forms.Old.NeuralParametricDemoTestOld.SetNeuralScriptShellPath (string path) inline
Sets the directory for
Parameters
path
References IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralScriptShellPath.
NeuralParametricDemo_HelpEventHandlers() [2/2]
void IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemo_HelpEventHandlers (object sender, KeyEventArgs e) inline private
References IG.Neural.Forms.Old.NeuralParametricDemoTestOld.AboutWindow, and IG.Neural.Applications.NeuralParametricDemoAboutWindowOld11.ShowHelp().
NeuralParametricDemo_KeyUp() [2/2]
void IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemo_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemo_HelpEventHandlers().
tabControl_KeyUp() [2/2]
void IG.Neural.Forms.Old.NeuralParametricDemoTestOld.tabControl_KeyUp (object sender, KeyEventArgs e) inline private
References IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemo_HelpEventHandlers().
Dispose() [2/2]
override void IG.Neural.Forms.Old.NeuralParametricDemoTestOld.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.Old.NeuralParametricDemoTestOld.components.
InitializeComponent() [2/2]
void IG.Neural.Forms.Old.NeuralParametricDemoTestOld.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemo_KeyUp(), IG.Neural.Forms.Old.NeuralParametricDemoTestOld.neuralParametricTest1, IG.Neural.Forms.Old.NeuralParametricDemoTestOld.neuralPredictionControl1, IG.Neural.Forms.Old.NeuralParametricDemoTestOld.tabControl, IG.Neural.Forms.Old.NeuralParametricDemoTestOld.tabControl_KeyUp(), IG.Neural.Forms.Old.NeuralParametricDemoTestOld.tbInfoLine, IG.Neural.Forms.Old.NeuralParametricDemoTestOld.tpParmTest, and IG.Neural.Forms.Old.NeuralParametricDemoTestOld.tpPrediction.
Member Data Documentation
_neuralModel
INeuralModel IG.Neural.Forms.Old.NeuralParametricDemoTestOld._neuralModel private
_neuralScriptShellPath
string IG.Neural.Forms.Old.NeuralParametricDemoTestOld._neuralScriptShellPath = null protected
_aboutWindow [1/2]
NeuralParametricDemoAboutWindowOld11 IG.Neural.Forms.Old.NeuralParametricDemoTestOld._aboutWindow protected
components
System ComponentModel IContainer IG.Neural.Forms.Old.NeuralParametricDemoTestOld.components = null private
Required designer variable.
Referenced by IG.Neural.Forms.Old.NeuralParametricDemoTestOld.Dispose().
tbInfoLine
System Windows Forms TextBox IG.Neural.Forms.Old.NeuralParametricDemoTestOld.tbInfoLine private
Referenced by IG.Neural.Forms.Old.NeuralParametricDemoTestOld.InitializeComponent().
tabControl
System Windows Forms TabControl IG.Neural.Forms.Old.NeuralParametricDemoTestOld.tabControl private
Referenced by IG.Neural.Forms.Old.NeuralParametricDemoTestOld.InitializeComponent().
tpPrediction
System Windows Forms TabPage IG.Neural.Forms.Old.NeuralParametricDemoTestOld.tpPrediction private
Referenced by IG.Neural.Forms.Old.NeuralParametricDemoTestOld.InitializeComponent().
tpParmTest
System Windows Forms TabPage IG.Neural.Forms.Old.NeuralParametricDemoTestOld.tpParmTest private
Referenced by IG.Neural.Forms.Old.NeuralParametricDemoTestOld.InitializeComponent().
neuralPredictionControl1
Forms NeuralPredictionControl IG.Neural.Forms.Old.NeuralParametricDemoTestOld.neuralPredictionControl1 private
Referenced by IG.Neural.Forms.Old.NeuralParametricDemoTestOld.InitializeComponent().
neuralParametricTest1
NeuralParametricTestOld IG.Neural.Forms.Old.NeuralParametricDemoTestOld.neuralParametricTest1 private
Referenced by IG.Neural.Forms.Old.NeuralParametricDemoTestOld.InitializeComponent().
_aboutWindow [2/2]
NeuralParametricDemoAboutWindow IG.Neural.Forms.Old.NeuralParametricDemoTestOld._aboutWindow protected
Property Documentation
NeuralModel
INeuralModel IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralModel get protected set
Neural network - based model.
Contains data definition and trained neural network approximator.
Referenced by IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemoTestOld(), and IG.Neural.Forms.Old.NeuralParametricDemoTestOld.SetNeuralModel().
NeuralScriptShellPath
string IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralScriptShellPath get protected set
Path of the working directory for the ANN-based approximation approximation scripts.
Referenced by IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemoTestOld(), and IG.Neural.Forms.Old.NeuralParametricDemoTestOld.SetNeuralScriptShellPath().
TrainedNetwork
INeuralApproximator IG.Neural.Forms.Old.NeuralParametricDemoTestOld.TrainedNetwork get
Traint artificial neural network.
NeuralDataDefinition
InputOutputDataDefiniton IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralDataDefinition get
Neural data definition.
AboutWindow [1/2]
NeuralParametricDemoAboutWindowOld11 IG.Neural.Forms.Old.NeuralParametricDemoTestOld.AboutWindow get
Window that shows information about the software.
Help is also accessible through that window.
Referenced by IG.Neural.Forms.Old.NeuralParametricDemoTestOld.NeuralParametricDemo_HelpEventHandlers().
AboutWindow [2/2]
NeuralParametricDemoAboutWindow IG.Neural.Forms.Old.NeuralParametricDemoTestOld.AboutWindow get
Window that shows information about the software.
Help is also accessible through that window.
The documentation for this class was generated from the following files:
shelldev/extensions/ExtAppAnnApp/FormsOld/NeuralParametricDemoTestOld.cs
shelldev/extensions/ExtAppAnnApp/FormsOld/NeuralParametricDemoTestOld.Designer.cs