Doc: IGLib EXTENDED: CShell.Framework.Services.WorkspaceActivator Class Reference
CShell.Framework.Services.WorkspaceActivator Class Reference
Public Member Functions
WorkspaceActivator (IEventAggregator eventAggregator)
void Activate ()
void Deactivate (bool close)
void Handle (WorkspaceOpenedEventArgs message)
void Handle (WorkspaceClosingEventArgs message)
Properties
bool IsActive [get]
Events
EventHandler< ActivationEventArgs > Activated
EventHandler< DeactivationEventArgs > AttemptingDeactivation
EventHandler< DeactivationEventArgs > Deactivated
Private Attributes
bool isActive = false
Constructor & Destructor Documentation
WorkspaceActivator()
CShell.Framework.Services.WorkspaceActivator.WorkspaceActivator (IEventAggregator eventAggregator) inline
Member Function Documentation
Activate()
void CShell.Framework.Services.WorkspaceActivator.Activate () inline
References CShell.Framework.Services.WorkspaceActivator.Activated, and CShell.Framework.Services.WorkspaceActivator.isActive.
Referenced by CShell.Framework.Services.WorkspaceActivator.Handle().
Deactivate()
void CShell.Framework.Services.WorkspaceActivator.Deactivate (bool close) inline
References CShell.Framework.Services.WorkspaceActivator.AttemptingDeactivation, CShell.Framework.Services.WorkspaceActivator.Deactivated, and CShell.Framework.Services.WorkspaceActivator.isActive.
Referenced by CShell.Framework.Services.WorkspaceActivator.Handle().
Handle() [1/2]
void CShell.Framework.Services.WorkspaceActivator.Handle (WorkspaceOpenedEventArgs message) inline
References CShell.Framework.Services.WorkspaceActivator.Activate().
Handle() [2/2]
void CShell.Framework.Services.WorkspaceActivator.Handle (WorkspaceClosingEventArgs message) inline
References CShell.Framework.Services.WorkspaceActivator.Deactivate().
Member Data Documentation
isActive
bool CShell.Framework.Services.WorkspaceActivator.isActive = false private
Referenced by CShell.Framework.Services.WorkspaceActivator.Activate(), and CShell.Framework.Services.WorkspaceActivator.Deactivate().
Property Documentation
IsActive
bool CShell.Framework.Services.WorkspaceActivator.IsActive get
Event Documentation
Activated
EventHandler<ActivationEventArgs> CShell.Framework.Services.WorkspaceActivator.Activated
Referenced by CShell.Framework.Services.WorkspaceActivator.Activate().
AttemptingDeactivation
EventHandler<DeactivationEventArgs> CShell.Framework.Services.WorkspaceActivator.AttemptingDeactivation
Referenced by CShell.Framework.Services.WorkspaceActivator.Deactivate().
Deactivated
EventHandler<DeactivationEventArgs> CShell.Framework.Services.WorkspaceActivator.Deactivated
Referenced by CShell.Framework.Services.WorkspaceActivator.Deactivate().
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShellCore/Framework/Services/WorkspaceActivator.cs