Doc: IGLib EXTENDED: NeuronDotNet.Core.Backpropagation.BackpropagationNetwork Class Reference
NeuronDotNet.Core.Backpropagation.BackpropagationNetwork Class Reference
This class extends a Network and represents a Backpropagation neural network.
Public Member Functions
BackpropagationNetwork (ActivationLayer inputLayer, ActivationLayer outputLayer)
Creates a new Back Propagation Network, with the specified input and output layers. (You are required to connect all layers using appropriate synapses, before using the constructor. Any changes made to the structure of the network after its creation may lead to complete malfunctioning)
BackpropagationNetwork (SerializationInfo info, StreamingContext context)
Deserialization Constructor
override void Learn (TrainingSample trainingSample, int currentIteration, int trainingEpochs)
Public Member Functions inherited from NeuronDotNet.Core.Network
Network (SerializationInfo info, StreamingContext context)
Deserialization constructor. It is assumed that the serialization info provided contains valid data.
virtual void GetObjectData (SerializationInfo info, StreamingContext context)
Populates the serialization info with the data necessary to serialize the network.
void SetLearningRate (double learningRate)
Sets the learning rate to the given value. All layers in the network will use this constant value as learning rate during the learning process.
void SetLearningRate (double initialLearningRate, double finalLearningRate)
Sets the initial and final values for learning rate. During the learning process, all layers in the network will use an efeective learning rate which varies uniformly from the initial value to the final value.
void SetLearningRate (ILearningRateFunction learningRateFunction)
Sets the learning rate function.
virtual void Initialize ()
Initializes all layers and connectors and makes them ready to undergo fresh training.
virtual double[] Run (double[] input)
Runs the neural network against the given input
virtual void Learn (TrainingSet trainingSet, int trainingEpochs)
Trains the neural network for the given training set (Batch Training)
void StopLearning ()
If the network is currently learning, this method stops the learning.
Protected Member Functions
override void OnBeginEpoch (int currentIteration, TrainingSet trainingSet)
Invokes BeginEpochEvent
override void OnEndEpoch (int currentIteration, TrainingSet trainingSet)
Invokes EndEpochEvent
override void LearnSample (TrainingSample trainingSample, int currentIteration, int trainingEpochs)
A protected helper function used to train single learning sample
Protected Member Functions inherited from NeuronDotNet.Core.Network
Network (ILayer inputLayer, ILayer outputLayer, TrainingMethod trainingMethod)
Creates a new neural network
virtual void OnBeginSample (int currentIteration, TrainingSample currentSample)
Invokes BeginSampleEvent
virtual void OnEndSample (int currentIteration, TrainingSample currentSample)
Invokes BeginSampleEvent
Properties
double? MeanSquaredError [get]
Gets the value of mean squared error
Properties inherited from NeuronDotNet.Core.Network
ILayer InputLayer [get]
Gets the input layer of the network
ILayer OutputLayer [get]
Gets the output layer of the network
int LayerCount [get]
Gets the number of layers in the network.
IEnumerable< ILayer > Layers [get]
Exposes an enumerator to iterate over layers in the network.
ILayer this[int index] [get]
Layer Indexer
int ConnectorCount [get]
Gets the number of connectors in the network.
IEnumerable< IConnector > Connectors [get]
Exposes an enumerator to iterate over connectors in the network.
double JitterNoiseLimit [get, set]
Gets or sets maximum absolute limit to the jitter noise
int JitterEpoch [get, set]
Gets or sets the jitter epoch
Properties inherited from NeuronDotNet.Core.INetwork
ILayer InputLayer [get]
Gets the input layer of the network
ILayer OutputLayer [get]
Gets the output layer of the network
int LayerCount [get]
Gets the number of layers in the network.
IEnumerable< ILayer > Layers [get]
Exposes an enumerator to iterate over layers in the network.
ILayer this[int index] [get]
Layer Indexer
int ConnectorCount [get]
Gets the number of connectors in the network.
IEnumerable< IConnector > Connectors [get]
Exposes an enumerator to iterate over connectors in the network.
double JitterNoiseLimit [get, set]
Gets or sets maximum absolute limit to the jitter noise
int JitterEpoch [get, set]
Gets or sets the jitter epoch
Private Attributes
double meanSquaredError
bool isValidMSE
Additional Inherited Members
Protected Attributes inherited from NeuronDotNet.Core.Network
readonly ILayer inputLayer
The input layer
readonly ILayer outputLayer
The output layer
readonly IList< ILayer > layers
List of layers in the network, ordered acyclically (first layer being input layer and last one being output layer)
readonly IList< IConnector > connectors
A list of connectors between layers.
readonly TrainingMethod trainingMethod
The method of training used to train the network
int jitterEpoch
Epoch(interval) at which Jitter operation is performed. If this value is zero, not jitter is performed.
double jitterNoiseLimit
Maximum absolute limit to the random noise added during Jitter operation
bool isStopping = false
This flag is set to true, whenever training needs to be stopped immmediately
Events inherited from NeuronDotNet.Core.Network
TrainingEpochEventHandler BeginEpochEvent
This event is invoked during the commencement of a new training iteration during 'Batch training' mode.
TrainingSampleEventHandler BeginSampleEvent
This event is invoked whenever the network is about to learn a training sample.
TrainingSampleEventHandler EndSampleEvent
This event is invoked whenever the network has successfully completed learning a training sample.
TrainingEpochEventHandler EndEpochEvent
This event is invoked whenever a training iteration is successfully completed during 'Batch training' mode.
Events inherited from NeuronDotNet.Core.INetwork
TrainingEpochEventHandler BeginEpochEvent
This event is invoked during the commencement of a new training iteration during 'Batch training' mode.
TrainingSampleEventHandler BeginSampleEvent
This event is invoked whenever the network is about to learn a training sample.
TrainingSampleEventHandler EndSampleEvent
This event is invoked whenever the network has successfully completed learning a training sample.
TrainingEpochEventHandler EndEpochEvent
This event is invoked whenever a training iteration is successfully completed during 'Batch training' mode.
Detailed Description
This class extends a Network and represents a Backpropagation neural network.
Constructor & Destructor Documentation
BackpropagationNetwork() [1/2]
NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.BackpropagationNetwork (ActivationLayer inputLayer, ActivationLayer outputLayer) inline
Creates a new Back Propagation Network, with the specified input and output layers. (You are required to connect all layers using appropriate synapses, before using the constructor. Any changes made to the structure of the network after its creation may lead to complete malfunctioning)
Parameters
inputLayer The input layer
outputLayer The output layer
Exceptions
ArgumentNullException If inputLayer or outputLayer is null
References NeuronDotNet.Core.Supervised.
BackpropagationNetwork() [2/2]
NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.BackpropagationNetwork (SerializationInfo info, StreamingContext context) inline
Deserialization Constructor
Parameters
info Serialization information to deserialize and obtain the data
context Serialization context to use
Exceptions
ArgumentNullException If info is null
Member Function Documentation
Learn()
override void NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.Learn (TrainingSample trainingSample, int currentIteration, int trainingEpochs) inline virtual
Trains the network for the given training sample (Online training mode). Note that this method trains the sample only once irrespective of the values of currentIteration and trainingEpochs. Those arguments are just used to adjust training parameters which are dependent on training progress.
Parameters
trainingSample Training sample to use
currentIteration Current training epoch
trainingEpochs Number of training epochs
Exceptions
ArgumentNullException If trainingSample is null
ArgumentException If trainingEpochs is not positive, or if currentIteration is negative or if currentIteration is less than trainingEpochs
Reimplemented from NeuronDotNet.Core.Network.
References NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.isValidMSE, and NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.meanSquaredError.
OnBeginEpoch()
override void NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.OnBeginEpoch (int currentIteration, TrainingSet trainingSet) inline protected virtual
Invokes BeginEpochEvent
Parameters
currentIteration Current training iteration
trainingSet Training set which is about to be trained
Reimplemented from NeuronDotNet.Core.Network.
References NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.isValidMSE, and NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.meanSquaredError.
Referenced by IG.Neural.NeuralApproximatorNeuron.MyNeuronBackPropagation.Learn(), and IG.Neural.NeuronBackPropagationLEarning.Learn().
OnEndEpoch()
override void NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.OnEndEpoch (int currentIteration, TrainingSet trainingSet) inline protected virtual
Invokes EndEpochEvent
Parameters
currentIteration Current training iteration
trainingSet Training set which got trained successfully this epoch
Reimplemented from NeuronDotNet.Core.Network.
References NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.isValidMSE, NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.meanSquaredError, and NeuronDotNet.Core.TrainingSet.TrainingSampleCount.
Referenced by IG.Neural.NeuralApproximatorNeuron.MyNeuronBackPropagation.Learn(), and IG.Neural.NeuronBackPropagationLEarning.Learn().
LearnSample()
override void NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.LearnSample (TrainingSample trainingSample, int currentIteration, int trainingEpochs) inline protected virtual
A protected helper function used to train single learning sample
Parameters
trainingSample Training sample to use
currentIteration Current training epoch (Assumed to be positive and less than trainingEpochs)
trainingEpochs Number of training epochs (Assumed to be positive)
Implements NeuronDotNet.Core.Network.
References NeuronDotNet.Core.Backpropagation.ActivationLayer.EvaluateErrors(), NeuronDotNet.Core.Network.inputLayer, NeuronDotNet.Core.TrainingSample.InputVector, NeuronDotNet.Core.Network.layers, NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.meanSquaredError, NeuronDotNet.Core.Network.outputLayer, NeuronDotNet.Core.TrainingSample.OutputVector, and NeuronDotNet.Core.ILayer.SetInput().
Referenced by IG.Neural.NeuralApproximatorNeuron.MyNeuronBackPropagation.Learn(), and IG.Neural.NeuronBackPropagationLEarning.Learn().
Member Data Documentation
meanSquaredError
double NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.meanSquaredError private
Referenced by NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.Learn(), NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.LearnSample(), NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.OnBeginEpoch(), and NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.OnEndEpoch().
isValidMSE
bool NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.isValidMSE private
Referenced by NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.Learn(), NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.OnBeginEpoch(), and NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.OnEndEpoch().
Property Documentation
MeanSquaredError
double? NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.MeanSquaredError get
Gets the value of mean squared error
Mean squared value of error in current training epoch
Referenced by IG.Neural.NeuralApproximatorNeuron.TrainNetworkSpecific().
The documentation for this class was generated from the following file:
shelldev/lib/externalextended/NeuronDotNetGPL/source/Core/Backpropagation/BackpropagationNetwork.cs