Doc: IGLib EXTENDED: IG.Neural.NeuralApplicationCommandsTadej Class Reference
IG.Neural.NeuralApplicationCommandsTadej Class Reference
Commands for application's interpreter for neural networks.
Static Public Member Functions
static new void InstallCommands (ICommandLineApplicationInterpreter app)
Installs Tadej's commands for neural networks on the applications's command interpreter.
static string CmdExampleTadej (CommandThread interpreterThread, string cmdName, string[] args)
Command. Example command for Tadej.
Static Public Member Functions inherited from IG.Neural.NeuralAllpicationCommands
static void InstallCommands (ICommandLineApplicationInterpreter app)
Installs Tadejcommands for neural networks on the applications's command interpreter.
static string cmdTestSerializationNeuralCSV (CommandThread interpreter, string cmdName, string[] args)
Tests serialization and deserialization of various data used in approximation by neural networks.
static string cmdTestSerializationNeural (CommandThread interpreter, string cmdName, string[] args)
Tests serialization and deserialization of various data used in approximation by neural networks.
static string CmdTestJson (CommandThread interpreter, string cmdName, string[] args)
Command. Tests speed of I/O in JSON format. A random matrix of specific size is randomly generated, read and written. Argumnets: inputFilePath: file path numRows: number of rows of the matrix numColumnt: number of columns of the matrix
static string CmdTestFormat (CommandThread interpreter, string cmdName, string[] args)
Command. Tests file formats. Attempsts to import the specified file in the specified format, then to export it under new name. Argumnets: format: file format specification. Not case sensitive. NeuralDataDefinition inputFilePath: file path
static string CmdSupplementNeuralDataDefinition (CommandThread interpreter, string cmdName, string[] args)
Command method that supplements neural input/output data definitions from training data (some values are inferred from data ranges in training data).
static string CmdNeuralClearMessages (CommandThread interpreter, string cmdName, string[] args)
Command. Clears all messages for neural network approximation file client/server.
static string CmdNeuralCalculateApproximationPlain (CommandThread interpreter, string cmdName, string[] args)
Command. Calculates approximation according to input parameters written in a file, and outputs resulting approximated values to a file. This command loads a neural network from the specified file, reads input parameters from another file, and writes output parameters to the third file. The first argument is the neural network file, the second is file with input parameters, and the third is file where approximated output values willl be written.
static string CmdNeuralCalculateApproximationServer (CommandThread interpreter, string cmdName, string[] args)
Command. Calculates approximation according to input parameters written in a file, and outputs resulting approximated values to a file. The only argument is the client/server working directory.
static string CmdNeuralCalculateApproximationClient (CommandThread interpreter, string cmdName, string[] args)
Command. Sends request to a server to calculate an approximation. The first argument is the client/server working directory, the second is file with input parameters, and the third is file where approximated output values willl be written
static string CmdNeuralCalculateMappingApproximationServer (CommandThread interpreter, string cmdName, string[] args)
Command. Calculates mapping + approximation according to reduced input parameters written in a file, and outputs resulting approximated values to a file. The only argument is the client/server working directory.
static string CmdNeuralCalculateMappingApproximationClient (CommandThread interpreter, string cmdName, string[] args)
Command. Sends request to a server to calculate mapping + approximation. The first argument is the client/server working directory, the second is file with reduced input parameters, and the third is file where approximated reduced output values willl be written
static string CmdExampleNeural (CommandThread interpreter, string cmdName, string[] args)
Command. Example command for Tadej.
Detailed Description
Commands for application's interpreter for neural networks.
$A Igor Apr11;
Member Function Documentation
InstallCommands()
static new void IG.Neural.NeuralApplicationCommandsTadej.InstallCommands (ICommandLineApplicationInterpreter app) inline static
Installs Tadej's commands for neural networks on the applications's command interpreter.
References IG.Lib.ICommandLineApplicationInterpreter.AddCommand(), IG.Neural.NeuralApplicationCommandsTadej.CmdExampleTadej(), and IG.Neural.NeuralAllpicationCommands.InstallCommands().
Referenced by IG.Lib.NeuralApplicationInterpreter.NeuralApplicationInterpreter().
CmdExampleTadej()
static string IG.Neural.NeuralApplicationCommandsTadej.CmdExampleTadej (CommandThread interpreterThread, string cmdName, string[] args) inline static
Command. Example command for Tadej.
Parameters
interpreterThread Interpreter thread on which commad is run.
cmdName Command name.
AppArguments Command arguments.
Returns
Format of the file if test was performed, null otherwise.
Referenced by IG.Neural.NeuralApplicationCommandsTadej.InstallCommands().
The documentation for this class was generated from the following file:
iglib/extensions/iglibneural/neural/neural_tadej/NeuralApplicationTadej.cs