Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLANSB Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLANSB Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLANSB (DLASSQ dlassq, LSAME lsame)
DLANSB ()
double Run (string NORM, string UPLO, int N, int K, double[] AB, int offset_ab, int LDAB, ref double[] WORK, int offset_work)
Private Attributes
DLASSQ _dlassq
LSAME _lsame
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLANSB returns the value of the one norm, or the Frobenius norm, or the infinity norm, or the element of largest absolute value of an n by n symmetric band matrix A, with k super-diagonals.
Description
DLANSB returns the value
DLANSB = (max(abs(A(i,j))), NORM = 'M' or 'm' ((norm1(A), NORM = '1', 'O' or 'o' ((normI(A), NORM = 'I' or 'i' ((normF(A), NORM = 'F', 'f', 'E' or 'e'
where norm1 denotes the one norm of a matrix (maximum column sum), normI denotes the infinity norm of a matrix (maximum row sum) and normF denotes the Frobenius norm of a matrix (square root of sum of squares). Note that max(abs(A(i,j))) is not a consistent matrix norm.
/summary>
Constructor & Destructor Documentation
DLANSB() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLANSB.DLANSB (DLASSQ dlassq, LSAME lsame) inline
DLANSB() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLANSB.DLANSB () inline
Member Function Documentation
Run()
double DotNumerics.LinearAlgebra.CSLapack.DLANSB.Run (string NORM, string UPLO, int N, int K, double[] AB, int offset_ab, int LDAB, ref double[] WORK, int offset_work) inline
Purpose
DLANSB returns the value of the one norm, or the Frobenius norm, or the infinity norm, or the element of largest absolute value of an n by n symmetric band matrix A, with k super-diagonals.
Description
DLANSB returns the value
DLANSB = (max(abs(A(i,j))), NORM = 'M' or 'm' ((norm1(A), NORM = '1', 'O' or 'o' ((normI(A), NORM = 'I' or 'i' ((normF(A), NORM = 'F', 'f', 'E' or 'e'
where norm1 denotes the one norm of a matrix (maximum column sum), normI denotes the infinity norm of a matrix (maximum row sum) and normF denotes the Frobenius norm of a matrix (square root of sum of squares). Note that max(abs(A(i,j))) is not a consistent matrix norm.
/summary>
Parameters
NORM (input) CHARACTER*1 Specifies the value to be returned in DLANSB as described above. /param>
Parameters
UPLO (input) CHARACTER*1 Specifies whether the upper or lower triangular part of the band matrix A is supplied. = 'U': Upper triangular part is supplied = 'L': Lower triangular part is supplied /param>
Parameters
N (input) INTEGER The order of the matrix A. N .GE. 0. When N = 0, DLANSB is set to zero. /param>
Parameters
K (input) INTEGER The number of super-diagonals or sub-diagonals of the band matrix A. K .GE. 0. /param>
Parameters
AB (input) DOUBLE PRECISION array, dimension (LDAB,N) The upper or lower triangle of the symmetric band matrix A, stored in the first K+1 rows of AB. The j-th column of A is stored in the j-th column of the array AB as follows: if UPLO = 'U', AB(k+1+i-j,j) = A(i,j) for max(1,j-k).LE.i.LE.j; if UPLO = 'L', AB(1+i-j,j) = A(i,j) for j.LE.i.LE.min(n,j+k). /param>
Parameters
LDAB (input) INTEGER The leading dimension of the array AB. LDAB .GE. K+1. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (MAX(1,LWORK)), where LWORK .GE. N when NORM = 'I' or '1' or 'O'; otherwise, WORK is not referenced. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLANSB.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASSQ.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLANSB.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSBEV.Run(), and DotNumerics.LinearAlgebra.CSLapack.DSBEVD.Run().
Member Data Documentation
_dlassq
DLASSQ DotNumerics.LinearAlgebra.CSLapack.DLANSB._dlassq private
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLANSB._lsame private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLANSB.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLANSB.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLANSB.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLANSB.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlansb.cs