Doc: IGLib EXTENDED: Test.SpinTest Class Reference
Test.SpinTest Class Reference
Summary description for SpinTest
Public Member Functions
SpinTest ()
void SpinEquality ()
void SpinInvalid1 ()
void SpinInvalid2 ()
void SpinStateInvalid1 ()
void SpinStateInvalid2 ()
void SpinStateInvalid3 ()
void ClebschGordonSepcialCase ()
void ClebschGordonOrthonormalityJM ()
void ClebschGordonOrthonormalityMM ()
void ThreeJExchangeSymmetry ()
void ThreeJRacahSymmetry ()
void ThreeJRecursion ()
void ThreeJLegendreIntegral ()
void SixJSpecialCase ()
void SixJReggeSymmetry ()
void SixJOrthonormality ()
void SixJSum ()
void SixJProductSum ()
void SixJThreeJRelation ()
void SixJExchangeSymmetry ()
void SixJZeroMinimum ()
Properties
TestContext TestContext [get, set]
Gets or sets the test context which provides information about and functionality for the current test run. /summary>
Static Private Member Functions
static ThreeJSymbol[] GenerateRandomThreeJSymbols (double j_max, int n)
static SixJSymbol[] GenerateRandomSixJSymbols (double j_max, int n)
static SpinRange CombinedSpinRange (Spin j1, Spin j2)
static SpinRange CombinedSpinRange (SpinRange r1, SpinRange r2)
static Spin[] AllSpinsInRange (SpinRange range)
static Spin[] RandomSpinsInRange (SpinRange range, int n)
static Spin[] GenerateRandomSpins (double j_min, double j_max, int n)
static Spin[] GenerateRandomCombinedSpins (Spin j1, Spin j2, int n)
static Spin[] GenerateCombinedSpins (Spin j1, Spin j2)
static SpinState[] GenerateRandomSpinStates (Spin j, int n)
static SpinState[] GenerateRandomSpinStates (double j_min, double j_max, int n)
Private Attributes
TestContext testContextInstance
Detailed Description
Summary description for SpinTest
Constructor & Destructor Documentation
SpinTest()
Test.SpinTest.SpinTest () inline
Member Function Documentation
GenerateRandomThreeJSymbols()
static ThreeJSymbol [] Test.SpinTest.GenerateRandomThreeJSymbols (double j_max, int n) inline static private
References Test.ThreeJSymbol.Column1, Test.ThreeJSymbol.Column2, and Test.ThreeJSymbol.Column3.
Referenced by Test.SpinTest.ThreeJExchangeSymmetry(), Test.SpinTest.ThreeJRacahSymmetry(), and Test.SpinTest.ThreeJRecursion().
GenerateRandomSixJSymbols()
static SixJSymbol [] Test.SpinTest.GenerateRandomSixJSymbols (double j_max, int n) inline static private
References Test.SixJSymbol.J1, Test.SixJSymbol.J2, Test.SixJSymbol.J3, Test.SixJSymbol.J4, Test.SixJSymbol.J5, and Test.SixJSymbol.J6.
Referenced by Test.SpinTest.SixJExchangeSymmetry(), Test.SpinTest.SixJOrthonormality(), Test.SpinTest.SixJProductSum(), Test.SpinTest.SixJReggeSymmetry(), and Test.SpinTest.SixJThreeJRelation().
CombinedSpinRange() [1/2]
static SpinRange Test.SpinTest.CombinedSpinRange (Spin j1, Spin j2) inline static private
References Meta.Numerics.Spin.Spin.J, Test.SpinRange.Maximum, and Test.SpinRange.Minimum.
Referenced by Test.SpinTest.SixJOrthonormality(), and Test.SpinTest.SixJProductSum().
CombinedSpinRange() [2/2]
static SpinRange Test.SpinTest.CombinedSpinRange (SpinRange r1, SpinRange r2) inline static private
References Meta.Numerics.Spin.Spin.J, Test.SpinRange.Maximum, and Test.SpinRange.Minimum.
AllSpinsInRange()
static Spin [] Test.SpinTest.AllSpinsInRange (SpinRange range) inline static private
References Meta.Numerics.Spin.Spin.J, Test.SpinRange.Maximum, and Test.SpinRange.Minimum.
Referenced by Test.SpinTest.SixJOrthonormality(), and Test.SpinTest.SixJProductSum().
RandomSpinsInRange()
static Spin [] Test.SpinTest.RandomSpinsInRange (SpinRange range, int n) inline static private
References Meta.Numerics.Spin.Spin.J, Test.SpinRange.Maximum, and Test.SpinRange.Minimum.
Referenced by Test.SpinTest.SixJOrthonormality(), and Test.SpinTest.SixJProductSum().
GenerateRandomSpins()
static Spin [] Test.SpinTest.GenerateRandomSpins (double j_min, double j_max, int n) inline static private
Referenced by Test.SpinTest.ClebschGordonOrthonormalityJM(), Test.SpinTest.ClebschGordonOrthonormalityMM(), and Test.SpinTest.SixJSum().
GenerateRandomCombinedSpins()
static Spin [] Test.SpinTest.GenerateRandomCombinedSpins (Spin j1, Spin j2, int n) inline static private
References Meta.Numerics.Spin.Spin.J.
Referenced by Test.SpinTest.ClebschGordonOrthonormalityJM(), and Test.SpinTest.SixJSum().
GenerateCombinedSpins()
static Spin [] Test.SpinTest.GenerateCombinedSpins (Spin j1, Spin j2) inline static private
References Meta.Numerics.Spin.Spin.J.
Referenced by Test.SpinTest.SixJSum().
GenerateRandomSpinStates() [1/2]
static SpinState [] Test.SpinTest.GenerateRandomSpinStates (Spin j, int n) inline static private
References Meta.Numerics.Spin.Spin.J.
Referenced by Test.SpinTest.ClebschGordonOrthonormalityJM(), Test.SpinTest.ClebschGordonOrthonormalityMM(), and Test.SpinTest.SixJThreeJRelation().
GenerateRandomSpinStates() [2/2]
static SpinState [] Test.SpinTest.GenerateRandomSpinStates (double j_min, double j_max, int n) inline static private
SpinEquality()
void Test.SpinTest.SpinEquality () inline
References Meta.Numerics.Spin.Spin.Dimension, Meta.Numerics.Spin.Spin.SpinOne, Meta.Numerics.Spin.Spin.SpinZero, and Meta.Numerics.Spin.Spin.States().
SpinInvalid1()
void Test.SpinTest.SpinInvalid1 () inline
SpinInvalid2()
void Test.SpinTest.SpinInvalid2 () inline
SpinStateInvalid1()
void Test.SpinTest.SpinStateInvalid1 () inline
SpinStateInvalid2()
void Test.SpinTest.SpinStateInvalid2 () inline
SpinStateInvalid3()
void Test.SpinTest.SpinStateInvalid3 () inline
ClebschGordonSepcialCase()
void Test.SpinTest.ClebschGordonSepcialCase () inline
References Meta.Numerics.Spin.SpinMath.ClebschGodron().
ClebschGordonOrthonormalityJM()
void Test.SpinTest.ClebschGordonOrthonormalityJM () inline
References Meta.Numerics.Spin.SpinMath.ClebschGodron(), Test.SpinTest.GenerateRandomCombinedSpins(), Test.SpinTest.GenerateRandomSpins(), Test.SpinTest.GenerateRandomSpinStates(), Meta.Numerics.Spin.SpinState.J, Meta.Numerics.Spin.SpinState.M, and Meta.Numerics.Spin.Spin.States().
ClebschGordonOrthonormalityMM()
void Test.SpinTest.ClebschGordonOrthonormalityMM () inline
References Meta.Numerics.Spin.SpinMath.ClebschGodron(), Test.SpinTest.GenerateRandomSpins(), Test.SpinTest.GenerateRandomSpinStates(), Meta.Numerics.Spin.Spin.J, and Meta.Numerics.Spin.SpinState.M.
ThreeJExchangeSymmetry()
void Test.SpinTest.ThreeJExchangeSymmetry () inline
References Test.ThreeJSymbol.Column1, Test.ThreeJSymbol.Column2, Test.ThreeJSymbol.Column3, Test.SpinTest.GenerateRandomThreeJSymbols(), Meta.Numerics.Spin.SpinState.J, Meta.Numerics.Spin.SpinState.M, and Meta.Numerics.Spin.SpinMath.ThreeJ().
ThreeJRacahSymmetry()
void Test.SpinTest.ThreeJRacahSymmetry () inline
References Test.ThreeJSymbol.Column1, Test.ThreeJSymbol.Column2, Test.ThreeJSymbol.Column3, Test.SpinTest.GenerateRandomThreeJSymbols(), Meta.Numerics.Spin.SpinState.J, Meta.Numerics.Spin.SpinState.M, and Meta.Numerics.Spin.SpinMath.ThreeJ().
ThreeJRecursion()
void Test.SpinTest.ThreeJRecursion () inline
References Test.ThreeJSymbol.Column1, Test.ThreeJSymbol.Column2, Test.ThreeJSymbol.Column3, Test.SpinTest.GenerateRandomThreeJSymbols(), Meta.Numerics.Spin.SpinState.J, Meta.Numerics.Spin.SpinState.M, and Meta.Numerics.Spin.SpinMath.ThreeJ().
ThreeJLegendreIntegral()
void Test.SpinTest.ThreeJLegendreIntegral () inline
References Meta.Numerics.Interval.FromEndpoints(), Meta.Numerics.Analysis.FunctionMath.Integrate(), Meta.Numerics.Functions.OrthogonalPolynomials.LegendreP(), and Meta.Numerics.Spin.SpinMath.ThreeJ().
SixJSpecialCase()
void Test.SpinTest.SixJSpecialCase () inline
References Meta.Numerics.Spin.SpinMath.SixJ(), Meta.Numerics.Spin.Spin.SpinOneHalf, and Meta.Numerics.Spin.Spin.SpinZero.
SixJReggeSymmetry()
void Test.SpinTest.SixJReggeSymmetry () inline
References Test.SpinTest.GenerateRandomSixJSymbols(), Meta.Numerics.Spin.Spin.J, Test.SixJSymbol.J1, Test.SixJSymbol.J2, Test.SixJSymbol.J3, Test.SixJSymbol.J4, Test.SixJSymbol.J5, Test.SixJSymbol.J6, and Meta.Numerics.Spin.SpinMath.SixJ().
SixJOrthonormality()
void Test.SpinTest.SixJOrthonormality () inline
References Test.SpinTest.AllSpinsInRange(), Test.SpinTest.CombinedSpinRange(), Test.SpinTest.GenerateRandomSixJSymbols(), Meta.Numerics.Spin.Spin.J, Test.SixJSymbol.J1, Test.SixJSymbol.J2, Test.SixJSymbol.J4, Test.SixJSymbol.J5, Test.SixJSymbol.J6, Test.SpinTest.RandomSpinsInRange(), and Meta.Numerics.Spin.SpinMath.SixJ().
SixJSum()
void Test.SpinTest.SixJSum () inline
References Test.SpinTest.GenerateCombinedSpins(), Test.SpinTest.GenerateRandomCombinedSpins(), Test.SpinTest.GenerateRandomSpins(), Meta.Numerics.Spin.Spin.J, and Meta.Numerics.Spin.SpinMath.SixJ().
SixJProductSum()
void Test.SpinTest.SixJProductSum () inline
References Test.SpinTest.AllSpinsInRange(), Test.SpinTest.CombinedSpinRange(), Test.SpinTest.GenerateRandomSixJSymbols(), Meta.Numerics.Spin.Spin.J, Test.SixJSymbol.J1, Test.SixJSymbol.J2, Test.SixJSymbol.J4, Test.SixJSymbol.J5, Test.SixJSymbol.J6, Test.SpinRange.Maximum, Test.SpinRange.Minimum, Test.SpinTest.RandomSpinsInRange(), and Meta.Numerics.Spin.SpinMath.SixJ().
SixJThreeJRelation()
void Test.SpinTest.SixJThreeJRelation () inline
References Test.SpinTest.GenerateRandomSixJSymbols(), Test.SpinTest.GenerateRandomSpinStates(), Meta.Numerics.Spin.SpinState.J, Test.SixJSymbol.J1, Test.SixJSymbol.J2, Test.SixJSymbol.J3, Test.SixJSymbol.J4, Test.SixJSymbol.J5, Test.SixJSymbol.J6, Meta.Numerics.Spin.SpinState.M, Meta.Numerics.Spin.SpinMath.SixJ(), and Meta.Numerics.Spin.SpinMath.ThreeJ().
SixJExchangeSymmetry()
void Test.SpinTest.SixJExchangeSymmetry () inline
References Test.SpinTest.GenerateRandomSixJSymbols(), Test.SixJSymbol.J1, Test.SixJSymbol.J2, Test.SixJSymbol.J3, Test.SixJSymbol.J4, Test.SixJSymbol.J5, Test.SixJSymbol.J6, and Meta.Numerics.Spin.SpinMath.SixJ().
SixJZeroMinimum()
void Test.SpinTest.SixJZeroMinimum () inline
References Meta.Numerics.Spin.SpinMath.SixJ(), and Meta.Numerics.Spin.Spin.SpinOne.
Member Data Documentation
testContextInstance
TestContext Test.SpinTest.testContextInstance private
Property Documentation
TestContext
TestContext Test.SpinTest.TestContext get set
Gets or sets the test context which provides information about and functionality for the current test run. /summary>
The documentation for this class was generated from the following file:
igtest/numerics/MetaNumerics/Numerics/Test/SpinTest.cs