Doc: IGLib EXTENDED: IG.Forms.FontSelectorSimple Class Reference
IG.Forms.FontSelectorSimple Class Reference
Simple control that allows font selection.
Public Member Functions
FontSelectorSimple ()
FontSelectorSimple (Font initialFont)
string FontDescriptionShort ()
Returns short textual description of the selected forn.
void UpdateAppearance ()
Updates appearance of the control, according to the state of font selection and the actual font.
FontSelectorSimple ()
FontSelectorSimple (Font initialFont)
string FontDescriptionShort ()
Returns short textual description of the selected forn.
void UpdateAppearance ()
Updates appearance of the control, according to the state of font selection and the actual font.
FontSelectorSimple ()
FontSelectorSimple (Font initialFont)
string FontDescriptionShort ()
Returns short textual description of the selected forn.
void UpdateAppearance ()
Updates appearance of the control, according to the state of font selection and the actual font.
Static Public Member Functions
static string FontDesctiptionShort (Font font)
Returns a short desription of the specified font.
static string FontDesctiptionShort (Font font)
Returns a short desription of the specified font.
static string FontDesctiptionShort (Font font)
Returns a short desription of the specified font.
Public Attributes
string _initialFontLabelText = "< Click to select font! >"
Protected Member Functions
void OpenFontDialog ()
void OnFontSelected (object sender, FontEventArgs eventArgs)
Triggers the FontSelected event. This occurs whenewer the selected font is changed, or when it is set for the first time.
void OnFontSelectedFirstTime (object sender, FontEventArgs eventArgs)
Triggers the FontSelectedFirstTime event. This occurs when font is selected for the first time.
void OpenFontDialog ()
void OnFontSelected (object sender, FontEventArgs eventArgs)
Triggers the FontSelected event. This occurs whenewer the selected font is changed, or when it is set for the first time.
void OnFontSelectedFirstTime (object sender, FontEventArgs eventArgs)
Triggers the FontSelectedFirstTime event. This occurs when font is selected for the first time.
void OpenFontDialog ()
void OnFontSelected (object sender, FontEventArgs eventArgs)
Triggers the FontSelected event. This occurs whenewer the selected font is changed, or when it is set for the first time.
void OnFontSelectedFirstTime (object sender, FontEventArgs eventArgs)
Triggers the FontSelectedFirstTime event. This occurs when font is selected for the first time.
Properties
bool IsFontSelected [get, set]
Font SelectedFont [get, set]
string InitialFontLabelText [get, set]
Color InitialFontLabelForeColor [get]
Color NormalFontLabelForeColor [get]
Events
FontEventHandler FontSelected
Event that is fired when the selected font changes.
FontEventHandler FontSelectedFirstTime
Event that occurs when the selected font gets defined (i.e., when it is set for the first time).
Private Member Functions
void btnOpenDialog_Click (object sender, EventArgs e)
void lblFontDescription_Click (object sender, EventArgs e)
void InitializeComponent ()
Required designer variable.
void btnOpenDialog_Click (object sender, EventArgs e)
void lblFontDescription_Click (object sender, EventArgs e)
void InitializeComponent ()
Required designer variable.
void btnOpenDialog_Click (object sender, EventArgs e)
void lblFontDescription_Click (object sender, EventArgs e)
void InitializeComponent ()
Required designer variable.
Private Attributes
bool _isFontSelected = false
Font _selectedFont = new Font("Times New Roman", 10)
System.Windows.Forms.Button btnOpenDialog
System.Windows.Forms.FontDialog fontDialog1
System.Windows.Forms.Label lblFontDescription
Detailed Description
Simple control that allows font selection.
Contains a button for font selection and a label with short description of the current font.
The font is initially unspecified when control if control is created with default constructor.
Font can be queeried, and change of font fires an event.
Constructor & Destructor Documentation
FontSelectorSimple() [1/6]
IG.Forms.FontSelectorSimple.FontSelectorSimple () inline
References IG.Forms.FontSelectorSimple.InitializeComponent().
FontSelectorSimple() [2/6]
IG.Forms.FontSelectorSimple.FontSelectorSimple (Font initialFont) inline
FontSelectorSimple() [3/6]
IG.Forms.FontSelectorSimple.FontSelectorSimple () inline
References IG.Forms.FontSelectorSimple.InitializeComponent().
FontSelectorSimple() [4/6]
IG.Forms.FontSelectorSimple.FontSelectorSimple (Font initialFont) inline
FontSelectorSimple() [5/6]
IG.Forms.FontSelectorSimple.FontSelectorSimple () inline
References IG.Forms.FontSelectorSimple.InitializeComponent().
FontSelectorSimple() [6/6]
IG.Forms.FontSelectorSimple.FontSelectorSimple (Font initialFont) inline
Member Function Documentation
FontDescriptionShort() [1/3]
string IG.Forms.FontSelectorSimple.FontDescriptionShort () inline
Returns short textual description of the selected forn.
References IG.Forms.FontSelectorSimple.FontDesctiptionShort(), IG.Forms.FontSelectorSimple.IsFontSelected, and IG.Forms.FontSelectorSimple.SelectedFont.
Referenced by IG.Forms.FontSelectorSimple.UpdateAppearance().
FontDesctiptionShort() [1/3]
static string IG.Forms.FontSelectorSimple.FontDesctiptionShort (Font font) inline static
Returns a short desription of the specified font.
Description contains font size, family name, and descriptors indicating whether it is bold, italic, underlined, or strikedout, separated by commas. If font has no modifier properties like bold then hte corresponding discriptor is just empty. Descriptors are like "bold", "italic", "underlined", etc.
Parameters
font Font whose description is returned.
Returns
Referenced by IG.Forms.FontSelectorSimple.FontDescriptionShort().
UpdateAppearance() [1/3]
void IG.Forms.FontSelectorSimple.UpdateAppearance () inline
Updates appearance of the control, according to the state of font selection and the actual font.
References IG.Forms.FontSelectorSimple.FontDescriptionShort(), IG.Forms.FontSelectorSimple.InitialFontLabelForeColor, IG.Forms.FontSelectorSimple.InitialFontLabelText, IG.Forms.FontSelectorSimple.IsFontSelected, IG.Forms.FontSelectorSimple.lblFontDescription, and IG.Forms.FontSelectorSimple.NormalFontLabelForeColor.
Referenced by IG.Forms.FontSelectorSimple.OnFontSelected(), and IG.Forms.FontSelectorSimple.OpenFontDialog().
OpenFontDialog() [1/3]
void IG.Forms.FontSelectorSimple.OpenFontDialog () inline protected
References IG.Forms.FontSelectorSimple.fontDialog1, IG.Forms.FontSelectorSimple.SelectedFont, and IG.Forms.FontSelectorSimple.UpdateAppearance().
Referenced by IG.Forms.FontSelectorSimple.btnOpenDialog_Click(), and IG.Forms.FontSelectorSimple.lblFontDescription_Click().
OnFontSelected() [1/3]
void IG.Forms.FontSelectorSimple.OnFontSelected (object sender, FontEventArgs eventArgs) inline protected
Triggers the FontSelected event. This occurs whenewer the selected font is changed, or when it is set for the first time.
References IG.Forms.FontSelectorSimple.FontSelected, and IG.Forms.FontSelectorSimple.UpdateAppearance().
OnFontSelectedFirstTime() [1/3]
void IG.Forms.FontSelectorSimple.OnFontSelectedFirstTime (object sender, FontEventArgs eventArgs) inline protected
Triggers the FontSelectedFirstTime event. This occurs when font is selected for the first time.
References IG.Forms.FontSelectorSimple.FontSelectedFirstTime.
btnOpenDialog_Click() [1/3]
void IG.Forms.FontSelectorSimple.btnOpenDialog_Click (object sender, EventArgs e) inline private
References IG.Forms.FontSelectorSimple.OpenFontDialog().
Referenced by IG.Forms.FontSelectorSimple.InitializeComponent().
lblFontDescription_Click() [1/3]
void IG.Forms.FontSelectorSimple.lblFontDescription_Click (object sender, EventArgs e) inline private
References IG.Forms.FontSelectorSimple.OpenFontDialog().
Referenced by IG.Forms.FontSelectorSimple.InitializeComponent().
InitializeComponent() [1/3]
void IG.Forms.FontSelectorSimple.InitializeComponent () inline private
Required designer variable.
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.FontSelectorSimple.btnOpenDialog, IG.Forms.FontSelectorSimple.btnOpenDialog_Click(), IG.Forms.FontSelectorSimple.fontDialog1, IG.Forms.FontSelectorSimple.lblFontDescription, and IG.Forms.FontSelectorSimple.lblFontDescription_Click().
Referenced by IG.Forms.FontSelectorSimple.FontSelectorSimple().
FontDescriptionShort() [2/3]
string IG.Forms.FontSelectorSimple.FontDescriptionShort () inline
Returns short textual description of the selected forn.
References IG.Forms.FontSelectorSimple.FontDesctiptionShort(), IG.Forms.FontSelectorSimple.IsFontSelected, and IG.Forms.FontSelectorSimple.SelectedFont.
FontDesctiptionShort() [2/3]
static string IG.Forms.FontSelectorSimple.FontDesctiptionShort (Font font) inline static
Returns a short desription of the specified font.
Description contains font size, family name, and descriptors indicating whether it is bold, italic, underlined, or strikedout, separated by commas. If font has no modifier properties like bold then hte corresponding discriptor is just empty. Descriptors are like "bold", "italic", "underlined", etc.
Parameters
font Font whose description is returned.
Returns
UpdateAppearance() [2/3]
void IG.Forms.FontSelectorSimple.UpdateAppearance () inline
Updates appearance of the control, according to the state of font selection and the actual font.
References IG.Forms.FontSelectorSimple.FontDescriptionShort(), IG.Forms.FontSelectorSimple.InitialFontLabelForeColor, IG.Forms.FontSelectorSimple.InitialFontLabelText, IG.Forms.FontSelectorSimple.IsFontSelected, IG.Forms.FontSelectorSimple.lblFontDescription, and IG.Forms.FontSelectorSimple.NormalFontLabelForeColor.
OpenFontDialog() [2/3]
void IG.Forms.FontSelectorSimple.OpenFontDialog () inline protected
References IG.Forms.FontSelectorSimple.fontDialog1, IG.Forms.FontSelectorSimple.SelectedFont, and IG.Forms.FontSelectorSimple.UpdateAppearance().
OnFontSelected() [2/3]
void IG.Forms.FontSelectorSimple.OnFontSelected (object sender, FontEventArgs eventArgs) inline protected
Triggers the FontSelected event. This occurs whenewer the selected font is changed, or when it is set for the first time.
References IG.Forms.FontSelectorSimple.FontSelected, and IG.Forms.FontSelectorSimple.UpdateAppearance().
OnFontSelectedFirstTime() [2/3]
void IG.Forms.FontSelectorSimple.OnFontSelectedFirstTime (object sender, FontEventArgs eventArgs) inline protected
Triggers the FontSelectedFirstTime event. This occurs when font is selected for the first time.
References IG.Forms.FontSelectorSimple.FontSelectedFirstTime.
btnOpenDialog_Click() [2/3]
void IG.Forms.FontSelectorSimple.btnOpenDialog_Click (object sender, EventArgs e) inline private
References IG.Forms.FontSelectorSimple.OpenFontDialog().
lblFontDescription_Click() [2/3]
void IG.Forms.FontSelectorSimple.lblFontDescription_Click (object sender, EventArgs e) inline private
References IG.Forms.FontSelectorSimple.OpenFontDialog().
InitializeComponent() [2/3]
void IG.Forms.FontSelectorSimple.InitializeComponent () inline private
Required designer variable.
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.FontSelectorSimple.btnOpenDialog, IG.Forms.FontSelectorSimple.btnOpenDialog_Click(), IG.Forms.FontSelectorSimple.fontDialog1, IG.Forms.FontSelectorSimple.lblFontDescription, and IG.Forms.FontSelectorSimple.lblFontDescription_Click().
FontDescriptionShort() [3/3]
string IG.Forms.FontSelectorSimple.FontDescriptionShort () inline
Returns short textual description of the selected forn.
References IG.Forms.FontSelectorSimple.FontDesctiptionShort(), IG.Forms.FontSelectorSimple.IsFontSelected, and IG.Forms.FontSelectorSimple.SelectedFont.
FontDesctiptionShort() [3/3]
static string IG.Forms.FontSelectorSimple.FontDesctiptionShort (Font font) inline static
Returns a short desription of the specified font.
Description contains font size, family name, and descriptors indicating whether it is bold, italic, underlined, or strikedout, separated by commas. If font has no modifier properties like bold then hte corresponding discriptor is just empty. Descriptors are like "bold", "italic", "underlined", etc.
Parameters
font Font whose description is returned.
Returns
UpdateAppearance() [3/3]
void IG.Forms.FontSelectorSimple.UpdateAppearance () inline
Updates appearance of the control, according to the state of font selection and the actual font.
References IG.Forms.FontSelectorSimple.FontDescriptionShort(), IG.Forms.FontSelectorSimple.InitialFontLabelForeColor, IG.Forms.FontSelectorSimple.InitialFontLabelText, IG.Forms.FontSelectorSimple.IsFontSelected, IG.Forms.FontSelectorSimple.lblFontDescription, and IG.Forms.FontSelectorSimple.NormalFontLabelForeColor.
OpenFontDialog() [3/3]
void IG.Forms.FontSelectorSimple.OpenFontDialog () inline protected
References IG.Forms.FontSelectorSimple.fontDialog1, IG.Forms.FontSelectorSimple.SelectedFont, and IG.Forms.FontSelectorSimple.UpdateAppearance().
OnFontSelected() [3/3]
void IG.Forms.FontSelectorSimple.OnFontSelected (object sender, FontEventArgs eventArgs) inline protected
Triggers the FontSelected event. This occurs whenewer the selected font is changed, or when it is set for the first time.
References IG.Forms.FontSelectorSimple.FontSelected, and IG.Forms.FontSelectorSimple.UpdateAppearance().
OnFontSelectedFirstTime() [3/3]
void IG.Forms.FontSelectorSimple.OnFontSelectedFirstTime (object sender, FontEventArgs eventArgs) inline protected
Triggers the FontSelectedFirstTime event. This occurs when font is selected for the first time.
References IG.Forms.FontSelectorSimple.FontSelectedFirstTime.
btnOpenDialog_Click() [3/3]
void IG.Forms.FontSelectorSimple.btnOpenDialog_Click (object sender, EventArgs e) inline private
References IG.Forms.FontSelectorSimple.OpenFontDialog().
lblFontDescription_Click() [3/3]
void IG.Forms.FontSelectorSimple.lblFontDescription_Click (object sender, EventArgs e) inline private
References IG.Forms.FontSelectorSimple.OpenFontDialog().
InitializeComponent() [3/3]
void IG.Forms.FontSelectorSimple.InitializeComponent () inline private
Required designer variable.
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.FontSelectorSimple.btnOpenDialog, IG.Forms.FontSelectorSimple.btnOpenDialog_Click(), IG.Forms.FontSelectorSimple.fontDialog1, IG.Forms.FontSelectorSimple.lblFontDescription, and IG.Forms.FontSelectorSimple.lblFontDescription_Click().
Member Data Documentation
_isFontSelected
bool IG.Forms.FontSelectorSimple._isFontSelected = false private
_selectedFont
Font IG.Forms.FontSelectorSimple._selectedFont = new Font("Times New Roman", 10) private
_initialFontLabelText
string IG.Forms.FontSelectorSimple._initialFontLabelText = "< Click to select font! >"
btnOpenDialog
System Windows Forms Button IG.Forms.FontSelectorSimple.btnOpenDialog private
Referenced by IG.Forms.FontSelectorSimple.InitializeComponent().
fontDialog1
System Windows Forms FontDialog IG.Forms.FontSelectorSimple.fontDialog1 private
Referenced by IG.Forms.FontSelectorSimple.InitializeComponent(), and IG.Forms.FontSelectorSimple.OpenFontDialog().
lblFontDescription
System Windows Forms Label IG.Forms.FontSelectorSimple.lblFontDescription private
Referenced by IG.Forms.FontSelectorSimple.InitializeComponent(), and IG.Forms.FontSelectorSimple.UpdateAppearance().
Property Documentation
IsFontSelected
bool IG.Forms.FontSelectorSimple.IsFontSelected get set protected
Referenced by IG.Forms.FontSelectorSimple.FontDescriptionShort(), and IG.Forms.FontSelectorSimple.UpdateAppearance().
SelectedFont
Font IG.Forms.FontSelectorSimple.SelectedFont get set
Referenced by IG.Forms.FontSelectorSimple.FontDescriptionShort(), IG.Forms.IndicatorLightTestControl.fontSelectorSimple1_FontSelected(), IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), IG.Forms.TimerControl.InitializeComponent(), IG.Forms.FontSelectorSimple.OpenFontDialog(), IG.Forms.TimerControlWorking.UpdateDisplayAppearance(), and IG.Forms.TimerControl.UpdateDisplayAppearance().
InitialFontLabelText
string IG.Forms.FontSelectorSimple.InitialFontLabelText get set
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), IG.Forms.TimerControl.InitializeComponent(), and IG.Forms.FontSelectorSimple.UpdateAppearance().
InitialFontLabelForeColor
Color IG.Forms.FontSelectorSimple.InitialFontLabelForeColor get protected
Referenced by IG.Forms.FontSelectorSimple.UpdateAppearance().
NormalFontLabelForeColor
Color IG.Forms.FontSelectorSimple.NormalFontLabelForeColor get protected
Referenced by IG.Forms.FontSelectorSimple.UpdateAppearance().
Event Documentation
FontSelected
FontEventHandler IG.Forms.FontSelectorSimple.FontSelected
Event that is fired when the selected font changes.
Referenced by IG.Forms.TimerControlWorking.InitializeComponent(), IG.Forms.IndicatorLightTestControl.InitializeComponent(), IG.Forms.TimerControl.InitializeComponent(), and IG.Forms.FontSelectorSimple.OnFontSelected().
FontSelectedFirstTime
FontEventHandler IG.Forms.FontSelectorSimple.FontSelectedFirstTime
Event that occurs when the selected font gets defined (i.e., when it is set for the first time).
Referenced by IG.Forms.FontSelectorSimple.OnFontSelectedFirstTime().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/BasicControls/FontSelectorSimple.cs
iglib/igforms/Utilities/BasicControls/FontSelectorSimple.Designer.cs