Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAQR5 Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAQR5 Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006 /summary>
Public Member Functions
DLAQR5 (DLAMCH dlamch, DGEMM dgemm, DLABAD dlabad, DLACPY dlacpy, DLAQR1 dlaqr1, DLARFG dlarfg, DLASET dlaset, DTRMM dtrmm)
DLAQR5 ()
void Run (bool WANTT, bool WANTZ, int KACC22, int N, int KTOP, int KBOT, int NSHFTS, ref double[] SR, int offset_sr, ref double[] SI, int offset_si, ref double[] H, int offset_h, int LDH, int ILOZ, int IHIZ, ref double[] Z, int offset_z, int LDZ, ref double[] V, int offset_v, int LDV, ref double[] U, int offset_u, int LDU, int NV, ref double[] WV, int offset_wv, int LDWV, int NH, ref double[] WH, int offset_wh, int LDWH)
Private Attributes
DLAMCH _dlamch
DGEMM _dgemm
DLABAD _dlabad
DLACPY _dlacpy
DLAQR1 _dlaqr1
DLARFG _dlarfg
DLASET _dlaset
DTRMM _dtrmm
double[] VT = new double[3]
Static Private Attributes
const double ZERO = 0.0E0
const double ONE = 1.0E0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006 /summary>
Constructor & Destructor Documentation
DLAQR5() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAQR5.DLAQR5 (DLAMCH dlamch, DGEMM dgemm, DLABAD dlabad, DLACPY dlacpy, DLAQR1 dlaqr1, DLARFG dlarfg, DLASET dlaset, DTRMM dtrmm) inline
DLAQR5() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAQR5.DLAQR5 () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DLAQR5.Run (bool WANTT, bool WANTZ, int KACC22, int N, int KTOP, int KBOT, int NSHFTS, ref double[] SR, int offset_sr, ref double[] SI, int offset_si, ref double[] H, int offset_h, int LDH, int ILOZ, int IHIZ, ref double[] Z, int offset_z, int LDZ, ref double[] V, int offset_v, int LDV, ref double[] U, int offset_u, int LDU, int NV, ref double[] WV, int offset_wv, int LDWV, int NH, ref double[] WH, int offset_wh, int LDWH) inline
Parameters
WANTT (input) logical scalar WANTT = .true. if the quasi-triangular Schur factor is being computed. WANTT is set to .false. otherwise. /param>
Parameters
WANTZ (input) logical scalar WANTZ = .true. if the orthogonal Schur factor is being computed. WANTZ is set to .false. otherwise. /param>
Parameters
KACC22 (input) integer with value 0, 1, or 2. Specifies the computation mode of far-from-diagonal orthogonal updates. = 0: DLAQR5 does not accumulate reflections and does not use matrix-matrix multiply to update far-from-diagonal matrix entries. = 1: DLAQR5 accumulates reflections and uses matrix-matrix multiply to update the far-from-diagonal matrix entries. = 2: DLAQR5 accumulates reflections, uses matrix-matrix multiply to update the far-from-diagonal matrix entries, and takes advantage of 2-by-2 block structure during matrix multiplies. /param>
Parameters
N (input) integer scalar N is the order of the Hessenberg matrix H upon which this subroutine operates. /param>
Parameters
KTOP (input) integer scalar /param>
Parameters
KBOT (input) integer scalar These are the first and last rows and columns of an isolated diagonal block upon which the QR sweep is to be applied. It is assumed without a check that either KTOP = 1 or H(KTOP,KTOP-1) = 0 and either KBOT = N or H(KBOT+1,KBOT) = 0. /param>
Parameters
NSHFTS (input) integer scalar NSHFTS gives the number of simultaneous shifts. NSHFTS must be positive and even. /param>
Parameters
SR (input) DOUBLE PRECISION array of size (NSHFTS) /param>
Parameters
SI (input) DOUBLE PRECISION array of size (NSHFTS) SR contains the real parts and SI contains the imaginary parts of the NSHFTS shifts of origin that define the multi-shift QR sweep. /param>
Parameters
H (input/output) DOUBLE PRECISION array of size (LDH,N) On input H contains a Hessenberg matrix. On output a multi-shift QR sweep with shifts SR(J)+i*SI(J) is applied to the isolated diagonal block in rows and columns KTOP through KBOT. /param>
Parameters
LDH (input) integer scalar LDH is the leading dimension of H just as declared in the calling procedure. LDH.GE.MAX(1,N). /param>
Parameters
ILOZ (input) INTEGER /param>
Parameters
IHIZ (input) INTEGER Specify the rows of Z to which transformations must be applied if WANTZ is .TRUE.. 1 .LE. ILOZ .LE. IHIZ .LE. N /param>
Parameters
Z (input/output) DOUBLE PRECISION array of size (LDZ,IHI) If WANTZ = .TRUE., then the QR Sweep orthogonal similarity transformation is accumulated into Z(ILOZ:IHIZ,ILO:IHI) from the right. If WANTZ = .FALSE., then Z is unreferenced. /param>
Parameters
LDZ (input) integer scalar LDA is the leading dimension of Z just as declared in the calling procedure. LDZ.GE.N. /param>
Parameters
V (workspace) DOUBLE PRECISION array of size (LDV,NSHFTS/2) /param>
Parameters
LDV (input) integer scalar LDV is the leading dimension of V as declared in the calling procedure. LDV.GE.3. /param>
Parameters
U (workspace) DOUBLE PRECISION array of size (LDU,3*NSHFTS-3) /param>
Parameters
LDU (input) integer scalar LDU is the leading dimension of U just as declared in the in the calling subroutine. LDU.GE.3*NSHFTS-3. /param>
Parameters
NV (input) integer scalar NV is the number of rows in WV agailable for workspace. NV.GE.1. /param>
Parameters
WV (workspace) DOUBLE PRECISION array of size (LDWV,3*NSHFTS-3) /param>
Parameters
LDWV (input) integer scalar LDWV is the leading dimension of WV as declared in the in the calling subroutine. LDWV.GE.NV.
/param>
Parameters
NH (input) integer scalar NH is the number of columns in array WH available for workspace. NH.GE.1. /param>
Parameters
WH (workspace) DOUBLE PRECISION array of size (LDWH,NH) /param>
Parameters
LDWH (input) integer scalar Leading dimension of WH just as declared in the calling procedure. LDWH.GE.3*NSHFTS-3. /param>
References DotNumerics.FortranLibrary.FortranLib.Mod(), DotNumerics.LinearAlgebra.CSLapack.DLAQR5.ONE, DotNumerics.LinearAlgebra.CSLapack.DLAQR1.Run(), DotNumerics.LinearAlgebra.CSLapack.DLABAD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLACPY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASET.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRMM.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR5.VT, and DotNumerics.LinearAlgebra.CSLapack.DLAQR5.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQR4.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLAQR0.Run().
Member Data Documentation
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DLAQR5._dlamch private
_dgemm
DGEMM DotNumerics.LinearAlgebra.CSLapack.DLAQR5._dgemm private
_dlabad
DLABAD DotNumerics.LinearAlgebra.CSLapack.DLAQR5._dlabad private
_dlacpy
DLACPY DotNumerics.LinearAlgebra.CSLapack.DLAQR5._dlacpy private
_dlaqr1
DLAQR1 DotNumerics.LinearAlgebra.CSLapack.DLAQR5._dlaqr1 private
_dlarfg
DLARFG DotNumerics.LinearAlgebra.CSLapack.DLAQR5._dlarfg private
_dlaset
DLASET DotNumerics.LinearAlgebra.CSLapack.DLAQR5._dlaset private
_dtrmm
DTRMM DotNumerics.LinearAlgebra.CSLapack.DLAQR5._dtrmm private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAQR5.ZERO = 0.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQR5.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAQR5.ONE = 1.0E0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQR5.Run().
VT
double [] DotNumerics.LinearAlgebra.CSLapack.DLAQR5.VT = new double[3] private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAQR5.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlaqr5.cs