Doc: IGLib EXTENDED: IG.Neural.TestFunctions Class Reference
IG.Neural.TestFunctions Class Reference
Static Public Member Functions
static void GenerateFunctionTrainingSamples (double lowerInputLimit, double upperInputLimit, double step, IRealFunction function, ref SampledDataSet trainingData)
static IRealFunction CreateFunction (string equation)
Creates a function loader and uses it for dynamic definition of functions.
static int CalculateNumSteps (double lowLimit, double highLimit, double steps)
static IVector[][] GenerateInputParameters2D (double step, double xMin, int xNumSteps, double yMin, int yNumSteps)
static IVector[][] CalculateFunction2D (IVector[][] inputPArameters)
static IVector[][] TrainingPoints2D (IVector[][] functionCoordinates, int numTrainingPoints, bool random)
Calculate desired number of training poits from data set in random or regullary order.
static IVector[][] TrainingPoints2D (IVector[][] functionCoordinates, int numXTrainingPoints, int numYTrainingPoints, bool random)
Calculate desired number of training poits from data set in random or regullary order.
Static Private Member Functions
static void GenerateInputParameters (double lowerInputLimit, double step, int numSteps, ref IVector[] inputParameters)
Member Function Documentation
GenerateFunctionTrainingSamples()
static void IG.Neural.TestFunctions.GenerateFunctionTrainingSamples (double lowerInputLimit, double upperInputLimit, double step, IRealFunction function, ref SampledDataSet trainingData) inline static
References IG.Neural.TestFunctions.GenerateInputParameters().
Referenced by IG.Neural.Applications.DemoNeuralOld.btnGenerateOptData1D_Click(), IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click(), and IG.Neural.Forms.Old.FormNeural1DOld.btnGenerateOptData_Click().
CreateFunction()
static IRealFunction IG.Neural.TestFunctions.CreateFunction (string equation) inline static
Creates a function loader and uses it for dynamic definition of functions.
References IG.Lib.RealFunctionLoader.CreateRealFunction(), IG.Lib.RealFunctionLoader.IndependentVariableName, IG.Lib.RealFunctionLoader.InvalidateDefinitions(), and IG.Lib.RealFunctionLoader.ValueDefinitionString.
GenerateInputParameters()
static void IG.Neural.TestFunctions.GenerateInputParameters (double lowerInputLimit, double step, int numSteps, ref IVector[] inputParameters) inline static private
Referenced by IG.Neural.TestFunctions.GenerateFunctionTrainingSamples().
CalculateNumSteps()
static int IG.Neural.TestFunctions.CalculateNumSteps (double lowLimit, double highLimit, double steps) inline static
GenerateInputParameters2D()
static IVector [][] IG.Neural.TestFunctions.GenerateInputParameters2D (double step, double xMin, int xNumSteps, double yMin, int yNumSteps) inline static
Parameters
step Step for x and y axes.
xMin Minimum on x axes.
xNumSteps Number of steps on x axes.
yMin Minimum on y axes.
yNumSteps Number of steps on y axes.
Returns
Returns points InputParameters2D[y][x]
References IG.Num.IVector< T >.Length.
CalculateFunction2D()
static IVector [][] IG.Neural.TestFunctions.CalculateFunction2D (IVector inputPArameters[][]) inline static
References IG.Num.IVector< T >.Length.
TrainingPoints2D() [1/2]
static IVector [][] IG.Neural.TestFunctions.TrainingPoints2D (IVector functionCoordinates[][], int numTrainingPoints, bool random) inline static
Calculate desired number of training poits from data set in random or regullary order.
Parameters
functionCoordinates Data set.
numTrainingPoints Number of training points for x and y axses.
Returns
Training points.
TrainingPoints2D() [2/2]
static IVector [][] IG.Neural.TestFunctions.TrainingPoints2D (IVector functionCoordinates[][], int numXTrainingPoints, int numYTrainingPoints, bool random) inline static
Calculate desired number of training poits from data set in random or regullary order.
Parameters
functionCoordinates Data set.
numXTrainingPoints Number of training points for x axses.
numYTrainingPoints Number of training points for y axses.
Returns
Training points.
References IG.Num.IVector< T >.Length.
The documentation for this class was generated from the following file:
shelldev/lib/extended/LibShellExt/highlevel_and_testing/Testing_Development/TestFunctions.cs