Doc: IGLib EXTENDED: IG.Gr3d.VtkForm Class Reference
IG.Gr3d.VtkForm Class Reference
Windows form for presenting VTK graphics.
Public Member Functions
VtkForm ()
Public Member Functions inherited from IG.Forms.IClosableFromContainedForm
void Close ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Properties
VtkControlBase VtkControl [get]
Gets the control of type VtkControlBase through which VTK functionality is controlled.
Kitware.VTK.RenderWindowControl VtkRenderWindowControl [get]
VTK's control that is actually used for rendering graphics and through which VTK can be interacted directly.
Properties inherited from IG.Gr3d.IVtkFormContainerGen< Kitware.VTK.RenderWindowControl >
VtkControlBase VtkControl [get]
Base windows forms control through which the basic VTK functionality and all additional features can be accessed.
VtkControlType VtkRenderWindowControl [get]
VTK's control that is actually used for rendering graphics and through which VTK can be interacted directly.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
VtkControlBase _vtkControl
Kitware.VTK.RenderWindowControl _vtkRenderWindowControl
System.ComponentModel.IContainer components = null
Required designer variable.
VtkControlWin vtkControlWin1
Detailed Description
Windows form for presenting VTK graphics.
Contains some additional buttons beside just the VTK renderer control.
This is a toplevel form that only contains a control of type VtkControlWin, which handles all VTK related stuff.
$A Igor xx May13;
Constructor & Destructor Documentation
VtkForm()
IG.Gr3d.VtkForm.VtkForm () inline
References IG.Gr3d.VtkForm.InitializeComponent(), IG.Gr3d.VtkControlBase.InitializeState(), and IG.Gr3d.VtkForm.VtkControl.
Member Function Documentation
Dispose()
override void IG.Gr3d.VtkForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Gr3d.VtkForm.components.
InitializeComponent()
void IG.Gr3d.VtkForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Gr3d.VtkForm.vtkControlWin1.
Referenced by IG.Gr3d.VtkForm.VtkForm().
Member Data Documentation
_vtkControl
VtkControlBase IG.Gr3d.VtkForm._vtkControl private
_vtkRenderWindowControl
Kitware.VTK.RenderWindowControl IG.Gr3d.VtkForm._vtkRenderWindowControl private
components
System.ComponentModel.IContainer IG.Gr3d.VtkForm.components = null private
Required designer variable.
Referenced by IG.Gr3d.VtkForm.Dispose().
vtkControlWin1
VtkControlWin IG.Gr3d.VtkForm.vtkControlWin1 private
Referenced by IG.Gr3d.VtkForm.InitializeComponent().
Property Documentation
VtkControl
VtkControlBase IG.Gr3d.VtkForm.VtkControl get
Gets the control of type VtkControlBase through which VTK functionality is controlled.
Referenced by IG.Gr3d.VtkForm.VtkForm().
VtkRenderWindowControl
Kitware.VTK.RenderWindowControl IG.Gr3d.VtkForm.VtkRenderWindowControl get
VTK's control that is actually used for rendering graphics and through which VTK can be interacted directly.
Instead of accessing this control directly, you should normally access it through the VtkControlBase.VtkControl property of the VtkControl property.
The documentation for this class was generated from the following files:
iglib/extensions/igplot3d/plot3d/vtkbased/Forms/VtkForm.cs
iglib/extensions/igplot3d/plot3d/vtkbased/Forms/VtkForm.Designer.cs