Doc: IGLib EXTENDED: NUnit.Framework.Internal.Commands.SetUpTearDownCommand Class Reference
NUnit.Framework.Internal.Commands.SetUpTearDownCommand Class Reference
SetUpTearDownCommand runs any SetUp methods for a suite, runs the test and then runs any TearDown methods.
Public Member Functions
SetUpTearDownCommand (TestCommand innerCommand)
Initializes a new instance of the SetUpTearDownCommand class.
override TestResult Execute (TestExecutionContext context)
Runs the test, saving a TestResult in the supplied TestExecutionContext.
Public Member Functions inherited from NUnit.Framework.Internal.Commands.TestCommand
TestCommand (Test test)
Construct a TestCommand for a test.
Private Attributes
IList< SetUpTearDownItem > _setUpTearDownItems
Additional Inherited Members
Protected Member Functions inherited from NUnit.Framework.Internal.Commands.DelegatingTestCommand
DelegatingTestCommand (TestCommand innerCommand)
TODO: Documentation needed for constructor
Protected Attributes inherited from NUnit.Framework.Internal.Commands.DelegatingTestCommand
TestCommand innerCommand
TODO: Documentation needed for field
Properties inherited from NUnit.Framework.Internal.Commands.TestCommand
Test Test [get, private set]
Gets the test associated with this command.
Detailed Description
SetUpTearDownCommand runs any SetUp methods for a suite, runs the test and then runs any TearDown methods.
Constructor & Destructor Documentation
SetUpTearDownCommand()
NUnit.Framework.Internal.Commands.SetUpTearDownCommand.SetUpTearDownCommand (TestCommand innerCommand) inline
Initializes a new instance of the SetUpTearDownCommand class.
Parameters
innerCommand The inner command.
References NUnit.Framework.Internal.Commands.SetUpTearDownCommand._setUpTearDownItems, NUnit.Framework.Internal.Execution.CommandBuilder.BuildSetUpTearDownList(), NUnit.Framework.Internal.Commands.DelegatingTestCommand.innerCommand, and NUnit.Framework.Internal.Commands.TestCommand.Test.
Member Function Documentation
Execute()
override TestResult NUnit.Framework.Internal.Commands.SetUpTearDownCommand.Execute (TestExecutionContext context) inline virtual
Runs the test, saving a TestResult in the supplied TestExecutionContext.
Parameters
context The context in which the test should run.
Returns
A TestResult
Implements NUnit.Framework.Internal.Commands.TestCommand.
References NUnit.Framework.Internal.Commands.SetUpTearDownCommand._setUpTearDownItems, NUnit.Framework.Internal.TestExecutionContext.CurrentResult, NUnit.Framework.Internal.Commands.TestCommand.Execute(), NUnit.Framework.Internal.TestExecutionContext.ExecutionStatus, NUnit.Framework.Internal.Commands.DelegatingTestCommand.innerCommand, and NUnit.Framework.Internal.TestResult.RecordException().
Member Data Documentation
_setUpTearDownItems
IList<SetUpTearDownItem> NUnit.Framework.Internal.Commands.SetUpTearDownCommand._setUpTearDownItems private
Referenced by NUnit.Framework.Internal.Commands.SetUpTearDownCommand.Execute(), and NUnit.Framework.Internal.Commands.SetUpTearDownCommand.SetUpTearDownCommand().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/Commands/SetUpTearDownCommand.cs