Doc: IGLib EXTENDED: AForge.Imaging.Filters.BlobsFiltering Class Reference
AForge.Imaging.Filters.BlobsFiltering Class Reference
Blobs filtering by size.
Public Member Functions
BlobsFiltering ()
Initializes a new instance of the BlobsFiltering class.
BlobsFiltering (int minWidth, int minHeight, int maxWidth, int maxHeight)
Initializes a new instance of the BlobsFiltering class.
BlobsFiltering (int minWidth, int minHeight, int maxWidth, int maxHeight, bool coupledSizeFiltering)
Initializes a new instance of the BlobsFiltering class.
BlobsFiltering (IBlobsFilter blobsFilter)
Initializes a new instance of the BlobsFiltering class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlaceFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
bool CoupledSizeFiltering [get, set]
Specifies if size filetering should be coupled or not.
int MinWidth [get, set]
Minimum allowed width of blob.
int MinHeight [get, set]
Minimum allowed height of blob.
int MaxWidth [get, set]
Maximum allowed width of blob.
int MaxHeight [get, set]
Maximum allowed height of blob.
IBlobsFilter BlobsFilter [get, set]
Custom blobs' filter to use.
Properties inherited from AForge.Imaging.Filters.BaseInPlaceFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
BlobCounter blobCounter = new BlobCounter()
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Blobs filtering by size.
The filter performs filtering of blobs by their size in the specified source image - all blobs, which are smaller or bigger then specified limits, are removed from the image.
<note>The image processing filter treats all none black pixels as objects' pixels and all black pixel as background.</note>
The filter accepts 8 bpp grayscale images and 24/32 color images for processing.
Sample usage:
// create filter
BlobsFiltering filter = new BlobsFiltering();
// configure filter
filter.CoupledSizeFiltering = true;
filter.MinWidth  = 70;
filter.MinHeight = 70;
// apply the filter
filter.ApplyInPlace(image);
Initial image:
Result image:
See also
BlobCounter, BlobCounterBase
Constructor & Destructor Documentation
BlobsFiltering() [1/4]
AForge.Imaging.Filters.BlobsFiltering.BlobsFiltering () inline
Initializes a new instance of the BlobsFiltering class.
References AForge.Imaging.Filters.BlobsFiltering.blobCounter, AForge.Imaging.BlobCounterBase.FilterBlobs, AForge.Imaging.Filters.BlobsFiltering.formatTranslations, AForge.Imaging.BlobCounterBase.MaxHeight, AForge.Imaging.BlobCounterBase.MaxWidth, AForge.Imaging.BlobCounterBase.MinHeight, and AForge.Imaging.BlobCounterBase.MinWidth.
BlobsFiltering() [2/4]
AForge.Imaging.Filters.BlobsFiltering.BlobsFiltering (int minWidth, int minHeight, int maxWidth, int maxHeight) inline
Initializes a new instance of the BlobsFiltering class.
Parameters
minWidth Minimum allowed width of blob.
minHeight Minimum allowed height of blob.
maxWidth Maximum allowed width of blob.
maxHeight Maximum allowed height of blob.
This constructor creates an instance of BlobsFiltering class with CoupledSizeFiltering property set to false.
BlobsFiltering() [3/4]
AForge.Imaging.Filters.BlobsFiltering.BlobsFiltering (int minWidth, int minHeight, int maxWidth, int maxHeight, bool coupledSizeFiltering) inline
Initializes a new instance of the BlobsFiltering class.
Parameters
minWidth Minimum allowed width of blob.
minHeight Minimum allowed height of blob.
maxWidth Maximum allowed width of blob.
maxHeight Maximum allowed height of blob.
coupledSizeFiltering Specifies if size filetering should be coupled or not.
For information about coupled filtering mode see documentation for BlobCounterBase.CoupledSizeFiltering property of BlobCounterBase class.
References AForge.Imaging.Filters.BlobsFiltering.blobCounter, AForge.Imaging.BlobCounterBase.CoupledSizeFiltering, AForge.Imaging.BlobCounterBase.MaxHeight, AForge.Imaging.BlobCounterBase.MaxWidth, AForge.Imaging.BlobCounterBase.MinHeight, and AForge.Imaging.BlobCounterBase.MinWidth.
BlobsFiltering() [4/4]
AForge.Imaging.Filters.BlobsFiltering.BlobsFiltering (IBlobsFilter blobsFilter) inline
Initializes a new instance of the BlobsFiltering class.
Parameters
blobsFilter Custom blobs' filtering routine to use (see BlobCounterBase.BlobsFilter).
References AForge.Imaging.Filters.BlobsFiltering.blobCounter, and AForge.Imaging.BlobCounterBase.BlobsFilter.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.BlobsFiltering.ProcessFilter (UnmanagedImage image) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
Implements AForge.Imaging.Filters.BaseInPlaceFilter.
References AForge.Imaging.RGB.B, AForge.Imaging.Filters.BlobsFiltering.blobCounter, AForge.Imaging.RGB.G, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.BlobCounterBase.ObjectLabels, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.BlobCounterBase.ProcessImage(), AForge.Imaging.RGB.R, AForge.Imaging.UnmanagedImage.Stride, and AForge.Imaging.UnmanagedImage.Width.
Member Data Documentation
blobCounter
BlobCounter AForge.Imaging.Filters.BlobsFiltering.blobCounter = new BlobCounter() private
Referenced by AForge.Imaging.Filters.BlobsFiltering.BlobsFiltering(), and AForge.Imaging.Filters.BlobsFiltering.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.BlobsFiltering.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.BlobsFiltering.BlobsFiltering().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.BlobsFiltering.FormatTranslations get
Format translations dictionary.
CoupledSizeFiltering
bool AForge.Imaging.Filters.BlobsFiltering.CoupledSizeFiltering get set
Specifies if size filetering should be coupled or not.
See documentation for BlobCounterBase.CoupledSizeFiltering property of BlobCounterBase class for more information.
MinWidth
int AForge.Imaging.Filters.BlobsFiltering.MinWidth get set
Minimum allowed width of blob.
MinHeight
int AForge.Imaging.Filters.BlobsFiltering.MinHeight get set
Minimum allowed height of blob.
MaxWidth
int AForge.Imaging.Filters.BlobsFiltering.MaxWidth get set
Maximum allowed width of blob.
MaxHeight
int AForge.Imaging.Filters.BlobsFiltering.MaxHeight get set
Maximum allowed height of blob.
BlobsFilter
IBlobsFilter AForge.Imaging.Filters.BlobsFiltering.BlobsFilter get set
Custom blobs' filter to use.
See BlobCounterBase.BlobsFilter for information about custom blobs' filtering routine.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Other/BlobsFiltering.cs