Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLANST Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLANST Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLANST (LSAME lsame, DLASSQ dlassq)
DLANST ()
double Run (string NORM, int N, double[] D, int offset_d, double[] E, int offset_e)
Private Attributes
LSAME _lsame
DLASSQ _dlassq
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLANST returns the value of the one norm, or the Frobenius norm, or the infinity norm, or the element of largest absolute value of a real symmetric tridiagonal matrix A.
Description
DLANST returns the value
DLANST = (max(abs(A(i,j))), NORM = 'M' or 'm' ((norm1(A), NORM = '1', 'O' or 'o' ((normI(A), NORM = 'I' or 'i' ((normF(A), NORM = 'F', 'f', 'E' or 'e'
where norm1 denotes the one norm of a matrix (maximum column sum), normI denotes the infinity norm of a matrix (maximum row sum) and normF denotes the Frobenius norm of a matrix (square root of sum of squares). Note that max(abs(A(i,j))) is not a consistent matrix norm.
/summary>
Constructor & Destructor Documentation
DLANST() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLANST.DLANST (LSAME lsame, DLASSQ dlassq) inline
DLANST() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLANST.DLANST () inline
Member Function Documentation
Run()
double DotNumerics.LinearAlgebra.CSLapack.DLANST.Run (string NORM, int N, double[] D, int offset_d, double[] E, int offset_e) inline
Purpose
DLANST returns the value of the one norm, or the Frobenius norm, or the infinity norm, or the element of largest absolute value of a real symmetric tridiagonal matrix A.
Description
DLANST returns the value
DLANST = (max(abs(A(i,j))), NORM = 'M' or 'm' ((norm1(A), NORM = '1', 'O' or 'o' ((normI(A), NORM = 'I' or 'i' ((normF(A), NORM = 'F', 'f', 'E' or 'e'
where norm1 denotes the one norm of a matrix (maximum column sum), normI denotes the infinity norm of a matrix (maximum row sum) and normF denotes the Frobenius norm of a matrix (square root of sum of squares). Note that max(abs(A(i,j))) is not a consistent matrix norm.
/summary>
Parameters
NORM (input) CHARACTER*1 Specifies the value to be returned in DLANST as described above. /param>
Parameters
N (input) INTEGER The order of the matrix A. N .GE. 0. When N = 0, DLANST is set to zero. /param>
Parameters
D (input) DOUBLE PRECISION array, dimension (N) The diagonal elements of A. /param>
Parameters
E (input) DOUBLE PRECISION array, dimension (N-1) The (n-1) sub-diagonal or super-diagonal elements of A. /param>
References DotNumerics.LinearAlgebra.CSLapack.DLANST.ONE, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASSQ.Run(), and DotNumerics.LinearAlgebra.CSLapack.DLANST.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DSTERF.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALSD.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEDC.Run(), and DotNumerics.LinearAlgebra.CSLapack.DBDSDC.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLANST._lsame private
_dlassq
DLASSQ DotNumerics.LinearAlgebra.CSLapack.DLANST._dlassq private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLANST.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLANST.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLANST.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLANST.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlanst.cs