Doc: IGLib EXTENDED: IG.Forms.BrowserSimpleControl Class Reference
IG.Forms.BrowserSimpleControl Class Reference
Public Member Functions
BrowserSimpleControl ()
virtual void OpenLocation (string location)
Static Public Attributes
const string DefaultHomeUrl = Util.IGLibUrl
const string DefaultSearchUrl = "http://www.google.com"
const string DefaultFileToOpen = "d:/users/igor/0000/tmp/index.html"
Protected Member Functions
virtual void FetchBrowserInitialPosition ()
Obtains browser y position and height of the panel containing controls.
virtual void SetBrowserPositionOriginal ()
Sets the browser y position within the form to its original position.
virtual void SetBrowserPositionWithoutControls ()
Sets browser y position for the situation where browser controls are not visible.
void ReportError (Exception ex)
Reports the error that occurred in the current window control.
void ReportError (string errorMessage)
Reports the error that occurred in the current window control.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
string _homeUrl = DefaultHomeUrl
string _searchUrl = DefaultSearchUrl
string _fileToOpen
Properties
object Lock [get]
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
string HomeUrl [get, set]
Home page Url.
string SearchUrl [get, set]
Home page Url.
string FileToOpen [get, set]
File to be opened in the file open dialog box.
Private Member Functions
void UpdateUrlToAdressBar ()
Sets browser URL to the text from the address bar.
void UpdateUrl (string urlString)
Sets browser URL to the specified text.
void txtAddressBar_Leave (object sender, EventArgs e)
void buttonHome_Click (object sender, EventArgs e)
void buttonBack_Click (object sender, EventArgs e)
void buttonForward_Click (object sender, EventArgs e)
void buttonRefresh_Click (object sender, EventArgs e)
void txtAddressBar_KeyPress (object sender, KeyPressEventArgs e)
void buttonSubmit_Click (object sender, EventArgs e)
void buttonStop_Click (object sender, EventArgs e)
void webBrowser_DocumentCompleted (object sender, WebBrowserDocumentCompletedEventArgs e)
void webBrowser_Navigating (object sender, WebBrowserNavigatingEventArgs e)
void webBrowser_CanGoBackChanged (object sender, EventArgs e)
void webBrowser_CanGoForwardChanged (object sender, EventArgs e)
void HideTopPanel ()
void ShowTopPanel ()
void TopPnlHideBtn_Click (object sender, EventArgs e)
void MenuTools_Controls_CheckStateChanged (object sender, EventArgs e)
void BrowserSimpleControl_VisibleChanged (object sender, EventArgs e)
void MenuFile_OpenURL_Click (object sender, EventArgs e)
void homeToolStripMenuItem_Click (object sender, EventArgs e)
void googleToolStripMenuItem_Click (object sender, EventArgs e)
void otherToolStripMenuItem_Click (object sender, EventArgs e)
void MenuFile_Open_Click (object sender, EventArgs e)
void printPreviewToolStripMenuItem_Click (object sender, EventArgs e)
void printToolStripMenuItem_Click (object sender, EventArgs e)
void MenuFile_Close_Click (object sender, EventArgs e)
void MenuFile_CloseDocument_Click (object sender, EventArgs e)
void MenuHelp_About_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
object _mainLock = new object()
bool _browserPositionRemembered = false
int _browserYInitialPosition = 0
int _controlPanelHeigt = 0
int _statusStripHeight = 0
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.StatusStrip statusStrip1
System.Windows.Forms.ToolStripStatusLabel StatusType
System.Windows.Forms.ToolStripStatusLabel StatusPath
System.Windows.Forms.ToolStripStatusLabel StatusError
System.Windows.Forms.ToolStripStatusLabel StatusStatus
System.Windows.Forms.MenuStrip menuStrip
System.Windows.Forms.ToolStripMenuItem MenuFile
System.Windows.Forms.ToolStripMenuItem MenuFile_OpenURL
System.Windows.Forms.ToolStripMenuItem MenuFile_Open
System.Windows.Forms.ToolStripMenuItem printPreviewToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem printToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem MenuFile_Close
System.Windows.Forms.ToolStripMenuItem MenuFile_CloseDocument
System.Windows.Forms.ToolStripMenuItem MenuTools
System.Windows.Forms.ToolStripMenuItem MenuTools_Controls
System.Windows.Forms.ToolStripSeparator toolStripSeparator5
System.Windows.Forms.ToolStripMenuItem MenuTools_Stop
System.Windows.Forms.ToolStripMenuItem MenuGelp
System.Windows.Forms.ToolStripMenuItem MenuHelp_About
System.Windows.Forms.WebBrowser browser
System.Windows.Forms.Panel ControlPnl
System.Windows.Forms.Button buttonBack
System.Windows.Forms.Button buttonForward
System.Windows.Forms.Button TopPnlHideBtn
System.Windows.Forms.Button buttonSubmit
System.Windows.Forms.TextBox txtAddressBar
System.Windows.Forms.Button buttonRefresh
System.Windows.Forms.Button buttonStop
System.Windows.Forms.Button buttonHome
System.Windows.Forms.Panel pnlOuter
System.Windows.Forms.ToolStripMenuItem homeToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem googleToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem otherToolStripMenuItem
System.Windows.Forms.OpenFileDialog openFileDialog
System.Windows.Forms.ToolStripSeparator toolStripSeparator1
System.Windows.Forms.ToolStripSeparator toolStripSeparator2
Constructor & Destructor Documentation
BrowserSimpleControl()
IG.Forms.BrowserSimpleControl.BrowserSimpleControl () inline
References IG.Forms.BrowserSimpleControl.buttonBack, IG.Forms.BrowserSimpleControl.buttonForward, IG.Forms.BrowserSimpleControl.buttonStop, IG.Forms.BrowserSimpleControl.FetchBrowserInitialPosition(), IG.Forms.BrowserSimpleControl.InitializeComponent(), and IG.Forms.BrowserSimpleControl.txtAddressBar.
Member Function Documentation
FetchBrowserInitialPosition()
virtual void IG.Forms.BrowserSimpleControl.FetchBrowserInitialPosition () inline protected virtual
Obtains browser y position and height of the panel containing controls.
References IG.Forms.BrowserSimpleControl._browserPositionRemembered, IG.Forms.BrowserSimpleControl._browserYInitialPosition, IG.Forms.BrowserSimpleControl._controlPanelHeigt, IG.Forms.BrowserSimpleControl._statusStripHeight, IG.Forms.BrowserSimpleControl.browser, IG.Forms.BrowserSimpleControl.ControlPnl, and IG.Forms.BrowserSimpleControl.statusStrip1.
Referenced by IG.Forms.BrowserSimpleControl.BrowserSimpleControl(), IG.Forms.BrowserSimpleControl.SetBrowserPositionOriginal(), and IG.Forms.BrowserSimpleControl.SetBrowserPositionWithoutControls().
SetBrowserPositionOriginal()
virtual void IG.Forms.BrowserSimpleControl.SetBrowserPositionOriginal () inline protected virtual
Sets the browser y position within the form to its original position.
References IG.Forms.BrowserSimpleControl._browserYInitialPosition, IG.Forms.BrowserSimpleControl.browser, IG.Forms.BrowserSimpleControl.FetchBrowserInitialPosition(), and IG.Forms.BrowserSimpleControl.statusStrip1.
Referenced by IG.Forms.BrowserSimpleControl.ShowTopPanel().
SetBrowserPositionWithoutControls()
virtual void IG.Forms.BrowserSimpleControl.SetBrowserPositionWithoutControls () inline protected virtual
Sets browser y position for the situation where browser controls are not visible.
References IG.Forms.BrowserSimpleControl._browserYInitialPosition, IG.Forms.BrowserSimpleControl._controlPanelHeigt, IG.Forms.BrowserSimpleControl.browser, IG.Forms.BrowserSimpleControl.FetchBrowserInitialPosition(), and IG.Forms.BrowserSimpleControl.statusStrip1.
Referenced by IG.Forms.BrowserSimpleControl.HideTopPanel().
OpenLocation()
virtual void IG.Forms.BrowserSimpleControl.OpenLocation (string location) inline virtual
References IG.Forms.BrowserSimpleControl.browser.
Referenced by IG.Forms.BrowserSimpleForm.OpenLocation(), and IG.Forms.BrowserSimpleWindow.OpenLocation().
ReportError() [1/2]
void IG.Forms.BrowserSimpleControl.ReportError (Exception ex) inline protected
Reports the error that occurred in the current window control.
Parameters
ex Exception that was thrown because of the error.
Referenced by IG.Forms.BrowserSimpleControl.buttonHome_Click(), IG.Forms.BrowserSimpleControl.buttonRefresh_Click(), IG.Forms.BrowserSimpleControl.MenuFile_Open_Click(), IG.Forms.BrowserSimpleControl.txtAddressBar_Leave(), IG.Forms.BrowserSimpleControl.UpdateUrl(), and IG.Forms.BrowserSimpleControl.UpdateUrlToAdressBar().
ReportError() [2/2]
void IG.Forms.BrowserSimpleControl.ReportError (string errorMessage) inline protected
Reports the error that occurred in the current window control.
Parameters
errorMessage Error message that describes the error.
UpdateUrlToAdressBar()
void IG.Forms.BrowserSimpleControl.UpdateUrlToAdressBar () inline private
Sets browser URL to the text from the address bar.
References IG.Forms.BrowserSimpleControl.ReportError(), IG.Forms.BrowserSimpleControl.txtAddressBar, and IG.Forms.BrowserSimpleControl.UpdateUrl().
Referenced by IG.Forms.BrowserSimpleControl.txtAddressBar_Leave().
UpdateUrl()
void IG.Forms.BrowserSimpleControl.UpdateUrl (string urlString) inline private
Sets browser URL to the specified text.
Parameters
urlString String representing the url to which address must be changed.
References IG.Forms.BrowserSimpleControl.browser, IG.Forms.BrowserSimpleControl.ReportError(), and IG.Forms.BrowserSimpleControl.txtAddressBar.
Referenced by IG.Forms.BrowserSimpleControl.buttonHome_Click(), and IG.Forms.BrowserSimpleControl.UpdateUrlToAdressBar().
txtAddressBar_Leave()
void IG.Forms.BrowserSimpleControl.txtAddressBar_Leave (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleControl.ReportError(), and IG.Forms.BrowserSimpleControl.UpdateUrlToAdressBar().
buttonHome_Click()
void IG.Forms.BrowserSimpleControl.buttonHome_Click (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleControl.HomeUrl, IG.Forms.BrowserSimpleControl.ReportError(), and IG.Forms.BrowserSimpleControl.UpdateUrl().
buttonBack_Click()
void IG.Forms.BrowserSimpleControl.buttonBack_Click (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleControl.browser, and IG.Forms.BrowserSimpleControl.txtAddressBar.
buttonForward_Click()
void IG.Forms.BrowserSimpleControl.buttonForward_Click (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleControl.browser, and IG.Forms.BrowserSimpleControl.txtAddressBar.
buttonRefresh_Click()
void IG.Forms.BrowserSimpleControl.buttonRefresh_Click (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleControl.browser, and IG.Forms.BrowserSimpleControl.ReportError().
txtAddressBar_KeyPress()
void IG.Forms.BrowserSimpleControl.txtAddressBar_KeyPress (object sender, KeyPressEventArgs e) inline private
References IG.Forms.BrowserSimpleControl.browser, and IG.Forms.BrowserSimpleControl.txtAddressBar.
buttonSubmit_Click()
void IG.Forms.BrowserSimpleControl.buttonSubmit_Click (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleControl.browser, and IG.Forms.BrowserSimpleControl.txtAddressBar.
buttonStop_Click()
void IG.Forms.BrowserSimpleControl.buttonStop_Click (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleControl.browser.
webBrowser_DocumentCompleted()
void IG.Forms.BrowserSimpleControl.webBrowser_DocumentCompleted (object sender, WebBrowserDocumentCompletedEventArgs e) inline private
References IG.Forms.BrowserSimpleControl.browser, IG.Forms.BrowserSimpleControl.buttonBack, IG.Forms.BrowserSimpleControl.buttonForward, IG.Forms.BrowserSimpleControl.buttonStop, and IG.Forms.BrowserSimpleControl.txtAddressBar.
webBrowser_Navigating()
void IG.Forms.BrowserSimpleControl.webBrowser_Navigating (object sender, WebBrowserNavigatingEventArgs e) inline private
References IG.Forms.BrowserSimpleControl.buttonStop.
webBrowser_CanGoBackChanged()
void IG.Forms.BrowserSimpleControl.webBrowser_CanGoBackChanged (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleControl.browser, and IG.Forms.BrowserSimpleControl.buttonBack.
webBrowser_CanGoForwardChanged()
void IG.Forms.BrowserSimpleControl.webBrowser_CanGoForwardChanged (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleControl.browser, and IG.Forms.BrowserSimpleControl.buttonForward.
HideTopPanel()
void IG.Forms.BrowserSimpleControl.HideTopPanel () inline private
References IG.Forms.BrowserSimpleControl.ControlPnl, and IG.Forms.BrowserSimpleControl.SetBrowserPositionWithoutControls().
Referenced by IG.Forms.BrowserSimpleControl.MenuTools_Controls_CheckStateChanged().
ShowTopPanel()
void IG.Forms.BrowserSimpleControl.ShowTopPanel () inline private
References IG.Forms.BrowserSimpleControl.ControlPnl, and IG.Forms.BrowserSimpleControl.SetBrowserPositionOriginal().
Referenced by IG.Forms.BrowserSimpleControl.MenuTools_Controls_CheckStateChanged().
TopPnlHideBtn_Click()
void IG.Forms.BrowserSimpleControl.TopPnlHideBtn_Click (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleControl.MenuTools_Controls.
MenuTools_Controls_CheckStateChanged()
void IG.Forms.BrowserSimpleControl.MenuTools_Controls_CheckStateChanged (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleControl.HideTopPanel(), and IG.Forms.BrowserSimpleControl.ShowTopPanel().
BrowserSimpleControl_VisibleChanged()
void IG.Forms.BrowserSimpleControl.BrowserSimpleControl_VisibleChanged (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleControl.txtAddressBar.
MenuFile_OpenURL_Click()
void IG.Forms.BrowserSimpleControl.MenuFile_OpenURL_Click (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleControl.txtAddressBar.
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
homeToolStripMenuItem_Click()
void IG.Forms.BrowserSimpleControl.homeToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleControl.browser, and IG.Forms.BrowserSimpleControl.HomeUrl.
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
googleToolStripMenuItem_Click()
void IG.Forms.BrowserSimpleControl.googleToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleControl.browser, and IG.Forms.BrowserSimpleControl.SearchUrl.
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
otherToolStripMenuItem_Click()
void IG.Forms.BrowserSimpleControl.otherToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleControl.txtAddressBar.
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
MenuFile_Open_Click()
void IG.Forms.BrowserSimpleControl.MenuFile_Open_Click (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleControl.browser, IG.Forms.BrowserSimpleControl.FileToOpen, IG.Forms.BrowserSimpleControl.openFileDialog, and IG.Forms.BrowserSimpleControl.ReportError().
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
printPreviewToolStripMenuItem_Click()
void IG.Forms.BrowserSimpleControl.printPreviewToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleControl.browser.
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
printToolStripMenuItem_Click()
void IG.Forms.BrowserSimpleControl.printToolStripMenuItem_Click (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleControl.browser.
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
MenuFile_Close_Click()
void IG.Forms.BrowserSimpleControl.MenuFile_Close_Click (object sender, EventArgs e) inline private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
MenuFile_CloseDocument_Click()
void IG.Forms.BrowserSimpleControl.MenuFile_CloseDocument_Click (object sender, EventArgs e) inline private
References IG.Forms.BrowserSimpleControl.browser.
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
MenuHelp_About_Click()
void IG.Forms.BrowserSimpleControl.MenuHelp_About_Click (object sender, EventArgs e) inline private
References IG.Lib.Util.IGLibUrl.
Dispose()
override void IG.Forms.BrowserSimpleControl.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.BrowserSimpleControl.components.
InitializeComponent()
void IG.Forms.BrowserSimpleControl.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.BrowserSimpleControl.browser, IG.Forms.BrowserSimpleControl.buttonBack, IG.Forms.BrowserSimpleControl.buttonForward, IG.Forms.BrowserSimpleControl.buttonHome, IG.Forms.BrowserSimpleControl.buttonRefresh, IG.Forms.BrowserSimpleControl.buttonStop, IG.Forms.BrowserSimpleControl.buttonSubmit, IG.Forms.BrowserSimpleControl.ControlPnl, IG.Forms.BrowserSimpleControl.googleToolStripMenuItem, IG.Forms.BrowserSimpleControl.googleToolStripMenuItem_Click(), IG.Forms.BrowserSimpleControl.homeToolStripMenuItem, IG.Forms.BrowserSimpleControl.homeToolStripMenuItem_Click(), IG.Forms.BrowserSimpleControl.MenuFile, IG.Forms.BrowserSimpleControl.MenuFile_Close, IG.Forms.BrowserSimpleControl.MenuFile_Close_Click(), IG.Forms.BrowserSimpleControl.MenuFile_CloseDocument, IG.Forms.BrowserSimpleControl.MenuFile_CloseDocument_Click(), IG.Forms.BrowserSimpleControl.MenuFile_Open, IG.Forms.BrowserSimpleControl.MenuFile_Open_Click(), IG.Forms.BrowserSimpleControl.MenuFile_OpenURL, IG.Forms.BrowserSimpleControl.MenuFile_OpenURL_Click(), IG.Forms.BrowserSimpleControl.MenuGelp, IG.Forms.BrowserSimpleControl.MenuHelp_About, IG.Forms.BrowserSimpleControl.menuStrip, IG.Forms.BrowserSimpleControl.MenuTools, IG.Forms.BrowserSimpleControl.MenuTools_Controls, IG.Forms.BrowserSimpleControl.MenuTools_Stop, IG.Forms.BrowserSimpleControl.openFileDialog, IG.Forms.BrowserSimpleControl.otherToolStripMenuItem, IG.Forms.BrowserSimpleControl.otherToolStripMenuItem_Click(), IG.Forms.BrowserSimpleControl.pnlOuter, IG.Forms.BrowserSimpleControl.printPreviewToolStripMenuItem, IG.Forms.BrowserSimpleControl.printPreviewToolStripMenuItem_Click(), IG.Forms.BrowserSimpleControl.printToolStripMenuItem, IG.Forms.BrowserSimpleControl.printToolStripMenuItem_Click(), IG.Forms.BrowserSimpleControl.StatusError, IG.Forms.BrowserSimpleControl.StatusPath, IG.Forms.BrowserSimpleControl.StatusStatus, IG.Forms.BrowserSimpleControl.statusStrip1, IG.Forms.BrowserSimpleControl.StatusType, IG.Forms.BrowserSimpleControl.toolStripSeparator1, IG.Forms.BrowserSimpleControl.toolStripSeparator2, IG.Forms.BrowserSimpleControl.toolStripSeparator5, IG.Forms.BrowserSimpleControl.TopPnlHideBtn, and IG.Forms.BrowserSimpleControl.txtAddressBar.
Referenced by IG.Forms.BrowserSimpleControl.BrowserSimpleControl().
Member Data Documentation
_mainLock
object IG.Forms.BrowserSimpleControl._mainLock = new object() private
_browserPositionRemembered
bool IG.Forms.BrowserSimpleControl._browserPositionRemembered = false private
Referenced by IG.Forms.BrowserSimpleControl.FetchBrowserInitialPosition().
_browserYInitialPosition
int IG.Forms.BrowserSimpleControl._browserYInitialPosition = 0 private
Referenced by IG.Forms.BrowserSimpleControl.FetchBrowserInitialPosition(), IG.Forms.BrowserSimpleControl.SetBrowserPositionOriginal(), and IG.Forms.BrowserSimpleControl.SetBrowserPositionWithoutControls().
_controlPanelHeigt
int IG.Forms.BrowserSimpleControl._controlPanelHeigt = 0 private
Referenced by IG.Forms.BrowserSimpleControl.FetchBrowserInitialPosition(), and IG.Forms.BrowserSimpleControl.SetBrowserPositionWithoutControls().
_statusStripHeight
int IG.Forms.BrowserSimpleControl._statusStripHeight = 0 private
Referenced by IG.Forms.BrowserSimpleControl.FetchBrowserInitialPosition().
DefaultHomeUrl
const string IG.Forms.BrowserSimpleControl.DefaultHomeUrl = Util.IGLibUrl static
_homeUrl
string IG.Forms.BrowserSimpleControl._homeUrl = DefaultHomeUrl protected
DefaultSearchUrl
const string IG.Forms.BrowserSimpleControl.DefaultSearchUrl = "http://www.google.com" static
_searchUrl
string IG.Forms.BrowserSimpleControl._searchUrl = DefaultSearchUrl protected
DefaultFileToOpen
const string IG.Forms.BrowserSimpleControl.DefaultFileToOpen = "d:/users/igor/0000/tmp/index.html" static
_fileToOpen
string IG.Forms.BrowserSimpleControl._fileToOpen protected
components
System.ComponentModel.IContainer IG.Forms.BrowserSimpleControl.components = null private
Required designer variable.
Referenced by IG.Forms.BrowserSimpleControl.Dispose().
statusStrip1
System.Windows.Forms.StatusStrip IG.Forms.BrowserSimpleControl.statusStrip1 private
Referenced by IG.Forms.BrowserSimpleControl.FetchBrowserInitialPosition(), IG.Forms.BrowserSimpleControl.InitializeComponent(), IG.Forms.BrowserSimpleControl.SetBrowserPositionOriginal(), and IG.Forms.BrowserSimpleControl.SetBrowserPositionWithoutControls().
StatusType
System.Windows.Forms.ToolStripStatusLabel IG.Forms.BrowserSimpleControl.StatusType private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
StatusPath
System.Windows.Forms.ToolStripStatusLabel IG.Forms.BrowserSimpleControl.StatusPath private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
StatusError
System.Windows.Forms.ToolStripStatusLabel IG.Forms.BrowserSimpleControl.StatusError private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
StatusStatus
System.Windows.Forms.ToolStripStatusLabel IG.Forms.BrowserSimpleControl.StatusStatus private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
menuStrip
System.Windows.Forms.MenuStrip IG.Forms.BrowserSimpleControl.menuStrip private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
MenuFile
System.Windows.Forms.ToolStripMenuItem IG.Forms.BrowserSimpleControl.MenuFile private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
MenuFile_OpenURL
System.Windows.Forms.ToolStripMenuItem IG.Forms.BrowserSimpleControl.MenuFile_OpenURL private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
MenuFile_Open
System.Windows.Forms.ToolStripMenuItem IG.Forms.BrowserSimpleControl.MenuFile_Open private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
printPreviewToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem IG.Forms.BrowserSimpleControl.printPreviewToolStripMenuItem private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
printToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem IG.Forms.BrowserSimpleControl.printToolStripMenuItem private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
MenuFile_Close
System.Windows.Forms.ToolStripMenuItem IG.Forms.BrowserSimpleControl.MenuFile_Close private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
MenuFile_CloseDocument
System.Windows.Forms.ToolStripMenuItem IG.Forms.BrowserSimpleControl.MenuFile_CloseDocument private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
MenuTools
System.Windows.Forms.ToolStripMenuItem IG.Forms.BrowserSimpleControl.MenuTools private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
MenuTools_Controls
System.Windows.Forms.ToolStripMenuItem IG.Forms.BrowserSimpleControl.MenuTools_Controls private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent(), and IG.Forms.BrowserSimpleControl.TopPnlHideBtn_Click().
toolStripSeparator5
System.Windows.Forms.ToolStripSeparator IG.Forms.BrowserSimpleControl.toolStripSeparator5 private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
MenuTools_Stop
System.Windows.Forms.ToolStripMenuItem IG.Forms.BrowserSimpleControl.MenuTools_Stop private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
MenuGelp
System.Windows.Forms.ToolStripMenuItem IG.Forms.BrowserSimpleControl.MenuGelp private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
MenuHelp_About
System.Windows.Forms.ToolStripMenuItem IG.Forms.BrowserSimpleControl.MenuHelp_About private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
browser
System.Windows.Forms.WebBrowser IG.Forms.BrowserSimpleControl.browser private
Referenced by IG.Forms.BrowserSimpleControl.buttonBack_Click(), IG.Forms.BrowserSimpleControl.buttonForward_Click(), IG.Forms.BrowserSimpleControl.buttonRefresh_Click(), IG.Forms.BrowserSimpleControl.buttonStop_Click(), IG.Forms.BrowserSimpleControl.buttonSubmit_Click(), IG.Forms.BrowserSimpleControl.FetchBrowserInitialPosition(), IG.Forms.BrowserSimpleControl.googleToolStripMenuItem_Click(), IG.Forms.BrowserSimpleControl.homeToolStripMenuItem_Click(), IG.Forms.BrowserSimpleControl.InitializeComponent(), IG.Forms.BrowserSimpleControl.MenuFile_CloseDocument_Click(), IG.Forms.BrowserSimpleControl.MenuFile_Open_Click(), IG.Forms.BrowserSimpleControl.OpenLocation(), IG.Forms.BrowserSimpleControl.printPreviewToolStripMenuItem_Click(), IG.Forms.BrowserSimpleControl.printToolStripMenuItem_Click(), IG.Forms.BrowserSimpleControl.SetBrowserPositionOriginal(), IG.Forms.BrowserSimpleControl.SetBrowserPositionWithoutControls(), IG.Forms.BrowserSimpleControl.txtAddressBar_KeyPress(), IG.Forms.BrowserSimpleControl.UpdateUrl(), IG.Forms.BrowserSimpleControl.webBrowser_CanGoBackChanged(), IG.Forms.BrowserSimpleControl.webBrowser_CanGoForwardChanged(), and IG.Forms.BrowserSimpleControl.webBrowser_DocumentCompleted().
ControlPnl
System.Windows.Forms.Panel IG.Forms.BrowserSimpleControl.ControlPnl private
Referenced by IG.Forms.BrowserSimpleControl.FetchBrowserInitialPosition(), IG.Forms.BrowserSimpleControl.HideTopPanel(), IG.Forms.BrowserSimpleControl.InitializeComponent(), and IG.Forms.BrowserSimpleControl.ShowTopPanel().
buttonBack
System.Windows.Forms.Button IG.Forms.BrowserSimpleControl.buttonBack private
Referenced by IG.Forms.BrowserSimpleControl.BrowserSimpleControl(), IG.Forms.BrowserSimpleControl.InitializeComponent(), IG.Forms.BrowserSimpleControl.webBrowser_CanGoBackChanged(), and IG.Forms.BrowserSimpleControl.webBrowser_DocumentCompleted().
buttonForward
System.Windows.Forms.Button IG.Forms.BrowserSimpleControl.buttonForward private
Referenced by IG.Forms.BrowserSimpleControl.BrowserSimpleControl(), IG.Forms.BrowserSimpleControl.InitializeComponent(), IG.Forms.BrowserSimpleControl.webBrowser_CanGoForwardChanged(), and IG.Forms.BrowserSimpleControl.webBrowser_DocumentCompleted().
TopPnlHideBtn
System.Windows.Forms.Button IG.Forms.BrowserSimpleControl.TopPnlHideBtn private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
buttonSubmit
System.Windows.Forms.Button IG.Forms.BrowserSimpleControl.buttonSubmit private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
txtAddressBar
System.Windows.Forms.TextBox IG.Forms.BrowserSimpleControl.txtAddressBar private
Referenced by IG.Forms.BrowserSimpleControl.BrowserSimpleControl(), IG.Forms.BrowserSimpleControl.BrowserSimpleControl_VisibleChanged(), IG.Forms.BrowserSimpleControl.buttonBack_Click(), IG.Forms.BrowserSimpleControl.buttonForward_Click(), IG.Forms.BrowserSimpleControl.buttonSubmit_Click(), IG.Forms.BrowserSimpleControl.InitializeComponent(), IG.Forms.BrowserSimpleControl.MenuFile_OpenURL_Click(), IG.Forms.BrowserSimpleControl.otherToolStripMenuItem_Click(), IG.Forms.BrowserSimpleControl.txtAddressBar_KeyPress(), IG.Forms.BrowserSimpleControl.UpdateUrl(), IG.Forms.BrowserSimpleControl.UpdateUrlToAdressBar(), and IG.Forms.BrowserSimpleControl.webBrowser_DocumentCompleted().
buttonRefresh
System.Windows.Forms.Button IG.Forms.BrowserSimpleControl.buttonRefresh private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
buttonStop
System.Windows.Forms.Button IG.Forms.BrowserSimpleControl.buttonStop private
Referenced by IG.Forms.BrowserSimpleControl.BrowserSimpleControl(), IG.Forms.BrowserSimpleControl.InitializeComponent(), IG.Forms.BrowserSimpleControl.webBrowser_DocumentCompleted(), and IG.Forms.BrowserSimpleControl.webBrowser_Navigating().
buttonHome
System.Windows.Forms.Button IG.Forms.BrowserSimpleControl.buttonHome private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
pnlOuter
System.Windows.Forms.Panel IG.Forms.BrowserSimpleControl.pnlOuter private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
homeToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem IG.Forms.BrowserSimpleControl.homeToolStripMenuItem private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
googleToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem IG.Forms.BrowserSimpleControl.googleToolStripMenuItem private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
otherToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem IG.Forms.BrowserSimpleControl.otherToolStripMenuItem private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
openFileDialog
System.Windows.Forms.OpenFileDialog IG.Forms.BrowserSimpleControl.openFileDialog private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent(), and IG.Forms.BrowserSimpleControl.MenuFile_Open_Click().
toolStripSeparator1
System.Windows.Forms.ToolStripSeparator IG.Forms.BrowserSimpleControl.toolStripSeparator1 private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
toolStripSeparator2
System.Windows.Forms.ToolStripSeparator IG.Forms.BrowserSimpleControl.toolStripSeparator2 private
Referenced by IG.Forms.BrowserSimpleControl.InitializeComponent().
Property Documentation
Lock
object IG.Forms.BrowserSimpleControl.Lock get
This object's central lock object to be used by other object. Do not use this object for locking in class' methods, for this you should use InternalLock.
HomeUrl
string IG.Forms.BrowserSimpleControl.HomeUrl get set
Home page Url.
Referenced by IG.Forms.BrowserSimpleControl.buttonHome_Click(), IG.Forms.BrowserSimpleControl.homeToolStripMenuItem_Click(), IG.Forms.BrowserSimpleForm.InitializeComponent(), and IG.Forms.BrowserSimpleWindow.InitializeComponent().
SearchUrl
string IG.Forms.BrowserSimpleControl.SearchUrl get set
Home page Url.
Referenced by IG.Forms.BrowserSimpleControl.googleToolStripMenuItem_Click(), and IG.Forms.BrowserSimpleForm.InitializeComponent().
FileToOpen
string IG.Forms.BrowserSimpleControl.FileToOpen get set
File to be opened in the file open dialog box.
Used for setting initial directory for the dialog box. Each time this property is reset to the last file path picked from the dialog box.
Referenced by IG.Forms.BrowserSimpleForm.InitializeComponent(), and IG.Forms.BrowserSimpleControl.MenuFile_Open_Click().
The documentation for this class was generated from the following files:
iglib/igforms/Basic/BrowserSimpleControl.cs
iglib/igforms/Basic/BrowserSimpleControl.Designer.cs