Doc: IGLib EXTENDED: NUnit.Framework.Constraints.NotConstraintTests Class Reference
NUnit.Framework.Constraints.NotConstraintTests Class Reference
Public Member Functions
void SetUp ()
void NotHonorsIgnoreCaseUsingConstructors ()
void NotHonorsIgnoreCaseUsingPrefixNotation ()
void NotHonorsTolerance ()
void CanUseNotOperator ()
Public Member Functions inherited from NUnit.Framework.Constraints.ConstraintTestBase
void SucceedsWithGoodValues (object value)
void FailsWithBadValues (object badValue, string message)
Public Member Functions inherited from NUnit.Framework.Constraints.ConstraintTestBaseNoData
void ProvidesProperDescription ()
void ProvidesProperStringRepresentation ()
Static Private Attributes
static object[] SuccessData = new object[] { 42, "Hello" }
static object[] FailureData = new object [] { new object[] { null, "null" } }
Additional Inherited Members
Protected Attributes inherited from NUnit.Framework.Constraints.ConstraintTestBaseNoData
Constraint theConstraint
string expectedDescription = "<NOT SET>"
string stringRepresentation = "<NOT SET>"
Member Function Documentation
SetUp()
void NUnit.Framework.Constraints.NotConstraintTests.SetUp () inline
References NUnit.Framework.Constraints.ConstraintTestBaseNoData.expectedDescription, NUnit.Framework.Constraints.ConstraintTestBaseNoData.stringRepresentation, and NUnit.Framework.Constraints.ConstraintTestBaseNoData.theConstraint.
NotHonorsIgnoreCaseUsingConstructors()
void NUnit.Framework.Constraints.NotConstraintTests.NotHonorsIgnoreCaseUsingConstructors () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
NotHonorsIgnoreCaseUsingPrefixNotation()
void NUnit.Framework.Constraints.NotConstraintTests.NotHonorsIgnoreCaseUsingPrefixNotation () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Constraints.ConstraintExpression.EqualTo(), NUnit.Framework.Constraints.EqualConstraint.IgnoreCase, NUnit.Framework.Is.Not, NUnit.Framework.Assert.That(), and NUnit.Framework.Assert.Throws().
NotHonorsTolerance()
void NUnit.Framework.Constraints.NotConstraintTests.NotHonorsTolerance () inline
References NUnit.Framework.Does.Contain(), NUnit.Framework.Constraints.ConstraintExpression.EqualTo(), NUnit.Framework.Is.Not, NUnit.Framework.Assert.That(), NUnit.Framework.Assert.Throws(), and NUnit.Framework.Constraints.EqualConstraint.Within().
CanUseNotOperator()
void NUnit.Framework.Constraints.NotConstraintTests.CanUseNotOperator () inline
References NUnit.Framework.Assert.That().
Member Data Documentation
SuccessData
object [] NUnit.Framework.Constraints.NotConstraintTests.SuccessData = new object[] { 42, "Hello" } static private
FailureData
object [] NUnit.Framework.Constraints.NotConstraintTests.FailureData = new object [] { new object[] { null, "null" } } static private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Constraints/NotConstraintTests.cs