Doc: IGLib EXTENDED: alglib.testfhtunit Class Reference
alglib.testfhtunit Class Reference
Static Public Member Functions
static bool testfht (bool silent)
static bool testfht (bool silent)
static bool _pexec_testfht (bool silent)
Static Private Member Functions
static void reffhtr1d (ref double[] a, int n)
static void reffhtr1dinv (ref double[] a, int n)
static void reffhtr1d (ref double[] a, int n)
static void reffhtr1dinv (ref double[] a, int n)
Member Function Documentation
testfht() [1/2]
static bool alglib.testfhtunit.testfht (bool silent) inline static
References alglib.fht.fhtr1d(), alglib.fht.fhtr1dinv(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.testfhtunit.reffhtr1d(), and alglib.testfhtunit.reffhtr1dinv().
Referenced by alglib.testfhtunit._pexec_testfht(), and _Test.Main().
reffhtr1d() [1/2]
static void alglib.testfhtunit.reffhtr1d (ref double[] a, int n) inline static private
References alglib.ap.assert().
Referenced by alglib.testfhtunit.reffhtr1dinv(), and alglib.testfhtunit.testfht().
reffhtr1dinv() [1/2]
static void alglib.testfhtunit.reffhtr1dinv (ref double[] a, int n) inline static private
References alglib.ap.assert(), and alglib.testfhtunit.reffhtr1d().
Referenced by alglib.testfhtunit.testfht().
testfht() [2/2]
static bool alglib.testfhtunit.testfht (bool silent) inline static
References alglib.fht.fhtr1d(), alglib.fht.fhtr1dinv(), alglib.math.machineepsilon, alglib.math.randomreal(), alglib.testfhtunit.reffhtr1d(), and alglib.testfhtunit.reffhtr1dinv().
_pexec_testfht()
static bool alglib.testfhtunit._pexec_testfht (bool silent) inline static
References alglib.testfhtunit.testfht().
Referenced by _Test.Main().
reffhtr1d() [2/2]
static void alglib.testfhtunit.reffhtr1d (ref double[] a, int n) inline static private
References alglib.ap.assert().
reffhtr1dinv() [2/2]
static void alglib.testfhtunit.reffhtr1dinv (ref double[] a, int n) inline static private
References alglib.ap.assert(), and alglib.testfhtunit.reffhtr1d().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs