Doc: IGLib EXTENDED: alglib.testrbfunit Class Reference
alglib.testrbfunit Class Reference
Static Public Member Functions
static bool testrbf (bool silent)
static bool sqrdegmatrixrbftest (bool silent)
static bool basicmultilayerrbf1dtest ()
static bool testrbf (bool silent)
static bool _pexec_testrbf (bool silent)
static bool sqrdegmatrixrbftest (bool silent)
static bool basicmultilayerrbf1dtest ()
Static Public Attributes
const int mxnx = 3
const double eps = 1.0E-6
const double tol = 1.0E-10
const int mxits = 0
const double heps = 1.0E-12
Static Private Member Functions
static bool specialtest ()
static bool basicrbftest ()
static bool irregularrbftest ()
static bool linearitymodelrbftest ()
static bool serializationtest ()
static bool searcherr (double[,] y0, double[,] y1, int n, int ny, int errtype, double[] b1, double[] delta)
static bool basicmultilayerrbftest ()
static bool specialtest ()
static bool basicrbftest ()
static bool irregularrbftest ()
static bool linearitymodelrbftest ()
static bool serializationtest ()
static bool searcherr (double[,] y0, double[,] y1, int n, int ny, int errtype, double[] b1, double[] delta)
static bool basicmultilayerrbftest ()
Member Function Documentation
testrbf() [1/2]
static bool alglib.testrbfunit.testrbf (bool silent) inline static
References alglib.testrbfunit.basicmultilayerrbftest(), alglib.testrbfunit.basicrbftest(), alglib.testrbfunit.irregularrbftest(), alglib.testrbfunit.linearitymodelrbftest(), alglib.testrbfunit.serializationtest(), alglib.testrbfunit.specialtest(), and alglib.testrbfunit.sqrdegmatrixrbftest().
Referenced by alglib.testrbfunit._pexec_testrbf(), and _Test.Main().
sqrdegmatrixrbftest() [1/2]
static bool alglib.testrbfunit.sqrdegmatrixrbftest (bool silent) inline static
References alglib.testrbfunit.eps, alglib.testrbfunit.heps, alglib.testrbfunit.mxits, alglib.math.randominteger(), alglib.math.randomreal(), alglib.rbf.rbfbuildmodel(), alglib.rbf.rbfcalc(), alglib.rbf.rbfcreate(), alglib.rbf.rbfsetalgoqnn(), alglib.rbf.rbfsetcond(), alglib.rbf.rbfsetpoints(), alglib.rbf.rbfunpack(), alglib.matgen.rmatrixrndorthogonal(), alglib.math.sqr(), and alglib.testrbfunit.tol.
Referenced by alglib.testrbfunit.testrbf().
basicmultilayerrbf1dtest() [1/2]
static bool alglib.testrbfunit.basicmultilayerrbf1dtest () inline static
References alglib.ap.assert(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.rbf.rbfbuildmodel(), alglib.rbf.rbfcalc(), alglib.rbf.rbfcalc2(), alglib.rbf.rbfcalc3(), alglib.rbf.rbfcalcbuf(), alglib.rbf.rbfcreate(), alglib.rbf.rbfgridcalc2(), alglib.rbf.rbfsetalgomultilayer(), alglib.rbf.rbfsetconstterm(), alglib.rbf.rbfsetlinterm(), alglib.rbf.rbfsetpoints(), alglib.rbf.rbfsetzeroterm(), and alglib.testrbfunit.searcherr().
specialtest() [1/2]
static bool alglib.testrbfunit.specialtest () inline static private
References alglib.math.randomreal(), alglib.rbf.rbfbuildmodel(), alglib.rbf.rbfcalc(), alglib.rbf.rbfcalc2(), alglib.rbf.rbfcalc3(), alglib.rbf.rbfcreate(), alglib.rbf.rbfsetalgomultilayer(), alglib.rbf.rbfsetalgoqnn(), alglib.rbf.rbfsetconstterm(), alglib.rbf.rbfsetlinterm(), alglib.rbf.rbfsetpoints(), alglib.rbf.rbfsetzeroterm(), and alglib.rbf.rbfunpack().
Referenced by alglib.testrbfunit.testrbf().
basicrbftest() [1/2]
static bool alglib.testrbfunit.basicrbftest () inline static private
References alglib.testrbfunit.eps, alglib.testrbfunit.heps, alglib.testrbfunit.mxits, alglib.math.randominteger(), alglib.math.randomreal(), alglib.rbf.rbfbuildmodel(), alglib.rbf.rbfcalc(), alglib.rbf.rbfcalc2(), alglib.rbf.rbfcalc3(), alglib.rbf.rbfcalcbuf(), alglib.rbf.rbfcreate(), alglib.rbf.rbfgridcalc2(), alglib.rbf.rbfsetalgoqnn(), alglib.rbf.rbfsetcond(), alglib.rbf.rbfsetconstterm(), alglib.rbf.rbfsetlinterm(), alglib.rbf.rbfsetpoints(), alglib.rbf.rbfsetzeroterm(), and alglib.rbf.rbfunpack().
Referenced by alglib.testrbfunit.testrbf().
irregularrbftest() [1/2]
static bool alglib.testrbfunit.irregularrbftest () inline static private
References alglib.testrbfunit.eps, alglib.testrbfunit.heps, alglib.testrbfunit.mxits, alglib.math.randominteger(), alglib.math.randomreal(), alglib.rbf.rbfbuildmodel(), alglib.rbf.rbfcalc(), alglib.rbf.rbfcalc2(), alglib.rbf.rbfcalc3(), alglib.rbf.rbfcalcbuf(), alglib.rbf.rbfcreate(), alglib.rbf.rbfsetalgoqnn(), alglib.rbf.rbfsetcond(), alglib.rbf.rbfsetconstterm(), alglib.rbf.rbfsetlinterm(), alglib.rbf.rbfsetpoints(), and alglib.rbf.rbfsetzeroterm().
Referenced by alglib.testrbfunit.testrbf().
linearitymodelrbftest() [1/2]
static bool alglib.testrbfunit.linearitymodelrbftest () inline static private
References alglib.math.randominteger(), alglib.math.randomreal(), alglib.rbf.rbfbuildmodel(), alglib.rbf.rbfcreate(), alglib.rbf.rbfsetalgoqnn(), alglib.rbf.rbfsetconstterm(), alglib.rbf.rbfsetlinterm(), alglib.rbf.rbfsetpoints(), alglib.rbf.rbfsetzeroterm(), alglib.rbf.rbfunpack(), and alglib.testrbfunit.tol.
Referenced by alglib.testrbfunit.testrbf().
serializationtest() [1/2]
static bool alglib.testrbfunit.serializationtest () inline static private
References alglib.serializer.alloc_start(), alglib.serializer.get_string(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.rbf.rbfalloc(), alglib.rbf.rbfbuildmodel(), alglib.rbf.rbfcalc(), alglib.rbf.rbfcreate(), alglib.rbf.rbfserialize(), alglib.rbf.rbfsetalgomultilayer(), alglib.rbf.rbfsetalgoqnn(), alglib.rbf.rbfsetlinterm(), alglib.rbf.rbfsetpoints(), alglib.rbf.rbfunserialize(), alglib.serializer.sstart_str(), alglib.serializer.stop(), and alglib.serializer.ustart_str().
Referenced by alglib.testrbfunit.testrbf().
searcherr() [1/2]
static bool alglib.testrbfunit.searcherr (double y0[,], double y1[,], int n, int ny, int errtype, double[] b1, double[] delta) inline static private
References alglib.ap.assert().
Referenced by alglib.testrbfunit.basicmultilayerrbf1dtest().
basicmultilayerrbftest() [1/2]
static bool alglib.testrbfunit.basicmultilayerrbftest () inline static private
References alglib.math.randominteger(), alglib.math.randomreal(), alglib.rbf.rbfbuildmodel(), alglib.rbf.rbfcalc(), alglib.rbf.rbfcalc2(), alglib.rbf.rbfcalc3(), alglib.rbf.rbfcalcbuf(), alglib.rbf.rbfcreate(), alglib.rbf.rbfgridcalc2(), alglib.rbf.rbfsetalgomultilayer(), alglib.rbf.rbfsetconstterm(), alglib.rbf.rbfsetlinterm(), alglib.rbf.rbfsetpoints(), and alglib.rbf.rbfsetzeroterm().
Referenced by alglib.testrbfunit.testrbf().
testrbf() [2/2]
static bool alglib.testrbfunit.testrbf (bool silent) inline static
References alglib.testrbfunit.basicmultilayerrbftest(), alglib.testrbfunit.basicrbftest(), alglib.testrbfunit.irregularrbftest(), alglib.testrbfunit.linearitymodelrbftest(), alglib.testrbfunit.serializationtest(), alglib.testrbfunit.specialtest(), and alglib.testrbfunit.sqrdegmatrixrbftest().
_pexec_testrbf()
static bool alglib.testrbfunit._pexec_testrbf (bool silent) inline static
References alglib.testrbfunit.testrbf().
Referenced by _Test.Main().
sqrdegmatrixrbftest() [2/2]
static bool alglib.testrbfunit.sqrdegmatrixrbftest (bool silent) inline static
References alglib.testrbfunit.eps, alglib.testrbfunit.heps, alglib.testrbfunit.mxits, alglib.math.randominteger(), alglib.math.randomreal(), alglib.rbf.rbfbuildmodel(), alglib.rbf.rbfcalc(), alglib.rbf.rbfcreate(), alglib.rbf.rbfsetalgoqnn(), alglib.rbf.rbfsetcond(), alglib.rbf.rbfsetpoints(), alglib.rbf.rbfunpack(), alglib.matgen.rmatrixrndorthogonal(), alglib.math.sqr(), and alglib.testrbfunit.tol.
basicmultilayerrbf1dtest() [2/2]
static bool alglib.testrbfunit.basicmultilayerrbf1dtest () inline static
References alglib.ap.assert(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.rbf.rbfbuildmodel(), alglib.rbf.rbfcalc(), alglib.rbf.rbfcalc2(), alglib.rbf.rbfcalc3(), alglib.rbf.rbfcalcbuf(), alglib.rbf.rbfcreate(), alglib.rbf.rbfgridcalc2(), alglib.rbf.rbfsetalgomultilayer(), alglib.rbf.rbfsetconstterm(), alglib.rbf.rbfsetlinterm(), alglib.rbf.rbfsetpoints(), alglib.rbf.rbfsetzeroterm(), and alglib.testrbfunit.searcherr().
specialtest() [2/2]
static bool alglib.testrbfunit.specialtest () inline static private
References alglib.math.randomreal(), alglib.rbf.rbfbuildmodel(), alglib.rbf.rbfcalc(), alglib.rbf.rbfcalc2(), alglib.rbf.rbfcalc3(), alglib.rbf.rbfcreate(), alglib.rbf.rbfsetalgomultilayer(), alglib.rbf.rbfsetalgoqnn(), alglib.rbf.rbfsetconstterm(), alglib.rbf.rbfsetlinterm(), alglib.rbf.rbfsetpoints(), alglib.rbf.rbfsetzeroterm(), and alglib.rbf.rbfunpack().
basicrbftest() [2/2]
static bool alglib.testrbfunit.basicrbftest () inline static private
References alglib.testrbfunit.eps, alglib.testrbfunit.heps, alglib.testrbfunit.mxits, alglib.math.randominteger(), alglib.math.randomreal(), alglib.rbf.rbfbuildmodel(), alglib.rbf.rbfcalc(), alglib.rbf.rbfcalc2(), alglib.rbf.rbfcalc3(), alglib.rbf.rbfcalcbuf(), alglib.rbf.rbfcreate(), alglib.rbf.rbfgridcalc2(), alglib.rbf.rbfsetalgoqnn(), alglib.rbf.rbfsetcond(), alglib.rbf.rbfsetconstterm(), alglib.rbf.rbfsetlinterm(), alglib.rbf.rbfsetpoints(), alglib.rbf.rbfsetzeroterm(), and alglib.rbf.rbfunpack().
irregularrbftest() [2/2]
static bool alglib.testrbfunit.irregularrbftest () inline static private
References alglib.testrbfunit.eps, alglib.testrbfunit.heps, alglib.testrbfunit.mxits, alglib.math.randominteger(), alglib.math.randomreal(), alglib.rbf.rbfbuildmodel(), alglib.rbf.rbfcalc(), alglib.rbf.rbfcalc2(), alglib.rbf.rbfcalc3(), alglib.rbf.rbfcalcbuf(), alglib.rbf.rbfcreate(), alglib.rbf.rbfsetalgoqnn(), alglib.rbf.rbfsetcond(), alglib.rbf.rbfsetconstterm(), alglib.rbf.rbfsetlinterm(), alglib.rbf.rbfsetpoints(), and alglib.rbf.rbfsetzeroterm().
linearitymodelrbftest() [2/2]
static bool alglib.testrbfunit.linearitymodelrbftest () inline static private
References alglib.math.randominteger(), alglib.math.randomreal(), alglib.rbf.rbfbuildmodel(), alglib.rbf.rbfcreate(), alglib.rbf.rbfsetalgoqnn(), alglib.rbf.rbfsetconstterm(), alglib.rbf.rbfsetlinterm(), alglib.rbf.rbfsetpoints(), alglib.rbf.rbfsetzeroterm(), alglib.rbf.rbfunpack(), and alglib.testrbfunit.tol.
serializationtest() [2/2]
static bool alglib.testrbfunit.serializationtest () inline static private
References alglib.serializer.alloc_start(), alglib.serializer.get_string(), alglib.math.randominteger(), alglib.math.randomreal(), alglib.rbf.rbfalloc(), alglib.rbf.rbfbuildmodel(), alglib.rbf.rbfcalc(), alglib.rbf.rbfcreate(), alglib.rbf.rbfserialize(), alglib.rbf.rbfsetalgomultilayer(), alglib.rbf.rbfsetalgoqnn(), alglib.rbf.rbfsetlinterm(), alglib.rbf.rbfsetpoints(), alglib.rbf.rbfunserialize(), alglib.serializer.sstart_str(), alglib.serializer.stop(), and alglib.serializer.ustart_str().
searcherr() [2/2]
static bool alglib.testrbfunit.searcherr (double y0[,], double y1[,], int n, int ny, int errtype, double[] b1, double[] delta) inline static private
References alglib.ap.assert().
basicmultilayerrbftest() [2/2]
static bool alglib.testrbfunit.basicmultilayerrbftest () inline static private
References alglib.math.randominteger(), alglib.math.randomreal(), alglib.rbf.rbfbuildmodel(), alglib.rbf.rbfcalc(), alglib.rbf.rbfcalc2(), alglib.rbf.rbfcalc3(), alglib.rbf.rbfcalcbuf(), alglib.rbf.rbfcreate(), alglib.rbf.rbfgridcalc2(), alglib.rbf.rbfsetalgomultilayer(), alglib.rbf.rbfsetconstterm(), alglib.rbf.rbfsetlinterm(), alglib.rbf.rbfsetpoints(), and alglib.rbf.rbfsetzeroterm().
Member Data Documentation
mxnx
const int alglib.testrbfunit.mxnx = 3 static
eps
const double alglib.testrbfunit.eps = 1.0E-6 static
Referenced by alglib.testrbfunit.basicrbftest(), alglib.testrbfunit.irregularrbftest(), and alglib.testrbfunit.sqrdegmatrixrbftest().
tol
const double alglib.testrbfunit.tol = 1.0E-10 static
Referenced by alglib.testrbfunit.linearitymodelrbftest(), and alglib.testrbfunit.sqrdegmatrixrbftest().
mxits
const int alglib.testrbfunit.mxits = 0 static
Referenced by alglib.testrbfunit.basicrbftest(), alglib.testrbfunit.irregularrbftest(), and alglib.testrbfunit.sqrdegmatrixrbftest().
heps
const double alglib.testrbfunit.heps = 1.0E-12 static
Referenced by alglib.testrbfunit.basicrbftest(), alglib.testrbfunit.irregularrbftest(), and alglib.testrbfunit.sqrdegmatrixrbftest().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/tests/test_c.cs