Doc: IGLib EXTENDED: IG.Neural.Forms.NeuralDemo1D Class Reference
IG.Neural.Forms.NeuralDemo1D Class Reference
A 1D neural network approximation demo control.
Public Member Functions
NeuralDemo1D ()
NeuralDemo1D ()
NeuralDemo1D ()
NeuralDemo1D ()
NeuralDemo1D ()
Static Public Member Functions
static ColorScale CreateGreenRedYellow (double minValue, double maxValue)
static ColorScale CreateGreenRedYellow (double minValue, double maxValue)
static ColorScale CreateGreenRedYellow (double minValue, double maxValue)
static ColorScale CreateGreenRedYellow (double minValue, double maxValue)
static ColorScale CreateGreenRedYellow (double minValue, double maxValue)
Public Attributes
System.ComponentModel.BackgroundWorker backgroundWorker1D
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Protected Attributes
INeuralApproximator _neuralApproximator
Properties
virtual INeuralApproximator NeuralApproximator [get, set]
Properties inherited from IG.Neural.INeuralApproximatorContainer
INeuralApproximator NeuralApproximator [get, set]
Gets or sets th the neural approximator for the containing class.
Private Member Functions
void LoadForm (object sender, EventArgs e)
void PredictFromApproximator (ref IVector[] exactInputParameters1D, ref IVector[] approximatedOutputValues1D)
Calculate approximation response on verification points stored in approximator.
IRealFunction createFunction1D ()
Creates a function loader and uses it for dynamic definition of functions.
void EnableControls1D (bool enabled)
void InitializeApproximator1D ()
Clean the approximator.
void GraphDimensions1D (SampledDataSet data1D)
Prepare graph for 1 dimension.
void PrepareTrainingPoints1D (bool randomPoints1D)
Preparing training points.
void WriteDefaultFunction1D ()
Write default Function for 1 dimension.
void WriteTrainingPoints1D (SampledDataSet trainingData1D)
Write training points for 1 dimension.
void WriteApproxGraf1D ()
Write approximation line 1 dimension.
void WriteErrors1D ()
Write training and verification errors in text box.
void ClearDefaultGraph ()
Clear Graph with default function for 1 dimension.
void ClearApproximationGraph ()
Clear Graph with approximative function for 1 dimension.
void ClearTrainingGraph ()
Clear Graph with training points for 1 dimension.
void ClearErrorGraph1D ()
Clear Graph with error convergence for 1 dimension.
void ResetAll1D ()
Invalidates training results AND training data, and makes corresponding changes in GUI (e.g. disables certain buttons, etc.).
void ResetResults1D ()
Invalidates the training results and makes corresponding changes in GUI to reflect this.
void btnReset1D_Click (object sender, EventArgs e)
Reset button.
void btStart1D_Click (object sender, EventArgs e)
Start training button.
void btStop1D_Click (object sender, EventArgs e)
void TrainNetworkThread1D ()
void btnGenerateOptData1D_Click (object sender, EventArgs e)
Generate training data button.
void rbMaxTrainError_CheckedChanged (object sender, EventArgs e)
Enable Maximum training error convergence to be written on graph.
void rbRmsTrainError_CheckedChanged (object sender, EventArgs e)
Enable Rms training error convergence to be written on graph.
void rbMaxVerError_CheckedChanged (object sender, EventArgs e)
Enable Maximum verification error convergence to be written on graph.
void rbRmsVerError_CheckedChanged (object sender, EventArgs e)
Enable Rms verification error convergence to be written on graph.
void cbSelfMade1D_CheckedChanged (object sender, EventArgs e)
Enable posibility to self made the equation.
void cbRandomData1D_CheckedChanged (object sender, EventArgs e)
Enable random training points.
void cbEquation1D_SelectedIndexChanged (object sender, EventArgs e)
Select equation from the list.
void tbSelfMadeEquation1D_TextChanged (object sender, EventArgs e)
Equation string.
void numSamples1D_ValueChanged (object sender, EventArgs e)
Number of training samples generated.
void numLowXLimit1D_ValueChanged (object sender, EventArgs e)
Lower limit for x-axes on the graph.
void numHighXLimit1D_ValueChanged (object sender, EventArgs e)
Higher limit for x-axes on the graph.
void numMaxEpoch1D_ValueChanged (object sender, EventArgs e)
Maximum number of epochs.
void numEpochBundle1D_ValueChanged (object sender, EventArgs e)
Number of epochs in bundle.
void numRMS1D_ValueChanged (object sender, EventArgs e)
Rms error limit.
void numLearningRate1D_ValueChanged (object sender, EventArgs e)
Learning rate.
void numMomentum1D_ValueChanged (object sender, EventArgs e)
Momentum.
void numHiddenNeuron1D_ValueChanged (object sender, EventArgs e)
Number of neurons in first hidden layer.
void numHiddenNeuronL21D_ValueChanged (object sender, EventArgs e)
Number of neurons in second hidden layer.
void numInputSafety1D_ValueChanged (object sender, EventArgs e)
Input safety factor.
void numOutputSafety1D_ValueChanged (object sender, EventArgs e)
Output safety factor.
void backgroundWorker1D_DoWork (object sender, DoWorkEventArgs e)
This event handler deals with the results of the background operation.
void backgroundWorker1D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
This event handler deals with the results of the background operation.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void LoadForm (object sender, EventArgs e)
void PredictFromApproximator (ref IVector[] exactInputParameters1D, ref IVector[] approximatedOutputValues1D)
Calculate approximation response on verification points stored in approximator.
IRealFunction createFunction1D ()
Creates a function loader and uses it for dynamic definition of functions.
void EnableControls1D (bool enabled)
void InitializeApproximator1D ()
Clean the approximator.
void GraphDimensions1D (SampledDataSet data1D)
Prepare graph for 1 dimension.
void PrepareTrainingPoints1D (bool randomPoints1D)
Preparing training points.
void WriteDefaultFunction1D ()
Write default Function for 1 dimension.
void WriteTrainingPoints1D (SampledDataSet trainingData1D)
Write training points for 1 dimension.
void WriteApproxGraf1D ()
Write approximation line 1 dimension.
void WriteErrors1D ()
Write training and verification errors in text box.
void ClearDefaultGraph ()
Clear Graph with default function for 1 dimension.
void ClearApproximationGraph ()
Clear Graph with approximative function for 1 dimension.
void ClearTrainingGraph ()
Clear Graph with training points for 1 dimension.
void ClearErrorGraph1D ()
Clear Graph with error convergence for 1 dimension.
void ResetAll1D ()
void btnReset1D_Click (object sender, EventArgs e)
Reset button.
void btStart1D_Click (object sender, EventArgs e)
Start training button.
void btStop1D_Click (object sender, EventArgs e)
void TrainNetworkThread1D ()
void btnGenerateOptData1D_Click (object sender, EventArgs e)
Generate training data button.
void rbMaxTrainError_CheckedChanged (object sender, EventArgs e)
Enable Maximum training error convergence to be written on graph.
void rbRmsTrainError_CheckedChanged (object sender, EventArgs e)
Enable Rms training error convergence to be written on graph.
void rbMaxVerError_CheckedChanged (object sender, EventArgs e)
Enable Maximum verification error convergence to be written on graph.
void rbRmsVerError_CheckedChanged (object sender, EventArgs e)
Enable Rms verification error convergence to be written on graph.
void cbSelfMade1D_CheckedChanged (object sender, EventArgs e)
Enable posibility to self made the equation.
void cbRandomData1D_CheckedChanged (object sender, EventArgs e)
Enable random training points.
void cbEquation1D_SelectedIndexChanged (object sender, EventArgs e)
Select equation from the list.
void tbSelfMadeEquation1D_TextChanged (object sender, EventArgs e)
Equation string.
void numSamples1D_ValueChanged (object sender, EventArgs e)
Number of training samples generated.
void numLowXLimit1D_ValueChanged (object sender, EventArgs e)
Lower limit for x-axes on the graph.
void numHighXLimit1D_ValueChanged (object sender, EventArgs e)
Higher limit for x-axes on the graph.
void numMaxEpoch1D_ValueChanged (object sender, EventArgs e)
Maximum number of epochs.
void numEpochBundle1D_ValueChanged (object sender, EventArgs e)
Number of epochs in bundle.
void numRMS1D_ValueChanged (object sender, EventArgs e)
Rms error limit.
void numLearningRate1D_ValueChanged (object sender, EventArgs e)
Learning rate.
void numMomentum1D_ValueChanged (object sender, EventArgs e)
Momentum.
void numHiddenNeuron1D_ValueChanged (object sender, EventArgs e)
Number of neurons in first hidden layer.
void numHiddenNeuronL21D_ValueChanged (object sender, EventArgs e)
Number of neurons in second hidden layer.
void numInputSafety1D_ValueChanged (object sender, EventArgs e)
Input safety factor.
void numOutputSafety1D_ValueChanged (object sender, EventArgs e)
Output safety factor.
void backgroundWorker1D_DoWork (object sender, DoWorkEventArgs e)
This event handler deals with the results of the background operation.
void backgroundWorker1D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
This event handler deals with the results of the background operation.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void LoadForm (object sender, EventArgs e)
void PredictFromApproximator (ref IVector[] exactInputParameters1D, ref IVector[] approximatedOutputValues1D)
Calculate approximation response on verification points stored in approximator.
IRealFunction createFunction1D ()
Creates a function loader and uses it for dynamic definition of functions.
void EnableControls1D (bool enabled)
void InitializeApproximator1D ()
Clean the approximator.
void GraphDimensions1D (SampledDataSet data1D)
Prepare graph for 1 dimension.
void PrepareTrainingPoints1D (bool randomPoints1D)
Preparing training points.
void WriteDefaultFunction1D ()
Write default Function for 1 dimension.
void WriteTrainingPoints1D (SampledDataSet trainingData1D)
Write training points for 1 dimension.
void WriteApproxGraf1D ()
Write approximation line 1 dimension.
void WriteErrors1D ()
Write training and verification errors in text box.
void ClearDefaultGraph ()
Clear Graph with default function for 1 dimension.
void ClearApproximationGraph ()
Clear Graph with approximative function for 1 dimension.
void ClearTrainingGraph ()
Clear Graph with training points for 1 dimension.
void ClearErrorGraph1D ()
Clear Graph with error convergence for 1 dimension.
void ResetAll1D ()
Invalidates training results AND training data, and makes corresponding changes in GUI (e.g. disables certain buttons, etc.).
void ResetResults1D ()
Invalidates the training results and makes corresponding changes in GUI to reflect this.
void btnReset1D_Click (object sender, EventArgs e)
Reset button.
void btStart1D_Click (object sender, EventArgs e)
Start training button.
void btStop1D_Click (object sender, EventArgs e)
void TrainNetworkThread1D ()
void btnGenerateOptData1D_Click (object sender, EventArgs e)
Generate training data button.
void rbMaxTrainError_CheckedChanged (object sender, EventArgs e)
Enable Maximum training error convergence to be written on graph.
void rbRmsTrainError_CheckedChanged (object sender, EventArgs e)
Enable Rms training error convergence to be written on graph.
void rbMaxVerError_CheckedChanged (object sender, EventArgs e)
Enable Maximum verification error convergence to be written on graph.
void rbRmsVerError_CheckedChanged (object sender, EventArgs e)
Enable Rms verification error convergence to be written on graph.
void cbSelfMade1D_CheckedChanged (object sender, EventArgs e)
Enable posibility to self made the equation.
void cbRandomData1D_CheckedChanged (object sender, EventArgs e)
Enable random training points.
void cbEquation1D_SelectedIndexChanged (object sender, EventArgs e)
Select equation from the list.
void tbSelfMadeEquation1D_TextChanged (object sender, EventArgs e)
Equation string.
void numSamples1D_ValueChanged (object sender, EventArgs e)
Number of training samples generated.
void numLowXLimit1D_ValueChanged (object sender, EventArgs e)
Lower limit for x-axes on the graph.
void numHighXLimit1D_ValueChanged (object sender, EventArgs e)
Higher limit for x-axes on the graph.
void numMaxEpoch1D_ValueChanged (object sender, EventArgs e)
Maximum number of epochs.
void numEpochBundle1D_ValueChanged (object sender, EventArgs e)
Number of epochs in bundle.
void numRMS1D_ValueChanged (object sender, EventArgs e)
Rms error limit.
void numLearningRate1D_ValueChanged (object sender, EventArgs e)
Learning rate.
void numMomentum1D_ValueChanged (object sender, EventArgs e)
Momentum.
void numHiddenNeuron1D_ValueChanged (object sender, EventArgs e)
Number of neurons in first hidden layer.
void numHiddenNeuronL21D_ValueChanged (object sender, EventArgs e)
Number of neurons in second hidden layer.
void numInputSafety1D_ValueChanged (object sender, EventArgs e)
Input safety factor.
void numOutputSafety1D_ValueChanged (object sender, EventArgs e)
Output safety factor.
void backgroundWorker1D_DoWork (object sender, DoWorkEventArgs e)
This event handler deals with the results of the background operation.
void backgroundWorker1D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
This event handler deals with the results of the background operation.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void LoadForm (object sender, EventArgs e)
void PredictFromApproximator (ref IVector[] exactInputParameters1D, ref IVector[] approximatedOutputValues1D)
Calculate approximation response on verification points stored in approximator.
IRealFunction createFunction1D ()
Creates a function loader and uses it for dynamic definition of functions.
void EnableControls1D (bool enabled)
void InitializeApproximator1D ()
Clean the approximator.
void GraphDimensions1D (SampledDataSet data1D)
Prepare graph for 1 dimension.
void PrepareTrainingPoints1D (bool randomPoints1D)
Preparing training points.
void WriteDefaultFunction1D ()
Write default Function for 1 dimension.
void WriteTrainingPoints1D (SampledDataSet trainingData1D)
Write training points for 1 dimension.
void WriteApproxGraf1D ()
Write approximation line 1 dimension.
void WriteErrors1D ()
Write training and verification errors in text box.
void ClearDefaultGraph ()
Clear Graph with default function for 1 dimension.
void ClearApproximationGraph ()
Clear Graph with approximative function for 1 dimension.
void ClearTrainingGraph ()
Clear Graph with training points for 1 dimension.
void ClearErrorGraph1D ()
Clear Graph with error convergence for 1 dimension.
void ResetAll1D ()
Invalidates training results AND training data, and makes corresponding changes in GUI (e.g. disables certain buttons, etc.).
void ResetResults1D ()
Invalidates the training results and makes corresponding changes in GUI to reflect this.
void btnReset1D_Click (object sender, EventArgs e)
Reset button.
void btStart1D_Click (object sender, EventArgs e)
Start training button.
void btStop1D_Click (object sender, EventArgs e)
void TrainNetworkThread1D ()
void btnGenerateOptData1D_Click (object sender, EventArgs e)
Generate training data button.
void rbMaxTrainError_CheckedChanged (object sender, EventArgs e)
Enable Maximum training error convergence to be written on graph.
void rbRmsTrainError_CheckedChanged (object sender, EventArgs e)
Enable Rms training error convergence to be written on graph.
void rbMaxVerError_CheckedChanged (object sender, EventArgs e)
Enable Maximum verification error convergence to be written on graph.
void rbRmsVerError_CheckedChanged (object sender, EventArgs e)
Enable Rms verification error convergence to be written on graph.
void cbSelfMade1D_CheckedChanged (object sender, EventArgs e)
Enable posibility to self made the equation.
void cbRandomData1D_CheckedChanged (object sender, EventArgs e)
Enable random training points.
void cbEquation1D_SelectedIndexChanged (object sender, EventArgs e)
Select equation from the list.
void tbSelfMadeEquation1D_TextChanged (object sender, EventArgs e)
Equation string.
void numSamples1D_ValueChanged (object sender, EventArgs e)
Number of training samples generated.
void numLowXLimit1D_ValueChanged (object sender, EventArgs e)
Lower limit for x-axes on the graph.
void numHighXLimit1D_ValueChanged (object sender, EventArgs e)
Higher limit for x-axes on the graph.
void numMaxEpoch1D_ValueChanged (object sender, EventArgs e)
Maximum number of epochs.
void numEpochBundle1D_ValueChanged (object sender, EventArgs e)
Number of epochs in bundle.
void numRMS1D_ValueChanged (object sender, EventArgs e)
Rms error limit.
void numLearningRate1D_ValueChanged (object sender, EventArgs e)
Learning rate.
void numMomentum1D_ValueChanged (object sender, EventArgs e)
Momentum.
void numHiddenNeuron1D_ValueChanged (object sender, EventArgs e)
Number of neurons in first hidden layer.
void numHiddenNeuronL21D_ValueChanged (object sender, EventArgs e)
Number of neurons in second hidden layer.
void numInputSafety1D_ValueChanged (object sender, EventArgs e)
Input safety factor.
void numOutputSafety1D_ValueChanged (object sender, EventArgs e)
Output safety factor.
void backgroundWorker1D_DoWork (object sender, DoWorkEventArgs e)
This event handler deals with the results of the background operation.
void backgroundWorker1D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
This event handler deals with the results of the background operation.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void LoadForm (object sender, EventArgs e)
void PredictFromApproximator (ref IVector[] exactInputParameters1D, ref IVector[] approximatedOutputValues1D)
Calculate approximation response on verification points stored in approximator.
IRealFunction createFunction1D ()
Creates a function loader and uses it for dynamic definition of functions.
void EnableControls1D (bool enabled)
void InitializeApproximator1D ()
Clean the approximator.
void GraphDimensions1D (SampledDataSet data1D)
Prepare graph for 1 dimension.
void PrepareTrainingPoints1D (bool randomPoints1D)
Preparing training points.
void WriteDefaultFunction1D ()
Write default Function for 1 dimension.
void WriteTrainingPoints1D (SampledDataSet trainingData1D)
Write training points for 1 dimension.
void WriteApproxGraf1D ()
Write approximation line 1 dimension.
void WriteErrors1D ()
Write training and verification errors in text box.
void ClearDefaultGraph ()
Clear Graph with default function for 1 dimension.
void ClearApproximationGraph ()
Clear Graph with approximative function for 1 dimension.
void ClearTrainingGraph ()
Clear Graph with training points for 1 dimension.
void ClearErrorGraph1D ()
Clear Graph with error convergence for 1 dimension.
void ResetAll1D ()
Invalidates training results AND training data, and makes corresponding changes in GUI (e.g. disables certain buttons, etc.).
void ResetResults1D ()
Invalidates the training results and makes corresponding changes in GUI to reflect this.
void btnReset1D_Click (object sender, EventArgs e)
Reset button.
void btStart1D_Click (object sender, EventArgs e)
Start training button.
void btStop1D_Click (object sender, EventArgs e)
void TrainNetworkThread1D ()
void btnGenerateOptData1D_Click (object sender, EventArgs e)
Generate training data button.
void rbMaxTrainError_CheckedChanged (object sender, EventArgs e)
Enable Maximum training error convergence to be written on graph.
void rbRmsTrainError_CheckedChanged (object sender, EventArgs e)
Enable Rms training error convergence to be written on graph.
void rbMaxVerError_CheckedChanged (object sender, EventArgs e)
Enable Maximum verification error convergence to be written on graph.
void rbRmsVerError_CheckedChanged (object sender, EventArgs e)
Enable Rms verification error convergence to be written on graph.
void cbSelfMade1D_CheckedChanged (object sender, EventArgs e)
Enable posibility to self made the equation.
void cbRandomData1D_CheckedChanged (object sender, EventArgs e)
Enable random training points.
void cbEquation1D_SelectedIndexChanged (object sender, EventArgs e)
Select equation from the list.
void tbSelfMadeEquation1D_TextChanged (object sender, EventArgs e)
Equation string.
void numSamples1D_ValueChanged (object sender, EventArgs e)
Number of training samples generated.
void numLowXLimit1D_ValueChanged (object sender, EventArgs e)
Lower limit for x-axes on the graph.
void numHighXLimit1D_ValueChanged (object sender, EventArgs e)
Higher limit for x-axes on the graph.
void numMaxEpoch1D_ValueChanged (object sender, EventArgs e)
Maximum number of epochs.
void numEpochBundle1D_ValueChanged (object sender, EventArgs e)
Number of epochs in bundle.
void numRMS1D_ValueChanged (object sender, EventArgs e)
Rms error limit.
void numLearningRate1D_ValueChanged (object sender, EventArgs e)
Learning rate.
void numMomentum1D_ValueChanged (object sender, EventArgs e)
Momentum.
void numHiddenNeuron1D_ValueChanged (object sender, EventArgs e)
Number of neurons in first hidden layer.
void numHiddenNeuronL21D_ValueChanged (object sender, EventArgs e)
Number of neurons in second hidden layer.
void numInputSafety1D_ValueChanged (object sender, EventArgs e)
Input safety factor.
void numOutputSafety1D_ValueChanged (object sender, EventArgs e)
Output safety factor.
void backgroundWorker1D_DoWork (object sender, DoWorkEventArgs e)
This event handler deals with the results of the background operation.
void backgroundWorker1D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e)
This event handler deals with the results of the background operation.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
GraphPane pane1D
Main Graph.
GraphPane pane1DError
Error Graph.
int hiddenNeuronL11D = 5
int hiddenNeuronL21D = 0
int maxEpoch1D = 5000
int epochInBundle1D = 500
double rmsError1D = 0.001
double learningRate1D = 0.3
double momentum1D = 0.6
int samples1D = 6
double lowHorizontalLimit1D = -5.0
double highHorizontalLimit1D = 5.0
double lowVerificationHorizontalLimit1D = -5.0
double highVerificationHorizontalLimit1D = 5.0
double inputSafetyFactor1D = 1.3
double outputSafetyFactor1D = 1.3
int thread1D = 0
string equation1D = "x*x"
bool maxTrainErrorEnabled1D = true
bool rmsTrainErrorEnabled1D = false
bool maxVerErrorEnabled1D = false
bool rmsVerErrorEnabled1D = false
bool stopTraining1D = false
LineItem defaultFunction1D
Default Function line.
LineItem trainingPoints1D
Training points line.
LineItem approximatedLine1D
Approximation line.
LineItem errorConvergenceFunction1D
NeuralNetworks network1D
ANN.
SampledDataSet trainingData1D = null
Training data.
SampledDataSet verificationData1D = null
Verification data.
SampledDataSet defaultFunctionData1D = null
Function data.
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.RadioButton rbRmsTrainError
System.Windows.Forms.RadioButton rbMaxTrainError
System.Windows.Forms.RadioButton rbRmsVerError
System.Windows.Forms.RadioButton rbMaxVerError
System.Windows.Forms.NumericUpDown numHiddenNeuronL21D
System.Windows.Forms.TextBox tbEquationError1D
System.Windows.Forms.Button btLoadANN1D
System.Windows.Forms.Button btSaveANN1D
System.Windows.Forms.TextBox tbRmsTrainError1D
System.Windows.Forms.Label label12
System.Windows.Forms.Label label13
System.Windows.Forms.TextBox tbMaxTrainError1D
System.Windows.Forms.TextBox tbRmsVerError1D
System.Windows.Forms.TextBox tbMaxVerError1D
System.Windows.Forms.Label label2
System.Windows.Forms.Label label1
ZedGraph.ZedGraphControl errorConvergence1D
System.Windows.Forms.Button btnReset1D
System.Windows.Forms.Button btStart1D
System.Windows.Forms.NumericUpDown numOutputSafety1D
System.Windows.Forms.Label label16
System.Windows.Forms.NumericUpDown numInputSafety1D
System.Windows.Forms.Label label15
System.Windows.Forms.NumericUpDown numHiddenNeuron1D
System.Windows.Forms.Label label11
System.Windows.Forms.NumericUpDown numMomentum1D
System.Windows.Forms.NumericUpDown numLearningRate1D
System.Windows.Forms.NumericUpDown numRMS1D
System.Windows.Forms.NumericUpDown numEpochBundle1D
System.Windows.Forms.NumericUpDown numMaxEpoch1D
System.Windows.Forms.Label label8
System.Windows.Forms.Label label7
System.Windows.Forms.Label label6
System.Windows.Forms.Label label5
System.Windows.Forms.Label label4
System.Windows.Forms.CheckBox cbRandomData1D
System.Windows.Forms.Button btnGenerateOptData1D
System.Windows.Forms.NumericUpDown numHighXLimit1D
System.Windows.Forms.NumericUpDown numLowXLimit1D
System.Windows.Forms.NumericUpDown numSamples1D
System.Windows.Forms.Label label9
System.Windows.Forms.TextBox tbSelfMadeEquation1D
System.Windows.Forms.ComboBox cbEquation1D
System.Windows.Forms.Label label19
System.Windows.Forms.CheckBox cbSelfMade1D
System.Windows.Forms.Button btLoad1D
ZedGraph.ZedGraphControl functionGraph
System.Windows.Forms.GroupBox groupBox5
System.Windows.Forms.GroupBox groupBox6
System.Windows.Forms.Button btStop1D
System.Windows.Forms.GroupBox groupBox7
System.Windows.Forms.GroupBox groupBox9
Static Private Attributes
static readonly Color enabledColor1D = Color.Tomato
static readonly Color disabledColor1D = Color.Goldenrod
Detailed Description
A 1D neural network approximation demo control.
$A Tadej xx; Igor Feb13;
Constructor & Destructor Documentation
NeuralDemo1D() [1/5]
IG.Neural.Forms.NeuralDemo1D.NeuralDemo1D () inline
References IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D, IG.Neural.Forms.NeuralDemo1D.highHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), IG.Neural.Forms.NeuralDemo1D.lowHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D, and IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D.
NeuralDemo1D() [2/5]
IG.Neural.Forms.NeuralDemo1D.NeuralDemo1D () inline
References IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D, IG.Neural.Forms.NeuralDemo1D.highHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), IG.Neural.Forms.NeuralDemo1D.lowHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D, and IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D.
NeuralDemo1D() [3/5]
IG.Neural.Forms.NeuralDemo1D.NeuralDemo1D () inline
References IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D, IG.Neural.Forms.NeuralDemo1D.highHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), IG.Neural.Forms.NeuralDemo1D.lowHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D, and IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D.
NeuralDemo1D() [4/5]
IG.Neural.Forms.NeuralDemo1D.NeuralDemo1D () inline
References IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D, IG.Neural.Forms.NeuralDemo1D.highHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), IG.Neural.Forms.NeuralDemo1D.lowHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D, and IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D.
NeuralDemo1D() [5/5]
IG.Neural.Forms.NeuralDemo1D.NeuralDemo1D () inline
References IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D, IG.Neural.Forms.NeuralDemo1D.highHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), IG.Neural.Forms.NeuralDemo1D.lowHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D, and IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D.
Member Function Documentation
LoadForm() [1/5]
void IG.Neural.Forms.NeuralDemo1D.LoadForm (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralDemo1D.errorConvergence1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Neural.Forms.NeuralDemo1D.pane1D, and IG.Neural.Forms.NeuralDemo1D.pane1DError.
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
PredictFromApproximator() [1/5]
void IG.Neural.Forms.NeuralDemo1D.PredictFromApproximator (ref IVector[] exactInputParameters1D, ref IVector[] approximatedOutputValues1D) inline private
Calculate approximation response on verification points stored in approximator.
Parameters
exactInputParameters1D Exact input parameters from verification points.
approximatedOutputValues1D Approximated output values from verification points.
References IG.Num.IVectorApproximator.CalculateOutput(), IG.Lib.SortedUniqueItemList< Type >.Contains(), IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputRange(), IG.Num.SampledDataSet.Length, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Num.INeuralApproximator.NumVerificationPoints, IG.Num.SampledDataSet.OutputLength, IG.Num.INeuralApproximator.TrainingData, and IG.Num.INeuralApproximator.VerificationIndices.
Referenced by IG.Neural.Forms.NeuralDemo1D.WriteApproxGraf1D().
createFunction1D() [1/5]
IRealFunction IG.Neural.Forms.NeuralDemo1D.createFunction1D () inline private
Creates a function loader and uses it for dynamic definition of functions.
References IG.Lib.RealFunctionLoader.CreateRealFunction(), IG.Neural.Forms.NeuralDemo1D.equation1D, IG.Lib.RealFunctionLoader.IndependentVariableName, IG.Lib.RealFunctionLoader.InvalidateDefinitions(), IG.Neural.Forms.NeuralDemo1D.tbEquationError1D, IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D, and IG.Lib.RealFunctionLoader.ValueDefinitionString.
Referenced by IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click().
CreateGreenRedYellow() [1/5]
static ColorScale IG.Neural.Forms.NeuralDemo1D.CreateGreenRedYellow (double minValue, double maxValue) inline static
EnableControls1D() [1/5]
void IG.Neural.Forms.NeuralDemo1D.EnableControls1D (bool enabled) inline private
References IG.Neural.Forms.NeuralDemo1D.disabledColor1D, IG.Neural.Forms.NeuralDemo1D.enabledColor1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, and IG.Neural.Forms.NeuralDemo1D.trainingPoints1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), and IG.Neural.Forms.NeuralDemo1D.WriteApproxGraf1D().
InitializeApproximator1D() [1/5]
void IG.Neural.Forms.NeuralDemo1D.InitializeApproximator1D () inline private
Clean the approximator.
References IG.Neural.Forms.NeuralDemo1D.NeuralApproximator.
Referenced by IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click(), and IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
GraphDimensions1D() [1/5]
void IG.Neural.Forms.NeuralDemo1D.GraphDimensions1D (SampledDataSet data1D) inline private
Prepare graph for 1 dimension.
Parameters
data Data set.
References IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.Length, and IG.Neural.Forms.NeuralDemo1D.pane1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.WriteDefaultFunction1D().
PrepareTrainingPoints1D() [1/5]
void IG.Neural.Forms.NeuralDemo1D.PrepareTrainingPoints1D (bool randomPoints1D) inline private
Preparing training points.
References IG.Num.SampledDataSet.AddElement(), IG.Neural.Forms.NeuralDemo1D.defaultFunctionData1D, IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Neural.Forms.NeuralDemo1D.highVerificationHorizontalLimit1D, IG.Num.SampledDataSet.Length, IG.Neural.Forms.NeuralDemo1D.lowVerificationHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.samples1D, and IG.Neural.Forms.NeuralDemo1D.trainingData1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click().
WriteDefaultFunction1D() [1/5]
void IG.Neural.Forms.NeuralDemo1D.WriteDefaultFunction1D () inline private
Write default Function for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.defaultFunction1D, IG.Neural.Forms.NeuralDemo1D.defaultFunctionData1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Neural.Forms.NeuralDemo1D.GraphDimensions1D(), and IG.Num.SampledDataSet.Length.
Referenced by IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click().
WriteTrainingPoints1D() [1/5]
void IG.Neural.Forms.NeuralDemo1D.WriteTrainingPoints1D (SampledDataSet trainingData1D) inline private
Write training points for 1 dimension.
Parameters
trainingData1D Training data.
References IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.enabledColor1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.InputLength, IG.Num.IVector< T >.Length, IG.Num.SampledDataSet.Length, IG.Num.SampledDataSet.OutputLength, IG.Neural.Forms.NeuralDemo1D.trainingData1D, and IG.Neural.Forms.NeuralDemo1D.trainingPoints1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click().
WriteApproxGraf1D() [1/5]
void IG.Neural.Forms.NeuralDemo1D.WriteApproxGraf1D () inline private
Write approximation line 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.approximatedLine1D, IG.Neural.Forms.NeuralDemo1D.EnableControls1D(), IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Neural.Forms.NeuralDemo1D.PredictFromApproximator(), and IG.Neural.Forms.NeuralDemo1D.thread1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_RunWorkerCompleted().
WriteErrors1D() [1/5]
void IG.Neural.Forms.NeuralDemo1D.WriteErrors1D () inline private
Write training and verification errors in text box.
References IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Num.INeuralApproximator.ConvergenceErrorsTrainingMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsTrainingRmsList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationRmsList, IG.Neural.Forms.NeuralDemo1D.epochInBundle1D, IG.Neural.Forms.NeuralDemo1D.errorConvergence1D, IG.Neural.Forms.NeuralDemo1D.errorConvergenceFunction1D, IG.Num.INeuralApproximator.GetErrorsTrainingMax(), IG.Num.INeuralApproximator.GetErrorsTrainingRms(), IG.Num.INeuralApproximator.GetErrorsVerificationMax(), IG.Num.INeuralApproximator.GetErrorsVerificationRms(), IG.Neural.Forms.NeuralDemo1D.maxTrainErrorEnabled1D, IG.Neural.Forms.NeuralDemo1D.maxVerErrorEnabled1D, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Neural.Forms.NeuralDemo1D.pane1DError, IG.Neural.Forms.NeuralDemo1D.rmsTrainErrorEnabled1D, IG.Neural.Forms.NeuralDemo1D.rmsVerErrorEnabled1D, IG.Neural.Forms.NeuralDemo1D.tbMaxTrainError1D, IG.Neural.Forms.NeuralDemo1D.tbMaxVerError1D, IG.Neural.Forms.NeuralDemo1D.tbRmsTrainError1D, and IG.Neural.Forms.NeuralDemo1D.tbRmsVerError1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_RunWorkerCompleted(), IG.Neural.Forms.NeuralDemo1D.rbMaxTrainError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.rbMaxVerError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.rbRmsTrainError_CheckedChanged(), and IG.Neural.Forms.NeuralDemo1D.rbRmsVerError_CheckedChanged().
ClearDefaultGraph() [1/5]
void IG.Neural.Forms.NeuralDemo1D.ClearDefaultGraph () inline private
Clear Graph with default function for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.defaultFunction1D, and IG.Neural.Forms.NeuralDemo1D.functionGraph.
Referenced by IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click(), and IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
ClearApproximationGraph() [1/5]
void IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph () inline private
Clear Graph with approximative function for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.approximatedLine1D, and IG.Neural.Forms.NeuralDemo1D.functionGraph.
Referenced by IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click(), IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), and IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
ClearTrainingGraph() [1/5]
void IG.Neural.Forms.NeuralDemo1D.ClearTrainingGraph () inline private
Clear Graph with training points for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.functionGraph, and IG.Neural.Forms.NeuralDemo1D.trainingPoints1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click(), and IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
ClearErrorGraph1D() [1/5]
void IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D () inline private
Clear Graph with error convergence for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.errorConvergence1D, IG.Neural.Forms.NeuralDemo1D.errorConvergenceFunction1D, IG.Neural.Forms.NeuralDemo1D.tbMaxTrainError1D, IG.Neural.Forms.NeuralDemo1D.tbMaxVerError1D, IG.Neural.Forms.NeuralDemo1D.tbRmsTrainError1D, and IG.Neural.Forms.NeuralDemo1D.tbRmsVerError1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click(), IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), IG.Neural.Forms.NeuralDemo1D.ResetAll1D(), and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
ResetAll1D() [1/5]
void IG.Neural.Forms.NeuralDemo1D.ResetAll1D () inline private
Invalidates training results AND training data, and makes corresponding changes in GUI (e.g. disables certain buttons, etc.).
References IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph(), IG.Neural.Forms.NeuralDemo1D.ClearDefaultGraph(), IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Neural.Forms.NeuralDemo1D.ClearTrainingGraph(), and IG.Neural.Forms.NeuralDemo1D.InitializeApproximator1D().
Referenced by IG.Neural.Forms.NeuralDemo1D.btnReset1D_Click(), IG.Neural.Forms.NeuralDemo1D.cbEquation1D_SelectedIndexChanged(), IG.Neural.Forms.NeuralDemo1D.cbRandomData1D_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D_ValueChanged(), and IG.Neural.Forms.NeuralDemo1D.numSamples1D_ValueChanged().
ResetResults1D() [1/4]
void IG.Neural.Forms.NeuralDemo1D.ResetResults1D () inline private
Invalidates the training results and makes corresponding changes in GUI to reflect this.
btnReset1D_Click() [1/5]
void IG.Neural.Forms.NeuralDemo1D.btnReset1D_Click (object sender, EventArgs e) inline private
Reset button.
References IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
btStart1D_Click() [1/5]
void IG.Neural.Forms.NeuralDemo1D.btStart1D_Click (object sender, EventArgs e) inline private
Start training button.
References IG.Neural.Forms.NeuralDemo1D.btLoadANN1D, IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D, IG.Neural.Forms.NeuralDemo1D.btnReset1D, IG.Neural.Forms.NeuralDemo1D.btSaveANN1D, IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.btStop1D, IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph(), IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Neural.Forms.NeuralDemo1D.EnableControls1D(), IG.Neural.Forms.NeuralDemo1D.enabledColor1D, IG.Neural.NeuralNetworks.EpochBundle, IG.Neural.Forms.NeuralDemo1D.epochInBundle1D, IG.Neural.NeuralNetworks.HiddenNeuron1L, IG.Neural.NeuralNetworks.HiddenNeuron2L, IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL11D, IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL21D, IG.Neural.NeuralNetworks.InputSafetyFactor, IG.Neural.Forms.NeuralDemo1D.inputSafetyFactor1D, IG.Neural.NeuralNetworks.LearningRate, IG.Neural.Forms.NeuralDemo1D.learningRate1D, IG.Neural.NeuralNetworks.MaxEpoch, IG.Neural.Forms.NeuralDemo1D.maxEpoch1D, IG.Neural.NeuralNetworks.Momentum, IG.Neural.Forms.NeuralDemo1D.momentum1D, IG.Neural.Forms.NeuralDemo1D.network1D, IG.Neural.NeuralNetworks.OutputSafetyFactor, IG.Neural.Forms.NeuralDemo1D.outputSafetyFactor1D, IG.Neural.NeuralNetworks.RMS, IG.Neural.Forms.NeuralDemo1D.rmsError1D, IG.Neural.Forms.NeuralDemo1D.trainingPoints1D, and IG.Neural.Forms.NeuralDemo1D.TrainNetworkThread1D().
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
btStop1D_Click() [1/5]
void IG.Neural.Forms.NeuralDemo1D.btStop1D_Click (object sender, EventArgs e) inline private
References IG.Neural.NeuralNetworks.BreakTraining, IG.Neural.Forms.NeuralDemo1D.network1D, and IG.Neural.Forms.NeuralDemo1D.stopTraining1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
TrainNetworkThread1D() [1/5]
void IG.Neural.Forms.NeuralDemo1D.TrainNetworkThread1D () inline private
References IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.btStart1D_Click().
btnGenerateOptData1D_Click() [1/5]
void IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click (object sender, EventArgs e) inline private
Generate training data button.
References IG.Neural.Forms.NeuralDemo1D.cbRandomData1D, IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph(), IG.Neural.Forms.NeuralDemo1D.ClearDefaultGraph(), IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Neural.Forms.NeuralDemo1D.ClearTrainingGraph(), IG.Neural.Forms.NeuralDemo1D.createFunction1D(), IG.Neural.Forms.NeuralDemo1D.defaultFunctionData1D, IG.Neural.TestFunctions.GenerateFunctionTrainingSamples(), IG.Neural.Forms.NeuralDemo1D.highHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.InitializeApproximator1D(), IG.Neural.Forms.NeuralDemo1D.lowHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.pane1D, IG.Neural.Forms.NeuralDemo1D.PrepareTrainingPoints1D(), IG.Neural.Forms.NeuralDemo1D.tbEquationError1D, IG.Neural.Forms.NeuralDemo1D.trainingData1D, IG.Neural.Forms.NeuralDemo1D.verificationData1D, IG.Neural.Forms.NeuralDemo1D.WriteDefaultFunction1D(), and IG.Neural.Forms.NeuralDemo1D.WriteTrainingPoints1D().
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
rbMaxTrainError_CheckedChanged() [1/5]
void IG.Neural.Forms.NeuralDemo1D.rbMaxTrainError_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum training error convergence to be written on graph.
References IG.Neural.Forms.NeuralDemo1D.maxTrainErrorEnabled1D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
rbRmsTrainError_CheckedChanged() [1/5]
void IG.Neural.Forms.NeuralDemo1D.rbRmsTrainError_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms training error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Neural.Forms.NeuralDemo1D.rmsTrainErrorEnabled1D, and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
rbMaxVerError_CheckedChanged() [1/5]
void IG.Neural.Forms.NeuralDemo1D.rbMaxVerError_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum verification error convergence to be written on graph.
References IG.Neural.Forms.NeuralDemo1D.maxVerErrorEnabled1D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
rbRmsVerError_CheckedChanged() [1/5]
void IG.Neural.Forms.NeuralDemo1D.rbRmsVerError_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms verification error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Neural.Forms.NeuralDemo1D.rmsVerErrorEnabled1D, and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
cbSelfMade1D_CheckedChanged() [1/5]
void IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D_CheckedChanged (object sender, EventArgs e) inline private
Enable posibility to self made the equation.
References IG.Neural.Forms.NeuralDemo1D.cbEquation1D, IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D, IG.Neural.Forms.NeuralDemo1D.ResetAll1D(), and IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
cbRandomData1D_CheckedChanged() [1/5]
void IG.Neural.Forms.NeuralDemo1D.cbRandomData1D_CheckedChanged (object sender, EventArgs e) inline private
Enable random training points.
References IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
cbEquation1D_SelectedIndexChanged() [1/5]
void IG.Neural.Forms.NeuralDemo1D.cbEquation1D_SelectedIndexChanged (object sender, EventArgs e) inline private
Select equation from the list.
References IG.Neural.Forms.NeuralDemo1D.cbEquation1D, IG.Neural.Forms.NeuralDemo1D.equation1D, and IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
tbSelfMadeEquation1D_TextChanged() [1/5]
void IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D_TextChanged (object sender, EventArgs e) inline private
Equation string.
References IG.Neural.Forms.NeuralDemo1D.equation1D, and IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
numSamples1D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralDemo1D.numSamples1D_ValueChanged (object sender, EventArgs e) inline private
Number of training samples generated.
References IG.Neural.Forms.NeuralDemo1D.numSamples1D, IG.Neural.Forms.NeuralDemo1D.ResetAll1D(), and IG.Neural.Forms.NeuralDemo1D.samples1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
numLowXLimit1D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D_ValueChanged (object sender, EventArgs e) inline private
Lower limit for x-axes on the graph.
References IG.Neural.Forms.NeuralDemo1D.lowHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D, and IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
numHighXLimit1D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D_ValueChanged (object sender, EventArgs e) inline private
Higher limit for x-axes on the graph.
References IG.Neural.Forms.NeuralDemo1D.highHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D, and IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
numMaxEpoch1D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D_ValueChanged (object sender, EventArgs e) inline private
Maximum number of epochs.
References IG.Neural.Forms.NeuralDemo1D.maxEpoch1D, and IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
numEpochBundle1D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D_ValueChanged (object sender, EventArgs e) inline private
Number of epochs in bundle.
References IG.Neural.Forms.NeuralDemo1D.epochInBundle1D, and IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
numRMS1D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralDemo1D.numRMS1D_ValueChanged (object sender, EventArgs e) inline private
Rms error limit.
References IG.Neural.Forms.NeuralDemo1D.numRMS1D, and IG.Neural.Forms.NeuralDemo1D.rmsError1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
numLearningRate1D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralDemo1D.numLearningRate1D_ValueChanged (object sender, EventArgs e) inline private
Learning rate.
References IG.Neural.Forms.NeuralDemo1D.learningRate1D, and IG.Neural.Forms.NeuralDemo1D.numLearningRate1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
numMomentum1D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralDemo1D.numMomentum1D_ValueChanged (object sender, EventArgs e) inline private
Momentum.
References IG.Neural.Forms.NeuralDemo1D.momentum1D, and IG.Neural.Forms.NeuralDemo1D.numMomentum1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
numHiddenNeuron1D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in first hidden layer.
References IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL11D, and IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
numHiddenNeuronL21D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in second hidden layer.
References IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL21D, and IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D.
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
numInputSafety1D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralDemo1D.numInputSafety1D_ValueChanged (object sender, EventArgs e) inline private
Input safety factor.
References IG.Neural.Forms.NeuralDemo1D.inputSafetyFactor1D, and IG.Neural.Forms.NeuralDemo1D.numInputSafety1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
numOutputSafety1D_ValueChanged() [1/5]
void IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D_ValueChanged (object sender, EventArgs e) inline private
Output safety factor.
References IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D, and IG.Neural.Forms.NeuralDemo1D.outputSafetyFactor1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
backgroundWorker1D_DoWork() [1/5]
void IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_DoWork (object sender, DoWorkEventArgs e) inline private
This event handler deals with the results of the background operation.
References IG.Neural.NeuralNetworks.BreakTraining, IG.Neural.Forms.NeuralDemo1D.network1D, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Neural.Forms.NeuralDemo1D.stopTraining1D, IG.Neural.Forms.NeuralDemo1D.trainingData1D, IG.Neural.NeuralNetworks.TrainNetwork(), and IG.Neural.Forms.NeuralDemo1D.verificationData1D.
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
backgroundWorker1D_RunWorkerCompleted() [1/5]
void IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
This event handler deals with the results of the background operation.
References IG.Neural.Forms.NeuralDemo1D.btLoadANN1D, IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D, IG.Neural.Forms.NeuralDemo1D.btnReset1D, IG.Neural.Forms.NeuralDemo1D.btSaveANN1D, IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.btStop1D, IG.Neural.Forms.NeuralDemo1D.WriteApproxGraf1D(), and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
Dispose() [1/5]
override void IG.Neural.Forms.NeuralDemo1D.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralDemo1D.components.
InitializeComponent() [1/5]
void IG.Neural.Forms.NeuralDemo1D.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D, IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_DoWork(), IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_RunWorkerCompleted(), IG.Neural.Forms.NeuralDemo1D.btLoad1D, IG.Neural.Forms.NeuralDemo1D.btLoadANN1D, IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D, IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click(), IG.Neural.Forms.NeuralDemo1D.btnReset1D, IG.Neural.Forms.NeuralDemo1D.btnReset1D_Click(), IG.Neural.Forms.NeuralDemo1D.btSaveANN1D, IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), IG.Neural.Forms.NeuralDemo1D.btStop1D, IG.Neural.Forms.NeuralDemo1D.btStop1D_Click(), IG.Neural.Forms.NeuralDemo1D.cbEquation1D, IG.Neural.Forms.NeuralDemo1D.cbEquation1D_SelectedIndexChanged(), IG.Neural.Forms.NeuralDemo1D.cbRandomData1D, IG.Neural.Forms.NeuralDemo1D.cbRandomData1D_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D, IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.components, IG.Neural.Forms.NeuralDemo1D.errorConvergence1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Neural.Forms.NeuralDemo1D.groupBox5, IG.Neural.Forms.NeuralDemo1D.groupBox6, IG.Neural.Forms.NeuralDemo1D.groupBox7, IG.Neural.Forms.NeuralDemo1D.groupBox9, IG.Neural.Forms.NeuralDemo1D.label1, IG.Neural.Forms.NeuralDemo1D.label11, IG.Neural.Forms.NeuralDemo1D.label12, IG.Neural.Forms.NeuralDemo1D.label13, IG.Neural.Forms.NeuralDemo1D.label15, IG.Neural.Forms.NeuralDemo1D.label16, IG.Neural.Forms.NeuralDemo1D.label19, IG.Neural.Forms.NeuralDemo1D.label2, IG.Neural.Forms.NeuralDemo1D.label4, IG.Neural.Forms.NeuralDemo1D.label5, IG.Neural.Forms.NeuralDemo1D.label6, IG.Neural.Forms.NeuralDemo1D.label7, IG.Neural.Forms.NeuralDemo1D.label8, IG.Neural.Forms.NeuralDemo1D.label9, IG.Neural.Forms.NeuralDemo1D.LoadForm(), IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D, IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D, IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D, IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D, IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numInputSafety1D, IG.Neural.Forms.NeuralDemo1D.numInputSafety1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numLearningRate1D, IG.Neural.Forms.NeuralDemo1D.numLearningRate1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D, IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D, IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numMomentum1D, IG.Neural.Forms.NeuralDemo1D.numMomentum1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D, IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numRMS1D, IG.Neural.Forms.NeuralDemo1D.numRMS1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numSamples1D, IG.Neural.Forms.NeuralDemo1D.numSamples1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.rbMaxTrainError, IG.Neural.Forms.NeuralDemo1D.rbMaxTrainError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.rbMaxVerError, IG.Neural.Forms.NeuralDemo1D.rbMaxVerError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.rbRmsTrainError, IG.Neural.Forms.NeuralDemo1D.rbRmsTrainError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.rbRmsVerError, IG.Neural.Forms.NeuralDemo1D.rbRmsVerError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.tbEquationError1D, IG.Neural.Forms.NeuralDemo1D.tbMaxTrainError1D, IG.Neural.Forms.NeuralDemo1D.tbMaxVerError1D, IG.Neural.Forms.NeuralDemo1D.tbRmsTrainError1D, IG.Neural.Forms.NeuralDemo1D.tbRmsVerError1D, IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D, and IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D_TextChanged().
Referenced by IG.Neural.Forms.NeuralDemo1D.NeuralDemo1D().
LoadForm() [2/5]
void IG.Neural.Forms.NeuralDemo1D.LoadForm (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralDemo1D.errorConvergence1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Neural.Forms.NeuralDemo1D.pane1D, and IG.Neural.Forms.NeuralDemo1D.pane1DError.
PredictFromApproximator() [2/5]
void IG.Neural.Forms.NeuralDemo1D.PredictFromApproximator (ref IVector[] exactInputParameters1D, ref IVector[] approximatedOutputValues1D) inline private
Calculate approximation response on verification points stored in approximator.
Parameters
exactInputParameters1D Exact input parameters from verification points.
approximatedOutputValues1D Approximated output values from verification points.
References IG.Num.IVectorApproximator.CalculateOutput(), IG.Lib.SortedUniqueItemList< Type >.Contains(), IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputRange(), IG.Num.SampledDataSet.Length, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Num.INeuralApproximator.NumVerificationPoints, IG.Num.SampledDataSet.OutputLength, IG.Num.INeuralApproximator.TrainingData, and IG.Num.INeuralApproximator.VerificationIndices.
createFunction1D() [2/5]
IRealFunction IG.Neural.Forms.NeuralDemo1D.createFunction1D () inline private
Creates a function loader and uses it for dynamic definition of functions.
References IG.Lib.RealFunctionLoader.CreateRealFunction(), IG.Neural.Forms.NeuralDemo1D.equation1D, IG.Lib.RealFunctionLoader.IndependentVariableName, IG.Lib.RealFunctionLoader.InvalidateDefinitions(), IG.Neural.Forms.NeuralDemo1D.tbEquationError1D, IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D, and IG.Lib.RealFunctionLoader.ValueDefinitionString.
CreateGreenRedYellow() [2/5]
static ColorScale IG.Neural.Forms.NeuralDemo1D.CreateGreenRedYellow (double minValue, double maxValue) inline static
EnableControls1D() [2/5]
void IG.Neural.Forms.NeuralDemo1D.EnableControls1D (bool enabled) inline private
References IG.Neural.Forms.NeuralDemo1D.disabledColor1D, IG.Neural.Forms.NeuralDemo1D.enabledColor1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, and IG.Neural.Forms.NeuralDemo1D.trainingPoints1D.
InitializeApproximator1D() [2/5]
void IG.Neural.Forms.NeuralDemo1D.InitializeApproximator1D () inline private
Clean the approximator.
References IG.Neural.Forms.NeuralDemo1D.NeuralApproximator.
GraphDimensions1D() [2/5]
void IG.Neural.Forms.NeuralDemo1D.GraphDimensions1D (SampledDataSet data1D) inline private
Prepare graph for 1 dimension.
Parameters
data Data set.
References IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.Length, and IG.Neural.Forms.NeuralDemo1D.pane1D.
PrepareTrainingPoints1D() [2/5]
void IG.Neural.Forms.NeuralDemo1D.PrepareTrainingPoints1D (bool randomPoints1D) inline private
Preparing training points.
References IG.Num.SampledDataSet.AddElement(), IG.Neural.Forms.NeuralDemo1D.defaultFunctionData1D, IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Neural.Forms.NeuralDemo1D.highVerificationHorizontalLimit1D, IG.Num.SampledDataSet.Length, IG.Neural.Forms.NeuralDemo1D.lowVerificationHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.samples1D, and IG.Neural.Forms.NeuralDemo1D.trainingData1D.
WriteDefaultFunction1D() [2/5]
void IG.Neural.Forms.NeuralDemo1D.WriteDefaultFunction1D () inline private
Write default Function for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.defaultFunction1D, IG.Neural.Forms.NeuralDemo1D.defaultFunctionData1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Neural.Forms.NeuralDemo1D.GraphDimensions1D(), and IG.Num.SampledDataSet.Length.
WriteTrainingPoints1D() [2/5]
void IG.Neural.Forms.NeuralDemo1D.WriteTrainingPoints1D (SampledDataSet trainingData1D) inline private
Write training points for 1 dimension.
Parameters
trainingData1D Training data.
References IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.enabledColor1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.InputLength, IG.Num.IVector< T >.Length, IG.Num.SampledDataSet.Length, IG.Num.SampledDataSet.OutputLength, IG.Neural.Forms.NeuralDemo1D.trainingData1D, and IG.Neural.Forms.NeuralDemo1D.trainingPoints1D.
WriteApproxGraf1D() [2/5]
void IG.Neural.Forms.NeuralDemo1D.WriteApproxGraf1D () inline private
Write approximation line 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.approximatedLine1D, IG.Neural.Forms.NeuralDemo1D.EnableControls1D(), IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Neural.Forms.NeuralDemo1D.PredictFromApproximator(), and IG.Neural.Forms.NeuralDemo1D.thread1D.
WriteErrors1D() [2/5]
void IG.Neural.Forms.NeuralDemo1D.WriteErrors1D () inline private
Write training and verification errors in text box.
References IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Num.INeuralApproximator.ConvergenceErrorsTrainingMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsTrainingRmsList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationRmsList, IG.Neural.Forms.NeuralDemo1D.epochInBundle1D, IG.Neural.Forms.NeuralDemo1D.errorConvergence1D, IG.Neural.Forms.NeuralDemo1D.errorConvergenceFunction1D, IG.Num.INeuralApproximator.GetErrorsTrainingMax(), IG.Num.INeuralApproximator.GetErrorsTrainingRms(), IG.Num.INeuralApproximator.GetErrorsVerificationMax(), IG.Num.INeuralApproximator.GetErrorsVerificationRms(), IG.Neural.Forms.NeuralDemo1D.maxTrainErrorEnabled1D, IG.Neural.Forms.NeuralDemo1D.maxVerErrorEnabled1D, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Neural.Forms.NeuralDemo1D.pane1DError, IG.Neural.Forms.NeuralDemo1D.rmsTrainErrorEnabled1D, IG.Neural.Forms.NeuralDemo1D.rmsVerErrorEnabled1D, IG.Neural.Forms.NeuralDemo1D.tbMaxTrainError1D, IG.Neural.Forms.NeuralDemo1D.tbMaxVerError1D, IG.Neural.Forms.NeuralDemo1D.tbRmsTrainError1D, and IG.Neural.Forms.NeuralDemo1D.tbRmsVerError1D.
ClearDefaultGraph() [2/5]
void IG.Neural.Forms.NeuralDemo1D.ClearDefaultGraph () inline private
Clear Graph with default function for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.defaultFunction1D, and IG.Neural.Forms.NeuralDemo1D.functionGraph.
ClearApproximationGraph() [2/5]
void IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph () inline private
Clear Graph with approximative function for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.approximatedLine1D, and IG.Neural.Forms.NeuralDemo1D.functionGraph.
ClearTrainingGraph() [2/5]
void IG.Neural.Forms.NeuralDemo1D.ClearTrainingGraph () inline private
Clear Graph with training points for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.functionGraph, and IG.Neural.Forms.NeuralDemo1D.trainingPoints1D.
ClearErrorGraph1D() [2/5]
void IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D () inline private
Clear Graph with error convergence for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.errorConvergence1D, IG.Neural.Forms.NeuralDemo1D.errorConvergenceFunction1D, IG.Neural.Forms.NeuralDemo1D.tbMaxTrainError1D, IG.Neural.Forms.NeuralDemo1D.tbMaxVerError1D, IG.Neural.Forms.NeuralDemo1D.tbRmsTrainError1D, and IG.Neural.Forms.NeuralDemo1D.tbRmsVerError1D.
ResetAll1D() [2/5]
void IG.Neural.Forms.NeuralDemo1D.ResetAll1D () inline private
References IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph(), IG.Neural.Forms.NeuralDemo1D.ClearDefaultGraph(), IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Neural.Forms.NeuralDemo1D.ClearTrainingGraph(), and IG.Neural.Forms.NeuralDemo1D.InitializeApproximator1D().
btnReset1D_Click() [2/5]
void IG.Neural.Forms.NeuralDemo1D.btnReset1D_Click (object sender, EventArgs e) inline private
Reset button.
References IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
btStart1D_Click() [2/5]
void IG.Neural.Forms.NeuralDemo1D.btStart1D_Click (object sender, EventArgs e) inline private
Start training button.
References IG.Neural.Forms.NeuralDemo1D.btLoadANN1D, IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D, IG.Neural.Forms.NeuralDemo1D.btnReset1D, IG.Neural.Forms.NeuralDemo1D.btSaveANN1D, IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.btStop1D, IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph(), IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Neural.Forms.NeuralDemo1D.EnableControls1D(), IG.Neural.Forms.NeuralDemo1D.enabledColor1D, IG.Neural.NeuralNetworks.EpochBundle, IG.Neural.Forms.NeuralDemo1D.epochInBundle1D, IG.Neural.NeuralNetworks.HiddenNeuron1L, IG.Neural.NeuralNetworks.HiddenNeuron2L, IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL11D, IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL21D, IG.Neural.NeuralNetworks.InputSafetyFactor, IG.Neural.Forms.NeuralDemo1D.inputSafetyFactor1D, IG.Neural.NeuralNetworks.LearningRate, IG.Neural.Forms.NeuralDemo1D.learningRate1D, IG.Neural.NeuralNetworks.MaxEpoch, IG.Neural.Forms.NeuralDemo1D.maxEpoch1D, IG.Neural.NeuralNetworks.Momentum, IG.Neural.Forms.NeuralDemo1D.momentum1D, IG.Neural.Forms.NeuralDemo1D.network1D, IG.Neural.NeuralNetworks.OutputSafetyFactor, IG.Neural.Forms.NeuralDemo1D.outputSafetyFactor1D, IG.Neural.NeuralNetworks.RMS, IG.Neural.Forms.NeuralDemo1D.rmsError1D, IG.Neural.Forms.NeuralDemo1D.trainingPoints1D, and IG.Neural.Forms.NeuralDemo1D.TrainNetworkThread1D().
btStop1D_Click() [2/5]
void IG.Neural.Forms.NeuralDemo1D.btStop1D_Click (object sender, EventArgs e) inline private
References IG.Neural.NeuralNetworks.BreakTraining, IG.Neural.Forms.NeuralDemo1D.network1D, and IG.Neural.Forms.NeuralDemo1D.stopTraining1D.
TrainNetworkThread1D() [2/5]
void IG.Neural.Forms.NeuralDemo1D.TrainNetworkThread1D () inline private
References IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D.
btnGenerateOptData1D_Click() [2/5]
void IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click (object sender, EventArgs e) inline private
Generate training data button.
References IG.Neural.Forms.NeuralDemo1D.cbRandomData1D, IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph(), IG.Neural.Forms.NeuralDemo1D.ClearDefaultGraph(), IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Neural.Forms.NeuralDemo1D.ClearTrainingGraph(), IG.Neural.Forms.NeuralDemo1D.createFunction1D(), IG.Neural.Forms.NeuralDemo1D.defaultFunctionData1D, IG.Neural.TestFunctions.GenerateFunctionTrainingSamples(), IG.Neural.Forms.NeuralDemo1D.highHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.InitializeApproximator1D(), IG.Neural.Forms.NeuralDemo1D.lowHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.pane1D, IG.Neural.Forms.NeuralDemo1D.PrepareTrainingPoints1D(), IG.Neural.Forms.NeuralDemo1D.tbEquationError1D, IG.Neural.Forms.NeuralDemo1D.trainingData1D, IG.Neural.Forms.NeuralDemo1D.verificationData1D, IG.Neural.Forms.NeuralDemo1D.WriteDefaultFunction1D(), and IG.Neural.Forms.NeuralDemo1D.WriteTrainingPoints1D().
rbMaxTrainError_CheckedChanged() [2/5]
void IG.Neural.Forms.NeuralDemo1D.rbMaxTrainError_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum training error convergence to be written on graph.
References IG.Neural.Forms.NeuralDemo1D.maxTrainErrorEnabled1D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
rbRmsTrainError_CheckedChanged() [2/5]
void IG.Neural.Forms.NeuralDemo1D.rbRmsTrainError_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms training error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Neural.Forms.NeuralDemo1D.rmsTrainErrorEnabled1D, and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
rbMaxVerError_CheckedChanged() [2/5]
void IG.Neural.Forms.NeuralDemo1D.rbMaxVerError_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum verification error convergence to be written on graph.
References IG.Neural.Forms.NeuralDemo1D.maxVerErrorEnabled1D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
rbRmsVerError_CheckedChanged() [2/5]
void IG.Neural.Forms.NeuralDemo1D.rbRmsVerError_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms verification error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Neural.Forms.NeuralDemo1D.rmsVerErrorEnabled1D, and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
cbSelfMade1D_CheckedChanged() [2/5]
void IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D_CheckedChanged (object sender, EventArgs e) inline private
Enable posibility to self made the equation.
References IG.Neural.Forms.NeuralDemo1D.cbEquation1D, IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D, and IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D.
cbRandomData1D_CheckedChanged() [2/5]
void IG.Neural.Forms.NeuralDemo1D.cbRandomData1D_CheckedChanged (object sender, EventArgs e) inline private
Enable random training points.
References IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
cbEquation1D_SelectedIndexChanged() [2/5]
void IG.Neural.Forms.NeuralDemo1D.cbEquation1D_SelectedIndexChanged (object sender, EventArgs e) inline private
Select equation from the list.
References IG.Neural.Forms.NeuralDemo1D.cbEquation1D, IG.Neural.Forms.NeuralDemo1D.equation1D, and IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
tbSelfMadeEquation1D_TextChanged() [2/5]
void IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D_TextChanged (object sender, EventArgs e) inline private
Equation string.
References IG.Neural.Forms.NeuralDemo1D.equation1D, and IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D.
numSamples1D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralDemo1D.numSamples1D_ValueChanged (object sender, EventArgs e) inline private
Number of training samples generated.
References IG.Neural.Forms.NeuralDemo1D.numSamples1D, and IG.Neural.Forms.NeuralDemo1D.samples1D.
numLowXLimit1D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D_ValueChanged (object sender, EventArgs e) inline private
Lower limit for x-axes on the graph.
References IG.Neural.Forms.NeuralDemo1D.lowHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D, and IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
numHighXLimit1D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D_ValueChanged (object sender, EventArgs e) inline private
Higher limit for x-axes on the graph.
References IG.Neural.Forms.NeuralDemo1D.highHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D, and IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
numMaxEpoch1D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D_ValueChanged (object sender, EventArgs e) inline private
Maximum number of epochs.
References IG.Neural.Forms.NeuralDemo1D.maxEpoch1D, and IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D.
numEpochBundle1D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D_ValueChanged (object sender, EventArgs e) inline private
Number of epochs in bundle.
References IG.Neural.Forms.NeuralDemo1D.epochInBundle1D, and IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D.
numRMS1D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralDemo1D.numRMS1D_ValueChanged (object sender, EventArgs e) inline private
Rms error limit.
References IG.Neural.Forms.NeuralDemo1D.numRMS1D, and IG.Neural.Forms.NeuralDemo1D.rmsError1D.
numLearningRate1D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralDemo1D.numLearningRate1D_ValueChanged (object sender, EventArgs e) inline private
Learning rate.
References IG.Neural.Forms.NeuralDemo1D.learningRate1D, and IG.Neural.Forms.NeuralDemo1D.numLearningRate1D.
numMomentum1D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralDemo1D.numMomentum1D_ValueChanged (object sender, EventArgs e) inline private
Momentum.
References IG.Neural.Forms.NeuralDemo1D.momentum1D, and IG.Neural.Forms.NeuralDemo1D.numMomentum1D.
numHiddenNeuron1D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in first hidden layer.
References IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL11D, and IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D.
numHiddenNeuronL21D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in second hidden layer.
References IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL21D, and IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D.
numInputSafety1D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralDemo1D.numInputSafety1D_ValueChanged (object sender, EventArgs e) inline private
Input safety factor.
References IG.Neural.Forms.NeuralDemo1D.inputSafetyFactor1D, and IG.Neural.Forms.NeuralDemo1D.numInputSafety1D.
numOutputSafety1D_ValueChanged() [2/5]
void IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D_ValueChanged (object sender, EventArgs e) inline private
Output safety factor.
References IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D, and IG.Neural.Forms.NeuralDemo1D.outputSafetyFactor1D.
backgroundWorker1D_DoWork() [2/5]
void IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_DoWork (object sender, DoWorkEventArgs e) inline private
This event handler deals with the results of the background operation.
References IG.Neural.NeuralNetworks.BreakTraining, IG.Neural.Forms.NeuralDemo1D.network1D, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Neural.Forms.NeuralDemo1D.stopTraining1D, IG.Neural.Forms.NeuralDemo1D.trainingData1D, IG.Neural.NeuralNetworks.TrainNetwork(), and IG.Neural.Forms.NeuralDemo1D.verificationData1D.
backgroundWorker1D_RunWorkerCompleted() [2/5]
void IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
This event handler deals with the results of the background operation.
References IG.Neural.Forms.NeuralDemo1D.btLoadANN1D, IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D, IG.Neural.Forms.NeuralDemo1D.btnReset1D, IG.Neural.Forms.NeuralDemo1D.btSaveANN1D, IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.btStop1D, IG.Neural.Forms.NeuralDemo1D.WriteApproxGraf1D(), and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
Dispose() [2/5]
override void IG.Neural.Forms.NeuralDemo1D.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralDemo1D.components.
InitializeComponent() [2/5]
void IG.Neural.Forms.NeuralDemo1D.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D, IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_DoWork(), IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_RunWorkerCompleted(), IG.Neural.Forms.NeuralDemo1D.btLoad1D, IG.Neural.Forms.NeuralDemo1D.btLoadANN1D, IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D, IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click(), IG.Neural.Forms.NeuralDemo1D.btnReset1D, IG.Neural.Forms.NeuralDemo1D.btnReset1D_Click(), IG.Neural.Forms.NeuralDemo1D.btSaveANN1D, IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), IG.Neural.Forms.NeuralDemo1D.btStop1D, IG.Neural.Forms.NeuralDemo1D.btStop1D_Click(), IG.Neural.Forms.NeuralDemo1D.cbEquation1D, IG.Neural.Forms.NeuralDemo1D.cbEquation1D_SelectedIndexChanged(), IG.Neural.Forms.NeuralDemo1D.cbRandomData1D, IG.Neural.Forms.NeuralDemo1D.cbRandomData1D_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D, IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.errorConvergence1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Neural.Forms.NeuralDemo1D.groupBox5, IG.Neural.Forms.NeuralDemo1D.groupBox6, IG.Neural.Forms.NeuralDemo1D.groupBox7, IG.Neural.Forms.NeuralDemo1D.groupBox9, IG.Neural.Forms.NeuralDemo1D.label1, IG.Neural.Forms.NeuralDemo1D.label11, IG.Neural.Forms.NeuralDemo1D.label12, IG.Neural.Forms.NeuralDemo1D.label13, IG.Neural.Forms.NeuralDemo1D.label15, IG.Neural.Forms.NeuralDemo1D.label16, IG.Neural.Forms.NeuralDemo1D.label19, IG.Neural.Forms.NeuralDemo1D.label2, IG.Neural.Forms.NeuralDemo1D.label4, IG.Neural.Forms.NeuralDemo1D.label5, IG.Neural.Forms.NeuralDemo1D.label6, IG.Neural.Forms.NeuralDemo1D.label7, IG.Neural.Forms.NeuralDemo1D.label8, IG.Neural.Forms.NeuralDemo1D.label9, IG.Neural.Forms.NeuralDemo1D.LoadForm(), IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D, IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D, IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D, IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D, IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numInputSafety1D, IG.Neural.Forms.NeuralDemo1D.numInputSafety1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numLearningRate1D, IG.Neural.Forms.NeuralDemo1D.numLearningRate1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D, IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D, IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numMomentum1D, IG.Neural.Forms.NeuralDemo1D.numMomentum1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D, IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numRMS1D, IG.Neural.Forms.NeuralDemo1D.numRMS1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numSamples1D, IG.Neural.Forms.NeuralDemo1D.numSamples1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.rbMaxTrainError, IG.Neural.Forms.NeuralDemo1D.rbMaxTrainError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.rbMaxVerError, IG.Neural.Forms.NeuralDemo1D.rbMaxVerError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.rbRmsTrainError, IG.Neural.Forms.NeuralDemo1D.rbRmsTrainError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.rbRmsVerError, IG.Neural.Forms.NeuralDemo1D.rbRmsVerError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.tbEquationError1D, IG.Neural.Forms.NeuralDemo1D.tbMaxTrainError1D, IG.Neural.Forms.NeuralDemo1D.tbMaxVerError1D, IG.Neural.Forms.NeuralDemo1D.tbRmsTrainError1D, IG.Neural.Forms.NeuralDemo1D.tbRmsVerError1D, IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D, and IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D_TextChanged().
LoadForm() [3/5]
void IG.Neural.Forms.NeuralDemo1D.LoadForm (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralDemo1D.errorConvergence1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Neural.Forms.NeuralDemo1D.pane1D, and IG.Neural.Forms.NeuralDemo1D.pane1DError.
PredictFromApproximator() [3/5]
void IG.Neural.Forms.NeuralDemo1D.PredictFromApproximator (ref IVector[] exactInputParameters1D, ref IVector[] approximatedOutputValues1D) inline private
Calculate approximation response on verification points stored in approximator.
Parameters
exactInputParameters1D Exact input parameters from verification points.
approximatedOutputValues1D Approximated output values from verification points.
References IG.Num.IVectorApproximator.CalculateOutput(), IG.Lib.SortedUniqueItemList< Type >.Contains(), IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputRange(), IG.Num.SampledDataSet.Length, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Num.INeuralApproximator.NumVerificationPoints, IG.Num.SampledDataSet.OutputLength, IG.Num.INeuralApproximator.TrainingData, and IG.Num.INeuralApproximator.VerificationIndices.
createFunction1D() [3/5]
IRealFunction IG.Neural.Forms.NeuralDemo1D.createFunction1D () inline private
Creates a function loader and uses it for dynamic definition of functions.
References IG.Lib.RealFunctionLoader.CreateRealFunction(), IG.Neural.Forms.NeuralDemo1D.equation1D, IG.Lib.RealFunctionLoader.IndependentVariableName, IG.Lib.RealFunctionLoader.InvalidateDefinitions(), IG.Neural.Forms.NeuralDemo1D.tbEquationError1D, IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D, and IG.Lib.RealFunctionLoader.ValueDefinitionString.
CreateGreenRedYellow() [3/5]
static ColorScale IG.Neural.Forms.NeuralDemo1D.CreateGreenRedYellow (double minValue, double maxValue) inline static
EnableControls1D() [3/5]
void IG.Neural.Forms.NeuralDemo1D.EnableControls1D (bool enabled) inline private
References IG.Neural.Forms.NeuralDemo1D.disabledColor1D, IG.Neural.Forms.NeuralDemo1D.enabledColor1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, and IG.Neural.Forms.NeuralDemo1D.trainingPoints1D.
InitializeApproximator1D() [3/5]
void IG.Neural.Forms.NeuralDemo1D.InitializeApproximator1D () inline private
Clean the approximator.
References IG.Neural.Forms.NeuralDemo1D.NeuralApproximator.
GraphDimensions1D() [3/5]
void IG.Neural.Forms.NeuralDemo1D.GraphDimensions1D (SampledDataSet data1D) inline private
Prepare graph for 1 dimension.
Parameters
data Data set.
References IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.Length, and IG.Neural.Forms.NeuralDemo1D.pane1D.
PrepareTrainingPoints1D() [3/5]
void IG.Neural.Forms.NeuralDemo1D.PrepareTrainingPoints1D (bool randomPoints1D) inline private
Preparing training points.
References IG.Num.SampledDataSet.AddElement(), IG.Neural.Forms.NeuralDemo1D.defaultFunctionData1D, IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Neural.Forms.NeuralDemo1D.highVerificationHorizontalLimit1D, IG.Num.SampledDataSet.Length, IG.Neural.Forms.NeuralDemo1D.lowVerificationHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.samples1D, and IG.Neural.Forms.NeuralDemo1D.trainingData1D.
WriteDefaultFunction1D() [3/5]
void IG.Neural.Forms.NeuralDemo1D.WriteDefaultFunction1D () inline private
Write default Function for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.defaultFunction1D, IG.Neural.Forms.NeuralDemo1D.defaultFunctionData1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Neural.Forms.NeuralDemo1D.GraphDimensions1D(), and IG.Num.SampledDataSet.Length.
WriteTrainingPoints1D() [3/5]
void IG.Neural.Forms.NeuralDemo1D.WriteTrainingPoints1D (SampledDataSet trainingData1D) inline private
Write training points for 1 dimension.
Parameters
trainingData1D Training data.
References IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.enabledColor1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.InputLength, IG.Num.IVector< T >.Length, IG.Num.SampledDataSet.Length, IG.Num.SampledDataSet.OutputLength, IG.Neural.Forms.NeuralDemo1D.trainingData1D, and IG.Neural.Forms.NeuralDemo1D.trainingPoints1D.
WriteApproxGraf1D() [3/5]
void IG.Neural.Forms.NeuralDemo1D.WriteApproxGraf1D () inline private
Write approximation line 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.approximatedLine1D, IG.Neural.Forms.NeuralDemo1D.EnableControls1D(), IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Neural.Forms.NeuralDemo1D.PredictFromApproximator(), and IG.Neural.Forms.NeuralDemo1D.thread1D.
WriteErrors1D() [3/5]
void IG.Neural.Forms.NeuralDemo1D.WriteErrors1D () inline private
Write training and verification errors in text box.
References IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Num.INeuralApproximator.ConvergenceErrorsTrainingMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsTrainingRmsList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationRmsList, IG.Neural.Forms.NeuralDemo1D.epochInBundle1D, IG.Neural.Forms.NeuralDemo1D.errorConvergence1D, IG.Neural.Forms.NeuralDemo1D.errorConvergenceFunction1D, IG.Num.INeuralApproximator.GetErrorsTrainingMax(), IG.Num.INeuralApproximator.GetErrorsTrainingRms(), IG.Num.INeuralApproximator.GetErrorsVerificationMax(), IG.Num.INeuralApproximator.GetErrorsVerificationRms(), IG.Neural.Forms.NeuralDemo1D.maxTrainErrorEnabled1D, IG.Neural.Forms.NeuralDemo1D.maxVerErrorEnabled1D, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Neural.Forms.NeuralDemo1D.pane1DError, IG.Neural.Forms.NeuralDemo1D.rmsTrainErrorEnabled1D, IG.Neural.Forms.NeuralDemo1D.rmsVerErrorEnabled1D, IG.Neural.Forms.NeuralDemo1D.tbMaxTrainError1D, IG.Neural.Forms.NeuralDemo1D.tbMaxVerError1D, IG.Neural.Forms.NeuralDemo1D.tbRmsTrainError1D, and IG.Neural.Forms.NeuralDemo1D.tbRmsVerError1D.
ClearDefaultGraph() [3/5]
void IG.Neural.Forms.NeuralDemo1D.ClearDefaultGraph () inline private
Clear Graph with default function for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.defaultFunction1D, and IG.Neural.Forms.NeuralDemo1D.functionGraph.
ClearApproximationGraph() [3/5]
void IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph () inline private
Clear Graph with approximative function for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.approximatedLine1D, and IG.Neural.Forms.NeuralDemo1D.functionGraph.
ClearTrainingGraph() [3/5]
void IG.Neural.Forms.NeuralDemo1D.ClearTrainingGraph () inline private
Clear Graph with training points for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.functionGraph, and IG.Neural.Forms.NeuralDemo1D.trainingPoints1D.
ClearErrorGraph1D() [3/5]
void IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D () inline private
Clear Graph with error convergence for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.errorConvergence1D, IG.Neural.Forms.NeuralDemo1D.errorConvergenceFunction1D, IG.Neural.Forms.NeuralDemo1D.tbMaxTrainError1D, IG.Neural.Forms.NeuralDemo1D.tbMaxVerError1D, IG.Neural.Forms.NeuralDemo1D.tbRmsTrainError1D, and IG.Neural.Forms.NeuralDemo1D.tbRmsVerError1D.
ResetAll1D() [3/5]
void IG.Neural.Forms.NeuralDemo1D.ResetAll1D () inline private
Invalidates training results AND training data, and makes corresponding changes in GUI (e.g. disables certain buttons, etc.).
References IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph(), IG.Neural.Forms.NeuralDemo1D.ClearDefaultGraph(), IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Neural.Forms.NeuralDemo1D.ClearTrainingGraph(), and IG.Neural.Forms.NeuralDemo1D.InitializeApproximator1D().
ResetResults1D() [2/4]
void IG.Neural.Forms.NeuralDemo1D.ResetResults1D () inline private
Invalidates the training results and makes corresponding changes in GUI to reflect this.
btnReset1D_Click() [3/5]
void IG.Neural.Forms.NeuralDemo1D.btnReset1D_Click (object sender, EventArgs e) inline private
Reset button.
References IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
btStart1D_Click() [3/5]
void IG.Neural.Forms.NeuralDemo1D.btStart1D_Click (object sender, EventArgs e) inline private
Start training button.
References IG.Neural.Forms.NeuralDemo1D.btLoadANN1D, IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D, IG.Neural.Forms.NeuralDemo1D.btnReset1D, IG.Neural.Forms.NeuralDemo1D.btSaveANN1D, IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.btStop1D, IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph(), IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Neural.Forms.NeuralDemo1D.EnableControls1D(), IG.Neural.Forms.NeuralDemo1D.enabledColor1D, IG.Neural.NeuralNetworks.EpochBundle, IG.Neural.Forms.NeuralDemo1D.epochInBundle1D, IG.Neural.NeuralNetworks.HiddenNeuron1L, IG.Neural.NeuralNetworks.HiddenNeuron2L, IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL11D, IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL21D, IG.Neural.NeuralNetworks.InputSafetyFactor, IG.Neural.Forms.NeuralDemo1D.inputSafetyFactor1D, IG.Neural.NeuralNetworks.LearningRate, IG.Neural.Forms.NeuralDemo1D.learningRate1D, IG.Neural.NeuralNetworks.MaxEpoch, IG.Neural.Forms.NeuralDemo1D.maxEpoch1D, IG.Neural.NeuralNetworks.Momentum, IG.Neural.Forms.NeuralDemo1D.momentum1D, IG.Neural.Forms.NeuralDemo1D.network1D, IG.Neural.NeuralNetworks.OutputSafetyFactor, IG.Neural.Forms.NeuralDemo1D.outputSafetyFactor1D, IG.Neural.NeuralNetworks.RMS, IG.Neural.Forms.NeuralDemo1D.rmsError1D, IG.Neural.Forms.NeuralDemo1D.trainingPoints1D, and IG.Neural.Forms.NeuralDemo1D.TrainNetworkThread1D().
btStop1D_Click() [3/5]
void IG.Neural.Forms.NeuralDemo1D.btStop1D_Click (object sender, EventArgs e) inline private
References IG.Neural.NeuralNetworks.BreakTraining, IG.Neural.Forms.NeuralDemo1D.network1D, and IG.Neural.Forms.NeuralDemo1D.stopTraining1D.
TrainNetworkThread1D() [3/5]
void IG.Neural.Forms.NeuralDemo1D.TrainNetworkThread1D () inline private
References IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D.
btnGenerateOptData1D_Click() [3/5]
void IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click (object sender, EventArgs e) inline private
Generate training data button.
References IG.Neural.Forms.NeuralDemo1D.cbRandomData1D, IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph(), IG.Neural.Forms.NeuralDemo1D.ClearDefaultGraph(), IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Neural.Forms.NeuralDemo1D.ClearTrainingGraph(), IG.Neural.Forms.NeuralDemo1D.createFunction1D(), IG.Neural.Forms.NeuralDemo1D.defaultFunctionData1D, IG.Neural.TestFunctions.GenerateFunctionTrainingSamples(), IG.Neural.Forms.NeuralDemo1D.highHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.InitializeApproximator1D(), IG.Neural.Forms.NeuralDemo1D.lowHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.pane1D, IG.Neural.Forms.NeuralDemo1D.PrepareTrainingPoints1D(), IG.Neural.Forms.NeuralDemo1D.tbEquationError1D, IG.Neural.Forms.NeuralDemo1D.trainingData1D, IG.Neural.Forms.NeuralDemo1D.verificationData1D, IG.Neural.Forms.NeuralDemo1D.WriteDefaultFunction1D(), and IG.Neural.Forms.NeuralDemo1D.WriteTrainingPoints1D().
rbMaxTrainError_CheckedChanged() [3/5]
void IG.Neural.Forms.NeuralDemo1D.rbMaxTrainError_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum training error convergence to be written on graph.
References IG.Neural.Forms.NeuralDemo1D.maxTrainErrorEnabled1D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
rbRmsTrainError_CheckedChanged() [3/5]
void IG.Neural.Forms.NeuralDemo1D.rbRmsTrainError_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms training error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Neural.Forms.NeuralDemo1D.rmsTrainErrorEnabled1D, and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
rbMaxVerError_CheckedChanged() [3/5]
void IG.Neural.Forms.NeuralDemo1D.rbMaxVerError_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum verification error convergence to be written on graph.
References IG.Neural.Forms.NeuralDemo1D.maxVerErrorEnabled1D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
rbRmsVerError_CheckedChanged() [3/5]
void IG.Neural.Forms.NeuralDemo1D.rbRmsVerError_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms verification error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Neural.Forms.NeuralDemo1D.rmsVerErrorEnabled1D, and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
cbSelfMade1D_CheckedChanged() [3/5]
void IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D_CheckedChanged (object sender, EventArgs e) inline private
Enable posibility to self made the equation.
References IG.Neural.Forms.NeuralDemo1D.cbEquation1D, IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D, IG.Neural.Forms.NeuralDemo1D.ResetAll1D(), and IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D.
cbRandomData1D_CheckedChanged() [3/5]
void IG.Neural.Forms.NeuralDemo1D.cbRandomData1D_CheckedChanged (object sender, EventArgs e) inline private
Enable random training points.
References IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
cbEquation1D_SelectedIndexChanged() [3/5]
void IG.Neural.Forms.NeuralDemo1D.cbEquation1D_SelectedIndexChanged (object sender, EventArgs e) inline private
Select equation from the list.
References IG.Neural.Forms.NeuralDemo1D.cbEquation1D, IG.Neural.Forms.NeuralDemo1D.equation1D, and IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
tbSelfMadeEquation1D_TextChanged() [3/5]
void IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D_TextChanged (object sender, EventArgs e) inline private
Equation string.
References IG.Neural.Forms.NeuralDemo1D.equation1D, and IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D.
numSamples1D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralDemo1D.numSamples1D_ValueChanged (object sender, EventArgs e) inline private
Number of training samples generated.
References IG.Neural.Forms.NeuralDemo1D.numSamples1D, IG.Neural.Forms.NeuralDemo1D.ResetAll1D(), and IG.Neural.Forms.NeuralDemo1D.samples1D.
numLowXLimit1D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D_ValueChanged (object sender, EventArgs e) inline private
Lower limit for x-axes on the graph.
References IG.Neural.Forms.NeuralDemo1D.lowHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D, and IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
numHighXLimit1D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D_ValueChanged (object sender, EventArgs e) inline private
Higher limit for x-axes on the graph.
References IG.Neural.Forms.NeuralDemo1D.highHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D, and IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
numMaxEpoch1D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D_ValueChanged (object sender, EventArgs e) inline private
Maximum number of epochs.
References IG.Neural.Forms.NeuralDemo1D.maxEpoch1D, and IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D.
numEpochBundle1D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D_ValueChanged (object sender, EventArgs e) inline private
Number of epochs in bundle.
References IG.Neural.Forms.NeuralDemo1D.epochInBundle1D, and IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D.
numRMS1D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralDemo1D.numRMS1D_ValueChanged (object sender, EventArgs e) inline private
Rms error limit.
References IG.Neural.Forms.NeuralDemo1D.numRMS1D, and IG.Neural.Forms.NeuralDemo1D.rmsError1D.
numLearningRate1D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralDemo1D.numLearningRate1D_ValueChanged (object sender, EventArgs e) inline private
Learning rate.
References IG.Neural.Forms.NeuralDemo1D.learningRate1D, and IG.Neural.Forms.NeuralDemo1D.numLearningRate1D.
numMomentum1D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralDemo1D.numMomentum1D_ValueChanged (object sender, EventArgs e) inline private
Momentum.
References IG.Neural.Forms.NeuralDemo1D.momentum1D, and IG.Neural.Forms.NeuralDemo1D.numMomentum1D.
numHiddenNeuron1D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in first hidden layer.
References IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL11D, and IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D.
numHiddenNeuronL21D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in second hidden layer.
References IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL21D, and IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D.
numInputSafety1D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralDemo1D.numInputSafety1D_ValueChanged (object sender, EventArgs e) inline private
Input safety factor.
References IG.Neural.Forms.NeuralDemo1D.inputSafetyFactor1D, and IG.Neural.Forms.NeuralDemo1D.numInputSafety1D.
numOutputSafety1D_ValueChanged() [3/5]
void IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D_ValueChanged (object sender, EventArgs e) inline private
Output safety factor.
References IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D, and IG.Neural.Forms.NeuralDemo1D.outputSafetyFactor1D.
backgroundWorker1D_DoWork() [3/5]
void IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_DoWork (object sender, DoWorkEventArgs e) inline private
This event handler deals with the results of the background operation.
References IG.Neural.NeuralNetworks.BreakTraining, IG.Neural.Forms.NeuralDemo1D.network1D, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Neural.Forms.NeuralDemo1D.stopTraining1D, IG.Neural.Forms.NeuralDemo1D.trainingData1D, IG.Neural.NeuralNetworks.TrainNetwork(), and IG.Neural.Forms.NeuralDemo1D.verificationData1D.
backgroundWorker1D_RunWorkerCompleted() [3/5]
void IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
This event handler deals with the results of the background operation.
References IG.Neural.Forms.NeuralDemo1D.btLoadANN1D, IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D, IG.Neural.Forms.NeuralDemo1D.btnReset1D, IG.Neural.Forms.NeuralDemo1D.btSaveANN1D, IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.btStop1D, IG.Neural.Forms.NeuralDemo1D.WriteApproxGraf1D(), and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
Dispose() [3/5]
override void IG.Neural.Forms.NeuralDemo1D.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralDemo1D.components.
InitializeComponent() [3/5]
void IG.Neural.Forms.NeuralDemo1D.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D, IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_DoWork(), IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_RunWorkerCompleted(), IG.Neural.Forms.NeuralDemo1D.btLoad1D, IG.Neural.Forms.NeuralDemo1D.btLoadANN1D, IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D, IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click(), IG.Neural.Forms.NeuralDemo1D.btnReset1D, IG.Neural.Forms.NeuralDemo1D.btnReset1D_Click(), IG.Neural.Forms.NeuralDemo1D.btSaveANN1D, IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), IG.Neural.Forms.NeuralDemo1D.btStop1D, IG.Neural.Forms.NeuralDemo1D.btStop1D_Click(), IG.Neural.Forms.NeuralDemo1D.cbEquation1D, IG.Neural.Forms.NeuralDemo1D.cbEquation1D_SelectedIndexChanged(), IG.Neural.Forms.NeuralDemo1D.cbRandomData1D, IG.Neural.Forms.NeuralDemo1D.cbRandomData1D_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D, IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.components, IG.Neural.Forms.NeuralDemo1D.errorConvergence1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Neural.Forms.NeuralDemo1D.groupBox5, IG.Neural.Forms.NeuralDemo1D.groupBox6, IG.Neural.Forms.NeuralDemo1D.groupBox7, IG.Neural.Forms.NeuralDemo1D.groupBox9, IG.Neural.Forms.NeuralDemo1D.label1, IG.Neural.Forms.NeuralDemo1D.label11, IG.Neural.Forms.NeuralDemo1D.label12, IG.Neural.Forms.NeuralDemo1D.label13, IG.Neural.Forms.NeuralDemo1D.label15, IG.Neural.Forms.NeuralDemo1D.label16, IG.Neural.Forms.NeuralDemo1D.label19, IG.Neural.Forms.NeuralDemo1D.label2, IG.Neural.Forms.NeuralDemo1D.label4, IG.Neural.Forms.NeuralDemo1D.label5, IG.Neural.Forms.NeuralDemo1D.label6, IG.Neural.Forms.NeuralDemo1D.label7, IG.Neural.Forms.NeuralDemo1D.label8, IG.Neural.Forms.NeuralDemo1D.label9, IG.Neural.Forms.NeuralDemo1D.LoadForm(), IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D, IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D, IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D, IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D, IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numInputSafety1D, IG.Neural.Forms.NeuralDemo1D.numInputSafety1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numLearningRate1D, IG.Neural.Forms.NeuralDemo1D.numLearningRate1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D, IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D, IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numMomentum1D, IG.Neural.Forms.NeuralDemo1D.numMomentum1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D, IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numRMS1D, IG.Neural.Forms.NeuralDemo1D.numRMS1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numSamples1D, IG.Neural.Forms.NeuralDemo1D.numSamples1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.rbMaxTrainError, IG.Neural.Forms.NeuralDemo1D.rbMaxTrainError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.rbMaxVerError, IG.Neural.Forms.NeuralDemo1D.rbMaxVerError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.rbRmsTrainError, IG.Neural.Forms.NeuralDemo1D.rbRmsTrainError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.rbRmsVerError, IG.Neural.Forms.NeuralDemo1D.rbRmsVerError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.tbEquationError1D, IG.Neural.Forms.NeuralDemo1D.tbMaxTrainError1D, IG.Neural.Forms.NeuralDemo1D.tbMaxVerError1D, IG.Neural.Forms.NeuralDemo1D.tbRmsTrainError1D, IG.Neural.Forms.NeuralDemo1D.tbRmsVerError1D, IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D, and IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D_TextChanged().
LoadForm() [4/5]
void IG.Neural.Forms.NeuralDemo1D.LoadForm (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralDemo1D.errorConvergence1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Neural.Forms.NeuralDemo1D.pane1D, and IG.Neural.Forms.NeuralDemo1D.pane1DError.
PredictFromApproximator() [4/5]
void IG.Neural.Forms.NeuralDemo1D.PredictFromApproximator (ref IVector[] exactInputParameters1D, ref IVector[] approximatedOutputValues1D) inline private
Calculate approximation response on verification points stored in approximator.
Parameters
exactInputParameters1D Exact input parameters from verification points.
approximatedOutputValues1D Approximated output values from verification points.
References IG.Num.IVectorApproximator.CalculateOutput(), IG.Lib.SortedUniqueItemList< Type >.Contains(), IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputRange(), IG.Num.SampledDataSet.Length, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Num.INeuralApproximator.NumVerificationPoints, IG.Num.SampledDataSet.OutputLength, IG.Num.INeuralApproximator.TrainingData, and IG.Num.INeuralApproximator.VerificationIndices.
createFunction1D() [4/5]
IRealFunction IG.Neural.Forms.NeuralDemo1D.createFunction1D () inline private
Creates a function loader and uses it for dynamic definition of functions.
References IG.Lib.RealFunctionLoader.CreateRealFunction(), IG.Neural.Forms.NeuralDemo1D.equation1D, IG.Lib.RealFunctionLoader.IndependentVariableName, IG.Lib.RealFunctionLoader.InvalidateDefinitions(), IG.Neural.Forms.NeuralDemo1D.tbEquationError1D, IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D, and IG.Lib.RealFunctionLoader.ValueDefinitionString.
CreateGreenRedYellow() [4/5]
static ColorScale IG.Neural.Forms.NeuralDemo1D.CreateGreenRedYellow (double minValue, double maxValue) inline static
EnableControls1D() [4/5]
void IG.Neural.Forms.NeuralDemo1D.EnableControls1D (bool enabled) inline private
References IG.Neural.Forms.NeuralDemo1D.disabledColor1D, IG.Neural.Forms.NeuralDemo1D.enabledColor1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, and IG.Neural.Forms.NeuralDemo1D.trainingPoints1D.
InitializeApproximator1D() [4/5]
void IG.Neural.Forms.NeuralDemo1D.InitializeApproximator1D () inline private
Clean the approximator.
References IG.Neural.Forms.NeuralDemo1D.NeuralApproximator.
GraphDimensions1D() [4/5]
void IG.Neural.Forms.NeuralDemo1D.GraphDimensions1D (SampledDataSet data1D) inline private
Prepare graph for 1 dimension.
Parameters
data Data set.
References IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.Length, and IG.Neural.Forms.NeuralDemo1D.pane1D.
PrepareTrainingPoints1D() [4/5]
void IG.Neural.Forms.NeuralDemo1D.PrepareTrainingPoints1D (bool randomPoints1D) inline private
Preparing training points.
References IG.Num.SampledDataSet.AddElement(), IG.Neural.Forms.NeuralDemo1D.defaultFunctionData1D, IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Neural.Forms.NeuralDemo1D.highVerificationHorizontalLimit1D, IG.Num.SampledDataSet.Length, IG.Neural.Forms.NeuralDemo1D.lowVerificationHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.samples1D, and IG.Neural.Forms.NeuralDemo1D.trainingData1D.
WriteDefaultFunction1D() [4/5]
void IG.Neural.Forms.NeuralDemo1D.WriteDefaultFunction1D () inline private
Write default Function for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.defaultFunction1D, IG.Neural.Forms.NeuralDemo1D.defaultFunctionData1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Neural.Forms.NeuralDemo1D.GraphDimensions1D(), and IG.Num.SampledDataSet.Length.
WriteTrainingPoints1D() [4/5]
void IG.Neural.Forms.NeuralDemo1D.WriteTrainingPoints1D (SampledDataSet trainingData1D) inline private
Write training points for 1 dimension.
Parameters
trainingData1D Training data.
References IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.enabledColor1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.InputLength, IG.Num.IVector< T >.Length, IG.Num.SampledDataSet.Length, IG.Num.SampledDataSet.OutputLength, IG.Neural.Forms.NeuralDemo1D.trainingData1D, and IG.Neural.Forms.NeuralDemo1D.trainingPoints1D.
WriteApproxGraf1D() [4/5]
void IG.Neural.Forms.NeuralDemo1D.WriteApproxGraf1D () inline private
Write approximation line 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.approximatedLine1D, IG.Neural.Forms.NeuralDemo1D.EnableControls1D(), IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Neural.Forms.NeuralDemo1D.PredictFromApproximator(), and IG.Neural.Forms.NeuralDemo1D.thread1D.
WriteErrors1D() [4/5]
void IG.Neural.Forms.NeuralDemo1D.WriteErrors1D () inline private
Write training and verification errors in text box.
References IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Num.INeuralApproximator.ConvergenceErrorsTrainingMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsTrainingRmsList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationRmsList, IG.Neural.Forms.NeuralDemo1D.epochInBundle1D, IG.Neural.Forms.NeuralDemo1D.errorConvergence1D, IG.Neural.Forms.NeuralDemo1D.errorConvergenceFunction1D, IG.Num.INeuralApproximator.GetErrorsTrainingMax(), IG.Num.INeuralApproximator.GetErrorsTrainingRms(), IG.Num.INeuralApproximator.GetErrorsVerificationMax(), IG.Num.INeuralApproximator.GetErrorsVerificationRms(), IG.Neural.Forms.NeuralDemo1D.maxTrainErrorEnabled1D, IG.Neural.Forms.NeuralDemo1D.maxVerErrorEnabled1D, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Neural.Forms.NeuralDemo1D.pane1DError, IG.Neural.Forms.NeuralDemo1D.rmsTrainErrorEnabled1D, IG.Neural.Forms.NeuralDemo1D.rmsVerErrorEnabled1D, IG.Neural.Forms.NeuralDemo1D.tbMaxTrainError1D, IG.Neural.Forms.NeuralDemo1D.tbMaxVerError1D, IG.Neural.Forms.NeuralDemo1D.tbRmsTrainError1D, and IG.Neural.Forms.NeuralDemo1D.tbRmsVerError1D.
ClearDefaultGraph() [4/5]
void IG.Neural.Forms.NeuralDemo1D.ClearDefaultGraph () inline private
Clear Graph with default function for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.defaultFunction1D, and IG.Neural.Forms.NeuralDemo1D.functionGraph.
ClearApproximationGraph() [4/5]
void IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph () inline private
Clear Graph with approximative function for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.approximatedLine1D, and IG.Neural.Forms.NeuralDemo1D.functionGraph.
ClearTrainingGraph() [4/5]
void IG.Neural.Forms.NeuralDemo1D.ClearTrainingGraph () inline private
Clear Graph with training points for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.functionGraph, and IG.Neural.Forms.NeuralDemo1D.trainingPoints1D.
ClearErrorGraph1D() [4/5]
void IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D () inline private
Clear Graph with error convergence for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.errorConvergence1D, IG.Neural.Forms.NeuralDemo1D.errorConvergenceFunction1D, IG.Neural.Forms.NeuralDemo1D.tbMaxTrainError1D, IG.Neural.Forms.NeuralDemo1D.tbMaxVerError1D, IG.Neural.Forms.NeuralDemo1D.tbRmsTrainError1D, and IG.Neural.Forms.NeuralDemo1D.tbRmsVerError1D.
ResetAll1D() [4/5]
void IG.Neural.Forms.NeuralDemo1D.ResetAll1D () inline private
Invalidates training results AND training data, and makes corresponding changes in GUI (e.g. disables certain buttons, etc.).
References IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph(), IG.Neural.Forms.NeuralDemo1D.ClearDefaultGraph(), IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Neural.Forms.NeuralDemo1D.ClearTrainingGraph(), and IG.Neural.Forms.NeuralDemo1D.InitializeApproximator1D().
ResetResults1D() [3/4]
void IG.Neural.Forms.NeuralDemo1D.ResetResults1D () inline private
Invalidates the training results and makes corresponding changes in GUI to reflect this.
btnReset1D_Click() [4/5]
void IG.Neural.Forms.NeuralDemo1D.btnReset1D_Click (object sender, EventArgs e) inline private
Reset button.
References IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
btStart1D_Click() [4/5]
void IG.Neural.Forms.NeuralDemo1D.btStart1D_Click (object sender, EventArgs e) inline private
Start training button.
References IG.Neural.Forms.NeuralDemo1D.btLoadANN1D, IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D, IG.Neural.Forms.NeuralDemo1D.btnReset1D, IG.Neural.Forms.NeuralDemo1D.btSaveANN1D, IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.btStop1D, IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph(), IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Neural.Forms.NeuralDemo1D.EnableControls1D(), IG.Neural.Forms.NeuralDemo1D.enabledColor1D, IG.Neural.NeuralNetworks.EpochBundle, IG.Neural.Forms.NeuralDemo1D.epochInBundle1D, IG.Neural.NeuralNetworks.HiddenNeuron1L, IG.Neural.NeuralNetworks.HiddenNeuron2L, IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL11D, IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL21D, IG.Neural.NeuralNetworks.InputSafetyFactor, IG.Neural.Forms.NeuralDemo1D.inputSafetyFactor1D, IG.Neural.NeuralNetworks.LearningRate, IG.Neural.Forms.NeuralDemo1D.learningRate1D, IG.Neural.NeuralNetworks.MaxEpoch, IG.Neural.Forms.NeuralDemo1D.maxEpoch1D, IG.Neural.NeuralNetworks.Momentum, IG.Neural.Forms.NeuralDemo1D.momentum1D, IG.Neural.Forms.NeuralDemo1D.network1D, IG.Neural.NeuralNetworks.OutputSafetyFactor, IG.Neural.Forms.NeuralDemo1D.outputSafetyFactor1D, IG.Neural.NeuralNetworks.RMS, IG.Neural.Forms.NeuralDemo1D.rmsError1D, IG.Neural.Forms.NeuralDemo1D.trainingPoints1D, and IG.Neural.Forms.NeuralDemo1D.TrainNetworkThread1D().
btStop1D_Click() [4/5]
void IG.Neural.Forms.NeuralDemo1D.btStop1D_Click (object sender, EventArgs e) inline private
References IG.Neural.NeuralNetworks.BreakTraining, IG.Neural.Forms.NeuralDemo1D.network1D, and IG.Neural.Forms.NeuralDemo1D.stopTraining1D.
TrainNetworkThread1D() [4/5]
void IG.Neural.Forms.NeuralDemo1D.TrainNetworkThread1D () inline private
References IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D.
btnGenerateOptData1D_Click() [4/5]
void IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click (object sender, EventArgs e) inline private
Generate training data button.
References IG.Neural.Forms.NeuralDemo1D.cbRandomData1D, IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph(), IG.Neural.Forms.NeuralDemo1D.ClearDefaultGraph(), IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Neural.Forms.NeuralDemo1D.ClearTrainingGraph(), IG.Neural.Forms.NeuralDemo1D.createFunction1D(), IG.Neural.Forms.NeuralDemo1D.defaultFunctionData1D, IG.Neural.TestFunctions.GenerateFunctionTrainingSamples(), IG.Neural.Forms.NeuralDemo1D.highHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.InitializeApproximator1D(), IG.Neural.Forms.NeuralDemo1D.lowHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.pane1D, IG.Neural.Forms.NeuralDemo1D.PrepareTrainingPoints1D(), IG.Neural.Forms.NeuralDemo1D.tbEquationError1D, IG.Neural.Forms.NeuralDemo1D.trainingData1D, IG.Neural.Forms.NeuralDemo1D.verificationData1D, IG.Neural.Forms.NeuralDemo1D.WriteDefaultFunction1D(), and IG.Neural.Forms.NeuralDemo1D.WriteTrainingPoints1D().
rbMaxTrainError_CheckedChanged() [4/5]
void IG.Neural.Forms.NeuralDemo1D.rbMaxTrainError_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum training error convergence to be written on graph.
References IG.Neural.Forms.NeuralDemo1D.maxTrainErrorEnabled1D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
rbRmsTrainError_CheckedChanged() [4/5]
void IG.Neural.Forms.NeuralDemo1D.rbRmsTrainError_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms training error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Neural.Forms.NeuralDemo1D.rmsTrainErrorEnabled1D, and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
rbMaxVerError_CheckedChanged() [4/5]
void IG.Neural.Forms.NeuralDemo1D.rbMaxVerError_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum verification error convergence to be written on graph.
References IG.Neural.Forms.NeuralDemo1D.maxVerErrorEnabled1D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
rbRmsVerError_CheckedChanged() [4/5]
void IG.Neural.Forms.NeuralDemo1D.rbRmsVerError_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms verification error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Neural.Forms.NeuralDemo1D.rmsVerErrorEnabled1D, and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
cbSelfMade1D_CheckedChanged() [4/5]
void IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D_CheckedChanged (object sender, EventArgs e) inline private
Enable posibility to self made the equation.
References IG.Neural.Forms.NeuralDemo1D.cbEquation1D, IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D, IG.Neural.Forms.NeuralDemo1D.ResetAll1D(), and IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D.
cbRandomData1D_CheckedChanged() [4/5]
void IG.Neural.Forms.NeuralDemo1D.cbRandomData1D_CheckedChanged (object sender, EventArgs e) inline private
Enable random training points.
References IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
cbEquation1D_SelectedIndexChanged() [4/5]
void IG.Neural.Forms.NeuralDemo1D.cbEquation1D_SelectedIndexChanged (object sender, EventArgs e) inline private
Select equation from the list.
References IG.Neural.Forms.NeuralDemo1D.cbEquation1D, IG.Neural.Forms.NeuralDemo1D.equation1D, and IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
tbSelfMadeEquation1D_TextChanged() [4/5]
void IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D_TextChanged (object sender, EventArgs e) inline private
Equation string.
References IG.Neural.Forms.NeuralDemo1D.equation1D, and IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D.
numSamples1D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralDemo1D.numSamples1D_ValueChanged (object sender, EventArgs e) inline private
Number of training samples generated.
References IG.Neural.Forms.NeuralDemo1D.numSamples1D, IG.Neural.Forms.NeuralDemo1D.ResetAll1D(), and IG.Neural.Forms.NeuralDemo1D.samples1D.
numLowXLimit1D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D_ValueChanged (object sender, EventArgs e) inline private
Lower limit for x-axes on the graph.
References IG.Neural.Forms.NeuralDemo1D.lowHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D, and IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
numHighXLimit1D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D_ValueChanged (object sender, EventArgs e) inline private
Higher limit for x-axes on the graph.
References IG.Neural.Forms.NeuralDemo1D.highHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D, and IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
numMaxEpoch1D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D_ValueChanged (object sender, EventArgs e) inline private
Maximum number of epochs.
References IG.Neural.Forms.NeuralDemo1D.maxEpoch1D, and IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D.
numEpochBundle1D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D_ValueChanged (object sender, EventArgs e) inline private
Number of epochs in bundle.
References IG.Neural.Forms.NeuralDemo1D.epochInBundle1D, and IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D.
numRMS1D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralDemo1D.numRMS1D_ValueChanged (object sender, EventArgs e) inline private
Rms error limit.
References IG.Neural.Forms.NeuralDemo1D.numRMS1D, and IG.Neural.Forms.NeuralDemo1D.rmsError1D.
numLearningRate1D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralDemo1D.numLearningRate1D_ValueChanged (object sender, EventArgs e) inline private
Learning rate.
References IG.Neural.Forms.NeuralDemo1D.learningRate1D, and IG.Neural.Forms.NeuralDemo1D.numLearningRate1D.
numMomentum1D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralDemo1D.numMomentum1D_ValueChanged (object sender, EventArgs e) inline private
Momentum.
References IG.Neural.Forms.NeuralDemo1D.momentum1D, and IG.Neural.Forms.NeuralDemo1D.numMomentum1D.
numHiddenNeuron1D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in first hidden layer.
References IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL11D, and IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D.
numHiddenNeuronL21D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in second hidden layer.
References IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL21D, and IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D.
numInputSafety1D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralDemo1D.numInputSafety1D_ValueChanged (object sender, EventArgs e) inline private
Input safety factor.
References IG.Neural.Forms.NeuralDemo1D.inputSafetyFactor1D, and IG.Neural.Forms.NeuralDemo1D.numInputSafety1D.
numOutputSafety1D_ValueChanged() [4/5]
void IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D_ValueChanged (object sender, EventArgs e) inline private
Output safety factor.
References IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D, and IG.Neural.Forms.NeuralDemo1D.outputSafetyFactor1D.
backgroundWorker1D_DoWork() [4/5]
void IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_DoWork (object sender, DoWorkEventArgs e) inline private
This event handler deals with the results of the background operation.
References IG.Neural.NeuralNetworks.BreakTraining, IG.Neural.Forms.NeuralDemo1D.network1D, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Neural.Forms.NeuralDemo1D.stopTraining1D, IG.Neural.Forms.NeuralDemo1D.trainingData1D, IG.Neural.NeuralNetworks.TrainNetwork(), and IG.Neural.Forms.NeuralDemo1D.verificationData1D.
backgroundWorker1D_RunWorkerCompleted() [4/5]
void IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
This event handler deals with the results of the background operation.
References IG.Neural.Forms.NeuralDemo1D.btLoadANN1D, IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D, IG.Neural.Forms.NeuralDemo1D.btnReset1D, IG.Neural.Forms.NeuralDemo1D.btSaveANN1D, IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.btStop1D, IG.Neural.Forms.NeuralDemo1D.WriteApproxGraf1D(), and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
Dispose() [4/5]
override void IG.Neural.Forms.NeuralDemo1D.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralDemo1D.components.
InitializeComponent() [4/5]
void IG.Neural.Forms.NeuralDemo1D.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D, IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_DoWork(), IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_RunWorkerCompleted(), IG.Neural.Forms.NeuralDemo1D.btLoad1D, IG.Neural.Forms.NeuralDemo1D.btLoadANN1D, IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D, IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click(), IG.Neural.Forms.NeuralDemo1D.btnReset1D, IG.Neural.Forms.NeuralDemo1D.btnReset1D_Click(), IG.Neural.Forms.NeuralDemo1D.btSaveANN1D, IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), IG.Neural.Forms.NeuralDemo1D.btStop1D, IG.Neural.Forms.NeuralDemo1D.btStop1D_Click(), IG.Neural.Forms.NeuralDemo1D.cbEquation1D, IG.Neural.Forms.NeuralDemo1D.cbEquation1D_SelectedIndexChanged(), IG.Neural.Forms.NeuralDemo1D.cbRandomData1D, IG.Neural.Forms.NeuralDemo1D.cbRandomData1D_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D, IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.components, IG.Neural.Forms.NeuralDemo1D.errorConvergence1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Neural.Forms.NeuralDemo1D.groupBox5, IG.Neural.Forms.NeuralDemo1D.groupBox6, IG.Neural.Forms.NeuralDemo1D.groupBox7, IG.Neural.Forms.NeuralDemo1D.groupBox9, IG.Neural.Forms.NeuralDemo1D.label1, IG.Neural.Forms.NeuralDemo1D.label11, IG.Neural.Forms.NeuralDemo1D.label12, IG.Neural.Forms.NeuralDemo1D.label13, IG.Neural.Forms.NeuralDemo1D.label15, IG.Neural.Forms.NeuralDemo1D.label16, IG.Neural.Forms.NeuralDemo1D.label19, IG.Neural.Forms.NeuralDemo1D.label2, IG.Neural.Forms.NeuralDemo1D.label4, IG.Neural.Forms.NeuralDemo1D.label5, IG.Neural.Forms.NeuralDemo1D.label6, IG.Neural.Forms.NeuralDemo1D.label7, IG.Neural.Forms.NeuralDemo1D.label8, IG.Neural.Forms.NeuralDemo1D.label9, IG.Neural.Forms.NeuralDemo1D.LoadForm(), IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D, IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D, IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D, IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D, IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numInputSafety1D, IG.Neural.Forms.NeuralDemo1D.numInputSafety1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numLearningRate1D, IG.Neural.Forms.NeuralDemo1D.numLearningRate1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D, IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D, IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numMomentum1D, IG.Neural.Forms.NeuralDemo1D.numMomentum1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D, IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numRMS1D, IG.Neural.Forms.NeuralDemo1D.numRMS1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numSamples1D, IG.Neural.Forms.NeuralDemo1D.numSamples1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.rbMaxTrainError, IG.Neural.Forms.NeuralDemo1D.rbMaxTrainError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.rbMaxVerError, IG.Neural.Forms.NeuralDemo1D.rbMaxVerError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.rbRmsTrainError, IG.Neural.Forms.NeuralDemo1D.rbRmsTrainError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.rbRmsVerError, IG.Neural.Forms.NeuralDemo1D.rbRmsVerError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.tbEquationError1D, IG.Neural.Forms.NeuralDemo1D.tbMaxTrainError1D, IG.Neural.Forms.NeuralDemo1D.tbMaxVerError1D, IG.Neural.Forms.NeuralDemo1D.tbRmsTrainError1D, IG.Neural.Forms.NeuralDemo1D.tbRmsVerError1D, IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D, and IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D_TextChanged().
LoadForm() [5/5]
void IG.Neural.Forms.NeuralDemo1D.LoadForm (object sender, EventArgs e) inline private
References IG.Neural.Forms.NeuralDemo1D.errorConvergence1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Neural.Forms.NeuralDemo1D.pane1D, and IG.Neural.Forms.NeuralDemo1D.pane1DError.
PredictFromApproximator() [5/5]
void IG.Neural.Forms.NeuralDemo1D.PredictFromApproximator (ref IVector[] exactInputParameters1D, ref IVector[] approximatedOutputValues1D) inline private
Calculate approximation response on verification points stored in approximator.
Parameters
exactInputParameters1D Exact input parameters from verification points.
approximatedOutputValues1D Approximated output values from verification points.
References IG.Num.IVectorApproximator.CalculateOutput(), IG.Lib.SortedUniqueItemList< Type >.Contains(), IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputRange(), IG.Num.SampledDataSet.Length, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Num.INeuralApproximator.NumVerificationPoints, IG.Num.SampledDataSet.OutputLength, IG.Num.INeuralApproximator.TrainingData, and IG.Num.INeuralApproximator.VerificationIndices.
createFunction1D() [5/5]
IRealFunction IG.Neural.Forms.NeuralDemo1D.createFunction1D () inline private
Creates a function loader and uses it for dynamic definition of functions.
References IG.Lib.RealFunctionLoader.CreateRealFunction(), IG.Neural.Forms.NeuralDemo1D.equation1D, IG.Lib.RealFunctionLoader.IndependentVariableName, IG.Lib.RealFunctionLoader.InvalidateDefinitions(), IG.Neural.Forms.NeuralDemo1D.tbEquationError1D, IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D, and IG.Lib.RealFunctionLoader.ValueDefinitionString.
CreateGreenRedYellow() [5/5]
static ColorScale IG.Neural.Forms.NeuralDemo1D.CreateGreenRedYellow (double minValue, double maxValue) inline static
EnableControls1D() [5/5]
void IG.Neural.Forms.NeuralDemo1D.EnableControls1D (bool enabled) inline private
References IG.Neural.Forms.NeuralDemo1D.disabledColor1D, IG.Neural.Forms.NeuralDemo1D.enabledColor1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, and IG.Neural.Forms.NeuralDemo1D.trainingPoints1D.
InitializeApproximator1D() [5/5]
void IG.Neural.Forms.NeuralDemo1D.InitializeApproximator1D () inline private
Clean the approximator.
References IG.Neural.Forms.NeuralDemo1D.NeuralApproximator.
GraphDimensions1D() [5/5]
void IG.Neural.Forms.NeuralDemo1D.GraphDimensions1D (SampledDataSet data1D) inline private
Prepare graph for 1 dimension.
Parameters
data Data set.
References IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.Length, and IG.Neural.Forms.NeuralDemo1D.pane1D.
PrepareTrainingPoints1D() [5/5]
void IG.Neural.Forms.NeuralDemo1D.PrepareTrainingPoints1D (bool randomPoints1D) inline private
Preparing training points.
References IG.Num.SampledDataSet.AddElement(), IG.Neural.Forms.NeuralDemo1D.defaultFunctionData1D, IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Neural.Forms.NeuralDemo1D.highVerificationHorizontalLimit1D, IG.Num.SampledDataSet.Length, IG.Neural.Forms.NeuralDemo1D.lowVerificationHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.samples1D, and IG.Neural.Forms.NeuralDemo1D.trainingData1D.
WriteDefaultFunction1D() [5/5]
void IG.Neural.Forms.NeuralDemo1D.WriteDefaultFunction1D () inline private
Write default Function for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.defaultFunction1D, IG.Neural.Forms.NeuralDemo1D.defaultFunctionData1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Neural.Forms.NeuralDemo1D.GraphDimensions1D(), and IG.Num.SampledDataSet.Length.
WriteTrainingPoints1D() [5/5]
void IG.Neural.Forms.NeuralDemo1D.WriteTrainingPoints1D (SampledDataSet trainingData1D) inline private
Write training points for 1 dimension.
Parameters
trainingData1D Training data.
References IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.enabledColor1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.InputLength, IG.Num.IVector< T >.Length, IG.Num.SampledDataSet.Length, IG.Num.SampledDataSet.OutputLength, IG.Neural.Forms.NeuralDemo1D.trainingData1D, and IG.Neural.Forms.NeuralDemo1D.trainingPoints1D.
WriteApproxGraf1D() [5/5]
void IG.Neural.Forms.NeuralDemo1D.WriteApproxGraf1D () inline private
Write approximation line 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.approximatedLine1D, IG.Neural.Forms.NeuralDemo1D.EnableControls1D(), IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Neural.Forms.NeuralDemo1D.PredictFromApproximator(), and IG.Neural.Forms.NeuralDemo1D.thread1D.
WriteErrors1D() [5/5]
void IG.Neural.Forms.NeuralDemo1D.WriteErrors1D () inline private
Write training and verification errors in text box.
References IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Num.INeuralApproximator.ConvergenceErrorsTrainingMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsTrainingRmsList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationMaxList, IG.Num.INeuralApproximator.ConvergenceErrorsVerificationRmsList, IG.Neural.Forms.NeuralDemo1D.epochInBundle1D, IG.Neural.Forms.NeuralDemo1D.errorConvergence1D, IG.Neural.Forms.NeuralDemo1D.errorConvergenceFunction1D, IG.Num.INeuralApproximator.GetErrorsTrainingMax(), IG.Num.INeuralApproximator.GetErrorsTrainingRms(), IG.Num.INeuralApproximator.GetErrorsVerificationMax(), IG.Num.INeuralApproximator.GetErrorsVerificationRms(), IG.Neural.Forms.NeuralDemo1D.maxTrainErrorEnabled1D, IG.Neural.Forms.NeuralDemo1D.maxVerErrorEnabled1D, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Neural.Forms.NeuralDemo1D.pane1DError, IG.Neural.Forms.NeuralDemo1D.rmsTrainErrorEnabled1D, IG.Neural.Forms.NeuralDemo1D.rmsVerErrorEnabled1D, IG.Neural.Forms.NeuralDemo1D.tbMaxTrainError1D, IG.Neural.Forms.NeuralDemo1D.tbMaxVerError1D, IG.Neural.Forms.NeuralDemo1D.tbRmsTrainError1D, and IG.Neural.Forms.NeuralDemo1D.tbRmsVerError1D.
ClearDefaultGraph() [5/5]
void IG.Neural.Forms.NeuralDemo1D.ClearDefaultGraph () inline private
Clear Graph with default function for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.defaultFunction1D, and IG.Neural.Forms.NeuralDemo1D.functionGraph.
ClearApproximationGraph() [5/5]
void IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph () inline private
Clear Graph with approximative function for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.approximatedLine1D, and IG.Neural.Forms.NeuralDemo1D.functionGraph.
ClearTrainingGraph() [5/5]
void IG.Neural.Forms.NeuralDemo1D.ClearTrainingGraph () inline private
Clear Graph with training points for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.functionGraph, and IG.Neural.Forms.NeuralDemo1D.trainingPoints1D.
ClearErrorGraph1D() [5/5]
void IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D () inline private
Clear Graph with error convergence for 1 dimension.
References IG.Neural.Forms.NeuralDemo1D.errorConvergence1D, IG.Neural.Forms.NeuralDemo1D.errorConvergenceFunction1D, IG.Neural.Forms.NeuralDemo1D.tbMaxTrainError1D, IG.Neural.Forms.NeuralDemo1D.tbMaxVerError1D, IG.Neural.Forms.NeuralDemo1D.tbRmsTrainError1D, and IG.Neural.Forms.NeuralDemo1D.tbRmsVerError1D.
ResetAll1D() [5/5]
void IG.Neural.Forms.NeuralDemo1D.ResetAll1D () inline private
Invalidates training results AND training data, and makes corresponding changes in GUI (e.g. disables certain buttons, etc.).
References IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph(), IG.Neural.Forms.NeuralDemo1D.ClearDefaultGraph(), IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Neural.Forms.NeuralDemo1D.ClearTrainingGraph(), and IG.Neural.Forms.NeuralDemo1D.InitializeApproximator1D().
ResetResults1D() [4/4]
void IG.Neural.Forms.NeuralDemo1D.ResetResults1D () inline private
Invalidates the training results and makes corresponding changes in GUI to reflect this.
btnReset1D_Click() [5/5]
void IG.Neural.Forms.NeuralDemo1D.btnReset1D_Click (object sender, EventArgs e) inline private
Reset button.
References IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
btStart1D_Click() [5/5]
void IG.Neural.Forms.NeuralDemo1D.btStart1D_Click (object sender, EventArgs e) inline private
Start training button.
References IG.Neural.Forms.NeuralDemo1D.btLoadANN1D, IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D, IG.Neural.Forms.NeuralDemo1D.btnReset1D, IG.Neural.Forms.NeuralDemo1D.btSaveANN1D, IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.btStop1D, IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph(), IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Neural.Forms.NeuralDemo1D.EnableControls1D(), IG.Neural.Forms.NeuralDemo1D.enabledColor1D, IG.Neural.NeuralNetworks.EpochBundle, IG.Neural.Forms.NeuralDemo1D.epochInBundle1D, IG.Neural.NeuralNetworks.HiddenNeuron1L, IG.Neural.NeuralNetworks.HiddenNeuron2L, IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL11D, IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL21D, IG.Neural.NeuralNetworks.InputSafetyFactor, IG.Neural.Forms.NeuralDemo1D.inputSafetyFactor1D, IG.Neural.NeuralNetworks.LearningRate, IG.Neural.Forms.NeuralDemo1D.learningRate1D, IG.Neural.NeuralNetworks.MaxEpoch, IG.Neural.Forms.NeuralDemo1D.maxEpoch1D, IG.Neural.NeuralNetworks.Momentum, IG.Neural.Forms.NeuralDemo1D.momentum1D, IG.Neural.Forms.NeuralDemo1D.network1D, IG.Neural.NeuralNetworks.OutputSafetyFactor, IG.Neural.Forms.NeuralDemo1D.outputSafetyFactor1D, IG.Neural.NeuralNetworks.RMS, IG.Neural.Forms.NeuralDemo1D.rmsError1D, IG.Neural.Forms.NeuralDemo1D.trainingPoints1D, and IG.Neural.Forms.NeuralDemo1D.TrainNetworkThread1D().
btStop1D_Click() [5/5]
void IG.Neural.Forms.NeuralDemo1D.btStop1D_Click (object sender, EventArgs e) inline private
References IG.Neural.NeuralNetworks.BreakTraining, IG.Neural.Forms.NeuralDemo1D.network1D, and IG.Neural.Forms.NeuralDemo1D.stopTraining1D.
TrainNetworkThread1D() [5/5]
void IG.Neural.Forms.NeuralDemo1D.TrainNetworkThread1D () inline private
References IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D.
btnGenerateOptData1D_Click() [5/5]
void IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click (object sender, EventArgs e) inline private
Generate training data button.
References IG.Neural.Forms.NeuralDemo1D.cbRandomData1D, IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph(), IG.Neural.Forms.NeuralDemo1D.ClearDefaultGraph(), IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Neural.Forms.NeuralDemo1D.ClearTrainingGraph(), IG.Neural.Forms.NeuralDemo1D.createFunction1D(), IG.Neural.Forms.NeuralDemo1D.defaultFunctionData1D, IG.Neural.TestFunctions.GenerateFunctionTrainingSamples(), IG.Neural.Forms.NeuralDemo1D.highHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.InitializeApproximator1D(), IG.Neural.Forms.NeuralDemo1D.lowHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.pane1D, IG.Neural.Forms.NeuralDemo1D.PrepareTrainingPoints1D(), IG.Neural.Forms.NeuralDemo1D.tbEquationError1D, IG.Neural.Forms.NeuralDemo1D.trainingData1D, IG.Neural.Forms.NeuralDemo1D.verificationData1D, IG.Neural.Forms.NeuralDemo1D.WriteDefaultFunction1D(), and IG.Neural.Forms.NeuralDemo1D.WriteTrainingPoints1D().
rbMaxTrainError_CheckedChanged() [5/5]
void IG.Neural.Forms.NeuralDemo1D.rbMaxTrainError_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum training error convergence to be written on graph.
References IG.Neural.Forms.NeuralDemo1D.maxTrainErrorEnabled1D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
rbRmsTrainError_CheckedChanged() [5/5]
void IG.Neural.Forms.NeuralDemo1D.rbRmsTrainError_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms training error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Neural.Forms.NeuralDemo1D.rmsTrainErrorEnabled1D, and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
rbMaxVerError_CheckedChanged() [5/5]
void IG.Neural.Forms.NeuralDemo1D.rbMaxVerError_CheckedChanged (object sender, EventArgs e) inline private
Enable Maximum verification error convergence to be written on graph.
References IG.Neural.Forms.NeuralDemo1D.maxVerErrorEnabled1D, IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
rbRmsVerError_CheckedChanged() [5/5]
void IG.Neural.Forms.NeuralDemo1D.rbRmsVerError_CheckedChanged (object sender, EventArgs e) inline private
Enable Rms verification error convergence to be written on graph.
References IG.Num.INeuralApproximator.NetworkTrained, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Neural.Forms.NeuralDemo1D.rmsVerErrorEnabled1D, and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
cbSelfMade1D_CheckedChanged() [5/5]
void IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D_CheckedChanged (object sender, EventArgs e) inline private
Enable posibility to self made the equation.
References IG.Neural.Forms.NeuralDemo1D.cbEquation1D, IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D, IG.Neural.Forms.NeuralDemo1D.ResetAll1D(), and IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D.
cbRandomData1D_CheckedChanged() [5/5]
void IG.Neural.Forms.NeuralDemo1D.cbRandomData1D_CheckedChanged (object sender, EventArgs e) inline private
Enable random training points.
References IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
cbEquation1D_SelectedIndexChanged() [5/5]
void IG.Neural.Forms.NeuralDemo1D.cbEquation1D_SelectedIndexChanged (object sender, EventArgs e) inline private
Select equation from the list.
References IG.Neural.Forms.NeuralDemo1D.cbEquation1D, IG.Neural.Forms.NeuralDemo1D.equation1D, and IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
tbSelfMadeEquation1D_TextChanged() [5/5]
void IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D_TextChanged (object sender, EventArgs e) inline private
Equation string.
References IG.Neural.Forms.NeuralDemo1D.equation1D, and IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D.
numSamples1D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralDemo1D.numSamples1D_ValueChanged (object sender, EventArgs e) inline private
Number of training samples generated.
References IG.Neural.Forms.NeuralDemo1D.numSamples1D, IG.Neural.Forms.NeuralDemo1D.ResetAll1D(), and IG.Neural.Forms.NeuralDemo1D.samples1D.
numLowXLimit1D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D_ValueChanged (object sender, EventArgs e) inline private
Lower limit for x-axes on the graph.
References IG.Neural.Forms.NeuralDemo1D.lowHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D, and IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
numHighXLimit1D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D_ValueChanged (object sender, EventArgs e) inline private
Higher limit for x-axes on the graph.
References IG.Neural.Forms.NeuralDemo1D.highHorizontalLimit1D, IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D, and IG.Neural.Forms.NeuralDemo1D.ResetAll1D().
numMaxEpoch1D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D_ValueChanged (object sender, EventArgs e) inline private
Maximum number of epochs.
References IG.Neural.Forms.NeuralDemo1D.maxEpoch1D, and IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D.
numEpochBundle1D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D_ValueChanged (object sender, EventArgs e) inline private
Number of epochs in bundle.
References IG.Neural.Forms.NeuralDemo1D.epochInBundle1D, and IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D.
numRMS1D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralDemo1D.numRMS1D_ValueChanged (object sender, EventArgs e) inline private
Rms error limit.
References IG.Neural.Forms.NeuralDemo1D.numRMS1D, and IG.Neural.Forms.NeuralDemo1D.rmsError1D.
numLearningRate1D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralDemo1D.numLearningRate1D_ValueChanged (object sender, EventArgs e) inline private
Learning rate.
References IG.Neural.Forms.NeuralDemo1D.learningRate1D, and IG.Neural.Forms.NeuralDemo1D.numLearningRate1D.
numMomentum1D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralDemo1D.numMomentum1D_ValueChanged (object sender, EventArgs e) inline private
Momentum.
References IG.Neural.Forms.NeuralDemo1D.momentum1D, and IG.Neural.Forms.NeuralDemo1D.numMomentum1D.
numHiddenNeuron1D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in first hidden layer.
References IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL11D, and IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D.
numHiddenNeuronL21D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D_ValueChanged (object sender, EventArgs e) inline private
Number of neurons in second hidden layer.
References IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL21D, and IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D.
numInputSafety1D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralDemo1D.numInputSafety1D_ValueChanged (object sender, EventArgs e) inline private
Input safety factor.
References IG.Neural.Forms.NeuralDemo1D.inputSafetyFactor1D, and IG.Neural.Forms.NeuralDemo1D.numInputSafety1D.
numOutputSafety1D_ValueChanged() [5/5]
void IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D_ValueChanged (object sender, EventArgs e) inline private
Output safety factor.
References IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D, and IG.Neural.Forms.NeuralDemo1D.outputSafetyFactor1D.
backgroundWorker1D_DoWork() [5/5]
void IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_DoWork (object sender, DoWorkEventArgs e) inline private
This event handler deals with the results of the background operation.
References IG.Neural.NeuralNetworks.BreakTraining, IG.Neural.Forms.NeuralDemo1D.network1D, IG.Neural.Forms.NeuralDemo1D.NeuralApproximator, IG.Lib.StopWatch1.Start(), IG.Lib.StopWatch1.Stop(), IG.Neural.Forms.NeuralDemo1D.stopTraining1D, IG.Neural.Forms.NeuralDemo1D.trainingData1D, IG.Neural.NeuralNetworks.TrainNetwork(), and IG.Neural.Forms.NeuralDemo1D.verificationData1D.
backgroundWorker1D_RunWorkerCompleted() [5/5]
void IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_RunWorkerCompleted (object sender, RunWorkerCompletedEventArgs e) inline private
This event handler deals with the results of the background operation.
References IG.Neural.Forms.NeuralDemo1D.btLoadANN1D, IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D, IG.Neural.Forms.NeuralDemo1D.btnReset1D, IG.Neural.Forms.NeuralDemo1D.btSaveANN1D, IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.btStop1D, IG.Neural.Forms.NeuralDemo1D.WriteApproxGraf1D(), and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
Dispose() [5/5]
override void IG.Neural.Forms.NeuralDemo1D.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Neural.Forms.NeuralDemo1D.components.
InitializeComponent() [5/5]
void IG.Neural.Forms.NeuralDemo1D.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D, IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_DoWork(), IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_RunWorkerCompleted(), IG.Neural.Forms.NeuralDemo1D.btLoad1D, IG.Neural.Forms.NeuralDemo1D.btLoadANN1D, IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D, IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click(), IG.Neural.Forms.NeuralDemo1D.btnReset1D, IG.Neural.Forms.NeuralDemo1D.btnReset1D_Click(), IG.Neural.Forms.NeuralDemo1D.btSaveANN1D, IG.Neural.Forms.NeuralDemo1D.btStart1D, IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), IG.Neural.Forms.NeuralDemo1D.btStop1D, IG.Neural.Forms.NeuralDemo1D.btStop1D_Click(), IG.Neural.Forms.NeuralDemo1D.cbEquation1D, IG.Neural.Forms.NeuralDemo1D.cbEquation1D_SelectedIndexChanged(), IG.Neural.Forms.NeuralDemo1D.cbRandomData1D, IG.Neural.Forms.NeuralDemo1D.cbRandomData1D_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D, IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.components, IG.Neural.Forms.NeuralDemo1D.errorConvergence1D, IG.Neural.Forms.NeuralDemo1D.functionGraph, IG.Neural.Forms.NeuralDemo1D.groupBox5, IG.Neural.Forms.NeuralDemo1D.groupBox6, IG.Neural.Forms.NeuralDemo1D.groupBox7, IG.Neural.Forms.NeuralDemo1D.groupBox9, IG.Neural.Forms.NeuralDemo1D.label1, IG.Neural.Forms.NeuralDemo1D.label11, IG.Neural.Forms.NeuralDemo1D.label12, IG.Neural.Forms.NeuralDemo1D.label13, IG.Neural.Forms.NeuralDemo1D.label15, IG.Neural.Forms.NeuralDemo1D.label16, IG.Neural.Forms.NeuralDemo1D.label19, IG.Neural.Forms.NeuralDemo1D.label2, IG.Neural.Forms.NeuralDemo1D.label4, IG.Neural.Forms.NeuralDemo1D.label5, IG.Neural.Forms.NeuralDemo1D.label6, IG.Neural.Forms.NeuralDemo1D.label7, IG.Neural.Forms.NeuralDemo1D.label8, IG.Neural.Forms.NeuralDemo1D.label9, IG.Neural.Forms.NeuralDemo1D.LoadForm(), IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D, IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D, IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D, IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D, IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numInputSafety1D, IG.Neural.Forms.NeuralDemo1D.numInputSafety1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numLearningRate1D, IG.Neural.Forms.NeuralDemo1D.numLearningRate1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D, IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D, IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numMomentum1D, IG.Neural.Forms.NeuralDemo1D.numMomentum1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D, IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numRMS1D, IG.Neural.Forms.NeuralDemo1D.numRMS1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.numSamples1D, IG.Neural.Forms.NeuralDemo1D.numSamples1D_ValueChanged(), IG.Neural.Forms.NeuralDemo1D.rbMaxTrainError, IG.Neural.Forms.NeuralDemo1D.rbMaxTrainError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.rbMaxVerError, IG.Neural.Forms.NeuralDemo1D.rbMaxVerError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.rbRmsTrainError, IG.Neural.Forms.NeuralDemo1D.rbRmsTrainError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.rbRmsVerError, IG.Neural.Forms.NeuralDemo1D.rbRmsVerError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.tbEquationError1D, IG.Neural.Forms.NeuralDemo1D.tbMaxTrainError1D, IG.Neural.Forms.NeuralDemo1D.tbMaxVerError1D, IG.Neural.Forms.NeuralDemo1D.tbRmsTrainError1D, IG.Neural.Forms.NeuralDemo1D.tbRmsVerError1D, IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D, and IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D_TextChanged().
Member Data Documentation
_neuralApproximator
INeuralApproximator IG.Neural.Forms.NeuralDemo1D._neuralApproximator protected
enabledColor1D
static readonly Color IG.Neural.Forms.NeuralDemo1D.enabledColor1D = Color.Tomato static private
Referenced by IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), IG.Neural.Forms.NeuralDemo1D.EnableControls1D(), and IG.Neural.Forms.NeuralDemo1D.WriteTrainingPoints1D().
disabledColor1D
static readonly Color IG.Neural.Forms.NeuralDemo1D.disabledColor1D = Color.Goldenrod static private
Referenced by IG.Neural.Forms.NeuralDemo1D.EnableControls1D().
pane1D
GraphPane IG.Neural.Forms.NeuralDemo1D.pane1D private
Main Graph.
Referenced by IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click(), IG.Neural.Forms.NeuralDemo1D.GraphDimensions1D(), and IG.Neural.Forms.NeuralDemo1D.LoadForm().
pane1DError
GraphPane IG.Neural.Forms.NeuralDemo1D.pane1DError private
Error Graph.
Referenced by IG.Neural.Forms.NeuralDemo1D.LoadForm(), and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
hiddenNeuronL11D
int IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL11D = 5 private
Referenced by IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), and IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D_ValueChanged().
hiddenNeuronL21D
int IG.Neural.Forms.NeuralDemo1D.hiddenNeuronL21D = 0 private
Referenced by IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), and IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D_ValueChanged().
maxEpoch1D
int IG.Neural.Forms.NeuralDemo1D.maxEpoch1D = 5000 private
Referenced by IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), and IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D_ValueChanged().
epochInBundle1D
int IG.Neural.Forms.NeuralDemo1D.epochInBundle1D = 500 private
Referenced by IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D_ValueChanged(), and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
rmsError1D
double IG.Neural.Forms.NeuralDemo1D.rmsError1D = 0.001 private
Referenced by IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), and IG.Neural.Forms.NeuralDemo1D.numRMS1D_ValueChanged().
learningRate1D
double IG.Neural.Forms.NeuralDemo1D.learningRate1D = 0.3 private
Referenced by IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), and IG.Neural.Forms.NeuralDemo1D.numLearningRate1D_ValueChanged().
momentum1D
double IG.Neural.Forms.NeuralDemo1D.momentum1D = 0.6 private
Referenced by IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), and IG.Neural.Forms.NeuralDemo1D.numMomentum1D_ValueChanged().
samples1D
int IG.Neural.Forms.NeuralDemo1D.samples1D = 6 private
Referenced by IG.Neural.Forms.NeuralDemo1D.numSamples1D_ValueChanged(), and IG.Neural.Forms.NeuralDemo1D.PrepareTrainingPoints1D().
lowHorizontalLimit1D
double IG.Neural.Forms.NeuralDemo1D.lowHorizontalLimit1D = -5.0 private
Referenced by IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click(), IG.Neural.Forms.NeuralDemo1D.NeuralDemo1D(), and IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D_ValueChanged().
highHorizontalLimit1D
double IG.Neural.Forms.NeuralDemo1D.highHorizontalLimit1D = 5.0 private
Referenced by IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click(), IG.Neural.Forms.NeuralDemo1D.NeuralDemo1D(), and IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D_ValueChanged().
lowVerificationHorizontalLimit1D
double IG.Neural.Forms.NeuralDemo1D.lowVerificationHorizontalLimit1D = -5.0 private
Referenced by IG.Neural.Forms.NeuralDemo1D.PrepareTrainingPoints1D().
highVerificationHorizontalLimit1D
double IG.Neural.Forms.NeuralDemo1D.highVerificationHorizontalLimit1D = 5.0 private
Referenced by IG.Neural.Forms.NeuralDemo1D.PrepareTrainingPoints1D().
inputSafetyFactor1D
double IG.Neural.Forms.NeuralDemo1D.inputSafetyFactor1D = 1.3 private
Referenced by IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), and IG.Neural.Forms.NeuralDemo1D.numInputSafety1D_ValueChanged().
outputSafetyFactor1D
double IG.Neural.Forms.NeuralDemo1D.outputSafetyFactor1D = 1.3 private
Referenced by IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), and IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D_ValueChanged().
thread1D
int IG.Neural.Forms.NeuralDemo1D.thread1D = 0 private
Referenced by IG.Neural.Forms.NeuralDemo1D.WriteApproxGraf1D().
equation1D
string IG.Neural.Forms.NeuralDemo1D.equation1D = "x*x" private
Referenced by IG.Neural.Forms.NeuralDemo1D.cbEquation1D_SelectedIndexChanged(), IG.Neural.Forms.NeuralDemo1D.createFunction1D(), and IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D_TextChanged().
maxTrainErrorEnabled1D
bool IG.Neural.Forms.NeuralDemo1D.maxTrainErrorEnabled1D = true private
Referenced by IG.Neural.Forms.NeuralDemo1D.rbMaxTrainError_CheckedChanged(), and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
rmsTrainErrorEnabled1D
bool IG.Neural.Forms.NeuralDemo1D.rmsTrainErrorEnabled1D = false private
Referenced by IG.Neural.Forms.NeuralDemo1D.rbRmsTrainError_CheckedChanged(), and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
maxVerErrorEnabled1D
bool IG.Neural.Forms.NeuralDemo1D.maxVerErrorEnabled1D = false private
Referenced by IG.Neural.Forms.NeuralDemo1D.rbMaxVerError_CheckedChanged(), and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
rmsVerErrorEnabled1D
bool IG.Neural.Forms.NeuralDemo1D.rmsVerErrorEnabled1D = false private
Referenced by IG.Neural.Forms.NeuralDemo1D.rbRmsVerError_CheckedChanged(), and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
stopTraining1D
bool IG.Neural.Forms.NeuralDemo1D.stopTraining1D = false private
Referenced by IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_DoWork(), and IG.Neural.Forms.NeuralDemo1D.btStop1D_Click().
defaultFunction1D
LineItem IG.Neural.Forms.NeuralDemo1D.defaultFunction1D private
Default Function line.
Referenced by IG.Neural.Forms.NeuralDemo1D.ClearDefaultGraph(), and IG.Neural.Forms.NeuralDemo1D.WriteDefaultFunction1D().
trainingPoints1D
LineItem IG.Neural.Forms.NeuralDemo1D.trainingPoints1D private
Training points line.
Referenced by IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), IG.Neural.Forms.NeuralDemo1D.ClearTrainingGraph(), IG.Neural.Forms.NeuralDemo1D.EnableControls1D(), and IG.Neural.Forms.NeuralDemo1D.WriteTrainingPoints1D().
approximatedLine1D
LineItem IG.Neural.Forms.NeuralDemo1D.approximatedLine1D private
Approximation line.
Referenced by IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph(), and IG.Neural.Forms.NeuralDemo1D.WriteApproxGraf1D().
errorConvergenceFunction1D
LineItem IG.Neural.Forms.NeuralDemo1D.errorConvergenceFunction1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
network1D
NeuralNetworks IG.Neural.Forms.NeuralDemo1D.network1D private
ANN.
Referenced by IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_DoWork(), IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), and IG.Neural.Forms.NeuralDemo1D.btStop1D_Click().
trainingData1D
SampledDataSet IG.Neural.Forms.NeuralDemo1D.trainingData1D = null private
Training data.
Referenced by IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_DoWork(), IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click(), IG.Neural.Forms.NeuralDemo1D.PrepareTrainingPoints1D(), and IG.Neural.Forms.NeuralDemo1D.WriteTrainingPoints1D().
verificationData1D
SampledDataSet IG.Neural.Forms.NeuralDemo1D.verificationData1D = null private
Verification data.
Referenced by IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_DoWork(), and IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click().
defaultFunctionData1D
SampledDataSet IG.Neural.Forms.NeuralDemo1D.defaultFunctionData1D = null private
Function data.
Referenced by IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click(), IG.Neural.Forms.NeuralDemo1D.PrepareTrainingPoints1D(), and IG.Neural.Forms.NeuralDemo1D.WriteDefaultFunction1D().
components
System ComponentModel IContainer IG.Neural.Forms.NeuralDemo1D.components = null private
Required designer variable.
Referenced by IG.Neural.Forms.NeuralDemo1D.Dispose(), and IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
rbRmsTrainError
System Windows Forms RadioButton IG.Neural.Forms.NeuralDemo1D.rbRmsTrainError private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
rbMaxTrainError
System Windows Forms RadioButton IG.Neural.Forms.NeuralDemo1D.rbMaxTrainError private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
rbRmsVerError
System Windows Forms RadioButton IG.Neural.Forms.NeuralDemo1D.rbRmsVerError private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
rbMaxVerError
System Windows Forms RadioButton IG.Neural.Forms.NeuralDemo1D.rbMaxVerError private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
numHiddenNeuronL21D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), and IG.Neural.Forms.NeuralDemo1D.numHiddenNeuronL21D_ValueChanged().
tbEquationError1D
System Windows Forms TextBox IG.Neural.Forms.NeuralDemo1D.tbEquationError1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click(), IG.Neural.Forms.NeuralDemo1D.createFunction1D(), and IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
btLoadANN1D
System Windows Forms Button IG.Neural.Forms.NeuralDemo1D.btLoadANN1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_RunWorkerCompleted(), IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), and IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
btSaveANN1D
System Windows Forms Button IG.Neural.Forms.NeuralDemo1D.btSaveANN1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_RunWorkerCompleted(), IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), and IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
tbRmsTrainError1D
System Windows Forms TextBox IG.Neural.Forms.NeuralDemo1D.tbRmsTrainError1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
label12
System Windows Forms Label IG.Neural.Forms.NeuralDemo1D.label12 private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
label13
System Windows Forms Label IG.Neural.Forms.NeuralDemo1D.label13 private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
tbMaxTrainError1D
System Windows Forms TextBox IG.Neural.Forms.NeuralDemo1D.tbMaxTrainError1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
tbRmsVerError1D
System Windows Forms TextBox IG.Neural.Forms.NeuralDemo1D.tbRmsVerError1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
tbMaxVerError1D
System Windows Forms TextBox IG.Neural.Forms.NeuralDemo1D.tbMaxVerError1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
label2
System Windows Forms Label IG.Neural.Forms.NeuralDemo1D.label2 private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
label1
System Windows Forms Label IG.Neural.Forms.NeuralDemo1D.label1 private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
errorConvergence1D
ZedGraph ZedGraphControl IG.Neural.Forms.NeuralDemo1D.errorConvergence1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.ClearErrorGraph1D(), IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), IG.Neural.Forms.NeuralDemo1D.LoadForm(), and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
btnReset1D
System Windows Forms Button IG.Neural.Forms.NeuralDemo1D.btnReset1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_RunWorkerCompleted(), IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), and IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
btStart1D
System Windows Forms Button IG.Neural.Forms.NeuralDemo1D.btStart1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_RunWorkerCompleted(), IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), IG.Neural.Forms.NeuralDemo1D.ResetAll1D(), and IG.Neural.Forms.NeuralDemo1D.WriteTrainingPoints1D().
numOutputSafety1D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), and IG.Neural.Forms.NeuralDemo1D.numOutputSafety1D_ValueChanged().
label16
System Windows Forms Label IG.Neural.Forms.NeuralDemo1D.label16 private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
numInputSafety1D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralDemo1D.numInputSafety1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), and IG.Neural.Forms.NeuralDemo1D.numInputSafety1D_ValueChanged().
label15
System Windows Forms Label IG.Neural.Forms.NeuralDemo1D.label15 private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
numHiddenNeuron1D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), and IG.Neural.Forms.NeuralDemo1D.numHiddenNeuron1D_ValueChanged().
label11
System Windows Forms Label IG.Neural.Forms.NeuralDemo1D.label11 private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
numMomentum1D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralDemo1D.numMomentum1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), and IG.Neural.Forms.NeuralDemo1D.numMomentum1D_ValueChanged().
numLearningRate1D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralDemo1D.numLearningRate1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), and IG.Neural.Forms.NeuralDemo1D.numLearningRate1D_ValueChanged().
numRMS1D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralDemo1D.numRMS1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), and IG.Neural.Forms.NeuralDemo1D.numRMS1D_ValueChanged().
numEpochBundle1D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), and IG.Neural.Forms.NeuralDemo1D.numEpochBundle1D_ValueChanged().
numMaxEpoch1D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), and IG.Neural.Forms.NeuralDemo1D.numMaxEpoch1D_ValueChanged().
label8
System Windows Forms Label IG.Neural.Forms.NeuralDemo1D.label8 private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
label7
System Windows Forms Label IG.Neural.Forms.NeuralDemo1D.label7 private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
label6
System Windows Forms Label IG.Neural.Forms.NeuralDemo1D.label6 private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
label5
System Windows Forms Label IG.Neural.Forms.NeuralDemo1D.label5 private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
label4
System Windows Forms Label IG.Neural.Forms.NeuralDemo1D.label4 private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
cbRandomData1D
System Windows Forms CheckBox IG.Neural.Forms.NeuralDemo1D.cbRandomData1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D_Click(), and IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
btnGenerateOptData1D
System Windows Forms Button IG.Neural.Forms.NeuralDemo1D.btnGenerateOptData1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_RunWorkerCompleted(), IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), and IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
numHighXLimit1D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), IG.Neural.Forms.NeuralDemo1D.NeuralDemo1D(), and IG.Neural.Forms.NeuralDemo1D.numHighXLimit1D_ValueChanged().
numLowXLimit1D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), IG.Neural.Forms.NeuralDemo1D.NeuralDemo1D(), and IG.Neural.Forms.NeuralDemo1D.numLowXLimit1D_ValueChanged().
numSamples1D
System Windows Forms NumericUpDown IG.Neural.Forms.NeuralDemo1D.numSamples1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), and IG.Neural.Forms.NeuralDemo1D.numSamples1D_ValueChanged().
label9
System Windows Forms Label IG.Neural.Forms.NeuralDemo1D.label9 private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
tbSelfMadeEquation1D
System Windows Forms TextBox IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.createFunction1D(), IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), and IG.Neural.Forms.NeuralDemo1D.tbSelfMadeEquation1D_TextChanged().
cbEquation1D
System Windows Forms ComboBox IG.Neural.Forms.NeuralDemo1D.cbEquation1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.cbEquation1D_SelectedIndexChanged(), IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D_CheckedChanged(), and IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
label19
System Windows Forms Label IG.Neural.Forms.NeuralDemo1D.label19 private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
cbSelfMade1D
System Windows Forms CheckBox IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.cbSelfMade1D_CheckedChanged(), and IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
btLoad1D
System Windows Forms Button IG.Neural.Forms.NeuralDemo1D.btLoad1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
functionGraph
ZedGraph ZedGraphControl IG.Neural.Forms.NeuralDemo1D.functionGraph private
Referenced by IG.Neural.Forms.NeuralDemo1D.ClearApproximationGraph(), IG.Neural.Forms.NeuralDemo1D.ClearDefaultGraph(), IG.Neural.Forms.NeuralDemo1D.ClearTrainingGraph(), IG.Neural.Forms.NeuralDemo1D.EnableControls1D(), IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), IG.Neural.Forms.NeuralDemo1D.LoadForm(), IG.Neural.Forms.NeuralDemo1D.WriteApproxGraf1D(), IG.Neural.Forms.NeuralDemo1D.WriteDefaultFunction1D(), and IG.Neural.Forms.NeuralDemo1D.WriteTrainingPoints1D().
groupBox5
System Windows Forms GroupBox IG.Neural.Forms.NeuralDemo1D.groupBox5 private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
groupBox6
System Windows Forms GroupBox IG.Neural.Forms.NeuralDemo1D.groupBox6 private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
btStop1D
System Windows Forms Button IG.Neural.Forms.NeuralDemo1D.btStop1D private
Referenced by IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_RunWorkerCompleted(), IG.Neural.Forms.NeuralDemo1D.btStart1D_Click(), and IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
groupBox7
System Windows Forms GroupBox IG.Neural.Forms.NeuralDemo1D.groupBox7 private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
groupBox9
System Windows Forms GroupBox IG.Neural.Forms.NeuralDemo1D.groupBox9 private
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent().
backgroundWorker1D
System ComponentModel BackgroundWorker IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D
Referenced by IG.Neural.Forms.NeuralDemo1D.InitializeComponent(), IG.Neural.Forms.NeuralDemo1D.NeuralDemo1D(), and IG.Neural.Forms.NeuralDemo1D.TrainNetworkThread1D().
Property Documentation
NeuralApproximator
INeuralApproximator IG.Neural.Forms.NeuralDemo1D.NeuralApproximator get set
Referenced by IG.Neural.Forms.NeuralDemo1D.backgroundWorker1D_DoWork(), IG.Neural.Forms.NeuralDemo1D.InitializeApproximator1D(), IG.Neural.Applications.NeuralApp1D.InitializeComponent(), IG.Neural.Forms.NeuralDemo1D.PredictFromApproximator(), IG.Neural.Forms.NeuralDemo1D.rbMaxTrainError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.rbMaxVerError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.rbRmsTrainError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.rbRmsVerError_CheckedChanged(), IG.Neural.Forms.NeuralDemo1D.WriteApproxGraf1D(), and IG.Neural.Forms.NeuralDemo1D.WriteErrors1D().
The documentation for this class was generated from the following files:
shelldev/lib/extended/LibNeuralExtForms/FormsExperimental/NeuralForms/NeuralControl1D.cs
shelldev/lib/extended/LibNeuralExtForms/FormsExperimental/NeuralForms/NeuralControl1D.Designer.cs