Doc: IGLib EXTENDED: IG.Lib.MsgObervationOrder Class Reference
IG.Lib.MsgObervationOrder Class Reference
Class for holding and manipulating the data about observation order. Includes parsing an XML file, storing data internally, and transcription of read data to a PADO object that enables saving data to a database.
Public Member Functions
MsgObervationOrder ()
Default constructor, sets the type information.
override void Read ()
Reads msg data from the internal XML document containing the msg.
override void Read (XmlParser data)
Read msg data from an XML document containing the msg.
override void CheckConsistency (AccummulatedReport rep)
Check correctness and consistency of data and creates a report on this.
string GetBisOrderId ()
Returns BIS Order Id for this msg.
override string ToString ()
override XmlDocument ToXml ()
Converts a msg to Xml and returns it.
Public Member Functions inherited from IG.Lib.MsgBase
void SetSenderLabex ()
Sets msg data such that sender is Labex and receiver is Bis.
void SetSenderBis ()
Sets msg data such that sender is Bis and receiver is Labex.
Public Member Functions inherited from IG.Lib.ParsableXmlObject
virtual void Save (string filename)
Saves contents of the msg to an xml file.
virtual void CreateXml ()
Creates msg Xml from the current msg data and stores it in this object.
virtual void Load (string filename)
Loads msg data from a file containing the XML msg.
virtual void LoadXml (string doc)
Loads msg data from a string containing the XML msg.
virtual void LoadXml (XmlDocument doc)
Loads msg data from an XmlDocument containing XML msg.
virtual void WriteToConsole ()
Writes cntents of the msg in a human readable form to the system console.
virtual void Write (string filename, bool append)
Writes cntents of the msg in a human readable form to a file.
Static Public Member Functions
static void PrepareOoNullify (ref string message, string comment)
Prepares the observation order message to be sent to the Calypso web service as response to another observation order message, for the case where message is specified a string. Sender, receiver and responder are re-set consistently such that Labex becomes sender of the message, action is set to Nullify and comment is set in addition.
static void PrepareOoNullify (ref XmlDocument msg, string comment)
Prepares the observation order message to be sent to the Calypso web service as response to another observation order message, for the case where message is specified a string. Sender, receiver and responder are re-set consistently such that Labex becomes sender of the message, action is set to Nullify and comment is set in addition.
static void PrepareOoNullify (ref XmlDocument msg, string comment, out bool changed)
Prepares the observation order message to be sent to the Calypso web service as response to another observation order message, for the case where message is specified a string. Sender, receiver and responder are re-set consistently such that Labex becomes sender of the message, action is set to Nullify and comment is set in addition.
static void PrepareOoNullify (ref XmlBuilder data, string comment)
Prepares the observation order message to be sent to the Calypso web service as nullify request for another observation order message. Sender, receiver and responder are re-set consistently such that Labex becomes sender of the message, action is set to Nullify and comment is set in addition.
static void PrepareOoNullify (ref XmlBuilder data, string comment, out bool changed)
Prepares the observation order message to be sent to the Calypso web service as nullify request for another observation order message. Sender, receiver and responder are re-set consistently such that Labex becomes sender of the message, action is set to Nullify and comment is set in addition.
static void PrepareOoResponse (ref string message, OoAction action, string comment, string sender, string receiver, string responder, out bool changed)
Prepares the observation order message to be sent to the Calypso web service as response to another observation order message. Contents of the message is modified according to parameters.
static void PrepareOoResponse (ref XmlDocument msg, OoAction action, string comment, string sender, string receiver, string responder, out bool changed)
Prepares the observation order message to be sent to the Calypso web service as response to another observation order message. Contents of the message is modified according to parameters.
static void PrepareOoResponse (ref XmlBuilder data, OoAction action, string comment, string sender, string receiver, string responder, out bool changed)
Prepares the observation order message to be sent to the Calypso web service as response to another observation order message. Contents of the message is modified according to parameters.
static void SetOoComment (ref XmlBuilder data, string comment, out bool changed)
Sets the comment in the the Xml document containing the SpecimenObservationOrter message (this is contained in the "text" element of the message body)
static void SetOoAction (ref string message, OoAction action, out bool changed)
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetOoAction (ref XmlDocument msg, OoAction action, out bool changed)
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetOoAction (ref XmlBuilder data, OoAction action, out bool changed)
Sets the action code of the Xml document containing the SpecimenObservationOrter message. Action code is set consistently in such a way that both dependent elements are set (also the "message code").
Static Public Member Functions inherited from IG.Lib.MsgBase
static void SetMessageReceiverOld (ref XmlDocument msg, string receiver, out bool changed)
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false. WARNING: searching for receiver element is done through an XPath expression, which may fail due to default namespaces that were not detected.
static void SetMessageReceiver (ref string message, string receiver, out bool changed)
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetMessageReceiver (ref XmlDocument msg, string receiver, out bool changed)
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetMessageReceiver (ref XmlBuilder data, string receiver, out bool changed)
Sets the receiver of the communication msg stored in an Xml builder to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetMessageSender (ref XmlBuilder data, string sender, out bool changed)
Sets the sender of the communication msg stored in an Xml builder to the specified sender, and indicates through an output argument whether the sender has been changed in msg. If the Sender stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static void SetMessageResponder (ref XmlBuilder data, string responder, out bool changed)
Sets the responder of the communication msg stored in an Xml builder to the specified responder, and indicates through an output argument whether the responder has been changed in msg. If the responder stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
static MessageType GetMessageType (string msgstring)
Infers the msg type from the XML string containing the msg, and returns it.
static MessageType GetMessageType (XmlDocument msg)
Infers the msg type from the XML document containing the msg, and returns it.
static MessageType GetMessageType (XmlParser data)
Infers the msg type from the XML parser containing the msg, and returns it.
Public Attributes
List< Observation > Observations = new List<Observation>()
List< Sample > Samples = new List<Sample>()
List< Patient > Patients = new List<Patient>()
List< Author > Authors = new List<Author>()
List< DiagnosisText > DiagnosisTexts = new List<DiagnosisText>()
List< DiagnosisCodeClass > DiagnosisCodes = new List<DiagnosisCodeClass>()
AutopsyDeathReason AutopsyDeathReason = null
Obduction declaration data:
AutopsyBasicDisease AutopsyBasicDisease = null
AutopsyAssociatedDisease AutopsyAssociatedDisease = null
AutopsyOtherInformation AutopsyOtherInformation = null
Public Attributes inherited from IG.Lib.MsgBase
MessageType Type = MessageType.Unknown
Message type. Helps with general methods that operate on any datatype of msg.
string MessageId = null
Message ID, obtained form the web service.
string MessageFile = null
Specifies the file where message has been backed up. Warning: this file may be deleted at any time!
string MessageNumber = null
Public Attributes inherited from IG.Lib.ParsableXmlObject
string XmlString = null
Properties
int NumSamples [get]
Gets number of samples.
bool PatientIsAlive [get]
Indicates whether patient is alive.
Properties inherited from IG.Lib.MsgBase
static MsgConst Const [get]
Gets objects that contains all constants related to communication messages.
string MessageXml [get, set]
Complete msg as obtained from the web service.
Properties inherited from IG.Lib.ParsableXmlObject
virtual IReporter R [get]
Reporter for this class.
XmlDocument Doc [get]
Returns the XML document representing the msg.
Private Attributes
OoAction Action = OoAction.Unknown
string ActionRoot = null
string ActionCode = null
DateTime? CreationTime = null
DateTime? Ordertime = null
string MessageCode = null
string MessageCodeSystem = null
string BisOrderId = null
string BisOrderIdOid = null
string ObservationType = null
string RsrTypeCodeSystem = null
string OrderStatus = null
string OrderComment = null
string Priority = null
string PriorityCodeSystem = null
Additional Inherited Members
Protected Attributes inherited from IG.Lib.ParsableXmlObject
XmlBuilder Data = new XmlBuilder()
Static Protected Attributes inherited from IG.Lib.MsgBase
static string LabexIdLowercase = null
Detailed Description
Class for holding and manipulating the data about observation order. Includes parsing an XML file, storing data internally, and transcription of read data to a PADO object that enables saving data to a database.
Constructor & Destructor Documentation
MsgObervationOrder()
IG.Lib.MsgObervationOrder.MsgObervationOrder () inline
Default constructor, sets the type information.
References IG.Lib.MsgBase.Type.
Member Function Documentation
Read() [1/2]
override void IG.Lib.MsgObervationOrder.Read () inline virtual
Reads msg data from the internal XML document containing the msg.
Implements IG.Lib.ParsableXmlObject.
References IG.Lib.ParsableXmlObject.Data.
Referenced by IGTest.ProgramIGTest.TestCalypsoWs(), IGTest.ProgramIGTest.TestMsgObservationOrder(), and IGTest.ProgramIGTest.TestMsgObservationOrderNullify().
Read() [2/2]
override void IG.Lib.MsgObervationOrder.Read (XmlParser data) inline virtual
Read msg data from an XML document containing the msg.
Parameters
doc Document containing the msg.
Implements IG.Lib.ParsableXmlObject.
References IG.Lib.MsgConstObservationOrder.ActionAttribute, IG.Lib.MsgObervationOrder.ActionCode, IG.Lib.MsgConstObservationOrder.ActionElement, IG.Lib.MsgConstObservationOrder.ActionOidAttribute, IG.Lib.MsgObervationOrder.ActionRoot, IG.Lib.XmlParser.Attribute(), IG.Lib.MedicalData.AttributeValue, IG.Lib.MsgObervationOrder.Authors, IG.Lib.MedicalData.AutopsyAssociatedDisease, IG.Lib.MedicalData.AutopsyBasicDisease, IG.Lib.MedicalData.AutopsyDeathReason, IG.Lib.MedicalData.AutopsyOtherInformation, IG.Lib.XmlParser.Back(), IG.Lib.XmlParser.BackToMark(), IG.Lib.Patient.BirthDate, IG.Lib.Patient.BirthDateStr, IG.Lib.Patient.Birthplace, IG.Lib.Sample.BisId, IG.Lib.Patient.BisId, IG.Lib.Author.BisId, IG.Lib.Sample.BisIdOid, IG.Lib.Patient.BisIdOid, IG.Lib.Author.BisIdOid, IG.Lib.Author.BisIdOrganization, IG.Lib.Author.BisIdOrganizationOid, IG.Lib.MsgObervationOrder.BisOrderId, IG.Lib.MsgObervationOrder.BisOrderIdOid, IG.Lib.MsgObervationOrder.CheckConsistency(), IG.Lib.Patient.City, IG.Lib.Author.City, IG.Lib.MedicalData.Code, IG.Lib.MsgConstCommon.CodeAttribute, IG.Lib.MsgConstCommon.CodeDescriptionAttribute, IG.Lib.MsgConstCommon.CodeElement, IG.Lib.MedicalData.CodeSystem, IG.Lib.MsgConstCommon.CodeSystemAttribute, IG.Lib.MsgBase.Const, IG.Lib.MsgConst.ConvertActionPriority(), IG.Lib.MsgConst.ConvertOoAction(), IG.Lib.MsgConst.ConvertOoStatus(), IG.Lib.MsgConst.ConvertTime(), IG.Lib.Patient.CountryCode, IG.Lib.Author.CountryCode, IG.Lib.Sample.CreationTime, IG.Lib.MsgObervationOrder.CreationTime, IG.Lib.MsgConstObservationOrder.CreationTimeAttribute, IG.Lib.MsgConstObservationOrder.CreationTimeElement, IG.Lib.Sample.CreationTimeString, IG.Lib.XmlParser.Current, IG.Lib.ParsableXmlObject.Data, IG.Lib.MedicalData.DataKind, IG.Lib.MedicalData.DataType, IG.Lib.IReporterBase.Depth, IG.Lib.MsgObervationOrder.DiagnosisCodes, IG.Lib.MedicalData.DiagnosisText, IG.Lib.MsgObervationOrder.DiagnosisTexts, IG.Lib.MedicalData.DiagonsisCode, IG.Lib.XmlParser.Doc, IG.Lib.MedicalData.ElementValue, IG.Lib.Sample.FixativeCode, IG.Lib.Sample.FixativeCodeDescription, IG.Lib.Sample.FixativeCodeSystem, IG.Lib.XmlParser.GoToMark(), IG.Lib.XmlParser.GoToRoot(), IG.Lib.Patient.HealthSecurityId, IG.Lib.MsgConstCommon.IdElement, IG.Lib.MsgConstCommon.IdIdAttribute, IG.Lib.MsgConstCommon.IdOidAttribute, IG.Lib.Patient.IsAlive, IG.Lib.MedicalData.IsAutopsyAssociatedDisease, IG.Lib.MedicalData.IsAutopsyBasicDisease, IG.Lib.MedicalData.IsAutopsyDeathReason, IG.Lib.MedicalData.IsAutopsyOtherInformation, IG.Lib.MedicalData.IsDiagnosisCode, IG.Lib.MedicalData.IsDiagnosisText, IG.Lib.Patient.IsMale, IG.Lib.MsgConstCommon.LeftSideCode, IG.Lib.MsgObervationOrder.MessageCode, IG.Lib.MsgObervationOrder.MessageCodeSystem, IG.Lib.MsgBase.MessageNumber, IG.Lib.MsgBase.MessageNumberOid, IG.Lib.MsgBase.MessageReceiver, IG.Lib.MsgBase.MessageReceiverOid, IG.Lib.MsgBase.MessageResponder, IG.Lib.MsgBase.MessageResponderOid, IG.Lib.MsgBase.MessageSender, IG.Lib.MsgBase.MessageSenderOid, IG.Lib.MsgConstCommon.MessageSubContainer, IG.Lib.MsgConstCommon.MessageSubContainerTypeAttribute, IG.Lib.MsgConstCommon.MessageSubContainerTypeAttributeValue, IG.Lib.MsgConstCommon.MessageTypeAttribute, IG.Lib.Patient.Name, IG.Lib.Author.Name, IG.Lib.XmlParser.Name, IG.Lib.XmlParser.NextElement(), IG.Lib.XmlParser.NextOrCurrentElement(), IG.Lib.Sample.NumPieces, IG.Lib.MsgConstObservationOrder.OoActionPriorityCodeAttribute, IG.Lib.MsgConstObservationOrder.OoActionPriorityCodeSystemAttribute, IG.Lib.MsgConstObservationOrder.OoActionPriorityElement, IG.Lib.MsgConstObservationOrder.OoAddressContainter, IG.Lib.MsgConstObservationOrder.OoAuthorContainer, IG.Lib.MsgConstObservationOrder.OoAuthorDataContainer, IG.Lib.MsgConstObservationOrder.OoAuthorDataSubcontainer, IG.Lib.MsgConstObservationOrder.OoAuthorNameContainer, IG.Lib.MsgConstObservationOrder.OoAuthorNameElement, IG.Lib.MsgConstObservationOrder.OoAuthorOrgContainer, IG.Lib.MsgConstObservationOrder.OoAuthorOrgNameElement, IG.Lib.MsgConstObservationOrder.OoAuthorPrefixElement, IG.Lib.MsgConstObservationOrder.OoAuthorSubcontainer, IG.Lib.MsgConstObservationOrder.OoAuthorSuffixElement, IG.Lib.MsgConstObservationOrder.OoAuthorSurnameElement, IG.Lib.MsgConstObservationOrder.OoCityElement, IG.Lib.MsgConstObservationOrder.OoCommentElement, IG.Lib.MsgConstObservationOrder.OoCountryCodeElement, IG.Lib.MsgConstCommon.OoGenderFemale, IG.Lib.MsgConstCommon.OoGenderMale, IG.Lib.MsgConstObservationOrder.OoMedicalDataCodeAttribute, IG.Lib.MsgConstObservationOrder.OoMedicalDataCodeSystemAttribute, IG.Lib.MsgConstObservationOrder.OoMedicalDataContainer, IG.Lib.MsgConstObservationOrder.OoMedicalDataElement, IG.Lib.MsgConstObservationOrder.OoMedicalDataKindAttribute, IG.Lib.MsgConstObservationOrder.OoMedicalDataKindElement, IG.Lib.MsgConstObservationOrder.OoMedicalDataSubContainer, IG.Lib.MsgConstObservationOrder.OoMedicalDataTypeAttribute, IG.Lib.MsgConstObservationOrder.OoMedicalDataValueAttribute, IG.Lib.MsgConstCommon.OoMessageContainer, IG.Lib.MsgConstCommon.OoMessageSubContainer2, IG.Lib.MsgConstObservationOrder.OoMessageType, IG.Lib.MsgConstObservationOrder.OoOrderStatusAttribute, IG.Lib.MsgConstObservationOrder.OoOrderStatusElement, IG.Lib.MsgConstObservationOrder.OoOrderTimeAttribute, IG.Lib.MsgConstObservationOrder.OoOrderTimeElement, IG.Lib.MsgConstObservationOrder.OoPatientBirthDateElement, IG.Lib.MsgConstObservationOrder.OoPatientBirthPlaceContainer, IG.Lib.MsgConstObservationOrder.OoPatientBirthPlaceElement, IG.Lib.MsgConstObservationOrder.OoPatientBirthPlaceSubcontainer, IG.Lib.MsgConstObservationOrder.OoPatientContainer, IG.Lib.MsgConstObservationOrder.OoPatientDataContainer, IG.Lib.MsgConstObservationOrder.OoPatientDeceasedElement, IG.Lib.MsgConstObservationOrder.OoPatientGenderAttribute, IG.Lib.MsgConstObservationOrder.OoPatientGenderElement, IG.Lib.MsgConstObservationOrder.OoPatientHealthInsuranceContainer, IG.Lib.MsgConstObservationOrder.OoPatientNameContainer, IG.Lib.MsgConstObservationOrder.OoPatientNameElement, IG.Lib.MsgConstObservationOrder.OoPatientSubContainer, IG.Lib.MsgConstObservationOrder.OoPatientSurnameElement, IG.Lib.MsgConstObservationOrder.OoPatientTimeOfDeathElement, IG.Lib.MsgConstObservationOrder.OoPostalCodeElement, IG.Lib.MsgConstCommon.OoRootName, IG.Lib.MsgConstObservationOrder.OoSampleContainer, IG.Lib.MsgConstObservationOrder.OoSampleDataContainer, IG.Lib.MsgConstObservationOrder.OoSampleDataSubContainer, IG.Lib.MsgConstObservationOrder.OoSampleFixativeElement, IG.Lib.MsgConstObservationOrder.OoSampleNumPiecesAttribute, IG.Lib.MsgConstObservationOrder.OoSampleNumPiecesContainer, IG.Lib.MsgConstObservationOrder.OoSampleNumPiecesElement, IG.Lib.MsgConstObservationOrder.OoSampleNumPiecesSubContainer, IG.Lib.MsgConstObservationOrder.OoSampleOrganElement, IG.Lib.MsgConstObservationOrder.OoSampleSideElement, IG.Lib.MsgConstObservationOrder.OoSampleStatuscodeElement, IG.Lib.MsgConstObservationOrder.OoSampleSubContainer, IG.Lib.MsgConstObservationOrder.OoSampleTimeElement, IG.Lib.MsgConstObservationOrder.OoStreetAddressElement, IG.Lib.MsgObervationOrder.OrderComment, IG.Lib.MsgObervationOrder.OrderStatus, IG.Lib.MsgObervationOrder.Ordertime, IG.Lib.Sample.OrganCode, IG.Lib.Sample.OrganCodeDescription, IG.Lib.Sample.OrganCodeSystem, IG.Lib.Author.OrganizationName, IG.Lib.MsgObervationOrder.Patients, IG.Lib.Patient.PostalCode, IG.Lib.Author.PostalCode, IG.Lib.Author.Prefix, IG.Lib.MsgObervationOrder.Priority, IG.Lib.MsgObervationOrder.PriorityCodeSystem, IG.Lib.ParsableXmlObject.R, IG.Lib.MsgConstCommon.ReceiverContainer, IG.Lib.MsgConstCommon.ReceiverSubContainer, IG.Lib.XmlParser.RemoveMark(), IG.Lib.XmlParser.RemoveMarks(), IG.Lib.ParsableXmlObject.AccummulatedReport.Report(), IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.MsgConstCommon.ResponderContainer, IG.Lib.MsgConstCommon.ResponderSubContainer, IG.Lib.ReporterBase.ReviseException(), IG.Lib.Sample.RightSide, IG.Lib.MsgConstCommon.RightsideCode, IG.Lib.MsgObervationOrder.RsrTypeCodeSystem, IG.Lib.Sample.SampleBarcode, IG.Lib.Sample.SampleBarcodeSystem, IG.Lib.Sample.SampleCode, IG.Lib.Sample.SampleCodeDescription, IG.Lib.Sample.SampleCodeSystem, IG.Lib.MsgObervationOrder.Samples, IG.Lib.MsgConstCommon.SenderContainer, IG.Lib.MsgConstCommon.SenderSubContainer, IG.Lib.XmlParser.SetMark(), IG.Lib.Sample.SideCode, IG.Lib.Sample.SideCodeDescription, IG.Lib.Sample.SideCodeSystem, IG.Lib.XmlParser.StepIn(), IG.Lib.XmlParser.StepOut(), IG.Lib.Patient.StreetAddress, IG.Lib.Author.StreetAddress, IG.Lib.Author.Suffix, IG.Lib.Patient.Surname, IG.Lib.Author.Surname, IG.Lib.Patient.TimeOfDeath, IG.Lib.Patient.TimeOfDeathStr, IG.Lib.MsgObervationOrder.ToString(), IG.Lib.IReporterBase.TreatInfo, IG.Lib.XmlParser.Value, and IG.Lib.MsgConstCommon.ValueAttribute.
CheckConsistency()
override void IG.Lib.MsgObervationOrder.CheckConsistency (AccummulatedReport rep) inline virtual
Check correctness and consistency of data and creates a report on this.
Parameters
rep Object where error, warning and info reports are accumulated.
Reimplemented from IG.Lib.ParsableXmlObject.
References IG.Lib.ParsableXmlObject.AccummulatedReport.AddError(), IG.Lib.ParsableXmlObject.AccummulatedReport.AddWarning(), IG.Lib.MsgObervationOrder.Authors, IG.Lib.Sample.BisId, IG.Lib.Patient.BisId, IG.Lib.Author.BisId, IG.Lib.Author.BisIdOrganization, IG.Lib.MsgObervationOrder.BisOrderId, IG.Lib.Author.City, IG.Lib.MsgBase.Const, IG.Lib.MsgConst.ConvertActionPriority(), IG.Lib.Author.CountryCode, IG.Lib.MsgObervationOrder.DiagnosisTexts, IG.Lib.Patient.IsAlive, IG.Lib.Patient.IsMale, IG.Lib.MsgConstCommon.MissingDataString, IG.Lib.Patient.Name, IG.Lib.Author.Name, IG.Lib.Sample.NumPieces, IG.Lib.MsgObervationOrder.NumSamples, IG.Lib.MsgConstCommon.ObservationTypeCitology, IG.Lib.MsgConstCommon.ObservationTypeHistology, IG.Lib.MsgConstCommon.ObservationTypePatology, IG.Lib.MsgConstObservationOrder.OoCheckAliveConsistency, IG.Lib.MsgObervationOrder.Ordertime, IG.Lib.MsgObervationOrder.PatientIsAlive, IG.Lib.MsgObervationOrder.Patients, IG.Lib.Author.PostalCode, IG.Lib.MsgObervationOrder.Priority, IG.Lib.Sample.SampleCode, IG.Lib.MsgObervationOrder.Samples, IG.Lib.Author.StreetAddress, IG.Lib.Patient.Surname, IG.Lib.Author.Surname, IG.Lib.DiagnosisText.Text, IG.Lib.AutopsyBase.Text, IG.Lib.Patient.TimeOfDeath, IG.Lib.Patient.TimeOfDeathStr, IG.Lib.MsgObervationOrder.ToString(), and IG.Lib.MsgBase.Type.
Referenced by IG.Lib.MsgObervationOrder.Read().
GetBisOrderId()
string IG.Lib.MsgObervationOrder.GetBisOrderId () inline
Returns BIS Order Id for this msg.
References IG.Lib.MsgObervationOrder.BisOrderId.
Referenced by IGTest.ProgramIGTest.ReceiveSpecimenObservationOrder().
ToString()
override string IG.Lib.MsgObervationOrder.ToString () inline
References IG.Lib.MsgObervationOrder.ActionCode, IG.Lib.MsgObervationOrder.ActionRoot, IG.Lib.MsgObervationOrder.Authors, IG.Lib.MsgObervationOrder.BisOrderId, IG.Lib.MsgBase.Const, IG.Lib.MsgConst.ConvertOoAction(), IG.Lib.MsgObervationOrder.CreationTime, IG.Lib.IReporterBase.Depth, IG.Lib.MsgObervationOrder.DiagnosisCodes, IG.Lib.MsgObervationOrder.DiagnosisTexts, IG.Lib.MsgObervationOrder.MessageCode, IG.Lib.MsgBase.MessageFile, IG.Lib.MsgBase.MessageId, IG.Lib.MsgBase.MessageNumber, IG.Lib.MsgBase.MessageNumberOid, IG.Lib.MsgBase.MessageReceiver, IG.Lib.MsgBase.MessageReceiverOid, IG.Lib.MsgBase.MessageResponder, IG.Lib.MsgBase.MessageResponderOid, IG.Lib.MsgBase.MessageSender, IG.Lib.MsgBase.MessageSenderOid, IG.Lib.MsgBase.MessageXml, IG.Lib.MsgObervationOrder.Observations, IG.Lib.MsgObervationOrder.OrderComment, IG.Lib.MsgObervationOrder.OrderStatus, IG.Lib.MsgObervationOrder.Ordertime, IG.Lib.MsgObervationOrder.PatientIsAlive, IG.Lib.MsgObervationOrder.Patients, IG.Lib.MsgObervationOrder.Priority, IG.Lib.MsgObervationOrder.PriorityCodeSystem, IG.Lib.ParsableXmlObject.R, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), IG.Lib.MsgObervationOrder.RsrTypeCodeSystem, IG.Lib.MsgObervationOrder.Samples, IG.Lib.AutopsyBase.ToString(), IG.Lib.IReporterBase.TreatInfo, and IG.Lib.MsgBase.Type.
Referenced by IG.Lib.MsgObervationOrder.CheckConsistency(), and IG.Lib.MsgObervationOrder.Read().
ToXml()
override XmlDocument IG.Lib.MsgObervationOrder.ToXml () inline virtual
Converts a msg to Xml and returns it.
Implements IG.Lib.ParsableXmlObject.
References IG.Lib.ParsableXmlObject.Data, IG.Lib.IReporterBase.Depth, IG.Lib.XmlParser.Doc, IG.Lib.ParsableXmlObject.R, IG.Lib.IReporterBase.ReportError(), IG.Lib.IReporterBase.ReportInfo(), and IG.Lib.IReporterBase.TreatInfo.
PrepareOoNullify() [1/5]
static void IG.Lib.MsgObervationOrder.PrepareOoNullify (ref string message, string comment) inline static
Prepares the observation order message to be sent to the Calypso web service as response to another observation order message, for the case where message is specified a string. Sender, receiver and responder are re-set consistently such that Labex becomes sender of the message, action is set to Nullify and comment is set in addition.
Parameters
message String containing the message.
comment Comment to be set on the message (if null then comment is not set, i.e. eventual current comment is preserved).
Referenced by IG.Lib.MsgObervationOrder.PrepareOoNullify(), LabexBis.Calypso.SendOoNullifyToBis(), and IGTest.ProgramIGTest.TestMsgObservationOrderNullify().
PrepareOoNullify() [2/5]
static void IG.Lib.MsgObervationOrder.PrepareOoNullify (ref XmlDocument msg, string comment) inline static
Prepares the observation order message to be sent to the Calypso web service as response to another observation order message, for the case where message is specified a string. Sender, receiver and responder are re-set consistently such that Labex becomes sender of the message, action is set to Nullify and comment is set in addition.
Parameters
msg XmlDocument containing the message.
comment Comment to be set on the message (if null then comment is not set, i.e. eventual current comment is preserved).
References IG.Lib.XmlUtilityBase.LoadXml(), and IG.Lib.MsgObervationOrder.PrepareOoNullify().
PrepareOoNullify() [3/5]
static void IG.Lib.MsgObervationOrder.PrepareOoNullify (ref XmlDocument msg, string comment, out bool changed) inline static
Prepares the observation order message to be sent to the Calypso web service as response to another observation order message, for the case where message is specified a string. Sender, receiver and responder are re-set consistently such that Labex becomes sender of the message, action is set to Nullify and comment is set in addition.
Parameters
msg XmlDocument containing the message.
comment Comment to be set on the message (if null then comment is not set, i.e. eventual current comment is preserved).
changed Output flag indicating whether message contents has been changed by this function.
References IG.Lib.XmlUtilityBase.LoadXml(), and IG.Lib.MsgObervationOrder.PrepareOoNullify().
PrepareOoNullify() [4/5]
static void IG.Lib.MsgObervationOrder.PrepareOoNullify (ref XmlBuilder data, string comment) inline static
Prepares the observation order message to be sent to the Calypso web service as nullify request for another observation order message. Sender, receiver and responder are re-set consistently such that Labex becomes sender of the message, action is set to Nullify and comment is set in addition.
Parameters
data XmlBuilder containing the message.
comment Comment to be set on the message (if null then comment is not set, i.e. eventual current comment is preserved).
References IG.Lib.MsgConstCommon.BisId, IG.Lib.MsgConst.Const, IG.Lib.MsgConstCommon.LabexId, IG.Lib.MsgBase.MessageReceiver, IG.Lib.MsgBase.MessageResponder, IG.Lib.MsgBase.MessageSender, and IG.Lib.MsgObervationOrder.PrepareOoResponse().
PrepareOoNullify() [5/5]
static void IG.Lib.MsgObervationOrder.PrepareOoNullify (ref XmlBuilder data, string comment, out bool changed) inline static
Prepares the observation order message to be sent to the Calypso web service as nullify request for another observation order message. Sender, receiver and responder are re-set consistently such that Labex becomes sender of the message, action is set to Nullify and comment is set in addition.
Parameters
data XmlBuilder containing the message.
comment Comment to be set on the message (if null then comment is not set, i.e. eventual current comment is preserved).
changed Output flag indicating whether message contents has been changed by this function.
References IG.Lib.MsgConstCommon.BisId, IG.Lib.MsgConst.Const, IG.Lib.MsgConstCommon.LabexId, IG.Lib.MsgBase.MessageReceiver, IG.Lib.MsgBase.MessageResponder, IG.Lib.MsgBase.MessageSender, and IG.Lib.MsgObervationOrder.PrepareOoResponse().
PrepareOoResponse() [1/3]
static void IG.Lib.MsgObervationOrder.PrepareOoResponse (ref string message, OoAction action, string comment, string sender, string receiver, string responder, out bool changed) inline static
Prepares the observation order message to be sent to the Calypso web service as response to another observation order message. Contents of the message is modified according to parameters.
Parameters
message String containing the message.
action Action to be set on the message (if OoAction.Unknown then message is not modified!)
comment Comment to be set on the message (if null then comment is not set, i.e. eventual current comment is preserved).
sender Sender to be set on the message. If null or empty string then sender is not modified on the message.
receiver Receiver to be set on the message. If null or empty string then receiver is not modified on the message.
responder Responder to be set on the message. If null or empty string then responder is not modified on the message.
changed Output flag indicating whether message contents has been changed by this function.
Referenced by IG.Lib.MsgObervationOrder.PrepareOoNullify(), and IG.Lib.MsgObervationOrder.PrepareOoResponse().
PrepareOoResponse() [2/3]
static void IG.Lib.MsgObervationOrder.PrepareOoResponse (ref XmlDocument msg, OoAction action, string comment, string sender, string receiver, string responder, out bool changed) inline static
Prepares the observation order message to be sent to the Calypso web service as response to another observation order message. Contents of the message is modified according to parameters.
Parameters
msg XmlDocument containing the message.
action Action to be set on the message (if OoAction.Unknown then message is not modified!)
comment Comment to be set on the message (if null then comment is not set, i.e. eventual current comment is preserved).
sender Sender to be set on the message. If null or empty string then sender is not modified on the message.
receiver Receiver to be set on the message. If null or empty string then receiver is not modified on the message.
responder Responder to be set on the message. If null or empty string then responder is not modified on the message.
changed Output flag indicating whether message contents has been changed by this function.
References IG.Lib.XmlUtilityBase.LoadXml(), and IG.Lib.MsgObervationOrder.PrepareOoResponse().
PrepareOoResponse() [3/3]
static void IG.Lib.MsgObervationOrder.PrepareOoResponse (ref XmlBuilder data, OoAction action, string comment, string sender, string receiver, string responder, out bool changed) inline static
Prepares the observation order message to be sent to the Calypso web service as response to another observation order message. Contents of the message is modified according to parameters.
Parameters
data XmlBuilder containing the message.
action Action to be set on the message (if OoAction.Unknown then message is not modified!)
comment Comment to be set on the message (if null then comment is not set, i.e. eventual current comment is preserved).
sender Sender to be set on the message. If null or empty string then sender is not modified on the message.
receiver Receiver to be set on the message. If null or empty string then receiver is not modified on the message.
responder Responder to be set on the message. If null or empty string then responder is not modified on the message.
changed Output flag indicating whether message contents has been changed by this function.
References IG.Lib.MsgBase.SetMessageReceiver(), IG.Lib.MsgBase.SetMessageResponder(), IG.Lib.MsgBase.SetMessageSender(), IG.Lib.MsgObervationOrder.SetOoAction(), and IG.Lib.MsgObervationOrder.SetOoComment().
SetOoComment()
static void IG.Lib.MsgObervationOrder.SetOoComment (ref XmlBuilder data, string comment, out bool changed) inline static
Sets the comment in the the Xml document containing the SpecimenObservationOrter message (this is contained in the "text" element of the message body)
Parameters
data XML builder containing the message where comment text is to be set.
comment The new comment to be set on the message.
changed Indicates whether the underlying XML message has been changed (i.e., whether the new comment replaced the old one in the message). Message is not changed only when the new message equals the old one or when an error occurs that prevents setting the message.
References IG.Lib.MsgConstCommon.CodeElement, IG.Lib.MsgBase.Const, IG.Lib.MsgConstCommon.MessageSubContainer, IG.Lib.MsgConstObservationOrder.OoCommentElement, IG.Lib.MsgConstCommon.OoMessageContainer, IG.Lib.MsgConstCommon.OoMessageSubContainer2, IG.Lib.MsgConstObservationOrder.OoOrderStatusElement, and IG.Lib.MsgObervationOrder.OrderComment.
Referenced by IG.Lib.MsgObervationOrder.PrepareOoResponse().
SetOoAction() [1/3]
static void IG.Lib.MsgObervationOrder.SetOoAction (ref string message, OoAction action, out bool changed) inline static
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
Parameters
msg Message document in which receiver should be set.
receiver The new receiver of the msg.
changed Indicates whether the msg has been changed (i.e., whether the new receiver has been written to the msg).
Referenced by IG.Lib.MsgObervationOrder.PrepareOoResponse(), and IG.Lib.MsgObervationOrder.SetOoAction().
SetOoAction() [2/3]
static void IG.Lib.MsgObervationOrder.SetOoAction (ref XmlDocument msg, OoAction action, out bool changed) inline static
Sets the receiver of the communication msg stored in msg to the specified receiver, and indicates through an output argument whether the receiver has been changed in msg. If the receiver stated in the msg already equals to the specified one then nothing changes in the msg and the output indicator becomes false.
Parameters
msg Message in which receiver should be set.
receiver The new receiver of the msg.
changed Indicates whether the msg has been changed (i.e., whether the new receiver has been written to the msg).
References IG.Lib.XmlUtilityBase.LoadXml(), and IG.Lib.MsgObervationOrder.SetOoAction().
SetOoAction() [3/3]
static void IG.Lib.MsgObervationOrder.SetOoAction (ref XmlBuilder data, OoAction action, out bool changed) inline static
Sets the action code of the Xml document containing the SpecimenObservationOrter message. Action code is set consistently in such a way that both dependent elements are set (also the "message code").
Parameters
data XML builder containing the message where action code is to be set.
action The new action code to be set on the message.
changed Indicates whether the msg has been changed (i.e., whether the new receiver has been written to the msg).
References IG.Lib.MsgConstObservationOrder.ActionAttribute, IG.Lib.MsgObervationOrder.ActionCode, IG.Lib.MsgConstObservationOrder.ActionElement, IG.Lib.MsgConstCommon.CodeAttribute, IG.Lib.MsgConstCommon.CodeElement, IG.Lib.MsgBase.Const, IG.Lib.MsgConst.ConvertOoAction(), IG.Lib.MsgConst.ConvertOoCode(), IG.Lib.MsgObervationOrder.MessageCode, and IG.Lib.MsgConstCommon.OoMessageContainer.
Member Data Documentation
Observations
List<Observation> IG.Lib.MsgObervationOrder.Observations = new List<Observation>()
Referenced by IG.Lib.MsgObervationOrder.ToString().
Samples
List<Sample> IG.Lib.MsgObervationOrder.Samples = new List<Sample>()
Referenced by IG.Lib.MsgObervationOrder.CheckConsistency(), IG.Lib.MsgObervationOrder.Read(), and IG.Lib.MsgObervationOrder.ToString().
Patients
List<Patient> IG.Lib.MsgObervationOrder.Patients = new List<Patient>()
Referenced by IG.Lib.MsgObervationOrder.CheckConsistency(), IG.Lib.MsgObervationOrder.Read(), and IG.Lib.MsgObervationOrder.ToString().
Authors
List<Author> IG.Lib.MsgObervationOrder.Authors = new List<Author>()
Referenced by IG.Lib.MsgObervationOrder.CheckConsistency(), IG.Lib.MsgObervationOrder.Read(), and IG.Lib.MsgObervationOrder.ToString().
DiagnosisTexts
List<DiagnosisText> IG.Lib.MsgObervationOrder.DiagnosisTexts = new List<DiagnosisText>()
Referenced by IG.Lib.MsgObervationOrder.CheckConsistency(), IG.Lib.MsgObervationOrder.Read(), and IG.Lib.MsgObervationOrder.ToString().
DiagnosisCodes
List<DiagnosisCodeClass> IG.Lib.MsgObervationOrder.DiagnosisCodes = new List<DiagnosisCodeClass>()
Referenced by IG.Lib.MsgObervationOrder.Read(), and IG.Lib.MsgObervationOrder.ToString().
AutopsyDeathReason
AutopsyDeathReason IG.Lib.MsgObervationOrder.AutopsyDeathReason = null
Obduction declaration data:
AutopsyBasicDisease
AutopsyBasicDisease IG.Lib.MsgObervationOrder.AutopsyBasicDisease = null
AutopsyAssociatedDisease
AutopsyAssociatedDisease IG.Lib.MsgObervationOrder.AutopsyAssociatedDisease = null
AutopsyOtherInformation
AutopsyOtherInformation IG.Lib.MsgObervationOrder.AutopsyOtherInformation = null
Action
OoAction IG.Lib.MsgObervationOrder.Action = OoAction.Unknown private
ActionRoot
string IG.Lib.MsgObervationOrder.ActionRoot = null private
Referenced by IG.Lib.MsgObervationOrder.Read(), and IG.Lib.MsgObervationOrder.ToString().
ActionCode
string IG.Lib.MsgObervationOrder.ActionCode = null private
Referenced by IG.Lib.MsgObervationOrder.Read(), IG.Lib.MsgObervationOrder.SetOoAction(), and IG.Lib.MsgObervationOrder.ToString().
CreationTime
DateTime? IG.Lib.MsgObervationOrder.CreationTime = null private
Referenced by IG.Lib.MsgObervationOrder.Read(), and IG.Lib.MsgObervationOrder.ToString().
Ordertime
DateTime? IG.Lib.MsgObervationOrder.Ordertime = null private
Referenced by IG.Lib.MsgObervationOrder.CheckConsistency(), IG.Lib.MsgObervationOrder.Read(), and IG.Lib.MsgObervationOrder.ToString().
MessageCode
string IG.Lib.MsgObervationOrder.MessageCode = null private
Referenced by IG.Lib.MsgObervationOrder.Read(), IG.Lib.MsgObervationOrder.SetOoAction(), and IG.Lib.MsgObervationOrder.ToString().
MessageCodeSystem
string IG.Lib.MsgObervationOrder.MessageCodeSystem = null private
Referenced by IG.Lib.MsgObervationOrder.Read().
BisOrderId
string IG.Lib.MsgObervationOrder.BisOrderId = null private
Referenced by IG.Lib.MsgObervationOrder.CheckConsistency(), IG.Lib.MsgObervationOrder.GetBisOrderId(), IG.Lib.MsgObervationOrder.Read(), and IG.Lib.MsgObervationOrder.ToString().
BisOrderIdOid
string IG.Lib.MsgObervationOrder.BisOrderIdOid = null private
Referenced by IG.Lib.MsgObervationOrder.Read().
ObservationType
string IG.Lib.MsgObervationOrder.ObservationType = null private
RsrTypeCodeSystem
string IG.Lib.MsgObervationOrder.RsrTypeCodeSystem = null private
Referenced by IG.Lib.MsgObervationOrder.Read(), and IG.Lib.MsgObervationOrder.ToString().
OrderStatus
string IG.Lib.MsgObervationOrder.OrderStatus = null private
Referenced by IG.Lib.MsgObervationOrder.Read(), and IG.Lib.MsgObervationOrder.ToString().
OrderComment
string IG.Lib.MsgObervationOrder.OrderComment = null private
Referenced by IG.Lib.MsgObervationOrder.Read(), IG.Lib.MsgObervationOrder.SetOoComment(), and IG.Lib.MsgObervationOrder.ToString().
Priority
string IG.Lib.MsgObervationOrder.Priority = null private
Referenced by IG.Lib.MsgObervationOrder.CheckConsistency(), IG.Lib.MsgObervationOrder.Read(), and IG.Lib.MsgObervationOrder.ToString().
PriorityCodeSystem
string IG.Lib.MsgObervationOrder.PriorityCodeSystem = null private
Referenced by IG.Lib.MsgObervationOrder.Read(), and IG.Lib.MsgObervationOrder.ToString().
Property Documentation
NumSamples
int IG.Lib.MsgObervationOrder.NumSamples get
Gets number of samples.
Referenced by IG.Lib.MsgObervationOrder.CheckConsistency().
PatientIsAlive
bool IG.Lib.MsgObervationOrder.PatientIsAlive get
Indicates whether patient is alive.
Referenced by IG.Lib.MsgObervationOrder.CheckConsistency(), and IG.Lib.MsgObervationOrder.ToString().
The documentation for this class was generated from the following file:
igtest/tmp_prem/prlab/LabexBis/MsgObservationOrder.cs