Doc: IGLib EXTENDED: NUnit.Framework.Internal.Execution.WorkItem Class Reference
NUnit.Framework.Internal.Execution.WorkItem Class Reference abstract
A WorkItem may be an individual test case, a fixture or a higher level grouping of tests. All WorkItems inherit from the abstract WorkItem class, which uses the template pattern to allow derived classes to perform work in whatever way is needed.
Public Member Functions
WorkItem (Test test)
Construct a WorkItem for a particular test.
void InitializeContext (TestExecutionContext context)
Initialize the TestExecutionContext. This must be done before executing the WorkItem.
virtual void Execute ()
Execute the current work item, including any child work items.
Static Public Member Functions
static WorkItem CreateWorkItem (ITest test, ITestFilter filter)
Creates a work item.
Protected Member Functions
abstract void PerformWork ()
Method that performs actually performs the work. It should set the State to WorkItemState.Complete when done.
void WorkItemComplete ()
Method called by the derived class when all work is complete
Properties
WorkItemState State [get]
Gets the current state of the WorkItem
Test Test [get]
The test being executed by the work item
TestExecutionContext Context [get]
The execution context
List< ITestAction > Actions [get]
The test actions to be performed before and after this test
TestResult Result [get, protected set]
The test result
Events
EventHandler Completed
Event triggered when the item is complete
Private Member Functions
void RunTestOnOwnThread (int timeout, ApartmentState apartment)
void RunTest ()
Private Attributes
WorkItemState _state
Test _test
TestExecutionContext _context
List< ITestAction > _actions = new List<ITestAction>()
Static Private Attributes
static Logger log = InternalTrace.GetLogger("WorkItem")
Detailed Description
A WorkItem may be an individual test case, a fixture or a higher level grouping of tests. All WorkItems inherit from the abstract WorkItem class, which uses the template pattern to allow derived classes to perform work in whatever way is needed.
A WorkItem is created with a particular TestExecutionContext and is responsible for re-establishing that context in the current thread before it begins or resumes execution.
Constructor & Destructor Documentation
WorkItem()
NUnit.Framework.Internal.Execution.WorkItem.WorkItem (Test test) inline
Construct a WorkItem for a particular test.
Parameters
test The test that the WorkItem will run
References NUnit.Framework.Internal.Execution.WorkItem._state, NUnit.Framework.Internal.Execution.WorkItem._test, NUnit.Framework.Internal.Test.MakeTestResult(), and NUnit.Framework.Internal.Execution.WorkItem.Result.
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.OnChildCompleted().
Member Function Documentation
CreateWorkItem()
static WorkItem NUnit.Framework.Internal.Execution.WorkItem.CreateWorkItem (ITest test, ITestFilter filter) inline static
Creates a work item.
Parameters
test The test for which this WorkItem is being created.
filter The filter to be used in selecting any child Tests.
Returns
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.CreateChildWorkItems(), NUnit.Framework.Api.NUnitTestAssemblyRunner.RunAsync(), NUnit.TestUtilities.TestBuilder.RunTest(), and NUnit.TestUtilities.TestBuilder.RunTestSuite().
InitializeContext()
void NUnit.Framework.Internal.Execution.WorkItem.InitializeContext (TestExecutionContext context) inline
Initialize the TestExecutionContext. This must be done before executing the WorkItem.
Originally, the context was provided in the constructor but delaying initialization of the context until the item is about to be dispatched allows changes in the parent context during OneTimeSetUp to be reflected in the child.
Parameters
context The TestExecutionContext to use
References NUnit.Framework.Internal.Execution.WorkItem._actions, and NUnit.Framework.Internal.Execution.WorkItem._context.
Referenced by NUnit.TestUtilities.FakeWorkItem.FakeWorkItem(), NUnit.Framework.Api.NUnitTestAssemblyRunner.RunAsync(), NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren(), NUnit.TestUtilities.TestBuilder.RunTest(), and NUnit.TestUtilities.TestBuilder.RunTestSuite().
Execute()
virtual void NUnit.Framework.Internal.Execution.WorkItem.Execute () inline virtual
Execute the current work item, including any child work items.
Reimplemented in NUnit.TestUtilities.FakeWorkItem, and NUnit.TestUtilities.FakeWorkItem.
References NUnit.Framework.Internal.Execution.WorkItem._context, NUnit.Framework.Internal.Execution.WorkItem.RunTest(), NUnit.Framework.Internal.Execution.WorkItem.RunTestOnOwnThread(), NUnit.Framework.Internal.TestExecutionContext.TestCaseTimeout, and NUnit.Framework.Internal.PropertyNames.Timeout.
Referenced by NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher.Dispatch(), NUnit.Framework.Internal.Execution.SimpleWorkItemDispatcher.RunnerThreadProc(), NUnit.TestUtilities.TestBuilder.RunTest(), and NUnit.TestUtilities.TestBuilder.RunTestSuite().
RunTestOnOwnThread()
void NUnit.Framework.Internal.Execution.WorkItem.RunTestOnOwnThread (int timeout, ApartmentState apartment) inline private
References NUnit.Framework.Internal.Execution.WorkItem.Context, NUnit.Framework.Internal.TestExecutionContext.CurrentCulture, NUnit.Framework.Internal.TestExecutionContext.CurrentUICulture, NUnit.Framework.Interfaces.ResultState.Failure, NUnit.Framework.Internal.ThreadUtility.Kill(), NUnit.Framework.Internal.Execution.WorkItem.log, NUnit.Framework.Internal.Execution.WorkItem.Result, NUnit.Framework.Internal.TestResult.ResultState, NUnit.Framework.Internal.Execution.WorkItem.RunTest(), NUnit.Framework.Internal.TestResult.SetResult(), and NUnit.Framework.Internal.Execution.WorkItem.WorkItemComplete().
Referenced by NUnit.Framework.Internal.Execution.WorkItem.Execute().
RunTest()
void NUnit.Framework.Internal.Execution.WorkItem.RunTest () inline private
References NUnit.Framework.Internal.Execution.WorkItem._context, NUnit.Framework.Internal.Execution.WorkItem._state, NUnit.Framework.Internal.TestExecutionContext.CurrentResult, NUnit.Framework.Internal.TestExecutionContext.CurrentTest, NUnit.Framework.Internal.TestExecutionContext.EstablishExecutionEnvironment(), NUnit.Framework.Internal.Execution.WorkItem.PerformWork(), NUnit.Framework.Internal.Execution.WorkItem.Result, NUnit.Framework.Internal.TestExecutionContext.StartTicks, NUnit.Framework.Internal.TestExecutionContext.StartTime, NUnit.Framework.Internal.Execution.WorkItem.Test, and NUnit.Framework.Interfaces.ITestListener.TestStarted().
Referenced by NUnit.Framework.Internal.Execution.WorkItem.Execute(), and NUnit.Framework.Internal.Execution.WorkItem.RunTestOnOwnThread().
PerformWork()
abstract void NUnit.Framework.Internal.Execution.WorkItem.PerformWork () protected pure virtual
Method that performs actually performs the work. It should set the State to WorkItemState.Complete when done.
Implemented in NUnit.TestUtilities.FakeWorkItem, NUnit.TestUtilities.FakeWorkItem, NUnit.Framework.Internal.Execution.CompositeWorkItem, and NUnit.Framework.Internal.Execution.SimpleWorkItem.
Referenced by NUnit.Framework.Internal.Execution.WorkItem.RunTest().
WorkItemComplete()
void NUnit.Framework.Internal.Execution.WorkItem.WorkItemComplete () inline protected
Method called by the derived class when all work is complete
References NUnit.Framework.Internal.Execution.WorkItem._context, NUnit.Framework.Internal.Execution.WorkItem._state, NUnit.Framework.Internal.TestResult.AssertCount, NUnit.Framework.Internal.Execution.WorkItem.Completed, NUnit.Framework.Internal.Execution.WorkItem.Context, NUnit.Framework.Internal.TestResult.Duration, NUnit.Framework.Internal.TestResult.EndTime, NUnit.Framework.Internal.Execution.WorkItem.Result, NUnit.Framework.Internal.TestExecutionContext.StartTicks, NUnit.Framework.Internal.TestResult.StartTime, NUnit.Framework.Internal.TestExecutionContext.StartTime, and NUnit.Framework.Interfaces.ITestListener.TestFinished().
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.CountDownChildTest(), NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork(), NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork(), and NUnit.Framework.Internal.Execution.WorkItem.RunTestOnOwnThread().
Member Data Documentation
log
Logger NUnit.Framework.Internal.Execution.WorkItem.log = InternalTrace.GetLogger("WorkItem") static private
Referenced by NUnit.Framework.Internal.Execution.WorkItem.RunTestOnOwnThread().
_state
WorkItemState NUnit.Framework.Internal.Execution.WorkItem._state private
Referenced by NUnit.Framework.Internal.Execution.WorkItem.RunTest(), NUnit.Framework.Internal.Execution.WorkItem.WorkItem(), and NUnit.Framework.Internal.Execution.WorkItem.WorkItemComplete().
_test
Test NUnit.Framework.Internal.Execution.WorkItem._test private
Referenced by NUnit.Framework.Internal.Execution.WorkItem.WorkItem().
_context
TestExecutionContext NUnit.Framework.Internal.Execution.WorkItem._context private
Referenced by NUnit.Framework.Internal.Execution.WorkItem.Execute(), NUnit.Framework.Internal.Execution.WorkItem.InitializeContext(), NUnit.Framework.Internal.Execution.WorkItem.RunTest(), and NUnit.Framework.Internal.Execution.WorkItem.WorkItemComplete().
_actions
List<ITestAction> NUnit.Framework.Internal.Execution.WorkItem._actions = new List<ITestAction>() private
Referenced by NUnit.Framework.Internal.Execution.WorkItem.InitializeContext().
Property Documentation
State
WorkItemState NUnit.Framework.Internal.Execution.WorkItem.State get
Gets the current state of the WorkItem
Referenced by NUnit.TestUtilities.TestBuilder.RunTest(), and NUnit.TestUtilities.TestBuilder.RunTestSuite().
Test
Test NUnit.Framework.Internal.Execution.WorkItem.Test get
The test being executed by the work item
Referenced by NUnit.Framework.Internal.Execution.WorkItem.RunTest().
Context
TestExecutionContext NUnit.Framework.Internal.Execution.WorkItem.Context get
The execution context
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.CheckForCancellation(), NUnit.Framework.Internal.Execution.CompositeWorkItem.CountDownChildTest(), NUnit.Framework.Internal.Execution.CompositeWorkItem.InitializeSetUpAndTearDownCommands(), NUnit.Framework.Internal.Execution.CompositeWorkItem.OnChildCompleted(), NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeSetUp(), NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeTearDown(), NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork(), NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork(), NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren(), NUnit.Framework.Internal.Execution.WorkItem.RunTestOnOwnThread(), NUnit.Framework.Internal.Execution.CompositeWorkItem.SkipChildren(), and NUnit.Framework.Internal.Execution.WorkItem.WorkItemComplete().
Actions
List<ITestAction> NUnit.Framework.Internal.Execution.WorkItem.Actions get
The test actions to be performed before and after this test
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.InitializeSetUpAndTearDownCommands().
Result
TestResult NUnit.Framework.Internal.Execution.WorkItem.Result get protected set
The test result
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.CheckForCancellation(), NUnit.Framework.Internal.Execution.CompositeWorkItem.CountDownChildTest(), NUnit.Framework.Internal.Execution.CompositeWorkItem.OnChildCompleted(), NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformOneTimeSetUp(), NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork(), NUnit.Framework.Internal.Execution.CompositeWorkItem.PerformWork(), NUnit.TestUtilities.TestBuilder.RunTest(), NUnit.Framework.Internal.Execution.WorkItem.RunTest(), NUnit.Framework.Internal.Execution.WorkItem.RunTestOnOwnThread(), NUnit.TestUtilities.TestBuilder.RunTestSuite(), NUnit.Framework.Internal.Execution.CompositeWorkItem.SkipChildren(), NUnit.Framework.Internal.Execution.CompositeWorkItem.SkipFixture(), NUnit.Framework.Internal.Execution.WorkItem.WorkItem(), and NUnit.Framework.Internal.Execution.WorkItem.WorkItemComplete().
Event Documentation
Completed
EventHandler NUnit.Framework.Internal.Execution.WorkItem.Completed
Event triggered when the item is complete
Referenced by NUnit.Framework.Internal.Execution.CompositeWorkItem.OnChildCompleted(), NUnit.Framework.Api.NUnitTestAssemblyRunner.RunAsync(), NUnit.Framework.Internal.Execution.CompositeWorkItem.RunChildren(), and NUnit.Framework.Internal.Execution.WorkItem.WorkItemComplete().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Internal/Execution/WorkItem.cs