Doc: IGLib EXTENDED: IG.Test.TestUtilities Class Reference
IG.Test.TestUtilities Class Reference
Unit tests for various utilities.
Public Member Functions
void ArraysConcatenateAndEquality ()
Tests array concatenation and equality checking.
void ArraysAndListToString ()
Tests array concatenation and equality checking.
void IGLibCore_Is_Available ()
This test is here just to veriy that the IGLibCore is actually properly linked, despite of errors that are sometimes reported.
void ArraysConcatenateAndEquality ()
Tests array concatenation and equality checking.
void ArraysAndListToString ()
Tests array concatenation and equality checking.
Protected Attributes
int OutputLevel = 1
Detailed Description
Unit tests for various utilities.
$A Igor May09;
Member Function Documentation
ArraysConcatenateAndEquality() [1/2]
void IG.Test.TestUtilities.ArraysConcatenateAndEquality () inline
Tests array concatenation and equality checking.
References IG.Test.TestUtilities.OutputLevel.
ArraysAndListToString() [1/2]
void IG.Test.TestUtilities.ArraysAndListToString () inline
Tests array concatenation and equality checking.
References IG.Test.TestUtilities.OutputLevel.
IGLibCore_Is_Available()
void IG.Test.TestUtilities.IGLibCore_Is_Available () inline
This test is here just to veriy that the IGLibCore is actually properly linked, despite of errors that are sometimes reported.
typical warning reported by MSBuild:
Warning The project 'IGLibCore' cannot be referenced.The referenced project is targeted to a different framework family(.NETCoreApp) TestUtil_MSTest
ArraysConcatenateAndEquality() [2/2]
void IG.Test.TestUtilities.ArraysConcatenateAndEquality () inline
Tests array concatenation and equality checking.
References IG.Test.TestUtilities.OutputLevel, NUnit.Framework.Assert.That(), and NUnit.Framework.Is.True.
ArraysAndListToString() [2/2]
void IG.Test.TestUtilities.ArraysAndListToString () inline
Tests array concatenation and equality checking.
References NUnit.Framework.Is.EqualTo(), IG.Test.TestUtilities.OutputLevel, and NUnit.Framework.Assert.That().
Member Data Documentation
OutputLevel
int IG.Test.TestUtilities.OutputLevel = 1 protected
Referenced by IG.Test.TestUtilities.ArraysAndListToString(), and IG.Test.TestUtilities.ArraysConcatenateAndEquality().
The documentation for this class was generated from the following file:
unittests/MSTests/TestUtil/TstUtil.cs