Doc: IGLib EXTENDED: NUnit.Framework.FileAssert Class Reference
NUnit.Framework.FileAssert Class Reference
Asserts on Files
Static Public Member Functions
static new bool Equals (object a, object b)
The Equals method throws an AssertionException. This is done to make sure there is no mistake by calling this function.
static new void ReferenceEquals (object a, object b)
override the default ReferenceEquals to throw an AssertionException. This implementation makes sure there is no mistake in calling this function as part of Assert.
static void AreEqual (Stream expected, Stream actual, string message, params object[] args)
Verifies that two Streams are equal. Two Streams are considered equal if both are null, or if both have the same value byte for byte. If they are not equal an AssertionException is thrown.
static void AreEqual (Stream expected, Stream actual)
Verifies that two Streams are equal. Two Streams are considered equal if both are null, or if both have the same value byte for byte. If they are not equal an AssertionException is thrown.
static void AreEqual (FileInfo expected, FileInfo actual, string message, params object[] args)
Verifies that two files are equal. Two files are considered equal if both are null, or if both have the same value byte for byte. If they are not equal an AssertionException is thrown.
static void AreEqual (FileInfo expected, FileInfo actual)
Verifies that two files are equal. Two files are considered equal if both are null, or if both have the same value byte for byte. If they are not equal an AssertionException is thrown.
static void AreEqual (string expected, string actual, string message, params object[] args)
Verifies that two files are equal. Two files are considered equal if both are null, or if both have the same value byte for byte. If they are not equal an AssertionException is thrown.
static void AreEqual (string expected, string actual)
Verifies that two files are equal. Two files are considered equal if both are null, or if both have the same value byte for byte. If they are not equal an AssertionException is thrown.
static void AreNotEqual (Stream expected, Stream actual, string message, params object[] args)
Asserts that two Streams are not equal. If they are equal an AssertionException is thrown.
static void AreNotEqual (Stream expected, Stream actual)
Asserts that two Streams are not equal. If they are equal an AssertionException is thrown.
static void AreNotEqual (FileInfo expected, FileInfo actual, string message, params object[] args)
Asserts that two files are not equal. If they are equal an AssertionException is thrown.
static void AreNotEqual (FileInfo expected, FileInfo actual)
Asserts that two files are not equal. If they are equal an AssertionException is thrown.
static void AreNotEqual (string expected, string actual, string message, params object[] args)
Asserts that two files are not equal. If they are equal an AssertionException is thrown.
static void AreNotEqual (string expected, string actual)
Asserts that two files are not equal. If they are equal an AssertionException is thrown.
static void Exists (FileInfo actual, string message, params object[] args)
Asserts that the file exists. If it does not exist an AssertionException is thrown.
static void Exists (FileInfo actual)
Asserts that the file exists. If it does not exist an AssertionException is thrown.
static void Exists (string actual, string message, params object[] args)
Asserts that the file exists. If it does not exist an AssertionException is thrown.
static void Exists (string actual)
Asserts that the file exists. If it does not exist an AssertionException is thrown.
static void DoesNotExist (FileInfo actual, string message, params object[] args)
Asserts that the file does not exist. If it does exist an AssertionException is thrown.
static void DoesNotExist (FileInfo actual)
Asserts that the file does not exist. If it does exist an AssertionException is thrown.
static void DoesNotExist (string actual, string message, params object[] args)
Asserts that the file does not exist. If it does exist an AssertionException is thrown.
static void DoesNotExist (string actual)
Asserts that the file does not exist. If it does exist an AssertionException is thrown.
Detailed Description
Asserts on Files
Member Function Documentation
Equals()
static new bool NUnit.Framework.FileAssert.Equals (object a, object b) inline static
The Equals method throws an AssertionException. This is done to make sure there is no mistake by calling this function.
Parameters
a
b
ReferenceEquals()
static new void NUnit.Framework.FileAssert.ReferenceEquals (object a, object b) inline static
override the default ReferenceEquals to throw an AssertionException. This implementation makes sure there is no mistake in calling this function as part of Assert.
Parameters
a
b
AreEqual() [1/6]
static void NUnit.Framework.FileAssert.AreEqual (Stream expected, Stream actual, string message, params object[] args) inline static
Verifies that two Streams are equal. Two Streams are considered equal if both are null, or if both have the same value byte for byte. If they are not equal an AssertionException is thrown.
Parameters
expected The expected Stream
actual The actual Stream
message The message to display if Streams are not equal
args Arguments to be used in formatting the message
References NUnit.Framework.Is.EqualTo(), and NUnit.Framework.Assert.That().
Referenced by NUnit.Framework.FileAssert.AreEqual(), NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWhenOneIsNull(), NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWithFileInfos(), NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWithFiles(), NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWithStreams(), NUnit.Framework.Assertions.FileAssertTests.AreEqualFailsWithTextFilesAfterReadingBothFiles(), NUnit.Framework.Assertions.FileAssertTests.AreEqualPassesUsingSameFileTwice(), NUnit.Framework.Assertions.FileAssertTests.AreEqualPassesWhenBothAreNull(), NUnit.Framework.Assertions.FileAssertTests.AreEqualPassesWithEqualStreams(), NUnit.Framework.Assertions.FileAssertTests.AreEqualPassesWithFileInfos(), NUnit.Framework.Assertions.FileAssertTests.AreEqualPassesWithFiles(), NUnit.Framework.Assertions.FileAssertTests.AreEqualPassesWithTextFiles(), NUnit.Framework.Assertions.FileAssertTests.NonReadableStreamGivesException(), and NUnit.Framework.Assertions.FileAssertTests.NonSeekableStreamGivesException().
AreEqual() [2/6]
static void NUnit.Framework.FileAssert.AreEqual (Stream expected, Stream actual) inline static
Verifies that two Streams are equal. Two Streams are considered equal if both are null, or if both have the same value byte for byte. If they are not equal an AssertionException is thrown.
Parameters
expected The expected Stream
actual The actual Stream
References NUnit.Framework.FileAssert.AreEqual().
AreEqual() [3/6]
static void NUnit.Framework.FileAssert.AreEqual (FileInfo expected, FileInfo actual, string message, params object[] args) inline static
Verifies that two files are equal. Two files are considered equal if both are null, or if both have the same value byte for byte. If they are not equal an AssertionException is thrown.
Parameters
expected A file containing the value that is expected
actual A file containing the actual value
message The message to display if Streams are not equal
args Arguments to be used in formatting the message
AreEqual() [4/6]
static void NUnit.Framework.FileAssert.AreEqual (FileInfo expected, FileInfo actual) inline static
Verifies that two files are equal. Two files are considered equal if both are null, or if both have the same value byte for byte. If they are not equal an AssertionException is thrown.
Parameters
expected A file containing the value that is expected
actual A file containing the actual value
References NUnit.Framework.FileAssert.AreEqual().
AreEqual() [5/6]
static void NUnit.Framework.FileAssert.AreEqual (string expected, string actual, string message, params object[] args) inline static
Verifies that two files are equal. Two files are considered equal if both are null, or if both have the same value byte for byte. If they are not equal an AssertionException is thrown.
Parameters
expected The path to a file containing the value that is expected
actual The path to a file containing the actual value
message The message to display if Streams are not equal
args Arguments to be used in formatting the message
AreEqual() [6/6]
static void NUnit.Framework.FileAssert.AreEqual (string expected, string actual) inline static
Verifies that two files are equal. Two files are considered equal if both are null, or if both have the same value byte for byte. If they are not equal an AssertionException is thrown.
Parameters
expected The path to a file containing the value that is expected
actual The path to a file containing the actual value
References NUnit.Framework.FileAssert.AreEqual().
AreNotEqual() [1/6]
static void NUnit.Framework.FileAssert.AreNotEqual (Stream expected, Stream actual, string message, params object[] args) inline static
Asserts that two Streams are not equal. If they are equal an AssertionException is thrown.
Parameters
expected The expected Stream
actual The actual Stream
message The message to be displayed when the two Stream are the same.
args Arguments to be used in formatting the message
Referenced by NUnit.Framework.FileAssert.AreNotEqual(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualFailsWhenBothAreNull(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualFailsWithFileInfos(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualFailsWithFiles(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualFailsWithStreams(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualIteratesOverTheEntireFile(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualIteratesOverTheEntireFileAndFails(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualPassesIfOneIsNull(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualPassesWithFileInfos(), NUnit.Framework.Assertions.FileAssertTests.AreNotEqualPassesWithFiles(), and NUnit.Framework.Assertions.FileAssertTests.AreNotEqualPassesWithStreams().
AreNotEqual() [2/6]
static void NUnit.Framework.FileAssert.AreNotEqual (Stream expected, Stream actual) inline static
Asserts that two Streams are not equal. If they are equal an AssertionException is thrown.
Parameters
expected The expected Stream
actual The actual Stream
References NUnit.Framework.FileAssert.AreNotEqual().
AreNotEqual() [3/6]
static void NUnit.Framework.FileAssert.AreNotEqual (FileInfo expected, FileInfo actual, string message, params object[] args) inline static
Asserts that two files are not equal. If they are equal an AssertionException is thrown.
Parameters
expected A file containing the value that is expected
actual A file containing the actual value
message The message to display if Streams are not equal
args Arguments to be used in formatting the message
AreNotEqual() [4/6]
static void NUnit.Framework.FileAssert.AreNotEqual (FileInfo expected, FileInfo actual) inline static
Asserts that two files are not equal. If they are equal an AssertionException is thrown.
Parameters
expected A file containing the value that is expected
actual A file containing the actual value
References NUnit.Framework.FileAssert.AreNotEqual().
AreNotEqual() [5/6]
static void NUnit.Framework.FileAssert.AreNotEqual (string expected, string actual, string message, params object[] args) inline static
Asserts that two files are not equal. If they are equal an AssertionException is thrown.
Parameters
expected The path to a file containing the value that is expected
actual The path to a file containing the actual value
message The message to display if Streams are not equal
args Arguments to be used in formatting the message
AreNotEqual() [6/6]
static void NUnit.Framework.FileAssert.AreNotEqual (string expected, string actual) inline static
Asserts that two files are not equal. If they are equal an AssertionException is thrown.
Parameters
expected The path to a file containing the value that is expected
actual The path to a file containing the actual value
References NUnit.Framework.FileAssert.AreNotEqual().
Exists() [1/4]
static void NUnit.Framework.FileAssert.Exists (FileInfo actual, string message, params object[] args) inline static
Asserts that the file exists. If it does not exist an AssertionException is thrown.
Parameters
actual A file containing the actual value
message The message to display if Streams are not equal
args Arguments to be used in formatting the message
Referenced by NUnit.Framework.FileAssert.Exists(), NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenFileInfoDoesNotExist(), NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenFileInfoIsNull(), NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenStringDoesNotExist(), NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenStringIsEmpty(), NUnit.Framework.Assertions.FileAssertTests.ExistsFailsWhenStringIsNull(), NUnit.Framework.Assertions.FileAssertTests.ExistsPassesWhenFileInfoExists(), and NUnit.Framework.Assertions.FileAssertTests.ExistsPassesWhenStringExists().
Exists() [2/4]
static void NUnit.Framework.FileAssert.Exists (FileInfo actual) inline static
Asserts that the file exists. If it does not exist an AssertionException is thrown.
Parameters
actual A file containing the actual value
References NUnit.Framework.FileAssert.Exists().
Exists() [3/4]
static void NUnit.Framework.FileAssert.Exists (string actual, string message, params object[] args) inline static
Asserts that the file exists. If it does not exist an AssertionException is thrown.
Parameters
actual The path to a file containing the actual value
message The message to display if Streams are not equal
args Arguments to be used in formatting the message
Exists() [4/4]
static void NUnit.Framework.FileAssert.Exists (string actual) inline static
Asserts that the file exists. If it does not exist an AssertionException is thrown.
Parameters
actual The path to a file containing the actual value
References NUnit.Framework.FileAssert.Exists().
DoesNotExist() [1/4]
static void NUnit.Framework.FileAssert.DoesNotExist (FileInfo actual, string message, params object[] args) inline static
Asserts that the file does not exist. If it does exist an AssertionException is thrown.
Parameters
actual A file containing the actual value
message The message to display if Streams are not equal
args Arguments to be used in formatting the message
Referenced by NUnit.Framework.FileAssert.DoesNotExist(), NUnit.Framework.Assertions.FileAssertTests.DoesNotExistFailsWhenFileInfoExists(), NUnit.Framework.Assertions.FileAssertTests.DoesNotExistFailsWhenFileInfoIsNull(), NUnit.Framework.Assertions.FileAssertTests.DoesNotExistFailsWhenStringExists(), NUnit.Framework.Assertions.FileAssertTests.DoesNotExistFailsWhenStringIsEmpty(), NUnit.Framework.Assertions.FileAssertTests.DoesNotExistFailsWhenStringIsNull(), NUnit.Framework.Assertions.FileAssertTests.DoesNotExistPassesWhenFileInfoDoesNotExist(), and NUnit.Framework.Assertions.FileAssertTests.DoesNotExistPassesWhenStringDoesNotExist().
DoesNotExist() [2/4]
static void NUnit.Framework.FileAssert.DoesNotExist (FileInfo actual) inline static
Asserts that the file does not exist. If it does exist an AssertionException is thrown.
Parameters
actual A file containing the actual value
References NUnit.Framework.FileAssert.DoesNotExist().
DoesNotExist() [3/4]
static void NUnit.Framework.FileAssert.DoesNotExist (string actual, string message, params object[] args) inline static
Asserts that the file does not exist. If it does exist an AssertionException is thrown.
Parameters
actual The path to a file containing the actual value
message The message to display if Streams are not equal
args Arguments to be used in formatting the message
DoesNotExist() [4/4]
static void NUnit.Framework.FileAssert.DoesNotExist (string actual) inline static
Asserts that the file does not exist. If it does exist an AssertionException is thrown.
Parameters
actual The path to a file containing the actual value
References NUnit.Framework.FileAssert.DoesNotExist().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/FileAssert.cs