Doc: IGLib EXTENDED: alglib.rcond Class Reference
alglib.rcond Class Reference
Static Public Member Functions
static double rmatrixrcond1 (double[,] a, int n)
static double rmatrixrcondinf (double[,] a, int n)
static double spdmatrixrcond (double[,] a, int n, bool isupper)
static double rmatrixtrrcond1 (double[,] a, int n, bool isupper, bool isunit)
static double rmatrixtrrcondinf (double[,] a, int n, bool isupper, bool isunit)
static double hpdmatrixrcond (complex[,] a, int n, bool isupper)
static double cmatrixrcond1 (complex[,] a, int n)
static double cmatrixrcondinf (complex[,] a, int n)
static double rmatrixlurcond1 (double[,] lua, int n)
static double rmatrixlurcondinf (double[,] lua, int n)
static double spdmatrixcholeskyrcond (double[,] a, int n, bool isupper)
static double hpdmatrixcholeskyrcond (complex[,] a, int n, bool isupper)
static double cmatrixlurcond1 (complex[,] lua, int n)
static double cmatrixlurcondinf (complex[,] lua, int n)
static double cmatrixtrrcond1 (complex[,] a, int n, bool isupper, bool isunit)
static double cmatrixtrrcondinf (complex[,] a, int n, bool isupper, bool isunit)
static double rcondthreshold ()
static double rmatrixrcond1 (double[,] a, int n)
static double rmatrixrcondinf (double[,] a, int n)
static double spdmatrixrcond (double[,] a, int n, bool isupper)
static double rmatrixtrrcond1 (double[,] a, int n, bool isupper, bool isunit)
static double rmatrixtrrcondinf (double[,] a, int n, bool isupper, bool isunit)
static double hpdmatrixrcond (complex[,] a, int n, bool isupper)
static double cmatrixrcond1 (complex[,] a, int n)
static double cmatrixrcondinf (complex[,] a, int n)
static double rmatrixlurcond1 (double[,] lua, int n)
static double rmatrixlurcondinf (double[,] lua, int n)
static double spdmatrixcholeskyrcond (double[,] a, int n, bool isupper)
static double hpdmatrixcholeskyrcond (complex[,] a, int n, bool isupper)
static double cmatrixlurcond1 (complex[,] lua, int n)
static double cmatrixlurcondinf (complex[,] lua, int n)
static double cmatrixtrrcond1 (complex[,] a, int n, bool isupper, bool isunit)
static double cmatrixtrrcondinf (complex[,] a, int n, bool isupper, bool isunit)
static double rcondthreshold ()
Static Private Member Functions
static void rmatrixrcondtrinternal (double[,] a, int n, bool isupper, bool isunit, bool onenorm, double anorm, ref double rc)
static void cmatrixrcondtrinternal (complex[,] a, int n, bool isupper, bool isunit, bool onenorm, double anorm, ref double rc)
static void spdmatrixrcondcholeskyinternal (double[,] cha, int n, bool isupper, bool isnormprovided, double anorm, ref double rc)
static void hpdmatrixrcondcholeskyinternal (complex[,] cha, int n, bool isupper, bool isnormprovided, double anorm, ref double rc)
static void rmatrixrcondluinternal (double[,] lua, int n, bool onenorm, bool isanormprovided, double anorm, ref double rc)
static void cmatrixrcondluinternal (complex[,] lua, int n, bool onenorm, bool isanormprovided, double anorm, ref double rc)
static void rmatrixestimatenorm (int n, ref double[] v, ref double[] x, ref int[] isgn, ref double est, ref int kase)
static void cmatrixestimatenorm (int n, ref complex[] v, ref complex[] x, ref double est, ref int kase, ref int[] isave, ref double[] rsave)
static double internalcomplexrcondscsum1 (complex[] x, int n)
static int internalcomplexrcondicmax1 (complex[] x, int n)
static void internalcomplexrcondsaveall (ref int[] isave, ref double[] rsave, ref int i, ref int iter, ref int j, ref int jlast, ref int jump, ref double absxi, ref double altsgn, ref double estold, ref double temp)
static void internalcomplexrcondloadall (ref int[] isave, ref double[] rsave, ref int i, ref int iter, ref int j, ref int jlast, ref int jump, ref double absxi, ref double altsgn, ref double estold, ref double temp)
static void rmatrixrcondtrinternal (double[,] a, int n, bool isupper, bool isunit, bool onenorm, double anorm, ref double rc)
static void cmatrixrcondtrinternal (complex[,] a, int n, bool isupper, bool isunit, bool onenorm, double anorm, ref double rc)
static void spdmatrixrcondcholeskyinternal (double[,] cha, int n, bool isupper, bool isnormprovided, double anorm, ref double rc)
static void hpdmatrixrcondcholeskyinternal (complex[,] cha, int n, bool isupper, bool isnormprovided, double anorm, ref double rc)
static void rmatrixrcondluinternal (double[,] lua, int n, bool onenorm, bool isanormprovided, double anorm, ref double rc)
static void cmatrixrcondluinternal (complex[,] lua, int n, bool onenorm, bool isanormprovided, double anorm, ref double rc)
static void rmatrixestimatenorm (int n, ref double[] v, ref double[] x, ref int[] isgn, ref double est, ref int kase)
static void cmatrixestimatenorm (int n, ref complex[] v, ref complex[] x, ref double est, ref int kase, ref int[] isave, ref double[] rsave)
static double internalcomplexrcondscsum1 (complex[] x, int n)
static int internalcomplexrcondicmax1 (complex[] x, int n)
static void internalcomplexrcondsaveall (ref int[] isave, ref double[] rsave, ref int i, ref int iter, ref int j, ref int jlast, ref int jump, ref double absxi, ref double altsgn, ref double estold, ref double temp)
static void internalcomplexrcondloadall (ref int[] isave, ref double[] rsave, ref int i, ref int iter, ref int j, ref int jlast, ref int jump, ref double absxi, ref double altsgn, ref double estold, ref double temp)
Member Function Documentation
rmatrixrcond1() [1/2]
static double alglib.rcond.rmatrixrcond1 (double a[,], int n) inline static
Referenced by alglib.rmatrixrcond1(), and alglib.testrcondunit.testrmatrixrcond().
rmatrixrcondinf() [1/2]
static double alglib.rcond.rmatrixrcondinf (double a[,], int n) inline static
Referenced by alglib.rmatrixrcondinf(), and alglib.testrcondunit.testrmatrixrcond().
spdmatrixrcond() [1/2]
static double alglib.rcond.spdmatrixrcond (double a[,], int n, bool isupper) inline static
Referenced by alglib.spdmatrixrcond(), and alglib.testrcondunit.testspdmatrixrcond().
rmatrixtrrcond1() [1/2]
static double alglib.rcond.rmatrixtrrcond1 (double a[,], int n, bool isupper, bool isunit) inline static
Referenced by alglib.rmatrixtrrcond1(), and alglib.testrcondunit.testrmatrixtrrcond().
rmatrixtrrcondinf() [1/2]
static double alglib.rcond.rmatrixtrrcondinf (double a[,], int n, bool isupper, bool isunit) inline static
Referenced by alglib.idwint.idwinternalsolver(), alglib.rmatrixtrrcondinf(), and alglib.testrcondunit.testrmatrixtrrcond().
hpdmatrixrcond() [1/2]
static double alglib.rcond.hpdmatrixrcond (complex a[,], int n, bool isupper) inline static
Referenced by alglib.hpdmatrixrcond(), and alglib.testrcondunit.testhpdmatrixrcond().
cmatrixrcond1() [1/2]
static double alglib.rcond.cmatrixrcond1 (complex a[,], int n) inline static
Referenced by alglib.cmatrixrcond1(), and alglib.testrcondunit.testcmatrixrcond().
cmatrixrcondinf() [1/2]
static double alglib.rcond.cmatrixrcondinf (complex a[,], int n) inline static
Referenced by alglib.cmatrixrcondinf(), and alglib.testrcondunit.testcmatrixrcond().
rmatrixlurcond1() [1/2]
static double alglib.rcond.rmatrixlurcond1 (double lua[,], int n) inline static
Referenced by alglib.rmatrixlurcond1(), alglib.densesolver.rmatrixlusolveinternal(), and alglib.testrcondunit.testrmatrixrcond().
rmatrixlurcondinf() [1/2]
static double alglib.rcond.rmatrixlurcondinf (double lua[,], int n) inline static
Referenced by alglib.rmatrixlurcondinf(), alglib.densesolver.rmatrixlusolveinternal(), and alglib.testrcondunit.testrmatrixrcond().
spdmatrixcholeskyrcond() [1/2]
static double alglib.rcond.spdmatrixcholeskyrcond (double a[,], int n, bool isupper) inline static
Referenced by alglib.spdmatrixcholeskyrcond(), alglib.densesolver.spdmatrixcholeskysolveinternal(), and alglib.testrcondunit.testspdmatrixrcond().
hpdmatrixcholeskyrcond() [1/2]
static double alglib.rcond.hpdmatrixcholeskyrcond (complex a[,], int n, bool isupper) inline static
Referenced by alglib.hpdmatrixcholeskyrcond(), alglib.densesolver.hpdmatrixcholeskysolveinternal(), and alglib.testrcondunit.testhpdmatrixrcond().
cmatrixlurcond1() [1/2]
static double alglib.rcond.cmatrixlurcond1 (complex lua[,], int n) inline static
Referenced by alglib.cmatrixlurcond1(), alglib.densesolver.cmatrixlusolveinternal(), and alglib.testrcondunit.testcmatrixrcond().
cmatrixlurcondinf() [1/2]
static double alglib.rcond.cmatrixlurcondinf (complex lua[,], int n) inline static
Referenced by alglib.cmatrixlurcondinf(), alglib.densesolver.cmatrixlusolveinternal(), and alglib.testrcondunit.testcmatrixrcond().
cmatrixtrrcond1() [1/2]
static double alglib.rcond.cmatrixtrrcond1 (complex a[,], int n, bool isupper, bool isunit) inline static
Referenced by alglib.cmatrixtrrcond1(), and alglib.testrcondunit.testcmatrixtrrcond().
cmatrixtrrcondinf() [1/2]
static double alglib.rcond.cmatrixtrrcondinf (complex a[,], int n, bool isupper, bool isunit) inline static
Referenced by alglib.cmatrixtrrcondinf(), and alglib.testrcondunit.testcmatrixtrrcond().
rcondthreshold() [1/2]
static double alglib.rcond.rcondthreshold () inline static
Referenced by alglib.densesolver.cmatrixlusolveinternal(), alglib.densesolver.hpdmatrixcholeskysolveinternal(), alglib.densesolver.rmatrixlusolveinternal(), and alglib.densesolver.spdmatrixcholeskysolveinternal().
rmatrixrcondtrinternal() [1/2]
static void alglib.rcond.rmatrixrcondtrinternal (double a[,], int n, bool isupper, bool isunit, bool onenorm, double anorm, ref double rc) inline static private
cmatrixrcondtrinternal() [1/2]
static void alglib.rcond.cmatrixrcondtrinternal (complex a[,], int n, bool isupper, bool isunit, bool onenorm, double anorm, ref double rc) inline static private
spdmatrixrcondcholeskyinternal() [1/2]
static void alglib.rcond.spdmatrixrcondcholeskyinternal (double cha[,], int n, bool isupper, bool isnormprovided, double anorm, ref double rc) inline static private
hpdmatrixrcondcholeskyinternal() [1/2]
static void alglib.rcond.hpdmatrixrcondcholeskyinternal (complex cha[,], int n, bool isupper, bool isnormprovided, double anorm, ref double rc) inline static private
rmatrixrcondluinternal() [1/2]
static void alglib.rcond.rmatrixrcondluinternal (double lua[,], int n, bool onenorm, bool isanormprovided, double anorm, ref double rc) inline static private
cmatrixrcondluinternal() [1/2]
static void alglib.rcond.cmatrixrcondluinternal (complex lua[,], int n, bool onenorm, bool isanormprovided, double anorm, ref double rc) inline static private
rmatrixestimatenorm() [1/2]
static void alglib.rcond.rmatrixestimatenorm (int n, ref double[] v, ref double[] x, ref int[] isgn, ref double est, ref int kase) inline static private
cmatrixestimatenorm() [1/2]
static void alglib.rcond.cmatrixestimatenorm (int n, ref complex[] v, ref complex[] x, ref double est, ref int kase, ref int[] isave, ref double[] rsave) inline static private
internalcomplexrcondscsum1() [1/2]
static double alglib.rcond.internalcomplexrcondscsum1 (complex[] x, int n) inline static private
internalcomplexrcondicmax1() [1/2]
static int alglib.rcond.internalcomplexrcondicmax1 (complex[] x, int n) inline static private
internalcomplexrcondsaveall() [1/2]
static void alglib.rcond.internalcomplexrcondsaveall (ref int[] isave, ref double[] rsave, ref int i, ref int iter, ref int j, ref int jlast, ref int jump, ref double absxi, ref double altsgn, ref double estold, ref double temp) inline static private
internalcomplexrcondloadall() [1/2]
static void alglib.rcond.internalcomplexrcondloadall (ref int[] isave, ref double[] rsave, ref int i, ref int iter, ref int j, ref int jlast, ref int jump, ref double absxi, ref double altsgn, ref double estold, ref double temp) inline static private
rmatrixrcond1() [2/2]
static double alglib.rcond.rmatrixrcond1 (double a[,], int n) inline static
rmatrixrcondinf() [2/2]
static double alglib.rcond.rmatrixrcondinf (double a[,], int n) inline static
spdmatrixrcond() [2/2]
static double alglib.rcond.spdmatrixrcond (double a[,], int n, bool isupper) inline static
rmatrixtrrcond1() [2/2]
static double alglib.rcond.rmatrixtrrcond1 (double a[,], int n, bool isupper, bool isunit) inline static
rmatrixtrrcondinf() [2/2]
static double alglib.rcond.rmatrixtrrcondinf (double a[,], int n, bool isupper, bool isunit) inline static
hpdmatrixrcond() [2/2]
static double alglib.rcond.hpdmatrixrcond (complex a[,], int n, bool isupper) inline static
cmatrixrcond1() [2/2]
static double alglib.rcond.cmatrixrcond1 (complex a[,], int n) inline static
cmatrixrcondinf() [2/2]
static double alglib.rcond.cmatrixrcondinf (complex a[,], int n) inline static
rmatrixlurcond1() [2/2]
static double alglib.rcond.rmatrixlurcond1 (double lua[,], int n) inline static
rmatrixlurcondinf() [2/2]
static double alglib.rcond.rmatrixlurcondinf (double lua[,], int n) inline static
spdmatrixcholeskyrcond() [2/2]
static double alglib.rcond.spdmatrixcholeskyrcond (double a[,], int n, bool isupper) inline static
hpdmatrixcholeskyrcond() [2/2]
static double alglib.rcond.hpdmatrixcholeskyrcond (complex a[,], int n, bool isupper) inline static
cmatrixlurcond1() [2/2]
static double alglib.rcond.cmatrixlurcond1 (complex lua[,], int n) inline static
cmatrixlurcondinf() [2/2]
static double alglib.rcond.cmatrixlurcondinf (complex lua[,], int n) inline static
cmatrixtrrcond1() [2/2]
static double alglib.rcond.cmatrixtrrcond1 (complex a[,], int n, bool isupper, bool isunit) inline static
cmatrixtrrcondinf() [2/2]
static double alglib.rcond.cmatrixtrrcondinf (complex a[,], int n, bool isupper, bool isunit) inline static
rcondthreshold() [2/2]
static double alglib.rcond.rcondthreshold () inline static
rmatrixrcondtrinternal() [2/2]
static void alglib.rcond.rmatrixrcondtrinternal (double a[,], int n, bool isupper, bool isunit, bool onenorm, double anorm, ref double rc) inline static private
cmatrixrcondtrinternal() [2/2]
static void alglib.rcond.cmatrixrcondtrinternal (complex a[,], int n, bool isupper, bool isunit, bool onenorm, double anorm, ref double rc) inline static private
spdmatrixrcondcholeskyinternal() [2/2]
static void alglib.rcond.spdmatrixrcondcholeskyinternal (double cha[,], int n, bool isupper, bool isnormprovided, double anorm, ref double rc) inline static private
hpdmatrixrcondcholeskyinternal() [2/2]
static void alglib.rcond.hpdmatrixrcondcholeskyinternal (complex cha[,], int n, bool isupper, bool isnormprovided, double anorm, ref double rc) inline static private
rmatrixrcondluinternal() [2/2]
static void alglib.rcond.rmatrixrcondluinternal (double lua[,], int n, bool onenorm, bool isanormprovided, double anorm, ref double rc) inline static private
cmatrixrcondluinternal() [2/2]
static void alglib.rcond.cmatrixrcondluinternal (complex lua[,], int n, bool onenorm, bool isanormprovided, double anorm, ref double rc) inline static private
rmatrixestimatenorm() [2/2]
static void alglib.rcond.rmatrixestimatenorm (int n, ref double[] v, ref double[] x, ref int[] isgn, ref double est, ref int kase) inline static private
cmatrixestimatenorm() [2/2]
static void alglib.rcond.cmatrixestimatenorm (int n, ref complex[] v, ref complex[] x, ref double est, ref int kase, ref int[] isave, ref double[] rsave) inline static private
internalcomplexrcondscsum1() [2/2]
static double alglib.rcond.internalcomplexrcondscsum1 (complex[] x, int n) inline static private
internalcomplexrcondicmax1() [2/2]
static int alglib.rcond.internalcomplexrcondicmax1 (complex[] x, int n) inline static private
internalcomplexrcondsaveall() [2/2]
static void alglib.rcond.internalcomplexrcondsaveall (ref int[] isave, ref double[] rsave, ref int i, ref int iter, ref int j, ref int jlast, ref int jump, ref double absxi, ref double altsgn, ref double estold, ref double temp) inline static private
internalcomplexrcondloadall() [2/2]
static void alglib.rcond.internalcomplexrcondloadall (ref int[] isave, ref double[] rsave, ref int i, ref int iter, ref int j, ref int jlast, ref int jump, ref double absxi, ref double altsgn, ref double estold, ref double temp) inline static private
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/linalg.cs