Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DLAMCH Class Reference
DotNumerics.LinearAlgebra.CSLapack.DLAMCH Class Reference
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DLAMCH (LSAME lsame, DLAMC2 dlamc2)
DLAMCH ()
double Run (string CMACH)
Private Attributes
LSAME _lsame
DLAMC2 _dlamc2
bool FIRST = false
double BASE = 0
double EMAX = 0
double EMIN = 0
double EPS = 0
double PREC = 0
double RMAX = 0
double RMIN = 0
double RND = 0
double SFMIN = 0
double T = 0
Static Private Attributes
const double ONE = 1.0E+0
const double ZERO = 0.0E+0
Detailed Description
– LAPACK auxiliary routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
DLAMCH determines double precision machine parameters.
/summary>
Constructor & Destructor Documentation
DLAMCH() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DLAMCH.DLAMCH (LSAME lsame, DLAMC2 dlamc2) inline
References DotNumerics.LinearAlgebra.CSLapack.DLAMCH.FIRST.
DLAMCH() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DLAMCH.DLAMCH () inline
References DotNumerics.LinearAlgebra.CSLapack.DLAMCH.FIRST.
Member Function Documentation
Run()
double DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run (string CMACH) inline
Purpose
DLAMCH determines double precision machine parameters.
/summary>
Parameters
CMACH (input) CHARACTER*1 Specifies the value to be returned by DLAMCH: = 'E' or 'e', DLAMCH := eps = 'S' or 's , DLAMCH := sfmin = 'B' or 'b', DLAMCH := base = 'P' or 'p', DLAMCH := eps*base = 'N' or 'n', DLAMCH := t = 'R' or 'r', DLAMCH := rnd = 'M' or 'm', DLAMCH := emin = 'U' or 'u', DLAMCH := rmin = 'L' or 'l', DLAMCH := emax = 'O' or 'o', DLAMCH := rmax
where
eps = relative machine precision sfmin = safe minimum, such that 1/sfmin does not overflow base = base of the machine prec = eps*base t = number of (base) digits in the mantissa rnd = 1.0 when rounding occurs in addition, 0.0 otherwise emin = minimum exponent before (gradual) underflow rmin = underflow threshold - base**(emin-1) emax = largest exponent before overflow rmax = overflow threshold - (base**emax)*(1-eps) /param>
References DotNumerics.LinearAlgebra.CSLapack.DLAMCH.BASE, DotNumerics.LinearAlgebra.CSLapack.DLAMCH.EMAX, DotNumerics.LinearAlgebra.CSLapack.DLAMCH.EMIN, DotNumerics.LinearAlgebra.CSLapack.DLAMCH.EPS, DotNumerics.LinearAlgebra.CSLapack.DLAMCH.FIRST, DotNumerics.LinearAlgebra.CSLapack.DLAMCH.ONE, DotNumerics.LinearAlgebra.CSLapack.DLAMCH.PREC, DotNumerics.LinearAlgebra.CSLapack.DLAMCH.RMAX, DotNumerics.LinearAlgebra.CSLapack.DLAMCH.RMIN, DotNumerics.LinearAlgebra.CSLapack.DLAMCH.RND, DotNumerics.LinearAlgebra.CSLapack.LSAME.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMC2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.SFMIN, DotNumerics.LinearAlgebra.CSLapack.DLAMCH.T, and DotNumerics.LinearAlgebra.CSLapack.DLAMCH.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DRSCL.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTERF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASQ6.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARTG.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASV2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLANV2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGETF2.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQPF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASQ2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED6.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQP2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASQ1.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASCL.Run(), DotNumerics.LinearAlgebra.CSLapack.DDISNA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED4.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBAL.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD4.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAZQ3.Run(), DotNumerics.LinearAlgebra.CSLapack.DTRCON.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAEXC.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAIC1.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQPS.Run(), DotNumerics.LinearAlgebra.CSLapack.DSBEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLATRS.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAHQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR5.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED8.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALSD.Run(), DotNumerics.LinearAlgebra.CSLapack.DTREVC.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEDC.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASY2.Run(), DotNumerics.LinearAlgebra.CSLapack.DBDSQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELS.Run(), DotNumerics.LinearAlgebra.CSLapack.DSBEVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD7.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASD2.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYEVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DBDSDC.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR3.Run(), DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELSY.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELSD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run(), DotNumerics.LinearAlgebra.CSLapack.DLALN2.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGGSVD.Run().
Member Data Documentation
_lsame
LSAME DotNumerics.LinearAlgebra.CSLapack.DLAMCH._lsame private
_dlamc2
DLAMC2 DotNumerics.LinearAlgebra.CSLapack.DLAMCH._dlamc2 private
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DLAMCH.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run().
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DLAMCH.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run().
FIRST
bool DotNumerics.LinearAlgebra.CSLapack.DLAMCH.FIRST = false private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAMCH.DLAMCH(), and DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run().
BASE
double DotNumerics.LinearAlgebra.CSLapack.DLAMCH.BASE = 0 private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run().
EMAX
double DotNumerics.LinearAlgebra.CSLapack.DLAMCH.EMAX = 0 private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run().
EMIN
double DotNumerics.LinearAlgebra.CSLapack.DLAMCH.EMIN = 0 private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run().
EPS
double DotNumerics.LinearAlgebra.CSLapack.DLAMCH.EPS = 0 private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run().
PREC
double DotNumerics.LinearAlgebra.CSLapack.DLAMCH.PREC = 0 private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run().
RMAX
double DotNumerics.LinearAlgebra.CSLapack.DLAMCH.RMAX = 0 private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run().
RMIN
double DotNumerics.LinearAlgebra.CSLapack.DLAMCH.RMIN = 0 private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run().
RND
double DotNumerics.LinearAlgebra.CSLapack.DLAMCH.RND = 0 private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run().
SFMIN
double DotNumerics.LinearAlgebra.CSLapack.DLAMCH.SFMIN = 0 private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run().
T
double DotNumerics.LinearAlgebra.CSLapack.DLAMCH.T = 0 private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dlamch.cs