Doc: IGLib EXTENDED: Approximation.MainFormNeuralApproximation Class Reference
Approximation.MainFormNeuralApproximation Class Reference
Summary description for Form1.
Public Member Functions
MainFormNeuralApproximation ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
delegate void SetTextCallback (System.Windows.Forms.Control control, string text)
void SetText (System.Windows.Forms.Control control, string text)
void MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e)
void UpdateSettings ()
void ChooseFile ()
void loadDataButton_Click (object sender, System.EventArgs e)
void UpdateDataListView ()
delegate void EnableCallback (bool enable)
void EnableControls (bool enable)
void startButton_Click (object sender, System.EventArgs e)
void stopButton_Click (object sender, System.EventArgs e)
void SearchSolution ()
Static Private Member Functions
static void FormMain ()
The main entry point for the application.
Private Attributes
System.Windows.Forms.GroupBox groupBox1
System.Windows.Forms.ListView dataList
System.Windows.Forms.Button loadDataButton
System.Windows.Forms.ColumnHeader xColumnHeader
System.Windows.Forms.ColumnHeader yColumnHeader
System.Windows.Forms.OpenFileDialog openFileDialog
System.Windows.Forms.GroupBox groupBox2
AForge.Controls.Chart chart
System.Windows.Forms.GroupBox groupBox3
System.Windows.Forms.TextBox momentumBox
System.Windows.Forms.Label label6
System.Windows.Forms.TextBox alphaBox
System.Windows.Forms.Label label2
System.Windows.Forms.TextBox learningRateBox
System.Windows.Forms.Label label1
System.Windows.Forms.Label label8
System.Windows.Forms.TextBox iterationsBox
System.Windows.Forms.Label label10
System.Windows.Forms.Label label9
System.Windows.Forms.GroupBox groupBox4
System.Windows.Forms.TextBox currentErrorBox
System.Windows.Forms.Label label3
System.Windows.Forms.TextBox currentIterationBox
System.Windows.Forms.Label label5
System.Windows.Forms.Button stopButton
System.Windows.Forms.Button startButton
System.Windows.Forms.Label label4
System.Windows.Forms.TextBox neuronsBox
System.ComponentModel.Container components = null
Required designer variable.
double[,] data = null
double learningRate = 0.1
double momentum = 0.0
double sigmoidAlphaValue = 2.0
int neuronsInFirstLayer = 20
int iterations = 1000
Thread workerThread = null
volatile bool needToStop = false
string _filePath = "../../data/aforge/"
bool _fileChosen = false
Detailed Description
Summary description for Form1.
Constructor & Destructor Documentation
MainFormNeuralApproximation()
Approximation.MainFormNeuralApproximation.MainFormNeuralApproximation () inline
References AForge.Controls.Chart.AddDataSeries(), Approximation.MainFormNeuralApproximation.chart, Approximation.MainFormNeuralApproximation.InitializeComponent(), and Approximation.MainFormNeuralApproximation.UpdateSettings().
Referenced by Approximation.MainFormNeuralApproximation.FormMain().
Member Function Documentation
Dispose()
override void Approximation.MainFormNeuralApproximation.Dispose (bool disposing) inline protected
Clean up any resources being used.
References Approximation.MainFormNeuralApproximation.components.
InitializeComponent()
void Approximation.MainFormNeuralApproximation.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by Approximation.MainFormNeuralApproximation.MainFormNeuralApproximation().
FormMain()
static void Approximation.MainFormNeuralApproximation.FormMain () inline static private
The main entry point for the application.
References Approximation.MainFormNeuralApproximation.MainFormNeuralApproximation().
SetTextCallback()
delegate void Approximation.MainFormNeuralApproximation.SetTextCallback (System.Windows.Forms.Control control, string text) private
Referenced by Approximation.MainFormNeuralApproximation.SetText().
SetText()
void Approximation.MainFormNeuralApproximation.SetText (System.Windows.Forms.Control control, string text) inline private
References Approximation.MainFormNeuralApproximation.SetTextCallback().
Referenced by Approximation.MainFormNeuralApproximation.SearchSolution().
MainForm_Closing()
void Approximation.MainFormNeuralApproximation.MainForm_Closing (object sender, System.ComponentModel.CancelEventArgs e) inline private
References Approximation.MainFormNeuralApproximation.needToStop, and Approximation.MainFormNeuralApproximation.workerThread.
UpdateSettings()
void Approximation.MainFormNeuralApproximation.UpdateSettings () inline private
References Approximation.MainFormNeuralApproximation.alphaBox, Approximation.MainFormNeuralApproximation.iterations, Approximation.MainFormNeuralApproximation.iterationsBox, Approximation.MainFormNeuralApproximation.learningRate, Approximation.MainFormNeuralApproximation.learningRateBox, Approximation.MainFormNeuralApproximation.momentum, Approximation.MainFormNeuralApproximation.momentumBox, Approximation.MainFormNeuralApproximation.neuronsBox, Approximation.MainFormNeuralApproximation.neuronsInFirstLayer, and Approximation.MainFormNeuralApproximation.sigmoidAlphaValue.
Referenced by Approximation.MainFormNeuralApproximation.MainFormNeuralApproximation(), and Approximation.MainFormNeuralApproximation.startButton_Click().
ChooseFile()
void Approximation.MainFormNeuralApproximation.ChooseFile () inline private
References Approximation.MainFormNeuralApproximation._fileChosen, and Approximation.MainFormNeuralApproximation._filePath.
Referenced by Approximation.MainFormNeuralApproximation.loadDataButton_Click().
loadDataButton_Click()
void Approximation.MainFormNeuralApproximation.loadDataButton_Click (object sender, System.EventArgs e) inline private
References Approximation.MainFormNeuralApproximation._fileChosen, Approximation.MainFormNeuralApproximation._filePath, Approximation.MainFormNeuralApproximation.chart, Approximation.MainFormNeuralApproximation.ChooseFile(), Approximation.MainFormNeuralApproximation.data, AForge.Controls.Chart.RangeX, Approximation.MainFormNeuralApproximation.startButton, Approximation.MainFormNeuralApproximation.UpdateDataListView(), and AForge.Controls.Chart.UpdateDataSeries().
UpdateDataListView()
void Approximation.MainFormNeuralApproximation.UpdateDataListView () inline private
References Approximation.MainFormNeuralApproximation.data, and Approximation.MainFormNeuralApproximation.dataList.
Referenced by Approximation.MainFormNeuralApproximation.loadDataButton_Click().
EnableCallback()
delegate void Approximation.MainFormNeuralApproximation.EnableCallback (bool enable) private
Referenced by Approximation.MainFormNeuralApproximation.EnableControls().
EnableControls()
void Approximation.MainFormNeuralApproximation.EnableControls (bool enable) inline private
References Approximation.MainFormNeuralApproximation.alphaBox, Approximation.MainFormNeuralApproximation.EnableCallback(), Approximation.MainFormNeuralApproximation.iterationsBox, Approximation.MainFormNeuralApproximation.learningRateBox, Approximation.MainFormNeuralApproximation.loadDataButton, Approximation.MainFormNeuralApproximation.momentumBox, Approximation.MainFormNeuralApproximation.neuronsBox, Approximation.MainFormNeuralApproximation.startButton, and Approximation.MainFormNeuralApproximation.stopButton.
Referenced by Approximation.MainFormNeuralApproximation.SearchSolution(), and Approximation.MainFormNeuralApproximation.startButton_Click().
startButton_Click()
void Approximation.MainFormNeuralApproximation.startButton_Click (object sender, System.EventArgs e) inline private
References Approximation.MainFormNeuralApproximation.alphaBox, Approximation.MainFormNeuralApproximation.EnableControls(), Approximation.MainFormNeuralApproximation.iterations, Approximation.MainFormNeuralApproximation.iterationsBox, Approximation.MainFormNeuralApproximation.learningRate, Approximation.MainFormNeuralApproximation.learningRateBox, Approximation.MainFormNeuralApproximation.momentum, Approximation.MainFormNeuralApproximation.momentumBox, Approximation.MainFormNeuralApproximation.needToStop, Approximation.MainFormNeuralApproximation.neuronsBox, Approximation.MainFormNeuralApproximation.neuronsInFirstLayer, Approximation.MainFormNeuralApproximation.SearchSolution(), Approximation.MainFormNeuralApproximation.sigmoidAlphaValue, Approximation.MainFormNeuralApproximation.UpdateSettings(), and Approximation.MainFormNeuralApproximation.workerThread.
stopButton_Click()
void Approximation.MainFormNeuralApproximation.stopButton_Click (object sender, System.EventArgs e) inline private
References Approximation.MainFormNeuralApproximation.needToStop, and Approximation.MainFormNeuralApproximation.workerThread.
SearchSolution()
void Approximation.MainFormNeuralApproximation.SearchSolution () inline private
References Approximation.MainFormNeuralApproximation.chart, AForge.Neuro.Network.Compute(), Approximation.MainFormNeuralApproximation.currentErrorBox, Approximation.MainFormNeuralApproximation.currentIterationBox, Approximation.MainFormNeuralApproximation.data, Approximation.MainFormNeuralApproximation.EnableControls(), Approximation.MainFormNeuralApproximation.iterations, AForge.Neuro.Learning.BackPropagationLearning.LearningRate, Approximation.MainFormNeuralApproximation.learningRate, AForge.DoubleRange.Length, AForge.DoubleRange.Min, AForge.Neuro.Learning.BackPropagationLearning.Momentum, Approximation.MainFormNeuralApproximation.momentum, Approximation.MainFormNeuralApproximation.needToStop, Approximation.MainFormNeuralApproximation.neuronsInFirstLayer, AForge.Controls.Chart.RangeX, AForge.Controls.Chart.RangeY, AForge.Neuro.Learning.BackPropagationLearning.RunEpoch(), Approximation.MainFormNeuralApproximation.SetText(), Approximation.MainFormNeuralApproximation.sigmoidAlphaValue, and AForge.Controls.Chart.UpdateDataSeries().
Referenced by Approximation.MainFormNeuralApproximation.startButton_Click().
Member Data Documentation
groupBox1
System.Windows.Forms.GroupBox Approximation.MainFormNeuralApproximation.groupBox1 private
dataList
System.Windows.Forms.ListView Approximation.MainFormNeuralApproximation.dataList private
Referenced by Approximation.MainFormNeuralApproximation.UpdateDataListView().
loadDataButton
System.Windows.Forms.Button Approximation.MainFormNeuralApproximation.loadDataButton private
Referenced by Approximation.MainFormNeuralApproximation.EnableControls().
xColumnHeader
System.Windows.Forms.ColumnHeader Approximation.MainFormNeuralApproximation.xColumnHeader private
yColumnHeader
System.Windows.Forms.ColumnHeader Approximation.MainFormNeuralApproximation.yColumnHeader private
openFileDialog
System.Windows.Forms.OpenFileDialog Approximation.MainFormNeuralApproximation.openFileDialog private
groupBox2
System.Windows.Forms.GroupBox Approximation.MainFormNeuralApproximation.groupBox2 private
chart
AForge.Controls.Chart Approximation.MainFormNeuralApproximation.chart private
Referenced by Approximation.MainFormNeuralApproximation.loadDataButton_Click(), Approximation.MainFormNeuralApproximation.MainFormNeuralApproximation(), and Approximation.MainFormNeuralApproximation.SearchSolution().
groupBox3
System.Windows.Forms.GroupBox Approximation.MainFormNeuralApproximation.groupBox3 private
momentumBox
System.Windows.Forms.TextBox Approximation.MainFormNeuralApproximation.momentumBox private
Referenced by Approximation.MainFormNeuralApproximation.EnableControls(), Approximation.MainFormNeuralApproximation.startButton_Click(), and Approximation.MainFormNeuralApproximation.UpdateSettings().
label6
System.Windows.Forms.Label Approximation.MainFormNeuralApproximation.label6 private
alphaBox
System.Windows.Forms.TextBox Approximation.MainFormNeuralApproximation.alphaBox private
Referenced by Approximation.MainFormNeuralApproximation.EnableControls(), Approximation.MainFormNeuralApproximation.startButton_Click(), and Approximation.MainFormNeuralApproximation.UpdateSettings().
label2
System.Windows.Forms.Label Approximation.MainFormNeuralApproximation.label2 private
learningRateBox
System.Windows.Forms.TextBox Approximation.MainFormNeuralApproximation.learningRateBox private
Referenced by Approximation.MainFormNeuralApproximation.EnableControls(), Approximation.MainFormNeuralApproximation.startButton_Click(), and Approximation.MainFormNeuralApproximation.UpdateSettings().
label1
System.Windows.Forms.Label Approximation.MainFormNeuralApproximation.label1 private
label8
System.Windows.Forms.Label Approximation.MainFormNeuralApproximation.label8 private
iterationsBox
System.Windows.Forms.TextBox Approximation.MainFormNeuralApproximation.iterationsBox private
Referenced by Approximation.MainFormNeuralApproximation.EnableControls(), Approximation.MainFormNeuralApproximation.startButton_Click(), and Approximation.MainFormNeuralApproximation.UpdateSettings().
label10
System.Windows.Forms.Label Approximation.MainFormNeuralApproximation.label10 private
label9
System.Windows.Forms.Label Approximation.MainFormNeuralApproximation.label9 private
groupBox4
System.Windows.Forms.GroupBox Approximation.MainFormNeuralApproximation.groupBox4 private
currentErrorBox
System.Windows.Forms.TextBox Approximation.MainFormNeuralApproximation.currentErrorBox private
Referenced by Approximation.MainFormNeuralApproximation.SearchSolution().
label3
System.Windows.Forms.Label Approximation.MainFormNeuralApproximation.label3 private
currentIterationBox
System.Windows.Forms.TextBox Approximation.MainFormNeuralApproximation.currentIterationBox private
Referenced by Approximation.MainFormNeuralApproximation.SearchSolution().
label5
System.Windows.Forms.Label Approximation.MainFormNeuralApproximation.label5 private
stopButton
System.Windows.Forms.Button Approximation.MainFormNeuralApproximation.stopButton private
Referenced by Approximation.MainFormNeuralApproximation.EnableControls().
startButton
System.Windows.Forms.Button Approximation.MainFormNeuralApproximation.startButton private
Referenced by Approximation.MainFormNeuralApproximation.EnableControls(), and Approximation.MainFormNeuralApproximation.loadDataButton_Click().
label4
System.Windows.Forms.Label Approximation.MainFormNeuralApproximation.label4 private
neuronsBox
System.Windows.Forms.TextBox Approximation.MainFormNeuralApproximation.neuronsBox private
Referenced by Approximation.MainFormNeuralApproximation.EnableControls(), Approximation.MainFormNeuralApproximation.startButton_Click(), and Approximation.MainFormNeuralApproximation.UpdateSettings().
components
System.ComponentModel.Container Approximation.MainFormNeuralApproximation.components = null private
Required designer variable.
Referenced by Approximation.MainFormNeuralApproximation.Dispose().
data
double [,] Approximation.MainFormNeuralApproximation.data = null private
Referenced by Approximation.MainFormNeuralApproximation.loadDataButton_Click(), Approximation.MainFormNeuralApproximation.SearchSolution(), and Approximation.MainFormNeuralApproximation.UpdateDataListView().
learningRate
double Approximation.MainFormNeuralApproximation.learningRate = 0.1 private
Referenced by Approximation.MainFormNeuralApproximation.SearchSolution(), Approximation.MainFormNeuralApproximation.startButton_Click(), and Approximation.MainFormNeuralApproximation.UpdateSettings().
momentum
double Approximation.MainFormNeuralApproximation.momentum = 0.0 private
Referenced by Approximation.MainFormNeuralApproximation.SearchSolution(), Approximation.MainFormNeuralApproximation.startButton_Click(), and Approximation.MainFormNeuralApproximation.UpdateSettings().
sigmoidAlphaValue
double Approximation.MainFormNeuralApproximation.sigmoidAlphaValue = 2.0 private
Referenced by Approximation.MainFormNeuralApproximation.SearchSolution(), Approximation.MainFormNeuralApproximation.startButton_Click(), and Approximation.MainFormNeuralApproximation.UpdateSettings().
neuronsInFirstLayer
int Approximation.MainFormNeuralApproximation.neuronsInFirstLayer = 20 private
Referenced by Approximation.MainFormNeuralApproximation.SearchSolution(), Approximation.MainFormNeuralApproximation.startButton_Click(), and Approximation.MainFormNeuralApproximation.UpdateSettings().
iterations
int Approximation.MainFormNeuralApproximation.iterations = 1000 private
Referenced by Approximation.MainFormNeuralApproximation.SearchSolution(), Approximation.MainFormNeuralApproximation.startButton_Click(), and Approximation.MainFormNeuralApproximation.UpdateSettings().
workerThread
Thread Approximation.MainFormNeuralApproximation.workerThread = null private
Referenced by Approximation.MainFormNeuralApproximation.MainForm_Closing(), Approximation.MainFormNeuralApproximation.startButton_Click(), and Approximation.MainFormNeuralApproximation.stopButton_Click().
needToStop
volatile bool Approximation.MainFormNeuralApproximation.needToStop = false private
Referenced by Approximation.MainFormNeuralApproximation.MainForm_Closing(), Approximation.MainFormNeuralApproximation.SearchSolution(), Approximation.MainFormNeuralApproximation.startButton_Click(), and Approximation.MainFormNeuralApproximation.stopButton_Click().
_filePath
string Approximation.MainFormNeuralApproximation._filePath = "../../data/aforge/" private
Referenced by Approximation.MainFormNeuralApproximation.ChooseFile(), and Approximation.MainFormNeuralApproximation.loadDataButton_Click().
_fileChosen
bool Approximation.MainFormNeuralApproximation._fileChosen = false private
Referenced by Approximation.MainFormNeuralApproximation.ChooseFile(), and Approximation.MainFormNeuralApproximation.loadDataButton_Click().
The documentation for this class was generated from the following file:
shelldev/extensions_shell/shell/TestApp/Neuro/Approximation/MainFormNeuralApproximation.cs