Doc: IGLib EXTENDED: alglib.polint Class Reference
alglib.polint Class Reference
Static Public Member Functions
static void polynomialbar2cheb (ratint.barycentricinterpolant p, double a, double b, ref double[] t)
static void polynomialcheb2bar (double[] t, int n, double a, double b, ratint.barycentricinterpolant p)
static void polynomialbar2pow (ratint.barycentricinterpolant p, double c, double s, ref double[] a)
static void polynomialpow2bar (double[] a, int n, double c, double s, ratint.barycentricinterpolant p)
static void polynomialbuild (double[] x, double[] y, int n, ratint.barycentricinterpolant p)
static void polynomialbuildeqdist (double a, double b, double[] y, int n, ratint.barycentricinterpolant p)
static void polynomialbuildcheb1 (double a, double b, double[] y, int n, ratint.barycentricinterpolant p)
static void polynomialbuildcheb2 (double a, double b, double[] y, int n, ratint.barycentricinterpolant p)
static double polynomialcalceqdist (double a, double b, double[] f, int n, double t)
static double polynomialcalccheb1 (double a, double b, double[] f, int n, double t)
static double polynomialcalccheb2 (double a, double b, double[] f, int n, double t)
static void polynomialbar2cheb (ratint.barycentricinterpolant p, double a, double b, ref double[] t)
static void polynomialcheb2bar (double[] t, int n, double a, double b, ratint.barycentricinterpolant p)
static void polynomialbar2pow (ratint.barycentricinterpolant p, double c, double s, ref double[] a)
static void polynomialpow2bar (double[] a, int n, double c, double s, ratint.barycentricinterpolant p)
static void polynomialbuild (double[] x, double[] y, int n, ratint.barycentricinterpolant p)
static void polynomialbuildeqdist (double a, double b, double[] y, int n, ratint.barycentricinterpolant p)
static void polynomialbuildcheb1 (double a, double b, double[] y, int n, ratint.barycentricinterpolant p)
static void polynomialbuildcheb2 (double a, double b, double[] y, int n, ratint.barycentricinterpolant p)
static double polynomialcalceqdist (double a, double b, double[] f, int n, double t)
static double polynomialcalccheb1 (double a, double b, double[] f, int n, double t)
static double polynomialcalccheb2 (double a, double b, double[] f, int n, double t)
Member Function Documentation
polynomialbar2cheb() [1/2]
static void alglib.polint.polynomialbar2cheb (ratint.barycentricinterpolant p, double a, double b, ref double[] t) inline static
References alglib.ap.assert(), alglib.ratint.barycentriccalc(), and alglib.math.isfinite().
Referenced by alglib.polynomialbar2cheb(), and alglib.testpolintunit.testpolint().
polynomialcheb2bar() [1/2]
static void alglib.polint.polynomialcheb2bar (double[] t, int n, double a, double b, ratint.barycentricinterpolant p) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), and alglib.polint.polynomialbuildcheb1().
Referenced by alglib.polynomialcheb2bar(), and alglib.testpolintunit.testpolint().
polynomialbar2pow() [1/2]
static void alglib.polint.polynomialbar2pow (ratint.barycentricinterpolant p, double c, double s, ref double[] a) inline static
References alglib.ap.assert(), alglib.ratint.barycentriccalc(), and alglib.math.isfinite().
Referenced by alglib.polynomialbar2pow(), and alglib.testpolintunit.testpolint().
polynomialpow2bar() [1/2]
static void alglib.polint.polynomialpow2bar (double[] a, int n, double c, double s, ratint.barycentricinterpolant p) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), and alglib.polint.polynomialbuildcheb1().
Referenced by alglib.polynomialpow2bar(), and alglib.testpolintunit.testpolint().
polynomialbuild() [1/2]
static void alglib.polint.polynomialbuild (double[] x, double[] y, int n, ratint.barycentricinterpolant p) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.ratint.barycentricbuildxyw(), alglib.apserv.isfinitevector(), and alglib.tsort.tagsortfastr().
Referenced by alglib.polynomialbuild(), alglib.testpolintunit.testpolint(), and alglib.testlsfitunit.testpolynomialfitting().
polynomialbuildeqdist() [1/2]
static void alglib.polint.polynomialbuildeqdist (double a, double b, double[] y, int n, ratint.barycentricinterpolant p) inline static
References alglib.ap.assert(), alglib.ratint.barycentricbuildxyw(), alglib.math.isfinite(), and alglib.apserv.isfinitevector().
Referenced by alglib.polynomialbuildeqdist(), and alglib.testpolintunit.testpolint().
polynomialbuildcheb1() [1/2]
static void alglib.polint.polynomialbuildcheb1 (double a, double b, double[] y, int n, ratint.barycentricinterpolant p) inline static
References alglib.ap.assert(), alglib.ratint.barycentricbuildxyw(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), and alglib.math.sqr().
Referenced by alglib.polynomialbuildcheb1(), alglib.polint.polynomialcheb2bar(), alglib.polint.polynomialpow2bar(), and alglib.testpolintunit.testpolint().
polynomialbuildcheb2() [1/2]
static void alglib.polint.polynomialbuildcheb2 (double a, double b, double[] y, int n, ratint.barycentricinterpolant p) inline static
References alglib.ap.assert(), alglib.ratint.barycentricbuildxyw(), alglib.math.isfinite(), and alglib.apserv.isfinitevector().
Referenced by alglib.polynomialbuildcheb2(), and alglib.testpolintunit.testpolint().
polynomialcalceqdist() [1/2]
static double alglib.polint.polynomialcalceqdist (double a, double b, double[] f, int n, double t) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), and alglib.math.minrealnumber.
Referenced by alglib.polynomialcalceqdist(), and alglib.testpolintunit.testpolint().
polynomialcalccheb1() [1/2]
static double alglib.polint.polynomialcalccheb1 (double a, double b, double[] f, int n, double t) inline static
References alglib.ap.assert(), alglib.beta(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), alglib.math.minrealnumber, and alglib.math.sqr().
Referenced by alglib.polynomialcalccheb1(), and alglib.testpolintunit.testpolint().
polynomialcalccheb2() [1/2]
static double alglib.polint.polynomialcalccheb2 (double a, double b, double[] f, int n, double t) inline static
References alglib.ap.assert(), alglib.beta(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), alglib.math.minrealnumber, and alglib.math.sqr().
Referenced by alglib.polynomialcalccheb2(), and alglib.testpolintunit.testpolint().
polynomialbar2cheb() [2/2]
static void alglib.polint.polynomialbar2cheb (ratint.barycentricinterpolant p, double a, double b, ref double[] t) inline static
References alglib.ap.assert(), alglib.ratint.barycentriccalc(), and alglib.math.isfinite().
polynomialcheb2bar() [2/2]
static void alglib.polint.polynomialcheb2bar (double[] t, int n, double a, double b, ratint.barycentricinterpolant p) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), and alglib.polint.polynomialbuildcheb1().
polynomialbar2pow() [2/2]
static void alglib.polint.polynomialbar2pow (ratint.barycentricinterpolant p, double c, double s, ref double[] a) inline static
References alglib.ap.assert(), alglib.ratint.barycentriccalc(), and alglib.math.isfinite().
polynomialpow2bar() [2/2]
static void alglib.polint.polynomialpow2bar (double[] a, int n, double c, double s, ratint.barycentricinterpolant p) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), and alglib.polint.polynomialbuildcheb1().
polynomialbuild() [2/2]
static void alglib.polint.polynomialbuild (double[] x, double[] y, int n, ratint.barycentricinterpolant p) inline static
References alglib.apserv.aredistinct(), alglib.ap.assert(), alglib.ratint.barycentricbuildxyw(), alglib.apserv.isfinitevector(), and alglib.tsort.tagsortfastr().
polynomialbuildeqdist() [2/2]
static void alglib.polint.polynomialbuildeqdist (double a, double b, double[] y, int n, ratint.barycentricinterpolant p) inline static
References alglib.ap.assert(), alglib.ratint.barycentricbuildxyw(), alglib.math.isfinite(), and alglib.apserv.isfinitevector().
polynomialbuildcheb1() [2/2]
static void alglib.polint.polynomialbuildcheb1 (double a, double b, double[] y, int n, ratint.barycentricinterpolant p) inline static
References alglib.ap.assert(), alglib.ratint.barycentricbuildxyw(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), and alglib.math.sqr().
polynomialbuildcheb2() [2/2]
static void alglib.polint.polynomialbuildcheb2 (double a, double b, double[] y, int n, ratint.barycentricinterpolant p) inline static
References alglib.ap.assert(), alglib.ratint.barycentricbuildxyw(), alglib.math.isfinite(), and alglib.apserv.isfinitevector().
polynomialcalceqdist() [2/2]
static double alglib.polint.polynomialcalceqdist (double a, double b, double[] f, int n, double t) inline static
References alglib.ap.assert(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), and alglib.math.minrealnumber.
polynomialcalccheb1() [2/2]
static double alglib.polint.polynomialcalccheb1 (double a, double b, double[] f, int n, double t) inline static
References alglib.ap.assert(), alglib.beta(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), alglib.math.minrealnumber, and alglib.math.sqr().
polynomialcalccheb2() [2/2]
static double alglib.polint.polynomialcalccheb2 (double a, double b, double[] f, int n, double t) inline static
References alglib.ap.assert(), alglib.beta(), alglib.math.isfinite(), alglib.apserv.isfinitevector(), alglib.math.minrealnumber, and alglib.math.sqr().
The documentation for this class was generated from the following file:
igtest/IGLibTestDev_Copy/00archive/alglib/alglib-3.6.0.csharp/src/interpolation.cs