Doc: IGLib EXTENDED: AForge.Imaging.Filters.BaseRotateFilter Class Reference
AForge.Imaging.Filters.BaseRotateFilter Class Reference
Base class for image rotation filters.
Public Member Functions
BaseRotateFilter (double angle)
Initializes a new instance of the BaseRotateFilter class.
BaseRotateFilter (double angle, bool keepSize)
Initializes a new instance of the BaseRotateFilter class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseTransformationFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
Protected Member Functions
override System.Drawing.Size CalculateNewImageSize (UnmanagedImage sourceData)
Calculates new image size.
Protected Member Functions inherited from AForge.Imaging.Filters.BaseTransformationFilter
abstract unsafe void ProcessFilter (UnmanagedImage sourceData, UnmanagedImage destinationData)
Process the filter on the specified image.
Protected Attributes
double angle
Rotation angle.
bool keepSize = false
Keep image size or not.
Color fillColor = Color.FromArgb(0, 0, 0)
Fill color.
Properties
double Angle [get, set]
Rotation angle, [0, 360].
bool KeepSize [get, set]
Keep image size or not.
Color FillColor [get, set]
Fill color.
Properties inherited from AForge.Imaging.Filters.BaseTransformationFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Detailed Description
Base class for image rotation filters.
The abstract class is the base class for all filters, which implement rotating algorithms.
Constructor & Destructor Documentation
BaseRotateFilter() [1/2]
AForge.Imaging.Filters.BaseRotateFilter.BaseRotateFilter (double angle) inline
Initializes a new instance of the BaseRotateFilter class.
Parameters
angle Rotation angle.
This constructor sets KeepSize property to false.
References AForge.Imaging.Filters.BaseRotateFilter.angle.
BaseRotateFilter() [2/2]
AForge.Imaging.Filters.BaseRotateFilter.BaseRotateFilter (double angle, bool keepSize) inline
Initializes a new instance of the BaseRotateFilter class.
Parameters
angle Rotation angle.
keepSize Keep image size or not.
References AForge.Imaging.Filters.BaseRotateFilter.angle, and AForge.Imaging.Filters.BaseRotateFilter.keepSize.
Member Function Documentation
CalculateNewImageSize()
override System.Drawing.Size AForge.Imaging.Filters.BaseRotateFilter.CalculateNewImageSize (UnmanagedImage sourceData) inline protected virtual
Calculates new image size.
Parameters
sourceData Source image data.
Returns
New image size - size of the destination image.
Implements AForge.Imaging.Filters.BaseTransformationFilter.
References AForge.Imaging.Filters.BaseRotateFilter.angle, AForge.Imaging.UnmanagedImage.Height, AForge.Imaging.Filters.BaseRotateFilter.keepSize, AForge.Imaging.Size, and AForge.Imaging.UnmanagedImage.Width.
Member Data Documentation
angle
double AForge.Imaging.Filters.BaseRotateFilter.angle protected
Rotation angle.
Referenced by AForge.Imaging.Filters.BaseRotateFilter.BaseRotateFilter(), AForge.Imaging.Filters.BaseRotateFilter.CalculateNewImageSize(), AForge.Imaging.Filters.RotateBilinear.ProcessFilter(), AForge.Imaging.Filters.RotateBicubic.ProcessFilter(), AForge.Imaging.Filters.RotateNearestNeighbor.ProcessFilter16bpc(), and AForge.Imaging.Filters.RotateNearestNeighbor.ProcessFilter8bpc().
keepSize
bool AForge.Imaging.Filters.BaseRotateFilter.keepSize = false protected
Keep image size or not.
Referenced by AForge.Imaging.Filters.BaseRotateFilter.BaseRotateFilter(), and AForge.Imaging.Filters.BaseRotateFilter.CalculateNewImageSize().
fillColor
Color AForge.Imaging.Filters.BaseRotateFilter.fillColor = Color.FromArgb(0, 0, 0) protected
Fill color.
Referenced by AForge.Imaging.Filters.RotateBilinear.ProcessFilter(), AForge.Imaging.Filters.RotateBicubic.ProcessFilter(), AForge.Imaging.Filters.RotateNearestNeighbor.ProcessFilter16bpc(), and AForge.Imaging.Filters.RotateNearestNeighbor.ProcessFilter8bpc().
Property Documentation
Angle
double AForge.Imaging.Filters.BaseRotateFilter.Angle get set
Rotation angle, [0, 360].
KeepSize
bool AForge.Imaging.Filters.BaseRotateFilter.KeepSize get set
Keep image size or not.
The property determines if source image's size will be kept as it is or not. If the value is set to false, then the new image will have new dimension according to rotation angle. If the valus is set to true, then the new image will have the same size, which means that some parts of the image may be clipped because of rotation.
FillColor
Color AForge.Imaging.Filters.BaseRotateFilter.FillColor get set
Fill color.
The fill color is used to fill areas of destination image, which don't have corresponsing pixels in source image.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/Base classes/BaseRotateFilter.cs