Doc: IGLib EXTENDED: AForge.Genetic.IGPGene Interface Reference
AForge.Genetic.IGPGene Interface Reference
Genetic Programming's gene interface.
Public Member Functions
IGPGene Clone ()
Clone gene.
void Generate ()
Randomize gene with random type and value.
void Generate (GPGeneType type)
Randomize gene with random value.
IGPGene CreateNew ()
Creates new gene with random type and value.
IGPGene CreateNew (GPGeneType type)
Creates new gene with certain type and random value.
Properties
GPGeneType GeneType [get]
Gene type.
int ArgumentsCount [get]
Arguments count.
int MaxArgumentsCount [get]
Maximum arguments count.
Detailed Description
Genetic Programming's gene interface.
This is a gene interface, which is used for building chromosomes in Genetic Programming (GP) and Gene Expression Programming (GEP).
Member Function Documentation
Clone()
IGPGene AForge.Genetic.IGPGene.Clone ()
Clone gene.
The method clones gene returning the exact copy of it.
Implemented in AForge.Genetic.ExtendedGeneFunction, and AForge.Genetic.SimpleGeneFunction.
Referenced by AForge.Genetic.GPTreeNode.Clone(), AForge.Genetic.GPTreeChromosome.CreateNew(), AForge.Genetic.GEPChromosome.GEPChromosome(), AForge.Genetic.GPTreeChromosome.GPTreeChromosome(), AForge.Genetic.GEPChromosome.TransposeIS(), and AForge.Genetic.GEPChromosome.TransposeRoot().
Generate() [1/2]
void AForge.Genetic.IGPGene.Generate ()
Randomize gene with random type and value.
The method randomizes a gene, setting its type and value randomly.
Implemented in AForge.Genetic.ExtendedGeneFunction, and AForge.Genetic.SimpleGeneFunction.
Referenced by AForge.Genetic.GPTreeChromosome.Generate(), AForge.Genetic.GEPChromosome.Generate(), AForge.Genetic.GPTreeChromosome.Mutate(), AForge.Genetic.GEPChromosome.MutateGene(), and AForge.Genetic.GPTreeChromosome.Trim().
Generate() [2/2]
void AForge.Genetic.IGPGene.Generate (GPGeneType type)
Randomize gene with random value.
Parameters
type Gene type to set.
The method randomizes a gene, setting its value randomly, but type is set to the specified one.
Implemented in AForge.Genetic.ExtendedGeneFunction, and AForge.Genetic.SimpleGeneFunction.
CreateNew() [1/2]
IGPGene AForge.Genetic.IGPGene.CreateNew ()
Creates new gene with random type and value.
The method creates new randomly initialized gene . The method is useful as factory method for those classes, which work with gene's interface, but not with particular gene class.
Implemented in AForge.Genetic.ExtendedGeneFunction, and AForge.Genetic.SimpleGeneFunction.
Referenced by AForge.Genetic.GEPChromosome.Generate(), and AForge.Genetic.GPTreeChromosome.Generate().
CreateNew() [2/2]
IGPGene AForge.Genetic.IGPGene.CreateNew (GPGeneType type)
Creates new gene with certain type and random value.
Parameters
type Gene type to create.
The method creates new gene with specified type, but random value. The method is useful as factory method for those classes, which work with gene's interface, but not with particular gene class.
Implemented in AForge.Genetic.ExtendedGeneFunction, and AForge.Genetic.SimpleGeneFunction.
Property Documentation
GeneType
GPGeneType AForge.Genetic.IGPGene.GeneType get
Gene type.
The property represents type of a gene - function, argument, etc.
Referenced by AForge.Genetic.GPTreeChromosome.Mutate().
ArgumentsCount
int AForge.Genetic.IGPGene.ArgumentsCount get
Arguments count.
Arguments count of a particular function gene.
Referenced by AForge.Genetic.GPTreeChromosome.Crossover(), AForge.Genetic.GPTreeChromosome.Generate(), AForge.Genetic.GEPChromosome.GetTree(), AForge.Genetic.GPTreeChromosome.Mutate(), and AForge.Genetic.GPTreeChromosome.RandomSwap().
MaxArgumentsCount
int AForge.Genetic.IGPGene.MaxArgumentsCount get
Maximum arguments count.
Maximum arguments count of a function gene. The property may be used by chromosomes' classes to allocate correctly memory for functions' arguments, for example.
Referenced by AForge.Genetic.GEPChromosome.GEPChromosome().
The documentation for this interface was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Genetic/Chromosomes/GP/IGPGene.cs