Doc: IGLib EXTENDED: AForge.Imaging.Filters.HSLFiltering Class Reference
AForge.Imaging.Filters.HSLFiltering Class Reference
Color filtering in HSL color space.
Public Member Functions
HSLFiltering ()
Initializes a new instance of the HSLFiltering class.
HSLFiltering (IntRange hue, Range saturation, Range luminance)
Initializes a new instance of the HSLFiltering class.
Public Member Functions inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
Bitmap Apply (Bitmap image)
Apply filter to an image.
Bitmap Apply (BitmapData imageData)
Apply filter to an image.
UnmanagedImage Apply (UnmanagedImage image)
Apply filter to an image in unmanaged memory.
void Apply (UnmanagedImage sourceImage, UnmanagedImage destinationImage)
Apply filter to an image in unmanaged memory.
void ApplyInPlace (Bitmap image)
Apply filter to an image.
void ApplyInPlace (BitmapData imageData)
Apply filter to an image.
void ApplyInPlace (UnmanagedImage image)
Apply filter to an unmanaged image.
void ApplyInPlace (Bitmap image, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (BitmapData imageData, Rectangle rect)
Apply filter to an image or its part.
void ApplyInPlace (UnmanagedImage image, Rectangle rect)
Apply filter to an unmanaged image or its part.
Protected Member Functions
override unsafe void ProcessFilter (UnmanagedImage image, Rectangle rect)
Process the filter on the specified image.
Properties
override Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
IntRange Hue [get, set]
Range of hue component, [0, 359].
Range Saturation [get, set]
Range of saturation component, [0, 1].
Range Luminance [get, set]
Range of luminance component, [0, 1].
HSL FillColor [get, set]
Fill color used to fill filtered pixels.
bool FillOutsideRange [get, set]
Determines, if pixels should be filled inside or outside specified color range.
bool UpdateHue [get, set]
Determines, if hue value of filtered pixels should be updated.
bool UpdateSaturation [get, set]
Determines, if saturation value of filtered pixels should be updated.
bool UpdateLuminance [get, set]
Determines, if luminance value of filtered pixels should be updated.
Properties inherited from AForge.Imaging.Filters.BaseInPlacePartialFilter
abstract Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Properties inherited from AForge.Imaging.Filters.IFilterInformation
Dictionary< PixelFormat, PixelFormat > FormatTranslations [get]
Format translations dictionary.
Private Attributes
IntRange hue = new IntRange(0, 359)
Range saturation = new Range(0.0f, 1.0f)
Range luminance = new Range(0.0f, 1.0f)
int fillH = 0
float fillS = 0.0f
float fillL = 0.0f
bool fillOutsideRange = true
bool updateH = true
bool updateS = true
bool updateL = true
Dictionary< PixelFormat, PixelFormat > formatTranslations = new Dictionary<PixelFormat, PixelFormat>()
Detailed Description
Color filtering in HSL color space.
The filter operates in HSL color space and filters pixels, which color is inside/outside of the specified HSL range - it keeps pixels with colors inside/outside of the specified range and fills the rest with specified color.
The filter accepts 24 and 32 bpp color images for processing.
Sample usage:
// create filter
HSLFiltering filter = new HSLFiltering();
// set color ranges to keep
filter.Hue = new IntRange(335, 0);
filter.Saturation = new Range(0.6f, 1);
filter.Luminance = new Range(0.1f, 1);
// apply the filter
filter.ApplyInPlace(image);
Initial image:
Result image:
Sample usage with saturation update only:
// create filter
HSLFiltering filter = new HSLFiltering();
// configure the filter
filter.Hue = new IntRange(340, 20);
filter.UpdateLuminance = false;
filter.UpdateHue = false;
// apply the filter
filter.ApplyInPlace(image);
Result image:
See also
ColorFiltering, YCbCrFiltering
Constructor & Destructor Documentation
HSLFiltering() [1/2]
AForge.Imaging.Filters.HSLFiltering.HSLFiltering () inline
Initializes a new instance of the HSLFiltering class.
References AForge.Imaging.Filters.HSLFiltering.formatTranslations.
HSLFiltering() [2/2]
AForge.Imaging.Filters.HSLFiltering.HSLFiltering (IntRange hue, Range saturation, Range luminance) inline
Initializes a new instance of the HSLFiltering class.
Parameters
hue Range of hue component.
saturation Range of saturation component.
luminance Range of luminance component.
References AForge.Imaging.Filters.HSLFiltering.hue, AForge.Imaging.Filters.HSLFiltering.luminance, and AForge.Imaging.Filters.HSLFiltering.saturation.
Member Function Documentation
ProcessFilter()
override unsafe void AForge.Imaging.Filters.HSLFiltering.ProcessFilter (UnmanagedImage image, Rectangle rect) inline protected virtual
Process the filter on the specified image.
Parameters
image Source image data.
rect Image rectangle for processing by the filter.
Implements AForge.Imaging.Filters.BaseInPlacePartialFilter.
References AForge.Imaging.RGB.B, AForge.Imaging.RGB.Blue, AForge.Imaging.Filters.HSLFiltering.fillH, AForge.Imaging.Filters.HSLFiltering.fillL, AForge.Imaging.Filters.HSLFiltering.fillOutsideRange, AForge.Imaging.Filters.HSLFiltering.fillS, AForge.Imaging.HSL.FromRGB(), AForge.Imaging.RGB.G, AForge.Imaging.RGB.Green, AForge.Imaging.Filters.HSLFiltering.hue, AForge.Imaging.HSL.Hue, AForge.Imaging.UnmanagedImage.ImageData, AForge.Imaging.Filters.HSLFiltering.luminance, AForge.Imaging.HSL.Luminance, AForge.IntRange.Max, AForge.Range.Max, AForge.IntRange.Min, AForge.Range.Min, AForge.Imaging.UnmanagedImage.PixelFormat, AForge.Imaging.RGB.R, AForge.Imaging.RGB.Red, AForge.Imaging.Filters.HSLFiltering.saturation, AForge.Imaging.HSL.Saturation, AForge.Imaging.UnmanagedImage.Stride, AForge.Imaging.HSL.ToRGB(), AForge.Imaging.Filters.HSLFiltering.updateH, AForge.Imaging.Filters.HSLFiltering.updateL, and AForge.Imaging.Filters.HSLFiltering.updateS.
Member Data Documentation
hue
IntRange AForge.Imaging.Filters.HSLFiltering.hue = new IntRange(0, 359) private
Referenced by AForge.Imaging.Filters.HSLFiltering.HSLFiltering(), and AForge.Imaging.Filters.HSLFiltering.ProcessFilter().
saturation
Range AForge.Imaging.Filters.HSLFiltering.saturation = new Range(0.0f, 1.0f) private
Referenced by AForge.Imaging.Filters.HSLFiltering.HSLFiltering(), and AForge.Imaging.Filters.HSLFiltering.ProcessFilter().
luminance
Range AForge.Imaging.Filters.HSLFiltering.luminance = new Range(0.0f, 1.0f) private
Referenced by AForge.Imaging.Filters.HSLFiltering.HSLFiltering(), and AForge.Imaging.Filters.HSLFiltering.ProcessFilter().
fillH
int AForge.Imaging.Filters.HSLFiltering.fillH = 0 private
Referenced by AForge.Imaging.Filters.HSLFiltering.ProcessFilter().
fillS
float AForge.Imaging.Filters.HSLFiltering.fillS = 0.0f private
Referenced by AForge.Imaging.Filters.HSLFiltering.ProcessFilter().
fillL
float AForge.Imaging.Filters.HSLFiltering.fillL = 0.0f private
Referenced by AForge.Imaging.Filters.HSLFiltering.ProcessFilter().
fillOutsideRange
bool AForge.Imaging.Filters.HSLFiltering.fillOutsideRange = true private
Referenced by AForge.Imaging.Filters.HSLFiltering.ProcessFilter().
updateH
bool AForge.Imaging.Filters.HSLFiltering.updateH = true private
Referenced by AForge.Imaging.Filters.HSLFiltering.ProcessFilter().
updateS
bool AForge.Imaging.Filters.HSLFiltering.updateS = true private
Referenced by AForge.Imaging.Filters.HSLFiltering.ProcessFilter().
updateL
bool AForge.Imaging.Filters.HSLFiltering.updateL = true private
Referenced by AForge.Imaging.Filters.HSLFiltering.ProcessFilter().
formatTranslations
Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.HSLFiltering.formatTranslations = new Dictionary<PixelFormat, PixelFormat>() private
Referenced by AForge.Imaging.Filters.HSLFiltering.HSLFiltering().
Property Documentation
FormatTranslations
override Dictionary<PixelFormat, PixelFormat> AForge.Imaging.Filters.HSLFiltering.FormatTranslations get
Format translations dictionary.
Hue
IntRange AForge.Imaging.Filters.HSLFiltering.Hue get set
Range of hue component, [0, 359].
<note>Because of hue values are cycled, the minimum value of the hue range may have bigger integer value than the maximum value, for example [330, 30].</note>
Saturation
Range AForge.Imaging.Filters.HSLFiltering.Saturation get set
Range of saturation component, [0, 1].
Luminance
Range AForge.Imaging.Filters.HSLFiltering.Luminance get set
Range of luminance component, [0, 1].
FillColor
HSL AForge.Imaging.Filters.HSLFiltering.FillColor get set
Fill color used to fill filtered pixels.
FillOutsideRange
bool AForge.Imaging.Filters.HSLFiltering.FillOutsideRange get set
Determines, if pixels should be filled inside or outside specified color range.
Default value is set to true, which means the filter removes colors outside of the specified range.
UpdateHue
bool AForge.Imaging.Filters.HSLFiltering.UpdateHue get set
Determines, if hue value of filtered pixels should be updated.
The property specifies if hue of filtered pixels should be updated with value from fill color or not.
Default value is set to true.
UpdateSaturation
bool AForge.Imaging.Filters.HSLFiltering.UpdateSaturation get set
Determines, if saturation value of filtered pixels should be updated.
The property specifies if saturation of filtered pixels should be updated with value from fill color or not.
Default value is set to true.
UpdateLuminance
bool AForge.Imaging.Filters.HSLFiltering.UpdateLuminance get set
Determines, if luminance value of filtered pixels should be updated.
The property specifies if luminance of filtered pixels should be updated with value from fill color or not.
Default value is set to true.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Imaging/Filters/HSL Filters/HSLFiltering.cs