Doc: IGLib EXTENDED: HoughTransform.MainForm Class Reference
HoughTransform.MainForm Class Reference
Public Member Functions
MainForm ()
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void exitToolStripMenuItem_Click (object sender, EventArgs e)
void openToolStripMenuItem_Click (object sender, EventArgs e)
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
FiltersSequence filter
HoughLineTransformation lineTransform = new HoughLineTransformation()
HoughCircleTransformation circleTransform = new HoughCircleTransformation(35)
System.ComponentModel.IContainer components = null
Required designer variable.
System.Windows.Forms.MenuStrip menuStrip1
System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem openToolStripMenuItem
System.Windows.Forms.ToolStripSeparator toolStripMenuItem1
System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem
System.Windows.Forms.OpenFileDialog openFileDialog
System.Windows.Forms.TabControl tabControl
System.Windows.Forms.TabPage tabPage1
System.Windows.Forms.PictureBox sourcePictureBox
System.Windows.Forms.TabPage tabPage2
System.Windows.Forms.PictureBox houghLinePictureBox
System.Windows.Forms.TabPage tabPage3
System.Windows.Forms.PictureBox houghCirclePictureBox
Constructor & Destructor Documentation
MainForm()
HoughTransform.MainForm.MainForm () inline
References HoughTransform.MainForm.circleTransform, HoughTransform.MainForm.InitializeComponent(), HoughTransform.MainForm.lineTransform, AForge.Imaging.HoughCircleTransformation.MinCircleIntensity, and AForge.Imaging.HoughLineTransformation.MinLineIntensity.
Member Function Documentation
exitToolStripMenuItem_Click()
void HoughTransform.MainForm.exitToolStripMenuItem_Click (object sender, EventArgs e) inline private
Referenced by HoughTransform.MainForm.InitializeComponent().
openToolStripMenuItem_Click()
void HoughTransform.MainForm.openToolStripMenuItem_Click (object sender, EventArgs e) inline private
References AForge.Imaging.Filters.FiltersSequence.Apply(), AForge.Imaging.HoughCircleTransformation.CirclesCount, HoughTransform.MainForm.circleTransform, AForge.Imaging.Image.Clone(), HoughTransform.MainForm.filter, AForge.Imaging.Image.FormatImage(), AForge.Imaging.HoughCircleTransformation.GetCirclesByRelativeIntensity(), AForge.Imaging.HoughLineTransformation.GetLinesByRelativeIntensity(), HoughTransform.MainForm.houghCirclePictureBox, HoughTransform.MainForm.houghLinePictureBox, AForge.Imaging.HoughCircle.Intensity, AForge.Imaging.HoughLine.Intensity, AForge.Imaging.HoughLineTransformation.LinesCount, HoughTransform.MainForm.lineTransform, AForge.Imaging.HoughCircleTransformation.MaxIntensity, AForge.Imaging.HoughLineTransformation.MaxIntensity, HoughTransform.MainForm.openFileDialog, AForge.Imaging.HoughCircleTransformation.ProcessImage(), AForge.Imaging.HoughLineTransformation.ProcessImage(), AForge.Imaging.HoughLine.Radius, AForge.Math.Geometry.Rectangle, AForge.Imaging.HoughCircle.RelativeIntensity, AForge.Imaging.HoughLine.RelativeIntensity, HoughTransform.MainForm.sourcePictureBox, AForge.Imaging.HoughLine.Theta, AForge.Imaging.HoughCircleTransformation.ToBitmap(), AForge.Imaging.HoughLineTransformation.ToBitmap(), AForge.Imaging.HoughCircle.X, and AForge.Imaging.HoughCircle.Y.
Referenced by HoughTransform.MainForm.InitializeComponent().
Dispose()
override void HoughTransform.MainForm.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References HoughTransform.MainForm.components.
InitializeComponent()
void HoughTransform.MainForm.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References HoughTransform.MainForm.exitToolStripMenuItem, HoughTransform.MainForm.exitToolStripMenuItem_Click(), HoughTransform.MainForm.fileToolStripMenuItem, HoughTransform.MainForm.houghCirclePictureBox, HoughTransform.MainForm.houghLinePictureBox, HoughTransform.MainForm.menuStrip1, HoughTransform.MainForm.openFileDialog, HoughTransform.MainForm.openToolStripMenuItem, HoughTransform.MainForm.openToolStripMenuItem_Click(), HoughTransform.MainForm.sourcePictureBox, HoughTransform.MainForm.tabControl, HoughTransform.MainForm.tabPage1, HoughTransform.MainForm.tabPage2, HoughTransform.MainForm.tabPage3, and HoughTransform.MainForm.toolStripMenuItem1.
Referenced by HoughTransform.MainForm.MainForm().
Member Data Documentation
filter
FiltersSequence HoughTransform.MainForm.filter private
Initial value:
= new FiltersSequence(
            Grayscale.CommonAlgorithms.BT709,
            new Threshold( 64 )
        )
Referenced by HoughTransform.MainForm.openToolStripMenuItem_Click().
lineTransform
HoughLineTransformation HoughTransform.MainForm.lineTransform = new HoughLineTransformation() private
Referenced by HoughTransform.MainForm.MainForm(), and HoughTransform.MainForm.openToolStripMenuItem_Click().
circleTransform
HoughCircleTransformation HoughTransform.MainForm.circleTransform = new HoughCircleTransformation(35) private
Referenced by HoughTransform.MainForm.MainForm(), and HoughTransform.MainForm.openToolStripMenuItem_Click().
components
System.ComponentModel.IContainer HoughTransform.MainForm.components = null private
Required designer variable.
Referenced by HoughTransform.MainForm.Dispose().
menuStrip1
System.Windows.Forms.MenuStrip HoughTransform.MainForm.menuStrip1 private
Referenced by HoughTransform.MainForm.InitializeComponent().
fileToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem HoughTransform.MainForm.fileToolStripMenuItem private
Referenced by HoughTransform.MainForm.InitializeComponent().
openToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem HoughTransform.MainForm.openToolStripMenuItem private
Referenced by HoughTransform.MainForm.InitializeComponent().
toolStripMenuItem1
System.Windows.Forms.ToolStripSeparator HoughTransform.MainForm.toolStripMenuItem1 private
Referenced by HoughTransform.MainForm.InitializeComponent().
exitToolStripMenuItem
System.Windows.Forms.ToolStripMenuItem HoughTransform.MainForm.exitToolStripMenuItem private
Referenced by HoughTransform.MainForm.InitializeComponent().
openFileDialog
System.Windows.Forms.OpenFileDialog HoughTransform.MainForm.openFileDialog private
Referenced by HoughTransform.MainForm.InitializeComponent(), and HoughTransform.MainForm.openToolStripMenuItem_Click().
tabControl
System.Windows.Forms.TabControl HoughTransform.MainForm.tabControl private
Referenced by HoughTransform.MainForm.InitializeComponent().
tabPage1
System.Windows.Forms.TabPage HoughTransform.MainForm.tabPage1 private
Referenced by HoughTransform.MainForm.InitializeComponent().
sourcePictureBox
System.Windows.Forms.PictureBox HoughTransform.MainForm.sourcePictureBox private
Referenced by HoughTransform.MainForm.InitializeComponent(), and HoughTransform.MainForm.openToolStripMenuItem_Click().
tabPage2
System.Windows.Forms.TabPage HoughTransform.MainForm.tabPage2 private
Referenced by HoughTransform.MainForm.InitializeComponent().
houghLinePictureBox
System.Windows.Forms.PictureBox HoughTransform.MainForm.houghLinePictureBox private
Referenced by HoughTransform.MainForm.InitializeComponent(), and HoughTransform.MainForm.openToolStripMenuItem_Click().
tabPage3
System.Windows.Forms.TabPage HoughTransform.MainForm.tabPage3 private
Referenced by HoughTransform.MainForm.InitializeComponent().
houghCirclePictureBox
System.Windows.Forms.PictureBox HoughTransform.MainForm.houghCirclePictureBox private
Referenced by HoughTransform.MainForm.InitializeComponent(), and HoughTransform.MainForm.openToolStripMenuItem_Click().
The documentation for this class was generated from the following files:
shelldev/lib_ann/aforge.net/Samples/Imaging/HoughTransformation/MainForm.cs
shelldev/lib_ann/aforge.net/Samples/Imaging/HoughTransformation/MainForm.Designer.cs