Doc: IGLib EXTENDED: efakt1.WebServiceSimulator Class Reference
efakt1.WebServiceSimulator Class Reference
Public Member Functions
WebServiceSimulator ()
void Connect ()
void Disconnect ()
string PosljiPaket (byte paketTipId, DateTime paketDatum, int stZapisov, decimal vsotaDokumentDatum, decimal vsotaCenaNeto, string paketXml)
int InsertIntoEfaPaket (byte paketTipId, DateTime paketDatum, int stZapisov, decimal vsotaDokumentDatum, decimal vsotaCenaNeto, int paketStatusId)
void UpdateGlavaPostavke (decimal paketId)
void SaveXmlToDisk (string paketXml, decimal paketId)
void InsertPaketXml (decimal paketId)
string GetPaketStatusXml (decimal paketId)
void ValidateXml ()
void ValidationHandler (object sender, System.Xml.Schema.ValidationEventArgs args)
int ValidateXml (string strXMLDoc)
Private Member Functions
void ReadSettings ()
string GetXmlFileName (decimal paketId)
string GetXmlErrorFileName (decimal paketId)
string GetXmlAnnSchemaPathName ()
string GetXmlStatusAnnSchemaPathName ()
string GetXmlPathName ()
string GetCnnString ()
string GetCnnStringBulk ()
Private Attributes
string cnnString
string cnnStringBulk
string xmlAnnSchemaPathName
string xmlStatusAnnSchemaPathName
string xmlPathName
System.Data.SqlClient.SqlConnection cnn = null
System.Data.SqlClient.SqlTransaction trans = null
int ErrorsCount = 0
string ErrorMessage = ""
Constructor & Destructor Documentation
WebServiceSimulator()
efakt1.WebServiceSimulator.WebServiceSimulator () inline
References efakt1.WebServiceSimulator.ReadSettings().
Member Function Documentation
ReadSettings()
void efakt1.WebServiceSimulator.ReadSettings () inline private
References efakt1.WebServiceSimulator.cnnString, efakt1.WebServiceSimulator.cnnStringBulk, efakt1.WebServiceSimulator.GetCnnString(), efakt1.WebServiceSimulator.GetCnnStringBulk(), efakt1.WebServiceSimulator.GetXmlAnnSchemaPathName(), efakt1.WebServiceSimulator.GetXmlPathName(), efakt1.WebServiceSimulator.GetXmlStatusAnnSchemaPathName(), efakt1.WebServiceSimulator.xmlAnnSchemaPathName, efakt1.WebServiceSimulator.xmlPathName, and efakt1.WebServiceSimulator.xmlStatusAnnSchemaPathName.
Referenced by efakt1.WebServiceSimulator.WebServiceSimulator().
Connect()
void efakt1.WebServiceSimulator.Connect () inline
References efakt1.WebServiceSimulator.cnn, and efakt1.WebServiceSimulator.cnnString.
Referenced by TestGui.Form2.button1_Click(), TestGui.Form2.button2_Click(), TestGui.Form2.button3_Click(), TestGui.Form2.button4_Click(), TestGui.Form2.button5_Click(), TestGui.Form2.button7_Click(), and efakt1.WebServiceSimulator.PosljiPaket().
Disconnect()
void efakt1.WebServiceSimulator.Disconnect () inline
References efakt1.WebServiceSimulator.cnn.
Referenced by TestGui.Form2.button1_Click(), TestGui.Form2.button2_Click(), TestGui.Form2.button3_Click(), TestGui.Form2.button4_Click(), TestGui.Form2.button5_Click(), TestGui.Form2.button7_Click(), and efakt1.WebServiceSimulator.PosljiPaket().
PosljiPaket()
string efakt1.WebServiceSimulator.PosljiPaket (byte paketTipId, DateTime paketDatum, int stZapisov, decimal vsotaDokumentDatum, decimal vsotaCenaNeto, string paketXml) inline
References efakt1.WebServiceSimulator.cnn, efakt1.WebServiceSimulator.Connect(), efakt1.WebServiceSimulator.Disconnect(), efakt1.WebServiceSimulator.GetPaketStatusXml(), efakt1.WebServiceSimulator.InsertIntoEfaPaket(), efakt1.WebServiceSimulator.InsertPaketXml(), efakt1.WebServiceSimulator.SaveXmlToDisk(), efakt1.WebServiceSimulator.trans, and efakt1.WebServiceSimulator.UpdateGlavaPostavke().
InsertIntoEfaPaket()
int efakt1.WebServiceSimulator.InsertIntoEfaPaket (byte paketTipId, DateTime paketDatum, int stZapisov, decimal vsotaDokumentDatum, decimal vsotaCenaNeto, int paketStatusId) inline
References efakt1.WebServiceSimulator.cnn, and efakt1.WebServiceSimulator.trans.
Referenced by TestGui.Form2.button1_Click(), and efakt1.WebServiceSimulator.PosljiPaket().
UpdateGlavaPostavke()
void efakt1.WebServiceSimulator.UpdateGlavaPostavke (decimal paketId) inline
References efakt1.WebServiceSimulator.cnn, and efakt1.WebServiceSimulator.trans.
Referenced by TestGui.Form2.button4_Click(), and efakt1.WebServiceSimulator.PosljiPaket().
SaveXmlToDisk()
void efakt1.WebServiceSimulator.SaveXmlToDisk (string paketXml, decimal paketId) inline
References efakt1.WebServiceSimulator.GetXmlFileName(), and efakt1.WebServiceSimulator.xmlPathName.
Referenced by TestGui.Form2.button2_Click(), and efakt1.WebServiceSimulator.PosljiPaket().
InsertPaketXml()
void efakt1.WebServiceSimulator.InsertPaketXml (decimal paketId) inline
References efakt1.WebServiceSimulator.cnnStringBulk, efakt1.WebServiceSimulator.GetXmlErrorFileName(), efakt1.WebServiceSimulator.GetXmlFileName(), efakt1.WebServiceSimulator.xmlAnnSchemaPathName, and efakt1.WebServiceSimulator.xmlPathName.
Referenced by TestGui.Form2.button3_Click(), and efakt1.WebServiceSimulator.PosljiPaket().
GetPaketStatusXml()
string efakt1.WebServiceSimulator.GetPaketStatusXml (decimal paketId) inline
References efakt1.WebServiceSimulator.cnnStringBulk, and efakt1.WebServiceSimulator.xmlStatusAnnSchemaPathName.
Referenced by TestGui.Form2.button5_Click(), and efakt1.WebServiceSimulator.PosljiPaket().
GetXmlFileName()
string efakt1.WebServiceSimulator.GetXmlFileName (decimal paketId) inline private
Referenced by efakt1.WebServiceSimulator.InsertPaketXml(), and efakt1.WebServiceSimulator.SaveXmlToDisk().
GetXmlErrorFileName()
string efakt1.WebServiceSimulator.GetXmlErrorFileName (decimal paketId) inline private
Referenced by efakt1.WebServiceSimulator.InsertPaketXml().
GetXmlAnnSchemaPathName()
string efakt1.WebServiceSimulator.GetXmlAnnSchemaPathName () inline private
Referenced by efakt1.WebServiceSimulator.ReadSettings().
GetXmlStatusAnnSchemaPathName()
string efakt1.WebServiceSimulator.GetXmlStatusAnnSchemaPathName () inline private
Referenced by efakt1.WebServiceSimulator.ReadSettings().
GetXmlPathName()
string efakt1.WebServiceSimulator.GetXmlPathName () inline private
Referenced by efakt1.WebServiceSimulator.ReadSettings().
GetCnnString()
string efakt1.WebServiceSimulator.GetCnnString () inline private
References efakt1.WebServiceSimulator.cnnString.
Referenced by efakt1.WebServiceSimulator.ReadSettings().
GetCnnStringBulk()
string efakt1.WebServiceSimulator.GetCnnStringBulk () inline private
References efakt1.WebServiceSimulator.cnnString, and efakt1.WebServiceSimulator.cnnStringBulk.
Referenced by efakt1.WebServiceSimulator.ReadSettings().
ValidateXml() [1/2]
void efakt1.WebServiceSimulator.ValidateXml () inline
Referenced by TestGui.Form2.button7_Click().
ValidationHandler()
void efakt1.WebServiceSimulator.ValidationHandler (object sender, System.Xml.Schema.ValidationEventArgs args) inline
References efakt1.WebServiceSimulator.ErrorMessage, and efakt1.WebServiceSimulator.ErrorsCount.
Referenced by efakt1.WebServiceSimulator.ValidateXml().
ValidateXml() [2/2]
int efakt1.WebServiceSimulator.ValidateXml (string strXMLDoc) inline
References efakt1.WebServiceSimulator.ErrorMessage, efakt1.WebServiceSimulator.ErrorsCount, and efakt1.WebServiceSimulator.ValidationHandler().
Member Data Documentation
cnnString
string efakt1.WebServiceSimulator.cnnString private
Referenced by efakt1.WebServiceSimulator.Connect(), efakt1.WebServiceSimulator.GetCnnString(), efakt1.WebServiceSimulator.GetCnnStringBulk(), and efakt1.WebServiceSimulator.ReadSettings().
cnnStringBulk
string efakt1.WebServiceSimulator.cnnStringBulk private
Referenced by efakt1.WebServiceSimulator.GetCnnStringBulk(), efakt1.WebServiceSimulator.GetPaketStatusXml(), efakt1.WebServiceSimulator.InsertPaketXml(), and efakt1.WebServiceSimulator.ReadSettings().
xmlAnnSchemaPathName
string efakt1.WebServiceSimulator.xmlAnnSchemaPathName private
Referenced by efakt1.WebServiceSimulator.InsertPaketXml(), and efakt1.WebServiceSimulator.ReadSettings().
xmlStatusAnnSchemaPathName
string efakt1.WebServiceSimulator.xmlStatusAnnSchemaPathName private
Referenced by efakt1.WebServiceSimulator.GetPaketStatusXml(), and efakt1.WebServiceSimulator.ReadSettings().
xmlPathName
string efakt1.WebServiceSimulator.xmlPathName private
Referenced by efakt1.WebServiceSimulator.InsertPaketXml(), efakt1.WebServiceSimulator.ReadSettings(), and efakt1.WebServiceSimulator.SaveXmlToDisk().
cnn
System.Data.SqlClient.SqlConnection efakt1.WebServiceSimulator.cnn = null private
Referenced by efakt1.WebServiceSimulator.Connect(), efakt1.WebServiceSimulator.Disconnect(), efakt1.WebServiceSimulator.InsertIntoEfaPaket(), efakt1.WebServiceSimulator.PosljiPaket(), and efakt1.WebServiceSimulator.UpdateGlavaPostavke().
trans
System.Data.SqlClient.SqlTransaction efakt1.WebServiceSimulator.trans = null private
Referenced by efakt1.WebServiceSimulator.InsertIntoEfaPaket(), efakt1.WebServiceSimulator.PosljiPaket(), and efakt1.WebServiceSimulator.UpdateGlavaPostavke().
ErrorsCount
int efakt1.WebServiceSimulator.ErrorsCount = 0 private
Referenced by efakt1.WebServiceSimulator.ValidateXml(), and efakt1.WebServiceSimulator.ValidationHandler().
ErrorMessage
string efakt1.WebServiceSimulator.ErrorMessage = "" private
Referenced by efakt1.WebServiceSimulator.ValidateXml(), and efakt1.WebServiceSimulator.ValidationHandler().
The documentation for this class was generated from the following file:
igtest/tmp_prem/prefa/95_Test/TestUtils/WebServiceSimulator/WebServiceSimulator.cs