Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.ILAENV Class Reference
DotNumerics.LinearAlgebra.CSLapack.ILAENV Class Reference
– LAPACK auxiliary routine (version 3.1.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. January 2007
Public Member Functions
ILAENV (IEEECK ieeeck, IPARMQ iparmq)
ILAENV ()
int Run (int ISPEC, string NAME, string OPTS, int N1, int N2, int N3, int N4)
Private Attributes
IEEECK _ieeeck
IPARMQ _iparmq
Detailed Description
– LAPACK auxiliary routine (version 3.1.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. January 2007
Purpose
ILAENV is called from the LAPACK routines to choose problem-dependent parameters for the local environment. See ISPEC for a description of the parameters.
ILAENV returns an INTEGER if ILAENV .GE. 0: ILAENV returns the value of the parameter specified by ISPEC if ILAENV .LT. 0: if ILAENV = -k, the k-th argument had an illegal value.
This version provides a set of parameters which should give good, but not optimal, performance on many of the currently available computers. Users are encouraged to modify this subroutine to set the tuning parameters for their particular machine using the option and problem size information in the arguments.
This routine will not function correctly if it is converted to all lower case. Converting it to all upper case is allowed.
/summary>
Constructor & Destructor Documentation
ILAENV() [1/2]
DotNumerics.LinearAlgebra.CSLapack.ILAENV.ILAENV (IEEECK ieeeck, IPARMQ iparmq) inline
ILAENV() [2/2]
DotNumerics.LinearAlgebra.CSLapack.ILAENV.ILAENV () inline
Member Function Documentation
Run()
int DotNumerics.LinearAlgebra.CSLapack.ILAENV.Run (int ISPEC, string NAME, string OPTS, int N1, int N2, int N3, int N4) inline
Purpose
ILAENV is called from the LAPACK routines to choose problem-dependent parameters for the local environment. See ISPEC for a description of the parameters.
ILAENV returns an INTEGER if ILAENV .GE. 0: ILAENV returns the value of the parameter specified by ISPEC if ILAENV .LT. 0: if ILAENV = -k, the k-th argument had an illegal value.
This version provides a set of parameters which should give good, but not optimal, performance on many of the currently available computers. Users are encouraged to modify this subroutine to set the tuning parameters for their particular machine using the option and problem size information in the arguments.
This routine will not function correctly if it is converted to all lower case. Converting it to all upper case is allowed.
/summary>
Parameters
ISPEC (input) INTEGER Specifies the parameter to be returned as the value of ILAENV. = 1: the optimal blocksize; if this value is 1, an unblocked algorithm will give the best performance. = 2: the minimum block size for which the block routine should be used; if the usable block size is less than this value, an unblocked routine should be used. = 3: the crossover point (in a block routine, for N less than this value, an unblocked routine should be used) = 4: the number of shifts, used in the nonsymmetric eigenvalue routines (DEPRECATED) = 5: the minimum column dimension for blocking to be used; rectangular blocks must have dimension at least k by m, where k is given by ILAENV(2,...) and m by ILAENV(5,...) = 6: the crossover point for the SVD (when reducing an m by n matrix to bidiagonal form, if max(m,n)/min(m,n) exceeds this value, a QR factorization is used first to reduce the matrix to a triangular form.) = 7: the number of processors = 8: the crossover point for the multishift QR method for nonsymmetric eigenvalue problems (DEPRECATED) = 9: maximum size of the subproblems at the bottom of the computation tree in the divide-and-conquer algorithm (used by xGELSD and xGESDD) =10: ieee NaN arithmetic can be trusted not to trap =11: infinity arithmetic can be trusted not to trap 12 .LE. ISPEC .LE. 16: xHSEQR or one of its subroutines, see IPARMQ for detailed explanation /param>
Parameters
NAME (input) CHARACTER*(*) The name of the calling subroutine, in either upper case or lower case. /param>
Parameters
OPTS (input) CHARACTER*(*) The character options to the subroutine NAME, concatenated into a single character string. For example, UPLO = 'U', TRANS = 'T', and DIAG = 'N' for a triangular routine would be specified as OPTS = 'UTN'. /param>
Parameters
N1 (input) INTEGER /param>
Parameters
N2 (input) INTEGER /param>
Parameters
N3 (input) INTEGER /param>
Parameters
N4 (input) INTEGER Problem dimensions for the subroutine NAME; these may not all be required. /param>
References DotNumerics.FortranLibrary.FortranLib.Copy(), DotNumerics.LinearAlgebra.CSLapack.IEEECK.Run(), DotNumerics.LinearAlgebra.CSLapack.IPARMQ.Run(), and DotNumerics.FortranLibrary.FortranLib.Substring().
Referenced by DotNumerics.LinearAlgebra.CSLapack.DTRTRI.Run(), DotNumerics.LinearAlgebra.CSLapack.DGETRI.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELQF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGERQF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGETRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLASQ2.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGHR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGBTRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGTR.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGLQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGQL.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DTZRZF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEHRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQP3.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYTRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEBRD.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMTR.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMLQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMQL.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMRQ.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DORGBR.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMRZ.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAED0.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGRQF.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGQRF.Run(), DotNumerics.LinearAlgebra.CSLapack.DORMBR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGLSE.Run(), DotNumerics.LinearAlgebra.CSLapack.DGGGLM.Run(), DotNumerics.LinearAlgebra.CSLapack.DSTEDC.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELS.Run(), DotNumerics.LinearAlgebra.CSLapack.DSYEVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEEV.Run(), DotNumerics.LinearAlgebra.CSLapack.DBDSDC.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR3.Run(), DotNumerics.LinearAlgebra.CSLapack.DGESVD.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELSY.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR4.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAQR0.Run(), DotNumerics.LinearAlgebra.CSLapack.DHSEQR.Run(), DotNumerics.LinearAlgebra.CSLapack.DGELSD.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGESDD.Run().
Member Data Documentation
_ieeeck
IEEECK DotNumerics.LinearAlgebra.CSLapack.ILAENV._ieeeck private
_iparmq
IPARMQ DotNumerics.LinearAlgebra.CSLapack.ILAENV._iparmq private
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/ilaenv.cs