Doc: IGLib EXTENDED: CShell.Modules.Repl.ViewModels.ReplViewModel Class Reference
CShell.Modules.Repl.ViewModels.ReplViewModel Class Reference
Public Member Functions
ReplViewModel (IEventAggregator eventAggregator)
void Handle (WorkspaceOpeningEventArgs message)
void Handle (WorkspaceClosedEventArgs message)
void Clear ()
void SuppressWarning (string warningCode)
void ShowWarning (string warningCode)
Protected Member Functions
override void OnViewLoaded (object view)
override void OnDeactivate (bool close)
Protected Member Functions inherited from CShell.Framework.Tool
Tool ()
Properties
override Uri IconSource [get]
override PaneLocation PreferredLocation [get]
override Uri Uri [get]
bool IsEvaluating [get]
IEnumerable< string > SuppressedWarnings [get]
bool ShowConsoleOutput [get, set]
string Font [get, set]
double FontSize [get, set]
System.Windows.Media.Color BackgroundColor [get, set]
System.Windows.Media.Color OutputColor [get, set]
System.Windows.Media.Color WarningColor [get, set]
System.Windows.Media.Color ErrorColor [get, set]
System.Windows.Media.Color ReplColor [get, set]
Properties inherited from CShell.Framework.Tool
ICommand?? CloseCommand [get]
abstract PaneLocation PreferredLocation [get]
abstract Uri Uri [get]
virtual Uri IconSource [get]
bool IsVisible [get, set]
Properties inherited from CShell.Framework.ITool
Uri Uri [get]
ICommand CloseCommand [get]
PaneLocation PreferredLocation [get]
bool IsVisible [get, set]
Properties inherited from CShell.Framework.Services.IRepl
bool IsEvaluating [get]
IEnumerable< string > SuppressedWarnings [get]
bool ShowConsoleOutput [get, set]
string Font [get, set]
double FontSize [get, set]
Color BackgroundColor [get, set]
Color OutputColor [get, set]
Color WarningColor [get, set]
Color ErrorColor [get, set]
Color ReplColor [get, set]
Private Member Functions
void TimerOnElapsed (object sender, ElapsedEventArgs elapsedEventArgs)
Private Attributes
readonly Timer timer
IRepl internalRepl
IReplView replView
IShell shell
DateTime lastTimeNoEvaluations
Constructor & Destructor Documentation
ReplViewModel()
CShell.Modules.Repl.ViewModels.ReplViewModel.ReplViewModel (IEventAggregator eventAggregator) inline
References CShell.Modules.Repl.ViewModels.ReplViewModel.timer, and CShell.Modules.Repl.ViewModels.ReplViewModel.TimerOnElapsed().
Member Function Documentation
OnViewLoaded()
override void CShell.Modules.Repl.ViewModels.ReplViewModel.OnViewLoaded (object view) inline protected
References CShell.Modules.Repl.Views.IReplView.GetRepl(), CShell.Modules.Repl.ViewModels.ReplViewModel.internalRepl, CShell.Modules.Repl.ViewModels.ReplViewModel.replView, and CShell.Modules.Repl.ViewModels.ReplViewModel.timer.
OnDeactivate()
override void CShell.Modules.Repl.ViewModels.ReplViewModel.OnDeactivate (bool close) inline protected
References CShell.Modules.Repl.ViewModels.ReplViewModel.timer.
TimerOnElapsed()
void CShell.Modules.Repl.ViewModels.ReplViewModel.TimerOnElapsed (object sender, ElapsedEventArgs elapsedEventArgs) inline private
References CShell.Modules.Repl.ViewModels.ReplViewModel.internalRepl, CShell.Framework.Services.IRepl.IsEvaluating, CShell.Modules.Repl.ViewModels.ReplViewModel.lastTimeNoEvaluations, CShell.Framework.Services.IStatusBar.Message, CShell.Modules.Repl.ViewModels.ReplViewModel.shell, CShell.Framework.Services.IShell.StatusBar, CShell.Framework.Services.IStatusBar.UpdateMessage(), and CShell.Framework.Services.IStatusBar.UpdateProgress().
Referenced by CShell.Modules.Repl.ViewModels.ReplViewModel.ReplViewModel().
Handle() [1/2]
void CShell.Modules.Repl.ViewModels.ReplViewModel.Handle (WorkspaceOpeningEventArgs message) inline
References CShell.Modules.Repl.ViewModels.ReplViewModel.replView, CShell.Modules.Repl.Views.IReplView.ScriptingEngine, CShell.Workspace.ScriptingEngine, and CShell.WorkspaceOpeningEventArgs.Workspace.
Handle() [2/2]
void CShell.Modules.Repl.ViewModels.ReplViewModel.Handle (WorkspaceClosedEventArgs message) inline
References CShell.Modules.Repl.ViewModels.ReplViewModel.replView, and CShell.Modules.Repl.Views.IReplView.ScriptingEngine.
Clear()
void CShell.Modules.Repl.ViewModels.ReplViewModel.Clear () inline
Implements CShell.Framework.Services.IRepl.
References CShell.Framework.Services.IRepl.Clear(), CShell.Modules.Repl.ViewModels.ReplViewModel.internalRepl, and CShell.Framework.Services.Execute.OnUIThread().
SuppressWarning()
void CShell.Modules.Repl.ViewModels.ReplViewModel.SuppressWarning (string warningCode) inline
Implements CShell.Framework.Services.IRepl.
References CShell.Modules.Repl.ViewModels.ReplViewModel.internalRepl, and CShell.Framework.Services.IRepl.SuppressWarning().
ShowWarning()
void CShell.Modules.Repl.ViewModels.ReplViewModel.ShowWarning (string warningCode) inline
Implements CShell.Framework.Services.IRepl.
References CShell.Modules.Repl.ViewModels.ReplViewModel.internalRepl, and CShell.Framework.Services.IRepl.ShowWarning().
Member Data Documentation
timer
readonly Timer CShell.Modules.Repl.ViewModels.ReplViewModel.timer private
Referenced by CShell.Modules.Repl.ViewModels.ReplViewModel.OnDeactivate(), CShell.Modules.Repl.ViewModels.ReplViewModel.OnViewLoaded(), and CShell.Modules.Repl.ViewModels.ReplViewModel.ReplViewModel().
internalRepl
IRepl CShell.Modules.Repl.ViewModels.ReplViewModel.internalRepl private
Referenced by CShell.Modules.Repl.ViewModels.ReplViewModel.Clear(), CShell.Modules.Repl.ViewModels.ReplViewModel.OnViewLoaded(), CShell.Modules.Repl.ViewModels.ReplViewModel.ShowWarning(), CShell.Modules.Repl.ViewModels.ReplViewModel.SuppressWarning(), and CShell.Modules.Repl.ViewModels.ReplViewModel.TimerOnElapsed().
replView
IReplView CShell.Modules.Repl.ViewModels.ReplViewModel.replView private
Referenced by CShell.Modules.Repl.ViewModels.ReplViewModel.Handle(), and CShell.Modules.Repl.ViewModels.ReplViewModel.OnViewLoaded().
shell
IShell CShell.Modules.Repl.ViewModels.ReplViewModel.shell private
Referenced by CShell.Modules.Repl.ViewModels.ReplViewModel.TimerOnElapsed().
lastTimeNoEvaluations
DateTime CShell.Modules.Repl.ViewModels.ReplViewModel.lastTimeNoEvaluations private
Referenced by CShell.Modules.Repl.ViewModels.ReplViewModel.TimerOnElapsed().
Property Documentation
IconSource
override Uri CShell.Modules.Repl.ViewModels.ReplViewModel.IconSource get
PreferredLocation
override PaneLocation CShell.Modules.Repl.ViewModels.ReplViewModel.PreferredLocation get
Uri
override Uri CShell.Modules.Repl.ViewModels.ReplViewModel.Uri get
IsEvaluating
bool CShell.Modules.Repl.ViewModels.ReplViewModel.IsEvaluating get
SuppressedWarnings
IEnumerable<string> CShell.Modules.Repl.ViewModels.ReplViewModel.SuppressedWarnings get
ShowConsoleOutput
bool CShell.Modules.Repl.ViewModels.ReplViewModel.ShowConsoleOutput get set
Font
string CShell.Modules.Repl.ViewModels.ReplViewModel.Font get set
FontSize
double CShell.Modules.Repl.ViewModels.ReplViewModel.FontSize get set
BackgroundColor
System.Windows.Media.Color CShell.Modules.Repl.ViewModels.ReplViewModel.BackgroundColor get set
OutputColor
System.Windows.Media.Color CShell.Modules.Repl.ViewModels.ReplViewModel.OutputColor get set
WarningColor
System.Windows.Media.Color CShell.Modules.Repl.ViewModels.ReplViewModel.WarningColor get set
ErrorColor
System.Windows.Media.Color CShell.Modules.Repl.ViewModels.ReplViewModel.ErrorColor get set
ReplColor
System.Windows.Media.Color CShell.Modules.Repl.ViewModels.ReplViewModel.ReplColor get set
The documentation for this class was generated from the following file:
shelldev/repl/CShell-0.1.2/Src/CShell/Modules/Repl/ViewModels/ReplViewModel.cs