Doc: IGLib EXTENDED: NUnit.Framework.Attributes.TestMethodBuilderTests Class Reference
NUnit.Framework.Attributes.TestMethodBuilderTests Class Reference
Public Member Functions
void TestAttribute_NoArgs_Runnable ()
void TestAttribute_WithArgs_NotRunnable ()
void TestCaseAttribute_NoArgs_NotRunnable ()
void TestCaseAttribute_RightArgs_Runnable ()
void TestCaseAttribute_WrongArgs_NotRunnable ()
void TestCaseSourceAttribute_NoArgs_NotRunnable ()
void TestCaseSourceAttribute_RightArgs_Runnable ()
void TestCaseSourceAttribute_WrongArgs_NotRunnable ()
void TheoryAttribute_NoArgs_NoCases ()
void TheoryAttribute_WithArgs_Runnable ()
void CombinatorialAttribute_NoArgs_NoCases ()
void CombinatorialAttribute_WithArgs_Runnable ()
void PairwiseAttribute_NoArgs_NoCases ()
void PairwiseAttribute_WithArgs_Runnable ()
void SequentialAttribute_NoArgs_NoCases ()
void SequentialAttribute_WithArgs_Runnable ()
Static Public Member Functions
static void MethodWithoutArgs ()
static void MethodWithIntArgs (int x, int y)
static void MethodWithIntValues ([Values(1, 2, 3)]int x, [Values(10, 20)]int y)
Private Member Functions
IMethodInfo GetMethod (string methodName)
Private Attributes
int[] ints = new int[] { 1, 2, 3 }
Static Private Attributes
static object[] GoodData
static object[] BadData
Member Function Documentation
TestAttribute_NoArgs_Runnable()
void NUnit.Framework.Attributes.TestMethodBuilderTests.TestAttribute_NoArgs_Runnable () inline
References NUnit.Framework.TestAttribute.BuildFrom(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TestMethodBuilderTests.GetMethod(), NUnit.Framework.Internal.Test.RunState, and NUnit.Framework.Assert.That().
TestAttribute_WithArgs_NotRunnable()
void NUnit.Framework.Attributes.TestMethodBuilderTests.TestAttribute_WithArgs_NotRunnable () inline
References NUnit.Framework.TestAttribute.BuildFrom(), NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TestMethodBuilderTests.GetMethod(), NUnit.Framework.Internal.Test.RunState, and NUnit.Framework.Assert.That().
TestCaseAttribute_NoArgs_NotRunnable()
void NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseAttribute_NoArgs_NotRunnable () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TestMethodBuilderTests.GetMethod(), and NUnit.Framework.Assert.That().
TestCaseAttribute_RightArgs_Runnable()
void NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseAttribute_RightArgs_Runnable () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TestMethodBuilderTests.GetMethod(), and NUnit.Framework.Assert.That().
TestCaseAttribute_WrongArgs_NotRunnable()
void NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseAttribute_WrongArgs_NotRunnable () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TestMethodBuilderTests.GetMethod(), and NUnit.Framework.Assert.That().
TestCaseSourceAttribute_NoArgs_NotRunnable()
void NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseSourceAttribute_NoArgs_NotRunnable () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TestMethodBuilderTests.GetMethod(), and NUnit.Framework.Assert.That().
TestCaseSourceAttribute_RightArgs_Runnable()
void NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseSourceAttribute_RightArgs_Runnable () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TestMethodBuilderTests.GetMethod(), and NUnit.Framework.Assert.That().
TestCaseSourceAttribute_WrongArgs_NotRunnable()
void NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseSourceAttribute_WrongArgs_NotRunnable () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TestMethodBuilderTests.GetMethod(), and NUnit.Framework.Assert.That().
TheoryAttribute_NoArgs_NoCases()
void NUnit.Framework.Attributes.TestMethodBuilderTests.TheoryAttribute_NoArgs_NoCases () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TestMethodBuilderTests.GetMethod(), and NUnit.Framework.Assert.That().
TheoryAttribute_WithArgs_Runnable()
void NUnit.Framework.Attributes.TestMethodBuilderTests.TheoryAttribute_WithArgs_Runnable () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TestMethodBuilderTests.GetMethod(), and NUnit.Framework.Assert.That().
CombinatorialAttribute_NoArgs_NoCases()
void NUnit.Framework.Attributes.TestMethodBuilderTests.CombinatorialAttribute_NoArgs_NoCases () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TestMethodBuilderTests.GetMethod(), and NUnit.Framework.Assert.That().
CombinatorialAttribute_WithArgs_Runnable()
void NUnit.Framework.Attributes.TestMethodBuilderTests.CombinatorialAttribute_WithArgs_Runnable () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TestMethodBuilderTests.GetMethod(), and NUnit.Framework.Assert.That().
PairwiseAttribute_NoArgs_NoCases()
void NUnit.Framework.Attributes.TestMethodBuilderTests.PairwiseAttribute_NoArgs_NoCases () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TestMethodBuilderTests.GetMethod(), and NUnit.Framework.Assert.That().
PairwiseAttribute_WithArgs_Runnable()
void NUnit.Framework.Attributes.TestMethodBuilderTests.PairwiseAttribute_WithArgs_Runnable () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TestMethodBuilderTests.GetMethod(), and NUnit.Framework.Assert.That().
SequentialAttribute_NoArgs_NoCases()
void NUnit.Framework.Attributes.TestMethodBuilderTests.SequentialAttribute_NoArgs_NoCases () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TestMethodBuilderTests.GetMethod(), and NUnit.Framework.Assert.That().
SequentialAttribute_WithArgs_Runnable()
void NUnit.Framework.Attributes.TestMethodBuilderTests.SequentialAttribute_WithArgs_Runnable () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Attributes.TestMethodBuilderTests.GetMethod(), and NUnit.Framework.Assert.That().
GetMethod()
IMethodInfo NUnit.Framework.Attributes.TestMethodBuilderTests.GetMethod (string methodName) inline private
Referenced by NUnit.Framework.Attributes.TestMethodBuilderTests.CombinatorialAttribute_NoArgs_NoCases(), NUnit.Framework.Attributes.TestMethodBuilderTests.CombinatorialAttribute_WithArgs_Runnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.PairwiseAttribute_NoArgs_NoCases(), NUnit.Framework.Attributes.TestMethodBuilderTests.PairwiseAttribute_WithArgs_Runnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.SequentialAttribute_NoArgs_NoCases(), NUnit.Framework.Attributes.TestMethodBuilderTests.SequentialAttribute_WithArgs_Runnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestAttribute_NoArgs_Runnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestAttribute_WithArgs_NotRunnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseAttribute_NoArgs_NotRunnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseAttribute_RightArgs_Runnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseAttribute_WrongArgs_NotRunnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseSourceAttribute_NoArgs_NotRunnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseSourceAttribute_RightArgs_Runnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TestCaseSourceAttribute_WrongArgs_NotRunnable(), NUnit.Framework.Attributes.TestMethodBuilderTests.TheoryAttribute_NoArgs_NoCases(), and NUnit.Framework.Attributes.TestMethodBuilderTests.TheoryAttribute_WithArgs_Runnable().
MethodWithoutArgs()
static void NUnit.Framework.Attributes.TestMethodBuilderTests.MethodWithoutArgs () inline static
MethodWithIntArgs()
static void NUnit.Framework.Attributes.TestMethodBuilderTests.MethodWithIntArgs (int x, int y) inline static
MethodWithIntValues()
static void NUnit.Framework.Attributes.TestMethodBuilderTests.MethodWithIntValues ([Values(1, 2, 3)] int x, [Values(10, 20)] int y) inline static
Member Data Documentation
GoodData
object [] NUnit.Framework.Attributes.TestMethodBuilderTests.GoodData static private
Initial value:
= new object[] {
            new object[] { 12, 3 },
            new object[] { 12, 4 },
            new object[] { 12, 6 } }
BadData
object [] NUnit.Framework.Attributes.TestMethodBuilderTests.BadData static private
Initial value:
= new object[] {
            new object[] { 12, 3, 4 },
            new object[] { 12, 4, 3 },
            new object[] { 12, 6, 2 } }
ints
int [] NUnit.Framework.Attributes.TestMethodBuilderTests.ints = new int[] { 1, 2, 3 } private
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Attributes/TestMethodBuilderTests.cs