Doc: IGLib EXTENDED: IG.Neural.ProgramTestTadej Class Reference
IG.Neural.ProgramTestTadej Class Reference
Static Public Member Functions
static void RunConvectionSim (int numRuns)
static void PrepareInputData (int numRuns)
static void PrepareInputFile (IVector inputParam)
static void ReadOutputFile (ref IVector outputValue)
static void PrepareFinalFile (IVector inputParam, IVector outputVal)
static void FromLogarithmicToNormalTrainingData (SampledDataSet logarithmicData, ref SampledDataSet normalData)
static void FilterTrainingData (SampledDataSet trainingData, ref SampledDataSet newTrainingData)
static void SaveNetworkNeuron (string directoryPath, string fileName, string internalStateFileName, SampledDataSet trainingData, int nnType)
static void LoadNetworkNeuron (string directoryPath, string fileName, string internalStateFileName, ref INeuralApproximator approximator, int nnType)
static void SeparateTrainingData (INeuralApproximator neuralNeuron)
Separate Complete training data in training data and verification data.
static NeuralApproximatorBase ExampleStoreNeuron (SampledDataSet trainingData, SampledDataSet verificationData, int nnType)
static void TestPrediction (string filePath, INeuralApproximator approximator, bool testFromFile)
Static Public Attributes
static List< IVector > inputParams c:\COBIK\Workspace\develop\shell\extensions\ExtTestTadej\bin\Debug\Final.txt"c:\COBIK\workspaceprojects\13_05_tadej_exams\ConvectionCavity\train\opt\Sim_main\2DNatConvCavity.exe"
static TextWriter textwr c:\COBIK\Workspace\develop\shell\extensions\ExtTestTadej\bin\Debug\output.txt"
Static Private Member Functions
static void Main (string[] args)
Member Function Documentation
Main()
static void IG.Neural.ProgramTestTadej.Main (string[] args) inline static private
References IG.Neural.ProgramTestTadej.ExampleStoreNeuron(), IG.Lib.UtilSystem.IsUserIgor, and IG.Neural.NeuralTadej.LoadSampledDataJson().
RunConvectionSim()
static void IG.Neural.ProgramTestTadej.RunConvectionSim (int numRuns) inline static
References IG.Neural.ProgramTestTadej.inputParams, IG.Neural.ProgramTestTadej.PrepareFinalFile(), IG.Neural.ProgramTestTadej.PrepareInputData(), IG.Neural.ProgramTestTadej.PrepareInputFile(), IG.Neural.ProgramTestTadej.ReadOutputFile(), and IG.Neural.ProgramTestTadej.textwr.
PrepareInputData()
static void IG.Neural.ProgramTestTadej.PrepareInputData (int numRuns) inline static
References IG.Neural.ProgramTestTadej.inputParams.
Referenced by IG.Neural.ProgramTestTadej.RunConvectionSim().
PrepareInputFile()
static void IG.Neural.ProgramTestTadej.PrepareInputFile (IVector inputParam) inline static
Referenced by IG.Neural.ProgramTestTadej.RunConvectionSim().
ReadOutputFile()
static void IG.Neural.ProgramTestTadej.ReadOutputFile (ref IVector outputValue) inline static
Referenced by IG.Neural.ProgramTestTadej.RunConvectionSim().
PrepareFinalFile()
static void IG.Neural.ProgramTestTadej.PrepareFinalFile (IVector inputParam, IVector outputVal) inline static
References IG.Num.IVector< T >.Length, and IG.Neural.ProgramTestTadej.textwr.
Referenced by IG.Neural.ProgramTestTadej.RunConvectionSim().
FromLogarithmicToNormalTrainingData()
static void IG.Neural.ProgramTestTadej.FromLogarithmicToNormalTrainingData (SampledDataSet logarithmicData, ref SampledDataSet normalData) inline static
References IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.InputLength, IG.Num.IVector< T >.Length, IG.Num.SampledDataSet.Length, and IG.Num.SampledDataSet.OutputLength.
FilterTrainingData()
static void IG.Neural.ProgramTestTadej.FilterTrainingData (SampledDataSet trainingData, ref SampledDataSet newTrainingData) inline static
References IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.InputLength, IG.Num.IVector< T >.Length, IG.Num.SampledDataSet.Length, IG.Neural.NeuralTadej.LoadDefinitionDataJson(), and IG.Num.SampledDataSet.OutputLength.
SaveNetworkNeuron()
static void IG.Neural.ProgramTestTadej.SaveNetworkNeuron (string directoryPath, string fileName, string internalStateFileName, SampledDataSet trainingData, int nnType) inline static
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyFrom(), IG.Neural.ProgramTestTadej.ExampleStoreNeuron(), IG.Num.INeuralApproximator.GetErrorsTrainingRms(), IG.Num.SampledDataSet.InputLength, IG.Num.INeuralApproximator.NetworkStateFilePath, IG.Num.IVectorApproximator.OutputLength, IG.Num.SampledDataSet.OutputLength, and IG.Num.NeuralApproximatorBase.SaveJson().
LoadNetworkNeuron()
static void IG.Neural.ProgramTestTadej.LoadNetworkNeuron (string directoryPath, string fileName, string internalStateFileName, ref INeuralApproximator approximator, int nnType) inline static
References IG.Lib.SerializationDtoBase< Type, BaseType >.CopyTo().
SeparateTrainingData()
static void IG.Neural.ProgramTestTadej.SeparateTrainingData (INeuralApproximator neuralNeuron) inline static
Separate Complete training data in training data and verification data.
Parameters
neuralNeuron
References IG.Num.SampledDataSet.AddElement(), IG.Lib.SortedUniqueItemList< Type >.Contains(), IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.SampledDataSet.InputLength, IG.Num.SampledDataSet.Length, IG.Num.SampledDataSet.OutputLength, IG.Neural.NeuralTadej.SaveTrainingDataJson(), IG.Num.INeuralApproximator.TrainingData, and IG.Num.INeuralApproximator.VerificationIndices.
Referenced by IG.Neural.ProgramTestTadej.ExampleStoreNeuron().
ExampleStoreNeuron()
static NeuralApproximatorBase IG.Neural.ProgramTestTadej.ExampleStoreNeuron (SampledDataSet trainingData, SampledDataSet verificationData, int nnType) inline static
References IG.Num.NeuralApproximatorBase.CalculateOutput(), IG.Lib.SortedUniqueItemList< Type >.Contains(), IG.Lib.IndexList.CreateRandom(), IG.Num.NeuralApproximatorBase.EpochsInBundle, IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.NeuralApproximatorBase.InputBoundsSafetyFactor, IG.Num.SampledDataSet.InputLength, IG.Num.NeuralApproximatorBase.InputLength, IG.Num.NeuralApproximatorBase.InputNeuronsRange, IG.Num.NeuralApproximatorBase.LearningRate, IG.Num.SampledDataSet.Length, IG.Num.NeuralApproximatorBase.MaxEpochs, IG.Num.NeuralApproximatorBase.Momentum, IG.Num.NeuralApproximatorBase.MultipleNetworks, IG.Num.NeuralApproximatorBase.OutputBoundsSafetyFactor, IG.Num.SampledDataSet.OutputLength, IG.Num.NeuralApproximatorBase.OutputLength, IG.Num.NeuralApproximatorBase.OutputLevel, IG.Num.NeuralApproximatorBase.OutputNeuronsRange, IG.Num.IBoundingBox.Reset(), IG.Num.NeuralApproximatorBase.SaveConvergenceRms, IG.Neural.ProgramTestTadej.SeparateTrainingData(), IG.Num.NeuralApproximatorBase.SetHiddenLayers(), IG.Num.NeuralApproximatorBase.SigmoidAlphaValue, IG.Num.VectorBase.Subtract(), IG.Num.NeuralApproximatorBase.ToleranceRms, IG.Num.IVector< T >.ToString(), IG.Num.NeuralApproximatorBase.ToString(), IG.Num.NeuralApproximatorBase.TrainingData, IG.Num.NeuralApproximatorBase.TrainNetwork(), IG.Num.IBoundingBox.UpdateAll(), and IG.Num.NeuralApproximatorBase.VerificationIndices.
Referenced by IG.Neural.ProgramTestTadej.Main(), and IG.Neural.ProgramTestTadej.SaveNetworkNeuron().
TestPrediction()
static void IG.Neural.ProgramTestTadej.TestPrediction (string filePath, INeuralApproximator approximator, bool testFromFile) inline static
Parameters
filePath File path for writing analysis.
approximator Neural network
testFromFile If true, testing data loaded from file.
References IG.Num.IVectorApproximator.CalculateOutput(), IG.Lib.SortedUniqueItemList< Type >.Contains(), IG.Num.INeuralApproximator.GetErrorsTrainingMeanAbs(), IG.Num.INeuralApproximator.GetErrorsVerificationMeanAbs(), IG.Num.SampledDataSet.GetInputParameters(), IG.Num.SampledDataSet.GetOutputRange(), IG.Num.SampledDataSet.GetOutputValues(), IG.Num.IVector< T >.Length, IG.Num.SampledDataSet.Length, IG.Neural.NeuralTadej.LoadTrainingDataCSV(), IG.Num.IVectorApproximator.OutputLength, IG.Num.SampledDataSet.OutputLength, IG.Num.INeuralApproximator.TrainingData, and IG.Num.INeuralApproximator.VerificationIndices.
Member Data Documentation
inputParams
List<IVector> IG.Neural.ProgramTestTadej.inputParams c:\COBIK\Workspace\develop\shell\extensions\ExtTestTadej\bin\Debug\Final.txt"c:\COBIK\workspaceprojects\13_05_tadej_exams\ConvectionCavity\train\opt\Sim_main\2DNatConvCavity.exe" static
Referenced by IG.Neural.ProgramTestTadej.PrepareInputData(), and IG.Neural.ProgramTestTadej.RunConvectionSim().
textwr
TextWriter IG.Neural.ProgramTestTadej.textwr c:\COBIK\Workspace\develop\shell\extensions\ExtTestTadej\bin\Debug\output.txt" static
Referenced by IG.Neural.ProgramTestTadej.PrepareFinalFile(), and IG.Neural.ProgramTestTadej.RunConvectionSim().
The documentation for this class was generated from the following file:
shelldev/extensions_shell/ExtTestTadej/ProgramExtTestTadej.cs