Doc: IGLib EXTENDED: NUnit.Framework.Internal.TestXmlTests Class Reference
NUnit.Framework.Internal.TestXmlTests Class Reference
Classes
class DummyFixture
class DummyGenericFixture
Public Member Functions
void SetUp ()
void TestTypeTests ()
void TestMethodToXml ()
void TestFixtureToXml ()
void TestFixtureToXml_Recursive ()
void TestSuiteToXml ()
void TestSuiteToXml_Recursive ()
void TestNameWithInvalidCharacter ()
Private Member Functions
void CheckXmlForTest (Test test, bool recursive)
void CheckXmlForTest (Test test, TNode topNode, bool recursive)
Private Attributes
TestSuite testSuite
TestFixture testFixture
TestMethod testMethod
Member Function Documentation
SetUp()
void NUnit.Framework.Internal.TestXmlTests.SetUp () inline
References NUnit.Framework.Interfaces.IPropertyBag.Add(), NUnit.Framework.Internal.PropertyNames.Category, NUnit.Framework.Internal.PropertyNames.Description, NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Interfaces.IPropertyBag.Set(), NUnit.Framework.Internal.TestXmlTests.testFixture, NUnit.Framework.Internal.TestXmlTests.testMethod, NUnit.Framework.Internal.TestSuite.Tests, and NUnit.Framework.Internal.TestXmlTests.testSuite.
TestTypeTests()
void NUnit.Framework.Internal.TestXmlTests.TestTypeTests () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestXmlTests.testFixture, NUnit.Framework.Internal.TestXmlTests.testMethod, NUnit.Framework.Internal.TestXmlTests.testSuite, NUnit.Framework.Internal.Test.TestType, and NUnit.Framework.Assert.That().
TestMethodToXml()
void NUnit.Framework.Internal.TestXmlTests.TestMethodToXml () inline
References NUnit.Framework.Internal.TestXmlTests.CheckXmlForTest(), and NUnit.Framework.Internal.TestXmlTests.testMethod.
TestFixtureToXml()
void NUnit.Framework.Internal.TestXmlTests.TestFixtureToXml () inline
References NUnit.Framework.Internal.TestXmlTests.CheckXmlForTest(), and NUnit.Framework.Internal.TestXmlTests.testFixture.
TestFixtureToXml_Recursive()
void NUnit.Framework.Internal.TestXmlTests.TestFixtureToXml_Recursive () inline
References NUnit.Framework.Internal.TestXmlTests.CheckXmlForTest(), and NUnit.Framework.Internal.TestXmlTests.testFixture.
TestSuiteToXml()
void NUnit.Framework.Internal.TestXmlTests.TestSuiteToXml () inline
References NUnit.Framework.Internal.TestXmlTests.CheckXmlForTest(), and NUnit.Framework.Internal.TestXmlTests.testSuite.
TestSuiteToXml_Recursive()
void NUnit.Framework.Internal.TestXmlTests.TestSuiteToXml_Recursive () inline
References NUnit.Framework.Internal.TestXmlTests.CheckXmlForTest(), and NUnit.Framework.Internal.TestXmlTests.testSuite.
TestNameWithInvalidCharacter()
void NUnit.Framework.Internal.TestXmlTests.TestNameWithInvalidCharacter () inline
References NUnit.Framework.Internal.Test.Name, NUnit.Framework.Interfaces.TNode.OuterXml, NUnit.Framework.Contains.Substring(), NUnit.Framework.Internal.TestXmlTests.testMethod, NUnit.Framework.Assert.That(), and NUnit.Framework.Internal.Test.ToXml().
CheckXmlForTest() [1/2]
void NUnit.Framework.Internal.TestXmlTests.CheckXmlForTest (Test test, bool recursive) inline private
References NUnit.Framework.Internal.Test.ToXml().
Referenced by NUnit.Framework.Internal.TestXmlTests.CheckXmlForTest(), NUnit.Framework.Internal.TestXmlTests.TestFixtureToXml(), NUnit.Framework.Internal.TestXmlTests.TestFixtureToXml_Recursive(), NUnit.Framework.Internal.TestXmlTests.TestMethodToXml(), NUnit.Framework.Internal.TestXmlTests.TestSuiteToXml(), and NUnit.Framework.Internal.TestXmlTests.TestSuiteToXml_Recursive().
CheckXmlForTest() [2/2]
void NUnit.Framework.Internal.TestXmlTests.CheckXmlForTest (Test test, TNode topNode, bool recursive) inline private
References NUnit.Framework.Interfaces.TNode.Attributes, NUnit.Framework.Internal.TestXmlTests.CheckXmlForTest(), NUnit.Framework.Interfaces.TNode.ChildNodes, NUnit.Framework.Internal.Test.ClassName, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Is.EquivalentTo(), NUnit.Framework.Internal.Test.FullName, NUnit.Framework.Internal.Test.Id, NUnit.Framework.Interfaces.IPropertyBag.Keys, NUnit.Framework.Internal.Test.MethodName, NUnit.Framework.Interfaces.TNode.Name, NUnit.Framework.Internal.Test.Name, NUnit.Framework.Assert.NotNull(), NUnit.Framework.Internal.Test.Properties, NUnit.Framework.Internal.Test.RunState, NUnit.Framework.Interfaces.TNode.SelectSingleNode(), NUnit.Framework.Internal.TestSuite.Tests, NUnit.Framework.Assert.That(), NUnit.Framework.Internal.Test.TypeInfo, and NUnit.Framework.Internal.Test.XmlElementName.
Member Data Documentation
testSuite
TestSuite NUnit.Framework.Internal.TestXmlTests.testSuite private
Referenced by NUnit.Framework.Internal.TestXmlTests.SetUp(), NUnit.Framework.Internal.TestXmlTests.TestSuiteToXml(), NUnit.Framework.Internal.TestXmlTests.TestSuiteToXml_Recursive(), and NUnit.Framework.Internal.TestXmlTests.TestTypeTests().
testFixture
TestFixture NUnit.Framework.Internal.TestXmlTests.testFixture private
Referenced by NUnit.Framework.Internal.TestXmlTests.SetUp(), NUnit.Framework.Internal.TestXmlTests.TestFixtureToXml(), NUnit.Framework.Internal.TestXmlTests.TestFixtureToXml_Recursive(), and NUnit.Framework.Internal.TestXmlTests.TestTypeTests().
testMethod
TestMethod NUnit.Framework.Internal.TestXmlTests.testMethod private
Referenced by NUnit.Framework.Internal.TestXmlTests.SetUp(), NUnit.Framework.Internal.TestXmlTests.TestMethodToXml(), NUnit.Framework.Internal.TestXmlTests.TestNameWithInvalidCharacter(), and NUnit.Framework.Internal.TestXmlTests.TestTypeTests().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/TestXmlTests.cs