Doc: IGLib EXTENDED: IG.Forms.NotificationFrame Class Reference
IG.Forms.NotificationFrame Class Reference
Public Member Functions
NotificationFrame ()
void ShowNotification (string title, string message, ReportType? notificationtype=null)
NotificationFrame ()
void ShowNotification (string title, string message, ReportType? notificationtype=null)
Protected Member Functions
override void Dispose (bool disposing)
Clean up any resources being used.
override void Dispose (bool disposing)
Clean up any resources being used.
Private Member Functions
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
void InitializeComponent ()
Required method for Designer support - do not modify the contents of this method with the code editor.
Private Attributes
System.ComponentModel.IContainer components = null
Required designer variable.
NotificationPanel notificationFrame1
NotificationPanel notificationFrame2
NotificationPanel notificationPanel1
NotificationPanel notificationPanel2
NotificationPanel notificationPanel3
NotificationPanel notificationPanel4
Constructor & Destructor Documentation
NotificationFrame() [1/2]
IG.Forms.NotificationFrame.NotificationFrame () inline
References IG.Forms.NotificationFrame.InitializeComponent().
NotificationFrame() [2/2]
IG.Forms.NotificationFrame.NotificationFrame () inline
References IG.Forms.NotificationFrame.InitializeComponent().
Member Function Documentation
ShowNotification() [1/2]
void IG.Forms.NotificationFrame.ShowNotification (string title, string message, ReportType? notificationtype = null) inline
References IG.Forms.NotificationParameters.DefaultType.
Referenced by IG.Forms.HashDirControl.ShowNotification().
Dispose() [1/2]
override void IG.Forms.NotificationFrame.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.NotificationFrame.components.
InitializeComponent() [1/2]
void IG.Forms.NotificationFrame.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.NotificationPanel.BackgroundColor, IG.Forms.NotificationPanel.ErrorColor, IG.Forms.NotificationPanel.ErrorTitle, IG.Forms.NotificationPanel.FadeColor, IG.Forms.NotificationPanel.FadingPortion, IG.Forms.NotificationPanel.FadingTime, IG.Forms.NotificationPanel.InfoTitle, IG.Forms.NotificationPanel.Message, IG.Forms.NotificationPanel.MessageColor, IG.Forms.NotificationPanel.NonFadingTime, IG.Forms.NotificationFrame.notificationPanel3, IG.Forms.NotificationFrame.notificationPanel4, IG.Forms.NotificationPanel.OtherBackgroundColor, IG.Forms.NotificationPanel.OtherTitle, IG.Forms.NotificationPanel.ShowTime, IG.Forms.NotificationPanel.ShowTmeMilliseconds, IG.Forms.NotificationPanel.TimerInterval, IG.Forms.NotificationPanel.TimerIntervalMilliseconds, IG.Forms.NotificationPanel.Title, IG.Forms.NotificationPanel.TitleColor, IG.Forms.NotificationPanel.Type, IG.Forms.NotificationPanel.WarningColor, and IG.Forms.NotificationPanel.WarningTitle.
Referenced by IG.Forms.NotificationFrame.NotificationFrame().
ShowNotification() [2/2]
void IG.Forms.NotificationFrame.ShowNotification (string title, string message, ReportType? notificationtype = null) inline
References IG.Forms.NotificationParameters.DefaultType.
Dispose() [2/2]
override void IG.Forms.NotificationFrame.Dispose (bool disposing) inline protected
Clean up any resources being used.
Parameters
disposing true if managed resources should be disposed; otherwise, false.
References IG.Forms.NotificationFrame.components.
InitializeComponent() [2/2]
void IG.Forms.NotificationFrame.InitializeComponent () inline private
Required method for Designer support - do not modify the contents of this method with the code editor.
References IG.Forms.NotificationPanel.BackgroundColor, IG.Forms.NotificationPanel.ErrorColor, IG.Forms.NotificationPanel.ErrorTitle, IG.Forms.NotificationPanel.FadeColor, IG.Forms.NotificationPanel.FadingPortion, IG.Forms.NotificationPanel.FadingTime, IG.Forms.NotificationPanel.InfoTitle, IG.Forms.NotificationPanel.Message, IG.Forms.NotificationPanel.MessageColor, IG.Forms.NotificationPanel.NonFadingTime, IG.Forms.NotificationFrame.notificationPanel3, IG.Forms.NotificationFrame.notificationPanel4, IG.Forms.NotificationPanel.OtherBackgroundColor, IG.Forms.NotificationPanel.OtherTitle, IG.Forms.NotificationPanel.ShowTime, IG.Forms.NotificationPanel.ShowTmeMilliseconds, IG.Forms.NotificationPanel.TimerInterval, IG.Forms.NotificationPanel.TimerIntervalMilliseconds, IG.Forms.NotificationPanel.Title, IG.Forms.NotificationPanel.TitleColor, IG.Forms.NotificationPanel.Type, IG.Forms.NotificationPanel.WarningColor, and IG.Forms.NotificationPanel.WarningTitle.
Member Data Documentation
components
System ComponentModel IContainer IG.Forms.NotificationFrame.components = null private
Required designer variable.
Referenced by IG.Forms.NotificationFrame.Dispose().
notificationFrame1
NotificationPanel IG.Forms.NotificationFrame.notificationFrame1 private
notificationFrame2
NotificationPanel IG.Forms.NotificationFrame.notificationFrame2 private
notificationPanel1
NotificationPanel IG.Forms.NotificationFrame.notificationPanel1 private
notificationPanel2
NotificationPanel IG.Forms.NotificationFrame.notificationPanel2 private
notificationPanel3
NotificationPanel IG.Forms.NotificationFrame.notificationPanel3 private
Referenced by IG.Forms.NotificationFrame.InitializeComponent().
notificationPanel4
NotificationPanel IG.Forms.NotificationFrame.notificationPanel4 private
Referenced by IG.Forms.NotificationFrame.InitializeComponent().
The documentation for this class was generated from the following files:
iglib/igforms/Utilities/Notification/NotificationFrame.cs
iglib/igforms/Utilities/Notification/NotificationFrame.Designer.cs