Doc: IGLib EXTENDED: JavaScience.PswdDialog Class Reference
JavaScience.PswdDialog Class Reference
Public Member Functions
PswdDialog (String title)
PswdDialog ()
String GetPswd ()
Static Public Member Functions
static void Main1 ()
Private Member Functions
void LoadImageIcon ()
void InitializeComponent ()
Private Attributes
String TITLE = "PswdDialog"
String ICONIMAGE = "JavaScience.keylock.ico"
Label lbl
TextBox pwbox
Button okButton
Button cancelButton
PictureBox imagebox
Constructor & Destructor Documentation
PswdDialog() [1/2]
JavaScience.PswdDialog.PswdDialog (String title) inline
References JavaScience.PswdDialog.InitializeComponent(), and JavaScience.PswdDialog.LoadImageIcon().
PswdDialog() [2/2]
JavaScience.PswdDialog.PswdDialog () inline
References JavaScience.PswdDialog.InitializeComponent(), and JavaScience.PswdDialog.LoadImageIcon().
Referenced by JavaScience.PswdDialog.Main1().
Member Function Documentation
GetPswd()
String JavaScience.PswdDialog.GetPswd () inline
References JavaScience.PswdDialog.pwbox.
Referenced by JavaScience.PswdDialog.Main1(), and JavaScience.TestPfx.MainPfx().
LoadImageIcon()
void JavaScience.PswdDialog.LoadImageIcon () inline private
References JavaScience.PswdDialog.ICONIMAGE, and JavaScience.PswdDialog.imagebox.
Referenced by JavaScience.PswdDialog.PswdDialog().
InitializeComponent()
void JavaScience.PswdDialog.InitializeComponent () inline private
References JavaScience.PswdDialog.cancelButton, JavaScience.PswdDialog.imagebox, JavaScience.PswdDialog.lbl, JavaScience.PswdDialog.okButton, JavaScience.PswdDialog.pwbox, and JavaScience.PswdDialog.TITLE.
Referenced by JavaScience.PswdDialog.PswdDialog().
Main1()
static void JavaScience.PswdDialog.Main1 () inline static
References JavaScience.PswdDialog.GetPswd(), and JavaScience.PswdDialog.PswdDialog().
Member Data Documentation
TITLE
String JavaScience.PswdDialog.TITLE = "PswdDialog" private
Referenced by JavaScience.PswdDialog.InitializeComponent().
ICONIMAGE
String JavaScience.PswdDialog.ICONIMAGE = "JavaScience.keylock.ico" private
Referenced by JavaScience.PswdDialog.LoadImageIcon().
lbl
Label JavaScience.PswdDialog.lbl private
Referenced by JavaScience.PswdDialog.InitializeComponent().
pwbox
TextBox JavaScience.PswdDialog.pwbox private
Referenced by JavaScience.PswdDialog.GetPswd(), and JavaScience.PswdDialog.InitializeComponent().
okButton
Button JavaScience.PswdDialog.okButton private
Referenced by JavaScience.PswdDialog.InitializeComponent().
cancelButton
Button JavaScience.PswdDialog.cancelButton private
Referenced by JavaScience.PswdDialog.InitializeComponent().
imagebox
PictureBox JavaScience.PswdDialog.imagebox private
Referenced by JavaScience.PswdDialog.InitializeComponent(), and JavaScience.PswdDialog.LoadImageIcon().
The documentation for this class was generated from the following file:
igtest/iglib_sandbox/encryption/pkcs12/PswdDialog.cs