Doc: IGLib EXTENDED: NUnit.Engine.Internal.Tests.ServerUtilityTests Class Reference
NUnit.Engine.Internal.Tests.ServerUtilityTests Class Reference
Summary description for RemotingUtilitiesTests.
Public Member Functions
void ReleaseChannels ()
void CanGetTcpChannelOnSpecifiedPort ()
void CanGetTcpChannelOnUnspecifiedPort ()
Private Attributes
TcpChannel channel1
TcpChannel channel2
Detailed Description
Summary description for RemotingUtilitiesTests.
Member Function Documentation
ReleaseChannels()
void NUnit.Engine.Internal.Tests.ServerUtilityTests.ReleaseChannels () inline
References NUnit.Engine.Internal.Tests.ServerUtilityTests.channel1, NUnit.Engine.Internal.Tests.ServerUtilityTests.channel2, and NUnit.Engine.Internal.ServerUtilities.SafeReleaseChannel().
CanGetTcpChannelOnSpecifiedPort()
void NUnit.Engine.Internal.Tests.ServerUtilityTests.CanGetTcpChannelOnSpecifiedPort () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Assert.AreSame(), NUnit.Engine.Internal.Tests.ServerUtilityTests.channel1, NUnit.Engine.Internal.Tests.ServerUtilityTests.channel2, and NUnit.Engine.Internal.ServerUtilities.GetTcpChannel().
CanGetTcpChannelOnUnspecifiedPort()
void NUnit.Engine.Internal.Tests.ServerUtilityTests.CanGetTcpChannelOnUnspecifiedPort () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Assert.AreSame(), NUnit.Engine.Internal.Tests.ServerUtilityTests.channel1, NUnit.Engine.Internal.Tests.ServerUtilityTests.channel2, and NUnit.Engine.Internal.ServerUtilities.GetTcpChannel().
Member Data Documentation
channel1
TcpChannel NUnit.Engine.Internal.Tests.ServerUtilityTests.channel1 private
Referenced by NUnit.Engine.Internal.Tests.ServerUtilityTests.CanGetTcpChannelOnSpecifiedPort(), NUnit.Engine.Internal.Tests.ServerUtilityTests.CanGetTcpChannelOnUnspecifiedPort(), and NUnit.Engine.Internal.Tests.ServerUtilityTests.ReleaseChannels().
channel2
TcpChannel NUnit.Engine.Internal.Tests.ServerUtilityTests.channel2 private
Referenced by NUnit.Engine.Internal.Tests.ServerUtilityTests.CanGetTcpChannelOnSpecifiedPort(), NUnit.Engine.Internal.Tests.ServerUtilityTests.CanGetTcpChannelOnUnspecifiedPort(), and NUnit.Engine.Internal.Tests.ServerUtilityTests.ReleaseChannels().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/nunit.engine.tests/Internal/ServerUtilityTests.cs