Doc: IGLib EXTENDED: TestWS_GUI.EFA_WS.Service Class Reference
TestWS_GUI.EFA_WS.Service Class Reference
Public Member Functions
Service ()
string PosljiPaket (string paketXml)
void PosljiPaketAsync (string paketXml)
void PosljiPaketAsync (string paketXml, object userState)
string PosljiPaketZip ([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] paketZip)
void PosljiPaketZipAsync (byte[] paketZip)
void PosljiPaketZipAsync (byte[] paketZip, object userState)
int StevilkaSeje ()
void StevilkaSejeAsync ()
void StevilkaSejeAsync (object userState)
string PaketStatus (decimal paketid)
void PaketStatusAsync (decimal paketid)
void PaketStatusAsync (decimal paketid, object userState)
byte[] PaketShema ()
void PaketShemaAsync ()
void PaketShemaAsync (object userState)
byte[] PaketStatusShema ()
void PaketStatusShemaAsync ()
void PaketStatusShemaAsync (object userState)
System.Data.DataSet PaketTipZalogaVrednosti ()
void PaketTipZalogaVrednostiAsync ()
void PaketTipZalogaVrednostiAsync (object userState)
System.Data.DataSet PaketStatusZalogaVrednosti ()
void PaketStatusZalogaVrednostiAsync ()
void PaketStatusZalogaVrednostiAsync (object userState)
System.Data.DataSet PodrocjaZalogaVrednosti ()
void PodrocjaZalogaVrednostiAsync ()
void PodrocjaZalogaVrednostiAsync (object userState)
new void CancelAsync (object userState)
Properties
new string Url [get, set]
new bool UseDefaultCredentials [get, set]
Events
PosljiPaketCompletedEventHandler PosljiPaketCompleted
PosljiPaketZipCompletedEventHandler PosljiPaketZipCompleted
StevilkaSejeCompletedEventHandler StevilkaSejeCompleted
PaketStatusCompletedEventHandler PaketStatusCompleted
PaketShemaCompletedEventHandler PaketShemaCompleted
PaketStatusShemaCompletedEventHandler PaketStatusShemaCompleted
PaketTipZalogaVrednostiCompletedEventHandler PaketTipZalogaVrednostiCompleted
PaketStatusZalogaVrednostiCompletedEventHandler PaketStatusZalogaVrednostiCompleted
PodrocjaZalogaVrednostiCompletedEventHandler PodrocjaZalogaVrednostiCompleted
Private Member Functions
void OnPosljiPaketOperationCompleted (object arg)
void OnPosljiPaketZipOperationCompleted (object arg)
void OnStevilkaSejeOperationCompleted (object arg)
void OnPaketStatusOperationCompleted (object arg)
void OnPaketShemaOperationCompleted (object arg)
void OnPaketStatusShemaOperationCompleted (object arg)
void OnPaketTipZalogaVrednostiOperationCompleted (object arg)
void OnPaketStatusZalogaVrednostiOperationCompleted (object arg)
void OnPodrocjaZalogaVrednostiOperationCompleted (object arg)
bool IsLocalFileSystemWebService (string url)
Private Attributes
System.Threading.SendOrPostCallback PosljiPaketOperationCompleted
System.Threading.SendOrPostCallback PosljiPaketZipOperationCompleted
System.Threading.SendOrPostCallback StevilkaSejeOperationCompleted
System.Threading.SendOrPostCallback PaketStatusOperationCompleted
System.Threading.SendOrPostCallback PaketShemaOperationCompleted
System.Threading.SendOrPostCallback PaketStatusShemaOperationCompleted
System.Threading.SendOrPostCallback PaketTipZalogaVrednostiOperationCompleted
System.Threading.SendOrPostCallback PaketStatusZalogaVrednostiOperationCompleted
System.Threading.SendOrPostCallback PodrocjaZalogaVrednostiOperationCompleted
bool useDefaultCredentialsSetExplicitly
Detailed Description
Constructor & Destructor Documentation
Service()
TestWS_GUI.EFA_WS.Service.Service () inline
References TestWS_GUI.EFA_WS.Service.IsLocalFileSystemWebService(), TestWS_GUI.EFA_WS.Service.Url, and TestWS_GUI.EFA_WS.Service.UseDefaultCredentials.
Member Function Documentation
PosljiPaket()
string TestWS_GUI.EFA_WS.Service.PosljiPaket (string paketXml) inline
PosljiPaketAsync() [1/2]
void TestWS_GUI.EFA_WS.Service.PosljiPaketAsync (string paketXml) inline
PosljiPaketAsync() [2/2]
void TestWS_GUI.EFA_WS.Service.PosljiPaketAsync (string paketXml, object userState) inline
References TestWS_GUI.EFA_WS.Service.OnPosljiPaketOperationCompleted(), and TestWS_GUI.EFA_WS.Service.PosljiPaketOperationCompleted.
OnPosljiPaketOperationCompleted()
void TestWS_GUI.EFA_WS.Service.OnPosljiPaketOperationCompleted (object arg) inline private
References TestWS_GUI.EFA_WS.Service.PosljiPaketCompleted.
Referenced by TestWS_GUI.EFA_WS.Service.PosljiPaketAsync().
PosljiPaketZip()
string TestWS_GUI.EFA_WS.Service.PosljiPaketZip ([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] paketZip) inline
PosljiPaketZipAsync() [1/2]
void TestWS_GUI.EFA_WS.Service.PosljiPaketZipAsync (byte[] paketZip) inline
PosljiPaketZipAsync() [2/2]
void TestWS_GUI.EFA_WS.Service.PosljiPaketZipAsync (byte[] paketZip, object userState) inline
References TestWS_GUI.EFA_WS.Service.OnPosljiPaketZipOperationCompleted(), and TestWS_GUI.EFA_WS.Service.PosljiPaketZipOperationCompleted.
OnPosljiPaketZipOperationCompleted()
void TestWS_GUI.EFA_WS.Service.OnPosljiPaketZipOperationCompleted (object arg) inline private
References TestWS_GUI.EFA_WS.Service.PosljiPaketZipCompleted.
Referenced by TestWS_GUI.EFA_WS.Service.PosljiPaketZipAsync().
StevilkaSeje()
int TestWS_GUI.EFA_WS.Service.StevilkaSeje () inline
StevilkaSejeAsync() [1/2]
void TestWS_GUI.EFA_WS.Service.StevilkaSejeAsync () inline
StevilkaSejeAsync() [2/2]
void TestWS_GUI.EFA_WS.Service.StevilkaSejeAsync (object userState) inline
References TestWS_GUI.EFA_WS.Service.OnStevilkaSejeOperationCompleted(), and TestWS_GUI.EFA_WS.Service.StevilkaSejeOperationCompleted.
OnStevilkaSejeOperationCompleted()
void TestWS_GUI.EFA_WS.Service.OnStevilkaSejeOperationCompleted (object arg) inline private
References TestWS_GUI.EFA_WS.Service.StevilkaSejeCompleted.
Referenced by TestWS_GUI.EFA_WS.Service.StevilkaSejeAsync().
PaketStatus()
string TestWS_GUI.EFA_WS.Service.PaketStatus (decimal paketid) inline
PaketStatusAsync() [1/2]
void TestWS_GUI.EFA_WS.Service.PaketStatusAsync (decimal paketid) inline
PaketStatusAsync() [2/2]
void TestWS_GUI.EFA_WS.Service.PaketStatusAsync (decimal paketid, object userState) inline
References TestWS_GUI.EFA_WS.Service.OnPaketStatusOperationCompleted(), and TestWS_GUI.EFA_WS.Service.PaketStatusOperationCompleted.
OnPaketStatusOperationCompleted()
void TestWS_GUI.EFA_WS.Service.OnPaketStatusOperationCompleted (object arg) inline private
References TestWS_GUI.EFA_WS.Service.PaketStatusCompleted.
Referenced by TestWS_GUI.EFA_WS.Service.PaketStatusAsync().
PaketShema()
byte [] TestWS_GUI.EFA_WS.Service.PaketShema () inline
PaketShemaAsync() [1/2]
void TestWS_GUI.EFA_WS.Service.PaketShemaAsync () inline
PaketShemaAsync() [2/2]
void TestWS_GUI.EFA_WS.Service.PaketShemaAsync (object userState) inline
References TestWS_GUI.EFA_WS.Service.OnPaketShemaOperationCompleted(), and TestWS_GUI.EFA_WS.Service.PaketShemaOperationCompleted.
OnPaketShemaOperationCompleted()
void TestWS_GUI.EFA_WS.Service.OnPaketShemaOperationCompleted (object arg) inline private
References TestWS_GUI.EFA_WS.Service.PaketShemaCompleted.
Referenced by TestWS_GUI.EFA_WS.Service.PaketShemaAsync().
PaketStatusShema()
byte [] TestWS_GUI.EFA_WS.Service.PaketStatusShema () inline
PaketStatusShemaAsync() [1/2]
void TestWS_GUI.EFA_WS.Service.PaketStatusShemaAsync () inline
PaketStatusShemaAsync() [2/2]
void TestWS_GUI.EFA_WS.Service.PaketStatusShemaAsync (object userState) inline
References TestWS_GUI.EFA_WS.Service.OnPaketStatusShemaOperationCompleted(), and TestWS_GUI.EFA_WS.Service.PaketStatusShemaOperationCompleted.
OnPaketStatusShemaOperationCompleted()
void TestWS_GUI.EFA_WS.Service.OnPaketStatusShemaOperationCompleted (object arg) inline private
References TestWS_GUI.EFA_WS.Service.PaketStatusShemaCompleted.
Referenced by TestWS_GUI.EFA_WS.Service.PaketStatusShemaAsync().
PaketTipZalogaVrednosti()
System.Data.DataSet TestWS_GUI.EFA_WS.Service.PaketTipZalogaVrednosti () inline
PaketTipZalogaVrednostiAsync() [1/2]
void TestWS_GUI.EFA_WS.Service.PaketTipZalogaVrednostiAsync () inline
PaketTipZalogaVrednostiAsync() [2/2]
void TestWS_GUI.EFA_WS.Service.PaketTipZalogaVrednostiAsync (object userState) inline
References TestWS_GUI.EFA_WS.Service.OnPaketTipZalogaVrednostiOperationCompleted(), and TestWS_GUI.EFA_WS.Service.PaketTipZalogaVrednostiOperationCompleted.
OnPaketTipZalogaVrednostiOperationCompleted()
void TestWS_GUI.EFA_WS.Service.OnPaketTipZalogaVrednostiOperationCompleted (object arg) inline private
References TestWS_GUI.EFA_WS.Service.PaketTipZalogaVrednostiCompleted.
Referenced by TestWS_GUI.EFA_WS.Service.PaketTipZalogaVrednostiAsync().
PaketStatusZalogaVrednosti()
System.Data.DataSet TestWS_GUI.EFA_WS.Service.PaketStatusZalogaVrednosti () inline
PaketStatusZalogaVrednostiAsync() [1/2]
void TestWS_GUI.EFA_WS.Service.PaketStatusZalogaVrednostiAsync () inline
PaketStatusZalogaVrednostiAsync() [2/2]
void TestWS_GUI.EFA_WS.Service.PaketStatusZalogaVrednostiAsync (object userState) inline
References TestWS_GUI.EFA_WS.Service.OnPaketStatusZalogaVrednostiOperationCompleted(), and TestWS_GUI.EFA_WS.Service.PaketStatusZalogaVrednostiOperationCompleted.
OnPaketStatusZalogaVrednostiOperationCompleted()
void TestWS_GUI.EFA_WS.Service.OnPaketStatusZalogaVrednostiOperationCompleted (object arg) inline private
References TestWS_GUI.EFA_WS.Service.PaketStatusZalogaVrednostiCompleted.
Referenced by TestWS_GUI.EFA_WS.Service.PaketStatusZalogaVrednostiAsync().
PodrocjaZalogaVrednosti()
System.Data.DataSet TestWS_GUI.EFA_WS.Service.PodrocjaZalogaVrednosti () inline
PodrocjaZalogaVrednostiAsync() [1/2]
void TestWS_GUI.EFA_WS.Service.PodrocjaZalogaVrednostiAsync () inline
PodrocjaZalogaVrednostiAsync() [2/2]
void TestWS_GUI.EFA_WS.Service.PodrocjaZalogaVrednostiAsync (object userState) inline
References TestWS_GUI.EFA_WS.Service.OnPodrocjaZalogaVrednostiOperationCompleted(), and TestWS_GUI.EFA_WS.Service.PodrocjaZalogaVrednostiOperationCompleted.
OnPodrocjaZalogaVrednostiOperationCompleted()
void TestWS_GUI.EFA_WS.Service.OnPodrocjaZalogaVrednostiOperationCompleted (object arg) inline private
References TestWS_GUI.EFA_WS.Service.PodrocjaZalogaVrednostiCompleted.
Referenced by TestWS_GUI.EFA_WS.Service.PodrocjaZalogaVrednostiAsync().
CancelAsync()
new void TestWS_GUI.EFA_WS.Service.CancelAsync (object userState) inline
IsLocalFileSystemWebService()
bool TestWS_GUI.EFA_WS.Service.IsLocalFileSystemWebService (string url) inline private
Referenced by TestWS_GUI.EFA_WS.Service.Service().
Member Data Documentation
PosljiPaketOperationCompleted
System.Threading.SendOrPostCallback TestWS_GUI.EFA_WS.Service.PosljiPaketOperationCompleted private
Referenced by TestWS_GUI.EFA_WS.Service.PosljiPaketAsync().
PosljiPaketZipOperationCompleted
System.Threading.SendOrPostCallback TestWS_GUI.EFA_WS.Service.PosljiPaketZipOperationCompleted private
Referenced by TestWS_GUI.EFA_WS.Service.PosljiPaketZipAsync().
StevilkaSejeOperationCompleted
System.Threading.SendOrPostCallback TestWS_GUI.EFA_WS.Service.StevilkaSejeOperationCompleted private
Referenced by TestWS_GUI.EFA_WS.Service.StevilkaSejeAsync().
PaketStatusOperationCompleted
System.Threading.SendOrPostCallback TestWS_GUI.EFA_WS.Service.PaketStatusOperationCompleted private
Referenced by TestWS_GUI.EFA_WS.Service.PaketStatusAsync().
PaketShemaOperationCompleted
System.Threading.SendOrPostCallback TestWS_GUI.EFA_WS.Service.PaketShemaOperationCompleted private
Referenced by TestWS_GUI.EFA_WS.Service.PaketShemaAsync().
PaketStatusShemaOperationCompleted
System.Threading.SendOrPostCallback TestWS_GUI.EFA_WS.Service.PaketStatusShemaOperationCompleted private
Referenced by TestWS_GUI.EFA_WS.Service.PaketStatusShemaAsync().
PaketTipZalogaVrednostiOperationCompleted
System.Threading.SendOrPostCallback TestWS_GUI.EFA_WS.Service.PaketTipZalogaVrednostiOperationCompleted private
Referenced by TestWS_GUI.EFA_WS.Service.PaketTipZalogaVrednostiAsync().
PaketStatusZalogaVrednostiOperationCompleted
System.Threading.SendOrPostCallback TestWS_GUI.EFA_WS.Service.PaketStatusZalogaVrednostiOperationCompleted private
Referenced by TestWS_GUI.EFA_WS.Service.PaketStatusZalogaVrednostiAsync().
PodrocjaZalogaVrednostiOperationCompleted
System.Threading.SendOrPostCallback TestWS_GUI.EFA_WS.Service.PodrocjaZalogaVrednostiOperationCompleted private
Referenced by TestWS_GUI.EFA_WS.Service.PodrocjaZalogaVrednostiAsync().
useDefaultCredentialsSetExplicitly
bool TestWS_GUI.EFA_WS.Service.useDefaultCredentialsSetExplicitly private
Property Documentation
Url
new string TestWS_GUI.EFA_WS.Service.Url get set
Referenced by TestWS_GUI.EFA_WS.Service.Service().
UseDefaultCredentials
new bool TestWS_GUI.EFA_WS.Service.UseDefaultCredentials get set
Referenced by TestWS_GUI.EFA_WS.Service.Service().
Event Documentation
PosljiPaketCompleted
PosljiPaketCompletedEventHandler TestWS_GUI.EFA_WS.Service.PosljiPaketCompleted
Referenced by TestWS_GUI.EFA_WS.Service.OnPosljiPaketOperationCompleted().
PosljiPaketZipCompleted
PosljiPaketZipCompletedEventHandler TestWS_GUI.EFA_WS.Service.PosljiPaketZipCompleted
Referenced by TestWS_GUI.EFA_WS.Service.OnPosljiPaketZipOperationCompleted().
StevilkaSejeCompleted
StevilkaSejeCompletedEventHandler TestWS_GUI.EFA_WS.Service.StevilkaSejeCompleted
Referenced by TestWS_GUI.EFA_WS.Service.OnStevilkaSejeOperationCompleted().
PaketStatusCompleted
PaketStatusCompletedEventHandler TestWS_GUI.EFA_WS.Service.PaketStatusCompleted
Referenced by TestWS_GUI.EFA_WS.Service.OnPaketStatusOperationCompleted().
PaketShemaCompleted
PaketShemaCompletedEventHandler TestWS_GUI.EFA_WS.Service.PaketShemaCompleted
Referenced by TestWS_GUI.EFA_WS.Service.OnPaketShemaOperationCompleted().
PaketStatusShemaCompleted
PaketStatusShemaCompletedEventHandler TestWS_GUI.EFA_WS.Service.PaketStatusShemaCompleted
Referenced by TestWS_GUI.EFA_WS.Service.OnPaketStatusShemaOperationCompleted().
PaketTipZalogaVrednostiCompleted
PaketTipZalogaVrednostiCompletedEventHandler TestWS_GUI.EFA_WS.Service.PaketTipZalogaVrednostiCompleted
Referenced by TestWS_GUI.EFA_WS.Service.OnPaketTipZalogaVrednostiOperationCompleted().
PaketStatusZalogaVrednostiCompleted
PaketStatusZalogaVrednostiCompletedEventHandler TestWS_GUI.EFA_WS.Service.PaketStatusZalogaVrednostiCompleted
Referenced by TestWS_GUI.EFA_WS.Service.OnPaketStatusZalogaVrednostiOperationCompleted().
PodrocjaZalogaVrednostiCompleted
PodrocjaZalogaVrednostiCompletedEventHandler TestWS_GUI.EFA_WS.Service.PodrocjaZalogaVrednostiCompleted
Referenced by TestWS_GUI.EFA_WS.Service.OnPodrocjaZalogaVrednostiOperationCompleted().
The documentation for this class was generated from the following file:
igtest/tmp_prem/prefa/95_Test/TestWS_GUI/Web References/EFA_WS/Reference.cs