Doc: IGLib EXTENDED: NUnit.Common.AssemblyHelper Class Reference
NUnit.Common.AssemblyHelper Class Reference
AssemblyHelper provides static methods for working with assemblies.
Static Public Member Functions
static string GetAssemblyPath (Type type)
Gets the path from which the assembly defining a type was loaded.
static string GetAssemblyPath (Assembly assembly)
Gets the path from which an assembly was loaded.
static string GetDirectoryName (Assembly assembly)
Gets the path to the directory from which an assembly was loaded.
static AssemblyName GetAssemblyName (Assembly assembly)
Gets the AssemblyName of an assembly.
static Assembly Load (string nameOrPath)
Loads an assembly given a string, which may be the path to the assembly or the AssemblyName
static string GetAssemblyPathFromCodeBase (string codeBase)
Gets the assembly path from code base.
Static Private Member Functions
static bool IsFileUri (string uri)
Detailed Description
AssemblyHelper provides static methods for working with assemblies.
Member Function Documentation
GetAssemblyPath() [1/2]
static string NUnit.Common.AssemblyHelper.GetAssemblyPath (Type type) inline static
Gets the path from which the assembly defining a type was loaded.
Parameters
type The Type.
Returns
The path.
Referenced by NUnit.Framework.Api.DefaultTestAssemblyBuilder.Build(), NUnit.Common.Tests.AssemblyHelperTests.GetPathForAssembly(), and NUnit.Common.Tests.AssemblyHelperTests.GetPathForType().
GetAssemblyPath() [2/2]
static string NUnit.Common.AssemblyHelper.GetAssemblyPath (Assembly assembly) inline static
Gets the path from which an assembly was loaded.
Parameters
assembly The assembly.
Returns
The path.
GetDirectoryName()
static string NUnit.Common.AssemblyHelper.GetDirectoryName (Assembly assembly) inline static
Gets the path to the directory from which an assembly was loaded.
Parameters
assembly The assembly.
Returns
The path.
Referenced by NUnit.Framework.Internal.TestExecutionContextTests.CanCreateObjectInAppDomain().
GetAssemblyName()
static AssemblyName NUnit.Common.AssemblyHelper.GetAssemblyName (Assembly assembly) inline static
Gets the AssemblyName of an assembly.
Parameters
assembly The assembly
Returns
An AssemblyName
Referenced by NUnit.Framework.Api.DefaultTestAssemblyBuilder.Build(), NUnitLite.TextUI.DisplayHeader(), NUnitLite.TextRunner.Execute(), NUnit.Common.Tests.AssemblyHelperTests.GetNameForAssembly(), and NUnitLite.NUnit2XmlOutputWriter.WriteEnvironment().
Load()
static Assembly NUnit.Common.AssemblyHelper.Load (string nameOrPath) inline static
Loads an assembly given a string, which may be the path to the assembly or the AssemblyName
Parameters
nameOrPath
Returns
Referenced by NUnit.Framework.Api.DefaultTestAssemblyBuilder.Build(), and NUnitLite.TextRunner.Execute().
IsFileUri()
static bool NUnit.Common.AssemblyHelper.IsFileUri (string uri) inline static private
GetAssemblyPathFromCodeBase()
static string NUnit.Common.AssemblyHelper.GetAssemblyPathFromCodeBase (string codeBase) inline static
Gets the assembly path from code base.
Public for testing purposes
Parameters
codeBase The code base.
Returns
Referenced by NUnit.Common.Tests.AssemblyHelperTests.GetAssemblyPathFromCodeBase().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/Common/nunit/AssemblyHelper.cs