Doc: IGLib EXTENDED: NeuronDotNet.Core.Backpropagation.ActivationLayer Class Reference
NeuronDotNet.Core.Backpropagation.ActivationLayer Class Reference abstract
Activation Layer is a layer of activation neurons.
Public Member Functions
ActivationLayer (SerializationInfo info, StreamingContext context)
Deserialization Constructor
override void GetObjectData (SerializationInfo info, StreamingContext context)
Populates the serialization info with the data needed to serialize the layer
override void Initialize ()
Initializes all neurons and makes them ready to undergo training freshly.
double SetErrors (double[] expectedOutput)
Sets neuron errors as the difference between actual and expected outputs
void EvaluateErrors ()
Evaluate errors at all neurons in the layer
abstract double Activate (double input, double previousOutput)
Activation function used by all neurons in this layer
abstract double Derivative (double input, double output)
Derivative function used by all neurons in this layer
Public Member Functions inherited from NeuronDotNet.Core.Layer< ActivationNeuron >
virtual void SetInput (double[] input)
Sets neuron inputs to the values specified by the given array
virtual double[] GetOutput ()
Gets the neuron outputs as an array
void SetLearningRate (double learningRate)
Sets the learning rate to the given value. The layer will use this constant value as learning rate throughout the learning process
void SetLearningRate (double initialLearningRate, double finalLearningRate)
Sets the initial and final values for learning rate. During the learning process, the effective learning rate uniformly changes from its initial value to final value
void SetLearningRate (ILearningRateFunction learningRateFunction)
Sets the learning rate function.
virtual void Run ()
Runs all neurons in the layer.
virtual void Learn (int currentIteration, int trainingEpochs)
All neurons and their are source connectors are allowed to learn. This method assumes a learning environment where inputs, outputs and other parameters (if any) are appropriate.
Protected Member Functions
ActivationLayer (int neuronCount)
Constructs an instance of activation Layer
Protected Member Functions inherited from NeuronDotNet.Core.Layer< ActivationNeuron >
Layer (int neuronCount)
Creates a new layer
Layer (SerializationInfo info, StreamingContext context)
Deserialization Constructor
Properties
bool UseFixedBiasValues [get, set]
Gets or sets a boolean representing whether to use fixed neuron bias values
Properties inherited from NeuronDotNet.Core.Layer< ActivationNeuron >
int NeuronCount [get]
Gets the neuron count
IEnumerable< TNeuron > Neurons [get]
Exposes an enumerator to iterate over all neurons in the layer
IEnumerable< INeuron > ILayer. Neurons [get]
TNeuron this[int index] [get]
Neuron Indexer
INeuron ILayer. this[int index] [get]
IList< IConnector > SourceConnectors [get]
Gets the list of source connectors
IList< IConnector > TargetConnectors [get]
Gets the list of target connectors
IInitializer Initializer [get, set]
Gets or sets the Initializer used to initialize the layer
double LearningRate [get]
Gets the initial value of learning rate
ILearningRateFunction LearningRateFunction [get]
Gets the learning rate function
Additional Inherited Members
Protected Attributes inherited from NeuronDotNet.Core.Layer< ActivationNeuron >
readonly TNeuron[] neurons
Array of neurons in the layer. This is never null.
readonly List< IConnector > sourceConnectors
List of source connectors. This read-only value is never null.
readonly List< IConnector > targetConnectors
List of target connectors. This read-only value is never null.
ILearningRateFunction learningRateFunction
Learning Rate Function
IInitializer initializer
Initializer used to initialize the layer. If this value is null, neurons will have default values for initializable parameters (usually zero)
Detailed Description
Activation Layer is a layer of activation neurons.
Constructor & Destructor Documentation
ActivationLayer() [1/2]
NeuronDotNet.Core.Backpropagation.ActivationLayer.ActivationLayer (int neuronCount) inline protected
Constructs an instance of activation Layer
Parameters
neuronCount The number of neurons in the layer
Exceptions
ArgumentException If neuronCount is zero or negative
References NeuronDotNet.Core.Layer< ActivationNeuron >.neurons.
ActivationLayer() [2/2]
NeuronDotNet.Core.Backpropagation.ActivationLayer.ActivationLayer (SerializationInfo info, StreamingContext context) inline
Deserialization Constructor
Parameters
info Serialization information to deserialize and obtain the data
context Serialization context to use
Exceptions
ArgumentNullException If info is null
References NeuronDotNet.Core.Layer< ActivationNeuron >.neurons.
Member Function Documentation
GetObjectData()
override void NeuronDotNet.Core.Backpropagation.ActivationLayer.GetObjectData (SerializationInfo info, StreamingContext context) inline virtual
Populates the serialization info with the data needed to serialize the layer
Parameters
info The serialization info to populate the data with
context The serialization context to use
Exceptions
ArgumentNullException If info is null
Reimplemented from NeuronDotNet.Core.Layer< ActivationNeuron >.
References NeuronDotNet.Core.Layer< ActivationNeuron >.neurons.
Initialize()
override void NeuronDotNet.Core.Backpropagation.ActivationLayer.Initialize () inline virtual
Initializes all neurons and makes them ready to undergo training freshly.
Implements NeuronDotNet.Core.Layer< ActivationNeuron >.
References NeuronDotNet.Core.IInitializer.Initialize(), and NeuronDotNet.Core.Layer< ActivationNeuron >.initializer.
SetErrors()
double NeuronDotNet.Core.Backpropagation.ActivationLayer.SetErrors (double[] expectedOutput) inline
Sets neuron errors as the difference between actual and expected outputs
Parameters
expectedOutput Expected output vector
Returns
Mean squared error
Exceptions
ArgumentNullException If expectedOutput is null
ArgumentException If length of expectedOutput is different from the number of neurons
References NeuronDotNet.Core.Layer< ActivationNeuron >.neurons, and NeuronDotNet.Core.Helper.ValidateNotNull().
EvaluateErrors()
void NeuronDotNet.Core.Backpropagation.ActivationLayer.EvaluateErrors () inline
Evaluate errors at all neurons in the layer
References NeuronDotNet.Core.Layer< ActivationNeuron >.neurons.
Referenced by NeuronDotNet.Core.Backpropagation.BackpropagationNetwork.LearnSample().
Activate()
abstract double NeuronDotNet.Core.Backpropagation.ActivationLayer.Activate (double input, double previousOutput) pure virtual
Activation function used by all neurons in this layer
Parameters
input Current input to the neuron
previousOutput The previous output at the neuron
Returns
The activated value
Implemented in NeuronDotNet.Core.Backpropagation.LogarithmLayer, NeuronDotNet.Core.Backpropagation.SigmoidLayer, NeuronDotNet.Core.Backpropagation.SineLayer, NeuronDotNet.Core.Backpropagation.TanhLayer, and NeuronDotNet.Core.Backpropagation.LinearLayer.
Referenced by NeuronDotNet.Core.Backpropagation.ActivationNeuron.Run().
Derivative()
abstract double NeuronDotNet.Core.Backpropagation.ActivationLayer.Derivative (double input, double output) pure virtual
Derivative function used by all neurons in this layer
Parameters
input Current input to the neuron
output Current output (activated) at the neuron
Returns
The result of derivative of activation function
Implemented in NeuronDotNet.Core.Backpropagation.LogarithmLayer, NeuronDotNet.Core.Backpropagation.SigmoidLayer, NeuronDotNet.Core.Backpropagation.SineLayer, NeuronDotNet.Core.Backpropagation.TanhLayer, and NeuronDotNet.Core.Backpropagation.LinearLayer.
Referenced by NeuronDotNet.Core.Backpropagation.ActivationNeuron.EvaluateError().
Property Documentation
UseFixedBiasValues
bool NeuronDotNet.Core.Backpropagation.ActivationLayer.UseFixedBiasValues get set
Gets or sets a boolean representing whether to use fixed neuron bias values
A boolean indicating whether bias values of activation neurons learn while training.
The documentation for this class was generated from the following file:
shelldev/lib/externalextended/NeuronDotNetGPL/source/Core/Backpropagation/ActivationLayer.cs