Doc: IGLib EXTENDED: NUnit.Core.Tests.PairwiseTest.LiveTest Class Reference
NUnit.Core.Tests.PairwiseTest.LiveTest Class Reference
Public Member Functions
void TestFixtureSetUp ()
void TestFixtureTearDown ()
void Test ([Values("a", "b", "c")] string a, [Values("+", "-")] string b, [Values("x", "y")] string c)
Public Attributes
Hashtable pairsTested = new Hashtable()
Member Function Documentation
TestFixtureSetUp()
void NUnit.Core.Tests.PairwiseTest.LiveTest.TestFixtureSetUp () inline
References NUnit.Core.Tests.PairwiseTest.LiveTest.pairsTested.
TestFixtureTearDown()
void NUnit.Core.Tests.PairwiseTest.LiveTest.TestFixtureTearDown () inline
References NUnit.Framework.Is.EqualTo(), NUnit.Core.Tests.PairwiseTest.LiveTest.pairsTested, and NUnit.Framework.Assert.That().
Test()
void NUnit.Core.Tests.PairwiseTest.LiveTest.Test ([Values("a", "b", "c")] string a, [Values("+", "-")] string b, [Values("x", "y")] string c) inline
References NUnit.Core.Tests.PairwiseTest.LiveTest.pairsTested.
Member Data Documentation
pairsTested
Hashtable NUnit.Core.Tests.PairwiseTest.LiveTest.pairsTested = new Hashtable()
Referenced by NUnit.Core.Tests.PairwiseTest.LiveTest.Test(), NUnit.Core.Tests.PairwiseTest.LiveTest.TestFixtureSetUp(), and NUnit.Core.Tests.PairwiseTest.LiveTest.TestFixtureTearDown().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitEngine/Addins/nunit.v2.driver.tests/PairwiseTests.cs