Doc: IGLib EXTENDED: DotNumerics.LinearAlgebra.CSLapack.DGEQPF Class Reference
DotNumerics.LinearAlgebra.CSLapack.DGEQPF Class Reference
– LAPACK deprecated driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Public Member Functions
DGEQPF (DGEQR2 dgeqr2, DLARF dlarf, DLARFG dlarfg, DORM2R dorm2r, DSWAP dswap, XERBLA xerbla, IDAMAX idamax, DLAMCH dlamch, DNRM2 dnrm2)
DGEQPF ()
void Run (int M, int N, ref double[] A, int offset_a, int LDA, ref int[] JPVT, int offset_jpvt, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, ref int INFO)
Private Attributes
DGEQR2 _dgeqr2
DLARF _dlarf
DLARFG _dlarfg
DORM2R _dorm2r
DSWAP _dswap
XERBLA _xerbla
IDAMAX _idamax
DLAMCH _dlamch
DNRM2 _dnrm2
Static Private Attributes
const double ZERO = 0.0E+0
const double ONE = 1.0E+0
Detailed Description
– LAPACK deprecated driver routine (version 3.1) – Univ. of Tennessee, Univ. of California Berkeley and NAG Ltd.. November 2006
Purpose
This routine is deprecated and has been replaced by routine DGEQP3.
DGEQPF computes a QR factorization with column pivoting of a real M-by-N matrix A: A*P = Q*R.
/summary>
Constructor & Destructor Documentation
DGEQPF() [1/2]
DotNumerics.LinearAlgebra.CSLapack.DGEQPF.DGEQPF (DGEQR2 dgeqr2, DLARF dlarf, DLARFG dlarfg, DORM2R dorm2r, DSWAP dswap, XERBLA xerbla, IDAMAX idamax, DLAMCH dlamch, DNRM2 dnrm2) inline
DGEQPF() [2/2]
DotNumerics.LinearAlgebra.CSLapack.DGEQPF.DGEQPF () inline
Member Function Documentation
Run()
void DotNumerics.LinearAlgebra.CSLapack.DGEQPF.Run (int M, int N, ref double[] A, int offset_a, int LDA, ref int[] JPVT, int offset_jpvt, ref double[] TAU, int offset_tau, ref double[] WORK, int offset_work, ref int INFO) inline
Purpose
This routine is deprecated and has been replaced by routine DGEQP3.
DGEQPF computes a QR factorization with column pivoting of a real M-by-N matrix A: A*P = Q*R.
/summary>
Parameters
M (input) INTEGER The number of rows of the matrix A. M .GE. 0. /param>
Parameters
N (input) INTEGER The number of columns of the matrix A. N .GE. 0 /param>
Parameters
A (input/output) DOUBLE PRECISION array, dimension (LDA,N) On entry, the M-by-N matrix A. On exit, the upper triangle of the array contains the min(M,N)-by-N upper triangular matrix R; the elements below the diagonal, together with the array TAU, represent the orthogonal matrix Q as a product of min(m,n) elementary reflectors. /param>
Parameters
LDA (input) INTEGER The leading dimension of the array A. LDA .GE. max(1,M). /param>
Parameters
JPVT (input/output) INTEGER array, dimension (N) On entry, if JPVT(i) .ne. 0, the i-th column of A is permuted to the front of A*P (a leading column); if JPVT(i) = 0, the i-th column of A is a free column. On exit, if JPVT(i) = k, then the i-th column of A*P was the k-th column of A. /param>
Parameters
TAU (output) DOUBLE PRECISION array, dimension (min(M,N)) The scalar factors of the elementary reflectors. /param>
Parameters
WORK (workspace) DOUBLE PRECISION array, dimension (3*N) /param>
Parameters
INFO (output) INTEGER = 0: successful exit .LT. 0: if INFO = -i, the i-th argument had an illegal value /param>
References DotNumerics.LinearAlgebra.CSLapack.DGEQPF.ONE, DotNumerics.LinearAlgebra.CSLapack.DNRM2.Run(), DotNumerics.LinearAlgebra.CSLapack.DSWAP.Run(), DotNumerics.LinearAlgebra.CSLapack.IDAMAX.Run(), DotNumerics.LinearAlgebra.CSLapack.XERBLA.Run(), DotNumerics.LinearAlgebra.CSLapack.DLAMCH.Run(), DotNumerics.LinearAlgebra.CSLapack.DGEQR2.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARF.Run(), DotNumerics.LinearAlgebra.CSLapack.DLARFG.Run(), DotNumerics.LinearAlgebra.CSLapack.DORM2R.Run(), and DotNumerics.LinearAlgebra.CSLapack.DGEQPF.ZERO.
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGGSVP.Run().
Member Data Documentation
_dgeqr2
DGEQR2 DotNumerics.LinearAlgebra.CSLapack.DGEQPF._dgeqr2 private
_dlarf
DLARF DotNumerics.LinearAlgebra.CSLapack.DGEQPF._dlarf private
_dlarfg
DLARFG DotNumerics.LinearAlgebra.CSLapack.DGEQPF._dlarfg private
_dorm2r
DORM2R DotNumerics.LinearAlgebra.CSLapack.DGEQPF._dorm2r private
_dswap
DSWAP DotNumerics.LinearAlgebra.CSLapack.DGEQPF._dswap private
_xerbla
XERBLA DotNumerics.LinearAlgebra.CSLapack.DGEQPF._xerbla private
_idamax
IDAMAX DotNumerics.LinearAlgebra.CSLapack.DGEQPF._idamax private
_dlamch
DLAMCH DotNumerics.LinearAlgebra.CSLapack.DGEQPF._dlamch private
_dnrm2
DNRM2 DotNumerics.LinearAlgebra.CSLapack.DGEQPF._dnrm2 private
ZERO
const double DotNumerics.LinearAlgebra.CSLapack.DGEQPF.ZERO = 0.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEQPF.Run().
ONE
const double DotNumerics.LinearAlgebra.CSLapack.DGEQPF.ONE = 1.0E+0 static private
Referenced by DotNumerics.LinearAlgebra.CSLapack.DGEQPF.Run().
The documentation for this class was generated from the following file:
shelldev/lib/external/LAPack/LAPack/dgeqpf.cs