Doc: IGLib EXTENDED: NUnit.Framework.Constraints.ComparisonAdapter Class Reference
NUnit.Framework.Constraints.ComparisonAdapter Class Reference abstract
ComparisonAdapter class centralizes all comparisons of _values in NUnit, adapting to the use of any provided IComparer, IComparer<T> or Comparison<T>.
Classes
class ComparerAdapter
ComparerAdapter extends ComparisonAdapter and allows use of an IComparer<T> or Comparison<T> to actually perform the comparison.
class ComparerAdapter
class ComparisonAdapterForComparison
class DefaultComparisonAdapter
Public Member Functions
abstract int Compare (object expected, object actual)
Compares two objects
Static Public Member Functions
static ComparisonAdapter For (IComparer comparer)
Returns a ComparisonAdapter that wraps an IComparer
static ComparisonAdapter For< T > (IComparer< T > comparer)
Returns a ComparisonAdapter that wraps an IComparer<T>
static ComparisonAdapter For< T > (Comparison< T > comparer)
Returns a ComparisonAdapter that wraps a Comparison<T>
Properties
static ComparisonAdapter Default [get]
Gets the default ComparisonAdapter, which wraps an NUnitComparer object.
Detailed Description
ComparisonAdapter class centralizes all comparisons of _values in NUnit, adapting to the use of any provided IComparer, IComparer<T> or Comparison<T>.
Member Function Documentation
For()
static ComparisonAdapter NUnit.Framework.Constraints.ComparisonAdapter.For (IComparer comparer) inline static
Returns a ComparisonAdapter that wraps an IComparer
Referenced by NUnit.Framework.Constraints.CollectionOrderedConstraint.Using(), NUnit.Framework.Constraints.RangeConstraint.Using(), NUnit.Framework.Constraints.ComparisonConstraint.Using(), NUnit.Framework.Constraints.CollectionOrderedConstraint.Using< T >(), NUnit.Framework.Constraints.RangeConstraint.Using< T >(), and NUnit.Framework.Constraints.ComparisonConstraint.Using< T >().
For< T >() [1/2]
static ComparisonAdapter NUnit.Framework.Constraints.ComparisonAdapter.For< T > (IComparer< T > comparer) inline static
Returns a ComparisonAdapter that wraps an IComparer<T>
For< T >() [2/2]
static ComparisonAdapter NUnit.Framework.Constraints.ComparisonAdapter.For< T > (Comparison< T > comparer) inline static
Returns a ComparisonAdapter that wraps a Comparison<T>
Compare()
abstract int NUnit.Framework.Constraints.ComparisonAdapter.Compare (object expected, object actual) pure virtual
Compares two objects
Implemented in NUnit.Framework.Constraints.ComparisonAdapter.ComparisonAdapterForComparison< T >, NUnit.Framework.Constraints.ComparisonAdapter.ComparerAdapter< T >, and NUnit.Framework.Constraints.ComparisonAdapter.ComparerAdapter< T >.
Referenced by NUnit.Framework.Constraints.RangeConstraint.ApplyTo< TActual >(), NUnit.Framework.Constraints.ComparisonConstraint.ApplyTo< TActual >(), NUnit.Framework.Constraints.CollectionOrderedConstraint.Matches(), and NUnit.Framework.Constraints.RangeConstraint.RangeConstraint().
Property Documentation
Default
ComparisonAdapter NUnit.Framework.Constraints.ComparisonAdapter.Default static get
Gets the default ComparisonAdapter, which wraps an NUnitComparer object.
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/framework/Constraints/ComparisonAdapter.cs