Doc: IGLib EXTENDED: alglib.testalglibbasicsunit.poolrec2 Class Reference
alglib.testalglibbasicsunit.poolrec2 Class Reference
Public Member Functions
poolrec2 ()
override void init ()
override alglib.apobject make_copy ()
Public Attributes
bool bval
poolrec1 recval
alglib.smp.shared_pool pool
Constructor & Destructor Documentation
poolrec2()
alglib.testalglibbasicsunit.poolrec2.poolrec2 () inline
References alglib.testalglibbasicsunit.poolrec2.init().
Referenced by alglib.testalglibbasicsunit.poolrec2.make_copy().
Member Function Documentation
init()
override void alglib.testalglibbasicsunit.poolrec2.init () inline virtual
Implements alglib.apobject.
References alglib.testalglibbasicsunit.poolrec2.pool, and alglib.testalglibbasicsunit.poolrec2.recval.
Referenced by alglib.testalglibbasicsunit.poolrec2.poolrec2().
make_copy()
override alglib.apobject alglib.testalglibbasicsunit.poolrec2.make_copy () inline virtual
Implements alglib.apobject.
References alglib.testalglibbasicsunit.poolrec2.bval, alglib.testalglibbasicsunit.poolrec1.make_copy(), alglib.testalglibbasicsunit.poolrec2.pool, alglib.testalglibbasicsunit.poolrec2.poolrec2(), and alglib.testalglibbasicsunit.poolrec2.recval.
Member Data Documentation
bval
bool alglib.testalglibbasicsunit.poolrec2.bval
Referenced by alglib.testalglibbasicsunit.createpoolandrecords(), alglib.testalglibbasicsunit.poolrec2.make_copy(), and alglib.testalglibbasicsunit.sharedpoolerrors().
recval
poolrec1 alglib.testalglibbasicsunit.poolrec2.recval
Referenced by alglib.testalglibbasicsunit.createpoolandrecords(), alglib.testalglibbasicsunit.poolrec2.init(), alglib.testalglibbasicsunit.poolrec2.make_copy(), and alglib.testalglibbasicsunit.sharedpoolerrors().
pool
alglib.smp.shared_pool alglib.testalglibbasicsunit.poolrec2.pool
Referenced by alglib.testalglibbasicsunit.poolrec2.init(), alglib.testalglibbasicsunit.poolrec2.make_copy(), and alglib.testalglibbasicsunit.sharedpoolerrors().
The documentation for this class was generated from the following file:
igtest/numerics/alglib_0.8.2/tests/test_c.cs