Doc: IGLib EXTENDED: NUnit.Framework.Internal.MixedResultTests Class Reference
NUnit.Framework.Internal.MixedResultTests Class Reference
Public Member Functions
void SuiteResultIsFailure ()
void SuiteResultXmlNodeIsFailure ()
void SuiteResultXmlNodeHasFourChildTests ()
Public Member Functions inherited from NUnit.Framework.Internal.TestResultTests
void SetUp ()
void TestResultBasicInfo ()
void SuiteResultBasicInfo ()
void TestResultXmlNodeBasicInfo ()
void SuiteResultXmlNodeBasicInfo ()
Protected Member Functions
override void SimulateTestRun ()
Additional Inherited Members
Protected Attributes inherited from NUnit.Framework.Internal.TestResultTests
TestResult testResult
TestResult suiteResult
TestMethod test
double expectedDuration
DateTime expectedStart
DateTime expectedEnd
Properties inherited from NUnit.Framework.Internal.TestResultTests
virtual ResultState ResultState [get]
virtual string ReasonNodeName [get]
Member Function Documentation
SimulateTestRun()
override void NUnit.Framework.Internal.MixedResultTests.SimulateTestRun () inline protected virtual
Implements NUnit.Framework.Internal.TestResultTests.
References NUnit.Framework.Internal.TestResult.AddResult(), NUnit.Framework.Internal.TestResult.AssertCount, NUnit.Framework.Interfaces.ResultState.Failure, NUnit.Framework.Interfaces.ResultState.Inconclusive, NUnit.Framework.Internal.TestResult.SetResult(), NUnit.Framework.Interfaces.ResultState.Success, NUnit.Framework.Internal.TestResultTests.suiteResult, and NUnit.Framework.Internal.TestResultTests.testResult.
SuiteResultIsFailure()
void NUnit.Framework.Internal.MixedResultTests.SuiteResultIsFailure () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Internal.TestResult.AssertCount, NUnit.Framework.Interfaces.ResultState.ChildFailure, NUnit.Framework.Is.EqualTo(), NUnit.Framework.Internal.TestResult.FailCount, NUnit.Framework.Internal.TestResult.InconclusiveCount, NUnit.Framework.Internal.TestResult.Message, NUnit.Framework.Assert.Null(), NUnit.Framework.Internal.TestResult.PassCount, NUnit.Framework.Internal.TestResult.ResultState, NUnit.Framework.Interfaces.ResultState.Site, NUnit.Framework.Internal.TestResult.SkipCount, NUnit.Framework.Internal.TestResult.StackTrace, NUnit.Framework.Interfaces.ResultState.Status, NUnit.Framework.Internal.TestResultTests.suiteResult, and NUnit.Framework.Assert.That().
SuiteResultXmlNodeIsFailure()
void NUnit.Framework.Internal.MixedResultTests.SuiteResultXmlNodeIsFailure () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.TNode.Attributes, NUnit.Framework.Assert.NotNull(), NUnit.Framework.Assert.Null(), NUnit.Framework.Interfaces.TNode.SelectSingleNode(), NUnit.Framework.Internal.TestResultTests.suiteResult, NUnit.Framework.Internal.TestResult.ToXml(), and NUnit.Framework.Interfaces.TNode.Value.
SuiteResultXmlNodeHasFourChildTests()
void NUnit.Framework.Internal.MixedResultTests.SuiteResultXmlNodeHasFourChildTests () inline
References NUnit.Framework.Assert.AreEqual(), NUnit.Framework.Interfaces.TNode.SelectNodes(), NUnit.Framework.Internal.TestResultTests.suiteResult, and NUnit.Framework.Internal.TestResult.ToXml().
The documentation for this class was generated from the following file:
unittests/NUnit_3_0_1_src/src/NUnitFramework/tests/Internal/TestResultTests.cs