Doc: IGLib EXTENDED: AForge.Robotics.Lego.RCXBrick Class Reference
AForge.Robotics.Lego.RCXBrick Class Reference
Manipulation of Lego Mindstorms RCX device.
Public Types
enum IRTowerType { IRTowerType.USB, IRTowerType.Serial }
Type of IR tower used for communication with RCX.
enum SoundType {
SoundType.Blip, SoundType.BeepBeep, SoundType.DownwardTones, SoundType.UpwardTones,
SoundType.LowBuzz, SoundType.FastUpwardTones
}
Enumeration of sound type playable by Lego RCX brick.
enum Sensor { Sensor.First, Sensor.Second, Sensor.Third }
Enumeration of RCX brick sensor ports.
enum SensorType {
SensorType.Raw, SensorType.Touch, SensorType.Temperatur, SensorType.Light,
SensorType.Rotation
}
Enumeration of RCX brick sensor types.
enum SensorMode {
SensorMode.Raw, SensorMode.Boolean, SensorMode.EdgeCount, SensorMode.PulseCount,
SensorMode.Percentage, SensorMode.TemperatureC, SensorMode.TemperatureF, SensorMode.Angle
}
Enumeration of RCX brick sensor modes.
enum Motor {
Motor.A = 1, Motor.B = 2, Motor.C = 4, Motor.AB = 3,
Motor.AC = 5, Motor.BC = 6, Motor.ABC = 7, Motor.All = 7
}
Enumeration of RCX brick motor ports.
Public Member Functions
RCXBrick ()
Initializes a new instance of the RCXBrick class.
bool Connect (IRTowerType towerType)
Connect to Lego RCX brick.
void Disconnect ()
Disconnnect from Lego RCX brick.
bool IsAlive ()
Check if the RCX brick is alive and responds to messages.
bool PlaySound (SoundType type)
Play one of supported sounds.
bool PlayTone (short frequency, byte duration)
Play tone of specified frequency.
bool GetVersion (out string romVersion, out string firmwareVersion)
Get version information of RCX brick.
bool GetBatteryPower (out int power)
Get battery power of RCX brick.
bool SetTime (byte hours, byte minutes)
Set current time for the RCX brick.
bool PowerOff ()
Turn off the RCX brick.
bool GetSensorValue (Sensor sensor, out short value)
Get sensor's value.
bool SetSensorType (Sensor sensor, SensorType type)
Set sensor's type.
bool SetSensorMode (Sensor sensor, SensorMode mode)
Set sensor's mode.
bool ClearSensor (Sensor sensor)
Clear the counter associated with the specified sensor by setting it to a value of zero.
bool SetMotorOn (Motor motors, bool on)
Turn on/off specified motors.
bool SetMotorPower (Motor motors, byte power)
Set power of specified motors.
bool SetMotorDirection (Motor motors, bool isForward)
Set direction of specified motors.
bool SetTransmitterRange (bool isLongRange)
Set IR transmitter's range.
Protected Member Functions
bool SendCommand (byte[] command, byte[] reply, int expectedReplyLen)
Send command to Lego RCX brick and read reply.
Properties
bool IsConnected [get]
Check if connection to RCX brick is established.
Private Member Functions
~RCXBrick ()
Destroys the instance of the RCXBrick class.
Private Attributes
IntPtr stack
object sync = new object()
Detailed Description
Manipulation of Lego Mindstorms RCX device.
The class allows to manipulate with Lego Mindstorms RCX device, setting its motors' state, getting information about sensors' values and performing some other manipulations.
<note>The class supports both types of IR towers - USB and serial (see RCXBrick.IRTowerType).</note>
<note>The class uses GhostAPI to communicate with Lego RCX device, so its libraries (GhostAPI.dll, PbkComm32.dll and PbkUsbPort.dll) should be placed into applications folder.</note>
Sample usage:
// create an instance of RCX brick
RCXBrick rcx = new RCXBrick();
// connect to the device
if (rcx.Connect(RCXBrick.IRTowerType.USB))
{
    // set forward direction of motor A
    rcx.SetMotorDirection( RCXBrick.Motor.A, true );
    // set power of motor
    rcx.SetMotorPower( RCXBrick.Motor.A, 1 );
    // turm motor on
    rcx.SetMotorOn( RCXBrick.Motor.A, true );
    // ...
    // turn off motors A, B and C
    rcx.SetMotorOn( RCXBrick.Motor.ABC, false );
    // get first sensor's value
    short value;
    if ( rcx.GetSensorValue( RCXBrick.Sensor.First, out value ) )
    {
        // ...
    }
    // ...
}
Member Enumeration Documentation
IRTowerType
enum AForge.Robotics.Lego.RCXBrick.IRTowerType strong
Type of IR tower used for communication with RCX.
Enumerator
USB
USB IR tower.
Serial
RS232 IR tower.
SoundType
enum AForge.Robotics.Lego.RCXBrick.SoundType strong
Enumeration of sound type playable by Lego RCX brick.
Enumerator
Blip
Blip sound.
BeepBeep
Double beep spund.
DownwardTones
Downward tones sound.
UpwardTones
Upward tones sound.
LowBuzz
Low buzz sound.
FastUpwardTones
Fast upward tones sound.
Sensor
enum AForge.Robotics.Lego.RCXBrick.Sensor strong
Enumeration of RCX brick sensor ports.
Enumerator
First
First sensor.
Second
Second sensor.
Third
Third sensor.
SensorType
enum AForge.Robotics.Lego.RCXBrick.SensorType strong
Enumeration of RCX brick sensor types.
Use SetSensorType method to set RCX sensor's type.
Enumerator
Raw
Raw sensor.
Touch
Touch sensor (default mode is boolean).
Temperatur
Temperature sensor (default mode is temperature in °C).
Light
Light sensor (default mode is percentage).
Rotation
Rotation sensor (default mode is angle).
SensorMode
enum AForge.Robotics.Lego.RCXBrick.SensorMode strong
Enumeration of RCX brick sensor modes.
Use SetSensorMode method to set RCX sensor's mode.
Enumerator
Raw
Raw mode - value in [0, 1023].
Boolean
Boolean - either 0 or 1.
EdgeCount
Number of boolean transitions.
PulseCount
Number of boolean transitions divided by two.
Percentage
Raw value scaled to [0, 100].
TemperatureC
Temperature in °C - 1/10ths of a degree, [-19.8, 69.5].
TemperatureF
Temperature in °F - 1/10ths of a degree, [-3.6, 157.1].
Angle
Angle - 1/16ths of a rotation, represented as a signed short.
Motor
enum AForge.Robotics.Lego.RCXBrick.Motor strong
Enumeration of RCX brick motor ports.
Enumerator
A
Motor A.
B
Motor B.
C
Motor C.
AB
Motors A and B.
AC
Motors A and C.
BC
Motors B and C.
ABC
Motors A, B and C.
All
All motors (A, B and C).
Constructor & Destructor Documentation
RCXBrick()
AForge.Robotics.Lego.RCXBrick.RCXBrick () inline
Initializes a new instance of the RCXBrick class.
~RCXBrick()
AForge.Robotics.Lego.RCXBrick.~RCXBrick () inline private
Destroys the instance of the RCXBrick class.
References AForge.Robotics.Lego.RCXBrick.Disconnect().
Member Function Documentation
Connect()
bool AForge.Robotics.Lego.RCXBrick.Connect (IRTowerType towerType) inline
Connect to Lego RCX brick.
Parameters
towerType Type of IR tower to use for communication with RCX brick.
Returns
Returns true on successful connection or false otherwise.
If connection to RCX brick was established before the call, existing connection will be reused. If it is required to force reconnection, then Disconnect method should be called before.
References AForge.Robotics.Lego.RCXBrick.Disconnect(), AForge.Robotics.Lego.RCXBrick.IsAlive(), AForge.Robotics.Lego.RCXBrick.stack, and AForge.Robotics.Lego.RCXBrick.sync.
Referenced by RCXTest.MainForm.connectButton_Click().
Disconnect()
void AForge.Robotics.Lego.RCXBrick.Disconnect () inline
Disconnnect from Lego RCX brick.
References AForge.Robotics.Lego.RCXBrick.stack, and AForge.Robotics.Lego.RCXBrick.sync.
Referenced by AForge.Robotics.Lego.RCXBrick.Connect(), RCXTest.MainForm.disconnectButton_Click(), RCXTest.MainForm.turnDeviceOffButton_Click(), and AForge.Robotics.Lego.RCXBrick.~RCXBrick().
IsAlive()
bool AForge.Robotics.Lego.RCXBrick.IsAlive () inline
Check if the RCX brick is alive and responds to messages.
Returns
Returns true if device is alive or false otherwise.
References AForge.Robotics.Lego.RCXBrick.SendCommand().
Referenced by AForge.Robotics.Lego.RCXBrick.Connect().
PlaySound()
bool AForge.Robotics.Lego.RCXBrick.PlaySound (SoundType type) inline
Play one of supported sounds.
Parameters
type Sound type to play.
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.RCXBrick.SendCommand().
Referenced by RCXTest.MainForm.playButton_Click().
PlayTone()
bool AForge.Robotics.Lego.RCXBrick.PlayTone (short frequency, byte duration) inline
Play tone of specified frequency.
Parameters
frequency Tone frequency in Hz.
duration Tone duration in 1/100ths of a second.
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.RCXBrick.SendCommand().
GetVersion()
bool AForge.Robotics.Lego.RCXBrick.GetVersion (out string romVersion, out string firmwareVersion) inline
Get version information of RCX brick.
Parameters
romVersion ROM version number.
firmwareVersion Firmware version number.
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.RCXBrick.SendCommand().
Referenced by RCXTest.MainForm.connectButton_Click().
GetBatteryPower()
bool AForge.Robotics.Lego.RCXBrick.GetBatteryPower (out int power) inline
Get battery power of RCX brick.
Parameters
power RCX brick's battery power in millivolts.
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.RCXBrick.SendCommand().
Referenced by RCXTest.MainForm.connectButton_Click().
SetTime()
bool AForge.Robotics.Lego.RCXBrick.SetTime (byte hours, byte minutes) inline
Set current time for the RCX brick.
Parameters
hours Hours, [0..23].
minutes Minutes, [0..59].
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.RCXBrick.SendCommand().
PowerOff()
bool AForge.Robotics.Lego.RCXBrick.PowerOff () inline
Turn off the RCX brick.
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.RCXBrick.SendCommand().
Referenced by RCXTest.MainForm.turnDeviceOffButton_Click().
GetSensorValue()
bool AForge.Robotics.Lego.RCXBrick.GetSensorValue (Sensor sensor, out short value) inline
Get sensor's value.
Parameters
sensor Sensor to get value of.
value Retrieved sensor's value (units depend on current sensor's type and mode).
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.RCXBrick.SendCommand().
Referenced by RCXTest.MainForm.getValueButton_Click().
SetSensorType()
bool AForge.Robotics.Lego.RCXBrick.SetSensorType (Sensor sensor, SensorType type) inline
Set sensor's type.
Parameters
sensor Sensor to set type of.
type Sensor type to set.
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.RCXBrick.SendCommand().
Referenced by RCXTest.MainForm.setSensorTypeButton_Click().
SetSensorMode()
bool AForge.Robotics.Lego.RCXBrick.SetSensorMode (Sensor sensor, SensorMode mode) inline
Set sensor's mode.
Parameters
sensor Sensor to set mode of.
mode Sensor mode to set.
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.RCXBrick.SendCommand().
Referenced by RCXTest.MainForm.setSensorModeButton_Click().
ClearSensor()
bool AForge.Robotics.Lego.RCXBrick.ClearSensor (Sensor sensor) inline
Clear the counter associated with the specified sensor by setting it to a value of zero.
Parameters
sensor Sensor to clear value of.
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.RCXBrick.SendCommand().
Referenced by RCXTest.MainForm.clearSensorButton_Click().
SetMotorOn()
bool AForge.Robotics.Lego.RCXBrick.SetMotorOn (Motor motors, bool on) inline
Turn on/off specified motors.
Parameters
motors Motors to turn on/off.
on True to turn motors on, otherwise false.
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.RCXBrick.SendCommand().
Referenced by RCXTest.MainForm.motorOffButton_Click(), and RCXTest.MainForm.motorOnButton_Click().
SetMotorPower()
bool AForge.Robotics.Lego.RCXBrick.SetMotorPower (Motor motors, byte power) inline
Set power of specified motors.
Parameters
motors Motors to set power of.
power Power level to set, [0..7].
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.RCXBrick.SendCommand().
Referenced by RCXTest.MainForm.motorOnButton_Click().
SetMotorDirection()
bool AForge.Robotics.Lego.RCXBrick.SetMotorDirection (Motor motors, bool isForward) inline
Set direction of specified motors.
Parameters
motors Motors to set direction of.
isForward True to set forward direction, false to set backward.
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.RCXBrick.SendCommand().
Referenced by RCXTest.MainForm.motorOnButton_Click().
SetTransmitterRange()
bool AForge.Robotics.Lego.RCXBrick.SetTransmitterRange (bool isLongRange) inline
Set IR transmitter's range.
Parameters
isLongRange True if long range should be set, otherwise false.
Returns
Returns true if command was executed successfully or false otherwise.
References AForge.Robotics.Lego.RCXBrick.SendCommand().
Referenced by RCXTest.MainForm.connectButton_Click().
SendCommand()
bool AForge.Robotics.Lego.RCXBrick.SendCommand (byte[] command, byte[] reply, int expectedReplyLen) inline protected
Send command to Lego RCX brick and read reply.
Parameters
command Command to send.
reply Buffer to receive reply into.
expectedReplyLen Expected reply length.
Returns
Returns true if the command was sent successfully and reply was received, otherwise false.
Exceptions
NullReferenceException Communication can not be performed, because connection with RCX brick was not established yet.
ArgumentException Reply buffer size is smaller than the reply data size.
ApplicationException Reply does not correspond to command (first byte of reply should be complement (bitwise NOT) to the first byte of command orred with 0x08).
References AForge.Robotics.Lego.RCXBrick.stack, and AForge.Robotics.Lego.RCXBrick.sync.
Referenced by AForge.Robotics.Lego.RCXBrick.ClearSensor(), AForge.Robotics.Lego.RCXBrick.GetBatteryPower(), AForge.Robotics.Lego.RCXBrick.GetSensorValue(), AForge.Robotics.Lego.RCXBrick.GetVersion(), AForge.Robotics.Lego.RCXBrick.IsAlive(), AForge.Robotics.Lego.RCXBrick.PlaySound(), AForge.Robotics.Lego.RCXBrick.PlayTone(), AForge.Robotics.Lego.RCXBrick.PowerOff(), AForge.Robotics.Lego.RCXBrick.SetMotorDirection(), AForge.Robotics.Lego.RCXBrick.SetMotorOn(), AForge.Robotics.Lego.RCXBrick.SetMotorPower(), AForge.Robotics.Lego.RCXBrick.SetSensorMode(), AForge.Robotics.Lego.RCXBrick.SetSensorType(), AForge.Robotics.Lego.RCXBrick.SetTime(), and AForge.Robotics.Lego.RCXBrick.SetTransmitterRange().
Member Data Documentation
stack
IntPtr AForge.Robotics.Lego.RCXBrick.stack private
Referenced by AForge.Robotics.Lego.RCXBrick.Connect(), AForge.Robotics.Lego.RCXBrick.Disconnect(), and AForge.Robotics.Lego.RCXBrick.SendCommand().
sync
object AForge.Robotics.Lego.RCXBrick.sync = new object() private
Referenced by AForge.Robotics.Lego.RCXBrick.Connect(), AForge.Robotics.Lego.RCXBrick.Disconnect(), and AForge.Robotics.Lego.RCXBrick.SendCommand().
Property Documentation
IsConnected
bool AForge.Robotics.Lego.RCXBrick.IsConnected get
Check if connection to RCX brick is established.
The documentation for this class was generated from the following file:
shelldev/lib_ann/aforge.net/Sources/Robotics.Lego/RCXBrick.cs